OpenFOAM: applications/solvers/acoustic/acousticFoam/createRegionControls.H File Reference
createRegionControls.H File Reference
Functions
fvSolution solutionDict (runTime)
bool solvePrimaryRegion (pimpleDict.getOrDefault("solvePrimaryRegion", true))
Variables
const dictionary & pimpleDict = solutionDict.subDict("PIMPLE")
Function Documentation
solutionDict()
fvSolution solutionDict (runTime)
Referenced by solution::read(), and solutionControl::read().
solvePrimaryRegion()
bool solvePrimaryRegion (pimpleDict. getOrDefault"solvePrimaryRegion", true)
Variable Documentation
pimpleDict
const dictionary& pimpleDict = solutionDict.subDict("PIMPLE")
Definition at line 3 of file createRegionControls.H.
Referenced by forAll(), and pimpleControl::read().