OpenFOAM: applications/utilities/postProcessing/miscellaneous/postChannel/readFields.H File Reference
readFields.H File Reference
Functions
IOobject UMeanHeader ("UMean", runTime.timeName(), mesh, IOobject::MUST_READ)
if (!UMeanHeader.typeHeaderOk< volVectorField >(true))
volVectorField UMean (UMeanHeader, mesh)
volSymmTensorField UPrime2Mean (IOobject("UPrime2Mean", runTime.timeName(), mesh, IOobject::MUST_READ), mesh)
volScalarField Rxx (UPrime2Mean.component(symmTensor::XX))
volScalarField Ryy (UPrime2Mean.component(symmTensor::YY))
volScalarField Rzz (UPrime2Mean.component(symmTensor::ZZ))
volScalarField Rxy (UPrime2Mean.component(symmTensor::XY))
volScalarField pPrime2Mean (IOobject("pPrime2Mean", runTime.timeName(), mesh, IOobject::MUST_READ), mesh)
Function Documentation
UMeanHeader()
IOobject UMeanHeader ("UMean" , runTime. timeName(), mesh , IOobject::MUST_READ)
if()
if (!UMeanHeader.typeHeaderOk< volVectorField > true)
Definition at line 9 of file readFields.H.
UMean()
volVectorField UMean (UMeanHeader , mesh)
Referenced by PopeIndex::execute(), turbulentDFSEMInletFvPatchVectorField::updateCoeffs(), and dsmcFields::write().
UPrime2Mean()
volSymmTensorField UPrime2Mean (IOobject("UPrime2Mean", runTime.timeName(), mesh, IOobject::MUST_READ) , mesh)
Rxx()
volScalarField Rxx (UPrime2Mean. componentsymmTensor::XX)
Ryy()
volScalarField Ryy (UPrime2Mean. componentsymmTensor::YY)
Rzz()
volScalarField Rzz (UPrime2Mean. componentsymmTensor::ZZ)
Rxy()
volScalarField Rxy (UPrime2Mean. componentsymmTensor::XY)
pPrime2Mean()
volScalarField pPrime2Mean (IOobject("pPrime2Mean", runTime.timeName(), mesh, IOobject::MUST_READ) , mesh)