OpenFOAM: applications/utilities/postProcessing/lagrangian/particleTracks/createControls.H File Reference
createControls.H File Reference
Functions
const word dictName ("particleTrackProperties")
IOdictionary propsDict (dictIO)
const word cloudName (propsDict.get< word >("cloud"))
label sampleFrequency (propsDict.get< label >("sampleFrequency"))
label maxPositions (propsDict.get< label >("maxPositions"))
label maxTracks (propsDict.getOrDefault< label >("maxTracks", -1))
word setFormat (propsDict.getOrDefault< word >("setFormat", "vtk"))
propsDict readIfPresent ("fields", acceptFields)
propsDict readIfPresent ("exclude", excludeFields)
const word UName (propsDict.getOrDefault< word >("U", "U"))
const dictionary formatOptions (propsDict.subOrEmptyDict("formatOptions", keyType::LITERAL))
Variables
wordRes acceptFields
wordRes excludeFields
Function Documentation
dictName()
const word dictName ("particleTrackProperties")
propsDict()
IOdictionary propsDict (dictIO)
Referenced by directionalPressureGradientExplicitSource::directionalPressureGradientExplicitSource(), fanMomentumSource::fanMomentumSource(), meanVelocityForce::meanVelocityForce(), functionObjectList::triggerIndex(), fieldAverage::writeAveragingProperties(), meanVelocityForce::writeProps(), streamLineBase::writeToFile(), and surfaceFieldValue::writeValues().
cloudName()
const word cloudName (propsDict.get< word > "cloud")
Referenced by Relaxation< CloudType >::cacheFields(), Explicit< CloudType >::cacheFields(), Implicit< CloudType >::cacheFields(), lagrangianFieldDecomposer::decomposeField(), lagrangianFieldDecomposer::decomposeFieldField(), lagrangianFieldDecomposer::decomposeFieldFields(), lagrangianFieldDecomposer::decomposeFields(), if(), if(), Foam::MapLagrangianFields(), Foam::MapLagrangianFields(), ensightCase::newCloud(), ensightCase::newCloudData(), cloudInfo::performAction(), lagrangianReconstructor::reconstructField(), lagrangianReconstructor::reconstructFieldField(), lagrangianReconstructor::reconstructFieldFields(), lagrangianReconstructor::reconstructFields(), lagrangianReconstructor::reconstructFields(), Foam::reconstructLagrangian(), lagrangianReconstructor::reconstructPositions(), dataCloud::write(), vtkCloud::write(), ensightCase::write(), and Foam::ensightOutput::writeCloudPositions().
sampleFrequency()
label sampleFrequency (propsDict.get< label > "sampleFrequency")
maxPositions()
label maxPositions (propsDict.get< label > "maxPositions")
Referenced by particleTracksSampler::setSampleRate().
maxTracks()
label maxTracks (propsDict.getOrDefault< label > "maxTracks", -1)
Referenced by particleTracksSampler::setSampleRate().
setFormat()
word setFormat (propsDict.getOrDefault< word > "setFormat", "vtk")
Referenced by particleDistribution::read(), regionSizeDistribution::read(), and streamLineBase::read().
readIfPresent() [1/2]
propsDict readIfPresent ("fields" , acceptFields)
readIfPresent() [2/2]
propsDict readIfPresent ("exclude" , excludeFields)
UName()
const word UName (propsDict.getOrDefault< word > "U", "U")
Referenced by heatExchangerSource::addSup(), dynamicRefineFvMesh::mapFields(), dynamicRefineFvMesh::unrefine(), fanPressureFvPatchScalarField::updateCoeffs(), rotatingTotalPressureFvPatchScalarField::updateCoeffs(), and totalPressureFvPatchScalarField::updateCoeffs().
formatOptions()
const dictionary formatOptions (propsDict. subOrEmptyDict"formatOptions", keyType::LITERAL)
Referenced by VTKsurfaceFormat< Face >::write(), VTPsurfaceFormat< Face >::write(), VTKsurfaceFormat< Face >::write(), and VTPsurfaceFormat< Face >::write().
Variable Documentation
acceptFields
wordRes acceptFields
Definition at line 20 of file createControls.H.
excludeFields
wordRes excludeFields
Definition at line 24 of file createControls.H.
Referenced by Cloud< ParcelType >::writeObject().