OpenFOAM: applications/solvers/heatTransfer/chtMultiRegionFoam/chtMultiRegionTwoPhaseEulerFoam/fluid/initContinuityErrs.H File Reference
initContinuityErrs.H File Reference
Functions
PtrList< uniformDimensionedScalarField > cumulativeContErrIO (fluidRegions.size())
forAll (cumulativeContErrIO, i)
UPtrList< scalar > cumulativeContErr (cumulativeContErrIO.size())
Function Documentation
cumulativeContErrIO()
PtrList< uniformDimensionedScalarField > cumulativeContErrIO (fluidRegions. size())
Referenced by forAll().
forAll()
forAll (cumulativeContErrIO , i)
Definition at line 2 of file initContinuityErrs.H.
References cumulativeContErrIO(), fluidRegions(), mesh, and runTime.
cumulativeContErr()
UPtrList< scalar > cumulativeContErr (cumulativeContErrIO. size())