OpenFOAM: src/phaseSystemModels/reactingEuler/saturationModels/ArdenBuck/ArdenBuck.C File Reference
ArdenBuck.C File Reference
Namespaces
namespace Foam
namespace Foam::saturationModels
Functions
defineTypeNameAndDebug (ArdenBuck, 0)
addToRunTimeSelectionTable (saturationModel, ArdenBuck, dictionary)
Variables
static const Foam::dimensionedScalar zeroC ("", Foam::dimTemperature, 273.15)
static const Foam::dimensionedScalar A ("", Foam::dimPressure, 611.21)
static const Foam::dimensionedScalar B ("", Foam::dimless, 18.678)
static const Foam::dimensionedScalar C ("", Foam::dimTemperature, 234.5)
static const Foam::dimensionedScalar D ("", Foam::dimTemperature, 257.14)
Detailed Description
Original source file ArdenBuck.C
Definition in file ArdenBuck.C.
Variable Documentation
zeroC
const Foam::dimensionedScalar zeroC("", Foam::dimTemperature, 273.15) ("" , Foam::dimTemperature , 273. 15) static
Referenced by ArdenBuck::lnPSat(), ArdenBuck::pSat(), and ArdenBuck::pSatPrime().
A
const Foam::dimensionedScalar A("", Foam::dimPressure, 611.21) ("" , Foam::dimPressure , 611. 21) static
Referenced by thermo< Thermo, Type >::a(), ISAT< CompType, ThermoType >::add(), Barycentric< Cmpt >::Barycentric(), Barycentric2D< Cmpt >::Barycentric2D(), alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField::calcAlphat(), PlessisMasliyahDragForce< CloudType >::calcCoupled(), LiquidEvaporationBoil< CloudType >::calculate(), COxidationHurtMitchell< CloudType >::calculate(), SyamlalOBrien::CdRe(), chemPointISAT< CompType, ThermoType >::checkSolution(), twoDPointCorrector::correctDisplacement(), twoDPointCorrector::correctPoints(), PengRobinsonGas< Specie >::Cp(), PengRobinsonGas< Specie >::CpMCv(), cubicEqn::cubicEqn(), Foam::diff(), EigenMatrix< cmptType >::EigenMatrix(), EigenMatrix< cmptType >::EigenMatrix(), Foam::eigenVector(), Foam::eigenVector(), Foam::eigenVector(), Foam::eigenVector(), Foam::MatrixTools::equal(), multiDimPolyFitter< T >::fillMatrix(), binaryTree< CompType, ThermoType >::insertNewLeaf(), updateMethod::inv(), SyamlalOBrien::K(), LangmuirHinshelwoodReactionRate::LangmuirHinshelwoodReactionRate(), lduMatrix::lduMatrix(), lduMatrix::lduMatrix(), linearEqn::linearEqn(), ArdenBuck::lnPSat(), Moment< Type >::Moment(), Foam::multiply(), Foam::multiply(), Foam::multiply(), Foam::multiply(), Foam::operator*(), Foam::operator+(), lduMatrix::operator+=(), LduMatrix< Type, DType, LUType >::operator+=(), Foam::operator-(), lduMatrix::operator-=(), LduMatrix< Type, DType, LUType >::operator-=(), lduMatrix::operator=(), LduMatrix< Type, DType, LUType >::operator=(), Foam::operator^(), Barycentric2D< Cmpt >::outside(), Foam::MatrixTools::pinv(), ArdenBuck::pSat(), ArdenBuck::pSatPrime(), QRMatrix< MatrixType >::QRMatrix(), QRMatrix< MatrixType >::QRMatrix(), cutFaceAdvect::quadAreaCoeffs(), quadraticEqn::quadraticEqn(), EFA< CompType, ThermoType >::reduceMechanism(), PFA< CompType, ThermoType >::reduceMechanism(), leastSquares::stencilWeights(), SVD::SVD(), Foam::SVDinv(), fixedMultiPhaseHeatFluxFvPatchScalarField::updateCoeffs(), alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs(), and PengRobinsonGas< Specie >::Z().
B
const Foam::dimensionedScalar B("", Foam::dimless, 18.678) ("" , Foam::dimless , 18. 678) static
Referenced by Barycentric< Cmpt >::Barycentric(), Barycentric2D< Cmpt >::Barycentric2D(), alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField::calcAlphat(), PlessisMasliyahDragForce< CloudType >::calcCoupled(), CentredFitSnGradData< Polynomial >::calcFit(), ObukhovLength::calcOL(), LiquidEvaporationBoil< CloudType >::calculate(), SyamlalOBrien::CdRe(), EBRSM< BasicTurbulenceModel >::correct(), PengRobinsonGas< Specie >::Cp(), PengRobinsonGas< Specie >::CpMCv(), cubicEqn::cubicEqn(), PengRobinsonGas< Specie >::Cv(), Foam::diff(), PengRobinsonGas< Specie >::E(), Foam::MatrixTools::equal(), PengRobinsonGas< Specie >::H(), Foam::Math::invIncGamma(), SyamlalOBrien::K(), linearEqn::linearEqn(), FitData< CentredFitData< Polynomial >, extendedCentredCellToFaceStencil, Polynomial >::movePoints(), Foam::multiply(), Foam::multiply(), Foam::multiply(), Foam::multiply(), Foam::operator&(), Foam::operator*(), Foam::operator+(), Foam::operator-(), Barycentric2D< Cmpt >::outside(), cutFaceAdvect::quadAreaCoeffs(), quadraticEqn::quadraticEqn(), EFA< CompType, ThermoType >::reduceMechanism(), PFA< CompType, ThermoType >::reduceMechanism(), PengRobinsonGas< Specie >::S(), fixedMultiPhaseHeatFluxFvPatchScalarField::updateCoeffs(), alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs(), and PengRobinsonGas< Specie >::Z().
C
const Foam::dimensionedScalar C("", Foam::dimTemperature, 234.5) ("" , Foam::dimTemperature , 234. 5) static
D
const Foam::dimensionedScalar D("", Foam::dimTemperature, 257.14) ("" , Foam::dimTemperature , 257. 14) static