OpenFOAM: src/lagrangian/molecularDynamics/molecule/mdTools/calculateAutoCorrelationFunctions.H File Reference
calculateAutoCorrelationFunctions.H File Reference
Functions
if (mesh.time().timeIndex() % vacf.sampleSteps()==0)
if (mesh.time().timeIndex() % pacf.sampleSteps()==0)
if (mesh.time().timeIndex() % hfacf.sampleSteps()==0)
Detailed Description
Original source file calculateAutoCorrelationFunctions.H
Definition in file calculateAutoCorrelationFunctions.H.
Function Documentation
if() [1/3]
if (mesh. time).timeIndex() % vacf.sampleSteps(= = 0)
Definition at line 22 of file calculateAutoCorrelationFunctions.H.
References vacf().
if() [2/3]
if (mesh. time).timeIndex() % pacf.sampleSteps(= = 0)
Definition at line 38 of file calculateAutoCorrelationFunctions.H.
References p, and pacf().
if() [3/3]
if (mesh. time).timeIndex() % hfacf.sampleSteps(= = 0)
Definition at line 60 of file calculateAutoCorrelationFunctions.H.
References hfacf(), and s().