OpenFOAM: src/lagrangian/molecularDynamics/molecule/mdTools/calculateMDFields.H File Reference
calculateMDFields.H File Reference
Functions
forAll (cellOccupancy, cell)
Variables
const List< DynamicList< molecule * > > & cellOccupancy = molecules.cellOccupancy()
Function Documentation
forAll()
forAll (cellOccupancy , cell)
Definition at line 3 of file calculateMDFields.H.
References allSpeciesM_RU(), allSpeciesN_RU(), allSpeciesVelocityMagSquaredSum_RU(), allSpeciesVelocitySum_RU(), cellOccupancy, and forAll.
Variable Documentation
cellOccupancy
const List<DynamicList<molecule*> >& cellOccupancy = molecules.cellOccupancy()
Definition at line 1 of file calculateMDFields.H.
Referenced by KinematicCloud< CloudType >::buildCellOccupancy(), forAll(), KinematicCloud< CloudType >::info(), MPPICCloud< CloudType >::info(), InflationInjection< CloudType >::parcelsToInject(), and InteractionLists< ParticleType >::sendReferredData().