OpenFOAM: applications/utilities/finiteArea/makeFaMesh/checkPatchTopology.H File Reference
checkPatchTopology.H File Reference
Input.
Functions
meshDefDict readIfPresent ("polyMeshPatches", polyPatchNames)
const labelList patchIDs (pbm.patchSet(polyPatchNames, false, true).sortedToc())
for (const label patchi :patchIDs)
labelList faceLabels (nFaceLabels)
uindirectPrimitivePatch pp (UIndirectList< face >(mesh.faces(), faceLabels), mesh.points())
labelHashSet badEdges (pp.nEdges()/20)
if (returnReduceAnd(pp.empty()))
else if (UPstream::parRun())
if (foundError)
Variables
const polyBoundaryMesh & pbm = mesh.boundaryMesh()
wordRes polyPatchNames
label nFaceLabels = 0
labelHashSet * pointSetPtr = nullptr
labelHashSet * badEdgesPtr = &badEdges
bool foundError = false
else
Detailed Description
Input.
Original source file checkPatchTopology.H
Definition in file checkPatchTopology.H.
Function Documentation
readIfPresent()
meshDefDict readIfPresent ("polyMeshPatches" , polyPatchNames)
Referenced by BFGS::BFGS(), GeometricField< symmTensor, fvPatchField, volMesh >::clamp_range(), GeometricField< symmTensor, fvPatchField, volMesh >::clone(), conjugateGradient::conjugateGradient(), laminar< ReactionThermo >::correct(), COxidationHurtMitchell< CloudType >::COxidationHurtMitchell(), DBFGS::DBFGS(), demandDrivenEntry< Type >::demandDrivenEntry(), DimensionedField< symmTensor, Foam::volMesh >::DimensionedField(), exprString::exprString(), GeometricField< symmTensor, fvPatchField, volMesh >::GeometricField(), GeometricField< symmTensor, fvPatchField, volMesh >::GeometricField(), properties::getTrigger(), LBFGS::LBFGS(), maxDurationCondition::maxDurationCondition(), argList::parse(), regularWaveModel::readDict(), waveModel::readDict(), dimensioned< Type >::readIfPresent(), liquidProperties::readIfPresent(), dynamicCodeContext::setCodeContext(), SQP::SQP(), and SR1::SR1().
patchIDs()
const labelList patchIDs (pbm. patchSetpolyPatchNames, false, true).sortedToc()
Referenced by preservePatches::add(), snappyLayerDriver::addLayers(), snappyLayerDriver::addLayers(), snappyLayerDriver::addLayersSinglePass(), preservePatches::apply(), boundaryMesh::changeFaces(), injectionModelList::correct(), transferModelList::correct(), transferModelList::correct(), cellDistFuncs::correctBoundaryFaceCells(), cellDistFuncs::correctBoundaryPointCells(), curvatureSeparation::curvatureSeparation(), structuredDecomp::decompose(), snappyLayerDriver::doLayers(), patchProbes::findElements(), polyBoundaryMesh::findPatchIDs(), GeometricBoundaryField< Type, PatchField, GeoMesh >::GeometricBoundaryField(), externalDisplacementMeshMover::getPatch(), cellDistFuncs::getPatchIDs(), injectionModelList::info(), transferModelList::info(), layerParameters::layerParameters(), meshRefinement::makePatch(), polyBoundaryMesh::matchGroups(), cellDistFuncs::maxPatchSize(), meshRefinement::mergePatchFaces(), meshRefinement::mergePatchFacesUndo(), meshRefinement::meshedPatches(), patchDistMethod::New(), optMeshMovement::New(), displacementMethod::New(), structuredRenumber::renumber(), sampledPatchInternalField::sampleOnPoints(), Foam::selectPatchFaces(), fvMeshSubsetter::setCellSubset(), fvMeshSubsetter::setCellSubset(), motionSmootherAlgo::setDisplacement(), motionSmootherAlgo::setDisplacementPatchFields(), faceSetOption::setFaceSelection(), faBoundaryMesh::setGroup(), polyBoundaryMesh::setGroup(), cellDistFuncs::sumPatchSize(), sampledPatch::update(), and externalCoupled::writeGeometry().
for()
for (const label patchi :patchIDs)
Definition at line 43 of file checkPatchTopology.H.
References nFaceLabels, and pbm.
faceLabels()
labelList faceLabels (nFaceLabels)
Referenced by singleProcessorFaceSets::add(), polyMeshAdder::add(), addPatchCellLayer::addedCells(), polyTopoChange::addMesh(), setToFaceZone::applyToSet(), face::areaInContact(), cellToCellStencil::calcFaceCells(), cellToFaceStencil::calcFaceCells(), zoneCellStencils::calcFaceCells(), FaceCellWave< Type, TrackingData >::cellToFace(), vtuSizing::copyFaceLabelsXml(), faMeshDecomposition::decomposeMesh(), FaceCellWave< Type, TrackingData >::enterDomain(), cellToCellStencil::insertFaceCells(), cellToFaceStencil::insertFaceCells(), zoneCellStencils::insertFaceCells(), FaceCellWave< Type, int >::iterate(), faMeshTools::newMesh(), vtuSizing::renumberFaceLabelsXml(), Foam::selectPatchFaces(), faMatrix< Type >::setComponentReference(), faceSetOption::setFaceSelection(), faMatrix< Type >::setReferences(), faMatrix< Type >::setReferences(), faceCollapser::setRefinement(), removeFaces::setRefinement(), faMatrix< Type >::setValues(), faMatrix< Type >::setValues(), faMatrix< Type >::setValues(), faMatrix< Type >::setValuesFromList(), sensitivitySurface::smoothSensitivities(), Foam::meshTools::visNormal(), and Foam::meshTools::writeOBJ().
pp()
uindirectPrimitivePatch pp (UIndirectList< face > mesh.faces(), faceLabels, mesh. points())
Referenced by KinematicSurfaceFilm< CloudType >::absorbInteraction(), isoSurfacePoint::adaptPatchFields(), preservePatches::add(), polyMeshAdder::add(), snappyLayerDriver::addLayers(), snappyLayerDriver::addLayers(), snappyLayerDriver::addLayersSinglePass(), polyTopoChange::addMesh(), meshRefinement::addPatch(), fvMeshTools::addPatch(), cellToCellStencil::allCoupledFacesPatch(), cellToFaceStencil::allCoupledFacesPatch(), zoneCellStencils::allCoupledFacesPatch(), preservePatches::apply(), searchableSurfaceToFaceZone::applyToSet(), assemblyFaceAreaPairGAMGAgglomeration::assemblyFaceAreaPairGAMGAgglomeration(), averageNeighbourFvGeometryScheme::averageCentres(), averageNeighbourFvGeometryScheme::averageNeighbourCentres(), snappySnapDriver::avgCellCentres(), patchMeshWriter::beginPiece(), meshRefinement::blockLeakFaces(), KinematicSurfaceFilm< CloudType >::bounceInteraction(), boundaryRadiationProperties::boundaryRadiationProperties(), treeDataPrimitivePatch< PatchType >::boxes(), Foam::meshTools::calcBoxPointNormals(), decompositionMethod::calcCellCells(), decompositionMethod::calcCellCells(), holeToFace::calcClosure(), curvatureSeparation::calcCosAngle(), addPatchCellLayer::calcExtrudeInfo(), cellToFaceStencil::calcFaceStencil(), polyDualMesh::calcFeatures(), processorCyclicPolyPatch::calcGeometry(), snappySnapDriver::calcNearestSurface(), snappySnapDriver::calcSnapDistance(), solarLoad::calculate(), viewFactor::calculate(), hexRef8::checkMesh(), Foam::collocatedPatch(), reconstructedDistanceFunction::constructRDF(), patchInjection::correct(), LocalInteraction< CloudType >::correct(), MultiInteraction< CloudType >::correct(), Rebound< CloudType >::correct(), RecycleInteraction< CloudType >::correct(), StandardWallInteraction< CloudType >::correct(), limitTemperature::correct(), wallDistAddressing::correct(), meshRefinement::countEdgeFaces(), globalMeshData::coupledPatch(), heThermo< BasicThermo, MixtureType >::Cp(), ReynoldsAnalogy::Cp(), heThermo< BasicThermo, MixtureType >::CpByCpv(), heThermo< BasicThermo, MixtureType >::Cpv(), meshRefinement::createBaffles(), structuredDecomp::decompose(), decompositionMethod::decompose(), snappySnapDriver::detectNearSurfaces(), directions::directions(), snappyLayerDriver::doLayers(), snappySnapDriver::doSnap(), KinematicSurfaceFilm< CloudType >::drySplashInteraction(), Curle::execute(), wallHeatFlux::execute(), faceCoupleInfo::faceLabels(), polyMeshTools::faceOrthogonality(), mappedPatchBase::facePoints(), FacePostProcessing< CloudType >::FacePostProcessing(), polyMeshTools::faceSkewness(), polyMeshTools::faceWeights(), faMesh::faMesh(), patchProbes::findElements(), mappedPatchBase::findLocalSamples(), lduPrimitiveMeshAssembly::findNbrMeshId(), volPointInterpolation::flatBoundaryField(), for(), for(), fvMeshSubsetter::fvMeshSubset(), fvMeshSubsetter::fvMeshSubset(), heThermo< BasicThermo, MixtureType >::gamma(), PatchTools::gatherAndMerge(), PatchTools::gatherAndMerge(), removeCells::getExposedFaces(), snappySnapDriver::getFacePoints(), syncTools::getInternalOrCoupledFaces(), syncTools::getInternalOrMasterFaces(), syncTools::getMasterFaces(), decompositionConstraint::getMinBoundaryValue(), externalDisplacementMeshMover::getPatch(), addPatchCellLayer::globalEdgeFaces(), globalIndexAndTransform::globalIndexAndTransform(), heheuPsiThermo< BasicPsiThermo, MixtureType >::heheuPsiThermo(), heheuPsiThermo< BasicPsiThermo, MixtureType >::heheuPsiThermo(), KinematicParcel< ParcelType >::hitPatch(), if(), if(), if(), if(), if(), isoSurfaceBase::ignoreCyclics(), singleDirectionUniformBin::initialise(), uniformBin::initialise(), heatExchangerModel::initialise(), viewFactor::initialise(), fluxSummary::initialiseCellZoneAndDirection(), fluxSummary::initialiseFaceZone(), fluxSummary::initialiseFaceZoneAndDirection(), cyclicACMIPolyPatch::initOrder(), cyclicPolyPatch::initOrder(), processorPolyPatch::initOrder(), processorCyclicPolyPatch::initOrder(), isoSurfacePoint::isoSurfacePoint(), heSolidThermo< BasicSolidThermo, MixtureType >::Kappa(), heSolidThermo< BasicSolidThermo, MixtureType >::Kappa(), temperatureCoupledBase::kappa(), interfaceOxideRate< Thermo, OtherThermo >::Kexp(), wallPointAddressing::leaveDomain(), localPointRegion::localPointRegion(), highAspectRatioFvGeometryScheme::makeAverageCentres(), mappedVariableThicknessWallFvPatch::makeDeltaCoeffs(), meshRefinement::makePatch(), fvMatrix< Type >::mapContributions(), inverseDistance::markBoundaries(), trackingInverseDistance::markBoundaries(), momentOfInertia::massPropertiesPatch(), meshStructure::meshStructure(), meshStructure::meshStructure(), medialAxisMeshMover::move(), regionModel1D::moveMesh(), solidBodyFvGeometryScheme::movePoints(), heheuPsiThermo< BasicPsiThermo, MixtureType >::mub(), heheuPsiThermo< BasicPsiThermo, MixtureType >::muu(), regionModel::nbrCoupledPatchID(), polyBoundaryMesh::neighbourEdges(), cyclicACMIPointPatch::neighbPatch(), cyclicACMIPolyPatch::neighbPatch(), cyclicAMIPointPatch::neighbPatch(), cyclicAMIPolyPatch::neighbPatch(), cyclicPointPatch::neighbPatch(), cyclicPolyPatch::neighbPatch(), wallAbsorptionEmissionModel::New(), wallTransmissivityModel::New(), PatchFunction1< scalar >::New(), PatchFunction1< Type >::New(), PatchFunction1< Type >::NewIfPresent(), PatchFunction1< scalar >::NewIfPresent(), meshSearch::nonCoupledBoundaryTree(), faceShading::nonCoupledPatches(), zoneCellStencils::nonEmptyFacesPatch(), opaqueDiffusive::opaqueDiffusive(), opaqueReflective::opaqueReflective(), labelRangeOp< polyPatch >::operator()(), Foam::operator<<(), Foam::operator>>(), cyclicACMIPolyPatch::order(), cyclicAMIPolyPatch::order(), cyclicPolyPatch::order(), oldCyclicPolyPatch::order(), processorPolyPatch::order(), processorCyclicPolyPatch::order(), KinematicCloud< CloudType >::patchData(), polyMeshAdder::patchFacePairs(), sampledPatch::patchIDs(), patchInteractionDataList::patchInteractionDataList(), enthalpySorptionFvPatchScalarField::patchSource(), CloudFunctionObjectList< CloudType >::postPatch(), ParticleErosion< CloudType >::postPatch(), ParticleHistogram< CloudType >::postPatch(), ParticlePostProcessing< CloudType >::postPatch(), PatchCollisionDensity< CloudType >::postPatch(), PatchInteractionFields< CloudType >::postPatch(), fvMeshDistribute::printMeshInfo(), singleDirectionUniformBin::processField(), uniformBin::processField(), polyMeshAdder::procPatchPairs(), heheuPsiThermo< BasicPsiThermo, MixtureType >::psib(), heheuPsiThermo< BasicPsiThermo, MixtureType >::psiu(), AMIWeights::read(), fieldExtents::read(), boundaryMesh::read(), processorCyclicPolyPatch::referPatch(), fvMeshTools::removeEmptyPatches(), RemoveParcels< CloudType >::RemoveParcels(), structuredRenumber::renumber(), SloanRenumber::renumber(), snappySnapDriver::repatchToSurface(), AMIWeights::reportPatch(), heThermo< BasicPsiThermo, MixtureType >::rhoEoS(), sampledFaceZone::sampleOnPoints(), sampledPatch::sampleOnPoints(), sampledPatchInternalField::sampleOnPoints(), motionSmootherAlgo::scaleMesh(), meshRefinement::selectSeparatedCoupledFaces(), uniformBin::setBinsAddressing(), extractEulerianParticles::setBlockedFaces(), motionSmootherAlgo::setDisplacement(), rotorDiskSource::setFaceArea(), fvGeometryScheme::setMeshPhi(), removeCells::setRefinement(), addPatchCellLayer::setRefinement(), addPatchCellLayer::setRefinement(), shortestPathSet::shortestPathSet(), snappySnapDriver::smoothDisplacement(), solidAbsorption::solidAbsorption(), KinematicSurfaceFilm< CloudType >::splashInteraction(), Foam::sumNeighbours(), syncTools::swapBoundaryCellList(), syncTools::swapBoundaryCellPositions(), syncTools::syncBoundaryFaceList(), syncTools::syncEdgeMap(), syncTools::syncFaceList(), syncTools::syncPointMap(), heheuPsiThermo< BasicPsiThermo, MixtureType >::Tb(), meshRefinement::testSyncBoundaryFaceList(), KinematicSurfaceFilm< CloudType >::transferParcel(), ThermoSurfaceFilm< CloudType >::transferParcel(), transparent::transparent(), function1::Tsat(), polynomial::Tsat(), ensightFaces::uniqueMeshPoints(), dynamicMotionSolverFvMeshAMI::update(), sampledFaceZone::update(), sampledPatch::update(), lduPrimitiveMeshAssembly::update(), oversetFvMeshBase::updateAddressing(), fixedPressureCompressibleDensityFvPatchScalarField::updateCoeffs(), supersonicFreestreamFvPatchVectorField::updateCoeffs(), cellMotionFvPatchField< Type >::updateCoeffs(), energyJumpFvPatchScalarField::updateCoeffs(), energyJumpAMIFvPatchScalarField::updateCoeffs(), speciesSorptionFvPatchScalarField::updateCoeffs(), humidityTemperatureCoupledMixedFvPatchScalarField::updateCoeffs(), outletMappedUniformInletHeatAdditionFvPatchField::updateCoeffs(), turbulentTemperatureRadCoupledMixedFvPatchScalarField::updateCoeffs(), movingWallVelocityFvPatchVectorField::Uwall(), cellToCellStencil::validBoundaryFaces(), cellToFaceStencil::validBoundaryFaces(), zoneCellStencils::validBoundaryFaces(), polyMeshTools::volRatio(), wallLayerCells::wallLayerCells(), WallLocalSpringSliderDashpot< CloudType >::WallLocalSpringSliderDashpot(), streamLineBase::wallPatch(), KinematicSurfaceFilm< CloudType >::wetSplashInteraction(), AMIWeights::write(), wallShearStress::write(), vtkWrite::write(), OBJstream::write(), ensightFaces::write(), Foam::vtk::writeCellSetFaces(), polyBoundaryMesh::writeData(), Foam::vtk::writeFaceSet(), patchMeshWriter::writeNeighIDs(), Foam::ensightOutput::writePointField(), patchMeshWriter::writePoints(), patchMeshWriter::writePolys(), patchMeshWriter::writePolysLegacy(), Foam::ensightOutput::writeVolField(), lumpedPointMovement::writeVTP(), AMIWeights::writeWeightField(), lumpedPointMovement::writeZonesVTP(), and meshRefinement::zonify().
badEdges()
labelHashSet badEdges (pp.nEdges()/ 20)
Referenced by if().
if() [1/3]
if (returnReduceAnd(pp.empty()))
Definition at line 74 of file checkPatchTopology.H.
if() [2/3]
else if (UPstream::parRun())
Definition at line 78 of file checkPatchTopology.H.
References badEdgesPtr, forAll, foundError, mesh, pointSetPtr, pp(), and UList< T >::size().
if() [3/3]
if (foundError)
Definition at line 137 of file checkPatchTopology.H.
References badEdges(), mesh, pp(), and writer().
Variable Documentation
pbm
const polyBoundaryMesh& pbm = mesh.boundaryMesh()
Definition at line 27 of file checkPatchTopology.H.
Referenced by preservePatches::add(), polyMeshAdder::add(), snappyLayerDriver::addLayers(), snappyLayerDriver::addLayersSinglePass(), preservePatches::apply(), searchableSurfaceToFaceZone::applyToSet(), Cloud< ParcelType >::autoMap(), averageNeighbourFvGeometryScheme::averageCentres(), averageNeighbourFvGeometryScheme::averageNeighbourCentres(), meshRefinement::balance(), boundaryRadiationProperties::boundaryRadiationProperties(), SurfaceFilmModel< CloudType >::cacheFilmFields(), curvatureSeparation::calcInvR1(), pointPatchDist::correct(), patchInjection::correct(), directionalPressureGradientExplicitSource::correct(), meshRefinement::createBaffles(), Foam::createReconstructMap(), motionSmootherAlgo::curPoints(), structuredDecomp::decompose(), polyMeshTools::faceOrthogonality(), FacePostProcessing< CloudType >::FacePostProcessing(), polyMeshTools::faceSkewness(), polyMeshTools::faceWeights(), cellVolumeWeight::findHoles(), inverseDistance::findHoles(), coupleGroupIdentifier::findOtherPatchID(), coupleGroupIdentifier::findOtherPatchID(), for(), meshRefinement::getFaceZoneInfo(), decompositionConstraint::getMinBoundaryValue(), if(), if(), injectionModelList::info(), transferModelList::info(), singleDirectionUniformBin::initialise(), uniformBin::initialise(), fluxSummary::initialiseCellZoneAndDirection(), SurfaceFilmModel< CloudType >::inject(), SurfaceFilmModel< CloudType >::injectParticles(), interpolationCellPatchConstrained< Type >::interpolate(), highAspectRatioFvGeometryScheme::makeAverageCentres(), inverseDistance::markBoundaries(), trackingInverseDistance::markBoundaries(), cellVolumeWeight::markPatchCells(), oversetPolyPatch::master(), Cloud< ParticleType >::move(), solidBodyFvGeometryScheme::movePoints(), regionModel::nbrCoupledPatchID(), faceShading::nonCoupledPatches(), Foam::operator<<(), polyMeshAdder::patchFacePairs(), patchInjection::patchInjection(), polyMeshAdder::procPatchPairs(), fieldExtents::read(), wallShearStress::read(), wallHeatFlux::read(), fvMeshTools::removeEmptyPatches(), RemoveParcels< CloudType >::RemoveParcels(), structuredRenumber::renumber(), sampledMeshedSurface::sampleOnFaces(), Foam::selectPatchFaces(), rotorDiskSource::setFaceArea(), faceSetOption::setFaceSelection(), shortestPathSet::shortestPathSet(), Foam::sumNeighbours(), dynamicMotionSolverFvMeshAMI::update(), polyMeshTools::volRatio(), AMIWeights::write(), and momentum::write().
polyPatchNames
wordRes polyPatchNames
Definition at line 29 of file checkPatchTopology.H.
Referenced by Foam::selectPatchFaces().
nFaceLabels
nFaceLabels = 0
Definition at line 42 of file checkPatchTopology.H.
Referenced by for(), vtuSizing::operator==(), Foam::selectPatchFaces(), and vtuSizing::sizeOf().
pointSetPtr
labelHashSet* pointSetPtr = nullptr
Definition at line 69 of file checkPatchTopology.H.
Referenced by PrimitivePatch< FaceList, PointField >::checkPointManifold(), PrimitivePatch< FaceList, PointField >::checkTopology(), and if().
badEdgesPtr
labelHashSet* badEdgesPtr = &badEdges
Definition at line 70 of file checkPatchTopology.H.
Referenced by if(), and PrimitivePatch< FaceList, PointField >::surfaceType().
foundError
foundError = false
Definition at line 72 of file checkPatchTopology.H.
Referenced by PatchTools::checkOrientation(), PrimitivePatch< FaceList, PointField >::checkPointManifold(), PrimitivePatch< FaceList, PointField >::checkTopology(), if(), and PrimitivePatch< FaceList, PointField >::surfaceType().
else
else
Initial value:
{
        const TopoType pTyp = pp.surfaceType(badEdgesPtr)
Definition at line 130 of file checkPatchTopology.H.