OpenFOAM: applications/utilities/finiteArea/checkFaMesh/faMeshWriteVTK.H File Reference
faMeshWriteVTK.H File Reference
Functions
writer writeGeometry ()
globalIndex procAddr (aMesh.nFaces())
if (Pstream::master())
writer beginCellData (4)
writer writeProcIDs ()
writer write ("cellID", cellIDs)
writer write ("area", aMesh.S().field())
writer write ("normal", aMesh.faceAreaNormals())
writer beginPointData (1)
Info<< nl<< "Wrote faMesh in vtk format: "<< writer.output().name()<< nl;}{ vtk::lineWriter writer(aMesh.points(), aMesh.edges(), fileName(aMesh.time().globalPath()/"finiteArea-edges"));writer.writeGeometry();writer.beginCellData(4);writer.writeProcIDs();{ Field< scalar > fld (faMeshTools::flattenEdgeField(aMesh.magLe(), true))
writer write ("magLe", fld)
Info<< nl<< "Wrote faMesh in vtk format: "<< writer.output().name()<< nl;}{ const Field< vector > edgeCentres (faMeshTools::flattenEdgeField(aMesh.edgeCentres(), true))
vtk::lineWriter writer (edgeCentres, edgeList::null(), fileName(aMesh.time().globalPath()/"finiteArea-edgesCentres"))
writer beginPointData (3)
writer write ("Le", fld)
writer write ("normal", fld)
Variables
labelList cellIDs
Detailed Description
Original source file faMeshWriteVTK.H
Definition in file faMeshWriteVTK.H.
Function Documentation
writeGeometry()
writer writeGeometry ()
Referenced by abaqusWriter::write(), nastranWriter::write(), FIREMeshWriter::write(), ensightWriter::writeCollated(), abaqusWriter::writeTemplate(), nastranWriter::writeTemplate(), nastranWriter::writeTemplate(), nastranWriter::writeTemplate(), and ensightWriter::writeUncollated().
procAddr()
globalIndex procAddr (aMesh. nFaces())
Referenced by faBoundaryMesh::checkParallelSync(), polyBoundaryMesh::checkParallelSync(), ZoneMesh< ZoneType, MeshType >::checkParallelSync(), if(), if(), Foam::ensightOutput::writeCloudField(), Foam::ensightOutput::writeCloudPositions(), Foam::ensightOutput::Detail::writeFieldComponents(), Foam::vtk::writeListParallel(), Foam::vtk::writeListParallel(), Foam::vtk::writeListParallel(), Foam::vtk::writeListParallel(), and fileWriter::writeProcIDs().
if()
if (Pstream::master())
Definition at line 38 of file faMeshWriteVTK.H.
References cellIDs, procAddr(), range, and List< T >::resize().
beginCellData()
writer beginCellData (4)
Referenced by lagrangianWriter::beginParcelData().
writeProcIDs()
writer writeProcIDs ()
write() [1/6]
writer write ("cellID" , cellIDs)
write() [2/6]
writer write ("area" , aMesh. S).field()
write() [3/6]
writer write ("normal" , aMesh. faceAreaNormals())
beginPointData() [1/2]
writer beginPointData (1)
Referenced by lagrangianWriter::beginParcelData().
fld()
Info<< nl<< "Wrote faMesh in vtk format: "<< writer.output().name()<< nl;}{ vtk::lineWriter writer(aMesh.points(), aMesh.edges(), fileName(aMesh.time().globalPath()/"finiteArea-edges")); writer.writeGeometry(); writer.beginCellData(4); writer.writeProcIDs(); { Field< scalar > fld (faMeshTools::flattenEdgeField(aMesh.magLe(), true))
Referenced by isoSurfacePoint::adaptPatchFields(), scene::addColourToMesh(), object::addData(), scene::addField(), scene::addFieldToMesh(), scene::addMesh(), windowModel::apply(), parseDriver::areaAverage(), parseDriver::areaAverage(), parseDriver::areaSum(), parseDriver::areaSum(), face::average(), triFace::average(), motionSmootherAlgo::avg(), beginPointData(), surfaceFieldValue::canWeight(), volFieldValue::canWeight(), oversetFvMeshBase::checkCoupledBC(), Foam::checkMethod(), Foam::checkMethod(), extendedCentredCellToFaceStencil::collectData(), extendedCentredFaceToCellStencil::collectData(), extendedCentredCellToCellStencil::collectData(), extendedCellToFaceStencil::collectData(), extendedFaceToCellStencil::collectData(), vtuAdaptor::convertField(), vtuAdaptor::convertField(), vtuAdaptor::convertField(), vtuAdaptor::convertField(), Foam::vtk::Tools::convertFieldToVTK(), coordinateScaling< scalar >::coordinateScaling(), oversetFvMeshBase::correctCoupledBoundaryConditions(), fvExprDriver::correctField(), IntegralScaleBox< Type >::correlate(), IntegralScaleBox< Type >::correlate(), cellCellStencil::createField(), nearWallFields::createFields(), distanceSurface::createGeometry(), cyclicACMIFvPatchField< Type >::cyclicACMIFvPatchField(), lagrangianFieldDecomposer::decomposeFieldFields(), dimFieldDecomposer::decomposeFields(), fvFieldDecomposer::decomposeFields(), pointFieldDecomposer::decomposeFields(), lagrangianFieldDecomposer::decomposeFields(), mapDistribute::distribute(), mappedPatchFieldBase< Type >::distribute(), mapDistribute::distribute(), mapDistribute::distribute(), mapDistribute::distribute(), faMeshDistributor::distributeAreaField(), faMeshDistributor::distributeEdgeField(), faMeshDistributor::distributeField(), faMeshDistributor::distributeField(), faMeshBoundaryHalo::distributeSparse(), faMeshBoundaryHalo::distributeSparse(), faMeshBoundaryHalo::distributeSparse(), faMesh::edgeLengthCorrection(), dynamicRefineFvMesh::error(), Foam::evaluateConstraintTypes(), exprResult::exprResult(), exprResult::exprResult(), wallDistAddressing::extract(), Field< Type >::Field(), parseDriver::field_cellSelection(), parseDriver::field_faceSelection(), parseDriver::field_pointSelection(), faMeshTools::flattenEdgeField(), for(), globalIndex::gather(), globalIndex::gather(), globalIndex::gather(), globalIndex::gather(), globalIndex::gather(), externalCoupled::gatherAndCombine(), particleTracksSampler::gatherInplace(), globalIndex::gatherInplace(), globalIndex::gatherInplaceOp(), fvMeshDistribute::generateTestField(), globalIndex::get(), triSurfaceMesh::getField(), distributedTriSurfaceMesh::getField(), surfaceFieldValue::getFieldValues(), decompositionConstraint::getMinBoundaryValue(), fvExprDriver::getOrReadFieldImpl(), exprResult::getReduced(), coalCloudList::hsTrans(), if(), if(), Foam::imposeMinVectorLength(), oversetFvPatchField< Type >::initEvaluate(), mappedPatchFieldBase< Type >::initRetrieveField(), FieldFunction1< Function1Type >::integrate(), lduPrimitiveProcessorInterface::interfaceInternalField(), cyclicACMIFvPatch::interpolate(), cyclicAMIPolyPatch::interpolate(), cyclicAMIFvPatch::interpolate(), pointToPointPlanarInterpolation::interpolate(), cellCellStencil::interpolate(), fvMeshSubsetProxy::interpolate(), fvMeshSubsetProxy::interpolate(), faMeshSubset::interpolate(), fvMeshSubset::interpolate(), cyclicAMIPolyPatch::interpolate(), surfaceInterpolate::interpolateFields(), isoSurfaceTopo::interpolateTemplate(), AMIInterpolation::interpolateToSource(), AMIInterpolation::interpolateToSource(), AMIInterpolation::interpolateToSource(), AMIInterpolation::interpolateToTarget(), AMIInterpolation::interpolateToTarget(), AMIInterpolation::interpolateToTarget(), cyclicAMIPolyPatch::interpolateUntransformed(), interpolationTable< Type >::interpolateValues(), Foam::invTransform(), Foam::invTransform(), Foam::invTransform(), Foam::invTransform(), Foam::invTransform(), Foam::invTransform(), epsilonWallFunctionFvPatchScalarField::manipulateMatrix(), omegaWallFunctionFvPatchScalarField::manipulateMatrix(), wallDistAddressing::map(), fvMeshAdder::MapDimFields(), fvMeshAdder::MapDimFields(), mappedPatchFieldBase< Type >::mappedField(), mappedPatchFieldBase< scalar >::mappedPatchFieldBase(), mappedPatchFieldBase< scalar >::mappedPatchFieldBase(), fvMeshAdder::MapSurfaceField(), fvMeshAdder::MapSurfaceFields(), fvMeshAdder::MapSurfaceFields(), volSurfaceMapping::mapToSurface(), volSurfaceMapping::mapToSurface(), fvMeshAdder::MapVolFields(), fvMeshAdder::MapVolFields(), debugWriter::mergeField(), surfaceWriter::mergeFieldTemplate(), codedPoints0MotionSolver::movePoints(), globalIndex::mpiGatherInplace(), globalIndex::mpiGatherInplaceOp(), cyclicFvPatchField< Type >::neighbourPatchField(), cyclicACMIFvPatchField< Type >::neighbourPatchField(), cyclicAMIFvPatchField< Type >::neighbourPatchField(), DimensionedField< Type, GeoMesh >::New(), DimensionedField< Type, GeoMesh >::New(), GeometricField< Type, PatchField, GeoMesh >::New(), GeometricField< Type, PatchField, GeoMesh >::New(), cyclicACMIFvPatchField< Type >::nonOverlapPatchField(), mapDistribute::transformPosition::operator()(), weightedPosition::operator()(), weightedPosition::operator()(), mapDistribute::transformPosition::operator()(), parallelFvGeometryScheme::transformOriented::operator()(), mapDistribute::transform::operator()(), FieldMapper::operator()(), mapDistribute::transformPosition::operator()(), mapDistribute::transform::operator()(), weightedPosition::operator()(), mapDistribute::transformPosition::operator()(), transformOp< PrimitivePatchType, Type, TrackingData >::operator()(), mapDistribute::transform::operator()(), weightedPosition::operator()(), foamToVtkReportFields::print(), fvMeshDistribute::printFieldInfo(), fvMeshDistribute::printIntFieldInfo(), singleDirectionUniformBin::processField(), uniformBin::processField(), DimensionedField< Type, GeoMesh >::readField(), Cloud< ParcelType >::readFromFiles(), Foam::regionSum(), mapDistribute::reverseDistribute(), mapDistribute::reverseDistribute(), mapDistribute::reverseDistribute(), mapDistribute::reverseDistribute(), coalCloudList::rhoTrans(), Foam::safeLog10(), nearWallFields::sampleBoundaryField(), nearWallFields::sampleFields(), mappedPatchBase::samplePoints(), globalIndex::scatter(), globalIndex::scatter(), accessor::set(), parseDriver::setInternalFieldResult(), motionSmootherAlgo::smooth(), coalCloudList::Srho(), coalCloudList::Srho(), mappedPatchFieldBase< scalar >::storeAndRetrieveField(), mappedPatchFieldBase< Type >::storeField(), solutionControl::storePrevIter(), cyclicACMIPointPatchField< Type >::swapAddSeparated(), cyclicAMIPointPatchField< Type >::swapAddSeparated(), cyclicPointPatchField< Type >::swapAddSeparated(), syncTools::syncBoundaryFaceList(), weightedPosition::syncPoints(), weightedPosition::syncPoints(), fvMeshDistribute::testField(), meshRefinement::testSyncPointList(), meshRefinement::testSyncPointList(), vectorTensorTransform::transform(), vectorTensorTransform::transform(), vectorTensorTransform::transform(), PatchFunction1< Type >::transform(), vectorTensorTransform::transform(), coordinateScaling< scalar >::transform(), Foam::transform(), Foam::transform(), Foam::transform(), Foam::transform(), Foam::transform(), Foam::transform(), Foam::transform(), Foam::transform(), Foam::transform(), Foam::transformPoints(), Foam::transformPoints(), turbulentDigitalFilterInletFvPatchField< Type >::updateCoeffs(), timeVaryingMappedFixedValuePointPatchField< Type >::updateCoeffs(), timeVaryingMassSorptionFvPatchScalarField::updateCoeffs(), coalCloudList::UTrans(), MappedFile< Type >::value(), FieldFunction1< Function1Type >::value(), parseDriver::volAverage(), parseDriver::volSum(), extendedCentredCellToFaceStencil::weightedSum(), extendedCentredCellToCellStencil::weightedSum(), extendedCentredFaceToCellStencil::weightedSum(), extendedCellToFaceStencil::weightedSum(), extendedCellToCellStencil::weightedSum(), extendedFaceToCellStencil::weightedSum(), extendedUpwindCellToFaceStencil::weightedSum(), regionSizeDistribution::write(), oversetFvMeshBase::writeAgglomeration(), Foam::ensightOutput::writeAreaField(), Foam::ensightOutput::writeAreaField(), Foam::ensightOutput::Detail::writeCoordinates(), ensightOutputSurface::writeData(), ensightOutputSurface::writeFaceData(), Foam::ensightOutput::Detail::writeFaceLocalField(), Foam::ensightOutput::Detail::writeFaceLocalField(), Foam::ensightOutput::Detail::writeFaceSubField(), Foam::ensightOutput::Detail::writeFaceSubField(), Foam::ensightOutput::writeField(), Foam::ensightOutput::writeField(), Foam::ensightOutput::writeField(), Foam::ensightOutput::writeField(), Foam::ensightOutput::Detail::writeFieldComponents(), Foam::ensightOutput::Detail::writeFieldComponents(), mappedPatchBase::writeIOField(), ensightOutputSurface::writePointData(), Foam::writeTrackField(), TableBase< Type >::x(), TableBase< Type >::y(), and boundaryRadiationProperties::zoneTransmissivity().
write() [4/6]
writer write ("magLe" , fld)
edgeCentres()
Info<< nl<< "Wrote faMesh in vtk format: "<< writer.output().name()<< nl;}{ const Field< vector > edgeCentres (faMeshTools::flattenEdgeField(aMesh.edgeCentres(), true))
Referenced by processorFaPatch::calcGeometry(), faPatch::delta(), coupledFaPatch::delta(), processorFaPatch::initGeometry(), and extendedEdgeMesh::select().
writer()
vtk::lineWriter writer (edgeCentres , edgeList::null() , fileName(aMesh.time().globalPath()/"finiteArea-edgesCentres"))
Referenced by searchableSurfaces::checkIntersection(), distanceSurface::filterFaceProximity(), distanceSurface::filterRegionProximity(), for(), for(), if(), if(), if(), if(), if(), if(), if(), isoSurfaceTopo::isoSurfaceTopo(), shortestPathSet::shortestPathSet(), Foam::vtkWritePatchEdges(), regionSizeDistribution::write(), vtkWrite::write(), FacePostProcessing< CloudType >::write(), ParticleCollector< CloudType >::write(), VTKedgeFormat::write(), graph::write(), surfaceFieldValue::writeAll(), Foam::writeAreaFields(), Foam::vtk::writeCellSetFaces(), Foam::vtk::writeFaceSet(), Foam::writePointField(), streamLineBase::writeToFile(), Foam::writeVolFields(), Foam::writeVolFields(), vtkWrite::writeVolFieldsImpl(), vtkWrite::writeVolFieldsImpl(), interfaceTrackingFvMesh::writeVTK(), NURBS3DSurface::writeVTK(), lumpedPointMovement::writeVTP(), AMIWeights::writeWeightField(), and lumpedPointMovement::writeZonesVTP().
beginPointData() [2/2]
writer beginPointData (3)
References aMesh(), and fld().
write() [5/6]
writer write ("Le" , fld)
write() [6/6]
writer write ("normal" , fld)
Variable Documentation
cellIDs
labelList cellIDs
Definition at line 36 of file faMeshWriteVTK.H.
Referenced by forces::addToInternalField(), snappyLayerDriver::doLayers(), volFieldValue::filterField(), if(), fluxSummary::initialiseCellZoneAndDirection(), cellCellStencil::interpolate(), inverseDistance::markDonors(), trackingInverseDistance::markDonors(), primitiveMeshTools::updateCellCentresAndVols(), specieReactionRates< ChemistryModelType >::write(), and zoneMotion::zoneMotion().