OpenFOAM: src/OpenFOAM/include/checkTimeOption.H File Reference
checkTimeOption.H File Reference
Functions
if (args.found("time"))
if (args.found("latestTime"))
Function Documentation
if() [1/2]
if (args. found"time")
Definition at line 3 of file checkTimeOption.H.
References args, TimePaths::findClosestTimeIndex(), argList::get(), and startTime.
if() [2/2]
if (args. found"latestTime")
Definition at line 10 of file checkTimeOption.H.
References UPtrList< T >::size(), and startTime.