OpenFOAM: applications/solvers/heatTransfer/chtMultiRegionFoam/chtMultiRegionTwoPhaseEulerFoam/fluid/setRegionFluidFields.H File Reference
setRegionFluidFields.H File Reference
Functions
thermo1 validate (args.executable(), "h", "e")
const dimensionedScalar initialMass ("initialMass", dimMass, initialMassFluid[i])
Variables
twoPhaseSystem & fluid = phaseSystemFluid[i]
phaseModel & phase1 = fluid.phase1()
phaseModel & phase2 = fluid.phase2()
const volScalarField & alpha1 = phase1
const volScalarField & alpha2 = phase2
volVectorField & U1 = phase1.URef()
surfaceScalarField & phi1 = phase1.phiRef()
const surfaceScalarField & alphaPhi1 = phase1.alphaPhi()
volVectorField & U2 = phase2.URef()
surfaceScalarField & phi2 = phase2.phiRef()
const surfaceScalarField & alphaPhi2 = phase2.alphaPhi()
surfaceScalarField & phi = fluid.phi()
rhoThermo & thermo1 = phase1.thermoRef()
rhoThermo & thermo2 = phase2.thermoRef()
volScalarField & rho1 = thermo1.rho()
const volScalarField & psi1 = thermo1.psi()
volScalarField & rho2 = thermo2.rho()
const volScalarField & psi2 = thermo2.psi()
const IOMRFZoneList & MRF = fluid.MRF()
fv::options & fvOptions = fluid.fvOptions()
volScalarField & p = thermo1.p()
volScalarField & p_rgh = p_rghFluid[i]
const volScalarField & gh = ghFluid[i]
const surfaceScalarField & ghf = ghfFluid[i]
bool frozenFlow = frozenFlowFluid[i]
pimpleControl & pimple = pimpleFluid[i]
const dimensionedScalar & pMin = pMinFluid[i]
Function Documentation
validate()
thermo1 validate (args. executable(), "h" , "e")
initialMass()
const dimensionedScalar initialMass ("initialMass" , dimMass , initialMassFluid [i])
Variable Documentation
fluid
twoPhaseSystem& fluid = phaseSystemFluid[i]
Definition at line 1 of file setRegionFluidFields.H.
Referenced by NicenoKEqn< BasicTurbulenceModel >::bubbleG(), LaheyKEpsilon< BasicTurbulenceModel >::bubbleG(), mixtureKEpsilon< BasicTurbulenceModel >::bubbleG(), alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField::calcAlphat(), linearTsub::correct(), phaseChange::correct(), mixtureKEpsilon< BasicTurbulenceModel >::correct(), continuousGasKEpsilon< BasicTurbulenceModel >::correctNut(), MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::correctThermo(), mixtureKEpsilon< BasicTurbulenceModel >::Ct2(), IATEsource::Eo(), for(), for(), forAll(), forAll(), forAll(), AnisothermalPhaseModel< BasePhaseModel >::heEqn(), if(), if(), if(), diffusionGasEvaporation< Thermo, OtherThermo >::Kexp(), continuousGasKEqn< BasicTurbulenceModel >::liquidTurbulence(), continuousGasKEpsilon< BasicTurbulenceModel >::liquidTurbulence(), IATEsource::Mo(), MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::MultiComponentPhaseModel(), phaseModel::New(), phaseModel::New(), phaseChange::phaseChange(), PurePhaseModel< BasePhaseModel, phaseThermo >::PurePhaseModel(), multiphaseInterHtcModel::q(), reactingEulerHtcModel::q(), continuousGasKEpsilon< BasicTurbulenceModel >::rhoEff(), mixtureKEpsilon< BasicTurbulenceModel >::rhogEff(), mixtureKEpsilon< BasicTurbulenceModel >::rholEff(), MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::solveYi(), MovingPhaseModel< BasePhaseModel >::UEqn(), MovingPhaseModel< BasePhaseModel >::UfEqn(), alphatWallBoilingWallFunctionFvPatchScalarField::updateCoeffs(), fixedMultiPhaseHeatFluxFvPatchScalarField::updateCoeffs(), JohnsonJacksonParticleSlipFvPatchVectorField::updateCoeffs(), JohnsonJacksonParticleThetaFvPatchScalarField::updateCoeffs(), IATEsource::Ur(), IATEsource::We(), while(), and while().
phase1
phaseModel& phase1 = fluid.phase1()
Definition at line 3 of file setRegionFluidFields.H.
Referenced by MassTransferPhaseSystem< BasePhaseSystem >::alphaTransfer(), ThermalPhaseChangePhaseSystem< BasePhaseSystem >::correctInterfaceThermo(), TwoResistanceHeatTransferPhaseSystem< BasePhaseSystem >::correctInterfaceThermo(), orderedPhasePair::dispersed(), orderedPhasePair::E(), phasePair::E(), noBlending::f1(), hyperbolic::f2(), linear::f2(), noBlending::f2(), for(), forAll(), orderedPhasePair::from(), OneResistanceHeatTransferPhaseSystem< BasePhaseSystem >::heatTransfer(), ThermalPhaseChangePhaseSystem< BasePhaseSystem >::heatTransfer(), TwoResistanceHeatTransferPhaseSystem< BasePhaseSystem >::heatTransfer(), if(), blended::K(), twoPhaseSystem::Kd(), twoPhaseSystem::Kdf(), phasePair::magUr(), multiphaseSystem::multiphaseSystem(), dragModel::New(), heatTransferModel::New(), phasePair::rho(), phasePair::sigma(), twoPhaseSystem::sigma(), multiphaseSystem::solveAlphas(), multiphaseSystem::surfaceTension(), TwoResistanceHeatTransferPhaseSystem< BasePhaseSystem >::TwoResistanceHeatTransferPhaseSystem(), twoPhaseSystem::Vm(), MassTransferPhaseSystem< BasePhaseSystem >::volTransfer(), and while().
phase2
phaseModel& phase2 = fluid.phase2()
Definition at line 4 of file setRegionFluidFields.H.
Referenced by MassTransferPhaseSystem< BasePhaseSystem >::alphaTransfer(), orderedPhasePair::continuous(), ThermalPhaseChangePhaseSystem< BasePhaseSystem >::correctInterfaceThermo(), TwoResistanceHeatTransferPhaseSystem< BasePhaseSystem >::correctInterfaceThermo(), multiphaseSystem::Cvm(), hyperbolic::f1(), linear::f1(), noBlending::f1(), for(), OneResistanceHeatTransferPhaseSystem< BasePhaseSystem >::heatTransfer(), ThermalPhaseChangePhaseSystem< BasePhaseSystem >::heatTransfer(), TwoResistanceHeatTransferPhaseSystem< BasePhaseSystem >::heatTransfer(), if(), blended::K(), twoPhaseSystem::Kd(), twoPhaseSystem::Kdf(), phasePair::magUr(), multiphaseSystem::multiphaseSystem(), dragModel::New(), heatTransferModel::New(), phasePair::rho(), phasePair::sigma(), twoPhaseSystem::sigma(), multiphaseSystem::solveAlphas(), multiphaseSystem::surfaceTension(), multiphaseSystem::Svm(), orderedPhasePair::to(), TwoResistanceHeatTransferPhaseSystem< BasePhaseSystem >::TwoResistanceHeatTransferPhaseSystem(), twoPhaseSystem::Vm(), MassTransferPhaseSystem< BasePhaseSystem >::volTransfer(), and while().
alpha1
const volScalarField& alpha1 = phase1
Definition at line 6 of file setRegionFluidFields.H.
Referenced by MassTransferPhaseSystem< BasePhaseSystem >::alphaTransfer(), Beetstra::CdRe(), Tenneti::CdRe(), for(), for(), for(), forAll(), Lun::granularPressureCoeff(), SyamlalRogersOBrien::granularPressureCoeff(), Lun::granularPressureCoeffPrime(), SyamlalRogersOBrien::granularPressureCoeffPrime(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), surfaceIteratorIso::isASurfaceCell(), surfaceIteratorPLIC::isASurfaceCell(), segregated::K(), multiphaseInterSystem::K(), Gidaspow::kappa(), HrenyaSinclair::kappa(), Syamlal::kappa(), multiphaseInterSystem::nearInterface(), multiphaseInterSystem::nearInterface(), heatTransferModel::New(), reconstructionSchemes::New(), multiphaseInterSystem::nHatf(), multiphaseInterSystem::nHatfv(), Gidaspow::nu(), HrenyaSinclair::nu(), noneViscosity::nu(), Syamlal::nu(), multiphaseInterSystem::nVolHatfv(), twoPhaseSystem::solve(), multiphaseSystem::solveAlphas(), MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::solveYi(), Foam::fvc::spreadSource(), DESModel< BasicTurbulenceModel >::Ssigma(), multiphaseInterSystem::surfaceTensionForce(), twoPhaseSystem::twoPhaseSystem(), surfaceIteratorIso::vofCutCell(), surfaceIteratorPLIC::vofCutCell(), while(), and while().
alpha2
const volScalarField& alpha2 = phase2
Definition at line 7 of file setRegionFluidFields.H.
Referenced by MassTransferPhaseSystem< BasePhaseSystem >::alphaTransfer(), Beetstra::CdRe(), Gibilaro::CdRe(), GidaspowSchillerNaumann::CdRe(), SyamlalOBrien::CdRe(), Tenneti::CdRe(), WenYu::CdRe(), for(), if(), if(), if(), segregated::K(), multiphaseInterSystem::K(), Ergun::K(), Gibilaro::K(), GidaspowErgunWenYu::K(), GidaspowSchillerNaumann::K(), SyamlalOBrien::K(), WenYu::K(), multiphaseInterSystem::nearInterface(), multiphaseInterSystem::nearInterface(), multiphaseInterSystem::nHatf(), multiphaseInterSystem::nHatfv(), multiphaseInterSystem::nVolHatfv(), twoPhaseSystem::solve(), multiphaseSystem::solveAlphas(), MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::solveYi(), Foam::fvc::spreadSource(), multiphaseInterSystem::surfaceTensionForce(), while(), and while().
U1
volVectorField& U1 = phase1.URef()
Definition at line 9 of file setRegionFluidFields.H.
Referenced by TrajectoryCollision< CloudType >::collideParcels(), ORourkeCollision< CloudType >::collideSorted(), for(), if(), and while().
phi1
surfaceScalarField& phi1 = phase1.phiRef()
Definition at line 10 of file setRegionFluidFields.H.
Referenced by forAll(), twoPhaseSystem::solve(), and while().
alphaPhi1
const surfaceScalarField& alphaPhi1 = phase1.alphaPhi()
Definition at line 11 of file setRegionFluidFields.H.
Referenced by for(), if(), twoPhaseSystem::solve(), and while().
U2
volVectorField& U2 = phase2.URef()
Definition at line 13 of file setRegionFluidFields.H.
Referenced by TrajectoryCollision< CloudType >::collideParcels(), ORourkeCollision< CloudType >::collideSorted(), for(), if(), and while().
phi2
surfaceScalarField& phi2 = phase2.phiRef()
Definition at line 14 of file setRegionFluidFields.H.
Referenced by forAll(), twoPhaseSystem::solve(), and while().
alphaPhi2
const surfaceScalarField& alphaPhi2 = phase2.alphaPhi()
Definition at line 15 of file setRegionFluidFields.H.
Referenced by for(), if(), and while().
phi
surfaceScalarField& phi = fluid.phi()
Definition at line 17 of file setRegionFluidFields.H.
thermo1
rhoThermo& thermo1 = phase1.thermoRef()
Definition at line 19 of file setRegionFluidFields.H.
Referenced by for().
thermo2
rhoThermo& thermo2 = phase2.thermoRef()
Definition at line 20 of file setRegionFluidFields.H.
Referenced by for().
rho1
volScalarField& rho1 = thermo1.rho()
Definition at line 25 of file setRegionFluidFields.H.
Referenced by SprayParcel< ParcelType >::calc(), ORourkeCollision< CloudType >::collideSorted(), for(), for(), isoAdvection::getRhoPhi(), isoAdvection::getRhoPhi(), Lun::granularPressureCoeff(), SyamlalRogersOBrien::granularPressureCoeff(), Lun::granularPressureCoeffPrime(), SyamlalRogersOBrien::granularPressureCoeffPrime(), if(), if(), segregated::K(), Gidaspow::kappa(), HrenyaSinclair::kappa(), Syamlal::kappa(), while(), and while().
psi1
const volScalarField& psi1 = thermo1.psi()
Definition at line 26 of file setRegionFluidFields.H.
Referenced by adjointkOmegaSST::blend(), kOmegaSSTBase< BasicEddyViscosityModel >::blend(), adjointkOmegaSST::blend(), kOmegaSSTBase< BasicEddyViscosityModel >::blend(), if(), and while().
rho2
volScalarField& rho2 = thermo2.rho()
Definition at line 28 of file setRegionFluidFields.H.
Referenced by ORourkeCollision< CloudType >::collideSorted(), for(), for(), isoAdvection::getRhoPhi(), isoAdvection::getRhoPhi(), if(), if(), segregated::K(), while(), and while().
psi2
const volScalarField& psi2 = thermo2.psi()
Definition at line 29 of file setRegionFluidFields.H.
Referenced by adjointkOmegaSST::blend(), kOmegaSSTBase< BasicEddyViscosityModel >::blend(), adjointkOmegaSST::blend(), kOmegaSSTBase< BasicEddyViscosityModel >::blend(), if(), and while().
MRF
const IOMRFZoneList& MRF = fluid.MRF()
Definition at line 31 of file setRegionFluidFields.H.
fvOptions
fv::options& fvOptions = fluid.fvOptions()
Definition at line 32 of file setRegionFluidFields.H.
p
volScalarField& p = thermo1.p()
Definition at line 34 of file setRegionFluidFields.H.
p_rgh
volScalarField& p_rgh = p_rghFluid[i]
Definition at line 36 of file setRegionFluidFields.H.
gh
const volScalarField& gh = ghFluid[i]
Definition at line 39 of file setRegionFluidFields.H.
ghf
const surfaceScalarField& ghf = ghfFluid[i]
Definition at line 40 of file setRegionFluidFields.H.
frozenFlow
bool frozenFlow = frozenFlowFluid[i]
Definition at line 49 of file setRegionFluidFields.H.
pimple
pimpleControl& pimple = pimpleFluid[i]
Definition at line 54 of file setRegionFluidFields.H.
Referenced by Foam::CorrectPhi(), Foam::CorrectPhi(), if(), if(), if(), while(), and while().
pMin
const dimensionedScalar& pMin = pMinFluid[i]
Definition at line 56 of file setRegionFluidFields.H.
Referenced by pressureControl::limit(), pressureControl::pressureControl(), while(), and while().