OpenFOAM: applications/solvers/heatTransfer/chtMultiRegionFoam/chtMultiRegionTwoPhaseEulerFoam/fluid/createFluidFields.H File Reference
createFluidFields.H File Reference
Functions
PtrList< twoPhaseSystem > phaseSystemFluid (fluidRegions.size())
PtrList< volScalarField > ghFluid (fluidRegions.size())
PtrList< surfaceScalarField > ghfFluid (fluidRegions.size())
PtrList< uniformDimensionedScalarField > hRefFluid (fluidRegions.size())
PtrList< volScalarField > p_rghFluid (fluidRegions.size())
PtrList< multivariateSurfaceInterpolationScheme< scalar >::fieldTable > fieldsFluid (fluidRegions.size())
List< scalar > initialMassFluid (fluidRegions.size())
List< bool > frozenFlowFluid (fluidRegions.size(), false)
List< label > pRefCellFluid (fluidRegions.size())
List< scalar > pRefValueFluid (fluidRegions.size())
PtrList< dimensionedScalar > pMinFluid (fluidRegions.size())
PtrList< pimpleControl > pimpleFluid (fluidRegions.size())
forAll (fluidRegions, i)
Variables
const uniformDimensionedVectorField & g = meshObjects::gravity::New(runTime)
Function Documentation
phaseSystemFluid()
PtrList< twoPhaseSystem > phaseSystemFluid (fluidRegions. size())
Referenced by forAll(), and forAll().
ghFluid()
PtrList< volScalarField > ghFluid (fluidRegions. size())
ghfFluid()
PtrList< surfaceScalarField > ghfFluid (fluidRegions. size())
hRefFluid()
PtrList< uniformDimensionedScalarField > hRefFluid (fluidRegions. size())
p_rghFluid()
PtrList< volScalarField > p_rghFluid (fluidRegions. size())
fieldsFluid()
PtrList< multivariateSurfaceInterpolationScheme< scalar >::fieldTable > fieldsFluid (fluidRegions. size())
Referenced by forAll().
initialMassFluid()
List< scalar > initialMassFluid (fluidRegions. size())
frozenFlowFluid()
List< bool > frozenFlowFluid (fluidRegions. size(), false)
pRefCellFluid()
List< label > pRefCellFluid (fluidRegions. size())
pRefValueFluid()
List< scalar > pRefValueFluid (fluidRegions. size())
pMinFluid()
PtrList< dimensionedScalar > pMinFluid (fluidRegions. size())
Referenced by forAll().
pimpleFluid()
PtrList< pimpleControl > pimpleFluid (fluidRegions. size())
Referenced by forAll().
forAll()
forAll (fluidRegions , i)
Definition at line 196 of file createFluidFields.H.
References fluidRegions(), frozenFlowFluid(), g, ghfFluid(), ghFluid(), hRefFluid(), initialMassFluid(), p, p_rghFluid(), phase1, phaseSystemFluid(), pimpleDict, pimpleFluid(), pMinFluid(), pRefCellFluid(), pRefValueFluid(), rho, runTime, and setRefCell().
Variable Documentation
g
const uniformDimensionedVectorField& g = meshObjects::gravity::New(runTime)
Definition at line 20 of file createFluidFields.H.