OpenFOAM: applications/solvers/heatTransfer/chtMultiRegionFoam/chtMultiRegionSimpleFoam/fluid/createFluidMeshes.H File Reference
createFluidMeshes.H File Reference
Functions
const wordList fluidNames (rp["fluid"])
PtrList< fvMesh > fluidRegions (fluidNames.size())
forAll (fluidNames, i)
Function Documentation
fluidNames()
const wordList fluidNames (rp ["fluid"])
Referenced by forAll().
fluidRegions()
PtrList< fvMesh > fluidRegions (fluidNames. size())
Referenced by forAll(), forAll(), forAll(), forAll(), and forAll().
forAll()
forAll (fluidNames , i)
Definition at line 5 of file createFluidMeshes.H.
References args, argList::dryRun(), fluidNames(), fluidRegions(), argList::found(), and runTime.