OpenFOAM: applications/solvers/heatTransfer/chtMultiRegionFoam/chtMultiRegionSimpleFoam/fluid/createFluidFields.H File Reference
createFluidFields.H File Reference
Functions
PtrList< rhoThermo > thermoFluid (fluidRegions.size())
PtrList< volScalarField > rhoFluid (fluidRegions.size())
PtrList< volVectorField > UFluid (fluidRegions.size())
PtrList< surfaceScalarField > phiFluid (fluidRegions.size())
PtrList< uniformDimensionedScalarField > hRefFluid (fluidRegions.size())
PtrList< volScalarField > ghFluid (fluidRegions.size())
PtrList< surfaceScalarField > ghfFluid (fluidRegions.size())
PtrList< compressible::turbulenceModel > turbulence (fluidRegions.size())
PtrList< volScalarField > p_rghFluid (fluidRegions.size())
PtrList< radiation::radiationModel > radiation (fluidRegions.size())
List< scalar > initialMassFluid (fluidRegions.size())
List< label > pRefCellFluid (fluidRegions.size(), -1)
List< scalar > pRefValueFluid (fluidRegions.size(), Zero)
List< bool > frozenFlowFluid (fluidRegions.size(), false)
PtrList< dimensionedScalar > rhoMax (fluidRegions.size())
PtrList< dimensionedScalar > rhoMin (fluidRegions.size())
PtrList< IOMRFZoneList > MRFfluid (fluidRegions.size())
PtrList< fv::options > fluidFvOptions (fluidRegions.size())
PtrList< fvVectorMatrix > UEqFluid (fluidRegions.size())
forAll (fluidRegions, i)
Variables
const uniformDimensionedVectorField & g = meshObjects::gravity::New(runTime)
Function Documentation
thermoFluid()
PtrList< rhoThermo > thermoFluid (fluidRegions. size())
Referenced by forAll().
rhoFluid()
PtrList< volScalarField > rhoFluid (fluidRegions. size())
Referenced by forAll(), forAll(), and forAll().
UFluid()
PtrList< volVectorField > UFluid (fluidRegions. size())
Referenced by forAll().
phiFluid()
PtrList< surfaceScalarField > phiFluid (fluidRegions. size())
Referenced by forAll(), forAll(), and forAll().
hRefFluid()
PtrList< uniformDimensionedScalarField > hRefFluid (fluidRegions. size())
Referenced by forAll().
ghFluid()
PtrList< volScalarField > ghFluid (fluidRegions. size())
Referenced by forAll().
ghfFluid()
PtrList< surfaceScalarField > ghfFluid (fluidRegions. size())
Referenced by forAll().
turbulence()
PtrList< compressible::turbulenceModel > turbulence (fluidRegions. size())
p_rghFluid()
PtrList< volScalarField > p_rghFluid (fluidRegions. size())
Referenced by forAll().
radiation()
PtrList< radiation::radiationModel > radiation (fluidRegions. size())
Referenced by forAll().
initialMassFluid()
List< scalar > initialMassFluid (fluidRegions. size())
Referenced by forAll().
pRefCellFluid()
List< label > pRefCellFluid (fluidRegions. size(), - 1)
Referenced by forAll().
pRefValueFluid()
List< scalar > pRefValueFluid (fluidRegions. size(), Zero)
Referenced by forAll().
frozenFlowFluid()
List< bool > frozenFlowFluid (fluidRegions. size(), false)
Referenced by forAll().
rhoMax()
PtrList< dimensionedScalar > rhoMax (fluidRegions. size())
rhoMin()
PtrList< dimensionedScalar > rhoMin (fluidRegions. size())
MRFfluid()
PtrList< IOMRFZoneList > MRFfluid (fluidRegions. size())
Referenced by forAll().
fluidFvOptions()
PtrList< fv::options > fluidFvOptions (fluidRegions. size())
Referenced by forAll().
UEqFluid()
PtrList< fvVectorMatrix > UEqFluid (fluidRegions. size())
Referenced by forAll().
forAll()
forAll (fluidRegions , i)
Definition at line 29 of file createFluidFields.H.
References fluidFvOptions(), fluidRegions(), frozenFlowFluid(), g, ghfFluid(), ghFluid(), hRefFluid(), initialMassFluid(), MRFfluid(), p, p_rghFluid(), phiFluid(), pRefCellFluid(), pRefValueFluid(), radiation(), rhoFluid(), rhoMax, rhoMin, runTime, setRefCell(), T, thermoFluid(), turbulence, UEqFluid(), and UFluid().
Variable Documentation
g
const uniformDimensionedVectorField& g = meshObjects::gravity::New(runTime)
Definition at line 26 of file createFluidFields.H.
Referenced by buoyancyEnergy::addSup(), multiphaseStabilizedTurbulence::addSup(), solidificationMeltingSource::addSup(), PrinceBlanch::addToCoalescenceRate(), Implicit< CloudType >::cacheFields(), SprayParcel< ParcelType >::calcBreakup(), cellLimitedGrad< Type, Limiter >::calcGrad(), cellMDLimitedGrad< Type >::calcGrad(), faceLimitedGrad< Type >::calcGrad(), faceMDLimitedGrad< Type >::calcGrad(), voxelMeshSearch::centre(), Zuber::CHF(), HuaXu::CHFSubCool(), coalCloudList::coalCloudList(), BrunDrippingInjection::correct(), filmTurbulenceModel::Cw(), KocamustafaogullariIshii::dDeparture(), adjointSpalartAllmaras::dfw_dr(), Foam::distanceToEllipse(), Foam::distanceToEllipsoid(), Foam::Elliptic::ellipticIntegralsKE(), IATEsource::Eo(), KinematicParcel< ParcelType >::Eo(), buoyantKEpsilon< BasicTurbulenceModel >::epsilonSource(), Cole::fDeparture(), Foam::findRootEllipseDistance(), Foam::findRootEllipsoidDistance(), for(), forAll(), interfaceTrackingFvMesh::freeSurfacePressureJump(), adjointSpalartAllmaras::fw(), buoyantKEpsilon< BasicTurbulenceModel >::Gcoef(), Foam::HSV_to_RGB(), BreenWestwater::htcFilmBoil(), Bromley::htcFilmBoil(), voxelMeshSearch::index(), voxelMeshSearch::index3(), Foam::Elliptic::JacobiAmp(), buoyantKEpsilon< BasicTurbulenceModel >::kSource(), cellMDLimitedGrad< Type >::limitFace(), cellMDLimitedGrad< Type >::limitFace(), makeFaGradScheme(), makeFaGradScheme(), makeFvGradScheme(), makeFvGradScheme(), makeFvGradScheme(), Jeschar::MHF(), phasePair::Mo(), IATEsource::Mo(), solidParticleCloud::move(), Foam::multiply(), Foam::multiply(), Foam::multiply(), surfaceFilmModel::New(), noiseFFT::octaves(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::omega(), Foam::operator<<(), Foam::RGB_to_HSV(), Foam::RGB_to_XYZ(), sixDoFRigidBodyMotionSolver::solve(), SVD::SVD(), triangulation_plot_eps(), twoPhaseSystem::twoPhaseSystem(), ReitzKHRT< CloudType >::update(), phaseHydrostaticPressureFvPatchScalarField::updateCoeffs(), prghPressureFvPatchScalarField::updateCoeffs(), prghTotalPressureFvPatchScalarField::updateCoeffs(), uniformDensityHydrostaticPressureFvPatchScalarField::updateCoeffs(), waveSurfacePressureFvPatchScalarField::updateCoeffs(), sixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs(), uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs(), alphaFixedPressureFvPatchScalarField::updateCoeffs(), waveMakerPointPatchVectorField::updateCoeffs(), prghPermeableAlphaTotalPressureFvPatchScalarField::updateSnGrad(), IATEsource::Ur(), waveMakerPointPatchVectorField::waveLength(), while(), while(), gnuplotWriter::write(), rawWriter::write(), xmgraceWriter::write(), voxelMeshSearch::writeGrid(), and Foam::XYZ_to_RGB().