OpenFOAM: QRMatrix< MatrixType > Class Template Reference
QRMatrix< MatrixType > Class Template Reference
QRMatrix computes QR decomposition of a given scalar/complex matrix A into the following:
#include <QRMatrix.H>
Public Types
enum modes : uint8_t { FULL = 1 , ECONOMY = 2 }
enum outputs : uint8_t { ONLY_Q = 1 , ONLY_R = 2 , BOTH_QR = 3 }
enum pivoting : bool { FALSE = false , TRUE = true }
typedef MatrixType::cmptType cmptType
typedef SquareMatrix< cmptType > SMatrix
typedef RectangularMatrix< cmptType > RMatrix
Public Member Functions
QRMatrix ()=delete
QRMatrix (const modes mode, const outputs output, const bool pivoting, MatrixType &A)
QRMatrix (const MatrixType &A, const modes mode, const outputs output=outputs::BOTH_QR, const bool pivoting=false)
const MatrixType & Q () const noexcept
MatrixType & Q () noexcept
const MatrixType & R () const noexcept
MatrixType & R () noexcept
const labelList & p () const noexcept
SMatrix P () const
void solve (List< cmptType > &x, const UList< cmptType > &source) const
template<class Addr >
void solve (List< cmptType > &x, const IndirectListBase< cmptType, Addr > &source) const
tmp< Field< cmptType > > solve (const UList< cmptType > &source) const
template<class Addr >
tmp< Field< cmptType > > solve (const IndirectListBase< cmptType, Addr > &source) const
RMatrix solve (const RMatrix &b)
SMatrix inv () const
template<class Addr >
Foam::tmp< Foam::Field< typename MatrixType::cmptType > > solve (const IndirectListBase< cmptType, Addr > &source) const
Detailed Description
template<class MatrixType>
class Foam::QRMatrix< MatrixType >
QRMatrix computes QR decomposition of a given scalar/complex matrix A into the following:
    A = Q R
or in case of QR decomposition with column pivoting:
    A P = Q R
where
= Unitary/orthogonal matrix
= Upper triangular matrix
= Permutation matrix
References:
        TNT implementation:
            Pozo, R. (1997).
            Template Numerical Toolkit for linear algebra:
            High performance programming with C++
            and the Standard Template Library.
            The International Journal of Supercomputer Applications
            and High Performance Computing, 11(3), 251-263.
            DOI:10.1177/109434209701100307
        QR decomposition with column pivoting (tag:QSB):
            Quintana-Ortí, G., Sun, X., & Bischof, C. H. (1998).
            A BLAS-3 version of the QR factorization with column pivoting.
            SIAM Journal on Scientific Computing, 19(5), 1486-1494.
            DOI:10.1137/S1064827595296732
        Moore-Penrose inverse algorithm (tags:KP; KPP):
            Katsikis, V. N., & Pappas, D. (2008).
            Fast computing of the Moore-Penrose inverse matrix.
            Electronic Journal of Linear Algebra, 17(1), 637-650.
            DOI:10.13001/1081-3810.1287
            Katsikis, V. N., Pappas, D., & Petralias, A. (2011).
            An improved method for the computation of
            the Moore–Penrose inverse matrix.
            Applied Mathematics and Computation, 217(23), 9828-9834.
            DOI:10.1016/j.amc.2011.04.080
        Tolerance for the Moore-Penrose inverse algorithm (tag:TA):
            Toutounian, F., & Ataei, A. (2009).
            A new method for computing Moore–Penrose inverse matrices.
            Journal of Computational and applied Mathematics, 228(1), 412-417.
            DOI:10.1016/j.cam.2008.10.008
Usage
Input:
= RectangularMatrix<Type> or SquareMatrix<Type>
Options for the decomposition mode:
= compute full-size decomposition
= compute economy-size decomposition
Options for the output types:
= compute only Q
= compute only R
= compute both Q and R
Options for the column pivoting:
= switch off column pivoting
= switch on column pivoting
Output:
= m-by-m (FULL) or m-by-k (ECONOMY) with k = min(m,n)
= m-by-n (FULL) or k-by-n (ECONOMY) with k = min(m,n)
= n-element label list
= n-by-n permutation matrix
Notes
QRMatrix involves modified implementations of the public-domain library TNT, which is available at https://math.nist.gov/tnt/index.html.
Q and R are always of the same type of the matrix A.
Type can be scalar or complex.
See also
Test-QRMatrix.C
Source files
QRMatrix.H
QRMatrix.C
QRMatrixI.H
Definition at line 207 of file QRMatrix.H.
Member Typedef Documentation
cmptType
template<class MatrixType > typedef MatrixType::cmptType cmptType
Definition at line 211 of file QRMatrix.H.
SMatrix
template<class MatrixType > typedef SquareMatrix<cmptType> SMatrix
Definition at line 212 of file QRMatrix.H.
RMatrix
template<class MatrixType > typedef RectangularMatrix<cmptType> RMatrix
Definition at line 213 of file QRMatrix.H.
Member Enumeration Documentation
modes
template<class MatrixType > enum modes : uint8_t
Enumerator
FULL
compute full-size decomposition
ECONOMY
compute economy-size decomposition
Definition at line 216 of file QRMatrix.H.
outputs
template<class MatrixType > enum outputs : uint8_t
Enumerator
ONLY_Q
compute only Q
ONLY_R
compute only R
BOTH_QR
compute both Q and R
Definition at line 223 of file QRMatrix.H.
pivoting
template<class MatrixType > enum pivoting : bool
Enumerator
FALSE
switch off column pivoting
TRUE
switch on column pivoting
Definition at line 231 of file QRMatrix.H.
Constructor & Destructor Documentation
QRMatrix() [1/3]
template<class MatrixType > QRMatrix () delete
QRMatrix() [2/3]
template<class MatrixType > QRMatrix (const modes mode, const outputs output, const bool pivoting, MatrixType & A) explicit
Definition at line 375 of file QRMatrix.C.
References A, and PtrList< T >::clear().
QRMatrix() [3/3]
template<class MatrixType > QRMatrix (const MatrixType & A, const modes mode, const outputs output = outputs::BOTH_QR, const bool pivoting = false) explicit
Definition at line 408 of file QRMatrix.C.
References A, and PtrList< T >::clear().
Member Function Documentation
Q() [1/2]
template<class MatrixType > const MatrixType & Q () const inline noexcept
Definition at line 337 of file QRMatrix.H.
Q() [2/2]
template<class MatrixType > MatrixType & Q () inline noexcept
Definition at line 343 of file QRMatrix.H.
R() [1/2]
template<class MatrixType > const MatrixType & R () const inline noexcept
Definition at line 349 of file QRMatrix.H.
R() [2/2]
template<class MatrixType > MatrixType & R () inline noexcept
Definition at line 355 of file QRMatrix.H.
p()
template<class MatrixType > const labelList & p () const inline noexcept
Definition at line 361 of file QRMatrix.H.
P()
template<class MatrixType > Foam::SquareMatrix< typename MatrixType::cmptType > P () const inline
Definition at line 26 of file QRMatrixI.H.
References forAll, and Foam::Zero.
solve() [1/6]
template<class MatrixType > void solve (List< cmptType > & x, const UList< cmptType > & source) const
Definition at line 441 of file QRMatrix.C.
References x.
solve() [2/6]
template<class MatrixType > template<class Addr > void solve (List< cmptType > & x, const IndirectListBase< cmptType, Addr > & source) const
Definition at line 453 of file QRMatrix.C.
References x.
solve() [3/6]
template<class MatrixType > Foam::tmp< Foam::Field< typename MatrixType::cmptType > > solve (const UList< cmptType > & source) const
Definition at line 465 of file QRMatrix.C.
solve() [4/6]
template<class MatrixType > template<class Addr > tmp< Field< cmptType > > solve (const IndirectListBase< cmptType, Addr > & source) const
solve() [5/6]
template<class MatrixType > Foam::RectangularMatrix< typename MatrixType::cmptType > solve (const RMatrix & b)
Definition at line 496 of file QRMatrix.C.
References Foam::abort(), alpha, b, Foam::diag(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, k, Matrix< Form, Type >::m(), Foam::mag(), Matrix< Form, Type >::n(), Foam::tab, WarningInFunction, and Foam::Zero.
inv()
template<class MatrixType > Foam::QRMatrix< MatrixType >::SMatrix inv () const
Definition at line 552 of file QRMatrix.C.
References Foam::inv(), and x.
solve() [6/6]
template<class MatrixType > template<class Addr > Foam::tmp< Foam::Field< typename MatrixType::cmptType > > solve (const IndirectListBase< cmptType, Addr > & source) const
Definition at line 481 of file QRMatrix.C.
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/QRMatrix/QRMatrix.H
src/OpenFOAM/matrices/QRMatrix/QRMatrix.C
src/OpenFOAM/matrices/QRMatrix/QRMatrixI.H