OpenFOAM: scanner Class Reference
scanner Class Reference
Ragel lexer/scanner interface for patch expressions.
#include <patchExprScanner.H>
Public Member Functions
scanner (bool withDebug=false)
~scanner ()
bool process (const std::string &str, size_t pos, size_t len, parseDriver &driver_)
bool process (const std::string &str, size_t pos, parseDriver &driver_)
bool process (const std::string &str, parseDriver &driver_)
Public Attributes
int debug
Detailed Description
Ragel lexer/scanner interface for patch expressions.
Note
Ragel code generated with the ./createCode script.
Definition at line 47 of file patchExprScanner.H.
Constructor & Destructor Documentation
scanner()
scanner (bool withDebug = false) inline explicit
Definition at line 84 of file patchExprScanner.H.
References scanner::debug.
~scanner()
~scanner ()
Member Function Documentation
process() [1/3]
bool process (const std::string & str, size_t pos, size_t len, parseDriver & driver_)
Referenced by parseDriver::parse(), scanner::process(), and scanner::process().
process() [2/3]
bool process (const std::string & str, size_t pos, parseDriver & driver_) inline
Definition at line 110 of file patchExprScanner.H.
References Foam::pos(), and scanner::process().
process() [3/3]
bool process (const std::string & str, parseDriver & driver_) inline
Definition at line 120 of file patchExprScanner.H.
References scanner::process().
Member Data Documentation
debug
int debug
Definition at line 78 of file patchExprScanner.H.
Referenced by scanner::scanner().
The documentation for this class was generated from the following file:
src/finiteVolume/expressions/patch/patchExprScanner.H