OpenFOAM: singleDirectionUniformBin Class Reference
singleDirectionUniformBin Class Reference
Calculates binned data in a specified direction.
#include <singleDirectionUniformBin.H>
Public Member Functions
TypeName ("singleDirectionUniformBin")
singleDirectionUniformBin (const dictionary &dict, const fvMesh &mesh, const word &outputPrefix)
singleDirectionUniformBin (const singleDirectionUniformBin &)=delete
void operator= (const singleDirectionUniformBin &)=delete
virtual ~singleDirectionUniformBin ()=default
virtual bool read (const dictionary &dict)
virtual void apply ()
Public Member Functions inherited from binModel
TypeName ("binModel")
declareRunTimeSelectionTable (autoPtr, binModel, dictionary,(const dictionary &dict, const fvMesh &mesh, const word &outputPrefix),(dict, mesh, outputPrefix))
binModel (const dictionary &dict, const fvMesh &mesh, const word &outputPrefix)
binModel (const binModel &)=delete
void operator= (const binModel &)=delete
virtual ~binModel ()=default
label nBin () const noexcept
virtual void updateMesh (const mapPolyMesh &mpm)
virtual void movePoints (const polyMesh &mesh)
template<>
bool decomposePatchValues (List< List< vector > > &data, const label bini, const vector &v, const vector &n) const
template<>
bool decomposePatchValues (List< List< vector > > &data, const label bini, const vector &v, const vector &n) const
template<class Type >
Foam::string writeComponents (const word &stem) const
Public Member Functions inherited from writeFile
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name="undefined", const bool writeToFile=true)
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name, const dictionary &dict, const bool writeToFile=true)
writeFile (const writeFile &wf)
virtual ~writeFile ()=default
virtual OFstream & file ()
virtual bool writeToFile () const
virtual bool canWriteToFile () const
virtual bool canResetFile () const
virtual bool canWriteHeader () const
virtual label charWidth () const
virtual void writeCommented (Ostream &os, const string &str) const
virtual void writeTabbed (Ostream &os, const string &str) const
virtual void writeHeader (Ostream &os, const string &str) const
virtual void writeCurrentTime (Ostream &os) const
virtual void writeBreak (Ostream &os) const
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
template<class Type >
void writeValue (Ostream &os, const Type &val) const
Protected Member Functions
template<class Type >
void writeFileHeader (OFstream &os) const
virtual void initialise ()
template<class Type >
bool processField (const label fieldi)
Protected Member Functions inherited from binModel
void setCoordinateSystem (const dictionary &dict, const word &e3Name=word::null, const word &e1Name=word::null)
template<class Type >
bool decomposePatchValues (List< List< Type > > &data, const label bini, const Type &v, const vector &n) const
template<class Type >
string writeComponents (const word &stem) const
template<class Type >
void writeBinnedData (List< List< Type > > &data, Ostream &os) const
Protected Member Functions inherited from writeFile
void initStream (Ostream &os) const
fileName baseFileDir () const
fileName baseTimeDir () const
fileName filePath (const fileName &fName) const
virtual autoPtr< OFstream > newFile (const fileName &fName) const
virtual autoPtr< OFstream > newFileAtTime (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > newFileAtStartTime (const word &name) const
virtual void resetFile (const word &name)
Omanip< int > valueWidth (const label offset=0) const
void operator= (const writeFile &)=delete
virtual autoPtr< OFstream > createFile (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > createFile (const word &name) const
Protected Attributes
scalar binDx_
scalar binMin_
scalar binMax_
vector binDir_
Protected Attributes inherited from binModel
const fvMesh & mesh_
bool decomposePatchValues_
bool cumulative_
autoPtr< coordinateSystem > coordSysPtr_
label nBin_
labelHashSet patchSet_
wordList fieldNames_
labelList cellZoneIDs_
PtrList< OFstream > filePtrs_
Protected Attributes inherited from writeFile
const objectRegistry & fileObr_
const fileName prefix_
word fileName_
autoPtr< OFstream > filePtr_
label writePrecision_
bool writeToFile_
bool updateHeader_
bool writtenHeader_
bool useUserTime_
scalar startTime_
Additional Inherited Members
Static Public Member Functions inherited from binModel
static autoPtr< binModel > New (const dictionary &dict, const fvMesh &mesh, const word &outputPrefix)
Static Public Attributes inherited from writeFile
static label addChars = 8
Detailed Description
Calculates binned data in a specified direction.
For example, a 10cm-long patch extending only in the x-direction can be binned into 5 bins in the same direction, so that local information can be output for each 2cm-long segment.
Usage
Minimal example by using system/controlDict.functions:
binField1
{
    // Other binField entries
    ...
    // Mandatory entries
    binModel          singleDirectionUniformBin;
    binData
    {
        // Mandatory entries
        nBin          <label>;
        direction     <vector>;
        // Optional entries
        cumulative    <bool>;
        min           <scalar>;
        max           <scalar>;
    }
}
where the entries mean:
Property Description Type Reqd Deflt
binModel Type name: singleDirectionUniformBin word yes -
binData Entries of the chosen bin model dict yes -
nBin Number of bins in binning direction label yes -
direction Binning direction vector yes -
cumulative
Flag to bin data accumulated with increasing distance
in binning direction
bool no false
min
Min-bound in the binning direction with respect to
the global coordinate system's origin
scalar no GREAT
max
Max-bound in the binning direction with respect to
the global coordinate system's origin
scalar no GREAT
Source files
singleDirectionUniformBin.H
singleDirectionUniformBin.C
singleDirectionUniformBinTemplates.C
Definition at line 148 of file singleDirectionUniformBin.H.
Constructor & Destructor Documentation
singleDirectionUniformBin() [1/2]
singleDirectionUniformBin (const dictionary & dict, const fvMesh & mesh, const word & outputPrefix)
Definition at line 89 of file singleDirectionUniformBin.C.
References dict, and singleDirectionUniformBin::read().
singleDirectionUniformBin() [2/2]
singleDirectionUniformBin (const singleDirectionUniformBin &) delete
~singleDirectionUniformBin()
virtual ~singleDirectionUniformBin () virtual default
Member Function Documentation
writeFileHeader()
template<class Type > void writeFileHeader (OFstream & os) const protected
Definition at line 23 of file singleDirectionUniformBinTemplates.C.
References singleDirectionUniformBin::binDir_, singleDirectionUniformBin::binDx_, singleDirectionUniformBin::binMax_, singleDirectionUniformBin::binMin_, binModel::decomposePatchValues_, Foam::endl(), forAll, Foam::name(), binModel::nBin_, Foam::nl, os(), Foam::tab, writeFile::writeCommented(), writeFile::writeHeader(), writeFile::writeHeaderValue(), and writeFile::writeTabbed().
initialise()
void initialise () protected virtual
Implements binModel.
Definition at line 38 of file singleDirectionUniformBin.C.
References singleDirectionUniformBin::binDir_, singleDirectionUniformBin::binDx_, singleDirectionUniformBin::binMax_, singleDirectionUniformBin::binMin_, binModel::cellZoneIDs_, Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::max(), binModel::mesh_, Foam::min(), binModel::nBin_, Foam::nl, binModel::patchSet_, pbm, pp(), and Foam::reduce().
processField()
template<class Type > bool processField (const label fieldi) protected
Definition at line 84 of file singleDirectionUniformBinTemplates.C.
References polyPatch::boundaryMesh(), fld(), forAll, forAllIters, Foam::max(), Foam::min(), pp(), Foam::reduce(), PtrList< T >::setSize(), and Foam::Zero.
TypeName()
TypeName ("singleDirectionUniformBin")
operator=()
void operator= (const singleDirectionUniformBin &) delete
read()
bool read (const dictionary & dict) virtual
Reimplemented from binModel.
Definition at line 108 of file singleDirectionUniformBin.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, UPtrList< T >::get(), Foam::Info, Foam::mag(), Foam::nl, Vector< Cmpt >::normalise(), and binModel::read().
Referenced by singleDirectionUniformBin::singleDirectionUniformBin().
apply()
void apply () virtual
Implements binModel.
Definition at line 154 of file singleDirectionUniformBin.C.
References Foam::endl(), forAll, and WarningInFunction.
Member Data Documentation
binDx_
scalar binDx_ protected
Definition at line 157 of file singleDirectionUniformBin.H.
Referenced by singleDirectionUniformBin::initialise(), and singleDirectionUniformBin::writeFileHeader().
binMin_
scalar binMin_ protected
Definition at line 160 of file singleDirectionUniformBin.H.
Referenced by singleDirectionUniformBin::initialise(), and singleDirectionUniformBin::writeFileHeader().
binMax_
scalar binMax_ protected
Definition at line 163 of file singleDirectionUniformBin.H.
Referenced by singleDirectionUniformBin::initialise(), and singleDirectionUniformBin::writeFileHeader().
binDir_
vector binDir_ protected
Definition at line 166 of file singleDirectionUniformBin.H.
Referenced by singleDirectionUniformBin::initialise(), and singleDirectionUniformBin::writeFileHeader().
The documentation for this class was generated from the following files:
src/functionObjects/field/binField/binModels/singleDirectionUniformBin/singleDirectionUniformBin.H
src/functionObjects/field/binField/binModels/singleDirectionUniformBin/singleDirectionUniformBin.C
src/functionObjects/field/binField/binModels/singleDirectionUniformBin/singleDirectionUniformBinTemplates.C