OpenFOAM: CentredFitSnGradScheme< Type, Polynomial, Stencil > Class Template Reference
CentredFitSnGradScheme< Type, Polynomial, Stencil > Class Template Reference
#include <CentredFitSnGradScheme.H>
Public Member Functions
TypeName ("CentredFitSnGradScheme")
CentredFitSnGradScheme (const fvMesh &mesh, Istream &is)
virtual tmp< surfaceScalarField > deltaCoeffs (const GeometricField< Type, fvPatchField, volMesh > &) const
virtual bool corrected () const noexcept
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > &vf) const
Public Member Functions inherited from snGradScheme< Type >
virtual const word & type () const =0
declareRunTimeSelectionTable (tmp, snGradScheme, Mesh,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
snGradScheme (const fvMesh &mesh)
virtual ~snGradScheme ()=default
const fvMesh & mesh () const
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const GeometricField< Type, fvPatchField, volMesh > &) const
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const tmp< GeometricField< Type, fvPatchField, volMesh > > &) const
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Additional Inherited Members
Static Public Member Functions inherited from snGradScheme< Type >
static tmp< snGradScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &, const word &snGradName="snGrad")
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > sndGrad (const GeometricField< Type, fvPatchField, volMesh > &, const word &snGradName="sndGrad")
Detailed Description
template<class Type, class Polynomial, class Stencil>
class Foam::fv::CentredFitSnGradScheme< Type, Polynomial, Stencil >
Definition at line 53 of file CentredFitSnGradScheme.H.
Constructor & Destructor Documentation
CentredFitSnGradScheme()
template<class Type , class Polynomial , class Stencil > CentredFitSnGradScheme (const fvMesh & mesh, Istream & is) inline
Definition at line 86 of file CentredFitSnGradScheme.H.
Member Function Documentation
TypeName()
template<class Type , class Polynomial , class Stencil > TypeName ("CentredFitSnGradScheme< Type, Polynomial, Stencil >")
deltaCoeffs()
template<class Type , class Polynomial , class Stencil > virtual tmp< surfaceScalarField > deltaCoeffs (const GeometricField< Type, fvPatchField, volMesh > &) const inline virtual
Implements snGradScheme< Type >.
Definition at line 97 of file CentredFitSnGradScheme.H.
References snGradScheme< Type >::mesh().
corrected()
template<class Type , class Polynomial , class Stencil > virtual bool corrected () const inline virtual noexcept
Reimplemented from snGradScheme< Type >.
Definition at line 106 of file CentredFitSnGradScheme.H.
correction()
template<class Type , class Polynomial , class Stencil > virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > & vf) const inline virtual
Reimplemented from snGradScheme< Type >.
Definition at line 113 of file CentredFitSnGradScheme.H.
References Foam::dimLength, snGradScheme< Type >::mesh(), MeshObject< Mesh, MeshObjectType, Type >::New(), and extendedCentredCellToFaceStencil::weightedSum().
The documentation for this class was generated from the following file:
src/finiteVolume/finiteVolume/snGradSchemes/CentredFitSnGrad/CentredFitSnGradScheme.H