OpenFOAM: point Class Reference
point Class Reference
Translation constraint on the centre of rotation: fixed in space.
#include <sixDoFRigidBodyMotionPointConstraint.H>
Public Member Functions
TypeName ("point")
point (const word &name, const dictionary &sDoFRBMCDict, const sixDoFRigidBodyMotion &motion)
virtual autoPtr< sixDoFRigidBodyMotionConstraint > clone () const
virtual ~point ()
virtual void setCentreOfRotation (Foam::point &) const
virtual void constrainTranslation (pointConstraint &) const
virtual void constrainRotation (pointConstraint &) const
virtual bool read (const dictionary &sDoFRBMCCoeff)
virtual void write (Ostream &) const
Public Member Functions inherited from sixDoFRigidBodyMotionConstraint
TypeName ("sixDoFRigidBodyMotionConstraint")
declareRunTimeSelectionTable (autoPtr, sixDoFRigidBodyMotionConstraint, dictionary,(const word &name, const dictionary &sDoFRBMCDict, const sixDoFRigidBodyMotion &motion),(name, sDoFRBMCDict, motion))
sixDoFRigidBodyMotionConstraint (const word &name, const dictionary &sDoFRBMCDict, const sixDoFRigidBodyMotion &motion)
virtual ~sixDoFRigidBodyMotionConstraint ()
const word & name () const
const dictionary & coeffDict () const
const sixDoFRigidBodyMotion & motion () const noexcept
Additional Inherited Members
Static Public Member Functions inherited from sixDoFRigidBodyMotionConstraint
static autoPtr< sixDoFRigidBodyMotionConstraint > New (const word &name, const dictionary &sDoFRBMCDict, const sixDoFRigidBodyMotion &motion)
Protected Attributes inherited from sixDoFRigidBodyMotionConstraint
word name_
dictionary sDoFRBMCCoeffs_
const sixDoFRigidBodyMotion & motion_
Detailed Description
Translation constraint on the centre of rotation: fixed in space.
If 'centreOfRotation' is not provided in the dictionary the centre of mass is used.
Source files
sixDoFRigidBodyMotionPointConstraint.H
sixDoFRigidBodyMotionPointConstraint.C
Definition at line 54 of file sixDoFRigidBodyMotionPointConstraint.H.
Constructor & Destructor Documentation
point()
point (const word & name, const dictionary & sDoFRBMCDict, const sixDoFRigidBodyMotion & motion)
Definition at line 46 of file sixDoFRigidBodyMotionPointConstraint.C.
References Foam::name(), point::point(), and point::read().
Referenced by point::point().
~point()
~point () virtual
Definition at line 62 of file sixDoFRigidBodyMotionPointConstraint.C.
References point::~point().
Referenced by point::~point().
Member Function Documentation
TypeName()
TypeName ("point")
clone()
virtual autoPtr< sixDoFRigidBodyMotionConstraint > clone () const inline virtual
Implements sixDoFRigidBodyMotionConstraint.
Definition at line 81 of file sixDoFRigidBodyMotionPointConstraint.H.
setCentreOfRotation()
void setCentreOfRotation (Foam::point & CofR) const virtual
Reimplemented from sixDoFRigidBodyMotionConstraint.
Definition at line 68 of file sixDoFRigidBodyMotionPointConstraint.C.
References point::setCentreOfRotation().
Referenced by point::setCentreOfRotation().
constrainTranslation()
void constrainTranslation (pointConstraint & pc) const virtual
Implements sixDoFRigidBodyMotionConstraint.
Definition at line 77 of file sixDoFRigidBodyMotionPointConstraint.C.
References pointConstraint::combine(), point::constrainTranslation(), and Foam::Zero.
Referenced by point::constrainTranslation().
constrainRotation()
void constrainRotation (pointConstraint & pc) const virtual
Implements sixDoFRigidBodyMotionConstraint.
Definition at line 86 of file sixDoFRigidBodyMotionPointConstraint.C.
References point::constrainRotation().
Referenced by point::constrainRotation().
read()
bool read (const dictionary & sDoFRBMCCoeff) virtual
Reimplemented from sixDoFRigidBodyMotionConstraint.
Definition at line 93 of file sixDoFRigidBodyMotionPointConstraint.C.
References point::read(), and sixDoFRigidBodyMotionConstraint::read().
Referenced by point::point(), and point::read().
write()
void write (Ostream & os) const virtual
Reimplemented from sixDoFRigidBodyMotionConstraint.
Definition at line 110 of file sixDoFRigidBodyMotionPointConstraint.C.
References os(), and point::write().
Referenced by point::write().
The documentation for this class was generated from the following files:
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/constraints/point/sixDoFRigidBodyMotionPointConstraint.H
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/constraints/point/sixDoFRigidBodyMotionPointConstraint.C