OpenFOAM: diameterModel Class Reference
diameterModel Class Reference abstract
Abstract base-class for dispersed-phase particle diameter models.
#include <diameterModel.H>
Public Member Functions
TypeName ("diameterModel")
declareRunTimeSelectionTable (autoPtr, diameterModel, dictionary,(const dictionary &dict, const phaseModel &phase),(dict, phase))
diameterModel (const dictionary &dict, const phaseModel &phase)
virtual ~diameterModel ()=default
virtual tmp< volScalarField > d () const =0
Static Public Member Functions
static autoPtr< diameterModel > New (const dictionary &dict, const phaseModel &phase)
Protected Attributes
const dictionary & dict_
const phaseModel & phase_
Detailed Description
Abstract base-class for dispersed-phase particle diameter models.
Source files
diameterModel.H
diameterModel.C
Definition at line 51 of file diameterModel.H.
Constructor & Destructor Documentation
diameterModel()
diameterModel (const dictionary & dict, const phaseModel & phase)
Definition at line 38 of file diameterModel.C.
~diameterModel()
virtual ~diameterModel () virtual default
Member Function Documentation
TypeName()
TypeName ("diameterModel")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , diameterModel , dictionary , (const dictionary &dict, const phaseModel &phase) , (dict, phase))
New()
Foam::autoPtr< Foam::multiphaseEuler::diameterModel > New (const dictionary & dict, const phaseModel & phase) static
Definition at line 52 of file diameterModel.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, Foam::Info, and phase::name().
Referenced by phaseModel::phaseModel().
d()
virtual tmp< volScalarField > d () const pure virtual
Implemented in constant, and isothermal.
Member Data Documentation
dict_
const dictionary& dict_ protected
Definition at line 57 of file diameterModel.H.
phase_
const phaseModel& phase_ protected
Definition at line 59 of file diameterModel.H.
The documentation for this class was generated from the following files:
src/phaseSystemModels/multiphaseEuler/multiphaseSystem/diameterModels/diameterModel/diameterModel.H
src/phaseSystemModels/multiphaseEuler/multiphaseSystem/diameterModels/diameterModel/diameterModel.C