OpenFOAM: ArrheniusReactionRate Class Reference
ArrheniusReactionRate Class Reference
Arrhenius reaction rate given by:
#include <ArrheniusReactionRate.H>
Public Member Functions
ArrheniusReactionRate (const scalar A, const scalar beta, const scalar Ta)
ArrheniusReactionRate (const speciesTable &species, const dictionary &dict)
scalar operator() (const scalar p, const scalar T, const scalarField &c) const
void write (Ostream &os) const
Static Public Member Functions
static word type ()
Friends
Ostream & operator<< (Ostream &, const ArrheniusReactionRate &)
Detailed Description
Arrhenius reaction rate given by:
k = A * T^beta * exp(-Ta/T)
Source files
ArrheniusReactionRate.H
ArrheniusReactionRateI.H
Definition at line 56 of file ArrheniusReactionRate.H.
Constructor & Destructor Documentation
ArrheniusReactionRate() [1/2]
ArrheniusReactionRate (const scalar A, const scalar beta, const scalar Ta) inline
Definition at line 23 of file ArrheniusReactionRateI.H.
ArrheniusReactionRate() [2/2]
ArrheniusReactionRate (const speciesTable & species, const dictionary & dict) inline
Definition at line 36 of file ArrheniusReactionRateI.H.
Member Function Documentation
type()
static word type () inline static
Definition at line 88 of file ArrheniusReactionRate.H.
operator()()
Foam::scalar operator() (const scalar p, const scalar T, const scalarField & c) const inline
Definition at line 50 of file ArrheniusReactionRateI.H.
References Foam::exp(), Foam::mag(), Foam::pow(), and T.
Referenced by thirdBodyArrheniusReactionRate::operator()().
write()
void write (Ostream & os) const inline
Definition at line 73 of file ArrheniusReactionRateI.H.
References os(), and Ostream::writeEntry().
Referenced by thirdBodyArrheniusReactionRate::write().
Friends And Related Symbol Documentation
operator<<
Ostream & operator<< (Ostream & , const ArrheniusReactionRate &) friend
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/reaction/reactionRate/ArrheniusReactionRate/ArrheniusReactionRate.H
src/thermophysicalModels/specie/reaction/reactionRate/ArrheniusReactionRate/ArrheniusReactionRateI.H