OpenFOAM: MarshakRadiationFvPatchScalarField Class Reference
MarshakRadiationFvPatchScalarField Class Reference
#include <MarshakRadiationFvPatchScalarField.H>
Public Member Functions
TypeName ("MarshakRadiation")
MarshakRadiationFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
MarshakRadiationFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
MarshakRadiationFvPatchScalarField (const MarshakRadiationFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
MarshakRadiationFvPatchScalarField (const MarshakRadiationFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
MarshakRadiationFvPatchScalarField (const MarshakRadiationFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
const word & TName () const
word & TName ()
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
Definition at line 85 of file MarshakRadiationFvPatchScalarField.H.
Constructor & Destructor Documentation
MarshakRadiationFvPatchScalarField() [1/5]
MarshakRadiationFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 32 of file MarshakRadiationFvPatchScalarField.C.
References Foam::Zero.
MarshakRadiationFvPatchScalarField() [2/5]
MarshakRadiationFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 62 of file MarshakRadiationFvPatchScalarField.C.
References dict, fvPatchField< scalar >::operator=(), and Foam::Zero.
MarshakRadiationFvPatchScalarField() [3/5]
MarshakRadiationFvPatchScalarField (const MarshakRadiationFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 48 of file MarshakRadiationFvPatchScalarField.C.
MarshakRadiationFvPatchScalarField() [4/5]
MarshakRadiationFvPatchScalarField (const MarshakRadiationFvPatchScalarField & ptf)
Definition at line 85 of file MarshakRadiationFvPatchScalarField.C.
MarshakRadiationFvPatchScalarField() [5/5]
MarshakRadiationFvPatchScalarField (const MarshakRadiationFvPatchScalarField & ptf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 96 of file MarshakRadiationFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("MarshakRadiation")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 136 of file MarshakRadiationFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 152 of file MarshakRadiationFvPatchScalarField.H.
TName() [1/2]
const word & TName () const inline
Definition at line 169 of file MarshakRadiationFvPatchScalarField.H.
TName() [2/2]
word & TName () inline
Definition at line 176 of file MarshakRadiationFvPatchScalarField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 110 of file MarshakRadiationFvPatchScalarField.C.
References gamma, mesh, UPstream::msgType(), MeshObject< fvMesh, Foam::GeometricMeshObject, boundaryRadiationProperties >::New(), Foam::pow4(), and Foam::constant::physicoChemical::sigma.
write()
void write (Ostream & os) const virtual
Definition at line 153 of file MarshakRadiationFvPatchScalarField.C.
References os(), and mixedFvPatchField< Type >::write().
The documentation for this class was generated from the following files:
src/thermophysicalModels/radiation/derivedFvPatchFields/MarshakRadiation/MarshakRadiationFvPatchScalarField.H
src/thermophysicalModels/radiation/derivedFvPatchFields/MarshakRadiation/MarshakRadiationFvPatchScalarField.C