OpenFOAM: speciesSorptionFvPatchScalarField Class Reference
speciesSorptionFvPatchScalarField Class Reference
Boundary conditions » Generic
This boundary condition provides a first-order zero-gradient condition for a given scalar field to model time-dependent adsorption-desorption processes.
#include <speciesSorptionFvPatchScalarField.H>
Public Types
enum equilibriumModelType : char { LANGMUIR = 0 }
enum kineticModelType : char { PseudoFirstOrder = 0 }
Public Types inherited from fvPatchField< Type >
typedef DimensionedField< Type, volMesh > Internal
typedef fvPatch Patch
typedef calculatedFvPatchField< Type > Calculated
Public Types inherited from Field< Type >
typedef pTraits< Type >::cmptType cmptType
typedef SubField< Type > subField
Public Types inherited from List< Type >
typedef SubList< Type > subList
Public Types inherited from UList< T >
typedef T value_type
typedef T * pointer
typedef const T * const_pointer
typedef T & reference
typedef const T & const_reference
typedef T * iterator
typedef const T * const_iterator
typedef label size_type
typedef label difference_type
typedef std::reverse_iterator< iterator > reverse_iterator
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
Public Member Functions
TypeName ("speciesSorption")
speciesSorptionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
speciesSorptionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
speciesSorptionFvPatchScalarField (const speciesSorptionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
speciesSorptionFvPatchScalarField (const speciesSorptionFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
speciesSorptionFvPatchScalarField (const speciesSorptionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual void autoMap (const fvPatchFieldMapper &)
virtual void rmap (const fvPatchScalarField &, const labelList &)
virtual tmp< scalarField > patchSource () const
tmp< scalarField > mass () const
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Public Member Functions inherited from zeroGradientFvPatchField< scalar >
TypeName ("zeroGradient")
zeroGradientFvPatchField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
zeroGradientFvPatchField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
zeroGradientFvPatchField (const zeroGradientFvPatchField< scalar > &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
zeroGradientFvPatchField (const zeroGradientFvPatchField< scalar > &)
zeroGradientFvPatchField (const zeroGradientFvPatchField< scalar > &, const DimensionedField< scalar, volMesh > &)
virtual tmp< Field< scalar > > snGrad () const
virtual void evaluate (const Pstream::commsTypes commsType=Pstream::commsTypes::blocking)
virtual tmp< Field< scalar > > valueInternalCoeffs (const tmp< scalarField > &) const
virtual tmp< Field< scalar > > valueBoundaryCoeffs (const tmp< scalarField > &) const
virtual tmp< Field< scalar > > gradientInternalCoeffs () const
virtual tmp< Field< scalar > > gradientBoundaryCoeffs () const
Public Member Functions inherited from fvPatchField< Type >
declareRunTimeSelectionTable (tmp, fvPatchField, patch,(const fvPatch &p, const DimensionedField< Type, volMesh > &iF),(p, iF))
declareRunTimeSelectionTable (tmp, fvPatchField, patchMapper,(const fvPatchField< Type > &ptf, const fvPatch &p, const DimensionedField< Type, volMesh > &iF, const fvPatchFieldMapper &m),(dynamic_cast< const fvPatchFieldType & >(ptf), p, iF, m))
declareRunTimeSelectionTable (tmp, fvPatchField, dictionary,(const fvPatch &p, const DimensionedField< Type, volMesh > &iF, const dictionary &dict),(p, iF, dict))
fvPatchField (const fvPatch &, const DimensionedField< Type, volMesh > &)
fvPatchField (const fvPatch &, const DimensionedField< Type, volMesh > &, const word &patchType)
fvPatchField (const fvPatch &, const DimensionedField< Type, volMesh > &, const Type &value)
fvPatchField (const fvPatch &, const DimensionedField< Type, volMesh > &, const Field< Type > &pfld)
fvPatchField (const fvPatch &, const DimensionedField< Type, volMesh > &, Field< Type > &&pfld)
fvPatchField (const fvPatch &, const DimensionedField< Type, volMesh > &, const dictionary &dict, IOobjectOption::readOption requireValue=IOobjectOption::MUST_READ)
fvPatchField (const fvPatch &p, const DimensionedField< Type, volMesh > &iF, const dictionary &dict, const bool valueReqd)
fvPatchField (const fvPatchField< Type > &, const fvPatch &, const DimensionedField< Type, volMesh > &, const fvPatchFieldMapper &)
fvPatchField (const fvPatchField< Type > &)
fvPatchField (const fvPatchField< Type > &, const DimensionedField< Type, volMesh > &)
virtual tmp< fvPatchField< Type > > clone (const DimensionedField< Type, volMesh > &iF) const
virtual ~fvPatchField ()=default
const DimensionedField< Type, volMesh > & internalField () const noexcept
const Field< Type > & primitiveField () const noexcept
virtual void rmap (const fvPatchField< Type > &, const labelList &)
virtual tmp< Field< Type > > snGrad (const scalarField &deltaCoeffs) const
virtual void updateWeightedCoeffs (const scalarField &weights)
virtual tmp< Field< Type > > patchInternalField () const
virtual void patchInternalField (Field< Type > &pfld) const
virtual tmp< Field< Type > > patchNeighbourField () const
virtual void initEvaluate (const Pstream::commsTypes commsType=Pstream::commsTypes::blocking)
virtual tmp< Field< Type > > gradientInternalCoeffs (const scalarField &deltaCoeffs) const
virtual tmp< Field< Type > > gradientBoundaryCoeffs (const scalarField &deltaCoeffs) const
virtual void manipulateMatrix (fvMatrix< Type > &matrix)
virtual void manipulateMatrix (fvMatrix< Type > &matrix, const scalarField &weights)
virtual void manipulateMatrix (fvMatrix< Type > &matrix, const label iMatrix, const direction cmp)
void check (const fvPatchField< Type > &) const
virtual void operator= (const UList< Type > &)
virtual void operator= (const fvPatchField< Type > &)
virtual void operator+= (const fvPatchField< Type > &)
virtual void operator-= (const fvPatchField< Type > &)
virtual void operator*= (const fvPatchField< scalar > &)
virtual void operator/= (const fvPatchField< scalar > &)
virtual void operator+= (const Field< Type > &)
virtual void operator-= (const Field< Type > &)
virtual void operator*= (const Field< scalar > &)
virtual void operator/= (const Field< scalar > &)
virtual void operator= (const Type &)
virtual void operator+= (const Type &)
virtual void operator-= (const Type &)
virtual void operator*= (const scalar)
virtual void operator/= (const scalar)
virtual void operator== (const fvPatchField< Type > &)
virtual void operator== (const Field< Type > &)
virtual void operator== (const Type &)
template<class Type2 >
Foam::tmp< Foam::fvPatchField< Type > > NewCalculatedType (const fvPatchField< Type2 > &pf)
Public Member Functions inherited from fvPatchFieldBase
TypeName ("fvPatchField")
fvPatchFieldBase (const fvPatch &p)
fvPatchFieldBase (const fvPatch &p, const word &patchType)
fvPatchFieldBase (const fvPatch &p, const dictionary &dict)
fvPatchFieldBase (const fvPatchFieldBase &rhs, const fvPatch &p)
fvPatchFieldBase (const fvPatchFieldBase &rhs)
virtual ~fvPatchFieldBase ()=default
virtual bool assignable () const
virtual bool fixesValue () const
virtual bool coupled () const
const objectRegistry & db () const
const fvPatch & patch () const noexcept
const word & patchType () const noexcept
word & patchType () noexcept
bool updated () const noexcept
bool manipulatedMatrix () const noexcept
bool useImplicit () const noexcept
bool useImplicit (bool on) noexcept
void checkPatch (const fvPatchFieldBase &rhs) const
Public Member Functions inherited from Field< Type >
constexpr Field () noexcept
Field (const label len)
Field (const label len, const Type &val)
Field (const label len, const Foam::zero)
Field (const Foam::one, const Type &val)
Field (const Foam::one, Type &&val)
Field (const Foam::one, const Foam::zero)
Field (const Field< Type > &fld)
Field (const UList< Type > &list)
template<class Addr >
Field (const IndirectListBase< Type, Addr > &list)
Field (Field< Type > &&fld)
Field (List< Type > &&list)
template<int SizeMin>
Field (DynamicList< Type, SizeMin > &&list)
Field (const UList< Type > &mapF, const labelUList &mapAddressing)
Field (const tmp< Field< Type > > &tmapF, const labelUList &mapAddressing)
Field (const UList< Type > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Field (const tmp< Field< Type > > &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Field (const UList< Type > &mapF, const FieldMapper &map, const bool applyFlip=true)
Field (const UList< Type > &mapF, const FieldMapper &map, const Type &defaultValue, const bool applyFlip=true)
Field (const UList< Type > &mapF, const FieldMapper &map, const UList< Type > &defaultValues, const bool applyFlip=true)
Field (const tmp< Field< Type > > &tmapF, const FieldMapper &map, const bool applyFlip=true)
Field (const tmp< Field< Type > > &tmapF, const FieldMapper &map, const Type &defaultValue, const bool applyFlip=true)
Field (const tmp< Field< Type > > &tmapF, const FieldMapper &map, const UList< Type > &defaultValues, const bool applyFlip=true)
Field (Field< Type > &fld, bool reuse)
Field (const tmp< Field< Type > > &tfld)
Field (Istream &is)
Field (const entry &e, const label len)
Field (const word &key, const dictionary &dict, const label len, IOobjectOption::readOption readOpt=IOobjectOption::MUST_READ)
tmp< Field< Type > > clone () const
void assign (const entry &e, const label len)
bool assign (const word &key, const dictionary &dict, const label len, IOobjectOption::readOption readOpt=IOobjectOption::MUST_READ)
void map (const UList< Type > &mapF, const labelUList &mapAddressing)
void map (const tmp< Field< Type > > &tmapF, const labelUList &mapAddressing)
void map (const UList< Type > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
void map (const tmp< Field< Type > > &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
void map (const UList< Type > &mapF, const FieldMapper &map, const bool applyFlip=true)
void map (const tmp< Field< Type > > &tmapF, const FieldMapper &map, const bool applyFlip=true)
void autoMap (const FieldMapper &map, const bool applyFlip=true)
void rmap (const UList< Type > &mapF, const labelUList &mapAddressing)
void rmap (const tmp< Field< Type > > &tmapF, const labelUList &mapAddressing)
void rmap (const UList< Type > &mapF, const labelUList &mapAddressing, const UList< scalar > &weights)
void rmap (const tmp< Field< Type > > &tmapF, const labelUList &mapAddressing, const UList< scalar > &weights)
void negate ()
void normalise ()
tmp< Field< cmptType > > component (const direction) const
void replace (const direction, const UList< cmptType > &)
void replace (const direction, const tmp< Field< cmptType > > &)
void replace (const direction, const cmptType &)
void clamp_min (const Type &lower)
void clamp_max (const Type &upper)
void clamp_range (const Type &lower, const Type &upper)
void clamp_range (const MinMax< Type > &range)
template<class VSForm >
VSForm block (const label start) const
tmp< Field< Type > > T () const
void writeEntry (const word &keyword, Ostream &os) const
SubField< Type > slice (const label pos, label len=-1)
const SubField< Type > slice (const label pos, label len=-1) const
SubField< Type > slice (const labelRange &range)
const SubField< Type > slice (const labelRange &range) const
void operator= (const Field< Type > &)
void operator= (const tmp< Field< Type > > &)
void operator= (const UList< Type > &rhs)
void operator= (const SubField< Type > &rhs)
template<class Addr >
void operator= (const IndirectListBase< Type, Addr > &rhs)
void operator= (Field< Type > &&rhs)
void operator= (List< Type > &&rhs)
template<int SizeMin>
void operator= (DynamicList< Type, SizeMin > &&rhs)
void operator= (const Type &val)
void operator= (const Foam::zero)
template<class Form , class Cmpt , direction nCmpt>
void operator= (const VectorSpace< Form, Cmpt, nCmpt > &)
void operator+= (const UList< Type > &)
void operator+= (const tmp< Field< Type > > &)
void operator-= (const UList< Type > &)
void operator-= (const tmp< Field< Type > > &)
void operator*= (const UList< scalar > &)
void operator*= (const tmp< Field< scalar > > &)
void operator/= (const UList< scalar > &)
void operator/= (const tmp< Field< scalar > > &)
void operator+= (const Type &)
void operator-= (const Type &)
void operator*= (const scalar &)
void operator/= (const scalar &)
template<class Type >
void operator= (const tmp< Field > &rhs)
void normalise ()
void normalise ()
void normalise ()
void normalise ()
Public Member Functions inherited from FieldBase
constexpr FieldBase () noexcept
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Public Member Functions inherited from List< Type >
constexpr List () noexcept
List (const label len)
List (const label len, const Type &val)
List (const label len, const Foam::zero)
List (const Foam::one, const Type &val)
List (const Foam::one, Type &&val)
List (const Foam::one, const Foam::zero)
List (const List< Type > &a)
List (const UList< Type > &a)
List (List< Type > &a, bool reuse)
List (const UList< Type > &list, const labelUList &indices)
List (const UList< Type > &list, const FixedList< label, N > &indices)
List (const FixedList< Type, N > &list)
List (const PtrList< Type > &list)
List (const SLList< Type > &list)
List (const IndirectListBase< Type, Addr > &list)
List (std::initializer_list< Type > list)
List (List< Type > &&list)
List (DynamicList< Type, SizeMin > &&list)
List (SLList< Type > &&list)
List (Istream &is)
autoPtr< List< Type > > clone () const
~List ()
void clear ()
void resize (const label len)
void resize (const label len, const Type &val)
void resize (const label newLen)
void resize_nocopy (const label len)
void setSize (const label n)
void setSize (const label n, const Type &val)
void transfer (List< Type > &list)
void transfer (DynamicList< Type, SizeMin > &list)
Type & newElmt (const label i)
Type & emplace_back (Args &&... args)
void push_back (const Type &val)
void push_back (Type &&val)
void push_back (const UList< Type > &list)
void push_back (const IndirectListBase< Type, Addr > &list)
label push_uniq (const Type &val)
void pop_back (label n=1)
void operator= (const UList< Type > &a)
void operator= (const List< Type > &list)
void operator= (const SLList< Type > &list)
void operator= (const IndirectListBase< Type, Addr > &list)
void operator= (const FixedList< Type, N > &list)
void operator= (std::initializer_list< Type > list)
void operator= (const Type &val)
void operator= (const Foam::zero)
void operator= (List< Type > &&list)
void operator= (DynamicList< Type, SizeMin > &&list)
void operator= (SLList< Type > &&list)
Istream & readList (Istream &is)
Istream & readList (Istream &is)
Istream & readList (Istream &is)
void shallowCopy (const UList< Type > &)=delete
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type set (const label i, bool val=true)
void append (const Type &val)
void append (Type &&val)
void append (const UList< Type > &list)
void append (const IndirectListBase< Type, Addr > &list)
label appendUniq (const Type &val)
Public Member Functions inherited from UList< T >
UList (const UList< T > &)=default
constexpr UList () noexcept
UList (T *__restrict__ v, const label len) noexcept
label fcIndex (const label i) const noexcept
label rcIndex (const label i) const noexcept
const T & fcValue (const label i) const
T & fcValue (const label i)
const T & rcValue (const label i) const
T & rcValue (const label i)
const T * cdata () const noexcept
T * data () noexcept
const char * cdata_bytes () const noexcept
char * data_bytes () noexcept
T & front ()
const T & front () const
T & back ()
const T & back () const
std::streamsize size_bytes () const noexcept
std::streamsize byteSize () const
void checkStart (const label start) const
void checkSize (const label size) const
void checkRange (const label start, const label len) const
void checkIndex (const label i) const
bool uniform () const
label find (const T &val, label pos=0) const
label rfind (const T &val, label pos=-1) const
bool contains (const T &val, label pos=0) const
void moveFirst (const label i)
void moveLast (const label i)
void swapFirst (const label i)
void swapLast (const label i)
void shallowCopy (const UList< T > &list)
void deepCopy (const UList< T > &list)
template<class Addr >
void deepCopy (const IndirectListBase< T, Addr > &list)
SubList< T > slice (const label pos, label len=-1)
const SubList< T > slice (const label pos, label len=-1) const
SubList< T > slice (const labelRange &range)
const SubList< T > slice (const labelRange &range) const
T & operator[] (const label i)
const T & operator[] (const label i) const
operator const Foam::List< T > & () const
void operator= (const T &val)
void operator= (const Foam::zero)
iterator begin () noexcept
iterator end () noexcept
iterator begin (const label i) noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
const_iterator begin () const noexcept
const_iterator end () const noexcept
const_iterator cbegin (const label i) const noexcept
const_iterator begin (const label i) const noexcept
reverse_iterator rbegin ()
reverse_iterator rend ()
const_reverse_iterator crbegin () const
const_reverse_iterator crend () const
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
bool empty () const noexcept
label size () const noexcept
void swap (UList< T > &list)
bool operator== (const UList< T > &a) const
bool operator!= (const UList< T > &a) const
bool operator< (const UList< T > &list) const
bool operator> (const UList< T > &a) const
bool operator<= (const UList< T > &a) const
bool operator>= (const UList< T > &a) const
Istream & readList (Istream &is)
void writeEntry (const word &keyword, Ostream &os) const
Ostream & writeList (Ostream &os, const label shortLen=0) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type test (const label i) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type get (const label i) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type unset (const label i)
T & first ()
const T & first () const
T & last ()
const T & last () const
bool found (const T &val, label pos=0) const
Istream & readList (Istream &is)
Ostream & writeList (Ostream &os, const label) const
const bool & operator[] (const label i) const
UPstream::commsStruct & operator[] (const label procID)
const UPstream::commsStruct & operator[] (const label procID) const
Foam::UPstream::commsStruct & operator[] (const label procID)
const Foam::UPstream::commsStruct & operator[] (const label procID) const
Ostream & writeList (Ostream &os, const label) const
Istream & readList (Istream &is)
Public Member Functions inherited from boundarySourcePatch
TypeName ("boundarySourcePatch")
virtual ~boundarySourcePatch ()=default
Static Public Attributes
static const Enum< equilibriumModelType > equilibriumModelTypeNames
static const Enum< kineticModelType > kinematicModelTypeNames
Static Public Attributes inherited from fvPatchFieldBase
static int disallowGenericPatchField
Static Public Attributes inherited from FieldBase
static const char *const typeName
static bool allowConstructFromLargerSize = false
Additional Inherited Members
Static Public Member Functions inherited from fvPatchField< Type >
static tmp< fvPatchField< Type > > New (const word &patchFieldType, const fvPatch &, const DimensionedField< Type, volMesh > &)
static tmp< fvPatchField< Type > > New (const word &patchFieldType, const word &actualPatchType, const fvPatch &, const DimensionedField< Type, volMesh > &)
static tmp< fvPatchField< Type > > New (const fvPatchField< Type > &, const fvPatch &, const DimensionedField< Type, volMesh > &, const fvPatchFieldMapper &)
static tmp< fvPatchField< Type > > New (const fvPatch &, const DimensionedField< Type, volMesh > &, const dictionary &)
static tmp< fvPatchField< Type > > NewCalculatedType (const fvPatch &)
template<class Type2 >
static tmp< fvPatchField< Type > > NewCalculatedType (const fvPatchField< Type2 > &)
Static Public Member Functions inherited from fvPatchFieldBase
static const word & emptyType () noexcept
static const word & calculatedType () noexcept
static const word & extrapolatedCalculatedType () noexcept
static const word & zeroGradientType () noexcept
Static Public Member Functions inherited from Field< Type >
static const Field< Type > & null ()
static autoPtr< Field< Type > > New (Istream &is)
template<class Type2 >
static tmp< Field< Type > > NewCalculatedType (const Field< Type2 > &f)
Static Public Member Functions inherited from List< Type >
static const List< Type > & null ()
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
static constexpr label max_size () noexcept
Protected Member Functions inherited from fvPatchField< Type >
bool readValueEntry (const dictionary &dict, IOobjectOption::readOption readOpt=IOobjectOption::LAZY_READ)
void writeValueEntry (Ostream &os) const
void extrapolateInternal ()
Protected Member Functions inherited from fvPatchFieldBase
virtual void readDict (const dictionary &dict)
void setUpdated (bool state) noexcept
void setManipulated (bool state) noexcept
Protected Member Functions inherited from UList< T >
void setAddressableSize (const label n) noexcept
void size (const label n)
void writeEntry (Ostream &os) const
labelRange validateRange (const labelRange &requestedRange) const
UList< T > & operator= (const UList< T > &)=delete
void writeEntry (Ostream &os) const
void writeEntry (Ostream &os) const
Detailed Description
This boundary condition provides a first-order zero-gradient condition for a given scalar field to model time-dependent adsorption-desorption processes.
where
= Equilibrium concentration
= Absorbed at wall
= Adsorption rate constant [1/s]
where
= Maximum concentration
= Langmuir constant
= Local cell value concentration
Usage
Example of the boundary condition specification:
<patchName>
{
    // Mandatory entries
    type                    speciesSorption;
    equilibriumModel        <word>;
    kinematicModel          <word>;
    kabs                    <scalar>;
    kl                      <scalar>;
    max                     <scalar>;
    thickness               <PatchFunction1<scalar>>;
    rhoS                    <scalar>;
    // Optional entries
    dfldp                   <scalarField>;
    mass                    <scalarField>;
    pName                   <word>;
    // Inherited entries
    ...
}
where the entries mean:
Property Description Type Reqd Deflt
type Type name: speciesSorption word yes -
equilibriumModel Equilibrium model word yes -
kinematicModel Kinematic model word yes -
kabs Adsorption rate constant [1/s] scalar yes -
kl Langmuir constant [1/Pa] scalar yes -
max Maximum concentation at wall [mol/kg] scalar yes -
thickness
Solid thickness along the patch
PatchFunction1<scalar> yes -
rhoS Solid density scalar yes -
dfldp Source on cells next to patch scalarField no Zero
mass
Absorbed mass per kg of absorbent [mol/kg]
scalarField no Zero
pName Name of operand pressure field word no p
Options for the equilibriumModel entry:
      Langmuir    | Langmuir model
Options for the kinematicModel entry:
      PseudoFirstOrder    | Pseudo first-order model
The inherited entries are elaborated in:
zeroGradientFvPatchFields.H
PatchFunction1.H
Source files
speciesSorptionFvPatchScalarField.H
speciesSorptionFvPatchScalarField.C
Definition at line 232 of file speciesSorptionFvPatchScalarField.H.
Member Enumeration Documentation
equilibriumModelType
enum equilibriumModelType : char
Enumerator
LANGMUIR
Definition at line 242 of file speciesSorptionFvPatchScalarField.H.
kineticModelType
enum kineticModelType : char
Enumerator
PseudoFirstOrder
Definition at line 248 of file speciesSorptionFvPatchScalarField.H.
Constructor & Destructor Documentation
speciesSorptionFvPatchScalarField() [1/5]
speciesSorptionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 135 of file speciesSorptionFvPatchScalarField.C.
speciesSorptionFvPatchScalarField() [2/5]
speciesSorptionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 155 of file speciesSorptionFvPatchScalarField.C.
References fvPatchField< Type >::operator=(), fvPatchField< Type >::readValueEntry(), and Foam::Zero.
speciesSorptionFvPatchScalarField() [3/5]
speciesSorptionFvPatchScalarField (const speciesSorptionFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 181 of file speciesSorptionFvPatchScalarField.C.
speciesSorptionFvPatchScalarField() [4/5]
speciesSorptionFvPatchScalarField (const speciesSorptionFvPatchScalarField & ptf)
Definition at line 203 of file speciesSorptionFvPatchScalarField.C.
speciesSorptionFvPatchScalarField() [5/5]
speciesSorptionFvPatchScalarField (const speciesSorptionFvPatchScalarField & ptf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 222 of file speciesSorptionFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("speciesSorption")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Reimplemented from zeroGradientFvPatchField< scalar >.
Definition at line 344 of file speciesSorptionFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Reimplemented from zeroGradientFvPatchField< scalar >.
Definition at line 360 of file speciesSorptionFvPatchScalarField.H.
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Reimplemented from fvPatchField< Type >.
Definition at line 244 of file speciesSorptionFvPatchScalarField.C.
rmap()
void rmap (const fvPatchScalarField & ptf, const labelList & addr) virtual
Definition at line 261 of file speciesSorptionFvPatchScalarField.C.
patchSource()
Foam::tmp< Foam::scalarField > patchSource () const virtual
Implements boundarySourcePatch.
Definition at line 281 of file speciesSorptionFvPatchScalarField.C.
References basicThermo::dictName, e, Foam::endl(), forAll, Foam::gMax(), Foam::gMin(), h, Foam::Info, and tmp< T >::New().
mass()
Foam::tmp< Foam::scalarField > mass () const
Definition at line 325 of file speciesSorptionFvPatchScalarField.C.
References tmp< T >::New().
updateCoeffs()
void updateCoeffs () virtual
Reimplemented from fvPatchField< Type >.
Definition at line 332 of file speciesSorptionFvPatchScalarField.C.
References Foam::dimMass, Foam::dimMoles, Foam::endl(), field(), Foam::gMax(), Foam::gMin(), Foam::Info, Foam::max(), Foam::name(), pp(), and Foam::Zero.
write()
void write (Ostream & os) const virtual
Reimplemented from fvPatchField< Type >.
Definition at line 395 of file speciesSorptionFvPatchScalarField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntry(), Ostream::writeEntryIfDifferent(), and fvPatchField< Type >::writeValueEntry().
Member Data Documentation
equilibriumModelTypeNames
const Foam::Enum< Foam::speciesSorptionFvPatchScalarField::equilibriumModelType > equilibriumModelTypeNames static
Definition at line 254 of file speciesSorptionFvPatchScalarField.H.
kinematicModelTypeNames
const Foam::Enum< Foam::speciesSorptionFvPatchScalarField::kineticModelType > kinematicModelTypeNames static
Definition at line 257 of file speciesSorptionFvPatchScalarField.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/reactionThermo/derivedFvPatchFields/speciesSorption/speciesSorptionFvPatchScalarField.H
src/thermophysicalModels/reactionThermo/derivedFvPatchFields/speciesSorption/speciesSorptionFvPatchScalarField.C