OpenFOAM: faFieldDecomposer::fieldsCache::privateCache Class Reference
faFieldDecomposer::fieldsCache::privateCache Class Reference
Public Member Functions
label size () const noexcept
bool empty () const noexcept
void readAll (const faMesh &mesh, const IOobjectList &objects)
template<class BoolListType >
void readAll (const BoolListType &haveMeshOnProc, const faMeshSubset *&subsetter, const faMesh &mesh, IOobjectList &objects)
void decomposeAll (const faFieldDecomposer &decomposer, bool report) const
Static Public Member Functions
template<class GeoField >
static void decompose (const faFieldDecomposer &decomposer, const PtrList< GeoField > &fields, bool report)
Public Attributes
PtrList< GeometricField< scalar, faPatchField, areaMesh > > scalarAreaFields_
PtrList< GeometricField< scalar, faePatchField, edgeMesh > > scalarEdgeFields_
PtrList< GeometricField< vector, faPatchField, areaMesh > > vectorAreaFields_
PtrList< GeometricField< vector, faePatchField, edgeMesh > > vectorEdgeFields_
PtrList< GeometricField< sphericalTensor, faPatchField, areaMesh > > sphericalTensorAreaFields_
PtrList< GeometricField< sphericalTensor, faePatchField, edgeMesh > > sphericalTensorEdgeFields_
PtrList< GeometricField< symmTensor, faPatchField, areaMesh > > symmTensorAreaFields_
PtrList< GeometricField< symmTensor, faePatchField, edgeMesh > > symmTensorEdgeFields_
PtrList< GeometricField< tensor, faPatchField, areaMesh > > tensorAreaFields_
PtrList< GeometricField< tensor, faePatchField, edgeMesh > > tensorEdgeFields_
Detailed Description
Definition at line 34 of file faFieldDecomposerCache.C.
Member Function Documentation
size()
label size () const inline noexcept
Definition at line 50 of file faFieldDecomposerCache.C.
References doLocalCode.
Referenced by faFieldDecomposer::fieldsCache::privateCache::empty().
empty()
bool empty () const inline noexcept
Definition at line 71 of file faFieldDecomposerCache.C.
References faFieldDecomposer::fieldsCache::privateCache::size().
readAll() [1/2]
void readAll (const faMesh & mesh, const IOobjectList & objects) inline
Definition at line 73 of file faFieldDecomposerCache.C.
References doLocalCode.
readAll() [2/2]
template<class BoolListType > void readAll (const BoolListType & haveMeshOnProc, const faMeshSubset *& subsetter, const faMesh & mesh, IOobjectList & objects) inline
Definition at line 114 of file faFieldDecomposerCache.C.
References doLocalCode.
decompose()
template<class GeoField > static void decompose (const faFieldDecomposer & decomposer, const PtrList< GeoField > & fields, bool report) inline static
Definition at line 153 of file faFieldDecomposerCache.C.
References faFieldDecomposer::decomposeFields(), fields, Foam::flatOutput(), Foam::Info, Foam::PtrListOps::names(), and Foam::nl.
decomposeAll()
void decomposeAll (const faFieldDecomposer & decomposer, bool report) const inline
Definition at line 174 of file faFieldDecomposerCache.C.
References doLocalCode.
Member Data Documentation
scalarAreaFields_
PtrList<GeometricField< scalar , faPatchField, areaMesh> > scalarAreaFields_
Definition at line 43 of file faFieldDecomposerCache.C.
scalarEdgeFields_
PtrList<GeometricField< scalar , faePatchField, edgeMesh> > scalarEdgeFields_
Definition at line 43 of file faFieldDecomposerCache.C.
vectorAreaFields_
PtrList<GeometricField< vector , faPatchField, areaMesh> > vectorAreaFields_
Definition at line 44 of file faFieldDecomposerCache.C.
vectorEdgeFields_
PtrList<GeometricField< vector , faePatchField, edgeMesh> > vectorEdgeFields_
Definition at line 44 of file faFieldDecomposerCache.C.
sphericalTensorAreaFields_
PtrList<GeometricField< sphericalTensor , faPatchField, areaMesh> > sphericalTensorAreaFields_
Definition at line 45 of file faFieldDecomposerCache.C.
sphericalTensorEdgeFields_
PtrList<GeometricField< sphericalTensor , faePatchField, edgeMesh> > sphericalTensorEdgeFields_
Definition at line 45 of file faFieldDecomposerCache.C.
symmTensorAreaFields_
PtrList<GeometricField< symmTensor , faPatchField, areaMesh> > symmTensorAreaFields_
Definition at line 46 of file faFieldDecomposerCache.C.
symmTensorEdgeFields_
PtrList<GeometricField< symmTensor , faePatchField, edgeMesh> > symmTensorEdgeFields_
Definition at line 46 of file faFieldDecomposerCache.C.
tensorAreaFields_
PtrList<GeometricField< tensor , faPatchField, areaMesh> > tensorAreaFields_
Definition at line 47 of file faFieldDecomposerCache.C.
tensorEdgeFields_
PtrList<GeometricField< tensor , faePatchField, edgeMesh> > tensorEdgeFields_
Definition at line 47 of file faFieldDecomposerCache.C.
The documentation for this class was generated from the following file:
src/parallel/decompose/faDecompose/faFieldDecomposerCache.C