OpenFOAM: Callback< CallbackType > Class Template Reference
Callback< CallbackType > Class Template Reference
Abstract class to handle automatic call-back registration with the CallbackRegistry. Derive from this class and extend by adding the appropriate callback functions.
#include <Callback.H>
Public Member Functions
Callback (CallbackRegistry< CallbackType > &)
Callback (const Callback< CallbackType > &)
virtual ~Callback ()
bool checkIn ()
bool checkOut ()
Detailed Description
template<class CallbackType>
class Foam::Callback< CallbackType >
Abstract class to handle automatic call-back registration with the CallbackRegistry. Derive from this class and extend by adding the appropriate callback functions.
Source files
Callback.H
Callback.C
Definition at line 49 of file Callback.H.
Constructor & Destructor Documentation
Callback() [1/2]
template<class CallbackType > Callback (CallbackRegistry< CallbackType > & cbr)
Definition at line 27 of file Callback.C.
References Callback< CallbackType >::checkIn().
Callback() [2/2]
template<class CallbackType > Callback (const Callback< CallbackType > & cb)
Definition at line 36 of file Callback.C.
References Callback< CallbackType >::checkIn().
~Callback()
template<class CallbackType > ~Callback () virtual
Definition at line 47 of file Callback.C.
Member Function Documentation
checkIn()
template<class CallbackType > bool checkIn ()
Definition at line 56 of file Callback.C.
References PtrList< T >::append().
Referenced by Callback< CallbackType >::Callback(), and Callback< CallbackType >::Callback().
checkOut()
template<class CallbackType > bool checkOut ()
Definition at line 69 of file Callback.C.
The documentation for this class was generated from the following files:
src/OpenFOAM/db/Callback/Callback.H
src/OpenFOAM/db/Callback/Callback.C