OpenFOAM: Schaeffer Class Reference
Schaeffer Class Reference
#include <SchaefferFrictionalStress.H>
Public Member Functions
TypeName ("Schaeffer")
Schaeffer (const dictionary &dict)
virtual ~Schaeffer ()
virtual tmp< volScalarField > frictionalPressure (const phaseModel &phase, const dimensionedScalar &alphaMinFriction, const dimensionedScalar &alphaMax) const
virtual tmp< volScalarField > frictionalPressurePrime (const phaseModel &phase, const dimensionedScalar &alphaMinFriction, const dimensionedScalar &alphaMax) const
virtual tmp< volScalarField > nu (const phaseModel &phase, const dimensionedScalar &alphaMinFriction, const dimensionedScalar &alphaMax, const volScalarField &pf, const volSymmTensorField &D) const
virtual bool read ()
TypeName ("Schaeffer")
Schaeffer (const dictionary &dict)
virtual ~Schaeffer ()
virtual tmp< volScalarField > frictionalPressure (const phaseModel &phase, const dimensionedScalar &alphaMinFriction, const dimensionedScalar &alphaMax) const
virtual tmp< volScalarField > frictionalPressurePrime (const phaseModel &phase, const dimensionedScalar &alphaMinFriction, const dimensionedScalar &alphaMax) const
virtual tmp< volScalarField > nu (const phaseModel &phase, const dimensionedScalar &alphaMinFriction, const dimensionedScalar &alphaMax, const volScalarField &pf, const volSymmTensorField &D) const
virtual bool read ()
Public Member Functions inherited from frictionalStressModel
TypeName ("frictionalStressModel")
declareRunTimeSelectionTable (autoPtr, frictionalStressModel, dictionary,(const dictionary &dict),(dict))
frictionalStressModel (const dictionary &dict)
virtual ~frictionalStressModel ()=default
TypeName ("frictionalStressModel")
declareRunTimeSelectionTable (autoPtr, frictionalStressModel, dictionary,(const dictionary &dict),(dict))
frictionalStressModel (const dictionary &dict)
virtual ~frictionalStressModel ()=default
Additional Inherited Members
Static Public Member Functions inherited from frictionalStressModel
static autoPtr< frictionalStressModel > New (const dictionary &dict)
static autoPtr< frictionalStressModel > New (const dictionary &dict)
Protected Attributes inherited from frictionalStressModel
const dictionary & dict_
Detailed Description
Source files
SchaefferFrictionalStress.H
SchaefferFrictionalStress.C
Source files
SchaefferFrictionalStress.H
SchaefferFrictionalStress.C
Definition at line 49 of file SchaefferFrictionalStress.H.
Constructor & Destructor Documentation
Schaeffer() [1/2]
Schaeffer (const dictionary & dict)
Definition at line 49 of file SchaefferFrictionalStress.C.
References Foam::degToRad(), and Foam::dimless.
~Schaeffer() [1/2]
~Schaeffer () virtual
Definition at line 64 of file SchaefferFrictionalStress.C.
Schaeffer() [2/2]
Schaeffer (const dictionary & dict)
~Schaeffer() [2/2]
virtual ~Schaeffer () virtual
Member Function Documentation
TypeName() [1/2]
TypeName ("Schaeffer")
frictionalPressure() [1/2]
Foam::tmp< Foam::volScalarField > frictionalPressure (const phaseModel & phase, const dimensionedScalar & alphaMinFriction, const dimensionedScalar & alphaMax) const virtual
Implements frictionalStressModel.
Definition at line 71 of file SchaefferFrictionalStress.C.
References alpha, Foam::max(), and Foam::pow().
frictionalPressurePrime() [1/2]
Foam::tmp< Foam::volScalarField > frictionalPressurePrime (const phaseModel & phase, const dimensionedScalar & alphaMinFriction, const dimensionedScalar & alphaMax) const virtual
Implements frictionalStressModel.
Definition at line 88 of file SchaefferFrictionalStress.C.
References alpha, Foam::max(), and Foam::pow().
nu() [1/2]
Foam::tmp< Foam::volScalarField > nu (const phaseModel & phase, const dimensionedScalar & alphaMinFriction, const dimensionedScalar & alphaMax, const volScalarField & pf, const volSymmTensorField & D) const virtual
Implements frictionalStressModel.
Definition at line 105 of file SchaefferFrictionalStress.C.
References alpha, GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), coupled(), D, forAll, Foam::invariantII(), Foam::mag(), DimensionedField< Type, GeoMesh >::mesh(), IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, patches, Foam::sin(), Foam::sqr(), Foam::sqrt(), Foam::tr(), U, and Foam::Zero.
read() [1/2]
bool read () virtual
Implements frictionalStressModel.
Definition at line 176 of file SchaefferFrictionalStress.C.
References Foam::degToRad().
TypeName() [2/2]
TypeName ("Schaeffer")
frictionalPressure() [2/2]
virtual tmp< volScalarField > frictionalPressure (const phaseModel & phase, const dimensionedScalar & alphaMinFriction, const dimensionedScalar & alphaMax) const virtual
Implements frictionalStressModel.
frictionalPressurePrime() [2/2]
virtual tmp< volScalarField > frictionalPressurePrime (const phaseModel & phase, const dimensionedScalar & alphaMinFriction, const dimensionedScalar & alphaMax) const virtual
Implements frictionalStressModel.
nu() [2/2]
virtual tmp< volScalarField > nu (const phaseModel & phase, const dimensionedScalar & alphaMinFriction, const dimensionedScalar & alphaMax, const volScalarField & pf, const volSymmTensorField & D) const virtual
Implements frictionalStressModel.
read() [2/2]
virtual bool read () virtual
Implements frictionalStressModel.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/twoPhaseCompressibleTurbulenceModels/kineticTheoryModels/frictionalStressModel/Schaeffer/SchaefferFrictionalStress.H
src/phaseSystemModels/twoPhaseEuler/phaseCompressibleTurbulenceModels/kineticTheoryModels/frictionalStressModel/Schaeffer/SchaefferFrictionalStress.H
src/phaseSystemModels/reactingEuler/twoPhaseCompressibleTurbulenceModels/kineticTheoryModels/frictionalStressModel/Schaeffer/SchaefferFrictionalStress.C
src/phaseSystemModels/twoPhaseEuler/phaseCompressibleTurbulenceModels/kineticTheoryModels/frictionalStressModel/Schaeffer/SchaefferFrictionalStress.C