OpenFOAM: faD2dt2Scheme< Type > Class Template Reference
faD2dt2Scheme< Type > Class Template Reference abstract
Abstract base class for d2dt2 schemes.
#include <faD2dt2Scheme.H>
Public Member Functions
virtual const word & type () const =0
declareRunTimeSelectionTable (tmp, faD2dt2Scheme, Istream,(const faMesh &mesh, Istream &schemeData),(mesh, schemeData))
faD2dt2Scheme (const faMesh &mesh)
faD2dt2Scheme (const faMesh &mesh, Istream &)
virtual ~faD2dt2Scheme ()
const faMesh & mesh () const
virtual tmp< GeometricField< Type, faPatchField, areaMesh > > facD2dt2 (const dimensioned< Type >)=0
virtual tmp< GeometricField< Type, faPatchField, areaMesh > > facD2dt2 (const GeometricField< Type, faPatchField, areaMesh > &)=0
virtual tmp< GeometricField< Type, faPatchField, areaMesh > > facD2dt2 (const dimensionedScalar &, const GeometricField< Type, faPatchField, areaMesh > &)=0
virtual tmp< GeometricField< Type, faPatchField, areaMesh > > facD2dt2 (const areaScalarField &, const GeometricField< Type, faPatchField, areaMesh > &)=0
virtual tmp< faMatrix< Type > > famD2dt2 (const GeometricField< Type, faPatchField, areaMesh > &)=0
virtual tmp< faMatrix< Type > > famD2dt2 (const dimensionedScalar &, const GeometricField< Type, faPatchField, areaMesh > &)=0
virtual tmp< faMatrix< Type > > famD2dt2 (const areaScalarField &, const GeometricField< Type, faPatchField, areaMesh > &)=0
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Static Public Member Functions
static tmp< faD2dt2Scheme< Type > > New (const faMesh &mesh, Istream &schemeData)
Protected Member Functions
faD2dt2Scheme (const faD2dt2Scheme &)=delete
void operator= (const faD2dt2Scheme &)=delete
Protected Attributes
const faMesh & mesh_
Detailed Description
template<class Type>
class Foam::fa::faD2dt2Scheme< Type >
Abstract base class for d2dt2 schemes.
Source files
faD2dt2Scheme.H
faD2dt2Scheme.C
Definition at line 62 of file faD2dt2Scheme.H.
Constructor & Destructor Documentation
faD2dt2Scheme() [1/3]
template<class Type > faD2dt2Scheme (const faD2dt2Scheme< Type > &) protected delete
faD2dt2Scheme() [2/3]
template<class Type > faD2dt2Scheme (const faMesh & mesh) inline
Definition at line 104 of file faD2dt2Scheme.H.
faD2dt2Scheme() [3/3]
template<class Type > faD2dt2Scheme (const faMesh & mesh, Istream &) inline
Definition at line 110 of file faD2dt2Scheme.H.
~faD2dt2Scheme()
template<class Type > ~faD2dt2Scheme () virtual
Definition at line 85 of file faD2dt2Scheme.C.
Member Function Documentation
operator=()
template<class Type > void operator= (const faD2dt2Scheme< Type > &) protected delete
type()
template<class Type > virtual const word & type () const pure virtual
declareRunTimeSelectionTable()
template<class Type > declareRunTimeSelectionTable (tmp , faD2dt2Scheme< Type > , Istream , (const faMesh &mesh, Istream &schemeData) , (mesh, schemeData))
New()
template<class Type > tmp< faD2dt2Scheme< Type > > New (const faMesh & mesh, Istream & schemeData) static
Definition at line 42 of file faD2dt2Scheme.C.
References Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, FatalIOErrorInLookup, InfoInFunction, mesh, and Foam::nl.
Referenced by Foam::fac::d2dt2(), Foam::fam::d2dt2(), Foam::fac::d2dt2(), Foam::fac::d2dt2(), Foam::fam::d2dt2(), Foam::fac::d2dt2(), and Foam::fam::d2dt2().
mesh()
template<class Type > const faMesh & mesh () const inline
Definition at line 133 of file faD2dt2Scheme.H.
References faD2dt2Scheme< Type >::mesh_.
Referenced by EulerFaD2dt2Scheme< Type >::mesh().
facD2dt2() [1/4]
template<class Type > virtual tmp< GeometricField< Type, faPatchField, areaMesh > > facD2dt2 (const dimensioned< Type >) pure virtual
Implemented in EulerFaD2dt2Scheme< Type >.
facD2dt2() [2/4]
template<class Type > virtual tmp< GeometricField< Type, faPatchField, areaMesh > > facD2dt2 (const GeometricField< Type, faPatchField, areaMesh > &) pure virtual
Implemented in EulerFaD2dt2Scheme< Type >.
facD2dt2() [3/4]
template<class Type > virtual tmp< GeometricField< Type, faPatchField, areaMesh > > facD2dt2 (const dimensionedScalar & , const GeometricField< Type, faPatchField, areaMesh > &) pure virtual
Implemented in EulerFaD2dt2Scheme< Type >.
facD2dt2() [4/4]
template<class Type > virtual tmp< GeometricField< Type, faPatchField, areaMesh > > facD2dt2 (const areaScalarField & , const GeometricField< Type, faPatchField, areaMesh > &) pure virtual
Implemented in EulerFaD2dt2Scheme< Type >.
famD2dt2() [1/3]
template<class Type > virtual tmp< faMatrix< Type > > famD2dt2 (const GeometricField< Type, faPatchField, areaMesh > &) pure virtual
Implemented in EulerFaD2dt2Scheme< Type >.
famD2dt2() [2/3]
template<class Type > virtual tmp< faMatrix< Type > > famD2dt2 (const dimensionedScalar & , const GeometricField< Type, faPatchField, areaMesh > &) pure virtual
Implemented in EulerFaD2dt2Scheme< Type >.
famD2dt2() [3/3]
template<class Type > virtual tmp< faMatrix< Type > > famD2dt2 (const areaScalarField & , const GeometricField< Type, faPatchField, areaMesh > &) pure virtual
Implemented in EulerFaD2dt2Scheme< Type >.
Member Data Documentation
mesh_
template<class Type > const faMesh& mesh_ protected
Definition at line 71 of file faD2dt2Scheme.H.
Referenced by faD2dt2Scheme< Type >::mesh().
The documentation for this class was generated from the following files:
src/finiteArea/finiteArea/d2dt2Schemes/faD2dt2Scheme/faD2dt2Scheme.H
src/finiteArea/finiteArea/d2dt2Schemes/faD2dt2Scheme/faD2dt2Scheme.C