OpenFOAM: Chung Class Reference
Chung Class Reference
Chung compressibility model.
#include <Chung.H>
Public Member Functions
TypeName ("Chung")
Chung (const dictionary &compressibilityProperties, const volScalarField &gamma, const word &psiName="psi")
~Chung ()
void correct ()
bool read (const dictionary &compressibilityProperties)
Public Member Functions inherited from barotropicCompressibilityModel
TypeName ("barotropicCompressibilityModel")
declareRunTimeSelectionTable (autoPtr, barotropicCompressibilityModel, dictionary,(const dictionary &compressibilityProperties, const volScalarField &gamma, const word &psiName),(compressibilityProperties, gamma, psiName))
barotropicCompressibilityModel (const dictionary &compressibilityProperties, const volScalarField &gamma, const word &psiName="psi")
virtual ~barotropicCompressibilityModel ()=default
const dictionary & compressibilityProperties () const
const volScalarField & psi () const
Additional Inherited Members
Static Public Member Functions inherited from barotropicCompressibilityModel
static autoPtr< barotropicCompressibilityModel > New (const dictionary &compressibilityProperties, const volScalarField &gamma, const word &psiName="psi")
Protected Member Functions inherited from barotropicCompressibilityModel
barotropicCompressibilityModel (const barotropicCompressibilityModel &)=delete
void operator= (const barotropicCompressibilityModel &)=delete
Protected Attributes inherited from barotropicCompressibilityModel
dictionary compressibilityProperties_
volScalarField psi_
const volScalarField & gamma_
Detailed Description
Chung compressibility model.
Source files
Chung.H
Chung.C
Definition at line 49 of file Chung.H.
Constructor & Destructor Documentation
Chung()
Chung (const dictionary & compressibilityProperties, const volScalarField & gamma, const word & psiName = "psi")
Definition at line 42 of file Chung.C.
References Chung::correct(), Foam::dimCompressibility, Foam::dimDensity, and Foam::dimPressure.
~Chung()
~Chung () inline
Definition at line 80 of file Chung.H.
Member Function Documentation
TypeName()
TypeName ("Chung")
correct()
void correct () virtual
Implements barotropicCompressibilityModel.
Definition at line 81 of file Chung.C.
References Foam::sqr(), and Foam::sqrt().
Referenced by Chung::Chung().
read()
bool read (const dictionary & compressibilityProperties) virtual
Implements barotropicCompressibilityModel.
Definition at line 100 of file Chung.C.
References barotropicCompressibilityModel::read().
The documentation for this class was generated from the following files:
src/thermophysicalModels/barotropicCompressibilityModel/Chung/Chung.H
src/thermophysicalModels/barotropicCompressibilityModel/Chung/Chung.C