OpenFOAM: phaseTransferModel Class Reference
phaseTransferModel Class Reference abstract
#include <phaseTransferModel.H>
Public Member Functions
TypeName ("phaseTransferModel")
declareRunTimeSelectionTable (autoPtr, phaseTransferModel, dictionary,(const dictionary &dict, const phasePair &pair),(dict, pair))
phaseTransferModel (const dictionary &dict, const phasePair &pair)
virtual ~phaseTransferModel ()=default
virtual tmp< volScalarField > dmdt () const =0
Static Public Member Functions
static autoPtr< phaseTransferModel > New (const dictionary &dict, const phasePair &pair)
Static Public Attributes
static const dimensionSet dimDmdt
Protected Attributes
const phasePair & pair_
Detailed Description
Source files
phaseTransferModel.H
phaseTransferModel.C
Definition at line 51 of file phaseTransferModel.H.
Constructor & Destructor Documentation
phaseTransferModel()
phaseTransferModel (const dictionary & dict, const phasePair & pair)
Definition at line 41 of file phaseTransferModel.C.
~phaseTransferModel()
virtual ~phaseTransferModel () virtual default
Member Function Documentation
TypeName()
TypeName ("phaseTransferModel")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , phaseTransferModel , dictionary , (const dictionary &dict, const phasePair &pair) , (dict, pair))
New()
Foam::autoPtr< Foam::phaseTransferModel > New (const dictionary & dict, const phasePair & pair) static
Definition at line 54 of file phaseTransferModel.C.
References Foam::abort(), dict, Foam::endl(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), and Foam::Info.
dmdt()
virtual tmp< volScalarField > dmdt () const pure virtual
Implemented in deposition.
Member Data Documentation
pair_
const phasePair& pair_ protected
Definition at line 58 of file phaseTransferModel.H.
dimDmdt
const Foam::dimensionSet dimDmdt static
Initial value:
=
    Foam::dimDensity/Foam::dimTime
Definition at line 85 of file phaseTransferModel.H.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/interfacialModels/phaseTransferModels/phaseTransferModel/phaseTransferModel.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/interfacialModels/phaseTransferModels/phaseTransferModel/phaseTransferModel.C