OpenFOAM: gltfWriter Class Reference
gltfWriter Class Reference
A coordSet(s) writer in glTF v2 format, which is particularly useful for writing track data.
#include <gltfCoordSetWriter.H>
Public Types
enum class fieldOption : char { NONE , UNIFORM , FIELD }
Public Member Functions
TypeNameNoDebug ("gltf")
gltfWriter ()
gltfWriter (const dictionary &options)
gltfWriter (const coordSet &coords, const fileName &outputPath, const dictionary &options=dictionary())
gltfWriter (const UPtrList< coordSet > &tracks, const fileName &outputPath, const dictionary &options=dictionary())
virtual ~gltfWriter ()
virtual fileName path () const
virtual void close (bool force=false)
virtual void beginTime (const Time &t)
virtual void beginTime (const instant &inst)
virtual void endTime ()
declareCoordSetWriterWriteMethod (label)
declareCoordSetWriterWriteMethod (scalar)
declareCoordSetWriterWriteMethod (vector)
declareCoordSetWriterWriteMethod (sphericalTensor)
declareCoordSetWriterWriteMethod (symmTensor)
declareCoordSetWriterWriteMethod (tensor)
template<class Type >
Foam::fileName writeTemplate (const word &fieldName, const UPtrList< const Field< Type > > &fieldPtrs)
template<class Type >
Foam::fileName writeTemplate_animate (const word &fieldName, const UPtrList< const Field< Type > > &fieldPtrs)
template<class Type >
Foam::fileName writeTemplate (const word &fieldName, const Field< Type > &values)
template<class Type >
Foam::fileName writeTemplate (const word &fieldName, const List< Field< Type > > &fieldValues)
Public Member Functions inherited from coordSetWriter
TypeName ("coordSetWriter")
declareRunTimeSelectionTable (autoPtr, coordSetWriter, word,(),())
declareRunTimeSelectionTable (autoPtr, coordSetWriter, wordDict,(const dictionary &writeOptions),(writeOptions))
coordSetWriter ()
coordSetWriter (const dictionary &options)
virtual ~coordSetWriter ()
virtual bool buffering () const
virtual bool buffering (const bool on)
virtual bool enabled () const
virtual bool needsUpdate () const
virtual bool wroteData () const
virtual bool expire ()
virtual void clear ()
virtual void setCoordinates (const coordSet *coords)
virtual void setCoordinates (const coordSet &coords)
virtual void setTracks (const UPtrList< coordSet > &tracks)
virtual void setTrackTimes (const UList< scalarField > &times)
label numPoints () const
label numTracks () const
bool hasCoords () const
bool empty () const
bool is_open () const noexcept
label nFields () const noexcept
label nFields (const label n) noexcept
bool useTracks () const noexcept
bool useTracks (const bool on) noexcept
bool useTimeDir () const noexcept
bool useTimeDir (const bool on) noexcept
bool verbose () const noexcept
bool verbose (bool on) noexcept
bool hasTime () const
const word & timeName () const
scalar timeValue () const
void setTime (const instant &inst)
void setTime (scalar timeValue)
void setTime (scalar timeValue, const word &timeName)
void unsetTime ()
virtual void open (const fileName &outputPath)
TBD: virtual fileName write() = 0;.
virtual void open (const coordSet &coords, const fileName &outputPath)
virtual void open (const UPtrList< coordSet > &tracks, const fileName &outputPath)
virtual InfoProxy< coordSetWriter > info () const
virtual fileName write (const word &fieldName, const Field< label > &field)=0
Write field of label (point data)
virtual fileName write (const word &fieldName, const List< Field< label > > &fieldValues)=0
Write track fields of label (point data)
virtual fileName write (const word &fieldName, const Field< scalar > &field)=0
Write field of scalar (point data)
virtual fileName write (const word &fieldName, const List< Field< scalar > > &fieldValues)=0
Write track fields of scalar (point data)
virtual fileName write (const word &fieldName, const Field< vector > &field)=0
Write field of vector (point data)
virtual fileName write (const word &fieldName, const List< Field< vector > > &fieldValues)=0
Write track fields of vector (point data)
virtual fileName write (const word &fieldName, const Field< sphericalTensor > &field)=0
Write field of sphericalTensor (point data)
virtual fileName write (const word &fieldName, const List< Field< sphericalTensor > > &fieldValues)=0
Write track fields of sphericalTensor (point data)
virtual fileName write (const word &fieldName, const Field< symmTensor > &field)=0
Write field of symmTensor (point data)
virtual fileName write (const word &fieldName, const List< Field< symmTensor > > &fieldValues)=0
Write track fields of symmTensor (point data)
virtual fileName write (const word &fieldName, const Field< tensor > &field)=0
Write field of tensor (point data)
virtual fileName write (const word &fieldName, const List< Field< tensor > > &fieldValues)=0
Write track fields of tensor (point data)
template<class Type >
Foam::UPtrList< const Foam::Field< Type > > repackageFields (const Field< Type > &field)
template<class Type >
Foam::UPtrList< const Foam::Field< Type > > repackageFields (const UList< Field< Type > > &fieldValues)
Static Public Attributes
static const Enum< fieldOption > fieldOptionNames_
Additional Inherited Members
Static Public Member Functions inherited from coordSetWriter
static dictionary formatOptions (const dictionary &dict, const word &formatName, const word &entryName="formatOptions")
static dictionary formatOptions (const dictionary &dict, const dictionary &setDict, const word &formatName, const word &entryName="formatOptions")
static bool supportedType (const word &writeType)
static autoPtr< coordSetWriter > New (const word &writeFormat)
static autoPtr< coordSetWriter > New (const word &writeFormat, const dictionary &writeOptions)
static word suffix (const word &fldName, const word &fileExt=word::null)
static word suffix (const wordList &fieldNames, const word &fileExt=word::null)
Protected Member Functions inherited from coordSetWriter
void appendField (const word &fieldName, const Field< label > &vals)
void appendField (const word &fieldName, const Field< scalar > &vals)
void appendField (const word &fieldName, const Field< vector > &vals)
void appendField (const word &fieldName, const Field< sphericalTensor > &vals)
void appendField (const word &fieldName, const Field< symmTensor > &vals)
void appendField (const word &fieldName, const Field< tensor > &vals)
void clearBuffers ()
label nDataColumns () const
virtual bool writeBuffered ()
void writeBufferContents (Ostream &os, const coordSet &coords, const char *sep) const
void getBufferLine (DynamicList< scalar > &buf, const coordSet &coords, const label pointi) const
fileName getExpectedPath (const word &fileExt=word::null) const
fileName getFieldPrefixedPath (const word &fieldName, const word &fileExt=word::null) const
void checkOpen () const
virtual bool merge () const
template<class Type >
fileName writeTemplate (const word &fieldName, const Field< Type > &values)
template<class Type >
fileName writeTemplate (const word &fieldName, const List< Field< Type > > &fieldValues)
coordSetWriter (const coordSetWriter &)=delete
void operator= (const coordSetWriter &)=delete
Static Protected Member Functions inherited from coordSetWriter
static void writeLine (Ostream &, const UList< word > &, const char *sep)
static void writeLine (Ostream &, const UList< scalar > &, const char *sep)
template<class Type >
static UPtrList< const Field< Type > > repackageFields (const Field< Type > &field)
template<class Type >
static UPtrList< const Field< Type > > repackageFields (const UList< Field< Type > > &fieldValues)
template<class Type >
static void writeTable (Ostream &os, const coordSet &coords, const UList< Type > &values, const char *sep)
Protected Attributes inherited from coordSetWriter
UPtrList< const coordSet > coords_
List< scalarField > trackTimes_
bool upToDate_
bool wroteGeom_
bool buffering_
bool useTracks_
bool useTimeDir_
bool verbose_
label nFields_
instant currTime_
fileName outputPath_
DynamicList< word > labelNames_
PtrDynList< Field< label > > labelFields_
DynamicList< word > scalarNames_
PtrDynList< Field< scalar > > scalarFields_
DynamicList< word > vectorNames_
PtrDynList< Field< vector > > vectorFields_
DynamicList< word > sphericalTensorNames_
PtrDynList< Field< sphericalTensor > > sphericalTensorFields_
DynamicList< word > symmTensorNames_
PtrDynList< Field< symmTensor > > symmTensorFields_
DynamicList< word > tensorNames_
PtrDynList< Field< tensor > > tensorFields_
Detailed Description
A coordSet(s) writer in glTF v2 format, which is particularly useful for writing track data.
Two files are generated:
filename.bin : a binary file containing all scene entities
filename.gltf : a JSON file that ties fields to the binary data
The output can contain both geometry and fields, with additional support for colours using a user-supplied colour map, and animation of particle tracks.
Controls are provided via the optional formatOptions dictionary.
For non-particle track data:
formatOptions
{
    // Apply colours flag (yes | no ) [optional]
    colours     yes;
    // List of options per field
    fieldInfo
    {
        p
        {
            // Colour map [optional]
            colourMap       <colourMap>;
            // Colour map minimum and maximum limits [optional]
            // Uses field min and max if not specified
            min             0;
            max             1;
            // Alpha channel [optional] (<scalar>)
            alpha           0.5;
        }
    }
}
\verbatim
For particle tracks:
\verbatim
formatOptions
{
    // Apply colours flag (yes | no) [optional]
    colours     yes;
    // Animate tracks (yes | no) [optional]
    animate     yes;
    // Animation properties [optional]
    animationInfo
    {
        // Colour map [optional]
        colourMap       <colourMap>;
        // Colour [optional] (<vector> | uniform | field)
        colour          (1 0 0); // RGB in range [0-1]
        //colour          uniform;
        //colourValue     (1 0 0); // RGB in range [0-1]
        //colour          field;
        //colourField     d;
        // Colour map minimum and maximum limits [optional]
        // Note: for colour = field option
        // Uses field min and max if not specified
        min             0;
        max             1;
        // Alpha channel [optional] (<scalar>)
        alpha           0.5;
    }
}
Note
When writing particle animations, the particle field and colour properties correspond to initial particle state (first data point) and cannot be animated (limitation of the file format).
For more information on the specification see https://www.khronos.org/registry/glTF/
Source files
gltfCoordSetWriter.H
gltfCoordSetWriter.C
Definition at line 136 of file gltfCoordSetWriter.H.
Member Enumeration Documentation
fieldOption
enum class fieldOption : char strong
Enumerator
NONE
Placeholder type (unnamed)
UNIFORM
Uniform value.
FIELD
Field value.
Definition at line 145 of file gltfCoordSetWriter.H.
Constructor & Destructor Documentation
gltfWriter() [1/4]
gltfWriter ()
Definition at line 287 of file gltfCoordSetWriter.C.
gltfWriter() [2/4]
gltfWriter (const dictionary & options) explicit
Definition at line 301 of file gltfCoordSetWriter.C.
gltfWriter() [3/4]
gltfWriter (const coordSet & coords, const fileName & outputPath, const dictionary & options = dictionary())
Definition at line 326 of file gltfCoordSetWriter.C.
References coordSetWriter::open().
gltfWriter() [4/4]
gltfWriter (const UPtrList< coordSet > & tracks, const fileName & outputPath, const dictionary & options = dictionary())
Definition at line 339 of file gltfCoordSetWriter.C.
References coordSetWriter::open().
~gltfWriter()
~gltfWriter () virtual
Definition at line 354 of file gltfCoordSetWriter.C.
Member Function Documentation
TypeNameNoDebug()
TypeNameNoDebug ("gltf")
path()
Foam::fileName path () const virtual
Implements coordSetWriter.
Definition at line 362 of file gltfCoordSetWriter.C.
close()
void close (bool force = false) virtual
Reimplemented from coordSetWriter.
Definition at line 371 of file gltfCoordSetWriter.C.
References coordSetWriter::close().
beginTime() [1/2]
void beginTime (const Time & t) virtual
Reimplemented from coordSetWriter.
Definition at line 378 of file gltfCoordSetWriter.C.
References coordSetWriter::beginTime().
beginTime() [2/2]
void beginTime (const instant & inst) virtual
Reimplemented from coordSetWriter.
Definition at line 385 of file gltfCoordSetWriter.C.
References coordSetWriter::beginTime().
endTime()
void endTime () virtual
Reimplemented from coordSetWriter.
Definition at line 392 of file gltfCoordSetWriter.C.
References coordSetWriter::endTime().
declareCoordSetWriterWriteMethod() [1/6]
declareCoordSetWriterWriteMethod (label)
declareCoordSetWriterWriteMethod() [2/6]
declareCoordSetWriterWriteMethod (scalar)
declareCoordSetWriterWriteMethod() [3/6]
declareCoordSetWriterWriteMethod (vector)
declareCoordSetWriterWriteMethod() [4/6]
declareCoordSetWriterWriteMethod (sphericalTensor)
declareCoordSetWriterWriteMethod() [5/6]
declareCoordSetWriterWriteMethod (symmTensor)
declareCoordSetWriterWriteMethod() [6/6]
declareCoordSetWriterWriteMethod (tensor)
writeTemplate() [1/3]
template<class Type > Foam::fileName writeTemplate (const word & fieldName, const UPtrList< const Field< Type > > & fieldPtrs)
Definition at line 402 of file gltfCoordSetWriter.C.
References alpha, Foam::component(), dict, Foam::exit(), Foam::FatalError, FatalErrorInFunction, field(), forAll, Foam::getBoundedColours(), Foam::max(), Foam::min(), Foam::minMax(), Foam::minMaxMag(), Foam::name(), Foam::nl, path(), UPtrList< T >::size(), and dictionary::subOrEmptyDict().
writeTemplate_animate()
template<class Type > Foam::fileName writeTemplate_animate (const word & fieldName, const UPtrList< const Field< Type > > & fieldPtrs)
Definition at line 508 of file gltfCoordSetWriter.C.
References PtrList< T >::clear(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, field(), forAll, Foam::getAnimationColour(), Foam::name(), Foam::nl, path(), UPtrList< T >::size(), and Foam::Zero.
writeTemplate() [2/3]
template<class Type > Foam::fileName writeTemplate (const word & fieldName, const Field< Type > & values)
Definition at line 712 of file gltfCoordSetWriter.C.
References fileName::null.
writeTemplate() [3/3]
template<class Type > Foam::fileName writeTemplate (const word & fieldName, const List< Field< Type > > & fieldValues)
Definition at line 730 of file gltfCoordSetWriter.C.
References fileName::null.
Member Data Documentation
fieldOptionNames_
const Foam::Enum< Foam::coordSetWriters::gltfWriter::fieldOption > fieldOptionNames_ static
Definition at line 154 of file gltfCoordSetWriter.H.
The documentation for this class was generated from the following files:
src/meshTools/coordSet/writers/gltf/gltfCoordSetWriter.H
src/meshTools/coordSet/writers/gltf/gltfCoordSetWriter.C