OpenFOAM: fixedIncidentRadiationFvPatchScalarField Class Reference
fixedIncidentRadiationFvPatchScalarField Class Reference
Boundary conditions » Thermophysical
Boundary condition for thermal coupling for solid regions. Used to emulate a fixed incident radiative heat flux on a wall.
#include <fixedIncidentRadiationFvPatchScalarField.H>
Public Member Functions
TypeName ("fixedIncidentRadiation")
fixedIncidentRadiationFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
fixedIncidentRadiationFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
fixedIncidentRadiationFvPatchScalarField (const fixedIncidentRadiationFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
fixedIncidentRadiationFvPatchScalarField (const fixedIncidentRadiationFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
fixedIncidentRadiationFvPatchScalarField (const fixedIncidentRadiationFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual void autoMap (const fvPatchFieldMapper &)
virtual void rmap (const fvPatchScalarField &, const labelList &)
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Public Member Functions inherited from temperatureCoupledBase
temperatureCoupledBase (const fvPatch &patch, const KMethodType method=KMethodType::mtFluidThermo)
temperatureCoupledBase (const fvPatch &patch, const KMethodType method, const word &kappaName, const word &alphaName, const word &alphaAniName)
temperatureCoupledBase (const fvPatch &patch, const dictionary &dict)
temperatureCoupledBase (const fvPatch &patch, const temperatureCoupledBase &base)
temperatureCoupledBase (const temperatureCoupledBase &base)
virtual ~temperatureCoupledBase ()=default
word KMethod () const
const word & kappaName () const noexcept
const word & alphaName () const noexcept
virtual tmp< scalarField > kappa (const scalarField &Tp) const
virtual tmp< scalarField > alpha (const scalarField &Tp) const
void write (Ostream &os) const
Additional Inherited Members
Public Types inherited from temperatureCoupledBase
enum KMethodType {
mtFluidThermo , mtSolidThermo , mtDirectionalSolidThermo , mtLookup ,
mtFunction
}
Protected Attributes inherited from temperatureCoupledBase
const fvPatch & patch_
const KMethodType method_
const word kappaName_
const word alphaName_
const word alphaAniName_
autoPtr< PatchFunction1< scalar > > kappaFunction1_
autoPtr< PatchFunction1< scalar > > alphaFunction1_
Static Protected Attributes inherited from temperatureCoupledBase
static const Enum< KMethodType > KMethodTypeNames_
Detailed Description
Boundary condition for thermal coupling for solid regions. Used to emulate a fixed incident radiative heat flux on a wall.
the gradient heat flux is calculated as :
qr = emissivity*(qrIncident - sigma_*T^4)
where:
emissivity is the emissivity of the solid. qrIncident is the specified fixed incident radiation.
Example usage:
wall { type fixedIncidentRadiation; qrIncident uniform 500; kappa solidThermo; KappaName none; }
kappa:
'lookup' : lookup volScalarField (or volSymmTensorField) with name
'solidThermo' : use solidThermo kappa()
emissivity:
'lookup' : lookup volScalarField emissivity
'localSolidRadiation': Look up for local solidRadiation
Source files
fixedIncidentRadiationFvPatchScalarField.H
fixedIncidentRadiationFvPatchScalarField.C
Definition at line 80 of file fixedIncidentRadiationFvPatchScalarField.H.
Constructor & Destructor Documentation
fixedIncidentRadiationFvPatchScalarField() [1/5]
fixedIncidentRadiationFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 33 of file fixedIncidentRadiationFvPatchScalarField.C.
fixedIncidentRadiationFvPatchScalarField() [2/5]
fixedIncidentRadiationFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 61 of file fixedIncidentRadiationFvPatchScalarField.C.
References dict, and Foam::Zero.
fixedIncidentRadiationFvPatchScalarField() [3/5]
fixedIncidentRadiationFvPatchScalarField (const fixedIncidentRadiationFvPatchScalarField & psf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 46 of file fixedIncidentRadiationFvPatchScalarField.C.
fixedIncidentRadiationFvPatchScalarField() [4/5]
fixedIncidentRadiationFvPatchScalarField (const fixedIncidentRadiationFvPatchScalarField & ptf)
Definition at line 94 of file fixedIncidentRadiationFvPatchScalarField.C.
fixedIncidentRadiationFvPatchScalarField() [5/5]
fixedIncidentRadiationFvPatchScalarField (const fixedIncidentRadiationFvPatchScalarField & psf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 81 of file fixedIncidentRadiationFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("fixedIncidentRadiation")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 134 of file fixedIncidentRadiationFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 153 of file fixedIncidentRadiationFvPatchScalarField.H.
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Implements temperatureCoupledBase.
Definition at line 108 of file fixedIncidentRadiationFvPatchScalarField.C.
References temperatureCoupledBase::autoMap().
rmap()
void rmap (const fvPatchScalarField & psf, const labelList & addr) virtual
Implements temperatureCoupledBase.
Definition at line 119 of file fixedIncidentRadiationFvPatchScalarField.C.
References temperatureCoupledBase::rmap().
updateCoeffs()
void updateCoeffs () virtual
Definition at line 138 of file fixedIncidentRadiationFvPatchScalarField.C.
References Foam::endl(), Foam::gAverage(), Foam::gMax(), Foam::gMin(), Foam::gSum(), Foam::Info, Foam::pow4(), radiation(), and Foam::constant::physicoChemical::sigma.
write()
void write (Ostream & os) const virtual
Definition at line 180 of file fixedIncidentRadiationFvPatchScalarField.C.
References os(), fixedGradientFvPatchField< Type >::write(), temperatureCoupledBase::write(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/thermoTools/derivedFvPatchFields/fixedIncidentRadiation/fixedIncidentRadiationFvPatchScalarField.H
src/thermoTools/derivedFvPatchFields/fixedIncidentRadiation/fixedIncidentRadiationFvPatchScalarField.C