OpenFOAM: maxDeltaxyz Class Reference
maxDeltaxyz Class Reference
#include <maxDeltaxyz.H>
Public Member Functions
TypeName ("maxDeltaxyz")
maxDeltaxyz (const word &name, const turbulenceModel &turbulence, const dictionary &)
virtual ~maxDeltaxyz ()=default
void calcDelta ()
virtual void read (const dictionary &)
virtual void correct ()
Public Member Functions inherited from LESdelta
TypeName ("LESdelta")
declareRunTimeSelectionTable (autoPtr, LESdelta, dictionary,(const word &name, const turbulenceModel &turbulence, const dictionary &dict),(name, turbulence, dict))
LESdelta (const word &name, const turbulenceModel &turbulence)
virtual ~LESdelta ()=default
const turbulenceModel & turbulence () const
virtual operator const volScalarField & () const
Additional Inherited Members
Static Public Member Functions inherited from LESdelta
static autoPtr< LESdelta > New (const word &name, const turbulenceModel &turbulence, const dictionary &dict, const word &lookupName="delta")
static autoPtr< LESdelta > New (const word &name, const turbulenceModel &turbulence, const dictionary &dict, const dictionaryConstructorTableType &additionalConstructors, const word &lookupName="delta")
Protected Member Functions inherited from LESdelta
LESdelta (const LESdelta &)=delete
void operator= (const LESdelta &)=delete
Protected Attributes inherited from LESdelta
const turbulenceModel & turbulenceModel_
volScalarField delta_
Detailed Description
Definition at line 52 of file maxDeltaxyz.H.
Constructor & Destructor Documentation
maxDeltaxyz()
maxDeltaxyz (const word & name, const turbulenceModel & turbulence, const dictionary & dict)
Definition at line 99 of file maxDeltaxyz.C.
References maxDeltaxyz::calcDelta(), and turbulence.
~maxDeltaxyz()
virtual ~maxDeltaxyz () virtual default
Member Function Documentation
TypeName()
TypeName ("maxDeltaxyz")
calcDelta()
void calcDelta ()
Definition at line 39 of file maxDeltaxyz.C.
References cells, GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), LESdelta::delta_, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::mag(), mesh, n, Foam::nl, GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef(), LESdelta::turbulenceModel_, and WarningInFunction.
Referenced by maxDeltaxyz::maxDeltaxyz().
read()
void read (const dictionary & dict) virtual
Implements LESdelta.
Definition at line 122 of file maxDeltaxyz.C.
References dict, dictionary::readIfPresent(), and Foam::type().
correct()
void correct () virtual
Implements LESdelta.
Definition at line 132 of file maxDeltaxyz.C.
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/LES/LESdeltas/maxDeltaxyz/maxDeltaxyz.H
src/TurbulenceModels/turbulenceModels/LES/LESdeltas/maxDeltaxyz/maxDeltaxyz.C