OpenFOAM: cellVolumeWeightMethod Class Reference
cellVolumeWeightMethod Class Reference
Cell-volume-weighted mesh-to-mesh interpolation class.
#include <cellVolumeWeightMethod.H>
Public Member Functions
TypeName ("cellVolumeWeight")
cellVolumeWeightMethod (const polyMesh &src, const polyMesh &tgt)
virtual ~cellVolumeWeightMethod ()
virtual void calculate (labelListList &srcToTgtAddr, scalarListList &srcToTgtWght, pointListList &srcToTgtVec, labelListList &tgtToSrcAddr, scalarListList &tgtToSrcWght, pointListList &tgtToSrcVec)
Public Member Functions inherited from meshToMeshMethod
TypeName ("meshToMeshMethod")
declareRunTimeSelectionTable (autoPtr, meshToMeshMethod, components,(const polyMesh &src, const polyMesh &tgt),(src, tgt))
meshToMeshMethod (const polyMesh &src, const polyMesh &tgt)
virtual ~meshToMeshMethod ()
const polyMesh & src () const
const polyMesh & tgt () const
scalar V () const
void writeConnectivity (const polyMesh &mesh1, const polyMesh &mesh2, const labelListList &mesh1ToMesh2Addr) const
Protected Member Functions
bool findInitialSeeds (const labelList &srcCellIDs, const boolList &mapFlag, const label startSeedI, label &srcSeedI, label &tgtSeedI) const
void calculateAddressing (labelListList &srcToTgtCellAddr, scalarListList &srcToTgtCellWght, labelListList &tgtToSrcCellAddr, scalarListList &tgtToSrcCellWght, const label srcSeedI, const label tgtSeedI, const labelList &srcCellIDs, boolList &mapFlag, label &startSeedI)
void setNextCells (label &startSeedI, label &srcCelli, label &tgtCelli, const labelList &srcCellIDs, const boolList &mapFlag, const DynamicList< label > &visitedCells, labelList &seedCells) const
Protected Member Functions inherited from meshToMeshMethod
labelList maskCells () const
virtual bool intersect (const label srcCelli, const label tgtCelli) const
virtual scalar interVol (const label srcCelli, const label tgtCelli) const
virtual Tuple2< scalar, point > interVolAndCentroid (const label srcCellI, const label tgtCellI)
virtual void appendNbrCells (const label tgtCelli, const polyMesh &mesh, const DynamicList< label > &visitedTgtCells, DynamicList< label > &nbrTgtCellIDs) const
virtual bool initialise (labelListList &srcToTgtAddr, scalarListList &srcToTgtWght, labelListList &tgtToTgtAddr, scalarListList &tgtToTgtWght) const
Additional Inherited Members
Static Public Member Functions inherited from meshToMeshMethod
static autoPtr< meshToMeshMethod > New (const word &methodName, const polyMesh &src, const polyMesh &tgt)
Protected Attributes inherited from meshToMeshMethod
const polyMesh & src_
const polyMesh & tgt_
scalar V_
Static Protected Attributes inherited from meshToMeshMethod
static scalar tolerance_ = 1e-6
Detailed Description
Cell-volume-weighted mesh-to-mesh interpolation class.
Volume conservative.
Source files
cellVolumeWeightMethod.H
cellVolumeWeightMethod.C
Definition at line 48 of file cellVolumeWeightMethod.H.
Constructor & Destructor Documentation
cellVolumeWeightMethod()
cellVolumeWeightMethod (const polyMesh & src, const polyMesh & tgt)
Definition at line 329 of file cellVolumeWeightMethod.C.
~cellVolumeWeightMethod()
~cellVolumeWeightMethod () virtual
Definition at line 341 of file cellVolumeWeightMethod.C.
Member Function Documentation
findInitialSeeds()
bool findInitialSeeds (const labelList & srcCellIDs, const boolList & mapFlag, const label startSeedI, label & srcSeedI, label & tgtSeedI) const protected
Definition at line 42 of file cellVolumeWeightMethod.C.
References Foam::endl(), meshToMeshMethod::intersect(), points, Foam::Pout, pts, UPtrList< T >::size(), meshToMeshMethod::src_, and meshToMeshMethod::tgt_.
calculateAddressing()
void calculateAddressing (labelListList & srcToTgtCellAddr, scalarListList & srcToTgtCellWght, labelListList & tgtToSrcCellAddr, scalarListList & tgtToSrcCellWght, const label srcSeedI, const label tgtSeedI, const labelList & srcCellIDs, boolList & mapFlag, label & startSeedI) protected
Definition at line 87 of file cellVolumeWeightMethod.C.
References PtrList< T >::append(), UPtrList< T >::back(), PtrList< T >::clear(), e, UPtrList< T >::empty(), Foam::endl(), forAll, Foam::mag(), PtrList< T >::push_back(), Foam::sum(), List< T >::transfer(), and WarningInFunction.
setNextCells()
void setNextCells (label & startSeedI, label & srcCelli, label & tgtCelli, const labelList & srcCellIDs, const boolList & mapFlag, const DynamicList< label > & visitedCells, labelList & seedCells) const protected
Definition at line 225 of file cellVolumeWeightMethod.C.
References Foam::endl(), forAll, Foam::Pout, and UPtrList< T >::size().
Referenced by correctedCellVolumeWeightMethod::calculateAddressing().
TypeName()
TypeName ("cellVolumeWeight")
calculate()
void calculate (labelListList & srcToTgtAddr, scalarListList & srcToTgtWght, pointListList & srcToTgtVec, labelListList & tgtToSrcAddr, scalarListList & tgtToSrcWght, pointListList & tgtToSrcVec) virtual
Implements meshToMeshMethod.
Reimplemented in correctedCellVolumeWeightMethod.
Definition at line 347 of file cellVolumeWeightMethod.C.
The documentation for this class was generated from the following files:
src/sampling/meshToMesh/calcMethod/cellVolumeWeight/cellVolumeWeightMethod.H
src/sampling/meshToMesh/calcMethod/cellVolumeWeight/cellVolumeWeightMethod.C