OpenFOAM: rotatingTotalPressureFvPatchScalarField Class Reference
rotatingTotalPressureFvPatchScalarField Class Reference
Boundary conditions » Inlet | Boundary conditions » Outlet
This boundary condition provides a total pressure condition for patches in a rotating frame.
#include <rotatingTotalPressureFvPatchScalarField.H>
Public Member Functions
TypeName ("rotatingTotalPressure")
rotatingTotalPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
rotatingTotalPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
rotatingTotalPressureFvPatchScalarField (const rotatingTotalPressureFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
rotatingTotalPressureFvPatchScalarField (const rotatingTotalPressureFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
rotatingTotalPressureFvPatchScalarField (const rotatingTotalPressureFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Public Member Functions inherited from totalPressureFvPatchScalarField
TypeName ("totalPressure")
totalPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
totalPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
totalPressureFvPatchScalarField (const totalPressureFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
totalPressureFvPatchScalarField (const totalPressureFvPatchScalarField &)
totalPressureFvPatchScalarField (const totalPressureFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
const word & UName () const
word & UName ()
const word & phiName () const
word & phiName ()
const word & rhoName () const
word & rhoName ()
const word & psiName () const
word & psiName ()
scalar gamma () const
scalar & gamma ()
const scalarField & p0 () const
scalarField & p0 ()
virtual void autoMap (const fvPatchFieldMapper &)
virtual void rmap (const fvPatchScalarField &, const labelList &)
virtual void updateCoeffs (const scalarField &p0p, const vectorField &Up)
Detailed Description
This boundary condition provides a total pressure condition for patches in a rotating frame.
Usage
Property Description Required Default value
U velocity field name no U
phi flux field name no phi
rho density field name no none
psi compressibility field name no none
gamma ratio of specific heats (Cp/Cv) yes
p0 static pressure reference yes
omega angular velocty of the frame [rad/s] yes
Example of the boundary condition specification:
    <patchName>
    {
        type            rotatingTotalPressure;
        U               U;
        phi             phi;
        rho             rho;
        psi             psi;
        gamma           1.4;
        p0              uniform 1e5;
        omega           100;
    }
The omega entry is a Function1 type, able to describe time varying functions.
See also
Foam::totalPressureFvPatchScalarField Foam::Function1Types
Source files
rotatingTotalPressureFvPatchScalarField.H
rotatingTotalPressureFvPatchScalarField.C
Definition at line 125 of file rotatingTotalPressureFvPatchScalarField.H.
Constructor & Destructor Documentation
rotatingTotalPressureFvPatchScalarField() [1/5]
rotatingTotalPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 30 of file rotatingTotalPressureFvPatchScalarField.C.
rotatingTotalPressureFvPatchScalarField() [2/5]
rotatingTotalPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 56 of file rotatingTotalPressureFvPatchScalarField.C.
rotatingTotalPressureFvPatchScalarField() [3/5]
rotatingTotalPressureFvPatchScalarField (const rotatingTotalPressureFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 42 of file rotatingTotalPressureFvPatchScalarField.C.
rotatingTotalPressureFvPatchScalarField() [4/5]
rotatingTotalPressureFvPatchScalarField (const rotatingTotalPressureFvPatchScalarField & rtppsf)
Definition at line 69 of file rotatingTotalPressureFvPatchScalarField.C.
rotatingTotalPressureFvPatchScalarField() [5/5]
rotatingTotalPressureFvPatchScalarField (const rotatingTotalPressureFvPatchScalarField & rtppsf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 80 of file rotatingTotalPressureFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("rotatingTotalPressure")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Reimplemented from totalPressureFvPatchScalarField.
Definition at line 175 of file rotatingTotalPressureFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Reimplemented from totalPressureFvPatchScalarField.
Definition at line 191 of file rotatingTotalPressureFvPatchScalarField.H.
updateCoeffs()
void updateCoeffs () virtual
Reimplemented from totalPressureFvPatchScalarField.
Definition at line 94 of file rotatingTotalPressureFvPatchScalarField.C.
References Foam::mag(), om, p0, UName(), and totalPressureFvPatchScalarField::updateCoeffs().
write()
void write (Ostream & os) const virtual
Reimplemented from totalPressureFvPatchScalarField.
Definition at line 118 of file rotatingTotalPressureFvPatchScalarField.C.
References os(), and totalPressureFvPatchScalarField::write().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/rotatingTotalPressure/rotatingTotalPressureFvPatchScalarField.H
src/finiteVolume/fields/fvPatchFields/derived/rotatingTotalPressure/rotatingTotalPressureFvPatchScalarField.C