OpenFOAM: faFieldReconstructor Class Reference
faFieldReconstructor Class Reference
Finite Area area and edge fields reconstruction.
#include <faFieldReconstructor.H>
Classes
class faPatchFieldReconstructor
Public Member Functions
faFieldReconstructor (faMesh &mesh, const PtrList< faMesh > &procMeshes, const PtrList< labelIOList > &edgeProcAddressing, const PtrList< labelIOList > &faceProcAddressing, const PtrList< labelIOList > &boundaryProcAddressing)
label nReconstructed () const noexcept
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > reconstructField (const IOobject &fieldObject, const PtrList< GeometricField< Type, faPatchField, areaMesh > > &) const
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > reconstructAreaField (const IOobject &fieldObject)
template<class Type >
tmp< GeometricField< Type, faePatchField, edgeMesh > > reconstructField (const IOobject &fieldObject, const PtrList< GeometricField< Type, faePatchField, edgeMesh > > &) const
template<class Type >
tmp< GeometricField< Type, faePatchField, edgeMesh > > reconstructEdgeField (const IOobject &fieldObject)
template<class Type >
label reconstructAreaFields (const UPtrList< const IOobject > &fieldObjects)
template<class Type >
label reconstructEdgeFields (const UPtrList< const IOobject > &fieldObjects)
template<class Type >
label reconstructAreaFields (const IOobjectList &objects, const wordRes &selectedFields=wordRes())
template<class Type >
label reconstructEdgeFields (const IOobjectList &objects, const wordRes &selectedFields=wordRes())
label reconstructAllFields (const IOobjectList &objects, const wordRes &selectedFields=wordRes())
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::faPatchField, Foam::areaMesh > > reconstructField (const IOobject &fieldObject, const PtrList< GeometricField< Type, faPatchField, areaMesh > > &procFields) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::faePatchField, Foam::edgeMesh > > reconstructField (const IOobject &fieldObject, const PtrList< GeometricField< Type, faePatchField, edgeMesh > > &procFields) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::faPatchField, Foam::areaMesh > > reconstructAreaField (const IOobject &fieldObject)
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::faePatchField, Foam::edgeMesh > > reconstructEdgeField (const IOobject &fieldObject)
template<class Type >
Foam::label reconstructAreaFields (const UPtrList< const IOobject > &fieldObjects)
template<class Type >
Foam::label reconstructEdgeFields (const UPtrList< const IOobject > &fieldObjects)
template<class Type >
Foam::label reconstructAreaFields (const IOobjectList &objects, const wordRes &selectedFields)
template<class Type >
Foam::label reconstructEdgeFields (const IOobjectList &objects, const wordRes &selectedFields)
Static Public Attributes
static int verbose_ = 1
Detailed Description
Finite Area area and edge fields reconstruction.
Author Zeljko Tukovic, FSB Zagreb Hrvoje Jasak, Wikki Ltd.
Source files
faFieldReconstructor.H
faFieldReconstructor.C
faFieldReconstructorTemplates.C
Definition at line 56 of file faFieldReconstructor.H.
Constructor & Destructor Documentation
faFieldReconstructor()
faFieldReconstructor (faMesh & mesh, const PtrList< faMesh > & procMeshes, const PtrList< labelIOList > & edgeProcAddressing, const PtrList< labelIOList > & faceProcAddressing, const PtrList< labelIOList > & boundaryProcAddressing)
Definition at line 33 of file faFieldReconstructor.C.
Member Function Documentation
nReconstructed()
label nReconstructed () const inline noexcept
Definition at line 166 of file faFieldReconstructor.H.
reconstructField() [1/4]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > reconstructField (const IOobject & fieldObject, const PtrList< GeometricField< Type, faPatchField, areaMesh > > &) const
reconstructAreaField() [1/2]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > reconstructAreaField (const IOobject & fieldObject)
reconstructField() [2/4]
template<class Type > tmp< GeometricField< Type, faePatchField, edgeMesh > > reconstructField (const IOobject & fieldObject, const PtrList< GeometricField< Type, faePatchField, edgeMesh > > &) const
reconstructEdgeField() [1/2]
template<class Type > tmp< GeometricField< Type, faePatchField, edgeMesh > > reconstructEdgeField (const IOobject & fieldObject)
reconstructAreaFields() [1/4]
template<class Type > label reconstructAreaFields (const UPtrList< const IOobject > & fieldObjects)
reconstructEdgeFields() [1/4]
template<class Type > label reconstructEdgeFields (const UPtrList< const IOobject > & fieldObjects)
reconstructAreaFields() [2/4]
template<class Type > label reconstructAreaFields (const IOobjectList & objects, const wordRes & selectedFields = wordRes())
reconstructEdgeFields() [2/4]
template<class Type > label reconstructEdgeFields (const IOobjectList & objects, const wordRes & selectedFields = wordRes())
reconstructAllFields()
Foam::label reconstructAllFields (const IOobjectList & objects, const wordRes & selectedFields = wordRes())
Definition at line 53 of file faFieldReconstructor.C.
References doLocalCode.
reconstructField() [3/4]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::faPatchField, Foam::areaMesh > > reconstructField (const IOobject & fieldObject, const PtrList< GeometricField< Type, faPatchField, areaMesh > > & procFields) const
Definition at line 34 of file faFieldReconstructorTemplates.C.
References boundary, faMesh::boundary(), cp, forAll, Foam::New(), faMesh::nFaces(), faMesh::nInternalEdges(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, PtrList< T >::set(), UPtrList< T >::size(), and faMesh::thisDb().
reconstructField() [4/4]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::faePatchField, Foam::edgeMesh > > reconstructField (const IOobject & fieldObject, const PtrList< GeometricField< Type, faePatchField, edgeMesh > > & procFields) const
Definition at line 265 of file faFieldReconstructorTemplates.C.
References boundary, cp, forAll, Foam::New(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, PtrList< T >::set(), and UPtrList< T >::size().
reconstructAreaField() [2/2]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::faPatchField, Foam::areaMesh > > reconstructAreaField (const IOobject & fieldObject)
Definition at line 516 of file faFieldReconstructorTemplates.C.
References forAll, IOobjectOption::MUST_READ, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, and PtrList< T >::set().
reconstructEdgeField() [2/2]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::faePatchField, Foam::edgeMesh > > reconstructEdgeField (const IOobject & fieldObject)
Definition at line 564 of file faFieldReconstructorTemplates.C.
References forAll, IOobjectOption::MUST_READ, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, and PtrList< T >::set().
reconstructAreaFields() [3/4]
template<class Type > Foam::label reconstructAreaFields (const UPtrList< const IOobject > & fieldObjects)
Definition at line 611 of file faFieldReconstructorTemplates.C.
References Foam::endl(), Foam::Info, io(), IOobject::isHeaderClass(), IOobject::name(), Foam::nl, and write().
reconstructEdgeFields() [3/4]
template<class Type > Foam::label reconstructEdgeFields (const UPtrList< const IOobject > & fieldObjects)
Definition at line 646 of file faFieldReconstructorTemplates.C.
References Foam::endl(), Foam::Info, io(), IOobject::isHeaderClass(), IOobject::name(), Foam::nl, and write().
reconstructAreaFields() [4/4]
template<class Type > Foam::label reconstructAreaFields (const IOobjectList & objects, const wordRes & selectedFields)
Definition at line 681 of file faFieldReconstructorTemplates.C.
References UPtrList< T >::empty().
reconstructEdgeFields() [4/4]
template<class Type > Foam::label reconstructEdgeFields (const IOobjectList & objects, const wordRes & selectedFields)
Definition at line 701 of file faFieldReconstructorTemplates.C.
References UPtrList< T >::empty().
Member Data Documentation
verbose_
int verbose_ = 1 static
Definition at line 147 of file faFieldReconstructor.H.
The documentation for this class was generated from the following files:
src/parallel/reconstruct/faReconstruct/faFieldReconstructor.H
src/parallel/reconstruct/faReconstruct/faFieldReconstructor.C
src/parallel/reconstruct/faReconstruct/faFieldReconstructorTemplates.C