OpenFOAM: lumpedPointState Class Reference
lumpedPointState Class Reference
The state of lumped points corresponds to positions and rotations.
#include <lumpedPointState.H>
Public Types
enum class inputFormatType { PLAIN , DICTIONARY }
Public Member Functions
lumpedPointState ()
lumpedPointState (const lumpedPointState &rhs)
lumpedPointState (const pointField &pts, const vectorField &ang, const quaternion::eulerOrder rotOrder=quaternion::eulerOrder::ZXZ, const bool degrees=false)
lumpedPointState (const pointField &pts, const quaternion::eulerOrder rotOrder=quaternion::eulerOrder::ZXZ, const bool degrees=false)
lumpedPointState (tmp< pointField > &pts, const quaternion::eulerOrder rotOrder=quaternion::eulerOrder::ZXZ, const bool degrees=false)
lumpedPointState (const dictionary &dict, const quaternion::eulerOrder rotOrder=quaternion::eulerOrder::ZXZ, const bool degrees=false)
virtual ~lumpedPointState ()=default
bool valid () const
bool empty () const
label size () const
const pointField & points () const
const vectorField & angles () const
const tensorField & rotations () const
void scalePoints (const scalar scaleFactor)
quaternion::eulerOrder rotationOrder () const
bool degrees () const
void relax (const scalar alpha, const lumpedPointState &prev)
bool readData (Istream &is, const quaternion::eulerOrder rotOrder=quaternion::eulerOrder::ZXZ, const bool degrees=false)
bool writeData (Ostream &os) const
void writeDict (Ostream &os) const
bool readPlain (Istream &is, const quaternion::eulerOrder rotOrder=quaternion::eulerOrder::ZXZ, const bool degrees=false)
void writePlain (Ostream &os) const
bool readData (const inputFormatType fmt, const fileName &file, const quaternion::eulerOrder rotOrder=quaternion::eulerOrder::ZXZ, const bool degrees=false)
void writeVTP (const fileName &outputFile, const labelListList &lines=labelListList(), const labelList &pointIds=labelList::null()) const
void operator= (const lumpedPointState &rhs)
void operator+= (const point &origin)
Static Public Attributes
static const Enum< inputFormatType > formatNames
static bool visUnused = true
static scalar visLength = 0.1
Detailed Description
The state of lumped points corresponds to positions and rotations.
This class encapsulates the response from the external application and serves as the entry point for applying relaxation, sub-stepping etc.
Dictionary input format
Property Description Required Default
points List of points yes
angles List of Euler rotation angles yes
rotationOrder The Euler-angle rotation order no zxz
degrees Rotation angles in degrees no false
Plain input format. Blank and comment lines starting with a '#' character are ignored. The angles are always in radians.
    NumPoints
    x0 y0 z0 eulerz0 eulerx'0 eulerz''0
    x1 y1 z1 eulerz1 eulerx'1 eulerz''1
    ...
See also
Foam::coordinateRotations::euler, Foam::quaternion
Source files
lumpedPointState.H
lumpedPointState.C
lumpedPointStateI.H
Definition at line 104 of file lumpedPointState.H.
Member Enumeration Documentation
inputFormatType
enum class inputFormatType strong
Enumerator
PLAIN
"plain" is a simple ASCII format
DICTIONARY
"dictionary" is the OpenFOAM dictionary format
Definition at line 111 of file lumpedPointState.H.
Constructor & Destructor Documentation
lumpedPointState() [1/6]
lumpedPointState ()
Definition at line 108 of file lumpedPointState.C.
lumpedPointState() [2/6]
lumpedPointState (const lumpedPointState & rhs)
Definition at line 118 of file lumpedPointState.C.
lumpedPointState() [3/6]
lumpedPointState (const pointField & pts, const vectorField & ang, const quaternion::eulerOrder rotOrder = quaternion::eulerOrder::ZXZ, const bool degrees = false)
Definition at line 128 of file lumpedPointState.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::nl, List< T >::resize(), UList< T >::size(), WarningInFunction, and Foam::Zero.
lumpedPointState() [4/6]
lumpedPointState (const pointField & pts, const quaternion::eulerOrder rotOrder = quaternion::eulerOrder::ZXZ, const bool degrees = false) explicit
Definition at line 160 of file lumpedPointState.C.
lumpedPointState() [5/6]
lumpedPointState (tmp< pointField > & pts, const quaternion::eulerOrder rotOrder = quaternion::eulerOrder::ZXZ, const bool degrees = false) explicit
Definition at line 175 of file lumpedPointState.C.
lumpedPointState() [6/6]
lumpedPointState (const dictionary & dict, const quaternion::eulerOrder rotOrder = quaternion::eulerOrder::ZXZ, const bool degrees = false) explicit
Definition at line 190 of file lumpedPointState.C.
References lumpedPointState::degrees(), and dict.
~lumpedPointState()
virtual ~lumpedPointState () virtual default
Member Function Documentation
valid()
bool valid () const inline
Definition at line 21 of file lumpedPointStateI.H.
References UList< T >::size().
empty()
bool empty () const inline
Definition at line 27 of file lumpedPointStateI.H.
References UPtrList< T >::empty().
Referenced by lumpedPointMovement::empty().
size()
Foam::label size () const inline
Definition at line 33 of file lumpedPointStateI.H.
References UPtrList< T >::size().
points()
const Foam::pointField & points () const inline
Definition at line 39 of file lumpedPointStateI.H.
angles()
const Foam::vectorField & angles () const inline
Definition at line 45 of file lumpedPointStateI.H.
rotations()
const Foam::tensorField & rotations () const inline
Definition at line 51 of file lumpedPointStateI.H.
Referenced by lumpedPointState::writeVTP().
scalePoints()
void scalePoints (const scalar scaleFactor)
Definition at line 229 of file lumpedPointState.C.
Referenced by lumpedPointMovement::scalePoints().
rotationOrder()
Foam::quaternion::eulerOrder rotationOrder () const inline
Definition at line 63 of file lumpedPointStateI.H.
degrees()
bool degrees () const inline
Definition at line 69 of file lumpedPointStateI.H.
Referenced by lumpedPointState::lumpedPointState().
relax()
void relax (const scalar alpha, const lumpedPointState & prev)
Definition at line 238 of file lumpedPointState.C.
References alpha, Foam::degToRad(), and Foam::radToDeg().
readData() [1/2]
bool readData (Istream & is, const quaternion::eulerOrder rotOrder = quaternion::eulerOrder::ZXZ, const bool degrees = false)
Definition at line 312 of file lumpedPointState.C.
References dict.
writeData()
bool writeData (Ostream & os) const
Definition at line 326 of file lumpedPointState.C.
References os().
writeDict()
void writeDict (Ostream & os) const
Definition at line 333 of file lumpedPointState.C.
References quaternion::eulerOrderNames, os(), Ostream::writeEntry(), and quaternion::ZXZ.
readPlain()
bool readPlain (Istream & is, const quaternion::eulerOrder rotOrder = quaternion::eulerOrder::ZXZ, const bool degrees = false)
Definition at line 267 of file lumpedPointState.C.
References forAll, PtrList< T >::resize(), and quaternion::ZXZ.
writePlain()
void writePlain (Ostream & os) const
Definition at line 348 of file lumpedPointState.C.
References forAll, os(), and p.
readData() [2/2]
bool readData (const inputFormatType fmt, const fileName & file, const quaternion::eulerOrder rotOrder = quaternion::eulerOrder::ZXZ, const bool degrees = false)
Definition at line 374 of file lumpedPointState.C.
References Pstream::broadcasts(), UPstream::master(), UPstream::parRun(), and UPstream::worldComm.
writeVTP()
void writeVTP (const fileName & outputFile, const labelListList & lines = labelListList(), const labelList & pointIds = labelList::null()) const
Definition at line 28 of file lumpedPointStateWriter.C.
References Foam::vtk::CONNECTIVITY, forAll, format(), Foam::vtk::INLINE_ASCII, Foam::vtk::LINES, UPstream::master(), Foam::vtk::newFormatter(), nPoints, Foam::vtk::NUMBER_OF_LINES, Foam::vtk::NUMBER_OF_POINTS, Foam::vtk::NUMBER_OF_POLYS, Foam::vtk::NUMBER_OF_VERTS, Foam::vtk::OFFSETS, os(), Foam::vtk::PIECE, Foam::vtk::POINTS, Foam::vtk::POLY_DATA, Foam::vtk::POLYS, lumpedPointState::rotations(), UPtrList< T >::size(), FixedList< T, N >::size(), UList< T >::size(), Foam::vtk::VERTS, lumpedPointState::visLength, Foam::vtk::write(), Foam::vtk::writeIdentity(), and Foam::vtk::writeList().
operator=()
void operator= (const lumpedPointState & rhs)
Definition at line 209 of file lumpedPointState.C.
operator+=()
void operator+= (const point & origin)
Definition at line 220 of file lumpedPointState.C.
References p.
Member Data Documentation
formatNames
const Foam::Enum< Foam::lumpedPointState::inputFormatType > formatNames static
Definition at line 121 of file lumpedPointState.H.
visUnused
bool visUnused = true static
Definition at line 160 of file lumpedPointState.H.
visLength
Foam::scalar visLength = 0.1 static
Definition at line 163 of file lumpedPointState.H.
Referenced by lumpedPointState::writeVTP().
The documentation for this class was generated from the following files:
src/lumpedPointMotion/state/lumpedPointState.H
src/lumpedPointMotion/state/lumpedPointState.C
src/lumpedPointMotion/state/lumpedPointStateI.H
src/lumpedPointMotion/state/lumpedPointStateWriter.C