OpenFOAM: mixedEnergyFvPatchScalarField Class Reference
mixedEnergyFvPatchScalarField Class Reference
Boundary conditions » Thermophysical
This boundary condition provides a mixed condition for internal energy.
#include <mixedEnergyFvPatchScalarField.H>
Public Member Functions
TypeName ("mixedEnergy")
mixedEnergyFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
mixedEnergyFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
mixedEnergyFvPatchScalarField (const mixedEnergyFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
mixedEnergyFvPatchScalarField (const mixedEnergyFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
mixedEnergyFvPatchScalarField (const mixedEnergyFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual bool fixesValue () const
virtual void updateCoeffs ()
virtual void manipulateMatrix (fvMatrix< scalar > &m, const label iMatrix, const direction cmpt)
Detailed Description
This boundary condition provides a mixed condition for internal energy.
See also
Foam::mixedFvPatchField
Source files
mixedEnergyFvPatchScalarField.H
mixedEnergyFvPatchScalarField.C
Definition at line 53 of file mixedEnergyFvPatchScalarField.H.
Constructor & Destructor Documentation
mixedEnergyFvPatchScalarField() [1/5]
mixedEnergyFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 32 of file mixedEnergyFvPatchScalarField.C.
References Foam::Zero.
mixedEnergyFvPatchScalarField() [2/5]
mixedEnergyFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 61 of file mixedEnergyFvPatchScalarField.C.
mixedEnergyFvPatchScalarField() [3/5]
mixedEnergyFvPatchScalarField (const mixedEnergyFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 48 of file mixedEnergyFvPatchScalarField.C.
mixedEnergyFvPatchScalarField() [4/5]
mixedEnergyFvPatchScalarField (const mixedEnergyFvPatchScalarField & tppsf)
Definition at line 73 of file mixedEnergyFvPatchScalarField.C.
mixedEnergyFvPatchScalarField() [5/5]
mixedEnergyFvPatchScalarField (const mixedEnergyFvPatchScalarField & tppsf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 83 of file mixedEnergyFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("mixedEnergy")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 98 of file mixedEnergyFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 114 of file mixedEnergyFvPatchScalarField.H.
fixesValue()
virtual bool fixesValue () const inline virtual
Definition at line 131 of file mixedEnergyFvPatchScalarField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 96 of file mixedEnergyFvPatchScalarField.C.
References basicThermo::lookupThermo().
manipulateMatrix()
void manipulateMatrix (fvMatrix< scalar > & m, const label iMatrix, const direction cmpt) virtual
Definition at line 127 of file mixedEnergyFvPatchScalarField.C.
References Foam::faceMap(), forAll, and basicThermo::lookupThermo().
The documentation for this class was generated from the following files:
src/thermophysicalModels/basic/derivedFvPatchFields/mixedEnergy/mixedEnergyFvPatchScalarField.H
src/thermophysicalModels/basic/derivedFvPatchFields/mixedEnergy/mixedEnergyFvPatchScalarField.C