OpenFOAM: fvFieldDecomposer Class Reference
fvFieldDecomposer Class Reference
Finite Volume volume and surface field decomposer.
#include <fvFieldDecomposer.H>
Classes
class fieldsCache
class patchFieldDecomposer
class processorSurfacePatchFieldDecomposer
class processorVolPatchFieldDecomposer
Public Member Functions
fvFieldDecomposer (const Foam::zero, const fvMesh &procMesh, const labelList &faceAddressing, const labelList &cellAddressing, const labelList &boundaryAddressing)
fvFieldDecomposer (const fvMesh &completeMesh, const fvMesh &procMesh, const labelList &faceAddressing, const labelList &cellAddressing, const labelList &boundaryAddressing)
fvFieldDecomposer (const List< labelRange > &boundaryRanges, const labelUList &faceOwner, const labelUList &faceNeigbour, const fvMesh &procMesh, const labelList &faceAddressing, const labelList &cellAddressing, const labelList &boundaryAddressing)
~fvFieldDecomposer ()=default
bool empty () const
void clear ()
void reset (const fvMesh &completeMesh)
void reset (const List< labelRange > &boundaryRanges, const labelUList &faceOwner, const labelUList &faceNeigbour)
template<class Type >
tmp< DimensionedField< Type, volMesh > > decomposeField (const DimensionedField< Type, volMesh > &field) const
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > decomposeField (const GeometricField< Type, fvPatchField, volMesh > &field, const bool allowUnknownPatchFields=false) const
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > decomposeField (const GeometricField< Type, fvsPatchField, surfaceMesh > &field) const
template<class GeoField >
void decomposeFields (const PtrList< GeoField > &fields) const
template<class Type >
Foam::tmp< Foam::DimensionedField< Type, Foam::volMesh > > decomposeField (const DimensionedField< Type, volMesh > &field) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > decomposeField (const GeometricField< Type, fvPatchField, volMesh > &field, const bool allowUnknownPatchFields) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > decomposeField (const GeometricField< Type, fvsPatchField, surfaceMesh > &field) const
Static Public Attributes
static int verbose_ = 1
Detailed Description
Finite Volume volume and surface field decomposer.
Source files
fvFieldDecomposer.H
fvFieldDecomposer.C
fvFieldDecomposerCache.C
fvFieldDecomposerTemplates.C
Definition at line 54 of file fvFieldDecomposer.H.
Constructor & Destructor Documentation
fvFieldDecomposer() [1/3]
fvFieldDecomposer (const Foam::zero , const fvMesh & procMesh, const labelList & faceAddressing, const labelList & cellAddressing, const labelList & boundaryAddressing)
Definition at line 129 of file fvFieldDecomposer.C.
fvFieldDecomposer() [2/3]
fvFieldDecomposer (const fvMesh & completeMesh, const fvMesh & procMesh, const labelList & faceAddressing, const labelList & cellAddressing, const labelList & boundaryAddressing)
Definition at line 150 of file fvFieldDecomposer.C.
References fvFieldDecomposer::reset().
fvFieldDecomposer() [3/3]
fvFieldDecomposer (const List< labelRange > & boundaryRanges, const labelUList & faceOwner, const labelUList & faceNeigbour, const fvMesh & procMesh, const labelList & faceAddressing, const labelList & cellAddressing, const labelList & boundaryAddressing)
Definition at line 172 of file fvFieldDecomposer.C.
References fvFieldDecomposer::reset().
~fvFieldDecomposer()
~fvFieldDecomposer () default
Member Function Documentation
empty()
bool empty () const
Definition at line 199 of file fvFieldDecomposer.C.
References UPtrList< T >::empty().
clear()
void clear ()
Definition at line 205 of file fvFieldDecomposer.C.
References PtrList< T >::clear().
reset() [1/2]
void reset (const fvMesh & completeMesh)
Definition at line 290 of file fvFieldDecomposer.C.
References clear(), forAll, PtrList< T >::resize(), s(), Foam::sign(), and UPtrList< T >::size().
Referenced by fvFieldDecomposer::fvFieldDecomposer(), and fvFieldDecomposer::fvFieldDecomposer().
reset() [2/2]
void reset (const List< labelRange > & boundaryRanges, const labelUList & faceOwner, const labelUList & faceNeigbour)
Definition at line 214 of file fvFieldDecomposer.C.
References clear(), forAll, PtrList< T >::resize(), s(), Foam::sign(), and UPtrList< T >::size().
decomposeField() [1/6]
template<class Type > tmp< DimensionedField< Type, volMesh > > decomposeField (const DimensionedField< Type, volMesh > & field) const
decomposeField() [2/6]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > decomposeField (const GeometricField< Type, fvPatchField, volMesh > & field, const bool allowUnknownPatchFields = false) const
decomposeField() [3/6]
template<class Type > tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > decomposeField (const GeometricField< Type, fvsPatchField, surfaceMesh > & field) const
decomposeFields()
template<class GeoField > void decomposeFields (const PtrList< GeoField > & fields) const
Definition at line 362 of file fvFieldDecomposerTemplates.C.
References fields, fld(), and write().
Referenced by fvFieldDecomposer::fieldsCache::privateCache::decompose().
decomposeField() [4/6]
template<class Type > Foam::tmp< Foam::DimensionedField< Type, Foam::volMesh > > decomposeField (const DimensionedField< Type, volMesh > & field) const
Definition at line 35 of file fvFieldDecomposerTemplates.C.
References field(), Foam::New(), IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, and IOobjectOption::NO_WRITE.
decomposeField() [5/6]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > decomposeField (const GeometricField< Type, fvPatchField, volMesh > & field, const bool allowUnknownPatchFields) const
Definition at line 65 of file fvFieldDecomposerTemplates.C.
References Foam::abort(), fvPatchFieldBase::calculatedType(), Foam::FatalError, FatalErrorInFunction, field(), forAll, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, and PtrList< T >::set().
decomposeField() [6/6]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > decomposeField (const GeometricField< Type, fvsPatchField, surfaceMesh > & field) const
Definition at line 194 of file fvFieldDecomposerTemplates.C.
References Foam::abort(), fvsPatchFieldBase::calculatedType(), Foam::FatalError, FatalErrorInFunction, field(), forAll, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, p, and PtrList< T >::set().
Member Data Documentation
verbose_
int verbose_ = 1 static
Definition at line 253 of file fvFieldDecomposer.H.
The documentation for this class was generated from the following files:
src/parallel/decompose/decompose/fvFieldDecomposer.H
src/parallel/decompose/decompose/fvFieldDecomposer.C
src/parallel/decompose/decompose/fvFieldDecomposerTemplates.C