OpenFOAM: fixedShearStressFvPatchVectorField Class Reference
fixedShearStressFvPatchVectorField Class Reference
Turbulence models » Boundary conditions
This boundary condition sets a user-defined shear stress constant and uniform across a given patch by using the expression:
#include <fixedShearStressFvPatchVectorField.H>
Public Member Functions
TypeName ("fixedShearStress")
fixedShearStressFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
fixedShearStressFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
fixedShearStressFvPatchVectorField (const fixedShearStressFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
fixedShearStressFvPatchVectorField (const fixedShearStressFvPatchVectorField &)
virtual tmp< fvPatchVectorField > clone () const
fixedShearStressFvPatchVectorField (const fixedShearStressFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
This boundary condition sets a user-defined shear stress constant and uniform across a given patch by using the expression:
Usage
Example of the boundary condition specification:
<patchName>
{
    // Mandatory entries
    type             fixedShearStress;
    tau              <vector>;
    // Inherited entries
    ...
}
where the entries mean:
Property Description Type Reqd Deflt
type Type name: fixedShearStress word yes -
tau Shear stress vector yes -
The inherited entries are elaborated in:
fixedValueFvPatchFields.H
Source files
fixedShearStressFvPatchVectorField.H
fixedShearStressFvPatchVectorField.C
Definition at line 98 of file fixedShearStressFvPatchVectorField.H.
Constructor & Destructor Documentation
fixedShearStressFvPatchVectorField() [1/5]
fixedShearStressFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Definition at line 31 of file fixedShearStressFvPatchVectorField.C.
fixedShearStressFvPatchVectorField() [2/5]
fixedShearStressFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Definition at line 42 of file fixedShearStressFvPatchVectorField.C.
fixedShearStressFvPatchVectorField() [3/5]
fixedShearStressFvPatchVectorField (const fixedShearStressFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 56 of file fixedShearStressFvPatchVectorField.C.
fixedShearStressFvPatchVectorField() [4/5]
fixedShearStressFvPatchVectorField (const fixedShearStressFvPatchVectorField & ptf)
Definition at line 69 of file fixedShearStressFvPatchVectorField.C.
fixedShearStressFvPatchVectorField() [5/5]
fixedShearStressFvPatchVectorField (const fixedShearStressFvPatchVectorField & ptf, const DimensionedField< vector, volMesh > & iF)
Definition at line 79 of file fixedShearStressFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("fixedShearStress")
clone() [1/2]
virtual tmp< fvPatchVectorField > clone () const inline virtual
Definition at line 147 of file fixedShearStressFvPatchVectorField.H.
clone() [2/2]
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Definition at line 163 of file fixedShearStressFvPatchVectorField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 92 of file fixedShearStressFvPatchVectorField.C.
References IOobject::groupName(), Foam::mag(), Foam::operator==(), and turbulenceModel::propertiesName.
write()
void write (Ostream & os) const virtual
Definition at line 122 of file fixedShearStressFvPatchVectorField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntry(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/derivedFvPatchFields/fixedShearStress/fixedShearStressFvPatchVectorField.H
src/TurbulenceModels/turbulenceModels/derivedFvPatchFields/fixedShearStress/fixedShearStressFvPatchVectorField.C