OpenFOAM: commSchedule Class Reference
commSchedule Class Reference
Determines the order in which a set of processors should communicate with one another.
#include <commSchedule.H>
Public Member Functions
ClassName ("commSchedule")
commSchedule (const label nProcs, const List< labelPair > &comms)
const labelList & schedule () const noexcept
const labelListList & procSchedule () const noexcept
Detailed Description
Determines the order in which a set of processors should communicate with one another.
The communication order should
have maximum overlap
allow blocking communication without deadlock
Does a very simple scheduling which assumes same time for all operations.
After construction:
schedule() gives the order in which the input communication should occur
procSchedule()[proci] gives per proci
Does not care whether 'talking' is first send, second receive or maybe full swap. This is all responsibility of caller. See Foam::rocessorTopology for use in scheduling processor boundary swaps.
Source files
commSchedule.H
commSchedule.C
Definition at line 63 of file commSchedule.H.
Constructor & Destructor Documentation
commSchedule()
commSchedule (const label nProcs, const List< labelPair > & comms)
Definition at line 65 of file commSchedule.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, UPtrList< T >::first(), forAll, Foam::labelMin, UPstream::master(), os(), Foam::outstandingComms(), Foam::Pout, PtrList< T >::push_back(), List< T >::resize_nocopy(), Foam::setw(), UPtrList< T >::size(), Foam::sortedOrder(), and Foam::Zero.
Member Function Documentation
ClassName()
ClassName ("commSchedule")
schedule()
const labelList & schedule () const inline noexcept
Definition at line 97 of file commSchedule.H.
procSchedule()
const labelListList & procSchedule () const inline noexcept
Definition at line 103 of file commSchedule.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/parallel/commSchedule/commSchedule.H
src/OpenFOAM/parallel/commSchedule/commSchedule.C