OpenFOAM: smoothDelta::deltaData Class Reference
smoothDelta::deltaData Class Reference
#include <smoothDelta.H>
Public Member Functions
deltaData ()
deltaData (const scalar delta)
scalar delta () const
template<class TrackingData >
bool valid (TrackingData &td) const
template<class TrackingData >
bool sameGeometry (const polyMesh &, const deltaData &, const scalar, TrackingData &td) const
template<class TrackingData >
void leaveDomain (const polyMesh &, const polyPatch &, const label patchFacei, const point &faceCentre, TrackingData &td)
template<class TrackingData >
void enterDomain (const polyMesh &, const polyPatch &, const label patchFacei, const point &faceCentre, TrackingData &td)
template<class TrackingData >
void transform (const polyMesh &, const tensor &, TrackingData &td)
template<class TrackingData >
bool updateCell (const polyMesh &, const label thisCelli, const label neighbourFacei, const deltaData &neighbourInfo, const scalar tol, TrackingData &td)
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFacei, const label neighbourCelli, const deltaData &neighbourInfo, const scalar tol, TrackingData &td)
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFacei, const deltaData &neighbourInfo, const scalar tol, TrackingData &td)
template<class TrackingData >
bool equal (const deltaData &, TrackingData &td) const
bool operator== (const deltaData &) const
bool operator!= (const deltaData &) const
Friends
Ostream & operator<< (Ostream &os, const deltaData &rhs)
Istream & operator>> (Istream &is, deltaData &rhs)
Detailed Description
Definition at line 58 of file smoothDelta.H.
Constructor & Destructor Documentation
deltaData() [1/2]
deltaData () inline
Definition at line 58 of file smoothDeltaDeltaDataI.H.
deltaData() [2/2]
deltaData (const scalar delta) inline
Definition at line 64 of file smoothDeltaDeltaDataI.H.
Member Function Documentation
delta()
scalar delta () const inline
Definition at line 94 of file smoothDelta.H.
valid()
template<class TrackingData > bool valid (TrackingData & td) const inline
Definition at line 73 of file smoothDeltaDeltaDataI.H.
References LESdelta::delta_.
sameGeometry()
template<class TrackingData > bool sameGeometry (const polyMesh & , const deltaData & , const scalar , TrackingData & td) const inline
Definition at line 83 of file smoothDeltaDeltaDataI.H.
leaveDomain()
template<class TrackingData > void leaveDomain (const polyMesh & , const polyPatch & , const label patchFacei, const point & faceCentre, TrackingData & td) inline
Definition at line 96 of file smoothDeltaDeltaDataI.H.
enterDomain()
template<class TrackingData > void enterDomain (const polyMesh & , const polyPatch & , const label patchFacei, const point & faceCentre, TrackingData & td) inline
Definition at line 118 of file smoothDeltaDeltaDataI.H.
transform()
template<class TrackingData > void transform (const polyMesh & , const tensor & , TrackingData & td) inline
Definition at line 108 of file smoothDeltaDeltaDataI.H.
updateCell()
template<class TrackingData > bool updateCell (const polyMesh & , const label thisCelli, const label neighbourFacei, const deltaData & neighbourInfo, const scalar tol, TrackingData & td) inline
Definition at line 130 of file smoothDeltaDeltaDataI.H.
References update().
updateFace() [1/2]
template<class TrackingData > bool updateFace (const polyMesh & , const label thisFacei, const label neighbourCelli, const deltaData & neighbourInfo, const scalar tol, TrackingData & td) inline
Definition at line 146 of file smoothDeltaDeltaDataI.H.
References update().
updateFace() [2/2]
template<class TrackingData > bool updateFace (const polyMesh & , const label thisFacei, const deltaData & neighbourInfo, const scalar tol, TrackingData & td) inline
Definition at line 162 of file smoothDeltaDeltaDataI.H.
References update().
equal()
template<class TrackingData > bool equal (const deltaData & rhs, TrackingData & td) const inline
Definition at line 177 of file smoothDeltaDeltaDataI.H.
References Foam::operator==().
operator==()
bool operator== (const deltaData & rhs) const inline
Definition at line 189 of file smoothDeltaDeltaDataI.H.
References LESdelta::delta_.
operator!=()
bool operator!= (const deltaData & rhs) const inline
Definition at line 198 of file smoothDeltaDeltaDataI.H.
Friends And Related Symbol Documentation
operator<<
Ostream & operator<< (Ostream & os, const deltaData & rhs) friend
Definition at line 199 of file smoothDelta.H.
operator>>
Istream & operator>> (Istream & is, deltaData & rhs) friend
Definition at line 204 of file smoothDelta.H.
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/LES/LESdeltas/smoothDelta/smoothDelta.H
src/TurbulenceModels/turbulenceModels/LES/LESdeltas/smoothDelta/smoothDeltaDeltaDataI.H