OpenFOAM: layerParameters Class Reference
layerParameters Class Reference
Simple container to keep together layer specific information.
#include <layerParameters.H>
Public Types
enum thicknessModelType {
FIRST_AND_TOTAL , FIRST_AND_EXPANSION , FINAL_AND_TOTAL , FINAL_AND_EXPANSION ,
TOTAL_AND_EXPANSION , FIRST_AND_RELATIVE_FINAL
}
Public Member Functions
layerParameters (const dictionary &dict, const polyBoundaryMesh &, const bool dryRun=false)
const dictionary & dict () const
const labelList & numLayers () const
const boolList & relativeSizes () const
const List< thicknessModelType > & layerModels () const
const scalarField & expansionRatio () const
const scalarField & finalLayerThickness () const
const scalarField & firstLayerThickness () const
const scalarField & thickness () const
const scalarField & minThickness () const
label nLayerIter () const
label nOuterIter () const
label nRelaxedIter () const
scalar featureAngle () const
scalar mergePatchFacesAngle () const
scalar concaveAngle () const
label nGrow () const
scalar maxFaceThicknessRatio () const
label nBufferCellsNoExtrude () const
bool additionalReporting () const
const word & meshShrinker () const
Static Public Member Functions
static scalar layerThickness (const thicknessModelType, const label nLayers, const scalar firstLayerThickness, const scalar finalLayerThickness, const scalar totalThickness, const scalar expansionRatio)
static scalar layerExpansionRatio (const thicknessModelType, const label nLayers, const scalar firstLayerThickness, const scalar finalLayerThickness, const scalar totalThickness, const scalar expansionRatio)
static scalar firstLayerThickness (const thicknessModelType, const label nLayers, const scalar firstLayerThickness, const scalar finalLayerThickness, const scalar totalThickness, const scalar expansionRatio)
static scalar finalLayerThicknessRatio (const label nLayers, const scalar expansionRatio)
static scalar layerThickness (const label nLayers, const scalar layerThickness, const scalar expansionRatio, const label layerStart, const label layerSize)
Detailed Description
Simple container to keep together layer specific information.
Source files
layerParameters.H
layerParameters.C
Definition at line 54 of file layerParameters.H.
Member Enumeration Documentation
thicknessModelType
enum thicknessModelType
Enumerator
FIRST_AND_TOTAL
FIRST_AND_EXPANSION
FINAL_AND_TOTAL
FINAL_AND_EXPANSION
TOTAL_AND_EXPANSION
FIRST_AND_RELATIVE_FINAL
Definition at line 66 of file layerParameters.H.
Constructor & Destructor Documentation
layerParameters()
layerParameters (const dictionary & dict, const polyBoundaryMesh & boundaryMesh, const bool dryRun = false)
Definition at line 332 of file layerParameters.C.
References layerParameters::dict(), Foam::endl(), Foam::exit(), layerParameters::expansionRatio(), Foam::FatalIOError, FatalIOErrorInFunction, layerParameters::FINAL_AND_EXPANSION, layerParameters::FINAL_AND_TOTAL, layerParameters::FIRST_AND_EXPANSION, layerParameters::FIRST_AND_RELATIVE_FINAL, layerParameters::FIRST_AND_TOTAL, forAll, UPtrList< T >::get(), IOWarningInFunction, Foam::nl, patchIDs(), meshRefinement::subDict(), layerParameters::thickness(), and layerParameters::TOTAL_AND_EXPANSION.
Member Function Documentation
dict()
const dictionary & dict () const inline
Definition at line 197 of file layerParameters.H.
Referenced by layerParameters::layerParameters().
numLayers()
const labelList & numLayers () const inline
Definition at line 210 of file layerParameters.H.
relativeSizes()
const boolList & relativeSizes () const inline
Definition at line 217 of file layerParameters.H.
layerModels()
const List< thicknessModelType > & layerModels () const inline
Definition at line 223 of file layerParameters.H.
expansionRatio()
const scalarField & expansionRatio () const inline
Definition at line 229 of file layerParameters.H.
Referenced by layerParameters::layerParameters().
finalLayerThickness()
const scalarField & finalLayerThickness () const inline
Definition at line 238 of file layerParameters.H.
firstLayerThickness() [1/2]
const scalarField & firstLayerThickness () const inline
Definition at line 246 of file layerParameters.H.
thickness()
const scalarField & thickness () const inline
Definition at line 254 of file layerParameters.H.
Referenced by layerParameters::layerParameters().
minThickness()
const scalarField & minThickness () const inline
Definition at line 263 of file layerParameters.H.
nLayerIter()
label nLayerIter () const inline
Definition at line 272 of file layerParameters.H.
nOuterIter()
label nOuterIter () const inline
Definition at line 281 of file layerParameters.H.
nRelaxedIter()
label nRelaxedIter () const inline
Definition at line 288 of file layerParameters.H.
featureAngle()
scalar featureAngle () const inline
Definition at line 296 of file layerParameters.H.
mergePatchFacesAngle()
scalar mergePatchFacesAngle () const inline
Definition at line 301 of file layerParameters.H.
concaveAngle()
scalar concaveAngle () const inline
Definition at line 306 of file layerParameters.H.
nGrow()
label nGrow () const inline
Definition at line 314 of file layerParameters.H.
maxFaceThicknessRatio()
scalar maxFaceThicknessRatio () const inline
Definition at line 320 of file layerParameters.H.
nBufferCellsNoExtrude()
label nBufferCellsNoExtrude () const inline
Definition at line 326 of file layerParameters.H.
additionalReporting()
bool additionalReporting () const inline
Definition at line 332 of file layerParameters.H.
meshShrinker()
const word & meshShrinker () const inline
Definition at line 338 of file layerParameters.H.
layerThickness() [1/2]
Foam::scalar layerThickness (const thicknessModelType layerSpec, const label nLayers, const scalar firstLayerThickness, const scalar finalLayerThickness, const scalar totalThickness, const scalar expansionRatio) static
Definition at line 740 of file layerParameters.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::mag(), and Foam::pow().
Referenced by snappyLayerDriver::addLayers().
layerExpansionRatio()
Foam::scalar layerExpansionRatio (const thicknessModelType layerSpec, const label nLayers, const scalar firstLayerThickness, const scalar finalLayerThickness, const scalar totalThickness, const scalar expansionRatio) static
Definition at line 833 of file layerParameters.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and Foam::pow().
firstLayerThickness() [2/2]
Foam::scalar firstLayerThickness (const thicknessModelType layerSpec, const label nLayers, const scalar firstLayerThickness, const scalar finalLayerThickness, const scalar totalThickness, const scalar expansionRatio) static
Definition at line 920 of file layerParameters.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and Foam::pow().
finalLayerThicknessRatio()
Foam::scalar finalLayerThicknessRatio (const label nLayers, const scalar expansionRatio) static
Definition at line 990 of file layerParameters.C.
References Foam::mag(), and Foam::pow().
Referenced by snappyLayerDriver::addLayers().
layerThickness() [2/2]
Foam::scalar layerThickness (const label nLayers, const scalar layerThickness, const scalar expansionRatio, const label layerStart, const label layerSize) static
Definition at line 690 of file layerParameters.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::mag(), and Foam::pow().
The documentation for this class was generated from the following files:
src/mesh/snappyHexMesh/snappyHexMeshDriver/layerParameters/layerParameters.H
src/mesh/snappyHexMesh/snappyHexMeshDriver/layerParameters/layerParameters.C