OpenFOAM: processorFvPatch Class Reference
processorFvPatch Class Reference
Processor patch.
#include <processorFvPatch.H>
Public Member Functions
TypeName (processorPolyPatch::typeName_())
processorFvPatch (const polyPatch &patch, const fvBoundaryMesh &bm)
virtual label comm () const
virtual int myProcNo () const
virtual int neighbProcNo () const
virtual int tag () const
virtual bool coupled () const
const processorPolyPatch & procPolyPatch () const
virtual bool parallel () const
virtual const tensorField & forwardT () const
virtual const tensorField & reverseT () const
virtual tmp< vectorField > delta () const
virtual tmp< labelField > interfaceInternalField (const labelUList &internalData) const
virtual tmp< labelField > interfaceInternalField (const labelUList &internalData, const labelUList &faceCells) const
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &internalData) const
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &iF, const labelUList &faceCells) const
virtual tmp< labelField > internalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &internalData) const
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, labelUList &iF) const
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, labelUList &iF, const labelUList &faceCell) const
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &iF) const
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &iF, const labelUList &faceCells) const
Public Member Functions inherited from coupledFvPatch
TypeNameNoDebug (coupledPolyPatch::typeName_())
coupledFvPatch (const polyPatch &patch, const fvBoundaryMesh &bm)
virtual ~coupledFvPatch ()=default
virtual const labelUList & faceCells () const
Public Member Functions inherited from lduInterface
TypeNameNoDebug ("lduInterface")
lduInterface () noexcept=default
virtual ~lduInterface ()=default
Public Member Functions inherited from fvPatch
virtual void makeDeltaCoeffs (scalarField &) const
virtual void makeNonOrthoDeltaCoeffs (scalarField &) const
virtual void makeNonOrthoCorrVectors (vectorField &) const
virtual void initMovePoints ()
virtual void movePoints ()
TypeName (polyPatch::typeName_())
declareRunTimeSelectionTable (autoPtr, fvPatch, polyPatch,(const polyPatch &patch, const fvBoundaryMesh &bm),(patch, bm))
fvPatch (const polyPatch &, const fvBoundaryMesh &)
virtual ~fvPatch ()
const polyPatch & patch () const noexcept
virtual const word & name () const
label index () const noexcept
label start () const noexcept
virtual label size () const
const fvBoundaryMesh & boundaryMesh () const noexcept
template<class T >
const List< T >::subList patchSlice (const List< T > &values) const
template<class T >
const List< T >::subList boundarySlice (const List< T > &values) const
const vectorField & Cf () const
tmp< vectorField > Cn () const
const vectorField & Sf () const
const scalarField & magSf () const
tmp< vectorField > unitSf () const
tmp< vectorField > nf () const
const scalarField & weights () const
const scalarField & deltaCoeffs () const
template<class Type >
void patchInternalField (const UList< Type > &internalData, const labelUList &addressing, Field< Type > &pfld) const
template<class Type >
void patchInternalField (const UList< Type > &internalData, Field< Type > &pfld) const
template<class Type >
tmp< Field< Type > > patchInternalField (const UList< Type > &internalData) const
template<class GeometricField , class AnyType = bool>
const GeometricField::Patch & patchField (const GeometricField &gf) const
template<class GeometricField , class AnyType = bool>
const GeometricField::Patch & lookupPatchField (const word &name, const GeometricField *=nullptr, const AnyType *=nullptr) const
template<class Type >
Foam::tmp< Foam::Field< Type > > patchInternalField (const UList< Type > &internalData) const
Public Member Functions inherited from processorLduInterface
TypeNameNoDebug ("processorLduInterface")
processorLduInterface () noexcept=default
virtual ~processorLduInterface ()=default
template<class Type >
void send (const UPstream::commsTypes commsType, const UList< Type > &f) const
template<class Type >
void receive (const UPstream::commsTypes commsType, UList< Type > &f) const
template<class Type >
tmp< Field< Type > > receive (const UPstream::commsTypes commsType, const label size) const
template<class Type >
void compressedSend (const UPstream::commsTypes commsType, const UList< Type > &f) const
template<class Type >
void compressedReceive (const UPstream::commsTypes commsType, UList< Type > &f) const
template<class Type >
tmp< Field< Type > > compressedReceive (const UPstream::commsTypes commsType, const label size) const
template<class Type >
Foam::tmp< Foam::Field< Type > > receive (const UPstream::commsTypes commsType, const label size) const
template<class Type >
Foam::tmp< Foam::Field< Type > > compressedReceive (const UPstream::commsTypes commsType, const label size) const
Protected Member Functions
void makeWeights (scalarField &) const
Additional Inherited Members
Public Types inherited from fvPatch
typedef fvBoundaryMesh BoundaryMesh
Static Public Member Functions inherited from fvPatch
static autoPtr< fvPatch > New (const polyPatch &, const fvBoundaryMesh &)
static const fvPatch & lookupPatch (const polyPatch &p)
static bool constraintType (const word &patchType)
static wordList constraintTypes ()
Detailed Description
Processor patch.
Source files
processorFvPatch.H
processorFvPatch.C
Definition at line 49 of file processorFvPatch.H.
Constructor & Destructor Documentation
processorFvPatch()
processorFvPatch (const polyPatch & patch, const fvBoundaryMesh & bm) inline
Definition at line 76 of file processorFvPatch.H.
Member Function Documentation
makeWeights()
void makeWeights (scalarField & w) const protected virtual
Implements coupledFvPatch.
Definition at line 37 of file processorFvPatch.C.
References coupledFvPatch::delta(), Foam::mag(), fvPatch::nf(), and UPstream::parRun().
TypeName()
TypeName (processorPolyPatch::typeName_())
comm()
virtual label comm () const inline virtual
Implements processorLduInterface.
Definition at line 86 of file processorFvPatch.H.
References processorPolyPatch::comm().
Referenced by processorFvPatchField< Type >::comm().
myProcNo()
virtual int myProcNo () const inline virtual
Implements processorLduInterface.
Definition at line 92 of file processorFvPatch.H.
References processorPolyPatch::myProcNo().
Referenced by processorFvPatchField< Type >::myProcNo().
neighbProcNo()
virtual int neighbProcNo () const inline virtual
Implements processorLduInterface.
Definition at line 98 of file processorFvPatch.H.
References processorPolyPatch::neighbProcNo().
Referenced by processorFvPatchField< Type >::neighbProcNo().
tag()
virtual int tag () const inline virtual
Implements processorLduInterface.
Reimplemented in processorCyclicFvPatch.
Definition at line 104 of file processorFvPatch.H.
References UPstream::msgType().
coupled()
virtual bool coupled () const inline virtual
Reimplemented from coupledFvPatch.
Definition at line 110 of file processorFvPatch.H.
References UPstream::parRun().
procPolyPatch()
const processorPolyPatch & procPolyPatch () const inline
Definition at line 115 of file processorFvPatch.H.
parallel()
virtual bool parallel () const inline virtual
Implements coupledFvPatch.
Reimplemented in processorCyclicFvPatch.
Definition at line 121 of file processorFvPatch.H.
References coupledPolyPatch::parallel().
Referenced by processorFvPatchField< Type >::doTransform().
forwardT()
virtual const tensorField & forwardT () const inline virtual
Implements coupledFvPatch.
Reimplemented in processorCyclicFvPatch.
Definition at line 127 of file processorFvPatch.H.
References coupledPolyPatch::forwardT().
Referenced by processorFvPatchField< Type >::forwardT().
reverseT()
virtual const tensorField & reverseT () const inline virtual
Implements coupledFvPatch.
Reimplemented in processorCyclicFvPatch.
Definition at line 133 of file processorFvPatch.H.
References coupledPolyPatch::reverseT().
delta()
Foam::tmp< Foam::vectorField > delta () const virtual
Implements coupledFvPatch.
Definition at line 63 of file processorFvPatch.C.
References coupledFvPatch::delta(), UPstream::parRun(), and Foam::transform().
interfaceInternalField() [1/2]
Foam::tmp< Foam::labelField > interfaceInternalField (const labelUList & internalData) const virtual
Implements coupledFvPatch.
Definition at line 98 of file processorFvPatch.C.
interfaceInternalField() [2/2]
Foam::tmp< Foam::labelField > interfaceInternalField (const labelUList & internalData, const labelUList & faceCells) const virtual
Implements coupledFvPatch.
Definition at line 107 of file processorFvPatch.C.
References tmp< T >::New().
initInternalFieldTransfer() [1/6]
void initInternalFieldTransfer (const Pstream::commsTypes commsType, const labelUList & internalData) const virtual
Reimplemented from coupledFvPatch.
Definition at line 119 of file processorFvPatch.C.
initInternalFieldTransfer() [2/6]
void initInternalFieldTransfer (const Pstream::commsTypes commsType, const labelUList & iF, const labelUList & faceCells) const virtual
Reimplemented from coupledFvPatch.
Definition at line 129 of file processorFvPatch.C.
internalFieldTransfer()
Foam::tmp< Foam::labelField > internalFieldTransfer (const Pstream::commsTypes commsType, const labelUList & internalData) const virtual
Implements coupledFvPatch.
Definition at line 140 of file processorFvPatch.C.
initInternalFieldTransfer() [3/6]
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, labelUList & iF) const inline virtual
Reimplemented from coupledFvPatch.
Definition at line 141 of file coupledFvPatch.H.
initInternalFieldTransfer() [4/6]
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, labelUList & iF, const labelUList & faceCell) const inline virtual
Reimplemented from coupledFvPatch.
Definition at line 149 of file coupledFvPatch.H.
initInternalFieldTransfer() [5/6]
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, const labelUList & iF) const inline virtual
Reimplemented from coupledFvPatch.
Definition at line 138 of file lduInterface.H.
initInternalFieldTransfer() [6/6]
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, const labelUList & iF, const labelUList & faceCells) const inline virtual
Reimplemented from coupledFvPatch.
Definition at line 138 of file lduInterface.H.
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/fvPatches/constraint/processor/processorFvPatch.H
src/finiteVolume/fvMesh/fvPatches/constraint/processor/processorFvPatch.C