OpenFOAM: metisLikeDecomp Class Reference
metisLikeDecomp Class Reference abstract
Domain decomposition using METIS-like data structures.
#include <metisLikeDecomp.H>
Public Member Functions
virtual ~metisLikeDecomp ()=default
virtual labelList decompose (const polyMesh &mesh, const pointField &points, const scalarField &pointWeights) const
virtual labelList decompose (const polyMesh &mesh, const labelList &agglom, const pointField &regionPoints, const scalarField &regionWeights) const
virtual labelList decompose (const labelListList &globalCellCells, const pointField &cellCentres, const scalarField &cellWeights) const
virtual labelList decompose (const pointField &points, const scalarField &pointWeights) const
virtual labelList decompose (const pointField &points) const
virtual labelList decompose (const polyMesh &mesh, const pointField &points, const scalarField &pointWeights) const=0
virtual labelList decompose (const polyMesh &mesh, const pointField &points) const
virtual labelList decompose (const polyMesh &mesh, const labelList &cellToRegion, const pointField &regionPoints, const scalarField &regionWeights) const
virtual labelList decompose (const polyMesh &mesh, const labelList &cellToRegion, const pointField &regionPoints) const
virtual labelList decompose (const labelListList &globalCellCells, const pointField &cc, const scalarField &cWeights) const=0
virtual labelList decompose (const labelListList &globalCellCells, const pointField &cc) const
virtual labelList decompose (const polyMesh &mesh, const scalarField &cellWeights, const boolList &blockedFace, const PtrList< labelList > &specifiedProcessorFaces, const labelList &specifiedProcessor, const List< labelPair > &explicitConnections) const
labelList decompose (const polyMesh &mesh, const scalarField &cWeights) const
Public Member Functions inherited from decompositionMethod
TypeName ("decompositionMethod")
declareRunTimeSelectionTable (autoPtr, decompositionMethod, dictionary,(const dictionary &decompDict, const word &regionName),(decompDict, regionName))
decompositionMethod (const dictionary &decompDict, const word &regionName="")
virtual ~decompositionMethod ()=default
label nDomains () const noexcept
virtual bool parallelAware () const =0
void setConstraints (const polyMesh &mesh, boolList &blockedFace, PtrList< labelList > &specifiedProcessorFaces, labelList &specifiedProcessor, List< labelPair > &explicitConnections) const
void applyConstraints (const polyMesh &mesh, const boolList &blockedFace, const PtrList< labelList > &specifiedProcessorFaces, const labelList &specifiedProcessor, const List< labelPair > &explicitConnections, labelList &finalDecomp) const
labelList decompose (const polyMesh &mesh, const scalarField &cWeights) const
Protected Member Functions
virtual label decomposeGeneral (const labelList &adjncy, const labelList &xadj, const List< scalar > &cellWeights, labelList &decomp) const
virtual label decomposeSerial (const labelList &adjncy, const labelList &xadj, const List< scalar > &cellWeights, labelList &decomp) const =0
metisLikeDecomp (const metisLikeDecomp &)=delete
void operator= (const metisLikeDecomp &)=delete
metisLikeDecomp (const word &derivedType, const dictionary &decompDict, int select=selectionType::NULL_DICT)
metisLikeDecomp (const word &derivedType, const dictionary &decompDict, const word &regionName, int select=selectionType::NULL_DICT)
Protected Member Functions inherited from decompositionMethod
const dictionary & findCoeffsDict (const word &coeffsName, int select=selectionType::DEFAULT) const
Protected Attributes
const dictionary & coeffsDict_
Protected Attributes inherited from decompositionMethod
const dictionary & decompDict_
const dictionary & decompRegionDict_
label nDomains_
PtrList< decompositionConstraint > constraints_
Additional Inherited Members
Static Public Member Functions inherited from decompositionMethod
static label nDomains (const dictionary &decompDict, const word &regionName="")
static const dictionary & optionalRegionDict (const dictionary &decompDict, const word &regionName)
static autoPtr< decompositionMethod > New (const dictionary &decompDict, const word &regionName="")
static void calcCellCells (const polyMesh &mesh, const labelList &agglom, const label nLocalCoarse, const bool global, CompactListList< label > &cellCells)
static void calcCellCells (const polyMesh &mesh, const labelList &agglom, const label nLocalCoarse, const bool parallel, CompactListList< label > &cellCells, CompactListList< scalar > &cellCellWeights)
Protected Types inherited from decompositionMethod
enum selectionType { DEFAULT = 0 , EXACT = 1 , MANDATORY = 2 , NULL_DICT = 4 }
Static Protected Member Functions inherited from decompositionMethod
static const dictionary & findCoeffsDict (const dictionary &dict, const word &coeffsName, int select=selectionType::DEFAULT)
Detailed Description
Domain decomposition using METIS-like data structures.
When run in parallel will collect the entire graph on to the master, decompose and send back.
Source files
metisLikeDecomp.H
metisLikeDecomp.C
Definition at line 47 of file metisLikeDecomp.H.
Constructor & Destructor Documentation
metisLikeDecomp() [1/3]
metisLikeDecomp (const metisLikeDecomp &) protected delete
metisLikeDecomp() [2/3]
metisLikeDecomp (const word & derivedType, const dictionary & decompDict, int select = selectionType::NULL_DICT) inline protected
Definition at line 90 of file metisLikeDecomp.H.
metisLikeDecomp() [3/3]
metisLikeDecomp (const word & derivedType, const dictionary & decompDict, const word & regionName, int select = selectionType::NULL_DICT) protected
Definition at line 179 of file metisLikeDecomp.C.
~metisLikeDecomp()
virtual ~metisLikeDecomp () virtual default
Member Function Documentation
decomposeGeneral()
Foam::label decomposeGeneral (const labelList & adjncy, const labelList & xadj, const List< scalar > & cellWeights, labelList & decomp) const protected virtual
Definition at line 27 of file metisLikeDecomp.C.
References PtrList< T >::clear(), metisLikeDecomp::decomposeSerial(), UPtrList< T >::empty(), Foam::endl(), Foam::Info, UPtrList< T >::last(), UPstream::master(), UPstream::masterNo(), Foam::max(), UPstream::msgType(), UPstream::nonBlocking, UPstream::nRequests(), UPstream::parRun(), UIPstream::read(), PtrList< T >::resize(), Foam::returnReduceAnd(), UPtrList< T >::size(), Foam::type(), UPstream::waitRequests(), UPstream::worldComm, and UOPstream::write().
decomposeSerial()
virtual label decomposeSerial (const labelList & adjncy, const labelList & xadj, const List< scalar > & cellWeights, labelList & decomp) const protected pure virtual
Implemented in kahipDecomp, metisDecomp, and scotchDecomp.
Referenced by metisLikeDecomp::decomposeGeneral().
operator=()
void operator= (const metisLikeDecomp &) protected delete
decompose() [1/13]
Foam::labelList decompose (const polyMesh & mesh, const pointField & points, const scalarField & pointWeights) const virtual
Implements decompositionMethod.
Reimplemented in scotchDecomp, and scotchDecomp.
Definition at line 194 of file metisLikeDecomp.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::identity(), mesh, primitiveMesh::nCells(), Foam::nl, points, and UPtrList< T >::size().
decompose() [2/13]
Foam::labelList decompose (const polyMesh & mesh, const labelList & agglom, const pointField & regionPoints, const scalarField & regionWeights) const virtual
Reimplemented from decompositionMethod.
Reimplemented in scotchDecomp, and scotchDecomp.
Definition at line 235 of file metisLikeDecomp.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, mesh, primitiveMesh::nCells(), and UPtrList< T >::size().
decompose() [3/13]
Foam::labelList decompose (const labelListList & globalCellCells, const pointField & cellCentres, const scalarField & cellWeights) const virtual
Implements decompositionMethod.
Reimplemented in scotchDecomp, and scotchDecomp.
Definition at line 288 of file metisLikeDecomp.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and UList< T >::size().
decompose() [4/13]
Foam::labelList decompose (const pointField & points, const scalarField & pointWeights) const virtual
Reimplemented from decompositionMethod.
Reimplemented in scotchDecomp.
Definition at line 218 of file decompositionMethod.C.
decompose() [5/13]
Foam::labelList decompose (const pointField & points) const virtual
Reimplemented from decompositionMethod.
Reimplemented in scotchDecomp.
Definition at line 225 of file decompositionMethod.C.
decompose() [6/13]
virtual labelList decompose (const polyMesh & mesh, const pointField & points, const scalarField & pointWeights) const virtual
Implements decompositionMethod.
Reimplemented in scotchDecomp, and scotchDecomp.
decompose() [7/13]
Foam::labelList decompose (const polyMesh & mesh, const pointField & points) const virtual
Reimplemented from decompositionMethod.
Reimplemented in scotchDecomp.
Definition at line 240 of file decompositionMethod.C.
decompose() [8/13]
Foam::labelList decompose (const polyMesh & mesh, const labelList & cellToRegion, const pointField & regionPoints, const scalarField & regionWeights) const virtual
Reimplemented from decompositionMethod.
Reimplemented in scotchDecomp, and scotchDecomp.
Definition at line 254 of file decompositionMethod.C.
decompose() [9/13]
Foam::labelList decompose (const polyMesh & mesh, const labelList & cellToRegion, const pointField & regionPoints) const virtual
Reimplemented from decompositionMethod.
Reimplemented in scotchDecomp.
Definition at line 263 of file decompositionMethod.C.
References Foam::abort(), dict, Foam::endl(), Foam::FatalIOError, and dictionary::name().
decompose() [10/13]
virtual labelList decompose (const labelListList & globalCellCells, const pointField & cc, const scalarField & cWeights) const virtual
Implements decompositionMethod.
Reimplemented in scotchDecomp, and scotchDecomp.
decompose() [11/13]
Foam::labelList decompose (const labelListList & globalCellCells, const pointField & cc) const virtual
Reimplemented from decompositionMethod.
Reimplemented in scotchDecomp.
Definition at line 288 of file decompositionMethod.C.
References Foam::cfindCoeffsDict().
decompose() [12/13]
Foam::labelList decompose (const polyMesh & mesh, const scalarField & cellWeights, const boolList & blockedFace, const PtrList< labelList > & specifiedProcessorFaces, const labelList & specifiedProcessor, const List< labelPair > & explicitConnections) const virtual
Reimplemented from decompositionMethod.
Reimplemented in scotchDecomp.
Definition at line 363 of file decompositionMethod.C.
decompose() [13/13]
Foam::labelList decompose (const polyMesh & mesh, const scalarField & cWeights) const
Definition at line 383 of file decompositionMethod.C.
Member Data Documentation
coeffsDict_
const dictionary& coeffsDict_ protected
Definition at line 56 of file metisLikeDecomp.H.
The documentation for this class was generated from the following files:
src/parallel/decompose/decompositionMethods/metisLikeDecomp/metisLikeDecomp.H
src/parallel/decompose/decompositionMethods/metisLikeDecomp/metisLikeDecomp.C