OpenFOAM: atmNutUWallFunctionFvPatchScalarField Class Reference
atmNutUWallFunctionFvPatchScalarField Class Reference
This boundary condition provides a wall constraint on the turbulent viscosity (i.e. nut) based on velocity (i.e. U) for atmospheric boundary layer modelling. It is designed to be used in conjunction with the atmBoundaryLayerInletVelocity boundary condition.
#include <atmNutUWallFunctionFvPatchScalarField.H>
Public Member Functions
TypeName ("atmNutUWallFunction")
atmNutUWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
atmNutUWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
atmNutUWallFunctionFvPatchScalarField (const atmNutUWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
atmNutUWallFunctionFvPatchScalarField (const atmNutUWallFunctionFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
atmNutUWallFunctionFvPatchScalarField (const atmNutUWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual void autoMap (const fvPatchFieldMapper &)
virtual void rmap (const fvPatchScalarField &, const labelList &)
virtual void write (Ostream &) const
Public Member Functions inherited from nutUWallFunctionFvPatchScalarField
TypeName ("nutUWallFunction")
nutUWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
nutUWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
nutUWallFunctionFvPatchScalarField (const nutUWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
nutUWallFunctionFvPatchScalarField (const nutUWallFunctionFvPatchScalarField &)
nutUWallFunctionFvPatchScalarField (const nutUWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< scalarField > yPlus () const
Public Member Functions inherited from nutWallFunctionFvPatchScalarField
TypeName ("nutWallFunction")
nutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
nutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &)
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
const wallFunctionCoefficients & wallCoeffs () const noexcept
virtual void updateCoeffs ()
Protected Member Functions
virtual tmp< scalarField > calcNut () const
void writeLocalEntries (Ostream &) const
Protected Member Functions inherited from nutUWallFunctionFvPatchScalarField
tmp< scalarField > calcYPlus (const scalarField &magUp) const
void writeLocalEntries (Ostream &) const
Protected Member Functions inherited from nutWallFunctionFvPatchScalarField
virtual const volVectorField & U (const turbulenceModel &turb) const
virtual void checkType ()
void writeLocalEntries (Ostream &) const
Additional Inherited Members
Static Public Member Functions inherited from nutWallFunctionFvPatchScalarField
static const nutWallFunctionFvPatchScalarField & nutw (const turbulenceModel &turbModel, const label patchi)
Protected Attributes inherited from nutWallFunctionFvPatchScalarField
word UName_
wallFunctionCoefficients wallCoeffs_
Detailed Description
This boundary condition provides a wall constraint on the turbulent viscosity (i.e. nut) based on velocity (i.e. U) for atmospheric boundary layer modelling. It is designed to be used in conjunction with the atmBoundaryLayerInletVelocity boundary condition.
The governing equation of the boundary condition:
where
= Friction velocity
= von Kármán constant
= Surface roughness length [m]
= Ground-normal coordinate
Required fields:
      nut     | Turbulent viscosity         [m2/s]
      U       | Velocity                    [m/s]
Usage
Example of the boundary condition specification:
<patchName>
{
    // Mandatory entries
    type            atmNutUWallFunction;
    z0              <PatchFunction1<scalar>>;
    // Optional entries
    boundNut        true;
    // Inherited entries
    ...
}
where the entries mean:
Property Description Type Reqd Deflt
type Type name: atmNutUWallFunction word yes -
z0 Surface roughness length [m] PatchFunction1<scalar> yes -
boundNut Flag: zero-bound nut near wall bool no true
The inherited entries are elaborated in:
nutUWallFunctionFvPatchScalarField.H
PatchFunction1.H
Source files
atmNutUWallFunctionFvPatchScalarField.H
atmNutUWallFunctionFvPatchScalarField.C
Definition at line 143 of file atmNutUWallFunctionFvPatchScalarField.H.
Constructor & Destructor Documentation
atmNutUWallFunctionFvPatchScalarField() [1/5]
atmNutUWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 111 of file atmNutUWallFunctionFvPatchScalarField.C.
atmNutUWallFunctionFvPatchScalarField() [2/5]
atmNutUWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 137 of file atmNutUWallFunctionFvPatchScalarField.C.
atmNutUWallFunctionFvPatchScalarField() [3/5]
atmNutUWallFunctionFvPatchScalarField (const atmNutUWallFunctionFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 123 of file atmNutUWallFunctionFvPatchScalarField.C.
atmNutUWallFunctionFvPatchScalarField() [4/5]
atmNutUWallFunctionFvPatchScalarField (const atmNutUWallFunctionFvPatchScalarField & rwfpsf)
Definition at line 150 of file atmNutUWallFunctionFvPatchScalarField.C.
atmNutUWallFunctionFvPatchScalarField() [5/5]
atmNutUWallFunctionFvPatchScalarField (const atmNutUWallFunctionFvPatchScalarField & rwfpsf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 161 of file atmNutUWallFunctionFvPatchScalarField.C.
Member Function Documentation
calcNut()
tmp< scalarField > calcNut () const protected virtual
Reimplemented from nutUWallFunctionFvPatchScalarField.
Definition at line 35 of file atmNutUWallFunctionFvPatchScalarField.C.
References e, Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, IOobject::groupName(), wallFunctionCoefficients::kappa(), Foam::log(), Foam::mag(), Foam::max(), tmp< T >::New(), nutWallFunctionFvPatchScalarField::nutw(), fvPatchField< Type >::patchInternalField(), turbulenceModel::propertiesName, Foam::sqr(), U, nutWallFunctionFvPatchScalarField::wallCoeffs_, and y.
writeLocalEntries()
void writeLocalEntries (Ostream & os) const protected
Definition at line 95 of file atmNutUWallFunctionFvPatchScalarField.C.
References os(), and Ostream::writeEntryIfDifferent().
Referenced by atmNutUWallFunctionFvPatchScalarField::write().
TypeName()
TypeName ("atmNutUWallFunction")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Reimplemented from nutUWallFunctionFvPatchScalarField.
Definition at line 209 of file atmNutUWallFunctionFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Reimplemented from nutUWallFunctionFvPatchScalarField.
Definition at line 225 of file atmNutUWallFunctionFvPatchScalarField.H.
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Definition at line 175 of file atmNutUWallFunctionFvPatchScalarField.C.
rmap()
void rmap (const fvPatchScalarField & ptf, const labelList & addr) virtual
Definition at line 189 of file atmNutUWallFunctionFvPatchScalarField.C.
write()
void write (Ostream & os) const virtual
Reimplemented from nutUWallFunctionFvPatchScalarField.
Definition at line 207 of file atmNutUWallFunctionFvPatchScalarField.C.
References os(), nutWallFunctionFvPatchScalarField::write(), atmNutUWallFunctionFvPatchScalarField::writeLocalEntries(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/atmosphericModels/derivedFvPatchFields/wallFunctions/atmNutUWallFunction/atmNutUWallFunctionFvPatchScalarField.H
src/atmosphericModels/derivedFvPatchFields/wallFunctions/atmNutUWallFunction/atmNutUWallFunctionFvPatchScalarField.C