OpenFOAM: dynamicCodeContext Class Reference
dynamicCodeContext Class Reference
Encapsulation of dynamic code dictionaries.
#include <dynamicCodeContext.H>
Public Member Functions
dynamicCodeContext ()
dynamicCodeContext (const dictionary &dict)
bool valid () const noexcept
void setCodeContext (const dictionary &dict)
const dictionary & dict () const noexcept
const string & options () const noexcept
const string & libs () const noexcept
const string & include () const noexcept
const string & localCode () const noexcept
const string & code () const noexcept
const SHA1 & sha1 () const noexcept
void append (const std::string &str)
const entry * findEntry (const word &key) const
bool readEntry (const word &key, string &str, bool mandatory=true, bool withLineNum=true)
bool readIfPresent (const word &key, string &str, bool withLineNum=true)
operator const dictionary & () const noexcept
Static Public Member Functions
static void inplaceExpand (string &str, const dictionary &dict)
static unsigned addLineDirective (string &code, label lineNum, const string &file)
static unsigned addLineDirective (string &code, label lineNum, const dictionary &dict)
Detailed Description
Encapsulation of dynamic code dictionaries.
Source files
dynamicCodeContext.H
dynamicCodeContext.C
Definition at line 49 of file dynamicCodeContext.H.
Constructor & Destructor Documentation
dynamicCodeContext() [1/2]
dynamicCodeContext ()
Definition at line 74 of file dynamicCodeContext.C.
dynamicCodeContext() [2/2]
dynamicCodeContext (const dictionary & dict) explicit
Definition at line 80 of file dynamicCodeContext.C.
References dynamicCodeContext::dict(), and dynamicCodeContext::setCodeContext().
Member Function Documentation
inplaceExpand()
void inplaceExpand (string & str, const dictionary & dict) static
Definition at line 28 of file dynamicCodeContext.C.
References dynamicCodeContext::dict(), Foam::stringOps::inplaceExpand(), and Foam::stringOps::inplaceTrim().
Referenced by dynamicCodeContext::readEntry().
addLineDirective() [1/2]
unsigned addLineDirective (string & code, label lineNum, const string & file) static
Definition at line 39 of file dynamicCodeContext.C.
References Foam::name().
addLineDirective() [2/2]
unsigned addLineDirective (string & code, label lineNum, const dictionary & dict) static
Definition at line 61 of file dynamicCodeContext.C.
References dict, and dictionary::name().
valid()
bool valid () const noexcept
Definition at line 90 of file dynamicCodeContext.C.
References dictionary::null.
setCodeContext()
void setCodeContext (const dictionary & dict)
Definition at line 157 of file dynamicCodeContext.C.
References dict, and readIfPresent().
Referenced by dynamicCodeContext::dynamicCodeContext().
dict()
const dictionary & dict () const inline noexcept
Definition at line 124 of file dynamicCodeContext.H.
References UPtrList< T >::get().
Referenced by dynamicCodeContext::dynamicCodeContext(), codeStream::getFunction(), dynamicCodeContext::inplaceExpand(), and codedBase::updateLibrary().
options()
const string & options () const inline noexcept
Definition at line 130 of file dynamicCodeContext.H.
Referenced by codeStream::getFunction(), codedPoints0MotionSolver::prepare(), codedMixedFvPatchField< Type >::prepare(), codedFunctionObject::prepare(), CodedSource< Type >::prepare(), CodedField< Type >::prepare(), and CodedFunction1< Type >::prepare().
libs()
const string & libs () const inline noexcept
Definition at line 136 of file dynamicCodeContext.H.
Referenced by codeStream::getFunction(), codedPoints0MotionSolver::prepare(), codedMixedFvPatchField< Type >::prepare(), codedFunctionObject::prepare(), CodedSource< Type >::prepare(), CodedField< Type >::prepare(), and CodedFunction1< Type >::prepare().
include()
const string & include () const inline noexcept
Definition at line 142 of file dynamicCodeContext.H.
Referenced by dynamicCode::setFilterContext().
localCode()
const string & localCode () const inline noexcept
Definition at line 148 of file dynamicCodeContext.H.
Referenced by dynamicCode::setFilterContext().
code()
const string & code () const inline noexcept
Definition at line 154 of file dynamicCodeContext.H.
Referenced by CodedField< Type >::prepare(), CodedFunction1< Type >::prepare(), and dynamicCode::setFilterContext().
sha1()
const SHA1 & sha1 () const inline noexcept
Definition at line 160 of file dynamicCodeContext.H.
Referenced by codeStream::getFunction(), codedPoints0MotionSolver::prepare(), codedMixedFvPatchField< Type >::prepare(), codedFunctionObject::prepare(), CodedSource< Type >::prepare(), CodedField< Type >::prepare(), CodedFunction1< Type >::prepare(), dynamicCode::setFilterContext(), codedBase::updateLibrary(), and dynamicCode::upToDate().
append()
void append (const std::string & str) inline
Definition at line 166 of file dynamicCodeContext.H.
findEntry()
const Foam::entry * findEntry (const word & key) const
Definition at line 96 of file dynamicCodeContext.C.
References dict, dictionary::findEntry(), and keyType::LITERAL.
readEntry()
bool readEntry (const word & key, string & str, bool mandatory = true, bool withLineNum = true)
Definition at line 102 of file dynamicCodeContext.C.
References dict, Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, dictionary::findEntry(), dynamicCodeContext::inplaceExpand(), keyType::LITERAL, dictionary::name(), and Foam::nl.
readIfPresent()
bool readIfPresent (const word & key, string & str, bool withLineNum = true)
Definition at line 146 of file dynamicCodeContext.C.
operator const dictionary &()
operator const dictionary & () const inline noexcept
Definition at line 204 of file dynamicCodeContext.H.
References dictionary::get().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/dynamicLibrary/dynamicCode/dynamicCodeContext.H
src/OpenFOAM/db/dynamicLibrary/dynamicCode/dynamicCodeContext.C