OpenFOAM: IOobject Class Reference
IOobject Class Reference
Defines the attributes of an object for which implicit objectRegistry management is supported, and provides the infrastructure for performing stream I/O.
#include <IOobject.H>
Public Types
enum objectState : char { GOOD , BAD }
enum fileCheckTypes : char { timeStamp , timeStampMaster , inotify , inotifyMaster }
Public Types inherited from IOobjectOption
enum readOption : unsigned char {
NO_READ = 0 , MUST_READ = 0x1 , READ_MODIFIED = 0x3 , MUST_READ_IF_MODIFIED = 0x3 ,
LAZY_READ = 0x4 , READ_IF_PRESENT = 0x4
}
enum writeOption : unsigned char { NO_WRITE = 0 , AUTO_WRITE = 0x10 }
enum registerOption : unsigned char { NO_REGISTER = 0 , REGISTER = 1 }
Public Member Functions
TypeName ("IOobject")
IOobject (const IOobject &)=default
virtual ~IOobject ()=default
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const fileName &path, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const fileName &path, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const IOobject &io, const objectRegistry &registry)
IOobject (const IOobject &io, const word &name)
IOobject (const IOobject &io, const word &name, const fileName &local)
IOobject (const IOobject &io, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt)
IOobject (const IOobject &io, IOobjectOption::registerOption regOpt)
autoPtr< IOobject > clone () const
autoPtr< IOobject > clone (const objectRegistry &registry) const
const objectRegistry & db () const noexcept
const Time & time () const noexcept
const word & name () const noexcept
const word & headerClassName () const noexcept
word & headerClassName () noexcept
const string & note () const noexcept
string & note () noexcept
virtual void rename (const word &newName)
unsigned labelByteSize () const noexcept
unsigned scalarByteSize () const noexcept
void resetHeader (const word &newName=word::null)
bool hasHeaderClass () const noexcept
template<class Type >
bool isHeaderClass () const
template<class Type >
bool isHeaderClassName () const
virtual const dictionary * findMetaData () const noexcept
word group () const
word member () const
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const noexcept
fileName & instance () noexcept
const fileName & local () const noexcept
fileName path () const
fileName path (const word &instance, const fileName &local=fileName::null) const
fileName objectPath () const
fileName objectRelPath () const
fileName localFilePath (const word &typeName, const bool search=true) const
fileName globalFilePath (const word &typeName, const bool search=true) const
IOstreamOption parseHeader (const dictionary &headerDict)
bool readHeader (Istream &is)
bool readHeader (dictionary &headerDict, Istream &is)
template<class Type >
bool typeHeaderOk (const bool checkType=true, const bool search=true, const bool verbose=true)
template<class Type >
void warnNoRereading () const
bool writeHeader (Ostream &os) const
bool writeHeader (Ostream &os, const word &objectType) const
void writeHeader (dictionary &dict, IOstreamOption streamOpt) const
void writeHeader (dictionary &dict, const word &objectType, IOstreamOption streamOpt) const
bool good () const noexcept
bool bad () const noexcept
InfoProxy< IOobject > info () const noexcept
void operator= (const IOobject &io)
template<>
bool isHeaderClass () const
template<class StringType >
Foam::word groupName (StringType base, const word &group)
Public Member Functions inherited from IOobjectOption
constexpr IOobjectOption (readOption rOpt=readOption::NO_READ, writeOption wOpt=writeOption::NO_WRITE, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (readOption rOpt, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (writeOption wOpt, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (registerOption registerObject, bool globalObject=false) noexcept
constexpr IOobjectOption (readOption rOpt, writeOption wOpt, bool registerObject, bool globalObject=false) noexcept
constexpr IOobjectOption (bool registerObject, bool globalObject=false) noexcept
readOption readOpt () const noexcept
readOption readOpt (readOption opt) noexcept
writeOption writeOpt () const noexcept
writeOption writeOpt (writeOption opt) noexcept
bool registerObject () const noexcept
bool registerObject (bool on) noexcept
bool globalObject () const noexcept
bool globalObject (bool on) noexcept
bool isAnyRead () const noexcept
bool isReadRequired () const noexcept
bool isReadOptional () const noexcept
readOption & readOpt () noexcept
writeOption & writeOpt () noexcept
bool & registerObject () noexcept
bool & globalObject () noexcept
Static Public Member Functions
static bool bannerEnabled () noexcept
static bool bannerEnabled (bool on) noexcept
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
template<class StringType >
static word groupName (StringType base, const word &group)
static word group (const word &name)
static word member (const word &name)
static word scopedName (const std::string &scope, const word &name)
static IOobject selectIO (const IOobject &io, const fileName &altFile, const word &ioName="")
static Ostream & writeBanner (Ostream &os, const bool noSyntaxHint=false)
static Ostream & writeDivider (Ostream &os)
static Ostream & writeEndDivider (Ostream &os)
Static Public Member Functions inherited from IOobjectOption
static bool isAnyRead (readOption opt) noexcept
static bool isReadRequired (readOption opt) noexcept
static bool isReadOptional (readOption opt) noexcept
static readOption lazierRead (readOption opt) noexcept
Static Public Attributes
static const Enum< fileCheckTypes > fileCheckTypesNames
static char scopeSeparator
static fileCheckTypes fileModificationChecking
static float fileModificationSkew
static int maxFileModificationPolls
Protected Member Functions
void setBad (const string &s)
Static Protected Member Functions
static void writeHeaderContent (Ostream &os, const IOobject &io, const word &objectType, const dictionary *metaDataDict=nullptr)
static void writeHeaderContent (dictionary &dict, const IOobject &io, const word &objectType, IOstreamOption streamOpt, const dictionary *metaDataDict=nullptr)
Detailed Description
Defines the attributes of an object for which implicit objectRegistry management is supported, and provides the infrastructure for performing stream I/O.
An IOobject is constructed with an object name, a class name, an instance path, a reference to a objectRegistry, and parameters determining its storage status.
Read options
Define what is done on object construction and explicit reads:
NO_READ
Do not read
MUST_READ
Object must be read from Istream on construction.
Error if Istream does not exist or cannot be read. Does not check timestamp or re-read.
READ_MODIFIED (MUST_READ_IF_MODIFIED)
Object must be read from Istream on construction.
Error if Istream does not exist or cannot be read. If object is registered its timestamp will be checked every timestep and possibly re-read.
LAZY_READ (READ_IF_PRESENT)
Read object from Istream, but only if Istream exists.
Error only if Istream exists but cannot be read. Does not check timestamp or re-read.
Write options
Define what is done on object destruction and explicit writes:
NO_WRITE
No automatic writing, but can be written explicitly
AUTO_WRITE
Object is written automatically when requested to by the objectRegistry.
When serializing, the IOobject characteristics are typically written as a FoamFile header, which is a sub-dictionary with the following type of content:
Property Description Type Reqd Deflt
version The base format version float no 2.0
format The stream format (ascii/binary) word yes
arch The architecture string string no
note Descriptive note about the object string no
location The relative location of the object string no
class The type of the object word yes
object The name of the object word yes
Note
Specifying registered does not result in the IOobject itself being registered. It is only serves as guidance for a regIOobject using it.
See also
Foam::objectRegistry Foam::regIOobject
Source files
IOobject.H
IOobject.C
IOobjectReadHeader.C
IOobjectWriteHeader.C
IOobjectPrint.C
Definition at line 171 of file IOobject.H.
Member Enumeration Documentation
objectState
enum objectState : char
Enumerator
GOOD
BAD
Definition at line 180 of file IOobject.H.
fileCheckTypes
enum fileCheckTypes : char
Enumerator
timeStamp
timeStampMaster
inotify
inotifyMaster
Definition at line 187 of file IOobject.H.
Constructor & Destructor Documentation
IOobject() [1/12]
IOobject (const IOobject &) default
~IOobject()
virtual ~IOobject () virtual default
IOobject() [2/12]
IOobject (const word & name, const fileName & instance, const objectRegistry & registry, IOobjectOption ioOpt = IOobjectOption())
Definition at line 313 of file IOobject.C.
References Foam::endl(), InfoInFunction, IOobject::instance(), and IOobject::name().
IOobject() [3/12]
IOobject (const word & name, const fileName & instance, const fileName & local, const objectRegistry & registry, IOobjectOption ioOpt = IOobjectOption())
Definition at line 334 of file IOobject.C.
References Foam::endl(), InfoInFunction, IOobject::instance(), IOobject::local(), and IOobject::name().
IOobject() [4/12]
IOobject (const fileName & path, const objectRegistry & registry, IOobjectOption ioOpt = IOobjectOption())
Definition at line 357 of file IOobject.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, IOobject::fileNameComponents(), InfoInFunction, and IOobject::path().
IOobject() [5/12]
IOobject (const word & name, const fileName & instance, const objectRegistry & registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt = IOobjectOption::NO_WRITE, bool registerObject = true, bool globalObject = false) inline
Definition at line 56 of file IOobjectI.H.
IOobject() [6/12]
IOobject (const word & name, const fileName & instance, const fileName & local, const objectRegistry & registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt = IOobjectOption::NO_WRITE, bool registerObject = true, bool globalObject = false) inline
Definition at line 77 of file IOobjectI.H.
IOobject() [7/12]
IOobject (const fileName & path, const objectRegistry & registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt = IOobjectOption::NO_WRITE, bool registerObject = true, bool globalObject = false) inline
Definition at line 100 of file IOobjectI.H.
IOobject() [8/12]
IOobject (const IOobject & io, const objectRegistry & registry)
Definition at line 381 of file IOobject.C.
IOobject() [9/12]
IOobject (const IOobject & io, const word & name)
Definition at line 402 of file IOobject.C.
IOobject() [10/12]
IOobject (const IOobject & io, const word & name, const fileName & local) inline
Definition at line 119 of file IOobjectI.H.
References IOobject::local().
IOobject() [11/12]
IOobject (const IOobject & io, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt) inline
Definition at line 132 of file IOobjectI.H.
References IOobjectOption::readOpt(), and IOobjectOption::writeOpt().
IOobject() [12/12]
IOobject (const IOobject & io, IOobjectOption::registerOption regOpt) inline
Definition at line 146 of file IOobjectI.H.
References IOobjectOption::registerObject().
Member Function Documentation
writeHeaderContent() [1/2]
void writeHeaderContent (Ostream & os, const IOobject & io, const word & objectType, const dictionary * metaDataDict = nullptr) static protected
Definition at line 150 of file IOobjectWriteHeader.C.
References Foam::foamVersion::buildArch, IOobject::db(), UPtrList< T >::empty(), IOstreamOption::format(), IOobject::instance(), io(), IOobject::local(), IOobject::name(), IOobject::note(), os(), IOstreamOption::version(), and Foam::writeHeaderEntry().
Referenced by IOobject::writeHeader(), and IOobject::writeHeader().
writeHeaderContent() [2/2]
void writeHeaderContent (dictionary & dict, const IOobject & io, const word & objectType, IOstreamOption streamOpt, const dictionary * metaDataDict = nullptr) static protected
Definition at line 189 of file IOobjectWriteHeader.C.
References dictionary::add(), Foam::foamVersion::buildArch, IOobject::db(), dict, UPtrList< T >::empty(), IOobject::instance(), io(), IOobject::local(), IOobject::name(), IOobject::note(), and dictionary::set().
setBad()
void setBad (const string & s) protected
Definition at line 528 of file IOobject.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, InfoInFunction, messageStream::level, and s().
TypeName()
TypeName ("IOobject")
bannerEnabled() [1/2]
static bool bannerEnabled () inline static noexcept
Definition at line 297 of file IOobject.H.
Referenced by decomposedBlockData::writeBlockEntry(), IOobject::writeHeader(), decomposedBlockData::writeHeader(), decomposedBlockData::writeHeader(), and collatedFileOperation::writeObject().
bannerEnabled() [2/2]
static bool bannerEnabled (bool on) inline static noexcept
Definition at line 304 of file IOobject.H.
fileNameComponents()
bool fileNameComponents (const fileName & path, fileName & instance, fileName & local, word & name) static
Definition at line 139 of file IOobject.C.
References PtrList< T >::clear(), Foam::cwd(), Foam::endl(), IOobject::fileNameComponents(), IOobject::instance(), Foam::isDir(), IOobject::local(), IOobject::name(), IOobject::path(), UPtrList< T >::size(), string::starts_with(), word::validate(), and WarningInFunction.
Referenced by IOobject::fileNameComponents(), and IOobject::IOobject().
groupName() [1/2]
template<class StringType > static word groupName (StringType base, const word & group) inline static
Referenced by phaseSystem::addField(), phaseSystem::addField(), phaseChange::addToDriftRate(), StaticPhaseModel< BasePhaseModel >::alphaPhi(), ThermalDiffusivity< BasicTurbulenceModel >::alphat(), basicMultiComponentMixture::basicMultiComponentMixture(), alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField::calcAlphat(), atmNutkWallFunctionFvPatchScalarField::calcNut(), atmNutUWallFunctionFvPatchScalarField::calcNut(), atmNutWallFunctionFvPatchScalarField::calcNut(), nutkFilmWallFunctionFvPatchScalarField::calcNut(), nutkRoughWallFunctionFvPatchScalarField::calcNut(), nutkWallFunctionFvPatchScalarField::calcNut(), nutUBlendedWallFunctionFvPatchScalarField::calcNut(), nutUSpaldingWallFunctionFvPatchScalarField::calcNut(), nutUTabulatedWallFunctionFvPatchScalarField::calcNut(), nutUWallFunctionFvPatchScalarField::calcNut(), nutkFilmWallFunctionFvPatchScalarField::calcUTau(), nutUBlendedWallFunctionFvPatchScalarField::calcUTau(), nutUSpaldingWallFunctionFvPatchScalarField::calcUTau(), nutUWallFunctionFvPatchScalarField::calcYPlus(), kOmegaSST::computeG(), turbulentDispersionModel::continuousTurbulence(), populationBalanceModel::continuousTurbulence(), Maxwell< BasicTurbulenceModel >::correct(), DarcyForchheimer::correct(), powerLaw::correct(), solidification::correct(), DarcyForchheimer::correct(), powerLaw::correct(), solidification::correct(), limitTemperature::correct(), MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::correctThermo(), Burns::D(), Gosman::D(), InterfaceCompositionModel< Thermo, OtherThermo >::D(), DeltaOmegaTildeDelta::DeltaOmegaTildeDelta(), kineticTheoryModel::devRhoReff(), phasePressureModel::devRhoReff(), Maxwell< BasicTurbulenceModel >::devRhoReff(), ReynoldsStress< BasicTurbulenceModel >::devRhoReff(), InterfaceCompositionModel< Thermo, OtherThermo >::Dfrom(), MovingPhaseModel< BasePhaseModel >::diffNo(), phaseSystem::dmdt(), SpalartAllmarasBase< BasicEddyViscosityModel >::DnuTildaEff(), InterfaceCompositionModel< Thermo, OtherThermo >::Dto(), SpalartAllmarasBase< BasicEddyViscosityModel >::epsilon(), laminarModel< BasicTurbulenceModel >::epsilon(), LESModel< BasicTurbulenceModel >::epsilon(), sigma< BasicTurbulenceModel >::epsilon(), RASModel< BasicTurbulenceModel >::epsilon(), DispersionRASModel< CloudType >::epsilonModel(), phaseSystem::fillFields(), phaseSystem::fillFields(), kOmegaSSTLM< BasicTurbulenceModel >::Flength(), kOmegaSSTLM< BasicTurbulenceModel >::Fonset(), phaseSystem::foundBlendedSubModel(), phaseSystem::foundSubModel(), kOmegaSSTLM< BasicTurbulenceModel >::Fthetat(), multiphaseInterSystem::generatePairsAndSubModels(), phaseSystem::generatePairsAndSubModels(), hyperbolic::hyperbolic(), IDDESDelta::IDDESDelta(), InterfaceCompositionPhaseChangePhaseSystem< BasePhaseSystem >::InterfaceCompositionPhaseChangePhaseSystem(), MovingPhaseModel< BasePhaseModel >::K(), SpalartAllmarasBase< BasicEddyViscosityModel >::k(), laminarModel< BasicTurbulenceModel >::k(), sigma< BasicTurbulenceModel >::k(), Smagorinsky< BasicTurbulenceModel >::k(), WALE< BasicTurbulenceModel >::k(), DispersionRASModel< CloudType >::kModel(), InterfaceCompositionModel< Thermo, OtherThermo >::L(), linear::linear(), continuousGasKEqn< BasicTurbulenceModel >::liquidTurbulence(), continuousGasKEpsilon< BasicTurbulenceModel >::liquidTurbulence(), phaseSystem::lookupBlendedSubModel(), multiphaseInterSystem::lookupSubModel(), phaseSystem::lookupSubModel(), twoPhaseSystem::lookupSubModel(), kaqRWallFunctionFvPatchScalarField::manipulateMatrix(), InterfaceCompositionPhaseChangePhaseSystem< BasePhaseSystem >::massTransfer(), PhaseTransferPhaseSystem< BasePhaseSystem >::massTransfer(), PopulationBalancePhaseSystem< BasePhaseSystem >::massTransfer(), ThermalPhaseChangePhaseSystem< BasePhaseSystem >::massTransfer(), MassTransferPhaseSystem< BasePhaseSystem >::MassTransferPhaseSystem(), moleFractions< ThermoType >::moleFractions(), MomentumTransferPhaseSystem< BasePhaseSystem >::MomentumTransferPhaseSystem(), MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::MultiComponentPhaseModel(), laminarModel< BasicTurbulenceModel >::New(), LESModel< BasicTurbulenceModel >::New(), RASModel< BasicTurbulenceModel >::New(), TurbulenceModel< Alpha, Rho, BasicTurbulenceModel, TransportModel >::New(), strainRateFunction::nu(), continuousGasKEpsilon< BasicTurbulenceModel >::nuEff(), generalizedNewtonian< BasicMomentumTransportModel >::nuEff(), laminarModel< BasicTurbulenceModel >::nuEff(), Stokes< BasicTurbulenceModel >::nuEff(), LESModel< BasicTurbulenceModel >::nuEff(), RASModel< BasicTurbulenceModel >::nuEff(), generalizedNewtonian< BasicMomentumTransportModel >::nut(), Stokes< BasicTurbulenceModel >::nut(), SpalartAllmarasBase< BasicEddyViscosityModel >::omega(), laminarModel< BasicTurbulenceModel >::omega(), LESModel< BasicTurbulenceModel >::omega(), RASModel< BasicTurbulenceModel >::omega(), phaseChange::phaseChange(), phaseForces::phaseForces(), phaseModel::phaseModel(), phaseModel::phaseModel(), basicThermo::phasePropertyName(), basicThermo::phasePropertyName(), basicThermo::phaseScopedName(), StaticPhaseModel< BasePhaseModel >::phi(), populationBalanceModel::populationBalanceModel(), PopulationBalancePhaseSystem< BasePhaseSystem >::PopulationBalancePhaseSystem(), PhaseCompressibleTurbulenceModel< TransportModel >::pPrime(), PhaseIncompressibleTurbulenceModel< TransportModel >::pPrime(), PhaseCompressibleTurbulenceModel< TransportModel >::pPrimef(), PhaseIncompressibleTurbulenceModel< TransportModel >::pPrimef(), InertPhaseModel< BasePhaseModel >::Qdot(), kineticTheoryModel::R(), phasePressureModel::R(), continuousGasKEpsilon< BasicTurbulenceModel >::R(), laminarModel< BasicTurbulenceModel >::R(), phaseChange::R(), wallBoiling::R(), BilgerMixtureFraction::read(), limitTemperature::read(), sampledSurfaces::read(), kOmegaSSTLM< BasicTurbulenceModel >::ReThetac(), kOmegaSSTLM< BasicTurbulenceModel >::ReThetat0(), continuousGasKEpsilon< BasicTurbulenceModel >::rhoEff(), SLADelta::SLADelta(), ThermalPhaseChangePhaseSystem< BasePhaseSystem >::ThermalPhaseChangePhaseSystem(), ThermoPhaseModel< BasePhaseModel, ThermoType >::ThermoPhaseModel(), TwoResistanceHeatTransferPhaseSystem< BasePhaseSystem >::TwoResistanceHeatTransferPhaseSystem(), StaticPhaseModel< BasePhaseModel >::U(), atmAlphatkWallFunctionFvPatchScalarField::updateCoeffs(), alphatWallBoilingWallFunctionFvPatchScalarField::updateCoeffs(), JohnsonJacksonParticleSlipFvPatchVectorField::updateCoeffs(), JohnsonJacksonParticleThetaFvPatchScalarField::updateCoeffs(), alphatFilmWallFunctionFvPatchScalarField::updateCoeffs(), convectiveHeatTransferFvPatchScalarField::updateCoeffs(), totalFlowRateAdvectiveDiffusiveFvPatchScalarField::updateCoeffs(), alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs(), alphatWallFunctionFvPatchScalarField::updateCoeffs(), wallHeatTransferFvPatchScalarField::updateCoeffs(), fixedShearStressFvPatchVectorField::updateCoeffs(), porousBafflePressureFvPatchField::updateCoeffs(), epsilonWallFunctionFvPatchScalarField::updateCoeffs(), kLowReWallFunctionFvPatchScalarField::updateCoeffs(), omegaWallFunctionFvPatchScalarField::updateCoeffs(), turbulentMixingLengthDissipationRateInletFvPatchScalarField::updateCoeffs(), turbulentMixingLengthFrequencyInletFvPatchScalarField::updateCoeffs(), epsilonWallFunctionFvPatchScalarField::updateWeightedCoeffs(), omegaWallFunctionFvPatchScalarField::updateWeightedCoeffs(), externalCoupledTemperatureMixedFvPatchScalarField::writeData(), Henry< Thermo, OtherThermo >::YfPrime(), nutkFilmWallFunctionFvPatchScalarField::yPlus(), nutkWallFunctionFvPatchScalarField::yPlus(), nutLowReWallFunctionFvPatchScalarField::yPlus(), nutUBlendedWallFunctionFvPatchScalarField::yPlus(), nutURoughWallFunctionFvPatchScalarField::yPlus(), nutUSpaldingWallFunctionFvPatchScalarField::yPlus(), nutUTabulatedWallFunctionFvPatchScalarField::yPlus(), nutUWallFunctionFvPatchScalarField::yPlus(), and StationaryPhaseModel< BasePhaseModel >::zeroField().
group() [1/2]
Foam::word group (const word & name) static
Definition at line 275 of file IOobject.C.
References Foam::name().
Referenced by laminarModel< BasicTurbulenceModel >::New(), LESModel< BasicTurbulenceModel >::New(), RASModel< BasicTurbulenceModel >::New(), TurbulenceModel< Alpha, Rho, BasicTurbulenceModel, TransportModel >::New(), and strainRateFunction::nu().
member() [1/2]
Foam::word member (const word & name) static
Definition at line 288 of file IOobject.C.
References Foam::name().
Referenced by ThermalPhaseChangePhaseSystem< BasePhaseSystem >::correctInterfaceThermo().
scopedName()
Foam::word scopedName (const std::string & scope, const word & name) inline static
Definition at line 39 of file IOobjectI.H.
References UPtrList< T >::empty(), Foam::name(), and IOobject::scopeSeparator.
Referenced by interRegionHeatTransferModel::addSup(), adjointkOmegaSST::beta(), adjointkOmegaSST::beta(), kOmegaSSTBase< BasicEddyViscosityModel >::beta(), SuppressionCollision< CloudType >::collide(), kOmegaSST::computeG(), kEpsilon< BasicTurbulenceModel >::correct(), RNGkEpsilon< BasicTurbulenceModel >::correct(), contactAngleForce::correct(), solverInfo::createResidualField(), adjointkOmegaSST::gamma(), adjointkOmegaSST::gamma(), kOmegaSSTBase< BasicEddyViscosityModel >::gamma(), kOmegaSSTBase< BasicEddyViscosityModel >::GbyNu0(), turbulenceModel::GName(), turbulenceFields::initialise(), kOmegaSSTDES< BasicTurbulenceModel >::LESRegion(), SpalartAllmarasDES< BasicTurbulenceModel >::LESRegion(), strainRateFunction::nu(), phaseChange::phaseChange(), basicThermo::phaseScopedName(), turbulenceFields::processField(), SpalartAllmarasDES< BasicTurbulenceModel >::psi(), turbulenceFields::read(), multiFieldValue::read(), multiRegion::read(), functionObject::scopedName(), lduMatrix::setResidualField(), dynamicContactAngleForce::theta(), adjointkOmegaSST::updatePrimalRelatedFields(), turbulenceFields::write(), and electricPotential::write().
selectIO()
Foam::IOobject selectIO (const IOobject & io, const fileName & altFile, const word & ioName = "") static
Definition at line 230 of file IOobject.C.
References IOobject::db(), UPtrList< T >::empty(), IOobjectOption::globalObject(), io(), Foam::isDir(), IOobject::name(), IOobjectOption::readOpt(), IOobjectOption::registerObject(), and IOobjectOption::writeOpt().
Referenced by decompositionModel::selectIO().
clone() [1/2]
autoPtr< IOobject > clone () const inline
Definition at line 494 of file IOobject.H.
References autoPtr< T >::New().
Referenced by searchableSurface::iNew::operator()(), and polyBoundaryMesh::polyBoundaryMesh().
clone() [2/2]
autoPtr< IOobject > clone (const objectRegistry & registry) const inline
Definition at line 500 of file IOobject.H.
References autoPtr< T >::New().
db()
const Foam::objectRegistry & db () const noexcept
Definition at line 425 of file IOobject.C.
Referenced by refinementHistory::add(), refinementHistory::apply(), SprayParcel< ParcelType >::calcAtomization(), isothermal::correct(), isothermal::d(), IATEsource::Eo(), hexRef8Data::hexRef8Data(), InjectionModel< CloudType >::inject(), InjectionModel< CloudType >::injectSteadyState(), PhiScheme< Type, PhiLimiter >::limiter(), Foam::loadPointField(), voxelMeshSearch::makeMesh(), IATEsource::Mo(), fvMeshTools::newMesh(), faMeshTools::newMesh(), rhoMagSqr< Type >::operator()(), rhoMagSqr< Type >::operator()(), fileOperation::processorsPath(), wallBoiling::R(), ReactingCloud< CloudType >::ReactingCloud(), refinementHistory::refinementHistory(), regionProperties::regionProperties(), searchableSurfaceCollection::searchableSurfaceCollection(), IOobject::selectIO(), motionSmootherAlgo::setDisplacement(), hexRef8Data::sync(), ThermoCloud< CloudType >::ThermoCloud(), KinematicParcel< ParcelType >::trackingData::updateAverages(), MPPICParcel< ParcelType >::trackingData::updateAverages(), PDRblock::writeBlockMeshDict(), decomposedBlockData::writeHeader(), IOobject::writeHeaderContent(), and IOobject::writeHeaderContent().
time()
const Foam::Time & time () const noexcept
Definition at line 431 of file IOobject.C.
Referenced by objective::accumulateJMean(), PrinceBlanch::addToCoalescenceRate(), InterfaceCompositionModel< Thermo, OtherThermo >::Dfrom(), distributedTriSurfaceMesh::distribute(), InterfaceCompositionModel< Thermo, OtherThermo >::Dto(), objective::isWithinIntegrationTime(), InterfaceCompositionModel< Thermo, OtherThermo >::L(), fvMeshTools::newMesh(), faMeshTools::newMesh(), objectiveManager::objectiveManager(), points0MotionSolver::points0MotionSolver(), fileOperation::processorsCasePath(), data::setSolverPerformance(), StandardChemistryModel< ReactionThermo, ThermoType >::StandardChemistryModel(), TDACChemistryModel< ReactionThermo, ThermoType >::TDACChemistryModel(), fvMesh::time(), pressurePIDControlInletVelocityFvPatchVectorField::updateCoeffs(), subCycleField< GeometricField >::updateTimeIndex(), triSurfaceMesh::writeObject(), regIOobject::writeObject(), and subCycleField< GeometricField >::~subCycleField().
name()
const Foam::word & name () const inline noexcept
Definition at line 162 of file IOobjectI.H.
Referenced by polyMeshAdder::add(), snappyLayerDriver::addLayers(), polyTopoChange::addMesh(), exprResultGlobals::addValue(), exprResultGlobals::addValue(), exprResultGlobals::addValue(), basicThermo::basicThermo(), cellZoneSet::cellZoneSet(), objectRegistry::checkIn(), objectRegistry::checkOut(), objectRegistry::clear(), meshObject::clear(), meshObject::clearUpto(), CollidingCloud< CloudType >::clone(), KinematicCloud< CloudType >::clone(), MPPICCloud< CloudType >::clone(), ReactingCloud< CloudType >::clone(), ReactingHeterogeneousCloud< CloudType >::clone(), ReactingMultiphaseCloud< CloudType >::clone(), ThermoCloud< CloudType >::clone(), SprayCloud< CloudType >::clone(), injectedParticleCloud::clone(), adjointkOmegaSST::convectionScheme(), RASModelVariables::copyAndRename(), atmNutSource::correct(), multiphaseStabilizedTurbulence::correct(), IOobjectList::countImpl(), IOobjectList::countTypeImpl(), fvMeshTools::createDummyFvMeshFiles(), decomposedBlockData::decomposedBlockData(), distributedTriSurfaceMesh::distribute(), faMeshDistributor::distributeAreaFields(), distributedTriSurfaceMesh::distributedTriSurfaceMesh(), faMeshDistributor::distributeEdgeFields(), BlendedInterfacialModel< ModelType >::evaluate(), thermalShell::evolveRegion(), readFields::execute(), removeRegisteredObject::execute(), fileOperation::exists(), faceZoneSet::faceZoneSet(), IOobject::fileNameComponents(), fileOperation::findInstance(), distributedTriSurfaceMesh::findLineAll(), distributedTriSurfaceMesh::findNearest(), distributedTriSurfaceMesh::findNearest(), genericPatchFieldBase::genericFatalSolveError(), exprResultGlobals::get(), distributedTriSurfaceMesh::getField(), exprResultGlobals::getNamespace(), distributedTriSurfaceMesh::getNormal(), distributedTriSurfaceMesh::getRegion(), distributedTriSurfaceMesh::getVolumeType(), AnisothermalPhaseModel< BasePhaseModel >::heEqn(), Foam::interpolate(), IOobject::IOobject(), IOobject::IOobject(), triSurfaceMesh::isSurfaceClosed(), sizeGroup::keyword(), triSurfaceLoader::load(), Foam::loadPointField(), objectRegistry::lookupObjectPtr(), objectRegistry::lookupObjectRefPtr(), voxelMeshSearch::makeMesh(), mappedPatchFieldBase< Type >::mapper(), solidBodyFvGeometryScheme::movePoints(), meshObject::movePoints(), fvMesh::name(), baseIOdictionary::name(), faePatchField< Type >::New(), faPatchField< Type >::New(), faePatchField< Type >::New(), faPatchField< Type >::New(), fvsPatchField< Type >::New(), fvPatchField< Type >::New(), fvPatchField< Type >::New(), fvsPatchField< Type >::New(), pointPatchField< Type >::New(), pointPatchField< Type >::New(), topoSet::New(), fvMeshTools::newMesh(), GeometricField< symmTensor, fvPatchField, volMesh >::normalise(), Foam::operator==(), Foam::operator==(), pointMesh::pointMesh(), pointZoneSet::pointZoneSet(), polyMesh::polyMesh(), polyMesh::polyMesh(), populationBalanceModel::populationBalanceModel(), genericPatchFieldBase::processEntry(), ReactingCloud< CloudType >::ReactingCloud(), wallBoundedStreamLine::read(), mixedFvPatchField< scalar >::readMixedEntries(), faFieldReconstructor::reconstructAreaFields(), faFieldReconstructor::reconstructEdgeFields(), lagrangianReconstructor::reconstructFieldFields(), lagrangianReconstructor::reconstructFields(), fvFieldReconstructor::reconstructInternalFields(), pointFieldReconstructor::reconstructPointFields(), fvFieldReconstructor::reconstructSurfaceFields(), fvFieldReconstructor::reconstructVolumeFields(), polyMesh::regionName(), exprResultGlobals::removeValue(), genericPatchFieldBase::reportMissingEntry(), objectRegistry::resetCacheTemporaryObject(), Time::run(), searchableSurfaceCollection::searchableSurfaceCollection(), IOobject::selectIO(), multiphaseSystem::solve(), KirchhoffShell::solveDisplacement(), oversetFvMeshBase::solveOverset(), kinematicSingleLayer::solveThickness(), regIOobject::store(), regIOobject::store(), subCycleField< GeometricField >::subCycleField(), ThermoCloud< CloudType >::ThermoCloud(), dictionary::topDict(), triSurfaceMesh::triSurfaceMesh(), triSurfaceMesh::triSurfaceMesh(), UniformDimensionedField< Type >::UniformDimensionedField(), KinematicParcel< ParcelType >::trackingData::updateAverages(), MPPICParcel< ParcelType >::trackingData::updateAverages(), waveSurfacePressureFvPatchScalarField::updateCoeffs(), topoBitSet::updateLabels(), topoBoolSet::updateLabels(), meshObject::updateMesh(), basicThermo::validate(), basicThermo::validate(), basicThermo::validate(), basicThermo::validate(), regionSizeDistribution::write(), writeCellVolumes::write(), MeshedSurfaceProxy< Face >::write(), PDRblock::writeBlockMeshDict(), faBoundaryMesh::writeData(), decomposedBlockData::writeHeader(), IOobject::writeHeaderContent(), IOobject::writeHeaderContent(), regionFunctionObject::writeObject(), Cloud< ParcelType >::writeObject(), regIOobject::writeObject(), distributedTriSurfaceMesh::writeObject(), and MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::YiEqn().
headerClassName() [1/2]
const Foam::word & headerClassName () const inline noexcept
Definition at line 180 of file IOobjectI.H.
Referenced by IOobjectList::countImpl(), decomposedBlockData::isCollatedType(), Foam::loadPointField(), IOobjectList::lookupClassImpl(), IOobjectList::namesImpl(), decomposedBlockData::readHeader(), decomposedBlockData::writeData(), Foam::writeMeshObject(), and Cloud< ParcelType >::writeObject().
headerClassName() [2/2]
Foam::word & headerClassName () inline noexcept
Definition at line 186 of file IOobjectI.H.
note() [1/2]
const Foam::string & note () const inline noexcept
Definition at line 192 of file IOobjectI.H.
Referenced by decomposedBlockData::writeData(), decomposedBlockData::writeHeader(), IOobject::writeHeaderContent(), and IOobject::writeHeaderContent().
note() [2/2]
Foam::string & note () inline noexcept
Definition at line 198 of file IOobjectI.H.
rename()
virtual void rename (const word & newName) inline virtual
Reimplemented in objectRegistry, and regIOobject.
Definition at line 532 of file IOobject.H.
Referenced by searchableCone::findLine(), searchableCone::findLineAll(), searchableCone::findLineAny(), dynamicMotionSolverListFvMesh::init(), processorFaMeshes::removeFiles(), processorMeshes::removeFiles(), regIOobject::rename(), and faMeshReconstructor::writeMesh().
labelByteSize()
unsigned labelByteSize () const inline noexcept
Definition at line 204 of file IOobjectI.H.
scalarByteSize()
unsigned scalarByteSize () const inline noexcept
Definition at line 210 of file IOobjectI.H.
resetHeader()
void resetHeader (const word & newName = word::null)
Definition at line 547 of file IOobject.C.
hasHeaderClass()
bool hasHeaderClass () const inline noexcept
Definition at line 218 of file IOobjectI.H.
References UPtrList< T >::empty().
Referenced by polyMesh::polyMesh().
isHeaderClass() [1/2]
template<class Type > bool isHeaderClass () const inline
Definition at line 225 of file IOobjectI.H.
Referenced by IOobjectList::cfindObject(), IOobjectList::countTypeImpl(), Foam::loadPointField(), IOobjectList::lookupClassTypeImpl(), IOobjectList::namesTypeImpl(), IOobjectList::objectsTypeImpl(), Cloud< ParticleType >::readStoreFile(), faFieldReconstructor::reconstructAreaFields(), faFieldReconstructor::reconstructEdgeFields(), lagrangianReconstructor::reconstructFields(), fvFieldReconstructor::reconstructInternalFields(), pointFieldReconstructor::reconstructPointFields(), fvFieldReconstructor::reconstructSurfaceFields(), and fvFieldReconstructor::reconstructVolumeFields().
isHeaderClassName()
template<class Type > bool isHeaderClassName () const inline
Definition at line 560 of file IOobject.H.
findMetaData()
const Foam::dictionary * findMetaData () const virtual noexcept
Reimplemented in regIOobject.
Definition at line 26 of file IOobjectMetaData.C.
Referenced by decomposedBlockData::writeExtraHeaderContent(), and decomposedBlockData::writeHeader().
group() [2/2]
Foam::word group () const inline
Definition at line 168 of file IOobjectI.H.
References word::ext().
Referenced by IOobject::groupName().
member() [2/2]
Foam::word member () const inline
Definition at line 174 of file IOobjectI.H.
References word::lessExt().
Referenced by diffusionGasEvaporation< Thermo, OtherThermo >::Kexp(), kineticGasEvaporation< Thermo, OtherThermo >::Kexp(), and kineticGasEvaporation< Thermo, OtherThermo >::kineticGasEvaporation().
rootPath()
const Foam::fileName & rootPath () const
Definition at line 437 of file IOobject.C.
Referenced by fileOperation::processorsCasePath().
caseName()
const Foam::fileName & caseName () const
Definition at line 443 of file IOobject.C.
instance() [1/2]
const Foam::fileName & instance () const inline noexcept
Definition at line 233 of file IOobjectI.H.
Referenced by snappyLayerDriver::addLayers(), IOobject::fileNameComponents(), Time::findInstance(), fileOperation::findInstance(), IOobject::IOobject(), IOobject::IOobject(), Foam::loadPointField(), triSurfaceMesh::movePoints(), points0MotionSolver::points0IO(), surfMesh::setInstance(), polyMesh::setInstance(), topoSet::setInstance(), surfMesh::surfMesh(), surfMesh::surfMesh(), decomposedBlockData::writeHeader(), IOobject::writeHeaderContent(), IOobject::writeHeaderContent(), triSurfaceMesh::writeObject(), regIOobject::writeObject(), and distributedTriSurfaceMesh::writeObject().
instance() [2/2]
Foam::fileName & instance () inline noexcept
Definition at line 239 of file IOobjectI.H.
local()
const Foam::fileName & local () const inline noexcept
Definition at line 245 of file IOobjectI.H.
Referenced by IOobject::fileNameComponents(), fileOperation::findInstance(), IOobject::IOobject(), IOobject::IOobject(), Foam::loadPointField(), fileOperation::processorsPath(), PDRblock::writeBlockMeshDict(), decomposedBlockData::writeHeader(), IOobject::writeHeaderContent(), and IOobject::writeHeaderContent().
path() [1/2]
Foam::fileName path () const
Definition at line 449 of file IOobject.C.
References local.
Referenced by IOobject::fileNameComponents(), IOobject::IOobject(), fileOperation::readObjects(), hexRef8::removeFiles(), refinementHistory::removeFiles(), meshRefinement::removeFiles(), topoSet::removeFiles(), and Time::writeObject().
path() [2/2]
Foam::fileName path (const word & instance, const fileName & local = fileName::null) const
Definition at line 472 of file IOobject.C.
References local.
objectPath()
Foam::fileName objectPath () const inline
Definition at line 251 of file IOobjectI.H.
References Foam::name(), and path().
Referenced by baseIOdictionary::baseIOdictionary(), baseIOdictionary::baseIOdictionary(), fileOperation::exists(), genericPatchFieldBase::genericFatalSolveError(), hexRef8::hexRef8(), fileOperation::objectPath(), genericPatchFieldBase::processEntry(), fileOperation::readObjects(), masterUncollatedFileOperation::readObjects(), uncollatedFileOperation::readObjects(), processorFaMeshes::removeFiles(), processorMeshes::removeFiles(), genericPatchFieldBase::reportMissingEntry(), hexRef8::setRefinement(), fileOperation::writeObject(), triSurfaceMesh::writeObject(), regIOobject::writeObject(), and distributedTriSurfaceMesh::writeObject().
objectRelPath()
Foam::fileName objectRelPath () const
Definition at line 483 of file IOobject.C.
References local, and Foam::name().
Referenced by faMeshTools::readProcAddressing(), fvMeshTools::readProcAddressing(), faMeshTools::writeProcAddressing(), and fvMeshTools::writeProcAddressing().
localFilePath()
Foam::fileName localFilePath (const word & typeName, const bool search = true) const
Definition at line 506 of file IOobject.C.
References Foam::fileHandler, and Foam::search().
Referenced by localIOdictionary::filePath(), distributedTriSurfaceMesh::filePath(), Foam::typeFilePath(), and fvExprDriver::updateSet().
globalFilePath()
Foam::fileName globalFilePath (const word & typeName, const bool search = true) const
Definition at line 517 of file IOobject.C.
References Foam::fileHandler, and Foam::search().
Referenced by porosityModel::filePath(), extendedFeatureEdgeMesh::filePath(), featureEdgeMesh::filePath(), searchableSurface::filePath(), triSurfaceMesh::filePath(), GlobalIOField< Type >::filePath(), GlobalIOList< Type >::filePath(), IOdictionary::filePath(), unwatchedIOdictionary::filePath(), IOMap< T >::filePath(), UniformDimensionedField< Type >::filePath(), Foam::typeFilePath(), and Foam::typeFilePath< IOMap< dictionary > >().
parseHeader()
Foam::IOstreamOption parseHeader (const dictionary & headerDict)
Definition at line 28 of file IOobjectReadHeader.C.
References UPtrList< T >::get(), Foam::foamVersion::labelByteSize(), and Foam::foamVersion::scalarByteSize().
readHeader() [1/2]
bool readHeader (Istream & is)
Definition at line 160 of file IOobjectReadHeader.C.
References IOobject::readHeader().
Referenced by decomposedBlockData::read(), decomposedBlockData::readHeader(), IOobject::readHeader(), and decomposedBlockData::writeData().
readHeader() [2/2]
bool readHeader (dictionary & headerDict, Istream & is)
Definition at line 66 of file IOobjectReadHeader.C.
References Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, Foam::Info, InfoInFunction, IOWarningInFunction, Foam::name(), Foam::nl, SeriousIOErrorInFunction, and Foam::writeHeader().
typeHeaderOk()
template<class Type > bool typeHeaderOk (const bool checkType = true, const bool search = true, const bool verbose = true)
Definition at line 31 of file IOobjectTemplates.C.
References Pstream::broadcast(), Foam::endl(), Foam::fileHandler, IOobject::fileModificationChecking, IOobject::inotifyMaster, UPstream::master(), Foam::search(), IOobject::timeStampMaster, and WarningInFunction.
Referenced by basicMultiComponentMixture::basicMultiComponentMixture(), fvMeshTools::createDummyFvMeshFiles(), fileOperation::exists(), topoSet::findIOobject(), hexRef8::hexRef8(), viewFactor::initialise(), PatchCollisionDensity< CloudType >::PatchCollisionDensity(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::pyrolysisChemistryModel(), TDACChemistryModel< ReactionThermo, ThermoType >::TDACChemistryModel(), fvExprDriver::updateSet(), and Foam::writeMeshObject().
warnNoRereading()
template<class Type > void warnNoRereading () const
Definition at line 86 of file IOobjectTemplates.C.
References Foam::endl(), Foam::name(), IOobjectOption::READ_MODIFIED, and WarningInFunction.
writeBanner()
Foam::Ostream & writeBanner (Ostream & os, const bool noSyntaxHint = false) static
Definition at line 72 of file IOobjectWriteHeader.C.
References Foam::foamVersion::api, and os().
Referenced by argList::parse(), IOobject::writeHeader(), decomposedBlockData::writeHeader(), and decomposedBlockData::writeHeader().
writeDivider()
Foam::Ostream & writeDivider (Ostream & os) static
Definition at line 128 of file IOobjectWriteHeader.C.
References os().
Referenced by Foam::listSwitches(), argList::parse(), edgeMeshFormat::write(), IOobject::writeHeader(), decomposedBlockData::writeHeader(), and decomposedBlockData::writeHeader().
writeEndDivider()
Foam::Ostream & writeEndDivider (Ostream & os) static
Definition at line 138 of file IOobjectWriteHeader.C.
References os().
Referenced by PDRblock::blockMeshDict(), MeshedSurfaceProxy< Face >::write(), PDRblock::writeBlockMeshDict(), decomposedBlockData::writeData(), collatedFileOperation::writeObject(), fileOperation::writeObject(), masterUncollatedFileOperation::writeObject(), boundaryDataWriter::writeTemplate(), and debugWriter::writeTemplate().
writeHeader() [1/4]
bool writeHeader (Ostream & os) const
Definition at line 273 of file IOobjectWriteHeader.C.
References os(), Foam::type(), and IOobject::writeHeader().
Referenced by MeshedSurfaceProxy< Face >::write(), interpolationLookUpTable< Type >::write(), decomposedBlockData::writeBlockEntry(), IOobject::writeHeader(), IOobject::writeHeader(), and fileOperation::writeObject().
writeHeader() [2/4]
bool writeHeader (Ostream & os, const word & objectType) const
Definition at line 231 of file IOobjectWriteHeader.C.
References IOobject::bannerEnabled(), Ostream::beginBlock(), Ostream::endBlock(), Foam::endl(), IOstream::good(), IOstream::info(), InfoInFunction, Foam::nl, os(), IOobject::writeBanner(), IOobject::writeDivider(), and IOobject::writeHeaderContent().
writeHeader() [3/4]
void writeHeader (dictionary & dict, IOstreamOption streamOpt) const
Definition at line 297 of file IOobjectWriteHeader.C.
References dict, Foam::type(), and IOobject::writeHeader().
writeHeader() [4/4]
void writeHeader (dictionary & dict, const word & objectType, IOstreamOption streamOpt) const
Definition at line 279 of file IOobjectWriteHeader.C.
References dict, and IOobject::writeHeaderContent().
good()
bool good () const inline noexcept
Definition at line 259 of file IOobjectI.H.
Referenced by topoSet::topoSet(), topoSet::topoSet(), and regIOobject::writeObject().
bad()
bool bad () const inline noexcept
Definition at line 265 of file IOobjectI.H.
info()
InfoProxy< IOobject > info () const inline noexcept
Definition at line 704 of file IOobject.H.
Referenced by profiling::create(), searchableSurfaceWithGaps::findNearest(), searchableSurface::findNearest(), GeometricField< Type, PatchField, GeoMesh >::GeometricField(), GeometricField< Type, PatchField, GeoMesh >::GeometricField(), GeometricField< Type, PatchField, GeoMesh >::GeometricField(), GeometricField< Type, PatchField, GeoMesh >::GeometricField(), GeometricField< Type, PatchField, GeoMesh >::GeometricField(), GeometricField< Type, PatchField, GeoMesh >::GeometricField(), GeometricField< Type, PatchField, GeoMesh >::GeometricField(), GeometricField< Type, PatchField, GeoMesh >::GeometricField(), GeometricField< Type, PatchField, GeoMesh >::GeometricField(), GeometricField< Type, PatchField, GeoMesh >::GeometricField(), searchableSurfaceWithGaps::getField(), searchableSurfaceWithGaps::getNormal(), searchableSurfaceWithGaps::getRegion(), searchableSurfaceWithGaps::getVolumeType(), irregularWaveModel::info(), regularWaveModel::info(), solitaryWaveModel::info(), waveGenerationModel::info(), Boussinesq::info(), cnoidal::info(), Grimshaw::info(), irregularMultiDirectional::info(), McCowan::info(), StokesI::info(), StokesII::info(), StokesV::info(), streamFunction::info(), Foam::operator<<(), profiling::profiling(), and KinematicCloud< CloudType >::solve().
operator=()
void operator= (const IOobject & io)
Definition at line 563 of file IOobject.C.
References IOobjectOption::globalObject(), io(), IOobjectOption::readOpt(), and IOobjectOption::writeOpt().
Referenced by regIOobject::operator=().
isHeaderClass() [2/2]
template<> bool isHeaderClass () const inline
Definition at line 718 of file IOobject.H.
groupName() [2/2]
template<class StringType > Foam::word groupName (StringType base, const word & group) inline
Definition at line 24 of file IOobjectI.H.
References IOobject::group().
Member Data Documentation
fileCheckTypesNames
const Foam::Enum< Foam::IOobject::fileCheckTypes > fileCheckTypesNames static
Definition at line 196 of file IOobject.H.
Referenced by argList::parse().
scopeSeparator
char scopeSeparator static
Definition at line 282 of file IOobject.H.
Referenced by IOobject::scopedName(), and dsmcFields::write().
fileModificationChecking
Foam::IOobject::fileCheckTypes fileModificationChecking static
Definition at line 285 of file IOobject.H.
Referenced by unwatchedIOdictionary::addWatch(), regIOobject::addWatch(), fileOperation::lookupAndCacheProcessorsPath(), fileOperation::monitor(), fvMeshTools::newMesh(), faMeshTools::newMesh(), argList::parse(), regIOobject::read(), regIOobject::readHeaderOk(), Time::readModifiedObjects(), IOobject::typeHeaderOk(), and regIOobject::writeObject().
fileModificationSkew
float fileModificationSkew static
Definition at line 288 of file IOobject.H.
Referenced by codeStream::getFunction(), argList::parse(), and dynamicCode::waitForFile().
maxFileModificationPolls
int maxFileModificationPolls static
Definition at line 291 of file IOobject.H.
Referenced by argList::parse(), and dynamicCode::waitForFile().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOobject/IOobject.H
src/OpenFOAM/db/IOobject/IOobject.C
src/OpenFOAM/db/IOobject/IOobjectI.H
src/OpenFOAM/db/IOobject/IOobjectMetaData.C
src/OpenFOAM/db/IOobject/IOobjectReadHeader.C
src/OpenFOAM/db/IOobject/IOobjectTemplates.C
src/OpenFOAM/db/IOobject/IOobjectWriteHeader.C