OpenFOAM: noiseFFT Class Reference
noiseFFT Class Reference
Performs FFT of pressure field to generate noise data.
#include <noiseFFT.H>
Public Member Functions
noiseFFT (const scalar deltaT, const label windowSize=-1)
~noiseFFT ()
void setData (scalarList &data)
void setData (const fileName &pFileName, const label skip=0)
graph pt () const
tmp< scalarField > Pf (const tmp< scalarField > &pn) const
graph meanPf (const windowModel &window) const
graph RMSmeanPf (const windowModel &window) const
graph PSDf (const windowModel &window) const
graph PSD (const graph &gPSDf) const
graph octaves (const graph &g, const labelUList &freqBandIDs) const
scalar dbToPa (const scalar db) const
tmp< scalarField > dbToPa (const tmp< scalarField > &db) const
Public Member Functions inherited from Field< scalar >
constexpr Field () noexcept
Field (const label len)
Field (const label len, const scalar &val)
Field (const label len, const Foam::zero)
Field (const Foam::one, const scalar &val)
Field (const Foam::one, scalar &&val)
Field (const Foam::one, const Foam::zero)
Field (const Field< scalar > &fld)
Field (const UList< scalar > &list)
Field (const IndirectListBase< scalar, Addr > &list)
Field (Field< scalar > &&fld)
Field (List< scalar > &&list)
Field (DynamicList< scalar, SizeMin > &&list)
Field (const UList< scalar > &mapF, const labelUList &mapAddressing)
Field (const tmp< Field< scalar > > &tmapF, const labelUList &mapAddressing)
Field (const UList< scalar > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Field (const tmp< Field< scalar > > &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Field (const UList< scalar > &mapF, const FieldMapper &map, const bool applyFlip=true)
Field (const UList< scalar > &mapF, const FieldMapper &map, const scalar &defaultValue, const bool applyFlip=true)
Field (const UList< scalar > &mapF, const FieldMapper &map, const UList< scalar > &defaultValues, const bool applyFlip=true)
Field (const tmp< Field< scalar > > &tmapF, const FieldMapper &map, const bool applyFlip=true)
Field (const tmp< Field< scalar > > &tmapF, const FieldMapper &map, const scalar &defaultValue, const bool applyFlip=true)
Field (const tmp< Field< scalar > > &tmapF, const FieldMapper &map, const UList< scalar > &defaultValues, const bool applyFlip=true)
Field (Field< scalar > &fld, bool reuse)
Field (const tmp< Field< scalar > > &tfld)
Field (Istream &is)
Field (const entry &e, const label len)
Field (const word &key, const dictionary &dict, const label len, IOobjectOption::readOption readOpt=IOobjectOption::MUST_READ)
tmp< Field< scalar > > clone () const
void assign (const entry &e, const label len)
bool assign (const word &key, const dictionary &dict, const label len, IOobjectOption::readOption readOpt=IOobjectOption::MUST_READ)
void map (const UList< scalar > &mapF, const labelUList &mapAddressing)
void map (const tmp< Field< scalar > > &tmapF, const labelUList &mapAddressing)
void map (const UList< scalar > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
void map (const tmp< Field< scalar > > &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
void map (const UList< scalar > &mapF, const FieldMapper &map, const bool applyFlip=true)
void map (const tmp< Field< scalar > > &tmapF, const FieldMapper &map, const bool applyFlip=true)
void autoMap (const FieldMapper &map, const bool applyFlip=true)
void rmap (const UList< scalar > &mapF, const labelUList &mapAddressing)
void rmap (const tmp< Field< scalar > > &tmapF, const labelUList &mapAddressing)
void rmap (const UList< scalar > &mapF, const labelUList &mapAddressing, const UList< scalar > &weights)
void rmap (const tmp< Field< scalar > > &tmapF, const labelUList &mapAddressing, const UList< scalar > &weights)
void negate ()
void normalise ()
void normalise ()
void normalise ()
void normalise ()
void normalise ()
tmp< Field< cmptType > > component (const direction) const
void replace (const direction, const UList< cmptType > &)
void replace (const direction, const tmp< Field< cmptType > > &)
void replace (const direction, const cmptType &)
void clamp_min (const scalar &lower)
void clamp_max (const scalar &upper)
void clamp_range (const scalar &lower, const scalar &upper)
void clamp_range (const MinMax< scalar > &range)
VSForm block (const label start) const
tmp< Field< scalar > > T () const
void writeEntry (const word &keyword, Ostream &os) const
SubField< scalar > slice (const label pos, label len=-1)
const SubField< scalar > slice (const label pos, label len=-1) const
SubField< scalar > slice (const labelRange &range)
const SubField< scalar > slice (const labelRange &range) const
void operator= (const Field< scalar > &)
void operator= (const tmp< Field< scalar > > &)
void operator= (const UList< scalar > &rhs)
void operator= (const SubField< scalar > &rhs)
void operator= (const IndirectListBase< scalar, Addr > &rhs)
void operator= (Field< scalar > &&rhs)
void operator= (List< scalar > &&rhs)
void operator= (DynamicList< scalar, SizeMin > &&rhs)
void operator= (const scalar &val)
void operator= (const Foam::zero)
void operator= (const VectorSpace< Form, Cmpt, nCmpt > &)
void operator= (const tmp< Field > &rhs)
void operator+= (const UList< scalar > &)
void operator+= (const tmp< Field< scalar > > &)
void operator+= (const scalar &)
void operator-= (const UList< scalar > &)
void operator-= (const tmp< Field< scalar > > &)
void operator-= (const scalar &)
void operator*= (const UList< scalar > &)
void operator*= (const tmp< Field< scalar > > &)
void operator*= (const scalar &)
void operator/= (const UList< scalar > &)
void operator/= (const tmp< Field< scalar > > &)
void operator/= (const scalar &)
Public Member Functions inherited from FieldBase
constexpr FieldBase () noexcept
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Public Member Functions inherited from List< T >
constexpr List () noexcept
List (const label len)
List (const label len, const T &val)
List (const label len, const Foam::zero)
List (const Foam::one, const T &val)
List (const Foam::one, T &&val)
List (const Foam::one, const Foam::zero)
List (const List< T > &a)
List (const UList< T > &a)
List (List< T > &a, bool reuse)
List (const UList< T > &list, const labelUList &indices)
template<unsigned N>
List (const UList< T > &list, const FixedList< label, N > &indices)
template<unsigned N>
List (const FixedList< T, N > &list)
List (const PtrList< T > &list)
List (const SLList< T > &list)
template<class Addr >
List (const IndirectListBase< T, Addr > &list)
List (std::initializer_list< T > list)
List (List< T > &&list)
template<int SizeMin>
List (DynamicList< T, SizeMin > &&list)
List (SLList< T > &&list)
List (Istream &is)
autoPtr< List< T > > clone () const
~List ()
void clear ()
void resize (const label len)
void resize (const label len, const T &val)
void resize_nocopy (const label len)
void setSize (const label n)
void setSize (const label n, const T &val)
void transfer (List< T > &list)
template<int SizeMin>
void transfer (DynamicList< T, SizeMin > &list)
T & newElmt (const label i)
template<class... Args>
T & emplace_back (Args &&... args)
void push_back (const T &val)
void push_back (T &&val)
void push_back (const UList< T > &list)
template<class Addr >
void push_back (const IndirectListBase< T, Addr > &list)
label push_uniq (const T &val)
void pop_back (label n=1)
void operator= (const UList< T > &a)
void operator= (const List< T > &list)
void operator= (const SLList< T > &list)
template<class Addr >
void operator= (const IndirectListBase< T, Addr > &list)
template<unsigned N>
void operator= (const FixedList< T, N > &list)
void operator= (std::initializer_list< T > list)
void operator= (const T &val)
void operator= (const Foam::zero)
void operator= (List< T > &&list)
template<int SizeMin>
void operator= (DynamicList< T, SizeMin > &&list)
void operator= (SLList< T > &&list)
Istream & readList (Istream &is)
void shallowCopy (const UList< T > &)=delete
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type set (const label i, bool val=true)
void append (const T &val)
void append (T &&val)
void append (const UList< T > &list)
template<class Addr >
void append (const IndirectListBase< T, Addr > &list)
label appendUniq (const T &val)
Istream & readList (Istream &is)
void resize (const label newLen)
Istream & readList (Istream &is)
Public Member Functions inherited from UList< T >
UList (const UList< T > &)=default
constexpr UList () noexcept
UList (T *__restrict__ v, const label len) noexcept
label fcIndex (const label i) const noexcept
label rcIndex (const label i) const noexcept
const T & fcValue (const label i) const
T & fcValue (const label i)
const T & rcValue (const label i) const
T & rcValue (const label i)
const T * cdata () const noexcept
T * data () noexcept
const char * cdata_bytes () const noexcept
char * data_bytes () noexcept
T & front ()
const T & front () const
T & back ()
const T & back () const
std::streamsize size_bytes () const noexcept
std::streamsize byteSize () const
void checkStart (const label start) const
void checkSize (const label size) const
void checkRange (const label start, const label len) const
void checkIndex (const label i) const
bool uniform () const
label find (const T &val, label pos=0) const
label rfind (const T &val, label pos=-1) const
bool contains (const T &val, label pos=0) const
void moveFirst (const label i)
void moveLast (const label i)
void swapFirst (const label i)
void swapLast (const label i)
void shallowCopy (const UList< T > &list)
void deepCopy (const UList< T > &list)
template<class Addr >
void deepCopy (const IndirectListBase< T, Addr > &list)
SubList< T > slice (const label pos, label len=-1)
const SubList< T > slice (const label pos, label len=-1) const
SubList< T > slice (const labelRange &range)
const SubList< T > slice (const labelRange &range) const
T & operator[] (const label i)
const T & operator[] (const label i) const
operator const Foam::List< T > & () const
void operator= (const T &val)
void operator= (const Foam::zero)
iterator begin () noexcept
iterator end () noexcept
iterator begin (const label i) noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
const_iterator begin () const noexcept
const_iterator end () const noexcept
const_iterator cbegin (const label i) const noexcept
const_iterator begin (const label i) const noexcept
reverse_iterator rbegin ()
reverse_iterator rend ()
const_reverse_iterator crbegin () const
const_reverse_iterator crend () const
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
bool empty () const noexcept
label size () const noexcept
void swap (UList< T > &list)
bool operator== (const UList< T > &a) const
bool operator!= (const UList< T > &a) const
bool operator< (const UList< T > &list) const
bool operator> (const UList< T > &a) const
bool operator<= (const UList< T > &a) const
bool operator>= (const UList< T > &a) const
Istream & readList (Istream &is)
void writeEntry (const word &keyword, Ostream &os) const
Ostream & writeList (Ostream &os, const label shortLen=0) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type test (const label i) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type get (const label i) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type unset (const label i)
T & first ()
const T & first () const
T & last ()
const T & last () const
bool found (const T &val, label pos=0) const
Istream & readList (Istream &is)
Ostream & writeList (Ostream &os, const label) const
const bool & operator[] (const label i) const
UPstream::commsStruct & operator[] (const label procID)
const UPstream::commsStruct & operator[] (const label procID) const
Foam::UPstream::commsStruct & operator[] (const label procID)
const Foam::UPstream::commsStruct & operator[] (const label procID) const
Ostream & writeList (Ostream &os, const label) const
Istream & readList (Istream &is)
Static Public Member Functions
static tmp< scalarField > frequencies (const label N, const scalar deltaT)
static tmp< scalarField > PSD (const scalarField &PSDf)
static tmp< scalarField > SPL (const scalarField &Prms2)
static void octaveBandInfo (const scalarField &f, const scalar fLower, const scalar fUpper, const scalar octave, labelList &fBandIDs, scalarField &fCentre)
Static Public Member Functions inherited from Field< scalar >
static const Field< scalar > & null ()
static autoPtr< Field< scalar > > New (Istream &is)
static tmp< Field< scalar > > NewCalculatedType (const Field< Type2 > &f)
Static Public Member Functions inherited from List< T >
static const List< T > & null ()
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
static constexpr label max_size () noexcept
Static Public Attributes
static scalar p0 = 2e-5
Static Public Attributes inherited from FieldBase
static const char *const typeName
static bool allowConstructFromLargerSize = false
Additional Inherited Members
Public Types inherited from Field< scalar >
typedef pTraits< scalar >::cmptType cmptType
typedef SubField< scalar > subField
Public Types inherited from List< T >
typedef SubList< T > subList
Public Types inherited from UList< T >
typedef T value_type
typedef T * pointer
typedef const T * const_pointer
typedef T & reference
typedef const T & const_reference
typedef T * iterator
typedef const T * const_iterator
typedef label size_type
typedef label difference_type
typedef std::reverse_iterator< iterator > reverse_iterator
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
Protected Member Functions inherited from UList< T >
void setAddressableSize (const label n) noexcept
void size (const label n)
void writeEntry (Ostream &os) const
labelRange validateRange (const labelRange &requestedRange) const
UList< T > & operator= (const UList< T > &)=delete
void writeEntry (Ostream &os) const
void writeEntry (Ostream &os) const
Detailed Description
Performs FFT of pressure field to generate noise data.
General functionality:
Pf: fft of the pressure data
meanPf: multi-window mean fft
RMSmeanPf: multi-window RMS mean fft
PSDf: multi-window power spectral density (PSD) in frequency domain
PSD: power spectral density in dB/Hz
SPL: sound pressure level in dB
Octave-based data:
PSD spectrum
SPL spectrum
Source files
noiseFFT.H
noiseFFT.C
See also
windowModel.H
Definition at line 65 of file noiseFFT.H.
Constructor & Destructor Documentation
noiseFFT()
noiseFFT (const scalar deltaT, const label windowSize = -1)
Definition at line 137 of file noiseFFT.C.
~noiseFFT()
~noiseFFT ()
Definition at line 169 of file noiseFFT.C.
Member Function Documentation
frequencies()
Foam::tmp< Foam::scalarField > frequencies (const label N, const scalar deltaT) static
Definition at line 36 of file noiseFFT.C.
References f(), forAll, N(), tmp< T >::New(), and Foam::Zero.
PSD() [1/2]
Foam::tmp< Foam::scalarField > PSD (const scalarField & PSDf) static
Definition at line 55 of file noiseFFT.C.
References Foam::log10(), p0, and Foam::sqr().
SPL()
Foam::tmp< Foam::scalarField > SPL (const scalarField & Prms2) static
Definition at line 61 of file noiseFFT.C.
References Foam::log10(), p0, and Foam::sqr().
octaveBandInfo()
void octaveBandInfo (const scalarField & f, const scalar fLower, const scalar fUpper, const scalar octave, labelList & fBandIDs, scalarField & fCentre) static
Definition at line 67 of file noiseFFT.C.
References PtrList< T >::append(), f(), forAll, noiseFFT::octaveBandInfo(), Foam::pow(), UPtrList< T >::size(), UList< T >::size(), and PtrList< T >::transfer().
Referenced by noiseFFT::octaveBandInfo().
setData() [1/2]
void setData (scalarList & data)
Definition at line 182 of file noiseFFT.C.
References Foam::average(), and p.
setData() [2/2]
void setData (const fileName & pFileName, const label skip = 0)
Definition at line 191 of file noiseFFT.C.
References Foam::average(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, p, UPtrList< T >::size(), and T0.
pt()
Foam::graph pt () const
Definition at line 249 of file noiseFFT.C.
References forAll.
Pf()
Foam::tmp< Foam::scalarField > Pf (const tmp< scalarField > & pn) const
Definition at line 268 of file noiseFFT.C.
References Foam::abort(), PtrList< T >::clear(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::mag(), n, tmp< T >::New(), fft::realTransform1D(), UPtrList< T >::size(), and Foam::sqrt().
meanPf()
Foam::graph meanPf (const windowModel & window) const
Definition at line 316 of file noiseFFT.C.
References windowModel::apply(), f(), forAll, N(), windowModel::nSamples(), windowModel::nWindow(), UList< T >::size(), and Foam::Zero.
RMSmeanPf()
Foam::graph RMSmeanPf (const windowModel & window) const
Definition at line 348 of file noiseFFT.C.
References windowModel::apply(), f(), forAll, N(), windowModel::nSamples(), windowModel::nWindow(), UPtrList< T >::size(), Foam::sqr(), Foam::sqrt(), and Foam::Zero.
PSDf()
Foam::graph PSDf (const windowModel & window) const
Definition at line 379 of file noiseFFT.C.
References windowModel::apply(), Foam::average(), Foam::endl(), f(), UPtrList< T >::first(), forAll, UPtrList< T >::last(), N(), windowModel::nSamples(), windowModel::nWindow(), Foam::Pout, UPtrList< T >::size(), Foam::sqr(), and Foam::Zero.
PSD() [2/2]
Foam::graph PSD (const graph & gPSDf) const
Definition at line 424 of file noiseFFT.C.
References Foam::log10(), p0, and Foam::sqr().
octaves()
Foam::graph octaves (const graph & g, const labelUList & freqBandIDs) const
Definition at line 437 of file noiseFFT.C.
References Foam::endl(), f(), g, UPtrList< T >::size(), WarningInFunction, and Foam::Zero.
dbToPa() [1/2]
Foam::scalar dbToPa (const scalar db) const
Definition at line 494 of file noiseFFT.C.
References p0, and Foam::pow().
dbToPa() [2/2]
Foam::tmp< Foam::scalarField > dbToPa (const tmp< scalarField > & db) const
Definition at line 500 of file noiseFFT.C.
References p0, and Foam::pow().
Member Data Documentation
p0
Foam::scalar p0 = 2e-5 static
Definition at line 105 of file noiseFFT.H.
The documentation for this class was generated from the following files:
src/randomProcesses/noise/noiseFFT/noiseFFT.H
src/randomProcesses/noise/noiseFFT/noiseFFT.C