OpenFOAM: fft Class Reference
fft Class Reference
Fast fourier transform using the fftw library.
#include <fft.H>
Public Types
enum transformDirection { FORWARD_TRANSFORM = -1 , REVERSE_TRANSFORM = 1 }
Static Public Member Functions
static void fftRenumberRecurse (List< complex > &data, List< complex > &renumData, const UList< int > &nn, label nnprod, label ii, label l1, label l2)
static void fftRenumber (List< complex > &data, const UList< int > &nn)
static tmp< complexField > realTransform1D (const scalarField &field)
static tmp< complexField > realTransform1D (const tmp< scalarField > &field)
static void transform (complexField &field, const UList< int > &nn, transformDirection fftDirection)
static tmp< complexField > forwardTransform (const tmp< complexField > &field, const UList< int > &nn)
static tmp< complexField > reverseTransform (const tmp< complexField > &field, const UList< int > &nn)
static tmp< complexVectorField > forwardTransform (const tmp< complexVectorField > &field, const UList< int > &nn)
static tmp< complexVectorField > reverseTransform (const tmp< complexVectorField > &field, const UList< int > &nn)
Detailed Description
Fast fourier transform using the fftw library.
The complex transform field is returned in the field supplied. The direction of transform is supplied as an argument (-1 = forward, 1 = reverse). The dimensionality and organisation of the array of values in space is supplied in the nn indexing array.
Note
The fftw library uses int only (no longs) for its dimensionality.
Source files
fft.H
fft.C
Definition at line 51 of file fft.H.
Member Enumeration Documentation
transformDirection
enum transformDirection
Enumerator
FORWARD_TRANSFORM
The sign -1 = FFTW_FORWARD.
REVERSE_TRANSFORM
The sign +1 = FFTW_BACKWARD.
Definition at line 56 of file fft.H.
Member Function Documentation
fftRenumberRecurse()
void fftRenumberRecurse (List< complex > & data, List< complex > & renumData, const UList< int > & nn, label nnprod, label ii, label l1, label l2) static
Definition at line 27 of file fft.C.
References fft::fftRenumberRecurse(), and UPtrList< T >::size().
Referenced by fft::fftRenumberRecurse().
fftRenumber()
void fftRenumber (List< complex > & data, const UList< int > & nn) static
Definition at line 87 of file fft.C.
References forAll.
realTransform1D() [1/2]
Foam::tmp< Foam::complexField > realTransform1D (const scalarField & field) static
Definition at line 113 of file fft.C.
References field(), n, tmp< T >::New(), and UPtrList< T >::size().
Referenced by noiseModel::Pf(), and noiseFFT::Pf().
realTransform1D() [2/2]
Foam::tmp< Foam::complexField > realTransform1D (const tmp< scalarField > & field) static
Definition at line 160 of file fft.C.
References PtrList< T >::clear().
transform()
void transform (complexField & field, const UList< int > & nn, transformDirection fftDirection) static
Definition at line 171 of file fft.C.
References UPtrList< T >::begin(), field(), forAll, N(), and UPtrList< T >::size().
forwardTransform() [1/2]
Foam::tmp< Foam::complexField > forwardTransform (const tmp< complexField > & field, const UList< int > & nn) static
Definition at line 235 of file fft.C.
References PtrList< T >::clear(), tmp< T >::New(), and Foam::transform().
Referenced by energySpectrum::calcAndWriteSpectrum(), and Foam::calcEk().
reverseTransform() [1/2]
Foam::tmp< Foam::complexField > reverseTransform (const tmp< complexField > & field, const UList< int > & nn) static
Definition at line 251 of file fft.C.
References PtrList< T >::clear(), tmp< T >::New(), and Foam::transform().
Referenced by turbGen::U().
forwardTransform() [2/2]
Foam::tmp< Foam::complexVectorField > forwardTransform (const tmp< complexVectorField > & field, const UList< int > & nn) static
Definition at line 267 of file fft.C.
References PtrList< T >::clear(), Foam::component(), VectorSpace< Form, Cmpt, Ncmpts >::nComponents, and tmp< T >::New().
reverseTransform() [2/2]
Foam::tmp< Foam::complexVectorField > reverseTransform (const tmp< complexVectorField > & field, const UList< int > & nn) static
Definition at line 290 of file fft.C.
References PtrList< T >::clear(), Foam::component(), VectorSpace< Form, Cmpt, Ncmpts >::nComponents, and tmp< T >::New().
The documentation for this class was generated from the following files:
src/randomProcesses/fft/fft.H
src/randomProcesses/fft/fft.C