OpenFOAM: stepUpdate Class Reference
stepUpdate Class Reference abstract
Abstract base class for step update methods used in line search.
#include <stepUpdate.H>
Public Member Functions
TypeName ("stepUpdate")
declareRunTimeSelectionTable (autoPtr, stepUpdate, dictionary,(const dictionary &dict),(dict))
stepUpdate (const dictionary &dict)
virtual ~stepUpdate ()=default
virtual void updateStep (scalar &step)=0
virtual void setDeriv (const scalar deriv)
virtual void setNewMeritValue (const scalar value)
virtual void setOldMeritValue (const scalar value)
Static Public Member Functions
static autoPtr< stepUpdate > New (const dictionary &dict)
Protected Member Functions
const dictionary & coeffsDict ()
Protected Attributes
const dictionary dict_
Detailed Description
Abstract base class for step update methods used in line search.
Source files
stepUpdate.H
stepUpdate.C
Definition at line 50 of file stepUpdate.H.
Constructor & Destructor Documentation
stepUpdate()
stepUpdate (const dictionary & dict)
Definition at line 44 of file stepUpdate.C.
~stepUpdate()
virtual ~stepUpdate () virtual default
Member Function Documentation
coeffsDict()
const Foam::dictionary & coeffsDict () protected
Definition at line 36 of file stepUpdate.C.
References stepUpdate::dict_, and Foam::type().
TypeName()
TypeName ("stepUpdate")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , stepUpdate , dictionary , (const dictionary &dict) , (dict))
New()
Foam::autoPtr< Foam::stepUpdate > New (const dictionary & dict) static
Definition at line 52 of file stepUpdate.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::getOrDefault(), Foam::Info, and Foam::type().
updateStep()
virtual void updateStep (scalar & step) pure virtual
Implemented in bisection, and quadratic.
setDeriv()
void setDeriv (const scalar deriv) virtual
Reimplemented in quadratic.
Definition at line 78 of file stepUpdate.C.
setNewMeritValue()
void setNewMeritValue (const scalar value) virtual
Reimplemented in quadratic.
Definition at line 84 of file stepUpdate.C.
setOldMeritValue()
void setOldMeritValue (const scalar value) virtual
Reimplemented in quadratic.
Definition at line 90 of file stepUpdate.C.
Member Data Documentation
dict_
const dictionary dict_ protected
Definition at line 56 of file stepUpdate.H.
Referenced by stepUpdate::coeffsDict().
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/optimisation/lineSearch/stepUpdate/stepUpdate/stepUpdate.H
src/optimisation/adjointOptimisation/adjoint/optimisation/lineSearch/stepUpdate/stepUpdate/stepUpdate.C