OpenFOAM: DispersionRASModel< CloudType > Class Template Reference
DispersionRASModel< CloudType > Class Template Reference abstract
Base class for particle dispersion models based on RAS turbulence.
#include <DispersionRASModel.H>
Public Member Functions
TypeName ("dispersionRASModel")
DispersionRASModel (const dictionary &dict, CloudType &owner)
DispersionRASModel (const DispersionRASModel< CloudType > &dm)
virtual autoPtr< DispersionModel< CloudType > > clone () const =0
virtual ~DispersionRASModel ()
virtual vector update (const scalar dt, const label celli, const vector &U, const vector &Uc, vector &UTurb, scalar &tTurb)=0
virtual void cacheFields (const bool store)
virtual void write (Ostream &os) const
Public Member Functions inherited from DispersionModel< CloudType >
TypeName ("dispersionModel")
declareRunTimeSelectionTable (autoPtr, DispersionModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
DispersionModel (CloudType &owner)
DispersionModel (const dictionary &dict, CloudType &owner, const word &type)
DispersionModel (const DispersionModel< CloudType > &dm)
virtual ~DispersionModel ()
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
virtual ~CloudSubModelBase ()=default
const CloudType & owner () const
virtual bool writeTime () const
virtual fileName localPath () const
CloudType & owner ()
virtual void info ()
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
subModelBase (const subModelBase &smb)
virtual ~subModelBase ()=default
const word & modelName () const
const dictionary & dict () const
const word & baseName () const
const word & modelType () const
const dictionary & coeffDict () const
const dictionary & properties () const
virtual bool defaultCoeffs (const bool printMsg) const
virtual bool active () const
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
bool getModelDict (const word &entryName, dictionary &dict) const
template<class Type >
bool getModelProperty (const word &entryName, Type &value) const
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Protected Member Functions
tmp< volScalarField > kModel () const
tmp< volScalarField > epsilonModel () const
Protected Member Functions inherited from subModelBase
bool inLine () const
Protected Attributes
const volScalarField * kPtr_
const volScalarField * epsilonPtr_
bool ownK_
bool ownEpsilon_
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Protected Attributes inherited from subModelBase
const word modelName_
dictionary & properties_
const dictionary dict_
const word baseName_
const word modelType_
const dictionary coeffDict_
Additional Inherited Members
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Static Public Member Functions inherited from DispersionModel< CloudType >
static autoPtr< DispersionModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Public Attributes inherited from subModelBase
bool log
Detailed Description
template<class CloudType>
class Foam::DispersionRASModel< CloudType >
Base class for particle dispersion models based on RAS turbulence.
Definition at line 43 of file DispersionRASModel.H.
Constructor & Destructor Documentation
DispersionRASModel() [1/2]
template<class CloudType > DispersionRASModel (const dictionary & dict, CloudType & owner)
Definition at line 86 of file DispersionRASModel.C.
DispersionRASModel() [2/2]
template<class CloudType > DispersionRASModel (const DispersionRASModel< CloudType > & dm)
Definition at line 101 of file DispersionRASModel.C.
~DispersionRASModel()
template<class CloudType > ~DispersionRASModel () virtual
Definition at line 120 of file DispersionRASModel.C.
Member Function Documentation
kModel()
template<class CloudType > Foam::tmp< Foam::volScalarField > kModel () const protected
Definition at line 29 of file DispersionRASModel.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, objectRegistry::findObject(), IOobject::groupName(), turbulenceModel::k(), Foam::nl, turbulenceModel::propertiesName, PtrList< T >::PtrList(), HashTable< T, Key, Hash >::sortedToc(), turb, and U.
epsilonModel()
template<class CloudType > Foam::tmp< Foam::volScalarField > epsilonModel () const protected
Definition at line 57 of file DispersionRASModel.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, objectRegistry::findObject(), IOobject::groupName(), Foam::nl, turbulenceModel::propertiesName, HashTable< T, Key, Hash >::sortedToc(), turb, and U.
TypeName()
template<class CloudType > TypeName ("dispersionRASModel")
clone()
template<class CloudType > virtual autoPtr< DispersionModel< CloudType > > clone () const pure virtual
Implements DispersionModel< CloudType >.
Implemented in GradientDispersionRAS< CloudType >, and StochasticDispersionRAS< CloudType >.
update()
template<class CloudType > virtual vector update (const scalar dt, const label celli, const vector & U, const vector & Uc, vector & UTurb, scalar & tTurb) pure virtual
Implements DispersionModel< CloudType >.
Implemented in GradientDispersionRAS< CloudType >, and StochasticDispersionRAS< CloudType >.
cacheFields()
template<class CloudType > void cacheFields (const bool store) virtual
Reimplemented from subModelBase.
Reimplemented in GradientDispersionRAS< CloudType >.
Definition at line 129 of file DispersionRASModel.C.
References Foam::deleteDemandDrivenData().
Referenced by GradientDispersionRAS< CloudType >::cacheFields().
write()
template<class CloudType > void write (Ostream & os) const virtual
Reimplemented from CloudSubModelBase< CloudType >.
Definition at line 176 of file DispersionRASModel.C.
References os(), CloudSubModelBase< CloudType >::write(), and Ostream::writeEntry().
Member Data Documentation
kPtr_
template<class CloudType > const volScalarField* kPtr_ protected
Definition at line 54 of file DispersionRASModel.H.
epsilonPtr_
template<class CloudType > const volScalarField* epsilonPtr_ protected
Definition at line 57 of file DispersionRASModel.H.
ownK_
template<class CloudType > bool ownK_ mutable protected
Definition at line 60 of file DispersionRASModel.H.
ownEpsilon_
template<class CloudType > bool ownEpsilon_ mutable protected
Definition at line 63 of file DispersionRASModel.H.
The documentation for this class was generated from the following files:
src/lagrangian/turbulence/submodels/Kinematic/DispersionModel/DispersionRASModel/DispersionRASModel.H
src/lagrangian/turbulence/submodels/Kinematic/DispersionModel/DispersionRASModel/DispersionRASModel.C