OpenFOAM: pyrMatcher Class Reference
pyrMatcher Class Reference
A cellMatcher for pyr cells (cellModel::PYR)
#include <pyrMatcher.H>
Public Member Functions
pyrMatcher ()
~pyrMatcher ()=default
virtual label nVertPerCell () const
virtual label nFacePerCell () const
virtual label nMaxVertPerFace () const
virtual label faceHashValue () const
virtual bool faceSizeMatch (const faceList &, const labelList &) const
virtual bool matchShape (const bool checkOnly, const faceList &faces, const labelList &faceOwner, const label celli, const labelList &myFaces)
virtual bool isA (const faceList &faces)
virtual bool isA (const primitiveMesh &mesh, const label celli)
virtual bool matches (const primitiveMesh &mesh, const label celli, cellShape &shape)
Public Member Functions inherited from cellMatcher
cellMatcher (const label vertPerCell, const label facePerCell, const label maxVertPerFace, const word &cellModelName)
virtual ~cellMatcher ()=default
const Map< label > & localPoint () const
const faceList & localFaces () const
const labelList & faceSize () const
const labelList & pointMap () const
const labelList & faceMap () const
const labelList & edgeFaces () const
const labelListList & pointFaceIndex () const
const labelList & vertLabels () const
const labelList & faceLabels () const
const cellModel & model () const
void write (Ostream &os) const
Static Public Member Functions
static bool test (const UList< face > &faces)
static bool test (const primitiveMesh &mesh, const label celli)
Additional Inherited Members
Protected Member Functions inherited from cellMatcher
label calcLocalFaces (const faceList &faces, const labelList &myFaces)
void calcEdgeAddressing (const label numVert)
void calcPointFaceIndex ()
label otherFace (const label numVert, const label v0, const label v1, const label localFacei) const
cellMatcher (const cellMatcher &)=delete
cellMatcher & operator= (const cellMatcher &)=delete
Static Protected Member Functions inherited from cellMatcher
static label edgeKey (const label numVert, const label v0, const label v1)
static label nextVert (const label, const label, const bool)
Protected Attributes inherited from cellMatcher
Map< label > localPoint_
faceList localFaces_
labelList faceSize_
labelList pointMap_
labelList faceMap_
labelList edgeFaces_
labelListList pointFaceIndex_
labelList vertLabels_
labelList faceLabels_
const word cellModelName_
const cellModel * cellModelPtr_
Detailed Description
A cellMatcher for pyr cells (cellModel::PYR)
See also
cellMatcher, cellModel
Source files
pyrMatcher.H
pyrMatcher.C
Definition at line 50 of file pyrMatcher.H.
Constructor & Destructor Documentation
pyrMatcher()
pyrMatcher ()
Definition at line 120 of file pyrMatcher.C.
~pyrMatcher()
~pyrMatcher () default
Member Function Documentation
test() [1/2]
bool test (const UList< face > & faces) static
Definition at line 107 of file pyrMatcher.C.
References Foam::checkFaceSizeMatch().
Referenced by pyrMatcher::isA(), and pyrMatcher::isA().
test() [2/2]
bool test (const primitiveMesh & mesh, const label celli) static
Definition at line 112 of file pyrMatcher.C.
References primitiveMesh::cells(), Foam::checkFaceSizeMatch(), polyMesh::faces(), and mesh.
nVertPerCell()
virtual label nVertPerCell () const inline virtual
Implements cellMatcher.
Definition at line 96 of file pyrMatcher.H.
nFacePerCell()
virtual label nFacePerCell () const inline virtual
Implements cellMatcher.
Definition at line 101 of file pyrMatcher.H.
nMaxVertPerFace()
virtual label nMaxVertPerFace () const inline virtual
Implements cellMatcher.
Definition at line 106 of file pyrMatcher.H.
faceHashValue()
Foam::label faceHashValue () const virtual
Implements cellMatcher.
Definition at line 290 of file pyrMatcher.C.
faceSizeMatch()
bool faceSizeMatch (const faceList & meshFaces, const labelList & cellFaces) const virtual
Implements cellMatcher.
Definition at line 296 of file pyrMatcher.C.
References Foam::checkFaceSizeMatch().
matchShape()
bool matchShape (const bool checkOnly, const faceList & faces, const labelList & faceOwner, const label celli, const labelList & myFaces) virtual
Implements cellMatcher.
Definition at line 134 of file pyrMatcher.C.
References forAll.
isA() [1/2]
virtual bool isA (const faceList & faces) inline virtual
Implements cellMatcher.
Definition at line 124 of file pyrMatcher.H.
References pyrMatcher::test().
isA() [2/2]
virtual bool isA (const primitiveMesh & mesh, const label celli) inline virtual
Implements cellMatcher.
Definition at line 129 of file pyrMatcher.H.
References mesh, and pyrMatcher::test().
matches()
bool matches (const primitiveMesh & mesh, const label celli, cellShape & shape) virtual
Implements cellMatcher.
Definition at line 306 of file pyrMatcher.C.
References primitiveMesh::cells(), polyMesh::faceOwner(), polyMesh::faces(), mesh, and cellShape::reset().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/meshShapes/cellMatcher/pyrMatcher.H
src/OpenFOAM/meshes/meshShapes/cellMatcher/pyrMatcher.C