OpenFOAM: Spiegler Class Reference
Spiegler Class Reference
A model for Leidenfrost effects based on Spiegler et al. (1963) for boiling flows.
#include <Spiegler.H>
Public Member Functions
TypeName ("Spiegler")
Spiegler (const dictionary &dict)
virtual ~Spiegler ()=default
virtual tmp< scalarField > TLeid (const phaseModel &liquid, const phaseModel &vapor, const label patchi, const scalarField &Tl, const scalarField &Tsatw, const scalarField &L) const
virtual void write (Ostream &os) const
Public Member Functions inherited from LeidenfrostModel
TypeName ("LeidenfrostModel")
declareRunTimeSelectionTable (autoPtr, LeidenfrostModel, dictionary,(const dictionary &dict),(dict))
LeidenfrostModel ()=default
virtual ~LeidenfrostModel ()=default
Additional Inherited Members
Static Public Member Functions inherited from LeidenfrostModel
static autoPtr< LeidenfrostModel > New (const dictionary &dict)
Detailed Description
A model for Leidenfrost effects based on Spiegler et al. (1963) for boiling flows.
Reference:
    Spiegler, P., Hopenfeld, J., Silberberg, M.,
    Bumpus Jr, C. F., & Norman, A. (1963).
    Onset of stable film boiling and the foam limit.
    International Journal of Heat and Mass Transfer, 6(11), 987-989.
    DOI:10.1016/0017-9310(63)90053-X
Usage
Example of the model specification:
LeidenfrostModel
{
    // Mandatory entries
    type            Spiegler;
    // Optional entries
    Tcrit            <scalar>;
}
where the entries mean:
Property Description Type Reqd Deflt
type Type name: Spiegler word yes -
Tcrit Critical temperature [K] scalar no 374.0
Source files
Spiegler.H
Spiegler.C
Definition at line 98 of file Spiegler.H.
Constructor & Destructor Documentation
Spiegler()
Spiegler (const dictionary & dict)
Definition at line 47 of file Spiegler.C.
~Spiegler()
virtual ~Spiegler () virtual default
Member Function Documentation
TypeName()
TypeName ("Spiegler")
TLeid()
Foam::tmp< Foam::scalarField > TLeid (const phaseModel & liquid, const phaseModel & vapor, const label patchi, const scalarField & Tl, const scalarField & Tsatw, const scalarField & L) const virtual
Implements LeidenfrostModel.
Definition at line 60 of file Spiegler.C.
References tmp< T >::New().
write()
void write (Ostream & os) const virtual
Reimplemented from LeidenfrostModel.
Definition at line 78 of file Spiegler.C.
References os(), and LeidenfrostModel::write().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/wallBoilingSubModels/LeidenfrostModels/Spiegler/Spiegler.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/wallBoilingSubModels/LeidenfrostModels/Spiegler/Spiegler.C