OpenFOAM: lnGradScheme< Type > Class Template Reference
lnGradScheme< Type > Class Template Reference abstract
Abstract base class for lnGrad schemes.
#include <lnGradScheme.H>
Public Member Functions
declareRunTimeSelectionTable (tmp, lnGradScheme, Mesh,(const faMesh &mesh, Istream &schemeData),(mesh, schemeData))
lnGradScheme (const faMesh &mesh)
virtual ~lnGradScheme ()
const faMesh & mesh () const
virtual tmp< edgeScalarField > deltaCoeffs (const GeometricField< Type, faPatchField, areaMesh > &) const =0
virtual bool corrected () const
virtual tmp< GeometricField< Type, faePatchField, edgeMesh > > correction (const GeometricField< Type, faPatchField, areaMesh > &) const
virtual tmp< GeometricField< Type, faePatchField, edgeMesh > > lnGrad (const GeometricField< Type, faPatchField, areaMesh > &) const
tmp< GeometricField< Type, faePatchField, edgeMesh > > lnGrad (const tmp< GeometricField< Type, faPatchField, areaMesh > > &) const
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Static Public Member Functions
static tmp< lnGradScheme< Type > > New (const faMesh &mesh, Istream &schemeData)
static tmp< GeometricField< Type, faePatchField, edgeMesh > > lnGrad (const GeometricField< Type, faPatchField, areaMesh > &, const tmp< edgeScalarField > &, const word &snGradName="lnGrad")
Detailed Description
template<class Type>
class Foam::fa::lnGradScheme< Type >
Abstract base class for lnGrad schemes.
Source files
lnGradScheme.H
lnGradScheme.C
Definition at line 58 of file lnGradScheme.H.
Constructor & Destructor Documentation
lnGradScheme()
template<class Type > lnGradScheme (const faMesh & mesh) inline
Definition at line 91 of file lnGradScheme.H.
~lnGradScheme()
template<class Type > ~lnGradScheme () virtual
Definition at line 85 of file lnGradScheme.C.
Member Function Documentation
declareRunTimeSelectionTable()
template<class Type > declareRunTimeSelectionTable (tmp , lnGradScheme< Type > , Mesh , (const faMesh &mesh, Istream &schemeData) , (mesh, schemeData))
New()
template<class Type > tmp< lnGradScheme< Type > > New (const faMesh & mesh, Istream & schemeData) static
Definition at line 41 of file lnGradScheme.C.
References Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, FatalIOErrorInLookup, InfoInFunction, mesh, and Foam::nl.
Referenced by laplacianScheme< Type >::laplacianScheme(), and Foam::fac::lnGrad().
mesh()
template<class Type > const faMesh & mesh () const inline
Definition at line 114 of file lnGradScheme.H.
Referenced by correctedLnGrad< Type >::corrected(), limitedLnGrad< Type >::corrected(), correctedLnGrad< Type >::deltaCoeffs(), fourthLnGrad< Type >::deltaCoeffs(), limitedLnGrad< Type >::deltaCoeffs(), and uncorrectedLnGrad< Type >::deltaCoeffs().
lnGrad() [1/3]
template<class Type > tmp< GeometricField< Type, faePatchField, edgeMesh > > lnGrad (const GeometricField< Type, faPatchField, areaMesh > & vf, const tmp< edgeScalarField > & tdeltaCoeffs, const word & snGradName = "lnGrad") static
Definition at line 93 of file lnGradScheme.C.
References forAll, mesh, IOobjectOption::NO_READ, and IOobjectOption::NO_WRITE.
deltaCoeffs()
template<class Type > virtual tmp< edgeScalarField > deltaCoeffs (const GeometricField< Type, faPatchField, areaMesh > &) const pure virtual
Implemented in correctedLnGrad< Type >, fourthLnGrad< Type >, limitedLnGrad< Type >, and uncorrectedLnGrad< Type >.
corrected()
template<class Type > virtual bool corrected () const inline virtual
Reimplemented in correctedLnGrad< Type >, fourthLnGrad< Type >, limitedLnGrad< Type >, and uncorrectedLnGrad< Type >.
Definition at line 136 of file lnGradScheme.H.
correction()
template<class Type > virtual tmp< GeometricField< Type, faePatchField, edgeMesh > > correction (const GeometricField< Type, faPatchField, areaMesh > &) const inline virtual
Reimplemented in correctedLnGrad< Type >, fourthLnGrad< Type >, limitedLnGrad< Type >, and uncorrectedLnGrad< Type >.
Definition at line 144 of file lnGradScheme.H.
lnGrad() [2/3]
template<class Type > tmp< GeometricField< Type, faePatchField, edgeMesh > > lnGrad (const GeometricField< Type, faPatchField, areaMesh > & vf) const virtual
Definition at line 147 of file lnGradScheme.C.
References Foam::correction().
lnGrad() [3/3]
template<class Type > tmp< GeometricField< Type, faePatchField, edgeMesh > > lnGrad (const tmp< GeometricField< Type, faPatchField, areaMesh > > & tvf) const
Definition at line 166 of file lnGradScheme.C.
References PtrList< T >::clear().
The documentation for this class was generated from the following files:
src/finiteArea/finiteArea/lnGradSchemes/lnGradScheme/lnGradScheme.H
src/finiteArea/finiteArea/lnGradSchemes/lnGradScheme/lnGradScheme.C