OpenFOAM: ThermoReynoldsNumber< CloudType > Class Template Reference
ThermoReynoldsNumber< CloudType > Class Template Reference
Lagrangian particle models » Submodels » Function objects
Calculates and writes particle Reynolds number field on the cloud. The normalisation factors are calculated with thermal effects.
#include <ThermoReynoldsNumber.H>
Public Member Functions
TypeName ("ReynoldsNumber")
void operator= (const ThermoReynoldsNumber< CloudType > &)=delete
ThermoReynoldsNumber (const dictionary &dict, CloudType &owner, const word &modelName)
ThermoReynoldsNumber (const ThermoReynoldsNumber< CloudType > &vf)
virtual autoPtr< CloudFunctionObject< CloudType > > clone () const
virtual ~ThermoReynoldsNumber ()=default
virtual void postEvolve (const typename parcelType::trackingData &td)
Public Member Functions inherited from CloudFunctionObject< CloudType >
TypeName ("cloudFunctionObject")
declareRunTimeSelectionTable (autoPtr, CloudFunctionObject, dictionary,(const dictionary &dict, CloudType &owner, const word &modelName),(dict, owner, modelName))
CloudFunctionObject (CloudType &owner)
CloudFunctionObject (const dictionary &dict, CloudType &owner, const word &objectType, const word &modelName)
CloudFunctionObject (const CloudFunctionObject< CloudType > &ppm)
virtual ~CloudFunctionObject ()=default
virtual void preEvolve (const typename parcelType::trackingData &td)
virtual void postMove (parcelType &p, const scalar dt, const point &position0, bool &keepParticle)
virtual void postPatch (const parcelType &p, const polyPatch &pp, bool &keepParticle)
virtual void postFace (const parcelType &p, bool &keepParticle)
const fileName & outputDir () const
fileName writeTimeDir () const
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
virtual ~CloudSubModelBase ()=default
const CloudType & owner () const
virtual bool writeTime () const
virtual fileName localPath () const
CloudType & owner ()
virtual void info ()
virtual void write (Ostream &os) const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
subModelBase (const subModelBase &smb)
virtual ~subModelBase ()=default
const word & modelName () const
const dictionary & dict () const
const word & baseName () const
const word & modelType () const
const dictionary & coeffDict () const
const dictionary & properties () const
virtual bool defaultCoeffs (const bool printMsg) const
virtual bool active () const
virtual void cacheFields (const bool store)
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
bool getModelDict (const word &entryName, dictionary &dict) const
template<class Type >
bool getModelProperty (const word &entryName, Type &value) const
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Additional Inherited Members
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Static Public Member Functions inherited from CloudFunctionObject< CloudType >
static autoPtr< CloudFunctionObject< CloudType > > New (const dictionary &dict, CloudType &owner, const word &objectType, const word &modelName)
Public Attributes inherited from subModelBase
bool log
Protected Member Functions inherited from subModelBase
bool inLine () const
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Protected Attributes inherited from subModelBase
const word modelName_
dictionary & properties_
const dictionary dict_
const word baseName_
const word modelType_
const dictionary coeffDict_
Detailed Description
template<class CloudType>
class Foam::ThermoReynoldsNumber< CloudType >
Calculates and writes particle Reynolds number field on the cloud. The normalisation factors are calculated with thermal effects.
= Particle Reynolds number
= Particle diameter
= Density of carrier in the film surrounding particle
= Dynamic viscosity of carrier in the film surrounding particle
= Relative velocity between particle and carrier
Operands:
Operand Type Location
input - -
output file - -
output field scalarField <time>/lagrangian/<cloud>/Re
Usage
Minimal example by using constant/<CloudProperties>:
cloudFunctions
{
    ThermoReynoldsNumber1
    {
        // Mandatory entries
        type             ReynoldsNumber;
    }
}
where the entries mean:
Property Description Type Reqd Deflt
type Type name: ReynoldsNumber word yes -
Note
Normalisation factors rhoc and muc are based on temperature dependent values calculated inside the film surrounding the particle rather than freestream values; therefore, the thermo ReynoldsNumber should not be expected to operate with kinematic (non-thermo) applications.
See also
Foam::KinematicReynoldsNumber
Source files
ThermoReynoldsNumber.H
ThermoReynoldsNumber.C
Definition at line 148 of file ThermoReynoldsNumber.H.
Constructor & Destructor Documentation
ThermoReynoldsNumber() [1/2]
template<class CloudType > ThermoReynoldsNumber (const dictionary & dict, CloudType & owner, const word & modelName)
Definition at line 27 of file ThermoReynoldsNumber.C.
ThermoReynoldsNumber() [2/2]
template<class CloudType > ThermoReynoldsNumber (const ThermoReynoldsNumber< CloudType > & vf)
Definition at line 39 of file ThermoReynoldsNumber.C.
~ThermoReynoldsNumber()
template<class CloudType > virtual ~ThermoReynoldsNumber () virtual default
Member Function Documentation
TypeName()
template<class CloudType > TypeName ("ReynoldsNumber")
operator=()
template<class CloudType > void operator= (const ThermoReynoldsNumber< CloudType > &) delete
clone()
template<class CloudType > virtual autoPtr< CloudFunctionObject< CloudType > > clone () const inline virtual
Reimplemented from CloudFunctionObject< CloudType >.
Definition at line 186 of file ThermoReynoldsNumber.H.
postEvolve()
template<class CloudType > void postEvolve (const typename parcelType::trackingData & td) virtual
Reimplemented from CloudFunctionObject< CloudType >.
Definition at line 51 of file ThermoReynoldsNumber.C.
References forAllConstIters, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, p, Pr(), Foam::Re(), IOobjectOption::REGISTER, List< T >::resize(), Foam::returnReduceOr(), UPtrList< T >::size(), and GeometricField< Type, PatchField, GeoMesh >::T().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/CloudFunctionObjects/ThermoReynoldsNumber/ThermoReynoldsNumber.H
src/lagrangian/intermediate/submodels/CloudFunctionObjects/ThermoReynoldsNumber/ThermoReynoldsNumber.C