OpenFOAM: systemCall Class Reference
systemCall Class Reference
FunctionObjects » Utility function objects
Executes system calls, entered in the form of string lists.
#include <systemCall.H>
Public Member Functions
TypeName ("systemCall")
systemCall (const word &name, const Time &runTime, const dictionary &dict)
virtual ~systemCall ()=default
virtual bool read (const dictionary &dict)
virtual bool execute ()
virtual bool write ()
virtual bool end ()
Public Member Functions inherited from functionObject
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name, const bool withNamePrefix=defaultUseNamePrefix)
autoPtr< functionObject > clone () const
virtual ~functionObject ()=default
virtual const word & type () const =0
const word & name () const noexcept
bool useNamePrefix () const noexcept
bool useNamePrefix (bool on) noexcept
virtual bool execute (const label subIndex)
virtual bool adjustTimeStep ()
virtual bool filesModified () const
virtual void updateMesh (const mapPolyMesh &mpm)
virtual void movePoints (const polyMesh &mesh)
Protected Member Functions
label dispatch (const stringList &calls)
systemCall (const systemCall &)=delete
void operator= (const systemCall &)=delete
Protected Member Functions inherited from functionObject
word scopedName (const word &name) const
Protected Attributes
stringList executeCalls_
stringList writeCalls_
stringList endCalls_
bool masterOnly_
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &runTime, const dictionary &dict)
Public Attributes inherited from functionObject
bool log
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
static bool defaultUseNamePrefix
static word outputPrefix
Detailed Description
Executes system calls, entered in the form of string lists.
Calls can be made at the following points in the calculation:
every time step
every output time
end of the calculation
Usage
Example of the function object specification:
systemCall1
{
    type        systemCall;
    libs        (utilityFunctionObjects);
    ...
    executeCalls
    (
        "echo execute"
    );
    writeCalls
    (
        "echo === writing data ==="
    );
    endCalls
    (
        "echo === echoing .bashrc ==="
        "cat ~/.bashrc"
        "echo \*\*\* done \*\*\*"
    );
}
Where the entries comprise:
Property Description Required Default value
type type name: systemCall yes
executeCalls list of calls on execute yes
writeCalls list of calls on write yes
endCalls list of calls on end yes
master execute on master only no false
Note
Since this function object executes system calls, there is a potential security risk. In order to use the systemCall function object, the allowSystemOperations must be set to '1'; otherwise, system calls will not be allowed.
Additionally, since the system commands are normally sent via the shell, special shell character may require backslash escaping.
See also
Foam::functionObject Foam::functionObjects::timeControl
Source files
systemCall.H
systemCall.C
Definition at line 136 of file systemCall.H.
Constructor & Destructor Documentation
systemCall() [1/2]
systemCall (const systemCall &) protected delete
systemCall() [2/2]
systemCall (const word & name, const Time & runTime, const dictionary & dict)
Definition at line 78 of file systemCall.C.
References dict, and systemCall::read().
~systemCall()
virtual ~systemCall () virtual default
Member Function Documentation
dispatch()
Foam::label dispatch (const stringList & calls) protected
Definition at line 48 of file systemCall.C.
References Pstream::broadcast(), UList< T >::empty(), UPstream::master(), systemCall::masterOnly_, and Foam::system().
operator=()
void operator= (const systemCall &) protected delete
TypeName()
TypeName ("systemCall")
read()
bool read (const dictionary & dict) virtual
Reimplemented from functionObject.
Definition at line 97 of file systemCall.C.
References dynamicCode::allowSystemOperations, Foam::foamVersion::api, dict, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::isAdministrator(), Foam::nl, functionObject::read(), and WarningInFunction.
Referenced by systemCall::systemCall().
execute()
bool execute () virtual
Implements functionObject.
Definition at line 145 of file systemCall.C.
write()
bool write () virtual
Implements functionObject.
Definition at line 152 of file systemCall.C.
end()
bool end () virtual
Reimplemented from functionObject.
Definition at line 159 of file systemCall.C.
Member Data Documentation
executeCalls_
stringList executeCalls_ protected
Definition at line 145 of file systemCall.H.
writeCalls_
stringList writeCalls_ protected
Definition at line 148 of file systemCall.H.
endCalls_
stringList endCalls_ protected
Definition at line 151 of file systemCall.H.
masterOnly_
bool masterOnly_ protected
Definition at line 154 of file systemCall.H.
Referenced by systemCall::dispatch().
The documentation for this class was generated from the following files:
src/functionObjects/utilities/systemCall/systemCall.H
src/functionObjects/utilities/systemCall/systemCall.C