OpenFOAM: heatTransferModel Class Reference
heatTransferModel Class Reference abstract
Base class for film heat transfer models.
#include <heatTransferModel.H>
Public Member Functions
TypeName ("heatTransferModel")
declareRunTimeSelectionTable (autoPtr, heatTransferModel, dictionary,(surfaceFilmRegionModel &film, const dictionary &dict),(film, dict))
heatTransferModel (surfaceFilmRegionModel &film)
heatTransferModel (const word &modelType, surfaceFilmRegionModel &film, const dictionary &dict)
virtual ~heatTransferModel ()
virtual void correct ()=0
virtual tmp< volScalarField > h () const =0
Public Member Functions inherited from filmSubModelBase
filmSubModelBase (surfaceFilmRegionModel &film)
filmSubModelBase (surfaceFilmRegionModel &film, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
filmSubModelBase (const word &modelName, surfaceFilmRegionModel &film, const dictionary &dict, const word &baseName, const word &modelType)
virtual ~filmSubModelBase ()
virtual bool writeTime () const
const surfaceFilmRegionModel & film () const
surfaceFilmRegionModel & film ()
template<class FilmType >
const FilmType & filmType () const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
subModelBase (const subModelBase &smb)
virtual ~subModelBase ()=default
const word & modelName () const
const dictionary & dict () const
const word & baseName () const
const word & modelType () const
const dictionary & coeffDict () const
const dictionary & properties () const
virtual bool defaultCoeffs (const bool printMsg) const
virtual bool active () const
virtual void cacheFields (const bool store)
virtual fileName localPath () const
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
bool getModelDict (const word &entryName, dictionary &dict) const
template<class Type >
bool getModelProperty (const word &entryName, Type &value) const
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
virtual void write (Ostream &os) const
Static Public Member Functions
static autoPtr< heatTransferModel > New (surfaceFilmRegionModel &film, const dictionary &dict)
Additional Inherited Members
Public Attributes inherited from subModelBase
bool log
Protected Member Functions inherited from subModelBase
bool inLine () const
Protected Attributes inherited from filmSubModelBase
surfaceFilmRegionModel & filmModel_
Protected Attributes inherited from subModelBase
const word modelName_
dictionary & properties_
const dictionary dict_
const word baseName_
const word modelType_
const dictionary coeffDict_
Detailed Description
Base class for film heat transfer models.
Source files
heatTransferModel.H
heatTransferModel.C
heatTransferModelNew.C
Definition at line 52 of file heatTransferModel.H.
Constructor & Destructor Documentation
heatTransferModel() [1/2]
heatTransferModel (surfaceFilmRegionModel & film)
Definition at line 39 of file heatTransferModel.C.
heatTransferModel() [2/2]
heatTransferModel (const word & modelType, surfaceFilmRegionModel & film, const dictionary & dict)
Definition at line 48 of file heatTransferModel.C.
~heatTransferModel()
~heatTransferModel () virtual
Definition at line 61 of file heatTransferModel.C.
Member Function Documentation
TypeName()
TypeName ("heatTransferModel")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , heatTransferModel , dictionary , (surfaceFilmRegionModel &film, const dictionary &dict) , (film, dict))
New()
autoPtr< heatTransferModel > New (surfaceFilmRegionModel & film, const dictionary & dict) static
Definition at line 35 of file heatTransferModelNew.C.
References subModelBase::dict(), Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, UPtrList< T >::get(), Foam::Info, and subModelBase::modelType().
correct()
virtual void correct () pure virtual
Implemented in constantHeatTransfer, and mappedConvectiveHeatTransfer.
h()
virtual tmp< volScalarField > h () const pure virtual
Implemented in constantHeatTransfer, and mappedConvectiveHeatTransfer.
The documentation for this class was generated from the following files:
src/regionModels/surfaceFilmModels/submodels/thermo/heatTransferModel/heatTransferModel/heatTransferModel.H
src/regionModels/surfaceFilmModels/submodels/thermo/heatTransferModel/heatTransferModel/heatTransferModel.C
src/regionModels/surfaceFilmModels/submodels/thermo/heatTransferModel/heatTransferModel/heatTransferModelNew.C