OpenFOAM: hexRef8 Class Reference
hexRef8 Class Reference
Refinement of (split) hexes using polyTopoChange.
#include <hexRef8.H>
Public Member Functions
ClassName ("hexRef8")
hexRef8 (const polyMesh &mesh, const bool readHistory=true)
hexRef8 (const polyMesh &mesh, const labelList &cellLevel, const labelList &pointLevel, const refinementHistory &history, const scalar level0Edge=-GREAT)
hexRef8 (const polyMesh &mesh, const labelList &cellLevel, const labelList &pointLevel, const scalar level0Edge=-GREAT)
const polyMesh & mesh () const
const labelIOList & cellLevel () const
const labelIOList & pointLevel () const
const refinementHistory & history () const
scalar level0EdgeLength () const
label faceLevel (const label facei) const
labelList consistentRefinement (const labelUList &cellLevel, const labelList &cellsToRefine, const bool maxSet) const
labelList consistentRefinement (const labelList &cellsToRefine, const bool maxSet) const
labelList consistentSlowRefinement (const label maxFaceDiff, const labelList &cellsToRefine, const labelList &facesToCheck, const label maxPointDiff, const labelList &pointsToCheck) const
labelList consistentSlowRefinement2 (const label maxFaceDiff, const labelList &cellsToRefine, const labelList &facesToCheck) const
labelListList setRefinement (const labelList &cells, polyTopoChange &)
void updateMesh (const mapPolyMesh &)
void storeData (const labelList &pointsToStore, const labelList &facesToStore, const labelList &cellsToStore)
void updateMesh (const mapPolyMesh &, const Map< label > &pointsToRestore, const Map< label > &facesToRestore, const Map< label > &cellsToRestore)
void subset (const labelList &pointMap, const labelList &faceMap, const labelList &cellMap)
void distribute (const mapDistributePolyMesh &)
void checkMesh () const
void checkRefinementLevels (const label maxPointDiff, const labelList &pointsToCheck) const
const cellShapeList & cellShapes () const
labelList getSplitPoints () const
labelList consistentUnrefinement (const labelList &pointsToUnrefine, const bool maxSet) const
void setUnrefinement (const labelList &splitPointLabels, polyTopoChange &)
void setInstance (const fileName &inst)
bool write (const bool writeOnProc=true) const
Static Public Member Functions
static void removeFiles (const polyMesh &)
Detailed Description
Refinement of (split) hexes using polyTopoChange.
Source files
hexRef8.H
hexRef8.C
Definition at line 62 of file hexRef8.H.
Constructor & Destructor Documentation
hexRef8() [1/3]
hexRef8 (const polyMesh & mesh, const bool readHistory = true) explicit
Definition at line 1918 of file hexRef8.C.
References Foam::abort(), refinementHistory::active(), hexRef8::checkMesh(), hexRef8::checkRefinementLevels(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, IOobject::objectPath(), refinementHistory::read(), IOobjectOption::READ_IF_PRESENT, IOobjectOption::readOpt(), UPtrList< T >::size(), UList< T >::size(), IOobject::typeHeaderOk(), and refinementHistory::visibleCells().
hexRef8() [2/3]
hexRef8 (const polyMesh & mesh, const labelList & cellLevel, const labelList & pointLevel, const refinementHistory & history, const scalar level0Edge = -GREAT)
Definition at line 2031 of file hexRef8.C.
References Foam::abort(), refinementHistory::active(), hexRef8::checkMesh(), hexRef8::checkRefinementLevels(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, UPtrList< T >::size(), UList< T >::size(), and refinementHistory::visibleCells().
hexRef8() [3/3]
hexRef8 (const polyMesh & mesh, const labelList & cellLevel, const labelList & pointLevel, const scalar level0Edge = -GREAT)
Definition at line 2140 of file hexRef8.C.
References Foam::abort(), hexRef8::checkMesh(), hexRef8::checkRefinementLevels(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, and UList< T >::size().
Member Function Documentation
ClassName()
ClassName ("hexRef8")
mesh()
const polyMesh & mesh () const inline
Definition at line 387 of file hexRef8.H.
cellLevel()
const labelIOList & cellLevel () const inline
Definition at line 392 of file hexRef8.H.
Referenced by dynamicRefineFvMesh::calculateProtectedCells().
pointLevel()
const labelIOList & pointLevel () const inline
Definition at line 397 of file hexRef8.H.
history()
const refinementHistory & history () const inline
Definition at line 402 of file hexRef8.H.
level0EdgeLength()
scalar level0EdgeLength () const inline
Definition at line 408 of file hexRef8.H.
References dimensioned< Type >::value().
faceLevel()
Foam::label faceLevel (const label facei) const
Definition at line 790 of file hexRef8.C.
References f(), and UList< T >::size().
consistentRefinement() [1/2]
Foam::labelList consistentRefinement (const labelUList & cellLevel, const labelList & cellsToRefine, const bool maxSet) const
Definition at line 2242 of file hexRef8.C.
References Foam::endl(), Foam::Pout, and Foam::reduce().
Referenced by hexRef8::consistentRefinement().
consistentRefinement() [2/2]
labelList consistentRefinement (const labelList & cellsToRefine, const bool maxSet) const inline
Definition at line 435 of file hexRef8.H.
References hexRef8::consistentRefinement().
consistentSlowRefinement()
Foam::labelList consistentSlowRefinement (const label maxFaceDiff, const labelList & cellsToRefine, const labelList & facesToCheck, const label maxPointDiff, const labelList & pointsToCheck) const
Definition at line 2298 of file hexRef8.C.
References Foam::abort(), PtrList< T >::append(), PtrList< T >::clear(), refinementData::count(), UPtrList< T >::count(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::findIndices(), forAll, forAllConstIters, Foam::labelMin, UPtrList< T >::last(), Foam::mag(), Foam::max(), Foam::nl, Foam::Pout, Foam::reduce(), UPtrList< T >::size(), syncTools::swapBoundaryFaceList(), syncTools::syncPointList(), refinementData::updateFace(), and Foam::Zero.
consistentSlowRefinement2()
Foam::labelList consistentSlowRefinement2 (const label maxFaceDiff, const labelList & cellsToRefine, const labelList & facesToCheck) const
Definition at line 2782 of file hexRef8.C.
References Foam::abort(), PtrList< T >::append(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::findIndices(), forAll, Foam::nl, Foam::Pout, FaceCellWaveBase::propagationTol(), Foam::reduce(), UPtrList< T >::size(), and UPtrList< T >::test().
setRefinement()
Foam::labelListList setRefinement (const labelList & cells, polyTopoChange & meshMod)
Definition at line 3182 of file hexRef8.C.
References Foam::abort(), PtrList< T >::append(), e, Foam::endl(), f(), Foam::FatalError, FatalErrorInFunction, forAll, HashSet< Key, Hash >::insert(), Foam::labelMax, Foam::labelMin, Foam::max(), Foam::min(), OFstream::name(), Foam::nl, IOobject::objectPath(), Foam::Pout, PtrList< T >::set(), polyTopoChange::setAction(), List< T >::setSize(), PtrList< T >::setSize(), HashTable< T, Key, Hash >::size(), UPtrList< T >::size(), UList< T >::size(), syncTools::swapBoundaryFaceList(), syncTools::syncBoundaryFacePositions(), syncTools::syncEdgeList(), syncTools::syncEdgePositions(), syncTools::syncFaceList(), UPtrList< T >::test(), List< T >::transfer(), PtrList< T >::transfer(), regIOobject::write(), Foam::meshTools::writeOBJ(), and Foam::Zero.
updateMesh() [1/2]
void updateMesh (const mapPolyMesh & map)
Definition at line 4224 of file hexRef8.C.
storeData()
void storeData (const labelList & pointsToStore, const labelList & facesToStore, const labelList & cellsToStore)
Definition at line 4196 of file hexRef8.C.
References PtrList< T >::clear(), forAll, PtrList< T >::resize(), and UPtrList< T >::size().
updateMesh() [2/2]
void updateMesh (const mapPolyMesh & map, const Map< label > & pointsToRestore, const Map< label > & facesToRestore, const Map< label > & cellsToRestore)
Definition at line 4235 of file hexRef8.C.
References Foam::abort(), mapPolyMesh::cellMap(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, forAllConstIters, newPointi, mapPolyMesh::nOldCells(), mapPolyMesh::nOldPoints(), mapPolyMesh::pointMap(), Foam::Pout, Foam::reorder(), mapPolyMesh::reverseCellMap(), mapPolyMesh::reversePointMap(), UPtrList< T >::size(), UList< T >::size(), and PtrList< T >::transfer().
subset()
void subset (const labelList & pointMap, const labelList & faceMap, const labelList & cellMap)
Definition at line 4425 of file hexRef8.C.
References Foam::abort(), Foam::endl(), Foam::faceMap(), Foam::FatalError, FatalErrorInFunction, forAll, newPointi, Foam::nl, Foam::Pout, UList< T >::size(), PtrList< T >::transfer(), and WarningInFunction.
distribute()
void distribute (const mapDistributePolyMesh & map)
Definition at line 4509 of file hexRef8.C.
References PtrList< T >::clear(), mapDistributePolyMesh::distributeCellData(), mapDistributePolyMesh::distributePointData(), Foam::endl(), and Foam::Pout.
checkMesh()
void checkMesh () const
Definition at line 4537 of file hexRef8.C.
References Foam::abort(), e, Foam::endl(), f(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::mag(), patches, Foam::Pout, pp(), UPtrList< T >::size(), UList< T >::size(), and syncTools::swapBoundaryFaceList().
Referenced by hexRef8::hexRef8(), hexRef8::hexRef8(), and hexRef8::hexRef8().
checkRefinementLevels()
void checkRefinementLevels (const label maxPointDiff, const labelList & pointsToCheck) const
Definition at line 4745 of file hexRef8.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::labelMax, Foam::labelMin, Foam::mag(), Foam::max(), Foam::nl, Foam::Pout, UPtrList< T >::size(), syncTools::swapBoundaryFaceList(), syncTools::syncPointList(), and Foam::Zero.
Referenced by hexRef8::hexRef8(), hexRef8::hexRef8(), and hexRef8::hexRef8().
cellShapes()
const Foam::cellShapeList & cellShapes () const
Definition at line 4998 of file hexRef8.C.
References Foam::endl(), forAll, Foam::nl, and Foam::Pout.
getSplitPoints()
Foam::labelList getSplitPoints () const
Definition at line 5058 of file hexRef8.C.
References Foam::abort(), Foam::endl(), f(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::Pout, UPtrList< T >::size(), and Foam::Zero.
consistentUnrefinement()
Foam::labelList consistentUnrefinement (const labelList & pointsToUnrefine, const bool maxSet) const
Definition at line 5261 of file hexRef8.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, UPtrList< T >::get(), Foam::Pout, Foam::reduce(), PtrList< T >::set(), syncTools::swapBoundaryFaceList(), and UPtrList< T >::test().
setUnrefinement()
void setUnrefinement (const labelList & splitPointLabels, polyTopoChange & meshMod)
Definition at line 5484 of file hexRef8.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::min(), Foam::nl, pFaces, Foam::Pout, UPtrList< T >::size(), and regIOobject::write().
setInstance()
void setInstance (const fileName & inst)
Definition at line 1725 of file hexRef8.C.
References Foam::endl(), and Foam::Pout.
write()
bool write (const bool writeOnProc = true) const
Definition at line 5686 of file hexRef8.C.
References refinementHistory::removeFiles().
removeFiles()
void removeFiles (const polyMesh & mesh) static
Definition at line 5706 of file hexRef8.C.
References DebugVar, Foam::exists(), polyMesh::facesInstance(), io(), mesh, polyMesh::meshSubDir, IOobject::path(), refinementHistory::removeFiles(), and Foam::rm().
Referenced by meshRefinement::removeFiles().
The documentation for this class was generated from the following files:
src/dynamicMesh/polyTopoChange/polyTopoChange/hexRef8/hexRef8.H
src/dynamicMesh/polyTopoChange/polyTopoChange/hexRef8/hexRef8.C