OpenFOAM: findNearestMaskedOp< PatchType > Class Template Reference
findNearestMaskedOp< PatchType > Class Template Reference
#include <findNearestMaskedOp.H>
Public Member Functions
findNearestMaskedOp (const indexedOctree< treeDataPrimitivePatch< PatchType > > &tree, const labelUList &excludeIndices)
void operator() (const labelUList &indices, const point &sample, scalar &nearestDistSqr, label &minIndex, point &nearestPoint) const
Detailed Description
template<class PatchType>
class Foam::findNearestMaskedOp< PatchType >
Definition at line 8 of file findNearestMaskedOp.H.
Constructor & Destructor Documentation
findNearestMaskedOp()
template<class PatchType > findNearestMaskedOp (const indexedOctree< treeDataPrimitivePatch< PatchType > > & tree, const labelUList & excludeIndices) inline
Definition at line 15 of file findNearestMaskedOp.H.
Member Function Documentation
operator()()
template<class PatchType > void operator() (const labelUList & indices, const point & sample, scalar & nearestDistSqr, label & minIndex, point & nearestPoint) const inline
Definition at line 25 of file findNearestMaskedOp.H.
References f(), forAll, UList< T >::found(), points, and Foam::sqr().
The documentation for this class was generated from the following file:
src/meshTools/AMIInterpolation/AMIInterpolation/findNearestMaskedOp.H