OpenFOAM: buoyancyForce Class Reference
buoyancyForce Class Reference
Numerics » Finite volume Options » Sources
Applies buoyancy force sources (i.e. Sf) to the momentum equation for incompressible and compressible flows.
#include <buoyancyForce.H>
Public Member Functions
TypeName ("buoyancyForce")
buoyancyForce (const word &sourceName, const word &modelType, const dictionary &dict, const fvMesh &mesh)
buoyancyForce (const buoyancyForce &)=delete
void operator= (const buoyancyForce &)=delete
virtual ~buoyancyForce ()=default
virtual void addSup (fvMatrix< vector > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldi)
virtual bool read (const dictionary &dict)
Public Member Functions inherited from option
TypeName ("option")
declareRunTimeSelectionTable (autoPtr, option, dictionary,(const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh),(name, modelType, dict, mesh))
option (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
autoPtr< option > clone () const
virtual ~option ()=default
const word & name () const noexcept
const fvMesh & mesh () const noexcept
const dictionary & coeffs () const noexcept
bool active () const noexcept
void setApplied (const label fieldi)
bool active (const bool on) noexcept
virtual bool isActive ()
virtual label applyToField (const word &fieldName) const
virtual void checkApplied () const
virtual void addSup (fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (fvMatrix< tensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< scalar > &eqn, const label fieldi)
virtual void constrain (fvMatrix< vector > &eqn, const label fieldi)
virtual void constrain (fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< tensor > &eqn, const label fieldi)
virtual void correct (volScalarField &field)
virtual void correct (volVectorField &field)
virtual void correct (volSphericalTensorField &field)
virtual void correct (volSymmTensorField &field)
virtual void correct (volTensorField &field)
virtual void postProcessSens (scalarField &sensField, const word &fieldName=word::null, const word &designVariablesName=word::null)
virtual void postProcessSens (vectorField &sensField, const word &fieldName=word::null, const word &designVariablesName=word::null)
virtual void postProcessSens (tensorField &sensField, const word &fieldName=word::null, const word &designVariablesName=word::null)
virtual void writeHeader (Ostream &) const
virtual void writeFooter (Ostream &) const
virtual void writeData (Ostream &) const
Additional Inherited Members
Static Public Member Functions inherited from option
static autoPtr< option > New (const word &name, const dictionary &dict, const fvMesh &mesh)
Public Attributes inherited from option
bool log
Protected Member Functions inherited from option
void resetApplied ()
Protected Attributes inherited from option
const word name_
const word modelType_
const fvMesh & mesh_
dictionary dict_
dictionary coeffs_
wordList fieldNames_
List< bool > applied_
bool active_
Detailed Description
Applies buoyancy force sources (i.e. Sf) to the momentum equation for incompressible and compressible flows.
where
= Buoyancy force source term
= Fluid density
= Gravitational acceleration field
Sources applied to:
      U         | Velocity                                   [m/s]
Required fields:
      U         | Velocity                                   [m/s]
Usage
Minimal example by using constant/fvOptions:
buoyancyForce1
{
    // Mandatory entries (unmodifiable)
    type             buoyancyForce;
    fields           (U);
    // Mandatory/Optional (inherited) entries
    ...
}
where the entries mean:
Property Description Type Reqd Dflt
type Type name: buoyancyEnergy word yes -
fields Name of operand vector field word yes -
The inherited entries are elaborated in:
fvOption.H
Note
The entry fields accepts only a single vector field name.
See also
Foam::fv::buoyancyEnergy
Foam::fv::buoyancyTurbSource
Source files
buoyancyForce.H
buoyancyForce.C
Definition at line 136 of file buoyancyForce.H.
Constructor & Destructor Documentation
buoyancyForce() [1/2]
buoyancyForce (const word & sourceName, const word & modelType, const dictionary & dict, const fvMesh & mesh)
Definition at line 41 of file buoyancyForce.C.
References option::coeffs_, Foam::exit(), Foam::FatalError, FatalErrorInFunction, option::fieldNames_, Foam::New(), dictionary::readEntry(), option::resetApplied(), and UList< T >::size().
buoyancyForce() [2/2]
buoyancyForce (const buoyancyForce &) delete
~buoyancyForce()
virtual ~buoyancyForce () virtual default
Member Function Documentation
TypeName()
TypeName ("buoyancyForce")
operator=()
void operator= (const buoyancyForce &) delete
addSup() [1/2]
void addSup (fvMatrix< vector > & eqn, const label fieldi) virtual
Reimplemented from option.
Definition at line 66 of file buoyancyForce.C.
addSup() [2/2]
void addSup (const volScalarField & rho, fvMatrix< vector > & eqn, const label fieldi) virtual
Reimplemented from option.
Definition at line 76 of file buoyancyForce.C.
References rho.
read()
bool read (const dictionary & dict) virtual
Reimplemented from option.
Definition at line 87 of file buoyancyForce.C.
References NotImplemented.
The documentation for this class was generated from the following files:
src/fvOptions/sources/derived/buoyancyForce/buoyancyForce.H
src/fvOptions/sources/derived/buoyancyForce/buoyancyForce.C