OpenFOAM: masslessBody Class Reference
masslessBody Class Reference
#include <masslessBody.H>
Public Member Functions
TypeName ("masslessBody")
masslessBody ()
masslessBody (const word &name)
masslessBody (const word &name, const dictionary &dict)
virtual autoPtr< rigidBody > clone () const
virtual ~masslessBody ()
virtual bool massless () const
virtual void write (Ostream &) const
Public Member Functions inherited from rigidBody
TypeName ("rigidBody")
declareRunTimeSelectionTable (autoPtr, rigidBody, dictionary,(const word &name, const dictionary &dict),(name, dict))
rigidBody (const word &name, const scalar &m, const vector &c, const symmTensor &Ic)
rigidBody (const word &name, const rigidBodyInertia &rbi)
rigidBody (const word &name, const dictionary &dict)
virtual ~rigidBody ()
const word & name () const
void merge (const subBody &)
Public Member Functions inherited from rigidBodyInertia
rigidBodyInertia ()
rigidBodyInertia (const scalar m, const vector &c, const symmTensor &Ic)
rigidBodyInertia (const dictionary &dict)
rigidBodyInertia (const spatialTensor &st)
rigidBodyInertia (Istream &is)
scalar m () const
const vector & c () const
const symmTensor & Ic () const
symmTensor Ioc () const
symmTensor Icc (const vector &c) const
symmTensor Io () const
scalar kineticEnergy (const spatialVector &v)
operator spatialTensor () const
void operator+= (const rigidBodyInertia &)
Additional Inherited Members
Static Public Member Functions inherited from rigidBody
static autoPtr< rigidBody > New (const word &name, const scalar &m, const vector &c, const symmTensor &Ic)
static autoPtr< rigidBody > New (const word &name, const dictionary &dict)
Static Public Member Functions inherited from rigidBodyInertia
static symmTensor Ioc (const scalar m, const vector &c)
Detailed Description
Definition at line 51 of file masslessBody.H.
Constructor & Destructor Documentation
masslessBody() [1/3]
masslessBody () inline
Definition at line 23 of file masslessBodyI.H.
Referenced by masslessBody::clone().
masslessBody() [2/3]
masslessBody (const word & name) inline
Definition at line 29 of file masslessBodyI.H.
masslessBody() [3/3]
masslessBody (const word & name, const dictionary & dict) inline
Definition at line 35 of file masslessBodyI.H.
~masslessBody()
~masslessBody () virtual
Definition at line 52 of file masslessBody.C.
Member Function Documentation
TypeName()
TypeName ("masslessBody")
clone()
Foam::autoPtr< Foam::RBD::rigidBody > clone () const virtual
Reimplemented from rigidBody.
Reimplemented in jointBody.
Definition at line 44 of file masslessBody.C.
References masslessBody::masslessBody().
massless()
bool massless () const virtual
Reimplemented from rigidBody.
Definition at line 58 of file masslessBody.C.
write()
void write (Ostream & os) const virtual
Reimplemented from rigidBody.
Definition at line 64 of file masslessBody.C.
References os(), and Foam::type().
The documentation for this class was generated from the following files:
src/rigidBodyDynamics/bodies/masslessBody/masslessBody.H
src/rigidBodyDynamics/bodies/masslessBody/masslessBody.C
src/rigidBodyDynamics/bodies/masslessBody/masslessBodyI.H