OpenFOAM: sensitivityMultiple Class Reference
sensitivityMultiple Class Reference
Calculation of adjoint based sensitivities of multiple types.
#include <sensitivityMultipleIncompressible.H>
Public Member Functions
TypeName ("multiple")
sensitivityMultiple (const fvMesh &mesh, const dictionary &dict, incompressibleAdjointSolver &adjointSolver)
virtual ~sensitivityMultiple ()=default
virtual bool readDict (const dictionary &dict)
virtual void accumulateIntegrand (const scalar dt)
virtual void assembleSensitivities ()
const scalarField & calculateSensitivities ()
virtual void clearSensitivities ()
virtual void write (const word &baseName=word::null)
Public Member Functions inherited from adjointSensitivity
TypeName ("adjointSensitivity")
declareRunTimeSelectionTable (autoPtr, adjointSensitivity, dictionary,(const fvMesh &mesh, const dictionary &dict, incompressibleAdjointSolver &adjointSolver),(mesh, dict, adjointSolver))
adjointSensitivity (const fvMesh &mesh, const dictionary &dict, incompressibleAdjointSolver &adjointSolver)
virtual ~adjointSensitivity ()=default
const incompressibleVars & primalVars () const
const incompressibleAdjointVars & adjointVars () const
const incompressibleAdjointSolver & adjointSolver () const
const scalarField & getSensitivities () const
tmp< volTensorField > computeGradDxDbMultiplier ()
tmp< volVectorField > adjointMeshMovementSource ()
Public Member Functions inherited from sensitivity
TypeName ("sensitivity")
sensitivity (const fvMesh &mesh, const dictionary &dict)
virtual ~sensitivity ()=default
const dictionary & dict () const
virtual void computeDerivativesSize ()
Protected Attributes
wordList sensTypes_
PtrList< adjointSensitivity > sens_
Protected Attributes inherited from adjointSensitivity
scalarField derivatives_
incompressibleAdjointSolver & adjointSolver_
const incompressibleVars & primalVars_
incompressibleAdjointVars & adjointVars_
objectiveManager & objectiveManager_
Protected Attributes inherited from sensitivity
const fvMesh & mesh_
dictionary dict_
autoPtr< volScalarField > fieldSensPtr_
Additional Inherited Members
Static Public Member Functions inherited from adjointSensitivity
static autoPtr< adjointSensitivity > New (const fvMesh &mesh, const dictionary &dict, incompressibleAdjointSolver &adjointSolver)
Detailed Description
Calculation of adjoint based sensitivities of multiple types.
Source files
sensitivityMultipleIncompressible.H
sensitivityMultiple.C
Definition at line 51 of file sensitivityMultipleIncompressible.H.
Constructor & Destructor Documentation
sensitivityMultiple()
sensitivityMultiple (const fvMesh & mesh, const dictionary & dict, incompressibleAdjointSolver & adjointSolver)
Definition at line 46 of file sensitivityMultipleIncompressible.C.
References sensitivity::dict(), forAll, mesh, adjointSensitivity::New(), sensitivityMultiple::sens_, sensitivityMultiple::sensTypes_, and PtrList< T >::set().
~sensitivityMultiple()
virtual ~sensitivityMultiple () virtual default
Member Function Documentation
TypeName()
TypeName ("multiple")
readDict()
bool readDict (const dictionary & dict) virtual
Reimplemented from sensitivity.
Definition at line 75 of file sensitivityMultipleIncompressible.C.
References sensitivity::dict(), forAll, sensitivity::readDict(), sensitivityMultiple::sens_, and sensitivityMultiple::sensTypes_.
accumulateIntegrand()
void accumulateIntegrand (const scalar dt) virtual
Implements adjointSensitivity.
Definition at line 94 of file sensitivityMultipleIncompressible.C.
References forAll, and sensitivityMultiple::sens_.
assembleSensitivities()
void assembleSensitivities () virtual
Implements adjointSensitivity.
Definition at line 103 of file sensitivityMultipleIncompressible.C.
References forAll, and sensitivityMultiple::sens_.
calculateSensitivities()
const scalarField & calculateSensitivities () virtual
Reimplemented from adjointSensitivity.
Definition at line 112 of file sensitivityMultipleIncompressible.C.
References adjointSensitivity::derivatives_, Foam::endl(), forAll, Foam::Info, sensitivityMultiple::sens_, sensitivityMultiple::sensTypes_, Foam::type(), and write().
clearSensitivities()
void clearSensitivities () virtual
Reimplemented from adjointSensitivity.
Definition at line 125 of file sensitivityMultipleIncompressible.C.
References forAll, and sensitivityMultiple::sens_.
write()
void write (const word & baseName = word::null) virtual
Reimplemented from adjointSensitivity.
Definition at line 134 of file sensitivityMultipleIncompressible.C.
References forAll, sensitivityMultiple::sens_, and sensitivityMultiple::sensTypes_.
Member Data Documentation
sensTypes_
wordList sensTypes_ protected
Definition at line 59 of file sensitivityMultipleIncompressible.H.
Referenced by sensitivityMultiple::calculateSensitivities(), sensitivityMultiple::readDict(), sensitivityMultiple::sensitivityMultiple(), and sensitivityMultiple::write().
sens_
PtrList<adjointSensitivity> sens_ protected
Definition at line 61 of file sensitivityMultipleIncompressible.H.
Referenced by sensitivityMultiple::accumulateIntegrand(), sensitivityMultiple::assembleSensitivities(), sensitivityMultiple::calculateSensitivities(), sensitivityMultiple::clearSensitivities(), sensitivityMultiple::readDict(), sensitivityMultiple::sensitivityMultiple(), and sensitivityMultiple::write().
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/optimisation/adjointSensitivity/incompressible/sensitivityMultiple/sensitivityMultipleIncompressible.H
src/optimisation/adjointOptimisation/adjoint/optimisation/adjointSensitivity/incompressible/sensitivityMultiple/sensitivityMultipleIncompressible.C