OpenFOAM: triSurfaceLoader Class Reference
triSurfaceLoader Class Reference
Convenience class for loading single or multiple surface files from the constant/triSurface (or other) directory.
#include <triSurfaceLoader.H>
Public Types
enum loadingOption { SINGLE_REGION , FILE_REGION , OFFSET_REGION , MERGE_REGION }
Public Member Functions
triSurfaceLoader (const fileName &directory)
triSurfaceLoader (const Time &runTime)
~triSurfaceLoader ()=default
const fileName & directory () const noexcept
const wordList & available () const noexcept
const wordList & selected () const noexcept
label readDir ()
label selectAll ()
label select (const word &name)
label select (const wordRe &mat)
label select (const UList< wordRe > &matcher)
autoPtr< triSurface > load (const enum loadingOption opt=loadingOption::OFFSET_REGION, const scalar scaleFactor=-1) const
Static Public Attributes
static const Enum< loadingOption > loadingOptionNames
Detailed Description
Convenience class for loading single or multiple surface files from the constant/triSurface (or other) directory.
Surfaces selection based on word, wordRe, list of wordRe. If multiple surfaces are selected, they are concatenated into a single surface with offset faces,points,regions.
Source files
triSurfaceLoader.H
triSurfaceLoader.C
Definition at line 58 of file triSurfaceLoader.H.
Member Enumeration Documentation
loadingOption
enum loadingOption
Enumerator
SINGLE_REGION
"single" = One region for all files
FILE_REGION
"file" = One region for each file
OFFSET_REGION
"offset" = Offset regions per file
MERGE_REGION
"merge" = Merge regions by name
Definition at line 63 of file triSurfaceLoader.H.
Constructor & Destructor Documentation
triSurfaceLoader() [1/2]
triSurfaceLoader (const fileName & directory)
Definition at line 43 of file triSurfaceLoader.C.
References triSurfaceLoader::readDir().
triSurfaceLoader() [2/2]
triSurfaceLoader (const Time & runTime)
Definition at line 53 of file triSurfaceLoader.C.
References triSurfaceLoader::readDir().
~triSurfaceLoader()
~triSurfaceLoader () default
Member Function Documentation
directory()
const fileName & directory () const inline noexcept
Definition at line 117 of file triSurfaceLoader.H.
available()
const wordList & available () const inline noexcept
Definition at line 123 of file triSurfaceLoader.H.
selected()
const wordList & selected () const inline noexcept
Definition at line 129 of file triSurfaceLoader.H.
readDir()
Foam::label readDir ()
Definition at line 65 of file triSurfaceLoader.C.
References triSurface::canRead(), f(), fileName::FILE, Foam::readDir(), and UList< T >::size().
Referenced by triSurfaceLoader::triSurfaceLoader(), and triSurfaceLoader::triSurfaceLoader().
selectAll()
Foam::label selectAll ()
Definition at line 90 of file triSurfaceLoader.C.
References UPtrList< T >::size().
select() [1/3]
Foam::label select (const word & name)
Definition at line 97 of file triSurfaceLoader.C.
References UPtrList< T >::first(), Foam::name(), and PtrList< T >::resize().
select() [2/3]
Foam::label select (const wordRe & mat)
Definition at line 113 of file triSurfaceLoader.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::findStrings(), Foam::nl, and Foam::sort().
select() [3/3]
Foam::label select (const UList< wordRe > & matcher)
Definition at line 138 of file triSurfaceLoader.C.
References PtrList< T >::append(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::findStrings(), Foam::flatOutput(), Foam::nl, UPtrList< T >::size(), and Foam::sort().
load()
Foam::autoPtr< Foam::triSurface > load (const enum loadingOption opt = loadingOption::OFFSET_REGION, const scalar scaleFactor = -1) const
Definition at line 201 of file triSurfaceLoader.C.
References PtrList< T >::append(), PtrList< T >::clear(), UPtrList< T >::empty(), f(), UPtrList< T >::first(), forAll, IOobject::name(), Foam::output(), p, patches, triSurface::patches(), patchId(), points, PtrList< T >::resize(), UPtrList< T >::size(), and PtrList< T >::transfer().
Member Data Documentation
loadingOptionNames
const Foam::Enum< Foam::triSurfaceLoader::loadingOption > loadingOptionNames static
Definition at line 72 of file triSurfaceLoader.H.
The documentation for this class was generated from the following files:
src/meshTools/triSurface/triSurfaceLoader/triSurfaceLoader.H
src/meshTools/triSurface/triSurfaceLoader/triSurfaceLoader.C