OpenFOAM: inletOutletTotalTemperatureFvPatchScalarField Class Reference
inletOutletTotalTemperatureFvPatchScalarField Class Reference
Boundary conditions » Outlet
This boundary condition provides an outflow condition for total temperature for use with supersonic cases, where a user-specified value is applied in the case of reverse flow.
#include <inletOutletTotalTemperatureFvPatchScalarField.H>
Public Member Functions
TypeName ("inletOutletTotalTemperature")
inletOutletTotalTemperatureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
inletOutletTotalTemperatureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
inletOutletTotalTemperatureFvPatchScalarField (const inletOutletTotalTemperatureFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
inletOutletTotalTemperatureFvPatchScalarField (const inletOutletTotalTemperatureFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
inletOutletTotalTemperatureFvPatchScalarField (const inletOutletTotalTemperatureFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
const scalarField & T0 () const
scalarField & T0 ()
virtual void autoMap (const fvPatchFieldMapper &)
virtual void rmap (const fvPatchScalarField &, const labelList &)
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
This boundary condition provides an outflow condition for total temperature for use with supersonic cases, where a user-specified value is applied in the case of reverse flow.
Usage
Property Description Required Default value
U velocity field name no U
phi flux field name no phi
psi compressibility field name no thermo:psi
gamma heat capacity ration (Cp/Cv) yes
inletValue reverse flow (inlet) value yes
T0 static temperature [K] yes
Example of the boundary condition specification:
    <patchName>
    {
        type            inletOutletTotalTemperature;
        U               U;
        phi             phi;
        psi             psi;
        gamma           gamma;
        inletValue      uniform 0;
        T0              uniform 0;
        value           uniform 0;
    }
See also
Foam::inletOutletFvPatchField
Source files
inletOutletTotalTemperatureFvPatchScalarField.H
inletOutletTotalTemperatureFvPatchScalarField.C
Definition at line 115 of file inletOutletTotalTemperatureFvPatchScalarField.H.
Constructor & Destructor Documentation
inletOutletTotalTemperatureFvPatchScalarField() [1/5]
inletOutletTotalTemperatureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 30 of file inletOutletTotalTemperatureFvPatchScalarField.C.
References Foam::Zero.
inletOutletTotalTemperatureFvPatchScalarField() [2/5]
inletOutletTotalTemperatureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 66 of file inletOutletTotalTemperatureFvPatchScalarField.C.
References dict, fvPatchField< Type >::operator=(), fvPatchFieldBase::readDict(), and Foam::Zero.
inletOutletTotalTemperatureFvPatchScalarField() [3/5]
inletOutletTotalTemperatureFvPatchScalarField (const inletOutletTotalTemperatureFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 49 of file inletOutletTotalTemperatureFvPatchScalarField.C.
inletOutletTotalTemperatureFvPatchScalarField() [4/5]
inletOutletTotalTemperatureFvPatchScalarField (const inletOutletTotalTemperatureFvPatchScalarField & tppsf)
Definition at line 96 of file inletOutletTotalTemperatureFvPatchScalarField.C.
inletOutletTotalTemperatureFvPatchScalarField() [5/5]
inletOutletTotalTemperatureFvPatchScalarField (const inletOutletTotalTemperatureFvPatchScalarField & tppsf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 110 of file inletOutletTotalTemperatureFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("inletOutletTotalTemperature")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 174 of file inletOutletTotalTemperatureFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 190 of file inletOutletTotalTemperatureFvPatchScalarField.H.
T0() [1/2]
const scalarField & T0 () const inline
Definition at line 207 of file inletOutletTotalTemperatureFvPatchScalarField.H.
T0() [2/2]
scalarField & T0 () inline
Definition at line 213 of file inletOutletTotalTemperatureFvPatchScalarField.H.
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Definition at line 127 of file inletOutletTotalTemperatureFvPatchScalarField.C.
rmap()
void rmap (const fvPatchScalarField & ptf, const labelList & addr) virtual
Definition at line 137 of file inletOutletTotalTemperatureFvPatchScalarField.C.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 152 of file inletOutletTotalTemperatureFvPatchScalarField.C.
References Foam::magSqr(), and Foam::neg().
write()
void write (Ostream & os) const virtual
Definition at line 178 of file inletOutletTotalTemperatureFvPatchScalarField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntry(), Ostream::writeEntryIfDifferent(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/inletOutletTotalTemperature/inletOutletTotalTemperatureFvPatchScalarField.H
src/finiteVolume/fields/fvPatchFields/derived/inletOutletTotalTemperature/inletOutletTotalTemperatureFvPatchScalarField.C