OpenFOAM: nearestFaceAMI Class Reference
nearestFaceAMI Class Reference
Nearest-face Arbitrary Mesh Interface (AMI) method.
#include <nearestFaceAMI.H>
Classes
class nearestEqOp
Public Types
typedef Tuple2< pointIndexHit, scalar > nearestAndDist
Public Member Functions
TypeName ("nearestFaceAMI")
nearestFaceAMI (const dictionary &dict, const bool reverseTarget=false)
nearestFaceAMI (const bool requireMatch=true, const bool reverseTarget=false, const scalar lowWeightCorrection=-1)
nearestFaceAMI (const nearestFaceAMI &ami)
virtual autoPtr< AMIInterpolation > clone () const
virtual ~nearestFaceAMI ()=default
virtual bool calculate (const primitivePatch &srcPatch, const primitivePatch &tgtPatch, const autoPtr< searchableSurface > &surfPtr=nullptr)
virtual void write (Ostream &os) const
Public Member Functions inherited from AMIInterpolation
TypeName ("AMIInterpolation")
declareRunTimeSelectionTable (autoPtr, AMIInterpolation, dict,(const dictionary &dict, const bool reverseTarget),(dict, reverseTarget))
declareRunTimeSelectionTable (autoPtr, AMIInterpolation, component,(const bool requireMatch, const bool reverseTarget, const scalar lowWeightCorrection),(requireMatch, reverseTarget, lowWeightCorrection))
AMIInterpolation (const dictionary &dict, const bool reverseTarget=false)
AMIInterpolation (const bool requireMatch=true, const bool reverseTarget=false, const scalar lowWeightCorrection=-1)
AMIInterpolation (const AMIInterpolation &fineAMI, const labelList &sourceRestrictAddressing, const labelList &neighbourRestrictAddressing)
AMIInterpolation (const AMIInterpolation &ami)
virtual ~AMIInterpolation ()=default
bool upToDate () const noexcept
bool upToDate (bool flag) noexcept
bool upToDate () noexcept
bool distributed () const
bool requireMatch () const
bool setRequireMatch (const bool flag)
bool mustMatchFaces () const
bool reverseTarget () const
scalar lowWeightCorrection () const
bool applyLowWeightCorrection () const
label singlePatchProc () const
const List< scalar > & srcMagSf () const
List< scalar > & srcMagSf ()
const labelListList & srcAddress () const
labelListList & srcAddress ()
const scalarListList & srcWeights () const
scalarListList & srcWeights ()
const scalarField & srcWeightsSum () const
scalarField & srcWeightsSum ()
const pointListList & srcCentroids () const
pointListList & srcCentroids ()
const mapDistribute & srcMap () const
const List< scalar > & tgtMagSf () const
List< scalar > & tgtMagSf ()
const labelListList & tgtAddress () const
labelListList & tgtAddress ()
const scalarListList & tgtWeights () const
scalarListList & tgtWeights ()
const scalarField & tgtWeightsSum () const
scalarField & tgtWeightsSum ()
const mapDistribute & tgtMap () const
void reset (autoPtr< mapDistribute > &&srcToTgtMap, autoPtr< mapDistribute > &&tgtToSrcMap, labelListList &&srcAddress, scalarListList &&srcWeights, labelListList &&tgtAddress, scalarListList &&tgtWeights)
void append (const primitivePatch &srcPatch, const primitivePatch &tgtPatch)
void normaliseWeights (const bool conformal, const bool output)
template<class Type , class CombineOp >
void interpolateToSource (const UList< Type > &fld, const CombineOp &cop, List< Type > &result, const UList< Type > &defaultValues=UList< Type >::null()) const
template<class Type , class CombineOp >
void interpolateToTarget (const UList< Type > &fld, const CombineOp &cop, List< Type > &result, const UList< Type > &defaultValues=UList< Type >::null()) const
template<class Type , class CombineOp >
tmp< Field< Type > > interpolateToSource (const Field< Type > &fld, const CombineOp &cop, const UList< Type > &defaultValues=UList< Type >::null()) const
template<class Type , class CombineOp >
tmp< Field< Type > > interpolateToSource (const tmp< Field< Type > > &tFld, const CombineOp &cop, const UList< Type > &defaultValues=UList< Type >::null()) const
template<class Type , class CombineOp >
tmp< Field< Type > > interpolateToTarget (const Field< Type > &fld, const CombineOp &cop, const UList< Type > &defaultValues=UList< Type >::null()) const
template<class Type , class CombineOp >
tmp< Field< Type > > interpolateToTarget (const tmp< Field< Type > > &tFld, const CombineOp &cop, const UList< Type > &defaultValues=UList< Type >::null()) const
template<class Type >
tmp< Field< Type > > interpolateToSource (const Field< Type > &fld, const UList< Type > &defaultValues=UList< Type >::null()) const
template<class Type >
tmp< Field< Type > > interpolateToSource (const tmp< Field< Type > > &tFld, const UList< Type > &defaultValues=UList< Type >::null()) const
template<class Type >
tmp< Field< Type > > interpolateToTarget (const Field< Type > &fld, const UList< Type > &defaultValues=UList< Type >::null()) const
template<class Type >
tmp< Field< Type > > interpolateToTarget (const tmp< Field< Type > > &tFld, const UList< Type > &defaultValues=UList< Type >::null()) const
label srcPointFace (const primitivePatch &srcPatch, const primitivePatch &tgtPatch, const vector &n, const label tgtFacei, point &tgtPoint) const
label tgtPointFace (const primitivePatch &srcPatch, const primitivePatch &tgtPatch, const vector &n, const label srcFacei, point &srcPoint) const
bool checkSymmetricWeights (const bool log) const
void writeFaceConnectivity (const primitivePatch &srcPatch, const primitivePatch &tgtPatch, const labelListList &srcAddress) const
template<class Type , class CombineOp >
Foam::tmp< Foam::Field< Type > > interpolateToSource (const Field< Type > &fld, const CombineOp &cop, const UList< Type > &defaultValues) const
template<class Type , class CombineOp >
Foam::tmp< Foam::Field< Type > > interpolateToSource (const tmp< Field< Type > > &tFld, const CombineOp &cop, const UList< Type > &defaultValues) const
template<class Type , class CombineOp >
Foam::tmp< Foam::Field< Type > > interpolateToTarget (const Field< Type > &fld, const CombineOp &cop, const UList< Type > &defaultValues) const
template<class Type , class CombineOp >
Foam::tmp< Foam::Field< Type > > interpolateToTarget (const tmp< Field< Type > > &tFld, const CombineOp &cop, const UList< Type > &defaultValues) const
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolateToSource (const Field< Type > &fld, const UList< Type > &defaultValues) const
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolateToSource (const tmp< Field< Type > > &tFld, const UList< Type > &defaultValues) const
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolateToTarget (const Field< Type > &fld, const UList< Type > &defaultValues) const
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolateToTarget (const tmp< Field< Type > > &tFld, const UList< Type > &defaultValues) const
Additional Inherited Members
Static Public Member Functions inherited from AMIInterpolation
static autoPtr< AMIInterpolation > New (const word &modelName, const dictionary &dict, const bool reverseTarget=false)
static autoPtr< AMIInterpolation > New (const word &modelName, const bool requireMatch=true, const bool reverseTarget=false, const scalar lowWeightCorrection=-1)
Static Public Attributes inherited from AMIInterpolation
static bool cacheIntersections_ = false
Protected Types inherited from AMIInterpolation
typedef treeDataPrimitivePatch< primitivePatch > treeType
Protected Member Functions inherited from AMIInterpolation
void operator= (const AMIInterpolation &)=delete
autoPtr< indexedOctree< treeType > > createTree (const primitivePatch &patch) const
label calcDistribution (const primitivePatch &srcPatch, const primitivePatch &tgtPatch) const
void projectPointsToSurface (const searchableSurface &surf, pointField &pts) const
const primitivePatch & srcPatch0 () const
const primitivePatch & tgtPatch0 () const
Static Protected Member Functions inherited from AMIInterpolation
static void normaliseWeights (const scalarList &patchAreas, const word &patchName, const labelListList &addr, scalarListList &wght, scalarField &wghtSum, const bool conformal, const bool output, const scalar lowWeightTol)
static void agglomerate (const autoPtr< mapDistribute > &targetMap, const scalarList &fineSrcMagSf, const labelListList &fineSrcAddress, const scalarListList &fineSrcWeights, const labelList &sourceRestrictAddressing, const labelList &targetRestrictAddressing, scalarList &srcMagSf, labelListList &srcAddress, scalarListList &srcWeights, scalarField &srcWeightsSum, autoPtr< mapDistribute > &tgtMap)
Protected Attributes inherited from AMIInterpolation
bool requireMatch_
const bool reverseTarget_
const scalar lowWeightCorrection_
label singlePatchProc_
scalarList srcMagSf_
labelListList srcAddress_
scalarListList srcWeights_
scalarField srcWeightsSum_
pointListList srcCentroids_
pointField srcPatchPts_
refPtr< primitivePatch > tsrcPatch0_
autoPtr< mapDistribute > srcMapPtr_
scalarList tgtMagSf_
labelListList tgtAddress_
scalarListList tgtWeights_
scalarField tgtWeightsSum_
pointListList tgtCentroids_
pointField tgtPatchPts_
refPtr< primitivePatch > ttgtPatch0_
autoPtr< mapDistribute > tgtMapPtr_
bool upToDate_
Detailed Description
Nearest-face Arbitrary Mesh Interface (AMI) method.
Source files
nearestFaceAMI.H
nearestFaceAMI.C
Definition at line 47 of file nearestFaceAMI.H.
Member Typedef Documentation
nearestAndDist
typedef Tuple2<pointIndexHit, scalar> nearestAndDist
Definition at line 53 of file nearestFaceAMI.H.
Constructor & Destructor Documentation
nearestFaceAMI() [1/3]
nearestFaceAMI (const dictionary & dict, const bool reverseTarget = false)
Definition at line 225 of file nearestFaceAMI.C.
nearestFaceAMI() [2/3]
nearestFaceAMI (const bool requireMatch = true, const bool reverseTarget = false, const scalar lowWeightCorrection = -1)
Definition at line 236 of file nearestFaceAMI.C.
nearestFaceAMI() [3/3]
nearestFaceAMI (const nearestFaceAMI & ami)
Definition at line 248 of file nearestFaceAMI.C.
~nearestFaceAMI()
virtual ~nearestFaceAMI () virtual default
Member Function Documentation
TypeName()
TypeName ("nearestFaceAMI")
clone()
virtual autoPtr< AMIInterpolation > clone () const inline virtual
Reimplemented from AMIInterpolation.
Definition at line 134 of file nearestFaceAMI.H.
calculate()
bool calculate (const primitivePatch & srcPatch, const primitivePatch & tgtPatch, const autoPtr< searchableSurface > & surfPtr = nullptr) virtual
Reimplemented from AMIInterpolation.
Definition at line 257 of file nearestFaceAMI.C.
References AMIInterpolation::calculate(), Foam::createTree(), Foam::endl(), forAll, PointIndexHit< PointType >::hit(), PointIndexHit< PointType >::index(), Foam::mag(), Foam::magSqr(), and WarningInFunction.
write()
void write (Ostream & os) const virtual
Reimplemented from AMIInterpolation.
Definition at line 399 of file nearestFaceAMI.C.
References os(), AMIInterpolation::write(), and Ostream::writeEntryIfDifferent().
The documentation for this class was generated from the following files:
src/meshTools/AMIInterpolation/AMIInterpolation/nearestFaceAMI/nearestFaceAMI.H
src/meshTools/AMIInterpolation/AMIInterpolation/nearestFaceAMI/nearestFaceAMI.C