OpenFOAM: adjointMeshMovementSolver Class Reference
adjointMeshMovementSolver Class Reference
Solver of the adjoint to the Laplace grid displacement equation.
#include <adjointMeshMovementSolverIncompressible.H>
Public Member Functions
TypeName ("adjointMeshMovementSolver")
adjointMeshMovementSolver (const fvMesh &mesh, const dictionary &dict, Foam::incompressible::adjointSensitivity &adjointSensitivity, const labelHashSet &sensitivityPatchIDs, const autoPtr< adjointEikonalSolver > &adjointEikonalSolverPtr)
virtual ~adjointMeshMovementSolver ()=default
virtual bool readDict (const dictionary &dict)
void accumulateIntegrand (const scalar dt)
void solve ()
void reset ()
boundaryVectorField & meshMovementSensitivities ()
const volVectorField & ma ()
Protected Member Functions
void read ()
Protected Attributes
const fvMesh & mesh_
dictionary dict_
Foam::incompressible::adjointSensitivity & adjointSensitivity_
const labelHashSet & sensitivityPatchIDs_
label nLaplaceIters_
scalar tolerance_
volVectorField ma_
volVectorField source_
autoPtr< boundaryVectorField > meshMovementSensPtr_
const autoPtr< adjointEikonalSolver > & adjointEikonalSolverPtr_
Detailed Description
Solver of the adjoint to the Laplace grid displacement equation.
Reference:
    Kavvadias, I., Papoutsis-Kiachagias, E., & Giannakoglou, K. (2015).
    On the proper treatment of grid sensitivities in continuous adjoint
    methods for shape optimization.
    Journal of Computational Physics, 301, 1–18.
    http://doi.org/10.1016/j.jcp.2015.08.012
Source files
adjointMeshMovementSolverIncompressible.H
adjointMeshMovementSolver.C
Definition at line 64 of file adjointMeshMovementSolverIncompressible.H.
Constructor & Destructor Documentation
adjointMeshMovementSolver()
adjointMeshMovementSolver (const fvMesh & mesh, const dictionary & dict, Foam::incompressible::adjointSensitivity & adjointSensitivity, const labelHashSet & sensitivityPatchIDs, const autoPtr< adjointEikonalSolver > & adjointEikonalSolverPtr)
Definition at line 51 of file adjointMeshMovementSolverIncompressible.C.
References adjointMeshMovementSolver::read().
~adjointMeshMovementSolver()
virtual ~adjointMeshMovementSolver () virtual default
Member Function Documentation
read()
void read () protected
Definition at line 42 of file adjointMeshMovementSolverIncompressible.C.
References adjointMeshMovementSolver::dict_, e, dictionary::getOrDefault(), adjointMeshMovementSolver::nLaplaceIters_, and adjointMeshMovementSolver::tolerance_.
Referenced by adjointMeshMovementSolver::adjointMeshMovementSolver(), and adjointMeshMovementSolver::solve().
TypeName()
TypeName ("adjointMeshMovementSolver")
readDict()
bool readDict (const dictionary & dict) virtual
Definition at line 107 of file adjointMeshMovementSolverIncompressible.C.
References dict, adjointMeshMovementSolver::dict_, and dictionary::subOrEmptyDict().
accumulateIntegrand()
void accumulateIntegrand (const scalar dt)
Definition at line 115 of file adjointMeshMovementSolverIncompressible.C.
References adjointSensitivity::adjointMeshMovementSource(), adjointMeshMovementSolver::adjointSensitivity_, and adjointMeshMovementSolver::source_.
solve()
void solve ()
Definition at line 125 of file adjointMeshMovementSolverIncompressible.C.
References adjointMeshMovementSolver::adjointEikonalSolverPtr_, GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), Foam::fvc::div(), Foam::endl(), Foam::gMax(), Foam::Info, Foam::fvm::laplacian(), adjointMeshMovementSolver::ma_, Foam::mag(), adjointMeshMovementSolver::mesh_, adjointMeshMovementSolver::nLaplaceIters_, adjointMeshMovementSolver::read(), Foam::solve(), adjointMeshMovementSolver::source_, T, adjointMeshMovementSolver::tolerance_, and regIOobject::write().
reset()
void reset ()
Definition at line 169 of file adjointMeshMovementSolverIncompressible.C.
References DimensionedField< Type, GeoMesh >::dimensions(), adjointMeshMovementSolver::meshMovementSensPtr_, adjointMeshMovementSolver::source_, Foam::Zero, and VectorSpace< Form, Cmpt, Ncmpts >::zero.
meshMovementSensitivities()
boundaryVectorField & meshMovementSensitivities ()
Definition at line 176 of file adjointMeshMovementSolverIncompressible.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), Foam::endl(), Foam::Info, adjointMeshMovementSolver::ma_, adjointMeshMovementSolver::meshMovementSensPtr_, and adjointMeshMovementSolver::sensitivityPatchIDs_.
ma()
const volVectorField & ma ()
Definition at line 192 of file adjointMeshMovementSolverIncompressible.C.
References adjointMeshMovementSolver::ma_.
Member Data Documentation
mesh_
const fvMesh& mesh_ protected
Definition at line 70 of file adjointMeshMovementSolverIncompressible.H.
Referenced by adjointMeshMovementSolver::solve().
dict_
dictionary dict_ protected
Definition at line 71 of file adjointMeshMovementSolverIncompressible.H.
Referenced by adjointMeshMovementSolver::read(), and adjointMeshMovementSolver::readDict().
adjointSensitivity_
Foam::incompressible::adjointSensitivity& adjointSensitivity_ protected
Definition at line 72 of file adjointMeshMovementSolverIncompressible.H.
Referenced by adjointMeshMovementSolver::accumulateIntegrand().
sensitivityPatchIDs_
const labelHashSet& sensitivityPatchIDs_ protected
Definition at line 73 of file adjointMeshMovementSolverIncompressible.H.
Referenced by adjointMeshMovementSolver::meshMovementSensitivities().
nLaplaceIters_
label nLaplaceIters_ protected
Definition at line 74 of file adjointMeshMovementSolverIncompressible.H.
Referenced by adjointMeshMovementSolver::read(), and adjointMeshMovementSolver::solve().
tolerance_
scalar tolerance_ protected
Definition at line 75 of file adjointMeshMovementSolverIncompressible.H.
Referenced by adjointMeshMovementSolver::read(), and adjointMeshMovementSolver::solve().
ma_
volVectorField ma_ protected
Definition at line 76 of file adjointMeshMovementSolverIncompressible.H.
Referenced by adjointMeshMovementSolver::ma(), adjointMeshMovementSolver::meshMovementSensitivities(), and adjointMeshMovementSolver::solve().
source_
volVectorField source_ protected
Definition at line 77 of file adjointMeshMovementSolverIncompressible.H.
Referenced by adjointMeshMovementSolver::accumulateIntegrand(), adjointMeshMovementSolver::reset(), and adjointMeshMovementSolver::solve().
meshMovementSensPtr_
autoPtr<boundaryVectorField> meshMovementSensPtr_ protected
Definition at line 80 of file adjointMeshMovementSolverIncompressible.H.
Referenced by adjointMeshMovementSolver::meshMovementSensitivities(), and adjointMeshMovementSolver::reset().
adjointEikonalSolverPtr_
const autoPtr<adjointEikonalSolver>& adjointEikonalSolverPtr_ protected
Definition at line 81 of file adjointMeshMovementSolverIncompressible.H.
Referenced by adjointMeshMovementSolver::solve().
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/optimisation/adjointSensitivity/incompressible/adjointMeshMovementSolver/adjointMeshMovementSolverIncompressible.H
src/optimisation/adjointOptimisation/adjoint/optimisation/adjointSensitivity/incompressible/adjointMeshMovementSolver/adjointMeshMovementSolverIncompressible.C