OpenFOAM: hierarchGeomDecomp Class Reference
hierarchGeomDecomp Class Reference
Does hierarchical decomposition of points, selectable as hierarchical.
#include <hierarchGeomDecomp.H>
Public Member Functions
hierarchGeomDecomp (const hierarchGeomDecomp &)=delete
void operator= (const hierarchGeomDecomp &)=delete
TypeName ("hierarchical")
hierarchGeomDecomp (const dictionary &decompDict, const word &regionName="")
virtual ~hierarchGeomDecomp ()=default
virtual bool parallelAware () const
virtual labelList decompose (const pointField &, const scalarField &weights) const
virtual labelList decompose (const pointField &) const
virtual labelList decompose (const polyMesh &mesh, const pointField &cc, const scalarField &cWeights) const
virtual labelList decompose (const polyMesh &mesh, const pointField &cc) const
virtual labelList decompose (const labelListList &globalCellCells, const pointField &cc, const scalarField &cWeights) const
virtual labelList decompose (const labelListList &globalCellCells, const pointField &cc) const
Public Member Functions inherited from geomDecomp
geomDecomp (const word &derivedType, const dictionary &decompDict, int select=selectionType::DEFAULT)
geomDecomp (const word &derivedType, const dictionary &decompDict, const word &regionName, int select=selectionType::DEFAULT)
Public Member Functions inherited from decompositionMethod
TypeName ("decompositionMethod")
declareRunTimeSelectionTable (autoPtr, decompositionMethod, dictionary,(const dictionary &decompDict, const word &regionName),(decompDict, regionName))
decompositionMethod (const dictionary &decompDict, const word &regionName="")
virtual ~decompositionMethod ()=default
label nDomains () const noexcept
virtual labelList decompose (const polyMesh &mesh, const labelList &cellToRegion, const pointField &regionPoints, const scalarField &regionWeights) const
virtual labelList decompose (const polyMesh &mesh, const labelList &cellToRegion, const pointField &regionPoints) const
void setConstraints (const polyMesh &mesh, boolList &blockedFace, PtrList< labelList > &specifiedProcessorFaces, labelList &specifiedProcessor, List< labelPair > &explicitConnections) const
void applyConstraints (const polyMesh &mesh, const boolList &blockedFace, const PtrList< labelList > &specifiedProcessorFaces, const labelList &specifiedProcessor, const List< labelPair > &explicitConnections, labelList &finalDecomp) const
virtual labelList decompose (const polyMesh &mesh, const scalarField &cellWeights, const boolList &blockedFace, const PtrList< labelList > &specifiedProcessorFaces, const labelList &specifiedProcessor, const List< labelPair > &explicitConnections) const
labelList decompose (const polyMesh &mesh, const scalarField &cWeights) const
Additional Inherited Members
Static Public Member Functions inherited from decompositionMethod
static label nDomains (const dictionary &decompDict, const word &regionName="")
static const dictionary & optionalRegionDict (const dictionary &decompDict, const word &regionName)
static autoPtr< decompositionMethod > New (const dictionary &decompDict, const word &regionName="")
static void calcCellCells (const polyMesh &mesh, const labelList &agglom, const label nLocalCoarse, const bool global, CompactListList< label > &cellCells)
static void calcCellCells (const polyMesh &mesh, const labelList &agglom, const label nLocalCoarse, const bool parallel, CompactListList< label > &cellCells, CompactListList< scalar > &cellCellWeights)
Protected Types inherited from decompositionMethod
enum selectionType { DEFAULT = 0 , EXACT = 1 , MANDATORY = 2 , NULL_DICT = 4 }
Protected Member Functions inherited from geomDecomp
tmp< pointField > adjustPoints (const pointField &) const
void checkDecompositionDirections (const Vector< label > &) const
Protected Member Functions inherited from decompositionMethod
const dictionary & findCoeffsDict (const word &coeffsName, int select=selectionType::DEFAULT) const
Static Protected Member Functions inherited from decompositionMethod
static const dictionary & findCoeffsDict (const dictionary &dict, const word &coeffsName, int select=selectionType::DEFAULT)
Protected Attributes inherited from geomDecomp
Vector< label > n_
Vector< direction > order_
const dictionary & coeffsDict_
Protected Attributes inherited from decompositionMethod
const dictionary & decompDict_
const dictionary & decompRegionDict_
label nDomains_
PtrList< decompositionConstraint > constraints_
Detailed Description
Does hierarchical decomposition of points, selectable as hierarchical.
Works by first sorting the points in x direction into equal sized bins, then in y direction and finally in z direction.
Uses single array to hold decomposition which is indexed as if it is a 3 dimensional array:
finalDecomp[i,j,k] is indexed as
i*n[0]*n[1] + j*n[1] + k
E.g. if we're sorting 'xyz': the first sort (over the x-component) determines in which x-domain the point goes. Then for each of the x-domains the points are sorted in y direction and each individual x-domain gets split into three y-domains. And similar for the z-direction.
Since the domains are of equal size the maximum difference in size is n[0]*n[1] (or n[1]*n[2]?) (small anyway)
Method coefficients:
Property Description Required Default
n (nx ny nz) yes
order order of operation no xyz
delta delta (jitter) for rotation matrix no 0.001
transform cartesian coordinate transformation no
Source files
hierarchGeomDecomp.H
hierarchGeomDecomp.C
Definition at line 97 of file hierarchGeomDecomp.H.
Constructor & Destructor Documentation
hierarchGeomDecomp() [1/2]
hierarchGeomDecomp (const hierarchGeomDecomp &) delete
hierarchGeomDecomp() [2/2]
hierarchGeomDecomp (const dictionary & decompDict, const word & regionName = "") explicit
Definition at line 670 of file hierarchGeomDecomp.C.
~hierarchGeomDecomp()
virtual ~hierarchGeomDecomp () virtual default
Member Function Documentation
operator=()
void operator= (const hierarchGeomDecomp &) delete
TypeName()
TypeName ("hierarchical")
parallelAware()
virtual bool parallelAware () const inline virtual
Implements decompositionMethod.
Definition at line 213 of file hierarchGeomDecomp.H.
decompose() [1/6]
Foam::labelList decompose (const pointField & points, const scalarField & weights) const virtual
Implements geomDecomp.
Definition at line 723 of file hierarchGeomDecomp.C.
References e, Foam::endl(), Foam::identity(), Foam::max(), points, Foam::returnReduce(), UPtrList< T >::size(), WarningInFunction, and Foam::Zero.
Referenced by hierarchGeomDecomp::decompose(), hierarchGeomDecomp::decompose(), hierarchGeomDecomp::decompose(), and hierarchGeomDecomp::decompose().
decompose() [2/6]
Foam::labelList decompose (const pointField & points) const virtual
Implements geomDecomp.
Definition at line 682 of file hierarchGeomDecomp.C.
References e, Foam::endl(), Foam::identity(), Foam::max(), points, Foam::returnReduce(), UPtrList< T >::size(), WarningInFunction, and Foam::Zero.
decompose() [3/6]
virtual labelList decompose (const polyMesh & mesh, const pointField & cc, const scalarField & cWeights) const inline virtual
Implements decompositionMethod.
Definition at line 233 of file hierarchGeomDecomp.H.
References geomDecomp::checkDecompositionDirections(), hierarchGeomDecomp::decompose(), and mesh.
decompose() [4/6]
virtual labelList decompose (const polyMesh & mesh, const pointField & cc) const inline virtual
Reimplemented from decompositionMethod.
Definition at line 247 of file hierarchGeomDecomp.H.
References geomDecomp::checkDecompositionDirections(), hierarchGeomDecomp::decompose(), and mesh.
decompose() [5/6]
virtual labelList decompose (const labelListList & globalCellCells, const pointField & cc, const scalarField & cWeights) const inline virtual
Implements decompositionMethod.
Definition at line 264 of file hierarchGeomDecomp.H.
References hierarchGeomDecomp::decompose().
decompose() [6/6]
virtual labelList decompose (const labelListList & globalCellCells, const pointField & cc) const inline virtual
Reimplemented from decompositionMethod.
Definition at line 274 of file hierarchGeomDecomp.H.
References hierarchGeomDecomp::decompose().
The documentation for this class was generated from the following files:
src/parallel/decompose/decompositionMethods/hierarchGeomDecomp/hierarchGeomDecomp.H
src/parallel/decompose/decompositionMethods/hierarchGeomDecomp/hierarchGeomDecomp.C