OpenFOAM: polyModifyFace Class Reference
polyModifyFace Class Reference
Class describing modification of a face.
#include <polyModifyFace.H>
Public Member Functions
TypeName ("modifyFace")
polyModifyFace ()
polyModifyFace (const face &f, const label faceID, const label owner, const label neighbour, const bool flipFaceFlux, const label patchID, const bool removeFromZone, const label zoneID, const bool zoneFlip)
virtual autoPtr< topoAction > clone () const
const face & newFace () const
label faceID () const
label owner () const
label neighbour () const
bool flipFaceFlux () const
bool isInPatch () const
label patchID () const
bool isInZone () const
bool onlyInZone () const
bool removeFromZone () const
label zoneID () const
label zoneFlip () const
Public Member Functions inherited from topoAction
TypeName ("topoAction")
topoAction ()
virtual ~topoAction ()=default
Detailed Description
Class describing modification of a face.
Definition at line 44 of file polyModifyFace.H.
Constructor & Destructor Documentation
polyModifyFace() [1/2]
polyModifyFace () inline
Definition at line 89 of file polyModifyFace.H.
Referenced by polyModifyFace::clone().
polyModifyFace() [2/2]
polyModifyFace (const face & f, const label faceID, const label owner, const label neighbour, const bool flipFaceFlux, const label patchID, const bool removeFromZone, const label zoneID, const bool zoneFlip) inline
Definition at line 103 of file polyModifyFace.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, Foam::min(), UList< T >::size(), and polyModifyFace::zoneFlip().
Member Function Documentation
TypeName()
TypeName ("modifyFace")
clone()
virtual autoPtr< topoAction > clone () const inline virtual
Implements topoAction.
Definition at line 183 of file polyModifyFace.H.
References polyModifyFace::polyModifyFace().
newFace()
const face & newFace () const inline
Definition at line 194 of file polyModifyFace.H.
faceID()
label faceID () const inline
Definition at line 200 of file polyModifyFace.H.
owner()
label owner () const inline
Definition at line 206 of file polyModifyFace.H.
neighbour()
label neighbour () const inline
Definition at line 212 of file polyModifyFace.H.
flipFaceFlux()
bool flipFaceFlux () const inline
Definition at line 218 of file polyModifyFace.H.
isInPatch()
bool isInPatch () const inline
Definition at line 224 of file polyModifyFace.H.
patchID()
label patchID () const inline
Definition at line 230 of file polyModifyFace.H.
isInZone()
bool isInZone () const inline
Definition at line 236 of file polyModifyFace.H.
onlyInZone()
bool onlyInZone () const inline
Definition at line 242 of file polyModifyFace.H.
removeFromZone()
bool removeFromZone () const inline
Definition at line 247 of file polyModifyFace.H.
zoneID()
label zoneID () const inline
Definition at line 253 of file polyModifyFace.H.
zoneFlip()
label zoneFlip () const inline
Definition at line 259 of file polyModifyFace.H.
Referenced by polyModifyFace::polyModifyFace().
The documentation for this class was generated from the following file:
src/meshTools/polyTopoChange/modifyObject/polyModifyFace.H