OpenFOAM: atmBoundaryLayerInletOmegaFvPatchScalarField Class Reference
atmBoundaryLayerInletOmegaFvPatchScalarField Class Reference
#include <atmBoundaryLayerInletOmegaFvPatchScalarField.H>
Public Member Functions
TypeName ("atmBoundaryLayerInletOmega")
atmBoundaryLayerInletOmegaFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
atmBoundaryLayerInletOmegaFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
atmBoundaryLayerInletOmegaFvPatchScalarField (const atmBoundaryLayerInletOmegaFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
virtual tmp< fvPatchScalarField > clone () const
atmBoundaryLayerInletOmegaFvPatchScalarField (const atmBoundaryLayerInletOmegaFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual void updateCoeffs ()
virtual void autoMap (const fvPatchFieldMapper &)
virtual void rmap (const fvPatchScalarField &, const labelList &)
virtual void write (Ostream &) const
Public Member Functions inherited from atmBoundaryLayer
atmBoundaryLayer (const Time &time, const polyPatch &pp)
atmBoundaryLayer (const Time &time, const polyPatch &pp, const dictionary &dict)
atmBoundaryLayer (const atmBoundaryLayer &abl, const fvPatch &patch, const fvPatchFieldMapper &mapper)
atmBoundaryLayer (const atmBoundaryLayer &)
vector flowDir () const
vector zDir () const
tmp< scalarField > Ustar (const scalarField &z0) const
void autoMap (const fvPatchFieldMapper &)
void rmap (const atmBoundaryLayer &, const labelList &)
tmp< vectorField > U (const vectorField &pCf) const
tmp< scalarField > k (const vectorField &pCf) const
tmp< scalarField > epsilon (const vectorField &pCf) const
tmp< scalarField > omega (const vectorField &pCf) const
void write (Ostream &) const
Additional Inherited Members
Protected Attributes inherited from atmBoundaryLayer
bool initABL_
Detailed Description
Definition at line 149 of file atmBoundaryLayerInletOmegaFvPatchScalarField.H.
Constructor & Destructor Documentation
atmBoundaryLayerInletOmegaFvPatchScalarField() [1/4]
atmBoundaryLayerInletOmegaFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 34 of file atmBoundaryLayerInletOmegaFvPatchScalarField.C.
atmBoundaryLayerInletOmegaFvPatchScalarField() [2/4]
atmBoundaryLayerInletOmegaFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 46 of file atmBoundaryLayerInletOmegaFvPatchScalarField.C.
References dict, atmBoundaryLayer::initABL_, IOobjectOption::MUST_READ, atmBoundaryLayer::omega(), and Field< scalar >::operator=().
atmBoundaryLayerInletOmegaFvPatchScalarField() [3/4]
atmBoundaryLayerInletOmegaFvPatchScalarField (const atmBoundaryLayerInletOmegaFvPatchScalarField & psf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 75 of file atmBoundaryLayerInletOmegaFvPatchScalarField.C.
atmBoundaryLayerInletOmegaFvPatchScalarField() [4/4]
atmBoundaryLayerInletOmegaFvPatchScalarField (const atmBoundaryLayerInletOmegaFvPatchScalarField & psf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 89 of file atmBoundaryLayerInletOmegaFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("atmBoundaryLayerInletOmega")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 189 of file atmBoundaryLayerInletOmegaFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 205 of file atmBoundaryLayerInletOmegaFvPatchScalarField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 103 of file atmBoundaryLayerInletOmegaFvPatchScalarField.C.
References atmBoundaryLayer::omega().
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Definition at line 116 of file atmBoundaryLayerInletOmegaFvPatchScalarField.C.
References atmBoundaryLayer::autoMap().
rmap()
void rmap (const fvPatchScalarField & psf, const labelList & addr) virtual
Definition at line 126 of file atmBoundaryLayerInletOmegaFvPatchScalarField.C.
References atmBoundaryLayer::rmap().
write()
void write (Ostream & os) const virtual
Definition at line 141 of file atmBoundaryLayerInletOmegaFvPatchScalarField.C.
References os(), atmBoundaryLayer::write(), fvPatchField< Type >::write(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/atmosphericModels/derivedFvPatchFields/atmBoundaryLayerInletOmega/atmBoundaryLayerInletOmegaFvPatchScalarField.H
src/atmosphericModels/derivedFvPatchFields/atmBoundaryLayerInletOmega/atmBoundaryLayerInletOmegaFvPatchScalarField.C