OpenFOAM: SRFModel Class Reference
SRFModel Class Reference
Top level model for single rotating frame.
#include <SRFModel.H>
Public Member Functions
TypeName ("SRFModel")
declareRunTimeSelectionTable (autoPtr, SRFModel, dictionary,(const volVectorField &Urel),(Urel))
SRFModel (const word &type, const volVectorField &Urel)
virtual ~SRFModel ()
virtual bool read ()
const dimensionedVector & origin () const
const vector & axis () const
const dimensionedVector & omega () const
tmp< volVectorField::Internal > Fcoriolis () const
tmp< volVectorField::Internal > Fcentrifugal () const
tmp< volVectorField::Internal > Su () const
vectorField velocity (const vectorField &positions) const
tmp< volVectorField > U () const
tmp< volVectorField > Uabs () const
Public Member Functions inherited from IOdictionary
IOdictionary (const IOobject &io, const dictionary *fallback=nullptr)
IOdictionary (const IOobject &io, const dictionary &dict)
IOdictionary (const IOobject &io, const word &wantedType, const dictionary *fallback=nullptr)
IOdictionary (const IOobject &io, Istream &is)
virtual ~IOdictionary ()=default
virtual bool global () const
virtual fileName filePath () const
Public Member Functions inherited from baseIOdictionary
TypeName ("dictionary")
baseIOdictionary (const baseIOdictionary &)=default
baseIOdictionary (baseIOdictionary &&)=default
virtual ~baseIOdictionary ()=default
baseIOdictionary (const IOobject &io, const dictionary *fallback=nullptr)
baseIOdictionary (const IOobject &io, const dictionary &dict)
baseIOdictionary (const IOobject &io, Istream &is)
const word & name () const
virtual bool readData (Istream &)
virtual bool writeData (Ostream &) const
void operator= (const baseIOdictionary &rhs)
void operator= (const dictionary &rhs)
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
regIOobject (const IOobject &io, const bool isTimeObject=false)
regIOobject (const regIOobject &rio)
regIOobject (const regIOobject &rio, bool registerCopy)
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
regIOobject (const IOobject &io, const regIOobject &rio)
virtual ~regIOobject ()
bool checkIn ()
bool checkOut ()
virtual void addWatch ()
bool registered () const noexcept
bool ownedByRegistry () const noexcept
bool store ()
void release (const bool unregister=false) noexcept
label eventNo () const noexcept
label & eventNo () noexcept
bool upToDate (const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
void setUpToDate ()
virtual void rename (const word &newName)
const dictionary * findMetaData () const noexcept
dictionary & getMetaData () noexcept
void removeMetaData ()
virtual void updateMetaData ()
bool headerOk ()
Istream & readStream (const word &, const bool readOnProc=true)
void close ()
virtual label addWatch (const fileName &)
const labelList & watchIndices () const noexcept
labelList & watchIndices () noexcept
virtual bool modified () const
virtual bool readIfModified ()
virtual bool writeObject (IOstreamOption streamOpt, const bool writeOnProc) const
virtual bool write (const bool writeOnProc=true) const
void operator= (const IOobject &io)
virtual bool writeObject (IOstreamOption::streamFormat fmt, IOstreamOption::versionNumber ver, IOstreamOption::compressionType cmp, const bool writeOnProc) const
Public Member Functions inherited from IOobject
TypeName ("IOobject")
IOobject (const IOobject &)=default
virtual ~IOobject ()=default
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const fileName &path, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const fileName &path, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const IOobject &io, const objectRegistry &registry)
IOobject (const IOobject &io, const word &name)
IOobject (const IOobject &io, const word &name, const fileName &local)
IOobject (const IOobject &io, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt)
IOobject (const IOobject &io, IOobjectOption::registerOption regOpt)
autoPtr< IOobject > clone () const
autoPtr< IOobject > clone (const objectRegistry &registry) const
const objectRegistry & db () const noexcept
const Time & time () const noexcept
const word & name () const noexcept
const word & headerClassName () const noexcept
word & headerClassName () noexcept
const string & note () const noexcept
string & note () noexcept
unsigned labelByteSize () const noexcept
unsigned scalarByteSize () const noexcept
void resetHeader (const word &newName=word::null)
bool hasHeaderClass () const noexcept
template<class Type >
bool isHeaderClass () const
template<class Type >
bool isHeaderClassName () const
word group () const
word member () const
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const noexcept
fileName & instance () noexcept
const fileName & local () const noexcept
fileName path () const
fileName path (const word &instance, const fileName &local=fileName::null) const
fileName objectPath () const
fileName objectRelPath () const
fileName localFilePath (const word &typeName, const bool search=true) const
fileName globalFilePath (const word &typeName, const bool search=true) const
IOstreamOption parseHeader (const dictionary &headerDict)
bool readHeader (Istream &is)
bool readHeader (dictionary &headerDict, Istream &is)
template<class Type >
bool typeHeaderOk (const bool checkType=true, const bool search=true, const bool verbose=true)
template<class Type >
void warnNoRereading () const
bool writeHeader (Ostream &os) const
bool writeHeader (Ostream &os, const word &objectType) const
void writeHeader (dictionary &dict, IOstreamOption streamOpt) const
void writeHeader (dictionary &dict, const word &objectType, IOstreamOption streamOpt) const
bool good () const noexcept
bool bad () const noexcept
InfoProxy< IOobject > info () const noexcept
void operator= (const IOobject &io)
template<>
bool isHeaderClass () const
template<class StringType >
Foam::word groupName (StringType base, const word &group)
Public Member Functions inherited from IOobjectOption
constexpr IOobjectOption (readOption rOpt=readOption::NO_READ, writeOption wOpt=writeOption::NO_WRITE, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (readOption rOpt, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (writeOption wOpt, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (registerOption registerObject, bool globalObject=false) noexcept
constexpr IOobjectOption (readOption rOpt, writeOption wOpt, bool registerObject, bool globalObject=false) noexcept
constexpr IOobjectOption (bool registerObject, bool globalObject=false) noexcept
readOption readOpt () const noexcept
readOption readOpt (readOption opt) noexcept
writeOption writeOpt () const noexcept
writeOption writeOpt (writeOption opt) noexcept
bool registerObject () const noexcept
bool registerObject (bool on) noexcept
bool globalObject () const noexcept
bool globalObject (bool on) noexcept
bool isAnyRead () const noexcept
bool isReadRequired () const noexcept
bool isReadOptional () const noexcept
readOption & readOpt () noexcept
writeOption & writeOpt () noexcept
bool & registerObject () noexcept
bool & globalObject () noexcept
Public Member Functions inherited from dictionary
ClassName ("dictionary")
dictionary ()
dictionary (const fileName &name)
dictionary (const fileName &name, const dictionary &parentDict, Istream &is, bool keepHeader=false)
dictionary (Istream &is)
dictionary (Istream &is, bool keepHeader)
dictionary (const dictionary &parentDict, const dictionary &dict)
dictionary (const dictionary &dict)
dictionary (const dictionary *dict)
dictionary (const dictionary &parentDict, dictionary &&dict)
dictionary (dictionary &&dict)
autoPtr< dictionary > clone () const
virtual ~dictionary ()
const fileName & name () const noexcept
fileName & name () noexcept
word dictName () const
fileName relativeName (const bool caseTag=false) const
bool isNullDict () const noexcept
const dictionary & parent () const noexcept
const dictionary & topDict () const
label startLineNumber () const
label endLineNumber () const
SHA1Digest digest () const
tokenList tokens () const
const entry * findEntry (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
entry * findEntry (const word &keyword, enum keyType::option matchOpt=keyType::REGEX)
bool found (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
const entry * findScoped (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
const dictionary * findDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
dictionary * findDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX)
bool isDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
const entry & lookupEntry (const word &keyword, enum keyType::option matchOpt) const
ITstream & lookup (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
template<class T >
T get (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
template<class T >
T getOrDefault (const word &keyword, const T &deflt, enum keyType::option matchOpt=keyType::REGEX) const
template<class T >
T getOrAdd (const word &keyword, const T &deflt, enum keyType::option matchOpt=keyType::REGEX)
template<class T >
bool readEntry (const word &keyword, T &val, enum keyType::option matchOpt=keyType::REGEX, IOobjectOption::readOption readOpt=IOobjectOption::MUST_READ) const
template<class T >
bool readIfPresent (const word &keyword, T &val, enum keyType::option matchOpt=keyType::REGEX) const
template<class T , class Predicate >
T getCheck (const word &keyword, const Predicate &pred, enum keyType::option matchOpt=keyType::REGEX) const
template<class T , class Predicate >
T getCheckOrDefault (const word &keyword, const T &deflt, const Predicate &pred, enum keyType::option matchOpt=keyType::REGEX) const
template<class T , class Predicate >
T getCheckOrAdd (const word &keyword, const T &deflt, const Predicate &pred, enum keyType::option matchOpt=keyType::REGEX)
template<class T , class Predicate >
bool readCheck (const word &keyword, T &val, const Predicate &pred, enum keyType::option matchOpt=keyType::REGEX, IOobjectOption::readOption readOpt=IOobjectOption::MUST_READ) const
template<class T , class Predicate >
bool readCheckIfPresent (const word &keyword, T &val, const Predicate &pred, enum keyType::option matchOpt=keyType::REGEX) const
const dictionary & subDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
dictionary & subDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX)
dictionary & subDictOrAdd (const word &keyword, enum keyType::option matchOpt=keyType::REGEX)
dictionary subOrEmptyDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX, const bool mandatory=false) const
const dictionary & optionalSubDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
wordList toc () const
wordList sortedToc () const
template<class Compare >
wordList sortedToc (const Compare &comp) const
List< keyType > keys (bool patterns=false) const
bool substituteKeyword (const word &keyword, bool mergeEntry=false)
bool substituteScopedKeyword (const word &keyword, bool mergeEntry=false)
entry * add (entry *entryPtr, bool mergeEntry=false)
entry * add (const entry &e, bool mergeEntry=false)
entry * add (const keyType &k, const word &v, bool overwrite=false)
entry * add (const keyType &k, const string &v, bool overwrite=false)
entry * add (const keyType &k, const label v, bool overwrite=false)
entry * add (const keyType &k, const scalar v, bool overwrite=false)
entry * add (const keyType &k, const dictionary &d, bool mergeEntry=false)
template<class T >
entry * add (const keyType &k, const T &v, bool overwrite=false)
entry * set (entry *entryPtr)
entry * set (const entry &e)
entry * set (const keyType &k, const dictionary &v)
template<class T >
entry * set (const keyType &k, const T &v)
bool remove (const word &keyword)
bool changeKeyword (const keyType &oldKeyword, const keyType &newKeyword, bool overwrite=false)
bool merge (const dictionary &dict)
void clear ()
void transfer (dictionary &dict)
void checkITstream (const ITstream &is, const word &keyword) const
bool read (Istream &is)
bool read (Istream &is, bool keepHeader)
void writeEntry (Ostream &os) const
void writeEntry (const keyType &keyword, Ostream &os) const
void writeEntries (Ostream &os, const bool extraNewLine=false) const
void write (Ostream &os, const bool subDict=true) const
const_searcher csearch (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
const_searcher search (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
searcher search (const word &keyword, enum keyType::option matchOpt=keyType::REGEX)
const_searcher csearchScoped (const word &keyword, enum keyType::option matchOpt) const
const_searcher searchScoped (const word &keyword, enum keyType::option matchOpt) const
searcher searchScoped (const word &keyword, enum keyType::option matchOpt)
const dictionary * cfindScopedDict (const fileName &dictPath) const
const dictionary * findScopedDict (const fileName &dictPath) const
dictionary * findScopedDict (const fileName &dictPath)
dictionary * makeScopedDict (const fileName &dictPath)
const_searcher csearchCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, enum keyType::option matchOpt=keyType::REGEX) const
const entry * findCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, enum keyType::option matchOpt) const
bool foundCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, enum keyType::option matchOpt=keyType::REGEX) const
const entry & lookupEntryCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, enum keyType::option matchOpt) const
ITstream & lookupCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, enum keyType::option matchOpt=keyType::REGEX) const
template<class T >
T getCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, enum keyType::option matchOpt=keyType::REGEX) const
template<class T >
T getOrDefaultCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, const T &deflt, enum keyType::option matchOpt=keyType::REGEX) const
template<class T >
bool readCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, T &val, enum keyType::option matchOpt=keyType::REGEX, IOobjectOption::readOption readOpt=IOobjectOption::MUST_READ) const
template<class T >
bool readIfPresentCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, T &val, enum keyType::option matchOpt=keyType::REGEX) const
void operator= (const dictionary &rhs)
void operator+= (const dictionary &rhs)
void operator|= (const dictionary &rhs)
void operator<<= (const dictionary &rhs)
bool getBool (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Same as get< bool >(const word&, keyType::option)
label getLabel (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Same as get< label >(const word&, keyType::option)
scalar getScalar (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Same as get< scalar >(const word&, keyType::option)
string getString (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Same as get< string >(const word&, keyType::option)
word getWord (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Same as get< word >(const word&, keyType::option)
fileName getFileName (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Same as get< fileName >(const word&, keyType::option)
template<class T >
T lookupOrDefault (const word &keyword, const T &deflt, enum keyType::option matchOpt=keyType::REGEX) const
template<class T >
T lookupOrAddDefault (const word &keyword, const T &deflt, enum keyType::option matchOpt=keyType::REGEX)
ITstream & operator[] (const word &keyword) const
bool found (const word &keyword, bool recursive, bool patternMatch=true) const
entry * lookupEntryPtr (const word &keyword, bool recursive, bool patternMatch)
const entry * lookupEntryPtr (const word &keyword, bool recursive, bool patternMatch) const
const entry * lookupScopedEntryPtr (const word &keyword, bool recursive, bool patternMatch) const
const dictionary * subDictPtr (const word &keyword) const
dictionary * subDictPtr (const word &keyword)
const entry & lookupEntry (const word &keyword, bool recursive, bool patternMatch) const
ITstream & lookup (const word &keyword, bool recursive, bool patternMatch=true) const
template<class T >
T lookupOrDefault (const word &keyword, const T &deflt, bool recursive, bool patternMatch=true) const
template<class T >
T lookupOrAddDefault (const word &keyword, const T &deflt, bool recursive, bool patternMatch=true)
template<class T >
bool readIfPresent (const word &keyword, T &val, bool recursive, bool patternMatch=true) const
template<class T >
T lookupType (const word &keyword, bool recursive=false, bool patternMatch=true) const
template<class Compare >
Foam::wordList sortedToc (const Compare &comp) const
template<class T >
Foam::entry * add (const keyType &k, const T &v, bool overwrite)
template<class T >
Foam::entry * set (const keyType &k, const T &v)
Public Member Functions inherited from ILList< LListBase, T >
ILList ()=default
ILList (T *item)
ILList (Istream &is)
ILList (const ILList< LListBase, T > &lst)
ILList (ILList< LListBase, T > &&lst)
template<class CloneArg >
ILList (const ILList< LListBase, T > &lst, const CloneArg &cloneArg)
template<class INew >
ILList (Istream &is, const INew &inew)
~ILList ()
void clear ()
void pop_front (label n=1)
bool erase (T *item)
void transfer (ILList< LListBase, T > &lst)
void operator= (const ILList< LListBase, T > &lst)
void operator= (ILList< LListBase, T > &&lst)
Public Member Functions inherited from UILList< LListBase, T >
UILList ()=default
UILList (T *item)
UILList (const UILList< LListBase, T > &list)
T * front ()
const T * front () const
T * back ()
const T * back () const
T * removeHead ()
T * remove (T *item)
T * remove (iterator &iter)
void operator= (const UILList< LListBase, T > &lst)
bool operator== (const UILList< LListBase, T > &lst) const
bool operator!= (const UILList< LListBase, T > &lst) const
Ostream & writeList (Ostream &os, const label shortLen=0) const
iterator begin ()
const_iterator cbegin () const
reverse_iterator rbegin ()
const_reverse_iterator crbegin () const
const_iterator begin () const
const_reverse_iterator rbegin () const
const iterator & end ()
const const_iterator & cend () const
const reverse_iterator & rend ()
const const_reverse_iterator & crend () const
const const_iterator & end () const
const const_reverse_iterator & rend () const
T * first ()
const T * first () const
T * last ()
const T * last () const
Static Public Member Functions
static autoPtr< SRFModel > New (const volVectorField &Urel)
Static Public Member Functions inherited from IOdictionary
static dictionary readContents (const IOobject &io)
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *p)
template<class Type >
static Type & store (autoPtr< Type > &ptr)
template<class Type >
static Type & store (autoPtr< Type > &&ptr)
template<class Type >
static Type & store (refPtr< Type > &ptr)
template<class Type >
static Type & store (refPtr< Type > &&ptr)
template<class Type >
static Type & store (tmp< Type > &ptr)
template<class Type >
static Type & store (tmp< Type > &&ptr)
Static Public Member Functions inherited from IOobject
static bool bannerEnabled () noexcept
static bool bannerEnabled (bool on) noexcept
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
template<class StringType >
static word groupName (StringType base, const word &group)
static word group (const word &name)
static word member (const word &name)
static word scopedName (const std::string &scope, const word &name)
static IOobject selectIO (const IOobject &io, const fileName &altFile, const word &ioName="")
static Ostream & writeBanner (Ostream &os, const bool noSyntaxHint=false)
static Ostream & writeDivider (Ostream &os)
static Ostream & writeEndDivider (Ostream &os)
Static Public Member Functions inherited from IOobjectOption
static bool isAnyRead (readOption opt) noexcept
static bool isReadRequired (readOption opt) noexcept
static bool isReadOptional (readOption opt) noexcept
static readOption lazierRead (readOption opt) noexcept
Static Public Member Functions inherited from dictionary
static int reportOptional () noexcept
static int reportOptional (const int level) noexcept
static autoPtr< dictionary > New (Istream &is)
Protected Attributes
const volVectorField & Urel_
const fvMesh & mesh_
dimensionedVector origin_
vector axis_
dictionary SRFModelCoeffs_
dimensionedVector omega_
Additional Inherited Members
Public Types inherited from IOobject
enum objectState : char { GOOD , BAD }
enum fileCheckTypes : char { timeStamp , timeStampMaster , inotify , inotifyMaster }
Public Types inherited from IOobjectOption
enum readOption : unsigned char {
NO_READ = 0 , MUST_READ = 0x1 , READ_MODIFIED = 0x3 , MUST_READ_IF_MODIFIED = 0x3 ,
LAZY_READ = 0x4 , READ_IF_PRESENT = 0x4
}
enum writeOption : unsigned char { NO_WRITE = 0 , AUTO_WRITE = 0x10 }
enum registerOption : unsigned char { NO_REGISTER = 0 , REGISTER = 1 }
Public Types inherited from dictionary
typedef Searcher< true > const_searcher
typedef Searcher< false > searcher
Public Types inherited from UILList< LListBase, T >
typedef T value_type
typedef T * pointer
typedef const T * const_pointer
typedef T & reference
typedef const T & const_reference
typedef label size_type
typedef label difference_type
using base_iterator = typename LListBase::iterator
using const_base_iterator = typename LListBase::const_iterator
Public Attributes inherited from dictionary
friend const_searcher
friend searcher
Static Public Attributes inherited from IOobject
static const Enum< fileCheckTypes > fileCheckTypesNames
static char scopeSeparator
static fileCheckTypes fileModificationChecking
static float fileModificationSkew
static int maxFileModificationPolls
Static Public Attributes inherited from dictionary
static int writeOptionalEntries
static const dictionary null
static refPtr< OSstream > reportingOutput
Protected Member Functions inherited from regIOobject
bool readHeaderOk (const IOstreamOption::streamFormat fmt, const word &typeName)
Protected Member Functions inherited from IOobject
void setBad (const string &s)
Static Protected Member Functions inherited from IOobject
static void writeHeaderContent (Ostream &os, const IOobject &io, const word &objectType, const dictionary *metaDataDict=nullptr)
static void writeHeaderContent (dictionary &dict, const IOobject &io, const word &objectType, IOstreamOption streamOpt, const dictionary *metaDataDict=nullptr)
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
Detailed Description
Top level model for single rotating frame.
Steady state only - no time derivatives included
Source files
SRFModel.H
SRFModel.C
Definition at line 61 of file SRFModel.H.
Constructor & Destructor Documentation
SRFModel()
SRFModel (const word & type, const volVectorField & Urel)
Definition at line 38 of file SRFModel.C.
References Foam::dimLength, Foam::dimless, Foam::dimTime, and Foam::normalised().
~SRFModel()
~SRFModel () virtual
Definition at line 66 of file SRFModel.C.
Member Function Documentation
TypeName()
TypeName ("SRFModel")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , SRFModel , dictionary , (const volVectorField &Urel) , (Urel))
New()
Foam::autoPtr< Foam::SRF::SRFModel > New (const volVectorField & Urel) static
Definition at line 26 of file SRFModelNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, Foam::Info, IOobjectOption::MUST_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, and Urel.
read()
bool read () virtual
Reimplemented from regIOobject.
Reimplemented in rpm.
Definition at line 72 of file SRFModel.C.
References regIOobject::read(), and Foam::type().
Referenced by rpm::read().
origin()
const Foam::dimensionedVector & origin () const
Definition at line 93 of file SRFModel.C.
axis()
const Foam::vector & axis () const
Definition at line 99 of file SRFModel.C.
omega()
const Foam::dimensionedVector & omega () const
Definition at line 105 of file SRFModel.C.
Fcoriolis()
Foam::tmp< Foam::DimensionedField< Foam::vector, Foam::volMesh > > Fcoriolis () const
Definition at line 112 of file SRFModel.C.
References IOobjectOption::NO_READ, and IOobjectOption::NO_WRITE.
Fcentrifugal()
Foam::tmp< Foam::DimensionedField< Foam::vector, Foam::volMesh > > Fcentrifugal () const
Definition at line 133 of file SRFModel.C.
References IOobjectOption::NO_READ, and IOobjectOption::NO_WRITE.
Su()
Foam::tmp< Foam::DimensionedField< Foam::vector, Foam::volMesh > > Su () const
Definition at line 154 of file SRFModel.C.
velocity()
Foam::vectorField velocity (const vectorField & positions) const
Definition at line 160 of file SRFModel.C.
U()
Foam::tmp< Foam::volVectorField > U () const
Definition at line 176 of file SRFModel.C.
References IOobjectOption::NO_READ, and IOobjectOption::NO_WRITE.
Uabs()
Foam::tmp< Foam::volVectorField > Uabs () const
Definition at line 197 of file SRFModel.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), forAll, IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef(), and U.
Member Data Documentation
Urel_
const volVectorField& Urel_ protected
Definition at line 71 of file SRFModel.H.
mesh_
const fvMesh& mesh_ protected
Definition at line 74 of file SRFModel.H.
origin_
dimensionedVector origin_ protected
Definition at line 77 of file SRFModel.H.
axis_
vector axis_ protected
Definition at line 80 of file SRFModel.H.
Referenced by rpm::rpm().
SRFModelCoeffs_
dictionary SRFModelCoeffs_ protected
Definition at line 83 of file SRFModel.H.
omega_
dimensionedVector omega_ protected
Definition at line 86 of file SRFModel.H.
Referenced by rpm::rpm().
The documentation for this class was generated from the following files:
src/finiteVolume/cfdTools/general/SRF/SRFModel/SRFModel/SRFModel.H
src/finiteVolume/cfdTools/general/SRF/SRFModel/SRFModel/SRFModel.C
src/finiteVolume/cfdTools/general/SRF/SRFModel/SRFModel/SRFModelNew.C