OpenFOAM: sizeDistribution Class Reference
sizeDistribution Class Reference
This function object calculates and outputs information about the size distribution of the dispersed phase, such as the number density function or its moments. It is designed to be used exclusively with the population balance modeling functionality of the reactingEulerFoam solvers. It can be applied to a specific cellZone or the entire domain.
#include <sizeDistribution.H>
Public Types
enum selectionModeTypes { rtCellZone , rtAll }
enum functionTypes { ftNdf , ftVdf , ftNc , ftMom }
enum abszissaTypes { atDiameter , atVolume }
Public Member Functions
TypeName ("sizeDistribution")
sizeDistribution (const word &name, const Time &runTime, const dictionary &dict)
virtual ~sizeDistribution ()
const dictionary & dict () const
const labelList & cellId () const
const fvMesh & mesh () const
virtual bool read (const dictionary &dict)
virtual bool execute ()
virtual bool write ()
Public Member Functions inherited from fvMeshFunctionObject
TypeName ("fvMeshFunctionObject")
fvMeshFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
fvMeshFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
virtual ~fvMeshFunctionObject ()=default
Public Member Functions inherited from regionFunctionObject
TypeName ("regionFunctionObject")
regionFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
regionFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
virtual ~regionFunctionObject ()=default
template<class ObjectType >
const ObjectType * lookupObjectPtr (const word &fieldName) const
template<class ObjectType >
ObjectType * lookupObjectRefPtr (const word &fieldName) const
Public Member Functions inherited from stateFunctionObject
stateFunctionObject (const word &name, const Time &runTime)
virtual ~stateFunctionObject ()=default
dictionary & propertyDict ()
bool foundProperty (const word &entryName) const
void clearTrigger ()
label getTrigger () const
bool setTrigger (const label triggeri)
bool getDict (const word &entryName, dictionary &dict) const
bool getObjectDict (const word &objectName, const word &entryName, dictionary &dict) const
template<class Type >
Type getProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getProperty (const word &entryName, Type &value) const
template<class Type >
void setProperty (const word &entryName, const Type &value)
template<class Type >
Type getObjectProperty (const word &objectName, const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getObjectProperty (const word &objectName, const word &entryName, Type &value) const
template<class Type >
void setObjectProperty (const word &objectName, const word &entryName, const Type &value)
template<class Type >
void setResult (const word &entryName, const Type &value)
template<class Type >
void setObjectResult (const word &objectName, const word &entryName, const Type &value)
template<class Type >
Type getResult (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
Type getObjectResult (const word &objectName, const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getObjectResult (const word &objectName, const word &entryName, Type &value) const
word resultType (const word &entryName) const
word objectResultType (const word &objectName, const word &entryName) const
wordList objectResultEntries () const
wordList objectResultEntries (const word &objectName) const
void writeResultEntries (Ostream &os) const
void writeResultEntries (const word &objectName, Ostream &os) const
void writeAllResultEntries (Ostream &os) const
Public Member Functions inherited from timeFunctionObject
timeFunctionObject (const word &name, const Time &runTime)
virtual ~timeFunctionObject ()=default
const Time & time () const
objectRegistry & storedObjects ()
const objectRegistry & storedObjects () const
Public Member Functions inherited from functionObject
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name, const bool withNamePrefix=defaultUseNamePrefix)
autoPtr< functionObject > clone () const
virtual ~functionObject ()=default
virtual const word & type () const =0
const word & name () const noexcept
bool useNamePrefix () const noexcept
bool useNamePrefix (bool on) noexcept
virtual bool execute (const label subIndex)
virtual bool end ()
virtual bool adjustTimeStep ()
virtual bool filesModified () const
virtual void updateMesh (const mapPolyMesh &mpm)
virtual void movePoints (const polyMesh &mesh)
Public Member Functions inherited from writeFile
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name="undefined", const bool writeToFile=true)
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name, const dictionary &dict, const bool writeToFile=true)
writeFile (const writeFile &wf)
virtual ~writeFile ()=default
virtual OFstream & file ()
virtual bool writeToFile () const
virtual bool canWriteToFile () const
virtual bool canResetFile () const
virtual bool canWriteHeader () const
virtual label charWidth () const
virtual void writeCommented (Ostream &os, const string &str) const
virtual void writeTabbed (Ostream &os, const string &str) const
virtual void writeHeader (Ostream &os, const string &str) const
virtual void writeCurrentTime (Ostream &os) const
virtual void writeBreak (Ostream &os) const
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
template<class Type >
void writeValue (Ostream &os, const Type &val) const
Static Public Attributes
static const Enum< selectionModeTypes > selectionModeTypeNames_
static const Enum< functionTypes > functionTypeNames_
static const Enum< abszissaTypes > abszissaTypeNames_
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
static bool defaultUseNamePrefix
static word outputPrefix
Static Public Attributes inherited from writeFile
static label addChars = 8
Protected Member Functions
void initialise (const dictionary &dict)
void setCellZoneCells ()
scalar volume () const
void combineFields (scalarField &field)
tmp< scalarField > filterField (const scalarField &field) const
void writeFileHeader (const label i=0)
Protected Member Functions inherited from fvMeshFunctionObject
fvMeshFunctionObject (const fvMeshFunctionObject &)=delete
void operator= (const fvMeshFunctionObject &)=delete
Protected Member Functions inherited from regionFunctionObject
virtual const objectRegistry & obr () const
template<class ObjectType >
bool foundObject (const word &fieldName) const
template<class ObjectType >
const ObjectType * cfindObject (const word &fieldName) const
template<class ObjectType >
const ObjectType * findObject (const word &fieldName) const
template<class ObjectType >
ObjectType * findObject (const word &fieldName)
template<class ObjectType >
ObjectType * getObjectPtr (const word &fieldName) const
template<class ObjectType >
const ObjectType & lookupObject (const word &fieldName) const
template<class ObjectType >
ObjectType & lookupObjectRef (const word &fieldName) const
template<class ObjectType >
bool store (word &fieldName, const tmp< ObjectType > &tfield, bool cacheable=false)
template<class ObjectType >
bool storeInDb (const word &fieldName, const tmp< ObjectType > &tfield, const objectRegistry &obr)
bool writeObject (const word &fieldName)
bool clearObject (const word &fieldName)
void clearObjects (const wordList &objNames)
regionFunctionObject (const regionFunctionObject &)=delete
void operator= (const regionFunctionObject &)=delete
Protected Member Functions inherited from stateFunctionObject
const functionObjects::properties & stateDict () const
functionObjects::properties & stateDict ()
stateFunctionObject (const stateFunctionObject &)=delete
void operator= (const stateFunctionObject &)=delete
Protected Member Functions inherited from timeFunctionObject
void clearOutputObjects (const wordList &objNames)
timeFunctionObject (const timeFunctionObject &)=delete
void operator= (const timeFunctionObject &)=delete
Protected Member Functions inherited from functionObject
word scopedName (const word &name) const
Protected Member Functions inherited from writeFile
void initStream (Ostream &os) const
fileName baseFileDir () const
fileName baseTimeDir () const
fileName filePath (const fileName &fName) const
virtual autoPtr< OFstream > newFile (const fileName &fName) const
virtual autoPtr< OFstream > newFileAtTime (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > newFileAtStartTime (const word &name) const
virtual void resetFile (const word &name)
Omanip< int > valueWidth (const label offset=0) const
void operator= (const writeFile &)=delete
virtual autoPtr< OFstream > createFile (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > createFile (const word &name) const
Protected Attributes
dictionary dict_
selectionModeTypes selectionModeType_
word selectionModeTypeName_
functionTypes functionType_
abszissaTypes abszissaType_
label nCells_
labelList cellId_
scalar volume_
bool writeVolume_
const Foam::diameterModels::populationBalanceModel & popBal_
List< scalar > N_
label momentOrder_
const Switch normalize_
scalar sumN_
scalar sumV_
Protected Attributes inherited from fvMeshFunctionObject
const fvMesh & mesh_
Protected Attributes inherited from regionFunctionObject
word subRegistryName_
const objectRegistry & obr_
const objectRegistry * obrPtr_
Protected Attributes inherited from timeFunctionObject
const Time & time_
Protected Attributes inherited from writeFile
const objectRegistry & fileObr_
const fileName prefix_
word fileName_
autoPtr< OFstream > filePtr_
label writePrecision_
bool writeToFile_
bool updateHeader_
bool writtenHeader_
bool useUserTime_
scalar startTime_
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &runTime, const dictionary &dict)
Public Attributes inherited from functionObject
bool log
Detailed Description
This function object calculates and outputs information about the size distribution of the dispersed phase, such as the number density function or its moments. It is designed to be used exclusively with the population balance modeling functionality of the reactingEulerFoam solvers. It can be applied to a specific cellZone or the entire domain.
Example of function object specification:
box.all.numberDensity.volume.bubbles
{
    type sizeDistribution;
    libs (reactingEulerFoamFunctionObjects);
    writeControl    outputTime;
    writeInterval   1;
    log             true;
    ...
    functionType        numberDensity;
    abszissaType        volume;
    selectionMode       all;
    populationBalanceModel   bubbles;
    normalize           true;
}
Usage
Property Description Required Default value
type type name: sizeDistribution yes
functionType numberDensity, volumeDensity, numberConcentration,
moments yes
abszissaType volume, diameter yes
momentOrder Write moment up to given order no 0
selectionMode Evaluate for cellZone or entire mesh yes
cellZone Required if selectionMode is cellZone
populationBalanceModel Respective populationBalanceModel yes
normalize Normalization no
See also
Foam::diameterModels::populationBalanceModel Foam::functionObject Foam::functionObjects::fvMeshFunctionObject Foam::functionObjects::writeFile
Source files
sizeDistribution.H
sizeDistribution.C
Definition at line 144 of file sizeDistribution.H.
Member Enumeration Documentation
selectionModeTypes
enum selectionModeTypes
Enumerator
rtCellZone
rtAll
Definition at line 155 of file sizeDistribution.H.
functionTypes
enum functionTypes
Enumerator
ftNdf
ftVdf
ftNc
ftMom
Definition at line 166 of file sizeDistribution.H.
abszissaTypes
enum abszissaTypes
Enumerator
atDiameter
atVolume
Definition at line 179 of file sizeDistribution.H.
Constructor & Destructor Documentation
sizeDistribution()
sizeDistribution (const word & name, const Time & runTime, const dictionary & dict)
Definition at line 338 of file sizeDistribution.C.
References sizeDistribution::dict(), functionObject::name(), writeFile::newFileAtStartTime(), sizeDistribution::read(), and writeFile::resetFile().
~sizeDistribution()
~sizeDistribution () virtual
Definition at line 380 of file sizeDistribution.C.
Member Function Documentation
initialise()
void initialise (const dictionary & dict) protected
Definition at line 76 of file sizeDistribution.C.
References sizeDistribution::abszissaType_, sizeDistribution::abszissaTypeNames_, sizeDistribution::atDiameter, sizeDistribution::atVolume, sizeDistribution::dict(), Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, FatalIOErrorInLookup, sizeDistribution::ftMom, sizeDistribution::ftNc, sizeDistribution::ftNdf, sizeDistribution::ftVdf, sizeDistribution::functionType_, sizeDistribution::functionTypeNames_, Foam::Info, functionObject::name(), sizeDistribution::nCells_, Foam::nl, word::null, sizeDistribution::selectionModeType_, sizeDistribution::selectionModeTypeName_, sizeDistribution::selectionModeTypeNames_, sizeDistribution::setCellZoneCells(), functionObject::type(), sizeDistribution::volume(), and sizeDistribution::volume_.
setCellZoneCells()
void setCellZoneCells () protected
Definition at line 161 of file sizeDistribution.C.
References dict, Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, FatalIOErrorInLookup, Foam::identity(), mesh, Foam::nl, word::null, and Foam::returnReduce().
Referenced by sizeDistribution::initialise().
volume()
Foam::scalar volume () const protected
Definition at line 207 of file sizeDistribution.C.
References Foam::gSum(), and mesh.
Referenced by sizeDistribution::initialise().
combineFields()
void combineFields (scalarField & field) protected
Definition at line 213 of file sizeDistribution.C.
References field(), Pstream::gatherList(), UPstream::master(), UPstream::myProcNo(), and UPstream::nProcs().
filterField()
Foam::tmp< Foam::scalarField > filterField (const scalarField & field) const protected
Definition at line 234 of file sizeDistribution.C.
References field().
writeFileHeader()
void writeFileHeader (const label i = 0) protected
Definition at line 243 of file sizeDistribution.C.
References Foam::endl(), forAll, Foam::tab, and Foam::writeHeader().
TypeName()
TypeName ("sizeDistribution")
dict()
const dictionary & dict () const inline
Definition at line 284 of file sizeDistribution.H.
References sizeDistribution::dict_.
Referenced by sizeDistribution::initialise(), and sizeDistribution::sizeDistribution().
cellId()
const labelList & cellId () const inline
Definition at line 290 of file sizeDistribution.H.
References sizeDistribution::cellId_.
mesh()
const fvMesh & mesh () const inline
Definition at line 296 of file sizeDistribution.H.
References regionFunctionObject::obr_.
read()
bool read (const dictionary & dict) virtual
Reimplemented from regionFunctionObject.
Definition at line 386 of file sizeDistribution.C.
References dict, functionObject::read(), and writeFile::read().
Referenced by sizeDistribution::sizeDistribution().
execute()
bool execute () virtual
Implements functionObject.
Definition at line 402 of file sizeDistribution.C.
write()
bool write () virtual
Implements functionObject.
Definition at line 408 of file sizeDistribution.C.
References alpha, delta, Foam::endl(), forAll, Log, UPstream::master(), mesh, Foam::name(), Foam::nl, Foam::sum(), Foam::tab, and Foam::type().
Member Data Documentation
selectionModeTypeNames_
const Foam::Enum< Foam::functionObjects::sizeDistribution::selectionModeTypes > selectionModeTypeNames_ static
Definition at line 162 of file sizeDistribution.H.
Referenced by sizeDistribution::initialise().
functionTypeNames_
const Foam::Enum< Foam::functionObjects::sizeDistribution::functionTypes > functionTypeNames_ static
Definition at line 175 of file sizeDistribution.H.
Referenced by sizeDistribution::initialise().
abszissaTypeNames_
const Foam::Enum< Foam::functionObjects::sizeDistribution::abszissaTypes > abszissaTypeNames_ static
Definition at line 186 of file sizeDistribution.H.
Referenced by sizeDistribution::initialise().
dict_
dictionary dict_ protected
Definition at line 194 of file sizeDistribution.H.
Referenced by sizeDistribution::dict().
selectionModeType_
selectionModeTypes selectionModeType_ protected
Definition at line 197 of file sizeDistribution.H.
Referenced by sizeDistribution::initialise().
selectionModeTypeName_
word selectionModeTypeName_ protected
Definition at line 200 of file sizeDistribution.H.
Referenced by sizeDistribution::initialise().
functionType_
functionTypes functionType_ protected
Definition at line 203 of file sizeDistribution.H.
Referenced by sizeDistribution::initialise().
abszissaType_
abszissaTypes abszissaType_ protected
Definition at line 206 of file sizeDistribution.H.
Referenced by sizeDistribution::initialise().
nCells_
label nCells_ protected
Definition at line 209 of file sizeDistribution.H.
Referenced by sizeDistribution::initialise().
cellId_
labelList cellId_ protected
Definition at line 212 of file sizeDistribution.H.
Referenced by sizeDistribution::cellId().
volume_
scalar volume_ protected
Definition at line 215 of file sizeDistribution.H.
Referenced by sizeDistribution::initialise().
writeVolume_
bool writeVolume_ protected
Definition at line 218 of file sizeDistribution.H.
popBal_
const Foam::diameterModels::populationBalanceModel& popBal_ protected
Definition at line 221 of file sizeDistribution.H.
N_
List<scalar> N_ protected
Definition at line 224 of file sizeDistribution.H.
momentOrder_
label momentOrder_ protected
Definition at line 227 of file sizeDistribution.H.
normalize_
const Switch normalize_ protected
Definition at line 230 of file sizeDistribution.H.
sumN_
scalar sumN_ protected
Definition at line 233 of file sizeDistribution.H.
sumV_
scalar sumV_ protected
Definition at line 236 of file sizeDistribution.H.
The documentation for this class was generated from the following files:
src/functionObjects/phaseSystems/sizeDistribution/sizeDistribution.H
src/functionObjects/phaseSystems/sizeDistribution/sizeDistribution.C