OpenFOAM: daughterSizeDistributionModel Class Reference
daughterSizeDistributionModel Class Reference abstract
Base class for daughter size distribution models.
#include <daughterSizeDistributionModel.H>
Public Member Functions
TypeName ("daughterSizeDistributionModel")
declareRunTimeSelectionTable (autoPtr, daughterSizeDistributionModel, dictionary,(const breakupModel &breakup, const dictionary &dict),(breakup, dict))
daughterSizeDistributionModel (const breakupModel &breakup, const dictionary &dict)
virtual ~daughterSizeDistributionModel ()
const dimensionedScalar & nik (const label i, const label k) const
void correct ()
virtual dimensionedScalar calcNik (const label i, const label k) const =0
Static Public Member Functions
static autoPtr< daughterSizeDistributionModel > New (const breakupModel &breakup, const dictionary &dict)
Protected Attributes
const breakupModel & breakup_
PtrList< PtrList< dimensionedScalar > > nik_
Detailed Description
Base class for daughter size distribution models.
Source files
daughterSizeDistributionModel.H
daughterSizeDistributionModel.C
Definition at line 51 of file daughterSizeDistributionModel.H.
Constructor & Destructor Documentation
daughterSizeDistributionModel()
daughterSizeDistributionModel (const breakupModel & breakup, const dictionary & dict)
Definition at line 71 of file daughterSizeDistributionModel.C.
~daughterSizeDistributionModel()
~daughterSizeDistributionModel () virtual
Definition at line 84 of file daughterSizeDistributionModel.C.
Member Function Documentation
TypeName()
TypeName ("daughterSizeDistributionModel")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , daughterSizeDistributionModel , dictionary , (const breakupModel &breakup, const dictionary &dict) , (breakup, dict))
New()
Foam::autoPtr< Foam::diameterModels::daughterSizeDistributionModel > New (const breakupModel & breakup, const dictionary & dict) static
Definition at line 40 of file daughterSizeDistributionModel.C.
References dict, Foam::exit(), Foam::FatalIOError, and FatalIOErrorInLookup.
Referenced by breakupModel::breakupModel().
nik()
const Foam::dimensionedScalar & nik (const label i, const label k) const
Definition at line 92 of file daughterSizeDistributionModel.C.
References k.
correct()
void correct ()
Definition at line 103 of file daughterSizeDistributionModel.C.
References PtrList< T >::append(), forAll, and k.
calcNik()
virtual dimensionedScalar calcNik (const label i, const label k) const pure virtual
Implemented in LaakkonenAlopaeusAittamaaDsd, and uniformBinary.
Member Data Documentation
breakup_
const breakupModel& breakup_ protected
Definition at line 58 of file daughterSizeDistributionModel.H.
nik_
PtrList<PtrList<dimensionedScalar> > nik_ protected
Definition at line 61 of file daughterSizeDistributionModel.H.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/populationBalanceModel/daughterSizeDistributionModels/daughterSizeDistributionModel/daughterSizeDistributionModel.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/populationBalanceModel/daughterSizeDistributionModels/daughterSizeDistributionModel/daughterSizeDistributionModel.C