OpenFOAM: ThermoParcel< ParcelType > Class Template Reference
ThermoParcel< ParcelType > Class Template Reference
Lagrangian particle models » Parcels
Thermodynamic parcel class with one/two-way coupling with the continuous phase. Includes Kinematic parcel sub-models, plus:
#include <ThermoParcel.H>
Classes
class constantProperties
class iNew
class trackingData
Public Member Functions
TypeName ("ThermoParcel")
AddToPropertyList (ParcelType, " T"+" Cp")
ThermoParcel (const polyMesh &mesh, const barycentric &coordinates, const label celli, const label tetFacei, const label tetPti)
ThermoParcel (const polyMesh &mesh, const vector &position, const label celli)
ThermoParcel (const polyMesh &mesh, const barycentric &coordinates, const label celli, const label tetFacei, const label tetPti, const label typeId, const scalar nParticle0, const scalar d0, const scalar dTarget0, const vector &U0, const vector &f0, const vector &angularMomentum0, const vector &torque0, const constantProperties &constProps)
ThermoParcel (const polyMesh &mesh, Istream &is, bool readFields=true, bool newFormat=true)
ThermoParcel (const ThermoParcel &p)
ThermoParcel (const ThermoParcel &p, const polyMesh &mesh)
virtual autoPtr< particle > clone () const
virtual autoPtr< particle > clone (const polyMesh &mesh) const
scalar T () const
scalar Cp () const
scalar hs () const
scalar & T ()
scalar & Cp ()
template<class TrackCloudType >
void setCellValues (TrackCloudType &cloud, trackingData &td)
template<class TrackCloudType >
void cellValueSourceCorrection (TrackCloudType &cloud, trackingData &td, const scalar dt)
template<class TrackCloudType >
void calcSurfaceValues (TrackCloudType &cloud, trackingData &td, const scalar T, scalar &Ts, scalar &rhos, scalar &mus, scalar &Pr, scalar &kappas) const
template<class TrackCloudType >
void calc (TrackCloudType &cloud, trackingData &td, const scalar dt)
void writeProperties (Ostream &os, const wordRes &filters, const word &delim, const bool namesOnly=false) const
template<class TrackCloudType >
Foam::scalar calcHeatTransfer (TrackCloudType &cloud, trackingData &td, const scalar dt, const scalar Re, const scalar Pr, const scalar kappa, const scalar NCpW, const scalar Sh, scalar &dhsTrans, scalar &Sph)
Static Public Member Functions
template<class CloudType >
static void readFields (CloudType &c)
template<class CloudType >
static void writeFields (const CloudType &c)
template<class CloudType >
static void readObjects (CloudType &c, const objectRegistry &obr)
template<class CloudType >
static void writeObjects (const CloudType &c, objectRegistry &obr)
Static Public Attributes
static const std::size_t sizeofFields
Protected Member Functions
template<class TrackCloudType >
scalar calcHeatTransfer (TrackCloudType &cloud, trackingData &td, const scalar dt, const scalar Re, const scalar Pr, const scalar kappa, const scalar NCpW, const scalar Sh, scalar &dhsTrans, scalar &Sph)
Protected Attributes
scalar T_
scalar Cp_
Friends
Ostream & operator<< (Ostream &, const ThermoParcel< ParcelType > &)
Detailed Description
template<class ParcelType>
class Foam::ThermoParcel< ParcelType >
Thermodynamic parcel class with one/two-way coupling with the continuous phase. Includes Kinematic parcel sub-models, plus:
heat transfer
Source files
ThermoParcel.H
ThermoParcelI.H
ThermoParcel.C
ThermoParcelIO.C
Definition at line 67 of file ThermoParcel.H.
Constructor & Destructor Documentation
ThermoParcel() [1/6]
template<class ParcelType > ThermoParcel (const polyMesh & mesh, const barycentric & coordinates, const label celli, const label tetFacei, const label tetPti) inline
Definition at line 69 of file ThermoParcelI.H.
ThermoParcel() [2/6]
template<class ParcelType > ThermoParcel (const polyMesh & mesh, const vector & position, const label celli) inline
Definition at line 85 of file ThermoParcelI.H.
ThermoParcel() [3/6]
template<class ParcelType > ThermoParcel (const polyMesh & mesh, const barycentric & coordinates, const label celli, const label tetFacei, const label tetPti, const label typeId, const scalar nParticle0, const scalar d0, const scalar dTarget0, const vector & U0, const vector & f0, const vector & angularMomentum0, const vector & torque0, const constantProperties & constProps) inline
Definition at line 99 of file ThermoParcelI.H.
ThermoParcel() [4/6]
template<class ParcelType > ThermoParcel (const polyMesh & mesh, Istream & is, bool readFields = true, bool newFormat = true)
Definition at line 43 of file ThermoParcelIO.C.
References IOstreamOption::ASCII, ThermoParcel< ParcelType >::Cp_, FUNCTION_NAME, ThermoParcel< ParcelType >::readFields(), Foam::readFields(), ThermoParcel< ParcelType >::sizeofFields, and ThermoParcel< ParcelType >::T_.
ThermoParcel() [5/6]
template<class ParcelType > ThermoParcel (const ThermoParcel< ParcelType > & p)
ThermoParcel() [6/6]
template<class ParcelType > ThermoParcel (const ThermoParcel< ParcelType > & p, const polyMesh & mesh)
Member Function Documentation
calcHeatTransfer() [1/2]
template<class ParcelType > template<class TrackCloudType > scalar calcHeatTransfer (TrackCloudType & cloud, trackingData & td, const scalar dt, const scalar Re, const scalar Pr, const scalar kappa, const scalar NCpW, const scalar Sh, scalar & dhsTrans, scalar & Sph) protected
TypeName()
template<class ParcelType > TypeName ("ThermoParcel< ParcelType >")
AddToPropertyList()
template<class ParcelType > AddToPropertyList (ParcelType , " T"+" Cp")
clone() [1/2]
template<class ParcelType > virtual autoPtr< particle > clone () const inline virtual
Definition at line 347 of file ThermoParcel.H.
clone() [2/2]
template<class ParcelType > virtual autoPtr< particle > clone (const polyMesh & mesh) const inline virtual
Definition at line 353 of file ThermoParcel.H.
References mesh.
T() [1/2]
template<class ParcelType > Foam::scalar T () const inline
Definition at line 200 of file ThermoParcelI.H.
Cp() [1/2]
template<class ParcelType > Foam::scalar Cp () const inline
Definition at line 207 of file ThermoParcelI.H.
hs()
template<class ParcelType > Foam::scalar hs () const inline
Definition at line 214 of file ThermoParcelI.H.
T() [2/2]
template<class ParcelType > Foam::scalar & T () inline
Definition at line 221 of file ThermoParcelI.H.
Cp() [2/2]
template<class ParcelType > Foam::scalar & Cp () inline
Definition at line 228 of file ThermoParcelI.H.
setCellValues()
template<class ParcelType > template<class TrackCloudType > void setCellValues (TrackCloudType & cloud, trackingData & td)
Definition at line 30 of file ThermoParcel.C.
References coordinates(), Foam::endl(), Foam::nl, and WarningInFunction.
cellValueSourceCorrection()
template<class ParcelType > template<class TrackCloudType > void cellValueSourceCorrection (TrackCloudType & cloud, trackingData & td, const scalar dt)
Definition at line 60 of file ThermoParcel.C.
References Foam::endl(), Foam::nl, and WarningInFunction.
calcSurfaceValues()
template<class ParcelType > template<class TrackCloudType > void calcSurfaceValues (TrackCloudType & cloud, trackingData & td, const scalar T, scalar & Ts, scalar & rhos, scalar & mus, scalar & Pr, scalar & kappas) const
Definition at line 94 of file ThermoParcel.C.
References coordinates(), Foam::endl(), Foam::max(), Foam::nl, Pr(), T, and WarningInFunction.
calc()
template<class ParcelType > template<class TrackCloudType > void calc (TrackCloudType & cloud, trackingData & td, const scalar dt)
Definition at line 137 of file ThermoParcel.C.
References Foam::pow4(), Pr(), Foam::Re(), Su, T0, and Foam::Zero.
readFields()
template<class ParcelType > template<class CloudType > void readFields (CloudType & c) static
Definition at line 84 of file ThermoParcelIO.C.
References Cp, IOobjectOption::MUST_READ, p, UPtrList< T >::size(), and T.
Referenced by ThermoParcel< ParcelType >::ThermoParcel().
writeFields()
template<class ParcelType > template<class CloudType > void writeFields (const CloudType & c) static
Definition at line 110 of file ThermoParcelIO.C.
References Cp, IOobjectOption::NO_READ, p, UPtrList< T >::size(), and T.
writeProperties()
template<class ParcelType > void writeProperties (Ostream & os, const wordRes & filters, const word & delim, const bool namesOnly = false) const
Definition at line 135 of file ThermoParcelIO.C.
References os(), and writeProp.
readObjects()
template<class ParcelType > template<class CloudType > void readObjects (CloudType & c, const objectRegistry & obr) static
Definition at line 158 of file ThermoParcelIO.C.
References Cp, p, UPtrList< T >::size(), and T.
writeObjects()
template<class ParcelType > template<class CloudType > void writeObjects (const CloudType & c, objectRegistry & obr) static
Definition at line 184 of file ThermoParcelIO.C.
References Cp, p, UPtrList< T >::size(), and T.
calcHeatTransfer() [2/2]
template<class ParcelType > template<class TrackCloudType > Foam::scalar calcHeatTransfer (TrackCloudType & cloud, trackingData & td, const scalar dt, const scalar Re, const scalar Pr, const scalar kappa, const scalar NCpW, const scalar Sh, scalar & dhsTrans, scalar & Sph)
Definition at line 246 of file ThermoParcel.C.
References Foam::clamp(), coordinates(), epsilon, Foam::pow4(), Pr(), Foam::Re(), rho, and Foam::constant::physicoChemical::sigma.
Friends And Related Symbol Documentation
operator<<
template<class ParcelType > Ostream & operator<< (Ostream & , const ThermoParcel< ParcelType > &) friend
Member Data Documentation
sizeofFields
template<class ParcelType > const std::size_t sizeofFields static
Definition at line 74 of file ThermoParcel.H.
Referenced by ThermoParcel< ParcelType >::ThermoParcel().
T_
template<class ParcelType > scalar T_ protected
Definition at line 249 of file ThermoParcel.H.
Referenced by ThermoParcel< ParcelType >::ThermoParcel().
Cp_
template<class ParcelType > scalar Cp_ protected
Definition at line 252 of file ThermoParcel.H.
Referenced by ThermoParcel< ParcelType >::trackingData::Cp(), and ThermoParcel< ParcelType >::ThermoParcel().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/parcels/Templates/ThermoParcel/ThermoParcel.H
src/lagrangian/intermediate/parcels/Templates/ThermoParcel/ThermoParcel.C
src/lagrangian/intermediate/parcels/Templates/ThermoParcel/ThermoParcelI.H
src/lagrangian/intermediate/parcels/Templates/ThermoParcel/ThermoParcelIO.C