OpenFOAM: polyBoundaryMesh Class Reference
polyBoundaryMesh Class Reference
A polyBoundaryMesh is a polyPatch list with additional search methods and registered IO.
#include <polyBoundaryMesh.H>
Public Member Functions
TypeName ("polyBoundaryMesh")
polyBoundaryMesh (const polyBoundaryMesh &)=delete
void operator= (const polyBoundaryMesh &)=delete
polyBoundaryMesh (const IOobject &io, const polyMesh &mesh)
polyBoundaryMesh (const IOobject &io, const polyMesh &mesh, const label size)
polyBoundaryMesh (const IOobject &io, const polyMesh &mesh, const polyPatchList &ppl)
~polyBoundaryMesh ()=default
void clear ()
void clearGeom ()
void clearAddressing ()
const polyMesh & mesh () const noexcept
UPtrList< const labelUList > faceCells () const
const List< labelPairList > & neighbourEdges () const
label nNonProcessor () const
label nProcessorPatches () const
wordList names () const
wordList types () const
wordList physicalTypes () const
labelList patchStarts () const
labelList patchSizes () const
List< labelRange > patchRanges () const
wordList groupNames () const
label start () const noexcept
label nFaces () const noexcept
labelRange range () const noexcept
labelRange range (const label patchi) const
labelList indices (const wordRe &matcher, const bool useGroups=true) const
labelList indices (const wordRes &matcher, const bool useGroups=true) const
label findIndex (const wordRe &key) const
label findPatchID (const word &patchName, const bool allowNotFound=true) const
template<class Type >
labelHashSet findPatchIDs () const
labelPair whichPatchFace (const label meshFacei) const
labelPairList whichPatchFace (const labelUList &meshFaceIndices) const
label whichPatch (const label meshFacei) const
const labelList & patchID () const
label patchID (const label meshFacei) const
labelList patchID (const labelUList &meshFaceIndices) const
const HashTable< labelList > & groupPatchIDs () const
void setGroup (const word &groupName, const labelUList &patchIDs)
labelHashSet patchSet (const UList< wordRe > &patchNames, const bool warnNotFound=true, const bool useGroups=true) const
void matchGroups (const labelUList &patchIDs, wordList &groups, labelHashSet &nonGroupPatches) const
bool checkParallelSync (const bool report=false) const
bool checkDefinition (const bool report=false) const
void movePoints (const pointField &p)
void updateMesh ()
void reorder (const labelUList &oldToNew, const bool validBoundary)
virtual bool writeData (Ostream &os) const
virtual bool writeObject (IOstreamOption streamOpt, const bool writeOnProc) const
const polyPatch & operator[] (const word &patchName) const
polyPatch & operator[] (const word &patchName)
labelList findIndices (const wordRe &key, bool useGroups=true) const
template<class Type >
Foam::labelHashSet findPatchIDs () const
Public Member Functions inherited from PtrList< T >
constexpr PtrList () noexcept
PtrList (const label len)
PtrList (const PtrList< T > &list)
PtrList (PtrList< T > &&list)
PtrList (UList< T * > &list)
template<class CloneArg >
PtrList (const PtrList< T > &list, const CloneArg &cloneArgs)
PtrList (PtrList< T > &list, bool reuse)
PtrList (const SLPtrList< T > &list)
template<class INew >
PtrList (Istream &is, const INew &inew)
PtrList (Istream &is)
~PtrList ()
template<class... Args>
PtrList< T > clone (Args &&... args) const
const T * set (const label i) const
void clear ()
void free ()
void resize (const label newLen)
template<class... Args>
T & emplace_back (Args &&... args)
void push_back (T *ptr)
void push_back (std::unique_ptr< T > &&ptr)
void push_back (autoPtr< T > &&ptr)
void push_back (const refPtr< T > &ptr)
void push_back (const tmp< T > &ptr)
void push_back (PtrList< T > &&other)
template<class... Args>
T & emplace_set (const label i, Args &&... args)
template<class... Args>
T & emplace (const label i, Args &&... args)
autoPtr< T > set (const label i, T *ptr)
autoPtr< T > set (const label i, std::unique_ptr< T > &&ptr)
autoPtr< T > set (const label i, autoPtr< T > &&ptr)
autoPtr< T > set (const label i, const refPtr< T > &ptr)
autoPtr< T > set (const label i, const tmp< T > &ptr)
autoPtr< T > release (const label i)
void transfer (PtrList< T > &list)
void operator= (const PtrList< T > &list)
void operator= (PtrList< T > &&list)
void push_back (autoPtr< T > &ptr)=delete
autoPtr< T > set (const label i, autoPtr< T > &ptr)
void setSize (const label newLen)
void append (autoPtr< T > &ptr)
void append (T *ptr)
void append (std::unique_ptr< T > &&ptr)
void append (autoPtr< T > &&ptr)
void append (const refPtr< T > &ptr)
void append (const tmp< T > &ptr)
void append (PtrList< T > &&other)
template<class... Args>
Foam::PtrList< T > clone (Args &&... args) const
Public Member Functions inherited from UPtrList< T >
constexpr UPtrList () noexcept
UPtrList (const label len)
UPtrList (const UPtrList< T > &list)
UPtrList (UPtrList< T > &&list)
UPtrList (UPtrList< T > &list, bool reuse)
UPtrList (PtrList< T > &list)
UPtrList (const UList< T * > &list)
UPtrList (UList< T > &list)
bool empty () const noexcept
label size () const noexcept
label count () const noexcept
T & front ()
const T & front () const
T & back ()
const T & back () const
const T * test (const label i) const
const T * get (const label i) const
T * get (const label i)
const T * set (const label i) const
void clear ()
void free ()
void resize (const label newLen)
label squeezeNull ()
void trimTrailingNull ()
void push_back (T *ptr)
void push_back (UPtrList< T > &&other)
void swap (UPtrList< T > &list)
void transfer (UPtrList< T > &list)
T * set (const label i, T *ptr)
void reorder (const labelUList &oldToNew, const bool check=false)
void sortOrder (const labelUList &order, const bool check=false)
void checkNonNull () const
const T & at (const label i) const
T & at (const label i)
const T & operator[] (const label i) const
T & operator[] (const label i)
FOAM_DEPRECATED_FOR (2022-09, "get(), set() or test() methods") const T *operator()(const label i) const
void operator= (const UPtrList< T > &list)
void operator= (UPtrList< T > &&list)
T ** begin_ptr () noexcept
T ** end_ptr () noexcept
iterator begin ()
iterator end () noexcept
const_iterator cbegin () const
const_iterator cend () const noexcept
const_iterator begin () const
const_iterator end () const noexcept
void setSize (const label n)
T & first ()
const T & first () const
T & last ()
const T & last () const
void append (T *ptr)
void append (UPtrList< T > &&other)
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
regIOobject (const IOobject &io, const bool isTimeObject=false)
regIOobject (const regIOobject &rio)
regIOobject (const regIOobject &rio, bool registerCopy)
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
regIOobject (const IOobject &io, const regIOobject &rio)
virtual ~regIOobject ()
bool checkIn ()
bool checkOut ()
virtual void addWatch ()
bool registered () const noexcept
bool ownedByRegistry () const noexcept
bool store ()
void release (const bool unregister=false) noexcept
label eventNo () const noexcept
label & eventNo () noexcept
bool upToDate (const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
void setUpToDate ()
virtual void rename (const word &newName)
const dictionary * findMetaData () const noexcept
dictionary & getMetaData () noexcept
void removeMetaData ()
virtual void updateMetaData ()
virtual fileName filePath () const
bool headerOk ()
Istream & readStream (const word &, const bool readOnProc=true)
void close ()
virtual bool readData (Istream &)
virtual bool read ()
virtual label addWatch (const fileName &)
const labelList & watchIndices () const noexcept
labelList & watchIndices () noexcept
virtual bool modified () const
virtual bool readIfModified ()
virtual bool write (const bool writeOnProc=true) const
virtual bool global () const
void operator= (const IOobject &io)
virtual bool writeObject (IOstreamOption::streamFormat fmt, IOstreamOption::versionNumber ver, IOstreamOption::compressionType cmp, const bool writeOnProc) const
Public Member Functions inherited from IOobject
TypeName ("IOobject")
IOobject (const IOobject &)=default
virtual ~IOobject ()=default
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const fileName &path, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const fileName &path, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const IOobject &io, const objectRegistry &registry)
IOobject (const IOobject &io, const word &name)
IOobject (const IOobject &io, const word &name, const fileName &local)
IOobject (const IOobject &io, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt)
IOobject (const IOobject &io, IOobjectOption::registerOption regOpt)
autoPtr< IOobject > clone () const
autoPtr< IOobject > clone (const objectRegistry &registry) const
const objectRegistry & db () const noexcept
const Time & time () const noexcept
const word & name () const noexcept
const word & headerClassName () const noexcept
word & headerClassName () noexcept
const string & note () const noexcept
string & note () noexcept
unsigned labelByteSize () const noexcept
unsigned scalarByteSize () const noexcept
void resetHeader (const word &newName=word::null)
bool hasHeaderClass () const noexcept
template<class Type >
bool isHeaderClass () const
template<class Type >
bool isHeaderClassName () const
word group () const
word member () const
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const noexcept
fileName & instance () noexcept
const fileName & local () const noexcept
fileName path () const
fileName path (const word &instance, const fileName &local=fileName::null) const
fileName objectPath () const
fileName objectRelPath () const
fileName localFilePath (const word &typeName, const bool search=true) const
fileName globalFilePath (const word &typeName, const bool search=true) const
IOstreamOption parseHeader (const dictionary &headerDict)
bool readHeader (Istream &is)
bool readHeader (dictionary &headerDict, Istream &is)
template<class Type >
bool typeHeaderOk (const bool checkType=true, const bool search=true, const bool verbose=true)
template<class Type >
void warnNoRereading () const
bool writeHeader (Ostream &os) const
bool writeHeader (Ostream &os, const word &objectType) const
void writeHeader (dictionary &dict, IOstreamOption streamOpt) const
void writeHeader (dictionary &dict, const word &objectType, IOstreamOption streamOpt) const
bool good () const noexcept
bool bad () const noexcept
InfoProxy< IOobject > info () const noexcept
void operator= (const IOobject &io)
template<>
bool isHeaderClass () const
template<class StringType >
Foam::word groupName (StringType base, const word &group)
Public Member Functions inherited from IOobjectOption
constexpr IOobjectOption (readOption rOpt=readOption::NO_READ, writeOption wOpt=writeOption::NO_WRITE, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (readOption rOpt, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (writeOption wOpt, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (registerOption registerObject, bool globalObject=false) noexcept
constexpr IOobjectOption (readOption rOpt, writeOption wOpt, bool registerObject, bool globalObject=false) noexcept
constexpr IOobjectOption (bool registerObject, bool globalObject=false) noexcept
readOption readOpt () const noexcept
readOption readOpt (readOption opt) noexcept
writeOption writeOpt () const noexcept
writeOption writeOpt (writeOption opt) noexcept
bool registerObject () const noexcept
bool registerObject (bool on) noexcept
bool globalObject () const noexcept
bool globalObject (bool on) noexcept
bool isAnyRead () const noexcept
bool isReadRequired () const noexcept
bool isReadOptional () const noexcept
readOption & readOpt () noexcept
writeOption & writeOpt () noexcept
bool & registerObject () noexcept
bool & globalObject () noexcept
Friends
class polyMesh
Ostream & operator<< (Ostream &os, const polyBoundaryMesh &pbm)
Additional Inherited Members
Public Types inherited from UPtrList< T >
typedef T value_type
typedef T & reference
typedef const T & const_reference
Public Types inherited from IOobject
enum objectState : char { GOOD , BAD }
enum fileCheckTypes : char { timeStamp , timeStampMaster , inotify , inotifyMaster }
Public Types inherited from IOobjectOption
enum readOption : unsigned char {
NO_READ = 0 , MUST_READ = 0x1 , READ_MODIFIED = 0x3 , MUST_READ_IF_MODIFIED = 0x3 ,
LAZY_READ = 0x4 , READ_IF_PRESENT = 0x4
}
enum writeOption : unsigned char { NO_WRITE = 0 , AUTO_WRITE = 0x10 }
enum registerOption : unsigned char { NO_REGISTER = 0 , REGISTER = 1 }
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *p)
template<class Type >
static Type & store (autoPtr< Type > &ptr)
template<class Type >
static Type & store (autoPtr< Type > &&ptr)
template<class Type >
static Type & store (refPtr< Type > &ptr)
template<class Type >
static Type & store (refPtr< Type > &&ptr)
template<class Type >
static Type & store (tmp< Type > &ptr)
template<class Type >
static Type & store (tmp< Type > &&ptr)
Static Public Member Functions inherited from IOobject
static bool bannerEnabled () noexcept
static bool bannerEnabled (bool on) noexcept
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
template<class StringType >
static word groupName (StringType base, const word &group)
static word group (const word &name)
static word member (const word &name)
static word scopedName (const std::string &scope, const word &name)
static IOobject selectIO (const IOobject &io, const fileName &altFile, const word &ioName="")
static Ostream & writeBanner (Ostream &os, const bool noSyntaxHint=false)
static Ostream & writeDivider (Ostream &os)
static Ostream & writeEndDivider (Ostream &os)
Static Public Member Functions inherited from IOobjectOption
static bool isAnyRead (readOption opt) noexcept
static bool isReadRequired (readOption opt) noexcept
static bool isReadOptional (readOption opt) noexcept
static readOption lazierRead (readOption opt) noexcept
Static Public Attributes inherited from IOobject
static const Enum< fileCheckTypes > fileCheckTypesNames
static char scopeSeparator
static fileCheckTypes fileModificationChecking
static float fileModificationSkew
static int maxFileModificationPolls
Protected Member Functions inherited from PtrList< T >
template<class INew >
void readIstream (Istream &is, const INew &inew)
Protected Member Functions inherited from UPtrList< T >
void setAddressableSize (const label n) noexcept
label find_next (label pos) const
UPtrList (Detail::PtrListDetail< T > &&ptrs)
Protected Member Functions inherited from regIOobject
bool readHeaderOk (const IOstreamOption::streamFormat fmt, const word &typeName)
Protected Member Functions inherited from IOobject
void setBad (const string &s)
Static Protected Member Functions inherited from IOobject
static void writeHeaderContent (Ostream &os, const IOobject &io, const word &objectType, const dictionary *metaDataDict=nullptr)
static void writeHeaderContent (dictionary &dict, const IOobject &io, const word &objectType, IOstreamOption streamOpt, const dictionary *metaDataDict=nullptr)
Protected Attributes inherited from UPtrList< T >
Detail::PtrListDetail< T > ptrs_
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
Detailed Description
A polyBoundaryMesh is a polyPatch list with additional search methods and registered IO.
Source files
polyBoundaryMesh.H
polyBoundaryMesh.C
Definition at line 58 of file polyBoundaryMesh.H.
Constructor & Destructor Documentation
polyBoundaryMesh() [1/4]
polyBoundaryMesh (const polyBoundaryMesh &) delete
polyBoundaryMesh() [2/4]
polyBoundaryMesh (const IOobject & io, const polyMesh & mesh)
Definition at line 150 of file polyBoundaryMesh.C.
polyBoundaryMesh() [3/4]
polyBoundaryMesh (const IOobject & io, const polyMesh & mesh, const label size)
Definition at line 164 of file polyBoundaryMesh.C.
polyBoundaryMesh() [4/4]
polyBoundaryMesh (const IOobject & io, const polyMesh & mesh, const polyPatchList & ppl)
Definition at line 177 of file polyBoundaryMesh.C.
References IOobject::clone(), forAll, patches, PtrList< T >::resize(), PtrList< T >::set(), and UPtrList< T >::size().
~polyBoundaryMesh()
~polyBoundaryMesh () default
Member Function Documentation
TypeName()
TypeName ("polyBoundaryMesh")
operator=()
void operator= (const polyBoundaryMesh &) delete
clear()
void clear ()
Definition at line 202 of file polyBoundaryMesh.C.
References PtrList< T >::clear().
Referenced by polyMesh::removeBoundary().
clearGeom()
void clearGeom ()
Definition at line 209 of file polyBoundaryMesh.C.
References p, and patches.
clearAddressing()
void clearAddressing ()
Definition at line 220 of file polyBoundaryMesh.C.
References p, and patches.
mesh()
const polyMesh & mesh () const inline noexcept
Definition at line 153 of file polyBoundaryMesh.H.
faceCells()
Foam::UPtrList< const Foam::labelUList > faceCells () const
Definition at line 284 of file polyBoundaryMesh.C.
References forAll, patches, PtrList< T >::set(), and UPtrList< T >::size().
neighbourEdges()
const Foam::List< Foam::labelPairList > & neighbourEdges () const
Definition at line 300 of file polyBoundaryMesh.C.
References Foam::abort(), e, PrimitivePatch< FaceList, PointField >::edges(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, PrimitivePatch< FaceList, PointField >::localPoints(), PrimitivePatch< FaceList, PointField >::meshPoints(), PrimitivePatch< FaceList, PointField >::nEdges(), PrimitivePatch< FaceList, PointField >::nInternalEdges(), Foam::nl, UPstream::parRun(), pp(), UPtrList< T >::size(), UList< T >::size(), and WarningInFunction.
nNonProcessor()
Foam::label nNonProcessor () const
Definition at line 533 of file polyBoundaryMesh.C.
References p, and patches.
nProcessorPatches()
Foam::label nProcessorPatches () const
Definition at line 553 of file polyBoundaryMesh.C.
References p, and patches.
names()
Foam::wordList names () const
Definition at line 571 of file polyBoundaryMesh.C.
types()
Foam::wordList types () const
Definition at line 577 of file polyBoundaryMesh.C.
physicalTypes()
Foam::wordList physicalTypes () const
Definition at line 583 of file polyBoundaryMesh.C.
References p.
patchStarts()
Foam::labelList patchStarts () const
Definition at line 594 of file polyBoundaryMesh.C.
References p.
patchSizes()
Foam::labelList patchSizes () const
Definition at line 605 of file polyBoundaryMesh.C.
References p, and UList< T >::size().
patchRanges()
Foam::List< Foam::labelRange > patchRanges () const
Definition at line 616 of file polyBoundaryMesh.C.
References p.
groupNames()
Foam::wordList groupNames () const
Definition at line 627 of file polyBoundaryMesh.C.
start()
Foam::label start () const noexcept
Definition at line 633 of file polyBoundaryMesh.C.
nFaces()
Foam::label nFaces () const noexcept
Definition at line 639 of file polyBoundaryMesh.C.
range() [1/2]
Foam::labelRange range () const noexcept
Definition at line 645 of file polyBoundaryMesh.C.
range() [2/2]
Foam::labelRange range (const label patchi) const
Definition at line 651 of file polyBoundaryMesh.C.
indices() [1/2]
Foam::labelList indices (const wordRe & matcher, const bool useGroups = true) const
Definition at line 663 of file polyBoundaryMesh.C.
References UPtrList< T >::empty(), Foam::PtrListOps::findMatching(), Foam::PtrListOps::firstMatching(), forAllConstIters, wordRe::isPattern(), wordRe::match(), and patchId().
Referenced by polyBoundaryMesh::findIndices().
indices() [2/2]
Foam::labelList indices (const wordRes & matcher, const bool useGroups = true) const
Definition at line 730 of file polyBoundaryMesh.C.
References UList< T >::empty(), UPtrList< T >::empty(), Foam::PtrListOps::findMatching(), UList< T >::first(), forAllConstIters, wordRes::match(), PtrList< T >::resize(), and UList< T >::size().
findIndex()
Foam::label findIndex (const wordRe & key) const
Definition at line 776 of file polyBoundaryMesh.C.
References UPtrList< T >::empty(), and Foam::PtrListOps::firstMatching().
findPatchID()
Foam::label findPatchID (const word & patchName, const bool allowNotFound = true) const
Definition at line 786 of file polyBoundaryMesh.C.
References polyMesh::defaultRegion, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::PtrListOps::firstMatching(), patchId(), and Foam::Pout.
findPatchIDs() [1/2]
template<class Type > labelHashSet findPatchIDs () const
whichPatchFace() [1/2]
Foam::labelPair whichPatchFace (const label meshFacei) const
Definition at line 835 of file polyBoundaryMesh.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, Foam::findLower(), Foam::flatOutput(), mesh, primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), Foam::nl, p, patches, and range.
Referenced by polyBoundaryMesh::whichPatch().
whichPatchFace() [2/2]
Foam::labelPairList whichPatchFace (const labelUList & meshFaceIndices) const
Definition at line 893 of file polyBoundaryMesh.C.
References forAll, Foam::output(), and UPtrList< T >::size().
whichPatch()
label whichPatch (const label meshFacei) const inline
Definition at line 258 of file polyBoundaryMesh.H.
References Pair< T >::first(), and polyBoundaryMesh::whichPatchFace().
patchID() [1/3]
const Foam::labelList & patchID () const
Definition at line 429 of file polyBoundaryMesh.C.
References forAll, and patches.
patchID() [2/3]
Foam::label patchID (const label meshFacei) const
Definition at line 453 of file polyBoundaryMesh.C.
References patchID.
patchID() [3/3]
Foam::labelList patchID (const labelUList & meshFaceIndices) const
Definition at line 467 of file polyBoundaryMesh.C.
References forAll, Foam::output(), patchID, and UPtrList< T >::size().
groupPatchIDs()
const Foam::HashTable< Foam::labelList > & groupPatchIDs () const
Definition at line 479 of file polyBoundaryMesh.C.
setGroup()
void setGroup (const word & groupName, const labelUList & patchIDs)
Definition at line 490 of file polyBoundaryMesh.C.
References forAll, UList< T >::found(), patches, patchIDs(), List< T >::resize(), and UPtrList< T >::size().
patchSet()
Foam::labelHashSet patchSet (const UList< wordRe > & patchNames, const bool warnNotFound = true, const bool useGroups = true) const
Definition at line 904 of file polyBoundaryMesh.C.
References UPtrList< T >::empty(), Foam::endl(), Foam::findMatchingStrings(), forAllConstIters, patchNames(), and WarningInFunction.
Referenced by wallShearStress::read(), and wallHeatFlux::read().
matchGroups()
void matchGroups (const labelUList & patchIDs, wordList & groups, labelHashSet & nonGroupPatches) const
Definition at line 973 of file polyBoundaryMesh.C.
References PtrList< T >::append(), forAllConstIters, patchIDs(), UPtrList< T >::size(), List< T >::transfer(), and PtrList< T >::transfer().
checkParallelSync()
bool checkParallelSync (const bool report = false) const
Definition at line 1013 of file polyBoundaryMesh.C.
References Foam::endl(), forAll, globalIndex::gather(), Foam::Info, UPstream::parRun(), Foam::Pout, procAddr(), globalIndex::range(), PtrList< T >::resize(), Foam::returnReduceOr(), UPtrList< T >::size(), and globalIndex::subProcs().
checkDefinition()
bool checkDefinition (const bool report = false) const
Definition at line 1095 of file polyBoundaryMesh.C.
References Foam::endl(), forAll, Foam::Info, mesh, primitiveMesh::nInternalFaces(), patchNames(), Foam::Pout, UPstream::reduceOr(), and UPtrList< T >::size().
movePoints()
void movePoints (const pointField & p)
Definition at line 1152 of file polyBoundaryMesh.C.
References UPstream::blocking, UPstream::defaultCommsType, forAll, polyMesh::globalData(), mesh, UPstream::nonBlocking, p, and UPstream::scheduled.
updateMesh()
void updateMesh ()
Definition at line 1198 of file polyBoundaryMesh.C.
References UPstream::blocking, UPstream::defaultCommsType, forAll, polyMesh::globalData(), mesh, UPstream::nonBlocking, and UPstream::scheduled.
Referenced by polyMesh::polyMesh(), polyMesh::polyMesh(), and polyMesh::updateMesh().
reorder()
void reorder (const labelUList & oldToNew, const bool validBoundary)
Definition at line 1248 of file polyBoundaryMesh.C.
References forAll, patches, and UPtrList< T >::reorder().
writeData()
bool writeData (Ostream & os) const virtual
Implements regIOobject.
Definition at line 1272 of file polyBoundaryMesh.C.
References token::BEGIN_LIST, Ostream::beginBlock(), IOstream::check(), Foam::decrIndent(), token::END_LIST, Ostream::endBlock(), FUNCTION_NAME, IOstream::good(), Foam::incrIndent(), Foam::nl, os(), patches, pp(), and UPtrList< T >::size().
writeObject()
bool writeObject (IOstreamOption streamOpt, const bool writeOnProc) const virtual
Reimplemented from regIOobject.
Definition at line 1292 of file polyBoundaryMesh.C.
References IOstreamOption::UNCOMPRESSED, and regIOobject::writeObject().
operator[]() [1/2]
const Foam::polyPatch & operator[] (const word & patchName) const
Definition at line 1305 of file polyBoundaryMesh.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, and Foam::nl.
operator[]() [2/2]
Foam::polyPatch & operator[] (const word & patchName)
Definition at line 1324 of file polyBoundaryMesh.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, and Foam::nl.
findIndices()
labelList findIndices (const wordRe & key, bool useGroups = true) const inline
Definition at line 355 of file polyBoundaryMesh.H.
References polyBoundaryMesh::indices().
findPatchIDs() [2/2]
template<class Type > Foam::labelHashSet findPatchIDs () const
Definition at line 24 of file polyBoundaryMeshTemplates.C.
References forAll, patches, and patchIDs().
Friends And Related Symbol Documentation
polyMesh
friend class polyMesh friend
Definition at line 95 of file polyBoundaryMesh.H.
operator<<
Ostream & operator<< (Ostream & os, const polyBoundaryMesh & pbm) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/polyBoundaryMesh/polyBoundaryMesh.H
src/OpenFOAM/meshes/polyMesh/polyBoundaryMesh/polyBoundaryMesh.C
src/OpenFOAM/meshes/polyMesh/polyBoundaryMesh/polyBoundaryMeshTemplates.C