OpenFOAM: hyperbolic Class Reference
hyperbolic Class Reference
#include <hyperbolic.H>
Public Member Functions
TypeName ("hyperbolic")
hyperbolic (const dictionary &dict, const wordList &phaseNames)
~hyperbolic ()=default
virtual tmp< volScalarField > f1 (const phaseModel &phase1, const phaseModel &phase2) const
virtual tmp< volScalarField > f2 (const phaseModel &phase1, const phaseModel &phase2) const
TypeName ("hyperbolic")
hyperbolic (const dictionary &dict, const wordList &phaseNames)
~hyperbolic ()=default
virtual tmp< volScalarField > f1 (const phaseModel &phase1, const phaseModel &phase2) const
virtual tmp< volScalarField > f2 (const phaseModel &phase1, const phaseModel &phase2) const
Public Member Functions inherited from blendingMethod
TypeName ("blendingMethod")
declareRunTimeSelectionTable (autoPtr, blendingMethod, dictionary,(const dictionary &dict, const wordList &phaseNames),(dict, phaseNames))
blendingMethod (const dictionary &dict)
virtual ~blendingMethod ()=default
TypeName ("blendingMethod")
declareRunTimeSelectionTable (autoPtr, blendingMethod, dictionary,(const dictionary &dict, const wordList &phaseNames),(dict, phaseNames))
blendingMethod (const dictionary &dict)
virtual ~blendingMethod ()=default
Additional Inherited Members
Static Public Member Functions inherited from blendingMethod
static autoPtr< blendingMethod > New (const word &modelName, const dictionary &dict, const wordList &phaseNames)
static autoPtr< blendingMethod > New (const dictionary &dict, const wordList &phaseNames)
Detailed Description
Source files
hyperbolic.H
hyperbolic.C
Definition at line 47 of file hyperbolic.H.
Constructor & Destructor Documentation
hyperbolic() [1/2]
hyperbolic (const dictionary & dict, const wordList & phaseNames)
Definition at line 43 of file hyperbolic.C.
References dict, Foam::dimless, and IOobject::groupName().
~hyperbolic() [1/2]
~hyperbolic () default
hyperbolic() [2/2]
hyperbolic (const dictionary & dict, const wordList & phaseNames)
~hyperbolic() [2/2]
~hyperbolic () default
Member Function Documentation
TypeName() [1/2]
TypeName ("hyperbolic")
f1() [1/2]
Foam::tmp< Foam::volScalarField > f1 (const phaseModel & phase1, const phaseModel & phase2) const virtual
Implements blendingMethod.
Definition at line 70 of file hyperbolic.C.
References phase2, and Foam::tanh().
f2() [1/2]
Foam::tmp< Foam::volScalarField > f2 (const phaseModel & phase1, const phaseModel & phase2) const virtual
Implements blendingMethod.
Definition at line 88 of file hyperbolic.C.
References phase1, and Foam::tanh().
TypeName() [2/2]
TypeName ("hyperbolic")
f1() [2/2]
virtual tmp< volScalarField > f1 (const phaseModel & phase1, const phaseModel & phase2) const virtual
Implements blendingMethod.
f2() [2/2]
virtual tmp< volScalarField > f2 (const phaseModel & phase1, const phaseModel & phase2) const virtual
Implements blendingMethod.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/BlendedInterfacialModel/blendingMethods/hyperbolic/hyperbolic.H
src/phaseSystemModels/twoPhaseEuler/twoPhaseSystem/BlendedInterfacialModel/blendingMethods/hyperbolic/hyperbolic.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/BlendedInterfacialModel/blendingMethods/hyperbolic/hyperbolic.C
src/phaseSystemModels/twoPhaseEuler/twoPhaseSystem/BlendedInterfacialModel/blendingMethods/hyperbolic/hyperbolic.C