OpenFOAM: surfaceFormatsCore Class Reference
surfaceFormatsCore Class Reference
A collection of helper functions for reading/writing surface formats.
#include <surfaceFormatsCore.H>
Public Member Functions
surfaceFormatsCore ()=default
virtual ~surfaceFormatsCore ()=default
Static Public Member Functions
static bool checkSupport (const wordHashSet &available, const word &fileType, const bool verbose=false, const char *functionName=nullptr)
static fileName findFile (const IOobject &io, const bool isGlobal=true)
static fileName findFile (const IOobject &io, const dictionary &dict, const bool isGlobal=true)
Static Public Attributes
static word nativeExt
Static Protected Member Functions
static string getLineNoComment (ISstream &is, const char comment='#')
template<class Container >
static List< surfZone > oneZone (const Container &container, const word &name="zone0")
static labelList getSelectedPatches (const surfZoneList &patches, const wordRes &allow, const wordRes &deny=wordRes())
static fileName relativeFilePath (const IOobject &io, const fileName &f, const bool isGlobal=true)
static fileName checkFile (const IOobject &io, const bool isGlobal=true)
static fileName checkFile (const IOobject &io, const dictionary &dict, const bool isGlobal=true)
Friends
class ::Foam::triSurface
Detailed Description
A collection of helper functions for reading/writing surface formats.
Source files
surfaceFormatsCore.H
surfaceFormatsCore.C
Definition at line 62 of file surfaceFormatsCore.H.
Constructor & Destructor Documentation
surfaceFormatsCore()
surfaceFormatsCore () default
~surfaceFormatsCore()
virtual ~surfaceFormatsCore () virtual default
Member Function Documentation
getLineNoComment()
Foam::string getLineNoComment (ISstream & is, const char comment = '#') static protected
Definition at line 35 of file surfaceFormatsCore.C.
oneZone()
template<class Container > static List< surfZone > oneZone (const Container & container, const word & name = "zone0") inline static protected
Definition at line 78 of file surfaceFormatsCore.H.
References Foam::name(), and UPtrList< T >::size().
getSelectedPatches()
Foam::labelList getSelectedPatches (const surfZoneList & patches, const wordRes & allow, const wordRes & deny = wordRes()) static protected
Definition at line 52 of file surfaceFormatsCore.C.
References Foam::stringListOps::findMatching(), and patches.
Referenced by MeshedSurface< Face >::subsetMesh().
relativeFilePath()
Foam::fileName relativeFilePath (const IOobject & io, const fileName & f, const bool isGlobal = true) static protected
Parameters
isGlobal resolve as a global file
Definition at line 170 of file surfaceFormatsCore.C.
References string::expand(), f(), Foam::fileHandler, io(), fileName::isAbsolute(), and word::null.
Referenced by triSurface::relativeFilePath().
checkFile() [1/2]
Foam::fileName checkFile (const IOobject & io, const bool isGlobal = true) static protected
Parameters
isGlobal resolve as a global file
Definition at line 249 of file surfaceFormatsCore.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, io(), Foam::nl, and word::null.
Referenced by triSurface::checkFile(), triSurface::checkFile(), and UnsortedMeshedSurface< Face >::UnsortedMeshedSurface().
checkFile() [2/2]
Foam::fileName checkFile (const IOobject & io, const dictionary & dict, const bool isGlobal = true) static protected
Parameters
isGlobal resolve as a global file
Definition at line 274 of file surfaceFormatsCore.C.
References dict, Foam::exists(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, io(), keyType::LITERAL, Foam::nl, and word::null.
checkSupport()
bool checkSupport (const wordHashSet & available, const word & fileType, const bool verbose = false, const char * functionName = nullptr) static
Definition at line 318 of file surfaceFormatsCore.C.
References Foam::flatOutput(), HashTable< T, Key, Hash >::found(), Foam::Info, Foam::nl, and HashTable< T, Key, Hash >::sortedToc().
Referenced by MeshedSurface< Face >::canReadType(), triSurface::canReadType(), UnsortedMeshedSurface< Face >::canReadType(), MeshedSurface< Face >::canWriteType(), MeshedSurfaceProxy< Face >::canWriteType(), triSurface::canWriteType(), and UnsortedMeshedSurface< Face >::canWriteType().
findFile() [1/2]
Foam::fileName findFile (const IOobject & io, const bool isGlobal = true) static
Parameters
isGlobal resolve as a global file
Definition at line 196 of file surfaceFormatsCore.C.
References Foam::exists(), io(), and word::null.
Referenced by triSurface::findFile(), and triSurface::findFile().
findFile() [2/2]
Foam::fileName findFile (const IOobject & io, const dictionary & dict, const bool isGlobal = true) static
Parameters
isGlobal resolve as a global file
Definition at line 218 of file surfaceFormatsCore.C.
References dict, Foam::exists(), io(), keyType::LITERAL, and word::null.
Friends And Related Symbol Documentation
::Foam::triSurface
friend class ::Foam::triSurface friend
Definition at line 67 of file surfaceFormatsCore.H.
Member Data Documentation
nativeExt
Foam::word nativeExt static
Definition at line 136 of file surfaceFormatsCore.H.
The documentation for this class was generated from the following files:
src/surfMesh/surfaceFormats/surfaceFormatsCore.H
src/surfMesh/surfaceFormats/surfaceFormatsCore.C