OpenFOAM: shapeSensitivitiesBase Class Reference
shapeSensitivitiesBase Class Reference
#include <shapeSensitivitiesBase.H>
Public Member Functions
TypeName ("shapeSensitivitiesBase")
shapeSensitivitiesBase (const fvMesh &mesh, const dictionary &dict)
virtual ~shapeSensitivitiesBase ()=default
const labelHashSet & sensitivityPatchIDs () const
void setSensitivityPatchIDs (const labelHashSet &sensPatchIDs)
void clearSensitivities ()
void write ()
void setSuffix (const word &suffix)
tmp< volVectorField > getWallFaceSensVec ()
tmp< volScalarField > getWallFaceSensNormal ()
tmp< volVectorField > getWallFaceSensNormalVec ()
tmp< pointVectorField > getWallPointSensVec ()
tmp< pointScalarField > getWallPointSensNormal ()
tmp< pointVectorField > getWallPointSensNormalVec ()
virtual const boundaryVectorField & getWallFaceSensVecBoundary () const
virtual const boundaryScalarField & getWallFaceSensNormalBoundary () const
virtual const boundaryVectorField & getWallFaceSensNormalVecBoundary () const
Protected Member Functions
template<class Type >
void constructAndWriteSensitivityField (const autoPtr< typename GeometricField< Type, fvPatchField, volMesh >::Boundary > &sensFieldPtr, const word &name) const
template<class Type >
void constructAndWriteSensitivtyPointField (const autoPtr< List< Field< Type > > > &sensFieldPtr, const word &name) const
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > constructVolSensitivtyField (const autoPtr< typename GeometricField< Type, fvPatchField, volMesh >::Boundary > &sensFieldPtr, const word &name) const
void writeFaceBasedSens () const
void writePointBasedSens () const
Protected Attributes
const fvMesh & meshShape_
word surfaceFieldSuffix_
bool writeAllSurfaceFiles_
labelHashSet sensitivityPatchIDs_
autoPtr< boundaryVectorField > wallFaceSensVecPtr_
autoPtr< boundaryScalarField > wallFaceSensNormalPtr_
autoPtr< boundaryVectorField > wallFaceSensNormalVecPtr_
autoPtr< pointBoundaryVectorField > wallPointSensVecPtr_
autoPtr< pointBoundaryScalarField > wallPointSensNormalPtr_
autoPtr< pointBoundaryVectorField > wallPointSensNormalVecPtr_
Detailed Description
Definition at line 59 of file shapeSensitivitiesBase.H.
Constructor & Destructor Documentation
shapeSensitivitiesBase()
shapeSensitivitiesBase (const fvMesh & mesh, const dictionary & dict)
Definition at line 117 of file shapeSensitivitiesBase.C.
~shapeSensitivitiesBase()
virtual ~shapeSensitivitiesBase () virtual default
Member Function Documentation
constructAndWriteSensitivityField()
template<class Type > void constructAndWriteSensitivityField (const autoPtr< typename GeometricField< Type, fvPatchField, volMesh >::Boundary > & sensFieldPtr, const word & name) const protected
Definition at line 33 of file shapeSensitivitiesBaseTemplates.C.
References Foam::dimless, shapeSensitivitiesBase::meshShape_, Foam::name(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, shapeSensitivitiesBase::sensitivityPatchIDs_, and Foam::Zero.
constructAndWriteSensitivtyPointField()
template<class Type > void constructAndWriteSensitivtyPointField (const autoPtr< List< Field< Type > > > & sensFieldPtr, const word & name) const protected
Definition at line 66 of file shapeSensitivitiesBaseTemplates.C.
References Foam::dimless, shapeSensitivitiesBase::meshShape_, Foam::name(), MeshObject< polyMesh, UpdateableMeshObject, pointMesh >::New(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, shapeSensitivitiesBase::sensitivityPatchIDs_, and Foam::Zero.
constructVolSensitivtyField()
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > constructVolSensitivtyField (const autoPtr< typename GeometricField< Type, fvPatchField, volMesh >::Boundary > & sensFieldPtr, const word & name) const protected
Definition at line 105 of file shapeSensitivitiesBaseTemplates.C.
References forAll, shapeSensitivitiesBase::meshShape_, Foam::name(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, and shapeSensitivitiesBase::sensitivityPatchIDs_.
writeFaceBasedSens()
void writeFaceBasedSens () const protected
Definition at line 36 of file shapeSensitivitiesBase.C.
References shapeSensitivitiesBase::surfaceFieldSuffix_, shapeSensitivitiesBase::wallFaceSensNormalPtr_, shapeSensitivitiesBase::wallFaceSensNormalVecPtr_, shapeSensitivitiesBase::wallFaceSensVecPtr_, and shapeSensitivitiesBase::writeAllSurfaceFiles_.
writePointBasedSens()
void writePointBasedSens () const protected
Definition at line 73 of file shapeSensitivitiesBase.C.
TypeName()
TypeName ("shapeSensitivitiesBase")
sensitivityPatchIDs()
const Foam::labelHashSet & sensitivityPatchIDs () const
Definition at line 153 of file shapeSensitivitiesBase.C.
setSensitivityPatchIDs()
void setSensitivityPatchIDs (const labelHashSet & sensPatchIDs)
Definition at line 159 of file shapeSensitivitiesBase.C.
clearSensitivities()
void clearSensitivities ()
Definition at line 168 of file shapeSensitivitiesBase.C.
References VectorSpace< Form, Cmpt, Ncmpts >::zero.
Referenced by sensitivitySurface::clearSensitivities(), sensitivitySurfacePoints::clearSensitivities(), and shapeSensitivities::clearSensitivities().
write()
void write ()
Definition at line 209 of file shapeSensitivitiesBase.C.
Referenced by sensitivitySurface::write(), sensitivitySurfacePoints::write(), and shapeSensitivities::write().
setSuffix()
void setSuffix (const word & suffix)
Definition at line 216 of file shapeSensitivitiesBase.C.
Referenced by sensitivitySurface::setSuffixName(), and sensitivitySurfacePoints::setSuffixName().
getWallFaceSensVec()
Foam::tmp< Foam::volVectorField > getWallFaceSensVec ()
Definition at line 223 of file shapeSensitivitiesBase.C.
References Foam::dimless, Foam::endl(), and WarningInFunction.
getWallFaceSensNormal()
Foam::tmp< Foam::volScalarField > getWallFaceSensNormal ()
Definition at line 254 of file shapeSensitivitiesBase.C.
References Foam::dimless, Foam::endl(), and WarningInFunction.
getWallFaceSensNormalVec()
Foam::tmp< Foam::volVectorField > getWallFaceSensNormalVec ()
Definition at line 284 of file shapeSensitivitiesBase.C.
References Foam::dimless, Foam::endl(), and WarningInFunction.
getWallPointSensVec()
Foam::tmp< Foam::pointVectorField > getWallPointSensVec ()
Definition at line 316 of file shapeSensitivitiesBase.C.
getWallPointSensNormal()
Foam::tmp< Foam::pointScalarField > getWallPointSensNormal ()
Definition at line 326 of file shapeSensitivitiesBase.C.
getWallPointSensNormalVec()
Foam::tmp< Foam::pointVectorField > getWallPointSensNormalVec ()
Definition at line 336 of file shapeSensitivitiesBase.C.
getWallFaceSensVecBoundary()
const Foam::boundaryVectorField & getWallFaceSensVecBoundary () const virtual
Definition at line 346 of file shapeSensitivitiesBase.C.
getWallFaceSensNormalBoundary()
const Foam::boundaryScalarField & getWallFaceSensNormalBoundary () const virtual
Definition at line 353 of file shapeSensitivitiesBase.C.
getWallFaceSensNormalVecBoundary()
const Foam::boundaryVectorField & getWallFaceSensNormalVecBoundary () const virtual
Definition at line 360 of file shapeSensitivitiesBase.C.
Member Data Documentation
meshShape_
const fvMesh& meshShape_ protected
Definition at line 65 of file shapeSensitivitiesBase.H.
Referenced by shapeSensitivitiesBase::constructAndWriteSensitivityField(), shapeSensitivitiesBase::constructAndWriteSensitivtyPointField(), and shapeSensitivitiesBase::constructVolSensitivtyField().
surfaceFieldSuffix_
word surfaceFieldSuffix_ protected
Definition at line 66 of file shapeSensitivitiesBase.H.
Referenced by shapeSensitivitiesBase::writeFaceBasedSens().
writeAllSurfaceFiles_
bool writeAllSurfaceFiles_ protected
Definition at line 67 of file shapeSensitivitiesBase.H.
Referenced by shapeSensitivitiesBase::writeFaceBasedSens().
sensitivityPatchIDs_
labelHashSet sensitivityPatchIDs_ protected
Definition at line 70 of file shapeSensitivitiesBase.H.
Referenced by shapeSensitivitiesBase::constructAndWriteSensitivityField(), shapeSensitivitiesBase::constructAndWriteSensitivtyPointField(), and shapeSensitivitiesBase::constructVolSensitivtyField().
wallFaceSensVecPtr_
autoPtr<boundaryVectorField> wallFaceSensVecPtr_ protected
Definition at line 79 of file shapeSensitivitiesBase.H.
Referenced by shapeSensitivitiesBase::writeFaceBasedSens().
wallFaceSensNormalPtr_
autoPtr<boundaryScalarField> wallFaceSensNormalPtr_ protected
Definition at line 82 of file shapeSensitivitiesBase.H.
Referenced by shapeSensitivitiesBase::writeFaceBasedSens().
wallFaceSensNormalVecPtr_
autoPtr<boundaryVectorField> wallFaceSensNormalVecPtr_ protected
Definition at line 85 of file shapeSensitivitiesBase.H.
Referenced by shapeSensitivitiesBase::writeFaceBasedSens().
wallPointSensVecPtr_
autoPtr<pointBoundaryVectorField> wallPointSensVecPtr_ protected
Definition at line 91 of file shapeSensitivitiesBase.H.
wallPointSensNormalPtr_
autoPtr<pointBoundaryScalarField> wallPointSensNormalPtr_ protected
Definition at line 94 of file shapeSensitivitiesBase.H.
wallPointSensNormalVecPtr_
autoPtr<pointBoundaryVectorField> wallPointSensNormalVecPtr_ protected
Definition at line 97 of file shapeSensitivitiesBase.H.
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/optimisation/adjointSensitivity/shapeSensitivitiesBase/shapeSensitivitiesBase.H
src/optimisation/adjointOptimisation/adjoint/optimisation/adjointSensitivity/shapeSensitivitiesBase/shapeSensitivitiesBase.C
src/optimisation/adjointOptimisation/adjoint/optimisation/adjointSensitivity/shapeSensitivitiesBase/shapeSensitivitiesBaseTemplates.C