OpenFOAM: solidMixtureProperties Class Reference
solidMixtureProperties Class Reference
A mixture of solids.
#include <solidMixtureProperties.H>
Public Member Functions
solidMixtureProperties (const dictionary &)
solidMixtureProperties (const solidMixtureProperties &lm)
virtual autoPtr< solidMixtureProperties > clone () const
virtual ~solidMixtureProperties ()=default
const List< word > & components () const
const PtrList< solidProperties > & properties () const
label size () const
scalar rho (const scalarField &Y) const
scalar Cp (const scalarField &Y) const
Static Public Member Functions
static autoPtr< solidMixtureProperties > New (const dictionary &)
Detailed Description
A mixture of solids.
An example of a two component solid mixture:
    <parentDictionary>
    {
        C;
        ash
        {
            //... user defined properties for ash
        }
    }
Source files
solidMixtureProperties.H
solidMixtureProperties.C
See also
Foam::solidProperties
Definition at line 65 of file solidMixtureProperties.H.
Constructor & Destructor Documentation
solidMixtureProperties() [1/2]
solidMixtureProperties (const dictionary & dict)
Definition at line 26 of file solidMixtureProperties.C.
References dict, dictionary::findDict(), forAll, solidProperties::New(), PtrList< T >::set(), PtrList< T >::setSize(), and UList< T >::size().
solidMixtureProperties() [2/2]
solidMixtureProperties (const solidMixtureProperties & lm)
Definition at line 60 of file solidMixtureProperties.C.
~solidMixtureProperties()
virtual ~solidMixtureProperties () virtual default
Member Function Documentation
clone()
virtual autoPtr< solidMixtureProperties > clone () const inline virtual
Definition at line 87 of file solidMixtureProperties.H.
References autoPtr< T >::New().
New()
Foam::autoPtr< Foam::solidMixtureProperties > New (const dictionary & thermophysicalProperties) static
Definition at line 72 of file solidMixtureProperties.C.
References autoPtr< T >::New().
Referenced by SLGThermo::SLGThermo().
components()
const List< word > & components () const inline
Definition at line 106 of file solidMixtureProperties.H.
properties()
const PtrList< solidProperties > & properties () const inline
Definition at line 112 of file solidMixtureProperties.H.
size()
label size () const inline
Definition at line 118 of file solidMixtureProperties.H.
References UPtrList< T >::size().
rho()
Foam::scalar rho (const scalarField & Y) const
Definition at line 83 of file solidMixtureProperties.C.
References forAll, and Y.
Cp()
Foam::scalar Cp (const scalarField & Y) const
Definition at line 96 of file solidMixtureProperties.C.
References Cp, forAll, and Y.
The documentation for this class was generated from the following files:
src/thermophysicalModels/thermophysicalProperties/solidProperties/solidMixtureProperties/solidMixtureProperties.H
src/thermophysicalModels/thermophysicalProperties/solidProperties/solidMixtureProperties/solidMixtureProperties.C