OpenFOAM: eddy Class Reference
eddy Class Reference
Class to describe eddies for the turbulentDFSEMInletFvPatchVectorField boundary condition.
#include <eddy.H>
Public Member Functions
eddy ()
eddy (Istream &is)
eddy (const label patchFaceI, const point &position0, const scalar x, const scalar sigmaX, const symmTensor &R, Random &rndGen)
eddy (const eddy &e)
label patchFaceI () const noexcept
const point & position0 () const noexcept
scalar x () const noexcept
const vector & sigma () const noexcept
const vector & alpha () const noexcept
const tensor & Rpg () const noexcept
scalar c1 () const noexcept
point position (const vector &n) const
label dir1 () const noexcept
vector epsilon (Random &rndGen) const
scalar volume () const
void move (const scalar dx)
boundBox bounds (const bool global=true) const
vector uPrime (const point &xp, const vector &n) const
void writeCentreOBJ (const vector &n, Ostream &os) const
label writeSurfaceOBJ (const label pointOffset, const vector &n, Ostream &os) const
void operator= (const eddy &e)
Static Public Attributes
static int debug = 0
Friends
bool operator== (const eddy &a, const eddy &b)
bool operator!= (const eddy &a, const eddy &b)
Istream & operator>> (Istream &is, eddy &e)
Ostream & operator<< (Ostream &os, const eddy &e)
Detailed Description
Class to describe eddies for the turbulentDFSEMInletFvPatchVectorField boundary condition.
Source files
eddy.H
eddy.C
eddyI.H
eddyIO.C
Definition at line 63 of file eddy.H.
Constructor & Destructor Documentation
eddy() [1/4]
eddy ()
Definition at line 110 of file eddy.C.
eddy() [2/4]
eddy (Istream & is)
Definition at line 27 of file eddyIO.C.
References FUNCTION_NAME, and Foam::readLabel().
eddy() [3/4]
eddy (const label patchFaceI, const point & position0, const scalar x, const scalar sigmaX, const symmTensor & R, Random & rndGen)
Definition at line 123 of file eddy.C.
References Foam::cmptAv(), Foam::cmptMin(), Foam::cmptProduct(), eddy::debug, e, Foam::eigenValues(), Foam::eigenVectors(), Foam::endl(), epsilon, forAll, found, lambda(), Foam::Pout, R, rndGen, dimensioned< Type >::T(), Tensor< Cmpt >::T(), and WarningInFunction.
eddy() [4/4]
eddy (const eddy & e)
Definition at line 209 of file eddy.C.
Member Function Documentation
patchFaceI()
Foam::label patchFaceI () const inline noexcept
Definition at line 35 of file eddyI.H.
position0()
const Foam::point & position0 () const inline noexcept
Definition at line 41 of file eddyI.H.
x()
Foam::scalar x () const inline noexcept
Definition at line 47 of file eddyI.H.
sigma()
const Foam::vector & sigma () const inline noexcept
Definition at line 53 of file eddyI.H.
alpha()
const Foam::vector & alpha () const inline noexcept
Definition at line 59 of file eddyI.H.
Rpg()
const Foam::tensor & Rpg () const inline noexcept
Definition at line 65 of file eddyI.H.
c1()
Foam::scalar c1 () const inline noexcept
Definition at line 71 of file eddyI.H.
position()
Foam::point position (const vector & n) const inline
Definition at line 77 of file eddyI.H.
References n.
dir1()
label dir1 () const inline noexcept
Definition at line 174 of file eddy.H.
epsilon()
Foam::vector epsilon (Random & rndGen) const inline
Definition at line 83 of file eddyI.H.
References rndGen.
volume()
Foam::scalar volume () const inline
Definition at line 89 of file eddyI.H.
References Foam::cmptProduct(), and Foam::constant::mathematical::pi().
move()
void move (const scalar dx) inline
Definition at line 95 of file eddyI.H.
bounds()
Foam::boundBox bounds (const bool global = true) const inline
Definition at line 101 of file eddyI.H.
References boundBox::max(), and boundBox::min().
uPrime()
Foam::vector uPrime (const point & xp, const vector & n) const
Definition at line 224 of file eddy.C.
References Foam::cmptDivide(), Foam::cmptMultiply(), Foam::mag(), n, VectorSpace< Form, Cmpt, Ncmpts >::one, rp(), and VectorSpace< Form, Cmpt, Ncmpts >::zero.
writeCentreOBJ()
void writeCentreOBJ (const vector & n, Ostream & os) const
Definition at line 248 of file eddy.C.
References n, Foam::nl, os(), and p.
writeSurfaceOBJ()
Foam::label writeSurfaceOBJ (const label pointOffset, const vector & n, Ostream & os) const
Definition at line 259 of file eddy.C.
References Foam::cos(), forAll, n, Foam::nl, os(), p, Foam::constant::mathematical::pi(), s(), Foam::sin(), Foam::sqr(), Foam::sqrt(), Foam::constant::mathematical::twoPi(), x, and Foam::Zero.
operator=()
void operator= (const eddy & e)
Definition at line 44 of file eddyIO.C.
References e.
Friends And Related Symbol Documentation
operator==
bool operator== (const eddy & a, const eddy & b) friend
Definition at line 220 of file eddy.H.
operator!=
bool operator!= (const eddy & a, const eddy & b) friend
Definition at line 233 of file eddy.H.
operator>>
Istream & operator>> (Istream & is, eddy & e) friend
operator<<
Ostream & operator<< (Ostream & os, const eddy & e) friend
Member Data Documentation
debug
int debug = 0 static
Definition at line 141 of file eddy.H.
Referenced by eddy::eddy(), and turbulentDFSEMInletFvPatchVectorField::turbulentDFSEMInletFvPatchVectorField().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/turbulentDFSEMInlet/eddy/eddy.H
src/finiteVolume/fields/fvPatchFields/derived/turbulentDFSEMInlet/eddy/eddy.C
src/finiteVolume/fields/fvPatchFields/derived/turbulentDFSEMInlet/eddy/eddyI.H
src/finiteVolume/fields/fvPatchFields/derived/turbulentDFSEMInlet/eddy/eddyIO.C