OpenFOAM: procLduInterface Class Reference
procLduInterface Class Reference
IO interface for processorLduInterface.
#include <procLduInterface.H>
Public Member Functions
procLduInterface (const procLduInterface &)=delete
procLduInterface (const lduInterfaceField &interface, const scalarField &coeffs)
procLduInterface (Istream &is)
autoPtr< procLduInterface > clone ()
Static Public Member Functions
static autoPtr< procLduInterface > New (Istream &is)
Friends
class LUscalarMatrix
Ostream & operator<< (Ostream &, const procLduInterface &)
Detailed Description
IO interface for processorLduInterface.
Source files
procLduInterface.H
procLduInterface.C
Definition at line 53 of file procLduInterface.H.
Constructor & Destructor Documentation
procLduInterface() [1/3]
procLduInterface (const procLduInterface &) delete
procLduInterface() [2/3]
procLduInterface (const lduInterfaceField & interface, const scalarField & coeffs)
Definition at line 28 of file procLduInterface.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and interface().
procLduInterface() [3/3]
procLduInterface (Istream & is)
Definition at line 64 of file procLduInterface.C.
Member Function Documentation
clone()
autoPtr< procLduInterface > clone () inline
Definition at line 85 of file procLduInterface.H.
References NotImplemented.
New()
static autoPtr< procLduInterface > New (Istream & is) inline static
Definition at line 91 of file procLduInterface.H.
References autoPtr< T >::New().
Friends And Related Symbol Documentation
LUscalarMatrix
friend class LUscalarMatrix friend
Definition at line 66 of file procLduInterface.H.
operator<<
Ostream & operator<< (Ostream & , const procLduInterface &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/LUscalarMatrix/procLduInterface.H
src/OpenFOAM/matrices/LUscalarMatrix/procLduInterface.C