OpenFOAM: liquidMixtureProperties Class Reference
liquidMixtureProperties Class Reference
A mixture of liquids.
#include <liquidMixtureProperties.H>
Public Member Functions
liquidMixtureProperties (const dictionary &dict)
liquidMixtureProperties (const liquidMixtureProperties &lm)
virtual autoPtr< liquidMixtureProperties > clone () const
virtual ~liquidMixtureProperties ()=default
const List< word > & components () const
const PtrList< liquidProperties > & properties () const
label size () const
scalar Tc (const scalarField &X) const
scalar pvInvert (const scalar p, const scalarField &X) const
scalar Tpc (const scalarField &X) const
scalar Ppc (const scalarField &X) const
scalar Tpt (const scalarField &X) const
scalar omega (const scalarField &X) const
scalarField Xs (const scalar p, const scalar Tg, const scalar Tl, const scalarField &Xg, const scalarField &Xl) const
scalar W (const scalarField &X) const
scalarField Y (const scalarField &X) const
scalarField X (const scalarField &Y) const
scalar rho (const scalar p, const scalar T, const scalarField &X) const
scalar pv (const scalar p, const scalar T, const scalarField &X) const
scalar hl (const scalar p, const scalar T, const scalarField &X) const
scalar Cp (const scalar p, const scalar T, const scalarField &X) const
scalar sigma (const scalar p, const scalar T, const scalarField &X) const
scalar mu (const scalar p, const scalar T, const scalarField &X) const
scalar kappa (const scalar p, const scalar T, const scalarField &X) const
scalar D (const scalar p, const scalar T, const scalarField &X) const
Static Public Member Functions
static autoPtr< liquidMixtureProperties > New (const dictionary &)
Detailed Description
A mixture of liquids.
An example of a two component liquid mixture:
    <parentDictionary>
    {
        H2O; // employ default coefficients
        C7H16
        {
            // ... user defined properties for C7H16
        }
    }
Source files
liquidMixtureProperties.H
liquidMixtureProperties.C
See also
Foam::liquidProperties
Definition at line 64 of file liquidMixtureProperties.H.
Constructor & Destructor Documentation
liquidMixtureProperties() [1/2]
liquidMixtureProperties (const dictionary & dict)
Definition at line 33 of file liquidMixtureProperties.C.
References dict, dictionary::findDict(), forAll, liquidProperties::New(), PtrList< T >::set(), PtrList< T >::setSize(), and UList< T >::size().
liquidMixtureProperties() [2/2]
liquidMixtureProperties (const liquidMixtureProperties & lm)
Definition at line 70 of file liquidMixtureProperties.C.
~liquidMixtureProperties()
virtual ~liquidMixtureProperties () virtual default
Member Function Documentation
clone()
virtual autoPtr< liquidMixtureProperties > clone () const inline virtual
Definition at line 89 of file liquidMixtureProperties.H.
References autoPtr< T >::New().
New()
Foam::autoPtr< Foam::liquidMixtureProperties > New (const dictionary & thermophysicalProperties) static
Definition at line 83 of file liquidMixtureProperties.C.
References autoPtr< T >::New().
Referenced by SLGThermo::SLGThermo().
components()
const List< word > & components () const inline
Definition at line 108 of file liquidMixtureProperties.H.
properties()
const PtrList< liquidProperties > & properties () const inline
Definition at line 114 of file liquidMixtureProperties.H.
size()
label size () const inline
Definition at line 120 of file liquidMixtureProperties.H.
References UPtrList< T >::size().
Referenced by liquidFilmModel::correctThermoFields().
Tc()
Foam::scalar Tc (const scalarField & X) const
Definition at line 94 of file liquidMixtureProperties.C.
References forAll.
pvInvert()
Foam::scalar pvInvert (const scalar p, const scalarField & X) const
Definition at line 123 of file liquidMixtureProperties.C.
References Foam::endl(), Foam::nl, p, T, and WarningInFunction.
Tpc()
Foam::scalar Tpc (const scalarField & X) const
Definition at line 167 of file liquidMixtureProperties.C.
References forAll.
Ppc()
Foam::scalar Ppc (const scalarField & X) const
Definition at line 180 of file liquidMixtureProperties.C.
References forAll, and Foam::constant::thermodynamic::RR.
Tpt()
Foam::scalar Tpt (const scalarField & X) const
Definition at line 110 of file liquidMixtureProperties.C.
References forAll.
omega()
Foam::scalar omega (const scalarField & X) const
Definition at line 195 of file liquidMixtureProperties.C.
References forAll.
Xs()
Foam::scalarField Xs (const scalar p, const scalar Tg, const scalar Tl, const scalarField & Xg, const scalarField & Xl) const
Definition at line 208 of file liquidMixtureProperties.C.
References forAll, Foam::min(), p, and UPtrList< T >::size().
W()
Foam::scalar W (const scalarField & X) const
Definition at line 230 of file liquidMixtureProperties.C.
References forAll.
Y()
Foam::scalarField Y (const scalarField & X) const
Definition at line 243 of file liquidMixtureProperties.C.
References forAll, UList< T >::size(), and Y.
X()
Foam::scalarField X (const scalarField & Y) const
Definition at line 260 of file liquidMixtureProperties.C.
References forAll, UPtrList< T >::size(), and Y.
rho()
Foam::scalar rho (const scalar p, const scalar T, const scalarField & X) const
Definition at line 277 of file liquidMixtureProperties.C.
References forAll, Foam::min(), p, rho, and T.
Referenced by liquidFilmModel::correctThermoFields().
pv()
Foam::scalar pv (const scalar p, const scalar T, const scalarField & X) const
Definition at line 307 of file liquidMixtureProperties.C.
References forAll, Foam::min(), p, and T.
hl()
Foam::scalar hl (const scalar p, const scalar T, const scalarField & X) const
Definition at line 333 of file liquidMixtureProperties.C.
References forAll, Foam::min(), p, and T.
Cp()
Foam::scalar Cp (const scalar p, const scalar T, const scalarField & X) const
Definition at line 359 of file liquidMixtureProperties.C.
References Cp, forAll, Foam::min(), p, and T.
Referenced by liquidFilmModel::correctThermoFields().
sigma()
Foam::scalar sigma (const scalar p, const scalar T, const scalarField & X) const
Definition at line 385 of file liquidMixtureProperties.C.
References forAll, Foam::min(), p, UList< T >::size(), and T.
Referenced by liquidFilmModel::correctThermoFields().
mu()
Foam::scalar mu (const scalar p, const scalar T, const scalarField & X) const
Definition at line 422 of file liquidMixtureProperties.C.
References Foam::exp(), forAll, Foam::log(), Foam::min(), mu, p, and T.
Referenced by liquidFilmModel::correctThermoFields().
kappa()
Foam::scalar kappa (const scalar p, const scalar T, const scalarField & X) const
Definition at line 444 of file liquidMixtureProperties.C.
References forAll, Foam::min(), p, UList< T >::size(), and T.
D()
Foam::scalar D (const scalar p, const scalar T, const scalarField & X) const
Definition at line 490 of file liquidMixtureProperties.C.
References forAll, Foam::min(), p, and T.
The documentation for this class was generated from the following files:
src/thermophysicalModels/thermophysicalProperties/liquidProperties/liquidMixtureProperties/liquidMixtureProperties.H
src/thermophysicalModels/thermophysicalProperties/liquidProperties/liquidMixtureProperties/liquidMixtureProperties.C