OpenFOAM: cylindrical Class Reference
cylindrical Class Reference
A special purpose coordinateRotation that is generally for use in combination with a cylindricalCS when only the orientation of the local Z-axis is relevant.
#include <cylindricalRotation.H>
Public Member Functions
TypeNameNoDebug ("cylindrical")
cylindrical ()=default
cylindrical (const cylindrical &crot)
cylindrical (const vector &axis)
cylindrical (const dictionary &dict)
autoPtr< coordinateRotation > clone () const
virtual ~cylindrical ()=default
virtual void write (Ostream &os) const
virtual void writeEntry (const word &keyword, Ostream &os) const
Public Member Functions inherited from axes
TypeNameNoDebug ("axes")
axes ()
axes (const axes &crot)
axes (const vector &axis1, const vector &axis2, axisOrder order=E3_E1)
axes (const vector &axis)
axes (const dictionary &dict)
virtual ~axes ()=default
virtual void clear ()
virtual tensor R () const
Public Member Functions inherited from coordinateRotation
TypeNameNoDebug ("coordinateRotation")
declareRunTimeSelectionTable (autoPtr, coordinateRotation, dictionary,(const dictionary &dict),(dict))
virtual ~coordinateRotation ()=default
Static Public Member Functions
static tensor rotation (const vector &axis)
Static Public Member Functions inherited from axes
static tensor rotation (const vector &axis1, const vector &axis2, axisOrder order=E3_E1)
Static Public Member Functions inherited from coordinateRotation
static autoPtr< coordinateRotation > New (const word &modelType, const dictionary &dict)
static autoPtr< coordinateRotation > New (const dictionary &dict)
Additional Inherited Members
Public Types inherited from axes
enum axisOrder { E1_E2 , E2_E3 , E3_E1 , E3_E1_COMPAT }
Protected Member Functions inherited from axes
void read (const dictionary &dict)
Static Protected Member Functions inherited from coordinateRotation
static vector findOrthogonal (const vector &axis)
Protected Attributes inherited from axes
vector axis1_
vector axis2_
axisOrder order_
Detailed Description
A special purpose coordinateRotation that is generally for use in combination with a cylindricalCS when only the orientation of the local Z-axis is relevant.
Dictionary entries
Property Description Reqd Default
type Type name: cylindrical yes
axis The z-axis yes
e3 Alias for 'axis' no
Source files
cylindricalRotation.H
cylindricalRotation.C
Definition at line 79 of file cylindricalRotation.H.
Constructor & Destructor Documentation
cylindrical() [1/4]
cylindrical () default
cylindrical() [2/4]
cylindrical (const cylindrical & crot)
Definition at line 57 of file cylindricalRotation.C.
cylindrical() [3/4]
cylindrical (const vector & axis) explicit
Definition at line 63 of file cylindricalRotation.C.
cylindrical() [4/4]
cylindrical (const dictionary & dict) explicit
Definition at line 69 of file cylindricalRotation.C.
~cylindrical()
virtual ~cylindrical () virtual default
Member Function Documentation
TypeNameNoDebug()
TypeNameNoDebug ("cylindrical")
clone()
autoPtr< coordinateRotation > clone () const inline virtual
Reimplemented from axes.
Definition at line 105 of file cylindricalRotation.H.
rotation()
Foam::tensor rotation (const vector & axis) static
Definition at line 45 of file cylindricalRotation.C.
References axes::E3_E1, axes::rotation(), and Foam::Zero.
write()
void write (Ostream & os) const virtual
Reimplemented from axes.
Definition at line 77 of file cylindricalRotation.C.
References os(), and Foam::type().
writeEntry()
void writeEntry (const word & keyword, Ostream & os) const virtual
Reimplemented from axes.
Definition at line 83 of file cylindricalRotation.C.
References os(), and Foam::type().
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/coordinate/rotation/cylindricalRotation.H
src/OpenFOAM/primitives/coordinate/rotation/cylindricalRotation.C