OpenFOAM: NicenoKEqn< BasicTurbulenceModel > Class Template Reference
NicenoKEqn< BasicTurbulenceModel > Class Template Reference
Turbulence models » LES turbulence
One-equation SGS model for the continuous phase in a two-phase system including bubble-generated turbulence.
#include <NicenoKEqn.H>
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from kEqn< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from LESeddyViscosity< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from eddyViscosity< LESModel< BasicTurbulenceModel > >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from linearViscousStress< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("NicenoKEqn")
NicenoKEqn (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
virtual ~NicenoKEqn ()=default
virtual bool read ()
Public Member Functions inherited from kEqn< BasicTurbulenceModel >
TypeName ("kEqn")
kEqn (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
virtual ~kEqn ()=default
virtual tmp< volScalarField > k () const
tmp< volScalarField > DkEff () const
virtual void correct ()
Public Member Functions inherited from LESeddyViscosity< BasicTurbulenceModel >
LESeddyViscosity (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
virtual ~LESeddyViscosity ()=default
Public Member Functions inherited from eddyViscosity< LESModel< BasicTurbulenceModel > >
eddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~eddyViscosity ()=default
virtual tmp< volScalarField > nut () const
virtual tmp< scalarField > nut (const label patchi) const
virtual tmp< volSymmTensorField > R () const
virtual void validate ()
Public Member Functions inherited from linearViscousStress< BasicTurbulenceModel >
linearViscousStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~linearViscousStress ()=default
virtual tmp< volSymmTensorField > devRhoReff () const
virtual tmp< volSymmTensorField > devRhoReff (const volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Protected Member Functions
virtual void correctNut ()
tmp< volScalarField > bubbleG () const
tmp< volScalarField > phaseTransferCoeff () const
virtual tmp< fvScalarMatrix > kSource () const
Protected Member Functions inherited from kEqn< BasicTurbulenceModel >
kEqn (const kEqn &)=delete
void operator= (const kEqn &)=delete
Protected Attributes
dimensionedScalar alphaInversion_
dimensionedScalar Cp_
dimensionedScalar Cmub_
Protected Attributes inherited from kEqn< BasicTurbulenceModel >
volScalarField k_
dimensionedScalar Ck_
Protected Attributes inherited from eddyViscosity< LESModel< BasicTurbulenceModel > >
volScalarField nut_
Detailed Description
template<class BasicTurbulenceModel>
class Foam::LESModels::NicenoKEqn< BasicTurbulenceModel >
One-equation SGS model for the continuous phase in a two-phase system including bubble-generated turbulence.
Reference:
    Niceno, B., Dhotre, M. T., & Deen, N. G. (2008).
    One-equation sub-grid scale (SGS) modelling for
    EulerEuler large eddy simulation (EELES) of dispersed bubbly flow.
    Chemical Engineering Science, 63(15), 3923-3931.
The default model coefficients are:
    NicenoKEqnCoeffs
    {
        Ck              0.094;
        Ce              1.048;
        alphaInversion  0.3;
        Cp              Ck;
        Cmub            0.6;
    }
Source files
NicenoKEqn.H
NicenoKEqn.C
Definition at line 74 of file NicenoKEqn.H.
Member Typedef Documentation
alphaField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 123 of file NicenoKEqn.H.
rhoField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 124 of file NicenoKEqn.H.
transportModel
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 125 of file NicenoKEqn.H.
Constructor & Destructor Documentation
NicenoKEqn()
template<class BasicTurbulenceModel > NicenoKEqn (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Definition at line 37 of file NicenoKEqn.C.
References Foam::type().
~NicenoKEqn()
template<class BasicTurbulenceModel > virtual ~NicenoKEqn () virtual default
Member Function Documentation
correctNut()
template<class BasicTurbulenceModel > void correctNut () protected virtual
Reimplemented from kEqn< BasicTurbulenceModel >.
Definition at line 151 of file NicenoKEqn.C.
References delta, Foam::mag(), options::New(), and Foam::sqrt().
bubbleG()
template<class BasicTurbulenceModel > tmp< volScalarField > bubbleG () const protected
Definition at line 169 of file NicenoKEqn.C.
References drag, fluid, Foam::mag(), liquid::rho(), and Foam::sqr().
phaseTransferCoeff()
template<class BasicTurbulenceModel > tmp< volScalarField > phaseTransferCoeff () const protected
Definition at line 194 of file NicenoKEqn.C.
References alpha, turbulenceModel::k(), Foam::max(), Foam::min(), rho, Foam::sqrt(), and U.
kSource()
template<class BasicTurbulenceModel > tmp< fvScalarMatrix > kSource () const protected virtual
Reimplemented from kEqn< BasicTurbulenceModel >.
Definition at line 216 of file NicenoKEqn.C.
References alpha, rho, and Foam::fvm::Sp().
TypeName()
template<class BasicTurbulenceModel > TypeName ("NicenoKEqn< BasicTurbulenceModel >")
read()
template<class BasicTurbulenceModel > bool read () virtual
Reimplemented from kEqn< BasicTurbulenceModel >.
Definition at line 103 of file NicenoKEqn.C.
Member Data Documentation
alphaInversion_
template<class BasicTurbulenceModel > dimensionedScalar alphaInversion_ protected
Definition at line 108 of file NicenoKEqn.H.
Cp_
template<class BasicTurbulenceModel > dimensionedScalar Cp_ protected
Definition at line 109 of file NicenoKEqn.H.
Cmub_
template<class BasicTurbulenceModel > dimensionedScalar Cmub_ protected
Definition at line 110 of file NicenoKEqn.H.
The documentation for this class was generated from the following files:
src/TurbulenceModels/phaseCompressible/LES/Niceno/NicenoKEqn.H
src/TurbulenceModels/phaseCompressible/LES/Niceno/NicenoKEqn.C