OpenFOAM: surfactantProperties Class Reference
surfactantProperties Class Reference
#include <surfactantProperties.H>
Public Member Functions
surfactantProperties (const dictionary &dict)
const dimensionedScalar & bulkConc () const
const dimensionedScalar & saturatedConc () const
const dimensionedScalar & adsorptionCoeff () const
const dimensionedScalar & desorptionCoeff () const
const dimensionedScalar & bulkDiffusion () const
const dimensionedScalar & diffusion () const
const dimensionedScalar & T () const
const dimensionedScalar & R () const
const dimensionedScalar & equilibriumConc () const
Switch soluble () const
tmp< areaScalarField > dSigma (const areaScalarField &surfactConc) const
Detailed Description
Definition at line 46 of file surfactantProperties.H.
Constructor & Destructor Documentation
surfactantProperties()
surfactantProperties (const dictionary & dict) inline explicit
Definition at line 85 of file surfactantProperties.H.
Member Function Documentation
bulkConc()
const dimensionedScalar & bulkConc () const inline
Definition at line 111 of file surfactantProperties.H.
saturatedConc()
const dimensionedScalar & saturatedConc () const inline
Definition at line 117 of file surfactantProperties.H.
Referenced by surfactantProperties::dSigma().
adsorptionCoeff()
const dimensionedScalar & adsorptionCoeff () const inline
Definition at line 123 of file surfactantProperties.H.
desorptionCoeff()
const dimensionedScalar & desorptionCoeff () const inline
Definition at line 129 of file surfactantProperties.H.
bulkDiffusion()
const dimensionedScalar & bulkDiffusion () const inline
Definition at line 135 of file surfactantProperties.H.
diffusion()
const dimensionedScalar & diffusion () const inline
Definition at line 141 of file surfactantProperties.H.
T()
const dimensionedScalar & T () const inline
Definition at line 147 of file surfactantProperties.H.
Referenced by surfactantProperties::dSigma().
R()
const dimensionedScalar & R () const inline
Definition at line 153 of file surfactantProperties.H.
Referenced by surfactantProperties::dSigma().
equilibriumConc()
const dimensionedScalar & equilibriumConc () const inline
Definition at line 159 of file surfactantProperties.H.
soluble()
Switch soluble () const inline
Definition at line 165 of file surfactantProperties.H.
dSigma()
tmp< areaScalarField > dSigma (const areaScalarField & surfactConc) const inline
Definition at line 171 of file surfactantProperties.H.
References Foam::log(), tmp< T >::New(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, surfactantProperties::R(), surfactantProperties::saturatedConc(), and surfactantProperties::T().
The documentation for this class was generated from the following file:
src/dynamicFaMesh/interfaceTrackingFvMesh/surfactantProperties.H