OpenFOAM: waxSolventEvaporation Class Reference
waxSolventEvaporation Class Reference
#include <waxSolventEvaporation.H>
Public Member Functions
TypeName ("waxSolventEvaporation")
waxSolventEvaporation (surfaceFilmRegionModel &film, const dictionary &dict)
virtual ~waxSolventEvaporation ()
virtual void correctModel (const scalar dt, scalarField &availableMass, scalarField &dMass, scalarField &dEnergy)
Public Member Functions inherited from phaseChangeModel
TypeName ("phaseChangeModel")
declareRunTimeSelectionTable (autoPtr, phaseChangeModel, dictionary,(surfaceFilmRegionModel &film, const dictionary &dict),(film, dict))
phaseChangeModel (surfaceFilmRegionModel &film)
phaseChangeModel (const word &modelType, surfaceFilmRegionModel &film, const dictionary &dict)
virtual ~phaseChangeModel ()
virtual void correct (const scalar dt, scalarField &availableMass, volScalarField &dMass, volScalarField &dEnergy)
virtual void info (Ostream &os) const
Public Member Functions inherited from filmSubModelBase
filmSubModelBase (surfaceFilmRegionModel &film)
filmSubModelBase (surfaceFilmRegionModel &film, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
filmSubModelBase (const word &modelName, surfaceFilmRegionModel &film, const dictionary &dict, const word &baseName, const word &modelType)
virtual ~filmSubModelBase ()
virtual bool writeTime () const
const surfaceFilmRegionModel & film () const
surfaceFilmRegionModel & film ()
template<class FilmType >
const FilmType & filmType () const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
subModelBase (const subModelBase &smb)
virtual ~subModelBase ()=default
const word & modelName () const
const dictionary & dict () const
const word & baseName () const
const word & modelType () const
const dictionary & coeffDict () const
const dictionary & properties () const
virtual bool defaultCoeffs (const bool printMsg) const
virtual bool active () const
virtual void cacheFields (const bool store)
virtual fileName localPath () const
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
bool getModelDict (const word &entryName, dictionary &dict) const
template<class Type >
bool getModelProperty (const word &entryName, Type &value) const
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
virtual void write (Ostream &os) const
Protected Member Functions
scalar Sh (const scalar Re, const scalar Sc) const
template<class YInfType >
void correctModel (const scalar dt, scalarField &availableMass, scalarField &dMass, scalarField &dEnergy, const YInfType &YInf)
waxSolventEvaporation (const waxSolventEvaporation &)=delete
void operator= (const waxSolventEvaporation &)=delete
Protected Member Functions inherited from subModelBase
bool inLine () const
Protected Attributes
uniformDimensionedScalarField Wwax_
uniformDimensionedScalarField Wsolvent_
uniformDimensionedScalarField Ysolvent0_
volScalarField Ysolvent_
const scalar deltaMin_
const scalar L_
const scalar TbFactor_
bool YInfZero_
autoPtr< Function1< scalar > > activityCoeff_
Protected Attributes inherited from phaseChangeModel
scalar latestMassPC_
scalar totalMassPC_
Protected Attributes inherited from filmSubModelBase
surfaceFilmRegionModel & filmModel_
Protected Attributes inherited from subModelBase
const word modelName_
dictionary & properties_
const dictionary dict_
const word baseName_
const word modelType_
const dictionary coeffDict_
Additional Inherited Members
Static Public Member Functions inherited from phaseChangeModel
static autoPtr< phaseChangeModel > New (surfaceFilmRegionModel &film, const dictionary &dict)
Public Attributes inherited from subModelBase
bool log
Detailed Description
Definition at line 52 of file waxSolventEvaporation.H.
Constructor & Destructor Documentation
waxSolventEvaporation() [1/2]
waxSolventEvaporation (const waxSolventEvaporation &) protected delete
waxSolventEvaporation() [2/2]
waxSolventEvaporation (surfaceFilmRegionModel & film, const dictionary & dict)
Definition at line 73 of file waxSolventEvaporation.C.
~waxSolventEvaporation()
~waxSolventEvaporation () virtual
Definition at line 136 of file waxSolventEvaporation.C.
Member Function Documentation
Sh()
scalar Sh (const scalar Re, const scalar Sc) const protected
Definition at line 54 of file waxSolventEvaporation.C.
References Foam::cbrt(), Foam::pow(), Foam::Re(), and Foam::sqrt().
Referenced by waxSolventEvaporation::correctModel().
correctModel() [1/2]
template<class YInfType > void correctModel (const scalar dt, scalarField & availableMass, scalarField & dMass, scalarField & dEnergy, const YInfType & YInf) protected
Definition at line 143 of file waxSolventEvaporation.C.
References waxSolventEvaporation::activityCoeff_, GeometricField< Type, PatchField, GeoMesh >::clamp_range(), filmThermoModel::D(), Foam::fvm::ddt(), delta, waxSolventEvaporation::deltaMin_, Foam::dimDensity, DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimTime, Foam::dimVelocity, Foam::fvm::div(), Foam::endl(), filmSubModelBase::film(), forAll, waxSolventEvaporation::L_, Foam::mag(), Foam::max(), Foam::min(), filmThermoModel::name(), IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, phi, filmThermoModel::pv(), Foam::Re(), rho, waxSolventEvaporation::Sh(), Foam::fvm::Sp(), T, filmThermoModel::Tb(), waxSolventEvaporation::TbFactor_, dimensioned< Type >::value(), WarningInFunction, waxSolventEvaporation::Wsolvent_, waxSolventEvaporation::Wwax_, waxSolventEvaporation::Ysolvent0_, waxSolventEvaporation::Ysolvent_, and Foam::Zero.
Referenced by waxSolventEvaporation::correctModel().
operator=()
void operator= (const waxSolventEvaporation &) protected delete
TypeName()
TypeName ("waxSolventEvaporation")
correctModel() [2/2]
void correctModel (const scalar dt, scalarField & availableMass, scalarField & dMass, scalarField & dEnergy) virtual
Implements phaseChangeModel.
Definition at line 372 of file waxSolventEvaporation.C.
References waxSolventEvaporation::correctModel(), filmSubModelBase::film(), and waxSolventEvaporation::YInfZero_.
Member Data Documentation
Wwax_
uniformDimensionedScalarField Wwax_ protected
Definition at line 61 of file waxSolventEvaporation.H.
Referenced by waxSolventEvaporation::correctModel().
Wsolvent_
uniformDimensionedScalarField Wsolvent_ protected
Definition at line 64 of file waxSolventEvaporation.H.
Referenced by waxSolventEvaporation::correctModel().
Ysolvent0_
uniformDimensionedScalarField Ysolvent0_ protected
Definition at line 67 of file waxSolventEvaporation.H.
Referenced by waxSolventEvaporation::correctModel().
Ysolvent_
volScalarField Ysolvent_ protected
Definition at line 70 of file waxSolventEvaporation.H.
Referenced by waxSolventEvaporation::correctModel().
deltaMin_
const scalar deltaMin_ protected
Definition at line 73 of file waxSolventEvaporation.H.
Referenced by waxSolventEvaporation::correctModel().
L_
const scalar L_ protected
Definition at line 76 of file waxSolventEvaporation.H.
Referenced by waxSolventEvaporation::correctModel().
TbFactor_
const scalar TbFactor_ protected
Definition at line 80 of file waxSolventEvaporation.H.
Referenced by waxSolventEvaporation::correctModel().
YInfZero_
bool YInfZero_ protected
Definition at line 83 of file waxSolventEvaporation.H.
Referenced by waxSolventEvaporation::correctModel().
activityCoeff_
autoPtr<Function1<scalar> > activityCoeff_ protected
Definition at line 86 of file waxSolventEvaporation.H.
Referenced by waxSolventEvaporation::correctModel().
The documentation for this class was generated from the following files:
src/regionModels/surfaceFilmModels/submodels/thermo/phaseChangeModel/waxSolventEvaporation/waxSolventEvaporation.H
src/regionModels/surfaceFilmModels/submodels/thermo/phaseChangeModel/waxSolventEvaporation/waxSolventEvaporation.C