OpenFOAM: SRFWallVelocityFvPatchVectorField Class Reference
SRFWallVelocityFvPatchVectorField Class Reference
Boundary conditions » Wall
Wall-velocity condition to be used in conjunction with the single rotating frame (SRF) model (see: FOAM::SRFModel)
#include <SRFWallVelocityFvPatchVectorField.H>
Public Member Functions
TypeName ("SRFWallVelocity")
SRFWallVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
SRFWallVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
SRFWallVelocityFvPatchVectorField (const SRFWallVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
SRFWallVelocityFvPatchVectorField (const SRFWallVelocityFvPatchVectorField &)
virtual tmp< fvPatchVectorField > clone () const
SRFWallVelocityFvPatchVectorField (const SRFWallVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
virtual void autoMap (const fvPatchFieldMapper &)
virtual void rmap (const fvPatchVectorField &, const labelList &)
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
Wall-velocity condition to be used in conjunction with the single rotating frame (SRF) model (see: FOAM::SRFModel)
The condition applies the appropriate rotation transformation in time and space to determine the local SRF velocity of the wall.
where
=
=
The normal component of is removed to ensure 0 wall-flux even if the wall patch faces are irregular.
Usage
Example of the boundary condition specification:
<patchName>
{
    type            SRFWallVelocity;
    value           uniform (0 0 0);    // Initial value
}
See also
Foam::SRFModel Foam::SRFVelocityFvPatchVectorField Foam::fixedValueFvPatchField
Source files
SRFWallVelocityFvPatchVectorField.H
SRFWallVelocityFvPatchVectorField.C
Definition at line 89 of file SRFWallVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
SRFWallVelocityFvPatchVectorField() [1/5]
SRFWallVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Definition at line 29 of file SRFWallVelocityFvPatchVectorField.C.
SRFWallVelocityFvPatchVectorField() [2/5]
SRFWallVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Definition at line 51 of file SRFWallVelocityFvPatchVectorField.C.
SRFWallVelocityFvPatchVectorField() [3/5]
SRFWallVelocityFvPatchVectorField (const SRFWallVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 39 of file SRFWallVelocityFvPatchVectorField.C.
SRFWallVelocityFvPatchVectorField() [4/5]
SRFWallVelocityFvPatchVectorField (const SRFWallVelocityFvPatchVectorField & srfvpvf)
Definition at line 62 of file SRFWallVelocityFvPatchVectorField.C.
SRFWallVelocityFvPatchVectorField() [5/5]
SRFWallVelocityFvPatchVectorField (const SRFWallVelocityFvPatchVectorField & srfvpvf, const DimensionedField< vector, volMesh > & iF)
Definition at line 71 of file SRFWallVelocityFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("SRFWallVelocity")
clone() [1/2]
virtual tmp< fvPatchVectorField > clone () const inline virtual
Definition at line 134 of file SRFWallVelocityFvPatchVectorField.H.
clone() [2/2]
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Definition at line 150 of file SRFWallVelocityFvPatchVectorField.H.
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Definition at line 83 of file SRFWallVelocityFvPatchVectorField.C.
References Field< vector >::autoMap().
rmap()
void rmap (const fvPatchVectorField & ptf, const labelList & addr) virtual
Definition at line 92 of file SRFWallVelocityFvPatchVectorField.C.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 102 of file SRFWallVelocityFvPatchVectorField.C.
References n, and Field< vector >::operator=().
write()
void write (Ostream & os) const virtual
Definition at line 125 of file SRFWallVelocityFvPatchVectorField.C.
References os(), fvPatchField< Type >::write(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/finiteVolume/cfdTools/general/SRF/derivedFvPatchFields/SRFWallVelocityFvPatchVectorField/SRFWallVelocityFvPatchVectorField.H
src/finiteVolume/cfdTools/general/SRF/derivedFvPatchFields/SRFWallVelocityFvPatchVectorField/SRFWallVelocityFvPatchVectorField.C