OpenFOAM: multiNormal Class Reference
multiNormal Class Reference
Particle-size distribution model wherein random samples are drawn from a mixture of a finite set of doubly-truncated univariate normal probability density functions:
#include <multiNormal.H>
Public Member Functions
TypeName ("multiNormal")
multiNormal (const dictionary &dict, Random &rndGen)
multiNormal (const multiNormal &p)
virtual autoPtr< distributionModel > clone () const
void operator= (const multiNormal &)=delete
virtual ~multiNormal ()=default
virtual scalar sample () const
scalar sample (const scalar mu, const scalar sigma) const
virtual scalar meanValue () const
Public Member Functions inherited from distributionModel
TypeName ("distributionModel")
declareRunTimeSelectionTable (autoPtr, distributionModel, dictionary,(const dictionary &dict, Random &rndGen),(dict, rndGen))
distributionModel (const word &name, const dictionary &dict, Random &rndGen)
distributionModel (const distributionModel &p)
virtual ~distributionModel ()=default
virtual scalar minValue () const
virtual scalar maxValue () const
Additional Inherited Members
Static Public Member Functions inherited from distributionModel
static autoPtr< distributionModel > New (const dictionary &dict, Random &rndGen)
Protected Member Functions inherited from distributionModel
virtual void check () const
Protected Attributes inherited from distributionModel
const dictionary distributionModelDict_
Random & rndGen_
scalar minValue_
scalar maxValue_
Detailed Description
Particle-size distribution model wherein random samples are drawn from a mixture of a finite set of doubly-truncated univariate normal probability density functions:
with for any distribution:
where
= Doubly-truncated univariate normal distribution
= Mean of the parent general normal distribution
= Standard deviation of the parent general normal distribution
= General normal probability density function
= General normal cumulative distribution function
= Sample
= Minimum of the distribution (the same for each distribution)
= Maximum of the distribution (the same for each distribution)
= Weighting factor
Constraints:
Random samples are generated by a combination of the inverse transform sampling technique and categorical sampling in three steps:
Draw a sample from the uniform probability density function on the unit interval
Find the interval among normalised cumulative weight intervals wherein resides
Draw a sample from the distribution corresponding to the interval by using the quantile function of the doubly-truncated univariate normal probability density function by the following expressions (similar to distributionModels::normal):
with
where is another sample drawn from the uniform probability density function on the unit interval .
Usage
Minimal example by using constant/<CloudProperties>:
subModels
{
    injectionModels
    {
        <name>
        {
            ...
            sizeDistribution
            {
                type        multiNormal;
                multiNormalDistribution
                {
                    minValue  <min>;
                    maxValue  <max>;
                    mu
                    (
                        <mean1>
                        <mean2>
                        ...
                    );
                    sigma
                    (
                        <standard deviation1>
                        <standard deviation2>
                        ...
                    );
                    weight
                    (
                        <weight1>
                        <weight2>
                        ...
                    );
                }
            }
        }
    }
}
where the entries mean:
Property Description Type Reqd Deflt
type Type name: multiNormal word yes -
multiNormalDistribution Distribution settings dict yes -
minValue Minimum of the distribution scalar yes -
maxValue Maximum of the distribution scalar yes -
mu
List of means of parent general normal
distributions
scalarList yes -
sigma
List of standard deviations of parent
general normal distributions
scalarList yes -
weight
List of weights of a given distribution in
the distribution mixture
scalarList yes -
Notes
The sum of normal distributions (i.e. a mixture distribution) should not be confused with the sum of normally-distributed random variables.
minValue and maxValue are the same for all distributions in the distribution mixture.
weight should always be input in a non-decreasing (i.e. monotonic) order.
Source files
multiNormal.H
multiNormal.C
Definition at line 281 of file multiNormal.H.
Constructor & Destructor Documentation
multiNormal() [1/2]
multiNormal (const dictionary & dict, Random & rndGen)
Definition at line 41 of file multiNormal.C.
multiNormal() [2/2]
multiNormal (const multiNormal & p)
Definition at line 113 of file multiNormal.C.
~multiNormal()
virtual ~multiNormal () virtual default
Member Function Documentation
TypeName()
TypeName ("multiNormal")
clone()
virtual autoPtr< distributionModel > clone () const inline virtual
Implements distributionModel.
Definition at line 313 of file multiNormal.H.
operator=()
void operator= (const multiNormal &) delete
sample() [1/2]
Foam::scalar sample () const virtual
Implements distributionModel.
Definition at line 124 of file multiNormal.C.
References UPtrList< T >::size().
sample() [2/2]
Foam::scalar sample (const scalar mu, const scalar sigma) const
Definition at line 142 of file multiNormal.C.
References b, Foam::clamp(), Foam::erf(), Foam::Math::erfInv(), mu, p, Foam::sqrt(), and x.
meanValue()
Foam::scalar meanValue () const virtual
Implements distributionModel.
Definition at line 168 of file multiNormal.C.
References forAll.
The documentation for this class was generated from the following files:
src/lagrangian/distributionModels/multiNormal/multiNormal.H
src/lagrangian/distributionModels/multiNormal/multiNormal.C