OpenFOAM: CollisionModel< CloudType > Class Template Reference
CollisionModel< CloudType > Class Template Reference abstract
Lagrangian particle models » Submodels » Kinematic » Collision
Templated collision model class.
#include <CollisionModel.H>
Public Member Functions
TypeName ("collisionModel")
declareRunTimeSelectionTable (autoPtr, CollisionModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
CollisionModel (CloudType &owner)
CollisionModel (const dictionary &dict, CloudType &owner, const word &type)
CollisionModel (const CollisionModel< CloudType > &cm)
virtual autoPtr< CollisionModel< CloudType > > clone () const =0
virtual ~CollisionModel ()
virtual label nSubCycles () const =0
virtual void collide ()=0
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
virtual ~CloudSubModelBase ()=default
const CloudType & owner () const
virtual bool writeTime () const
virtual fileName localPath () const
CloudType & owner ()
virtual void info ()
virtual void write (Ostream &os) const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
subModelBase (const subModelBase &smb)
virtual ~subModelBase ()=default
const word & modelName () const
const dictionary & dict () const
const word & baseName () const
const word & modelType () const
const dictionary & coeffDict () const
const dictionary & properties () const
virtual bool defaultCoeffs (const bool printMsg) const
virtual bool active () const
virtual void cacheFields (const bool store)
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
bool getModelDict (const word &entryName, dictionary &dict) const
template<class Type >
bool getModelProperty (const word &entryName, Type &value) const
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Static Public Member Functions
static autoPtr< CollisionModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Additional Inherited Members
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Public Attributes inherited from subModelBase
bool log
Protected Member Functions inherited from subModelBase
bool inLine () const
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Protected Attributes inherited from subModelBase
const word modelName_
dictionary & properties_
const dictionary dict_
const word baseName_
const word modelType_
const dictionary coeffDict_
Detailed Description
template<class CloudType>
class Foam::CollisionModel< CloudType >
Templated collision model class.
Source files
CollisionModel.H
CollisionModel.C
CollisionModelNew.C
Definition at line 54 of file CollisionModel.H.
Constructor & Destructor Documentation
CollisionModel() [1/3]
template<class CloudType > CollisionModel (CloudType & owner)
Definition at line 26 of file CollisionModel.C.
CollisionModel() [2/3]
template<class CloudType > CollisionModel (const dictionary & dict, CloudType & owner, const word & type)
Definition at line 33 of file CollisionModel.C.
CollisionModel() [3/3]
template<class CloudType > CollisionModel (const CollisionModel< CloudType > & cm)
Definition at line 45 of file CollisionModel.C.
~CollisionModel()
template<class CloudType > ~CollisionModel () virtual
Definition at line 57 of file CollisionModel.C.
Member Function Documentation
TypeName()
template<class CloudType > TypeName ("collisionModel")
declareRunTimeSelectionTable()
template<class CloudType > declareRunTimeSelectionTable (autoPtr , CollisionModel< CloudType > , dictionary , (const dictionary &dict, CloudType &owner) , (dict, owner))
clone()
template<class CloudType > virtual autoPtr< CollisionModel< CloudType > > clone () const pure virtual
Implemented in NoCollision< CloudType >, and PairCollision< CloudType >.
New()
template<class CloudType > Foam::autoPtr< Foam::CollisionModel< CloudType > > New (const dictionary & dict, CloudType & owner) static
Definition at line 28 of file CollisionModelNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, Foam::Info, and PtrList< T >::PtrList().
nSubCycles()
template<class CloudType > virtual label nSubCycles () const pure virtual
Implemented in NoCollision< CloudType >, and PairCollision< CloudType >.
collide()
template<class CloudType > virtual void collide () pure virtual
Implemented in NoCollision< CloudType >, and PairCollision< CloudType >.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/clouds/Templates/CollidingCloud/CollidingCloud.H
src/lagrangian/intermediate/submodels/Kinematic/CollisionModel/CollisionModel/CollisionModel.H
src/lagrangian/intermediate/submodels/Kinematic/CollisionModel/CollisionModel/CollisionModel.C
src/lagrangian/intermediate/submodels/Kinematic/CollisionModel/CollisionModel/CollisionModelNew.C