OpenFOAM: subBody Class Reference
subBody Class Reference
#include <subBody.H>
Public Member Functions
subBody (const autoPtr< rigidBody > &bodyPtr, const word &masterName, const label masterID, const spatialTransform &masterXT)
autoPtr< subBody > clone () const
const rigidBody & body () const
const word & name () const
const word & masterName () const
label masterID () const
const spatialTransform & masterXT () const
void write (Ostream &) const
Detailed Description
Definition at line 53 of file subBody.H.
Constructor & Destructor Documentation
subBody()
subBody (const autoPtr< rigidBody > & bodyPtr, const word & masterName, const label masterID, const spatialTransform & masterXT) inline
Definition at line 23 of file subBodyI.H.
Member Function Documentation
clone()
Foam::autoPtr< Foam::RBD::subBody > clone () const inline
Definition at line 38 of file subBodyI.H.
References autoPtr< T >::New().
body()
const Foam::RBD::rigidBody & body () const inline
Definition at line 46 of file subBodyI.H.
Referenced by rigidBody::merge().
name()
const Foam::word & name () const inline
Definition at line 52 of file subBodyI.H.
masterName()
const Foam::word & masterName () const inline
Definition at line 58 of file subBodyI.H.
masterID()
Foam::label masterID () const inline
Definition at line 64 of file subBodyI.H.
masterXT()
const Foam::spatialTransform & masterXT () const inline
Definition at line 70 of file subBodyI.H.
Referenced by rigidBody::merge().
write()
void write (Ostream & os) const
Definition at line 25 of file subBody.C.
References os().
The documentation for this class was generated from the following files:
src/rigidBodyDynamics/bodies/subBody/subBody.H
src/rigidBodyDynamics/bodies/subBody/subBody.C
src/rigidBodyDynamics/bodies/subBody/subBodyI.H