OpenFOAM: Pstream Class Reference
Pstream Class Reference
Inter-processor communications stream.
#include <Pstream.H>
Public Member Functions
ClassName ("Pstream")
Pstream (const UPstream::commsTypes commsType, const label bufSize=0)
Public Member Functions inherited from UPstream
ClassName ("UPstream")
UPstream (const commsTypes commsType) noexcept
commsTypes commsType () const noexcept
commsTypes commsType (const commsTypes ct) noexcept
template<class T >
Foam::List< T > allGatherValues (const T &localValue, const label comm)
template<class T >
Foam::List< T > listGatherValues (const T &localValue, const label comm)
Static Public Member Functions
template<class Type >
static void broadcast (Type &value, const label comm=UPstream::worldComm)
template<class Type , class... Args>
static void broadcasts (const label comm, Type &arg1, Args &&... args)
template<class T , class BinaryOp >
static void gather (const List< commsStruct > &comms, T &value, const BinaryOp &bop, const int tag, const label comm)
template<class T , class BinaryOp >
static void gather (T &value, const BinaryOp &bop, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm)
template<class T , class CombineOp >
static void combineGather (const List< commsStruct > &comms, T &value, const CombineOp &cop, const int tag, const label comm)
template<class T , class CombineOp >
static void combineGather (T &value, const CombineOp &cop, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm)
template<class T , class CombineOp >
static void combineReduce (const List< commsStruct > &comms, T &value, const CombineOp &cop, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm)
template<class T , class CombineOp >
static void combineReduce (T &value, const CombineOp &cop, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm)
template<class T , class CombineOp >
static void combineAllGather (T &value, const CombineOp &cop, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm)
template<class T , class CombineOp >
static void listCombineGather (const List< commsStruct > &comms, List< T > &values, const CombineOp &cop, const int tag, const label comm)
template<class T , class CombineOp >
static void listCombineGather (List< T > &values, const CombineOp &cop, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm)
template<class T , class CombineOp >
static void listCombineReduce (List< T > &values, const CombineOp &cop, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm)
template<class T , class CombineOp >
static void listCombineAllGather (List< T > &values, const CombineOp &cop, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm)
template<class Container , class CombineOp >
static void mapCombineGather (const List< commsStruct > &comms, Container &values, const CombineOp &cop, const int tag, const label comm)
template<class Container , class CombineOp >
static void mapCombineGather (Container &values, const CombineOp &cop, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm)
template<class Container , class CombineOp >
static void mapCombineReduce (Container &values, const CombineOp &cop, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm)
template<class Container , class CombineOp >
static void mapCombineAllGather (Container &values, const CombineOp &cop, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm)
template<class T >
static void gatherList (const List< commsStruct > &comms, List< T > &values, const int tag, const label comm)
template<class T >
static void gatherList (List< T > &values, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm)
template<class T >
static void allGatherList (List< T > &values, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm)
template<class T >
static void scatter (const List< commsStruct > &comms, T &value, const int tag, const label comm)
template<class T >
static void scatter (T &value, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm)
template<class T >
static void combineScatter (const List< commsStruct > &comms, T &value, const int tag, const label comm)
template<class T >
static void combineScatter (T &value, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm)
template<class T >
static void listCombineScatter (const List< commsStruct > &comms, List< T > &value, const int tag, const label comm)
template<class T >
static void listCombineScatter (List< T > &value, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm)
template<class Container >
static void mapCombineScatter (const List< commsStruct > &comms, Container &values, const int tag, const label comm)
template<class Container >
static void mapCombineScatter (Container &values, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm)
template<class T >
static void scatterList (const List< commsStruct > &comms, List< T > &values, const int tag, const label comm)
template<class T >
static void scatterList (List< T > &values, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm)
template<class Container >
static void exchangeSizes (const labelUList &sendProcs, const labelUList &recvProcs, const Container &sendBufs, labelList &sizes, const label tag=UPstream::msgType(), const label comm=UPstream::worldComm)
template<class Container >
static void exchangeSizes (const labelUList &neighProcs, const Container &sendBufs, labelList &sizes, const label tag=UPstream::msgType(), const label comm=UPstream::worldComm)
template<class Container >
static void exchangeSizes (const Container &sendBufs, labelList &recvSizes, const label comm=UPstream::worldComm)
template<class Container >
static void exchangeSizes (const Map< Container > &sendBufs, Map< label > &recvSizes, const label tag=UPstream::msgType(), const label comm=UPstream::worldComm)
template<class Container , class Type >
static void exchange (const UList< Container > &sendBufs, const labelUList &recvSizes, List< Container > &recvBufs, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm, const bool wait=true)
template<class Container , class Type >
static void exchange (const Map< Container > &sendBufs, const Map< label > &recvSizes, Map< Container > &recvBufs, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm, const bool wait=true)
template<class Container , class Type >
static void exchange (const UList< Container > &sendBufs, List< Container > &recvBufs, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm, const bool wait=true)
template<class Container , class Type >
static void exchange (const Map< Container > &sendBufs, Map< Container > &recvBufs, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm, const bool wait=true)
template<class Container , class Type >
static void exchangeConsensus (const UList< Container > &sendBufs, List< Container > &recvBufs, const int tag, const label comm, const bool wait=true)
template<class Container , class Type >
static void exchangeConsensus (const Map< Container > &sendBufs, Map< Container > &recvBufs, const int tag, const label comm, const bool wait=true)
static bool broadcast (char *buf, const std::streamsize bufSize, const label communicator, const int rootProcNo=masterNo())
Static Public Member Functions inherited from UPstream
static constexpr label commGlobal () noexcept
static constexpr label commSelf () noexcept
static label commWorld () noexcept
static label commWorld (const label communicator) noexcept
static label commWarn (const label communicator) noexcept
static label nComms () noexcept
static void printCommTree (const label communicator)
static label commIntraHost ()
static label commInterHost ()
static bool hasHostComms ()
static void clearHostComms ()
static label allocateCommunicator (const label parent, const labelRange &subRanks, const bool withComponents=true)
static label allocateCommunicator (const label parent, const labelUList &subRanks, const bool withComponents=true)
static void freeCommunicator (const label communicator, const bool withComponents=true)
static label allocateInterHostCommunicator (const label parentCommunicator=worldComm)
static label allocateIntraHostCommunicator (const label parentCommunicator=worldComm)
static int baseProcNo (label comm, int procID)
static label procNo (const label comm, const int baseProcID)
static label procNo (const label comm, const label currentComm, const int currentProcID)
static void addValidParOptions (HashTable< string > &validParOptions)
static bool init (int &argc, char **&argv, const bool needsThread)
static bool initNull ()
static void barrier (const label communicator, UPstream::Request *req=nullptr)
static std::pair< int, int > probeMessage (const UPstream::commsTypes commsType, const int fromProcNo, const int tag=UPstream::msgType(), const label communicator=worldComm)
static label nRequests () noexcept
static void resetRequests (const label n)
static void addRequest (UPstream::Request &req)
static void cancelRequest (const label i)
static void cancelRequest (UPstream::Request &req)
static void cancelRequests (UList< UPstream::Request > &requests)
static void freeRequest (UPstream::Request &req)
static void freeRequests (UList< UPstream::Request > &requests)
static void waitRequests (const label pos, label len=-1)
static void waitRequests (UList< UPstream::Request > &requests)
static bool waitAnyRequest (const label pos, label len=-1)
static bool waitSomeRequests (const label pos, DynamicList< int > *indices=nullptr)
static label waitAnyRequest (UList< UPstream::Request > &requests)
static void waitRequest (const label i)
static void waitRequest (UPstream::Request &req)
static bool finishedRequest (const label i)
static bool finishedRequest (UPstream::Request &req)
static bool finishedRequests (const label pos, label len=-1)
static bool finishedRequests (UList< UPstream::Request > &requests)
static bool finishedRequestPair (label &req0, label &req1)
static void waitRequestPair (label &req0, label &req1)
static bool parRun (const bool on) noexcept
static bool & parRun () noexcept
static bool haveThreads () noexcept
static constexpr int masterNo () noexcept
static label nProcs (const label communicator=worldComm)
static int myProcNo (const label communicator=worldComm)
static bool master (const label communicator=worldComm)
static bool is_rank (const label communicator=worldComm)
static bool is_subrank (const label communicator=worldComm)
static bool is_parallel (const label communicator=worldComm)
static label parent (const label communicator)
static List< int > & procID (const label communicator)
static const wordList & allWorlds () noexcept
static const labelList & worldIDs () noexcept
static label myWorldID ()
static const word & myWorld ()
static rangeType allProcs (const label communicator=worldComm)
static rangeType subProcs (const label communicator=worldComm)
static const List< commsStruct > & linearCommunication (const label communicator=worldComm)
static const List< commsStruct > & treeCommunication (const label communicator=worldComm)
static const List< commsStruct > & whichCommunication (const label communicator=worldComm)
static int & msgType () noexcept
static void shutdown (int errNo=0)
static void abort ()
static void exit (int errNo=1)
static void allToAll (const UList< int32_t > &sendData, UList< int32_t > &recvData, const label communicator=worldComm)
static void allToAll (const UList< int64_t > &sendData, UList< int64_t > &recvData, const label communicator=worldComm)
static void allToAllConsensus (const UList< int32_t > &sendData, UList< int32_t > &recvData, const int tag, const label communicator=worldComm)
static void allToAllConsensus (const UList< int64_t > &sendData, UList< int64_t > &recvData, const int tag, const label communicator=worldComm)
static void allToAllConsensus (const Map< int32_t > &sendData, Map< int32_t > &recvData, const int tag, const label communicator=worldComm)
static void allToAllConsensus (const Map< int64_t > &sendData, Map< int64_t > &recvData, const int tag, const label communicator=worldComm)
static void mpiGather (const char *sendData, char *recvData, int count, const label communicator=worldComm)
Receive identically-sized char data from all ranks.
static void mpiScatter (const char *sendData, char *recvData, int count, const label communicator=worldComm)
Send identically-sized char data to all ranks.
static void mpiAllGather (char *allData, int count, const label communicator=worldComm)
Gather/scatter identically-sized char data.
static void gather (const char *sendData, int sendCount, char *recvData, const UList< int > &recvCounts, const UList< int > &recvOffsets, const label communicator=worldComm)
Receive variable length char data from all ranks.
static void scatter (const char *sendData, const UList< int > &sendCounts, const UList< int > &sendOffsets, char *recvData, int recvCount, const label communicator=worldComm)
Send variable length char data to all ranks.
static void gather (const int32_t *sendData, int sendCount, int32_t *recvData, const UList< int > &recvCounts, const UList< int > &recvOffsets, const label communicator=worldComm)
Receive variable length int32_t data from all ranks.
static void scatter (const int32_t *sendData, const UList< int > &sendCounts, const UList< int > &sendOffsets, int32_t *recvData, int recvCount, const label communicator=worldComm)
Send variable length int32_t data to all ranks.
static void gather (const int64_t *sendData, int sendCount, int64_t *recvData, const UList< int > &recvCounts, const UList< int > &recvOffsets, const label communicator=worldComm)
Receive variable length int64_t data from all ranks.
static void scatter (const int64_t *sendData, const UList< int > &sendCounts, const UList< int > &sendOffsets, int64_t *recvData, int recvCount, const label communicator=worldComm)
Send variable length int64_t data to all ranks.
static void gather (const uint32_t *sendData, int sendCount, uint32_t *recvData, const UList< int > &recvCounts, const UList< int > &recvOffsets, const label communicator=worldComm)
Receive variable length uint32_t data from all ranks.
static void scatter (const uint32_t *sendData, const UList< int > &sendCounts, const UList< int > &sendOffsets, uint32_t *recvData, int recvCount, const label communicator=worldComm)
Send variable length uint32_t data to all ranks.
static void gather (const uint64_t *sendData, int sendCount, uint64_t *recvData, const UList< int > &recvCounts, const UList< int > &recvOffsets, const label communicator=worldComm)
Receive variable length uint64_t data from all ranks.
static void scatter (const uint64_t *sendData, const UList< int > &sendCounts, const UList< int > &sendOffsets, uint64_t *recvData, int recvCount, const label communicator=worldComm)
Send variable length uint64_t data to all ranks.
static void gather (const float *sendData, int sendCount, float *recvData, const UList< int > &recvCounts, const UList< int > &recvOffsets, const label communicator=worldComm)
Receive variable length float data from all ranks.
static void scatter (const float *sendData, const UList< int > &sendCounts, const UList< int > &sendOffsets, float *recvData, int recvCount, const label communicator=worldComm)
Send variable length float data to all ranks.
static void gather (const double *sendData, int sendCount, double *recvData, const UList< int > &recvCounts, const UList< int > &recvOffsets, const label communicator=worldComm)
Receive variable length double data from all ranks.
static void scatter (const double *sendData, const UList< int > &sendCounts, const UList< int > &sendOffsets, double *recvData, int recvCount, const label communicator=worldComm)
Send variable length double data to all ranks.
template<class T >
static List< T > allGatherValues (const T &localValue, const label communicator=worldComm)
template<class T >
static List< T > listGatherValues (const T &localValue, const label communicator=worldComm)
template<class T >
static T listScatterValues (const UList< T > &allValues, const label communicator=worldComm)
static bool broadcast (char *buf, const std::streamsize bufSize, const label communicator, const int rootProcNo=masterNo())
static void reduceAnd (bool &value, const label communicator=worldComm)
static void reduceOr (bool &value, const label communicator=worldComm)
static void waitRequests ()
static constexpr int firstSlave () noexcept
static int lastSlave (const label communicator=worldComm)
Protected Attributes
DynamicList< char > transferBuf_
Additional Inherited Members
Public Types inherited from UPstream
enum class commsTypes : char { blocking , scheduled , nonBlocking }
enum class sendModes : char { normal , sync }
typedef IntRange< int > rangeType
Static Public Attributes inherited from UPstream
static const Enum< commsTypes > commsTypeNames
static bool floatTransfer
static int nProcsSimpleSum
static int nProcsNonblockingExchange
static int nPollProcInterfaces
static commsTypes defaultCommsType
static int maxCommsSize
static int tuning_NBX_
static const int mpiBufferSize
static label worldComm
static label warnComm
Detailed Description
Inter-processor communications stream.
Source files
Pstream.H
Pstream.C
PstreamBroadcast.C
PstreamGather.C
PstreamCombineGather.C
PstreamGatherList.C
PstreamExchangeConsensus.C
PstreamExchange.C
Definition at line 57 of file Pstream.H.
Constructor & Destructor Documentation
Pstream()
Pstream (const UPstream::commsTypes commsType, const label bufSize = 0) inline explicit
Definition at line 78 of file Pstream.H.
References DynamicList< T, SizeMin >::setCapacity(), and Pstream::transferBuf_.
Member Function Documentation
ClassName()
ClassName ("Pstream")
broadcast() [1/2]
template<class Type > void broadcast (Type & value, const label comm = UPstream::worldComm) static
Definition at line 28 of file PstreamBroadcast.C.
References UPstream::broadcast(), UPstream::is_parallel(), UPstream::master(), UPstream::masterNo(), and os().
Referenced by unwatchedIOdictionary::addWatch(), regIOobject::addWatch(), masterUncollatedFileOperation::addWatch(), Foam::broadcastFile_recursive(), AMIInterpolation::calcDistribution(), decomposedBlockData::calcNumProcs(), viewFactor::calculate(), ZoneMesh< ZoneType, MeshType >::checkParallelSync(), processorColour::colour(), Pstream::combineReduce(), Pstream::combineReduce(), Pstream::combineScatter(), Pstream::combineScatter(), masterUncollatedFileOperation::dirPath(), systemCall::dispatch(), faMeshDistributor::distribute(), abort::execute(), masterUncollatedFileOperation::filePath(), distanceSurface::filterKeepLargestRegion(), distanceSurface::filterKeepNearestRegions(), distanceSurface::filterRegionProximity(), masterUncollatedFileOperation::findInstance(), masterUncollatedFileOperation::findTimes(), masterUncollatedFileOperation::findWatch(), ensightSurfaceReader::geometry(), masterUncollatedFileOperation::getFile(), fileOperation::getGlobalHostIORanks(), masterUncollatedFileOperation::getState(), Random::globalGaussNormal(), Random::globalPosition(), Random::globalPosition(), Random::globalPosition(), Random::globalRandomise01(), Random::globalSample01(), Pstream::listCombineReduce(), Pstream::listCombineScatter(), Pstream::listCombineScatter(), fileOperation::lookupAndCacheProcessorsPath(), Pstream::mapCombineReduce(), Pstream::mapCombineScatter(), Pstream::mapCombineScatter(), fileOperation::nProcs(), InflationInjection< CloudType >::parcelsToInject(), decomposedBlockData::readBlocks(), decomposedBlockData::readBlocks(), ensightSurfaceReader::readField(), masterUncollatedFileOperation::readHeader(), regIOobject::readHeaderOk(), masterUncollatedFileOperation::readStream(), surfaceNoise::readSurfaceData(), Foam::reduce(), masterUncollatedFileOperation::removeWatch(), Pstream::scatter(), Pstream::scatter(), mapDistributeBase::schedule(), Time::setMonitoring(), globalMeshData::sharedPoints(), rigidBodyMotion::solve(), ParSortableList< Type >::sort(), surfaceNoise::surfaceAverage(), hexRef8Data::sync(), syncTools::syncEdgeMap(), syncTools::syncPointMap(), triSurfaceMesh::triSurfaceMesh(), triSurfaceMesh::triSurfaceMesh(), IOobject::typeHeaderOk(), fileOperation::uniformFile(), sixDoFRigidBodyMotion::update(), fileMonitor::updateStates(), dynamicCode::waitForFile(), externalFileCoupler::waitForMaster(), externalFileCoupler::waitForSlave(), decomposedBlockData::writeBlocks(), surfaceNoise::writeSurfaceData(), and streamLineBase::writeToFile().
broadcasts()
template<class Type , class... Args> void broadcasts (const label comm, Type & arg1, Args &&... args) static
Definition at line 58 of file PstreamBroadcast.C.
References args, Foam::Detail::inputLoop(), UPstream::is_parallel(), UPstream::master(), UPstream::masterNo(), os(), and Foam::Detail::outputLoop().
Referenced by surfaceNoise::calculate(), masterUncollatedFileOperation::dirPath(), ensightSurfaceReader::ensightSurfaceReader(), masterUncollatedFileOperation::filePath(), surfaceNoise::initialise(), fvMeshTools::newMesh(), faMeshTools::newMesh(), masterUncollatedFileOperation::read(), uncollatedFileOperation::read(), decomposedBlockData::readBlocks(), lumpedPointState::readData(), masterUncollatedFileOperation::readHeader(), masterUncollatedFileOperation::readObjects(), fileOperation::sync(), masterUncollatedFileOperation::sync(), OFstreamCollator::write(), and decomposedBlockData::writeData().
gather() [1/2]
template<class T , class BinaryOp > void gather (const List< commsStruct > & comms, T & value, const BinaryOp & bop, const int tag, const label comm) static
Definition at line 36 of file PstreamGather.C.
References UPstream::is_parallel(), UPstream::myProcNo(), UIPstream::read(), UPstream::scheduled, T, and UOPstream::write().
Referenced by Pstream::gather(), and Foam::reduce().
gather() [2/2]
template<class T , class BinaryOp > void gather (T & value, const BinaryOp & bop, const int tag = UPstream::msgType(), const label comm = UPstream::worldComm) static
Definition at line 199 of file PstreamGather.C.
References Pstream::gather(), and UPstream::whichCommunication().
combineGather() [1/2]
template<class T , class CombineOp > void combineGather (const List< commsStruct > & comms, T & value, const CombineOp & cop, const int tag, const label comm) static
Definition at line 41 of file PstreamCombineGather.C.
References Foam::endl(), UPstream::is_parallel(), UPstream::myProcNo(), Foam::Pout, UIPstream::read(), UPstream::scheduled, T, and UOPstream::write().
Referenced by Pstream::combineGather(), Pstream::combineReduce(), and Pstream::combineReduce().
combineGather() [2/2]
template<class T , class CombineOp > void combineGather (T & value, const CombineOp & cop, const int tag = UPstream::msgType(), const label comm = UPstream::worldComm) static
Definition at line 222 of file PstreamCombineGather.C.
References Pstream::combineGather(), and UPstream::whichCommunication().
combineReduce() [1/2]
template<class T , class CombineOp > void combineReduce (const List< commsStruct > & comms, T & value, const CombineOp & cop, const int tag = UPstream::msgType(), const label comm = UPstream::worldComm) static
Definition at line 264 of file PstreamCombineGather.C.
References Pstream::broadcast(), and Pstream::combineGather().
Referenced by Pstream::combineAllGather(), Foam::combineReduce(), multiWorldConnections::createComms(), globalMeshData::geometricSharedPoints(), faGlobalMeshData::updateMesh(), ParticlePostProcessing< CloudType >::write(), and vtkCloud::writeFields().
combineReduce() [2/2]
template<class T , class CombineOp > void combineReduce (T & value, const CombineOp & cop, const int tag = UPstream::msgType(), const label comm = UPstream::worldComm) static
Definition at line 279 of file PstreamCombineGather.C.
References Pstream::broadcast(), Pstream::combineGather(), UPstream::is_parallel(), and UPstream::whichCommunication().
combineAllGather()
template<class T , class CombineOp > static void combineAllGather (T & value, const CombineOp & cop, const int tag = UPstream::msgType(), const label comm = UPstream::worldComm) inline static
Definition at line 206 of file Pstream.H.
References Pstream::combineReduce().
listCombineGather() [1/2]
template<class T , class CombineOp > void listCombineGather (const List< commsStruct > & comms, List< T > & values, const CombineOp & cop, const int tag, const label comm) static
Definition at line 300 of file PstreamCombineGather.C.
References Foam::endl(), forAll, UPstream::is_parallel(), UPstream::myProcNo(), Foam::Pout, UIPstream::read(), UPstream::scheduled, and UOPstream::write().
Referenced by patchInjection::correct(), cellCellStencil::count(), distanceSurface::filterKeepLargestRegion(), distanceSurface::filterKeepNearestRegions(), distanceSurface::filterRegionProximity(), LocalInteraction< CloudType >::info(), RecycleInteraction< CloudType >::info(), StandardWallInteraction< CloudType >::info(), injectionModelList::info(), transferModelList::info(), Pstream::listCombineGather(), Pstream::listCombineReduce(), patchInjection::patchInjectedMassTotals(), meshRefinement::printMeshInfo(), fileMonitor::updateStates(), ParticleZoneInfo< CloudType >::write(), equalBinWidth::write(), and unequalBinWidth::write().
listCombineGather() [2/2]
template<class T , class CombineOp > void listCombineGather (List< T > & values, const CombineOp & cop, const int tag = UPstream::msgType(), const label comm = UPstream::worldComm) static
Definition at line 487 of file PstreamCombineGather.C.
References Pstream::listCombineGather(), and UPstream::whichCommunication().
listCombineReduce()
template<class T , class CombineOp > void listCombineReduce (List< T > & values, const CombineOp & cop, const int tag = UPstream::msgType(), const label comm = UPstream::worldComm) static
Definition at line 529 of file PstreamCombineGather.C.
References Pstream::broadcast(), UPstream::is_parallel(), Pstream::listCombineGather(), and UPstream::whichCommunication().
Referenced by meshRefinement::balance(), viewFactor::calculate(), extractEulerianParticles::calculateAddressing(), NURBS3DVolume::computeControlPointSensitivities(), NURBS3DVolume::computeControlPointSensitivities(), meshRefinement::createZoneBaffles(), Curle::execute(), patchProbes::findElements(), cellVolumeWeight::findHoles(), inverseDistance::findHoles(), mappedPatchBase::findSamples(), propellerInfo::interpolate(), Pstream::listCombineAllGather(), fvMeshSubset::reset(), patchProbes::sample(), probes::sample(), patchProbes::sample(), probes::sample(), TDACChemistryModel< ReactionThermo, ThermoType >::solve(), trackingInverseDistance::trackingInverseDistance(), cellVolumeWeight::update(), inverseDistance::update(), patchInjectionBase::updateMesh(), propellerInfo::updateSampleDiskCells(), and ParticleZoneInfo< CloudType >::write().
listCombineAllGather()
template<class T , class CombineOp > static void listCombineAllGather (List< T > & values, const CombineOp & cop, const int tag = UPstream::msgType(), const label comm = UPstream::worldComm) inline static
Definition at line 252 of file Pstream.H.
References Pstream::listCombineReduce().
mapCombineGather() [1/2]
template<class Container , class CombineOp > void mapCombineGather (const List< commsStruct > & comms, Container & values, const CombineOp & cop, const int tag, const label comm) static
Definition at line 550 of file PstreamCombineGather.C.
References UPtrList< T >::cbegin(), UPtrList< T >::cend(), Foam::endl(), UPstream::is_parallel(), UPstream::myProcNo(), Foam::Pout, and UPstream::scheduled.
Referenced by Pstream::mapCombineGather(), and Pstream::mapCombineReduce().
mapCombineGather() [2/2]
template<class Container , class CombineOp > void mapCombineGather (Container & values, const CombineOp & cop, const int tag = UPstream::msgType(), const label comm = UPstream::worldComm) static
Definition at line 693 of file PstreamCombineGather.C.
References Pstream::mapCombineGather(), and UPstream::whichCommunication().
mapCombineReduce()
template<class Container , class CombineOp > void mapCombineReduce (Container & values, const CombineOp & cop, const int tag = UPstream::msgType(), const label comm = UPstream::worldComm) static
Definition at line 735 of file PstreamCombineGather.C.
References Pstream::broadcast(), UPstream::is_parallel(), Pstream::mapCombineGather(), and UPstream::whichCommunication().
Referenced by Pstream::mapCombineAllGather(), regionSplit2D::regionSplit2D(), Foam::regionSum(), areaWrite::write(), and meshRefinement::zonify().
mapCombineAllGather()
template<class Container , class CombineOp > static void mapCombineAllGather (Container & values, const CombineOp & cop, const int tag = UPstream::msgType(), const label comm = UPstream::worldComm) inline static
Definition at line 305 of file Pstream.H.
References Pstream::mapCombineReduce().
gatherList() [1/2]
template<class T > void gatherList (const List< commsStruct > & comms, List< T > & values, const int tag, const label comm) static
Definition at line 40 of file PstreamGatherList.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, UPstream::is_parallel(), UPstream::myProcNo(), Foam::nl, UPstream::nProcs(), Foam::Pout, UIPstream::read(), UPstream::scheduled, UPtrList< T >::size(), and UOPstream::write().
Referenced by Pstream::allGatherList(), processorColour::colour(), sizeDistribution::combineFields(), Foam::createReconstructMap(), Foam::createReconstructMap(), externalCoupled::gatherAndCombine(), Pstream::gatherList(), viewFactor::initialise(), masterUncollatedFileOperation::masterOp(), masterUncollatedFileOperation::masterOp(), masterUncollatedFileOperation::NewIFstream(), InflationInjection< CloudType >::parcelsToInject(), collatedFileOperation::printBanner(), fileOperation::printRanks(), masterUncollatedFileOperation::readHeader(), masterUncollatedFileOperation::readStream(), ParSortableList< Type >::sort(), FacePostProcessing< CloudType >::write(), ParticleHistogram< CloudType >::write(), ParticlePostProcessing< CloudType >::write(), externalCoupled::writeGeometry(), and isoAdvection::writeIsoFaces().
gatherList() [2/2]
template<class T > void gatherList (List< T > & values, const int tag = UPstream::msgType(), const label comm = UPstream::worldComm) static
Definition at line 313 of file PstreamGatherList.C.
References Pstream::gatherList(), and UPstream::whichCommunication().
allGatherList()
template<class T > void allGatherList (List< T > & values, const int tag = UPstream::msgType(), const label comm = UPstream::worldComm) static
Definition at line 338 of file PstreamGatherList.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, Pstream::gatherList(), UPstream::is_parallel(), UPstream::mpiAllGather(), Foam::nl, UPstream::nProcs(), Pstream::scatterList(), T, and UPstream::whichCommunication().
Referenced by surfaceZonesInfo::addCellZonesToMesh(), surfaceZonesInfo::addFaceZonesToMesh(), sensitivitySurfacePoints::assembleSensitivities(), fieldMinMax::calcMinMaxFieldType(), meshRefinement::checkCoupledFaceZones(), mappedPatchBase::collectSamples(), fieldValue::combineFields(), distributedTriSurfaceMesh::distribute(), mappedPatchBase::findSamples(), InjectedParticleDistributionInjection< CloudType >::initialise(), InjectedParticleInjection< CloudType >::initialise(), pointHistory::pointHistory(), powerLawLopesdaCostaZone::powerLawLopesdaCostaZone(), processorTopology::procAdjacency(), fvMeshSubset::reset(), inverseDistance::update(), and trackingInverseDistance::update().
scatter() [1/2]
template<class T > void scatter (const List< commsStruct > & comms, T & value, const int tag, const label comm) static
Definition at line 116 of file PstreamGather.C.
References Pstream::broadcast(), forAllReverse, UPstream::is_parallel(), UPstream::myProcNo(), UIPstream::read(), UPstream::scheduled, T, and UOPstream::write().
Referenced by Pstream::scatter().
scatter() [2/2]
template<class T > void scatter (T & value, const int tag = UPstream::msgType(), const label comm = UPstream::worldComm) static
Definition at line 212 of file PstreamGather.C.
References Pstream::broadcast(), Pstream::scatter(), and UPstream::whichCommunication().
combineScatter() [1/2]
template<class T > void combineScatter (const List< commsStruct > & comms, T & value, const int tag, const label comm) static
Definition at line 141 of file PstreamCombineGather.C.
References Pstream::broadcast(), forAllReverse, UPstream::is_parallel(), UPstream::myProcNo(), UIPstream::read(), UPstream::scheduled, T, and UOPstream::write().
Referenced by Pstream::combineScatter().
combineScatter() [2/2]
template<class T > void combineScatter (T & value, const int tag = UPstream::msgType(), const label comm = UPstream::worldComm) static
Definition at line 242 of file PstreamCombineGather.C.
References Pstream::broadcast(), Pstream::combineScatter(), and UPstream::whichCommunication().
listCombineScatter() [1/2]
template<class T > void listCombineScatter (const List< commsStruct > & comms, List< T > & value, const int tag, const label comm) static
Definition at line 406 of file PstreamCombineGather.C.
References Pstream::broadcast(), forAllReverse, UPstream::is_parallel(), UPstream::myProcNo(), UIPstream::read(), UPstream::scheduled, and UOPstream::write().
Referenced by Pstream::listCombineScatter().
listCombineScatter() [2/2]
template<class T > void listCombineScatter (List< T > & value, const int tag = UPstream::msgType(), const label comm = UPstream::worldComm) static
Definition at line 507 of file PstreamCombineGather.C.
References Pstream::broadcast(), Pstream::listCombineScatter(), and UPstream::whichCommunication().
mapCombineScatter() [1/2]
template<class Container > void mapCombineScatter (const List< commsStruct > & comms, Container & values, const int tag, const label comm) static
Definition at line 631 of file PstreamCombineGather.C.
References Pstream::broadcast(), Foam::endl(), forAllReverse, UPstream::is_parallel(), UPstream::myProcNo(), Foam::Pout, and UPstream::scheduled.
Referenced by Pstream::mapCombineScatter().
mapCombineScatter() [2/2]
template<class Container > void mapCombineScatter (Container & values, const int tag = UPstream::msgType(), const label comm = UPstream::worldComm) static
Definition at line 713 of file PstreamCombineGather.C.
References Pstream::broadcast(), Pstream::mapCombineScatter(), and UPstream::whichCommunication().
scatterList() [1/2]
template<class T > void scatterList (const List< commsStruct > & comms, List< T > & values, const int tag, const label comm) static
Definition at line 184 of file PstreamGatherList.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, forAllReverse, UPstream::is_parallel(), UPstream::myProcNo(), Foam::nl, UPstream::nProcs(), Foam::Pout, UIPstream::read(), UPstream::scheduled, UPtrList< T >::size(), and UOPstream::write().
Referenced by Pstream::allGatherList(), and Pstream::scatterList().
scatterList() [2/2]
template<class T > void scatterList (List< T > & values, const int tag = UPstream::msgType(), const label comm = UPstream::worldComm) static
Definition at line 326 of file PstreamGatherList.C.
References Pstream::scatterList(), and UPstream::whichCommunication().
exchangeSizes() [1/4]
template<class Container > void exchangeSizes (const labelUList & sendProcs, const labelUList & recvProcs, const Container & sendBufs, labelList & sizes, const label tag = UPstream::msgType(), const label comm = UPstream::worldComm) static
Definition at line 749 of file PstreamExchange.C.
References Foam::abort(), PtrList< T >::clear(), Foam::FatalError, FatalErrorInFunction, UPstream::is_rank(), UPstream::myProcNo(), UPstream::nonBlocking, UPstream::nProcs(), UPstream::nRequests(), UIPstream::read(), UPtrList< T >::size(), UPstream::waitRequests(), and UOPstream::write().
Referenced by mapDistributeBase::mapDistributeBase().
exchangeSizes() [2/4]
template<class Container > void exchangeSizes (const labelUList & neighProcs, const Container & sendBufs, labelList & sizes, const label tag = UPstream::msgType(), const label comm = UPstream::worldComm) static
Definition at line 827 of file PstreamExchange.C.
References PtrList< T >::clear(), and UPstream::is_rank().
exchangeSizes() [3/4]
template<class Container > void exchangeSizes (const Container & sendBufs, labelList & recvSizes, const label comm = UPstream::worldComm) static
Definition at line 894 of file PstreamExchange.C.
References Foam::abort(), UPstream::allToAll(), UPstream::allToAllConsensus(), PtrList< T >::clear(), Foam::FatalError, FatalErrorInFunction, forAll, UPstream::is_rank(), UPstream::msgType(), UPstream::nProcs(), UPstream::nProcsNonblockingExchange, and UPtrList< T >::size().
exchangeSizes() [4/4]
template<class Container > void exchangeSizes (const Map< Container > & sendBufs, Map< label > & recvSizes, const label tag = UPstream::msgType(), const label comm = UPstream::worldComm) static
Definition at line 856 of file PstreamExchange.C.
References UPstream::allToAllConsensus(), PtrList< T >::clear(), PtrList< T >::emplace(), forAllConstIters, UPstream::is_rank(), and UPtrList< T >::size().
exchange() [1/4]
template<class Container , class Type > void exchange (const UList< Container > & sendBufs, const labelUList & recvSizes, List< Container > & recvBufs, const int tag = UPstream::msgType(), const label comm = UPstream::worldComm, const bool wait = true) static
Parameters
wait Wait for requests to complete
Definition at line 466 of file PstreamExchange.C.
References Foam::abort(), PtrList< T >::clear(), UPtrList< T >::empty(), Foam::FatalError, FatalErrorInFunction, forAll, UPstream::is_parallel(), UPstream::is_rank(), UPstream::maxCommsSize, UPstream::myProcNo(), UPstream::nProcs(), PtrList< T >::push_back(), and UPtrList< T >::size().
exchange() [2/4]
template<class Container , class Type > void exchange (const Map< Container > & sendBufs, const Map< label > & recvSizes, Map< Container > & recvBufs, const int tag = UPstream::msgType(), const label comm = UPstream::worldComm, const bool wait = true) static
Parameters
recvSizes Num of recv elements (not bytes)
wait Wait for requests to complete
Definition at line 587 of file PstreamExchange.C.
References b, UPtrList< T >::begin(), PtrList< T >::clear(), UPtrList< T >::empty(), UPtrList< T >::end(), forAllConstIters, forAllIters, UPstream::is_parallel(), UPstream::is_rank(), UPstream::maxCommsSize, UPstream::myProcNo(), PtrList< T >::push_back(), and UPtrList< T >::size().
exchange() [3/4]
template<class Container , class Type > void exchange (const UList< Container > & sendBufs, List< Container > & recvBufs, const int tag = UPstream::msgType(), const label comm = UPstream::worldComm, const bool wait = true) static
Parameters
wait Wait for requests to complete
Definition at line 947 of file PstreamExchange.C.
exchange() [4/4]
template<class Container , class Type > void exchange (const Map< Container > & sendBufs, Map< Container > & recvBufs, const int tag = UPstream::msgType(), const label comm = UPstream::worldComm, const bool wait = true) static
Parameters
wait Wait for requests to complete
Definition at line 970 of file PstreamExchange.C.
exchangeConsensus() [1/2]
template<class Container , class Type > void exchangeConsensus (const UList< Container > & sendBufs, List< Container > & recvBufs, const int tag, const label comm, const bool wait = true) static
Parameters
wait Wait for requests to complete
Definition at line 414 of file PstreamExchangeConsensus.C.
References Foam::abort(), Foam::PstreamDetail::exchangeConsensus(), Foam::FatalError, FatalErrorInFunction, UPstream::nProcs(), and UPtrList< T >::size().
exchangeConsensus() [2/2]
template<class Container , class Type > void exchangeConsensus (const Map< Container > & sendBufs, Map< Container > & recvBufs, const int tag, const label comm, const bool wait = true) static
Parameters
wait Wait for requests to complete
Definition at line 450 of file PstreamExchangeConsensus.C.
References Foam::PstreamDetail::exchangeConsensus().
broadcast() [2/2]
bool broadcast (char * buf, const std::streamsize bufSize, const label communicator, const int rootProcNo = masterNo()) static
Definition at line 1150 of file UPstreamBroadcast.C.
Member Data Documentation
transferBuf_
DynamicList<char> transferBuf_ protected
Definition at line 66 of file Pstream.H.
Referenced by Pstream::Pstream().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOstreams/Pstreams/Pstream.H
src/OpenFOAM/db/IOstreams/Pstreams/PstreamBroadcast.C
src/OpenFOAM/db/IOstreams/Pstreams/PstreamCombineGather.C
src/OpenFOAM/db/IOstreams/Pstreams/PstreamExchange.C
src/OpenFOAM/db/IOstreams/Pstreams/PstreamExchangeConsensus.C
src/OpenFOAM/db/IOstreams/Pstreams/PstreamGather.C
src/OpenFOAM/db/IOstreams/Pstreams/PstreamGatherList.C