OpenFOAM: interstitialInletVelocityFvPatchVectorField Class Reference
interstitialInletVelocityFvPatchVectorField Class Reference
Inlet velocity in which the actual interstitial velocity is calculated by dividing the specified inletVelocity field with the local phase-fraction.
#include <interstitialInletVelocityFvPatchVectorField.H>
Public Member Functions
TypeName ("interstitialInletVelocity")
interstitialInletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
interstitialInletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
interstitialInletVelocityFvPatchVectorField (const interstitialInletVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
interstitialInletVelocityFvPatchVectorField (const interstitialInletVelocityFvPatchVectorField &)
virtual tmp< fvPatchVectorField > clone () const
interstitialInletVelocityFvPatchVectorField (const interstitialInletVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
virtual void autoMap (const fvPatchFieldMapper &)
virtual void rmap (const fvPatchVectorField &, const labelList &)
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
Inlet velocity in which the actual interstitial velocity is calculated by dividing the specified inletVelocity field with the local phase-fraction.
Example of the boundary condition specification:
inlet
{
    type              interstitialInletVelocity;
    inletVelocity     uniform (0 0.2 0);// Non-interstitial inlet velocity
    alpha             alpha.particles;  // Name of the phase-fraction field
    value             uniform (0 0 0);
}
Source files
interstitialInletVelocityFvPatchVectorField.H
interstitialInletVelocityFvPatchVectorField.C
Definition at line 57 of file interstitialInletVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
interstitialInletVelocityFvPatchVectorField() [1/5]
interstitialInletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Definition at line 30 of file interstitialInletVelocityFvPatchVectorField.C.
interstitialInletVelocityFvPatchVectorField() [2/5]
interstitialInletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Definition at line 58 of file interstitialInletVelocityFvPatchVectorField.C.
interstitialInletVelocityFvPatchVectorField() [3/5]
interstitialInletVelocityFvPatchVectorField (const interstitialInletVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 43 of file interstitialInletVelocityFvPatchVectorField.C.
interstitialInletVelocityFvPatchVectorField() [4/5]
interstitialInletVelocityFvPatchVectorField (const interstitialInletVelocityFvPatchVectorField & ptf)
Definition at line 72 of file interstitialInletVelocityFvPatchVectorField.C.
interstitialInletVelocityFvPatchVectorField() [5/5]
interstitialInletVelocityFvPatchVectorField (const interstitialInletVelocityFvPatchVectorField & ptf, const DimensionedField< vector, volMesh > & iF)
Definition at line 84 of file interstitialInletVelocityFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("interstitialInletVelocity")
clone() [1/2]
virtual tmp< fvPatchVectorField > clone () const inline virtual
Definition at line 111 of file interstitialInletVelocityFvPatchVectorField.H.
clone() [2/2]
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Definition at line 127 of file interstitialInletVelocityFvPatchVectorField.H.
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Definition at line 99 of file interstitialInletVelocityFvPatchVectorField.C.
rmap()
void rmap (const fvPatchVectorField & ptf, const labelList & addr) virtual
Definition at line 109 of file interstitialInletVelocityFvPatchVectorField.C.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 124 of file interstitialInletVelocityFvPatchVectorField.C.
References Foam::operator==().
write()
void write (Ostream & os) const virtual
Definition at line 138 of file interstitialInletVelocityFvPatchVectorField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntryIfDifferent(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/interstitialInletVelocity/interstitialInletVelocityFvPatchVectorField.H
src/finiteVolume/fields/fvPatchFields/derived/interstitialInletVelocity/interstitialInletVelocityFvPatchVectorField.C