OpenFOAM: laminarModel< BasicTurbulenceModel > Class Template Reference
laminarModel< BasicTurbulenceModel > Class Template Reference
Templated abstract base class for laminar transport models.
#include <laminarModel.H>
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("laminar")
declareRunTimeSelectionTable (autoPtr, laminarModel, dictionary,(const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName),(alpha, rho, U, alphaRhoPhi, phi, transport, propertiesName))
laminarModel (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~laminarModel ()=default
virtual bool read ()
virtual const dictionary & coeffDict () const
virtual tmp< volScalarField > nut () const
virtual tmp< scalarField > nut (const label patchi) const
virtual tmp< volScalarField > nuEff () const
virtual tmp< scalarField > nuEff (const label patchi) const
virtual tmp< volScalarField > k () const
virtual tmp< volScalarField > epsilon () const
virtual tmp< volScalarField > omega () const
virtual tmp< volSymmTensorField > R () const
virtual void correct ()
Static Public Member Functions
static autoPtr< laminarModel > New (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Protected Member Functions
virtual void printCoeffs (const word &type)
laminarModel (const laminarModel &)=delete
void operator= (const laminarModel &)=delete
Protected Attributes
dictionary laminarDict_
Switch printCoeffs_
dictionary coeffDict_
Detailed Description
template<class BasicTurbulenceModel>
class Foam::laminarModel< BasicTurbulenceModel >
Templated abstract base class for laminar transport models.
Source files
laminarModel.H
laminarModel.C
Definition at line 48 of file laminarModel.H.
Member Typedef Documentation
alphaField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 81 of file laminarModel.H.
rhoField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 82 of file laminarModel.H.
transportModel
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 83 of file laminarModel.H.
Constructor & Destructor Documentation
laminarModel() [1/2]
template<class BasicTurbulenceModel > laminarModel (const laminarModel< BasicTurbulenceModel > &) protected delete
laminarModel() [2/2]
template<class BasicTurbulenceModel > laminarModel (const word & type, const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName)
Definition at line 40 of file laminarModel.C.
~laminarModel()
template<class BasicTurbulenceModel > virtual ~laminarModel () virtual default
Member Function Documentation
printCoeffs()
template<class BasicTurbulenceModel > void printCoeffs (const word & type) protected virtual
Definition at line 28 of file laminarModel.C.
References Foam::endl(), and Foam::Info.
Referenced by Maxwell< BasicTurbulenceModel >::Maxwell().
operator=()
template<class BasicTurbulenceModel > void operator= (const laminarModel< BasicTurbulenceModel > &) protected delete
TypeName()
template<class BasicTurbulenceModel > TypeName ("laminar")
declareRunTimeSelectionTable()
template<class BasicTurbulenceModel > declareRunTimeSelectionTable (autoPtr , laminarModel< BasicTurbulenceModel > , dictionary , (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName) , (alpha, rho, U, alphaRhoPhi, phi, transport, propertiesName))
New()
template<class BasicTurbulenceModel > Foam::autoPtr< Foam::laminarModel< BasicTurbulenceModel > > New (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName) static
Definition at line 78 of file laminarModel.C.
References dict, dictionary::findDict(), dictionary::getCompat(), IOobject::group(), IOobject::groupName(), IOobjectOption::MUST_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, and U.
read()
template<class BasicTurbulenceModel > bool read () virtual
Reimplemented in generalizedNewtonian< BasicMomentumTransportModel >, Maxwell< BasicTurbulenceModel >, Stokes< BasicTurbulenceModel >, linearViscousStress< laminarModel< BasicMomentumTransportModel > >, and linearViscousStress< laminarModel< BasicTurbulenceModel > >.
Definition at line 166 of file laminarModel.C.
coeffDict()
template<class BasicTurbulenceModel > virtual const dictionary & coeffDict () const inline virtual
Reimplemented in Stokes< BasicTurbulenceModel >.
Definition at line 154 of file laminarModel.H.
References laminarModel< BasicTurbulenceModel >::coeffDict_.
nut() [1/2]
template<class BasicTurbulenceModel > Foam::tmp< Foam::volScalarField > nut () const virtual
Reimplemented in generalizedNewtonian< BasicMomentumTransportModel >, and Stokes< BasicTurbulenceModel >.
Definition at line 183 of file laminarModel.C.
nut() [2/2]
template<class BasicTurbulenceModel > Foam::tmp< Foam::scalarField > nut (const label patchi) const virtual
Reimplemented in generalizedNewtonian< BasicMomentumTransportModel >, and Stokes< BasicTurbulenceModel >.
Definition at line 204 of file laminarModel.C.
References Foam::Zero.
nuEff() [1/2]
template<class BasicTurbulenceModel > Foam::tmp< Foam::volScalarField > nuEff () const virtual
Reimplemented in generalizedNewtonian< BasicMomentumTransportModel >, and Stokes< BasicTurbulenceModel >.
Definition at line 218 of file laminarModel.C.
References IOobject::groupName().
nuEff() [2/2]
template<class BasicTurbulenceModel > Foam::tmp< Foam::scalarField > nuEff (const label patchi) const virtual
Reimplemented in generalizedNewtonian< BasicMomentumTransportModel >, and Stokes< BasicTurbulenceModel >.
Definition at line 232 of file laminarModel.C.
References nu.
k()
template<class BasicTurbulenceModel > Foam::tmp< Foam::volScalarField > k () const virtual
Definition at line 243 of file laminarModel.C.
References IOobject::groupName(), tmp< T >::New(), IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, Foam::sqr(), and Foam::Zero.
epsilon()
template<class BasicTurbulenceModel > Foam::tmp< Foam::volScalarField > epsilon () const virtual
Definition at line 264 of file laminarModel.C.
References Foam::dimTime, IOobject::groupName(), tmp< T >::New(), IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, Foam::sqr(), and Foam::Zero.
omega()
template<class BasicTurbulenceModel > Foam::tmp< Foam::volScalarField > omega () const virtual
Definition at line 285 of file laminarModel.C.
References Foam::dimless, Foam::dimTime, IOobject::groupName(), tmp< T >::New(), IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, and Foam::Zero.
R()
template<class BasicTurbulenceModel > Foam::tmp< Foam::volSymmTensorField > R () const virtual
Reimplemented in Maxwell< BasicTurbulenceModel >.
Definition at line 306 of file laminarModel.C.
References IOobject::groupName(), tmp< T >::New(), IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, Foam::sqr(), and Foam::Zero.
correct()
template<class BasicTurbulenceModel > void correct () virtual
Reimplemented in generalizedNewtonian< BasicMomentumTransportModel >, Maxwell< BasicTurbulenceModel >, Stokes< BasicTurbulenceModel >, linearViscousStress< laminarModel< BasicMomentumTransportModel > >, and linearViscousStress< laminarModel< BasicTurbulenceModel > >.
Definition at line 326 of file laminarModel.C.
Referenced by generalizedNewtonian< BasicMomentumTransportModel >::correct(), Maxwell< BasicTurbulenceModel >::correct(), and Stokes< BasicTurbulenceModel >::correct().
Member Data Documentation
laminarDict_
template<class BasicTurbulenceModel > dictionary laminarDict_ protected
Definition at line 58 of file laminarModel.H.
printCoeffs_
template<class BasicTurbulenceModel > Switch printCoeffs_ protected
Definition at line 61 of file laminarModel.H.
coeffDict_
template<class BasicTurbulenceModel > dictionary coeffDict_ protected
Definition at line 64 of file laminarModel.H.
Referenced by laminarModel< BasicTurbulenceModel >::coeffDict().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/laminar/laminarModel/laminarModel.H
src/TurbulenceModels/turbulenceModels/laminar/laminarModel/laminarModel.C