OpenFOAM: writerCaching Class Reference
writerCaching Class Reference
State information for writers with collated times.
#include <ensightWriterCaching.H>
Public Member Functions
writerCaching (const word &cacheFileName)
virtual ~writerCaching ()=default
const scalarList & times () const noexcept
const bitSet & geometries () const noexcept
label latestTimeIndex () const
label latestGeomIndex () const
int geometryTimeset () const
const dictionary & fieldsDict () const
void clear ()
bool update (const fileName &baseDir, const scalar timeValue, const bool geomChanged, const word &fieldName, const word &fieldType, const word &varName=word::null)
Detailed Description
State information for writers with collated times.
The class maintains an internal list of the known times as well as a file-cached version with the field information. The information is used for restarts.
Source files
ensightWriterCaching.H
ensightWriterCaching.C
Definition at line 55 of file ensightWriterCaching.H.
Constructor & Destructor Documentation
writerCaching()
writerCaching (const word & cacheFileName) explicit
Definition at line 63 of file ensightWriterCaching.C.
~writerCaching()
virtual ~writerCaching () virtual default
Member Function Documentation
times()
const scalarList & times () const inline noexcept
Definition at line 104 of file ensightWriterCaching.H.
geometries()
const bitSet & geometries () const inline noexcept
Definition at line 110 of file ensightWriterCaching.H.
latestTimeIndex()
Foam::label latestTimeIndex () const
Definition at line 180 of file ensightWriterCaching.C.
References Foam::max().
latestGeomIndex()
Foam::label latestGeomIndex () const
Definition at line 185 of file ensightWriterCaching.C.
References Foam::max().
geometryTimeset()
int geometryTimeset () const
Definition at line 193 of file ensightWriterCaching.C.
fieldsDict()
const Foam::dictionary & fieldsDict () const
Definition at line 71 of file ensightWriterCaching.C.
References keyType::LITERAL, and dictionary::null.
clear()
void clear ()
Definition at line 109 of file ensightWriterCaching.C.
References PtrList< T >::clear().
update()
bool update (const fileName & baseDir, const scalar timeValue, const bool geomChanged, const word & fieldName, const word & fieldType, const word & varName = word::null)
Parameters
baseDir Directory containing cache file
timeValue The current time value
geomChanged Monitored geometry changed
fieldName Name of field
fieldType Type of field
varName Alternative field name
Definition at line 213 of file ensightWriterCaching.C.
References dict, UPtrList< T >::empty(), Foam::equalTimes, Foam::findTimeIndex(), Foam::nl, os(), PtrList< T >::resize(), PtrList< T >::set(), and timeIndex.
The documentation for this class was generated from the following files:
src/fileFormats/ensight/file/ensightWriterCaching.H
src/fileFormats/ensight/file/ensightWriterCaching.C