OpenFOAM: IntegralScaleBox< Type > Class Template Reference
IntegralScaleBox< Type > Class Template Reference
Class to describe the integral-scale container being used in the turbulentDigitalFilterInletFvPatchField boundary condition.
#include <IntegralScaleBox.H>
Public Member Functions
IntegralScaleBox (const fvPatch &p)
IntegralScaleBox (const fvPatch &p, const IntegralScaleBox &b)
IntegralScaleBox (const fvPatch &p, const dictionary &dict)
IntegralScaleBox (const IntegralScaleBox &b)
const primitivePatch & patch ()
bool fsm () const noexcept
void initialise ()
void shift ()
void refill ()
Field< Type > convolve () const
void correlate (scalarField &fld)
void correlate (vectorField &fld)
void write (Ostream &) const
Static Public Attributes
static int debug = 0
Detailed Description
template<class Type>
class Foam::turbulence::IntegralScaleBox< Type >
Class to describe the integral-scale container being used in the turbulentDigitalFilterInletFvPatchField boundary condition.
Source files
IntegralScaleBox.H
IntegralScaleBox.C
Definition at line 53 of file IntegralScaleBox.H.
Constructor & Destructor Documentation
IntegralScaleBox() [1/4]
template<class Type > IntegralScaleBox (const fvPatch & p) explicit
Definition at line 474 of file IntegralScaleBox.C.
IntegralScaleBox() [2/4]
template<class Type > IntegralScaleBox (const fvPatch & p, const IntegralScaleBox< Type > & b)
Definition at line 502 of file IntegralScaleBox.C.
IntegralScaleBox() [3/4]
template<class Type > IntegralScaleBox (const fvPatch & p, const dictionary & dict)
Definition at line 531 of file IntegralScaleBox.C.
References Foam::cmptMin(), dict, Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, Foam::min(), and Foam::nl.
IntegralScaleBox() [4/4]
template<class Type > IntegralScaleBox (const IntegralScaleBox< Type > & b)
Definition at line 584 of file IntegralScaleBox.C.
Member Function Documentation
patch()
template<class Type > const primitivePatch & patch () inline
Definition at line 235 of file IntegralScaleBox.H.
fsm()
template<class Type > bool fsm () const inline noexcept
Definition at line 246 of file IntegralScaleBox.H.
initialise()
template<class Type > void initialise ()
Definition at line 614 of file IntegralScaleBox.C.
References Foam::endl(), Foam::Info, Foam::nl, and Foam::Zero.
shift()
template<class Type > void shift ()
Definition at line 664 of file IntegralScaleBox.C.
References Foam::inplaceRotateList().
refill()
template<class Type > void refill ()
Definition at line 683 of file IntegralScaleBox.C.
convolve()
template<class Type > Foam::Field< Type > convolve () const
Definition at line 704 of file IntegralScaleBox.C.
References k, p, UPtrList< T >::size(), Foam::sum(), and Foam::Zero.
correlate() [1/2]
template<class Type > void correlate (scalarField & fld)
Definition at line 831 of file IntegralScaleBox.C.
References fld().
correlate() [2/2]
template<class Type > void correlate (vectorField & fld)
Definition at line 847 of file IntegralScaleBox.C.
References fld().
write()
template<class Type > void write (Ostream & os) const
Definition at line 869 of file IntegralScaleBox.C.
References os().
Member Data Documentation
debug
template<class Type > int debug = 0 static
Definition at line 227 of file IntegralScaleBox.H.
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/turbulentDigitalFilterInlet/IntegralScaleBox/IntegralScaleBox.H
src/finiteVolume/fields/fvPatchFields/derived/turbulentDigitalFilterInlet/IntegralScaleBox/IntegralScaleBox.C