OpenFOAM: PBiCG Class Reference
PBiCG Class Reference
Preconditioned bi-conjugate gradient solver for asymmetric lduMatrices using a run-time selectable preconditioner.
#include <PBiCG.H>
Public Member Functions
TypeName ("PBiCG")
PBiCG (const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces, const dictionary &solverControls)
virtual ~PBiCG ()=default
virtual solverPerformance solve (scalarField &psi, const scalarField &source, const direction cmpt=0) const
Public Member Functions inherited from lduMatrix::solver
virtual const word & type () const =0
declareRunTimeSelectionTable (autoPtr, solver, symMatrix,(const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces, const dictionary &solverControls),(fieldName, matrix, interfaceBouCoeffs, interfaceIntCoeffs, interfaces, solverControls))
declareRunTimeSelectionTable (autoPtr, solver, asymMatrix,(const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces, const dictionary &solverControls),(fieldName, matrix, interfaceBouCoeffs, interfaceIntCoeffs, interfaces, solverControls))
solver (const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces, const dictionary &solverControls)
virtual ~solver ()=default
const word & fieldName () const noexcept
const lduMatrix & matrix () const noexcept
const FieldField< Field, scalar > & interfaceBouCoeffs () const noexcept
const FieldField< Field, scalar > & interfaceIntCoeffs () const noexcept
const lduInterfaceFieldPtrsList & interfaces () const noexcept
virtual void read (const dictionary &)
virtual solverPerformance scalarSolve (solveScalarField &psi, const solveScalarField &source, const direction cmpt=0) const
solveScalarField::cmptType normFactor (const solveScalarField &psi, const solveScalarField &source, const solveScalarField &Apsi, solveScalarField &tmpField, const lduMatrix::normTypes normType) const
solveScalarField::cmptType normFactor (const solveScalarField &psi, const solveScalarField &source, const solveScalarField &Apsi, solveScalarField &tmpField) const
Additional Inherited Members
Static Public Member Functions inherited from lduMatrix::solver
static autoPtr< solver > New (const word &solverName, const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces, const dictionary &solverControls)
static autoPtr< solver > New (const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces, const dictionary &solverControls)
Protected Member Functions inherited from lduMatrix::solver
virtual void readControls ()
Protected Attributes inherited from lduMatrix::solver
word fieldName_
const lduMatrix & matrix_
const FieldField< Field, scalar > & interfaceBouCoeffs_
const FieldField< Field, scalar > & interfaceIntCoeffs_
lduInterfaceFieldPtrsList interfaces_
dictionary controlDict_
int log_
label minIter_
label maxIter_
lduMatrix::normTypes normType_
scalar tolerance_
scalar relTol_
profilingTrigger profiling_
Detailed Description
Preconditioned bi-conjugate gradient solver for asymmetric lduMatrices using a run-time selectable preconditioner.
Source files
PBiCG.H
PBiCG.C
Definition at line 48 of file PBiCG.H.
Constructor & Destructor Documentation
PBiCG()
PBiCG (const word & fieldName, const lduMatrix & matrix, const FieldField< Field, scalar > & interfaceBouCoeffs, const FieldField< Field, scalar > & interfaceIntCoeffs, const lduInterfaceFieldPtrsList & interfaces, const dictionary & solverControls)
Definition at line 38 of file PBiCG.C.
~PBiCG()
virtual ~PBiCG () virtual default
Member Function Documentation
TypeName()
TypeName ("PBiCG")
solve()
Foam::solverPerformance solve (scalarField & psi, const scalarField & source, const direction cmpt = 0) const virtual
Implements lduMatrix::solver.
Definition at line 62 of file PBiCG.C.
References alpha, UPtrList< T >::begin(), beta(), lduMatrix::defaultMaxIter, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, lduMatrix::preconditioner::getName(), Foam::gSumMag(), Foam::gSumProd(), Foam::Info, Foam::mag(), Foam::max(), mesh, lduMatrix::preconditioner::New(), Foam::nl, psi, and UPtrList< T >::size().
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/lduMatrix/solvers/PBiCG/PBiCG.H
src/OpenFOAM/matrices/lduMatrix/solvers/PBiCG/PBiCG.C