OpenFOAM: triSurfaceTools Class Reference
triSurfaceTools Class Reference
A collection of tools for triSurface.
#include <triSurfaceTools.H>
Public Types
enum sideType { UNKNOWN , INSIDE , OUTSIDE }
Public Member Functions
triSurface triangulateFaceCentre (const polyBoundaryMesh &mBesh, const labelHashSet &includePatches, const bool verbose=false)
scalarField featureProximity (const triSurface &surf, const scalar searchDistance)
Static Public Member Functions
static void writeOBJ (const fileName &fName, const pointField &pts)
static void writeOBJ (const triSurface &surf, const fileName &fName, const boolList &markedVerts)
static void getVertexTriangles (const triSurface &surf, const label edgeI, labelList &edgeTris)
static labelList getVertexVertices (const triSurface &surf, const edge &e)
static label otherFace (const triSurface &surf, const label facei, const label edgeI)
static void otherEdges (const triSurface &surf, const label facei, const label edgeI, label &e1, label &e2)
static void otherVertices (const triSurface &surf, const label facei, const label vertI, label &vert1I, label &vert2I)
static label oppositeEdge (const triSurface &surf, const label facei, const label vertI)
static label oppositeVertex (const triSurface &surf, const label facei, const label edgeI)
static label getEdge (const triSurface &surf, const label vert1I, const label vert2I)
static label getTriangle (const triSurface &surf, const label e0I, const label e1I, const label e2I)
static triSurface collapseEdges (const triSurface &surf, const labelList &collapsableEdges)
static triSurface collapseEdges (const triSurface &surf, const labelList &collapsableEdges, const pointField &edgeMids, labelList &faceStatus)
static triSurface greenRefine (const triSurface &surf, const labelList &refineEdges)
static triSurface redGreenRefine (const triSurface &surf, const labelList &refineFaces)
static label minEdge (const triSurface &surf, const labelList &edgeIndices)
static label maxEdge (const triSurface &surf, const labelList &edgeIndices)
static triSurface mergePoints (const triSurface &surf, const scalar mergeTol)
static vector surfaceNormal (const triSurface &surf, const label nearestFacei, const point &nearestPt)
static sideType edgeSide (const triSurface &surf, const point &sample, const point &nearestPoint, const label edgeI)
static sideType surfaceSide (const triSurface &surf, const point &sample, const label nearestFacei)
static triSurface triangulate (const polyBoundaryMesh &mBesh, const labelHashSet &includePatches, labelList &faceMap, const bool verbose=false)
static triSurface triangulate (const polyBoundaryMesh &bMesh, const labelHashSet &includePatches, const boundBox &bBox, const bool verbose=false)
static triSurface delaunay2D (const List< vector2D > &)
static void calcInterpolationWeights (const triPointRef &tri, const point &p, FixedList< scalar, 3 > &weights)
static void calcInterpolationWeights (const triSurface &s, const pointField &samplePts, List< FixedList< label, 3 > > &allVerts, List< FixedList< scalar, 3 > > &allWeights)
static scalar vertexNormalWeight (const triFace &f, const label pI, const vector &fN, const UList< point > &points)
static tmp< vectorField > vertexNormals (const triSurface &surf)
static tmp< triadField > vertexTriads (const triSurface &surf, const vectorField &pointNormals)
static tmp< scalarField > curvatures (const triSurface &surf, const vectorField &pointNormals, const triadField &pointTriads)
static tmp< scalarField > curvatures (const triSurface &surf)
static tmp< scalarField > writeCurvature (const Time &runTime, const word &basename, const triSurface &surf)
static Pair< tmp< scalarField > > writeCloseness (const Time &runTime, const word &basename, const triSurface &surf, const scalar internalAngleTolerance=45, const scalar externalAngleTolerance=10)
static void writeFeatureProximity (const Time &runTime, const word &basename, const triSurface &surf, const bool writeVTK, const scalar searchDistance)
static bool validTri (const triSurface &, const label facei, const bool verbose=true)
static bool validTri (const MeshedSurface< face > &, const label facei, const bool verbose=true)
static surfaceLocation classify (const triSurface &, const label triI, const point &trianglePoint)
static surfaceLocation trackToEdge (const triSurface &, const surfaceLocation &start, const surfaceLocation &end, const plane &cutPlane)
static void track (const triSurface &, const surfaceLocation &endInfo, const plane &cutPlane, surfaceLocation &hitInfo)
Static Public Attributes
static const label ANYEDGE = -1
static const label NOEDGE = -2
static const label COLLAPSED = -3
Detailed Description
A collection of tools for triSurface.
Note
The curvature calculation is an implementation of the algorithm from:
    "Estimating Curvatures and their Derivatives on Triangle Meshes"
    by S. Rusinkiewicz
    3DPVT'04 Proceedings of the 3D Data Processing,
    Visualization, and Transmission, 2nd International Symposium
    Pages 486-493
    http://gfx.cs.princeton.edu/pubs/_2004_ECA/curvpaper.pdf
Source files
triSurfaceTools.H
triSurfaceTools.C
triSurfaceCloseness.C
triSurfaceCurvature.C
Definition at line 82 of file triSurfaceTools.H.
Member Enumeration Documentation
sideType
enum sideType
Enumerator
UNKNOWN
INSIDE
OUTSIDE
Definition at line 446 of file triSurfaceTools.H.
Member Function Documentation
writeOBJ() [1/2]
void writeOBJ (const fileName & fName, const pointField & pts) static
Definition at line 1188 of file triSurfaceTools.C.
References Foam::endl(), Foam::Pout, pts, and UPtrList< T >::size().
writeOBJ() [2/2]
void writeOBJ (const triSurface & surf, const fileName & fName, const boolList & markedVerts) static
Definition at line 1205 of file triSurfaceTools.C.
References Foam::endl(), forAll, PrimitivePatch< FaceList, PointField >::localPoints(), Foam::Pout, Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
getVertexTriangles()
void getVertexTriangles (const triSurface & surf, const label edgeI, labelList & edgeTris) static
Definition at line 1235 of file triSurfaceTools.C.
References e, PrimitivePatch< FaceList, PointField >::edgeFaces(), PrimitivePatch< FaceList, PointField >::edges(), UList< T >::end(), PrimitivePatch< FaceList, PointField >::pointFaces(), PtrList< T >::setSize(), and UPtrList< T >::size().
getVertexVertices()
Foam::labelList getVertexVertices (const triSurface & surf, const edge & e) static
Definition at line 1276 of file triSurfaceTools.C.
References e, PrimitivePatch< FaceList, PointField >::edges(), UList< T >::end(), and PrimitivePatch< FaceList, PointField >::pointEdges().
otherFace()
Foam::label otherFace (const triSurface & surf, const label facei, const label edgeI) static
Definition at line 1307 of file triSurfaceTools.C.
References PrimitivePatch< FaceList, PointField >::edgeFaces(), and UPtrList< T >::size().
otherEdges()
void otherEdges (const triSurface & surf, const label facei, const label edgeI, label & e1, label & e2) static
Definition at line 1332 of file triSurfaceTools.C.
References Foam::abort(), PrimitivePatch< FaceList, PointField >::edges(), PrimitivePatch< FaceList, PointField >::faceEdges(), Foam::FatalError, FatalErrorInFunction, and PrimitivePatch< FaceList, PointField >::localFaces().
otherVertices()
void otherVertices (const triSurface & surf, const label facei, const label vertI, label & vert1I, label & vert2I) static
Definition at line 1361 of file triSurfaceTools.C.
References Foam::abort(), f(), Foam::FatalError, FatalErrorInFunction, PrimitivePatch< FaceList, PointField >::localFaces(), and Foam::nl.
oppositeEdge()
Foam::label oppositeEdge (const triSurface & surf, const label facei, const label vertI) static
Definition at line 1397 of file triSurfaceTools.C.
References Foam::abort(), e, PrimitivePatch< FaceList, PointField >::edges(), PrimitivePatch< FaceList, PointField >::faceEdges(), Foam::FatalError, FatalErrorInFunction, UList< T >::found(), and Foam::nl.
oppositeVertex()
Foam::label oppositeVertex (const triSurface & surf, const label facei, const label edgeI) static
Definition at line 1426 of file triSurfaceTools.C.
References Foam::abort(), e, PrimitivePatch< FaceList, PointField >::edges(), f(), Foam::FatalError, FatalErrorInFunction, UList< T >::found(), and PrimitivePatch< FaceList, PointField >::localFaces().
getEdge()
Foam::label getEdge (const triSurface & surf, const label vert1I, const label vert2I) static
Definition at line 1453 of file triSurfaceTools.C.
References e, PrimitivePatch< FaceList, PointField >::edges(), UList< T >::found(), and PrimitivePatch< FaceList, PointField >::pointEdges().
getTriangle()
Foam::label getTriangle (const triSurface & surf, const label e0I, const label e1I, const label e2I) static
Definition at line 1476 of file triSurfaceTools.C.
References Foam::abort(), PrimitivePatch< FaceList, PointField >::edgeFaces(), PrimitivePatch< FaceList, PointField >::faceEdges(), Foam::FatalError, and FatalErrorInFunction.
collapseEdges() [1/2]
Foam::triSurface collapseEdges (const triSurface & surf, const labelList & collapsableEdges) static
Definition at line 1521 of file triSurfaceTools.C.
References e, PrimitivePatch< FaceList, PointField >::edges(), forAll, PrimitivePatch< FaceList, PointField >::localPoints(), PrimitivePatch< FaceList, PointField >::nEdges(), and UList< T >::size().
collapseEdges() [2/2]
Foam::triSurface collapseEdges (const triSurface & surf, const labelList & collapsableEdges, const pointField & edgeMids, labelList & faceStatus) static
Definition at line 1568 of file triSurfaceTools.C.
References Foam::abort(), e, PrimitivePatch< FaceList, PointField >::edgeFaces(), PrimitivePatch< FaceList, PointField >::edges(), UList< T >::end(), Foam::endl(), f(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::identity(), PrimitivePatch< FaceList, PointField >::localFaces(), PrimitivePatch< FaceList, PointField >::localPoints(), Foam::min(), PrimitivePatch< FaceList, PointField >::nEdges(), triSurface::patches(), PtrList< T >::resize(), UPtrList< T >::size(), and UList< T >::size().
greenRefine()
Foam::triSurface greenRefine (const triSurface & surf, const labelList & refineEdges) static
Definition at line 1735 of file triSurfaceTools.C.
References PtrList< T >::append(), e, PrimitivePatch< FaceList, PointField >::edgeFaces(), PrimitivePatch< FaceList, PointField >::edges(), forAll, PrimitivePatch< FaceList, PointField >::localFaces(), PrimitivePatch< FaceList, PointField >::localPoints(), PrimitivePatch< FaceList, PointField >::nEdges(), newPointi, PrimitivePatch< FaceList, PointField >::nPoints(), triSurface::patches(), List< T >::setSize(), and UList< T >::size().
redGreenRefine()
Foam::triSurface redGreenRefine (const triSurface & surf, const labelList & refineFaces) static
Definition at line 1716 of file triSurfaceTools.C.
References forAll, and UList< T >::size().
minEdge()
Foam::label minEdge (const triSurface & surf, const labelList & edgeIndices) static
Definition at line 1818 of file triSurfaceTools.C.
References e, PrimitivePatch< FaceList, PointField >::edges(), and PrimitivePatch< FaceList, PointField >::localPoints().
maxEdge()
Foam::label maxEdge (const triSurface & surf, const labelList & edgeIndices) static
Definition at line 1845 of file triSurfaceTools.C.
References e, PrimitivePatch< FaceList, PointField >::edges(), and PrimitivePatch< FaceList, PointField >::localPoints().
mergePoints()
Foam::triSurface mergePoints (const triSurface & surf, const scalar mergeTol) static
Definition at line 1872 of file triSurfaceTools.C.
References f(), PrimitivePatch< FaceList, PointField >::localFaces(), PrimitivePatch< FaceList, PointField >::localPoints(), Foam::mergePoints(), triSurface::patches(), PtrList< T >::resize(), and UList< T >::size().
surfaceNormal()
Foam::vector surfaceNormal (const triSurface & surf, const label nearestFacei, const point & nearestPt) static
Definition at line 1929 of file triSurfaceTools.C.
References triangle< Point, PointRef >::EDGE, PrimitivePatch< FaceList, PointField >::edgeFaces(), f(), PrimitivePatch< FaceList, PointField >::faceEdges(), PrimitivePatch< FaceList, PointField >::faceNormals(), PrimitivePatch< FaceList, PointField >::localFaces(), triangle< Point, PointRef >::NONE, Foam::normalised(), PrimitivePatch< FaceList, PointField >::pointNormals(), points, PrimitivePatch< FaceList, PointField >::points(), and Foam::Zero.
edgeSide()
Foam::triSurfaceTools::sideType edgeSide (const triSurface & surf, const point & sample, const point & nearestPoint, const label edgeI) static
Definition at line 1973 of file triSurfaceTools.C.
References PrimitivePatch< FaceList, PointField >::edgeFaces(), PrimitivePatch< FaceList, PointField >::faceNormals(), n, and UPtrList< T >::size().
surfaceSide()
Foam::triSurfaceTools::sideType surfaceSide (const triSurface & surf, const point & sample, const label nearestFacei) static
Definition at line 2010 of file triSurfaceTools.C.
References Foam::abort(), e, triangle< Point, PointRef >::EDGE, PrimitivePatch< FaceList, PointField >::edges(), f(), PrimitivePatch< FaceList, PointField >::faceEdges(), PrimitivePatch< FaceList, PointField >::faceNormals(), Foam::FatalError, FatalErrorInFunction, forAll, PrimitivePatch< FaceList, PointField >::localFaces(), PrimitivePatch< FaceList, PointField >::localPoints(), Foam::mag(), Foam::magSqr(), triangle< Point, PointRef >::NONE, PrimitivePatch< FaceList, PointField >::pointEdges(), points, PrimitivePatch< FaceList, PointField >::points(), and Foam::sqr().
Referenced by treeDataPrimitivePatch< PatchType >::getVolumeType().
triangulate() [1/2]
Foam::triSurface triangulate (const polyBoundaryMesh & mBesh, const labelHashSet & includePatches, labelList & faceMap, const bool verbose = false) static
Definition at line 2166 of file triSurfaceTools.C.
References Foam::endl(), f(), Foam::faceMap(), mesh, points, polyMesh::points(), Foam::Pout, List< T >::setSize(), PtrList< T >::setSize(), UPtrList< T >::size(), and triangles.
Referenced by powerLawLopesdaCostaZone::powerLawLopesdaCostaZone().
triangulate() [2/2]
Foam::triSurface triangulate (const polyBoundaryMesh & bMesh, const labelHashSet & includePatches, const boundBox & bBox, const bool verbose = false) static
Definition at line 2264 of file triSurfaceTools.C.
References PtrList< T >::append(), Foam::endl(), f(), forAll, mesh, primitiveMesh::nBoundaryFaces(), points, polyMesh::points(), Foam::Pout, PtrList< T >::setSize(), UPtrList< T >::size(), and triangles.
triangulateFaceCentre()
Foam::triSurface triangulateFaceCentre (const polyBoundaryMesh & mBesh, const labelHashSet & includePatches, const bool verbose = false)
Definition at line 2350 of file triSurfaceTools.C.
References PtrList< T >::append(), Foam::endl(), f(), primitiveMesh::faceCentres(), UList< T >::fcIndex(), forAll, mesh, primitiveMesh::nBoundaryFaces(), newPointi, points, polyMesh::points(), Foam::Pout, PtrList< T >::setSize(), UPtrList< T >::size(), UList< T >::size(), and triangles.
delaunay2D()
Foam::triSurface delaunay2D (const List< vector2D > & pts) static
Definition at line 2447 of file triSurfaceTools.C.
References Foam::abort(), UPtrList< T >::begin(), dtris2(), Foam::FatalError, FatalErrorInFunction, forAll, points, pts, PtrList< T >::setSize(), and UPtrList< T >::size().
calcInterpolationWeights() [1/2]
void calcInterpolationWeights (const triPointRef & tri, const point & p, FixedList< scalar, 3 > & weights) static
Definition at line 2512 of file triSurfaceTools.C.
References triangle< Point, PointRef >::a(), triangle< Point, PointRef >::b(), triangle< Point, PointRef >::c(), Foam::max(), Foam::normalised(), and p.
calcInterpolationWeights() [2/2]
void calcInterpolationWeights (const triSurface & s, const pointField & samplePts, List< FixedList< label, 3 > > & allVerts, List< FixedList< scalar, 3 > > & allWeights) static
Definition at line 2543 of file triSurfaceTools.C.
References Vector< Cmpt >::dist(), PointHit< PointType >::distance(), triangle< Point, PointRef >::EDGE, f(), UList< T >::fcIndex(), forAll, PointHit< PointType >::hit(), Foam::min(), triangle< Point, PointRef >::nearestPointClassify(), p0, PointHit< PointType >::point(), triangle< Point, PointRef >::POINT, points, s(), PtrList< T >::setSize(), and UPtrList< T >::size().
vertexNormalWeight()
Foam::scalar vertexNormalWeight (const triFace & f, const label pI, const vector & fN, const UList< point > & points) static
Definition at line 35 of file triSurfaceCurvature.C.
References Foam::abort(), f(), Foam::FatalError, FatalErrorInFunction, Foam::mag(), Foam::magSqr(), and points.
Referenced by triSurfaceTools::curvatures().
vertexNormals()
Foam::tmp< Foam::vectorField > vertexNormals (const triSurface & surf) static
Definition at line 59 of file triSurfaceCurvature.C.
References Foam::endl(), f(), forAll, Foam::Info, PrimitivePatch< FaceList, PointField >::meshPoints(), tmp< T >::New(), PrimitivePatch< FaceList, PointField >::nPoints(), pFaces, PrimitivePatch< FaceList, PointField >::pointFaces(), points, PrimitivePatch< FaceList, PointField >::points(), and Foam::Zero.
Referenced by triSurfaceTools::curvatures().
vertexTriads()
Foam::tmp< Foam::triadField > vertexTriads (const triSurface & surf, const vectorField & pointNormals) static
Definition at line 102 of file triSurfaceCurvature.C.
References e, forAll, Foam::mag(), PrimitivePatch< FaceList, PointField >::meshPointMap(), tmp< T >::New(), Foam::normalised(), p, points, PrimitivePatch< FaceList, PointField >::points(), UPtrList< T >::size(), and triad::unset.
Referenced by triSurfaceTools::curvatures().
curvatures() [1/2]
Foam::tmp< Foam::scalarField > curvatures (const triSurface & surf, const vectorField & pointNormals, const triadField & pointTriads) static
Definition at line 139 of file triSurfaceCurvature.C.
References e, Foam::eigenValues(), Foam::endl(), f(), forAll, Foam::Info, Foam::LUsolve(), Foam::mag(), Foam::magSqr(), Foam::max(), PrimitivePatch< FaceList, PointField >::meshPointMap(), PrimitivePatch< FaceList, PointField >::meshPoints(), tmp< T >::New(), points, PrimitivePatch< FaceList, PointField >::points(), Foam::rotationTensor(), PtrList< T >::set(), UPtrList< T >::size(), UList< T >::size(), Foam::sqr(), T, triSurfaceTools::vertexNormalWeight(), x, y, Foam::Zero, and VectorSpace< SymmTensor2D< Cmpt >, Cmpt, 3 >::zero.
Referenced by refinementSurfaces::setCurvatureMinLevelFields(), and triSurfaceTools::writeCurvature().
curvatures() [2/2]
Foam::tmp< Foam::scalarField > curvatures (const triSurface & surf) static
Definition at line 324 of file triSurfaceCurvature.C.
References PtrList< T >::clear(), triSurfaceTools::vertexNormals(), and triSurfaceTools::vertexTriads().
writeCurvature()
Foam::tmp< Foam::scalarField > writeCurvature (const Time & runTime, const word & basename, const triSurface & surf) static
Definition at line 341 of file triSurfaceCurvature.C.
References TimePaths::constant(), triSurfaceTools::curvatures(), Foam::dimLength, Foam::endl(), Foam::Info, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, runTime, and UPtrList< T >::swap().
writeCloseness()
Foam::Pair< Foam::tmp< Foam::scalarField > > writeCloseness (const Time & runTime, const word & basename, const triSurface & surf, const scalar internalAngleTolerance = 45, const scalar externalAngleTolerance = 10) static
Definition at line 88 of file triSurfaceCloseness.C.
References Foam::cos(), Foam::degToRad(), Foam::dimLength, Foam::drawHitProblem(), Foam::endl(), forAll, Foam::Info, Foam::nl, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, runTime, UPtrList< T >::size(), UList< T >::size(), and UPtrList< T >::swap().
featureProximity()
scalarField featureProximity (const triSurface & surf, const scalar searchDistance)
writeFeatureProximity()
static void writeFeatureProximity (const Time & runTime, const word & basename, const triSurface & surf, const bool writeVTK, const scalar searchDistance) static
validTri() [1/2]
bool validTri (const triSurface & surf, const label facei, const bool verbose = true) static
Definition at line 2666 of file triSurfaceTools.C.
References Foam::endl(), f(), PrimitivePatch< FaceList, PointField >::faceFaces(), PrimitivePatch< FaceList, PointField >::points(), UPtrList< T >::size(), and WarningInFunction.
Referenced by isoSurfaceCell::isoSurfaceCell(), and isoSurfacePoint::isoSurfacePoint().
validTri() [2/2]
bool validTri (const MeshedSurface< face > & surf, const label facei, const bool verbose = true) static
Definition at line 2745 of file triSurfaceTools.C.
References Foam::endl(), f(), UPtrList< T >::size(), UList< T >::size(), and WarningInFunction.
classify()
Foam::surfaceLocation classify (const triSurface & s, const label triI, const point & trianglePoint) static
Definition at line 2839 of file triSurfaceTools.C.
References triangle< Point, PointRef >::EDGE, surfaceLocation::elementType(), triangle< Point, PointRef >::NONE, triangle< Point, PointRef >::POINT, s(), PointIndexHit< PointType >::setHit(), PointIndexHit< PointType >::setIndex(), PointIndexHit< PointType >::setMiss(), and PointIndexHit< PointType >::setPoint().
trackToEdge()
Foam::surfaceLocation trackToEdge (const triSurface & s, const surfaceLocation & start, const surfaceLocation & end, const plane & cutPlane) static
Definition at line 2883 of file triSurfaceTools.C.
References triangle< Point, PointRef >::EDGE, surfaceLocation::elementType(), PointIndexHit< PointType >::hit(), PointIndexHit< PointType >::index(), triangle< Point, PointRef >::NONE, pFaces, PointIndexHit< PointType >::point(), s(), PointIndexHit< PointType >::setMiss(), and surfaceLocation::triangle().
track()
void track (const triSurface & s, const surfaceLocation & endInfo, const plane & cutPlane, surfaceLocation & hitInfo) static
Definition at line 2961 of file triSurfaceTools.C.
References s().
Member Data Documentation
ANYEDGE
const Foam::label ANYEDGE = -1 static
Definition at line 376 of file triSurfaceTools.H.
NOEDGE
const Foam::label NOEDGE = -2 static
Definition at line 377 of file triSurfaceTools.H.
COLLAPSED
const Foam::label COLLAPSED = -3 static
Definition at line 378 of file triSurfaceTools.H.
The documentation for this class was generated from the following files:
src/meshTools/triSurface/triSurfaceTools/triSurfaceTools.H
src/meshTools/triSurface/triSurfaceTools/triSurfaceCloseness.C
src/meshTools/triSurface/triSurfaceTools/triSurfaceCurvature.C
src/meshTools/triSurface/triSurfaceTools/triSurfaceTools.C