OpenFOAM: turbulentMixingLengthFrequencyInletFvPatchScalarField Class Reference
turbulentMixingLengthFrequencyInletFvPatchScalarField Class Reference
Turbulence models » RAS turbulence » Boundary conditions | Boundary conditions » Inlet
This boundary condition provides a turbulence specific dissipation, (omega) inlet condition based on a specified mixing length. The patch values are calculated using:
#include <turbulentMixingLengthFrequencyInletFvPatchScalarField.H>
Public Member Functions
TypeName ("turbulentMixingLengthFrequencyInlet")
turbulentMixingLengthFrequencyInletFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
turbulentMixingLengthFrequencyInletFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
turbulentMixingLengthFrequencyInletFvPatchScalarField (const turbulentMixingLengthFrequencyInletFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
turbulentMixingLengthFrequencyInletFvPatchScalarField (const turbulentMixingLengthFrequencyInletFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
turbulentMixingLengthFrequencyInletFvPatchScalarField (const turbulentMixingLengthFrequencyInletFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
This boundary condition provides a turbulence specific dissipation, (omega) inlet condition based on a specified mixing length. The patch values are calculated using:
where
= patch omega values
= Model coefficient, set to 0.09
= turbulence kinetic energy
= length scale
Usage
Property Description Required Default value
mixingLength Length scale [m] yes
phi flux field name no phi
k turbulence kinetic energy field name no k
Example of the boundary condition specification:
    <patchName>
    {
        type            turbulentMixingLengthFrequencyInlet;
        mixingLength    0.005;
        value           uniform 200;   // placeholder
    }
Note
In the event of reverse flow, a zero-gradient condition is applied
See also
Foam::inletOutletFvPatchField
Source files
turbulentMixingLengthFrequencyInletFvPatchScalarField.H
turbulentMixingLengthFrequencyInletFvPatchScalarField.C
Definition at line 125 of file turbulentMixingLengthFrequencyInletFvPatchScalarField.H.
Constructor & Destructor Documentation
turbulentMixingLengthFrequencyInletFvPatchScalarField() [1/5]
turbulentMixingLengthFrequencyInletFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 36 of file turbulentMixingLengthFrequencyInletFvPatchScalarField.C.
References Foam::Zero.
turbulentMixingLengthFrequencyInletFvPatchScalarField() [2/5]
turbulentMixingLengthFrequencyInletFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 66 of file turbulentMixingLengthFrequencyInletFvPatchScalarField.C.
References dict, IOobjectOption::MUST_READ, and Foam::Zero.
turbulentMixingLengthFrequencyInletFvPatchScalarField() [3/5]
turbulentMixingLengthFrequencyInletFvPatchScalarField (const turbulentMixingLengthFrequencyInletFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 52 of file turbulentMixingLengthFrequencyInletFvPatchScalarField.C.
turbulentMixingLengthFrequencyInletFvPatchScalarField() [4/5]
turbulentMixingLengthFrequencyInletFvPatchScalarField (const turbulentMixingLengthFrequencyInletFvPatchScalarField & ptf)
Definition at line 87 of file turbulentMixingLengthFrequencyInletFvPatchScalarField.C.
turbulentMixingLengthFrequencyInletFvPatchScalarField() [5/5]
turbulentMixingLengthFrequencyInletFvPatchScalarField (const turbulentMixingLengthFrequencyInletFvPatchScalarField & ptf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 98 of file turbulentMixingLengthFrequencyInletFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("turbulentMixingLengthFrequencyInlet")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 179 of file turbulentMixingLengthFrequencyInletFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 198 of file turbulentMixingLengthFrequencyInletFvPatchScalarField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 113 of file turbulentMixingLengthFrequencyInletFvPatchScalarField.C.
References IOobject::groupName(), Foam::neg(), Foam::pow(), turbulenceModel::propertiesName, and Foam::sqrt().
write()
void write (Ostream & os) const virtual
Definition at line 148 of file turbulentMixingLengthFrequencyInletFvPatchScalarField.C.
References os(), fvPatchField< Type >::write(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/RAS/derivedFvPatchFields/turbulentMixingLengthFrequencyInlet/turbulentMixingLengthFrequencyInletFvPatchScalarField.H
src/TurbulenceModels/turbulenceModels/RAS/derivedFvPatchFields/turbulentMixingLengthFrequencyInlet/turbulentMixingLengthFrequencyInletFvPatchScalarField.C