OpenFOAM: faBoundaryMeshEntries Class Reference
faBoundaryMeshEntries Class Reference
Read and store dictionary entries for finite-area boundary patches.
#include <faBoundaryMeshEntries.H>
Public Member Functions
TypeNameNoDebug ("faBoundaryMesh")
faBoundaryMeshEntries (const IOobject &io)
bool writeData (Ostream &) const
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
regIOobject (const IOobject &io, const bool isTimeObject=false)
regIOobject (const regIOobject &rio)
regIOobject (const regIOobject &rio, bool registerCopy)
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
regIOobject (const IOobject &io, const regIOobject &rio)
virtual ~regIOobject ()
bool checkIn ()
bool checkOut ()
virtual void addWatch ()
bool registered () const noexcept
bool ownedByRegistry () const noexcept
bool store ()
void release (const bool unregister=false) noexcept
label eventNo () const noexcept
label & eventNo () noexcept
bool upToDate (const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
void setUpToDate ()
virtual void rename (const word &newName)
const dictionary * findMetaData () const noexcept
dictionary & getMetaData () noexcept
void removeMetaData ()
virtual void updateMetaData ()
virtual fileName filePath () const
bool headerOk ()
Istream & readStream (const word &, const bool readOnProc=true)
void close ()
virtual bool readData (Istream &)
virtual bool read ()
virtual label addWatch (const fileName &)
const labelList & watchIndices () const noexcept
labelList & watchIndices () noexcept
virtual bool modified () const
virtual bool readIfModified ()
virtual bool writeObject (IOstreamOption streamOpt, const bool writeOnProc) const
virtual bool write (const bool writeOnProc=true) const
virtual bool global () const
void operator= (const IOobject &io)
virtual bool writeObject (IOstreamOption::streamFormat fmt, IOstreamOption::versionNumber ver, IOstreamOption::compressionType cmp, const bool writeOnProc) const
Public Member Functions inherited from IOobject
TypeName ("IOobject")
IOobject (const IOobject &)=default
virtual ~IOobject ()=default
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const fileName &path, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const fileName &path, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const IOobject &io, const objectRegistry &registry)
IOobject (const IOobject &io, const word &name)
IOobject (const IOobject &io, const word &name, const fileName &local)
IOobject (const IOobject &io, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt)
IOobject (const IOobject &io, IOobjectOption::registerOption regOpt)
autoPtr< IOobject > clone () const
autoPtr< IOobject > clone (const objectRegistry &registry) const
const objectRegistry & db () const noexcept
const Time & time () const noexcept
const word & name () const noexcept
const word & headerClassName () const noexcept
word & headerClassName () noexcept
const string & note () const noexcept
string & note () noexcept
unsigned labelByteSize () const noexcept
unsigned scalarByteSize () const noexcept
void resetHeader (const word &newName=word::null)
bool hasHeaderClass () const noexcept
template<class Type >
bool isHeaderClass () const
template<class Type >
bool isHeaderClassName () const
word group () const
word member () const
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const noexcept
fileName & instance () noexcept
const fileName & local () const noexcept
fileName path () const
fileName path (const word &instance, const fileName &local=fileName::null) const
fileName objectPath () const
fileName objectRelPath () const
fileName localFilePath (const word &typeName, const bool search=true) const
fileName globalFilePath (const word &typeName, const bool search=true) const
IOstreamOption parseHeader (const dictionary &headerDict)
bool readHeader (Istream &is)
bool readHeader (dictionary &headerDict, Istream &is)
template<class Type >
bool typeHeaderOk (const bool checkType=true, const bool search=true, const bool verbose=true)
template<class Type >
void warnNoRereading () const
bool writeHeader (Ostream &os) const
bool writeHeader (Ostream &os, const word &objectType) const
void writeHeader (dictionary &dict, IOstreamOption streamOpt) const
void writeHeader (dictionary &dict, const word &objectType, IOstreamOption streamOpt) const
bool good () const noexcept
bool bad () const noexcept
InfoProxy< IOobject > info () const noexcept
void operator= (const IOobject &io)
template<>
bool isHeaderClass () const
template<class StringType >
Foam::word groupName (StringType base, const word &group)
Public Member Functions inherited from IOobjectOption
constexpr IOobjectOption (readOption rOpt=readOption::NO_READ, writeOption wOpt=writeOption::NO_WRITE, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (readOption rOpt, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (writeOption wOpt, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (registerOption registerObject, bool globalObject=false) noexcept
constexpr IOobjectOption (readOption rOpt, writeOption wOpt, bool registerObject, bool globalObject=false) noexcept
constexpr IOobjectOption (bool registerObject, bool globalObject=false) noexcept
readOption readOpt () const noexcept
readOption readOpt (readOption opt) noexcept
writeOption writeOpt () const noexcept
writeOption writeOpt (writeOption opt) noexcept
bool registerObject () const noexcept
bool registerObject (bool on) noexcept
bool globalObject () const noexcept
bool globalObject (bool on) noexcept
bool isAnyRead () const noexcept
bool isReadRequired () const noexcept
bool isReadOptional () const noexcept
readOption & readOpt () noexcept
writeOption & writeOpt () noexcept
bool & registerObject () noexcept
bool & globalObject () noexcept
Public Member Functions inherited from PtrList< entry >
constexpr PtrList () noexcept
PtrList (const label len)
PtrList (const PtrList< entry > &list)
PtrList (PtrList< entry > &&list)
PtrList (UList< entry * > &list)
PtrList (const PtrList< entry > &list, const CloneArg &cloneArgs)
PtrList (PtrList< entry > &list, bool reuse)
PtrList (const SLPtrList< entry > &list)
PtrList (Istream &is, const INew &inew)
PtrList (Istream &is)
~PtrList ()
PtrList< entry > clone (Args &&... args) const
Foam::PtrList< entry > clone (Args &&... args) const
const entry * set (const label i) const
autoPtr< entry > set (const label i, entry *ptr)
autoPtr< entry > set (const label i, std::unique_ptr< entry > &&ptr)
autoPtr< entry > set (const label i, autoPtr< entry > &&ptr)
autoPtr< entry > set (const label i, const refPtr< entry > &ptr)
autoPtr< entry > set (const label i, const tmp< entry > &ptr)
autoPtr< entry > set (const label i, autoPtr< entry > &ptr)
void clear ()
void free ()
void resize (const label newLen)
entry & emplace_back (Args &&... args)
void push_back (entry *ptr)
void push_back (std::unique_ptr< entry > &&ptr)
void push_back (autoPtr< entry > &&ptr)
void push_back (const refPtr< entry > &ptr)
void push_back (const tmp< entry > &ptr)
void push_back (PtrList< entry > &&other)
void push_back (autoPtr< entry > &ptr)=delete
entry & emplace_set (const label i, Args &&... args)
entry & emplace (const label i, Args &&... args)
autoPtr< entry > release (const label i)
void transfer (PtrList< entry > &list)
void operator= (const PtrList< entry > &list)
void operator= (PtrList< entry > &&list)
void setSize (const label newLen)
void append (autoPtr< entry > &ptr)
void append (entry *ptr)
void append (std::unique_ptr< entry > &&ptr)
void append (autoPtr< entry > &&ptr)
void append (const refPtr< entry > &ptr)
void append (const tmp< entry > &ptr)
void append (PtrList< entry > &&other)
Public Member Functions inherited from UPtrList< T >
constexpr UPtrList () noexcept
UPtrList (const label len)
UPtrList (const UPtrList< T > &list)
UPtrList (UPtrList< T > &&list)
UPtrList (UPtrList< T > &list, bool reuse)
UPtrList (PtrList< T > &list)
UPtrList (const UList< T * > &list)
UPtrList (UList< T > &list)
bool empty () const noexcept
label size () const noexcept
label count () const noexcept
T & front ()
const T & front () const
T & back ()
const T & back () const
const T * test (const label i) const
const T * get (const label i) const
T * get (const label i)
const T * set (const label i) const
void clear ()
void free ()
void resize (const label newLen)
label squeezeNull ()
void trimTrailingNull ()
void push_back (T *ptr)
void push_back (UPtrList< T > &&other)
void swap (UPtrList< T > &list)
void transfer (UPtrList< T > &list)
T * set (const label i, T *ptr)
void reorder (const labelUList &oldToNew, const bool check=false)
void sortOrder (const labelUList &order, const bool check=false)
void checkNonNull () const
const T & at (const label i) const
T & at (const label i)
const T & operator[] (const label i) const
T & operator[] (const label i)
FOAM_DEPRECATED_FOR (2022-09, "get(), set() or test() methods") const T *operator()(const label i) const
void operator= (const UPtrList< T > &list)
void operator= (UPtrList< T > &&list)
T ** begin_ptr () noexcept
T ** end_ptr () noexcept
iterator begin ()
iterator end () noexcept
const_iterator cbegin () const
const_iterator cend () const noexcept
const_iterator begin () const
const_iterator end () const noexcept
void setSize (const label n)
T & first ()
const T & first () const
T & last ()
const T & last () const
void append (T *ptr)
void append (UPtrList< T > &&other)
Additional Inherited Members
Public Types inherited from IOobject
enum objectState : char { GOOD , BAD }
enum fileCheckTypes : char { timeStamp , timeStampMaster , inotify , inotifyMaster }
Public Types inherited from IOobjectOption
enum readOption : unsigned char {
NO_READ = 0 , MUST_READ = 0x1 , READ_MODIFIED = 0x3 , MUST_READ_IF_MODIFIED = 0x3 ,
LAZY_READ = 0x4 , READ_IF_PRESENT = 0x4
}
enum writeOption : unsigned char { NO_WRITE = 0 , AUTO_WRITE = 0x10 }
enum registerOption : unsigned char { NO_REGISTER = 0 , REGISTER = 1 }
Public Types inherited from UPtrList< T >
typedef T value_type
typedef T & reference
typedef const T & const_reference
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *p)
template<class Type >
static Type & store (autoPtr< Type > &ptr)
template<class Type >
static Type & store (autoPtr< Type > &&ptr)
template<class Type >
static Type & store (refPtr< Type > &ptr)
template<class Type >
static Type & store (refPtr< Type > &&ptr)
template<class Type >
static Type & store (tmp< Type > &ptr)
template<class Type >
static Type & store (tmp< Type > &&ptr)
Static Public Member Functions inherited from IOobject
static bool bannerEnabled () noexcept
static bool bannerEnabled (bool on) noexcept
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
template<class StringType >
static word groupName (StringType base, const word &group)
static word group (const word &name)
static word member (const word &name)
static word scopedName (const std::string &scope, const word &name)
static IOobject selectIO (const IOobject &io, const fileName &altFile, const word &ioName="")
static Ostream & writeBanner (Ostream &os, const bool noSyntaxHint=false)
static Ostream & writeDivider (Ostream &os)
static Ostream & writeEndDivider (Ostream &os)
Static Public Member Functions inherited from IOobjectOption
static bool isAnyRead (readOption opt) noexcept
static bool isReadRequired (readOption opt) noexcept
static bool isReadOptional (readOption opt) noexcept
static readOption lazierRead (readOption opt) noexcept
Static Public Attributes inherited from IOobject
static const Enum< fileCheckTypes > fileCheckTypesNames
static char scopeSeparator
static fileCheckTypes fileModificationChecking
static float fileModificationSkew
static int maxFileModificationPolls
Protected Member Functions inherited from regIOobject
bool readHeaderOk (const IOstreamOption::streamFormat fmt, const word &typeName)
Protected Member Functions inherited from IOobject
void setBad (const string &s)
Protected Member Functions inherited from PtrList< entry >
void readIstream (Istream &is, const INew &inew)
Protected Member Functions inherited from UPtrList< T >
void setAddressableSize (const label n) noexcept
label find_next (label pos) const
UPtrList (Detail::PtrListDetail< T > &&ptrs)
Static Protected Member Functions inherited from IOobject
static void writeHeaderContent (Ostream &os, const IOobject &io, const word &objectType, const dictionary *metaDataDict=nullptr)
static void writeHeaderContent (dictionary &dict, const IOobject &io, const word &objectType, IOstreamOption streamOpt, const dictionary *metaDataDict=nullptr)
Protected Attributes inherited from UPtrList< T >
Detail::PtrListDetail< T > ptrs_
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
Detailed Description
Read and store dictionary entries for finite-area boundary patches.
Source files
faBoundaryMeshEntries.H
faBoundaryMeshEntries.C
Definition at line 48 of file faBoundaryMeshEntries.H.
Constructor & Destructor Documentation
faBoundaryMeshEntries()
faBoundaryMeshEntries (const IOobject & io) inline explicit
Definition at line 62 of file faBoundaryMeshEntries.H.
References regIOobject::headerOk(), IOobjectOption::isReadOptional(), IOobjectOption::isReadRequired(), and regIOobject::readStream().
Member Function Documentation
TypeNameNoDebug()
TypeNameNoDebug ("faBoundaryMesh")
writeData()
bool writeData (Ostream &) const inline virtual
Implements regIOobject.
Definition at line 76 of file faBoundaryMeshEntries.H.
References NotImplemented.
The documentation for this class was generated from the following file:
src/finiteArea/faMesh/faBoundaryMesh/faBoundaryMeshEntries.H