OpenFOAM: orientation Class Reference
orientation Class Reference
Orientation constraint: fixed in global space.
#include <sixDoFRigidBodyMotionOrientationConstraint.H>
Public Member Functions
TypeName ("orientation")
orientation (const word &name, const dictionary &sDoFRBMCDict, const sixDoFRigidBodyMotion &motion)
virtual autoPtr< sixDoFRigidBodyMotionConstraint > clone () const
virtual ~orientation ()
virtual void constrainTranslation (pointConstraint &) const
virtual void constrainRotation (pointConstraint &) const
virtual bool read (const dictionary &sDoFRBMCCoeff)
virtual void write (Ostream &) const
Public Member Functions inherited from sixDoFRigidBodyMotionConstraint
TypeName ("sixDoFRigidBodyMotionConstraint")
declareRunTimeSelectionTable (autoPtr, sixDoFRigidBodyMotionConstraint, dictionary,(const word &name, const dictionary &sDoFRBMCDict, const sixDoFRigidBodyMotion &motion),(name, sDoFRBMCDict, motion))
sixDoFRigidBodyMotionConstraint (const word &name, const dictionary &sDoFRBMCDict, const sixDoFRigidBodyMotion &motion)
virtual ~sixDoFRigidBodyMotionConstraint ()
const word & name () const
virtual void setCentreOfRotation (point &) const
const dictionary & coeffDict () const
const sixDoFRigidBodyMotion & motion () const noexcept
Additional Inherited Members
Static Public Member Functions inherited from sixDoFRigidBodyMotionConstraint
static autoPtr< sixDoFRigidBodyMotionConstraint > New (const word &name, const dictionary &sDoFRBMCDict, const sixDoFRigidBodyMotion &motion)
Protected Attributes inherited from sixDoFRigidBodyMotionConstraint
word name_
dictionary sDoFRBMCCoeffs_
const sixDoFRigidBodyMotion & motion_
Detailed Description
Orientation constraint: fixed in global space.
Source files
sixDoFRigidBodyMotionOrientationConstraint.H
sixDoFRigidBodyMotionOrientationConstraint.C
Definition at line 50 of file sixDoFRigidBodyMotionOrientationConstraint.H.
Constructor & Destructor Documentation
orientation()
orientation (const word & name, const dictionary & sDoFRBMCDict, const sixDoFRigidBodyMotion & motion)
Definition at line 45 of file sixDoFRigidBodyMotionOrientationConstraint.C.
References Foam::name(), and orientation::read().
~orientation()
~orientation () virtual
Definition at line 60 of file sixDoFRigidBodyMotionOrientationConstraint.C.
Member Function Documentation
TypeName()
TypeName ("orientation")
clone()
virtual autoPtr< sixDoFRigidBodyMotionConstraint > clone () const inline virtual
Implements sixDoFRigidBodyMotionConstraint.
Definition at line 72 of file sixDoFRigidBodyMotionOrientationConstraint.H.
constrainTranslation()
void constrainTranslation (pointConstraint & pc) const virtual
Implements sixDoFRigidBodyMotionConstraint.
Definition at line 66 of file sixDoFRigidBodyMotionOrientationConstraint.C.
constrainRotation()
void constrainRotation (pointConstraint & pc) const virtual
Implements sixDoFRigidBodyMotionConstraint.
Definition at line 74 of file sixDoFRigidBodyMotionOrientationConstraint.C.
References pointConstraint::combine(), and Foam::Zero.
read()
bool read (const dictionary & sDoFRBMCCoeff) virtual
Reimplemented from sixDoFRigidBodyMotionConstraint.
Definition at line 84 of file sixDoFRigidBodyMotionOrientationConstraint.C.
References sixDoFRigidBodyMotionConstraint::read().
Referenced by orientation::orientation().
write()
void write (Ostream & os) const virtual
Reimplemented from sixDoFRigidBodyMotionConstraint.
Definition at line 95 of file sixDoFRigidBodyMotionOrientationConstraint.C.
The documentation for this class was generated from the following files:
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/constraints/orientation/sixDoFRigidBodyMotionOrientationConstraint.H
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/constraints/orientation/sixDoFRigidBodyMotionOrientationConstraint.C