OpenFOAM: harmonicSpring Class Reference
harmonicSpring Class Reference
#include <harmonicSpring.H>
Public Member Functions
TypeName ("harmonicSpring")
harmonicSpring (const word &name, const dictionary &tetherPotentialProperties)
~harmonicSpring ()
scalar energy (const vector r) const
vector force (const vector r) const
bool read (const dictionary &tetherPotentialProperties)
Public Member Functions inherited from tetherPotential
TypeName ("tetherPotential")
declareRunTimeSelectionTable (autoPtr, tetherPotential, dictionary,(const word &name, const dictionary &tetherPotentialProperties),(name, tetherPotentialProperties))
tetherPotential (const word &name, const dictionary &tetherPotentialProperties)
virtual ~tetherPotential ()=default
const dictionary & tetherPotentialProperties () const
Additional Inherited Members
Static Public Member Functions inherited from tetherPotential
static autoPtr< tetherPotential > New (const word &name, const dictionary &tetherPotentialProperties)
Protected Member Functions inherited from tetherPotential
tetherPotential (const tetherPotential &)=delete
void operator= (const tetherPotential &)=delete
Protected Attributes inherited from tetherPotential
word name_
dictionary tetherPotentialProperties_
Detailed Description
Source files
harmonicSpring.H
harmonicSpring.C
Definition at line 48 of file harmonicSpring.H.
Constructor & Destructor Documentation
harmonicSpring()
harmonicSpring (const word & name, const dictionary & tetherPotentialProperties)
Definition at line 45 of file harmonicSpring.C.
~harmonicSpring()
~harmonicSpring () inline
Definition at line 76 of file harmonicSpring.H.
Member Function Documentation
TypeName()
TypeName ("harmonicSpring")
energy()
scalar energy (const vector r) const virtual
Implements tetherPotential.
Definition at line 62 of file harmonicSpring.C.
References Foam::magSqr().
force()
vector force (const vector r) const virtual
Implements tetherPotential.
Definition at line 68 of file harmonicSpring.C.
read()
bool read (const dictionary & tetherPotentialProperties) virtual
Implements tetherPotential.
Definition at line 74 of file harmonicSpring.C.
References tetherPotential::read(), dictionary::readEntry(), and tetherPotential::tetherPotentialProperties().
The documentation for this class was generated from the following files:
src/lagrangian/molecularDynamics/potential/tetherPotential/derived/harmonicSpring/harmonicSpring.H
src/lagrangian/molecularDynamics/potential/tetherPotential/derived/harmonicSpring/harmonicSpring.C