OpenFOAM: UILList< LListBase, T >::reverse_iterator Class Reference
UILList< LListBase, T >::reverse_iterator Class Reference
#include <UILList.H>
Public Member Functions
reverse_iterator (base_iterator iter)
pointer get () const
reference operator* () const
pointer operator-> () const
reference operator() () const
reverse_iterator & operator++ ()
Detailed Description
template<class LListBase, class T>
class Foam::UILList< LListBase, T >::reverse_iterator
Definition at line 287 of file UILList.H.
Constructor & Destructor Documentation
reverse_iterator()
template<class LListBase , class T > reverse_iterator (base_iterator iter) inline
Definition at line 293 of file UILList.H.
Member Function Documentation
get()
template<class LListBase , class T > pointer get () const inline
Definition at line 299 of file UILList.H.
References T.
Referenced by UILList< LListBase, T >::reverse_iterator::operator*(), and UILList< LListBase, T >::reverse_iterator::operator->().
operator*()
template<class LListBase , class T > reference operator* () const inline
Definition at line 304 of file UILList.H.
References UILList< LListBase, T >::reverse_iterator::get().
Referenced by UILList< LListBase, T >::reverse_iterator::operator()().
operator->()
template<class LListBase , class T > pointer operator-> () const inline
Definition at line 309 of file UILList.H.
References UILList< LListBase, T >::reverse_iterator::get().
operator()()
template<class LListBase , class T > reference operator() () const inline
Definition at line 314 of file UILList.H.
References UILList< LListBase, T >::reverse_iterator::operator*().
operator++()
template<class LListBase , class T > reverse_iterator & operator++ () inline
Definition at line 319 of file UILList.H.
The documentation for this class was generated from the following file:
src/OpenFOAM/containers/LinkedLists/accessTypes/UILList/UILList.H