OpenFOAM: pointNoise Class Reference
pointNoise Class Reference
Perform noise analysis on point-based pressure data.
#include <pointNoise.H>
Public Member Functions
TypeName ("pointNoise")
pointNoise (const dictionary &dict, const objectRegistry &obr, const word &name=typeName, const bool readFields=true)
virtual ~pointNoise ()=default
virtual bool read (const dictionary &dict)
virtual void calculate ()
Public Member Functions inherited from noiseModel
TypeName ("noiseModel")
declareRunTimeSelectionTable (autoPtr, noiseModel, dictionary,(const dictionary &dict, const objectRegistry &obr),(dict, obr))
noiseModel (const noiseModel &)=delete
void operator= (const noiseModel &)=delete
noiseModel (const dictionary &dict, const objectRegistry &obr, const word &name, const bool readFields=true)
virtual ~noiseModel ()=default
tmp< Foam::scalarField > PSD (const scalarField &PSDf) const
tmp< scalarField > SPL (const scalarField &Prms2, const scalar f) const
tmp< scalarField > SPL (const scalarField &Prms2, const scalarField &f) const
void cleanFFTW ()
void writeWeightings () const
Public Member Functions inherited from writeFile
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name="undefined", const bool writeToFile=true)
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name, const dictionary &dict, const bool writeToFile=true)
writeFile (const writeFile &wf)
virtual ~writeFile ()=default
virtual OFstream & file ()
virtual bool writeToFile () const
virtual bool canWriteToFile () const
virtual bool canResetFile () const
virtual bool canWriteHeader () const
virtual label charWidth () const
virtual void writeCommented (Ostream &os, const string &str) const
virtual void writeTabbed (Ostream &os, const string &str) const
virtual void writeHeader (Ostream &os, const string &str) const
virtual void writeCurrentTime (Ostream &os) const
virtual void writeBreak (Ostream &os) const
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
template<class Type >
void writeValue (Ostream &os, const Type &val) const
Protected Member Functions
void filterTimeData (const scalarField &t0, const scalarField &p0, scalarField &t, scalarField &p) const
void processData (const label dataseti, const Function1Types::CSV< scalar > &data)
Protected Member Functions inherited from noiseModel
scalar checkUniformTimeStep (const scalarList &times) const
bool validateBounds (const scalarList &p) const
fileName baseFileDir (const label dataseti) const
void writeFileHeader (Ostream &os, const string &x, const string &y, const UList< Tuple2< string, token > > &headerValues=UList< Tuple2< string, token > >::null()) const
void writeFreqDataToFile (Ostream &os, const scalarField &f, const scalarField &fx) const
tmp< scalarField > uniformFrequencies (const scalar deltaT, const bool check) const
tmp< scalarField > octaves (const scalarField &data, const scalarField &f, const labelUList &freqBandIDs) const
tmp< scalarField > Pf (const scalarField &p) const
tmp< scalarField > meanPf (const scalarField &p) const
tmp< scalarField > RMSmeanPf (const scalarField &p) const
tmp< scalarField > PSDf (const scalarField &p, const scalar deltaT) const
scalar RAf (const scalar f) const
scalar gainA (const scalar f) const
scalar RBf (const scalar f) const
scalar gainB (const scalar f) const
scalar RCf (const scalar f) const
scalar gainC (const scalar f) const
scalar RDf (const scalar f) const
scalar gainD (const scalar f) const
Protected Member Functions inherited from writeFile
void initStream (Ostream &os) const
fileName baseFileDir () const
fileName baseTimeDir () const
fileName filePath (const fileName &fName) const
virtual autoPtr< OFstream > newFile (const fileName &fName) const
virtual autoPtr< OFstream > newFileAtTime (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > newFileAtStartTime (const word &name) const
virtual void resetFile (const word &name)
Omanip< int > valueWidth (const label offset=0) const
void operator= (const writeFile &)=delete
virtual autoPtr< OFstream > createFile (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > createFile (const word &name) const
Protected Attributes
List< fileName > inputFileNames_
Protected Attributes inherited from noiseModel
const dictionary dict_
scalar rhoRef_
label nSamples_
scalar fLower_
scalar fUpper_
scalar startTime_
autoPtr< windowModel > windowModelPtr_
weightingType SPLweighting_
scalar dBRef_
scalar minPressure_
scalar maxPressure_
fileName outputPrefix_
bool writePrmsf_
bool writeSPL_
bool writePSD_
bool writePSDf_
bool writeOctaves_
planInfo planInfo_
Protected Attributes inherited from writeFile
const objectRegistry & fileObr_
const fileName prefix_
word fileName_
autoPtr< OFstream > filePtr_
label writePrecision_
bool writeToFile_
bool updateHeader_
bool writtenHeader_
bool useUserTime_
scalar startTime_
Additional Inherited Members
Public Types inherited from noiseModel
enum class weightingType {
none , dBA , dBB , dBC ,
dBD
}
Static Public Member Functions inherited from noiseModel
static autoPtr< noiseModel > New (const dictionary &dict, const objectRegistry &obr)
Static Public Attributes inherited from noiseModel
static const Enum< weightingType > weightingTypeNames_
Static Public Attributes inherited from writeFile
static label addChars = 8
Static Protected Member Functions inherited from noiseModel
static label findStartTimeIndex (const instantList &allTimes, const scalar startTime)
static void setOctaveBands (const scalarField &f, const scalar fLower, const scalar fUpper, const scalar octave, labelList &fBandIDs, scalarField &fCentre)
Detailed Description
Perform noise analysis on point-based pressure data.
Input data is read from a dictionary, e.g.
// Pressure reference
pRef            0;
// Number of samples in sampling window, default = 2^16 (=65536)
N               4096;
// Lower frequency bounds
fl              25;
// Upper frequency bounds
fu              25;
// Start time
startTime       0;
windowModel     <modelType>
<modelType>Coeffs
{
    ...
}
// Pressure data supplied in CSV file format
file            "pressureData";
//files           ("pressureData1" "pressureData2");
nHeaderLine     1;
refColumn       0;
componentColumns (1);
separator       " ";
mergeSeparators yes;
Source files
pointNoise.H
pointNoise.C
See also
noiseModel.H windowModel.H
Definition at line 88 of file pointNoise.H.
Constructor & Destructor Documentation
pointNoise()
pointNoise (const dictionary & dict, const objectRegistry & obr, const word & name = typeName, const bool readFields = true)
Definition at line 214 of file pointNoise.C.
References dict, pointNoise::read(), and Foam::readFields().
~pointNoise()
virtual ~pointNoise () virtual default
Member Function Documentation
filterTimeData()
void filterTimeData (const scalarField & t0, const scalarField & p0, scalarField & t, scalarField & p) const protected
Definition at line 39 of file pointNoise.C.
References PtrList< T >::append(), forAll, p, p0, UPtrList< T >::size(), noiseModel::startTime_, List< T >::transfer(), and PtrList< T >::transfer().
Referenced by pointNoise::processData().
processData()
void processData (const label dataseti, const Function1Types::CSV< scalar > & data) protected
Definition at line 64 of file pointNoise.C.
References Foam::average(), writeFile::baseFileDir(), noiseModel::checkUniformTimeStep(), Foam::endl(), f(), writeFile::fileObr_, filePtr, pointNoise::filterTimeData(), noiseModel::fLower_, noiseModel::fUpper_, Foam::Info, UPstream::master(), writeFile::newFile(), Foam::nl, noiseModel::octaves(), os(), p, noiseModel::PSD(), noiseModel::PSDf(), noiseModel::rhoRef_, noiseModel::RMSmeanPf(), noiseModel::setOctaveBands(), UList< T >::size(), noiseModel::SPL(), noiseModel::SPLweighting_, noiseModel::uniformFrequencies(), noiseModel::validateBounds(), WarningInFunction, noiseModel::weightingTypeNames_, noiseModel::windowModelPtr_, noiseModel::writeFileHeader(), noiseModel::writeFreqDataToFile(), noiseModel::writeOctaves_, noiseModel::writePrmsf_, noiseModel::writePSD_, noiseModel::writePSDf_, and noiseModel::writeSPL_.
Referenced by pointNoise::calculate().
TypeName()
TypeName ("pointNoise")
read()
bool read (const dictionary & dict) virtual
Reimplemented from noiseModel.
Definition at line 257 of file pointNoise.C.
References dict, UList< T >::first(), pointNoise::inputFileNames_, noiseModel::read(), and List< T >::resize().
Referenced by pointNoise::pointNoise().
calculate()
void calculate () virtual
Implements noiseModel.
Definition at line 233 of file pointNoise.C.
References noiseModel::dict_, argList::envGlobalPath(), string::expand(), forAll, pointNoise::inputFileNames_, fileName::isAbsolute(), UPstream::master(), and pointNoise::processData().
Member Data Documentation
inputFileNames_
List<fileName> inputFileNames_ protected
Definition at line 98 of file pointNoise.H.
Referenced by pointNoise::calculate(), and pointNoise::read().
The documentation for this class was generated from the following files:
src/randomProcesses/noise/noiseModels/pointNoise/pointNoise.H
src/randomProcesses/noise/noiseModels/pointNoise/pointNoise.C