OpenFOAM: patchFaceOrientation Class Reference
patchFaceOrientation Class Reference
Transport of orientation for use in PatchEdgeFaceWave.
#include <patchFaceOrientation.H>
Public Member Functions
patchFaceOrientation ()
patchFaceOrientation (const label)
label flipStatus () const
void flip ()
template<class TrackingData >
bool valid (TrackingData &td) const
template<class TrackingData >
void transform (const polyMesh &mesh, const indirectPrimitivePatch &patch, const tensor &rotTensor, const scalar tol, TrackingData &td)
template<class TrackingData >
bool updateEdge (const polyMesh &mesh, const indirectPrimitivePatch &patch, const label edgeI, const label facei, const patchFaceOrientation &faceInfo, const scalar tol, TrackingData &td)
template<class TrackingData >
bool updateEdge (const polyMesh &mesh, const indirectPrimitivePatch &patch, const patchFaceOrientation &edgeInfo, const bool sameOrientation, const scalar tol, TrackingData &td)
template<class TrackingData >
bool updateFace (const polyMesh &mesh, const indirectPrimitivePatch &patch, const label facei, const label edgeI, const patchFaceOrientation &edgeInfo, const scalar tol, TrackingData &td)
template<class TrackingData >
bool equal (const patchFaceOrientation &, TrackingData &) const
bool operator== (const patchFaceOrientation &) const
bool operator!= (const patchFaceOrientation &) const
Friends
Ostream & operator<< (Ostream &, const patchFaceOrientation &)
Istream & operator>> (Istream &, patchFaceOrientation &)
Detailed Description
Transport of orientation for use in PatchEdgeFaceWave.
Source files
patchFaceOrientation.H
patchFaceOrientationI.H
patchFaceOrientation.C
Definition at line 56 of file patchFaceOrientation.H.
Constructor & Destructor Documentation
patchFaceOrientation() [1/2]
patchFaceOrientation () inline
Definition at line 28 of file patchFaceOrientationI.H.
patchFaceOrientation() [2/2]
patchFaceOrientation (const label flipStatus) inline
Definition at line 34 of file patchFaceOrientationI.H.
Member Function Documentation
flipStatus()
label flipStatus () const inline
Definition at line 79 of file patchFaceOrientation.H.
flip()
void flip () inline
Definition at line 45 of file patchFaceOrientationI.H.
References orientedSurface::FLIP, and orientedSurface::NOFLIP.
valid()
template<class TrackingData > bool valid (TrackingData & td) const inline
Definition at line 59 of file patchFaceOrientationI.H.
References orientedSurface::UNVISITED.
transform()
template<class TrackingData > void transform (const polyMesh & mesh, const indirectPrimitivePatch & patch, const tensor & rotTensor, const scalar tol, TrackingData & td) inline
Definition at line 66 of file patchFaceOrientationI.H.
updateEdge() [1/2]
template<class TrackingData > bool updateEdge (const polyMesh & mesh, const indirectPrimitivePatch & patch, const label edgeI, const label facei, const patchFaceOrientation & faceInfo, const scalar tol, TrackingData & td) inline
Definition at line 78 of file patchFaceOrientationI.H.
References e, and f().
updateEdge() [2/2]
template<class TrackingData > bool updateEdge (const polyMesh & mesh, const indirectPrimitivePatch & patch, const patchFaceOrientation & edgeInfo, const bool sameOrientation, const scalar tol, TrackingData & td) inline
Definition at line 116 of file patchFaceOrientationI.H.
updateFace()
template<class TrackingData > bool updateFace (const polyMesh & mesh, const indirectPrimitivePatch & patch, const label facei, const label edgeI, const patchFaceOrientation & edgeInfo, const scalar tol, TrackingData & td) inline
Definition at line 145 of file patchFaceOrientationI.H.
References e, and f().
equal()
template<class TrackingData > bool equal (const patchFaceOrientation & rhs, TrackingData & td) const inline
Definition at line 187 of file patchFaceOrientationI.H.
References Foam::operator==().
operator==()
bool operator== (const patchFaceOrientation & rhs) const inline
Definition at line 199 of file patchFaceOrientationI.H.
operator!=()
bool operator!= (const patchFaceOrientation & rhs) const inline
Definition at line 208 of file patchFaceOrientationI.H.
Friends And Related Symbol Documentation
operator<<
Ostream & operator<< (Ostream & , const patchFaceOrientation &) friend
operator>>
Istream & operator>> (Istream & , patchFaceOrientation &) friend
The documentation for this class was generated from the following files:
src/mesh/snappyHexMesh/meshRefinement/patchFaceOrientation.H
src/mesh/snappyHexMesh/meshRefinement/patchFaceOrientationI.H