OpenFOAM: fvMeshPrimitiveLduAddressing Class Reference
fvMeshPrimitiveLduAddressing Class Reference
Variant of fvMeshLduAddressing that contains addressing instead of slices.
#include <fvMeshPrimitiveLduAddressing.H>
Public Member Functions
fvMeshPrimitiveLduAddressing (const fvMesh &mesh)
fvMeshPrimitiveLduAddressing (const label nCells, labelList &&lowerAddr, labelList &&upperAddr, const UPtrList< const labelUList > &patchAddr, const lduSchedule &ps)
virtual ~fvMeshPrimitiveLduAddressing ()=default
virtual const labelUList & lowerAddr () const noexcept
virtual const labelUList & upperAddr () const noexcept
virtual const labelUList & patchAddr (const label patchi) const
virtual const lduSchedule & patchSchedule () const noexcept
Public Member Functions inherited from lduAddressing
lduAddressing (const label nEqns)
virtual ~lduAddressing ()
label size () const
void clearOut ()
const labelUList & losortAddr () const
const labelUList & ownerStartAddr () const
const labelUList & losortStartAddr () const
label triIndex (const label a, const label b) const
Tuple2< label, scalar > band () const
Static Public Member Functions
static labelList addAddressing (const lduAddressing &addr, const labelListList &nbrCells, label &nExtraFaces, labelList &lower, labelList &upper, labelListList &nbrCellFaces, const globalIndex &, const labelList &globalCellIDs, labelListList &localFaceCells, labelListList &remoteFaceCells)
static label triIndex (const lduAddressing &, const label, const label)
Detailed Description
Variant of fvMeshLduAddressing that contains addressing instead of slices.
Alternatively use lduPrimitiveMesh but that assumes there are only lduInterfaces and not also generic patches.
Source files
fvMeshPrimitiveLduAddressing.H
fvMeshPrimitiveLduAddressing.C
Definition at line 53 of file fvMeshPrimitiveLduAddressing.H.
Constructor & Destructor Documentation
fvMeshPrimitiveLduAddressing() [1/2]
fvMeshPrimitiveLduAddressing (const fvMesh & mesh) explicit
Definition at line 28 of file fvMeshPrimitiveLduAddressing.C.
fvMeshPrimitiveLduAddressing() [2/2]
fvMeshPrimitiveLduAddressing (const label nCells, labelList && lowerAddr, labelList && upperAddr, const UPtrList< const labelUList > & patchAddr, const lduSchedule & ps)
Definition at line 48 of file fvMeshPrimitiveLduAddressing.C.
~fvMeshPrimitiveLduAddressing()
virtual ~fvMeshPrimitiveLduAddressing () virtual default
Member Function Documentation
lowerAddr()
virtual const labelUList & lowerAddr () const inline virtual noexcept
Implements lduAddressing.
Definition at line 109 of file fvMeshPrimitiveLduAddressing.H.
upperAddr()
virtual const labelUList & upperAddr () const inline virtual noexcept
Implements lduAddressing.
Definition at line 115 of file fvMeshPrimitiveLduAddressing.H.
patchAddr()
virtual const labelUList & patchAddr (const label patchi) const inline virtual
Implements lduAddressing.
Definition at line 121 of file fvMeshPrimitiveLduAddressing.H.
patchSchedule()
virtual const lduSchedule & patchSchedule () const inline virtual noexcept
Implements lduAddressing.
Definition at line 127 of file fvMeshPrimitiveLduAddressing.H.
addAddressing()
Foam::labelList addAddressing (const lduAddressing & addr, const labelListList & nbrCells, label & nExtraFaces, labelList & lower, labelList & upper, labelListList & nbrCellFaces, const globalIndex & globalNumbering, const labelList & globalCellIDs, labelListList & localFaceCells, labelListList & remoteFaceCells) static
Definition at line 93 of file fvMeshPrimitiveLduAddressing.C.
References forAll, Foam::inplaceRenumber(), Foam::inplaceReorder(), Foam::max(), Foam::min(), UPstream::nProcs(), List< T >::setSize(), PtrList< T >::setSize(), UPtrList< T >::size(), UList< T >::size(), globalIndex::toLocal(), lduPrimitiveMesh::upperTriOrder(), globalIndex::whichProcID(), and Foam::Zero.
Referenced by oversetFvMeshBase::updateAddressing().
triIndex()
Foam::label triIndex (const lduAddressing & addr, const label a, const label b) static
Definition at line 67 of file fvMeshPrimitiveLduAddressing.C.
References b, Foam::max(), and Foam::min().
The documentation for this class was generated from the following files:
src/overset/fvMeshPrimitiveLduAddressing/fvMeshPrimitiveLduAddressing.H
src/overset/fvMeshPrimitiveLduAddressing/fvMeshPrimitiveLduAddressing.C