OpenFOAM: CloudSubModelBase< CloudType > Class Template Reference
CloudSubModelBase< CloudType > Class Template Reference
Base class for cloud sub-models.
#include <CloudSubModelBase.H>
Inherits subModelBase.
Inherited by AtomizationModel< Foam::SprayCloud< Foam::DSMCCloud > >, BreakupModel< Foam::SprayCloud< Foam::DSMCCloud > >, CloudFunctionObject< KinematicCloud< Foam::DSMCCloud > >, CloudFunctionObject< KinematicCloud< CloudType > >, CloudFunctionObject< KinematicCloud< Cloud< basicKinematicCollidingParcel > > >, CollisionModel< Foam::CollidingCloud< Foam::DSMCCloud > >, CompositionModel< Foam::ReactingCloud< Foam::DSMCCloud > >, DampingModel< Foam::KinematicCloud< Foam::DSMCCloud > >, DampingModel< Foam::MPPICCloud< Foam::DSMCCloud > >, DevolatilisationModel< Foam::ReactingMultiphaseCloud< Foam::DSMCCloud > >, DispersionModel< Foam::KinematicCloud< Foam::DSMCCloud > >, HeatTransferModel< Foam::ThermoCloud< Foam::DSMCCloud > >, HeterogeneousReactingModel< Foam::ReactingHeterogeneousCloud< Foam::DSMCCloud > >, InjectionModel< Foam::KinematicCloud< Foam::DSMCCloud > >, IsotropyModel< Foam::KinematicCloud< Foam::DSMCCloud > >, IsotropyModel< Foam::MPPICCloud< Foam::DSMCCloud > >, PackingModel< Foam::KinematicCloud< Foam::DSMCCloud > >, PackingModel< Foam::MPPICCloud< Foam::DSMCCloud > >, PatchInteractionModel< Foam::KinematicCloud< Foam::DSMCCloud > >, PatchInteractionModel< Foam::DSMCCloud >, PhaseChangeModel< Foam::ReactingCloud< Foam::DSMCCloud > >, StochasticCollisionModel< Foam::KinematicCloud< Foam::DSMCCloud > >, SurfaceFilmModel< Foam::KinematicCloud< Foam::DSMCCloud > >, SurfaceReactionModel< Foam::ReactingMultiphaseCloud< Foam::DSMCCloud > >, AtomizationModel< CloudType >, BreakupModel< CloudType >, CloudFunctionObject< CloudType >, CollisionModel< CloudType >, CompositionModel< CloudType >, DampingModel< CloudType >, DevolatilisationModel< CloudType >, DispersionModel< CloudType >, HeatTransferModel< CloudType >, HeterogeneousReactingModel< CloudType >, InjectionModel< CloudType >, IsotropyModel< CloudType >, PackingModel< CloudType >, PatchInteractionModel< CloudType >, PhaseChangeModel< CloudType >, StochasticCollisionModel< CloudType >, SurfaceFilmModel< CloudType >, and SurfaceReactionModel< CloudType >.
Public Types
typedef CloudType cloudType
Public Member Functions
CloudSubModelBase (CloudType &owner)
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
virtual ~CloudSubModelBase ()=default
const CloudType & owner () const
virtual bool writeTime () const
virtual fileName localPath () const
CloudType & owner ()
virtual void info ()
virtual void write (Ostream &os) const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
subModelBase (const subModelBase &smb)
virtual ~subModelBase ()=default
const word & modelName () const
const dictionary & dict () const
const word & baseName () const
const word & modelType () const
const dictionary & coeffDict () const
const dictionary & properties () const
virtual bool defaultCoeffs (const bool printMsg) const
virtual bool active () const
virtual void cacheFields (const bool store)
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
bool getModelDict (const word &entryName, dictionary &dict) const
template<class Type >
bool getModelProperty (const word &entryName, Type &value) const
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Protected Attributes
CloudType & owner_
Protected Attributes inherited from subModelBase
const word modelName_
dictionary & properties_
const dictionary dict_
const word baseName_
const word modelType_
const dictionary coeffDict_
Additional Inherited Members
Public Attributes inherited from subModelBase
bool log
Protected Member Functions inherited from subModelBase
bool inLine () const
Detailed Description
template<class CloudType>
class Foam::CloudSubModelBase< CloudType >
Base class for cloud sub-models.
Source files
CloudSubModelBase.H
CloudSubModelBase.C
Definition at line 47 of file CloudSubModelBase.H.
Member Typedef Documentation
cloudType
template<class CloudType > typedef CloudType cloudType
Definition at line 94 of file CloudSubModelBase.H.
Constructor & Destructor Documentation
CloudSubModelBase() [1/4]
template<class CloudType > CloudSubModelBase (CloudType & owner)
Definition at line 28 of file CloudSubModelBase.C.
References subModelBase::log, and CloudSubModelBase< CloudType >::owner_.
CloudSubModelBase() [2/4]
template<class CloudType > CloudSubModelBase (CloudType & owner, const dictionary & dict, const word & baseName, const word & modelType, const word & dictExt = "Coeffs")
Definition at line 38 of file CloudSubModelBase.C.
References subModelBase::log, and CloudSubModelBase< CloudType >::owner_.
CloudSubModelBase() [3/4]
template<class CloudType > CloudSubModelBase (const word & modelName, CloudType & owner, const dictionary & dict, const word & baseName, const word & modelType)
Definition at line 62 of file CloudSubModelBase.C.
CloudSubModelBase() [4/4]
template<class CloudType > CloudSubModelBase (const CloudSubModelBase< CloudType > & smb)
Definition at line 86 of file CloudSubModelBase.C.
~CloudSubModelBase()
template<class CloudType > virtual ~CloudSubModelBase () virtual default
Member Function Documentation
owner() [1/2]
template<class CloudType > const CloudType & owner () const
Definition at line 101 of file CloudSubModelBase.C.
Referenced by CloudFunctionObject< CloudType >::CloudFunctionObject(), ConeInjection< CloudType >::ConeInjection(), ConeNozzleInjection< CloudType >::ConeNozzleInjection(), ConstantRateDevolatilisation< CloudType >::ConstantRateDevolatilisation(), COxidationDiffusionLimitedRate< CloudType >::COxidationDiffusionLimitedRate(), COxidationHurtMitchell< CloudType >::COxidationHurtMitchell(), COxidationIntrinsicRate< CloudType >::COxidationIntrinsicRate(), COxidationKineticDiffusionLimitedRate< CloudType >::COxidationKineticDiffusionLimitedRate(), COxidationMurphyShaddix< CloudType >::COxidationMurphyShaddix(), FaceInteraction< CloudType >::FaceInteraction(), FacePostProcessing< CloudType >::FacePostProcessing(), Implicit< CloudType >::Implicit(), InflationInjection< CloudType >::InflationInjection(), InjectedParticleDistributionInjection< CloudType >::InjectedParticleDistributionInjection(), InjectedParticleInjection< CloudType >::InjectedParticleInjection(), KinematicLookupTableInjection< CloudType >::KinematicLookupTableInjection(), LiquidEvapFuchsKnudsen< CloudType >::LiquidEvapFuchsKnudsen(), LiquidEvaporation< CloudType >::LiquidEvaporation(), LiquidEvaporationBoil< CloudType >::LiquidEvaporationBoil(), LocalInteraction< CloudType >::LocalInteraction(), MUCSheterogeneousRate< CloudType >::MUCSheterogeneousRate(), ParticleErosion< CloudType >::ParticleErosion(), ParticleZoneInfo< CloudType >::ParticleZoneInfo(), PatchCollisionDensity< CloudType >::PatchCollisionDensity(), PatchFlowRateInjection< CloudType >::PatchFlowRateInjection(), PatchInjection< CloudType >::PatchInjection(), ReactingLookupTableInjection< CloudType >::ReactingLookupTableInjection(), ReactingMultiphaseLookupTableInjection< CloudType >::ReactingMultiphaseLookupTableInjection(), RemoveParcels< CloudType >::RemoveParcels(), SingleKineticRateDevolatilisation< CloudType >::SingleKineticRateDevolatilisation(), and ThermoLookupTableInjection< CloudType >::ThermoLookupTableInjection().
writeTime()
template<class CloudType > bool writeTime () const virtual
Reimplemented from subModelBase.
Definition at line 115 of file CloudSubModelBase.C.
localPath()
template<class CloudType > Foam::fileName localPath () const virtual
Reimplemented from subModelBase.
Definition at line 125 of file CloudSubModelBase.C.
References word::null, and cloud::prefix.
Referenced by CloudFunctionObject< CloudType >::CloudFunctionObject().
owner() [2/2]
template<class CloudType > CloudType & owner ()
Definition at line 108 of file CloudSubModelBase.C.
info()
template<class CloudType > void info () virtual
Reimplemented in HeterogeneousReactingModel< CloudType >, HeterogeneousReactingModel< Foam::ReactingHeterogeneousCloud< Foam::DSMCCloud > >, InjectedParticleDistributionInjection< CloudType >, InjectedParticleInjection< CloudType >, InjectionModel< CloudType >, InjectionModel< Foam::KinematicCloud< Foam::DSMCCloud > >, LocalInteraction< CloudType >, MultiInteraction< CloudType >, PatchInteractionModel< CloudType >, PatchInteractionModel< Foam::DSMCCloud >, PatchInteractionModel< Foam::KinematicCloud< Foam::DSMCCloud > >, RecycleInteraction< CloudType >, StandardWallInteraction< CloudType >, KinematicSurfaceFilm< CloudType >, SurfaceFilmModel< CloudType >, SurfaceFilmModel< Foam::KinematicCloud< Foam::DSMCCloud > >, PhaseChangeModel< CloudType >, PhaseChangeModel< Foam::ReactingCloud< Foam::DSMCCloud > >, DevolatilisationModel< CloudType >, DevolatilisationModel< Foam::ReactingMultiphaseCloud< Foam::DSMCCloud > >, SurfaceReactionModel< CloudType >, SurfaceReactionModel< Foam::ReactingMultiphaseCloud< Foam::DSMCCloud > >, and ThermoSurfaceFilm< CloudType >.
Definition at line 137 of file CloudSubModelBase.C.
References Foam::log().
Referenced by HeterogeneousReactingModel< CloudType >::info(), InjectionModel< CloudType >::info(), PatchInteractionModel< CloudType >::info(), SurfaceFilmModel< CloudType >::info(), PhaseChangeModel< CloudType >::info(), DevolatilisationModel< CloudType >::info(), and SurfaceReactionModel< CloudType >::info().
write()
template<class CloudType > void write (Ostream & os) const virtual
Reimplemented from subModelBase.
Reimplemented in DispersionRASModel< CloudType >.
Definition at line 144 of file CloudSubModelBase.C.
References os(), subModelBase::write(), and Ostream::writeEntry().
Referenced by DispersionRASModel< CloudType >::write().
Member Data Documentation
owner_
template<class CloudType > CloudType& owner_ protected
Definition at line 56 of file CloudSubModelBase.H.
Referenced by CloudSubModelBase< CloudType >::CloudSubModelBase(), and CloudSubModelBase< CloudType >::CloudSubModelBase().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/CloudSubModelBase.H
src/lagrangian/intermediate/submodels/CloudSubModelBase.C