OpenFOAM: SpalartAllmaras Class Reference
SpalartAllmaras Class Reference
#include <SpalartAllmaras.H>
Public Member Functions
TypeName ("SpalartAllmaras")
SpalartAllmaras (const fvMesh &mesh, const solverControl &SolverControl)
virtual ~SpalartAllmaras ()=default
virtual bool hasTMVar1 () const
virtual bool hasTMVar2 () const
virtual bool hasNut () const
virtual tmp< volScalarField > nutJacobianVar1 (const singlePhaseTransportModel &laminarTransport) const
Public Member Functions inherited from RASModelVariables
TypeName ("RASModelVariables")
declareRunTimeSelectionTable (autoPtr, RASModelVariables, dictionary,(const fvMesh &mesh, const solverControl &SolverControl),(mesh, SolverControl))
RASModelVariables (const fvMesh &mesh, const solverControl &SolverControl)
RASModelVariables (const RASModelVariables &rmv)
autoPtr< RASModelVariables > clone () const
virtual ~RASModelVariables ()=default
const word & TMVar1BaseName () const
const word & TMVar2BaseName () const
const word & nutBaseName () const
bool hasDist () const
const volScalarField & TMVar1 () const
volScalarField & TMVar1 ()
const volScalarField & TMVar2 () const
volScalarField & TMVar2 ()
const volScalarField & nutRef () const
volScalarField & nutRef ()
const volScalarField & d () const
volScalarField & d ()
const volScalarField & TMVar1Inst () const
volScalarField & TMVar1Inst ()
const volScalarField & TMVar2Inst () const
volScalarField & TMVar2Inst ()
const volScalarField & nutRefInst () const
volScalarField & nutRefInst ()
virtual tmp< volScalarField > nutJacobianVar2 (const singlePhaseTransportModel &laminarTransport) const
virtual tmp< volScalarField::Internal > G ()
void restoreInitValues ()
void resetMeanFields ()
virtual void computeMeanFields ()
tmp< volSymmTensorField > devReff (const singlePhaseTransportModel &laminarTransport, const volVectorField &U) const
virtual void correctBoundaryConditions (const incompressible::turbulenceModel &turbulence)
virtual void transfer (RASModelVariables &rmv)
Additional Inherited Members
Static Public Member Functions inherited from RASModelVariables
static autoPtr< RASModelVariables > New (const fvMesh &mesh, const solverControl &SolverControl)
Protected Member Functions inherited from RASModelVariables
virtual void allocateInitValues ()
virtual void allocateMeanFields ()
refPtr< volScalarField > cloneRefPtr (const refPtr< volScalarField > &obj) const
void copyAndRename (volScalarField &f1, volScalarField &f2)
void operator= (const RASModelVariables &)=delete
Protected Attributes inherited from RASModelVariables
const fvMesh & mesh_
const solverControl & solverControl_
word TMVar1BaseName_
word TMVar2BaseName_
word nutBaseName_
refPtr< volScalarField > TMVar1Ptr_
refPtr< volScalarField > TMVar2Ptr_
refPtr< volScalarField > nutPtr_
refPtr< volScalarField > distPtr_
refPtr< volScalarField > TMVar1InitPtr_
refPtr< volScalarField > TMVar2InitPtr_
refPtr< volScalarField > nutInitPtr_
refPtr< volScalarField > TMVar1MeanPtr_
refPtr< volScalarField > TMVar2MeanPtr_
refPtr< volScalarField > nutMeanPtr_
Detailed Description
Source files
SpalartAllmaras.H
SpalartAllmaras.C
Definition at line 52 of file SpalartAllmaras.H.
Constructor & Destructor Documentation
SpalartAllmaras()
SpalartAllmaras (const fvMesh & mesh, const solverControl & SolverControl)
Definition at line 43 of file SpalartAllmaras.C.
References RASModelVariables::allocateInitValues(), RASModelVariables::allocateMeanFields(), Foam::dimless, RASModelVariables::distPtr_, mesh, RASModelVariables::mesh_, MeshObject< fvMesh, UpdateableMeshObject, wallDist >::New(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, RASModelVariables::nutBaseName_, RASModelVariables::nutPtr_, RASModelVariables::TMVar1BaseName_, RASModelVariables::TMVar1Ptr_, RASModelVariables::TMVar2Ptr_, y, and Foam::Zero.
~SpalartAllmaras()
virtual ~SpalartAllmaras () virtual default
Member Function Documentation
TypeName()
TypeName ("SpalartAllmaras")
hasTMVar1()
virtual bool hasTMVar1 () const inline virtual
Reimplemented from RASModelVariables.
Definition at line 80 of file SpalartAllmaras.H.
hasTMVar2()
virtual bool hasTMVar2 () const inline virtual
Reimplemented from RASModelVariables.
Definition at line 84 of file SpalartAllmaras.H.
hasNut()
virtual bool hasNut () const inline virtual
Reimplemented from RASModelVariables.
Definition at line 88 of file SpalartAllmaras.H.
nutJacobianVar1()
tmp< volScalarField > nutJacobianVar1 (const singlePhaseTransportModel & laminarTransport) const virtual
Reimplemented from RASModelVariables.
Definition at line 89 of file SpalartAllmaras.C.
References Foam::dimless, laminarTransport(), RASModelVariables::mesh_, tmp< T >::New(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, nu, Foam::pow3(), Foam::sqr(), RASModelVariables::TMVar1(), and Foam::Zero.
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/turbulenceModels/turbulenceModelVariables/RAS/SpalartAllmaras/SpalartAllmaras.H
src/optimisation/adjointOptimisation/adjoint/turbulenceModels/turbulenceModelVariables/RAS/SpalartAllmaras/SpalartAllmaras.C