OpenFOAM: activeBaffleVelocityFvPatchVectorField Class Reference
activeBaffleVelocityFvPatchVectorField Class Reference
Boundary conditions » Coupled
This velocity boundary condition simulates the opening of a baffle due to local flow conditions, by merging the behaviours of wall and cyclic conditions. The baffle joins two mesh regions, where the open fraction determines the interpolation weights applied to each cyclic- and neighbour-patch contribution.
#include <activeBaffleVelocityFvPatchVectorField.H>
Public Member Functions
TypeName ("activeBaffleVelocity")
activeBaffleVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
activeBaffleVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
activeBaffleVelocityFvPatchVectorField (const activeBaffleVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
activeBaffleVelocityFvPatchVectorField (const activeBaffleVelocityFvPatchVectorField &)
virtual tmp< fvPatchVectorField > clone () const
activeBaffleVelocityFvPatchVectorField (const activeBaffleVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
virtual void autoMap (const fvPatchFieldMapper &)
virtual void rmap (const fvPatchVectorField &, const labelList &)
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
This velocity boundary condition simulates the opening of a baffle due to local flow conditions, by merging the behaviours of wall and cyclic conditions. The baffle joins two mesh regions, where the open fraction determines the interpolation weights applied to each cyclic- and neighbour-patch contribution.
We determine whether the baffle is opening or closing from the sign of the net force across the baffle, from which the baffle open fraction is updated using:
where
= baffle open fraction [0-1]
= baffle open fraction on previous evaluation
= simulation time step
= time taken to open the baffle
= net force across the baffle
The open fraction is then applied to scale the patch areas.
Usage
Property Description Required Default value
p pressure field name no p
cyclicPatch cylclic patch name yes
orientation 1 or -1 used to switch flow direction yes
openFraction current opatch open fraction [0-1] yes
openingTime time taken to open the baffle yes
maxOpenFractionDelta max open fraction change per timestep yes
Example of the boundary condition specification:
    <patchName>
    {
        type            activeBaffleVelocity;
        p               p;
        cyclicPatch     cyclic1;
        orientation     1;
        openFraction    0.2;
        openingTime     5.0;
        maxOpenFractionDelta 0.1;
    }
See also
Foam::fixedValueFvPatchField Foam::cyclicFvPatchField
Source files
activeBaffleVelocityFvPatchVectorField.H
activeBaffleVelocityFvPatchVectorField.C
Definition at line 158 of file activeBaffleVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
activeBaffleVelocityFvPatchVectorField() [1/5]
activeBaffleVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Definition at line 30 of file activeBaffleVelocityFvPatchVectorField.C.
activeBaffleVelocityFvPatchVectorField() [2/5]
activeBaffleVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Definition at line 76 of file activeBaffleVelocityFvPatchVectorField.C.
References fvPatchField< vector >::operator=(), and Foam::Zero.
activeBaffleVelocityFvPatchVectorField() [3/5]
activeBaffleVelocityFvPatchVectorField (const activeBaffleVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 52 of file activeBaffleVelocityFvPatchVectorField.C.
activeBaffleVelocityFvPatchVectorField() [4/5]
activeBaffleVelocityFvPatchVectorField (const activeBaffleVelocityFvPatchVectorField & ptf)
Definition at line 108 of file activeBaffleVelocityFvPatchVectorField.C.
activeBaffleVelocityFvPatchVectorField() [5/5]
activeBaffleVelocityFvPatchVectorField (const activeBaffleVelocityFvPatchVectorField & ptf, const DimensionedField< vector, volMesh > & iF)
Definition at line 129 of file activeBaffleVelocityFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("activeBaffleVelocity")
clone() [1/2]
virtual tmp< fvPatchVectorField > clone () const inline virtual
Definition at line 241 of file activeBaffleVelocityFvPatchVectorField.H.
clone() [2/2]
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Definition at line 257 of file activeBaffleVelocityFvPatchVectorField.H.
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Definition at line 153 of file activeBaffleVelocityFvPatchVectorField.C.
rmap()
void rmap (const fvPatchVectorField & ptf, const labelList & addr) virtual
Definition at line 182 of file activeBaffleVelocityFvPatchVectorField.C.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 207 of file activeBaffleVelocityFvPatchVectorField.C.
References Foam::clamp(), e, Foam::endl(), forAll, Foam::Info, Foam::mag(), Foam::min(), p, Foam::sign(), and timeIndex.
write()
void write (Ostream & os) const virtual
Definition at line 285 of file activeBaffleVelocityFvPatchVectorField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntry(), Ostream::writeEntryIfDifferent(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/activeBaffleVelocity/activeBaffleVelocityFvPatchVectorField.H
src/finiteVolume/fields/fvPatchFields/derived/activeBaffleVelocity/activeBaffleVelocityFvPatchVectorField.C