OpenFOAM: PtrList< T > Class Template Reference
PtrList< T > Class Template Reference
A list of pointers to objects of type <T>, with allocation/deallocation management of the pointers. The operator[] returns a reference to the object, not the pointer.
#include <PtrList.H>
Inherits UPtrList< T >.
Inherited by CloudFunctionObjectList< KinematicCloud< Foam::DSMCCloud > >, CloudFunctionObjectList< KinematicCloud< CloudType > >, CloudFunctionObjectList< KinematicCloud< Cloud< basicKinematicCollidingParcel > > >, DictionaryBase< PtrList< T >, T >, FieldField< PatchField, Type >, FieldField< fvPatchField, symmTensor >, FieldField< fvPatchField, scalar >, FieldField< pointPatchField, Type >, FieldField< fvPatchField, vector >, FieldField< fvPatchField, tensor >, FieldField< Foam::fvPatchField, scalar >, FieldField< Foam::fvPatchField, Foam::Vector >, FieldField< Foam::pointPatchField, Foam::Vector >, FieldField< Field, Foam::Vector >, FieldField< Field, scalar >, FieldField< Foam::Field, scalar >, FieldField< Foam::Field, LUType >, FieldField< fvsPatchField, scalar >, FieldField< pointPatchField, scalar >, FieldField< pointPatchField, vector >, FieldField< Foam::Field, solveScalar >, FieldField< faPatchField, scalar >, FieldField< Foam::faPatchField, scalar >, FieldField< Foam::faePatchField, scalar >, FieldField< Foam::faPatchField, Foam::Vector >, FieldField< Foam::faePatchField, Foam::Vector >, FieldField< Foam::faPatchField, Foam::SphericalTensor >, FieldField< Foam::faePatchField, Foam::SphericalTensor >, FieldField< Foam::faPatchField, Foam::SymmTensor >, FieldField< Foam::faePatchField, Foam::SymmTensor >, FieldField< Foam::faPatchField, Foam::Tensor >, FieldField< Foam::faePatchField, Foam::Tensor >, FieldField< Foam::Field, Type >, FieldField< Foam::Field, Foam::Tensor >, FieldField< Foam::fvsPatchField, scalar >, FieldField< Foam::fvsPatchField, Foam::Vector >, FieldField< Foam::fvPatchField, Foam::SphericalTensor >, FieldField< Foam::fvsPatchField, Foam::SphericalTensor >, FieldField< Foam::fvPatchField, Foam::SymmTensor >, FieldField< Foam::fvsPatchField, Foam::SymmTensor >, FieldField< Foam::fvPatchField, Foam::Tensor >, FieldField< Foam::fvsPatchField, Foam::Tensor >, FieldField< Foam::fvPatchField, Type >, FieldField< Foam::pointPatchField, Type >, FieldField< Foam::fvsPatchField, Type >, FieldField< fvsPatchField, vector >, FieldField< Foam::pointPatchField, scalar >, FieldField< Foam::pointPatchField, Foam::SphericalTensor >, FieldField< Foam::pointPatchField, Foam::SymmTensor >, FieldField< Foam::pointPatchField, Foam::Tensor >, FieldField< faPatchField, tensor >, FieldField< faPatchField, vector >, FieldField< faePatchField, scalar >, IOPtrList< Foam::entry >, InjectionModelList< Foam::KinematicCloud< Foam::DSMCCloud > >, ParticleForceList< KinematicCloud< Foam::DSMCCloud > >, ParticleForceList< KinematicCloud< CloudType > >, ParticleForceList< KinematicCloud< Cloud< basicKinematicCollidingParcel > > >, PtrDynList< Foam::Field< label > >, PtrDynList< Foam::Field< scalar > >, PtrDynList< Foam::Field< Foam::Vector > >, PtrDynList< Foam::Field< Foam::SphericalTensor > >, PtrDynList< Foam::Field< Foam::SymmTensor > >, PtrDynList< Foam::Field< Foam::Tensor > >, PtrDynList< Foam::profilingInformation >, ZoneMesh< pointZone, polyMesh >, ZoneMesh< faceZone, polyMesh >, ZoneMesh< cellZone, polyMesh >, IOPtrList< T >, PtrDynList< T, SizeMin >, faBoundaryMesh, fvBoundaryMesh, pointBoundaryMesh, and polyBoundaryMesh.
Public Member Functions
constexpr PtrList () noexcept
PtrList (const label len)
PtrList (const PtrList< T > &list)
PtrList (PtrList< T > &&list)
PtrList (UList< T * > &list)
template<class CloneArg >
PtrList (const PtrList< T > &list, const CloneArg &cloneArgs)
PtrList (PtrList< T > &list, bool reuse)
PtrList (const SLPtrList< T > &list)
template<class INew >
PtrList (Istream &is, const INew &inew)
PtrList (Istream &is)
~PtrList ()
template<class... Args>
PtrList< T > clone (Args &&... args) const
const T * set (const label i) const
void clear ()
void free ()
void resize (const label newLen)
template<class... Args>
T & emplace_back (Args &&... args)
void push_back (T *ptr)
void push_back (std::unique_ptr< T > &&ptr)
void push_back (autoPtr< T > &&ptr)
void push_back (const refPtr< T > &ptr)
void push_back (const tmp< T > &ptr)
void push_back (PtrList< T > &&other)
template<class... Args>
T & emplace_set (const label i, Args &&... args)
template<class... Args>
T & emplace (const label i, Args &&... args)
autoPtr< T > set (const label i, T *ptr)
autoPtr< T > set (const label i, std::unique_ptr< T > &&ptr)
autoPtr< T > set (const label i, autoPtr< T > &&ptr)
autoPtr< T > set (const label i, const refPtr< T > &ptr)
autoPtr< T > set (const label i, const tmp< T > &ptr)
autoPtr< T > release (const label i)
void transfer (PtrList< T > &list)
void operator= (const PtrList< T > &list)
void operator= (PtrList< T > &&list)
void push_back (autoPtr< T > &ptr)=delete
autoPtr< T > set (const label i, autoPtr< T > &ptr)
void setSize (const label newLen)
void append (autoPtr< T > &ptr)
void append (T *ptr)
void append (std::unique_ptr< T > &&ptr)
void append (autoPtr< T > &&ptr)
void append (const refPtr< T > &ptr)
void append (const tmp< T > &ptr)
void append (PtrList< T > &&other)
template<class... Args>
Foam::PtrList< T > clone (Args &&... args) const
Public Member Functions inherited from UPtrList< T >
constexpr UPtrList () noexcept
UPtrList (const label len)
UPtrList (const UPtrList< T > &list)
UPtrList (UPtrList< T > &&list)
UPtrList (UPtrList< T > &list, bool reuse)
UPtrList (PtrList< T > &list)
UPtrList (const UList< T * > &list)
UPtrList (UList< T > &list)
bool empty () const noexcept
label size () const noexcept
label count () const noexcept
T & front ()
const T & front () const
T & back ()
const T & back () const
const T * test (const label i) const
const T * get (const label i) const
T * get (const label i)
const T * set (const label i) const
void clear ()
void free ()
void resize (const label newLen)
label squeezeNull ()
void trimTrailingNull ()
void push_back (T *ptr)
void push_back (UPtrList< T > &&other)
void swap (UPtrList< T > &list)
void transfer (UPtrList< T > &list)
T * set (const label i, T *ptr)
void reorder (const labelUList &oldToNew, const bool check=false)
void sortOrder (const labelUList &order, const bool check=false)
void checkNonNull () const
const T & at (const label i) const
T & at (const label i)
const T & operator[] (const label i) const
T & operator[] (const label i)
FOAM_DEPRECATED_FOR (2022-09, "get(), set() or test() methods") const T *operator()(const label i) const
void operator= (const UPtrList< T > &list)
void operator= (UPtrList< T > &&list)
T ** begin_ptr () noexcept
T ** end_ptr () noexcept
iterator begin ()
iterator end () noexcept
const_iterator cbegin () const
const_iterator cend () const noexcept
const_iterator begin () const
const_iterator end () const noexcept
void setSize (const label n)
T & first ()
const T & first () const
T & last ()
const T & last () const
void append (T *ptr)
void append (UPtrList< T > &&other)
Protected Member Functions
template<class INew >
void readIstream (Istream &is, const INew &inew)
Protected Member Functions inherited from UPtrList< T >
void setAddressableSize (const label n) noexcept
label find_next (label pos) const
UPtrList (Detail::PtrListDetail< T > &&ptrs)
Friends
Istream & operator>> (Istream &is, PtrList< T > &list)
Additional Inherited Members
Public Types inherited from UPtrList< T >
typedef T value_type
typedef T & reference
typedef const T & const_reference
Protected Attributes inherited from UPtrList< T >
Detail::PtrListDetail< T > ptrs_
Detailed Description
template<class T>
class Foam::PtrList< T >
A list of pointers to objects of type <T>, with allocation/deallocation management of the pointers. The operator[] returns a reference to the object, not the pointer.
See also
Foam::UPtrList Foam::PtrDynList
Source files
PtrList.H
PtrListI.H
PtrList.C
PtrListIO.C
Definition at line 64 of file PtrList.H.
Constructor & Destructor Documentation
PtrList() [1/10]
template<class T > constexpr PtrList () inline constexpr noexcept
Definition at line 29 of file PtrListI.H.
Referenced by adjointBoundaryCondition< Type >::addATCUaGradUTerm(), faMatrix< Type >::addToInternalField(), LduMatrix< Type, DType, LUType >::Amul(), Matrix< Form, Type >::AmulImpl(), PrimitivePatch< FaceList, PointField >::boundaryFaces(), treeDataPrimitivePatch< PatchType >::boxes(), singleStepReactingMixture< ThermoType >::calculateqFuel(), LiquidEvaporation< CloudType >::calcXc(), LiquidEvaporationBoil< CloudType >::calcXc(), LiquidEvapFuchsKnudsen< CloudType >::calcXcSolution(), MeshedSurface< Face >::checkZones(), SuppressionCollision< CloudType >::collide(), ORourkeCollision< CloudType >::collide(), FieldField< Field, Type >::component(), adjointBoundaryCondition< Type >::computePatchGrad(), tetrahedron< Point, PointRef >::containmentSphere(), kOmegaSSTBase< BasicEddyViscosityModel >::correct(), SpalartAllmarasBase< BasicEddyViscosityModel >::correct(), deferredCorrection< Type >::correction(), linearUpwind< Type >::correction(), linearUpwindV< Type >::correction(), linearUpwindNormal< Type >::correction(), pointLinear< Type >::correction(), cyclicFvPatchField< scalar >::cyclicFvPatchField(), SpalartAllmarasBase< BasicEddyViscosityModel >::epsilon(), kOmegaSSTBase< BasicEddyViscosityModel >::F1(), kOmegaSSTBase< BasicEddyViscosityModel >::F2(), kOmegaSSTBase< BasicEddyViscosityModel >::F23(), kOmegaSSTBase< BasicEddyViscosityModel >::F3(), PatchToPatchInterpolation< FromPatch, ToPatch >::faceInterpolate(), PatchToPatchInterpolation< FromPatch, ToPatch >::faceInterpolate(), SpalartAllmarasBase< BasicEddyViscosityModel >::fv1(), SpalartAllmarasBase< BasicEddyViscosityModel >::fv2(), kOmegaSSTBase< BasicEddyViscosityModel >::GbyNu0(), MinMax< T >::ge(), adjointBoundaryCondition< Type >::getATC(), leastSquareGrad< T >::grad(), leastSquareGrad< T >::grad(), heThermo< BasicThermo, MixtureType >::heBoundaryCorrection(), InterfaceCompositionPhaseChangePhaseSystem< BasePhaseSystem >::iDmdt(), ThermalPhaseChangePhaseSystem< BasePhaseSystem >::iDmdt(), InjectedParticleDistributionInjection< CloudType >::initialise(), InjectedParticleInjection< CloudType >::initialise(), LduMatrix< Type, DType, LUType >::initMatrixInterfaces(), leastSquaresEdgeInterpolation< Type >::interpolate(), SpalartAllmarasBase< BasicEddyViscosityModel >::k(), DispersionRASModel< CloudType >::kModel(), PhiScheme< Type, PhiLimiter >::limiter(), WallCollisionRecord< Type >::match(), line< Point, PointRef >::nearestDist(), ParticleForce< CloudType >::New(), HeterogeneousReactingModel< CloudType >::New(), SurfaceReactionModel< CloudType >::New(), BinaryCollisionModel< CloudType >::New(), InflowBoundaryModel< CloudType >::New(), WallInteractionModel< CloudType >::New(), CollisionModel< CloudType >::New(), PairModel< CloudType >::New(), WallModel< CloudType >::New(), DispersionModel< CloudType >::New(), InjectionModel< CloudType >::New(), PatchInteractionModel< CloudType >::New(), StochasticCollisionModel< CloudType >::New(), SurfaceFilmModel< CloudType >::New(), CompositionModel< CloudType >::New(), PhaseChangeModel< CloudType >::New(), DevolatilisationModel< CloudType >::New(), HeatTransferModel< CloudType >::New(), AtomizationModel< CloudType >::New(), BreakupModel< CloudType >::New(), CloudFunctionObject< CloudType >::New(), tableReader< Type >::New(), chemistryReader< ThermoType >::New(), edgeInterpolationScheme< Type >::New(), MeshedSurface< Face >::New(), UnsortedMeshedSurface< Face >::New(), multivariateSurfaceInterpolationScheme< Type >::New(), limitedSurfaceInterpolationScheme< Type >::New(), surfaceInterpolationScheme< Type >::New(), chemistryReductionMethod< CompType, ThermoType >::New(), chemistryTabulationMethod< CompType, ThermoType >::New(), interpolation< Type >::New(), faPatchField< Type >::New(), faePatchField< Type >::New(), fvsPatchField< Type >::New(), fvPatchField< Type >::New(), pointPatchField< Type >::New(), OppositeFaceCellWave< Type, TrackingData >::opposingFaceLabels(), PopulationBalancePhaseSystem< BasePhaseSystem >::pDmdt(), PatchToPatchInterpolation< FromPatch, ToPatch >::pointInterpolate(), PatchToPatchInterpolation< FromPatch, ToPatch >::pointInterpolate(), InjectionModel< CloudType >::prepareForNextTimeStep(), PrimitivePatch< FaceList, PointField >::projectPoints(), SpalartAllmarasBase< BasicEddyViscosityModel >::r(), clock::rawDate(), PhaseTransferPhaseSystem< BasePhaseSystem >::rDmdt(), PtrList< T >::readIstream(), List< T >::readList(), UList< T >::readList(), PackedList< Width >::repeated_value(), GeometricField< Type, PatchField, GeoMesh >::replace(), GeometricField< Type, PatchField, GeoMesh >::replace(), IjkField< Type >::resize(), faMatrix< Type >::setComponentReference(), FieldField< Field, Type >::T(), KinematicSurfaceFilm< CloudType >::tangentVector(), FaceCellWave< Type, TrackingData >::updateCell(), ReactingParcel< ParcelType >::updatedDeltaVolume(), jumpCyclicFvPatchField< Type >::updateInterfaceMatrix(), VectorSpace< Form, Cmpt, Ncmpts >::VectorSpace(), faNVDscheme< Type, NVDweight >::weights(), correlationFunction< Type >::writeAveraged(), FixedList< T, N >::writeEntry(), UList< T >::writeEntry(), and StationaryPhaseModel< BasePhaseModel >::zeroField().
PtrList() [2/10]
template<class T > PtrList (const label len) inline explicit
Definition at line 36 of file PtrListI.H.
PtrList() [3/10]
template<class T > PtrList (const PtrList< T > & list) inline
Definition at line 43 of file PtrListI.H.
PtrList() [4/10]
template<class T > PtrList (PtrList< T > && list) inline
Definition at line 50 of file PtrListI.H.
PtrList() [5/10]
template<class T > PtrList (UList< T * > & list) inline explicit
Definition at line 57 of file PtrListI.H.
References T.
PtrList() [6/10]
template<class T > template<class CloneArg > PtrList (const PtrList< T > & list, const CloneArg & cloneArgs) inline
Definition at line 68 of file PtrListI.H.
PtrList() [7/10]
template<class T > PtrList (PtrList< T > & list, bool reuse)
Definition at line 28 of file PtrList.C.
References PtrList< T >::clone(), UPtrList< T >::ptrs_, and UPtrList< T >::size().
PtrList() [8/10]
template<class T > PtrList (const SLPtrList< T > & list) explicit
Definition at line 46 of file PtrList.C.
References UPtrList< T >::cbegin(), UPtrList< T >::cend(), PtrList< T >::clone(), UPtrList< T >::ptrs_, and UPtrList< T >::size().
PtrList() [9/10]
template<class T > template<class INew > PtrList (Istream & is, const INew & inew)
Definition at line 143 of file PtrListIO.C.
PtrList() [10/10]
template<class T > PtrList (Istream & is)
Definition at line 150 of file PtrListIO.C.
~PtrList()
template<class T > ~PtrList ()
Definition at line 64 of file PtrList.C.
Member Function Documentation
readIstream()
template<class T > template<class INew > void readIstream (Istream & is, const INew & inew) protected
Definition at line 30 of file PtrListIO.C.
References token::BEGIN_LIST, PtrList< T >::clear(), FUNCTION_NAME, p, PtrList< T >::PtrList(), PtrList< T >::resize(), PtrList< T >::set(), and T.
Referenced by IOPtrList< T >::IOPtrList(), IOPtrList< T >::IOPtrList(), IOPtrList< Foam::entry >::IOPtrList(), and IOPtrList< Foam::entry >::operator=().
clone() [1/2]
template<class T > template<class... Args> PtrList< T > clone (Args &&... args) const
Referenced by fvMeshTools::addPatch(), faMeshDistributor::distribute(), PtrListDetail< CloudFunctionObject< CloudType > >::free(), freestreamFvPatchField< Type >::freestreamFvPatchField(), freestreamFvPatchField< Type >::freestreamFvPatchField(), ILList< LListBase, T >::ILList(), ILList< LListBase, T >::ILList(), rigidBodyModel::join(), mapPolyMesh::mapPolyMesh(), fvMeshTools::newMesh(), coordinateSystem::operator=(), ILList< ParticleType >::operator=(), refinementHistory::splitCell8::operator=(), boundaryMesh::patchify(), Foam::preservePatchTypes(), PtrList< T >::PtrList(), PtrList< T >::PtrList(), refinementSurfaces::refinementSurfaces(), TimeFunction1< Type >::TimeFunction1(), and cyclicACMIPolyPatch::updateAreas().
set() [1/7]
template<class T > const T * set (const label i) const inline
Definition at line 130 of file PtrList.H.
References UPtrList< T >::set().
Referenced by AABBTree< Type >::AABBTree(), isoSurfacePoint::adaptPatchFields(), PrintTable< KeyType, DataType >::add(), fvMeshAdder::add(), geometric::add(), polyMeshAdder::add(), fvMeshAdder::add(), polyMeshAdder::add(), argList::addArgument(), surfaceZonesInfo::addCellZone(), cellTable::addCellZones(), scene::addColourToMesh(), sixDoFRigidBodyMotion::addConstraints(), exprDriver::addContextObject(), polyTopoChange::addFace(), surfaceZonesInfo::addFaceZone(), phaseSystem::addField(), phaseSystem::addField(), scene::addField(), lduPrimitiveMesh::addInterfaces(), oversetFvMeshBase::addInterpolation(), columnFvMeshInfo::addLocalPatches(), ABAQUSCore::readHelper::addNewElset(), argList::addOption(), topoSetSource::addOrDelete(), topoSetSource::addOrDelete(), topoSetSource::addOrDelete(), meshRefinement::addPatch(), fvMeshTools::addPatch(), FIREMeshReader::addPatches(), meshRefinement::addPointZone(), sixDoFRigidBodyMotion::addRestraints(), topoBitSet::addSet(), exprDriver::addUniformVariable(), argList::addUsage(), exprResultGlobals::addValue(), exprResultGlobals::addValue(), adjointSolverManager::adjointSolverManager(), polyMeshTetDecomposition::adjustTetBasePtIs(), pairPatchAgglomeration::agglomerate(), MGridGenGAMGAgglomeration::agglomerate(), pairGAMGAgglomeration::agglomerate(), GAMGAgglomeration::agglomerateLduAddressing(), LBFGS::allocateMatrices(), meshRefinement::appendPatch(), holeToFace::applyToSet(), normalToFace::applyToSet(), argList::argList(), attachPolyTopoChanger::attach(), Cloud< ParcelType >::autoMap(), extendedEdgeMesh::autoMap(), basicMultiComponentMixture::basicMultiComponentMixture(), Bezier::Bezier(), blackBodyEmission::blackBodyEmission(), meshRefinement::blockLeakFaces(), boundaryRadiationProperties::boundaryRadiationProperties(), PatchTools::calcBounds(), createShellMesh::calcPointRegions(), viewFactor::calculate(), dynamicRefineFvMesh::calculateProtectedCells(), oversetFvMeshBase::cellAverage(), processorColour::cellColour(), cuttingSurfaceBase::cellSelection(), ReynoldsAnalogy::Cf(), boundaryMesh::changeFaces(), boundaryMesh::changePatchType(), Foam::checkFireEdges(), edgeCollapser::checkMeshQuality(), dynamicCode::clear(), GAMGAgglomeration::clearLevel(), GAMGAgglomeration::combineLevels(), ABAQUSCore::readHelper::compact_nodes(), edgeCollapser::consistentCollapse(), hexRef8::consistentUnrefinement(), adjointSolverManager::constraintSensitivities(), coordinateScaling< Type >::coordinateScaling(), diffusionMulticomponent< ReactionThermo, ThermoType >::correct(), ensightMesh::correct(), wallDistData< TransferType >::correct(), directionalMeshWave::correct(), meshWave::correct(), directionalPressureGradientExplicitSource::correct(), trackedParticle::correctAfterParallelTransfer(), AABBTree< Type >::createBoxes(), nearWallFields::createFields(), logFiles::createFiles(), fvMatrix< Type >::createOrUpdateLduPrimitiveAssembly(), inverseDistance::createStencil(), dictionary::csearch(), HashTable< T, Key, Hash >::csorted(), triSurfaceTools::curvatures(), cyclicACMIFvPatchField< Type >::cyclicACMIFvPatchField(), MomentumTransferPhaseSystem< BasePhaseSystem >::ddtCorrByAs(), faFieldDecomposer::decomposeField(), faFieldDecomposer::decomposeField(), fvFieldDecomposer::decomposeField(), fvFieldDecomposer::decomposeField(), pointFieldDecomposer::decomposeField(), boundaryMesh::deletePatch(), Foam::diff(), dimensionSets::dimensionSets(), faMeshDistributor::distribute(), fvMeshDistribute::distribute(), distributedDILUPreconditioner::distributedDILUPreconditioner(), faMeshDistributor::distributeField(), faMeshDistributor::distributeField(), snappyLayerDriver::doLayers(), multiphaseSystem::dragCoeffs(), dummyAgglomeration::dummyAgglomeration(), faBoundaryMesh::edgeFaces(), faBoundaryMesh::edgeLabels(), extendedEdgeMesh::edgeTreesByType(), electrostaticDepositionFvPatchScalarField::electrostaticDepositionFvPatchScalarField(), energyTransport::energyTransport(), fvExprDriver::evaluateVariable(), dynamicRefineFvMesh::extendMarkedCells(), extrudePatchMesh::extrudePatchMesh(), fvBoundaryMesh::faceCells(), polyBoundaryMesh::faceCells(), FaceInteraction< CloudType >::FaceInteraction(), faMatrix< Type >::faMatrix(), phaseSystem::fillFields(), distanceSurface::filterFaceProximity(), distanceSurface::filterKeepLargestRegion(), distanceSurface::filterKeepNearestRegions(), distanceSurface::filterPrepareRegionSplit(), distanceSurface::filterRegionProximity(), meshRefinement::findRegions(), PstreamBuffers::finishedSends(), forAll(), fvMatrix< Type >::fvMatrix(), GAMGSolver::GAMGSolver(), lduPrimitiveMesh::gather(), GeometricBoundaryField< symmTensor, fvPatchField, volMesh >::GeometricBoundaryField(), GeometricBoundaryField< symmTensor, fvPatchField, volMesh >::GeometricBoundaryField(), GeometricBoundaryField< Type, PatchField, GeoMesh >::GeometricBoundaryField(), GeometricBoundaryField< Type, PatchField, GeoMesh >::GeometricBoundaryField(), GeometricBoundaryField< Type, PatchField, GeoMesh >::GeometricBoundaryField(), GeometricBoundaryField< Type, PatchField, GeoMesh >::GeometricBoundaryField(), surfaceZonesInfo::getAllClosedNamedSurfaces(), surfaceZonesInfo::getClosedNamedSurfaces(), surfaceZonesInfo::getInsidePointNamedSurfaces(), meshRefinement::getMasterEdges(), meshRefinement::getMasterPoints(), surfaceZonesInfo::getNamedSurfaces(), surfaceZonesInfo::getStandaloneNamedSurfaces(), surfaceZonesInfo::getUnclosedNamedSurfaces(), GAMGProcAgglomeration::globalCellCells(), lduPrimitiveMesh::globalCellCells(), greyMeanAbsorptionEmission::greyMeanAbsorptionEmission(), GAMGAgglomeration::hasMeshLevel(), OneResistanceHeatTransferPhaseSystem< BasePhaseSystem >::heatTransfer(), TwoResistanceHeatTransferPhaseSystem< BasePhaseSystem >::heatTransfer(), hexRef8Data::hexRef8Data(), if(), if(), if(), if(), isoSurfaceBase::ignoreCyclics(), dynamicMultiMotionSolverFvMesh::init(), dynamicRefineFvMesh::init(), interRegionExplicitPorositySource::initialise(), InjectedParticleDistributionInjection< CloudType >::initialise(), viewFactor::initialise(), streamLineBase::initInterpolations(), InjectedParticleDistributionInjection< CloudType >::InjectedParticleDistributionInjection(), InjectedParticleDistributionInjection< CloudType >::InjectedParticleDistributionInjection(), PDRblock::innerMesh(), GeometricBoundaryField< Type, PatchField, GeoMesh >::interfaces(), faMeshSubset::interpolate(), faMeshSubset::interpolate(), singleCellFvMesh::interpolate(), fvMeshSubset::interpolate(), fvMeshSubset::interpolate(), fvMeshSubset::interpolate(), meshToMesh0::interpolate(), regionModel::interRegionAMI(), meshRefinement::intersectedPoints(), isoSurfaceCell::isoSurfaceCell(), isoSurfacePoint::isoSurfacePoint(), isoSurfaceTopo::isoSurfaceTopo(), lduPrimitiveMesh::lduPrimitiveMesh(), lduPrimitiveMesh::lduPrimitiveMesh(), lduPrimitiveMeshAssembly::lduPrimitiveMeshAssembly(), Foam::MULES::limitSum(), Foam::MULES::limitSum(), liquidMixtureProperties::liquidMixtureProperties(), IOobjectList::lookupClassImpl(), IOobjectList::lookupClassTypeImpl(), IOobjectList::lookupImpl(), LUscalarMatrix::LUscalarMatrix(), polyTopoChange::makeMesh(), voxelMeshSearch::makeMesh(), cyclicFvPatchField< Type >::manipulateMatrix(), cyclicACMIFvPatchField< Type >::manipulateMatrix(), cyclicAMIFvPatchField< Type >::manipulateMatrix(), fvMeshAdder::MapDimField(), fvMeshAdder::MapDimFields(), dynamicRefineFvMesh::mapFields(), volSurfaceMapping::mapInternalToSurface(), meshToMesh::mapSrcToTgt(), fvMeshAdder::MapSurfaceField(), fvMeshAdder::MapSurfaceFields(), meshToMesh::mapTgtToSrc(), fvMeshAdder::MapVolField(), fvMeshAdder::MapVolFields(), edgeCollapser::markMergeEdges(), meshRefinement::markOutsideFaces(), edgeCollapser::markSmallEdges(), Foam::markupBoundaryPoints(), PhaseTransferPhaseSystem< BasePhaseSystem >::massTransfer(), PatchTools::matchEdges(), edgeMesh::mergeEdges(), polyTopoChange::modifyFace(), moleFractions< ThermoType >::moleFractions(), MomentumTransferPhaseSystem< BasePhaseSystem >::momentumTransfer(), MomentumTransferPhaseSystem< BasePhaseSystem >::momentumTransferf(), multiComponentMixture< ThermoType >::multiComponentMixture(), MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::MultiComponentPhaseModel(), MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::MultiComponentPhaseModel(), multiSolidBodyMotionSolver::multiSolidBodyMotionSolver(), Function1< Type >::New(), PatchFunction1< Type >::New(), ensightCase::newData(), fvMeshTools::newMesh(), faMeshTools::newMesh(), nonBlockingGaussSeidelSmoother::nonBlockingGaussSeidelSmoother(), lduPrimitiveMesh::nonBlockingSchedule(), oversetFvMeshBase::normalisation(), objectiveManager::objectiveManager(), IOobjectList::objectsTypeImpl(), objectRegistry::objectsTypeImpl(), noiseModel::octaves(), triad::operator+=(), FieldField< PatchField, Type >::operator/=(), cell::opposingFace(), optimisationManager::optimisationManager(), outletMappedUniformInletFvPatchField< Type >::outletMappedUniformInletFvPatchField(), pairPatchAgglomeration::pairPatchAgglomeration(), pairPatchAgglomeration::pairPatchAgglomeration(), argList::parse(), MomentumTransferPhaseSystem< BasePhaseSystem >::partialElimination(), MomentumTransferPhaseSystem< BasePhaseSystem >::partialEliminationf(), blockMesh::patchDicts(), boundaryMesh::patchify(), cuttingSurfaceBase::performCut(), phaseChange::phaseChange(), phaseForces::phaseForces(), pointBoundaryMesh::pointBoundaryMesh(), polyBoundaryMesh::polyBoundaryMesh(), polyMesh::polyMesh(), polyMesh::polyMesh(), RecycleInteraction< CloudType >::postEvolve(), powerLawLopesdaCostaZone::powerLawLopesdaCostaZone(), Foam::preservePatchTypes(), filmTurbulenceModel::primaryRegionFriction(), GAMGProcAgglomeration::printStats(), GAMGAgglomeration::procAgglomerateLduAddressing(), procLduMatrix::procLduMatrix(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::pyrolysisChemistryModel(), heatTransferCoeffModel::q(), multiphaseInterHtcModel::q(), reactingEulerHtcModel::q(), radiativeIntensityRay::radiativeIntensityRay(), ReactingCloud< CloudType >::ReactingCloud(), ReactingCloud< Foam::DSMCCloud >::ReactingCloud(), functionObjectList::read(), Curle::read(), runTimeControl::read(), externalFileSource::read(), binModel::read(), multiFieldValue::read(), electricPotential::read(), areaWrite::read(), multiRegion::read(), sampledSurfaces::read(), multiMotion::read(), NASedgeFormat::read(), ABAQUSsurfaceFormat< Face >::read(), STARCDedgeFormat::read(), boundaryMesh::read(), externalCoupled::readDataMaster(), GeometricBoundaryField< symmTensor, fvPatchField, volMesh >::readField(), GeometricBoundaryField< Type, PatchField, GeoMesh >::readField(), lagrangianFieldDecomposer::readFieldFields(), lagrangianFieldDecomposer::readFields(), functionObjectList::readFunctionObject(), PtrList< CloudFunctionObject< CloudType > >::readIstream(), PtrList< T >::readIstream(), Foam::readLagrangian(), PackedList< Width >::readList(), valueAverageBase::readState(), boundaryMesh::readTriSurface(), polyMesh::readUpdate(), mapDistributeBase::receive(), plicRDF::reconstruct(), faFieldReconstructor::reconstructAreaField(), faFieldReconstructor::reconstructEdgeField(), faFieldReconstructor::reconstructField(), faFieldReconstructor::reconstructField(), fvFieldReconstructor::reconstructField(), fvFieldReconstructor::reconstructField(), pointFieldReconstructor::reconstructField(), fvFieldReconstructor::reconstructInternalField(), pointFieldReconstructor::reconstructPointField(), processorMeshes::reconstructPoints(), fvFieldReconstructor::reconstructSurfaceField(), fvFieldReconstructor::reconstructVolumeField(), RecycleInteraction< CloudType >::RecycleInteraction(), codedFunctionObject::redirectFunctionObject(), codedPoints0MotionSolver::redirectMotionSolver(), CodedSource< Type >::redirectOption(), codedFixedValueFvPatchField< Type >::redirectPatchField(), codedMixedFvPatchField< Type >::redirectPatchField(), codedFixedValuePointPatchField< Type >::redirectPatchField(), dynamicRefineFvMesh::refine(), distanceSurface::refineBlockedCells(), refinementSurfaces::refinementSurfaces(), refinementSurfaces::refinementSurfaces(), refinementFeatures::regionEdgeTrees(), variablesSet::renameTurbulenceField(), coordSetWriter::repackageFields(), coordSetWriter::repackageFields(), snappySnapDriver::repatchToSurface(), fvMeshSubset::reset(), faMeshSubset::reset(), fvMeshSubset::reset(), pointFieldDecomposer::reset(), valueAverageBase::resetState(), sampledMeshedSurface::sampledMeshedSurface(), sampledPatchInternalField::sampledPatchInternalField(), sampledFaceZone::sampleOnPoints(), sampledPatch::sampleOnPoints(), sampledSurface::sampleOnPoints(), searchableSurfaceCollection::searchableSurfaceCollection(), cellCellStencil::seedCell(), ZoneMesh< pointZone, polyMesh >::selection(), dynamicRefineFvMesh::selectRefineCandidates(), dynamicRefineFvMesh::selectUnrefinePoints(), mapDistributeBase::send(), distributedDILUPreconditioner::sendGlobal(), sensitivityMultiple::sensitivityMultiple(), PtrList< T >::set(), PtrListDictionary< phaseModel >::set(), PtrListDictionary< T >::set(), topoBitSet::set(), topoBoolSet::set(), topoBitSet::set(), Foam::BitOps::set(), argList::setAdvanced(), fvMatrix< Type >::setBounAndInterCoeffs(), refinementSurfaces::setCurvatureMinLevelFields(), dynamicCode::setFilterContext(), dynamicCode::setFilterVariable(), fvMatrix< Type >::setInterfaces(), argList::setOption(), PackedList< Width >::setPair(), addPatchCellLayer::setRefinement(), hexRef8::setRefinement(), edgeCollapser::setRefinement(), data::setSolverPerformance(), ensightCase::setTime(), coordSetWriter::setTracks(), cellCellStencil::setUpFront(), cellCellStencil::setUpFrontOnOversetPatch(), Foam::simpleGeometricFilter(), singleStepReactingMixture< ThermoType >::singleStepReactingMixture(), fieldSmoother::smoothNormals(), solidChemistryModel< CompType, SolidThermo >::solidChemistryModel(), solidMixtureProperties::solidMixtureProperties(), multiphaseSystem::solve(), multiphaseSystem::solveAlphas(), MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::solveYi(), HashTable< T, Key, Hash >::sorted(), StandardChemistryModel< ReactionThermo, ThermoType >::StandardChemistryModel(), PatchTools::subsetMap(), reconstructionSchemes::surface(), surfaceAlignedSBRStressFvMotionSolver::surfaceAlignedSBRStressFvMotionSolver(), syncTools::syncFaceList(), syncTools::syncPointMap(), ParticleStressModel::tau(), thermoSingleLayer::thermoSingleLayer(), blockMesh::topology(), trackingInverseDistance::trackingInverseDistance(), triSurfaceRegionSearch::treeByRegion(), dynamicRefineFvMesh::unrefine(), liquidFilmBase::Up(), cellVolumeWeight::update(), inverseDistance::update(), trackingInverseDistance::update(), rawTopoChangerFvMesh::update(), writerCaching::update(), lduPrimitiveMeshAssembly::update(), oversetFvMeshBase::updateAddressing(), optimisationType::updateGradientsAndValues(), topoBitSet::updateLabels(), topoBoolSet::updateLabels(), topoSet::updateLabels(), fileMonitor::updateStates(), dynamicRefineFvMesh::updateTopology(), solution::upgradeSolverDict(), liquidFilmBase::Uw(), volBSplinesBase::volBSplinesBase(), cellCellStencil::walkFront(), wideBandAbsorptionEmission::wideBandAbsorptionEmission(), maxDurationCondition::write(), vtkWrite::write(), writeObjects::write(), OFstreamCollator::write(), oversetFvMeshBase::write(), externalCoupled::writeDataMaster(), faMeshDecomposition::writeDecomposition(), cellZoneSet::writeObject(), faceZoneSet::writeObject(), pointZoneSet::writeObject(), triSurface::writeStats(), streamLineBase::writeToFile(), Foam::writeVolFields(), vtkWrite::writeVolFieldsImpl(), and zoneMotion::zoneMotion().
clear()
template<class T > void clear () inline
Definition at line 81 of file PtrListI.H.
Referenced by MRFZoneList::absolute(), sensitivitySurface::accumulateIntegrand(), sensitivitySurfacePoints::accumulateIntegrand(), extendedEdgeMesh::add(), labelRanges::add(), ISAT< CompType, ThermoType >::add(), boundBox::add(), polyMeshAdder::add(), cellTable::addCellZones(), Cloud< ParcelType >::addParticle(), polyMesh::addPatches(), faMatrix< Type >::addToInternalField(), fvMatrix< Type >::addToInternalField(), regIOobject::addWatch(), adjointkOmegaSST::adjointMeanFlowSource(), surfaceWriter::adjustSurface(), polyMeshTetDecomposition::adjustTetBasePtIs(), UPstream::allocateCommunicator(), UPstream::allocateCommunicator(), Foam::PstreamDetail::allToAllConsensus(), LduMatrix< Type, DType, LUType >::Amul(), lduMatrix::Amul(), haloToCell::applyToSet(), HashSet< Key, Hash >::assignMany(), Foam::atan2(), Foam::atan2(), Foam::atan2(), Foam::atan2(), Foam::atan2(), Foam::atan2(), Foam::atan2(), Foam::atan2(), Foam::atan2(), Foam::atan2(), Foam::fac::average(), Foam::fac::average(), Foam::fvc::average(), Foam::fvc::average(), Foam::meshTools::bandCompression(), vtkWriter::beginTime(), vtkWriter::beginTime(), PDRblock::blockMeshDict(), InterfaceForce< CloudType >::cacheFields(), LiftForce< CloudType >::cacheFields(), PressureGradientForce< CloudType >::cacheFields(), Relaxation< CloudType >::cacheFields(), Explicit< CloudType >::cacheFields(), faceAreaIntersect::calc(), faceAreaWeightAMI::calcAddressing(), holeToFace::calcClosure(), cellToCellStencil::calcFaceCells(), cellToFaceStencil::calcFaceCells(), zoneCellStencils::calcFaceCells(), cellToFaceStencil::calcFaceStencil(), cutCell::calcIsoFacePointsFromEdges(), cellMatcher::calcLocalFaces(), createShellMesh::calcPointRegions(), coupledFaPatch::calcTransformTensors(), waveMethod::calculate(), cellVolumeWeightMethod::calculateAddressing(), mapNearestMethod::calculateAddressing(), correctedCellVolumeWeightMethod::calculateAddressing(), dynamicRefineFvMesh::calculateProtectedCells(), primitiveMesh::cellCells(), primitiveMesh::cellEdges(), primitiveMesh::cellPoints(), cuttingSurfaceBase::cellSelection(), primitiveMesh::checkFaceFaces(), MeshedSurface< Face >::checkFaces(), regIOobject::checkOut(), Foam::clamp(), Foam::clamp(), ABAQUSCore::readHelper::clear(), writerCaching::clear(), STLAsciiParse::clear(), STLReader::clear(), seriesWriter::clear(), vtmWriter::clear(), faBoundaryMesh::clear(), faMeshSubset::clear(), faPatchData::clear(), fvMatrix< Type >::clear(), fvMeshSubset::clear(), edgeMesh::clear(), CompactListList< T >::clear(), Distribution< Type >::clear(), UPtrList< T >::clear(), namedDictionary::clear(), dlLibraryTable::clear(), dynamicCode::clear(), functionObjectList::clear(), IjkField< Type >::clear(), mapDistributeBase::clear(), mapDistributePolyMesh::clear(), polyBoundaryMesh::clear(), ZoneMesh< ZoneType, MeshType >::clear(), globalIndex::clear(), coordinateSystem::clear(), Enum< EnumType >::clear(), decompositionInformation::clear(), fvFieldDecomposer::clear(), pointFieldDecomposer::clear(), faFieldDecomposer::clear(), mergedSurf::clear(), MeshedSurfaceIOAllocator::clear(), TRIReader::clear(), fieldAverageItem::clear(), ZoneMesh< ZoneType, MeshType >::clearAddressing(), polyMesh::clearAddressing(), parseDriver::clearField(), reader::clearGeom(), polyMesh::clearGeom(), surfaceInterpolation::clearOut(), meshSearch::clearOut(), triSurfaceSearch::clearOut(), globalMeshData::clearOut(), distributedTriSurfaceMesh::clearOut(), PstreamBuffers::clearRecv(), PstreamBuffers::clearRecvs(), exprDriver::clearResult(), fieldSelection::clearSelection(), PstreamBuffers::clearSend(), PstreamBuffers::clearSends(), adjointSolver::clearSensitivities(), PackedList< Width >::clearStorage(), CircularBuffer< T >::clearStorage(), OListStreamAllocator::clearStorage(), cutCellIso::clearStorage(), cutCellPLIC::clearStorage(), cutFaceAdvect::clearStorage(), cutFaceIso::clearStorage(), cutFacePLIC::clearStorage(), exprDriver::clearVariables(), surfaceWriter::close(), ensightWriter::close(), vtkWriter::close(), ensightWriter::close(), vtkWriter::close(), dlLibraryTable::close(), dlLibraryTable::close(), ofstreamPointer::close(), Foam::cmptAv(), Foam::cmptAv(), Foam::cmptAv(), Foam::cmptAv(), Foam::cmptMag(), Foam::cmptMag(), Foam::cmptMagSqr(), Foam::cmptMax(), Foam::cmptMax(), Foam::cmptMin(), Foam::cmptMin(), processorColour::colour(), ABAQUSCore::readHelper::compact_nodes(), DimensionedField< symmTensor, Foam::volMesh >::component(), incompressibleAdjointSolver::computeGradDxDbMultiplier(), hexRef8::consistentSlowRefinement(), surfMesh::copySurface(), kEpsilonLopesdaCosta< BasicTurbulenceModel >::correct(), kL< BasicTurbulenceModel >::correct(), LamBremhorstKE::correct(), LienLeschziner::correct(), mixtureKEpsilon< BasicTurbulenceModel >::correct(), kOmegaSSTBase< BasicEddyViscosityModel >::correct(), SpalartAllmarasBase< BasicEddyViscosityModel >::correct(), dynamicKEqn< BasicTurbulenceModel >::correct(), kEqn< BasicTurbulenceModel >::correct(), EBRSM< BasicTurbulenceModel >::correct(), kEpsilon< BasicTurbulenceModel >::correct(), kEpsilonPhitF< BasicTurbulenceModel >::correct(), kOmega< BasicTurbulenceModel >::correct(), LaunderSharmaKE< BasicTurbulenceModel >::correct(), RNGkEpsilon< BasicTurbulenceModel >::correct(), fvMeshSubsetProxy::correct(), incompressiblePrimalSolver::correctBoundaryConditions(), kOmegaSSTLM< BasicTurbulenceModel >::correctReThetatGammaInt(), removePoints::countPointUsage(), profiling::create(), box::createMap(), meshRefinement::createZoneBaffles(), Foam::fvc::curl(), triSurfaceTools::curvatures(), Foam::fvc::DDt(), simpleGeomDecomp::decompose(), simpleGeomDecomp::decompose(), metisLikeDecomp::decomposeGeneral(), faMeshDecomposition::decomposeMesh(), DimensionedField< symmTensor, Foam::volMesh >::DimensionedField(), DimensionedField< Type, GeoMesh >::DimensionedField(), DimensionedField< Type, GeoMesh >::DimensionedField(), DimensionedField< Type, GeoMesh >::DimensionedField(), fvMeshDistribute::distribute(), hexRef8::distribute(), refinementHistory::distribute(), meshRefinement::distribute(), distributedDILUPreconditioner::distributedDILUPreconditioner(), Foam::fac::div(), Foam::fac::div(), Foam::fvc::div(), Foam::fvc::div(), Foam::fac::div(), Foam::fam::div(), Foam::fac::div(), Foam::fam::div(), Foam::fac::div(), Foam::fac::div(), Foam::fac::div(), Foam::fac::div(), Foam::fac::div(), Foam::fvc::div(), Foam::fvc::div(), Foam::fvc::div(), Foam::fvc::div(), Foam::fvm::div(), Foam::fvc::div(), Foam::fvm::div(), Foam::fvc::div(), Foam::fvc::div(), adjointkOmegaSST::divUMeanFlowSource(), Foam::dlOpen(), Foam::fvc::domainIntegrate(), Foam::fvc::domainIntegrate(), snappySnapDriver::doSnap(), surfaceInterpolationScheme< Type >::dotInterpolate(), primitiveMesh::edgeCells(), primitiveMesh::edgeFaces(), Foam::fac::edgeIntegrate(), Foam::fac::edgeSum(), PatchEdgeFaceWave< PrimitivePatchType, Type, TrackingData >::edgeToFace(), vtkWrite::end(), vtkWriter::endTime(), edgeInterpolationScheme< Type >::euclidianInterpolate(), FilterField::evaluate(), Pstream::exchange(), Pstream::exchange(), Pstream::exchangeSizes(), Pstream::exchangeSizes(), Pstream::exchangeSizes(), Pstream::exchangeSizes(), ddt2::execute(), zeroGradient::execute(), coordSetWriter::expire(), sampledIsoSurface::expire(), surfaceWriter::expire(), sampledInterface::expire(), ABAQUSCore::faceDecomposition(), NASCore::faceDecomposition(), primitiveMesh::faceEdges(), LduMatrix< Type, DType, LUType >::faceH(), lduMatrix::faceH(), PatchToPatchInterpolation< FromPatch, ToPatch >::faceInterpolate(), PatchEdgeFaceWave< PrimitivePatchType, Type, TrackingData >::faceToEdge(), PrimitivePatchInterpolation< Patch >::faceToEdgeInterpolate(), PrimitivePatchInterpolation< Patch >::faceToPointInterpolate(), faMatrix< Type >::faMatrix(), FieldField< Field, Type >::FieldField(), boundaryDataSurfaceReader::fieldNames(), IOobject::fileNameComponents(), masterUncollatedFileOperation::filePathInfo(), refinementSurfaces::findAllIntersections(), voxelMeshSearch::findCell(), shellSurfaces::findDirectionalLevel(), searchableBox::findLineAll(), searchableCone::findLineAll(), searchableCylinder::findLineAll(), searchableDisk::findLineAll(), searchablePlane::findLineAll(), searchablePlate::findLineAll(), searchableRotatedBox::findLineAll(), searchableSphere::findLineAll(), searchableSurfaceCollection::findLineAll(), searchableSurfaceWithGaps::findLineAll(), distributedTriSurfaceMesh::findLineAll(), triSurfaceSearch::findLineAll(), PstreamBuffers::finishedSends(), adjointSpalartAllmaras::FISensitivityTerm(), extendedEdgeMesh::flipNormals(), Foam::fvc::flux(), Foam::fvc::flux(), Foam::fvc::flux(), Foam::fvc::flux(), Foam::fvc::flux(), Foam::fvc::flux(), Foam::fvc::flux(), for(), fft::forwardTransform(), fft::forwardTransform(), fvMatrix< Type >::fvMatrix(), globalIndex::gather(), globalIndex::gather(), globalIndex::gatherInplace(), decomposedBlockData::gatherSlaveData(), globalIndex::gatherValues(), GeometricField< Type, PatchField, GeoMesh >::GeometricField(), coordSetWriter::getBufferLine(), zoneDistribute::getFields(), fvExprDriver::getOrReadFieldImpl(), cellDistFuncs::getPointNeighbours(), globalIndex::globalIndex(), updateMethod::globalSum(), Foam::fac::grad(), gradScheme< Type >::grad(), Foam::fac::grad(), Foam::fac::grad(), gradScheme< Type >::grad(), Foam::fvc::grad(), Foam::fvc::grad(), Foam::fvc::grad(), LduMatrix< Type, DType, LUType >::H(), lduMatrix::H(), FaceCellWave< Type, TrackingData >::handleExplicitConnections(), FaceCellWave< Type, TrackingData >::handleProcPatches(), indexedOctree< Type >::indexedOctree(), fieldAverage::initialize(), streamLineBase::initInterpolations(), fvMeshSubsetProxy::interpolate(), leastSquaresEdgeInterpolation< Type >::interpolate(), edgeInterpolationScheme< Type >::interpolate(), volPointInterpolation::interpolate(), pointToPointPlanarInterpolation::interpolate(), edgeInterpolationScheme< Type >::interpolate(), surfaceInterpolationScheme< Type >::interpolate(), volPointInterpolation::interpolate(), volPointInterpolation::interpolate(), pointVolInterpolation::interpolate(), meshToMesh0::interpolate(), meshToMesh0::interpolate(), fvMeshSubsetProxy::interpolateInternal(), meshToMesh0::interpolateInternalField(), Foam::inv(), Foam::inv(), IOField< Type >::IOField(), isoSurfaceTopo::isoSurfaceTopo(), JobInfo::JobInfo(), Foam::fac::laplacian(), Foam::fvc::laplacian(), Foam::fvc::laplacian(), Foam::fac::laplacian(), Foam::fac::laplacian(), Foam::fvc::laplacian(), Foam::fvc::laplacian(), Foam::fvc::laplacian(), Foam::fam::laplacian(), Foam::fac::laplacian(), Foam::fam::laplacian(), Foam::fac::laplacian(), Foam::fvm::laplacian(), Foam::fvc::laplacian(), Foam::fvm::laplacian(), Foam::fvc::laplacian(), Foam::fvc::laplacian(), Foam::fvm::laplacian(), Foam::fvc::laplacian(), Foam::fvm::laplacian(), Foam::fvc::laplacian(), Foam::fvc::laplacian(), Foam::fac::laplacian(), Foam::fac::laplacian(), Foam::fvc::laplacian(), Foam::fvc::laplacian(), Foam::linearEdgeInterpolate(), Foam::linearInterpolate(), lnGradScheme< Type >::lnGrad(), Foam::fac::lnGrad(), Foam::fac::lnGrad(), triSurfaceLoader::load(), Foam::mag(), Foam::mag(), Foam::mag(), Foam::mag(), Foam::magSqr(), Foam::magSqr(), Foam::magSqr(), Foam::magSqr(), Foam::fvc::magSqrGradGrad(), adjointSimple::mainIter(), simple::mainIter(), Foam::makeZeroGradientField(), Foam::makeZeroGradientField(), mapDistribute::mapDistributeBase(), volSurfaceMapping::mapInternalToSurface(), volSurfaceMapping::mapInternalToSurface(), volSurfaceMapping::mapToSurface(), volSurfaceMapping::mapToSurface(), volSurfaceMapping::mapToSurface(), volSurfaceMapping::mapToSurface(), volSurfaceMapping::mapToVolume(), volSurfaceMapping::mapToVolume(), volSurfaceMapping::mapToVolume(), volSurfaceMapping::mapToVolumePatch(), volSurfaceMapping::mapToVolumePatch(), inverseDistance::markDonors(), trackingInverseDistance::markDonors(), trackingInverseDistance::markPatchesAsHoles(), inverseDistance::markPatchesAsHoles(), surfaceWriter::merge(), blockMesh::mesh(), meshedSurfRef::movePoints(), globalIndex::mpiGather(), globalIndex::mpiGatherInplace(), globalIndex::mpiGatherInplaceOp(), Foam::fac::ndiv(), Foam::fac::ndiv(), Foam::fac::ndiv(), Foam::fac::ndiv(), Foam::fac::ndiv(), Foam::fac::ndiv(), Foam::fam::ndiv(), Foam::fam::ndiv(), Foam::fac::ndiv(), Foam::fac::ndiv(), Foam::fac::ndiv(), entry::New(), fvMeshTools::newMesh(), Foam::fac::ngrad(), Foam::fac::ngrad(), Foam::fac::ngrad(), MeshedSurface< Face >::nTriangles(), adjointkOmegaSST::nutMeanFlowSource(), dlLibraryTable::open(), csvTableReader< Type >::operator()(), anisotropicFilter::operator()(), laplaceFilter::operator()(), simpleFilter::operator()(), anisotropicFilter::operator()(), laplaceFilter::operator()(), simpleFilter::operator()(), anisotropicFilter::operator()(), laplaceFilter::operator()(), simpleFilter::operator()(), anisotropicFilter::operator()(), laplaceFilter::operator()(), simpleFilter::operator()(), faMatrix< Type >::operator*=(), faMatrix< Type >::operator*=(), fvMatrix< Type >::operator*=(), fvMatrix< Type >::operator*=(), faMatrix< Type >::operator+=(), fvMatrix< Type >::operator+=(), faMatrix< Type >::operator+=(), fvMatrix< Type >::operator+=(), faMatrix< Type >::operator+=(), fvMatrix< Type >::operator+=(), faMatrix< Type >::operator-=(), fvMatrix< Type >::operator-=(), faMatrix< Type >::operator-=(), fvMatrix< Type >::operator-=(), faMatrix< Type >::operator-=(), fvMatrix< Type >::operator-=(), Foam::operator<<(), cellTable::operator=(), SortableList< T >::operator=(), DimensionedField< Type, GeoMesh >::operator=(), faMatrix< Type >::operator=(), fvMatrix< Type >::operator=(), GeometricField< Type, PatchField, GeoMesh >::operator=(), SortableList< T >::operator=(), SortableList< T >::operator=(), GeometricField< Type, PatchField, GeoMesh >::operator==(), Foam::operator>>(), OppositeFaceCellWave< Type, TrackingData >::opposingFaceLabels(), argList::parse(), scalarRange::parse(), noiseFFT::Pf(), primitiveMesh::pointCells(), PatchToPatchInterpolation< FromPatch, ToPatch >::pointInterpolate(), primitiveMesh::pointPoints(), PrimitivePatchInterpolation< Patch >::pointToFaceInterpolate(), Foam::polyMeshZipUpCells(), ParticleTrap< CloudType >::postEvolve(), simple::postLoop(), ParticleCollector< CloudType >::postMove(), Foam::pow(), Foam::pow(), Foam::pow(), Foam::pow(), Foam::pow(), Foam::pow(), Foam::pow(), Foam::pow(), Foam::pow(), Foam::pow(), Foam::pow(), Foam::pow(), Foam::pow(), Foam::pow(), PtrDynList< Foam::Field< label > >::push_back(), DynamicList< T, SizeMin >::push_back(), ITstream::push_back(), PtrDynList< T, SizeMin >::push_back(), QRMatrix< MatrixType >::QRMatrix(), QRMatrix< MatrixType >::QRMatrix(), realizableKE< BasicTurbulenceModel >::rCmu(), functionObjectList::read(), regIOobject::read(), Time::read(), AMIWeights::read(), wallBoundedStreamLine::read(), solverInfo::read(), sampledSets::read(), fvExpressionField::read(), surfaceFieldValue::read(), volFieldValue::read(), fluxSummary::read(), cloudInfo::read(), dataCloud::read(), vtkCloud::read(), ensightWrite::read(), vtkWrite::read(), rigidBodyModel::read(), sampledSurfaces::read(), sixDoFRigidBodyMotion::read(), strainRateFunction::read(), NASedgeFormat::read(), NASsurfaceFormat< Face >::read(), OBJsurfaceFormat< Face >::read(), STARCDsurfaceFormat< Face >::read(), STLsurfaceFormat< Face >::read(), TRIsurfaceFormat< Face >::read(), STARCDedgeFormat::read(), boundaryMesh::read(), fieldAverage::readAveragingProperties(), Time::readDict(), mapDistribute::readDict(), GeometricBoundaryField< Type, PatchField, GeoMesh >::readField(), PtrList< T >::readIstream(), PackedList< Width >::readList(), LList< LListBase, T >::readList(), List< T >::readList(), Time::readModifiedObjects(), fileOperation::readObjects(), masterUncollatedFileOperation::readObjects(), Foam::readObjVertices(), STARCDCore::readPoints(), masterUncollatedFileOperation::readStream(), boundaryMesh::readTriSurface(), Foam::readUntilBalancedDelimiter(), Foam::readVariable(), Foam::readVerbatim(), fft::realTransform1D(), isoAlpha::reconstruct(), Foam::fvc::reconstruct(), Foam::fvc::reconstructMag(), regionSplit::regionSplit(), regionSplit::regionSplit(), MRFZoneList::relative(), MRFZoneList::relative(), MRFZoneList::relative(), cyclicAMIPolyPatch::removeAMIFaces(), seriesWriter::removeNewer(), MeshedSurface< Face >::removeZones(), ofstreamPointer::reopen(), ifstreamPointer::reopen_gz(), FIREMeshReader::reorganize(), vtmWriter::repair(), Field< Type >::replace(), ensightMesh::options::reset(), FilterField::reset(), UPstream::commsStruct::reset(), faMeshBoundaryHalo::reset(), globalIndex::reset(), vtuSizing::reset(), Foam::resetFuncsImpl(), polyMesh::resetMotion(), logFiles::resetName(), logFiles::resetNames(), CompactListList< T >::resize(), fieldAverage::restart(), faceAreaWeightAMI::restartUncoveredSourceFace(), fft::reverseTransform(), fft::reverseTransform(), OListStreamAllocator::rewind(), UOPstreamBase::rewind(), ISstream::rewind(), Field< Type >::rmap(), Field< Type >::rmap(), Field< T >::rmap(), searchableSurfaceToCell::searchableSurfaceToCell(), searchableSurfaceToFace::searchableSurfaceToFace(), searchableSurfaceToPoint::searchableSurfaceToPoint(), decompositionMethod::setConstraints(), faBoundaryMesh::setGroup(), ZoneMesh< ZoneType, MeshType >::setGroup(), Time::setMonitoring(), mappedPatchBase::setOffset(), mappedPatchBase::setOffset(), meshCutter::setRefinement(), tetDecomposer::setRefinement(), addPatchCellLayer::setRefinement(), meshCutAndRemove::setRefinement(), boundaryCutter::setRefinement(), propellerInfo::setSampleDiskGeometry(), coordSetWriter::setTracks(), coordSetWriter::setTrackTimes(), combineFaces::setUnrefinement(), zoneDistribute::setUpCommforZone(), SortableList< T >::shrink(), searchableSurfacesQueries::signedDistance(), snGradScheme< Type >::snGrad(), Foam::fvc::snGrad(), Foam::fvc::snGrad(), ensightFaces::sort(), PatchTools::sortedPointEdges(), MeshedSurface< Face >::sortFacesAndStore(), split(), meshRefinement::splitFacesUndo(), Foam::stringOps::splitFunctionArgs(), fileOperation::splitProcessorPath(), Foam::sqr(), Foam::sqr(), Foam::sqr(), Foam::sqr(), Foam::stabilise(), Foam::stabilise(), Foam::stabilise(), MeshedSurface< Face >::stitchFaces(), hexRef8::storeData(), string::string_printf(), faMatrix< Type >::subtractFromInternalField(), fvMatrix< Type >::subtractFromInternalField(), Foam::sumSqr(), surfaceFeatures::surfaceFeatures(), Foam::fvc::surfaceIntegrate(), surfaceIntersection::surfaceIntersection(), surfaceIntersection::surfaceIntersection(), surfaceIntersection::surfaceIntersection(), Foam::fvc::surfaceSum(), UnsortedMeshedSurface< Face >::swap(), LduMatrix< Type, DType, LUType >::Tmul(), lduMatrix::Tmul(), MeshedSurface< Face >::transcribe(), DLListBase::transfer(), MeshedSurface< Face >::transfer(), triSurface::transfer(), SLListBase::transfer(), MeshedSurface< Face >::transfer(), UnsortedMeshedSurface< Face >::transfer(), Foam::transform(), PatchFunction1< Type >::transform(), Foam::transformPoints(), MeshedSurface< Face >::triangulate(), advancingFrontAMI::triangulatePatch(), hashedWordList::uniq(), coordSetWriter::unsetTime(), surfaceWriter::unsetTime(), cellVolumeWeight::update(), inverseDistance::update(), trackingInverseDistance::update(), objectiveForce::update_dxdbMultiplier(), objectiveMoment::update_dxdbMultiplier(), polyMesh::updateGeomPoints(), hexRef8Data::updateMesh(), polyMesh::updateMesh(), patchInjectionBase::updateMesh(), ensightMesh::options::useBoundaryMesh(), ensightMesh::options::useCellZones(), TableBase< Type >::userTimeToTime(), Foam::fvc::volumeIntegrate(), Foam::fvc::volumeIntegrate(), distributedDILUPreconditioner::wait(), UPstream::waitSomeRequests(), cuttingSurfaceBase::walkCellCuts(), processorColour::walkFront(), areaWrite::write(), ParticleTracks< CloudType >::write(), vtmWriter::write(), FIREMeshWriter::write(), FLMAsurfaceFormat< Face >::write(), surfaceFieldValue::writeAll(), Foam::writeAreaField(), Foam::writeAreaFields(), Foam::writeDimFields(), Foam::writeDimFields(), Field< T >::writeEntry(), externalCoupled::writeGeometry(), Foam::writePointField(), Foam::writePointField(), propellerInfo::writeSampleDiskSurface(), surfaceNoise::writeSurfaceData(), gltfWriter::writeTemplate_animate(), Foam::writeVolField(), Foam::writeVolFields(), Foam::writeVolFields(), zoneToCell::zones(), zoneToFace::zones(), zoneToPoint::zones(), zoneToCell::zones(), zoneToFace::zones(), zoneToPoint::zones(), zoneToCell::zones(), zoneToFace::zones(), zoneToPoint::zones(), HashPtrTable< T, Key, Hash >::~HashPtrTable(), LPtrList< LListBase, T >::~LPtrList(), processorFaPatch::~processorFaPatch(), processorPolyPatch::~processorPolyPatch(), and Time::~Time().
free()
template<class T > void free () inline
Definition at line 89 of file PtrListI.H.
Referenced by mapDistributeBase::send().
resize()
template<class T > void resize (const label newLen)
Definition at line 95 of file PtrList.C.
Referenced by geometric::add(), preservePatches::add(), singleProcessorFaceSets::add(), object::addData(), polyTopoChange::addMesh(), fvMeshTools::addPatch(), exprDriver::addVariables(), regIOobject::addWatch(), MeshedSurface< Face >::addZones(), pairGAMGAgglomeration::agglomerate(), UPstream::allGatherValues(), UPstream::allocateCommunicator(), HashSet< Key, Hash >::assignMany(), attachPolyTopoChanger::attach(), Foam::blankElementMasks(), searchableDisk::boundingSpheres(), searchablePlane::boundingSpheres(), searchablePlate::boundingSpheres(), searchableSphere::boundingSpheres(), box::box(), SurfaceFilmModel< CloudType >::cacheFilmFields(), isoSurfaceBase::calcCellCuts(), Foam::calcElementMasks(), polyLine::calcParam(), DarcyForchheimer::calcTransformModelData(), fixedCoeff::calcTransformModelData(), coupledFaPatch::calcTransformTensors(), dynamicRefineFvMesh::calculateProtectedCells(), cuttingSurfaceBase::cellSelection(), MeshedSurface< Face >::checkFaces(), faBoundaryMesh::checkParallelSync(), polyBoundaryMesh::checkParallelSync(), ensightFaces::classify(), dlLibraryTable::close(), cellShape::collapsedFaces(), triSurfaceTools::collapseEdges(), collector::collector(), mappedPatchBase::collectSamples(), PrecisionAdaptor< Type, InputType, Container >::commit(), CompactListList< T >::CompactListList(), CompactListList< T >::CompactListList(), ConstantField< Type >::ConstantField(), faPatch::constraintTypes(), fvPatch::constraintTypes(), polyPatch::constraintTypes(), ensightMesh::correct(), wallDistAddressing::correct(), profiling::create(), metisLikeDecomp::decomposeGeneral(), faMeshDecomposition::decomposeMesh(), faMeshDistributor::distribute(), mapDistributeBase::distribute(), mapDistributeBase::distribute(), cell::edges(), extendedEdgeMesh::edgeTreesByType(), STLAsciiParse::endFacet(), fvExprDriver::evaluateVariableRemote(), ABAQUSCore::faceDecomposition(), NASCore::faceDecomposition(), polyMeshFilter::filter(), polyMeshFilter::filter(), polyMeshFilter::filterEdges(), distanceSurface::filterFaceProximity(), searchableDisk::findLine(), searchableSphere::findLine(), searchableSphere::findLineAll(), searchableSphere::findLineAny(), namesList< T >::findNames(), searchableDisk::findNearest(), searchableSphere::findNearest(), PstreamBuffers::finishedSends(), decomposedBlockData::gather(), decomposedBlockData::gatherSlaveData(), Foam::getAcceptableFunctionKeys(), FIRECore::getFireString(), fileOperation::getGlobalHostIORanks(), Foam::getHostGroupIds(), Foam::exprTools::getList(), distributedTriSurfaceMesh::getVolumeType(), searchableSphere::getVolumeType(), FaceCellWave< Type, TrackingData >::handleProcPatches(), if(), if(), if(), if(), ZoneMesh< ZoneType, MeshType >::indices(), faBoundaryMesh::indices(), polyBoundaryMesh::indices(), ZoneMesh< ZoneType, MeshType >::indices(), dynamicMultiMotionSolverFvMesh::init(), heatExchangerModel::initialise(), fluxSummary::initialiseFaceZone(), fluxSummary::initialiseFaceZoneAndDirection(), streamLineBase::initInterpolations(), Foam::inplaceReorder(), Foam::inplaceSubset(), Foam::inplaceSubset(), Foam::inplaceSubsetList(), Foam::inplaceSubsetMatchingStrings(), Foam::inplaceUniqueSort(), GAMGInterface::interfaceInternalField(), wallBoundedStreamLineParticle::interpolateFields(), regionModel::interRegionAMI(), topoBitSet::invert(), topoBoolSet::invert(), Foam::invertCellSelection(), Foam::invertManyToMany(), Foam::invertOneToMany(), isoSurfaceTopo::isoSurfaceTopo(), dictionary::keys(), cell::labels(), UPstream::listGatherValues(), triSurfaceLoader::load(), dlLibraryTable::loaded(), processorFaPatch::makeNonGlobalPatchPoints(), mapDistribute::mapDistributeBase(), mapDistribute::mapDistributeBase(), volSurfaceMapping::mapInternalToSurface(), reconstructedDistanceFunction::markCellsNearSurf(), PatchTools::matchEdges(), PatchTools::matchPoints(), debugWriter::mergeField(), surfaceWriter::mergeFieldTemplate(), triSurfaceTools::mergePoints(), globalIndex::mpiGather(), MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::MultiComponentPhaseModel(), multiSolidBodyMotionSolver::multiSolidBodyMotionSolver(), IOobjectList::namesImpl(), objectRegistry::namesImpl(), IOobjectList::namesTypeImpl(), objectRegistry::namesTypeImpl(), extendedEdgeMesh::nearestFeatureEdgeByType(), processorTopology::New(), faMeshTools::newMesh(), meshSearch::nonCoupledBoundaryTree(), MeshedSurface< Face >::nTriangles(), IOobjectList::objectsTypeImpl(), objectRegistry::objectsTypeImpl(), appendEqOp< T >::operator()(), CompactListList< T >::packImpl(), argList::parse(), ParticleHistogram< CloudType >::ParticleHistogram(), ParticlePostProcessing< CloudType >::ParticlePostProcessing(), sampledPatch::patchIDs(), cuttingSurfaceBase::performCut(), Foam::MatrixTools::pinv(), pointCells::pointCells(), primitiveMesh::pointCells(), polyBoundaryMesh::polyBoundaryMesh(), PtrDynList< Foam::Field< label > >::pop_back(), HeatTransferCoeff< CloudType >::postEvolve(), NusseltNumber< CloudType >::postEvolve(), ParticleDose< CloudType >::postEvolve(), WeberNumberReacting< CloudType >::postEvolve(), Foam::prependList(), Foam::printTable(), basicThermo::printThermoNames(), processorTopology::procAdjacency(), PtrListDictionary< T >::PtrListDictionary(), Reaction< ThermoType >::Reaction(), functionObjectList::read(), writeDictionary::read(), patchProbes::read(), limitHeight::read(), contactHeatFluxSource::read(), externalFileSource::read(), derivedFields::read(), surfaceFieldValue::read(), volFieldValue::read(), multiFieldValue::read(), dataCloud::read(), vtkCloud::read(), multiRegion::read(), velocityDampingConstraint::read(), FixedValueConstraint< Type >::read(), limitTurbulenceViscosity::read(), limitVelocity::read(), acousticDampingSource::read(), explicitPorositySource::read(), valueAverageBase::read(), sampledSurfaces::read(), multiphaseMangrovesSource::read(), multiphaseMangrovesTurbulenceModel::read(), NASedgeFormat::read(), ABAQUSsurfaceFormat< Face >::read(), GTSsurfaceFormat< Face >::read(), STARCDedgeFormat::read(), VTKedgeFormat::read(), boundaryMesh::read(), Foam::blockMeshTools::read(), dimensionSet::read(), Foam::readBlock(), dynamicRefineFvMesh::readDict(), Foam::readDir(), GeometricBoundaryField< Type, PatchField, GeoMesh >::readField(), masterUncollatedFileOperation::readHeader(), PtrList< T >::readIstream(), PackedList< Width >::readList(), CircularBuffer< T >::readList(), List< T >::readList(), lumpedPointState::readPlain(), masterUncollatedFileOperation::readStream(), functionEntry::readStringList(), surfaceNoise::readSurfaceData(), boundaryMesh::readTriSurface(), mapDistributeBase::receive(), searchableBox::regions(), searchableDisk::regions(), searchablePlate::regions(), searchableSphere::regions(), fvMeshTools::removeEmptyPatches(), seriesWriter::removeNewer(), Foam::renumber(), Foam::reorder(), vtmWriter::repair(), profilingPstream::report(), PtrDynList< T, SizeMin >::reserve(), fvMeshSubset::reset(), faFieldDecomposer::reset(), faMeshBoundaryHalo::reset(), fvFieldDecomposer::reset(), globalIndex::reset(), faFieldDecomposer::reset(), fvFieldDecomposer::reset(), pointFieldDecomposer::reset(), CompactListList< T >::resize(), CompactListList< T >::resize(), CompactListList< T >::resize(), lagrangianFieldDecomposer::fieldsCache::resize(), List< T >::resize(), CompactListList< T >::resize(), CompactListList< T >::resize_nocopy(), Foam::reverseList(), Foam::rotateList(), seriesWriter::scan(), ConstPrecisionAdaptor< Type, InputType, Container >::select(), triSurfaceLoader::select(), mapDistributeBase::send(), polyTopoChange::setCapacity(), faceSetOption::setFaceSelection(), removePoints::setRefinement(), meshCutter::setRefinement(), meshCutAndRemove::setRefinement(), edgeCollapser::setRefinement(), boundaryCutter::setRefinement(), PtrList< T >::setSize(), UnsortedMeshedSurface< Face >::setSize(), Foam::simpleGeometricFilter(), LUscalarMatrix::solve(), UnsortedMeshedSurface< Face >::sortedZones(), MeshedSurface< Face >::sortFacesAndStore(), Foam::stringOps::splitFunctionArgs(), basicThermo::splitThermoName(), MeshedSurface< Face >::stitchFaces(), hexRef8::storeData(), SHA1Digest::str(), streamLineParticle::streamLineParticle(), string::string_printf(), IndirectList< T >::subset(), IndirectList< T >::subset_if(), PatchTools::subsetMap(), Foam::subsetMatchingStrings(), syncTools::swapBoundaryCellList(), syncTools::swapBoundaryCellPositions(), masterUncollatedFileOperation::sync(), syncTools::syncPointMap(), HashTable< T, Key, Hash >::tocEntries(), HashTable< T, Key, Hash >::tocKeys(), faceAreaIntersect::triangulate(), MeshedSurface< Face >::triangulate(), mapDistributeBase::unionCombineMasks(), hashedWordList::uniq(), wordRes::uniq(), IndirectList< T >::uniq(), wordRes::uniq(), PrimitivePatch< FaceList, PointField >::uniqBoundaryFaces(), sampledFaceZone::update(), sampledPatch::update(), writerCaching::update(), faMesh::updateMesh(), cellZoneSet::updateMesh(), pointZoneSet::updateMesh(), polyMesh::updateMesh(), lduPrimitiveMesh::upperTriOrder(), string::validate(), Foam::stringOps::validate(), volBSplinesBase::volBSplinesBase(), cuttingSurfaceBase::walkCellCuts(), wallBoundedStreamLineParticle::wallBoundedStreamLineParticle(), ensightCase::options::width(), multiFieldValue::write(), vtkWrite::write(), ParticleZoneInfo< CloudType >::write(), ensightFaces::write(), decomposedBlockData::writeBlocks(), profiling::writeData(), streamLineBase::writeToFile(), zoneToCell::zones(), zoneToFace::zones(), zoneToPoint::zones(), faceZoneToCell::zones(), zoneToCell::zones(), zoneToFace::zones(), and zoneToPoint::zones().
emplace_back()
template<class T > template<class... Args> T & emplace_back (Args &&... args) inline
Definition at line 97 of file PtrListI.H.
Referenced by AABBTree< Type >::AABBTree(), dynamicCode::addCreateFile(), Foam::PstreamDetail::allToAllConsensus(), Foam::PstreamDetail::allToAllConsensus(), ZoneMesh< ZoneType, MeshType >::cfindZone(), AABBTree< Type >::createBoxes(), Foam::PstreamDetail::exchangeConsensus(), Foam::PstreamDetail::exchangeConsensus(), ZoneMesh< ZoneType, MeshType >::findZoneID(), for(), Foam::getEdge(), dynamicIndexedOctree< Type >::insert(), dynamicIndexedOctree< Type >::insertIndex(), streamLineParticle::move(), wallBoundedStreamLineParticle::move(), streamLineBase::storePoint(), streamLineBase::trimToBox(), and streamLineBase::trimToBox().
push_back() [1/7]
template<class T > void push_back (T * ptr) inline
Definition at line 106 of file PtrListI.H.
References UPtrList< T >::push_back().
Referenced by AABBTree< Type >::AABBTree(), dynamicCode::addCompileFile(), dynamicCode::addCopyFile(), UPstream::allocateInterHostCommunicator(), UPstream::allocateIntraHostCommunicator(), PtrList< T >::append(), PtrList< T >::append(), dlLibraryTable::append(), PtrList< T >::append(), PtrList< T >::append(), PtrList< T >::append(), PtrList< T >::append(), PtrList< T >::append(), directMethod::appendToDirectSeeds(), UPtrList< CloudFunctionObject< CloudType > >::back(), Foam::meshTools::bandCompression(), profiling::beginTimer(), cellVolumeWeightMethod::calculateAddressing(), correctedCellVolumeWeightMethod::calculateAddressing(), primitiveMesh::cellCells(), primitiveMesh::cellEdges(), primitiveMesh::cellPoints(), commSchedule::commSchedule(), profiling::create(), AABBTree< Type >::createBoxes(), primitiveMesh::edgeCells(), Pstream::exchange(), Pstream::exchange(), ifeqEntry::execute(), ifeqEntry::execute(), primitiveMesh::faceEdges(), mapNearestMethod::findMappedSrcCell(), mapNearestMethod::findNearestCell(), PstreamBuffers::finishedSends(), UPtrList< CloudFunctionObject< CloudType > >::front(), Foam::getEdge(), fileOperation::getGlobalHostIORanks(), Foam::getHostGroupIds(), Foam::getSelectedProcs(), FaceCellWave< Type, TrackingData >::handleExplicitConnections(), indexedOctree< Type >::indexedOctree(), processorTopology::New(), Reaction< ThermoType >::New(), csvTableReader< Type >::operator()(), OppositeFaceCellWave< Type, TrackingData >::opposingFaceLabels(), primitiveMesh::pointCells(), primitiveMesh::pointPoints(), Foam::polyMeshZipUpCells(), fileOperation::printRanks(), faceAreaWeightAMI::processSourceFace(), Foam::PstreamGlobals::push_request(), masterUncollatedFileOperation::read(), ensightSurfaceReader::readCase(), ensightSurfaceReader::readGeometry(), PackedList< Width >::readList(), LList< LListBase, T >::readList(), distributedDILUPreconditioner::receive(), dynamicIndexedOctree< Type >::removeIndex(), UPstream::commsStruct::reset(), dynamicCode::resolveTemplates(), distributedDILUPreconditioner::send(), PatchEdgeFaceWave< PrimitivePatchType, Type, TrackingData >::setEdgeInfo(), PointEdgeWave< Type, TrackingData >::setPointInfo(), data::setSolverPerformance(), Foam::stringOps::splitFunctionArgs(), streamLineBase::storePoint(), exprResultDelayed::storeValue(), syncTools::syncEdgeMap(), syncTools::syncPointMap(), UILList< LListBase, T >::UILList(), FaceCellWave< Type, TrackingData >::updateCell(), FaceCellWave< Type, int >::updateFace(), FaceCellWave< Type, TrackingData >::updateFace(), OTstream::write(), OTstream::write(), OTstream::write(), OTstream::write(), OTstream::write(), OTstream::write(), OTstream::write(), OTstream::write(), OTstream::writeQuoted(), and ZoneMesh< pointZone, polyMesh >::ZoneMesh().
push_back() [2/7]
template<class T > void push_back (std::unique_ptr< T > && ptr) inline
Definition at line 113 of file PtrListI.H.
References UPtrList< T >::push_back().
push_back() [3/7]
template<class T > void push_back (autoPtr< T > && ptr) inline
Definition at line 120 of file PtrListI.H.
References UPtrList< T >::push_back().
push_back() [4/7]
template<class T > void push_back (const refPtr< T > & ptr) inline
Definition at line 127 of file PtrListI.H.
References UPtrList< T >::push_back().
push_back() [5/7]
template<class T > void push_back (const tmp< T > & ptr) inline
Definition at line 134 of file PtrListI.H.
push_back() [6/7]
template<class T > void push_back (PtrList< T > && other) inline
Definition at line 141 of file PtrListI.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
emplace_set()
template<class T > template<class... Args> T & emplace_set (const label i, Args &&... args) inline
Definition at line 166 of file PtrListI.H.
References args, and T.
Referenced by Foam::shallowCloneFunctions().
emplace()
template<class T > template<class... Args> T & emplace (const label i, Args &&... args) inline
Definition at line 176 of file PtrListI.H.
References args, and T.
Referenced by ABAQUSCore::abaqusToFoamFaceAddr(), Pstream::exchangeSizes(), zoneDistribute::getFields(), HashSet< Key, Hash >::insert(), and HashSet< Key, Hash >::set().
set() [2/7]
template<class T > Foam::autoPtr< T > set (const label i, T * ptr) inline
Definition at line 185 of file PtrListI.H.
set() [3/7]
template<class T > Foam::autoPtr< T > set (const label i, std::unique_ptr< T > && ptr) inline
Definition at line 196 of file PtrListI.H.
set() [4/7]
template<class T > Foam::autoPtr< T > set (const label i, autoPtr< T > && ptr) inline
Definition at line 207 of file PtrListI.H.
set() [5/7]
template<class T > Foam::autoPtr< T > set (const label i, const refPtr< T > & ptr) inline
Definition at line 218 of file PtrListI.H.
set() [6/7]
template<class T > Foam::autoPtr< T > set (const label i, const tmp< T > & ptr) inline
Definition at line 229 of file PtrListI.H.
release()
template<class T > Foam::autoPtr< T > release (const label i) inline
Definition at line 240 of file PtrListI.H.
Referenced by PtrList< T >::append(), objectRegistry::cacheTemporaryObject(), fileOperation::fileHandler(), HashPtrTable< IOobject >::get(), HashPtrTable< T, Key, Hash >::insert(), PtrList< CloudFunctionObject< CloudType > >::operator=(), fvExpressionField::performAction(), PtrDynList< T, SizeMin >::push_back(), PtrDynList< T, SizeMin >::push_back(), sampledSurfaces::read(), STLCore::readBinaryHeader(), ifstreamPointer::release(), ofstreamPointer::release(), HashPtrTable< T, Key, Hash >::set(), HashPtrTable< T, Key, Hash >::set(), PtrDynList< T, SizeMin >::set(), PtrDynList< T, SizeMin >::set(), PtrList< T >::set(), PtrDynList< T, SizeMin >::set(), regIOobject::store(), regIOobject::store(), and PtrList< CloudFunctionObject< CloudType > >::transfer().
transfer()
template<class T > void transfer (PtrList< T > & list) inline
Definition at line 252 of file PtrListI.H.
References UPtrList< T >::transfer().
Referenced by extendedEdgeMesh::add(), geometric::add(), faMesh::addFaPatches(), polyMesh::addPatches(), cellZoneSet::addSet(), pointZoneSet::addSet(), extendedEdgeMesh::allNearestFeatureEdges(), extendedEdgeMesh::allNearestFeaturePoints(), setToCellZone::applyToSet(), cellToFaceZone::applyToSet(), faceZoneToFaceZone::applyToSet(), searchableSurfaceToFaceZone::applyToSet(), setAndNormalToFaceZone::applyToSet(), setsToFaceZone::applyToSet(), setToFaceZone::applyToSet(), setToPointZone::applyToSet(), extendedEdgeMesh::autoMap(), PDRblock::blockMeshDict(), enrichedPatch::calcEnrichedFaces(), createShellMesh::calcPointRegions(), faceAreaWeightAMI::calculate(), faceAreaWeightAMI2D::calculate(), extractEulerianParticles::calculateAddressing(), primitiveMesh::checkEdgeLength(), removeFaces::compatibleRemoves(), mappedPatchBase::constructIOField(), wallDistData< TransferType >::correct(), fvMeshSubsetProxy::correct(), meshWave::correct(), directionalMeshWave::correct(), meshWave::correct(), inverseDistance::createStencil(), curvatureSeparation::curvatureSeparation(), extendedEdgeMesh::cut(), cyclicACMIGAMGInterface::cyclicACMIGAMGInterface(), cyclicAMIGAMGInterface::cyclicAMIGAMGInterface(), fvMeshDistribute::distribute(), mapDistributeBase::distribute(), mapDistributeBase::distribute(), pointNoise::filterTimeData(), searchableBox::findLineAll(), searchableRotatedBox::findLineAll(), triSurfaceSearch::findLineAll(), distributedTriSurfaceMesh::findNearest(), extendedEdgeMesh::flipNormals(), globalIndex::gather(), globalIndex::gatherInplace(), fileOperation::getGlobalHostIORanks(), Foam::getSelectedProcs(), globalIndex::globalIndex(), InjectedParticleDistributionInjection< CloudType >::initialise(), InjectedParticleInjection< CloudType >::initialise(), Foam::inplaceMapKey(), Foam::inplaceReorder(), Foam::inplaceUniqueSort(), IOPtrList< T >::IOPtrList(), lduPrimitiveMesh::lduPrimitiveMesh(), triSurfaceLoader::load(), voxelMeshSearch::makeMesh(), mappedPatchFieldBase< Type >::mappedField(), triSurface::markZone(), PatchTools::markZone(), momentOfInertia::massPropertiesPatch(), polyBoundaryMesh::matchGroups(), cellToCellStencil::merge(), cellToFaceStencil::merge(), globalIndex::mpiGatherInplace(), globalIndex::mpiGatherInplaceOp(), oversetFvMeshBase::normalisation(), noiseFFT::octaveBandInfo(), CompactListList< T >::operator=(), GeometricField< Type, PatchField, GeoMesh >::operator=(), FieldField< Field, Type >::operator=(), UPtrList< T >::operator=(), GAMGAgglomeration::procAgglomerateRestrictAddressing(), functionObjectList::read(), solutionControl::read(), sampledSurfaces::read(), IATE::read(), NASedgeFormat::read(), ABAQUSsurfaceFormat< Face >::read(), NASsurfaceFormat< Face >::read(), OBJsurfaceFormat< Face >::read(), STLsurfaceFormat< Face >::read(), TRIsurfaceFormat< Face >::read(), OBJedgeFormat::read(), STARCDedgeFormat::read(), ensightSurfaceReader::readCase(), ensightSurfaceReader::readGeometry(), CircularBuffer< T >::readList(), List< T >::readList(), UList< T >::readList(), STARCDCore::readPoints(), FIREMeshReader::readSelections(), surfMesh::readUpdate(), dynamicRefineFvMesh::refine(), searchableSurfaceCollection::regions(), edgeMesh::regions(), surfMesh::releaseGeom(), cuttingSurfaceBase::remapFaces(), UnsortedMeshedSurface< Face >::remapFaces(), edgeIntersections::removeDegenerates(), dynamicIndexedOctree< Type >::removeIndex(), UPtrList< T >::reorder(), BiIndirectList< T >::resetAddressing(), motionSmootherAlgo::scaleMesh(), noiseModel::setOctaveBands(), box::setRefineFlags(), hexRef8::setRefinement(), createShellMesh::setRefinement(), removePoints::setUnrefinement(), graph::setXRange(), oversetFvMeshBase::solveOverset(), MeshedSurface< Face >::sortFacesAndStore(), UPtrList< T >::sortOrder(), extendedEdgeMesh::sortPointsAndEdges(), streamLineParticle::streamLineParticle(), hexRef8::subset(), cellZoneSet::subset(), pointZoneSet::subset(), cellZoneSet::subtractSet(), pointZoneSet::subtractSet(), faceZoneSet::sync(), MeshedSurface< Face >::transcribe(), CompactListList< T >::transfer(), edgeMesh::transfer(), extendedEdgeMesh::transfer(), mapDistributeBase::transfer(), mapDistributePolyMesh::transfer(), PackedList< Width >::transfer(), PtrDynList< T, SizeMin >::transfer(), MeshedSurface< Face >::transfer(), incompressibleVars::transfer(), MeshedSurface< Face >::triangulate(), dynamicRefineFvMesh::unrefine(), cellVolumeWeight::update(), inverseDistance::update(), trackingInverseDistance::update(), mappedFixedInternalValueFvPatchField< Type >::updateCoeffs(), mappedVelocityFluxFixedValueFvPatchField::updateCoeffs(), polyMesh::updateGeomPoints(), meshRefinement::updateList(), boundaryCutter::updateMesh(), meshCutAndRemove::updateMesh(), meshCutter::updateMesh(), externalDisplacementMeshMover::updateMesh(), localPointRegion::updateMesh(), probes::updateMesh(), meshRefinement::updateMesh(), addPatchCellLayer::updateMesh(), hexRef8::updateMesh(), cellZoneSet::updateMesh(), faceZoneSet::updateMesh(), pointZoneSet::updateMesh(), solverFieldSelection::updateSelection(), UPtrList< CloudFunctionObject< CloudType > >::UPtrList(), Sampled< Type >::value(), cellCellStencil::walkFront(), processorColour::walkFront(), wallBoundedStreamLineParticle::wallBoundedStreamLineParticle(), areaWrite::write(), and streamLineBase::writeToFile().
operator=() [1/2]
template<class T > void operator= (const PtrList< T > & list)
Definition at line 125 of file PtrList.C.
References resize(), and UPtrList< T >::size().
Referenced by MatrixSpace< BarycentricTensor< Cmpt >, Cmpt, 4, 3 >::operator&=(), IOPtrList< T >::operator=(), PtrDynList< T, SizeMin >::operator=(), PtrDynList< T, SizeMin >::operator=(), PtrDynList< T, SizeMin >::operator=(), HashSet< Key, Hash >::operator=(), and HashSet< Key, Hash >::operator=().
operator=() [2/2]
template<class T > void operator= (PtrList< T > && list) inline
Definition at line 267 of file PtrListI.H.
push_back() [7/7]
template<class T > void push_back (autoPtr< T > & ptr) delete
set() [7/7]
template<class T > autoPtr< T > set (const label i, autoPtr< T > & ptr) inline
Definition at line 226 of file PtrList.H.
References PtrList< T >::release(), and PtrList< T >::set().
setSize()
template<class T > void setSize (const label newLen) inline
Definition at line 232 of file PtrList.H.
References PtrList< T >::resize().
Referenced by isoSurfacePoint::adaptPatchFields(), refinementHistory::add(), fvMeshAdder::add(), preserveBaffles::add(), preserveFaceZones::add(), fvMeshAdder::add(), polyMeshAdder::add(), fvMeshPrimitiveLduAddressing::addAddressing(), cyclicAMIPolyPatch::addAMIFaces(), surfaceZonesInfo::addCellZone(), cellTable::addCellZones(), sixDoFRigidBodyMotion::addConstraints(), addPatchCellLayer::addedCells(), mapPatchChange::addedPatches(), surfaceZonesInfo::addFaceZone(), surfaceZonesInfo::addFaceZonesToMesh(), lduPrimitiveMesh::addInterfaces(), oversetFvMeshBase::addInterpolation(), edgeSurface::addIntersectionEdges(), snappyLayerDriver::addLayers(), snappyLayerDriver::addLayers(), boundaryMesh::addPatch(), meshRefinement::addPointZone(), sixDoFRigidBodyMotion::addRestraints(), interRegionExplicitPorositySource::addSup(), interRegionExplicitPorositySource::addSup(), adjointSolverManager::adjointSolverManager(), AMIInterpolation::agglomerate(), GAMGAgglomeration::agglomerateLduAddressing(), meshRefinement::appendPatch(), face::areaInContact(), sensitivitySurfacePoints::assembleSensitivities(), FreeStream< CloudType >::autoMap(), extendedEdgeMesh::autoMap(), meshRefinement::baffleAndSplitMesh(), meshRefinement::balance(), binned::binned(), searchableBox::boundingSpheres(), searchableCone::boundingSpheres(), searchableCylinder::boundingSpheres(), searchableExtrudedCircle::boundingSpheres(), searchableSurfaceCollection::boundingSpheres(), triSurfaceMesh::boundingSpheres(), KinematicCloud< CloudType >::buildCellOccupancy(), nearWallFields::calcAddressing(), highAspectRatioFvGeometryScheme::calcAspectRatioWeights(), decompositionMethod::calcCellCells(), decompositionMethod::calcCellCells(), primitiveMesh::calcCells(), addPatchCellLayer::calcExtrudeInfo(), cellToFaceStencil::calcFaceStencil(), CentredFitSnGradData< Polynomial >::calcFit(), triSurfaceTools::calcInterpolationWeights(), createShellMesh::calcPointRegions(), surfaceNoise::calculate(), waveMethod::calculate(), faceAreaWeightAMI2D::calculate(), waveMethod::calculate(), correctedCellVolumeWeightMethod::calculate(), meshRefinement::calculateEdgeWeights(), GAMGAgglomeration::calculateRegionMaster(), nutUSpaldingWallFunctionFvPatchScalarField::calcUTau(), pointMVCWeight::calcWeights(), primitiveMeshTools::cellClosedness(), cellMatcher::cellMatcher(), fvMotionSolver::cellMotionBoundaryTypes(), boundaryMesh::changeFaces(), GAMGAgglomeration::checkRestriction(), refinementHistory::clone(), extendedCellToFaceStencil::collectData(), extendedFaceToCellStencil::collectData(), holeToFace::combine(), GAMGAgglomeration::compactLevels(), removeFaces::compatibleRemoves(), NURBS3DVolume::computeParametricCoordinates(), nearWallDistNoSearch::correct(), inverseFaceDistanceDiffusivity::correct(), inversePointDistanceDiffusivity::correct(), removePoints::countPointUsage(), epsilonWallFunctionFvPatchScalarField::createAveragingWeights(), omegaWallFunctionFvPatchScalarField::createAveragingWeights(), nearWallFields::createFields(), meshRefinement::createZoneBaffles(), motionSmootherAlgo::curPoints(), geomCellLooper::cut(), faMeshDecomposition::decomposeMesh(), triSurfaceTools::delaunay2D(), mapPatchChange::deletedPatches(), meshRefinement::directionalRefineCandidates(), fvMeshDistribute::distribute(), mapDistributeBase::distribute(), mappedPatchFieldBase< Type >::distribute(), distributedDILUPreconditioner::distributedDILUPreconditioner(), snappySnapDriver::doSnap(), electrostaticDepositionFvPatchScalarField::electrostaticDepositionFvPatchScalarField(), energyTransport::energyTransport(), mapDistributeBase::exchangeAddressing(), mapDistributeBase::exchangeAddressing(), primitiveMesh::faceEdges(), FaceInteraction< CloudType >::FaceInteraction(), blockDescriptor::facePoints(), FacePostProcessing< CloudType >::FacePostProcessing(), primitiveMeshTools::facePyramidVolume(), refinementSurfaces::findAllIntersections(), refinementSurfaces::findAllIntersections(), searchableSurfacesQueries::findAllIntersections(), searchableSurfacesQueries::findAnyIntersection(), shellSurfaces::findDirectionalLevel(), shellSurfaces::findHigherGapLevel(), refinementSurfaces::findHigherIntersection(), refinementSurfaces::findInside(), shellSurfaces::findLevel(), searchableBox::findLine(), searchableCone::findLine(), searchableCylinder::findLine(), searchablePlane::findLine(), searchablePlate::findLine(), searchableRotatedBox::findLine(), searchableSurfaceCollection::findLine(), searchableSurfaceWithGaps::findLine(), triSurfaceSearch::findLine(), searchableBox::findLineAll(), searchableCone::findLineAll(), searchableCylinder::findLineAll(), searchableDisk::findLineAll(), searchablePlane::findLineAll(), searchablePlate::findLineAll(), searchableRotatedBox::findLineAll(), searchableSurfaceCollection::findLineAll(), searchableSurfaceWithGaps::findLineAll(), distributedTriSurfaceMesh::findLineAll(), searchableBox::findLineAny(), searchableCone::findLineAny(), searchableCylinder::findLineAny(), searchableRotatedBox::findLineAny(), triSurfaceSearch::findLineAny(), mappedPatchBase::findLocalSamples(), searchableBox::findNearest(), searchableCone::findNearest(), searchableCylinder::findNearest(), searchableExtrudedCircle::findNearest(), searchablePlane::findNearest(), searchablePlate::findNearest(), searchableRotatedBox::findNearest(), distributedTriSurfaceMesh::findNearest(), triSurfaceRegionSearch::findNearest(), triSurfaceSearch::findNearest(), searchableSurfacesQueries::findNearest(), searchableSurfacesQueries::findNearest(), searchableSurfacesQueries::findNearest(), refinementFeatures::findNearestEdge(), refinementSurfaces::findNearestIntersection(), refinementSurfaces::findNearestIntersection(), refinementSurfaces::findNearestIntersection(), refinementSurfaces::findNearestIntersection(), searchableSurfacesQueries::findNearestIntersection(), refinementFeatures::findNearestPoint(), refinementSurfaces::findNearestRegion(), refinementSurfaces::findNearestRegion(), refinementSurfaces::findNearestRegion(), refinementFeatures::findNearestRegionEdge(), searchableExtrudedCircle::findParametricNearest(), mappedPatchBase::findSamples(), polyMeshAdder::findSharedPoints(), FreeStream< CloudType >::FreeStream(), GAMGAgglomeration::GAMGAgglomeration(), decomposedBlockData::gather(), lduPrimitiveMesh::gather(), externalCoupled::gatherAndCombine(), combineFaces::getMergeSets(), decompositionConstraint::getMinBoundaryValue(), surfaceZonesInfo::getNamedSurfaces(), searchablePlane::getNormal(), boundaryMesh::getNTris(), weightedPosition::getPoints(), surfaceZonesInfo::getStandaloneNamedSurfaces(), surfaceZonesInfo::getUnclosedNamedSurfaces(), surfaceZonesInfo::getUnnamedSurfaces(), removePoints::getUnrefimentSet(), cellLooper::getVertEdgesNonFace(), triSurfaceTools::getVertexTriangles(), cellLooper::getVertFacesNonEdge(), distributedTriSurfaceMesh::getVolumeType(), searchableCone::getVolumeType(), searchableCylinder::getVolumeType(), triSurfaceMesh::getVolumeType(), meshRefinement::getZoneFaces(), cellCellStencil::globalCellCells(), addPatchCellLayer::globalEdgeFaces(), chemPointISAT< CompType, ThermoType >::grow(), inverseDistance::holeExtrapolationStencil(), Distribution< Type >::index(), LocalInteraction< CloudType >::info(), RecycleInteraction< CloudType >::info(), StandardWallInteraction< CloudType >::info(), dynamicMotionSolverListFvMesh::init(), interRegionExplicitPorositySource::initialise(), InjectedParticleDistributionInjection< CloudType >::initialise(), viewFactor::initialise(), meshToMeshMethod::initialise(), waveMakerPointPatchVectorField::initialiseGeometry(), waveModel::initialiseGeometry(), fluxSummary::initialiseSurfaceAndDirection(), InjectedParticleDistributionInjection< CloudType >::InjectedParticleDistributionInjection(), AMIInterpolation::interpolateToSource(), AMIInterpolation::interpolateToTarget(), interpolationLookUpTable< scalar >::interpolationLookUpTable(), cellZoneSet::invert(), faceZoneSet::invert(), pointZoneSet::invert(), isoSurfaceCell::isoSurfaceCell(), isoSurfacePoint::isoSurfacePoint(), lduPrimitiveMesh::lduPrimitiveMesh(), liquidMixtureProperties::liquidMixtureProperties(), LocalInteraction< CloudType >::LocalInteraction(), distributedTriSurfaceMesh::localQueries(), averageNeighbourFvGeometryScheme::makePyrHeights(), cyclicACMIPolyPatch::mapCollocatedFaces(), fvMatrix< Type >::mapContributions(), fvMeshAdder::MapDimField(), mapDistribute::mapDistribute(), mapDistribute::mapDistribute(), mappedPatchFieldBase< Type >::mappedField(), fvMeshAdder::MapSurfaceField(), fvMeshAdder::MapVolField(), inverseDistance::markDonors(), trackingInverseDistance::markDonors(), boundaryMesh::markFaces(), meshRefinement::markOutsideFaces(), Foam::matchPoints(), Foam::matchPoints(), edgeIntersections::merge(), cellToCellStencil::merge(), cellToFaceStencil::merge(), zoneCellStencils::merge(), meshRefinement::mergeBaffles(), edgeMesh::mergeEdges(), surfaceIntersection::mergeEdges(), meshRefinement::mergePatchFaces(), meshRefinement::mergePatchFacesUndo(), globalMeshData::mergePoints(), globalMeshData::mergePoints(), fileOperation::mergeTimes(), moleFractions< ThermoType >::moleFractions(), engineValve::movingPatchIDs(), MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::MultiComponentPhaseModel(), extendedEdgeMesh::nearestFeatureEdge(), surfaceFeatures::nearestSurfEdge(), surfaceFeatures::nearestSurfEdge(), cellCuts::nonAnchorPoints(), Distribution< Type >::normalised(), AMIInterpolation::normaliseWeights(), objectiveManager::objectiveManager(), listPlusEqOp< T >::operator()(), globalMeshData::ListPlusEqOp< T >::operator()(), optimisationManager::optimisationManager(), cyclicAMIPolyPatch::order(), cyclicPolyPatch::order(), oldCyclicPolyPatch::order(), processorPolyPatch::order(), outletMappedUniformInletFvPatchField< Type >::outletMappedUniformInletFvPatchField(), distributedTriSurfaceMesh::overlappingSurface(), polyMeshAdder::patchFacePairs(), pointFieldReconstructor::pointFieldReconstructor(), PatchTools::pointNormals(), polyMesh::polyMesh(), polyMesh::polyMesh(), Foam::polyMeshZipUpCells(), powerLawLopesdaCostaZone::powerLawLopesdaCostaZone(), Foam::preservePatchTypes(), singleDirectionUniformBin::processField(), uniformBin::processField(), procLduMatrix::procLduMatrix(), polyMeshAdder::procPatchPairs(), Distribution< Type >::raw(), regIOobject::read(), Curle::read(), noiseModel::read(), multiMotion::read(), STLsurfaceFormat< Face >::read(), TRIsurfaceFormat< Face >::read(), OBJedgeFormat::read(), STARCDMeshReader::readBoundary(), STARCDMeshReader::readCells(), reader::readField(), STARCDMeshReader::readPoints(), FIREMeshReader::readSelections(), polyMesh::readUpdate(), lagrangianReconstructor::reconstructField(), lagrangianReconstructor::reconstructFieldField(), RecycleInteraction< CloudType >::RecycleInteraction(), DAC< CompType, ThermoType >::reduceMechanism(), DRG< CompType, ThermoType >::reduceMechanism(), DRGEP< CompType, ThermoType >::reduceMechanism(), EFA< CompType, ThermoType >::reduceMechanism(), PFA< CompType, ThermoType >::reduceMechanism(), meshRefinement::refineCandidates(), refinementHistory::refinementHistory(), refinementSurfaces::refinementSurfaces(), searchableCone::regions(), searchableCylinder::regions(), searchableExtrudedCircle::regions(), searchablePlane::regions(), searchableSurfaceCollection::regions(), triSurfaceMesh::regions(), edgeMesh::regions(), edgeIntersections::removeDegenerates(), RemoveParcels< CloudType >::RemoveParcels(), FIREMeshReader::reorganize(), fvMeshSubset::reset(), logFiles::resetNames(), searchableSurfaceCollection::searchableSurfaceCollection(), searchableSurfaces::searchableSurfaces(), meshRefinement::selectIntersectedFaces(), distributedDILUPreconditioner::sendGlobal(), uniformBin::setBinsAddressing(), fvMatrix< Type >::setBounAndInterCoeffs(), decompositionMethod::setConstraints(), boundaryMesh::setFeatureEdges(), surfaceFeatures::setFromStatus(), pairPotential::setLookupTables(), weightedPosition::setPoints(), box::setRefineFlags(), removePoints::setRefinement(), tetDecomposer::setRefinement(), addPatchCellLayer::setRefinement(), hexRef8::setRefinement(), combineFaces::setRefinement(), refinementIterator::setRefinement(), duplicatePoints::setRefinement(), propellerInfo::setSampleDiskGeometry(), molecule::setSiteSizes(), removePoints::setUnrefinement(), shellSurfaces::shellSurfaces(), searchableSurfacesQueries::signedDistance(), solidMixtureProperties::solidMixtureProperties(), oversetFvMeshBase::solveOverset(), ParSortableList< Type >::sort(), extendedEdgeMesh::sortedOrder(), extendedEdgeMesh::sortPointsAndEdges(), meshRefinement::splitFacesUndo(), meshRefinement::splitMeshRegions(), StandardWallInteraction< CloudType >::StandardWallInteraction(), oversetFvPatchField< Type >::storeFringeCoefficients(), thermoSingleLayer::thermoSingleLayer(), trackingInverseDistance::trackingInverseDistance(), fvMatrix< Type >::transferFvMatrixCoeffs(), globalIndexAndTransform::transformIndicesForPatches(), triSurfaceRegionSearch::treeByRegion(), face::triangles(), boundaryMesh::triangulate(), triSurfaceTools::triangulate(), triSurfaceTools::triangulate(), triSurfaceTools::triangulateFaceCentre(), boundaryMesh::triangulateLocal(), advancingFrontAMI::triangulatePatch(), triSurface::triFaceFaces(), streamLineBase::trimToBox(), inverseDistance::update(), trackingInverseDistance::update(), voxelMeshSearch::update(), lduPrimitiveMeshAssembly::update(), oversetFvMeshBase::updateAddressing(), turbulentTemperatureRadCoupledMixedFvPatchScalarField::updateCoeffs(), patchEdgeFaceRegions::updateEdge(), patchEdgeFaceRegions::updateEdge(), patchEdgeFaceRegions::updateFace(), optimisationType::updateGradientsAndValues(), edgeVertex::updateLabels(), lduPrimitiveMeshAssembly::updateMaps(), faGlobalMeshData::updateMesh(), boundaryCutter::updateMesh(), removePoints::updateMesh(), faMesh::updateMesh(), addPatchCellLayer::updateMesh(), faceZoneSet::updateMesh(), faceZone::updateMesh(), cellToCellStencil::validBoundaryFaces(), cellToFaceStencil::validBoundaryFaces(), zoneCellStencils::validBoundaryFaces(), Sampled< Type >::value(), WallLocalSpringSliderDashpot< CloudType >::WallLocalSpringSliderDashpot(), meshRefinement::weightedSum(), OFstreamCollator::write(), updateMethod::writeCorrection(), cellZoneSet::writeObject(), faceZoneSet::writeObject(), pointZoneSet::writeObject(), and streamLineBase::writeToFile().
append() [1/7]
template<class T > void append (autoPtr< T > & ptr) inline
Definition at line 236 of file PtrList.H.
References PtrList< T >::push_back(), and PtrList< T >::release().
Referenced by extendedEdgeMesh::add(), singleProcessorFaceSets::add(), ISAT< CompType, ThermoType >::add(), vtmWriter::add(), argList::addArgument(), polyTopoChange::addCell(), cellTable::addCellZones(), mesh::addColour(), polyTopoChange::addFace(), mesh::addField(), fvMatrix< Type >::addFvMatrix(), argList::addNote(), polyTopoChange::addPoint(), cellZoneSet::addSet(), faceZoneSet::addSet(), pointZoneSet::addSet(), animation::addTranslation(), STLAsciiParse::addVertexComponent(), regIOobject::addWatch(), unwatchedIOdictionary::addWatch(), regIOobject::addWatch(), fileOperation::addWatches(), masterUncollatedFileOperation::addWatches(), AMIInterpolation::agglomerate(), extendedEdgeMesh::allNearestFeatureEdges(), extendedEdgeMesh::allNearestFeaturePoints(), AMIInterpolation::append(), PDRblock::gridControl::append(), codedBase::append(), vtmWriter::append(), vtmWriter::append(), advancingFrontAMI::appendNbrFaces(), Foam::appendTriLabels(), setToCellZone::applyToSet(), normalToFace::applyToSet(), cellToFaceZone::applyToSet(), faceZoneToFaceZone::applyToSet(), searchableSurfaceToFaceZone::applyToSet(), setAndNormalToFaceZone::applyToSet(), setsToFaceZone::applyToSet(), setToFaceZone::applyToSet(), setToPointZone::applyToSet(), extendedEdgeMesh::autoMap(), vtmWriter::beginBlock(), meshRefinement::blockLeakFaces(), PDRblock::blockMeshDict(), KinematicCloud< CloudType >::buildCellOccupancy(), faceAreaWeightAMI::calcAddressing(), holeToFace::calcClosure(), enrichedPatch::calcEnrichedFaces(), polyDualMesh::calcFeatures(), cutCell::calcIsoFacePointsFromEdges(), mappedPatchBase::calcMapping(), faPatch::calcPointEdges(), faPatch::calcPointLabels(), createShellMesh::calcPointRegions(), cutCellIso::calcSubCell(), cutCellPLIC::calcSubCell(), cutFace::calcSubFace(), cutFaceAdvect::calcSubFace(), cutFaceIso::calcSubFace(), cutFace::calcSubFace(), cutFace::calcSubFace(), cutFaceAdvect::calcSubFace(), cutFacePLIC::calcSubFace(), viewFactor::calculate(), waveMethod::calculate(), valueAverageBase::calculate(), cellVolumeWeightMethod::calculateAddressing(), directMethod::calculateAddressing(), mapNearestMethod::calculateAddressing(), correctedCellVolumeWeightMethod::calculateAddressing(), calculatedProcessorGAMGInterface::calculatedProcessorGAMGInterface(), processorColour::cellColour(), polyMeshTetDecomposition::cellTetIndices(), edgeCollapser::checkBadFaces(), Callback< CallbackType >::checkIn(), searchableSurfaces::checkIntersection(), GAMGAgglomeration::checkRestriction(), refinementHistory::clone(), collectLibsCallback(), CollisionRecordList< PairType, WallType >::CollisionRecordList(), processorColour::colour(), triSurface::compactPoints(), removeFaces::compatibleRemoves(), hexRef8::consistentSlowRefinement(), hexRef8::consistentSlowRefinement2(), patchPatchDist::correct(), daughterSizeDistributionModel::correct(), RecycleInteraction< CloudType >::correct(), List< Type >::create(), epsilonWallFunctionFvPatchScalarField::createAveragingWeights(), omegaWallFunctionFvPatchScalarField::createAveragingWeights(), box::createMap(), inverseDistance::createStencil(), curvatureSeparation::curvatureSeparation(), geomCellLooper::cut(), extendedEdgeMesh::cut(), cutFaceAdvect::cutPoints(), cutFaceAdvect::cutPoints(), cyclicACMIGAMGInterface::cyclicACMIGAMGInterface(), cyclicAMIGAMGInterface::cyclicAMIGAMGInterface(), cyclicGAMGInterface::cyclicGAMGInterface(), faMeshDecomposition::decomposeMesh(), refinementHistory::distribute(), Foam::dlLoaded(), snappyLayerDriver::doLayers(), box::doRefineBoxes(), snappySnapDriver::doSnap(), extendedEdgeMesh::edgeBaffles(), primitiveMesh::edgeFaces(), edgeSurface::edgeSurface(), STLAsciiParse::endFacet(), ddt2::execute(), zeroGradient::execute(), runTimeControl::execute(), extendedUpwindCellToFaceStencil::extendedUpwindCellToFaceStencil(), extendedUpwindCellToFaceStencil::extendedUpwindCellToFaceStencil(), FaceInteraction< CloudType >::FaceInteraction(), FacePostProcessing< CloudType >::FacePostProcessing(), boundaryRadiationProperties::faceZoneIds(), pointNoise::filterTimeData(), voxelMeshSearch::findCell(), shellSurfaces::findDirectionalLevel(), localPointRegion::findDuplicateFacePairs(), searchableBox::findLineAll(), searchableRotatedBox::findLineAll(), triSurfaceSearch::findLineAll(), distributedTriSurfaceMesh::findNearest(), mappedPatchBase::findSamples(), for(), isoSurfacePoint::generateFaceTriPoints(), volBSplinesBase::getAllControlPoints(), coordSetWriter::getBufferLine(), removeCells::getExposedFaces(), zoneDistribute::getFields(), externalDisplacementMeshMover::getFixedValueBCs(), combineFaces::getMergeSets(), boundaryMesh::getNearest(), incompressiblePrimalSolver::getObjectiveFunctions(), cellDistFuncs::getPointNeighbours(), undoableMeshCutter::getSplitFaces(), distributedTriSurfaceMesh::getVolumeType(), meshRefinement::getZones(), globalIndexAndTransform::globalIndexAndTransform(), triSurfaceTools::greenRefine(), chemPointISAT< CompType, ThermoType >::grow(), inverseDistance::holeExtrapolationStencil(), InjectedParticleDistributionInjection< CloudType >::initialise(), viewFactor::initialise(), fluxSummary::initialiseCellZoneAndDirection(), fluxSummary::initialiseFaceZone(), fluxSummary::initialiseFaceZoneAndDirection(), fluxSummary::initialiseSurface(), fluxSummary::initialiseSurfaceAndDirection(), objectivePtLosses::initialize(), objectiveUniformityPatch::initialize(), wallBoundedStreamLineParticle::interpolateFields(), regionModel::interRegionAMI(), intersectedSurface::intersectedSurface(), meshSearch::intersections(), rigidBodyModel::join_(), lduPrimitiveMesh::lduPrimitiveMesh(), triSurfaceLoader::load(), fileOperation::lookupAndCacheProcessorsPath(), Foam::lumpedPointTools::lumpedPointStates(), LuoSvendsen::LuoSvendsen(), epsilonWallFunctionFvPatchScalarField::manipulateMatrix(), omegaWallFunctionFvPatchScalarField::manipulateMatrix(), inverseDistance::markDonors(), trackingInverseDistance::markDonors(), triSurface::markZone(), PatchTools::markZone(), momentOfInertia::massPropertiesPatch(), polyBoundaryMesh::matchGroups(), CollisionRecordList< PairType, WallType >::matchPairRecord(), CollisionRecordList< PairType, WallType >::matchWallRecord(), meshRefinement::mergePatchFacesUndo(), meshRefinement::mergeZoneBaffles(), blockMesh::mesh(), meshRefinement::meshedPatches(), findCellParticle::move(), chemistryReductionMethod< CompType, ThermoType >::New(), chemistryTabulationMethod< CompType, ThermoType >::New(), combustionModel::New(), fvMeshTools::newMesh(), faceShading::nonCoupledPatches(), properties::objectResultEntries(), noiseFFT::octaveBandInfo(), formatter::openTagImpl(), appendOp< Container >::operator()(), storeOp::operator()(), sampledSet::iNewCapture::operator()(), sampledSurface::iNewCapture::operator()(), storeOp::operator()(), MeshedSurface< face >::operator=(), oversetGAMGInterface::oversetGAMGInterface(), InflationInjection< CloudType >::parcelsToInject(), sampledPatch::patchIDs(), lumpedPointDisplacementPointPatchVectorField::patchIds(), boundaryMesh::patchify(), patchInteractionDataList::patchInteractionDataList(), ParticleHistogram< CloudType >::postFace(), ParticlePostProcessing< CloudType >::postFace(), ParticleZoneInfo< CloudType >::postMove(), ParticleHistogram< CloudType >::postPatch(), collatedFileOperation::printBanner(), Foam::printRootsSubscription(), processorGAMGInterface::processorGAMGInterface(), faceAreaWeightAMI::processSourceFace(), polyMeshAdder::procPatchPairs(), binModel::read(), externalCoupled::read(), NASedgeFormat::read(), ABAQUSsurfaceFormat< Face >::read(), AC3DsurfaceFormat< Face >::read(), NASsurfaceFormat< Face >::read(), OBJsurfaceFormat< Face >::read(), OFFsurfaceFormat< Face >::read(), STARCDsurfaceFormat< Face >::read(), VTKsurfaceFormat< Face >::read(), OBJedgeFormat::read(), STARCDedgeFormat::read(), Foam::blockMeshTools::read(), IOPosition< CloudType >::readData(), lagrangianFieldDecomposer::readFieldFields(), Foam::readObjVertices(), STARCDCore::readPoints(), ABAQUSCore::readHelper::readPoints(), FIREMeshReader::readSelections(), Foam::readUntilBalancedDelimiter(), Foam::readVariable(), Foam::readVerbatim(), isoAlpha::reconstruct(), lagrangianReconstructor::reconstructFieldFields(), lagrangianReconstructor::reconstructPositions(), DAC< CompType, ThermoType >::reduceMechanism(), DRG< CompType, ThermoType >::reduceMechanism(), DRGEP< CompType, ThermoType >::reduceMechanism(), PFA< CompType, ThermoType >::reduceMechanism(), box::refineBox(), box::refineBox(), refinementHistory::refinementHistory(), refinementHistory::refinementHistory(), searchableSurfaceCollection::regions(), edgeMesh::regions(), regionSplit2D::regionSplit2D(), RemoveParcels< CloudType >::RemoveParcels(), vtmWriter::repair(), fieldSelection::resetFieldFilters(), logFiles::resetName(), logFiles::resetNames(), rigidBodyMeshMotion::rigidBodyMeshMotion(), rigidBodyMeshMotionSolver::rigidBodyMeshMotionSolver(), triSurfaceLoader::select(), surfaceFeatures::selectFeatureEdges(), dynamicRefineFvMesh::selectRefineCells(), dynamicRefineFvMesh::selectUnrefinePoints(), boundaryMesh::setFeatureEdges(), fvMatrix< Type >::setInterfaces(), noiseModel::setOctaveBands(), box::setRefineFlags(), hexRef8::setRefinement(), faceCollapser::setRefinement(), edgeCollapser::setRefinement(), boundaryCutter::setRefinement(), createShellMesh::setRefinement(), propellerInfo::setSampleDiskGeometry(), masterUncollatedFileOperation::setTime(), shortestPathSet::shortestPathSet(), searchableSurfacesQueries::signedDistance(), Foam::fvc::smooth(), PatchTools::sortedPointEdges(), extendedEdgeMesh::sortPointsAndEdges(), Foam::stringOps::split(), Foam::stringOps::split(), Foam::stringOps::splitAny(), meshRefinement::splitFacesUndo(), Foam::stringOps::splitFixed(), meshRefinement::splitMeshRegions(), Foam::fvc::spread(), faceAreaWeightAMI2D::storeInterArea(), cellZoneSet::subset(), faceZoneSet::subset(), pointZoneSet::subset(), meshRefinement::subsetBaffles(), cellZoneSet::subtractSet(), faceZoneSet::subtractSet(), pointZoneSet::subtractSet(), reconstructionSchemes::surface(), surfaceFeatures::surfaceFeatures(), surfaceIntersection::surfaceIntersection(), Foam::fvc::sweep(), faceZoneSet::sync(), cutFaceAdvect::timeIntegratedArea(), cutFaceAdvect::timeIntegratedArea(), cutFaceAdvect::timeIntegratedFaceFlux(), cutFaceAdvect::timeIntegratedFaceFlux(), faceAreaIntersect::triangleFan(), triSurfaceTools::triangulate(), triSurfaceTools::triangulateFaceCentre(), refinementParameters::unzonedLocations(), CollisionRecordList< PairType, WallType >::update(), cellVolumeWeight::update(), inverseDistance::update(), trackingInverseDistance::update(), oversetFvMeshBase::updateAddressing(), wallPoints::updateCell(), outletMappedUniformInletFvPatchField< Type >::updateCoeffs(), wallPoints::updateFace(), wallPoints::updateFace(), externalDisplacementMeshMover::updateMesh(), probes::updateMesh(), patchInjectionBase::updateMesh(), propellerInfo::updateSampleDiskCells(), solverFieldSelection::updateSelection(), cuttingSurfaceBase::walkCellCuts(), cellCellStencil::walkFront(), processorColour::walkFront(), wallLayerCells::wallLayerCells(), WallLocalSpringSliderDashpot< CloudType >::WallLocalSpringSliderDashpot(), particleDistribution::write(), vtkCloud::write(), areaWrite::write(), vtkWrite::write(), ParticleZoneInfo< CloudType >::write(), oversetFvMeshBase::write(), csvWriter::writeBuffered(), externalCoupled::writeGeometry(), refinementParameters::zonedLocations(), and refinementParameters::zonePoints().
append() [2/7]
template<class T > void append (T * ptr) inline
Definition at line 240 of file PtrList.H.
References PtrList< T >::push_back().
append() [3/7]
template<class T > void append (std::unique_ptr< T > && ptr) inline
Definition at line 244 of file PtrList.H.
References PtrList< T >::push_back().
append() [4/7]
template<class T > void append (autoPtr< T > && ptr) inline
Definition at line 251 of file PtrList.H.
References PtrList< T >::push_back().
append() [5/7]
template<class T > void append (const refPtr< T > & ptr) inline
Definition at line 255 of file PtrList.H.
References PtrList< T >::push_back().
append() [6/7]
template<class T > void append (const tmp< T > & ptr) inline
Definition at line 259 of file PtrList.H.
References PtrList< T >::push_back().
append() [7/7]
template<class T > void append (PtrList< T > && other) inline
Definition at line 263 of file PtrList.H.
References PtrList< T >::push_back().
clone() [2/2]
template<class T > template<class... Args> Foam::PtrList< T > clone (Args &&... args) const
Definition at line 74 of file PtrList.C.
References args, UPtrList< T >::ptrs_, and T.
Friends And Related Symbol Documentation
operator>>
template<class T > Istream & operator>> (Istream & is, PtrList< T > & list) friend
Referenced by LList< LListBase, T >::LList().
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/Lists/List/List.H
src/OpenFOAM/containers/PtrLists/PtrList/PtrList.H
src/OpenFOAM/containers/PtrLists/PtrList/PtrList.C
src/OpenFOAM/containers/PtrLists/PtrList/PtrListI.H
src/OpenFOAM/containers/PtrLists/PtrList/PtrListIO.C