OpenFOAM: sensitivitySurfacePoints Class Reference
sensitivitySurfacePoints Class Reference
Calculation of adjoint based sensitivities at wall points.
#include <sensitivitySurfacePointsIncompressible.H>
Public Member Functions
TypeName ("surfacePoints")
sensitivitySurfacePoints (const fvMesh &mesh, const dictionary &dict, incompressibleAdjointSolver &adjointSolver)
virtual ~sensitivitySurfacePoints ()=default
virtual bool readDict (const dictionary &dict)
virtual void accumulateIntegrand (const scalar dt)
virtual void assembleSensitivities ()
virtual void clearSensitivities ()
virtual void write (const word &baseName=word::null)
Public Member Functions inherited from adjointSensitivity
TypeName ("adjointSensitivity")
declareRunTimeSelectionTable (autoPtr, adjointSensitivity, dictionary,(const fvMesh &mesh, const dictionary &dict, incompressibleAdjointSolver &adjointSolver),(mesh, dict, adjointSolver))
adjointSensitivity (const fvMesh &mesh, const dictionary &dict, incompressibleAdjointSolver &adjointSolver)
virtual ~adjointSensitivity ()=default
const incompressibleVars & primalVars () const
const incompressibleAdjointVars & adjointVars () const
const incompressibleAdjointSolver & adjointSolver () const
virtual const scalarField & calculateSensitivities ()
const scalarField & getSensitivities () const
tmp< volTensorField > computeGradDxDbMultiplier ()
tmp< volVectorField > adjointMeshMovementSource ()
Public Member Functions inherited from sensitivity
TypeName ("sensitivity")
sensitivity (const fvMesh &mesh, const dictionary &dict)
virtual ~sensitivity ()=default
const dictionary & dict () const
virtual void computeDerivativesSize ()
Protected Member Functions
void read ()
void finaliseFaceMultiplier ()
void finalisePointSensitivities ()
void constructGlobalPointNormalsAndAreas (vectorField &pointNormals, scalarField &pointMagSf)
void setSuffixName ()
Protected Attributes
bool includeSurfaceArea_
bool includePressureTerm_
bool includeGradStressTerm_
bool includeTransposeStresses_
bool useSnGradInTranposeStresses_
bool includeDivTerm_
bool includeDistance_
bool includeMeshMovement_
bool includeObjective_
autoPtr< adjointEikonalSolver > eikonalSolver_
autoPtr< adjointMeshMovementSolver > meshMovementSolver_
autoPtr< boundaryVectorField > wallFaceSens_
autoPtr< boundaryVectorField > dSfdbMult_
autoPtr< boundaryVectorField > dnfdbMult_
Protected Attributes inherited from adjointSensitivity
scalarField derivatives_
incompressibleAdjointSolver & adjointSolver_
const incompressibleVars & primalVars_
incompressibleAdjointVars & adjointVars_
objectiveManager & objectiveManager_
Protected Attributes inherited from sensitivity
const fvMesh & mesh_
dictionary dict_
autoPtr< volScalarField > fieldSensPtr_
Additional Inherited Members
Static Public Member Functions inherited from adjointSensitivity
static autoPtr< adjointSensitivity > New (const fvMesh &mesh, const dictionary &dict, incompressibleAdjointSolver &adjointSolver)
Detailed Description
Calculation of adjoint based sensitivities at wall points.
Source files
sensitivitySurfacePointsIncompressible.H
sensitivitySurfacePoints.C
Definition at line 55 of file sensitivitySurfacePointsIncompressible.H.
Constructor & Destructor Documentation
sensitivitySurfacePoints()
sensitivitySurfacePoints (const fvMesh & mesh, const dictionary & dict, incompressibleAdjointSolver & adjointSolver)
Definition at line 326 of file sensitivitySurfacePointsIncompressible.C.
References adjointSensitivity::derivatives_, sensitivity::mesh_, sensitivitySurfacePoints::read(), Foam::reduce(), and Foam::Zero.
~sensitivitySurfacePoints()
virtual ~sensitivitySurfacePoints () virtual default
Member Function Documentation
read()
void read () protected
Definition at line 48 of file sensitivitySurfacePointsIncompressible.C.
References incompressibleAdjointVars::adjointTurbulence(), adjointSensitivity::adjointVars_, sensitivity::dict(), sensitivitySurfacePoints::eikonalSolver_, sensitivitySurfacePoints::includeDistance_, sensitivitySurfacePoints::includeDivTerm_, sensitivitySurfacePoints::includeGradStressTerm_, sensitivitySurfacePoints::includeMeshMovement_, sensitivitySurfacePoints::includeObjective_, sensitivitySurfacePoints::includePressureTerm_, sensitivitySurfacePoints::includeSurfaceArea_, sensitivitySurfacePoints::includeTransposeStresses_, sensitivity::mesh_, sensitivitySurfacePoints::meshMovementSolver_, adjointSensitivity::primalVars_, and sensitivitySurfacePoints::useSnGradInTranposeStresses_.
Referenced by sensitivitySurfacePoints::sensitivitySurfacePoints().
finaliseFaceMultiplier()
void finaliseFaceMultiplier () protected
Definition at line 106 of file sensitivitySurfacePointsIncompressible.C.
References sensitivitySurfacePoints::dnfdbMult_, sensitivitySurfacePoints::eikonalSolver_, sensitivitySurfacePoints::includeDistance_, sensitivitySurfacePoints::includeMeshMovement_, sensitivity::mesh_, sensitivitySurfacePoints::meshMovementSolver_, and sensitivitySurfacePoints::wallFaceSens_.
Referenced by sensitivitySurfacePoints::assembleSensitivities().
finalisePointSensitivities()
void finalisePointSensitivities () protected
Definition at line 167 of file sensitivitySurfacePointsIncompressible.C.
References sensitivitySurfacePoints::dnfdbMult_, sensitivitySurfacePoints::dSfdbMult_, forAll, Tensor< scalar >::I, sensitivitySurfacePoints::includeObjective_, sensitivity::mesh_, p, UPtrList< T >::size(), sensitivitySurfacePoints::wallFaceSens_, and Foam::Zero.
Referenced by sensitivitySurfacePoints::assembleSensitivities().
constructGlobalPointNormalsAndAreas()
void constructGlobalPointNormalsAndAreas (vectorField & pointNormals, scalarField & pointMagSf) protected
Definition at line 252 of file sensitivitySurfacePointsIncompressible.C.
References forAll, sensitivity::mesh_, syncTools::syncPointList(), and VectorSpace< Form, Cmpt, Ncmpts >::zero.
Referenced by sensitivitySurfacePoints::assembleSensitivities().
setSuffixName()
void setSuffixName () protected
Definition at line 303 of file sensitivitySurfacePointsIncompressible.C.
References adjointSensitivity::adjointVars_, sensitivity::dict(), sensitivitySurfacePoints::includeMeshMovement_, word::null, shapeSensitivitiesBase::setSuffix(), and variablesSet::solverName().
Referenced by sensitivitySurfacePoints::write().
TypeName()
TypeName ("surfacePoints")
readDict()
bool readDict (const dictionary & dict) virtual
Reimplemented from sensitivity.
Definition at line 379 of file sensitivitySurfacePointsIncompressible.C.
References sensitivity::dict(), sensitivitySurfacePoints::eikonalSolver_, sensitivitySurfacePoints::meshMovementSolver_, and sensitivity::readDict().
accumulateIntegrand()
void accumulateIntegrand (const scalar dt) virtual
Implements adjointSensitivity.
Definition at line 400 of file sensitivitySurfacePointsIncompressible.C.
References incompressibleAdjointSolver::additionalSensitivityMapTerms(), adjointSensitivity::adjointSolver_, incompressibleAdjointVars::adjointTurbulence(), adjointSensitivity::adjointVars_, GeometricField< Type, PatchField, GeoMesh >::boundaryField(), PtrList< T >::clear(), Field< Type >::component(), DebugInfo, Foam::dimVelocity, sensitivitySurfacePoints::dnfdbMult_, sensitivitySurfacePoints::dSfdbMult_, sensitivitySurfacePoints::eikonalSolver_, Foam::endl(), forAll, objectiveManager::getObjectiveFunctions(), Foam::fvc::grad(), sensitivitySurfacePoints::includeDistance_, sensitivitySurfacePoints::includeDivTerm_, sensitivitySurfacePoints::includeGradStressTerm_, sensitivitySurfacePoints::includeMeshMovement_, sensitivitySurfacePoints::includeObjective_, sensitivitySurfacePoints::includePressureTerm_, sensitivitySurfacePoints::includeTransposeStresses_, sensitivity::mesh_, sensitivitySurfacePoints::meshMovementSolver_, GeometricField< tensor, fvPatchField, volMesh >::New(), adjointSensitivity::objectiveManager_, p, incompressibleAdjointMeanFlowVars::pa(), adjointSensitivity::primalVars_, UPtrList< T >::size(), Foam::sqr(), Foam::twoSymm(), U, incompressibleAdjointMeanFlowVars::Ua(), Foam::unzipRow(), sensitivitySurfacePoints::useSnGradInTranposeStresses_, sensitivitySurfacePoints::wallFaceSens_, and Foam::Zero.
assembleSensitivities()
void assembleSensitivities () virtual
Implements adjointSensitivity.
Definition at line 613 of file sensitivitySurfacePointsIncompressible.C.
References Pstream::allGatherList(), sensitivitySurfacePoints::constructGlobalPointNormalsAndAreas(), adjointSensitivity::derivatives_, sensitivitySurfacePoints::finaliseFaceMultiplier(), sensitivitySurfacePoints::finalisePointSensitivities(), forAll, sensitivitySurfacePoints::includeSurfaceArea_, Foam::mag(), sensitivity::mesh_, UPstream::myProcNo(), UPstream::nProcs(), PtrList< T >::setSize(), UPtrList< T >::size(), syncTools::syncPointList(), Foam::Zero, and VectorSpace< Form, Cmpt, Ncmpts >::zero.
clearSensitivities()
void clearSensitivities () virtual
Reimplemented from adjointSensitivity.
Definition at line 730 of file sensitivitySurfacePointsIncompressible.C.
References adjointSensitivity::clearSensitivities(), shapeSensitivitiesBase::clearSensitivities(), sensitivitySurfacePoints::dnfdbMult_, sensitivitySurfacePoints::dSfdbMult_, sensitivitySurfacePoints::eikonalSolver_, sensitivitySurfacePoints::includeDistance_, sensitivitySurfacePoints::includeMeshMovement_, sensitivitySurfacePoints::meshMovementSolver_, sensitivitySurfacePoints::wallFaceSens_, and VectorSpace< Form, Cmpt, Ncmpts >::zero.
write()
void write (const word & baseName = word::null) virtual
Reimplemented from adjointSensitivity.
Definition at line 753 of file sensitivitySurfacePointsIncompressible.C.
References sensitivitySurfacePoints::setSuffixName(), shapeSensitivitiesBase::write(), and adjointSensitivity::write().
Member Data Documentation
includeSurfaceArea_
bool includeSurfaceArea_ protected
Definition at line 66 of file sensitivitySurfacePointsIncompressible.H.
Referenced by sensitivitySurfacePoints::assembleSensitivities(), and sensitivitySurfacePoints::read().
includePressureTerm_
bool includePressureTerm_ protected
Definition at line 69 of file sensitivitySurfacePointsIncompressible.H.
Referenced by sensitivitySurfacePoints::accumulateIntegrand(), and sensitivitySurfacePoints::read().
includeGradStressTerm_
bool includeGradStressTerm_ protected
Definition at line 72 of file sensitivitySurfacePointsIncompressible.H.
Referenced by sensitivitySurfacePoints::accumulateIntegrand(), and sensitivitySurfacePoints::read().
includeTransposeStresses_
bool includeTransposeStresses_ protected
Definition at line 75 of file sensitivitySurfacePointsIncompressible.H.
Referenced by sensitivitySurfacePoints::accumulateIntegrand(), and sensitivitySurfacePoints::read().
useSnGradInTranposeStresses_
bool useSnGradInTranposeStresses_ protected
Definition at line 78 of file sensitivitySurfacePointsIncompressible.H.
Referenced by sensitivitySurfacePoints::accumulateIntegrand(), and sensitivitySurfacePoints::read().
includeDivTerm_
bool includeDivTerm_ protected
Definition at line 81 of file sensitivitySurfacePointsIncompressible.H.
Referenced by sensitivitySurfacePoints::accumulateIntegrand(), and sensitivitySurfacePoints::read().
includeDistance_
bool includeDistance_ protected
Definition at line 84 of file sensitivitySurfacePointsIncompressible.H.
Referenced by sensitivitySurfacePoints::accumulateIntegrand(), sensitivitySurfacePoints::clearSensitivities(), sensitivitySurfacePoints::finaliseFaceMultiplier(), and sensitivitySurfacePoints::read().
includeMeshMovement_
bool includeMeshMovement_ protected
Definition at line 87 of file sensitivitySurfacePointsIncompressible.H.
Referenced by sensitivitySurfacePoints::accumulateIntegrand(), sensitivitySurfacePoints::clearSensitivities(), sensitivitySurfacePoints::finaliseFaceMultiplier(), sensitivitySurfacePoints::read(), and sensitivitySurfacePoints::setSuffixName().
includeObjective_
bool includeObjective_ protected
Definition at line 90 of file sensitivitySurfacePointsIncompressible.H.
Referenced by sensitivitySurfacePoints::accumulateIntegrand(), sensitivitySurfacePoints::finalisePointSensitivities(), and sensitivitySurfacePoints::read().
eikonalSolver_
autoPtr<adjointEikonalSolver> eikonalSolver_ protected
Definition at line 92 of file sensitivitySurfacePointsIncompressible.H.
Referenced by sensitivitySurfacePoints::accumulateIntegrand(), sensitivitySurfacePoints::clearSensitivities(), sensitivitySurfacePoints::finaliseFaceMultiplier(), sensitivitySurfacePoints::read(), and sensitivitySurfacePoints::readDict().
meshMovementSolver_
autoPtr<adjointMeshMovementSolver> meshMovementSolver_ protected
Definition at line 94 of file sensitivitySurfacePointsIncompressible.H.
Referenced by sensitivitySurfacePoints::accumulateIntegrand(), sensitivitySurfacePoints::clearSensitivities(), sensitivitySurfacePoints::finaliseFaceMultiplier(), sensitivitySurfacePoints::read(), and sensitivitySurfacePoints::readDict().
wallFaceSens_
autoPtr<boundaryVectorField> wallFaceSens_ protected
Definition at line 101 of file sensitivitySurfacePointsIncompressible.H.
Referenced by sensitivitySurfacePoints::accumulateIntegrand(), sensitivitySurfacePoints::clearSensitivities(), sensitivitySurfacePoints::finaliseFaceMultiplier(), and sensitivitySurfacePoints::finalisePointSensitivities().
dSfdbMult_
autoPtr<boundaryVectorField> dSfdbMult_ protected
Definition at line 104 of file sensitivitySurfacePointsIncompressible.H.
Referenced by sensitivitySurfacePoints::accumulateIntegrand(), sensitivitySurfacePoints::clearSensitivities(), and sensitivitySurfacePoints::finalisePointSensitivities().
dnfdbMult_
autoPtr<boundaryVectorField> dnfdbMult_ protected
Definition at line 105 of file sensitivitySurfacePointsIncompressible.H.
Referenced by sensitivitySurfacePoints::accumulateIntegrand(), sensitivitySurfacePoints::clearSensitivities(), sensitivitySurfacePoints::finaliseFaceMultiplier(), and sensitivitySurfacePoints::finalisePointSensitivities().
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/optimisation/adjointSensitivity/incompressible/sensitivitySurfacePoints/sensitivitySurfacePointsIncompressible.H
src/optimisation/adjointOptimisation/adjoint/optimisation/adjointSensitivity/incompressible/sensitivitySurfacePoints/sensitivitySurfacePointsIncompressible.C