OpenFOAM: chemPointISAT< CompType, ThermoType > Class Template Reference
chemPointISAT< CompType, ThermoType > Class Template Reference
Leaf of the binary tree. The chemPoint stores the composition 'phi', the mapping of this composition Rphi, the mapping gradient matrix A and the matrix describing the Ellipsoid Of Accuracy (EOA).
#include <chemPointISAT.H>
Public Member Functions
chemPointISAT (TDACChemistryModel< CompType, ThermoType > &chemistry, const scalarField &phi, const scalarField &Rphi, const scalarSquareMatrix &A, const scalarField &scaleFactor, const scalar &tolerance, const label &completeSpaceSize, const dictionary &coeffsDict, binaryNode< CompType, ThermoType > *node=nullptr)
chemPointISAT (const chemPointISAT< CompType, ThermoType > &p, binaryNode< CompType, ThermoType > *node)
chemPointISAT (chemPointISAT< CompType, ThermoType > &p)
TDACChemistryModel< CompType, ThermoType > & chemistry ()
label nGrowth ()
label & completeSpaceSize ()
const scalarField & phi () const
const scalarField & Rphi () const
const scalarField & scaleFactor ()
const scalar & tolerance ()
binaryNode< CompType, ThermoType > *& node ()
const scalarSquareMatrix & A () const
scalarSquareMatrix & A ()
const scalarSquareMatrix & LT () const
scalarSquareMatrix & LT ()
label nActiveSpecies ()
List< label > & completeToSimplifiedIndex ()
List< label > & simplifiedToCompleteIndex ()
void increaseNumRetrieve ()
void resetNumRetrieve ()
void increaseNLifeTime ()
label simplifiedToCompleteIndex (const label i)
const label & timeTag ()
label & lastTimeUsed ()
bool & toRemove ()
label & maxNumNewDim ()
const label & numRetrieve ()
const label & nLifeTime ()
bool variableTimeStep () const
bool inEOA (const scalarField &phiq)
bool grow (const scalarField &phiq)
bool checkSolution (const scalarField &phiq, const scalarField &Rphiq)
Static Public Member Functions
static void changeTolerance (scalar newTol)
Detailed Description
template<class CompType, class ThermoType>
class Foam::chemPointISAT< CompType, ThermoType >
Leaf of the binary tree. The chemPoint stores the composition 'phi', the mapping of this composition Rphi, the mapping gradient matrix A and the matrix describing the Ellipsoid Of Accuracy (EOA).
1)When the chemPoint is created the region of accuracy is approximated by an ellipsoid E centered in 'phi' (obtained with the constant): E = {x| ||L^T.(x-phi)|| <= 1}, with x a point in the composition space and L^T the transpose of an upper triangular matrix describing the EOA (see below: "Computation of L").
2)To RETRIEVE the mapping from the chemPoint phi, the query point phiq has to be in the EOA of phi. It follows that, dphi=phiq-phi and to test if phiq is in the ellipsoid there are two methods. First, compare r=||dphi|| with rmin and rmax. If r < rmin, phiq is in the EOA. If r > rmax, phiq is out of the EOA. This operations is O(completeSpaceSize) and is performed first. If rmin < r < rmax, then the second method is used: ||L^T.dphi|| <= 1 to be in the EOA.
If phiq is in the EOA, Rphiq is obtained by linear interpolation: Rphiq= Rphi + A.dphi.
3)If phiq is not in the EOA, then the mapping is computed. But as the EOA is a conservative approximation of the region of accuracy surrounding the point phi, we could expand it by comparing the computed results with the one obtained by linear interpolation. The error epsGrow is calculated: epsGrow = ||B.(dR - dRl)||, with dR = Rphiq - Rphi, dRl = A.dphi and B the diagonal scale factor matrix. If epsGrow <= tolerance, the EOA is too conservative and a GROW is perforned otherwise, the newly computed mapping is associated to the initial composition and added to the tree.
4)To GROW the EOA, we expand it to include the previous EOA and the query point phiq. The rank-one matrix method is used. The EOA is transformed to a hypersphere centered at the origin. Then it is expanded to include the transformed point phiq' on its boundary. Then the inverse transformation give the modified matrix L' (see below: "Grow the EOA").
Computation of L : In [1], the EOA of the constant approximation is given by E = {x| ||B.A/tolerance.(x-phi)|| <= 1}, with B a scale factor diagonal matrix, A the mapping gradient matrix and tolerance the absolute tolerance. If we take the QR decomposition of (B.A)/tolerance= Q.R, with Q an orthogonal matrix and R an upper triangular matrix such that the EOA is described by (phiq-phi0)^T.R^T.R.(phiq-phi0) <= 1 L^T = R, both Cholesky decomposition of A^T.B^T.B.A/tolerance^2 This representation of the ellipsoid is used in [2] and in order to avoid large value of semi-axe length in certain direction, a Singular Value Decomposition (SVD) is performed on the L matrix: L = UDV^T, with the orthogonal matrix U giving the directions of the principal axes and 1/di the inverse of the element of the diagonal matrix D giving the length of the principal semi-axes. To avoid very large value of those length, di' = max(di, 1/(alphaEOA*sqrt(tolerance))), with alphaEOA = 0.1 (see [2]) di' = max(di, 1/2), see [1]. The latter will be used in this implementation. And L' = UD'V^T, with D' the diagonal matrix with the modified di'.
Grow the EOA : More details about the minimum-volume ellipsoid covering an ellispoid E and a point p are found in [3]. Here is the main steps to obtain the modified matrix L' describing the new ellipsoid. 1) calculate the point p' in the transformed space : p' = L^T.(p-phi) 2) compute the rank-one decomposition: G = I + gamma.p'.p'^T, with gamma = (1/|p'|-1)*1/|p'|^2 3) compute L': L' = L.G.
References:
    [1] Pope, S. B. (1997).
    Computationally efficient implementation of combustion chemistry using
    in situ adaptive tabulation.
    Combustion Theory and Modelling, 1, 41-63.
    [2] Lu, L., & Pope, S. B. (2009).
    An improved algorithm for in situ adaptive tabulation.
    Journal of Computational Physics, 228(2), 361-386.
    [3] Pope, S. B. (2008).
    Algorithms for ellipsoids.
    Cornell University Report No. FDA, 08-01.
Definition at line 136 of file chemPointISAT.H.
Constructor & Destructor Documentation
chemPointISAT() [1/3]
template<class CompType , class ThermoType > chemPointISAT (TDACChemistryModel< CompType, ThermoType > & chemistry, const scalarField & phi, const scalarField & Rphi, const scalarSquareMatrix & A, const scalarField & scaleFactor, const scalar & tolerance, const label & completeSpaceSize, const dictionary & coeffsDict, binaryNode< CompType, ThermoType > * node = nullptr)
Definition at line 198 of file chemPointISAT.C.
References chemPointISAT< CompType, ThermoType >::A(), chemPointISAT< CompType, ThermoType >::chemistry(), chemPointISAT< CompType, ThermoType >::completeSpaceSize(), TDACChemistryModel< ReactionThermo, ThermoType >::completeToSimplifiedIndex(), D, Foam::max(), TDACChemistryModel< ReactionThermo, ThermoType >::mechRed(), Foam::multiply(), chemPointISAT< CompType, ThermoType >::scaleFactor(), chemPointISAT< CompType, ThermoType >::simplifiedToCompleteIndex(), TDACChemistryModel< ReactionThermo, ThermoType >::simplifiedToCompleteIndex(), chemPointISAT< CompType, ThermoType >::tolerance(), and chemPointISAT< CompType, ThermoType >::variableTimeStep().
chemPointISAT() [2/3]
template<class CompType , class ThermoType > chemPointISAT (const chemPointISAT< CompType, ThermoType > & p, binaryNode< CompType, ThermoType > * node)
chemPointISAT() [3/3]
template<class CompType , class ThermoType > chemPointISAT (Foam::chemPointISAT< CompType, ThermoType > & p)
Definition at line 317 of file chemPointISAT.C.
References chemPointISAT< CompType, ThermoType >::completeSpaceSize(), p, and chemPointISAT< CompType, ThermoType >::variableTimeStep().
Member Function Documentation
chemistry()
template<class CompType , class ThermoType > TDACChemistryModel< CompType, ThermoType > & chemistry () inline
Definition at line 271 of file chemPointISAT.H.
Referenced by chemPointISAT< CompType, ThermoType >::chemPointISAT().
nGrowth()
template<class CompType , class ThermoType > label nGrowth () inline
Definition at line 276 of file chemPointISAT.H.
completeSpaceSize()
template<class CompType , class ThermoType > label & completeSpaceSize () inline
Definition at line 281 of file chemPointISAT.H.
Referenced by chemPointISAT< CompType, ThermoType >::chemPointISAT(), and chemPointISAT< CompType, ThermoType >::chemPointISAT().
phi()
template<class CompType , class ThermoType > const scalarField & phi () const inline
Definition at line 286 of file chemPointISAT.H.
Rphi()
template<class CompType , class ThermoType > const scalarField & Rphi () const inline
Definition at line 291 of file chemPointISAT.H.
scaleFactor()
template<class CompType , class ThermoType > const scalarField & scaleFactor () inline
Definition at line 296 of file chemPointISAT.H.
Referenced by chemPointISAT< CompType, ThermoType >::chemPointISAT().
tolerance()
template<class CompType , class ThermoType > const scalar & tolerance () inline
Definition at line 301 of file chemPointISAT.H.
Referenced by chemPointISAT< CompType, ThermoType >::chemPointISAT().
changeTolerance()
template<class CompType , class ThermoType > static void changeTolerance (scalar newTol) inline static
Definition at line 306 of file chemPointISAT.H.
node()
template<class CompType , class ThermoType > binaryNode< CompType, ThermoType > *& node () inline
Definition at line 311 of file chemPointISAT.H.
Referenced by binaryTree< CompType, ThermoType >::treeSuccessor().
A() [1/2]
template<class CompType , class ThermoType > const scalarSquareMatrix & A () const inline
Definition at line 316 of file chemPointISAT.H.
Referenced by chemPointISAT< CompType, ThermoType >::chemPointISAT().
A() [2/2]
template<class CompType , class ThermoType > scalarSquareMatrix & A () inline
Definition at line 321 of file chemPointISAT.H.
LT() [1/2]
template<class CompType , class ThermoType > const scalarSquareMatrix & LT () const inline
Definition at line 326 of file chemPointISAT.H.
LT() [2/2]
template<class CompType , class ThermoType > scalarSquareMatrix & LT () inline
Definition at line 331 of file chemPointISAT.H.
nActiveSpecies()
template<class CompType , class ThermoType > label nActiveSpecies () inline
Definition at line 336 of file chemPointISAT.H.
completeToSimplifiedIndex()
template<class CompType , class ThermoType > List< label > & completeToSimplifiedIndex () inline
Definition at line 341 of file chemPointISAT.H.
simplifiedToCompleteIndex() [1/2]
template<class CompType , class ThermoType > List< label > & simplifiedToCompleteIndex () inline
Definition at line 346 of file chemPointISAT.H.
Referenced by chemPointISAT< CompType, ThermoType >::chemPointISAT().
increaseNumRetrieve()
template<class CompType , class ThermoType > void increaseNumRetrieve ()
Definition at line 785 of file chemPointISAT.C.
resetNumRetrieve()
template<class CompType , class ThermoType > void resetNumRetrieve ()
Definition at line 792 of file chemPointISAT.C.
increaseNLifeTime()
template<class CompType , class ThermoType > void increaseNLifeTime ()
Definition at line 799 of file chemPointISAT.C.
simplifiedToCompleteIndex() [2/2]
template<class CompType , class ThermoType > Foam::label simplifiedToCompleteIndex (const label i)
Definition at line 806 of file chemPointISAT.C.
timeTag()
template<class CompType , class ThermoType > const label & timeTag () inline
Definition at line 362 of file chemPointISAT.H.
lastTimeUsed()
template<class CompType , class ThermoType > label & lastTimeUsed () inline
Definition at line 367 of file chemPointISAT.H.
toRemove()
template<class CompType , class ThermoType > bool & toRemove () inline
Definition at line 372 of file chemPointISAT.H.
maxNumNewDim()
template<class CompType , class ThermoType > label & maxNumNewDim () inline
Definition at line 377 of file chemPointISAT.H.
numRetrieve()
template<class CompType , class ThermoType > const label & numRetrieve () inline
Definition at line 382 of file chemPointISAT.H.
nLifeTime()
template<class CompType , class ThermoType > const label & nLifeTime () inline
Definition at line 387 of file chemPointISAT.H.
variableTimeStep()
template<class CompType , class ThermoType > bool variableTimeStep () const inline
Definition at line 392 of file chemPointISAT.H.
Referenced by chemPointISAT< CompType, ThermoType >::chemPointISAT(), and chemPointISAT< CompType, ThermoType >::chemPointISAT().
inEOA()
template<class CompType , class ThermoType > bool inEOA (const scalarField & phiq)
Definition at line 363 of file chemPointISAT.C.
References Foam::endl(), Foam::Info, Foam::max(), Foam::nl, phi, Foam::sqr(), Foam::sqrt(), and Foam::Zero.
grow()
template<class CompType , class ThermoType > bool grow (const scalarField & phiq)
Definition at line 599 of file chemPointISAT.C.
References PtrList< T >::append(), forAll, gamma, phi, PtrList< T >::setSize(), UPtrList< T >::size(), Foam::sqr(), Foam::sqrt(), and Foam::Zero.
checkSolution()
template<class CompType , class ThermoType > bool checkSolution (const scalarField & phiq, const scalarField & Rphiq)
Definition at line 527 of file chemPointISAT.C.
References A, phi, Foam::sqr(), and Foam::sqrt().
The documentation for this class was generated from the following files:
src/thermophysicalModels/chemistryModel/chemistryModel/TDACChemistryModel/tabulation/ISAT/chemPointISAT/chemPointISAT.H
src/thermophysicalModels/chemistryModel/chemistryModel/TDACChemistryModel/tabulation/ISAT/chemPointISAT/chemPointISAT.C