OpenFOAM: LESdelta Class Reference
LESdelta Class Reference abstract
Abstract base class for LES deltas.
#include <LESdelta.H>
Public Member Functions
TypeName ("LESdelta")
declareRunTimeSelectionTable (autoPtr, LESdelta, dictionary,(const word &name, const turbulenceModel &turbulence, const dictionary &dict),(name, turbulence, dict))
LESdelta (const word &name, const turbulenceModel &turbulence)
virtual ~LESdelta ()=default
const turbulenceModel & turbulence () const
virtual void read (const dictionary &)=0
virtual void correct ()=0
virtual operator const volScalarField & () const
Static Public Member Functions
static autoPtr< LESdelta > New (const word &name, const turbulenceModel &turbulence, const dictionary &dict, const word &lookupName="delta")
static autoPtr< LESdelta > New (const word &name, const turbulenceModel &turbulence, const dictionary &dict, const dictionaryConstructorTableType &additionalConstructors, const word &lookupName="delta")
Protected Member Functions
LESdelta (const LESdelta &)=delete
void operator= (const LESdelta &)=delete
Protected Attributes
const turbulenceModel & turbulenceModel_
volScalarField delta_
Detailed Description
Abstract base class for LES deltas.
Source files
LESdelta.H
LESdelta.C
Definition at line 49 of file LESdelta.H.
Constructor & Destructor Documentation
LESdelta() [1/2]
LESdelta (const LESdelta &) protected delete
LESdelta() [2/2]
LESdelta (const word & name, const turbulenceModel & turbulence)
Definition at line 35 of file LESdelta.C.
References Foam::dimLength, and Foam::name().
~LESdelta()
virtual ~LESdelta () virtual default
Member Function Documentation
operator=()
void operator= (const LESdelta &) protected delete
TypeName()
TypeName ("LESdelta")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , LESdelta , dictionary , (const word &name, const turbulenceModel &turbulence, const dictionary &dict) , (name, turbulence, dict))
New() [1/2]
Foam::autoPtr< Foam::LESdelta > New (const word & name, const turbulenceModel & turbulence, const dictionary & dict, const word & lookupName = "delta") static
Definition at line 60 of file LESdelta.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), Foam::Info, Foam::name(), and turbulence.
Referenced by DeltaOmegaTildeDelta::DeltaOmegaTildeDelta(), IDDESDelta::IDDESDelta(), and SLADelta::SLADelta().
New() [2/2]
Foam::autoPtr< Foam::LESdelta > New (const word & name, const turbulenceModel & turbulence, const dictionary & dict, const dictionaryConstructorTableType & additionalConstructors, const word & lookupName = "delta") static
Definition at line 89 of file LESdelta.C.
References dict, UPtrList< T >::empty(), Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), Foam::Info, Foam::name(), Foam::nl, and turbulence.
turbulence()
const turbulenceModel & turbulence () const inline
Definition at line 130 of file LESdelta.H.
References LESdelta::turbulenceModel_.
Referenced by DeltaOmegaTildeDelta::DeltaOmegaTildeDelta(), IDDESDelta::IDDESDelta(), and SLADelta::SLADelta().
read()
virtual void read (const dictionary &) pure virtual
Implemented in cubeRootVolDelta, DeltaOmegaTildeDelta, IDDESDelta, maxDeltaxyz, maxDeltaxyzCubeRootLESDelta, PrandtlDelta, SLADelta, vanDriestDelta, and smoothDelta.
correct()
virtual void correct () pure virtual
Implemented in cubeRootVolDelta, DeltaOmegaTildeDelta, IDDESDelta, maxDeltaxyz, maxDeltaxyzCubeRootLESDelta, PrandtlDelta, SLADelta, smoothDelta, and vanDriestDelta.
operator const volScalarField &()
virtual operator const volScalarField & () const inline virtual
Definition at line 144 of file LESdelta.H.
References LESdelta::delta_.
Member Data Documentation
turbulenceModel_
const turbulenceModel& turbulenceModel_ protected
Definition at line 55 of file LESdelta.H.
Referenced by cubeRootVolDelta::calcDelta(), maxDeltaxyz::calcDelta(), and LESdelta::turbulence().
delta_
volScalarField delta_ protected
Definition at line 57 of file LESdelta.H.
Referenced by cubeRootVolDelta::calcDelta(), maxDeltaxyz::calcDelta(), LESdelta::operator const volScalarField &(), smoothDelta::deltaData::operator==(), smoothDelta::deltaData::valid(), and vanDriestDelta::vanDriestDelta().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/LES/LESdeltas/LESdelta/LESdelta.H
src/TurbulenceModels/turbulenceModels/LES/LESdeltas/LESdelta/LESdelta.C