OpenFOAM: icoPolynomial< Specie, PolySize > Class Template Reference
icoPolynomial< Specie, PolySize > Class Template Reference
Thermophysical models » Specie » Equation of state
Incompressible, polynomial form of equation of state, using a polynomial function for density.
#include <icoPolynomial.H>
Public Member Functions
icoPolynomial (const Specie &sp, const Polynomial< PolySize > &rhoPoly)
icoPolynomial (const dictionary &dict)
icoPolynomial (const word &name, const icoPolynomial &)
autoPtr< icoPolynomial > clone () const
scalar rho (scalar p, scalar T) const
scalar H (const scalar p, const scalar T) const
scalar Cp (scalar p, scalar T) const
scalar E (const scalar p, const scalar T) const
scalar Cv (scalar p, scalar T) const
scalar S (const scalar p, const scalar T) const
scalar psi (scalar p, scalar T) const
scalar Z (scalar p, scalar T) const
scalar CpMCv (scalar p, scalar T) const
void write (Ostream &os) const
void operator+= (const icoPolynomial &)
void operator*= (const scalar)
Static Public Member Functions
static autoPtr< icoPolynomial > New (const dictionary &dict)
static word typeName ()
Static Public Attributes
static const bool incompressible = true
static const bool isochoric = false
Friends
icoPolynomial operator+ (const icoPolynomial &, const icoPolynomial &)
icoPolynomial operator* (const scalar s, const icoPolynomial &)
icoPolynomial operator== (const icoPolynomial &, const icoPolynomial &)
Ostream & operator (Ostream &, const icoPolynomial &)
Detailed Description
template<class Specie, int PolySize = 8>
class Foam::icoPolynomial< Specie, PolySize >
Incompressible, polynomial form of equation of state, using a polynomial function for density.
Usage
Property Description
rhoCoeffs<8> Density polynomial coefficients
Example of the specification of the equation of state:
    equationOfState
    {
        rhoCoeffs<8>    ( 1000 -0.05 0.003 0 0 0 0 0 );
    }
The polynomial expression is evaluated as so:
Note
Input in [kg/m3], but internally uses [kg/m3/kmol].
Source files
icoPolynomial.H
icoPolynomialI.H
icoPolynomial.C
See also
Foam::Polynomial
Definition at line 120 of file icoPolynomial.H.
Constructor & Destructor Documentation
icoPolynomial() [1/3]
template<class Specie , int PolySize> icoPolynomial (const Specie & sp, const Polynomial< PolySize > & rhoPoly) inline
Definition at line 26 of file icoPolynomialI.H.
icoPolynomial() [2/3]
template<class Specie , int PolySize> icoPolynomial (const dictionary & dict) explicit
Definition at line 32 of file icoPolynomial.C.
icoPolynomial() [3/3]
template<class Specie , int PolySize = 8> icoPolynomial (const word & name, const icoPolynomial< Specie, PolySize > &) inline
Member Function Documentation
clone()
template<class Specie , int PolySize> Foam::autoPtr< Foam::icoPolynomial< Specie, PolySize > > clone () const inline
Definition at line 53 of file icoPolynomialI.H.
References Foam::New().
New()
template<class Specie , int PolySize> Foam::autoPtr< Foam::icoPolynomial< Specie, PolySize > > New (const dictionary & dict) inline static
Definition at line 61 of file icoPolynomialI.H.
References dict, and Foam::New().
typeName()
template<class Specie , int PolySize = 8> static word typeName () inline static
Definition at line 168 of file icoPolynomial.H.
rho()
template<class Specie , int PolySize> Foam::scalar rho (scalar p, scalar T) const inline
Definition at line 70 of file icoPolynomialI.H.
References T.
H()
template<class Specie , int PolySize> Foam::scalar H (const scalar p, const scalar T) const inline
Definition at line 81 of file icoPolynomialI.H.
Cp()
template<class Specie , int PolySize> Foam::scalar Cp (scalar p, scalar T) const inline
Definition at line 92 of file icoPolynomialI.H.
E()
template<class Specie , int PolySize> Foam::scalar E (const scalar p, const scalar T) const inline
Definition at line 103 of file icoPolynomialI.H.
Cv()
template<class Specie , int PolySize> Foam::scalar Cv (scalar p, scalar T) const inline
Definition at line 114 of file icoPolynomialI.H.
S()
template<class Specie , int PolySize> Foam::scalar S (const scalar p, const scalar T) const inline
Definition at line 125 of file icoPolynomialI.H.
psi()
template<class Specie , int PolySize> Foam::scalar psi (scalar p, scalar T) const inline
Definition at line 136 of file icoPolynomialI.H.
Z()
template<class Specie , int PolySize> Foam::scalar Z (scalar p, scalar T) const inline
Definition at line 147 of file icoPolynomialI.H.
CpMCv()
template<class Specie , int PolySize> Foam::scalar CpMCv (scalar p, scalar T) const inline
Definition at line 158 of file icoPolynomialI.H.
write()
template<class Specie , int PolySize> void write (Ostream & os) const
Definition at line 42 of file icoPolynomial.C.
References os().
operator+=()
template<class Specie , int PolySize = 8> void operator+= (const icoPolynomial< Specie, PolySize > &) inline
Definition at line 171 of file icoPolynomialI.H.
References Foam::mag(), and Y.
operator*=()
template<class Specie , int PolySize> void operator*= (const scalar s) inline
Definition at line 190 of file icoPolynomialI.H.
References s().
Friends And Related Symbol Documentation
operator+
template<class Specie , int PolySize = 8> icoPolynomial operator+ (const icoPolynomial< Specie, PolySize > & , const icoPolynomial< Specie, PolySize > &) friend
operator*
template<class Specie , int PolySize = 8> icoPolynomial operator* (const scalar s, const icoPolynomial< Specie, PolySize > &) friend
operator==
template<class Specie , int PolySize = 8> icoPolynomial operator== (const icoPolynomial< Specie, PolySize > & , const icoPolynomial< Specie, PolySize > &) friend
operator
template<class Specie , int PolySize = 8> Ostream & operator (Ostream & , const icoPolynomial< Specie, PolySize > &) friend
Member Data Documentation
incompressible
template<class Specie , int PolySize = 8> const bool incompressible = true static
Definition at line 177 of file icoPolynomial.H.
isochoric
template<class Specie , int PolySize = 8> const bool isochoric = false static
Definition at line 180 of file icoPolynomial.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/equationOfState/icoPolynomial/icoPolynomial.H
src/thermophysicalModels/specie/equationOfState/icoPolynomial/icoPolynomial.C
src/thermophysicalModels/specie/equationOfState/icoPolynomial/icoPolynomialI.H