OpenFOAM: wallBoiling Class Reference
wallBoiling Class Reference
Wall-boiling IATE source.
#include <wallBoiling.H>
Public Member Functions
TypeName ("wallBoiling")
wallBoiling (const IATE &iate, const dictionary &dict)
virtual ~wallBoiling ()=default
virtual tmp< fvScalarMatrix > R (const volScalarField &alphai, volScalarField &kappai) const
Public Member Functions inherited from IATEsource
TypeName ("IATEsource")
declareRunTimeSelectionTable (autoPtr, IATEsource, dictionary,(const IATE &iate, const dictionary &dict),(iate, dict))
IATEsource (const IATE &iate)
autoPtr< IATEsource > clone () const
virtual ~IATEsource ()=default
const phaseModel & phase () const
const twoPhaseSystem & fluid () const
const phaseModel & otherPhase () const
scalar phi () const
tmp< volScalarField > Ur () const
tmp< volScalarField > Ut () const
tmp< volScalarField > Re () const
tmp< volScalarField > CD () const
tmp< volScalarField > Mo () const
tmp< volScalarField > Eo () const
tmp< volScalarField > We () const
TypeName ("IATEsource")
declareRunTimeSelectionTable (autoPtr, IATEsource, dictionary,(const IATE &iate, const dictionary &dict),(iate, dict))
IATEsource (const IATE &iate)
autoPtr< IATEsource > clone () const
virtual ~IATEsource ()=default
const phaseModel & phase () const
const twoPhaseSystem & fluid () const
const phaseModel & otherPhase () const
scalar phi () const
tmp< volScalarField > Ur () const
tmp< volScalarField > Ut () const
tmp< volScalarField > Re () const
tmp< volScalarField > CD () const
tmp< volScalarField > Mo () const
tmp< volScalarField > Eo () const
tmp< volScalarField > We () const
virtual tmp< volScalarField > R () const =0
Additional Inherited Members
Static Public Member Functions inherited from IATEsource
static autoPtr< IATEsource > New (const word &type, const IATE &iate, const dictionary &dict)
static autoPtr< IATEsource > New (const word &type, const IATE &iate, const dictionary &dict)
Protected Attributes inherited from IATEsource
const IATE & iate_
Detailed Description
Wall-boiling IATE source.
Source files
wallBoiling.H
wallBoiling.C
Definition at line 51 of file wallBoiling.H.
Constructor & Destructor Documentation
wallBoiling()
wallBoiling (const IATE & iate, const dictionary & dict)
Definition at line 44 of file wallBoiling.C.
~wallBoiling()
virtual ~wallBoiling () virtual default
Member Function Documentation
TypeName()
TypeName ("wallBoiling")
R()
Foam::tmp< Foam::fvScalarMatrix > R (const volScalarField & alphai, volScalarField & kappai) const virtual
Implements IATEsource.
Definition at line 57 of file wallBoiling.C.
References IOobject::db(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimless, Foam::dimTime, forAll, IOobject::groupName(), mesh, Foam::name(), turbulenceModel::propertiesName, R, rho, phase::rho(), Foam::fvm::Sp(), timeName, and turbulence.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/twoPhaseSystem/diameterModels/IATE/IATEsources/wallBoiling/wallBoiling.H
src/phaseSystemModels/reactingEuler/twoPhaseSystem/diameterModels/IATE/IATEsources/wallBoiling/wallBoiling.C