OpenFOAM: PBiCICG< Type, DType, LUType > Class Template Reference
PBiCICG< Type, DType, LUType > Class Template Reference
Preconditioned bi-conjugate gradient solver for asymmetric lduMatrices using a run-time selectable preconditioner.
#include <PBiCICG.H>
Public Member Functions
TypeName ("PBiCICG")
PBiCICG (const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix, const dictionary &solverDict)
virtual ~PBiCICG ()=default
virtual SolverPerformance< Type > solve (Field< Type > &psi) const
Public Member Functions inherited from LduMatrix< Type, DType, LUType >::solver
virtual const word & type () const =0
declareRunTimeSelectionTable (autoPtr, solver, symMatrix,(const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix, const dictionary &solverDict),(fieldName, matrix, solverDict))
declareRunTimeSelectionTable (autoPtr, solver, asymMatrix,(const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix, const dictionary &solverDict),(fieldName, matrix, solverDict))
solver (const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix, const dictionary &solverDict)
virtual ~solver ()=default
const word & fieldName () const noexcept
const LduMatrix< Type, DType, LUType > & matrix () const noexcept
virtual void read (const dictionary &)
Type normFactor (const Field< Type > &psi, const Field< Type > &Apsi, Field< Type > &tmpField, const lduMatrix::normTypes normType) const
Type normFactor (const Field< Type > &psi, const Field< Type > &Apsi, Field< Type > &tmpField) const
Additional Inherited Members
Static Public Member Functions inherited from LduMatrix< Type, DType, LUType >::solver
static autoPtr< solver > New (const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix, const dictionary &solverDict)
Protected Member Functions inherited from LduMatrix< Type, DType, LUType >::solver
virtual void readControls ()
template<class T >
void readControl (const dictionary &dict, T &val, const word &key)
Protected Attributes inherited from LduMatrix< Type, DType, LUType >::solver
word fieldName_
const LduMatrix< Type, DType, LUType > & matrix_
dictionary controlDict_
int log_
label minIter_
label maxIter_
lduMatrix::normTypes normType_
Type tolerance_
Type relTol_
Detailed Description
template<class Type, class DType, class LUType>
class Foam::PBiCICG< Type, DType, LUType >
Preconditioned bi-conjugate gradient solver for asymmetric lduMatrices using a run-time selectable preconditioner.
Source files
PBiCICG.H
PBiCICG.C
Definition at line 49 of file PBiCICG.H.
Constructor & Destructor Documentation
PBiCICG()
template<class Type , class DType , class LUType > PBiCICG (const word & fieldName, const LduMatrix< Type, DType, LUType > & matrix, const dictionary & solverDict)
Definition at line 27 of file PBiCICG.C.
~PBiCICG()
template<class Type , class DType , class LUType > virtual ~PBiCICG () virtual default
Member Function Documentation
TypeName()
template<class Type , class DType , class LUType > TypeName ("PBiCICG< Type, DType, LUType >")
solve()
template<class Type , class DType , class LUType > Foam::SolverPerformance< Type > solve (Field< Type > & psi) const virtual
Implements LduMatrix< Type, DType, LUType >::solver.
Definition at line 47 of file PBiCICG.C.
References alpha, UPtrList< T >::begin(), beta(), Foam::cmptDivide(), Foam::cmptMag(), Foam::cmptMultiply(), Foam::endl(), Foam::gSumCmptMag(), Foam::gSumCmptProd(), Foam::Info, LduMatrix< Type, DType, LUType >::preconditioner::New(), psi, UPtrList< T >::size(), Foam::stabilise(), and Foam::Zero.
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/LduMatrix/Solvers/PBiCICG/PBiCICG.H
src/OpenFOAM/matrices/LduMatrix/Solvers/PBiCICG/PBiCICG.C