OpenFOAM: parallelFvGeometryScheme::transformOriented Class Reference
parallelFvGeometryScheme::transformOriented Class Reference
#include <parallelFvGeometryScheme.H>
Public Member Functions
template<class Type >
void operator() (const coupledPolyPatch &cpp, UList< Type > &fld) const
Detailed Description
Definition at line 115 of file parallelFvGeometryScheme.H.
Member Function Documentation
operator()()
template<class Type > void operator() (const coupledPolyPatch & cpp, UList< Type > & fld) const inline
Definition at line 120 of file parallelFvGeometryScheme.H.
References f(), fld(), and Foam::transformList().
The documentation for this class was generated from the following file:
src/finiteVolume/fvMesh/fvGeometryScheme/parallel/parallelFvGeometryScheme.H