OpenFOAM: patchEdgeFaceRegion Class Reference
patchEdgeFaceRegion Class Reference
Transport of region for use in PatchEdgeFaceWave.
#include <patchEdgeFaceRegion.H>
Public Member Functions
patchEdgeFaceRegion ()
patchEdgeFaceRegion (const label regioni)
label region () const
template<class TrackingData >
bool valid (TrackingData &td) const
template<class TrackingData >
void transform (const polyMesh &mesh, const indirectPrimitivePatch &patch, const tensor &rotTensor, const scalar tol, TrackingData &td)
template<class TrackingData >
bool updateEdge (const polyMesh &mesh, const indirectPrimitivePatch &patch, const label edgeI, const label facei, const patchEdgeFaceRegion &faceInfo, const scalar tol, TrackingData &td)
template<class TrackingData >
bool updateEdge (const polyMesh &mesh, const indirectPrimitivePatch &patch, const patchEdgeFaceRegion &edgeInfo, const bool sameOrientation, const scalar tol, TrackingData &td)
template<class TrackingData >
bool updateFace (const polyMesh &mesh, const indirectPrimitivePatch &patch, const label facei, const label edgeI, const patchEdgeFaceRegion &edgeInfo, const scalar tol, TrackingData &td)
template<class TrackingData >
bool equal (const patchEdgeFaceRegion &, TrackingData &) const
bool operator== (const patchEdgeFaceRegion &) const
bool operator!= (const patchEdgeFaceRegion &) const
Friends
Ostream & operator<< (Ostream &, const patchEdgeFaceRegion &)
Istream & operator>> (Istream &, patchEdgeFaceRegion &)
Detailed Description
Transport of region for use in PatchEdgeFaceWave.
Set element to -2 to denote blocked.
Source files
patchEdgeFaceRegion.H
patchEdgeFaceRegionI.H
patchEdgeFaceRegion.C
Definition at line 63 of file patchEdgeFaceRegion.H.
Constructor & Destructor Documentation
patchEdgeFaceRegion() [1/2]
patchEdgeFaceRegion () inline
Definition at line 71 of file patchEdgeFaceRegionI.H.
patchEdgeFaceRegion() [2/2]
patchEdgeFaceRegion (const label regioni) inline
Definition at line 77 of file patchEdgeFaceRegionI.H.
Member Function Documentation
region()
label region () const inline
Definition at line 99 of file patchEdgeFaceRegion.H.
valid()
template<class TrackingData > bool valid (TrackingData & td) const inline
Definition at line 89 of file patchEdgeFaceRegionI.H.
transform()
template<class TrackingData > void transform (const polyMesh & mesh, const indirectPrimitivePatch & patch, const tensor & rotTensor, const scalar tol, TrackingData & td) inline
Definition at line 96 of file patchEdgeFaceRegionI.H.
updateEdge() [1/2]
template<class TrackingData > bool updateEdge (const polyMesh & mesh, const indirectPrimitivePatch & patch, const label edgeI, const label facei, const patchEdgeFaceRegion & faceInfo, const scalar tol, TrackingData & td) inline
Definition at line 108 of file patchEdgeFaceRegionI.H.
References update().
updateEdge() [2/2]
template<class TrackingData > bool updateEdge (const polyMesh & mesh, const indirectPrimitivePatch & patch, const patchEdgeFaceRegion & edgeInfo, const bool sameOrientation, const scalar tol, TrackingData & td) inline
Definition at line 124 of file patchEdgeFaceRegionI.H.
References update().
updateFace()
template<class TrackingData > bool updateFace (const polyMesh & mesh, const indirectPrimitivePatch & patch, const label facei, const label edgeI, const patchEdgeFaceRegion & edgeInfo, const scalar tol, TrackingData & td) inline
Definition at line 139 of file patchEdgeFaceRegionI.H.
References update().
equal()
template<class TrackingData > bool equal (const patchEdgeFaceRegion & rhs, TrackingData & td) const inline
Definition at line 155 of file patchEdgeFaceRegionI.H.
References Foam::operator==().
operator==()
bool operator== (const patchEdgeFaceRegion & rhs) const inline
Definition at line 167 of file patchEdgeFaceRegionI.H.
operator!=()
bool operator!= (const patchEdgeFaceRegion & rhs) const inline
Definition at line 176 of file patchEdgeFaceRegionI.H.
Friends And Related Symbol Documentation
operator<<
Ostream & operator<< (Ostream & , const patchEdgeFaceRegion &) friend
operator>>
Istream & operator>> (Istream & , patchEdgeFaceRegion &) friend
The documentation for this class was generated from the following files:
src/meshTools/algorithms/PatchEdgeFaceWave/patchEdgeFaceRegion.H
src/meshTools/algorithms/PatchEdgeFaceWave/patchEdgeFaceRegionI.H