OpenFOAM: regIOobject Class Reference
regIOobject Class Reference abstract
regIOobject is an abstract class derived from IOobject to handle automatic object registration with the objectRegistry.
#include <regIOobject.H>
Inherits IOobject.
Inherited by AveragingMethod< Foam::Vector >, AveragingMethod< scalar >, BlendedInterfacialModel< Foam::dragModel >, BlendedInterfacialModel< Foam::virtualMassModel >, BlendedInterfacialModel< Foam::heatTransferModel >, BlendedInterfacialModel< Foam::liftModel >, BlendedInterfacialModel< Foam::wallLubricationModel >, BlendedInterfacialModel< Foam::turbulentDispersionModel >, CompactIOField< Foam::Field< label >, label >, CompactIOField< Foam::Field< scalar >, scalar >, CompactIOField< Foam::Field< Foam::Vector >, Foam::Vector >, CompactIOField< Foam::Field< Foam::SphericalTensor >, Foam::SphericalTensor >, CompactIOField< Foam::Field< Foam::SymmTensor >, Foam::SymmTensor >, CompactIOField< Foam::Field< Foam::Tensor >, Foam::Tensor >, CompactIOList< face, label >, DimensionedField< symmTensor, Foam::volMesh >, DimensionedField< symmTensor, volMesh >, DimensionedField< scalar, Foam::volMesh >, DimensionedField< scalar, volMesh >, DimensionedField< Type, pointMesh >, DimensionedField< vector, Foam::pointMesh >, DimensionedField< vector, Foam::volMesh >, DimensionedField< vector, volMesh >, DimensionedField< tensor, Foam::volMesh >, DimensionedField< tensor, volMesh >, DimensionedField< Foam::Vector, Foam::volMesh >, DimensionedField< Foam::Vector, Foam::pointMesh >, DimensionedField< scalar, Foam::surfaceMesh >, DimensionedField< scalar, surfaceMesh >, DimensionedField< scalar, Foam::pointMesh >, DimensionedField< scalar, pointMesh >, DimensionedField< vector, pointMesh >, DimensionedField< scalar, Foam::areaMesh >, DimensionedField< scalar, areaMesh >, DimensionedField< scalar, Foam::edgeMesh >, DimensionedField< Foam::Vector, Foam::areaMesh >, DimensionedField< Foam::Vector, Foam::edgeMesh >, DimensionedField< Foam::SphericalTensor, Foam::areaMesh >, DimensionedField< Foam::SphericalTensor, Foam::edgeMesh >, DimensionedField< Foam::SymmTensor, Foam::areaMesh >, DimensionedField< Foam::SymmTensor, Foam::edgeMesh >, DimensionedField< Foam::Tensor, Foam::areaMesh >, DimensionedField< Foam::Tensor, Foam::edgeMesh >, DimensionedField< Type, Foam::areaMesh >, DimensionedField< Type, Foam::edgeMesh >, DimensionedField< Foam::Vector, Foam::surfaceMesh >, DimensionedField< Foam::SphericalTensor, Foam::volMesh >, DimensionedField< Foam::SphericalTensor, Foam::surfaceMesh >, DimensionedField< Foam::SymmTensor, Foam::volMesh >, DimensionedField< Foam::SymmTensor, Foam::surfaceMesh >, DimensionedField< Foam::Tensor, Foam::volMesh >, DimensionedField< Foam::Tensor, Foam::surfaceMesh >, DimensionedField< Type, Foam::volMesh >, DimensionedField< Type, Foam::surfaceMesh >, DimensionedField< Type, Foam::pointMesh >, DimensionedField< vector, Foam::surfaceMesh >, DimensionedField< vector, surfaceMesh >, DimensionedField< scalar, triSurfacePointGeoMesh >, DimensionedField< Foam::SphericalTensor, Foam::pointMesh >, DimensionedField< Foam::SymmTensor, Foam::pointMesh >, DimensionedField< Foam::Tensor, Foam::pointMesh >, DimensionedField< tensor, Foam::areaMesh >, DimensionedField< tensor, areaMesh >, DimensionedField< vector, Foam::areaMesh >, DimensionedField< vector, areaMesh >, DimensionedField< scalar, edgeMesh >, GlobalIOField< vector >, GlobalIOList< kinematicParcelInjectionData >, GlobalIOList< reactingParcelInjectionData >, GlobalIOList< reactingMultiphaseParcelInjectionData >, IOField< label >, IOField< scalar >, IOField< Foam::Vector >, IOField< Foam::SphericalTensor >, IOField< Foam::SymmTensor >, IOField< Foam::Tensor >, IOList< label >, IOList< labelList >, IOPtrList< Foam::entry >, UniformDimensionedField< scalar >, UniformDimensionedField< vector >, ZoneMesh< pointZone, polyMesh >, ZoneMesh< faceZone, polyMesh >, ZoneMesh< cellZone, polyMesh >, ATCModel, AveragingMethod< Type >, BlendedInterfacialModel< ModelType >, CompactIOField< T, BaseType >, CompactIOList< T, BaseType >, DimensionedField< Type, GeoMesh >, GlobalIOField< Type >, GlobalIOList< Type >, IOField< Type >, IOFieldRef< Type >, IOList< T >, IOListRef< T >, IOMap< T >, IOPosition< CloudType >, IOPtrList< T >, IOmapDistribute, IOmapDistributePolyMesh, IOmapDistributePolyMeshRef, PDRDragModel, SLGThermo, SubDimensionedField< Type, GeoMesh >, UniformDimensionedField< Type >, ZoneMesh< ZoneType, MeshType >, adjointSolverManager, baseIOdictionary, coordinateSystems, decomposedBlockData, populationBalanceModel, dragModel, dragModel, exprResultGlobals, fvExprDriverWriter, extendedFeatureEdgeMesh, faBoundaryMesh, faBoundaryMeshEntries, featureEdgeMesh, fieldDictionary, adjointTurbulenceModel, lduPrimitiveMeshAssembly, lumpedPointIOMovement, meshObject, surfaceTensionModel, objectRegistry, objectiveManager, polyBoundaryMesh, polyBoundaryMeshEntries, polyTopoChanger, porosityModel, porousModel, solarLoadBase, rawIOField< Type >, surfaceTensionModel, refinementHistory, searchableSurface, solutionControl, surfZoneIOList, surfaceTensionModel, topoSet, virtualMassModel, and virtualMassModel.
Public Member Functions
TypeName ("regIOobject")
regIOobject (const IOobject &io, const bool isTimeObject=false)
regIOobject (const regIOobject &rio)
regIOobject (const regIOobject &rio, bool registerCopy)
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
regIOobject (const IOobject &io, const regIOobject &rio)
virtual ~regIOobject ()
bool checkIn ()
bool checkOut ()
virtual void addWatch ()
bool registered () const noexcept
bool ownedByRegistry () const noexcept
bool store ()
void release (const bool unregister=false) noexcept
label eventNo () const noexcept
label & eventNo () noexcept
bool upToDate (const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
void setUpToDate ()
virtual void rename (const word &newName)
const dictionary * findMetaData () const noexcept
dictionary & getMetaData () noexcept
void removeMetaData ()
virtual void updateMetaData ()
virtual fileName filePath () const
bool headerOk ()
Istream & readStream (const word &, const bool readOnProc=true)
void close ()
virtual bool readData (Istream &)
virtual bool read ()
virtual label addWatch (const fileName &)
const labelList & watchIndices () const noexcept
labelList & watchIndices () noexcept
virtual bool modified () const
virtual bool readIfModified ()
virtual bool writeData (Ostream &) const =0
virtual bool writeObject (IOstreamOption streamOpt, const bool writeOnProc) const
virtual bool write (const bool writeOnProc=true) const
virtual bool global () const
void operator= (const IOobject &io)
virtual bool writeObject (IOstreamOption::streamFormat fmt, IOstreamOption::versionNumber ver, IOstreamOption::compressionType cmp, const bool writeOnProc) const
Public Member Functions inherited from IOobject
TypeName ("IOobject")
IOobject (const IOobject &)=default
virtual ~IOobject ()=default
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const fileName &path, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const fileName &path, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const IOobject &io, const objectRegistry &registry)
IOobject (const IOobject &io, const word &name)
IOobject (const IOobject &io, const word &name, const fileName &local)
IOobject (const IOobject &io, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt)
IOobject (const IOobject &io, IOobjectOption::registerOption regOpt)
autoPtr< IOobject > clone () const
autoPtr< IOobject > clone (const objectRegistry &registry) const
const objectRegistry & db () const noexcept
const Time & time () const noexcept
const word & name () const noexcept
const word & headerClassName () const noexcept
word & headerClassName () noexcept
const string & note () const noexcept
string & note () noexcept
unsigned labelByteSize () const noexcept
unsigned scalarByteSize () const noexcept
void resetHeader (const word &newName=word::null)
bool hasHeaderClass () const noexcept
template<class Type >
bool isHeaderClass () const
template<class Type >
bool isHeaderClassName () const
word group () const
word member () const
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const noexcept
fileName & instance () noexcept
const fileName & local () const noexcept
fileName path () const
fileName path (const word &instance, const fileName &local=fileName::null) const
fileName objectPath () const
fileName objectRelPath () const
fileName localFilePath (const word &typeName, const bool search=true) const
fileName globalFilePath (const word &typeName, const bool search=true) const
IOstreamOption parseHeader (const dictionary &headerDict)
bool readHeader (Istream &is)
bool readHeader (dictionary &headerDict, Istream &is)
template<class Type >
bool typeHeaderOk (const bool checkType=true, const bool search=true, const bool verbose=true)
template<class Type >
void warnNoRereading () const
bool writeHeader (Ostream &os) const
bool writeHeader (Ostream &os, const word &objectType) const
void writeHeader (dictionary &dict, IOstreamOption streamOpt) const
void writeHeader (dictionary &dict, const word &objectType, IOstreamOption streamOpt) const
bool good () const noexcept
bool bad () const noexcept
InfoProxy< IOobject > info () const noexcept
void operator= (const IOobject &io)
template<>
bool isHeaderClass () const
template<class StringType >
Foam::word groupName (StringType base, const word &group)
Public Member Functions inherited from IOobjectOption
constexpr IOobjectOption (readOption rOpt=readOption::NO_READ, writeOption wOpt=writeOption::NO_WRITE, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (readOption rOpt, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (writeOption wOpt, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (registerOption registerObject, bool globalObject=false) noexcept
constexpr IOobjectOption (readOption rOpt, writeOption wOpt, bool registerObject, bool globalObject=false) noexcept
constexpr IOobjectOption (bool registerObject, bool globalObject=false) noexcept
readOption readOpt () const noexcept
readOption readOpt (readOption opt) noexcept
writeOption writeOpt () const noexcept
writeOption writeOpt (writeOption opt) noexcept
bool registerObject () const noexcept
bool registerObject (bool on) noexcept
bool globalObject () const noexcept
bool globalObject (bool on) noexcept
bool isAnyRead () const noexcept
bool isReadRequired () const noexcept
bool isReadOptional () const noexcept
readOption & readOpt () noexcept
writeOption & writeOpt () noexcept
bool & registerObject () noexcept
bool & globalObject () noexcept
Static Public Member Functions
template<class Type >
static Type & store (Type *p)
template<class Type >
static Type & store (autoPtr< Type > &ptr)
template<class Type >
static Type & store (autoPtr< Type > &&ptr)
template<class Type >
static Type & store (refPtr< Type > &ptr)
template<class Type >
static Type & store (refPtr< Type > &&ptr)
template<class Type >
static Type & store (tmp< Type > &ptr)
template<class Type >
static Type & store (tmp< Type > &&ptr)
Static Public Member Functions inherited from IOobject
static bool bannerEnabled () noexcept
static bool bannerEnabled (bool on) noexcept
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
template<class StringType >
static word groupName (StringType base, const word &group)
static word group (const word &name)
static word member (const word &name)
static word scopedName (const std::string &scope, const word &name)
static IOobject selectIO (const IOobject &io, const fileName &altFile, const word &ioName="")
static Ostream & writeBanner (Ostream &os, const bool noSyntaxHint=false)
static Ostream & writeDivider (Ostream &os)
static Ostream & writeEndDivider (Ostream &os)
Static Public Member Functions inherited from IOobjectOption
static bool isAnyRead (readOption opt) noexcept
static bool isReadRequired (readOption opt) noexcept
static bool isReadOptional (readOption opt) noexcept
static readOption lazierRead (readOption opt) noexcept
Protected Member Functions
bool readHeaderOk (const IOstreamOption::streamFormat fmt, const word &typeName)
Protected Member Functions inherited from IOobject
void setBad (const string &s)
Static Protected Attributes
static bool masterOnlyReading = false
Friends
class functionEntries::codeStream
class fileOperations::uncollatedFileOperation
Additional Inherited Members
Public Types inherited from IOobject
enum objectState : char { GOOD , BAD }
enum fileCheckTypes : char { timeStamp , timeStampMaster , inotify , inotifyMaster }
Public Types inherited from IOobjectOption
enum readOption : unsigned char {
NO_READ = 0 , MUST_READ = 0x1 , READ_MODIFIED = 0x3 , MUST_READ_IF_MODIFIED = 0x3 ,
LAZY_READ = 0x4 , READ_IF_PRESENT = 0x4
}
enum writeOption : unsigned char { NO_WRITE = 0 , AUTO_WRITE = 0x10 }
enum registerOption : unsigned char { NO_REGISTER = 0 , REGISTER = 1 }
Static Public Attributes inherited from IOobject
static const Enum< fileCheckTypes > fileCheckTypesNames
static char scopeSeparator
static fileCheckTypes fileModificationChecking
static float fileModificationSkew
static int maxFileModificationPolls
Static Protected Member Functions inherited from IOobject
static void writeHeaderContent (Ostream &os, const IOobject &io, const word &objectType, const dictionary *metaDataDict=nullptr)
static void writeHeaderContent (dictionary &dict, const IOobject &io, const word &objectType, IOstreamOption streamOpt, const dictionary *metaDataDict=nullptr)
Detailed Description
regIOobject is an abstract class derived from IOobject to handle automatic object registration with the objectRegistry.
Source files
regIOobject.H
regIOobject.C
regIOobjectRead.C
regIOobjectWrite.C
Definition at line 65 of file regIOobject.H.
Constructor & Destructor Documentation
regIOobject() [1/5]
regIOobject (const IOobject & io, const bool isTimeObject = false)
Definition at line 43 of file regIOobject.C.
References regIOobject::checkIn(), and IOobjectOption::registerObject().
regIOobject() [2/5]
regIOobject (const regIOobject & rio)
Definition at line 61 of file regIOobject.C.
regIOobject() [3/5]
regIOobject (const regIOobject & rio, bool registerCopy)
Definition at line 75 of file regIOobject.C.
References regIOobject::checkIn(), and regIOobject::checkOut().
regIOobject() [4/5]
regIOobject (const word & newName, const regIOobject & rio, bool registerCopy)
Definition at line 97 of file regIOobject.C.
References regIOobject::checkIn().
regIOobject() [5/5]
regIOobject (const IOobject & io, const regIOobject & rio)
Definition at line 122 of file regIOobject.C.
References regIOobject::checkIn(), and IOobjectOption::registerObject().
~regIOobject()
~regIOobject () virtual
Definition at line 145 of file regIOobject.C.
References Foam::endl(), Foam::name(), path(), Foam::Pout, and Foam::type().
Member Function Documentation
readHeaderOk()
bool readHeaderOk (const IOstreamOption::streamFormat fmt, const word & typeName) protected
Definition at line 31 of file regIOobjectRead.C.
References Pstream::broadcast(), Foam::fileHandler, IOobject::fileModificationChecking, regIOobject::global(), regIOobject::headerOk(), IOobject::inotifyMaster, IOobjectOption::isReadOptional(), IOobjectOption::isReadRequired(), UPstream::master(), UPstream::parRun(), and IOobject::timeStampMaster.
Referenced by GlobalIOField< Type >::GlobalIOField(), GlobalIOField< Type >::GlobalIOField(), GlobalIOField< Type >::GlobalIOField(), GlobalIOList< Type >::GlobalIOList(), GlobalIOList< Type >::GlobalIOList(), GlobalIOList< Type >::GlobalIOList(), GlobalIOList< Type >::GlobalIOList(), IOdictionary::IOdictionary(), localIOdictionary::localIOdictionary(), UniformDimensionedField< Type >::UniformDimensionedField(), UniformDimensionedField< Type >::UniformDimensionedField(), and unwatchedIOdictionary::unwatchedIOdictionary().
TypeName()
TypeName ("regIOobject")
checkIn()
bool checkIn ()
Definition at line 187 of file regIOobject.C.
References Foam::abort(), polyMesh::defaultRegion, Foam::endl(), Foam::FatalError, FatalErrorInFunction, Foam::name(), and WarningInFunction.
Referenced by regIOobject::regIOobject(), regIOobject::regIOobject(), regIOobject::regIOobject(), and regIOobject::regIOobject().
checkOut()
bool checkOut ()
Definition at line 223 of file regIOobject.C.
References PtrList< T >::clear(), Foam::fileHandler, and forAllReverse.
Referenced by regionFunctionObject::clearObject(), regionFunctionObject::clearObjects(), removeRegisteredObject::execute(), regIOobject::regIOobject(), motionSolver::stealRegistration(), and lumpedPointDisplacementPointPatchVectorField::~lumpedPointDisplacementPointPatchVectorField().
addWatch() [1/2]
void addWatch () virtual
Reimplemented in unwatchedIOdictionary.
Definition at line 266 of file regIOobject.C.
References Foam::abort(), PtrList< T >::append(), Pstream::broadcast(), PtrList< T >::clear(), f(), Foam::FatalError, FatalErrorInFunction, Foam::fileHandler, IOobject::fileModificationChecking, forAll, forAllReverse, IOobject::inotifyMaster, UPstream::master(), IOobjectOption::MUST_READ_IF_MODIFIED, UPstream::parRun(), PtrList< T >::resize(), UList< T >::size(), IOobject::timeStampMaster, and Foam::type().
Referenced by IOdictionary::IOdictionary(), IOdictionary::IOdictionary(), IOPtrList< T >::IOPtrList(), IOPtrList< T >::IOPtrList(), localIOdictionary::localIOdictionary(), localIOdictionary::localIOdictionary(), IOPtrList< Foam::entry >::operator=(), schemesLookup::schemesLookup(), and solution::solution().
registered()
bool registered () const inline noexcept
Definition at line 24 of file regIOobjectI.H.
ownedByRegistry()
bool ownedByRegistry () const inline noexcept
Definition at line 30 of file regIOobjectI.H.
Referenced by objectRegistry::clear(), regionFunctionObject::clearObject(), regionFunctionObject::clearObjects(), objectRegistry::erase(), and removeRegisteredObject::execute().
store() [1/8]
bool store () inline
Definition at line 36 of file regIOobjectI.H.
References Foam::name(), Foam::nl, and WarningInFunction.
Referenced by objectRegistry::cacheTemporaryObject(), codedBase::codeDict(), adjointBoundaryCondition< Type >::computePatchGrad(), mappedPatchBase::constructIOField(), gradScheme< Type >::grad(), volPointInterpolation::interpolate(), volPointInterpolation::interpolate(), lumpedPointDisplacementPointPatchVectorField::movement(), zoneDistribute::New(), zoneCPCStencil::New(), options::New(), processorColour::New(), MeshObject< Mesh, MeshObjectType, Type >::New(), coordinateSystems::New(), polySurface::polySurface(), fvExprDriver::readAndRegister(), and mappedPatchBase::storeField().
store() [2/8]
template<class Type > Type & store (Type * p) inline static
Definition at line 53 of file regIOobjectI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and p.
store() [3/8]
template<class Type > Type & store (autoPtr< Type > & ptr) inline static
Definition at line 77 of file regIOobjectI.H.
References PtrList< T >::release().
store() [4/8]
template<class Type > Type & store (autoPtr< Type > && ptr) inline static
Definition at line 85 of file regIOobjectI.H.
store() [5/8]
template<class Type > Type & store (refPtr< Type > & ptr) inline static
Definition at line 93 of file regIOobjectI.H.
References UPtrList< T >::get(), IOobject::name(), p, PtrList< T >::release(), and WarningInFunction.
store() [6/8]
template<class Type > Type & store (refPtr< Type > && ptr) inline static
Definition at line 126 of file regIOobjectI.H.
store() [7/8]
template<class Type > Type & store (tmp< Type > & ptr) inline static
Definition at line 134 of file regIOobjectI.H.
References UPtrList< T >::get(), IOobject::name(), p, and WarningInFunction.
store() [8/8]
template<class Type > Type & store (tmp< Type > && ptr) inline static
Definition at line 167 of file regIOobjectI.H.
release()
void release (const bool unregister = false) inline noexcept
Definition at line 174 of file regIOobjectI.H.
Referenced by objectRegistry::clear(), and objectRegistry::erase().
eventNo() [1/2]
Foam::label eventNo () const inline noexcept
Definition at line 184 of file regIOobjectI.H.
Referenced by cyclicACMIFvPatch::cyclicACMIFvPatch(), triSurfaceMesh::movePoints(), cyclicACMIPolyPatch::updateAreas(), and regIOobject::upToDate().
eventNo() [2/2]
Foam::label & eventNo () inline noexcept
Definition at line 189 of file regIOobjectI.H.
upToDate() [1/4]
bool upToDate (const regIOobject & a) const
Definition at line 338 of file regIOobject.C.
References regIOobject::eventNo(), and Foam::labelMax.
upToDate() [2/4]
bool upToDate (const regIOobject & a, const regIOobject & b) const
Definition at line 377 of file regIOobject.C.
References b.
upToDate() [3/4]
bool upToDate (const regIOobject & a, const regIOobject & b, const regIOobject & c) const
Definition at line 387 of file regIOobject.C.
References b.
upToDate() [4/4]
bool upToDate (const regIOobject & a, const regIOobject & b, const regIOobject & c, const regIOobject & d) const
Definition at line 398 of file regIOobject.C.
References b.
setUpToDate()
void setUpToDate ()
Definition at line 410 of file regIOobject.C.
Referenced by cyclicACMIPolyPatch::updateAreas().
rename()
void rename (const word & newName) virtual
Reimplemented from IOobject.
Reimplemented in objectRegistry.
Definition at line 416 of file regIOobject.C.
References IOobject::rename().
Referenced by heThermo< BasicThermo, MixtureType >::alphaEff(), heThermo< BasicThermo, MixtureType >::alphahe(), RASModelVariables::copyAndRename(), if(), and objectRegistry::rename().
findMetaData()
const Foam::dictionary * findMetaData () const virtual noexcept
Reimplemented from IOobject.
Definition at line 26 of file regIOobjectMetaData.C.
References UPtrList< T >::get().
getMetaData()
Foam::dictionary & getMetaData () noexcept
Definition at line 32 of file regIOobjectMetaData.C.
removeMetaData()
void removeMetaData ()
Definition at line 42 of file regIOobjectMetaData.C.
updateMetaData()
void updateMetaData () virtual
Reimplemented in ZoneMesh< ZoneType, MeshType >, ZoneMesh< cellZone, polyMesh >, ZoneMesh< faceZone, polyMesh >, and ZoneMesh< pointZone, polyMesh >.
Definition at line 48 of file regIOobjectMetaData.C.
filePath()
Foam::fileName filePath () const virtual
Reimplemented in porosityModel, extendedFeatureEdgeMesh, featureEdgeMesh, searchableSurface, triSurfaceMesh, GlobalIOField< Type >, GlobalIOField< vector >, GlobalIOList< Type >, GlobalIOList< kinematicParcelInjectionData >, GlobalIOList< reactingMultiphaseParcelInjectionData >, GlobalIOList< reactingParcelInjectionData >, IOdictionary, localIOdictionary, unwatchedIOdictionary, IOMap< T >, UniformDimensionedField< Type >, UniformDimensionedField< scalar >, UniformDimensionedField< vector >, distributedTriSurfaceMesh, and baseIOdictionary.
Definition at line 431 of file regIOobject.C.
References Foam::type().
headerOk()
bool headerOk ()
Definition at line 437 of file regIOobject.C.
References Foam::endl(), Foam::fileHandler, IOWarningInFunction, and Foam::type().
Referenced by atmNutSource::atmNutSource(), decomposedBlockData::decomposedBlockData(), extendedFeatureEdgeMesh::extendedFeatureEdgeMesh(), faBoundaryMeshEntries::faBoundaryMeshEntries(), featureEdgeMesh::featureEdgeMesh(), fvExprDriverWriter::fvExprDriverWriter(), IOPtrList< T >::IOPtrList(), IOPtrList< T >::IOPtrList(), polyBoundaryMeshEntries::polyBoundaryMeshEntries(), regIOobject::readHeaderOk(), schemesLookup::schemesLookup(), solution::solution(), topoSet::topoSet(), and topoSet::topoSet().
readStream()
Foam::Istream & readStream (const word & expectName, const bool readOnProc = true)
Definition at line 118 of file regIOobjectRead.C.
References Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, Foam::name(), Foam::Pout, UPtrList< T >::size(), and Foam::type().
Referenced by DimensionedField< Type, GeoMesh >::DimensionedField(), extendedFeatureEdgeMesh::extendedFeatureEdgeMesh(), faBoundaryMeshEntries::faBoundaryMeshEntries(), featureEdgeMesh::featureEdgeMesh(), fieldDictionary::fieldDictionary(), fvExprDriverWriter::fvExprDriverWriter(), IOPtrList< T >::IOPtrList(), IOPtrList< T >::IOPtrList(), lumpedPointIOMovement::lumpedPointIOMovement(), IOPtrList< Foam::entry >::operator=(), polyBoundaryMeshEntries::polyBoundaryMeshEntries(), surfZoneIOList::surfZoneIOList(), topoSet::topoSet(), and topoSet::topoSet().
close()
void close ()
Definition at line 161 of file regIOobjectRead.C.
References Foam::endl(), and Foam::Pout.
Referenced by extendedFeatureEdgeMesh::extendedFeatureEdgeMesh(), featureEdgeMesh::featureEdgeMesh(), fieldDictionary::fieldDictionary(), IOPtrList< T >::IOPtrList(), IOPtrList< T >::IOPtrList(), lumpedPointIOMovement::lumpedPointIOMovement(), IOPtrList< Foam::entry >::operator=(), adjointRASModel::read(), surfZoneIOList::surfZoneIOList(), topoSet::topoSet(), and topoSet::topoSet().
readData()
bool readData (Istream &) virtual
Reimplemented in refinementHistory, IOPosition< CloudType >, extendedFeatureEdgeMesh, featureEdgeMesh, baseIOdictionary, UniformDimensionedField< Type >, UniformDimensionedField< scalar >, UniformDimensionedField< vector >, IOmapDistribute, fvExprDriverWriter, lumpedPointIOMovement, GlobalIOField< Type >, GlobalIOField< vector >, GlobalIOList< Type >, GlobalIOList< kinematicParcelInjectionData >, GlobalIOList< reactingMultiphaseParcelInjectionData >, GlobalIOList< reactingParcelInjectionData >, IOmapDistributePolyMesh, IOmapDistributePolyMeshRef, and exprResultGlobals.
Definition at line 175 of file regIOobjectRead.C.
read()
bool read () virtual
Reimplemented in PDRDragModel, twoPhaseMixtureThermo, incompressibleTwoPhaseInteractingMixture, laserDTRM, constant, interfaceHeatResistance, temperaturePhaseChangeTwoPhaseMixture, thermoIncompressibleTwoPhaseMixture, twoPhaseMixtureEThermo, incompressibleThreePhaseMixture, Kunz, Merkle, SchnerrSauer, multiphaseMixture, combustionModel, CombustionModel< ReactionThermo >, diffusion< ReactionThermo, ThermoType >, diffusionMulticomponent< ReactionThermo, ThermoType >, EDC< ReactionThermo >, eddyDissipationDiffusionModel< ReactionThermo, ThermoType >, eddyDissipationModelBase< ReactionThermo, ThermoType >, FSD< ReactionThermo, ThermoType >, infinitelyFastChemistry< ReactionThermo, ThermoType >, laminar< ReactionThermo >, noCombustion< ReactionThermo >, PaSR< ReactionThermo >, singleStepCombustion< ReactionThermo, ThermoType >, zoneCombustion< ReactionThermo >, motionSolver, refinementHistory, crankConRod, engineTime, options, options, IOMRFZoneList, IOporosityModelList, porosityModel, pimpleControl, simpleControl, solutionControl, rpm, SRFModel, decomposedBlockData, Time, schemesLookup, solution, tolerances, optimisationManager, SIMPLEControlOpt, SIMPLEControl, SIMPLEControlSingleRun, adjointkOmegaSST, adjointLaminar, adjointRASModel, adjointSpalartAllmaras, multiphaseSystem, multiphaseInterSystem, multiphaseSystem, phaseModel, phaseModel, phaseSystem, phaseModel, twoPhaseSystem, noPyrolysis, pyrolysisModel, reactingOneDim, thermo, regionModel, regionModel1D, singleLayerRegion, kinematicSingleLayer, surfaceFilmRegionModel, thermoSingleLayer, noThermo, thermalBaffle, thermalBaffleModel, rigidBodyMeshMotion, rigidBodyMeshMotionSolver, sixDoFRigidBodyMotionSolver, basicThermo, fvDOM, noRadiation, opaqueSolid, P1, solarLoad, viewFactor, solidThermo, immiscibleIncompressibleTwoPhaseMixture, incompressibleTwoPhaseMixture, singlePhaseTransportModel, phaseChangeTwoPhaseMixture, adjointTurbulenceModel, radiationModel, and turbulenceModel.
Definition at line 181 of file regIOobjectRead.C.
References IOstreamOption::BINARY, PtrList< T >::clear(), Foam::fileHandler, IOobject::fileModificationChecking, forAll, forAllReverse, IOobject::inotifyMaster, PtrList< T >::setSize(), UPtrList< T >::size(), IOobject::timeStampMaster, and Foam::type().
Referenced by columnFvMesh::columnFvMesh(), combustionModel::read(), motionSolver::read(), IOMRFZoneList::read(), IOporosityModelList::read(), SRFModel::read(), schemesLookup::read(), solution::read(), tolerances::read(), optimisationManager::read(), multiphaseSystem::read(), multiphaseInterSystem::read(), phaseSystem::read(), twoPhaseSystem::read(), regionModel::read(), basicThermo::read(), solidThermo::read(), incompressibleTwoPhaseMixture::read(), singlePhaseTransportModel::read(), radiationModel::read(), turbulenceModel::read(), and SimplifiedDynamicFvMesh< DynamicMeshType >::SimplifiedDynamicFvMesh().
addWatch() [2/2]
Foam::label addWatch (const fileName & f) virtual
Reimplemented in unwatchedIOdictionary.
Definition at line 242 of file regIOobject.C.
References PtrList< T >::append(), f(), Foam::fileHandler, IOobjectOption::MUST_READ_IF_MODIFIED, and UPtrList< T >::size().
watchIndices() [1/2]
const Foam::labelList & watchIndices () const inline noexcept
Definition at line 195 of file regIOobjectI.H.
Referenced by Time::readDict().
watchIndices() [2/2]
Foam::labelList & watchIndices () inline noexcept
Definition at line 201 of file regIOobjectI.H.
modified()
bool modified () const virtual
Reimplemented in objectRegistry.
Definition at line 230 of file regIOobjectRead.C.
References Foam::fileHandler, forAllReverse, and fileMonitor::UNMODIFIED.
readIfModified()
bool readIfModified () virtual
Reimplemented in objectRegistry.
Definition at line 244 of file regIOobjectRead.C.
References Foam::endl(), Foam::fileHandler, forAllReverse, InfoInFunction, UPtrList< T >::last(), Foam::name(), Foam::read(), and fileMonitor::UNMODIFIED.
writeData()
virtual bool writeData (Ostream &) const pure virtual
Implemented in solarLoadBase, SLGThermo, PDRDragModel, refinementHistory, polyTopoChanger, faBoundaryMeshEntries, solutionControl, lduPrimitiveMeshAssembly, AveragingMethod< Type >, AveragingMethod< Foam::Vector >, AveragingMethod< scalar >, extendedFeatureEdgeMesh, featureEdgeMesh, searchableBox, searchableCone, searchableCylinder, searchableDisk, searchableExtrudedCircle, searchablePlane, searchablePlate, searchableRotatedBox, searchableSphere, searchableSurfaceCollection, triSurfaceMesh, topoSet, CompactIOList< T, BaseType >, CompactIOList< face, label >, baseIOdictionary, objectRegistry, GeometricField< Type, PatchField, GeoMesh >, GeometricField< Foam::SphericalTensor, Foam::faePatchField, Foam::edgeMesh >, GeometricField< Foam::SphericalTensor, Foam::faPatchField, Foam::areaMesh >, GeometricField< Foam::SphericalTensor, Foam::fvPatchField, Foam::volMesh >, GeometricField< Foam::SphericalTensor, Foam::fvsPatchField, Foam::surfaceMesh >, GeometricField< Foam::SphericalTensor, Foam::pointPatchField, Foam::pointMesh >, GeometricField< Foam::SymmTensor, Foam::faePatchField, Foam::edgeMesh >, GeometricField< Foam::SymmTensor, Foam::faPatchField, Foam::areaMesh >, GeometricField< Foam::SymmTensor, Foam::fvPatchField, Foam::volMesh >, GeometricField< Foam::SymmTensor, Foam::fvsPatchField, Foam::surfaceMesh >, GeometricField< Foam::SymmTensor, Foam::pointPatchField, Foam::pointMesh >, GeometricField< Foam::Tensor, Foam::faePatchField, Foam::edgeMesh >, GeometricField< Foam::Tensor, Foam::faPatchField, Foam::areaMesh >, GeometricField< Foam::Tensor, Foam::fvPatchField, Foam::volMesh >, GeometricField< Foam::Tensor, Foam::fvsPatchField, Foam::surfaceMesh >, GeometricField< Foam::Tensor, Foam::pointPatchField, Foam::pointMesh >, GeometricField< Foam::Vector, Foam::faePatchField, Foam::edgeMesh >, GeometricField< Foam::Vector, Foam::faPatchField, Foam::areaMesh >, GeometricField< Foam::Vector, Foam::fvPatchField, Foam::volMesh >, GeometricField< Foam::Vector, Foam::fvsPatchField, Foam::surfaceMesh >, GeometricField< Foam::Vector, Foam::pointPatchField, Foam::pointMesh >, GeometricField< scalar, faePatchField, edgeMesh >, GeometricField< scalar, faPatchField, areaMesh >, GeometricField< scalar, Foam::faePatchField, Foam::edgeMesh >, GeometricField< scalar, Foam::faPatchField, Foam::areaMesh >, GeometricField< scalar, Foam::fvPatchField, Foam::volMesh >, GeometricField< scalar, Foam::fvsPatchField, Foam::surfaceMesh >, GeometricField< scalar, Foam::pointPatchField, Foam::pointMesh >, GeometricField< scalar, fvPatchField, volMesh >, GeometricField< scalar, fvsPatchField, surfaceMesh >, GeometricField< scalar, pointPatchField, pointMesh >, GeometricField< symmTensor, fvPatchField, volMesh >, GeometricField< tensor, faPatchField, areaMesh >, GeometricField< tensor, fvPatchField, volMesh >, GeometricField< Type, Foam::fvPatchField, Foam::volMesh >, GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh >, GeometricField< Type, Foam::pointPatchField, Foam::pointMesh >, GeometricField< Type, pointPatchField, pointMesh >, GeometricField< vector, faPatchField, areaMesh >, GeometricField< vector, fvPatchField, volMesh >, GeometricField< vector, fvsPatchField, surfaceMesh >, GeometricField< vector, pointPatchField, pointMesh >, UniformDimensionedField< Type >, UniformDimensionedField< scalar >, UniformDimensionedField< vector >, IOmapDistribute, polyBoundaryMeshEntries, ATCModel, objectiveManager, adjointSolverManager, solver, adjointTurbulenceModel, populationBalanceModel, liquidProperties, powerLawLopesdaCosta, faBoundaryMesh, DarcyForchheimer, fixedCoeff, porosityModel, powerLaw, solidification, fvExprDriverWriter, IOPosition< CloudType >, lumpedPointIOMovement, searchableSurfaceWithGaps, fieldDictionary, CompactIOField< T, BaseType >, CompactIOField< Foam::Field< Foam::SphericalTensor >, Foam::SphericalTensor >, CompactIOField< Foam::Field< Foam::SymmTensor >, Foam::SymmTensor >, CompactIOField< Foam::Field< Foam::Tensor >, Foam::Tensor >, CompactIOField< Foam::Field< Foam::Vector >, Foam::Vector >, CompactIOField< Foam::Field< label >, label >, CompactIOField< Foam::Field< scalar >, scalar >, decomposedBlockData, GlobalIOField< Type >, GlobalIOField< vector >, GlobalIOList< Type >, GlobalIOList< kinematicParcelInjectionData >, GlobalIOList< reactingMultiphaseParcelInjectionData >, GlobalIOList< reactingParcelInjectionData >, IOField< Type >, IOField< Foam::SphericalTensor >, IOField< Foam::SymmTensor >, IOField< Foam::Tensor >, IOField< Foam::Vector >, IOField< label >, IOField< scalar >, IOFieldRef< Type >, IOList< T >, IOList< label >, IOList< labelList >, IOListRef< T >, IOMap< T >, IOPtrList< T >, IOPtrList< Foam::entry >, rawIOField< Type >, exprResultGlobals, DimensionedField< Type, GeoMesh >, DimensionedField< Foam::SphericalTensor, Foam::areaMesh >, DimensionedField< Foam::SphericalTensor, Foam::edgeMesh >, DimensionedField< Foam::SphericalTensor, Foam::pointMesh >, DimensionedField< Foam::SphericalTensor, Foam::surfaceMesh >, DimensionedField< Foam::SphericalTensor, Foam::volMesh >, DimensionedField< Foam::SymmTensor, Foam::areaMesh >, DimensionedField< Foam::SymmTensor, Foam::edgeMesh >, DimensionedField< Foam::SymmTensor, Foam::pointMesh >, DimensionedField< Foam::SymmTensor, Foam::surfaceMesh >, DimensionedField< Foam::SymmTensor, Foam::volMesh >, DimensionedField< Foam::Tensor, Foam::areaMesh >, DimensionedField< Foam::Tensor, Foam::edgeMesh >, DimensionedField< Foam::Tensor, Foam::pointMesh >, DimensionedField< Foam::Tensor, Foam::surfaceMesh >, DimensionedField< Foam::Tensor, Foam::volMesh >, DimensionedField< Foam::Vector, Foam::areaMesh >, DimensionedField< Foam::Vector, Foam::edgeMesh >, DimensionedField< Foam::Vector, Foam::pointMesh >, DimensionedField< Foam::Vector, Foam::surfaceMesh >, DimensionedField< Foam::Vector, Foam::volMesh >, DimensionedField< scalar, areaMesh >, DimensionedField< scalar, edgeMesh >, DimensionedField< scalar, Foam::areaMesh >, DimensionedField< scalar, Foam::edgeMesh >, DimensionedField< scalar, Foam::pointMesh >, DimensionedField< scalar, Foam::surfaceMesh >, DimensionedField< scalar, Foam::volMesh >, DimensionedField< scalar, pointMesh >, DimensionedField< scalar, surfaceMesh >, DimensionedField< scalar, triSurfacePointGeoMesh >, DimensionedField< scalar, volMesh >, DimensionedField< symmTensor, Foam::volMesh >, DimensionedField< symmTensor, volMesh >, DimensionedField< tensor, areaMesh >, DimensionedField< tensor, Foam::areaMesh >, DimensionedField< tensor, Foam::volMesh >, DimensionedField< tensor, volMesh >, DimensionedField< Type, Foam::areaMesh >, DimensionedField< Type, Foam::edgeMesh >, DimensionedField< Type, Foam::pointMesh >, DimensionedField< Type, Foam::surfaceMesh >, DimensionedField< Type, Foam::volMesh >, DimensionedField< Type, pointMesh >, DimensionedField< vector, areaMesh >, DimensionedField< vector, Foam::areaMesh >, DimensionedField< vector, Foam::pointMesh >, DimensionedField< vector, Foam::surfaceMesh >, DimensionedField< vector, Foam::volMesh >, DimensionedField< vector, pointMesh >, DimensionedField< vector, surfaceMesh >, DimensionedField< vector, volMesh >, profiling, IOmapDistributePolyMesh, IOmapDistributePolyMeshRef, polyBoundaryMesh, ZoneMesh< ZoneType, MeshType >, ZoneMesh< cellZone, polyMesh >, ZoneMesh< faceZone, polyMesh >, ZoneMesh< pointZone, polyMesh >, coordinateSystems, objective, NURBS3DVolume, adjointSolver, adjointSimple, RASTurbulenceModel, simple, porousModel, surfaceTensionModel, BlendedInterfacialModel< ModelType >, BlendedInterfacialModel< Foam::dragModel >, BlendedInterfacialModel< Foam::heatTransferModel >, BlendedInterfacialModel< Foam::liftModel >, BlendedInterfacialModel< Foam::turbulentDispersionModel >, BlendedInterfacialModel< Foam::virtualMassModel >, BlendedInterfacialModel< Foam::wallLubricationModel >, surfaceTensionModel, dragModel, virtualMassModel, dragModel, virtualMassModel, surfZoneIOList, constant, temperatureDependent, and surfaceTensionModel.
writeObject() [1/2]
bool writeObject (IOstreamOption streamOpt, const bool writeOnProc) const virtual
Reimplemented in dynamicRefineFvMesh, motionSolver, faBoundaryMesh, fvMesh, Cloud< ParticleType >, Cloud< basicKinematicCollidingParcel >, Cloud< Foam::DTRMParticle >, Cloud< Foam::molecule >, Cloud< Foam::passiveParticle >, Cloud< indexedParticle >, Cloud< injectedParticle >, Cloud< molecule >, Cloud< ParcelType >, Cloud< parcelType >, Cloud< passiveParticle >, Cloud< passivePositionParticle >, Cloud< solidParticle >, Cloud< streamLineParticle >, Cloud< typename CloudType::parcelType >, Cloud< wallBoundedStreamLineParticle >, triSurfaceMesh, cellZoneSet, faceZoneSet, pointZoneSet, CompactIOField< T, BaseType >, CompactIOField< Foam::Field< Foam::SphericalTensor >, Foam::SphericalTensor >, CompactIOField< Foam::Field< Foam::SymmTensor >, Foam::SymmTensor >, CompactIOField< Foam::Field< Foam::Tensor >, Foam::Tensor >, CompactIOField< Foam::Field< Foam::Vector >, Foam::Vector >, CompactIOField< Foam::Field< label >, label >, CompactIOField< Foam::Field< scalar >, scalar >, CompactIOList< T, BaseType >, CompactIOList< face, label >, decomposedBlockData, objectRegistry, Time, polyBoundaryMesh, dynamicOversetFvMesh, staticOversetFvMesh, distributedTriSurfaceMesh, rigidBodyMeshMotion, rigidBodyMeshMotionSolver, sixDoFRigidBodyMotionSolver, polySurface, surfMesh, coordinateSystems, unmappedPassivePositionParticleCloud, and profiling.
Definition at line 28 of file regIOobjectWrite.C.
References Foam::endl(), Foam::fileHandler, IOobject::fileModificationChecking, IOobject::good(), IOobject::inotifyMaster, IOobject::instance(), UList< T >::last(), UPstream::master(), IOobject::name(), IOobject::objectPath(), Foam::Pout, SeriousErrorInFunction, UList< T >::size(), Foam::system(), IOobject::time(), timeName, and IOobject::timeStampMaster.
Referenced by faBoundaryMesh::writeObject(), cellZoneSet::writeObject(), faceZoneSet::writeObject(), pointZoneSet::writeObject(), CompactIOField< T, BaseType >::writeObject(), CompactIOList< T, BaseType >::writeObject(), polyBoundaryMesh::writeObject(), coordinateSystems::writeObject(), profiling::writeObject(), and regIOobject::writeObject().
write()
bool write (const bool writeOnProc = true) const virtual
Reimplemented in objectiveIncompressible, objective, incompressibleAdjointSolver, incompressiblePrimalSolver, solver, SIMPLEControlOpt, SIMPLEControlSingleRun, SIMPLEControl, faMesh, fvMesh, IOPosition< CloudType >, AveragingMethod< Type >, AveragingMethod< Foam::Vector >, AveragingMethod< scalar >, and extendedFeatureEdgeMesh.
Definition at line 127 of file regIOobjectWrite.C.
Referenced by rotorDiskSource::addSup(), rotorDiskSource::addSup(), columnFvMesh::columnFvMesh(), diffusionMulticomponent< ReactionThermo, ThermoType >::correct(), contactAngleForce::correct(), snappySnapDriver::doSnap(), KinematicCloud< CloudType >::info(), diffusionGasEvaporation< Thermo, OtherThermo >::Kexp(), SIMPLEControlOpt::loop(), polyMesh::movePoints(), multiphaseSystem::multiphaseSystem(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), polyMesh::polyMesh(), liquidFilmBase::postEvolveRegion(), adjointSolver::postLoop(), genericPatchFieldBase::putEntry(), snappySnapDriver::scaleMesh(), hexRef8::setRefinement(), hexRef8::setUnrefinement(), sixDoFRigidBodyMotionSolver::sixDoFRigidBodyMotionSolver(), adjointEikonalSolver::solve(), adjointMeshMovementSolver::solve(), oversetFvMeshBase::solveOverset(), kinematicSingleLayer::transferPrimaryRegionSourceFields(), regionSizeDistribution::write(), writeCellVolumes::write(), solverInfo::write(), PatchCollisionDensity< CloudType >::write(), SIMPLEControlSingleRun::write(), fvMesh::write(), IOPosition< CloudType >::write(), genericPolyPatch::write(), ReactingHeterogeneousParcel< ParcelType >::writeFields(), regionFunctionObject::writeObject(), cellZoneSet::writeObject(), faceZoneSet::writeObject(), pointZoneSet::writeObject(), faMeshTools::writeProcAddressing(), and fvMeshTools::writeProcAddressing().
global()
virtual bool global () const inline virtual
Reimplemented in porosityModel, extendedFeatureEdgeMesh, featureEdgeMesh, searchableSurface, triSurfaceMesh, GlobalIOField< Type >, GlobalIOField< vector >, GlobalIOList< Type >, GlobalIOList< kinematicParcelInjectionData >, GlobalIOList< reactingMultiphaseParcelInjectionData >, GlobalIOList< reactingParcelInjectionData >, IOdictionary, localIOdictionary, unwatchedIOdictionary, IOMap< T >, UniformDimensionedField< Type >, UniformDimensionedField< scalar >, UniformDimensionedField< vector >, distributedTriSurfaceMesh, and baseIOdictionary.
Definition at line 351 of file regIOobject.H.
Referenced by regIOobject::readHeaderOk().
operator=()
void operator= (const IOobject & io)
Definition at line 458 of file regIOobject.C.
References io(), and IOobject::operator=().
writeObject() [2/2]
virtual bool writeObject (IOstreamOption::streamFormat fmt, IOstreamOption::versionNumber ver, IOstreamOption::compressionType cmp, const bool writeOnProc) const inline virtual
Definition at line 367 of file regIOobject.H.
References regIOobject::writeObject().
Friends And Related Symbol Documentation
functionEntries::codeStream
friend class functionEntries::codeStream friend
Definition at line 117 of file regIOobject.H.
fileOperations::uncollatedFileOperation
friend class fileOperations::uncollatedFileOperation friend
Definition at line 118 of file regIOobject.H.
Member Data Documentation
masterOnlyReading
bool masterOnlyReading = false static protected
Definition at line 79 of file regIOobject.H.
Referenced by codeStream::doingMasterOnlyReading(), and uncollatedFileOperation::read().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/regIOobject/regIOobject.H
src/OpenFOAM/db/regIOobject/regIOobject.C
src/OpenFOAM/db/regIOobject/regIOobjectI.H
src/OpenFOAM/db/regIOobject/regIOobjectMetaData.C
src/OpenFOAM/db/regIOobject/regIOobjectRead.C
src/OpenFOAM/db/regIOobject/regIOobjectWrite.C