OpenFOAM: solidProperties Class Reference
solidProperties Class Reference
The thermophysical properties of a solid.
#include <solidProperties.H>
Public Member Functions
TypeName ("solid")
declareRunTimeSelectionTable (autoPtr, solidProperties,,(),())
declareRunTimeSelectionTable (autoPtr, solidProperties, dictionary,(const dictionary &dict),(dict))
solidProperties (scalar rho, scalar Cp, scalar kappa, scalar Hf, scalar emissivity, scalar W, scalar nu, scalar E)
solidProperties (const dictionary &dict)
virtual autoPtr< solidProperties > clone () const
virtual ~solidProperties ()=default
scalar rho () const
scalar Cp () const
scalar kappa () const
scalar Hf () const
scalar Hs (const scalar T) const
scalar emissivity () const
scalar W () const
scalar nu () const
scalar E () const
void readIfPresent (const dictionary &dict)
virtual void writeData (Ostream &os) const
Static Public Member Functions
static autoPtr< solidProperties > New (const word &name)
static autoPtr< solidProperties > New (const dictionary &dict)
Friends
Ostream & operator<< (Ostream &os, const solidProperties &s)
Detailed Description
The thermophysical properties of a solid.
Source files
solidProperties.H
solidProperties.C
Definition at line 50 of file solidProperties.H.
Constructor & Destructor Documentation
solidProperties() [1/2]
solidProperties (scalar rho, scalar Cp, scalar kappa, scalar Hf, scalar emissivity, scalar W, scalar nu, scalar E)
Definition at line 36 of file solidProperties.C.
solidProperties() [2/2]
solidProperties (const dictionary & dict)
Definition at line 59 of file solidProperties.C.
~solidProperties()
virtual ~solidProperties () virtual default
Member Function Documentation
TypeName()
TypeName ("solid")
declareRunTimeSelectionTable() [1/2]
declareRunTimeSelectionTable (autoPtr , solidProperties , () , ())
declareRunTimeSelectionTable() [2/2]
declareRunTimeSelectionTable (autoPtr , solidProperties , dictionary , (const dictionary &dict) , (dict))
clone()
virtual autoPtr< solidProperties > clone () const inline virtual
Reimplemented in ash, C, and CaCO3.
Definition at line 125 of file solidProperties.H.
References autoPtr< T >::New().
New() [1/2]
Foam::autoPtr< Foam::solidProperties > New (const word & name) static
Definition at line 27 of file solidPropertiesNew.C.
References DebugInFunction, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInLookup, and Foam::name().
Referenced by solidMixtureProperties::solidMixtureProperties().
New() [2/2]
Foam::autoPtr< Foam::solidProperties > New (const dictionary & dict) static
Definition at line 50 of file solidPropertiesNew.C.
References DebugInFunction, dict, dictionary::dictName(), Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::found(), dictionary::get(), autoPtr< T >::New(), Foam::New(), and dictionary::optionalSubDict().
rho()
Foam::scalar rho () const inline
Definition at line 26 of file solidPropertiesI.H.
Referenced by thermalShell::rho().
Cp()
Foam::scalar Cp () const inline
Definition at line 32 of file solidPropertiesI.H.
Referenced by thermalShell::Cp().
kappa()
Foam::scalar kappa () const inline
Definition at line 38 of file solidPropertiesI.H.
Referenced by thermalShell::kappa().
Hf()
Foam::scalar Hf () const inline
Definition at line 44 of file solidPropertiesI.H.
Hs()
Foam::scalar Hs (const scalar T) const inline
Definition at line 50 of file solidPropertiesI.H.
References T, and Foam::constant::thermodynamic::Tstd.
emissivity()
Foam::scalar emissivity () const inline
Definition at line 56 of file solidPropertiesI.H.
W()
Foam::scalar W () const inline
Definition at line 62 of file solidPropertiesI.H.
nu()
Foam::scalar nu () const inline
Definition at line 68 of file solidPropertiesI.H.
E()
Foam::scalar E () const inline
Definition at line 74 of file solidPropertiesI.H.
readIfPresent()
void readIfPresent (const dictionary & dict)
Definition at line 74 of file solidProperties.C.
References dict, dictionary::readIfPresent(), and dictionary::readIfPresentCompat().
Referenced by ash::ash(), C::C(), and CaCO3::CaCO3().
writeData()
void writeData (Ostream & os) const virtual
Reimplemented in ash, C, and CaCO3.
Definition at line 87 of file solidProperties.C.
References os(), and token::SPACE.
Referenced by ash::writeData(), C::writeData(), and CaCO3::writeData().
Friends And Related Symbol Documentation
operator<<
Ostream & operator<< (Ostream & os, const solidProperties & s) friend
The documentation for this class was generated from the following files:
src/thermophysicalModels/thermophysicalProperties/solidProperties/solidProperties/solidProperties.H
src/thermophysicalModels/thermophysicalProperties/solidProperties/solidProperties/solidProperties.C
src/thermophysicalModels/thermophysicalProperties/solidProperties/solidProperties/solidPropertiesI.H
src/thermophysicalModels/thermophysicalProperties/solidProperties/solidProperties/solidPropertiesNew.C