OpenFOAM: object Class Reference
object Class Reference
glTF binary object
#include <foamGltfObject.H>
Public Member Functions
object ()
object (const word &name)
template<class Type >
void addData (const Type &fld)
template<class Type1 , class Type2 >
void addData (const Type1 &fld1, const Type2 &fld2)
const Foam::List< float > & data () const noexcept
Public Member Functions inherited from base
base ()
base (const word &name)
~base ()=default
label & id () noexcept
const word & name () const noexcept
void write (Ostream &os) const
void operator= (const base &gltf)
Additional Inherited Members
Protected Attributes inherited from base
word name_
label id_
Detailed Description
glTF binary object
Note
Implements the glTF v2 specification
Source files
foamGltfObject.H
foamGltfObject.C
foamGltfObjectTemplates.C
Definition at line 53 of file foamGltfObject.H.
Constructor & Destructor Documentation
object() [1/2]
object ()
Definition at line 26 of file foamGltfObject.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
object() [2/2]
object (const word & name) explicit
Definition at line 40 of file foamGltfObject.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Member Function Documentation
addData() [1/2]
template<class Type > void addData (const Type & fld)
Definition at line 22 of file foamGltfObjectTemplates.C.
References Foam::component(), fld(), forAll, List< T >::resize(), UPtrList< T >::size(), and UList< T >::size().
addData() [2/2]
template<class Type1 , class Type2 > void addData (const Type1 & fld1, const Type2 & fld2)
Definition at line 40 of file foamGltfObjectTemplates.C.
References Foam::abort(), Foam::component(), Foam::FatalError, FatalErrorInFunction, forAll, PtrList< T >::resize(), and UPtrList< T >::size().
data()
const Foam::List< float > & data () const noexcept
Definition at line 56 of file foamGltfObject.C.
The documentation for this class was generated from the following files:
src/fileFormats/gltf/foamGltfObject.H
src/fileFormats/gltf/foamGltfObject.C
src/fileFormats/gltf/foamGltfObjectTemplates.C