OpenFOAM: PhaseTransferPhaseSystem< BasePhaseSystem > Class Template Reference
PhaseTransferPhaseSystem< BasePhaseSystem > Class Template Reference
Class which models non-thermally-coupled mass transfers; i.e., representation changes, rather than phase changes.
#include <PhaseTransferPhaseSystem.H>
Public Member Functions
PhaseTransferPhaseSystem (const fvMesh &)
virtual ~PhaseTransferPhaseSystem ()
virtual tmp< volScalarField > dmdt (const phasePairKey &key) const
virtual PtrList< volScalarField > dmdts () const
virtual autoPtr< phaseSystem::massTransferTable > massTransfer () const
virtual void correct ()
virtual bool read ()
Protected Types
typedef HashTable< autoPtr< BlendedInterfacialModel< phaseTransferModel > >, phasePairKey, phasePairKey::hash > phaseTransferModelTable
typedef HashPtrTable< volScalarField, phasePairKey, phasePairKey::hash > rDmdtTable
Protected Member Functions
virtual tmp< volScalarField > rDmdt (const phasePairKey &key) const
Protected Attributes
phaseTransferModelTable phaseTransferModels_
rDmdtTable rDmdt_
Detailed Description
template<class BasePhaseSystem>
class Foam::PhaseTransferPhaseSystem< BasePhaseSystem >
Class which models non-thermally-coupled mass transfers; i.e., representation changes, rather than phase changes.
Source files
PhaseTransferPhaseSystem.H
PhaseTransferPhaseSystem.C
Definition at line 52 of file PhaseTransferPhaseSystem.H.
Member Typedef Documentation
phaseTransferModelTable
template<class BasePhaseSystem > typedef HashTable< autoPtr<BlendedInterfacialModel<phaseTransferModel> >, phasePairKey, phasePairKey::hash > phaseTransferModelTable protected
Definition at line 65 of file PhaseTransferPhaseSystem.H.
rDmdtTable
template<class BasePhaseSystem > typedef HashPtrTable<volScalarField, phasePairKey, phasePairKey::hash> rDmdtTable protected
Definition at line 68 of file PhaseTransferPhaseSystem.H.
Constructor & Destructor Documentation
PhaseTransferPhaseSystem()
template<class BasePhaseSystem > PhaseTransferPhaseSystem (const fvMesh & mesh)
Definition at line 48 of file PhaseTransferPhaseSystem.C.
References phaseSystem::dmdt(), forAllConstIter, PhaseTransferPhaseSystem< BasePhaseSystem >::phaseTransferModels_, PhaseTransferPhaseSystem< BasePhaseSystem >::rDmdt_, and HashPtrTable< T, Key, Hash >::set().
~PhaseTransferPhaseSystem()
template<class BasePhaseSystem > ~PhaseTransferPhaseSystem () virtual
Definition at line 81 of file PhaseTransferPhaseSystem.C.
Member Function Documentation
rDmdt()
template<class BasePhaseSystem > Foam::tmp< Foam::volScalarField > rDmdt (const phasePairKey & key) const protected virtual
Definition at line 29 of file PhaseTransferPhaseSystem.C.
References phaseSystem::dmdt(), and PtrList< T >::PtrList().
dmdt()
template<class BasePhaseSystem > Foam::tmp< Foam::volScalarField > dmdt (const phasePairKey & key) const virtual
Definition at line 90 of file PhaseTransferPhaseSystem.C.
dmdts()
template<class BasePhaseSystem > Foam::PtrList< Foam::volScalarField > dmdts () const virtual
Definition at line 101 of file PhaseTransferPhaseSystem.C.
References forAllConstIter, phasePair::phase1(), and phasePair::phase2().
massTransfer()
template<class BasePhaseSystem > Foam::autoPtr< Foam::phaseSystem::massTransferTable > massTransfer () const virtual
Definition at line 120 of file PhaseTransferPhaseSystem.C.
References Foam::dimMass, Foam::dimTime, forAll, forAllConstIter, IOobject::groupName(), phase::name(), phaseModel::name(), Foam::name(), Foam::negPart(), phasePair::phase1(), phasePair::phase2(), phasei, Foam::posPart(), psi, PtrList< T >::set(), and Foam::fvm::Sp().
correct()
template<class BasePhaseSystem > void correct () virtual
Definition at line 196 of file PhaseTransferPhaseSystem.C.
References Foam::dimDensity, Foam::dimTime, and forAllConstIter.
read()
template<class BasePhaseSystem > bool read () virtual
Definition at line 225 of file PhaseTransferPhaseSystem.C.
Member Data Documentation
phaseTransferModels_
template<class BasePhaseSystem > phaseTransferModelTable phaseTransferModels_ protected
Definition at line 76 of file PhaseTransferPhaseSystem.H.
Referenced by PhaseTransferPhaseSystem< BasePhaseSystem >::PhaseTransferPhaseSystem().
rDmdt_
template<class BasePhaseSystem > rDmdtTable rDmdt_ protected
Definition at line 79 of file PhaseTransferPhaseSystem.H.
Referenced by PhaseTransferPhaseSystem< BasePhaseSystem >::PhaseTransferPhaseSystem().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/PhaseSystems/PhaseTransferPhaseSystem/PhaseTransferPhaseSystem.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/PhaseSystems/PhaseTransferPhaseSystem/PhaseTransferPhaseSystem.C