OpenFOAM: IOerror Class Reference
IOerror Class Reference
#include <error.H>
Public Member Functions
IOerror (const string &title)
IOerror (const dictionary &errDict)
virtual ~IOerror () noexcept
const string & ioFileName () const noexcept
label ioStartLineNumber () const noexcept
label ioEndLineNumber () const noexcept
OSstream & operator() (const char *functionName, const char *sourceFileName, const int sourceFileLineNumber, const string &ioFileName, const label ioStartLineNumber=-1, const label ioEndLineNumber=-1)
OSstream & operator() (const char *functionName, const char *sourceFileName, const int sourceFileLineNumber, const IOstream &ioStream)
OSstream & operator() (const char *functionName, const char *sourceFileName, const int sourceFileLineNumber, const dictionary &dict)
OSstream & operator() (const std::string &where, const IOstream &ioStream)
OSstream & operator() (const std::string &where, const dictionary &dict)
operator dictionary () const
void exit (const int errNo=1)
void abort ()
virtual void write (Ostream &os, const bool withTitle=true) const
Public Member Functions inherited from error
error (const string &title)
error (const dictionary &errDict)
error (const error &err)
virtual ~error () noexcept
string message () const
void clear () const
const string & functionName () const noexcept
const string & sourceFileName () const noexcept
label sourceFileLineNumber () const noexcept
bool throwing () const noexcept
bool throwing (const bool on) noexcept
OSstream & stream ()
operator OSstream & ()
OSstream & operator() ()
OSstream & operator() (const string &functionName)
OSstream & operator() (const char *functionName, const char *sourceFileName, const int sourceFileLineNumber=0)
OSstream & operator() (const string &functionName, const char *sourceFileName, const int sourceFileLineNumber=0)
operator dictionary () const
void exit (const int errNo=1)
void abort ()
bool throwExceptions (const bool on=true) noexcept
bool dontThrowExceptions () noexcept
Public Member Functions inherited from messageStream
messageStream (const string &title, const errorSeverity severity, const int maxErrors=0)
messageStream (const dictionary &dict)
const string & title () const noexcept
int maxErrors () const noexcept
int maxErrors (int nErrors) noexcept
OSstream & stream (OSstream *alternative=nullptr)
OSstream & masterStream (const label communicator)
std::ostream & stdStream ()
OSstream & deprecated (const int afterVersion, const char *functionName, const char *sourceFileName, const int sourceFileLineNumber=0)
operator OSstream & ()
OSstream & operator() ()
OSstream & operator() (const std::string &functionName)
OSstream & operator() (const char *functionName, const char *sourceFileName, const int sourceFileLineNumber=0)
OSstream & operator() (const std::string &functionName, const char *sourceFileName, const int sourceFileLineNumber=0)
OSstream & operator() (const char *functionName, const char *sourceFileName, const int sourceFileLineNumber, const std::string &ioFileName, const label ioStartLineNumber=-1, const label ioEndLineNumber=-1)
OSstream & operator() (const char *functionName, const char *sourceFileName, const int sourceFileLineNumber, const IOstream &)
OSstream & operator() (const char *functionName, const char *sourceFileName, const int sourceFileLineNumber, const dictionary &)
Static Public Member Functions
static void SafeFatalIOError (const char *functionName, const char *sourceFileName, const int sourceFileLineNumber, const IOstream &ioStream, const string &msg)
Static Public Member Functions inherited from error
static bool master (const label communicator=-1)
static bool warnAboutAge (const int version) noexcept
static bool warnAboutAge (const char *what, const int version)
static void safePrintStack (std::ostream &os, int size=-1)
static void printStack (Ostream &os, int size=-1)
static bool useAbort ()
Additional Inherited Members
Public Types inherited from messageStream
enum errorSeverity {
INFO = 1 , INFO_STDERR , WARNING , SERIOUS ,
FATAL
}
Static Public Attributes inherited from messageStream
static int level
static int redirect
Protected Member Functions inherited from error
void simpleExit (const int errNo, const bool isAbort)
Protected Attributes inherited from error
string functionName_
string sourceFileName_
label sourceFileLineNumber_
bool throwing_
std::unique_ptr< OStringStream > messageStreamPtr_
Protected Attributes inherited from messageStream
string title_
errorSeverity severity_
int maxErrors_
int errorCount_
Detailed Description
Definition at line 277 of file error.H.
Constructor & Destructor Documentation
IOerror() [1/2]
IOerror (const string & title) explicit
Definition at line 34 of file IOerror.C.
IOerror() [2/2]
IOerror (const dictionary & errDict) explicit
Definition at line 43 of file IOerror.C.
~IOerror()
~IOerror () virtual noexcept
Definition at line 54 of file IOerror.C.
Member Function Documentation
ioFileName()
const string & ioFileName () const inline noexcept
Definition at line 312 of file error.H.
ioStartLineNumber()
label ioStartLineNumber () const inline noexcept
Definition at line 318 of file error.H.
ioEndLineNumber()
label ioEndLineNumber () const inline noexcept
Definition at line 324 of file error.H.
operator()() [1/5]
Foam::OSstream & operator() (const char * functionName, const char * sourceFileName, const int sourceFileLineNumber, const string & ioFileName, const label ioStartLineNumber = -1, const label ioEndLineNumber = -1)
Definition at line 60 of file IOerror.C.
References os().
operator()() [2/5]
Foam::OSstream & operator() (const char * functionName, const char * sourceFileName, const int sourceFileLineNumber, const IOstream & ioStream)
Definition at line 85 of file IOerror.C.
operator()() [3/5]
Foam::OSstream & operator() (const char * functionName, const char * sourceFileName, const int sourceFileLineNumber, const dictionary & dict)
Definition at line 105 of file IOerror.C.
References dict, dictionary::endLineNumber(), dictionary::relativeName(), and dictionary::startLineNumber().
operator()() [4/5]
Foam::OSstream & operator() (const std::string & where, const IOstream & ioStream)
Definition at line 125 of file IOerror.C.
operator()() [5/5]
Foam::OSstream & operator() (const std::string & where, const dictionary & dict)
Definition at line 143 of file IOerror.C.
References dict, dictionary::endLineNumber(), dictionary::relativeName(), and dictionary::startLineNumber().
SafeFatalIOError()
void SafeFatalIOError (const char * functionName, const char * sourceFileName, const int sourceFileLineNumber, const IOstream & ioStream, const string & msg) static
Definition at line 161 of file IOerror.C.
References JobInfo::constructed, Foam::exit(), Foam::FatalIOError, and Foam::nl.
operator dictionary()
operator dictionary () const
exit()
void exit (const int errNo = 1)
Definition at line 239 of file IOerror.C.
Referenced by Foam::exit(), IFstream::operator()(), and Istream::operator()().
abort()
void abort ()
Definition at line 245 of file IOerror.C.
Referenced by Foam::abort().
write()
void write (Ostream & os, const bool withTitle = true) const virtual
Reimplemented from error.
Definition at line 251 of file IOerror.C.
References Foam::foamVersion::api, IOstream::bad(), messageStream::level, Foam::nl, os(), Foam::foamVersion::patch, and Foam::foamVersion::patched().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/error/error.H
src/OpenFOAM/db/error/IOerror.C