OpenFOAM: surfaceInterpolationScheme< Type > Class Template Reference
surfaceInterpolationScheme< Type > Class Template Reference abstract
Abstract base class for surface interpolation schemes.
#include <surfaceInterpolationScheme.H>
Public Member Functions
TypeName ("surfaceInterpolationScheme")
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, Mesh,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, MeshFlux,(const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
surfaceInterpolationScheme (const fvMesh &mesh)
virtual ~surfaceInterpolationScheme ()=default
const fvMesh & mesh () const
virtual tmp< surfaceScalarField > weights (const GeometricField< Type, fvPatchField, volMesh > &) const =0
virtual bool corrected () const
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > &) const
virtual tmp< GeometricField< typename innerProduct< vector, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf) const
tmp< GeometricField< typename innerProduct< vector, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const tmp< GeometricField< Type, fvPatchField, volMesh > > &) const
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &) const
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > &) const
template<class SFType >
Foam::tmp< Foam::GeometricField< typename Foam::innerProduct< typename SFType::value_type, Type >::type, Foam::fvsPatchField, Foam::surfaceMesh > > dotInterpolate (const SFType &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf, const tmp< surfaceScalarField > &tlambdas)
tmp< GeometricField< typename innerProduct< vector, scalar >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const GeometricField< scalar, fvPatchField, volMesh > &) const
Foam::tmp< Foam::GeometricField< typename Foam::innerProduct< Foam::vector, Foam::scalar >::type, Foam::fvsPatchField, Foam::surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const GeometricField< scalar, fvPatchField, volMesh > &) const
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Static Public Member Functions
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData)
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &, const tmp< surfaceScalarField > &)
template<class SFType >
static tmp< GeometricField< typename innerProduct< typename SFType::value_type, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const SFType &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf, const tmp< surfaceScalarField > &tlambdas)
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &)
Detailed Description
template<class Type>
class Foam::surfaceInterpolationScheme< Type >
Abstract base class for surface interpolation schemes.
Source files
surfaceInterpolationScheme.H
surfaceInterpolationScheme.C
Definition at line 53 of file surfaceInterpolationScheme.H.
Constructor & Destructor Documentation
surfaceInterpolationScheme()
template<class Type > surfaceInterpolationScheme (const fvMesh & mesh) inline
Definition at line 109 of file surfaceInterpolationScheme.H.
~surfaceInterpolationScheme()
template<class Type > virtual ~surfaceInterpolationScheme () virtual default
Member Function Documentation
TypeName()
template<class Type > TypeName ("surfaceInterpolationScheme< Type >")
declareRunTimeSelectionTable() [1/2]
template<class Type > declareRunTimeSelectionTable (tmp , surfaceInterpolationScheme< Type > , Mesh , (const fvMesh &mesh, Istream &schemeData) , (mesh, schemeData))
declareRunTimeSelectionTable() [2/2]
template<class Type > declareRunTimeSelectionTable (tmp , surfaceInterpolationScheme< Type > , MeshFlux , (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData) , (mesh, faceFlux, schemeData))
New() [1/2]
template<class Type > Foam::tmp< Foam::surfaceInterpolationScheme< Type > > New (const fvMesh & mesh, Istream & schemeData) static
Definition at line 32 of file surfaceInterpolationScheme.C.
References Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, FatalIOErrorInLookup, InfoInFunction, mesh, and PtrList< T >::PtrList().
Referenced by adjointBoundaryCondition< Type >::computePatchGrad(), adjointkOmegaSST::convectionScheme(), gaussGrad< Type >::gaussGrad(), adjointkOmegaSST::interpolationScheme(), laplacianScheme< Type, GType >::laplacianScheme(), and multivariateIndependentScheme< Type >::operator()().
New() [2/2]
template<class Type > Foam::tmp< Foam::surfaceInterpolationScheme< Type > > New (const fvMesh & mesh, const surfaceScalarField & faceFlux, Istream & schemeData) static
Definition at line 73 of file surfaceInterpolationScheme.C.
References Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, FatalIOErrorInLookup, InfoInFunction, and mesh.
mesh()
template<class Type > const fvMesh & mesh () const inline
Definition at line 140 of file surfaceInterpolationScheme.H.
Referenced by cellCoBlended< Type >::blendingFactor(), CoBlended< Type >::blendingFactor(), localBlended< Type >::blendingFactor(), DEShybrid< Type >::blendingFactor(), skewCorrected< Type >::corrected(), CentredFitScheme< Type, Polynomial, Stencil >::correction(), cubic< Type >::correction(), localBlended< Type >::correction(), outletStabilised< Type >::correction(), PureUpwindFitScheme< Type, Polynomial, Stencil >::correction(), skewCorrected< Type >::correction(), UpwindFitScheme< Type, Polynomial, Stencil >::correction(), localBlended< Type >::interpolate(), localMax< Type >::interpolate(), localMin< Type >::interpolate(), blended< Type >::limiter(), upwind< Type >::limiter(), skewCorrected< Type >::skewCorrection(), clippedLinear< Type >::weights(), linear< Type >::weights(), midPoint< Type >::weights(), reverseLinear< Type >::weights(), weightedFlux< Type >::weights(), blended< Type >::weights(), localBlended< Type >::weights(), and outletStabilised< Type >::weights().
interpolate() [1/4]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > & vf, const tmp< surfaceScalarField > & tlambdas, const tmp< surfaceScalarField > & tys) static
Definition at line 118 of file surfaceInterpolationScheme.C.
Referenced by deferredCorrection< Type >::correction(), cubic< Type >::correction(), Foam::linearInterpolate(), and skewCorrected< Type >::skewCorrection().
dotInterpolate() [1/6]
template<class Type > template<class SFType > static tmp< GeometricField< typename innerProduct< typename SFType::value_type, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const SFType & Sf, const GeometricField< Type, fvPatchField, volMesh > & vf, const tmp< surfaceScalarField > & tlambdas) static
interpolate() [2/4]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > & vf, const tmp< surfaceScalarField > & tlambdas) static
Definition at line 304 of file surfaceInterpolationScheme.C.
weights()
template<class Type > virtual tmp< surfaceScalarField > weights (const GeometricField< Type, fvPatchField, volMesh > &) const pure virtual
Implemented in harmonic, limitedSurfaceInterpolationScheme< Type >, upwind< Type >, multivariateSelectionScheme< Type >::fieldScheme, multivariateUpwind< Type >::fieldScheme, clippedLinear< Type >, downwind< Type >, linear< Type >, localMax< Type >, localMin< Type >, LUST< Type >, midPoint< Type >, reverseLinear< Type >, weighted< Type >, weightedFlux< Type >, multivariateSurfaceInterpolationScheme< Type >::fieldScheme, blended< Type >, limitWith< Type >, cellCoBlended< Type >, CoBlended< Type >, fixedBlended< Type >, limiterBlended< Type >, localBlended< Type >, outletStabilised< Type >, and skewCorrected< Type >.
corrected()
template<class Type > virtual bool corrected () const inline virtual
Reimplemented in limitWith< Type >, cellCoBlended< Type >, CentredFitScheme< Type, Polynomial, Stencil >, CoBlended< Type >, cubic< Type >, deferredCorrection< Type >, fixedBlended< Type >, limiterBlended< Type >, linearUpwind< Type >, linearUpwindV< Type >, localBlended< Type >, LUST< Type >, outletStabilised< Type >, pointLinear< Type >, PureUpwindFitScheme< Type, Polynomial, Stencil >, skewCorrected< Type >, UpwindFitScheme< Type, Polynomial, Stencil >, linearUpwindNormal< Type >, and DEShybrid< Type >.
Definition at line 191 of file surfaceInterpolationScheme.H.
correction()
template<class Type > virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > &) const inline virtual
Reimplemented in deferredCorrection< Type >, linearUpwind< Type >, linearUpwindV< Type >, linearUpwindNormal< Type >, limitWith< Type >, cellCoBlended< Type >, CentredFitScheme< Type, Polynomial, Stencil >, CoBlended< Type >, cubic< Type >, fixedBlended< Type >, limiterBlended< Type >, localBlended< Type >, LUST< Type >, outletStabilised< Type >, pointLinear< Type >, PureUpwindFitScheme< Type, Polynomial, Stencil >, skewCorrected< Type >, and UpwindFitScheme< Type, Polynomial, Stencil >.
Definition at line 199 of file surfaceInterpolationScheme.H.
dotInterpolate() [2/6]
template<class Type > Foam::tmp< Foam::GeometricField< typename Foam::innerProduct< Foam::vector, Type >::type, Foam::fvsPatchField, Foam::surfaceMesh > > dotInterpolate (const surfaceVectorField & Sf, const GeometricField< Type, fvPatchField, volMesh > & vf) const virtual
Definition at line 324 of file surfaceInterpolationScheme.C.
References Foam::correction(), Foam::endl(), InfoInFunction, and DimensionedField< Type, GeoMesh >::oriented().
dotInterpolate() [3/6]
template<class Type > Foam::tmp< Foam::GeometricField< typename Foam::innerProduct< Foam::vector, Type >::type, Foam::fvsPatchField, Foam::surfaceMesh > > dotInterpolate (const surfaceVectorField & Sf, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf) const
Definition at line 371 of file surfaceInterpolationScheme.C.
References PtrList< T >::clear().
interpolate() [3/4]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > & vf) const virtual
Reimplemented in harmonic, cellCoBlended< Type >, CoBlended< Type >, fixedBlended< Type >, limiterBlended< Type >, localBlended< Type >, localMax< Type >, localMin< Type >, and weightedFlux< Type >.
Definition at line 394 of file surfaceInterpolationScheme.C.
References Foam::correction(), Foam::endl(), InfoInFunction, and Foam::interpolate().
interpolate() [4/4]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf) const
Definition at line 423 of file surfaceInterpolationScheme.C.
References PtrList< T >::clear(), and Foam::interpolate().
dotInterpolate() [4/6]
template<class Type > template<class SFType > Foam::tmp< Foam::GeometricField< typename Foam::innerProduct< typename SFType::value_type, Type >::type, Foam::fvsPatchField, Foam::surfaceMesh > > dotInterpolate (const SFType & Sf, const GeometricField< Type, fvPatchField, volMesh > & vf, const tmp< surfaceScalarField > & tlambdas)
Definition at line 209 of file surfaceInterpolationScheme.C.
dotInterpolate() [5/6]
tmp< GeometricField< typename innerProduct< vector, scalar >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField & Sf, const GeometricField< scalar, fvPatchField, volMesh > &) const
dotInterpolate() [6/6]
Foam::tmp< Foam::GeometricField< typename Foam::innerProduct< Foam::vector, Foam::scalar >::type, Foam::fvsPatchField, Foam::surfaceMesh > > dotInterpolate (const surfaceVectorField & Sf, const GeometricField< scalar, fvPatchField, volMesh > &) const
Definition at line 68 of file surfaceInterpolationSchemes.C.
References NotImplemented.
The documentation for this class was generated from the following files:
src/finiteVolume/interpolation/surfaceInterpolation/surfaceInterpolationScheme/surfaceInterpolationScheme.H
src/finiteVolume/interpolation/surfaceInterpolation/surfaceInterpolationScheme/surfaceInterpolationScheme.C