OpenFOAM: lumpedPointController Class Reference
lumpedPointController Class Reference
Simple connectivity of point labels to specify a controller for lumped point movement.
#include <lumpedPointController.H>
Public Member Functions
lumpedPointController () noexcept
lumpedPointController (const labelUList &pointLabels)
lumpedPointController (labelList &&pointLabels)
lumpedPointController (const dictionary &dict)
~lumpedPointController ()=default
bool empty () const
label size () const
const labelList & pointLabels () const
void remapPointLabels (const label nPoints, const Map< label > &originalIds)
Static Public Member Functions
static autoPtr< lumpedPointController > New (const dictionary &dict)
Detailed Description
Simple connectivity of point labels to specify a controller for lumped point movement.
Dictionary parameters
Property Description Required Default
pointLabels List of point labels yes
Note
If the calling program itself specified a point-label mapping (eg, original ids from FEA), these can be used initially and remapped.
Source files
lumpedPointController.H
lumpedPointController.C
Definition at line 71 of file lumpedPointController.H.
Constructor & Destructor Documentation
lumpedPointController() [1/4]
lumpedPointController () noexcept
Definition at line 28 of file lumpedPointController.C.
lumpedPointController() [2/4]
lumpedPointController (const labelUList & pointLabels) explicit
Definition at line 34 of file lumpedPointController.C.
lumpedPointController() [3/4]
lumpedPointController (labelList && pointLabels) explicit
Definition at line 43 of file lumpedPointController.C.
lumpedPointController() [4/4]
lumpedPointController (const dictionary & dict) explicit
Definition at line 52 of file lumpedPointController.C.
~lumpedPointController()
~lumpedPointController () default
Member Function Documentation
New()
static autoPtr< lumpedPointController > New (const dictionary & dict) inline static
Definition at line 97 of file lumpedPointController.H.
References dict, and autoPtr< T >::New().
empty()
bool empty () const inline
Definition at line 110 of file lumpedPointController.H.
References UList< T >::empty().
size()
label size () const inline
Definition at line 116 of file lumpedPointController.H.
References UList< T >::size().
pointLabels()
const labelList & pointLabels () const inline
Definition at line 122 of file lumpedPointController.H.
remapPointLabels()
void remapPointLabels (const label nPoints, const Map< label > & originalIds)
Definition at line 63 of file lumpedPointController.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::flatOutput(), Foam::max(), Foam::min(), Foam::nl, nPoints, and UPtrList< T >::size().
The documentation for this class was generated from the following files:
src/lumpedPointMotion/controller/lumpedPointController.H
src/lumpedPointMotion/controller/lumpedPointController.C