OpenFOAM: IATEsource Class Reference
IATEsource Class Reference abstract
IATE (Interfacial Area Transport Equation) bubble diameter model run-time selectable sources.
#include <IATEsource.H>
Classes
class iNew
Public Member Functions
TypeName ("IATEsource")
declareRunTimeSelectionTable (autoPtr, IATEsource, dictionary,(const IATE &iate, const dictionary &dict),(iate, dict))
IATEsource (const IATE &iate)
autoPtr< IATEsource > clone () const
virtual ~IATEsource ()=default
const phaseModel & phase () const
const twoPhaseSystem & fluid () const
const phaseModel & otherPhase () const
scalar phi () const
tmp< volScalarField > Ur () const
tmp< volScalarField > Ut () const
tmp< volScalarField > Re () const
tmp< volScalarField > CD () const
tmp< volScalarField > Mo () const
tmp< volScalarField > Eo () const
tmp< volScalarField > We () const
virtual tmp< fvScalarMatrix > R (const volScalarField &alphai, volScalarField &kappai) const =0
TypeName ("IATEsource")
declareRunTimeSelectionTable (autoPtr, IATEsource, dictionary,(const IATE &iate, const dictionary &dict),(iate, dict))
IATEsource (const IATE &iate)
autoPtr< IATEsource > clone () const
virtual ~IATEsource ()=default
const phaseModel & phase () const
const twoPhaseSystem & fluid () const
const phaseModel & otherPhase () const
scalar phi () const
tmp< volScalarField > Ur () const
tmp< volScalarField > Ut () const
tmp< volScalarField > Re () const
tmp< volScalarField > CD () const
tmp< volScalarField > Mo () const
tmp< volScalarField > Eo () const
tmp< volScalarField > We () const
virtual tmp< volScalarField > R () const =0
Static Public Member Functions
static autoPtr< IATEsource > New (const word &type, const IATE &iate, const dictionary &dict)
static autoPtr< IATEsource > New (const word &type, const IATE &iate, const dictionary &dict)
Protected Attributes
const IATE & iate_
Detailed Description
IATE (Interfacial Area Transport Equation) bubble diameter model run-time selectable sources.
Source files
IATEsource.H
IATEsource.C
Source files
IATEsource.H
IATEsource.C
Definition at line 52 of file IATEsource.H.
Constructor & Destructor Documentation
IATEsource() [1/2]
IATEsource (const IATE & iate) inline
Definition at line 108 of file IATEsource.H.
~IATEsource() [1/2]
virtual ~IATEsource () virtual default
IATEsource() [2/2]
IATEsource (const IATE & iate) inline
Definition at line 107 of file IATEsource.H.
~IATEsource() [2/2]
virtual ~IATEsource () virtual default
Member Function Documentation
TypeName() [1/2]
TypeName ("IATEsource")
declareRunTimeSelectionTable() [1/2]
declareRunTimeSelectionTable (autoPtr , IATEsource , dictionary , (const IATE &iate, const dictionary &dict) , (iate, dict))
clone() [1/2]
autoPtr< IATEsource > clone () const inline
Definition at line 113 of file IATEsource.H.
References NotImplemented.
New() [1/2]
Foam::autoPtr< Foam::diameterModels::IATEsource > New (const word & type, const IATE & iate, const dictionary & dict) static
Definition at line 42 of file IATEsource.C.
References dict, Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, and Foam::type().
Referenced by IATEsource::iNew::operator()().
phase() [1/2]
const phaseModel & phase () const inline
Definition at line 136 of file IATEsource.H.
References IATEsource::iate_.
Referenced by IATEsource::otherPhase(), and randomCoalescence::R().
fluid() [1/2]
const twoPhaseSystem & fluid () const inline
Definition at line 141 of file IATEsource.H.
References IATEsource::iate_.
Referenced by IATEsource::otherPhase().
otherPhase() [1/2]
const phaseModel & otherPhase () const inline
Definition at line 146 of file IATEsource.H.
References IATEsource::fluid(), and IATEsource::phase().
phi() [1/2]
scalar phi () const inline
Definition at line 151 of file IATEsource.H.
References Foam::constant::mathematical::pi().
Referenced by randomCoalescence::R(), and wakeEntrainmentCoalescence::R().
Ur() [1/2]
Foam::tmp< Foam::volScalarField > Ur () const
Definition at line 68 of file IATEsource.C.
References fluid, g, Foam::mag(), Foam::max(), DimensionedField< Type, GeoMesh >::mesh(), Foam::pow(), Foam::pow025(), rho, Foam::sqr(), and Foam::sqrt().
Referenced by wakeEntrainmentCoalescence::R().
Ut() [1/2]
Foam::tmp< Foam::volScalarField > Ut () const
Definition at line 84 of file IATEsource.C.
References k, and Foam::sqrt().
Referenced by randomCoalescence::R(), and turbulentBreakUp::R().
Re() [1/2]
Foam::tmp< Foam::volScalarField > Re () const
Definition at line 89 of file IATEsource.C.
References e, Foam::max(), and nu.
CD() [1/2]
Foam::tmp< Foam::volScalarField > CD () const
Definition at line 94 of file IATEsource.C.
References Foam::max(), Foam::min(), Foam::pow(), and Foam::Re().
Referenced by wakeEntrainmentCoalescence::R().
Mo() [1/2]
Foam::tmp< Foam::volScalarField > Mo () const
Definition at line 111 of file IATEsource.C.
References IOobject::db(), fluid, g, Foam::mag(), nu, Foam::pow3(), Foam::pow4(), rho, phase::rho(), and Foam::sqr().
Eo() [1/2]
Foam::tmp< Foam::volScalarField > Eo () const
Definition at line 122 of file IATEsource.C.
References IOobject::db(), fluid, g, Foam::mag(), phase::rho(), and Foam::sqr().
We() [1/2]
Foam::tmp< Foam::volScalarField > We () const
Definition at line 133 of file IATEsource.C.
References fluid, and Foam::sqr().
Referenced by turbulentBreakUp::R().
R() [1/2]
virtual tmp< fvScalarMatrix > R (const volScalarField & alphai, volScalarField & kappai) const pure virtual
Implemented in dummy, phaseChange, randomCoalescence, turbulentBreakUp, wakeEntrainmentCoalescence, and wallBoiling.
TypeName() [2/2]
TypeName ("IATEsource")
declareRunTimeSelectionTable() [2/2]
declareRunTimeSelectionTable (autoPtr , IATEsource , dictionary , (const IATE &iate, const dictionary &dict) , (iate, dict))
clone() [2/2]
autoPtr< IATEsource > clone () const inline
Definition at line 112 of file IATEsource.H.
References NotImplemented.
New() [2/2]
static autoPtr< IATEsource > New (const word & type, const IATE & iate, const dictionary & dict) static
phase() [2/2]
const phaseModel & phase () const inline
Definition at line 135 of file IATEsource.H.
References IATEsource::iate_.
fluid() [2/2]
const twoPhaseSystem & fluid () const inline
Definition at line 140 of file IATEsource.H.
References IATEsource::iate_.
otherPhase() [2/2]
const phaseModel & otherPhase () const inline
Definition at line 145 of file IATEsource.H.
References IATEsource::phase().
phi() [2/2]
scalar phi () const inline
Definition at line 150 of file IATEsource.H.
References Foam::constant::mathematical::pi().
Ur() [2/2]
tmp< volScalarField > Ur () const
Ut() [2/2]
tmp< volScalarField > Ut () const
Re() [2/2]
tmp< volScalarField > Re () const
CD() [2/2]
tmp< volScalarField > CD () const
Mo() [2/2]
tmp< volScalarField > Mo () const
Eo() [2/2]
tmp< volScalarField > Eo () const
We() [2/2]
tmp< volScalarField > We () const
R() [2/2]
virtual tmp< volScalarField > R () const pure virtual
Implemented in dummy, randomCoalescence, turbulentBreakUp, and wakeEntrainmentCoalescence.
Member Data Documentation
iate_
const IATE & iate_ protected
Definition at line 60 of file IATEsource.H.
Referenced by IATEsource::fluid(), IATEsource::phase(), dummy::R(), randomCoalescence::R(), turbulentBreakUp::R(), wakeEntrainmentCoalescence::R(), and dummy::R().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/twoPhaseSystem/diameterModels/IATE/IATEsources/IATEsource/IATEsource.H
src/phaseSystemModels/twoPhaseEuler/twoPhaseSystem/diameterModels/IATE/IATEsources/IATEsource/IATEsource.H
src/phaseSystemModels/reactingEuler/twoPhaseSystem/diameterModels/IATE/IATEsources/IATEsource/IATEsource.C
src/phaseSystemModels/twoPhaseEuler/twoPhaseSystem/diameterModels/IATE/IATEsources/IATEsource/IATEsource.C