OpenFOAM: IsothermalPhaseModel< BasePhaseModel > Class Template Reference
IsothermalPhaseModel< BasePhaseModel > Class Template Reference
Class which represents a phase for which the temperature (strictly energy) remains constant. Returns an empty energy equation and does nothing when correctThermo is called.
#include <IsothermalPhaseModel.H>
Public Member Functions
IsothermalPhaseModel (const phaseSystem &fluid, const word &phaseName, const label index)
virtual ~IsothermalPhaseModel ()=default
virtual void correctThermo ()
virtual bool isothermal () const
virtual tmp< fvScalarMatrix > heEqn ()
Detailed Description
template<class BasePhaseModel>
class Foam::IsothermalPhaseModel< BasePhaseModel >
Class which represents a phase for which the temperature (strictly energy) remains constant. Returns an empty energy equation and does nothing when correctThermo is called.
Source files
IsothermalPhaseModel.H
IsothermalPhaseModel.C
Definition at line 49 of file IsothermalPhaseModel.H.
Constructor & Destructor Documentation
IsothermalPhaseModel()
template<class BasePhaseModel > IsothermalPhaseModel (const phaseSystem & fluid, const word & phaseName, const label index)
Definition at line 27 of file IsothermalPhaseModel.C.
~IsothermalPhaseModel()
template<class BasePhaseModel > virtual ~IsothermalPhaseModel () virtual default
Member Function Documentation
correctThermo()
template<class BasePhaseModel > void correctThermo () virtual
Definition at line 41 of file IsothermalPhaseModel.C.
References Foam::name(), GeometricField< scalar, fvPatchField, volMesh >::New(), p, and T.
isothermal()
template<class BasePhaseModel > bool isothermal () const virtual
Definition at line 61 of file IsothermalPhaseModel.C.
heEqn()
template<class BasePhaseModel > Foam::tmp< Foam::fvScalarMatrix > heEqn () virtual
Definition at line 69 of file IsothermalPhaseModel.C.
References Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/phaseModel/IsothermalPhaseModel/IsothermalPhaseModel.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/phaseModel/IsothermalPhaseModel/IsothermalPhaseModel.C