OpenFOAM: PointEdgeWaveBase Class Reference
PointEdgeWaveBase Class Reference
#include <PointEdgeWave.H>
Public Member Functions
ClassName ("PointEdgeWave")
PointEdgeWaveBase (const polyMesh &mesh)
const polyMesh & mesh () const noexcept
label nChangedPoints () const noexcept
label nChangedEdges () const noexcept
label nUnvisitedEdges () const noexcept
label nUnvisitedPoints () const noexcept
Static Public Member Functions
static scalar propagationTol () noexcept
static scalar setPropagationTol (const scalar tol) noexcept
Static Public Attributes
static int dummyTrackData_ = 12345
Protected Attributes
const polyMesh & mesh_
PstreamBuffers pBufs_
bitSet changedPoint_
bitSet changedEdge_
DynamicList< label > changedPoints_
DynamicList< label > changedEdges_
label nUnvisitedPoints_
label nUnvisitedEdges_
Static Protected Attributes
static scalar propagationTol_ = 0.01
Detailed Description
Definition at line 77 of file PointEdgeWave.H.
Constructor & Destructor Documentation
PointEdgeWaveBase()
PointEdgeWaveBase (const polyMesh & mesh) explicit
Definition at line 40 of file PointEdgeWaveBase.C.
References PstreamBuffers::allowClearRecv(), and PointEdgeWaveBase::pBufs_.
Member Function Documentation
ClassName()
ClassName ("PointEdgeWave")
propagationTol()
static scalar propagationTol () inline static noexcept
Definition at line 135 of file PointEdgeWave.H.
References PointEdgeWaveBase::propagationTol_.
setPropagationTol()
static scalar setPropagationTol (const scalar tol) inline static noexcept
Definition at line 141 of file PointEdgeWave.H.
References PointEdgeWaveBase::propagationTol_.
mesh()
const polyMesh & mesh () const inline noexcept
Definition at line 152 of file PointEdgeWave.H.
References PointEdgeWaveBase::mesh_.
nChangedPoints()
label nChangedPoints () const inline noexcept
Definition at line 155 of file PointEdgeWave.H.
References PointEdgeWaveBase::changedPoints_, and UList< T >::size().
Referenced by PointEdgeWave< Type, TrackingData >::PointEdgeWave().
nChangedEdges()
label nChangedEdges () const inline noexcept
Definition at line 158 of file PointEdgeWave.H.
References PointEdgeWaveBase::changedEdges_, and UList< T >::size().
Referenced by PointEdgeWave< Type, TrackingData >::PointEdgeWave().
nUnvisitedEdges()
label nUnvisitedEdges () const inline noexcept
Definition at line 166 of file PointEdgeWave.H.
References PointEdgeWaveBase::nUnvisitedEdges_.
nUnvisitedPoints()
label nUnvisitedPoints () const inline noexcept
Definition at line 169 of file PointEdgeWave.H.
References PointEdgeWaveBase::nUnvisitedPoints_.
Member Data Documentation
propagationTol_
Foam::scalar propagationTol_ = 0.01 static protected
Definition at line 86 of file PointEdgeWave.H.
Referenced by PointEdgeWaveBase::propagationTol(), and PointEdgeWaveBase::setPropagationTol().
mesh_
const polyMesh& mesh_ protected
Definition at line 92 of file PointEdgeWave.H.
Referenced by PointEdgeWaveBase::mesh(), and PointEdgeWave< Type, TrackingData >::PointEdgeWave().
pBufs_
PstreamBuffers pBufs_ protected
Definition at line 95 of file PointEdgeWave.H.
Referenced by PointEdgeWaveBase::PointEdgeWaveBase().
changedPoint_
bitSet changedPoint_ protected
Definition at line 98 of file PointEdgeWave.H.
changedEdge_
bitSet changedEdge_ protected
Definition at line 101 of file PointEdgeWave.H.
changedPoints_
DynamicList<label> changedPoints_ protected
Definition at line 104 of file PointEdgeWave.H.
Referenced by PointEdgeWaveBase::nChangedPoints().
changedEdges_
DynamicList<label> changedEdges_ protected
Definition at line 107 of file PointEdgeWave.H.
Referenced by PointEdgeWaveBase::nChangedEdges().
nUnvisitedPoints_
label nUnvisitedPoints_ protected
Definition at line 110 of file PointEdgeWave.H.
Referenced by PointEdgeWaveBase::nUnvisitedPoints().
nUnvisitedEdges_
label nUnvisitedEdges_ protected
Definition at line 113 of file PointEdgeWave.H.
Referenced by PointEdgeWaveBase::nUnvisitedEdges().
dummyTrackData_
int dummyTrackData_ = 12345 static
Definition at line 119 of file PointEdgeWave.H.
The documentation for this class was generated from the following files:
src/meshTools/algorithms/PointEdgeWave/PointEdgeWave.H
src/meshTools/algorithms/PointEdgeWave/PointEdgeWaveBase.C