OpenFOAM: cloudAbsorptionEmission Class Reference
cloudAbsorptionEmission Class Reference
Retrieves absorption/emission data from a cloud object.
#include <cloudAbsorptionEmission.H>
Public Member Functions
TypeName ("cloudAbsorptionEmission")
cloudAbsorptionEmission (const dictionary &dict, const fvMesh &mesh)
virtual ~cloudAbsorptionEmission ()
virtual tmp< volScalarField > aDisp (const label bandI=0) const
virtual tmp< volScalarField > eDisp (const label bandI=0) const
virtual tmp< volScalarField > EDisp (const label bandI=0) const
Public Member Functions inherited from absorptionEmissionModel
TypeName ("absorptionEmissionModel")
declareRunTimeSelectionTable (autoPtr, absorptionEmissionModel, dictionary,(const dictionary &dict, const fvMesh &mesh),(dict, mesh))
absorptionEmissionModel (const dictionary &dict, const fvMesh &mesh)
virtual ~absorptionEmissionModel ()
const fvMesh & mesh () const
const dictionary & dict () const
virtual tmp< volScalarField > a (const label bandI=0) const
virtual tmp< volScalarField > aCont (const label bandI=0) const
virtual tmp< volScalarField > e (const label bandI=0) const
virtual tmp< volScalarField > eCont (const label bandI=0) const
virtual tmp< volScalarField > E (const label bandI=0) const
virtual tmp< volScalarField > ECont (const label bandI=0) const
virtual label nBands () const
virtual const Vector2D< scalar > & bands (const label n) const
virtual bool isGrey () const
virtual void correct (volScalarField &a, PtrList< volScalarField > &aj) const
Additional Inherited Members
Static Public Member Functions inherited from absorptionEmissionModel
static autoPtr< absorptionEmissionModel > New (const dictionary &dict, const fvMesh &mesh)
Protected Attributes inherited from absorptionEmissionModel
const dictionary dict_
const fvMesh & mesh_
Detailed Description
Retrieves absorption/emission data from a cloud object.
Source files
cloudAbsorptionEmission.H
cloudAbsorptionEmission.C
Definition at line 48 of file cloudAbsorptionEmission.H.
Constructor & Destructor Documentation
cloudAbsorptionEmission()
cloudAbsorptionEmission (const dictionary & dict, const fvMesh & mesh)
Definition at line 45 of file cloudAbsorptionEmission.C.
~cloudAbsorptionEmission()
~cloudAbsorptionEmission () virtual
Definition at line 59 of file cloudAbsorptionEmission.C.
Member Function Documentation
TypeName()
TypeName ("cloudAbsorptionEmission")
aDisp()
Foam::tmp< Foam::volScalarField > aDisp (const label bandI = 0) const virtual
Reimplemented from absorptionEmissionModel.
Definition at line 66 of file cloudAbsorptionEmission.C.
References thermoCloud::ap(), Foam::dimLength, Foam::dimless, forAll, IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, and Foam::Zero.
eDisp()
Foam::tmp< Foam::volScalarField > eDisp (const label bandI = 0) const virtual
Reimplemented from absorptionEmissionModel.
Definition at line 101 of file cloudAbsorptionEmission.C.
References Foam::dimLength, Foam::dimless, tmp< T >::New(), IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, and Foam::Zero.
EDisp()
Foam::tmp< Foam::volScalarField > EDisp (const label bandI = 0) const virtual
Reimplemented from absorptionEmissionModel.
Definition at line 121 of file cloudAbsorptionEmission.C.
References Foam::dimLength, Foam::dimMass, Foam::dimTime, thermoCloud::Ep(), forAll, IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, Foam::pow3(), and Foam::Zero.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/addOns/radiation/absorptionEmission/cloudAbsorptionEmission/cloudAbsorptionEmission.H
src/lagrangian/intermediate/submodels/addOns/radiation/absorptionEmission/cloudAbsorptionEmission/cloudAbsorptionEmission.C