OpenFOAM: simpleObjectRegistry Class Reference
simpleObjectRegistry Class Reference
Object registry for simpleRegIOobject. Maintains ordering.
#include <simpleObjectRegistry.H>
Public Member Functions
simpleObjectRegistry (const label size=128)
void setValues (const dictionary &dict, bool report=false)
void setNamedValue (std::string name, int val, bool report=false)
void setNamedInt (std::string name, int val, bool report=false)
Public Member Functions inherited from Dictionary< simpleObjectRegistryEntry >
Dictionary (const label size=128)
Dictionary (const Dictionary &dict)
bool erase (const word &keyword)
Public Member Functions inherited from DictionaryBase< IDLListType, T >
DictionaryBase (const label size=128)
DictionaryBase (const DictionaryBase &dict)
template<class INew >
DictionaryBase (Istream &is, const INew &inew)
DictionaryBase (Istream &is)
bool contains (const word &keyword) const
const T * cfind (const word &keyword) const
T * find (const word &keyword)
const T * lookup (const word &keyword) const
T * lookup (const word &keyword)
wordList toc () const
wordList sortedToc () const
template<class Compare >
wordList sortedToc (const Compare &comp) const
void push_front (const word &keyword, T *ptr)
void push_back (const word &keyword, T *ptr)
T * remove (const word &keyword)
void clear ()
void transfer (DictionaryBase< IDLListType, T > &dict)
void operator= (const DictionaryBase &)
const T * operator[] (const word &key) const
T * operator[] (const word &key)
bool found (const word &key) const
const T * lookupPtr (const word &keyword) const
T * lookupPtr (const word &keyword)
void insert (const word &keyword, T *ptr)
void prepend (const word &keyword, T *ptr)
void append (const word &keyword, T *ptr)
template<class Compare >
Foam::wordList sortedToc (const Compare &comp) const
Additional Inherited Members
Protected Member Functions inherited from DictionaryBase< IDLListType, T >
void addEntries ()
Protected Attributes inherited from DictionaryBase< IDLListType, T >
HashTable< T * > hashedTs_
Detailed Description
Object registry for simpleRegIOobject. Maintains ordering.
Source files
simpleObjectRegistry.H
simpleObjectRegistry.C
Definition at line 77 of file simpleObjectRegistry.H.
Constructor & Destructor Documentation
simpleObjectRegistry()
simpleObjectRegistry (const label size = 128) inline explicit
Definition at line 86 of file simpleObjectRegistry.H.
Member Function Documentation
setValues()
void setValues (const dictionary & dict, bool report = false)
Definition at line 30 of file simpleObjectRegistry.C.
References dict, DictionaryBase< IDLListType, T >::find(), Foam::infoDetailLevel, Log, Foam::log(), Foam::name(), Foam::nl, and os().
Referenced by Time::readDict().
setNamedValue()
void setNamedValue (std::string name, int val, bool report = false)
Definition at line 84 of file simpleObjectRegistry.C.
References Foam::infoDetailLevel, Log, Foam::log(), Foam::name(), Foam::nl, and Foam::readInt().
Referenced by argList::argList(), and simpleObjectRegistry::setNamedInt().
setNamedInt()
void setNamedInt (std::string name, int val, bool report = false) inline
Definition at line 108 of file simpleObjectRegistry.H.
References simpleObjectRegistry::setNamedValue().
The documentation for this class was generated from the following files:
src/OpenFOAM/global/debug/simpleObjectRegistry.H
src/OpenFOAM/global/debug/simpleObjectRegistry.C