OpenFOAM: FitData< FitDataType, ExtendedStencil, Polynomial > Class Template Reference
FitData< FitDataType, ExtendedStencil, Polynomial > Class Template Reference abstract
Data for the upwinded and centred polynomial fit interpolation schemes. The linearCorrection_ determines whether the fit is for a corrected linear scheme (first two coefficients are corrections for owner and neighbour) or a pure upwind scheme (first coefficient is correction for owner; weight on face taken as 1).
#include <FitData.H>
Public Member Functions
FitData (const fvMesh &mesh, const ExtendedStencil &stencil, const bool linearCorrection, const scalar linearLimitFactor, const scalar centralWeight)
virtual ~FitData ()=default
const ExtendedStencil & stencil () const
scalar linearLimitFactor () const
scalar centralWeight () const
label dim () const
label minSize () const
bool linearCorrection () const
void calcFit (scalarList &coeffsi, const List< point > &, const scalar wLin, const label faci)
virtual void calcFit ()=0
bool movePoints ()
Public Member Functions inherited from MeshObject< fvMesh, MoveableMeshObject, FitDataType >
MeshObject (const fvMesh &mesh)
MeshObject (const word &objName, const fvMesh &mesh)
virtual ~MeshObject ()=default
const fvMesh & mesh () const noexcept
virtual bool writeData (Ostream &os) const
Protected Member Functions
void findFaceDirs (vector &idir, vector &jdir, vector &kdir, const label faci)
Additional Inherited Members
Static Public Member Functions inherited from MeshObject< fvMesh, MoveableMeshObject, FitDataType >
static const FitDataType & New (const fvMesh &mesh, Args &&... args)
static const FitDataType & New (const word &objName, const fvMesh &mesh, Args &&... args)
static bool Delete (const word &objName, const fvMesh &mesh)
static bool Delete (const fvMesh &mesh)
Protected Attributes inherited from MeshObject< fvMesh, MoveableMeshObject, FitDataType >
const fvMesh & mesh_
Detailed Description
template<class FitDataType, class ExtendedStencil, class Polynomial>
class Foam::FitData< FitDataType, ExtendedStencil, Polynomial >
Data for the upwinded and centred polynomial fit interpolation schemes. The linearCorrection_ determines whether the fit is for a corrected linear scheme (first two coefficients are corrections for owner and neighbour) or a pure upwind scheme (first coefficient is correction for owner; weight on face taken as 1).
Source files
FitData.H
FitData.C
Definition at line 53 of file FitData.H.
Constructor & Destructor Documentation
FitData()
template<class Form , class ExtendedStencil , class Polynomial > FitData (const fvMesh & mesh, const ExtendedStencil & stencil, const bool linearCorrection, const scalar linearLimitFactor, const scalar centralWeight)
Definition at line 29 of file FitData.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and FitData< FitDataType, ExtendedStencil, Polynomial >::linearLimitFactor().
~FitData()
template<class FitDataType , class ExtendedStencil , class Polynomial > virtual ~FitData () virtual default
Member Function Documentation
findFaceDirs()
template<class FitDataType , class ExtendedStencil , class Polynomial > void findFaceDirs (vector & idir, vector & jdir, vector & kdir, const label faci) protected
Definition at line 64 of file FitData.C.
References primitiveMesh::faceAreas(), polyMesh::geometricD(), mesh, polyMesh::nGeometricD(), and Foam::normalised().
stencil()
template<class FitDataType , class ExtendedStencil , class Polynomial > const ExtendedStencil & stencil () const inline
Definition at line 114 of file FitData.H.
linearLimitFactor()
template<class FitDataType , class ExtendedStencil , class Polynomial > scalar linearLimitFactor () const inline
Definition at line 120 of file FitData.H.
Referenced by FitData< FitDataType, ExtendedStencil, Polynomial >::FitData().
centralWeight()
template<class FitDataType , class ExtendedStencil , class Polynomial > scalar centralWeight () const inline
Definition at line 126 of file FitData.H.
dim()
template<class FitDataType , class ExtendedStencil , class Polynomial > label dim () const inline
Definition at line 132 of file FitData.H.
minSize()
template<class FitDataType , class ExtendedStencil , class Polynomial > label minSize () const inline
Definition at line 138 of file FitData.H.
linearCorrection()
template<class FitDataType , class ExtendedStencil , class Polynomial > bool linearCorrection () const inline
Definition at line 143 of file FitData.H.
calcFit() [1/2]
template<class FitDataType , class ExtendedStencil , class Polynomial > void calcFit (scalarList & coeffsi, const List< point > & C, const scalar wLin, const label faci)
Definition at line 125 of file FitData.C.
References primitiveMesh::faceCentres(), mesh, and p0.
calcFit() [2/2]
template<class FitDataType , class ExtendedStencil , class Polynomial > virtual void calcFit () pure virtual
Implemented in CentredFitSnGradData< Polynomial >.
movePoints()
template<class FitDataType , class ExtendedStencil , class Polynomial > bool movePoints ()
Definition at line 310 of file FitData.C.
The documentation for this class was generated from the following files:
src/finiteVolume/interpolation/surfaceInterpolation/schemes/FitData/FitData.H
src/finiteVolume/interpolation/surfaceInterpolation/schemes/FitData/FitData.C