OpenFOAM: sensitivityBezierFI Class Reference
sensitivityBezierFI Class Reference
Calculation of adjoint based sensitivities for Bezier control points using the FI appoach.
#include <sensitivityBezierFIIncompressible.H>
Public Member Functions
TypeName ("BezierFI")
sensitivityBezierFI (const fvMesh &mesh, const dictionary &dict, incompressibleAdjointSolver &adjointSolver)
virtual ~sensitivityBezierFI ()=default
virtual void assembleSensitivities ()
virtual void clearSensitivities ()
virtual void write (const word &baseName=word::null)
Public Member Functions inherited from FIBase
TypeName ("volumetricBSplinesFI")
FIBase (const fvMesh &mesh, const dictionary &dict, incompressibleAdjointSolver &adjointSolver)
virtual ~FIBase ()=default
virtual bool readDict (const dictionary &dict)
virtual void accumulateIntegrand (const scalar dt)
Public Member Functions inherited from shapeSensitivities
TypeName ("shapeSensitivities")
shapeSensitivities (const fvMesh &mesh, const dictionary &dict, incompressibleAdjointSolver &adjointSolver)
virtual ~shapeSensitivities ()=default
Public Member Functions inherited from adjointSensitivity
TypeName ("adjointSensitivity")
declareRunTimeSelectionTable (autoPtr, adjointSensitivity, dictionary,(const fvMesh &mesh, const dictionary &dict, incompressibleAdjointSolver &adjointSolver),(mesh, dict, adjointSolver))
adjointSensitivity (const fvMesh &mesh, const dictionary &dict, incompressibleAdjointSolver &adjointSolver)
virtual ~adjointSensitivity ()=default
const incompressibleVars & primalVars () const
const incompressibleAdjointVars & adjointVars () const
const incompressibleAdjointSolver & adjointSolver () const
virtual const scalarField & calculateSensitivities ()
const scalarField & getSensitivities () const
tmp< volTensorField > computeGradDxDbMultiplier ()
tmp< volVectorField > adjointMeshMovementSource ()
Public Member Functions inherited from sensitivity
TypeName ("sensitivity")
sensitivity (const fvMesh &mesh, const dictionary &dict)
virtual ~sensitivity ()=default
const dictionary & dict () const
virtual void computeDerivativesSize ()
Protected Member Functions
void read ()
tmp< volVectorField > solveMeshMovementEqn (const label iCP, const label idir)
Protected Member Functions inherited from FIBase
void read ()
Protected Member Functions inherited from shapeSensitivities
virtual void accumulateDirectSensitivityIntegrand (const scalar dt)
virtual void accumulateBCSensitivityIntegrand (const scalar dt)
tmp< boundaryVectorField > dvdbMult () const
Protected Attributes
Bezier Bezier_
scalarField flowSens_
scalarField dSdbSens_
scalarField dndbSens_
scalarField dxdbDirectSens_
scalarField dVdbSens_
scalarField distanceSens_
scalarField optionsSens_
scalarField bcSens_
fileName derivativesFolder_
label meshMovementIters_
scalar meshMovementResidualLimit_
volVectorField dxdb_
Protected Attributes inherited from FIBase
volTensorField gradDxDbMult_
scalarField divDxDbMult_
vectorField optionsDxDbMult_
bool includeDistance_
autoPtr< adjointEikonalSolver > eikonalSolver_
Protected Attributes inherited from shapeSensitivities
autoPtr< boundaryVectorField > dSfdbMult_
autoPtr< boundaryVectorField > dnfdbMult_
autoPtr< boundaryVectorField > dxdbDirectMult_
autoPtr< boundaryVectorField > bcDxDbMult_
Protected Attributes inherited from adjointSensitivity
scalarField derivatives_
incompressibleAdjointSolver & adjointSolver_
const incompressibleVars & primalVars_
incompressibleAdjointVars & adjointVars_
objectiveManager & objectiveManager_
Protected Attributes inherited from sensitivity
const fvMesh & mesh_
dictionary dict_
autoPtr< volScalarField > fieldSensPtr_
Additional Inherited Members
Static Public Member Functions inherited from adjointSensitivity
static autoPtr< adjointSensitivity > New (const fvMesh &mesh, const dictionary &dict, incompressibleAdjointSolver &adjointSolver)
Detailed Description
Calculation of adjoint based sensitivities for Bezier control points using the FI appoach.
Source files
sensitivityBezierFIIncompressible.H
sensitivityBezierFI.C
Definition at line 60 of file sensitivityBezierFIIncompressible.H.
Constructor & Destructor Documentation
sensitivityBezierFI()
sensitivityBezierFI (const fvMesh & mesh, const dictionary & dict, incompressibleAdjointSolver & adjointSolver)
Definition at line 114 of file sensitivityBezierFIIncompressible.C.
References sensitivityBezierFI::Bezier_, adjointSensitivity::derivatives_, sensitivityBezierFI::derivativesFolder_, Foam::mkDir(), Bezier::nBezier(), sensitivityBezierFI::read(), and Foam::Zero.
~sensitivityBezierFI()
virtual ~sensitivityBezierFI () virtual default
Member Function Documentation
read()
void read () protected
Definition at line 46 of file sensitivityBezierFIIncompressible.C.
References sensitivity::dict_, sensitivityBezierFI::meshMovementIters_, sensitivityBezierFI::meshMovementResidualLimit_, FIBase::read(), and dictionary::subOrEmptyDict().
Referenced by sensitivityBezierFI::sensitivityBezierFI(), and sensitivityBezierFI::solveMeshMovementEqn().
solveMeshMovementEqn()
tmp< volVectorField > solveMeshMovementEqn (const label iCP, const label idir) protected
Definition at line 59 of file sensitivityBezierFIIncompressible.C.
References sensitivityBezierFI::Bezier_, GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), sensitivityBezierFI::dxdb_, Bezier::dxdbFace(), Foam::endl(), Foam::gMax(), Foam::Info, Foam::fvm::laplacian(), Foam::mag(), sensitivity::mesh_, sensitivityBezierFI::meshMovementIters_, sensitivityBezierFI::meshMovementResidualLimit_, and sensitivityBezierFI::read().
Referenced by sensitivityBezierFI::assembleSensitivities().
TypeName()
TypeName ("BezierFI")
assembleSensitivities()
void assembleSensitivities () virtual
Implements FIBase.
Definition at line 157 of file sensitivityBezierFIIncompressible.C.
References shapeSensitivities::bcDxDbMult_, sensitivityBezierFI::bcSens_, sensitivityBezierFI::Bezier_, Bezier::confineXmovement(), Bezier::confineYmovement(), Bezier::confineZmovement(), adjointSensitivity::derivatives_, sensitivityBezierFI::distanceSens_, Foam::fvc::div(), FIBase::divDxDbMult_, Bezier::dndbBasedSensitivities(), sensitivityBezierFI::dndbSens_, shapeSensitivities::dnfdbMult_, sensitivityBezierFI::dSdbSens_, shapeSensitivities::dSfdbMult_, sensitivityBezierFI::dVdbSens_, shapeSensitivities::dxdbDirectMult_, sensitivityBezierFI::dxdbDirectSens_, Bezier::dxdbFace(), FIBase::eikonalSolver_, sensitivityBezierFI::flowSens_, Foam::fvc::grad(), FIBase::gradDxDbMult_, Foam::gSum(), FIBase::includeDistance_, sensitivity::mesh_, Bezier::nBezier(), FIBase::optionsDxDbMult_, sensitivityBezierFI::optionsSens_, GeometricField< Type, PatchField, GeoMesh >::primitiveField(), sensitivityBezierFI::solveMeshMovementEqn(), and T.
clearSensitivities()
void clearSensitivities () virtual
Reimplemented from FIBase.
Definition at line 285 of file sensitivityBezierFIIncompressible.C.
References sensitivityBezierFI::bcSens_, FIBase::clearSensitivities(), sensitivityBezierFI::distanceSens_, sensitivityBezierFI::dndbSens_, sensitivityBezierFI::dSdbSens_, sensitivityBezierFI::dVdbSens_, sensitivityBezierFI::dxdbDirectSens_, sensitivityBezierFI::flowSens_, sensitivityBezierFI::optionsSens_, and Foam::Zero.
write()
void write (const word & baseName = word::null) virtual
Reimplemented from shapeSensitivities.
Definition at line 300 of file sensitivityBezierFIIncompressible.C.
References adjointSensitivity::adjointVars_, sensitivityBezierFI::bcSens_, sensitivityBezierFI::Bezier_, Bezier::confineMovement(), IOstream::defaultPrecision(), adjointSensitivity::derivatives_, sensitivityBezierFI::derivativesFolder_, sensitivityBezierFI::distanceSens_, sensitivityBezierFI::dndbSens_, sensitivityBezierFI::dSdbSens_, sensitivityBezierFI::dVdbSens_, sensitivityBezierFI::dxdbDirectSens_, Foam::endl(), sensitivityBezierFI::flowSens_, Foam::Info, UPstream::master(), Foam::max(), sensitivity::mesh_, Foam::name(), Bezier::nBezier(), sensitivityBezierFI::optionsSens_, Foam::setw(), UList< T >::size(), and variablesSet::solverName().
Member Data Documentation
Bezier_
Bezier Bezier_ protected
Definition at line 67 of file sensitivityBezierFIIncompressible.H.
Referenced by sensitivityBezierFI::assembleSensitivities(), sensitivityBezierFI::sensitivityBezierFI(), sensitivityBezierFI::solveMeshMovementEqn(), and sensitivityBezierFI::write().
flowSens_
scalarField flowSens_ protected
Definition at line 70 of file sensitivityBezierFIIncompressible.H.
Referenced by sensitivityBezierFI::assembleSensitivities(), sensitivityBezierFI::clearSensitivities(), and sensitivityBezierFI::write().
dSdbSens_
scalarField dSdbSens_ protected
Definition at line 73 of file sensitivityBezierFIIncompressible.H.
Referenced by sensitivityBezierFI::assembleSensitivities(), sensitivityBezierFI::clearSensitivities(), and sensitivityBezierFI::write().
dndbSens_
scalarField dndbSens_ protected
Definition at line 76 of file sensitivityBezierFIIncompressible.H.
Referenced by sensitivityBezierFI::assembleSensitivities(), sensitivityBezierFI::clearSensitivities(), and sensitivityBezierFI::write().
dxdbDirectSens_
scalarField dxdbDirectSens_ protected
Definition at line 80 of file sensitivityBezierFIIncompressible.H.
Referenced by sensitivityBezierFI::assembleSensitivities(), sensitivityBezierFI::clearSensitivities(), and sensitivityBezierFI::write().
dVdbSens_
scalarField dVdbSens_ protected
Definition at line 83 of file sensitivityBezierFIIncompressible.H.
Referenced by sensitivityBezierFI::assembleSensitivities(), sensitivityBezierFI::clearSensitivities(), and sensitivityBezierFI::write().
distanceSens_
scalarField distanceSens_ protected
Definition at line 86 of file sensitivityBezierFIIncompressible.H.
Referenced by sensitivityBezierFI::assembleSensitivities(), sensitivityBezierFI::clearSensitivities(), and sensitivityBezierFI::write().
optionsSens_
scalarField optionsSens_ protected
Definition at line 89 of file sensitivityBezierFIIncompressible.H.
Referenced by sensitivityBezierFI::assembleSensitivities(), sensitivityBezierFI::clearSensitivities(), and sensitivityBezierFI::write().
bcSens_
scalarField bcSens_ protected
Definition at line 92 of file sensitivityBezierFIIncompressible.H.
Referenced by sensitivityBezierFI::assembleSensitivities(), sensitivityBezierFI::clearSensitivities(), and sensitivityBezierFI::write().
derivativesFolder_
fileName derivativesFolder_ protected
Definition at line 94 of file sensitivityBezierFIIncompressible.H.
Referenced by sensitivityBezierFI::sensitivityBezierFI(), and sensitivityBezierFI::write().
meshMovementIters_
label meshMovementIters_ protected
Definition at line 96 of file sensitivityBezierFIIncompressible.H.
Referenced by sensitivityBezierFI::read(), and sensitivityBezierFI::solveMeshMovementEqn().
meshMovementResidualLimit_
scalar meshMovementResidualLimit_ protected
Definition at line 97 of file sensitivityBezierFIIncompressible.H.
Referenced by sensitivityBezierFI::read(), and sensitivityBezierFI::solveMeshMovementEqn().
dxdb_
volVectorField dxdb_ protected
Definition at line 98 of file sensitivityBezierFIIncompressible.H.
Referenced by sensitivityBezierFI::solveMeshMovementEqn().
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/optimisation/adjointSensitivity/incompressible/sensitivityBezierFI/sensitivityBezierFIIncompressible.H
src/optimisation/adjointOptimisation/adjoint/optimisation/adjointSensitivity/incompressible/sensitivityBezierFI/sensitivityBezierFIIncompressible.C