OpenFOAM: curvatureSeparation Class Reference
curvatureSeparation Class Reference
Curvature film separation model.
#include <curvatureSeparation.H>
Public Member Functions
TypeName ("curvatureSeparation")
curvatureSeparation (surfaceFilmRegionModel &film, const dictionary &dict)
virtual ~curvatureSeparation ()
virtual void correct (scalarField &availableMass, scalarField &massToInject, scalarField &diameterToInject)
Public Member Functions inherited from injectionModel
TypeName ("injectionModel")
declareRunTimeSelectionTable (autoPtr, injectionModel, dictionary,(surfaceFilmRegionModel &film, const dictionary &dict),(film, dict))
injectionModel (surfaceFilmRegionModel &film)
injectionModel (const word &modelType, surfaceFilmRegionModel &film, const dictionary &dict)
virtual ~injectionModel ()
virtual scalar injectedMassTotal () const
virtual void patchInjectedMassTotals (scalarField &patchMasses) const
Public Member Functions inherited from filmSubModelBase
filmSubModelBase (surfaceFilmRegionModel &film)
filmSubModelBase (surfaceFilmRegionModel &film, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
filmSubModelBase (const word &modelName, surfaceFilmRegionModel &film, const dictionary &dict, const word &baseName, const word &modelType)
virtual ~filmSubModelBase ()
virtual bool writeTime () const
const surfaceFilmRegionModel & film () const
surfaceFilmRegionModel & film ()
template<class FilmType >
const FilmType & filmType () const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
subModelBase (const subModelBase &smb)
virtual ~subModelBase ()=default
const word & modelName () const
const dictionary & dict () const
const word & baseName () const
const word & modelType () const
const dictionary & coeffDict () const
const dictionary & properties () const
virtual bool defaultCoeffs (const bool printMsg) const
virtual bool active () const
virtual void cacheFields (const bool store)
virtual fileName localPath () const
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
bool getModelDict (const word &entryName, dictionary &dict) const
template<class Type >
bool getModelProperty (const word &entryName, Type &value) const
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
virtual void write (Ostream &os) const
Protected Member Functions
tmp< volScalarField > calcInvR1 (const volVectorField &U) const
tmp< scalarField > calcCosAngle (const surfaceScalarField &phi) const
Protected Member Functions inherited from injectionModel
void addToInjectedMass (const scalar dMass)
void correct ()
Protected Member Functions inherited from subModelBase
bool inLine () const
Protected Attributes
volTensorField gradNHat_
scalar deltaByR1Min_
List< Tuple2< label, scalar > > definedPatchRadii_
scalar magG_
vector gHat_
Protected Attributes inherited from filmSubModelBase
surfaceFilmRegionModel & filmModel_
Protected Attributes inherited from subModelBase
const word modelName_
dictionary & properties_
const dictionary dict_
const word baseName_
const word modelType_
const dictionary coeffDict_
Additional Inherited Members
Static Public Member Functions inherited from injectionModel
static autoPtr< injectionModel > New (surfaceFilmRegionModel &film, const dictionary &dict, const word &mdoelType)
Public Attributes inherited from subModelBase
bool log
Detailed Description
Curvature film separation model.
Assesses film curvature via the mesh geometry and calculates a force balance of the form:
F_sum = F_inertial + F_body + F_surface
If F_sum < 0, the film separates. Similarly, if F_sum > 0 the film will remain attached.
Based on description given by Owen and D. J. Ryley. The flow of thin liquid films around corners. International Journal of Multiphase Flow, 11(1):51-62, 1985.
Source files
curvatureSeparation.H
curvatureSeparation.C
Definition at line 64 of file curvatureSeparation.H.
Constructor & Destructor Documentation
curvatureSeparation()
curvatureSeparation (surfaceFilmRegionModel & film, const dictionary & dict)
Definition at line 219 of file curvatureSeparation.C.
References PtrList< T >::append(), subModelBase::coeffDict_, curvatureSeparation::definedPatchRadii_, Foam::exit(), Foam::FatalError, FatalErrorInFunction, filmSubModelBase::film(), Foam::findIndices(), forAll, forAllReverse, curvatureSeparation::gHat_, curvatureSeparation::magG_, patchIDs(), UPtrList< T >::size(), and PtrList< T >::transfer().
~curvatureSeparation()
~curvatureSeparation () virtual
Definition at line 271 of file curvatureSeparation.C.
Member Function Documentation
calcInvR1()
tmp< volScalarField > calcInvR1 (const volVectorField & U) const protected
Definition at line 55 of file curvatureSeparation.C.
References curvatureSeparation::definedPatchRadii_, Foam::dimVelocity, e, filmSubModelBase::film(), UPtrList< T >::first(), forAll, curvatureSeparation::gradNHat_, Foam::mag(), Foam::max(), mesh, pbm, and U.
Referenced by curvatureSeparation::correct().
calcCosAngle()
tmp< scalarField > calcCosAngle (const surfaceScalarField & phi) const protected
Definition at line 109 of file curvatureSeparation.C.
References Foam::clamp(), Foam::dimless, filmSubModelBase::film(), forAll, curvatureSeparation::gHat_, mesh, IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, phi, pp(), Foam::Zero, and fvPatchFieldBase::zeroGradientType().
Referenced by curvatureSeparation::correct().
TypeName()
TypeName ("curvatureSeparation")
correct()
void correct (scalarField & availableMass, scalarField & massToInject, scalarField & diameterToInject) virtual
Implements injectionModel.
Definition at line 277 of file curvatureSeparation.C.
References injectionModel::addToInjectedMass(), curvatureSeparation::calcCosAngle(), curvatureSeparation::calcInvR1(), injectionModel::correct(), delta, curvatureSeparation::deltaByR1Min_, Foam::dimForce, e, filmSubModelBase::film(), forAll, curvatureSeparation::magG_, Foam::magSqr(), mesh, IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, phi, rho, Foam::sqr(), Foam::sum(), U, Foam::Zero, and fvPatchFieldBase::zeroGradientType().
Member Data Documentation
gradNHat_
volTensorField gradNHat_ protected
Definition at line 84 of file curvatureSeparation.H.
Referenced by curvatureSeparation::calcInvR1().
deltaByR1Min_
scalar deltaByR1Min_ protected
Definition at line 87 of file curvatureSeparation.H.
Referenced by curvatureSeparation::correct().
definedPatchRadii_
List<Tuple2<label, scalar> > definedPatchRadii_ protected
Definition at line 91 of file curvatureSeparation.H.
Referenced by curvatureSeparation::calcInvR1(), and curvatureSeparation::curvatureSeparation().
magG_
scalar magG_ protected
Definition at line 94 of file curvatureSeparation.H.
Referenced by curvatureSeparation::correct(), and curvatureSeparation::curvatureSeparation().
gHat_
vector gHat_ protected
Definition at line 97 of file curvatureSeparation.H.
Referenced by curvatureSeparation::calcCosAngle(), and curvatureSeparation::curvatureSeparation().
The documentation for this class was generated from the following files:
src/regionModels/surfaceFilmModels/submodels/kinematic/injectionModel/curvatureSeparation/curvatureSeparation.H
src/regionModels/surfaceFilmModels/submodels/kinematic/injectionModel/curvatureSeparation/curvatureSeparation.C