OpenFOAM: triSurfaceSearch Class Reference
triSurfaceSearch Class Reference
Helper class to search on triSurface.
#include <triSurfaceSearch.H>
Public Member Functions
triSurfaceSearch (const triSurface &surface)
triSurfaceSearch (const triSurface &surface, const dictionary &dict)
triSurfaceSearch (const triSurface &surface, const scalar tolerance, const label maxTreeDepth=10)
~triSurfaceSearch ()
void clearOut ()
const indexedOctree< treeDataTriSurface > & tree () const
const triSurface & surface () const
scalar tolerance () const
label maxTreeDepth () const
boolList calcInside (const pointField &searchPoints) const
void findNearest (const pointField &samples, const scalarField &nearestDistSqr, List< pointIndexHit > &info) const
pointIndexHit nearest (const point &pt, const vector &span) const
void findLine (const pointField &start, const pointField &end, List< pointIndexHit > &info) const
void findLineAny (const pointField &start, const pointField &end, List< pointIndexHit > &info) const
void findLineAll (const pointField &start, const pointField &end, List< List< pointIndexHit > > &info) const
Detailed Description
Helper class to search on triSurface.
Source files
triSurfaceSearch.H
triSurfaceSearch.C
Definition at line 54 of file triSurfaceSearch.H.
Constructor & Destructor Documentation
triSurfaceSearch() [1/3]
triSurfaceSearch (const triSurface & surface) explicit
Definition at line 129 of file triSurfaceSearch.C.
triSurfaceSearch() [2/3]
triSurfaceSearch (const triSurface & surface, const dictionary & dict)
Definition at line 138 of file triSurfaceSearch.C.
References dict, Foam::endl(), and Foam::Info.
triSurfaceSearch() [3/3]
triSurfaceSearch (const triSurface & surface, const scalar tolerance, const label maxTreeDepth = 10)
Definition at line 163 of file triSurfaceSearch.C.
References indexedOctreeBase::perturbTol().
~triSurfaceSearch()
~triSurfaceSearch ()
Definition at line 184 of file triSurfaceSearch.C.
Member Function Documentation
clearOut()
void clearOut ()
Definition at line 190 of file triSurfaceSearch.C.
References PtrList< T >::clear().
Referenced by triSurfaceRegionSearch::clearOut().
tree()
const Foam::indexedOctree< Foam::treeDataTriSurface > & tree () const
Definition at line 199 of file triSurfaceSearch.C.
References PatchTools::calcBounds(), e, Foam::endl(), boundBox::inflate(), nPoints, indexedOctreeBase::perturbTol(), points, rndGen, UPtrList< T >::size(), WarningInFunction, and VectorSpace< Form, Cmpt, Ncmpts >::zero.
surface()
const triSurface & surface () const inline
Definition at line 125 of file triSurfaceSearch.H.
tolerance()
scalar tolerance () const inline
Definition at line 131 of file triSurfaceSearch.H.
maxTreeDepth()
label maxTreeDepth () const inline
Definition at line 137 of file triSurfaceSearch.H.
calcInside()
Foam::boolList calcInside (const pointField & searchPoints) const
Definition at line 252 of file triSurfaceSearch.C.
References forAll, volumeType::INSIDE, samples(), UList< T >::size(), and tree().
findNearest()
void findNearest (const pointField & samples, const scalarField & nearestDistSqr, List< pointIndexHit > & info) const
Definition at line 280 of file triSurfaceSearch.C.
References forAll, indexedOctreeBase::perturbTol(), samples(), PtrList< T >::setSize(), UList< T >::size(), and tree().
Referenced by triSurfaceMesh::findNearest(), and triSurfaceRegionSearch::findNearest().
nearest()
Foam::pointIndexHit nearest (const point & pt, const vector & span) const
Definition at line 310 of file triSurfaceSearch.C.
References Foam::magSqr(), and tree().
findLine()
void findLine (const pointField & start, const pointField & end, List< pointIndexHit > & info) const
Definition at line 323 of file triSurfaceSearch.C.
References forAll, indexedOctreeBase::perturbTol(), PtrList< T >::setSize(), UList< T >::size(), and tree().
Referenced by triSurfaceMesh::findLine().
findLineAny()
void findLineAny (const pointField & start, const pointField & end, List< pointIndexHit > & info) const
Definition at line 346 of file triSurfaceSearch.C.
References forAll, indexedOctreeBase::perturbTol(), PtrList< T >::setSize(), UList< T >::size(), and tree().
Referenced by triSurfaceMesh::findLineAny().
findLineAll()
void findLineAll (const pointField & start, const pointField & end, List< List< pointIndexHit > > & info) const
Definition at line 369 of file triSurfaceSearch.C.
References PtrList< T >::append(), PtrList< T >::clear(), forAll, Foam::normalised(), indexedOctreeBase::perturbTol(), UList< T >::size(), PtrList< T >::transfer(), and tree().
Referenced by triSurfaceMesh::findLineAll().
The documentation for this class was generated from the following files:
src/meshTools/triSurface/triSurfaceSearch/triSurfaceSearch.H
src/meshTools/triSurface/triSurfaceSearch/triSurfaceSearch.C