OpenFOAM: ThermalDiffusivity< BasicTurbulenceModel > Class Template Reference
ThermalDiffusivity< BasicTurbulenceModel > Class Template Reference
Templated wrapper class to provide compressible turbulence models thermal diffusivity based thermal transport.
#include <ThermalDiffusivity.H>
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef volScalarField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
ThermalDiffusivity (const word &type, const alphaField &alpha, const volScalarField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~ThermalDiffusivity ()=default
virtual tmp< volScalarField > kappa () const
virtual tmp< scalarField > kappa (const label patchi) const
virtual tmp< volScalarField > alpha () const
virtual tmp< scalarField > alpha (const label patchi) const
virtual tmp< volScalarField > alphat () const
virtual tmp< scalarField > alphat (const label patchi) const
virtual tmp< volScalarField > kappaEff () const
virtual tmp< scalarField > kappaEff (const label patchi) const
virtual tmp< volScalarField > alphaEff () const
virtual tmp< scalarField > alphaEff (const label patchi) const
Static Public Member Functions
static autoPtr< ThermalDiffusivity > New (const alphaField &alpha, const volScalarField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transportModel, const word &propertiesName=turbulenceModel::propertiesName)
static autoPtr< ThermalDiffusivity > New (const volScalarField &rho, const volVectorField &U, const surfaceScalarField &phi, const transportModel &transportModel, const word &propertiesName=turbulenceModel::propertiesName)
Detailed Description
template<class BasicTurbulenceModel>
class Foam::ThermalDiffusivity< BasicTurbulenceModel >
Templated wrapper class to provide compressible turbulence models thermal diffusivity based thermal transport.
Source files
ThermalDiffusivity.H
ThermalDiffusivity.C
Definition at line 47 of file ThermalDiffusivity.H.
Member Typedef Documentation
alphaField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 54 of file ThermalDiffusivity.H.
rhoField
template<class BasicTurbulenceModel > typedef volScalarField rhoField
Definition at line 55 of file ThermalDiffusivity.H.
transportModel
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 56 of file ThermalDiffusivity.H.
Constructor & Destructor Documentation
ThermalDiffusivity()
template<class BasicTurbulenceModel > ThermalDiffusivity (const word & type, const alphaField & alpha, const volScalarField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName)
Definition at line 26 of file ThermalDiffusivity.C.
~ThermalDiffusivity()
template<class BasicTurbulenceModel > virtual ~ThermalDiffusivity () virtual default
Member Function Documentation
New() [1/2]
template<class BasicTurbulenceModel > Foam::autoPtr< Foam::ThermalDiffusivity< BasicTurbulenceModel > > New (const alphaField & alpha, const volScalarField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transportModel, const word & propertiesName = turbulenceModel::propertiesName) static
Definition at line 56 of file ThermalDiffusivity.C.
New() [2/2]
template<class BasicTurbulenceModel > Foam::autoPtr< Foam::ThermalDiffusivity< BasicTurbulenceModel > > New (const volScalarField & rho, const volVectorField & U, const surfaceScalarField & phi, const transportModel & transportModel, const word & propertiesName = turbulenceModel::propertiesName) static
Definition at line 86 of file ThermalDiffusivity.C.
kappa() [1/2]
template<class BasicTurbulenceModel > virtual tmp< volScalarField > kappa () const inline virtual
Definition at line 108 of file ThermalDiffusivity.H.
Referenced by ThermalDiffusivity< BasicTurbulenceModel >::kappaEff(), and ThermalDiffusivity< BasicTurbulenceModel >::kappaEff().
kappa() [2/2]
template<class BasicTurbulenceModel > virtual tmp< scalarField > kappa (const label patchi) const inline virtual
Definition at line 115 of file ThermalDiffusivity.H.
alpha() [1/2]
template<class BasicTurbulenceModel > virtual tmp< volScalarField > alpha () const inline virtual
Definition at line 121 of file ThermalDiffusivity.H.
alpha() [2/2]
template<class BasicTurbulenceModel > virtual tmp< scalarField > alpha (const label patchi) const inline virtual
Definition at line 128 of file ThermalDiffusivity.H.
alphat() [1/2]
template<class BasicTurbulenceModel > Foam::tmp< Foam::volScalarField > alphat () const virtual
Reimplemented in EddyDiffusivity< compressible::turbulenceModel >, EddyDiffusivity< phaseCompressibleTurbulenceModel >, and EddyDiffusivity< ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > > >.
Definition at line 114 of file ThermalDiffusivity.C.
References Foam::dimDensity, Foam::dimViscosity, IOobject::groupName(), tmp< T >::New(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, and Foam::Zero.
alphat() [2/2]
template<class BasicTurbulenceModel > Foam::tmp< Foam::scalarField > alphat (const label patchi) const virtual
Reimplemented in EddyDiffusivity< compressible::turbulenceModel >, EddyDiffusivity< phaseCompressibleTurbulenceModel >, and EddyDiffusivity< ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > > >.
Definition at line 134 of file ThermalDiffusivity.C.
kappaEff() [1/2]
template<class BasicTurbulenceModel > virtual tmp< volScalarField > kappaEff () const inline virtual
Reimplemented in EddyDiffusivity< compressible::turbulenceModel >, EddyDiffusivity< phaseCompressibleTurbulenceModel >, and EddyDiffusivity< ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > > >.
Definition at line 142 of file ThermalDiffusivity.H.
References ThermalDiffusivity< BasicTurbulenceModel >::kappa().
kappaEff() [2/2]
template<class BasicTurbulenceModel > virtual tmp< scalarField > kappaEff (const label patchi) const inline virtual
Reimplemented in EddyDiffusivity< compressible::turbulenceModel >, EddyDiffusivity< phaseCompressibleTurbulenceModel >, and EddyDiffusivity< ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > > >.
Definition at line 149 of file ThermalDiffusivity.H.
References ThermalDiffusivity< BasicTurbulenceModel >::kappa().
alphaEff() [1/2]
template<class BasicTurbulenceModel > virtual tmp< volScalarField > alphaEff () const inline virtual
Reimplemented in EddyDiffusivity< compressible::turbulenceModel >, EddyDiffusivity< phaseCompressibleTurbulenceModel >, and EddyDiffusivity< ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > > >.
Definition at line 156 of file ThermalDiffusivity.H.
Referenced by heatTransferCoeffModel::q().
alphaEff() [2/2]
template<class BasicTurbulenceModel > virtual tmp< scalarField > alphaEff (const label patchi) const inline virtual
Reimplemented in EddyDiffusivity< compressible::turbulenceModel >, EddyDiffusivity< phaseCompressibleTurbulenceModel >, and EddyDiffusivity< ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > > >.
Definition at line 163 of file ThermalDiffusivity.H.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/turbulence/phaseCompressibleTurbulenceModelFwd.H
src/TurbulenceModels/compressible/ThermalDiffusivity/ThermalDiffusivity.H
src/TurbulenceModels/compressible/ThermalDiffusivity/ThermalDiffusivity.C