OpenFOAM: HashTable< T, Key, Hash >::iterator Class Reference
HashTable< T, Key, Hash >::iterator Class Reference
#include <HashTable.H>
Public Types
using iterator_category = std::forward_iterator_tag
using difference_type = this_type::difference_type
using node_type = this_type::node_type
using key_type = this_type::key_type
using mapped_type = this_type::mapped_type
using value_type = this_type::value_type
using pointer = this_type::pointer
using reference = this_type::reference
using const_pointer = this_type::const_pointer
using const_reference = this_type::const_reference
Public Types inherited from HashTable< T, Key, Hash >::Iterator< false >
using iterator_category = std::forward_iterator_tag
using difference_type = this_type::difference_type
using table_type = typename std::conditional< Const, const this_type, this_type >::type
using node_type = typename std::conditional< Const, const this_type::node_type, this_type::node_type >::type
using key_type = this_type::key_type
using mapped_type = typename std::conditional< Const, const this_type::mapped_type, this_type::mapped_type >::type
Public Member Functions
iterator ()=default
iterator (const Iterator< false > &iter)
const node_type * node () const noexcept
node_type * node () noexcept
const_reference val () const
reference val ()
const_reference operator* () const
const_reference operator() () const
reference operator* ()
reference operator() ()
iterator & operator++ ()
iterator operator++ (int)
Public Member Functions inherited from HashTable< T, Key, Hash >::Iterator< false >
bool good () const noexcept
bool found () const noexcept
const Key & key () const
Ostream & print (Ostream &os) const
operator bool () const noexcept
bool operator== (const Iterator< Any > &iter) const noexcept
bool operator!= (const Iterator< Any > &iter) const noexcept
Additional Inherited Members
Protected Member Functions inherited from HashTable< T, Key, Hash >::Iterator< false >
constexpr Iterator () noexcept
Iterator (table_type *tbl)
Iterator (table_type *tbl, const Key &key)
void increment ()
operator const Iterator< Any > & () const
Protected Attributes inherited from HashTable< T, Key, Hash >::Iterator< false >
node_type * entry_
table_type * container_
label index_
Detailed Description
template<class T, class Key = word, class Hash = Foam::Hash<Key>>
class Foam::HashTable< T, Key, Hash >::iterator
Definition at line 736 of file HashTable.H.
Member Typedef Documentation
iterator_category
template<class T , class Key = word, class Hash = Foam::Hash<Key>> using iterator_category = std::forward_iterator_tag
Definition at line 743 of file HashTable.H.
difference_type
template<class T , class Key = word, class Hash = Foam::Hash<Key>> using difference_type = this_type::difference_type
Definition at line 744 of file HashTable.H.
node_type
template<class T , class Key = word, class Hash = Foam::Hash<Key>> using node_type = this_type::node_type
Definition at line 746 of file HashTable.H.
key_type
template<class T , class Key = word, class Hash = Foam::Hash<Key>> using key_type = this_type::key_type
Definition at line 747 of file HashTable.H.
mapped_type
template<class T , class Key = word, class Hash = Foam::Hash<Key>> using mapped_type = this_type::mapped_type
Definition at line 748 of file HashTable.H.
value_type
template<class T , class Key = word, class Hash = Foam::Hash<Key>> using value_type = this_type::value_type
Definition at line 749 of file HashTable.H.
pointer
template<class T , class Key = word, class Hash = Foam::Hash<Key>> using pointer = this_type::pointer
Definition at line 750 of file HashTable.H.
reference
template<class T , class Key = word, class Hash = Foam::Hash<Key>> using reference = this_type::reference
Definition at line 751 of file HashTable.H.
const_pointer
template<class T , class Key = word, class Hash = Foam::Hash<Key>> using const_pointer = this_type::const_pointer
Definition at line 752 of file HashTable.H.
const_reference
template<class T , class Key = word, class Hash = Foam::Hash<Key>> using const_reference = this_type::const_reference
Definition at line 753 of file HashTable.H.
Constructor & Destructor Documentation
iterator() [1/2]
template<class T , class Key = word, class Hash = Foam::Hash<Key>> iterator () default
iterator() [2/2]
template<class T , class Key = word, class Hash = Foam::Hash<Key>> iterator (const Iterator< false > & iter) inline explicit
Definition at line 762 of file HashTable.H.
Member Function Documentation
node() [1/2]
template<class T , class Key = word, class Hash = Foam::Hash<Key>> const node_type * node () const inline noexcept
Definition at line 771 of file HashTable.H.
node() [2/2]
template<class T , class Key = word, class Hash = Foam::Hash<Key>> node_type * node () inline noexcept
Definition at line 777 of file HashTable.H.
val() [1/2]
template<class T , class Key = word, class Hash = Foam::Hash<Key>> const_reference val () const inline
Definition at line 783 of file HashTable.H.
Referenced by HashTable< T, Key, Hash >::at(), HashTable< T, Key, Hash >::iterator::operator()(), HashTable< T, Key, Hash >::iterator::operator()(), HashTable< T, Key, Hash >::operator()(), HashTable< T, Key, Hash >::iterator::operator*(), and HashTable< T, Key, Hash >::iterator::operator*().
val() [2/2]
template<class T , class Key = word, class Hash = Foam::Hash<Key>> reference val () inline
Definition at line 789 of file HashTable.H.
operator*() [1/2]
template<class T , class Key = word, class Hash = Foam::Hash<Key>> const_reference operator* () const inline
Definition at line 795 of file HashTable.H.
References HashTable< T, Key, Hash >::iterator::val().
operator()() [1/2]
template<class T , class Key = word, class Hash = Foam::Hash<Key>> const_reference operator() () const inline
Definition at line 796 of file HashTable.H.
References HashTable< T, Key, Hash >::iterator::val().
operator*() [2/2]
template<class T , class Key = word, class Hash = Foam::Hash<Key>> reference operator* () inline
Definition at line 799 of file HashTable.H.
References HashTable< T, Key, Hash >::iterator::val().
operator()() [2/2]
template<class T , class Key = word, class Hash = Foam::Hash<Key>> reference operator() () inline
Definition at line 800 of file HashTable.H.
References HashTable< T, Key, Hash >::iterator::val().
operator++() [1/2]
template<class T , class Key , class Hash > Foam::HashTable< T, Key, Hash >::iterator & operator++ () inline
Definition at line 125 of file HashTableIterI.H.
operator++() [2/2]
template<class T , class Key , class Hash > Foam::HashTable< T, Key, Hash >::iterator operator++ (int) inline
Definition at line 134 of file HashTableIterI.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/HashTables/HashTable/HashTable.H
src/OpenFOAM/containers/HashTables/HashTable/HashTableIterI.H