OpenFOAM: VTKsurfaceFormatCore Class Reference
VTKsurfaceFormatCore Class Reference
Internal class used by the VTKsurfaceFormat Format is LEGACY_ASCII.
#include <VTKsurfaceFormatCore.H>
Static Protected Member Functions
static vtk::outputOptions formatOptions (const dictionary &dict, vtk::outputOptions opts=vtk::formatType::LEGACY_ASCII)
static void writeHeader (vtk::formatter &format, const UList< point > &pts)
static void writeCellData (vtk::formatter &format, const UList< surfZone > &zones)
static void writeCellData (vtk::formatter &format, const labelUList &zoneIds)
Detailed Description
Internal class used by the VTKsurfaceFormat Format is LEGACY_ASCII.
Output Options
Property Description Required Default
format ascii or binary format no ascii
precision Write precision in ascii no same as IOstream
Source files
VTKsurfaceFormatCore.H
VTKsurfaceFormatCore.C
Definition at line 73 of file VTKsurfaceFormatCore.H.
Member Function Documentation
formatOptions()
Foam::vtk::outputOptions formatOptions (const dictionary & dict, vtk::outputOptions opts = vtk::formatType::LEGACY_ASCII) static protected
Definition at line 27 of file VTKsurfaceFormatCore.C.
References outputOptions::append(), outputOptions::ascii(), IOstreamOption::ASCII, IOstream::defaultPrecision(), dict, IOstreamOption::formatEnum(), outputOptions::legacy(), and outputOptions::precision().
writeHeader()
void writeHeader (vtk::formatter & format, const UList< point > & pts) static protected
Definition at line 51 of file VTKsurfaceFormatCore.C.
References Foam::vtk::legacy::beginPoints(), clock::dateTime(), format(), pts, and Foam::vtk::writeList().
writeCellData() [1/2]
void writeCellData (vtk::formatter & format, const UList< surfZone > & zones) static protected
Definition at line 70 of file VTKsurfaceFormatCore.C.
References Foam::vtk::legacy::beginCellData(), format(), UPtrList< T >::size(), and Foam::vtk::write().
writeCellData() [2/2]
void writeCellData (vtk::formatter & format, const labelUList & zoneIds) static protected
Definition at line 98 of file VTKsurfaceFormatCore.C.
References Foam::vtk::legacy::beginCellData(), format(), UList< T >::size(), and Foam::vtk::writeList().
The documentation for this class was generated from the following files:
src/surfMesh/surfaceFormats/vtk/VTKsurfaceFormatCore.H
src/surfMesh/surfaceFormats/vtk/VTKsurfaceFormatCore.C