OpenFOAM: RanzMarshall Class Reference
RanzMarshall Class Reference
#include <RanzMarshall.H>
Public Member Functions
TypeName ("RanzMarshall")
RanzMarshall (const dictionary &interfaceDict, const volScalarField &alpha1, const phaseModel &phase1, const phaseModel &phase2)
virtual ~RanzMarshall ()
tmp< volScalarField > K (const volScalarField &Ur) const
Public Member Functions inherited from heatTransferModel
TypeName ("heatTransferModel")
declareRunTimeSelectionTable (autoPtr, heatTransferModel, dictionary,(const dictionary &dict, const volScalarField &alpha1, const phaseModel &phase1, const phaseModel &phase2),(dict, alpha1, phase1, phase2))
heatTransferModel (const dictionary &dict, const volScalarField &alpha1, const phaseModel &phase1, const phaseModel &phase2)
virtual ~heatTransferModel ()=default
Additional Inherited Members
Static Public Member Functions inherited from heatTransferModel
static autoPtr< heatTransferModel > New (const dictionary &dict, const volScalarField &alpha1, const phaseModel &phase1, const phaseModel &phase2)
Protected Attributes inherited from heatTransferModel
const dictionary & interfaceDict_
const volScalarField & alpha1_
const phaseModel & phase1_
const phaseModel & phase2_
Detailed Description
Source files
RanzMarshall.H
RanzMarshall.C
Definition at line 50 of file RanzMarshall.H.
Constructor & Destructor Documentation
RanzMarshall()
RanzMarshall (const dictionary & interfaceDict, const volScalarField & alpha1, const phaseModel & phase1, const phaseModel & phase2)
Definition at line 48 of file RanzMarshall.C.
~RanzMarshall()
~RanzMarshall () virtual
Definition at line 62 of file RanzMarshall.C.
Member Function Documentation
TypeName()
TypeName ("RanzMarshall")
K()
Foam::tmp< Foam::volScalarField > K (const volScalarField & Ur) const virtual
Implements heatTransferModel.
Definition at line 69 of file RanzMarshall.C.
References Foam::cbrt(), Foam::max(), Foam::Re(), Foam::sqr(), and Foam::sqrt().
The documentation for this class was generated from the following files:
src/phaseSystemModels/multiphaseEuler/multiphaseSystem/interfacialModels/heatTransferModels/RanzMarshall/RanzMarshall.H
src/phaseSystemModels/multiphaseEuler/multiphaseSystem/interfacialModels/heatTransferModels/RanzMarshall/RanzMarshall.C