OpenFOAM: massTransferModel Class Reference
massTransferModel Class Reference abstract
#include <massTransferModel.H>
Public Member Functions
TypeName ("massTransferModel")
declareRunTimeSelectionTable (autoPtr, massTransferModel, dictionary,(const dictionary &dict, const phasePair &pair),(dict, pair))
massTransferModel (const dictionary &dict, const phasePair &pair)
virtual ~massTransferModel ()=default
virtual tmp< volScalarField > K () const =0
Static Public Member Functions
static autoPtr< massTransferModel > New (const dictionary &dict, const phasePair &pair)
Static Public Attributes
static const dimensionSet dimK
Protected Attributes
const phasePair & pair_
Detailed Description
Source files
massTransferModel.H
massTransferModel.C
Definition at line 51 of file massTransferModel.H.
Constructor & Destructor Documentation
massTransferModel()
massTransferModel (const dictionary & dict, const phasePair & pair)
Definition at line 40 of file massTransferModel.C.
~massTransferModel()
virtual ~massTransferModel () virtual default
Member Function Documentation
TypeName()
TypeName ("massTransferModel")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , massTransferModel , dictionary , (const dictionary &dict, const phasePair &pair) , (dict, pair))
New()
Foam::autoPtr< Foam::massTransferModel > New (const dictionary & dict, const phasePair & pair) static
Definition at line 53 of file massTransferModel.C.
References Foam::abort(), dict, Foam::endl(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), and Foam::Info.
K()
virtual tmp< volScalarField > K () const pure virtual
Implemented in Frossling, and sphericalMassTransfer.
Member Data Documentation
pair_
const phasePair& pair_ protected
Definition at line 58 of file massTransferModel.H.
dimK
const Foam::dimensionSet dimK static
Definition at line 85 of file massTransferModel.H.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/interfacialCompositionModels/massTransferModels/massTransferModel/massTransferModel.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/interfacialCompositionModels/massTransferModels/massTransferModel/massTransferModel.C