OpenFOAM: AABBTree< Type > Class Template Reference
AABBTree< Type > Class Template Reference
Templated tree of axis-aligned bounding boxes (AABB)
#include <AABBTree.H>
Public Member Functions
AABBTree ()
AABBTree (const UList< Type > &objects, const pointField &points, const bool equalBinSize=true, label maxLevel=3, label minBinSize=100)
const List< treeBoundBox > & boundBoxes () const noexcept
const List< labelList > & addressing () const noexcept
bool pointInside (const point &pt) const
bool overlaps (const boundBox &bbIn) const
void writeOBJ (Ostream &os) const
Public Member Functions inherited from AABBTreeBase
AABBTreeBase ()=default
Protected Member Functions
void writeOBJ (const bool leavesOnly, const bool writeLinesOnly, const treeBoundBox &bb, const label nodeI, const List< Pair< treeBoundBox > > &bbs, const List< Pair< label > > &nodes, label &vertI, Ostream &os) const
void createBoxes (const bool equalBinSize, const label level, const UList< Type > &objects, const pointField &points, const labelUList &objectIDs, const treeBoundBox &bb, const label nodeI, DynamicList< Pair< treeBoundBox > > &bbs, DynamicList< labelPair > &nodes, DynamicList< labelList > &addressing) const
Protected Attributes
label maxLevel_
label minLeafSize_
List< treeBoundBox > boundBoxes_
List< labelList > addressing_
Friends
Istream & operator>> (Istream &, AABBTree &)
Ostream & operator<< (Ostream &, const AABBTree &)
Additional Inherited Members
Static Public Member Functions inherited from AABBTreeBase
static void writeOBJ (Ostream &os, const treeBoundBox &bb, label &vertIndex, const bool writeLinesOnly=false)
Static Protected Attributes inherited from AABBTreeBase
static scalar tolerance_ = 1e-4
Detailed Description
template<class Type>
class Foam::AABBTree< Type >
Templated tree of axis-aligned bounding boxes (AABB)
Designed to be templated on either faces or cells, the AABBTree will decompose the input into a tree of AABB's. The maximum number of tree levels and minimum number of objects per leaf are provided on construction, and the contents (addressing) is stored.
Source files
AABBTree.H
AABBTree.C
AABBTreeBase.C
Definition at line 107 of file AABBTree.H.
Constructor & Destructor Documentation
AABBTree() [1/2]
template<class Type > AABBTree ()
Definition at line 270 of file AABBTree.C.
AABBTree() [2/2]
template<class Type > AABBTree (const UList< Type > & objects, const pointField & points, const bool equalBinSize = true, label maxLevel = 3, label minBinSize = 100)
Definition at line 280 of file AABBTree.C.
References AABBTree< Type >::addressing(), AABBTree< Type >::addressing_, AABBTree< Type >::boundBoxes(), AABBTree< Type >::boundBoxes_, UPtrList< T >::count(), AABBTree< Type >::createBoxes(), PtrList< T >::emplace_back(), UPtrList< T >::empty(), Foam::endl(), forAll, Foam::identity(), Foam::Info, points, PtrList< T >::push_back(), PtrList< T >::set(), UPtrList< T >::size(), and List< T >::transfer().
Member Function Documentation
writeOBJ() [1/2]
template<class Type > void writeOBJ (const bool leavesOnly, const bool writeLinesOnly, const treeBoundBox & bb, const label nodeI, const List< Pair< treeBoundBox > > & bbs, const List< Pair< label > > & nodes, label & vertI, Ostream & os) const protected
Definition at line 28 of file AABBTree.C.
References UPtrList< T >::first(), os(), and AABBTreeBase::writeOBJ().
createBoxes()
template<class Type > void createBoxes (const bool equalBinSize, const label level, const UList< Type > & objects, const pointField & points, const labelUList & objectIDs, const treeBoundBox & bb, const label nodeI, DynamicList< Pair< treeBoundBox > > & bbs, DynamicList< labelPair > & nodes, DynamicList< labelList > & addressing) const protected
Definition at line 75 of file AABBTree.C.
References Foam::component(), PtrList< T >::emplace_back(), boundBox::maxDir(), boundBox::min(), points, PtrList< T >::push_back(), PtrList< T >::set(), UPtrList< T >::size(), Foam::sort(), and boundBox::span().
Referenced by AABBTree< Type >::AABBTree().
boundBoxes()
template<class Type > const List< treeBoundBox > & boundBoxes () const inline noexcept
Definition at line 184 of file AABBTree.H.
References AABBTree< Type >::boundBoxes_.
Referenced by AABBTree< Type >::AABBTree().
addressing()
template<class Type > const List< labelList > & addressing () const inline noexcept
Definition at line 190 of file AABBTree.H.
References AABBTree< Type >::addressing_.
Referenced by AABBTree< Type >::AABBTree().
pointInside()
template<class Type > bool pointInside (const point & pt) const
Definition at line 403 of file AABBTree.C.
overlaps()
template<class Type > bool overlaps (const boundBox & bbIn) const
Definition at line 418 of file AABBTree.C.
writeOBJ() [2/2]
template<class Type > void writeOBJ (Ostream & os) const
Definition at line 390 of file AABBTree.C.
References os(), and AABBTreeBase::writeOBJ().
Friends And Related Symbol Documentation
operator>>
template<class Type > Istream & operator>> (Istream & , AABBTree< Type > &) friend
operator<<
template<class Type > Ostream & operator<< (Ostream & , const AABBTree< Type > &) friend
Member Data Documentation
maxLevel_
template<class Type > label maxLevel_ protected
Definition at line 116 of file AABBTree.H.
minLeafSize_
template<class Type > label minLeafSize_ protected
Definition at line 119 of file AABBTree.H.
boundBoxes_
template<class Type > List<treeBoundBox> boundBoxes_ protected
Definition at line 122 of file AABBTree.H.
Referenced by AABBTree< Type >::AABBTree(), and AABBTree< Type >::boundBoxes().
addressing_
template<class Type > List<labelList> addressing_ protected
Definition at line 125 of file AABBTree.H.
Referenced by AABBTree< Type >::AABBTree(), and AABBTree< Type >::addressing().
The documentation for this class was generated from the following files:
src/OpenFOAM/algorithms/AABBTree/AABBTree.H
src/OpenFOAM/algorithms/AABBTree/AABBTree.C