OpenFOAM: kkLOmega Class Reference
kkLOmega Class Reference
Low Reynolds-number k-kl-omega turbulence model for incompressible flows.
#include <kkLOmega.H>
Public Member Functions
TypeName ("kkLOmega")
kkLOmega (const geometricOneField &alpha, const geometricOneField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
virtual ~kkLOmega ()=default
virtual bool read ()
tmp< volScalarField > DkEff (const volScalarField &alphaT) const
tmp< volScalarField > DomegaEff (const volScalarField &alphaT) const
virtual tmp< volScalarField > kl () const
virtual tmp< volScalarField > kt () const
virtual tmp< volScalarField > omega () const
virtual tmp< volScalarField > k () const
virtual tmp< volScalarField > epsilon () const
virtual void validate ()
virtual void correct ()
Public Member Functions inherited from eddyViscosity< incompressible::RASModel >
eddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~eddyViscosity ()=default
virtual tmp< volScalarField > nut () const
virtual tmp< scalarField > nut (const label patchi) const
virtual tmp< volSymmTensorField > R () const
Public Member Functions inherited from linearViscousStress< BasicTurbulenceModel >
linearViscousStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~linearViscousStress ()=default
virtual tmp< volSymmTensorField > devRhoReff () const
virtual tmp< volSymmTensorField > devRhoReff (const volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Protected Member Functions
virtual void correctNut ()
Protected Attributes
dimensionedScalar A0_
dimensionedScalar As_
dimensionedScalar Av_
dimensionedScalar Abp_
dimensionedScalar Anat_
dimensionedScalar Ats_
dimensionedScalar CbpCrit_
dimensionedScalar Cnc_
dimensionedScalar CnatCrit_
dimensionedScalar Cint_
dimensionedScalar CtsCrit_
dimensionedScalar CrNat_
dimensionedScalar C11_
dimensionedScalar C12_
dimensionedScalar CR_
dimensionedScalar CalphaTheta_
dimensionedScalar Css_
dimensionedScalar CtauL_
dimensionedScalar Cw1_
dimensionedScalar Cw2_
dimensionedScalar Cw3_
dimensionedScalar CwR_
dimensionedScalar Clambda_
dimensionedScalar CmuStd_
dimensionedScalar Prtheta_
dimensionedScalar Sigmak_
dimensionedScalar Sigmaw_
volScalarField kt_
volScalarField kl_
volScalarField omega_
volScalarField epsilon_
const volScalarField & y_
Protected Attributes inherited from eddyViscosity< incompressible::RASModel >
volScalarField nut_
Additional Inherited Members
Public Types inherited from eddyViscosity< incompressible::RASModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from linearViscousStress< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Detailed Description
Low Reynolds-number k-kl-omega turbulence model for incompressible flows.
Reference:
    Standard model:
        Walters, D. K., & Cokljat, D. (2008).
        A three-equation eddy-viscosity model for Reynolds-averaged
        NavierStokes simulations of transitional flow.
        Journal of Fluids Engineering, 130(12), 121401.
        DOI:10.1115/1.2979230
    Typo corrections:
        Furst, J. (2013).
        Numerical simulation of transitional flows
        with laminar kinetic energy.
        Engineering MECHANICS, 20(5), 379-388.
The default model coefficients are
    kkLOmegaCoeffs
    {
        A0             4.04
        As             2.12
        Av             6.75
        Abp            0.6
        Anat           200
        Ats            200
        CbpCrit        1.2
        Cnc            0.1
        CnatCrit       1250
        Cint           0.75
        CtsCrit        1000
        CrNat          0.02
        C11            3.4e-6
        C12            1.0e-10
        CR             0.12
        CalphaTheta    0.035
        Css            1.5
        CtauL          4360
        Cw1            0.44
        Cw2            0.92
        Cw3            0.3
        CwR            1.5
        Clambda        2.495
        CmuStd         0.09
        Prtheta        0.85
        Sigmak         1
        Sigmaw         1.17
    }
Source files
kkLOmega.H
kkLOmega.C
Definition at line 106 of file kkLOmega.H.
Constructor & Destructor Documentation
kkLOmega()
kkLOmega (const geometricOneField & alpha, const geometricOneField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Definition at line 218 of file kkLOmega.C.
References Foam::bound(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), kkLOmega::epsilon_, kkLOmega::kl_, kkLOmega::kt_, eddyViscosity< incompressible::RASModel >::nut_, kkLOmega::omega_, and Foam::type().
~kkLOmega()
virtual ~kkLOmega () virtual default
Member Function Documentation
correctNut()
void correctNut () protected virtual
Implements eddyViscosity< incompressible::RASModel >.
Definition at line 208 of file kkLOmega.C.
References NotImplemented.
TypeName()
TypeName ("kkLOmega")
read()
bool read () virtual
Implements eddyViscosity< incompressible::RASModel >.
Definition at line 550 of file kkLOmega.C.
References kkLOmega::A0_, kkLOmega::Abp_, kkLOmega::Anat_, kkLOmega::As_, kkLOmega::Ats_, kkLOmega::Av_, kkLOmega::C11_, kkLOmega::C12_, kkLOmega::CalphaTheta_, kkLOmega::CbpCrit_, kkLOmega::Cint_, kkLOmega::Clambda_, kkLOmega::CmuStd_, kkLOmega::CnatCrit_, kkLOmega::Cnc_, kkLOmega::CR_, kkLOmega::CrNat_, kkLOmega::Css_, kkLOmega::CtauL_, kkLOmega::CtsCrit_, kkLOmega::Cw1_, kkLOmega::Cw2_, kkLOmega::Cw3_, kkLOmega::CwR_, kkLOmega::Prtheta_, dimensioned< Type >::readIfPresent(), kkLOmega::Sigmak_, and kkLOmega::Sigmaw_.
DkEff()
tmp< volScalarField > DkEff (const volScalarField & alphaT) const inline
Definition at line 238 of file kkLOmega.H.
References nu, and kkLOmega::Sigmak_.
Referenced by kkLOmega::correct().
DomegaEff()
tmp< volScalarField > DomegaEff (const volScalarField & alphaT) const inline
Definition at line 247 of file kkLOmega.H.
References nu, and kkLOmega::Sigmaw_.
Referenced by kkLOmega::correct().
kl()
virtual tmp< volScalarField > kl () const inline virtual
Definition at line 256 of file kkLOmega.H.
References kkLOmega::kl_.
kt()
virtual tmp< volScalarField > kt () const inline virtual
Definition at line 262 of file kkLOmega.H.
References kkLOmega::kt_.
omega()
virtual tmp< volScalarField > omega () const inline virtual
Definition at line 268 of file kkLOmega.H.
References kkLOmega::omega_.
k()
virtual tmp< volScalarField > k () const inline virtual
Implements eddyViscosity< incompressible::RASModel >.
Definition at line 274 of file kkLOmega.H.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), kkLOmega::kl_, kkLOmega::kt_, and kkLOmega::omega_.
epsilon()
virtual tmp< volScalarField > epsilon () const inline virtual
Definition at line 293 of file kkLOmega.H.
References kkLOmega::epsilon_.
validate()
void validate () virtual
Reimplemented from eddyViscosity< incompressible::RASModel >.
Definition at line 590 of file kkLOmega.C.
correct()
void correct () virtual
Implements eddyViscosity< incompressible::RASModel >.
Definition at line 594 of file kkLOmega.C.
References kkLOmega::Abp_, kkLOmega::Anat_, Foam::bound(), GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), kkLOmega::C11_, kkLOmega::C12_, kkLOmega::Clambda_, kkLOmega::Cnc_, eddyViscosity< BasicTurbulenceModel >::correct(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), kkLOmega::CR_, kkLOmega::CrNat_, kkLOmega::Cw1_, kkLOmega::Cw2_, kkLOmega::Cw3_, kkLOmega::CwR_, D, Foam::fvm::ddt(), Foam::devSymm(), Foam::dimLength, Foam::dimless, Foam::fvm::div(), kkLOmega::DkEff(), kkLOmega::DomegaEff(), kkLOmega::epsilon_, GeometricBoundaryField< Type, PatchField, GeoMesh >::evaluateCoupled(), Foam::exp(), fv(), Foam::fvc::grad(), kkLOmega::kl_, kkLOmega::kt_, Foam::fvm::laplacian(), Foam::mag(), Foam::magSqr(), Foam::min(), nu, eddyViscosity< incompressible::RASModel >::nut_, kkLOmega::omega_, Foam::pow(), Foam::pow3(), Foam::skew(), solve(), Foam::fvm::Sp(), Foam::sqr(), Foam::sqrt(), Foam::fvm::SuSp(), GeometricBoundaryField< Type, PatchField, GeoMesh >::updateCoeffs(), and kkLOmega::y_.
Member Data Documentation
A0_
dimensionedScalar A0_ protected
Definition at line 159 of file kkLOmega.H.
Referenced by kkLOmega::read().
As_
dimensionedScalar As_ protected
Definition at line 160 of file kkLOmega.H.
Referenced by kkLOmega::read().
Av_
dimensionedScalar Av_ protected
Definition at line 161 of file kkLOmega.H.
Referenced by kkLOmega::read().
Abp_
dimensionedScalar Abp_ protected
Definition at line 162 of file kkLOmega.H.
Referenced by kkLOmega::correct(), and kkLOmega::read().
Anat_
dimensionedScalar Anat_ protected
Definition at line 163 of file kkLOmega.H.
Referenced by kkLOmega::correct(), and kkLOmega::read().
Ats_
dimensionedScalar Ats_ protected
Definition at line 164 of file kkLOmega.H.
Referenced by kkLOmega::read().
CbpCrit_
dimensionedScalar CbpCrit_ protected
Definition at line 165 of file kkLOmega.H.
Referenced by kkLOmega::read().
Cnc_
dimensionedScalar Cnc_ protected
Definition at line 166 of file kkLOmega.H.
Referenced by kkLOmega::correct(), and kkLOmega::read().
CnatCrit_
dimensionedScalar CnatCrit_ protected
Definition at line 167 of file kkLOmega.H.
Referenced by kkLOmega::read().
Cint_
dimensionedScalar Cint_ protected
Definition at line 168 of file kkLOmega.H.
Referenced by kkLOmega::read().
CtsCrit_
dimensionedScalar CtsCrit_ protected
Definition at line 169 of file kkLOmega.H.
Referenced by kkLOmega::read().
CrNat_
dimensionedScalar CrNat_ protected
Definition at line 170 of file kkLOmega.H.
Referenced by kkLOmega::correct(), and kkLOmega::read().
C11_
dimensionedScalar C11_ protected
Definition at line 171 of file kkLOmega.H.
Referenced by kkLOmega::correct(), and kkLOmega::read().
C12_
dimensionedScalar C12_ protected
Definition at line 172 of file kkLOmega.H.
Referenced by kkLOmega::correct(), and kkLOmega::read().
CR_
dimensionedScalar CR_ protected
Definition at line 173 of file kkLOmega.H.
Referenced by kkLOmega::correct(), and kkLOmega::read().
CalphaTheta_
dimensionedScalar CalphaTheta_ protected
Definition at line 174 of file kkLOmega.H.
Referenced by kkLOmega::read().
Css_
dimensionedScalar Css_ protected
Definition at line 175 of file kkLOmega.H.
Referenced by kkLOmega::read().
CtauL_
dimensionedScalar CtauL_ protected
Definition at line 176 of file kkLOmega.H.
Referenced by kkLOmega::read().
Cw1_
dimensionedScalar Cw1_ protected
Definition at line 177 of file kkLOmega.H.
Referenced by kkLOmega::correct(), and kkLOmega::read().
Cw2_
dimensionedScalar Cw2_ protected
Definition at line 178 of file kkLOmega.H.
Referenced by kkLOmega::correct(), and kkLOmega::read().
Cw3_
dimensionedScalar Cw3_ protected
Definition at line 179 of file kkLOmega.H.
Referenced by kkLOmega::correct(), and kkLOmega::read().
CwR_
dimensionedScalar CwR_ protected
Definition at line 180 of file kkLOmega.H.
Referenced by kkLOmega::correct(), and kkLOmega::read().
Clambda_
dimensionedScalar Clambda_ protected
Definition at line 181 of file kkLOmega.H.
Referenced by kkLOmega::correct(), and kkLOmega::read().
CmuStd_
dimensionedScalar CmuStd_ protected
Definition at line 182 of file kkLOmega.H.
Referenced by kkLOmega::read().
Prtheta_
dimensionedScalar Prtheta_ protected
Definition at line 183 of file kkLOmega.H.
Referenced by kkLOmega::read().
Sigmak_
dimensionedScalar Sigmak_ protected
Definition at line 184 of file kkLOmega.H.
Referenced by kkLOmega::DkEff(), and kkLOmega::read().
Sigmaw_
dimensionedScalar Sigmaw_ protected
Definition at line 185 of file kkLOmega.H.
Referenced by kkLOmega::DomegaEff(), and kkLOmega::read().
kt_
volScalarField kt_ protected
Definition at line 190 of file kkLOmega.H.
Referenced by kkLOmega::correct(), kkLOmega::k(), kkLOmega::kkLOmega(), and kkLOmega::kt().
kl_
volScalarField kl_ protected
Definition at line 191 of file kkLOmega.H.
Referenced by kkLOmega::correct(), kkLOmega::k(), kkLOmega::kkLOmega(), and kkLOmega::kl().
omega_
volScalarField omega_ protected
Definition at line 192 of file kkLOmega.H.
Referenced by kkLOmega::correct(), kkLOmega::k(), kkLOmega::kkLOmega(), and kkLOmega::omega().
epsilon_
volScalarField epsilon_ protected
Definition at line 193 of file kkLOmega.H.
Referenced by kkLOmega::correct(), kkLOmega::epsilon(), and kkLOmega::kkLOmega().
y_
const volScalarField& y_ protected
Definition at line 198 of file kkLOmega.H.
Referenced by kkLOmega::correct().
The documentation for this class was generated from the following files:
src/TurbulenceModels/incompressible/turbulentTransportModels/RAS/kkLOmega/kkLOmega.H
src/TurbulenceModels/incompressible/turbulentTransportModels/RAS/kkLOmega/kkLOmega.C