OpenFOAM: sixDoFRigidBodyMotionRestraint Class Reference
sixDoFRigidBodyMotionRestraint Class Reference abstract
Base class for defining restraints for sixDoF motions.
#include <sixDoFRigidBodyMotionRestraint.H>
Public Member Functions
TypeName ("sixDoFRigidBodyMotionRestraint")
declareRunTimeSelectionTable (autoPtr, sixDoFRigidBodyMotionRestraint, dictionary,(const word &name, const dictionary &sDoFRBMRDict),(name, sDoFRBMRDict))
sixDoFRigidBodyMotionRestraint (const word &name, const dictionary &sDoFRBMRDict)
virtual autoPtr< sixDoFRigidBodyMotionRestraint > clone () const =0
virtual ~sixDoFRigidBodyMotionRestraint ()
const word & name () const
virtual void restrain (const sixDoFRigidBodyMotion &motion, vector &restraintPosition, vector &restraintForce, vector &restraintMoment) const =0
virtual bool read (const dictionary &sDoFRBMRDict)
const dictionary & coeffDict () const
virtual void write (Ostream &) const =0
Static Public Member Functions
static autoPtr< sixDoFRigidBodyMotionRestraint > New (const word &name, const dictionary &sDoFRBMRDict)
Protected Attributes
word name_
dictionary sDoFRBMRCoeffs_
Detailed Description
Base class for defining restraints for sixDoF motions.
Source files
sixDoFRigidBodyMotionRestraint.H
sixDoFRigidBodyMotionRestraint.C
sixDoFRigidBodyMotionRestraintNew.C
Definition at line 63 of file sixDoFRigidBodyMotionRestraint.H.
Constructor & Destructor Documentation
sixDoFRigidBodyMotionRestraint()
sixDoFRigidBodyMotionRestraint (const word & name, const dictionary & sDoFRBMRDict)
Definition at line 34 of file sixDoFRigidBodyMotionRestraint.C.
References Foam::name().
~sixDoFRigidBodyMotionRestraint()
~sixDoFRigidBodyMotionRestraint () virtual
Definition at line 47 of file sixDoFRigidBodyMotionRestraint.C.
Member Function Documentation
TypeName()
TypeName ("sixDoFRigidBodyMotionRestraint")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , sixDoFRigidBodyMotionRestraint , dictionary , (const word &name, const dictionary &sDoFRBMRDict) , (name, sDoFRBMRDict))
clone()
virtual autoPtr< sixDoFRigidBodyMotionRestraint > clone () const pure virtual
Implemented in linearAxialAngularSpring, linearDamper, linearSpring, linearSpringDamper, softWall, sphericalAngularDamper, sphericalAngularSpring, and tabulatedAxialAngularSpring.
New()
Foam::autoPtr< Foam::sixDoFRigidBodyMotionRestraint > New (const word & name, const dictionary & sDoFRBMRDict) static
Definition at line 27 of file sixDoFRigidBodyMotionRestraintNew.C.
References dict, Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, and sixDoFRigidBodyMotionRestraint::name().
Referenced by sixDoFRigidBodyMotion::addRestraints().
name()
const word & name () const inline
Definition at line 125 of file sixDoFRigidBodyMotionRestraint.H.
References sixDoFRigidBodyMotionRestraint::name_.
Referenced by sixDoFRigidBodyMotionRestraint::New().
restrain()
virtual void restrain (const sixDoFRigidBodyMotion & motion, vector & restraintPosition, vector & restraintForce, vector & restraintMoment) const pure virtual
Implemented in linearAxialAngularSpring, linearDamper, linearSpring, linearSpringDamper, softWall, sphericalAngularDamper, sphericalAngularSpring, and tabulatedAxialAngularSpring.
read()
bool read (const dictionary & sDoFRBMRDict) virtual
Reimplemented in linearAxialAngularSpring, linearDamper, linearSpring, linearSpringDamper, softWall, sphericalAngularDamper, sphericalAngularSpring, and tabulatedAxialAngularSpring.
Definition at line 53 of file sixDoFRigidBodyMotionRestraint.C.
Referenced by linearAxialAngularSpring::read(), linearDamper::read(), linearSpring::read(), linearSpringDamper::read(), softWall::read(), sphericalAngularDamper::read(), sphericalAngularSpring::read(), and tabulatedAxialAngularSpring::read().
coeffDict()
const dictionary & coeffDict () const inline
Definition at line 146 of file sixDoFRigidBodyMotionRestraint.H.
References sixDoFRigidBodyMotionRestraint::sDoFRBMRCoeffs_.
write()
virtual void write (Ostream &) const pure virtual
Implemented in linearAxialAngularSpring, linearDamper, linearSpring, linearSpringDamper, softWall, sphericalAngularDamper, sphericalAngularSpring, and tabulatedAxialAngularSpring.
Member Data Documentation
name_
word name_ protected
Definition at line 71 of file sixDoFRigidBodyMotionRestraint.H.
Referenced by sixDoFRigidBodyMotionRestraint::name().
sDoFRBMRCoeffs_
dictionary sDoFRBMRCoeffs_ protected
Definition at line 74 of file sixDoFRigidBodyMotionRestraint.H.
Referenced by sixDoFRigidBodyMotionRestraint::coeffDict().
The documentation for this class was generated from the following files:
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/restraints/sixDoFRigidBodyMotionRestraint/sixDoFRigidBodyMotionRestraint.H
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/restraints/sixDoFRigidBodyMotionRestraint/sixDoFRigidBodyMotionRestraint.C
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/restraints/sixDoFRigidBodyMotionRestraint/sixDoFRigidBodyMotionRestraintNew.C