OpenFOAM: PatchInteractionFields< CloudType > Class Template Reference
PatchInteractionFields< CloudType > Class Template Reference
Lagrangian particle models » Submodels » Function objects
Creates volume fields whose boundaries are used to store patch interaction statistics.
#include <PatchInteractionFields.H>
Public Types
enum class resetMode { none , timeStep , writeTime }
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Public Member Functions
TypeName ("patchInteractionFields")
PatchInteractionFields (const dictionary &dict, CloudType &owner, const word &modelName)
PatchInteractionFields (const PatchInteractionFields< CloudType > &pii)
virtual autoPtr< CloudFunctionObject< CloudType > > clone () const
virtual ~PatchInteractionFields ()=default
virtual void preEvolve (const typename parcelType::trackingData &td)
virtual void postPatch (const parcelType &p, const polyPatch &pp, bool &keepParticle)
Public Member Functions inherited from CloudFunctionObject< CloudType >
TypeName ("cloudFunctionObject")
declareRunTimeSelectionTable (autoPtr, CloudFunctionObject, dictionary,(const dictionary &dict, CloudType &owner, const word &modelName),(dict, owner, modelName))
CloudFunctionObject (CloudType &owner)
CloudFunctionObject (const dictionary &dict, CloudType &owner, const word &objectType, const word &modelName)
CloudFunctionObject (const CloudFunctionObject< CloudType > &ppm)
virtual ~CloudFunctionObject ()=default
virtual void postEvolve (const typename parcelType::trackingData &td)
virtual void postMove (parcelType &p, const scalar dt, const point &position0, bool &keepParticle)
virtual void postFace (const parcelType &p, bool &keepParticle)
const fileName & outputDir () const
fileName writeTimeDir () const
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
virtual ~CloudSubModelBase ()=default
const CloudType & owner () const
virtual bool writeTime () const
virtual fileName localPath () const
CloudType & owner ()
virtual void info ()
virtual void write (Ostream &os) const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
subModelBase (const subModelBase &smb)
virtual ~subModelBase ()=default
const word & modelName () const
const dictionary & dict () const
const word & baseName () const
const word & modelType () const
const dictionary & coeffDict () const
const dictionary & properties () const
virtual bool defaultCoeffs (const bool printMsg) const
virtual bool active () const
virtual void cacheFields (const bool store)
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
bool getModelDict (const word &entryName, dictionary &dict) const
template<class Type >
bool getModelProperty (const word &entryName, Type &value) const
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Static Public Attributes
static const Enum< resetMode > resetModeNames_
Protected Member Functions
void reset ()
virtual void write ()
void clearOrReset (autoPtr< volScalarField > &fieldPtr, const word &fieldName, const dimensionSet &dims) const
Protected Member Functions inherited from subModelBase
bool inLine () const
Additional Inherited Members
Static Public Member Functions inherited from CloudFunctionObject< CloudType >
static autoPtr< CloudFunctionObject< CloudType > > New (const dictionary &dict, CloudType &owner, const word &objectType, const word &modelName)
Public Attributes inherited from subModelBase
bool log
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Protected Attributes inherited from subModelBase
const word modelName_
dictionary & properties_
const dictionary dict_
const word baseName_
const word modelType_
const dictionary coeffDict_
Detailed Description
template<class CloudType>
class Foam::PatchInteractionFields< CloudType >
Creates volume fields whose boundaries are used to store patch interaction statistics.
Current field output per patch face:
<cloud><model>:count - cumulative particle hits
<cloud><model>:mass - cumulative mass of hitting particles
Fields can be reset according to:
none: fields are not reset
timeStep: reset at each time step
writeTime: reset at each write time
Usage
patchInteractionFields1
{
    type            patchInteractionFields;
    resetMode       writeTime;
}
Source files
PatchInteractionFields.H
PatchInteractionFields.C
Definition at line 72 of file PatchInteractionFields.H.
Member Enumeration Documentation
resetMode
template<class CloudType > enum class resetMode strong
Enumerator
none
timeStep
writeTime
Definition at line 81 of file PatchInteractionFields.H.
Constructor & Destructor Documentation
PatchInteractionFields() [1/2]
template<class CloudType > PatchInteractionFields (const dictionary & dict, CloudType & owner, const word & modelName)
Definition at line 113 of file PatchInteractionFields.C.
References PatchInteractionFields< CloudType >::reset().
PatchInteractionFields() [2/2]
template<class CloudType > PatchInteractionFields (const PatchInteractionFields< CloudType > & pii)
Definition at line 138 of file PatchInteractionFields.C.
~PatchInteractionFields()
template<class CloudType > virtual ~PatchInteractionFields () virtual default
Member Function Documentation
reset()
template<class CloudType > void reset () protected
Definition at line 73 of file PatchInteractionFields.C.
References Foam::dimless, and Foam::dimMass.
Referenced by PatchInteractionFields< CloudType >::PatchInteractionFields().
write()
template<class CloudType > void write () protected virtual
Reimplemented from CloudFunctionObject< CloudType >.
Definition at line 81 of file PatchInteractionFields.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
clearOrReset()
template<class CloudType > void clearOrReset (autoPtr< volScalarField > & fieldPtr, const word & fieldName, const dimensionSet & dims) const protected
Definition at line 37 of file PatchInteractionFields.C.
References mesh, Foam::name(), IOobjectOption::NO_WRITE, IOobjectOption::READ_IF_PRESENT, and Foam::Zero.
TypeName()
template<class CloudType > TypeName ("patchInteractionFields")
clone()
template<class CloudType > virtual autoPtr< CloudFunctionObject< CloudType > > clone () const inline virtual
Reimplemented from CloudFunctionObject< CloudType >.
Definition at line 147 of file PatchInteractionFields.H.
preEvolve()
template<class CloudType > void preEvolve (const typename parcelType::trackingData & td) virtual
Reimplemented from CloudFunctionObject< CloudType >.
Definition at line 153 of file PatchInteractionFields.C.
postPatch()
template<class CloudType > void postPatch (const parcelType & p, const polyPatch & pp, bool & keepParticle) virtual
Reimplemented from CloudFunctionObject< CloudType >.
Definition at line 166 of file PatchInteractionFields.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), p, and pp().
Member Data Documentation
resetModeNames_
template<class CloudType > const Foam::Enum< typename Foam::PatchInteractionFields< CloudType >::resetMode > resetModeNames_ static
Definition at line 88 of file PatchInteractionFields.H.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/CloudFunctionObjects/PatchInteractionFields/PatchInteractionFields.H
src/lagrangian/intermediate/submodels/CloudFunctionObjects/PatchInteractionFields/PatchInteractionFields.C