OpenFOAM: solidBodyMotionFunction Class Reference
solidBodyMotionFunction Class Reference abstract
Base class for defining solid-body motions.
#include <solidBodyMotionFunction.H>
Public Member Functions
TypeName ("solidBodyMotionFunction")
declareRunTimeSelectionTable (autoPtr, solidBodyMotionFunction, dictionary,(const dictionary &SBMFCoeffs, const Time &runTime),(SBMFCoeffs, runTime))
solidBodyMotionFunction (const dictionary &SBMFCoeffs, const Time &runTime)
virtual autoPtr< solidBodyMotionFunction > clone () const =0
virtual ~solidBodyMotionFunction ()=default
virtual septernion transformation () const =0
virtual bool read (const dictionary &SBMFCoeffs)=0
virtual void writeData (Ostream &) const
Static Public Member Functions
static autoPtr< solidBodyMotionFunction > New (const dictionary &SBMFCoeffs, const Time &runTime)
Protected Member Functions
solidBodyMotionFunction (const solidBodyMotionFunction &)=delete
void operator= (const solidBodyMotionFunction &)=delete
Protected Attributes
dictionary SBMFCoeffs_
const Time & time_
Detailed Description
Base class for defining solid-body motions.
Source files
solidBodyMotionFunction.H
solidBodyMotionFunction.C
dynamicFvMeshNew.C
Definition at line 60 of file solidBodyMotionFunction.H.
Constructor & Destructor Documentation
solidBodyMotionFunction() [1/2]
solidBodyMotionFunction (const solidBodyMotionFunction &) protected delete
solidBodyMotionFunction() [2/2]
solidBodyMotionFunction (const dictionary & SBMFCoeffs, const Time & runTime)
Definition at line 35 of file solidBodyMotionFunction.C.
~solidBodyMotionFunction()
virtual ~solidBodyMotionFunction () virtual default
Member Function Documentation
operator=()
void operator= (const solidBodyMotionFunction &) protected delete
TypeName()
TypeName ("solidBodyMotionFunction")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , solidBodyMotionFunction , dictionary , (const dictionary &SBMFCoeffs, const Time &runTime) , (SBMFCoeffs, runTime))
clone()
virtual autoPtr< solidBodyMotionFunction > clone () const pure virtual
Implemented in axisRotationMotion, drivenLinearMotion, linearMotion, multiMotion, oscillatingRotatingMotion, rotatingMotion, SDA, and tabulated6DoFMotion.
New()
Foam::autoPtr< Foam::solidBodyMotionFunction > New (const dictionary & SBMFCoeffs, const Time & runTime) static
Definition at line 26 of file solidBodyMotionFunctionNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, Foam::Info, and runTime.
Referenced by multiSolidBodyMotionSolver::multiSolidBodyMotionSolver(), and multiMotion::read().
transformation()
virtual septernion transformation () const pure virtual
Implemented in axisRotationMotion, drivenLinearMotion, linearMotion, multiMotion, oscillatingRotatingMotion, rotatingMotion, SDA, and tabulated6DoFMotion.
read()
bool read (const dictionary & SBMFCoeffs) pure virtual
Implemented in axisRotationMotion, drivenLinearMotion, linearMotion, multiMotion, oscillatingRotatingMotion, rotatingMotion, SDA, and tabulated6DoFMotion.
Definition at line 56 of file solidBodyMotionFunction.C.
References dict, dictionary::optionalSubDict(), and Foam::type().
Referenced by axisRotationMotion::read(), drivenLinearMotion::read(), linearMotion::read(), multiMotion::read(), oscillatingRotatingMotion::read(), rotatingMotion::read(), SDA::read(), and tabulated6DoFMotion::read().
writeData()
void writeData (Ostream & os) const virtual
Definition at line 64 of file solidBodyMotionFunction.C.
References os().
Member Data Documentation
SBMFCoeffs_
dictionary SBMFCoeffs_ protected
Definition at line 66 of file solidBodyMotionFunction.H.
Referenced by axisRotationMotion::clone(), drivenLinearMotion::clone(), linearMotion::clone(), multiMotion::clone(), oscillatingRotatingMotion::clone(), rotatingMotion::clone(), SDA::clone(), and tabulated6DoFMotion::clone().
time_
const Time& time_ protected
Definition at line 68 of file solidBodyMotionFunction.H.
Referenced by axisRotationMotion::clone(), drivenLinearMotion::clone(), linearMotion::clone(), multiMotion::clone(), oscillatingRotatingMotion::clone(), rotatingMotion::clone(), SDA::clone(), and tabulated6DoFMotion::clone().
The documentation for this class was generated from the following files:
src/dynamicMesh/motionSolvers/displacement/solidBody/solidBodyMotionFunctions/solidBodyMotionFunction/solidBodyMotionFunction.H
src/dynamicMesh/motionSolvers/displacement/solidBody/solidBodyMotionFunctions/solidBodyMotionFunction/solidBodyMotionFunction.C
src/dynamicMesh/motionSolvers/displacement/solidBody/solidBodyMotionFunctions/solidBodyMotionFunction/solidBodyMotionFunctionNew.C