OpenFOAM: atmBoundaryLayerInletEpsilonFvPatchScalarField Class Reference
atmBoundaryLayerInletEpsilonFvPatchScalarField Class Reference
Turbulence models » RAS turbulence » Boundary conditions | Boundary conditions » Inlet
This boundary condition provides a log-law type ground-normal inlet boundary condition for the turbulent kinetic energy dissipation rate (i.e. epsilon) for homogeneous, two-dimensional, dry-air, equilibrium and neutral atmospheric boundary layer modelling.
#include <atmBoundaryLayerInletEpsilonFvPatchScalarField.H>
Public Member Functions
TypeName ("atmBoundaryLayerInletEpsilon")
atmBoundaryLayerInletEpsilonFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
atmBoundaryLayerInletEpsilonFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
atmBoundaryLayerInletEpsilonFvPatchScalarField (const atmBoundaryLayerInletEpsilonFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
virtual tmp< fvPatchScalarField > clone () const
atmBoundaryLayerInletEpsilonFvPatchScalarField (const atmBoundaryLayerInletEpsilonFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual void updateCoeffs ()
virtual void autoMap (const fvPatchFieldMapper &)
virtual void rmap (const fvPatchScalarField &, const labelList &)
virtual void write (Ostream &) const
Public Member Functions inherited from atmBoundaryLayer
atmBoundaryLayer (const Time &time, const polyPatch &pp)
atmBoundaryLayer (const Time &time, const polyPatch &pp, const dictionary &dict)
atmBoundaryLayer (const atmBoundaryLayer &abl, const fvPatch &patch, const fvPatchFieldMapper &mapper)
atmBoundaryLayer (const atmBoundaryLayer &)
vector flowDir () const
vector zDir () const
tmp< scalarField > Ustar (const scalarField &z0) const
void autoMap (const fvPatchFieldMapper &)
void rmap (const atmBoundaryLayer &, const labelList &)
tmp< vectorField > U (const vectorField &pCf) const
tmp< scalarField > k (const vectorField &pCf) const
tmp< scalarField > epsilon (const vectorField &pCf) const
tmp< scalarField > omega (const vectorField &pCf) const
void write (Ostream &) const
Additional Inherited Members
Protected Attributes inherited from atmBoundaryLayer
bool initABL_
Detailed Description
This boundary condition provides a log-law type ground-normal inlet boundary condition for the turbulent kinetic energy dissipation rate (i.e. epsilon) for homogeneous, two-dimensional, dry-air, equilibrium and neutral atmospheric boundary layer modelling.
The ground-normal epsilon profile expression:
where
= Ground-normal TKE dissipation rate profile [m^2/s^3]
= Friction velocity [m/s]
= von Kármán constant [-]
= Ground-normal coordinate component [m]
= Aerodynamic roughness length [m]
= Ground-normal displacement height [m]
= Curve-fitting coefficient for YGCJ profiles [-]
= Curve-fitting coefficient for YGCJ profiles [-]
Required fields:
        epsilon   | Turbulent kinetic energy dissipation rate   [m2/s3]
Usage
Example of the boundary condition specification:
inlet
{
    // Mandatory entries (unmodifiable)
    type            atmBoundaryLayerInletEpsilon;
    // Mandatory/Optional (inherited) entries (unmodifiable)
    ...
}
where the entries mean:
Property Description Type Reqd Deflt
type Type name: atmBoundaryLayerInletEpsilon word yes -
The inherited entries are elaborated in:
atmBoundaryLayer.H
inletOutletFvPatchField.H
See also
Foam::atmBoundaryLayer
Foam::atmBoundaryLayerInletKFvPatchScalarField
Foam::atmBoundaryLayerInletOmegaFvPatchScalarField
Foam::atmBoundaryLayerInletVelocityFvPatchVectorField
Source files
atmBoundaryLayerInletEpsilonFvPatchScalarField.H
atmBoundaryLayerInletEpsilonFvPatchScalarField.C
Definition at line 152 of file atmBoundaryLayerInletEpsilonFvPatchScalarField.H.
Constructor & Destructor Documentation
atmBoundaryLayerInletEpsilonFvPatchScalarField() [1/4]
atmBoundaryLayerInletEpsilonFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 36 of file atmBoundaryLayerInletEpsilonFvPatchScalarField.C.
atmBoundaryLayerInletEpsilonFvPatchScalarField() [2/4]
atmBoundaryLayerInletEpsilonFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 48 of file atmBoundaryLayerInletEpsilonFvPatchScalarField.C.
References dict, epsilon, atmBoundaryLayer::initABL_, IOobjectOption::MUST_READ, and Field< scalar >::operator=().
atmBoundaryLayerInletEpsilonFvPatchScalarField() [3/4]
atmBoundaryLayerInletEpsilonFvPatchScalarField (const atmBoundaryLayerInletEpsilonFvPatchScalarField & psf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 77 of file atmBoundaryLayerInletEpsilonFvPatchScalarField.C.
atmBoundaryLayerInletEpsilonFvPatchScalarField() [4/4]
atmBoundaryLayerInletEpsilonFvPatchScalarField (const atmBoundaryLayerInletEpsilonFvPatchScalarField & psf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 91 of file atmBoundaryLayerInletEpsilonFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("atmBoundaryLayerInletEpsilon")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 192 of file atmBoundaryLayerInletEpsilonFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 208 of file atmBoundaryLayerInletEpsilonFvPatchScalarField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 105 of file atmBoundaryLayerInletEpsilonFvPatchScalarField.C.
References epsilon.
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Definition at line 118 of file atmBoundaryLayerInletEpsilonFvPatchScalarField.C.
References atmBoundaryLayer::autoMap().
rmap()
void rmap (const fvPatchScalarField & psf, const labelList & addr) virtual
Definition at line 128 of file atmBoundaryLayerInletEpsilonFvPatchScalarField.C.
References atmBoundaryLayer::rmap().
write()
void write (Ostream & os) const virtual
Definition at line 143 of file atmBoundaryLayerInletEpsilonFvPatchScalarField.C.
References os(), atmBoundaryLayer::write(), fvPatchField< Type >::write(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/atmosphericModels/derivedFvPatchFields/atmBoundaryLayerInletEpsilon/atmBoundaryLayerInletEpsilonFvPatchScalarField.H
src/atmosphericModels/derivedFvPatchFields/atmBoundaryLayerInletEpsilon/atmBoundaryLayerInletEpsilonFvPatchScalarField.C