OpenFOAM: ParticleStressModel Class Reference
ParticleStressModel Class Reference abstract
Lagrangian particle models » Submodels » MP-PIC » Particle stress
Base class for inter-particle stress models.
#include <ParticleStressModel.H>
Public Member Functions
TypeName ("particleStressModel")
declareRunTimeSelectionTable (autoPtr, ParticleStressModel, dictionary,(const dictionary &dict),(dict))
ParticleStressModel (const dictionary &dict)
ParticleStressModel (const ParticleStressModel &sm)
virtual autoPtr< ParticleStressModel > clone () const =0
virtual ~ParticleStressModel ()
scalar alphaPacked () const
virtual tmp< Field< scalar > > tau (const Field< scalar > &alpha, const Field< scalar > &rho, const Field< scalar > &uRms) const =0
virtual tmp< Field< scalar > > dTaudTheta (const Field< scalar > &alpha, const Field< scalar > &rho, const Field< scalar > &uRms) const =0
tmp< FieldField< Field, scalar > > tau (const FieldField< Field, scalar > &alpha, const FieldField< Field, scalar > &rho, const FieldField< Field, scalar > &uRms) const
Static Public Member Functions
static autoPtr< ParticleStressModel > New (const dictionary &dict)
Protected Attributes
scalar alphaPacked_
Detailed Description
Base class for inter-particle stress models.
Source files
ParticleStressModel.H
exponential.C
Definition at line 52 of file ParticleStressModel.H.
Constructor & Destructor Documentation
ParticleStressModel() [1/2]
ParticleStressModel (const dictionary & dict)
Definition at line 35 of file ParticleStressModel.C.
ParticleStressModel() [2/2]
ParticleStressModel (const ParticleStressModel & sm)
Definition at line 44 of file ParticleStressModel.C.
~ParticleStressModel()
~ParticleStressModel () virtual
Definition at line 83 of file ParticleStressModel.C.
Member Function Documentation
TypeName()
TypeName ("particleStressModel")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , ParticleStressModel , dictionary , (const dictionary &dict) , (dict))
clone()
virtual autoPtr< ParticleStressModel > clone () const pure virtual
Implemented in exponential, HarrisCrighton, and Lun.
New()
Foam::autoPtr< Foam::ParticleStressModel > New (const dictionary & dict) static
Definition at line 55 of file ParticleStressModel.C.
References Foam::abort(), dict, Foam::endl(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), and Foam::Info.
alphaPacked()
Foam::scalar alphaPacked () const
Definition at line 89 of file ParticleStressModel.C.
tau() [1/2]
virtual tmp< Field< scalar > > tau (const Field< scalar > & alpha, const Field< scalar > & rho, const Field< scalar > & uRms) const pure virtual
Implemented in exponential, HarrisCrighton, and Lun.
dTaudTheta()
virtual tmp< Field< scalar > > dTaudTheta (const Field< scalar > & alpha, const Field< scalar > & rho, const Field< scalar > & uRms) const pure virtual
Implemented in exponential, HarrisCrighton, and Lun.
tau() [2/2]
Foam::tmp< Foam::FieldField< Foam::Field, Foam::scalar > > tau (const FieldField< Field, scalar > & alpha, const FieldField< Field, scalar > & rho, const FieldField< Field, scalar > & uRms) const
Definition at line 96 of file ParticleStressModel.C.
References alpha, forAll, rho, PtrList< T >::set(), and UList< T >::size().
Member Data Documentation
alphaPacked_
scalar alphaPacked_ protected
Definition at line 67 of file ParticleStressModel.H.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/MPPIC/ParticleStressModels/ParticleStressModel/ParticleStressModel.H
src/lagrangian/intermediate/submodels/MPPIC/ParticleStressModels/ParticleStressModel/ParticleStressModel.C