OpenFOAM: multivariateSurfaceInterpolationScheme< Type > Class Template Reference
multivariateSurfaceInterpolationScheme< Type > Class Template Reference abstract
Abstract base class for multi-variate surface interpolation schemes.
#include <multivariateSurfaceInterpolationScheme.H>
Classes
class fieldScheme
class fieldTable
Public Member Functions
virtual const word & type () const =0
declareRunTimeSelectionTable (tmp, multivariateSurfaceInterpolationScheme, Istream,(const fvMesh &mesh, const fieldTable &fields, const surfaceScalarField &faceFlux, Istream &is),(mesh, fields, faceFlux, is))
multivariateSurfaceInterpolationScheme (const fvMesh &mesh, const fieldTable &fields, const surfaceScalarField &faceFlux, Istream &schemeData)
virtual ~multivariateSurfaceInterpolationScheme ()=default
const fvMesh & mesh () const
const fieldTable & fields () const
virtual tmp< surfaceInterpolationScheme< Type > > operator() (const GeometricField< Type, fvPatchField, volMesh > &field) const =0
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Static Public Member Functions
static tmp< multivariateSurfaceInterpolationScheme< Type > > New (const fvMesh &mesh, const fieldTable &fields, const surfaceScalarField &faceFlux, Istream &schemeData)
Detailed Description
template<class Type>
class Foam::multivariateSurfaceInterpolationScheme< Type >
Abstract base class for multi-variate surface interpolation schemes.
Source files
multivariateSurfaceInterpolationScheme.H
multivariateSurfaceInterpolationScheme.C
Definition at line 48 of file multivariateSurfaceInterpolationScheme.H.
Constructor & Destructor Documentation
multivariateSurfaceInterpolationScheme()
template<class Type > multivariateSurfaceInterpolationScheme (const fvMesh & mesh, const fieldTable & fields, const surfaceScalarField & faceFlux, Istream & schemeData)
~multivariateSurfaceInterpolationScheme()
template<class Type > virtual ~multivariateSurfaceInterpolationScheme () virtual default
Member Function Documentation
type()
template<class Type > virtual const word & type () const pure virtual
declareRunTimeSelectionTable()
template<class Type > declareRunTimeSelectionTable (tmp , multivariateSurfaceInterpolationScheme< Type > , Istream , (const fvMesh &mesh, const fieldTable &fields, const surfaceScalarField &faceFlux, Istream &is) , (mesh, fields, faceFlux, is))
New()
template<class Type > Foam::tmp< Foam::multivariateSurfaceInterpolationScheme< Type > > New (const fvMesh & mesh, const fieldTable & fields, const surfaceScalarField & faceFlux, Istream & schemeData) static
Definition at line 48 of file multivariateSurfaceInterpolationScheme.C.
References Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, InfoInFunction, mesh, and PtrList< T >::PtrList().
mesh()
template<class Type > const fvMesh & mesh () const inline
Definition at line 149 of file multivariateSurfaceInterpolationScheme.H.
Referenced by multivariateScheme< Type, Scheme >::multivariateScheme(), and multivariateSelectionScheme< Type >::multivariateSelectionScheme().
fields()
template<class Type > const fieldTable & fields () const inline
Definition at line 155 of file multivariateSurfaceInterpolationScheme.H.
Referenced by multivariateScheme< Type, Scheme >::multivariateScheme(), and multivariateSelectionScheme< Type >::multivariateSelectionScheme().
operator()()
template<class Type > virtual tmp< surfaceInterpolationScheme< Type > > operator() (const GeometricField< Type, fvPatchField, volMesh > & field) const pure virtual
Implemented in multivariateIndependentScheme< Type >, multivariateScheme< Type, Scheme >, multivariateSelectionScheme< Type >, and multivariateUpwind< Type >.
The documentation for this class was generated from the following files:
src/finiteVolume/interpolation/surfaceInterpolation/multivariateSchemes/multivariateSurfaceInterpolationScheme/multivariateSurfaceInterpolationScheme.H
src/finiteVolume/interpolation/surfaceInterpolation/multivariateSchemes/multivariateSurfaceInterpolationScheme/multivariateSurfaceInterpolationScheme.C