OpenFOAM: surfZone Class Reference
surfZone Class Reference
A surface zone on a MeshedSurface.
#include <surfZone.H>
Public Member Functions
surfZone (const surfZone &)=default
surfZone & operator= (const surfZone &)=default
surfZone ()
surfZone (const word &name, const label size)
surfZone (const word &name, const label size, const label start, const label index, const word &geometricType=word::null)
surfZone (const word &name, const dictionary &dict, const label index)
surfZone (const surfZone &, const label index)
autoPtr< surfZone > clone () const
label start () const
label & start ()
label size () const
label & size ()
labelRange range () const
void write (Ostream &os) const
surfZone (Istream &is, const label index)=delete
void writeDict (Ostream &os) const
Public Member Functions inherited from surfZoneIdentifier
surfZoneIdentifier (const surfZoneIdentifier &)=default
surfZoneIdentifier & operator= (const surfZoneIdentifier &)=default
surfZoneIdentifier ()
surfZoneIdentifier (const label index)
surfZoneIdentifier (const word &name, const label index)
surfZoneIdentifier (const word &name, const label index, const word &geometricType)
surfZoneIdentifier (const word &name, const dictionary &dict, const label index)
surfZoneIdentifier (const surfZoneIdentifier &ident, const label index)
const word & name () const
word & name ()
const word & geometricType () const
word & geometricType ()
label index () const
label & index ()
void write (Ostream &os) const
Static Public Member Functions
static autoPtr< surfZone > New (Istream &is)
Static Public Member Functions inherited from surfZoneIdentifier
static word defaultName (const label n=-1)
Additional Inherited Members
Static Public Attributes inherited from surfZoneIdentifier
static constexpr const char *const emptyType = "empty"
Detailed Description
A surface zone on a MeshedSurface.
Similar in concept to a faceZone, but the face list is contiguous.
Source files
surfZone.H
surfZone.C
Definition at line 52 of file surfZone.H.
Constructor & Destructor Documentation
surfZone() [1/7]
surfZone (const surfZone &) default
surfZone() [2/7]
surfZone ()
Definition at line 27 of file surfZone.C.
surfZone() [3/7]
surfZone (const word & name, const label size)
Definition at line 35 of file surfZone.C.
surfZone() [4/7]
surfZone (const word & name, const label size, const label start, const label index, const word & geometricType = word::null)
Definition at line 43 of file surfZone.C.
surfZone() [5/7]
surfZone (const word & name, const dictionary & dict, const label index)
Definition at line 58 of file surfZone.C.
surfZone() [6/7]
surfZone (const surfZone & zone, const label index)
Definition at line 71 of file surfZone.C.
References surfZoneIdentifier::index().
surfZone() [7/7]
surfZone (Istream & is, const label index) delete
Member Function Documentation
operator=()
surfZone & operator= (const surfZone &) default
clone()
autoPtr< surfZone > clone () const inline
Definition at line 106 of file surfZone.H.
References NotImplemented.
New()
static autoPtr< surfZone > New (Istream & is) inline static
Definition at line 112 of file surfZone.H.
References dict, surfZoneIdentifier::name(), and autoPtr< T >::New().
start() [1/2]
label start () const inline
Definition at line 124 of file surfZone.H.
Referenced by Foam::operator==().
start() [2/2]
label & start () inline
Definition at line 130 of file surfZone.H.
size() [1/2]
label size () const inline
Definition at line 136 of file surfZone.H.
Referenced by Foam::operator==().
size() [2/2]
label & size () inline
Definition at line 142 of file surfZone.H.
range()
labelRange range () const inline
Definition at line 148 of file surfZone.H.
write()
void write (Ostream & os) const
Definition at line 81 of file surfZone.C.
References Ostream::beginBlock(), Ostream::endBlock(), Foam::name(), os(), surfZoneIdentifier::write(), and Ostream::writeEntry().
writeDict()
void writeDict (Ostream & os) const inline
Definition at line 167 of file surfZone.H.
References os(), and write().
The documentation for this class was generated from the following files:
src/surfMesh/surfZone/surfZone.H
src/surfMesh/surfZone/surfZone.C