OpenFOAM: PairCollisionRecord< Type > Class Template Reference
PairCollisionRecord< Type > Class Template Reference
Record of a collision between the particle holding the record and the particle with the stored id.
#include <PairCollisionRecord.H>
Public Member Functions
PairCollisionRecord ()
PairCollisionRecord (bool accessed, label origProcOfOther, label origIdOfOther, const Type &data=Type(Zero))
PairCollisionRecord (Istream &)
PairCollisionRecord (const PairCollisionRecord &)
~PairCollisionRecord ()
label origProcOfOther () const
label origIdOfOther () const
const Type & collisionData () const
Type & collisionData ()
bool match (label queryOrigProcOfOther, label queryOrigIdOfOther) const
bool accessed () const
void setAccessed ()
void setUnaccessed ()
void operator= (const PairCollisionRecord &)
Friends
bool operator== (const PairCollisionRecord< Type > &, const PairCollisionRecord< Type > &)
bool operator!= (const PairCollisionRecord< Type > &, const PairCollisionRecord< Type > &)
Istream & operator>> (Istream &, PairCollisionRecord< Type > &)
Ostream & operator<< (Ostream &, const PairCollisionRecord< Type > &)
Detailed Description
template<class Type>
class Foam::PairCollisionRecord< Type >
Record of a collision between the particle holding the record and the particle with the stored id.
The access status of the record is to be coded in the origProcOfOther data member. The actual processor is offset by +1. A negative value means that the record has not been accessed, positive means that it has.
Source files
PairCollisionRecord.H
PairCollisionRecordI.H
PairCollisionRecord.C
PairCollisionRecordIO.C
Definition at line 82 of file PairCollisionRecord.H.
Constructor & Destructor Documentation
PairCollisionRecord() [1/4]
template<class Type > PairCollisionRecord ()
Definition at line 27 of file PairCollisionRecord.C.
PairCollisionRecord() [2/4]
template<class Type > PairCollisionRecord (bool accessed, label origProcOfOther, label origIdOfOther, const Type & data = Type(Zero))
Definition at line 36 of file PairCollisionRecord.C.
References PairCollisionRecord< Type >::accessed(), and PairCollisionRecord< Type >::setUnaccessed().
PairCollisionRecord() [3/4]
template<class Type > PairCollisionRecord (Istream & is)
Definition at line 27 of file PairCollisionRecordIO.C.
References FUNCTION_NAME, and Foam::readLabel().
PairCollisionRecord() [4/4]
template<class Type > PairCollisionRecord (const PairCollisionRecord< Type > &)
~PairCollisionRecord()
template<class Type > ~PairCollisionRecord ()
Definition at line 72 of file PairCollisionRecord.C.
Member Function Documentation
origProcOfOther()
template<class Type > Foam::label origProcOfOther () const inline
Definition at line 39 of file PairCollisionRecordI.H.
References Foam::mag().
origIdOfOther()
template<class Type > Foam::label origIdOfOther () const inline
Definition at line 46 of file PairCollisionRecordI.H.
collisionData() [1/2]
template<class Type > const Type & collisionData () const inline
Definition at line 54 of file PairCollisionRecordI.H.
collisionData() [2/2]
template<class Type > Type & collisionData () inline
Definition at line 61 of file PairCollisionRecordI.H.
match()
template<class Type > bool match (label queryOrigProcOfOther, label queryOrigIdOfOther) const inline
Definition at line 24 of file PairCollisionRecordI.H.
accessed()
template<class Type > bool accessed () const inline
Definition at line 68 of file PairCollisionRecordI.H.
References Foam::pos0().
Referenced by PairCollisionRecord< Type >::PairCollisionRecord().
setAccessed()
template<class Type > void setAccessed () inline
Definition at line 75 of file PairCollisionRecordI.H.
setUnaccessed()
template<class Type > void setUnaccessed () inline
Definition at line 82 of file PairCollisionRecordI.H.
Referenced by PairCollisionRecord< Type >::PairCollisionRecord().
operator=()
template<class Type > void operator= (const PairCollisionRecord< Type > &)
Definition at line 79 of file PairCollisionRecord.C.
Friends And Related Symbol Documentation
operator==
template<class Type > bool operator== (const PairCollisionRecord< Type > & , const PairCollisionRecord< Type > &) friend
operator!=
template<class Type > bool operator!= (const PairCollisionRecord< Type > & , const PairCollisionRecord< Type > &) friend
operator>>
template<class Type > Istream & operator>> (Istream & , PairCollisionRecord< Type > &) friend
operator<<
template<class Type > Ostream & operator<< (Ostream & , const PairCollisionRecord< Type > &) friend
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/parcels/Templates/CollidingParcel/CollisionRecordList/PairCollisionRecord/PairCollisionRecord.H
src/lagrangian/intermediate/parcels/Templates/CollidingParcel/CollisionRecordList/PairCollisionRecord/PairCollisionRecord.C
src/lagrangian/intermediate/parcels/Templates/CollidingParcel/CollisionRecordList/PairCollisionRecord/PairCollisionRecordI.H
src/lagrangian/intermediate/parcels/Templates/CollidingParcel/CollisionRecordList/PairCollisionRecord/PairCollisionRecordIO.C