OpenFOAM: H2O Class Reference
H2O Class Reference
water
#include <H2O.H>
Public Member Functions
TypeName ("H2O")
H2O ()
H2O (const liquidProperties &l, const NSRDSfunc5 &density, const NSRDSfunc1 &vapourPressure, const NSRDSfunc6 &heatOfVapourisation, const NSRDSfunc0 &heatCapacity, const NSRDSfunc0 &enthalpy, const NSRDSfunc7 &idealGasHeatCapacity, const NSRDSfunc4 &secondVirialCoeff, const NSRDSfunc1 &dynamicViscosity, const NSRDSfunc2 &vapourDynamicViscosity, const NSRDSfunc0 &thermalConductivity, const NSRDSfunc2 &vapourThermalConductivity, const NSRDSfunc6 &surfaceTension, const APIdiffCoefFunc &vapourDiffussivity)
H2O (const dictionary &dict)
virtual autoPtr< liquidProperties > clone () const
scalar rho (scalar p, scalar T) const
scalar pv (scalar p, scalar T) const
scalar hl (scalar p, scalar T) const
scalar Cp (scalar p, scalar T) const
scalar h (scalar p, scalar T) const
scalar Cpg (scalar p, scalar T) const
scalar B (scalar p, scalar T) const
scalar mu (scalar p, scalar T) const
scalar mug (scalar p, scalar T) const
scalar kappa (scalar p, scalar T) const
scalar kappag (scalar p, scalar T) const
scalar sigma (scalar p, scalar T) const
scalar D (scalar p, scalar T) const
scalar D (scalar p, scalar T, scalar Wb) const
void writeData (Ostream &os) const
Public Member Functions inherited from liquidProperties
TypeName ("liquid")
declareRunTimeSelectionTable (autoPtr, liquidProperties,,(),())
declareRunTimeSelectionTable (autoPtr, liquidProperties, dictionary,(const dictionary &dict),(dict))
liquidProperties (scalar W, scalar Tc, scalar Pc, scalar Vc, scalar Zc, scalar Tt, scalar Pt, scalar Tb, scalar dipm, scalar omega, scalar delta)
liquidProperties (const dictionary &dict)
virtual ~liquidProperties ()=default
scalar Y () const
scalar Tc () const
scalar Pc () const
scalar Vc () const
scalar Zc () const
scalar Tt () const
scalar Pt () const
scalar Tb () const
scalar dipm () const
scalar omega () const
scalar delta () const
scalar limit (const scalar T) const
scalar psi (scalar p, scalar T) const
scalar CpMCv (scalar p, scalar T) const
scalar Ha (const scalar p, const scalar T) const
scalar Hs (const scalar p, const scalar T) const
scalar Hc () const
scalar S (const scalar p, const scalar T) const
scalar alphah (const scalar p, const scalar T) const
virtual scalar pvInvert (scalar p) const
void readIfPresent (const dictionary &dict)
template<class Func >
void readIfPresent (Func &f, const word &name, const dictionary &dict)
template<class Liquid >
void readIfPresent (Liquid &l, const dictionary &dict)
template<class Liquid >
void writeData (const Liquid &l, Ostream &os) const
Public Member Functions inherited from thermophysicalProperties
TypeName ("thermophysicalProperties")
declareRunTimeSelectionTable (autoPtr, thermophysicalProperties,,(),())
declareRunTimeSelectionTable (autoPtr, thermophysicalProperties, dictionary,(const dictionary &dict),(dict))
thermophysicalProperties (scalar W)
thermophysicalProperties (const dictionary &dict)
virtual ~thermophysicalProperties ()=default
scalar W () const
scalar limit (const scalar T) const
void readIfPresent (const dictionary &dict)
Friends
class liquidProperties
Ostream & operator<< (Ostream &os, const H2O &l)
Additional Inherited Members
Static Public Member Functions inherited from liquidProperties
static autoPtr< liquidProperties > New (const word &name)
static autoPtr< liquidProperties > New (const dictionary &dict)
Static Public Member Functions inherited from thermophysicalProperties
static autoPtr< thermophysicalProperties > New (const word &name)
static autoPtr< thermophysicalProperties > New (const dictionary &dict)
Static Public Attributes inherited from liquidProperties
static const bool incompressible = true
static const bool isochoric = false
Detailed Description
water
Source files
H2O.H
H2O.C
Definition at line 55 of file H2O.H.
Constructor & Destructor Documentation
H2O() [1/3]
H2O ()
Definition at line 35 of file H2O.C.
H2O() [2/3]
H2O (const liquidProperties & l, const NSRDSfunc5 & density, const NSRDSfunc1 & vapourPressure, const NSRDSfunc6 & heatOfVapourisation, const NSRDSfunc0 & heatCapacity, const NSRDSfunc0 & enthalpy, const NSRDSfunc7 & idealGasHeatCapacity, const NSRDSfunc4 & secondVirialCoeff, const NSRDSfunc1 & dynamicViscosity, const NSRDSfunc2 & vapourDynamicViscosity, const NSRDSfunc0 & thermalConductivity, const NSRDSfunc2 & vapourThermalConductivity, const NSRDSfunc6 & surfaceTension, const APIdiffCoefFunc & vapourDiffussivity)
Definition at line 97 of file H2O.C.
H2O() [3/3]
H2O (const dictionary & dict)
Definition at line 132 of file H2O.C.
References dict, and liquidProperties::readIfPresent().
Member Function Documentation
TypeName()
TypeName ("H2O")
clone()
virtual autoPtr< liquidProperties > clone () const inline virtual
Implements liquidProperties.
Definition at line 112 of file H2O.H.
rho()
Foam::scalar rho (scalar p, scalar T) const inline virtual
Implements thermophysicalProperties.
Definition at line 21 of file H2OI.H.
References NSRDSfunc5::f(), p, and T.
pv()
Foam::scalar pv (scalar p, scalar T) const inline virtual
Implements liquidProperties.
Definition at line 27 of file H2OI.H.
References p, and T.
hl()
Foam::scalar hl (scalar p, scalar T) const inline virtual
Implements liquidProperties.
Definition at line 33 of file H2OI.H.
References p, and T.
Cp()
Foam::scalar Cp (scalar p, scalar T) const inline virtual
Implements thermophysicalProperties.
Definition at line 39 of file H2OI.H.
References p, and T.
h()
Foam::scalar h (scalar p, scalar T) const inline virtual
Implements liquidProperties.
Definition at line 45 of file H2OI.H.
References p, and T.
Cpg()
Foam::scalar Cpg (scalar p, scalar T) const inline virtual
Implements liquidProperties.
Definition at line 51 of file H2OI.H.
References p, and T.
B()
Foam::scalar B (scalar p, scalar T) const inline
Definition at line 57 of file H2OI.H.
References p, and T.
mu()
Foam::scalar mu (scalar p, scalar T) const inline virtual
Implements liquidProperties.
Definition at line 63 of file H2OI.H.
References p, and T.
mug()
Foam::scalar mug (scalar p, scalar T) const inline virtual
Implements liquidProperties.
Definition at line 69 of file H2OI.H.
References p, and T.
kappa()
Foam::scalar kappa (scalar p, scalar T) const inline virtual
Implements liquidProperties.
Definition at line 75 of file H2OI.H.
References p, and T.
kappag()
Foam::scalar kappag (scalar p, scalar T) const inline virtual
Implements liquidProperties.
Definition at line 81 of file H2OI.H.
References p, and T.
sigma()
Foam::scalar sigma (scalar p, scalar T) const inline virtual
Implements liquidProperties.
Definition at line 87 of file H2OI.H.
References p, and T.
D() [1/2]
Foam::scalar D (scalar p, scalar T) const inline virtual
Implements liquidProperties.
Definition at line 93 of file H2OI.H.
References p, and T.
D() [2/2]
Foam::scalar D (scalar p, scalar T, scalar Wb) const inline virtual
Implements liquidProperties.
Definition at line 99 of file H2OI.H.
References p, and T.
writeData()
void writeData (Ostream & os) const virtual
Implements liquidProperties.
Definition at line 142 of file H2O.C.
References os(), and liquidProperties::writeData().
Referenced by Foam::operator<<().
Friends And Related Symbol Documentation
liquidProperties
friend class liquidProperties friend
Definition at line 78 of file H2O.H.
operator<<
Ostream & operator<< (Ostream & os, const H2O & l) friend
The documentation for this class was generated from the following files:
src/thermophysicalModels/thermophysicalProperties/liquidProperties/H2O/H2O.H
src/thermophysicalModels/thermophysicalProperties/liquidProperties/H2O/H2O.C
src/thermophysicalModels/thermophysicalProperties/liquidProperties/H2O/H2OI.H