OpenFOAM: cellFeatures Class Reference
cellFeatures Class Reference
Cell analysis class.
#include <cellFeatures.H>
Public Member Functions
cellFeatures (const primitiveMesh &, const scalar minCos, const label celli)
~cellFeatures ()
const labelHashSet & featureEdge () const
const faceList & faces () const
const List< DynamicList< label > > & faceMap () const
bool isFeatureEdge (const label edgeI) const
bool isFeaturePoint (const label edge0, const label edge1) const
bool isFeatureVertex (const label facei, const label vertI) const
Detailed Description
Cell analysis class.
Constructs feature edges and feature points, which are edges/points with and angle > given specification. Can be asked for 'superFaces' which can be used to see if a cell is a 'splitHex'.
Source files
cellFeatures.H
cellFeatures.C
Definition at line 59 of file cellFeatures.H.
Constructor & Destructor Documentation
cellFeatures()
cellFeatures (const primitiveMesh & mesh, const scalar minCos, const label celli)
Definition at line 361 of file cellFeatures.C.
References forAll, and HashSet< Key, Hash >::insert().
~cellFeatures()
~cellFeatures ()
Definition at line 392 of file cellFeatures.C.
References Foam::deleteDemandDrivenData().
Member Function Documentation
featureEdge()
const labelHashSet & featureEdge () const inline
Definition at line 132 of file cellFeatures.H.
Referenced by cellFeatures::isFeatureEdge().
faces()
const faceList & faces () const inline
Definition at line 137 of file cellFeatures.H.
faceMap()
const List< DynamicList< label > > & faceMap () const inline
Definition at line 147 of file cellFeatures.H.
isFeatureEdge()
bool isFeatureEdge (const label edgeI) const inline
Definition at line 161 of file cellFeatures.H.
References cellFeatures::featureEdge().
isFeaturePoint()
bool isFeaturePoint (const label edge0, const label edge1) const
Definition at line 400 of file cellFeatures.C.
References Foam::abort(), edge::end(), UPtrList< T >::end(), Foam::FatalError, FatalErrorInFunction, edge::start(), and edge::unitVec().
isFeatureVertex()
bool isFeatureVertex (const label facei, const label vertI) const
Definition at line 463 of file cellFeatures.C.
References Foam::abort(), Foam::meshTools::edgeOnFace(), Foam::FatalError, FatalErrorInFunction, and forAll.
The documentation for this class was generated from the following files:
src/meshTools/cellFeatures/cellFeatures.H
src/meshTools/cellFeatures/cellFeatures.C