OpenFOAM: convectionScheme< Type > Class Template Reference
convectionScheme< Type > Class Template Reference abstract
Numerics » Finite volume numerical schemes » Convection schemes
Abstract base class for convection schemes.
#include <convectionScheme.H>
Public Member Functions
virtual const word & type () const =0
declareRunTimeSelectionTable (tmp, convectionScheme, Istream,(const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
declareRunTimeSelectionTable (tmp, convectionScheme, Multivariate,(const fvMesh &mesh, const typename multivariateSurfaceInterpolationScheme< Type >::fieldTable &fields, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, fields, faceFlux, schemeData))
convectionScheme (const convectionScheme &)
convectionScheme (const fvMesh &mesh, const surfaceScalarField &)
virtual ~convectionScheme ()
const fvMesh & mesh () const
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const surfaceScalarField &, const GeometricField< Type, fvPatchField, volMesh > &) const =0
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const surfaceScalarField &, const GeometricField< Type, fvPatchField, volMesh > &) const =0
virtual tmp< fvMatrix< Type > > fvmDiv (const surfaceScalarField &, const GeometricField< Type, fvPatchField, volMesh > &) const =0
virtual tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDiv (const surfaceScalarField &, const GeometricField< Type, fvPatchField, volMesh > &) const =0
void operator= (const convectionScheme< Type > &)
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Static Public Member Functions
static tmp< convectionScheme< Type > > New (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData)
static tmp< convectionScheme< Type > > New (const fvMesh &mesh, const typename multivariateSurfaceInterpolationScheme< Type >::fieldTable &fields, const surfaceScalarField &faceFlux, Istream &schemeData)
Detailed Description
template<class Type>
class Foam::fv::convectionScheme< Type >
Abstract base class for convection schemes.
Source files
convectionScheme.H
convectionScheme.C
Definition at line 65 of file convectionScheme.H.
Constructor & Destructor Documentation
convectionScheme() [1/2]
template<class Type > convectionScheme (const convectionScheme< Type > & cs)
Definition at line 44 of file convectionScheme.C.
convectionScheme() [2/2]
template<class Type > convectionScheme (const fvMesh & mesh, const surfaceScalarField &) inline
Definition at line 117 of file convectionScheme.H.
~convectionScheme()
template<class Type > ~convectionScheme () virtual
Definition at line 145 of file convectionScheme.C.
Member Function Documentation
type()
template<class Type > virtual const word & type () const pure virtual
declareRunTimeSelectionTable() [1/2]
template<class Type > declareRunTimeSelectionTable (tmp , convectionScheme< Type > , Istream , (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData) , (mesh, faceFlux, schemeData))
declareRunTimeSelectionTable() [2/2]
template<class Type > declareRunTimeSelectionTable (tmp , convectionScheme< Type > , Multivariate , (const fvMesh &mesh, const typename multivariateSurfaceInterpolationScheme< Type >::fieldTable &fields, const surfaceScalarField &faceFlux, Istream &schemeData) , (mesh, fields, faceFlux, schemeData))
New() [1/2]
template<class Type > tmp< convectionScheme< Type > > New (const fvMesh & mesh, const surfaceScalarField & faceFlux, Istream & schemeData) static
Definition at line 54 of file convectionScheme.C.
References Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, FatalIOErrorInLookup, InfoInFunction, and mesh.
Referenced by Foam::fvc::div(), Foam::fvm::div(), and Foam::fvc::flux().
New() [2/2]
template<class Type > tmp< convectionScheme< Type > > New (const fvMesh & mesh, const typename multivariateSurfaceInterpolationScheme< Type >::fieldTable & fields, const surfaceScalarField & faceFlux, Istream & schemeData) static
Definition at line 100 of file convectionScheme.C.
References Foam::endl(), and InfoInFunction.
mesh()
template<class Type > const fvMesh & mesh () const inline
Definition at line 157 of file convectionScheme.H.
interpolate()
template<class Type > virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const surfaceScalarField & , const GeometricField< Type, fvPatchField, volMesh > &) const pure virtual
Implemented in boundedConvectionScheme< Type >, gaussConvectionScheme< Type >, and multivariateGaussConvectionScheme< Type >.
flux()
template<class Type > virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const surfaceScalarField & , const GeometricField< Type, fvPatchField, volMesh > &) const pure virtual
Implemented in boundedConvectionScheme< Type >, gaussConvectionScheme< Type >, and multivariateGaussConvectionScheme< Type >.
fvmDiv()
template<class Type > virtual tmp< fvMatrix< Type > > fvmDiv (const surfaceScalarField & , const GeometricField< Type, fvPatchField, volMesh > &) const pure virtual
Implemented in boundedConvectionScheme< Type >, gaussConvectionScheme< Type >, and multivariateGaussConvectionScheme< Type >.
fvcDiv()
template<class Type > virtual tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDiv (const surfaceScalarField & , const GeometricField< Type, fvPatchField, volMesh > &) const pure virtual
Implemented in boundedConvectionScheme< Type >, gaussConvectionScheme< Type >, and multivariateGaussConvectionScheme< Type >.
operator=()
template<class Type > void operator= (const convectionScheme< Type > & cs)
Definition at line 152 of file convectionScheme.C.
The documentation for this class was generated from the following files:
src/finiteVolume/finiteVolume/convectionSchemes/convectionScheme/convectionScheme.H
src/finiteVolume/finiteVolume/convectionSchemes/convectionScheme/convectionScheme.C