OpenFOAM: splineInterpolationWeights Class Reference
splineInterpolationWeights Class Reference
Catmull-Rom spline interpolation.
#include <splineInterpolationWeights.H>
Public Member Functions
TypeName ("spline")
splineInterpolationWeights (const scalarField &samples, const bool checkEqualDistance=true)
virtual ~splineInterpolationWeights ()=default
virtual bool valueWeights (const scalar t, labelList &indices, scalarField &weights) const
virtual bool integrationWeights (const scalar t1, const scalar t2, labelList &indices, scalarField &weights) const
Public Member Functions inherited from interpolationWeights
TypeName ("interpolationWeights")
declareRunTimeSelectionTable (autoPtr, interpolationWeights, word,(const scalarField &samples),(samples))
interpolationWeights (const scalarField &samples)
virtual ~interpolationWeights ()=default
template<class ListType1 , class ListType2 >
Foam::outerProduct< typenameListType1::value_type, typenameListType2::value_type >::type weightedSum (const ListType1 &f1, const ListType2 &f2)
Additional Inherited Members
Static Public Member Functions inherited from interpolationWeights
static autoPtr< interpolationWeights > New (const word &type, const scalarField &samples)
template<class ListType1 , class ListType2 >
static outerProduct< typenameListType1::value_type, typenameListType2::value_type >::type weightedSum (const ListType1 &f1, const ListType2 &f2)
Protected Member Functions inherited from interpolationWeights
interpolationWeights (const interpolationWeights &)=delete
void operator= (const interpolationWeights &)=delete
Protected Attributes inherited from interpolationWeights
const scalarField & samples_
Detailed Description
Catmull-Rom spline interpolation.
Source files
splineInterpolationWeights.H
splineInterpolationWeights.C
Definition at line 47 of file splineInterpolationWeights.H.
Constructor & Destructor Documentation
splineInterpolationWeights()
splineInterpolationWeights (const scalarField & samples, const bool checkEqualDistance = true) explicit
Definition at line 43 of file splineInterpolationWeights.C.
References Foam::endl(), Foam::mag(), Foam::nl, samples(), interpolationWeights::samples_, UPtrList< T >::size(), and WarningInFunction.
~splineInterpolationWeights()
virtual ~splineInterpolationWeights () virtual default
Member Function Documentation
TypeName()
TypeName ("spline")
valueWeights()
bool valueWeights (const scalar t, labelList & indices, scalarField & weights) const virtual
Implements interpolationWeights.
Definition at line 75 of file splineInterpolationWeights.C.
References Foam::findLower(), mu, List< T >::setSize(), UPtrList< T >::size(), UList< T >::size(), linearInterpolationWeights::valueWeights(), w0, w1, w2, and w3.
integrationWeights()
virtual bool integrationWeights (const scalar t1, const scalar t2, labelList & indices, scalarField & weights) const inline virtual
Implements interpolationWeights.
Definition at line 92 of file splineInterpolationWeights.H.
References NotImplemented.
The documentation for this class was generated from the following files:
src/OpenFOAM/interpolations/interpolationWeights/splineInterpolationWeights/splineInterpolationWeights.H
src/OpenFOAM/interpolations/interpolationWeights/splineInterpolationWeights/splineInterpolationWeights.C