OpenFOAM: SSG< BasicTurbulenceModel > Class Template Reference
SSG< BasicTurbulenceModel > Class Template Reference
Turbulence models » RAS turbulence
Speziale, Sarkar and Gatski Reynolds-stress turbulence model for incompressible and compressible flows.
#include <SSG.H>
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from ReynoldsStress< RASModel< BasicTurbulenceModel > >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from RASModel< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("SSG")
SSG (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
virtual ~SSG ()=default
virtual bool read ()
virtual tmp< volScalarField > k () const
virtual tmp< volScalarField > epsilon () const
tmp< volSymmTensorField > DREff () const
tmp< volSymmTensorField > DepsilonEff () const
virtual void correct ()
Public Member Functions inherited from ReynoldsStress< RASModel< BasicTurbulenceModel > >
Foam::tmp< Foam::fvVectorMatrix > DivDevRhoReff (const RhoFieldType &rho, volVectorField &U) const
ReynoldsStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~ReynoldsStress ()=default
virtual tmp< volScalarField > nut () const
virtual tmp< scalarField > nut (const label patchi) const
virtual tmp< volSymmTensorField > R () const
virtual tmp< volSymmTensorField > devRhoReff () const
virtual tmp< volSymmTensorField > devRhoReff (const volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
virtual void validate ()
Public Member Functions inherited from RASModel< BasicTurbulenceModel >
TypeName ("RAS")
declareRunTimeSelectionTable (autoPtr, RASModel, dictionary,(const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName),(alpha, rho, U, alphaRhoPhi, phi, transport, propertiesName))
RASModel (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~RASModel ()=default
const dimensionedScalar & kMin () const noexcept
const dimensionedScalar & epsilonMin () const noexcept
const dimensionedScalar & omegaMin () const noexcept
dimensionedScalar & kMin () noexcept
dimensionedScalar & epsilonMin () noexcept
dimensionedScalar & omegaMin () noexcept
virtual const dictionary & coeffDict () const
virtual tmp< volScalarField > nuEff () const
virtual tmp< scalarField > nuEff (const label patchi) const
virtual tmp< volScalarField > omega () const
Public Member Functions inherited from RASModelBase
ClassName ("RASModelBase")
RASModelBase () noexcept=default
virtual ~RASModelBase ()=default
Protected Member Functions
virtual void correctNut ()
Protected Member Functions inherited from ReynoldsStress< RASModel< BasicTurbulenceModel > >
void boundNormalStress (volSymmTensorField &R) const
void correctWallShearStress (volSymmTensorField &R) const
void checkRealizabilityConditions (const volSymmTensorField &R) const
tmp< fvVectorMatrix > DivDevRhoReff (const RhoFieldType &rho, volVectorField &U) const
Protected Member Functions inherited from RASModel< BasicTurbulenceModel >
virtual void printCoeffs (const word &type)
RASModel (const RASModel &)=delete
void operator= (const RASModel &)=delete
Protected Attributes
dimensionedScalar Cmu_
dimensionedScalar C1_
dimensionedScalar C1s_
dimensionedScalar C2_
dimensionedScalar C3_
dimensionedScalar C3s_
dimensionedScalar C4_
dimensionedScalar C5_
dimensionedScalar Ceps1_
dimensionedScalar Ceps2_
dimensionedScalar Cs_
dimensionedScalar Ceps_
volScalarField k_
volScalarField epsilon_
Protected Attributes inherited from ReynoldsStress< RASModel< BasicTurbulenceModel > >
dimensionedScalar couplingFactor_
volSymmTensorField R_
volScalarField nut_
Protected Attributes inherited from RASModel< BasicTurbulenceModel >
dictionary RASDict_
Switch turbulence_
Switch printCoeffs_
dictionary coeffDict_
dimensionedScalar kMin_
dimensionedScalar epsilonMin_
dimensionedScalar omegaMin_
Additional Inherited Members
Static Public Member Functions inherited from RASModel< BasicTurbulenceModel >
static autoPtr< RASModel > New (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Detailed Description
template<class BasicTurbulenceModel>
class Foam::RASModels::SSG< BasicTurbulenceModel >
Speziale, Sarkar and Gatski Reynolds-stress turbulence model for incompressible and compressible flows.
Reference:
    Speziale, C. G., Sarkar, S., & Gatski, T. B. (1991).
    Modelling the pressure-strain correlation of turbulence:
    an invariant dynamical systems approach.
    Journal of Fluid Mechanics, 227, 245-272.
Including the generalized gradient diffusion model of Daly and Harlow:
    Daly, B. J., & Harlow, F. H. (1970).
    Transport equations in turbulence.
    Physics of Fluids (1958-1988), 13(11), 2634-2649.
The default model coefficients are:
    SSGCoeffs
    {
        Cmu             0.09;
        C1              3.4;
        C1s             1.8;
        C2              4.2;
        C3              0.8;
        C3s             1.3;
        C4              1.25;
        C5              0.4;
        Ceps1           1.44;
        Ceps2           1.92;
        Cs              0.25;
        Ceps            0.15;
        couplingFactor  0.0;
    }
Source files
SSG.H
SSG.C
Definition at line 94 of file SSG.H.
Member Typedef Documentation
alphaField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 142 of file SSG.H.
rhoField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 143 of file SSG.H.
transportModel
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 144 of file SSG.H.
Constructor & Destructor Documentation
SSG()
template<class BasicTurbulenceModel > SSG (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Definition at line 49 of file SSG.C.
References Foam::bound(), ReynoldsStress< RASModel< BasicTurbulenceModel > >::boundNormalStress(), SSG< BasicTurbulenceModel >::epsilon_, RASModel< BasicTurbulenceModel >::epsilonMin_, SSG< BasicTurbulenceModel >::k_, RASModel< BasicTurbulenceModel >::printCoeffs(), ReynoldsStress< RASModel< BasicTurbulenceModel > >::R_, Foam::tr(), and Foam::type().
~SSG()
template<class BasicTurbulenceModel > virtual ~SSG () virtual default
Member Function Documentation
correctNut()
template<class BasicTurbulenceModel > void correctNut () protected virtual
Implements ReynoldsStress< RASModel< BasicTurbulenceModel > >.
Definition at line 36 of file SSG.C.
References options::New(), and Foam::sqr().
TypeName()
template<class BasicTurbulenceModel > TypeName ("SSG< BasicTurbulenceModel >")
read()
template<class BasicTurbulenceModel > bool read () virtual
Implements ReynoldsStress< RASModel< BasicTurbulenceModel > >.
Definition at line 222 of file SSG.C.
References Foam::read().
k()
template<class BasicTurbulenceModel > virtual tmp< volScalarField > k () const inline virtual
Reimplemented from ReynoldsStress< RASModel< BasicTurbulenceModel > >.
Definition at line 177 of file SSG.H.
References SSG< BasicTurbulenceModel >::k_.
epsilon()
template<class BasicTurbulenceModel > virtual tmp< volScalarField > epsilon () const inline virtual
Reimplemented from RASModel< BasicTurbulenceModel >.
Definition at line 183 of file SSG.H.
References SSG< BasicTurbulenceModel >::epsilon_.
DREff()
template<class BasicTurbulenceModel > tmp< volSymmTensorField > DREff () const
Definition at line 248 of file SSG.C.
References Foam::I, and nu.
DepsilonEff()
template<class BasicTurbulenceModel > tmp< volSymmTensorField > DepsilonEff () const
Definition at line 262 of file SSG.C.
References Foam::I, and nu.
correct()
template<class BasicTurbulenceModel > void correct () virtual
Implements ReynoldsStress< RASModel< BasicTurbulenceModel > >.
Definition at line 276 of file SSG.C.
References alpha, b, Foam::bound(), correct(), Foam::fvm::ddt(), Foam::dev(), Foam::devTwoSymm(), Foam::fvm::div(), forAll, fvOptions, Foam::fvc::grad(), Foam::I, Foam::innerSqr(), Foam::fvm::laplacian(), Foam::mag(), Foam::min(), options::New(), patches, R, rho, Foam::skew(), solve(), Foam::fvm::Sp(), Foam::symm(), Foam::tr(), Foam::twoSymm(), and U.
Member Data Documentation
Cmu_
template<class BasicTurbulenceModel > dimensionedScalar Cmu_ protected
Definition at line 113 of file SSG.H.
C1_
template<class BasicTurbulenceModel > dimensionedScalar C1_ protected
Definition at line 115 of file SSG.H.
C1s_
template<class BasicTurbulenceModel > dimensionedScalar C1s_ protected
Definition at line 116 of file SSG.H.
C2_
template<class BasicTurbulenceModel > dimensionedScalar C2_ protected
Definition at line 117 of file SSG.H.
C3_
template<class BasicTurbulenceModel > dimensionedScalar C3_ protected
Definition at line 118 of file SSG.H.
C3s_
template<class BasicTurbulenceModel > dimensionedScalar C3s_ protected
Definition at line 119 of file SSG.H.
C4_
template<class BasicTurbulenceModel > dimensionedScalar C4_ protected
Definition at line 120 of file SSG.H.
C5_
template<class BasicTurbulenceModel > dimensionedScalar C5_ protected
Definition at line 121 of file SSG.H.
Ceps1_
template<class BasicTurbulenceModel > dimensionedScalar Ceps1_ protected
Definition at line 123 of file SSG.H.
Ceps2_
template<class BasicTurbulenceModel > dimensionedScalar Ceps2_ protected
Definition at line 124 of file SSG.H.
Cs_
template<class BasicTurbulenceModel > dimensionedScalar Cs_ protected
Definition at line 125 of file SSG.H.
Ceps_
template<class BasicTurbulenceModel > dimensionedScalar Ceps_ protected
Definition at line 126 of file SSG.H.
k_
template<class BasicTurbulenceModel > volScalarField k_ protected
Definition at line 130 of file SSG.H.
Referenced by SSG< BasicTurbulenceModel >::k(), and SSG< BasicTurbulenceModel >::SSG().
epsilon_
template<class BasicTurbulenceModel > volScalarField epsilon_ protected
Definition at line 131 of file SSG.H.
Referenced by SSG< BasicTurbulenceModel >::epsilon(), and SSG< BasicTurbulenceModel >::SSG().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/RAS/SSG/SSG.H
src/TurbulenceModels/turbulenceModels/RAS/SSG/SSG.C