OpenFOAM: polyMesh Class Reference
polyMesh Class Reference
Mesh consisting of general polyhedral cells.
#include <polyMesh.H>
Public Types
enum readUpdateState { UNCHANGED , POINTS_MOVED , TOPO_CHANGE , TOPO_PATCH_CHANGE }
enum cellDecomposition { FACE_PLANES , FACE_CENTRE_TRIS , FACE_DIAG_TRIS , CELL_TETS }
typedef polyMesh Mesh
typedef polyBoundaryMesh BoundaryMesh
Public Types inherited from IOobject
enum objectState : char { GOOD , BAD }
enum fileCheckTypes : char { timeStamp , timeStampMaster , inotify , inotifyMaster }
Public Types inherited from IOobjectOption
enum readOption : unsigned char {
NO_READ = 0 , MUST_READ = 0x1 , READ_MODIFIED = 0x3 , MUST_READ_IF_MODIFIED = 0x3 ,
LAZY_READ = 0x4 , READ_IF_PRESENT = 0x4
}
enum writeOption : unsigned char { NO_WRITE = 0 , AUTO_WRITE = 0x10 }
enum registerOption : unsigned char { NO_REGISTER = 0 , REGISTER = 1 }
Public Types inherited from HashTable< regIOobject * >
typedef HashTable< regIOobject *, word, Foam::Hash< word > > this_type
typedef std::conditional< std::is_same< Foam::zero, typenamestd::remove_cv< regIOobject * >::type >::value, Detail::HashTableSingle< word >, Detail::HashTablePair< word, regIOobject * > >::type node_type
typedef word key_type
typedef regIOobject * mapped_type
typedef regIOobject * value_type
typedef Foam::Hash< word > hasher
typedef regIOobject * * pointer
typedef regIOobject * & reference
typedef const regIOobject * * const_pointer
typedef const regIOobject * & const_reference
typedef label difference_type
typedef label size_type
using key_iterator = key_iterator_base< iterator >
using const_key_iterator = key_iterator_base< const_iterator >
Public Member Functions
TypeName ("polyMesh")
polyMesh (const IOobject &io, const bool doInit=true)
polyMesh (const IOobject &io, const zero, const bool syncPar=true)
polyMesh (const IOobject &io, pointField &&points, faceList &&faces, labelList &&owner, labelList &&neighbour, const bool syncPar=true)
polyMesh (const IOobject &io, pointField &&points, faceList &&faces, cellList &&cells, const bool syncPar=true)
polyMesh (const IOobject &io, pointField &&points, const cellShapeList &shapes, const faceListList &boundaryFaces, const wordList &boundaryPatchNames, const wordList &boundaryPatchTypes, const word &defaultBoundaryPatchName, const word &defaultBoundaryPatchType, const wordList &boundaryPatchPhysicalTypes, const bool syncPar=true)
polyMesh (const IOobject &io, pointField &&points, const cellShapeList &shapes, const faceListList &boundaryFaces, const wordList &boundaryPatchNames, const PtrList< dictionary > &boundaryDicts, const word &defaultBoundaryPatchName, const word &defaultBoundaryPatchType, const bool syncPar=true)
virtual ~polyMesh ()
virtual const fileName & dbDir () const
fileName meshDir () const
const fileName & pointsInstance () const
const fileName & facesInstance () const
void setInstance (const fileName &instance, const IOobjectOption::writeOption wOpt=IOobject::AUTO_WRITE)
const word & regionName () const
virtual const pointField & points () const
virtual bool upToDatePoints (const regIOobject &io) const
virtual void setUpToDatePoints (regIOobject &io) const
virtual const faceList & faces () const
virtual const labelList & faceOwner () const
virtual const labelList & faceNeighbour () const
virtual const pointField & oldPoints () const
virtual const pointField & oldCellCentres () const
const polyBoundaryMesh & boundaryMesh () const noexcept
const boundBox & bounds () const noexcept
const Vector< label > & geometricD () const
label nGeometricD () const
const Vector< label > & solutionD () const
label nSolutionD () const
const labelIOList & tetBasePtIs () const
const indexedOctree< treeDataCell > & cellTree () const
const pointZoneMesh & pointZones () const noexcept
const faceZoneMesh & faceZones () const noexcept
const cellZoneMesh & cellZones () const noexcept
const globalMeshData & globalData () const
label comm () const noexcept
label & comm () noexcept
const objectRegistry & thisDb () const noexcept
virtual bool dynamic () const
bool moving () const noexcept
bool moving (const bool on) noexcept
bool topoChanging () const noexcept
bool topoChanging (const bool on) noexcept
bool changing () const noexcept
virtual void movePoints (const pointField &)
void resetMotion () const
pointZoneMesh & pointZones () noexcept
faceZoneMesh & faceZones () noexcept
cellZoneMesh & cellZones () noexcept
void addPatches (polyPatchList &plist, const bool validBoundary=true)
void addPatches (const List< polyPatch * > &p, const bool validBoundary=true)
void addZones (PtrList< pointZone > &&pz, PtrList< faceZone > &&fz, PtrList< cellZone > &&cz)
void addZones (const List< pointZone * > &pz, const List< faceZone * > &fz, const List< cellZone * > &cz)
virtual bool init (const bool doInit)
virtual readUpdateState readUpdate ()
virtual void updateMesh (const mapPolyMesh &mpm)
void removeBoundary ()
void resetPrimitives (autoPtr< pointField > &&points, autoPtr< faceList > &&faces, autoPtr< labelList > &&owner, autoPtr< labelList > &&neighbour, const labelUList &patchSizes, const labelUList &patchStarts, const bool validBoundary=true)
void clearGeom ()
void updateGeomPoints (pointIOField &&newPoints, autoPtr< labelIOList > &newTetBasePtIsPtr)
void clearAddressing (const bool isMeshUpdate=false)
void clearOut ()
void clearPrimitives ()
void clearTetBasePtIs ()
void clearCellTree ()
void removeFiles (const fileName &instanceDir) const
void removeFiles () const
bool hasTetBasePtIs () const
virtual bool checkFaceOrthogonality (const bool report=false, labelHashSet *setPtr=nullptr) const
virtual bool checkFaceSkewness (const bool report=false, labelHashSet *setPtr=nullptr) const
virtual bool checkEdgeAlignment (const bool report, const Vector< label > &directions, labelHashSet *setPtr) const
virtual bool checkCellDeterminant (const bool report, labelHashSet *setPtr) const
virtual bool checkMeshMotion (const pointField &newPoints, const bool report=false, const bool detailedReport=false) const
virtual bool checkFaceWeight (const bool report, const scalar minWeight=0.05, labelHashSet *setPtr=nullptr) const
virtual bool checkVolRatio (const bool report, const scalar minRatio=0.01, labelHashSet *setPtr=nullptr) const
void findCellFacePt (const point &p, label &celli, label &tetFacei, label &tetPti) const
void findTetFacePt (const label celli, const point &p, label &tetFacei, label &tetPti) const
bool pointInCell (const point &p, label celli, const cellDecomposition=CELL_TETS) const
label findCell (const point &p, const cellDecomposition=CELL_TETS) const
Public Member Functions inherited from objectRegistry
TypeName ("objectRegistry")
objectRegistry (const Time &db, const label nObjects=128)
objectRegistry (const IOobject &io, const label nObjects=128)
virtual ~objectRegistry ()
const objectRegistry & thisDb () const noexcept
const objectRegistry & parent () const noexcept
const Time & time () const noexcept
bool isTimeDb () const noexcept
HashTable< wordHashSet > classes () const
template<class MatchPredicate >
HashTable< wordHashSet > classes (const MatchPredicate &matchName) const
UPtrList< const regIOobject > csorted () const
UPtrList< const regIOobject > sorted () const
UPtrList< regIOobject > sorted ()
template<class Type >
UPtrList< const Type > csorted () const
template<class Type >
UPtrList< const Type > sorted () const
template<class Type >
UPtrList< Type > sorted ()
template<class Type , class MatchPredicate >
UPtrList< const Type > csorted (const MatchPredicate &matchName) const
template<class Type , class MatchPredicate >
UPtrList< const Type > sorted (const MatchPredicate &matchName) const
template<class Type , class MatchPredicate >
UPtrList< Type > sorted (const MatchPredicate &matchName)
label count (const char *clsName) const
template<class MatchPredicate >
label count (const MatchPredicate &matchClass) const
template<class MatchPredicate1 , class MatchPredicate2 >
label count (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName) const
template<class Type >
label count (const bool strict=false) const
template<class Type , class MatchPredicate >
label count (const MatchPredicate &matchName) const
wordList names () const
wordList names (const char *clsName) const
template<class MatchPredicate >
wordList names (const MatchPredicate &matchClass) const
template<class MatchPredicate1 , class MatchPredicate2 >
wordList names (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName) const
template<class Type >
wordList names () const
template<class Type , class MatchPredicate >
wordList names (const MatchPredicate &matchName) const
wordList sortedNames () const
wordList sortedNames (const char *clsName) const
template<class MatchPredicate >
wordList sortedNames (const MatchPredicate &matchClass) const
template<class MatchPredicate1 , class MatchPredicate2 >
wordList sortedNames (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName) const
template<class Type >
wordList sortedNames () const
template<class Type , class MatchPredicate >
wordList sortedNames (const MatchPredicate &matchName) const
const objectRegistry & subRegistry (const word &name, const bool forceCreate=false, const bool recursive=false) const
template<class Type >
HashTable< const Type * > lookupClass (const bool strict=false) const
template<class Type >
HashTable< Type * > lookupClass (const bool strict=false)
const regIOobject * cfindIOobject (const word &name, const bool recursive=false) const
bool contains (const word &name, const bool recursive=false) const
template<class Type >
bool foundObject (const word &name, const bool recursive=false) const
template<class Type >
const Type * cfindObject (const word &name, const bool recursive=false) const
template<class Type >
const Type * findObject (const word &name, const bool recursive=false) const
template<class Type >
Type * findObject (const word &name, const bool recursive=false)
template<class Type >
Type * getObjectPtr (const word &name, const bool recursive=false) const
template<class Type >
const Type & lookupObject (const word &name, const bool recursive=false) const
template<class Type >
Type & lookupObjectRef (const word &name, const bool recursive=false) const
label getEvent () const
bool checkIn (regIOobject *io) const
bool checkIn (regIOobject &io) const
bool checkOut (regIOobject *io) const
bool checkOut (regIOobject &io) const
bool checkOut (const word &key) const
void clear ()
void clearStorage ()
bool erase (const iterator &iter)
bool erase (const word &key)
label erase (std::initializer_list< word > keys)
label erase (const UList< word > &keys)
virtual void rename (const word &newName)
bool cacheTemporaryObject (const word &name) const
template<class Type >
bool cacheTemporaryObject (Type &obj) const
void resetCacheTemporaryObject (const regIOobject *io) const
void resetCacheTemporaryObject (const regIOobject &io) const
bool checkCacheTemporaryObjects () const
virtual bool modified () const
void readModifiedObjects ()
virtual bool readIfModified ()
virtual bool writeData (Ostream &) const
virtual bool writeObject (IOstreamOption streamOpt, const bool writeOnProc) const
bool found (const word &name, bool recursive=false) const
template<class Type >
const Type * lookupObjectPtr (const word &name, bool recursive=false) const
template<class Type >
Type * lookupObjectRefPtr (const word &name, bool recursive=false) const
template<class MatchPredicate >
Foam::HashTable< Foam::wordHashSet > classesImpl (const objectRegistry &list, const MatchPredicate &matchName)
template<class MatchPredicate1 , class MatchPredicate2 >
Foam::label countImpl (const objectRegistry &list, const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName)
template<class Type , class MatchPredicate >
Foam::label countTypeImpl (const objectRegistry &list, const MatchPredicate &matchName)
template<class MatchPredicate1 , class MatchPredicate2 >
Foam::wordList namesImpl (const objectRegistry &list, const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName, const bool doSort)
template<class Type , class MatchPredicate >
Foam::wordList namesTypeImpl (const objectRegistry &list, const MatchPredicate &matchName, const bool doSort)
template<class Type , class MatchPredicate >
Foam::UPtrList< Type > objectsTypeImpl (const objectRegistry &list, const MatchPredicate &matchName)
template<class MatchPredicate >
Foam::HashTable< Foam::wordHashSet > classes (const MatchPredicate &matchName) const
template<class MatchPredicate >
Foam::label count (const MatchPredicate &matchClass) const
template<class MatchPredicate1 , class MatchPredicate2 >
Foam::label count (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName) const
template<class Type , class MatchPredicate >
Foam::label count (const MatchPredicate &matchName) const
template<class Type >
Foam::label count (const bool strict) const
template<class Type >
Foam::UPtrList< const Type > csorted () const
template<class Type >
Foam::UPtrList< const Type > sorted () const
template<class Type >
Foam::UPtrList< Type > sorted ()
template<class Type , class MatchPredicate >
Foam::UPtrList< const Type > csorted (const MatchPredicate &matchName) const
template<class Type , class MatchPredicate >
Foam::UPtrList< const Type > sorted (const MatchPredicate &matchName) const
template<class Type , class MatchPredicate >
Foam::UPtrList< Type > sorted (const MatchPredicate &matchName)
template<class MatchPredicate >
Foam::wordList names (const MatchPredicate &matchClass) const
template<class MatchPredicate1 , class MatchPredicate2 >
Foam::wordList names (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName) const
template<class Type >
Foam::wordList names () const
template<class Type , class MatchPredicate >
Foam::wordList names (const MatchPredicate &matchName) const
template<class MatchPredicate >
Foam::wordList sortedNames (const MatchPredicate &matchClass) const
template<class MatchPredicate1 , class MatchPredicate2 >
Foam::wordList sortedNames (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName) const
template<class Type >
Foam::wordList sortedNames () const
template<class Type , class MatchPredicate >
Foam::wordList sortedNames (const MatchPredicate &matchName) const
template<class Type >
Foam::HashTable< const Type * > lookupClass (const bool strict) const
template<class Type >
Foam::HashTable< Type * > lookupClass (const bool strict)
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
regIOobject (const IOobject &io, const bool isTimeObject=false)
regIOobject (const regIOobject &rio)
regIOobject (const regIOobject &rio, bool registerCopy)
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
regIOobject (const IOobject &io, const regIOobject &rio)
virtual ~regIOobject ()
bool checkIn ()
bool checkOut ()
virtual void addWatch ()
bool registered () const noexcept
bool ownedByRegistry () const noexcept
bool store ()
void release (const bool unregister=false) noexcept
label eventNo () const noexcept
label & eventNo () noexcept
bool upToDate (const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
void setUpToDate ()
const dictionary * findMetaData () const noexcept
dictionary & getMetaData () noexcept
void removeMetaData ()
virtual void updateMetaData ()
virtual fileName filePath () const
bool headerOk ()
Istream & readStream (const word &, const bool readOnProc=true)
void close ()
virtual bool readData (Istream &)
virtual bool read ()
virtual label addWatch (const fileName &)
const labelList & watchIndices () const noexcept
labelList & watchIndices () noexcept
virtual bool write (const bool writeOnProc=true) const
virtual bool global () const
void operator= (const IOobject &io)
virtual bool writeObject (IOstreamOption::streamFormat fmt, IOstreamOption::versionNumber ver, IOstreamOption::compressionType cmp, const bool writeOnProc) const
Public Member Functions inherited from IOobject
TypeName ("IOobject")
IOobject (const IOobject &)=default
virtual ~IOobject ()=default
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const fileName &path, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const fileName &path, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const IOobject &io, const objectRegistry &registry)
IOobject (const IOobject &io, const word &name)
IOobject (const IOobject &io, const word &name, const fileName &local)
IOobject (const IOobject &io, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt)
IOobject (const IOobject &io, IOobjectOption::registerOption regOpt)
autoPtr< IOobject > clone () const
autoPtr< IOobject > clone (const objectRegistry &registry) const
const objectRegistry & db () const noexcept
const Time & time () const noexcept
const word & name () const noexcept
const word & headerClassName () const noexcept
word & headerClassName () noexcept
const string & note () const noexcept
string & note () noexcept
unsigned labelByteSize () const noexcept
unsigned scalarByteSize () const noexcept
void resetHeader (const word &newName=word::null)
bool hasHeaderClass () const noexcept
template<class Type >
bool isHeaderClass () const
template<class Type >
bool isHeaderClassName () const
word group () const
word member () const
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const noexcept
fileName & instance () noexcept
const fileName & local () const noexcept
fileName path () const
fileName path (const word &instance, const fileName &local=fileName::null) const
fileName objectPath () const
fileName objectRelPath () const
fileName localFilePath (const word &typeName, const bool search=true) const
fileName globalFilePath (const word &typeName, const bool search=true) const
IOstreamOption parseHeader (const dictionary &headerDict)
bool readHeader (Istream &is)
bool readHeader (dictionary &headerDict, Istream &is)
template<class Type >
bool typeHeaderOk (const bool checkType=true, const bool search=true, const bool verbose=true)
template<class Type >
void warnNoRereading () const
bool writeHeader (Ostream &os) const
bool writeHeader (Ostream &os, const word &objectType) const
void writeHeader (dictionary &dict, IOstreamOption streamOpt) const
void writeHeader (dictionary &dict, const word &objectType, IOstreamOption streamOpt) const
bool good () const noexcept
bool bad () const noexcept
InfoProxy< IOobject > info () const noexcept
void operator= (const IOobject &io)
template<>
bool isHeaderClass () const
template<class StringType >
Foam::word groupName (StringType base, const word &group)
Public Member Functions inherited from IOobjectOption
constexpr IOobjectOption (readOption rOpt=readOption::NO_READ, writeOption wOpt=writeOption::NO_WRITE, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (readOption rOpt, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (writeOption wOpt, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (registerOption registerObject, bool globalObject=false) noexcept
constexpr IOobjectOption (readOption rOpt, writeOption wOpt, bool registerObject, bool globalObject=false) noexcept
constexpr IOobjectOption (bool registerObject, bool globalObject=false) noexcept
readOption readOpt () const noexcept
readOption readOpt (readOption opt) noexcept
writeOption writeOpt () const noexcept
writeOption writeOpt (writeOption opt) noexcept
bool registerObject () const noexcept
bool registerObject (bool on) noexcept
bool globalObject () const noexcept
bool globalObject (bool on) noexcept
bool isAnyRead () const noexcept
bool isReadRequired () const noexcept
bool isReadOptional () const noexcept
readOption & readOpt () noexcept
writeOption & writeOpt () noexcept
bool & registerObject () noexcept
bool & globalObject () noexcept
Public Member Functions inherited from HashTable< regIOobject * >
HashTable ()
HashTable (const label size)
HashTable (Istream &is, const label size=128)
HashTable (const this_type &ht)
HashTable (this_type &&rhs)
HashTable (std::initializer_list< std::pair< word, regIOobject * > > list)
~HashTable ()
bool empty () const noexcept
label size () const noexcept
label capacity () const noexcept
regIOobject * & at (const word &key)
const regIOobject * & at (const word &key) const
bool contains (const word &key) const
iterator find (const word &key)
const_iterator find (const word &key) const
const_iterator cfind (const word &key) const
const regIOobject * & lookup (const word &key, const regIOobject * &deflt) const
List< word > toc () const
List< word > sortedToc () const
List< word > sortedToc (const Compare &comp) const
Foam::List< word > sortedToc (const Compare &comp) const
List< word > tocKeys (const UnaryPredicate &pred, const bool invert=false) const
Foam::List< word > tocKeys (const UnaryPredicate &pred, const bool invert) const
List< word > tocValues (const UnaryPredicate &pred, const bool invert=false) const
Foam::List< word > tocValues (const UnaryPredicate &pred, const bool invert) const
List< word > tocEntries (const BinaryPredicate &pred, const bool invert=false) const
Foam::List< word > tocEntries (const BinaryPredicate &pred, const bool invert) const
UPtrList< const node_type > csorted () const
UPtrList< const node_type > sorted () const
UPtrList< node_type > sorted ()
label countKeys (const UnaryPredicate &pred, const bool invert=false) const
Foam::label countKeys (const UnaryPredicate &pred, const bool invert) const
label countValues (const UnaryPredicate &pred, const bool invert=false) const
Foam::label countValues (const UnaryPredicate &pred, const bool invert) const
label countEntries (const BinaryPredicate &pred, const bool invert=false) const
Foam::label countEntries (const BinaryPredicate &pred, const bool invert) const
bool emplace (const word &key, Args &&... args)
bool emplace_set (const word &key, Args &&... args)
bool insert (const word &key, const regIOobject * &obj)
bool insert (const word &key, regIOobject * &&obj)
bool set (const word &key, const regIOobject * &obj)
bool set (const word &key, regIOobject * &&obj)
bool erase (const iterator &iter)
bool erase (const word &key)
label erase (const HashTable< AnyType, word, AnyHash > &other)
label erase (std::initializer_list< word > keys)
label erase (InputIter first, InputIter last)
label erase (const FixedList< word, N > &keys)
label erase (const UList< word > &keys)
Foam::label erase (InputIter first, InputIter last)
Foam::label erase (const FixedList< word, N > &keys)
Foam::label erase (const HashTable< AnyType, word, AnyHash > &other)
label retain (const HashTable< AnyType, word, AnyHash > &other)
Foam::label retain (const HashTable< AnyType, word, AnyHash > &other)
label filterKeys (const UnaryPredicate &pred, const bool pruning=false)
Foam::label filterKeys (const UnaryPredicate &pred, const bool pruning)
label filterValues (const UnaryPredicate &pred, const bool pruning=false)
Foam::label filterValues (const UnaryPredicate &pred, const bool pruning)
label filterEntries (const BinaryPredicate &pred, const bool pruning=false)
Foam::label filterEntries (const BinaryPredicate &pred, const bool pruning)
void resize (const label sz)
void clear ()
void clearStorage ()
void swap (HashTable< regIOobject *, word, Foam::Hash< word > > &rhs)
void transfer (HashTable< regIOobject *, word, Foam::Hash< word > > &rhs)
void merge (HashTable< regIOobject *, word, Foam::Hash< word > > &source)
void merge (HashTable< regIOobject *, word, Foam::Hash< word > > &&source)
regIOobject * & operator[] (const word &key)
const regIOobject * & operator[] (const word &key) const
regIOobject * & operator() (const word &key)
regIOobject * & operator() (const word &key, const regIOobject * &deflt)
void operator= (const this_type &rhs)
void operator= (std::initializer_list< std::pair< word, regIOobject * > > rhs)
void operator= (this_type &&rhs)
bool operator== (const this_type &rhs) const
bool operator!= (const this_type &rhs) const
this_type & operator+= (const this_type &rhs)
const_iterator_pair< const_key_iterator, this_type > keys () const
iterator begin ()
const_iterator begin () const
const_iterator cbegin () const
iterator end () noexcept
const_iterator end () const noexcept
constexpr const_iterator cend () const noexcept
Ostream & printInfo (Ostream &os) const
Ostream & writeKeys (Ostream &os, const label shortLen=0) const
bool found (const word &key) const
Public Member Functions inherited from HashTableCore
ClassName ("HashTable")
HashTableCore () noexcept=default
Public Member Functions inherited from primitiveMesh
ClassName ("primitiveMesh")
primitiveMesh (const label nPoints, const label nInternalFaces, const label nFaces, const label nCells)
virtual ~primitiveMesh ()
void reset (const label nPoints, const label nInternalFaces, const label nFaces, const label nCells)
void reset (const label nPoints, const label nInternalFaces, const label nFaces, const label nCells, cellList &cells)
void resetGeometry (pointField &&faceCentres, pointField &&faceAreas, pointField &&cellCentres, scalarField &&cellVolumes)
label nPoints () const noexcept
label nEdges () const
label nFaces () const noexcept
label nCells () const noexcept
label nInternalFaces () const noexcept
label nBoundaryFaces () const noexcept
label nInternalPoints () const noexcept
label nInternal0Edges () const
label nInternal1Edges () const
label nInternalEdges () const
const cellShapeList & cellShapes () const
const edgeList & edges () const
const labelListList & cellCells () const
const labelListList & edgeCells () const
const labelListList & pointCells () const
const cellList & cells () const
const labelListList & edgeFaces () const
const labelListList & pointFaces () const
const labelListList & cellEdges () const
const labelListList & faceEdges () const
const labelListList & pointEdges () const
const labelListList & pointPoints () const
const labelListList & cellPoints () const
const vectorField & cellCentres () const
const vectorField & faceCentres () const
const scalarField & cellVolumes () const
const vectorField & faceAreas () const
void movePoints (const pointField &p, const pointField &oldP)
bool isInternalFace (const label faceIndex) const noexcept
virtual bool checkUpperTriangular (const bool report=false, labelHashSet *setPtr=nullptr) const
virtual bool checkCellsZipUp (const bool report=false, labelHashSet *setPtr=nullptr) const
virtual bool checkFaceVertices (const bool report=false, labelHashSet *setPtr=nullptr) const
virtual bool checkPoints (const bool report=false, labelHashSet *setPtr=nullptr) const
virtual bool checkFaceFaces (const bool report=false, labelHashSet *setPtr=nullptr) const
virtual bool checkClosedBoundary (const bool report=false) const
virtual bool checkClosedCells (const bool report=false, labelHashSet *setPtr=nullptr, labelHashSet *highAspectSetPtr=nullptr, const Vector< label > &solutionD=Vector< label >::one) const
virtual bool checkFaceAreas (const bool report=false, labelHashSet *setPtr=nullptr) const
virtual bool checkCellVolumes (const bool report=false, labelHashSet *setPtr=nullptr) const
virtual bool checkFacePyramids (const bool report=false, const scalar minPyrVol=-SMALL, labelHashSet *setPtr=nullptr) const
virtual bool checkFaceAngles (const bool report=false, const scalar maxSin=10, labelHashSet *setPtr=nullptr) const
virtual bool checkFaceFlatness (const bool report, const scalar warnFlatness, labelHashSet *setPtr) const
virtual bool checkPointNearness (const bool report, const scalar reportDistSqr, labelHashSet *setPtr=nullptr) const
virtual bool checkEdgeLength (const bool report, const scalar minLenSqr, labelHashSet *setPtr=nullptr) const
virtual bool checkConcaveCells (const bool report=false, labelHashSet *setPtr=nullptr) const
virtual bool checkTopology (const bool report=false) const
virtual bool checkGeometry (const bool report=false) const
virtual bool checkMesh (const bool report=false) const
boundBox cellBb (const label celli) const
bool pointInCellBB (const point &p, label celli, scalar inflationFraction=0) const
bool pointInCell (const point &p, label celli) const
label findNearestCell (const point &location) const
label findCell (const point &location) const
void printAllocated () const
bool hasCellShapes () const noexcept
bool hasEdges () const noexcept
bool hasCellCells () const noexcept
bool hasEdgeCells () const noexcept
bool hasPointCells () const noexcept
bool hasCells () const noexcept
bool hasEdgeFaces () const noexcept
bool hasPointFaces () const noexcept
bool hasCellEdges () const noexcept
bool hasFaceEdges () const noexcept
bool hasPointEdges () const noexcept
bool hasPointPoints () const noexcept
bool hasCellPoints () const noexcept
bool hasCellCentres () const noexcept
bool hasCellVolumes () const noexcept
bool hasFaceCentres () const noexcept
bool hasFaceAreas () const noexcept
const labelList & cellCells (const label celli, DynamicList< label > &) const
const labelList & cellCells (const label celli) const
const labelList & cellPoints (const label celli, labelHashSet &, DynamicList< label > &) const
const labelList & cellPoints (const label celli) const
const labelList & pointCells (const label pointi, DynamicList< label > &) const
const labelList & pointCells (const label pointi) const
const labelList & pointPoints (const label pointi, DynamicList< label > &) const
const labelList & pointPoints (const label pointi) const
const labelList & faceEdges (const label facei, DynamicList< label > &) const
const labelList & faceEdges (const label facei) const
const labelList & edgeFaces (const label edgeI, DynamicList< label > &) const
const labelList & edgeFaces (const label edgeI) const
const labelList & edgeCells (const label edgeI, DynamicList< label > &) const
const labelList & edgeCells (const label edgeI) const
const labelList & cellEdges (const label celli, labelHashSet &, DynamicList< label > &) const
const labelList & cellEdges (const label celli) const
virtual void updateGeom ()
void clearGeom ()
void clearCellGeom ()
void clearAddressing ()
void clearOut ()
Static Public Member Functions
static const word & regionName (const word &region)
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *p)
template<class Type >
static Type & store (autoPtr< Type > &ptr)
template<class Type >
static Type & store (autoPtr< Type > &&ptr)
template<class Type >
static Type & store (refPtr< Type > &ptr)
template<class Type >
static Type & store (refPtr< Type > &&ptr)
template<class Type >
static Type & store (tmp< Type > &ptr)
template<class Type >
static Type & store (tmp< Type > &&ptr)
Static Public Member Functions inherited from IOobject
static bool bannerEnabled () noexcept
static bool bannerEnabled (bool on) noexcept
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
template<class StringType >
static word groupName (StringType base, const word &group)
static word group (const word &name)
static word member (const word &name)
static word scopedName (const std::string &scope, const word &name)
static IOobject selectIO (const IOobject &io, const fileName &altFile, const word &ioName="")
static Ostream & writeBanner (Ostream &os, const bool noSyntaxHint=false)
static Ostream & writeDivider (Ostream &os)
static Ostream & writeEndDivider (Ostream &os)
Static Public Member Functions inherited from IOobjectOption
static bool isAnyRead (readOption opt) noexcept
static bool isReadRequired (readOption opt) noexcept
static bool isReadOptional (readOption opt) noexcept
static readOption lazierRead (readOption opt) noexcept
Static Public Member Functions inherited from HashTableCore
static label canonicalSize (const label requested_size)
Static Public Member Functions inherited from primitiveMesh
static void calcCells (cellList &, const labelUList &own, const labelUList &nei, const label nCells=-1)
static bool calcPointOrder (label &nInternalPoints, labelList &pointMap, const faceList &, const label nInternalFaces, const label nPoints)
static scalar setClosedThreshold (const scalar)
static scalar setAspectThreshold (const scalar)
static scalar setNonOrthThreshold (const scalar)
static scalar setSkewThreshold (const scalar)
Static Public Attributes
static word defaultRegion = "region0"
static word meshSubDir = "polyMesh"
Static Public Attributes inherited from IOobject
static const Enum< fileCheckTypes > fileCheckTypesNames
static char scopeSeparator
static fileCheckTypes fileModificationChecking
static float fileModificationSkew
static int maxFileModificationPolls
Static Public Attributes inherited from HashTableCore
static const label maxTableSize
Static Public Attributes inherited from primitiveMesh
static const unsigned cellsPerEdge_ = 4
static const unsigned cellsPerPoint_ = 8
static const unsigned facesPerCell_ = 6
static const unsigned facesPerEdge_ = 4
static const unsigned facesPerPoint_ = 12
static const unsigned edgesPerCell_ = 12
static const unsigned edgesPerFace_ = 4
static const unsigned edgesPerPoint_ = 6
static const unsigned pointsPerCell_ = 8
static const unsigned pointsPerFace_ = 4
Additional Inherited Members
Protected Member Functions inherited from regIOobject
bool readHeaderOk (const IOstreamOption::streamFormat fmt, const word &typeName)
Protected Member Functions inherited from IOobject
void setBad (const string &s)
Protected Member Functions inherited from primitiveMesh
void calcFaceCentresAndAreas () const
void calcCellCentresAndVols () const
void calcEdgeVectors () const
bool checkDuplicateFaces (const label, const Map< label > &, label &nBaffleFaces, labelHashSet *) const
bool checkCommonOrder (const label, const Map< label > &, labelHashSet *) const
bool checkClosedBoundary (const vectorField &areas, const bool report, const bitSet &internalOrCoupledFaces) const
bool checkClosedCells (const vectorField &faceAreas, const scalarField &cellVolumes, const bool report, labelHashSet *setPtr, labelHashSet *aspectSetPtr, const Vector< label > &meshD) const
bool checkFaceAreas (const vectorField &faceAreas, const bool report, const bool detailedReport, labelHashSet *setPtr) const
bool checkCellVolumes (const scalarField &vols, const bool report, const bool detailedReport, labelHashSet *setPtr) const
bool checkFaceOrthogonality (const vectorField &fAreas, const vectorField &cellCtrs, const bool report, labelHashSet *setPtr) const
bool checkFacePyramids (const pointField &points, const vectorField &ctrs, const bool report, const bool detailedReport, const scalar minPyrVol, labelHashSet *setPtr) const
bool checkFaceSkewness (const pointField &points, const vectorField &fCtrs, const vectorField &fAreas, const vectorField &cellCtrs, const bool report, labelHashSet *setPtr) const
bool checkFaceAngles (const pointField &points, const vectorField &faceAreas, const bool report, const scalar maxDeg, labelHashSet *setPtr) const
bool checkFaceFlatness (const pointField &points, const vectorField &faceCentres, const vectorField &faceAreas, const bool report, const scalar warnFlatness, labelHashSet *setPtr) const
bool checkConcaveCells (const vectorField &fAreas, const pointField &fCentres, const bool report, labelHashSet *setPtr) const
primitiveMesh ()
Static Protected Member Functions inherited from IOobject
static void writeHeaderContent (Ostream &os, const IOobject &io, const word &objectType, const dictionary *metaDataDict=nullptr)
static void writeHeaderContent (dictionary &dict, const IOobject &io, const word &objectType, IOstreamOption streamOpt, const dictionary *metaDataDict=nullptr)
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
Static Protected Attributes inherited from primitiveMesh
static scalar closedThreshold_ = 1.0e-6
static scalar aspectThreshold_ = 1000
static scalar nonOrthThreshold_ = 70
static scalar skewThreshold_ = 4
static scalar planarCosAngle_ = 1.0e-6
Detailed Description
Mesh consisting of general polyhedral cells.
Source files
polyMesh.H
polyMesh.C
polyMeshInitMesh.C
polyMeshClear.C
polyMeshFromShapeMesh.C
polyMeshIO.C
polyMeshUpdate.C
polyMeshCheck.C
Definition at line 73 of file polyMesh.H.
Member Typedef Documentation
Mesh
typedef polyMesh Mesh
Definition at line 307 of file polyMesh.H.
BoundaryMesh
typedef polyBoundaryMesh BoundaryMesh
Definition at line 310 of file polyMesh.H.
Member Enumeration Documentation
readUpdateState
enum readUpdateState
Enumerator
UNCHANGED
POINTS_MOVED
TOPO_CHANGE
TOPO_PATCH_CHANGE
Definition at line 86 of file polyMesh.H.
cellDecomposition
enum cellDecomposition
Enumerator
FACE_PLANES
FACE_CENTRE_TRIS
FACE_DIAG_TRIS
CELL_TETS
Definition at line 96 of file polyMesh.H.
Constructor & Destructor Documentation
polyMesh() [1/6]
polyMesh (const IOobject & io, const bool doInit = true) explicit
Definition at line 165 of file polyMesh.C.
References UPtrList< T >::empty(), Foam::endl(), IOobject::hasHeaderClass(), polyMesh::init(), polyMesh::meshDir(), polyMesh::meshSubDir, IOobjectOption::MUST_READ, primitiveMesh::nCells(), IOobjectOption::NO_WRITE, primitiveMesh::nPoints(), Foam::returnReduceAnd(), Foam::returnReduceOr(), objectRegistry::time(), WarningInFunction, and regIOobject::write().
polyMesh() [2/6]
polyMesh (const IOobject & io, const zero , const bool syncPar = true)
Definition at line 703 of file polyMesh.C.
polyMesh() [3/6]
polyMesh (const IOobject & io, pointField && points, faceList && faces, labelList && owner, labelList && neighbour, const bool syncPar = true)
Definition at line 379 of file polyMesh.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::max(), Foam::min(), and UList< T >::size().
polyMesh() [4/6]
polyMesh (const IOobject & io, pointField && points, faceList && faces, cellList && cells, const bool syncPar = true)
Definition at line 533 of file polyMesh.C.
References Foam::abort(), primitiveMesh::cells(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::max(), Foam::min(), and UList< T >::size().
polyMesh() [5/6]
polyMesh (const IOobject & io, pointField && points, const cellShapeList & shapes, const faceListList & boundaryFaces, const wordList & boundaryPatchNames, const wordList & boundaryPatchTypes, const word & defaultBoundaryPatchName, const word & defaultBoundaryPatchType, const wordList & boundaryPatchPhysicalTypes, const bool syncPar = true)
Definition at line 438 of file polyMeshFromShapeMesh.C.
References primitiveMesh::cells(), primitiveMesh::checkMesh(), DebugInfo, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::Info, IOobject::name(), polyPatch::New(), primitiveMesh::nFaces(), Foam::reduce(), PtrList< T >::set(), PtrList< T >::setSize(), UPtrList< T >::size(), UList< T >::size(), polyBoundaryMesh::updateMesh(), and WarningInFunction.
polyMesh() [6/6]
polyMesh (const IOobject & io, pointField && points, const cellShapeList & shapes, const faceListList & boundaryFaces, const wordList & boundaryPatchNames, const PtrList< dictionary > & boundaryDicts, const word & defaultBoundaryPatchName, const word & defaultBoundaryPatchType, const bool syncPar = true)
Definition at line 720 of file polyMeshFromShapeMesh.C.
References boundaryDicts(), primitiveMesh::cells(), primitiveMesh::checkMesh(), DebugInfo, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::Info, IOobject::name(), polyPatch::New(), primitiveMesh::nFaces(), Foam::reduce(), PtrList< T >::set(), PtrList< T >::setSize(), UPtrList< T >::size(), UList< T >::size(), Foam::type(), polyBoundaryMesh::updateMesh(), and WarningInFunction.
~polyMesh()
~polyMesh () virtual
Definition at line 808 of file polyMesh.C.
Member Function Documentation
TypeName()
TypeName ("polyMesh")
dbDir()
const Foam::fileName & dbDir () const virtual
Reimplemented from objectRegistry.
Definition at line 825 of file polyMesh.C.
References objectRegistry::dbDir().
Referenced by topoSet::findIOobject(), topoSet::localPath(), faMesh::meshDir(), and cellCellStencil::zoneID().
meshDir()
Foam::fileName meshDir () const
Definition at line 836 of file polyMesh.C.
Referenced by polyMesh::polyMesh().
pointsInstance()
const Foam::fileName & pointsInstance () const
Definition at line 848 of file polyMesh.C.
Referenced by fvMesh::makeSf(), faMesh::pointsInstance(), shapeOptimisation::updateDesignVariables(), mappedPatchBase::updateMeshTime(), and mappedPatchBase::updateSampleMeshTime().
facesInstance()
const Foam::fileName & facesInstance () const
Definition at line 854 of file polyMesh.C.
Referenced by manualDecomp::decompose(), faMesh::facesInstance(), topoSet::findIOobject(), topoSet::localPath(), processorFaMeshes::removeFiles(), hexRef8::removeFiles(), refinementHistory::removeFiles(), meshRefinement::removeFiles(), topoSet::removeFiles(), processorMeshes::removeFiles(), manualRenumber::renumber(), faMeshTools::writeProcAddressing(), fvMeshTools::writeProcAddressing(), and cellCellStencil::zoneID().
setInstance()
void setInstance (const fileName & instance, const IOobjectOption::writeOption wOpt = IOobject::AUTO_WRITE)
Definition at line 28 of file polyMeshIO.C.
References DebugInFunction, Foam::endl(), IOobject::instance(), and IOobjectOption::writeOpt().
Referenced by snappyLayerDriver::addLayers(), snappyLayerDriver::addLayers(), columnFvMesh::columnFvMesh(), meshRefinement::mergePatchFaces(), and polyMesh::updateMesh().
regionName() [1/2]
const Foam::word & regionName (const word & region) static
Definition at line 817 of file polyMesh.C.
References polyMesh::defaultRegion, and word::null.
Referenced by faMeshTools::newMesh().
regionName() [2/2]
const Foam::word & regionName () const
Definition at line 842 of file polyMesh.C.
References IOobject::name(), and polyMesh::regionName().
Referenced by dynamicFvMesh::New(), simplifiedDynamicFvMeshBase::New(), fvMeshTools::newMesh(), faMesh::regionName(), polyMesh::regionName(), and vtkWrite::write().
points()
const Foam::pointField & points () const virtual
Implements primitiveMesh.
Definition at line 1073 of file polyMesh.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Referenced by polyMeshAdder::add(), snappyLayerDriver::addLayers(), polyTopoChange::addMesh(), polyMeshTetDecomposition::adjustTetBasePtIs(), tetIndices::barycentricToPoint(), treeDataCell::bounds(), Foam::boundsImpl(), cell::box(), holeToFace::calcClosure(), polyDualMesh::calcFeatures(), meshRefinement::calculateEdgeWeights(), polyTopoChange::changeMesh(), layerAdditionRemoval::changeTopology(), polyMeshGeometry::checkEdgeLength(), polyMeshTetDecomposition::checkFaceTets(), motionSmootherAlgo::checkMesh(), pointZone::checkParallelSync(), edgeVertex::coord(), volumetricBSplinesMotionSolver::curPoints(), geomCellLooper::cut(), mappedPatchBase::facePoint(), tetIndices::faceTri(), localPointRegion::findDuplicateFaces(), mappedPatchBase::findLocalSamples(), searchableExtrudedCircle::findParametricNearest(), polyMeshAdder::findSharedPoints(), PatchTools::gatherAndMerge(), Foam::getMeshPointRef(), searchableExtrudedCircle::getNormal(), externalDisplacementMeshMover::getPatch(), FreeStream< CloudType >::inflow(), volPointInterpolation::interpolateDimensionedInternalField(), wallBoundedParticle::isTriAlongTrack(), meshRefinement::makePatch(), polyMeshAdder::mergePoints(), momentOfInertia::meshInertia(), faMesh::movePoints(), cyclicACMIFvPatch::movePoints(), tetOverlapVolume::overlappingCells(), cuttingPlane::performCut(), fvMeshDistribute::printMeshInfo(), boundaryMesh::read(), elasticityMotionSolver::setBoundaryConditions(), edgeFaceCirculator::setCanonical(), motionSmootherAlgo::setDisplacement(), boundaryMesh::setFeatureEdges(), displacementMethodelasticityMotionSolver::setMotionField(), meshCutter::setRefinement(), perfectInterface::setRefinement(), meshCutAndRemove::setRefinement(), perfectInterface::setRefinement(), syncTools::syncEdgeList(), syncTools::syncEdgeList(), meshRefinement::testSyncPointList(), meshRefinement::testSyncPointList(), tetIndices::tet(), wallBoundedParticle::trackFaceTri(), wallBoundedParticle::trackToEdge(), triSurfaceTools::triangulate(), triSurfaceTools::triangulate(), triSurfaceTools::triangulateFaceCentre(), dynamicMotionSolverListFvMesh::update(), inverseDistance::update(), trackingInverseDistance::update(), cellMotionFvPatchField< Type >::updateCoeffs(), shapeOptimisation::updateDesignVariables(), pointEdgePoint::updateEdge(), PointIntegrateData< DataType >::updateEdge(), componentDisplacementMotionSolver::updateMesh(), points0MotionSolver::updateMesh(), pointEdgePoint::updatePoint(), pointEdgePoint::updatePoint(), FacePostProcessing< CloudType >::write(), ensightCells::write(), pointSet::writeDebug(), pointBitSet::writeDebug(), and MeshedSurface< face >::~MeshedSurface().
upToDatePoints()
bool upToDatePoints (const regIOobject & io) const virtual
Definition at line 1086 of file polyMesh.C.
References io().
setUpToDatePoints()
void setUpToDatePoints (regIOobject & io) const virtual
Definition at line 1092 of file polyMesh.C.
References io().
faces()
const Foam::faceList & faces () const virtual
Implements primitiveMesh.
Definition at line 1098 of file polyMesh.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Referenced by polyMeshAdder::add(), cyclicAMIPolyPatch::addAMIFaces(), polyTopoChange::addMesh(), polyMeshTetDecomposition::adjustTetBasePtIs(), primitiveMeshTools::boundaryFaceSkewness(), Foam::boundsImpl(), cell::box(), holeToFace::calcClosure(), polyDualMesh::calcFeatures(), pointMVCWeight::calcWeights(), polyMeshTetDecomposition::cellTetIndices(), layerAdditionRemoval::changeTopology(), polyMeshGeometry::checkEdgeLength(), polyMeshGeometry::checkFaceAngles(), primitiveMeshGeometry::checkFaceAngles(), polyMeshGeometry::checkFaceFlatness(), polyMeshGeometry::checkFacePyramids(), primitiveMeshGeometry::checkFacePyramids(), polyMeshGeometry::checkFaceSkewness(), polyMeshTetDecomposition::checkFaceTets(), polyMeshGeometry::checkFaceTwist(), primitiveMeshGeometry::checkFaceTwist(), edgeCollapser::checkMeshQuality(), polyMeshGeometry::checkTriangleTwist(), inversePointDistanceDiffusivity::correct(), wallBoundedParticle::crossDiagonalEdge(), wallBoundedParticle::crossEdgeConnectedFace(), wallBoundedParticle::crossEdgeConnectedFace(), decompositionMethod::decompose(), directionInfo::edgeToFaceIndex(), primitiveMeshTools::faceConcavity(), primitiveMeshTools::faceFlatness(), mappedPatchBase::facePoint(), primitiveMeshTools::facePyramidVolume(), polyMeshTools::faceSkewness(), primitiveMeshTools::faceSkewness(), primitiveMeshTools::faceSkewness(), polyMeshTetDecomposition::faceTetIndices(), tetIndices::faceTriIs(), polyMeshTetDecomposition::findBasePoint(), localPointRegion::findDuplicateFaces(), polyMeshTetDecomposition::findFaceBasePts(), sampledSet::findNearFace(), polyMeshTetDecomposition::findSharedBasePoint(), polyMeshTetDecomposition::findTet(), surfaceSets::getHangingCells(), externalDisplacementMeshMover::getPatch(), wallBoundedParticle::hitProcessorPatch(), prismMatcher::isA(), tetWedgeMatcher::isA(), wedgeMatcher::isA(), highAspectRatioFvGeometryScheme::makeAverageCentres(), primitiveMeshTools::makeFaceCentresAndAreas(), meshRefinement::makePatch(), degenerateMatcher::match(), hexMatcher::matches(), prismMatcher::matches(), pyrMatcher::matches(), tetMatcher::matches(), tetWedgeMatcher::matches(), wedgeMatcher::matches(), polyMeshAdder::mergePoints(), treeDataFace::overlaps(), edgeFaceCirculator::sameOrder(), edgeFaceCirculator::setCanonical(), meshCutter::setRefinement(), perfectInterface::setRefinement(), meshCutAndRemove::setRefinement(), perfectInterface::setRefinement(), syncTools::syncEdgeMap(), hexMatcher::test(), pyrMatcher::test(), tetMatcher::test(), wallBoundedParticle::trackToEdge(), tetIndices::triIs(), directionInfo::updateCell(), lumpedPointMovement::writeZonesVTP(), and MeshedSurface< face >::~MeshedSurface().
faceOwner()
const Foam::labelList & faceOwner () const virtual
Implements primitiveMesh.
Definition at line 1111 of file polyMesh.C.
Referenced by polyMeshAdder::add(), cyclicAMIPolyPatch::addAMIFaces(), polyTopoChange::addMesh(), polyMeshTetDecomposition::adjustTetBasePtIs(), polyMeshGeometry::affectedCells(), snappySnapDriver::avgCellCentres(), decompositionMethod::calcCellCells(), decompositionMethod::calcCellCells(), polyDualMesh::calcFeatures(), dynamicRefineFvMesh::calculateProtectedCells(), primitiveMeshTools::cellClosedness(), edgeFaceCirculator::cellLabel(), polyMeshGeometry::checkFaceDotProduct(), primitiveMeshGeometry::checkFaceDotProduct(), polyMeshGeometry::checkFacePyramids(), primitiveMeshGeometry::checkFacePyramids(), polyMeshGeometry::checkFaceSkewness(), primitiveMeshGeometry::checkFaceSkewness(), polyMeshGeometry::checkFaceTets(), polyMeshTetDecomposition::checkFaceTets(), polyMeshGeometry::checkFaceTwist(), polyMeshGeometry::checkFaceWeights(), primitiveMeshGeometry::checkFaceWeights(), polyMeshGeometry::checkVolRatio(), cellDistFuncs::correctBoundaryFaceCells(), decompositionMethod::decompose(), faMesh::faceCells(), primitiveMeshTools::faceOrthogonality(), mappedPatchBase::facePoint(), primitiveMeshTools::facePyramidVolume(), polyMeshTools::faceSkewness(), primitiveMeshTools::faceSkewness(), tetIndices::faceTriIs(), polyMeshTools::faceWeights(), polyMeshTetDecomposition::findBasePoint(), polyMeshTetDecomposition::findFaceBasePts(), polyMeshTetDecomposition::findSharedBasePoint(), cellPointWeight::findTriangle(), sampledSet::getBoundaryCell(), sampledSet::getNeighbourCell(), cellCellStencil::globalCellCells(), FreeStream< CloudType >::inflow(), cellToCellStencil::insertFaceCells(), cellToFaceStencil::insertFaceCells(), prismMatcher::isA(), tetWedgeMatcher::isA(), wedgeMatcher::isA(), highAspectRatioFvGeometryScheme::makeAverageCentres(), primitiveMeshTools::makeCellCentresAndVols(), dynamicRefineFvMesh::mapNewInternalFaces(), Foam::markGrowFaceCellFace(), meshRefinement::markOutsideFaces(), degenerateMatcher::match(), hexMatcher::matches(), prismMatcher::matches(), pyrMatcher::matches(), tetMatcher::matches(), tetWedgeMatcher::matches(), wedgeMatcher::matches(), meshRefinement::mergePatchFaces(), polyMeshAdder::mergePoints(), polyMeshTetDecomposition::minQuality(), edgeFaceCirculator::operator++(), sampledSet::pointInCell(), sampledSet::pushIn(), undoableMeshCutter::removeSplitFaces(), SloanRenumber::renumber(), sampledFaceZone::sampleOnPoints(), sampledPatch::sampleOnPoints(), edgeFaceCirculator::setCanonical(), meshCutter::setRefinement(), perfectInterface::setRefinement(), meshCutAndRemove::setRefinement(), Foam::sumNeighbours(), wallBoundedParticle::trackToEdge(), tetIndices::triIs(), primitiveMeshTools::updateCellCentresAndVols(), and polyMeshTools::volRatio().
faceNeighbour()
const Foam::labelList & faceNeighbour () const virtual
Implements primitiveMesh.
Definition at line 1117 of file polyMesh.C.
Referenced by polyMeshAdder::add(), addPatchCellLayer::addedCells(), polyTopoChange::addMesh(), polyMeshTetDecomposition::adjustTetBasePtIs(), polyMeshGeometry::affectedCells(), decompositionMethod::calcCellCells(), decompositionMethod::calcCellCells(), dynamicRefineFvMesh::calculateProtectedCells(), primitiveMeshTools::cellClosedness(), edgeFaceCirculator::cellLabel(), polyMeshGeometry::checkFaceDotProduct(), primitiveMeshGeometry::checkFaceDotProduct(), polyMeshGeometry::checkFacePyramids(), primitiveMeshGeometry::checkFacePyramids(), polyMeshGeometry::checkFaceSkewness(), primitiveMeshGeometry::checkFaceSkewness(), polyMeshGeometry::checkFaceTets(), polyMeshTetDecomposition::checkFaceTets(), polyMeshGeometry::checkFaceTwist(), polyMeshGeometry::checkFaceWeights(), primitiveMeshGeometry::checkFaceWeights(), polyMeshGeometry::checkVolRatio(), decompositionMethod::decompose(), primitiveMeshTools::faceOrthogonality(), primitiveMeshTools::facePyramidVolume(), polyMeshTools::faceSkewness(), primitiveMeshTools::faceSkewness(), polyMeshTools::faceWeights(), polyMeshTetDecomposition::findSharedBasePoint(), sampledSet::getNeighbourCell(), cellCellStencil::globalCellCells(), cellToCellStencil::insertFaceCells(), cellToFaceStencil::insertFaceCells(), highAspectRatioFvGeometryScheme::makeAverageCentres(), primitiveMeshTools::makeCellCentresAndVols(), dynamicRefineFvMesh::mapNewInternalFaces(), Foam::markGrowFaceCellFace(), meshRefinement::markOutsideFaces(), polyMeshAdder::mergePoints(), polyMeshTetDecomposition::minQuality(), edgeFaceCirculator::operator++(), undoableMeshCutter::removeSplitFaces(), SloanRenumber::renumber(), edgeFaceCirculator::setCanonical(), meshCutter::setRefinement(), perfectInterface::setRefinement(), meshCutAndRemove::setRefinement(), Foam::sumNeighbours(), wallBoundedParticle::trackToEdge(), and polyMeshTools::volRatio().
oldPoints()
const Foam::pointField & oldPoints () const virtual
Implements primitiveMesh.
Definition at line 1123 of file polyMesh.C.
References Foam::endl(), and WarningInFunction.
Referenced by tetIndices::oldFaceTri(), tetIndices::oldTet(), and movingWallVelocityFvPatchVectorField::Uwall().
oldCellCentres()
const Foam::pointField & oldCellCentres () const virtual
Definition at line 1145 of file polyMesh.C.
Referenced by tetIndices::oldTet().
boundaryMesh()
const polyBoundaryMesh & boundaryMesh () const inline noexcept
Definition at line 452 of file polyMesh.H.
Referenced by fvMeshAdder::add(), polyMeshAdder::add(), snappyRefineDriver::addFaceZones(), snappyLayerDriver::addLayers(), polyTopoChange::addMesh(), meshRefinement::addPatch(), oversetFvPatchField< Type >::adjustPsi(), cellToCellStencil::allCoupledFacesPatch(), cellToFaceStencil::allCoupledFacesPatch(), temperatureCoupledBase::alpha(), meshRefinement::appendPatch(), assemblyFaceAreaPairGAMGAgglomeration::assemblyFaceAreaPairGAMGAgglomeration(), FreeStream< CloudType >::autoMap(), decompositionMethod::calcCellCells(), decompositionMethod::calcCellCells(), addPatchCellLayer::calcExtrudeInfo(), polyDualMesh::calcFeatures(), snappySnapDriver::calcNearestSurface(), polyTopoChange::changeMesh(), polyTopoChange::changeMesh(), polyMeshGeometry::checkFaceDotProduct(), polyMeshGeometry::checkFaceSkewness(), polyMeshGeometry::checkFaceTets(), polyMeshTetDecomposition::checkFaceTets(), polyMeshGeometry::checkFaceTwist(), polyMeshGeometry::checkFaceWeights(), faceZone::checkParallelSync(), polyMeshGeometry::checkVolRatio(), adjointBoundaryCondition< Type >::computePatchGrad(), wallDistData< TransferType >::correct(), inverseFaceDistanceDiffusivity::correct(), inversePointDistanceDiffusivity::correct(), cellDistFuncs::correctBoundaryFaceCells(), cellDistFuncs::correctBoundaryPointCells(), Foam::createReconstructMap(), Foam::createZeroBoundaryPointFieldPtr(), structuredDecomp::decompose(), decompositionMethod::decompose(), snappyLayerDriver::doLayers(), polyMeshTools::faceSkewness(), polyMeshTools::faceWeights(), localPointRegion::findDuplicateFacePairs(), polyMeshTetDecomposition::findFaceBasePts(), pointBoundaryMesh::findPatchID(), syncTools::getInternalOrCoupledFaces(), syncTools::getInternalOrMasterFaces(), syncTools::getMasterFaces(), externalDisplacementMeshMover::getPatch(), cellDistFuncs::getPatchIDs(), hexCellFvMesh::hexCellFvMesh(), DSMCParcel< ParcelType >::hitWallPatch(), fvBoundaryMesh::indices(), pointBoundaryMesh::indices(), fvBoundaryMesh::indices(), pointBoundaryMesh::indices(), FreeStream< CloudType >::inflow(), SurfaceFilmModel< CloudType >::inject(), SurfaceFilmModel< CloudType >::injectParticles(), temperatureCoupledBase::kappa(), highAspectRatioFvGeometryScheme::makeAverageCentres(), polyTopoChange::makeMesh(), polyTopoChange::makeMesh(), meshRefinement::makePatch(), cellDistFuncs::maxPatchSize(), meshRefinement::mergePatchFaces(), polyMeshAdder::mergePoints(), meshReader::mesh(), fvMeshTools::newMesh(), faceShading::nonCoupledPatches(), polyMeshAdder::patchFacePairs(), sampledPatch::patchIDs(), boundaryMesh::patchify(), boundaryMesh::read(), fvMeshTools::removeEmptyPatches(), structuredRenumber::renumber(), SloanRenumber::renumber(), fvMeshTools::reorderPatches(), snappySnapDriver::repatchToSurface(), sampledFaceZone::sampleOnPoints(), sampledPatch::sampleOnPoints(), sampledPatchInternalField::sampleOnPoints(), displacementMethodelasticityMotionSolver::setMotionField(), patchInjectionBase::setPositionAndCell(), perfectInterface::setRefinement(), meshCutAndRemove::setRefinement(), perfectInterface::setRefinement(), fvMatrix< Type >::setValuesFromList(), shapeOptimisation::shapeOptimisation(), oversetFvPatchField< Type >::storeFringeCoefficients(), Foam::sumNeighbours(), cellDistFuncs::sumPatchSize(), mappedPatchBase::surfPtr(), syncTools::swapBoundaryCellList(), syncTools::syncBoundaryFaceList(), syncTools::syncEdgeMap(), syncTools::syncFaceList(), syncTools::syncPointMap(), sampledFaceZone::update(), sampledPatch::update(), attachDetach::updateMesh(), perfectInterface::updateMesh(), slidingInterface::updateMesh(), patchInjectionBase::updateMesh(), mappedPatchBase::updateMeshTime(), cellToCellStencil::validBoundaryFaces(), cellToFaceStencil::validBoundaryFaces(), polyMeshTools::volRatio(), fvMeshTools::writeProcAddressing(), lumpedPointMovement::writeVTP(), and lumpedPointMovement::writeZonesVTP().
bounds()
const boundBox & bounds () const inline noexcept
Definition at line 458 of file polyMesh.H.
Referenced by cuttingSurfaceBase::cellSelection(), refinementParameters::findCells(), streamLineParticle::move(), and sampledMeshedSurface::update().
geometricD()
const Foam::Vector< Foam::label > & geometricD () const
Definition at line 860 of file polyMesh.C.
Referenced by FitData< FitDataType, ExtendedStencil, Polynomial >::findFaceDirs().
nGeometricD()
Foam::label nGeometricD () const
Definition at line 871 of file polyMesh.C.
References Foam::cmptSum().
Referenced by FitData< FitDataType, ExtendedStencil, Polynomial >::findFaceDirs(), and inverseDistance::update().
solutionD()
const Foam::Vector< Foam::label > & solutionD () const
Definition at line 877 of file polyMesh.C.
Referenced by KinematicParcel< ParcelType >::calcVelocity(), InjectionModel< CloudType >::inject(), InjectionModel< CloudType >::injectSteadyState(), KinematicSurfaceFilm< CloudType >::splashInteraction(), and fvMesh::validComponents().
nSolutionD()
Foam::label nSolutionD () const
Definition at line 888 of file polyMesh.C.
References Foam::cmptSum().
Referenced by get_mesh_dim().
tetBasePtIs()
const Foam::labelIOList & tetBasePtIs () const
Definition at line 894 of file polyMesh.C.
References Foam::endl(), polyMeshTetDecomposition::findFaceBasePts(), IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, and WarningInFunction.
Referenced by polyMeshTetDecomposition::adjustTetBasePtIs(), wallBoundedParticle::crossEdgeConnectedFace(), mappedPatchBase::facePoint(), mappedPatchBase::facePoints(), tetIndices::faceTriIs(), meshRefinement::findCell(), refinementParameters::findCells(), meshRefinement::findRegion(), Foam::readLagrangian(), and tetIndices::triIs().
cellTree()
const Foam::indexedOctree< Foam::treeDataCell > & cellTree () const
Definition at line 934 of file polyMesh.C.
References e, points, and rndGen.
Referenced by mappedPatchBase::findLocalSamples(), and tetOverlapVolume::overlappingCells().
pointZones() [1/2]
const pointZoneMesh & pointZones () const inline noexcept
Definition at line 488 of file polyMesh.H.
Referenced by fvMeshAdder::add(), polyMeshAdder::add(), polyTopoChange::addMesh(), polyTopoChange::changeMesh(), polyTopoChange::makeMesh(), slidingInterface::modifyMotionPoints(), fvMeshTools::newMesh(), fvMeshDistribute::printMeshInfo(), and slidingInterface::updateMesh().
faceZones() [1/2]
const faceZoneMesh & faceZones () const inline noexcept
Definition at line 494 of file polyMesh.H.
Referenced by fvMeshAdder::add(), polyMeshAdder::add(), cyclicAMIPolyPatch::addAMIFaces(), surfaceZonesInfo::addFaceZone(), surfaceZonesInfo::addFaceZonesToMesh(), snappyLayerDriver::addLayers(), polyTopoChange::addMesh(), polyTopoChange::changeMesh(), layerAdditionRemoval::changeTopology(), meshRefinement::checkCoupledFaceZones(), snappyLayerDriver::doLayers(), snappySnapDriver::doSnap(), polyTopoChange::makeMesh(), polyMeshAdder::mergePoints(), slidingInterface::modifyMotionPoints(), fvMeshTools::newMesh(), RemoveParcels< CloudType >::postEvolve(), fvMeshDistribute::printMeshInfo(), snappySnapDriver::repatchToSurface(), perfectInterface::setRefinement(), meshRefinement::subsetBaffles(), sampledFaceZone::update(), attachDetach::updateMesh(), perfectInterface::updateMesh(), slidingInterface::updateMesh(), FaceInteraction< CloudType >::write(), FacePostProcessing< CloudType >::write(), and sampledFaceZone::zoneIDs().
cellZones() [1/2]
const cellZoneMesh & cellZones () const inline noexcept
Definition at line 500 of file polyMesh.H.
Referenced by fvMeshAdder::add(), polyMeshAdder::add(), surfaceZonesInfo::addCellZone(), cellTable::addCellZones(), surfaceZonesInfo::addCellZonesToMesh(), polyTopoChange::addMesh(), cuttingSurfaceBase::cellSelection(), polyTopoChange::changeMesh(), polyTopoChange::makeMesh(), fvMeshTools::newMesh(), cellTable::operator=(), fvMeshDistribute::printMeshInfo(), displacementLayeredMotionMotionSolver::solve(), and CellZoneInjection< CloudType >::updateMesh().
globalData()
const Foam::globalMeshData & globalData () const
Definition at line 1300 of file polyMesh.C.
References Foam::endl(), and Foam::Pout.
Referenced by addPatchCellLayer::calcExtrudeInfo(), faBoundaryMesh::calcGeometry(), structuredDecomp::decompose(), decompositionMethod::decompose(), PatchTools::edgeNormals(), polyMeshAdder::findSharedPoints(), faMeshTools::forceDemandDriven(), PatchTools::gatherAndMerge(), syncTools::getMasterEdges(), syncTools::getMasterPoints(), wallPointAddressing::leaveDomain(), faBoundaryMesh::movePoints(), pointBoundaryMesh::movePoints(), polyBoundaryMesh::movePoints(), faMeshTools::newMesh(), structuredRenumber::renumber(), zoltanRenumber::renumber(), motionSmootherAlgo::setDisplacement(), syncTools::syncEdgeList(), syncTools::syncEdgeList(), syncTools::syncEdgeList(), syncTools::syncEdgeMap(), syncTools::syncPointList(), syncTools::syncPointList(), syncTools::syncPointList(), syncTools::syncPointMap(), wallPointAddressing::updateCell(), wallPointAddressing::updateFace(), wallPointAddressing::updateFace(), faBoundaryMesh::updateMesh(), pointBoundaryMesh::updateMesh(), polyBoundaryMesh::updateMesh(), and FacePostProcessing< CloudType >::write().
comm() [1/2]
Foam::label comm () const noexcept
Definition at line 1318 of file polyMesh.C.
Referenced by fvMesh::comm().
comm() [2/2]
Foam::label & comm () noexcept
Definition at line 1324 of file polyMesh.C.
thisDb()
const objectRegistry & thisDb () const inline noexcept
Definition at line 515 of file polyMesh.H.
Referenced by fvMesh::thisDb().
dynamic()
virtual bool dynamic () const inline virtual
Reimplemented in dynamicFvMesh, staticFvMesh, and engineMesh.
Definition at line 524 of file polyMesh.H.
moving() [1/2]
bool moving () const inline noexcept
Definition at line 530 of file polyMesh.H.
Referenced by snappyLayerDriver::addLayers(), snappyLayerDriver::addLayers(), backwardDdtScheme< Type >::backwardDdtScheme(), polyMesh::changing(), meshRefinement::mergePatchFaces(), and movingWallVelocityFvPatchVectorField::updateCoeffs().
moving() [2/2]
bool moving (const bool on) inline noexcept
Definition at line 536 of file polyMesh.H.
topoChanging() [1/2]
bool topoChanging () const inline noexcept
Definition at line 544 of file polyMesh.H.
Referenced by polyTopoChange::changeMesh(), and polyMesh::changing().
topoChanging() [2/2]
bool topoChanging (const bool on) inline noexcept
Definition at line 550 of file polyMesh.H.
changing()
bool changing () const inline noexcept
Definition at line 558 of file polyMesh.H.
References polyMesh::moving(), and polyMesh::topoChanging().
Referenced by epsilonWallFunctionFvPatchScalarField::createAveragingWeights(), and omegaWallFunctionFvPatchScalarField::createAveragingWeights().
movePoints()
void movePoints (const pointField & newPoints) virtual
Reimplemented in fvMesh.
Definition at line 1163 of file polyMesh.C.
References IOobjectOption::AUTO_WRITE, DebugInFunction, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::Info, InfoInFunction, primitiveMesh::movePoints(), Foam::nl, UPtrList< T >::size(), UList< T >::size(), timeIndex, regIOobject::write(), and Foam::Zero.
Referenced by fvMesh::movePoints().
resetMotion()
void resetMotion () const
Definition at line 1292 of file polyMesh.C.
References PtrList< T >::clear().
pointZones() [2/2]
pointZoneMesh & pointZones () inline noexcept
Definition at line 573 of file polyMesh.H.
faceZones() [2/2]
faceZoneMesh & faceZones () inline noexcept
Definition at line 579 of file polyMesh.H.
cellZones() [2/2]
cellZoneMesh & cellZones () inline noexcept
Definition at line 585 of file polyMesh.H.
addPatches() [1/2]
void addPatches (polyPatchList & plist, const bool validBoundary = true)
Definition at line 965 of file polyMesh.C.
References Foam::abort(), PtrList< T >::clear(), Foam::FatalError, FatalErrorInFunction, PtrList< T >::transfer(), and Foam::Zero.
Referenced by polyMeshAdder::add(), and meshReader::mesh().
addPatches() [2/2]
void addPatches (const List< polyPatch * > & p, const bool validBoundary = true)
Definition at line 1043 of file polyMesh.C.
References p.
addZones() [1/2]
void addZones (PtrList< pointZone > && pz, PtrList< faceZone > && fz, PtrList< cellZone > && cz)
Definition at line 1003 of file polyMesh.C.
References Foam::abort(), IOobjectOption::AUTO_WRITE, Foam::FatalError, FatalErrorInFunction, and UPtrList< T >::size().
Referenced by fvMeshTools::newMesh().
addZones() [2/2]
void addZones (const List< pointZone * > & pz, const List< faceZone * > & fz, const List< cellZone * > & cz)
Definition at line 1056 of file polyMesh.C.
init()
bool init (const bool doInit) virtual
Reimplemented from primitiveMesh.
Reimplemented in interfaceTrackingFvMesh, dynamicFvMesh, dynamicMotionSolverFvMesh, dynamicMotionSolverFvMeshAMI, dynamicMotionSolverListFvMesh, dynamicMultiMotionSolverFvMesh, dynamicRefineFvMesh, fvMesh, dynamicMotionSolverTopoFvMesh, and movingConeTopoFvMesh.
Definition at line 359 of file polyMesh.C.
References primitiveMesh::init().
Referenced by fvMesh::init(), and polyMesh::polyMesh().
readUpdate()
Foam::polyMesh::readUpdateState readUpdate () virtual
Reimplemented in fvMesh.
Definition at line 68 of file polyMeshIO.C.
References cells, DebugInFunction, Foam::endl(), forAll, Foam::Info, IOobjectOption::MUST_READ, Foam::name(), Foam::nl, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, polyMesh::POINTS_MOVED, IOobjectOption::READ_IF_PRESENT, PtrList< T >::set(), PtrList< T >::setSize(), UPtrList< T >::size(), polyMesh::TOPO_CHANGE, polyMesh::TOPO_PATCH_CHANGE, polyMesh::UNCHANGED, WarningInFunction, and Foam::Zero.
Referenced by fvMesh::readUpdate().
updateMesh()
void updateMesh (const mapPolyMesh & mpm) virtual
Reimplemented in fvMesh.
Definition at line 36 of file polyMeshUpdate.C.
References primitiveMesh::cellCentres(), PtrList< T >::clear(), ZoneMesh< ZoneType, MeshType >::clearAddressing(), DebugInFunction, Foam::endl(), forAll, newPointi, PtrList< T >::resize(), polyMesh::setInstance(), HashTable< regIOobject * >::size(), UList< T >::size(), objectRegistry::time(), timeName, polyBoundaryMesh::updateMesh(), and Foam::Zero.
Referenced by fvMesh::updateMesh().
removeBoundary()
void removeBoundary ()
Definition at line 32 of file polyMeshClear.C.
References polyBoundaryMesh::clear(), polyMesh::clearOut(), DebugInFunction, and Foam::endl().
Referenced by fvMesh::removeFvBoundary().
resetPrimitives()
void resetPrimitives (autoPtr< pointField > && points, autoPtr< faceList > && faces, autoPtr< labelList > && owner, autoPtr< labelList > && neighbour, const labelUList & patchSizes, const labelUList & patchStarts, const bool validBoundary = true)
Definition at line 709 of file polyMesh.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::max(), Foam::min(), nPoints, points, Foam::returnReduceAnd(), UPtrList< T >::size(), and timeName.
Referenced by polyTopoChange::changeMesh().
clearGeom()
void clearGeom ()
Definition at line 44 of file polyMeshClear.C.
References PtrList< T >::clear(), primitiveMesh::clearGeom(), DebugInFunction, Foam::endl(), and Foam::Zero.
updateGeomPoints()
void updateGeomPoints (pointIOField && newPoints, autoPtr< labelIOList > & newTetBasePtIsPtr)
Definition at line 65 of file polyMeshClear.C.
References PtrList< T >::clear(), primitiveMesh::clearGeom(), meshObject::clearUpto(), DebugInFunction, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, UPtrList< T >::size(), PtrList< T >::transfer(), and Foam::Zero.
clearAddressing()
void clearAddressing (const bool isMeshUpdate = false)
Definition at line 143 of file polyMeshClear.C.
References PtrList< T >::clear(), primitiveMesh::clearAddressing(), meshObject::clearUpto(), DebugInFunction, Foam::endl(), and Foam::Zero.
clearOut()
void clearOut ()
Definition at line 213 of file polyMeshClear.C.
Referenced by fvMesh::clearOut(), and polyMesh::removeBoundary().
clearPrimitives()
void clearPrimitives ()
Definition at line 200 of file polyMeshClear.C.
clearTetBasePtIs()
void clearTetBasePtIs ()
Definition at line 220 of file polyMeshClear.C.
References DebugInFunction, and Foam::endl().
clearCellTree()
void clearCellTree ()
Definition at line 228 of file polyMeshClear.C.
References DebugInFunction, and Foam::endl().
removeFiles() [1/2]
void removeFiles (const fileName & instanceDir) const
Definition at line 1330 of file polyMesh.C.
References Foam::isDir(), Foam::rm(), and Foam::rmDir().
Referenced by meshReader::writeMesh().
removeFiles() [2/2]
void removeFiles () const
Definition at line 1354 of file polyMesh.C.
hasTetBasePtIs()
bool hasTetBasePtIs () const inline
Definition at line 687 of file polyMesh.H.
checkFaceOrthogonality()
bool checkFaceOrthogonality (const bool report = false, labelHashSet * setPtr = nullptr) const virtual
Reimplemented from primitiveMesh.
Definition at line 633 of file polyMeshCheck.C.
checkFaceSkewness()
bool checkFaceSkewness (const bool report = false, labelHashSet * setPtr = nullptr) const virtual
Reimplemented from primitiveMesh.
Definition at line 650 of file polyMeshCheck.C.
References points.
checkEdgeAlignment()
bool checkEdgeAlignment (const bool report, const Vector< label > & directions, labelHashSet * setPtr) const virtual
Definition at line 669 of file polyMeshCheck.C.
References points.
checkCellDeterminant()
bool checkCellDeterminant (const bool report, labelHashSet * setPtr) const virtual
Definition at line 686 of file polyMeshCheck.C.
checkMeshMotion()
bool checkMeshMotion (const pointField & newPoints, const bool report = false, const bool detailedReport = false) const virtual
Definition at line 732 of file polyMeshCheck.C.
References cellVols, Foam::endl(), primitiveMeshTools::makeCellCentresAndVols(), primitiveMeshTools::makeFaceCentresAndAreas(), and Foam::Pout.
checkFaceWeight()
bool checkFaceWeight (const bool report, const scalar minWeight = 0.05, labelHashSet * setPtr = nullptr) const virtual
Definition at line 702 of file polyMeshCheck.C.
checkVolRatio()
bool checkVolRatio (const bool report, const scalar minRatio = 0.01, labelHashSet * setPtr = nullptr) const virtual
Definition at line 721 of file polyMeshCheck.C.
findCellFacePt()
void findCellFacePt (const point & p, label & celli, label & tetFacei, label & tetPti) const
Definition at line 1360 of file polyMesh.C.
References p, and tree().
Referenced by patchInjectionBase::setPositionAndCell().
findTetFacePt()
void findTetFacePt (const label celli, const point & p, label & tetFacei, label & tetPti) const
Definition at line 1385 of file polyMesh.C.
References tetIndices::face(), polyMeshTetDecomposition::findTet(), mesh, p, and tetIndices::tetPt().
Referenced by sampledSet::pushIn(), and patchInjectionBase::setPositionAndCell().
pointInCell()
bool pointInCell (const point & p, label celli, const cellDecomposition decompMode = CELL_TETS) const
Definition at line 1401 of file polyMesh.C.
References triangle< Point, PointRef >::areaNormal(), cells, triangle< Point, PointRef >::centre(), f(), forAll, p, primitiveMesh::pointInCell(), points, and UList< T >::size().
findCell()
Foam::label findCell (const point & p, const cellDecomposition decompMode = CELL_TETS) const
Definition at line 1511 of file polyMesh.C.
References p, and UPstream::parRun().
Referenced by meshRefinement::findCell(), refinementParameters::findCells(), probes::findElements(), meshRefinement::findRegion(), and sampledSet::getTrackingPoint().
Member Data Documentation
defaultRegion
Foam::word defaultRegion = "region0" static
Definition at line 317 of file polyMesh.H.
Referenced by regIOobject::checkIn(), externalCoupled::compositeName(), polyBoundaryMesh::findPatchID(), meshReader::mesh(), FIREMeshReader::mesh(), reader::mesh(), dynamicFvMesh::New(), polyMesh::regionName(), setRegistry(), fvMatrix< Type >::solver(), fvMatrix< Type >::solveSegregatedOrCoupled(), and volFieldValue::writeValues().
meshSubDir
Foam::word meshSubDir = "polyMesh" static
Definition at line 320 of file polyMesh.H.
Referenced by refinementHistory::add(), refinementHistory::apply(), componentDisplacementMotionSolver::componentDisplacementMotionSolver(), faMeshDecomposition::decomposeMesh(), faMeshReconstructor::faMeshReconstructor(), topoSet::findIOobject(), topoSet::findIOobject(), topoSet::localPath(), solidBodyMotionDisplacementPointPatchVectorField::localPoints0(), fvMesh::makeSf(), fvMeshTools::newMesh(), points0MotionSolver::points0IO(), points0MotionSolver::points0MotionSolver(), polyMesh::polyMesh(), fvMeshTools::readProcAddressing(), processorMeshes::reconstructPoints(), hexRef8::removeFiles(), refinementHistory::removeFiles(), meshRefinement::removeFiles(), topoSet::removeFiles(), processorMeshes::removeFiles(), shapeOptimisation::updateDesignVariables(), fvExprDriver::updateSet(), faMeshDecomposition::writeDecomposition(), fvMeshTools::writeProcAddressing(), and cellCellStencil::zoneID().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/polyMesh.H
src/OpenFOAM/meshes/polyMesh/polyMesh.C
src/OpenFOAM/meshes/polyMesh/polyMeshCheck/polyMeshCheck.C
src/OpenFOAM/meshes/polyMesh/polyMeshClear.C
src/OpenFOAM/meshes/polyMesh/polyMeshFromShapeMesh.C
src/OpenFOAM/meshes/polyMesh/polyMeshInitMesh.C
src/OpenFOAM/meshes/polyMesh/polyMeshIO.C
src/OpenFOAM/meshes/polyMesh/polyMeshUpdate.C