OpenFOAM: distributedDICPreconditioner Class Reference
distributedDICPreconditioner Class Reference
Numerics » Matrix manipulation and solvers » Preconditioners
Version of DICpreconditioner that uses preconditioning across processor (and coupled) boundaries. Based on 'Parallel Preconditioners' chapter from 'Iterative Methods for Sparse Linear Systems' by Yousef Saad.
#include <distributedDICPreconditioner.H>
Public Member Functions
TypeName ("distributedDIC")
distributedDICPreconditioner (const lduMatrix::solver &, const dictionary &solverControlsUnused)
virtual ~distributedDICPreconditioner ()=default
Public Member Functions inherited from distributedDILUPreconditioner
TypeName ("distributedDILU")
distributedDILUPreconditioner (const lduMatrix::solver &, const dictionary &solverControlsUnused)
virtual ~distributedDILUPreconditioner ()
virtual void precondition (solveScalarField &wA, const solveScalarField &rA, const direction cmpt=0) const
virtual void setFinished (const solverPerformance &perf) const
Public Member Functions inherited from lduMatrix::preconditioner
virtual const word & type () const =0
declareRunTimeSelectionTable (autoPtr, preconditioner, symMatrix,(const solver &sol, const dictionary &solverControls),(sol, solverControls))
declareRunTimeSelectionTable (autoPtr, preconditioner, asymMatrix,(const solver &sol, const dictionary &solverControls),(sol, solverControls))
preconditioner (const solver &sol)
virtual ~preconditioner ()=default
virtual void read (const dictionary &)
virtual void preconditionT (solveScalarField &wT, const solveScalarField &rT, const direction cmpt=0) const
Protected Member Functions
virtual void forwardInternalDiag (solveScalarField &rD, const label colouri) const
virtual void forwardInternal (solveScalarField &wA, const label colouri) const
Protected Member Functions inherited from distributedDILUPreconditioner
void updateMatrixInterfaces (const bool add, const FieldField< Field, scalar > &coupleCoeffs, const labelList &selectedInterfaces, const solveScalarField &psiif, solveScalarField &result, const direction cmpt) const
void sendGlobal (const labelList &selectedInterfaces, solveScalarField &psi, const label colouri) const
void receive (const labelList &selectedInterfaces, DynamicList< UPstream::Request > &requests) const
void send (const labelList &selectedInterfaces, const solveScalarField &psiInternal, DynamicList< UPstream::Request > &requests) const
void wait (DynamicList< UPstream::Request > &requests, const bool cancel=false) const
virtual void addInterfaceDiag (solveScalarField &rD, const label inti, const Field< solveScalar > &recvBuf) const
virtual void addInterface (solveScalarField &wA, const label inti, const Field< solveScalar > &recvBuf) const
virtual void backwardInternal (solveScalarField &wA, const label colouri) const
virtual void calcReciprocalD (solveScalarField &rD) const
Additional Inherited Members
Static Public Member Functions inherited from lduMatrix::preconditioner
static word getName (const dictionary &)
static autoPtr< preconditioner > New (const solver &sol, const dictionary &solverControls)
Protected Attributes inherited from distributedDILUPreconditioner
const bool coupled_
FieldField< Field, solveScalar > sendBufs_
FieldField< Field, solveScalar > recvBufs_
DynamicList< UPstream::Request > recvRequests_
DynamicList< label > lowerNbrs_
DynamicList< UPstream::Request > lowerSendRequests_
DynamicList< UPstream::Request > lowerRecvRequests_
DynamicList< label > higherNbrs_
DynamicList< UPstream::Request > higherSendRequests_
DynamicList< UPstream::Request > higherRecvRequests_
autoPtr< labelList > cellColourPtr_
label nColours_
PtrList< FieldField< Field, solveScalar > > colourBufs_
List< DynamicList< label > > lowerGlobalRecv_
List< DynamicList< label > > lowerGlobalSend_
List< label > lowerColour_
List< DynamicList< label > > higherGlobalRecv_
List< DynamicList< label > > higherGlobalSend_
List< label > higherColour_
solveScalarField rD_
Protected Attributes inherited from lduMatrix::preconditioner
const solver & solver_
Static Protected Attributes inherited from distributedDILUPreconditioner
static const lduMesh * meshPtr_ = nullptr
static autoPtr< labelList > procColoursPtr_
Detailed Description
Version of DICpreconditioner that uses preconditioning across processor (and coupled) boundaries. Based on 'Parallel Preconditioners' chapter from 'Iterative Methods for Sparse Linear Systems' by Yousef Saad.
Leaves out the handling of boundary nodes after internal nodes since probably not beneficial (so no overlap of comms and internal calculation)
By default preconditions across coupled boundaries (currently only tested for cyclicAMI). This can be disabled with the 'coupled' setting
solver PCG; preconditioner { preconditioner distributedDIC; coupled false; }
The cyclicAMI boundary behaviour will only work if
running non-parallel or
different sides of cyclicAMI run on different processors i.e. there is no processor which has cells on both owner and neighbour of the patch pair.
See also
Foam::DICPreconditioner Foam::distributedDILUPreconditioner
Source files
distributedDICPreconditioner.H
distributedDICPreconditioner.C
Definition at line 74 of file distributedDICPreconditioner.H.
Constructor & Destructor Documentation
distributedDICPreconditioner()
distributedDICPreconditioner (const lduMatrix::solver & sol, const dictionary & solverControlsUnused)
Definition at line 118 of file distributedDICPreconditioner.C.
~distributedDICPreconditioner()
virtual ~distributedDICPreconditioner () virtual default
Member Function Documentation
forwardInternalDiag()
void forwardInternalDiag (solveScalarField & rD, const label colouri) const protected virtual
Reimplemented from distributedDILUPreconditioner.
Definition at line 37 of file distributedDICPreconditioner.C.
References UPtrList< T >::begin(), distributedDILUPreconditioner::cellColourPtr_, UPtrList< T >::size(), and lduMatrix::preconditioner::solver_.
forwardInternal()
void forwardInternal (solveScalarField & wA, const label colouri) const protected virtual
Reimplemented from distributedDILUPreconditioner.
Definition at line 75 of file distributedDICPreconditioner.C.
References UPtrList< T >::begin(), and UPtrList< T >::size().
TypeName()
TypeName ("distributedDIC")
The documentation for this class was generated from the following files:
src/meshTools/matrices/lduMatrix/preconditioners/distributedDILUPreconditioner/distributedDICPreconditioner.H
src/meshTools/matrices/lduMatrix/preconditioners/distributedDILUPreconditioner/distributedDICPreconditioner.C