OpenFOAM: adjointFarFieldTMVar1FvPatchScalarField Class Reference
adjointFarFieldTMVar1FvPatchScalarField Class Reference
#include <adjointFarFieldTMVar1FvPatchScalarField.H>
Public Member Functions
TypeName ("adjointFarFieldTMVar1")
adjointFarFieldTMVar1FvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
adjointFarFieldTMVar1FvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
adjointFarFieldTMVar1FvPatchScalarField (const adjointFarFieldTMVar1FvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
virtual tmp< fvPatchScalarField > clone () const
adjointFarFieldTMVar1FvPatchScalarField (const adjointFarFieldTMVar1FvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual void updateCoeffs ()
virtual tmp< Field< scalar > > valueInternalCoeffs (const tmp< scalarField > &) const
virtual tmp< Field< scalar > > valueBoundaryCoeffs (const tmp< scalarField > &) const
virtual void write (Ostream &) const
Public Member Functions inherited from adjointBoundaryCondition< Type >
TypeName ("adjointBoundaryCondition")
adjointBoundaryCondition (const fvPatch &p, const DimensionedField< Type, volMesh > &iF, const word &solverName)
adjointBoundaryCondition (const adjointBoundaryCondition< Type > &)
virtual ~adjointBoundaryCondition ()=default
const word & objectiveManagerName () const
const word & adjointSolverName () const
const word & simulationType () const
void setBoundaryContributionPtr ()
boundaryAdjointContribution & getBoundaryAdjContribution ()
const ATCModel & getATC () const
virtual tmp< Field< typename Foam::outerProduct< Foam::vector, Type >::type > > dxdbMult () const
virtual void updatePrimalBasedQuantities ()
Additional Inherited Members
Protected Member Functions inherited from adjointBoundaryCondition< Type >
template<class Type2 >
tmp< Field< typename Foam::outerProduct< Foam::vector, Type2 >::type > > computePatchGrad (word name)
bool addATCUaGradUTerm ()
Protected Attributes inherited from adjointBoundaryCondition< Type >
const fvPatch & patch_
word managerName_
word adjointSolverName_
word simulationType_
autoPtr< boundaryAdjointContribution > boundaryContrPtr_
Switch addATCUaGradUTerm_
Detailed Description
Source files
adjointFarFieldTMVar1FvPatchScalarField.H
adjointFarFieldTMVar1FvPatchScalarField.C
Definition at line 48 of file adjointFarFieldTMVar1FvPatchScalarField.H.
Constructor & Destructor Documentation
adjointFarFieldTMVar1FvPatchScalarField() [1/4]
adjointFarFieldTMVar1FvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 35 of file adjointFarFieldTMVar1FvPatchScalarField.C.
adjointFarFieldTMVar1FvPatchScalarField() [2/4]
adjointFarFieldTMVar1FvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 61 of file adjointFarFieldTMVar1FvPatchScalarField.C.
References dict, and IOobjectOption::MUST_READ.
adjointFarFieldTMVar1FvPatchScalarField() [3/4]
adjointFarFieldTMVar1FvPatchScalarField (const adjointFarFieldTMVar1FvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 47 of file adjointFarFieldTMVar1FvPatchScalarField.C.
adjointFarFieldTMVar1FvPatchScalarField() [4/4]
adjointFarFieldTMVar1FvPatchScalarField (const adjointFarFieldTMVar1FvPatchScalarField & tppsf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 76 of file adjointFarFieldTMVar1FvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("adjointFarFieldTMVar1")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 87 of file adjointFarFieldTMVar1FvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 103 of file adjointFarFieldTMVar1FvPatchScalarField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 90 of file adjointFarFieldTMVar1FvPatchScalarField.C.
References adjointBoundaryCondition< Type >::boundaryContrPtr_, delta, and Foam::pos().
valueInternalCoeffs()
tmp< Field< scalar > > valueInternalCoeffs (const tmp< scalarField > &) const virtual
Definition at line 122 of file adjointFarFieldTMVar1FvPatchScalarField.C.
References adjointBoundaryCondition< Type >::boundaryContrPtr_, Foam::neg(), and Foam::New().
valueBoundaryCoeffs()
tmp< Field< scalar > > valueBoundaryCoeffs (const tmp< scalarField > &) const virtual
Definition at line 135 of file adjointFarFieldTMVar1FvPatchScalarField.C.
References adjointBoundaryCondition< Type >::boundaryContrPtr_, Foam::New(), and Foam::pos().
write()
void write (Ostream & os) const virtual
Definition at line 148 of file adjointFarFieldTMVar1FvPatchScalarField.C.
References adjointBoundaryCondition< Type >::adjointSolverName_, os(), fvPatchField< Type >::write(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/turbulenceModels/incompressibleAdjoint/adjointRAS/derivedFvPatchFields/adjointFarFieldTMVar1/adjointFarFieldTMVar1FvPatchScalarField.H
src/optimisation/adjointOptimisation/adjoint/turbulenceModels/incompressibleAdjoint/adjointRAS/derivedFvPatchFields/adjointFarFieldTMVar1/adjointFarFieldTMVar1FvPatchScalarField.C