OpenFOAM: decompositionConstraint Class Reference
decompositionConstraint Class Reference abstract
Abstract class for handling decomposition constraints.
#include <decompositionConstraint.H>
Public Member Functions
TypeName ("decompositionConstraint")
declareRunTimeSelectionTable (autoPtr, decompositionConstraint, dictionary,(const dictionary &dict),(dict))
decompositionConstraint (const dictionary &constraintDict)
decompositionConstraint (const dictionary &constraintDict, const word &modelType)
virtual ~decompositionConstraint ()=default
virtual void add (const polyMesh &mesh, boolList &blockedFace, PtrList< labelList > &specifiedProcessorFaces, labelList &specifiedProcessor, List< labelPair > &explicitConnections) const =0
virtual void apply (const polyMesh &mesh, const boolList &blockedFace, const PtrList< labelList > &specifiedProcessorFaces, const labelList &specifiedProcessor, const List< labelPair > &explicitConnections, labelList &decomposition) const
Static Public Member Functions
static autoPtr< decompositionConstraint > New (const dictionary &constraintDict)
static autoPtr< decompositionConstraint > New (const dictionary &constraintDict, const word &modelType)
Protected Member Functions
void getMinBoundaryValue (const polyMesh &mesh, const labelList &decomposition, labelList &destProc) const
decompositionConstraint (const decompositionConstraint &)=delete
void operator= (const decompositionConstraint &)=delete
Protected Attributes
dictionary coeffDict_
Detailed Description
Abstract class for handling decomposition constraints.
Source files
decompositionConstraint.H
decompositionConstraint.C
Definition at line 54 of file decompositionConstraint.H.
Constructor & Destructor Documentation
decompositionConstraint() [1/3]
decompositionConstraint (const decompositionConstraint &) protected delete
decompositionConstraint() [2/3]
decompositionConstraint (const dictionary & constraintDict) explicit
Definition at line 125 of file decompositionConstraint.C.
decompositionConstraint() [3/3]
decompositionConstraint (const dictionary & constraintDict, const word & modelType)
Definition at line 134 of file decompositionConstraint.C.
~decompositionConstraint()
virtual ~decompositionConstraint () virtual default
Member Function Documentation
getMinBoundaryValue()
void getMinBoundaryValue (const polyMesh & mesh, const labelList & decomposition, labelList & destProc) const protected
Definition at line 37 of file decompositionConstraint.C.
References fld(), forAll, Foam::labelMax, mesh, Foam::min(), pbm, pp(), PtrList< T >::setSize(), and syncTools::syncBoundaryFaceList().
operator=()
void operator= (const decompositionConstraint &) protected delete
TypeName()
TypeName ("decompositionConstraint")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , decompositionConstraint , dictionary , (const dictionary &dict) , (dict))
New() [1/2]
Foam::autoPtr< Foam::decompositionConstraint > New (const dictionary & constraintDict) static
Definition at line 147 of file decompositionConstraint.C.
References dict, dictionary::get(), and decompositionConstraint::New().
Referenced by decompositionConstraint::New().
New() [2/2]
Foam::autoPtr< Foam::decompositionConstraint > New (const dictionary & constraintDict, const word & modelType) static
Definition at line 161 of file decompositionConstraint.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, and Foam::Info.
add()
virtual void add (const polyMesh & mesh, boolList & blockedFace, PtrList< labelList > & specifiedProcessorFaces, labelList & specifiedProcessor, List< labelPair > & explicitConnections) const pure virtual
Implemented in geometric, preserveBaffles, preserveFaceZones, preservePatches, refinementHistory, and singleProcessorFaceSets.
apply()
virtual void apply (const polyMesh & mesh, const boolList & blockedFace, const PtrList< labelList > & specifiedProcessorFaces, const labelList & specifiedProcessor, const List< labelPair > & explicitConnections, labelList & decomposition) const inline virtual
Reimplemented in preserveBaffles, preserveFaceZones, preservePatches, refinementHistory, and singleProcessorFaceSets.
Definition at line 151 of file decompositionConstraint.H.
Member Data Documentation
coeffDict_
dictionary coeffDict_ protected
Definition at line 61 of file decompositionConstraint.H.
The documentation for this class was generated from the following files:
src/parallel/decompose/decompositionMethods/decompositionConstraints/decompositionConstraint/decompositionConstraint.H
src/parallel/decompose/decompositionMethods/decompositionConstraints/decompositionConstraint/decompositionConstraint.C