OpenFOAM: indexedCell< Gt, Cb > Class Template Reference
indexedCell< Gt, Cb > Class Template Reference
An indexed form of CGAL::Triangulation_cell_base_3<K> used to keep track of the Delaunay cells (tets) in the tessellation.
#include <indexedCell.H>
Classes
struct Rebind_TDS
Public Types
typedef Cb::Triangulation_data_structure Tds
typedef Cb::Vertex_handle Vertex_handle
typedef Cb::Cell_handle Cell_handle
Public Types inherited from indexedCellEnum
enum cellTypes {
ctUnassigned = INT_MIN , ctFar = INT_MIN + 1 , ctInternal = INT_MIN + 2 , ctSurface = INT_MIN + 3 ,
ctFeatureEdge = INT_MIN + 4 , ctFeaturePoint = INT_MIN + 5
}
Public Member Functions
indexedCell ()
indexedCell (Vertex_handle v0, Vertex_handle v1, Vertex_handle v2, Vertex_handle v3)
indexedCell (Vertex_handle v0, Vertex_handle v1, Vertex_handle v2, Vertex_handle v3, Cell_handle n0, Cell_handle n1, Cell_handle n2, Cell_handle n3)
Foam::label & cellIndex ()
Foam::label cellIndex () const
const Foam::point dual ()
bool unassigned () const
int & filterCount ()
int filterCount () const
bool real () const
bool hasFarPoint () const
bool hasReferredPoint () const
bool hasFeaturePoint () const
bool hasSeedPoint () const
bool hasInternalPoint () const
bool hasBoundaryPoint () const
bool hasConstrainedPoint () const
bool parallelDualVertex () const
Foam::label vertexLowestProc () const
Foam::tetCell vertexGlobalIndices (const Foam::globalIndex &globalDelaunayVertexIndices) const
Foam::FixedList< Foam::label, 4 > globallyOrderedCellVertices (const Foam::globalIndex &globalDelaunayVertexIndices) const
bool internalOrBoundaryDualVertex () const
bool anyInternalOrBoundaryDualVertex () const
bool boundaryDualVertex () const
bool baffleSurfaceDualVertex () const
bool baffleEdgeDualVertex () const
bool featureEdgeDualVertex () const
bool featurePointDualVertex () const
bool nearProcBoundary () const
bool potentialCoplanarCell () const
bool featurePointExternalCell () const
bool featurePointInternalCell () const
Foam::InfoProxy< indexedCell< Gt, Cb > > info () const noexcept
Friends
Foam::Ostream & Foam::operator (Foam::Ostream &, const Foam::InfoProxy< indexedCell< Gt, Cb > > &)
Additional Inherited Members
Static Public Attributes inherited from indexedCellEnum
static const Enum< cellTypes > cellTypesNames_
Detailed Description
template<class Gt, class Cb = CGAL::Delaunay_triangulation_cell_base_with_circumcenter_3<Gt>>
class CGAL::indexedCell< Gt, Cb >
An indexed form of CGAL::Triangulation_cell_base_3<K> used to keep track of the Delaunay cells (tets) in the tessellation.
Source files
indexedCell.H
indexedCellI.H
indexedCell.C
Definition at line 88 of file indexedCell.H.
Member Typedef Documentation
Tds
template<class Gt , class Cb = CGAL::Delaunay_triangulation_cell_base_with_circumcenter_3<Gt>> typedef Cb::Triangulation_data_structure Tds
Definition at line 121 of file indexedCell.H.
Vertex_handle
template<class Gt , class Cb = CGAL::Delaunay_triangulation_cell_base_with_circumcenter_3<Gt>> typedef Cb::Vertex_handle Vertex_handle
Definition at line 122 of file indexedCell.H.
Cell_handle
template<class Gt , class Cb = CGAL::Delaunay_triangulation_cell_base_with_circumcenter_3<Gt>> typedef Cb::Cell_handle Cell_handle
Definition at line 123 of file indexedCell.H.
Constructor & Destructor Documentation
indexedCell() [1/3]
template<class Gt , class Cb > indexedCell () inline
Definition at line 49 of file indexedCellI.H.
indexedCell() [2/3]
template<class Gt , class Cb > indexedCell (Vertex_handle v0, Vertex_handle v1, Vertex_handle v2, Vertex_handle v3) inline
Definition at line 58 of file indexedCellI.H.
indexedCell() [3/3]
template<class Gt , class Cb > indexedCell (Vertex_handle v0, Vertex_handle v1, Vertex_handle v2, Vertex_handle v3, Cell_handle n0, Cell_handle n1, Cell_handle n2, Cell_handle n3) inline
Definition at line 70 of file indexedCellI.H.
Member Function Documentation
cellIndex() [1/2]
template<class Gt , class Cb > Foam::label & cellIndex () inline
Definition at line 91 of file indexedCellI.H.
cellIndex() [2/2]
template<class Gt , class Cb > Foam::label cellIndex () const inline
Definition at line 98 of file indexedCellI.H.
dual()
template<class Gt , class Cb > const Foam::point dual () inline
Definition at line 115 of file indexedCellI.H.
unassigned()
template<class Gt , class Cb > bool unassigned () const inline
Definition at line 131 of file indexedCellI.H.
filterCount() [1/2]
template<class Gt , class Cb > int & filterCount () inline
Definition at line 138 of file indexedCellI.H.
filterCount() [2/2]
template<class Gt , class Cb > int filterCount () const inline
Definition at line 145 of file indexedCellI.H.
real()
template<class Gt , class Cb > bool real () const inline
Definition at line 152 of file indexedCellI.H.
hasFarPoint()
template<class Gt , class Cb > bool hasFarPoint () const inline
Definition at line 174 of file indexedCellI.H.
hasReferredPoint()
template<class Gt , class Cb > bool hasReferredPoint () const inline
Definition at line 187 of file indexedCellI.H.
hasFeaturePoint()
template<class Gt , class Cb > bool hasFeaturePoint () const inline
Definition at line 200 of file indexedCellI.H.
hasSeedPoint()
template<class Gt , class Cb > bool hasSeedPoint () const inline
Definition at line 213 of file indexedCellI.H.
hasInternalPoint()
template<class Gt , class Cb > bool hasInternalPoint () const inline
Definition at line 226 of file indexedCellI.H.
hasBoundaryPoint()
template<class Gt , class Cb > bool hasBoundaryPoint () const inline
Definition at line 239 of file indexedCellI.H.
hasConstrainedPoint()
template<class Gt , class Cb > bool hasConstrainedPoint () const inline
Definition at line 252 of file indexedCellI.H.
parallelDualVertex()
template<class Gt , class Cb > bool parallelDualVertex () const inline
Definition at line 265 of file indexedCellI.H.
vertexLowestProc()
template<class Gt , class Cb > Foam::label vertexLowestProc () const inline
Definition at line 289 of file indexedCellI.H.
vertexGlobalIndices()
template<class Gt , class Cb > Foam::tetCell vertexGlobalIndices (const Foam::globalIndex & globalDelaunayVertexIndices) const inline
Definition at line 306 of file indexedCellI.H.
References FixedList< T, N >::size().
globallyOrderedCellVertices()
template<class Gt , class Cb > Foam::FixedList< Foam::label, 4 > globallyOrderedCellVertices (const Foam::globalIndex & globalDelaunayVertexIndices) const inline
Definition at line 333 of file indexedCellI.H.
References Foam::identity(), and FixedList< T, N >::size().
internalOrBoundaryDualVertex()
template<class Gt , class Cb > bool internalOrBoundaryDualVertex () const inline
Definition at line 367 of file indexedCellI.H.
anyInternalOrBoundaryDualVertex()
template<class Gt , class Cb > bool anyInternalOrBoundaryDualVertex () const inline
Definition at line 380 of file indexedCellI.H.
boundaryDualVertex()
template<class Gt , class Cb > bool boundaryDualVertex () const inline
Definition at line 397 of file indexedCellI.H.
baffleSurfaceDualVertex()
template<class Gt , class Cb > bool baffleSurfaceDualVertex () const inline
Definition at line 440 of file indexedCellI.H.
baffleEdgeDualVertex()
template<class Gt , class Cb > bool baffleEdgeDualVertex () const inline
Definition at line 461 of file indexedCellI.H.
featureEdgeDualVertex()
template<class Gt , class Cb > bool featureEdgeDualVertex () const inline
Definition at line 482 of file indexedCellI.H.
featurePointDualVertex()
template<class Gt , class Cb > bool featurePointDualVertex () const inline
Definition at line 520 of file indexedCellI.H.
nearProcBoundary()
template<class Gt , class Cb > bool nearProcBoundary () const inline
Definition at line 533 of file indexedCellI.H.
potentialCoplanarCell()
template<class Gt , class Cb > bool potentialCoplanarCell () const inline
Definition at line 546 of file indexedCellI.H.
References Foam::vectorTools::areParallel(), Foam::endl(), Foam::Pout, and Foam::Zero.
featurePointExternalCell()
template<class Gt , class Cb > bool featurePointExternalCell () const inline
Definition at line 636 of file indexedCellI.H.
featurePointInternalCell()
template<class Gt , class Cb > bool featurePointInternalCell () const inline
Definition at line 698 of file indexedCellI.H.
info()
template<class Gt , class Cb = CGAL::Delaunay_triangulation_cell_base_with_circumcenter_3<Gt>> Foam::InfoProxy< indexedCell< Gt, Cb > > info () const inline noexcept
Definition at line 249 of file indexedCell.H.
Friends And Related Symbol Documentation
Foam::operator
template<class Gt , class Cb = CGAL::Delaunay_triangulation_cell_base_with_circumcenter_3<Gt>> Foam::Ostream & Foam::operator (Foam::Ostream & , const Foam::InfoProxy< indexedCell< Gt, Cb > > &) friend
The documentation for this class was generated from the following files:
applications/utilities/mesh/generation/foamyMesh/conformalVoronoiMesh/conformalVoronoiMesh/indexedCell/indexedCell.H
applications/utilities/mesh/generation/foamyMesh/conformalVoronoiMesh/conformalVoronoiMesh/indexedCell/indexedCellI.H