OpenFOAM: cellMatcher Class Reference
cellMatcher Class Reference abstract
Base class for cellshape matchers (hexMatch, prismMatch, etc.). These are classes which given a mesh and cell number find out the orientation of the cellShape and construct cell-vertex to mesh-vertex mapping and cell-face to mesh-face mapping.
#include <cellMatcher.H>
Public Member Functions
cellMatcher (const label vertPerCell, const label facePerCell, const label maxVertPerFace, const word &cellModelName)
virtual ~cellMatcher ()=default
const Map< label > & localPoint () const
const faceList & localFaces () const
const labelList & faceSize () const
const labelList & pointMap () const
const labelList & faceMap () const
const labelList & edgeFaces () const
const labelListList & pointFaceIndex () const
const labelList & vertLabels () const
const labelList & faceLabels () const
const cellModel & model () const
void write (Ostream &os) const
virtual label nVertPerCell () const =0
virtual label nFacePerCell () const =0
virtual label nMaxVertPerFace () const =0
virtual label faceHashValue () const =0
virtual bool faceSizeMatch (const faceList &, const labelList &) const =0
virtual bool matchShape (const bool checkOnly, const faceList &faces, const labelList &faceOwner, const label celli, const labelList &myFaces)=0
virtual bool isA (const primitiveMesh &mesh, const label celli)=0
virtual bool isA (const faceList &)=0
virtual bool matches (const primitiveMesh &mesh, const label celli, cellShape &shape)=0
Protected Member Functions
label calcLocalFaces (const faceList &faces, const labelList &myFaces)
void calcEdgeAddressing (const label numVert)
void calcPointFaceIndex ()
label otherFace (const label numVert, const label v0, const label v1, const label localFacei) const
cellMatcher (const cellMatcher &)=delete
cellMatcher & operator= (const cellMatcher &)=delete
Static Protected Member Functions
static label edgeKey (const label numVert, const label v0, const label v1)
static label nextVert (const label, const label, const bool)
Protected Attributes
Map< label > localPoint_
faceList localFaces_
labelList faceSize_
labelList pointMap_
labelList faceMap_
labelList edgeFaces_
labelListList pointFaceIndex_
labelList vertLabels_
labelList faceLabels_
const word cellModelName_
const cellModel * cellModelPtr_
Detailed Description
Base class for cellshape matchers (hexMatch, prismMatch, etc.). These are classes which given a mesh and cell number find out the orientation of the cellShape and construct cell-vertex to mesh-vertex mapping and cell-face to mesh-face mapping.
For example,
    hexMatcher hex(mesh);
    cellShape shape;
    ..
    bool isHex = hex.match(celli, shape);
Now shape is set to the correct Hex cellShape (if isHex is true)
Alternatively there is direct access to the vertex and face mapping:
    const labelList& hexVertLabels = hex.vertLabels();
    const labelList& hexFaceLabels = hex.faceLabels();
Now
hexVertLabels[n] is vertex label of hex vertex n
hexFaceLabels[n] is face label of hex vertex n
Process of cellShape recognition consists of following steps:
renumber vertices of cell to local vertex numbers
construct (local to cell) addressing edge-to-faces
construct (local to cell) addressing vertex and face to index in face
find most unique face shape (e.g. triangle for prism)
walk (following either vertices in face or jumping from face to other face) to other faces and checking face sizes.
if necessary try other rotations of this face (only necessary for wedge, tet-wedge)
if necessary try other faces which most unique face shape (never necessary for hex degenerates)
The whole calculation is done such that no lists are allocated during cell checking. E.g. localFaces_ are always sized to hold max. number of possible face vertices and a separate list is filled which holds the actusl face sizes.
For now all hex-degenerates implemented. Numbering taken from picture in demoGuide.
Source files
cellMatcher.H
cellMatcherI.H
cellMatcher.C
Definition at line 95 of file cellMatcher.H.
Constructor & Destructor Documentation
cellMatcher() [1/2]
cellMatcher (const cellMatcher &) protected delete
cellMatcher() [2/2]
cellMatcher (const label vertPerCell, const label facePerCell, const label maxVertPerFace, const word & cellModelName)
Definition at line 32 of file cellMatcher.C.
References f(), cellMatcher::localFaces_, cellMatcher::pointFaceIndex_, and PtrList< T >::setSize().
~cellMatcher()
virtual ~cellMatcher () virtual default
Member Function Documentation
edgeKey()
Foam::label edgeKey (const label numVert, const label v0, const label v1) inline static protected
Definition at line 89 of file cellMatcherI.H.
nextVert()
Foam::label nextVert (const label localVertI, const label size, const bool rightHand) inline static protected
Definition at line 101 of file cellMatcherI.H.
calcLocalFaces()
Foam::label calcLocalFaces (const faceList & faces, const labelList & myFaces) protected
Definition at line 66 of file cellMatcher.C.
References PtrList< T >::clear(), f(), forAll, forAllConstIters, UPtrList< T >::size(), and UList< T >::size().
calcEdgeAddressing()
void calcEdgeAddressing (const label numVert) protected
Definition at line 130 of file cellMatcher.C.
References Foam::abort(), f(), Foam::FatalError, FatalErrorInFunction, and forAll.
calcPointFaceIndex()
void calcPointFaceIndex () protected
Definition at line 179 of file cellMatcher.C.
References f(), and forAll.
otherFace()
Foam::label otherFace (const label numVert, const label v0, const label v1, const label localFacei) const protected
Definition at line 205 of file cellMatcher.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
operator=()
cellMatcher & operator= (const cellMatcher &) protected delete
localPoint()
const Foam::Map< Foam::label > & localPoint () const inline
Definition at line 23 of file cellMatcherI.H.
References cellMatcher::localPoint_.
localFaces()
const Foam::faceList & localFaces () const inline
Definition at line 29 of file cellMatcherI.H.
faceSize()
const Foam::labelList & faceSize () const inline
Definition at line 35 of file cellMatcherI.H.
pointMap()
const Foam::labelList & pointMap () const inline
Definition at line 41 of file cellMatcherI.H.
faceMap()
const Foam::labelList & faceMap () const inline
Definition at line 47 of file cellMatcherI.H.
edgeFaces()
const Foam::labelList & edgeFaces () const inline
Definition at line 53 of file cellMatcherI.H.
pointFaceIndex()
const Foam::labelListList & pointFaceIndex () const inline
Definition at line 59 of file cellMatcherI.H.
vertLabels()
const Foam::labelList & vertLabels () const inline
Definition at line 65 of file cellMatcherI.H.
faceLabels()
const Foam::labelList & faceLabels () const inline
Definition at line 71 of file cellMatcherI.H.
model()
const Foam::cellModel & model () const inline
Definition at line 77 of file cellMatcherI.H.
References cellModel::ptr().
write()
void write (Foam::Ostream & os) const
Definition at line 235 of file cellMatcher.C.
References Foam::endl(), forAll, Foam::nl, and os().
nVertPerCell()
virtual label nVertPerCell () const pure virtual
Implemented in hexMatcher, prismMatcher, pyrMatcher, tetMatcher, tetWedgeMatcher, and wedgeMatcher.
nFacePerCell()
virtual label nFacePerCell () const pure virtual
Implemented in hexMatcher, prismMatcher, pyrMatcher, tetMatcher, tetWedgeMatcher, and wedgeMatcher.
nMaxVertPerFace()
virtual label nMaxVertPerFace () const pure virtual
Implemented in hexMatcher, prismMatcher, pyrMatcher, tetMatcher, tetWedgeMatcher, and wedgeMatcher.
faceHashValue()
virtual label faceHashValue () const pure virtual
Implemented in hexMatcher, prismMatcher, pyrMatcher, tetMatcher, tetWedgeMatcher, and wedgeMatcher.
faceSizeMatch()
virtual bool faceSizeMatch (const faceList & , const labelList &) const pure virtual
Implemented in hexMatcher, prismMatcher, pyrMatcher, tetMatcher, tetWedgeMatcher, and wedgeMatcher.
matchShape()
virtual bool matchShape (const bool checkOnly, const faceList & faces, const labelList & faceOwner, const label celli, const labelList & myFaces) pure virtual
Implemented in hexMatcher, prismMatcher, pyrMatcher, tetMatcher, tetWedgeMatcher, and wedgeMatcher.
isA() [1/2]
virtual bool isA (const primitiveMesh & mesh, const label celli) pure virtual
Implemented in hexMatcher, prismMatcher, pyrMatcher, tetMatcher, tetWedgeMatcher, and wedgeMatcher.
isA() [2/2]
virtual bool isA (const faceList &) pure virtual
Implemented in prismMatcher, tetWedgeMatcher, wedgeMatcher, hexMatcher, pyrMatcher, and tetMatcher.
matches()
virtual bool matches (const primitiveMesh & mesh, const label celli, cellShape & shape) pure virtual
Implemented in hexMatcher, prismMatcher, pyrMatcher, tetMatcher, tetWedgeMatcher, and wedgeMatcher.
Member Data Documentation
localPoint_
Map<label> localPoint_ protected
Definition at line 116 of file cellMatcher.H.
Referenced by cellMatcher::localPoint().
localFaces_
faceList localFaces_ protected
Definition at line 119 of file cellMatcher.H.
Referenced by cellMatcher::cellMatcher().
faceSize_
labelList faceSize_ protected
Definition at line 122 of file cellMatcher.H.
pointMap_
labelList pointMap_ protected
Definition at line 125 of file cellMatcher.H.
faceMap_
labelList faceMap_ protected
Definition at line 128 of file cellMatcher.H.
edgeFaces_
labelList edgeFaces_ protected
Definition at line 131 of file cellMatcher.H.
pointFaceIndex_
labelListList pointFaceIndex_ protected
Definition at line 135 of file cellMatcher.H.
Referenced by cellMatcher::cellMatcher().
vertLabels_
labelList vertLabels_ protected
Definition at line 138 of file cellMatcher.H.
faceLabels_
labelList faceLabels_ protected
Definition at line 141 of file cellMatcher.H.
cellModelName_
const word cellModelName_ protected
Definition at line 144 of file cellMatcher.H.
cellModelPtr_
const cellModel* cellModelPtr_ mutable protected
Definition at line 146 of file cellMatcher.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/meshShapes/cellMatcher/cellMatcher.H
src/OpenFOAM/meshes/meshShapes/cellMatcher/cellMatcher.C
src/OpenFOAM/meshes/meshShapes/cellMatcher/cellMatcherI.H