OpenFOAM: binModel Class Reference
binModel Class Reference abstract
Base class for bin models to handle general bin characteristics.
#include <binModel.H>
Public Member Functions
TypeName ("binModel")
declareRunTimeSelectionTable (autoPtr, binModel, dictionary,(const dictionary &dict, const fvMesh &mesh, const word &outputPrefix),(dict, mesh, outputPrefix))
binModel (const dictionary &dict, const fvMesh &mesh, const word &outputPrefix)
binModel (const binModel &)=delete
void operator= (const binModel &)=delete
virtual ~binModel ()=default
virtual bool read (const dictionary &dict)
label nBin () const noexcept
virtual void initialise ()=0
virtual void apply ()=0
virtual void updateMesh (const mapPolyMesh &mpm)
virtual void movePoints (const polyMesh &mesh)
template<>
bool decomposePatchValues (List< List< vector > > &data, const label bini, const vector &v, const vector &n) const
template<>
bool decomposePatchValues (List< List< vector > > &data, const label bini, const vector &v, const vector &n) const
template<class Type >
Foam::string writeComponents (const word &stem) const
Public Member Functions inherited from writeFile
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name="undefined", const bool writeToFile=true)
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name, const dictionary &dict, const bool writeToFile=true)
writeFile (const writeFile &wf)
virtual ~writeFile ()=default
virtual OFstream & file ()
virtual bool writeToFile () const
virtual bool canWriteToFile () const
virtual bool canResetFile () const
virtual bool canWriteHeader () const
virtual label charWidth () const
virtual void writeCommented (Ostream &os, const string &str) const
virtual void writeTabbed (Ostream &os, const string &str) const
virtual void writeHeader (Ostream &os, const string &str) const
virtual void writeCurrentTime (Ostream &os) const
virtual void writeBreak (Ostream &os) const
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
template<class Type >
void writeValue (Ostream &os, const Type &val) const
Static Public Member Functions
static autoPtr< binModel > New (const dictionary &dict, const fvMesh &mesh, const word &outputPrefix)
Protected Member Functions
void setCoordinateSystem (const dictionary &dict, const word &e3Name=word::null, const word &e1Name=word::null)
template<class Type >
bool decomposePatchValues (List< List< Type > > &data, const label bini, const Type &v, const vector &n) const
template<class Type >
string writeComponents (const word &stem) const
template<class Type >
void writeBinnedData (List< List< Type > > &data, Ostream &os) const
Protected Member Functions inherited from writeFile
void initStream (Ostream &os) const
fileName baseFileDir () const
fileName baseTimeDir () const
fileName filePath (const fileName &fName) const
virtual autoPtr< OFstream > newFile (const fileName &fName) const
virtual autoPtr< OFstream > newFileAtTime (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > newFileAtStartTime (const word &name) const
virtual void resetFile (const word &name)
Omanip< int > valueWidth (const label offset=0) const
void operator= (const writeFile &)=delete
virtual autoPtr< OFstream > createFile (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > createFile (const word &name) const
Protected Attributes
const fvMesh & mesh_
bool decomposePatchValues_
bool cumulative_
autoPtr< coordinateSystem > coordSysPtr_
label nBin_
labelHashSet patchSet_
wordList fieldNames_
labelList cellZoneIDs_
PtrList< OFstream > filePtrs_
Protected Attributes inherited from writeFile
const objectRegistry & fileObr_
const fileName prefix_
word fileName_
autoPtr< OFstream > filePtr_
label writePrecision_
bool writeToFile_
bool updateHeader_
bool writtenHeader_
bool useUserTime_
scalar startTime_
Additional Inherited Members
Static Public Attributes inherited from writeFile
static label addChars = 8
Detailed Description
Base class for bin models to handle general bin characteristics.
Source files
binModel.H
binModel.C
binModelNew.C
binModelTemplates.C
Definition at line 57 of file binModel.H.
Constructor & Destructor Documentation
binModel() [1/2]
binModel (const dictionary & dict, const fvMesh & mesh, const word & outputPrefix)
Definition at line 107 of file binModel.C.
binModel() [2/2]
binModel (const binModel &) delete
~binModel()
virtual ~binModel () virtual default
Member Function Documentation
setCoordinateSystem()
void setCoordinateSystem (const dictionary & dict, const word & e3Name = word::null, const word & e1Name = word::null) protected
Definition at line 66 of file binModel.C.
References dict, UPtrList< T >::empty(), Foam::endl(), dictionary::get(), Foam::Info, Foam::nl, dictionary::readIfPresent(), and Foam::Zero.
decomposePatchValues() [1/3]
template<class Type > bool decomposePatchValues (List< List< Type > > & data, const label bini, const Type & v, const vector & n) const protected
Definition at line 24 of file binModelTemplates.C.
References binModel::decomposePatchValues_.
writeComponents() [1/2]
template<class Type > string writeComponents (const word & stem) const protected
writeBinnedData()
template<class Type > void writeBinnedData (List< List< Type > > & data, Ostream & os) const protected
Definition at line 55 of file binModelTemplates.C.
References Foam::endl(), os(), and Foam::Zero.
TypeName()
TypeName ("binModel")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , binModel , dictionary , (const dictionary &dict, const fvMesh &mesh, const word &outputPrefix) , (dict, mesh, outputPrefix))
New()
Foam::autoPtr< Foam::binModel > New (const dictionary & dict, const fvMesh & mesh, const word & outputPrefix) static
Definition at line 26 of file binModelNew.C.
References dict, Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, and mesh.
Referenced by binField::read().
operator=()
void operator= (const binModel &) delete
read()
bool read (const dictionary & dict) virtual
Reimplemented from writeFile.
Reimplemented in singleDirectionUniformBin, and uniformBin.
Definition at line 129 of file binModel.C.
References PtrList< T >::append(), dict, UPtrList< T >::empty(), Foam::endl(), forAll, dictionary::found(), dictionary::get(), dictionary::getOrDefault(), Foam::nl, writeFile::read(), PtrList< T >::set(), UPtrList< T >::size(), WarningInFunction, and zoneIDs.
Referenced by singleDirectionUniformBin::read(), and uniformBin::read().
nBin()
label nBin () const inline noexcept
Definition at line 191 of file binModel.H.
References binModel::nBin_.
initialise()
virtual void initialise () pure virtual
Implemented in singleDirectionUniformBin, and uniformBin.
apply()
virtual void apply () pure virtual
Implemented in singleDirectionUniformBin, and uniformBin.
updateMesh()
void updateMesh (const mapPolyMesh & mpm) virtual
Reimplemented in uniformBin.
Definition at line 182 of file binModel.C.
movePoints()
void movePoints (const polyMesh & mesh) virtual
Reimplemented in uniformBin.
Definition at line 186 of file binModel.C.
decomposePatchValues() [2/3]
template<> bool decomposePatchValues (List< List< vector > > & data, const label bini, const vector & v, const vector & n) const
Definition at line 37 of file binModel.C.
References Foam::abort(), binModel::decomposePatchValues_, Foam::FatalError, FatalErrorInFunction, and n.
decomposePatchValues() [3/3]
template<> bool decomposePatchValues (List< List< vector > > & data, const label bini, const vector & v, const vector & n) const
writeComponents() [2/2]
template<class Type > Foam::string writeComponents (const word & stem) const
Definition at line 37 of file binModelTemplates.C.
Member Data Documentation
mesh_
const fvMesh& mesh_ protected
Definition at line 66 of file binModel.H.
Referenced by singleDirectionUniformBin::initialise(), and uniformBin::initialise().
decomposePatchValues_
bool decomposePatchValues_ protected
Definition at line 69 of file binModel.H.
Referenced by binModel::decomposePatchValues(), binModel::decomposePatchValues(), singleDirectionUniformBin::writeFileHeader(), and uniformBin::writeFileHeader().
cumulative_
bool cumulative_ protected
Definition at line 73 of file binModel.H.
coordSysPtr_
autoPtr<coordinateSystem> coordSysPtr_ protected
Definition at line 76 of file binModel.H.
Referenced by uniformBin::initialise(), and uniformBin::writeFileHeader().
nBin_
label nBin_ protected
Definition at line 79 of file binModel.H.
Referenced by singleDirectionUniformBin::initialise(), binModel::nBin(), singleDirectionUniformBin::writeFileHeader(), and uniformBin::writeFileHeader().
patchSet_
labelHashSet patchSet_ protected
Definition at line 82 of file binModel.H.
Referenced by singleDirectionUniformBin::initialise(), and uniformBin::initialise().
fieldNames_
wordList fieldNames_ protected
Definition at line 85 of file binModel.H.
cellZoneIDs_
labelList cellZoneIDs_ protected
Definition at line 88 of file binModel.H.
Referenced by singleDirectionUniformBin::initialise(), and uniformBin::initialise().
filePtrs_
PtrList<OFstream> filePtrs_ protected
Definition at line 91 of file binModel.H.
The documentation for this class was generated from the following files:
src/functionObjects/field/binField/binModels/binModel/binModel.H
src/functionObjects/field/binField/binModels/binModel/binModel.C
src/functionObjects/field/binField/binModels/binModel/binModelNew.C
src/functionObjects/field/binField/binModels/binModel/binModelTemplates.C