OpenFOAM: LunSavage Class Reference
LunSavage Class Reference
#include <LunSavageRadial.H>
Public Member Functions
TypeName ("LunSavage")
LunSavage (const dictionary &dict)
virtual ~LunSavage ()
tmp< volScalarField > g0 (const volScalarField &alpha, const dimensionedScalar &alphaMinFriction, const dimensionedScalar &alphaMax) const
tmp< volScalarField > g0prime (const volScalarField &alpha, const dimensionedScalar &alphaMinFriction, const dimensionedScalar &alphaMax) const
TypeName ("LunSavage")
LunSavage (const dictionary &dict)
virtual ~LunSavage ()
tmp< volScalarField > g0 (const volScalarField &alpha, const dimensionedScalar &alphaMinFriction, const dimensionedScalar &alphaMax) const
tmp< volScalarField > g0prime (const volScalarField &alpha, const dimensionedScalar &alphaMinFriction, const dimensionedScalar &alphaMax) const
Public Member Functions inherited from radialModel
TypeName ("radialModel")
declareRunTimeSelectionTable (autoPtr, radialModel, dictionary,(const dictionary &dict),(dict))
radialModel (const dictionary &dict)
virtual ~radialModel ()=default
virtual bool read ()
TypeName ("radialModel")
declareRunTimeSelectionTable (autoPtr, radialModel, dictionary,(const dictionary &dict),(dict))
radialModel (const dictionary &dict)
virtual ~radialModel ()=default
virtual bool read ()
Additional Inherited Members
Static Public Member Functions inherited from radialModel
static autoPtr< radialModel > New (const dictionary &dict)
static autoPtr< radialModel > New (const dictionary &dict)
Protected Attributes inherited from radialModel
const dictionary & dict_
Detailed Description
Source files
LunSavageRadial.H
LunSavage.C
Source files
LunSavageRadial.H
LunSavage.C
Definition at line 49 of file LunSavageRadial.H.
Constructor & Destructor Documentation
LunSavage() [1/2]
LunSavage (const dictionary & dict)
Definition at line 47 of file LunSavageRadial.C.
~LunSavage() [1/2]
~LunSavage () virtual
Definition at line 58 of file LunSavageRadial.C.
LunSavage() [2/2]
LunSavage (const dictionary & dict)
~LunSavage() [2/2]
virtual ~LunSavage () virtual
Member Function Documentation
TypeName() [1/2]
TypeName ("LunSavage")
g0() [1/2]
Foam::tmp< Foam::volScalarField > g0 (const volScalarField & alpha, const dimensionedScalar & alphaMinFriction, const dimensionedScalar & alphaMax) const virtual
Implements radialModel.
Definition at line 65 of file LunSavageRadial.C.
References alpha, alphaMax(), and Foam::pow().
g0prime() [1/2]
Foam::tmp< Foam::volScalarField > g0prime (const volScalarField & alpha, const dimensionedScalar & alphaMinFriction, const dimensionedScalar & alphaMax) const virtual
Implements radialModel.
Definition at line 78 of file LunSavageRadial.C.
References alpha, alphaMax(), and Foam::pow().
TypeName() [2/2]
TypeName ("LunSavage")
g0() [2/2]
tmp< volScalarField > g0 (const volScalarField & alpha, const dimensionedScalar & alphaMinFriction, const dimensionedScalar & alphaMax) const virtual
Implements radialModel.
g0prime() [2/2]
tmp< volScalarField > g0prime (const volScalarField & alpha, const dimensionedScalar & alphaMinFriction, const dimensionedScalar & alphaMax) const virtual
Implements radialModel.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/twoPhaseCompressibleTurbulenceModels/kineticTheoryModels/radialModel/LunSavage/LunSavageRadial.H
src/phaseSystemModels/twoPhaseEuler/phaseCompressibleTurbulenceModels/kineticTheoryModels/radialModel/LunSavage/LunSavageRadial.H
src/phaseSystemModels/reactingEuler/twoPhaseCompressibleTurbulenceModels/kineticTheoryModels/radialModel/LunSavage/LunSavageRadial.C
src/phaseSystemModels/twoPhaseEuler/phaseCompressibleTurbulenceModels/kineticTheoryModels/radialModel/LunSavage/LunSavageRadial.C