OpenFOAM: randomCoalescence Class Reference
randomCoalescence Class Reference
Random coalescence IATE source as defined in paper:
#include <randomCoalescence.H>
Public Member Functions
TypeName ("randomCoalescence")
randomCoalescence (const IATE &iate, const dictionary &dict)
virtual ~randomCoalescence ()=default
virtual tmp< fvScalarMatrix > R (const volScalarField &alphai, volScalarField &kappai) const
TypeName ("randomCoalescence")
randomCoalescence (const IATE &iate, const dictionary &dict)
virtual ~randomCoalescence ()=default
virtual tmp< volScalarField > R () const
Public Member Functions inherited from IATEsource
TypeName ("IATEsource")
declareRunTimeSelectionTable (autoPtr, IATEsource, dictionary,(const IATE &iate, const dictionary &dict),(iate, dict))
IATEsource (const IATE &iate)
autoPtr< IATEsource > clone () const
virtual ~IATEsource ()=default
const phaseModel & phase () const
const twoPhaseSystem & fluid () const
const phaseModel & otherPhase () const
scalar phi () const
tmp< volScalarField > Ur () const
tmp< volScalarField > Ut () const
tmp< volScalarField > Re () const
tmp< volScalarField > CD () const
tmp< volScalarField > Mo () const
tmp< volScalarField > Eo () const
tmp< volScalarField > We () const
TypeName ("IATEsource")
declareRunTimeSelectionTable (autoPtr, IATEsource, dictionary,(const IATE &iate, const dictionary &dict),(iate, dict))
IATEsource (const IATE &iate)
autoPtr< IATEsource > clone () const
virtual ~IATEsource ()=default
const phaseModel & phase () const
const twoPhaseSystem & fluid () const
const phaseModel & otherPhase () const
scalar phi () const
tmp< volScalarField > Ur () const
tmp< volScalarField > Ut () const
tmp< volScalarField > Re () const
tmp< volScalarField > CD () const
tmp< volScalarField > Mo () const
tmp< volScalarField > Eo () const
tmp< volScalarField > We () const
Additional Inherited Members
Static Public Member Functions inherited from IATEsource
static autoPtr< IATEsource > New (const word &type, const IATE &iate, const dictionary &dict)
static autoPtr< IATEsource > New (const word &type, const IATE &iate, const dictionary &dict)
Protected Attributes inherited from IATEsource
const IATE & iate_
Detailed Description
Random coalescence IATE source as defined in paper:
Reference:
    Ishii, M., Kim, S., & Kelly, J. (2005).
    Development of interfacial area transport equation.
    Nuclear Engineering and Technology, 37(6), 525-536.
Source files
randomCoalescence.H
randomCoalescence.C
    "Development of Interfacial Area Transport Equation"
    Ishii, M., Kim, S. and Kelly, J.,
    Nuclear Engineering and Technology, Vol.37 No.6 December 2005
Source files
randomCoalescence.H
randomCoalescence.C
Definition at line 59 of file randomCoalescence.H.
Constructor & Destructor Documentation
randomCoalescence() [1/2]
randomCoalescence (const IATE & iate, const dictionary & dict)
Definition at line 42 of file randomCoalescence.C.
References Foam::dimless.
~randomCoalescence() [1/2]
virtual ~randomCoalescence () virtual default
randomCoalescence() [2/2]
randomCoalescence (const IATE & iate, const dictionary & dict)
~randomCoalescence() [2/2]
virtual ~randomCoalescence () virtual default
Member Function Documentation
TypeName() [1/2]
TypeName ("randomCoalescence")
R() [1/2]
Foam::tmp< Foam::fvScalarMatrix > R (const volScalarField & alphai, volScalarField & kappai) const virtual
Implements IATEsource.
Definition at line 59 of file randomCoalescence.C.
References alpha, alphaMax(), Foam::cbrt(), Foam::dimless, Foam::dimTime, Foam::exp(), forAll, phi, R, and Foam::fvm::Sp().
TypeName() [2/2]
TypeName ("randomCoalescence")
R() [2/2]
Foam::tmp< Foam::volScalarField > R () const virtual
Implements IATEsource.
Definition at line 58 of file randomCoalescence.C.
References alpha, alphaMax(), Foam::cbrt(), Foam::dimless, Foam::dimTime, Foam::exp(), forAll, IATEsource::iate_, IATEsource::phase(), IATEsource::phi(), randomCoalescence::R(), IATEsource::Ut(), dimensioned< Type >::value(), and Foam::Zero.
Referenced by randomCoalescence::R().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/twoPhaseSystem/diameterModels/IATE/IATEsources/randomCoalescence/randomCoalescence.H
src/phaseSystemModels/twoPhaseEuler/twoPhaseSystem/diameterModels/IATE/IATEsources/randomCoalescence/randomCoalescence.H
src/phaseSystemModels/reactingEuler/twoPhaseSystem/diameterModels/IATE/IATEsources/randomCoalescence/randomCoalescence.C
src/phaseSystemModels/twoPhaseEuler/twoPhaseSystem/diameterModels/IATE/IATEsources/randomCoalescence/randomCoalescence.C