OpenFOAM: directionInfo Class Reference
directionInfo Class Reference
Holds direction in which to split cell (in fact a local coordinate axes). Information is a label and a direction.
#include <directionInfo.H>
Public Member Functions
directionInfo ()
directionInfo (const label index, const vector &n)
label index () const
const vector & n () const
template<class TrackingData >
bool valid (TrackingData &td) const
template<class TrackingData >
bool sameGeometry (const polyMesh &, const directionInfo &, const scalar, TrackingData &td) const
template<class TrackingData >
void leaveDomain (const polyMesh &, const polyPatch &, const label patchFacei, const point &faceCentre, TrackingData &td)
template<class TrackingData >
void enterDomain (const polyMesh &, const polyPatch &, const label patchFacei, const point &faceCentre, TrackingData &td)
template<class TrackingData >
void transform (const polyMesh &, const tensor &, TrackingData &td)
template<class TrackingData >
bool updateCell (const polyMesh &, const label thisCelli, const label neighbourFacei, const directionInfo &neighbourInfo, const scalar tol, TrackingData &td)
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFacei, const label neighbourCelli, const directionInfo &neighbourInfo, const scalar tol, TrackingData &td)
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFacei, const directionInfo &neighbourInfo, const scalar tol, TrackingData &td)
template<class TrackingData >
bool equal (const directionInfo &, TrackingData &td) const
bool operator== (const directionInfo &) const
bool operator!= (const directionInfo &) const
Static Public Member Functions
static label edgeToFaceIndex (const primitiveMesh &mesh, const label celli, const label facei, const label edgeI)
Friends
Ostream & operator<< (Ostream &, const directionInfo &)
Istream & operator>> (Istream &, directionInfo &)
Detailed Description
Holds direction in which to split cell (in fact a local coordinate axes). Information is a label and a direction.
The direction is the normal direction to cut in. The label's meaning depends on whether the info is on a cell or on a face:
in cell: edge that is being cut. (determines for hex how cut is)
in face: local face point that is being cut or -1.
(-1) : cut is tangential to plane
(>= 0): edge fp..fp+1 is cut
(has to be facepoint, not vertex since vertex not valid across processors whereas f[0] should correspond to f[0] on other side)
The rule is that if the label is set (-1 or higher) it is used (topological information only), otherwise the vector is used. This makes sure that we use topological information as much as possible and so a hex mesh is cut purely topologically. All other shapes are cut geometrically.
Source files
directionInfo.H
directionInfoI.H
directionInfo.C
Definition at line 79 of file directionInfo.H.
Constructor & Destructor Documentation
directionInfo() [1/2]
directionInfo () inline
Definition at line 28 of file directionInfoI.H.
directionInfo() [2/2]
directionInfo (const label index, const vector & n) inline
Definition at line 35 of file directionInfoI.H.
Member Function Documentation
edgeToFaceIndex()
Foam::label edgeToFaceIndex (const primitiveMesh & mesh, const label celli, const label facei, const label edgeI) static
Definition at line 88 of file directionInfo.C.
References Foam::abort(), e, primitiveMesh::edges(), edge::end(), UList< T >::end(), UPtrList< T >::end(), Foam::endl(), f(), polyMesh::faces(), Foam::FatalError, FatalErrorInFunction, UList< T >::find(), Foam::meshTools::getEdgeFaces(), mesh, primitiveMesh::nEdges(), UList< T >::size(), edge::start(), and Foam::meshTools::walkFace().
index()
label index () const inline
Definition at line 142 of file directionInfo.H.
n()
const vector & n () const inline
Definition at line 147 of file directionInfo.H.
valid()
template<class TrackingData > bool valid (TrackingData & td) const inline
Definition at line 49 of file directionInfoI.H.
sameGeometry()
template<class TrackingData > bool sameGeometry (const polyMesh & , const directionInfo & w2, const scalar tol, TrackingData & td) const inline
Definition at line 57 of file directionInfoI.H.
leaveDomain()
template<class TrackingData > void leaveDomain (const polyMesh & , const polyPatch & patch, const label patchFacei, const point & faceCentre, TrackingData & td) inline
Definition at line 71 of file directionInfoI.H.
enterDomain()
template<class TrackingData > void enterDomain (const polyMesh & , const polyPatch & patch, const label patchFacei, const point & faceCentre, TrackingData & td) inline
Definition at line 87 of file directionInfoI.H.
References f(), and UList< T >::size().
transform()
template<class TrackingData > void transform (const polyMesh & , const tensor & rotTensor, TrackingData & td) inline
Definition at line 107 of file directionInfoI.H.
updateCell()
template<class TrackingData > bool updateCell (const polyMesh & mesh, const label thisCelli, const label neighbourFacei, const directionInfo & neighbourInfo, const scalar tol, TrackingData & td) inline
Definition at line 118 of file directionInfoI.H.
References e, primitiveMesh::edges(), f(), primitiveMesh::faceEdges(), polyMesh::faces(), mesh, Foam::meshTools::otherEdge(), Foam::meshTools::otherFace(), UList< T >::size(), and hexMatcher::test().
updateFace() [1/2]
template<class TrackingData > bool updateFace (const polyMesh & mesh, const label thisFacei, const label neighbourCelli, const directionInfo & neighbourInfo, const scalar tol, TrackingData & td) inline
Definition at line 199 of file directionInfoI.H.
References mesh.
updateFace() [2/2]
template<class TrackingData > bool updateFace (const polyMesh & mesh, const label thisFacei, const directionInfo & neighbourInfo, const scalar tol, TrackingData & td) inline
Definition at line 247 of file directionInfoI.H.
equal()
template<class TrackingData > bool equal (const directionInfo & rhs, TrackingData & td) const inline
Definition at line 273 of file directionInfoI.H.
References Foam::operator==().
operator==()
bool operator== (const directionInfo & rhs) const inline
Definition at line 285 of file directionInfoI.H.
operator!=()
bool operator!= (const directionInfo & rhs) const inline
Definition at line 294 of file directionInfoI.H.
Friends And Related Symbol Documentation
operator<<
Ostream & operator<< (Ostream & , const directionInfo &) friend
operator>>
Istream & operator>> (Istream & , directionInfo &) friend
The documentation for this class was generated from the following files:
src/dynamicMesh/meshCut/directions/directionInfo/directionInfo.H
src/dynamicMesh/meshCut/directions/directionInfo/directionInfo.C
src/dynamicMesh/meshCut/directions/directionInfo/directionInfoI.H