OpenFOAM: triSurfaceRegionSearch Class Reference
triSurfaceRegionSearch Class Reference
Helper class to search on triSurface. Creates an octree for each region of the surface and only searches on the specified regions.
#include <triSurfaceRegionSearch.H>
Public Member Functions
triSurfaceRegionSearch (const triSurface &)
triSurfaceRegionSearch (const triSurface &, const dictionary &dict)
~triSurfaceRegionSearch ()
void clearOut ()
const PtrList< treeType > & treeByRegion () const
void findNearest (const pointField &samples, const scalarField &nearestDistSqr, const labelList &regionIndices, List< pointIndexHit > &info) const
Public Member Functions inherited from triSurfaceSearch
triSurfaceSearch (const triSurface &surface)
triSurfaceSearch (const triSurface &surface, const dictionary &dict)
triSurfaceSearch (const triSurface &surface, const scalar tolerance, const label maxTreeDepth=10)
~triSurfaceSearch ()
void clearOut ()
const indexedOctree< treeDataTriSurface > & tree () const
const triSurface & surface () const
scalar tolerance () const
label maxTreeDepth () const
boolList calcInside (const pointField &searchPoints) const
void findNearest (const pointField &samples, const scalarField &nearestDistSqr, List< pointIndexHit > &info) const
pointIndexHit nearest (const point &pt, const vector &span) const
void findLine (const pointField &start, const pointField &end, List< pointIndexHit > &info) const
void findLineAny (const pointField &start, const pointField &end, List< pointIndexHit > &info) const
void findLineAll (const pointField &start, const pointField &end, List< List< pointIndexHit > > &info) const
Detailed Description
Helper class to search on triSurface. Creates an octree for each region of the surface and only searches on the specified regions.
Source files
triSurfaceRegionSearch.H
triSurfaceRegionSearch.C
Definition at line 54 of file triSurfaceRegionSearch.H.
Constructor & Destructor Documentation
triSurfaceRegionSearch() [1/2]
triSurfaceRegionSearch (const triSurface & surface) explicit
Definition at line 29 of file triSurfaceRegionSearch.C.
triSurfaceRegionSearch() [2/2]
triSurfaceRegionSearch (const triSurface & surface, const dictionary & dict)
Definition at line 37 of file triSurfaceRegionSearch.C.
~triSurfaceRegionSearch()
~triSurfaceRegionSearch ()
Definition at line 51 of file triSurfaceRegionSearch.C.
Member Function Documentation
clearOut()
void clearOut ()
Definition at line 57 of file triSurfaceRegionSearch.C.
References triSurfaceSearch::clearOut().
Referenced by triSurfaceMesh::clearOut(), and triSurfaceMesh::movePoints().
treeByRegion()
const Foam::PtrList< Foam::triSurfaceRegionSearch::treeType > & treeByRegion () const
Definition at line 67 of file triSurfaceRegionSearch.C.
References PatchTools::calcBounds(), e, forAll, boundBox::inflate(), Foam::max(), nPoints, points, rndGen, PtrList< T >::set(), PtrList< T >::setSize(), Foam::Zero, and VectorSpace< Form, Cmpt, Ncmpts >::zero.
findNearest()
void findNearest (const pointField & samples, const scalarField & nearestDistSqr, const labelList & regionIndices, List< pointIndexHit > & info) const
Definition at line 179 of file triSurfaceRegionSearch.C.
References UPtrList< T >::empty(), triSurfaceSearch::findNearest(), forAll, samples(), PtrList< T >::setSize(), and UList< T >::size().
Referenced by triSurfaceMesh::findNearest().
The documentation for this class was generated from the following files:
src/meshTools/triSurface/triSurfaceSearch/triSurfaceRegionSearch.H
src/meshTools/triSurface/triSurfaceSearch/triSurfaceRegionSearch.C