OpenFOAM: PtrListDictionary< T > Class Template Reference
PtrListDictionary< T > Class Template Reference
Template dictionary class which manages the storage associated with it.
#include <PtrListDictionary.H>
Public Member Functions
PtrListDictionary (const label size)
PtrListDictionary (const PtrListDictionary &dict)
template<class INew >
PtrListDictionary (Istream &is, const INew &inew)
PtrListDictionary (Istream &is)
autoPtr< T > set (const label i, const word &key, T *ptr)
autoPtr< T > set (const label i, const word &key, autoPtr< T > &aptr)
autoPtr< T > set (const label i, const word &key, tmp< T > &t)
const T & operator[] (const word &key) const
T & operator[] (const word &key)
Public Member Functions inherited from DictionaryBase< PtrList< T >, T >
DictionaryBase (const label size=128)
DictionaryBase (const DictionaryBase &dict)
DictionaryBase (Istream &is, const INew &inew)
DictionaryBase (Istream &is)
bool contains (const word &keyword) const
const T * cfind (const word &keyword) const
T * find (const word &keyword)
const T * lookup (const word &keyword) const
T * lookup (const word &keyword)
wordList toc () const
wordList sortedToc () const
wordList sortedToc (const Compare &comp) const
Foam::wordList sortedToc (const Compare &comp) const
void push_front (const word &keyword, T *ptr)
void push_back (const word &keyword, T *ptr)
T * remove (const word &keyword)
void clear ()
void transfer (DictionaryBase< PtrList< T >, T > &dict)
void operator= (const DictionaryBase &)
const T * operator[] (const word &key) const
T * operator[] (const word &key)
bool found (const word &key) const
const T * lookupPtr (const word &keyword) const
T * lookupPtr (const word &keyword)
void insert (const word &keyword, T *ptr)
void prepend (const word &keyword, T *ptr)
void append (const word &keyword, T *ptr)
Public Member Functions inherited from PtrList< T >
constexpr PtrList () noexcept
PtrList (const label len)
PtrList (const PtrList< T > &list)
PtrList (PtrList< T > &&list)
PtrList (UList< T * > &list)
template<class CloneArg >
PtrList (const PtrList< T > &list, const CloneArg &cloneArgs)
PtrList (PtrList< T > &list, bool reuse)
PtrList (const SLPtrList< T > &list)
template<class INew >
PtrList (Istream &is, const INew &inew)
PtrList (Istream &is)
~PtrList ()
template<class... Args>
PtrList< T > clone (Args &&... args) const
const T * set (const label i) const
void clear ()
void free ()
void resize (const label newLen)
template<class... Args>
T & emplace_back (Args &&... args)
void push_back (T *ptr)
void push_back (std::unique_ptr< T > &&ptr)
void push_back (autoPtr< T > &&ptr)
void push_back (const refPtr< T > &ptr)
void push_back (const tmp< T > &ptr)
void push_back (PtrList< T > &&other)
template<class... Args>
T & emplace_set (const label i, Args &&... args)
template<class... Args>
T & emplace (const label i, Args &&... args)
autoPtr< T > set (const label i, T *ptr)
autoPtr< T > set (const label i, std::unique_ptr< T > &&ptr)
autoPtr< T > set (const label i, autoPtr< T > &&ptr)
autoPtr< T > set (const label i, const refPtr< T > &ptr)
autoPtr< T > set (const label i, const tmp< T > &ptr)
autoPtr< T > release (const label i)
void transfer (PtrList< T > &list)
void operator= (const PtrList< T > &list)
void operator= (PtrList< T > &&list)
void push_back (autoPtr< T > &ptr)=delete
autoPtr< T > set (const label i, autoPtr< T > &ptr)
void setSize (const label newLen)
void append (autoPtr< T > &ptr)
void append (T *ptr)
void append (std::unique_ptr< T > &&ptr)
void append (autoPtr< T > &&ptr)
void append (const refPtr< T > &ptr)
void append (const tmp< T > &ptr)
void append (PtrList< T > &&other)
template<class... Args>
Foam::PtrList< T > clone (Args &&... args) const
Public Member Functions inherited from UPtrList< T >
constexpr UPtrList () noexcept
UPtrList (const label len)
UPtrList (const UPtrList< T > &list)
UPtrList (UPtrList< T > &&list)
UPtrList (UPtrList< T > &list, bool reuse)
UPtrList (PtrList< T > &list)
UPtrList (const UList< T * > &list)
UPtrList (UList< T > &list)
bool empty () const noexcept
label size () const noexcept
label count () const noexcept
T & front ()
const T & front () const
T & back ()
const T & back () const
const T * test (const label i) const
const T * get (const label i) const
T * get (const label i)
const T * set (const label i) const
void clear ()
void free ()
void resize (const label newLen)
label squeezeNull ()
void trimTrailingNull ()
void push_back (T *ptr)
void push_back (UPtrList< T > &&other)
void swap (UPtrList< T > &list)
void transfer (UPtrList< T > &list)
T * set (const label i, T *ptr)
void reorder (const labelUList &oldToNew, const bool check=false)
void sortOrder (const labelUList &order, const bool check=false)
void checkNonNull () const
const T & at (const label i) const
T & at (const label i)
const T & operator[] (const label i) const
T & operator[] (const label i)
FOAM_DEPRECATED_FOR (2022-09, "get(), set() or test() methods") const T *operator()(const label i) const
void operator= (const UPtrList< T > &list)
void operator= (UPtrList< T > &&list)
T ** begin_ptr () noexcept
T ** end_ptr () noexcept
iterator begin ()
iterator end () noexcept
const_iterator cbegin () const
const_iterator cend () const noexcept
const_iterator begin () const
const_iterator end () const noexcept
void setSize (const label n)
T & first ()
const T & first () const
T & last ()
const T & last () const
void append (T *ptr)
void append (UPtrList< T > &&other)
Additional Inherited Members
Public Types inherited from UPtrList< T >
typedef T value_type
typedef T & reference
typedef const T & const_reference
Protected Member Functions inherited from DictionaryBase< PtrList< T >, T >
void addEntries ()
Protected Member Functions inherited from PtrList< T >
template<class INew >
void readIstream (Istream &is, const INew &inew)
Protected Member Functions inherited from UPtrList< T >
void setAddressableSize (const label n) noexcept
label find_next (label pos) const
UPtrList (Detail::PtrListDetail< T > &&ptrs)
Protected Attributes inherited from DictionaryBase< PtrList< T >, T >
HashTable< T * > hashedTs_
Protected Attributes inherited from UPtrList< T >
Detail::PtrListDetail< T > ptrs_
Detailed Description
template<class T>
class Foam::PtrListDictionary< T >
Template dictionary class which manages the storage associated with it.
It is derived from DictionaryBase instantiated on the memory managed PtrList of <T> to provide ordered indexing in addition to the dictionary lookup.
Source files
PtrListDictionary.H
PtrListDictionary.C
Definition at line 51 of file PtrListDictionary.H.
Constructor & Destructor Documentation
PtrListDictionary() [1/4]
template<class T > PtrListDictionary (const label size) explicit
Definition at line 26 of file PtrListDictionary.C.
References PtrList< T >::resize(), and UPtrList< T >::size().
PtrListDictionary() [2/4]
template<class T > PtrListDictionary (const PtrListDictionary< T > & dict)
Definition at line 35 of file PtrListDictionary.C.
PtrListDictionary() [3/4]
template<class T > template<class INew > PtrListDictionary (Istream & is, const INew & inew)
Definition at line 43 of file PtrListDictionary.C.
PtrListDictionary() [4/4]
template<class T > PtrListDictionary (Istream & is) explicit
Definition at line 50 of file PtrListDictionary.C.
Member Function Documentation
set() [1/3]
template<class T > Foam::autoPtr< T > set (const label i, const word & key, T * ptr) inline
Definition at line 59 of file PtrListDictionary.C.
set() [2/3]
template<class T > Foam::autoPtr< T > set (const label i, const word & key, autoPtr< T > & aptr) inline
Definition at line 77 of file PtrListDictionary.C.
set() [3/3]
template<class T > Foam::autoPtr< T > set (const label i, const word & key, tmp< T > & t) inline
Definition at line 96 of file PtrListDictionary.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, insert(), PtrList< T >::set(), and T.
operator[]() [1/2]
template<class T > const T & operator[] (const word & key) const inline
Definition at line 90 of file PtrListDictionary.H.
References DictionaryBase< PtrList< T >, T >::operator, and T.
operator[]() [2/2]
template<class T > T & operator[] (const word & key) inline
Definition at line 96 of file PtrListDictionary.H.
References DictionaryBase< PtrList< T >, T >::operator, and T.
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/Dictionaries/PtrListDictionary/PtrListDictionary.H
src/OpenFOAM/containers/Dictionaries/PtrListDictionary/PtrListDictionary.C