OpenFOAM: fvMeshAdder Class Reference
fvMeshAdder Class Reference
Adds two fvMeshes without using any polyMesh morphing. Uses polyMeshAdder.
#include <fvMeshAdder.H>
Public Member Functions
ClassName ("fvMeshAdder")
Static Public Member Functions
static autoPtr< mapAddedPolyMesh > add (fvMesh &mesh0, const fvMesh &mesh1, const faceCoupleInfo &coupleInfo, const bool validBoundary=true, const bool fullyMapped=false)
template<class Type >
static void MapVolFields (const mapAddedPolyMesh &, const fvMesh &mesh, const fvMesh &meshToAdd, const bool fullyMapped=false)
template<class Type >
static void MapSurfaceFields (const mapAddedPolyMesh &, const fvMesh &mesh, const fvMesh &meshToAdd, const bool fullyMapped=false)
template<class Type >
static void MapDimFields (const mapAddedPolyMesh &, const fvMesh &mesh, const fvMesh &meshToAdd)
static autoPtr< mapPolyMesh > add (const label myProci, UPtrList< fvMesh > &fvMeshes, const labelList &oldFaceOwner, const labelListList &localBoundaryFace, const labelListList &remoteFaceProc, const labelListList &remoteBoundaryFace, labelListList &constructPatchMap, labelListList &constructCellMap, labelListList &constructFaceMap, labelListList &constructPointMap)
template<class Type >
static void MapDimField (UPtrList< DimensionedField< Type, volMesh > > &flds, const labelListList &cellProcAddressing, const bool fullyMapped)
template<class Type >
static void MapVolField (UPtrList< GeometricField< Type, fvPatchField, volMesh > > &flds, const labelList &oldPatchStarts0, const labelList &oldPatchSizes0, const labelListList &patchProcAddressing, const labelListList &cellProcAddressing, const labelListList &faceProcAddressing, const bool fullyMapped)
template<class Type >
static void MapSurfaceField (UPtrList< GeometricField< Type, fvsPatchField, surfaceMesh > > &, const labelList &oldFaceOwner0, const labelList &oldPatchStarts0, const labelList &oldPatchSizes0, const labelListList &patchProcAddressing, const labelListList &cellProcAddressing, const labelListList &faceProcAddressing, const bool fullyMapped)
template<class Type >
static void MapDimFields (const UPtrList< fvMesh > &meshes, const labelListList &cellProcAddressing, const bool fullyMapped=false)
template<class Type >
static void MapVolFields (const UPtrList< fvMesh > &meshes, const labelList &oldPatchStarts0, const labelList &oldPatchSizes0, const labelListList &patchProcAddressing, const labelListList &cellProcAddressing, const labelListList &faceProcAddressing, const labelListList &pointProcAddressing, const bool fullyMapped=false)
template<class Type >
static void MapSurfaceFields (const UPtrList< fvMesh > &meshes, const labelList &oldFaceOwner0, const labelList &oldPatchStarts0, const labelList &oldPatchSizes0, const labelListList &patchProcAddressing, const labelListList &cellProcAddressing, const labelListList &faceProcAddressing, const labelListList &pointProcAddressing, const bool fullyMapped=false)
Static Public Member Functions inherited from polyMeshAdder
static autoPtr< polyMesh > add (const IOobject &io, const polyMesh &mesh0, const polyMesh &mesh1, const faceCoupleInfo &coupleInfo, autoPtr< mapAddedPolyMesh > &mapPtr)
static autoPtr< mapAddedPolyMesh > add (polyMesh &mesh0, const polyMesh &mesh1, const faceCoupleInfo &coupleInfo, const bool validBoundary=true)
static Map< label > findSharedPoints (const polyMesh &, const scalar mergeTol)
static void mergePoints (const polyMesh &, const Map< label > &pointToMaster, polyTopoChange &meshMod)
static label procPatchPairs (const UPtrList< polyMesh > &meshes, List< DynamicList< label > > &localPatch, List< DynamicList< label > > &remoteMesh, List< DynamicList< label > > &remotePatch)
static void patchFacePairs (const UPtrList< polyMesh > &meshes, const List< DynamicList< label > > &localPatch, const List< DynamicList< label > > &remoteMesh, const List< DynamicList< label > > &remotePatch, labelListList &localBoundaryFace, labelListList &remoteFaceMesh, labelListList &remoteBoundaryFace)
static void add (const UPtrList< polyMesh > &meshes, const UList< labelList > &patchMap, const labelListList &localBoundaryFace, const labelListList &remoteFaceMesh, const labelListList &remoteBoundaryFace, const labelListList &remoteFaceStart, const UList< labelList > &pointZoneMap, const UList< labelList > &faceZoneMap, const UList< labelList > &cellZoneMap, polyTopoChange &meshMod, labelListList &cellProcAddressing, labelListList &faceProcAddressing, labelListList &pointProcAddressing)
Detailed Description
Adds two fvMeshes without using any polyMesh morphing. Uses polyMeshAdder.
Source files
fvMeshAdder.H
fvMeshAdder.C
fvMeshAdderTemplates.C
Definition at line 63 of file fvMeshAdder.H.
Member Function Documentation
ClassName()
ClassName ("fvMeshAdder")
add() [1/2]
Foam::autoPtr< Foam::mapAddedPolyMesh > add (fvMesh & mesh0, const fvMesh & mesh1, const faceCoupleInfo & coupleInfo, const bool validBoundary = true, const bool fullyMapped = false) static
Definition at line 66 of file fvMeshAdder.C.
References polyMeshAdder::add(), forAll, fvPatch::New(), patches, PtrList< T >::set(), PtrList< T >::setSize(), and UPtrList< T >::size().
Referenced by fvMeshDistribute::distribute().
MapVolFields() [1/2]
template<class Type > void MapVolFields (const mapAddedPolyMesh & meshMap, const fvMesh & mesh, const fvMesh & meshToAdd, const bool fullyMapped = false) static
Definition at line 258 of file fvMeshAdderTemplates.C.
References DebugPout, Foam::endl(), fields, fld(), forAllIters, mesh, and WarningInFunction.
MapSurfaceFields() [1/2]
template<class Type > void MapSurfaceFields (const mapAddedPolyMesh & meshMap, const fvMesh & mesh, const fvMesh & meshToAdd, const bool fullyMapped = false) static
Definition at line 568 of file fvMeshAdderTemplates.C.
References DebugPout, Foam::endl(), fields, fld(), forAllIters, mesh, and WarningInFunction.
MapDimFields() [1/2]
template<class Type > void MapDimFields (const mapAddedPolyMesh & meshMap, const fvMesh & mesh, const fvMesh & meshToAdd) static
Definition at line 650 of file fvMeshAdderTemplates.C.
References DebugPout, Foam::endl(), fields, fld(), forAllIters, mesh, and WarningInFunction.
add() [2/2]
Foam::autoPtr< Foam::mapPolyMesh > add (const label myProci, UPtrList< fvMesh > & fvMeshes, const labelList & oldFaceOwner, const labelListList & localBoundaryFace, const labelListList & remoteFaceProc, const labelListList & remoteBoundaryFace, labelListList & constructPatchMap, labelListList & constructCellMap, labelListList & constructFaceMap, labelListList & constructPointMap) static
Definition at line 127 of file fvMeshAdder.C.
References polyMeshAdder::add(), polyMesh::boundaryMesh(), polyMesh::cellZones(), polyTopoChange::changeMesh(), Foam::faceMap(), polyMesh::faceZones(), forAll, UPtrList< T >::get(), Foam::identity(), Foam::inplaceRenumber(), mesh, meshes(), primitiveMesh::nCells(), primitiveMesh::nFaces(), nPoints, primitiveMesh::nPoints(), polyMesh::pointZones(), PtrList< T >::set(), polyTopoChange::setCapacity(), PtrList< T >::setSize(), and UPtrList< T >::size().
MapDimField()
template<class Type > void MapDimField (UPtrList< DimensionedField< Type, volMesh > > & flds, const labelListList & cellProcAddressing, const bool fullyMapped) static
Definition at line 700 of file fvMeshAdderTemplates.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, mesh, PtrList< T >::set(), PtrList< T >::setSize(), UPtrList< T >::size(), and UList< T >::size().
MapVolField()
template<class Type > void MapVolField (UPtrList< GeometricField< Type, fvPatchField, volMesh > > & flds, const labelList & oldPatchStarts0, const labelList & oldPatchSizes0, const labelListList & patchProcAddressing, const labelListList & cellProcAddressing, const labelListList & faceProcAddressing, const bool fullyMapped) static
Definition at line 750 of file fvMeshAdderTemplates.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, mesh, PtrList< T >::set(), PtrList< T >::setSize(), UPtrList< T >::size(), and WarningInFunction.
MapSurfaceField()
template<class Type > void MapSurfaceField (UPtrList< GeometricField< Type, fvsPatchField, surfaceMesh > > & flds, const labelList & oldFaceOwner0, const labelList & oldPatchStarts0, const labelList & oldPatchSizes0, const labelListList & patchProcAddressing, const labelListList & cellProcAddressing, const labelListList & faceProcAddressing, const bool fullyMapped) static
Definition at line 885 of file fvMeshAdderTemplates.C.
References Foam::endl(), Foam::exit(), Foam::faceMap(), Foam::FatalError, FatalErrorInFunction, fld(), forAll, PtrList< T >::set(), PtrList< T >::setSize(), UPtrList< T >::size(), and WarningInFunction.
MapDimFields() [2/2]
template<class Type > void MapDimFields (const UPtrList< fvMesh > & meshes, const labelListList & cellProcAddressing, const bool fullyMapped = false) static
Definition at line 1164 of file fvMeshAdderTemplates.C.
References DebugPout, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, fields, fld(), forAll, meshes(), PtrList< T >::set(), and UPtrList< T >::size().
MapVolFields() [2/2]
template<class Type > void MapVolFields (const UPtrList< fvMesh > & meshes, const labelList & oldPatchStarts0, const labelList & oldPatchSizes0, const labelListList & patchProcAddressing, const labelListList & cellProcAddressing, const labelListList & faceProcAddressing, const labelListList & pointProcAddressing, const bool fullyMapped = false) static
Definition at line 1089 of file fvMeshAdderTemplates.C.
References DebugPout, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, fields, fld(), forAll, meshes(), PtrList< T >::set(), and UPtrList< T >::size().
MapSurfaceFields() [2/2]
template<class Type > void MapSurfaceFields (const UPtrList< fvMesh > & meshes, const labelList & oldFaceOwner0, const labelList & oldPatchStarts0, const labelList & oldPatchSizes0, const labelListList & patchProcAddressing, const labelListList & cellProcAddressing, const labelListList & faceProcAddressing, const labelListList & pointProcAddressing, const bool fullyMapped = false) static
Definition at line 1219 of file fvMeshAdderTemplates.C.
References DebugPout, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, fields, fld(), forAll, meshes(), PtrList< T >::set(), and UPtrList< T >::size().
The documentation for this class was generated from the following files:
src/dynamicMesh/fvMeshAdder/fvMeshAdder.H
src/dynamicMesh/fvMeshAdder/fvMeshAdder.C
src/dynamicMesh/fvMeshAdder/fvMeshAdderTemplates.C