OpenFOAM: cutFacePLIC Class Reference
cutFacePLIC Class Reference
Class for cutting a face, faceI, of an fvMesh, mesh_, at its intersection with an plane defined by normal and a base point.
#include <cutFacePLIC.H>
Public Member Functions
cutFacePLIC (const fvMesh &mesh)
label calcSubFace (const label faceI, const vector &normal, const vector &base)
const point & subFaceCentre () const noexcept
const vector & subFaceArea () const noexcept
const DynamicList< point > & subFacePoints () const noexcept
const DynamicList< point > & surfacePoints () const noexcept
void clearStorage ()
Public Member Functions inherited from cutFace
cutFace (const fvMesh &mesh)
Additional Inherited Members
Static Public Attributes inherited from cutFace
static int debug = 0
Protected Member Functions inherited from cutFace
void calcSubFace (const label faceI, const scalarList &pointStatus, label firstFullySubmergedPoint, DynamicList< point > &subFacePoints, DynamicList< point > &surfacePoints, label &faceStatus, vector &subFaceCentre, vector &subFaceArea)
void calcSubFace (const label faceI, const scalarList &pointStatus, const scalarList &weights, label firstFullySubmergedPoint, DynamicList< point > &subFacePoints, DynamicList< point > &surfacePoints, label &faceStatus, vector &subFaceCentre, vector &subFaceArea)
void calcSubFaceCentreAndArea (DynamicList< point > &subFacePoints, vector &subFaceCentre, vector &subFaceArea)
void calcSubFace (const face &f, const pointField &points, const scalarList &pointStatus, label firstFullySubmergedPoint, DynamicList< point > &subFacePoints, DynamicList< point > &surfacePoints, label &faceStatus, vector &subFaceCentre, vector &subFaceArea)
Detailed Description
Class for cutting a face, faceI, of an fvMesh, mesh_, at its intersection with an plane defined by normal and a base point.
Reference:
    Henning Scheufler, Johan Roenby,
    Accurate and efficient surface reconstruction from volume
    fraction data on general meshes,
    Journal of Computational Physics, 2019,
    doi 10.1016/j.jcp.2019.01.009
Original code supplied by Henning Scheufler, DLR (2019)
Source files
cutFacePLIC.H
cutFacePLIC.C
Definition at line 66 of file cutFacePLIC.H.
Constructor & Destructor Documentation
cutFacePLIC()
cutFacePLIC (const fvMesh & mesh) explicit
Definition at line 27 of file cutFacePLIC.C.
References cutFacePLIC::clearStorage().
Member Function Documentation
calcSubFace()
Foam::label calcSubFace (const label faceI, const vector & normal, const vector & base)
Definition at line 45 of file cutFacePLIC.C.
References PtrList< T >::append(), cutFace::calcSubFace(), f(), forAll, Foam::mag(), UList< T >::size(), and Foam::Zero.
subFaceCentre()
const point & subFaceCentre () const inline noexcept
Definition at line 121 of file cutFacePLIC.H.
subFaceArea()
const vector & subFaceArea () const inline noexcept
Definition at line 127 of file cutFacePLIC.H.
subFacePoints()
const DynamicList< point > & subFacePoints () const inline noexcept
Definition at line 133 of file cutFacePLIC.H.
surfacePoints()
const DynamicList< point > & surfacePoints () const inline noexcept
Definition at line 139 of file cutFacePLIC.H.
clearStorage()
void clearStorage ()
Definition at line 111 of file cutFacePLIC.C.
References PtrList< T >::clear(), and Foam::Zero.
Referenced by cutFacePLIC::cutFacePLIC().
The documentation for this class was generated from the following files:
src/transportModels/geometricVoF/cellCuts/cutFace/cutFacePLIC.H
src/transportModels/geometricVoF/cellCuts/cutFace/cutFacePLIC.C