OpenFOAM: pressureInletOutletVelocityFvPatchVectorField Class Reference
pressureInletOutletVelocityFvPatchVectorField Class Reference
Boundary conditions » Inlet | Boundary conditions » Outlet
This velocity inlet/outlet boundary condition is applied to velocity boundaries where the pressure is specified. A zero-gradient condition is applied for outflow (as defined by the flux); for inflow, the velocity is obtained from the patch-face normal component of the internal-cell value.
#include <pressureInletOutletVelocityFvPatchVectorField.H>
Public Member Functions
TypeName ("pressureInletOutletVelocity")
pressureInletOutletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
pressureInletOutletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
pressureInletOutletVelocityFvPatchVectorField (const pressureInletOutletVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
pressureInletOutletVelocityFvPatchVectorField (const pressureInletOutletVelocityFvPatchVectorField &)
virtual tmp< fvPatchVectorField > clone () const
pressureInletOutletVelocityFvPatchVectorField (const pressureInletOutletVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
virtual bool assignable () const
const word & phiName () const
word & phiName ()
const vectorField & tangentialVelocity () const
void setTangentialVelocity (const vectorField &tangentialVelocity)
virtual void autoMap (const fvPatchFieldMapper &)
virtual void rmap (const fvPatchVectorField &, const labelList &)
virtual void updateCoeffs ()
virtual void write (Ostream &) const
virtual void operator= (const fvPatchField< vector > &pvf)
Detailed Description
This velocity inlet/outlet boundary condition is applied to velocity boundaries where the pressure is specified. A zero-gradient condition is applied for outflow (as defined by the flux); for inflow, the velocity is obtained from the patch-face normal component of the internal-cell value.
The tangential patch velocity can be optionally specified.
Usage
Property Description Required Default value
phi flux field name no phi
tangentialVelocity tangential velocity field no
Example of the boundary condition specification:
    <patchName>
    {
        type            pressureInletOutletVelocity;
        phi             phi;
        tangentialVelocity uniform (0 0 0);
        value           uniform (0 0 0);
    }
Note
Sign conventions:
positive flux (out of domain): apply zero-gradient condition
negative flux (into of domain): derive from the flux in the patch-normal direction
Source files
pressureInletOutletVelocityFvPatchVectorField.H
pressureInletOutletVelocityFvPatchVectorField.C
Definition at line 94 of file pressureInletOutletVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
pressureInletOutletVelocityFvPatchVectorField() [1/5]
pressureInletOutletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Definition at line 30 of file pressureInletOutletVelocityFvPatchVectorField.C.
References Foam::Zero.
pressureInletOutletVelocityFvPatchVectorField() [2/5]
pressureInletOutletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Definition at line 65 of file pressureInletOutletVelocityFvPatchVectorField.C.
References dict, IOobjectOption::MUST_READ, p, fvPatchFieldBase::readDict(), pressureInletOutletVelocityFvPatchVectorField::setTangentialVelocity(), and Foam::Zero.
pressureInletOutletVelocityFvPatchVectorField() [3/5]
pressureInletOutletVelocityFvPatchVectorField (const pressureInletOutletVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 46 of file pressureInletOutletVelocityFvPatchVectorField.C.
References UPtrList< T >::size().
pressureInletOutletVelocityFvPatchVectorField() [4/5]
pressureInletOutletVelocityFvPatchVectorField (const pressureInletOutletVelocityFvPatchVectorField & pivpvf)
Definition at line 96 of file pressureInletOutletVelocityFvPatchVectorField.C.
pressureInletOutletVelocityFvPatchVectorField() [5/5]
pressureInletOutletVelocityFvPatchVectorField (const pressureInletOutletVelocityFvPatchVectorField & pivpvf, const DimensionedField< vector, volMesh > & iF)
Definition at line 108 of file pressureInletOutletVelocityFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("pressureInletOutletVelocity")
clone() [1/2]
virtual tmp< fvPatchVectorField > clone () const inline virtual
Reimplemented in rotatingPressureInletOutletVelocityFvPatchVectorField.
Definition at line 147 of file pressureInletOutletVelocityFvPatchVectorField.H.
clone() [2/2]
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Reimplemented in rotatingPressureInletOutletVelocityFvPatchVectorField.
Definition at line 163 of file pressureInletOutletVelocityFvPatchVectorField.H.
assignable()
virtual bool assignable () const inline virtual
Definition at line 178 of file pressureInletOutletVelocityFvPatchVectorField.H.
phiName() [1/2]
const word & phiName () const inline
Definition at line 184 of file pressureInletOutletVelocityFvPatchVectorField.H.
phiName() [2/2]
word & phiName () inline
Definition at line 190 of file pressureInletOutletVelocityFvPatchVectorField.H.
tangentialVelocity()
const vectorField & tangentialVelocity () const inline
Definition at line 196 of file pressureInletOutletVelocityFvPatchVectorField.H.
setTangentialVelocity()
void setTangentialVelocity (const vectorField & tangentialVelocity)
Definition at line 123 of file pressureInletOutletVelocityFvPatchVectorField.C.
References n.
Referenced by pressureInletOutletVelocityFvPatchVectorField::pressureInletOutletVelocityFvPatchVectorField().
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Definition at line 132 of file pressureInletOutletVelocityFvPatchVectorField.C.
rmap()
void rmap (const fvPatchVectorField & ptf, const labelList & addr) virtual
Definition at line 145 of file pressureInletOutletVelocityFvPatchVectorField.C.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 163 of file pressureInletOutletVelocityFvPatchVectorField.C.
References Foam::I, Foam::neg(), and Foam::sqr().
write()
void write (Ostream & os) const virtual
Reimplemented in rotatingPressureInletOutletVelocityFvPatchVectorField.
Definition at line 180 of file pressureInletOutletVelocityFvPatchVectorField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntryIfDifferent(), and fvPatchField< Type >::writeValueEntry().
operator=()
void operator= (const fvPatchField< vector > & pvf) virtual
Definition at line 198 of file pressureInletOutletVelocityFvPatchVectorField.C.
References Foam::I, fvPatchField< Type >::operator=(), and Foam::transform().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/pressureInletOutletVelocity/pressureInletOutletVelocityFvPatchVectorField.H
src/finiteVolume/fields/fvPatchFields/derived/pressureInletOutletVelocity/pressureInletOutletVelocityFvPatchVectorField.C