OpenFOAM: MatrixSpace< Form, Cmpt, Mrows, Ncols > Class Template Reference
MatrixSpace< Form, Cmpt, Mrows, Ncols > Class Template Reference
Templated matrix space.
#include <MatrixSpace.H>
Classes
class Block
class ConstBlock
Public Types
typedef MatrixSpace< Form, Cmpt, Mrows, Ncols > msType
Public Types inherited from VectorSpace< Form, Cmpt, Mrows *Ncols >
typedef VectorSpace< Form, Cmpt, Ncmpts > vsType
typedef Cmpt cmptType
typedef Cmpt magType
typedef Cmpt * iterator
typedef const Cmpt * const_iterator
Public Member Functions
MatrixSpace ()=default
MatrixSpace (const Foam::zero)
template<class Form2 , class Cmpt2 >
MatrixSpace (const VectorSpace< Form2, Cmpt2, Mrows *Ncols > &)
template<template< class, direction, direction > class Block2, direction BRowStart, direction BColStart>
MatrixSpace (const Block2< Form, BRowStart, BColStart > &block)
MatrixSpace (Istream &is)
template<direction Row, direction Col>
const Cmpt & elmt () const noexcept
template<direction Row, direction Col>
Cmpt & elmt () noexcept
const Cmpt & xx () const noexcept
const Cmpt & xy () const noexcept
const Cmpt & xz () const noexcept
const Cmpt & yx () const noexcept
const Cmpt & yy () const noexcept
const Cmpt & yz () const noexcept
const Cmpt & zx () const noexcept
const Cmpt & zy () const noexcept
const Cmpt & zz () const noexcept
Cmpt & xx () noexcept
Cmpt & xy () noexcept
Cmpt & xz () noexcept
Cmpt & yx () noexcept
Cmpt & yy () noexcept
Cmpt & yz () noexcept
Cmpt & zx () noexcept
Cmpt & zy () noexcept
Cmpt & zz () noexcept
typeOfTranspose< Cmpt, Form >::type T () const
template<class SubTensor , direction BRowStart, direction BColStart>
ConstBlock< SubTensor, BRowStart, BColStart > block () const
template<class SubTensor , direction BRowStart, direction BColStart>
Block< SubTensor, BRowStart, BColStart > block ()
const Cmpt & operator() (const direction &i, const direction &j) const
Cmpt & operator() (const direction &i, const direction &j)
void operator= (const Foam::zero)
template<template< class, direction, direction > class Block2, direction BRowStart, direction BColStart>
void operator= (const Block2< Form, BRowStart, BColStart > &block)
template<class Form2 >
void operator&= (const MatrixSpace< Form, Cmpt, Ncols, Ncols > &matrix)
template<class SubTensor , Foam::direction BRowStart, Foam::direction BColStart>
Foam::MatrixSpace< Form, Cmpt, Mrows, Ncols >::template ConstBlock< SubTensor, BRowStart, BColStart > block () const
template<class SubTensor , Foam::direction BRowStart, Foam::direction BColStart>
Foam::MatrixSpace< Form, Cmpt, Mrows, Ncols >::template Block< SubTensor, BRowStart, BColStart > block ()
Public Member Functions inherited from VectorSpace< Form, Cmpt, Mrows *Ncols >
VectorSpace ()=default
VectorSpace (const Foam::zero)
VectorSpace (const VectorSpace< Form, Cmpt, Ncmpts > &vs)
VectorSpace (const VectorSpace< Form2, Cmpt2, Ncmpts > &)
VectorSpace (Istream &is)
const Cmpt & component (const direction) const
Cmpt & component (const direction)
void component (Cmpt &, const direction) const
void replace (const direction, const Cmpt &)
const Cmpt * cdata () const noexcept
Cmpt * data () noexcept
const ConstBlock< SubVector, BStart > block () const
const Foam::VectorSpace< Form, Cmpt, Ncmpts >::template ConstBlock< SubVector, BStart > block () const
const Cmpt & operator[] (const direction) const
Cmpt & operator[] (const direction)
void operator= (const VectorSpace< Form, Cmpt, Ncmpts > &)
void operator= (const Foam::zero)
void operator+= (const VectorSpace< Form, Cmpt, Ncmpts > &)
void operator-= (const VectorSpace< Form, Cmpt, Ncmpts > &)
void operator*= (const scalar)
void operator/= (const scalar)
iterator begin () noexcept
const_iterator begin () const noexcept
iterator end () noexcept
const_iterator end () const noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
Static Public Member Functions
static direction m () noexcept
static direction n () noexcept
static msType identity ()
Static Public Member Functions inherited from VectorSpace< Form, Cmpt, Mrows *Ncols >
static constexpr direction size () noexcept
static Form uniform (const Cmpt &s)
Static Public Attributes
static constexpr direction mRows = Mrows
static constexpr direction nCols = Ncols
Static Public Attributes inherited from VectorSpace< Form, Cmpt, Mrows *Ncols >
static constexpr direction dim
static constexpr direction nComponents
static constexpr direction mRows
static constexpr direction nCols
static const char *const typeName
static const char *const componentNames []
static const Form zero
static const Form one
static const Form max
static const Form min
static const Form rootMax
static const Form rootMin
Additional Inherited Members
Public Attributes inherited from VectorSpace< Form, Cmpt, Mrows *Ncols >
Cmpt v_ [Ncmpts]
Detailed Description
template<class Form, class Cmpt, direction Mrows, direction Ncols>
class Foam::MatrixSpace< Form, Cmpt, Mrows, Ncols >
Templated matrix space.
Template arguments are the Form the matrix space will be used to create, the type of the elements and the number of rows and columns of the matrix.
Source files
MatrixSpace.H
MatrixSpaceI.H
See also
Foam::VectorSpace
Definition at line 54 of file MatrixSpace.H.
Member Typedef Documentation
msType
template<class Form , class Cmpt , direction Mrows, direction Ncols> typedef MatrixSpace<Form, Cmpt, Mrows, Ncols> msType
Definition at line 63 of file MatrixSpace.H.
Constructor & Destructor Documentation
MatrixSpace() [1/5]
template<class Form , class Cmpt , direction Mrows, direction Ncols> MatrixSpace () default
MatrixSpace() [2/5]
template<class Form , class Cmpt , Foam::direction Mrows, Foam::direction Ncols> MatrixSpace (const Foam::zero) inline
Definition at line 26 of file MatrixSpaceI.H.
MatrixSpace() [3/5]
template<class Form , class Cmpt , Foam::direction Mrows, Foam::direction Ncols> template<class Form2 , class Cmpt2 > MatrixSpace (const VectorSpace< Form2, Cmpt2, Mrows *Ncols > & vs) inline explicit
Definition at line 37 of file MatrixSpaceI.H.
MatrixSpace() [4/5]
template<class Form , class Cmpt , Foam::direction Mrows, Foam::direction Ncols> template<template< class, Foam::direction, Foam::direction > class Block2, Foam::direction BRowStart, Foam::direction BColStart> MatrixSpace (const Block2< Form, BRowStart, BColStart > & block) inline
Definition at line 53 of file MatrixSpaceI.H.
MatrixSpace() [5/5]
template<class Form , class Cmpt , Foam::direction Mrows, Foam::direction Ncols> MatrixSpace (Istream & is) inline explicit
Definition at line 69 of file MatrixSpaceI.H.
Member Function Documentation
m()
template<class Form , class Cmpt , direction Mrows, direction Ncols> static direction m () inline static noexcept
Definition at line 75 of file MatrixSpace.H.
n()
template<class Form , class Cmpt , direction Mrows, direction Ncols> static direction n () inline static noexcept
Definition at line 81 of file MatrixSpace.H.
identity()
template<class Form , class Cmpt , Foam::direction Mrows, Foam::direction Ncols> Foam::MatrixSpace< Form, Cmpt, Mrows, Ncols > identity () inline static
Definition at line 141 of file MatrixSpaceI.H.
References Foam::Zero.
elmt() [1/2]
template<class Form , class Cmpt , Foam::direction Mrows, Foam::direction Ncols> template<Foam::direction Row, Foam::direction Col> const Cmpt & elmt () const inline noexcept
Definition at line 121 of file MatrixSpaceI.H.
elmt() [2/2]
template<class Form , class Cmpt , Foam::direction Mrows, Foam::direction Ncols> template<Foam::direction Row, Foam::direction Col> Cmpt & elmt () inline noexcept
Definition at line 131 of file MatrixSpaceI.H.
References VectorSpace< Form, Cmpt, Mrows *Ncols >::v_.
xx() [1/2]
template<class Form , class Cmpt , direction Mrows, direction Ncols> const Cmpt & xx () const inline noexcept
Definition at line 246 of file MatrixSpace.H.
Referenced by Rs::jcalc(), Rxyz::jcalc(), Ryxz::jcalc(), and Rzyx::jcalc().
xy() [1/2]
template<class Form , class Cmpt , direction Mrows, direction Ncols> const Cmpt & xy () const inline noexcept
Definition at line 247 of file MatrixSpace.H.
Referenced by Rxyz::jcalc(), and Ryxz::jcalc().
xz() [1/2]
template<class Form , class Cmpt , direction Mrows, direction Ncols> const Cmpt & xz () const inline noexcept
Definition at line 248 of file MatrixSpace.H.
Referenced by Rzyx::jcalc().
yx() [1/2]
template<class Form , class Cmpt , direction Mrows, direction Ncols> const Cmpt & yx () const inline noexcept
Definition at line 249 of file MatrixSpace.H.
Referenced by Rxyz::jcalc(), Ryxz::jcalc(), and Rzyx::jcalc().
yy() [1/2]
template<class Form , class Cmpt , direction Mrows, direction Ncols> const Cmpt & yy () const inline noexcept
Definition at line 250 of file MatrixSpace.H.
Referenced by Rs::jcalc(), Rxyz::jcalc(), Ryxz::jcalc(), and Rzyx::jcalc().
yz() [1/2]
template<class Form , class Cmpt , direction Mrows, direction Ncols> const Cmpt & yz () const inline noexcept
Definition at line 251 of file MatrixSpace.H.
zx() [1/2]
template<class Form , class Cmpt , direction Mrows, direction Ncols> const Cmpt & zx () const inline noexcept
Definition at line 252 of file MatrixSpace.H.
Referenced by Rxyz::jcalc(), Ryxz::jcalc(), and Rzyx::jcalc().
zy() [1/2]
template<class Form , class Cmpt , direction Mrows, direction Ncols> const Cmpt & zy () const inline noexcept
Definition at line 253 of file MatrixSpace.H.
Referenced by Rzyx::jcalc().
zz() [1/2]
template<class Form , class Cmpt , direction Mrows, direction Ncols> const Cmpt & zz () const inline noexcept
Definition at line 254 of file MatrixSpace.H.
Referenced by Rs::jcalc(), Rxyz::jcalc(), and Ryxz::jcalc().
xx() [2/2]
template<class Form , class Cmpt , direction Mrows, direction Ncols> Cmpt & xx () inline noexcept
Definition at line 260 of file MatrixSpace.H.
xy() [2/2]
template<class Form , class Cmpt , direction Mrows, direction Ncols> Cmpt & xy () inline noexcept
Definition at line 261 of file MatrixSpace.H.
xz() [2/2]
template<class Form , class Cmpt , direction Mrows, direction Ncols> Cmpt & xz () inline noexcept
Definition at line 262 of file MatrixSpace.H.
yx() [2/2]
template<class Form , class Cmpt , direction Mrows, direction Ncols> Cmpt & yx () inline noexcept
Definition at line 263 of file MatrixSpace.H.
yy() [2/2]
template<class Form , class Cmpt , direction Mrows, direction Ncols> Cmpt & yy () inline noexcept
Definition at line 264 of file MatrixSpace.H.
yz() [2/2]
template<class Form , class Cmpt , direction Mrows, direction Ncols> Cmpt & yz () inline noexcept
Definition at line 265 of file MatrixSpace.H.
zx() [2/2]
template<class Form , class Cmpt , direction Mrows, direction Ncols> Cmpt & zx () inline noexcept
Definition at line 266 of file MatrixSpace.H.
zy() [2/2]
template<class Form , class Cmpt , direction Mrows, direction Ncols> Cmpt & zy () inline noexcept
Definition at line 267 of file MatrixSpace.H.
zz() [2/2]
template<class Form , class Cmpt , direction Mrows, direction Ncols> Cmpt & zz () inline noexcept
Definition at line 268 of file MatrixSpace.H.
T()
template<class Form , class Cmpt , Foam::direction Mrows, Foam::direction Ncols> Foam::typeOfTranspose< Cmpt, Form >::type T () const inline
Definition at line 157 of file MatrixSpaceI.H.
block() [1/4]
template<class Form , class Cmpt , direction Mrows, direction Ncols> template<class SubTensor , direction BRowStart, direction BColStart> ConstBlock< SubTensor, BRowStart, BColStart > block () const inline
Referenced by MatrixSpace< Form, Cmpt, Mrows, Ncols >::operator=().
block() [2/4]
template<class Form , class Cmpt , direction Mrows, direction Ncols> template<class SubTensor , direction BRowStart, direction BColStart> Block< SubTensor, BRowStart, BColStart > block () inline
operator()() [1/2]
template<class Form , class Cmpt , Foam::direction Mrows, Foam::direction Ncols> const Cmpt & operator() (const direction & i, const direction & j) const inline
Definition at line 207 of file MatrixSpaceI.H.
Referenced by MatrixSpace< Form, Cmpt, Mrows, Ncols >::Block< SubTensor, BRowStart, BColStart >::operator()(), MatrixSpace< Form, Cmpt, Mrows, Ncols >::operator=(), MatrixSpace< Form, Cmpt, Mrows, Ncols >::Block< SubTensor, BRowStart, BColStart >::operator=(), and MatrixSpace< Form, Cmpt, Mrows, Ncols >::Block< SubTensor, BRowStart, BColStart >::operator=().
operator()() [2/2]
template<class Form , class Cmpt , Foam::direction Mrows, Foam::direction Ncols> Cmpt & operator() (const direction & i, const direction & j) inline
Definition at line 227 of file MatrixSpaceI.H.
operator=() [1/2]
template<class Form , class Cmpt , Foam::direction Mrows, Foam::direction Ncols> void operator= (const Foam::zero) inline
Definition at line 312 of file MatrixSpaceI.H.
operator=() [2/2]
template<class Form , class Cmpt , Foam::direction Mrows, Foam::direction Ncols> template<template< class, Foam::direction, Foam::direction > class Block2, Foam::direction BRowStart, Foam::direction BColStart> void operator= (const Block2< Form, BRowStart, BColStart > & block) inline
Definition at line 339 of file MatrixSpaceI.H.
References MatrixSpace< Form, Cmpt, Mrows, Ncols >::block(), and MatrixSpace< Form, Cmpt, Mrows, Ncols >::operator()().
operator&=()
template<class Form , class Cmpt , Foam::direction Mrows, Foam::direction Ncols> template<class Form2 > void operator&= (const MatrixSpace< Form, Cmpt, Ncols, Ncols > & matrix) inline
Definition at line 323 of file MatrixSpaceI.H.
block() [3/4]
template<class Form , class Cmpt , direction Mrows, direction Ncols> template<class SubTensor , Foam::direction BRowStart, Foam::direction BColStart> Foam::MatrixSpace< Form, Cmpt, Mrows, Ncols >::template ConstBlock< SubTensor, BRowStart, BColStart > block () const inline
Definition at line 182 of file MatrixSpaceI.H.
block() [4/4]
template<class Form , class Cmpt , direction Mrows, direction Ncols> template<class SubTensor , Foam::direction BRowStart, Foam::direction BColStart> Foam::MatrixSpace< Form, Cmpt, Mrows, Ncols >::template Block< SubTensor, BRowStart, BColStart > block () inline
Definition at line 198 of file MatrixSpaceI.H.
Member Data Documentation
mRows
template<class Form , class Cmpt , direction Mrows, direction Ncols> constexpr direction mRows = Mrows static constexpr
Definition at line 68 of file MatrixSpace.H.
Referenced by MatrixSpace< Form, Cmpt, Mrows, Ncols >::Block< SubTensor, BRowStart, BColStart >::Block(), MatrixSpace< Form, Cmpt, Mrows, Ncols >::ConstBlock< SubTensor, BRowStart, BColStart >::ConstBlock(), and MatrixSpace< Form, Cmpt, Mrows, Ncols >::Block< SubTensor, BRowStart, BColStart >::operator=().
nCols
template<class Form , class Cmpt , direction Mrows, direction Ncols> constexpr direction nCols = Ncols static constexpr
Definition at line 69 of file MatrixSpace.H.
Referenced by MatrixSpace< Form, Cmpt, Mrows, Ncols >::Block< SubTensor, BRowStart, BColStart >::Block(), MatrixSpace< Form, Cmpt, Mrows, Ncols >::Block< SubTensor, BRowStart, BColStart >::operator=(), and MatrixSpace< Form, Cmpt, Mrows, Ncols >::Block< SubTensor, BRowStart, BColStart >::operator=().
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/MatrixSpace/MatrixSpace.H
src/OpenFOAM/primitives/MatrixSpace/MatrixSpaceI.H