OpenFOAM: DEShybrid< Type > Class Template Reference
DEShybrid< Type > Class Template Reference
Improved hybrid convection scheme of Travin et al. for hybrid RAS/LES calculations with enhanced Grey Area Mitigation (GAM) behaviour.
#include <DEShybrid.H>
Public Member Functions
TypeName ("DEShybrid")
DEShybrid (const fvMesh &mesh, Istream &is)
DEShybrid (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &is)
virtual tmp< surfaceScalarField > blendingFactor (const GeometricField< Type, fvPatchField, volMesh > &vf) const
tmp< surfaceScalarField > weights (const VolFieldType &vf) const
tmp< SurfaceFieldType > interpolate (const VolFieldType &vf) const
virtual bool corrected () const
virtual tmp< SurfaceFieldType > correction (const VolFieldType &vf) const
Public Member Functions inherited from surfaceInterpolationScheme< Type >
TypeName ("surfaceInterpolationScheme")
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, Mesh,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, MeshFlux,(const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
surfaceInterpolationScheme (const fvMesh &mesh)
virtual ~surfaceInterpolationScheme ()=default
const fvMesh & mesh () const
virtual tmp< surfaceScalarField > weights (const GeometricField< Type, fvPatchField, volMesh > &) const =0
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > &) const
virtual tmp< GeometricField< typename innerProduct< vector, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf) const
tmp< GeometricField< typename innerProduct< vector, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const tmp< GeometricField< Type, fvPatchField, volMesh > > &) const
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &) const
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > &) const
template<class SFType >
Foam::tmp< Foam::GeometricField< typename Foam::innerProduct< typename SFType::value_type, Type >::type, Foam::fvsPatchField, Foam::surfaceMesh > > dotInterpolate (const SFType &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf, const tmp< surfaceScalarField > &tlambdas)
tmp< GeometricField< typename innerProduct< vector, scalar >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const GeometricField< scalar, fvPatchField, volMesh > &) const
Foam::tmp< Foam::GeometricField< typename Foam::innerProduct< Foam::vector, Foam::scalar >::type, Foam::fvsPatchField, Foam::surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const GeometricField< scalar, fvPatchField, volMesh > &) const
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Public Member Functions inherited from blendedSchemeBase< Type >
blendedSchemeBase ()=default
virtual ~blendedSchemeBase ()=default
Additional Inherited Members
Static Public Member Functions inherited from surfaceInterpolationScheme< Type >
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData)
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &, const tmp< surfaceScalarField > &)
template<class SFType >
static tmp< GeometricField< typename innerProduct< typename SFType::value_type, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const SFType &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf, const tmp< surfaceScalarField > &tlambdas)
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &)
Detailed Description
template<class Type>
class Foam::DEShybrid< Type >
Improved hybrid convection scheme of Travin et al. for hybrid RAS/LES calculations with enhanced Grey Area Mitigation (GAM) behaviour.
The scheme provides a blend between two convection schemes, based on local properties including the wall distance, velocity gradient and eddy viscosity. The scheme was originally developed for DES calculations to blend a low-dissipative scheme, e.g. linear, in the vorticity-dominated, finely-resolved regions and a numerically more robust, e.g. upwind-biased, convection scheme in irrotational or coarsely-resolved regions.
The routine calculates the blending factor denoted as "sigma" in the literature reference, where 0 <= sigma <= sigmaMax, which is then employed to set the weights:
where
= blending factor
= scheme 1 weights
= scheme 2 weights
First published in:
        Travin, A., Shur, M., Strelets, M., & Spalart, P. R. (2000).
        Physical and numerical upgrades in the detached-eddy
        simulation of complex turbulent flows.
        In LES of Complex Transitional and Turbulent Flows.
        Proceedings of the Euromech Colloquium 412. Munich, Germany
Original publication contained a typo for C_H3 constant. Corrected version with minor changes for 2 lower limiters published in:
        Spalart, P., Shur, M., Strelets, M., & Travin, A. (2012).
        Sensitivity of landing-gear noise predictions by large-eddy
        simulation to numerics and resolution.
        In 50th AIAA Aerospace Sciences Meeting Including the
        New Horizons Forum and Aerospace Exposition. Nashville, US.
        DOI:10.2514/6.2012-1174
Example of the DEShybrid scheme specification using linear within the LES region and linearUpwind within the RAS region:
    divSchemes
    {
        .
        .
        div(phi,U)      Gauss DEShybrid
            linear                    // scheme 1
            linearUpwind grad(U)      // scheme 2
            delta                     // LES delta name, e.g. 'delta', 'hmax'
            0.65                      // CDES coefficient
            30                        // Reference velocity scale
            2                         // Reference length scale
            0                         // Minimum sigma limit (0-1)
            1                         // Maximum sigma limit (0-1)
            1.0e-03                   // Limiter of B function, typically 1e-03
            1.0;                      // nut limiter (if > 1, GAM extension is active)
        .
        .
    }
Notes
Scheme 1 should be linear (or other low-dissipative schemes) which will be used in the detached/vortex shedding regions.
Scheme 2 should be an upwind/deferred correction/TVD scheme which will be used in the free-stream/Euler/boundary layer regions.
The scheme is compiled into a separate library, and not available to solvers by default. In order to use the scheme, add the library as a run-time loaded library in the $FOAM\_CASE/system/controlDict dictionary, e.g.:
        libs (turbulenceModelSchemes);
Source files
DEShybrid.H
DEShybrid.C
Definition at line 143 of file DEShybrid.H.
Constructor & Destructor Documentation
DEShybrid() [1/2]
template<class Type > DEShybrid (const fvMesh & mesh, Istream & is) inline
Definition at line 374 of file DEShybrid.H.
DEShybrid() [2/2]
template<class Type > DEShybrid (const fvMesh & mesh, const surfaceScalarField & faceFlux, Istream & is) inline
Definition at line 396 of file DEShybrid.H.
Member Function Documentation
TypeName()
template<class Type > TypeName ("DEShybrid< Type >")
blendingFactor()
template<class Type > virtual tmp< surfaceScalarField > blendingFactor (const GeometricField< Type, fvPatchField, volMesh > & vf) const inline virtual
Implements blendedSchemeBase< Type >.
Definition at line 432 of file DEShybrid.H.
References delta, Foam::exit(), Foam::FatalError, FatalErrorInFunction, surfaceInterpolationScheme< Type >::mesh(), and turbulenceModel::propertiesName.
Referenced by DEShybrid< Type >::correction(), DEShybrid< Type >::interpolate(), and DEShybrid< Type >::weights().
weights()
template<class Type > tmp< surfaceScalarField > weights (const VolFieldType & vf) const inline
Definition at line 470 of file DEShybrid.H.
References DEShybrid< Type >::blendingFactor().
interpolate()
template<class Type > tmp< SurfaceFieldType > interpolate (const VolFieldType & vf) const inline
Definition at line 482 of file DEShybrid.H.
References DEShybrid< Type >::blendingFactor().
corrected()
template<class Type > virtual bool corrected () const inline virtual
Reimplemented from surfaceInterpolationScheme< Type >.
Definition at line 493 of file DEShybrid.H.
Referenced by DEShybrid< Type >::correction().
correction()
template<class Type > virtual tmp< SurfaceFieldType > correction (const VolFieldType & vf) const inline virtual
Definition at line 501 of file DEShybrid.H.
References DEShybrid< Type >::blendingFactor(), DEShybrid< Type >::corrected(), and DEShybrid< Type >::correction().
Referenced by DEShybrid< Type >::correction().
The documentation for this class was generated from the following file:
src/TurbulenceModels/schemes/DEShybrid/DEShybrid.H