OpenFOAM: cylindricalInletVelocityFvPatchVectorField Class Reference
cylindricalInletVelocityFvPatchVectorField Class Reference
Boundary conditions » Inlet
This boundary condition describes an inlet vector boundary condition in cylindrical coordinates given a central axis, central point, rpm, axial and radial velocity.
#include <cylindricalInletVelocityFvPatchVectorField.H>
Public Member Functions
TypeName ("cylindricalInletVelocity")
cylindricalInletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
cylindricalInletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
cylindricalInletVelocityFvPatchVectorField (const cylindricalInletVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
cylindricalInletVelocityFvPatchVectorField (const cylindricalInletVelocityFvPatchVectorField &)
virtual tmp< fvPatchVectorField > clone () const
cylindricalInletVelocityFvPatchVectorField (const cylindricalInletVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
This boundary condition describes an inlet vector boundary condition in cylindrical coordinates given a central axis, central point, rpm, axial and radial velocity.
Usage
Property Description Required Default value
axis axis of rotation yes
origin origin of rotation yes
axialVelocity axial velocity profile [m/s] yes
radialVelocity radial velocity profile [m/s] yes
rpm rotational speed (revolutions per minute) yes
Example of the boundary condition specification:
    <patchName>
    {
        type            cylindricalInletVelocity;
        axis            (0 0 1);
        origin          (0 0 0);
        axialVelocity   constant 30;
        radialVelocity  constant -10;
        rpm             constant 100;
    }
Note
The axialVelocity, radialVelocity and rpm entries are Function1 types, able to describe time varying functions. The example above gives the usage for supplying constant values.
See also
Foam::fixedValueFvPatchField Foam::Function1Types
Source files
cylindricalInletVelocityFvPatchVectorField.H
cylindricalInletVelocityFvPatchVectorField.C
Definition at line 113 of file cylindricalInletVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
cylindricalInletVelocityFvPatchVectorField() [1/5]
cylindricalInletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Definition at line 31 of file cylindricalInletVelocityFvPatchVectorField.C.
cylindricalInletVelocityFvPatchVectorField() [2/5]
cylindricalInletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Definition at line 65 of file cylindricalInletVelocityFvPatchVectorField.C.
cylindricalInletVelocityFvPatchVectorField() [3/5]
cylindricalInletVelocityFvPatchVectorField (const cylindricalInletVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 47 of file cylindricalInletVelocityFvPatchVectorField.C.
cylindricalInletVelocityFvPatchVectorField() [4/5]
cylindricalInletVelocityFvPatchVectorField (const cylindricalInletVelocityFvPatchVectorField & ptf)
Definition at line 85 of file cylindricalInletVelocityFvPatchVectorField.C.
cylindricalInletVelocityFvPatchVectorField() [5/5]
cylindricalInletVelocityFvPatchVectorField (const cylindricalInletVelocityFvPatchVectorField & ptf, const DimensionedField< vector, volMesh > & iF)
Definition at line 100 of file cylindricalInletVelocityFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("cylindricalInletVelocity")
clone() [1/2]
virtual tmp< fvPatchVectorField > clone () const inline virtual
Definition at line 176 of file cylindricalInletVelocityFvPatchVectorField.H.
clone() [2/2]
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Definition at line 192 of file cylindricalInletVelocityFvPatchVectorField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 118 of file cylindricalInletVelocityFvPatchVectorField.C.
References Foam::mag(), Foam::operator==(), Foam::rpmToRads(), and fvPatchField< Type >::updateCoeffs().
write()
void write (Ostream & os) const virtual
Definition at line 146 of file cylindricalInletVelocityFvPatchVectorField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntry(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/cylindricalInletVelocity/cylindricalInletVelocityFvPatchVectorField.H
src/finiteVolume/fields/fvPatchFields/derived/cylindricalInletVelocity/cylindricalInletVelocityFvPatchVectorField.C