OpenFOAM: ReynoldsAnalogy Class Reference
ReynoldsAnalogy Class Reference
Heat transfer coefficient calculation based on Reynolds Analogy, which is used to relate turbulent momentum and heat transfer.
#include <ReynoldsAnalogy.H>
Public Member Functions
TypeName ("ReynoldsAnalogy")
ReynoldsAnalogy (const dictionary &dict, const fvMesh &mesh, const word &TName)
ReynoldsAnalogy (const ReynoldsAnalogy &)=delete
void operator= (const ReynoldsAnalogy &)=delete
virtual ~ReynoldsAnalogy ()=default
virtual bool read (const dictionary &dict)
Public Member Functions inherited from heatTransferCoeffModel
TypeName ("heatTransferCoeffModel")
declareRunTimeSelectionTable (autoPtr, heatTransferCoeffModel, dictionary,(const dictionary &dict, const fvMesh &mesh, const word &TName),(dict, mesh, TName))
heatTransferCoeffModel (const dictionary &dict, const fvMesh &mesh, const word &TName)
heatTransferCoeffModel (const heatTransferCoeffModel &)=delete
void operator= (const heatTransferCoeffModel &)=delete
virtual ~heatTransferCoeffModel ()=default
const fvMesh & mesh () const noexcept
const labelHashSet & patchSet () const noexcept
const word & TName () const noexcept
const word & qrName () const noexcept
tmp< FieldField< Field, scalar > > q () const
virtual bool calc (volScalarField &result, const FieldField< Field, scalar > &q)
Protected Member Functions
virtual tmp< scalarField > rho (const label patchi) const
virtual tmp< scalarField > Cp (const label patchi) const
virtual tmp< volSymmTensorField > devReff () const
tmp< FieldField< Field, scalar > > Cf () const
virtual void htc (volScalarField &htc, const FieldField< Field, scalar > &q)
Protected Attributes
word UName_
vector URef_
word rhoName_
scalar rhoRef_
word CpName_
scalar CpRef_
Protected Attributes inherited from heatTransferCoeffModel
const fvMesh & mesh_
labelHashSet patchSet_
const word TName_
word qrName_
Additional Inherited Members
Static Public Member Functions inherited from heatTransferCoeffModel
static autoPtr< heatTransferCoeffModel > New (const dictionary &dict, const fvMesh &mesh, const word &TName)
Detailed Description
Heat transfer coefficient calculation based on Reynolds Analogy, which is used to relate turbulent momentum and heat transfer.
The heat transfer coefficient is derived from the skin friction coefficient:
as:
where
= Heat transfer coefficient [W/m^2/K]
= Reference fluid density [kg/m^3]
= Reference specific heat capacity at constant pressure [J/kg/K]
= Reference velocity [m/s]
= Skin friction coefficient [-]
= Wall shear stress [m^2/s^2]
Usage
Minimal example by using system/controlDict.functions:
heatTransferCoeff1
{
    // Inherited entries
    ...
    // Mandatory entries
    htcModel        ReynoldsAnalogy;
    UInf            <vector>;
    // Optional entries
    U               <word>;
    Cp              <word>;
    rho             <word>;
    // Conditional mandatory entries
        // when Cp == CpInf
        CpInf       <scalar>;
        // when rho == rhoInf
        rhoInf      <scalar>;
}
where the entries mean:
Property Description Type Reqd Deflt
type Model name: ReynoldsAnalogy word yes -
UInf Reference velocity vector yes -
U Name of velocity field word no U
Cp Name of reference specific heat capacity word no Cp
CpInf Reference specific heat capacity value scalar choice -
rho Name of fluid density field word no rho
rhoInf Reference fluid density value scalar choice -
Note
In order to use a reference Cp, set Cp to CpInf.
In order to use a reference rho, set rho to rhoInf.
Source files
ReynoldsAnalogy.H
ReynoldsAnalogy.C
Definition at line 187 of file ReynoldsAnalogy.H.
Constructor & Destructor Documentation
ReynoldsAnalogy() [1/2]
ReynoldsAnalogy (const dictionary & dict, const fvMesh & mesh, const word & TName)
Definition at line 210 of file ReynoldsAnalogy.C.
References dict, and ReynoldsAnalogy::read().
ReynoldsAnalogy() [2/2]
ReynoldsAnalogy (const ReynoldsAnalogy &) delete
~ReynoldsAnalogy()
virtual ~ReynoldsAnalogy () virtual default
Member Function Documentation
rho()
Foam::tmp< Foam::scalarField > rho (const label patchi) const protected virtual
Definition at line 47 of file ReynoldsAnalogy.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, heatTransferCoeffModel::mesh_, n, tmp< T >::New(), rho, ReynoldsAnalogy::rhoName_, ReynoldsAnalogy::rhoRef_, and UPtrList< T >::size().
Cp()
Foam::tmp< Foam::scalarField > Cp (const label patchi) const protected virtual
Definition at line 69 of file ReynoldsAnalogy.C.
References basicThermo::dictName, Foam::exit(), Foam::FatalError, FatalErrorInFunction, n, tmp< T >::New(), pp(), and UPtrList< T >::size().
devReff()
Foam::tmp< Foam::volSymmTensorField > devReff () const protected virtual
Definition at line 96 of file ReynoldsAnalogy.C.
References Foam::devTwoSymm(), basicThermo::dictName, Foam::dimViscosity, Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::fvc::grad(), nu, transportProperties(), turb, and U.
Cf()
Foam::tmp< Foam::FieldField< Foam::Field, Foam::scalar > > Cf () const protected
Definition at line 154 of file ReynoldsAnalogy.C.
References forAll, Foam::mag(), Foam::magSqr(), Foam::New(), fvPatchFieldBase::patch(), R, PtrList< T >::set(), UPtrList< T >::size(), U, and Foam::Zero.
htc()
void htc (volScalarField & htc, const FieldField< Field, scalar > & q) protected virtual
Implements heatTransferCoeffModel.
Definition at line 187 of file ReynoldsAnalogy.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), Cp, Foam::mag(), and rho.
TypeName()
TypeName ("ReynoldsAnalogy")
operator=()
void operator= (const ReynoldsAnalogy &) delete
read()
bool read (const dictionary & dict) virtual
Reimplemented from heatTransferCoeffModel.
Definition at line 231 of file ReynoldsAnalogy.C.
References dict, and heatTransferCoeffModel::read().
Referenced by ReynoldsAnalogy::ReynoldsAnalogy().
Member Data Documentation
UName_
word UName_ protected
Definition at line 196 of file ReynoldsAnalogy.H.
URef_
vector URef_ protected
Definition at line 199 of file ReynoldsAnalogy.H.
rhoName_
word rhoName_ protected
Definition at line 202 of file ReynoldsAnalogy.H.
Referenced by ReynoldsAnalogy::rho().
rhoRef_
scalar rhoRef_ protected
Definition at line 205 of file ReynoldsAnalogy.H.
Referenced by ReynoldsAnalogy::rho().
CpName_
word CpName_ protected
Definition at line 208 of file ReynoldsAnalogy.H.
CpRef_
scalar CpRef_ protected
Definition at line 211 of file ReynoldsAnalogy.H.
The documentation for this class was generated from the following files:
src/functionObjects/field/heatTransferCoeff/heatTransferCoeffModels/ReynoldsAnalogy/ReynoldsAnalogy.H
src/functionObjects/field/heatTransferCoeff/heatTransferCoeffModels/ReynoldsAnalogy/ReynoldsAnalogy.C