OpenFOAM: radiativeIntensityRay Class Reference
radiativeIntensityRay Class Reference
Radiation intensity for a ray in a given direction.
#include <radiativeIntensityRay.H>
Public Member Functions
radiativeIntensityRay (const fvDOM &dom, const fvMesh &mesh, const scalar phi, const scalar theta, const scalar deltaPhi, const scalar deltaTheta, const label lambda, const absorptionEmissionModel &absEmmModel_, const blackBodyEmission &blackBody, const label rayId)
~radiativeIntensityRay ()
scalar correct ()
void init (const scalar phi, const scalar theta, const scalar deltaPhi, const scalar deltaTheta, const scalar lambda)
void addIntensity ()
const volScalarField & I () const
const volScalarField & qr () const
volScalarField & qr ()
volScalarField & qin ()
volScalarField & qem ()
const volScalarField & qin () const
const volScalarField & qem () const
const vector & d () const
const vector & dAve () const
vector & d ()
vector & dAve ()
scalar nLambda () const
scalar phi () const
scalar theta () const
scalar omega () const
const volScalarField & ILambda (const label lambdaI) const
Static Public Attributes
static const word intensityPrefix
Detailed Description
Radiation intensity for a ray in a given direction.
Source files
radiativeIntensityRay.H
radiativeIntensityRay.C
Definition at line 53 of file radiativeIntensityRay.H.
Constructor & Destructor Documentation
radiativeIntensityRay()
radiativeIntensityRay (const fvDOM & dom, const fvMesh & mesh, const scalar phi, const scalar theta, const scalar deltaPhi, const scalar deltaTheta, const label lambda, const absorptionEmissionModel & absEmmModel_, const blackBodyEmission & blackBody, const label rayId)
Definition at line 35 of file radiativeIntensityRay.C.
References IOobjectOption::AUTO_WRITE, Foam::cos(), Foam::dimMass, Foam::dimTime, forAll, radiativeIntensityRay::intensityPrefix, IOobjectOption::MUST_READ, Foam::name(), VectorSpace< Form, Cmpt, Ncmpts >::nComponents, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, radiativeIntensityRay::phi(), Foam::pow3(), Foam::rotationTensor(), PtrList< T >::set(), Foam::sin(), radiativeIntensityRay::theta(), Foam::Zero, and VectorSpace< Form, Cmpt, Ncmpts >::zero.
~radiativeIntensityRay()
~radiativeIntensityRay ()
Definition at line 241 of file radiativeIntensityRay.C.
Member Function Documentation
correct()
Foam::scalar correct ()
Definition at line 247 of file radiativeIntensityRay.C.
References Foam::fvm::div(), forAll, k, Foam::max(), Foam::constant::mathematical::pi(), solve(), and Foam::fvm::Sp().
init()
void init (const scalar phi, const scalar theta, const scalar deltaPhi, const scalar deltaTheta, const scalar lambda)
addIntensity()
void addIntensity ()
Definition at line 294 of file radiativeIntensityRay.C.
References Foam::dimMass, Foam::dimTime, forAll, Foam::pow3(), and Foam::Zero.
I()
const Foam::volScalarField & I () const inline
Definition at line 22 of file radiativeIntensityRayI.H.
qr() [1/2]
const Foam::volScalarField & qr () const inline
Definition at line 29 of file radiativeIntensityRayI.H.
Referenced by greyDiffusiveRadiationMixedFvPatchScalarField::updateCoeffs(), and wideBandDiffusiveRadiationMixedFvPatchScalarField::updateCoeffs().
qr() [2/2]
Foam::volScalarField & qr () inline
Definition at line 35 of file radiativeIntensityRayI.H.
qin() [1/2]
Foam::volScalarField & qin () inline
Definition at line 47 of file radiativeIntensityRayI.H.
Referenced by greyDiffusiveRadiationMixedFvPatchScalarField::updateCoeffs(), and wideBandDiffusiveRadiationMixedFvPatchScalarField::updateCoeffs().
qem() [1/2]
Foam::volScalarField & qem () inline
Definition at line 60 of file radiativeIntensityRayI.H.
Referenced by greyDiffusiveRadiationMixedFvPatchScalarField::updateCoeffs(), and wideBandDiffusiveRadiationMixedFvPatchScalarField::updateCoeffs().
qin() [2/2]
const Foam::volScalarField & qin () const inline
Definition at line 40 of file radiativeIntensityRayI.H.
qem() [2/2]
const Foam::volScalarField & qem () const inline
Definition at line 53 of file radiativeIntensityRayI.H.
d() [1/2]
const Foam::vector & d () const inline
Definition at line 66 of file radiativeIntensityRayI.H.
dAve() [1/2]
const Foam::vector & dAve () const inline
Definition at line 72 of file radiativeIntensityRayI.H.
Referenced by greyDiffusiveRadiationMixedFvPatchScalarField::updateCoeffs(), and wideBandDiffusiveRadiationMixedFvPatchScalarField::updateCoeffs().
d() [2/2]
Foam::vector & d () inline
Definition at line 78 of file radiativeIntensityRayI.H.
dAve() [2/2]
Foam::vector & dAve () inline
Definition at line 84 of file radiativeIntensityRayI.H.
nLambda()
Foam::scalar nLambda () const inline
Definition at line 90 of file radiativeIntensityRayI.H.
phi()
Foam::scalar phi () const inline
Definition at line 96 of file radiativeIntensityRayI.H.
Referenced by radiativeIntensityRay::radiativeIntensityRay().
theta()
Foam::scalar theta () const inline
Definition at line 102 of file radiativeIntensityRayI.H.
Referenced by radiativeIntensityRay::radiativeIntensityRay().
omega()
Foam::scalar omega () const inline
Definition at line 108 of file radiativeIntensityRayI.H.
ILambda()
const Foam::volScalarField & ILambda (const label lambdaI) const inline
Definition at line 115 of file radiativeIntensityRayI.H.
Member Data Documentation
intensityPrefix
const Foam::word intensityPrefix static
Definition at line 57 of file radiativeIntensityRay.H.
Referenced by radiativeIntensityRay::radiativeIntensityRay().
The documentation for this class was generated from the following files:
src/thermophysicalModels/radiation/radiationModels/fvDOM/radiativeIntensityRay/radiativeIntensityRay.H
src/thermophysicalModels/radiation/radiationModels/fvDOM/radiativeIntensityRay/radiativeIntensityRay.C
src/thermophysicalModels/radiation/radiationModels/fvDOM/radiativeIntensityRay/radiativeIntensityRayI.H