OpenFOAM: volSurfaceMapping Class Reference
volSurfaceMapping Class Reference
Volume to surface and surface to volume mapping.
#include <volSurfaceMapping.H>
Public Member Functions
volSurfaceMapping (const faMesh &mesh)
volSurfaceMapping (const volSurfaceMapping &)=delete
void operator= (const volSurfaceMapping &)=delete
~volSurfaceMapping ()=default
template<class Type >
void mapToSurface (const GeometricBoundaryField< Type, fvPatchField, volMesh > &, Field< Type > &result) const
template<class Type >
tmp< Field< Type > > mapToSurface (const GeometricBoundaryField< Type, fvPatchField, volMesh > &) const
template<class Type >
void mapToSurface (const GeometricField< Type, fvPatchField, volMesh > &, Field< Type > &result) const
template<class Type >
void mapToSurface (const tmp< GeometricField< Type, fvPatchField, volMesh > > &, Field< Type > &result) const
template<class Type >
tmp< Field< Type > > mapToSurface (const GeometricField< Type, fvPatchField, volMesh > &) const
template<class Type >
tmp< Field< Type > > mapToSurface (const tmp< GeometricField< Type, fvPatchField, volMesh > > &) const
template<class Type >
void mapToSurface (const GeometricField< Type, fvsPatchField, surfaceMesh > &, Field< Type > &result) const
template<class Type >
tmp< Field< Type > > mapToSurface (const GeometricField< Type, fvsPatchField, surfaceMesh > &) const
template<class Type >
void mapToSurface (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > &, Field< Type > &result) const
template<class Type >
tmp< Field< Type > > mapToSurface (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > &) const
template<class Type >
void mapToSurface (const UPtrList< Field< Type > > &patchFields, Field< Type > &result) const
template<class Type >
void mapToSurface (const PtrMap< Field< Type > > &patchFields, Field< Type > &result) const
template<class Type >
tmp< Field< Type > > mapToSurface (const UPtrList< Field< Type > > &patchFields) const
template<class Type >
tmp< Field< Type > > mapToSurface (const PtrMap< Field< Type > > &patchFields) const
template<class Type >
void mapInternalToSurface (const GeometricBoundaryField< Type, fvPatchField, volMesh > &, Field< Type > &result) const
template<class Type >
tmp< Field< Type > > mapInternalToSurface (const GeometricBoundaryField< Type, fvPatchField, volMesh > &) const
template<class Type >
void mapInternalToSurface (const GeometricField< Type, fvPatchField, volMesh > &, Field< Type > &result) const
template<class Type >
void mapInternalToSurface (const tmp< GeometricField< Type, fvPatchField, volMesh > > &, Field< Type > &result) const
template<class Type >
tmp< Field< Type > > mapInternalToSurface (const GeometricField< Type, fvPatchField, volMesh > &) const
template<class Type >
tmp< Field< Type > > mapInternalToSurface (const tmp< GeometricField< Type, fvPatchField, volMesh > > &) const
template<class Type >
void mapToVolume (const DimensionedField< Type, areaMesh > &, GeometricBoundaryField< Type, fvPatchField, volMesh > &dest, const label destPatchi=-1) const
template<class Type >
void mapToVolume (const tmp< DimensionedField< Type, areaMesh > > &, GeometricBoundaryField< Type, fvPatchField, volMesh > &dest, const label destPatchi=-1) const
template<class Type >
void mapToVolume (const DimensionedField< Type, areaMesh > &, GeometricField< Type, fvPatchField, volMesh > &dest, const label destPatchi=-1) const
template<class Type >
void mapToVolume (const tmp< DimensionedField< Type, areaMesh > > &, GeometricField< Type, fvPatchField, volMesh > &dest, const label destPatchi=-1) const
template<class Type >
void mapToVolume (const tmp< GeometricField< Type, faPatchField, areaMesh > > &, GeometricBoundaryField< Type, fvPatchField, volMesh > &dest, const label destPatchi=-1) const
template<class Type >
void mapToVolume (const tmp< GeometricField< Type, faPatchField, areaMesh > > &, GeometricField< Type, fvPatchField, volMesh > &dest, const label destPatchi=-1) const
template<class Type >
void mapToVolumePatch (const DimensionedField< Type, areaMesh > &af, Field< Type > &dest, const label destPatchi) const
template<class Type >
void mapToVolumePatch (const tmp< DimensionedField< Type, areaMesh > > &af, Field< Type > &dest, const label destPatchi) const
template<class Type >
void mapToVolumePatch (const tmp< GeometricField< Type, faPatchField, areaMesh > > &taf, Field< Type > &dest, const label destPatchi) const
template<class Type >
Foam::tmp< Foam::Field< Type > > mapToSurface (const GeometricBoundaryField< Type, fvPatchField, volMesh > &bfld) const
template<class Type >
Foam::tmp< Foam::Field< Type > > mapToSurface (const GeometricField< Type, fvPatchField, volMesh > &vfld) const
template<class Type >
Foam::tmp< Foam::Field< Type > > mapToSurface (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf) const
template<class Type >
Foam::tmp< Foam::Field< Type > > mapToSurface (const GeometricField< Type, fvsPatchField, surfaceMesh > &fld) const
template<class Type >
Foam::tmp< Foam::Field< Type > > mapToSurface (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > &tsf) const
template<class Type >
Foam::tmp< Foam::Field< Type > > mapToSurface (const UPtrList< Field< Type > > &patchFields) const
template<class Type >
Foam::tmp< Foam::Field< Type > > mapToSurface (const PtrMap< Field< Type > > &patchFields) const
template<class Type >
Foam::tmp< Foam::Field< Type > > mapInternalToSurface (const GeometricBoundaryField< Type, fvPatchField, volMesh > &bfld) const
template<class Type >
Foam::tmp< Foam::Field< Type > > mapInternalToSurface (const GeometricField< Type, fvPatchField, volMesh > &vfld) const
template<class Type >
Foam::tmp< Foam::Field< Type > > mapInternalToSurface (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf) const
Detailed Description
Volume to surface and surface to volume mapping.
Author Hrvoje Jasak, Wikki Ltd.
Source files
volSurfaceMapping.H
volSurfaceMapping.C
Definition at line 58 of file volSurfaceMapping.H.
Constructor & Destructor Documentation
volSurfaceMapping() [1/2]
volSurfaceMapping (const faMesh & mesh) inline explicit
Definition at line 71 of file volSurfaceMapping.H.
volSurfaceMapping() [2/2]
volSurfaceMapping (const volSurfaceMapping &) delete
~volSurfaceMapping()
~volSurfaceMapping () default
Member Function Documentation
operator=()
void operator= (const volSurfaceMapping &) delete
mapToSurface() [1/21]
template<class Type > void mapToSurface (const GeometricBoundaryField< Type, fvPatchField, volMesh > & bfld, Field< Type > & result) const
Definition at line 27 of file volSurfaceMapping.C.
References UPtrList< T >::first(), and forAll.
Referenced by SurfaceFilmModel< CloudType >::cacheFilmFields().
mapToSurface() [2/21]
template<class Type > tmp< Field< Type > > mapToSurface (const GeometricBoundaryField< Type, fvPatchField, volMesh > &) const
mapToSurface() [3/21]
template<class Type > void mapToSurface (const GeometricField< Type, fvPatchField, volMesh > & vfld, Field< Type > & result) const
Definition at line 64 of file volSurfaceMapping.C.
mapToSurface() [4/21]
template<class Type > void mapToSurface (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf, Field< Type > & result) const
Definition at line 75 of file volSurfaceMapping.C.
References PtrList< T >::clear().
mapToSurface() [5/21]
template<class Type > tmp< Field< Type > > mapToSurface (const GeometricField< Type, fvPatchField, volMesh > &) const
mapToSurface() [6/21]
template<class Type > tmp< Field< Type > > mapToSurface (const tmp< GeometricField< Type, fvPatchField, volMesh > > &) const
mapToSurface() [7/21]
template<class Type > void mapToSurface (const GeometricField< Type, fvsPatchField, surfaceMesh > & fld, Field< Type > & result) const
Definition at line 109 of file volSurfaceMapping.C.
References UPtrList< T >::first(), fld(), and forAll.
mapToSurface() [8/21]
template<class Type > tmp< Field< Type > > mapToSurface (const GeometricField< Type, fvsPatchField, surfaceMesh > &) const
mapToSurface() [9/21]
template<class Type > void mapToSurface (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > & tsf, Field< Type > & result) const
Definition at line 154 of file volSurfaceMapping.C.
References PtrList< T >::clear().
mapToSurface() [10/21]
template<class Type > tmp< Field< Type > > mapToSurface (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > &) const
mapToSurface() [11/21]
template<class Type > void mapToSurface (const UPtrList< Field< Type > > & patchFields, Field< Type > & result) const
Definition at line 178 of file volSurfaceMapping.C.
References UPtrList< T >::first(), forAll, and UPtrList< T >::get().
mapToSurface() [12/21]
template<class Type > void mapToSurface (const PtrMap< Field< Type > > & patchFields, Field< Type > & result) const
Definition at line 206 of file volSurfaceMapping.C.
References UPtrList< T >::first(), forAll, and UPtrList< T >::get().
mapToSurface() [13/21]
template<class Type > tmp< Field< Type > > mapToSurface (const UPtrList< Field< Type > > & patchFields) const
mapToSurface() [14/21]
template<class Type > tmp< Field< Type > > mapToSurface (const PtrMap< Field< Type > > & patchFields) const
mapInternalToSurface() [1/9]
template<class Type > void mapInternalToSurface (const GeometricBoundaryField< Type, fvPatchField, volMesh > & bfld, Field< Type > & result) const
Definition at line 258 of file volSurfaceMapping.C.
References UPtrList< T >::empty(), UPtrList< T >::last(), patches, PtrList< T >::resize(), and PtrList< T >::set().
mapInternalToSurface() [2/9]
template<class Type > tmp< Field< Type > > mapInternalToSurface (const GeometricBoundaryField< Type, fvPatchField, volMesh > &) const
mapInternalToSurface() [3/9]
template<class Type > void mapInternalToSurface (const GeometricField< Type, fvPatchField, volMesh > & vf, Field< Type > & result) const
Definition at line 300 of file volSurfaceMapping.C.
mapInternalToSurface() [4/9]
template<class Type > void mapInternalToSurface (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf, Field< Type > & result) const
Definition at line 311 of file volSurfaceMapping.C.
References PtrList< T >::clear().
mapInternalToSurface() [5/9]
template<class Type > tmp< Field< Type > > mapInternalToSurface (const GeometricField< Type, fvPatchField, volMesh > &) const
mapInternalToSurface() [6/9]
template<class Type > tmp< Field< Type > > mapInternalToSurface (const tmp< GeometricField< Type, fvPatchField, volMesh > > &) const
mapToVolume() [1/6]
template<class Type > void mapToVolume (const DimensionedField< Type, areaMesh > & af, GeometricBoundaryField< Type, fvPatchField, volMesh > & dest, const label destPatchi = -1) const
Definition at line 345 of file volSurfaceMapping.C.
References UPtrList< T >::first(), and forAll.
mapToVolume() [2/6]
template<class Type > void mapToVolume (const tmp< DimensionedField< Type, areaMesh > > & taf, GeometricBoundaryField< Type, fvPatchField, volMesh > & dest, const label destPatchi = -1) const
Definition at line 372 of file volSurfaceMapping.C.
References PtrList< T >::clear(), and mapToVolume().
mapToVolume() [3/6]
template<class Type > void mapToVolume (const DimensionedField< Type, areaMesh > & af, GeometricField< Type, fvPatchField, volMesh > & dest, const label destPatchi = -1) const
Definition at line 385 of file volSurfaceMapping.C.
References mapToVolume().
mapToVolume() [4/6]
template<class Type > void mapToVolume (const tmp< DimensionedField< Type, areaMesh > > & taf, GeometricField< Type, fvPatchField, volMesh > & dest, const label destPatchi = -1) const
Definition at line 397 of file volSurfaceMapping.C.
References mapToVolume().
mapToVolume() [5/6]
template<class Type > void mapToVolume (const tmp< GeometricField< Type, faPatchField, areaMesh > > & taf, GeometricBoundaryField< Type, fvPatchField, volMesh > & dest, const label destPatchi = -1) const
Definition at line 409 of file volSurfaceMapping.C.
References PtrList< T >::clear(), and mapToVolume().
mapToVolume() [6/6]
template<class Type > void mapToVolume (const tmp< GeometricField< Type, faPatchField, areaMesh > > & taf, GeometricField< Type, fvPatchField, volMesh > & dest, const label destPatchi = -1) const
Definition at line 422 of file volSurfaceMapping.C.
References PtrList< T >::clear(), and mapToVolume().
mapToVolumePatch() [1/3]
template<class Type > void mapToVolumePatch (const DimensionedField< Type, areaMesh > & af, Field< Type > & dest, const label destPatchi) const
Definition at line 435 of file volSurfaceMapping.C.
References UPtrList< T >::first(), and forAll.
mapToVolumePatch() [2/3]
template<class Type > void mapToVolumePatch (const tmp< DimensionedField< Type, areaMesh > > & af, Field< Type > & dest, const label destPatchi) const
Definition at line 459 of file volSurfaceMapping.C.
References PtrList< T >::clear().
mapToVolumePatch() [3/3]
template<class Type > void mapToVolumePatch (const tmp< GeometricField< Type, faPatchField, areaMesh > > & taf, Field< Type > & dest, const label destPatchi) const
Definition at line 472 of file volSurfaceMapping.C.
References PtrList< T >::clear().
mapToSurface() [15/21]
template<class Type > Foam::tmp< Foam::Field< Type > > mapToSurface (const GeometricBoundaryField< Type, fvPatchField, volMesh > & bfld) const
Definition at line 52 of file volSurfaceMapping.C.
References Foam::New(), and Foam::Zero.
mapToSurface() [16/21]
template<class Type > Foam::tmp< Foam::Field< Type > > mapToSurface (const GeometricField< Type, fvPatchField, volMesh > & vfld) const
Definition at line 87 of file volSurfaceMapping.C.
mapToSurface() [17/21]
template<class Type > Foam::tmp< Foam::Field< Type > > mapToSurface (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf) const
Definition at line 97 of file volSurfaceMapping.C.
References PtrList< T >::clear().
mapToSurface() [18/21]
template<class Type > Foam::tmp< Foam::Field< Type > > mapToSurface (const GeometricField< Type, fvsPatchField, surfaceMesh > & fld) const
Definition at line 142 of file volSurfaceMapping.C.
References fld(), Foam::New(), and Foam::Zero.
mapToSurface() [19/21]
template<class Type > Foam::tmp< Foam::Field< Type > > mapToSurface (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > & tsf) const
Definition at line 166 of file volSurfaceMapping.C.
References PtrList< T >::clear().
mapToSurface() [20/21]
template<class Type > Foam::tmp< Foam::Field< Type > > mapToSurface (const UPtrList< Field< Type > > & patchFields) const
Definition at line 234 of file volSurfaceMapping.C.
References Foam::New(), and Foam::Zero.
mapToSurface() [21/21]
template<class Type > Foam::tmp< Foam::Field< Type > > mapToSurface (const PtrMap< Field< Type > > & patchFields) const
Definition at line 246 of file volSurfaceMapping.C.
References Foam::New(), and Foam::Zero.
mapInternalToSurface() [7/9]
template<class Type > Foam::tmp< Foam::Field< Type > > mapInternalToSurface (const GeometricBoundaryField< Type, fvPatchField, volMesh > & bfld) const
Definition at line 286 of file volSurfaceMapping.C.
References Foam::New(), and Foam::Zero.
mapInternalToSurface() [8/9]
template<class Type > Foam::tmp< Foam::Field< Type > > mapInternalToSurface (const GeometricField< Type, fvPatchField, volMesh > & vfld) const
Definition at line 323 of file volSurfaceMapping.C.
mapInternalToSurface() [9/9]
template<class Type > Foam::tmp< Foam::Field< Type > > mapInternalToSurface (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf) const
Definition at line 333 of file volSurfaceMapping.C.
References PtrList< T >::clear().
The documentation for this class was generated from the following files:
src/finiteArea/interpolation/volSurfaceMapping/volSurfaceMapping.H
src/finiteArea/interpolation/volSurfaceMapping/volSurfaceMapping.C