OpenFOAM: ConstMatrixBlock< MatrixType > Class Template Reference
ConstMatrixBlock< MatrixType > Class Template Reference
#include <MatrixBlock.H>
Public Types
typedef MatrixType::cmptType cmptType
Public Member Functions
ConstMatrixBlock (const MatrixType &matrix, const label m, const label n, const label mStart, const label nStart)
label m () const
label n () const
labelPair sizes () const
const cmptType & operator() (const label i, const label j) const
operator Field< cmptType > () const
void checkIndex (const label i, const label j) const
Detailed Description
template<class MatrixType>
class Foam::ConstMatrixBlock< MatrixType >
Definition at line 57 of file MatrixBlock.H.
Member Typedef Documentation
cmptType
template<class MatrixType > typedef MatrixType::cmptType cmptType
Definition at line 81 of file MatrixBlock.H.
Constructor & Destructor Documentation
ConstMatrixBlock()
template<class MatrixType > ConstMatrixBlock (const MatrixType & matrix, const label m, const label n, const label mStart, const label nStart) inline
Definition at line 25 of file MatrixBlockI.H.
Member Function Documentation
m()
template<class MatrixType > Foam::label m () const inline
Definition at line 83 of file MatrixBlockI.H.
n()
template<class MatrixType > Foam::label n () const inline
Definition at line 90 of file MatrixBlockI.H.
sizes()
template<class MatrixType > Foam::labelPair sizes () const inline
Definition at line 111 of file MatrixBlockI.H.
operator()()
template<class MatrixType > const MatrixType::cmptType & operator() (const label i, const label j) const inline
Definition at line 128 of file MatrixBlockI.H.
operator Field< cmptType >()
template<class MatrixType > operator Field< cmptType > () const
Definition at line 27 of file MatrixBlock.C.
References Foam::abort(), f(), Foam::FatalError, FatalErrorInFunction, and forAll.
checkIndex()
template<class MatrixType > void checkIndex (const label i, const label j) const
Definition at line 96 of file MatrixBlock.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/Matrix/Matrix.H
src/OpenFOAM/matrices/MatrixBlock/MatrixBlock.H
src/OpenFOAM/matrices/MatrixBlock/MatrixBlock.C
src/OpenFOAM/matrices/MatrixBlock/MatrixBlockI.H