OpenFOAM: treeDataCell::findIntersectOp Class Reference
treeDataCell::findIntersectOp Class Reference
#include <treeDataCell.H>
Public Member Functions
findIntersectOp (const indexedOctree< treeDataCell > &tree)
bool operator() (const label index, const point &start, const point &end, point &intersectionPoint) const
Detailed Description
Definition at line 118 of file treeDataCell.H.
Constructor & Destructor Documentation
findIntersectOp()
findIntersectOp (const indexedOctree< treeDataCell > & tree)
Definition at line 293 of file treeDataCell.C.
Member Function Documentation
operator()()
bool operator() (const label index, const point & start, const point & end, point & intersectionPoint) const
Definition at line 364 of file treeDataCell.C.
References f(), intersection::HALF_RAY, Foam::magSqr(), treeDataCell::mesh(), treeDataCell::objectIndex(), treeBoundBox::posBits(), intersection::setPlanarTol(), and Foam::sqr().
The documentation for this class was generated from the following files:
src/OpenFOAM/algorithms/indexedOctree/treeDataCell.H
src/OpenFOAM/algorithms/indexedOctree/treeDataCell.C