OpenFOAM: faceShading Class Reference
faceShading Class Reference
Helper class to calculate visible faces for global, sun-like illumination.
#include <faceShading.H>
Public Member Functions
ClassName ("faceShading")
faceShading (const fvMesh &mesh, const vector &dir)
faceShading (const fvMesh &mesh, const labelList &patchIDs, const labelList &zoneIDs, const vector &dir)
~faceShading ()=default
const vector direction () const
vector & direction ()
const labelList & rayStartFaces () const
void correct ()
Static Public Member Functions
static labelList nonCoupledPatches (const polyMesh &mesh)
Detailed Description
Helper class to calculate visible faces for global, sun-like illumination.
faceShading uses the transmissivity value in the boundaryRadiationProperties in order to evaluate which faces are "hit" by the "direction" vector. NOTE: Only transmissivity values of zero are considered for opaque walls.
Source files
faceShading.H
faceShading.C
Definition at line 57 of file faceShading.H.
Constructor & Destructor Documentation
faceShading() [1/2]
faceShading (const fvMesh & mesh, const vector & dir)
Definition at line 507 of file faceShading.C.
faceShading() [2/2]
faceShading (const fvMesh & mesh, const labelList & patchIDs, const labelList & zoneIDs, const vector & dir)
Definition at line 523 of file faceShading.C.
~faceShading()
~faceShading () default
Member Function Documentation
ClassName()
ClassName ("faceShading")
nonCoupledPatches()
Foam::labelList nonCoupledPatches (const polyMesh & mesh) static
Definition at line 543 of file faceShading.C.
References PtrList< T >::append(), polyMesh::boundaryMesh(), forAll, mesh, pbm, and pp().
direction() [1/2]
const vector direction () const inline
Definition at line 168 of file faceShading.H.
direction() [2/2]
vector & direction () inline
Definition at line 174 of file faceShading.H.
rayStartFaces()
const labelList & rayStartFaces () const inline
Definition at line 180 of file faceShading.H.
correct()
void correct ()
Definition at line 560 of file faceShading.C.
The documentation for this class was generated from the following files:
src/thermophysicalModels/radiation/radiationModels/solarLoad/faceShading/faceShading.H
src/thermophysicalModels/radiation/radiationModels/solarLoad/faceShading/faceShading.C