OpenFOAM: zoltanRenumber Class Reference
zoltanRenumber Class Reference
Renumber using Zoltan.
#include <zoltanRenumber.H>
Public Member Functions
TypeName ("zoltan")
zoltanRenumber (const dictionary &dict)
virtual ~zoltanRenumber ()=default
virtual labelList renumber (const pointField &) const
virtual labelList renumber (const polyMesh &mesh, const pointField &cc) const
virtual labelList renumber (const CompactListList< label > &cellCells, const pointField &cellCentres) const
virtual labelList renumber (const labelListList &cellCells, const pointField &cellCentres) const
Public Member Functions inherited from renumberMethod
TypeName ("renumberMethod")
declareRunTimeSelectionTable (autoPtr, renumberMethod, dictionary,(const dictionary &renumberDict),(renumberDict))
renumberMethod (const dictionary &dict)
virtual ~renumberMethod ()=default
virtual labelList renumber (const labelList &cellCells, const labelList &offsets, const pointField &) const
virtual labelList renumber (const polyMesh &mesh, const labelList &fineToCoarse, const pointField &coarsePoints) const
Additional Inherited Members
Static Public Member Functions inherited from renumberMethod
static autoPtr< renumberMethod > New (const dictionary &renumberDict)
Protected Member Functions inherited from renumberMethod
renumberMethod (const renumberMethod &)=delete
void operator= (const renumberMethod &)=delete
Protected Attributes inherited from renumberMethod
const dictionary & renumberDict_
Detailed Description
Renumber using Zoltan.
Use Zoltan.
Zoltan install:
in your ~/.bashrc: export ZOLTAN_ARCH_DIR=\ $WM_THIRD_PARTY_DIR/platforms/linux64Gcc/Zoltan_XXX
unpack into $WM_THIRD_PARTY_DIR
cd Zoltan_XXX
mkdir build
cd build
export CCFLAGS="-fPIC"
export CXXFLAGS="-fPIC"
export CFLAGS="-fPIC"
export LDFLAGS="-shared"
../configure \ –prefix=$ZOLTAN_ARCH_DIR \ –with-ccflags=-fPIC –with-cxxflags=-fPIC –with-ldflags=-shared
Source files
zoltanRenumber.C
zoltanRenumber.C
Source files
zoltanRenumber.H
zoltanRenumber.C
Definition at line 45 of file zoltanRenumber.H.
Constructor & Destructor Documentation
zoltanRenumber()
zoltanRenumber (const dictionary & dict) explicit
Definition at line 267 of file zoltanRenumber.C.
~zoltanRenumber()
virtual ~zoltanRenumber () virtual default
Member Function Documentation
TypeName()
TypeName ("zoltan")
renumber() [1/4]
virtual labelList renumber (const pointField &) const inline virtual
Reimplemented from renumberMethod.
Definition at line 84 of file zoltanRenumber.H.
References NotImplemented.
renumber() [2/4]
Foam::labelList renumber (const polyMesh & mesh, const pointField & cc) const virtual
Reimplemented from renumberMethod.
Definition at line 276 of file zoltanRenumber.C.
References args, UPtrList< T >::begin(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, UPtrList< T >::get(), get_edge_list(), get_geom_list(), get_mesh_dim(), get_num_edges_list(), get_number_of_vertices(), get_vertex_list(), polyMesh::globalData(), Foam::Info, mesh, primitiveMesh::nCells(), Foam::Pout, UPtrList< T >::size(), and argList::size().
renumber() [3/4]
virtual labelList renumber (const CompactListList< label > & cellCells, const pointField & cellCentres) const inline virtual
Reimplemented from renumberMethod.
Definition at line 101 of file zoltanRenumber.H.
References NotImplemented.
renumber() [4/4]
virtual labelList renumber (const labelListList & cellCells, const pointField & cellCentres) const inline virtual
Implements renumberMethod.
Definition at line 113 of file zoltanRenumber.H.
References NotImplemented.
The documentation for this class was generated from the following files:
src/renumber/zoltanRenumber/zoltanRenumber.H
src/renumber/zoltanRenumber/zoltanRenumber.C