OpenFOAM: lagrangianFieldDecomposer Class Reference
lagrangianFieldDecomposer Class Reference
Lagrangian field decomposer.
#include <lagrangianFieldDecomposer.H>
Classes
class fieldsCache
Public Member Functions
lagrangianFieldDecomposer (const polyMesh &mesh, const polyMesh &procMesh, const labelList &faceProcAddressing, const labelList &cellProcAddressing, const word &cloudName, const Cloud< indexedParticle > &lagrangianPositions, const List< SLList< indexedParticle * > * > &cellParticles)
template<class Type >
tmp< IOField< Type > > decomposeField (const word &cloudName, const IOField< Type > &field) const
template<class Type >
tmp< CompactIOField< Field< Type >, Type > > decomposeFieldField (const word &cloudName, const CompactIOField< Field< Type >, Type > &field) const
template<class GeoField >
void decomposeFields (const word &cloudName, const PtrList< GeoField > &fields) const
template<class GeoField >
void decomposeFieldFields (const word &cloudName, const PtrList< GeoField > &fields) const
template<class Type >
Foam::tmp< Foam::IOField< Type > > decomposeField (const word &cloudName, const IOField< Type > &field) const
template<class Type >
Foam::tmp< Foam::CompactIOField< Foam::Field< Type >, Type > > decomposeFieldField (const word &cloudName, const CompactIOField< Field< Type >, Type > &field) const
Static Public Member Functions
template<class Type >
static void readFields (const label cloudi, const IOobjectList &lagrangianObjects, PtrList< PtrList< IOField< Type > > > &cloudFields)
template<class Type >
static void readFieldFields (const label cloudi, const IOobjectList &lagrangianObjects, PtrList< PtrList< CompactIOField< Field< Type >, Type > > > &cloudFields)
Detailed Description
Lagrangian field decomposer.
Source files
lagrangianFieldDecomposer.H
lagrangianFieldDecomposer.C
lagrangianFieldDecomposerCache.C
lagrangianFieldDecomposerReadFields.C
lagrangianFieldDecomposerTemplates.C
Definition at line 56 of file lagrangianFieldDecomposer.H.
Constructor & Destructor Documentation
lagrangianFieldDecomposer()
lagrangianFieldDecomposer (const polyMesh & mesh, const polyMesh & procMesh, const labelList & faceProcAddressing, const labelList & cellProcAddressing, const word & cloudName, const Cloud< indexedParticle > & lagrangianPositions, const List< SLList< indexedParticle * > * > & cellParticles)
Definition at line 29 of file lagrangianFieldDecomposer.C.
References Foam::abort(), particle< Type >::coordinates(), Foam::FatalError, FatalErrorInFunction, forAll, forAllConstIters, indexedParticle::index(), Foam::mag(), Foam::nl, particle< Type >::procTetPt(), List< T >::resize(), UList< T >::size(), particle< Type >::tetFace(), and write().
Member Function Documentation
readFields()
template<class Type > void readFields (const label cloudi, const IOobjectList & lagrangianObjects, PtrList< PtrList< IOField< Type > > > & cloudFields) static
Definition at line 28 of file lagrangianFieldDecomposerReadFields.C.
References io(), PtrList< T >::set(), and UPtrList< T >::size().
readFieldFields()
template<class Type > void readFieldFields (const label cloudi, const IOobjectList & lagrangianObjects, PtrList< PtrList< CompactIOField< Field< Type >, Type > > > & cloudFields) static
Definition at line 58 of file lagrangianFieldDecomposerReadFields.C.
References PtrList< T >::append(), io(), PtrList< T >::set(), UPtrList< T >::size(), and Foam::sort().
decomposeField() [1/2]
template<class Type > tmp< IOField< Type > > decomposeField (const word & cloudName, const IOField< Type > & field) const
decomposeFieldField() [1/2]
template<class Type > tmp< CompactIOField< Field< Type >, Type > > decomposeFieldField (const word & cloudName, const CompactIOField< Field< Type >, Type > & field) const
decomposeFields()
template<class GeoField > void decomposeFields (const word & cloudName, const PtrList< GeoField > & fields) const
Definition at line 82 of file lagrangianFieldDecomposerTemplates.C.
References cloudName(), fields, fld(), and write().
decomposeFieldFields()
template<class GeoField > void decomposeFieldFields (const word & cloudName, const PtrList< GeoField > & fields) const
Definition at line 98 of file lagrangianFieldDecomposerTemplates.C.
References cloudName(), fields, fld(), and write().
decomposeField() [2/2]
template<class Type > Foam::tmp< Foam::IOField< Type > > decomposeField (const word & cloudName, const IOField< Type > & field) const
Definition at line 29 of file lagrangianFieldDecomposerTemplates.C.
References cloudName(), field(), Foam::New(), IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, and cloud::prefix.
decomposeFieldField() [2/2]
template<class Type > Foam::tmp< Foam::CompactIOField< Foam::Field< Type >, Type > > decomposeFieldField (const word & cloudName, const CompactIOField< Field< Type >, Type > & field) const
Definition at line 56 of file lagrangianFieldDecomposerTemplates.C.
References cloudName(), field(), Foam::New(), IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, and cloud::prefix.
The documentation for this class was generated from the following files:
src/parallel/decompose/decompose/lagrangianFieldDecomposer.H
src/parallel/decompose/decompose/lagrangianFieldDecomposer.C
src/parallel/decompose/decompose/lagrangianFieldDecomposerReadFields.C
src/parallel/decompose/decompose/lagrangianFieldDecomposerTemplates.C