OpenFOAM: functionObjectList Class Reference
functionObjectList Class Reference
List of function objects with start(), execute() and end() functions that is called for each object.
#include <functionObjectList.H>
Public Member Functions
functionObjectList (const Time &runTime, const bool execution=true)
functionObjectList (const Time &runTime, const dictionary &parentDict, const bool execution=true)
~functionObjectList ()=default
label triggerIndex () const
void resetPropertiesDict ()
functionObjects::properties & propsDict ()
const Foam::functionObjects::properties & propsDict () const
objectRegistry & storedObjects ()
const objectRegistry & storedObjects () const
void clear ()
label findObjectID (const word &objName) const
bool read ()
void on ()
void off ()
bool status () const
bool start ()
bool execute ()
bool execute (const label subIndex)
bool execute (const UList< wordRe > &functionNames, const label subIndex)
bool end ()
bool adjustTimeStep ()
bool filesModified () const
void updateMesh (const mapPolyMesh &mpm)
void movePoints (const polyMesh &mesh)
Static Public Member Functions
static autoPtr< functionObjectList > New (const argList &args, const Time &runTime, dictionary &controlDict, HashSet< wordRe > &requiredFields)
static void list ()
static fileName findDict (const word &funcName)
static bool readFunctionObject (const string &funcNameArgs0, dictionary &functionsDict, HashSet< wordRe > &requiredFields, const word &region=word::null)
Static Public Attributes
static fileName functionObjectDictPath
Detailed Description
List of function objects with start(), execute() and end() functions that is called for each object.
functions   // sub-dictionary name under the system/controlDict file
{
    ..optional entries..
    <userDict1>
    {
        // Mandatory entries
        type    <typeName>;
        libs    (<libName> .. <libName>);
        ...
    }
    <userDict2>
    {
        ...
    }
    ...
}
with optional entries:
Property Description Type Reqd Deflt
libs Preloaded library names words no -
errors Error handling (default/warn/ignore/strict) word no inherits
useNamePrefix Default enable/disable scoping prefix bool no no-op
The optional errors entry controls how FatalError is caught during construction and execute/write. FatalIOError is unaffected.
default : warn on construction errors, fatal on runtime errors
warn : warn on construction and runtime errors
ignore : ignore construction and runtime errors
strict : fatal on construction and runtime errors
See also
Foam::functionObject Foam::functionObjects::timeControl
Source files
functionObjectList.H
functionObjectList.C
Definition at line 126 of file functionObjectList.H.
Constructor & Destructor Documentation
functionObjectList() [1/2]
functionObjectList (const Time & runTime, const bool execution = true)
Definition at line 389 of file functionObjectList.C.
functionObjectList() [2/2]
functionObjectList (const Time & runTime, const dictionary & parentDict, const bool execution = true)
Definition at line 399 of file functionObjectList.C.
~functionObjectList()
~functionObjectList () default
Member Function Documentation
New()
Foam::autoPtr< Foam::functionObjectList > New (const argList & args, const Time & runTime, dictionary & controlDict, HashSet< wordRe > & requiredFields) static
Definition at line 420 of file functionObjectList.C.
References args, controlDict(), argList::found(), argList::getList(), argList::getOrDefault(), IOobjectOption::MUST_READ_IF_MODIFIED, IOobjectOption::NO_WRITE, dictionary::null, regionName, IOobjectOption::REGISTER, and runTime.
triggerIndex()
Foam::label triggerIndex () const
Definition at line 510 of file functionObjectList.C.
References propsDict().
resetPropertiesDict()
void resetPropertiesDict ()
Definition at line 516 of file functionObjectList.C.
propsDict() [1/2]
Foam::functionObjects::properties & propsDict ()
Definition at line 524 of file functionObjectList.C.
propsDict() [2/2]
const Foam::functionObjects::properties & propsDict () const
Definition at line 536 of file functionObjectList.C.
storedObjects() [1/2]
Foam::objectRegistry & storedObjects ()
Definition at line 547 of file functionObjectList.C.
storedObjects() [2/2]
const Foam::objectRegistry & storedObjects () const
Definition at line 558 of file functionObjectList.C.
clear()
void clear ()
Definition at line 569 of file functionObjectList.C.
References PtrList< T >::clear().
findObjectID()
Foam::label findObjectID (const word & objName) const
Definition at line 580 of file functionObjectList.C.
list()
void list () static
Definition at line 189 of file functionObjectList.C.
References Foam::findEtcDirs(), Foam::Info, Foam::nl, and HashTable< T, Key, Hash >::sortedToc().
findDict()
Foam::fileName findDict (const word & funcName) static
Definition at line 205 of file functionObjectList.C.
References UPtrList< T >::empty(), Foam::stringOps::expand(), Foam::findEtcDirs(), Foam::isFile(), fileName::null, and Foam::search().
Referenced by functionObjectList::readFunctionObject().
readFunctionObject()
bool readFunctionObject (const string & funcNameArgs0, dictionary & functionsDict, HashSet< wordRe > & requiredFields, const word & region = word::null) static
Definition at line 229 of file functionObjectList.C.
References args, Foam::endl(), Foam::fileHandler, functionObjectList::findDict(), UPtrList< T >::first(), UPtrList< T >::get(), entry::New(), path(), PtrList< T >::set(), argList::size(), Foam::stringOps::splitFunctionArgs(), word::validate(), and WarningInFunction.
Referenced by includeFuncEntry::execute().
read()
bool read ()
Definition at line 932 of file functionObjectList.C.
References addProfiling, PtrList< T >::clear(), functionObject::defaultUseNamePrefix, dict, dictionary::digest(), Foam::endl(), timeControl::entriesPresent(), Foam::exit(), Foam::exitNow(), Foam::FatalError, Foam::FatalIOError, FatalIOErrorInFunction, UPtrList< T >::front(), dictionary::getOrDefault(), Foam::Info, IOWarningInFunction, keyType::LITERAL, functionObject::New(), Foam::nl, PtrList< T >::resize(), Foam::returnReduceAnd(), PtrList< T >::set(), UPtrList< T >::size(), error::throwing(), PtrList< T >::transfer(), and Foam::Warning.
on()
void on ()
Definition at line 598 of file functionObjectList.C.
Referenced by Time::Time(), Time::Time(), Time::Time(), and Time::Time().
off()
void off ()
Definition at line 604 of file functionObjectList.C.
status()
bool status () const
Definition at line 611 of file functionObjectList.C.
start()
bool start ()
Definition at line 617 of file functionObjectList.C.
References Foam::read().
execute() [1/3]
bool execute ()
Definition at line 623 of file functionObjectList.C.
References addProfiling, IOstreamOption::ASCII, UPtrList< T >::cbegin(), Foam::endl(), Foam::FatalError, Foam::FatalIOError, Foam::Info, maxWarnings, Foam::nl, IOstream::precision_, Foam::read(), error::throwing(), and Foam::Warning.
execute() [2/3]
bool execute (const label subIndex)
Definition at line 791 of file functionObjectList.C.
execute() [3/3]
bool execute (const UList< wordRe > & functionNames, const label subIndex)
Definition at line 809 of file functionObjectList.C.
References Foam::stringOps::match(), and UPtrList< T >::size().
end()
bool end ()
Definition at line 834 of file functionObjectList.C.
References addProfiling, UPtrList< T >::cbegin(), UPtrList< T >::end(), Foam::endl(), Foam::FatalError, Foam::FatalIOError, Foam::Info, maxWarnings, Foam::nl, Foam::read(), error::throwing(), and Foam::Warning.
adjustTimeStep()
bool adjustTimeStep ()
Definition at line 901 of file functionObjectList.C.
References addProfiling, and Foam::read().
Referenced by Time::adjustDeltaT().
filesModified()
bool filesModified () const
Definition at line 1205 of file functionObjectList.C.
updateMesh()
void updateMesh (const mapPolyMesh & mpm)
Definition at line 1220 of file functionObjectList.C.
movePoints()
void movePoints (const polyMesh & mesh)
Definition at line 1232 of file functionObjectList.C.
References mesh.
Member Data Documentation
functionObjectDictPath
Foam::fileName functionObjectDictPath static
Definition at line 230 of file functionObjectList.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/db/functionObjects/functionObjectList/functionObjectList.H
src/OpenFOAM/db/functionObjects/functionObjectList/functionObjectList.C