OpenFOAM: ptscotchDecomp Class Reference
ptscotchDecomp Class Reference
PTScotch domain decomposition.
#include <ptscotchDecomp.H>
Public Member Functions
TypeName ("ptscotch")
ptscotchDecomp (const dictionary &decompDict, const word &regionName="")
virtual ~ptscotchDecomp ()=default
virtual bool parallelAware () const
virtual labelList decompose (const polyMesh &mesh, const pointField &points, const scalarField &pointWeights) const
virtual labelList decompose (const polyMesh &mesh, const labelList &agglom, const pointField &regionPoints, const scalarField &regionWeights) const
virtual labelList decompose (const labelListList &globalCellCells, const pointField &cc, const scalarField &cWeights) const
virtual labelList decompose (const pointField &points, const scalarField &pointWeights) const
virtual labelList decompose (const pointField &points) const
virtual labelList decompose (const polyMesh &mesh, const pointField &points, const scalarField &pointWeights) const=0
virtual labelList decompose (const polyMesh &mesh, const pointField &points) const
virtual labelList decompose (const polyMesh &mesh, const labelList &cellToRegion, const pointField &regionPoints, const scalarField &regionWeights) const
virtual labelList decompose (const polyMesh &mesh, const labelList &cellToRegion, const pointField &regionPoints) const
virtual labelList decompose (const labelListList &globalCellCells, const pointField &cc, const scalarField &cWeights) const=0
virtual labelList decompose (const labelListList &globalCellCells, const pointField &cc) const
virtual labelList decompose (const polyMesh &mesh, const scalarField &cellWeights, const boolList &blockedFace, const PtrList< labelList > &specifiedProcessorFaces, const labelList &specifiedProcessor, const List< labelPair > &explicitConnections) const
labelList decompose (const polyMesh &mesh, const scalarField &cWeights) const
Public Member Functions inherited from decompositionMethod
TypeName ("decompositionMethod")
declareRunTimeSelectionTable (autoPtr, decompositionMethod, dictionary,(const dictionary &decompDict, const word &regionName),(decompDict, regionName))
decompositionMethod (const dictionary &decompDict, const word &regionName="")
virtual ~decompositionMethod ()=default
label nDomains () const noexcept
void setConstraints (const polyMesh &mesh, boolList &blockedFace, PtrList< labelList > &specifiedProcessorFaces, labelList &specifiedProcessor, List< labelPair > &explicitConnections) const
void applyConstraints (const polyMesh &mesh, const boolList &blockedFace, const PtrList< labelList > &specifiedProcessorFaces, const labelList &specifiedProcessor, const List< labelPair > &explicitConnections, labelList &finalDecomp) const
labelList decompose (const polyMesh &mesh, const scalarField &cWeights) const
Additional Inherited Members
Static Public Member Functions inherited from decompositionMethod
static label nDomains (const dictionary &decompDict, const word &regionName="")
static const dictionary & optionalRegionDict (const dictionary &decompDict, const word &regionName)
static autoPtr< decompositionMethod > New (const dictionary &decompDict, const word &regionName="")
static void calcCellCells (const polyMesh &mesh, const labelList &agglom, const label nLocalCoarse, const bool global, CompactListList< label > &cellCells)
static void calcCellCells (const polyMesh &mesh, const labelList &agglom, const label nLocalCoarse, const bool parallel, CompactListList< label > &cellCells, CompactListList< scalar > &cellCellWeights)
Protected Types inherited from decompositionMethod
enum selectionType { DEFAULT = 0 , EXACT = 1 , MANDATORY = 2 , NULL_DICT = 4 }
Protected Member Functions inherited from decompositionMethod
const dictionary & findCoeffsDict (const word &coeffsName, int select=selectionType::DEFAULT) const
Static Protected Member Functions inherited from decompositionMethod
static const dictionary & findCoeffsDict (const dictionary &dict, const word &coeffsName, int select=selectionType::DEFAULT)
Protected Attributes inherited from decompositionMethod
const dictionary & decompDict_
const dictionary & decompRegionDict_
label nDomains_
PtrList< decompositionConstraint > constraints_
Detailed Description
PTScotch domain decomposition.
For the main details about how to define the strategies, see scotchDecomp.
Coefficients dictionary: scotchCoeffs, coeffs.
Nonetheless, when decomposing in parallel, using writeGraph=true will write out .dgr files for debugging. For example, use these files with dgpart as follows:
mpirun -np 4 dgpart 2 'region0_%r.dgr'
where:
r gets replaced by current processor rank
it will decompose into 2 domains
See also
Foam::scotchDecomp
Source files
ptscotchDecomp.H
ptscotchDecomp.C
Definition at line 64 of file ptscotchDecomp.H.
Constructor & Destructor Documentation
ptscotchDecomp()
ptscotchDecomp (const dictionary & decompDict, const word & regionName = "") explicit
Definition at line 69 of file dummyPtscotchDecomp.C.
~ptscotchDecomp()
virtual ~ptscotchDecomp () virtual default
Member Function Documentation
TypeName()
TypeName ("ptscotch")
parallelAware()
virtual bool parallelAware () const inline virtual
Implements decompositionMethod.
Definition at line 117 of file ptscotchDecomp.H.
decompose() [1/13]
Foam::labelList decompose (const polyMesh & mesh, const pointField & points, const scalarField & pointWeights) const virtual
Implements decompositionMethod.
Definition at line 82 of file dummyPtscotchDecomp.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and notImplementedMessage.
decompose() [2/13]
Foam::labelList decompose (const polyMesh & mesh, const labelList & agglom, const pointField & regionPoints, const scalarField & regionWeights) const virtual
Reimplemented from decompositionMethod.
Definition at line 96 of file dummyPtscotchDecomp.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and notImplementedMessage.
decompose() [3/13]
Foam::labelList decompose (const labelListList & globalCellCells, const pointField & cc, const scalarField & cWeights) const virtual
Implements decompositionMethod.
Definition at line 111 of file dummyPtscotchDecomp.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and notImplementedMessage.
decompose() [4/13]
Foam::labelList decompose (const pointField & points, const scalarField & pointWeights) const virtual
Reimplemented from decompositionMethod.
Definition at line 218 of file decompositionMethod.C.
decompose() [5/13]
Foam::labelList decompose (const pointField & points) const virtual
Reimplemented from decompositionMethod.
Definition at line 225 of file decompositionMethod.C.
decompose() [6/13]
virtual labelList decompose (const polyMesh & mesh, const pointField & points, const scalarField & pointWeights) const virtual
Implements decompositionMethod.
decompose() [7/13]
Foam::labelList decompose (const polyMesh & mesh, const pointField & points) const virtual
Reimplemented from decompositionMethod.
Definition at line 240 of file decompositionMethod.C.
decompose() [8/13]
Foam::labelList decompose (const polyMesh & mesh, const labelList & cellToRegion, const pointField & regionPoints, const scalarField & regionWeights) const virtual
Reimplemented from decompositionMethod.
Definition at line 254 of file decompositionMethod.C.
decompose() [9/13]
Foam::labelList decompose (const polyMesh & mesh, const labelList & cellToRegion, const pointField & regionPoints) const virtual
Reimplemented from decompositionMethod.
Definition at line 263 of file decompositionMethod.C.
decompose() [10/13]
virtual labelList decompose (const labelListList & globalCellCells, const pointField & cc, const scalarField & cWeights) const virtual
Implements decompositionMethod.
decompose() [11/13]
Foam::labelList decompose (const labelListList & globalCellCells, const pointField & cc) const virtual
Reimplemented from decompositionMethod.
Definition at line 288 of file decompositionMethod.C.
decompose() [12/13]
Foam::labelList decompose (const polyMesh & mesh, const scalarField & cellWeights, const boolList & blockedFace, const PtrList< labelList > & specifiedProcessorFaces, const labelList & specifiedProcessor, const List< labelPair > & explicitConnections) const virtual
Reimplemented from decompositionMethod.
Definition at line 363 of file decompositionMethod.C.
decompose() [13/13]
Foam::labelList decompose (const polyMesh & mesh, const scalarField & cWeights) const
Definition at line 383 of file decompositionMethod.C.
The documentation for this class was generated from the following files:
src/parallel/decompose/ptscotchDecomp/ptscotchDecomp.H
src/dummyThirdParty/ptscotchDecomp/dummyPtscotchDecomp.C
src/parallel/decompose/ptscotchDecomp/ptscotchDecomp.C