OpenFOAM: prghTotalPressureFvPatchScalarField Class Reference
prghTotalPressureFvPatchScalarField Class Reference
Boundary conditions » Generic
This boundary condition provides static pressure condition for p_rgh, calculated as:
#include <prghTotalPressureFvPatchScalarField.H>
Public Member Functions
TypeName ("prghTotalPressure")
prghTotalPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
prghTotalPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
prghTotalPressureFvPatchScalarField (const prghTotalPressureFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
prghTotalPressureFvPatchScalarField (const prghTotalPressureFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
prghTotalPressureFvPatchScalarField (const prghTotalPressureFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
const scalarField & p0 () const
scalarField & p0 ()
virtual void autoMap (const fvPatchFieldMapper &)
virtual void rmap (const fvPatchScalarField &, const labelList &)
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Protected Attributes
word UName_
word phiName_
word rhoName_
scalarField p0_
Detailed Description
This boundary condition provides static pressure condition for p_rgh, calculated as:
where
= Pseudo hydrostatic pressure [Pa]
= Static pressure [Pa]
= Total pressure [Pa]
= Height in the opposite direction to gravity
= Reference height in the opposite direction to gravity
= Density
= Acceleration due to gravity [m/s^2]
Usage
Property Description Required Default value
U Velocity field name no U
phi Flux field name no phi
rho Density field name no rho
p0 Total pressure yes
Example of the boundary condition specification:
    <patchName>
    {
        type            prghTotalPressure;
        p0              uniform 0;
    }
See also
Foam::fixedValueFvPatchScalarField
Source files
prghTotalPressureFvPatchScalarField.H
prghTotalPressureFvPatchScalarField.C
Definition at line 143 of file prghTotalPressureFvPatchScalarField.H.
Constructor & Destructor Documentation
prghTotalPressureFvPatchScalarField() [1/5]
prghTotalPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 31 of file prghTotalPressureFvPatchScalarField.C.
prghTotalPressureFvPatchScalarField() [2/5]
prghTotalPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 45 of file prghTotalPressureFvPatchScalarField.C.
References dict, fvPatchField< Type >::operator=(), and prghTotalPressureFvPatchScalarField::p0_.
prghTotalPressureFvPatchScalarField() [3/5]
prghTotalPressureFvPatchScalarField (const prghTotalPressureFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 65 of file prghTotalPressureFvPatchScalarField.C.
prghTotalPressureFvPatchScalarField() [4/5]
prghTotalPressureFvPatchScalarField (const prghTotalPressureFvPatchScalarField & ptf)
Definition at line 81 of file prghTotalPressureFvPatchScalarField.C.
prghTotalPressureFvPatchScalarField() [5/5]
prghTotalPressureFvPatchScalarField (const prghTotalPressureFvPatchScalarField & ptf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 94 of file prghTotalPressureFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("prghTotalPressure")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 205 of file prghTotalPressureFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 221 of file prghTotalPressureFvPatchScalarField.H.
p0() [1/2]
const scalarField & p0 () const inline
Definition at line 238 of file prghTotalPressureFvPatchScalarField.H.
References prghTotalPressureFvPatchScalarField::p0_.
p0() [2/2]
scalarField & p0 () inline
Definition at line 244 of file prghTotalPressureFvPatchScalarField.H.
References prghTotalPressureFvPatchScalarField::p0_.
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Definition at line 110 of file prghTotalPressureFvPatchScalarField.C.
rmap()
void rmap (const fvPatchScalarField & ptf, const labelList & addr) virtual
Definition at line 120 of file prghTotalPressureFvPatchScalarField.C.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 135 of file prghTotalPressureFvPatchScalarField.C.
References Foam::cmptMag(), Foam::dimLength, g, Foam::mag(), Foam::magSqr(), Foam::neg(), and gravity::New().
write()
void write (Ostream & os) const virtual
Definition at line 175 of file prghTotalPressureFvPatchScalarField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntryIfDifferent(), and fvPatchField< Type >::writeValueEntry().
Member Data Documentation
UName_
word UName_ protected
Definition at line 153 of file prghTotalPressureFvPatchScalarField.H.
phiName_
word phiName_ protected
Definition at line 156 of file prghTotalPressureFvPatchScalarField.H.
rhoName_
word rhoName_ protected
Definition at line 159 of file prghTotalPressureFvPatchScalarField.H.
p0_
scalarField p0_ protected
Definition at line 162 of file prghTotalPressureFvPatchScalarField.H.
Referenced by prghTotalPressureFvPatchScalarField::p0(), prghTotalPressureFvPatchScalarField::p0(), and prghTotalPressureFvPatchScalarField::prghTotalPressureFvPatchScalarField().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/prghTotalPressure/prghTotalPressureFvPatchScalarField.H
src/finiteVolume/fields/fvPatchFields/derived/prghTotalPressure/prghTotalPressureFvPatchScalarField.C