OpenFOAM: injectionModel Class Reference
injectionModel Class Reference abstract
Base class for film injection models, handling mass transfer from the film.
#include <injectionModel.H>
Public Member Functions
TypeName ("injectionModel")
declareRunTimeSelectionTable (autoPtr, injectionModel, dictionary,(surfaceFilmRegionModel &film, const dictionary &dict),(film, dict))
injectionModel (surfaceFilmRegionModel &film)
injectionModel (const word &modelType, surfaceFilmRegionModel &film, const dictionary &dict)
virtual ~injectionModel ()
virtual void correct (scalarField &availableMass, scalarField &massToInject, scalarField &diameterToInject)=0
virtual scalar injectedMassTotal () const
virtual void patchInjectedMassTotals (scalarField &patchMasses) const
Public Member Functions inherited from filmSubModelBase
filmSubModelBase (surfaceFilmRegionModel &film)
filmSubModelBase (surfaceFilmRegionModel &film, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
filmSubModelBase (const word &modelName, surfaceFilmRegionModel &film, const dictionary &dict, const word &baseName, const word &modelType)
virtual ~filmSubModelBase ()
virtual bool writeTime () const
const surfaceFilmRegionModel & film () const
surfaceFilmRegionModel & film ()
template<class FilmType >
const FilmType & filmType () const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
subModelBase (const subModelBase &smb)
virtual ~subModelBase ()=default
const word & modelName () const
const dictionary & dict () const
const word & baseName () const
const word & modelType () const
const dictionary & coeffDict () const
const dictionary & properties () const
virtual bool defaultCoeffs (const bool printMsg) const
virtual bool active () const
virtual void cacheFields (const bool store)
virtual fileName localPath () const
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
bool getModelDict (const word &entryName, dictionary &dict) const
template<class Type >
bool getModelProperty (const word &entryName, Type &value) const
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
virtual void write (Ostream &os) const
Static Public Member Functions
static autoPtr< injectionModel > New (surfaceFilmRegionModel &film, const dictionary &dict, const word &mdoelType)
Protected Member Functions
void addToInjectedMass (const scalar dMass)
void correct ()
Protected Member Functions inherited from subModelBase
bool inLine () const
Additional Inherited Members
Public Attributes inherited from subModelBase
bool log
Protected Attributes inherited from filmSubModelBase
surfaceFilmRegionModel & filmModel_
Protected Attributes inherited from subModelBase
const word modelName_
dictionary & properties_
const dictionary dict_
const word baseName_
const word modelType_
const dictionary coeffDict_
Detailed Description
Base class for film injection models, handling mass transfer from the film.
Source files
injectionModel.H
injectionModel.C
injectionModelNew.C
Definition at line 54 of file injectionModel.H.
Constructor & Destructor Documentation
injectionModel() [1/2]
injectionModel (surfaceFilmRegionModel & film)
Definition at line 47 of file injectionModel.C.
injectionModel() [2/2]
injectionModel (const word & modelType, surfaceFilmRegionModel & film, const dictionary & dict)
Definition at line 54 of file injectionModel.C.
~injectionModel()
~injectionModel () virtual
Definition at line 68 of file injectionModel.C.
Member Function Documentation
addToInjectedMass()
void addToInjectedMass (const scalar dMass) protected
Definition at line 39 of file injectionModel.C.
Referenced by BrunDrippingInjection::correct(), curvatureSeparation::correct(), drippingInjection::correct(), and patchInjection::correct().
correct() [1/2]
void correct () protected
Definition at line 74 of file injectionModel.C.
References Foam::returnReduce(), and filmSubModelBase::writeTime().
Referenced by BrunDrippingInjection::correct(), curvatureSeparation::correct(), drippingInjection::correct(), patchInjection::correct(), and injectionModelList::correct().
TypeName()
TypeName ("injectionModel")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , injectionModel , dictionary , (surfaceFilmRegionModel &film, const dictionary &dict) , (film, dict))
New()
autoPtr< injectionModel > New (surfaceFilmRegionModel & film, const dictionary & dict, const word & mdoelType) static
Definition at line 35 of file injectionModelNew.C.
References subModelBase::dict(), Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, Foam::Info, and subModelBase::modelType().
Referenced by injectionModelList::injectionModelList().
correct() [2/2]
virtual void correct (scalarField & availableMass, scalarField & massToInject, scalarField & diameterToInject) pure virtual
Implemented in BrunDrippingInjection, curvatureSeparation, drippingInjection, and patchInjection.
injectedMassTotal()
scalar injectedMassTotal () const virtual
Definition at line 86 of file injectionModel.C.
References Foam::returnReduce().
Referenced by injectionModelList::info().
patchInjectedMassTotals()
virtual void patchInjectedMassTotals (scalarField & patchMasses) const inline virtual
Reimplemented in patchInjection.
Definition at line 149 of file injectionModel.H.
Referenced by injectionModelList::info().
The documentation for this class was generated from the following files:
src/regionModels/surfaceFilmModels/submodels/kinematic/injectionModel/injectionModel/injectionModel.H
src/regionModels/surfaceFilmModels/submodels/kinematic/injectionModel/injectionModel/injectionModel.C
src/regionModels/surfaceFilmModels/submodels/kinematic/injectionModel/injectionModel/injectionModelNew.C