OpenFOAM: pointEdgeCollapse Class Reference
pointEdgeCollapse Class Reference
Determines length of string of edges walked to point.
#include <pointEdgeCollapse.H>
Public Member Functions
pointEdgeCollapse ()
pointEdgeCollapse (const point &collapsePoint, const label collapseIndex, const label collapsePriority)
const point & collapsePoint () const
label collapseIndex () const
label collapsePriority () const
template<class TrackingData >
bool valid (TrackingData &td) const
template<class TrackingData >
void leaveDomain (const polyPatch &patch, const label patchPointi, const point &pos, TrackingData &td)
template<class TrackingData >
void enterDomain (const polyPatch &patch, const label patchPointi, const point &pos, TrackingData &td)
template<class TrackingData >
void transform (const tensor &rotTensor, TrackingData &td)
template<class TrackingData >
bool updatePoint (const polyMesh &mesh, const label pointi, const label edgeI, const pointEdgeCollapse &edgeInfo, const scalar tol, TrackingData &td)
template<class TrackingData >
bool updatePoint (const polyMesh &mesh, const label pointi, const pointEdgeCollapse &newPointInfo, const scalar tol, TrackingData &td)
template<class TrackingData >
bool updatePoint (const pointEdgeCollapse &newPointInfo, const scalar tol, TrackingData &td)
template<class TrackingData >
bool updateEdge (const polyMesh &mesh, const label edgeI, const label pointi, const pointEdgeCollapse &pointInfo, const scalar tol, TrackingData &td)
template<class TrackingData >
bool equal (const pointEdgeCollapse &, TrackingData &) const
bool operator== (const pointEdgeCollapse &) const
bool operator!= (const pointEdgeCollapse &) const
Friends
Ostream & operator<< (Ostream &, const pointEdgeCollapse &)
Istream & operator>> (Istream &, pointEdgeCollapse &)
Detailed Description
Determines length of string of edges walked to point.
Source files
pointEdgeCollapse.H
pointEdgeCollapseI.H
pointEdgeCollapse.C
Definition at line 57 of file pointEdgeCollapse.H.
Constructor & Destructor Documentation
pointEdgeCollapse() [1/2]
pointEdgeCollapse () inline
Definition at line 112 of file pointEdgeCollapseI.H.
pointEdgeCollapse() [2/2]
pointEdgeCollapse (const point & collapsePoint, const label collapseIndex, const label collapsePriority) inline
Definition at line 120 of file pointEdgeCollapseI.H.
Member Function Documentation
collapsePoint()
const point & collapsePoint () const inline
Definition at line 105 of file pointEdgeCollapse.H.
collapseIndex()
label collapseIndex () const inline
Definition at line 110 of file pointEdgeCollapse.H.
collapsePriority()
label collapsePriority () const inline
Definition at line 115 of file pointEdgeCollapse.H.
valid()
template<class TrackingData > bool valid (TrackingData & td) const inline
Definition at line 136 of file pointEdgeCollapseI.H.
leaveDomain()
template<class TrackingData > void leaveDomain (const polyPatch & patch, const label patchPointi, const point & pos, TrackingData & td) inline
Definition at line 143 of file pointEdgeCollapseI.H.
enterDomain()
template<class TrackingData > void enterDomain (const polyPatch & patch, const label patchPointi, const point & pos, TrackingData & td) inline
Definition at line 169 of file pointEdgeCollapseI.H.
transform()
template<class TrackingData > void transform (const tensor & rotTensor, TrackingData & td) inline
Definition at line 156 of file pointEdgeCollapseI.H.
References Foam::transform().
updatePoint() [1/3]
template<class TrackingData > bool updatePoint (const polyMesh & mesh, const label pointi, const label edgeI, const pointEdgeCollapse & edgeInfo, const scalar tol, TrackingData & td) inline
Definition at line 184 of file pointEdgeCollapseI.H.
References update().
updatePoint() [2/3]
template<class TrackingData > bool updatePoint (const polyMesh & mesh, const label pointi, const pointEdgeCollapse & newPointInfo, const scalar tol, TrackingData & td) inline
Definition at line 200 of file pointEdgeCollapseI.H.
References update().
updatePoint() [3/3]
template<class TrackingData > bool updatePoint (const pointEdgeCollapse & newPointInfo, const scalar tol, TrackingData & td) inline
Definition at line 215 of file pointEdgeCollapseI.H.
References update().
updateEdge()
template<class TrackingData > bool updateEdge (const polyMesh & mesh, const label edgeI, const label pointi, const pointEdgeCollapse & pointInfo, const scalar tol, TrackingData & td) inline
Definition at line 228 of file pointEdgeCollapseI.H.
References update().
equal()
template<class TrackingData > bool equal (const pointEdgeCollapse & rhs, TrackingData & td) const inline
Definition at line 243 of file pointEdgeCollapseI.H.
References Foam::operator==().
operator==()
bool operator== (const pointEdgeCollapse & rhs) const inline
Definition at line 255 of file pointEdgeCollapseI.H.
operator!=()
bool operator!= (const pointEdgeCollapse & rhs) const inline
Definition at line 267 of file pointEdgeCollapseI.H.
Friends And Related Symbol Documentation
operator<<
Ostream & operator<< (Ostream & , const pointEdgeCollapse &) friend
operator>>
Istream & operator>> (Istream & , pointEdgeCollapse &) friend
The documentation for this class was generated from the following files:
src/dynamicMesh/polyTopoChange/polyTopoChange/pointEdgeCollapse/pointEdgeCollapse.H
src/dynamicMesh/polyTopoChange/polyTopoChange/pointEdgeCollapse/pointEdgeCollapseI.H