OpenFOAM: patchDistMethod Class Reference
patchDistMethod Class Reference abstract
Specialisation of patchDist for wall distance calculation.
#include <patchDistMethod.H>
Public Member Functions
TypeName ("patchDistMethod")
declareRunTimeSelectionTable (autoPtr, patchDistMethod, dictionary,(const dictionary &dict, const fvMesh &mesh, const labelHashSet &patchIDs),(dict, mesh, patchIDs))
patchDistMethod (const fvMesh &mesh, const labelHashSet &patchIDs)
virtual ~patchDistMethod ()
const labelHashSet & patchIDs () const
virtual bool movePoints ()
virtual void updateMesh (const mapPolyMesh &)
virtual bool correct (volScalarField &y)=0
virtual bool correct (volScalarField &y, volVectorField &n)=0
template<class Type >
Foam::wordList patchTypes (const fvMesh &mesh, const labelHashSet &patchIDs)
Static Public Member Functions
static autoPtr< patchDistMethod > New (const dictionary &dict, const fvMesh &mesh, const labelHashSet &patchIDs, const word &defaultPatchDistMethod=word::null)
template<class Type >
static wordList patchTypes (const fvMesh &mesh, const labelHashSet &patchIDs)
Protected Member Functions
patchDistMethod (const patchDistMethod &)=delete
void operator= (const patchDistMethod &)=delete
Protected Attributes
const fvMesh & mesh_
const labelHashSet patchIDs_
Detailed Description
Specialisation of patchDist for wall distance calculation.
Source files
patchDistMethod.H
patchDistMethod.C
Definition at line 55 of file patchDistMethod.H.
Constructor & Destructor Documentation
patchDistMethod() [1/2]
patchDistMethod (const patchDistMethod &) protected delete
patchDistMethod() [2/2]
patchDistMethod (const fvMesh & mesh, const labelHashSet & patchIDs)
Definition at line 35 of file patchDistMethod.C.
~patchDistMethod()
~patchDistMethod () virtual
Definition at line 91 of file patchDistMethod.C.
Member Function Documentation
operator=()
void operator= (const patchDistMethod &) protected delete
TypeName()
TypeName ("patchDistMethod")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , patchDistMethod , dictionary , (const dictionary &dict, const fvMesh &mesh, const labelHashSet &patchIDs) , (dict, mesh, patchIDs))
New()
Foam::autoPtr< Foam::patchDistMethod > New (const dictionary & dict, const fvMesh & mesh, const labelHashSet & patchIDs, const word & defaultPatchDistMethod = word::null) static
Definition at line 49 of file patchDistMethod.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, Foam::Info, keyType::LITERAL, mesh, IOobjectOption::MUST_READ, patchIDs(), IOobjectOption::READ_IF_PRESENT, and dictionary::readEntry().
patchTypes() [1/2]
template<class Type > static wordList patchTypes (const fvMesh & mesh, const labelHashSet & patchIDs) static
patchIDs()
const labelHashSet & patchIDs () const inline
Definition at line 139 of file patchDistMethod.H.
References patchDistMethod::patchIDs_.
Referenced by patchDistMethod::patchTypes().
movePoints()
virtual bool movePoints () inline virtual
Reimplemented in exact.
Definition at line 145 of file patchDistMethod.H.
updateMesh()
virtual void updateMesh (const mapPolyMesh &) inline virtual
Reimplemented in exact.
Definition at line 151 of file patchDistMethod.H.
correct() [1/2]
virtual bool correct (volScalarField & y) pure virtual
Implemented in advectionDiffusion, directionalMeshWave, meshWave, meshWaveAddressing, Poisson, and exact.
correct() [2/2]
virtual bool correct (volScalarField & y, volVectorField & n) pure virtual
Implemented in advectionDiffusion, directionalMeshWave, meshWave, meshWaveAddressing, Poisson, and exact.
patchTypes() [2/2]
template<class Type > Foam::wordList patchTypes (const fvMesh & mesh, const labelHashSet & patchIDs)
Definition at line 27 of file patchDistMethodTemplates.C.
References mesh, patchDistMethod::patchIDs(), and fvPatchFieldBase::zeroGradientType().
Member Data Documentation
mesh_
const fvMesh& mesh_ protected
Definition at line 62 of file patchDistMethod.H.
patchIDs_
const labelHashSet patchIDs_ protected
Definition at line 65 of file patchDistMethod.H.
Referenced by patchDistMethod::patchIDs().
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/wallDist/patchDistMethods/patchDistMethod/patchDistMethod.H
src/finiteVolume/fvMesh/wallDist/patchDistMethods/patchDistMethod/patchDistMethod.C
src/finiteVolume/fvMesh/wallDist/patchDistMethods/patchDistMethod/patchDistMethodTemplates.C