OpenFOAM: sampledSets Class Reference
sampledSets Class Reference
Set of sets to sample.
#include <sampledSets.H>
Public Member Functions
TypeName ("sets")
sampledSets (const word &name, const Time &runTime, const dictionary &dict)
sampledSets (const word &name, const objectRegistry &obr, const dictionary &dict, const bool loadFromFiles=false)
virtual ~sampledSets ()=default
bool verbose (const bool on) noexcept
virtual bool read (const dictionary &)
virtual bool execute ()
virtual bool write ()
void correct ()
virtual void updateMesh (const mapPolyMesh &)
virtual void movePoints (const polyMesh &)
virtual void readUpdate (const polyMesh::readUpdateState state)
template<class GeoField >
Foam::tmp< GeoField > getOrLoadField (const word &fieldName) const
Public Member Functions inherited from fvMeshFunctionObject
TypeName ("fvMeshFunctionObject")
fvMeshFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
fvMeshFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
virtual ~fvMeshFunctionObject ()=default
Public Member Functions inherited from regionFunctionObject
TypeName ("regionFunctionObject")
regionFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
regionFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
virtual ~regionFunctionObject ()=default
template<class ObjectType >
const ObjectType * lookupObjectPtr (const word &fieldName) const
template<class ObjectType >
ObjectType * lookupObjectRefPtr (const word &fieldName) const
Public Member Functions inherited from stateFunctionObject
stateFunctionObject (const word &name, const Time &runTime)
virtual ~stateFunctionObject ()=default
dictionary & propertyDict ()
bool foundProperty (const word &entryName) const
void clearTrigger ()
label getTrigger () const
bool setTrigger (const label triggeri)
bool getDict (const word &entryName, dictionary &dict) const
bool getObjectDict (const word &objectName, const word &entryName, dictionary &dict) const
template<class Type >
Type getProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getProperty (const word &entryName, Type &value) const
template<class Type >
void setProperty (const word &entryName, const Type &value)
template<class Type >
Type getObjectProperty (const word &objectName, const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getObjectProperty (const word &objectName, const word &entryName, Type &value) const
template<class Type >
void setObjectProperty (const word &objectName, const word &entryName, const Type &value)
template<class Type >
void setResult (const word &entryName, const Type &value)
template<class Type >
void setObjectResult (const word &objectName, const word &entryName, const Type &value)
template<class Type >
Type getResult (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
Type getObjectResult (const word &objectName, const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getObjectResult (const word &objectName, const word &entryName, Type &value) const
word resultType (const word &entryName) const
word objectResultType (const word &objectName, const word &entryName) const
wordList objectResultEntries () const
wordList objectResultEntries (const word &objectName) const
void writeResultEntries (Ostream &os) const
void writeResultEntries (const word &objectName, Ostream &os) const
void writeAllResultEntries (Ostream &os) const
Public Member Functions inherited from timeFunctionObject
timeFunctionObject (const word &name, const Time &runTime)
virtual ~timeFunctionObject ()=default
const Time & time () const
objectRegistry & storedObjects ()
const objectRegistry & storedObjects () const
Public Member Functions inherited from functionObject
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name, const bool withNamePrefix=defaultUseNamePrefix)
autoPtr< functionObject > clone () const
virtual ~functionObject ()=default
virtual const word & type () const =0
const word & name () const noexcept
bool useNamePrefix () const noexcept
bool useNamePrefix (bool on) noexcept
virtual bool execute (const label subIndex)
virtual bool end ()
virtual bool adjustTimeStep ()
virtual bool filesModified () const
Public Member Functions inherited from PtrList< sampledSet >
constexpr PtrList () noexcept
PtrList (const label len)
PtrList (const PtrList< sampledSet > &list)
PtrList (PtrList< sampledSet > &&list)
PtrList (UList< sampledSet * > &list)
PtrList (const PtrList< sampledSet > &list, const CloneArg &cloneArgs)
PtrList (PtrList< sampledSet > &list, bool reuse)
PtrList (const SLPtrList< sampledSet > &list)
PtrList (Istream &is, const INew &inew)
PtrList (Istream &is)
~PtrList ()
PtrList< sampledSet > clone (Args &&... args) const
Foam::PtrList< sampledSet > clone (Args &&... args) const
const sampledSet * set (const label i) const
autoPtr< sampledSet > set (const label i, sampledSet *ptr)
autoPtr< sampledSet > set (const label i, std::unique_ptr< sampledSet > &&ptr)
autoPtr< sampledSet > set (const label i, autoPtr< sampledSet > &&ptr)
autoPtr< sampledSet > set (const label i, const refPtr< sampledSet > &ptr)
autoPtr< sampledSet > set (const label i, const tmp< sampledSet > &ptr)
autoPtr< sampledSet > set (const label i, autoPtr< sampledSet > &ptr)
void clear ()
void free ()
void resize (const label newLen)
sampledSet & emplace_back (Args &&... args)
void push_back (sampledSet *ptr)
void push_back (std::unique_ptr< sampledSet > &&ptr)
void push_back (autoPtr< sampledSet > &&ptr)
void push_back (const refPtr< sampledSet > &ptr)
void push_back (const tmp< sampledSet > &ptr)
void push_back (PtrList< sampledSet > &&other)
void push_back (autoPtr< sampledSet > &ptr)=delete
sampledSet & emplace_set (const label i, Args &&... args)
sampledSet & emplace (const label i, Args &&... args)
autoPtr< sampledSet > release (const label i)
void transfer (PtrList< sampledSet > &list)
void operator= (const PtrList< sampledSet > &list)
void operator= (PtrList< sampledSet > &&list)
void setSize (const label newLen)
void append (autoPtr< sampledSet > &ptr)
void append (sampledSet *ptr)
void append (std::unique_ptr< sampledSet > &&ptr)
void append (autoPtr< sampledSet > &&ptr)
void append (const refPtr< sampledSet > &ptr)
void append (const tmp< sampledSet > &ptr)
void append (PtrList< sampledSet > &&other)
Public Member Functions inherited from UPtrList< T >
constexpr UPtrList () noexcept
UPtrList (const label len)
UPtrList (const UPtrList< T > &list)
UPtrList (UPtrList< T > &&list)
UPtrList (UPtrList< T > &list, bool reuse)
UPtrList (PtrList< T > &list)
UPtrList (const UList< T * > &list)
UPtrList (UList< T > &list)
bool empty () const noexcept
label size () const noexcept
label count () const noexcept
T & front ()
const T & front () const
T & back ()
const T & back () const
const T * test (const label i) const
const T * get (const label i) const
T * get (const label i)
const T * set (const label i) const
void clear ()
void free ()
void resize (const label newLen)
label squeezeNull ()
void trimTrailingNull ()
void push_back (T *ptr)
void push_back (UPtrList< T > &&other)
void swap (UPtrList< T > &list)
void transfer (UPtrList< T > &list)
T * set (const label i, T *ptr)
void reorder (const labelUList &oldToNew, const bool check=false)
void sortOrder (const labelUList &order, const bool check=false)
void checkNonNull () const
const T & at (const label i) const
T & at (const label i)
const T & operator[] (const label i) const
T & operator[] (const label i)
FOAM_DEPRECATED_FOR (2022-09, "get(), set() or test() methods") const T *operator()(const label i) const
void operator= (const UPtrList< T > &list)
void operator= (UPtrList< T > &&list)
T ** begin_ptr () noexcept
T ** end_ptr () noexcept
iterator begin ()
iterator end () noexcept
const_iterator cbegin () const
const_iterator cend () const noexcept
const_iterator begin () const
const_iterator end () const noexcept
void setSize (const label n)
T & first ()
const T & first () const
T & last ()
const T & last () const
void append (T *ptr)
void append (UPtrList< T > &&other)
Additional Inherited Members
Public Types inherited from UPtrList< T >
typedef T value_type
typedef T & reference
typedef const T & const_reference
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &runTime, const dictionary &dict)
Public Attributes inherited from functionObject
bool log
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
static bool defaultUseNamePrefix
static word outputPrefix
Protected Member Functions inherited from fvMeshFunctionObject
fvMeshFunctionObject (const fvMeshFunctionObject &)=delete
void operator= (const fvMeshFunctionObject &)=delete
Protected Member Functions inherited from regionFunctionObject
virtual const objectRegistry & obr () const
template<class ObjectType >
bool foundObject (const word &fieldName) const
template<class ObjectType >
const ObjectType * cfindObject (const word &fieldName) const
template<class ObjectType >
const ObjectType * findObject (const word &fieldName) const
template<class ObjectType >
ObjectType * findObject (const word &fieldName)
template<class ObjectType >
ObjectType * getObjectPtr (const word &fieldName) const
template<class ObjectType >
const ObjectType & lookupObject (const word &fieldName) const
template<class ObjectType >
ObjectType & lookupObjectRef (const word &fieldName) const
template<class ObjectType >
bool store (word &fieldName, const tmp< ObjectType > &tfield, bool cacheable=false)
template<class ObjectType >
bool storeInDb (const word &fieldName, const tmp< ObjectType > &tfield, const objectRegistry &obr)
bool writeObject (const word &fieldName)
bool clearObject (const word &fieldName)
void clearObjects (const wordList &objNames)
regionFunctionObject (const regionFunctionObject &)=delete
void operator= (const regionFunctionObject &)=delete
Protected Member Functions inherited from stateFunctionObject
const functionObjects::properties & stateDict () const
functionObjects::properties & stateDict ()
stateFunctionObject (const stateFunctionObject &)=delete
void operator= (const stateFunctionObject &)=delete
Protected Member Functions inherited from timeFunctionObject
void clearOutputObjects (const wordList &objNames)
timeFunctionObject (const timeFunctionObject &)=delete
void operator= (const timeFunctionObject &)=delete
Protected Member Functions inherited from functionObject
word scopedName (const word &name) const
Protected Member Functions inherited from PtrList< sampledSet >
void readIstream (Istream &is, const INew &inew)
Protected Member Functions inherited from UPtrList< T >
void setAddressableSize (const label n) noexcept
label find_next (label pos) const
UPtrList (Detail::PtrListDetail< T > &&ptrs)
Protected Attributes inherited from fvMeshFunctionObject
const fvMesh & mesh_
Protected Attributes inherited from regionFunctionObject
word subRegistryName_
const objectRegistry & obr_
const objectRegistry * obrPtr_
Protected Attributes inherited from timeFunctionObject
const Time & time_
Protected Attributes inherited from UPtrList< T >
Detail::PtrListDetail< T > ptrs_
Detailed Description
Set of sets to sample.
The write() method is used to sample and write files.
Example of function object specification:
surfaces
{
    type    sets;
    libs    (sampling);
    // Write at same frequency as fields
    writeControl    writeTime;
    writeInterval   1;
    // Fields to be sampled
    fields          (p U);
    // Scheme to obtain values
    interpolationScheme cellPoint;
    // Output format
    setFormat   vtk;
    formatOptions
    {
        vtk
        {
            precision  10;
        }
    }
    sets
    {
        Uref
        {
            type    cloud;
            axis    xyz;
            points  ((-0.0508 0.0508 0.01));
        }
    }
}
Entries:
Property Description Required Default
type Type-name: sets yes
sets Dictionary or list of sample sets expected
fields word/regex list of fields to sample yes
interpolationScheme scheme to obtain values no cellPoint
setFormat output format yes
sampleOnExecute Sample (store) on execution as well no false
formatOptions dictionary of format options no
Additional per-set entries:
Property Description Required Default
store Store surface/fields on registry no
setFormat output format no
formatOptions dictionary of format options no
Note
Special setFormat probes can be used to output ensemble results in a format similar to the probes function object.
Source files
sampledSets.H
sampledSets.C
sampledSetsImpl.C
Definition at line 188 of file sampledSets.H.
Constructor & Destructor Documentation
sampledSets() [1/2]
sampledSets (const word & name, const Time & runTime, const dictionary & dict)
Definition at line 417 of file sampledSets.C.
References fileName::clean(), dict, and sampledSets::read().
sampledSets() [2/2]
sampledSets (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false)
Definition at line 453 of file sampledSets.C.
References fileName::clean(), dict, and sampledSets::read().
~sampledSets()
virtual ~sampledSets () virtual default
Member Function Documentation
TypeName()
TypeName ("sets")
verbose()
bool verbose (const bool on) noexcept
Definition at line 492 of file sampledSets.C.
read()
bool read (const dictionary & dict) virtual
Reimplemented from regionFunctionObject.
Definition at line 500 of file sampledSets.C.
References PtrList< T >::clear(), dict, Foam::endl(), dictionary::findEntry(), Foam::flatOutput(), forAll, dictionary::getOrDefault(), Foam::Info, keyType::LITERAL, UPstream::master(), Foam::nl, Foam::Pout, dictionary::readEntry(), and s().
Referenced by sampledSets::sampledSets(), and sampledSets::sampledSets().
execute()
bool execute () virtual
Implements functionObject.
Definition at line 707 of file sampledSets.C.
write()
bool write () virtual
Implements functionObject.
Definition at line 718 of file sampledSets.C.
correct()
void correct ()
Definition at line 724 of file sampledSets.C.
updateMesh()
void updateMesh (const mapPolyMesh & mpm) virtual
Reimplemented from functionObject.
Definition at line 730 of file sampledSets.C.
References correct().
movePoints()
void movePoints (const polyMesh & mesh) virtual
Reimplemented from functionObject.
Definition at line 739 of file sampledSets.C.
References correct(), and mesh.
readUpdate()
void readUpdate (const polyMesh::readUpdateState state) virtual
Definition at line 748 of file sampledSets.C.
References correct(), and polyMesh::UNCHANGED.
getOrLoadField()
template<class GeoField > Foam::tmp< GeoField > getOrLoadField (const word & fieldName) const
Definition at line 32 of file sampledSetsImpl.C.
References fvMeshFunctionObject::mesh_, IOobjectOption::MUST_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, and PtrList< sampledSet >::PtrList().
The documentation for this class was generated from the following files:
src/sampling/sampledSet/sampledSets/sampledSets.H
src/sampling/sampledSet/sampledSets/sampledSets.C
src/sampling/sampledSet/sampledSets/sampledSetsImpl.C