OpenFOAM: OSHA1streamAllocator Class Reference
OSHA1streamAllocator Class Reference
#include <OSHA1stream.H>
Public Member Functions
SHA1 & sha1 () noexcept
SHA1Digest digest ()
void reset ()
Protected Types
typedef osha1stream stream_type
Protected Member Functions
OSHA1streamAllocator ()=default
Protected Attributes
stream_type stream_
Detailed Description
Definition at line 130 of file OSHA1stream.H.
Member Typedef Documentation
stream_type
typedef osha1stream stream_type protected
Definition at line 136 of file OSHA1stream.H.
Constructor & Destructor Documentation
OSHA1streamAllocator()
OSHA1streamAllocator () protected default
Member Function Documentation
sha1()
SHA1 & sha1 () inline noexcept
Definition at line 153 of file OSHA1stream.H.
References osha1stream::sha1(), and OSHA1streamAllocator::stream_.
Referenced by OSHA1stream::rewind().
digest()
SHA1Digest digest () inline
Definition at line 160 of file OSHA1stream.H.
References osha1stream::sha1(), and OSHA1streamAllocator::stream_.
reset()
void reset () inline
Definition at line 167 of file OSHA1stream.H.
References osha1stream::sha1(), and OSHA1streamAllocator::stream_.
Member Data Documentation
stream_
stream_type stream_ protected
Definition at line 139 of file OSHA1stream.H.
Referenced by OSHA1streamAllocator::digest(), OSHA1streamAllocator::reset(), and OSHA1streamAllocator::sha1().
The documentation for this class was generated from the following file:
src/OpenFOAM/db/IOstreams/hashes/OSHA1stream.H