OpenFOAM: IATE Class Reference
IATE Class Reference
IATE (Interfacial Area Transport Equation) bubble diameter model.
#include <IATE.H>
Public Member Functions
TypeName ("IATE")
IATE (const dictionary &diameterProperties, const phaseModel &phase)
virtual ~IATE ()
const volScalarField & kappai () const
tmp< volScalarField > a () const
virtual tmp< volScalarField > d () const
virtual void correct ()
virtual bool read (const dictionary &phaseProperties)
TypeName ("IATE")
IATE (const dictionary &diameterProperties, const phaseModel &phase)
virtual ~IATE ()
const volScalarField & kappai () const
tmp< volScalarField > a () const
virtual tmp< volScalarField > d () const
virtual void correct ()
virtual bool read (const dictionary &phaseProperties)
Public Member Functions inherited from diameterModel
TypeName ("diameterModel")
declareRunTimeSelectionTable (autoPtr, diameterModel, dictionary,(const dictionary &dict, const phaseModel &phase),(dict, phase))
diameterModel (const dictionary &dict, const phaseModel &phase)
virtual ~diameterModel ()=default
const dictionary & diameterProperties () const
const phaseModel & phase () const
TypeName ("diameterModel")
declareRunTimeSelectionTable (autoPtr, diameterModel, dictionary,(const dictionary &dict, const phaseModel &phase),(dict, phase))
diameterModel (const dictionary &dict, const phaseModel &phase)
virtual ~diameterModel ()=default
const dictionary & diameterProperties () const
const phaseModel & phase () const
Friends
class IATEsource
Additional Inherited Members
Static Public Member Functions inherited from diameterModel
static autoPtr< diameterModel > New (const dictionary &diameterProperties, const phaseModel &phase)
static autoPtr< diameterModel > New (const dictionary &dict, const phaseModel &phase)
Protected Attributes inherited from diameterModel
dictionary diameterProperties_
const phaseModel & phase_
Detailed Description
IATE (Interfacial Area Transport Equation) bubble diameter model.
Solves for the interfacial curvature per unit volume of the phase rather than interfacial area per unit volume to avoid stability issues relating to the consistency requirements between the phase fraction and interfacial area per unit volume. In every other respect this model is as presented in the paper:
Reference:
    Ishii, M., Kim, S., & Kelly, J. (2005).
    Development of interfacial area transport equation.
    Nuclear Engineering and Technology, 37(6), 525-536.
Source files
IATE.H
IATE.C
Solves for the interfacial curvature per unit volume of the phase rather than interfacial area per unit volume to avoid stability issues relating to the consistency requirements between the phase fraction and interfacial area per unit volume. In every other respect this model is as presented in the paper:
    "Development of Interfacial Area Transport Equation"
    Ishii, M., Kim, S. and Kelly, J.,
    Nuclear Engineering and Technology, Vol.37 No.6 December 2005
Source files
IATE.H
IATE.C
Definition at line 64 of file IATE.H.
Constructor & Destructor Documentation
IATE() [1/2]
IATE (const dictionary & diameterProperties, const phaseModel & phase)
Definition at line 55 of file IATE.C.
References Foam::dimLength, Foam::dimless, and Foam::name().
~IATE() [1/2]
~IATE () virtual
Definition at line 99 of file IATE.C.
IATE() [2/2]
IATE (const dictionary & diameterProperties, const phaseModel & phase)
~IATE() [2/2]
virtual ~IATE () virtual
Member Function Documentation
TypeName() [1/2]
TypeName ("IATE")
kappai() [1/2]
const volScalarField & kappai () const inline
Definition at line 119 of file IATE.H.
a() [1/2]
tmp< volScalarField > a () const inline
Definition at line 125 of file IATE.H.
References diameterModel::phase_.
d() [1/2]
virtual tmp< volScalarField > d () const inline virtual
Implements diameterModel.
Definition at line 131 of file IATE.H.
correct() [1/2]
void correct () virtual
Reimplemented from diameterModel.
Definition at line 110 of file IATE.C.
References Foam::fvc::average(), Foam::fvc::ddt(), Foam::fvm::ddt(), Foam::fvc::div(), Foam::fvm::div(), forAll, fvOptions, Foam::max(), options::New(), R, Foam::fvm::Sp(), and Foam::fvm::SuSp().
read() [1/2]
bool read (const dictionary & phaseProperties) virtual
Implements diameterModel.
Definition at line 164 of file IATE.C.
References diameterModel::read(), and PtrList< T >::transfer().
TypeName() [2/2]
TypeName ("IATE")
kappai() [2/2]
const volScalarField & kappai () const inline
Definition at line 118 of file IATE.H.
a() [2/2]
tmp< volScalarField > a () const inline
Definition at line 124 of file IATE.H.
References diameterModel::phase_.
d() [2/2]
virtual tmp< volScalarField > d () const inline virtual
Implements diameterModel.
Definition at line 130 of file IATE.H.
correct() [2/2]
virtual void correct () virtual
Reimplemented from diameterModel.
read() [2/2]
virtual bool read (const dictionary & phaseProperties) virtual
Implements diameterModel.
Friends And Related Symbol Documentation
IATEsource
IATEsource friend
Definition at line 96 of file IATE.H.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/twoPhaseSystem/diameterModels/IATE/IATE.H
src/phaseSystemModels/twoPhaseEuler/twoPhaseSystem/diameterModels/IATE/IATE.H
src/phaseSystemModels/reactingEuler/twoPhaseSystem/diameterModels/IATE/IATE.C
src/phaseSystemModels/twoPhaseEuler/twoPhaseSystem/diameterModels/IATE/IATE.C