OpenFOAM: limitWith< Type > Class Template Reference
limitWith< Type > Class Template Reference
Numerics » Finite volume numerical schemes » Surface interpolation schemes » Limited interpolation schemes
limitWith differencing scheme limits the specified scheme with the specified limiter.
#include <limitWith.H>
Public Member Functions
TypeName ("limitWith")
limitWith (const fvMesh &mesh, Istream &is)
limitWith (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &is)
virtual tmp< surfaceScalarField > weights (const GeometricField< Type, fvPatchField, volMesh > &vf) const
virtual bool corrected () const
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > &vf) const
Public Member Functions inherited from surfaceInterpolationScheme< Type >
TypeName ("surfaceInterpolationScheme")
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, Mesh,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, MeshFlux,(const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
surfaceInterpolationScheme (const fvMesh &mesh)
virtual ~surfaceInterpolationScheme ()=default
const fvMesh & mesh () const
virtual tmp< GeometricField< typename innerProduct< vector, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf) const
tmp< GeometricField< typename innerProduct< vector, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const tmp< GeometricField< Type, fvPatchField, volMesh > > &) const
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &) const
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > &) const
template<class SFType >
Foam::tmp< Foam::GeometricField< typename Foam::innerProduct< typename SFType::value_type, Type >::type, Foam::fvsPatchField, Foam::surfaceMesh > > dotInterpolate (const SFType &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf, const tmp< surfaceScalarField > &tlambdas)
tmp< GeometricField< typename innerProduct< vector, scalar >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const GeometricField< scalar, fvPatchField, volMesh > &) const
Foam::tmp< Foam::GeometricField< typename Foam::innerProduct< Foam::vector, Foam::scalar >::type, Foam::fvsPatchField, Foam::surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const GeometricField< scalar, fvPatchField, volMesh > &) const
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Additional Inherited Members
Static Public Member Functions inherited from surfaceInterpolationScheme< Type >
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData)
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &, const tmp< surfaceScalarField > &)
template<class SFType >
static tmp< GeometricField< typename innerProduct< typename SFType::value_type, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const SFType &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf, const tmp< surfaceScalarField > &tlambdas)
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &)
Detailed Description
template<class Type>
class Foam::limitWith< Type >
limitWith differencing scheme limits the specified scheme with the specified limiter.
Source files
limitWith.H
limitWith.C
Definition at line 52 of file limitWith.H.
Constructor & Destructor Documentation
limitWith() [1/2]
template<class Type > limitWith (const fvMesh & mesh, Istream & is) inline
Definition at line 83 of file limitWith.H.
limitWith() [2/2]
template<class Type > limitWith (const fvMesh & mesh, const surfaceScalarField & faceFlux, Istream & is) inline
Definition at line 101 of file limitWith.H.
Member Function Documentation
TypeName()
template<class Type > TypeName ("limitWith< Type >")
weights()
template<class Type > virtual tmp< surfaceScalarField > weights (const GeometricField< Type, fvPatchField, volMesh > & vf) const inline virtual
Implements surfaceInterpolationScheme< Type >.
Definition at line 123 of file limitWith.H.
References Foam::limiter(), and limitWith< Type >::weights().
Referenced by limitWith< Type >::weights().
corrected()
template<class Type > virtual bool corrected () const inline virtual
Reimplemented from surfaceInterpolationScheme< Type >.
Definition at line 137 of file limitWith.H.
correction()
template<class Type > virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > & vf) const inline virtual
Reimplemented from surfaceInterpolationScheme< Type >.
Definition at line 145 of file limitWith.H.
The documentation for this class was generated from the following file:
src/finiteVolume/interpolation/surfaceInterpolation/limitedSchemes/limitWith/limitWith.H