OpenFOAM: surfaceReader Class Reference
surfaceReader Class Reference abstract
Abstract base class for surface readers with fields.
#include <surfaceReader.H>
Public Member Functions
TypeName ("surfaceReader")
declareRunTimeSelectionTable (autoPtr, surfaceReader, fileName,(const fileName &fName, const dictionary &options),(fName, options))
surfaceReader (const fileName &fName)
surfaceReader (const fileName &fName, const dictionary &options)
virtual ~surfaceReader ()=default
virtual const meshedSurface & geometry (const label timeIndex)=0
virtual instantList times () const =0
virtual wordList fieldNames (const label timeIndex) const =0
virtual tmp< Field< scalar > > field (const label timeIndex, const label fieldIndex, const scalar &refValue=pTraits< scalar >::zero) const =0
virtual tmp< Field< vector > > field (const label timeIndex, const label fieldIndex, const vector &refValue=pTraits< vector >::zero) const =0
virtual tmp< Field< sphericalTensor > > field (const label timeIndex, const label fieldIndex, const sphericalTensor &refValue=pTraits< sphericalTensor >::zero) const =0
virtual tmp< Field< symmTensor > > field (const label timeIndex, const label fieldIndex, const symmTensor &refValue=pTraits< symmTensor >::zero) const =0
virtual tmp< Field< tensor > > field (const label timeIndex, const label fieldIndex, const tensor &refValue=pTraits< tensor >::zero) const =0
Static Public Member Functions
static dictionary formatOptions (const dictionary &dict, const word &formatName, const word &entryName="formatOptions")
static autoPtr< surfaceReader > New (const word &readType, const fileName &fName, const dictionary &options=dictionary())
Protected Attributes
fileName fileName_
Detailed Description
Abstract base class for surface readers with fields.
Some readers support different input options, these are typically specified as 'readOptions' in the containing dictionary.
readOptions
{
    default
    {
        verbose     false;
    }
    ensight
    {
        masterOnly  false;
    }
}
Source files
surfaceReader.H
surfaceReader.C
Definition at line 67 of file surfaceReader.H.
Constructor & Destructor Documentation
surfaceReader() [1/2]
surfaceReader (const fileName & fName) explicit
Definition at line 48 of file surfaceReader.C.
surfaceReader() [2/2]
surfaceReader (const fileName & fName, const dictionary & options)
Definition at line 57 of file surfaceReader.C.
~surfaceReader()
virtual ~surfaceReader () virtual default
Member Function Documentation
TypeName()
TypeName ("surfaceReader")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , surfaceReader , fileName , (const fileName &fName, const dictionary &options) , (fName, options))
formatOptions()
Foam::dictionary formatOptions (const dictionary & dict, const word & formatName, const word & entryName = "formatOptions") static
Definition at line 35 of file surfaceReader.C.
References dict, and Foam::fileFormats::getFormatOptions().
New()
Foam::autoPtr< Foam::surfaceReader > New (const word & readType, const fileName & fName, const dictionary & options = dictionary()) static
Definition at line 70 of file surfaceReader.C.
References Foam::exit(), Foam::FatalError, and FatalErrorInLookup.
Referenced by surfaceNoise::initialise(), MappedFile< Type >::MappedFile(), and boundaryDataSurfaceReader::readField().
geometry()
virtual const meshedSurface & geometry (const label timeIndex) pure virtual
Implemented in boundaryDataSurfaceReader, and ensightSurfaceReader.
times()
virtual instantList times () const pure virtual
Implemented in boundaryDataSurfaceReader, and ensightSurfaceReader.
fieldNames()
virtual wordList fieldNames (const label timeIndex) const pure virtual
Implemented in boundaryDataSurfaceReader, and ensightSurfaceReader.
field() [1/5]
virtual tmp< Field< scalar > > field (const label timeIndex, const label fieldIndex, const scalar & refValue = pTraits< scalar >::zero) const pure virtual
Implemented in boundaryDataSurfaceReader, and ensightSurfaceReader.
field() [2/5]
virtual tmp< Field< vector > > field (const label timeIndex, const label fieldIndex, const vector & refValue = pTraits< vector >::zero) const pure virtual
Implemented in boundaryDataSurfaceReader, and ensightSurfaceReader.
field() [3/5]
virtual tmp< Field< sphericalTensor > > field (const label timeIndex, const label fieldIndex, const sphericalTensor & refValue = pTraits< sphericalTensor >::zero) const pure virtual
Implemented in boundaryDataSurfaceReader, and ensightSurfaceReader.
field() [4/5]
virtual tmp< Field< symmTensor > > field (const label timeIndex, const label fieldIndex, const symmTensor & refValue = pTraits< symmTensor >::zero) const pure virtual
Implemented in boundaryDataSurfaceReader, and ensightSurfaceReader.
field() [5/5]
virtual tmp< Field< tensor > > field (const label timeIndex, const label fieldIndex, const tensor & refValue = pTraits< tensor >::zero) const pure virtual
Implemented in boundaryDataSurfaceReader, and ensightSurfaceReader.
Member Data Documentation
fileName_
fileName fileName_ protected
Definition at line 72 of file surfaceReader.H.
The documentation for this class was generated from the following files:
src/surfMesh/readers/common/surfaceReader.H
src/surfMesh/readers/common/surfaceReader.C