OpenFOAM: PengRobinsonGas< Specie > Class Template Reference
PengRobinsonGas< Specie > Class Template Reference
Thermophysical models » Specie » Equation of state
PengRobinsonGas gas equation of state.
#include <PengRobinsonGas.H>
Public Member Functions
PengRobinsonGas (const Specie &sp, const scalar &Tc, const scalar &Vc, const scalar &Zc, const scalar &Pc, const scalar &omega)
PengRobinsonGas (const dictionary &dict)
PengRobinsonGas (const word &name, const PengRobinsonGas &)
autoPtr< PengRobinsonGas > clone () const
scalar rho (scalar p, scalar T) const
scalar H (const scalar p, const scalar T) const
scalar Cp (scalar p, scalar T) const
scalar E (const scalar p, const scalar T) const
scalar Cv (scalar p, scalar T) const
scalar S (const scalar p, const scalar T) const
scalar psi (scalar p, scalar T) const
scalar Z (scalar p, scalar T) const
scalar CpMCv (scalar p, scalar T) const
void write (Ostream &os) const
void operator+= (const PengRobinsonGas &)
void operator*= (const scalar)
Static Public Member Functions
static autoPtr< PengRobinsonGas > New (const dictionary &dict)
static word typeName ()
Static Public Attributes
static const bool incompressible = false
static const bool isochoric = false
Friends
PengRobinsonGas operator+ (const PengRobinsonGas &, const PengRobinsonGas &)
PengRobinsonGas operator* (const scalar s, const PengRobinsonGas &)
PengRobinsonGas operator== (const PengRobinsonGas &, const PengRobinsonGas &)
Ostream & operator<< (Ostream &, const PengRobinsonGas &)
Detailed Description
template<class Specie>
class Foam::PengRobinsonGas< Specie >
PengRobinsonGas gas equation of state.
Source files
PengRobinsonGas.H
PengRobinsonGasI.H
PengRobinsonGas.C
Definition at line 85 of file PengRobinsonGas.H.
Constructor & Destructor Documentation
PengRobinsonGas() [1/3]
template<class Specie > PengRobinsonGas (const Specie & sp, const scalar & Tc, const scalar & Vc, const scalar & Zc, const scalar & Pc, const scalar & omega) inline
Definition at line 27 of file PengRobinsonGasI.H.
PengRobinsonGas() [2/3]
template<class Specie > PengRobinsonGas (const dictionary & dict)
Definition at line 27 of file PengRobinsonGas.C.
PengRobinsonGas() [3/3]
template<class Specie > PengRobinsonGas (const word & name, const PengRobinsonGas< Specie > & pg) inline
Definition at line 49 of file PengRobinsonGasI.H.
Member Function Documentation
clone()
template<class Specie > Foam::autoPtr< Foam::PengRobinsonGas< Specie > > clone () const inline
Definition at line 66 of file PengRobinsonGasI.H.
References Foam::New().
New()
template<class Specie > Foam::autoPtr< Foam::PengRobinsonGas< Specie > > New (const dictionary & dict) inline static
Definition at line 74 of file PengRobinsonGasI.H.
References dict, and Foam::New().
typeName()
template<class Specie > static word typeName () inline static
Definition at line 141 of file PengRobinsonGas.H.
rho()
template<class Specie > Foam::scalar rho (scalar p, scalar T) const inline
Definition at line 86 of file PengRobinsonGasI.H.
References p, R, and T.
H()
template<class Specie > Foam::scalar H (const scalar p, const scalar T) const inline
Definition at line 98 of file PengRobinsonGasI.H.
References alpha, B, Foam::log(), p, Pr(), R, Foam::sqr(), Foam::sqrt(), and T.
Cp()
template<class Specie > Foam::scalar Cp (scalar p, scalar T) const inline
Definition at line 120 of file PengRobinsonGasI.H.
References A, alpha, b, B, Foam::log(), M, N(), p, Foam::pow3(), Foam::sqr(), Foam::sqrt(), and T.
E()
template<class Specie > Foam::scalar E (const scalar p, const scalar T) const inline
Definition at line 151 of file PengRobinsonGasI.H.
References alpha, B, Foam::log(), p, Pr(), R, Foam::sqr(), Foam::sqrt(), and T.
Cv()
template<class Specie > Foam::scalar Cv (scalar p, scalar T) const inline
Definition at line 172 of file PengRobinsonGasI.H.
References b, B, Foam::log(), p, Foam::pow3(), Foam::sqr(), Foam::sqrt(), and T.
S()
template<class Specie > Foam::scalar S (const scalar p, const scalar T) const inline
Definition at line 195 of file PengRobinsonGasI.H.
References B, Foam::log(), p, Pr(), R, Foam::sqr(), Foam::sqrt(), and T.
psi()
template<class Specie > Foam::scalar psi (scalar p, scalar T) const inline
Definition at line 222 of file PengRobinsonGasI.H.
References p, R, and T.
Z()
template<class Specie > Foam::scalar Z (scalar p, scalar T) const inline
Definition at line 235 of file PengRobinsonGasI.H.
References A, Foam::acos(), alpha, b, B, Foam::cbrt(), Foam::cos(), D, Foam::mag(), Foam::max(), p, Foam::constant::mathematical::pi(), Foam::pow3(), Foam::sqr(), Foam::sqrt(), and T.
CpMCv()
template<class Specie > Foam::scalar CpMCv (scalar p, scalar T) const inline
Definition at line 297 of file PengRobinsonGasI.H.
References A, alpha, b, B, M, N(), p, R, Foam::sqr(), Foam::sqrt(), and T.
write()
template<class Specie > void write (Ostream & os) const
Definition at line 47 of file PengRobinsonGas.C.
References os().
operator+=()
template<class Specie > void operator+= (const PengRobinsonGas< Specie > &) inline
Definition at line 325 of file PengRobinsonGasI.H.
References Foam::mag(), and Y.
operator*=()
template<class Specie > void operator*= (const scalar s) inline
Definition at line 348 of file PengRobinsonGasI.H.
References s().
Friends And Related Symbol Documentation
operator+
template<class Specie > PengRobinsonGas operator+ (const PengRobinsonGas< Specie > & , const PengRobinsonGas< Specie > &) friend
operator*
template<class Specie > PengRobinsonGas operator* (const scalar s, const PengRobinsonGas< Specie > &) friend
operator==
template<class Specie > PengRobinsonGas operator== (const PengRobinsonGas< Specie > & , const PengRobinsonGas< Specie > &) friend
operator<<
template<class Specie > Ostream & operator<< (Ostream & , const PengRobinsonGas< Specie > &) friend
Member Data Documentation
incompressible
template<class Specie > const bool incompressible = false static
Definition at line 150 of file PengRobinsonGas.H.
isochoric
template<class Specie > const bool isochoric = false static
Definition at line 153 of file PengRobinsonGas.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/equationOfState/PengRobinsonGas/PengRobinsonGas.H
src/thermophysicalModels/specie/equationOfState/PengRobinsonGas/PengRobinsonGas.C
src/thermophysicalModels/specie/equationOfState/PengRobinsonGas/PengRobinsonGasI.H