OpenFOAM: ParticleForce< CloudType > Class Template Reference
ParticleForce< CloudType > Class Template Reference
Lagrangian particle models » Submodels » Kinematic » Forces
Abstract base class for particle forces.
#include <ParticleForce.H>
Public Types
typedef VectorSpace< Vector< vector >, vector, 2 > returnType
Public Member Functions
TypeName ("particleForce")
declareRunTimeSelectionTable (autoPtr, ParticleForce, dictionary,(CloudType &owner, const fvMesh &mesh, const dictionary &dict),(owner, mesh, dict))
ParticleForce (CloudType &owner, const fvMesh &mesh, const dictionary &dict, const word &forceType, const bool readCoeffs)
ParticleForce (const ParticleForce &pf)
virtual autoPtr< ParticleForce< CloudType > > clone () const
virtual ~ParticleForce ()
const CloudType & owner () const
CloudType & owner ()
const fvMesh & mesh () const
const dictionary & coeffs () const
virtual void cacheFields (const bool store)
virtual forceSuSp calcCoupled (const typename CloudType::parcelType &p, const typename CloudType::parcelType::trackingData &td, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const
virtual forceSuSp calcNonCoupled (const typename CloudType::parcelType &p, const typename CloudType::parcelType::trackingData &td, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const
virtual scalar massAdd (const typename CloudType::parcelType &p, const typename CloudType::parcelType::trackingData &td, const scalar mass) const
Static Public Member Functions
static autoPtr< ParticleForce< CloudType > > New (CloudType &owner, const fvMesh &mesh, const dictionary &dict, const word &forceType)
Detailed Description
template<class CloudType>
class Foam::ParticleForce< CloudType >
Abstract base class for particle forces.
Source files
ParticleForce.H
ParticleForceI.H
ParticleForce.C
ParticleForceNew.C
Definition at line 55 of file ParticleForce.H.
Member Typedef Documentation
returnType
template<class CloudType > typedef VectorSpace<Vector<vector>, vector, 2> returnType
Definition at line 90 of file ParticleForce.H.
Constructor & Destructor Documentation
ParticleForce() [1/2]
template<class CloudType > ParticleForce (CloudType & owner, const fvMesh & mesh, const dictionary & dict, const word & forceType, const bool readCoeffs)
Definition at line 26 of file ParticleForce.C.
References dict, Foam::exit(), Foam::FatalIOError, and FatalIOErrorInFunction.
ParticleForce() [2/2]
template<class CloudType > ParticleForce (const ParticleForce< CloudType > & pf)
Definition at line 49 of file ParticleForce.C.
~ParticleForce()
template<class CloudType > ~ParticleForce () virtual
Definition at line 60 of file ParticleForce.C.
Member Function Documentation
TypeName()
template<class CloudType > TypeName ("particleForce")
declareRunTimeSelectionTable()
template<class CloudType > declareRunTimeSelectionTable (autoPtr , ParticleForce< CloudType > , dictionary , (CloudType &owner, const fvMesh &mesh, const dictionary &dict) , (owner, mesh, dict))
clone()
template<class CloudType > virtual autoPtr< ParticleForce< CloudType > > clone () const inline virtual
Reimplemented in CoulombForce< CloudType >, DistortedSphereDragForce< CloudType >, ErgunWenYuDragForce< CloudType >, NonSphereDragForce< CloudType >, PlessisMasliyahDragForce< CloudType >, SphereDragForce< CloudType >, WenYuDragForce< CloudType >, GravityForce< CloudType >, InterfaceForce< CloudType >, LiftForce< CloudType >, SaffmanMeiLiftForce< CloudType >, TomiyamaLiftForce< CloudType >, NonInertialFrameForce< CloudType >, ParamagneticForce< CloudType >, PressureGradientForce< CloudType >, SRFForce< CloudType >, VirtualMassForce< CloudType >, and BrownianMotionForce< CloudType >.
Definition at line 109 of file ParticleForce.H.
New()
template<class CloudType > Foam::autoPtr< Foam::ParticleForce< CloudType > > New (CloudType & owner, const fvMesh & mesh, const dictionary & dict, const word & forceType) static
Definition at line 28 of file ParticleForceNew.C.
References Foam::abort(), dict, Foam::endl(), Foam::FatalIOError, FatalIOErrorInLookup, Foam::Info, mesh, and PtrList< T >::PtrList().
owner() [1/2]
template<class CloudType > const CloudType & owner () const inline
Definition at line 24 of file ParticleForceI.H.
owner() [2/2]
template<class CloudType > CloudType & owner () inline
Definition at line 31 of file ParticleForceI.H.
mesh()
template<class CloudType > const Foam::fvMesh & mesh () const inline
Definition at line 38 of file ParticleForceI.H.
coeffs()
template<class CloudType > const Foam::dictionary & coeffs () const inline
Definition at line 45 of file ParticleForceI.H.
cacheFields()
template<class CloudType > void cacheFields (const bool store) virtual
Reimplemented in CoulombForce< CloudType >, InterfaceForce< CloudType >, LiftForce< CloudType >, NonInertialFrameForce< CloudType >, ParamagneticForce< CloudType >, PressureGradientForce< CloudType >, SRFForce< CloudType >, VirtualMassForce< CloudType >, and BrownianMotionForce< CloudType >.
Definition at line 67 of file ParticleForce.C.
calcCoupled()
template<class CloudType > Foam::forceSuSp calcCoupled (const typename CloudType::parcelType & p, const typename CloudType::parcelType::trackingData & td, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const virtual
Reimplemented in DistortedSphereDragForce< CloudType >, ErgunWenYuDragForce< CloudType >, NonSphereDragForce< CloudType >, PlessisMasliyahDragForce< CloudType >, SphereDragForce< CloudType >, WenYuDragForce< CloudType >, LiftForce< CloudType >, PressureGradientForce< CloudType >, VirtualMassForce< CloudType >, and BrownianMotionForce< CloudType >.
Definition at line 72 of file ParticleForce.C.
References forceSuSp::Sp(), forceSuSp::Su(), and Foam::Zero.
calcNonCoupled()
template<class CloudType > Foam::forceSuSp calcNonCoupled (const typename CloudType::parcelType & p, const typename CloudType::parcelType::trackingData & td, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const virtual
Reimplemented in CoulombForce< CloudType >, GravityForce< CloudType >, InterfaceForce< CloudType >, NonInertialFrameForce< CloudType >, ParamagneticForce< CloudType >, and SRFForce< CloudType >.
Definition at line 91 of file ParticleForce.C.
massAdd()
template<class CloudType > Foam::scalar massAdd (const typename CloudType::parcelType & p, const typename CloudType::parcelType::trackingData & td, const scalar mass) const virtual
Reimplemented in PressureGradientForce< CloudType >, and VirtualMassForce< CloudType >.
Definition at line 110 of file ParticleForce.C.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/Kinematic/ParticleForces/ParticleForce/ParticleForce.H
src/lagrangian/intermediate/submodels/Kinematic/ParticleForces/ParticleForce/ParticleForce.C
src/lagrangian/intermediate/submodels/Kinematic/ParticleForces/ParticleForce/ParticleForceI.H
src/lagrangian/intermediate/submodels/Kinematic/ParticleForces/ParticleForce/ParticleForceNew.C