OpenFOAM: binaryTree< CompType, ThermoType > Class Template Reference
binaryTree< CompType, ThermoType > Class Template Reference
Data storage of the chemistryOnLineLibrary according to a binary tree structure.
#include <binaryTree.H>
Public Types
typedef binaryNode< CompType, ThermoType > node
typedef chemPointISAT< CompType, ThermoType > chemPoint
Public Member Functions
binaryTree (TDACChemistryModel< CompType, ThermoType > &chemistry, dictionary coeffsDict)
label size ()
label depth (node *subTreeRoot)
label depth ()
node * root ()
label maxNLeafs ()
void insertNewLeaf (const scalarField &phiq, const scalarField &Rphiq, const scalarSquareMatrix &A, const scalarField &scaleFactor, const scalar &epsTol, const label nCols, chemPoint *&phi0)
void binaryTreeSearch (const scalarField &phiq, node *node, chemPoint *&nearest)
bool secondaryBTSearch (const scalarField &phiq, chemPoint *&x)
void deleteLeaf (chemPoint *&phi0)
void balance ()
void deleteAllNode ()
chemPoint * treeMin (node *subTreeRoot)
chemPoint * treeMin ()
chemPoint * treeSuccessor (chemPoint *x)
void clear ()
bool isFull ()
void resetNumRetrieve ()
Detailed Description
template<class CompType, class ThermoType>
class Foam::binaryTree< CompType, ThermoType >
Data storage of the chemistryOnLineLibrary according to a binary tree structure.
0 (root node) / \ 0 0 / \ / \ L R L 0 / \ L R
L: leafLeft_ R: leafRight_
Definition at line 53 of file binaryTree.H.
Member Typedef Documentation
node
template<class CompType , class ThermoType > typedef binaryNode<CompType, ThermoType> node
Definition at line 58 of file binaryTree.H.
chemPoint
template<class CompType , class ThermoType > typedef chemPointISAT<CompType, ThermoType> chemPoint
Definition at line 59 of file binaryTree.H.
Constructor & Destructor Documentation
binaryTree()
template<class CompType , class ThermoType > binaryTree (TDACChemistryModel< CompType, ThermoType > & chemistry, dictionary coeffsDict)
Definition at line 336 of file binaryTree.C.
Member Function Documentation
size()
template<class CompType , class ThermoType > label size () inline
Definition at line 134 of file binaryTree.H.
depth() [1/2]
template<class CompType , class ThermoType > Foam::label depth (node * subTreeRoot)
Definition at line 354 of file binaryTree.C.
References Foam::max().
depth() [2/2]
template<class CompType , class ThermoType > label depth () inline
Definition at line 142 of file binaryTree.H.
References binaryTree< CompType, ThermoType >::depth().
Referenced by binaryTree< CompType, ThermoType >::depth().
root()
template<class CompType , class ThermoType > node * root () inline
Definition at line 147 of file binaryTree.H.
maxNLeafs()
template<class CompType , class ThermoType > label maxNLeafs () inline
Definition at line 152 of file binaryTree.H.
insertNewLeaf()
template<class CompType , class ThermoType > void insertNewLeaf (const scalarField & phiq, const scalarField & Rphiq, const scalarSquareMatrix & A, const scalarField & scaleFactor, const scalar & epsTol, const label nCols, chemPoint *& phi0)
Definition at line 375 of file binaryTree.C.
References A, and Foam::deleteDemandDrivenData().
binaryTreeSearch()
template<class CompType , class ThermoType > void binaryTreeSearch (const scalarField & phiq, node * node, chemPoint *& nearest)
Definition at line 459 of file binaryTree.C.
References binaryNode< CompType, ThermoType >::a(), binaryNode< CompType, ThermoType >::leafLeft(), binaryNode< CompType, ThermoType >::leafRight(), binaryNode< CompType, ThermoType >::nodeLeft(), binaryNode< CompType, ThermoType >::nodeRight(), UPtrList< T >::size(), and binaryNode< CompType, ThermoType >::v().
secondaryBTSearch()
template<class CompType , class ThermoType > bool secondaryBTSearch (const scalarField & phiq, chemPoint *& x)
Definition at line 516 of file binaryTree.C.
References x, and y.
deleteLeaf()
template<class CompType , class ThermoType > void deleteLeaf (chemPoint *& phi0)
Definition at line 574 of file binaryTree.C.
References Foam::deleteDemandDrivenData(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, binaryNode< CompType, ThermoType >::parent(), and x.
balance()
template<class CompType , class ThermoType > void balance ()
Definition at line 638 of file binaryTree.C.
References forAll, n, UPtrList< T >::size(), Foam::sqr(), x, and Foam::Zero.
deleteAllNode()
template<class CompType , class ThermoType > void deleteAllNode () inline
Definition at line 215 of file binaryTree.H.
References binaryTree< CompType, ThermoType >::deleteAllNode().
Referenced by binaryTree< CompType, ThermoType >::deleteAllNode().
treeMin() [1/2]
template<class CompType , class ThermoType > Foam::chemPointISAT< CompType, ThermoType > * treeMin (node * subTreeRoot)
Definition at line 730 of file binaryTree.C.
treeMin() [2/2]
template<class CompType , class ThermoType > chemPoint * treeMin () inline
Definition at line 222 of file binaryTree.H.
References binaryTree< CompType, ThermoType >::treeMin().
Referenced by binaryTree< CompType, ThermoType >::treeMin().
treeSuccessor()
template<class CompType , class ThermoType > Foam::chemPointISAT< CompType, ThermoType > * treeSuccessor (chemPoint * x)
Definition at line 747 of file binaryTree.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, chemPointISAT< CompType, ThermoType >::node(), x, and y.
clear()
template<class CompType , class ThermoType > void clear ()
Definition at line 797 of file binaryTree.C.
isFull()
template<class CompType , class ThermoType > bool isFull ()
Definition at line 811 of file binaryTree.C.
resetNumRetrieve()
template<class CompType , class ThermoType > void resetNumRetrieve ()
Definition at line 818 of file binaryTree.C.
The documentation for this class was generated from the following files:
src/thermophysicalModels/chemistryModel/chemistryModel/TDACChemistryModel/tabulation/ISAT/binaryTree/binaryTree.H
src/thermophysicalModels/chemistryModel/chemistryModel/TDACChemistryModel/tabulation/ISAT/binaryTree/binaryTree.C