OpenFOAM: drippingInjection Class Reference
drippingInjection Class Reference
Film dripping mass transfer model.
#include <drippingInjection.H>
Public Member Functions
TypeName ("drippingInjection")
drippingInjection (surfaceFilmRegionModel &film, const dictionary &dict)
virtual ~drippingInjection ()
virtual void correct (scalarField &availableMass, scalarField &massToInject, scalarField &diameterToInject)
Public Member Functions inherited from injectionModel
TypeName ("injectionModel")
declareRunTimeSelectionTable (autoPtr, injectionModel, dictionary,(surfaceFilmRegionModel &film, const dictionary &dict),(film, dict))
injectionModel (surfaceFilmRegionModel &film)
injectionModel (const word &modelType, surfaceFilmRegionModel &film, const dictionary &dict)
virtual ~injectionModel ()
virtual scalar injectedMassTotal () const
virtual void patchInjectedMassTotals (scalarField &patchMasses) const
Public Member Functions inherited from filmSubModelBase
filmSubModelBase (surfaceFilmRegionModel &film)
filmSubModelBase (surfaceFilmRegionModel &film, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
filmSubModelBase (const word &modelName, surfaceFilmRegionModel &film, const dictionary &dict, const word &baseName, const word &modelType)
virtual ~filmSubModelBase ()
virtual bool writeTime () const
const surfaceFilmRegionModel & film () const
surfaceFilmRegionModel & film ()
template<class FilmType >
const FilmType & filmType () const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
subModelBase (const subModelBase &smb)
virtual ~subModelBase ()=default
const word & modelName () const
const dictionary & dict () const
const word & baseName () const
const word & modelType () const
const dictionary & coeffDict () const
const dictionary & properties () const
virtual bool defaultCoeffs (const bool printMsg) const
virtual bool active () const
virtual void cacheFields (const bool store)
virtual fileName localPath () const
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
bool getModelDict (const word &entryName, dictionary &dict) const
template<class Type >
bool getModelProperty (const word &entryName, Type &value) const
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
virtual void write (Ostream &os) const
Protected Attributes
scalar deltaStable_
scalar particlesPerParcel_
Random rndGen_
const autoPtr< distributionModel > parcelDistribution_
scalarList diameter_
Protected Attributes inherited from filmSubModelBase
surfaceFilmRegionModel & filmModel_
Protected Attributes inherited from subModelBase
const word modelName_
dictionary & properties_
const dictionary dict_
const word baseName_
const word modelType_
const dictionary coeffDict_
Additional Inherited Members
Static Public Member Functions inherited from injectionModel
static autoPtr< injectionModel > New (surfaceFilmRegionModel &film, const dictionary &dict, const word &mdoelType)
Public Attributes inherited from subModelBase
bool log
Protected Member Functions inherited from injectionModel
void addToInjectedMass (const scalar dMass)
void correct ()
Protected Member Functions inherited from subModelBase
bool inLine () const
Detailed Description
Film dripping mass transfer model.
If the film mass exceeds that needed to generate a valid parcel, the equivalent mass is removed from the film.
New parcel diameters are sampled from a PDF.
Source files
drippingInjection.H
drippingInjection.C
Definition at line 57 of file drippingInjection.H.
Constructor & Destructor Documentation
drippingInjection()
drippingInjection (surfaceFilmRegionModel & film, const dictionary & dict)
Definition at line 46 of file drippingInjection.C.
~drippingInjection()
~drippingInjection () virtual
Definition at line 70 of file drippingInjection.C.
Member Function Documentation
TypeName()
TypeName ("drippingInjection")
correct()
void correct (scalarField & availableMass, scalarField & massToInject, scalarField & diameterToInject) virtual
Implements injectionModel.
Definition at line 76 of file drippingInjection.C.
References injectionModel::addToInjectedMass(), injectionModel::correct(), delta, drippingInjection::deltaStable_, drippingInjection::diameter_, filmSubModelBase::film(), forAll, Foam::max(), Foam::min(), drippingInjection::parcelDistribution_, drippingInjection::particlesPerParcel_, Foam::constant::mathematical::pi(), Foam::pow3(), rho, and Foam::Zero.
Member Data Documentation
deltaStable_
scalar deltaStable_ protected
Definition at line 78 of file drippingInjection.H.
Referenced by drippingInjection::correct().
particlesPerParcel_
scalar particlesPerParcel_ protected
Definition at line 81 of file drippingInjection.H.
Referenced by drippingInjection::correct().
rndGen_
Random rndGen_ protected
Definition at line 84 of file drippingInjection.H.
parcelDistribution_
const autoPtr<distributionModel> parcelDistribution_ protected
Definition at line 88 of file drippingInjection.H.
Referenced by drippingInjection::correct().
diameter_
scalarList diameter_ protected
Definition at line 91 of file drippingInjection.H.
Referenced by drippingInjection::correct().
The documentation for this class was generated from the following files:
src/regionModels/surfaceFilmModels/submodels/kinematic/injectionModel/drippingInjection/drippingInjection.H
src/regionModels/surfaceFilmModels/submodels/kinematic/injectionModel/drippingInjection/drippingInjection.C