OpenFOAM: extendedCentredCellToCellStencil Class Reference
extendedCentredCellToCellStencil Class Reference
#include <extendedCentredCellToCellStencil.H>
Public Member Functions
extendedCentredCellToCellStencil (const cellToCellStencil &)
const mapDistribute & map () const
const labelListList & stencil () const
void compact ()
template<class Type >
void collectData (const GeometricField< Type, fvPatchField, volMesh > &fld, List< List< Type > > &stencilFld) const
template<class Type , class WeightType >
tmp< GeometricField< typename outerProduct< WeightType, Type >::type, fvPatchField, volMesh > > weightedSum (const GeometricField< Type, fvPatchField, volMesh > &fld, const List< List< WeightType > > &stencilWeights) const
Public Member Functions inherited from extendedCellToCellStencil
extendedCellToCellStencil (const polyMesh &)
template<class Type , class WeightType >
Foam::tmp< Foam::GeometricField< typename Foam::outerProduct< WeightType, Type >::type, Foam::fvPatchField, Foam::volMesh > > weightedSum (const mapDistribute &map, const labelListList &stencil, const GeometricField< Type, fvPatchField, volMesh > &fld, const List< List< WeightType > > &stencilWeights)
Additional Inherited Members
Static Public Member Functions inherited from extendedCellToCellStencil
template<class Type , class WeightType >
static tmp< GeometricField< typename outerProduct< WeightType, Type >::type, fvPatchField, volMesh > > weightedSum (const mapDistribute &map, const labelListList &stencil, const GeometricField< Type, fvPatchField, volMesh > &fld, const List< List< WeightType > > &stencilWeights)
Protected Attributes inherited from extendedCellToCellStencil
const polyMesh & mesh_
Detailed Description
Source files
extendedCentredCellToCellStencil.H
extendedCentredCellToCellStencil.C
Definition at line 48 of file extendedCentredCellToCellStencil.H.
Constructor & Destructor Documentation
extendedCentredCellToCellStencil()
extendedCentredCellToCellStencil (const cellToCellStencil & stencil) explicit
Definition at line 27 of file extendedCentredCellToCellStencil.C.
References UPstream::nProcs(), and extendedCentredCellToCellStencil::stencil().
Member Function Documentation
map()
const mapDistribute & map () const inline
Definition at line 84 of file extendedCentredCellToCellStencil.H.
Referenced by LeastSquaresGrad< Type, Stencil >::calcGrad(), extendedCentredCellToCellStencil::collectData(), and extendedCentredCellToCellStencil::weightedSum().
stencil()
const labelListList & stencil () const inline
Definition at line 90 of file extendedCentredCellToCellStencil.H.
Referenced by LeastSquaresGrad< Type, Stencil >::calcGrad(), extendedCentredCellToCellStencil::collectData(), extendedCentredCellToCellStencil::extendedCentredCellToCellStencil(), and extendedCentredCellToCellStencil::weightedSum().
compact()
void compact ()
Definition at line 51 of file extendedCentredCellToCellStencil.C.
References forAll, and UPstream::msgType().
collectData()
template<class Type > void collectData (const GeometricField< Type, fvPatchField, volMesh > & fld, List< List< Type > > & stencilFld) const inline
Definition at line 100 of file extendedCentredCellToCellStencil.H.
References extendedCellToFaceStencil::collectData(), fld(), extendedCentredCellToCellStencil::map(), and extendedCentredCellToCellStencil::stencil().
weightedSum()
template<class Type , class WeightType > tmp< GeometricField< typename outerProduct< WeightType, Type >::type, fvPatchField, volMesh > > weightedSum (const GeometricField< Type, fvPatchField, volMesh > & fld, const List< List< WeightType > > & stencilWeights) const inline
Definition at line 125 of file extendedCentredCellToCellStencil.H.
References fld(), extendedCentredCellToCellStencil::map(), extendedCentredCellToCellStencil::stencil(), and extendedCellToCellStencil::weightedSum().
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/extendedStencil/cellToCell/extendedCentredCellToCellStencil.H
src/finiteVolume/fvMesh/extendedStencil/cellToCell/extendedCentredCellToCellStencil.C