OpenFOAM: faFieldDecomposer::processorAreaPatchFieldDecomposer Class Reference
faFieldDecomposer::processorAreaPatchFieldDecomposer Class Reference
#include <faFieldDecomposer.H>
Public Member Functions
processorAreaPatchFieldDecomposer (const label nTotalFaces, const labelUList &edgeOwner, const labelUList &edgeNeigbour, const labelUList &addressingSlice, const scalarField &edgeWeights=scalarField::null())
processorAreaPatchFieldDecomposer (const faMesh &mesh, const labelUList &addressingSlice)
label size () const
virtual label sizeBeforeMapping () const
bool direct () const
virtual bool hasUnmapped () const
const labelListList & addressing () const
const scalarListList & weights () const
Public Member Functions inherited from faPatchFieldMapper
faPatchFieldMapper ()=default
Public Member Functions inherited from FieldMapper
FieldMapper ()=default
virtual ~FieldMapper ()=default
virtual bool distributed () const
virtual const labelUList & directAddressing () const
virtual const mapDistributeBase & distributeMap () const
template<class Type >
tmp< Field< Type > > operator() (const Field< Type > &fld) const
Detailed Description
Definition at line 118 of file faFieldDecomposer.H.
Constructor & Destructor Documentation
processorAreaPatchFieldDecomposer() [1/2]
processorAreaPatchFieldDecomposer (const label nTotalFaces, const labelUList & edgeOwner, const labelUList & edgeNeigbour, const labelUList & addressingSlice, const scalarField & edgeWeights = scalarField::null())
Definition at line 46 of file faFieldDecomposer.C.
References forAll, List< T >::resize(), UPtrList< T >::size(), and faFieldDecomposer::processorAreaPatchFieldDecomposer::weights().
processorAreaPatchFieldDecomposer() [2/2]
processorAreaPatchFieldDecomposer (const faMesh & mesh, const labelUList & addressingSlice)
Definition at line 109 of file faFieldDecomposer.C.
Member Function Documentation
size()
label size () const inline virtual
Implements FieldMapper.
Definition at line 150 of file faFieldDecomposer.H.
References UList< T >::size().
sizeBeforeMapping()
virtual label sizeBeforeMapping () const inline virtual
Definition at line 155 of file faFieldDecomposer.H.
direct()
bool direct () const inline virtual
Implements FieldMapper.
Definition at line 160 of file faFieldDecomposer.H.
hasUnmapped()
virtual bool hasUnmapped () const inline virtual
Implements FieldMapper.
Definition at line 165 of file faFieldDecomposer.H.
addressing()
const labelListList & addressing () const inline virtual
Reimplemented from FieldMapper.
Definition at line 170 of file faFieldDecomposer.H.
weights()
const scalarListList & weights () const inline virtual
Reimplemented from FieldMapper.
Definition at line 175 of file faFieldDecomposer.H.
Referenced by faFieldDecomposer::processorAreaPatchFieldDecomposer::processorAreaPatchFieldDecomposer().
The documentation for this class was generated from the following files:
src/parallel/decompose/faDecompose/faFieldDecomposer.H
src/parallel/decompose/faDecompose/faFieldDecomposer.C