OpenFOAM: base Class Reference
base Class Reference
Base class for glTF entities.
#include <foamGltfBase.H>
Public Member Functions
base ()
base (const word &name)
~base ()=default
label & id () noexcept
const word & name () const noexcept
void write (Ostream &os) const
void operator= (const base &gltf)
Protected Attributes
word name_
label id_
Detailed Description
Base class for glTF entities.
Definition at line 116 of file foamGltfBase.H.
Constructor & Destructor Documentation
base() [1/2]
base () inline
Definition at line 134 of file foamGltfBase.H.
base() [2/2]
base (const word & name) inline explicit
Definition at line 140 of file foamGltfBase.H.
~base()
~base () default
Member Function Documentation
id()
label & id () inline noexcept
Definition at line 154 of file foamGltfBase.H.
References base::id_.
name()
const word & name () const inline noexcept
Definition at line 160 of file foamGltfBase.H.
References base::name_.
write()
void write (Ostream & os) const inline
Definition at line 166 of file foamGltfBase.H.
References Foam::indent(), base::name_, Foam::nl, and os().
Referenced by accessor::write(), bufferView::write(), and mesh::write().
operator=()
void operator= (const base & gltf) inline
Definition at line 175 of file foamGltfBase.H.
References base::id_, and base::name_.
Referenced by bufferView::operator=().
Member Data Documentation
name_
word name_ protected
Definition at line 123 of file foamGltfBase.H.
Referenced by base::name(), base::operator=(), and base::write().
id_
label id_ protected
Definition at line 126 of file foamGltfBase.H.
Referenced by base::id(), and base::operator=().
The documentation for this class was generated from the following file:
src/fileFormats/gltf/foamGltfBase.H