OpenFOAM: searchableSurfaces Class Reference
searchableSurfaces Class Reference
Container for searchableSurfaces. The collection is specified as a dictionary. For example,.
#include <searchableSurfaces.H>
Public Member Functions
ClassName ("searchableSurfaces")
searchableSurfaces (const label)
searchableSurfaces (const IOobject &, const dictionary &, const bool singleRegionName)
const wordList & names () const
wordList & names ()
const List< wordList > & regionNames () const
List< wordList > & regionNames ()
label findSurfaceID (const word &name) const
label findSurfaceRegionID (const word &surfaceName, const word &regionName) const
void findAnyIntersection (const pointField &start, const pointField &end, labelList &surfaces, List< pointIndexHit > &) const
void findAllIntersections (const pointField &start, const pointField &end, labelListList &surfaces, List< List< pointIndexHit > > &) const
void findNearestIntersection (const pointField &start, const pointField &end, labelList &surface1, List< pointIndexHit > &hit1, labelList &surface2, List< pointIndexHit > &hit2) const
void findNearest (const pointField &, const scalarField &nearestDistSqr, labelList &surfaces, List< pointIndexHit > &) const
void findNearest (const labelListList &regionIndices, const pointField &samples, const scalarField &nearestDistSqr, labelList &nearestSurfaces, List< pointIndexHit > &nearestInfo) const
boundBox bounds () const
bool checkClosed (const bool report) const
bool checkNormalOrientation (const bool report) const
bool checkSizes (const scalar maxRatio, const bool report) const
bool checkIntersection (const scalar tol, autoPtr< coordSetWriter > &setWriter, const bool report) const
bool checkQuality (const scalar minQuality, const bool report) const
label checkTopology (const bool report) const
label checkGeometry (const scalar maxRatio, const scalar tolerance, autoPtr< coordSetWriter > &setWriter, const scalar minQuality, const bool report) const
void writeStats (const List< wordList > &, Ostream &) const
const searchableSurface & operator[] (const word &) const
searchableSurface & operator[] (const word &)
Public Member Functions inherited from PtrList< searchableSurface >
constexpr PtrList () noexcept
PtrList (const label len)
PtrList (const PtrList< searchableSurface > &list)
PtrList (PtrList< searchableSurface > &&list)
PtrList (UList< searchableSurface * > &list)
PtrList (const PtrList< searchableSurface > &list, const CloneArg &cloneArgs)
PtrList (PtrList< searchableSurface > &list, bool reuse)
PtrList (const SLPtrList< searchableSurface > &list)
PtrList (Istream &is, const INew &inew)
PtrList (Istream &is)
~PtrList ()
PtrList< searchableSurface > clone (Args &&... args) const
Foam::PtrList< searchableSurface > clone (Args &&... args) const
const searchableSurface * set (const label i) const
autoPtr< searchableSurface > set (const label i, searchableSurface *ptr)
autoPtr< searchableSurface > set (const label i, std::unique_ptr< searchableSurface > &&ptr)
autoPtr< searchableSurface > set (const label i, autoPtr< searchableSurface > &&ptr)
autoPtr< searchableSurface > set (const label i, const refPtr< searchableSurface > &ptr)
autoPtr< searchableSurface > set (const label i, const tmp< searchableSurface > &ptr)
autoPtr< searchableSurface > set (const label i, autoPtr< searchableSurface > &ptr)
void clear ()
void free ()
void resize (const label newLen)
searchableSurface & emplace_back (Args &&... args)
void push_back (searchableSurface *ptr)
void push_back (std::unique_ptr< searchableSurface > &&ptr)
void push_back (autoPtr< searchableSurface > &&ptr)
void push_back (const refPtr< searchableSurface > &ptr)
void push_back (const tmp< searchableSurface > &ptr)
void push_back (PtrList< searchableSurface > &&other)
void push_back (autoPtr< searchableSurface > &ptr)=delete
searchableSurface & emplace_set (const label i, Args &&... args)
searchableSurface & emplace (const label i, Args &&... args)
autoPtr< searchableSurface > release (const label i)
void transfer (PtrList< searchableSurface > &list)
void operator= (const PtrList< searchableSurface > &list)
void operator= (PtrList< searchableSurface > &&list)
void setSize (const label newLen)
void append (autoPtr< searchableSurface > &ptr)
void append (searchableSurface *ptr)
void append (std::unique_ptr< searchableSurface > &&ptr)
void append (autoPtr< searchableSurface > &&ptr)
void append (const refPtr< searchableSurface > &ptr)
void append (const tmp< searchableSurface > &ptr)
void append (PtrList< searchableSurface > &&other)
Public Member Functions inherited from UPtrList< T >
constexpr UPtrList () noexcept
UPtrList (const label len)
UPtrList (const UPtrList< T > &list)
UPtrList (UPtrList< T > &&list)
UPtrList (UPtrList< T > &list, bool reuse)
UPtrList (PtrList< T > &list)
UPtrList (const UList< T * > &list)
UPtrList (UList< T > &list)
bool empty () const noexcept
label size () const noexcept
label count () const noexcept
T & front ()
const T & front () const
T & back ()
const T & back () const
const T * test (const label i) const
const T * get (const label i) const
T * get (const label i)
const T * set (const label i) const
void clear ()
void free ()
void resize (const label newLen)
label squeezeNull ()
void trimTrailingNull ()
void push_back (T *ptr)
void push_back (UPtrList< T > &&other)
void swap (UPtrList< T > &list)
void transfer (UPtrList< T > &list)
T * set (const label i, T *ptr)
void reorder (const labelUList &oldToNew, const bool check=false)
void sortOrder (const labelUList &order, const bool check=false)
void checkNonNull () const
const T & at (const label i) const
T & at (const label i)
const T & operator[] (const label i) const
T & operator[] (const label i)
FOAM_DEPRECATED_FOR (2022-09, "get(), set() or test() methods") const T *operator()(const label i) const
void operator= (const UPtrList< T > &list)
void operator= (UPtrList< T > &&list)
T ** begin_ptr () noexcept
T ** end_ptr () noexcept
iterator begin ()
iterator end () noexcept
const_iterator cbegin () const
const_iterator cend () const noexcept
const_iterator begin () const
const_iterator end () const noexcept
void setSize (const label n)
T & first ()
const T & first () const
T & last ()
const T & last () const
void append (T *ptr)
void append (UPtrList< T > &&other)
Additional Inherited Members
Public Types inherited from UPtrList< T >
typedef T value_type
typedef T & reference
typedef const T & const_reference
Protected Member Functions inherited from PtrList< searchableSurface >
void readIstream (Istream &is, const INew &inew)
Protected Member Functions inherited from UPtrList< T >
void setAddressableSize (const label n) noexcept
label find_next (label pos) const
UPtrList (Detail::PtrListDetail< T > &&ptrs)
Protected Attributes inherited from UPtrList< T >
Detail::PtrListDetail< T > ptrs_
Detailed Description
Container for searchableSurfaces. The collection is specified as a dictionary. For example,.
geometry
{
    surface1
    {
        type  ...;
    }
    surface2
    {
        type  ...;
    }
}
The Sub-dictionary parameters
Property Description Required Default
name alternative name for surface no dict name
regions Region names sub-dictionary no
Source files
searchableSurfaces.H
searchableSurfaces.C
Definition at line 89 of file searchableSurfaces.H.
Constructor & Destructor Documentation
searchableSurfaces() [1/2]
searchableSurfaces (const label size) explicit
Definition at line 92 of file searchableSurfaces.C.
searchableSurfaces() [2/2]
searchableSurfaces (const IOobject & io, const dictionary & topDict, const bool singleRegionName)
Definition at line 190 of file searchableSurfaces.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, UPtrList< T >::get(), io(), searchableSurface::New(), Foam::nl, searchableSurfaces::operator[](), PtrList< searchableSurface >::PtrList(), s(), PtrList< searchableSurface >::set(), List< T >::setSize(), PtrList< T >::setSize(), UPtrList< T >::size(), and dictionary::subDict().
Member Function Documentation
ClassName()
ClassName ("searchableSurfaces")
names() [1/2]
const wordList & names () const inline
Definition at line 153 of file searchableSurfaces.H.
names() [2/2]
wordList & names () inline
Definition at line 159 of file searchableSurfaces.H.
regionNames() [1/2]
const List< wordList > & regionNames () const inline
Definition at line 165 of file searchableSurfaces.H.
regionNames() [2/2]
List< wordList > & regionNames () inline
Definition at line 171 of file searchableSurfaces.H.
findSurfaceID()
Foam::label findSurfaceID (const word & name) const
Definition at line 302 of file searchableSurfaces.C.
findSurfaceRegionID()
Foam::label findSurfaceRegionID (const word & surfaceName, const word & regionName) const
Definition at line 311 of file searchableSurfaces.C.
References regionName.
findAnyIntersection()
void findAnyIntersection (const pointField & start, const pointField & end, labelList & surfaces, List< pointIndexHit > & hitInfo) const
Definition at line 324 of file searchableSurfaces.C.
References searchableSurfacesQueries::findAnyIntersection().
findAllIntersections()
void findAllIntersections (const pointField & start, const pointField & end, labelListList & surfaces, List< List< pointIndexHit > > & hitInfo) const
Definition at line 344 of file searchableSurfaces.C.
References searchableSurfacesQueries::findAllIntersections().
findNearestIntersection()
void findNearestIntersection (const pointField & start, const pointField & end, labelList & surface1, List< pointIndexHit > & hit1, labelList & surface2, List< pointIndexHit > & hit2) const
Definition at line 365 of file searchableSurfaces.C.
References searchableSurfacesQueries::findNearestIntersection().
findNearest() [1/2]
void findNearest (const pointField & samples, const scalarField & nearestDistSqr, labelList & surfaces, List< pointIndexHit > & nearestInfo) const
Definition at line 389 of file searchableSurfaces.C.
References searchableSurfacesQueries::findNearest(), and samples().
findNearest() [2/2]
void findNearest (const labelListList & regionIndices, const pointField & samples, const scalarField & nearestDistSqr, labelList & nearestSurfaces, List< pointIndexHit > & nearestInfo) const
Definition at line 409 of file searchableSurfaces.C.
References searchableSurfacesQueries::findNearest(), and samples().
bounds()
Foam::boundBox bounds () const
Definition at line 433 of file searchableSurfaces.C.
References searchableSurfacesQueries::bounds().
checkClosed()
bool checkClosed (const bool report) const
Definition at line 443 of file searchableSurfaces.C.
References Foam::endl(), forAll, Foam::Info, Foam::nl, Foam::returnReduceOr(), and s().
checkNormalOrientation()
bool checkNormalOrientation (const bool report) const
Definition at line 510 of file searchableSurfaces.C.
References PatchTools::checkOrientation(), Foam::endl(), forAll, Foam::Info, PatchTools::markZones(), Foam::returnReduceOr(), s(), and UPtrList< T >::size().
checkSizes()
bool checkSizes (const scalar maxRatio, const bool report) const
Definition at line 556 of file searchableSurfaces.C.
References Foam::endl(), forAll, Foam::Info, boundBox::mag(), Foam::nl, and Foam::returnReduceOr().
checkIntersection()
bool checkIntersection (const scalar tol, autoPtr< coordSetWriter > & setWriter, const bool report) const
Definition at line 604 of file searchableSurfaces.C.
References PtrList< T >::append(), fileWriter::close(), e, Foam::endl(), forAll, Foam::Info, Foam::mag(), coordSet::name(), fileWriter::open(), Foam::returnReduceOr(), UPtrList< T >::size(), polyWriter::write(), and writer().
checkQuality()
bool checkQuality (const scalar minQuality, const bool report) const
Definition at line 744 of file searchableSurfaces.C.
References Foam::endl(), f(), forAll, Foam::Info, Foam::returnReduceOr(), and s().
checkTopology()
Foam::label checkTopology (const bool report) const
Definition at line 809 of file searchableSurfaces.C.
checkGeometry()
Foam::label checkGeometry (const scalar maxRatio, const scalar tolerance, autoPtr< coordSetWriter > & setWriter, const scalar minQuality, const bool report) const
Definition at line 829 of file searchableSurfaces.C.
writeStats()
void writeStats (const List< wordList > & patchTypes, Ostream & os) const
Definition at line 859 of file searchableSurfaces.C.
References Foam::endl(), forAll, Foam::Info, Foam::nl, patchTypes(), s(), and UList< T >::size().
operator[]() [1/2]
const Foam::searchableSurface & operator[] (const word & surfName) const
Definition at line 904 of file searchableSurfaces.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, and Foam::nl.
Referenced by searchableSurfaces::searchableSurfaces().
operator[]() [2/2]
Foam::searchableSurface & operator[] (const word & surfName)
Definition at line 923 of file searchableSurfaces.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, and Foam::nl.
The documentation for this class was generated from the following files:
src/meshTools/searchableSurfaces/searchableSurfaces/searchableSurfaces.H
src/meshTools/searchableSurfaces/searchableSurfaces/searchableSurfaces.C