OpenFOAM: viscosityModel Class Reference
viscosityModel Class Reference abstract
An abstract base class for incompressible viscosityModels.
#include <viscosityModel.H>
Public Member Functions
TypeName ("viscosityModel")
declareRunTimeSelectionTable (autoPtr, viscosityModel, dictionary,(const word &name, const dictionary &viscosityProperties, const volVectorField &U, const surfaceScalarField &phi),(name, viscosityProperties, U, phi))
viscosityModel (const word &name, const dictionary &viscosityProperties, const volVectorField &U, const surfaceScalarField &phi)
virtual ~viscosityModel ()=default
const dictionary & viscosityProperties () const
tmp< volScalarField > strainRate () const
virtual tmp< volScalarField > nu () const =0
virtual tmp< scalarField > nu (const label patchi) const =0
virtual void correct ()=0
virtual bool read (const dictionary &viscosityProperties)=0
Static Public Member Functions
static autoPtr< viscosityModel > New (const word &name, const dictionary &viscosityProperties, const volVectorField &U, const surfaceScalarField &phi)
Protected Member Functions
viscosityModel (const viscosityModel &)=delete
void operator= (const viscosityModel &)=delete
Protected Attributes
word name_
dictionary viscosityProperties_
const volVectorField & U_
const surfaceScalarField & phi_
Detailed Description
An abstract base class for incompressible viscosityModels.
Source files
viscosityModel.H
viscosityModel.C
The strain rate is defined by:
mag(symm(grad(U)))
Source files
viscosityModel.H
viscosityModel.C
viscosityModelNew.C
Definition at line 64 of file viscosityModel.H.
Constructor & Destructor Documentation
viscosityModel() [1/2]
viscosityModel (const viscosityModel &) protected delete
viscosityModel() [2/2]
viscosityModel (const word & name, const dictionary & viscosityProperties, const volVectorField & U, const surfaceScalarField & phi)
Definition at line 36 of file viscosityModel.C.
References Foam::name().
~viscosityModel()
virtual ~viscosityModel () virtual default
Member Function Documentation
operator=()
void operator= (const viscosityModel &) protected delete
TypeName()
TypeName ("viscosityModel")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , viscosityModel , dictionary , (const word &name, const dictionary &viscosityProperties, const volVectorField &U, const surfaceScalarField &phi) , (name, viscosityProperties, U, phi))
New()
Foam::autoPtr< Foam::viscosityModel > New (const word & name, const dictionary & viscosityProperties, const volVectorField & U, const surfaceScalarField & phi) static
Definition at line 28 of file viscosityModelNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, Foam::Info, Foam::name(), phi, and U.
viscosityProperties()
const dictionary & viscosityProperties () const inline
Definition at line 141 of file viscosityModel.H.
References viscosityModel::viscosityProperties_.
strainRate()
Foam::tmp< Foam::volScalarField > strainRate () const
Definition at line 53 of file viscosityModel.C.
References Foam::fvc::grad(), Foam::mag(), Foam::sqrt(), and Foam::symm().
Referenced by BirdCarreau::calcNu(), Casson::calcNu(), CrossPowerLaw::calcNu(), HerschelBulkley::calcNu(), and powerLaw::calcNu().
nu() [1/2]
virtual tmp< volScalarField > nu () const pure virtual
Implemented in BirdCarreau, Casson, CrossPowerLaw, HerschelBulkley, Newtonian, powerLaw, and strainRateFunction.
nu() [2/2]
virtual tmp< scalarField > nu (const label patchi) const pure virtual
Implemented in BirdCarreau, Casson, CrossPowerLaw, HerschelBulkley, Newtonian, powerLaw, and strainRateFunction.
correct()
virtual void correct () pure virtual
Implemented in BirdCarreau, Casson, CrossPowerLaw, HerschelBulkley, Newtonian, powerLaw, and strainRateFunction.
read()
bool read (const dictionary & viscosityProperties) pure virtual
Implemented in BirdCarreau, Casson, CrossPowerLaw, HerschelBulkley, Newtonian, powerLaw, and strainRateFunction.
Definition at line 59 of file viscosityModel.C.
Referenced by Arrhenius< ViscousModel >::read(), BirdCarreau::read(), Casson::read(), CrossPowerLaw::read(), HerschelBulkley::read(), Newtonian::read(), powerLaw::read(), and strainRateFunction::read().
Member Data Documentation
name_
word name_ protected
Definition at line 71 of file viscosityModel.H.
viscosityProperties_
dictionary viscosityProperties_ protected
Definition at line 72 of file viscosityModel.H.
Referenced by viscosityModel::viscosityProperties().
U_
const volVectorField& U_ protected
Definition at line 74 of file viscosityModel.H.
phi_
const surfaceScalarField& phi_ protected
Definition at line 75 of file viscosityModel.H.
The documentation for this class was generated from the following files:
src/transportModels/incompressible/viscosityModels/viscosityModel/viscosityModel.H
src/transportModels/incompressible/viscosityModels/viscosityModel/viscosityModel.C
src/transportModels/incompressible/viscosityModels/viscosityModel/viscosityModelNew.C