OpenFOAM: oversetFvMeshBase Class Reference
oversetFvMeshBase Class Reference
Support for overset functionality.
#include <oversetFvMeshBase.H>
Public Member Functions
TypeName ("oversetFvMeshBase")
oversetFvMeshBase (const fvMesh &mesh, const bool doInit=true)
virtual ~oversetFvMeshBase ()
const fvMeshPrimitiveLduAddressing & primitiveLduAddr () const
virtual const lduAddressing & lduAddr () const
virtual lduInterfacePtrsList interfaces () const
const labelList & reverseFaceMap () const
bool active () const
void active (const bool f) const
template<class Type >
void addInterpolation (fvMatrix< Type > &m, const scalarField &normalisation, const bool setHoleCellValue, const Type &holeCellValue) const
virtual bool update ()
virtual bool interpolateFields ()
virtual bool writeObject (IOstreamOption streamOpt, const bool writeOnProc) const
template<class Type >
tmp< scalarField > normalisation (const fvMatrix< Type > &m) const
template<class Type >
Foam::tmp< Foam::scalarField > normalisation (const fvMatrix< Type > &m) const
template<class Type >
Foam::SolverPerformance< Type > solveOverset (fvMatrix< Type > &m, const dictionary &dict) const
Static Public Member Functions
template<class GeoField >
static void checkCoupledBC (const GeoField &fld)
template<class GeoField , class PatchType >
static void correctBoundaryConditions (typename GeoField::Boundary &bfld, const bool typeOnly)
Protected Member Functions
virtual bool updateAddressing () const
template<class Type >
void write (Ostream &, const fvMatrix< Type > &, const lduAddressing &, const lduInterfacePtrsList &) const
template<class Type >
void scaleConnection (Field< Type > &coeffs, const labelUList &types, const scalarList &factor, const bool setHoleCellValue, const label celli, const label facei) const
template<class Type >
SolverPerformance< Type > solveOverset (fvMatrix< Type > &m, const dictionary &) const
scalar cellAverage (const labelList &types, const labelList &nbrTypes, const scalarField &norm, const scalarField &nbrNorm, const label celli, bitSet &isFront) const
void writeAgglomeration (const GAMGAgglomeration &agglom) const
Static Protected Member Functions
template<class GeoField >
static void correctCoupledBoundaryConditions (GeoField &fld)
Protected Attributes
const fvMesh & mesh_
bool active_
autoPtr< fvMeshPrimitiveLduAddressing > lduPtr_
PtrList< const lduPrimitiveProcessorInterface > remoteStencilInterfaces_
lduInterfacePtrsList allInterfaces_
labelListList stencilFaces_
labelListList stencilPatches_
labelList reverseFaceMap_
Detailed Description
Support for overset functionality.
Source files
oversetFvMeshBase.H
oversetFvMeshBase.C
Definition at line 52 of file oversetFvMeshBase.H.
Constructor & Destructor Documentation
oversetFvMeshBase()
oversetFvMeshBase (const fvMesh & mesh, const bool doInit = true)
Definition at line 512 of file oversetFvMeshBase.C.
References oversetFvMeshBase::mesh_, and MeshObject< Mesh, MeshObjectType, Type >::New().
~oversetFvMeshBase()
~oversetFvMeshBase () virtual
Definition at line 524 of file oversetFvMeshBase.C.
Member Function Documentation
updateAddressing()
bool updateAddressing () const protected virtual
Definition at line 39 of file oversetFvMeshBase.C.
References fvMeshPrimitiveLduAddressing::addAddressing(), oversetFvMeshBase::allInterfaces_, PtrList< T >::append(), boundary, Foam::endl(), forAll, interface(), oversetFvMeshBase::lduPtr_, oversetFvMeshBase::mesh_, UPstream::msgType(), UPstream::myProcNo(), MeshObject< Mesh, MeshObjectType, Type >::New(), UPstream::nProcs(), overlap, patches, Foam::Pout, pp(), oversetFvMeshBase::remoteStencilInterfaces_, oversetFvMeshBase::reverseFaceMap_, PtrList< T >::set(), UPtrList< T >::set(), List< T >::setSize(), UPtrList< T >::setSize(), PtrList< T >::setSize(), UPtrList< T >::size(), UList< T >::size(), oversetFvMeshBase::stencilFaces_, oversetFvMeshBase::stencilPatches_, globalIndex::toGlobal(), globalIndex::toLocal(), and globalIndex::whichProcID().
write()
template<class Type > void write (Ostream & os, const fvMatrix< Type > & m, const lduAddressing & addr, const lduInterfacePtrsList & interfaces) const protected
Definition at line 856 of file oversetFvMeshBaseTemplates.C.
References PtrList< T >::append(), Foam::diag(), Foam::endl(), forAll, os(), PtrList< T >::set(), UPtrList< T >::set(), and UPtrList< T >::size().
scaleConnection()
template<class Type > void scaleConnection (Field< Type > & coeffs, const labelUList & types, const scalarList & factor, const bool setHoleCellValue, const label celli, const label facei) const protected
Definition at line 32 of file oversetFvMeshBaseTemplates.C.
References f(), cellCellStencil::HOLE, cellCellStencil::INTERPOLATED, and cellCellStencil::SPECIAL.
solveOverset() [1/2]
template<class Type > SolverPerformance< Type > solveOverset (fvMatrix< Type > & m, const dictionary &) const protected
correctCoupledBoundaryConditions()
template<class GeoField > void correctCoupledBoundaryConditions (GeoField & fld) static protected
Definition at line 983 of file oversetFvMeshBaseTemplates.C.
References coupled(), UPstream::defaultCommsType, fld(), forAll, UPstream::nonBlocking, UPstream::nRequests(), and UPstream::waitRequests().
cellAverage()
Foam::scalar cellAverage (const labelList & types, const labelList & nbrTypes, const scalarField & norm, const scalarField & nbrNorm, const label celli, bitSet & isFront) const protected
Definition at line 353 of file oversetFvMeshBase.C.
References PtrList< T >::set().
writeAgglomeration()
void writeAgglomeration (const GAMGAgglomeration & agglom) const protected
Definition at line 411 of file oversetFvMeshBase.C.
References correctBoundaryConditions(), Foam::dimless, Foam::endl(), fld(), forAll, Foam::identity(), Foam::Info, Foam::invertOneToMany(), Foam::max(), Foam::name(), IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, Foam::returnReduce(), UPtrList< T >::size(), and Foam::Zero.
TypeName()
TypeName ("oversetFvMeshBase")
primitiveLduAddr()
const Foam::fvMeshPrimitiveLduAddressing & primitiveLduAddr () const
Definition at line 562 of file oversetFvMeshBase.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Referenced by oversetFvMeshBase::active().
lduAddr()
const Foam::lduAddressing & lduAddr () const virtual
Reimplemented in dynamicOversetFvMesh, and staticOversetFvMesh.
Definition at line 530 of file oversetFvMeshBase.C.
Referenced by dynamicOversetFvMesh::lduAddr(), and staticOversetFvMesh::lduAddr().
interfaces()
Foam::lduInterfacePtrsList interfaces () const virtual
Reimplemented in dynamicOversetFvMesh, and staticOversetFvMesh.
Definition at line 546 of file oversetFvMeshBase.C.
Referenced by dynamicOversetFvMesh::interfaces(), and staticOversetFvMesh::interfaces().
reverseFaceMap()
const labelList & reverseFaceMap () const inline
Definition at line 189 of file oversetFvMeshBase.H.
References oversetFvMeshBase::reverseFaceMap_.
active() [1/2]
bool active () const inline
Definition at line 195 of file oversetFvMeshBase.H.
References oversetFvMeshBase::active_.
active() [2/2]
void active (const bool f) const inline
Definition at line 201 of file oversetFvMeshBase.H.
References oversetFvMeshBase::active_, oversetFvMeshBase::allInterfaces_, DebugInfo, Foam::endl(), f(), oversetFvMeshBase::mesh_, oversetFvMeshBase::primitiveLduAddr(), and UPtrList< T >::size().
addInterpolation()
template<class Type > void addInterpolation (fvMatrix< Type > & m, const scalarField & normalisation, const bool setHoleCellValue, const Type & holeCellValue) const
Definition at line 286 of file oversetFvMeshBaseTemplates.C.
References boundaryFieldRef(), Foam::diag(), Foam::exit(), f(), Foam::FatalError, FatalErrorInFunction, forAll, cellCellStencil::HOLE, Foam::inplaceReorder(), cellCellStencil::INTERPOLATED, MeshObject< Mesh, MeshObjectType, Type >::New(), overlap, s(), PtrList< T >::set(), PtrList< T >::setSize(), UPtrList< T >::size(), UList< T >::size(), cellCellStencil::SPECIAL, and Foam::Zero.
update()
bool update () virtual
Reimplemented in dynamicOversetFvMesh, and staticOversetFvMesh.
Definition at line 574 of file oversetFvMeshBase.C.
Referenced by staticOversetFvMesh::staticOversetFvMesh(), dynamicOversetFvMesh::update(), and staticOversetFvMesh::update().
interpolateFields()
bool interpolateFields () virtual
Definition at line 592 of file oversetFvMeshBase.C.
References MeshObject< Mesh, MeshObjectType, Type >::New(), overlap, and dictionary::toc().
writeObject()
bool writeObject (IOstreamOption streamOpt, const bool writeOnProc) const virtual
Reimplemented in dynamicOversetFvMesh, and staticOversetFvMesh.
Definition at line 619 of file oversetFvMeshBase.C.
References cellTypes, cellCellStencil::correctBoundaryConditions(), Foam::dimless, Foam::endl(), forAll, MeshObject< Mesh, MeshObjectType, Type >::New(), IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, overlap, UPtrList< T >::size(), UList< T >::size(), WarningInFunction, Foam::Zero, and fvPatchFieldBase::zeroGradientType().
Referenced by dynamicOversetFvMesh::writeObject(), and staticOversetFvMesh::writeObject().
checkCoupledBC()
template<class GeoField > void checkCoupledBC (const GeoField & fld) static
Definition at line 1017 of file oversetFvMeshBaseTemplates.C.
References Foam::endl(), fld(), forAll, and Foam::Pout.
correctBoundaryConditions()
template<class GeoField , class PatchType > void correctBoundaryConditions (typename GeoField::Boundary & bfld, const bool typeOnly) static
Definition at line 70 of file oversetFvMeshBaseTemplates.C.
References UPstream::defaultCommsType, forAll, UPstream::nonBlocking, UPstream::nRequests(), and UPstream::waitRequests().
Referenced by cellVolumeWeight::update(), inverseDistance::update(), and trackingInverseDistance::update().
normalisation() [1/2]
template<class Type > tmp< scalarField > normalisation (const fvMatrix< Type > & m) const
normalisation() [2/2]
template<class Type > Foam::tmp< Foam::scalarField > normalisation (const fvMatrix< Type > & m) const
Definition at line 104 of file oversetFvMeshBaseTemplates.C.
References Foam::endl(), forAll, cellCellStencil::HOLE, Foam::magSqr(), n, MeshObject< Mesh, MeshObjectType, Type >::New(), overlap, Foam::Pout, Foam::returnReduce(), Foam::returnReduceOr(), PtrList< T >::set(), Foam::sqr(), syncTools::swapBoundaryCellList(), syncTools::syncFaceList(), and PtrList< T >::transfer().
solveOverset() [2/2]
template<class Type > Foam::SolverPerformance< Type > solveOverset (fvMatrix< Type > & m, const dictionary & dict) const
Definition at line 697 of file oversetFvMeshBaseTemplates.C.
References boundaryFieldRef(), GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), cellCellStencil::CALCULATED, correctBoundaryConditions(), dict, Foam::dimless, Foam::endl(), DimensionedField< Type, GeoMesh >::field(), forAll, cellCellStencil::HOLE, Foam::isA(), IOobject::name(), MeshObject< Mesh, MeshObjectType, Type >::New(), IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, overlap, Foam::Pout, psi, GeometricField< Type, PatchField, GeoMesh >::ref(), s(), PtrList< T >::setSize(), UPtrList< T >::size(), PtrList< T >::transfer(), regIOobject::write(), and Foam::Zero.
Member Data Documentation
mesh_
const fvMesh& mesh_ protected
Definition at line 68 of file oversetFvMeshBase.H.
Referenced by oversetFvMeshBase::active(), oversetFvMeshBase::oversetFvMeshBase(), and oversetFvMeshBase::updateAddressing().
active_
bool active_ mutable protected
Definition at line 72 of file oversetFvMeshBase.H.
Referenced by oversetFvMeshBase::active(), and oversetFvMeshBase::active().
lduPtr_
autoPtr<fvMeshPrimitiveLduAddressing> lduPtr_ mutable protected
Definition at line 75 of file oversetFvMeshBase.H.
Referenced by oversetFvMeshBase::updateAddressing().
remoteStencilInterfaces_
PtrList<const lduPrimitiveProcessorInterface> remoteStencilInterfaces_ mutable protected
Definition at line 79 of file oversetFvMeshBase.H.
Referenced by oversetFvMeshBase::updateAddressing().
allInterfaces_
lduInterfacePtrsList allInterfaces_ mutable protected
Definition at line 83 of file oversetFvMeshBase.H.
Referenced by oversetFvMeshBase::active(), and oversetFvMeshBase::updateAddressing().
stencilFaces_
labelListList stencilFaces_ mutable protected
Definition at line 86 of file oversetFvMeshBase.H.
Referenced by oversetFvMeshBase::updateAddressing().
stencilPatches_
labelListList stencilPatches_ mutable protected
Definition at line 89 of file oversetFvMeshBase.H.
Referenced by oversetFvMeshBase::updateAddressing().
reverseFaceMap_
labelList reverseFaceMap_ mutable protected
Definition at line 92 of file oversetFvMeshBase.H.
Referenced by oversetFvMeshBase::reverseFaceMap(), and oversetFvMeshBase::updateAddressing().
The documentation for this class was generated from the following files:
src/overset/oversetFvMesh/oversetFvMeshBase.H
src/overset/oversetFvMesh/oversetFvMeshBase.C
src/overset/oversetFvMesh/oversetFvMeshBaseTemplates.C