OpenFOAM: exprResult Class Reference
exprResult Class Reference
A polymorphic field/result from evaluating an expression.
#include <exprResult.H>
Public Member Functions
TypeName ("exprResult")
declareRunTimeSelectionTable (autoPtr, exprResult, dictionary,(const dictionary &dict),(dict))
declareRunTimeSelectionTable (autoPtr, exprResult, empty,(),())
exprResult ()
exprResult (const exprResult &expr)
exprResult (exprResult &&expr)
exprResult (const dictionary &dict, const bool uniform=false, const bool needsValue=false)
exprResult (Istream &is)
template<class Type >
exprResult (const Field< Type > &fld)
template<class Type >
exprResult (Field< Type > &&fld)
template<class Type >
exprResult (autoPtr< Type > &&obj)
template<class Type >
exprResult (const dimensioned< Type > &dt)
exprResult (const bool &val)
Construct from single value of bool.
exprResult (const scalar &val)
Construct from single value of scalar.
exprResult (const vector &val)
Construct from single value of vector.
exprResult (const tensor &val)
Construct from single value of tensor.
exprResult (const symmTensor &val)
Construct from single value of symmTensor.
exprResult (const sphericalTensor &val)
Construct from single value of sphericalTensor.
virtual autoPtr< exprResult > clone () const
virtual ~exprResult ()
bool hasValue () const
const word & valueType () const noexcept
bool isPointData (const bool wantPointData=true) const
bool isUniform () const
template<class Type >
bool isType () const
template<class Type >
Type getValue () const
bool is_bool () const
label size () const
const void * dataAddress () const
void clear ()
void noReset () noexcept
void allowReset () noexcept
void testIfSingleValue (const bool parRun=Pstream::parRun())
template<class Type >
void setResult (Field< Type > *, bool wantPointData=false)
template<class Type >
void setResult (const Field< Type > &, bool wantPointData=false)
template<class Type >
void setResult (Field< Type > &&, bool wantPointData=false)
template<class Type >
void setResult (const Type &val, const label size)
template<class Type >
void setSingleValue (const Type &val)
template<class Type >
const Field< Type > & cref () const
template<class Type >
Field< Type > & ref ()
template<class Type >
Field< Type > & constCast () const
template<class Type >
tmp< Field< Type > > getResult (bool cacheCopy=false)
exprResult getUniform (const label size, const bool noWarn, const bool parRun=Pstream::parRun()) const
template<template< class > class BinaryOp, class Type >
Type getReduced (const BinaryOp< Type > &bop, const Type &initial=pTraits< Type >::zero)
void writeEntry (const word &keyword, Ostream &os) const
void writeDict (Ostream &os, const bool subDict=true) const
void writeField (Ostream &os, const word &keyword="") const
void writeValue (Ostream &os) const
virtual void operator= (const exprResult &rhs)
virtual void operator= (exprResult &&rhs)
exprResult & operator*= (const scalar &b)
exprResult & operator+= (const exprResult &b)
template<class Type >
Foam::tmp< Foam::Field< Type > > getResult (bool cacheCopy)
template<class Type >
const Foam::Field< Type > & cref () const
template<class Type >
Foam::Field< Type > & ref ()
template<class Type >
Foam::Field< Type > & constCast () const
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Static Public Member Functions
static autoPtr< exprResult > New (const dictionary &dict)
static autoPtr< exprResult > New (Istream &is)
Static Public Attributes
static const exprResult null
Protected Member Functions
virtual expressions::exprResult & target ()
virtual void resetImpl ()
bool reset (bool force=false)
void needsReset (bool val)
Friends
class exprResultGlobals
Detailed Description
A polymorphic field/result from evaluating an expression.
Dictionary parameters
Property Description Required Default
resultType The type of result no exprResult
unsetValue Create without reading the dictionary no false
noReset Suppress reset on time no false
When creating with values
Property Description Required Default
valueType Result value type (scalar, vector,..) yes
isSingleValue A single field value no false
isPointValue Interpret values as point values no false
value The field values yes
fieldSize The size of the field (when not single-value) no
Source files
exprResult.H
exprResult.C
exprResultI.H
Definition at line 120 of file exprResult.H.
Constructor & Destructor Documentation
exprResult() [1/15]
exprResult ()
Definition at line 199 of file exprResult.C.
References exprResult::clear().
exprResult() [2/15]
exprResult (const exprResult & expr)
Definition at line 215 of file exprResult.C.
References exprResult::operator=().
exprResult() [3/15]
exprResult (exprResult && expr)
Definition at line 223 of file exprResult.C.
References exprResult::operator=().
exprResult() [4/15]
exprResult (const dictionary & dict, const bool uniform = false, const bool needsValue = false) explicit
Definition at line 231 of file exprResult.C.
References DebugInFunction, dict, Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, dictionary::getOrDefault(), exprResult::hasValue(), keyType::LITERAL, and Foam::nl.
exprResult() [5/15]
exprResult (Istream & is) explicit
exprResult() [6/15]
template<class Type > exprResult (const Field< Type > & fld) explicit
Definition at line 187 of file exprResultI.H.
References DebugInFunction, fld(), Foam::nl, and exprResult::setResult().
exprResult() [7/15]
template<class Type > exprResult (Field< Type > && fld) explicit
Definition at line 198 of file exprResultI.H.
References DebugInFunction, fld(), Foam::nl, and exprResult::setResult().
exprResult() [8/15]
template<class Type > exprResult (autoPtr< Type > && obj) explicit
exprResult() [9/15]
template<class Type > exprResult (const dimensioned< Type > & dt) explicit
Definition at line 209 of file exprResultI.H.
References DebugInFunction, Foam::nl, and exprResult::setSingleValue().
exprResult() [10/15]
exprResult (const bool & val) inline explicit
Construct from single value of bool.
Definition at line 388 of file exprResult.H.
exprResult() [11/15]
exprResult (const scalar & val) inline explicit
Construct from single value of scalar.
Definition at line 389 of file exprResult.H.
exprResult() [12/15]
exprResult (const vector & val) inline explicit
Construct from single value of vector.
Definition at line 390 of file exprResult.H.
exprResult() [13/15]
exprResult (const tensor & val) inline explicit
Construct from single value of tensor.
Definition at line 391 of file exprResult.H.
exprResult() [14/15]
exprResult (const symmTensor & val) inline explicit
Construct from single value of symmTensor.
Definition at line 392 of file exprResult.H.
exprResult() [15/15]
exprResult (const sphericalTensor & val) inline explicit
Construct from single value of sphericalTensor.
Definition at line 393 of file exprResult.H.
~exprResult()
~exprResult () virtual
Definition at line 364 of file exprResult.C.
References DebugInFunction, and Foam::nl.
Member Function Documentation
target()
virtual expressions::exprResult & target () inline protected virtual
Reimplemented in exprResultDelayed.
Definition at line 297 of file exprResult.H.
resetImpl()
void resetImpl () protected virtual
Reimplemented in exprResultStored, and exprResultStoredStack.
Definition at line 374 of file exprResult.C.
References clear().
reset()
bool reset (bool force = false) protected
Definition at line 380 of file exprResult.C.
needsReset()
void needsReset (bool val) inline protected
Definition at line 307 of file exprResult.H.
Referenced by exprResultStack::exprResultStack(), exprResultStack::exprResultStack(), exprResultStack::exprResultStack(), exprResultStoredStack::exprResultStoredStack(), exprResultStoredStack::exprResultStoredStack(), and exprResultStoredStack::exprResultStoredStack().
TypeName()
TypeName ("exprResult")
declareRunTimeSelectionTable() [1/2]
declareRunTimeSelectionTable (autoPtr , exprResult , dictionary , (const dictionary &dict) , (dict))
declareRunTimeSelectionTable() [2/2]
declareRunTimeSelectionTable (autoPtr , exprResult , empty , () , ())
New() [1/2]
Foam::autoPtr< Foam::expressions::exprResult > New (const dictionary & dict) static
Definition at line 299 of file exprResult.C.
References DebugInfo, dict, Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, and Foam::nl.
Referenced by exprResultGlobals::addValue().
New() [2/2]
Foam::autoPtr< Foam::expressions::exprResult > New (Istream & is) static
Definition at line 352 of file exprResult.C.
References dict, and Foam::New().
clone()
virtual autoPtr< exprResult > clone () const inline virtual
Reimplemented in exprResultDelayed, exprResultStack, exprResultStored, and exprResultStoredStack.
Definition at line 407 of file exprResult.H.
References autoPtr< T >::New().
hasValue()
bool hasValue () const inline
Definition at line 220 of file exprResultI.H.
Referenced by Foam::stringOps::evaluate(), exprResult::exprResult(), and Function1Expression< Type >::value().
valueType()
const Foam::word & valueType () const inline noexcept
Definition at line 227 of file exprResultI.H.
Referenced by exprDriver::getResultType(), exprResultStack::push(), and Function1Expression< Type >::value().
isPointData()
bool isPointData (const bool wantPointData = true) const inline
Definition at line 233 of file exprResultI.H.
Referenced by exprDriver::getResult().
isUniform()
bool isUniform () const inline
Definition at line 242 of file exprResultI.H.
isType()
template<class Type > bool isType () const inline
Definition at line 249 of file exprResultI.H.
Referenced by Function1Expression< Type >::value().
getValue()
template<class Type > Type getValue () const inline
Definition at line 256 of file exprResultI.H.
References UPtrList< T >::get(), and Foam::Zero.
is_bool()
bool is_bool () const inline
Definition at line 267 of file exprResultI.H.
size()
Foam::label size () const inline
Definition at line 273 of file exprResultI.H.
Referenced by Foam::stringOps::evaluate(), and Function1Expression< Type >::value().
dataAddress()
const void * dataAddress () const
Definition at line 829 of file exprResult.C.
References defineExpressionMethod, Foam::exit(), Foam::FatalError, FatalErrorInFunction, and Foam::nl.
clear()
void clear ()
Definition at line 392 of file exprResult.C.
Referenced by exprResult::exprResult().
noReset()
void noReset () inline noexcept
Definition at line 462 of file exprResult.H.
allowReset()
void allowReset () inline noexcept
Definition at line 465 of file exprResult.H.
testIfSingleValue()
void testIfSingleValue (const bool parRun = Pstream::parRun())
Definition at line 467 of file exprResult.C.
References Foam::endl(), Foam::nl, and WarningInFunction.
setResult() [1/4]
template<class Type > void setResult (Field< Type > * fldPtr, bool wantPointData = false) inline
Definition at line 350 of file exprResultI.H.
Referenced by exprResult::exprResult(), and exprResult::exprResult().
setResult() [2/4]
template<class Type > void setResult (const Field< Type > & val, bool wantPointData = false) inline
Definition at line 280 of file exprResultI.H.
References DebugInFunction, and Foam::nl.
setResult() [3/4]
template<class Type > void setResult (Field< Type > && val, bool wantPointData = false) inline
Definition at line 293 of file exprResultI.H.
References DebugInFunction, and Foam::nl.
setResult() [4/4]
template<class Type > void setResult (const Type & val, const label size) inline
Definition at line 382 of file exprResultI.H.
setSingleValue()
template<class Type > void setSingleValue (const Type & val) inline
Definition at line 415 of file exprResultI.H.
Referenced by exprDriver::addUniformVariable(), and exprResult::exprResult().
cref() [1/2]
template<class Type > const Field< Type > & cref () const inline
Referenced by Function1Expression< Type >::value().
ref() [1/2]
template<class Type > Field< Type > & ref () inline
constCast() [1/2]
template<class Type > Field< Type > & constCast () const inline
getResult() [1/2]
template<class Type > tmp< Field< Type > > getResult (bool cacheCopy = false) inline
Referenced by exprDriver::getResult().
getUniform()
Foam::expressions::exprResult getUniform (const label size, const bool noWarn, const bool parRun = Pstream::parRun()) const
Definition at line 431 of file exprResult.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and Foam::nl.
getReduced()
template<template< class > class BinaryOp, class Type > Type getReduced (const BinaryOp< Type > & bop, const Type & initial = pTraits<Type>::zero) inline
Definition at line 719 of file exprResultI.H.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, fld(), Foam::nl, and Foam::returnReduce().
writeEntry()
void writeEntry (const word & keyword, Ostream & os) const
Definition at line 556 of file exprResult.C.
References Foam::endl(), os(), and WarningInFunction.
writeDict()
void writeDict (Ostream & os, const bool subDict = true) const
Definition at line 580 of file exprResult.C.
References DebugInFunction, IOstreamOption::formatNames, Foam::name(), Foam::nl, and os().
writeField()
void writeField (Ostream & os, const word & keyword = "") const
Definition at line 624 of file exprResult.C.
References DebugInFunction, Foam::endl(), IOstreamOption::formatNames, Foam::name(), Foam::nl, os(), and WarningInFunction.
Referenced by Foam::stringOps::evaluate().
writeValue()
void writeValue (Ostream & os) const
Definition at line 656 of file exprResult.C.
References DebugInFunction, Foam::endl(), IOstreamOption::formatNames, Foam::name(), Foam::nl, os(), and WarningInFunction.
Referenced by Foam::stringOps::evaluate().
operator=() [1/2]
void operator= (const exprResult & rhs) virtual
Reimplemented in exprResultDelayed, exprResultStack, and exprResultStored.
Definition at line 494 of file exprResult.C.
References clear(), DebugInFunction, Foam::exit(), Foam::FatalError, FatalErrorInFunction, and Foam::nl.
Referenced by exprResult::exprResult(), exprResult::exprResult(), exprResultStored::operator=(), exprResultDelayed::operator=(), exprResultStored::operator=(), exprResultStack::push(), and exprResultDelayed::setReadValue().
operator=() [2/2]
void operator= (exprResult && rhs) virtual
Reimplemented in exprResultDelayed.
Definition at line 532 of file exprResult.C.
References clear().
operator*=()
Foam::expressions::exprResult & operator*= (const scalar & b)
Definition at line 690 of file exprResult.C.
References b, Foam::exit(), Foam::FatalError, FatalErrorInFunction, and Foam::nl.
operator+=()
Foam::expressions::exprResult & operator+= (const exprResult & b)
Definition at line 724 of file exprResult.C.
References b, Foam::exit(), Foam::FatalError, FatalErrorInFunction, and Foam::nl.
getResult() [2/2]
template<class Type > Foam::tmp< Foam::Field< Type > > getResult (bool cacheCopy) inline
Definition at line 635 of file exprResultI.H.
References clear(), DebugInFunction, Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::New(), and Foam::nl.
cref() [2/2]
template<class Type > const Foam::Field< Type > & cref () const inline
Definition at line 677 of file exprResultI.H.
References DebugInFunction, Foam::exit(), Foam::FatalError, FatalErrorInFunction, and Foam::nl.
ref() [2/2]
template<class Type > Foam::Field< Type > & ref () inline
Definition at line 704 of file exprResultI.H.
constCast() [2/2]
template<class Type > Foam::Field< Type > & constCast () const inline
Definition at line 712 of file exprResultI.H.
Friends And Related Symbol Documentation
exprResultGlobals
friend class exprResultGlobals friend
Definition at line 316 of file exprResult.H.
Member Data Documentation
null
const Foam::expressions::exprResult null static
Definition at line 313 of file exprResult.H.
Referenced by exprResultGlobals::get().
The documentation for this class was generated from the following files:
src/OpenFOAM/expressions/exprResult/exprResult.H
src/OpenFOAM/expressions/exprResult/exprResult.C
src/OpenFOAM/expressions/exprResult/exprResultI.H