OpenFOAM: heatExchangerSource Class Reference
heatExchangerSource Class Reference
Numerics » Finite volume Options » Sources
Heat exchanger source model for compressible flows, where the heat exchanger is modelled as an energy source using a selection of cells.
#include <heatExchangerSource.H>
Public Member Functions
TypeName ("heatExchangerSource")
heatExchangerSource (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
heatExchangerSource (const heatExchangerSource &)=delete
void operator= (const heatExchangerSource &)=delete
virtual ~heatExchangerSource ()=default
virtual void addSup (fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldi)
virtual bool read (const dictionary &dict)
Public Member Functions inherited from cellSetOption
TypeName ("cellSetOption")
cellSetOption (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
virtual ~cellSetOption ()=default
scalar timeStart () const noexcept
scalar duration () const noexcept
bool inTimeLimits (const scalar timeValue) const
bool useSubMesh () const noexcept
selectionModeType selectionMode () const noexcept
const wordRes & selectionNames () const noexcept
const wordRe & zoneName () const
scalar V () const noexcept
const labelList & cells () const noexcept
scalar timeStart (scalar val) noexcept
scalar duration (scalar val) noexcept
virtual bool isActive ()
const word & cellSetName () const
Public Member Functions inherited from option
TypeName ("option")
declareRunTimeSelectionTable (autoPtr, option, dictionary,(const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh),(name, modelType, dict, mesh))
option (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
autoPtr< option > clone () const
virtual ~option ()=default
const word & name () const noexcept
const fvMesh & mesh () const noexcept
const dictionary & coeffs () const noexcept
bool active () const noexcept
void setApplied (const label fieldi)
bool active (const bool on) noexcept
virtual label applyToField (const word &fieldName) const
virtual void checkApplied () const
virtual void addSup (fvMatrix< vector > &eqn, const label fieldi)
virtual void addSup (fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (fvMatrix< tensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< scalar > &eqn, const label fieldi)
virtual void constrain (fvMatrix< vector > &eqn, const label fieldi)
virtual void constrain (fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< tensor > &eqn, const label fieldi)
virtual void correct (volScalarField &field)
virtual void correct (volVectorField &field)
virtual void correct (volSphericalTensorField &field)
virtual void correct (volSymmTensorField &field)
virtual void correct (volTensorField &field)
virtual void postProcessSens (scalarField &sensField, const word &fieldName=word::null, const word &designVariablesName=word::null)
virtual void postProcessSens (vectorField &sensField, const word &fieldName=word::null, const word &designVariablesName=word::null)
virtual void postProcessSens (tensorField &sensField, const word &fieldName=word::null, const word &designVariablesName=word::null)
virtual void writeHeader (Ostream &) const
virtual void writeFooter (Ostream &) const
virtual void writeData (Ostream &) const
Additional Inherited Members
Public Types inherited from cellSetOption
enum selectionModeType {
smAll , smCellSet , smCellZone , smPoints ,
smGeometric , smCellType
}
Static Public Member Functions inherited from option
static autoPtr< option > New (const word &name, const dictionary &dict, const fvMesh &mesh)
Public Attributes inherited from option
bool log
Static Public Attributes inherited from cellSetOption
static const Enum< selectionModeType > selectionModeTypeNames_
Protected Member Functions inherited from cellSetOption
void setSelection (const dictionary &dict)
void setCellSelection ()
void setVol ()
Protected Member Functions inherited from option
void resetApplied ()
Protected Attributes inherited from cellSetOption
scalar timeStart_
scalar duration_
selectionModeType selectionMode_
wordRes selectionNames_
List< point > points_
dictionary geometricSelection_
labelList cells_
scalar V_
Protected Attributes inherited from option
const word name_
const word modelType_
const fvMesh & mesh_
dictionary dict_
dictionary coeffs_
wordList fieldNames_
List< bool > applied_
bool active_
Detailed Description
Heat exchanger source model for compressible flows, where the heat exchanger is modelled as an energy source using a selection of cells.
Sources applied to either of the below, if exist:
  e         | Internal energy                            [m2/s2]
  h         | Enthalphy                                  [m2/s2]
Required fields:
  T         | Temperature                                [K]
  U         | Velocity                                   [m/s]
  phi       | Mass flux                                  [kg/s]
Usage
Minimal example by using constant/fvOptions:
<name>
{
    // Mandatory entries
    type                     heatExchangerSource;
    model                    <word>;
    faceZone                 <word>;
    // Conditional entries
        // Option-1: when model == effectivenessTable
        // Option-2: when model == referenceTemperature
    // Optional entries
    U                        <word>;
    T                        <word>;
    phi                      <word>;
    // Inherited entries
    ...
}
where the entries mean:
Property Description Type Reqd Deflt
type Type name: heatExchangerSource word yes -
model Name of the heat exchanger model word yes -
faceZone
Name of the faceZone at the heat exchanger inlet
word yes -
U Name of operand velocity field word no U
T Name of operand temperature field word no T
phi Name of operand flux field word no phi
Options for the model entry:
      effectivenessTable    | Calculate heat exchange via an effectiveness table
      referenceTemperature  | Calculate heat exchange via a temperature table
The inherited entries are elaborated in:
fvOption.H
cellSetOption.H
writeFile.H
Function1.H
Source files
heatExchangerSource.H
heatExchangerSource.C
Definition at line 164 of file heatExchangerSource.H.
Constructor & Destructor Documentation
heatExchangerSource() [1/2]
heatExchangerSource (const word & name, const word & modelType, const dictionary & dict, const fvMesh & mesh)
Definition at line 42 of file heatExchangerSource.C.
References dict, basicThermo::dictName, option::fieldNames_, option::mesh_, Foam::name(), Foam::New(), heatExchangerSource::read(), option::resetApplied(), and List< T >::resize().
heatExchangerSource() [2/2]
heatExchangerSource (const heatExchangerSource &) delete
~heatExchangerSource()
virtual ~heatExchangerSource () virtual default
Member Function Documentation
TypeName()
TypeName ("heatExchangerSource")
operator=()
void operator= (const heatExchangerSource &) delete
addSup() [1/2]
virtual void addSup (fvMatrix< scalar > & eqn, const label fieldi) inline virtual
Reimplemented from option.
Definition at line 205 of file heatExchangerSource.H.
References NotImplemented.
addSup() [2/2]
void addSup (const volScalarField & rho, fvMatrix< scalar > & eqn, const label fieldi) virtual
Reimplemented from option.
Definition at line 70 of file heatExchangerSource.C.
References forAll, Foam::log(), Foam::mag(), U, and UName().
read()
bool read (const dictionary & dict) virtual
Reimplemented from cellSetOption.
Definition at line 98 of file heatExchangerSource.C.
References dict, and cellSetOption::read().
Referenced by heatExchangerSource::heatExchangerSource().
The documentation for this class was generated from the following files:
src/fvOptions/sources/derived/heatExchangerSource/heatExchangerSource.H
src/fvOptions/sources/derived/heatExchangerSource/heatExchangerSource.C