OpenFOAM: WALE< BasicTurbulenceModel > Class Template Reference
WALE< BasicTurbulenceModel > Class Template Reference
Turbulence models » LES turbulence
The Wall-adapting local eddy-viscosity (WALE) SGS model.
#include <WALE.H>
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from LESeddyViscosity< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from eddyViscosity< LESModel< BasicTurbulenceModel > >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from linearViscousStress< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("WALE")
WALE (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
virtual ~WALE ()=default
virtual bool read ()
virtual tmp< volScalarField > k () const
virtual void correct ()
Public Member Functions inherited from LESeddyViscosity< BasicTurbulenceModel >
LESeddyViscosity (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
virtual ~LESeddyViscosity ()=default
Public Member Functions inherited from eddyViscosity< LESModel< BasicTurbulenceModel > >
eddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~eddyViscosity ()=default
virtual tmp< volScalarField > nut () const
virtual tmp< scalarField > nut (const label patchi) const
virtual tmp< volSymmTensorField > R () const
virtual void validate ()
Public Member Functions inherited from linearViscousStress< BasicTurbulenceModel >
linearViscousStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~linearViscousStress ()=default
virtual tmp< volSymmTensorField > devRhoReff () const
virtual tmp< volSymmTensorField > devRhoReff (const volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Protected Member Functions
tmp< volSymmTensorField > Sd (const volTensorField &gradU) const
tmp< volScalarField > k (const volTensorField &gradU) const
virtual void correctNut ()
Protected Attributes
dimensionedScalar Ck_
dimensionedScalar Cw_
Protected Attributes inherited from eddyViscosity< LESModel< BasicTurbulenceModel > >
volScalarField nut_
Detailed Description
template<class BasicTurbulenceModel>
class Foam::LESModels::WALE< BasicTurbulenceModel >
The Wall-adapting local eddy-viscosity (WALE) SGS model.
Reference:
    Nicoud, F., & Ducros, F. (1999).
    Subgrid-scale stress modelling based on the square of the velocity
    gradient tensor.
    Flow, Turbulence and Combustion, 62(3), 183-200.
The default model coefficients are
    WALECoeffs
    {
        Ck                  0.094;
        Ce                  1.048;e
        Cw                  0.325;
    }
See also
Foam::LESModels::Smagorinsky
Source files
WALE.H
WALE.C
Definition at line 75 of file WALE.H.
Member Typedef Documentation
alphaField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 112 of file WALE.H.
rhoField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 113 of file WALE.H.
transportModel
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 114 of file WALE.H.
Constructor & Destructor Documentation
WALE()
template<class BasicTurbulenceModel > WALE (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Definition at line 98 of file WALE.C.
References Foam::type().
~WALE()
template<class BasicTurbulenceModel > virtual ~WALE () virtual default
Member Function Documentation
Sd()
template<class BasicTurbulenceModel > tmp< volSymmTensorField > Sd (const volTensorField & gradU) const protected
Definition at line 35 of file WALE.C.
References Foam::devSymm().
k() [1/2]
template<class BasicTurbulenceModel > tmp< volScalarField > k (const volTensorField & gradU) const protected
Definition at line 45 of file WALE.C.
References delta, IOobject::groupName(), Foam::magSqr(), Foam::pow(), Foam::pow3(), Foam::sqr(), and Foam::symm().
correctNut()
template<class BasicTurbulenceModel > void correctNut () protected virtual
Implements eddyViscosity< LESModel< BasicTurbulenceModel > >.
Definition at line 85 of file WALE.C.
References delta, Foam::fvc::grad(), k, options::New(), and Foam::sqrt().
TypeName()
template<class BasicTurbulenceModel > TypeName ("WALE< BasicTurbulenceModel >")
read()
template<class BasicTurbulenceModel > bool read () virtual
Reimplemented from LESeddyViscosity< BasicTurbulenceModel >.
Definition at line 152 of file WALE.C.
k() [2/2]
template<class BasicTurbulenceModel > virtual tmp< volScalarField > k () const inline virtual
Implements eddyViscosity< LESModel< BasicTurbulenceModel > >.
Definition at line 147 of file WALE.H.
References Foam::fvc::grad(), and WALE< BasicTurbulenceModel >::k().
Referenced by WALE< BasicTurbulenceModel >::k().
correct()
template<class BasicTurbulenceModel > void correct () virtual
Implements eddyViscosity< LESModel< BasicTurbulenceModel > >.
Definition at line 167 of file WALE.C.
References linearViscousStress< BasicTurbulenceModel >::correct().
Member Data Documentation
Ck_
template<class BasicTurbulenceModel > dimensionedScalar Ck_ protected
Definition at line 92 of file WALE.H.
Cw_
template<class BasicTurbulenceModel > dimensionedScalar Cw_ protected
Definition at line 93 of file WALE.H.
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/LES/WALE/WALE.H
src/TurbulenceModels/turbulenceModels/LES/WALE/WALE.C