OpenFOAM: LList< LListBase, T > Class Template Reference
LList< LListBase, T > Class Template Reference
Template class for non-intrusive linked lists.
#include <LList.H>
Classes
class const_iterator
class const_reverse_iterator
class iterator
struct link
class reverse_iterator
Public Types
typedef T value_type
typedef T * pointer
typedef const T * const_pointer
typedef T & reference
typedef const T & const_reference
typedef label size_type
typedef label difference_type
using base_iterator = typename LListBase::iterator
using const_base_iterator = typename LListBase::const_iterator
Public Member Functions
LList ()=default
LList (const T &elem)
LList (T &&elem)
LList (Istream &is)
LList (const LList< LListBase, T > &lst)
LList (LList< LListBase, T > &&lst)
LList (std::initializer_list< T > lst)
~LList ()
reference front ()
const_reference front () const
reference back ()
const_reference back () const
void push_front (const T &elem)
void push_front (T &&elem)
void push_back (const T &elem)
void push_back (T &&elem)
void clear ()
void pop_front (label n=1)
T removeHead ()
T remove (link *item)
T remove (iterator &iter)
void transfer (LList< LListBase, T > &lst)
void operator= (const LList< LListBase, T > &lst)
void operator= (LList< LListBase, T > &&lst)
void operator= (std::initializer_list< T > lst)
Istream & readList (Istream &is)
Ostream & writeList (Ostream &os, const label shortLen=0) const
iterator begin ()
const_iterator cbegin () const
reverse_iterator rbegin ()
const_reverse_iterator crbegin () const
const_iterator begin () const
const_reverse_iterator rbegin () const
const iterator & end ()
const const_iterator & cend () const
const reverse_iterator & rend ()
const const_reverse_iterator & crend () const
const const_iterator & end () const
const const_reverse_iterator & rend () const
reference first ()
const_reference first () const
reference last ()
const_reference last () const
void prepend (const T &elem)
void prepend (T &&elem)
void append (const T &elem)
void append (T &&elem)
void insert (const T &elem)
void insert (T &&elem)
Friends
Istream & operator>> (Istream &, LList< LListBase, T > &lst)
Ostream & operator (Ostream &os, const LList< LListBase, T > &lst)
Detailed Description
template<class LListBase, class T>
class Foam::LList< LListBase, T >
Template class for non-intrusive linked lists.
Source files
LList.H
LList.C
LListIO.C
Definition at line 68 of file LList.H.
Member Typedef Documentation
value_type
template<class LListBase , class T > typedef T value_type
Definition at line 77 of file LList.H.
pointer
template<class LListBase , class T > typedef T* pointer
Definition at line 80 of file LList.H.
const_pointer
template<class LListBase , class T > typedef const T* const_pointer
Definition at line 83 of file LList.H.
reference
template<class LListBase , class T > typedef T& reference
Definition at line 86 of file LList.H.
const_reference
template<class LListBase , class T > typedef const T& const_reference
Definition at line 89 of file LList.H.
size_type
template<class LListBase , class T > typedef label size_type
Definition at line 92 of file LList.H.
difference_type
template<class LListBase , class T > typedef label difference_type
Definition at line 95 of file LList.H.
base_iterator
template<class LListBase , class T > using base_iterator = typename LListBase::iterator
Definition at line 103 of file LList.H.
const_base_iterator
template<class LListBase , class T > using const_base_iterator = typename LListBase::const_iterator
Definition at line 104 of file LList.H.
Constructor & Destructor Documentation
LList() [1/7]
template<class LListBase , class T > LList () default
LList() [2/7]
template<class LListBase , class T > LList (const T & elem) inline explicit
Definition at line 169 of file LList.H.
References LList< LListBase, T >::push_front().
LList() [3/7]
template<class LListBase , class T > LList (T && elem) inline explicit
Definition at line 175 of file LList.H.
References LList< LListBase, T >::push_front().
LList() [4/7]
template<class LListBase , class T > LList (Istream & is) explicit
Definition at line 29 of file LListIO.C.
References PtrList< T >::operator>>.
LList() [5/7]
template<class LListBase , class T > LList (const LList< LListBase, T > & lst)
Definition at line 27 of file LList.C.
References LList< LListBase, T >::push_back(), and T.
LList() [6/7]
template<class LListBase , class T > LList (LList< LListBase, T > && lst)
Definition at line 39 of file LList.C.
LList() [7/7]
template<class LListBase , class T > LList (std::initializer_list< T > lst)
Definition at line 48 of file LList.C.
References LList< LListBase, T >::push_back(), and T.
~LList()
template<class LListBase , class T > ~LList ()
Definition at line 62 of file LList.C.
References clear().
Member Function Documentation
front() [1/2]
template<class LListBase , class T > reference front () inline
Definition at line 200 of file LList.H.
References LList< LListBase, T >::link::ref().
Referenced by FIFOStack< T >::bottom(), LList< LListBase, T >::first(), LList< LListBase, T >::first(), and LIFOStack< T >::top().
front() [2/2]
template<class LListBase , class T > const_reference front () const inline
Definition at line 206 of file LList.H.
References LList< LListBase, T >::link::ref().
back() [1/2]
template<class LListBase , class T > reference back () inline
Definition at line 212 of file LList.H.
References LList< LListBase, T >::link::ref().
Referenced by LIFOStack< T >::bottom(), LList< LListBase, T >::last(), LList< LListBase, T >::last(), and FIFOStack< T >::top().
back() [2/2]
template<class LListBase , class T > const_reference back () const inline
Definition at line 218 of file LList.H.
References LList< LListBase, T >::link::ref().
push_front() [1/2]
template<class LListBase , class T > void push_front (const T & elem) inline
Definition at line 225 of file LList.H.
Referenced by LList< LListBase, T >::insert(), LList< LListBase, T >::insert(), LList< LListBase, T >::LList(), LList< LListBase, T >::LList(), LList< LListBase, T >::prepend(), LList< LListBase, T >::prepend(), LIFOStack< T >::push(), and LIFOStack< T >::push().
push_front() [2/2]
template<class LListBase , class T > void push_front (T && elem) inline
Definition at line 231 of file LList.H.
push_back() [1/2]
template<class LListBase , class T > void push_back (const T & elem) inline
Definition at line 237 of file LList.H.
Referenced by LList< LListBase, T >::append(), LList< LListBase, T >::append(), LList< LListBase, T >::LList(), LList< LListBase, T >::LList(), FIFOStack< T >::push(), and FIFOStack< T >::push().
push_back() [2/2]
template<class LListBase , class T > void push_back (T && elem) inline
Definition at line 243 of file LList.H.
clear()
template<class LListBase , class T > void clear ()
Definition at line 88 of file LList.C.
Referenced by LPtrList< LListBase, T >::clear().
pop_front()
template<class LListBase , class T > void pop_front (label n = 1)
Definition at line 71 of file LList.C.
References n, and p.
removeHead()
template<class LListBase , class T > T removeHead () inline
Definition at line 255 of file LList.H.
References LList< LListBase, T >::link::remove().
Referenced by FIFOStack< T >::pop(), and LIFOStack< T >::pop().
remove() [1/2]
template<class LListBase , class T > T remove (link * item) inline
Definition at line 261 of file LList.H.
References LList< LListBase, T >::link::remove().
remove() [2/2]
template<class LListBase , class T > T remove (iterator & iter) inline
Definition at line 267 of file LList.H.
References LList< LListBase, T >::link::remove().
transfer()
template<class LListBase , class T > void transfer (LList< LListBase, T > & lst)
Definition at line 96 of file LList.C.
References clear().
Referenced by LPtrList< LListBase, T >::transfer().
operator=() [1/3]
template<class LListBase , class T > void operator= (const LList< LListBase, T > & lst)
Definition at line 106 of file LList.C.
References clear(), and T.
operator=() [2/3]
template<class LListBase , class T > void operator= (LList< LListBase, T > && lst)
Definition at line 118 of file LList.C.
References clear().
operator=() [3/3]
template<class LListBase , class T > void operator= (std::initializer_list< T > lst)
Definition at line 127 of file LList.C.
References clear(), and T.
readList()
template<class LListBase , class T > Foam::Istream & readList (Istream & is)
Definition at line 38 of file LListIO.C.
References token::BEGIN_LIST, PtrList< T >::clear(), token::END_LIST, Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, FUNCTION_NAME, PtrList< T >::push_back(), and T.
writeList()
template<class LListBase , class T > Foam::Ostream & writeList (Ostream & os, const label shortLen = 0) const
Definition at line 117 of file LListIO.C.
References token::BEGIN_LIST, IOstream::check(), token::END_LIST, FUNCTION_NAME, Foam::nl, os(), token::SPACE, and T.
begin() [1/2]
template<class LListBase , class T > iterator begin () inline
Definition at line 489 of file LList.H.
cbegin()
template<class LListBase , class T > const_iterator cbegin () const inline
Definition at line 495 of file LList.H.
Referenced by fieldAverageItem::calculateMeanField().
rbegin() [1/2]
template<class LListBase , class T > reverse_iterator rbegin () inline
Definition at line 501 of file LList.H.
crbegin()
template<class LListBase , class T > const_reverse_iterator crbegin () const inline
Definition at line 507 of file LList.H.
Referenced by LList< LListBase, T >::rbegin().
begin() [2/2]
template<class LListBase , class T > const_iterator begin () const inline
Definition at line 513 of file LList.H.
rbegin() [2/2]
template<class LListBase , class T > const_reverse_iterator rbegin () const inline
Definition at line 519 of file LList.H.
References LList< LListBase, T >::crbegin().
end() [1/2]
template<class LListBase , class T > const iterator & end () inline
Definition at line 526 of file LList.H.
Referenced by namesList< T >::find().
cend()
template<class LListBase , class T > const const_iterator & cend () const inline
Definition at line 532 of file LList.H.
Referenced by LList< LListBase, T >::end().
rend() [1/2]
template<class LListBase , class T > const reverse_iterator & rend () inline
Definition at line 538 of file LList.H.
crend()
template<class LListBase , class T > const const_reverse_iterator & crend () const inline
Definition at line 544 of file LList.H.
Referenced by LList< LListBase, T >::rend().
end() [2/2]
template<class LListBase , class T > const const_iterator & end () const inline
Definition at line 550 of file LList.H.
References LList< LListBase, T >::cend().
rend() [2/2]
template<class LListBase , class T > const const_reverse_iterator & rend () const inline
Definition at line 556 of file LList.H.
References LList< LListBase, T >::crend().
first() [1/2]
template<class LListBase , class T > reference first () inline
Definition at line 566 of file LList.H.
References LList< LListBase, T >::front().
Referenced by fieldAverageItem::calculateMeanField().
first() [2/2]
template<class LListBase , class T > const_reference first () const inline
Definition at line 570 of file LList.H.
References LList< LListBase, T >::front().
last() [1/2]
template<class LListBase , class T > reference last () inline
Definition at line 574 of file LList.H.
References LList< LListBase, T >::back().
last() [2/2]
template<class LListBase , class T > const_reference last () const inline
Definition at line 578 of file LList.H.
References LList< LListBase, T >::back().
prepend() [1/2]
template<class LListBase , class T > void prepend (const T & elem) inline
Definition at line 582 of file LList.H.
References LList< LListBase, T >::push_front().
prepend() [2/2]
template<class LListBase , class T > void prepend (T && elem) inline
Definition at line 586 of file LList.H.
References LList< LListBase, T >::push_front().
append() [1/2]
template<class LListBase , class T > void append (const T & elem) inline
Definition at line 590 of file LList.H.
References LList< LListBase, T >::push_back().
append() [2/2]
template<class LListBase , class T > void append (T && elem) inline
Definition at line 594 of file LList.H.
References LList< LListBase, T >::push_back().
insert() [1/2]
template<class LListBase , class T > void insert (const T & elem) inline
Definition at line 598 of file LList.H.
References LList< LListBase, T >::push_front().
insert() [2/2]
template<class LListBase , class T > void insert (T && elem) inline
Definition at line 602 of file LList.H.
References LList< LListBase, T >::push_front().
Friends And Related Symbol Documentation
operator>>
template<class LListBase , class T > Istream & operator>> (Istream & , LList< LListBase, T > & lst) friend
operator
template<class LListBase , class T > Ostream & operator (Ostream & os, const LList< LListBase, T > & lst) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/LinkedLists/accessTypes/LList/LList.H
src/OpenFOAM/containers/LinkedLists/accessTypes/LList/LList.C
src/OpenFOAM/containers/LinkedLists/accessTypes/LList/LListIO.C