OpenFOAM: axisAligned Class Reference
axisAligned Class Reference
Defines control points aligned with coordinate system.
#include <axisAligned.H>
Public Member Functions
TypeName ("axisAligned")
axisAligned (NURBS3DVolume &box)
virtual ~axisAligned ()=default
Public Member Functions inherited from controlPointsDefinition
TypeName ("controlPointsDefinition")
declareRunTimeSelectionTable (autoPtr, controlPointsDefinition, dictionary,(NURBS3DVolume &box),(box))
controlPointsDefinition (NURBS3DVolume &box)
virtual ~controlPointsDefinition ()=default
Protected Member Functions
virtual void computeControlPoints ()
Protected Member Functions inherited from controlPointsDefinition
void transformControlPoints (const vector &geometryMin, const vector &geometryMax)
Additional Inherited Members
Static Public Member Functions inherited from controlPointsDefinition
static autoPtr< controlPointsDefinition > New (NURBS3DVolume &box)
Protected Attributes inherited from controlPointsDefinition
NURBS3DVolume & box_
vectorField & cps_
Detailed Description
Defines control points aligned with coordinate system.
Source files
axisAligned.H
axisAligned.C
Definition at line 48 of file axisAligned.H.
Constructor & Destructor Documentation
axisAligned()
axisAligned (NURBS3DVolume & box)
Definition at line 79 of file axisAligned.C.
References axisAligned::computeControlPoints().
~axisAligned()
virtual ~axisAligned () virtual default
Member Function Documentation
computeControlPoints()
void computeControlPoints () protected virtual
Implements controlPointsDefinition.
Definition at line 43 of file axisAligned.C.
References NURBS3DVolume::basisU(), NURBS3DVolume::basisV(), NURBS3DVolume::basisW(), controlPointsDefinition::box_, controlPointsDefinition::cps_, NURBS3DVolume::dict(), UPtrList< T >::get(), NURBS3DVolume::getCPID(), and List< T >::setSize().
Referenced by axisAligned::axisAligned().
TypeName()
TypeName ("axisAligned")
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/parameterization/NURBS/NURBS3DVolume/controlPointsDefinition/axisAligned/axisAligned.H
src/optimisation/adjointOptimisation/adjoint/parameterization/NURBS/NURBS3DVolume/controlPointsDefinition/axisAligned/axisAligned.C