OpenFOAM: cellShapeControlMesh Class Reference
cellShapeControlMesh Class Reference
#include <cellShapeControlMesh.H>
Public Types
typedef CellSizeDelaunay::Cell_handle Cell_handle
typedef CellSizeDelaunay::Vertex_handle Vertex_handle
typedef CellSizeDelaunay::Point Point
Public Types inherited from DistributedDelaunayMesh< CellSizeDelaunay >
typedef Triangulation::Vertex_handle Vertex_handle
typedef Triangulation::Cell_handle Cell_handle
typedef Triangulation::Point Point
typedef Triangulation::Finite_vertices_iterator Finite_vertices_iterator
typedef Triangulation::Finite_cells_iterator Finite_cells_iterator
typedef Triangulation::All_cells_iterator All_cells_iterator
Public Types inherited from DelaunayMesh< Triangulation >
typedef Triangulation::Cell_handle Cell_handle
typedef Triangulation::Vertex_handle Vertex_handle
typedef Triangulation::Edge Edge
typedef Triangulation::Point Point
typedef Triangulation::Facet Facet
typedef Triangulation::Finite_vertices_iterator Finite_vertices_iterator
typedef Triangulation::Finite_cells_iterator Finite_cells_iterator
typedef Triangulation::Finite_facets_iterator Finite_facets_iterator
Public Member Functions
ClassName ("cellShapeControlMesh")
cellShapeControlMesh (const Time &runTime)
~cellShapeControlMesh ()=default
const Time & time () const
void barycentricCoords (const Foam::point &pt, barycentric &bary, Cell_handle &ch) const
boundBox bounds () const
label removePoints ()
tmp< pointField > cellCentres () const
Vertex_handle insert (const Foam::point &pt, const scalar &size, const triad &alignment, const Foam::indexedVertexEnum::vertexType type=Vb::vtInternal)
Vertex_handle insertFar (const Foam::point &pt)
void distribute (const backgroundMeshDecomposition &decomposition)
tensorField dumpAlignments () const
void writeTriangulation ()
void write () const
label estimateCellCount (const autoPtr< backgroundMeshDecomposition > &decomposition) const
Public Member Functions inherited from DistributedDelaunayMesh< CellSizeDelaunay >
DistributedDelaunayMesh (const Time &runTime)
DistributedDelaunayMesh (const Time &runTime, const word &meshName)
~DistributedDelaunayMesh ()=default
scalar calculateLoadUnbalance () const
bool distribute (const boundBox &bb)
autoPtr< mapDistribute > distribute (const backgroundMeshDecomposition &decomposition, List< Foam::point > &points)
void sync (const boundBox &bb)
void sync (const boundBox &bb, PtrList< labelPairHashSet > &referralVertices, labelPairHashSet &receivedVertices, bool iterateReferral=true)
labelPairHashSet rangeInsertReferredWithInfo (PointIterator begin, PointIterator end, bool printErrors=true)
Public Member Functions inherited from DelaunayMesh< Triangulation >
DelaunayMesh (const Time &runTime)
DelaunayMesh (const Time &runTime, const word &meshName)
~DelaunayMesh ()
const Time & time () const
void timeCheck (const string &description, const bool check=true) const
label getNewCellIndex () const
label getNewVertexIndex () const
label cellCount () const
label vertexCount () const
void resetCellCount ()
void resetVertexCount ()
void reset ()
Map< label > insertPoints (const List< Vb > &vertices, const bool reIndex)
template<class PointIterator >
Map< label > rangeInsertWithInfo (PointIterator begin, PointIterator end, bool printErrors=false, bool reIndex=true)
void printInfo (Ostream &os) const
void printVertexInfo (Ostream &os) const
autoPtr< polyMesh > createMesh (const fileName &name, labelPairLookup &vertexMap, labelList &cellMap, const bool writeDelaunayData=true) const
Static Public Attributes
static word meshSubDir
Additional Inherited Members
Static Public Member Functions inherited from DistributedDelaunayMesh< CellSizeDelaunay >
static autoPtr< mapDistribute > buildMap (const List< label > &toProc)
Detailed Description
Source files
cellShapeControlMesh.H
cellShapeControlMeshI.H
cellShapeControlMesh.C
Definition at line 60 of file cellShapeControlMesh.H.
Member Typedef Documentation
Cell_handle
typedef CellSizeDelaunay::Cell_handle Cell_handle
Definition at line 66 of file cellShapeControlMesh.H.
Vertex_handle
typedef CellSizeDelaunay::Vertex_handle Vertex_handle
Definition at line 67 of file cellShapeControlMesh.H.
Point
typedef CellSizeDelaunay::Point Point
Definition at line 68 of file cellShapeControlMesh.H.
Constructor & Destructor Documentation
cellShapeControlMesh()
cellShapeControlMesh (const Time & runTime) explicit
~cellShapeControlMesh()
~cellShapeControlMesh () default
Member Function Documentation
ClassName()
ClassName ("cellShapeControlMesh")
time()
const Time & time () const inline
Definition at line 114 of file cellShapeControlMesh.H.
barycentricCoords()
void barycentricCoords (const Foam::point & pt, barycentric & bary, Cell_handle & ch) const
bounds()
boundBox bounds () const
removePoints()
label removePoints ()
cellCentres()
tmp< pointField > cellCentres () const
insert()
Foam::cellShapeControlMesh::Vertex_handle insert (const Foam::point & pt, const scalar & size, const triad & alignment, const Foam::indexedVertexEnum::vertexType type = Vb::vtInternal) inline
Definition at line 23 of file cellShapeControlMeshI.H.
References DelaunayMesh< Triangulation >::getNewVertexIndex(), UPstream::myProcNo(), Foam::type(), Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
insertFar()
Foam::cellShapeControlMesh::Vertex_handle insertFar (const Foam::point & pt) inline
Definition at line 45 of file cellShapeControlMeshI.H.
References UPstream::myProcNo(), indexedVertexEnum::vtFar, Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
distribute()
void distribute (const backgroundMeshDecomposition & decomposition)
dumpAlignments()
tensorField dumpAlignments () const
writeTriangulation()
void writeTriangulation ()
write()
void write () const
estimateCellCount()
label estimateCellCount (const autoPtr< backgroundMeshDecomposition > & decomposition) const
Member Data Documentation
meshSubDir
word meshSubDir static
Definition at line 97 of file cellShapeControlMesh.H.
The documentation for this class was generated from the following files:
applications/utilities/mesh/generation/foamyMesh/conformalVoronoiMesh/cellShapeControl/cellShapeControlMesh/cellShapeControlMesh.H
applications/utilities/mesh/generation/foamyMesh/conformalVoronoiMesh/cellShapeControl/cellShapeControlMesh/cellShapeControlMeshI.H