OpenFOAM: ParticleTracks< CloudType > Class Template Reference
ParticleTracks< CloudType > Class Template Reference
Lagrangian particle models » Submodels » Function objects
Records particle state (all variables) on each call to postFace.
#include <ParticleTracks.H>
Public Member Functions
TypeName ("particleTracks")
ParticleTracks (const dictionary &dict, CloudType &owner, const word &modelName)
ParticleTracks (const ParticleTracks< CloudType > &ppm)
virtual autoPtr< CloudFunctionObject< CloudType > > clone () const
virtual ~ParticleTracks ()=default
label trackInterval () const
label maxSamples () const
bool resetOnWrite () const
const labelPairLookup & faceHitCounter () const
const Cloud< parcelType > & cloud () const
virtual void preEvolve (const typename parcelType::trackingData &td)
virtual void postFace (const parcelType &p, bool &keepParticle)
Public Member Functions inherited from CloudFunctionObject< CloudType >
TypeName ("cloudFunctionObject")
declareRunTimeSelectionTable (autoPtr, CloudFunctionObject, dictionary,(const dictionary &dict, CloudType &owner, const word &modelName),(dict, owner, modelName))
CloudFunctionObject (CloudType &owner)
CloudFunctionObject (const dictionary &dict, CloudType &owner, const word &objectType, const word &modelName)
CloudFunctionObject (const CloudFunctionObject< CloudType > &ppm)
virtual ~CloudFunctionObject ()=default
virtual void postEvolve (const typename parcelType::trackingData &td)
virtual void postMove (parcelType &p, const scalar dt, const point &position0, bool &keepParticle)
virtual void postPatch (const parcelType &p, const polyPatch &pp, bool &keepParticle)
const fileName & outputDir () const
fileName writeTimeDir () const
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
virtual ~CloudSubModelBase ()=default
const CloudType & owner () const
virtual bool writeTime () const
virtual fileName localPath () const
CloudType & owner ()
virtual void info ()
virtual void write (Ostream &os) const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
subModelBase (const subModelBase &smb)
virtual ~subModelBase ()=default
const word & modelName () const
const dictionary & dict () const
const word & baseName () const
const word & modelType () const
const dictionary & coeffDict () const
const dictionary & properties () const
virtual bool defaultCoeffs (const bool printMsg) const
virtual bool active () const
virtual void cacheFields (const bool store)
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
bool getModelDict (const word &entryName, dictionary &dict) const
template<class Type >
bool getModelProperty (const word &entryName, Type &value) const
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Protected Member Functions
void write ()
Protected Member Functions inherited from subModelBase
bool inLine () const
Additional Inherited Members
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Static Public Member Functions inherited from CloudFunctionObject< CloudType >
static autoPtr< CloudFunctionObject< CloudType > > New (const dictionary &dict, CloudType &owner, const word &objectType, const word &modelName)
Public Attributes inherited from subModelBase
bool log
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Protected Attributes inherited from subModelBase
const word modelName_
dictionary & properties_
const dictionary dict_
const word baseName_
const word modelType_
const dictionary coeffDict_
Detailed Description
template<class CloudType>
class Foam::ParticleTracks< CloudType >
Records particle state (all variables) on each call to postFace.
Source files
ParticleTracks.H
ParticleTracks.C
Definition at line 52 of file ParticleTracks.H.
Constructor & Destructor Documentation
ParticleTracks() [1/2]
template<class CloudType > ParticleTracks (const dictionary & dict, CloudType & owner, const word & modelName)
Definition at line 51 of file ParticleTracks.C.
ParticleTracks() [2/2]
template<class CloudType > ParticleTracks (const ParticleTracks< CloudType > & ppm)
Definition at line 68 of file ParticleTracks.C.
~ParticleTracks()
template<class CloudType > virtual ~ParticleTracks () virtual default
Member Function Documentation
write()
template<class CloudType > void write () protected virtual
Reimplemented from CloudFunctionObject< CloudType >.
Definition at line 30 of file ParticleTracks.C.
References PtrList< T >::clear(), DebugInFunction, and Foam::endl().
TypeName()
template<class CloudType > TypeName ("particleTracks")
clone()
template<class CloudType > virtual autoPtr< CloudFunctionObject< CloudType > > clone () const inline virtual
Reimplemented from CloudFunctionObject< CloudType >.
Definition at line 106 of file ParticleTracks.H.
trackInterval()
template<class CloudType > Foam::label trackInterval () const inline
Definition at line 27 of file ParticleTracksI.H.
maxSamples()
template<class CloudType > Foam::label maxSamples () const inline
Definition at line 34 of file ParticleTracksI.H.
resetOnWrite()
template<class CloudType > bool resetOnWrite () const inline
Definition at line 41 of file ParticleTracksI.H.
faceHitCounter()
template<class CloudType > const Foam::labelPairLookup & faceHitCounter () const inline
Definition at line 49 of file ParticleTracksI.H.
cloud()
template<class CloudType > const Foam::Cloud< typename CloudType::parcelType > & cloud () const inline
Definition at line 57 of file ParticleTracksI.H.
preEvolve()
template<class CloudType > void preEvolve (const typename parcelType::trackingData & td) virtual
Reimplemented from CloudFunctionObject< CloudType >.
Definition at line 85 of file ParticleTracks.C.
References Foam::name().
postFace()
template<class CloudType > void postFace (const parcelType & p, bool & keepParticle) virtual
Reimplemented from CloudFunctionObject< CloudType >.
Definition at line 101 of file ParticleTracks.C.
References Foam::abort(), GeometricField< Type, PatchField, GeoMesh >::clone(), Foam::FatalError, FatalErrorInFunction, nSamples(), Foam::output(), and p.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/CloudFunctionObjects/ParticleTracks/ParticleTracks.H
src/lagrangian/intermediate/submodels/CloudFunctionObjects/ParticleTracks/ParticleTracks.C
src/lagrangian/intermediate/submodels/CloudFunctionObjects/ParticleTracks/ParticleTracksI.H