OpenFOAM: UILList< LListBase, T >::const_reverse_iterator Class Reference
UILList< LListBase, T >::const_reverse_iterator Class Reference
#include <UILList.H>
Public Member Functions
const_reverse_iterator (const_base_iterator iter)
const_pointer get () const
const_reference operator* () const
const_pointer operator-> () const
const_reference operator() () const
const_reverse_iterator & operator++ ()
Detailed Description
template<class LListBase, class T>
class Foam::UILList< LListBase, T >::const_reverse_iterator
Definition at line 331 of file UILList.H.
Constructor & Destructor Documentation
const_reverse_iterator()
template<class LListBase , class T > const_reverse_iterator (const_base_iterator iter) inline
Definition at line 337 of file UILList.H.
Member Function Documentation
get()
template<class LListBase , class T > const_pointer get () const inline
Definition at line 343 of file UILList.H.
References T.
Referenced by UILList< LListBase, T >::const_reverse_iterator::operator*(), and UILList< LListBase, T >::const_reverse_iterator::operator->().
operator*()
template<class LListBase , class T > const_reference operator* () const inline
Definition at line 348 of file UILList.H.
References UILList< LListBase, T >::const_reverse_iterator::get().
Referenced by UILList< LListBase, T >::const_reverse_iterator::operator()().
operator->()
template<class LListBase , class T > const_pointer operator-> () const inline
Definition at line 353 of file UILList.H.
References UILList< LListBase, T >::const_reverse_iterator::get().
operator()()
template<class LListBase , class T > const_reference operator() () const inline
Definition at line 358 of file UILList.H.
References UILList< LListBase, T >::const_reverse_iterator::operator*().
operator++()
template<class LListBase , class T > const_reverse_iterator & operator++ () inline
Definition at line 363 of file UILList.H.
The documentation for this class was generated from the following file:
src/OpenFOAM/containers/LinkedLists/accessTypes/UILList/UILList.H