OpenFOAM: waveAlphaFvPatchScalarField Class Reference
waveAlphaFvPatchScalarField Class Reference
Example of the boundary condition specification:
#include <waveAlphaFvPatchScalarField.H>
Public Member Functions
TypeName ("waveAlpha")
waveAlphaFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
waveAlphaFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
waveAlphaFvPatchScalarField (const waveAlphaFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
waveAlphaFvPatchScalarField (const waveAlphaFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
waveAlphaFvPatchScalarField (const waveAlphaFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
Example of the boundary condition specification:
inlet
{
    type            waveAlpha;
    value           uniform (0 0 0);
}
Usage
Property Description Required Default value
type type: waveAlpha yes
waveDict Dictionary specifying wave variables no waveProperties
Note
The value is positive inwards
May not work correctly for transonic inlets
Strange behaviour with potentialFoam since the U equation is not solved
Source files
waveAlphaFvPatchScalarField.H
waveAlphaFvPatchScalarField.C
Definition at line 80 of file waveAlphaFvPatchScalarField.H.
Constructor & Destructor Documentation
waveAlphaFvPatchScalarField() [1/5]
waveAlphaFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 29 of file waveAlphaFvPatchScalarField.C.
waveAlphaFvPatchScalarField() [2/5]
waveAlphaFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 53 of file waveAlphaFvPatchScalarField.C.
waveAlphaFvPatchScalarField() [3/5]
waveAlphaFvPatchScalarField (const waveAlphaFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 40 of file waveAlphaFvPatchScalarField.C.
waveAlphaFvPatchScalarField() [4/5]
waveAlphaFvPatchScalarField (const waveAlphaFvPatchScalarField & ptf)
Definition at line 65 of file waveAlphaFvPatchScalarField.C.
waveAlphaFvPatchScalarField() [5/5]
waveAlphaFvPatchScalarField (const waveAlphaFvPatchScalarField & ptf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 75 of file waveAlphaFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("waveAlpha")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 131 of file waveAlphaFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 147 of file waveAlphaFvPatchScalarField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 88 of file waveAlphaFvPatchScalarField.C.
References waveModel::alpha(), waveModel::correct(), waveModel::lookupOrCreate(), mesh, Foam::operator==(), and fvPatchField< Type >::updateCoeffs().
write()
void write (Ostream & os) const virtual
Definition at line 115 of file waveAlphaFvPatchScalarField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntry(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/waveModels/derivedFvPatchFields/waveAlpha/waveAlphaFvPatchScalarField.H
src/waveModels/derivedFvPatchFields/waveAlpha/waveAlphaFvPatchScalarField.C