OpenFOAM: alphatJayatillekeWallFunctionFvPatchScalarField Class Reference
alphatJayatillekeWallFunctionFvPatchScalarField Class Reference
Turbulence models » Incompressible turbulence » Boundary conditions » Wall functions
This boundary condition provides a kinematic turbulent thermal conductivity for using wall functions, using the Jayatilleke 'P' function.
#include <alphatJayatillekeWallFunctionFvPatchScalarField.H>
Public Member Functions
TypeName ("alphatJayatillekeWallFunction")
alphatJayatillekeWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
alphatJayatillekeWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
alphatJayatillekeWallFunctionFvPatchScalarField (const alphatJayatillekeWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
alphatJayatillekeWallFunctionFvPatchScalarField (const alphatJayatillekeWallFunctionFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
alphatJayatillekeWallFunctionFvPatchScalarField (const alphatJayatillekeWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Protected Member Functions
virtual void checkType ()
tmp< scalarField > yPlus (const turbulenceModel &turbModel) const
scalar Psmooth (const scalar Prat) const
scalar yPlusTherm (const scalar P, const scalar Prat) const
Protected Attributes
scalar Prt_
scalar kappa_
scalar E_
Static Protected Attributes
static scalar tolerance_ = 0.01
static label maxIters_ = 10
Detailed Description
This boundary condition provides a kinematic turbulent thermal conductivity for using wall functions, using the Jayatilleke 'P' function.
Usage
Example of the boundary condition specification:
<patchName>
{
    // Mandatory entries
    type            alphatJayatillekeWallFunction;
    // Optional entries
    Prt             <scalar>;
    kappa           <scalar>;
    E               <scalar>;
    // Inherited entries
    ...
}
where the entries mean:
Property Description Type Reqd Deflt
type Type name: alphatJayatillekeWallFunction word yes -
Prt Turbulent Prandtl number scalar no 0.85
kappa von Karman constant scalar no 0.41
E Wall roughness parameter scalar no 9.8
The inherited entries are elaborated in:
fixedValueFvPatchFields.H
Note
The units of kinematic turbulent thermal conductivity are [m2/s].
Source files
alphatJayatillekeWallFunctionFvPatchScalarField.H
alphatJayatillekeWallFunctionFvPatchScalarField.C
Definition at line 117 of file alphatJayatillekeWallFunctionFvPatchScalarField.H.
Constructor & Destructor Documentation
alphatJayatillekeWallFunctionFvPatchScalarField() [1/5]
alphatJayatillekeWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 131 of file alphatJayatillekeWallFunctionFvPatchScalarField.C.
References alphatJayatillekeWallFunctionFvPatchScalarField::checkType().
alphatJayatillekeWallFunctionFvPatchScalarField() [2/5]
alphatJayatillekeWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 165 of file alphatJayatillekeWallFunctionFvPatchScalarField.C.
References alphatJayatillekeWallFunctionFvPatchScalarField::checkType().
alphatJayatillekeWallFunctionFvPatchScalarField() [3/5]
alphatJayatillekeWallFunctionFvPatchScalarField (const alphatJayatillekeWallFunctionFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 147 of file alphatJayatillekeWallFunctionFvPatchScalarField.C.
References alphatJayatillekeWallFunctionFvPatchScalarField::checkType().
alphatJayatillekeWallFunctionFvPatchScalarField() [4/5]
alphatJayatillekeWallFunctionFvPatchScalarField (const alphatJayatillekeWallFunctionFvPatchScalarField & wfpsf)
Definition at line 182 of file alphatJayatillekeWallFunctionFvPatchScalarField.C.
References alphatJayatillekeWallFunctionFvPatchScalarField::checkType().
alphatJayatillekeWallFunctionFvPatchScalarField() [5/5]
alphatJayatillekeWallFunctionFvPatchScalarField (const alphatJayatillekeWallFunctionFvPatchScalarField & wfpsf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 197 of file alphatJayatillekeWallFunctionFvPatchScalarField.C.
References alphatJayatillekeWallFunctionFvPatchScalarField::checkType().
Member Function Documentation
checkType()
void checkType () protected virtual
Definition at line 43 of file alphatJayatillekeWallFunctionFvPatchScalarField.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, and Foam::nl.
Referenced by alphatJayatillekeWallFunctionFvPatchScalarField::alphatJayatillekeWallFunctionFvPatchScalarField(), alphatJayatillekeWallFunctionFvPatchScalarField::alphatJayatillekeWallFunctionFvPatchScalarField(), alphatJayatillekeWallFunctionFvPatchScalarField::alphatJayatillekeWallFunctionFvPatchScalarField(), alphatJayatillekeWallFunctionFvPatchScalarField::alphatJayatillekeWallFunctionFvPatchScalarField(), and alphatJayatillekeWallFunctionFvPatchScalarField::alphatJayatillekeWallFunctionFvPatchScalarField().
yPlus()
tmp< scalarField > yPlus (const turbulenceModel & turbModel) const protected
Definition at line 57 of file alphatJayatillekeWallFunctionFvPatchScalarField.C.
References Foam::mag(), nut, fvPatchField< Type >::snGrad(), Foam::sqrt(), and y.
Psmooth()
scalar Psmooth (const scalar Prat) const protected
Definition at line 88 of file alphatJayatillekeWallFunctionFvPatchScalarField.C.
References Foam::exp(), and Foam::pow().
Referenced by alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs().
yPlusTherm()
scalar yPlusTherm (const scalar P, const scalar Prat) const protected
Definition at line 97 of file alphatJayatillekeWallFunctionFvPatchScalarField.C.
References alphatJayatillekeWallFunctionFvPatchScalarField::E_, f(), alphatJayatillekeWallFunctionFvPatchScalarField::kappa_, Foam::log(), Foam::mag(), alphatJayatillekeWallFunctionFvPatchScalarField::maxIters_, and alphatJayatillekeWallFunctionFvPatchScalarField::tolerance_.
Referenced by alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs().
TypeName()
TypeName ("alphatJayatillekeWallFunction")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 201 of file alphatJayatillekeWallFunctionFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 217 of file alphatJayatillekeWallFunctionFvPatchScalarField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 215 of file alphatJayatillekeWallFunctionFvPatchScalarField.C.
References Foam::dimless, alphatJayatillekeWallFunctionFvPatchScalarField::E_, forAll, IOobject::groupName(), alphatJayatillekeWallFunctionFvPatchScalarField::kappa_, Foam::log(), Foam::max(), nu, Pr(), turbulenceModel::propertiesName, alphatJayatillekeWallFunctionFvPatchScalarField::Prt_, alphatJayatillekeWallFunctionFvPatchScalarField::Psmooth(), transportProperties(), fvPatchField< Type >::updateCoeffs(), yPlus, and alphatJayatillekeWallFunctionFvPatchScalarField::yPlusTherm().
write()
void write (Ostream & os) const virtual
Definition at line 282 of file alphatJayatillekeWallFunctionFvPatchScalarField.C.
References alphatJayatillekeWallFunctionFvPatchScalarField::E_, alphatJayatillekeWallFunctionFvPatchScalarField::kappa_, os(), alphatJayatillekeWallFunctionFvPatchScalarField::Prt_, fvPatchField< Type >::write(), and fvPatchField< Type >::writeValueEntry().
Member Data Documentation
Prt_
scalar Prt_ protected
Definition at line 126 of file alphatJayatillekeWallFunctionFvPatchScalarField.H.
Referenced by alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs(), and alphatJayatillekeWallFunctionFvPatchScalarField::write().
kappa_
scalar kappa_ protected
Definition at line 129 of file alphatJayatillekeWallFunctionFvPatchScalarField.H.
Referenced by alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs(), alphatJayatillekeWallFunctionFvPatchScalarField::write(), and alphatJayatillekeWallFunctionFvPatchScalarField::yPlusTherm().
E_
scalar E_ protected
Definition at line 132 of file alphatJayatillekeWallFunctionFvPatchScalarField.H.
Referenced by alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs(), alphatJayatillekeWallFunctionFvPatchScalarField::write(), and alphatJayatillekeWallFunctionFvPatchScalarField::yPlusTherm().
tolerance_
scalar tolerance_ = 0.01 static protected
Definition at line 137 of file alphatJayatillekeWallFunctionFvPatchScalarField.H.
Referenced by alphatJayatillekeWallFunctionFvPatchScalarField::yPlusTherm().
maxIters_
label maxIters_ = 10 static protected
Definition at line 138 of file alphatJayatillekeWallFunctionFvPatchScalarField.H.
Referenced by alphatJayatillekeWallFunctionFvPatchScalarField::yPlusTherm().
The documentation for this class was generated from the following files:
src/TurbulenceModels/incompressible/turbulentTransportModels/derivedFvPatchFields/wallFunctions/alphatWallFunctions/alphatJayatillekeWallFunction/alphatJayatillekeWallFunctionFvPatchScalarField.H
src/TurbulenceModels/incompressible/turbulentTransportModels/derivedFvPatchFields/wallFunctions/alphatWallFunctions/alphatJayatillekeWallFunction/alphatJayatillekeWallFunctionFvPatchScalarField.C