OpenFOAM: wallDist Class Reference
wallDist Class Reference
Interface to run-time selectable methods to calculate the distance-to-wall and normal-to-wall fields.
#include <wallDist.H>
Public Member Functions
ClassName ("wallDist")
wallDist (const fvMesh &mesh, const labelHashSet &patchIDs, const word &patchTypeName="patch")
wallDist (const fvMesh &mesh, const word &defaultPatchDistMethod, const labelHashSet &patchIDs, const word &patchTypeName="patch")
wallDist (const fvMesh &mesh, const word &patchTypeName="wall")
virtual ~wallDist ()
const labelHashSet & patchIDs () const noexcept
const volScalarField & y () const noexcept
const volVectorField & n () const
virtual bool movePoints ()
virtual void updateMesh (const mapPolyMesh &)
Public Member Functions inherited from MeshObject< fvMesh, UpdateableMeshObject, wallDist >
MeshObject (const fvMesh &mesh)
MeshObject (const word &objName, const fvMesh &mesh)
virtual ~MeshObject ()=default
const fvMesh & mesh () const noexcept
virtual bool writeData (Ostream &os) const
Additional Inherited Members
Static Public Member Functions inherited from MeshObject< fvMesh, UpdateableMeshObject, wallDist >
static const wallDist & New (const fvMesh &mesh, Args &&... args)
static const wallDist & New (const word &objName, const fvMesh &mesh, Args &&... args)
static bool Delete (const word &objName, const fvMesh &mesh)
static bool Delete (const fvMesh &mesh)
Protected Attributes inherited from MeshObject< fvMesh, UpdateableMeshObject, wallDist >
const fvMesh & mesh_
Detailed Description
Interface to run-time selectable methods to calculate the distance-to-wall and normal-to-wall fields.
Example of the wallDist specification in fvSchemes:
    wallDist
    {
        method meshWave;
        // Optional entry enabling the calculation
        // of the normal-to-wall field
        nRequired false;
        // Optional entry delaying wall distance update to every n steps
        // Default is 1 (update every step)
        updateInterval 5;
    }
See also
Foam::patchDistMethod::meshWave Foam::patchDistMethod::Poisson Foam::patchDistMethod::advectionDiffusion
Source files
wallDist.H
wallDist.C
Definition at line 71 of file wallDist.H.
Constructor & Destructor Documentation
wallDist() [1/3]
wallDist (const fvMesh & mesh, const labelHashSet & patchIDs, const word & patchTypeName = "patch")
Definition at line 67 of file wallDist.C.
wallDist() [2/3]
wallDist (const fvMesh & mesh, const word & defaultPatchDistMethod, const labelHashSet & patchIDs, const word & patchTypeName = "patch")
Definition at line 78 of file wallDist.C.
References wallDist::movePoints().
wallDist() [3/3]
wallDist (const fvMesh & mesh, const word & patchTypeName = "wall")
Definition at line 133 of file wallDist.C.
~wallDist()
~wallDist () virtual
Definition at line 146 of file wallDist.C.
Member Function Documentation
ClassName()
ClassName ("wallDist")
patchIDs()
const labelHashSet & patchIDs () const inline noexcept
Definition at line 158 of file wallDist.H.
y()
const volScalarField & y () const inline noexcept
Definition at line 164 of file wallDist.H.
n()
const Foam::volVectorField & n () const
Definition at line 152 of file wallDist.C.
References Foam::endl(), Foam::isNull(), Foam::nl, and WarningInFunction.
movePoints()
bool movePoints () virtual
Definition at line 170 of file wallDist.C.
References DebugInfo, and Foam::endl().
Referenced by wallDist::wallDist().
updateMesh()
void updateMesh (const mapPolyMesh & mpm) virtual
Definition at line 201 of file wallDist.C.
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/wallDist/wallDist/wallDist.H
src/finiteVolume/fvMesh/wallDist/wallDist/wallDist.C