OpenFOAM: splitCell Class Reference
splitCell Class Reference
Description of cell after splitting. Contains cellLabel and pointers to cells it it split in. See directedRefinement.
#include <splitCell.H>
Public Member Functions
splitCell (const label celli, splitCell *parent)
~splitCell ()
label cellLabel () const
label & cellLabel ()
splitCell * parent () const
splitCell *& parent ()
splitCell * master () const
splitCell *& master ()
splitCell * slave () const
splitCell *& slave ()
bool isMaster () const
bool isUnrefined () const
splitCell * getOther () const
Detailed Description
Description of cell after splitting. Contains cellLabel and pointers to cells it it split in. See directedRefinement.
Source files
splitCell.H
splitCell.C
Definition at line 47 of file splitCell.H.
Constructor & Destructor Documentation
splitCell()
splitCell (const label celli, splitCell * parent)
Definition at line 26 of file splitCell.C.
~splitCell()
~splitCell ()
Definition at line 37 of file splitCell.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, and FatalErrorInFunction.
Member Function Documentation
cellLabel() [1/2]
label cellLabel () const inline
Definition at line 89 of file splitCell.H.
cellLabel() [2/2]
label & cellLabel () inline
Definition at line 94 of file splitCell.H.
parent() [1/2]
splitCell * parent () const inline
Definition at line 99 of file splitCell.H.
parent() [2/2]
splitCell *& parent () inline
Definition at line 104 of file splitCell.H.
master() [1/2]
splitCell * master () const inline
Definition at line 109 of file splitCell.H.
master() [2/2]
splitCell *& master () inline
Definition at line 114 of file splitCell.H.
slave() [1/2]
splitCell * slave () const inline
Definition at line 119 of file splitCell.H.
slave() [2/2]
splitCell *& slave () inline
Definition at line 124 of file splitCell.H.
isMaster()
bool isMaster () const
Definition at line 64 of file splitCell.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, and FatalErrorInFunction.
isUnrefined()
bool isUnrefined () const
Definition at line 94 of file splitCell.C.
getOther()
Foam::splitCell * getOther () const
Definition at line 100 of file splitCell.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, and FatalErrorInFunction.
The documentation for this class was generated from the following files:
src/dynamicMesh/meshCut/splitCell/splitCell.H
src/dynamicMesh/meshCut/splitCell/splitCell.C