OpenFOAM: coordSetWriter Class Reference
coordSetWriter Class Reference abstract
Base class for writing coordSet(s) and tracks with fields.
#include <coordSetWriter.H>
Public Member Functions
TypeName ("coordSetWriter")
declareRunTimeSelectionTable (autoPtr, coordSetWriter, word,(),())
declareRunTimeSelectionTable (autoPtr, coordSetWriter, wordDict,(const dictionary &writeOptions),(writeOptions))
coordSetWriter ()
coordSetWriter (const dictionary &options)
virtual ~coordSetWriter ()
virtual bool buffering () const
virtual bool buffering (const bool on)
virtual bool enabled () const
virtual bool needsUpdate () const
virtual bool wroteData () const
virtual bool expire ()
virtual void clear ()
virtual void setCoordinates (const coordSet *coords)
virtual void setCoordinates (const coordSet &coords)
virtual void setTracks (const UPtrList< coordSet > &tracks)
virtual void setTrackTimes (const UList< scalarField > &times)
label numPoints () const
label numTracks () const
bool hasCoords () const
bool empty () const
bool is_open () const noexcept
label nFields () const noexcept
label nFields (const label n) noexcept
bool useTracks () const noexcept
bool useTracks (const bool on) noexcept
bool useTimeDir () const noexcept
bool useTimeDir (const bool on) noexcept
bool verbose () const noexcept
bool verbose (bool on) noexcept
bool hasTime () const
const word & timeName () const
scalar timeValue () const
void setTime (const instant &inst)
void setTime (scalar timeValue)
void setTime (scalar timeValue, const word &timeName)
void unsetTime ()
virtual void beginTime (const Time &t)
virtual void beginTime (const instant &inst)
virtual void endTime ()
virtual fileName path () const =0
virtual void open (const fileName &outputPath)
TBD: virtual fileName write() = 0;.
virtual void open (const coordSet &coords, const fileName &outputPath)
virtual void open (const UPtrList< coordSet > &tracks, const fileName &outputPath)
virtual void close (bool force=false)
virtual InfoProxy< coordSetWriter > info () const
virtual fileName write (const word &fieldName, const Field< label > &field)=0
Write field of label (point data)
virtual fileName write (const word &fieldName, const List< Field< label > > &fieldValues)=0
Write track fields of label (point data)
virtual fileName write (const word &fieldName, const Field< scalar > &field)=0
Write field of scalar (point data)
virtual fileName write (const word &fieldName, const List< Field< scalar > > &fieldValues)=0
Write track fields of scalar (point data)
virtual fileName write (const word &fieldName, const Field< vector > &field)=0
Write field of vector (point data)
virtual fileName write (const word &fieldName, const List< Field< vector > > &fieldValues)=0
Write track fields of vector (point data)
virtual fileName write (const word &fieldName, const Field< sphericalTensor > &field)=0
Write field of sphericalTensor (point data)
virtual fileName write (const word &fieldName, const List< Field< sphericalTensor > > &fieldValues)=0
Write track fields of sphericalTensor (point data)
virtual fileName write (const word &fieldName, const Field< symmTensor > &field)=0
Write field of symmTensor (point data)
virtual fileName write (const word &fieldName, const List< Field< symmTensor > > &fieldValues)=0
Write track fields of symmTensor (point data)
virtual fileName write (const word &fieldName, const Field< tensor > &field)=0
Write field of tensor (point data)
virtual fileName write (const word &fieldName, const List< Field< tensor > > &fieldValues)=0
Write track fields of tensor (point data)
template<class Type >
Foam::UPtrList< const Foam::Field< Type > > repackageFields (const Field< Type > &field)
template<class Type >
Foam::UPtrList< const Foam::Field< Type > > repackageFields (const UList< Field< Type > > &fieldValues)
Static Public Member Functions
static dictionary formatOptions (const dictionary &dict, const word &formatName, const word &entryName="formatOptions")
static dictionary formatOptions (const dictionary &dict, const dictionary &setDict, const word &formatName, const word &entryName="formatOptions")
static bool supportedType (const word &writeType)
static autoPtr< coordSetWriter > New (const word &writeFormat)
static autoPtr< coordSetWriter > New (const word &writeFormat, const dictionary &writeOptions)
static word suffix (const word &fldName, const word &fileExt=word::null)
static word suffix (const wordList &fieldNames, const word &fileExt=word::null)
Protected Member Functions
void appendField (const word &fieldName, const Field< label > &vals)
void appendField (const word &fieldName, const Field< scalar > &vals)
void appendField (const word &fieldName, const Field< vector > &vals)
void appendField (const word &fieldName, const Field< sphericalTensor > &vals)
void appendField (const word &fieldName, const Field< symmTensor > &vals)
void appendField (const word &fieldName, const Field< tensor > &vals)
void clearBuffers ()
label nDataColumns () const
virtual bool writeBuffered ()
void writeBufferContents (Ostream &os, const coordSet &coords, const char *sep) const
void getBufferLine (DynamicList< scalar > &buf, const coordSet &coords, const label pointi) const
fileName getExpectedPath (const word &fileExt=word::null) const
fileName getFieldPrefixedPath (const word &fieldName, const word &fileExt=word::null) const
void checkOpen () const
virtual bool merge () const
template<class Type >
fileName writeTemplate (const word &fieldName, const Field< Type > &values)
template<class Type >
fileName writeTemplate (const word &fieldName, const List< Field< Type > > &fieldValues)
coordSetWriter (const coordSetWriter &)=delete
void operator= (const coordSetWriter &)=delete
Static Protected Member Functions
static void writeLine (Ostream &, const UList< word > &, const char *sep)
static void writeLine (Ostream &, const UList< scalar > &, const char *sep)
template<class Type >
static UPtrList< const Field< Type > > repackageFields (const Field< Type > &field)
template<class Type >
static UPtrList< const Field< Type > > repackageFields (const UList< Field< Type > > &fieldValues)
template<class Type >
static void writeTable (Ostream &os, const coordSet &coords, const UList< Type > &values, const char *sep)
Protected Attributes
UPtrList< const coordSet > coords_
List< scalarField > trackTimes_
bool upToDate_
bool wroteGeom_
bool buffering_
bool useTracks_
bool useTimeDir_
bool verbose_
label nFields_
instant currTime_
fileName outputPath_
DynamicList< word > labelNames_
PtrDynList< Field< label > > labelFields_
DynamicList< word > scalarNames_
PtrDynList< Field< scalar > > scalarFields_
DynamicList< word > vectorNames_
PtrDynList< Field< vector > > vectorFields_
DynamicList< word > sphericalTensorNames_
PtrDynList< Field< sphericalTensor > > sphericalTensorFields_
DynamicList< word > symmTensorNames_
PtrDynList< Field< symmTensor > > symmTensorFields_
DynamicList< word > tensorNames_
PtrDynList< Field< tensor > > tensorFields_
Friends
Ostream & operator<< (Ostream &os, const InfoProxy< coordSetWriter > &iproxy)
Detailed Description
Base class for writing coordSet(s) and tracks with fields.
Example:
    coordSet coords(...);
    // Construct writer of xmgr type
    autoPtr<coordSetWriter> writer(coordSetWriter::New("vtk"));
    writer.open(coords, path/name);
    writer.write("density", rho);
    writer.write("velocity", U);
Source files
coordSetWriter.H
coordSetWriterI.H
coordSetWriter.C
coordSetWriterBuffers.C
coordSetWriterNew.C
Definition at line 81 of file coordSetWriter.H.
Constructor & Destructor Documentation
coordSetWriter() [1/3]
coordSetWriter (const coordSetWriter &) protected delete
coordSetWriter() [2/3]
coordSetWriter ()
Definition at line 100 of file coordSetWriter.C.
coordSetWriter() [3/3]
coordSetWriter (const dictionary & options) explicit
Definition at line 117 of file coordSetWriter.C.
References dictionary::readIfPresent(), and coordSetWriter::verbose_.
~coordSetWriter()
~coordSetWriter () virtual
Definition at line 127 of file coordSetWriter.C.
Member Function Documentation
appendField() [1/6]
void appendField (const word & fieldName, const Field< label > & vals) inline protected
Definition at line 142 of file coordSetWriter.H.
appendField() [2/6]
void appendField (const word & fieldName, const Field< scalar > & vals) inline protected
Definition at line 143 of file coordSetWriter.H.
appendField() [3/6]
void appendField (const word & fieldName, const Field< vector > & vals) inline protected
Definition at line 144 of file coordSetWriter.H.
appendField() [4/6]
void appendField (const word & fieldName, const Field< sphericalTensor > & vals) inline protected
Definition at line 145 of file coordSetWriter.H.
appendField() [5/6]
void appendField (const word & fieldName, const Field< symmTensor > & vals) inline protected
Definition at line 146 of file coordSetWriter.H.
appendField() [6/6]
void appendField (const word & fieldName, const Field< tensor > & vals) inline protected
Definition at line 147 of file coordSetWriter.H.
writeLine() [1/2]
void writeLine (Ostream & os, const UList< word > & values, const char * sep) static protected
Definition at line 25 of file coordSetWriterBuffers.C.
References forAll, Foam::nl, and os().
writeLine() [2/2]
void writeLine (Ostream & os, const UList< scalar > & values, const char * sep) static protected
Definition at line 44 of file coordSetWriterBuffers.C.
References forAll, Foam::nl, and os().
clearBuffers()
void clearBuffers () protected
Definition at line 63 of file coordSetWriterBuffers.C.
References doLocalCode.
nDataColumns()
Foam::label nDataColumns () const protected
Definition at line 82 of file coordSetWriterBuffers.C.
References doLocalCode.
writeBuffered()
bool writeBuffered () protected virtual
Reimplemented in csvWriter, gnuplotWriter, and rawWriter.
Definition at line 149 of file coordSetWriterBuffers.C.
writeBufferContents()
void writeBufferContents (Ostream & os, const coordSet & coords, const char * sep) const protected
Definition at line 155 of file coordSetWriterBuffers.C.
References os(), and UPtrList< T >::size().
getBufferLine()
void getBufferLine (DynamicList< scalar > & buf, const coordSet & coords, const label pointi) const protected
Definition at line 102 of file coordSetWriterBuffers.C.
References PtrList< T >::append(), PtrList< T >::clear(), doLocalCode, and p.
getExpectedPath()
Foam::fileName getExpectedPath (const word & fileExt = word::null) const protected
Definition at line 362 of file coordSetWriter.C.
References fileName::ext(), fileName::path(), and timeName.
getFieldPrefixedPath()
Foam::fileName getFieldPrefixedPath (const word & fieldName, const word & fileExt = word::null) const protected
Definition at line 388 of file coordSetWriter.C.
References fileName::ext(), fileName::path(), and timeName.
Referenced by csvWriter::writeTemplate(), gnuplotWriter::writeTemplate(), rawWriter::writeTemplate(), and xmgraceWriter::writeTemplate().
checkOpen()
void checkOpen () const protected
Definition at line 420 of file coordSetWriter.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::nl, and Foam::type().
merge()
bool merge () const protected virtual
Definition at line 431 of file coordSetWriter.C.
repackageFields() [1/4]
template<class Type > static UPtrList< const Field< Type > > repackageFields (const Field< Type > & field) static protected
repackageFields() [2/4]
template<class Type > static UPtrList< const Field< Type > > repackageFields (const UList< Field< Type > > & fieldValues) static protected
writeTable()
template<class Type > void writeTable (Ostream & os, const coordSet & coords, const UList< Type > & values, const char * sep) static protected
Definition at line 49 of file coordSetWriterTemplates.C.
References Foam::component(), forAll, Foam::nl, os(), and p.
Referenced by csvWriter::writeTemplate(), gnuplotWriter::writeTemplate(), rawWriter::writeTemplate(), and xmgraceWriter::writeTemplate().
writeTemplate() [1/2]
template<class Type > fileName writeTemplate (const word & fieldName, const Field< Type > & values) inline protected
if (!wroteGeom_) { return this->write(); }
Parameters
fieldName Name of field
values Local field values to write
Definition at line 241 of file coordSetWriter.H.
References fileName::null.
writeTemplate() [2/2]
template<class Type > fileName writeTemplate (const word & fieldName, const List< Field< Type > > & fieldValues) inline protected
Definition at line 256 of file coordSetWriter.H.
References fileName::null.
operator=()
void operator= (const coordSetWriter &) protected delete
TypeName()
TypeName ("coordSetWriter")
declareRunTimeSelectionTable() [1/2]
declareRunTimeSelectionTable (autoPtr , coordSetWriter , word , () , ())
declareRunTimeSelectionTable() [2/2]
declareRunTimeSelectionTable (autoPtr , coordSetWriter , wordDict , (const dictionary &writeOptions) , (writeOptions))
formatOptions() [1/2]
Foam::dictionary formatOptions (const dictionary & dict, const word & formatName, const word & entryName = "formatOptions") static
Definition at line 75 of file coordSetWriter.C.
References dict, and Foam::fileFormats::getFormatOptions().
Referenced by ParticleZoneInfo< CloudType >::ParticleZoneInfo().
formatOptions() [2/2]
Foam::dictionary formatOptions (const dictionary & dict, const dictionary & setDict, const word & formatName, const word & entryName = "formatOptions") static
Definition at line 86 of file coordSetWriter.C.
References dict, and Foam::fileFormats::getFormatOptions().
supportedType()
bool supportedType (const word & writeType) static
Definition at line 26 of file coordSetWriterNew.C.
New() [1/2]
Foam::autoPtr< Foam::coordSetWriter > New (const word & writeFormat) static
Definition at line 36 of file coordSetWriterNew.C.
References Foam::exit(), Foam::FatalError, and FatalErrorInLookup.
Referenced by ParticleZoneInfo< CloudType >::ParticleZoneInfo(), particleDistribution::read(), regionSizeDistribution::read(), and streamLineBase::read().
New() [2/2]
Foam::autoPtr< Foam::coordSetWriter > New (const word & writeFormat, const dictionary & writeOptions) static
Definition at line 57 of file coordSetWriterNew.C.
References Foam::exit(), Foam::FatalError, and FatalErrorInLookup.
suffix() [1/2]
Foam::word suffix (const word & fldName, const word & fileExt = word::null) static
Definition at line 38 of file coordSetWriter.C.
References UPtrList< T >::empty(), and word::ext().
suffix() [2/2]
Foam::word suffix (const wordList & fieldNames, const word & fileExt = word::null) static
Definition at line 55 of file coordSetWriter.C.
References UPtrList< T >::empty(), and word::ext().
buffering() [1/2]
bool buffering () const virtual
Reimplemented in nullWriter.
Definition at line 177 of file coordSetWriterBuffers.C.
buffering() [2/2]
bool buffering (const bool on) virtual
Reimplemented in csvWriter, gnuplotWriter, rawWriter, and xmgraceWriter.
Definition at line 184 of file coordSetWriterBuffers.C.
enabled()
virtual bool enabled () const inline virtual
Reimplemented in nullWriter.
Definition at line 380 of file coordSetWriter.H.
needsUpdate()
bool needsUpdate () const virtual
Reimplemented in nullWriter.
Definition at line 323 of file coordSetWriter.C.
wroteData()
bool wroteData () const virtual
Reimplemented in nullWriter.
Definition at line 329 of file coordSetWriter.C.
expire()
bool expire () virtual
Definition at line 335 of file coordSetWriter.C.
References PtrList< T >::clear().
clear()
void clear () virtual
Definition at line 239 of file coordSetWriter.C.
setCoordinates() [1/2]
void setCoordinates (const coordSet * coords) virtual
Reimplemented in nullWriter.
Definition at line 249 of file coordSetWriter.C.
setCoordinates() [2/2]
void setCoordinates (const coordSet & coords) virtual
Reimplemented in nullWriter.
Definition at line 267 of file coordSetWriter.C.
setTracks()
void setTracks (const UPtrList< coordSet > & tracks) virtual
Reimplemented in nullWriter.
Definition at line 273 of file coordSetWriter.C.
References PtrList< T >::clear(), forAll, UPtrList< T >::get(), PtrList< T >::set(), and UPtrList< T >::size().
setTrackTimes()
void setTrackTimes (const UList< scalarField > & times) virtual
Definition at line 290 of file coordSetWriter.C.
References PtrList< T >::clear(), and UPtrList< T >::size().
numPoints()
Foam::label numPoints () const
Definition at line 303 of file coordSetWriter.C.
References forAll, UPtrList< T >::get(), and UPtrList< T >::size().
numTracks()
Foam::label numTracks () const
Definition at line 317 of file coordSetWriter.C.
References UPtrList< T >::size().
hasCoords()
bool hasCoords () const
Definition at line 351 of file coordSetWriter.C.
References UPtrList< T >::empty().
empty()
bool empty () const
Definition at line 357 of file coordSetWriter.C.
References UPtrList< T >::empty().
is_open()
bool is_open () const inline noexcept
Definition at line 23 of file coordSetWriterI.H.
References coordSetWriter::outputPath_.
nFields() [1/2]
Foam::label nFields () const inline noexcept
Definition at line 29 of file coordSetWriterI.H.
nFields() [2/2]
Foam::label nFields (const label n) inline noexcept
Definition at line 35 of file coordSetWriterI.H.
References n.
useTracks() [1/2]
bool useTracks () const inline noexcept
Definition at line 43 of file coordSetWriterI.H.
useTracks() [2/2]
bool useTracks (const bool on) inline noexcept
Definition at line 49 of file coordSetWriterI.H.
useTimeDir() [1/2]
bool useTimeDir () const inline noexcept
Definition at line 57 of file coordSetWriterI.H.
useTimeDir() [2/2]
bool useTimeDir (const bool on) inline noexcept
Definition at line 63 of file coordSetWriterI.H.
verbose() [1/2]
bool verbose () const inline noexcept
Definition at line 71 of file coordSetWriterI.H.
verbose() [2/2]
bool verbose (bool on) inline noexcept
Definition at line 77 of file coordSetWriterI.H.
hasTime()
bool hasTime () const inline
Definition at line 85 of file coordSetWriterI.H.
References UPtrList< T >::size().
timeName()
const Foam::word & timeName () const inline
Definition at line 91 of file coordSetWriterI.H.
timeValue()
Foam::scalar timeValue () const inline
Definition at line 97 of file coordSetWriterI.H.
References UPtrList< T >::empty().
setTime() [1/3]
void setTime (const instant & inst)
Definition at line 135 of file coordSetWriter.C.
setTime() [2/3]
void setTime (scalar timeValue)
Definition at line 141 of file coordSetWriter.C.
setTime() [3/3]
void setTime (scalar timeValue, const word & timeName)
Definition at line 147 of file coordSetWriter.C.
References timeName.
unsetTime()
void unsetTime ()
Definition at line 154 of file coordSetWriter.C.
References PtrList< T >::clear().
beginTime() [1/2]
void beginTime (const Time & t) virtual
Reimplemented in gltfWriter, vtkWriter, and xmgraceWriter.
Definition at line 161 of file coordSetWriter.C.
References setTime(), Time::timeName(), and dimensioned< Type >::value().
Referenced by gltfWriter::beginTime(), vtkWriter::beginTime(), xmgraceWriter::beginTime(), gltfWriter::beginTime(), vtkWriter::beginTime(), and xmgraceWriter::beginTime().
beginTime() [2/2]
void beginTime (const instant & inst) virtual
Reimplemented in gltfWriter, vtkWriter, and xmgraceWriter.
Definition at line 167 of file coordSetWriter.C.
References setTime().
endTime()
void endTime () virtual
Reimplemented in gltfWriter, vtkWriter, and xmgraceWriter.
Definition at line 173 of file coordSetWriter.C.
Referenced by gltfWriter::endTime(), vtkWriter::endTime(), and xmgraceWriter::endTime().
path()
virtual fileName path () const pure virtual
Implemented in csvWriter, ensightWriter, gltfWriter, gnuplotWriter, nastranWriter, nullWriter, rawWriter, vtkWriter, and xmgraceWriter.
open() [1/3]
void open (const fileName & outputPath) virtual
TBD: virtual fileName write() = 0;.
Reimplemented in nullWriter.
Definition at line 188 of file coordSetWriter.C.
Referenced by csvWriter::csvWriter(), csvWriter::csvWriter(), ensightWriter::ensightWriter(), ensightWriter::ensightWriter(), gltfWriter::gltfWriter(), gltfWriter::gltfWriter(), gnuplotWriter::gnuplotWriter(), gnuplotWriter::gnuplotWriter(), nastranWriter::nastranWriter(), nastranWriter::nastranWriter(), rawWriter::rawWriter(), rawWriter::rawWriter(), vtkWriter::vtkWriter(), vtkWriter::vtkWriter(), xmgraceWriter::xmgraceWriter(), and xmgraceWriter::xmgraceWriter().
open() [2/3]
void open (const coordSet & coords, const fileName & outputPath) virtual
Definition at line 195 of file coordSetWriter.C.
open() [3/3]
void open (const UPtrList< coordSet > & tracks, const fileName & outputPath) virtual
Definition at line 207 of file coordSetWriter.C.
close()
void close (bool force = false) virtual
Reimplemented in ensightWriter, gltfWriter, vtkWriter, and xmgraceWriter.
Definition at line 219 of file coordSetWriter.C.
References Foam::Info, and Foam::nl.
Referenced by ensightWriter::close(), gltfWriter::close(), vtkWriter::close(), and xmgraceWriter::close().
info()
virtual InfoProxy< coordSetWriter > info () const inline virtual
Definition at line 538 of file coordSetWriter.H.
write() [1/12]
virtual fileName write (const word & fieldName, const Field< label > & field) pure virtual
Write field of label (point data)
Parameters
fieldName Name of field
field Field values
write() [2/12]
virtual fileName write (const word & fieldName, const List< Field< label > > & fieldValues) pure virtual
Write track fields of label (point data)
Parameters
fieldName Name of field
fieldValues Per-track values
write() [3/12]
virtual fileName write (const word & fieldName, const Field< scalar > & field) pure virtual
Write field of scalar (point data)
Parameters
fieldName Name of field
field Field values
write() [4/12]
virtual fileName write (const word & fieldName, const List< Field< scalar > > & fieldValues) pure virtual
Write track fields of scalar (point data)
Parameters
fieldName Name of field
fieldValues Per-track values
write() [5/12]
virtual fileName write (const word & fieldName, const Field< vector > & field) pure virtual
Write field of vector (point data)
Parameters
fieldName Name of field
field Field values
write() [6/12]
virtual fileName write (const word & fieldName, const List< Field< vector > > & fieldValues) pure virtual
Write track fields of vector (point data)
Parameters
fieldName Name of field
fieldValues Per-track values
write() [7/12]
virtual fileName write (const word & fieldName, const Field< sphericalTensor > & field) pure virtual
Write field of sphericalTensor (point data)
Parameters
fieldName Name of field
field Field values
write() [8/12]
virtual fileName write (const word & fieldName, const List< Field< sphericalTensor > > & fieldValues) pure virtual
Write track fields of sphericalTensor (point data)
Parameters
fieldName Name of field
fieldValues Per-track values
write() [9/12]
virtual fileName write (const word & fieldName, const Field< symmTensor > & field) pure virtual
Write field of symmTensor (point data)
Parameters
fieldName Name of field
field Field values
write() [10/12]
virtual fileName write (const word & fieldName, const List< Field< symmTensor > > & fieldValues) pure virtual
Write track fields of symmTensor (point data)
Parameters
fieldName Name of field
fieldValues Per-track values
write() [11/12]
virtual fileName write (const word & fieldName, const Field< tensor > & field) pure virtual
Write field of tensor (point data)
Parameters
fieldName Name of field
field Field values
write() [12/12]
virtual fileName write (const word & fieldName, const List< Field< tensor > > & fieldValues) pure virtual
Write track fields of tensor (point data)
Parameters
fieldName Name of field
fieldValues Per-track values
repackageFields() [3/4]
template<class Type > Foam::UPtrList< const Foam::Field< Type > > repackageFields (const Field< Type > & field)
Definition at line 25 of file coordSetWriterTemplates.C.
References field(), and PtrList< T >::set().
repackageFields() [4/4]
template<class Type > Foam::UPtrList< const Foam::Field< Type > > repackageFields (const UList< Field< Type > > & fieldValues)
Definition at line 36 of file coordSetWriterTemplates.C.
References forAll, and PtrList< T >::set().
Friends And Related Symbol Documentation
operator<<
Ostream & operator<< (Ostream & os, const InfoProxy< coordSetWriter > & iproxy) friend
Member Data Documentation
coords_
UPtrList<const coordSet> coords_ protected
Definition at line 88 of file coordSetWriter.H.
Referenced by csvWriter::writeTemplate(), gnuplotWriter::writeTemplate(), rawWriter::writeTemplate(), and xmgraceWriter::writeTemplate().
trackTimes_
List<scalarField> trackTimes_ protected
Definition at line 91 of file coordSetWriter.H.
upToDate_
bool upToDate_ mutable protected
Definition at line 94 of file coordSetWriter.H.
wroteGeom_
bool wroteGeom_ mutable protected
Definition at line 97 of file coordSetWriter.H.
Referenced by csvWriter::writeTemplate(), gnuplotWriter::writeTemplate(), rawWriter::writeTemplate(), and xmgraceWriter::writeTemplate().
buffering_
bool buffering_ mutable protected
//- Writing in parallel (via master) bool parallel_;
Definition at line 103 of file coordSetWriter.H.
Referenced by csvWriter::csvWriter(), csvWriter::csvWriter(), gnuplotWriter::gnuplotWriter(), gnuplotWriter::gnuplotWriter(), rawWriter::rawWriter(), rawWriter::rawWriter(), xmgraceWriter::xmgraceWriter(), and xmgraceWriter::xmgraceWriter().
useTracks_
bool useTracks_ protected
Definition at line 106 of file coordSetWriter.H.
useTimeDir_
bool useTimeDir_ protected
Definition at line 109 of file coordSetWriter.H.
verbose_
bool verbose_ protected
Definition at line 112 of file coordSetWriter.H.
Referenced by coordSetWriter::coordSetWriter(), csvWriter::writeTemplate(), gnuplotWriter::writeTemplate(), rawWriter::writeTemplate(), and xmgraceWriter::writeTemplate().
nFields_
label nFields_ protected
Definition at line 115 of file coordSetWriter.H.
currTime_
instant currTime_ protected
Definition at line 118 of file coordSetWriter.H.
outputPath_
fileName outputPath_ protected
Definition at line 121 of file coordSetWriter.H.
Referenced by coordSetWriter::is_open().
labelNames_
DynamicList<word> labelNames_ protected
Definition at line 142 of file coordSetWriter.H.
labelFields_
PtrDynList<Field< label > > labelFields_ protected
Definition at line 142 of file coordSetWriter.H.
scalarNames_
DynamicList<word> scalarNames_ protected
Definition at line 143 of file coordSetWriter.H.
scalarFields_
PtrDynList<Field< scalar > > scalarFields_ protected
Definition at line 143 of file coordSetWriter.H.
vectorNames_
DynamicList<word> vectorNames_ protected
Definition at line 144 of file coordSetWriter.H.
vectorFields_
PtrDynList<Field< vector > > vectorFields_ protected
Definition at line 144 of file coordSetWriter.H.
sphericalTensorNames_
DynamicList<word> sphericalTensorNames_ protected
Definition at line 145 of file coordSetWriter.H.
sphericalTensorFields_
PtrDynList<Field< sphericalTensor > > sphericalTensorFields_ protected
Definition at line 145 of file coordSetWriter.H.
symmTensorNames_
DynamicList<word> symmTensorNames_ protected
Definition at line 146 of file coordSetWriter.H.
symmTensorFields_
PtrDynList<Field< symmTensor > > symmTensorFields_ protected
Definition at line 146 of file coordSetWriter.H.
tensorNames_
DynamicList<word> tensorNames_ protected
Definition at line 147 of file coordSetWriter.H.
tensorFields_
PtrDynList<Field< tensor > > tensorFields_ protected
Definition at line 147 of file coordSetWriter.H.
The documentation for this class was generated from the following files:
src/meshTools/coordSet/writers/common/coordSetWriter.H
src/meshTools/coordSet/writers/common/coordSetWriter.C
src/meshTools/coordSet/writers/common/coordSetWriterBuffers.C
src/meshTools/coordSet/writers/common/coordSetWriterI.H
src/meshTools/coordSet/writers/common/coordSetWriterNew.C
src/meshTools/coordSet/writers/common/coordSetWriterTemplates.C