OpenFOAM: convectionScheme< Type > Class Template Reference
convectionScheme< Type > Class Template Reference abstract
Abstract base class for finite area calculus convection schemes.
#include <faConvectionScheme.H>
Public Member Functions
declareRunTimeSelectionTable (tmp, convectionScheme, Istream,(const faMesh &mesh, const edgeScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
convectionScheme (const faMesh &mesh, const edgeScalarField &faceFlux)
virtual ~convectionScheme ()
const faMesh & mesh () const
virtual tmp< GeometricField< Type, faePatchField, edgeMesh > > flux (const edgeScalarField &, const GeometricField< Type, faPatchField, areaMesh > &) const =0
virtual tmp< faMatrix< Type > > famDiv (const edgeScalarField &, const GeometricField< Type, faPatchField, areaMesh > &) const =0
virtual tmp< GeometricField< Type, faPatchField, areaMesh > > facDiv (const edgeScalarField &, const GeometricField< Type, faPatchField, areaMesh > &) const =0
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Static Public Member Functions
static tmp< convectionScheme< Type > > New (const faMesh &mesh, const edgeScalarField &faceFlux, Istream &schemeData)
Detailed Description
template<class Type>
class Foam::fa::convectionScheme< Type >
Abstract base class for finite area calculus convection schemes.
Source files
faConvectionScheme.H
faConvectionScheme.C
Definition at line 61 of file faConvectionScheme.H.
Constructor & Destructor Documentation
convectionScheme()
template<class Type > convectionScheme (const faMesh & mesh, const edgeScalarField & faceFlux) inline
Definition at line 100 of file faConvectionScheme.H.
~convectionScheme()
template<class Type > ~convectionScheme () virtual
Definition at line 74 of file faConvectionScheme.C.
Member Function Documentation
declareRunTimeSelectionTable()
template<class Type > declareRunTimeSelectionTable (tmp , convectionScheme< Type > , Istream , (const faMesh &mesh, const edgeScalarField &faceFlux, Istream &schemeData) , (mesh, faceFlux, schemeData))
New()
template<class Type > Foam::tmp< Foam::fa::convectionScheme< Type > > New (const faMesh & mesh, const edgeScalarField & faceFlux, Istream & schemeData) static
Definition at line 29 of file faConvectionScheme.C.
References Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, FatalIOErrorInLookup, InfoInFunction, mesh, and Foam::nl.
Referenced by Foam::fam::div(), and Foam::fam::ndiv().
mesh()
template<class Type > const faMesh & mesh () const inline
Definition at line 128 of file faConvectionScheme.H.
flux()
template<class Type > virtual tmp< GeometricField< Type, faePatchField, edgeMesh > > flux (const edgeScalarField & , const GeometricField< Type, faPatchField, areaMesh > &) const pure virtual
Implemented in gaussConvectionScheme< Type >.
famDiv()
template<class Type > virtual tmp< faMatrix< Type > > famDiv (const edgeScalarField & , const GeometricField< Type, faPatchField, areaMesh > &) const pure virtual
Implemented in gaussConvectionScheme< Type >.
Referenced by Foam::fam::div().
facDiv()
template<class Type > virtual tmp< GeometricField< Type, faPatchField, areaMesh > > facDiv (const edgeScalarField & , const GeometricField< Type, faPatchField, areaMesh > &) const pure virtual
Implemented in gaussConvectionScheme< Type >.
Referenced by Foam::fac::div(), Foam::fam::div(), and Foam::fac::ndiv().
The documentation for this class was generated from the following files:
src/finiteArea/finiteArea/convectionSchemes/faConvectionScheme/faConvectionScheme.H
src/finiteArea/finiteArea/convectionSchemes/faConvectionScheme/faConvectionScheme.C