OpenFOAM: sensitivity Class Reference
sensitivity Class Reference abstract
Abstract base class for adjoint sensitivities.
#include <sensitivity.H>
Public Member Functions
TypeName ("sensitivity")
sensitivity (const fvMesh &mesh, const dictionary &dict)
virtual ~sensitivity ()=default
const dictionary & dict () const
virtual bool readDict (const dictionary &dict)
virtual void computeDerivativesSize ()
virtual const scalarField & calculateSensitivities ()=0
virtual void write (const word &baseName=word::null)
Protected Attributes
const fvMesh & mesh_
dictionary dict_
autoPtr< volScalarField > fieldSensPtr_
Detailed Description
Abstract base class for adjoint sensitivities.
Source files
sensitivity.H
sensitivity.C
Definition at line 59 of file sensitivity.H.
Constructor & Destructor Documentation
sensitivity()
sensitivity (const fvMesh & mesh, const dictionary & dict)
Definition at line 36 of file sensitivity.C.
~sensitivity()
virtual ~sensitivity () virtual default
Member Function Documentation
TypeName()
TypeName ("sensitivity")
dict()
const Foam::dictionary & dict () const
Definition at line 50 of file sensitivity.C.
Referenced by sensitivitySurface::computeRadius(), adjointSensitivity::New(), sensitivitySurface::read(), sensitivitySurfacePoints::read(), SIBase::read(), FIBase::readDict(), sensitivityMultiple::readDict(), sensitivitySurface::readDict(), sensitivitySurfacePoints::readDict(), SIBase::readDict(), sensitivityMultiple::sensitivityMultiple(), sensitivitySurface::setSuffixName(), sensitivitySurfacePoints::setSuffixName(), and sensitivitySurface::smoothSensitivities().
readDict()
bool readDict (const dictionary & dict) virtual
Reimplemented in FIBase, sensitivityMultiple, sensitivitySurface, sensitivitySurfacePoints, and SIBase.
Definition at line 56 of file sensitivity.C.
References dict.
Referenced by FIBase::readDict(), sensitivityMultiple::readDict(), sensitivitySurface::readDict(), sensitivitySurfacePoints::readDict(), and SIBase::readDict().
computeDerivativesSize()
void computeDerivativesSize () virtual
Reimplemented in sensitivitySurface.
Definition at line 64 of file sensitivity.C.
calculateSensitivities()
virtual const scalarField & calculateSensitivities () pure virtual
Implemented in adjointSensitivity, and sensitivityMultiple.
write()
void write (const word & baseName = word::null) virtual
Reimplemented in adjointSensitivity, sensitivityBezier, sensitivityBezierFI, sensitivityMultiple, sensitivitySurface, sensitivitySurfacePoints, sensitivityVolBSplines, sensitivityVolBSplinesFI, shapeSensitivities, and SIBase.
Definition at line 70 of file sensitivity.C.
Referenced by adjointSensitivity::write().
Member Data Documentation
mesh_
const fvMesh& mesh_ protected
Definition at line 65 of file sensitivity.H.
Referenced by shapeSensitivities::accumulateBCSensitivityIntegrand(), shapeSensitivities::accumulateDirectSensitivityIntegrand(), FIBase::accumulateIntegrand(), sensitivitySurface::accumulateIntegrand(), sensitivitySurfacePoints::accumulateIntegrand(), sensitivitySurface::addGeometricSens(), adjointSensitivity::adjointMeshMovementSource(), sensitivityBezierFI::assembleSensitivities(), sensitivitySurface::assembleSensitivities(), sensitivitySurfacePoints::assembleSensitivities(), sensitivityVolBSplinesFI::assembleSensitivities(), sensitivitySurface::computeDerivativesSize(), sensitivitySurface::computeRadius(), sensitivitySurfacePoints::constructGlobalPointNormalsAndAreas(), sensitivitySurfacePoints::finaliseFaceMultiplier(), sensitivitySurfacePoints::finalisePointSensitivities(), FIBase::read(), sensitivitySurface::read(), sensitivitySurfacePoints::read(), sensitivitySurface::sensitivitySurface(), sensitivitySurfacePoints::sensitivitySurfacePoints(), sensitivitySurface::smoothSensitivities(), sensitivityBezierFI::solveMeshMovementEqn(), sensitivityBezier::write(), sensitivityBezierFI::write(), sensitivityVolBSplines::write(), and sensitivityVolBSplinesFI::write().
dict_
dictionary dict_ protected
Definition at line 66 of file sensitivity.H.
Referenced by FIBase::read(), sensitivityBezierFI::read(), and sensitivitySurface::read().
fieldSensPtr_
autoPtr<volScalarField> fieldSensPtr_ protected
Definition at line 70 of file sensitivity.H.
Referenced by adjointSensitivity::clearSensitivities().
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/optimisation/adjointSensitivity/sensitivity/sensitivity.H
src/optimisation/adjointOptimisation/adjoint/optimisation/adjointSensitivity/sensitivity/sensitivity.C