OpenFOAM: transferModelList Class Reference
transferModelList Class Reference
#include <transferModelList.H>
Public Member Functions
transferModelList (surfaceFilmRegionModel &film)
transferModelList (surfaceFilmRegionModel &film, const dictionary &dict)
virtual ~transferModelList ()
virtual void correct (scalarField &availableMass, volScalarField &massToTransfer)
virtual void correct (scalarField &availableMass, volScalarField &massToTransfer, volScalarField &energyToTransfer)
virtual void info (Ostream &os)
Public Member Functions inherited from PtrList< transferModel >
constexpr PtrList () noexcept
PtrList (const label len)
PtrList (const PtrList< transferModel > &list)
PtrList (PtrList< transferModel > &&list)
PtrList (UList< transferModel * > &list)
PtrList (const PtrList< transferModel > &list, const CloneArg &cloneArgs)
PtrList (PtrList< transferModel > &list, bool reuse)
PtrList (const SLPtrList< transferModel > &list)
PtrList (Istream &is, const INew &inew)
PtrList (Istream &is)
~PtrList ()
PtrList< transferModel > clone (Args &&... args) const
Foam::PtrList< transferModel > clone (Args &&... args) const
const transferModel * set (const label i) const
autoPtr< transferModel > set (const label i, transferModel *ptr)
autoPtr< transferModel > set (const label i, std::unique_ptr< transferModel > &&ptr)
autoPtr< transferModel > set (const label i, autoPtr< transferModel > &&ptr)
autoPtr< transferModel > set (const label i, const refPtr< transferModel > &ptr)
autoPtr< transferModel > set (const label i, const tmp< transferModel > &ptr)
autoPtr< transferModel > set (const label i, autoPtr< transferModel > &ptr)
void clear ()
void free ()
void resize (const label newLen)
transferModel & emplace_back (Args &&... args)
void push_back (transferModel *ptr)
void push_back (std::unique_ptr< transferModel > &&ptr)
void push_back (autoPtr< transferModel > &&ptr)
void push_back (const refPtr< transferModel > &ptr)
void push_back (const tmp< transferModel > &ptr)
void push_back (PtrList< transferModel > &&other)
void push_back (autoPtr< transferModel > &ptr)=delete
transferModel & emplace_set (const label i, Args &&... args)
transferModel & emplace (const label i, Args &&... args)
autoPtr< transferModel > release (const label i)
void transfer (PtrList< transferModel > &list)
void operator= (const PtrList< transferModel > &list)
void operator= (PtrList< transferModel > &&list)
void setSize (const label newLen)
void append (autoPtr< transferModel > &ptr)
void append (transferModel *ptr)
void append (std::unique_ptr< transferModel > &&ptr)
void append (autoPtr< transferModel > &&ptr)
void append (const refPtr< transferModel > &ptr)
void append (const tmp< transferModel > &ptr)
void append (PtrList< transferModel > &&other)
Public Member Functions inherited from UPtrList< T >
constexpr UPtrList () noexcept
UPtrList (const label len)
UPtrList (const UPtrList< T > &list)
UPtrList (UPtrList< T > &&list)
UPtrList (UPtrList< T > &list, bool reuse)
UPtrList (PtrList< T > &list)
UPtrList (const UList< T * > &list)
UPtrList (UList< T > &list)
bool empty () const noexcept
label size () const noexcept
label count () const noexcept
T & front ()
const T & front () const
T & back ()
const T & back () const
const T * test (const label i) const
const T * get (const label i) const
T * get (const label i)
const T * set (const label i) const
void clear ()
void free ()
void resize (const label newLen)
label squeezeNull ()
void trimTrailingNull ()
void push_back (T *ptr)
void push_back (UPtrList< T > &&other)
void swap (UPtrList< T > &list)
void transfer (UPtrList< T > &list)
T * set (const label i, T *ptr)
void reorder (const labelUList &oldToNew, const bool check=false)
void sortOrder (const labelUList &order, const bool check=false)
void checkNonNull () const
const T & at (const label i) const
T & at (const label i)
const T & operator[] (const label i) const
T & operator[] (const label i)
FOAM_DEPRECATED_FOR (2022-09, "get(), set() or test() methods") const T *operator()(const label i) const
void operator= (const UPtrList< T > &list)
void operator= (UPtrList< T > &&list)
T ** begin_ptr () noexcept
T ** end_ptr () noexcept
iterator begin ()
iterator end () noexcept
const_iterator cbegin () const
const_iterator cend () const noexcept
const_iterator begin () const
const_iterator end () const noexcept
void setSize (const label n)
T & first ()
const T & first () const
T & last ()
const T & last () const
void append (T *ptr)
void append (UPtrList< T > &&other)
Public Member Functions inherited from filmSubModelBase
filmSubModelBase (surfaceFilmRegionModel &film)
filmSubModelBase (surfaceFilmRegionModel &film, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
filmSubModelBase (const word &modelName, surfaceFilmRegionModel &film, const dictionary &dict, const word &baseName, const word &modelType)
virtual ~filmSubModelBase ()
virtual bool writeTime () const
const surfaceFilmRegionModel & film () const
surfaceFilmRegionModel & film ()
template<class FilmType >
const FilmType & filmType () const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
subModelBase (const subModelBase &smb)
virtual ~subModelBase ()=default
const word & modelName () const
const dictionary & dict () const
const word & baseName () const
const word & modelType () const
const dictionary & coeffDict () const
const dictionary & properties () const
virtual bool defaultCoeffs (const bool printMsg) const
virtual bool active () const
virtual void cacheFields (const bool store)
virtual fileName localPath () const
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
bool getModelDict (const word &entryName, dictionary &dict) const
template<class Type >
bool getModelProperty (const word &entryName, Type &value) const
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
virtual void write (Ostream &os) const
Additional Inherited Members
Public Types inherited from UPtrList< T >
typedef T value_type
typedef T & reference
typedef const T & const_reference
Public Attributes inherited from subModelBase
bool log
Protected Member Functions inherited from PtrList< transferModel >
void readIstream (Istream &is, const INew &inew)
Protected Member Functions inherited from UPtrList< T >
void setAddressableSize (const label n) noexcept
label find_next (label pos) const
UPtrList (Detail::PtrListDetail< T > &&ptrs)
Protected Member Functions inherited from subModelBase
bool inLine () const
Protected Attributes inherited from UPtrList< T >
Detail::PtrListDetail< T > ptrs_
Protected Attributes inherited from filmSubModelBase
surfaceFilmRegionModel & filmModel_
Protected Attributes inherited from subModelBase
const word modelName_
dictionary & properties_
const dictionary dict_
const word baseName_
const word modelType_
const dictionary coeffDict_
Detailed Description
Definition at line 52 of file transferModelList.H.
Constructor & Destructor Documentation
transferModelList() [1/2]
transferModelList (surfaceFilmRegionModel & film)
Definition at line 35 of file transferModelList.C.
transferModelList() [2/2]
transferModelList (surfaceFilmRegionModel & film, const dictionary & dict)
Definition at line 42 of file transferModelList.C.
References subModelBase::dict(), Foam::endl(), filmSubModelBase::film(), Foam::Info, transferModel::New(), PtrList< transferModel >::PtrList(), PtrList< transferModel >::set(), PtrList< transferModel >::setSize(), HashTable< T, Key, Hash >::size(), and UPtrList< T >::size().
~transferModelList()
~transferModelList () virtual
Definition at line 87 of file transferModelList.C.
Member Function Documentation
correct() [1/2]
void correct (scalarField & availableMass, volScalarField & massToTransfer) virtual
Definition at line 93 of file transferModelList.C.
References filmSubModelBase::film(), forAll, UPtrList< T >::operator[](), patchIDs(), and Foam::sum().
Referenced by kinematicSingleLayer::updateSubmodels(), and thermoSingleLayer::updateSubmodels().
correct() [2/2]
void correct (scalarField & availableMass, volScalarField & massToTransfer, volScalarField & energyToTransfer) virtual
Definition at line 119 of file transferModelList.C.
References filmSubModelBase::film(), forAll, UPtrList< T >::operator[](), patchIDs(), and Foam::sum().
info()
void info (Ostream & os) virtual
Definition at line 147 of file transferModelList.C.
References Foam::endl(), filmSubModelBase::film(), forAll, subModelBase::getBaseProperty(), Foam::indent(), Foam::Info, Pstream::listCombineGather(), Foam::mag(), IOstream::name(), Foam::nl, UPtrList< T >::operator[](), os(), patchIDs(), transferModel::patchTransferredMassTotals(), pbm, PtrList< transferModel >::PtrList(), subModelBase::setBaseProperty(), UPtrList< T >::size(), UList< T >::size(), transferModel::transferredMassTotal(), filmSubModelBase::writeTime(), and Foam::Zero.
Referenced by kinematicSingleLayer::info().
The documentation for this class was generated from the following files:
src/regionModels/surfaceFilmModels/submodels/kinematic/transferModels/transferModelList/transferModelList.H
src/regionModels/surfaceFilmModels/submodels/kinematic/transferModels/transferModelList/transferModelList.C