OpenFOAM: diameterModel Class Reference
diameterModel Class Reference abstract
Abstract base-class for dispersed-phase particle diameter models.
#include <diameterModel.H>
Public Member Functions
TypeName ("diameterModel")
declareRunTimeSelectionTable (autoPtr, diameterModel, dictionary,(const dictionary &dict, const phaseModel &phase),(dict, phase))
diameterModel (const dictionary &dict, const phaseModel &phase)
virtual ~diameterModel ()=default
const dictionary & diameterProperties () const
const phaseModel & phase () const
virtual tmp< volScalarField > d () const =0
virtual void correct ()
virtual bool read (const dictionary &phaseProperties)=0
TypeName ("diameterModel")
declareRunTimeSelectionTable (autoPtr, diameterModel, dictionary,(const dictionary &dict, const phaseModel &phase),(dict, phase))
diameterModel (const dictionary &dict, const phaseModel &phase)
virtual ~diameterModel ()=default
const dictionary & diameterProperties () const
const phaseModel & phase () const
virtual tmp< volScalarField > d () const =0
virtual void correct ()
virtual bool read (const dictionary &dict)=0
Static Public Member Functions
static autoPtr< diameterModel > New (const dictionary &diameterProperties, const phaseModel &phase)
static autoPtr< diameterModel > New (const dictionary &dict, const phaseModel &phase)
Protected Attributes
dictionary diameterProperties_
const phaseModel & phase_
Detailed Description
Abstract base-class for dispersed-phase particle diameter models.
Source files
diameterModel.H
diameterModel.C
Source files
diameterModel.H
diameterModel.C
Definition at line 49 of file diameterModel.H.
Constructor & Destructor Documentation
diameterModel() [1/2]
diameterModel (const dictionary & dict, const phaseModel & phase)
Definition at line 35 of file diameterModel.C.
~diameterModel() [1/2]
virtual ~diameterModel () virtual default
diameterModel() [2/2]
diameterModel (const dictionary & dict, const phaseModel & phase)
~diameterModel() [2/2]
virtual ~diameterModel () virtual default
Member Function Documentation
TypeName() [1/2]
TypeName ("diameterModel")
declareRunTimeSelectionTable() [1/2]
declareRunTimeSelectionTable (autoPtr , diameterModel , dictionary , (const dictionary &dict, const phaseModel &phase) , (dict, phase))
New() [1/2]
Foam::autoPtr< Foam::diameterModel > New (const dictionary & diameterProperties, const phaseModel & phase) static
Definition at line 49 of file diameterModel.C.
References Foam::abort(), dict, Foam::endl(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), Foam::Info, phase::name(), and dictionary::optionalSubDict().
Referenced by phaseModel::phaseModel(), and phaseModel::phaseModel().
diameterProperties() [1/2]
const dictionary & diameterProperties () const inline
Definition at line 106 of file diameterModel.H.
References diameterModel::diameterProperties_.
phase() [1/2]
const phaseModel & phase () const inline
Definition at line 112 of file diameterModel.H.
References diameterModel::phase_.
Referenced by velocityGroup::velocityGroup().
d() [1/2]
virtual tmp< volScalarField > d () const pure virtual
Implemented in constant, isothermal, linearTsub, velocityGroup, IATE, constant, IATE, and isothermal.
correct() [1/2]
void correct () virtual
Reimplemented in isothermal, linearTsub, IATE, and IATE.
Definition at line 85 of file diameterModel.C.
read() [1/2]
bool read (const dictionary & phaseProperties) pure virtual
Implemented in constant, velocityGroup, constant, isothermal, linearTsub, IATE, IATE, and isothermal.
Definition at line 89 of file diameterModel.C.
References dict, dictionary::optionalSubDict(), and Foam::type().
Referenced by constant::read(), velocityGroup::read(), isothermal::read(), linearTsub::read(), and IATE::read().
TypeName() [2/2]
TypeName ("diameterModel")
declareRunTimeSelectionTable() [2/2]
declareRunTimeSelectionTable (autoPtr , diameterModel , dictionary , (const dictionary &dict, const phaseModel &phase) , (dict, phase))
New() [2/2]
static autoPtr< diameterModel > New (const dictionary & dict, const phaseModel & phase) static
diameterProperties() [2/2]
const dictionary & diameterProperties () const inline
Definition at line 105 of file diameterModel.H.
References diameterModel::diameterProperties_.
phase() [2/2]
const phaseModel & phase () const inline
Definition at line 111 of file diameterModel.H.
References diameterModel::phase_.
d() [2/2]
virtual tmp< volScalarField > d () const pure virtual
Implemented in constant, isothermal, linearTsub, velocityGroup, IATE, constant, IATE, and isothermal.
correct() [2/2]
virtual void correct () virtual
Reimplemented in isothermal, linearTsub, IATE, and IATE.
read() [2/2]
virtual bool read (const dictionary & dict) pure virtual
Implemented in constant, velocityGroup, constant, isothermal, linearTsub, IATE, IATE, and isothermal.
Member Data Documentation
diameterProperties_
dictionary diameterProperties_ protected
Definition at line 55 of file diameterModel.H.
Referenced by diameterModel::diameterProperties().
phase_
const phaseModel & phase_ protected
Definition at line 57 of file diameterModel.H.
Referenced by IATE::a(), diameterModel::phase(), and velocityGroup::velocityGroup().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/diameterModels/diameterModel/diameterModel.H
src/phaseSystemModels/twoPhaseEuler/twoPhaseSystem/diameterModels/diameterModel/diameterModel.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/diameterModels/diameterModel/diameterModel.C
src/phaseSystemModels/twoPhaseEuler/twoPhaseSystem/diameterModels/diameterModel/diameterModel.C