OpenFOAM: atmBoundaryLayerInletVelocityFvPatchVectorField Class Reference
atmBoundaryLayerInletVelocityFvPatchVectorField Class Reference
Turbulence models » RAS turbulence » Boundary conditions | Boundary conditions » Inlet
This boundary condition provides a log-law type ground-normal inlet boundary condition for the streamwise component of wind velocity (i.e. u) for homogeneous, two-dimensional, dry-air, equilibrium and neutral atmospheric boundary layer modelling.
#include <atmBoundaryLayerInletVelocityFvPatchVectorField.H>
Public Member Functions
TypeName ("atmBoundaryLayerInletVelocity")
atmBoundaryLayerInletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
atmBoundaryLayerInletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
atmBoundaryLayerInletVelocityFvPatchVectorField (const atmBoundaryLayerInletVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
virtual tmp< fvPatchVectorField > clone () const
atmBoundaryLayerInletVelocityFvPatchVectorField (const atmBoundaryLayerInletVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
virtual void updateCoeffs ()
virtual void autoMap (const fvPatchFieldMapper &)
virtual void rmap (const fvPatchVectorField &, const labelList &)
virtual void write (Ostream &) const
Public Member Functions inherited from atmBoundaryLayer
atmBoundaryLayer (const Time &time, const polyPatch &pp)
atmBoundaryLayer (const Time &time, const polyPatch &pp, const dictionary &dict)
atmBoundaryLayer (const atmBoundaryLayer &abl, const fvPatch &patch, const fvPatchFieldMapper &mapper)
atmBoundaryLayer (const atmBoundaryLayer &)
vector flowDir () const
vector zDir () const
tmp< scalarField > Ustar (const scalarField &z0) const
void autoMap (const fvPatchFieldMapper &)
void rmap (const atmBoundaryLayer &, const labelList &)
tmp< vectorField > U (const vectorField &pCf) const
tmp< scalarField > k (const vectorField &pCf) const
tmp< scalarField > epsilon (const vectorField &pCf) const
tmp< scalarField > omega (const vectorField &pCf) const
void write (Ostream &) const
Additional Inherited Members
Protected Attributes inherited from atmBoundaryLayer
bool initABL_
Detailed Description
This boundary condition provides a log-law type ground-normal inlet boundary condition for the streamwise component of wind velocity (i.e. u) for homogeneous, two-dimensional, dry-air, equilibrium and neutral atmospheric boundary layer modelling.
The ground-normal streamwise flow speed profile expression:
where
= Ground-normal streamwise flow speed profile [m/s]
= Spanwise flow speed [m/s]
= Ground-normal flow speed [m/s]
= Friction velocity [m/s]
= von Kármán constant [-]
= Ground-normal coordinate component [m]
= Ground-normal displacement height [m]
= Aerodynamic roughness length [m]
Required fields:
        U   | Velocity                                          [m/s]
Usage
Example of the boundary condition specification:
inlet
{
    // Mandatory entries (unmodifiable)
    type            atmBoundaryLayerInletVelocity;
    // Mandatory/Optional (inherited) entries (unmodifiable)
    ...
}
where the entries mean:
Property Description Type Reqd Deflt
type Type name: atmBoundaryLayerInletVelocity word yes -
The inherited entries are elaborated in:
atmBoundaryLayer.H
inletOutletFvPatchField.H
See also
Foam::atmBoundaryLayer
Foam::atmBoundaryLayerInletKFvPatchScalarField
Foam::atmBoundaryLayerInletEpsilonFvPatchScalarField
Foam::atmBoundaryLayerInletOmegaFvPatchScalarField
Source files
atmBoundaryLayerInletVelocityFvPatchVectorField.H
atmBoundaryLayerInletVelocityFvPatchVectorField.C
Definition at line 155 of file atmBoundaryLayerInletVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
atmBoundaryLayerInletVelocityFvPatchVectorField() [1/4]
atmBoundaryLayerInletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Definition at line 35 of file atmBoundaryLayerInletVelocityFvPatchVectorField.C.
atmBoundaryLayerInletVelocityFvPatchVectorField() [2/4]
atmBoundaryLayerInletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Definition at line 47 of file atmBoundaryLayerInletVelocityFvPatchVectorField.C.
References dict, atmBoundaryLayer::initABL_, IOobjectOption::MUST_READ, Field< vector >::operator=(), U, and Foam::Zero.
atmBoundaryLayerInletVelocityFvPatchVectorField() [3/4]
atmBoundaryLayerInletVelocityFvPatchVectorField (const atmBoundaryLayerInletVelocityFvPatchVectorField & pvf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 76 of file atmBoundaryLayerInletVelocityFvPatchVectorField.C.
atmBoundaryLayerInletVelocityFvPatchVectorField() [4/4]
atmBoundaryLayerInletVelocityFvPatchVectorField (const atmBoundaryLayerInletVelocityFvPatchVectorField & pvf, const DimensionedField< vector, volMesh > & iF)
Definition at line 90 of file atmBoundaryLayerInletVelocityFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("atmBoundaryLayerInletVelocity")
clone() [1/2]
virtual tmp< fvPatchVectorField > clone () const inline virtual
Definition at line 195 of file atmBoundaryLayerInletVelocityFvPatchVectorField.H.
clone() [2/2]
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Definition at line 211 of file atmBoundaryLayerInletVelocityFvPatchVectorField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 104 of file atmBoundaryLayerInletVelocityFvPatchVectorField.C.
References U.
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Definition at line 117 of file atmBoundaryLayerInletVelocityFvPatchVectorField.C.
References atmBoundaryLayer::autoMap().
rmap()
void rmap (const fvPatchVectorField & pvf, const labelList & addr) virtual
Definition at line 127 of file atmBoundaryLayerInletVelocityFvPatchVectorField.C.
References atmBoundaryLayer::rmap().
write()
void write (Ostream & os) const virtual
Definition at line 142 of file atmBoundaryLayerInletVelocityFvPatchVectorField.C.
References os(), atmBoundaryLayer::write(), fvPatchField< Type >::write(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/atmosphericModels/derivedFvPatchFields/atmBoundaryLayerInletVelocity/atmBoundaryLayerInletVelocityFvPatchVectorField.H
src/atmosphericModels/derivedFvPatchFields/atmBoundaryLayerInletVelocity/atmBoundaryLayerInletVelocityFvPatchVectorField.C