OpenFOAM: indexedOctreeBase Class Reference
indexedOctreeBase Class Reference
#include <indexedOctree.H>
Classes
class node
Public Member Functions
ClassName ("indexedOctree")
indexedOctreeBase ()=default
Static Public Member Functions
static bool isEmpty (labelBits i) noexcept
static bool isContent (labelBits i) noexcept
static bool isNode (labelBits i) noexcept
static label getContent (labelBits i)
static label getNode (const labelBits i)
static direction getOctant (labelBits i) noexcept
static scalar & perturbTol () noexcept
static scalar perturbTol (scalar tol) noexcept
static void writeOBJ (Ostream &os, const treeBoundBox &bb, label &vertIndex, const bool writeLinesOnly=false)
Static Protected Member Functions
static labelBits emptyPlusOctant (direction octant)
static labelBits contentPlusOctant (label i, direction octant)
static labelBits nodePlusOctant (label i, direction octant)
Static Protected Attributes
static scalar perturbTol_ = 10*SMALL
Detailed Description
Definition at line 67 of file indexedOctree.H.
Constructor & Destructor Documentation
indexedOctreeBase()
indexedOctreeBase () default
Member Function Documentation
isEmpty()
static bool isEmpty (labelBits i) inline static noexcept
Definition at line 127 of file indexedOctree.H.
isContent()
static bool isContent (labelBits i) inline static noexcept
Definition at line 133 of file indexedOctree.H.
Referenced by indexedOctreeBase::getContent().
isNode()
static bool isNode (labelBits i) inline static noexcept
Definition at line 139 of file indexedOctree.H.
Referenced by indexedOctreeBase::getNode().
getContent()
static label getContent (labelBits i) inline static
Definition at line 148 of file indexedOctree.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, indexedOctreeBase::isContent(), and labelBits::val().
getNode()
static label getNode (const labelBits i) inline static
Definition at line 159 of file indexedOctree.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, indexedOctreeBase::isNode(), and labelBits::val().
getOctant()
static direction getOctant (labelBits i) inline static noexcept
Definition at line 170 of file indexedOctree.H.
emptyPlusOctant()
static labelBits emptyPlusOctant (direction octant) inline static protected
Definition at line 194 of file indexedOctree.H.
contentPlusOctant()
static labelBits contentPlusOctant (label i, direction octant) inline static protected
Definition at line 200 of file indexedOctree.H.
nodePlusOctant()
static labelBits nodePlusOctant (label i, direction octant) inline static protected
Definition at line 206 of file indexedOctree.H.
perturbTol() [1/2]
static scalar & perturbTol () inline static noexcept
Definition at line 215 of file indexedOctree.H.
References indexedOctreeBase::perturbTol_.
Referenced by triSurfaceMesh::edgeTree(), triSurfaceSearch::findLine(), triSurfaceSearch::findLineAll(), triSurfaceSearch::findLineAny(), triSurfaceSearch::findNearest(), triSurfaceMesh::getVolumeType(), triSurfaceSearch::tree(), and triSurfaceSearch::triSurfaceSearch().
perturbTol() [2/2]
static scalar perturbTol (scalar tol) inline static noexcept
Definition at line 218 of file indexedOctree.H.
References indexedOctreeBase::perturbTol_.
ClassName()
ClassName ("indexedOctree")
writeOBJ()
void writeOBJ (Ostream & os, const treeBoundBox & bb, label & vertIndex, const bool writeLinesOnly = false) static
Definition at line 37 of file indexedOctreeBase.C.
References e, treeBoundBox::edges, f(), treeBoundBox::faces, Foam::nl, os(), p, treeBoundBox::points(), pts, and UPtrList< T >::size().
Member Data Documentation
perturbTol_
scalar perturbTol_ = 10*SMALL static protected
Definition at line 185 of file indexedOctree.H.
Referenced by indexedOctreeBase::perturbTol(), and indexedOctreeBase::perturbTol().
The documentation for this class was generated from the following files:
src/OpenFOAM/algorithms/indexedOctree/indexedOctree.H
src/OpenFOAM/algorithms/indexedOctree/indexedOctreeBase.C