OpenFOAM: thixotropicViscosity Class Reference
thixotropicViscosity Class Reference
Thixotropic viscosity model based on the evolution of the structural parameter :
#include <thixotropicViscosity.H>
Public Member Functions
TypeName ("thixotropic")
thixotropicViscosity (surfaceFilmRegionModel &film, const dictionary &dict, volScalarField &mu)
virtual ~thixotropicViscosity ()
virtual void correct (const volScalarField &p, const volScalarField &T)
Public Member Functions inherited from filmViscosityModel
TypeName ("filmViscosityModel")
declareRunTimeSelectionTable (autoPtr, filmViscosityModel, dictionary,(surfaceFilmRegionModel &film, const dictionary &dict, volScalarField &mu),(film, dict, mu))
filmViscosityModel (const word &modelType, surfaceFilmRegionModel &film, const dictionary &dict, volScalarField &mu)
virtual ~filmViscosityModel ()
virtual void info (Ostream &os) const
Public Member Functions inherited from filmSubModelBase
filmSubModelBase (surfaceFilmRegionModel &film)
filmSubModelBase (surfaceFilmRegionModel &film, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
filmSubModelBase (const word &modelName, surfaceFilmRegionModel &film, const dictionary &dict, const word &baseName, const word &modelType)
virtual ~filmSubModelBase ()
virtual bool writeTime () const
const surfaceFilmRegionModel & film () const
surfaceFilmRegionModel & film ()
template<class FilmType >
const FilmType & filmType () const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
subModelBase (const subModelBase &smb)
virtual ~subModelBase ()=default
const word & modelName () const
const dictionary & dict () const
const word & baseName () const
const word & modelType () const
const dictionary & coeffDict () const
const dictionary & properties () const
virtual bool defaultCoeffs (const bool printMsg) const
virtual bool active () const
virtual void cacheFields (const bool store)
virtual fileName localPath () const
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
bool getModelDict (const word &entryName, dictionary &dict) const
template<class Type >
bool getModelProperty (const word &entryName, Type &value) const
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
virtual void write (Ostream &os) const
Protected Attributes
dimensionedScalar a_
dimensionedScalar b_
dimensionedScalar d_
dimensionedScalar c_
dimensionedScalar mu0_
dimensionedScalar muInf_
dimensionedScalar K_
volScalarField lambda_
Protected Attributes inherited from filmViscosityModel
volScalarField & mu_
Protected Attributes inherited from filmSubModelBase
surfaceFilmRegionModel & filmModel_
Protected Attributes inherited from subModelBase
const word modelName_
dictionary & properties_
const dictionary dict_
const word baseName_
const word modelType_
const dictionary coeffDict_
Additional Inherited Members
Static Public Member Functions inherited from filmViscosityModel
static autoPtr< filmViscosityModel > New (surfaceFilmRegionModel &film, const dictionary &dict, volScalarField &mu)
Public Attributes inherited from subModelBase
bool log
Protected Member Functions inherited from subModelBase
bool inLine () const
Detailed Description
Thixotropic viscosity model based on the evolution of the structural parameter :
The viscosity is then calculated using the expression
Where the parameter K is given by:
Here:
= structural parameter
= model coefficient
= model coefficient
= model coefficient
= model coefficient
= stress rate [1/s]
= limiting viscosity when
= limiting viscosity when
Reference:
        Barnes H A, 1997.  Thixotropy - a review.  J. Non-Newtonian Fluid
        Mech 70, pp 1-33
Source files
thixotropicViscosity.H
thixotropicViscosity.C
Definition at line 117 of file thixotropicViscosity.H.
Constructor & Destructor Documentation
thixotropicViscosity()
thixotropicViscosity (surfaceFilmRegionModel & film, const dictionary & dict, volScalarField & mu)
Definition at line 53 of file thixotropicViscosity.C.
References GeometricField< Type, PatchField, GeoMesh >::clamp_range(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), thixotropicViscosity::lambda_, filmViscosityModel::mu_, and thixotropicViscosity::muInf_.
~thixotropicViscosity()
~thixotropicViscosity () virtual
Definition at line 91 of file thixotropicViscosity.C.
Member Function Documentation
TypeName()
TypeName ("thixotropic")
correct()
void correct (const volScalarField & p, const volScalarField & T) virtual
Implements filmViscosityModel.
Definition at line 97 of file thixotropicViscosity.C.
References thixotropicViscosity::a_, alpha, thixotropicViscosity::b_, thixotropicViscosity::c_, GeometricField< Type, PatchField, GeoMesh >::clamp_range(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), thixotropicViscosity::d_, Foam::fvm::ddt(), delta, DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimless, Foam::dimTime, Foam::fvc::div(), Foam::fvm::div(), filmSubModelBase::film(), Foam::fvc::interpolate(), thixotropicViscosity::K_, thixotropicViscosity::lambda_, Foam::mag(), Foam::max(), filmViscosityModel::mu_, thixotropicViscosity::muInf_, phi, Foam::pow(), runTime, Foam::fvm::Sp(), Foam::sqr(), Foam::fvm::SuSp(), U, and Foam::Zero.
Member Data Documentation
a_
dimensionedScalar a_ protected
Definition at line 135 of file thixotropicViscosity.H.
Referenced by thixotropicViscosity::correct().
b_
dimensionedScalar b_ protected
Definition at line 138 of file thixotropicViscosity.H.
Referenced by thixotropicViscosity::correct().
d_
dimensionedScalar d_ protected
Definition at line 141 of file thixotropicViscosity.H.
Referenced by thixotropicViscosity::correct().
c_
dimensionedScalar c_ protected
Definition at line 144 of file thixotropicViscosity.H.
Referenced by thixotropicViscosity::correct().
mu0_
dimensionedScalar mu0_ protected
Definition at line 147 of file thixotropicViscosity.H.
muInf_
dimensionedScalar muInf_ protected
Definition at line 150 of file thixotropicViscosity.H.
Referenced by thixotropicViscosity::correct(), and thixotropicViscosity::thixotropicViscosity().
K_
dimensionedScalar K_ protected
Definition at line 153 of file thixotropicViscosity.H.
Referenced by thixotropicViscosity::correct().
lambda_
volScalarField lambda_ protected
Definition at line 158 of file thixotropicViscosity.H.
Referenced by thixotropicViscosity::correct(), and thixotropicViscosity::thixotropicViscosity().
The documentation for this class was generated from the following files:
src/regionModels/surfaceFilmModels/submodels/thermo/filmViscosityModel/thixotropicViscosity/thixotropicViscosity.H
src/regionModels/surfaceFilmModels/submodels/thermo/filmViscosityModel/thixotropicViscosity/thixotropicViscosity.C