OpenFOAM: energySpectrum Class Reference
energySpectrum Class Reference
FunctionObjects » Field function objects
Calculates the energy spectrum for a structured IJK mesh.
#include <energySpectrum.H>
Public Member Functions
TypeName ("energySpectrum")
energySpectrum (const word &name, const Time &runTime, const dictionary &dict)
virtual ~energySpectrum ()=default
virtual bool read (const dictionary &)
virtual bool execute ()
virtual bool write ()
Public Member Functions inherited from fvMeshFunctionObject
TypeName ("fvMeshFunctionObject")
fvMeshFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
fvMeshFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
virtual ~fvMeshFunctionObject ()=default
Public Member Functions inherited from regionFunctionObject
TypeName ("regionFunctionObject")
regionFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
regionFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
virtual ~regionFunctionObject ()=default
template<class ObjectType >
const ObjectType * lookupObjectPtr (const word &fieldName) const
template<class ObjectType >
ObjectType * lookupObjectRefPtr (const word &fieldName) const
Public Member Functions inherited from stateFunctionObject
stateFunctionObject (const word &name, const Time &runTime)
virtual ~stateFunctionObject ()=default
dictionary & propertyDict ()
bool foundProperty (const word &entryName) const
void clearTrigger ()
label getTrigger () const
bool setTrigger (const label triggeri)
bool getDict (const word &entryName, dictionary &dict) const
bool getObjectDict (const word &objectName, const word &entryName, dictionary &dict) const
template<class Type >
Type getProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getProperty (const word &entryName, Type &value) const
template<class Type >
void setProperty (const word &entryName, const Type &value)
template<class Type >
Type getObjectProperty (const word &objectName, const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getObjectProperty (const word &objectName, const word &entryName, Type &value) const
template<class Type >
void setObjectProperty (const word &objectName, const word &entryName, const Type &value)
template<class Type >
void setResult (const word &entryName, const Type &value)
template<class Type >
void setObjectResult (const word &objectName, const word &entryName, const Type &value)
template<class Type >
Type getResult (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
Type getObjectResult (const word &objectName, const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getObjectResult (const word &objectName, const word &entryName, Type &value) const
word resultType (const word &entryName) const
word objectResultType (const word &objectName, const word &entryName) const
wordList objectResultEntries () const
wordList objectResultEntries (const word &objectName) const
void writeResultEntries (Ostream &os) const
void writeResultEntries (const word &objectName, Ostream &os) const
void writeAllResultEntries (Ostream &os) const
Public Member Functions inherited from timeFunctionObject
timeFunctionObject (const word &name, const Time &runTime)
virtual ~timeFunctionObject ()=default
const Time & time () const
objectRegistry & storedObjects ()
const objectRegistry & storedObjects () const
Public Member Functions inherited from functionObject
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name, const bool withNamePrefix=defaultUseNamePrefix)
autoPtr< functionObject > clone () const
virtual ~functionObject ()=default
virtual const word & type () const =0
const word & name () const noexcept
bool useNamePrefix () const noexcept
bool useNamePrefix (bool on) noexcept
virtual bool execute (const label subIndex)
virtual bool end ()
virtual bool adjustTimeStep ()
virtual bool filesModified () const
virtual void updateMesh (const mapPolyMesh &mpm)
virtual void movePoints (const polyMesh &mesh)
Public Member Functions inherited from writeFile
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name="undefined", const bool writeToFile=true)
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name, const dictionary &dict, const bool writeToFile=true)
writeFile (const writeFile &wf)
virtual ~writeFile ()=default
virtual OFstream & file ()
virtual bool writeToFile () const
virtual bool canWriteToFile () const
virtual bool canResetFile () const
virtual bool canWriteHeader () const
virtual label charWidth () const
virtual void writeCommented (Ostream &os, const string &str) const
virtual void writeTabbed (Ostream &os, const string &str) const
virtual void writeHeader (Ostream &os, const string &str) const
virtual void writeCurrentTime (Ostream &os) const
virtual void writeBreak (Ostream &os) const
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
template<class Type >
void writeValue (Ostream &os, const Type &val) const
Protected Member Functions
virtual void writeFileHeader (Ostream &os)
void calcAndWriteSpectrum (const vectorField &U, const vectorField &C, const vector &c0, const vector &deltaC, const Vector< int > &N, const scalar kappaNorm)
energySpectrum (const energySpectrum &)=delete
void operator= (const energySpectrum &)=delete
Protected Member Functions inherited from fvMeshFunctionObject
fvMeshFunctionObject (const fvMeshFunctionObject &)=delete
void operator= (const fvMeshFunctionObject &)=delete
Protected Member Functions inherited from regionFunctionObject
virtual const objectRegistry & obr () const
template<class ObjectType >
bool foundObject (const word &fieldName) const
template<class ObjectType >
const ObjectType * cfindObject (const word &fieldName) const
template<class ObjectType >
const ObjectType * findObject (const word &fieldName) const
template<class ObjectType >
ObjectType * findObject (const word &fieldName)
template<class ObjectType >
ObjectType * getObjectPtr (const word &fieldName) const
template<class ObjectType >
const ObjectType & lookupObject (const word &fieldName) const
template<class ObjectType >
ObjectType & lookupObjectRef (const word &fieldName) const
template<class ObjectType >
bool store (word &fieldName, const tmp< ObjectType > &tfield, bool cacheable=false)
template<class ObjectType >
bool storeInDb (const word &fieldName, const tmp< ObjectType > &tfield, const objectRegistry &obr)
bool writeObject (const word &fieldName)
bool clearObject (const word &fieldName)
void clearObjects (const wordList &objNames)
regionFunctionObject (const regionFunctionObject &)=delete
void operator= (const regionFunctionObject &)=delete
Protected Member Functions inherited from stateFunctionObject
const functionObjects::properties & stateDict () const
functionObjects::properties & stateDict ()
stateFunctionObject (const stateFunctionObject &)=delete
void operator= (const stateFunctionObject &)=delete
Protected Member Functions inherited from timeFunctionObject
void clearOutputObjects (const wordList &objNames)
timeFunctionObject (const timeFunctionObject &)=delete
void operator= (const timeFunctionObject &)=delete
Protected Member Functions inherited from functionObject
word scopedName (const word &name) const
Protected Member Functions inherited from writeFile
void initStream (Ostream &os) const
fileName baseFileDir () const
fileName baseTimeDir () const
fileName filePath (const fileName &fName) const
virtual autoPtr< OFstream > newFile (const fileName &fName) const
virtual autoPtr< OFstream > newFileAtTime (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > newFileAtStartTime (const word &name) const
virtual void resetFile (const word &name)
Omanip< int > valueWidth (const label offset=0) const
void operator= (const writeFile &)=delete
virtual autoPtr< OFstream > createFile (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > createFile (const word &name) const
Protected Attributes
labelList cellAddr_
word UName_
Vector< int > N_
vector c0_
vector deltaC_
scalar kappaNorm_
Protected Attributes inherited from fvMeshFunctionObject
const fvMesh & mesh_
Protected Attributes inherited from regionFunctionObject
word subRegistryName_
const objectRegistry & obr_
const objectRegistry * obrPtr_
Protected Attributes inherited from timeFunctionObject
const Time & time_
Protected Attributes inherited from writeFile
const objectRegistry & fileObr_
const fileName prefix_
word fileName_
autoPtr< OFstream > filePtr_
label writePrecision_
bool writeToFile_
bool updateHeader_
bool writtenHeader_
bool useUserTime_
scalar startTime_
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &runTime, const dictionary &dict)
Public Attributes inherited from functionObject
bool log
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
static bool defaultUseNamePrefix
static word outputPrefix
Static Public Attributes inherited from writeFile
static label addChars = 8
Detailed Description
Calculates the energy spectrum for a structured IJK mesh.
Usage
Example of function object specification:
energySpectrum1
{
    type        energySpectrum;
    libs        (fieldFunctionObjects);
    ...
    log         yes;
}
Where the entries comprise:
Property Description Required Default value
type type name: energySpectrum yes
log write info to standard output no yes
Output data is written to the file <timeDir>/energySpectrum.dat
See also
Foam::functionObjects::fvMeshFunctionObject Foam::functionObjects::writeFile
Source files
energySpectrum.H
energySpectrum.C
energySpectrumTemplates.C
Definition at line 95 of file energySpectrum.H.
Constructor & Destructor Documentation
energySpectrum() [1/2]
energySpectrum (const energySpectrum &) protected delete
energySpectrum() [2/2]
energySpectrum (const word & name, const Time & runTime, const dictionary & dict)
Definition at line 114 of file energySpectrum.C.
References dict, and energySpectrum::read().
~energySpectrum()
virtual ~energySpectrum () virtual default
Member Function Documentation
writeFileHeader()
void writeFileHeader (Ostream & os) protected virtual
Definition at line 44 of file energySpectrum.C.
References Foam::endl(), os(), writeFile::writeCommented(), and writeFile::writeHeader().
calcAndWriteSpectrum()
void calcAndWriteSpectrum (const vectorField & U, const vectorField & C, const vector & c0, const vector & deltaC, const Vector< int > & N, const scalar kappaNorm) protected
Definition at line 54 of file energySpectrum.C.
References Foam::cmptMax(), Foam::cmptProduct(), Foam::ComplexField(), Foam::endl(), forAll, fft::forwardTransform(), k, Log, N(), Foam::name(), Foam::nl, os(), Foam::sqrt(), Foam::tab, U, Uf, Vector< Cmpt >::x(), Vector< Cmpt >::y(), Vector< Cmpt >::z(), Foam::Zero, and VectorSpace< Form, Cmpt, Ncmpts >::zero.
operator=()
void operator= (const energySpectrum &) protected delete
TypeName()
TypeName ("energySpectrum")
read()
bool read (const dictionary & dict) virtual
Reimplemented from regionFunctionObject.
Definition at line 136 of file energySpectrum.C.
References Foam::cmptDivide(), Foam::cmptMax(), dict, e, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, k, L, Log, Foam::max(), meshBb(), Foam::min(), Foam::name(), functionObject::read(), writeFile::read(), Foam::returnReduce(), boundBox::span(), Foam::constant::mathematical::twoPi(), x, and y.
Referenced by energySpectrum::energySpectrum().
execute()
bool execute () virtual
Implements functionObject.
Definition at line 197 of file energySpectrum.C.
write()
bool write () virtual
Implements functionObject.
Definition at line 203 of file energySpectrum.C.
References UPstream::allProcs(), Foam::cmptProduct(), Cp, UPstream::master(), UPstream::masterNo(), UPstream::nonBlocking, UPstream::parRun(), and U.
Member Data Documentation
cellAddr_
labelList cellAddr_ protected
Definition at line 105 of file energySpectrum.H.
UName_
word UName_ protected
Definition at line 108 of file energySpectrum.H.
N_
Vector<int> N_ protected
Definition at line 111 of file energySpectrum.H.
c0_
vector c0_ protected
Definition at line 114 of file energySpectrum.H.
deltaC_
vector deltaC_ protected
Definition at line 117 of file energySpectrum.H.
kappaNorm_
scalar kappaNorm_ protected
Definition at line 120 of file energySpectrum.H.
The documentation for this class was generated from the following files:
src/functionObjects/randomProcesses/energySpectrum/energySpectrum.H
src/functionObjects/randomProcesses/energySpectrum/energySpectrum.C