OpenFOAM: adjointOutletVelocityFluxFvPatchVectorField Class Reference
adjointOutletVelocityFluxFvPatchVectorField Class Reference
An outlet boundary condition for patches in which the primal flow exhibits recirculation. Adds the contribution of the objective as an adjoint momentum flux directly to the PDEs, without the need to first compute an adjoint outlet velocity, circumventing thus the division with (almost) zero that manifests in case of primal flow recirculation.
#include <adjointOutletVelocityFluxFvPatchVectorField.H>
Public Member Functions
TypeName ("adjointOutletVelocityFlux")
adjointOutletVelocityFluxFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
adjointOutletVelocityFluxFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
adjointOutletVelocityFluxFvPatchVectorField (const adjointOutletVelocityFluxFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
virtual tmp< fvPatchVectorField > clone () const
adjointOutletVelocityFluxFvPatchVectorField (const adjointOutletVelocityFluxFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
virtual bool assignable () const
virtual void manipulateMatrix (fvMatrix< vector > &matrix)
virtual void updateCoeffs ()
virtual tmp< Field< vector > > valueInternalCoeffs (const tmp< scalarField > &) const
virtual tmp< Field< vector > > valueBoundaryCoeffs (const tmp< scalarField > &) const
virtual tmp< Field< vector > > gradientBoundaryCoeffs () const
virtual tmp< Field< vector > > gradientInternalCoeffs () const
virtual void write (Ostream &) const
virtual void operator= (const fvPatchField< vector > &pvf)
Public Member Functions inherited from adjointBoundaryCondition< Type >
TypeName ("adjointBoundaryCondition")
adjointBoundaryCondition (const fvPatch &p, const DimensionedField< Type, volMesh > &iF, const word &solverName)
adjointBoundaryCondition (const adjointBoundaryCondition< Type > &)
virtual ~adjointBoundaryCondition ()=default
const word & objectiveManagerName () const
const word & adjointSolverName () const
const word & simulationType () const
void setBoundaryContributionPtr ()
boundaryAdjointContribution & getBoundaryAdjContribution ()
const ATCModel & getATC () const
virtual tmp< Field< typename Foam::outerProduct< Foam::vector, Type >::type > > dxdbMult () const
virtual void updatePrimalBasedQuantities ()
Additional Inherited Members
Protected Member Functions inherited from adjointBoundaryCondition< Type >
template<class Type2 >
tmp< Field< typename Foam::outerProduct< Foam::vector, Type2 >::type > > computePatchGrad (word name)
bool addATCUaGradUTerm ()
Protected Attributes inherited from adjointBoundaryCondition< Type >
const fvPatch & patch_
word managerName_
word adjointSolverName_
word simulationType_
autoPtr< boundaryAdjointContribution > boundaryContrPtr_
Switch addATCUaGradUTerm_
Detailed Description
An outlet boundary condition for patches in which the primal flow exhibits recirculation. Adds the contribution of the objective as an adjoint momentum flux directly to the PDEs, without the need to first compute an adjoint outlet velocity, circumventing thus the division with (almost) zero that manifests in case of primal flow recirculation.
Source files
adjointOutletVelocityFluxFvPatchVectorField.H
adjointOutletVelocityFluxFvPatchVectorField.C
Definition at line 56 of file adjointOutletVelocityFluxFvPatchVectorField.H.
Constructor & Destructor Documentation
adjointOutletVelocityFluxFvPatchVectorField() [1/4]
adjointOutletVelocityFluxFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Definition at line 30 of file adjointOutletVelocityFluxFvPatchVectorField.C.
adjointOutletVelocityFluxFvPatchVectorField() [2/4]
adjointOutletVelocityFluxFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Definition at line 56 of file adjointOutletVelocityFluxFvPatchVectorField.C.
References dict, and IOobjectOption::MUST_READ.
adjointOutletVelocityFluxFvPatchVectorField() [3/4]
adjointOutletVelocityFluxFvPatchVectorField (const adjointOutletVelocityFluxFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 42 of file adjointOutletVelocityFluxFvPatchVectorField.C.
adjointOutletVelocityFluxFvPatchVectorField() [4/4]
adjointOutletVelocityFluxFvPatchVectorField (const adjointOutletVelocityFluxFvPatchVectorField & pivpvf, const DimensionedField< vector, volMesh > & iF)
Definition at line 71 of file adjointOutletVelocityFluxFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("adjointOutletVelocityFlux")
clone() [1/2]
virtual tmp< fvPatchVectorField > clone () const inline virtual
Definition at line 97 of file adjointOutletVelocityFluxFvPatchVectorField.H.
clone() [2/2]
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Definition at line 113 of file adjointOutletVelocityFluxFvPatchVectorField.H.
assignable()
virtual bool assignable () const inline virtual
Definition at line 130 of file adjointOutletVelocityFluxFvPatchVectorField.H.
manipulateMatrix()
void manipulateMatrix (fvMatrix< vector > & matrix) virtual
Definition at line 85 of file adjointOutletVelocityFluxFvPatchVectorField.C.
References addProfiling, forAll, SphericalTensor< scalar >::oneThirdI, and Foam::tr().
updateCoeffs()
void updateCoeffs () virtual
Definition at line 139 of file adjointOutletVelocityFluxFvPatchVectorField.C.
References Foam::operator==().
valueInternalCoeffs()
Foam::tmp< Foam::Field< Foam::vector > > valueInternalCoeffs (const tmp< scalarField > &) const virtual
Definition at line 160 of file adjointOutletVelocityFluxFvPatchVectorField.C.
References Foam::New(), and Foam::Zero.
valueBoundaryCoeffs()
Foam::tmp< Foam::Field< Foam::vector > > valueBoundaryCoeffs (const tmp< scalarField > &) const virtual
Definition at line 170 of file adjointOutletVelocityFluxFvPatchVectorField.C.
References Foam::New(), and Foam::Zero.
gradientBoundaryCoeffs()
Foam::tmp< Foam::Field< Foam::vector > > gradientBoundaryCoeffs () const virtual
Definition at line 180 of file adjointOutletVelocityFluxFvPatchVectorField.C.
References Foam::New(), and Foam::Zero.
gradientInternalCoeffs()
Foam::tmp< Foam::Field< Foam::vector > > gradientInternalCoeffs () const virtual
Definition at line 188 of file adjointOutletVelocityFluxFvPatchVectorField.C.
References Foam::New(), and Foam::Zero.
write()
void write (Ostream & os) const virtual
Definition at line 195 of file adjointOutletVelocityFluxFvPatchVectorField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntry(), and fvPatchField< Type >::writeValueEntry().
operator=()
void operator= (const fvPatchField< vector > & pvf) virtual
Definition at line 208 of file adjointOutletVelocityFluxFvPatchVectorField.C.
References fvPatchField< Type >::operator=().
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/adjointBoundaryConditions/adjointOutletVelocityFlux/adjointOutletVelocityFluxFvPatchVectorField.H
src/optimisation/adjointOptimisation/adjoint/adjointBoundaryConditions/adjointOutletVelocityFlux/adjointOutletVelocityFluxFvPatchVectorField.C