OpenFOAM: InflowBoundaryModel< CloudType > Class Template Reference
InflowBoundaryModel< CloudType > Class Template Reference abstract
Templated inflow boundary model class.
#include <InflowBoundaryModel.H>
Public Member Functions
TypeName ("InflowBoundaryModel")
declareRunTimeSelectionTable (autoPtr, InflowBoundaryModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
InflowBoundaryModel (CloudType &owner)
InflowBoundaryModel (const dictionary &dict, CloudType &owner, const word &type)
virtual ~InflowBoundaryModel ()
const CloudType & owner () const
CloudType & owner ()
const dictionary & dict () const
const dictionary & coeffDict () const
virtual void autoMap (const mapPolyMesh &)
virtual void inflow ()=0
Static Public Member Functions
static autoPtr< InflowBoundaryModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Detailed Description
template<class CloudType>
class Foam::InflowBoundaryModel< CloudType >
Templated inflow boundary model class.
Source files
InflowBoundaryModel.H
InflowBoundaryModel.C
InflowBoundaryModelNew.C
Definition at line 51 of file InflowBoundaryModel.H.
Constructor & Destructor Documentation
InflowBoundaryModel() [1/2]
template<class CloudType > InflowBoundaryModel (CloudType & owner)
Definition at line 26 of file InflowBoundaryModel.C.
InflowBoundaryModel() [2/2]
template<class CloudType > InflowBoundaryModel (const dictionary & dict, CloudType & owner, const word & type)
Definition at line 35 of file InflowBoundaryModel.C.
~InflowBoundaryModel()
template<class CloudType > ~InflowBoundaryModel () virtual
Definition at line 51 of file InflowBoundaryModel.C.
Member Function Documentation
TypeName()
template<class CloudType > TypeName ("InflowBoundaryModel< CloudType >")
declareRunTimeSelectionTable()
template<class CloudType > declareRunTimeSelectionTable (autoPtr , InflowBoundaryModel< CloudType > , dictionary , (const dictionary &dict, CloudType &owner) , (dict, owner))
New()
template<class CloudType > Foam::autoPtr< Foam::InflowBoundaryModel< CloudType > > New (const dictionary & dict, CloudType & owner) static
Definition at line 28 of file InflowBoundaryModelNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, Foam::Info, and PtrList< T >::PtrList().
owner() [1/2]
template<class CloudType > const CloudType & owner () const inline
Definition at line 58 of file InflowBoundaryModel.C.
owner() [2/2]
template<class CloudType > CloudType & owner () inline
Definition at line 65 of file InflowBoundaryModel.C.
dict()
template<class CloudType > const Foam::dictionary & dict () const inline
Definition at line 72 of file InflowBoundaryModel.C.
coeffDict()
template<class CloudType > const Foam::dictionary & coeffDict () const inline
Definition at line 79 of file InflowBoundaryModel.C.
Referenced by FreeStream< CloudType >::FreeStream().
autoMap()
template<class CloudType > virtual void autoMap (const mapPolyMesh &) inline virtual
Reimplemented in FreeStream< CloudType >.
Definition at line 127 of file InflowBoundaryModel.H.
inflow()
template<class CloudType > virtual void inflow () pure virtual
Implemented in FreeStream< CloudType >, and NoInflow< CloudType >.
The documentation for this class was generated from the following files:
src/lagrangian/DSMC/clouds/Templates/DSMCCloud/DSMCCloud.H
src/lagrangian/DSMC/submodels/InflowBoundaryModel/InflowBoundaryModel/InflowBoundaryModel.H
src/lagrangian/DSMC/submodels/InflowBoundaryModel/InflowBoundaryModel/InflowBoundaryModel.C
src/lagrangian/DSMC/submodels/InflowBoundaryModel/InflowBoundaryModel/InflowBoundaryModelNew.C