OpenFOAM: greyDiffusiveViewFactorFixedValueFvPatchScalarField Class Reference
greyDiffusiveViewFactorFixedValueFvPatchScalarField Class Reference
Boundary conditions » Thermophysical
This boundary condition provides a grey-diffuse condition for radiative heat flux, qr, for use with the view factor model.
#include <greyDiffusiveViewFactorFixedValueFvPatchScalarField.H>
Public Member Functions
TypeName ("greyDiffusiveRadiationViewFactor")
greyDiffusiveViewFactorFixedValueFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
greyDiffusiveViewFactorFixedValueFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
greyDiffusiveViewFactorFixedValueFvPatchScalarField (const greyDiffusiveViewFactorFixedValueFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
greyDiffusiveViewFactorFixedValueFvPatchScalarField (const greyDiffusiveViewFactorFixedValueFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
greyDiffusiveViewFactorFixedValueFvPatchScalarField (const greyDiffusiveViewFactorFixedValueFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
tmp< scalarField > qro (label bandI=0) const
virtual void updateCoeffs ()
virtual void autoMap (const fvPatchFieldMapper &)
virtual void rmap (const fvPatchScalarField &, const labelList &)
virtual void write (Ostream &) const
Detailed Description
This boundary condition provides a grey-diffuse condition for radiative heat flux, qr, for use with the view factor model.
Usage
Property Description Required Default value
qro external radiative heat flux yes
Example of the boundary condition specification:
    <patchName>
    {
        type            greyDiffusiveRadiationViewFactor;
        qro             uniform 0;
    }
See also
Foam::radiation::radiationModel Foam::radiation::viewFactor Foam::radiationCoupledBase Foam::fixedValueFvPatchField
Source files
greyDiffusiveViewFactorFixedValueFvPatchScalarField.H
greyDiffusiveViewFactorFixedValueFvPatchScalarField.C
Definition at line 84 of file greyDiffusiveViewFactorFixedValueFvPatchScalarField.H.
Constructor & Destructor Documentation
greyDiffusiveViewFactorFixedValueFvPatchScalarField() [1/5]
greyDiffusiveViewFactorFixedValueFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 31 of file greyDiffusiveViewFactorFixedValueFvPatchScalarField.C.
greyDiffusiveViewFactorFixedValueFvPatchScalarField() [2/5]
greyDiffusiveViewFactorFixedValueFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 57 of file greyDiffusiveViewFactorFixedValueFvPatchScalarField.C.
References dict, fvPatchField< scalar >::operator=(), and Foam::Zero.
greyDiffusiveViewFactorFixedValueFvPatchScalarField() [3/5]
greyDiffusiveViewFactorFixedValueFvPatchScalarField (const greyDiffusiveViewFactorFixedValueFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 43 of file greyDiffusiveViewFactorFixedValueFvPatchScalarField.C.
greyDiffusiveViewFactorFixedValueFvPatchScalarField() [4/5]
greyDiffusiveViewFactorFixedValueFvPatchScalarField (const greyDiffusiveViewFactorFixedValueFvPatchScalarField & ptf)
Definition at line 75 of file greyDiffusiveViewFactorFixedValueFvPatchScalarField.C.
greyDiffusiveViewFactorFixedValueFvPatchScalarField() [5/5]
greyDiffusiveViewFactorFixedValueFvPatchScalarField (const greyDiffusiveViewFactorFixedValueFvPatchScalarField & ptf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 86 of file greyDiffusiveViewFactorFixedValueFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("greyDiffusiveRadiationViewFactor")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 134 of file greyDiffusiveViewFactorFixedValueFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 150 of file greyDiffusiveViewFactorFixedValueFvPatchScalarField.H.
qro()
Foam::tmp< Foam::scalarField > qro (label bandI = 0) const
Definition at line 151 of file greyDiffusiveViewFactorFixedValueFvPatchScalarField.C.
References Foam::name(), and radiation().
updateCoeffs()
void updateCoeffs () virtual
Definition at line 126 of file greyDiffusiveViewFactorFixedValueFvPatchScalarField.C.
References Foam::endl(), Foam::gAverage(), Foam::gMax(), Foam::gMin(), Foam::gSum(), and Foam::Info.
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Definition at line 100 of file greyDiffusiveViewFactorFixedValueFvPatchScalarField.C.
rmap()
void rmap (const fvPatchScalarField & ptf, const labelList & addr) virtual
Definition at line 111 of file greyDiffusiveViewFactorFixedValueFvPatchScalarField.C.
write()
void write (Ostream & os) const virtual
Definition at line 181 of file greyDiffusiveViewFactorFixedValueFvPatchScalarField.C.
References os(), and fixedValueFvPatchField< Type >::write().
The documentation for this class was generated from the following files:
src/thermophysicalModels/radiation/derivedFvPatchFields/greyDiffusiveViewFactor/greyDiffusiveViewFactorFixedValueFvPatchScalarField.H
src/thermophysicalModels/radiation/derivedFvPatchFields/greyDiffusiveViewFactor/greyDiffusiveViewFactorFixedValueFvPatchScalarField.C