OpenFOAM: Square< Type > Class Template Reference
Square< Type > Class Template Reference
A templated square-wave function with support for offset, etc.
#include <Square.H>
Public Member Functions
TypeName ("square")
void operator= (const Square< Type > &)=delete
Square (const word &entryName, const dictionary &dict, const objectRegistry *obrPtr=nullptr)
Square (const Square< Type > &rhs)
virtual tmp< Function1< Type > > clone () const
virtual ~Square ()=default
virtual Type value (const scalar t) const
virtual void writeData (Ostream &os) const
virtual void writeEntries (Ostream &os) const
Public Member Functions inherited from Sine< Type >
TypeName ("sine")
void operator= (const Sine< Type > &)=delete
Sine (const word &entryName, const dictionary &dict, const objectRegistry *obrPtr=nullptr)
Sine (const Sine< Type > &rhs)
virtual ~Sine ()=default
virtual void userTimeToTime (const Time &t)
Public Member Functions inherited from Function1< Type >
TypeName ("Function1") declareRunTimeSelectionTable(autoPtr
Function1 (const word &entryName, const objectRegistry *obrPtr=nullptr)
Function1 (const word &entryName, const dictionary &dict, const objectRegistry *obrPtr=nullptr)
Function1 (const Function1< Type > &rhs)
virtual ~Function1 ()=default
virtual bool constant () const
virtual bool good () const
virtual tmp< Field< Type > > value (const scalarField &x) const
virtual Type integrate (const scalar x1, const scalar x2) const
virtual tmp< Field< Type > > integrate (const scalarField &x1, const scalarField &x2) const
Public Member Functions inherited from function1Base
function1Base (const word &entryName, const objectRegistry *obrPtr=nullptr)
function1Base (const word &entryName, const dictionary &dict, const objectRegistry *obrPtr=nullptr)
function1Base (const function1Base &rhs)
virtual ~function1Base ()
const word & name () const noexcept
const objectRegistry * whichDb () const noexcept
void resetDb (const objectRegistry *obrPtr=nullptr) noexcept
void resetDb (const objectRegistry &db) noexcept
const objectRegistry & obr () const
bool isTime () const noexcept
const Time & time () const
template<class MeshType >
const MeshType & mesh (const word &regionName=word::null) const
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Additional Inherited Members
Public Types inherited from Function1< Type >
typedef Type returnType
Static Public Member Functions inherited from Function1< Type >
static autoPtr< Function1< Type > > New (const word &entryName, const dictionary &dict, const word &redirectType, const objectRegistry *obrPtr=nullptr, const bool mandatory=true)
static autoPtr< Function1< Type > > NewCompat (const word &entryName, std::initializer_list< std::pair< const char *, int > > compat, const dictionary &dict, const word &redirectType=word::null, const objectRegistry *obrPtr=nullptr, const bool mandatory=true)
static autoPtr< Function1< Type > > New (const word &entryName, const dictionary &dict, const objectRegistry *obrPtr=nullptr, const bool mandatory=true)
static autoPtr< Function1< Type > > NewIfPresent (const word &entryName, const dictionary &dict, const word &redirectType, const objectRegistry *obrPtr=nullptr)
static autoPtr< Function1< Type > > NewIfPresent (const word &entryName, const dictionary &dict, const objectRegistry *obrPtr=nullptr)
static refPtr< Function1< Type > > New (HashPtrTable< Function1< Type > > &cache, const word &entryName, const dictionary &dict, enum keyType::option matchOpt=keyType::LITERAL, const objectRegistry *obrPtr=nullptr, const bool mandatory=true)
Public Attributes inherited from Function1< Type >
Function1
dictionary
const word & entryName
const word const dictionary & dict
const word const dictionary const objectRegistry * obrPtr
const word const dictionary const objectRegistry entryName
const word const dictionary const objectRegistry dict
const word const dictionary const objectRegistry obrPtr
Protected Member Functions inherited from Sine< Type >
scalar cycle (const scalar t) const
scalar cosForm (const scalar t) const
scalar sinForm (const scalar t) const
scalar squareForm (const scalar t, const scalar posFrac) const
Type cosValue (const scalar t) const
Type sinValue (const scalar t) const
Type squareValue (const scalar t, const scalar posFrac) const
Protected Member Functions inherited from Function1< Type >
void operator= (const Function1< Type > &)=delete
Protected Member Functions inherited from function1Base
void operator= (const function1Base &)=delete
Protected Attributes inherited from Sine< Type >
scalar t0_
autoPtr< Function1< scalar > > amplitude_
autoPtr< Function1< scalar > > period_
autoPtr< Function1< scalar > > frequency_
autoPtr< Function1< Type > > scale_
autoPtr< Function1< Type > > level_
Protected Attributes inherited from function1Base
const word name_
const objectRegistry * obrPtr_
Detailed Description
template<class Type>
class Foam::Function1Types::Square< Type >
A templated square-wave function with support for offset, etc.
The wave period can be specified directly
Or it can be specified by the frequency
where
is the square-wave function in range with a mark/space ratio of
= Description Units
= Amplitude -
= Frequency [1/s]
= Period [s]
= Type scale factor -
= Type offset level -
= Time [s]
= Start time offset [s]
= mark/space ratio -
The dictionary specification would typically resemble this:
    entry1
    {
        type        square;
        frequency   10;
        amplitude   0.1;
        // A scalar Function1
        scale       2e-6;
        level       2e-6;
    }
    entry2
    {
        type        square;
        frequency   10;
        // A vector Function1
        scale       (1 0.1 0);
        level       (10 1 0);
    }
where the entries mean:
Property Description Type Reqd Default
type Function type: square word yes
amplitude Amplitude Function1<scalar> no 1
frequency Frequency [1/s] Function1<scalar> or period
period Period [s] Function1<scalar> or frequency
scale Scale factor (Type) Function1<Type> yes
level Offset level (Type) Function1<Type> yes
t0 Start time offset scalar no 0
mark Positive amount scalar no 1
space Negative amount scalar no 1
Note
For slow oscillations it can be more intuitive to specify the period.
Definition at line 219 of file Square.H.
Constructor & Destructor Documentation
Square() [1/2]
template<class Type > Square (const word & entryName, const dictionary & dict, const objectRegistry * obrPtr = nullptr)
Definition at line 27 of file Square.C.
Square() [2/2]
template<class Type > Square (const Square< Type > & rhs) explicit
Definition at line 41 of file Square.C.
~Square()
template<class Type > virtual ~Square () virtual default
Member Function Documentation
TypeName()
template<class Type > TypeName ("square")
operator=()
template<class Type > void operator= (const Square< Type > &) delete
clone()
template<class Type > virtual tmp< Function1< Type > > clone () const inline virtual
Reimplemented from Sine< Type >.
Definition at line 257 of file Square.H.
value()
template<class Type > virtual Type value (const scalar t) const inline virtual
Reimplemented from Sine< Type >.
Definition at line 270 of file Square.H.
References Sine< Type >::squareValue().
writeData()
template<class Type > void writeData (Ostream & os) const virtual
Reimplemented from Sine< Type >.
Definition at line 61 of file Square.C.
References Foam::name(), os(), and Function1< Type >::writeData().
writeEntries()
template<class Type > void writeEntries (Ostream & os) const virtual
Reimplemented from Sine< Type >.
Definition at line 52 of file Square.C.
References os(), and Sine< Type >::writeEntries().
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/functions/Function1/Square/Square.H
src/OpenFOAM/primitives/functions/Function1/Square/Square.C