OpenFOAM: nutkFilmWallFunctionFvPatchScalarField Class Reference
nutkFilmWallFunctionFvPatchScalarField Class Reference
Boundary conditions » Region boundary conditions » Surface film boundary conditions | Turbulence models » Compressible turbulence » Boundary conditions » Wall functions
This boundary condition provides a turbulent viscosity condition when using wall functions, based on turbulence kinetic energy, for use with surface film models.
#include <nutkFilmWallFunctionFvPatchScalarField.H>
Public Member Functions
TypeName ("nutkFilmWallFunction")
nutkFilmWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
nutkFilmWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
nutkFilmWallFunctionFvPatchScalarField (const nutkFilmWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
nutkFilmWallFunctionFvPatchScalarField (const nutkFilmWallFunctionFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
nutkFilmWallFunctionFvPatchScalarField (const nutkFilmWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual tmp< scalarField > yPlus () const
virtual void write (Ostream &os) const
Public Member Functions inherited from nutkWallFunctionFvPatchScalarField
TypeName ("nutkWallFunction")
nutkWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
nutkWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
nutkWallFunctionFvPatchScalarField (const nutkWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
nutkWallFunctionFvPatchScalarField (const nutkWallFunctionFvPatchScalarField &)
nutkWallFunctionFvPatchScalarField (const nutkWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Public Member Functions inherited from nutWallFunctionFvPatchScalarField
TypeName ("nutWallFunction")
nutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
nutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &)
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
const wallFunctionCoefficients & wallCoeffs () const noexcept
virtual void updateCoeffs ()
Protected Member Functions
virtual tmp< scalarField > calcNut () const
tmp< scalarField > calcUTau (const scalarField &magGradU) const
void writeLocalEntries (Ostream &) const
Protected Member Functions inherited from nutkWallFunctionFvPatchScalarField
void writeLocalEntries (Ostream &) const
Protected Member Functions inherited from nutWallFunctionFvPatchScalarField
virtual const volVectorField & U (const turbulenceModel &turb) const
virtual void checkType ()
void writeLocalEntries (Ostream &) const
Protected Attributes
word filmRegionName_
scalar B_
scalar yPlusCrit_
Protected Attributes inherited from nutWallFunctionFvPatchScalarField
word UName_
wallFunctionCoefficients wallCoeffs_
Additional Inherited Members
Static Public Member Functions inherited from nutWallFunctionFvPatchScalarField
static const nutWallFunctionFvPatchScalarField & nutw (const turbulenceModel &turbModel, const label patchi)
Detailed Description
This boundary condition provides a turbulent viscosity condition when using wall functions, based on turbulence kinetic energy, for use with surface film models.
Usage
Example of the boundary condition specification:
<patchName>
{
    // Mandatory entries
    type            nutkFilmWallFunction;
    // Optional entries
    filmRegion      <word>;
    B               <scalar>;
    yPlusCrit       <scalar>;
    // Inherited entries
    ...
}
where the entries mean:
Property Description Type Reqd Deflt
type Type name: alphatFilmWallFunction word yes -
filmRegion Name of film region word no surfaceFilmProperties
B Model coefficient scalar no 5.5
yPlusCrit Critical y+ for transition to turbulence scalar no 11.5
The inherited entries are elaborated in:
nutkWallFunctionFvPatchScalarField.H
Source files
nutkFilmWallFunctionFvPatchScalarField.H
nutkFilmWallFunctionFvPatchScalarField.C
Definition at line 116 of file nutkFilmWallFunctionFvPatchScalarField.H.
Constructor & Destructor Documentation
nutkFilmWallFunctionFvPatchScalarField() [1/5]
nutkFilmWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 169 of file nutkFilmWallFunctionFvPatchScalarField.C.
nutkFilmWallFunctionFvPatchScalarField() [2/5]
nutkFilmWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 197 of file nutkFilmWallFunctionFvPatchScalarField.C.
nutkFilmWallFunctionFvPatchScalarField() [3/5]
nutkFilmWallFunctionFvPatchScalarField (const nutkFilmWallFunctionFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 182 of file nutkFilmWallFunctionFvPatchScalarField.C.
nutkFilmWallFunctionFvPatchScalarField() [4/5]
nutkFilmWallFunctionFvPatchScalarField (const nutkFilmWallFunctionFvPatchScalarField & wfpsf)
Definition at line 214 of file nutkFilmWallFunctionFvPatchScalarField.C.
nutkFilmWallFunctionFvPatchScalarField() [5/5]
nutkFilmWallFunctionFvPatchScalarField (const nutkFilmWallFunctionFvPatchScalarField & wfpsf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 226 of file nutkFilmWallFunctionFvPatchScalarField.C.
Member Function Documentation
calcNut()
tmp< scalarField > calcNut () const protected virtual
Reimplemented from nutkWallFunctionFvPatchScalarField.
Definition at line 124 of file nutkFilmWallFunctionFvPatchScalarField.C.
References nutkFilmWallFunctionFvPatchScalarField::calcUTau(), IOobject::groupName(), Foam::mag(), Foam::max(), turbulenceModel::propertiesName, and Foam::sqr().
calcUTau()
tmp< scalarField > calcUTau (const scalarField & magGradU) const protected
Definition at line 42 of file nutkFilmWallFunctionFvPatchScalarField.C.
References nutkFilmWallFunctionFvPatchScalarField::B_, wallFunctionCoefficients::Cmu(), Foam::exp(), nutkFilmWallFunctionFvPatchScalarField::filmRegionName_, forAll, IOobject::groupName(), k, wallFunctionCoefficients::kappa(), Foam::max(), Foam::min(), tmp< T >::New(), Foam::pow(), Foam::pow025(), turbulenceModel::propertiesName, Foam::sqrt(), uTau, nutWallFunctionFvPatchScalarField::wallCoeffs_, y, nutkFilmWallFunctionFvPatchScalarField::yPlus(), nutkFilmWallFunctionFvPatchScalarField::yPlusCrit_, and Foam::Zero.
Referenced by nutkFilmWallFunctionFvPatchScalarField::calcNut(), and nutkFilmWallFunctionFvPatchScalarField::yPlus().
writeLocalEntries()
void writeLocalEntries (Ostream & os) const protected
Definition at line 151 of file nutkFilmWallFunctionFvPatchScalarField.C.
References nutkFilmWallFunctionFvPatchScalarField::B_, nutkFilmWallFunctionFvPatchScalarField::filmRegionName_, os(), and nutkFilmWallFunctionFvPatchScalarField::yPlusCrit_.
Referenced by nutkFilmWallFunctionFvPatchScalarField::write().
TypeName()
TypeName ("nutkFilmWallFunction")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Reimplemented from nutkWallFunctionFvPatchScalarField.
Definition at line 187 of file nutkFilmWallFunctionFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Reimplemented from nutkWallFunctionFvPatchScalarField.
Definition at line 203 of file nutkFilmWallFunctionFvPatchScalarField.H.
yPlus()
tmp< scalarField > yPlus () const virtual
Reimplemented from nutkWallFunctionFvPatchScalarField.
Definition at line 241 of file nutkFilmWallFunctionFvPatchScalarField.C.
References nutkFilmWallFunctionFvPatchScalarField::calcUTau(), IOobject::groupName(), Foam::mag(), turbulenceModel::propertiesName, fvPatchField< Type >::snGrad(), and y.
Referenced by nutkFilmWallFunctionFvPatchScalarField::calcUTau().
write()
void write (Ostream & os) const virtual
Reimplemented from nutkWallFunctionFvPatchScalarField.
Definition at line 265 of file nutkFilmWallFunctionFvPatchScalarField.C.
References os(), nutWallFunctionFvPatchScalarField::write(), nutkFilmWallFunctionFvPatchScalarField::writeLocalEntries(), and fvPatchField< Type >::writeValueEntry().
Member Data Documentation
filmRegionName_
word filmRegionName_ protected
Definition at line 125 of file nutkFilmWallFunctionFvPatchScalarField.H.
Referenced by nutkFilmWallFunctionFvPatchScalarField::calcUTau(), and nutkFilmWallFunctionFvPatchScalarField::writeLocalEntries().
B_
scalar B_ protected
Definition at line 128 of file nutkFilmWallFunctionFvPatchScalarField.H.
Referenced by nutkFilmWallFunctionFvPatchScalarField::calcUTau(), and nutkFilmWallFunctionFvPatchScalarField::writeLocalEntries().
yPlusCrit_
scalar yPlusCrit_ protected
Definition at line 131 of file nutkFilmWallFunctionFvPatchScalarField.H.
Referenced by nutkFilmWallFunctionFvPatchScalarField::calcUTau(), and nutkFilmWallFunctionFvPatchScalarField::writeLocalEntries().
The documentation for this class was generated from the following files:
src/regionModels/surfaceFilmModels/derivedFvPatchFields/wallFunctions/nutkFilmWallFunction/nutkFilmWallFunctionFvPatchScalarField.H
src/regionModels/surfaceFilmModels/derivedFvPatchFields/wallFunctions/nutkFilmWallFunction/nutkFilmWallFunctionFvPatchScalarField.C