OpenFOAM: variableHeightFlowRateFvPatchScalarField Class Reference
variableHeightFlowRateFvPatchScalarField Class Reference
Boundary conditions » Inlet
This boundary condition provides a phase fraction condition based on the local flow conditions, whereby the values are constrained to lay between user-specified upper and lower bounds. The behaviour is described by:
#include <variableHeightFlowRateFvPatchField.H>
Public Member Functions
TypeName ("variableHeightFlowRate")
variableHeightFlowRateFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
variableHeightFlowRateFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
variableHeightFlowRateFvPatchScalarField (const variableHeightFlowRateFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
variableHeightFlowRateFvPatchScalarField (const variableHeightFlowRateFvPatchScalarField &)
virtual tmp< fvPatchField< scalar > > clone () const
variableHeightFlowRateFvPatchScalarField (const variableHeightFlowRateFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchField< scalar > > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Protected Attributes
word phiName_
scalar lowerBound_
scalar upperBound_
Detailed Description
This boundary condition provides a phase fraction condition based on the local flow conditions, whereby the values are constrained to lay between user-specified upper and lower bounds. The behaviour is described by:
if alpha > upperBound:
apply a fixed value condition, with a uniform level of the upper bound
if lower bound <= alpha <= upper bound:
apply a zero-gradient condition
if alpha < lowerBound:
apply a fixed value condition, with a uniform level of the lower bound
Usage
Property Description Required Default value
phi flux field name no phi
lowerBound lower bound for clipping yes
upperBound upper bound for clipping yes
Example of the boundary condition specification:
    <patchName>
    {
        type            variableHeightFlowRate;
        lowerBound      0.0;
        upperBound      0.9;
        value           uniform 0;
    }
Source files
variableHeightFlowRateFvPatchField.H
variableHeightFlowRateFvPatchScalarField.C
Definition at line 99 of file variableHeightFlowRateFvPatchField.H.
Constructor & Destructor Documentation
variableHeightFlowRateFvPatchScalarField() [1/5]
variableHeightFlowRateFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 30 of file variableHeightFlowRateFvPatchField.C.
variableHeightFlowRateFvPatchScalarField() [2/5]
variableHeightFlowRateFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 64 of file variableHeightFlowRateFvPatchField.C.
References dict, and fvPatchFieldBase::readDict().
variableHeightFlowRateFvPatchScalarField() [3/5]
variableHeightFlowRateFvPatchScalarField (const variableHeightFlowRateFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 48 of file variableHeightFlowRateFvPatchField.C.
variableHeightFlowRateFvPatchScalarField() [4/5]
variableHeightFlowRateFvPatchScalarField (const variableHeightFlowRateFvPatchScalarField & ptf)
Definition at line 91 of file variableHeightFlowRateFvPatchField.C.
variableHeightFlowRateFvPatchScalarField() [5/5]
variableHeightFlowRateFvPatchScalarField (const variableHeightFlowRateFvPatchScalarField & ptf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 104 of file variableHeightFlowRateFvPatchField.C.
Member Function Documentation
TypeName()
TypeName ("variableHeightFlowRate")
clone() [1/2]
virtual tmp< fvPatchField< scalar > > clone () const inline virtual
Definition at line 158 of file variableHeightFlowRateFvPatchField.H.
clone() [2/2]
virtual tmp< fvPatchField< scalar > > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 174 of file variableHeightFlowRateFvPatchField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 120 of file variableHeightFlowRateFvPatchField.C.
References forAll.
write()
void write (Ostream & os) const virtual
Definition at line 162 of file variableHeightFlowRateFvPatchField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntry(), Ostream::writeEntryIfDifferent(), and fvPatchField< Type >::writeValueEntry().
Member Data Documentation
phiName_
word phiName_ protected
Definition at line 109 of file variableHeightFlowRateFvPatchField.H.
lowerBound_
scalar lowerBound_ protected
Definition at line 112 of file variableHeightFlowRateFvPatchField.H.
upperBound_
scalar upperBound_ protected
Definition at line 115 of file variableHeightFlowRateFvPatchField.H.
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/variableHeightFlowRate/variableHeightFlowRateFvPatchField.H
src/finiteVolume/fields/fvPatchFields/derived/variableHeightFlowRate/variableHeightFlowRateFvPatchField.C