OpenFOAM: interRegionExplicitPorositySource Class Reference
interRegionExplicitPorositySource Class Reference
Numerics » Finite volume Options » Sources
Applies inter-region explicit porosity source.
#include <interRegionExplicitPorositySource.H>
Public Member Functions
TypeName ("interRegionExplicitPorositySource")
interRegionExplicitPorositySource (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
interRegionExplicitPorositySource (const interRegionExplicitPorositySource &)=delete
void operator= (const interRegionExplicitPorositySource &)=delete
virtual ~interRegionExplicitPorositySource ()=default
virtual void addSup (fvMatrix< vector > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldi)
virtual bool read (const dictionary &dict)
Public Member Functions inherited from interRegionOption
TypeName ("interRegionOption")
interRegionOption (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
interRegionOption (const interRegionOption &)=delete
void operator= (const interRegionOption &)=delete
virtual ~interRegionOption ()=default
const word & nbrRegionName () const
const meshToMesh & meshInterp () const
Public Member Functions inherited from option
TypeName ("option")
declareRunTimeSelectionTable (autoPtr, option, dictionary,(const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh),(name, modelType, dict, mesh))
option (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
autoPtr< option > clone () const
virtual ~option ()=default
const word & name () const noexcept
const fvMesh & mesh () const noexcept
const dictionary & coeffs () const noexcept
bool active () const noexcept
void setApplied (const label fieldi)
bool active (const bool on) noexcept
virtual bool isActive ()
virtual label applyToField (const word &fieldName) const
virtual void checkApplied () const
virtual void addSup (fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (fvMatrix< tensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< scalar > &eqn, const label fieldi)
virtual void constrain (fvMatrix< vector > &eqn, const label fieldi)
virtual void constrain (fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< tensor > &eqn, const label fieldi)
virtual void correct (volScalarField &field)
virtual void correct (volVectorField &field)
virtual void correct (volSphericalTensorField &field)
virtual void correct (volSymmTensorField &field)
virtual void correct (volTensorField &field)
virtual void postProcessSens (scalarField &sensField, const word &fieldName=word::null, const word &designVariablesName=word::null)
virtual void postProcessSens (vectorField &sensField, const word &fieldName=word::null, const word &designVariablesName=word::null)
virtual void postProcessSens (tensorField &sensField, const word &fieldName=word::null, const word &designVariablesName=word::null)
virtual void writeHeader (Ostream &) const
virtual void writeFooter (Ostream &) const
virtual void writeData (Ostream &) const
Protected Member Functions
void initialise ()
Protected Member Functions inherited from interRegionOption
void setMapper ()
Protected Member Functions inherited from option
void resetApplied ()
Protected Attributes
autoPtr< porosityModel > porosityPtr_
bool firstIter_
word UName_
word muName_
Protected Attributes inherited from interRegionOption
bool master_
word nbrRegionName_
autoPtr< meshToMesh > meshInterpPtr_
Protected Attributes inherited from option
const word name_
const word modelType_
const fvMesh & mesh_
dictionary dict_
dictionary coeffs_
wordList fieldNames_
List< bool > applied_
bool active_
Additional Inherited Members
Static Public Member Functions inherited from option
static autoPtr< option > New (const word &name, const dictionary &dict, const fvMesh &mesh)
Public Attributes inherited from option
bool log
Detailed Description
Applies inter-region explicit porosity source.
Usage
Minimal example by using constant/fvOptions:
interRegionExplicitPorositySource1
{
    // Mandatory entries (unmodifiable)
    type                 interRegionExplicitPorositySource;
    interRegionExplicitPorositySourceCoeffs
    {
        // Mandatory entries (unmodifiable)
        type     <porosityModel>;
        // Optional entries (runtime modifiable)
        U        U;
        mu       thermo:mu;
    }
    // Mandatory/Optional (inherited) entries
    ...
}
where the entries mean:
Property Description Type Reqd Dflt
type Type name: interRegionExplicitPorositySource word yes -
type Name of porosity model word yes -
U Name of operand velocity field word no U
mu Name of operand dynamic viscosity field word no thermo:mu
The inherited entries are elaborated in:
interRegionOption.H
Sources described by, for example using the DarcyForchheimer model:
    interRegionExplicitPorositySourceCoeffs
    {
        type            DarcyForchheimer;
        DarcyForchheimerCoeffs
        {
            d   d [0 -2 0 0 0 0 0] (5e7 -1000 -1000);
            f   f [0 -1 0 0 0 0 0] (0 0 0);
            coordinateSystem
            {
                origin  (0 0 0);
                e1      (0.70710678 0.70710678 0);
                e2      (0 0 1);
            }
        }
    }
Note
The porous region must be selected as a cellZone.
Source files
interRegionExplicitPorositySource.H
interRegionExplicitPorositySource.C
Definition at line 145 of file interRegionExplicitPorositySource.H.
Constructor & Destructor Documentation
interRegionExplicitPorositySource() [1/2]
interRegionExplicitPorositySource (const word & name, const word & modelType, const dictionary & dict, const fvMesh & mesh)
Definition at line 106 of file interRegionExplicitPorositySource.C.
References option::active_, option::fieldNames_, option::resetApplied(), List< T >::resize(), and interRegionExplicitPorositySource::UName_.
interRegionExplicitPorositySource() [2/2]
interRegionExplicitPorositySource (const interRegionExplicitPorositySource &) delete
~interRegionExplicitPorositySource()
virtual ~interRegionExplicitPorositySource () virtual default
Member Function Documentation
initialise()
void initialise () protected
Definition at line 46 of file interRegionExplicitPorositySource.C.
References Foam::abort(), ZoneMesh< ZoneType, MeshType >::clearAddressing(), option::coeffs_, Foam::FatalError, FatalErrorInFunction, interRegionExplicitPorositySource::firstIter_, option::mesh_, option::name_, interRegionOption::nbrRegionName_, porosityModel::New(), interRegionExplicitPorositySource::porosityPtr_, PtrList< T >::set(), PtrList< T >::setSize(), and UPtrList< T >::size().
TypeName()
TypeName ("interRegionExplicitPorositySource")
operator=()
void operator= (const interRegionExplicitPorositySource &) delete
addSup() [1/2]
void addSup (fvMatrix< vector > & eqn, const label fieldi) virtual
Reimplemented from option.
Definition at line 130 of file interRegionExplicitPorositySource.C.
References IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, PtrList< T >::setSize(), UPtrList< T >::size(), U, and Foam::Zero.
addSup() [2/2]
void addSup (const volScalarField & rho, fvMatrix< vector > & eqn, const label fieldi) virtual
Reimplemented from option.
Definition at line 183 of file interRegionExplicitPorositySource.C.
References Foam::dimDensity, Foam::dimViscosity, mu, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, rho, PtrList< T >::setSize(), UPtrList< T >::size(), U, and Foam::Zero.
read()
bool read (const dictionary & dict) virtual
Reimplemented from interRegionOption.
Definition at line 283 of file interRegionExplicitPorositySource.C.
References dict, and interRegionOption::read().
Member Data Documentation
porosityPtr_
autoPtr<porosityModel> porosityPtr_ protected
Definition at line 154 of file interRegionExplicitPorositySource.H.
Referenced by interRegionExplicitPorositySource::initialise().
firstIter_
bool firstIter_ protected
Definition at line 157 of file interRegionExplicitPorositySource.H.
Referenced by interRegionExplicitPorositySource::initialise().
UName_
word UName_ protected
Definition at line 160 of file interRegionExplicitPorositySource.H.
Referenced by interRegionExplicitPorositySource::interRegionExplicitPorositySource().
muName_
word muName_ protected
Definition at line 163 of file interRegionExplicitPorositySource.H.
The documentation for this class was generated from the following files:
src/fvOptions/sources/interRegion/interRegionExplicitPorositySource/interRegionExplicitPorositySource.H
src/fvOptions/sources/interRegion/interRegionExplicitPorositySource/interRegionExplicitPorositySource.C