OpenFOAM: perfectInterface Class Reference
perfectInterface Class Reference
Hack of attachDetach to couple patches when they perfectly align. Does not decouple. Used by stitchMesh app. Does geometric matching.
#include <perfectInterface.H>
Public Member Functions
TypeName ("perfectInterface")
perfectInterface (const word &name, const label index, const polyTopoChanger &mme, const word &faceZoneName, const word &masterPatchName, const word &slavePatchName)
perfectInterface (const word &name, const dictionary &dict, const label index, const polyTopoChanger &mme)
virtual ~perfectInterface ()=default
virtual bool changeTopology () const
virtual void setRefinement (polyTopoChange &) const
virtual void setRefinement (const indirectPrimitivePatch &pp0, const indirectPrimitivePatch &pp1, polyTopoChange &) const
virtual void modifyMotionPoints (pointField &motionPoints) const
virtual void updateMesh (const mapPolyMesh &)
virtual void write (Ostream &) const
virtual void writeDict (Ostream &) const
Public Member Functions inherited from polyMeshModifier
TypeName ("meshModifier")
declareRunTimeSelectionTable (autoPtr, polyMeshModifier, dictionary,(const word &name, const dictionary &dict, const label index, const polyTopoChanger &mme),(name, dict, index, mme))
polyMeshModifier (const word &name, const label index, const polyTopoChanger &mme, const bool act)
virtual ~polyMeshModifier ()=default
const word & name () const
label index () const
const polyTopoChanger & topoChanger () const
Switch active () const
void enable () const
void disable () const
Additional Inherited Members
Static Public Member Functions inherited from polyMeshModifier
static autoPtr< polyMeshModifier > New (const word &name, const dictionary &dict, const label index, const polyTopoChanger &mme)
Detailed Description
Hack of attachDetach to couple patches when they perfectly align. Does not decouple. Used by stitchMesh app. Does geometric matching.
Source files
perfectInterface.H
perfectInterface.C
Definition at line 54 of file perfectInterface.H.
Constructor & Destructor Documentation
perfectInterface() [1/2]
perfectInterface (const word & name, const label index, const polyTopoChanger & mme, const word & faceZoneName, const word & masterPatchName, const word & slavePatchName)
Definition at line 79 of file perfectInterface.C.
perfectInterface() [2/2]
perfectInterface (const word & name, const dictionary & dict, const label index, const polyTopoChanger & mme)
Definition at line 96 of file perfectInterface.C.
~perfectInterface()
virtual ~perfectInterface () virtual default
Member Function Documentation
TypeName()
TypeName ("perfectInterface")
changeTopology()
bool changeTopology () const virtual
Implements polyMeshModifier.
Definition at line 125 of file perfectInterface.C.
References Foam::endl(), Foam::name(), and Foam::Pout.
setRefinement() [1/2]
void setRefinement (polyTopoChange & ref) const virtual
Implements polyMeshModifier.
Definition at line 420 of file perfectInterface.C.
References polyMesh::boundaryMesh(), Foam::endl(), polyMesh::faces(), Foam::identity(), mesh, Foam::name(), patches, polyMesh::points(), Foam::Pout, and ref().
setRefinement() [2/2]
void setRefinement (const indirectPrimitivePatch & pp0, const indirectPrimitivePatch & pp1, polyTopoChange & ref) const virtual
Definition at line 147 of file perfectInterface.C.
References polyMesh::boundaryMesh(), Foam::endl(), Foam::exit(), f(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), polyMesh::faces(), polyMesh::faceZones(), Foam::FatalError, FatalErrorInFunction, forAll, primitiveMesh::isInternalFace(), Foam::mag(), Foam::matchPoints(), mesh, Foam::min(), patches, pFaces, primitiveMesh::pointFaces(), polyMesh::points(), Foam::Pout, ref(), face::reverseFace(), UPtrList< T >::size(), UList< T >::size(), and WarningInFunction.
modifyMotionPoints()
void modifyMotionPoints (pointField & motionPoints) const virtual
Implements polyMeshModifier.
Definition at line 461 of file perfectInterface.C.
updateMesh()
void updateMesh (const mapPolyMesh & morphMap) virtual
Implements polyMeshModifier.
Definition at line 468 of file perfectInterface.C.
References polyMesh::boundaryMesh(), polyMesh::faceZones(), mesh, and dynamicFvMesh::update().
write()
void write (Ostream & os) const virtual
Implements polyMeshModifier.
Definition at line 479 of file perfectInterface.C.
References Foam::endl(), Foam::name(), Foam::nl, os(), and Foam::type().
writeDict()
void writeDict (Ostream & os) const virtual
Implements polyMeshModifier.
Definition at line 489 of file perfectInterface.C.
References Ostream::beginBlock(), Ostream::endBlock(), Foam::name(), Foam::nl, os(), Foam::type(), and Ostream::writeEntry().
The documentation for this class was generated from the following files:
src/dynamicMesh/perfectInterface/perfectInterface.H
src/dynamicMesh/perfectInterface/perfectInterface.C