OpenFOAM: NonEquilibriumReversibleReaction< ReactionType, ReactionThermo, ReactionRate > Class Template Reference
NonEquilibriumReversibleReaction< ReactionType, ReactionThermo, ReactionRate > Class Template Reference
Thermophysical models » Specie » Reactions
Simple extension of Reaction to handle reversible reactions using equilibrium thermodynamics.
#include <NonEquilibriumReversibleReaction.H>
Public Member Functions
TypeName ("nonEquilibriumReversible")
NonEquilibriumReversibleReaction (const ReactionType< ReactionThermo > &reaction, const ReactionRate &forwardReactionRate, const ReactionRate &reverseReactionRate)
NonEquilibriumReversibleReaction (const NonEquilibriumReversibleReaction< ReactionType, ReactionThermo, ReactionRate > &, const speciesTable &species)
NonEquilibriumReversibleReaction (const speciesTable &species, const ReactionTable< ReactionThermo > &thermoDatabase, const dictionary &dict)
virtual autoPtr< ReactionType< ReactionThermo > > clone () const
virtual autoPtr< ReactionType< ReactionThermo > > clone (const speciesTable &species) const
virtual ~NonEquilibriumReversibleReaction ()=default
virtual scalar kf (const scalar p, const scalar T, const scalarField &c) const
virtual scalar kr (const scalar kfwd, const scalar p, const scalar T, const scalarField &c) const
virtual scalar kr (const scalar p, const scalar T, const scalarField &c) const
virtual void write (Ostream &os) const
Detailed Description
template<template< class > class ReactionType, class ReactionThermo, class ReactionRate>
class Foam::NonEquilibriumReversibleReaction< ReactionType, ReactionThermo, ReactionRate >
Simple extension of Reaction to handle reversible reactions using equilibrium thermodynamics.
Source files
NonEquilibriumReversibleReaction.H
NonEquilibriumReversibleReaction.C
Definition at line 57 of file NonEquilibriumReversibleReaction.H.
Constructor & Destructor Documentation
NonEquilibriumReversibleReaction() [1/3]
template<template< class > class ReactionType, class ReactionThermo , class ReactionRate > NonEquilibriumReversibleReaction (const ReactionType< ReactionThermo > & reaction, const ReactionRate & forwardReactionRate, const ReactionRate & reverseReactionRate)
Definition at line 37 of file NonEquilibriumReversibleReaction.C.
NonEquilibriumReversibleReaction() [2/3]
template<template< class > class ReactionType, class ReactionThermo , class ReactionRate > NonEquilibriumReversibleReaction (const NonEquilibriumReversibleReaction< ReactionType, ReactionThermo, ReactionRate > & nerr, const speciesTable & species)
Definition at line 87 of file NonEquilibriumReversibleReaction.C.
NonEquilibriumReversibleReaction() [3/3]
template<template< class > class ReactionType, class ReactionThermo , class ReactionRate > NonEquilibriumReversibleReaction (const speciesTable & species, const ReactionTable< ReactionThermo > & thermoDatabase, const dictionary & dict)
Definition at line 62 of file NonEquilibriumReversibleReaction.C.
~NonEquilibriumReversibleReaction()
template<template< class > class ReactionType, class ReactionThermo , class ReactionRate > virtual ~NonEquilibriumReversibleReaction () virtual default
Member Function Documentation
TypeName()
template<template< class > class ReactionType, class ReactionThermo , class ReactionRate > TypeName ("nonEquilibriumReversible")
clone() [1/2]
template<template< class > class ReactionType, class ReactionThermo , class ReactionRate > virtual autoPtr< ReactionType< ReactionThermo > > clone () const inline virtual
Definition at line 112 of file NonEquilibriumReversibleReaction.H.
clone() [2/2]
template<template< class > class ReactionType, class ReactionThermo , class ReactionRate > virtual autoPtr< ReactionType< ReactionThermo > > clone (const speciesTable & species) const inline virtual
Definition at line 122 of file NonEquilibriumReversibleReaction.H.
kf()
template<template< class > class ReactionType, class ReactionThermo , class ReactionRate > Foam::scalar kf (const scalar p, const scalar T, const scalarField & c) const virtual
Definition at line 119 of file NonEquilibriumReversibleReaction.C.
References p, and T.
kr() [1/2]
template<template< class > class ReactionType, class ReactionThermo , class ReactionRate > Foam::scalar kr (const scalar kfwd, const scalar p, const scalar T, const scalarField & c) const virtual
Definition at line 142 of file NonEquilibriumReversibleReaction.C.
References p, and T.
kr() [2/2]
template<template< class > class ReactionType, class ReactionThermo , class ReactionRate > Foam::scalar kr (const scalar p, const scalar T, const scalarField & c) const virtual
Definition at line 166 of file NonEquilibriumReversibleReaction.C.
References p, and T.
write()
template<template< class > class ReactionType, class ReactionThermo , class ReactionRate > void write (Ostream & os) const virtual
Definition at line 188 of file NonEquilibriumReversibleReaction.C.
References Ostream::beginBlock(), Ostream::endBlock(), and os().
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/reaction/Reactions/NonEquilibriumReversibleReaction/NonEquilibriumReversibleReaction.H
src/thermophysicalModels/specie/reaction/Reactions/NonEquilibriumReversibleReaction/NonEquilibriumReversibleReaction.C