OpenFOAM: fixedMultiPhaseHeatFluxFvPatchScalarField Class Reference
fixedMultiPhaseHeatFluxFvPatchScalarField Class Reference
Calculates a wall temperature that produces the specified overall wall heat flux across all the phases in an Eulerian multi-phase simulation.
#include <fixedMultiPhaseHeatFluxFvPatchScalarField.H>
Public Member Functions
TypeName ("fixedMultiPhaseHeatFlux")
fixedMultiPhaseHeatFluxFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
fixedMultiPhaseHeatFluxFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
fixedMultiPhaseHeatFluxFvPatchScalarField (const fixedMultiPhaseHeatFluxFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
fixedMultiPhaseHeatFluxFvPatchScalarField (const fixedMultiPhaseHeatFluxFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
fixedMultiPhaseHeatFluxFvPatchScalarField (const fixedMultiPhaseHeatFluxFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual void autoMap (const fvPatchFieldMapper &)
virtual void rmap (const fvPatchScalarField &, const labelList &)
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
Calculates a wall temperature that produces the specified overall wall heat flux across all the phases in an Eulerian multi-phase simulation.
Intended to be used with copiedFixedValue to ensure that phase wall temperature are consistent:
Set fixedMultiPhaseHeatFlux boundary for one of the phases
Use copiedFixedValue for all the other phases.
Usage
Example of the boundary condition specification:
<patchName>
{
    // Mandatory entries
    type            fixedMultiPhaseHeatFlux;
    q               <scalarField>;
    // Optional entries
    relax           <scalar>;
    Tmin            <scalar>;
    // Inherited entries
    ...
}
where the entries mean:
Property Description Type Reqd Deflt
type Type name: fixedMultiPhaseHeatFlux word yes -
q Heat power [W] or flux [W/m2] scalarField yes -
relax Relaxation factor scalar no 1.0
Tmin Minimum temperature limit [K] scalar no 273.0
The inherited entries are elaborated in:
fixedValueFvPatchFields.H
See also
Foam::fixedValueFvPatchField
Source files
fixedMultiPhaseHeatFluxFvPatchScalarField.H
fixedMultiPhaseHeatFluxFvPatchScalarField.C
Definition at line 117 of file fixedMultiPhaseHeatFluxFvPatchScalarField.H.
Constructor & Destructor Documentation
fixedMultiPhaseHeatFluxFvPatchScalarField() [1/5]
fixedMultiPhaseHeatFluxFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 33 of file fixedMultiPhaseHeatFluxFvPatchScalarField.C.
fixedMultiPhaseHeatFluxFvPatchScalarField() [2/5]
fixedMultiPhaseHeatFluxFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 47 of file fixedMultiPhaseHeatFluxFvPatchScalarField.C.
fixedMultiPhaseHeatFluxFvPatchScalarField() [3/5]
fixedMultiPhaseHeatFluxFvPatchScalarField (const fixedMultiPhaseHeatFluxFvPatchScalarField & psf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 62 of file fixedMultiPhaseHeatFluxFvPatchScalarField.C.
fixedMultiPhaseHeatFluxFvPatchScalarField() [4/5]
fixedMultiPhaseHeatFluxFvPatchScalarField (const fixedMultiPhaseHeatFluxFvPatchScalarField & psf)
Definition at line 78 of file fixedMultiPhaseHeatFluxFvPatchScalarField.C.
fixedMultiPhaseHeatFluxFvPatchScalarField() [5/5]
fixedMultiPhaseHeatFluxFvPatchScalarField (const fixedMultiPhaseHeatFluxFvPatchScalarField & psf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 91 of file fixedMultiPhaseHeatFluxFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("fixedMultiPhaseHeatFlux")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 174 of file fixedMultiPhaseHeatFluxFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 190 of file fixedMultiPhaseHeatFluxFvPatchScalarField.H.
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Definition at line 164 of file fixedMultiPhaseHeatFluxFvPatchScalarField.C.
rmap()
void rmap (const fvPatchScalarField & ptf, const labelList & addr) virtual
Definition at line 174 of file fixedMultiPhaseHeatFluxFvPatchScalarField.C.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 108 of file fixedMultiPhaseHeatFluxFvPatchScalarField.C.
References A, alpha, B, GeometricField< Type, PatchField, GeoMesh >::boundaryField(), Foam::endl(), fluid, forAll, Foam::gMax(), Foam::gMin(), Foam::gSum(), Foam::Info, kappaEff, Foam::max(), phase::name(), Foam::operator==(), phasei, phaseSystem::phases(), UPtrList< T >::size(), T, and Foam::Zero.
write()
void write (Ostream & os) const virtual
Definition at line 189 of file fixedMultiPhaseHeatFluxFvPatchScalarField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntry(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/fixedMultiPhaseHeatFlux/fixedMultiPhaseHeatFluxFvPatchScalarField.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/fixedMultiPhaseHeatFlux/fixedMultiPhaseHeatFluxFvPatchScalarField.C