OpenFOAM: argList Class Reference
argList Class Reference
Extract command arguments and options from the supplied argc and argv parameters.
#include <argList.H>
Public Member Functions
argList (int &argc, char **&argv, bool checkArgs=argList::argsMandatory(), bool checkOpts=true, bool initialise=true)
argList (const argList &args, const HashTable< string > &options, bool checkArgs=true, bool checkOpts=true, bool initialise=true)
virtual ~argList ()
void parse (bool checkArgs, bool checkOpts, bool initialise)
const word & executable () const noexcept
const string & commandLine () const noexcept
const fileName & rootPath () const noexcept
const fileName & caseName () const noexcept
const fileName & globalCaseName () const noexcept
fileName path () const
fileName globalPath () const
fileName relativePath (const fileName &input, const bool caseTag=false) const
const ParRunControl & runControl () const noexcept
bool distributed () const noexcept
int dryRun () const noexcept
int dryRun (const int level) noexcept
int verbose () const noexcept
int verbose (const int level) noexcept
bool allowFunctionObjects () const
bool allowLibs () const
dlLibraryTable & libs () const noexcept
label size () const noexcept
const stringList & args () const noexcept
stringList & args () noexcept
const HashTable< string > & options () const noexcept
HashTable< string > & options () noexcept
bool found (const word &optName) const
label count (const UList< word > &optionNames) const
label count (std::initializer_list< word > optionNames) const
ITstream lookup (const word &optName) const
template<class T >
T get (const label index) const
template<class T >
List< T > getList (const label index) const
template<class T = string>
T get (const word &optName) const
template<class T >
T getOrDefault (const word &optName, const T &deflt) const
template<class T >
List< T > getList (const word &optName, bool mandatory=true) const
template<class T >
bool readIfPresent (const word &optName, T &val) const
template<class T >
bool readIfPresent (const word &optName, T &val, const T &deflt) const
template<class T >
bool readListIfPresent (const word &optName, List< T > &list) const
template<class T , class Predicate >
bool readCheck (const word &optName, T &val, const Predicate &pred, bool mandatory=true) const
template<class T , class Predicate >
bool readCheckIfPresent (const word &optName, T &val, const Predicate &pred) const
template<class T , class Predicate >
T getCheck (const word &optName, const Predicate &pred) const
template<class T , class Predicate >
T getCheckOrDefault (const word &optName, const T &deflt, const Predicate &pred) const
bool setOption (const word &optName, const string &param="")
bool unsetOption (const word &optName)
void printCompat () const
void printNotes () const
void printUsage (bool full=true) const
void printMan () const
void displayDoc (bool source=false) const
bool check (bool checkArgs=argList::argsMandatory(), bool checkOpts=true) const
bool checkRootCase () const
const string & operator[] (const label index) const
const string & operator[] (const word &optName) const
template<class T = string>
T opt (const word &optName) const
template<class T >
T opt (const word &optName, const T &deflt) const
template<class T >
T get (const word &optName, const T &deflt) const
template<class T >
T lookupOrDefault (const word &optName, const T &deflt) const
const ParRunControl & parRunControl () const
template<class T >
T read (const label index) const
template<class T >
T argRead (const label index) const
bool optionFound (const word &optName) const
ITstream optionLookup (const word &optName) const
template<class T >
T optionRead (const word &optName) const
template<class T >
bool optionReadIfPresent (const word &optName, T &val) const
template<class T >
bool optionReadIfPresent (const word &optName, T &val, const T &deflt) const
template<class T >
T optionLookupOrDefault (const word &optName, const T &deflt) const
template<class T >
List< T > optionReadList (const word &optName) const
template<>
int32_t get (const label index) const
template<>
int64_t get (const label index) const
template<>
float get (const label index) const
template<>
double get (const label index) const
template<>
int32_t get (const word &optName) const
template<>
int64_t get (const word &optName) const
template<>
float get (const word &optName) const
template<>
double get (const word &optName) const
template<class T >
Foam::List< T > getList (const label index) const
template<class T >
Foam::List< T > getList (const word &optName, bool mandatory) const
Static Public Member Functions
static word envExecutable ()
static fileName envGlobalPath ()
static fileName envRelativePath (const fileName &input, const bool caseTag=false)
static void addArgument (const string &argName, const string &usage="")
static void addBoolOption (const word &optName, const string &usage="", bool advanced=false)
static void addOption (const word &optName, const string &param="", const string &usage="", bool advanced=false)
static void setAdvanced (const word &optName, bool advanced=true)
static void addOptionCompat (const word &optName, std::pair< const char *, int > compat)
static void ignoreOptionCompat (std::pair< const char *, int > compat, bool expectArg)
static void addUsage (const word &optName, const string &usage)
static void addNote (const string &note)
static void removeOption (const word &optName)
static void noMandatoryArgs ()
static bool argsMandatory ()
static void noBanner ()
static bool bannerEnabled ()
static void addDryRunOption (const string &usage, bool advanced=false)
static void addVerboseOption (const string &usage="", bool advanced=false)
static void noFunctionObjects (bool addWithOption=false)
static void noJobInfo ()
static void noLibs ()
static void noParallel ()
static void noCheckProcessorDirectories ()
static void parallelThreads_on ()
static bool postProcess (int argc, char *argv[])
static int verbose (int argc, char *argv[])
Static Public Attributes
static SLList< string > validArgs
static HashSet< string > advancedOptions
static HashTable< string > validOptions
static HashTable< string > validParOptions
static HashTable< std::pair< word, int > > validOptionsCompat
static HashTable< std::pair< bool, int > > ignoreOptionsCompat
static HashTable< string, label, Hash< label > > argUsage
static HashTable< string > optionUsage
static SLList< string > notes
static std::string::size_type usageMin = 20
static std::string::size_type usageMax = 80
static word postProcessOptionName
Detailed Description
Extract command arguments and options from the supplied argc and argv parameters.
Sequences with "(" ... ")" are transformed into a stringList. For example,
    program -listFiles \‍( *.txt \‍)
would create a stringList:
    ( "file1.txt" "file2.txt" ... "fileN.txt" )
The backslash-escaping is required to avoid interpretation by the shell.
Default command-line options:
-case <dir>
Select a case directory instead of the current working directory
-decomposeParDict <file>
Read decomposePar dictionary from specified location
-parallel
Specify case as a parallel job
-doc
Display the documentation in browser
-srcDoc
Display the source documentation in browser
-help
Print the usage
Additionally, the -noFunctionObjects and -postProcess options may be present for some solvers or utilities.
Environment variables set by argList or by Time:
FOAM_API
The value of foamVersion::api
FOAM_CASE
The path of the global case. It is the same for serial and parallel jobs.
FOAM_CASENAME
The name of the global case.
FOAM_EXECUTABLE
If not already present in the calling environment, it is set to the name portion of the calling executable.
FOAM_APPLICATION
If not already present in the calling environment, it is set to the value of the application entry (from controlDict) if that entry is present.
The value of the FOAM_APPLICATION may be inconsistent if the value of the application entry is adjusted during runtime.
Note
The document browser used is defined by the FOAM_DOC_BROWSER environment variable or the Documentation/docBrowser entry in the <etc>/controlDict file. The %f token is used as a placeholder for the file name.
The valid (mandatory) arguments can be adjusted via the addArgument static method instead of directly manipulating the argList::validArgs static member.
The valid options can be adjusted via the addOption/removeOption static methods instead of directly manipulating the argList::validOptions static member.
Source files
argList.H
argList.C
argListI.H
Definition at line 118 of file argList.H.
Constructor & Destructor Documentation
argList() [1/2]
argList (int & argc, char **& argv, bool checkArgs = argList::argsMandatory(), bool checkOpts = true, bool initialise = true)
Definition at line 895 of file argList.C.
References dlLibraryTable::append(), UList< T >::data(), Foam::debug::debugObjects(), fileOperation::defaultFileHandler, DetailInfo, UPtrList< T >::empty(), Foam::endl(), UPstream::exit(), Foam::getEnv(), ParRunControl::incrDryRun(), ParRunControl::incrVerbose(), Foam::Info, Foam::debug::infoObjects(), Switch::INVALID, argList::libs(), fileName::name(), fileOperationInitialise::New(), Foam::nl, Foam::debug::optimisationObjects(), ParRunControl::parRun(), argList::parse(), Foam::foamVersion::printBuildInfo(), List< T >::resize(), ParRunControl::runPar(), PtrList< T >::set(), simpleObjectRegistry::setNamedValue(), UList< T >::size(), messageStream::stdStream(), ParRunControl::threads(), argList::validOptions, argList::validParOptions, and Foam::Warning.
argList() [2/2]
argList (const argList & args, const HashTable< string > & options, bool checkArgs = true, bool checkOpts = true, bool initialise = true)
Definition at line 1155 of file argList.C.
References argList::parse().
~argList()
~argList () virtual
Definition at line 1930 of file argList.C.
References fileOperation::fileHandler(), Foam::jobInfo, and JobInfo::stop().
Member Function Documentation
envExecutable()
Foam::word envExecutable () static
Definition at line 645 of file argList.C.
References Foam::getEnv().
envGlobalPath()
Foam::fileName envGlobalPath () static
Definition at line 651 of file argList.C.
References Foam::getEnv().
Referenced by pointNoise::calculate(), surfaceNoise::calculate(), boundaryDataSurfaceReader::readField(), boundaryDataSurfaceReader::readPoints(), boundaryDataWriter::write(), debugWriter::write(), boundaryDataWriter::writeTemplate(), and debugWriter::writeTemplate().
envRelativePath()
Foam::fileName envRelativePath (const fileName & input, const bool caseTag = false) static
Definition at line 657 of file argList.C.
References Foam::input().
Referenced by IOstream::relativeName(), and dictionary::relativeName().
parse()
void parse (bool checkArgs, bool checkOpts, bool initialise)
Definition at line 1178 of file argList.C.
References dictionary::add(), PstreamBuffers::algorithm, dynamicCode::allowSystemOperations, UPstream::allWorlds(), Foam::foamVersion::api, Foam::foamVersion::build, Foam::foamVersion::buildArch, Foam::check(), fileName::clean(), List< T >::clear(), PtrList< T >::clear(), clock::clockTime(), UPstream::commsTypeNames, Foam::cwd(), clock::date(), UPstream::defaultCommsType, fileOperation::defaultFileHandler, DetailInfo, UList< T >::empty(), UPtrList< T >::empty(), Foam::endl(), Foam::exit(), UPstream::exit(), Foam::FatalError, FatalErrorIn, FatalErrorInFunction, IOobject::fileCheckTypesNames, fileOperation::fileHandler(), Foam::fileHandler, fileOperation::fileHandlerPtr_, IOobject::fileModificationChecking, IOobject::fileModificationSkew, Foam::findMatchingStrings(), UPtrList< T >::first(), Foam::flatOutput(), UPstream::floatTransfer, forAll, Foam::getEnv(), Foam::hostName(), Foam::Info, Foam::debug::infoSwitch(), fileName::isAbsolute(), Foam::isDir(), Foam::jobInfo, keyType::LITERAL, UPstream::master(), UPstream::masterNo(), IOobject::maxFileModificationPolls, IOobjectOption::MUST_READ, UPstream::myProcNo(), UPstream::myWorld(), Switch::name(), Foam::name(), fileOperation::New(), Foam::nl, UPstream::nPollProcInterfaces, UPstream::nProcs(), UPstream::nProcsNonblockingExchange, UPstream::nProcsSimpleSum, fileName::null, UPstream::parRun(), Foam::foamVersion::patch, Foam::foamVersion::patched(), Foam::pgid(), Foam::pid(), Foam::ppid(), Foam::foamVersion::printBuildInfo(), Foam::printHostsSubscription(), Foam::printRootsSubscription(), IOobjectOption::READ_IF_PRESENT, readIfPresent(), List< T >::resize(), PtrList< T >::resize(), UPstream::scheduled, sigFpe::set(), sigInt::set(), sigQuit::set(), sigSegv::set(), PtrList< T >::set(), UPtrList< T >::size(), UList< T >::size(), string::starts_with(), messageStream::stdStream(), UPstream::subProcs(), IOobject::timeStamp, IOobject::timeStampMaster, UPstream::tuning_NBX_, Foam::userName(), Foam::foamVersion::version, Foam::Warning, JobInfo::write(), error::write(), IOobject::writeBanner(), and IOobject::writeDivider().
Referenced by argList::argList(), and argList::argList().
executable()
const Foam::word & executable () const inline noexcept
Definition at line 44 of file argListI.H.
Referenced by if(), if(), if(), if(), if(), if(), if(), if(), and if().
commandLine()
const Foam::string & commandLine () const inline noexcept
Definition at line 50 of file argListI.H.
rootPath()
const Foam::fileName & rootPath () const inline noexcept
Definition at line 56 of file argListI.H.
caseName()
const Foam::fileName & caseName () const inline noexcept
Definition at line 62 of file argListI.H.
globalCaseName()
const Foam::fileName & globalCaseName () const inline noexcept
Definition at line 68 of file argListI.H.
path()
Foam::fileName path () const inline
Definition at line 74 of file argListI.H.
globalPath()
Foam::fileName globalPath () const inline
Definition at line 80 of file argListI.H.
relativePath()
Foam::fileName relativePath (const fileName & input, const bool caseTag = false) const inline
Definition at line 86 of file argListI.H.
References Foam::input().
Referenced by if(), if(), if(), if(), if(), if(), if(), and if().
runControl()
const Foam::ParRunControl & runControl () const inline noexcept
Definition at line 97 of file argListI.H.
distributed()
bool distributed () const inline noexcept
Definition at line 103 of file argListI.H.
dryRun() [1/2]
int dryRun () const inline noexcept
Definition at line 109 of file argListI.H.
Referenced by forAll(), forAll(), and dynamicFvMesh::New().
dryRun() [2/2]
int dryRun (const int level) inline noexcept
Definition at line 115 of file argListI.H.
verbose() [1/3]
int verbose () const inline noexcept
Definition at line 121 of file argListI.H.
verbose() [2/3]
int verbose (const int level) inline noexcept
Definition at line 127 of file argListI.H.
allowFunctionObjects()
bool allowFunctionObjects () const
Definition at line 1941 of file argList.C.
Referenced by Time::Time().
allowLibs()
bool allowLibs () const
Definition at line 1959 of file argList.C.
Referenced by Time::Time().
libs()
Foam::dlLibraryTable & libs () const inline noexcept
Definition at line 133 of file argListI.H.
Referenced by argList::argList().
size()
Foam::label size () const inline noexcept
Definition at line 139 of file argListI.H.
References UPtrList< T >::size().
Referenced by functionObjectList::readFunctionObject(), zoltanRenumber::renumber(), and Foam::stringOps::splitFunctionArgs().
args() [1/2]
const Foam::stringList & args () const inline noexcept
Definition at line 145 of file argListI.H.
args() [2/2]
Foam::stringList & args () inline noexcept
Definition at line 151 of file argListI.H.
options() [1/2]
const Foam::HashTable< Foam::string > & options () const inline noexcept
Definition at line 158 of file argListI.H.
options() [2/2]
Foam::HashTable< Foam::string > & options () inline noexcept
Definition at line 165 of file argListI.H.
found()
bool found (const word & optName) const inline
Definition at line 171 of file argListI.H.
Referenced by forAll(), forAll(), if(), if(), if(), if(), dynamicFvMesh::New(), functionObjectList::New(), timeSelector::select(), timeSelector::selectIfPresent(), and Time::Time().
count() [1/2]
Foam::label count (const UList< word > & optionNames) const
Definition at line 1967 of file argList.C.
count() [2/2]
Foam::label count (std::initializer_list< word > optionNames) const
Definition at line 1981 of file argList.C.
lookup()
Foam::ITstream lookup (const word & optName) const inline
Definition at line 177 of file argListI.H.
get() [1/11]
template<class T > T get (const label index) const inline
Definition at line 271 of file argListI.H.
References T.
Referenced by if(), if(), if(), and if().
getList() [1/4]
template<class T > List< T > getList (const label index) const inline
Referenced by functionObjectList::New().
get() [2/11]
template<class T > T get (const word & optName) const inline
Definition at line 285 of file argListI.H.
References T.
getOrDefault()
template<class T > T getOrDefault (const word & optName, const T & deflt) const inline
Definition at line 299 of file argListI.H.
Referenced by functionObjectList::New().
getList() [2/4]
template<class T > List< T > getList (const word & optName, bool mandatory = true) const inline
readIfPresent() [1/2]
template<class T > bool readIfPresent (const word & optName, T & val) const inline
Definition at line 315 of file argListI.H.
Referenced by if().
readIfPresent() [2/2]
template<class T > bool readIfPresent (const word & optName, T & val, const T & deflt) const inline
Definition at line 332 of file argListI.H.
readListIfPresent()
template<class T > bool readListIfPresent (const word & optName, List< T > & list) const inline
Definition at line 386 of file argListI.H.
readCheck()
template<class T , class Predicate > bool readCheck (const word & optName, T & val, const Predicate & pred, bool mandatory = true) const inline
Definition at line 408 of file argListI.H.
References Foam::exit(), Foam::FatalError, and Foam::nl.
readCheckIfPresent()
template<class T , class Predicate > bool readCheckIfPresent (const word & optName, T & val, const Predicate & pred) const inline
Definition at line 437 of file argListI.H.
getCheck()
template<class T , class Predicate > T getCheck (const word & optName, const Predicate & pred) const inline
Definition at line 449 of file argListI.H.
References T.
getCheckOrDefault()
template<class T , class Predicate > T getCheckOrDefault (const word & optName, const T & deflt, const Predicate & pred) const inline
Definition at line 462 of file argListI.H.
References T.
addArgument()
addArgument (const string & argName, const string & usage = "") static
Definition at line 350 of file argList.C.
References PtrList< T >::append(), PtrList< T >::set(), and UPtrList< T >::size().
addBoolOption()
addBoolOption (const word & optName, const string & usage = "", bool advanced = false) static
Definition at line 373 of file argList.C.
References argList::addOption().
Referenced by argList::addDryRunOption(), timeSelector::addOptions(), argList::addVerboseOption(), argList::noFunctionObjects(), and argList::noLibs().
addOption()
addOption (const word & optName, const string & param = "", const string & usage = "", bool advanced = false) static
Initial value:
{
    Foam::argList::addBoolOption
    (
        "allRegions",
        "Use all regions in regionProperties"
    )
Definition at line 384 of file argList.C.
References PtrList< T >::set().
Referenced by argList::addBoolOption(), and timeSelector::addOptions().
setAdvanced()
void setAdvanced (const word & optName, bool advanced = true) static
Definition at line 404 of file argList.C.
References PtrList< T >::set().
addOptionCompat()
void addOptionCompat (const word & optName, std::pair< const char *, int > compat) static
Definition at line 417 of file argList.C.
References UPtrList< T >::first().
ignoreOptionCompat()
void ignoreOptionCompat (std::pair< const char *, int > compat, bool expectArg) static
Definition at line 431 of file argList.C.
References UPtrList< T >::first().
addUsage()
void addUsage (const word & optName, const string & usage) static
Definition at line 445 of file argList.C.
References PtrList< T >::set().
addNote()
addNote (const string & note) static
Definition at line 462 of file argList.C.
References PtrList< T >::append().
removeOption()
void removeOption (const word & optName) static
Definition at line 471 of file argList.C.
noMandatoryArgs()
void noMandatoryArgs () static
Definition at line 479 of file argList.C.
argsMandatory()
bool argsMandatory () static
Definition at line 485 of file argList.C.
noBanner()
void noBanner () static
Definition at line 491 of file argList.C.
References Foam::infoDetailLevel.
bannerEnabled()
bool bannerEnabled () static
Definition at line 497 of file argList.C.
References Foam::infoDetailLevel.
addDryRunOption()
addDryRunOption (const string & usage, bool advanced = false) static
Parameters
advanced usage information (expected)
Definition at line 503 of file argList.C.
References argList::addBoolOption().
addVerboseOption()
void addVerboseOption (const string & usage = "", bool advanced = false) static
Parameters
advanced usage information (optional)
Definition at line 519 of file argList.C.
References argList::addBoolOption().
noFunctionObjects()
void noFunctionObjects (bool addWithOption = false) static
Definition at line 547 of file argList.C.
References argList::addBoolOption().
noJobInfo()
void noJobInfo () static
Definition at line 567 of file argList.C.
References JobInfo::disable().
noLibs()
void noLibs () static
Definition at line 573 of file argList.C.
References argList::addBoolOption().
noParallel()
void noParallel () static
Definition at line 584 of file argList.C.
noCheckProcessorDirectories()
void noCheckProcessorDirectories () static
Definition at line 602 of file argList.C.
parallelThreads_on()
void parallelThreads_on () static
Definition at line 596 of file argList.C.
setOption()
bool setOption (const word & optName, const string & param = "")
Definition at line 1995 of file argList.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::nl, and PtrList< T >::set().
unsetOption()
bool unsetOption (const word & optName)
Definition at line 2023 of file argList.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and Foam::nl.
postProcess()
bool postProcess (int argc, char * argv[]) static
Definition at line 608 of file argList.C.
verbose() [3/3]
int verbose (int argc, char * argv[]) static
Definition at line 629 of file argList.C.
printCompat()
void printCompat () const
Definition at line 533 of file argListHelp.C.
References UPtrList< T >::first(), argList::ignoreOptionsCompat, Foam::Info, k, Foam::nl, Foam::setf(), Foam::setfill(), Foam::setw(), token::SPACE, and argList::validOptionsCompat.
printNotes()
void printNotes () const
Definition at line 455 of file argListHelp.C.
References Foam::Info, Foam::nl, and Foam::stringOps::writeWrapped().
printUsage()
void printUsage (bool full = true) const
Definition at line 359 of file argListHelp.C.
References argList::argUsage, Foam::endl(), argList::ignoreOptionsCompat, Foam::Info, Foam::nl, string::null, Foam::foamVersion::printBuildInfo(), Foam::printOption(), Foam::printOptionUsage(), UPtrList< T >::size(), messageStream::stdStream(), and argList::validOptionsCompat.
printMan()
void printMan () const
Definition at line 193 of file argListHelp.C.
References argList::advancedOptions, Foam::foamVersion::api, argList::argUsage, token::DQUOTE, UPtrList< T >::empty(), argList::ignoreOptionsCompat, Foam::Info, Foam::nl, argList::notes, string::null, Foam::printManFooter(), Foam::printManOption(), UPtrList< T >::size(), token::SPACE, Foam::stringOps::upper(), argList::usageMax, argList::validArgs, argList::validOptions, argList::validOptionsCompat, and Foam::stringOps::writeWrapped().
displayDoc()
void displayDoc (bool source = false) const
Definition at line 2044 of file argList.C.
References Foam::foamVersion::api, Foam::debug::controlDict(), UPtrList< T >::empty(), Foam::endl(), Foam::stringOps::expand(), UPtrList< T >::get(), Foam::getEnv(), Foam::Info, Foam::isFile(), Foam::nl, Foam::stringOps::splitSpace(), dictionary::subDict(), and Foam::system().
check()
bool check (bool checkArgs = argList::argsMandatory(), bool checkOpts = true) const
Definition at line 2118 of file argList.C.
References Foam::endl(), Foam::FatalError, forAllConstIters, UPstream::master(), Foam::nl, and UPtrList< T >::size().
checkRootCase()
bool checkRootCase () const
Definition at line 2166 of file argList.C.
References UPtrList< T >::empty(), Foam::endl(), Foam::FatalError, Foam::fileHandler, Foam::isDir(), UPstream::master(), and path().
operator[]() [1/2]
const Foam::string & operator[] (const label index) const inline
Definition at line 483 of file argListI.H.
operator[]() [2/2]
const Foam::string & operator[] (const word & optName) const inline
Definition at line 489 of file argListI.H.
opt() [1/2]
template<class T = string> T opt (const word & optName) const inline
Definition at line 727 of file argList.H.
opt() [2/2]
template<class T > T opt (const word & optName, const T & deflt) const inline
Definition at line 735 of file argList.H.
get() [3/11]
template<class T > T get (const word & optName, const T & deflt) const inline
Definition at line 743 of file argList.H.
lookupOrDefault()
template<class T > T lookupOrDefault (const word & optName, const T & deflt) const inline
Definition at line 751 of file argList.H.
parRunControl()
const ParRunControl & parRunControl () const inline
Definition at line 757 of file argList.H.
read()
template<class T > T read (const label index) const inline
Definition at line 769 of file argList.H.
argRead()
template<class T > T argRead (const label index) const inline
Definition at line 779 of file argList.H.
optionFound()
bool optionFound (const word & optName) const inline
Definition at line 787 of file argList.H.
References found.
optionLookup()
ITstream optionLookup (const word & optName) const inline
Definition at line 795 of file argList.H.
optionRead()
template<class T > T optionRead (const word & optName) const inline
Definition at line 804 of file argList.H.
optionReadIfPresent() [1/2]
template<class T > bool optionReadIfPresent (const word & optName, T & val) const inline
Definition at line 814 of file argList.H.
optionReadIfPresent() [2/2]
template<class T > bool optionReadIfPresent (const word & optName, T & val, const T & deflt) const inline
Definition at line 829 of file argList.H.
optionLookupOrDefault()
template<class T > T optionLookupOrDefault (const word & optName, const T & deflt) const inline
Definition at line 844 of file argList.H.
optionReadList()
template<class T > List< T > optionReadList (const word & optName) const inline
Definition at line 857 of file argList.H.
get() [4/11]
template<> int32_t get (const label index) const inline
Definition at line 187 of file argListI.H.
References Foam::readInt32().
get() [5/11]
template<> int64_t get (const label index) const inline
Definition at line 192 of file argListI.H.
References Foam::readInt64().
get() [6/11]
template<> float get (const label index) const inline
Definition at line 197 of file argListI.H.
get() [7/11]
template<> double get (const label index) const inline
Definition at line 202 of file argListI.H.
get() [8/11]
template<> int32_t get (const word & optName) const inline
Definition at line 208 of file argListI.H.
References Foam::readInt32().
get() [9/11]
template<> int64_t get (const word & optName) const inline
Definition at line 213 of file argListI.H.
References Foam::readInt64().
get() [10/11]
template<> float get (const word & optName) const inline
Definition at line 218 of file argListI.H.
get() [11/11]
template<> double get (const word & optName) const inline
Definition at line 223 of file argListI.H.
getList() [3/4]
template<class T > Foam::List< T > getList (const label index) const inline
Definition at line 350 of file argListI.H.
getList() [4/4]
template<class T > Foam::List< T > getList (const word & optName, bool mandatory) const inline
Definition at line 364 of file argListI.H.
Member Data Documentation
validArgs
Foam::SLList< Foam::string > validArgs static
Definition at line 204 of file argList.H.
Referenced by argList::printMan().
advancedOptions
Foam::HashSet< Foam::string > advancedOptions static
Definition at line 207 of file argList.H.
Referenced by argList::printMan().
validOptions
Foam::HashTable< Foam::string > validOptions static
Definition at line 210 of file argList.H.
Referenced by argList::argList(), argList::printMan(), Foam::printManOption(), Foam::printOption(), and timeSelector::select().
validParOptions
Foam::HashTable< Foam::string > validParOptions static
Definition at line 213 of file argList.H.
Referenced by argList::argList(), and Foam::printManOption().
validOptionsCompat
Foam::HashTable< std::pair< Foam::word, int > > validOptionsCompat static
Definition at line 217 of file argList.H.
Referenced by argList::printCompat(), argList::printMan(), and argList::printUsage().
ignoreOptionsCompat
Foam::HashTable< std::pair< bool, int > > ignoreOptionsCompat static
Definition at line 221 of file argList.H.
Referenced by argList::printCompat(), argList::printMan(), and argList::printUsage().
argUsage
Foam::HashTable< Foam::string, Foam::label, Foam::Hash< Foam::label > > argUsage static
Definition at line 224 of file argList.H.
Referenced by argList::printMan(), and argList::printUsage().
optionUsage
Foam::HashTable< Foam::string > optionUsage static
Definition at line 227 of file argList.H.
Referenced by Foam::printManOption(), and Foam::printOption().
notes
Foam::SLList< Foam::string > notes static
Definition at line 230 of file argList.H.
Referenced by argList::printMan().
usageMin
std::string::size_type usageMin = 20 static
Definition at line 233 of file argList.H.
Referenced by Foam::printOptionUsage().
usageMax
std::string::size_type usageMax = 80 static
Definition at line 236 of file argList.H.
Referenced by argList::printMan(), Foam::printManOption(), and Foam::printOptionUsage().
postProcessOptionName
Foam::word postProcessOptionName static
Definition at line 239 of file argList.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/global/argList/argList.H
src/OpenFOAM/db/functionObjects/functionObjectList/postProcess.H
src/OpenFOAM/global/argList/argList.C
src/OpenFOAM/global/argList/argListHelp.C
src/OpenFOAM/global/argList/argListI.H
src/OpenFOAM/include/addAllRegionOptions.H
src/OpenFOAM/include/addCheckCaseOptions.H
src/OpenFOAM/include/addDictOption.H
src/OpenFOAM/include/addFunctionObjectOptions.H
src/OpenFOAM/include/addOverwriteOption.H
src/OpenFOAM/include/addProfilingOption.H
src/OpenFOAM/include/addRegionOption.H
src/OpenFOAM/include/addTimeOptions.H
src/OpenFOAM/include/setRootCaseListOptions.H
applications/utilities/miscellaneous/foamHelp/addToolOption.H