OpenFOAM: FieldFunction1< Function1Type > Class Template Reference
FieldFunction1< Function1Type > Class Template Reference
#include <Function1.H>
Public Types
typedef Function1Type::returnType Type
Public Member Functions
FieldFunction1 (const word &entryName, const dictionary &dict, const objectRegistry *obrPtr=nullptr)
virtual tmp< Function1< Type > > clone () const
virtual ~FieldFunction1 ()=default
virtual tmp< Field< Type > > value (const scalarField &x) const
virtual tmp< Field< Type > > integrate (const scalarField &x1, const scalarField &x2) const
Detailed Description
template<class Function1Type>
class Foam::FieldFunction1< Function1Type >
Definition at line 300 of file Function1.H.
Member Typedef Documentation
Type
template<class Function1Type > typedef Function1Type::returnType Type
Definition at line 306 of file Function1.H.
Constructor & Destructor Documentation
FieldFunction1()
template<class Function1Type > FieldFunction1 (const word & entryName, const dictionary & dict, const objectRegistry * obrPtr = nullptr)
Definition at line 119 of file Function1.C.
~FieldFunction1()
template<class Function1Type > virtual ~FieldFunction1 () virtual default
Member Function Documentation
clone()
template<class Function1Type > Foam::tmp< Foam::Function1< typename Function1Type::returnType > > clone () const virtual
Definition at line 132 of file Function1.C.
value()
template<class Function1Type > Foam::tmp< Foam::Field< typename Function1Type::returnType > > value (const scalarField & x) const virtual
Definition at line 102 of file Function1.C.
References fld(), forAll, Foam::New(), and x.
integrate()
template<class Function1Type > Foam::tmp< Foam::Field< typename Function1Type::returnType > > integrate (const scalarField & x1, const scalarField & x2) const virtual
Definition at line 143 of file Function1.C.
References fld(), forAll, Foam::New(), and UPtrList< T >::size().
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/functions/Function1/Function1/Function1.H
src/OpenFOAM/primitives/functions/Function1/Function1/Function1.C