OpenFOAM: coordinateRotation Class Reference
coordinateRotation Class Reference abstract
User specification of a coordinate rotation.
#include <coordinateRotation.H>
Public Member Functions
TypeNameNoDebug ("coordinateRotation")
declareRunTimeSelectionTable (autoPtr, coordinateRotation, dictionary,(const dictionary &dict),(dict))
virtual autoPtr< coordinateRotation > clone () const =0
virtual ~coordinateRotation ()=default
virtual void clear ()=0
virtual tensor R () const =0
virtual void write (Ostream &os) const =0
virtual void writeEntry (const word &keyword, Ostream &os) const =0
Static Public Member Functions
static autoPtr< coordinateRotation > New (const word &modelType, const dictionary &dict)
static autoPtr< coordinateRotation > New (const dictionary &dict)
Static Protected Member Functions
static vector findOrthogonal (const vector &axis)
Detailed Description
User specification of a coordinate rotation.
rotation
{
    type    axes
    e1      (1 0 0);
    e2      (0 1 0);
}
Types of coordinateRotations:
none
axes
axisAngle
cylindrical
euler
starcd
Source files
coordinateRotation.H
coordinateRotation.C
Definition at line 76 of file coordinateRotation.H.
Constructor & Destructor Documentation
~coordinateRotation()
virtual ~coordinateRotation () virtual default
Member Function Documentation
findOrthogonal()
Foam::vector findOrthogonal (const vector & axis) static protected
Definition at line 37 of file coordinateRotation.C.
References Foam::mag(), VectorSpace< Form, Cmpt, Ncmpts >::nComponents, and Foam::Zero.
Referenced by axes::rotation().
TypeNameNoDebug()
TypeNameNoDebug ("coordinateRotation")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , coordinateRotation , dictionary , (const dictionary &dict) , (dict))
clone()
virtual autoPtr< coordinateRotation > clone () const pure virtual
Implemented in axes, axisAngle, cylindrical, euler, identity, specified, and starcd.
New() [1/2]
Foam::autoPtr< Foam::coordinateRotation > New (const word & modelType, const dictionary & dict) static
Definition at line 65 of file coordinateRotation.C.
References dict, Foam::exit(), Foam::FatalIOError, and FatalIOErrorInLookup.
Referenced by coordinateSystem::assign(), and coordinateRotation::New().
New() [2/2]
Foam::autoPtr< Foam::coordinateRotation > New (const dictionary & dict) static
Definition at line 97 of file coordinateRotation.C.
References dict, dictionary::get(), and coordinateRotation::New().
clear()
virtual void clear () pure virtual
Implemented in axes, axisAngle, euler, identity, specified, and starcd.
R()
virtual tensor R () const pure virtual
Implemented in axes, axisAngle, euler, identity, specified, and starcd.
write()
virtual void write (Ostream & os) const pure virtual
Implemented in axes, axisAngle, cylindrical, euler, identity, specified, and starcd.
writeEntry()
virtual void writeEntry (const word & keyword, Ostream & os) const pure virtual
Implemented in axes, axisAngle, cylindrical, euler, identity, specified, and starcd.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/coordinate/rotation/coordinateRotation.H
src/OpenFOAM/primitives/coordinate/rotation/coordinateRotation.C