OpenFOAM: displacementMethoddisplacementLaplacian Class Reference
displacementMethoddisplacementLaplacian Class Reference
Wrapper class for the displacementLaplacian motion solver.
#include <displacementMethoddisplacementLaplacian.H>
Public Member Functions
TypeName ("displacementLaplacian")
displacementMethoddisplacementLaplacian (fvMesh &mesh, const labelList &patchIDs)
virtual ~displacementMethoddisplacementLaplacian ()=default
void setMotionField (const pointVectorField &pointMovement)
void setMotionField (const volVectorField &cellMovement)
void setControlField (const vectorField &controlField)
void setControlField (const scalarField &controlField)
Public Member Functions inherited from displacementMethod
TypeName ("displacementMethod")
declareRunTimeSelectionTable (autoPtr, displacementMethod, dictionary,(fvMesh &mesh, const labelList &patchIDs),(mesh, patchIDs))
displacementMethod (fvMesh &mesh, const labelList &patchIDs)
virtual ~displacementMethod ()=default
virtual void boundControlField (vectorField &controlField)
autoPtr< motionSolver > & getMotionSolver ()
scalar getMaxDisplacement () const
void update ()
Protected Attributes
pointVectorField & pointDisplacement_
volVectorField & cellDisplacement_
bool resetFields_
Protected Attributes inherited from displacementMethod
fvMesh & mesh_
const labelList & patchIDs_
autoPtr< motionSolver > motionPtr_
scalar maxDisplacement_
Additional Inherited Members
Static Public Member Functions inherited from displacementMethod
static autoPtr< displacementMethod > New (fvMesh &mesh, const labelList &patchIDs)
Detailed Description
Wrapper class for the displacementLaplacian motion solver.
Source files
displacementMethoddisplacementLaplacian.H
displacementMethoddisplacementLaplacian.C
Definition at line 48 of file displacementMethoddisplacementLaplacian.H.
Constructor & Destructor Documentation
displacementMethoddisplacementLaplacian()
displacementMethoddisplacementLaplacian (fvMesh & mesh, const labelList & patchIDs)
Definition at line 44 of file displacementMethoddisplacementLaplacian.C.
~displacementMethoddisplacementLaplacian()
virtual ~displacementMethoddisplacementLaplacian () virtual default
Member Function Documentation
TypeName()
TypeName ("displacementLaplacian")
setMotionField() [1/2]
void setMotionField (const pointVectorField & pointMovement) virtual
Implements displacementMethod.
Definition at line 105 of file displacementMethoddisplacementLaplacian.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), displacementMethoddisplacementLaplacian::cellDisplacement_, GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), Foam::endl(), Foam::gMax(), Foam::Info, Foam::mag(), Foam::max(), displacementMethod::maxDisplacement_, displacementMethod::patchIDs_, displacementMethoddisplacementLaplacian::pointDisplacement_, GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef(), displacementMethoddisplacementLaplacian::resetFields_, and VectorSpace< Form, Cmpt, Ncmpts >::zero.
setMotionField() [2/2]
void setMotionField (const volVectorField & cellMovement) virtual
Implements displacementMethod.
Definition at line 153 of file displacementMethoddisplacementLaplacian.C.
References NotImplemented.
setControlField() [1/2]
void setControlField (const vectorField & controlField) virtual
Implements displacementMethod.
Definition at line 162 of file displacementMethoddisplacementLaplacian.C.
References NotImplemented.
setControlField() [2/2]
void setControlField (const scalarField & controlField) virtual
Implements displacementMethod.
Definition at line 171 of file displacementMethoddisplacementLaplacian.C.
References NotImplemented.
Member Data Documentation
pointDisplacement_
pointVectorField& pointDisplacement_ protected
Definition at line 56 of file displacementMethoddisplacementLaplacian.H.
Referenced by displacementMethoddisplacementLaplacian::setMotionField().
cellDisplacement_
volVectorField& cellDisplacement_ protected
Definition at line 58 of file displacementMethoddisplacementLaplacian.H.
Referenced by displacementMethoddisplacementLaplacian::setMotionField().
resetFields_
bool resetFields_ protected
Definition at line 60 of file displacementMethoddisplacementLaplacian.H.
Referenced by displacementMethoddisplacementLaplacian::setMotionField().
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/displacementMethod/displacementMethoddisplacementLaplacian/displacementMethoddisplacementLaplacian.H
src/optimisation/adjointOptimisation/adjoint/displacementMethod/displacementMethoddisplacementLaplacian/displacementMethoddisplacementLaplacian.C