OpenFOAM: JohnsonJacksonSchaeffer Class Reference
JohnsonJacksonSchaeffer Class Reference
#include <JohnsonJacksonSchaefferFrictionalStress.H>
Public Member Functions
TypeName ("JohnsonJacksonSchaeffer")
JohnsonJacksonSchaeffer (const dictionary &dict)
virtual ~JohnsonJacksonSchaeffer ()
virtual tmp< volScalarField > frictionalPressure (const phaseModel &phase, const dimensionedScalar &alphaMinFriction, const dimensionedScalar &alphaMax) const
virtual tmp< volScalarField > frictionalPressurePrime (const phaseModel &phase, const dimensionedScalar &alphaMinFriction, const dimensionedScalar &alphaMax) const
virtual tmp< volScalarField > nu (const phaseModel &phase, const dimensionedScalar &alphaMinFriction, const dimensionedScalar &alphaMax, const volScalarField &pf, const volSymmTensorField &D) const
virtual bool read ()
TypeName ("JohnsonJacksonSchaeffer")
JohnsonJacksonSchaeffer (const dictionary &dict)
virtual ~JohnsonJacksonSchaeffer ()
virtual tmp< volScalarField > frictionalPressure (const phaseModel &phase, const dimensionedScalar &alphaMinFriction, const dimensionedScalar &alphaMax) const
virtual tmp< volScalarField > frictionalPressurePrime (const phaseModel &phase, const dimensionedScalar &alphaMinFriction, const dimensionedScalar &alphaMax) const
virtual tmp< volScalarField > nu (const phaseModel &phase, const dimensionedScalar &alphaMinFriction, const dimensionedScalar &alphaMax, const volScalarField &pf, const volSymmTensorField &D) const
virtual bool read ()
Public Member Functions inherited from frictionalStressModel
TypeName ("frictionalStressModel")
declareRunTimeSelectionTable (autoPtr, frictionalStressModel, dictionary,(const dictionary &dict),(dict))
frictionalStressModel (const dictionary &dict)
virtual ~frictionalStressModel ()=default
TypeName ("frictionalStressModel")
declareRunTimeSelectionTable (autoPtr, frictionalStressModel, dictionary,(const dictionary &dict),(dict))
frictionalStressModel (const dictionary &dict)
virtual ~frictionalStressModel ()=default
Additional Inherited Members
Static Public Member Functions inherited from frictionalStressModel
static autoPtr< frictionalStressModel > New (const dictionary &dict)
static autoPtr< frictionalStressModel > New (const dictionary &dict)
Protected Attributes inherited from frictionalStressModel
const dictionary & dict_
Detailed Description
Source files
JohnsonJacksonSchaefferFrictionalStress.H
JohnsonJacksonSchaefferFrictionalStress.C
Source files
JohnsonJacksonSchaefferFrictionalStress.H
JohnsonJacksonSchaefferFrictionalStress.C
Definition at line 49 of file JohnsonJacksonSchaefferFrictionalStress.H.
Constructor & Destructor Documentation
JohnsonJacksonSchaeffer() [1/2]
JohnsonJacksonSchaeffer (const dictionary & dict)
Definition at line 49 of file JohnsonJacksonSchaefferFrictionalStress.C.
References Foam::degToRad(), and Foam::dimless.
~JohnsonJacksonSchaeffer() [1/2]
~JohnsonJacksonSchaeffer () virtual
Definition at line 69 of file JohnsonJacksonSchaefferFrictionalStress.C.
JohnsonJacksonSchaeffer() [2/2]
JohnsonJacksonSchaeffer (const dictionary & dict)
~JohnsonJacksonSchaeffer() [2/2]
virtual ~JohnsonJacksonSchaeffer () virtual
Member Function Documentation
TypeName() [1/2]
TypeName ("JohnsonJacksonSchaeffer")
frictionalPressure() [1/2]
Foam::tmp< Foam::volScalarField > frictionalPressure (const phaseModel & phase, const dimensionedScalar & alphaMinFriction, const dimensionedScalar & alphaMax) const virtual
Implements frictionalStressModel.
Definition at line 77 of file JohnsonJacksonSchaefferFrictionalStress.C.
References alpha, alphaMax(), Foam::max(), and Foam::pow().
frictionalPressurePrime() [1/2]
Foam::tmp< Foam::volScalarField > frictionalPressurePrime (const phaseModel & phase, const dimensionedScalar & alphaMinFriction, const dimensionedScalar & alphaMax) const virtual
Implements frictionalStressModel.
Definition at line 94 of file JohnsonJacksonSchaefferFrictionalStress.C.
References alpha, alphaMax(), Foam::max(), and Foam::pow().
nu() [1/2]
Foam::tmp< Foam::volScalarField > nu (const phaseModel & phase, const dimensionedScalar & alphaMinFriction, const dimensionedScalar & alphaMax, const volScalarField & pf, const volSymmTensorField & D) const virtual
Implements frictionalStressModel.
Definition at line 114 of file JohnsonJacksonSchaefferFrictionalStress.C.
References alpha, GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), coupled(), D, forAll, Foam::invariantII(), Foam::mag(), DimensionedField< Type, GeoMesh >::mesh(), GeometricField< scalar, fvPatchField, volMesh >::New(), patches, Foam::sin(), Foam::sqr(), Foam::sqrt(), Foam::tr(), and U.
read() [1/2]
bool read () virtual
Implements frictionalStressModel.
Definition at line 178 of file JohnsonJacksonSchaefferFrictionalStress.C.
References Foam::degToRad().
TypeName() [2/2]
TypeName ("JohnsonJacksonSchaeffer")
frictionalPressure() [2/2]
virtual tmp< volScalarField > frictionalPressure (const phaseModel & phase, const dimensionedScalar & alphaMinFriction, const dimensionedScalar & alphaMax) const virtual
Implements frictionalStressModel.
frictionalPressurePrime() [2/2]
virtual tmp< volScalarField > frictionalPressurePrime (const phaseModel & phase, const dimensionedScalar & alphaMinFriction, const dimensionedScalar & alphaMax) const virtual
Implements frictionalStressModel.
nu() [2/2]
virtual tmp< volScalarField > nu (const phaseModel & phase, const dimensionedScalar & alphaMinFriction, const dimensionedScalar & alphaMax, const volScalarField & pf, const volSymmTensorField & D) const virtual
Implements frictionalStressModel.
read() [2/2]
virtual bool read () virtual
Implements frictionalStressModel.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/twoPhaseCompressibleTurbulenceModels/kineticTheoryModels/frictionalStressModel/JohnsonJacksonSchaeffer/JohnsonJacksonSchaefferFrictionalStress.H
src/phaseSystemModels/twoPhaseEuler/phaseCompressibleTurbulenceModels/kineticTheoryModels/frictionalStressModel/JohnsonJacksonSchaeffer/JohnsonJacksonSchaefferFrictionalStress.H
src/phaseSystemModels/reactingEuler/twoPhaseCompressibleTurbulenceModels/kineticTheoryModels/frictionalStressModel/JohnsonJacksonSchaeffer/JohnsonJacksonSchaefferFrictionalStress.C
src/phaseSystemModels/twoPhaseEuler/phaseCompressibleTurbulenceModels/kineticTheoryModels/frictionalStressModel/JohnsonJacksonSchaeffer/JohnsonJacksonSchaefferFrictionalStress.C