OpenFOAM: incompressibleVars Class Reference
incompressibleVars Class Reference
Base class for solution control classes.
#include <incompressibleVars.H>
Public Member Functions
TypeName ("incompressibleVars")
incompressibleVars (fvMesh &mesh, solverControl &SolverControl)
incompressibleVars (const incompressibleVars &vs)
virtual autoPtr< variablesSet > clone () const
virtual ~incompressibleVars ()=default
const volScalarField & p () const
volScalarField & p ()
const volVectorField & U () const
volVectorField & U ()
const surfaceScalarField & phi () const
surfaceScalarField & phi ()
const volScalarField & pInst () const
volScalarField & pInst ()
const volVectorField & UInst () const
volVectorField & UInst ()
const surfaceScalarField & phiInst () const
surfaceScalarField & phiInst ()
const singlePhaseTransportModel & laminarTransport () const
singlePhaseTransportModel & laminarTransport ()
const autoPtr< incompressible::turbulenceModel > & turbulence () const
autoPtr< incompressible::turbulenceModel > & turbulence ()
const autoPtr< incompressible::RASModelVariables > & RASModelVariables () const
autoPtr< incompressible::RASModelVariables > & RASModelVariables ()
void restoreInitValues ()
void resetMeanFields ()
void computeMeanFields ()
void correctBoundaryConditions ()
bool storeInitValues () const
bool computeMeanFields () const
virtual void transfer (variablesSet &vars)
bool write () const
Public Member Functions inherited from variablesSet
TypeName ("variablesSet")
variablesSet (fvMesh &mesh, const dictionary &dict)
virtual ~variablesSet ()=default
const word & solverName () const
bool useSolverNameForFields () const
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > allocateField (const fvMesh &mesh, const word &baseName, const word &solverName, const bool useSolverNameForFields)
template<class Type >
void renameTurbulenceField (GeometricField< Type, fvPatchField, volMesh > &baseField, const word &solverName)
tmp< surfaceScalarField > allocateFluxField (const fvMesh &mesh, const volVectorField &velocity, const word &baseName, const word &solverName, const bool useSolverNameForFields)
Protected Member Functions
void setFields ()
void setInitFields ()
void setMeanFields ()
void renameTurbulenceFields ()
void correctNonTurbulentBoundaryConditions ()
void correctTurbulentBoundaryConditions ()
void operator= (const incompressibleVars &)
Protected Member Functions inherited from variablesSet
template<class Type , template< class > class PatchField, class GeoMesh >
autoPtr< GeometricField< Type, PatchField, GeoMesh > > allocateRenamedField (const autoPtr< GeometricField< Type, PatchField, GeoMesh > > &bf)
template<class Type , template< class > class PatchField, class GeoMesh >
void swapAndRename (autoPtr< GeometricField< Type, PatchField, GeoMesh > > &p1, autoPtr< GeometricField< Type, PatchField, GeoMesh > > &p2)
Protected Attributes
solverControl & solverControl_
autoPtr< volScalarField > pPtr_
autoPtr< volVectorField > UPtr_
autoPtr< surfaceScalarField > phiPtr_
autoPtr< singlePhaseTransportModel > laminarTransportPtr_
autoPtr< incompressible::turbulenceModel > turbulence_
autoPtr< incompressible::RASModelVariables > RASModelVariables_
autoPtr< volScalarField > pInitPtr_
autoPtr< volVectorField > UInitPtr_
autoPtr< surfaceScalarField > phiInitPtr_
autoPtr< volScalarField > pMeanPtr_
autoPtr< volVectorField > UMeanPtr_
autoPtr< surfaceScalarField > phiMeanPtr_
bool correctBoundaryConditions_
Protected Attributes inherited from variablesSet
fvMesh & mesh_
word solverName_
bool useSolverNameForFields_
Additional Inherited Members
Static Public Member Functions inherited from variablesSet
template<class Type >
static void setField (autoPtr< GeometricField< Type, fvPatchField, volMesh > > &fieldPtr, const fvMesh &mesh, const word &baseName, const word &solverName, const bool useSolverNameForFields)
static void setFluxField (autoPtr< surfaceScalarField > &fieldPtr, const fvMesh &mesh, const volVectorField &velocity, const word &baseName, const word &solverName, const bool useSolverNameForFields)
static tmp< volVectorField > autoCreateMeshMovementField (const fvMesh &mesh, const word &name, const dimensionSet &dims)
template<class Type , template< class > class PatchField, class GeoMesh >
static void nullifyField (GeometricField< Type, PatchField, GeoMesh > &fieldPtr)
Detailed Description
Base class for solution control classes.
Definition at line 48 of file incompressibleVars.H.
Constructor & Destructor Documentation
incompressibleVars() [1/2]
incompressibleVars (fvMesh & mesh, solverControl & SolverControl)
Definition at line 223 of file incompressibleVars.C.
References incompressibleVars::setFields(), incompressibleVars::setInitFields(), and incompressibleVars::setMeanFields().
incompressibleVars() [2/2]
incompressibleVars (const incompressibleVars & vs)
Definition at line 258 of file incompressibleVars.C.
References DebugInfo, and Foam::endl().
~incompressibleVars()
virtual ~incompressibleVars () virtual default
Member Function Documentation
setFields()
void setFields () protected
Definition at line 37 of file incompressibleVars.C.
References incompressibleVars::correctBoundaryConditions_, incompressibleVars::correctNonTurbulentBoundaryConditions(), incompressibleVars::correctTurbulentBoundaryConditions(), incompressibleVars::laminarTransport(), incompressibleVars::laminarTransportPtr_, variablesSet::mesh_, RASModelVariables::New(), IncompressibleTurbulenceModel< TransportModel >::New(), incompressibleVars::phiInst(), incompressibleVars::phiPtr_, incompressibleVars::pPtr_, incompressibleVars::RASModelVariables_, incompressibleVars::renameTurbulenceFields(), variablesSet::setField(), variablesSet::setFluxField(), schemesLookup::setFluxRequired(), incompressibleVars::solverControl_, variablesSet::solverName_, incompressibleVars::turbulence_, incompressibleVars::UInst(), incompressibleVars::UPtr_, and variablesSet::useSolverNameForFields_.
Referenced by incompressibleVars::incompressibleVars().
setInitFields()
void setInitFields () protected
Definition at line 92 of file incompressibleVars.C.
References Foam::name(), incompressibleVars::phiInitPtr_, incompressibleVars::phiInst(), incompressibleVars::pInitPtr_, incompressibleVars::pInst(), incompressibleVars::solverControl_, solverControl::storeInitValues(), incompressibleVars::UInitPtr_, and incompressibleVars::UInst().
Referenced by incompressibleVars::incompressibleVars().
setMeanFields()
void setMeanFields () protected
Definition at line 109 of file incompressibleVars.C.
References IOobjectOption::AUTO_WRITE, solverControl::average(), incompressibleVars::correctBoundaryConditions_, Foam::endl(), Foam::Info, variablesSet::mesh_, Foam::name(), incompressibleVars::phiInst(), incompressibleVars::phiMeanPtr_, incompressibleVars::pInst(), incompressibleVars::pMeanPtr_, IOobjectOption::READ_IF_PRESENT, incompressibleVars::solverControl_, fvMesh::time(), incompressibleVars::UInst(), and incompressibleVars::UMeanPtr_.
Referenced by incompressibleVars::incompressibleVars().
renameTurbulenceFields()
void renameTurbulenceFields () protected
Definition at line 173 of file incompressibleVars.C.
References incompressibleVars::RASModelVariables_, variablesSet::renameTurbulenceField(), variablesSet::solverName_, and variablesSet::useSolverNameForFields_.
Referenced by incompressibleVars::setFields().
correctNonTurbulentBoundaryConditions()
void correctNonTurbulentBoundaryConditions () protected
Definition at line 198 of file incompressibleVars.C.
References solverControl::average(), Foam::endl(), Foam::Info, incompressibleVars::pInst(), incompressibleVars::pMeanPtr_, incompressibleVars::solverControl_, incompressibleVars::UInst(), and incompressibleVars::UMeanPtr_.
Referenced by incompressibleVars::correctBoundaryConditions(), and incompressibleVars::setFields().
correctTurbulentBoundaryConditions()
void correctTurbulentBoundaryConditions () protected
Definition at line 211 of file incompressibleVars.C.
References Foam::endl(), Foam::Info, incompressibleVars::RASModelVariables_, and incompressibleVars::turbulence_.
Referenced by incompressibleVars::setFields().
operator=()
void operator= (const incompressibleVars &) protected
TypeName()
TypeName ("incompressibleVars")
clone()
autoPtr< variablesSet > clone () const virtual
Reimplemented from variablesSet.
Definition at line 287 of file incompressibleVars.C.
References DebugInfo, and Foam::endl().
p() [1/2]
const volScalarField & p () const
Definition at line 298 of file incompressibleVars.C.
References incompressibleVars::pMeanPtr_, incompressibleVars::pPtr_, incompressibleVars::solverControl_, and solverControl::useAveragedFields().
p() [2/2]
volScalarField & p ()
Definition at line 311 of file incompressibleVars.C.
References incompressibleVars::pMeanPtr_, incompressibleVars::pPtr_, incompressibleVars::solverControl_, and solverControl::useAveragedFields().
U() [1/2]
const volVectorField & U () const
Definition at line 324 of file incompressibleVars.C.
References incompressibleVars::solverControl_, incompressibleVars::UMeanPtr_, incompressibleVars::UPtr_, and solverControl::useAveragedFields().
Referenced by adjointkOmegaSST::addWallFunctionTerms(), adjointkOmegaSST::adjointMeanFlowSource(), adjointkOmegaSST::convectionMeanFlowSource(), adjointkOmegaSST::correct(), adjointkOmegaSST::diffusionNutMeanFlowMult(), adjointSpalartAllmaras::distanceSensitivities(), adjointkOmegaSST::divUMeanFlowSource(), adjointkOmegaSST::dR_dF1(), adjointkOmegaSST::dR_dnut(), adjointkOmegaSST::FISensitivityTerm(), adjointSpalartAllmaras::FISensitivityTerm(), adjointkOmegaSST::GMeanFlowSource(), adjointRASModel::New(), adjointTurbulenceModel::New(), adjointkOmegaSST::nutJacobianTMVar1(), adjointkOmegaSST::nutJacobianTMVar2(), adjointkOmegaSST::nutJacobianU(), adjointkOmegaSST::nutMeanFlowSource(), adjointkOmegaSST::updatePrimalRelatedFields(), and adjointSpalartAllmaras::updatePrimalRelatedFields().
U() [2/2]
volVectorField & U ()
Definition at line 337 of file incompressibleVars.C.
References incompressibleVars::solverControl_, incompressibleVars::UMeanPtr_, incompressibleVars::UPtr_, and solverControl::useAveragedFields().
phi() [1/2]
const surfaceScalarField & phi () const
Definition at line 350 of file incompressibleVars.C.
References incompressibleVars::phiMeanPtr_, incompressibleVars::phiPtr_, incompressibleVars::solverControl_, and solverControl::useAveragedFields().
Referenced by adjointkOmegaSST::convectionScheme(), adjointkOmegaSST::correct(), adjointSpalartAllmaras::correct(), and adjointkOmegaSST::dR_dF1().
phi() [2/2]
surfaceScalarField & phi ()
Definition at line 362 of file incompressibleVars.C.
References incompressibleVars::phiMeanPtr_, incompressibleVars::phiPtr_, incompressibleVars::solverControl_, and solverControl::useAveragedFields().
pInst() [1/2]
const Foam::volScalarField & pInst () const inline
Definition at line 24 of file incompressibleVarsI.H.
References incompressibleVars::pPtr_.
Referenced by incompressibleVars::computeMeanFields(), incompressibleVars::correctNonTurbulentBoundaryConditions(), RASTurbulenceModel::RASTurbulenceModel(), incompressibleVars::resetMeanFields(), incompressibleVars::restoreInitValues(), incompressibleVars::setInitFields(), incompressibleVars::setMeanFields(), and simple::simple().
pInst() [2/2]
Foam::volScalarField & pInst () inline
Definition at line 30 of file incompressibleVarsI.H.
UInst() [1/2]
const Foam::volVectorField & UInst () const inline
Definition at line 36 of file incompressibleVarsI.H.
Referenced by incompressibleVars::computeMeanFields(), incompressibleVars::correctNonTurbulentBoundaryConditions(), incompressibleVars::resetMeanFields(), incompressibleVars::restoreInitValues(), incompressibleVars::setFields(), incompressibleVars::setInitFields(), and incompressibleVars::setMeanFields().
UInst() [2/2]
Foam::volVectorField & UInst () inline
Definition at line 42 of file incompressibleVarsI.H.
phiInst() [1/2]
const Foam::surfaceScalarField & phiInst () const inline
Definition at line 49 of file incompressibleVarsI.H.
Referenced by incompressibleVars::computeMeanFields(), adjointkOmegaSST::convectionScheme(), incompressibleVars::resetMeanFields(), incompressibleVars::restoreInitValues(), incompressibleVars::setFields(), incompressibleVars::setInitFields(), and incompressibleVars::setMeanFields().
phiInst() [2/2]
Foam::surfaceScalarField & phiInst () inline
Definition at line 55 of file incompressibleVarsI.H.
laminarTransport() [1/2]
const Foam::singlePhaseTransportModel & laminarTransport () const inline
Definition at line 62 of file incompressibleVarsI.H.
Referenced by adjointTurbulenceModel::correct(), adjointTurbulenceModel::nu(), adjointTurbulenceModel::nuEff(), adjointTurbulenceModel::nuEff(), and incompressibleVars::setFields().
laminarTransport() [2/2]
Foam::singlePhaseTransportModel & laminarTransport () inline
Definition at line 69 of file incompressibleVarsI.H.
turbulence() [1/2]
const Foam::autoPtr< Foam::incompressible::turbulenceModel > & turbulence () const inline
Definition at line 76 of file incompressibleVarsI.H.
Referenced by adjointkOmegaSST::addWallFunctionTerms(), and adjointkOmegaSST::adjointMeanFlowSource().
turbulence() [2/2]
Foam::autoPtr< Foam::incompressible::turbulenceModel > & turbulence () inline
Definition at line 83 of file incompressibleVarsI.H.
RASModelVariables() [1/2]
const Foam::autoPtr< Foam::incompressible::RASModelVariables > & RASModelVariables () const inline
Definition at line 90 of file incompressibleVarsI.H.
Referenced by adjointkOmegaSST::FISensitivityTerm(), adjointkOmegaSST::k(), adjointkOmegaSST::k(), adjointTurbulenceModel::nuEff(), adjointTurbulenceModel::nuEff(), adjointSpalartAllmaras::nut(), adjointTurbulenceModel::nut(), adjointSpalartAllmaras::nuTilda(), adjointkOmegaSST::nutRef(), adjointkOmegaSST::nutRef(), adjointkOmegaSST::omega(), adjointkOmegaSST::omega(), and adjointkOmegaSST::updatePrimalRelatedFields().
RASModelVariables() [2/2]
Foam::autoPtr< Foam::incompressible::RASModelVariables > & RASModelVariables () inline
Definition at line 97 of file incompressibleVarsI.H.
restoreInitValues()
void restoreInitValues ()
Definition at line 375 of file incompressibleVars.C.
References Foam::endl(), Foam::Info, incompressibleVars::phiInitPtr_, incompressibleVars::phiInst(), incompressibleVars::pInitPtr_, incompressibleVars::pInst(), incompressibleVars::RASModelVariables_, incompressibleVars::solverControl_, solverControl::storeInitValues(), incompressibleVars::UInitPtr_, and incompressibleVars::UInst().
resetMeanFields()
void resetMeanFields ()
Definition at line 388 of file incompressibleVars.C.
References solverControl::average(), solverControl::averageIter(), Foam::endl(), Foam::Info, incompressibleVars::phiInst(), incompressibleVars::phiMeanPtr_, incompressibleVars::pInst(), incompressibleVars::pMeanPtr_, incompressibleVars::RASModelVariables_, incompressibleVars::solverControl_, incompressibleVars::UInst(), incompressibleVars::UMeanPtr_, and Foam::Zero.
computeMeanFields() [1/2]
void computeMeanFields ()
Definition at line 406 of file incompressibleVars.C.
References solverControl::averageIter(), solverControl::doAverageIter(), Foam::endl(), Foam::Info, incompressibleVars::phiInst(), incompressibleVars::phiMeanPtr_, incompressibleVars::pInst(), incompressibleVars::pMeanPtr_, incompressibleVars::RASModelVariables_, incompressibleVars::solverControl_, incompressibleVars::UInst(), and incompressibleVars::UMeanPtr_.
correctBoundaryConditions()
void correctBoundaryConditions ()
Definition at line 424 of file incompressibleVars.C.
References incompressibleVars::correctNonTurbulentBoundaryConditions(), incompressibleVars::RASModelVariables_, and incompressibleVars::turbulence_.
storeInitValues()
bool storeInitValues () const
Definition at line 431 of file incompressibleVars.C.
References incompressibleVars::solverControl_, and solverControl::storeInitValues().
computeMeanFields() [2/2]
bool computeMeanFields () const
Definition at line 437 of file incompressibleVars.C.
References solverControl::average(), and incompressibleVars::solverControl_.
transfer()
void transfer (variablesSet & vars) virtual
Reimplemented from variablesSet.
Definition at line 443 of file incompressibleVars.C.
References incompressibleVars::phiPtr_, incompressibleVars::pPtr_, incompressibleVars::RASModelVariables_, variablesSet::swapAndRename(), PtrList< T >::transfer(), and incompressibleVars::UPtr_.
write()
bool write () const
Definition at line 457 of file incompressibleVars.C.
References variablesSet::mesh_, incompressibleVars::RASModelVariables_, variablesSet::useSolverNameForFields_, and incompressibleVars::write().
Referenced by incompressibleVars::write(), incompressibleAdjointSolver::write(), and incompressibleAdjointSolver::writeNow().
Member Data Documentation
solverControl_
solverControl& solverControl_ protected
Definition at line 57 of file incompressibleVars.H.
Referenced by incompressibleVars::computeMeanFields(), incompressibleVars::computeMeanFields(), incompressibleVars::correctNonTurbulentBoundaryConditions(), incompressibleVars::p(), incompressibleVars::p(), incompressibleVars::phi(), incompressibleVars::phi(), incompressibleVars::resetMeanFields(), incompressibleVars::restoreInitValues(), incompressibleVars::setFields(), incompressibleVars::setInitFields(), incompressibleVars::setMeanFields(), incompressibleVars::storeInitValues(), incompressibleVars::U(), and incompressibleVars::U().
pPtr_
autoPtr<volScalarField> pPtr_ protected
Definition at line 60 of file incompressibleVars.H.
Referenced by incompressibleVars::p(), incompressibleVars::p(), incompressibleVars::pInst(), incompressibleVars::setFields(), and incompressibleVars::transfer().
UPtr_
autoPtr<volVectorField> UPtr_ protected
Definition at line 61 of file incompressibleVars.H.
Referenced by incompressibleVars::setFields(), incompressibleVars::transfer(), incompressibleVars::U(), and incompressibleVars::U().
phiPtr_
autoPtr<surfaceScalarField> phiPtr_ protected
Definition at line 62 of file incompressibleVars.H.
Referenced by incompressibleVars::phi(), incompressibleVars::phi(), incompressibleVars::setFields(), and incompressibleVars::transfer().
laminarTransportPtr_
autoPtr<singlePhaseTransportModel> laminarTransportPtr_ protected
Definition at line 63 of file incompressibleVars.H.
Referenced by incompressibleVars::setFields().
turbulence_
autoPtr<incompressible::turbulenceModel> turbulence_ protected
Definition at line 64 of file incompressibleVars.H.
Referenced by incompressibleVars::correctBoundaryConditions(), incompressibleVars::correctTurbulentBoundaryConditions(), and incompressibleVars::setFields().
RASModelVariables_
autoPtr<incompressible::RASModelVariables> RASModelVariables_ protected
Definition at line 65 of file incompressibleVars.H.
Referenced by incompressibleVars::computeMeanFields(), incompressibleVars::correctBoundaryConditions(), incompressibleVars::correctTurbulentBoundaryConditions(), incompressibleVars::renameTurbulenceFields(), incompressibleVars::resetMeanFields(), incompressibleVars::restoreInitValues(), incompressibleVars::setFields(), incompressibleVars::transfer(), and incompressibleVars::write().
pInitPtr_
autoPtr<volScalarField> pInitPtr_ protected
Definition at line 69 of file incompressibleVars.H.
Referenced by incompressibleVars::restoreInitValues(), and incompressibleVars::setInitFields().
UInitPtr_
autoPtr<volVectorField> UInitPtr_ protected
Definition at line 70 of file incompressibleVars.H.
Referenced by incompressibleVars::restoreInitValues(), and incompressibleVars::setInitFields().
phiInitPtr_
autoPtr<surfaceScalarField> phiInitPtr_ protected
Definition at line 71 of file incompressibleVars.H.
Referenced by incompressibleVars::restoreInitValues(), and incompressibleVars::setInitFields().
pMeanPtr_
autoPtr<volScalarField> pMeanPtr_ protected
Definition at line 75 of file incompressibleVars.H.
Referenced by incompressibleVars::computeMeanFields(), incompressibleVars::correctNonTurbulentBoundaryConditions(), incompressibleVars::p(), incompressibleVars::p(), incompressibleVars::resetMeanFields(), and incompressibleVars::setMeanFields().
UMeanPtr_
autoPtr<volVectorField> UMeanPtr_ protected
Definition at line 76 of file incompressibleVars.H.
Referenced by incompressibleVars::computeMeanFields(), incompressibleVars::correctNonTurbulentBoundaryConditions(), incompressibleVars::resetMeanFields(), incompressibleVars::setMeanFields(), incompressibleVars::U(), and incompressibleVars::U().
phiMeanPtr_
autoPtr<surfaceScalarField> phiMeanPtr_ protected
Definition at line 77 of file incompressibleVars.H.
Referenced by incompressibleVars::computeMeanFields(), incompressibleVars::phi(), incompressibleVars::phi(), incompressibleVars::resetMeanFields(), and incompressibleVars::setMeanFields().
correctBoundaryConditions_
bool correctBoundaryConditions_ protected
Definition at line 82 of file incompressibleVars.H.
Referenced by incompressibleVars::setFields(), and incompressibleVars::setMeanFields().
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/solvers/variablesSet/incompressible/incompressibleVars.H
src/optimisation/adjointOptimisation/adjoint/solvers/variablesSet/incompressible/incompressibleVars.C
src/optimisation/adjointOptimisation/adjoint/solvers/variablesSet/incompressible/incompressibleVarsI.H