OpenFOAM: extendedFeatureEdgeMeshFormat Class Reference
extendedFeatureEdgeMeshFormat Class Reference
Provide a means of reading extendedFeatureEdgeMesh as featureEdgeMesh.
#include <extendedFeatureEdgeMeshFormat.H>
Public Member Functions
extendedFeatureEdgeMeshFormat (const fileName &)
virtual ~extendedFeatureEdgeMeshFormat ()=default
virtual bool read (const fileName &)
Public Member Functions inherited from edgeMesh
edgeMesh (const faMesh &mesh)
label size () const
const edgeVectorField & C () const
TypeName ("edgeMesh")
edgeMesh ()
edgeMesh (const edgeMesh &em)
edgeMesh (edgeMesh &&em)
edgeMesh (const pointField &points, const edgeList &edges)
edgeMesh (pointField &&pointLst, edgeList &&edgeLst)
edgeMesh (const fileName &name)
edgeMesh (const fileName &name, const word &fileType)
declareRunTimeSelectionTable (autoPtr, edgeMesh, fileExtension,(const fileName &name),(name))
virtual ~edgeMesh ()=default
declareMemberFunctionSelectionTable (void, edgeMesh, write, fileExtension,(const fileName &name, const edgeMesh &mesh, IOstreamOption streamOpt, const dictionary &options),(name, mesh, streamOpt, options))
void transfer (edgeMesh &mesh)
bool read (const fileName &name, const word &fileType)
const pointField & points () const noexcept
const edgeList & edges () const noexcept
const labelListList & pointEdges () const
label regions (labelList &edgeRegion) const
virtual void clear ()
virtual void scalePoints (const scalar scaleFactor)
virtual void mergePoints (const scalar mergeDist)
virtual void mergeEdges ()
virtual void writeStats (Ostream &) const
virtual void write (const fileName &name, IOstreamOption streamOpt=IOstreamOption(), const dictionary &options=dictionary::null) const
virtual void write (const fileName &name, const word &fileType, IOstreamOption streamOpt=IOstreamOption(), const dictionary &options=dictionary::null) const
void operator= (const edgeMesh &rhs)
void operator= (edgeMesh &&rhs)
Public Member Functions inherited from GeoMesh< faMesh >
GeoMesh (const faMesh &mesh)
bool hasDb () const
const objectRegistry & thisDb () const
const faMesh & operator() () const
Public Member Functions inherited from edgeMeshFormatsCore
edgeMeshFormatsCore ()=default
virtual ~edgeMeshFormatsCore ()=default
Static Public Member Functions
static autoPtr< edgeMesh > New (const fileName &name)
Static Public Member Functions inherited from edgeMesh
static label size (const Mesh &mesh)
static wordHashSet readTypes ()
static wordHashSet writeTypes ()
static bool canReadType (const word &fileType, bool verbose=false)
static bool canWriteType (const word &fileType, bool verbose=false)
static bool canRead (const fileName &name, bool verbose=false)
static autoPtr< edgeMesh > New (const fileName &name, const word &fileType)
static autoPtr< edgeMesh > New (const fileName &name)
static void write (const fileName &name, const edgeMesh &mesh, IOstreamOption streamOpt=IOstreamOption(), const dictionary &options=dictionary::null)
static void write (const fileName &name, const word &fileType, const edgeMesh &mesh, IOstreamOption streamOpt=IOstreamOption(), const dictionary &options=dictionary::null)
Static Public Member Functions inherited from edgeMeshFormatsCore
static bool checkSupport (const wordHashSet &available, const word &fileType, const bool verbose=false, const char *functionName=nullptr)
Additional Inherited Members
Public Types inherited from GeoMesh< faMesh >
typedef faMesh Mesh
typedef MESH::BoundaryMesh BoundaryMesh
Static Public Attributes inherited from edgeMeshFormatsCore
static word nativeExt
Protected Member Functions inherited from edgeMesh
pointField & storedPoints () noexcept
edgeList & storedEdges () noexcept
Static Protected Member Functions inherited from edgeMeshFormatsCore
static string getLineNoComment (ISstream &is, const char comment='#')
Protected Attributes inherited from GeoMesh< faMesh >
const faMesh & mesh_
Detailed Description
Provide a means of reading extendedFeatureEdgeMesh as featureEdgeMesh.
Source files
extendedFeatureEdgeMeshFormat.H
extendedFeatureEdgeMeshFormat.C
Definition at line 48 of file extendedFeatureEdgeMeshFormat.H.
Constructor & Destructor Documentation
extendedFeatureEdgeMeshFormat()
extendedFeatureEdgeMeshFormat (const fileName & filename)
Definition at line 27 of file extendedFeatureEdgeMeshFormat.C.
References extendedFeatureEdgeMeshFormat::read().
~extendedFeatureEdgeMeshFormat()
virtual ~extendedFeatureEdgeMeshFormat () virtual default
Member Function Documentation
New()
static autoPtr< edgeMesh > New (const fileName & name) inline static
Definition at line 75 of file extendedFeatureEdgeMeshFormat.H.
References Foam::name().
read()
bool read (const fileName & filename) virtual
Reimplemented from edgeMesh.
Definition at line 38 of file extendedFeatureEdgeMeshFormat.C.
References clear(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, and edgeMeshFormat::read().
Referenced by extendedFeatureEdgeMeshFormat::extendedFeatureEdgeMeshFormat().
The documentation for this class was generated from the following files:
src/meshTools/edgeMesh/extendedFeatureEdgeMesh/extendedFeatureEdgeMeshFormat.H
src/meshTools/edgeMesh/extendedFeatureEdgeMesh/extendedFeatureEdgeMeshFormat.C