OpenFOAM: LduMatrix< Type, DType, LUType > Class Template Reference
LduMatrix< Type, DType, LUType > Class Template Reference
LduMatrix is a general matrix class in which the coefficients are stored as three arrays, one for the upper triangle, one for the lower triangle and a third for the diagonal.
#include <LduMatrix.H>
Classes
class preconditioner
class smoother
class solver
Public Member Functions
ClassName ("LduMatrix")
LduMatrix (const lduMesh &)
LduMatrix (const LduMatrix< Type, DType, LUType > &)
LduMatrix (LduMatrix< Type, DType, LUType > &, bool reuse)
LduMatrix (const lduMesh &, Istream &)
~LduMatrix ()
const lduMesh & mesh () const noexcept
const lduAddressing & lduAddr () const
const lduSchedule & patchSchedule () const
const LduInterfaceFieldPtrsList< Type > & interfaces () const
LduInterfaceFieldPtrsList< Type > & interfaces ()
Field< DType > & diag ()
Field< LUType > & upper ()
Field< LUType > & lower ()
Field< Type > & source ()
FieldField< Field, LUType > & interfacesUpper ()
FieldField< Field, LUType > & interfacesLower ()
const Field< DType > & diag () const
const Field< LUType > & upper () const
const Field< LUType > & lower () const
const Field< Type > & source () const
const FieldField< Field, LUType > & interfacesUpper () const
const FieldField< Field, LUType > & interfacesLower () const
bool hasDiag () const noexcept
bool hasUpper () const noexcept
bool hasLower () const noexcept
bool hasSource () const noexcept
bool diagonal () const noexcept
bool symmetric () const noexcept
bool asymmetric () const noexcept
void sumDiag ()
void negSumDiag ()
void sumMagOffDiag (Field< LUType > &sumOff) const
void Amul (Field< Type > &, const tmp< Field< Type > > &) const
void Tmul (Field< Type > &, const tmp< Field< Type > > &) const
void sumA (Field< Type > &) const
void residual (Field< Type > &rA, const Field< Type > &psi) const
tmp< Field< Type > > residual (const Field< Type > &psi) const
void initMatrixInterfaces (const bool add, const FieldField< Field, LUType > &interfaceCoeffs, const Field< Type > &psiif, Field< Type > &result) const
void updateMatrixInterfaces (const bool add, const FieldField< Field, LUType > &interfaceCoeffs, const Field< Type > &psiif, Field< Type > &result, const label startRequest) const
tmp< Field< Type > > H (const Field< Type > &) const
tmp< Field< Type > > H (const tmp< Field< Type > > &) const
tmp< Field< Type > > faceH (const Field< Type > &) const
tmp< Field< Type > > faceH (const tmp< Field< Type > > &) const
void operator= (const LduMatrix< Type, DType, LUType > &)
void negate ()
void operator+= (const LduMatrix< Type, DType, LUType > &)
void operator-= (const LduMatrix< Type, DType, LUType > &)
void operator*= (const scalarField &)
void operator*= (scalar)
Friends
class SolverPerformance< Type >
Ostream & operator (Ostream &, const LduMatrix< Type, DType, LUType > &)
Detailed Description
template<class Type, class DType, class LUType>
class Foam::LduMatrix< Type, DType, LUType >
LduMatrix is a general matrix class in which the coefficients are stored as three arrays, one for the upper triangle, one for the lower triangle and a third for the diagonal.
Addressing arrays must be supplied for the upper and lower triangles.
Note
It might be better if this class were organised as a hierarchy starting from an empty matrix, then deriving diagonal, symmetric and asymmetric matrices.
Source files
LduMatrix.H
LduMatrixATmul.C
LduMatrix.C
LduMatrixOperations.C
LduMatrixSolver.C
LduMatrixPreconditioner.C
LduMatrixTests.C
LduMatrixUpdateMatrixInterfaces.C
Definition at line 83 of file LduMatrix.H.
Constructor & Destructor Documentation
LduMatrix() [1/4]
template<class Type , class DType , class LUType > LduMatrix (const lduMesh & mesh)
Definition at line 27 of file LduMatrix.C.
LduMatrix() [2/4]
template<class Type , class DType , class LUType > LduMatrix (const LduMatrix< Type, DType, LUType > &)
LduMatrix() [3/4]
template<class Type , class DType , class LUType > LduMatrix (LduMatrix< Type, DType, LUType > & , bool reuse)
LduMatrix() [4/4]
template<class Type , class DType , class LUType > LduMatrix (const lduMesh & mesh, Istream & is)
Definition at line 138 of file LduMatrix.C.
~LduMatrix()
template<class Type , class DType , class LUType > ~LduMatrix ()
Definition at line 158 of file LduMatrix.C.
Member Function Documentation
ClassName()
template<class Type , class DType , class LUType > ClassName ("LduMatrix< Type, DType, LUType >")
mesh()
template<class Type , class DType , class LUType > const lduMesh & mesh () const inline noexcept
Definition at line 496 of file LduMatrix.H.
lduAddr()
template<class Type , class DType , class LUType > const lduAddressing & lduAddr () const inline
Definition at line 502 of file LduMatrix.H.
References lduMesh::lduAddr().
Referenced by LduMatrix< Type, DType, LUType >::patchSchedule().
patchSchedule()
template<class Type , class DType , class LUType > const lduSchedule & patchSchedule () const inline
Definition at line 508 of file LduMatrix.H.
References LduMatrix< Type, DType, LUType >::lduAddr().
interfaces() [1/2]
template<class Type , class DType , class LUType > const LduInterfaceFieldPtrsList< Type > & interfaces () const inline
Definition at line 514 of file LduMatrix.H.
interfaces() [2/2]
template<class Type , class DType , class LUType > LduInterfaceFieldPtrsList< Type > & interfaces () inline
Definition at line 520 of file LduMatrix.H.
diag() [1/2]
template<class Type , class DType , class LUType > Foam::Field< DType > & diag ()
Definition at line 185 of file LduMatrix.C.
References Foam::Zero.
upper() [1/2]
template<class Type , class DType , class LUType > Foam::Field< LUType > & upper ()
Definition at line 197 of file LduMatrix.C.
References Foam::Zero.
Referenced by LduMatrix< Type, DType, LUType >::faceH(), LduMatrix< Type, DType, LUType >::negSumDiag(), LduMatrix< Type, DType, LUType >::sumDiag(), and LduMatrix< Type, DType, LUType >::sumMagOffDiag().
lower() [1/2]
template<class Type , class DType , class LUType > Foam::Field< LUType > & lower ()
Definition at line 220 of file LduMatrix.C.
References Foam::Zero.
Referenced by LduMatrix< Type, DType, LUType >::faceH(), LduMatrix< Type, DType, LUType >::negSumDiag(), LduMatrix< Type, DType, LUType >::sumDiag(), and LduMatrix< Type, DType, LUType >::sumMagOffDiag().
source() [1/2]
template<class Type , class DType , class LUType > Foam::Field< Type > & source ()
Definition at line 243 of file LduMatrix.C.
References Foam::Zero.
interfacesUpper() [1/2]
template<class Type , class DType , class LUType > FieldField< Field, LUType > & interfacesUpper () inline
Definition at line 533 of file LduMatrix.H.
interfacesLower() [1/2]
template<class Type , class DType , class LUType > FieldField< Field, LUType > & interfacesLower () inline
Definition at line 538 of file LduMatrix.H.
diag() [2/2]
template<class Type , class DType , class LUType > const Foam::Field< DType > & diag () const
Definition at line 255 of file LduMatrix.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
upper() [2/2]
template<class Type , class DType , class LUType > const Foam::Field< LUType > & upper () const
Definition at line 269 of file LduMatrix.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
lower() [2/2]
template<class Type , class DType , class LUType > const Foam::Field< LUType > & lower () const
Definition at line 290 of file LduMatrix.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
source() [2/2]
template<class Type , class DType , class LUType > const Foam::Field< Type > & source () const
Definition at line 311 of file LduMatrix.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
interfacesUpper() [2/2]
template<class Type , class DType , class LUType > const FieldField< Field, LUType > & interfacesUpper () const inline
Definition at line 549 of file LduMatrix.H.
interfacesLower() [2/2]
template<class Type , class DType , class LUType > const FieldField< Field, LUType > & interfacesLower () const inline
Definition at line 554 of file LduMatrix.H.
hasDiag()
template<class Type , class DType , class LUType > bool hasDiag () const inline noexcept
Definition at line 560 of file LduMatrix.H.
hasUpper()
template<class Type , class DType , class LUType > bool hasUpper () const inline noexcept
Definition at line 565 of file LduMatrix.H.
hasLower()
template<class Type , class DType , class LUType > bool hasLower () const inline noexcept
Definition at line 570 of file LduMatrix.H.
hasSource()
template<class Type , class DType , class LUType > bool hasSource () const inline noexcept
Definition at line 575 of file LduMatrix.H.
diagonal()
template<class Type , class DType , class LUType > bool diagonal () const inline noexcept
Definition at line 580 of file LduMatrix.H.
symmetric()
template<class Type , class DType , class LUType > bool symmetric () const inline noexcept
Definition at line 585 of file LduMatrix.H.
asymmetric()
template<class Type , class DType , class LUType > bool asymmetric () const inline noexcept
Definition at line 590 of file LduMatrix.H.
sumDiag()
template<class Type , class DType , class LUType > void sumDiag ()
Definition at line 27 of file LduMatrixOperations.C.
References Foam::diag(), LduMatrix< Type, DType, LUType >::lower(), UList< T >::size(), and LduMatrix< Type, DType, LUType >::upper().
negSumDiag()
template<class Type , class DType , class LUType > void negSumDiag ()
Definition at line 45 of file LduMatrixOperations.C.
References Foam::diag(), LduMatrix< Type, DType, LUType >::lower(), UList< T >::size(), and LduMatrix< Type, DType, LUType >::upper().
sumMagOffDiag()
template<class Type , class DType , class LUType > void sumMagOffDiag (Field< LUType > & sumOff) const
Definition at line 63 of file LduMatrixOperations.C.
References Foam::cmptMag(), LduMatrix< Type, DType, LUType >::lower(), UList< T >::size(), and LduMatrix< Type, DType, LUType >::upper().
Amul()
template<class Type , class DType , class LUType > void Amul (Field< Type > & Apsi, const tmp< Field< Type > > & tpsi) const
Definition at line 27 of file LduMatrixATmul.C.
References UPtrList< T >::begin(), PtrList< T >::clear(), Foam::diag(), Foam::dot(), UPstream::nRequests(), psi, PtrList< T >::PtrList(), and UPtrList< T >::size().
Tmul()
template<class Type , class DType , class LUType > void Tmul (Field< Type > & Tpsi, const tmp< Field< Type > > & tpsi) const
Definition at line 86 of file LduMatrixATmul.C.
References UPtrList< T >::begin(), PtrList< T >::clear(), Foam::diag(), Foam::dot(), UPstream::nRequests(), psi, and UPtrList< T >::size().
sumA()
template<class Type , class DType , class LUType > void sumA (Field< Type > & sumA) const
Definition at line 144 of file LduMatrixATmul.C.
References UPtrList< T >::begin(), Foam::diag(), Foam::dot(), forAll, and UPtrList< T >::size().
residual() [1/2]
template<class Type , class DType , class LUType > void residual (Field< Type > & rA, const Field< Type > & psi) const
Definition at line 192 of file LduMatrixATmul.C.
References UPtrList< T >::begin(), Foam::diag(), Foam::dot(), UPstream::nRequests(), psi, and UPtrList< T >::size().
residual() [2/2]
template<class Type , class DType , class LUType > Foam::tmp< Foam::Field< Type > > residual (const Field< Type > & psi) const
Definition at line 252 of file LduMatrixATmul.C.
References Foam::New(), psi, and UPtrList< T >::size().
initMatrixInterfaces()
template<class Type , class DType , class LUType > void initMatrixInterfaces (const bool add, const FieldField< Field, LUType > & interfaceCoeffs, const Field< Type > & psiif, Field< Type > & result) const
Definition at line 28 of file LduMatrixUpdateMatrixInterfaces.C.
References Foam::add(), UPstream::blocking, UPstream::commsTypeNames, UPstream::defaultCommsType, Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, UPstream::nonBlocking, PtrList< T >::PtrList(), UPstream::scheduled, UPtrList< T >::size(), and UList< T >::size().
updateMatrixInterfaces()
template<class Type , class DType , class LUType > void updateMatrixInterfaces (const bool add, const FieldField< Field, LUType > & interfaceCoeffs, const Field< Type > & psiif, Field< Type > & result, const label startRequest) const
Definition at line 100 of file LduMatrixUpdateMatrixInterfaces.C.
References Foam::add(), UPstream::blocking, UPstream::commsTypeNames, UPstream::defaultCommsType, Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, UPtrList< T >::get(), UPstream::nonBlocking, UPstream::nPollProcInterfaces, UPstream::scheduled, UPtrList< T >::size(), UList< T >::size(), UPstream::waitRequests(), and UPstream::waitSomeRequests().
H() [1/2]
template<class Type , class DType , class LUType > Foam::tmp< Foam::Field< Type > > H (const Field< Type > & psi) const
Definition at line 84 of file LduMatrixOperations.C.
References UPtrList< T >::begin(), psi, and Foam::Zero.
H() [2/2]
template<class Type , class DType , class LUType > Foam::tmp< Foam::Field< Type > > H (const tmp< Field< Type > > & tpsi) const
Definition at line 119 of file LduMatrixOperations.C.
References PtrList< T >::clear(), and H().
faceH() [1/2]
template<class Type , class DType , class LUType > Foam::tmp< Foam::Field< Type > > faceH (const Field< Type > & psi) const
Definition at line 129 of file LduMatrixOperations.C.
References LduMatrix< Type, DType, LUType >::lower(), Foam::New(), psi, UPtrList< T >::size(), UList< T >::size(), and LduMatrix< Type, DType, LUType >::upper().
faceH() [2/2]
template<class Type , class DType , class LUType > Foam::tmp< Foam::Field< Type > > faceH (const tmp< Field< Type > > & tpsi) const
Definition at line 152 of file LduMatrixOperations.C.
References PtrList< T >::clear().
operator=()
template<class Type , class DType , class LUType > void operator= (const LduMatrix< Type, DType, LUType > &)
Definition at line 163 of file LduMatrixOperations.C.
References A, and Foam::diag().
negate()
template<class Type , class DType , class LUType > void negate ()
Definition at line 206 of file LduMatrixOperations.C.
References Foam::negate().
operator+=()
template<class Type , class DType , class LUType > void operator+= (const LduMatrix< Type, DType, LUType > &)
Definition at line 234 of file LduMatrixOperations.C.
References A, Foam::abort(), Foam::diag(), Foam::FatalError, and FatalErrorInFunction.
operator-=()
template<class Type , class DType , class LUType > void operator-= (const LduMatrix< Type, DType, LUType > &)
Definition at line 311 of file LduMatrixOperations.C.
References A, Foam::abort(), Foam::diag(), Foam::FatalError, and FatalErrorInFunction.
operator*=() [1/2]
template<class Type , class DType , class LUType > void operator*= (const scalarField & sf)
Definition at line 388 of file LduMatrixOperations.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
operator*=() [2/2]
template<class Type , class DType , class LUType > void operator*= (scalar s)
Definition at line 436 of file LduMatrixOperations.C.
References s().
Friends And Related Symbol Documentation
SolverPerformance< Type >
template<class Type , class DType , class LUType > friend class SolverPerformance< Type > friend
Definition at line 103 of file LduMatrix.H.
operator
template<class Type , class DType , class LUType > Ostream & operator (Ostream & , const LduMatrix< Type, DType, LUType > &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/LduMatrix/LduMatrix/LduMatrix.H
src/OpenFOAM/matrices/LduMatrix/LduMatrix/LduMatrix.C
src/OpenFOAM/matrices/LduMatrix/LduMatrix/LduMatrixATmul.C
src/OpenFOAM/matrices/LduMatrix/LduMatrix/LduMatrixOperations.C
src/OpenFOAM/matrices/LduMatrix/LduMatrix/LduMatrixUpdateMatrixInterfaces.C