OpenFOAM: resolutionIndexModel Class Reference
resolutionIndexModel Class Reference abstract
A base class for resolutionIndex models.
#include <resolutionIndexModel.H>
Public Member Functions
TypeName ("resolutionIndexModel")
declareRunTimeSelectionTable (autoPtr, resolutionIndexModel, dictionary,(const word &name, const fvMesh &mesh, const dictionary &dict),(name, mesh, dict))
resolutionIndexModel (const word &name, const fvMesh &mesh, const dictionary &dict)
resolutionIndexModel (const resolutionIndexModel &)=delete
void operator= (const resolutionIndexModel &)=delete
virtual ~resolutionIndexModel ()=default
const fvMesh & mesh () const noexcept
const word & resultName () const noexcept
virtual bool read (const dictionary &dict)
virtual bool execute ()=0
virtual bool write ()=0
Static Public Member Functions
static autoPtr< resolutionIndexModel > New (const word &name, const fvMesh &mesh, const dictionary &dict)
Protected Member Functions
template<class GeoFieldType >
GeoFieldType & getOrReadField (const word &fieldName) const
tmp< volScalarField > V () const
Detailed Description
A base class for resolutionIndex models.
Source files
resolutionIndexModel.H
resolutionIndexModel.C
resolutionIndexModelNew.C
Definition at line 57 of file resolutionIndexModel.H.
Constructor & Destructor Documentation
resolutionIndexModel() [1/2]
resolutionIndexModel (const word & name, const fvMesh & mesh, const dictionary & dict)
Definition at line 66 of file resolutionIndexModel.C.
resolutionIndexModel() [2/2]
resolutionIndexModel (const resolutionIndexModel &) delete
~resolutionIndexModel()
virtual ~resolutionIndexModel () virtual default
Member Function Documentation
getOrReadField()
template<class GeoFieldType > GeoFieldType & getOrReadField (const word & fieldName) const protected
Definition at line 27 of file resolutionIndexModelTemplates.C.
References IOobjectOption::AUTO_WRITE, IOobjectOption::MUST_READ, and IOobjectOption::REGISTER.
V()
Foam::tmp< Foam::volScalarField > V () const protected
Definition at line 39 of file resolutionIndexModel.C.
References Foam::dimVolume, tmp< T >::New(), IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, and fvPatchFieldBase::zeroGradientType().
TypeName()
TypeName ("resolutionIndexModel")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , resolutionIndexModel , dictionary , (const word &name, const fvMesh &mesh, const dictionary &dict) , (name, mesh, dict))
New()
Foam::autoPtr< Foam::resolutionIndexModel > New (const word & name, const fvMesh & mesh, const dictionary & dict) static
Definition at line 26 of file resolutionIndexModelNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, Foam::Info, resolutionIndexModel::mesh(), Foam::name(), and Foam::nl.
Referenced by resolutionIndex::read().
operator=()
void operator= (const resolutionIndexModel &) delete
mesh()
const fvMesh & mesh () const inline noexcept
Definition at line 140 of file resolutionIndexModel.H.
Referenced by resolutionIndexModel::New().
resultName()
const word & resultName () const inline noexcept
Definition at line 146 of file resolutionIndexModel.H.
read()
bool read (const dictionary & dict) virtual
Reimplemented in CelikEtaIndex, CelikNuIndex, and PopeIndex.
Definition at line 80 of file resolutionIndexModel.C.
References dict, Foam::dimless, dictionary::getOrDefault(), IOobjectOption::LAZY_READ, IOobjectOption::NO_WRITE, IOobjectOption::REGISTER, Foam::type(), Foam::Zero, and fvPatchFieldBase::zeroGradientType().
Referenced by CelikEtaIndex::read(), CelikNuIndex::read(), and PopeIndex::read().
execute()
virtual bool execute () pure virtual
Implemented in CelikEtaIndex, CelikNuIndex, and PopeIndex.
write()
virtual bool write () pure virtual
Implemented in CelikEtaIndex, CelikNuIndex, and PopeIndex.
The documentation for this class was generated from the following files:
src/functionObjects/field/resolutionIndex/resolutionIndexModels/resolutionIndexModel/resolutionIndexModel.H
src/functionObjects/field/resolutionIndex/resolutionIndexModels/resolutionIndexModel/resolutionIndexModel.C
src/functionObjects/field/resolutionIndex/resolutionIndexModels/resolutionIndexModel/resolutionIndexModelNew.C
src/functionObjects/field/resolutionIndex/resolutionIndexModels/resolutionIndexModel/resolutionIndexModelTemplates.C