OpenFOAM: totalPressureFvPatchScalarField Class Reference
totalPressureFvPatchScalarField Class Reference
Boundary conditions » Inlet | Boundary conditions » Outlet
This boundary condition provides a total pressure condition. Four variants are possible:
#include <totalPressureFvPatchScalarField.H>
Public Member Functions
TypeName ("totalPressure")
totalPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
totalPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
totalPressureFvPatchScalarField (const totalPressureFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
totalPressureFvPatchScalarField (const totalPressureFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
totalPressureFvPatchScalarField (const totalPressureFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
const word & UName () const
word & UName ()
const word & phiName () const
word & phiName ()
const word & rhoName () const
word & rhoName ()
const word & psiName () const
word & psiName ()
scalar gamma () const
scalar & gamma ()
const scalarField & p0 () const
scalarField & p0 ()
virtual void autoMap (const fvPatchFieldMapper &)
virtual void rmap (const fvPatchScalarField &, const labelList &)
virtual void updateCoeffs (const scalarField &p0p, const vectorField &Up)
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
This boundary condition provides a total pressure condition. Four variants are possible:
1. incompressible subsonic:
where
= incompressible pressure at patch [m2/s2]
= incompressible total pressure [m2/s2]
= velocity
2. compressible subsonic:
where
= pressure at patch [Pa]
= total pressure [Pa]
= density [kg/m3]
= velocity
3. compressible transonic ():
where
= pressure at patch [Pa]
= total pressure [Pa]
= coefficient given by
4. compressible supersonic ():
where
= pressure at patch [Pa]
= total pressure [Pa]
= ratio of specific heats (Cp/Cv)
= compressibility [m2/s2]
= coefficient given by
The modes of operation are set by the dimensions of the pressure field to which this boundary condition is applied, the psi entry and the value of gamma:
Mode dimensions psi gamma
incompressible subsonic p/rho
compressible subsonic p none
compressible transonic p psi 1
compressible supersonic p psi > 1
Usage
Property Description Required Default value
U Velocity field name no U
phi Flux field name no phi
rho Density field name no rho
psi Compressibility field name no none
gamma (Cp/Cv) no 1
p0 Total pressure yes
Example of the boundary condition specification:
    <patchName>
    {
        type            totalPressure;
        p0              uniform 1e5;
    }
See also
Foam::fixedValueFvPatchField
Source files
totalPressureFvPatchScalarField.H
totalPressureFvPatchScalarField.C
Definition at line 252 of file totalPressureFvPatchScalarField.H.
Constructor & Destructor Documentation
totalPressureFvPatchScalarField() [1/5]
totalPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 31 of file totalPressureFvPatchScalarField.C.
totalPressureFvPatchScalarField() [2/5]
totalPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 47 of file totalPressureFvPatchScalarField.C.
References dict, and fvPatchField< Type >::operator=().
totalPressureFvPatchScalarField() [3/5]
totalPressureFvPatchScalarField (const totalPressureFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 69 of file totalPressureFvPatchScalarField.C.
totalPressureFvPatchScalarField() [4/5]
totalPressureFvPatchScalarField (const totalPressureFvPatchScalarField & tppsf)
Definition at line 87 of file totalPressureFvPatchScalarField.C.
totalPressureFvPatchScalarField() [5/5]
totalPressureFvPatchScalarField (const totalPressureFvPatchScalarField & tppsf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 102 of file totalPressureFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("totalPressure")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Reimplemented in fanPressureFvPatchScalarField, and rotatingTotalPressureFvPatchScalarField.
Definition at line 318 of file totalPressureFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Reimplemented in fanPressureFvPatchScalarField, and rotatingTotalPressureFvPatchScalarField.
Definition at line 334 of file totalPressureFvPatchScalarField.H.
UName() [1/2]
const word & UName () const inline
Definition at line 351 of file totalPressureFvPatchScalarField.H.
UName() [2/2]
word & UName () inline
Definition at line 358 of file totalPressureFvPatchScalarField.H.
phiName() [1/2]
const word & phiName () const inline
Definition at line 364 of file totalPressureFvPatchScalarField.H.
phiName() [2/2]
word & phiName () inline
Definition at line 371 of file totalPressureFvPatchScalarField.H.
rhoName() [1/2]
const word & rhoName () const inline
Definition at line 377 of file totalPressureFvPatchScalarField.H.
rhoName() [2/2]
word & rhoName () inline
Definition at line 384 of file totalPressureFvPatchScalarField.H.
psiName() [1/2]
const word & psiName () const inline
Definition at line 390 of file totalPressureFvPatchScalarField.H.
psiName() [2/2]
word & psiName () inline
Definition at line 397 of file totalPressureFvPatchScalarField.H.
gamma() [1/2]
scalar gamma () const inline
Definition at line 403 of file totalPressureFvPatchScalarField.H.
gamma() [2/2]
scalar & gamma () inline
Definition at line 409 of file totalPressureFvPatchScalarField.H.
p0() [1/2]
const scalarField & p0 () const inline
Definition at line 415 of file totalPressureFvPatchScalarField.H.
p0() [2/2]
scalarField & p0 () inline
Definition at line 421 of file totalPressureFvPatchScalarField.H.
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Definition at line 120 of file totalPressureFvPatchScalarField.C.
rmap()
void rmap (const fvPatchScalarField & ptf, const labelList & addr) virtual
Definition at line 130 of file totalPressureFvPatchScalarField.C.
updateCoeffs() [1/2]
void updateCoeffs (const scalarField & p0p, const vectorField & Up) virtual
Definition at line 145 of file totalPressureFvPatchScalarField.C.
References Foam::dimDensity, Foam::dimPressure, Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::magSqr(), Foam::neg(), Foam::nl, Foam::operator==(), Foam::pow(), and rho.
updateCoeffs() [2/2]
void updateCoeffs () virtual
Reimplemented in fanPressureFvPatchScalarField, and rotatingTotalPressureFvPatchScalarField.
Definition at line 221 of file totalPressureFvPatchScalarField.C.
References p0, and UName().
Referenced by fanPressureFvPatchScalarField::updateCoeffs(), and rotatingTotalPressureFvPatchScalarField::updateCoeffs().
write()
void write (Ostream & os) const virtual
Reimplemented in rotatingTotalPressureFvPatchScalarField, and fanPressureFvPatchScalarField.
Definition at line 231 of file totalPressureFvPatchScalarField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntry(), Ostream::writeEntryIfDifferent(), and fvPatchField< Type >::writeValueEntry().
Referenced by rotatingTotalPressureFvPatchScalarField::write(), and fanPressureFvPatchScalarField::write().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/totalPressure/totalPressureFvPatchScalarField.H
src/finiteVolume/fields/fvPatchFields/derived/totalPressure/totalPressureFvPatchScalarField.C