OpenFOAM: fixedPressureCompressibleDensityFvPatchScalarField Class Reference
fixedPressureCompressibleDensityFvPatchScalarField Class Reference
Boundary conditions » Inlet
This boundary condition calculates a (liquid) compressible density as a function of pressure and fluid properties:
#include <fixedPressureCompressibleDensityFvPatchScalarField.H>
Public Member Functions
TypeName ("fixedPressureCompressibleDensity")
fixedPressureCompressibleDensityFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
fixedPressureCompressibleDensityFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
fixedPressureCompressibleDensityFvPatchScalarField (const fixedPressureCompressibleDensityFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
fixedPressureCompressibleDensityFvPatchScalarField (const fixedPressureCompressibleDensityFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
fixedPressureCompressibleDensityFvPatchScalarField (const fixedPressureCompressibleDensityFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
This boundary condition calculates a (liquid) compressible density as a function of pressure and fluid properties:
where
= density [kg/m3]
= saturation liquid density [kg/m3]
= liquid compressibility
= pressure [Pa]
= saturation pressure [Pa]
The variables rholSat, pSat and psil are retrieved from the thermodynamicProperties dictionary.
Usage
Property Description Required Default value
p pressure field name no p
Example of the boundary condition specification:
    <patchName>
    {
        type        fixedPressureCompressibleDensity;
        p           p;
        value       uniform 1;
    }
See also
Foam::fixedValueFvPatchField
Source files
fixedPressureCompressibleDensityFvPatchScalarField.H
fixedPressureCompressibleDensityFvPatchScalarField.C
Definition at line 116 of file fixedPressureCompressibleDensityFvPatchScalarField.H.
Constructor & Destructor Documentation
fixedPressureCompressibleDensityFvPatchScalarField() [1/5]
fixedPressureCompressibleDensityFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 30 of file fixedPressureCompressibleDensityFvPatchScalarField.C.
fixedPressureCompressibleDensityFvPatchScalarField() [2/5]
fixedPressureCompressibleDensityFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 56 of file fixedPressureCompressibleDensityFvPatchScalarField.C.
fixedPressureCompressibleDensityFvPatchScalarField() [3/5]
fixedPressureCompressibleDensityFvPatchScalarField (const fixedPressureCompressibleDensityFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 42 of file fixedPressureCompressibleDensityFvPatchScalarField.C.
fixedPressureCompressibleDensityFvPatchScalarField() [4/5]
fixedPressureCompressibleDensityFvPatchScalarField (const fixedPressureCompressibleDensityFvPatchScalarField & ptf)
Definition at line 69 of file fixedPressureCompressibleDensityFvPatchScalarField.C.
fixedPressureCompressibleDensityFvPatchScalarField() [5/5]
fixedPressureCompressibleDensityFvPatchScalarField (const fixedPressureCompressibleDensityFvPatchScalarField & ptf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 80 of file fixedPressureCompressibleDensityFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("fixedPressureCompressibleDensity")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 167 of file fixedPressureCompressibleDensityFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 183 of file fixedPressureCompressibleDensityFvPatchScalarField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 94 of file fixedPressureCompressibleDensityFvPatchScalarField.C.
References Foam::operator==(), pp(), fvPatchField< Type >::updateCoeffs(), and dimensioned< Type >::value().
write()
void write (Ostream & os) const virtual
Definition at line 118 of file fixedPressureCompressibleDensityFvPatchScalarField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntryIfDifferent(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/fixedPressureCompressibleDensity/fixedPressureCompressibleDensityFvPatchScalarField.H
src/finiteVolume/fields/fvPatchFields/derived/fixedPressureCompressibleDensity/fixedPressureCompressibleDensityFvPatchScalarField.C