OpenFOAM: limitVelocity Class Reference
limitVelocity Class Reference
Corrects velocity field (i.e. T) within a specified region by applying a given maximum velocity magnitude limit.
#include <limitVelocity.H>
Public Member Functions
TypeName ("limitVelocity")
limitVelocity (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
limitVelocity (const limitVelocity &)=delete
void operator= (const limitVelocity &)=delete
virtual ~limitVelocity ()=default
virtual bool read (const dictionary &dict)
virtual void correct (volVectorField &U)
Public Member Functions inherited from cellSetOption
TypeName ("cellSetOption")
cellSetOption (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
virtual ~cellSetOption ()=default
scalar timeStart () const noexcept
scalar duration () const noexcept
bool inTimeLimits (const scalar timeValue) const
bool useSubMesh () const noexcept
selectionModeType selectionMode () const noexcept
const wordRes & selectionNames () const noexcept
const wordRe & zoneName () const
scalar V () const noexcept
const labelList & cells () const noexcept
scalar timeStart (scalar val) noexcept
scalar duration (scalar val) noexcept
virtual bool isActive ()
const word & cellSetName () const
Public Member Functions inherited from option
TypeName ("option")
declareRunTimeSelectionTable (autoPtr, option, dictionary,(const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh),(name, modelType, dict, mesh))
option (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
autoPtr< option > clone () const
virtual ~option ()=default
const word & name () const noexcept
const fvMesh & mesh () const noexcept
const dictionary & coeffs () const noexcept
bool active () const noexcept
void setApplied (const label fieldi)
bool active (const bool on) noexcept
virtual label applyToField (const word &fieldName) const
virtual void checkApplied () const
virtual void addSup (fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (fvMatrix< vector > &eqn, const label fieldi)
virtual void addSup (fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (fvMatrix< tensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< scalar > &eqn, const label fieldi)
virtual void constrain (fvMatrix< vector > &eqn, const label fieldi)
virtual void constrain (fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< tensor > &eqn, const label fieldi)
virtual void correct (volScalarField &field)
virtual void correct (volSphericalTensorField &field)
virtual void correct (volSymmTensorField &field)
virtual void correct (volTensorField &field)
virtual void postProcessSens (scalarField &sensField, const word &fieldName=word::null, const word &designVariablesName=word::null)
virtual void postProcessSens (vectorField &sensField, const word &fieldName=word::null, const word &designVariablesName=word::null)
virtual void postProcessSens (tensorField &sensField, const word &fieldName=word::null, const word &designVariablesName=word::null)
virtual void writeHeader (Ostream &) const
virtual void writeFooter (Ostream &) const
virtual void writeData (Ostream &) const
Public Member Functions inherited from writeFile
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name="undefined", const bool writeToFile=true)
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name, const dictionary &dict, const bool writeToFile=true)
writeFile (const writeFile &wf)
virtual ~writeFile ()=default
virtual OFstream & file ()
virtual bool writeToFile () const
virtual bool canWriteToFile () const
virtual bool canResetFile () const
virtual bool canWriteHeader () const
virtual label charWidth () const
virtual void writeCommented (Ostream &os, const string &str) const
virtual void writeTabbed (Ostream &os, const string &str) const
virtual void writeHeader (Ostream &os, const string &str) const
virtual void writeCurrentTime (Ostream &os) const
virtual void writeBreak (Ostream &os) const
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
template<class Type >
void writeValue (Ostream &os, const Type &val) const
Protected Member Functions
void writeFileHeader (Ostream &os)
Protected Member Functions inherited from cellSetOption
void setSelection (const dictionary &dict)
void setCellSelection ()
void setVol ()
Protected Member Functions inherited from option
void resetApplied ()
Protected Member Functions inherited from writeFile
void initStream (Ostream &os) const
fileName baseFileDir () const
fileName baseTimeDir () const
fileName filePath (const fileName &fName) const
virtual autoPtr< OFstream > newFile (const fileName &fName) const
virtual autoPtr< OFstream > newFileAtTime (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > newFileAtStartTime (const word &name) const
virtual void resetFile (const word &name)
Omanip< int > valueWidth (const label offset=0) const
void operator= (const writeFile &)=delete
virtual autoPtr< OFstream > createFile (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > createFile (const word &name) const
Protected Attributes
word UName_
scalar max_
Protected Attributes inherited from cellSetOption
scalar timeStart_
scalar duration_
selectionModeType selectionMode_
wordRes selectionNames_
List< point > points_
dictionary geometricSelection_
labelList cells_
scalar V_
Protected Attributes inherited from option
const word name_
const word modelType_
const fvMesh & mesh_
dictionary dict_
dictionary coeffs_
wordList fieldNames_
List< bool > applied_
bool active_
Protected Attributes inherited from writeFile
const objectRegistry & fileObr_
const fileName prefix_
word fileName_
autoPtr< OFstream > filePtr_
label writePrecision_
bool writeToFile_
bool updateHeader_
bool writtenHeader_
bool useUserTime_
scalar startTime_
Additional Inherited Members
Public Types inherited from cellSetOption
enum selectionModeType {
smAll , smCellSet , smCellZone , smPoints ,
smGeometric , smCellType
}
Static Public Member Functions inherited from option
static autoPtr< option > New (const word &name, const dictionary &dict, const fvMesh &mesh)
Public Attributes inherited from option
bool log
Static Public Attributes inherited from cellSetOption
static const Enum< selectionModeType > selectionModeTypeNames_
Static Public Attributes inherited from writeFile
static label addChars = 8
Detailed Description
Corrects velocity field (i.e. T) within a specified region by applying a given maximum velocity magnitude limit.
Corrections applied to:
  U    | Velocity                   [m/s]
Required fields:
  U    | Velocity                   [m/s]
Usage
Minimal example by using constant/fvOptions:
limitVelocity1
{
    // Mandatory entries (unmodifiable)
    type            limitVelocity;
    // Mandatory entries (runtime modifiable)
    max             <maxValue>;
    // Optional entries (runtime modifiable)
    U               <Uname>;
    // Mandatory/Optional (inherited) entries
    ...
}
where the entries mean:
Property Description Type Reqd Dflt
type Type name: limitVelocity word yes -
max Maximum velocity limit [m/s] scalar yes -
U Name of operand velocity field word no U
The inherited entries are elaborated in:
fvOption.H
cellSetOption.H
writeFile.H
See also
Foam::fv::velocityDampingConstraint
Source files
limitVelocity.H
limitVelocity.C
Definition at line 120 of file limitVelocity.H.
Constructor & Destructor Documentation
limitVelocity() [1/2]
limitVelocity (const word & name, const word & modelType, const dictionary & dict, const fvMesh & mesh)
Definition at line 57 of file limitVelocity.C.
References dict, fv(), and limitVelocity::read().
limitVelocity() [2/2]
limitVelocity (const limitVelocity &) delete
~limitVelocity()
virtual ~limitVelocity () virtual default
Member Function Documentation
writeFileHeader()
void writeFileHeader (Ostream & os) protected
Definition at line 40 of file limitVelocity.C.
References Foam::endl(), limitVelocity::max_, Foam::name(), os(), writeFile::writeCommented(), writeFile::writeHeaderValue(), writeFile::writeTabbed(), and writeFile::writtenHeader_.
TypeName()
TypeName ("limitVelocity")
operator=()
void operator= (const limitVelocity &) delete
read()
bool read (const dictionary & dict) virtual
Reimplemented from cellSetOption.
Definition at line 76 of file limitVelocity.C.
References dict, cellSetOption::read(), option::resetApplied(), and PtrList< T >::resize().
Referenced by limitVelocity::limitVelocity().
correct()
void correct (volVectorField & U) virtual
Reimplemented from option.
Definition at line 107 of file limitVelocity.C.
References e, Foam::endl(), Foam::Info, Foam::magSqr(), Foam::reduce(), Foam::returnReduce(), UPtrList< T >::size(), Foam::sqr(), Foam::sqrt(), token::TAB, Foam::type(), U, and cellSetOption::useSubMesh().
Member Data Documentation
UName_
word UName_ protected
Definition at line 130 of file limitVelocity.H.
max_
scalar max_ protected
Definition at line 133 of file limitVelocity.H.
Referenced by limitVelocity::writeFileHeader().
The documentation for this class was generated from the following files:
src/fvOptions/corrections/limitVelocity/limitVelocity.H
src/fvOptions/corrections/limitVelocity/limitVelocity.C