OpenFOAM: thermophysicalProperties Class Reference
thermophysicalProperties Class Reference abstract
Base-class for thermophysical properties of solids, liquids and gases providing an interface compatible with the templated thermodynamics packages.
#include <thermophysicalProperties.H>
Public Member Functions
TypeName ("thermophysicalProperties")
declareRunTimeSelectionTable (autoPtr, thermophysicalProperties,,(),())
declareRunTimeSelectionTable (autoPtr, thermophysicalProperties, dictionary,(const dictionary &dict),(dict))
thermophysicalProperties (scalar W)
thermophysicalProperties (const dictionary &dict)
virtual ~thermophysicalProperties ()=default
scalar W () const
scalar limit (const scalar T) const
virtual scalar rho (scalar p, scalar T) const =0
virtual scalar psi (scalar p, scalar T) const =0
virtual scalar CpMCv (scalar p, scalar T) const =0
virtual scalar Cp (const scalar p, const scalar T) const =0
virtual scalar Hs (const scalar p, const scalar T) const =0
virtual scalar Hc () const =0
virtual scalar Ha (const scalar p, const scalar T) const =0
virtual scalar S (const scalar p, const scalar T) const =0
virtual scalar mu (scalar p, scalar T) const =0
virtual scalar kappa (scalar p, scalar T) const =0
virtual scalar alphah (const scalar p, const scalar T) const =0
void readIfPresent (const dictionary &dict)
virtual void writeData (Ostream &os) const =0
Static Public Member Functions
static autoPtr< thermophysicalProperties > New (const word &name)
static autoPtr< thermophysicalProperties > New (const dictionary &dict)
Friends
Ostream & operator<< (Ostream &os, const thermophysicalProperties &l)
Detailed Description
Base-class for thermophysical properties of solids, liquids and gases providing an interface compatible with the templated thermodynamics packages.
Source files
thermophysicalProperties.H
thermophysicalPropertiesI.H
thermophysicalProperties.C
Definition at line 51 of file thermophysicalProperties.H.
Constructor & Destructor Documentation
thermophysicalProperties() [1/2]
thermophysicalProperties (scalar W)
Definition at line 35 of file thermophysicalProperties.C.
thermophysicalProperties() [2/2]
thermophysicalProperties (const dictionary & dict)
Definition at line 41 of file thermophysicalProperties.C.
~thermophysicalProperties()
virtual ~thermophysicalProperties () virtual default
Member Function Documentation
TypeName()
TypeName ("thermophysicalProperties")
declareRunTimeSelectionTable() [1/2]
declareRunTimeSelectionTable (autoPtr , thermophysicalProperties , () , ())
declareRunTimeSelectionTable() [2/2]
declareRunTimeSelectionTable (autoPtr , thermophysicalProperties , dictionary , (const dictionary &dict) , (dict))
New() [1/2]
Foam::autoPtr< Foam::thermophysicalProperties > New (const word & name) static
Definition at line 50 of file thermophysicalProperties.C.
References DebugInFunction, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInLookup, and Foam::name().
New() [2/2]
Foam::autoPtr< Foam::thermophysicalProperties > New (const dictionary & dict) static
Definition at line 74 of file thermophysicalProperties.C.
References DebugInFunction, dict, dictionary::dictName(), Foam::endl(), Foam::exit(), Foam::FatalIOError, and FatalIOErrorInLookup.
W()
Foam::scalar W () const inline
Definition at line 29 of file thermophysicalPropertiesI.H.
Referenced by Schroeder::TDNB().
limit()
Foam::scalar limit (const scalar T) const inline
Definition at line 23 of file thermophysicalPropertiesI.H.
References T.
rho()
virtual scalar rho (scalar p, scalar T) const pure virtual
Implemented in aC10H7CH3, Ar, bC10H7CH3, C10H22, C12H26, C13H28, C14H30, C16H34, C2H5OH, C2H6, C2H6O, C3H6O, C3H8, C4H10O, C6H14, C6H6, C7H16, C7H8, C8H10, C8H18, C9H20, CH3OH, CH4N2O, H2O, iC3H8O, IC8H18, IDEA, liquid, MB, N2, and nC3H8O.
psi()
virtual scalar psi (scalar p, scalar T) const pure virtual
Implemented in liquidProperties.
CpMCv()
virtual scalar CpMCv (scalar p, scalar T) const pure virtual
Implemented in liquidProperties.
Cp()
virtual scalar Cp (const scalar p, const scalar T) const pure virtual
Implemented in aC10H7CH3, Ar, bC10H7CH3, C10H22, C12H26, C13H28, C14H30, C16H34, C2H5OH, C2H6, C2H6O, C3H6O, C3H8, C4H10O, C6H14, C6H6, C7H16, C7H8, C8H10, C8H18, C9H20, CH3OH, CH4N2O, H2O, iC3H8O, IC8H18, IDEA, liquid, MB, N2, and nC3H8O.
Hs()
virtual scalar Hs (const scalar p, const scalar T) const pure virtual
Implemented in liquidProperties.
Hc()
virtual scalar Hc () const pure virtual
Implemented in liquidProperties.
Ha()
virtual scalar Ha (const scalar p, const scalar T) const pure virtual
Implemented in liquidProperties.
S()
virtual scalar S (const scalar p, const scalar T) const pure virtual
Implemented in liquidProperties.
mu()
virtual scalar mu (scalar p, scalar T) const pure virtual
Implemented in aC10H7CH3, Ar, bC10H7CH3, C10H22, C12H26, C13H28, C14H30, C16H34, C2H5OH, C2H6, C2H6O, C3H6O, C3H8, C4H10O, C6H14, C6H6, C7H16, C7H8, C8H10, C8H18, C9H20, CH3OH, CH4N2O, H2O, iC3H8O, IC8H18, IDEA, liquid, MB, N2, nC3H8O, and liquidProperties.
kappa()
virtual scalar kappa (scalar p, scalar T) const pure virtual
Implemented in aC10H7CH3, Ar, bC10H7CH3, C10H22, C12H26, C13H28, C14H30, C16H34, C2H5OH, C2H6, C2H6O, C3H6O, C3H8, C4H10O, C6H14, C6H6, C7H16, C7H8, C8H10, C8H18, C9H20, CH3OH, CH4N2O, H2O, iC3H8O, IC8H18, IDEA, liquid, MB, N2, nC3H8O, and liquidProperties.
alphah()
virtual scalar alphah (const scalar p, const scalar T) const pure virtual
Implemented in liquidProperties.
readIfPresent()
void readIfPresent (const dictionary & dict)
Definition at line 102 of file thermophysicalProperties.C.
References dict, and dictionary::readIfPresent().
Referenced by liquidProperties::readIfPresent().
writeData()
void writeData (Ostream & os) const pure virtual
Implemented in aC10H7CH3, Ar, bC10H7CH3, C10H22, C12H26, C13H28, C14H30, C16H34, C2H5OH, C2H6, C2H6O, C3H6O, C3H8, C4H10O, C6H14, C6H6, C7H16, C7H8, C8H10, C8H18, C9H20, CH3OH, CH4N2O, H2O, iC3H8O, IC8H18, IDEA, liquid, MB, N2, nC3H8O, and liquidProperties.
Definition at line 108 of file thermophysicalProperties.C.
References os().
Referenced by Foam::operator<<(), and liquidProperties::writeData().
Friends And Related Symbol Documentation
operator<<
Ostream & operator<< (Ostream & os, const thermophysicalProperties & l) friend
The documentation for this class was generated from the following files:
src/thermophysicalModels/thermophysicalProperties/thermophysicalProperties/thermophysicalProperties.H
src/thermophysicalModels/thermophysicalProperties/thermophysicalProperties/thermophysicalProperties.C
src/thermophysicalModels/thermophysicalProperties/thermophysicalProperties/thermophysicalPropertiesI.H