OpenFOAM: namedBlock Class Reference
namedBlock Class Reference
Gives name to a block.
#include <namedBlock.H>
Public Member Functions
TypeNameNoDebug ("name")
namedBlock (const dictionary &dict, const label index, const pointField &vertices, const blockEdgeList &edges, const blockFaceList &faces, Istream &is)
virtual ~namedBlock ()=default
Public Member Functions inherited from word
word ()=default
word (const word &)=default
word (word &&w)=default
word (const string &s, bool doStrip=true)
word (string &&s, bool doStrip=true)
word (const std::string &s, bool doStrip=true)
word (std::string &&s, bool doStrip=true)
word (const char *s, bool doStrip=true)
word (const char *s, size_type len, bool doStrip)
word (Istream &is)
void stripInvalid ()
word ext () const
word & ext (const word &ending)
word & replace_ext (const word &ending)
word lessExt () const
word & operator= (const word &s)
word & operator= (word &&s)
word & operator= (const string &s)
word & operator= (string &&s)
word & operator= (const std::string &s)
word & operator= (std::string &&s)
word & operator= (const char *s)
bool hasExt () const
bool hasExt (const std::string &s) const
bool removeExt ()
template<class PrimitiveType >
Foam::word printf (const char *fmt, const PrimitiveType &val)
template<class PrimitiveType >
Foam::word printf (const std::string &fmt, const PrimitiveType &val)
bool remove_ext ()
bool has_ext () const
bool has_ext (const char *ending) const
bool has_ext (const std::string &ending) const
bool has_ext (const wordRe &ending) const
Public Member Functions inherited from string
string ()=default
string (const std::string &str)
string (std::string &&str)
string (const char *str)
string (const char *str, const size_type len)
string (const char c)
string (const size_type len, const char c)
string (Istream &is)
bool match (const std::string &text) const
string & replace (const std::string &s1, const std::string &s2, size_type pos=0)
string & replaceAll (const std::string &s1, const std::string &s2, size_type pos=0)
string & replaceAny (const std::string &s1, const char c2, size_type pos=0)
string & expand (const bool allowEmpty=false)
bool removeRepeated (const char character)
bool removeStart (const std::string &text)
bool removeStart (const char c)
bool removeEnd (const std::string &text)
bool removeEnd (const char c)
void swap (std::string &str)
bool operator() (const std::string &text) const
bool contains (char c) const noexcept
bool contains (const std::string &s) const noexcept
bool contains (const char *s) const
bool starts_with (char c) const
bool starts_with (const std::string &s) const
bool starts_with (const char *s) const
bool ends_with (char c) const
bool ends_with (const std::string &s) const
bool ends_with (const char *s) const
size_type count (const char c) const
bool startsWith (const std::string &s) const
bool endsWith (const std::string &s) const
bool removeTrailing (const char c)
Public Member Functions inherited from block
TypeName ("block")
declareRunTimeSelectionTable (autoPtr, block, Istream,(const dictionary &dict, const label index, const pointField &vertices, const blockEdgeList &edges, const blockFaceList &faces, Istream &is),(dict, index, vertices, edges, faces, is))
block (const cellShape &bshape, const pointField &vertices, const blockEdgeList &edges, const blockFaceList &faces, const labelVector &density, const UList< gradingDescriptors > &expand=UList< gradingDescriptors >::null(), const word &zoneName="")
block (const dictionary &dict, const label index, const pointField &vertices, const blockEdgeList &edges, const blockFaceList &faces, Istream &is)
block (const blockDescriptor &blockDesc)
autoPtr< block > clone () const
virtual ~block ()=default
const pointField & points () const noexcept
const List< hexCell > & cells () const
const FixedList< List< FixedList< label, 4 > >, 6 > & boundaryPatches () const noexcept
cellShapeList shapes () const
Public Member Functions inherited from blockDescriptor
blockDescriptor (const blockDescriptor &)=default
void operator= (const blockDescriptor &)=delete
blockDescriptor (const cellShape &bshape, const pointField &vertices, const blockEdgeList &edges, const blockFaceList &faces, const labelVector &density, const UList< gradingDescriptors > &expand=UList< gradingDescriptors >::null(), const word &zoneName=word::null)
blockDescriptor (const dictionary &dict, const label blockIndex, const pointField &vertices, const blockEdgeList &edges, const blockFaceList &faces, Istream &is)
const pointField & vertices () const noexcept
const blockFaceList & blockFaces () const noexcept
const cellShape & blockShape () const noexcept
const labelVector & density () const noexcept
const List< gradingDescriptors > & grading () const noexcept
const word & zoneName () const noexcept
const FixedList< label, 6 > & curvedFaces () const noexcept
label nCurvedFaces () const noexcept
const point & blockPoint (const label i) const
label facePointLabel (const direction facei, const label i, const label j) const
bool vertex (const label i, const label j, const label k) const
bool edge (const label i, const label j, const label k) const
int edgesPointsWeights (pointField(&edgesPoints)[12], scalarList(&edgesWeights)[12]) const
bool edgePointsWeights (const label edgei, pointField &edgePoints, scalarList &edgeWeights, const label nDiv, const gradingDescriptors &gd=gradingDescriptors()) const
bool edgePointsWeights (const label edgei, pointField &edgePoints, scalarList &edgeWeights) const
bool flatFaceOrEdge (const label i, const label j, const label k) const
FixedList< pointField, 6 > facePoints (const pointField &points) const
void correctFacePoints (FixedList< pointField, 6 > &) const
InfoProxy< blockDescriptor > info () const noexcept
Public Member Functions inherited from ijkMesh
ijkMesh ()
ijkMesh (const labelVector &ijk)
ijkMesh (const label nx, const label ny, const label nz)
label nPoints () const
label nCells () const
label nFaces () const
label nInternalFaces () const
label nBoundaryFaces () const
label nBoundaryFaces (const direction shapeFacei) const
label cellLabel (const label i, const label j, const label k) const
label cellLabel (const labelVector &ijk) const
label pointLabel (const label i, const label j, const label k) const
label pointLabel (const labelVector &ijk) const
hexCell vertLabels (const label i, const label j, const label k) const
hexCell vertLabels (const labelVector &ijk) const
Public Member Functions inherited from ijkAddressing
ijkAddressing ()
ijkAddressing (const labelVector &ijk)
ijkAddressing (const label ni, const label nj, const label nk)
bool empty () const
const labelVector & sizes () const
labelVector & sizes ()
label size () const
const label & size (const vector::components cmpt) const
void clear ()
void reset (const label ni, const label nj, const label nk)
void reset (const labelVector &newSizes)
label index (const label i, const label j, const label k) const
label index (const labelVector &ijk) const
labelVector index (const label idx) const
void checkIndex (const label i, const label j, const label k, const bool allowExtra=false) const
void checkIndex (const labelVector &ijk, const bool allowExtra=false) const
void checkSizes () const
void checkSizes (const labelVector &other) const
void checkSizes (const label nTotal) const
Additional Inherited Members
Static Public Member Functions inherited from word
template<class PrimitiveType >
static word printf (const char *fmt, const PrimitiveType &val)
template<class PrimitiveType >
static word printf (const std::string &fmt, const PrimitiveType &val)
static bool valid (char c)
static word validate (const std::string &s, const bool prefix=false)
static word validate (const char *first, const char *last, const bool prefix=false)
Static Public Member Functions inherited from string
template<class StringType >
static bool valid (const std::string &str)
template<class StringType >
static bool stripInvalid (std::string &str)
template<class StringType >
static StringType validate (const std::string &str)
Static Public Member Functions inherited from block
static autoPtr< block > New (const dictionary &dict, const label index, const pointField &points, const blockEdgeList &edges, const blockFaceList &faces, Istream &)
Static Public Member Functions inherited from blockDescriptor
static void write (Ostream &, const label blocki, const dictionary &)
Static Public Attributes inherited from word
static const char *const typeName = "word"
static int debug
static const word null
Static Public Attributes inherited from string
static const char *const typeName = "string"
static int debug
static const string null
Protected Member Functions inherited from string
std::string::size_type find_ext () const
word ext () const
bool ext (const word &ending)
bool has_ext () const
bool has_ext (const char *ending) const
bool has_ext (const std::string &ending) const
bool has_ext (const wordRe &ending) const
bool remove_path ()
bool remove_ext ()
Static Protected Member Functions inherited from string
static std::string::size_type find_ext (const std::string &str)
template<class PrimitiveType >
static std::string::size_type string_printf (std::string &output, const char *fmt, const PrimitiveType &val)
template<class PrimitiveType >
static std::string::size_type string_printf (std::string &output, const std::string &fmt, const PrimitiveType &val)
Detailed Description
Gives name to a block.
Source files
namedBlock.H
namedBlock.C
Definition at line 49 of file namedBlock.H.
Constructor & Destructor Documentation
namedBlock()
namedBlock (const dictionary & dict, const label index, const pointField & vertices, const blockEdgeList & edges, const blockFaceList & faces, Istream & is)
Definition at line 39 of file namedBlock.C.
References dictionary::add(), dict, dictionary::findDict(), ijkAddressing::index(), and Foam::vertices().
~namedBlock()
virtual ~namedBlock () virtual default
Member Function Documentation
TypeNameNoDebug()
TypeNameNoDebug ("name")
The documentation for this class was generated from the following files:
src/mesh/blockMesh/blocks/namedBlock/namedBlock.H
src/mesh/blockMesh/blocks/namedBlock/namedBlock.C