OpenFOAM: RosinRammler Class Reference
RosinRammler Class Reference
Particle-size distribution model wherein random samples are drawn from the doubly-truncated two-parameter Rosin-Rammler (Weibull) probability density function:
#include <RosinRammler.H>
Public Member Functions
TypeName ("RosinRammler")
RosinRammler (const dictionary &dict, Random &rndGen)
RosinRammler (const RosinRammler &p)
virtual autoPtr< distributionModel > clone () const
void operator= (const RosinRammler &)=delete
virtual ~RosinRammler ()=default
virtual scalar sample () const
virtual scalar meanValue () const
Public Member Functions inherited from distributionModel
TypeName ("distributionModel")
declareRunTimeSelectionTable (autoPtr, distributionModel, dictionary,(const dictionary &dict, Random &rndGen),(dict, rndGen))
distributionModel (const word &name, const dictionary &dict, Random &rndGen)
distributionModel (const distributionModel &p)
virtual ~distributionModel ()=default
virtual scalar minValue () const
virtual scalar maxValue () const
Additional Inherited Members
Static Public Member Functions inherited from distributionModel
static autoPtr< distributionModel > New (const dictionary &dict, Random &rndGen)
Protected Member Functions inherited from distributionModel
virtual void check () const
Protected Attributes inherited from distributionModel
const dictionary distributionModelDict_
Random & rndGen_
scalar minValue_
scalar maxValue_
Detailed Description
Particle-size distribution model wherein random samples are drawn from the doubly-truncated two-parameter Rosin-Rammler (Weibull) probability density function:
where
= Rosin-Rammler probability density function
= Scale parameter
= Shape parameter
= Sample
= Minimum of the distribution
= Maximum of the distribution
Constraints:
Random samples are generated by the inverse transform sampling technique by using the quantile function of the doubly-truncated two-parameter Rosin-Rammler (Weibull) probability density function:
with
where is sample drawn from the uniform probability density function on the unit interval .
Reference:
    Doubly-truncated two-parameter Weibull distribution and its moments (tag:C):
        Crénin, F. (2015).
        Truncated Weibull Distribution Functions and Moments.
        SSRN 2690255.
        DOI:10.2139/ssrn.2690255
Usage
Minimal example by using constant/<CloudProperties>:
subModels
{
    injectionModels
    {
        <name>
        {
            ...
            sizeDistribution
            {
                type        RosinRammler;
                RosinRammlerDistribution
                {
                    lambda      <scaleParameterValue>;
                    n           <shapeParameterValue>;
                    minValue    <minValue>;
                    maxValue    <maxValue>;
                }
            }
        }
    }
}
where the entries mean:
Property Description Type Reqd Deflt
type Type name: RosinRammler word yes -
RosinRammlerDistribution Distribution settings dict yes -
lambda Scale parameter scalar yes -
n Shape parameter scalar yes -
minValue Minimum of the distribution scalar yes -
maxValue Maximum of the distribution scalar yes -
Source files
RosinRammler.H
RosinRammler.C
Definition at line 215 of file RosinRammler.H.
Constructor & Destructor Documentation
RosinRammler() [1/2]
RosinRammler (const dictionary & dict, Random & rndGen)
Definition at line 39 of file RosinRammler.C.
RosinRammler() [2/2]
RosinRammler (const RosinRammler & p)
Definition at line 73 of file RosinRammler.C.
~RosinRammler()
virtual ~RosinRammler () virtual default
Member Function Documentation
TypeName()
TypeName ("RosinRammler")
clone()
virtual autoPtr< distributionModel > clone () const inline virtual
Implements distributionModel.
Definition at line 243 of file RosinRammler.H.
operator=()
void operator= (const RosinRammler &) delete
sample()
Foam::scalar sample () const virtual
Implements distributionModel.
Definition at line 83 of file RosinRammler.C.
References Foam::exp(), Foam::log(), and Foam::pow().
meanValue()
Foam::scalar meanValue () const virtual
Implements distributionModel.
Definition at line 93 of file RosinRammler.C.
References Foam::exp(), Foam::gMax(), Foam::gMin(), Foam::Math::incGamma_P(), and Foam::pow().
The documentation for this class was generated from the following files:
src/lagrangian/distributionModels/RosinRammler/RosinRammler.H
src/lagrangian/distributionModels/RosinRammler/RosinRammler.C