OpenFOAM: filmRadiationModel Class Reference
filmRadiationModel Class Reference abstract
Base class for film radiation models.
#include <filmRadiationModel.H>
Public Member Functions
TypeName ("radiationModel")
declareRunTimeSelectionTable (autoPtr, filmRadiationModel, dictionary,(surfaceFilmRegionModel &film, const dictionary &dict),(film, dict))
filmRadiationModel (surfaceFilmRegionModel &film)
filmRadiationModel (const word &modelType, surfaceFilmRegionModel &film, const dictionary &dict)
virtual ~filmRadiationModel ()
virtual void correct ()=0
virtual tmp< volScalarField > Shs ()=0
Public Member Functions inherited from filmSubModelBase
filmSubModelBase (surfaceFilmRegionModel &film)
filmSubModelBase (surfaceFilmRegionModel &film, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
filmSubModelBase (const word &modelName, surfaceFilmRegionModel &film, const dictionary &dict, const word &baseName, const word &modelType)
virtual ~filmSubModelBase ()
virtual bool writeTime () const
const surfaceFilmRegionModel & film () const
surfaceFilmRegionModel & film ()
template<class FilmType >
const FilmType & filmType () const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
subModelBase (const subModelBase &smb)
virtual ~subModelBase ()=default
const word & modelName () const
const dictionary & dict () const
const word & baseName () const
const word & modelType () const
const dictionary & coeffDict () const
const dictionary & properties () const
virtual bool defaultCoeffs (const bool printMsg) const
virtual bool active () const
virtual void cacheFields (const bool store)
virtual fileName localPath () const
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
bool getModelDict (const word &entryName, dictionary &dict) const
template<class Type >
bool getModelProperty (const word &entryName, Type &value) const
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
virtual void write (Ostream &os) const
Static Public Member Functions
static autoPtr< filmRadiationModel > New (surfaceFilmRegionModel &film, const dictionary &dict)
Additional Inherited Members
Public Attributes inherited from subModelBase
bool log
Protected Member Functions inherited from subModelBase
bool inLine () const
Protected Attributes inherited from filmSubModelBase
surfaceFilmRegionModel & filmModel_
Protected Attributes inherited from subModelBase
const word modelName_
dictionary & properties_
const dictionary dict_
const word baseName_
const word modelType_
const dictionary coeffDict_
Detailed Description
Base class for film radiation models.
Source files
filmRadiationModel.H
filmRadiationModel.C
filmRadiationModelNew.C
Definition at line 52 of file filmRadiationModel.H.
Constructor & Destructor Documentation
filmRadiationModel() [1/2]
filmRadiationModel (surfaceFilmRegionModel & film)
Definition at line 39 of file filmRadiationModel.C.
filmRadiationModel() [2/2]
filmRadiationModel (const word & modelType, surfaceFilmRegionModel & film, const dictionary & dict)
Definition at line 45 of file filmRadiationModel.C.
~filmRadiationModel()
~filmRadiationModel () virtual
Definition at line 58 of file filmRadiationModel.C.
Member Function Documentation
TypeName()
TypeName ("radiationModel")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , filmRadiationModel , dictionary , (surfaceFilmRegionModel &film, const dictionary &dict) , (film, dict))
New()
autoPtr< filmRadiationModel > New (surfaceFilmRegionModel & film, const dictionary & dict) static
Definition at line 35 of file filmRadiationModelNew.C.
References subModelBase::dict(), Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, UPtrList< T >::get(), Foam::Info, and subModelBase::modelType().
correct()
virtual void correct () pure virtual
Implemented in constantRadiation, noRadiation, primaryRadiation, and standardRadiation.
Shs()
virtual tmp< volScalarField > Shs () pure virtual
Implemented in constantRadiation, noRadiation, primaryRadiation, and standardRadiation.
The documentation for this class was generated from the following files:
src/regionModels/surfaceFilmModels/submodels/thermo/filmRadiationModel/filmRadiationModel/filmRadiationModel.H
src/regionModels/surfaceFilmModels/submodels/thermo/filmRadiationModel/filmRadiationModel/filmRadiationModel.C
src/regionModels/surfaceFilmModels/submodels/thermo/filmRadiationModel/filmRadiationModel/filmRadiationModelNew.C