OpenFOAM: fixedTrim Class Reference
fixedTrim Class Reference
Trim model where the operating characteristics of rotor (e.g. blade pitch angle) are fixed, hence the possibility of varying thrust and torque.
#include <fixedTrim.H>
Public Member Functions
TypeName ("fixedTrim")
fixedTrim (const fv::rotorDiskSource &rotor, const dictionary &dict)
fixedTrim (const fixedTrim &)=delete
void operator= (const fixedTrim &)=delete
virtual ~fixedTrim ()=default
void read (const dictionary &dict)
virtual tmp< scalarField > thetag () const
virtual void correct (const vectorField &U, vectorField &force)
virtual void correct (const volScalarField rho, const vectorField &U, vectorField &force)
Public Member Functions inherited from trimModel
TypeName ("trimModel")
declareRunTimeSelectionTable (autoPtr, trimModel, dictionary,(const fv::rotorDiskSource &rotor, const dictionary &dict),(rotor, dict))
trimModel (const fv::rotorDiskSource &rotor, const dictionary &dict, const word &name)
virtual ~trimModel ()=default
Protected Attributes
scalarField thetag_
Protected Attributes inherited from trimModel
const fv::rotorDiskSource & rotor_
const word name_
dictionary coeffs_
Additional Inherited Members
Static Public Member Functions inherited from trimModel
static autoPtr< trimModel > New (const fv::rotorDiskSource &rotor, const dictionary &dict)
Detailed Description
Trim model where the operating characteristics of rotor (e.g. blade pitch angle) are fixed, hence the possibility of varying thrust and torque.
Usage
Minimal example by using constant/fvOptions: rotorDiskSource1 { Mandatory/Optional (inherited) entries ...
Mandatory entries (runtime modifiable) trimModel fixedTrim;
fixedTrimCoeffs { Conditional mandatory entries (runtime modifiable)
when trimModel=fixedTrim theta0 5.0; theta1c 1.0; theta1s 4.0; } }
See also
Foam::fv::rotorDiskSource
Foam::trimModel
Foam::targetCoeffTrim
Source files
fixedTrim.H
fixedTrim.C
Definition at line 75 of file fixedTrim.H.
Constructor & Destructor Documentation
fixedTrim() [1/2]
fixedTrim (const fv::rotorDiskSource & rotor, const dictionary & dict)
Definition at line 40 of file fixedTrim.C.
References dict, and fixedTrim::read().
fixedTrim() [2/2]
fixedTrim (const fixedTrim &) delete
~fixedTrim()
virtual ~fixedTrim () virtual default
Member Function Documentation
TypeName()
TypeName ("fixedTrim")
operator=()
void operator= (const fixedTrim &) delete
read()
void read (const dictionary & dict) virtual
Reimplemented from trimModel.
Definition at line 55 of file fixedTrim.C.
References Foam::cos(), Foam::degToRad(), dict, forAll, psi, trimModel::read(), Foam::sin(), and x.
Referenced by fixedTrim::fixedTrim().
thetag()
Foam::tmp< Foam::scalarField > thetag () const virtual
Implements trimModel.
Definition at line 72 of file fixedTrim.C.
correct() [1/2]
void correct (const vectorField & U, vectorField & force) virtual
Implements trimModel.
Definition at line 78 of file fixedTrim.C.
correct() [2/2]
void correct (const volScalarField rho, const vectorField & U, vectorField & force) virtual
Implements trimModel.
Definition at line 86 of file fixedTrim.C.
Member Data Documentation
thetag_
scalarField thetag_ protected
Definition at line 84 of file fixedTrim.H.
The documentation for this class was generated from the following files:
src/fvOptions/sources/derived/rotorDiskSource/trimModel/fixed/fixedTrim.H
src/fvOptions/sources/derived/rotorDiskSource/trimModel/fixed/fixedTrim.C