OpenFOAM: pointBoundaryMesh Class Reference
pointBoundaryMesh Class Reference
Foam::pointBoundaryMesh.
#include <pointBoundaryMesh.H>
Public Member Functions
pointBoundaryMesh (const pointMesh &, const polyBoundaryMesh &)
const pointMesh & mesh () const noexcept
labelList indices (const wordRe &matcher, const bool useGroups) const
labelList indices (const wordRes &matcher, const bool useGroups) const
label findPatchID (const word &patchName) const
void movePoints (const pointField &)
void updateMesh ()
labelList findIndices (const wordRe &key, bool useGroups) const
Public Member Functions inherited from PtrList< T >
constexpr PtrList () noexcept
PtrList (const label len)
PtrList (const PtrList< T > &list)
PtrList (PtrList< T > &&list)
PtrList (UList< T * > &list)
template<class CloneArg >
PtrList (const PtrList< T > &list, const CloneArg &cloneArgs)
PtrList (PtrList< T > &list, bool reuse)
PtrList (const SLPtrList< T > &list)
template<class INew >
PtrList (Istream &is, const INew &inew)
PtrList (Istream &is)
~PtrList ()
template<class... Args>
PtrList< T > clone (Args &&... args) const
const T * set (const label i) const
void clear ()
void free ()
void resize (const label newLen)
template<class... Args>
T & emplace_back (Args &&... args)
void push_back (T *ptr)
void push_back (std::unique_ptr< T > &&ptr)
void push_back (autoPtr< T > &&ptr)
void push_back (const refPtr< T > &ptr)
void push_back (const tmp< T > &ptr)
void push_back (PtrList< T > &&other)
template<class... Args>
T & emplace_set (const label i, Args &&... args)
template<class... Args>
T & emplace (const label i, Args &&... args)
autoPtr< T > set (const label i, T *ptr)
autoPtr< T > set (const label i, std::unique_ptr< T > &&ptr)
autoPtr< T > set (const label i, autoPtr< T > &&ptr)
autoPtr< T > set (const label i, const refPtr< T > &ptr)
autoPtr< T > set (const label i, const tmp< T > &ptr)
autoPtr< T > release (const label i)
void transfer (PtrList< T > &list)
void operator= (const PtrList< T > &list)
void operator= (PtrList< T > &&list)
void push_back (autoPtr< T > &ptr)=delete
autoPtr< T > set (const label i, autoPtr< T > &ptr)
void setSize (const label newLen)
void append (autoPtr< T > &ptr)
void append (T *ptr)
void append (std::unique_ptr< T > &&ptr)
void append (autoPtr< T > &&ptr)
void append (const refPtr< T > &ptr)
void append (const tmp< T > &ptr)
void append (PtrList< T > &&other)
template<class... Args>
Foam::PtrList< T > clone (Args &&... args) const
Public Member Functions inherited from UPtrList< T >
constexpr UPtrList () noexcept
UPtrList (const label len)
UPtrList (const UPtrList< T > &list)
UPtrList (UPtrList< T > &&list)
UPtrList (UPtrList< T > &list, bool reuse)
UPtrList (PtrList< T > &list)
UPtrList (const UList< T * > &list)
UPtrList (UList< T > &list)
bool empty () const noexcept
label size () const noexcept
label count () const noexcept
T & front ()
const T & front () const
T & back ()
const T & back () const
const T * test (const label i) const
const T * get (const label i) const
T * get (const label i)
const T * set (const label i) const
void clear ()
void free ()
void resize (const label newLen)
label squeezeNull ()
void trimTrailingNull ()
void push_back (T *ptr)
void push_back (UPtrList< T > &&other)
void swap (UPtrList< T > &list)
void transfer (UPtrList< T > &list)
T * set (const label i, T *ptr)
void reorder (const labelUList &oldToNew, const bool check=false)
void sortOrder (const labelUList &order, const bool check=false)
void checkNonNull () const
const T & at (const label i) const
T & at (const label i)
const T & operator[] (const label i) const
T & operator[] (const label i)
FOAM_DEPRECATED_FOR (2022-09, "get(), set() or test() methods") const T *operator()(const label i) const
void operator= (const UPtrList< T > &list)
void operator= (UPtrList< T > &&list)
T ** begin_ptr () noexcept
T ** end_ptr () noexcept
iterator begin ()
iterator end () noexcept
const_iterator cbegin () const
const_iterator cend () const noexcept
const_iterator begin () const
const_iterator end () const noexcept
void setSize (const label n)
T & first ()
const T & first () const
T & last ()
const T & last () const
void append (T *ptr)
void append (UPtrList< T > &&other)
Friends
class pointMesh
Additional Inherited Members
Public Types inherited from UPtrList< T >
typedef T value_type
typedef T & reference
typedef const T & const_reference
Protected Member Functions inherited from PtrList< T >
template<class INew >
void readIstream (Istream &is, const INew &inew)
Protected Member Functions inherited from UPtrList< T >
void setAddressableSize (const label n) noexcept
label find_next (label pos) const
UPtrList (Detail::PtrListDetail< T > &&ptrs)
Protected Attributes inherited from UPtrList< T >
Detail::PtrListDetail< T > ptrs_
Detailed Description
Foam::pointBoundaryMesh.
Source files
pointBoundaryMesh.H
pointBoundaryMesh.C
Definition at line 52 of file pointBoundaryMesh.H.
Constructor & Destructor Documentation
pointBoundaryMesh()
pointBoundaryMesh (const pointMesh & m, const polyBoundaryMesh & basicBdry)
Definition at line 32 of file pointBoundaryMesh.C.
References forAll, facePointPatch::New(), and PtrList< T >::set().
Member Function Documentation
mesh()
const pointMesh & mesh () const inline noexcept
Definition at line 93 of file pointBoundaryMesh.H.
indices() [1/2]
Foam::labelList indices (const wordRe & matcher, const bool useGroups) const
Definition at line 57 of file pointBoundaryMesh.C.
References polyMesh::boundaryMesh(), and mesh.
Referenced by pointBoundaryMesh::findIndices().
indices() [2/2]
Foam::labelList indices (const wordRes & matcher, const bool useGroups) const
Definition at line 67 of file pointBoundaryMesh.C.
References polyMesh::boundaryMesh(), and mesh.
findPatchID()
Foam::label findPatchID (const word & patchName) const
Definition at line 77 of file pointBoundaryMesh.C.
References polyMesh::boundaryMesh(), and mesh.
movePoints()
void movePoints (const pointField & p)
Definition at line 129 of file pointBoundaryMesh.C.
References UPstream::blocking, UPstream::defaultCommsType, forAll, polyMesh::globalData(), mesh, UPstream::nonBlocking, p, and UPstream::scheduled.
updateMesh()
void updateMesh ()
Definition at line 175 of file pointBoundaryMesh.C.
References UPstream::blocking, UPstream::defaultCommsType, forAll, polyMesh::globalData(), mesh, UPstream::nonBlocking, and UPstream::scheduled.
findIndices()
labelList findIndices (const wordRe & key, bool useGroups) const inline
Definition at line 121 of file pointBoundaryMesh.H.
References pointBoundaryMesh::indices().
Friends And Related Symbol Documentation
pointMesh
friend class pointMesh friend
Definition at line 77 of file pointBoundaryMesh.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/pointMesh/pointBoundaryMesh/pointBoundaryMesh.H
src/OpenFOAM/meshes/pointMesh/pointBoundaryMesh/pointBoundaryMesh.C