OpenFOAM: line< Point, PointRef > Class Template Reference
line< Point, PointRef > Class Template Reference
A line primitive.
#include <line.H>
Public Member Functions
line (const Point &from, const Point &to)
line (const UList< Point > &points, const FixedList< label, 2 > &indices)
line (Istream &is)
PointRef a () const noexcept
PointRef b () const noexcept
PointRef first () const noexcept
PointRef second () const noexcept
PointRef start () const noexcept
PointRef end () const noexcept
PointRef last () const noexcept
Point centre () const
scalar mag () const
Point vec () const
Point unitVec () const
Pair< Point > box () const
PointHit< Point > nearestDist (const Point &p) const
scalar nearestDist (const line< Point, const Point & > &edge, Point &thisPoint, Point &edgePoint) const
scalar nearestDist (const line< point2D, const point2D & > &e, point2D &thisPt, point2D &edgePt) const
scalar nearestDist (const line< point2D, const point2D & > &edge, point2D &thisPoint, point2D &edgePoint) const
Static Public Member Functions
static Pair< Point > box (const Point &p0, const Point &p1)
Friends
Istream & operator>> (Istream &, line &)
Ostream & operator (Ostream &, const line &)
Detailed Description
template<class Point, class PointRef>
class Foam::line< Point, PointRef >
A line primitive.
Source files
line.H
lineI.H
Definition at line 146 of file line.H.
Constructor & Destructor Documentation
line() [1/3]
template<class Point , class PointRef > line (const Point & from, const Point & to) inline
Definition at line 44 of file lineI.H.
line() [2/3]
template<class Point , class PointRef > line (const UList< Point > & points, const FixedList< label, 2 > & indices) inline
Definition at line 56 of file lineI.H.
line() [3/3]
template<class Point , class PointRef > line (Istream & is) inline explicit
Definition at line 68 of file lineI.H.
Member Function Documentation
a()
template<class Point , class PointRef > PointRef a () const inline noexcept
Definition at line 181 of file line.H.
b()
template<class Point , class PointRef > PointRef b () const inline noexcept
Definition at line 184 of file line.H.
first()
template<class Point , class PointRef > PointRef first () const inline noexcept
Definition at line 187 of file line.H.
second()
template<class Point , class PointRef > PointRef second () const inline noexcept
Definition at line 190 of file line.H.
start()
template<class Point , class PointRef > PointRef start () const inline noexcept
Definition at line 193 of file line.H.
end()
template<class Point , class PointRef > PointRef end () const inline noexcept
Definition at line 196 of file line.H.
last()
template<class Point , class PointRef > PointRef last () const inline noexcept
Definition at line 199 of file line.H.
box() [1/2]
template<class Point , class PointRef > Foam::Pair< Point > box (const Point & p0, const Point & p1) inline static
Definition at line 138 of file lineI.H.
References Foam::max(), Foam::min(), and p0.
centre()
template<class Point , class PointRef > Point centre () const inline
Definition at line 83 of file lineI.H.
mag()
template<class Point , class PointRef > Foam::scalar mag () const inline
Definition at line 96 of file lineI.H.
References b.
vec()
template<class Point , class PointRef > Point vec () const inline
Definition at line 109 of file lineI.H.
References b.
unitVec()
template<class Point , class PointRef > Point unitVec () const inline
Definition at line 122 of file lineI.H.
References Foam::mag(), s(), and Foam::Zero.
box() [2/2]
template<class Point , class PointRef > Foam::Pair< Point > box () const inline
Definition at line 149 of file lineI.H.
References line< Point, PointRef >::box().
Referenced by linePoints::box(), line< Point, PointRef >::box(), and edge::box().
nearestDist() [1/4]
template<class Point , class PointRef > Foam::PointHit< Point > nearestDist (const Point & p) const
Definition at line 162 of file lineI.H.
References b, Foam::mag(), and p.
Referenced by treeDataEdge::findNearest(), and treeDataEdge::overlaps().
nearestDist() [2/4]
template<class Point , class PointRef > Foam::scalar nearestDist (const line< Point, const Point & > & edge, Point & thisPoint, Point & edgePoint) const
Definition at line 194 of file lineI.H.
References b, edge::end(), Foam::mag(), Foam::magSqr(), Foam::max(), Foam::min(), s(), and edge::start().
nearestDist() [3/4]
scalar nearestDist (const line< point2D, const point2D & > & e, point2D & thisPt, point2D & edgePt) const
Definition at line 31 of file line.C.
References e, UPtrList< T >::end(), VectorSpace< Form, Cmpt, Ncmpts >::end(), Foam::mag(), Foam::max(), Foam::min(), Vector2D< Cmpt >::perp(), PtrList< T >::PtrList(), and s().
nearestDist() [4/4]
scalar nearestDist (const line< point2D, const point2D & > & edge, point2D & thisPoint, point2D & edgePoint) const
Friends And Related Symbol Documentation
operator>>
template<class Point , class PointRef > Istream & operator>> (Istream & , line< Point, PointRef > &) friend
operator
template<class Point , class PointRef > Ostream & operator (Ostream & , const line< Point, PointRef > &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/primitiveShapes/line/line.H
src/OpenFOAM/meshes/primitiveShapes/line/lineI.H