OpenFOAM: adjointSensitivity Class Reference
adjointSensitivity Class Reference abstract
Abstract base class for adjoint-based sensitivities in incompressible flows.
#include <adjointSensitivityIncompressible.H>
Public Member Functions
TypeName ("adjointSensitivity")
declareRunTimeSelectionTable (autoPtr, adjointSensitivity, dictionary,(const fvMesh &mesh, const dictionary &dict, incompressibleAdjointSolver &adjointSolver),(mesh, dict, adjointSolver))
adjointSensitivity (const fvMesh &mesh, const dictionary &dict, incompressibleAdjointSolver &adjointSolver)
virtual ~adjointSensitivity ()=default
const incompressibleVars & primalVars () const
const incompressibleAdjointVars & adjointVars () const
const incompressibleAdjointSolver & adjointSolver () const
virtual void accumulateIntegrand (const scalar dt)=0
virtual void assembleSensitivities ()=0
virtual const scalarField & calculateSensitivities ()
const scalarField & getSensitivities () const
virtual void clearSensitivities ()
virtual void write (const word &baseName=word::null)
tmp< volTensorField > computeGradDxDbMultiplier ()
tmp< volVectorField > adjointMeshMovementSource ()
Public Member Functions inherited from sensitivity
TypeName ("sensitivity")
sensitivity (const fvMesh &mesh, const dictionary &dict)
virtual ~sensitivity ()=default
const dictionary & dict () const
virtual bool readDict (const dictionary &dict)
virtual void computeDerivativesSize ()
Static Public Member Functions
static autoPtr< adjointSensitivity > New (const fvMesh &mesh, const dictionary &dict, incompressibleAdjointSolver &adjointSolver)
Protected Attributes
scalarField derivatives_
incompressibleAdjointSolver & adjointSolver_
const incompressibleVars & primalVars_
incompressibleAdjointVars & adjointVars_
objectiveManager & objectiveManager_
Protected Attributes inherited from sensitivity
const fvMesh & mesh_
dictionary dict_
autoPtr< volScalarField > fieldSensPtr_
Detailed Description
Abstract base class for adjoint-based sensitivities in incompressible flows.
Reference:
    For the FI and ESI formulations
        Kavvadias, I., Papoutsis-Kiachagias, E., & Giannakoglou, K. (2015).
        On the proper treatment of grid sensitivities in continuous adjoint
        methods for shape optimization.
        Journal of Computational Physics, 301, 1–18.
        http://doi.org/10.1016/j.jcp.2015.08.012
    For the SI formulation
        Papoutsis-Kiachagias, E. M., & Giannakoglou, K. C. (2014).
        Continuous Adjoint Methods for Turbulent Flows, Applied to Shape
        and Topology Optimization: Industrial Applications.
        Archives of Computational Methods in Engineering, 23(2), 255–299.
        http://doi.org/10.1007/s11831-014-9141-9
Source files
adjointSensitivityIncompressible.H
adjointSensitivity.C
Definition at line 74 of file adjointSensitivityIncompressible.H.
Constructor & Destructor Documentation
adjointSensitivity()
adjointSensitivity (const fvMesh & mesh, const dictionary & dict, incompressibleAdjointSolver & adjointSolver)
Definition at line 45 of file adjointSensitivityIncompressible.C.
~adjointSensitivity()
virtual ~adjointSensitivity () virtual default
Member Function Documentation
TypeName()
TypeName ("adjointSensitivity")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , adjointSensitivity , dictionary , (const fvMesh &mesh, const dictionary &dict, incompressibleAdjointSolver &adjointSolver) , (mesh, dict, adjointSolver))
New()
autoPtr< adjointSensitivity > New (const fvMesh & mesh, const dictionary & dict, incompressibleAdjointSolver & adjointSolver) static
Definition at line 63 of file adjointSensitivityIncompressible.C.
References sensitivity::dict(), Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, UPtrList< T >::get(), Foam::Info, and mesh.
Referenced by adjointSimple::adjointSimple(), and sensitivityMultiple::sensitivityMultiple().
primalVars()
const incompressibleVars & primalVars () const inline
Definition at line 154 of file adjointSensitivityIncompressible.H.
References adjointSensitivity::primalVars_.
adjointVars()
const incompressibleAdjointVars & adjointVars () const inline
Definition at line 160 of file adjointSensitivityIncompressible.H.
References adjointSensitivity::adjointVars_.
adjointSolver()
const incompressibleAdjointSolver & adjointSolver () const inline
Definition at line 166 of file adjointSensitivityIncompressible.H.
References adjointSensitivity::adjointSolver_.
accumulateIntegrand()
virtual void accumulateIntegrand (const scalar dt) pure virtual
Implemented in FIBase, sensitivityMultiple, sensitivitySurface, sensitivitySurfacePoints, SIBase, and shapeSensitivities.
assembleSensitivities()
virtual void assembleSensitivities () pure virtual
Implemented in sensitivityBezier, sensitivityBezierFI, sensitivityMultiple, sensitivitySurface, sensitivitySurfacePoints, sensitivityVolBSplines, sensitivityVolBSplinesFI, FIBase, shapeSensitivities, and SIBase.
Referenced by adjointSensitivity::calculateSensitivities().
calculateSensitivities()
const scalarField & calculateSensitivities () virtual
Implements sensitivity.
Reimplemented in sensitivityMultiple.
Definition at line 96 of file adjointSensitivityIncompressible.C.
References adjointSensitivity::assembleSensitivities(), adjointSensitivity::derivatives_, Foam::type(), and write().
getSensitivities()
const scalarField & getSensitivities () const
Definition at line 104 of file adjointSensitivityIncompressible.C.
References adjointSensitivity::derivatives_.
clearSensitivities()
void clearSensitivities () virtual
Reimplemented in FIBase, sensitivityBezier, sensitivityBezierFI, sensitivityMultiple, sensitivitySurface, sensitivitySurfacePoints, sensitivityVolBSplines, sensitivityVolBSplinesFI, shapeSensitivities, and SIBase.
Definition at line 110 of file adjointSensitivityIncompressible.C.
References adjointSensitivity::derivatives_, and sensitivity::fieldSensPtr_.
Referenced by sensitivitySurface::clearSensitivities(), sensitivitySurfacePoints::clearSensitivities(), and shapeSensitivities::clearSensitivities().
write()
void write (const word & baseName = word::null) virtual
Reimplemented from sensitivity.
Reimplemented in sensitivityBezier, sensitivityBezierFI, sensitivityMultiple, sensitivitySurface, sensitivitySurfacePoints, sensitivityVolBSplines, sensitivityVolBSplinesFI, shapeSensitivities, and SIBase.
Definition at line 120 of file adjointSensitivityIncompressible.C.
References sensitivity::write().
Referenced by sensitivitySurface::write(), sensitivitySurfacePoints::write(), and shapeSensitivities::write().
computeGradDxDbMultiplier()
tmp< volTensorField > computeGradDxDbMultiplier ()
Definition at line 126 of file adjointSensitivityIncompressible.C.
References adjointSensitivity::adjointSolver_, and incompressibleAdjointSolver::computeGradDxDbMultiplier().
Referenced by FIBase::accumulateIntegrand(), and adjointSensitivity::adjointMeshMovementSource().
adjointMeshMovementSource()
tmp< volVectorField > adjointMeshMovementSource ()
Definition at line 132 of file adjointSensitivityIncompressible.C.
References adjointSensitivity::adjointVars_, adjointSensitivity::computeGradDxDbMultiplier(), Foam::dimLength, Foam::fvc::div(), sensitivity::mesh_, options::New(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef(), variablesSet::solverName(), and Foam::Zero.
Referenced by adjointMeshMovementSolver::accumulateIntegrand().
Member Data Documentation
derivatives_
scalarField derivatives_ protected
Definition at line 82 of file adjointSensitivityIncompressible.H.
Referenced by sensitivityBezier::assembleSensitivities(), sensitivityBezierFI::assembleSensitivities(), sensitivitySurface::assembleSensitivities(), sensitivitySurfacePoints::assembleSensitivities(), sensitivityVolBSplines::assembleSensitivities(), sensitivityVolBSplinesFI::assembleSensitivities(), adjointSensitivity::calculateSensitivities(), sensitivityMultiple::calculateSensitivities(), adjointSensitivity::clearSensitivities(), sensitivitySurface::computeDerivativesSize(), adjointSensitivity::getSensitivities(), sensitivityBezier::sensitivityBezier(), sensitivityBezierFI::sensitivityBezierFI(), sensitivitySurfacePoints::sensitivitySurfacePoints(), sensitivityVolBSplines::sensitivityVolBSplines(), sensitivityVolBSplinesFI::sensitivityVolBSplinesFI(), sensitivityBezier::write(), sensitivityBezierFI::write(), sensitivityVolBSplines::write(), and sensitivityVolBSplinesFI::write().
adjointSolver_
incompressibleAdjointSolver& adjointSolver_ protected
Definition at line 83 of file adjointSensitivityIncompressible.H.
Referenced by sensitivitySurface::accumulateIntegrand(), sensitivitySurfacePoints::accumulateIntegrand(), adjointSensitivity::adjointSolver(), and adjointSensitivity::computeGradDxDbMultiplier().
primalVars_
const incompressibleVars& primalVars_ protected
Definition at line 84 of file adjointSensitivityIncompressible.H.
Referenced by sensitivitySurface::accumulateIntegrand(), sensitivitySurfacePoints::accumulateIntegrand(), shapeSensitivities::dvdbMult(), adjointSensitivity::primalVars(), FIBase::read(), sensitivitySurface::read(), and sensitivitySurfacePoints::read().
adjointVars_
incompressibleAdjointVars& adjointVars_ protected
Definition at line 85 of file adjointSensitivityIncompressible.H.
Referenced by shapeSensitivities::accumulateBCSensitivityIntegrand(), FIBase::accumulateIntegrand(), sensitivitySurface::accumulateIntegrand(), sensitivitySurfacePoints::accumulateIntegrand(), adjointSensitivity::adjointMeshMovementSource(), adjointSensitivity::adjointVars(), shapeSensitivities::dvdbMult(), FIBase::read(), sensitivitySurface::read(), sensitivitySurfacePoints::read(), sensitivitySurface::setSuffixName(), sensitivitySurfacePoints::setSuffixName(), sensitivityBezier::write(), sensitivityBezierFI::write(), sensitivityVolBSplines::write(), and sensitivityVolBSplinesFI::write().
objectiveManager_
objectiveManager& objectiveManager_ protected
Definition at line 86 of file adjointSensitivityIncompressible.H.
Referenced by shapeSensitivities::accumulateDirectSensitivityIntegrand(), FIBase::accumulateIntegrand(), sensitivitySurface::accumulateIntegrand(), sensitivitySurfacePoints::accumulateIntegrand(), and sensitivitySurface::addGeometricSens().
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/optimisation/adjointSensitivity/incompressible/adjointSensitivity/adjointSensitivityIncompressible.H
src/optimisation/adjointOptimisation/adjoint/optimisation/adjointSensitivity/incompressible/adjointSensitivity/adjointSensitivityIncompressible.C