OpenFOAM: SIMPLEControlOpt Class Reference
SIMPLEControlOpt Class Reference
SIMPLE control class for optimisation runs. Each time is sub-cycled and corresponds to one optimisation cycle.
#include <SIMPLEControlOpt.H>
Public Member Functions
TypeName ("steadyOptimisation")
SIMPLEControlOpt (fvMesh &mesh, const word &managerType, const solver &solver)
virtual ~SIMPLEControlOpt ()=default
virtual bool write (const bool valid=true) const
virtual bool loop ()
Public Member Functions inherited from SIMPLEControl
TypeName ("SIMPLEControl")
declareRunTimeSelectionTable (autoPtr, SIMPLEControl, dictionary,(fvMesh &mesh, const word &managerType, const solver &solver),(mesh, managerType, solver))
SIMPLEControl (fvMesh &mesh, const word &managerType, const solver &solver)
virtual ~SIMPLEControl ()=default
virtual void readIters ()
void checkMeanSolution () const
virtual const dictionary dict () const
label & pRefCell ()
scalar & pRefValue ()
Public Member Functions inherited from solverControl
TypeName ("solverControl")
solverControl (const solver &solver)
virtual ~solverControl ()=default
virtual const dictionary solverDict () const
virtual const dictionary solutionDict () const
bool printMaxMags () const
bool storeInitValues () const
label iter () const
label & averageIter ()
label averageIter () const
label averageStartIter () const
bool doAverageIter () const
bool useAveragedFields () const
bool average () const
Public Member Functions inherited from simpleControl
TypeName ("simpleControl")
simpleControl (fvMesh &mesh, const word &dictName="SIMPLE", const bool verbose=true)
virtual ~simpleControl ()=default
Public Member Functions inherited from solutionControl
TypeName ("solutionControl")
solutionControl (fvMesh &mesh, const word &algorithmName)
virtual ~solutionControl ()=default
label corr () const
label corrNonOrtho () const
label nNonOrthCorr () const
bool finalNonOrthogonalIter () const
bool momentumPredictor () const
bool transonic () const
bool consistent () const
bool frozenFlow () const
bool correctNonOrthogonal ()
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
regIOobject (const IOobject &io, const bool isTimeObject=false)
regIOobject (const regIOobject &rio)
regIOobject (const regIOobject &rio, bool registerCopy)
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
regIOobject (const IOobject &io, const regIOobject &rio)
virtual ~regIOobject ()
bool checkIn ()
bool checkOut ()
virtual void addWatch ()
bool registered () const noexcept
bool ownedByRegistry () const noexcept
bool store ()
void release (const bool unregister=false) noexcept
label eventNo () const noexcept
label & eventNo () noexcept
bool upToDate (const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
void setUpToDate ()
virtual void rename (const word &newName)
const dictionary * findMetaData () const noexcept
dictionary & getMetaData () noexcept
void removeMetaData ()
virtual void updateMetaData ()
virtual fileName filePath () const
bool headerOk ()
Istream & readStream (const word &, const bool readOnProc=true)
void close ()
virtual bool readData (Istream &)
virtual label addWatch (const fileName &)
const labelList & watchIndices () const noexcept
labelList & watchIndices () noexcept
virtual bool modified () const
virtual bool readIfModified ()
virtual bool writeObject (IOstreamOption streamOpt, const bool writeOnProc) const
virtual bool global () const
void operator= (const IOobject &io)
virtual bool writeObject (IOstreamOption::streamFormat fmt, IOstreamOption::versionNumber ver, IOstreamOption::compressionType cmp, const bool writeOnProc) const
Public Member Functions inherited from IOobject
TypeName ("IOobject")
IOobject (const IOobject &)=default
virtual ~IOobject ()=default
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const fileName &path, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const fileName &path, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const IOobject &io, const objectRegistry &registry)
IOobject (const IOobject &io, const word &name)
IOobject (const IOobject &io, const word &name, const fileName &local)
IOobject (const IOobject &io, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt)
IOobject (const IOobject &io, IOobjectOption::registerOption regOpt)
autoPtr< IOobject > clone () const
autoPtr< IOobject > clone (const objectRegistry &registry) const
const objectRegistry & db () const noexcept
const Time & time () const noexcept
const word & name () const noexcept
const word & headerClassName () const noexcept
word & headerClassName () noexcept
const string & note () const noexcept
string & note () noexcept
unsigned labelByteSize () const noexcept
unsigned scalarByteSize () const noexcept
void resetHeader (const word &newName=word::null)
bool hasHeaderClass () const noexcept
template<class Type >
bool isHeaderClass () const
template<class Type >
bool isHeaderClassName () const
word group () const
word member () const
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const noexcept
fileName & instance () noexcept
const fileName & local () const noexcept
fileName path () const
fileName path (const word &instance, const fileName &local=fileName::null) const
fileName objectPath () const
fileName objectRelPath () const
fileName localFilePath (const word &typeName, const bool search=true) const
fileName globalFilePath (const word &typeName, const bool search=true) const
IOstreamOption parseHeader (const dictionary &headerDict)
bool readHeader (Istream &is)
bool readHeader (dictionary &headerDict, Istream &is)
template<class Type >
bool typeHeaderOk (const bool checkType=true, const bool search=true, const bool verbose=true)
template<class Type >
void warnNoRereading () const
bool writeHeader (Ostream &os) const
bool writeHeader (Ostream &os, const word &objectType) const
void writeHeader (dictionary &dict, IOstreamOption streamOpt) const
void writeHeader (dictionary &dict, const word &objectType, IOstreamOption streamOpt) const
bool good () const noexcept
bool bad () const noexcept
InfoProxy< IOobject > info () const noexcept
void operator= (const IOobject &io)
template<>
bool isHeaderClass () const
template<class StringType >
Foam::word groupName (StringType base, const word &group)
Public Member Functions inherited from IOobjectOption
constexpr IOobjectOption (readOption rOpt=readOption::NO_READ, writeOption wOpt=writeOption::NO_WRITE, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (readOption rOpt, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (writeOption wOpt, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (registerOption registerObject, bool globalObject=false) noexcept
constexpr IOobjectOption (readOption rOpt, writeOption wOpt, bool registerObject, bool globalObject=false) noexcept
constexpr IOobjectOption (bool registerObject, bool globalObject=false) noexcept
readOption readOpt () const noexcept
readOption readOpt (readOption opt) noexcept
writeOption writeOpt () const noexcept
writeOption writeOpt (writeOption opt) noexcept
bool registerObject () const noexcept
bool registerObject (bool on) noexcept
bool globalObject () const noexcept
bool globalObject (bool on) noexcept
bool isAnyRead () const noexcept
bool isReadRequired () const noexcept
bool isReadOptional () const noexcept
readOption & readOpt () noexcept
writeOption & writeOpt () noexcept
bool & registerObject () noexcept
bool & globalObject () noexcept
Protected Member Functions
virtual bool read ()
virtual bool criteriaSatisfied ()
const label & nIters () const
void resetDeltaT ()
Protected Member Functions inherited from solutionControl
virtual bool read (const bool absTolOnly)
virtual label applyToField (const word &fieldName, const bool useRegEx=true) const
virtual void storePrevIterFields () const
template<class Type >
void storePrevIter () const
Pair< scalar > maxResidual (const entry &solverPerfDictEntry) const
virtual void setFirstIterFlag (const bool check=true, const bool force=false)
virtual bool writeData (Ostream &) const
Protected Member Functions inherited from regIOobject
bool readHeaderOk (const IOstreamOption::streamFormat fmt, const word &typeName)
Protected Member Functions inherited from IOobject
void setBad (const string &s)
Protected Attributes
label nInitialIters_
autoPtr< subCycleTime > subCycledTimePtr_
scalar deltaTSubSycle_
Protected Attributes inherited from SIMPLEControl
const word & managerType_
label nIters_
label pRefCell_
scalar pRefValue_
Protected Attributes inherited from solverControl
const solver & solver_
bool printMaxMags_
label iter_
label averageIter_
label averageStartIter_
bool storeInitValues_
bool average_
Protected Attributes inherited from simpleControl
bool initialised_
Protected Attributes inherited from solutionControl
fvMesh & mesh_
List< fieldData > residualControl_
const word algorithmName_
label nNonOrthCorr_
bool momentumPredictor_
bool transonic_
bool consistent_
bool frozenFlow_
label corr_
label corrNonOrtho_
Additional Inherited Members
Public Types inherited from IOobject
enum objectState : char { GOOD , BAD }
enum fileCheckTypes : char { timeStamp , timeStampMaster , inotify , inotifyMaster }
Public Types inherited from IOobjectOption
enum readOption : unsigned char {
NO_READ = 0 , MUST_READ = 0x1 , READ_MODIFIED = 0x3 , MUST_READ_IF_MODIFIED = 0x3 ,
LAZY_READ = 0x4 , READ_IF_PRESENT = 0x4
}
enum writeOption : unsigned char { NO_WRITE = 0 , AUTO_WRITE = 0x10 }
enum registerOption : unsigned char { NO_REGISTER = 0 , REGISTER = 1 }
Static Public Member Functions inherited from SIMPLEControl
static autoPtr< SIMPLEControl > New (fvMesh &mesh, const word &managerType, const solver &solver)
Static Public Member Functions inherited from solutionControl
static Pair< scalar > maxResidual (const fvMesh &fvmesh, const entry &dataDictEntry)
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *p)
template<class Type >
static Type & store (autoPtr< Type > &ptr)
template<class Type >
static Type & store (autoPtr< Type > &&ptr)
template<class Type >
static Type & store (refPtr< Type > &ptr)
template<class Type >
static Type & store (refPtr< Type > &&ptr)
template<class Type >
static Type & store (tmp< Type > &ptr)
template<class Type >
static Type & store (tmp< Type > &&ptr)
Static Public Member Functions inherited from IOobject
static bool bannerEnabled () noexcept
static bool bannerEnabled (bool on) noexcept
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
template<class StringType >
static word groupName (StringType base, const word &group)
static word group (const word &name)
static word member (const word &name)
static word scopedName (const std::string &scope, const word &name)
static IOobject selectIO (const IOobject &io, const fileName &altFile, const word &ioName="")
static Ostream & writeBanner (Ostream &os, const bool noSyntaxHint=false)
static Ostream & writeDivider (Ostream &os)
static Ostream & writeEndDivider (Ostream &os)
Static Public Member Functions inherited from IOobjectOption
static bool isAnyRead (readOption opt) noexcept
static bool isReadRequired (readOption opt) noexcept
static bool isReadOptional (readOption opt) noexcept
static readOption lazierRead (readOption opt) noexcept
Static Public Attributes inherited from IOobject
static const Enum< fileCheckTypes > fileCheckTypesNames
static char scopeSeparator
static fileCheckTypes fileModificationChecking
static float fileModificationSkew
static int maxFileModificationPolls
Static Protected Member Functions inherited from solutionControl
template<class Type >
static bool maxTypeResidual (const fvMesh &fvmesh, const entry &solverPerfDictEntry, Pair< scalar > &residuals)
Static Protected Member Functions inherited from IOobject
static void writeHeaderContent (Ostream &os, const IOobject &io, const word &objectType, const dictionary *metaDataDict=nullptr)
static void writeHeaderContent (dictionary &dict, const IOobject &io, const word &objectType, IOstreamOption streamOpt, const dictionary *metaDataDict=nullptr)
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
Detailed Description
SIMPLE control class for optimisation runs. Each time is sub-cycled and corresponds to one optimisation cycle.
Definition at line 46 of file SIMPLEControlOpt.H.
Constructor & Destructor Documentation
SIMPLEControlOpt()
SIMPLEControlOpt (fvMesh & mesh, const word & managerType, const solver & solver)
Definition at line 89 of file SIMPLEControlOpt.C.
References SIMPLEControlOpt::read().
~SIMPLEControlOpt()
virtual ~SIMPLEControlOpt () virtual default
Member Function Documentation
read()
bool read () protected virtual
Reimplemented from SIMPLEControl.
Definition at line 37 of file SIMPLEControlOpt.C.
References SIMPLEControl::dict(), SIMPLEControlOpt::nInitialIters_, SIMPLEControl::nIters_, and SIMPLEControl::read().
Referenced by SIMPLEControlOpt::SIMPLEControlOpt().
criteriaSatisfied()
bool criteriaSatisfied () protected virtual
Reimplemented from simpleControl.
Definition at line 44 of file SIMPLEControlOpt.C.
References simpleControl::criteriaSatisfied().
nIters()
const Foam::label & nIters () const protected
Definition at line 64 of file SIMPLEControlOpt.C.
resetDeltaT()
void resetDeltaT () protected
Definition at line 77 of file SIMPLEControlOpt.C.
References TimeState::deltaTValue(), runTime, and Time::setDeltaT().
TypeName()
TypeName ("steadyOptimisation")
write()
bool write (const bool valid = true) const virtual
Implements SIMPLEControl.
Definition at line 107 of file SIMPLEControlOpt.C.
loop()
bool loop () virtual
Implements SIMPLEControl.
Definition at line 115 of file SIMPLEControlOpt.C.
References DebugInfo, TimeState::deltaTValue(), Foam::endl(), Foam::Info, Foam::nl, Foam::read(), Time::readModifiedObjects(), runTime, and regIOobject::write().
Member Data Documentation
nInitialIters_
label nInitialIters_ protected
Definition at line 55 of file SIMPLEControlOpt.H.
Referenced by SIMPLEControlOpt::read().
subCycledTimePtr_
autoPtr<subCycleTime> subCycledTimePtr_ protected
Definition at line 58 of file SIMPLEControlOpt.H.
deltaTSubSycle_
scalar deltaTSubSycle_ protected
Definition at line 61 of file SIMPLEControlOpt.H.
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/solvers/solverControl/SIMPLEControl/optimisation/SIMPLEControlOpt.H
src/optimisation/adjointOptimisation/adjoint/solvers/solverControl/SIMPLEControl/optimisation/SIMPLEControlOpt.C