OpenFOAM: parallelFvGeometryScheme Class Reference
parallelFvGeometryScheme Class Reference
Geometry calculation scheme with explicit sync of face-geometry across processor patches.
#include <parallelFvGeometryScheme.H>
Classes
class transformOriented
Public Member Functions
TypeName ("parallel")
parallelFvGeometryScheme (const fvMesh &mesh, const dictionary &dict)
virtual ~parallelFvGeometryScheme ()=default
const fvGeometryScheme & geometry () const
virtual void movePoints ()
virtual void updateMesh (const mapPolyMesh &mpm)
virtual tmp< surfaceScalarField > weights () const
virtual tmp< surfaceScalarField > deltaCoeffs () const
virtual tmp< surfaceScalarField > nonOrthDeltaCoeffs () const
virtual tmp< surfaceVectorField > nonOrthCorrectionVectors () const
Public Member Functions inherited from fvGeometryScheme
TypeName ("fvGeometryScheme")
declareRunTimeSelectionTable (tmp, fvGeometryScheme, dict,(const fvMesh &mesh, const dictionary &dict),(mesh, dict))
fvGeometryScheme (const fvMesh &mesh, const dictionary &dict)
virtual ~fvGeometryScheme ()=default
const fvMesh & mesh () const
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Protected Attributes
dictionary dict_
tmp< fvGeometryScheme > geometryPtr_
Protected Attributes inherited from fvGeometryScheme
const fvMesh & mesh_
Additional Inherited Members
Static Public Member Functions inherited from fvGeometryScheme
static tmp< fvGeometryScheme > New (const fvMesh &mesh, const dictionary &dict, const word &defaultScheme)
Protected Member Functions inherited from fvGeometryScheme
bool setMeshPhi () const
Detailed Description
Geometry calculation scheme with explicit sync of face-geometry across processor patches.
applies face centre and normal (negated) to the neighbour side of a processor boundary.
recalculates the resulting cell volumes.
mainly interesting in single-precision in that it removes the different truncation error from circulating in different order. This can cause problems when calculating global transformations.
it does change the face normal/centre so might affect the cell-closedness of the attached cells.
Usage
In system/fvSchemes add a geometry scheme:
geometry
{
    type            parallel;
    // Optional underlying geometry scheme. (default is basic)
    geometry
    {
        type        solidBody;
    }
}
The default behaviour will print the total number of adjusted face and cell properties:
    parallelFvGeometryScheme::movePoints() :
        adjusted geometry of faces:113 of cells:54
In addition a warning will be printed if an internal face gives a different result.
Source files
parallelFvGeometryScheme.H
parallelFvGeometryScheme.C
Definition at line 81 of file parallelFvGeometryScheme.H.
Constructor & Destructor Documentation
parallelFvGeometryScheme()
parallelFvGeometryScheme (const fvMesh & mesh, const dictionary & dict)
Definition at line 216 of file parallelFvGeometryScheme.C.
~parallelFvGeometryScheme()
virtual ~parallelFvGeometryScheme () virtual default
Member Function Documentation
TypeName()
TypeName ("parallel")
geometry()
const Foam::fvGeometryScheme & geometry () const
Definition at line 229 of file parallelFvGeometryScheme.C.
References Foam::endl(), fvGeometryScheme::New(), and Foam::Pout.
movePoints()
void movePoints () virtual
Reimplemented from fvGeometryScheme.
Definition at line 250 of file parallelFvGeometryScheme.C.
References Foam::endl(), and Foam::Pout.
updateMesh()
void updateMesh (const mapPolyMesh & mpm) virtual
Reimplemented from fvGeometryScheme.
Definition at line 266 of file parallelFvGeometryScheme.C.
weights()
Foam::tmp< Foam::surfaceScalarField > weights () const virtual
Implements fvGeometryScheme.
Definition at line 273 of file parallelFvGeometryScheme.C.
deltaCoeffs()
Foam::tmp< Foam::surfaceScalarField > deltaCoeffs () const virtual
Implements fvGeometryScheme.
Definition at line 280 of file parallelFvGeometryScheme.C.
nonOrthDeltaCoeffs()
Foam::tmp< Foam::surfaceScalarField > nonOrthDeltaCoeffs () const virtual
Implements fvGeometryScheme.
Definition at line 287 of file parallelFvGeometryScheme.C.
nonOrthCorrectionVectors()
Foam::tmp< Foam::surfaceVectorField > nonOrthCorrectionVectors () const virtual
Implements fvGeometryScheme.
Definition at line 294 of file parallelFvGeometryScheme.C.
Member Data Documentation
dict_
dictionary dict_ protected
Definition at line 90 of file parallelFvGeometryScheme.H.
geometryPtr_
tmp<fvGeometryScheme> geometryPtr_ mutable protected
Definition at line 93 of file parallelFvGeometryScheme.H.
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/fvGeometryScheme/parallel/parallelFvGeometryScheme.H
src/finiteVolume/fvMesh/fvGeometryScheme/parallel/parallelFvGeometryScheme.C