OpenFOAM: sceneWriter Class Reference
sceneWriter Class Reference
Wrapper for glTF scene for file output.
#include <foamGltfSceneWriter.H>
Public Member Functions
sceneWriter (const sceneWriter &)=delete
void operator= (const sceneWriter &)=delete
sceneWriter ()=default
sceneWriter (const fileName &outputFile)
~sceneWriter ()
bool valid () const noexcept
const fileName & path () const
const scene & getScene () const
scene & getScene ()
void open (const fileName &outputFile)
void close ()
Detailed Description
Wrapper for glTF scene for file output.
Source files
foamGltfSceneWriter.H
foamGltfSceneWriter.C
Definition at line 54 of file foamGltfSceneWriter.H.
Constructor & Destructor Documentation
sceneWriter() [1/3]
sceneWriter (const sceneWriter &) delete
sceneWriter() [2/3]
sceneWriter () default
sceneWriter() [3/3]
sceneWriter (const fileName & outputFile) explicit
Definition at line 27 of file foamGltfSceneWriter.C.
References sceneWriter::open().
~sceneWriter()
~sceneWriter ()
Definition at line 38 of file foamGltfSceneWriter.C.
Member Function Documentation
operator=()
void operator= (const sceneWriter &) delete
valid()
bool valid () const noexcept
Definition at line 46 of file foamGltfSceneWriter.C.
path()
const Foam::fileName & path () const
Definition at line 52 of file foamGltfSceneWriter.C.
References fileName::null.
getScene() [1/2]
const Foam::glTF::scene & getScene () const
Definition at line 58 of file foamGltfSceneWriter.C.
getScene() [2/2]
Foam::glTF::scene & getScene ()
Definition at line 64 of file foamGltfSceneWriter.C.
open()
void open (const fileName & outputFile)
Definition at line 70 of file foamGltfSceneWriter.C.
References Foam::isDir(), and Foam::mkDir().
Referenced by sceneWriter::sceneWriter().
close()
void close ()
Definition at line 88 of file foamGltfSceneWriter.C.
The documentation for this class was generated from the following files:
src/fileFormats/gltf/foamGltfSceneWriter.H
src/fileFormats/gltf/foamGltfSceneWriter.C