OpenFOAM: patchMeanVelocityForce Class Reference
patchMeanVelocityForce Class Reference
Applies the force over the specified patch to maintain the specified mean velocity for incompressible flows.
#include <patchMeanVelocityForce.H>
Public Member Functions
TypeName ("patchMeanVelocityForce")
patchMeanVelocityForce (const word &sourceName, const word &modelType, const dictionary &dict, const fvMesh &mesh)
patchMeanVelocityForce (const patchMeanVelocityForce &)=delete
void operator= (const patchMeanVelocityForce &)=delete
~patchMeanVelocityForce ()=default
Public Member Functions inherited from meanVelocityForce
TypeName ("meanVelocityForce")
meanVelocityForce (const word &sourceName, const word &modelType, const dictionary &dict, const fvMesh &mesh)
meanVelocityForce (const meanVelocityForce &)=delete
void operator= (const meanVelocityForce &)=delete
virtual ~meanVelocityForce ()=default
virtual void correct (volVectorField &U)
virtual void addSup (fvMatrix< vector > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldi)
virtual void constrain (fvMatrix< vector > &eqn, const label fieldi)
virtual bool read (const dictionary &dict)
Public Member Functions inherited from cellSetOption
TypeName ("cellSetOption")
cellSetOption (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
virtual ~cellSetOption ()=default
scalar timeStart () const noexcept
scalar duration () const noexcept
bool inTimeLimits (const scalar timeValue) const
bool useSubMesh () const noexcept
selectionModeType selectionMode () const noexcept
const wordRes & selectionNames () const noexcept
const wordRe & zoneName () const
scalar V () const noexcept
const labelList & cells () const noexcept
scalar timeStart (scalar val) noexcept
scalar duration (scalar val) noexcept
virtual bool isActive ()
const word & cellSetName () const
Public Member Functions inherited from option
TypeName ("option")
declareRunTimeSelectionTable (autoPtr, option, dictionary,(const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh),(name, modelType, dict, mesh))
option (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
autoPtr< option > clone () const
virtual ~option ()=default
const word & name () const noexcept
const fvMesh & mesh () const noexcept
const dictionary & coeffs () const noexcept
bool active () const noexcept
void setApplied (const label fieldi)
bool active (const bool on) noexcept
virtual label applyToField (const word &fieldName) const
virtual void checkApplied () const
virtual void addSup (fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (fvMatrix< tensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< scalar > &eqn, const label fieldi)
virtual void constrain (fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< tensor > &eqn, const label fieldi)
virtual void correct (volScalarField &field)
virtual void correct (volSphericalTensorField &field)
virtual void correct (volSymmTensorField &field)
virtual void correct (volTensorField &field)
virtual void postProcessSens (scalarField &sensField, const word &fieldName=word::null, const word &designVariablesName=word::null)
virtual void postProcessSens (vectorField &sensField, const word &fieldName=word::null, const word &designVariablesName=word::null)
virtual void postProcessSens (tensorField &sensField, const word &fieldName=word::null, const word &designVariablesName=word::null)
virtual void writeHeader (Ostream &) const
virtual void writeFooter (Ostream &) const
virtual void writeData (Ostream &) const
Protected Member Functions
virtual scalar magUbarAve (const volVectorField &U) const
Protected Member Functions inherited from meanVelocityForce
void writeProps (const scalar gradP) const
void update (fvMatrix< vector > &eqn)
Protected Member Functions inherited from cellSetOption
void setSelection (const dictionary &dict)
void setCellSelection ()
void setVol ()
Protected Member Functions inherited from option
void resetApplied ()
Protected Attributes
word patch_
label patchi_
Protected Attributes inherited from meanVelocityForce
vector Ubar_
scalar gradP0_
scalar dGradP_
vector flowDir_
scalar relaxation_
autoPtr< volScalarField > rAPtr_
Protected Attributes inherited from cellSetOption
scalar timeStart_
scalar duration_
selectionModeType selectionMode_
wordRes selectionNames_
List< point > points_
dictionary geometricSelection_
labelList cells_
scalar V_
Protected Attributes inherited from option
const word name_
const word modelType_
const fvMesh & mesh_
dictionary dict_
dictionary coeffs_
wordList fieldNames_
List< bool > applied_
bool active_
Additional Inherited Members
Public Types inherited from cellSetOption
enum selectionModeType {
smAll , smCellSet , smCellZone , smPoints ,
smGeometric , smCellType
}
Static Public Member Functions inherited from option
static autoPtr< option > New (const word &name, const dictionary &dict, const fvMesh &mesh)
Public Attributes inherited from option
bool log
Static Public Attributes inherited from cellSetOption
static const Enum< selectionModeType > selectionModeTypeNames_
Detailed Description
Applies the force over the specified patch to maintain the specified mean velocity for incompressible flows.
Sources applied to:
  U         | Velocity                                   [m/s]
Required fields:
  U         | Velocity                                   [m/s]
Usage
Minimal example by using constant/fvOptions:
patchMeanVelocityForce1
{
    // Mandatory entries (unmodifiable)
    type                 patchMeanVelocityForce;
    patch                <patchName>;
    // Mandatory/Optional (inherited) entries
    ...
}
where the entries mean:
Property Description Type Reqd Dflt
type Type name: patchMeanVelocityForce word yes -
patch Name of operand patch word yes -
The inherited entries are elaborated in:
meanVelocityForce.H
See also
Foam::fv::meanVelocityForce
Source files
patchMeanVelocityForce.H
patchMeanVelocityForce.C
Definition at line 105 of file patchMeanVelocityForce.H.
Constructor & Destructor Documentation
patchMeanVelocityForce() [1/2]
patchMeanVelocityForce (const word & sourceName, const word & modelType, const dictionary & dict, const fvMesh & mesh)
Definition at line 40 of file patchMeanVelocityForce.C.
References dict, Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, patchMeanVelocityForce::patch_, and patchMeanVelocityForce::patchi_.
patchMeanVelocityForce() [2/2]
patchMeanVelocityForce (const patchMeanVelocityForce &) delete
~patchMeanVelocityForce()
~patchMeanVelocityForce () default
Member Function Documentation
magUbarAve()
Foam::scalar magUbarAve (const volVectorField & U) const protected virtual
Reimplemented from meanVelocityForce.
Definition at line 63 of file patchMeanVelocityForce.C.
References UPstream::parRun(), patches, processorCyclicPolyPatch::patchIDs(), Foam::stabilise(), Foam::sum(), U, and Foam::Zero.
TypeName()
TypeName ("patchMeanVelocityForce")
operator=()
void operator= (const patchMeanVelocityForce &) delete
Member Data Documentation
patch_
word patch_ protected
Definition at line 114 of file patchMeanVelocityForce.H.
Referenced by patchMeanVelocityForce::patchMeanVelocityForce().
patchi_
label patchi_ protected
Definition at line 117 of file patchMeanVelocityForce.H.
Referenced by patchMeanVelocityForce::patchMeanVelocityForce().
The documentation for this class was generated from the following files:
src/fvOptions/sources/derived/meanVelocityForce/patchMeanVelocityForce/patchMeanVelocityForce.H
src/fvOptions/sources/derived/meanVelocityForce/patchMeanVelocityForce/patchMeanVelocityForce.C