OpenFOAM: sensitivityVolBSplines Class Reference
sensitivityVolBSplines Class Reference
Calculation of adjoint based sensitivities at vol B-Splines control points using the SI or e-SI approach (determined by surface sensitivities)
#include <sensitivityVolBSplinesIncompressible.H>
Public Member Functions
TypeName ("volumetricBSplines")
sensitivityVolBSplines (const fvMesh &mesh, const dictionary &dict, incompressibleAdjointSolver &adjointSolver)
virtual ~sensitivityVolBSplines ()=default
virtual void assembleSensitivities ()
virtual void clearSensitivities ()
virtual void write (const word &baseName=word::null)
Public Member Functions inherited from SIBase
TypeName ("volumetricBSplinesFI")
SIBase (const fvMesh &mesh, const dictionary &dict, incompressibleAdjointSolver &adjointSolver)
virtual ~SIBase ()=default
virtual bool readDict (const dictionary &dict)
virtual void accumulateIntegrand (const scalar dt)
const sensitivitySurface & getSurfaceSensitivities () const
Public Member Functions inherited from shapeSensitivities
TypeName ("shapeSensitivities")
shapeSensitivities (const fvMesh &mesh, const dictionary &dict, incompressibleAdjointSolver &adjointSolver)
virtual ~shapeSensitivities ()=default
Public Member Functions inherited from adjointSensitivity
TypeName ("adjointSensitivity")
declareRunTimeSelectionTable (autoPtr, adjointSensitivity, dictionary,(const fvMesh &mesh, const dictionary &dict, incompressibleAdjointSolver &adjointSolver),(mesh, dict, adjointSolver))
adjointSensitivity (const fvMesh &mesh, const dictionary &dict, incompressibleAdjointSolver &adjointSolver)
virtual ~adjointSensitivity ()=default
const incompressibleVars & primalVars () const
const incompressibleAdjointVars & adjointVars () const
const incompressibleAdjointSolver & adjointSolver () const
virtual const scalarField & calculateSensitivities ()
const scalarField & getSensitivities () const
tmp< volTensorField > computeGradDxDbMultiplier ()
tmp< volVectorField > adjointMeshMovementSource ()
Public Member Functions inherited from sensitivity
TypeName ("sensitivity")
sensitivity (const fvMesh &mesh, const dictionary &dict)
virtual ~sensitivity ()=default
const dictionary & dict () const
virtual void computeDerivativesSize ()
Protected Member Functions
void computeObjectiveContributions ()
void computeBCContributions ()
Protected Member Functions inherited from SIBase
void read ()
Protected Member Functions inherited from shapeSensitivities
virtual void accumulateDirectSensitivityIntegrand (const scalar dt)
virtual void accumulateBCSensitivityIntegrand (const scalar dt)
tmp< boundaryVectorField > dvdbMult () const
Protected Attributes
volBSplinesBase & volBSplinesBase_
vectorField flowSens_
vectorField dSdbSens_
vectorField dndbSens_
vectorField dxdbDirectSens_
vectorField bcSens_
fileName derivativesFolder_
Protected Attributes inherited from SIBase
sensitivitySurface surfaceSensitivity_
bool includeObjective_
bool writeSensitivityMap_
Protected Attributes inherited from shapeSensitivities
autoPtr< boundaryVectorField > dSfdbMult_
autoPtr< boundaryVectorField > dnfdbMult_
autoPtr< boundaryVectorField > dxdbDirectMult_
autoPtr< boundaryVectorField > bcDxDbMult_
Protected Attributes inherited from adjointSensitivity
scalarField derivatives_
incompressibleAdjointSolver & adjointSolver_
const incompressibleVars & primalVars_
incompressibleAdjointVars & adjointVars_
objectiveManager & objectiveManager_
Protected Attributes inherited from sensitivity
const fvMesh & mesh_
dictionary dict_
autoPtr< volScalarField > fieldSensPtr_
Additional Inherited Members
Static Public Member Functions inherited from adjointSensitivity
static autoPtr< adjointSensitivity > New (const fvMesh &mesh, const dictionary &dict, incompressibleAdjointSolver &adjointSolver)
Detailed Description
Calculation of adjoint based sensitivities at vol B-Splines control points using the SI or e-SI approach (determined by surface sensitivities)
Source files
sensitivityVolBSplinesIncompressible.H
sensitivityVolBSplines.C
Definition at line 53 of file sensitivityVolBSplinesIncompressible.H.
Constructor & Destructor Documentation
sensitivityVolBSplines()
sensitivityVolBSplines (const fvMesh & mesh, const dictionary & dict, incompressibleAdjointSolver & adjointSolver)
Definition at line 135 of file sensitivityVolBSplinesIncompressible.C.
References sensitivityVolBSplines::bcSens_, adjointSensitivity::derivatives_, sensitivityVolBSplines::derivativesFolder_, sensitivityVolBSplines::dndbSens_, sensitivityVolBSplines::dSdbSens_, sensitivityVolBSplines::dxdbDirectSens_, sensitivityVolBSplines::flowSens_, volBSplinesBase::getTotalControlPointsNumber(), Foam::mkDir(), sensitivityVolBSplines::volBSplinesBase_, and Foam::Zero.
~sensitivityVolBSplines()
virtual ~sensitivityVolBSplines () virtual default
Member Function Documentation
computeObjectiveContributions()
void computeObjectiveContributions () protected
Definition at line 47 of file sensitivityVolBSplinesIncompressible.C.
References volBSplinesBase::boundControlPointMovement(), volBSplinesBase::boxesRef(), sensitivityVolBSplines::dndbSens_, shapeSensitivities::dnfdbMult_, sensitivityVolBSplines::dSdbSens_, shapeSensitivities::dSfdbMult_, shapeSensitivities::dxdbDirectMult_, sensitivityVolBSplines::dxdbDirectSens_, forAll, Foam::gSum(), SIBase::includeObjective_, UPtrList< T >::size(), sensitivityVolBSplines::volBSplinesBase_, and Foam::Zero.
Referenced by sensitivityVolBSplines::assembleSensitivities().
computeBCContributions()
void computeBCContributions () protected
Definition at line 109 of file sensitivityVolBSplinesIncompressible.C.
References shapeSensitivities::bcDxDbMult_, sensitivityVolBSplines::bcSens_, volBSplinesBase::boundControlPointMovement(), volBSplinesBase::boxesRef(), forAll, UPtrList< T >::size(), and sensitivityVolBSplines::volBSplinesBase_.
Referenced by sensitivityVolBSplines::assembleSensitivities().
TypeName()
TypeName ("volumetricBSplines")
assembleSensitivities()
void assembleSensitivities () virtual
Implements SIBase.
Definition at line 172 of file sensitivityVolBSplinesIncompressible.C.
References sensitivitySurface::assembleSensitivities(), sensitivityVolBSplines::bcSens_, volBSplinesBase::boundControlPointMovement(), volBSplinesBase::boxesRef(), sensitivityVolBSplines::computeBCContributions(), sensitivityVolBSplines::computeObjectiveContributions(), adjointSensitivity::derivatives_, sensitivityVolBSplines::dndbSens_, sensitivityVolBSplines::dSdbSens_, sensitivityVolBSplines::dxdbDirectSens_, sensitivityVolBSplines::flowSens_, forAll, UPtrList< T >::size(), SIBase::surfaceSensitivity_, and sensitivityVolBSplines::volBSplinesBase_.
clearSensitivities()
void clearSensitivities () virtual
Reimplemented from SIBase.
Definition at line 238 of file sensitivityVolBSplinesIncompressible.C.
References sensitivityVolBSplines::bcSens_, SIBase::clearSensitivities(), sensitivityVolBSplines::dndbSens_, sensitivityVolBSplines::dSdbSens_, sensitivityVolBSplines::dxdbDirectSens_, sensitivityVolBSplines::flowSens_, and VectorSpace< Form, Cmpt, Ncmpts >::zero.
write()
void write (const word & baseName = word::null) virtual
Reimplemented from SIBase.
Definition at line 250 of file sensitivityVolBSplinesIncompressible.C.
References adjointSensitivity::adjointVars_, sensitivityVolBSplines::bcSens_, volBSplinesBase::boxesRef(), IOstream::defaultPrecision(), adjointSensitivity::derivatives_, sensitivityVolBSplines::derivativesFolder_, sensitivityVolBSplines::dndbSens_, sensitivityVolBSplines::dSdbSens_, sensitivityVolBSplines::dxdbDirectSens_, Foam::endl(), sensitivityVolBSplines::flowSens_, forAll, Foam::Info, UPstream::master(), Foam::max(), sensitivity::mesh_, Foam::name(), Foam::setw(), UPtrList< T >::size(), UList< T >::size(), variablesSet::solverName(), sensitivityVolBSplines::volBSplinesBase_, and SIBase::write().
Member Data Documentation
volBSplinesBase_
volBSplinesBase& volBSplinesBase_ protected
Definition at line 62 of file sensitivityVolBSplinesIncompressible.H.
Referenced by sensitivityVolBSplines::assembleSensitivities(), sensitivityVolBSplines::computeBCContributions(), sensitivityVolBSplines::computeObjectiveContributions(), sensitivityVolBSplines::sensitivityVolBSplines(), and sensitivityVolBSplines::write().
flowSens_
vectorField flowSens_ protected
Definition at line 65 of file sensitivityVolBSplinesIncompressible.H.
Referenced by sensitivityVolBSplines::assembleSensitivities(), sensitivityVolBSplines::clearSensitivities(), sensitivityVolBSplines::sensitivityVolBSplines(), and sensitivityVolBSplines::write().
dSdbSens_
vectorField dSdbSens_ protected
Definition at line 68 of file sensitivityVolBSplinesIncompressible.H.
Referenced by sensitivityVolBSplines::assembleSensitivities(), sensitivityVolBSplines::clearSensitivities(), sensitivityVolBSplines::computeObjectiveContributions(), sensitivityVolBSplines::sensitivityVolBSplines(), and sensitivityVolBSplines::write().
dndbSens_
vectorField dndbSens_ protected
Definition at line 71 of file sensitivityVolBSplinesIncompressible.H.
Referenced by sensitivityVolBSplines::assembleSensitivities(), sensitivityVolBSplines::clearSensitivities(), sensitivityVolBSplines::computeObjectiveContributions(), sensitivityVolBSplines::sensitivityVolBSplines(), and sensitivityVolBSplines::write().
dxdbDirectSens_
vectorField dxdbDirectSens_ protected
Definition at line 75 of file sensitivityVolBSplinesIncompressible.H.
Referenced by sensitivityVolBSplines::assembleSensitivities(), sensitivityVolBSplines::clearSensitivities(), sensitivityVolBSplines::computeObjectiveContributions(), sensitivityVolBSplines::sensitivityVolBSplines(), and sensitivityVolBSplines::write().
bcSens_
vectorField bcSens_ protected
Definition at line 78 of file sensitivityVolBSplinesIncompressible.H.
Referenced by sensitivityVolBSplines::assembleSensitivities(), sensitivityVolBSplines::clearSensitivities(), sensitivityVolBSplines::computeBCContributions(), sensitivityVolBSplines::sensitivityVolBSplines(), and sensitivityVolBSplines::write().
derivativesFolder_
fileName derivativesFolder_ protected
Definition at line 80 of file sensitivityVolBSplinesIncompressible.H.
Referenced by sensitivityVolBSplines::sensitivityVolBSplines(), and sensitivityVolBSplines::write().
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/optimisation/adjointSensitivity/incompressible/sensitivityVolBSplines/sensitivityVolBSplinesIncompressible.H
src/optimisation/adjointOptimisation/adjoint/optimisation/adjointSensitivity/incompressible/sensitivityVolBSplines/sensitivityVolBSplinesIncompressible.C