OpenFOAM: Field< Type > Class Template Reference
Field< Type > Class Template Reference
Generic templated field type.
#include <Field.H>
Inherits FieldBase, and List< Type >.
Inherited by CompactIOField< Foam::Field< label >, label >, CompactIOField< Foam::Field< scalar >, scalar >, CompactIOField< Foam::Field< Foam::Vector >, Foam::Vector >, CompactIOField< Foam::Field< Foam::SphericalTensor >, Foam::SphericalTensor >, CompactIOField< Foam::Field< Foam::SymmTensor >, Foam::SymmTensor >, CompactIOField< Foam::Field< Foam::Tensor >, Foam::Tensor >, DimensionedField< symmTensor, Foam::volMesh >, DimensionedField< symmTensor, volMesh >, DimensionedField< scalar, Foam::volMesh >, DimensionedField< scalar, volMesh >, DimensionedField< Type, pointMesh >, DimensionedField< vector, Foam::pointMesh >, DimensionedField< vector, Foam::volMesh >, DimensionedField< vector, volMesh >, DimensionedField< tensor, Foam::volMesh >, DimensionedField< tensor, volMesh >, DimensionedField< Foam::Vector, Foam::volMesh >, DimensionedField< Foam::Vector, Foam::pointMesh >, DimensionedField< scalar, Foam::surfaceMesh >, DimensionedField< scalar, surfaceMesh >, DimensionedField< scalar, Foam::pointMesh >, DimensionedField< scalar, pointMesh >, DimensionedField< vector, pointMesh >, DimensionedField< scalar, Foam::areaMesh >, DimensionedField< scalar, areaMesh >, DimensionedField< scalar, Foam::edgeMesh >, DimensionedField< Foam::Vector, Foam::areaMesh >, DimensionedField< Foam::Vector, Foam::edgeMesh >, DimensionedField< Foam::SphericalTensor, Foam::areaMesh >, DimensionedField< Foam::SphericalTensor, Foam::edgeMesh >, DimensionedField< Foam::SymmTensor, Foam::areaMesh >, DimensionedField< Foam::SymmTensor, Foam::edgeMesh >, DimensionedField< Foam::Tensor, Foam::areaMesh >, DimensionedField< Foam::Tensor, Foam::edgeMesh >, DimensionedField< Type, Foam::areaMesh >, DimensionedField< Type, Foam::edgeMesh >, DimensionedField< Foam::Vector, Foam::surfaceMesh >, DimensionedField< Foam::SphericalTensor, Foam::volMesh >, DimensionedField< Foam::SphericalTensor, Foam::surfaceMesh >, DimensionedField< Foam::SymmTensor, Foam::volMesh >, DimensionedField< Foam::SymmTensor, Foam::surfaceMesh >, DimensionedField< Foam::Tensor, Foam::volMesh >, DimensionedField< Foam::Tensor, Foam::surfaceMesh >, DimensionedField< Type, Foam::volMesh >, DimensionedField< Type, Foam::surfaceMesh >, DimensionedField< Type, Foam::pointMesh >, DimensionedField< vector, Foam::surfaceMesh >, DimensionedField< vector, surfaceMesh >, DimensionedField< scalar, triSurfacePointGeoMesh >, DimensionedField< Foam::SphericalTensor, Foam::pointMesh >, DimensionedField< Foam::SymmTensor, Foam::pointMesh >, DimensionedField< Foam::Tensor, Foam::pointMesh >, DimensionedField< tensor, Foam::areaMesh >, DimensionedField< tensor, areaMesh >, DimensionedField< vector, Foam::areaMesh >, DimensionedField< vector, areaMesh >, DimensionedField< scalar, edgeMesh >, DynamicField< Foam::Vector >, DynamicField< label >, GlobalIOField< vector >, IOField< label >, IOField< scalar >, IOField< Foam::Vector >, IOField< Foam::SphericalTensor >, IOField< Foam::SymmTensor >, IOField< Foam::Tensor >, IjkField< scalar >, IjkField< Foam::Vector >, IjkField< Foam::Vector< bool > >, IjkField< Foam::SymmTensor >, faPatchField< scalar >, faPatchField< Foam::Vector >, faPatchField< Foam::SphericalTensor >, faPatchField< Foam::SymmTensor >, faPatchField< Foam::Tensor >, faPatchField< tensor >, faPatchField< vector >, faePatchField< scalar >, faePatchField< Foam::Vector >, faePatchField< Foam::SphericalTensor >, faePatchField< Foam::SymmTensor >, faePatchField< Foam::Tensor >, fvPatchField< symmTensor >, fvPatchField< scalar >, fvPatchField< vector >, fvPatchField< tensor >, fvPatchField< Foam::Vector >, fvPatchField< Foam::SphericalTensor >, fvPatchField< Foam::SymmTensor >, fvPatchField< Foam::Tensor >, fvsPatchField< scalar >, fvsPatchField< Foam::Vector >, fvsPatchField< Foam::SphericalTensor >, fvsPatchField< Foam::SymmTensor >, fvsPatchField< Foam::Tensor >, fvsPatchField< vector >, valuePointPatchField< vector >, DimensionedField< Type, GeoMesh >, GlobalIOField< Type >, IOField< Type >, IjkField< Type >, faPatchField< Type >, faePatchField< Type >, fvPatchField< Type >, fvsPatchField< Type >, rawIOField< Type >, and valuePointPatchField< Type >.
Public Types
typedef pTraits< Type >::cmptType cmptType
typedef SubField< Type > subField
Public Types inherited from List< Type >
typedef SubList< Type > subList
Public Types inherited from UList< T >
typedef T value_type
typedef T * pointer
typedef const T * const_pointer
typedef T & reference
typedef const T & const_reference
typedef T * iterator
typedef const T * const_iterator
typedef label size_type
typedef label difference_type
typedef std::reverse_iterator< iterator > reverse_iterator
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
Public Member Functions
constexpr Field () noexcept
Field (const label len)
Field (const label len, const Type &val)
Field (const label len, const Foam::zero)
Field (const Foam::one, const Type &val)
Field (const Foam::one, Type &&val)
Field (const Foam::one, const Foam::zero)
Field (const Field< Type > &fld)
Field (const UList< Type > &list)
template<class Addr >
Field (const IndirectListBase< Type, Addr > &list)
Field (Field< Type > &&fld)
Field (List< Type > &&list)
template<int SizeMin>
Field (DynamicList< Type, SizeMin > &&list)
Field (const UList< Type > &mapF, const labelUList &mapAddressing)
Field (const tmp< Field< Type > > &tmapF, const labelUList &mapAddressing)
Field (const UList< Type > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Field (const tmp< Field< Type > > &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Field (const UList< Type > &mapF, const FieldMapper &map, const bool applyFlip=true)
Field (const UList< Type > &mapF, const FieldMapper &map, const Type &defaultValue, const bool applyFlip=true)
Field (const UList< Type > &mapF, const FieldMapper &map, const UList< Type > &defaultValues, const bool applyFlip=true)
Field (const tmp< Field< Type > > &tmapF, const FieldMapper &map, const bool applyFlip=true)
Field (const tmp< Field< Type > > &tmapF, const FieldMapper &map, const Type &defaultValue, const bool applyFlip=true)
Field (const tmp< Field< Type > > &tmapF, const FieldMapper &map, const UList< Type > &defaultValues, const bool applyFlip=true)
Field (Field< Type > &fld, bool reuse)
Field (const tmp< Field< Type > > &tfld)
Field (Istream &is)
Field (const entry &e, const label len)
Field (const word &key, const dictionary &dict, const label len, IOobjectOption::readOption readOpt=IOobjectOption::MUST_READ)
tmp< Field< Type > > clone () const
void assign (const entry &e, const label len)
bool assign (const word &key, const dictionary &dict, const label len, IOobjectOption::readOption readOpt=IOobjectOption::MUST_READ)
void map (const UList< Type > &mapF, const labelUList &mapAddressing)
void map (const tmp< Field< Type > > &tmapF, const labelUList &mapAddressing)
void map (const UList< Type > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
void map (const tmp< Field< Type > > &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
void map (const UList< Type > &mapF, const FieldMapper &map, const bool applyFlip=true)
void map (const tmp< Field< Type > > &tmapF, const FieldMapper &map, const bool applyFlip=true)
void autoMap (const FieldMapper &map, const bool applyFlip=true)
void rmap (const UList< Type > &mapF, const labelUList &mapAddressing)
void rmap (const tmp< Field< Type > > &tmapF, const labelUList &mapAddressing)
void rmap (const UList< Type > &mapF, const labelUList &mapAddressing, const UList< scalar > &weights)
void rmap (const tmp< Field< Type > > &tmapF, const labelUList &mapAddressing, const UList< scalar > &weights)
void negate ()
void normalise ()
tmp< Field< cmptType > > component (const direction) const
void replace (const direction, const UList< cmptType > &)
void replace (const direction, const tmp< Field< cmptType > > &)
void replace (const direction, const cmptType &)
void clamp_min (const Type &lower)
void clamp_max (const Type &upper)
void clamp_range (const Type &lower, const Type &upper)
void clamp_range (const MinMax< Type > &range)
template<class VSForm >
VSForm block (const label start) const
tmp< Field< Type > > T () const
void writeEntry (const word &keyword, Ostream &os) const
SubField< Type > slice (const label pos, label len=-1)
const SubField< Type > slice (const label pos, label len=-1) const
SubField< Type > slice (const labelRange &range)
const SubField< Type > slice (const labelRange &range) const
void operator= (const Field< Type > &)
void operator= (const tmp< Field< Type > > &)
void operator= (const UList< Type > &rhs)
void operator= (const SubField< Type > &rhs)
template<class Addr >
void operator= (const IndirectListBase< Type, Addr > &rhs)
void operator= (Field< Type > &&rhs)
void operator= (List< Type > &&rhs)
template<int SizeMin>
void operator= (DynamicList< Type, SizeMin > &&rhs)
void operator= (const Type &val)
void operator= (const Foam::zero)
template<class Form , class Cmpt , direction nCmpt>
void operator= (const VectorSpace< Form, Cmpt, nCmpt > &)
void operator+= (const UList< Type > &)
void operator+= (const tmp< Field< Type > > &)
void operator-= (const UList< Type > &)
void operator-= (const tmp< Field< Type > > &)
void operator*= (const UList< scalar > &)
void operator*= (const tmp< Field< scalar > > &)
void operator/= (const UList< scalar > &)
void operator/= (const tmp< Field< scalar > > &)
void operator+= (const Type &)
void operator-= (const Type &)
void operator*= (const scalar &)
void operator/= (const scalar &)
template<class Type >
void operator= (const tmp< Field > &rhs)
void normalise ()
void normalise ()
void normalise ()
void normalise ()
Public Member Functions inherited from FieldBase
constexpr FieldBase () noexcept
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Public Member Functions inherited from List< Type >
constexpr List () noexcept
List (const label len)
List (const label len, const Type &val)
List (const label len, const Foam::zero)
List (const Foam::one, const Type &val)
List (const Foam::one, Type &&val)
List (const Foam::one, const Foam::zero)
List (const List< Type > &a)
List (const UList< Type > &a)
List (List< Type > &a, bool reuse)
List (const UList< Type > &list, const labelUList &indices)
List (const UList< Type > &list, const FixedList< label, N > &indices)
List (const FixedList< Type, N > &list)
List (const PtrList< Type > &list)
List (const SLList< Type > &list)
List (const IndirectListBase< Type, Addr > &list)
List (std::initializer_list< Type > list)
List (List< Type > &&list)
List (DynamicList< Type, SizeMin > &&list)
List (SLList< Type > &&list)
List (Istream &is)
autoPtr< List< Type > > clone () const
~List ()
void clear ()
void resize (const label len)
void resize (const label len, const Type &val)
void resize (const label newLen)
void resize_nocopy (const label len)
void setSize (const label n)
void setSize (const label n, const Type &val)
void transfer (List< Type > &list)
void transfer (DynamicList< Type, SizeMin > &list)
Type & newElmt (const label i)
Type & emplace_back (Args &&... args)
void push_back (const Type &val)
void push_back (Type &&val)
void push_back (const UList< Type > &list)
void push_back (const IndirectListBase< Type, Addr > &list)
label push_uniq (const Type &val)
void pop_back (label n=1)
void operator= (const UList< Type > &a)
void operator= (const List< Type > &list)
void operator= (const SLList< Type > &list)
void operator= (const IndirectListBase< Type, Addr > &list)
void operator= (const FixedList< Type, N > &list)
void operator= (std::initializer_list< Type > list)
void operator= (const Type &val)
void operator= (const Foam::zero)
void operator= (List< Type > &&list)
void operator= (DynamicList< Type, SizeMin > &&list)
void operator= (SLList< Type > &&list)
Istream & readList (Istream &is)
Istream & readList (Istream &is)
Istream & readList (Istream &is)
void shallowCopy (const UList< Type > &)=delete
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type set (const label i, bool val=true)
void append (const Type &val)
void append (Type &&val)
void append (const UList< Type > &list)
void append (const IndirectListBase< Type, Addr > &list)
label appendUniq (const Type &val)
Public Member Functions inherited from UList< T >
UList (const UList< T > &)=default
constexpr UList () noexcept
UList (T *__restrict__ v, const label len) noexcept
label fcIndex (const label i) const noexcept
label rcIndex (const label i) const noexcept
const T & fcValue (const label i) const
T & fcValue (const label i)
const T & rcValue (const label i) const
T & rcValue (const label i)
const T * cdata () const noexcept
T * data () noexcept
const char * cdata_bytes () const noexcept
char * data_bytes () noexcept
T & front ()
const T & front () const
T & back ()
const T & back () const
std::streamsize size_bytes () const noexcept
std::streamsize byteSize () const
void checkStart (const label start) const
void checkSize (const label size) const
void checkRange (const label start, const label len) const
void checkIndex (const label i) const
bool uniform () const
label find (const T &val, label pos=0) const
label rfind (const T &val, label pos=-1) const
bool contains (const T &val, label pos=0) const
void moveFirst (const label i)
void moveLast (const label i)
void swapFirst (const label i)
void swapLast (const label i)
void shallowCopy (const UList< T > &list)
void deepCopy (const UList< T > &list)
template<class Addr >
void deepCopy (const IndirectListBase< T, Addr > &list)
SubList< T > slice (const label pos, label len=-1)
const SubList< T > slice (const label pos, label len=-1) const
SubList< T > slice (const labelRange &range)
const SubList< T > slice (const labelRange &range) const
T & operator[] (const label i)
const T & operator[] (const label i) const
operator const Foam::List< T > & () const
void operator= (const T &val)
void operator= (const Foam::zero)
iterator begin () noexcept
iterator end () noexcept
iterator begin (const label i) noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
const_iterator begin () const noexcept
const_iterator end () const noexcept
const_iterator cbegin (const label i) const noexcept
const_iterator begin (const label i) const noexcept
reverse_iterator rbegin ()
reverse_iterator rend ()
const_reverse_iterator crbegin () const
const_reverse_iterator crend () const
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
bool empty () const noexcept
label size () const noexcept
void swap (UList< T > &list)
bool operator== (const UList< T > &a) const
bool operator!= (const UList< T > &a) const
bool operator< (const UList< T > &list) const
bool operator> (const UList< T > &a) const
bool operator<= (const UList< T > &a) const
bool operator>= (const UList< T > &a) const
Istream & readList (Istream &is)
void writeEntry (const word &keyword, Ostream &os) const
Ostream & writeList (Ostream &os, const label shortLen=0) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type test (const label i) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type get (const label i) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type unset (const label i)
T & first ()
const T & first () const
T & last ()
const T & last () const
bool found (const T &val, label pos=0) const
Istream & readList (Istream &is)
Ostream & writeList (Ostream &os, const label) const
const bool & operator[] (const label i) const
UPstream::commsStruct & operator[] (const label procID)
const UPstream::commsStruct & operator[] (const label procID) const
Foam::UPstream::commsStruct & operator[] (const label procID)
const Foam::UPstream::commsStruct & operator[] (const label procID) const
Ostream & writeList (Ostream &os, const label) const
Istream & readList (Istream &is)
Static Public Member Functions
static const Field< Type > & null ()
static autoPtr< Field< Type > > New (Istream &is)
template<class Type2 >
static tmp< Field< Type > > NewCalculatedType (const Field< Type2 > &f)
Static Public Member Functions inherited from List< Type >
static const List< Type > & null ()
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
static constexpr label max_size () noexcept
Friends
Ostream & operator<< (Ostream &, const Field< Type > &)
Ostream & operator<< (Ostream &, const tmp< Field< Type > > &)
Additional Inherited Members
Static Public Attributes inherited from FieldBase
static const char *const typeName
static bool allowConstructFromLargerSize = false
Protected Member Functions inherited from UList< T >
void setAddressableSize (const label n) noexcept
void size (const label n)
void writeEntry (Ostream &os) const
labelRange validateRange (const labelRange &requestedRange) const
UList< T > & operator= (const UList< T > &)=delete
void writeEntry (Ostream &os) const
void writeEntry (Ostream &os) const
Detailed Description
template<class Type>
class Foam::Field< Type >
Generic templated field type.
Source files
Field.H
FieldFunctions.H
FieldFunctionsM.H
FieldMapper.H
FieldI.H
FieldM.H
Field.C
FieldBase.C
FieldFunctions.C
FieldFunctionsM.C
Definition at line 106 of file Field.H.
Member Typedef Documentation
cmptType
template<class Type > typedef pTraits<Type>::cmptType cmptType
Definition at line 114 of file Field.H.
subField
template<class Type > typedef SubField<Type> subField
Definition at line 117 of file Field.H.
Constructor & Destructor Documentation
Field() [1/28]
template<class Type > constexpr Field () inline constexpr noexcept
Definition at line 33 of file FieldI.H.
Field() [2/28]
template<class Type > Field (const label len) inline explicit
Definition at line 40 of file FieldI.H.
Field() [3/28]
template<class Type > Field (const label len, const Type & val) inline
Definition at line 47 of file FieldI.H.
Field() [4/28]
template<class Type > Field (const label len, const Foam::zero) inline
Definition at line 54 of file FieldI.H.
Field() [5/28]
template<class Type > Field (const Foam::one , const Type & val) inline
Definition at line 61 of file FieldI.H.
Field() [6/28]
template<class Type > Field (const Foam::one , Type && val) inline
Definition at line 68 of file FieldI.H.
Field() [7/28]
template<class Type > Field (const Foam::one , const Foam::zero) inline
Definition at line 75 of file FieldI.H.
Field() [8/28]
template<class Type > Field (const Field< Type > & fld) inline
Definition at line 82 of file FieldI.H.
Field() [9/28]
template<class Type > Field (const UList< Type > & list) inline explicit
Definition at line 89 of file FieldI.H.
Field() [10/28]
template<class Type > template<class Addr > Field (const IndirectListBase< Type, Addr > & list) inline explicit
Definition at line 97 of file FieldI.H.
Field() [11/28]
template<class Type > Field (Field< Type > && fld) inline
Definition at line 104 of file FieldI.H.
References fld(), and List< T >::transfer().
Field() [12/28]
template<class Type > Field (List< Type > && list) inline
Definition at line 113 of file FieldI.H.
References List< T >::transfer().
Field() [13/28]
template<class Type > template<int SizeMin> Field (DynamicList< Type, SizeMin > && list) inline
Definition at line 123 of file FieldI.H.
References List< T >::transfer().
Field() [14/28]
template<class Type > Field (const UList< Type > & mapF, const labelUList & mapAddressing)
Definition at line 31 of file Field.C.
References Field< Type >::map().
Field() [15/28]
template<class Type > Field (const tmp< Field< Type > > & tmapF, const labelUList & mapAddressing)
Definition at line 44 of file Field.C.
References Field< Type >::map().
Field() [16/28]
template<class Type > Field (const UList< Type > & mapF, const labelListList & mapAddressing, const scalarListList & weights)
Definition at line 57 of file Field.C.
References Field< Type >::map().
Field() [17/28]
template<class Type > Field (const tmp< Field< Type > > & tmapF, const labelListList & mapAddressing, const scalarListList & weights)
Definition at line 71 of file Field.C.
References Field< Type >::map().
Field() [18/28]
template<class Type > Field (const UList< Type > & mapF, const FieldMapper & map, const bool applyFlip = true)
Definition at line 85 of file Field.C.
References Field< Type >::map().
Field() [19/28]
template<class Type > Field (const UList< Type > & mapF, const FieldMapper & map, const Type & defaultValue, const bool applyFlip = true)
Definition at line 99 of file Field.C.
References Field< Type >::map().
Field() [20/28]
template<class Type > Field (const UList< Type > & mapF, const FieldMapper & map, const UList< Type > & defaultValues, const bool applyFlip = true)
Definition at line 114 of file Field.C.
References Field< Type >::map().
Field() [21/28]
template<class Type > Field (const tmp< Field< Type > > & tmapF, const FieldMapper & map, const bool applyFlip = true)
Definition at line 129 of file Field.C.
References Field< Type >::map().
Field() [22/28]
template<class Type > Field (const tmp< Field< Type > > & tmapF, const FieldMapper & map, const Type & defaultValue, const bool applyFlip = true)
Definition at line 143 of file Field.C.
References Field< Type >::map().
Field() [23/28]
template<class Type > Field (const tmp< Field< Type > > & tmapF, const FieldMapper & map, const UList< Type > & defaultValues, const bool applyFlip = true)
Definition at line 158 of file Field.C.
References Field< Type >::map().
Field() [24/28]
template<class Type > Field (Field< Type > & fld, bool reuse) inline
Definition at line 132 of file FieldI.H.
Field() [25/28]
template<class Type > Field (const tmp< Field< Type > > & tfld) inline
Definition at line 139 of file FieldI.H.
Field() [26/28]
template<class Type > Field (Istream & is) inline
Definition at line 148 of file FieldI.H.
Field() [27/28]
template<class Type > Field (const entry & e, const label len)
Definition at line 173 of file Field.C.
References Field< Type >::assign(), and e.
Field() [28/28]
template<class Type > Field (const word & key, const dictionary & dict, const label len, IOobjectOption::readOption readOpt = IOobjectOption::MUST_READ)
Parameters
key Lookup key. Uses LITERAL (not REGEX)
dict dictionary
len length
Definition at line 180 of file Field.C.
Member Function Documentation
null()
template<class Type > const Foam::Field< Type > & null () inline static
Definition at line 24 of file FieldI.H.
Referenced by slicedFaPatchField< Type >::gradientBoundaryCoeffs(), slicedFvPatchField< Type >::gradientBoundaryCoeffs(), slicedFaPatchField< Type >::gradientInternalCoeffs(), slicedFvPatchField< Type >::gradientInternalCoeffs(), slicedFaPatchField< Type >::patchInternalField(), slicedFvPatchField< Type >::patchInternalField(), slicedFaPatchField< Type >::patchNeighbourField(), slicedFvPatchField< Type >::patchNeighbourField(), slicedFaPatchField< Type >::patchNeighbourField(), slicedFvPatchField< Type >::patchNeighbourField(), slicedFaPatchField< Type >::snGrad(), slicedFvPatchField< Type >::snGrad(), slicedFaPatchField< Type >::valueBoundaryCoeffs(), slicedFvPatchField< Type >::valueBoundaryCoeffs(), slicedFaPatchField< Type >::valueInternalCoeffs(), and slicedFvPatchField< Type >::valueInternalCoeffs().
clone()
template<class Type > Foam::tmp< Foam::Field< Type > > clone () const inline
Definition at line 155 of file FieldI.H.
References Foam::New().
New()
template<class Type > static autoPtr< Field< Type > > New (Istream & is) inline static
Definition at line 286 of file Field.H.
Referenced by Field< Type >::NewCalculatedType().
NewCalculatedType()
template<class Type > template<class Type2 > static tmp< Field< Type > > NewCalculatedType (const Field< Type2 > & f) inline static
Definition at line 294 of file Field.H.
References f(), and Field< Type >::New().
assign() [1/2]
template<class Type > void assign (const entry & e, const label len)
Definition at line 207 of file Field.C.
Referenced by Field< Type >::Field(), faePatchField< Type >::readValueEntry(), faPatchField< Type >::readValueEntry(), fvPatchField< Type >::readValueEntry(), fvsPatchField< Type >::readValueEntry(), and valuePointPatchField< Type >::readValueEntry().
assign() [2/2]
template<class Type > bool assign (const word & key, const dictionary & dict, const label len, IOobjectOption::readOption readOpt = IOobjectOption::MUST_READ)
Parameters
key Lookup key. Uses LITERAL (not REGEX)
dict dictionary
len expected length
Definition at line 265 of file Field.C.
map() [1/6]
template<class Type > void map (const UList< Type > & mapF, const labelUList & mapAddressing)
Definition at line 302 of file Field.C.
References f(), UPtrList< T >::size(), and UList< T >::size().
Referenced by conjugateGradient::computeCorrection(), externalWallHeatFluxTemperatureFvPatchScalarField::externalWallHeatFluxTemperatureFvPatchScalarField(), Field< Type >::Field(), Field< Type >::Field(), Field< Type >::Field(), Field< Type >::Field(), Field< Type >::Field(), Field< Type >::Field(), Field< Type >::Field(), Field< Type >::Field(), Field< Type >::Field(), Field< Type >::Field(), fvPatchField< Type >::fvPatchField(), outletMappedUniformInletFvPatchField< Type >::outletMappedUniformInletFvPatchField(), uniformFixedValueFaPatchField< Type >::uniformFixedValueFaPatchField(), uniformFixedValueFvPatchField< Type >::uniformFixedValueFvPatchField(), uniformFixedValuePointPatchField< Type >::uniformFixedValuePointPatchField(), and uniformInletOutletFvPatchField< Type >::uniformInletOutletFvPatchField().
map() [2/6]
template<class Type > void map (const tmp< Field< Type > > & tmapF, const labelUList & mapAddressing)
Definition at line 331 of file Field.C.
map() [3/6]
template<class Type > void map (const UList< Type > & mapF, const labelListList & mapAddressing, const scalarListList & weights)
Definition at line 343 of file Field.C.
map() [4/6]
template<class Type > void map (const tmp< Field< Type > > & tmapF, const labelListList & mapAddressing, const scalarListList & weights)
Definition at line 380 of file Field.C.
map() [5/6]
template<class Type > void map (const UList< Type > & mapF, const FieldMapper & map, const bool applyFlip = true)
Definition at line 393 of file Field.C.
map() [6/6]
template<class Type > void map (const tmp< Field< Type > > & tmapF, const FieldMapper & map, const bool applyFlip = true)
Definition at line 452 of file Field.C.
autoMap()
template<class Type > void autoMap (const FieldMapper & map, const bool applyFlip = true)
Definition at line 465 of file Field.C.
References FieldMapper::distributed(), and FieldMapper::distributeMap().
Referenced by faePatchField< Type >::autoMap(), fixedGradientFaPatchField< Type >::autoMap(), mixedFaPatchField< Type >::autoMap(), faPatchField< Type >::autoMap(), fvPatchField< Type >::autoMap(), fvsPatchField< Type >::autoMap(), Cloud< ParticleType >::autoMap(), angularOscillatingDisplacementPointPatchVectorField::autoMap(), angularOscillatingVelocityPointPatchVectorField::autoMap(), oscillatingVelocityPointPatchVectorField::autoMap(), timeVaryingMappedFixedValuePointPatchField< Type >::autoMap(), uniformFixedValuePointPatchField< Type >::autoMap(), sixDoFRigidBodyDisplacementPointPatchVectorField::autoMap(), uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField::autoMap(), and valuePointPatchField< vector >::valuePointPatchField().
rmap() [1/4]
template<class Type > void rmap (const UList< Type > & mapF, const labelUList & mapAddressing)
Definition at line 528 of file Field.C.
References f(), and forAll.
Referenced by extendedEdgeMesh::add(), fvPatchField< symmTensor >::extrapolateInternal(), extendedEdgeMesh::flipNormals(), faePatchField< Type >::rmap(), faPatchField< Type >::rmap(), fvsPatchField< Type >::rmap(), timeVaryingMappedFixedValuePointPatchField< Type >::rmap(), uniformFixedValuePointPatchField< Type >::rmap(), valuePointPatchField< Type >::rmap(), angularOscillatingDisplacementPointPatchVectorField::rmap(), angularOscillatingVelocityPointPatchVectorField::rmap(), oscillatingVelocityPointPatchVectorField::rmap(), sixDoFRigidBodyDisplacementPointPatchVectorField::rmap(), and uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField::rmap().
rmap() [2/4]
template<class Type > void rmap (const tmp< Field< Type > > & tmapF, const labelUList & mapAddressing)
Definition at line 549 of file Field.C.
References PtrList< T >::clear().
rmap() [3/4]
template<class Type > void rmap (const UList< Type > & mapF, const labelUList & mapAddressing, const UList< scalar > & weights)
Definition at line 561 of file Field.C.
References f(), forAll, and Foam::Zero.
rmap() [4/4]
template<class Type > void rmap (const tmp< Field< Type > > & tmapF, const labelUList & mapAddressing, const UList< scalar > & weights)
Definition at line 580 of file Field.C.
References PtrList< T >::clear().
negate()
template<class Type > void negate ()
Definition at line 593 of file Field.C.
References TFOR_ALL_F_OP_OP_F.
normalise() [1/5]
template<class Type > void normalise ()
Definition at line 601 of file Field.C.
Referenced by searchableExtrudedCircle::getNormal(), and searchableSphere::getNormal().
component()
template<class Type > Foam::tmp< Foam::Field< typename Foam::Field< Type >::cmptType > > component (const direction d) const
Definition at line 607 of file Field.C.
References Foam::component(), and Foam::New().
Referenced by sensitivitySurface::accumulateIntegrand(), sensitivitySurfacePoints::accumulateIntegrand(), sensitivityVolBSplinesFI::assembleSensitivities(), setFlow::execute(), NURBS3DVolume::findPointsInBox(), uniformBin::initialise(), and sensitivityBezier::write().
replace() [1/3]
template<class Type > void replace (const direction d, const UList< cmptType > & sf)
Definition at line 619 of file Field.C.
References TFOR_ALL_F_OP_FUNC_S_F.
Referenced by anisotropicFilter::anisotropicFilter(), anisotropicFilter::anisotropicFilter(), displacementComponentLaplacianFvMotionSolver::curPoints(), setFlow::execute(), and dynamicInkJetFvMesh::update().
replace() [2/3]
template<class Type > void replace (const direction d, const tmp< Field< cmptType > > & tsf)
Definition at line 631 of file Field.C.
References PtrList< T >::clear().
replace() [3/3]
template<class Type > void replace (const direction d, const cmptType & c)
Definition at line 643 of file Field.C.
References TFOR_ALL_F_OP_FUNC_S_S.
clamp_min()
template<class Type > void clamp_min (const Type & lower)
Definition at line 655 of file Field.C.
References Foam::max().
clamp_max()
template<class Type > void clamp_max (const Type & upper)
Definition at line 666 of file Field.C.
References Foam::min().
clamp_range() [1/2]
template<class Type > void clamp_range (const Type & lower, const Type & upper)
Definition at line 678 of file Field.C.
References Foam::max(), and Foam::min().
Referenced by Moraga::Cl(), and Field< Type >::clamp_range().
clamp_range() [2/2]
template<class Type > void clamp_range (const MinMax< Type > & range)
Definition at line 691 of file Field.C.
References Field< Type >::clamp_range(), and range.
block()
template<class Type > template<class VSForm > VSForm block (const label start) const
Definition at line 699 of file Field.C.
Referenced by rigidBodyModel::forwardDynamics(), rigidBodyModel::forwardDynamicsCorrection(), Pxyz::jcalc(), Rs::jcalc(), Rxyz::jcalc(), Ryxz::jcalc(), Rzyx::jcalc(), and joint::unitQuaternion().
T()
template<class Type > Foam::tmp< Foam::Field< Type > > T () const
Definition at line 711 of file Field.C.
References Foam::New(), and Foam::T().
writeEntry()
template<class Type > void writeEntry (const word & keyword, Ostream & os) const
Definition at line 720 of file Field.C.
References token::END_STATEMENT, Foam::nl, os(), token::SPACE, UList< T >::writeEntry(), and Ostream::writeKeyword().
Referenced by angularOscillatingDisplacementPointPatchVectorField::write(), angularOscillatingVelocityPointPatchVectorField::write(), oscillatingVelocityPointPatchVectorField::write(), alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField::write(), alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField::write(), alphatPhaseChangeWallFunctionFvPatchScalarField::write(), alphatWallBoilingWallFunctionFvPatchScalarField::write(), sixDoFRigidBodyDisplacementPointPatchVectorField::write(), uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField::write(), fvsPatchField< Type >::write(), DimensionedField< Type, GeoMesh >::writeData(), faePatchField< Type >::writeValueEntry(), faPatchField< Type >::writeValueEntry(), fvPatchField< Type >::writeValueEntry(), fvsPatchField< Type >::writeValueEntry(), and valuePointPatchField< Type >::writeValueEntry().
slice() [1/4]
template<class Type > Foam::SubField< Type > slice (const label pos, label len = -1)
Definition at line 174 of file SubField.H.
References Foam::pos(), and UList< T >::size().
slice() [2/4]
template<class Type > const Foam::SubField< Type > slice (const label pos, label len = -1) const
Definition at line 186 of file SubField.H.
References Foam::pos(), and UList< T >::size().
slice() [3/4]
template<class Type > Foam::SubField< Type > slice (const labelRange & range)
Definition at line 198 of file SubField.H.
References range.
slice() [4/4]
template<class Type > const Foam::SubField< Type > slice (const labelRange & range) const
Definition at line 206 of file SubField.H.
References range.
operator=() [1/12]
template<class Type > void operator= (const Field< Type > & rhs)
Definition at line 747 of file Field.C.
References List< T >::operator=().
Referenced by fvPatchField< symmTensor >::autoMap(), CompactIOField< T, BaseType >::CompactIOField(), directionMixedFvPatchField< Type >::evaluate(), clampedPlateFaPatchField< Type >::evaluate(), faePatchField< Type >::faePatchField(), faPatchField< Type >::faPatchField(), faPatchField< scalar >::faPatchField(), fvPatchField< symmTensor >::fvPatchField(), fvPatchField< symmTensor >::fvPatchField(), fvsPatchField< scalar >::fvsPatchField(), GlobalIOField< Type >::GlobalIOField(), IOField< Type >::IOField(), adjointFarFieldPressureFvPatchScalarField::operator*=(), adjointFarFieldPressureFvPatchScalarField::operator*=(), adjointFarFieldPressureFvPatchScalarField::operator*=(), adjointFarFieldPressureFvPatchScalarField::operator+=(), adjointFarFieldPressureFvPatchScalarField::operator+=(), adjointFarFieldPressureFvPatchScalarField::operator+=(), adjointFarFieldPressureFvPatchScalarField::operator-=(), adjointFarFieldPressureFvPatchScalarField::operator-=(), adjointFarFieldPressureFvPatchScalarField::operator-=(), DimensionedField< symmTensor, Foam::volMesh >::operator/=(), adjointFarFieldPressureFvPatchScalarField::operator/=(), adjointFarFieldPressureFvPatchScalarField::operator/=(), adjointFarFieldPressureFvPatchScalarField::operator/=(), CompactIOField< T, BaseType >::operator=(), DimensionedField< Type, GeoMesh >::operator=(), faePatchField< Type >::operator=(), faPatchField< Type >::operator=(), IjkField< Type >::operator=(), adjointFarFieldPressureFvPatchScalarField::operator=(), fvsPatchField< Type >::operator=(), GlobalIOField< Type >::operator=(), IOField< label >::operator=(), IOField< Type >::operator=(), valuePointPatchField< vector >::operator=(), adjointFarFieldPressureFvPatchScalarField::operator=(), IjkField< Type >::operator=(), faePatchField< Type >::operator=(), fvPatchField< Type >::operator=(), IjkField< Type >::operator=(), adjointFarFieldPressureFvPatchScalarField::operator=(), faPatchField< Type >::operator=(), fvsPatchField< Type >::operator=(), valuePointPatchField< Type >::operator=(), faePatchField< Type >::operator==(), faPatchField< Type >::operator==(), faePatchField< Type >::operator==(), faPatchField< Type >::operator==(), fvPatchField< Type >::operator==(), fvsPatchField< Type >::operator==(), valuePointPatchField< Type >::operator==(), scaledFixedValueFvPatchField< Type >::operator==(), scaledFixedValueFvPatchField< Type >::operator==(), fvsPatchField< Type >::operator==(), valuePointPatchField< Type >::operator==(), faePatchField< Type >::operator==(), faPatchField< Type >::operator==(), fvPatchField< Type >::operator==(), fvsPatchField< Type >::operator==(), valuePointPatchField< Type >::operator==(), scaledFixedValueFvPatchField< Type >::operator==(), valuePointPatchField< Type >::operator==(), valuePointPatchField< vector >::operator==(), valuePointPatchField< vector >::operator==(), faePatchField< scalar >::readValueEntry(), IjkField< scalar >::resize(), scaledFixedValueFvPatchField< Type >::updateCoeffs(), oscillatingDisplacementPointPatchVectorField::updateCoeffs(), and waveMakerPointPatchVectorField::updateCoeffs().
operator=() [2/12]
template<class Type > void operator= (const tmp< Field< Type > > &)
operator=() [3/12]
template<class Type > void operator= (const UList< Type > & rhs) inline
Definition at line 164 of file FieldI.H.
operator=() [4/12]
template<class Type > void operator= (const SubField< Type > & rhs) inline
Definition at line 171 of file FieldI.H.
References List< T >::operator=().
operator=() [5/12]
template<class Type > template<class Addr > void operator= (const IndirectListBase< Type, Addr > & rhs) inline
Definition at line 179 of file FieldI.H.
References List< T >::operator=().
operator=() [6/12]
template<class Type > void operator= (Field< Type > && rhs) inline
Definition at line 189 of file FieldI.H.
References List< T >::transfer().
operator=() [7/12]
template<class Type > void operator= (List< Type > && rhs) inline
Definition at line 196 of file FieldI.H.
References List< T >::transfer().
operator=() [8/12]
template<class Type > template<int SizeMin> void operator= (DynamicList< Type, SizeMin > && rhs) inline
Definition at line 204 of file FieldI.H.
References List< T >::transfer().
operator=() [9/12]
template<class Type > void operator= (const Type & val) inline
Definition at line 211 of file FieldI.H.
References List< T >::operator=().
operator=() [10/12]
template<class Type > void operator= (const Foam::zero) inline
Definition at line 218 of file FieldI.H.
References List< T >::operator=(), and Foam::Zero.
operator=() [11/12]
template<class Type > template<class Form , class Cmpt , Foam::direction nCmpt> void operator= (const VectorSpace< Form, Cmpt, nCmpt > & vs)
Definition at line 772 of file Field.C.
References TFOR_ALL_F_OP_S.
operator+=() [1/3]
template<class Type > void operator+= (const UList< Type > & f)
Definition at line 799 of file Field.C.
Referenced by faPatchField< scalar >::faPatchField(), faPatchField< scalar >::faPatchField(), faePatchField< Type >::operator+=(), faPatchField< Type >::operator+=(), faePatchField< Type >::operator+=(), fvPatchField< Type >::operator+=(), fvsPatchField< Type >::operator+=(), fvPatchField< Type >::operator+=(), fvsPatchField< Type >::operator+=(), faePatchField< Type >::operator+=(), fvPatchField< Type >::operator+=(), and fvsPatchField< Type >::operator+=().
operator+=() [2/3]
template<class Type > void operator+= (const tmp< Field< Type > > & tf)
Definition at line 799 of file Field.C.
operator-=() [1/3]
template<class Type > void operator-= (const UList< Type > & f)
Definition at line 800 of file Field.C.
Referenced by faePatchField< scalar >::faePatchField(), faePatchField< scalar >::faePatchField(), fvsPatchField< scalar >::fvsPatchField(), faePatchField< Type >::operator-=(), faPatchField< Type >::operator-=(), faPatchField< Type >::operator-=(), fvPatchField< Type >::operator-=(), fvsPatchField< Type >::operator-=(), faPatchField< Type >::operator-=(), fvPatchField< Type >::operator-=(), and fvsPatchField< Type >::operator-=().
operator-=() [2/3]
template<class Type > void operator-= (const tmp< Field< Type > > & tf)
Definition at line 800 of file Field.C.
operator*=() [1/3]
template<class Type > void operator*= (const UList< scalar > & f)
Definition at line 801 of file Field.C.
Referenced by faePatchField< scalar >::faePatchField(), fvPatchField< symmTensor >::fvPatchField(), faePatchField< Type >::operator*=(), faPatchField< Type >::operator*=(), fvPatchField< Type >::operator*=(), fvsPatchField< Type >::operator*=(), fvsPatchField< Type >::operator*=(), faePatchField< Type >::operator*=(), faPatchField< Type >::operator*=(), fvPatchField< Type >::operator*=(), and fvsPatchField< Type >::operator*=().
operator*=() [2/3]
template<class Type > void operator*= (const tmp< Field< scalar > > & tf)
Definition at line 801 of file Field.C.
operator/=() [1/3]
template<class Type > void operator/= (const UList< scalar > & f)
Definition at line 802 of file Field.C.
References f(), and os().
Referenced by faePatchField< scalar >::faePatchField(), faPatchField< scalar >::faPatchField(), fvsPatchField< scalar >::fvsPatchField(), faePatchField< Type >::operator/=(), faPatchField< Type >::operator/=(), fvPatchField< Type >::operator/=(), fvPatchField< Type >::operator/=(), fvsPatchField< Type >::operator/=(), faePatchField< Type >::operator/=(), faPatchField< Type >::operator/=(), and fvPatchField< Type >::operator/=().
operator/=() [2/3]
template<class Type > void operator/= (const tmp< Field< scalar > > & tf)
Definition at line 802 of file Field.C.
operator+=() [3/3]
template<class Type > void operator+= (const Type & t)
Definition at line 799 of file Field.C.
operator-=() [3/3]
template<class Type > void operator-= (const Type & t)
Definition at line 800 of file Field.C.
operator*=() [3/3]
template<class Type > void operator*= (const scalar & t)
Definition at line 801 of file Field.C.
operator/=() [3/3]
template<class Type > void operator/= (const scalar & t)
Definition at line 802 of file Field.C.
operator=() [12/12]
template<class Type > template<class Type > void operator= (const tmp< Field< Type > > & rhs)
Definition at line 759 of file Field.C.
References List< T >::operator=().
normalise() [2/5]
void normalise ()
Definition at line 38 of file vectorField.C.
References Foam::floatScalarROOTVSMALL, Foam::magSqr(), s(), and Foam::sqrt().
normalise() [3/5]
void normalise ()
Definition at line 69 of file vectorField.C.
References Foam::doubleScalarROOTVSMALL, Foam::magSqr(), s(), and Foam::sqrt().
normalise() [4/5]
void normalise ()
normalise() [5/5]
void normalise ()
Friends And Related Symbol Documentation
operator<< [1/2]
template<class Type > Ostream & operator<< (Ostream & , const Field< Type > &) friend
operator<< [2/2]
template<class Type > Ostream & operator<< (Ostream & , const tmp< Field< Type > > &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/fields/Fields/Field/Field.H
src/OpenFOAM/fields/Fields/Field/Field.C
src/OpenFOAM/fields/Fields/Field/FieldI.H
src/OpenFOAM/fields/Fields/Field/SubField.H