OpenFOAM: dimensionSet Class Reference
dimensionSet Class Reference
Dimension set for the base types, which can be used to implement rigorous dimension checking for algebraic manipulation.
#include <dimensionSet.H>
Public Types
enum dimensionType {
MASS , LENGTH , TIME , TEMPERATURE ,
MOLES , CURRENT , LUMINOUS_INTENSITY
}
typedef FixedList< scalar, 7 > list_type
Public Member Functions
ClassName ("dimensionSet")
dimensionSet ()
dimensionSet (const scalar mass, const scalar length, const scalar time, const scalar temperature, const scalar moles, const scalar current=0, const scalar luminousIntensity=0)
dimensionSet (const FixedList< scalar, 7 > &dimensions)
dimensionSet (const dimensionSet &ds)
dimensionSet (const word &entryName, const dictionary &dict, IOobjectOption::readOption readOpt=IOobjectOption::MUST_READ)
autoPtr< dimensionSet > clone () const
dimensionSet (Istream &is)
bool dimensionless () const
const FixedList< scalar, 7 > & values () const noexcept
FixedList< scalar, 7 > & values () noexcept
void clear ()
void reset (const dimensionSet &ds)
bool readEntry (const word &entryName, const dictionary &dict, IOobjectOption::readOption readOpt=IOobjectOption::MUST_READ)
bool readIfPresent (const word &entryName, const dictionary &dict)
Istream & read (Istream &is, scalar &multiplier, const dictionary &)
Istream & read (Istream &is, scalar &multiplier, const HashTable< dimensionedScalar > &)
Istream & read (Istream &is, scalar &multiplier)
Ostream & write (Ostream &os, scalar &multiplier, const dimensionSets &writeUnits) const
Ostream & write (Ostream &os, scalar &multiplier) const
scalar operator[] (const dimensionType) const
scalar & operator[] (const dimensionType)
scalar operator[] (const label) const
scalar & operator[] (const label)
bool operator== (const dimensionSet &) const
bool operator!= (const dimensionSet &) const
bool operator= (const dimensionSet &) const
bool operator+= (const dimensionSet &) const
bool operator-= (const dimensionSet &) const
bool operator*= (const dimensionSet &)
bool operator/= (const dimensionSet &)
Static Public Member Functions
static bool checking (bool on) noexcept
static bool checking () noexcept
Static Public Attributes
static constexpr int nDimensions = 7
static const scalar smallExponent = SMALL
Detailed Description
Dimension set for the base types, which can be used to implement rigorous dimension checking for algebraic manipulation.
The dimensions are specified in the following order (SI units for reference only):
Property SI Description SI unit
MASS kilogram kg
LENGTH metre m
TIME second s
TEMPERATURE Kelvin K
MOLES mole mol
CURRENT Ampere A
LUMINOUS_INTENSITY Candela cd
Source files
dimensionSet.H
dimensionSet.C
dimensionSetIO.C
Definition at line 105 of file dimensionSet.H.
Member Typedef Documentation
list_type
typedef FixedList<scalar,7> list_type
Definition at line 110 of file dimensionSet.H.
Member Enumeration Documentation
dimensionType
enum dimensionType
Enumerator
MASS
kilogram kg
LENGTH
metre m
TIME
second s
TEMPERATURE
Kelvin K.
MOLES
mole mol
CURRENT
Ampere A.
LUMINOUS_INTENSITY
Candela cd.
Definition at line 119 of file dimensionSet.H.
Constructor & Destructor Documentation
dimensionSet() [1/6]
dimensionSet ()
Definition at line 64 of file dimensionSet.C.
dimensionSet() [2/6]
dimensionSet (const scalar mass, const scalar length, const scalar time, const scalar temperature, const scalar moles, const scalar current = 0, const scalar luminousIntensity = 0)
Definition at line 70 of file dimensionSet.C.
References dimensionSet::CURRENT, dimensionSet::LENGTH, dimensionSet::LUMINOUS_INTENSITY, dimensionSet::MASS, dimensionSet::MOLES, dimensionSet::TEMPERATURE, and dimensionSet::TIME.
dimensionSet() [3/6]
dimensionSet (const FixedList< scalar, 7 > & dimensions)
Definition at line 93 of file dimensionSet.C.
dimensionSet() [4/6]
dimensionSet (const dimensionSet & ds)
Definition at line 99 of file dimensionSet.C.
dimensionSet() [5/6]
dimensionSet (const word & entryName, const dictionary & dict, IOobjectOption::readOption readOpt = IOobjectOption::MUST_READ)
Parameters
entryName Lookup key. LITERAL (not REGEX)
Definition at line 30 of file dimensionSetIO.C.
References dict, and dimensionSet::readEntry().
dimensionSet() [6/6]
dimensionSet (Istream & is) explicit
Definition at line 43 of file dimensionSetIO.C.
Member Function Documentation
ClassName()
ClassName ("dimensionSet")
checking() [1/2]
static bool checking (bool on) inline static noexcept
Definition at line 215 of file dimensionSet.H.
checking() [2/2]
static bool checking () inline static noexcept
Definition at line 223 of file dimensionSet.H.
Referenced by SemiImplicitSource< Type >::addSup(), Foam::atan2(), Foam::checkMethod(), Foam::checkMethod(), Foam::checkMethod(), Foam::checkMethod(), Foam::checkMethod(), Foam::checkMethod(), Foam::clamp(), fvExprDriver::getOrReadFieldImpl(), Foam::hypot(), Foam::lerp(), Foam::max(), Foam::min(), Foam::operator+(), dimensionSet::operator+=(), Foam::operator-(), dimensionSet::operator-=(), dimensionSet::operator=(), Foam::pow(), Foam::pow(), Foam::pow(), Foam::pow(), Foam::pow(), Foam::pow(), Foam::pow(), Foam::pow(), Foam::pow(), Foam::pow(), Foam::pow(), Foam::pow(), Foam::pow(), Foam::pow(), Foam::pow(), Foam::pow(), Foam::pow(), Foam::stabilise(), and Foam::trans().
clone()
autoPtr< dimensionSet > clone () const inline
Definition at line 262 of file dimensionSet.H.
References autoPtr< T >::New().
dimensionless()
bool dimensionless () const
Definition at line 107 of file dimensionSet.C.
values() [1/2]
const Foam::FixedList< Foam::scalar, 7 > & values () const noexcept
Definition at line 123 of file dimensionSet.C.
Referenced by Foam::operator*(), and Foam::operator/().
values() [2/2]
Foam::FixedList< Foam::scalar, 7 > & values () noexcept
Definition at line 130 of file dimensionSet.C.
clear()
void clear ()
Definition at line 136 of file dimensionSet.C.
References Foam::Zero.
reset()
void reset (const dimensionSet & ds)
Definition at line 142 of file dimensionSet.C.
readEntry()
bool readEntry (const word & entryName, const dictionary & dict, IOobjectOption::readOption readOpt = IOobjectOption::MUST_READ)
Parameters
entryName Lookup key. LITERAL (not REGEX)
dict The dictionary
readOpt The read option
Definition at line 408 of file dimensionSetIO.C.
References dict, e, Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, dictionary::findEntry(), IOobjectOption::isReadRequired(), keyType::LITERAL, Foam::nl, IOobjectOption::NO_READ, and dictionary::relativeName().
Referenced by dimensionSet::dimensionSet(), and dimensionSet::readIfPresent().
readIfPresent()
bool readIfPresent (const word & entryName, const dictionary & dict) inline
Parameters
entryName Lookup key. LITERAL (not REGEX)
dict The dictionary
Definition at line 309 of file dimensionSet.H.
References dict, IOobjectOption::READ_IF_PRESENT, and dimensionSet::readEntry().
read() [1/3]
Foam::Istream & read (Istream & is, scalar & multiplier, const dictionary & readSet)
Definition at line 532 of file dimensionSetIO.C.
References UPtrList< T >::back(), token::BEGIN_SQR, dimensionSet::CURRENT, token::END_SQR, Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, FUNCTION_NAME, token::isNumber(), token::isWord(), keyType::LITERAL, dimensionSet::LUMINOUS_INTENSITY, dimensionSet::MASS, dimensionSet::nDimensions, Foam::nl, token::number(), Foam::pow(), PtrList< T >::resize(), s(), UPtrList< T >::size(), and token::wordToken().
read() [2/3]
Foam::Istream & read (Istream & is, scalar & multiplier, const HashTable< dimensionedScalar > & readSet)
Definition at line 445 of file dimensionSetIO.C.
References token::BEGIN_SQR, dimensionSet::CURRENT, token::END_SQR, Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, FUNCTION_NAME, token::isNumber(), dimensionSet::LUMINOUS_INTENSITY, dimensionSet::MASS, Foam::nl, and token::number().
read() [3/3]
Foam::Istream & read (Istream & is, scalar & multiplier)
Definition at line 522 of file dimensionSetIO.C.
References Foam::read(), and Foam::unitSet().
write() [1/2]
Foam::Ostream & write (Ostream & os, scalar & multiplier, const dimensionSets & writeUnits) const
Definition at line 656 of file dimensionSetIO.C.
References IOstreamOption::ASCII, token::BEGIN_SQR, IOstream::check(), token::END_SQR, forAll, IOstreamOption::format(), FUNCTION_NAME, Foam::mag(), dimensionSet::nDimensions, os(), Foam::pow(), OSstream::precision(), and token::SPACE.
write() [2/2]
Foam::Ostream & write (Ostream & os, scalar & multiplier) const
Definition at line 728 of file dimensionSetIO.C.
References os(), write(), and Foam::writeUnitSet().
operator[]() [1/4]
Foam::scalar operator[] (const dimensionType type) const
Definition at line 150 of file dimensionSet.C.
References Foam::type().
operator[]() [2/4]
Foam::scalar & operator[] (const dimensionType type)
Definition at line 156 of file dimensionSet.C.
References Foam::type().
operator[]() [3/4]
Foam::scalar operator[] (const label type) const
Definition at line 162 of file dimensionSet.C.
References Foam::type().
operator[]() [4/4]
Foam::scalar & operator[] (const label type)
Definition at line 168 of file dimensionSet.C.
References Foam::type().
operator==()
bool operator== (const dimensionSet & ds) const
Definition at line 174 of file dimensionSet.C.
References Foam::mag().
operator!=()
bool operator!= (const dimensionSet & ds) const
Definition at line 192 of file dimensionSet.C.
References Foam::operator==().
operator=()
bool operator= (const dimensionSet & ds) const
Definition at line 198 of file dimensionSet.C.
References Foam::checkDims(), and dimensionSet::checking().
operator+=()
bool operator+= (const dimensionSet & ds) const
Definition at line 209 of file dimensionSet.C.
References Foam::checkDims(), and dimensionSet::checking().
operator-=()
bool operator-= (const dimensionSet & ds) const
Definition at line 220 of file dimensionSet.C.
References Foam::checkDims(), and dimensionSet::checking().
operator*=()
bool operator*= (const dimensionSet & ds)
Definition at line 231 of file dimensionSet.C.
operator/=()
bool operator/= (const dimensionSet & ds)
Definition at line 239 of file dimensionSet.C.
Member Data Documentation
nDimensions
constexpr int nDimensions = 7 static constexpr
Definition at line 116 of file dimensionSet.H.
Referenced by dimensionSet::read(), and dimensionSet::write().
smallExponent
const Foam::scalar smallExponent = SMALL static
Definition at line 134 of file dimensionSet.H.
Referenced by Foam::operator>>().
The documentation for this class was generated from the following files:
src/OpenFOAM/dimensionSet/dimensionSet.H
src/OpenFOAM/dimensionSet/dimensionSet.C
src/OpenFOAM/dimensionSet/dimensionSetIO.C