OpenFOAM: fileOperationInitialise Class Reference
fileOperationInitialise Class Reference abstract
#include <fileOperationInitialise.H>
Public Member Functions
TypeName ("fileOperationInitialise")
fileOperationInitialise (int &argc, char **&argv)
declareRunTimeSelectionTable (autoPtr, fileOperationInitialise, word,(int &argc, char **&argv),(argc, argv))
virtual ~fileOperationInitialise ()=default
virtual bool needsThreading () const =0
Static Public Member Functions
static autoPtr< fileOperationInitialise > New (const word &type, int &argc, char **&argv)
Detailed Description
Definition at line 46 of file fileOperationInitialise.H.
Constructor & Destructor Documentation
fileOperationInitialise()
fileOperationInitialise (int & argc, char **& argv)
Definition at line 40 of file fileOperationInitialise.C.
References Foam::Info, Foam::nl, and Foam::setEnv().
~fileOperationInitialise()
virtual ~fileOperationInitialise () virtual default
Member Function Documentation
TypeName()
TypeName ("fileOperationInitialise")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , fileOperationInitialise , word , (int &argc, char **&argv) , (argc, argv))
New()
Foam::autoPtr< Foam::fileOperations::fileOperationInitialise > New (const word & type, int & argc, char **& argv) static
Definition at line 99 of file fileOperationInitialise.C.
References Foam::abort(), DebugInFunction, Foam::endl(), Foam::FatalError, FatalErrorInLookup, and Foam::type().
Referenced by argList::argList().
needsThreading()
virtual bool needsThreading () const pure virtual
Implemented in fileOperationInitialise_collated, and fileOperationInitialise_unthreaded.
The documentation for this class was generated from the following files:
src/OpenFOAM/global/fileOperations/fileOperation/fileOperationInitialise.H
src/OpenFOAM/global/fileOperations/fileOperation/fileOperationInitialise.C