OpenFOAM: ISstream Class Reference
ISstream Class Reference
Generic input stream using a standard (STL) stream.
#include <ISstream.H>
Public Member Functions
ISstream (std::istream &is, const string &streamName, IOstreamOption streamOpt=IOstreamOption())
ISstream (std::istream &is, const string &streamName, IOstreamOption::streamFormat fmt, IOstreamOption::compressionType cmp=IOstreamOption::UNCOMPRESSED)
ISstream (std::istream &is, const string &streamName, IOstreamOption::streamFormat fmt, IOstreamOption::versionNumber ver, IOstreamOption::compressionType cmp=IOstreamOption::UNCOMPRESSED)
virtual ~ISstream ()=default
virtual const fileName & name () const
virtual fileName & name ()
virtual const std::istream & stdStream () const
virtual std::istream & stdStream ()
virtual ios_base::fmtflags flags () const
virtual ios_base::fmtflags flags (const ios_base::fmtflags f)
void syncState ()
bool seekCommentEnd_Cstyle ()
bool continueReadUntilRightBrace (std::string &str, const bool stripComments=true)
ISstream & get (char &c)
int peek ()
ISstream & getLine (std::string &str, char delim='\n')
std::streamsize getLine (std::nullptr_t, char delim='\n')
ISstream & putback (const char c)
virtual Istream & read (token &t)
virtual Istream & read (char &c)
virtual Istream & read (word &str)
virtual Istream & read (string &str)
virtual Istream & read (label &val)
virtual Istream & read (float &val)
virtual Istream & read (double &val)
virtual Istream & read (char *data, std::streamsize count)
virtual Istream & readRaw (char *data, std::streamsize count)
virtual bool beginRawRead ()
virtual bool endRawRead ()
virtual void rewind ()
virtual void print (Ostream &os) const
Public Member Functions inherited from Istream
Istream (const Istream &)=default
virtual ~Istream ()=default
Istream (IOstreamOption streamOpt=IOstreamOption())
Istream (IOstreamOption::streamFormat fmt, IOstreamOption::compressionType cmp=IOstreamOption::UNCOMPRESSED)
const token & peekBack () const noexcept
bool peekBack (token &tok)
void putBack (const token &tok)
bool getBack (token &tok)
bool readBegin (const char *funcName)
bool readEnd (const char *funcName)
char readBeginList (const char *funcName)
char readEndList (const char *funcName)
Istream & operator() () const
Public Member Functions inherited from IOstream
IOstream (const IOstream &)=default
virtual ~IOstream ()=default
IOstream (IOstreamOption streamOpt=IOstreamOption())
IOstream (IOstreamOption::streamFormat fmt, IOstreamOption::versionNumber ver, IOstreamOption::compressionType cmp=IOstreamOption::UNCOMPRESSED)
fileName relativeName () const
virtual bool check (const char *operation) const
bool fatalCheck (const char *operation) const
bool opened () const noexcept
bool closed () const noexcept
bool good () const noexcept
bool eof () const noexcept
bool fail () const noexcept
bool bad () const noexcept
operator bool () const noexcept
bool operator! () const noexcept
unsigned labelByteSize () const noexcept
unsigned scalarByteSize () const noexcept
void setLabelByteSize (unsigned nbytes) noexcept
void setScalarByteSize (unsigned nbytes) noexcept
template<class T = label>
std::enable_if< std::is_integral< T >::value, bool >::type checkLabelSize () const noexcept
template<class T = scalar>
std::enable_if< std::is_floating_point< T >::value, bool >::type checkScalarSize () const noexcept
label lineNumber () const noexcept
label & lineNumber () noexcept
label lineNumber (const label num) noexcept
void setEof () noexcept
void setFail () noexcept
void setBad ()
ios_base::fmtflags setf (const ios_base::fmtflags f)
ios_base::fmtflags setf (const ios_base::fmtflags f, const ios_base::fmtflags mask)
void unsetf (const ios_base::fmtflags f)
void print (Ostream &os, const int streamState) const
InfoProxy< IOstream > info () const noexcept
Public Member Functions inherited from IOstreamOption
constexpr IOstreamOption (streamFormat fmt=streamFormat::ASCII, compressionType comp=compressionType::UNCOMPRESSED) noexcept
constexpr IOstreamOption (streamFormat fmt, compressionType comp, versionNumber ver) noexcept
constexpr IOstreamOption (streamFormat fmt, versionNumber ver, compressionType comp=compressionType::UNCOMPRESSED) noexcept
IOstreamOption (const IOstreamOption &opt, streamFormat fmt) noexcept
streamFormat format () const noexcept
streamFormat format (const streamFormat fmt) noexcept
streamFormat format (const word &formatName)
compressionType compression () const noexcept
compressionType compression (const compressionType comp) noexcept
compressionType compression (const word &compName)
versionNumber version () const noexcept
versionNumber version (const versionNumber ver) noexcept
versionNumber version (const token &tok)
Additional Inherited Members
Public Types inherited from IOstream
enum streamAccess : char { CLOSED = 0 , OPENED }
Public Types inherited from IOstreamOption
enum streamFormat : char { ASCII = 0 , BINARY }
enum compressionType : char { UNCOMPRESSED = 0 , COMPRESSED }
enum appendType : char { NON_APPEND = 0 , APPEND }
enum atomicType : char { NON_ATOMIC = 0 , ATOMIC }
Static Public Member Functions inherited from IOstream
static unsigned int defaultPrecision () noexcept
static unsigned int defaultPrecision (unsigned int prec) noexcept
Static Public Member Functions inherited from IOstreamOption
static streamFormat formatEnum (const word &formatName, const streamFormat deflt=streamFormat::ASCII)
static streamFormat formatEnum (const word &key, const dictionary &dict, const streamFormat deflt=streamFormat::ASCII)
static compressionType compressionEnum (const word &compName, const compressionType deflt=compressionType::UNCOMPRESSED)
static compressionType compressionEnum (const word &key, const dictionary &dict, const compressionType deflt=compressionType::UNCOMPRESSED)
Static Public Attributes inherited from IOstream
static unsigned int precision_
Static Public Attributes inherited from IOstreamOption
static const Enum< streamFormat > formatNames
static const versionNumber currentVersion
Protected Member Functions inherited from Istream
bool hasPutback () const noexcept
Protected Member Functions inherited from IOstream
void setOpened () noexcept
void setClosed () noexcept
void setState (std::ios_base::iostate state) noexcept
void setGood () noexcept
Protected Attributes inherited from IOstream
std::ios_base::iostate ioState_
streamAccess openClosed_
unsigned char sizeofLabel_
unsigned char sizeofScalar_
label lineNumber_
Static Protected Attributes inherited from IOstream
static fileName staticName_
Detailed Description
Generic input stream using a standard (STL) stream.
Source files
ISstream.H
ISstreamI.H
ISstream.C
Definition at line 51 of file ISstream.H.
Constructor & Destructor Documentation
ISstream() [1/3]
ISstream (std::istream & is, const string & streamName, IOstreamOption streamOpt = IOstreamOption()) inline
Definition at line 24 of file ISstreamI.H.
References IOstream::setGood(), IOstream::setOpened(), and ISstream::syncState().
ISstream() [2/3]
ISstream (std::istream & is, const string & streamName, IOstreamOption::streamFormat fmt, IOstreamOption::compressionType cmp = IOstreamOption::UNCOMPRESSED) inline
Definition at line 86 of file ISstream.H.
ISstream() [3/3]
ISstream (std::istream & is, const string & streamName, IOstreamOption::streamFormat fmt, IOstreamOption::versionNumber ver, IOstreamOption::compressionType cmp = IOstreamOption::UNCOMPRESSED) inline
Definition at line 98 of file ISstream.H.
~ISstream()
virtual ~ISstream () virtual default
Member Function Documentation
name() [1/2]
virtual const fileName & name () const inline virtual
Reimplemented from IOstream.
Reimplemented in IFstream.
Definition at line 121 of file ISstream.H.
Referenced by ISstream::print(), and IStringStream::print().
name() [2/2]
virtual fileName & name () inline virtual
Reimplemented in IFstream.
Definition at line 124 of file ISstream.H.
stdStream() [1/2]
virtual const std::istream & stdStream () const inline virtual
Reimplemented in IFstream.
Definition at line 130 of file ISstream.H.
stdStream() [2/2]
virtual std::istream & stdStream () inline virtual
Reimplemented in IFstream.
Definition at line 133 of file ISstream.H.
flags() [1/2]
virtual ios_base::fmtflags flags () const inline virtual
Implements IOstream.
Reimplemented in dummyISstream.
Definition at line 139 of file ISstream.H.
flags() [2/2]
virtual ios_base::fmtflags flags (const ios_base::fmtflags f) inline virtual
Implements IOstream.
Reimplemented in dummyISstream.
Definition at line 145 of file ISstream.H.
References f().
syncState()
void syncState () inline
Definition at line 151 of file ISstream.H.
References IOstream::setState().
Referenced by ISstream::ISstream().
seekCommentEnd_Cstyle()
bool seekCommentEnd_Cstyle ()
Definition at line 72 of file ISstream.C.
References ISstream::get().
continueReadUntilRightBrace()
bool continueReadUntilRightBrace (std::string & str, const bool stripComments = true)
Definition at line 505 of file ISstream.C.
References token::BEGIN_BLOCK, token::END_BLOCK, and Foam::readUntilBalancedDelimiter().
get()
Foam::ISstream & get (char & c) inline
Definition at line 49 of file ISstreamI.H.
References ISstream::get().
Referenced by ISstream::get(), and ISstream::seekCommentEnd_Cstyle().
peek()
int peek () inline
Definition at line 63 of file ISstreamI.H.
getLine() [1/2]
Foam::ISstream & getLine (std::string & str, char delim = '\n') inline
Definition at line 69 of file ISstreamI.H.
getLine() [2/2]
std::streamsize getLine (std::nullptr_t , char delim = '\n') inline
Definition at line 83 of file ISstreamI.H.
putback()
Foam::ISstream & putback (const char c) inline
Definition at line 99 of file ISstreamI.H.
read() [1/8]
Foam::Istream & read (token & t) virtual
Implements Istream.
Reimplemented in dummyISstream, and ensightReadFile.
Definition at line 523 of file ISstream.C.
References token::ASSIGN, token::BEGIN_BLOCK, token::BEGIN_LIST, token::BEGIN_SQR, Foam::charToWord(), token::COLON, token::COMMA, token::DIRECTIVE, token::DIVIDE, token::DOLLAR, token::DQUOTE, token::END_BLOCK, token::END_LIST, token::END_SQR, token::END_STATEMENT, Foam::endl(), token::ERROR, Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, Istream::getBack(), token::HASH, IOWarningInFunction, token::compound::isCompound(), token::lineNumber(), token::MINUS, token::MULTIPLY, token::compound::New(), Foam::nl, token::PLUS, Foam::read(), Foam::readVariable(), Foam::readVerbatim(), token::setBad(), token::setType(), word::valid(), and token::VERBATIM.
read() [2/8]
Foam::Istream & read (char & c) virtual
Implements Istream.
Reimplemented in dummyISstream, and ensightReadFile.
Definition at line 802 of file ISstream.C.
read() [3/8]
Foam::Istream & read (word & str) virtual
Implements Istream.
Reimplemented in dummyISstream, and ensightReadFile.
Definition at line 809 of file ISstream.C.
References token::BEGIN_LIST, token::END_LIST, Foam::endl(), errLen, Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, IOWarningInFunction, Foam::nl, and word::valid().
read() [4/8]
Foam::Istream & read (string & str) virtual
Implements Istream.
Reimplemented in dummyISstream, ensightReadFile, and ensightReadFile.
Definition at line 889 of file ISstream.C.
References token::DQUOTE, errLen, Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, and token::NL.
read() [5/8]
Foam::Istream & read (label & val) virtual
Implements Istream.
Reimplemented in dummyISstream, ensightReadFile, and ensightReadFile.
Definition at line 990 of file ISstream.C.
read() [6/8]
Foam::Istream & read (float & val) virtual
Implements Istream.
Reimplemented in dummyISstream, ensightReadFile, and ensightReadFile.
Definition at line 998 of file ISstream.C.
read() [7/8]
Foam::Istream & read (double & val) virtual
Implements Istream.
Reimplemented in dummyISstream, ensightReadFile, and ensightReadFile.
Definition at line 1006 of file ISstream.C.
read() [8/8]
Foam::Istream & read (char * data, std::streamsize count) virtual
Implements Istream.
Reimplemented in dummyISstream, ensightReadFile, and ensightReadFile.
Definition at line 1014 of file ISstream.C.
readRaw()
Foam::Istream & readRaw (char * data, std::streamsize count) virtual
Implements Istream.
Reimplemented in dummyISstream.
Definition at line 1024 of file ISstream.C.
beginRawRead()
bool beginRawRead () virtual
Implements Istream.
Reimplemented in dummyISstream.
Definition at line 1055 of file ISstream.C.
References Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, and format().
endRawRead()
bool endRawRead () virtual
Implements Istream.
Reimplemented in dummyISstream.
Definition at line 1070 of file ISstream.C.
rewind()
void rewind () virtual
Implements Istream.
Reimplemented in dummyISstream, IFstream, IListStream, and UIListStream.
Definition at line 1078 of file ISstream.C.
References PtrList< T >::clear().
Referenced by IStringStream::reset(), and IFstream::rewind().
print()
void print (Ostream & os) const virtual
Reimplemented from IOstream.
Reimplemented in IFstream, IListStream, UIListStream, and IStringStream.
Definition at line 30 of file SstreamsPrint.C.
References ISstream::name(), os(), and IOstream::print().
Referenced by IFstream::print(), and IStringStream::print().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOstreams/Sstreams/ISstream.H
src/OpenFOAM/db/IOstreams/Sstreams/ISstream.C
src/OpenFOAM/db/IOstreams/Sstreams/ISstreamI.H
src/OpenFOAM/db/IOstreams/Sstreams/SstreamsPrint.C