OpenFOAM: HashSet< Key, Hash > Class Template Reference
HashSet< Key, Hash > Class Template Reference
A HashTable with keys but without contents that is similar to std::unordered_set.
#include <HashSet.H>
Public Types
typedef HashSet< Key, Hash > this_type
typedef HashTable< Foam::zero, Key, Hash > parent_type
using iterator = typename parent_type::key_iterator
using const_iterator = typename parent_type::const_key_iterator
Public Types inherited from HashTable< T, Key, Hash >
typedef HashTable< T, Key, Hash > this_type
typedef std::conditional< std::is_same< Foam::zero, typenamestd::remove_cv< T >::type >::value, Detail::HashTableSingle< Key >, Detail::HashTablePair< Key, T > >::type node_type
typedef Key key_type
typedef T mapped_type
typedef T value_type
typedef Hash hasher
typedef T * pointer
typedef T & reference
typedef const T * const_pointer
typedef const T & const_reference
typedef label difference_type
typedef label size_type
using key_iterator = key_iterator_base< iterator >
using const_key_iterator = key_iterator_base< const_iterator >
Public Member Functions
HashSet ()
HashSet (const this_type &rhs)
HashSet (this_type &&rhs)
HashSet (const label size)
HashSet (Istream &is)
template<unsigned N>
HashSet (const FixedList< Key, N > &list)
HashSet (const UList< Key > &list)
template<class Addr >
HashSet (const IndirectListBase< Key, Addr > &list)
HashSet (std::initializer_list< Key > list)
template<class AnyType , class AnyHash >
HashSet (const HashTable< AnyType, Key, AnyHash > &tbl)
bool test (const Key &key) const
bool insert (const Key &key)
bool set (const Key &key)
bool unset (const Key &key)
void merge (HashSet< Key, Hash > &source)
void merge (HashSet< Key, Hash > &&source)
template<class InputIter >
label insert (InputIter first, InputIter last)
label insert (std::initializer_list< Key > list)
template<unsigned N>
label insert (const FixedList< Key, N > &list)
label insert (const UList< Key > &list)
template<class Addr >
label insert (const IndirectListBase< Key, Addr > &list)
template<class InputIter >
label set (InputIter first, InputIter last)
label set (std::initializer_list< Key > list)
template<unsigned N>
label set (const FixedList< Key, N > &list)
label set (const UList< Key > &list)
template<class Addr >
label set (const IndirectListBase< Key, Addr > &list)
template<class InputIter >
label setMany (InputIter first, InputIter last)
template<class InputIter >
label unset (InputIter first, InputIter last)
label unset (std::initializer_list< Key > list)
template<unsigned N>
label unset (const FixedList< Key, N > &list)
label unset (const UList< Key > &list)
template<class Addr >
label unset (const IndirectListBase< Key, Addr > &list)
iterator begin ()
const_iterator begin () const
const_iterator cbegin () const
iterator end () noexcept
const_iterator end () const noexcept
constexpr const_iterator cend () const noexcept
Ostream & writeList (Ostream &os, const label shortLen=0) const
bool operator() (const Key &key) const noexcept
bool operator[] (const Key &key) const noexcept
void operator= (const this_type &rhs)
void operator= (this_type &&rhs)
bool operator== (const this_type &rhs) const
bool operator!= (const this_type &rhs) const
void operator= (const UList< Key > &rhs)
template<unsigned N>
void operator= (const FixedList< Key, N > &rhs)
void operator= (std::initializer_list< Key > rhs)
this_type & operator|= (const this_type &rhs)
this_type & operator&= (const this_type &rhs)
this_type & operator^= (const this_type &rhs)
this_type & operator+= (const this_type &rhs)
this_type & operator-= (const this_type &rhs)
template<class UnaryPredicate >
List< Key > tocValues (const UnaryPredicate &, const bool)=delete
template<class BinaryPredicate >
List< Key > tocEntries (const BinaryPredicate &, const bool)=delete
template<class UnaryPredicate >
label countValues (const UnaryPredicate &, const bool)=delete
template<class BinaryPredicate >
label countEntries (const BinaryPredicate &, const bool)=delete
template<class UnaryPredicate >
label filterValues (const UnaryPredicate &, const bool)=delete
template<class BinaryPredicate >
label filterEntries (const BinaryPredicate &, const bool)=delete
template<class InputIter >
Foam::label assignMany (const label nItems, InputIter first, InputIter last)
template<class InputIter >
Foam::label insert (InputIter first, InputIter last)
template<unsigned N>
Foam::label insert (const FixedList< Key, N > &list)
template<class Addr >
Foam::label insert (const IndirectListBase< Key, Addr > &list)
template<class InputIter >
Foam::label unset (InputIter first, InputIter last)
template<unsigned N>
Foam::label unset (const FixedList< Key, N > &list)
template<class Addr >
Foam::label unset (const IndirectListBase< Key, Addr > &list)
Public Member Functions inherited from HashTable< T, Key, Hash >
HashTable ()
HashTable (const label size)
HashTable (Istream &is, const label size=128)
HashTable (const this_type &ht)
HashTable (this_type &&rhs)
HashTable (std::initializer_list< std::pair< Key, T > > list)
~HashTable ()
bool empty () const noexcept
label size () const noexcept
label capacity () const noexcept
T & at (const Key &key)
const T & at (const Key &key) const
bool contains (const Key &key) const
iterator find (const Key &key)
const_iterator find (const Key &key) const
const_iterator cfind (const Key &key) const
const T & lookup (const Key &key, const T &deflt) const
List< Key > toc () const
List< Key > sortedToc () const
template<class Compare >
List< Key > sortedToc (const Compare &comp) const
template<class UnaryPredicate >
List< Key > tocKeys (const UnaryPredicate &pred, const bool invert=false) const
template<class UnaryPredicate >
List< Key > tocValues (const UnaryPredicate &pred, const bool invert=false) const
template<class BinaryPredicate >
List< Key > tocEntries (const BinaryPredicate &pred, const bool invert=false) const
UPtrList< const node_type > csorted () const
UPtrList< const node_type > sorted () const
UPtrList< node_type > sorted ()
template<class UnaryPredicate >
label countKeys (const UnaryPredicate &pred, const bool invert=false) const
template<class UnaryPredicate >
label countValues (const UnaryPredicate &pred, const bool invert=false) const
template<class BinaryPredicate >
label countEntries (const BinaryPredicate &pred, const bool invert=false) const
template<class... Args>
bool emplace (const Key &key, Args &&... args)
template<class... Args>
bool emplace_set (const Key &key, Args &&... args)
bool insert (const Key &key, const T &obj)
bool insert (const Key &key, T &&obj)
bool set (const Key &key, const T &obj)
bool set (const Key &key, T &&obj)
bool erase (const iterator &iter)
bool erase (const Key &key)
template<class AnyType , class AnyHash >
label erase (const HashTable< AnyType, Key, AnyHash > &other)
label erase (std::initializer_list< Key > keys)
template<class InputIter >
label erase (InputIter first, InputIter last)
template<unsigned N>
label erase (const FixedList< Key, N > &keys)
label erase (const UList< Key > &keys)
template<class AnyType , class AnyHash >
label retain (const HashTable< AnyType, Key, AnyHash > &other)
template<class UnaryPredicate >
label filterKeys (const UnaryPredicate &pred, const bool pruning=false)
template<class UnaryPredicate >
label filterValues (const UnaryPredicate &pred, const bool pruning=false)
template<class BinaryPredicate >
label filterEntries (const BinaryPredicate &pred, const bool pruning=false)
void resize (const label sz)
void clear ()
void clearStorage ()
void swap (HashTable< T, Key, Hash > &rhs)
void transfer (HashTable< T, Key, Hash > &rhs)
void merge (HashTable< T, Key, Hash > &source)
void merge (HashTable< T, Key, Hash > &&source)
T & operator[] (const Key &key)
const T & operator[] (const Key &key) const
T & operator() (const Key &key)
T & operator() (const Key &key, const T &deflt)
void operator= (const this_type &rhs)
void operator= (std::initializer_list< std::pair< Key, T > > rhs)
void operator= (this_type &&rhs)
bool operator== (const this_type &rhs) const
bool operator!= (const this_type &rhs) const
this_type & operator+= (const this_type &rhs)
const_iterator_pair< const_key_iterator, this_type > keys () const
iterator begin ()
const_iterator begin () const
const_iterator cbegin () const
iterator end () noexcept
const_iterator end () const noexcept
constexpr const_iterator cend () const noexcept
Ostream & printInfo (Ostream &os) const
Ostream & writeKeys (Ostream &os, const label shortLen=0) const
bool found (const Key &key) const
template<class Compare >
Foam::List< Key > sortedToc (const Compare &comp) const
template<class UnaryPredicate >
Foam::List< Key > tocKeys (const UnaryPredicate &pred, const bool invert) const
template<class UnaryPredicate >
Foam::List< Key > tocValues (const UnaryPredicate &pred, const bool invert) const
template<class BinaryPredicate >
Foam::List< Key > tocEntries (const BinaryPredicate &pred, const bool invert) const
template<class UnaryPredicate >
Foam::label countKeys (const UnaryPredicate &pred, const bool invert) const
template<class UnaryPredicate >
Foam::label countValues (const UnaryPredicate &pred, const bool invert) const
template<class BinaryPredicate >
Foam::label countEntries (const BinaryPredicate &pred, const bool invert) const
template<class InputIter >
Foam::label erase (InputIter first, InputIter last)
template<unsigned N>
Foam::label erase (const FixedList< Key, N > &keys)
template<class AnyType , class AnyHash >
Foam::label erase (const HashTable< AnyType, Key, AnyHash > &other)
template<class AnyType , class AnyHash >
Foam::label retain (const HashTable< AnyType, Key, AnyHash > &other)
template<class UnaryPredicate >
Foam::label filterKeys (const UnaryPredicate &pred, const bool pruning)
template<class UnaryPredicate >
Foam::label filterValues (const UnaryPredicate &pred, const bool pruning)
template<class BinaryPredicate >
Foam::label filterEntries (const BinaryPredicate &pred, const bool pruning)
Public Member Functions inherited from HashTableCore
ClassName ("HashTable")
HashTableCore () noexcept=default
Additional Inherited Members
Static Public Member Functions inherited from HashTableCore
static label canonicalSize (const label requested_size)
Static Public Attributes inherited from HashTableCore
static const label maxTableSize
Detailed Description
template<class Key, class Hash = Foam::Hash<Key>>
class Foam::HashSet< Key, Hash >
A HashTable with keys but without contents that is similar to std::unordered_set.
The entries are considered unordered since their placement depends on the method used to generate the hash key index, the table capacity, insertion order etc. When the key order is important, use the sortedToc() method to obtain a list of sorted keys and use that for further access.
Note
The HashSet iterator dereferences to the key, so the following range-for works as expected:
labelHashSet someLabels{10, 20, 30, 40, ...};
for (const label i : someLabels)
{
    Info<< "val:" << i << nl;
}
Definition at line 93 of file HashSet.H.
Member Typedef Documentation
this_type
template<class Key , class Hash = Foam::Hash<Key>> typedef HashSet<Key, Hash> this_type
Definition at line 112 of file HashSet.H.
parent_type
template<class Key , class Hash = Foam::Hash<Key>> typedef HashTable<Foam::zero, Key, Hash> parent_type
Definition at line 115 of file HashSet.H.
iterator
template<class Key , class Hash = Foam::Hash<Key>> using iterator = typename parent_type::key_iterator
Definition at line 118 of file HashSet.H.
const_iterator
template<class Key , class Hash = Foam::Hash<Key>> using const_iterator = typename parent_type::const_key_iterator
Definition at line 121 of file HashSet.H.
Constructor & Destructor Documentation
HashSet() [1/10]
template<class Key , class Hash = Foam::Hash<Key>> HashSet () inline
Definition at line 127 of file HashSet.H.
HashSet() [2/10]
template<class Key , class Hash = Foam::Hash<Key>> HashSet (const this_type & rhs) inline
Definition at line 133 of file HashSet.H.
HashSet() [3/10]
template<class Key , class Hash = Foam::Hash<Key>> HashSet (this_type && rhs) inline
Definition at line 139 of file HashSet.H.
HashSet() [4/10]
template<class Key , class Hash = Foam::Hash<Key>> HashSet (const label size) inline explicit
Definition at line 145 of file HashSet.H.
HashSet() [5/10]
template<class Key , class Hash = Foam::Hash<Key>> HashSet (Istream & is) inline explicit
Definition at line 151 of file HashSet.H.
HashSet() [6/10]
template<class Key , class Hash > template<unsigned N> HashSet (const FixedList< Key, N > & list) explicit
Definition at line 57 of file HashSet.C.
References UPtrList< T >::begin(), UPtrList< T >::end(), and insert().
HashSet() [7/10]
template<class Key , class Hash > HashSet (const UList< Key > & list) explicit
Definition at line 66 of file HashSet.C.
References UPtrList< T >::begin(), UPtrList< T >::end(), and insert().
HashSet() [8/10]
template<class Key , class Hash > template<class Addr > HashSet (const IndirectListBase< Key, Addr > & list) explicit
Definition at line 76 of file HashSet.C.
References UPtrList< T >::begin(), UPtrList< T >::end(), and insert().
HashSet() [9/10]
template<class Key , class Hash > HashSet (std::initializer_list< Key > list)
Definition at line 85 of file HashSet.C.
References insert().
HashSet() [10/10]
template<class Key , class Hash > template<class AnyType , class AnyHash > HashSet (const HashTable< AnyType, Key, AnyHash > & tbl) explicit
Definition at line 95 of file HashSet.C.
References UPtrList< T >::cbegin(), UPtrList< T >::cend(), and insert().
Member Function Documentation
test()
template<class Key , class Hash = Foam::Hash<Key>> bool test (const Key & key) const inline
Definition at line 180 of file HashSet.H.
References HashTable< T, Key, Hash >::contains().
Referenced by mappedPatchBase::calcMapping().
insert() [1/9]
template<class Key , class Hash = Foam::Hash<Key>> bool insert (const Key & key) inline
Definition at line 191 of file HashSet.H.
References PtrList< T >::emplace().
Referenced by primitiveMeshGeometry::affectedCells(), polyMeshGeometry::affectedCells(), decompositionMethod::calcCellCells(), decompositionMethod::calcCellCells(), cellFeatures::cellFeatures(), cellVolumeWeight::cellVolumeWeight(), primitiveMesh::checkFaceVertices(), PrimitivePatch< FaceList, PointField >::checkPointManifold(), PrimitivePatch< FaceList, PointField >::checkTopology(), inverseFaceDistanceDiffusivity::correct(), combineFaces::getMergeSets(), surfaceSets::getSurfaceSets(), viewFactor::initialise(), inverseDistance::inverseDistance(), meshRefinement::mergePatchFaces(), meshRefinement::mergePatchFacesUndo(), faceAreaWeightAMI2D::overlappingTgtFaces(), cellSetOption::setCellSelection(), hexRef8::setRefinement(), PrimitivePatch< FaceList, PointField >::surfaceType(), faGlobalMeshData::updateMesh(), Foam::HashSetOps::used(), and Foam::HashSetOps::used().
set() [1/6]
template<class Key , class Hash = Foam::Hash<Key>> bool set (const Key & key) inline
Definition at line 197 of file HashSet.H.
References PtrList< T >::emplace().
Referenced by mappedPatchBase::calcMapping(), pointSet::distribute(), cellSet::distribute(), faceSet::distribute(), topoSet::set(), topoSet::set(), faceSet::sync(), and pointSet::sync().
unset() [1/9]
template<class Key , class Hash = Foam::Hash<Key>> bool unset (const Key & key) inline
Definition at line 204 of file HashSet.H.
Referenced by turbulenceFields::initialise(), topoSet::unset(), and topoSet::unset().
merge() [1/2]
template<class Key , class Hash > void merge (HashSet< Key, Hash > & source)
Definition at line 229 of file HashSet.C.
merge() [2/2]
template<class Key , class Hash > void merge (HashSet< Key, Hash > && source)
Definition at line 236 of file HashSet.C.
insert() [2/9]
template<class Key , class Hash = Foam::Hash<Key>> template<class InputIter > label insert (InputIter first, InputIter last) inline
insert() [3/9]
template<class Key , class Hash > Foam::label insert (std::initializer_list< Key > list) inline
Definition at line 133 of file HashSet.C.
References insert().
insert() [4/9]
template<class Key , class Hash = Foam::Hash<Key>> template<unsigned N> label insert (const FixedList< Key, N > & list) inline
insert() [5/9]
template<class Key , class Hash > Foam::label insert (const UList< Key > & list) inline
Definition at line 154 of file HashSet.C.
insert() [6/9]
template<class Key , class Hash = Foam::Hash<Key>> template<class Addr > label insert (const IndirectListBase< Key, Addr > & list) inline
set() [2/6]
template<class Key , class Hash = Foam::Hash<Key>> template<class InputIter > label set (InputIter first, InputIter last) inline
Definition at line 247 of file HashSet.H.
References insert().
set() [3/6]
template<class Key , class Hash = Foam::Hash<Key>> label set (std::initializer_list< Key > list) inline
Definition at line 253 of file HashSet.H.
References insert().
set() [4/6]
template<class Key , class Hash = Foam::Hash<Key>> template<unsigned N> label set (const FixedList< Key, N > & list) inline
Definition at line 260 of file HashSet.H.
References insert().
set() [5/6]
template<class Key , class Hash = Foam::Hash<Key>> label set (const UList< Key > & list) inline
Definition at line 266 of file HashSet.H.
References insert().
set() [6/6]
template<class Key , class Hash = Foam::Hash<Key>> template<class Addr > label set (const IndirectListBase< Key, Addr > & list) inline
Definition at line 273 of file HashSet.H.
References insert().
setMany()
template<class Key , class Hash = Foam::Hash<Key>> template<class InputIter > label setMany (InputIter first, InputIter last) inline
Definition at line 281 of file HashSet.H.
References insert().
unset() [2/9]
template<class Key , class Hash = Foam::Hash<Key>> template<class InputIter > label unset (InputIter first, InputIter last) inline
unset() [3/9]
template<class Key , class Hash > Foam::label unset (std::initializer_list< Key > list) inline
Definition at line 187 of file HashSet.C.
unset() [4/9]
template<class Key , class Hash = Foam::Hash<Key>> template<unsigned N> label unset (const FixedList< Key, N > & list) inline
unset() [5/9]
template<class Key , class Hash > Foam::label unset (const UList< Key > & list) inline
Definition at line 208 of file HashSet.C.
unset() [6/9]
template<class Key , class Hash = Foam::Hash<Key>> template<class Addr > label unset (const IndirectListBase< Key, Addr > & list) inline
begin() [1/2]
template<class Key , class Hash > Foam::HashSet< Key, Hash >::iterator begin () inline
Definition at line 453 of file HashSet.C.
References UPtrList< T >::begin().
begin() [2/2]
template<class Key , class Hash > Foam::HashSet< Key, Hash >::const_iterator begin () const inline
Definition at line 464 of file HashSet.C.
References UPtrList< T >::begin().
cbegin()
template<class Key , class Hash > Foam::HashSet< Key, Hash >::const_iterator cbegin () const inline
Definition at line 475 of file HashSet.C.
References UPtrList< T >::cbegin().
end() [1/2]
template<class Key , class Hash > Foam::HashSet< Key, Hash >::iterator end () inline noexcept
Definition at line 486 of file HashSet.C.
end() [2/2]
template<class Key , class Hash > Foam::HashSet< Key, Hash >::const_iterator end () const inline noexcept
Definition at line 494 of file HashSet.C.
cend()
template<class Key , class Hash > constexpr Foam::HashSet< Key, Hash >::const_iterator cend () const inline constexpr noexcept
Definition at line 502 of file HashSet.C.
writeList()
template<class Key , class Hash = Foam::Hash<Key>> Ostream & writeList (Ostream & os, const label shortLen = 0) const inline
Definition at line 326 of file HashSet.H.
References HashTable< T, Key, Hash >::writeKeys().
operator()()
template<class Key , class Hash > bool operator() (const Key & key) const inline noexcept
Definition at line 245 of file HashSet.C.
operator[]()
template<class Key , class Hash > bool operator[] (const Key & key) const inline noexcept
Definition at line 252 of file HashSet.C.
operator=() [1/5]
template<class Key , class Hash = Foam::Hash<Key>> void operator= (const this_type & rhs) inline
Definition at line 342 of file HashSet.H.
References PtrList< T >::operator=().
operator=() [2/5]
template<class Key , class Hash = Foam::Hash<Key>> void operator= (this_type && rhs) inline
Definition at line 348 of file HashSet.H.
References PtrList< T >::operator=().
operator==()
template<class Key , class Hash = Foam::Hash<Key>> bool operator== (const this_type & rhs) const
Definition at line 281 of file HashSet.C.
References UPtrList< T >::cbegin(), UPtrList< T >::cend(), and UPtrList< T >::size().
operator!=()
template<class Key , class Hash = Foam::Hash<Key>> bool operator!= (const this_type & rhs) const
Definition at line 302 of file HashSet.C.
References Foam::operator==().
operator=() [3/5]
template<class Key , class Hash > void operator= (const UList< Key > & rhs)
Definition at line 267 of file HashSet.C.
References UPtrList< T >::begin(), UPtrList< T >::end(), and UPtrList< T >::size().
operator=() [4/5]
template<class Key , class Hash > template<unsigned N> void operator= (const FixedList< Key, N > & rhs)
Definition at line 260 of file HashSet.C.
References UPtrList< T >::begin(), UPtrList< T >::end(), and UPtrList< T >::size().
operator=() [5/5]
template<class Key , class Hash > void operator= (std::initializer_list< Key > rhs)
Definition at line 274 of file HashSet.C.
operator|=()
template<class Key , class Hash = Foam::Hash<Key>> Foam::HashSet< Key, Hash > & operator|= (const this_type & rhs)
Definition at line 310 of file HashSet.C.
operator&=()
template<class Key , class Hash = Foam::Hash<Key>> Foam::HashSet< Key, Hash > & operator&= (const this_type & rhs) inline
Definition at line 324 of file HashSet.C.
operator^=()
template<class Key , class Hash = Foam::Hash<Key>> Foam::HashSet< Key, Hash > & operator^= (const this_type & rhs)
Definition at line 333 of file HashSet.C.
operator+=()
template<class Key , class Hash = Foam::Hash<Key>> Foam::HashSet< Key, Hash > & operator+= (const this_type & rhs) inline
Definition at line 354 of file HashSet.C.
operator-=()
template<class Key , class Hash = Foam::Hash<Key>> Foam::HashSet< Key, Hash > & operator-= (const this_type & rhs) inline
Definition at line 362 of file HashSet.C.
tocValues()
template<class Key , class Hash = Foam::Hash<Key>> template<class UnaryPredicate > List< Key > tocValues (const UnaryPredicate & , const bool) delete
tocEntries()
template<class Key , class Hash = Foam::Hash<Key>> template<class BinaryPredicate > List< Key > tocEntries (const BinaryPredicate & , const bool) delete
countValues()
template<class Key , class Hash = Foam::Hash<Key>> template<class UnaryPredicate > label countValues (const UnaryPredicate & , const bool) delete
countEntries()
template<class Key , class Hash = Foam::Hash<Key>> template<class BinaryPredicate > label countEntries (const BinaryPredicate & , const bool) delete
filterValues()
template<class Key , class Hash = Foam::Hash<Key>> template<class UnaryPredicate > label filterValues (const UnaryPredicate & , const bool) delete
filterEntries()
template<class Key , class Hash = Foam::Hash<Key>> template<class BinaryPredicate > label filterEntries (const BinaryPredicate & , const bool) delete
assignMany()
template<class Key , class Hash = Foam::Hash<Key>> template<class InputIter > Foam::label assignMany (const label nItems, InputIter first, InputIter last) inline
Definition at line 32 of file HashSet.C.
References PtrList< T >::clear(), insert(), UPtrList< T >::last(), and PtrList< T >::resize().
insert() [7/9]
template<class Key , class Hash = Foam::Hash<Key>> template<class InputIter > Foam::label insert (InputIter first, InputIter last) inline
Definition at line 113 of file HashSet.C.
References insert().
insert() [8/9]
template<class Key , class Hash = Foam::Hash<Key>> template<unsigned N> Foam::label insert (const FixedList< Key, N > & list) inline
Definition at line 144 of file HashSet.C.
References UPtrList< T >::begin(), UPtrList< T >::end(), and insert().
insert() [9/9]
template<class Key , class Hash = Foam::Hash<Key>> template<class Addr > Foam::label insert (const IndirectListBase< Key, Addr > & list) inline
Definition at line 165 of file HashSet.C.
unset() [7/9]
template<class Key , class Hash = Foam::Hash<Key>> template<class InputIter > Foam::label unset (InputIter first, InputIter last) inline
Definition at line 176 of file HashSet.C.
unset() [8/9]
template<class Key , class Hash = Foam::Hash<Key>> template<unsigned N> Foam::label unset (const FixedList< Key, N > & list) inline
Definition at line 198 of file HashSet.C.
References UPtrList< T >::begin(), and UPtrList< T >::end().
unset() [9/9]
template<class Key , class Hash = Foam::Hash<Key>> template<class Addr > Foam::label unset (const IndirectListBase< Key, Addr > & list) inline
Definition at line 219 of file HashSet.C.
References UPtrList< T >::begin(), and UPtrList< T >::end().
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/HashTables/HashSet/HashSet.H
src/OpenFOAM/containers/HashTables/HashSet/HashSet.C