OpenFOAM: namedDictionary Class Reference
namedDictionary Class Reference
A tuple of keyType and dictionary, which can be used when reading named or unnamed dictionary entries or simply a name.
#include <namedDictionary.H>
Public Member Functions
namedDictionary ()=default
namedDictionary (Istream &is)
~namedDictionary ()=default
void clear ()
bool empty () const noexcept
const keyType & keyword () const noexcept
keyType & keyword () noexcept
const dictionary & dict () const noexcept
dictionary & dict () noexcept
Public Member Functions inherited from Tuple2< keyType, dictionary >
Tuple2 ()=default
Tuple2 (const keyType &f, const dictionary &s)
Tuple2 (keyType &&f, dictionary &&s)
Tuple2 (const std::pair< keyType, dictionary > &vals)
Tuple2 (std::pair< keyType, dictionary > &&vals)
Tuple2 (Istream &is)
const keyType & first () const noexcept
keyType & first () noexcept
const dictionary & second () const noexcept
dictionary & second () noexcept
Friends
Istream & operator>> (Istream &, namedDictionary &)
Ostream & operator<< (Ostream &, const namedDictionary &)
Additional Inherited Members
Public Types inherited from Tuple2< keyType, dictionary >
typedef keyType first_type
typedef dictionary second_type
Detailed Description
A tuple of keyType and dictionary, which can be used when reading named or unnamed dictionary entries or simply a name.
For example,
fields
(
    U
    T { relax  false; }
);
In can also be used in situations where an individual dictionary entry should be read.
actions
(
    testing { action new; ... }   // An action with a name
    { action subset;  }           // Unnamed action
);
Normal dictionary reading would fail for this type of input since the leading 'testing' keyword would cause the entire content to be considered a single dictionary.
Note
No distinction currently made between a missing and an empty dictionary.
Source files
namedDictionary.H
namedDictionary.C
Definition at line 80 of file namedDictionary.H.
Constructor & Destructor Documentation
namedDictionary() [1/2]
namedDictionary () default
namedDictionary() [2/2]
namedDictionary (Istream & is) explicit
Definition at line 26 of file namedDictionary.C.
~namedDictionary()
~namedDictionary () default
Member Function Documentation
clear()
void clear ()
Definition at line 34 of file namedDictionary.C.
References PtrList< T >::clear().
empty()
bool empty () const noexcept
Definition at line 41 of file namedDictionary.C.
keyword() [1/2]
const keyType & keyword () const inline noexcept
Definition at line 111 of file namedDictionary.H.
References Tuple2< keyType, dictionary >::first().
keyword() [2/2]
keyType & keyword () inline noexcept
Definition at line 117 of file namedDictionary.H.
References Tuple2< keyType, dictionary >::first().
dict() [1/2]
const dictionary & dict () const inline noexcept
Definition at line 123 of file namedDictionary.H.
References Tuple2< keyType, dictionary >::second().
dict() [2/2]
dictionary & dict () inline noexcept
Definition at line 129 of file namedDictionary.H.
References Tuple2< keyType, dictionary >::second().
Friends And Related Symbol Documentation
operator>>
Istream & operator>> (Istream & , namedDictionary &) friend
operator<<
Ostream & operator<< (Ostream & , const namedDictionary &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/db/dictionary/namedDictionary/namedDictionary.H
src/OpenFOAM/db/dictionary/namedDictionary/namedDictionary.C