OpenFOAM: globalIndexAndTransform Class Reference
globalIndexAndTransform Class Reference
Determination and storage of the possible independent transforms introduced by coupledPolyPatches, as well as all of the possible permutations of these transforms generated by the presence of multiple coupledPolyPatches, i.e. more than one cyclic boundary. Note that any given point can be on maximum 3 transforms only (and these transforms have to be perpendicular)
#include <globalIndexAndTransform.H>
Classes
class less
Public Member Functions
ClassName ("globalIndexAndTransform")
globalIndexAndTransform (const polyMesh &mesh)
label encodeTransformIndex (const labelList &permutationIndices) const
labelList decodeTransformIndex (const label transformIndex) const
label addToTransformIndex (const label transformIndex, const label patchi, const bool isSendingSide=true, const scalar tol=SMALL) const
label mergeTransformIndex (const label transformIndex0, const label transformIndex1) const
label minimumTransformIndex (const label transformIndex0, const label transformIndex1) const
label subtractTransformIndex (const label transformIndex0, const label transformIndex1) const
labelPair encode (const label index, const label transformIndex) const
labelPair encode (const label proci, const label index, const label transformIndex) const
label index (const labelPair &globalIAndTransform) const
label processor (const labelPair &globalIAndTransform) const
label transformIndex (const labelPair &globalIAndTransform) const
label nIndependentTransforms () const
const List< vectorTensorTransform > & transforms () const
const List< vectorTensorTransform > & transformPermutations () const
label nullTransformIndex () const
const List< labelPair > & patchTransformSign () const
const vectorTensorTransform & transform (label transformIndex) const
labelList transformIndicesForPatches (const labelHashSet &patchIs) const
pointField transformPatches (const labelHashSet &patchIs, const point &pt) const
Detailed Description
Determination and storage of the possible independent transforms introduced by coupledPolyPatches, as well as all of the possible permutations of these transforms generated by the presence of multiple coupledPolyPatches, i.e. more than one cyclic boundary. Note that any given point can be on maximum 3 transforms only (and these transforms have to be perpendicular)
Also provides global index encoding and decoding for entity (i.e. cell) index, processor index and transform index (0 or positive integer) to a labelPair.
Source files
globalIndexAndTransform.H
globalIndexAndTransform.C
Definition at line 60 of file globalIndexAndTransform.H.
Constructor & Destructor Documentation
globalIndexAndTransform()
globalIndexAndTransform (const polyMesh & mesh)
Definition at line 449 of file globalIndexAndTransform.C.
References PtrList< T >::append(), Foam::endl(), UPtrList< T >::first(), forAll, Foam::Info, globalIndexAndTransform::nullTransformIndex(), patches, pp(), and UPtrList< T >::size().
Member Function Documentation
ClassName()
ClassName ("globalIndexAndTransform")
encodeTransformIndex()
Foam::label encodeTransformIndex (const labelList & permutationIndices) const inline
Definition at line 69 of file globalIndexAndTransformI.H.
References Foam::abort(), b, Foam::FatalError, FatalErrorInFunction, forAll, Foam::mag(), UPtrList< T >::size(), and globalIndexAndTransform::transformIndex().
decodeTransformIndex()
Foam::labelList decodeTransformIndex (const label transformIndex) const inline
Definition at line 105 of file globalIndexAndTransformI.H.
References forAll, and Foam::Zero.
addToTransformIndex()
Foam::label addToTransformIndex (const label transformIndex, const label patchi, const bool isSendingSide = true, const scalar tol = SMALL) const inline
Definition at line 123 of file globalIndexAndTransformI.H.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, UPtrList< T >::first(), Foam::labelMin, Foam::mag(), IOstream::name(), R, Foam::sign(), UPtrList< T >::size(), and Foam::tr().
mergeTransformIndex()
label mergeTransformIndex (const label transformIndex0, const label transformIndex1) const inline
minimumTransformIndex()
Foam::label minimumTransformIndex (const label transformIndex0, const label transformIndex1) const inline
Definition at line 234 of file globalIndexAndTransformI.H.
References forAll.
subtractTransformIndex()
Foam::label subtractTransformIndex (const label transformIndex0, const label transformIndex1) const inline
Definition at line 278 of file globalIndexAndTransformI.H.
References forAll.
encode() [1/2]
Foam::labelPair encode (const label index, const label transformIndex) const inline
Definition at line 296 of file globalIndexAndTransformI.H.
References UPstream::myProcNo().
encode() [2/2]
Foam::labelPair encode (const label proci, const label index, const label transformIndex) const inline
Definition at line 306 of file globalIndexAndTransformI.H.
References Foam::abort(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::labelMax, and UPtrList< T >::size().
index()
Foam::label index (const labelPair & globalIAndTransform) const inline
Definition at line 340 of file globalIndexAndTransformI.H.
References UPtrList< T >::first().
Referenced by mapDistribute::mapDistribute(), and mapDistribute::mapDistribute().
processor()
Foam::label processor (const labelPair & globalIAndTransform) const inline
Definition at line 349 of file globalIndexAndTransformI.H.
References UPtrList< T >::size().
Referenced by mapDistribute::mapDistribute(), and mapDistribute::mapDistribute().
transformIndex()
Foam::label transformIndex (const labelPair & globalIAndTransform) const inline
Definition at line 358 of file globalIndexAndTransformI.H.
References UPtrList< T >::size().
Referenced by globalIndexAndTransform::encodeTransformIndex(), mapDistribute::mapDistribute(), and mapDistribute::mapDistribute().
nIndependentTransforms()
Foam::label nIndependentTransforms () const inline
Definition at line 367 of file globalIndexAndTransformI.H.
References UPtrList< T >::size().
transforms()
const Foam::List< Foam::vectorTensorTransform > & transforms () const inline
Definition at line 374 of file globalIndexAndTransformI.H.
transformPermutations()
const Foam::List< Foam::vectorTensorTransform > & transformPermutations () const inline
Definition at line 381 of file globalIndexAndTransformI.H.
Referenced by mapDistribute::mapDistribute(), and mapDistribute::mapDistribute().
nullTransformIndex()
Foam::label nullTransformIndex () const inline
Definition at line 387 of file globalIndexAndTransformI.H.
Referenced by globalIndexAndTransform::globalIndexAndTransform().
patchTransformSign()
const Foam::labelPairList & patchTransformSign () const inline
Definition at line 394 of file globalIndexAndTransformI.H.
transform()
const Foam::vectorTensorTransform & transform (label transformIndex) const inline
Definition at line 400 of file globalIndexAndTransformI.H.
transformIndicesForPatches()
Foam::labelList transformIndicesForPatches (const labelHashSet & patchIs) const inline
Definition at line 409 of file globalIndexAndTransformI.H.
References b, UPtrList< T >::empty(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, UPtrList< T >::first(), Foam::mag(), Foam::pow(), PtrList< T >::setSize(), Foam::sign(), Foam::sum(), and Foam::Zero.
transformPatches()
Foam::pointField transformPatches (const labelHashSet & patchIs, const point & pt) const inline
Definition at line 582 of file globalIndexAndTransformI.H.
References forAll, and UPtrList< T >::size().
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/globalIndexAndTransform/globalIndexAndTransform.H
src/OpenFOAM/primitives/globalIndexAndTransform/globalIndexAndTransform.C
src/OpenFOAM/primitives/globalIndexAndTransform/globalIndexAndTransformI.H