OpenFOAM: ignition Class Reference
ignition Class Reference
Foam::ignition.
#include <ignition.H>
Public Member Functions
ignition (const dictionary &, const Time &, const fvMesh &)
ignition (const dictionary &, const engineTime &, const fvMesh &)
const PtrList< ignitionSite > & sites ()
bool ignite () const
bool igniting () const
bool ignited () const
Detailed Description
Foam::ignition.
Source files
ignition.H
ignition.C
ignitionIO.C
Definition at line 51 of file ignition.H.
Constructor & Destructor Documentation
ignition() [1/2]
ignition (const dictionary & combustionProperties, const Time & db, const fvMesh & mesh)
Definition at line 27 of file ignitionIO.C.
References Foam::endl(), and Foam::Info.
ignition() [2/2]
ignition (const dictionary & combustionProperties, const engineTime & edb, const fvMesh & mesh)
Definition at line 53 of file ignitionIO.C.
References Foam::endl(), and Foam::Info.
Member Function Documentation
sites()
const PtrList< ignitionSite > & sites () inline
Definition at line 85 of file ignition.H.
ignite()
bool ignite () const inline
Definition at line 93 of file ignition.H.
Referenced by ignition::igniting().
igniting()
bool igniting () const
Definition at line 27 of file ignition.C.
References forAll, ignition::ignite(), and ignition::igniting().
Referenced by ignition::igniting().
ignited()
bool ignited () const
Definition at line 48 of file ignition.C.
References forAll.
The documentation for this class was generated from the following files:
src/engine/ignition/ignition.H
src/engine/ignition/ignition.C
src/engine/ignition/ignitionIO.C