OpenFOAM: meshCutAndRemove Class Reference
meshCutAndRemove Class Reference
Like meshCutter but also removes non-anchor side of cell.
#include <meshCutAndRemove.H>
Public Member Functions
ClassName ("meshCutAndRemove")
meshCutAndRemove (const polyMesh &mesh)
void setRefinement (const label exposedPatchi, const cellCuts &cuts, const labelList &cutPatch, polyTopoChange &meshMod)
void updateMesh (const mapPolyMesh &)
const Map< label > & addedFaces () const
const EdgeMap< label > & addedPoints () const
Public Member Functions inherited from edgeVertex
edgeVertex (const polyMesh &mesh)
const polyMesh & mesh () const
bool isEdge (const label eVert) const
label getEdge (const label eVert) const
label getVertex (const label eVert) const
label vertToEVert (const label vertI) const
label edgeToEVert (const label edgeI) const
point coord (const label cut, const scalar weight) const
label cutPairToEdge (const label cut0, const label cut1) const
Ostream & writeCut (Ostream &os, const label cut, const scalar) const
Ostream & writeCuts (Ostream &os, const labelList &, const scalarField &) const
Additional Inherited Members
Static Public Member Functions inherited from edgeVertex
static void updateLabels (const labelList &map, List< refineCell > &)
static void updateLabels (const labelList &map, Map< label > &)
static void updateLabels (const labelList &map, labelHashSet &)
static bool isEdge (const primitiveMesh &mesh, const label eVert)
static label getEdge (const primitiveMesh &mesh, const label eVert)
static label getVertex (const primitiveMesh &mesh, const label eVert)
static label vertToEVert (const primitiveMesh &mesh, const label vertI)
static label edgeToEVert (const primitiveMesh &mesh, const label edgeI)
static point coord (const primitiveMesh &, const label cut, const scalar weight)
static label cutPairToEdge (const primitiveMesh &, const label cut0, const label cut1)
Detailed Description
Like meshCutter but also removes non-anchor side of cell.
Source files
meshCutAndRemove.H
meshCutAndRemove.C
Definition at line 60 of file meshCutAndRemove.H.
Constructor & Destructor Documentation
meshCutAndRemove()
meshCutAndRemove (const polyMesh & mesh) explicit
Definition at line 559 of file meshCutAndRemove.C.
Member Function Documentation
ClassName()
ClassName ("meshCutAndRemove")
setRefinement()
void setRefinement (const label exposedPatchi, const cellCuts & cuts, const labelList & cutPatch, polyTopoChange & meshMod)
Definition at line 569 of file meshCutAndRemove.C.
References Foam::abort(), polyMesh::boundaryMesh(), primitiveMesh::cellPoints(), PtrList< T >::clear(), e, primitiveMesh::edgeFaces(), primitiveMesh::edges(), UList< T >::end(), Foam::endl(), f(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), polyMesh::faces(), Foam::FatalError, FatalErrorInFunction, forAll, forAllConstIters, Foam::getEdge(), mesh, Foam::nl, nPoints, patches, patchID, polyMesh::points(), Foam::Pout, PtrList< T >::resize(), Foam::reverse(), polyTopoChange::setAction(), UPtrList< T >::size(), and UList< T >::size().
updateMesh()
void updateMesh (const mapPolyMesh & map)
Definition at line 1262 of file meshCutAndRemove.C.
References e, UList< T >::end(), Foam::endl(), forAllConstIters, Foam::Pout, mapPolyMesh::reverseCellMap(), mapPolyMesh::reverseFaceMap(), mapPolyMesh::reversePointMap(), and PtrList< T >::transfer().
addedFaces()
const Map< label > & addedFaces () const inline
Definition at line 219 of file meshCutAndRemove.H.
addedPoints()
const EdgeMap< label > & addedPoints () const inline
Definition at line 227 of file meshCutAndRemove.H.
The documentation for this class was generated from the following files:
src/dynamicMesh/meshCut/meshModifiers/meshCutAndRemove/meshCutAndRemove.H
src/dynamicMesh/meshCut/meshModifiers/meshCutAndRemove/meshCutAndRemove.C