OpenFOAM: adjointFarFieldPressureFvPatchScalarField Class Reference
adjointFarFieldPressureFvPatchScalarField Class Reference
#include <adjointFarFieldPressureFvPatchScalarField.H>
Public Member Functions
TypeName ("adjointFarFieldPressure")
adjointFarFieldPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
adjointFarFieldPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
adjointFarFieldPressureFvPatchScalarField (const adjointFarFieldPressureFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
virtual tmp< fvPatchScalarField > clone () const
adjointFarFieldPressureFvPatchScalarField (const adjointFarFieldPressureFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual tmp< Field< scalar > > snGrad () const
virtual tmp< Field< scalar > > valueInternalCoeffs (const tmp< scalarField > &) const
virtual tmp< Field< scalar > > valueBoundaryCoeffs (const tmp< scalarField > &) const
virtual tmp< Field< scalar > > gradientInternalCoeffs () const
virtual tmp< Field< scalar > > gradientBoundaryCoeffs () const
virtual void updateCoeffs ()
virtual void write (Ostream &) const
virtual void operator= (const UList< scalar > &)
virtual void operator= (const fvPatchField< scalar > &)
virtual void operator+= (const fvPatchField< scalar > &)
virtual void operator-= (const fvPatchField< scalar > &)
virtual void operator*= (const fvPatchField< scalar > &)
virtual void operator/= (const fvPatchField< scalar > &)
virtual void operator+= (const Field< scalar > &)
virtual void operator-= (const Field< scalar > &)
virtual void operator*= (const Field< scalar > &)
virtual void operator/= (const Field< scalar > &)
virtual void operator= (const scalar)
virtual void operator+= (const scalar)
virtual void operator-= (const scalar)
virtual void operator*= (const scalar)
virtual void operator/= (const scalar)
Public Member Functions inherited from adjointBoundaryCondition< Type >
TypeName ("adjointBoundaryCondition")
adjointBoundaryCondition (const fvPatch &p, const DimensionedField< Type, volMesh > &iF, const word &solverName)
adjointBoundaryCondition (const adjointBoundaryCondition< Type > &)
virtual ~adjointBoundaryCondition ()=default
const word & objectiveManagerName () const
const word & adjointSolverName () const
const word & simulationType () const
void setBoundaryContributionPtr ()
boundaryAdjointContribution & getBoundaryAdjContribution ()
const ATCModel & getATC () const
virtual tmp< Field< typename Foam::outerProduct< Foam::vector, Type >::type > > dxdbMult () const
virtual void updatePrimalBasedQuantities ()
Additional Inherited Members
Protected Member Functions inherited from adjointBoundaryCondition< Type >
template<class Type2 >
tmp< Field< typename Foam::outerProduct< Foam::vector, Type2 >::type > > computePatchGrad (word name)
bool addATCUaGradUTerm ()
Protected Attributes inherited from adjointBoundaryCondition< Type >
const fvPatch & patch_
word managerName_
word adjointSolverName_
word simulationType_
autoPtr< boundaryAdjointContribution > boundaryContrPtr_
Switch addATCUaGradUTerm_
Detailed Description
Source files
adjointFarFieldPressureFvPatchScalarField.H
adjointFarFieldPressureFvPatchScalarField.C
Definition at line 50 of file adjointFarFieldPressureFvPatchScalarField.H.
Constructor & Destructor Documentation
adjointFarFieldPressureFvPatchScalarField() [1/4]
adjointFarFieldPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 32 of file adjointFarFieldPressureFvPatchScalarField.C.
adjointFarFieldPressureFvPatchScalarField() [2/4]
adjointFarFieldPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 58 of file adjointFarFieldPressureFvPatchScalarField.C.
References dict, and IOobjectOption::MUST_READ.
adjointFarFieldPressureFvPatchScalarField() [3/4]
adjointFarFieldPressureFvPatchScalarField (const adjointFarFieldPressureFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 44 of file adjointFarFieldPressureFvPatchScalarField.C.
adjointFarFieldPressureFvPatchScalarField() [4/4]
adjointFarFieldPressureFvPatchScalarField (const adjointFarFieldPressureFvPatchScalarField & tppsf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 73 of file adjointFarFieldPressureFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("adjointFarFieldPressure")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 89 of file adjointFarFieldPressureFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 105 of file adjointFarFieldPressureFvPatchScalarField.H.
snGrad()
Foam::tmp< Foam::Field< Foam::scalar > > snGrad () const virtual
Definition at line 161 of file adjointFarFieldPressureFvPatchScalarField.C.
References Foam::pos().
valueInternalCoeffs()
Foam::tmp< Foam::Field< Foam::scalar > > valueInternalCoeffs (const tmp< scalarField > &) const virtual
Definition at line 176 of file adjointFarFieldPressureFvPatchScalarField.C.
References Foam::neg().
valueBoundaryCoeffs()
Foam::tmp< Foam::Field< Foam::scalar > > valueBoundaryCoeffs (const tmp< scalarField > &) const virtual
Definition at line 194 of file adjointFarFieldPressureFvPatchScalarField.C.
References Foam::pos().
gradientInternalCoeffs()
Foam::tmp< Foam::Field< Foam::scalar > > gradientInternalCoeffs () const virtual
Definition at line 212 of file adjointFarFieldPressureFvPatchScalarField.C.
References Foam::pos().
gradientBoundaryCoeffs()
Foam::tmp< Foam::Field< Foam::scalar > > gradientBoundaryCoeffs () const virtual
Definition at line 228 of file adjointFarFieldPressureFvPatchScalarField.C.
References Foam::pos().
updateCoeffs()
void updateCoeffs () virtual
Definition at line 87 of file adjointFarFieldPressureFvPatchScalarField.C.
References delta, Foam::neg(), and Foam::pos().
write()
void write (Ostream & os) const virtual
Definition at line 243 of file adjointFarFieldPressureFvPatchScalarField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntry(), and fvPatchField< Type >::writeValueEntry().
operator=() [1/3]
void operator= (const UList< scalar > & ul) virtual
Definition at line 253 of file adjointFarFieldPressureFvPatchScalarField.C.
References Foam::neg(), Field< Type >::operator=(), and Foam::pos().
operator=() [2/3]
void operator= (const fvPatchField< scalar > & ptf) virtual
Definition at line 265 of file adjointFarFieldPressureFvPatchScalarField.C.
References Foam::check(), Foam::neg(), Field< Type >::operator=(), and Foam::pos().
operator+=() [1/3]
void operator+= (const fvPatchField< scalar > & ptf) virtual
Definition at line 278 of file adjointFarFieldPressureFvPatchScalarField.C.
References Foam::check(), Foam::neg(), Field< Type >::operator=(), and Foam::pos().
operator-=() [1/3]
void operator-= (const fvPatchField< scalar > & ptf) virtual
Definition at line 291 of file adjointFarFieldPressureFvPatchScalarField.C.
References Foam::check(), Foam::neg(), Field< Type >::operator=(), and Foam::pos().
operator*=() [1/3]
void operator*= (const fvPatchField< scalar > & ptf) virtual
Definition at line 304 of file adjointFarFieldPressureFvPatchScalarField.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, Foam::neg(), Field< Type >::operator=(), and Foam::pos().
operator/=() [1/3]
void operator/= (const fvPatchField< scalar > & ptf) virtual
Definition at line 323 of file adjointFarFieldPressureFvPatchScalarField.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, Foam::neg(), Field< Type >::operator=(), and Foam::pos().
operator+=() [2/3]
void operator+= (const Field< scalar > & tf) virtual
Definition at line 342 of file adjointFarFieldPressureFvPatchScalarField.C.
References Foam::neg(), Field< Type >::operator=(), and Foam::pos().
operator-=() [2/3]
void operator-= (const Field< scalar > & tf) virtual
Definition at line 354 of file adjointFarFieldPressureFvPatchScalarField.C.
References Foam::neg(), Field< Type >::operator=(), and Foam::pos().
operator*=() [2/3]
void operator*= (const Field< scalar > & tf) virtual
Definition at line 366 of file adjointFarFieldPressureFvPatchScalarField.C.
References Foam::neg(), Field< Type >::operator=(), and Foam::pos().
operator/=() [2/3]
void operator/= (const Field< scalar > & tf) virtual
Definition at line 378 of file adjointFarFieldPressureFvPatchScalarField.C.
References Foam::neg(), Field< Type >::operator=(), and Foam::pos().
operator=() [3/3]
void operator= (const scalar t) virtual
Definition at line 390 of file adjointFarFieldPressureFvPatchScalarField.C.
References Foam::neg(), Field< Type >::operator=(), and Foam::pos().
operator+=() [3/3]
void operator+= (const scalar t) virtual
Definition at line 402 of file adjointFarFieldPressureFvPatchScalarField.C.
References Foam::neg(), Field< Type >::operator=(), and Foam::pos().
operator-=() [3/3]
void operator-= (const scalar t) virtual
Definition at line 414 of file adjointFarFieldPressureFvPatchScalarField.C.
References Foam::neg(), Field< Type >::operator=(), and Foam::pos().
operator*=() [3/3]
void operator*= (const scalar s) virtual
Definition at line 430 of file adjointFarFieldPressureFvPatchScalarField.C.
References Foam::neg(), Field< Type >::operator=(), Foam::pos(), and s().
operator/=() [3/3]
void operator/= (const scalar s) virtual
Definition at line 442 of file adjointFarFieldPressureFvPatchScalarField.C.
References Foam::neg(), Field< Type >::operator=(), Foam::pos(), and s().
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/adjointBoundaryConditions/adjointFarFieldPressure/adjointFarFieldPressureFvPatchScalarField.H
src/optimisation/adjointOptimisation/adjoint/adjointBoundaryConditions/adjointFarFieldPressure/adjointFarFieldPressureFvPatchScalarField.C