OpenFOAM: Euler Class Reference
Euler Class Reference
#include <Euler.H>
Public Member Functions
TypeName ("Euler")
Euler ()
virtual autoPtr< integrationScheme > clone () const
virtual ~Euler ()
virtual scalar dtEff (const scalar dt, const scalar Beta) const
virtual scalar sumDtEff (const scalar dt, const scalar Beta) const
Public Member Functions inherited from integrationScheme
TypeName ("integrationScheme")
declareRunTimeSelectionTable (autoPtr, integrationScheme, word,(),())
integrationScheme ()
virtual ~integrationScheme ()
template<class Type >
Type delta (const Type &phi, const scalar dt, const Type &Alpha, const scalar Beta) const
template<class Type >
Type partialDelta (const Type &phi, const scalar dt, const Type &Alpha, const scalar Beta, const Type &alphai, const scalar betai) const
Additional Inherited Members
Static Public Member Functions inherited from integrationScheme
static autoPtr< integrationScheme > New (const word &phiName, const dictionary &dict)
template<class Type >
static Type explicitDelta (const Type &phi, const scalar dtEff, const Type &Alpha, const scalar Beta)
Detailed Description
Definition at line 47 of file Euler.H.
Constructor & Destructor Documentation
Euler()
Euler ()
Definition at line 37 of file Euler.C.
Referenced by Euler::clone().
~Euler()
~Euler () virtual
Definition at line 43 of file Euler.C.
Member Function Documentation
TypeName()
TypeName ("Euler")
clone()
virtual autoPtr< integrationScheme > clone () const inline virtual
Implements integrationScheme.
Definition at line 63 of file Euler.H.
References Euler::Euler().
dtEff()
Foam::scalar dtEff (const scalar dt, const scalar Beta) const virtual
Implements integrationScheme.
Definition at line 49 of file Euler.C.
sumDtEff()
Foam::scalar sumDtEff (const scalar dt, const scalar Beta) const virtual
Implements integrationScheme.
Definition at line 59 of file Euler.C.
References Foam::sqr().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/integrationScheme/Euler/Euler.H
src/lagrangian/intermediate/integrationScheme/Euler/Euler.C