OpenFOAM: transferModel Class Reference
transferModel Class Reference abstract
Base class for film transfer models, handling mass transfer between the film and the continuous phase.
#include <transferModel.H>
Public Member Functions
TypeName ("transferModel")
declareRunTimeSelectionTable (autoPtr, transferModel, dictionary,(surfaceFilmRegionModel &film, const dictionary &dict),(film, dict))
transferModel (surfaceFilmRegionModel &film)
transferModel (const word &modelType, surfaceFilmRegionModel &film, const dictionary &dict)
virtual ~transferModel ()
virtual void correct (scalarField &availableMass, scalarField &massToTransfer)=0
virtual void correct (scalarField &availableMass, scalarField &massToTransfer, scalarField &energyToTransfer)
virtual scalar transferredMassTotal () const
virtual void patchTransferredMassTotals (scalarField &patchMasses) const
Public Member Functions inherited from filmSubModelBase
filmSubModelBase (surfaceFilmRegionModel &film)
filmSubModelBase (surfaceFilmRegionModel &film, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
filmSubModelBase (const word &modelName, surfaceFilmRegionModel &film, const dictionary &dict, const word &baseName, const word &modelType)
virtual ~filmSubModelBase ()
virtual bool writeTime () const
const surfaceFilmRegionModel & film () const
surfaceFilmRegionModel & film ()
template<class FilmType >
const FilmType & filmType () const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
subModelBase (const subModelBase &smb)
virtual ~subModelBase ()=default
const word & modelName () const
const dictionary & dict () const
const word & baseName () const
const word & modelType () const
const dictionary & coeffDict () const
const dictionary & properties () const
virtual bool defaultCoeffs (const bool printMsg) const
virtual bool active () const
virtual void cacheFields (const bool store)
virtual fileName localPath () const
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
bool getModelDict (const word &entryName, dictionary &dict) const
template<class Type >
bool getModelProperty (const word &entryName, Type &value) const
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
virtual void write (Ostream &os) const
Static Public Member Functions
static autoPtr< transferModel > New (surfaceFilmRegionModel &film, const dictionary &dict, const word &modelType)
Protected Member Functions
void addToTransferredMass (const scalar dMass)
void correct ()
Protected Member Functions inherited from subModelBase
bool inLine () const
Additional Inherited Members
Public Attributes inherited from subModelBase
bool log
Protected Attributes inherited from filmSubModelBase
surfaceFilmRegionModel & filmModel_
Protected Attributes inherited from subModelBase
const word modelName_
dictionary & properties_
const dictionary dict_
const word baseName_
const word modelType_
const dictionary coeffDict_
Detailed Description
Base class for film transfer models, handling mass transfer between the film and the continuous phase.
Source files
transferModel.H
transferModel.C
transferModelNew.C
Definition at line 54 of file transferModel.H.
Constructor & Destructor Documentation
transferModel() [1/2]
transferModel (surfaceFilmRegionModel & film)
Definition at line 47 of file transferModel.C.
transferModel() [2/2]
transferModel (const word & modelType, surfaceFilmRegionModel & film, const dictionary & dict)
Definition at line 54 of file transferModel.C.
~transferModel()
~transferModel () virtual
Definition at line 68 of file transferModel.C.
Member Function Documentation
addToTransferredMass()
void addToTransferredMass (const scalar dMass) protected
Definition at line 39 of file transferModel.C.
correct() [1/3]
void correct () protected
Definition at line 74 of file transferModel.C.
References Foam::returnReduce(), and filmSubModelBase::writeTime().
Referenced by transferModel::correct().
TypeName()
TypeName ("transferModel")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , transferModel , dictionary , (surfaceFilmRegionModel &film, const dictionary &dict) , (film, dict))
New()
autoPtr< transferModel > New (surfaceFilmRegionModel & film, const dictionary & dict, const word & modelType) static
Definition at line 35 of file transferModelNew.C.
References subModelBase::dict(), Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, Foam::Info, and subModelBase::modelType().
Referenced by transferModelList::transferModelList().
correct() [2/3]
virtual void correct (scalarField & availableMass, scalarField & massToTransfer) pure virtual
Implemented in VoFPatchTransfer.
correct() [3/3]
void correct (scalarField & availableMass, scalarField & massToTransfer, scalarField & energyToTransfer) virtual
Reimplemented in VoFPatchTransfer.
Definition at line 85 of file transferModel.C.
References transferModel::correct(), filmSubModelBase::film(), UPtrList< T >::size(), and Foam::Zero.
transferredMassTotal()
scalar transferredMassTotal () const virtual
Definition at line 98 of file transferModel.C.
References Foam::returnReduce().
Referenced by transferModelList::info().
patchTransferredMassTotals()
virtual void patchTransferredMassTotals (scalarField & patchMasses) const inline virtual
Reimplemented in VoFPatchTransfer.
Definition at line 156 of file transferModel.H.
Referenced by transferModelList::info().
The documentation for this class was generated from the following files:
src/regionModels/surfaceFilmModels/submodels/kinematic/transferModels/transferModel/transferModel.H
src/regionModels/surfaceFilmModels/submodels/kinematic/transferModels/transferModel/transferModel.C
src/regionModels/surfaceFilmModels/submodels/kinematic/transferModels/transferModel/transferModelNew.C