OpenFOAM: bufferView Class Reference
bufferView Class Reference
glTF buffer view - provides a view/slice of the glTF buffer
#include <foamGltfBufferView.H>
Public Member Functions
bufferView ()
bufferView (const word &name)
~bufferView ()=default
label & buffer () noexcept
label & byteOffset () noexcept
label & byteLength () noexcept
label & target () noexcept
void write (Ostream &os) const
void operator= (const bufferView &bv)
Public Member Functions inherited from base
base ()
base (const word &name)
~base ()=default
label & id () noexcept
const word & name () const noexcept
void write (Ostream &os) const
void operator= (const base &gltf)
Protected Attributes
label buffer_
label byteOffset_
label byteLength_
label target_
Protected Attributes inherited from base
word name_
label id_
Detailed Description
glTF buffer view - provides a view/slice of the glTF buffer
Note
Implements the glTF v2 specification
Source files
foamGltfBufferView.H
foamGltfBufferView.C
Definition at line 59 of file foamGltfBufferView.H.
Constructor & Destructor Documentation
bufferView() [1/2]
bufferView ()
Definition at line 25 of file foamGltfBufferView.C.
bufferView() [2/2]
bufferView (const word & name) explicit
Definition at line 35 of file foamGltfBufferView.C.
~bufferView()
~bufferView () default
Member Function Documentation
buffer()
Foam::label & buffer () noexcept
Definition at line 47 of file foamGltfBufferView.C.
byteOffset()
Foam::label & byteOffset () noexcept
Definition at line 53 of file foamGltfBufferView.C.
byteLength()
Foam::label & byteLength () noexcept
Definition at line 59 of file foamGltfBufferView.C.
target()
Foam::label & target () noexcept
Definition at line 65 of file foamGltfBufferView.C.
write()
void write (Ostream & os) const
Definition at line 71 of file foamGltfBufferView.C.
References Foam::indent(), Foam::nl, os(), and base::write().
operator=()
void operator= (const bufferView & bv)
Definition at line 87 of file foamGltfBufferView.C.
References base::operator=().
Member Data Documentation
buffer_
label buffer_ protected
Definition at line 68 of file foamGltfBufferView.H.
byteOffset_
label byteOffset_ protected
Definition at line 71 of file foamGltfBufferView.H.
byteLength_
label byteLength_ protected
Definition at line 74 of file foamGltfBufferView.H.
target_
label target_ protected
Definition at line 77 of file foamGltfBufferView.H.
The documentation for this class was generated from the following files:
src/fileFormats/gltf/foamGltfBufferView.H
src/fileFormats/gltf/foamGltfBufferView.C