OpenFOAM: exprResultStored Class Reference
exprResultStored Class Reference
An exprResult with persistence.
#include <exprResultStored.H>
Public Member Functions
TypeNameNoDebug ("exprResultStored")
exprResultStored ()
exprResultStored (const exprResultStored &rhs)
exprResultStored (const dictionary &dict)
virtual autoPtr< exprResult > clone () const
virtual ~exprResultStored ()=default
const word & name () const
const expressions::exprString & initialValueExpression () const
void writeDict (Ostream &os) const
void operator= (const exprResultStored &rhs)
void operator= (const exprResult &rhs)
Public Member Functions inherited from exprResult
TypeName ("exprResult")
declareRunTimeSelectionTable (autoPtr, exprResult, dictionary,(const dictionary &dict),(dict))
declareRunTimeSelectionTable (autoPtr, exprResult, empty,(),())
exprResult ()
exprResult (const exprResult &expr)
exprResult (exprResult &&expr)
exprResult (const dictionary &dict, const bool uniform=false, const bool needsValue=false)
exprResult (Istream &is)
template<class Type >
exprResult (const Field< Type > &fld)
template<class Type >
exprResult (Field< Type > &&fld)
template<class Type >
exprResult (autoPtr< Type > &&obj)
template<class Type >
exprResult (const dimensioned< Type > &dt)
exprResult (const bool &val)
Construct from single value of bool.
exprResult (const scalar &val)
Construct from single value of scalar.
exprResult (const vector &val)
Construct from single value of vector.
exprResult (const tensor &val)
Construct from single value of tensor.
exprResult (const symmTensor &val)
Construct from single value of symmTensor.
exprResult (const sphericalTensor &val)
Construct from single value of sphericalTensor.
virtual ~exprResult ()
bool hasValue () const
const word & valueType () const noexcept
bool isPointData (const bool wantPointData=true) const
bool isUniform () const
template<class Type >
bool isType () const
template<class Type >
Type getValue () const
bool is_bool () const
label size () const
const void * dataAddress () const
void clear ()
void noReset () noexcept
void allowReset () noexcept
void testIfSingleValue (const bool parRun=Pstream::parRun())
template<class Type >
void setResult (Field< Type > *, bool wantPointData=false)
template<class Type >
void setResult (const Field< Type > &, bool wantPointData=false)
template<class Type >
void setResult (Field< Type > &&, bool wantPointData=false)
template<class Type >
void setResult (const Type &val, const label size)
template<class Type >
void setSingleValue (const Type &val)
template<class Type >
const Field< Type > & cref () const
template<class Type >
Field< Type > & ref ()
template<class Type >
Field< Type > & constCast () const
template<class Type >
tmp< Field< Type > > getResult (bool cacheCopy=false)
exprResult getUniform (const label size, const bool noWarn, const bool parRun=Pstream::parRun()) const
template<template< class > class BinaryOp, class Type >
Type getReduced (const BinaryOp< Type > &bop, const Type &initial=pTraits< Type >::zero)
void writeEntry (const word &keyword, Ostream &os) const
void writeDict (Ostream &os, const bool subDict=true) const
void writeField (Ostream &os, const word &keyword="") const
void writeValue (Ostream &os) const
virtual void operator= (exprResult &&rhs)
exprResult & operator*= (const scalar &b)
exprResult & operator+= (const exprResult &b)
template<class Type >
Foam::tmp< Foam::Field< Type > > getResult (bool cacheCopy)
template<class Type >
const Foam::Field< Type > & cref () const
template<class Type >
Foam::Field< Type > & ref ()
template<class Type >
Foam::Field< Type > & constCast () const
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Protected Member Functions
virtual void resetImpl ()
Protected Member Functions inherited from exprResult
virtual expressions::exprResult & target ()
bool reset (bool force=false)
void needsReset (bool val)
Additional Inherited Members
Static Public Member Functions inherited from exprResult
static autoPtr< exprResult > New (const dictionary &dict)
static autoPtr< exprResult > New (Istream &is)
Static Public Attributes inherited from exprResult
static const exprResult null
Detailed Description
An exprResult with persistence.
Dictionary parameters
Property Description Required Default
name The result name yes
initialValue The initial value yes
value The expression result (dictionary) no
Source files
exprResultStored.H
StoredExpressionResult.C
Definition at line 78 of file exprResultStored.H.
Constructor & Destructor Documentation
exprResultStored() [1/3]
exprResultStored ()
Definition at line 52 of file exprResultStored.C.
Referenced by exprResultStored::clone().
exprResultStored() [2/3]
exprResultStored (const exprResultStored & rhs)
Definition at line 60 of file exprResultStored.C.
exprResultStored() [3/3]
exprResultStored (const dictionary & dict) explicit
Definition at line 71 of file exprResultStored.C.
~exprResultStored()
virtual ~exprResultStored () virtual default
Member Function Documentation
resetImpl()
virtual void resetImpl () inline protected virtual
Reimplemented from exprResult.
Definition at line 96 of file exprResultStored.H.
TypeNameNoDebug()
TypeNameNoDebug ("exprResultStored")
clone()
virtual autoPtr< exprResult > clone () const inline virtual
Reimplemented from exprResult.
Definition at line 119 of file exprResultStored.H.
References exprResultStored::exprResultStored().
name()
const word & name () const inline
Definition at line 135 of file exprResultStored.H.
initialValueExpression()
const expressions::exprString & initialValueExpression () const inline
Definition at line 141 of file exprResultStored.H.
writeDict()
void writeDict (Ostream & os) const
Definition at line 84 of file exprResultStored.C.
References os().
operator=() [1/2]
void operator= (const exprResultStored & rhs)
Definition at line 100 of file exprResultStored.C.
References exprResult::operator=().
operator=() [2/2]
void operator= (const exprResult & rhs) virtual
Reimplemented from exprResult.
Definition at line 117 of file exprResultStored.C.
References exprResult::operator=().
The documentation for this class was generated from the following files:
src/OpenFOAM/expressions/exprResult/exprResultStored.H
src/OpenFOAM/expressions/exprResult/exprResultStored.C