OpenFOAM: linearAxialAngularSpring Class Reference
linearAxialAngularSpring Class Reference
Mesh motion » Rigid body dynamics » Restraints
Linear axial angular spring restraint.
#include <linearAxialAngularSpring.H>
Public Member Functions
TypeName ("linearAxialAngularSpring")
linearAxialAngularSpring (const word &name, const dictionary &dict, const rigidBodyModel &model)
virtual autoPtr< restraint > clone () const
virtual ~linearAxialAngularSpring ()
virtual void restrain (scalarField &tau, Field< spatialVector > &fx, const rigidBodyModelState &state) const
virtual bool read (const dictionary &dict)
virtual void write (Ostream &) const
Public Member Functions inherited from restraint
TypeName ("restraint")
declareRunTimeSelectionTable (autoPtr, restraint, dictionary,(const word &name, const dictionary &dict, const rigidBodyModel &model),(name, dict, model))
restraint (const word &name, const dictionary &dict, const rigidBodyModel &model)
virtual ~restraint ()
const word & name () const
label bodyID () const
const dictionary & coeffDict () const
Additional Inherited Members
Static Public Member Functions inherited from restraint
static autoPtr< restraint > New (const word &name, const dictionary &dict, const rigidBodyModel &model)
Protected Member Functions inherited from restraint
point bodyPoint (const point &p) const
spatialVector bodyPointVelocity (const point &p) const
Protected Attributes inherited from restraint
word name_
label bodyID_
label bodyIndex_
dictionary coeffs_
const rigidBodyModel & model_
Detailed Description
Linear axial angular spring restraint.
Source files
linearAxialAngularSpring.H
linearAxialAngularSpring.C
Definition at line 53 of file linearAxialAngularSpring.H.
Constructor & Destructor Documentation
linearAxialAngularSpring()
linearAxialAngularSpring (const word & name, const dictionary & dict, const rigidBodyModel & model)
Definition at line 49 of file linearAxialAngularSpring.C.
References dict, Foam::name(), and linearAxialAngularSpring::read().
~linearAxialAngularSpring()
~linearAxialAngularSpring () virtual
Definition at line 64 of file linearAxialAngularSpring.C.
Member Function Documentation
TypeName()
TypeName ("linearAxialAngularSpring")
clone()
virtual autoPtr< restraint > clone () const inline virtual
Implements restraint.
Definition at line 89 of file linearAxialAngularSpring.H.
restrain()
void restrain (scalarField & tau, Field< spatialVector > & fx, const rigidBodyModelState & state) const virtual
Implements restraint.
Definition at line 70 of file linearAxialAngularSpring.C.
References Foam::acos(), Foam::endl(), Foam::Info, Foam::mag(), Foam::min(), Foam::rotationTensor(), Foam::sign(), and Foam::Zero.
read()
bool read (const dictionary & dict) virtual
Reimplemented from restraint.
Definition at line 137 of file linearAxialAngularSpring.C.
References Foam::abort(), dict, Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::I, Foam::mag(), Foam::nl, restraint::read(), and Foam::sqrt().
Referenced by linearAxialAngularSpring::linearAxialAngularSpring().
write()
void write (Ostream & os) const virtual
Implements restraint.
Definition at line 177 of file linearAxialAngularSpring.C.
References os(), and restraint::write().
The documentation for this class was generated from the following files:
src/rigidBodyDynamics/restraints/linearAxialAngularSpring/linearAxialAngularSpring.H
src/rigidBodyDynamics/restraints/linearAxialAngularSpring/linearAxialAngularSpring.C