OpenFOAM: RecycleInteraction< CloudType > Class Template Reference
RecycleInteraction< CloudType > Class Template Reference
Lagrangian particle models » Submodels » Kinematic » Patch interaction
Patch interaction model to perform parcel transfer and recycle from one patch to another.
#include <RecycleInteraction.H>
Public Member Functions
TypeName ("recycleInteraction")
RecycleInteraction (const dictionary &dict, CloudType &cloud)
RecycleInteraction (const RecycleInteraction< CloudType > &pim)
virtual autoPtr< PatchInteractionModel< CloudType > > clone () const
virtual ~RecycleInteraction ()=default
virtual bool correct (typename CloudType::parcelType &p, const polyPatch &pp, bool &keepParticle)
virtual void postEvolve ()
virtual void info ()
Public Member Functions inherited from PatchInteractionModel< CloudType >
TypeName ("patchInteractionModel")
declareRunTimeSelectionTable (autoPtr, PatchInteractionModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
PatchInteractionModel (CloudType &owner)
PatchInteractionModel (const dictionary &dict, CloudType &owner, const word &type)
PatchInteractionModel (const PatchInteractionModel< CloudType > &pim)
virtual ~PatchInteractionModel ()=default
const word & UName () const
const scalar & Urmax () const
virtual void addToEscapedParcels (const scalar mass)
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
virtual ~CloudSubModelBase ()=default
const CloudType & owner () const
virtual bool writeTime () const
virtual fileName localPath () const
CloudType & owner ()
virtual void write (Ostream &os) const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
subModelBase (const subModelBase &smb)
virtual ~subModelBase ()=default
const word & modelName () const
const dictionary & dict () const
const word & baseName () const
const word & modelType () const
const dictionary & coeffDict () const
const dictionary & properties () const
virtual bool defaultCoeffs (const bool printMsg) const
virtual bool active () const
virtual void cacheFields (const bool store)
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
bool getModelDict (const word &entryName, dictionary &dict) const
template<class Type >
bool getModelProperty (const word &entryName, Type &value) const
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Public Member Functions inherited from writeFile
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name="undefined", const bool writeToFile=true)
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name, const dictionary &dict, const bool writeToFile=true)
writeFile (const writeFile &wf)
virtual ~writeFile ()=default
virtual bool read (const dictionary &dict)
virtual OFstream & file ()
virtual bool writeToFile () const
virtual bool canWriteToFile () const
virtual bool canResetFile () const
virtual bool canWriteHeader () const
virtual label charWidth () const
virtual void writeCommented (Ostream &os, const string &str) const
virtual void writeTabbed (Ostream &os, const string &str) const
virtual void writeHeader (Ostream &os, const string &str) const
virtual void writeCurrentTime (Ostream &os) const
virtual void writeBreak (Ostream &os) const
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
template<class Type >
void writeValue (Ostream &os, const Type &val) const
Protected Types
typedef CloudType::parcelType parcelType
Protected Member Functions
virtual void writeFileHeader (Ostream &os)
Protected Member Functions inherited from subModelBase
bool inLine () const
Protected Member Functions inherited from writeFile
void initStream (Ostream &os) const
fileName baseFileDir () const
fileName baseTimeDir () const
fileName filePath (const fileName &fName) const
virtual autoPtr< OFstream > newFile (const fileName &fName) const
virtual autoPtr< OFstream > newFileAtTime (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > newFileAtStartTime (const word &name) const
virtual void resetFile (const word &name)
Omanip< int > valueWidth (const label offset=0) const
void operator= (const writeFile &)=delete
virtual autoPtr< OFstream > createFile (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > createFile (const word &name) const
Protected Attributes
const fvMesh & mesh_
List< Pair< word > > recyclePatches_
List< Pair< label > > recyclePatchesIds_
List< IDLList< parcelType > > recycledParcels_
List< List< label > > nRemoved_
List< List< scalar > > massRemoved_
List< List< label > > nInjected_
List< List< scalar > > massInjected_
Map< label > injIdToIndex_
PtrList< patchInjectionBase > injectionPatchPtr_
const scalar recycleFraction_
bool outputByInjectorId_
Protected Attributes inherited from PatchInteractionModel< CloudType >
const word UName_
label escapedParcels_
scalar escapedMass_
scalar Urmax_
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Protected Attributes inherited from subModelBase
const word modelName_
dictionary & properties_
const dictionary dict_
const word baseName_
const word modelType_
const dictionary coeffDict_
Protected Attributes inherited from writeFile
const objectRegistry & fileObr_
const fileName prefix_
word fileName_
autoPtr< OFstream > filePtr_
label writePrecision_
bool writeToFile_
bool updateHeader_
bool writtenHeader_
bool useUserTime_
scalar startTime_
Additional Inherited Members
Public Types inherited from PatchInteractionModel< CloudType >
enum interactionType {
itNone , itRebound , itStick , itEscape ,
itOther
}
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Static Public Member Functions inherited from PatchInteractionModel< CloudType >
static autoPtr< PatchInteractionModel< CloudType > > New (const dictionary &dict, CloudType &owner)
static word interactionTypeToWord (const interactionType &itEnum)
static interactionType wordToInteractionType (const word &itWord)
Public Attributes inherited from subModelBase
bool log
Static Public Attributes inherited from PatchInteractionModel< CloudType >
static wordList interactionTypeNames_
Static Public Attributes inherited from writeFile
static label addChars = 8
Detailed Description
template<class CloudType>
class Foam::RecycleInteraction< CloudType >
Patch interaction model to perform parcel transfer and recycle from one patch to another.
Parcels that hit a given 'outflow' patch are recycled to a given 'inflow' patch, with optional:
recycle fraction [0-1]
Usage
Minimal example by using constant/reactingCloud1Properties.subModels.multiInteractionCoeffs
multiInteractionCoeffs
{
    ...
    model1
    {
        // Mandatory entries (unmodifiable)
        patchInteractionModel    recycleInteraction;
        recycleInteractionCoeffs
        {
            recyclePatches
            (
                (<outletPatch1> <inletPatch1>)
                (<outletPatch2> <inletPatch2>)
                ...
            );
            recycleFraction      0.8; // [0-1]
            // Optional entries (unmodifiable)
            outputByInjectorId   false;
        }
    }
    ...
}
where the entries mean:
Property Description Type Reqd Dflt
patchInteractionModel
Type name: recycleInteraction
word yes -
recyclePatches
Names of outlet-inlet patch pairs
(word word) yes -
recycleFraction
Fraction of parcels recycled from
outlet to inlet
scalar yes -
outputByInjectorId
Flag to output escaped/mass
particles sorted by injectorID
bool no false
Source files
RecycleInteraction.H
RecycleInteraction.C
Definition at line 141 of file RecycleInteraction.H.
Member Typedef Documentation
parcelType
template<class CloudType > typedef CloudType::parcelType parcelType protected
Definition at line 147 of file RecycleInteraction.H.
Constructor & Destructor Documentation
RecycleInteraction() [1/2]
template<class CloudType > RecycleInteraction (const dictionary & dict, CloudType & cloud)
Definition at line 56 of file RecycleInteraction.C.
References HashTable< T, Key, Hash >::empty(), UPtrList< T >::first(), forAll, RecycleInteraction< CloudType >::injectionPatchPtr_, RecycleInteraction< CloudType >::injIdToIndex_, HashTable< T, Key, Hash >::insert(), RecycleInteraction< CloudType >::massInjected_, RecycleInteraction< CloudType >::massRemoved_, RecycleInteraction< CloudType >::mesh_, RecycleInteraction< CloudType >::nInjected_, RecycleInteraction< CloudType >::nRemoved_, RecycleInteraction< CloudType >::outputByInjectorId_, RecycleInteraction< CloudType >::recyclePatches_, RecycleInteraction< CloudType >::recyclePatchesIds_, PtrList< T >::set(), List< T >::setSize(), PtrList< T >::setSize(), and Foam::Zero.
RecycleInteraction() [2/2]
template<class CloudType > RecycleInteraction (const RecycleInteraction< CloudType > & pim)
Definition at line 126 of file RecycleInteraction.C.
~RecycleInteraction()
template<class CloudType > virtual ~RecycleInteraction () virtual default
Member Function Documentation
writeFileHeader()
template<class CloudType > void writeFileHeader (Ostream & os) protected virtual
Reimplemented from PatchInteractionModel< CloudType >.
Definition at line 26 of file RecycleInteraction.C.
References UPtrList< T >::first(), forAll, Foam::name(), os(), and PatchInteractionModel< CloudType >::writeFileHeader().
TypeName()
template<class CloudType > TypeName ("recycleInteraction")
clone()
template<class CloudType > virtual autoPtr< PatchInteractionModel< CloudType > > clone () const inline virtual
Implements PatchInteractionModel< CloudType >.
Definition at line 213 of file RecycleInteraction.H.
correct()
template<class CloudType > bool correct (typename CloudType::parcelType & p, const polyPatch & pp, bool & keepParticle) virtual
Implements PatchInteractionModel< CloudType >.
Definition at line 149 of file RecycleInteraction.C.
References PtrList< T >::append(), GeometricField< Type, PatchField, GeoMesh >::clone(), forAll, p, and pp().
postEvolve()
template<class CloudType > void postEvolve () virtual
Reimplemented from PatchInteractionModel< CloudType >.
Definition at line 197 of file RecycleInteraction.C.
References forAll, UPtrList< T >::get(), mesh, UPstream::nonBlocking, UPstream::nProcs(), p, UPstream::parRun(), rndGen, and PtrList< T >::set().
info()
template<class CloudType > void info () virtual
Reimplemented from PatchInteractionModel< CloudType >.
Definition at line 347 of file RecycleInteraction.C.
References Foam::endl(), UPtrList< T >::first(), forAll, forAllConstIters, PatchInteractionModel< CloudType >::info(), Pstream::listCombineGather(), Log_, Foam::nl, PtrList< T >::setSize(), UPtrList< T >::size(), Foam::tab, and Foam::Zero.
Member Data Documentation
mesh_
template<class CloudType > const fvMesh& mesh_ protected
Definition at line 152 of file RecycleInteraction.H.
Referenced by RecycleInteraction< CloudType >::RecycleInteraction().
recyclePatches_
template<class CloudType > List<Pair<word> > recyclePatches_ protected
Definition at line 155 of file RecycleInteraction.H.
Referenced by RecycleInteraction< CloudType >::RecycleInteraction().
recyclePatchesIds_
template<class CloudType > List<Pair<label> > recyclePatchesIds_ protected
Definition at line 158 of file RecycleInteraction.H.
Referenced by RecycleInteraction< CloudType >::RecycleInteraction().
recycledParcels_
template<class CloudType > List<IDLList<parcelType> > recycledParcels_ protected
Definition at line 161 of file RecycleInteraction.H.
nRemoved_
template<class CloudType > List<List<label> > nRemoved_ protected
Definition at line 167 of file RecycleInteraction.H.
Referenced by RecycleInteraction< CloudType >::RecycleInteraction().
massRemoved_
template<class CloudType > List<List<scalar> > massRemoved_ protected
Definition at line 170 of file RecycleInteraction.H.
Referenced by RecycleInteraction< CloudType >::RecycleInteraction().
nInjected_
template<class CloudType > List<List<label> > nInjected_ protected
Definition at line 173 of file RecycleInteraction.H.
Referenced by RecycleInteraction< CloudType >::RecycleInteraction().
massInjected_
template<class CloudType > List<List<scalar> > massInjected_ protected
Definition at line 176 of file RecycleInteraction.H.
Referenced by RecycleInteraction< CloudType >::RecycleInteraction().
injIdToIndex_
template<class CloudType > Map<label> injIdToIndex_ protected
Definition at line 180 of file RecycleInteraction.H.
Referenced by RecycleInteraction< CloudType >::RecycleInteraction().
injectionPatchPtr_
template<class CloudType > PtrList<patchInjectionBase> injectionPatchPtr_ protected
Definition at line 183 of file RecycleInteraction.H.
Referenced by RecycleInteraction< CloudType >::RecycleInteraction().
recycleFraction_
template<class CloudType > const scalar recycleFraction_ protected
Definition at line 186 of file RecycleInteraction.H.
outputByInjectorId_
template<class CloudType > bool outputByInjectorId_ protected
Definition at line 189 of file RecycleInteraction.H.
Referenced by RecycleInteraction< CloudType >::RecycleInteraction().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/Kinematic/PatchInteractionModel/RecycleInteraction/RecycleInteraction.H
src/lagrangian/intermediate/submodels/Kinematic/PatchInteractionModel/RecycleInteraction/RecycleInteraction.C