OpenFOAM: DRG< CompType, ThermoType > Class Template Reference
DRG< CompType, ThermoType > Class Template Reference
Implementation of the Directed Relation Graph (DRG) method.
#include <DRG.H>
Public Member Functions
TypeName ("DRG")
DRG (const IOdictionary &dict, TDACChemistryModel< CompType, ThermoType > &chemistry)
virtual ~DRG ()
virtual void reduceMechanism (const scalarField &c, const scalar T, const scalar p)
Public Member Functions inherited from chemistryReductionMethod< CompType, ThermoType >
TypeName ("chemistryReductionMethod")
declareRunTimeSelectionTable (autoPtr, chemistryReductionMethod, dictionary,(const IOdictionary &dict, TDACChemistryModel< CompType, ThermoType > &chemistry),(dict, chemistry))
chemistryReductionMethod (const IOdictionary &dict, TDACChemistryModel< CompType, ThermoType > &chemistry)
virtual ~chemistryReductionMethod ()
bool active () const
bool log () const
const List< bool > & activeSpecies () const
label NsSimp ()
label nSpecie ()
scalar tolerance () const
Additional Inherited Members
Static Public Member Functions inherited from chemistryReductionMethod< CompType, ThermoType >
static autoPtr< chemistryReductionMethod< CompType, ThermoType > > New (const IOdictionary &dict, TDACChemistryModel< CompType, ThermoType > &chemistry)
Protected Attributes inherited from chemistryReductionMethod< CompType, ThermoType >
const IOdictionary & dict_
const dictionary coeffsDict_
Switch active_
Switch log_
TDACChemistryModel< CompType, ThermoType > & chemistry_
List< bool > activeSpecies_
label NsSimp_
const label nSpecie_
scalar tolerance_
Detailed Description
template<class CompType, class ThermoType>
class Foam::chemistryReductionMethods::DRG< CompType, ThermoType >
Implementation of the Directed Relation Graph (DRG) method.
Source files
DRG.H
DRG.C
Definition at line 49 of file DRG.H.
Constructor & Destructor Documentation
DRG()
template<class CompType , class ThermoType > DRG (const IOdictionary & dict, TDACChemistryModel< CompType, ThermoType > & chemistry)
Definition at line 26 of file DRG.C.
References chemistry, chemistryReductionMethod< CompType, ThermoType >::coeffsDict_, Foam::exit(), Foam::FatalError, FatalErrorInFunction, and UList< T >::size().
~DRG()
template<class CompType , class ThermoType > ~DRG () virtual
Definition at line 58 of file DRG.C.
Member Function Documentation
TypeName()
template<class CompType , class ThermoType > TypeName ("DRG< CompType, ThermoType >")
reduceMechanism()
template<class CompType , class ThermoType > void reduceMechanism (const scalarField & c, const scalar T, const scalar p) virtual
Implements chemistryReductionMethod< CompType, ThermoType >.
Definition at line 65 of file DRG.C.
References PtrList< T >::append(), UPtrList< T >::empty(), forAll, found, p, R, s(), PtrList< T >::setSize(), UPtrList< T >::size(), T, and Foam::Zero.
The documentation for this class was generated from the following files:
src/thermophysicalModels/chemistryModel/chemistryModel/TDACChemistryModel/reduction/DRG/DRG.H
src/thermophysicalModels/chemistryModel/chemistryModel/TDACChemistryModel/reduction/DRG/DRG.C