OpenFOAM: forceCoeffs Class Reference
forceCoeffs Class Reference
FunctionObjects » Forces function objects
Computes force and moment coefficients over a given list of patches, and optionally over given porous zones. The following coefficients can be selected and output:
#include <forceCoeffs.H>
Classes
struct coeffDesc
class forceComponents
Public Member Functions
TypeName ("forceCoeffs")
forceCoeffs (const word &name, const Time &runTime, const dictionary &dict, const bool readFields=true)
forceCoeffs (const forceCoeffs &)=delete
void operator= (const forceCoeffs &)=delete
virtual ~forceCoeffs ()=default
virtual bool read (const dictionary &dict)
virtual bool execute ()
virtual bool write ()
Public Member Functions inherited from forces
TypeName ("forces")
forces (const word &name, const Time &runTime, const dictionary &dict, const bool readFields=true)
forces (const word &name, const objectRegistry &obr, const dictionary &dict, const bool readFields=true)
forces (const forces &)=delete
void operator= (const forces &)=delete
virtual ~forces ()=default
virtual void calcForcesMoments ()
virtual vector forceEff () const
virtual vector momentEff () const
Public Member Functions inherited from fvMeshFunctionObject
TypeName ("fvMeshFunctionObject")
fvMeshFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
fvMeshFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
virtual ~fvMeshFunctionObject ()=default
Public Member Functions inherited from regionFunctionObject
TypeName ("regionFunctionObject")
regionFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
regionFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
virtual ~regionFunctionObject ()=default
template<class ObjectType >
const ObjectType * lookupObjectPtr (const word &fieldName) const
template<class ObjectType >
ObjectType * lookupObjectRefPtr (const word &fieldName) const
Public Member Functions inherited from stateFunctionObject
stateFunctionObject (const word &name, const Time &runTime)
virtual ~stateFunctionObject ()=default
dictionary & propertyDict ()
bool foundProperty (const word &entryName) const
void clearTrigger ()
label getTrigger () const
bool setTrigger (const label triggeri)
bool getDict (const word &entryName, dictionary &dict) const
bool getObjectDict (const word &objectName, const word &entryName, dictionary &dict) const
template<class Type >
Type getProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getProperty (const word &entryName, Type &value) const
template<class Type >
void setProperty (const word &entryName, const Type &value)
template<class Type >
Type getObjectProperty (const word &objectName, const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getObjectProperty (const word &objectName, const word &entryName, Type &value) const
template<class Type >
void setObjectProperty (const word &objectName, const word &entryName, const Type &value)
template<class Type >
void setResult (const word &entryName, const Type &value)
template<class Type >
void setObjectResult (const word &objectName, const word &entryName, const Type &value)
template<class Type >
Type getResult (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
Type getObjectResult (const word &objectName, const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getObjectResult (const word &objectName, const word &entryName, Type &value) const
word resultType (const word &entryName) const
word objectResultType (const word &objectName, const word &entryName) const
wordList objectResultEntries () const
wordList objectResultEntries (const word &objectName) const
void writeResultEntries (Ostream &os) const
void writeResultEntries (const word &objectName, Ostream &os) const
void writeAllResultEntries (Ostream &os) const
Public Member Functions inherited from timeFunctionObject
timeFunctionObject (const word &name, const Time &runTime)
virtual ~timeFunctionObject ()=default
const Time & time () const
objectRegistry & storedObjects ()
const objectRegistry & storedObjects () const
Public Member Functions inherited from functionObject
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name, const bool withNamePrefix=defaultUseNamePrefix)
autoPtr< functionObject > clone () const
virtual ~functionObject ()=default
virtual const word & type () const =0
const word & name () const noexcept
bool useNamePrefix () const noexcept
bool useNamePrefix (bool on) noexcept
virtual bool execute (const label subIndex)
virtual bool end ()
virtual bool adjustTimeStep ()
virtual bool filesModified () const
virtual void updateMesh (const mapPolyMesh &mpm)
virtual void movePoints (const polyMesh &mesh)
Public Member Functions inherited from writeFile
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name="undefined", const bool writeToFile=true)
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name, const dictionary &dict, const bool writeToFile=true)
writeFile (const writeFile &wf)
virtual ~writeFile ()=default
virtual OFstream & file ()
virtual bool writeToFile () const
virtual bool canWriteToFile () const
virtual bool canResetFile () const
virtual bool canWriteHeader () const
virtual label charWidth () const
virtual void writeCommented (Ostream &os, const string &str) const
virtual void writeTabbed (Ostream &os, const string &str) const
virtual void writeHeader (Ostream &os, const string &str) const
virtual void writeCurrentTime (Ostream &os) const
virtual void writeBreak (Ostream &os) const
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
template<class Type >
void writeValue (Ostream &os, const Type &val) const
Protected Member Functions
void initialise ()
volVectorField & forceCoeff ()
volVectorField & momentCoeff ()
void reset ()
HashTable< coeffDesc > selectCoeffs () const
void calcForceCoeffs ()
void calcMomentCoeffs ()
List< scalar > integrateData (const List< Field< scalar > > &coeff) const
void createIntegratedDataFile ()
void writeIntegratedDataFileHeader (const word &header, OFstream &os) const
void writeIntegratedDataFile ()
Protected Member Functions inherited from forces
void setCoordinateSystem (const dictionary &dict, const word &e3Name=word::null, const word &e1Name=word::null)
volVectorField & force ()
volVectorField & moment ()
void initialise ()
void reset ()
tmp< symmTensorField > devRhoReff (const tensorField &gradUp, const label patchi) const
tmp< volScalarField > mu () const
tmp< volScalarField > rho () const
tmp< scalarField > rho (const label patchi) const
scalar rho (const volScalarField &p) const
void addToPatchFields (const label patchi, const vectorField &Md, const vectorField &fP, const vectorField &fV)
void addToInternalField (const labelList &cellIDs, const vectorField &Md, const vectorField &f)
void createIntegratedDataFiles ()
void writeIntegratedDataFileHeader (const word &header, OFstream &os) const
void writeIntegratedDataFiles ()
void writeIntegratedDataFile (const vector &pres, const vector &vis, const vector &internal, OFstream &os) const
void logIntegratedData (const string &descriptor, const vector &pres, const vector &vis, const vector &internal) const
Protected Member Functions inherited from fvMeshFunctionObject
fvMeshFunctionObject (const fvMeshFunctionObject &)=delete
void operator= (const fvMeshFunctionObject &)=delete
Protected Member Functions inherited from regionFunctionObject
virtual const objectRegistry & obr () const
template<class ObjectType >
bool foundObject (const word &fieldName) const
template<class ObjectType >
const ObjectType * cfindObject (const word &fieldName) const
template<class ObjectType >
const ObjectType * findObject (const word &fieldName) const
template<class ObjectType >
ObjectType * findObject (const word &fieldName)
template<class ObjectType >
ObjectType * getObjectPtr (const word &fieldName) const
template<class ObjectType >
const ObjectType & lookupObject (const word &fieldName) const
template<class ObjectType >
ObjectType & lookupObjectRef (const word &fieldName) const
template<class ObjectType >
bool store (word &fieldName, const tmp< ObjectType > &tfield, bool cacheable=false)
template<class ObjectType >
bool storeInDb (const word &fieldName, const tmp< ObjectType > &tfield, const objectRegistry &obr)
bool writeObject (const word &fieldName)
bool clearObject (const word &fieldName)
void clearObjects (const wordList &objNames)
regionFunctionObject (const regionFunctionObject &)=delete
void operator= (const regionFunctionObject &)=delete
Protected Member Functions inherited from stateFunctionObject
const functionObjects::properties & stateDict () const
functionObjects::properties & stateDict ()
stateFunctionObject (const stateFunctionObject &)=delete
void operator= (const stateFunctionObject &)=delete
Protected Member Functions inherited from timeFunctionObject
void clearOutputObjects (const wordList &objNames)
timeFunctionObject (const timeFunctionObject &)=delete
void operator= (const timeFunctionObject &)=delete
Protected Member Functions inherited from functionObject
word scopedName (const word &name) const
Protected Member Functions inherited from writeFile
void initStream (Ostream &os) const
fileName baseFileDir () const
fileName baseTimeDir () const
fileName filePath (const fileName &fName) const
virtual autoPtr< OFstream > newFile (const fileName &fName) const
virtual autoPtr< OFstream > newFileAtTime (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > newFileAtStartTime (const word &name) const
virtual void resetFile (const word &name)
Omanip< int > valueWidth (const label offset=0) const
void operator= (const writeFile &)=delete
virtual autoPtr< OFstream > createFile (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > createFile (const word &name) const
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &runTime, const dictionary &dict)
Public Attributes inherited from functionObject
bool log
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
static bool defaultUseNamePrefix
static word outputPrefix
Static Public Attributes inherited from writeFile
static label addChars = 8
Protected Attributes inherited from forces
vector sumPatchForcesP_
vector sumPatchForcesV_
vector sumPatchMomentsP_
vector sumPatchMomentsV_
vector sumInternalForces_
vector sumInternalMoments_
autoPtr< OFstream > forceFilePtr_
autoPtr< OFstream > momentFilePtr_
autoPtr< coordinateSystem > coordSysPtr_
labelHashSet patchSet_
scalar rhoRef_
scalar pRef_
word pName_
word UName_
word rhoName_
word fDName_
bool directForceDensity_
bool porosity_
bool writeFields_
bool initialised_
Protected Attributes inherited from fvMeshFunctionObject
const fvMesh & mesh_
Protected Attributes inherited from regionFunctionObject
word subRegistryName_
const objectRegistry & obr_
const objectRegistry * obrPtr_
Protected Attributes inherited from timeFunctionObject
const Time & time_
Protected Attributes inherited from writeFile
const objectRegistry & fileObr_
const fileName prefix_
word fileName_
autoPtr< OFstream > filePtr_
label writePrecision_
bool writeToFile_
bool updateHeader_
bool writtenHeader_
bool useUserTime_
scalar startTime_
Detailed Description
Computes force and moment coefficients over a given list of patches, and optionally over given porous zones. The following coefficients can be selected and output:
  Cd      | Drag coefficient
  Cs      | Side-force coefficient
  Cl      | Lift coefficient
  CmRoll  | Roll-moment coefficient
  CmPitch | Pitch-moment coefficient
  CmYaw   | Yaw-moment coefficient
The force coefficients can also be optionally output in terms of their front and rear axle constituents:
    Cd{f,r} = 0.5*Cd {+,-} CmRoll
    Cs{f,r} = 0.5*Cs {+,-} CmYaw
    Cl{f,r} = 0.5*Cl {+,-} CmPitch
where f and r represent front and rear axles, respectively.
Force and moment coefficients are output in their total and constituent components:
total force and moment coefficients
pressure contributions
viscous contributions
porous resistance contributions (optional)
Force and moment coefficients can be computed and output in:
the global Cartesian coordinate system (default)
a user-defined Cartesian coordinate system
Operands:
Operand Type Location
input - -
output file dat postProcessing/<FO>/<time>/<file>s
output field volVectorField <time>/<outField>s
where <file>s:
      coefficient.dat  | Integrated coefficients over all patches
where <outField>s:
      <namePrefix>:forceCoeff   | Force coefficient field
      <namePrefix>:momentCoeff  | Moment coefficient field
Usage
Minimal example by using system/controlDict.functions:
forceCoeffs1
{
    // Mandatory entries
    type                forceCoeffs;
    libs                (forces);
    patches             (<wordRes>); // (wall1 "(wall2|wall3)");
    magUInf             <scalar>;
    lRef                <scalar>;
    Aref                <scalar>;
    // Optional entries
    coefficients        (<wordHashSet>);
    directForceDensity  <bool>;
    porosity            <bool>;
    writeFields         <bool>;
    useNamePrefix       <bool>;
    // Conditional mandatory entries
        // Cartesian coordinate system specification when evaluating
        // force and moment coefficients, either of the below
        // Define the centre of rotation
        // with implicit directions e1=(1 0 0) and e3=(0 0 1)
        CofR            (0 0 0); // Centre of rotation
        // Define local coordinate system by origin + axes
        origin          (0 0 0);
        e1              (1 0 0);
        e3              (0 0 1); // (e1, e2) or (e2, e3) or (e3, e1)
        // General coordinate system specification (always cartesian)
        coordinateSystem
        {
            origin      (0 0 0);
            rotation
            {
                type    ...;
                ...
            }
        }
    // Conditional optional entries
        // if directForceDensity == true
        fD              <word>;
        // if directForceDensity == false
        p               <word>;
        U               <word>;
        rho             <word>;
        rhoInf          <scalar>; // redundant for incompressible-flow cases
        pRef            <scalar>;
    // Inherited entries
    ...
}
where the entries mean:
Property Description Type Reqd Deflt
type Type name: forceCoeffs word yes -
libs Library name: forces word yes -
patches Names of operand patches wordRes yes -
coefficients Names of operand coefficients wordHashSet no -
magUInf Reference velocity magnitude scalar yes -
lRef
Reference length scale for moment calculations
scalar yes -
Aref Reference area scalar yes -
directForceDensity
Flag to directly supply force density
bool no false
porosity Flag to include porosity contributions bool no false
writeFields Flag to write force and moment fields bool no false
useNamePrefix Flag to include prefix for field names bool no false
CofR Centre of rotation vector cndtnl -
origin Origin of coordinate system vector cndtnl -
e3 e3 coordinate axis vector cndtnl -
e1 e1 coordinate axis vector cndtnl -
coordinateSystem Coordinate system specifier dictionary cndtnl -
fD Name of force density field word cndtnl-no fD
p Name of pressure field word cndtnl-no p
U Name of velocity field word cndtnl-no U
rho Name of density field word cndtnl-no rho
rhoInf Value of reference density scalar cndtnl-yes -
pRef Value of reference pressure scalar cndtnl-no 0
Options for the coefficients entry:
      Cd      | Drag coefficient
      Cs      | Side-force coefficient
      Cl      | Lift coefficient
      CmRoll  | Roll-moment coefficient
      CmPitch | Pitch-moment coefficient
      CmYaw   | Yaw-moment coefficient
      Cd(f)   | Front-axle drag coefficient
      Cs(f)   | Front-axle side-force coefficient
      Cl(f)   | Front-axle lift coefficient
      Cd(r)   | Rear-axle drag coefficient
      Cs(r)   | Rear-axle side-force coefficient
      Cl(r)   | Rear-axle lift coefficient
The inherited entries are elaborated in:
functionObject.H
writeFile.H
coordinateSystem.H
forces.H
Note
rhoInf is always redundant for incompressible computations. That is, rhoInf is always equal to 1 in incompressible computations no matter which input value is assigned to rhoInf. The value of rhoInf is only used for compressible computations.
writeControl and writeInterval entries of function object do control when to output force and moment files and fields.
Input for force/moment coefficient directions require an origin and two orthogonal directions where the remaining orthogonal direction is automatically computed.
The default direction relations are shown below:
Property Description Alias Direction
dragDir Drag direction e1 (1 0 0)
sideDir Side force direction e2 (0 1 0)
liftDir Lift direction e3 (0 0 1)
rollAxis Roll axis e1 (1 0 0)
pitchAxis Pitch axis e2 (0 1 0)
yawAxis Yaw axis e3 (0 0 1)
If a coordinateSystem entry exists, it is taken in favour of CofR.
Source files
forceCoeffs.H
forceCoeffs.C
Definition at line 433 of file forceCoeffs.H.
Constructor & Destructor Documentation
forceCoeffs() [1/2]
forceCoeffs (const word & name, const Time & runTime, const dictionary & dict, const bool readFields = true)
Definition at line 268 of file forceCoeffs.C.
References dict, Foam::endl(), Foam::Info, forceCoeffs::read(), and forces::setCoordinateSystem().
forceCoeffs() [2/2]
forceCoeffs (const forceCoeffs &) delete
~forceCoeffs()
virtual ~forceCoeffs () virtual default
Member Function Documentation
initialise()
void initialise () protected
Definition at line 46 of file forceCoeffs.C.
forceCoeff()
Foam::volVectorField & forceCoeff () protected
Definition at line 57 of file forceCoeffs.C.
References Foam::dimless, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, IOobjectOption::REGISTER, and Foam::Zero.
momentCoeff()
Foam::volVectorField & momentCoeff () protected
Definition at line 86 of file forceCoeffs.C.
References Foam::dimless, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, IOobjectOption::REGISTER, and Foam::Zero.
reset()
void reset () protected
Definition at line 115 of file forceCoeffs.C.
References Foam::dimless, and Foam::Zero.
selectCoeffs()
Foam::HashTable< Foam::functionObjects::forceCoeffs::coeffDesc > selectCoeffs () const protected
Definition at line 126 of file forceCoeffs.C.
References forAllConstIters, and UPtrList< T >::front().
calcForceCoeffs()
void calcForceCoeffs () protected
Definition at line 152 of file forceCoeffs.C.
References Foam::dimForce, Foam::dimless, pDyn(), and Foam::sqr().
calcMomentCoeffs()
void calcMomentCoeffs () protected
Definition at line 176 of file forceCoeffs.C.
References Foam::dimForce, Foam::dimLength, Foam::dimless, pDyn(), and Foam::sqr().
integrateData()
List< scalar > integrateData (const List< Field< scalar > > & coeff) const protected
createIntegratedDataFile()
void createIntegratedDataFile () protected
Definition at line 200 of file forceCoeffs.C.
writeIntegratedDataFileHeader()
void writeIntegratedDataFileHeader (const word & header, OFstream & os) const protected
Definition at line 210 of file forceCoeffs.C.
References Foam::endl(), os(), and Foam::writeHeader().
writeIntegratedDataFile()
void writeIntegratedDataFile () protected
Definition at line 245 of file forceCoeffs.C.
References Foam::endl(), os(), and Foam::tab.
TypeName()
TypeName ("forceCoeffs")
operator=()
void operator= (const forceCoeffs &) delete
read()
bool read (const dictionary & dict) virtual
Reimplemented from forces.
Definition at line 296 of file forceCoeffs.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, Foam::Info, initialised_(), Foam::min(), Foam::nl, and forces::read().
Referenced by forceCoeffs::forceCoeffs().
execute()
bool execute () virtual
Reimplemented from forces.
Definition at line 377 of file forceCoeffs.C.
References forces::calcForcesMoments(), Foam::endl(), Foam::Info, Log, Foam::name(), Foam::nl, os(), Foam::tab, and Foam::type().
write()
bool write () virtual
Reimplemented from forces.
Definition at line 433 of file forceCoeffs.C.
References Foam::endl(), and Log.
The documentation for this class was generated from the following files:
src/functionObjects/forces/forceCoeffs/forceCoeffs.H
src/functionObjects/forces/forceCoeffs/forceCoeffs.C