OpenFOAM: barotropicCompressibilityModel Class Reference
barotropicCompressibilityModel Class Reference abstract
Abstract class for barotropic compressibility models.
#include <barotropicCompressibilityModel.H>
Public Member Functions
TypeName ("barotropicCompressibilityModel")
declareRunTimeSelectionTable (autoPtr, barotropicCompressibilityModel, dictionary,(const dictionary &compressibilityProperties, const volScalarField &gamma, const word &psiName),(compressibilityProperties, gamma, psiName))
barotropicCompressibilityModel (const dictionary &compressibilityProperties, const volScalarField &gamma, const word &psiName="psi")
virtual ~barotropicCompressibilityModel ()=default
const dictionary & compressibilityProperties () const
const volScalarField & psi () const
virtual void correct ()=0
virtual bool read (const dictionary &compressibilityProperties)=0
Static Public Member Functions
static autoPtr< barotropicCompressibilityModel > New (const dictionary &compressibilityProperties, const volScalarField &gamma, const word &psiName="psi")
Protected Member Functions
barotropicCompressibilityModel (const barotropicCompressibilityModel &)=delete
void operator= (const barotropicCompressibilityModel &)=delete
Protected Attributes
dictionary compressibilityProperties_
volScalarField psi_
const volScalarField & gamma_
Detailed Description
Abstract class for barotropic compressibility models.
Source files
barotropicCompressibilityModel.H
barotropicCompressibilityModel.C
newbarotropicCompressibilityModel.C
Definition at line 61 of file barotropicCompressibilityModel.H.
Constructor & Destructor Documentation
barotropicCompressibilityModel() [1/2]
barotropicCompressibilityModel (const barotropicCompressibilityModel &) protected delete
barotropicCompressibilityModel() [2/2]
barotropicCompressibilityModel (const dictionary & compressibilityProperties, const volScalarField & gamma, const word & psiName = "psi")
Definition at line 36 of file barotropicCompressibilityModel.C.
~barotropicCompressibilityModel()
virtual ~barotropicCompressibilityModel () virtual default
Member Function Documentation
operator=()
void operator= (const barotropicCompressibilityModel &) protected delete
TypeName()
TypeName ("barotropicCompressibilityModel")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , barotropicCompressibilityModel , dictionary , (const dictionary &compressibilityProperties, const volScalarField &gamma, const word &psiName) , (compressibilityProperties, gamma, psiName))
New()
Foam::autoPtr< Foam::barotropicCompressibilityModel > New (const dictionary & compressibilityProperties, const volScalarField & gamma, const word & psiName = "psi") static
Definition at line 27 of file barotropicCompressibilityModelNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, gamma, and Foam::Info.
compressibilityProperties()
const dictionary & compressibilityProperties () const inline
Definition at line 137 of file barotropicCompressibilityModel.H.
References barotropicCompressibilityModel::compressibilityProperties_.
psi()
const volScalarField & psi () const inline
Definition at line 143 of file barotropicCompressibilityModel.H.
References barotropicCompressibilityModel::psi_.
correct()
virtual void correct () pure virtual
Implemented in Chung, linear, and Wallis.
read()
bool read (const dictionary & compressibilityProperties) pure virtual
Implemented in Chung, linear, and Wallis.
Definition at line 61 of file barotropicCompressibilityModel.C.
Referenced by Chung::read(), linear::read(), and Wallis::read().
Member Data Documentation
compressibilityProperties_
dictionary compressibilityProperties_ protected
Definition at line 68 of file barotropicCompressibilityModel.H.
Referenced by barotropicCompressibilityModel::compressibilityProperties().
psi_
volScalarField psi_ protected
Definition at line 70 of file barotropicCompressibilityModel.H.
Referenced by linear::linear(), and barotropicCompressibilityModel::psi().
gamma_
const volScalarField& gamma_ protected
Definition at line 71 of file barotropicCompressibilityModel.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/barotropicCompressibilityModel/barotropicCompressibilityModel/barotropicCompressibilityModel.H
src/thermophysicalModels/barotropicCompressibilityModel/barotropicCompressibilityModel/barotropicCompressibilityModel.C
src/thermophysicalModels/barotropicCompressibilityModel/barotropicCompressibilityModel/barotropicCompressibilityModelNew.C