OpenFOAM: laplaceFilter Class Reference
laplaceFilter Class Reference
Laplace filter for LES.
#include <laplaceFilter.H>
Public Member Functions
TypeName ("laplace")
laplaceFilter (const fvMesh &mesh, scalar widthCoeff)
laplaceFilter (const fvMesh &mesh, const dictionary &)
virtual ~laplaceFilter ()=default
virtual void read (const dictionary &)
virtual tmp< volScalarField > operator() (const tmp< volScalarField > &) const
virtual tmp< volVectorField > operator() (const tmp< volVectorField > &) const
virtual tmp< volSymmTensorField > operator() (const tmp< volSymmTensorField > &) const
virtual tmp< volTensorField > operator() (const tmp< volTensorField > &) const
Public Member Functions inherited from LESfilter
TypeName ("LESfilter")
declareRunTimeSelectionTable (autoPtr, LESfilter, dictionary,(const fvMesh &mesh, const dictionary &LESfilterDict),(mesh, LESfilterDict))
LESfilter (const fvMesh &mesh)
virtual ~LESfilter ()=default
const fvMesh & mesh () const
Additional Inherited Members
Static Public Member Functions inherited from LESfilter
static autoPtr< LESfilter > New (const fvMesh &, const dictionary &, const word &filterDictName="filter")
Protected Member Functions inherited from LESfilter
template<class GeoFieldType >
void correctBoundaryConditions (const tmp< GeoFieldType > &tgf) const
Detailed Description
Laplace filter for LES.
Kernel                 as filter          as Test filter with ratio 2
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Box filter:            g = delta2/24  ->  g = delta2/6
Spherical box filter:  g = delta2/64  ->  g = delta2/16
Gaussian filter:       g = delta2/24  ->  g = delta2/6
Source files
laplaceFilter.H
laplaceFilter.C
Definition at line 54 of file laplaceFilter.H.
Constructor & Destructor Documentation
laplaceFilter() [1/2]
laplaceFilter (const fvMesh & mesh, scalar widthCoeff)
Definition at line 38 of file laplaceFilter.C.
References Foam::dimLength, LESfilter::mesh(), Foam::pow(), and GeometricField< Type, PatchField, GeoMesh >::ref().
laplaceFilter() [2/2]
laplaceFilter (const fvMesh & mesh, const dictionary & bd)
Definition at line 58 of file laplaceFilter.C.
References LESfilter::mesh(), Foam::pow(), and GeometricField< Type, PatchField, GeoMesh >::ref().
~laplaceFilter()
virtual ~laplaceFilter () virtual default
Member Function Documentation
TypeName()
TypeName ("laplace")
read()
void read (const dictionary & bd) virtual
Implements LESfilter.
Definition at line 83 of file laplaceFilter.C.
References Foam::type().
operator()() [1/4]
Foam::tmp< Foam::volScalarField > operator() (const tmp< volScalarField > & unFilteredField) const virtual
Implements LESfilter.
Definition at line 91 of file laplaceFilter.C.
References PtrList< T >::clear(), correctBoundaryConditions(), and Foam::fvc::laplacian().
operator()() [2/4]
Foam::tmp< Foam::volVectorField > operator() (const tmp< volVectorField > & unFilteredField) const virtual
Implements LESfilter.
Definition at line 107 of file laplaceFilter.C.
References PtrList< T >::clear(), correctBoundaryConditions(), and Foam::fvc::laplacian().
operator()() [3/4]
Foam::tmp< Foam::volSymmTensorField > operator() (const tmp< volSymmTensorField > & unFilteredField) const virtual
Implements LESfilter.
Definition at line 123 of file laplaceFilter.C.
References PtrList< T >::clear(), correctBoundaryConditions(), and Foam::fvc::laplacian().
operator()() [4/4]
Foam::tmp< Foam::volTensorField > operator() (const tmp< volTensorField > & unFilteredField) const virtual
Implements LESfilter.
Definition at line 139 of file laplaceFilter.C.
References PtrList< T >::clear(), correctBoundaryConditions(), and Foam::fvc::laplacian().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/LES/LESfilters/laplaceFilter/laplaceFilter.H
src/TurbulenceModels/turbulenceModels/LES/LESfilters/laplaceFilter/laplaceFilter.C