OpenFOAM: DynamicField< T, SizeMin > Class Template Reference
DynamicField< T, SizeMin > Class Template Reference
Dynamically sized Field.
#include <DynamicField.H>
Public Member Functions
constexpr DynamicField () noexcept
DynamicField (const label len)
DynamicField (const label len, const T &val)
DynamicField (const label len, const Foam::zero)
DynamicField (const DynamicField< T, SizeMin > &list)
template<int AnySizeMin>
DynamicField (const DynamicField< T, AnySizeMin > &list)
DynamicField (const UList< T > &list)
template<class Addr >
DynamicField (const IndirectListBase< T, Addr > &list)
DynamicField (List< T > &&content)
DynamicField (DynamicField< T, SizeMin > &&content)
template<int AnySizeMin>
DynamicField (DynamicField< T, AnySizeMin > &&content)
template<int AnySizeMin>
DynamicField (DynamicList< T, AnySizeMin > &&list)
DynamicField (const UList< T > &mapF, const labelUList &mapAddressing)
DynamicField (const UList< T > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
DynamicField (const UList< T > &mapF, const FieldMapper &map)
DynamicField (Istream &is)
tmp< DynamicField< T, SizeMin > > clone () const
label capacity () const noexcept
std::streamsize capacity_bytes () const noexcept
void setCapacity (const label len)
void setCapacity_nocopy (const label len)
void setCapacity_unsafe (const label len) noexcept
void reserve (const label len)
void reserve_nocopy (const label len)
void resize (const label len)
void resize (const label len, const T &val)
void resize_nocopy (const label len)
void setSize (const label n)
void setSize (const label n, const T &val)
void clear () noexcept
void clearStorage ()
label expandStorage () noexcept
void shrinkStorage ()
DynamicField< T, SizeMin > & shrink ()
template<int AnySizeMin>
void swap (DynamicField< T, AnySizeMin > &other)
template<int AnySizeMin>
void swap (DynamicList< T, AnySizeMin > &other)
void transfer (List< T > &list)
template<int AnySizeMin>
void transfer (DynamicList< T, AnySizeMin > &list)
template<int AnySizeMin>
void transfer (DynamicField< T, AnySizeMin > &list)
template<class... Args>
T & emplace_back (Args &&... args)
void push_back (const T &val)
void push_back (T &&val)
void push_back (const UList< T > &list)
void pop_back (label n=1)
Istream & readList (Istream &is)
void operator= (const T &val)
void operator= (const Foam::zero)
void operator= (const UList< T > &list)
void operator= (const DynamicField< T, SizeMin > &list)
template<class Addr >
void operator= (const IndirectListBase< T, Addr > &rhs)
void operator= (List< T > &&list)
template<int AnySizeMin>
void operator= (DynamicList< T, AnySizeMin > &&list)
void operator= (DynamicField< T, SizeMin > &&list)
template<int AnySizeMin>
void operator= (DynamicField< T, AnySizeMin > &&list)
T & operator() (const label i)
void append (const T &val)
void append (T &&val)
void append (const UList< T > &list)
Public Member Functions inherited from Field< T >
constexpr Field () noexcept
Field (const label len)
Field (const label len, const T &val)
Field (const label len, const Foam::zero)
Field (const Foam::one, const T &val)
Field (const Foam::one, T &&val)
Field (const Foam::one, const Foam::zero)
Field (const Field< T > &fld)
Field (const UList< T > &list)
Field (const IndirectListBase< T, Addr > &list)
Field (Field< T > &&fld)
Field (List< T > &&list)
Field (DynamicList< T, SizeMin > &&list)
Field (const UList< T > &mapF, const labelUList &mapAddressing)
Field (const tmp< Field< T > > &tmapF, const labelUList &mapAddressing)
Field (const UList< T > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Field (const tmp< Field< T > > &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Field (const UList< T > &mapF, const FieldMapper &map, const bool applyFlip=true)
Field (const UList< T > &mapF, const FieldMapper &map, const T &defaultValue, const bool applyFlip=true)
Field (const UList< T > &mapF, const FieldMapper &map, const UList< T > &defaultValues, const bool applyFlip=true)
Field (const tmp< Field< T > > &tmapF, const FieldMapper &map, const bool applyFlip=true)
Field (const tmp< Field< T > > &tmapF, const FieldMapper &map, const T &defaultValue, const bool applyFlip=true)
Field (const tmp< Field< T > > &tmapF, const FieldMapper &map, const UList< T > &defaultValues, const bool applyFlip=true)
Field (Field< T > &fld, bool reuse)
Field (const tmp< Field< T > > &tfld)
Field (Istream &is)
Field (const entry &e, const label len)
Field (const word &key, const dictionary &dict, const label len, IOobjectOption::readOption readOpt=IOobjectOption::MUST_READ)
tmp< Field< T > > clone () const
void assign (const entry &e, const label len)
bool assign (const word &key, const dictionary &dict, const label len, IOobjectOption::readOption readOpt=IOobjectOption::MUST_READ)
void map (const UList< T > &mapF, const labelUList &mapAddressing)
void map (const tmp< Field< T > > &tmapF, const labelUList &mapAddressing)
void map (const UList< T > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
void map (const tmp< Field< T > > &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
void map (const UList< T > &mapF, const FieldMapper &map, const bool applyFlip=true)
void map (const tmp< Field< T > > &tmapF, const FieldMapper &map, const bool applyFlip=true)
void autoMap (const FieldMapper &map, const bool applyFlip=true)
void rmap (const UList< T > &mapF, const labelUList &mapAddressing)
void rmap (const tmp< Field< T > > &tmapF, const labelUList &mapAddressing)
void rmap (const UList< T > &mapF, const labelUList &mapAddressing, const UList< scalar > &weights)
void rmap (const tmp< Field< T > > &tmapF, const labelUList &mapAddressing, const UList< scalar > &weights)
void negate ()
void normalise ()
void normalise ()
void normalise ()
void normalise ()
void normalise ()
tmp< Field< cmptType > > component (const direction) const
void replace (const direction, const UList< cmptType > &)
void replace (const direction, const tmp< Field< cmptType > > &)
void replace (const direction, const cmptType &)
void clamp_min (const T &lower)
void clamp_max (const T &upper)
void clamp_range (const T &lower, const T &upper)
void clamp_range (const MinMax< T > &range)
VSForm block (const label start) const
tmp< Field< T > > T () const
void writeEntry (const word &keyword, Ostream &os) const
SubField< T > slice (const label pos, label len=-1)
const SubField< T > slice (const label pos, label len=-1) const
SubField< T > slice (const labelRange &range)
const SubField< T > slice (const labelRange &range) const
void operator= (const Field< T > &)
void operator= (const tmp< Field< T > > &)
void operator= (const UList< T > &rhs)
void operator= (const SubField< T > &rhs)
void operator= (const IndirectListBase< T, Addr > &rhs)
void operator= (Field< T > &&rhs)
void operator= (List< T > &&rhs)
void operator= (DynamicList< T, SizeMin > &&rhs)
void operator= (const T &val)
void operator= (const Foam::zero)
void operator= (const VectorSpace< Form, Cmpt, nCmpt > &)
void operator= (const tmp< Field > &rhs)
void operator+= (const UList< T > &)
void operator+= (const tmp< Field< T > > &)
void operator+= (const T &)
void operator-= (const UList< T > &)
void operator-= (const tmp< Field< T > > &)
void operator-= (const T &)
void operator*= (const UList< scalar > &)
void operator*= (const tmp< Field< scalar > > &)
void operator*= (const scalar &)
void operator/= (const UList< scalar > &)
void operator/= (const tmp< Field< scalar > > &)
void operator/= (const scalar &)
Public Member Functions inherited from FieldBase
constexpr FieldBase () noexcept
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Public Member Functions inherited from List< T >
constexpr List () noexcept
List (const label len)
List (const label len, const T &val)
List (const label len, const Foam::zero)
List (const Foam::one, const T &val)
List (const Foam::one, T &&val)
List (const Foam::one, const Foam::zero)
List (const List< T > &a)
List (const UList< T > &a)
List (List< T > &a, bool reuse)
List (const UList< T > &list, const labelUList &indices)
template<unsigned N>
List (const UList< T > &list, const FixedList< label, N > &indices)
template<unsigned N>
List (const FixedList< T, N > &list)
List (const PtrList< T > &list)
List (const SLList< T > &list)
template<class Addr >
List (const IndirectListBase< T, Addr > &list)
List (std::initializer_list< T > list)
List (List< T > &&list)
template<int SizeMin>
List (DynamicList< T, SizeMin > &&list)
List (SLList< T > &&list)
List (Istream &is)
autoPtr< List< T > > clone () const
~List ()
void clear ()
void resize (const label len)
void resize (const label len, const T &val)
void resize_nocopy (const label len)
void setSize (const label n)
void setSize (const label n, const T &val)
void transfer (List< T > &list)
template<int SizeMin>
void transfer (DynamicList< T, SizeMin > &list)
T & newElmt (const label i)
template<class... Args>
T & emplace_back (Args &&... args)
void push_back (const T &val)
void push_back (T &&val)
void push_back (const UList< T > &list)
template<class Addr >
void push_back (const IndirectListBase< T, Addr > &list)
label push_uniq (const T &val)
void pop_back (label n=1)
void operator= (const UList< T > &a)
void operator= (const List< T > &list)
void operator= (const SLList< T > &list)
template<class Addr >
void operator= (const IndirectListBase< T, Addr > &list)
template<unsigned N>
void operator= (const FixedList< T, N > &list)
void operator= (std::initializer_list< T > list)
void operator= (const T &val)
void operator= (const Foam::zero)
void operator= (List< T > &&list)
template<int SizeMin>
void operator= (DynamicList< T, SizeMin > &&list)
void operator= (SLList< T > &&list)
Istream & readList (Istream &is)
void shallowCopy (const UList< T > &)=delete
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type set (const label i, bool val=true)
void append (const T &val)
void append (T &&val)
void append (const UList< T > &list)
template<class Addr >
void append (const IndirectListBase< T, Addr > &list)
label appendUniq (const T &val)
Istream & readList (Istream &is)
void resize (const label newLen)
Istream & readList (Istream &is)
Public Member Functions inherited from UList< T >
UList (const UList< T > &)=default
constexpr UList () noexcept
UList (T *__restrict__ v, const label len) noexcept
label fcIndex (const label i) const noexcept
label rcIndex (const label i) const noexcept
const T & fcValue (const label i) const
T & fcValue (const label i)
const T & rcValue (const label i) const
T & rcValue (const label i)
const T * cdata () const noexcept
T * data () noexcept
const char * cdata_bytes () const noexcept
char * data_bytes () noexcept
T & front ()
const T & front () const
T & back ()
const T & back () const
std::streamsize size_bytes () const noexcept
std::streamsize byteSize () const
void checkStart (const label start) const
void checkSize (const label size) const
void checkRange (const label start, const label len) const
void checkIndex (const label i) const
bool uniform () const
label find (const T &val, label pos=0) const
label rfind (const T &val, label pos=-1) const
bool contains (const T &val, label pos=0) const
void moveFirst (const label i)
void moveLast (const label i)
void swapFirst (const label i)
void swapLast (const label i)
void shallowCopy (const UList< T > &list)
void deepCopy (const UList< T > &list)
template<class Addr >
void deepCopy (const IndirectListBase< T, Addr > &list)
SubList< T > slice (const label pos, label len=-1)
const SubList< T > slice (const label pos, label len=-1) const
SubList< T > slice (const labelRange &range)
const SubList< T > slice (const labelRange &range) const
T & operator[] (const label i)
const T & operator[] (const label i) const
operator const Foam::List< T > & () const
void operator= (const T &val)
void operator= (const Foam::zero)
iterator begin () noexcept
iterator end () noexcept
iterator begin (const label i) noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
const_iterator begin () const noexcept
const_iterator end () const noexcept
const_iterator cbegin (const label i) const noexcept
const_iterator begin (const label i) const noexcept
reverse_iterator rbegin ()
reverse_iterator rend ()
const_reverse_iterator crbegin () const
const_reverse_iterator crend () const
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
bool empty () const noexcept
label size () const noexcept
void swap (UList< T > &list)
bool operator== (const UList< T > &a) const
bool operator!= (const UList< T > &a) const
bool operator< (const UList< T > &list) const
bool operator> (const UList< T > &a) const
bool operator<= (const UList< T > &a) const
bool operator>= (const UList< T > &a) const
Istream & readList (Istream &is)
void writeEntry (const word &keyword, Ostream &os) const
Ostream & writeList (Ostream &os, const label shortLen=0) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type test (const label i) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type get (const label i) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type unset (const label i)
T & first ()
const T & first () const
T & last ()
const T & last () const
bool found (const T &val, label pos=0) const
Istream & readList (Istream &is)
Ostream & writeList (Ostream &os, const label) const
const bool & operator[] (const label i) const
UPstream::commsStruct & operator[] (const label procID)
const UPstream::commsStruct & operator[] (const label procID) const
Foam::UPstream::commsStruct & operator[] (const label procID)
const Foam::UPstream::commsStruct & operator[] (const label procID) const
Ostream & writeList (Ostream &os, const label) const
Istream & readList (Istream &is)
Static Public Member Functions
static const DynamicField< T, SizeMin > & null ()
static constexpr label min_size () noexcept
Static Public Member Functions inherited from Field< T >
static const Field< T > & null ()
static autoPtr< Field< T > > New (Istream &is)
static tmp< Field< T > > NewCalculatedType (const Field< Type2 > &f)
Static Public Member Functions inherited from List< T >
static const List< T > & null ()
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
static constexpr label max_size () noexcept
Friends
Istream & operator>> (Istream &is, DynamicField< T, SizeMin > &rhs)
Ostream & operator (Ostream &os, const DynamicField< T, SizeMin > &rhs)
Additional Inherited Members
Public Types inherited from Field< T >
typedef pTraits< T >::cmptType cmptType
typedef SubField< T > subField
Public Types inherited from List< T >
typedef SubList< T > subList
Public Types inherited from UList< T >
typedef T value_type
typedef T * pointer
typedef const T * const_pointer
typedef T & reference
typedef const T & const_reference
typedef T * iterator
typedef const T * const_iterator
typedef label size_type
typedef label difference_type
typedef std::reverse_iterator< iterator > reverse_iterator
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
Static Public Attributes inherited from FieldBase
static const char *const typeName
static bool allowConstructFromLargerSize = false
Protected Member Functions inherited from UList< T >
void setAddressableSize (const label n) noexcept
void size (const label n)
void writeEntry (Ostream &os) const
labelRange validateRange (const labelRange &requestedRange) const
UList< T > & operator= (const UList< T > &)=delete
void writeEntry (Ostream &os) const
void writeEntry (Ostream &os) const
Detailed Description
template<class T, int SizeMin = 64>
class Foam::DynamicField< T, SizeMin >
Dynamically sized Field.
Source files
DynamicField.H
DynamicFieldI.H
Definition at line 58 of file DynamicField.H.
Constructor & Destructor Documentation
DynamicField() [1/16]
template<class T , int SizeMin> constexpr DynamicField () inline constexpr noexcept
Definition at line 125 of file DynamicFieldI.H.
DynamicField() [2/16]
template<class T , int SizeMin> DynamicField (const label len) inline explicit
Definition at line 133 of file DynamicFieldI.H.
DynamicField() [3/16]
template<class T , int SizeMin> DynamicField (const label len, const T & val) inline
Definition at line 143 of file DynamicFieldI.H.
DynamicField() [4/16]
template<class T , int SizeMin> DynamicField (const label len, const Foam::zero) inline
Definition at line 155 of file DynamicFieldI.H.
DynamicField() [5/16]
template<class T , int SizeMin> DynamicField (const DynamicField< T, SizeMin > & list) inline
Definition at line 167 of file DynamicFieldI.H.
DynamicField() [6/16]
template<class T , int SizeMin> template<int AnySizeMin> DynamicField (const DynamicField< T, AnySizeMin > & list) inline
Definition at line 179 of file DynamicFieldI.H.
DynamicField() [7/16]
template<class T , int SizeMin> DynamicField (const UList< T > & list) inline explicit
Definition at line 190 of file DynamicFieldI.H.
DynamicField() [8/16]
template<class T , int SizeMin> template<class Addr > DynamicField (const IndirectListBase< T, Addr > & list) inline explicit
Definition at line 202 of file DynamicFieldI.H.
DynamicField() [9/16]
template<class T , int SizeMin> DynamicField (List< T > && content) inline explicit
Definition at line 213 of file DynamicFieldI.H.
DynamicField() [10/16]
template<class T , int SizeMin> DynamicField (DynamicField< T, SizeMin > && content) inline
Definition at line 238 of file DynamicFieldI.H.
DynamicField() [11/16]
template<class T , int SizeMin> template<int AnySizeMin> DynamicField (DynamicField< T, AnySizeMin > && content) inline
Definition at line 252 of file DynamicFieldI.H.
DynamicField() [12/16]
template<class T , int SizeMin> template<int AnySizeMin> DynamicField (DynamicList< T, AnySizeMin > && list) inline
Definition at line 225 of file DynamicFieldI.H.
DynamicField() [13/16]
template<class T , int SizeMin> DynamicField (const UList< T > & mapF, const labelUList & mapAddressing) inline
Definition at line 265 of file DynamicFieldI.H.
DynamicField() [14/16]
template<class T , int SizeMin> DynamicField (const UList< T > & mapF, const labelListList & mapAddressing, const scalarListList & weights) inline
Definition at line 277 of file DynamicFieldI.H.
DynamicField() [15/16]
template<class T , int SizeMin> DynamicField (const UList< T > & mapF, const FieldMapper & map) inline
Definition at line 290 of file DynamicFieldI.H.
DynamicField() [16/16]
template<class T , int SizeMin> DynamicField (Istream & is) inline explicit
Definition at line 302 of file DynamicFieldI.H.
Member Function Documentation
null()
template<class T , int SizeMin = 64> static const DynamicField< T, SizeMin > & null () inline static
Definition at line 96 of file DynamicField.H.
clone()
template<class T , int SizeMin> Foam::tmp< Foam::DynamicField< T, SizeMin > > clone () const inline
Definition at line 311 of file DynamicFieldI.H.
References Foam::New().
min_size()
template<class T , int SizeMin = 64> static constexpr label min_size () inline static constexpr noexcept
Definition at line 179 of file DynamicField.H.
capacity()
template<class T , int SizeMin = 64> label capacity () const inline noexcept
Definition at line 182 of file DynamicField.H.
capacity_bytes()
template<class T , int SizeMin> std::streamsize capacity_bytes () const inline noexcept
Definition at line 321 of file DynamicFieldI.H.
References T.
setCapacity()
template<class T , int SizeMin> void setCapacity (const label len) inline
Definition at line 328 of file DynamicFieldI.H.
setCapacity_nocopy()
template<class T , int SizeMin> void setCapacity_nocopy (const label len) inline
Definition at line 338 of file DynamicFieldI.H.
setCapacity_unsafe()
template<class T , int SizeMin> void setCapacity_unsafe (const label len) inline noexcept
Definition at line 348 of file DynamicFieldI.H.
reserve()
template<class T , int SizeMin> void reserve (const label len) inline
Definition at line 358 of file DynamicFieldI.H.
reserve_nocopy()
template<class T , int SizeMin> void reserve_nocopy (const label len) inline
Definition at line 368 of file DynamicFieldI.H.
resize() [1/2]
template<class T , int SizeMin> void resize (const label len) inline
Definition at line 378 of file DynamicFieldI.H.
Referenced by DynamicField< T, SizeMin >::setSize(), and DynamicField< T, SizeMin >::setSize().
resize() [2/2]
template<class T , int SizeMin> void resize (const label len, const T & val) inline
Definition at line 398 of file DynamicFieldI.H.
References resize(), and UList< T >::size().
resize_nocopy()
template<class T , int SizeMin> void resize_nocopy (const label len) inline
Definition at line 388 of file DynamicFieldI.H.
setSize() [1/2]
template<class T , int SizeMin = 64> void setSize (const label n) inline
Definition at line 232 of file DynamicField.H.
References DynamicField< T, SizeMin >::resize().
setSize() [2/2]
template<class T , int SizeMin = 64> void setSize (const label n, const T & val) inline
Definition at line 235 of file DynamicField.H.
References DynamicField< T, SizeMin >::resize().
clear()
template<class T , int SizeMin> void clear () inline noexcept
Definition at line 417 of file DynamicFieldI.H.
References UList< T >::setAddressableSize().
clearStorage()
template<class T , int SizeMin> void clearStorage () inline
Definition at line 424 of file DynamicFieldI.H.
References List< T >::clear().
expandStorage()
template<class T , int SizeMin> Foam::label expandStorage () inline noexcept
Definition at line 432 of file DynamicFieldI.H.
References UList< T >::setAddressableSize(), and UList< T >::size().
shrinkStorage()
template<class T , int SizeMin> void shrinkStorage () inline
Definition at line 444 of file DynamicFieldI.H.
References List< T >::resize(), UList< T >::setAddressableSize(), and UList< T >::size().
shrink()
template<class T , int SizeMin> Foam::DynamicField< T, SizeMin > & shrink () inline
Definition at line 461 of file DynamicFieldI.H.
swap() [1/2]
template<class T , int SizeMin> template<int AnySizeMin> void swap (DynamicField< T, AnySizeMin > & other) inline
Definition at line 470 of file DynamicFieldI.H.
References UList< T >::swap().
swap() [2/2]
template<class T , int SizeMin> template<int AnySizeMin> void swap (DynamicList< T, AnySizeMin > & other) inline
Definition at line 494 of file DynamicFieldI.H.
References UList< T >::swap().
transfer() [1/3]
template<class T , int SizeMin> void transfer (List< T > & list) inline
Definition at line 521 of file DynamicFieldI.H.
References UPtrList< T >::size(), and List< Type >::transfer().
transfer() [2/3]
template<class T , int SizeMin> template<int AnySizeMin> void transfer (DynamicList< T, AnySizeMin > & list) inline
Definition at line 531 of file DynamicFieldI.H.
References List< Type >::transfer().
transfer() [3/3]
template<class T , int SizeMin> template<int AnySizeMin> void transfer (DynamicField< T, AnySizeMin > & list) inline
Definition at line 556 of file DynamicFieldI.H.
References List< Type >::transfer().
emplace_back()
template<class T , int SizeMin> template<class... Args> T & emplace_back (Args &&... args) inline
Definition at line 581 of file DynamicFieldI.H.
References args, resize(), UList< T >::size(), and T.
push_back() [1/3]
template<class T , int SizeMin> void push_back (const T & val) inline
Definition at line 597 of file DynamicFieldI.H.
References resize(), and UList< T >::size().
Referenced by DynamicField< T, SizeMin >::append(), DynamicField< T, SizeMin >::append(), and DynamicField< T, SizeMin >::append().
push_back() [2/3]
template<class T , int SizeMin> void push_back (T && val) inline
Definition at line 610 of file DynamicFieldI.H.
References resize(), and UList< T >::size().
push_back() [3/3]
template<class T , int SizeMin> void push_back (const UList< T > & list) inline
Definition at line 623 of file DynamicFieldI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, resize(), UList< T >::size(), UPtrList< T >::size(), and T.
pop_back()
template<class T , int SizeMin> void pop_back (label n = 1) inline
Definition at line 646 of file DynamicFieldI.H.
References clear(), n, and resize().
readList()
template<class T , int SizeMin> Foam::Istream & readList (Istream & is) inline
Definition at line 784 of file DynamicFieldI.H.
References UPtrList< T >::swap().
operator=() [1/9]
template<class T , int SizeMin> void operator= (const T & val) inline
Definition at line 677 of file DynamicFieldI.H.
References UList< T >::operator=().
operator=() [2/9]
template<class T , int SizeMin> void operator= (const Foam::zero) inline
Definition at line 687 of file DynamicFieldI.H.
References UList< T >::operator=(), and Foam::Zero.
operator=() [3/9]
template<class T , int SizeMin> void operator= (const UList< T > & list) inline
Definition at line 697 of file DynamicFieldI.H.
operator=() [4/9]
template<class T , int SizeMin> void operator= (const DynamicField< T, SizeMin > & list) inline
Definition at line 707 of file DynamicFieldI.H.
operator=() [5/9]
template<class T , int SizeMin> template<class Addr > void operator= (const IndirectListBase< T, Addr > & rhs) inline
if (static_cast<const UList<T>*>(this) == static_cast<const UList<T>*>(&list.values()))
Definition at line 723 of file DynamicFieldI.H.
operator=() [6/9]
template<class T , int SizeMin> void operator= (List< T > && list) inline
Definition at line 740 of file DynamicFieldI.H.
operator=() [7/9]
template<class T , int SizeMin> template<int AnySizeMin> void operator= (DynamicList< T, AnySizeMin > && list) inline
Definition at line 772 of file DynamicFieldI.H.
operator=() [8/9]
template<class T , int SizeMin> void operator= (DynamicField< T, SizeMin > && list) inline
Definition at line 750 of file DynamicFieldI.H.
operator=() [9/9]
template<class T , int SizeMin> template<int AnySizeMin> void operator= (DynamicField< T, AnySizeMin > && list) inline
Definition at line 761 of file DynamicFieldI.H.
operator()()
template<class T , int SizeMin> T & operator() (const label i) inline
Definition at line 662 of file DynamicFieldI.H.
References resize().
append() [1/3]
template<class T , int SizeMin = 64> void append (const T & val) inline
Definition at line 362 of file DynamicField.H.
References DynamicField< T, SizeMin >::push_back().
append() [2/3]
template<class T , int SizeMin = 64> void append (T && val) inline
Definition at line 366 of file DynamicField.H.
References DynamicField< T, SizeMin >::push_back().
append() [3/3]
template<class T , int SizeMin = 64> void append (const UList< T > & list) inline
Definition at line 370 of file DynamicField.H.
References DynamicField< T, SizeMin >::push_back().
Friends And Related Symbol Documentation
operator>>
template<class T , int SizeMin = 64> Istream & operator>> (Istream & is, DynamicField< T, SizeMin > & rhs) friend
operator
template<class T , int SizeMin = 64> Ostream & operator (Ostream & os, const DynamicField< T, SizeMin > & rhs) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/fields/Fields/DynamicField/DynamicField.H
src/OpenFOAM/fields/Fields/DynamicField/DynamicFieldI.H