OpenFOAM: mixtureKEpsilon< BasicTurbulenceModel > Class Template Reference
mixtureKEpsilon< BasicTurbulenceModel > Class Template Reference
Turbulence models » RAS turbulence
Mixture k-epsilon turbulence model for two-phase gas-liquid systems.
#include <mixtureKEpsilon.H>
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from linearViscousStress< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("mixtureKEpsilon")
mixtureKEpsilon (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
virtual ~mixtureKEpsilon ()=default
virtual bool read ()
virtual tmp< volScalarField > k () const
virtual tmp< volScalarField > epsilon () const
virtual void correct ()
Public Member Functions inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
eddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~eddyViscosity ()=default
virtual tmp< volScalarField > nut () const
virtual tmp< scalarField > nut (const label patchi) const
virtual tmp< volSymmTensorField > R () const
virtual void validate ()
Public Member Functions inherited from linearViscousStress< BasicTurbulenceModel >
linearViscousStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~linearViscousStress ()=default
virtual tmp< volSymmTensorField > devRhoReff () const
virtual tmp< volSymmTensorField > devRhoReff (const volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Protected Member Functions
wordList epsilonBoundaryTypes (const volScalarField &epsilon) const
void correctInletOutlet (volScalarField &vsf, const volScalarField &refVsf) const
void initMixtureFields ()
virtual void correctNut ()
tmp< volScalarField > Ct2 () const
tmp< volScalarField > rholEff () const
tmp< volScalarField > rhogEff () const
tmp< volScalarField > rhom () const
tmp< volScalarField > mix (const volScalarField &fc, const volScalarField &fd) const
tmp< volScalarField > mixU (const volScalarField &fc, const volScalarField &fd) const
tmp< surfaceScalarField > mixFlux (const surfaceScalarField &fc, const surfaceScalarField &fd) const
tmp< volScalarField > bubbleG () const
virtual tmp< fvScalarMatrix > kSource () const
virtual tmp< fvScalarMatrix > epsilonSource () const
tmp< volScalarField > DkEff (const volScalarField &nutm) const
tmp< volScalarField > DepsilonEff (const volScalarField &nutm) const
Protected Attributes
dimensionedScalar Cmu_
dimensionedScalar C1_
dimensionedScalar C2_
dimensionedScalar C3_
dimensionedScalar Cp_
dimensionedScalar sigmak_
dimensionedScalar sigmaEps_
volScalarField k_
volScalarField epsilon_
autoPtr< volScalarField > Ct2_
autoPtr< volScalarField > rhom_
autoPtr< volScalarField > km_
autoPtr< volScalarField > epsilonm_
Protected Attributes inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
volScalarField nut_
Detailed Description
template<class BasicTurbulenceModel>
class Foam::RASModels::mixtureKEpsilon< BasicTurbulenceModel >
Mixture k-epsilon turbulence model for two-phase gas-liquid systems.
The basic structure of the model is based on:
    Behzadi, A., Issa, R. I., & Rusche, H. (2004).
    Modelling of dispersed bubble and droplet flow at high phase fractions.
    Chemical Engineering Science, 59(4), 759-770.
but an effective density for the gas is used in the averaging and an alternative model for bubble-generated turbulence from:
    Lahey Jr, R. T. (2005).
    The simulation of multidimensional multiphase flows.
    Nuclear Engineering and Design, 235(10), 1043-1060.
The default model coefficients are
    mixtureKEpsilonCoeffs
    {
        Cmu         0.09;
        C1          1.44;
        C2          1.92;
        C3          C2;
        sigmak      1.0;
        sigmaEps    1.3;
    }
Source files
mixtureKEpsilon.H
mixtureKEpsilon.C
Definition at line 82 of file mixtureKEpsilon.H.
Member Typedef Documentation
alphaField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 200 of file mixtureKEpsilon.H.
rhoField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 201 of file mixtureKEpsilon.H.
transportModel
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 202 of file mixtureKEpsilon.H.
Constructor & Destructor Documentation
mixtureKEpsilon()
template<class BasicTurbulenceModel > mixtureKEpsilon (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Definition at line 42 of file mixtureKEpsilon.C.
References Foam::bound(), mixtureKEpsilon< BasicTurbulenceModel >::epsilon_, mixtureKEpsilon< BasicTurbulenceModel >::k_, and Foam::type().
~mixtureKEpsilon()
template<class BasicTurbulenceModel > virtual ~mixtureKEpsilon () virtual default
Member Function Documentation
epsilonBoundaryTypes()
template<class BasicTurbulenceModel > wordList epsilonBoundaryTypes (const volScalarField & epsilon) const protected
Definition at line 168 of file mixtureKEpsilon.C.
References epsilon, and forAll.
correctInletOutlet()
template<class BasicTurbulenceModel > void correctInletOutlet (volScalarField & vsf, const volScalarField & refVsf) const protected
Definition at line 190 of file mixtureKEpsilon.C.
References forAll.
initMixtureFields()
template<class BasicTurbulenceModel > void initMixtureFields () protected
Definition at line 218 of file mixtureKEpsilon.C.
References IOobjectOption::AUTO_WRITE, GeometricField< Type, PatchField, GeoMesh >::boundaryField(), and IOobjectOption::READ_IF_PRESENT.
correctNut()
template<class BasicTurbulenceModel > void correctNut () protected virtual
Implements eddyViscosity< RASModel< BasicTurbulenceModel > >.
Definition at line 329 of file mixtureKEpsilon.C.
References options::New(), and Foam::sqr().
Ct2()
template<class BasicTurbulenceModel > tmp< volScalarField > Ct2 () const protected
Definition at line 371 of file mixtureKEpsilon.C.
References beta(), Foam::exp(), fluid, Foam::mag(), liquid::rho(), Foam::sqr(), and Foam::sqrt().
rholEff()
template<class BasicTurbulenceModel > tmp< volScalarField > rholEff () const protected
Definition at line 398 of file mixtureKEpsilon.C.
References fluid.
rhogEff()
template<class BasicTurbulenceModel > tmp< volScalarField > rhogEff () const protected
Definition at line 407 of file mixtureKEpsilon.C.
References fluid.
rhom()
template<class BasicTurbulenceModel > tmp< volScalarField > rhom () const protected
Definition at line 420 of file mixtureKEpsilon.C.
References alphal.
mix()
template<class BasicTurbulenceModel > tmp< volScalarField > mix (const volScalarField & fc, const volScalarField & fd) const protected
Definition at line 430 of file mixtureKEpsilon.C.
References alphal.
mixU()
template<class BasicTurbulenceModel > tmp< volScalarField > mixU (const volScalarField & fc, const volScalarField & fd) const protected
Definition at line 444 of file mixtureKEpsilon.C.
References alphal.
mixFlux()
template<class BasicTurbulenceModel > tmp< surfaceScalarField > mixFlux (const surfaceScalarField & fc, const surfaceScalarField & fd) const protected
Definition at line 460 of file mixtureKEpsilon.C.
References alphal, and Foam::fvc::interpolate().
bubbleG()
template<class BasicTurbulenceModel > tmp< volScalarField > bubbleG () const protected
Definition at line 482 of file mixtureKEpsilon.C.
References drag, fluid, Foam::mag(), Foam::pow(), Foam::pow3(), and liquid::rho().
kSource()
template<class BasicTurbulenceModel > tmp< fvScalarMatrix > kSource () const protected virtual
Definition at line 520 of file mixtureKEpsilon.C.
References Foam::fvm::Su().
epsilonSource()
template<class BasicTurbulenceModel > tmp< fvScalarMatrix > epsilonSource () const protected virtual
Definition at line 527 of file mixtureKEpsilon.C.
References Foam::fvm::Su().
DkEff()
template<class BasicTurbulenceModel > tmp< volScalarField > DkEff (const volScalarField & nutm) const inline protected
Definition at line 173 of file mixtureKEpsilon.H.
References mixtureKEpsilon< BasicTurbulenceModel >::sigmak_.
DepsilonEff()
template<class BasicTurbulenceModel > tmp< volScalarField > DepsilonEff (const volScalarField & nutm) const inline protected
Definition at line 186 of file mixtureKEpsilon.H.
References mixtureKEpsilon< BasicTurbulenceModel >::sigmaEps_.
TypeName()
template<class BasicTurbulenceModel > TypeName ("mixtureKEpsilon< BasicTurbulenceModel >")
read()
template<class BasicTurbulenceModel > bool read () virtual
Implements eddyViscosity< RASModel< BasicTurbulenceModel > >.
Definition at line 309 of file mixtureKEpsilon.C.
References Foam::read().
k()
template<class BasicTurbulenceModel > virtual tmp< volScalarField > k () const inline virtual
Implements eddyViscosity< RASModel< BasicTurbulenceModel > >.
Definition at line 235 of file mixtureKEpsilon.H.
References mixtureKEpsilon< BasicTurbulenceModel >::k_.
epsilon()
template<class BasicTurbulenceModel > virtual tmp< volScalarField > epsilon () const inline virtual
Definition at line 241 of file mixtureKEpsilon.H.
References mixtureKEpsilon< BasicTurbulenceModel >::epsilon_.
correct()
template<class BasicTurbulenceModel > void correct () virtual
Implements eddyViscosity< RASModel< BasicTurbulenceModel > >.
Definition at line 534 of file mixtureKEpsilon.C.
References Foam::fvc::absolute(), alphal, Foam::bound(), GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), PtrList< T >::clear(), correct(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), Foam::fvm::ddt(), Foam::devTwoSymm(), Foam::fvc::div(), Foam::fvm::div(), GeometricBoundaryField< Type, PatchField, GeoMesh >::evaluateCoupled(), fluid, fvOptions, Foam::fvc::grad(), Foam::fvm::laplacian(), options::New(), nu, phi, phig(), solve(), Foam::fvm::Sp(), Foam::fvm::SuSp(), and GeometricBoundaryField< Type, PatchField, GeoMesh >::updateCoeffs().
Member Data Documentation
Cmu_
template<class BasicTurbulenceModel > dimensionedScalar Cmu_ protected
Definition at line 109 of file mixtureKEpsilon.H.
C1_
template<class BasicTurbulenceModel > dimensionedScalar C1_ protected
Definition at line 110 of file mixtureKEpsilon.H.
C2_
template<class BasicTurbulenceModel > dimensionedScalar C2_ protected
Definition at line 111 of file mixtureKEpsilon.H.
C3_
template<class BasicTurbulenceModel > dimensionedScalar C3_ protected
Definition at line 112 of file mixtureKEpsilon.H.
Cp_
template<class BasicTurbulenceModel > dimensionedScalar Cp_ protected
Definition at line 113 of file mixtureKEpsilon.H.
sigmak_
template<class BasicTurbulenceModel > dimensionedScalar sigmak_ protected
Definition at line 114 of file mixtureKEpsilon.H.
Referenced by mixtureKEpsilon< BasicTurbulenceModel >::DkEff().
sigmaEps_
template<class BasicTurbulenceModel > dimensionedScalar sigmaEps_ protected
Definition at line 115 of file mixtureKEpsilon.H.
Referenced by mixtureKEpsilon< BasicTurbulenceModel >::DepsilonEff().
k_
template<class BasicTurbulenceModel > volScalarField k_ protected
Definition at line 119 of file mixtureKEpsilon.H.
Referenced by mixtureKEpsilon< BasicTurbulenceModel >::k(), and mixtureKEpsilon< BasicTurbulenceModel >::mixtureKEpsilon().
epsilon_
template<class BasicTurbulenceModel > volScalarField epsilon_ protected
Definition at line 120 of file mixtureKEpsilon.H.
Referenced by mixtureKEpsilon< BasicTurbulenceModel >::epsilon(), and mixtureKEpsilon< BasicTurbulenceModel >::mixtureKEpsilon().
Ct2_
template<class BasicTurbulenceModel > autoPtr<volScalarField> Ct2_ protected
Definition at line 124 of file mixtureKEpsilon.H.
rhom_
template<class BasicTurbulenceModel > autoPtr<volScalarField> rhom_ protected
Definition at line 125 of file mixtureKEpsilon.H.
km_
template<class BasicTurbulenceModel > autoPtr<volScalarField> km_ protected
Definition at line 126 of file mixtureKEpsilon.H.
epsilonm_
template<class BasicTurbulenceModel > autoPtr<volScalarField> epsilonm_ protected
Definition at line 127 of file mixtureKEpsilon.H.
The documentation for this class was generated from the following files:
src/TurbulenceModels/phaseCompressible/RAS/mixtureKEpsilon/mixtureKEpsilon.H
src/TurbulenceModels/phaseCompressible/RAS/mixtureKEpsilon/mixtureKEpsilon.C