OpenFOAM: UPstream Class Reference
UPstream Class Reference
Inter-processor communications stream.
#include <UPstream.H>
Classes
class commsStruct
class communicator
class Request
Public Types
enum class commsTypes : char { blocking , scheduled , nonBlocking }
enum class sendModes : char { normal , sync }
typedef IntRange< int > rangeType
Public Member Functions
ClassName ("UPstream")
UPstream (const commsTypes commsType) noexcept
commsTypes commsType () const noexcept
commsTypes commsType (const commsTypes ct) noexcept
template<class T >
Foam::List< T > allGatherValues (const T &localValue, const label comm)
template<class T >
Foam::List< T > listGatherValues (const T &localValue, const label comm)
Static Public Member Functions
static constexpr label commGlobal () noexcept
static constexpr label commSelf () noexcept
static label commWorld () noexcept
static label commWorld (const label communicator) noexcept
static label commWarn (const label communicator) noexcept
static label nComms () noexcept
static void printCommTree (const label communicator)
static label commIntraHost ()
static label commInterHost ()
static bool hasHostComms ()
static void clearHostComms ()
static label allocateCommunicator (const label parent, const labelRange &subRanks, const bool withComponents=true)
static label allocateCommunicator (const label parent, const labelUList &subRanks, const bool withComponents=true)
static void freeCommunicator (const label communicator, const bool withComponents=true)
static label allocateInterHostCommunicator (const label parentCommunicator=worldComm)
static label allocateIntraHostCommunicator (const label parentCommunicator=worldComm)
static int baseProcNo (label comm, int procID)
static label procNo (const label comm, const int baseProcID)
static label procNo (const label comm, const label currentComm, const int currentProcID)
static void addValidParOptions (HashTable< string > &validParOptions)
static bool init (int &argc, char **&argv, const bool needsThread)
static bool initNull ()
static void barrier (const label communicator, UPstream::Request *req=nullptr)
static std::pair< int, int > probeMessage (const UPstream::commsTypes commsType, const int fromProcNo, const int tag=UPstream::msgType(), const label communicator=worldComm)
static label nRequests () noexcept
static void resetRequests (const label n)
static void addRequest (UPstream::Request &req)
static void cancelRequest (const label i)
static void cancelRequest (UPstream::Request &req)
static void cancelRequests (UList< UPstream::Request > &requests)
static void freeRequest (UPstream::Request &req)
static void freeRequests (UList< UPstream::Request > &requests)
static void waitRequests (const label pos, label len=-1)
static void waitRequests (UList< UPstream::Request > &requests)
static bool waitAnyRequest (const label pos, label len=-1)
static bool waitSomeRequests (const label pos, DynamicList< int > *indices=nullptr)
static label waitAnyRequest (UList< UPstream::Request > &requests)
static void waitRequest (const label i)
static void waitRequest (UPstream::Request &req)
static bool finishedRequest (const label i)
static bool finishedRequest (UPstream::Request &req)
static bool finishedRequests (const label pos, label len=-1)
static bool finishedRequests (UList< UPstream::Request > &requests)
static bool finishedRequestPair (label &req0, label &req1)
static void waitRequestPair (label &req0, label &req1)
static bool parRun (const bool on) noexcept
static bool & parRun () noexcept
static bool haveThreads () noexcept
static constexpr int masterNo () noexcept
static label nProcs (const label communicator=worldComm)
static int myProcNo (const label communicator=worldComm)
static bool master (const label communicator=worldComm)
static bool is_rank (const label communicator=worldComm)
static bool is_subrank (const label communicator=worldComm)
static bool is_parallel (const label communicator=worldComm)
static label parent (const label communicator)
static List< int > & procID (const label communicator)
static const wordList & allWorlds () noexcept
static const labelList & worldIDs () noexcept
static label myWorldID ()
static const word & myWorld ()
static rangeType allProcs (const label communicator=worldComm)
static rangeType subProcs (const label communicator=worldComm)
static const List< commsStruct > & linearCommunication (const label communicator=worldComm)
static const List< commsStruct > & treeCommunication (const label communicator=worldComm)
static const List< commsStruct > & whichCommunication (const label communicator=worldComm)
static int & msgType () noexcept
static void shutdown (int errNo=0)
static void abort ()
static void exit (int errNo=1)
static void allToAll (const UList< int32_t > &sendData, UList< int32_t > &recvData, const label communicator=worldComm)
static void allToAll (const UList< int64_t > &sendData, UList< int64_t > &recvData, const label communicator=worldComm)
static void allToAllConsensus (const UList< int32_t > &sendData, UList< int32_t > &recvData, const int tag, const label communicator=worldComm)
static void allToAllConsensus (const UList< int64_t > &sendData, UList< int64_t > &recvData, const int tag, const label communicator=worldComm)
static void allToAllConsensus (const Map< int32_t > &sendData, Map< int32_t > &recvData, const int tag, const label communicator=worldComm)
static void allToAllConsensus (const Map< int64_t > &sendData, Map< int64_t > &recvData, const int tag, const label communicator=worldComm)
static void mpiGather (const char *sendData, char *recvData, int count, const label communicator=worldComm)
Receive identically-sized char data from all ranks.
static void mpiScatter (const char *sendData, char *recvData, int count, const label communicator=worldComm)
Send identically-sized char data to all ranks.
static void mpiAllGather (char *allData, int count, const label communicator=worldComm)
Gather/scatter identically-sized char data.
static void gather (const char *sendData, int sendCount, char *recvData, const UList< int > &recvCounts, const UList< int > &recvOffsets, const label communicator=worldComm)
Receive variable length char data from all ranks.
static void scatter (const char *sendData, const UList< int > &sendCounts, const UList< int > &sendOffsets, char *recvData, int recvCount, const label communicator=worldComm)
Send variable length char data to all ranks.
static void gather (const int32_t *sendData, int sendCount, int32_t *recvData, const UList< int > &recvCounts, const UList< int > &recvOffsets, const label communicator=worldComm)
Receive variable length int32_t data from all ranks.
static void scatter (const int32_t *sendData, const UList< int > &sendCounts, const UList< int > &sendOffsets, int32_t *recvData, int recvCount, const label communicator=worldComm)
Send variable length int32_t data to all ranks.
static void gather (const int64_t *sendData, int sendCount, int64_t *recvData, const UList< int > &recvCounts, const UList< int > &recvOffsets, const label communicator=worldComm)
Receive variable length int64_t data from all ranks.
static void scatter (const int64_t *sendData, const UList< int > &sendCounts, const UList< int > &sendOffsets, int64_t *recvData, int recvCount, const label communicator=worldComm)
Send variable length int64_t data to all ranks.
static void gather (const uint32_t *sendData, int sendCount, uint32_t *recvData, const UList< int > &recvCounts, const UList< int > &recvOffsets, const label communicator=worldComm)
Receive variable length uint32_t data from all ranks.
static void scatter (const uint32_t *sendData, const UList< int > &sendCounts, const UList< int > &sendOffsets, uint32_t *recvData, int recvCount, const label communicator=worldComm)
Send variable length uint32_t data to all ranks.
static void gather (const uint64_t *sendData, int sendCount, uint64_t *recvData, const UList< int > &recvCounts, const UList< int > &recvOffsets, const label communicator=worldComm)
Receive variable length uint64_t data from all ranks.
static void scatter (const uint64_t *sendData, const UList< int > &sendCounts, const UList< int > &sendOffsets, uint64_t *recvData, int recvCount, const label communicator=worldComm)
Send variable length uint64_t data to all ranks.
static void gather (const float *sendData, int sendCount, float *recvData, const UList< int > &recvCounts, const UList< int > &recvOffsets, const label communicator=worldComm)
Receive variable length float data from all ranks.
static void scatter (const float *sendData, const UList< int > &sendCounts, const UList< int > &sendOffsets, float *recvData, int recvCount, const label communicator=worldComm)
Send variable length float data to all ranks.
static void gather (const double *sendData, int sendCount, double *recvData, const UList< int > &recvCounts, const UList< int > &recvOffsets, const label communicator=worldComm)
Receive variable length double data from all ranks.
static void scatter (const double *sendData, const UList< int > &sendCounts, const UList< int > &sendOffsets, double *recvData, int recvCount, const label communicator=worldComm)
Send variable length double data to all ranks.
template<class T >
static List< T > allGatherValues (const T &localValue, const label communicator=worldComm)
template<class T >
static List< T > listGatherValues (const T &localValue, const label communicator=worldComm)
template<class T >
static T listScatterValues (const UList< T > &allValues, const label communicator=worldComm)
static bool broadcast (char *buf, const std::streamsize bufSize, const label communicator, const int rootProcNo=masterNo())
static void reduceAnd (bool &value, const label communicator=worldComm)
static void reduceOr (bool &value, const label communicator=worldComm)
static void waitRequests ()
static constexpr int firstSlave () noexcept
static int lastSlave (const label communicator=worldComm)
Static Public Attributes
static const Enum< commsTypes > commsTypeNames
static bool floatTransfer
static int nProcsSimpleSum
static int nProcsNonblockingExchange
static int nPollProcInterfaces
static commsTypes defaultCommsType
static int maxCommsSize
static int tuning_NBX_
static const int mpiBufferSize
static label worldComm
static label warnComm
Detailed Description
Inter-processor communications stream.
Source files
UPstream.H
UPstream.C
UPstreamCommsStruct.C
UPstreamTemplates.C
Definition at line 62 of file UPstream.H.
Member Typedef Documentation
rangeType
typedef IntRange<int> rangeType
Definition at line 67 of file UPstream.H.
Member Enumeration Documentation
commsTypes
enum class commsTypes : char strong
Enumerator
blocking
"blocking" : (MPI_Bsend, MPI_Recv)
scheduled
"scheduled" : (MPI_Send, MPI_Recv)
nonBlocking
"nonBlocking" : (MPI_Isend, MPI_Irecv)
Definition at line 70 of file UPstream.H.
sendModes
enum class sendModes : char strong
Enumerator
normal
(MPI_Send, MPI_Isend)
sync
(MPI_Ssend, MPI_Issend)
Definition at line 81 of file UPstream.H.
Constructor & Destructor Documentation
UPstream()
UPstream (const commsTypes commsType) inline explicit noexcept
Definition at line 367 of file UPstream.H.
Member Function Documentation
ClassName()
ClassName ("UPstream")
commGlobal()
static constexpr label commGlobal () inline static constexpr noexcept
Definition at line 315 of file UPstream.H.
Referenced by multiWorldConnections::createComms(), fileOperation::getManagedComm(), UPstream::myWorld(), UPstream::myWorldID(), and syncObjects::sync().
commSelf()
static constexpr label commSelf () inline static constexpr noexcept
Definition at line 318 of file UPstream.H.
Referenced by fileOperation::getManagedComm().
commWorld() [1/2]
static label commWorld () inline static noexcept
Definition at line 321 of file UPstream.H.
References UPstream::worldComm.
Referenced by mappedPatchBase::calcAMI(), multiWorldConnections::createComms(), mappedPatchBase::distribute(), mappedPatchBase::distribute(), faMeshDistributor::distributeAreaFields(), faMeshDistributor::distributeEdgeFields(), fileOperation::getManagedComm(), mappedPatchBase::getWorldCommunicator(), profilingPstream::report(), mappedPatchBase::reverseDistribute(), and mappedPatchBase::reverseDistribute().
commWorld() [2/2]
static label commWorld (const label communicator) inline static noexcept
Definition at line 325 of file UPstream.H.
References UPstream::worldComm.
commWarn()
static label commWarn (const label communicator) inline static noexcept
Definition at line 335 of file UPstream.H.
References UPstream::warnComm.
Referenced by mappedPatchBase::calcAMI(), mappedPatchBase::collectSamples(), multiWorldConnections::createComms(), mappedPatchBase::distribute(), mappedPatchBase::distribute(), mappedPatchBase::findSamples(), mappedPatchBase::reverseDistribute(), mappedPatchBase::reverseDistribute(), syncObjects::sync(), and globalMeshData::updateMesh().
nComms()
static label nComms () inline static noexcept
Definition at line 343 of file UPstream.H.
References UPtrList< T >::size().
printCommTree()
void printCommTree (const label communicator) static
Definition at line 671 of file UPstream.C.
References Foam::Info, UPstream::master(), and UPstream::whichCommunication().
commIntraHost()
Foam::label commIntraHost () static
Definition at line 682 of file UPstream.C.
commInterHost()
Foam::label commInterHost () static
Definition at line 696 of file UPstream.C.
hasHostComms()
bool hasHostComms () static
Definition at line 710 of file UPstream.C.
clearHostComms()
void clearHostComms () static
Definition at line 716 of file UPstream.C.
allocateCommunicator() [1/2]
Foam::label allocateCommunicator (const label parent, const labelRange & subRanks, const bool withComponents = true) static
if (myProcNo_[index] < 0 && parentIndex >= 0) { // As global rank myProcNo_[index] = -(myProcNo_[worldComm]+1);
OR: // As parent rank number if (myProcNo_[parentIndex] >= 0) { myProcNo_[index] = -(myProcNo_[parentIndex]+1); } }
Parameters
parent The parent communicator
subRanks The contiguous sub-ranks of parent to use
withComponents Call allocateCommunicatorComponents()
Definition at line 257 of file UPstream.C.
References PtrList< T >::clear(), Foam::endl(), UPstream::masterNo(), Foam::nl, Foam::Pout, and IntRange< IntType >::size().
Referenced by eagerGAMGProcAgglomeration::agglomerate(), manualGAMGProcAgglomeration::agglomerate(), masterCoarsestGAMGProcAgglomeration::agglomerate(), procFacesGAMGProcAgglomeration::agglomerate(), Foam::getCommPattern(), UPstream::communicator::reset(), and UPstream::communicator::reset().
allocateCommunicator() [2/2]
Foam::label allocateCommunicator (const label parent, const labelUList & subRanks, const bool withComponents = true) static
if (myProcNo_[index] < 0 && parentIndex >= 0) { // As global rank myProcNo_[index] = -(myProcNo_[worldComm]+1);
OR: // As parent rank number if (myProcNo_[parentIndex] >= 0) { myProcNo_[index] = -(myProcNo_[parentIndex]+1); } }
Parameters
parent The parent communicator
subRanks The sub-ranks of parent to use (ignore negative values)
withComponents Call allocateCommunicatorComponents()
Definition at line 318 of file UPstream.C.
References UPtrList< T >::begin(), PtrList< T >::clear(), Foam::endl(), Foam::flatOutput(), UPstream::masterNo(), Foam::nl, Foam::Pout, PtrList< T >::resize(), and UList< T >::size().
freeCommunicator()
void freeCommunicator (const label communicator, const bool withComponents = true) static
Definition at line 564 of file UPstream.C.
References Foam::endl(), and Foam::Pout.
Referenced by GAMGProcAgglomeration::clearCommunicators(), UPstream::communicator::reset(), UPstream::communicator::reset(), UPstream::communicator::reset(), UPstream::communicator::reset(), collatedFileOperation::~collatedFileOperation(), UPstream::communicator::~communicator(), hostCollatedFileOperation::~hostCollatedFileOperation(), hostUncollatedFileOperation::~hostUncollatedFileOperation(), masterUncollatedFileOperation::~masterUncollatedFileOperation(), OFstreamCollator::~OFstreamCollator(), and uncollatedFileOperation::~uncollatedFileOperation().
allocateInterHostCommunicator()
Foam::label allocateInterHostCommunicator (const label parentCommunicator = worldComm) static
Definition at line 400 of file UPstream.C.
References forAll, Foam::getHostGroupIds(), PtrList< T >::push_back(), and UPtrList< T >::size().
allocateIntraHostCommunicator()
Foam::label allocateIntraHostCommunicator (const label parentCommunicator = worldComm) static
Definition at line 423 of file UPstream.C.
References forAll, Foam::getHostGroupIds(), UPstream::myProcNo(), PtrList< T >::push_back(), and UPtrList< T >::size().
baseProcNo()
int baseProcNo (label comm, int procID) static
Definition at line 604 of file UPstream.C.
References UPstream::parent(), and UPstream::procID().
Referenced by UPstream::procNo().
procNo() [1/2]
Foam::label procNo (const label comm, const int baseProcID) static
Definition at line 617 of file UPstream.C.
References UPstream::parent(), UPstream::procID(), and UPstream::procNo().
Referenced by UPstream::procNo(), and UPstream::procNo().
procNo() [2/2]
Foam::label procNo (const label comm, const label currentComm, const int currentProcID) static
Definition at line 633 of file UPstream.C.
References UPstream::baseProcNo(), and UPstream::procNo().
addValidParOptions()
void addValidParOptions (HashTable< string > & validParOptions) static
Definition at line 26 of file UPstream.C.
init()
bool init (int & argc, char **& argv, const bool needsThread) static
Definition at line 40 of file UPstream.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
Referenced by ParRunControl::runPar().
initNull()
bool initNull () static
Definition at line 30 of file UPstream.C.
References Foam::endl(), and WarningInFunction.
barrier()
void barrier (const label communicator, UPstream::Request * req = nullptr) static
Definition at line 83 of file UPstream.C.
Referenced by Foam::PstreamDetail::exchangeConsensus(), and Foam::PstreamDetail::exchangeConsensus().
probeMessage()
std::pair< int, int > probeMessage (const UPstream::commsTypes commsType, const int fromProcNo, const int tag = UPstream::msgType(), const label communicator = worldComm) static
Definition at line 88 of file UPstream.C.
Referenced by Foam::PstreamDetail::exchangeConsensus(), and Foam::PstreamDetail::exchangeConsensus().
nRequests()
Foam::label nRequests () static noexcept
Definition at line 45 of file UPstreamRequest.C.
Referenced by GAMGAgglomeration::agglomerateLduAddressing(), LduMatrix< Type, DType, LUType >::Amul(), lduMatrix::Amul(), meshWaveAddressing::correct(), cellCellStencil::correctBoundaryConditions(), oversetFvMeshBase::correctBoundaryConditions(), oversetFvMeshBase::correctCoupledBoundaryConditions(), metisLikeDecomp::decomposeGeneral(), faMeshDistributor::distribute(), mapDistributeBase::distribute(), mapDistributeBase::distribute(), GeometricBoundaryField< Type, PatchField, GeoMesh >::evaluate(), Foam::evaluateConstraintTypes(), GeometricBoundaryField< Type, PatchField, GeoMesh >::evaluateCoupled(), Foam::PstreamDetail::exchangeBuf(), Foam::PstreamDetail::exchangeConsensus(), Foam::PstreamDetail::exchangeConsensus(), Foam::PstreamDetail::exchangeContainer(), Foam::PstreamDetail::exchangeContainer(), mapDistributeBase::exchangeMasks(), Pstream::exchangeSizes(), globalIndex::gather(), globalIndex::gather(), globalIndex::gatherValues(), GAMGProcAgglomeration::globalCellCells(), lduPrimitiveMesh::globalCellCells(), processorFaPatchField< Type >::initEvaluate(), calculatedProcessorFvPatchField< Type >::initEvaluate(), processorFvPatchField< Type >::initEvaluate(), processorFaPatchField< Type >::initInterfaceMatrixUpdate(), processorFvPatchField< Type >::initInterfaceMatrixUpdate(), processorFaPatchField< Type >::initInterfaceMatrixUpdate(), calculatedProcessorFvPatchField< Type >::initInterfaceMatrixUpdate(), processorFvPatchField< Type >::initInterfaceMatrixUpdate(), lduCalculatedProcessorField< Type >::initInterfaceMatrixUpdate(), processorGAMGInterfaceField::initInterfaceMatrixUpdate(), calculatedProcessorGAMGInterfaceField::initInterfaceMatrixUpdate(), LduMatrix< Type, DType, LUType >::residual(), lduMatrix::residual(), globalIndex::scatter(), mapDistributeBase::send(), TGaussSeidelSmoother< Type, DType, LUType >::smooth(), nonBlockingGaussSeidelSmoother::smooth(), GaussSeidelSmoother::smooth(), symGaussSeidelSmoother::smooth(), faMatrix< Type >::solve(), fvMatrix< Type >::solveSegregated(), syncTools::syncBoundaryFaceList(), syncTools::syncFaceList(), LduMatrix< Type, DType, LUType >::Tmul(), lduMatrix::Tmul(), distributedDILUPreconditioner::updateMatrixInterfaces(), and OFstreamCollator::write().
resetRequests()
void resetRequests (const label n) static
Definition at line 47 of file UPstreamRequest.C.
addRequest()
void addRequest (UPstream::Request & req) static
Definition at line 49 of file UPstreamRequest.C.
cancelRequest() [1/2]
void cancelRequest (const label i) static
Definition at line 51 of file UPstreamRequest.C.
Referenced by UPstream::Request::cancel().
cancelRequest() [2/2]
void cancelRequest (UPstream::Request & req) static
Definition at line 52 of file UPstreamRequest.C.
cancelRequests()
void cancelRequests (UList< UPstream::Request > & requests) static
Definition at line 53 of file UPstreamRequest.C.
Referenced by distributedDILUPreconditioner::wait().
freeRequest()
void freeRequest (UPstream::Request & req) static
Definition at line 55 of file UPstreamRequest.C.
Referenced by UPstream::Request::free().
freeRequests()
void freeRequests (UList< UPstream::Request > & requests) static
Definition at line 56 of file UPstreamRequest.C.
waitRequests() [1/3]
void waitRequests (const label pos, label len = -1) static
Definition at line 58 of file UPstreamRequest.C.
waitRequests() [2/3]
void waitRequests (UList< UPstream::Request > & requests) static
Definition at line 59 of file UPstreamRequest.C.
waitAnyRequest() [1/2]
bool waitAnyRequest (const label pos, label len = -1) static
Definition at line 61 of file UPstreamRequest.C.
waitSomeRequests()
bool waitSomeRequests (const label pos, DynamicList< int > * indices = nullptr) static
Definition at line 66 of file UPstreamRequest.C.
References PtrList< T >::clear().
Referenced by LduMatrix< Type, DType, LUType >::updateMatrixInterfaces(), and lduMatrix::updateMatrixInterfaces().
waitAnyRequest() [2/2]
Foam::label waitAnyRequest (UList< UPstream::Request > & requests) static
Definition at line 76 of file UPstreamRequest.C.
waitRequest() [1/2]
void waitRequest (const label i) static
void Foam::UPstream::waitRequests (UPstream::Request& req0, UPstream::Request& req1) { // No-op for non-parallel if (!UPstreamparRun()) { return; }
int count = 0; MPI_Request waitRequests[2];
waitRequests[count] = PstreamDetail::Request::get(req0); if (MPI_REQUEST_NULL != waitRequests[count]) { ++count; }
waitRequests[count] = PstreamDetail::Request::get(req1); if (MPI_REQUEST_NULL != waitRequests[count]) { ++count; }
// Flag in advance as being handled req0 = UPstream::Request(MPI_REQUEST_NULL); req1 = UPstream::Request(MPI_REQUEST_NULL);
if (!count) { return; }
profilingPstream::beginTiming();
// On success: sets each request to MPI_REQUEST_NULL if (MPI_Waitall(count, waitRequests, MPI_STATUSES_IGNORE)) { FatalErrorInFunction << "MPI_Waitall returned with error" << Foam::abort(FatalError); }
profilingPstream::addWaitTime(); }
Definition at line 81 of file UPstreamRequest.C.
Referenced by processorFaPatchField< Type >::evaluate(), calculatedProcessorFvPatchField< Type >::evaluate(), processorFvPatchField< Type >::evaluate(), processorFaPatchField< Type >::updateInterfaceMatrix(), processorFvPatchField< Type >::updateInterfaceMatrix(), processorFaPatchField< Type >::updateInterfaceMatrix(), calculatedProcessorFvPatchField< Type >::updateInterfaceMatrix(), processorFvPatchField< Type >::updateInterfaceMatrix(), lduCalculatedProcessorField< Type >::updateInterfaceMatrix(), processorGAMGInterfaceField::updateInterfaceMatrix(), calculatedProcessorGAMGInterfaceField::updateInterfaceMatrix(), and UPstream::Request::wait().
waitRequest() [2/2]
void waitRequest (UPstream::Request & req) static
Definition at line 82 of file UPstreamRequest.C.
finishedRequest() [1/2]
bool finishedRequest (const label i) static
Definition at line 84 of file UPstreamRequest.C.
Referenced by processorFaPatchField< Type >::evaluate(), calculatedProcessorFvPatchField< Type >::evaluate(), processorFvPatchField< Type >::evaluate(), Foam::PstreamDetail::exchangeConsensus(), Foam::PstreamDetail::exchangeConsensus(), UPstream::Request::finished(), processorFaPatchField< Type >::ready(), calculatedProcessorFvPatchField< Type >::ready(), processorFvPatchField< Type >::ready(), lduCalculatedProcessorField< Type >::ready(), processorFaPatchField< Type >::updateInterfaceMatrix(), processorFvPatchField< Type >::updateInterfaceMatrix(), processorFaPatchField< Type >::updateInterfaceMatrix(), calculatedProcessorFvPatchField< Type >::updateInterfaceMatrix(), processorFvPatchField< Type >::updateInterfaceMatrix(), lduCalculatedProcessorField< Type >::updateInterfaceMatrix(), processorGAMGInterfaceField::updateInterfaceMatrix(), and calculatedProcessorGAMGInterfaceField::updateInterfaceMatrix().
finishedRequest() [2/2]
bool finishedRequest (UPstream::Request & req) static
Definition at line 85 of file UPstreamRequest.C.
finishedRequests() [1/2]
bool finishedRequests (const label pos, label len = -1) static
Definition at line 87 of file UPstreamRequest.C.
Referenced by Foam::PstreamDetail::exchangeConsensus(), and Foam::PstreamDetail::exchangeConsensus().
finishedRequests() [2/2]
bool finishedRequests (UList< UPstream::Request > & requests) static
Definition at line 93 of file UPstreamRequest.C.
finishedRequestPair()
bool finishedRequestPair (label & req0, label & req1) static
Definition at line 99 of file UPstreamRequest.C.
Referenced by calculatedProcessorFvPatchField< Type >::all_ready(), and lduCalculatedProcessorField< Type >::all_ready().
waitRequestPair()
void waitRequestPair (label & req0, label & req1) static
Definition at line 107 of file UPstreamRequest.C.
parRun() [1/2]
static bool parRun (const bool on) inline static noexcept
Definition at line 735 of file UPstream.H.
parRun() [2/2]
static bool & parRun () inline static noexcept
Definition at line 744 of file UPstream.H.
Referenced by snappyLayerDriver::addLayers(), snappyLayerDriver::addLayersSinglePass(), unwatchedIOdictionary::addWatch(), regIOobject::addWatch(), masterUncollatedFileOperation::addWatch(), Cloud< ParcelType >::autoMap(), meshRefinement::balance(), AMIInterpolation::calcDistribution(), addPatchCellLayer::calcExtrudeInfo(), processorFaPatch::calcGeometry(), processorPolyPatch::calcGeometry(), processorCyclicPolyPatch::calcGeometry(), surfaceNoise::calculate(), waveMethod::calculate(), cyclicAMIPolyPatch::canResetAMI(), FaceCellWave< Type, TrackingData >::cellToFace(), OppositeFaceCellWave< Type, TrackingData >::cellToFace(), IOobjectList::checkNames(), faBoundaryMesh::checkParallelSync(), polyBoundaryMesh::checkParallelSync(), ZoneMesh< ZoneType, MeshType >::checkParallelSync(), AMIInterpolation::checkSymmetricWeights(), fieldValue::combineFields(), limitTurbulenceViscosity::correct(), cellCellStencil::correctBoundaryConditions(), meshRefinement::countEdgeFaces(), processorFaPatch::coupled(), processorFaePatchField< Type >::coupled(), processorFaPatchField< Type >::coupled(), calculatedProcessorFvPatchField< Type >::coupled(), processorFvPatchField< Type >::coupled(), cyclicACMIFvsPatchField< Type >::coupled(), processorFvsPatchField< Type >::coupled(), processorCyclicFvsPatchField< Type >::coupled(), cyclicACMIFvPatch::coupled(), cyclicAMIFvPatch::coupled(), processorFvPatch::coupled(), cyclicAMIPointPatch::coupled(), processorPointPatchField< Type >::coupled(), processorCyclicPointPatchField< Type >::coupled(), processorPolyPatch::coupled(), multiWorldConnections::createComms(), simpleGeomDecomp::decompose(), simpleGeomDecomp::decompose(), decompositionMethod::decompose(), metisLikeDecomp::decomposeGeneral(), conformalVoronoiMesh::decomposition(), processorFaPatch::delta(), processorFvPatch::delta(), masterUncollatedFileOperation::dirPath(), faMeshDistributor::distribute(), fvMeshDistribute::distribute(), distributedTriSurfaceMesh::distribute(), refinementHistory::distribute(), mapDistributeBase::distribute(), mapDistributeBase::distribute(), distributedTriSurfaceMesh::distributedTriSurfaceMesh(), distributedTriSurfaceMesh::distributedTriSurfaceMesh(), faMeshBoundaryHalo::distributeSparse(), snappyLayerDriver::doLayers(), snappyRefineDriver::doRefine(), PointEdgeWave< Type, TrackingData >::edgeToPoint(), ensightSurfaceReader::ensightSurfaceReader(), processorFaPatchField< Type >::evaluate(), calculatedProcessorFvPatchField< Type >::evaluate(), processorFvPatchField< Type >::evaluate(), mapDistributeBase::exchangeMasks(), Foam::exitNow(), faMeshReconstructor::faMeshReconstructor(), faMeshReconstructor::faMeshReconstructor(), masterUncollatedFileOperation::filePath(), polyMesh::findCell(), masterUncollatedFileOperation::findInstance(), distributedTriSurfaceMesh::findLine(), distributedTriSurfaceMesh::findLineAll(), distributedTriSurfaceMesh::findLineAny(), distributedTriSurfaceMesh::findNearest(), distributedTriSurfaceMesh::findNearest(), masterUncollatedFileOperation::findTimes(), masterUncollatedFileOperation::findWatch(), fvMeshSubsetter::fvMeshSubset(), globalIndex::gather(), globalIndex::gather(), PatchTools::gatherAndMerge(), PatchTools::gatherAndMerge(), globalIndex::gatherInplace(), globalIndex::gatherInplaceOp(), globalIndex::gatherOp(), globalIndex::gatherOp(), ensightSurfaceReader::geometry(), Foam::getCommPattern(), zoneDistribute::getDatafromOtherProc(), distributedTriSurfaceMesh::getField(), masterUncollatedFileOperation::getFile(), distributedTriSurfaceMesh::getNormal(), distributedTriSurfaceMesh::getRegion(), masterUncollatedFileOperation::getState(), distributedTriSurfaceMesh::getVolumeType(), GAMGProcAgglomeration::globalCellCells(), faMeshBoundaryHalo::haloSize(), InflationInjection< CloudType >::InflationInjection(), faMesh::init(), processorFaPatchField< Type >::initEvaluate(), calculatedProcessorFvPatchField< Type >::initEvaluate(), processorFvPatchField< Type >::initEvaluate(), processorFaPatch::initGeometry(), processorPolyPatch::initGeometry(), InjectedParticleDistributionInjection< CloudType >::initialise(), InjectedParticleInjection< CloudType >::initialise(), extractEulerianParticles::initialiseBins(), processorPolyPatch::initOrder(), processorCyclicPointPatchField< Type >::initSwapAddSeparated(), processorFaPatch::initUpdateMesh(), processorPolyPatch::initUpdateMesh(), fileOperation::isIOrank(), isoAdvection::isoAdvection(), FaceCellWave< Type, TrackingData >::iterate(), PointEdgeWave< Type, TrackingData >::iterate(), masterUncollatedFileOperation::localObjectPath(), fileOperation::lookupAndCacheProcessorsPath(), LUscalarMatrix::LUscalarMatrix(), patchMeanVelocityForce::magUbarAve(), processorFaPatch::makeDeltaCoeffs(), processorFaPatch::makeNonGlobalPatchPoints(), processorFaPatch::makeWeights(), processorFvPatch::makeWeights(), error::master(), masterUncollatedFileOperation::masterOp(), masterUncollatedFileOperation::masterOp(), surfaceWriter::merge(), mergedSurf::merge(), debugWriter::mergeField(), surfaceWriter::mergeFieldTemplate(), globalIndex::mpiGather(), globalIndex::mpiGatherInplace(), globalIndex::mpiGatherInplaceOp(), globalIndex::mpiGatherOp(), decompositionMethod::nDomains(), polyBoundaryMesh::neighbourEdges(), processorTopology::New(), masterUncollatedFileOperation::NewIFstream(), fvMeshTools::newMesh(), faMeshTools::newMesh(), fileWriter::open(), processorPolyPatch::order(), fieldMinMax::output(), InflationInjection< CloudType >::parcelsToInject(), argList::parse(), RecycleInteraction< CloudType >::postEvolve(), powerLawLopesdaCostaZone::powerLawLopesdaCostaZone(), faMeshTools::printMeshChecks(), processorTopology::procAdjacency(), collatedFileOperation::processorsDir(), surfaceNoise::read(), masterUncollatedFileOperation::read(), uncollatedFileOperation::read(), lumpedPointState::readData(), ensightSurfaceReader::readField(), regIOobject::readHeaderOk(), Time::readModifiedObjects(), masterUncollatedFileOperation::readObjects(), masterUncollatedFileOperation::readStream(), surfaceNoise::readSurfaceData(), masterUncollatedFileOperation::removeWatch(), parProfiling::report(), profilingPstream::report(), AMIWeights::reportPatch(), fvMeshSubset::reset(), faMeshBoundaryHalo::reset(), globalIndex::reset(), globalIndex::scatter(), globalIndex::scatter(), mapDistributeBase::schedule(), Time::setControls(), surfaceWriter::setSurface(), surfaceWriter::setSurface(), masterUncollatedFileOperation::setUnmodified(), zoneDistribute::setUpCommforZone(), globalMeshData::sharedPoints(), shortestPathSet::shortestPathSet(), error::simpleExit(), TDACChemistryModel< ReactionThermo, ThermoType >::solve(), LUscalarMatrix::solve(), messageStream::stream(), surfaceWriter::surface(), surfaceNoise::surfaceAverage(), processorCyclicPointPatchField< Type >::swapAddSeparated(), syncObjects::sync(), masterUncollatedFileOperation::sync(), syncTools::syncEdgeMap(), faMesh::syncGeom(), syncTools::syncPointMap(), triSurfaceMesh::triSurfaceMesh(), triSurfaceMesh::triSurfaceMesh(), fileOperation::uniformFile(), mapDistributeBase::unionCombineMasks(), ensightFaces::uniqueMeshPoints(), turbulentDFSEMInletFvPatchVectorField::updateCoeffs(), calculatedProcessorFvPatchField< Type >::updateInterfaceMatrix(), faMesh::updateMesh(), processorFaPatch::updateMesh(), processorPolyPatch::updateMesh(), fileOperation::updateStates(), masterUncollatedFileOperation::updateStates(), dynamicCode::waitForFile(), energySpectrum::write(), vtkWrite::write(), ParticleZoneInfo< CloudType >::write(), ensightCells::write(), ensightFaces::write(), meshToMeshMethod::writeConnectivity(), AMIWeights::writeFileHeader(), fieldMinMax::writeFileHeader(), isoAdvection::writeIsoFaces(), faMeshReconstructor::writeMesh(), patchMeshWriter::writeNeighIDs(), collatedFileOperation::writeObject(), faMeshTools::writeProcAddressing(), fileWriter::writeProcIDs(), surfaceNoise::writeSurfaceData(), and streamLineBase::writeToFile().
haveThreads()
static bool haveThreads () inline static noexcept
Definition at line 747 of file UPstream.H.
Referenced by OFstreamCollator::write().
masterNo()
static constexpr int masterNo () inline static constexpr noexcept
Definition at line 750 of file UPstream.H.
Referenced by UPstream::allocateCommunicator(), UPstream::allocateCommunicator(), Pstream::broadcast(), Pstream::broadcasts(), Foam::createReconstructMap(), Foam::createReconstructMap(), metisLikeDecomp::decomposeGeneral(), Foam::getHostGroupIds(), UPstream::is_subrank(), LUscalarMatrix::LUscalarMatrix(), UPstream::master(), masterUncollatedFileOperation::NewIFstream(), argList::parse(), masterUncollatedFileOperation::read(), masterUncollatedFileOperation::read(), uncollatedFileOperation::read(), decomposedBlockData::readBlocks(), decomposedBlockData::readBlocks(), masterUncollatedFileOperation::readHeader(), masterUncollatedFileOperation::scatterList(), mapDistributeBase::schedule(), globalMeshData::sharedPoints(), LUscalarMatrix::solve(), syncTools::syncEdgeMap(), syncTools::syncPointMap(), energySpectrum::write(), patchWriter::write(), patchWriter::write(), patchWriter::write(), decomposedBlockData::writeBlocks(), patchMeshWriter::writeNeighIDs(), patchMeshWriter::writePatchIDs(), and patchMeshWriter::writePoints().
nProcs()
static label nProcs (const label communicator = worldComm) inline static
Definition at line 754 of file UPstream.H.
References UPtrList< T >::size().
Referenced by fvMeshPrimitiveLduAddressing::addAddressing(), surfaceZonesInfo::addCellZonesToMesh(), surfaceZonesInfo::addFaceZonesToMesh(), eagerGAMGProcAgglomeration::agglomerate(), manualGAMGProcAgglomeration::agglomerate(), masterCoarsestGAMGProcAgglomeration::agglomerate(), procFacesGAMGProcAgglomeration::agglomerate(), AMIInterpolation::agglomerate(), Pstream::allGatherList(), UPstream::allGatherValues(), UPstream::allProcs(), sensitivitySurfacePoints::assembleSensitivities(), meshRefinement::balance(), faMesh::boundaryProcs(), faPatch::boundaryProcs(), faMesh::boundaryProcSizes(), faPatch::boundaryProcSizes(), mapDistributeBase::calcCompactAddressing(), fieldMinMax::calcMinMaxFieldType(), decomposedBlockData::calcNumProcs(), surfaceNoise::calculate(), meshRefinement::checkCoupledFaceZones(), mappedPatchBase::collectSamples(), processorColour::colour(), fieldValue::combineFields(), sizeDistribution::combineFields(), GAMGAgglomeration::continueAgglomerating(), fvMeshDistribute::countCells(), box::createMap(), Foam::createReconstructMap(), Foam::createReconstructMap(), meshRefinement::directionalRefineCandidates(), faMeshDistributor::distribute(), fvMeshDistribute::distribute(), distributedTriSurfaceMesh::distribute(), mapDistributeBase::distribute(), mapDistributeBase::distribute(), distributedDILUPreconditioner::distributedDILUPreconditioner(), box::doRefineBoxes(), Pstream::exchange(), mapDistributeBase::exchangeAddressing(), mapDistributeBase::exchangeAddressing(), Foam::PstreamDetail::exchangeConsensus(), Pstream::exchangeConsensus(), Foam::PstreamDetail::exchangeConsensus(), mapDistributeBase::exchangeMasks(), Pstream::exchangeSizes(), Pstream::exchangeSizes(), extendedCentredCellToCellStencil::extendedCentredCellToCellStencil(), extendedCentredCellToFaceStencil::extendedCentredCellToFaceStencil(), extendedCentredFaceToCellStencil::extendedCentredFaceToCellStencil(), extendedUpwindCellToFaceStencil::extendedUpwindCellToFaceStencil(), extendedUpwindCellToFaceStencil::extendedUpwindCellToFaceStencil(), distributedTriSurfaceMesh::findNearest(), mappedPatchBase::findSamples(), decomposedBlockData::gather(), externalCoupled::gatherAndCombine(), Pstream::gatherList(), decomposedBlockData::gatherSlaveData(), globalIndex::get(), fileOperation::getGlobalHostIORanks(), Foam::getHostGroupIds(), Foam::getSelectedProcs(), distributedTriSurfaceMesh::getVolumeType(), InjectedParticleDistributionInjection< CloudType >::initialise(), InjectedParticleInjection< CloudType >::initialise(), viewFactor::initialise(), mappedPatchFieldBase< Type >::initRetrieveField(), UPstream::is_parallel(), UPstream::lastSlave(), UPstream::linearCommunication(), UPstream::listGatherValues(), UPstream::listScatterValues(), distributedTriSurfaceMesh::localQueries(), LUscalarMatrix::LUscalarMatrix(), mapDistributeBase::mapDistributeBase(), mapDistribute::mapDistributeBase(), mapDistributeBase::mapDistributeBase(), inverseDistance::markDonors(), trackingInverseDistance::markDonors(), masterCoarsestGAMGProcAgglomeration::masterCoarsestGAMGProcAgglomeration(), masterUncollatedFileOperation::masterOp(), masterUncollatedFileOperation::masterOp(), Cloud< ParticleType >::move(), decompositionMethod::nDomains(), processorTopology::New(), masterUncollatedFileOperation::NewIFstream(), InflationInjection< CloudType >::parcelsToInject(), argList::parse(), ParticleZoneInfo< CloudType >::ParticleZoneInfo(), pointHistory::pointHistory(), RecycleInteraction< CloudType >::postEvolve(), powerLawLopesdaCostaZone::powerLawLopesdaCostaZone(), collatedFileOperation::printBanner(), mapDistributeBase::printLayout(), fileOperation::printRanks(), processorTopology::procAdjacency(), masterUncollatedFileOperation::read(), masterUncollatedFileOperation::readHeader(), masterUncollatedFileOperation::readStream(), meshRefinement::refineCandidates(), Foam::regionSum(), meshRefinement::removeGapCells(), parProfiling::report(), profilingPstream::report(), fvMeshSubset::reset(), faMeshBoundaryHalo::reset(), globalIndex::reset(), Pstream::scatterList(), mapDistributeBase::schedule(), mapDistributeBase::send(), Time::setControls(), zoneDistribute::setUpCommforZone(), ParSortableList< Type >::sort(), UPstream::subProcs(), fileOperation::subRanks(), UPstream::treeCommunication(), inverseDistance::update(), trackingInverseDistance::update(), oversetFvMeshBase::updateAddressing(), turbulentDFSEMInletFvPatchVectorField::updateCoeffs(), globalMeshData::updateMesh(), UPstream::whichCommunication(), FacePostProcessing< CloudType >::write(), ParticleHistogram< CloudType >::write(), ParticlePostProcessing< CloudType >::write(), ParticleZoneInfo< CloudType >::write(), decomposedBlockData::writeBlocks(), externalCoupled::writeGeometry(), isoAdvection::writeIsoFaces(), and streamLineBase::writeToFile().
myProcNo()
static int myProcNo (const label communicator = worldComm) inline static
Definition at line 761 of file UPstream.H.
Referenced by surfaceZonesInfo::addCellZonesToMesh(), surfaceZonesInfo::addFaceZonesToMesh(), eagerGAMGProcAgglomeration::agglomerate(), manualGAMGProcAgglomeration::agglomerate(), masterCoarsestGAMGProcAgglomeration::agglomerate(), AMIInterpolation::agglomerate(), GAMGProcAgglomeration::agglomerate(), UPstream::allGatherValues(), UPstream::allocateIntraHostCommunicator(), sensitivitySurfacePoints::assembleSensitivities(), faMesh::boundaryProcs(), faPatch::boundaryProcs(), faMesh::boundaryProcSizes(), faPatch::boundaryProcSizes(), SprayParcel< ParcelType >::calcBreakup(), mapDistributeBase::calcCompactAddressing(), fieldMinMax::calcMinMaxFieldType(), viewFactor::calculate(), GAMGAgglomeration::calculateRegionMaster(), meshRefinement::checkCoupledFaceZones(), mappedPatchBase::collectSamples(), processorColour::colour(), fieldValue::combineFields(), sizeDistribution::combineFields(), Pstream::combineGather(), Pstream::combineScatter(), wallDistAddressing::correct(), box::createMap(), Foam::createReconstructMap(), Foam::createReconstructMap(), noDecomp::decompose(), noDecomp::decompose(), faMeshDistributor::distribute(), fvMeshDistribute::distribute(), distributedTriSurfaceMesh::distribute(), mapDistributeBase::distribute(), mapDistributeBase::distribute(), distributedDILUPreconditioner::distributedDILUPreconditioner(), box::doRefineBoxes(), globalIndexAndTransform::encode(), Pstream::exchange(), Pstream::exchange(), mapDistributeBase::exchangeAddressing(), mapDistributeBase::exchangeAddressing(), Foam::PstreamDetail::exchangeBuf(), Foam::PstreamDetail::exchangeChunkedBuf(), Foam::PstreamDetail::exchangeConsensus(), Foam::PstreamDetail::exchangeConsensus(), Foam::PstreamDetail::exchangeContainer(), Foam::PstreamDetail::exchangeContainer(), mapDistributeBase::exchangeMasks(), Pstream::exchangeSizes(), processorField::execute(), InjectionModel< CloudType >::findCellAtPosition(), patchProbes::findElements(), probes::findElements(), mappedPatchBase::findLocalSamples(), distributedTriSurfaceMesh::findNearest(), distributedTriSurfaceMesh::findNearest(), mappedPatchBase::findSamples(), lduPrimitiveMesh::gather(), globalIndex::gather(), globalIndex::gather(), globalIndex::gather(), Pstream::gather(), externalCoupled::gatherAndCombine(), Pstream::gatherList(), decomposedBlockData::gatherSlaveData(), globalIndex::gatherValues(), zoneDistribute::getDatafromOtherProc(), Foam::getSelectedProcs(), GAMGProcAgglomeration::globalCellCells(), lduPrimitiveMesh::globalCellCells(), inverseDistance::holeExtrapolationStencil(), InjectedParticleDistributionInjection< CloudType >::initialise(), InjectedParticleInjection< CloudType >::initialise(), viewFactor::initialise(), globalIndex::inplaceToGlobal(), cellShapeControlMesh::insert(), cellShapeControlMesh::insertFar(), globalIndex::isLocal(), lduPrimitiveMesh::lduPrimitiveMesh(), Pstream::listCombineGather(), Pstream::listCombineScatter(), masterUncollatedFileOperation::localObjectPath(), globalIndex::localSize(), globalIndex::localStart(), Pstream::mapCombineGather(), Pstream::mapCombineScatter(), mapDistribute::mapDistribute(), mapDistribute::mapDistribute(), mapDistributeBase::mapDistributeBase(), mapDistribute::mapDistributeBase(), mapDistributeBase::mapDistributeBase(), inverseDistance::markDonors(), trackingInverseDistance::markDonors(), trackingInverseDistance::markPatchesAsHoles(), inverseDistance::markPatchesAsHoles(), masterUncollatedFileOperation::masterOp(), masterUncollatedFileOperation::masterOp(), PstreamBuffers::maxNonLocalRecvCount(), globalIndex::maxNonLocalSize(), processorColour::myColour(), UPstream::myWorld(), UPstream::myWorldID(), processorTopology::New(), masterUncollatedFileOperation::NewIFstream(), regionSplit::nLocalRegions(), InflationInjection< CloudType >::parcelsToInject(), argList::parse(), pointHistory::pointHistory(), ParticlePostProcessing< CloudType >::postFace(), ParticlePostProcessing< CloudType >::postPatch(), powerLawLopesdaCostaZone::powerLawLopesdaCostaZone(), collatedFileOperation::printBanner(), mapDistributeBase::printLayout(), fileOperation::printRanks(), processorTopology::procAdjacency(), GAMGAgglomeration::procAgglomerateLduAddressing(), GAMGAgglomeration::procAgglomerateRestrictAddressing(), backgroundMeshDecomposition::procBounds(), processorField::processorField(), globalIndex::range(), masterUncollatedFileOperation::read(), masterUncollatedFileOperation::read(), masterUncollatedFileOperation::readHeader(), masterUncollatedFileOperation::readStream(), mapDistributeBase::receive(), indexedVertex< Gt, Vb >::referred(), fvMeshSubset::reset(), faMeshBoundaryHalo::reset(), globalIndex::reset(), globalIndex::scatter(), Pstream::scatter(), Pstream::scatterList(), mapDistributeBase::schedule(), mapDistributeBase::send(), Time::setControls(), patchInjectionBase::setPositionAndCell(), box::setRefineFlags(), zoneDistribute::setUpCommforZone(), ParSortableList< Type >::sort(), KinematicSurfaceFilm< CloudType >::splashInteraction(), fileOperation::subRanks(), masterUncollatedFileOperation::sync(), globalIndex::toGlobal(), globalIndex::toGlobal(), globalIndex::toLocal(), mapDistributeBase::unionCombineMasks(), inverseDistance::update(), trackingInverseDistance::update(), oversetFvMeshBase::updateAddressing(), processorField::updateMesh(), patchInjectionBase::updateMesh(), propellerInfo::updateSampleDiskCells(), dynamicCode::waitForFile(), globalIndex::whichProcID(), FacePostProcessing< CloudType >::write(), ParticleHistogram< CloudType >::write(), ParticlePostProcessing< CloudType >::write(), box::writeBoxes(), meshToMeshMethod::writeConnectivity(), AMIInterpolation::writeFaceConnectivity(), externalCoupled::writeGeometry(), isoAdvection::writeIsoFaces(), fileWriter::writeProcIDs(), and extendedCellToFaceStencil::writeStencilStats().
master()
static bool master (const label communicator = worldComm) inline static
Definition at line 767 of file UPstream.H.
References UPstream::masterNo().
Referenced by abort::abort(), regIOobject::addWatch(), masterUncollatedFileOperation::addWatch(), Pstream::broadcast(), Foam::broadcastFile_recursive(), Foam::broadcastFile_single(), Pstream::broadcasts(), mappedPatchBase::calcMapping(), decomposedBlockData::calcNumProcs(), pointNoise::calculate(), surfaceNoise::calculate(), viewFactor::calculate(), writeFile::canResetFile(), writeFile::canWriteHeader(), writeFile::canWriteToFile(), argList::check(), fileWriter::checkFormatterValidity(), ZoneMesh< ZoneType, MeshType >::checkParallelSync(), argList::checkRootCase(), extractEulerianParticles::collectParticle(), processorColour::colour(), sizeDistribution::combineFields(), commSchedule::commSchedule(), logFiles::createFiles(), Foam::createReconstructMap(), Foam::createReconstructMap(), simpleGeomDecomp::decompose(), simpleGeomDecomp::decompose(), metisLikeDecomp::decomposeGeneral(), masterUncollatedFileOperation::dirPath(), systemCall::dispatch(), distributedTriSurfaceMesh::distribute(), distributedTriSurfaceMesh::distributedTriSurfaceMesh(), distributedTriSurfaceMesh::distributedTriSurfaceMesh(), distributedTriSurfaceMesh::distributedTriSurfaceMesh(), snappyVoxelMeshDriver::doRefine(), abort::end(), ensightSurfaceReader::ensightSurfaceReader(), Curle::execute(), momentum::execute(), wallHeatFlux::execute(), abort::execute(), externalFileCoupler::externalFileCoupler(), externalFileCoupler::externalFileCoupler(), masterUncollatedFileOperation::filePath(), logFiles::files(), logFiles::files(), distanceSurface::filterKeepLargestRegion(), distanceSurface::filterKeepNearestRegions(), distanceSurface::filterRegionProximity(), probes::findElements(), masterUncollatedFileOperation::findInstance(), masterUncollatedFileOperation::findTimes(), masterUncollatedFileOperation::findWatch(), STDMD::fit(), globalIndex::gather(), decomposedBlockData::gather(), globalIndex::gather(), externalCoupled::gatherAndCombine(), PatchTools::gatherAndMerge(), globalIndex::gatherInplace(), decomposedBlockData::gatherSlaveData(), coordSet::gatherSort(), ensightSurfaceReader::geometry(), masterUncollatedFileOperation::getFile(), codeStream::getFunction(), fileOperation::getGlobalHostIORanks(), Foam::getHostGroupIds(), Foam::getSelectedProcs(), masterUncollatedFileOperation::getState(), Random::globalGaussNormal(), globalIndex::globalIndex(), Random::globalPosition(), Random::globalPosition(), Random::globalPosition(), Random::globalRandomise01(), Random::globalSample01(), viewFactor::initialise(), surfaceNoise::initialise(), fileOperation::isIOrank(), JobInfo::JobInfo(), UPstream::listGatherValues(), UPstream::listScatterValues(), fileOperation::lookupAndCacheProcessorsPath(), LUscalarMatrix::LUscalarMatrix(), NURBS3DVolume::makeFolders(), error::master(), masterUncollatedFileOperation::masterOp(), masterUncollatedFileOperation::masterOp(), messageStream::masterStream(), debugWriter::mergeField(), surfaceWriter::mergeFieldTemplate(), globalIndex::mpiGather(), globalIndex::mpiGatherInplace(), globalIndex::mpiGatherInplaceOp(), ensightCase::newCloud(), ensightCase::newCloudData(), ensightCase::newData(), writeFile::newFile(), writeFile::newFileAtTime(), ensightCase::newGeometry(), masterUncollatedFileOperation::NewIFstream(), fvMeshTools::newMesh(), faMeshTools::newMesh(), fileOperation::nProcs(), objectiveManager::objectiveManager(), fileWriter::open(), InflationInjection< CloudType >::parcelsToInject(), argList::parse(), ParticleZoneInfo< CloudType >::ParticleZoneInfo(), SprayCloud< CloudType >::penetration(), pointHistory::pointHistory(), porosityModel::porosityModel(), probes::prepare(), collatedFileOperation::printBanner(), UPstream::printCommTree(), faMeshTools::printMeshChecks(), meshRefinement::printMeshInfo(), fileOperation::printRanks(), pointNoise::processData(), decomposedBlockData::read(), timeActivatedFileUpdate::read(), sampledSets::read(), externalCoupled::read(), writeFile::read(), sampledSurfaces::read(), masterUncollatedFileOperation::read(), masterUncollatedFileOperation::read(), uncollatedFileOperation::read(), decomposedBlockData::readBlocks(), decomposedBlockData::readBlocks(), lumpedPointState::readData(), baseIOdictionary::readData(), ensightSurfaceReader::readField(), masterUncollatedFileOperation::readHeader(), regIOobject::readHeaderOk(), masterUncollatedFileOperation::readObjects(), masterUncollatedFileOperation::readStream(), surfaceNoise::readSurfaceData(), externalCoupled::removeDataMaster(), externalCoupled::removeDataSlave(), RemoveParcels< CloudType >::RemoveParcels(), masterUncollatedFileOperation::removeWatch(), profilingPstream::report(), globalIndex::reset(), logFiles::resetNames(), masterUncollatedFileOperation::scatterList(), mapDistributeBase::schedule(), fvMatrix< Type >::setComponentReference(), fvMatrix< Type >::setComponentReference(), faMatrix< Type >::setReference(), ensightCase::setTime(), masterUncollatedFileOperation::setUnmodified(), globalMeshData::sharedPoints(), shortestPathSet::shortestPathSet(), externalFileCoupler::shutdown(), snappyVoxelMeshDriver::snappyVoxelMeshDriver(), rigidBodyMeshMotion::solve(), rigidBodyMeshMotionSolver::solve(), rigidBodyMotion::solve(), LUscalarMatrix::solve(), ParSortableList< Type >::sort(), SQP::SQP(), messageStream::stream(), surfaceNoise::surfaceAverage(), masterUncollatedFileOperation::sync(), hexRef8Data::sync(), syncTools::syncEdgeMap(), syncTools::syncPointMap(), triSurfaceMesh::triSurfaceMesh(), triSurfaceMesh::triSurfaceMesh(), IOobject::typeHeaderOk(), sixDoFRigidBodyMotion::update(), activePressureForceBaffleVelocityFvPatchVectorField::updateCoeffs(), electrostaticDepositionFvPatchScalarField::updateCoeffs(), lumpedPointDisplacementPointPatchVectorField::updateCoeffs(), updateMethod::updateMethod(), masterUncollatedFileOperation::updateStates(), fileMonitor::updateStates(), solution::upgradeSolverDict(), externalFileCoupler::useMaster(), externalFileCoupler::useSlave(), OFstreamCollator::waitAll(), externalFileCoupler::waitForMaster(), externalFileCoupler::waitForSlave(), surfaceFieldValue::write(), volFieldValue::write(), reactionsSensitivityAnalysis< chemistryType >::write(), regionSizeDistribution::write(), wallShearStress::write(), yPlus::write(), vtkCloud::write(), sizeDistribution::write(), energySpectrum::write(), timeInfo::write(), vtkWrite::write(), FacePostProcessing< CloudType >::write(), ParticleCollector< CloudType >::write(), ParticleHistogram< CloudType >::write(), ParticlePostProcessing< CloudType >::write(), ParticleZoneInfo< CloudType >::write(), SQP::write(), abaqusWriter::write(), boundaryDataWriter::write(), debugWriter::write(), foamWriter::write(), nastranWriter::write(), proxyWriter::write(), rawWriter::write(), starcdWriter::write(), vtkWriter::write(), x3dWriter::write(), effectivenessTable::write(), referenceTemperature::write(), objective::write(), NURBS3DCurve::write(), NURBS3DSurface::write(), patchWriter::write(), patchWriter::write(), patchWriter::write(), sensitivityBezier::write(), sensitivityBezierFI::write(), sensitivityVolBSplines::write(), sensitivityVolBSplinesFI::write(), OFstreamCollator::write(), NURBS3DCurve::write(), NURBS3DSurface::write(), histogramModel::write(), surfaceFieldValue::writeAll(), propellerInfo::writeAxialWake(), decomposedBlockData::writeBlocks(), ensightWriter::writeCollated(), updateMethod::writeCorrection(), NURBS3DVolume::writeCps(), decomposedBlockData::writeData(), vtkCloud::writeFields(), lumpedPointMovement::writeForcesAndMomentsVTP(), externalCoupled::writeGeometry(), objective::writeInstantaneousSeparator(), objective::writeInstantaneousValue(), isoAdvection::writeIsoFaces(), objective::writeMeanValue(), faMeshReconstructor::writeMesh(), patchMeshWriter::writeNeighIDs(), collatedFileOperation::writeObject(), decomposedBlockData::writeObject(), regIOobject::writeObject(), patchMeshWriter::writePatchIDs(), patchMeshWriter::writePoints(), faMeshTools::writeProcAddressing(), fileWriter::writeProcIDs(), lumpedPointMovement::writeStateVTP(), surfaceNoise::writeSurfaceData(), abaqusWriter::writeTemplate(), boundaryDataWriter::writeTemplate(), debugWriter::writeTemplate(), foamWriter::writeTemplate(), nastranWriter::writeTemplate(), rawWriter::writeTemplate(), starcdWriter::writeTemplate(), vtkWriter::writeTemplate(), x3dWriter::writeTemplate(), streamLineBase::writeToFile(), ensightWriter::writeUncollated(), surfaceFieldValue::writeValues(), NURBS3DSurface::writeVTK(), lumpedPointState::writeVTP(), propellerInfo::writeWake(), AMIWeights::writeWeightField(), NURBS3DCurve::writeWParses(), NURBS3DSurface::writeWParses(), NURBS3DCurve::writeWParses(), and NURBS3DSurface::writeWParses().
is_rank()
static bool is_rank (const label communicator = worldComm) inline static
Definition at line 774 of file UPstream.H.
Referenced by Pstream::exchange(), Pstream::exchange(), Foam::PstreamDetail::exchangeConsensus(), Pstream::exchangeSizes(), Pstream::exchangeSizes(), Pstream::exchangeSizes(), Pstream::exchangeSizes(), UPstream::is_parallel(), and UPstream::listScatterValues().
is_subrank()
static bool is_subrank (const label communicator = worldComm) inline static
Definition at line 780 of file UPstream.H.
References UPstream::masterNo().
Referenced by Foam::broadcastFile_recursive(), and Foam::broadcastFile_single().
is_parallel()
static bool is_parallel (const label communicator = worldComm) inline static
Definition at line 789 of file UPstream.H.
References UPstream::is_rank(), and UPstream::nProcs().
Referenced by Pstream::allGatherList(), UPstream::allGatherValues(), Pstream::broadcast(), Pstream::broadcasts(), Pstream::combineGather(), Pstream::combineReduce(), Pstream::combineScatter(), Pstream::exchange(), Pstream::exchange(), Foam::PstreamDetail::exchangeConsensus(), Foam::PstreamDetail::exchangeConsensus(), Pstream::gather(), Pstream::gatherList(), Pstream::listCombineGather(), Pstream::listCombineReduce(), Pstream::listCombineScatter(), UPstream::listGatherValues(), UPstream::listScatterValues(), Pstream::mapCombineGather(), Pstream::mapCombineReduce(), Pstream::mapCombineScatter(), Foam::reduce(), Pstream::scatter(), Pstream::scatterList(), and Foam::sumReduce().
parent()
static label parent (const label communicator) inline static
Definition at line 798 of file UPstream.H.
Referenced by UPstream::baseProcNo(), UPstream::procNo(), GAMGAgglomeration::prolongField(), UPstream::communicator::reset(), UPstream::communicator::reset(), and GAMGAgglomeration::restrictField().
procID()
static List< int > & procID (const label communicator) inline static
Definition at line 804 of file UPstream.H.
Referenced by UPstream::baseProcNo(), Foam::operator<<(), UList< T >::operator[](), UList< T >::operator[](), collatedFileOperation::processorsDir(), UPstream::procNo(), masterUncollatedFileOperation::read(), UPstream::commsStruct::reset(), mappedPatchFieldBase< Type >::retrieveField(), and mappedPatchFieldBase< Type >::storeField().
allWorlds()
static const wordList & allWorlds () inline static noexcept
Definition at line 813 of file UPstream.H.
Referenced by mappedPatchBase::calcMapping(), mappedPatchBase::masterWorld(), argList::parse(), Foam::printDOT(), and mappedPatchBase::sameWorld().
worldIDs()
static const labelList & worldIDs () inline static noexcept
Definition at line 819 of file UPstream.H.
myWorldID()
static label myWorldID () inline static
Definition at line 825 of file UPstream.H.
References UPstream::commGlobal(), and UPstream::myProcNo().
Referenced by mappedPatchBase::calcMapping(), multiWorldConnections::createComms(), and mappedPatchBase::masterWorld().
myWorld()
static const word & myWorld () inline static
Definition at line 831 of file UPstream.H.
References UPstream::commGlobal(), and UPstream::myProcNo().
Referenced by multiWorldConnections::addConnectionById(), multiWorldConnections::addConnectionByName(), mappedPatchBase::calcMapping(), argList::parse(), mappedPatchBase::sameWorld(), and mappedPatchBase::sampleMesh().
allProcs()
static rangeType allProcs (const label communicator = worldComm) inline static
Definition at line 840 of file UPstream.H.
References UPstream::nProcs().
Referenced by refinementHistory::distribute(), mapDistributeBase::distribute(), mapDistributeBase::distribute(), box::doRefineBoxes(), globalIndex::gather(), globalIndex::gather(), Foam::getSelectedProcs(), viewFactor::initialise(), inverseDistance::markDonors(), trackingInverseDistance::markDonors(), trackingInverseDistance::markPatchesAsHoles(), inverseDistance::markPatchesAsHoles(), globalIndex::mpiGather(), masterUncollatedFileOperation::read(), mapDistributeBase::receive(), mapDistributeBase::receive(), InteractionLists< ParticleType >::receiveReferredData(), globalIndex::scatter(), mapDistributeBase::send(), mapDistributeBase::send(), InteractionLists< ParticleType >::sendReferredData(), box::setRefineFlags(), ParSortableList< Type >::sort(), energySpectrum::write(), box::writeBoxes(), and externalCoupled::writeGeometry().
subProcs()
static rangeType subProcs (const label communicator = worldComm) inline static
Definition at line 847 of file UPstream.H.
References UPstream::nProcs().
Referenced by LUscalarMatrix::LUscalarMatrix(), masterUncollatedFileOperation::NewIFstream(), argList::parse(), masterUncollatedFileOperation::read(), decomposedBlockData::readBlocks(), decomposedBlockData::readBlocks(), masterUncollatedFileOperation::scatterList(), mapDistributeBase::schedule(), globalMeshData::sharedPoints(), LUscalarMatrix::solve(), syncTools::syncEdgeMap(), syncTools::syncPointMap(), patchWriter::write(), patchWriter::write(), patchWriter::write(), patchMeshWriter::writeNeighIDs(), patchMeshWriter::writePatchIDs(), and patchMeshWriter::writePoints().
linearCommunication()
const Foam::List< Foam::UPstream::commsStruct > & linearCommunication (const label communicator = worldComm) static
Definition at line 646 of file UPstream.C.
References UPstream::nProcs().
Referenced by UPstream::whichCommunication().
treeCommunication()
const Foam::List< Foam::UPstream::commsStruct > & treeCommunication (const label communicator = worldComm) static
Definition at line 659 of file UPstream.C.
References UPstream::nProcs().
Referenced by UPstream::whichCommunication().
whichCommunication()
static const List< commsStruct > & whichCommunication (const label communicator = worldComm) inline static
Definition at line 868 of file UPstream.H.
References UPstream::linearCommunication(), UPstream::nProcs(), UPstream::nProcsSimpleSum, and UPstream::treeCommunication().
Referenced by Pstream::allGatherList(), Pstream::combineGather(), Pstream::combineReduce(), Pstream::combineScatter(), Pstream::gather(), Pstream::gatherList(), Pstream::listCombineGather(), Pstream::listCombineReduce(), Pstream::listCombineScatter(), Pstream::mapCombineGather(), Pstream::mapCombineReduce(), Pstream::mapCombineScatter(), UPstream::printCommTree(), Foam::reduce(), Pstream::scatter(), and Pstream::scatterList().
msgType()
static int & msgType () inline static noexcept
Definition at line 883 of file UPstream.H.
Referenced by solidAbsorption::a(), mappedPatchBase::calcMapping(), masterUncollatedFileOperation::chMod(), meshRefinement::collectAndPrint(), mappedPatchBase::collectSamples(), processorColour::colour(), extendedCentredCellToCellStencil::compact(), extendedCentredCellToFaceStencil::compact(), extendedCentredFaceToCellStencil::compact(), GAMGAgglomeration::continueAgglomerating(), masterUncollatedFileOperation::cp(), inverseDistance::createStencil(), metisLikeDecomp::decomposeGeneral(), masterUncollatedFileOperation::dirPath(), faMeshDistributor::distribute(), mappedPatchBase::distribute(), solidAbsorption::e(), Foam::PstreamDetail::exchangeChunkedBuf(), Pstream::exchangeSizes(), masterUncollatedFileOperation::exists(), masterUncollatedFileOperation::filePath(), masterUncollatedFileOperation::fileSize(), distributedTriSurfaceMesh::findNearest(), mappedPatchBase::findSamples(), lduPrimitiveMesh::gather(), Foam::gAverage(), distributedTriSurfaceMesh::getVolumeType(), Foam::gSumCmptProd(), Foam::gSumProd(), masterUncollatedFileOperation::highResLastModified(), viewFactor::initialise(), cellCellStencil::interpolate(), regionModel::interRegionAMI(), masterUncollatedFileOperation::isDir(), masterUncollatedFileOperation::isFile(), masterUncollatedFileOperation::lastModified(), lduPrimitiveMesh::lduPrimitiveMesh(), masterUncollatedFileOperation::ln(), LUscalarMatrix::LUscalarMatrix(), oversetFvPatchField< Type >::manipulateMatrix(), mappedPatchFieldBase< Type >::mappedField(), mappedPatchFieldBase< Type >::mappedInternalField(), mappedPatchFieldBase< Type >::mappedWeightField(), mappedPatchFieldBase< Type >::mappedWeightField(), regionModel::mapRegionPatchField(), regionModel::mapRegionPatchField(), regionModel::mapRegionPatchInternalField(), debugWriter::mergeField(), surfaceWriter::mergeFieldTemplate(), masterUncollatedFileOperation::mkDir(), masterUncollatedFileOperation::mode(), masterUncollatedFileOperation::mv(), masterUncollatedFileOperation::mvBak(), masterUncollatedFileOperation::NewIFstream(), fileOperation::printRanks(), processorTopology::procAdjacency(), GAMGAgglomeration::procAgglomerateRestrictAddressing(), GAMGAgglomeration::prolongField(), decomposedBlockData::readBlocks(), decomposedBlockData::readBlocks(), masterUncollatedFileOperation::readDir(), masterUncollatedFileOperation::readHeader(), masterUncollatedFileOperation::readStream(), surfaceNoise::readSurfaceData(), lduMesh::reduce(), fvMatrix< Type >::relax(), faMeshBoundaryHalo::reset(), GAMGAgglomeration::restrictField(), mappedPatchBase::reverseDistribute(), masterUncollatedFileOperation::rm(), masterUncollatedFileOperation::rmDir(), mapDistributeBase::schedule(), LUscalarMatrix::solve(), surfaceNoise::surfaceAverage(), processorFaPatch::tag(), processorFvPatch::tag(), processorPolyPatch::tag(), processorCyclicPolyPatch::tag(), masterUncollatedFileOperation::type(), oversetFvMeshBase::updateAddressing(), mappedFixedInternalValueFvPatchField< Type >::updateCoeffs(), mappedFlowRateFvPatchVectorField::updateCoeffs(), mappedVelocityFluxFixedValueFvPatchField::updateCoeffs(), filmPyrolysisTemperatureCoupledFvPatchScalarField::updateCoeffs(), filmPyrolysisVelocityCoupledFvPatchVectorField::updateCoeffs(), alphatFilmWallFunctionFvPatchScalarField::updateCoeffs(), greyDiffusiveRadiationMixedFvPatchScalarField::updateCoeffs(), MarshakRadiationFvPatchScalarField::updateCoeffs(), MarshakRadiationFixedTemperatureFvPatchScalarField::updateCoeffs(), wideBandDiffusiveRadiationMixedFvPatchScalarField::updateCoeffs(), thermalBaffle1DFvPatchScalarField< solidType >::updateCoeffs(), turbulentTemperatureCoupledBaffleMixedFvPatchScalarField::updateCoeffs(), turbulentTemperatureRadCoupledMixedFvPatchScalarField::updateCoeffs(), distributedDILUPreconditioner::updateMatrixInterfaces(), globalMeshData::updateMesh(), Sampled< Type >::value(), OFstreamCollator::write(), decomposedBlockData::writeBlocks(), and surfaceNoise::writeSurfaceData().
commsType() [1/2]
commsTypes commsType () const inline noexcept
Definition at line 889 of file UPstream.H.
Referenced by UIPstream::read(), UIPstream::read(), UIPstream::UIPstream(), UIPstream::UIPstream(), and UOPstream::write().
commsType() [2/2]
commsTypes commsType (const commsTypes ct) inline noexcept
Definition at line 896 of file UPstream.H.
shutdown()
void shutdown (int errNo = 0) static
Definition at line 51 of file UPstream.C.
Referenced by ParRunControl::~ParRunControl().
abort()
void abort () static
Definition at line 62 of file UPstream.C.
Referenced by error::simpleExit().
exit()
void exit (int errNo = 1) static
Definition at line 55 of file UPstream.C.
Referenced by argList::argList(), Foam::exitNow(), argList::parse(), ParRunControl::runPar(), and error::simpleExit().
allToAll() [1/2]
void allToAll (const UList< int32_t > & sendData, UList< int32_t > & recvData, const label communicator = worldComm) static
Definition at line 42 of file UPstreamAllToAll.C.
Referenced by fvMeshDistribute::distribute(), and Pstream::exchangeSizes().
allToAll() [2/2]
void allToAll (const UList< int64_t > & sendData, UList< int64_t > & recvData, const label communicator = worldComm) static
Definition at line 43 of file UPstreamAllToAll.C.
allToAllConsensus() [1/4]
void allToAllConsensus (const UList< int32_t > & sendData, UList< int32_t > & recvData, const int tag, const label communicator = worldComm) static
Definition at line 74 of file UPstreamAllToAll.C.
Referenced by Pstream::exchangeSizes(), and Pstream::exchangeSizes().
allToAllConsensus() [2/4]
void allToAllConsensus (const UList< int64_t > & sendData, UList< int64_t > & recvData, const int tag, const label communicator = worldComm) static
Definition at line 75 of file UPstreamAllToAll.C.
allToAllConsensus() [3/4]
void allToAllConsensus (const Map< int32_t > & sendData, Map< int32_t > & recvData, const int tag, const label communicator = worldComm) static
Definition at line 74 of file UPstreamAllToAll.C.
allToAllConsensus() [4/4]
void allToAllConsensus (const Map< int64_t > & sendData, Map< int64_t > & recvData, const int tag, const label communicator = worldComm) static
Definition at line 75 of file UPstreamAllToAll.C.
mpiGather()
void mpiGather (const char * sendData, char * recvData, int count, const label communicator = worldComm) static
Receive identically-sized char data from all ranks.
Parameters
sendData On rank: individual value to send
recvData On master: receive buffer with all values
count Number of send/recv data per rank. Globally consistent!
Definition at line 61 of file UPstreamGatherScatter.C.
Referenced by fileOperation::getGlobalHostIORanks(), Foam::getHostGroupIds(), UPstream::listGatherValues(), and profilingPstream::report().
mpiScatter()
void mpiScatter (const char * sendData, char * recvData, int count, const label communicator = worldComm) static
Send identically-sized char data to all ranks.
Parameters
sendData On master: send buffer with all values
recvData On rank: individual value to receive
count Number of send/recv data per rank. Globally consistent!
Definition at line 61 of file UPstreamGatherScatter.C.
Referenced by UPstream::listScatterValues().
mpiAllGather()
void mpiAllGather (char * allData, int count, const label communicator = worldComm) static
Gather/scatter identically-sized char data.
Send data from proc slot, receive into all slots
Parameters
allData On all ranks: the base of the data locations
count Number of send/recv data per rank. Globally consistent!
Definition at line 61 of file UPstreamGatherScatter.C.
Referenced by Pstream::allGatherList(), and UPstream::allGatherValues().
gather() [1/7]
void gather (const char * sendData, int sendCount, char * recvData, const UList< int > & recvCounts, const UList< int > & recvOffsets, const label communicator = worldComm) static
Receive variable length char data from all ranks.
Parameters
sendCount Ignored on master if recvCount[0] == 0
recvData Ignored on non-root rank
recvCounts Ignored on non-root rank
recvOffsets Ignored on non-root rank
Definition at line 101 of file UPstreamGatherScatter.C.
Referenced by decomposedBlockData::gather(), decomposedBlockData::gatherSlaveData(), and globalIndex::mpiGather().
scatter() [1/7]
void scatter (const char * sendData, const UList< int > & sendCounts, const UList< int > & sendOffsets, char * recvData, int recvCount, const label communicator = worldComm) static
Send variable length char data to all ranks.
Parameters
sendData Ignored on non-root rank
sendCounts Ignored on non-root rank
sendOffsets Ignored on non-root rank
Definition at line 101 of file UPstreamGatherScatter.C.
gather() [2/7]
void gather (const int32_t * sendData, int sendCount, int32_t * recvData, const UList< int > & recvCounts, const UList< int > & recvOffsets, const label communicator = worldComm) static
Receive variable length int32_t data from all ranks.
Parameters
sendCount Ignored on master if recvCount[0] == 0
recvData Ignored on non-root rank
recvCounts Ignored on non-root rank
recvOffsets Ignored on non-root rank
Definition at line 102 of file UPstreamGatherScatter.C.
scatter() [2/7]
void scatter (const int32_t * sendData, const UList< int > & sendCounts, const UList< int > & sendOffsets, int32_t * recvData, int recvCount, const label communicator = worldComm) static
Send variable length int32_t data to all ranks.
Parameters
sendData Ignored on non-root rank
sendCounts Ignored on non-root rank
sendOffsets Ignored on non-root rank
Definition at line 102 of file UPstreamGatherScatter.C.
gather() [3/7]
void gather (const int64_t * sendData, int sendCount, int64_t * recvData, const UList< int > & recvCounts, const UList< int > & recvOffsets, const label communicator = worldComm) static
Receive variable length int64_t data from all ranks.
Parameters
sendCount Ignored on master if recvCount[0] == 0
recvData Ignored on non-root rank
recvCounts Ignored on non-root rank
recvOffsets Ignored on non-root rank
Definition at line 103 of file UPstreamGatherScatter.C.
scatter() [3/7]
void scatter (const int64_t * sendData, const UList< int > & sendCounts, const UList< int > & sendOffsets, int64_t * recvData, int recvCount, const label communicator = worldComm) static
Send variable length int64_t data to all ranks.
Parameters
sendData Ignored on non-root rank
sendCounts Ignored on non-root rank
sendOffsets Ignored on non-root rank
Definition at line 103 of file UPstreamGatherScatter.C.
gather() [4/7]
void gather (const uint32_t * sendData, int sendCount, uint32_t * recvData, const UList< int > & recvCounts, const UList< int > & recvOffsets, const label communicator = worldComm) static
Receive variable length uint32_t data from all ranks.
Parameters
sendCount Ignored on master if recvCount[0] == 0
recvData Ignored on non-root rank
recvCounts Ignored on non-root rank
recvOffsets Ignored on non-root rank
Definition at line 104 of file UPstreamGatherScatter.C.
scatter() [4/7]
void scatter (const uint32_t * sendData, const UList< int > & sendCounts, const UList< int > & sendOffsets, uint32_t * recvData, int recvCount, const label communicator = worldComm) static
Send variable length uint32_t data to all ranks.
Parameters
sendData Ignored on non-root rank
sendCounts Ignored on non-root rank
sendOffsets Ignored on non-root rank
Definition at line 104 of file UPstreamGatherScatter.C.
gather() [5/7]
void gather (const uint64_t * sendData, int sendCount, uint64_t * recvData, const UList< int > & recvCounts, const UList< int > & recvOffsets, const label communicator = worldComm) static
Receive variable length uint64_t data from all ranks.
Parameters
sendCount Ignored on master if recvCount[0] == 0
recvData Ignored on non-root rank
recvCounts Ignored on non-root rank
recvOffsets Ignored on non-root rank
Definition at line 105 of file UPstreamGatherScatter.C.
scatter() [5/7]
void scatter (const uint64_t * sendData, const UList< int > & sendCounts, const UList< int > & sendOffsets, uint64_t * recvData, int recvCount, const label communicator = worldComm) static
Send variable length uint64_t data to all ranks.
Parameters
sendData Ignored on non-root rank
sendCounts Ignored on non-root rank
sendOffsets Ignored on non-root rank
Definition at line 105 of file UPstreamGatherScatter.C.
gather() [6/7]
void gather (const float * sendData, int sendCount, float * recvData, const UList< int > & recvCounts, const UList< int > & recvOffsets, const label communicator = worldComm) static
Receive variable length float data from all ranks.
Parameters
sendCount Ignored on master if recvCount[0] == 0
recvData Ignored on non-root rank
recvCounts Ignored on non-root rank
recvOffsets Ignored on non-root rank
Definition at line 106 of file UPstreamGatherScatter.C.
scatter() [6/7]
void scatter (const float * sendData, const UList< int > & sendCounts, const UList< int > & sendOffsets, float * recvData, int recvCount, const label communicator = worldComm) static
Send variable length float data to all ranks.
Parameters
sendData Ignored on non-root rank
sendCounts Ignored on non-root rank
sendOffsets Ignored on non-root rank
Definition at line 106 of file UPstreamGatherScatter.C.
gather() [7/7]
void gather (const double * sendData, int sendCount, double * recvData, const UList< int > & recvCounts, const UList< int > & recvOffsets, const label communicator = worldComm) static
Receive variable length double data from all ranks.
Parameters
sendCount Ignored on master if recvCount[0] == 0
recvData Ignored on non-root rank
recvCounts Ignored on non-root rank
recvOffsets Ignored on non-root rank
Definition at line 107 of file UPstreamGatherScatter.C.
scatter() [7/7]
void scatter (const double * sendData, const UList< int > & sendCounts, const UList< int > & sendOffsets, double * recvData, int recvCount, const label communicator = worldComm) static
Send variable length double data to all ranks.
Parameters
sendData Ignored on non-root rank
sendCounts Ignored on non-root rank
sendOffsets Ignored on non-root rank
Definition at line 107 of file UPstreamGatherScatter.C.
allGatherValues() [1/2]
template<class T > static List< T > allGatherValues (const T & localValue, const label communicator = worldComm) static
Referenced by globalIndex::reset().
listGatherValues() [1/2]
template<class T > static List< T > listGatherValues (const T & localValue, const label communicator = worldComm) static
Referenced by globalIndex::globalIndex(), globalIndex::globalIndex(), globalIndex::reset(), and globalIndex::reset().
listScatterValues()
template<class T > T listScatterValues (const UList< T > & allValues, const label communicator = worldComm) static
Definition at line 104 of file UPstreamTemplates.C.
References Foam::abort(), UPtrList< T >::empty(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, UPstream::is_parallel(), UPstream::is_rank(), UPstream::master(), UPstream::mpiScatter(), UPstream::nProcs(), UPtrList< T >::size(), T, and Foam::Zero.
broadcast()
bool broadcast (char * buf, const std::streamsize bufSize, const label communicator, const int rootProcNo = masterNo()) static
Definition at line 25 of file UPstreamBroadcast.C.
Referenced by Pstream::broadcast(), Foam::broadcastFile_recursive(), Foam::broadcastFile_single(), Foam::getHostGroupIds(), and globalIndex::mpiGather().
reduceAnd()
void reduceAnd (bool & value, const label communicator = worldComm) static
Definition at line 28 of file UPstreamReduce.C.
Referenced by faMeshReconstructor::faMeshReconstructor(), and Foam::returnReduceAnd().
reduceOr()
void reduceOr (bool & value, const label communicator = worldComm) static
Definition at line 31 of file UPstreamReduce.C.
Referenced by polyBoundaryMesh::checkDefinition(), primitiveMesh::checkUpperTriangular(), snappyLayerDriver::doLayers(), PstreamBuffers::finishedSends(), masterUncollatedFileOperation::readStream(), and Foam::returnReduceOr().
waitRequests() [3/3]
static void waitRequests () inline static
Definition at line 1184 of file UPstream.H.
References UPstream::waitRequests().
Referenced by GAMGAgglomeration::agglomerateLduAddressing(), meshWaveAddressing::correct(), cellCellStencil::correctBoundaryConditions(), oversetFvMeshBase::correctBoundaryConditions(), oversetFvMeshBase::correctCoupledBoundaryConditions(), metisLikeDecomp::decomposeGeneral(), faMeshDistributor::distribute(), mapDistributeBase::distribute(), mapDistributeBase::distribute(), GeometricBoundaryField< Type, PatchField, GeoMesh >::evaluate(), Foam::evaluateConstraintTypes(), GeometricBoundaryField< Type, PatchField, GeoMesh >::evaluateCoupled(), Foam::PstreamDetail::exchangeBuf(), Foam::PstreamDetail::exchangeConsensus(), Foam::PstreamDetail::exchangeConsensus(), Foam::PstreamDetail::exchangeContainer(), Foam::PstreamDetail::exchangeContainer(), mapDistributeBase::exchangeMasks(), Pstream::exchangeSizes(), globalIndex::gather(), globalIndex::gather(), globalIndex::gatherValues(), GAMGProcAgglomeration::globalCellCells(), lduPrimitiveMesh::globalCellCells(), mapDistributeBase::receive(), InteractionLists< ParticleType >::receiveReferredData(), globalIndex::scatter(), syncTools::syncBoundaryFaceList(), syncTools::syncFaceList(), LduMatrix< Type, DType, LUType >::updateMatrixInterfaces(), distributedDILUPreconditioner::updateMatrixInterfaces(), lduMatrix::updateMatrixInterfaces(), distributedDILUPreconditioner::wait(), UPstream::waitRequests(), and OFstreamCollator::write().
firstSlave()
static constexpr int firstSlave () inline static constexpr noexcept
Definition at line 1188 of file UPstream.H.
lastSlave()
static int lastSlave (const label communicator = worldComm) inline static
Definition at line 1195 of file UPstream.H.
References UPstream::nProcs().
allGatherValues() [2/2]
template<class T > Foam::List< T > allGatherValues (const T & localValue, const label comm)
Definition at line 24 of file UPstreamTemplates.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, UPstream::is_parallel(), UPstream::mpiAllGather(), UPstream::myProcNo(), UPstream::nProcs(), PtrList< T >::resize(), and T.
listGatherValues() [2/2]
template<class T > Foam::List< T > listGatherValues (const T & localValue, const label comm)
Definition at line 60 of file UPstreamTemplates.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, UPstream::is_parallel(), UPstream::master(), UPstream::mpiGather(), UPstream::nProcs(), PtrList< T >::resize(), and T.
Member Data Documentation
commsTypeNames
const Foam::Enum< Foam::UPstream::commsTypes > commsTypeNames static
Definition at line 78 of file UPstream.H.
Referenced by debugWriter::debugWriter(), GeometricBoundaryField< Type, PatchField, GeoMesh >::evaluate(), GeometricBoundaryField< Type, PatchField, GeoMesh >::evaluateCoupled(), PstreamBuffers::finishedGathers(), PstreamBuffers::finishedScatters(), PstreamBuffers::finishedSends(), LduMatrix< Type, DType, LUType >::initMatrixInterfaces(), lduMatrix::initMatrixInterfaces(), argList::parse(), surfaceNoise::read(), decomposedBlockData::readBlocks(), decomposedBlockData::readBlocks(), surfaceWriter::surfaceWriter(), LduMatrix< Type, DType, LUType >::updateMatrixInterfaces(), lduMatrix::updateMatrixInterfaces(), and decomposedBlockData::writeBlocks().
floatTransfer
bool floatTransfer static
Definition at line 280 of file UPstream.H.
Referenced by processorLduInterface::compressedReceive(), processorLduInterface::compressedSend(), processorFvPatchField< Type >::evaluate(), processorFvPatchField< Type >::initEvaluate(), processorFvPatchField< Type >::initInterfaceMatrixUpdate(), processorFvPatchField< Type >::initInterfaceMatrixUpdate(), processorGAMGInterfaceField::initInterfaceMatrixUpdate(), calculatedProcessorGAMGInterfaceField::initInterfaceMatrixUpdate(), argList::parse(), processorFvPatchField< Type >::updateInterfaceMatrix(), processorFvPatchField< Type >::updateInterfaceMatrix(), processorGAMGInterfaceField::updateInterfaceMatrix(), and calculatedProcessorGAMGInterfaceField::updateInterfaceMatrix().
nProcsSimpleSum
int nProcsSimpleSum static
Definition at line 283 of file UPstream.H.
Referenced by argList::parse(), UPstream::commsStruct::reset(), and UPstream::whichCommunication().
nProcsNonblockingExchange
int nProcsNonblockingExchange static
Definition at line 287 of file UPstream.H.
Referenced by Pstream::exchangeSizes(), and argList::parse().
nPollProcInterfaces
int nPollProcInterfaces static
Definition at line 290 of file UPstream.H.
Referenced by argList::parse(), LduMatrix< Type, DType, LUType >::updateMatrixInterfaces(), and lduMatrix::updateMatrixInterfaces().
defaultCommsType
Foam::UPstream::commsTypes defaultCommsType static
Definition at line 293 of file UPstream.H.
Referenced by faBoundaryMesh::calcGeometry(), oversetFvMeshBase::correctBoundaryConditions(), oversetFvMeshBase::correctCoupledBoundaryConditions(), mapDistributeBase::distribute(), mappedPatchBase::distribute(), GeometricBoundaryField< Type, PatchField, GeoMesh >::evaluate(), Foam::evaluateConstraintTypes(), GeometricBoundaryField< Type, PatchField, GeoMesh >::evaluateCoupled(), LduMatrix< Type, DType, LUType >::initMatrixInterfaces(), lduMatrix::initMatrixInterfaces(), faBoundaryMesh::movePoints(), pointBoundaryMesh::movePoints(), polyBoundaryMesh::movePoints(), processorTopology::New(), argList::parse(), processorCyclicFvPatchField< Type >::processorCyclicFvPatchField(), mapDistributeBase::reverseDistribute(), mapDistributeBase::reverseDistribute(), mappedPatchBase::reverseDistribute(), syncTools::syncBoundaryFaceList(), LduMatrix< Type, DType, LUType >::updateMatrixInterfaces(), lduMatrix::updateMatrixInterfaces(), faBoundaryMesh::updateMesh(), pointBoundaryMesh::updateMesh(), and polyBoundaryMesh::updateMesh().
maxCommsSize
int maxCommsSize static
Definition at line 296 of file UPstream.H.
Referenced by Foam::broadcastFile_single(), Pstream::exchange(), Pstream::exchange(), and Foam::PstreamDetail::exchangeChunkedBuf().
tuning_NBX_
int tuning_NBX_ static
Definition at line 299 of file UPstream.H.
Referenced by Foam::PstreamDetail::exchangeConsensus(), and argList::parse().
mpiBufferSize
const int mpiBufferSize static
Definition at line 302 of file UPstream.H.
Referenced by attachOurBuffers().
worldComm
Foam::label worldComm static
Definition at line 309 of file UPstream.H.
Referenced by masterUncollatedFileOperation::addWatch(), decompositionMethod::calcCellCells(), decompositionMethod::calcCellCells(), surfaceNoise::calculate(), multiWorldConnections::comms(), UPstream::commWorld(), UPstream::commWorld(), metisLikeDecomp::decomposeGeneral(), masterUncollatedFileOperation::dirPath(), ensightSurfaceReader::ensightSurfaceReader(), masterUncollatedFileOperation::filePath(), masterUncollatedFileOperation::findInstance(), masterUncollatedFileOperation::findTimes(), masterUncollatedFileOperation::findWatch(), ensightSurfaceReader::geometry(), multiWorldConnections::getCommById(), multiWorldConnections::getCommByName(), Foam::getCommPattern(), masterUncollatedFileOperation::getFile(), fileOperation::getGlobalHostIORanks(), Foam::getSelectedProcs(), masterUncollatedFileOperation::getState(), masterUncollatedFileOperation::highResLastModified(), viewFactor::initialise(), surfaceNoise::initialise(), masterUncollatedFileOperation::lastModified(), masterUncollatedFileOperation::localObjectPath(), fileOperation::lookupAndCacheProcessorsPath(), messageStream::masterStream(), debugWriter::mergeField(), surfaceWriter::mergeFieldTemplate(), fvMeshTools::newMesh(), faMeshTools::newMesh(), fileOperation::printRanks(), masterUncollatedFileOperation::read(), uncollatedFileOperation::read(), decomposedBlockData::readBlocks(), lumpedPointState::readData(), ensightSurfaceReader::readField(), masterUncollatedFileOperation::readHeader(), masterUncollatedFileOperation::readObjects(), masterUncollatedFileOperation::readStream(), surfaceNoise::readSurfaceData(), masterUncollatedFileOperation::removeWatch(), Time::setMonitoring(), masterUncollatedFileOperation::setUnmodified(), fileOperation::subRanks(), surfaceNoise::surfaceAverage(), fileOperation::sync(), masterUncollatedFileOperation::sync(), globalMeshData::updateMesh(), masterUncollatedFileOperation::updateStates(), and surfaceNoise::writeSurfaceData().
warnComm
Foam::label warnComm static
Definition at line 312 of file UPstream.H.
Referenced by UPstream::commWarn(), messageStream::masterStream(), and Foam::reduce().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOstreams/Pstreams/UPstream.H
src/OpenFOAM/db/IOstreams/Pstreams/UPstream.C
src/OpenFOAM/db/IOstreams/Pstreams/UPstreamTemplates.C
src/Pstream/dummy/UPstream.C
src/Pstream/dummy/UPstreamAllToAll.C
src/Pstream/dummy/UPstreamBroadcast.C
src/Pstream/dummy/UPstreamGatherScatter.C
src/Pstream/dummy/UPstreamReduce.C
src/Pstream/dummy/UPstreamRequest.C
src/Pstream/mpi/UPstream.C
src/Pstream/mpi/UPstreamAllToAll.C
src/Pstream/mpi/UPstreamBroadcast.C
src/Pstream/mpi/UPstreamGatherScatter.C
src/Pstream/mpi/UPstreamReduce.C
src/Pstream/mpi/UPstreamRequest.C