OpenFOAM: turbulentTemperatureCoupledBaffleMixedFvPatchScalarField Class Reference
turbulentTemperatureCoupledBaffleMixedFvPatchScalarField Class Reference
Mixed boundary condition for temperature, to be used for heat-transfer on back-to-back baffles. Optional thin thermal layer resistances can be specified through thicknessLayers and kappaLayers entries.
#include <turbulentTemperatureCoupledBaffleMixedFvPatchScalarField.H>
Public Member Functions
TypeName ("compressible::turbulentTemperatureCoupledBaffleMixed")
turbulentTemperatureCoupledBaffleMixedFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
turbulentTemperatureCoupledBaffleMixedFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
turbulentTemperatureCoupledBaffleMixedFvPatchScalarField (const turbulentTemperatureCoupledBaffleMixedFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
turbulentTemperatureCoupledBaffleMixedFvPatchScalarField (const turbulentTemperatureCoupledBaffleMixedFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
turbulentTemperatureCoupledBaffleMixedFvPatchScalarField (const turbulentTemperatureCoupledBaffleMixedFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual void autoMap (const fvPatchFieldMapper &)
virtual void rmap (const fvPatchField< scalar > &, const labelList &)
virtual tmp< scalarField > kappa (const scalarField &Tp) const
virtual void updateCoeffs ()
virtual void manipulateMatrix (fvMatrix< scalar > &m, const label iMatrix, const direction cmpt)
virtual void write (Ostream &os) const
Public Member Functions inherited from temperatureCoupledBase
temperatureCoupledBase (const fvPatch &patch, const KMethodType method=KMethodType::mtFluidThermo)
temperatureCoupledBase (const fvPatch &patch, const KMethodType method, const word &kappaName, const word &alphaName, const word &alphaAniName)
temperatureCoupledBase (const fvPatch &patch, const dictionary &dict)
temperatureCoupledBase (const fvPatch &patch, const temperatureCoupledBase &base)
temperatureCoupledBase (const temperatureCoupledBase &base)
virtual ~temperatureCoupledBase ()=default
word KMethod () const
const word & kappaName () const noexcept
const word & alphaName () const noexcept
virtual tmp< scalarField > alpha (const scalarField &Tp) const
void write (Ostream &os) const
Public Member Functions inherited from mappedPatchFieldBase< scalar >
mappedPatchFieldBase (const mappedPatchBase &mapper, const fvPatchField< scalar > &patchField, const word &fieldName, const bool setAverage, const scalar average, const word &interpolationScheme)
mappedPatchFieldBase (const mappedPatchBase &mapper, const fvPatchField< scalar > &patchField, const dictionary &dict)
mappedPatchFieldBase (const mappedPatchBase &mapper, const fvPatchField< scalar > &patchField, const dictionary &dict, const Field< scalar > &fld)
mappedPatchFieldBase (const mappedPatchBase &mapper, const fvPatchField< scalar > &patchField)
mappedPatchFieldBase (const mappedPatchFieldBase< scalar > &mapper)
mappedPatchFieldBase (const mappedPatchBase &mapper, const fvPatchField< scalar > &patchField, const mappedPatchFieldBase< scalar > &base)
virtual ~mappedPatchFieldBase ()=default
const GeometricField< T, fvPatchField, volMesh > & sampleField (const word &fieldName) const
const GeometricField< scalar, fvPatchField, volMesh > & sampleField () const
const Foam::GeometricField< Type2, Foam::fvPatchField, Foam::volMesh > & sampleField (const word &fieldName) const
virtual tmp< Field< scalar > > mappedField () const
virtual tmp< Field< scalar > > mappedInternalField () const
virtual tmp< scalarField > mappedWeightField () const
virtual void mappedWeightField (const word &weightFieldName, tmp< scalarField > &thisWeights, tmp< scalarField > &nbrWeights) const
void distribute (const word &fieldName, Field< T > &newValues) const
Additional Inherited Members
Public Types inherited from temperatureCoupledBase
enum KMethodType {
mtFluidThermo , mtSolidThermo , mtDirectionalSolidThermo , mtLookup ,
mtFunction
}
Static Public Member Functions inherited from mappedPatchFieldBase< scalar >
static const mappedPatchBase & mapper (const fvPatch &p, const DimensionedField< scalar, volMesh > &iF)
Protected Member Functions inherited from mappedPatchFieldBase< scalar >
void initRetrieveField (const objectRegistry &obr, const word &region, const word &patch, const labelListList &map, const word &fieldName, const Field< T > &fld) const
void initRetrieveField (const word &fieldName, const Field< T > &fld) const
bool storeAndRetrieveField (const word &fieldName, const label myComm, const labelListList &subMap, const label constructSize, const labelListList &constructMap, const labelListList &address, const scalarListList &weights, Field< T > &fld) const
void storeField (const objectRegistry &obr, const word &region, const word &patch, const label myComm, const labelListList &procToMap, const word &fieldName, const Field< T > &fld) const
bool retrieveField (const bool allowUnset, const objectRegistry &obr, const word &region, const word &patch, const label myComm, const labelListList &procToMap, const word &fieldName, Field< T > &fld) const
Protected Attributes inherited from temperatureCoupledBase
const fvPatch & patch_
const KMethodType method_
const word kappaName_
const word alphaName_
const word alphaAniName_
autoPtr< PatchFunction1< scalar > > kappaFunction1_
autoPtr< PatchFunction1< scalar > > alphaFunction1_
Protected Attributes inherited from mappedPatchFieldBase< scalar >
const mappedPatchBase & mapper_
const fvPatchField< scalar > & patchField_
word fieldName_
const bool setAverage_
const scalar average_
word interpolationScheme_
Static Protected Attributes inherited from temperatureCoupledBase
static const Enum< KMethodType > KMethodTypeNames_
Detailed Description
Mixed boundary condition for temperature, to be used for heat-transfer on back-to-back baffles. Optional thin thermal layer resistances can be specified through thicknessLayers and kappaLayers entries.
Specifies gradient and temperature such that the equations are the same on both sides:
refGradient = zero gradient
refValue = neighbour value
mixFraction = nbrKDelta / (nbrKDelta + myKDelta())
where KDelta is heat-transfer coefficient K * deltaCoeffs
The thermal conductivity kappa can either be retrieved from various possible sources, as detailed in the class temperatureCoupledBase.
Usage
Property Description Required Default value
Tnbr name of the field no T
thicknessLayers list of thicknesses per layer [m] no
kappaLayers list of thermal conductivities per layer [W/m/K] no
thicknessLayer single thickness of layer [m] no
kappaLayer corresponding thermal conductivity [W/m/K] no
kappaMethod inherited from temperatureCoupledBase inherited
kappa inherited from temperatureCoupledBase inherited
Example of the boundary condition specification:
    <patchName>
    {
        type            compressible::turbulentTemperatureCoupledBaffleMixed;
        Tnbr            T;
        thicknessLayers (0.1 0.2 0.3 0.4);
        kappaLayers     (1 2 3 4);
        kappaMethod     lookup;
        kappa           kappa;
        value           uniform 300;
    }
Needs to be on underlying mapped(Wall)FvPatch.
See also
Foam::temperatureCoupledBase
Source files
turbulentTemperatureCoupledBaffleMixedFvPatchScalarField.H
turbulentTemperatureCoupledBaffleMixedFvPatchScalarField.C
Definition at line 136 of file turbulentTemperatureCoupledBaffleMixedFvPatchScalarField.H.
Constructor & Destructor Documentation
turbulentTemperatureCoupledBaffleMixedFvPatchScalarField() [1/5]
turbulentTemperatureCoupledBaffleMixedFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 37 of file turbulentTemperatureCoupledBaffleMixedFvPatchScalarField.C.
References Foam::Zero.
turbulentTemperatureCoupledBaffleMixedFvPatchScalarField() [2/5]
turbulentTemperatureCoupledBaffleMixedFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
// Store patch value as initial guess when running in database mode mappedPatchFieldBase<scalar>::initRetrieveField (this->internalField().name(), *this); mappedPatchFieldBase<scalar>::initRetrieveField (this->internalField().name() + "_weights", this->patch().deltaCoeffs());
Definition at line 84 of file turbulentTemperatureCoupledBaffleMixedFvPatchScalarField.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, IOobjectOption::MUST_READ, PatchFunction1< Type >::NewIfPresent(), p, WarningInFunction, and Foam::Zero.
turbulentTemperatureCoupledBaffleMixedFvPatchScalarField() [3/5]
turbulentTemperatureCoupledBaffleMixedFvPatchScalarField (const turbulentTemperatureCoupledBaffleMixedFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 59 of file turbulentTemperatureCoupledBaffleMixedFvPatchScalarField.C.
turbulentTemperatureCoupledBaffleMixedFvPatchScalarField() [4/5]
turbulentTemperatureCoupledBaffleMixedFvPatchScalarField (const turbulentTemperatureCoupledBaffleMixedFvPatchScalarField & wtcsf)
Definition at line 192 of file turbulentTemperatureCoupledBaffleMixedFvPatchScalarField.C.
turbulentTemperatureCoupledBaffleMixedFvPatchScalarField() [5/5]
turbulentTemperatureCoupledBaffleMixedFvPatchScalarField (const turbulentTemperatureCoupledBaffleMixedFvPatchScalarField & wtcsf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 169 of file turbulentTemperatureCoupledBaffleMixedFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("compressible::turbulentTemperatureCoupledBaffleMixed")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 208 of file turbulentTemperatureCoupledBaffleMixedFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 227 of file turbulentTemperatureCoupledBaffleMixedFvPatchScalarField.H.
autoMap()
void autoMap (const fvPatchFieldMapper & mapper) virtual
Implements temperatureCoupledBase.
Definition at line 216 of file turbulentTemperatureCoupledBaffleMixedFvPatchScalarField.C.
References temperatureCoupledBase::autoMap(), and mappedPatchFieldBase< scalar >::mapper().
rmap()
void rmap (const fvPatchField< scalar > & ptf, const labelList & addr) virtual
Implements temperatureCoupledBase.
Definition at line 232 of file turbulentTemperatureCoupledBaffleMixedFvPatchScalarField.C.
References Foam::refCast(), and temperatureCoupledBase::rmap().
kappa()
tmp< Foam::scalarField > kappa (const scalarField & Tp) const virtual
Reimplemented from temperatureCoupledBase.
Definition at line 257 of file turbulentTemperatureCoupledBaffleMixedFvPatchScalarField.C.
References forAll, temperatureCoupledBase::kappa(), and UList< T >::size().
Referenced by turbulentTemperatureCoupledBaffleMixedFvPatchScalarField::updateCoeffs().
updateCoeffs()
void updateCoeffs () virtual
Definition at line 298 of file turbulentTemperatureCoupledBaffleMixedFvPatchScalarField.C.
References mappedPatchFieldBase< scalar >::distribute(), Foam::endl(), Foam::gAverage(), Foam::gMax(), Foam::gMin(), Foam::gSum(), Foam::Info, turbulentTemperatureCoupledBaffleMixedFvPatchScalarField::kappa(), mappedPatchFieldBase< Type >::mapper(), UPstream::msgType(), Foam::name(), Foam::refCast(), and Foam::Zero.
manipulateMatrix()
void manipulateMatrix (fvMatrix< scalar > & m, const label iMatrix, const direction cmpt) virtual
Definition at line 401 of file turbulentTemperatureCoupledBaffleMixedFvPatchScalarField.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
write()
void write (Ostream & os) const virtual
Reimplemented from mappedPatchFieldBase< scalar >.
Definition at line 448 of file turbulentTemperatureCoupledBaffleMixedFvPatchScalarField.C.
References os(), UList< T >::size(), mixedFvPatchField< Type >::write(), mappedPatchFieldBase< Type >::write(), temperatureCoupledBase::write(), and UList< T >::writeEntry().
The documentation for this class was generated from the following files:
src/thermoTools/derivedFvPatchFields/turbulentTemperatureCoupledBaffleMixed/turbulentTemperatureCoupledBaffleMixedFvPatchScalarField.H
src/thermoTools/derivedFvPatchFields/turbulentTemperatureCoupledBaffleMixed/turbulentTemperatureCoupledBaffleMixedFvPatchScalarField.C