OpenFOAM: bitSet Class Reference
bitSet Class Reference
A bitSet stores bits (elements with only two states) in packed internal format and supports a variety of bit-set operations. Its behaviour is largely list-like, with some HashSet features.
#include <bitSet.H>
Classes
class const_iterator
class reference
Public Types
typedef unsigned int const_reference
Public Types inherited from PackedList< 1 >
typedef unsigned int block_type
typedef unsigned int const_reference
Public Member Functions
ClassName ("bitSet")
bitSet () noexcept
bitSet (Istream &is)
bitSet (const label n)
bitSet (const label n, const bool val)
bitSet (const bitSet &bitset)
bitSet (bitSet &&bitset)
bitSet (const bitSet &bitset, const labelUList &addr)
template<class Addr >
bitSet (const bitSet &bitset, const IndirectListBase< label, Addr > &addr)
bitSet (const bitSet &bitset, const labelRange &range)
bitSet (const UList< bool > &bools)
bitSet (const label n, const labelRange &range)
bitSet (const label n, const labelUList &locations)
template<class Addr >
bitSet (const label n, const IndirectListBase< label, Addr > &locations)
template<unsigned N>
bitSet (const label n, const FixedList< label, N > &locations)
bitSet (const label n, std::initializer_list< label > locations)
bitSet (const labelRange &range)
bitSet (const labelUList &locations)
template<class Addr >
bitSet (const IndirectListBase< label, Addr > &locations)
template<unsigned N>
bitSet (const FixedList< label, N > &locations)
autoPtr< bitSet > clone () const
bool all () const
bool any () const
bool none () const
bool uniform () const
unsigned int count (const bool on=true) const
bool intersects (const bitSet &other) const
bool test (const label pos) const
bool contains (const label pos) const
label find_first () const
label find_first_not () const
label find_last () const
label find_next (label pos) const
labelList toc () const
labelList sortedToc () const
List< bool > values () const
void fill (const bool val)
void assign (const UList< bool > &bools)
void set (const bitSet &bitset)
void set (const labelRange &range)
bitSet & unset (const bitSet &other)
void unset (const labelRange &range)
void flip ()
void flip (const label pos)
void resize_last ()
void swap (bitSet &bitset)
void transfer (bitSet &bitset)
bitSet & bound (const label maxSize)
bitSet & bound (const bitSet &other)
bitSet & extend (const label minSize)
bitSet & extend (const bitSet &other)
template<class InputIter >
label setMany (InputIter first, InputIter last)
label set (const labelUList &locations)
template<class Addr >
label set (const IndirectListBase< label, Addr > &locations)
template<unsigned N>
label set (const FixedList< label, N > &locations)
template<class InputIter >
label unset (InputIter first, InputIter last)
label unset (const labelUList &locations)
template<class Addr >
label unset (const IndirectListBase< label, Addr > &locations)
template<unsigned N>
label unset (const FixedList< label, N > &locations)
const_iterator begin () const
const_iterator cbegin () const
const_iterator begin (label pos) const
const_iterator cbegin (label pos) const
const_iterator end () const noexcept
const_iterator cend () const noexcept
bool operator() (const label pos) const
unsigned int operator[] (const label i) const
reference operator[] (const label i)
bitSet & operator= (const bitSet &bitset)
bitSet & operator= (bitSet &&bitset)
bitSet & operator= (const bool val)
bitSet & operator&= (const bitSet &other)
bitSet & operator|= (const bitSet &other)
bitSet & operator^= (const bitSet &other)
bitSet & operator-= (const bitSet &other)
InfoProxy< bitSet > info () const noexcept
bool found (const label pos) const
void assign (const unsigned int val)
template<class Addr >
Foam::label set (const IndirectListBase< label, Addr > &locations)
template<class Addr >
Foam::label unset (const IndirectListBase< label, Addr > &locations)
template<class InputIter >
Foam::label setMany (InputIter first, InputIter last)
template<class InputIter >
Foam::label unset (InputIter first, InputIter last)
template<unsigned N>
Foam::label set (const FixedList< label, N > &locations)
template<unsigned N>
Foam::label unset (const FixedList< label, N > &locations)
Public Member Functions inherited from PackedList< 1 >
void writeEntry (const word &keyword, Ostream &os) const
constexpr PackedList () noexcept
PackedList (const label numElem)
PackedList (const label numElem, const unsigned int val)
PackedList (Istream &is)
PackedList (const PackedList< Width > &list)
PackedList (PackedList< Width > &&list)
PackedList (const PackedList< Width > &list, const labelUList &addr)
PackedList (const PackedList< Width > &list, const IndirectListBase< label, Addr > &addr)
PackedList (const PackedList< Width > &list, const labelRange &range)
PackedList (const labelUList &values)
PackedList (const IndirectListBase< label, Addr > &values)
autoPtr< PackedList< Width > > clone () const
void checkIndex (const label i) const
bool empty () const noexcept
label size () const noexcept
label capacity () const noexcept
bool uniform () const
bool equal (const PackedList< Width > &other) const
unsigned int get (const label i) const
bool set (const label i, unsigned int val=~0u)
bool unset (const label i)
labelList values () const
List< IntType > unpack () const
List< IntType > unpack (const labelRange &range) const
List< IntType > unpack (const labelUList &locations) const
Foam::List< IntType > unpack () const
Foam::List< IntType > unpack (const labelRange &range) const
Foam::List< IntType > unpack (const labelUList &locations) const
void fill (const unsigned int val)
bool trim (label minpos=-1)
void reset ()
void setCapacity (const label numElem)
void resize (const label numElem, const unsigned int val=0u)
void resize_nocopy (const label numElem)
void reserve (const label numElem)
void clear ()
void clearStorage ()
void shrink ()
void swap (PackedList< Width > &rhs)
void transfer (PackedList< Width > &rhs)
label nBlocks () const
const List< unsigned int > & storage () const
List< unsigned int > & storage ()
const unsigned int * cdata () const noexcept
unsigned int * data () noexcept
const char * cdata_bytes () const noexcept
char * data_bytes () noexcept
std::streamsize size_data () const noexcept
std::streamsize size_bytes () const noexcept
std::streamsize byteSize () const noexcept
Ostream & printBits (Ostream &os, bool debugOutput=false) const
Istream & readList (Istream &is)
Ostream & writeList (Ostream &os, const label shortLen=0) const
void push_back (const unsigned int val)
void pop_back (label n=1)
unsigned int remove ()
unsigned int operator[] (const label i) const
reference operator[] (const label i)
void operator= (const PackedList< Width > &lst)
void operator= (PackedList< Width > &&lst)
void operator= (const unsigned int val)
InfoProxy< PackedList< Width > > info () const noexcept
void assign (const unsigned int val)
void assign (const PackedList< Width > &rhs)
void setSize (const label n, unsigned int val=0u)
PackedList< Width > & append (const unsigned int val)
Public Member Functions inherited from PackedListCore
ClassNameNoDebug ("PackedList")
Static Public Member Functions
static const bitSet & null ()
Static Public Member Functions inherited from PackedList< 1 >
static constexpr label num_blocks (label numElem) noexcept
static constexpr block_type mask_lower (unsigned elementOffset)
Protected Member Functions
bitSet & minusEq (const bitSet &other)
bitSet & andEq (const bitSet &other)
bitSet & orEq (const bitSet &other)
bitSet & xorEq (const bitSet &other)
Protected Member Functions inherited from PackedList< 1 >
unsigned int repeated_value (unsigned val)
unsigned int readValue (Istream &is)
void setPair (Istream &is)
void setPair (Istream &is)
void writeEntry (Ostream &os) const
void clear_trailing_bits ()
void copyAssign (const PackedList< Width > &rhs)
Additional Inherited Members
Static Public Attributes inherited from PackedList< 1 >
static constexpr unsigned bits_per_block
static constexpr unsigned element_width
static constexpr unsigned elem_per_block
static constexpr block_type max_value
Protected Types inherited from PackedList< 1 >
typedef List< block_type > block_container
Static Protected Member Functions inherited from PackedList< 1 >
static unsigned int repeated_value (unsigned val)
static unsigned int readValue (Istream &is)
Protected Attributes inherited from PackedList< 1 >
block_container blocks_
label size_
Detailed Description
A bitSet stores bits (elements with only two states) in packed internal format and supports a variety of bit-set operations. Its behaviour is largely list-like, with some HashSet features.
Source files
bitSet.H
bitSetI.H
bitSet.C
bitSetIO.C
bitSetTemplates.C
See also
Foam::BitOps Foam::PackedList
Definition at line 59 of file bitSet.H.
Member Typedef Documentation
const_reference
typedef unsigned int const_reference
Definition at line 120 of file bitSet.H.
Constructor & Destructor Documentation
bitSet() [1/19]
bitSet () inline noexcept
Definition at line 70 of file bitSetI.H.
bitSet() [2/19]
bitSet (Istream & is) explicit
Definition at line 215 of file bitSet.C.
bitSet() [3/19]
bitSet (const label n) inline explicit
Definition at line 76 of file bitSetI.H.
bitSet() [4/19]
bitSet (const label n, const bool val) inline
Definition at line 82 of file bitSetI.H.
References bitSet::fill().
bitSet() [5/19]
bitSet (const bitSet & bitset) inline
Definition at line 90 of file bitSetI.H.
bitSet() [6/19]
bitSet (bitSet && bitset) inline
Definition at line 96 of file bitSetI.H.
bitSet() [7/19]
bitSet (const bitSet & bitset, const labelUList & addr)
Definition at line 223 of file bitSet.C.
References PackedList< Width >::get(), bitSet::set(), and UPtrList< T >::size().
bitSet() [8/19]
template<class Addr > bitSet (const bitSet & bitset, const IndirectListBase< label, Addr > & addr)
Definition at line 46 of file bitSetTemplates.C.
References PackedList< Width >::get(), bitSet::set(), and UPtrList< T >::size().
bitSet() [9/19]
bitSet (const bitSet & bitset, const labelRange & range)
Definition at line 236 of file bitSet.C.
References PackedList< Width >::get(), Foam::pos(), range, bitSet::set(), and UPtrList< T >::size().
bitSet() [10/19]
bitSet (const UList< bool > & bools) inline explicit
Definition at line 102 of file bitSetI.H.
References bitSet::assign().
bitSet() [11/19]
bitSet (const label n, const labelRange & range) explicit
Definition at line 251 of file bitSet.C.
References bitSet::set().
bitSet() [12/19]
bitSet (const label n, const labelUList & locations) inline
Definition at line 110 of file bitSetI.H.
References UPtrList< T >::begin(), UPtrList< T >::end(), and bitSet::setMany().
bitSet() [13/19]
template<class Addr > bitSet (const label n, const IndirectListBase< label, Addr > & locations) inline
Definition at line 119 of file bitSetI.H.
References UPtrList< T >::begin(), UPtrList< T >::end(), and bitSet::setMany().
bitSet() [14/19]
template<unsigned N> bitSet (const label n, const FixedList< label, N > & locations)
Definition at line 26 of file bitSetTemplates.C.
References UPtrList< T >::begin(), UPtrList< T >::end(), and bitSet::setMany().
bitSet() [15/19]
bitSet (const label n, std::initializer_list< label > locations) inline
Definition at line 131 of file bitSetI.H.
References UPtrList< T >::begin(), UPtrList< T >::end(), and bitSet::setMany().
bitSet() [16/19]
bitSet (const labelRange & range) explicit
Definition at line 259 of file bitSet.C.
References range.
bitSet() [17/19]
bitSet (const labelUList & locations) inline explicit
Definition at line 143 of file bitSetI.H.
References UPtrList< T >::begin(), UPtrList< T >::end(), and bitSet::setMany().
bitSet() [18/19]
template<class Addr > bitSet (const IndirectListBase< label, Addr > & locations) inline explicit
Definition at line 152 of file bitSetI.H.
References UPtrList< T >::begin(), UPtrList< T >::end(), and bitSet::setMany().
bitSet() [19/19]
template<unsigned N> bitSet (const FixedList< label, N > & locations) explicit
Definition at line 36 of file bitSetTemplates.C.
References UPtrList< T >::begin(), UPtrList< T >::end(), and bitSet::setMany().
Member Function Documentation
minusEq()
Foam::bitSet & minusEq (const bitSet & other) protected
Definition at line 35 of file bitSet.C.
References PackedList< 1 >::blocks_, PackedList< Width >::blocks_, InfoInFunction, Foam::nl, bitSet::none(), PackedList< 1 >::num_blocks(), PackedList< 1 >::reset(), PackedList< Width >::size(), and PackedList< 1 >::size().
Referenced by bitSet::operator-=(), and bitSet::unset().
andEq()
Foam::bitSet & andEq (const bitSet & other) protected
Definition at line 70 of file bitSet.C.
References PackedList< Width >::blocks_, InfoInFunction, Foam::nl, bitSet::none(), resize(), and PackedList< Width >::size().
Referenced by bitSet::operator&=().
orEq()
Foam::bitSet & orEq (const bitSet & other) protected
Definition at line 122 of file bitSet.C.
References PackedList< Width >::blocks_, bitSet::find_last(), InfoInFunction, Foam::nl, bitSet::none(), resize(), and PackedList< Width >::size().
Referenced by bitSet::operator|=(), and bitSet::set().
xorEq()
Foam::bitSet & xorEq (const bitSet & other) protected
Definition at line 167 of file bitSet.C.
References PackedList< Width >::blocks_, bitSet::find_last(), InfoInFunction, Foam::nl, bitSet::none(), resize(), and PackedList< Width >::size().
Referenced by bitSet::operator^=().
null()
const Foam::bitSet & null () inline static
Definition at line 448 of file bitSetI.H.
ClassName()
ClassName ("bitSet")
clone()
Foam::autoPtr< Foam::bitSet > clone () const inline
Definition at line 163 of file bitSetI.H.
References autoPtr< T >::New().
all()
bool all () const inline
Definition at line 454 of file bitSetI.H.
References PackedList< 1 >::empty().
Referenced by triSurface::checkTriangles(), ensightCase::printTimeset(), and bitSet::uniform().
any()
bool any () const inline
Definition at line 462 of file bitSetI.H.
References PackedList< 1 >::blocks_, PackedList< 1 >::num_blocks(), and PackedList< 1 >::size().
Referenced by ensightMesh::correct(), and bitSet::none().
none()
bool none () const inline
Definition at line 481 of file bitSetI.H.
References bitSet::any().
Referenced by bitSet::andEq(), ensightMesh::correct(), bitSet::minusEq(), bitSet::orEq(), bitSet::uniform(), and bitSet::xorEq().
uniform()
bool uniform () const inline
Definition at line 487 of file bitSetI.H.
References bitSet::all(), bitSet::none(), PackedList< 1 >::size(), and bitSet::test().
count()
unsigned int count (const bool on = true) const inline
Definition at line 493 of file bitSetI.H.
References Foam::BitOps::bit_count(), PackedList< 1 >::blocks_, PackedList< 1 >::num_blocks(), and PackedList< 1 >::size().
Referenced by Foam::operator<<(), ensightCase::printTimeset(), ConeInjection< CloudType >::updateMesh(), FieldActivatedInjection< CloudType >::updateMesh(), KinematicLookupTableInjection< CloudType >::updateMesh(), ReactingLookupTableInjection< CloudType >::updateMesh(), ReactingMultiphaseLookupTableInjection< CloudType >::updateMesh(), and ThermoLookupTableInjection< CloudType >::updateMesh().
intersects()
bool intersects (const bitSet & other) const
Definition at line 287 of file bitSet.C.
References PackedList< Width >::blocks_, and PackedList< Width >::size().
test()
bool test (const label pos) const inline
Definition at line 262 of file bitSet.H.
References PackedList< 1 >::get().
Referenced by polyDualMesh::calcFeatures(), dynamicRefineFvMesh::checkEightAnchorPoints(), edgeCollapser::consistentCollapse(), ensightMesh::correct(), zoneSubSet::mapToZone(), bitSet::operator()(), fvMeshSubset::reset(), edgeCollapser::setRefinement(), and bitSet::uniform().
contains()
bool contains (const label pos) const inline
Definition at line 268 of file bitSet.H.
References PackedList< 1 >::get().
Referenced by bitSet::found().
find_first()
Foam::label find_first () const inline
Definition at line 307 of file bitSetI.H.
References PackedList< 1 >::blocks_, PackedList< 1 >::elem_per_block, PackedList< 1 >::num_blocks(), Foam::pos(), and PackedList< 1 >::size().
Referenced by Foam::reorder().
find_first_not()
Foam::label find_first_not () const inline
Definition at line 336 of file bitSetI.H.
References PackedList< 1 >::blocks_, PackedList< 1 >::elem_per_block, and Foam::pos().
find_last()
Foam::label find_last () const inline
Definition at line 368 of file bitSetI.H.
References PackedList< 1 >::blocks_, PackedList< 1 >::elem_per_block, PackedList< 1 >::num_blocks(), Foam::pos(), and PackedList< 1 >::size().
Referenced by topoBitSet::check(), bitSet::orEq(), bitSet::resize_last(), topoBitSet::updateLabels(), and bitSet::xorEq().
find_next()
Foam::label find_next (label pos) const inline
Definition at line 394 of file bitSetI.H.
References PackedList< 1 >::blocks_, PackedList< 1 >::elem_per_block, PackedList< 1 >::num_blocks(), Foam::pos(), and PackedList< 1 >::size().
Referenced by Foam::reorder().
toc()
Foam::labelList toc () const
Definition at line 467 of file bitSet.C.
References Foam::output(), and Foam::pos().
Referenced by bitSet::sortedToc(), and Foam::BitOps::toc().
sortedToc()
Foam::labelList sortedToc () const inline
Definition at line 514 of file bitSetI.H.
References bitSet::toc().
Referenced by fvMeshSubset::reset(), cellSetOption::setCellSelection(), and Foam::BitOps::sortedToc().
values()
Foam::List< bool > values () const
Definition at line 506 of file bitSet.C.
References Foam::output(), and Foam::pos().
Referenced by faceBitSet::distribute(), and pointBitSet::distribute().
fill()
void fill (const bool val) inline
Definition at line 547 of file bitSetI.H.
References PackedList< 1 >::blocks_, PackedList< 1 >::clear_trailing_bits(), PackedList< 1 >::empty(), PackedList< 1 >::num_blocks(), and PackedList< 1 >::size().
Referenced by bitSet::assign(), bitSet::bitSet(), and bitSet::operator=().
assign() [1/2]
void assign (const UList< bool > & bools)
Definition at line 267 of file bitSet.C.
References clear(), resize(), and UList< T >::size().
Referenced by bitSet::bitSet(), faceBitSet::distribute(), and pointBitSet::distribute().
set() [1/7]
void set (const bitSet & bitset) inline
Definition at line 571 of file bitSetI.H.
References bitSet::orEq().
Referenced by Foam::apply(), bitSet::bitSet(), bitSet::bitSet(), bitSet::bitSet(), bitSet::bitSet(), Foam::calcElementMasks(), polyDualMesh::calcFeatures(), dynamicRefineFvMesh::checkEightAnchorPoints(), ensightMesh::correct(), fvMeshSubsetProxy::correct(), Foam::BitSetOps::create(), Foam::BitSetOps::create(), Foam::BitSetOps::create(), syncTools::getMasterEdges(), syncTools::getMasterPoints(), bitSet::reference::operator=(), bitSet::reference::operator=(), Foam::reorder(), ZoneMesh< ZoneType, MeshType >::selection(), Foam::BitOps::set(), edgeCollapser::setRefinement(), MeshedSurface< Face >::subsetMesh(), triSurface::subsetMesh(), ConeInjection< CloudType >::updateMesh(), FieldActivatedInjection< CloudType >::updateMesh(), KinematicLookupTableInjection< CloudType >::updateMesh(), ReactingLookupTableInjection< CloudType >::updateMesh(), ReactingMultiphaseLookupTableInjection< CloudType >::updateMesh(), and ThermoLookupTableInjection< CloudType >::updateMesh().
set() [2/7]
void set (const labelRange & range)
Definition at line 307 of file bitSet.C.
References labelRange::adjust(), IntRange< IntType >::begin_value(), IntRange< IntType >::empty(), IntRange< IntType >::end_value(), range, reserve(), and resize().
unset() [1/9]
Foam::bitSet & unset (const bitSet & other) inline
Definition at line 609 of file bitSetI.H.
References bitSet::minusEq().
Referenced by Foam::apply(), triSurface::checkTriangles(), edgeCollapser::consistentCollapse(), syncTools::getInternalOrCoupledFaces(), syncTools::getInternalOrMasterFaces(), syncTools::getMasterFaces(), globalMeshData::mergePoints(), Foam::BitOps::unset(), bitSet::unset(), and bitSet::unset().
unset() [2/9]
void unset (const labelRange & range)
Definition at line 386 of file bitSet.C.
References IntRange< IntType >::begin_value(), IntRange< IntType >::empty(), IntRange< IntType >::end_value(), range, and resize().
flip() [1/2]
void flip () inline
Definition at line 615 of file bitSetI.H.
References PackedList< 1 >::blocks_, PackedList< 1 >::clear_trailing_bits(), PackedList< 1 >::num_blocks(), and PackedList< 1 >::size().
Referenced by parcelSelection::calculateFilter(), ensightMesh::correct(), Foam::operator~(), ConeInjection< CloudType >::updateMesh(), FieldActivatedInjection< CloudType >::updateMesh(), KinematicLookupTableInjection< CloudType >::updateMesh(), ReactingLookupTableInjection< CloudType >::updateMesh(), ReactingMultiphaseLookupTableInjection< CloudType >::updateMesh(), and ThermoLookupTableInjection< CloudType >::updateMesh().
flip() [2/2]
void flip (const label pos) inline
Definition at line 630 of file bitSetI.H.
References bitSet::reference::flip(), and PackedList< 1 >::size().
resize_last()
void resize_last () inline
Definition at line 520 of file bitSetI.H.
References PackedList< 1 >::clear(), bitSet::find_last(), Foam::pos(), and PackedList< 1 >::resize().
Referenced by Foam::operator&(), Foam::operator-(), Foam::operator^(), and Foam::operator|().
swap()
void swap (bitSet & bitset) inline
Definition at line 535 of file bitSetI.H.
References PackedList< Width >::swap().
transfer()
void transfer (bitSet & bitset) inline
Definition at line 541 of file bitSetI.H.
References PackedList< Width >::transfer().
Referenced by bitSet::operator=(), and topoBitSet::updateLabels().
bound() [1/2]
Foam::bitSet & bound (const label maxSize) inline
Definition at line 639 of file bitSetI.H.
References PackedList< 1 >::resize(), and PackedList< 1 >::size().
Referenced by bitSet::bound().
bound() [2/2]
Foam::bitSet & bound (const bitSet & other) inline
Definition at line 650 of file bitSetI.H.
References bitSet::bound(), and PackedList< Width >::size().
extend() [1/2]
Foam::bitSet & extend (const label minSize) inline
Definition at line 656 of file bitSetI.H.
References PackedList< 1 >::resize(), and PackedList< 1 >::size().
Referenced by bitSet::extend().
extend() [2/2]
Foam::bitSet & extend (const bitSet & other) inline
Definition at line 667 of file bitSetI.H.
References bitSet::extend(), and PackedList< Width >::size().
setMany() [1/2]
template<class InputIter > label setMany (InputIter first, InputIter last)
Referenced by bitSet::bitSet(), bitSet::bitSet(), bitSet::bitSet(), bitSet::bitSet(), bitSet::bitSet(), bitSet::bitSet(), Foam::HashSetOps::bitset(), bitSet::bitSet(), bitSet::set(), and bitSet::set().
set() [3/7]
Foam::label set (const labelUList & locations) inline
Definition at line 577 of file bitSetI.H.
References UPtrList< T >::begin(), UPtrList< T >::end(), and bitSet::setMany().
set() [4/7]
template<class Addr > label set (const IndirectListBase< label, Addr > & locations) inline
set() [5/7]
template<unsigned N> label set (const FixedList< label, N > & locations)
unset() [3/9]
template<class InputIter > label unset (InputIter first, InputIter last)
unset() [4/9]
Foam::label unset (const labelUList & locations) inline
Definition at line 593 of file bitSetI.H.
References UPtrList< T >::begin(), UPtrList< T >::end(), and bitSet::unset().
unset() [5/9]
template<class Addr > label unset (const IndirectListBase< label, Addr > & locations) inline
unset() [6/9]
template<unsigned N> label unset (const FixedList< label, N > & locations)
begin() [1/2]
Foam::bitSet::const_iterator begin () const inline
Definition at line 271 of file bitSetI.H.
cbegin() [1/2]
Foam::bitSet::const_iterator cbegin () const inline
Definition at line 277 of file bitSetI.H.
begin() [2/2]
Foam::bitSet::const_iterator begin (label pos) const inline
Definition at line 283 of file bitSetI.H.
References Foam::pos().
cbegin() [2/2]
Foam::bitSet::const_iterator cbegin (label pos) const inline
Definition at line 289 of file bitSetI.H.
References Foam::pos().
end()
Foam::bitSet::const_iterator end () const inline noexcept
Definition at line 295 of file bitSetI.H.
cend()
Foam::bitSet::const_iterator cend () const inline noexcept
Definition at line 301 of file bitSetI.H.
operator()()
bool operator() (const label pos) const inline
Definition at line 675 of file bitSetI.H.
References Foam::pos(), and bitSet::test().
operator[]() [1/2]
unsigned int operator[] (const label i) const inline
Definition at line 681 of file bitSetI.H.
References PackedList< 1 >::get().
operator[]() [2/2]
Foam::bitSet::reference operator[] (const label i) inline
Definition at line 687 of file bitSetI.H.
References PackedList< 1 >::checkIndex().
operator=() [1/3]
Foam::bitSet & operator= (const bitSet & bitset) inline
Definition at line 696 of file bitSetI.H.
References PackedList< Width >::operator=().
operator=() [2/3]
Foam::bitSet & operator= (bitSet && bitset) inline
Definition at line 703 of file bitSetI.H.
References bitSet::transfer().
operator=() [3/3]
Foam::bitSet & operator= (const bool val) inline
Definition at line 710 of file bitSetI.H.
References bitSet::fill().
operator&=()
Foam::bitSet & operator&= (const bitSet & other) inline
Definition at line 717 of file bitSetI.H.
References bitSet::andEq().
operator|=()
Foam::bitSet & operator|= (const bitSet & other) inline
Definition at line 723 of file bitSetI.H.
References bitSet::orEq().
operator^=()
Foam::bitSet & operator^= (const bitSet & other) inline
Definition at line 729 of file bitSetI.H.
References bitSet::xorEq().
operator-=()
Foam::bitSet & operator-= (const bitSet & other) inline
Definition at line 735 of file bitSetI.H.
References bitSet::minusEq().
info()
InfoProxy< bitSet > info () const inline noexcept
Definition at line 604 of file bitSet.H.
found()
bool found (const label pos) const inline
Definition at line 613 of file bitSet.H.
References bitSet::contains().
assign() [2/2]
void assign (const unsigned int val) inline
Definition at line 617 of file bitSet.H.
References bitSet::fill().
set() [6/7]
template<class Addr > Foam::label set (const IndirectListBase< label, Addr > & locations) inline
Definition at line 584 of file bitSetI.H.
References UPtrList< T >::begin(), UPtrList< T >::end(), and bitSet::setMany().
unset() [7/9]
template<class Addr > Foam::label unset (const IndirectListBase< label, Addr > & locations) inline
Definition at line 600 of file bitSetI.H.
References UPtrList< T >::begin(), UPtrList< T >::end(), and bitSet::unset().
setMany() [2/2]
template<class InputIter > Foam::label setMany (InputIter first, InputIter last)
Definition at line 67 of file bitSetTemplates.C.
References Foam::max(), and reserve().
unset() [8/9]
template<class InputIter > Foam::label unset (InputIter first, InputIter last)
Definition at line 93 of file bitSetTemplates.C.
set() [7/7]
template<unsigned N> Foam::label set (const FixedList< label, N > & locations)
Definition at line 110 of file bitSetTemplates.C.
References UPtrList< T >::begin(), and UPtrList< T >::end().
unset() [9/9]
template<unsigned N> Foam::label unset (const FixedList< label, N > & locations)
Definition at line 117 of file bitSetTemplates.C.
References UPtrList< T >::begin(), and UPtrList< T >::end().
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/Bits/bitSet/bitSet.H
src/OpenFOAM/containers/Bits/bitSet/bitSet.C
src/OpenFOAM/containers/Bits/bitSet/bitSetI.H
src/OpenFOAM/containers/Bits/bitSet/bitSetTemplates.C