OpenFOAM: fvFieldDecomposer::processorVolPatchFieldDecomposer Class Reference
fvFieldDecomposer::processorVolPatchFieldDecomposer Class Reference
#include <fvFieldDecomposer.H>
Public Member Functions
processorVolPatchFieldDecomposer (const labelUList &faceOwner, const labelUList &faceNeigbour, const labelUList &addressingSlice)
processorVolPatchFieldDecomposer (const polyMesh &mesh, const labelUList &addressingSlice)
label size () const
bool direct () const
bool hasUnmapped () const
const labelUList & directAddressing () const
Public Member Functions inherited from fvPatchFieldMapper
fvPatchFieldMapper ()=default
Public Member Functions inherited from FieldMapper
FieldMapper ()=default
virtual ~FieldMapper ()=default
virtual bool distributed () const
virtual const mapDistributeBase & distributeMap () const
virtual const labelListList & addressing () const
virtual const scalarListList & weights () const
template<class Type >
tmp< Field< Type > > operator() (const Field< Type > &fld) const
Detailed Description
Definition at line 109 of file fvFieldDecomposer.H.
Constructor & Destructor Documentation
processorVolPatchFieldDecomposer() [1/2]
processorVolPatchFieldDecomposer (const labelUList & faceOwner, const labelUList & faceNeigbour, const labelUList & addressingSlice)
Definition at line 47 of file fvFieldDecomposer.C.
References forAll, Foam::mag(), and UPtrList< T >::size().
processorVolPatchFieldDecomposer() [2/2]
processorVolPatchFieldDecomposer (const polyMesh & mesh, const labelUList & addressingSlice)
Definition at line 93 of file fvFieldDecomposer.C.
Member Function Documentation
size()
label size () const inline virtual
Implements FieldMapper.
Definition at line 137 of file fvFieldDecomposer.H.
References UList< T >::size().
direct()
bool direct () const inline virtual
Implements FieldMapper.
Definition at line 142 of file fvFieldDecomposer.H.
hasUnmapped()
bool hasUnmapped () const inline virtual
Implements FieldMapper.
Definition at line 148 of file fvFieldDecomposer.H.
directAddressing()
const labelUList & directAddressing () const inline virtual
Reimplemented from FieldMapper.
Definition at line 153 of file fvFieldDecomposer.H.
The documentation for this class was generated from the following files:
src/parallel/decompose/decompose/fvFieldDecomposer.H
src/parallel/decompose/decompose/fvFieldDecomposer.C