OpenFOAM: treeDataFace Class Reference
treeDataFace Class Reference
Encapsulation of data for searching on faces.
#include <treeDataFace.H>
Classes
class findIntersectOp
class findNearestOp
Public Member Functions
ClassName ("treeDataFace")
treeDataFace (const bool cacheBb, const primitiveMesh &mesh)
treeDataFace (const bool cacheBb, const polyPatch &patch)
treeDataFace (const bool cacheBb, const primitiveMesh &mesh, const labelRange &range)
treeDataFace (const bool cacheBb, const primitiveMesh &mesh, const labelUList &faceLabels)
treeDataFace (const bool cacheBb, const primitiveMesh &mesh, labelList &&faceLabels)
treeDataFace (const primitiveMesh &mesh)
treeDataFace (const polyPatch &patch)
treeDataFace (const primitiveMesh &mesh, const labelRange &range)
treeDataFace (const primitiveMesh &mesh, const labelUList &faceLabels)
treeDataFace (const primitiveMesh &mesh, labelList &&faceLabels)
int nDim () const noexcept
treeBoundBox bounds (const labelUList &indices) const
const primitiveMesh & mesh () const noexcept
const labelList & faceLabels () const noexcept
bool useSubset () const noexcept
bool empty () const noexcept
label size () const noexcept
label objectIndex (const label index) const
const face & operator[] (const label index) const
const point & centre (const label index) const
tmp< pointField > centres () const
volumeType getVolumeType (const indexedOctree< treeDataFace > &, const point &) const
bool overlaps (const label index, const treeBoundBox &searchBox) const
bool overlaps (const label index, const point &centre, const scalar radiusSqr) const
void findNearest (const labelUList &indices, const point &sample, scalar &nearestDistSqr, label &nearestIndex, point &nearestPoint) const
Static Public Member Functions
static treeBoundBoxList boxes (const primitiveMesh &mesh)
static treeBoundBoxList boxes (const primitiveMesh &mesh, const labelRange &range)
static treeBoundBoxList boxes (const primitiveMesh &mesh, const labelUList &faceIds)
static treeBoundBox bounds (const primitiveMesh &mesh, const labelRange &range)
static treeBoundBox bounds (const primitiveMesh &mesh, const labelUList &faceIds)
Detailed Description
Encapsulation of data for searching on faces.
Source files
treeDataFace.H
treeDataFace.C
Definition at line 55 of file treeDataFace.H.
Constructor & Destructor Documentation
treeDataFace() [1/10]
treeDataFace (const bool cacheBb, const primitiveMesh & mesh)
Definition at line 176 of file treeDataFace.C.
treeDataFace() [2/10]
treeDataFace (const bool cacheBb, const polyPatch & patch)
Definition at line 209 of file treeDataFace.C.
treeDataFace() [3/10]
treeDataFace (const bool cacheBb, const primitiveMesh & mesh, const labelRange & range)
Definition at line 192 of file treeDataFace.C.
treeDataFace() [4/10]
treeDataFace (const bool cacheBb, const primitiveMesh & mesh, const labelUList & faceLabels)
Definition at line 219 of file treeDataFace.C.
treeDataFace() [5/10]
treeDataFace (const bool cacheBb, const primitiveMesh & mesh, labelList && faceLabels)
Definition at line 236 of file treeDataFace.C.
treeDataFace() [6/10]
treeDataFace (const primitiveMesh & mesh) inline explicit
Definition at line 193 of file treeDataFace.H.
treeDataFace() [7/10]
treeDataFace (const polyPatch & patch) inline explicit
Definition at line 199 of file treeDataFace.H.
treeDataFace() [8/10]
treeDataFace (const primitiveMesh & mesh, const labelRange & range) inline
Definition at line 205 of file treeDataFace.H.
treeDataFace() [9/10]
treeDataFace (const primitiveMesh & mesh, const labelUList & faceLabels) inline
Definition at line 211 of file treeDataFace.H.
treeDataFace() [10/10]
treeDataFace (const primitiveMesh & mesh, labelList && faceLabels) inline
Definition at line 217 of file treeDataFace.H.
Member Function Documentation
ClassName()
ClassName ("treeDataFace")
boxes() [1/3]
Foam::treeBoundBoxList boxes (const primitiveMesh & mesh) static
Definition at line 90 of file treeDataFace.C.
References Foam::boxesImpl(), and treeDataFace::mesh().
boxes() [2/3]
Foam::treeBoundBoxList boxes (const primitiveMesh & mesh, const labelRange & range) static
Definition at line 98 of file treeDataFace.C.
References Foam::boxesImpl(), mesh, and range.
boxes() [3/3]
Foam::treeBoundBoxList boxes (const primitiveMesh & mesh, const labelUList & faceIds) static
Definition at line 109 of file treeDataFace.C.
References Foam::boxesImpl(), and mesh.
bounds() [1/3]
Foam::treeBoundBox bounds (const primitiveMesh & mesh, const labelRange & range) static
Definition at line 120 of file treeDataFace.C.
References Foam::boundsImpl(), mesh, and range.
Referenced by treeDataFace::bounds().
bounds() [2/3]
Foam::treeBoundBox bounds (const primitiveMesh & mesh, const labelUList & faceIds) static
Definition at line 131 of file treeDataFace.C.
References Foam::boundsImpl(), and mesh.
nDim()
int nDim () const inline noexcept
Definition at line 263 of file treeDataFace.H.
bounds() [3/3]
Foam::treeBoundBox bounds (const labelUList & indices) const
Definition at line 256 of file treeDataFace.C.
References boundBox::add(), and treeDataFace::bounds().
mesh()
const primitiveMesh & mesh () const inline noexcept
Definition at line 272 of file treeDataFace.H.
Referenced by treeDataFace::boxes(), and treeDataFace::findNearest().
faceLabels()
const labelList & faceLabels () const inline noexcept
Definition at line 275 of file treeDataFace.H.
useSubset()
bool useSubset () const inline noexcept
Definition at line 278 of file treeDataFace.H.
empty()
bool empty () const inline noexcept
Definition at line 281 of file treeDataFace.H.
References UList< T >::empty(), and primitiveMesh::nFaces().
size()
label size () const inline noexcept
Definition at line 287 of file treeDataFace.H.
References primitiveMesh::nFaces(), and UList< T >::size().
objectIndex()
label objectIndex (const label index) const inline
Definition at line 293 of file treeDataFace.H.
Referenced by treeDataFace::centre(), treeDataFace::findNearest(), treeDataFace::findIntersectOp::operator()(), and treeDataFace::operator[]().
operator[]()
const face & operator[] (const label index) const inline
Definition at line 299 of file treeDataFace.H.
References primitiveMesh::faces(), and treeDataFace::objectIndex().
centre()
const point & centre (const label index) const inline
Definition at line 305 of file treeDataFace.H.
References primitiveMesh::faceCentres(), and treeDataFace::objectIndex().
centres()
Foam::tmp< Foam::pointField > centres () const
Definition at line 276 of file treeDataFace.C.
References tmp< T >::New().
getVolumeType()
Foam::volumeType getVolumeType (const indexedOctree< treeDataFace > & oc, const point & sample) const
Definition at line 287 of file treeDataFace.C.
References Foam::abort(), e, Foam::endl(), f(), Foam::FatalError, FatalErrorInFunction, UList< T >::fcIndex(), forAll, indexedOctree< Type >::getSide(), PointIndexHit< PointType >::index(), Foam::mag(), Foam::magSqr(), Foam::normalised(), points, Foam::Pout, UList< T >::rcIndex(), Foam::sqr(), volumeType::UNKNOWN, and Foam::Zero.
overlaps() [1/2]
bool overlaps (const label index, const treeBoundBox & searchBox) const
Definition at line 527 of file treeDataFace.C.
References f(), forAll, points, and UList< T >::size().
overlaps() [2/2]
bool overlaps (const label index, const point & centre, const scalar radiusSqr) const
Definition at line 586 of file treeDataFace.C.
References f(), polyMesh::faces(), mesh, points, and Foam::sqr().
findNearest()
void findNearest (const labelUList & indices, const point & sample, scalar & nearestDistSqr, label & nearestIndex, point & nearestPoint) const
Definition at line 639 of file treeDataFace.C.
References f(), treeDataFace::mesh(), treeDataFace::objectIndex(), points, and Foam::sqr().
The documentation for this class was generated from the following files:
src/meshTools/indexedOctree/treeDataFace.H
src/meshTools/indexedOctree/treeDataFace.C