OpenFOAM: kOmegaSSTBase< BasicEddyViscosityModel > Class Template Reference
kOmegaSSTBase< BasicEddyViscosityModel > Class Template Reference
Base class implementation of the k-omega-SST turbulence model for incompressible and compressible flows.
#include <kOmegaSSTBase.H>
Public Types
typedef BasicEddyViscosityModel::alphaField alphaField
typedef BasicEddyViscosityModel::rhoField rhoField
typedef BasicEddyViscosityModel::transportModel transportModel
Public Member Functions
kOmegaSSTBase (const kOmegaSSTBase &)=delete
void operator= (const kOmegaSSTBase &)=delete
kOmegaSSTBase (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
virtual ~kOmegaSSTBase ()=default
virtual bool read ()
tmp< volScalarField > DkEff (const volScalarField &F1) const
tmp< volScalarField > DomegaEff (const volScalarField &F1) const
virtual tmp< volScalarField > k () const
virtual tmp< volScalarField > omega () const
virtual void correct ()
Protected Member Functions
void setDecayControl (const dictionary &dict)
virtual tmp< volScalarField > F1 (const volScalarField &CDkOmega) const
virtual tmp< volScalarField > F2 () const
virtual tmp< volScalarField > F3 () const
virtual tmp< volScalarField > F23 () const
tmp< volScalarField > blend (const volScalarField &F1, const dimensionedScalar &psi1, const dimensionedScalar &psi2) const
tmp< volScalarField::Internal > blend (const volScalarField::Internal &F1, const dimensionedScalar &psi1, const dimensionedScalar &psi2) const
tmp< volScalarField > alphaK (const volScalarField &F1) const
tmp< volScalarField > alphaOmega (const volScalarField &F1) const
tmp< volScalarField::Internal > beta (const volScalarField::Internal &F1) const
tmp< volScalarField::Internal > gamma (const volScalarField::Internal &F1) const
virtual void correctNut (const volScalarField &S2)
virtual void correctNut ()
virtual tmp< volScalarField > S2 (const volTensorField &gradU) const
virtual tmp< volScalarField::Internal > Pk (const volScalarField::Internal &G) const
virtual tmp< volScalarField::Internal > epsilonByk (const volScalarField &F1, const volTensorField &gradU) const
virtual tmp< volScalarField::Internal > GbyNu0 (const volTensorField &gradU, const volScalarField &S2) const
virtual tmp< volScalarField::Internal > GbyNu (const volScalarField::Internal &GbyNu0, const volScalarField::Internal &F2, const volScalarField::Internal &S2) const
virtual tmp< fvScalarMatrix > kSource () const
virtual tmp< fvScalarMatrix > omegaSource () const
virtual tmp< fvScalarMatrix > Qsas (const volScalarField::Internal &S2, const volScalarField::Internal &gamma, const volScalarField::Internal &beta) const
Protected Attributes
dimensionedScalar alphaK1_
dimensionedScalar alphaK2_
dimensionedScalar alphaOmega1_
dimensionedScalar alphaOmega2_
dimensionedScalar gamma1_
dimensionedScalar gamma2_
dimensionedScalar beta1_
dimensionedScalar beta2_
dimensionedScalar betaStar_
dimensionedScalar a1_
dimensionedScalar b1_
dimensionedScalar c1_
Switch F3_
const volScalarField & y_
volScalarField k_
volScalarField omega_
Switch decayControl_
dimensionedScalar kInf_
dimensionedScalar omegaInf_
Detailed Description
template<class BasicEddyViscosityModel>
class Foam::kOmegaSSTBase< BasicEddyViscosityModel >
Base class implementation of the k-omega-SST turbulence model for incompressible and compressible flows.
Turbulence model described in:
    Menter, F. R. & Esch, T. (2001).
    Elements of Industrial Heat Transfer Prediction.
    16th Brazilian Congress of Mechanical Engineering (COBEM).
with updated coefficients from
    Menter, F. R., Kuntz, M., and Langtry, R. (2003).
    Ten Years of Industrial Experience with the SST Turbulence Model.
    Turbulence, Heat and Mass Transfer 4, ed: K. Hanjalic, Y. Nagano,
    & M. Tummers, Begell House, Inc., 625 - 632.
but with the consistent production terms from the 2001 paper as form in the 2003 paper is a typo, see
    http://turbmodels.larc.nasa.gov/sst.html
and the addition of the optional F3 term for rough walls from
    Hellsten, A. (1998).
    Some Improvements in Menter's k-omega-SST turbulence model
    29th AIAA Fluid Dynamics Conference, AIAA-98-2554.
and the optional decay control from:
    Spalart, P. R. and Rumsey, C. L. (2007).
    Effective Inflow Conditions for Turbulence Models in Aerodynamic
    Calculations
    AIAA Journal, 45(10), 2544 - 2553.
Note that this implementation is written in terms of alpha diffusion coefficients rather than the more traditional sigma (alpha = 1/sigma) so that the blending can be applied to all coefficients in a consistent manner. The paper suggests that sigma is blended but this would not be consistent with the blending of the k-epsilon and k-omega models.
Also note that the error in the last term of equation (2) relating to sigma has been corrected.
Wall-functions are applied in this implementation by using equations (14) to specify the near-wall omega as appropriate.
The blending functions (15) and (16) are not currently used because of the uncertainty in their origin, range of applicability and that if y+ becomes sufficiently small blending u_tau in this manner clearly becomes nonsense.
The default model coefficients are
    kOmegaSSTBaseCoeffs
    {
        alphaK1         0.85;
        alphaK2         1.0;
        alphaOmega1     0.5;
        alphaOmega2     0.856;
        beta1           0.075;
        beta2           0.0828;
        betaStar        0.09;
        gamma1          5/9;
        gamma2          0.44;
        a1              0.31;
        b1              1.0;
        c1              10.0;
        F3              no;
        // Optional decay control
        decayControl    yes;
        kInf            \<far-field k value\>;
        omegaInf        \<far-field omega value\>;
    }
Source files
kOmegaSSTBase.H
kOmegaSSTBase.C
Definition at line 125 of file kOmegaSSTBase.H.
Member Typedef Documentation
alphaField
template<class BasicEddyViscosityModel > typedef BasicEddyViscosityModel::alphaField alphaField
Definition at line 297 of file kOmegaSSTBase.H.
rhoField
template<class BasicEddyViscosityModel > typedef BasicEddyViscosityModel::rhoField rhoField
Definition at line 298 of file kOmegaSSTBase.H.
transportModel
template<class BasicEddyViscosityModel > typedef BasicEddyViscosityModel::transportModel transportModel
Definition at line 299 of file kOmegaSSTBase.H.
Constructor & Destructor Documentation
kOmegaSSTBase() [1/2]
template<class BasicEddyViscosityModel > kOmegaSSTBase (const kOmegaSSTBase< BasicEddyViscosityModel > &) delete
kOmegaSSTBase() [2/2]
template<class BasicEddyViscosityModel > kOmegaSSTBase (const word & type, const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName)
Definition at line 232 of file kOmegaSSTBase.C.
~kOmegaSSTBase()
template<class BasicEddyViscosityModel > virtual ~kOmegaSSTBase () virtual default
Member Function Documentation
setDecayControl()
template<class BasicEddyViscosityModel > void setDecayControl (const dictionary & dict) protected
Definition at line 441 of file kOmegaSSTBase.C.
References dict, Foam::endl(), and Foam::Info.
F1()
template<class BasicEddyViscosityModel > tmp< volScalarField > F1 (const volScalarField & CDkOmega) const protected virtual
Reimplemented in kOmegaSSTLM< BasicTurbulenceModel >.
Definition at line 36 of file kOmegaSSTBase.C.
References Foam::dimless, Foam::dimTime, Foam::max(), Foam::min(), mu, Foam::pow4(), PtrList< T >::PtrList(), Foam::sqr(), Foam::sqrt(), and Foam::tanh().
F2()
template<class BasicEddyViscosityModel > tmp< volScalarField > F2 () const protected virtual
Definition at line 66 of file kOmegaSSTBase.C.
References Foam::max(), Foam::min(), mu, PtrList< T >::PtrList(), Foam::sqr(), Foam::sqrt(), and Foam::tanh().
F3()
template<class BasicEddyViscosityModel > tmp< volScalarField > F3 () const protected virtual
Definition at line 83 of file kOmegaSSTBase.C.
References Foam::min(), mu, Foam::pow4(), PtrList< T >::PtrList(), Foam::sqr(), and Foam::tanh().
F23()
template<class BasicEddyViscosityModel > tmp< volScalarField > F23 () const protected virtual
Definition at line 96 of file kOmegaSSTBase.C.
References F2, F3, and PtrList< T >::PtrList().
blend() [1/2]
template<class BasicEddyViscosityModel > tmp< volScalarField > blend (const volScalarField & F1, const dimensionedScalar & psi1, const dimensionedScalar & psi2) const inline protected
Definition at line 190 of file kOmegaSSTBase.H.
References F1, psi1, and psi2.
Referenced by kOmegaSSTBase< BasicEddyViscosityModel >::alphaK(), kOmegaSSTBase< BasicEddyViscosityModel >::alphaOmega(), kOmegaSSTBase< BasicEddyViscosityModel >::beta(), and kOmegaSSTBase< BasicEddyViscosityModel >::gamma().
blend() [2/2]
template<class BasicEddyViscosityModel > tmp< volScalarField::Internal > blend (const volScalarField::Internal & F1, const dimensionedScalar & psi1, const dimensionedScalar & psi2) const inline protected
Definition at line 201 of file kOmegaSSTBase.H.
References F1, psi1, and psi2.
alphaK()
template<class BasicEddyViscosityModel > tmp< volScalarField > alphaK (const volScalarField & F1) const inline protected
Definition at line 211 of file kOmegaSSTBase.H.
References kOmegaSSTBase< BasicEddyViscosityModel >::alphaK1_, kOmegaSSTBase< BasicEddyViscosityModel >::alphaK2_, kOmegaSSTBase< BasicEddyViscosityModel >::blend(), and F1.
Referenced by kOmegaSSTBase< BasicEddyViscosityModel >::DkEff().
alphaOmega()
template<class BasicEddyViscosityModel > tmp< volScalarField > alphaOmega (const volScalarField & F1) const inline protected
Definition at line 216 of file kOmegaSSTBase.H.
References kOmegaSSTBase< BasicEddyViscosityModel >::alphaOmega1_, kOmegaSSTBase< BasicEddyViscosityModel >::alphaOmega2_, kOmegaSSTBase< BasicEddyViscosityModel >::blend(), and F1.
Referenced by kOmegaSSTBase< BasicEddyViscosityModel >::DomegaEff().
beta()
template<class BasicEddyViscosityModel > tmp< volScalarField::Internal > beta (const volScalarField::Internal & F1) const inline protected
Definition at line 221 of file kOmegaSSTBase.H.
References kOmegaSSTBase< BasicEddyViscosityModel >::beta1_, kOmegaSSTBase< BasicEddyViscosityModel >::beta2_, kOmegaSSTBase< BasicEddyViscosityModel >::blend(), tmp< T >::New(), IOobject::scopedName(), and Foam::type().
gamma()
template<class BasicEddyViscosityModel > tmp< volScalarField::Internal > gamma (const volScalarField::Internal & F1) const inline protected
Definition at line 233 of file kOmegaSSTBase.H.
References kOmegaSSTBase< BasicEddyViscosityModel >::blend(), kOmegaSSTBase< BasicEddyViscosityModel >::gamma1_, kOmegaSSTBase< BasicEddyViscosityModel >::gamma2_, tmp< T >::New(), IOobject::scopedName(), and Foam::type().
correctNut() [1/2]
template<class BasicEddyViscosityModel > void correctNut (const volScalarField & S2) protected virtual
Reimplemented in kOmegaSSTSato< BasicTurbulenceModel >, kOmegaSSTDES< BasicTurbulenceModel >, and kOmegaSST< BasicTurbulenceModel >.
Definition at line 110 of file kOmegaSSTBase.C.
References Foam::max(), options::New(), and Foam::sqrt().
correctNut() [2/2]
template<class BasicEddyViscosityModel > void correctNut () protected virtual
Reimplemented in kOmegaSSTDES< BasicTurbulenceModel >, and kOmegaSST< BasicTurbulenceModel >.
Definition at line 123 of file kOmegaSSTBase.C.
References Foam::fvc::grad(), Foam::magSqr(), and Foam::symm().
S2()
template<class BasicEddyViscosityModel > Foam::tmp< Foam::volScalarField > S2 (const volTensorField & gradU) const protected virtual
Reimplemented in kOmegaSSTDDES< BasicTurbulenceModel >, and kOmegaSSTDES< BasicTurbulenceModel >.
Definition at line 130 of file kOmegaSSTBase.C.
References Foam::magSqr(), and Foam::symm().
Pk()
template<class BasicEddyViscosityModel > tmp< volScalarField::Internal > Pk (const volScalarField::Internal & G) const protected virtual
Reimplemented in kOmegaSSTLM< BasicTurbulenceModel >.
Definition at line 140 of file kOmegaSSTBase.C.
References Foam::min().
epsilonByk()
template<class BasicEddyViscosityModel > tmp< volScalarField::Internal > epsilonByk (const volScalarField & F1, const volTensorField & gradU) const protected virtual
Reimplemented in kOmegaSSTDES< BasicTurbulenceModel >, and kOmegaSSTLM< BasicTurbulenceModel >.
Definition at line 150 of file kOmegaSSTBase.C.
GbyNu0()
template<class BasicEddyViscosityModel > tmp< volScalarField::Internal > GbyNu0 (const volTensorField & gradU, const volScalarField & S2) const protected virtual
Reimplemented in kOmegaSSTDDES< BasicTurbulenceModel >, and kOmegaSSTDES< BasicTurbulenceModel >.
Definition at line 161 of file kOmegaSSTBase.C.
References Foam::devTwoSymm(), tmp< T >::New(), PtrList< T >::PtrList(), IOobject::scopedName(), and Foam::type().
GbyNu()
template<class BasicEddyViscosityModel > tmp< volScalarField::Internal > GbyNu (const volScalarField::Internal & GbyNu0, const volScalarField::Internal & F2, const volScalarField::Internal & S2) const protected virtual
Reimplemented in kOmegaSSTDDES< BasicTurbulenceModel >, and kOmegaSSTDES< BasicTurbulenceModel >.
Definition at line 176 of file kOmegaSSTBase.C.
kSource()
template<class BasicEddyViscosityModel > tmp< fvScalarMatrix > kSource () const protected virtual
Definition at line 192 of file kOmegaSSTBase.C.
References Foam::dimTime, Foam::dimVolume, and tmp< T >::New().
omegaSource()
template<class BasicEddyViscosityModel > tmp< fvScalarMatrix > omegaSource () const protected virtual
Definition at line 203 of file kOmegaSSTBase.C.
References Foam::dimTime, Foam::dimVolume, and tmp< T >::New().
Qsas()
template<class BasicEddyViscosityModel > tmp< fvScalarMatrix > Qsas (const volScalarField::Internal & S2, const volScalarField::Internal & gamma, const volScalarField::Internal & beta) const protected virtual
Reimplemented in kOmegaSSTSAS< BasicTurbulenceModel >.
Definition at line 214 of file kOmegaSSTBase.C.
References Foam::dimTime, Foam::dimVolume, and tmp< T >::New().
operator=()
template<class BasicEddyViscosityModel > void operator= (const kOmegaSSTBase< BasicEddyViscosityModel > &) delete
read()
template<class BasicEddyViscosityModel > bool read () virtual
Reimplemented in kOmegaSSTSato< BasicTurbulenceModel >, kOmegaSSTDDES< BasicTurbulenceModel >, kOmegaSSTDES< BasicTurbulenceModel >, kOmegaSSTIDDES< BasicTurbulenceModel >, kOmegaSSTLM< BasicTurbulenceModel >, and kOmegaSSTSAS< BasicTurbulenceModel >.
Definition at line 465 of file kOmegaSSTBase.C.
DkEff()
template<class BasicEddyViscosityModel > tmp< volScalarField > DkEff (const volScalarField & F1) const inline
Definition at line 337 of file kOmegaSSTBase.H.
References kOmegaSSTBase< BasicEddyViscosityModel >::alphaK(), F1, tmp< T >::New(), and nu.
DomegaEff()
template<class BasicEddyViscosityModel > tmp< volScalarField > DomegaEff (const volScalarField & F1) const inline
Definition at line 347 of file kOmegaSSTBase.H.
References kOmegaSSTBase< BasicEddyViscosityModel >::alphaOmega(), F1, tmp< T >::New(), and nu.
k()
template<class BasicEddyViscosityModel > virtual tmp< volScalarField > k () const inline virtual
Definition at line 357 of file kOmegaSSTBase.H.
References kOmegaSSTBase< BasicEddyViscosityModel >::k_.
omega()
template<class BasicEddyViscosityModel > virtual tmp< volScalarField > omega () const inline virtual
Definition at line 363 of file kOmegaSSTBase.H.
References kOmegaSSTBase< BasicEddyViscosityModel >::omega_.
correct()
template<class BasicEddyViscosityModel > void correct () virtual
Reimplemented in kOmegaSSTSato< BasicTurbulenceModel >, and kOmegaSSTLM< BasicTurbulenceModel >.
Definition at line 493 of file kOmegaSSTBase.C.
References Foam::fvc::absolute(), alpha, beta(), Foam::bound(), PtrList< T >::clear(), Foam::fvm::ddt(), Foam::fvc::div(), Foam::fvm::div(), divU, F1, fvOptions, gamma, Foam::fvc::grad(), Foam::fvm::laplacian(), options::New(), nut, phi, PtrList< T >::PtrList(), rho, solve(), Foam::fvm::Sp(), Foam::sqr(), Foam::fvm::SuSp(), and U.
Member Data Documentation
alphaK1_
template<class BasicEddyViscosityModel > dimensionedScalar alphaK1_ protected
Definition at line 135 of file kOmegaSSTBase.H.
Referenced by kOmegaSSTBase< BasicEddyViscosityModel >::alphaK().
alphaK2_
template<class BasicEddyViscosityModel > dimensionedScalar alphaK2_ protected
Definition at line 136 of file kOmegaSSTBase.H.
Referenced by kOmegaSSTBase< BasicEddyViscosityModel >::alphaK().
alphaOmega1_
template<class BasicEddyViscosityModel > dimensionedScalar alphaOmega1_ protected
Definition at line 138 of file kOmegaSSTBase.H.
Referenced by kOmegaSSTBase< BasicEddyViscosityModel >::alphaOmega().
alphaOmega2_
template<class BasicEddyViscosityModel > dimensionedScalar alphaOmega2_ protected
Definition at line 139 of file kOmegaSSTBase.H.
Referenced by kOmegaSSTBase< BasicEddyViscosityModel >::alphaOmega().
gamma1_
template<class BasicEddyViscosityModel > dimensionedScalar gamma1_ protected
Definition at line 141 of file kOmegaSSTBase.H.
Referenced by kOmegaSSTBase< BasicEddyViscosityModel >::gamma().
gamma2_
template<class BasicEddyViscosityModel > dimensionedScalar gamma2_ protected
Definition at line 142 of file kOmegaSSTBase.H.
Referenced by kOmegaSSTBase< BasicEddyViscosityModel >::gamma().
beta1_
template<class BasicEddyViscosityModel > dimensionedScalar beta1_ protected
Definition at line 144 of file kOmegaSSTBase.H.
Referenced by kOmegaSSTBase< BasicEddyViscosityModel >::beta().
beta2_
template<class BasicEddyViscosityModel > dimensionedScalar beta2_ protected
Definition at line 145 of file kOmegaSSTBase.H.
Referenced by kOmegaSSTBase< BasicEddyViscosityModel >::beta().
betaStar_
template<class BasicEddyViscosityModel > dimensionedScalar betaStar_ protected
Definition at line 147 of file kOmegaSSTBase.H.
a1_
template<class BasicEddyViscosityModel > dimensionedScalar a1_ protected
Definition at line 149 of file kOmegaSSTBase.H.
b1_
template<class BasicEddyViscosityModel > dimensionedScalar b1_ protected
Definition at line 150 of file kOmegaSSTBase.H.
c1_
template<class BasicEddyViscosityModel > dimensionedScalar c1_ protected
Definition at line 151 of file kOmegaSSTBase.H.
F3_
template<class BasicEddyViscosityModel > Switch F3_ protected
Definition at line 154 of file kOmegaSSTBase.H.
y_
template<class BasicEddyViscosityModel > const volScalarField& y_ protected
Definition at line 162 of file kOmegaSSTBase.H.
k_
template<class BasicEddyViscosityModel > volScalarField k_ protected
Definition at line 165 of file kOmegaSSTBase.H.
Referenced by kOmegaSSTBase< BasicEddyViscosityModel >::k().
omega_
template<class BasicEddyViscosityModel > volScalarField omega_ protected
Definition at line 168 of file kOmegaSSTBase.H.
Referenced by kOmegaSSTBase< BasicEddyViscosityModel >::omega().
decayControl_
template<class BasicEddyViscosityModel > Switch decayControl_ protected
Definition at line 174 of file kOmegaSSTBase.H.
kInf_
template<class BasicEddyViscosityModel > dimensionedScalar kInf_ protected
Definition at line 175 of file kOmegaSSTBase.H.
omegaInf_
template<class BasicEddyViscosityModel > dimensionedScalar omegaInf_ protected
Definition at line 176 of file kOmegaSSTBase.H.
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/Base/kOmegaSST/kOmegaSSTBase.H
src/TurbulenceModels/turbulenceModels/Base/kOmegaSST/kOmegaSSTBase.C