OpenFOAM: refinementData Class Reference
refinementData Class Reference
Transfers refinement levels such that slow transition between levels is maintained. Used in FaceCellWave.
#include <refinementData.H>
Public Member Functions
refinementData ()
refinementData (const label refinementCount, const label count)
label refinementCount () const
label & refinementCount ()
label count () const
label & count ()
bool isRefined () const
template<class TrackingData >
bool valid (TrackingData &td) const
template<class TrackingData >
bool sameGeometry (const polyMesh &, const refinementData &, const scalar, TrackingData &td) const
template<class TrackingData >
void leaveDomain (const polyMesh &, const polyPatch &, const label patchFacei, const point &faceCentre, TrackingData &td)
template<class TrackingData >
void enterDomain (const polyMesh &, const polyPatch &, const label patchFacei, const point &faceCentre, TrackingData &td)
template<class TrackingData >
void transform (const polyMesh &, const tensor &, TrackingData &td)
template<class TrackingData >
bool updateCell (const polyMesh &, const label thisCelli, const label neighbourFacei, const refinementData &neighbourInfo, const scalar tol, TrackingData &td)
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFacei, const label neighbourCelli, const refinementData &neighbourInfo, const scalar tol, TrackingData &td)
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFacei, const refinementData &neighbourInfo, const scalar tol, TrackingData &td)
template<class TrackingData >
bool equal (const refinementData &, TrackingData &td) const
bool operator== (const refinementData &) const
bool operator!= (const refinementData &) const
Friends
Ostream & operator<< (Ostream &, const refinementData &)
Istream & operator>> (Istream &, refinementData &)
Detailed Description
Transfers refinement levels such that slow transition between levels is maintained. Used in FaceCellWave.
Source files
refinementData.H
refinementDataI.H
refinementData.C
Definition at line 58 of file refinementData.H.
Constructor & Destructor Documentation
refinementData() [1/2]
refinementData () inline
Definition at line 24 of file refinementDataI.H.
refinementData() [2/2]
refinementData (const label refinementCount, const label count) inline
Definition at line 31 of file refinementDataI.H.
Member Function Documentation
refinementCount() [1/2]
label refinementCount () const inline
Definition at line 83 of file refinementData.H.
refinementCount() [2/2]
label & refinementCount () inline
Definition at line 87 of file refinementData.H.
count() [1/2]
label count () const inline
Definition at line 92 of file refinementData.H.
Referenced by hexRef8::consistentSlowRefinement().
count() [2/2]
label & count () inline
Definition at line 96 of file refinementData.H.
isRefined()
bool isRefined () const inline
Definition at line 101 of file refinementData.H.
valid()
template<class TrackingData > bool valid (TrackingData & td) const inline
Definition at line 45 of file refinementDataI.H.
sameGeometry()
template<class TrackingData > bool sameGeometry (const polyMesh & , const refinementData & , const scalar , TrackingData & td) const inline
Definition at line 53 of file refinementDataI.H.
leaveDomain()
template<class TrackingData > void leaveDomain (const polyMesh & , const polyPatch & patch, const label patchFacei, const point & faceCentre, TrackingData & td) inline
Definition at line 67 of file refinementDataI.H.
enterDomain()
template<class TrackingData > void enterDomain (const polyMesh & , const polyPatch & patch, const label patchFacei, const point & faceCentre, TrackingData & td) inline
Definition at line 91 of file refinementDataI.H.
transform()
template<class TrackingData > void transform (const polyMesh & , const tensor & rotTensor, TrackingData & td) inline
Definition at line 80 of file refinementDataI.H.
updateCell()
template<class TrackingData > bool updateCell (const polyMesh & , const label thisCelli, const label neighbourFacei, const refinementData & neighbourInfo, const scalar tol, TrackingData & td) inline
Definition at line 104 of file refinementDataI.H.
References Foam::abort(), UPtrList< T >::count(), Foam::FatalError, FatalErrorInFunction, and Foam::max().
updateFace() [1/2]
template<class TrackingData > bool updateFace (const polyMesh & , const label thisFacei, const label neighbourCelli, const refinementData & neighbourInfo, const scalar tol, TrackingData & td) inline
Definition at line 166 of file refinementDataI.H.
References UPtrList< T >::count().
Referenced by hexRef8::consistentSlowRefinement().
updateFace() [2/2]
template<class TrackingData > bool updateFace (const polyMesh & , const label thisFacei, const refinementData & neighbourInfo, const scalar tol, TrackingData & td) inline
Definition at line 201 of file refinementDataI.H.
References UPtrList< T >::count().
equal()
template<class TrackingData > bool equal (const refinementData & rhs, TrackingData & td) const inline
Definition at line 234 of file refinementDataI.H.
References Foam::operator==().
operator==()
bool operator== (const refinementData & rhs) const inline
Definition at line 246 of file refinementDataI.H.
operator!=()
bool operator!= (const refinementData & rhs) const inline
Definition at line 255 of file refinementDataI.H.
Friends And Related Symbol Documentation
operator<<
Ostream & operator<< (Ostream & , const refinementData &) friend
operator>>
Istream & operator>> (Istream & , refinementData &) friend
The documentation for this class was generated from the following files:
src/dynamicMesh/polyTopoChange/polyTopoChange/refinementData.H
src/dynamicMesh/polyTopoChange/polyTopoChange/refinementDataI.H