OpenFOAM: mappedVelocityFluxFixedValueFvPatchField Class Reference
mappedVelocityFluxFixedValueFvPatchField Class Reference
Boundary conditions » Inlet | Boundary conditions » Coupled
This boundary condition maps the velocity and flux from a neighbour patch to this patch.
#include <mappedVelocityFluxFixedValueFvPatchField.H>
Public Member Functions
TypeName ("mappedVelocityFlux")
mappedVelocityFluxFixedValueFvPatchField (const fvPatch &, const DimensionedField< vector, volMesh > &)
mappedVelocityFluxFixedValueFvPatchField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
mappedVelocityFluxFixedValueFvPatchField (const mappedVelocityFluxFixedValueFvPatchField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
mappedVelocityFluxFixedValueFvPatchField (const mappedVelocityFluxFixedValueFvPatchField &)
virtual tmp< fvPatchVectorField > clone () const
mappedVelocityFluxFixedValueFvPatchField (const mappedVelocityFluxFixedValueFvPatchField &, const DimensionedField< vector, volMesh > &)
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
This boundary condition maps the velocity and flux from a neighbour patch to this patch.
Usage
Property Description Required Default value
phi flux field name no phi
Example of the boundary condition specification:
    <patchName>
    {
        type            mappedVelocityFlux;
        phi             phi;
        value           uniform 0;  // place holder
    }
The underlying sample mode should be set to nearestPatchFace or nearestFace
Note
This boundary condition can only be applied to patches that are of the mappedPolyPatch type.
See also
Foam::mappedPatchBase Foam::mappedPolyPatch Foam::mappedFvPatch Foam::fixedValueFvPatchVectorField
Source files
mappedVelocityFluxFixedValueFvPatchField.H
mappedVelocityFluxFixedValueFvPatchField.C
Definition at line 90 of file mappedVelocityFluxFixedValueFvPatchField.H.
Constructor & Destructor Documentation
mappedVelocityFluxFixedValueFvPatchField() [1/5]
mappedVelocityFluxFixedValueFvPatchField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Definition at line 32 of file mappedVelocityFluxFixedValueFvPatchField.C.
mappedVelocityFluxFixedValueFvPatchField() [2/5]
mappedVelocityFluxFixedValueFvPatchField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Definition at line 69 of file mappedVelocityFluxFixedValueFvPatchField.C.
References dict, Foam::exit(), Foam::FatalError, FatalErrorInFunction, mappedPatchBase::NEARESTCELL, and p.
mappedVelocityFluxFixedValueFvPatchField() [3/5]
mappedVelocityFluxFixedValueFvPatchField (const mappedVelocityFluxFixedValueFvPatchField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 44 of file mappedVelocityFluxFixedValueFvPatchField.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and p.
mappedVelocityFluxFixedValueFvPatchField() [4/5]
mappedVelocityFluxFixedValueFvPatchField (const mappedVelocityFluxFixedValueFvPatchField & ptf)
Definition at line 109 of file mappedVelocityFluxFixedValueFvPatchField.C.
mappedVelocityFluxFixedValueFvPatchField() [5/5]
mappedVelocityFluxFixedValueFvPatchField (const mappedVelocityFluxFixedValueFvPatchField & ptf, const DimensionedField< vector, volMesh > & iF)
Definition at line 120 of file mappedVelocityFluxFixedValueFvPatchField.C.
Member Function Documentation
TypeName()
TypeName ("mappedVelocityFlux")
clone() [1/2]
virtual tmp< fvPatchVectorField > clone () const inline virtual
Definition at line 140 of file mappedVelocityFluxFixedValueFvPatchField.H.
clone() [2/2]
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Definition at line 156 of file mappedVelocityFluxFixedValueFvPatchField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 134 of file mappedVelocityFluxFixedValueFvPatchField.C.
References Foam::abort(), boundaryFieldRef(), Foam::FatalError, FatalErrorInFunction, forAll, UPstream::msgType(), mappedPatchBase::NEARESTFACE, mappedPatchBase::NEARESTPATCHFACE, mappedPatchBase::NEARESTPATCHFACEAMI, Foam::nl, Foam::operator==(), PtrList< T >::transfer(), and Foam::Zero.
write()
void write (Ostream & os) const virtual
Definition at line 227 of file mappedVelocityFluxFixedValueFvPatchField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntryIfDifferent(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/mappedVelocityFluxFixedValue/mappedVelocityFluxFixedValueFvPatchField.H
src/finiteVolume/fields/fvPatchFields/derived/mappedVelocityFluxFixedValue/mappedVelocityFluxFixedValueFvPatchField.C