OpenFOAM: multiDirRefinement Class Reference
multiDirRefinement Class Reference
Does multiple pass refinement to refine cells in multiple directions.
#include <multiDirRefinement.H>
Public Member Functions
ClassName ("multiDirRefinement")
multiDirRefinement (polyMesh &mesh, const labelList &cellLabels, const dictionary &dict)
multiDirRefinement (polyMesh &mesh, const labelList &cellLabels, const List< vectorField > &, const dictionary &dict)
multiDirRefinement (polyMesh &mesh, undoableMeshCutter &cutter, const cellLooper &cellCutter, const labelList &cellLabels, const List< vectorField > &directions, const bool writeMesh=false)
const labelListList & addedCells () const
Detailed Description
Does multiple pass refinement to refine cells in multiple directions.
Gets a list of cells to refine and vectorFields for the whole mesh. It then tries to refine in one direction after the other the wanted cells. After construction the mesh will have been refined in multiple directions.
Holds the list of cells to refine and the map from original to added for every refinement level.
Gets constructed from a dictionary or from components. Uses an undoableMeshCutter which does the actual cutting. Undo facility is switched of unless constructed from external one which allows this.
The cut cells get stored in addedCells which is for every vectorField to cut with the map from uncut to added cell (i.e. from master to slave). Note: map is only valid for a given direction.
Parallel: should be ok. Uses 'reduce' whenever it needs to make a local decision.
Source files
multiDirRefinement.H
multiDirRefinement.C
Definition at line 72 of file multiDirRefinement.H.
Constructor & Destructor Documentation
multiDirRefinement() [1/3]
multiDirRefinement (polyMesh & mesh, const labelList & cellLabels, const dictionary & dict)
Definition at line 476 of file multiDirRefinement.C.
References dict, mesh, Foam::returnReduceOr(), UPtrList< T >::size(), and UList< T >::size().
multiDirRefinement() [2/3]
multiDirRefinement (polyMesh & mesh, const labelList & cellLabels, const List< vectorField > & cellDirs, const dictionary & dict)
Definition at line 514 of file multiDirRefinement.C.
References dict, mesh, Foam::returnReduceOr(), UPtrList< T >::size(), and UList< T >::size().
multiDirRefinement() [3/3]
multiDirRefinement (polyMesh & mesh, undoableMeshCutter & cutter, const cellLooper & cellCutter, const labelList & cellLabels, const List< vectorField > & directions, const bool writeMesh = false)
Definition at line 552 of file multiDirRefinement.C.
References mesh.
Member Function Documentation
ClassName()
ClassName ("multiDirRefinement")
addedCells()
const labelListList & addedCells () const inline
Definition at line 188 of file multiDirRefinement.H.
The documentation for this class was generated from the following files:
src/dynamicMesh/meshCut/meshModifiers/multiDirRefinement/multiDirRefinement.H
src/dynamicMesh/meshCut/meshModifiers/multiDirRefinement/multiDirRefinement.C