OpenFOAM: SpalartAllmarasDDES< BasicTurbulenceModel > Class Template Reference
SpalartAllmarasDDES< BasicTurbulenceModel > Class Template Reference
Turbulence models » DES turbulence
SpalartAllmaras DDES turbulence model for incompressible and compressible flows.
#include <SpalartAllmarasDDES.H>
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from SpalartAllmarasDES< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("SpalartAllmarasDDES")
SpalartAllmarasDDES (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
virtual ~SpalartAllmarasDDES ()=default
virtual bool read ()
virtual tmp< volScalarField > fd () const
Public Member Functions inherited from SpalartAllmarasDES< BasicTurbulenceModel >
TypeName ("SpalartAllmarasDES")
SpalartAllmarasDES (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
virtual ~SpalartAllmarasDES ()=default
virtual tmp< volScalarField > LESRegion () const
Protected Member Functions
virtual tmp< volScalarField > Stilda (const volScalarField &chi, const volScalarField &fv1, const volTensorField &gradU, const volScalarField &dTilda) const
virtual tmp< volScalarField > dTilda (const volScalarField &chi, const volScalarField &fv1, const volTensorField &gradU) const
Protected Member Functions inherited from SpalartAllmarasDES< BasicTurbulenceModel >
virtual tmp< volScalarField > psi (const volScalarField &chi, const volScalarField &fv1) const
virtual tmp< volScalarField > lengthScaleLES (const volScalarField &chi, const volScalarField &fv1) const
virtual void correctNut ()
Protected Attributes
dimensionedScalar Cd1_
dimensionedScalar Cd2_
Protected Attributes inherited from SpalartAllmarasDES< BasicTurbulenceModel >
Switch useSigma_
dimensionedScalar CDES_
Switch lowReCorrection_
dimensionedScalar fwStar_
Detailed Description
template<class BasicTurbulenceModel>
class Foam::LESModels::SpalartAllmarasDDES< BasicTurbulenceModel >
SpalartAllmaras DDES turbulence model for incompressible and compressible flows.
Reference:
    Spalart, P. R., Deck, S., Shur, M. L., Squires,
    K. D., Strelets, M. K., & Travin, A. (2006).
    A new version of detached-eddy simulation,
    resistant to ambiguous grid densities.
    Theoretical and computational fluid dynamics, 20(3), 181-195.
    DOI:10.1007/s00162-006-0015-0
Source files
SpalartAllmarasDDES.H
SpalartAllmarasDDES.C
Definition at line 65 of file SpalartAllmarasDDES.H.
Member Typedef Documentation
alphaField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 113 of file SpalartAllmarasDDES.H.
rhoField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 114 of file SpalartAllmarasDDES.H.
transportModel
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 115 of file SpalartAllmarasDDES.H.
Constructor & Destructor Documentation
SpalartAllmarasDDES()
template<class BasicTurbulenceModel > SpalartAllmarasDDES (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Definition at line 111 of file SpalartAllmarasDDES.C.
References Foam::type().
~SpalartAllmarasDDES()
template<class BasicTurbulenceModel > virtual ~SpalartAllmarasDDES () virtual default
Member Function Documentation
Stilda()
template<class BasicTurbulenceModel > tmp< volScalarField > Stilda (const volScalarField & chi, const volScalarField & fv1, const volTensorField & gradU, const volScalarField & dTilda) const protected virtual
Reimplemented from SpalartAllmarasDES< BasicTurbulenceModel >.
Definition at line 49 of file SpalartAllmarasDDES.C.
References Foam::mag(), Foam::max(), Foam::pos(), and Foam::sqr().
dTilda()
template<class BasicTurbulenceModel > tmp< volScalarField > dTilda (const volScalarField & chi, const volScalarField & fv1, const volTensorField & gradU) const protected virtual
Reimplemented from SpalartAllmarasDES< BasicTurbulenceModel >.
Definition at line 89 of file SpalartAllmarasDDES.C.
References Foam::dimLength, Foam::mag(), Foam::max(), and Foam::Zero.
TypeName()
template<class BasicTurbulenceModel > TypeName ("SpalartAllmarasDDES< BasicTurbulenceModel >")
read()
template<class BasicTurbulenceModel > bool read () virtual
Reimplemented from SpalartAllmarasDES< BasicTurbulenceModel >.
Definition at line 171 of file SpalartAllmarasDDES.C.
fd()
template<class BasicTurbulenceModel > tmp< volScalarField > fd () const virtual
Definition at line 186 of file SpalartAllmarasDDES.C.
References Foam::fvc::grad(), and Foam::mag().
Member Data Documentation
Cd1_
template<class BasicTurbulenceModel > dimensionedScalar Cd1_ protected
Definition at line 87 of file SpalartAllmarasDDES.H.
Cd2_
template<class BasicTurbulenceModel > dimensionedScalar Cd2_ protected
Definition at line 88 of file SpalartAllmarasDDES.H.
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/DES/SpalartAllmarasDDES/SpalartAllmarasDDES.H
src/TurbulenceModels/turbulenceModels/DES/SpalartAllmarasDDES/SpalartAllmarasDDES.C