OpenFOAM: GAMGProcAgglomeration Class Reference
GAMGProcAgglomeration Class Reference abstract
Processor agglomeration of GAMGAgglomerations.
#include <GAMGProcAgglomeration.H>
Public Member Functions
TypeName ("GAMGProcAgglomeration")
declareRunTimeSelectionTable (autoPtr, GAMGProcAgglomeration, GAMGAgglomeration,(GAMGAgglomeration &agglom, const dictionary &controlDict),(agglom, controlDict))
GAMGProcAgglomeration (const GAMGProcAgglomeration &)=delete
void operator= (const GAMGProcAgglomeration &)=delete
GAMGProcAgglomeration (GAMGAgglomeration &agglom, const dictionary &controlDict)
virtual ~GAMGProcAgglomeration ()
virtual bool agglomerate ()=0
Static Public Member Functions
static autoPtr< GAMGProcAgglomeration > New (const word &type, GAMGAgglomeration &agglom, const dictionary &controlDict)
Protected Member Functions
void printStats (Ostream &os, GAMGAgglomeration &agglom) const
bool agglomerate (const label fineLevelIndex, const labelList &procAgglomMap, const labelList &masterProcs, const List< label > &agglomProcIDs, const label procAgglomComm)
void clearCommunicators ()
Static Protected Member Functions
static labelListList globalCellCells (const lduMesh &)
Protected Attributes
GAMGAgglomeration & agglom_
DynamicList< label > comms_
Detailed Description
Processor agglomeration of GAMGAgglomerations.
Source files
GAMGProcAgglomeration.H
GAMGProcAgglomeration.C
Definition at line 54 of file GAMGProcAgglomeration.H.
Constructor & Destructor Documentation
GAMGProcAgglomeration() [1/2]
GAMGProcAgglomeration (const GAMGProcAgglomeration &) delete
GAMGProcAgglomeration() [2/2]
GAMGProcAgglomeration (GAMGAgglomeration & agglom, const dictionary & controlDict)
Definition at line 339 of file GAMGProcAgglomeration.C.
~GAMGProcAgglomeration()
~GAMGProcAgglomeration () virtual
Definition at line 376 of file GAMGProcAgglomeration.C.
Member Function Documentation
printStats()
void printStats (Ostream & os, GAMGAgglomeration & agglom) const protected
Definition at line 37 of file GAMGProcAgglomeration.C.
References Foam::endl(), forAll, Foam::max(), Foam::nl, os(), PtrList< T >::set(), and UPtrList< T >::size().
agglomerate() [1/2]
bool agglomerate (const label fineLevelIndex, const labelList & procAgglomMap, const labelList & masterProcs, const List< label > & agglomProcIDs, const label procAgglomComm) protected
Definition at line 261 of file GAMGProcAgglomeration.C.
References UPstream::myProcNo(), and UPtrList< T >::size().
globalCellCells()
Foam::labelListList globalCellCells (const lduMesh & mesh) static protected
Definition at line 115 of file GAMGProcAgglomeration.C.
References fvMesh::comm(), forAll, Foam::identity(), fvMesh::interfaces(), fvMesh::lduAddr(), globalIndex::localSize(), globalIndex::localStart(), mesh, UPstream::myProcNo(), UPstream::nonBlocking, UPstream::nRequests(), UPstream::parRun(), PtrList< T >::set(), UPtrList< T >::set(), List< T >::setSize(), UPtrList< T >::size(), Foam::stableSort(), and UPstream::waitRequests().
clearCommunicators()
void clearCommunicators () protected
Definition at line 384 of file GAMGProcAgglomeration.C.
References forAllReverse, and UPstream::freeCommunicator().
TypeName()
TypeName ("GAMGProcAgglomeration")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , GAMGProcAgglomeration , GAMGAgglomeration , (GAMGAgglomeration &agglom, const dictionary &controlDict) , (agglom, controlDict))
operator=()
void operator= (const GAMGProcAgglomeration &) delete
New()
Foam::autoPtr< Foam::GAMGProcAgglomeration > New (const word & type, GAMGAgglomeration & agglom, const dictionary & controlDict) static
Definition at line 349 of file GAMGProcAgglomeration.C.
References controlDict(), DebugInFunction, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::nl, and Foam::type().
agglomerate() [2/2]
virtual bool agglomerate () pure virtual
Implemented in eagerGAMGProcAgglomeration, manualGAMGProcAgglomeration, masterCoarsestGAMGProcAgglomeration, noneGAMGProcAgglomeration, and procFacesGAMGProcAgglomeration.
Referenced by eagerGAMGProcAgglomeration::agglomerate(), manualGAMGProcAgglomeration::agglomerate(), masterCoarsestGAMGProcAgglomeration::agglomerate(), and procFacesGAMGProcAgglomeration::agglomerate().
Member Data Documentation
agglom_
GAMGAgglomeration& agglom_ protected
Definition at line 61 of file GAMGProcAgglomeration.H.
comms_
DynamicList<label> comms_ protected
Definition at line 64 of file GAMGProcAgglomeration.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/GAMGProcAgglomerations/GAMGProcAgglomeration/GAMGProcAgglomeration.H
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/GAMGProcAgglomerations/GAMGProcAgglomeration/GAMGProcAgglomeration.C