OpenFOAM: CHFSubCoolModel Class Reference
CHFSubCoolModel Class Reference abstract
#include <CHFSubCoolModel.H>
Public Member Functions
TypeName ("CHFSubCoolModel")
declareRunTimeSelectionTable (autoPtr, CHFSubCoolModel, dictionary,(const dictionary &dict),(dict))
CHFSubCoolModel ()=default
virtual ~CHFSubCoolModel ()=default
virtual tmp< scalarField > CHFSubCool (const phaseModel &liquid, const phaseModel &vapor, const label patchi, const scalarField &Tl, const scalarField &Tsatw, const scalarField &L) const =0
virtual void write (Ostream &os) const
Static Public Member Functions
static autoPtr< CHFSubCoolModel > New (const dictionary &dict)
Detailed Description
Definition at line 53 of file CHFSubCoolModel.H.
Constructor & Destructor Documentation
CHFSubCoolModel()
CHFSubCoolModel () default
~CHFSubCoolModel()
virtual ~CHFSubCoolModel () virtual default
Member Function Documentation
TypeName()
TypeName ("CHFSubCoolModel")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , CHFSubCoolModel , dictionary , (const dictionary &dict) , (dict))
New()
Foam::autoPtr< Foam::wallBoilingModels::CHFSubCoolModel > New (const dictionary & dict) static
Definition at line 38 of file CHFSubCoolModel.C.
References Foam::abort(), dict, Foam::endl(), Foam::FatalIOError, FatalIOErrorInLookup, and Foam::Info.
Referenced by alphatWallBoilingWallFunctionFvPatchScalarField::alphatWallBoilingWallFunctionFvPatchScalarField().
CHFSubCool()
virtual tmp< scalarField > CHFSubCool (const phaseModel & liquid, const phaseModel & vapor, const label patchi, const scalarField & Tl, const scalarField & Tsatw, const scalarField & L) const pure virtual
Implemented in HuaXu, and Tatsumoto.
write()
void write (Ostream & os) const virtual
Reimplemented in HuaXu, and Tatsumoto.
Definition at line 66 of file CHFSubCoolModel.C.
References os(), and Foam::type().
Referenced by HuaXu::write(), and Tatsumoto::write().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/wallBoilingSubModels/CHFSubCoolModels/CHFSubCoolModel/CHFSubCoolModel.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/wallBoilingSubModels/CHFSubCoolModels/CHFSubCoolModel/CHFSubCoolModel.C