OpenFOAM: LimitedScheme< Type, Limiter, LimitFunc > Class Template Reference
LimitedScheme< Type, Limiter, LimitFunc > Class Template Reference
Numerics » Finite volume numerical schemes » Surface interpolation schemes » Limited interpolation schemes
Class to create NVD/TVD limited weighting-factors.
#include <LimitedScheme.H>
Public Types
typedef Limiter LimiterType
Public Member Functions
TypeName ("LimitedScheme")
LimitedScheme (const fvMesh &mesh, const surfaceScalarField &faceFlux, const Limiter &weight)
LimitedScheme (const fvMesh &mesh, Istream &is)
LimitedScheme (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &is)
virtual tmp< surfaceScalarField > limiter (const GeometricField< Type, fvPatchField, volMesh > &) const
Public Member Functions inherited from limitedSurfaceInterpolationScheme< Type >
TypeName ("limitedSurfaceInterpolationScheme")
declareRunTimeSelectionTable (tmp, limitedSurfaceInterpolationScheme, Mesh,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
declareRunTimeSelectionTable (tmp, limitedSurfaceInterpolationScheme, MeshFlux,(const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
limitedSurfaceInterpolationScheme (const fvMesh &mesh, const surfaceScalarField &faceFlux)
limitedSurfaceInterpolationScheme (const fvMesh &mesh, Istream &is)
virtual ~limitedSurfaceInterpolationScheme ()
tmp< surfaceScalarField > weights (const GeometricField< Type, fvPatchField, volMesh > &, const surfaceScalarField &CDweights, tmp< surfaceScalarField > tLimiter) const
virtual tmp< surfaceScalarField > weights (const GeometricField< Type, fvPatchField, volMesh > &) const
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const GeometricField< Type, fvPatchField, volMesh > &) const
Public Member Functions inherited from surfaceInterpolationScheme< Type >
TypeName ("surfaceInterpolationScheme")
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, Mesh,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, MeshFlux,(const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
surfaceInterpolationScheme (const fvMesh &mesh)
virtual ~surfaceInterpolationScheme ()=default
const fvMesh & mesh () const
virtual bool corrected () const
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > &) const
virtual tmp< GeometricField< typename innerProduct< vector, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf) const
tmp< GeometricField< typename innerProduct< vector, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const tmp< GeometricField< Type, fvPatchField, volMesh > > &) const
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &) const
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > &) const
template<class SFType >
Foam::tmp< Foam::GeometricField< typename Foam::innerProduct< typename SFType::value_type, Type >::type, Foam::fvsPatchField, Foam::surfaceMesh > > dotInterpolate (const SFType &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf, const tmp< surfaceScalarField > &tlambdas)
tmp< GeometricField< typename innerProduct< vector, scalar >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const GeometricField< scalar, fvPatchField, volMesh > &) const
Foam::tmp< Foam::GeometricField< typename Foam::innerProduct< Foam::vector, Foam::scalar >::type, Foam::fvsPatchField, Foam::surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const GeometricField< scalar, fvPatchField, volMesh > &) const
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Additional Inherited Members
Static Public Member Functions inherited from limitedSurfaceInterpolationScheme< Type >
static tmp< limitedSurfaceInterpolationScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
static tmp< limitedSurfaceInterpolationScheme< Type > > New (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData)
Static Public Member Functions inherited from surfaceInterpolationScheme< Type >
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData)
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &, const tmp< surfaceScalarField > &)
template<class SFType >
static tmp< GeometricField< typename innerProduct< typename SFType::value_type, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const SFType &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf, const tmp< surfaceScalarField > &tlambdas)
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &)
Protected Attributes inherited from limitedSurfaceInterpolationScheme< Type >
const surfaceScalarField & faceFlux_
Detailed Description
template<class Type, class Limiter, template< class > class LimitFunc>
class Foam::LimitedScheme< Type, Limiter, LimitFunc >
Class to create NVD/TVD limited weighting-factors.
The particular differencing scheme class is supplied as a template argument, the weight function of which is called by the weight function of this class for the internal faces as well as faces of coupled patches (e.g. processor-processor patches). The weight function is supplied the central-differencing weighting factor, the face-flux, the cell and face gradients (from which the normalised variable distribution may be created) and the cell centre distance.
This code organisation is both neat and efficient, allowing for convenient implementation of new schemes to run on parallelised cases.
Source files
LimitedScheme.H
LimitedScheme.C
Definition at line 64 of file LimitedScheme.H.
Member Typedef Documentation
LimiterType
template<class Type , class Limiter , template< class > class LimitFunc> typedef Limiter LimiterType
Definition at line 90 of file LimitedScheme.H.
Constructor & Destructor Documentation
LimitedScheme() [1/3]
template<class Type , class Limiter , template< class > class LimitFunc> LimitedScheme (const fvMesh & mesh, const surfaceScalarField & faceFlux, const Limiter & weight) inline
Definition at line 95 of file LimitedScheme.H.
LimitedScheme() [2/3]
template<class Type , class Limiter , template< class > class LimitFunc> LimitedScheme (const fvMesh & mesh, Istream & is) inline
Definition at line 109 of file LimitedScheme.H.
LimitedScheme() [3/3]
template<class Type , class Limiter , template< class > class LimitFunc> LimitedScheme (const fvMesh & mesh, const surfaceScalarField & faceFlux, Istream & is) inline
Definition at line 120 of file LimitedScheme.H.
Member Function Documentation
TypeName()
template<class Type , class Limiter , template< class > class LimitFunc> TypeName ("LimitedScheme< Type, Limiter, LimitFunc >")
limiter()
template<class Type , class Limiter , template< class > class LimitFunc> Foam::tmp< Foam::surfaceScalarField > limiter (const GeometricField< Type, fvPatchField, volMesh > & phi) const virtual
Implements limitedSurfaceInterpolationScheme< Type >.
Definition at line 136 of file LimitedScheme.C.
References Foam::dimless, objectRegistry::getObjectPtr(), mesh, tmp< T >::New(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, phi, IOobjectOption::REGISTER, fvMesh::time(), and Foam::type().
Referenced by LimitedLimiter< LimitedScheme >::limiter().
The documentation for this class was generated from the following files:
src/finiteVolume/interpolation/surfaceInterpolation/limitedSchemes/LimitedScheme/LimitedScheme.H
src/finiteVolume/interpolation/surfaceInterpolation/limitedSchemes/LimitedScheme/LimitedScheme.C