OpenFOAM: scalars Class Reference
scalars Class Reference
A list of unary predicates (tests) on scalars. Includes a number of standard comparison predicates (eg, "less", "greater", ...)
#include <scalarPredicates.H>
Public Types
enum opType {
EQUAL , NOT_EQUAL , LESS , LESS_EQUAL ,
GREATER , GREATER_EQUAL , ALWAYS , NEVER ,
LESS_EQ = LESS_EQUAL , GREATER_EQ = GREATER_EQUAL
}
typedef std::function< bool(Foam::scalar)> unary
Public Types inherited from List< std::function< bool(Foam::scalar)> >
typedef SubList< std::function< bool(Foam::scalar)> > subList
Public Types inherited from UList< T >
typedef T value_type
typedef T * pointer
typedef const T * const_pointer
typedef T & reference
typedef const T & const_reference
typedef T * iterator
typedef const T * const_iterator
typedef label size_type
typedef label difference_type
typedef std::reverse_iterator< iterator > reverse_iterator
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
Public Member Functions
scalars (std::initializer_list< std::pair< word, scalar > > entries)
scalars (const UList< Tuple2< word, scalar > > &entries)
scalars (Istream &is)
~scalars ()=default
void assign (std::initializer_list< std::pair< word, scalar > > entries)
void assign (const UList< Tuple2< word, scalar > > &entries)
label find (const scalar value, label pos=0) const
label rfind (const scalar value, label pos=-1) const
bool contains (const scalar value, label pos=0) const
bool match (const scalar value) const
bool matchAny (const scalar value) const
bool matchAll (const scalar value) const
labelList matching (const scalar value) const
labelList matching (const UList< scalar > &input, const bool invert=false) const
bool operator() (const scalar value) const
bool found (const scalar value, label pos=0) const
Public Member Functions inherited from List< std::function< bool(Foam::scalar)> >
constexpr List () noexcept
List (const label len)
List (const label len, const std::function< bool(Foam::scalar)> &val)
List (const label len, const Foam::zero)
List (const Foam::one, const std::function< bool(Foam::scalar)> &val)
List (const Foam::one, std::function< bool(Foam::scalar)> &&val)
List (const Foam::one, const Foam::zero)
List (const List< std::function< bool(Foam::scalar)> > &a)
List (const UList< std::function< bool(Foam::scalar)> > &a)
List (List< std::function< bool(Foam::scalar)> > &a, bool reuse)
List (const UList< std::function< bool(Foam::scalar)> > &list, const labelUList &indices)
List (const UList< std::function< bool(Foam::scalar)> > &list, const FixedList< label, N > &indices)
List (const FixedList< std::function< bool(Foam::scalar)>, N > &list)
List (const PtrList< std::function< bool(Foam::scalar)> > &list)
List (const SLList< std::function< bool(Foam::scalar)> > &list)
List (const IndirectListBase< std::function< bool(Foam::scalar)>, Addr > &list)
List (std::initializer_list< std::function< bool(Foam::scalar)> > list)
List (List< std::function< bool(Foam::scalar)> > &&list)
List (DynamicList< std::function< bool(Foam::scalar)>, SizeMin > &&list)
List (SLList< std::function< bool(Foam::scalar)> > &&list)
List (Istream &is)
autoPtr< List< std::function< bool(Foam::scalar)> > > clone () const
~List ()
void clear ()
void resize (const label len)
void resize (const label len, const std::function< bool(Foam::scalar)> &val)
void resize (const label newLen)
void resize_nocopy (const label len)
void setSize (const label n)
void setSize (const label n, const std::function< bool(Foam::scalar)> &val)
void transfer (List< std::function< bool(Foam::scalar)> > &list)
void transfer (DynamicList< std::function< bool(Foam::scalar)>, SizeMin > &list)
std::function< bool(Foam::scalar)> & newElmt (const label i)
std::function< bool(Foam::scalar)> & emplace_back (Args &&... args)
void push_back (const std::function< bool(Foam::scalar)> &val)
void push_back (std::function< bool(Foam::scalar)> &&val)
void push_back (const UList< std::function< bool(Foam::scalar)> > &list)
void push_back (const IndirectListBase< std::function< bool(Foam::scalar)>, Addr > &list)
label push_uniq (const std::function< bool(Foam::scalar)> &val)
void pop_back (label n=1)
void operator= (const UList< std::function< bool(Foam::scalar)> > &a)
void operator= (const List< std::function< bool(Foam::scalar)> > &list)
void operator= (const SLList< std::function< bool(Foam::scalar)> > &list)
void operator= (const IndirectListBase< std::function< bool(Foam::scalar)>, Addr > &list)
void operator= (const FixedList< std::function< bool(Foam::scalar)>, N > &list)
void operator= (std::initializer_list< std::function< bool(Foam::scalar)> > list)
void operator= (const std::function< bool(Foam::scalar)> &val)
void operator= (const Foam::zero)
void operator= (List< std::function< bool(Foam::scalar)> > &&list)
void operator= (DynamicList< std::function< bool(Foam::scalar)>, SizeMin > &&list)
void operator= (SLList< std::function< bool(Foam::scalar)> > &&list)
Istream & readList (Istream &is)
Istream & readList (Istream &is)
Istream & readList (Istream &is)
void shallowCopy (const UList< std::function< bool(Foam::scalar)> > &)=delete
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type set (const label i, bool val=true)
void append (const std::function< bool(Foam::scalar)> &val)
void append (std::function< bool(Foam::scalar)> &&val)
void append (const UList< std::function< bool(Foam::scalar)> > &list)
void append (const IndirectListBase< std::function< bool(Foam::scalar)>, Addr > &list)
label appendUniq (const std::function< bool(Foam::scalar)> &val)
Public Member Functions inherited from UList< T >
UList (const UList< T > &)=default
constexpr UList () noexcept
UList (T *__restrict__ v, const label len) noexcept
label fcIndex (const label i) const noexcept
label rcIndex (const label i) const noexcept
const T & fcValue (const label i) const
T & fcValue (const label i)
const T & rcValue (const label i) const
T & rcValue (const label i)
const T * cdata () const noexcept
T * data () noexcept
const char * cdata_bytes () const noexcept
char * data_bytes () noexcept
T & front ()
const T & front () const
T & back ()
const T & back () const
std::streamsize size_bytes () const noexcept
std::streamsize byteSize () const
void checkStart (const label start) const
void checkSize (const label size) const
void checkRange (const label start, const label len) const
void checkIndex (const label i) const
bool uniform () const
label find (const T &val, label pos=0) const
label rfind (const T &val, label pos=-1) const
bool contains (const T &val, label pos=0) const
void moveFirst (const label i)
void moveLast (const label i)
void swapFirst (const label i)
void swapLast (const label i)
void shallowCopy (const UList< T > &list)
void deepCopy (const UList< T > &list)
template<class Addr >
void deepCopy (const IndirectListBase< T, Addr > &list)
SubList< T > slice (const label pos, label len=-1)
const SubList< T > slice (const label pos, label len=-1) const
SubList< T > slice (const labelRange &range)
const SubList< T > slice (const labelRange &range) const
T & operator[] (const label i)
const T & operator[] (const label i) const
operator const Foam::List< T > & () const
void operator= (const T &val)
void operator= (const Foam::zero)
iterator begin () noexcept
iterator end () noexcept
iterator begin (const label i) noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
const_iterator begin () const noexcept
const_iterator end () const noexcept
const_iterator cbegin (const label i) const noexcept
const_iterator begin (const label i) const noexcept
reverse_iterator rbegin ()
reverse_iterator rend ()
const_reverse_iterator crbegin () const
const_reverse_iterator crend () const
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
bool empty () const noexcept
label size () const noexcept
void swap (UList< T > &list)
bool operator== (const UList< T > &a) const
bool operator!= (const UList< T > &a) const
bool operator< (const UList< T > &list) const
bool operator> (const UList< T > &a) const
bool operator<= (const UList< T > &a) const
bool operator>= (const UList< T > &a) const
Istream & readList (Istream &is)
void writeEntry (const word &keyword, Ostream &os) const
Ostream & writeList (Ostream &os, const label shortLen=0) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type test (const label i) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type get (const label i) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type unset (const label i)
T & first ()
const T & first () const
T & last ()
const T & last () const
bool found (const T &val, label pos=0) const
Istream & readList (Istream &is)
Ostream & writeList (Ostream &os, const label) const
const bool & operator[] (const label i) const
UPstream::commsStruct & operator[] (const label procID)
const UPstream::commsStruct & operator[] (const label procID) const
Foam::UPstream::commsStruct & operator[] (const label procID)
const Foam::UPstream::commsStruct & operator[] (const label procID) const
Ostream & writeList (Ostream &os, const label) const
Istream & readList (Istream &is)
Static Public Member Functions
static unary equalOp (const scalar opVal, const scalar tol=VSMALL)
static unary notEqualOp (const scalar opVal, const scalar tol=VSMALL)
static unary lessOp (const scalar opVal)
static unary lessEqualOp (const scalar opVal)
static unary greaterOp (const scalar opVal)
static unary greaterEqualOp (const scalar opVal)
static unary trueOp ()
static unary falseOp ()
static unary andOp (const unary &test1, const unary &test2)
static unary orOp (const unary &test1, const unary &test2)
static unary operation (const opType op, const scalar opVal, const scalar tol=VSMALL)
static unary operation (const word &opName, const scalar opVal, const scalar tol=VSMALL)
static unary operation (const Tuple2< word, scalar > &op, const scalar tol=VSMALL)
static unary operation (const std::pair< word, scalar > &op, const scalar tol=VSMALL)
Static Public Member Functions inherited from List< std::function< bool(Foam::scalar)> >
static const List< std::function< bool(Foam::scalar)> > & null ()
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
static constexpr label max_size () noexcept
Static Public Attributes
static const Enum< opType > opNames
Additional Inherited Members
Protected Member Functions inherited from UList< T >
void setAddressableSize (const label n) noexcept
void size (const label n)
void writeEntry (Ostream &os) const
labelRange validateRange (const labelRange &requestedRange) const
UList< T > & operator= (const UList< T > &)=delete
void writeEntry (Ostream &os) const
void writeEntry (Ostream &os) const
Detailed Description
A list of unary predicates (tests) on scalars. Includes a number of standard comparison predicates (eg, "less", "greater", ...)
Note
This class is still subject to larger changes (2018-11) as it matures.
See also
Foam::scalarRange, Foam::scalarRanges
Source files
scalarPredicates.H
scalarPredicates.C
scalarPredicatesI.H
Definition at line 62 of file scalarPredicates.H.
Member Typedef Documentation
unary
typedef std::function<bool(Foam::scalar)> unary
Definition at line 71 of file scalarPredicates.H.
Member Enumeration Documentation
opType
enum opType
Enumerator
EQUAL
"eq", "equal"
NOT_EQUAL
"neq", "notEqual"
LESS
"lt", "less"
LESS_EQUAL
"le", "lessEqual", "lessEq"
GREATER
"gt", "greater"
GREATER_EQUAL
"ge", "greaterEqual", "greaterEq"
ALWAYS
Always matches.
NEVER
Never matches.
LESS_EQ
GREATER_EQ
Definition at line 74 of file scalarPredicates.H.
Constructor & Destructor Documentation
scalars() [1/3]
scalars (std::initializer_list< std::pair< word, scalar > > entries) explicit
Definition at line 176 of file scalarPredicates.C.
scalars() [2/3]
scalars (const UList< Tuple2< word, scalar > > & entries) explicit
Definition at line 185 of file scalarPredicates.C.
scalars() [3/3]
scalars (Istream & is) explicit
Definition at line 194 of file scalarPredicates.C.
~scalars()
~scalars () default
Member Function Documentation
equalOp()
static unary equalOp (const scalar opVal, const scalar tol = VSMALL) inline static
Definition at line 97 of file scalarPredicates.H.
References Foam::mag().
notEqualOp()
static unary notEqualOp (const scalar opVal, const scalar tol = VSMALL) inline static
Definition at line 111 of file scalarPredicates.H.
References Foam::mag().
lessOp()
static unary lessOp (const scalar opVal) inline static
Definition at line 125 of file scalarPredicates.H.
lessEqualOp()
static unary lessEqualOp (const scalar opVal) inline static
Definition at line 135 of file scalarPredicates.H.
greaterOp()
static unary greaterOp (const scalar opVal) inline static
Definition at line 146 of file scalarPredicates.H.
greaterEqualOp()
static unary greaterEqualOp (const scalar opVal) inline static
Definition at line 156 of file scalarPredicates.H.
trueOp()
static unary trueOp () inline static
Definition at line 168 of file scalarPredicates.H.
falseOp()
static unary falseOp () inline static
Definition at line 174 of file scalarPredicates.H.
andOp()
static unary andOp (const unary & test1, const unary & test2) inline static
Definition at line 183 of file scalarPredicates.H.
Referenced by parcelSelection::calculateFilter().
orOp()
static unary orOp (const unary & test1, const unary & test2) inline static
Definition at line 192 of file scalarPredicates.H.
Referenced by parcelSelection::calculateFilter().
operation() [1/4]
static unary operation (const opType op, const scalar opVal, const scalar tol = VSMALL) static
Referenced by scalars::assign(), scalars::assign(), parcelSelection::calculateFilter(), and scalars::operation().
operation() [2/4]
Foam::predicates::scalars::unary operation (const word & opName, const scalar opVal, const scalar tol = VSMALL) inline static
Definition at line 23 of file scalarPredicatesI.H.
References scalars::operation(), and scalars::opNames.
operation() [3/4]
Foam::predicates::scalars::unary operation (const Tuple2< word, scalar > & op, const scalar tol = VSMALL) inline static
Definition at line 34 of file scalarPredicatesI.H.
References UPtrList< T >::first().
operation() [4/4]
Foam::predicates::scalars::unary operation (const std::pair< word, scalar > & op, const scalar tol = VSMALL) inline static
Definition at line 44 of file scalarPredicatesI.H.
assign() [1/2]
void assign (std::initializer_list< std::pair< word, scalar > > entries)
Definition at line 202 of file scalarPredicates.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::hasBadEntries(), scalars::operation(), and Foam::printBadEntries().
Referenced by Foam::operator>>().
assign() [2/2]
void assign (const UList< Tuple2< word, scalar > > & entries)
Definition at line 232 of file scalarPredicates.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::hasBadEntries(), scalars::operation(), and Foam::printBadEntries().
find()
Foam::label find (const scalar value, label pos = 0) const
Definition at line 262 of file scalarPredicates.C.
References Foam::pos().
rfind()
Foam::label rfind (const scalar value, label pos = -1) const
Definition at line 289 of file scalarPredicates.C.
References Foam::pos().
contains()
bool contains (const scalar value, label pos = 0) const inline
Definition at line 56 of file scalarPredicatesI.H.
References Foam::pos().
Referenced by scalars::found().
match()
bool match (const scalar value) const inline
Definition at line 66 of file scalarPredicatesI.H.
matchAny()
bool matchAny (const scalar value) const inline
Definition at line 72 of file scalarPredicatesI.H.
Referenced by scalars::operator()().
matchAll()
bool matchAll (const scalar value) const inline
Definition at line 86 of file scalarPredicatesI.H.
matching() [1/2]
Foam::labelList matching (const scalar value) const inline
Definition at line 100 of file scalarPredicatesI.H.
References List< T >::resize().
matching() [2/2]
Foam::labelList matching (const UList< scalar > & input, const bool invert = false) const inline
Definition at line 123 of file scalarPredicatesI.H.
References Foam::input(), Foam::invert(), List< T >::resize(), and UPtrList< T >::size().
operator()()
bool operator() (const scalar value) const inline
Definition at line 323 of file scalarPredicates.H.
References scalars::matchAny().
found()
bool found (const scalar value, label pos = 0) const inline
Definition at line 329 of file scalarPredicates.H.
References scalars::contains(), and Foam::pos().
Member Data Documentation
opNames
const Foam::Enum< Foam::predicates::scalars::opType > opNames static
Definition at line 91 of file scalarPredicates.H.
Referenced by Foam::hasBadEntries(), scalars::operation(), and Foam::printBadEntries().
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/predicates/scalar/scalarPredicates.H
src/OpenFOAM/primitives/predicates/scalar/scalarPredicates.C
src/OpenFOAM/primitives/predicates/scalar/scalarPredicatesI.H