OpenFOAM: wallFunctionBlenders Class Reference
wallFunctionBlenders Class Reference
The class wallFunctionBlenders is a base class that hosts common entries for various derived wall-function boundary conditions to be used in low- and high-Reynolds number applications.
#include <wallFunctionBlenders.H>
Public Member Functions
wallFunctionBlenders ()
wallFunctionBlenders (const dictionary &dict, const blenderType blender, const scalar n)
void writeEntries (Ostream &) const
Protected Types
enum blenderType {
STEPWISE , MAX , BINOMIAL , EXPONENTIAL ,
TANH
}
Protected Attributes
enum blenderType blender_
scalar n_
Static Protected Attributes
static const Enum< blenderType > blenderTypeNames
Detailed Description
The class wallFunctionBlenders is a base class that hosts common entries for various derived wall-function boundary conditions to be used in low- and high-Reynolds number applications.
Reference:
    Default model coefficients (tag:VM):
        Versteeg, H. K., & Malalasekera, W. (2011).
        An introduction to computational fluid dynamics: The finite
        volume method. Harlow: Pearson Education.
        Subsection "3.5.2 k-epsilon model".
    Binomial blending of the viscous and inertial sublayers (tag:ME):
        Menter, F., & Esch, T. (2001).
        Elements of industrial heat transfer prediction.
        In Proceedings of the 16th Brazilian Congress of Mechanical
        Engineering (COBEM), November 2001. vol. 20, p. 117-127.
    Exponential/Max blending of the viscous and inertial sublayers (tag:PH):
        Popovac, M., & Hanjalić, K. (2007).
        Compound wall treatment for RANS computation of complex
        turbulent flows and heat transfer.
        Flow, turbulence and combustion, 78(2), 177-202.
        DOI:10.1007/s10494-006-9067-x
    Tanh blending of the viscous and inertial sublayers (tag:KAS):
        Knopp, T., Alrutz, T., & Schwamborn, D. (2006).
        A grid and flow adaptive wall-function method for RANS
        turbulence modelling.
        Journal of Computational Physics, 220(1), 19-40.
        DOI:10.1016/j.jcp.2006.05.003
Usage
Example of the boundary condition specification:
<patchName>
{
    // Top-level entries
    ...
    // Optional entries
    blending        stepwise;
    n               4.0;
    // Inherited entries
    ...
}
where the entries mean:
Property Description Type Reqd Deflt
blending Viscous/inertial sublayer blending word no stepwise
n Binomial blending exponent scalar no 2.0
Options for the blending entry:
      stepwise    | Stepwise switch (discontinuous)
      max         | Maximum value switch (discontinuous)
      binomial    | Binomial blending (smooth)
      exponential | Exponential blending (smooth)
      tanh        | Tanh blending (smooth)
wherein predictions of a given quantity (e.g. nut) for viscous and inertial sublayers are blended according to the following expressions:
stepwise (default):
where
= prediction in viscous sublayer
= prediction in inertial sublayer
= estimated wall-normal height of cell centre in wall units
= estimated where sublayers intersect
max (PH:Eq. 27):
binomial (ME:Eqs. 15-16):
where
= Binomial blending exponent
exponential (PH:Eq. 32):
where (PH:Eq. 31)
= Blending expression
=
tanh (KAS:Eqs. 33-34):
where
=
=
=
G predictions for viscous and inertial sublayers are blended in a stepwise manner, and G below (i.e. in the viscous sublayer) is presumed to be zero.
Blending treatments are enabled for the following wall functions:
epsilonWallFunctionFvPatchScalarField.H
omegaWallFunctionFvPatchScalarField.H
nutkWallFunctionFvPatchScalarField.H
nutUWallFunctionFvPatchScalarField.H
Source files
wallFunctionBlenders.H
wallFunctionBlenders.C
Definition at line 249 of file wallFunctionBlenders.H.
Member Enumeration Documentation
blenderType
enum blenderType protected
Enumerator
STEPWISE
"Stepwise switch (discontinuous)"
MAX
"Maximum value switch (discontinuous)"
BINOMIAL
"Binomial blending (smooth)"
EXPONENTIAL
"Exponential blending (smooth)"
TANH
"Tanh blending (smooth)"
Definition at line 256 of file wallFunctionBlenders.H.
Constructor & Destructor Documentation
wallFunctionBlenders() [1/2]
wallFunctionBlenders ()
Definition at line 44 of file wallFunctionBlenders.C.
wallFunctionBlenders() [2/2]
wallFunctionBlenders (const dictionary & dict, const blenderType blender, const scalar n)
Definition at line 51 of file wallFunctionBlenders.C.
Member Function Documentation
writeEntries()
void writeEntries (Ostream & os) const
Definition at line 81 of file wallFunctionBlenders.C.
References os(), and Ostream::writeEntry().
Referenced by epsilonWallFunctionFvPatchScalarField::writeLocalEntries(), nutkWallFunctionFvPatchScalarField::writeLocalEntries(), nutUWallFunctionFvPatchScalarField::writeLocalEntries(), and omegaWallFunctionFvPatchScalarField::writeLocalEntries().
Member Data Documentation
blenderTypeNames
const Foam::Enum< Foam::wallFunctionBlenders::blenderType > blenderTypeNames static protected
Definition at line 266 of file wallFunctionBlenders.H.
blender_
enum blenderType blender_ protected
Definition at line 272 of file wallFunctionBlenders.H.
Referenced by nutkWallFunctionFvPatchScalarField::calcNut(), and nutUWallFunctionFvPatchScalarField::calcNut().
n_
scalar n_ protected
Definition at line 276 of file wallFunctionBlenders.H.
Referenced by nutkWallFunctionFvPatchScalarField::calcNut(), and nutUWallFunctionFvPatchScalarField::calcNut().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/derivedFvPatchFields/wallFunctions/wallFunction/wallFunctionBlenders/wallFunctionBlenders.H
src/TurbulenceModels/turbulenceModels/derivedFvPatchFields/wallFunctions/wallFunction/wallFunctionBlenders/wallFunctionBlenders.C