OpenFOAM: pressureInletOutletParSlipVelocityFvPatchVectorField Class Reference
pressureInletOutletParSlipVelocityFvPatchVectorField Class Reference
Boundary conditions » Inlet | Boundary conditions » Outlet
This velocity inlet/outlet boundary condition for pressure boundary where the pressure is specified. A zero-gradient is applied for outflow (as defined by the flux); for inflow, the velocity is obtained from the flux with the specified inlet direction.
#include <pressureInletOutletParSlipVelocityFvPatchVectorField.H>
Public Member Functions
TypeName ("pressureInletOutletParSlipVelocity")
pressureInletOutletParSlipVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
pressureInletOutletParSlipVelocityFvPatchVectorField (const pressureInletOutletParSlipVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
pressureInletOutletParSlipVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
pressureInletOutletParSlipVelocityFvPatchVectorField (const pressureInletOutletParSlipVelocityFvPatchVectorField &)
virtual tmp< fvPatchVectorField > clone () const
pressureInletOutletParSlipVelocityFvPatchVectorField (const pressureInletOutletParSlipVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
virtual bool assignable () const
const word & rhoName () const
word & rhoName ()
const word & phiName () const
word & phiName ()
virtual void updateCoeffs ()
virtual void write (Ostream &) const
virtual void operator= (const fvPatchField< vector > &pvf)
Detailed Description
This velocity inlet/outlet boundary condition for pressure boundary where the pressure is specified. A zero-gradient is applied for outflow (as defined by the flux); for inflow, the velocity is obtained from the flux with the specified inlet direction.
A slip condition is applied tangential to the patch.
Usage
Property Description Required Default value
phi flux field name no phi
rho density field name no rho
Example of the boundary condition specification:
    <patchName>
    {
        type            pressureInletOutletParSlipVelocity;
        value           uniform 0;
    }
Note
Sign conventions:
positive flux (out of domain): apply zero-gradient condition
negative flux (into of domain): derive from the flux with specified direction
See also
Foam::mixedFvPatchVectorField Foam::pressureDirectedInletOutletVelocityFvPatchVectorField
Source files
pressureInletOutletParSlipVelocityFvPatchVectorField.H
pressureInletOutletParSlipVelocityFvPatchVectorField.C
Definition at line 96 of file pressureInletOutletParSlipVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
pressureInletOutletParSlipVelocityFvPatchVectorField() [1/5]
pressureInletOutletParSlipVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Definition at line 31 of file pressureInletOutletParSlipVelocityFvPatchVectorField.C.
References Foam::Zero.
pressureInletOutletParSlipVelocityFvPatchVectorField() [2/5]
pressureInletOutletParSlipVelocityFvPatchVectorField (const pressureInletOutletParSlipVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 48 of file pressureInletOutletParSlipVelocityFvPatchVectorField.C.
pressureInletOutletParSlipVelocityFvPatchVectorField() [3/5]
pressureInletOutletParSlipVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Definition at line 63 of file pressureInletOutletParSlipVelocityFvPatchVectorField.C.
References dict, IOobjectOption::MUST_READ, fvPatchFieldBase::readDict(), and Foam::Zero.
pressureInletOutletParSlipVelocityFvPatchVectorField() [4/5]
pressureInletOutletParSlipVelocityFvPatchVectorField (const pressureInletOutletParSlipVelocityFvPatchVectorField & pivpvf)
Definition at line 83 of file pressureInletOutletParSlipVelocityFvPatchVectorField.C.
pressureInletOutletParSlipVelocityFvPatchVectorField() [5/5]
pressureInletOutletParSlipVelocityFvPatchVectorField (const pressureInletOutletParSlipVelocityFvPatchVectorField & pivpvf, const DimensionedField< vector, volMesh > & iF)
Definition at line 95 of file pressureInletOutletParSlipVelocityFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("pressureInletOutletParSlipVelocity")
clone() [1/2]
virtual tmp< fvPatchVectorField > clone () const inline virtual
Definition at line 150 of file pressureInletOutletParSlipVelocityFvPatchVectorField.H.
clone() [2/2]
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Definition at line 169 of file pressureInletOutletParSlipVelocityFvPatchVectorField.H.
assignable()
virtual bool assignable () const inline virtual
Definition at line 188 of file pressureInletOutletParSlipVelocityFvPatchVectorField.H.
rhoName() [1/2]
const word & rhoName () const inline
Definition at line 194 of file pressureInletOutletParSlipVelocityFvPatchVectorField.H.
rhoName() [2/2]
word & rhoName () inline
Definition at line 200 of file pressureInletOutletParSlipVelocityFvPatchVectorField.H.
phiName() [1/2]
const word & phiName () const inline
Definition at line 206 of file pressureInletOutletParSlipVelocityFvPatchVectorField.H.
phiName() [2/2]
word & phiName () inline
Definition at line 212 of file pressureInletOutletParSlipVelocityFvPatchVectorField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 110 of file pressureInletOutletParSlipVelocityFvPatchVectorField.C.
References Foam::dimMass, Foam::dimTime, Foam::dimVolume, Foam::exit(), Foam::FatalError, FatalErrorInFunction, n, Foam::neg(), and Foam::nl.
write()
void write (Ostream & os) const virtual
Definition at line 152 of file pressureInletOutletParSlipVelocityFvPatchVectorField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntryIfDifferent(), and fvPatchField< Type >::writeValueEntry().
operator=()
void operator= (const fvPatchField< vector > & pvf) virtual
Definition at line 166 of file pressureInletOutletParSlipVelocityFvPatchVectorField.C.
References fvPatchField< Type >::operator=().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/pressureInletOutletParSlipVelocity/pressureInletOutletParSlipVelocityFvPatchVectorField.H
src/finiteVolume/fields/fvPatchFields/derived/pressureInletOutletParSlipVelocity/pressureInletOutletParSlipVelocityFvPatchVectorField.C