OpenFOAM: skewCorrectedEdgeInterpolation< Type > Class Template Reference
skewCorrectedEdgeInterpolation< Type > Class Template Reference
Linear/upwind blended differencing scheme.
#include <skewCorrectedEdgeInterpolation.H>
Public Member Functions
TypeName ("skewCorrected")
skewCorrectedEdgeInterpolation (const faMesh &mesh, Istream &is)
skewCorrectedEdgeInterpolation (const faMesh &mesh, const edgeScalarField &faceFlux, Istream &is)
skewCorrectedEdgeInterpolation (const skewCorrectedEdgeInterpolation &)=delete
void operator= (const skewCorrectedEdgeInterpolation &)=delete
virtual tmp< edgeScalarField > weights (const GeometricField< Type, faPatchField, areaMesh > &vf) const
virtual bool corrected () const
tmp< GeometricField< Type, faePatchField, edgeMesh > > skewCorrection (const GeometricField< Type, faPatchField, areaMesh > &vf) const
virtual tmp< GeometricField< Type, faePatchField, edgeMesh > > correction (const GeometricField< Type, faPatchField, areaMesh > &vf) const
Public Member Functions inherited from edgeInterpolationScheme< Type >
declareRunTimeSelectionTable (tmp, edgeInterpolationScheme, Mesh,(const faMesh &mesh, Istream &schemeData),(mesh, schemeData))
declareRunTimeSelectionTable (tmp, edgeInterpolationScheme, MeshFlux,(const faMesh &mesh, const edgeScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
edgeInterpolationScheme (const faMesh &mesh)
virtual ~edgeInterpolationScheme ()
const faMesh & mesh () const
virtual tmp< GeometricField< Type, faePatchField, edgeMesh > > interpolate (const GeometricField< Type, faPatchField, areaMesh > &) const
virtual tmp< GeometricField< Type, faePatchField, edgeMesh > > euclidianInterpolate (const GeometricField< Type, faPatchField, areaMesh > &) const
tmp< GeometricField< Type, faePatchField, edgeMesh > > interpolate (const tmp< GeometricField< Type, faPatchField, areaMesh > > &) const
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Additional Inherited Members
Static Public Member Functions inherited from edgeInterpolationScheme< Type >
static tmp< edgeInterpolationScheme< Type > > New (const faMesh &mesh, Istream &schemeData)
static tmp< edgeInterpolationScheme< Type > > New (const faMesh &mesh, const edgeScalarField &faceFlux, Istream &schemeData)
static tmp< GeometricField< Type, faePatchField, edgeMesh > > interpolate (const GeometricField< Type, faPatchField, areaMesh > &, const tmp< edgeScalarField > &, const tmp< edgeScalarField > &)
static tmp< GeometricField< Type, faePatchField, edgeMesh > > interpolate (const GeometricField< Type, faPatchField, areaMesh > &, const tmp< edgeScalarField > &)
static tmp< GeometricField< Type, faePatchField, edgeMesh > > euclidianInterpolate (const GeometricField< Type, faPatchField, areaMesh > &, const tmp< edgeScalarField > &)
Detailed Description
template<class Type>
class Foam::skewCorrectedEdgeInterpolation< Type >
Linear/upwind blended differencing scheme.
Source files
skewCorrectedEdgeInterpolation.H
skewCorrectedEdgeInterpolationMake.C
Definition at line 52 of file skewCorrectedEdgeInterpolation.H.
Constructor & Destructor Documentation
skewCorrectedEdgeInterpolation() [1/3]
template<class Type > skewCorrectedEdgeInterpolation (const faMesh & mesh, Istream & is) inline
Definition at line 70 of file skewCorrectedEdgeInterpolation.H.
skewCorrectedEdgeInterpolation() [2/3]
template<class Type > skewCorrectedEdgeInterpolation (const faMesh & mesh, const edgeScalarField & faceFlux, Istream & is) inline
Definition at line 80 of file skewCorrectedEdgeInterpolation.H.
skewCorrectedEdgeInterpolation() [3/3]
template<class Type > skewCorrectedEdgeInterpolation (const skewCorrectedEdgeInterpolation< Type > &) delete
Member Function Documentation
TypeName()
template<class Type > TypeName ("skewCorrected")
operator=()
template<class Type > void operator= (const skewCorrectedEdgeInterpolation< Type > &) delete
weights()
template<class Type > virtual tmp< edgeScalarField > weights (const GeometricField< Type, faPatchField, areaMesh > & vf) const inline virtual
Implements edgeInterpolationScheme< Type >.
Definition at line 105 of file skewCorrectedEdgeInterpolation.H.
corrected()
template<class Type > virtual bool corrected () const inline virtual
Reimplemented from edgeInterpolationScheme< Type >.
Definition at line 114 of file skewCorrectedEdgeInterpolation.H.
References edgeInterpolationScheme< Type >::mesh(), and Foam::skew().
Referenced by skewCorrectedEdgeInterpolation< Type >::correction().
skewCorrection()
template<class Type > tmp< GeometricField< Type, faePatchField, edgeMesh > > skewCorrection (const GeometricField< Type, faPatchField, areaMesh > & vf) const inline
Definition at line 121 of file skewCorrectedEdgeInterpolation.H.
References edgeInterpolationScheme< Type >::interpolate(), edgeInterpolationScheme< Type >::mesh(), Foam::type(), and Foam::Zero.
Referenced by skewCorrectedEdgeInterpolation< Type >::correction().
correction()
template<class Type > virtual tmp< GeometricField< Type, faePatchField, edgeMesh > > correction (const GeometricField< Type, faPatchField, areaMesh > & vf) const inline virtual
Reimplemented from edgeInterpolationScheme< Type >.
Definition at line 173 of file skewCorrectedEdgeInterpolation.H.
References skewCorrectedEdgeInterpolation< Type >::corrected(), edgeInterpolationScheme< Type >::mesh(), Foam::skew(), and skewCorrectedEdgeInterpolation< Type >::skewCorrection().
The documentation for this class was generated from the following file:
src/finiteArea/interpolation/edgeInterpolation/schemes/skewCorrected/skewCorrectedEdgeInterpolation.H