OpenFOAM: directoryIterator Class Reference
directoryIterator Class Reference
Public Member Functions
directoryIterator (const std::string &dirName, bool allowHidden=false)
~directoryIterator ()
bool exists () const noexcept
bool good () const noexcept
void close ()
const std::string & val () const noexcept
bool next ()
operator bool () const noexcept
const std::string & operator* () const noexcept
directoryIterator & operator++ ()
Detailed Description
Definition at line 162 of file POSIX.C.
Constructor & Destructor Documentation
directoryIterator()
directoryIterator (const std::string & dirName, bool allowHidden = false) inline
Definition at line 188 of file POSIX.C.
References UPtrList< T >::empty(), and directoryIterator::next().
~directoryIterator()
~directoryIterator () inline
Definition at line 205 of file POSIX.C.
References directoryIterator::close().
Member Function Documentation
exists()
bool exists () const inline noexcept
Definition at line 214 of file POSIX.C.
good()
bool good () const inline noexcept
Definition at line 220 of file POSIX.C.
Referenced by directoryIterator::operator bool().
close()
void close () inline
Definition at line 226 of file POSIX.C.
Referenced by directoryIterator::next(), and directoryIterator::~directoryIterator().
val()
const std::string & val () const inline noexcept
Definition at line 236 of file POSIX.C.
Referenced by directoryIterator::operator*().
next()
bool next () inline
Definition at line 244 of file POSIX.C.
References directoryIterator::close().
Referenced by directoryIterator::directoryIterator(), and directoryIterator::operator++().
operator bool()
operator bool () const inline noexcept
Definition at line 266 of file POSIX.C.
References directoryIterator::good().
operator*()
const std::string & operator* () const inline noexcept
Definition at line 272 of file POSIX.C.
References directoryIterator::val().
operator++()
directoryIterator & operator++ () inline
Definition at line 278 of file POSIX.C.
References directoryIterator::next().
The documentation for this class was generated from the following file:
src/OSspecific/POSIX/POSIX.C