OpenFOAM: Tatsumoto Class Reference
Tatsumoto Class Reference
A critical heat flux (CHF) sub-cooling correlation model.
#include <Tatsumoto.H>
Public Member Functions
TypeName ("Tatsumoto")
Tatsumoto (const dictionary &dict)
virtual ~Tatsumoto ()=default
virtual tmp< scalarField > CHFSubCool (const phaseModel &liquid, const phaseModel &vapor, const label patchi, const scalarField &Tl, const scalarField &Tsatw, const scalarField &L) const
virtual void write (Ostream &os) const
Public Member Functions inherited from CHFSubCoolModel
TypeName ("CHFSubCoolModel")
declareRunTimeSelectionTable (autoPtr, CHFSubCoolModel, dictionary,(const dictionary &dict),(dict))
CHFSubCoolModel ()=default
virtual ~CHFSubCoolModel ()=default
Additional Inherited Members
Static Public Member Functions inherited from CHFSubCoolModel
static autoPtr< CHFSubCoolModel > New (const dictionary &dict)
Detailed Description
A critical heat flux (CHF) sub-cooling correlation model.
Usage
Example of the model specification:
CHFSubCoolModel
{
    // Mandatory entries
    type            Tatsumoto;
    // Optional entries
    K               <scalar>;
}
where the entries mean:
Property Description Type Reqd Deflt
type Type name: Tatsumoto word yes -
K Model coefficient scalar no 0.23
Source files
Tatsumoto.H
Tatsumoto.C
Definition at line 88 of file Tatsumoto.H.
Constructor & Destructor Documentation
Tatsumoto()
Tatsumoto (const dictionary & dict)
Definition at line 48 of file Tatsumoto.C.
~Tatsumoto()
virtual ~Tatsumoto () virtual default
Member Function Documentation
TypeName()
TypeName ("Tatsumoto")
CHFSubCool()
Foam::tmp< Foam::scalarField > CHFSubCool (const phaseModel & liquid, const phaseModel & vapor, const label patchi, const scalarField & Tl, const scalarField & Tsatw, const scalarField & L) const virtual
Implements CHFSubCoolModel.
Definition at line 61 of file Tatsumoto.C.
References cells, Cp, liquid::Cp(), L, Foam::max(), Foam::pow(), and tCp.
write()
void write (Ostream & os) const virtual
Reimplemented from CHFSubCoolModel.
Definition at line 88 of file Tatsumoto.C.
References os(), and CHFSubCoolModel::write().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/wallBoilingSubModels/CHFSubCoolModels/Tatsumoto/Tatsumoto.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/wallBoilingSubModels/CHFSubCoolModels/Tatsumoto/Tatsumoto.C