OpenFOAM: InputValueMapper< Type > Class Template Reference
InputValueMapper< Type > Class Template Reference
Function1 wrapper that maps the input value prior to it being used by another Function1.
#include <InputValueMapper.H>
Public Types
enum class mappingMode { NONE , FUNCTION1 , MINMAX }
Public Types inherited from Function1< Type >
typedef Type returnType
Public Member Functions
TypeName ("inputValueMapper")
void operator= (const InputValueMapper< Type > &)=delete
InputValueMapper (const word &entryName, const dictionary &dict, const objectRegistry *obrPtr=nullptr)
InputValueMapper (const InputValueMapper< Type > &rhs)
virtual tmp< Function1< Type > > clone () const
virtual ~InputValueMapper ()=default
virtual Type value (const scalar t) const
virtual Type integrate (const scalar x1, const scalar x2) const
virtual void writeData (Ostream &os) const
virtual void writeEntries (Ostream &os) const
Public Member Functions inherited from Function1< Type >
TypeName ("Function1") declareRunTimeSelectionTable(autoPtr
Function1 (const word &entryName, const objectRegistry *obrPtr=nullptr)
Function1 (const word &entryName, const dictionary &dict, const objectRegistry *obrPtr=nullptr)
Function1 (const Function1< Type > &rhs)
virtual ~Function1 ()=default
virtual bool constant () const
virtual bool good () const
virtual tmp< Field< Type > > value (const scalarField &x) const
virtual tmp< Field< Type > > integrate (const scalarField &x1, const scalarField &x2) const
Public Member Functions inherited from function1Base
function1Base (const word &entryName, const objectRegistry *obrPtr=nullptr)
function1Base (const word &entryName, const dictionary &dict, const objectRegistry *obrPtr=nullptr)
function1Base (const function1Base &rhs)
virtual ~function1Base ()
const word & name () const noexcept
const objectRegistry * whichDb () const noexcept
void resetDb (const objectRegistry *obrPtr=nullptr) noexcept
void resetDb (const objectRegistry &db) noexcept
const objectRegistry & obr () const
bool isTime () const noexcept
const Time & time () const
template<class MeshType >
const MeshType & mesh (const word &regionName=word::null) const
virtual void userTimeToTime (const Time &t)
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Static Public Attributes
static const Enum< mappingMode > mappingModeNames_
Additional Inherited Members
Static Public Member Functions inherited from Function1< Type >
static autoPtr< Function1< Type > > New (const word &entryName, const dictionary &dict, const word &redirectType, const objectRegistry *obrPtr=nullptr, const bool mandatory=true)
static autoPtr< Function1< Type > > NewCompat (const word &entryName, std::initializer_list< std::pair< const char *, int > > compat, const dictionary &dict, const word &redirectType=word::null, const objectRegistry *obrPtr=nullptr, const bool mandatory=true)
static autoPtr< Function1< Type > > New (const word &entryName, const dictionary &dict, const objectRegistry *obrPtr=nullptr, const bool mandatory=true)
static autoPtr< Function1< Type > > NewIfPresent (const word &entryName, const dictionary &dict, const word &redirectType, const objectRegistry *obrPtr=nullptr)
static autoPtr< Function1< Type > > NewIfPresent (const word &entryName, const dictionary &dict, const objectRegistry *obrPtr=nullptr)
static refPtr< Function1< Type > > New (HashPtrTable< Function1< Type > > &cache, const word &entryName, const dictionary &dict, enum keyType::option matchOpt=keyType::LITERAL, const objectRegistry *obrPtr=nullptr, const bool mandatory=true)
Public Attributes inherited from Function1< Type >
Function1
dictionary
const word & entryName
const word const dictionary & dict
const word const dictionary const objectRegistry * obrPtr
const word const dictionary const objectRegistry entryName
const word const dictionary const objectRegistry dict
const word const dictionary const objectRegistry obrPtr
Protected Member Functions inherited from Function1< Type >
void operator= (const Function1< Type > &)=delete
Protected Member Functions inherited from function1Base
void operator= (const function1Base &)=delete
Protected Attributes inherited from function1Base
const word name_
const objectRegistry * obrPtr_
Detailed Description
template<class Type>
class Foam::Function1Types::InputValueMapper< Type >
Function1 wrapper that maps the input value prior to it being used by another Function1.
Example usage for limiting a polynomial:
    <entryName>
    {
        type            inputValueMapper;
        mode            minMax;
        min             0.4;
        max             1.4;
        value polynomial
        (
            (5 1)
            (-2 2)
            (-2 3)
            (1 4)
        );
    }
Here the return value will be:
poly(0.4) for x <= 0.4;
poly(1.4) for x >= 1.4; and
poly(x) for 0.4 < x < 1.4.
Example usage for supplying a patch mass flux for a table lookup:
    <entryName>
    {
        type            inputValueMapper;
        mode            function;
        function
        {
            type            functionObjectValue;
            functionObject  surfaceFieldValue1;
            functionObjectResult sum(outlet,phi);
        }
        value
        {
            type        table;
            file        "<system>/fanCurve.txt";
        }
    }
Where:
Property Description Required
mode Mapping mode (see below) yes
function Mapping Function1 no*
min Minimum input value no*
max Maximum input value no*
value Function of type Function1<Type> yes
Mapping modes include
none : the input value is simply passed to the 'value' Function1
function : the input value is passed through the 'function' Function1 before being passed to the 'value' Function1
minMax : limits the input value to 'min' and 'max' values before being passed to the 'value' Function1
Note
Replaces the LimitRange Function1 (v2106 and earlier)
Source files
InputValueMapper.H
InputValueMapper.C
InputValueMapperI.H
Definition at line 144 of file InputValueMapper.H.
Member Enumeration Documentation
mappingMode
template<class Type > enum class mappingMode strong
Enumerator
NONE
FUNCTION1
MINMAX
Definition at line 153 of file InputValueMapper.H.
Constructor & Destructor Documentation
InputValueMapper() [1/2]
template<class Type > InputValueMapper (const word & entryName, const dictionary & dict, const objectRegistry * obrPtr = nullptr)
Definition at line 84 of file InputValueMapper.C.
References Function1< Type >::dict.
InputValueMapper() [2/2]
template<class Type > InputValueMapper (const InputValueMapper< Type > & rhs) explicit
Definition at line 103 of file InputValueMapper.C.
~InputValueMapper()
template<class Type > virtual ~InputValueMapper () virtual default
Member Function Documentation
TypeName()
template<class Type > TypeName ("inputValueMapper")
operator=()
template<class Type > void operator= (const InputValueMapper< Type > &) delete
clone()
template<class Type > virtual tmp< Function1< Type > > clone () const inline virtual
Implements Function1< Type >.
Definition at line 224 of file InputValueMapper.H.
value()
template<class Type > Type value (const scalar t) const inline virtual
Reimplemented from Function1< Type >.
Definition at line 26 of file InputValueMapperI.H.
References Foam::abort(), Foam::clamp(), Foam::FatalError, and FatalErrorInFunction.
integrate()
template<class Type > Type integrate (const scalar x1, const scalar x2) const inline virtual
Reimplemented from Function1< Type >.
Definition at line 61 of file InputValueMapperI.H.
References Foam::abort(), Foam::clamp(), Foam::FatalError, FatalErrorInFunction, Foam::max(), and Foam::min().
writeData()
template<class Type > void writeData (Ostream & os) const virtual
Reimplemented from Function1< Type >.
Definition at line 160 of file InputValueMapper.C.
References Foam::name(), os(), and Function1< Type >::writeData().
writeEntries()
template<class Type > void writeEntries (Ostream & os) const virtual
Reimplemented from Function1< Type >.
Definition at line 120 of file InputValueMapper.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and os().
Member Data Documentation
mappingModeNames_
template<class Type > const Foam::Enum< typename Foam::Function1Types::InputValueMapper< Type >::mappingMode > mappingModeNames_ static
Definition at line 161 of file InputValueMapper.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/functions/Function1/InputValueMapper/InputValueMapper.H
src/OpenFOAM/primitives/functions/Function1/InputValueMapper/InputValueMapper.C
src/OpenFOAM/primitives/functions/Function1/InputValueMapper/InputValueMapperI.H