OpenFOAM: anisotropicFilter Class Reference
anisotropicFilter Class Reference
anisotropic filter
#include <anisotropicFilter.H>
Public Member Functions
TypeName ("anisotropic")
anisotropicFilter (const fvMesh &mesh, scalar widthCoeff)
anisotropicFilter (const fvMesh &mesh, const dictionary &)
virtual ~anisotropicFilter ()=default
virtual void read (const dictionary &)
virtual tmp< volScalarField > operator() (const tmp< volScalarField > &) const
virtual tmp< volVectorField > operator() (const tmp< volVectorField > &) const
virtual tmp< volSymmTensorField > operator() (const tmp< volSymmTensorField > &) const
virtual tmp< volTensorField > operator() (const tmp< volTensorField > &) const
Public Member Functions inherited from LESfilter
TypeName ("LESfilter")
declareRunTimeSelectionTable (autoPtr, LESfilter, dictionary,(const fvMesh &mesh, const dictionary &LESfilterDict),(mesh, LESfilterDict))
LESfilter (const fvMesh &mesh)
virtual ~LESfilter ()=default
const fvMesh & mesh () const
Additional Inherited Members
Static Public Member Functions inherited from LESfilter
static autoPtr< LESfilter > New (const fvMesh &, const dictionary &, const word &filterDictName="filter")
Protected Member Functions inherited from LESfilter
template<class GeoFieldType >
void correctBoundaryConditions (const tmp< GeoFieldType > &tgf) const
Detailed Description
anisotropic filter
Kernel                 as filter          as Test filter with ratio 2
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Box filter:            g = delta2/24  ->  g = delta2/6
Spherical box filter:  g = delta2/64  ->  g = delta2/16
Gaussian filter:       g = delta2/24  ->  g = delta2/6
Source files
anisotropicFilter.H
anisotropicFilter.C
Definition at line 55 of file anisotropicFilter.H.
Constructor & Destructor Documentation
anisotropicFilter() [1/2]
anisotropicFilter (const fvMesh & mesh, scalar widthCoeff)
Definition at line 38 of file anisotropicFilter.C.
References Foam::dimLength, Foam::mag(), LESfilter::mesh(), VectorSpace< Form, Cmpt, Ncmpts >::nComponents, GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef(), Field< Type >::replace(), Foam::sqr(), and Foam::fvc::surfaceSum().
anisotropicFilter() [2/2]
anisotropicFilter (const fvMesh & mesh, const dictionary & bd)
Definition at line 74 of file anisotropicFilter.C.
References Foam::mag(), LESfilter::mesh(), VectorSpace< Form, Cmpt, Ncmpts >::nComponents, GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef(), Field< Type >::replace(), Foam::sqr(), and Foam::fvc::surfaceSum().
~anisotropicFilter()
virtual ~anisotropicFilter () virtual default
Member Function Documentation
TypeName()
TypeName ("anisotropic")
read()
void read (const dictionary & bd) virtual
Implements LESfilter.
Definition at line 115 of file anisotropicFilter.C.
References Foam::type().
operator()() [1/4]
Foam::tmp< Foam::volScalarField > operator() (const tmp< volScalarField > & unFilteredField) const virtual
Implements LESfilter.
Definition at line 123 of file anisotropicFilter.C.
References PtrList< T >::clear(), correctBoundaryConditions(), mesh, Foam::fvc::snGrad(), and Foam::fvc::surfaceIntegrate().
operator()() [2/4]
Foam::tmp< Foam::volVectorField > operator() (const tmp< volVectorField > & unFilteredField) const virtual
Implements LESfilter.
Definition at line 147 of file anisotropicFilter.C.
References PtrList< T >::clear(), correctBoundaryConditions(), mesh, Foam::fvc::snGrad(), and Foam::fvc::surfaceIntegrate().
operator()() [3/4]
Foam::tmp< Foam::volSymmTensorField > operator() (const tmp< volSymmTensorField > & unFilteredField) const virtual
Implements LESfilter.
Definition at line 171 of file anisotropicFilter.C.
References PtrList< T >::clear(), Foam::component(), correctBoundaryConditions(), mesh, VectorSpace< Form, Cmpt, Ncmpts >::nComponents, and timeName.
operator()() [4/4]
Foam::tmp< Foam::volTensorField > operator() (const tmp< volTensorField > & unFilteredField) const virtual
Implements LESfilter.
Definition at line 207 of file anisotropicFilter.C.
References PtrList< T >::clear(), Foam::component(), correctBoundaryConditions(), mesh, VectorSpace< Form, Cmpt, Mrows *Ncols >::nComponents, and timeName.
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/LES/LESfilters/anisotropicFilter/anisotropicFilter.H
src/TurbulenceModels/turbulenceModels/LES/LESfilters/anisotropicFilter/anisotropicFilter.C