OpenFOAM: faMeshDistributor Class Reference
faMeshDistributor Class Reference
Holds a reference to the original mesh (the baseMesh) and optionally to a subset of that mesh (the subMesh) with mapping lists for points, faces, and cells.
#include <faMeshDistributor.H>
Public Member Functions
faMeshDistributor (const faMeshDistributor &)=delete
void operator= (const faMeshDistributor &)=delete
faMeshDistributor (const faMesh &srcMesh, const faMesh &tgtMesh, const mapDistributePolyMesh &faDistMap, const bool isWriteProc)
faMeshDistributor (const faMesh &srcMesh, const faMesh &tgtMesh, const mapDistributePolyMesh &faDistMap, refPtr< fileOperation > &writeHandler)
label distributeAllFields (const IOobjectList &objects, const wordRes &selectedFields=wordRes()) const
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > distributeField (const GeometricField< Type, faPatchField, areaMesh > &fld) const
template<class Type >
tmp< GeometricField< Type, faePatchField, edgeMesh > > distributeField (const GeometricField< Type, faePatchField, edgeMesh > &fld) const
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > distributeAreaField (const IOobject &fieldObject) const
template<class Type >
tmp< GeometricField< Type, faePatchField, edgeMesh > > distributeEdgeField (const IOobject &fieldObject) const
template<class Type >
label distributeAreaFields (const IOobjectList &objects, const wordRes &selectedFields=wordRes()) const
template<class Type >
label distributeEdgeFields (const IOobjectList &objects, const wordRes &selectedFields=wordRes()) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::faPatchField, Foam::areaMesh > > distributeField (const GeometricField< Type, faPatchField, areaMesh > &fld) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::faePatchField, Foam::edgeMesh > > distributeField (const GeometricField< Type, faePatchField, edgeMesh > &fld) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::faPatchField, Foam::areaMesh > > distributeAreaField (const IOobject &fieldObject) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::faePatchField, Foam::edgeMesh > > distributeEdgeField (const IOobject &fieldObject) const
template<class Type >
Foam::label distributeAreaFields (const IOobjectList &objects, const wordRes &selectedFields) const
template<class Type >
Foam::label distributeEdgeFields (const IOobjectList &objects, const wordRes &selectedFields) const
Static Public Member Functions
static mapDistributePolyMesh distribute (const faMesh &oldMesh, const mapDistributePolyMesh &distMap, const polyMesh &tgtPolyMesh, autoPtr< faMesh > &newMeshPtr)
static mapDistributePolyMesh distribute (const faMesh &oldMesh, const mapDistributePolyMesh &distMap, autoPtr< faMesh > &newMeshPtr)
Static Public Attributes
static int verbose_ = 0
Detailed Description
Holds a reference to the original mesh (the baseMesh) and optionally to a subset of that mesh (the subMesh) with mapping lists for points, faces, and cells.
Source files
faMeshDistributor.H
faMeshDistributor.C
faMeshDistributorNew.C
faMeshDistributorTemplates.C
Definition at line 57 of file faMeshDistributor.H.
Constructor & Destructor Documentation
faMeshDistributor() [1/3]
faMeshDistributor (const faMeshDistributor &) delete
faMeshDistributor() [2/3]
faMeshDistributor (const faMesh & srcMesh, const faMesh & tgtMesh, const mapDistributePolyMesh & faDistMap, const bool isWriteProc)
Definition at line 185 of file faMeshDistributor.C.
faMeshDistributor() [3/3]
faMeshDistributor (const faMesh & srcMesh, const faMesh & tgtMesh, const mapDistributePolyMesh & faDistMap, refPtr< fileOperation > & writeHandler)
Definition at line 206 of file faMeshDistributor.C.
Member Function Documentation
operator=()
void operator= (const faMeshDistributor &) delete
distribute() [1/2]
Foam::mapDistributePolyMesh distribute (const faMesh & oldMesh, const mapDistributePolyMesh & distMap, const polyMesh & tgtPolyMesh, autoPtr< faMesh > & newMeshPtr) static
{ // Transcribe from patchMapInfo gathered earlier. // - transform Map of labelHashSet to labelListList
labelListList sendToRemote(Pstream::nProcs(faPatchMap.comm()));
forAllConstIters(patchMapInfo, iter) { const label proci = iter.key(); sendToRemote[proci] = iter.val().sortedToc(); }
auto& patchSubMap = faPatchMap.subMap(); auto& patchCnstrMap = faPatchMap.constructMap();
patchSubMap = sendToRemote; patchCnstrMap.resize(patchSubMap.size());
// Change sendToRemote into recv-from-remote by using // all-to-all exchange
Pstream::exchange<labelList, label> (sendToRemote, patchCnstrMap, UPstream::msgType(), faPatchMap.comm()); }
Parameters
tgtPolyMesh From polyMesh
Definition at line 32 of file faMeshDistributorNew.C.
References Foam::abort(), add(), Pstream::broadcast(), PtrList< T >::clone(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::ListOps::findIndices(), Pair< T >::first(), forAll, Foam::identity(), io(), UPtrList< T >::last(), Foam::mag(), UPstream::msgType(), UPstream::myProcNo(), UPstream::nonBlocking, nPatches, UPstream::nProcs(), UPstream::nRequests(), UPstream::parRun(), IOobjectOption::READ_IF_PRESENT, mapDistributeBase::renumberMap(), PtrList< T >::resize(), Pair< T >::second(), PtrList< T >::set(), UPtrList< T >::size(), Foam::sortedOrder(), UPstream::waitRequests(), x, y, and Foam::Zero.
Referenced by faMeshDistributor::distribute().
distribute() [2/2]
Foam::mapDistributePolyMesh distribute (const faMesh & oldMesh, const mapDistributePolyMesh & distMap, autoPtr< faMesh > & newMeshPtr) static
Parameters
newMeshPtr From polyMesh
Definition at line 893 of file faMeshDistributorNew.C.
References faMeshDistributor::distribute().
distributeAllFields()
Foam::label distributeAllFields (const IOobjectList & objects, const wordRes & selectedFields = wordRes()) const
Definition at line 229 of file faMeshDistributor.C.
distributeField() [1/4]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > distributeField (const GeometricField< Type, faPatchField, areaMesh > & fld) const
distributeField() [2/4]
template<class Type > tmp< GeometricField< Type, faePatchField, edgeMesh > > distributeField (const GeometricField< Type, faePatchField, edgeMesh > & fld) const
distributeAreaField() [1/2]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > distributeAreaField (const IOobject & fieldObject) const
distributeEdgeField() [1/2]
template<class Type > tmp< GeometricField< Type, faePatchField, edgeMesh > > distributeEdgeField (const IOobject & fieldObject) const
distributeAreaFields() [1/2]
template<class Type > label distributeAreaFields (const IOobjectList & objects, const wordRes & selectedFields = wordRes()) const
distributeEdgeFields() [1/2]
template<class Type > label distributeEdgeFields (const IOobjectList & objects, const wordRes & selectedFields = wordRes()) const
distributeField() [3/4]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::faPatchField, Foam::areaMesh > > distributeField (const GeometricField< Type, faPatchField, areaMesh > & fld) const
Definition at line 40 of file faMeshDistributorTemplates.C.
References UPtrList< T >::empty(), fld(), forAll, Foam::New(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, UList< label >::null(), PtrList< T >::set(), UPtrList< T >::size(), and UPtrList< T >::test().
distributeField() [4/4]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::faePatchField, Foam::edgeMesh > > distributeField (const GeometricField< Type, faePatchField, edgeMesh > & fld) const
Definition at line 149 of file faMeshDistributorTemplates.C.
References fld(), forAll, Foam::New(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, UList< label >::null(), and PtrList< T >::set().
distributeAreaField() [2/2]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::faPatchField, Foam::areaMesh > > distributeAreaField (const IOobject & fieldObject) const
Definition at line 254 of file faMeshDistributorTemplates.C.
References fld().
distributeEdgeField() [2/2]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::faePatchField, Foam::edgeMesh > > distributeEdgeField (const IOobject & fieldObject) const
Definition at line 273 of file faMeshDistributorTemplates.C.
References fld().
distributeAreaFields() [2/2]
template<class Type > Foam::label distributeAreaFields (const IOobjectList & objects, const wordRes & selectedFields) const
Definition at line 291 of file faMeshDistributorTemplates.C.
References UPstream::commWorld(), UPtrList< T >::empty(), Foam::endl(), fileOperation::fileHandler(), Foam::fileHandler, Foam::Info, io(), IOobject::name(), and Foam::nl.
distributeEdgeFields() [2/2]
template<class Type > Foam::label distributeEdgeFields (const IOobjectList & objects, const wordRes & selectedFields) const
Definition at line 349 of file faMeshDistributorTemplates.C.
References UPstream::commWorld(), UPtrList< T >::empty(), Foam::endl(), fileOperation::fileHandler(), Foam::fileHandler, Foam::Info, io(), IOobject::name(), and Foam::nl.
Member Data Documentation
verbose_
int verbose_ = 0 static
Definition at line 111 of file faMeshDistributor.H.
The documentation for this class was generated from the following files:
src/finiteArea/distributed/faMeshDistributor.H
src/finiteArea/distributed/faMeshDistributor.C
src/finiteArea/distributed/faMeshDistributorNew.C
src/finiteArea/distributed/faMeshDistributorTemplates.C