OpenFOAM: plenumPressureFvPatchScalarField Class Reference
plenumPressureFvPatchScalarField Class Reference
Boundary conditions » Inlet
This boundary condition provides a plenum pressure inlet condition. This condition creates a zero-dimensional model of an enclosed volume of gas upstream of the inlet. The pressure that the boundary condition exerts on the inlet boundary is dependent on the thermodynamic state of the upstream volume. The upstream plenum density and temperature are time-stepped along with the rest of the simulation, and momentum is neglected. The plenum is supplied with a user specified mass flow and temperature.
#include <plenumPressureFvPatchScalarField.H>
Public Member Functions
TypeName ("plenumPressure")
plenumPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
plenumPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
plenumPressureFvPatchScalarField (const plenumPressureFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
plenumPressureFvPatchScalarField (const plenumPressureFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
plenumPressureFvPatchScalarField (const plenumPressureFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
This boundary condition provides a plenum pressure inlet condition. This condition creates a zero-dimensional model of an enclosed volume of gas upstream of the inlet. The pressure that the boundary condition exerts on the inlet boundary is dependent on the thermodynamic state of the upstream volume. The upstream plenum density and temperature are time-stepped along with the rest of the simulation, and momentum is neglected. The plenum is supplied with a user specified mass flow and temperature.
The result is a boundary condition which blends between a pressure inlet condition condition and a fixed mass flow. The smaller the plenum volume, the quicker the pressure responds to a deviation from the supply mass flow, and the closer the model approximates a fixed mass flow. As the plenum size increases, the model becomes more similar to a specified pressure.
The expansion from the plenum to the inlet boundary is controlled by an area ratio and a discharge coefficient. The area ratio can be used to represent further acceleration between a sub-grid blockage such as fins. The discharge coefficient represents a fractional deviation from an ideal expansion process.
This condition is useful for simulating unsteady internal flow problems for which both a mass flow boundary is unrealistic, and a pressure boundary is susceptible to flow reversal. It was developed for use in simulating confined combustion.
Reference:
    Bainbridge, W. (2013).
    The Numerical Simulation of Oscillations in Gas Turbine Combustion
    Chambers,
    PhD Thesis,
    Chapter 4, Section 4.3.1.2, 77-80.
Usage
Property Description Required Default value
gamma ratio of specific heats yes none
R specific gas constant yes none
supplyMassFlowRate flow rate into the plenum yes none
supplyTotalTemperature temperature into the plenum yes none
plenumVolume plenum volume yes none
plenumDensity plenum density yes none
plenumTemperature plenum temperature yes none
U velocity field name no U
phi flux field name no phi
rho inlet density no none
inletAreaRatio inlet open fraction yes none
inletDischargeCoefficient inlet loss coefficient yes none
timeScale relaxation time scale yes none
Example of the boundary condition specification:
    <patchName>
    {
        type            plenumPressure;
        gamma           1.4;
        R               287.04;
        supplyMassFlowRate 0.0001;
        supplyTotalTemperature 300;
        plenumVolume    0.000125;
        plenumDensity   1.1613;
        plenumTemperature 300;
        inletAreaRatio  1.0;
        inletDischargeCoefficient 0.8;
        timeScale       1e-4;
        value           uniform 1e5;
    }
Source files
plenumPressureFvPatchScalarField.H
plenumPressureFvPatchScalarField.C
Definition at line 189 of file plenumPressureFvPatchScalarField.H.
Constructor & Destructor Documentation
plenumPressureFvPatchScalarField() [1/5]
plenumPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 30 of file plenumPressureFvPatchScalarField.C.
plenumPressureFvPatchScalarField() [2/5]
plenumPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 57 of file plenumPressureFvPatchScalarField.C.
References dict.
plenumPressureFvPatchScalarField() [3/5]
plenumPressureFvPatchScalarField (const plenumPressureFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 84 of file plenumPressureFvPatchScalarField.C.
plenumPressureFvPatchScalarField() [4/5]
plenumPressureFvPatchScalarField (const plenumPressureFvPatchScalarField & tppsf)
Definition at line 110 of file plenumPressureFvPatchScalarField.C.
plenumPressureFvPatchScalarField() [5/5]
plenumPressureFvPatchScalarField (const plenumPressureFvPatchScalarField & tppsf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 133 of file plenumPressureFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("plenumPressure")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 288 of file plenumPressureFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 304 of file plenumPressureFvPatchScalarField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 159 of file plenumPressureFvPatchScalarField.C.
References cp, Foam::dimMass, Foam::dimTime, Foam::dimVolume, Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::gSum(), Foam::lerp(), Foam::magSqr(), Foam::max(), Foam::nl, oldTime(), Foam::operator==(), p, phi, Foam::pos0(), Foam::pow(), s(), Foam::sqrt(), timeIndex, and U.
write()
void write (Ostream & os) const virtual
Definition at line 286 of file plenumPressureFvPatchScalarField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntry(), Ostream::writeEntryIfDifferent(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/plenumPressure/plenumPressureFvPatchScalarField.H
src/finiteVolume/fields/fvPatchFields/derived/plenumPressure/plenumPressureFvPatchScalarField.C