OpenFOAM: isothermal Class Reference
isothermal Class Reference
Isothermal dispersed-phase particle diameter model.
#include <isothermalDiameter.H>
Public Member Functions
TypeName ("isothermal")
isothermal (const dictionary &diameterProperties, const phaseModel &phase)
virtual ~isothermal ()=default
virtual tmp< volScalarField > d () const
virtual void correct ()
virtual bool read (const dictionary &phaseProperties)
TypeName ("isothermal")
isothermal (const dictionary &diameterProperties, const phaseModel &phase)
virtual ~isothermal ()
virtual tmp< volScalarField > d () const
virtual bool read (const dictionary &phaseProperties)
Public Member Functions inherited from diameterModel
TypeName ("diameterModel")
declareRunTimeSelectionTable (autoPtr, diameterModel, dictionary,(const dictionary &dict, const phaseModel &phase),(dict, phase))
diameterModel (const dictionary &dict, const phaseModel &phase)
virtual ~diameterModel ()=default
const dictionary & diameterProperties () const
const phaseModel & phase () const
TypeName ("diameterModel")
declareRunTimeSelectionTable (autoPtr, diameterModel, dictionary,(const dictionary &dict, const phaseModel &phase),(dict, phase))
diameterModel (const dictionary &dict, const phaseModel &phase)
virtual ~diameterModel ()=default
const dictionary & diameterProperties () const
const phaseModel & phase () const
Additional Inherited Members
Static Public Member Functions inherited from diameterModel
static autoPtr< diameterModel > New (const dictionary &diameterProperties, const phaseModel &phase)
static autoPtr< diameterModel > New (const dictionary &dict, const phaseModel &phase)
Protected Attributes inherited from diameterModel
dictionary diameterProperties_
const phaseModel & phase_
Detailed Description
Isothermal dispersed-phase particle diameter model.
Source files
isothermalDiameter.H
isothermal.C
Source files
isothermalDiameter.H
isothermal.C
Definition at line 48 of file isothermalDiameter.H.
Constructor & Destructor Documentation
isothermal() [1/2]
isothermal (const dictionary & diameterProperties, const phaseModel & phase)
Definition at line 45 of file isothermalDiameter.C.
References Foam::dimLength, Foam::dimPressure, and Foam::name().
~isothermal() [1/2]
~isothermal () virtual default
Definition at line 58 of file isothermalDiameter.C.
isothermal() [2/2]
isothermal (const dictionary & diameterProperties, const phaseModel & phase)
~isothermal() [2/2]
virtual ~isothermal () virtual
Member Function Documentation
TypeName() [1/2]
TypeName ("isothermal")
d() [1/2]
Foam::tmp< Foam::volScalarField > d () const virtual
Implements diameterModel.
Definition at line 72 of file isothermalDiameter.C.
correct()
void correct () virtual
Reimplemented from diameterModel.
Definition at line 78 of file isothermalDiameter.C.
References IOobject::db(), p, and Foam::pow().
read() [1/2]
bool read (const dictionary & phaseProperties) virtual
Implements diameterModel.
Definition at line 86 of file isothermalDiameter.C.
References diameterModel::read().
TypeName() [2/2]
TypeName ("isothermal")
d() [2/2]
virtual tmp< volScalarField > d () const virtual
Implements diameterModel.
read() [2/2]
virtual bool read (const dictionary & phaseProperties) virtual
Implements diameterModel.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/diameterModels/isothermalDiameter/isothermalDiameter.H
src/phaseSystemModels/twoPhaseEuler/twoPhaseSystem/diameterModels/isothermalDiameter/isothermalDiameter.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/diameterModels/isothermalDiameter/isothermalDiameter.C
src/phaseSystemModels/twoPhaseEuler/twoPhaseSystem/diameterModels/isothermalDiameter/isothermalDiameter.C