OpenFOAM: snappyVoxelMeshDriver Class Reference
snappyVoxelMeshDriver Class Reference
Equivalent of snappyRefineDriver but operating on a voxel mesh.
#include <snappyVoxelMeshDriver.H>
Public Member Functions
ClassName ("snappyVoxelMeshDriver")
snappyVoxelMeshDriver (meshRefinement &meshRefiner, const labelUList &globalToMasterPatch, const labelUList &globalToSlavePatch)
void doRefine (const refinementParameters &refineParams)
Detailed Description
Equivalent of snappyRefineDriver but operating on a voxel mesh.
Used to estimate cell size count from refinement (currently).
Source files
snappyVoxelMeshDriver.H
snappyVoxelMeshDriver.C
Definition at line 56 of file snappyVoxelMeshDriver.H.
Constructor & Destructor Documentation
snappyVoxelMeshDriver()
snappyVoxelMeshDriver (meshRefinement & meshRefiner, const labelUList & globalToMasterPatch, const labelUList & globalToSlavePatch)
Definition at line 345 of file snappyVoxelMeshDriver.C.
References Foam::endl(), meshRefinement::features(), forAll, Foam::Info, Foam::labelMax, Foam::labelMin, UPstream::master(), Foam::max(), meshRefinement::meshCutter(), Foam::nl, Foam::pow(), List< T >::setSize(), Foam::setw(), meshRefinement::shells(), Foam::Sout, boundBox::span(), meshRefinement::surfaces(), and OSstream::width().
Member Function Documentation
ClassName()
ClassName ("snappyVoxelMeshDriver")
doRefine()
void doRefine (const refinementParameters & refineParams)
Definition at line 440 of file snappyVoxelMeshDriver.C.
References Foam::endl(), forAll, Foam::Info, UPstream::master(), Foam::max(), Foam::nl, Foam::pow(), s(), UPtrList< T >::size(), and WarningInFunction.
The documentation for this class was generated from the following files:
src/mesh/snappyHexMesh/snappyHexMeshDriver/snappyVoxelMeshDriver.H
src/mesh/snappyHexMesh/snappyHexMeshDriver/snappyVoxelMeshDriver.C