OpenFOAM: searchablePlate Class Reference
searchablePlate Class Reference
Searching on finite plate. Plate has to be aligned with coordinate axes. Plate defined as origin and span. One of the components of span has to be 0 which defines the normal direction. E.g.
#include <searchablePlate.H>
Public Member Functions
TypeName ("searchablePlate")
searchablePlate (const IOobject &io, const point &origin, const vector &span)
searchablePlate (const IOobject &io, const dictionary &dict)
virtual ~searchablePlate ()=default
const point & centre () const noexcept
virtual const wordList & regions () const
virtual bool hasVolumeType () const
virtual volumeType outsideVolumeType () const
virtual label size () const
virtual tmp< pointField > coordinates () const
virtual void boundingSpheres (pointField &centres, scalarField &radiusSqr) const
virtual tmp< pointField > points () const
virtual bool overlaps (const boundBox &bb) const
virtual void findNearest (const pointField &sample, const scalarField &nearestDistSqr, List< pointIndexHit > &) const
virtual void findLine (const pointField &start, const pointField &end, List< pointIndexHit > &) const
virtual void findLineAny (const pointField &start, const pointField &end, List< pointIndexHit > &) const
virtual void findLineAll (const pointField &start, const pointField &end, List< List< pointIndexHit > > &) const
virtual void getRegion (const List< pointIndexHit > &, labelList &region) const
virtual void getNormal (const List< pointIndexHit > &, vectorField &normal) const
virtual void getVolumeType (const pointField &, List< volumeType > &) const
bool writeData (Ostream &) const
Public Member Functions inherited from searchableSurface
TypeName ("searchableSurface")
declareRunTimeSelectionTable (autoPtr, searchableSurface, dict,(const IOobject &io, const dictionary &dict),(io, dict))
searchableSurface (const IOobject &io)
virtual autoPtr< searchableSurface > clone () const
virtual ~searchableSurface ()=default
virtual bool global () const
virtual fileName filePath () const
virtual const boundBox & bounds () const
virtual boundBox & bounds ()
virtual label globalSize () const
virtual void distribute (const List< treeBoundBox > &, const bool keepNonLocal, autoPtr< mapDistribute > &faceMap, autoPtr< mapDistribute > &pointMap)
virtual void setField (const labelList &values)
virtual void getField (const List< pointIndexHit > &, labelList &values) const
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
regIOobject (const IOobject &io, const bool isTimeObject=false)
regIOobject (const regIOobject &rio)
regIOobject (const regIOobject &rio, bool registerCopy)
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
regIOobject (const IOobject &io, const regIOobject &rio)
virtual ~regIOobject ()
bool checkIn ()
bool checkOut ()
virtual void addWatch ()
bool registered () const noexcept
bool ownedByRegistry () const noexcept
bool store ()
void release (const bool unregister=false) noexcept
label eventNo () const noexcept
label & eventNo () noexcept
bool upToDate (const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
void setUpToDate ()
virtual void rename (const word &newName)
const dictionary * findMetaData () const noexcept
dictionary & getMetaData () noexcept
void removeMetaData ()
virtual void updateMetaData ()
bool headerOk ()
Istream & readStream (const word &, const bool readOnProc=true)
void close ()
virtual bool readData (Istream &)
virtual bool read ()
virtual label addWatch (const fileName &)
const labelList & watchIndices () const noexcept
labelList & watchIndices () noexcept
virtual bool modified () const
virtual bool readIfModified ()
virtual bool writeObject (IOstreamOption streamOpt, const bool writeOnProc) const
virtual bool write (const bool writeOnProc=true) const
void operator= (const IOobject &io)
virtual bool writeObject (IOstreamOption::streamFormat fmt, IOstreamOption::versionNumber ver, IOstreamOption::compressionType cmp, const bool writeOnProc) const
Public Member Functions inherited from IOobject
TypeName ("IOobject")
IOobject (const IOobject &)=default
virtual ~IOobject ()=default
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const fileName &path, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const fileName &path, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const IOobject &io, const objectRegistry &registry)
IOobject (const IOobject &io, const word &name)
IOobject (const IOobject &io, const word &name, const fileName &local)
IOobject (const IOobject &io, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt)
IOobject (const IOobject &io, IOobjectOption::registerOption regOpt)
autoPtr< IOobject > clone () const
autoPtr< IOobject > clone (const objectRegistry &registry) const
const objectRegistry & db () const noexcept
const Time & time () const noexcept
const word & name () const noexcept
const word & headerClassName () const noexcept
word & headerClassName () noexcept
const string & note () const noexcept
string & note () noexcept
unsigned labelByteSize () const noexcept
unsigned scalarByteSize () const noexcept
void resetHeader (const word &newName=word::null)
bool hasHeaderClass () const noexcept
template<class Type >
bool isHeaderClass () const
template<class Type >
bool isHeaderClassName () const
word group () const
word member () const
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const noexcept
fileName & instance () noexcept
const fileName & local () const noexcept
fileName path () const
fileName path (const word &instance, const fileName &local=fileName::null) const
fileName objectPath () const
fileName objectRelPath () const
fileName localFilePath (const word &typeName, const bool search=true) const
fileName globalFilePath (const word &typeName, const bool search=true) const
IOstreamOption parseHeader (const dictionary &headerDict)
bool readHeader (Istream &is)
bool readHeader (dictionary &headerDict, Istream &is)
template<class Type >
bool typeHeaderOk (const bool checkType=true, const bool search=true, const bool verbose=true)
template<class Type >
void warnNoRereading () const
bool writeHeader (Ostream &os) const
bool writeHeader (Ostream &os, const word &objectType) const
void writeHeader (dictionary &dict, IOstreamOption streamOpt) const
void writeHeader (dictionary &dict, const word &objectType, IOstreamOption streamOpt) const
bool good () const noexcept
bool bad () const noexcept
InfoProxy< IOobject > info () const noexcept
void operator= (const IOobject &io)
template<>
bool isHeaderClass () const
template<class StringType >
Foam::word groupName (StringType base, const word &group)
Public Member Functions inherited from IOobjectOption
constexpr IOobjectOption (readOption rOpt=readOption::NO_READ, writeOption wOpt=writeOption::NO_WRITE, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (readOption rOpt, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (writeOption wOpt, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (registerOption registerObject, bool globalObject=false) noexcept
constexpr IOobjectOption (readOption rOpt, writeOption wOpt, bool registerObject, bool globalObject=false) noexcept
constexpr IOobjectOption (bool registerObject, bool globalObject=false) noexcept
readOption readOpt () const noexcept
readOption readOpt (readOption opt) noexcept
writeOption writeOpt () const noexcept
writeOption writeOpt (writeOption opt) noexcept
bool registerObject () const noexcept
bool registerObject (bool on) noexcept
bool globalObject () const noexcept
bool globalObject (bool on) noexcept
bool isAnyRead () const noexcept
bool isReadRequired () const noexcept
bool isReadOptional () const noexcept
readOption & readOpt () noexcept
writeOption & writeOpt () noexcept
bool & registerObject () noexcept
bool & globalObject () noexcept
Additional Inherited Members
Public Types inherited from IOobject
enum objectState : char { GOOD , BAD }
enum fileCheckTypes : char { timeStamp , timeStampMaster , inotify , inotifyMaster }
Public Types inherited from IOobjectOption
enum readOption : unsigned char {
NO_READ = 0 , MUST_READ = 0x1 , READ_MODIFIED = 0x3 , MUST_READ_IF_MODIFIED = 0x3 ,
LAZY_READ = 0x4 , READ_IF_PRESENT = 0x4
}
enum writeOption : unsigned char { NO_WRITE = 0 , AUTO_WRITE = 0x10 }
enum registerOption : unsigned char { NO_REGISTER = 0 , REGISTER = 1 }
Static Public Member Functions inherited from searchableSurface
static autoPtr< searchableSurface > New (const word &surfaceType, const IOobject &io, const dictionary &dict)
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *p)
template<class Type >
static Type & store (autoPtr< Type > &ptr)
template<class Type >
static Type & store (autoPtr< Type > &&ptr)
template<class Type >
static Type & store (refPtr< Type > &ptr)
template<class Type >
static Type & store (refPtr< Type > &&ptr)
template<class Type >
static Type & store (tmp< Type > &ptr)
template<class Type >
static Type & store (tmp< Type > &&ptr)
Static Public Member Functions inherited from IOobject
static bool bannerEnabled () noexcept
static bool bannerEnabled (bool on) noexcept
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
template<class StringType >
static word groupName (StringType base, const word &group)
static word group (const word &name)
static word member (const word &name)
static word scopedName (const std::string &scope, const word &name)
static IOobject selectIO (const IOobject &io, const fileName &altFile, const word &ioName="")
static Ostream & writeBanner (Ostream &os, const bool noSyntaxHint=false)
static Ostream & writeDivider (Ostream &os)
static Ostream & writeEndDivider (Ostream &os)
Static Public Member Functions inherited from IOobjectOption
static bool isAnyRead (readOption opt) noexcept
static bool isReadRequired (readOption opt) noexcept
static bool isReadOptional (readOption opt) noexcept
static readOption lazierRead (readOption opt) noexcept
Static Public Attributes inherited from IOobject
static const Enum< fileCheckTypes > fileCheckTypesNames
static char scopeSeparator
static fileCheckTypes fileModificationChecking
static float fileModificationSkew
static int maxFileModificationPolls
Protected Member Functions inherited from regIOobject
bool readHeaderOk (const IOstreamOption::streamFormat fmt, const word &typeName)
Protected Member Functions inherited from IOobject
void setBad (const string &s)
Static Protected Member Functions inherited from IOobject
static void writeHeaderContent (Ostream &os, const IOobject &io, const word &objectType, const dictionary *metaDataDict=nullptr)
static void writeHeaderContent (dictionary &dict, const IOobject &io, const word &objectType, IOstreamOption streamOpt, const dictionary *metaDataDict=nullptr)
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
Detailed Description
Searching on finite plate. Plate has to be aligned with coordinate axes. Plate defined as origin and span. One of the components of span has to be 0 which defines the normal direction. E.g.
span    = (Sx Sy 0)     // plate in x-y plane
origin  = (Ox Oy Oz)
now plane is from (Ox Oy Oz) to (Ox+Sx Oy+Sy Oz)
Dictionary parameters
Property Description Required Default
type plate selector
origin The minimum corner of the plate yes
span The plate dimensions yes
Note
Longer type name : searchablePlate
Source files
searchablePlate.H
searchablePlate.C
Definition at line 89 of file searchablePlate.H.
Constructor & Destructor Documentation
searchablePlate() [1/2]
searchablePlate (const IOobject & io, const point & origin, const vector & span)
Definition at line 213 of file searchablePlate.C.
References searchableSurface::bounds(), VectorSpace< Form, Cmpt, Ncmpts >::componentNames, DebugInFunction, and Foam::nl.
searchablePlate() [2/2]
searchablePlate (const IOobject & io, const dictionary & dict)
Definition at line 234 of file searchablePlate.C.
~searchablePlate()
virtual ~searchablePlate () virtual default
Member Function Documentation
TypeName()
TypeName ("searchablePlate")
centre()
const point & centre () const inline noexcept
Definition at line 166 of file searchablePlate.H.
regions()
const Foam::wordList & regions () const virtual
Implements searchableSurface.
Definition at line 246 of file searchablePlate.C.
References UPtrList< T >::first(), and PtrList< T >::resize().
hasVolumeType()
virtual bool hasVolumeType () const inline virtual
Reimplemented from searchableSurface.
Definition at line 175 of file searchablePlate.H.
outsideVolumeType()
virtual volumeType outsideVolumeType () const inline virtual
Implements searchableSurface.
Definition at line 181 of file searchablePlate.H.
References volumeType::UNKNOWN.
size()
virtual label size () const inline virtual
Implements searchableSurface.
Definition at line 187 of file searchablePlate.H.
coordinates()
Foam::tmp< Foam::pointField > coordinates () const virtual
Implements searchableSurface.
Definition at line 257 of file searchablePlate.C.
References tmp< T >::New().
boundingSpheres()
void boundingSpheres (pointField & centres, scalarField & radiusSqr) const virtual
Implements searchableSurface.
Definition at line 263 of file searchablePlate.C.
References Foam::magSqr(), List< T >::resize(), PtrList< T >::resize(), and Foam::sqr().
points()
Foam::tmp< Foam::pointField > points () const virtual
Implements searchableSurface.
Definition at line 280 of file searchablePlate.C.
References tmp< T >::New(), and pts.
overlaps()
bool overlaps (const boundBox & bb) const virtual
Implements searchableSurface.
Definition at line 307 of file searchablePlate.C.
References boundBox::overlaps().
findNearest()
void findNearest (const pointField & sample, const scalarField & nearestDistSqr, List< pointIndexHit > & info) const virtual
Implements searchableSurface.
Definition at line 313 of file searchablePlate.C.
References forAll, samples(), PtrList< T >::setSize(), and UList< T >::size().
findLine()
void findLine (const pointField & start, const pointField & end, List< pointIndexHit > & info) const virtual
Implements searchableSurface.
Definition at line 329 of file searchablePlate.C.
References forAll, PtrList< T >::setSize(), and UList< T >::size().
findLineAny()
void findLineAny (const pointField & start, const pointField & end, List< pointIndexHit > & info) const virtual
Implements searchableSurface.
Definition at line 345 of file searchablePlate.C.
findLineAll()
void findLineAll (const pointField & start, const pointField & end, List< List< pointIndexHit > > & info) const virtual
Implements searchableSurface.
Definition at line 356 of file searchablePlate.C.
References PtrList< T >::clear(), forAll, PtrList< T >::setSize(), and UList< T >::size().
getRegion()
void getRegion (const List< pointIndexHit > & info, labelList & region) const virtual
Implements searchableSurface.
Definition at line 382 of file searchablePlate.C.
References List< T >::setSize(), and UPtrList< T >::size().
getNormal()
void getNormal (const List< pointIndexHit > & info, vectorField & normal) const virtual
Implements searchableSurface.
Definition at line 393 of file searchablePlate.C.
References forAll, List< T >::setSize(), UPtrList< T >::size(), and Foam::Zero.
getVolumeType()
void getVolumeType (const pointField & points, List< volumeType > & volType) const virtual
Implements searchableSurface.
Definition at line 408 of file searchablePlate.C.
References Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
writeData()
bool writeData (Ostream &) const inline virtual
Implements regIOobject.
Definition at line 267 of file searchablePlate.H.
References NotImplemented.
The documentation for this class was generated from the following files:
src/meshTools/searchableSurfaces/searchablePlate/searchablePlate.H
src/meshTools/searchableSurfaces/searchablePlate/searchablePlate.C