OpenFOAM: UOprocess Class Reference
UOprocess Class Reference
Random UO process.
#include <UOprocess.H>
Public Member Functions
UOprocess (const Kmesh &kmesh, const scalar deltaT, const dictionary &)
const complexVectorField & newField ()
Detailed Description
Random UO process.
Source files
UOprocess.H
UOprocess.C
Definition at line 51 of file UOprocess.H.
Constructor & Destructor Documentation
UOprocess()
UOprocess (const Kmesh & kmesh, const scalar deltaT, const dictionary & UOdict)
Definition at line 47 of file UOprocess.C.
References forAll, Foam::magSqr(), Foam::sqr(), and VectorSpace< Vector< Cmpt >, Cmpt, 3 >::zero.
Member Function Documentation
newField()
const complexVectorField & newField ()
Definition at line 88 of file UOprocess.C.
References forAll, Foam::Info, Foam::magSqr(), Foam::nl, and Foam::sqr().
The documentation for this class was generated from the following files:
src/randomProcesses/processes/UOprocess/UOprocess.H
src/randomProcesses/processes/UOprocess/UOprocess.C