OpenFOAM: nonuniformTransformCyclicPointPatch Class Reference
nonuniformTransformCyclicPointPatch Class Reference
Cyclic patch with slip constraint.
#include <nonuniformTransformCyclicPointPatch.H>
Public Member Functions
TypeName (nonuniformTransformCyclicPolyPatch::typeName_())
nonuniformTransformCyclicPointPatch (const polyPatch &patch, const pointBoundaryMesh &bm)
virtual ~nonuniformTransformCyclicPointPatch ()=default
virtual const vectorField & pointNormals () const
virtual void applyConstraint (const label pointi, pointConstraint &) const
Public Member Functions inherited from cyclicPointPatch
TypeName (cyclicPolyPatch::typeName_())
cyclicPointPatch (const polyPatch &patch, const pointBoundaryMesh &bm)
virtual ~cyclicPointPatch ()
virtual const word & constraintType () const
const cyclicPolyPatch & cyclicPatch () const
const cyclicPointPatch & neighbPatch () const
bool parallel () const
const tensorField & forwardT () const
const tensorField & reverseT () const
virtual const edgeList & transformPairs () const
Public Member Functions inherited from coupledFacePointPatch
TypeName (coupledPolyPatch::typeName_())
coupledFacePointPatch (const polyPatch &patch, const pointBoundaryMesh &bm)
virtual ~coupledFacePointPatch ()=default
Public Member Functions inherited from facePointPatch
TypeName (polyPatch::typeName_())
declareRunTimeSelectionTable (autoPtr, facePointPatch, polyPatch,(const polyPatch &patch, const pointBoundaryMesh &bm),(patch, bm))
facePointPatch (const polyPatch &p, const pointBoundaryMesh &pm)
virtual ~facePointPatch ()=default
virtual const polyPatch & patch () const
virtual const word & name () const
virtual label size () const
virtual label index () const
virtual bool coupled () const
virtual const labelList & meshPoints () const
virtual const pointField & localPoints () const
Public Member Functions inherited from pointPatch
TypeName ("basePatch")
pointPatch (const pointBoundaryMesh &bm)
virtual ~pointPatch ()=default
const pointBoundaryMesh & boundaryMesh () const
Public Member Functions inherited from coupledPointPatch
TypeName (coupledPolyPatch::typeName_())
coupledPointPatch (const pointBoundaryMesh &bm)
virtual ~coupledPointPatch ()=default
Additional Inherited Members
Static Public Member Functions inherited from facePointPatch
static autoPtr< facePointPatch > New (const polyPatch &, const pointBoundaryMesh &)
Protected Member Functions inherited from coupledFacePointPatch
coupledFacePointPatch (const coupledFacePointPatch &)=delete
void operator= (const coupledFacePointPatch &)=delete
Protected Member Functions inherited from facePointPatch
facePointPatch (const facePointPatch &)=delete
void operator= (const facePointPatch &)=delete
Protected Member Functions inherited from pointPatch
pointPatch (const pointPatch &)=delete
void operator= (const pointPatch &)=delete
Protected Member Functions inherited from coupledPointPatch
coupledPointPatch (const coupledPointPatch &)=delete
void operator= (const coupledPointPatch &)=delete
Protected Attributes inherited from facePointPatch
const polyPatch & polyPatch_
Detailed Description
Cyclic patch with slip constraint.
Source files
nonuniformTransformCyclicPointPatch.H
nonuniformTransformCyclicPointPatch.C
Definition at line 48 of file nonuniformTransformCyclicPointPatch.H.
Constructor & Destructor Documentation
nonuniformTransformCyclicPointPatch()
nonuniformTransformCyclicPointPatch (const polyPatch & patch, const pointBoundaryMesh & bm) inline
Definition at line 62 of file nonuniformTransformCyclicPointPatch.H.
~nonuniformTransformCyclicPointPatch()
virtual ~nonuniformTransformCyclicPointPatch () virtual default
Member Function Documentation
TypeName()
TypeName (nonuniformTransformCyclicPolyPatch::typeName_())
pointNormals()
const vectorField & pointNormals () const virtual
Reimplemented from facePointPatch.
Definition at line 44 of file nonuniformTransformCyclicPointPatch.C.
Referenced by nonuniformTransformCyclicPointPatch::applyConstraint().
applyConstraint()
void applyConstraint (const label pointi, pointConstraint & pc) const virtual
Reimplemented from pointPatch.
Definition at line 54 of file nonuniformTransformCyclicPointPatch.C.
References pointConstraint::applyConstraint(), and nonuniformTransformCyclicPointPatch::pointNormals().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/pointMesh/pointPatches/constraint/nonuniformTransformCyclic/nonuniformTransformCyclicPointPatch.H
src/OpenFOAM/meshes/pointMesh/pointPatches/constraint/nonuniformTransformCyclic/nonuniformTransformCyclicPointPatch.C