OpenFOAM: pointPatchFieldBase Class Reference
pointPatchFieldBase Class Reference
#include <pointPatchField.H>
Public Member Functions
TypeName ("pointPatchField")
pointPatchFieldBase (const pointPatch &p)
pointPatchFieldBase (const pointPatch &p, const word &patchType)
pointPatchFieldBase (const pointPatch &p, const dictionary &dict)
pointPatchFieldBase (const pointPatchFieldBase &, const pointPatch &p)
pointPatchFieldBase (const pointPatchFieldBase &)
virtual ~pointPatchFieldBase ()=default
virtual bool fixesValue () const
virtual bool coupled () const
virtual const word & constraintType () const
const objectRegistry & db () const
const pointPatch & patch () const noexcept
const word & patchType () const noexcept
word & patchType () noexcept
bool updated () const noexcept
bool manipulatedMatrix () const noexcept
void checkPatch (const pointPatchFieldBase &rhs) const
Static Public Member Functions
static const word & emptyType () noexcept
static const word & calculatedType () noexcept
static const word & zeroGradientType () noexcept
Static Public Attributes
static int disallowGenericPatchField
Protected Member Functions
virtual void readDict (const dictionary &dict)
void setUpdated (bool state) noexcept
void setManipulated (bool state) noexcept
Detailed Description
Definition at line 72 of file pointPatchField.H.
Constructor & Destructor Documentation
pointPatchFieldBase() [1/5]
pointPatchFieldBase (const pointPatch & p) explicit
Definition at line 39 of file pointPatchFieldBase.C.
pointPatchFieldBase() [2/5]
pointPatchFieldBase (const pointPatch & p, const word & patchType)
Definition at line 47 of file pointPatchFieldBase.C.
References pointPatchFieldBase::patchType().
pointPatchFieldBase() [3/5]
pointPatchFieldBase (const pointPatch & p, const dictionary & dict)
Definition at line 59 of file pointPatchFieldBase.C.
References dict, and pointPatchFieldBase::readDict().
pointPatchFieldBase() [4/5]
pointPatchFieldBase (const pointPatchFieldBase & rhs, const pointPatch & p)
Definition at line 71 of file pointPatchFieldBase.C.
pointPatchFieldBase() [5/5]
pointPatchFieldBase (const pointPatchFieldBase & rhs)
Definition at line 83 of file pointPatchFieldBase.C.
~pointPatchFieldBase()
virtual ~pointPatchFieldBase () virtual default
Member Function Documentation
readDict()
void readDict (const dictionary & dict) protected virtual
Definition at line 93 of file pointPatchFieldBase.C.
References dict, keyType::LITERAL, and dictionary::readIfPresent().
Referenced by pointPatchFieldBase::pointPatchFieldBase().
setUpdated()
void setUpdated (bool state) inline protected noexcept
Definition at line 99 of file pointPatchField.H.
Referenced by pointPatchField< Type >::evaluate(), and pointPatchField< Type >::updateCoeffs().
setManipulated()
void setManipulated (bool state) inline protected noexcept
Definition at line 105 of file pointPatchField.H.
TypeName()
TypeName ("pointPatchField")
emptyType()
static const word & emptyType () inline static noexcept
Definition at line 143 of file pointPatchField.H.
References Foam::fieldTypes::emptyType.
calculatedType()
static const word & calculatedType () inline static noexcept
Definition at line 149 of file pointPatchField.H.
References Foam::fieldTypes::calculatedType.
Referenced by fvMeshSubset::interpolate().
zeroGradientType()
static const word & zeroGradientType () inline static noexcept
Definition at line 155 of file pointPatchField.H.
References Foam::fieldTypes::zeroGradientType.
fixesValue()
virtual bool fixesValue () const inline virtual
Reimplemented in fixedValuePointPatchField< Type >, and fixedValuePointPatchField< vector >.
Definition at line 166 of file pointPatchField.H.
coupled()
virtual bool coupled () const inline virtual
Reimplemented in cyclicAMIPointPatchField< Type >, coupledPointPatchField< Type >, processorPointPatchField< Type >, and processorCyclicPointPatchField< Type >.
Definition at line 172 of file pointPatchField.H.
constraintType()
virtual const word & constraintType () const inline virtual
Reimplemented in cyclicACMIPointPatchField< Type >, cyclicAMIPointPatchField< Type >, cyclicPointPatchField< Type >, emptyPointPatchField< Type >, processorPointPatchField< Type >, symmetryPointPatchField< Type >, symmetryPlanePointPatchField< Type >, and wedgePointPatchField< Type >.
Definition at line 178 of file pointPatchField.H.
References word::null.
db()
const Foam::objectRegistry & db () const
Definition at line 99 of file pointPatchFieldBase.C.
Referenced by waveMakerPointPatchVectorField::g(), timeVaryingUniformFixedValuePointPatchField< Type >::timeVaryingUniformFixedValuePointPatchField(), timeVaryingUniformFixedValuePointPatchField< Type >::timeVaryingUniformFixedValuePointPatchField(), sixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs(), and uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs().
patch()
const pointPatch & patch () const inline noexcept
Definition at line 190 of file pointPatchField.H.
Referenced by cyclicACMIPointPatchField< Type >::cyclicACMIPointPatchField(), cyclicACMIPointPatchField< Type >::cyclicACMIPointPatchField(), cyclicAMIPointPatchField< Type >::cyclicAMIPointPatchField(), cyclicAMIPointPatchField< Type >::cyclicAMIPointPatchField(), cyclicPointPatchField< Type >::cyclicPointPatchField(), cyclicPointPatchField< Type >::cyclicPointPatchField(), emptyPointPatchField< Type >::emptyPointPatchField(), emptyPointPatchField< Type >::emptyPointPatchField(), genericPointPatchField< Type >::genericPointPatchField(), genericPointPatchField< Type >::genericPointPatchField(), lumpedPointDisplacementPointPatchVectorField::lumpedPointDisplacementPointPatchVectorField(), valuePointPatchField< Type >::readValueEntry(), valuePointPatchField< vector >::readValueEntry(), pointPatchField< Type >::size(), symmetryPlanePointPatchField< Type >::symmetryPlanePointPatchField(), symmetryPlanePointPatchField< Type >::symmetryPlanePointPatchField(), symmetryPointPatchField< Type >::symmetryPointPatchField(), symmetryPointPatchField< Type >::symmetryPointPatchField(), angularOscillatingVelocityPointPatchVectorField::updateCoeffs(), oscillatingVelocityPointPatchVectorField::updateCoeffs(), sixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs(), wedgePointPatchField< Type >::wedgePointPatchField(), and wedgePointPatchField< Type >::wedgePointPatchField().
patchType() [1/2]
const word & patchType () const inline noexcept
Definition at line 196 of file pointPatchField.H.
Referenced by pointPatchFieldBase::pointPatchFieldBase().
patchType() [2/2]
word & patchType () inline noexcept
Definition at line 202 of file pointPatchField.H.
updated()
bool updated () const inline noexcept
Definition at line 211 of file pointPatchField.H.
Referenced by angularOscillatingDisplacementPointPatchVectorField::updateCoeffs(), angularOscillatingVelocityPointPatchVectorField::updateCoeffs(), oscillatingDisplacementPointPatchVectorField::updateCoeffs(), oscillatingVelocityPointPatchVectorField::updateCoeffs(), uniformInterpolatedDisplacementPointPatchVectorField::updateCoeffs(), sixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs(), and uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs().
manipulatedMatrix()
bool manipulatedMatrix () const inline noexcept
Definition at line 218 of file pointPatchField.H.
checkPatch()
void checkPatch (const pointPatchFieldBase & rhs) const
Definition at line 105 of file pointPatchFieldBase.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Member Data Documentation
disallowGenericPatchField
int disallowGenericPatchField static
Definition at line 112 of file pointPatchField.H.
Referenced by pointPatchField< Type >::New().
The documentation for this class was generated from the following files:
src/OpenFOAM/fields/pointPatchFields/pointPatchField/pointPatchField.H
src/OpenFOAM/fields/pointPatchFields/pointPatchField/pointPatchFieldBase.C