OpenFOAM: mappedFlowRateFvPatchVectorField Class Reference
mappedFlowRateFvPatchVectorField Class Reference
Boundary conditions » Inlet | Boundary conditions » Coupled
Describes a volumetric/mass flow normal vector boundary condition by its magnitude as an integral over its area.
#include <mappedFlowRateFvPatchVectorField.H>
Public Member Functions
TypeName ("mappedFlowRate")
mappedFlowRateFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
mappedFlowRateFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
mappedFlowRateFvPatchVectorField (const mappedFlowRateFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
mappedFlowRateFvPatchVectorField (const mappedFlowRateFvPatchVectorField &)
virtual tmp< fvPatchVectorField > clone () const
mappedFlowRateFvPatchVectorField (const mappedFlowRateFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
Describes a volumetric/mass flow normal vector boundary condition by its magnitude as an integral over its area.
The inlet mass flux is taken from the neighbour region.
The basis of the patch (volumetric or mass) is determined by the dimensions of the flux, phi. The current density is used to correct the velocity when applying the mass basis.
Usage
Property Description Required Default value
phi flux field name no phi
rho density field name no rho
neigPhi name of flux field on neighbour mesh yes
Example of the boundary condition specification:
    <patchName>
    {
        type            mappedFlowRate;
        phi             phi;
        rho             rho;
        neigPhi         phi;
        value           uniform (0 0 0); // placeholder
    }
Source files
mappedFlowRateFvPatchVectorField.H
mappedFlowRateFvPatchVectorField.C
Definition at line 95 of file mappedFlowRateFvPatchVectorField.H.
Constructor & Destructor Documentation
mappedFlowRateFvPatchVectorField() [1/5]
mappedFlowRateFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Definition at line 31 of file mappedFlowRateFvPatchVectorField.C.
mappedFlowRateFvPatchVectorField() [2/5]
mappedFlowRateFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Definition at line 59 of file mappedFlowRateFvPatchVectorField.C.
mappedFlowRateFvPatchVectorField() [3/5]
mappedFlowRateFvPatchVectorField (const mappedFlowRateFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 44 of file mappedFlowRateFvPatchVectorField.C.
mappedFlowRateFvPatchVectorField() [4/5]
mappedFlowRateFvPatchVectorField (const mappedFlowRateFvPatchVectorField & ptf)
Definition at line 73 of file mappedFlowRateFvPatchVectorField.C.
mappedFlowRateFvPatchVectorField() [5/5]
mappedFlowRateFvPatchVectorField (const mappedFlowRateFvPatchVectorField & ptf, const DimensionedField< vector, volMesh > & iF)
Definition at line 85 of file mappedFlowRateFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("mappedFlowRate")
clone() [1/2]
virtual tmp< fvPatchVectorField > clone () const inline virtual
Definition at line 152 of file mappedFlowRateFvPatchVectorField.H.
clone() [2/2]
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Definition at line 168 of file mappedFlowRateFvPatchVectorField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 100 of file mappedFlowRateFvPatchVectorField.C.
References DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimMass, Foam::dimTime, Foam::dimVolume, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::gSum(), Foam::Info, UPstream::msgType(), n, Foam::nl, Foam::operator==(), phi, U, and fvPatchField< Type >::updateCoeffs().
write()
void write (Ostream & os) const virtual
Definition at line 180 of file mappedFlowRateFvPatchVectorField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntry(), Ostream::writeEntryIfDifferent(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/mappedFlowRate/mappedFlowRateFvPatchVectorField.H
src/finiteVolume/fields/fvPatchFields/derived/mappedFlowRate/mappedFlowRateFvPatchVectorField.C