OpenFOAM: nutURoughWallFunctionFvPatchScalarField Class Reference
nutURoughWallFunctionFvPatchScalarField Class Reference
Turbulence models » Boundary conditions » Wall functions
This boundary condition provides a wall function on the turbulent viscosity (i.e. nut) based on velocity (i.e. U) for low- and high-Reynolds number applications for rough walls.
#include <nutURoughWallFunctionFvPatchScalarField.H>
Public Member Functions
TypeName ("nutURoughWallFunction")
nutURoughWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
nutURoughWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
nutURoughWallFunctionFvPatchScalarField (const nutURoughWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
nutURoughWallFunctionFvPatchScalarField (const nutURoughWallFunctionFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
nutURoughWallFunctionFvPatchScalarField (const nutURoughWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
scalar roughnessHeight () const noexcept
scalar & roughnessHeight () noexcept
scalar roughnessConstant () const noexcept
scalar & roughnessConstant () noexcept
scalar roughnessFactor () const noexcept
scalar & roughnessFactor () noexcept
virtual tmp< scalarField > yPlus () const
virtual void write (Ostream &os) const
Public Member Functions inherited from nutWallFunctionFvPatchScalarField
TypeName ("nutWallFunction")
nutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
nutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &)
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
const wallFunctionCoefficients & wallCoeffs () const noexcept
virtual void updateCoeffs ()
Additional Inherited Members
Static Public Member Functions inherited from nutWallFunctionFvPatchScalarField
static const nutWallFunctionFvPatchScalarField & nutw (const turbulenceModel &turbModel, const label patchi)
Protected Member Functions inherited from nutWallFunctionFvPatchScalarField
virtual const volVectorField & U (const turbulenceModel &turb) const
virtual void checkType ()
void writeLocalEntries (Ostream &) const
Protected Attributes inherited from nutWallFunctionFvPatchScalarField
word UName_
wallFunctionCoefficients wallCoeffs_
Detailed Description
This boundary condition provides a wall function on the turbulent viscosity (i.e. nut) based on velocity (i.e. U) for low- and high-Reynolds number applications for rough walls.
Usage
Example of the boundary condition specification:
<patchName>
{
    // Mandatory entries
    type                nutURoughWallFunction;
    roughnessHeight     1e-5;
    roughnessConstant   0.5;
    roughnessFactor     1;
    // Optional entries
    maxIter             10;
    tolerance           0.0001;
    // Inherited entries
    ...
}
where the entries mean:
Property Description Type Reqd Deflt
type Type name: nutURoughWallFunction word yes -
roughnessHeight Roughness height scalar yes -
roughnessConstant Roughness constant scalar yes -
roughnessFactor Scaling factor scalar yes -
maxIter Number of Newton-Raphson iterations label no 10
tolerance Convergence tolerance scalar no 0.0001
The inherited entries are elaborated in:
nutWallFunctionFvPatchScalarField.H
Note
Suffers from non-exact restart since correctNut() (called through turbulence->validate) returns a slightly different value every time it is called. See nutUSpaldingWallFunctionFvPatchScalarField.C.
Source files
nutURoughWallFunctionFvPatchScalarField.H
nutURoughWallFunctionFvPatchScalarField.C
Definition at line 134 of file nutURoughWallFunctionFvPatchScalarField.H.
Constructor & Destructor Documentation
nutURoughWallFunctionFvPatchScalarField() [1/5]
nutURoughWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 227 of file nutURoughWallFunctionFvPatchScalarField.C.
nutURoughWallFunctionFvPatchScalarField() [2/5]
nutURoughWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 261 of file nutURoughWallFunctionFvPatchScalarField.C.
nutURoughWallFunctionFvPatchScalarField() [3/5]
nutURoughWallFunctionFvPatchScalarField (const nutURoughWallFunctionFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 243 of file nutURoughWallFunctionFvPatchScalarField.C.
nutURoughWallFunctionFvPatchScalarField() [4/5]
nutURoughWallFunctionFvPatchScalarField (const nutURoughWallFunctionFvPatchScalarField & rwfpsf)
Definition at line 278 of file nutURoughWallFunctionFvPatchScalarField.C.
nutURoughWallFunctionFvPatchScalarField() [5/5]
nutURoughWallFunctionFvPatchScalarField (const nutURoughWallFunctionFvPatchScalarField & rwfpsf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 293 of file nutURoughWallFunctionFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("nutURoughWallFunction")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 212 of file nutURoughWallFunctionFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 228 of file nutURoughWallFunctionFvPatchScalarField.H.
roughnessHeight() [1/2]
scalar roughnessHeight () const inline noexcept
Definition at line 245 of file nutURoughWallFunctionFvPatchScalarField.H.
roughnessHeight() [2/2]
scalar & roughnessHeight () inline noexcept
Definition at line 251 of file nutURoughWallFunctionFvPatchScalarField.H.
roughnessConstant() [1/2]
scalar roughnessConstant () const inline noexcept
Definition at line 257 of file nutURoughWallFunctionFvPatchScalarField.H.
roughnessConstant() [2/2]
scalar & roughnessConstant () inline noexcept
Definition at line 263 of file nutURoughWallFunctionFvPatchScalarField.H.
roughnessFactor() [1/2]
scalar roughnessFactor () const inline noexcept
Definition at line 269 of file nutURoughWallFunctionFvPatchScalarField.H.
roughnessFactor() [2/2]
scalar & roughnessFactor () inline noexcept
Definition at line 276 of file nutURoughWallFunctionFvPatchScalarField.H.
yPlus()
Foam::tmp< Foam::scalarField > yPlus () const virtual
Implements nutWallFunctionFvPatchScalarField.
Definition at line 312 of file nutURoughWallFunctionFvPatchScalarField.C.
References IOobject::groupName(), Foam::mag(), magUp, turbulenceModel::propertiesName, and U.
write()
void write (Ostream & os) const virtual
Reimplemented from nutWallFunctionFvPatchScalarField.
Definition at line 332 of file nutURoughWallFunctionFvPatchScalarField.C.
References os(), nutWallFunctionFvPatchScalarField::write(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/derivedFvPatchFields/wallFunctions/nutWallFunctions/nutURoughWallFunction/nutURoughWallFunctionFvPatchScalarField.H
src/TurbulenceModels/turbulenceModels/derivedFvPatchFields/wallFunctions/nutWallFunctions/nutURoughWallFunction/nutURoughWallFunctionFvPatchScalarField.C