OpenFOAM: List< Type > Class Template Reference
List< Type > Class Template Reference
Container for glTF entities.
#include <foamGltfList.H>
Public Member Functions
List ()=default
~List ()=default
Type & create (const word &name)
const DynamicList< Type > & data () const noexcept
bool empty () const noexcept
label size () const noexcept
void write (Ostream &os, const word &keyword, bool firstEntry=false)
void write (Ostream &os) const
Type & operator[] (const label i)
Detailed Description
template<class Type>
class Foam::glTF::List< Type >
Container for glTF entities.
Note
Implements the glTF v2 specification
Source files
foamGltfList.H
foamGltfList.C
Definition at line 61 of file foamGltfList.H.
Constructor & Destructor Documentation
List()
template<class Type > List () default
~List()
template<class Type > ~List () default
Member Function Documentation
create()
template<class Type > Type & create (const word & name)
Definition at line 26 of file foamGltfList.C.
References PtrList< T >::append(), UPtrList< T >::last(), Foam::name(), and UPtrList< T >::size().
data()
template<class Type > const Foam::DynamicList< Type > & data () const noexcept
Definition at line 37 of file foamGltfList.C.
empty()
template<class Type > bool empty () const noexcept
Definition at line 44 of file foamGltfList.C.
References UPtrList< T >::empty().
size()
template<class Type > Foam::label size () const noexcept
Definition at line 51 of file foamGltfList.C.
References UPtrList< T >::size().
write() [1/2]
template<class Type > void write (Ostream & os, const word & keyword, bool firstEntry = false)
Definition at line 58 of file foamGltfList.C.
References Foam::decrIndent(), Foam::incrIndent(), Foam::indent(), Foam::nl, os(), and write().
write() [2/2]
template<class Type > void write (Ostream & os) const
Definition at line 84 of file foamGltfList.C.
operator[]()
template<class Type > Type & operator[] (const label i)
Definition at line 100 of file foamGltfList.C.
The documentation for this class was generated from the following files:
src/fileFormats/gltf/foamGltfList.H
src/fileFormats/gltf/foamGltfList.C