OpenFOAM: localBlended< Type > Class Template Reference
localBlended< Type > Class Template Reference
Numerics » Finite volume numerical schemes » Surface interpolation schemes
Two-scheme localBlended differencing scheme.
#include <localBlended.H>
Public Member Functions
TypeName ("localBlended")
localBlended (const fvMesh &mesh, Istream &is)
localBlended (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &is)
virtual ~localBlended ()=default
virtual tmp< surfaceScalarField > blendingFactor (const GeometricField< Type, fvPatchField, volMesh > &vf) const
tmp< surfaceScalarField > weights (const GeometricField< Type, fvPatchField, volMesh > &vf) const
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &vf) const
virtual bool corrected () const
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > &vf) const
Public Member Functions inherited from surfaceInterpolationScheme< Type >
TypeName ("surfaceInterpolationScheme")
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, Mesh,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, MeshFlux,(const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
surfaceInterpolationScheme (const fvMesh &mesh)
virtual ~surfaceInterpolationScheme ()=default
const fvMesh & mesh () const
virtual tmp< GeometricField< typename innerProduct< vector, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf) const
tmp< GeometricField< typename innerProduct< vector, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const tmp< GeometricField< Type, fvPatchField, volMesh > > &) const
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > &) const
template<class SFType >
Foam::tmp< Foam::GeometricField< typename Foam::innerProduct< typename SFType::value_type, Type >::type, Foam::fvsPatchField, Foam::surfaceMesh > > dotInterpolate (const SFType &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf, const tmp< surfaceScalarField > &tlambdas)
tmp< GeometricField< typename innerProduct< vector, scalar >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const GeometricField< scalar, fvPatchField, volMesh > &) const
Foam::tmp< Foam::GeometricField< typename Foam::innerProduct< Foam::vector, Foam::scalar >::type, Foam::fvsPatchField, Foam::surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const GeometricField< scalar, fvPatchField, volMesh > &) const
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Public Member Functions inherited from blendedSchemeBase< Type >
blendedSchemeBase ()=default
virtual ~blendedSchemeBase ()=default
Additional Inherited Members
Static Public Member Functions inherited from surfaceInterpolationScheme< Type >
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData)
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &, const tmp< surfaceScalarField > &)
template<class SFType >
static tmp< GeometricField< typename innerProduct< typename SFType::value_type, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const SFType &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf, const tmp< surfaceScalarField > &tlambdas)
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &)
Detailed Description
template<class Type>
class Foam::localBlended< Type >
Two-scheme localBlended differencing scheme.
Source files
localBlended.H
localBlended.C
Definition at line 52 of file localBlended.H.
Constructor & Destructor Documentation
localBlended() [1/2]
template<class Type > localBlended (const fvMesh & mesh, Istream & is) inline
Definition at line 84 of file localBlended.H.
localBlended() [2/2]
template<class Type > localBlended (const fvMesh & mesh, const surfaceScalarField & faceFlux, Istream & is) inline
Definition at line 102 of file localBlended.H.
~localBlended()
template<class Type > virtual ~localBlended () virtual default
Member Function Documentation
TypeName()
template<class Type > TypeName ("localBlended< Type >")
blendingFactor()
template<class Type > virtual tmp< surfaceScalarField > blendingFactor (const GeometricField< Type, fvPatchField, volMesh > & vf) const inline virtual
Implements blendedSchemeBase< Type >.
Definition at line 128 of file localBlended.H.
References surfaceInterpolationScheme< Type >::mesh().
Referenced by localBlended< Type >::correction(), localBlended< Type >::interpolate(), and localBlended< Type >::weights().
weights()
template<class Type > tmp< surfaceScalarField > weights (const GeometricField< Type, fvPatchField, volMesh > & vf) const inline virtual
Implements surfaceInterpolationScheme< Type >.
Definition at line 142 of file localBlended.H.
References localBlended< Type >::blendingFactor(), and surfaceInterpolationScheme< Type >::mesh().
interpolate()
template<class Type > tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > & vf) const inline virtual
Reimplemented from surfaceInterpolationScheme< Type >.
Definition at line 162 of file localBlended.H.
References localBlended< Type >::blendingFactor(), and surfaceInterpolationScheme< Type >::mesh().
corrected()
template<class Type > virtual bool corrected () const inline virtual
Reimplemented from surfaceInterpolationScheme< Type >.
Definition at line 180 of file localBlended.H.
Referenced by localBlended< Type >::correction().
correction()
template<class Type > virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > & vf) const inline virtual
Reimplemented from surfaceInterpolationScheme< Type >.
Definition at line 189 of file localBlended.H.
References localBlended< Type >::blendingFactor(), localBlended< Type >::corrected(), localBlended< Type >::correction(), and surfaceInterpolationScheme< Type >::mesh().
Referenced by localBlended< Type >::correction().
The documentation for this class was generated from the following file:
src/finiteVolume/interpolation/surfaceInterpolation/schemes/localBlended/localBlended.H