OpenFOAM: spatialTransform Class Reference
spatialTransform Class Reference
Compact representation of the Plücker spatial transformation tensor in terms of the rotation tensor E and translation vector r .
#include <spatialTransform.H>
Classes
class dual
class transpose
Public Member Functions
spatialTransform ()
spatialTransform (const tensor &E, const vector &r)
spatialTransform (Istream &)
const tensor & E () const
tensor & E ()
const vector & r () const
vector & r ()
transpose T () const
spatialTransform inv () const
dual operator* () const
operator spatialTensor () const
void operator&= (const spatialTransform &X)
spatialTransform operator& (const spatialTransform &X) const
spatialVector operator& (const spatialVector &v) const
vector transformPoint (const vector &p) const
spatialVector operator&& (const spatialVector &v) const
Friends
Istream & operator>> (Istream &, spatialTransform &)
Ostream & operator<< (Ostream &, const spatialTransform &)
Detailed Description
Compact representation of the Plücker spatial transformation tensor in terms of the rotation tensor E and translation vector r .
See Chapter 2 and Appendix A in reference:
    Featherstone, R. (2008).
    Rigid body dynamics algorithms.
    Springer.
Source files
spatialTransform.H
spatialTransformI.H
Definition at line 62 of file spatialTransform.H.
Constructor & Destructor Documentation
spatialTransform() [1/3]
spatialTransform () inline
Definition at line 33 of file spatialTransformI.H.
Referenced by spatialTransform::inv(), and spatialTransform::operator&().
spatialTransform() [2/3]
spatialTransform (const tensor & E, const vector & r) inline
Definition at line 40 of file spatialTransformI.H.
spatialTransform() [3/3]
spatialTransform (Istream & is) inline
Definition at line 51 of file spatialTransformI.H.
Member Function Documentation
E() [1/2]
const Foam::tensor & E () const inline
Definition at line 72 of file spatialTransformI.H.
Referenced by Pxyz::jcalc(), Rs::jcalc(), Rxyz::jcalc(), Ryxz::jcalc(), Rzyx::jcalc(), Foam::operator>>(), and Foam::RBD::transform().
E() [2/2]
Foam::tensor & E () inline
Definition at line 77 of file spatialTransformI.H.
r() [1/2]
const Foam::vector & r () const inline
Definition at line 82 of file spatialTransformI.H.
Referenced by Pxyz::jcalc(), Rs::jcalc(), Rxyz::jcalc(), Ryxz::jcalc(), Rzyx::jcalc(), Foam::operator>>(), and Foam::RBD::transform().
r() [2/2]
Foam::vector & r () inline
Definition at line 87 of file spatialTransformI.H.
T()
Foam::spatialTransform::transpose T () const inline
Definition at line 93 of file spatialTransformI.H.
inv()
Foam::spatialTransform inv () const inline
Definition at line 99 of file spatialTransformI.H.
References spatialTransform::spatialTransform(), and Tensor< Cmpt >::T().
operator*()
Foam::spatialTransform::dual operator* () const inline
Definition at line 107 of file spatialTransformI.H.
operator spatialTensor()
operator spatialTensor () const inline
Definition at line 113 of file spatialTransformI.H.
References Foam::Zero.
operator&=()
void operator&= (const spatialTransform & X) inline
Definition at line 123 of file spatialTransformI.H.
operator&() [1/2]
Foam::spatialTransform operator& (const spatialTransform & X) const inline
Definition at line 130 of file spatialTransformI.H.
References spatialTransform::spatialTransform().
operator&() [2/2]
Foam::spatialVector operator& (const spatialVector & v) const inline
Definition at line 139 of file spatialTransformI.H.
transformPoint()
Foam::vector transformPoint (const vector & p) const inline
Definition at line 165 of file spatialTransformI.H.
References p.
Referenced by rigidBodyMotion::transformPoints(), and rigidBodyMotion::transformPoints().
operator&&()
Foam::spatialVector operator&& (const spatialVector & v) const inline
Definition at line 152 of file spatialTransformI.H.
Friends And Related Symbol Documentation
operator>>
Istream & operator>> (Istream & , spatialTransform &) friend
operator<<
Ostream & operator<< (Ostream & , const spatialTransform &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/spatialVectorAlgebra/spatialTransform/spatialTransform.H
src/OpenFOAM/primitives/spatialVectorAlgebra/spatialTransform/spatialTransformI.H