OpenFOAM: dynamicAlphaContactAngleFvPatchScalarField Class Reference
dynamicAlphaContactAngleFvPatchScalarField Class Reference
A dynamic alphaContactAngle scalar boundary condition (alphaContactAngleTwoPhaseFvPatchScalarField)
#include <dynamicAlphaContactAngleFvPatchScalarField.H>
Public Member Functions
TypeName ("dynamicAlphaContactAngle")
dynamicAlphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
dynamicAlphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
dynamicAlphaContactAngleFvPatchScalarField (const dynamicAlphaContactAngleFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
dynamicAlphaContactAngleFvPatchScalarField (const dynamicAlphaContactAngleFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
dynamicAlphaContactAngleFvPatchScalarField (const dynamicAlphaContactAngleFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual tmp< scalarField > theta (const fvPatchVectorField &Up, const fvsPatchVectorField &nHat) const
virtual void write (Ostream &) const
Public Member Functions inherited from alphaContactAngleTwoPhaseFvPatchScalarField
alphaContactAngleTwoPhaseFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
alphaContactAngleTwoPhaseFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
alphaContactAngleTwoPhaseFvPatchScalarField (const alphaContactAngleTwoPhaseFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
alphaContactAngleTwoPhaseFvPatchScalarField (const alphaContactAngleTwoPhaseFvPatchScalarField &)
alphaContactAngleTwoPhaseFvPatchScalarField (const alphaContactAngleTwoPhaseFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual void evaluate (const Pstream::commsTypes commsType=Pstream::commsTypes::blocking)
Additional Inherited Members
Public Types inherited from alphaContactAngleTwoPhaseFvPatchScalarField
enum limitControls { lcNone , lcGradient , lcZeroGradient , lcAlpha }
Public Attributes inherited from alphaContactAngleTwoPhaseFvPatchScalarField
limitControls limit_
Static Public Attributes inherited from alphaContactAngleTwoPhaseFvPatchScalarField
static const Enum< limitControls > limitControlNames_
Detailed Description
A dynamic alphaContactAngle scalar boundary condition (alphaContactAngleTwoPhaseFvPatchScalarField)
Source files
dynamicAlphaContactAngleFvPatchScalarField.H
dynamicAlphaContactAngleFvPatchScalarField.C
Definition at line 48 of file dynamicAlphaContactAngleFvPatchScalarField.H.
Constructor & Destructor Documentation
dynamicAlphaContactAngleFvPatchScalarField() [1/5]
dynamicAlphaContactAngleFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 29 of file dynamicAlphaContactAngleFvPatchScalarField.C.
dynamicAlphaContactAngleFvPatchScalarField() [2/5]
dynamicAlphaContactAngleFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 61 of file dynamicAlphaContactAngleFvPatchScalarField.C.
References alphaContactAngleTwoPhaseFvPatchScalarField::evaluate().
dynamicAlphaContactAngleFvPatchScalarField() [3/5]
dynamicAlphaContactAngleFvPatchScalarField (const dynamicAlphaContactAngleFvPatchScalarField & gcpsf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 44 of file dynamicAlphaContactAngleFvPatchScalarField.C.
dynamicAlphaContactAngleFvPatchScalarField() [4/5]
dynamicAlphaContactAngleFvPatchScalarField (const dynamicAlphaContactAngleFvPatchScalarField & gcpsf)
Definition at line 79 of file dynamicAlphaContactAngleFvPatchScalarField.C.
dynamicAlphaContactAngleFvPatchScalarField() [5/5]
dynamicAlphaContactAngleFvPatchScalarField (const dynamicAlphaContactAngleFvPatchScalarField & gcpsf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 93 of file dynamicAlphaContactAngleFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("dynamicAlphaContactAngle")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 108 of file dynamicAlphaContactAngleFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 124 of file dynamicAlphaContactAngleFvPatchScalarField.H.
theta()
Foam::tmp< Foam::scalarField > theta (const fvPatchVectorField & Up, const fvsPatchVectorField & nHat) const virtual
Implements alphaContactAngleTwoPhaseFvPatchScalarField.
Definition at line 111 of file dynamicAlphaContactAngleFvPatchScalarField.C.
References Foam::mag(), tmp< T >::New(), fvPatchField< Type >::patchInternalField(), and Foam::tanh().
write()
void write (Ostream & os) const virtual
Reimplemented from alphaContactAngleTwoPhaseFvPatchScalarField.
Definition at line 142 of file dynamicAlphaContactAngleFvPatchScalarField.C.
References os(), alphaContactAngleTwoPhaseFvPatchScalarField::write(), Ostream::writeEntry(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/transportModels/twoPhaseProperties/alphaContactAngle/dynamicAlphaContactAngle/dynamicAlphaContactAngleFvPatchScalarField.H
src/transportModels/twoPhaseProperties/alphaContactAngle/dynamicAlphaContactAngle/dynamicAlphaContactAngleFvPatchScalarField.C