OpenFOAM: sampledNone Class Reference
sampledNone Class Reference
A no operation sampledSurface that can be used when a sampler is expected but is not desired. For example, to temporarily disable a sampling definition, or to provide a boilerplate definition that is overwritten at a later stage in a dictionary.
#include <sampledNone.H>
Public Member Functions
TypeName ("sampledNone")
sampledNone ()
sampledNone (const word &name)
sampledNone (const word &name, const polyMesh &, const dictionary &)
virtual ~sampledNone ()=default
virtual bool needsUpdate () const
virtual bool expire ()
virtual bool update ()
virtual const pointField & points () const
virtual const faceList & faces () const
virtual const labelList & zoneIds () const
virtual const vectorField & Sf () const
virtual const scalarField & magSf () const
virtual const vectorField & Cf () const
virtual tmp< scalarField > sample (const interpolation< scalar > &sampler) const
virtual tmp< vectorField > sample (const interpolation< vector > &sampler) const
virtual tmp< sphericalTensorField > sample (const interpolation< sphericalTensor > &sampler) const
virtual tmp< symmTensorField > sample (const interpolation< symmTensor > &sampler) const
virtual tmp< tensorField > sample (const interpolation< tensor > &sampler) const
virtual tmp< scalarField > interpolate (const interpolation< scalar > &interpolator) const
virtual tmp< vectorField > interpolate (const interpolation< vector > &interpolator) const
virtual tmp< sphericalTensorField > interpolate (const interpolation< sphericalTensor > &interpolator) const
virtual tmp< symmTensorField > interpolate (const interpolation< symmTensor > &interpolator) const
virtual tmp< tensorField > interpolate (const interpolation< tensor > &interpolator) const
Public Member Functions inherited from MeshedSurface< face >
MeshedSurface ()
MeshedSurface (const MeshedSurface &surf)
MeshedSurface (const UnsortedMeshedSurface< face > &surf)
MeshedSurface (MeshedSurface &&surf)
MeshedSurface (UnsortedMeshedSurface< face > &&surf)
MeshedSurface (const pointField &pointLst, const UList< face > &faceLst, const UList< surfZone > &zoneLst)
MeshedSurface (pointField &&pointLst, List< face > &&faceLst, const UList< surfZone > &zoneLst)
MeshedSurface (const pointField &pointLst, const UList< face > &faceLst, const labelUList &zoneSizes=labelUList(), const UList< word > &zoneNames=UList< word >())
MeshedSurface (pointField &&pointLst, List< face > &&faceLst, const labelUList &zoneSizes=labelUList(), const UList< word > &zoneNames=UList< word >())
MeshedSurface (const polyBoundaryMesh &bMesh, const bool globalPoints=false)
MeshedSurface (const surfMesh &mesh)
MeshedSurface (const fileName &name)
MeshedSurface (const fileName &name, const word &fileType)
MeshedSurface (Istream &is)
MeshedSurface (const Time &runTime)
MeshedSurface (const Time &runTime, const word &surfName)
MeshedSurface (const IOobject &io, const dictionary &dict, const bool isGlobal=true)
MeshedSurface (const MeshedSurface< face > &surf)
MeshedSurface (MeshedSurface< face > &&surf)
bool read (const fileName &name, const word &fileType)
virtual bool read (const fileName &name)
virtual void write (const fileName &name, IOstreamOption streamOpt=IOstreamOption(), const dictionary &options=dictionary::null) const
virtual void write (const fileName &name, const word &fileType, IOstreamOption streamOpt=IOstreamOption(), const dictionary &options=dictionary::null) const
void write (const Time &runTime, const word &surfName=word::null) const
ClassName ("MeshedSurface")
declareRunTimeSelectionTable (autoPtr, MeshedSurface, fileExtension,(const fileName &name),(name))
virtual ~MeshedSurface ()
declareMemberFunctionSelectionTable (void, UnsortedMeshedSurface, write, fileExtension,(const fileName &name, const MeshedSurface< face > &surf, IOstreamOption streamOpt, const dictionary &options),(name, surf, streamOpt, options))
label size () const
const List< face > & surfFaces () const
const labelList & faceIds () const
const surfZoneList & surfZones () const
const vectorField & Sf () const
const scalarField & magSf () const
const vectorField & Cf () const
virtual void clear ()
virtual void addZones (const UList< surfZone > &, const bool cullEmpty=false)
virtual void addZones (const labelUList &sizes, const UList< word > &names, const bool cullEmpty=false)
virtual void addZones (const labelUList &sizes, const bool cullEmpty=false)
bool addZonesToFaces ()
bool addZonesToFaces ()
bool addZonesToFaces ()
virtual void removeZones ()
virtual void movePoints (const pointField &newPoints)
virtual void scalePoints (const scalar scaleFactor)
virtual void cleanup (const bool verbose)
virtual void compactPoints (labelList &pointMap=const_cast< labelList & >(labelList::null()))
virtual bool stitchFaces (const scalar tol=SMALL, const bool verbose=false)
virtual bool checkFaces (const bool verbose=false)
virtual label nTriangles () const
virtual label nTriangles (labelList &faceMap) const
virtual label triangulate ()
virtual label triangulate (labelList &faceMap)
void subsetMeshMap (const BoolListType &include, labelList &pointMap, labelList &faceMap) const
MeshedSurface subsetMesh (const UList< bool > &include, labelList &pointMap, labelList &faceMap) const
MeshedSurface subsetMesh (const bitSet &include, labelList &pointMap, labelList &faceMap) const
MeshedSurface subsetMesh (const UList< bool > &include) const
MeshedSurface subsetMesh (const bitSet &include) const
MeshedSurface subsetMesh (const wordRes &includeNames, const wordRes &excludeNames=wordRes()) const
void swap (MeshedSurface< face > &surf)
void transfer (pointField &pointLst, List< face > &faceLst)
void transfer (MeshedSurface< face > &surf)
void transfer (UnsortedMeshedSurface< face > &surf)
autoPtr< MeshedSurface< face > > releaseGeom ()
void swapFaces (List< face > &faces)
void swapPoints (pointField &points)
void writeStats (Ostream &os) const
void operator= (const MeshedSurface< face > &surf)
void operator= (MeshedSurface< face > &&surf)
operator MeshedSurfaceProxy< face > () const
Public Member Functions inherited from PrimitivePatch< FaceList, PointField >
PrimitivePatch (const FaceList &faces, const PointField &points)
PrimitivePatch (FaceList &&faces, const PointField &points)
PrimitivePatch (FaceList &faces, PointField &points, const bool reuse)
PrimitivePatch (const PrimitivePatch< FaceList, PointField > &pp)
virtual ~PrimitivePatch ()
void clearOut ()
void clearGeom ()
void clearTopology ()
void clearPatchMeshAddr ()
void swap (PrimitivePatch &)=delete
const Field< point_type > & points () const noexcept
label nFaces () const noexcept
label nPoints () const
label nEdges () const
const edgeList & edges () const
const edgeList::subList internalEdges () const
const edgeList::subList boundaryEdges () const
label nInternalEdges () const
label nBoundaryEdges () const
bool isInternalEdge (const label edgei) const
const labelList & boundaryPoints () const
const labelListList & faceFaces () const
const labelListList & edgeFaces () const
const labelListList & faceEdges () const
const labelListList & pointEdges () const
const labelListList & pointFaces () const
const List< face_type > & localFaces () const
labelList boundaryFaces () const
labelList uniqBoundaryFaces () const
const labelList & meshPoints () const
const Map< label > & meshPointMap () const
const Field< point_type > & localPoints () const
const labelList & localPointOrder () const
label whichPoint (const label gp) const
edge meshEdge (const label edgei) const
edge meshEdge (const edge &e) const
label findEdge (const edge &e) const
labelList meshEdges (const edgeList &allEdges, const labelListList &cellEdges, const labelList &faceCells) const
labelList meshEdges (const edgeList &allEdges, const labelListList &pointEdges) const
label meshEdge (const label edgei, const edgeList &allEdges, const labelListList &pointEdges) const
labelList meshEdges (const labelUList &edgeLabels, const edgeList &allEdges, const labelListList &pointEdges) const
const Field< point_type > & faceCentres () const
const Field< point_type > & faceAreas () const
const Field< scalar > & magFaceAreas () const
const Field< point_type > & faceNormals () const
const Field< point_type > & pointNormals () const
Pair< point_type > box () const
scalar sphere (const label facei) const
bool hasFaceAreas () const
bool hasFaceCentres () const
bool hasFaceNormals () const
bool hasPointNormals () const
bool hasBoundaryPoints () const
bool hasEdges () const
bool hasFaceFaces () const
bool hasEdgeFaces () const
bool hasFaceEdges () const
bool hasPointEdges () const
bool hasPointFaces () const
bool hasMeshPoints () const
bool hasMeshPointMap () const
template<class ToPatch >
List< objectHit > projectPoints (const ToPatch &targetPatch, const Field< point_type > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
template<class ToPatch >
List< objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< point_type > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
const labelListList & edgeLoops () const
surfaceTopo surfaceType (labelHashSet *badEdgesPtr=nullptr) const
bool checkTopology (const bool report=false, labelHashSet *pointSetPtr=nullptr) const
bool checkPointManifold (const bool report=false, labelHashSet *pointSetPtr=nullptr) const
virtual void movePoints (const Field< point_type > &)
void operator= (const PrimitivePatch< FaceList, PointField > &rhs)
void operator= (PrimitivePatch< FaceList, PointField > &&rhs)
label whichEdge (const edge &e) const
template<class ToPatch >
Foam::List< Foam::objectHit > projectPoints (const ToPatch &targetPatch, const Field< typename Foam::PrimitivePatch< FaceList, PointField >::point_type > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
template<class ToPatch >
Foam::List< Foam::objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< typename Foam::PrimitivePatch< FaceList, PointField >::point_type > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
Public Member Functions inherited from PrimitivePatchBase
ClassName ("PrimitivePatch")
PrimitivePatchBase ()=default
Public Member Functions inherited from surfaceFormatsCore
surfaceFormatsCore ()=default
virtual ~surfaceFormatsCore ()=default
Public Member Functions inherited from sampledSurface
TypeName ("sampledSurface")
declareRunTimeSelectionTable (autoPtr, sampledSurface, word,(const word &name, const polyMesh &mesh, const dictionary &dict),(name, mesh, dict))
sampledSurface (const word &name, const polyMesh &mesh, const bool interpolateToPoints=false)
sampledSurface (const word &name, const polyMesh &mesh, const dictionary &dict)
autoPtr< sampledSurface > clone () const
virtual ~sampledSurface ()
const polyMesh & mesh () const noexcept
const word & name () const noexcept
bool enabled () const noexcept
bool invariant () const noexcept
bool isPointData () const noexcept
virtual bool isPointData (const bool on)
scalar area () const
virtual bool hasFaceIds () const
polySurface * getRegistrySurface (const objectRegistry &obr, word lookupName="") const
polySurface * storeRegistrySurface (objectRegistry &obr, word lookupName="") const
bool removeRegistrySurface (objectRegistry &obr, word lookupName="") const
template<class Type , class GeoMeshType >
bool storeRegistryField (const objectRegistry &obr, const word &fieldName, const dimensionSet &dims, const Field< Type > &values, word lookupName="") const
template<class Type , class GeoMeshType >
bool storeRegistryField (const objectRegistry &obr, const word &fieldName, const dimensionSet &dims, Field< Type > &&values, word lookupName="") const
virtual bool withSurfaceFields () const
virtual tmp< scalarField > sample (const surfaceScalarField &sField) const
virtual tmp< vectorField > sample (const surfaceVectorField &sField) const
virtual tmp< sphericalTensorField > sample (const surfaceSphericalTensorField &sField) const
virtual tmp< symmTensorField > sample (const surfaceSymmTensorField &sField) const
virtual tmp< tensorField > sample (const surfaceTensorField &sField) const
virtual void rename (const word &newName)
virtual void print (Ostream &os, int level=0) const
bool interpolate () const noexcept
template<class Type >
Foam::tmp< Foam::Field< Type > > sampleOnFaces (const interpolation< Type > &sampler, const labelUList &elements, const faceList &fcs, const pointField &pts, const Type &defaultValue)
template<class Type >
Foam::tmp< Foam::Field< Type > > sampleOnPoints (const interpolation< Type > &interpolator, const labelUList &elements, const faceList &fcs, const pointField &pts)
template<class Type >
Foam::tmp< Foam::VolumeField< Type > > pointAverage (const PointField< Type > &pfld)
Public Member Functions inherited from meshedSurf
constexpr meshedSurf () noexcept=default
virtual ~meshedSurf ()=default
virtual const labelList & faceIds () const
Additional Inherited Members
Public Types inherited from MeshedSurface< face >
typedef face face_type
typedef point point_type
Public Types inherited from PrimitivePatch< FaceList, PointField >
enum surfaceTopo { MANIFOLD , OPEN , ILLEGAL }
typedef std::remove_reference< FaceList >::type::value_type face_type
typedef std::remove_reference< PointField >::type::value_type point_type
typedef FaceList FaceListType
typedef PointField PointFieldType
typedef face_type FaceType
Static Public Member Functions inherited from MeshedSurface< face >
static void write (const fileName &name, const MeshedSurface< face > &surf, IOstreamOption streamOpt=IOstreamOption(), const dictionary &options=dictionary::null)
static void write (const fileName &name, const word &fileType, const MeshedSurface< face > &surf, IOstreamOption streamOpt=IOstreamOption(), const dictionary &options=dictionary::null)
static wordHashSet readTypes ()
static wordHashSet writeTypes ()
static bool canReadType (const word &fileType, bool verbose=false)
static bool canWriteType (const word &fileType, bool verbose=false)
static bool canRead (const fileName &name, bool verbose=false)
static autoPtr< MeshedSurface > New (const fileName &name, const word &fileType, bool mandatory=true)
static autoPtr< MeshedSurface > New (const fileName &name)
Static Public Member Functions inherited from surfaceFormatsCore
static bool checkSupport (const wordHashSet &available, const word &fileType, const bool verbose=false, const char *functionName=nullptr)
static fileName findFile (const IOobject &io, const bool isGlobal=true)
static fileName findFile (const IOobject &io, const dictionary &dict, const bool isGlobal=true)
Static Public Member Functions inherited from sampledSurface
static autoPtr< sampledSurface > New (const word &name, const polyMesh &mesh, const dictionary &dict)
Static Public Attributes inherited from surfaceFormatsCore
static word nativeExt
Protected Member Functions inherited from MeshedSurface< face >
void transcribe (MeshedSurface< face > &surf)
void transcribe (MeshedSurface< face > &surf)
void transcribe (MeshedSurface< face > &surf)
void transcribe (MeshedSurface< face > &surf)
void checkZones (const bool verbose=true)
pointField & storedPoints ()
List< face > & storedFaces ()
labelList & storedFaceIds ()
surfZoneList & storedZones ()
void sortFacesAndStore (DynamicList< face > &unsortedFaces, DynamicList< label > &zoneIds, DynamicList< label > &elemIds, bool sorted)
virtual void remapFaces (const labelUList &faceMapNewToOld)
Protected Member Functions inherited from sampledSurface
virtual void clearGeom () const
sampledSurface (const word &name, std::nullptr_t)
Static Protected Member Functions inherited from surfaceFormatsCore
static string getLineNoComment (ISstream &is, const char comment='#')
template<class Container >
static List< surfZone > oneZone (const Container &container, const word &name="zone0")
static labelList getSelectedPatches (const surfZoneList &patches, const wordRes &allow, const wordRes &deny=wordRes())
static fileName relativeFilePath (const IOobject &io, const fileName &f, const bool isGlobal=true)
static fileName checkFile (const IOobject &io, const bool isGlobal=true)
static fileName checkFile (const IOobject &io, const dictionary &dict, const bool isGlobal=true)
Static Protected Member Functions inherited from sampledSurface
template<class Type >
static tmp< Field< Type > > sampleOnFaces (const interpolation< Type > &sampler, const labelUList &elements, const faceList &fcs, const pointField &pts, const Type &defaultValue=Type(Zero))
template<class Type >
static tmp< Field< Type > > sampleOnPoints (const interpolation< Type > &interpolator, const labelUList &elements, const faceList &fcs, const pointField &pts)
template<class Type >
static tmp< VolumeField< Type > > pointAverage (const PointField< Type > &pfld)
Detailed Description
A no operation sampledSurface that can be used when a sampler is expected but is not desired. For example, to temporarily disable a sampling definition, or to provide a boilerplate definition that is overwritten at a later stage in a dictionary.
Usage
Property Description Required Default
type 'none' yes
Source files
sampledNone.H
sampledNone.C
Definition at line 66 of file sampledNone.H.
Constructor & Destructor Documentation
sampledNone() [1/3]
sampledNone () explicit
Definition at line 37 of file sampledNone.C.
sampledNone() [2/3]
sampledNone (const word & name) explicit
Definition at line 43 of file sampledNone.C.
sampledNone() [3/3]
sampledNone (const word & name, const polyMesh & mesh, const dictionary & dict)
Definition at line 49 of file sampledNone.C.
~sampledNone()
virtual ~sampledNone () virtual default
Member Function Documentation
TypeName()
TypeName ("sampledNone")
needsUpdate()
bool needsUpdate () const virtual
Implements sampledSurface.
Definition at line 62 of file sampledNone.C.
expire()
bool expire () virtual
Implements sampledSurface.
Definition at line 68 of file sampledNone.C.
update()
bool update () virtual
Implements sampledSurface.
Definition at line 74 of file sampledNone.C.
points()
virtual const pointField & points () const inline virtual
Implements sampledSurface.
Definition at line 107 of file sampledNone.H.
References PrimitivePatch< FaceList, PointField >::points().
faces()
virtual const faceList & faces () const inline virtual
Implements sampledSurface.
Definition at line 113 of file sampledNone.H.
References MeshedSurface< face >::surfFaces().
zoneIds()
virtual const labelList & zoneIds () const inline virtual
Reimplemented from meshedSurf.
Definition at line 119 of file sampledNone.H.
References List< label >::null().
Sf()
virtual const vectorField & Sf () const inline virtual
Implements sampledSurface.
Definition at line 125 of file sampledNone.H.
References MeshedSurface< face >::Sf().
magSf()
virtual const scalarField & magSf () const inline virtual
Implements sampledSurface.
Definition at line 131 of file sampledNone.H.
References MeshedSurface< face >::magSf().
Cf()
virtual const vectorField & Cf () const inline virtual
Implements sampledSurface.
Definition at line 137 of file sampledNone.H.
References MeshedSurface< face >::Cf().
sample() [1/5]
Foam::tmp< Foam::Field< Foam::scalar > > sample (const interpolation< scalar > & sampler) const virtual
Implements sampledSurface.
Definition at line 88 of file sampledNone.C.
sample() [2/5]
Foam::tmp< Foam::Field< Foam::vector > > sample (const interpolation< vector > & sampler) const virtual
Implements sampledSurface.
Definition at line 89 of file sampledNone.C.
sample() [3/5]
Foam::tmp< Foam::Field< Foam::sphericalTensor > > sample (const interpolation< sphericalTensor > & sampler) const virtual
Implements sampledSurface.
Definition at line 90 of file sampledNone.C.
sample() [4/5]
Foam::tmp< Foam::Field< Foam::symmTensor > > sample (const interpolation< symmTensor > & sampler) const virtual
Implements sampledSurface.
Definition at line 91 of file sampledNone.C.
sample() [5/5]
Foam::tmp< Foam::Field< Foam::tensor > > sample (const interpolation< tensor > & sampler) const virtual
Implements sampledSurface.
Definition at line 92 of file sampledNone.C.
interpolate() [1/5]
Foam::tmp< Foam::Field< Foam::scalar > > interpolate (const interpolation< scalar > & interpolator) const virtual
Implements sampledSurface.
Definition at line 94 of file sampledNone.C.
interpolate() [2/5]
Foam::tmp< Foam::Field< Foam::vector > > interpolate (const interpolation< vector > & interpolator) const virtual
Implements sampledSurface.
Definition at line 95 of file sampledNone.C.
interpolate() [3/5]
Foam::tmp< Foam::Field< Foam::sphericalTensor > > interpolate (const interpolation< sphericalTensor > & interpolator) const virtual
Implements sampledSurface.
Definition at line 96 of file sampledNone.C.
interpolate() [4/5]
Foam::tmp< Foam::Field< Foam::symmTensor > > interpolate (const interpolation< symmTensor > & interpolator) const virtual
Implements sampledSurface.
Definition at line 97 of file sampledNone.C.
interpolate() [5/5]
Foam::tmp< Foam::Field< Foam::tensor > > interpolate (const interpolation< tensor > & interpolator) const virtual
Implements sampledSurface.
Definition at line 98 of file sampledNone.C.
The documentation for this class was generated from the following files:
src/sampling/sampledSurface/sampledNone/sampledNone.H
src/sampling/sampledSurface/sampledNone/sampledNone.C