OpenFOAM: averageCondition Class Reference
averageCondition Class Reference
Average run time condition - satisfied when average does not change by more than a given value.
#include <averageCondition.H>
Public Member Functions
TypeName ("average")
averageCondition (const word &name, const objectRegistry &obr, const dictionary &dict, stateFunctionObject &state)
virtual ~averageCondition ()=default
virtual bool apply ()
virtual void write ()
virtual void reset ()
Public Member Functions inherited from runTimeCondition
TypeName ("runTimeCondition")
declareRunTimeSelectionTable (autoPtr, runTimeCondition, dictionary,(const word &name, const objectRegistry &obr, const dictionary &dict, stateFunctionObject &state),(name, obr, dict, state))
runTimeCondition (const word &name, const objectRegistry &obr, const dictionary &dict, stateFunctionObject &state)
virtual ~runTimeCondition ()=default
virtual const word & name () const
virtual bool active () const
virtual label groupID () const
Public Member Functions inherited from valueAverageBase
valueAverageBase (const word &name, const objectRegistry &obr, const dictionary &dict, stateFunctionObject &state, const bool writeToFile=true)
valueAverageBase (const valueAverageBase &)=delete
void operator= (const valueAverageBase &)=delete
virtual ~valueAverageBase ()=default
virtual bool read (const dictionary &dict)
virtual bool calculate (dictionary &dict)
Public Member Functions inherited from writeFile
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name="undefined", const bool writeToFile=true)
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name, const dictionary &dict, const bool writeToFile=true)
writeFile (const writeFile &wf)
virtual ~writeFile ()=default
virtual OFstream & file ()
virtual bool writeToFile () const
virtual bool canWriteToFile () const
virtual bool canResetFile () const
virtual bool canWriteHeader () const
virtual label charWidth () const
virtual void writeCommented (Ostream &os, const string &str) const
virtual void writeTabbed (Ostream &os, const string &str) const
virtual void writeHeader (Ostream &os, const string &str) const
virtual void writeCurrentTime (Ostream &os) const
virtual void writeBreak (Ostream &os) const
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
template<class Type >
void writeValue (Ostream &os, const Type &val) const
Protected Attributes
label nIterStartUp_
label iter_
Protected Attributes inherited from runTimeCondition
word name_
const objectRegistry & obr_
stateFunctionObject & state_
bool active_
dictionary & conditionDict_
label groupID_
Protected Attributes inherited from valueAverageBase
bool resetOnRestart_
windowType windowType_
stateFunctionObject & state_
word functionObjectName_
wordList fieldNames_
scalar tolerance_
scalar window_
List< scalar > totalTime_
Protected Attributes inherited from writeFile
const objectRegistry & fileObr_
const fileName prefix_
word fileName_
autoPtr< OFstream > filePtr_
label writePrecision_
bool writeToFile_
bool updateHeader_
bool writtenHeader_
bool useUserTime_
scalar startTime_
Additional Inherited Members
Public Types inherited from valueAverageBase
enum class windowType : uint8_t { NONE , APPROXIMATE , EXACT }
Static Public Member Functions inherited from runTimeCondition
static autoPtr< runTimeCondition > New (const word &conditionName, const objectRegistry &obr, const dictionary &dict, stateFunctionObject &state)
Public Attributes inherited from runTimeCondition
Switch log
Static Public Attributes inherited from valueAverageBase
static const Enum< windowType > windowTypeNames
Static Public Attributes inherited from writeFile
static label addChars = 8
Protected Member Functions inherited from runTimeCondition
dictionary & setConditionDict ()
const dictionary & conditionDict () const
dictionary & conditionDict ()
Protected Member Functions inherited from valueAverageBase
template<class Type , class Type2 = Type>
bool calc (const label fieldi, bool &converged, dictionary &dict)
virtual void writeFileHeader (Ostream &os) const
virtual void readState (dictionary &dict)
virtual void writeState (dictionary &dict)
virtual void resetState (dictionary &dict)
Protected Member Functions inherited from writeFile
void initStream (Ostream &os) const
fileName baseFileDir () const
fileName baseTimeDir () const
fileName filePath (const fileName &fName) const
virtual autoPtr< OFstream > newFile (const fileName &fName) const
virtual autoPtr< OFstream > newFileAtTime (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > newFileAtStartTime (const word &name) const
virtual void resetFile (const word &name)
Omanip< int > valueWidth (const label offset=0) const
void operator= (const writeFile &)=delete
virtual autoPtr< OFstream > createFile (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > createFile (const word &name) const
Detailed Description
Average run time condition - satisfied when average does not change by more than a given value.
See also
Foam::functionObjects::valueAverageBase
Source files
averageCondition.H
averageCondition.H
averageCondition.C
Definition at line 56 of file averageCondition.H.
Constructor & Destructor Documentation
averageCondition()
averageCondition (const word & name, const objectRegistry & obr, const dictionary & dict, stateFunctionObject & state)
Definition at line 40 of file averageCondition.C.
References runTimeCondition::conditionDict(), averageCondition::iter_, Foam::name(), and valueAverageBase::readState().
~averageCondition()
virtual ~averageCondition () virtual default
Member Function Documentation
TypeName()
TypeName ("average")
apply()
bool apply () virtual
Implements runTimeCondition.
Definition at line 63 of file averageCondition.C.
References valueAverageBase::calculate(), Foam::decrIndent(), Foam::incrIndent(), and Foam::Info.
write()
void write () virtual
Implements runTimeCondition.
Definition at line 85 of file averageCondition.C.
References dictionary::set(), and valueAverageBase::writeState().
reset()
void reset () virtual
Implements runTimeCondition.
Definition at line 95 of file averageCondition.C.
References valueAverageBase::resetState().
Member Data Documentation
nIterStartUp_
label nIterStartUp_ protected
Definition at line 66 of file averageCondition.H.
iter_
label iter_ protected
Definition at line 69 of file averageCondition.H.
Referenced by averageCondition::averageCondition().
The documentation for this class was generated from the following files:
src/functionObjects/utilities/runTimeControl/runTimeCondition/averageCondition/averageCondition.H
src/functionObjects/utilities/runTimeControl/runTimeCondition/averageCondition/averageCondition.C