OpenFOAM: leastSquaresEdgeInterpolation< Type > Class Template Reference
leastSquaresEdgeInterpolation< Type > Class Template Reference
Least-squares edge interpolation scheme class, from face centers to points then from points to edges.
#include <leastSquaresEdgeInterpolation.H>
Public Member Functions
TypeName ("leastSquares")
leastSquaresEdgeInterpolation (const faMesh &mesh)
leastSquaresEdgeInterpolation (const faMesh &mesh, Istream &)
leastSquaresEdgeInterpolation (const faMesh &mesh, const edgeScalarField &, Istream &)
tmp< GeometricField< Type, faePatchField, edgeMesh > > interpolate (const GeometricField< Type, faPatchField, areaMesh > &) const
tmp< edgeScalarField > weights (const GeometricField< Type, faPatchField, areaMesh > &) const
Public Member Functions inherited from edgeInterpolationScheme< Type >
declareRunTimeSelectionTable (tmp, edgeInterpolationScheme, Mesh,(const faMesh &mesh, Istream &schemeData),(mesh, schemeData))
declareRunTimeSelectionTable (tmp, edgeInterpolationScheme, MeshFlux,(const faMesh &mesh, const edgeScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
edgeInterpolationScheme (const faMesh &mesh)
virtual ~edgeInterpolationScheme ()
const faMesh & mesh () const
virtual bool corrected () const
virtual tmp< GeometricField< Type, faePatchField, edgeMesh > > correction (const GeometricField< Type, faPatchField, areaMesh > &) const
virtual tmp< GeometricField< Type, faePatchField, edgeMesh > > euclidianInterpolate (const GeometricField< Type, faPatchField, areaMesh > &) const
tmp< GeometricField< Type, faePatchField, edgeMesh > > interpolate (const tmp< GeometricField< Type, faPatchField, areaMesh > > &) const
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Additional Inherited Members
Static Public Member Functions inherited from edgeInterpolationScheme< Type >
static tmp< edgeInterpolationScheme< Type > > New (const faMesh &mesh, Istream &schemeData)
static tmp< edgeInterpolationScheme< Type > > New (const faMesh &mesh, const edgeScalarField &faceFlux, Istream &schemeData)
static tmp< GeometricField< Type, faePatchField, edgeMesh > > interpolate (const GeometricField< Type, faPatchField, areaMesh > &, const tmp< edgeScalarField > &, const tmp< edgeScalarField > &)
static tmp< GeometricField< Type, faePatchField, edgeMesh > > interpolate (const GeometricField< Type, faPatchField, areaMesh > &, const tmp< edgeScalarField > &)
static tmp< GeometricField< Type, faePatchField, edgeMesh > > euclidianInterpolate (const GeometricField< Type, faPatchField, areaMesh > &, const tmp< edgeScalarField > &)
Detailed Description
template<class Type>
class Foam::leastSquaresEdgeInterpolation< Type >
Least-squares edge interpolation scheme class, from face centers to points then from points to edges.
References:
    Governing equations (tag:P):
        Pesci, C. (2019).
        Computational analysis of fluid interfaces
        influenced by soluble surfactant.
        Darmstadt, Technische Universität. PhD thesis.
        URI:https://tuprints.ulb.tu-darmstadt.de/id/eprint/9303
Source files
leastSquaresEdgeInterpolation.H
leastSquaresEdgeInterpolationMake.C
Definition at line 61 of file leastSquaresEdgeInterpolation.H.
Constructor & Destructor Documentation
leastSquaresEdgeInterpolation() [1/3]
template<class Type > leastSquaresEdgeInterpolation (const faMesh & mesh) inline
Definition at line 80 of file leastSquaresEdgeInterpolation.H.
leastSquaresEdgeInterpolation() [2/3]
template<class Type > leastSquaresEdgeInterpolation (const faMesh & mesh, Istream &) inline
Definition at line 86 of file leastSquaresEdgeInterpolation.H.
leastSquaresEdgeInterpolation() [3/3]
template<class Type > leastSquaresEdgeInterpolation (const faMesh & mesh, const edgeScalarField & , Istream &) inline
Definition at line 92 of file leastSquaresEdgeInterpolation.H.
Member Function Documentation
TypeName()
template<class Type > TypeName ("leastSquares")
interpolate()
template<class Type > tmp< GeometricField< Type, faePatchField, edgeMesh > > interpolate (const GeometricField< Type, faPatchField, areaMesh > & af) const virtual
Reimplemented from edgeInterpolationScheme< Type >.
Definition at line 125 of file leastSquaresEdgeInterpolation.H.
References PtrList< T >::clear(), UPtrList< T >::end(), forAll, gradScheme< Type >::grad(), Foam::mag(), Foam::max(), mesh, tmp< T >::New(), PtrList< T >::PtrList(), UPtrList< T >::size(), Foam::sum(), and Foam::Zero.
weights()
template<class Type > tmp< edgeScalarField > weights (const GeometricField< Type, faPatchField, areaMesh > &) const inline virtual
Implements edgeInterpolationScheme< Type >.
Definition at line 113 of file leastSquaresEdgeInterpolation.H.
References edgeInterpolationScheme< Type >::mesh().
The documentation for this class was generated from the following file:
src/finiteArea/interpolation/edgeInterpolation/schemes/leastSquares/leastSquaresEdgeInterpolation.H