OpenFOAM: chemistryReductionMethod< CompType, ThermoType > Class Template Reference
chemistryReductionMethod< CompType, ThermoType > Class Template Reference abstract
An abstract class for methods of chemical mechanism reduction.
#include <chemistryReductionMethod.H>
Public Member Functions
TypeName ("chemistryReductionMethod")
declareRunTimeSelectionTable (autoPtr, chemistryReductionMethod, dictionary,(const IOdictionary &dict, TDACChemistryModel< CompType, ThermoType > &chemistry),(dict, chemistry))
chemistryReductionMethod (const IOdictionary &dict, TDACChemistryModel< CompType, ThermoType > &chemistry)
virtual ~chemistryReductionMethod ()
bool active () const
bool log () const
const List< bool > & activeSpecies () const
label NsSimp ()
label nSpecie ()
scalar tolerance () const
virtual void reduceMechanism (const scalarField &c, const scalar T, const scalar p)=0
Static Public Member Functions
static autoPtr< chemistryReductionMethod< CompType, ThermoType > > New (const IOdictionary &dict, TDACChemistryModel< CompType, ThermoType > &chemistry)
Protected Attributes
const IOdictionary & dict_
const dictionary coeffsDict_
Switch active_
Switch log_
TDACChemistryModel< CompType, ThermoType > & chemistry_
List< bool > activeSpecies_
label NsSimp_
const label nSpecie_
scalar tolerance_
Detailed Description
template<class CompType, class ThermoType>
class Foam::chemistryReductionMethod< CompType, ThermoType >
An abstract class for methods of chemical mechanism reduction.
An abstract class for reducing chemical mechanisms.
Source files
chemistryReductionMethod.H
chemistryReductionMethod.C
Source files
chemistryReductionMethodI.H
chemistryReductionMethod.C
Definition at line 52 of file chemistryReductionMethod.H.
Constructor & Destructor Documentation
chemistryReductionMethod()
template<class CompType , class ThermoType > chemistryReductionMethod (const IOdictionary & dict, Foam::TDACChemistryModel< CompType, ThermoType > & chemistry)
Definition at line 28 of file chemistryReductionMethod.C.
~chemistryReductionMethod()
template<class CompType , class ThermoType > ~chemistryReductionMethod () virtual
Definition at line 49 of file chemistryReductionMethod.C.
Member Function Documentation
TypeName()
template<class CompType , class ThermoType > TypeName ("chemistryReductionMethod< CompType, ThermoType >")
declareRunTimeSelectionTable()
template<class CompType , class ThermoType > declareRunTimeSelectionTable (autoPtr , chemistryReductionMethod< CompType, ThermoType > , dictionary , (const IOdictionary &dict, TDACChemistryModel< CompType, ThermoType > &chemistry) , (dict, chemistry))
New()
template<class CompType , class ThermoType > Foam::autoPtr< Foam::chemistryReductionMethod< CompType, ThermoType > > New (const IOdictionary & dict, TDACChemistryModel< CompType, ThermoType > & chemistry) static
DynamicList<word> thisCmpts(6); thisCmpts.append(CompType::typeName); thisCmpts.append (basicThermo::splitThermoName(ThermoType::typeName(), 5));
DynamicList<word> validNames;
if (thisCmpts == SubList<word>(cmpts, 6, 1)) { validNames.append(cmpts[0]); }
Definition at line 29 of file chemistryReductionMethodNew.C.
References PtrList< T >::append(), dict, UPtrList< T >::empty(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInLookup, UPtrList< T >::get(), Foam::Info, Foam::nl, Foam::printTable(), PtrList< T >::PtrList(), UPtrList< T >::size(), and basicThermo::splitThermoName().
Referenced by TDACChemistryModel< ReactionThermo, ThermoType >::TDACChemistryModel().
active()
template<class CompType , class ThermoType > bool active () const inline
Definition at line 36 of file chemistryReductionMethodI.H.
log()
template<class CompType , class ThermoType > bool log () const inline
Definition at line 44 of file chemistryReductionMethodI.H.
activeSpecies()
template<class CompType , class ThermoType > const Foam::List< bool > & activeSpecies () const inline
Definition at line 52 of file chemistryReductionMethodI.H.
NsSimp()
template<class CompType , class ThermoType > Foam::label NsSimp () inline
Definition at line 60 of file chemistryReductionMethodI.H.
nSpecie()
template<class CompType , class ThermoType > Foam::label nSpecie () inline
Definition at line 68 of file chemistryReductionMethodI.H.
tolerance()
template<class CompType , class ThermoType > Foam::scalar tolerance () const inline
Definition at line 76 of file chemistryReductionMethodI.H.
reduceMechanism()
template<class CompType , class ThermoType > virtual void reduceMechanism (const scalarField & c, const scalar T, const scalar p) pure virtual
Implemented in DAC< CompType, ThermoType >, DRG< CompType, ThermoType >, DRGEP< CompType, ThermoType >, EFA< CompType, ThermoType >, none< CompType, ThermoType >, and PFA< CompType, ThermoType >.
Member Data Documentation
dict_
template<class CompType , class ThermoType > const IOdictionary& dict_ protected
Definition at line 57 of file chemistryReductionMethod.H.
coeffsDict_
template<class CompType , class ThermoType > const dictionary coeffsDict_ protected
Definition at line 60 of file chemistryReductionMethod.H.
Referenced by DAC< CompType, ThermoType >::DAC(), DRG< CompType, ThermoType >::DRG(), DRGEP< CompType, ThermoType >::DRGEP(), EFA< CompType, ThermoType >::EFA(), and PFA< CompType, ThermoType >::PFA().
active_
template<class CompType , class ThermoType > Switch active_ protected
Definition at line 63 of file chemistryReductionMethod.H.
Referenced by none< CompType, ThermoType >::none().
log_
template<class CompType , class ThermoType > Switch log_ protected
Definition at line 66 of file chemistryReductionMethod.H.
chemistry_
template<class CompType , class ThermoType > TDACChemistryModel<CompType, ThermoType>& chemistry_ protected
Definition at line 68 of file chemistryReductionMethod.H.
Referenced by DAC< CompType, ThermoType >::DAC(), DRGEP< CompType, ThermoType >::DRGEP(), and EFA< CompType, ThermoType >::EFA().
activeSpecies_
template<class CompType , class ThermoType > List<bool> activeSpecies_ protected
Definition at line 71 of file chemistryReductionMethod.H.
NsSimp_
template<class CompType , class ThermoType > label NsSimp_ protected
Definition at line 74 of file chemistryReductionMethod.H.
nSpecie_
template<class CompType , class ThermoType > const label nSpecie_ protected
Definition at line 77 of file chemistryReductionMethod.H.
Referenced by DAC< CompType, ThermoType >::DAC(), DRGEP< CompType, ThermoType >::DRGEP(), and EFA< CompType, ThermoType >::EFA().
tolerance_
template<class CompType , class ThermoType > scalar tolerance_ protected
Definition at line 80 of file chemistryReductionMethod.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/chemistryModel/chemistryModel/TDACChemistryModel/reduction/chemistryReductionMethod/chemistryReductionMethod.H
src/thermophysicalModels/chemistryModel/chemistryModel/TDACChemistryModel/reduction/chemistryReductionMethod/chemistryReductionMethod.C
src/thermophysicalModels/chemistryModel/chemistryModel/TDACChemistryModel/reduction/chemistryReductionMethod/chemistryReductionMethodI.H
src/thermophysicalModels/chemistryModel/chemistryModel/TDACChemistryModel/reduction/chemistryReductionMethod/chemistryReductionMethodNew.C