OpenFOAM: decompositionInformation Class Reference
decompositionInformation Class Reference
Abstract base class for decomposition.
#include <decompositionInformation.H>
Public Member Functions
decompositionInformation (const labelUList &adjncy, const labelUList &xadj, const labelUList &decomp, const label nDomains)
decompositionInformation (const CompactListList< label > &cellCells, const labelUList &decomp, const label nDomains)
~decompositionInformation ()=default
void clear ()
label nDomains () const noexcept
void printSummary (Ostream &os) const
void printDetails (Ostream &os) const
void printAll (Ostream &os) const
Detailed Description
Abstract base class for decomposition.
Source files
decompositionInformation.H
decompositionInformation.C
Definition at line 46 of file decompositionInformation.H.
Constructor & Destructor Documentation
decompositionInformation() [1/2]
decompositionInformation (const labelUList & adjncy, const labelUList & xadj, const labelUList & decomp, const label nDomains)
Definition at line 114 of file decompositionInformation.C.
References decompositionInformation::nDomains().
decompositionInformation() [2/2]
decompositionInformation (const CompactListList< label > & cellCells, const labelUList & decomp, const label nDomains)
Definition at line 129 of file decompositionInformation.C.
References decompositionInformation::nDomains().
~decompositionInformation()
~decompositionInformation () default
Member Function Documentation
clear()
void clear ()
Definition at line 145 of file decompositionInformation.C.
References PtrList< T >::clear().
nDomains()
label nDomains () const inline noexcept
Definition at line 125 of file decompositionInformation.H.
Referenced by decompositionInformation::decompositionInformation(), and decompositionInformation::decompositionInformation().
printSummary()
void printSummary (Ostream & os) const
Definition at line 154 of file decompositionInformation.C.
References Foam::nl, os(), and OFstream::print().
printDetails()
void printDetails (Ostream & os) const
Definition at line 162 of file decompositionInformation.C.
References forAll, n, Foam::nl, and os().
printAll()
void printAll (Ostream & os) const
Definition at line 211 of file decompositionInformation.C.
References os().
The documentation for this class was generated from the following files:
src/parallel/decompose/decompose/decompositionInformation.H
src/parallel/decompose/decompose/decompositionInformation.C