OpenFOAM: pointToPointPlanarInterpolation Class Reference
pointToPointPlanarInterpolation Class Reference
Interpolates between two sets of unstructured points using 2D Delaunay triangulation. Used in e.g. timeVaryingMapped bcs.
#include <pointToPointPlanarInterpolation.H>
Public Member Functions
ClassName ("pointToPointPlanarInterpolation")
pointToPointPlanarInterpolation (const pointToPointPlanarInterpolation &)=default
pointToPointPlanarInterpolation & operator= (const pointToPointPlanarInterpolation &)=default
pointToPointPlanarInterpolation (const pointField &sourcePoints, const pointField &destPoints, const scalar perturb, const bool nearestOnly=false)
pointToPointPlanarInterpolation (const coordinateSystem &referenceCS, const pointField &sourcePoints, const pointField &destPoints, const scalar perturb)
pointToPointPlanarInterpolation (const scalar perturb, const bool nearestOnly, const coordinateSystem &referenceCS, const label sourceSize, List< FixedList< label, 3 > > &&nearestVertex, List< FixedList< scalar, 3 > > &&nearestVertexWeight)
autoPtr< pointToPointPlanarInterpolation > clone () const
scalar perturb () const noexcept
bool nearestOnly () const noexcept
const coordSystem::cartesian & referenceCS () const noexcept
label sourceSize () const noexcept
label targetSize () const noexcept
const List< FixedList< label, 3 > > & nearestVertex () const noexcept
const List< FixedList< scalar, 3 > > & nearestVertexWeight () const noexcept
template<class Type >
tmp< Field< Type > > interpolate (const Field< Type > &sourceFld) const
template<class Type >
tmp< Field< Type > > interpolate (const tmp< Field< Type > > &tsource) const
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolate (const Field< Type > &sourceFld) const
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolate (const tmp< Field< Type > > &tsource) const
Static Public Member Functions
static wordList timeNames (const instantList &times)
Detailed Description
Interpolates between two sets of unstructured points using 2D Delaunay triangulation. Used in e.g. timeVaryingMapped bcs.
Source files
pointToPointPlanarInterpolation.H
pointToPointPlanarInterpolation.C
Definition at line 51 of file pointToPointPlanarInterpolation.H.
Constructor & Destructor Documentation
pointToPointPlanarInterpolation() [1/4]
pointToPointPlanarInterpolation (const pointToPointPlanarInterpolation &) default
pointToPointPlanarInterpolation() [2/4]
pointToPointPlanarInterpolation (const pointField & sourcePoints, const pointField & destPoints, const scalar perturb, const bool nearestOnly = false)
Definition at line 315 of file pointToPointPlanarInterpolation.C.
References pointToPointPlanarInterpolation::nearestOnly().
pointToPointPlanarInterpolation() [3/4]
pointToPointPlanarInterpolation (const coordinateSystem & referenceCS, const pointField & sourcePoints, const pointField & destPoints, const scalar perturb)
Definition at line 336 of file pointToPointPlanarInterpolation.C.
pointToPointPlanarInterpolation() [4/4]
pointToPointPlanarInterpolation (const scalar perturb, const bool nearestOnly, const coordinateSystem & referenceCS, const label sourceSize, List< FixedList< label, 3 > > && nearestVertex, List< FixedList< scalar, 3 > > && nearestVertexWeight)
Definition at line 353 of file pointToPointPlanarInterpolation.C.
Member Function Documentation
ClassName()
ClassName ("pointToPointPlanarInterpolation")
operator=()
pointToPointPlanarInterpolation & operator= (const pointToPointPlanarInterpolation &) default
clone()
autoPtr< pointToPointPlanarInterpolation > clone () const inline
Definition at line 144 of file pointToPointPlanarInterpolation.H.
References autoPtr< T >::New().
perturb()
scalar perturb () const inline noexcept
Definition at line 153 of file pointToPointPlanarInterpolation.H.
nearestOnly()
bool nearestOnly () const inline noexcept
Definition at line 159 of file pointToPointPlanarInterpolation.H.
Referenced by pointToPointPlanarInterpolation::pointToPointPlanarInterpolation().
referenceCS()
const coordSystem::cartesian & referenceCS () const inline noexcept
Definition at line 165 of file pointToPointPlanarInterpolation.H.
sourceSize()
label sourceSize () const inline noexcept
Definition at line 171 of file pointToPointPlanarInterpolation.H.
targetSize()
label targetSize () const inline noexcept
Definition at line 177 of file pointToPointPlanarInterpolation.H.
References UPtrList< T >::size().
nearestVertex()
const List< FixedList< label, 3 > > & nearestVertex () const inline noexcept
Definition at line 183 of file pointToPointPlanarInterpolation.H.
nearestVertexWeight()
const List< FixedList< scalar, 3 > > & nearestVertexWeight () const inline noexcept
Definition at line 189 of file pointToPointPlanarInterpolation.H.
timeNames()
Foam::wordList timeNames (const instantList & times) static
Definition at line 374 of file pointToPointPlanarInterpolation.C.
References forAll, and UList< T >::size().
interpolate() [1/4]
template<class Type > tmp< Field< Type > > interpolate (const Field< Type > & sourceFld) const
interpolate() [2/4]
template<class Type > tmp< Field< Type > > interpolate (const tmp< Field< Type > > & tsource) const
interpolate() [3/4]
template<class Type > Foam::tmp< Foam::Field< Type > > interpolate (const Field< Type > & sourceFld) const
Definition at line 28 of file pointToPointPlanarInterpolationTemplates.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, fld(), forAll, Foam::New(), and UPtrList< T >::size().
interpolate() [4/4]
template<class Type > Foam::tmp< Foam::Field< Type > > interpolate (const tmp< Field< Type > > & tsource) const
Definition at line 80 of file pointToPointPlanarInterpolationTemplates.C.
References PtrList< T >::clear(), and Foam::interpolate().
The documentation for this class was generated from the following files:
src/meshTools/triSurface/triSurfaceTools/pointToPointPlanarInterpolation.H
src/meshTools/triSurface/triSurfaceTools/pointToPointPlanarInterpolation.C
src/meshTools/triSurface/triSurfaceTools/pointToPointPlanarInterpolationTemplates.C