OpenFOAM: tmp< T > Class Template Reference
tmp< T > Class Template Reference
A class for managing temporary objects.
#include <tmp.H>
Public Types
typedef T element_type
typedef T * pointer
typedef Foam::refCount refCount
Public Member Functions
constexpr tmp () noexcept
constexpr tmp (std::nullptr_t) noexcept
tmp (T *p)
tmp (bool immovable, T *p)
constexpr tmp (const T &obj) noexcept
tmp (tmp< T > &&rhs) noexcept
tmp (const tmp< T > &&rhs) noexcept
tmp (const tmp< T > &rhs)
tmp (const tmp< T > &rhs, bool reuse)
tmp (const autoPtr< T > &)=delete
tmp (const refPtr< T > &)=delete
tmp (autoPtr< T > &&rhs) noexcept
~tmp () noexcept
bool good () const noexcept
bool is_const () const noexcept
bool is_pointer () const noexcept
bool is_reference () const noexcept
bool movable () const noexcept
T * get () noexcept
const T * get () const noexcept
const T & cref () const
T & ref () const
T & constCast () const
T * ptr () const
void clear () const noexcept
void reset (tmp< T > &&other) noexcept
void reset (T *p=nullptr) noexcept
void reset (bool immovable, T *p) noexcept
void reset (const autoPtr< T > &)=delete
void reset (const refPtr< T > &)=delete
void cref (const tmp< T > &other) noexcept
void cref (const T &obj) noexcept
void cref (const T *p) noexcept
void cref (const autoPtr< T > &)=delete
void cref (const refPtr< T > &)=delete
void ref (T &obj) noexcept
void ref (T *p) noexcept
void ref (const autoPtr< T > &)=delete
void ref (const refPtr< T > &)=delete
void swap (tmp< T > &other) noexcept
const T * operator-> () const
T * operator-> ()
const T & operator() () const
operator bool () const noexcept
operator const T & () const
void operator= (const tmp< T > &other)
void operator= (tmp< T > &&other) noexcept
void operator= (T *p)
void operator= (std::nullptr_t) noexcept
bool valid () const noexcept
bool isTmp () const noexcept
bool empty () const noexcept
Static Public Member Functions
template<class... Args>
static tmp< T > New (Args &&... args)
template<class... Args>
static tmp< T > NewImmovable (bool immovable, Args &&... args)
template<class U , class... Args>
static tmp< T > NewFrom (Args &&... args)
static word typeName ()
Detailed Description
template<class T>
class Foam::tmp< T >
A class for managing temporary objects.
This is a combination of std::shared_ptr (with intrusive ref-counting) and a shared_ptr without ref-counting and null deleter. This allows the tmp to double as a pointer management and an indirect pointer to externally allocated objects. In contrast to std::shared_ptr, only a limited number of tmp items will ever share a pointer.
Source files
tmp.H
tmpI.H
See also
Foam::autoPtr Foam::refPtr Foam::refCount
Definition at line 65 of file tmp.H.
Member Typedef Documentation
element_type
template<class T > typedef T element_type
Definition at line 97 of file tmp.H.
pointer
template<class T > typedef T* pointer
Definition at line 100 of file tmp.H.
refCount
template<class T > typedef Foam::refCount refCount
Definition at line 104 of file tmp.H.
Constructor & Destructor Documentation
tmp() [1/12]
template<class T > constexpr tmp () inline constexpr noexcept
Definition at line 54 of file tmpI.H.
tmp() [2/12]
template<class T > constexpr tmp (std::nullptr_t) inline constexpr noexcept
Definition at line 62 of file tmpI.H.
tmp() [3/12]
template<class T > tmp (T * p) inline explicit
Definition at line 70 of file tmpI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and tmp< T >::typeName().
tmp() [4/12]
template<class T > tmp (bool immovable, T * p) inline
Definition at line 87 of file tmpI.H.
tmp() [5/12]
template<class T > constexpr tmp (const T & obj) inline constexpr noexcept
Definition at line 96 of file tmpI.H.
tmp() [6/12]
template<class T > tmp (tmp< T > && rhs) inline noexcept
Definition at line 104 of file tmpI.H.
tmp() [7/12]
template<class T > tmp (const tmp< T > && rhs) inline noexcept
Definition at line 115 of file tmpI.H.
tmp() [8/12]
template<class T > tmp (const tmp< T > & rhs) inline
Definition at line 126 of file tmpI.H.
tmp() [9/12]
template<class T > tmp (const tmp< T > & rhs, bool reuse) inline
Definition at line 150 of file tmpI.H.
tmp() [10/12]
template<class T > tmp (const autoPtr< T > &) delete
tmp() [11/12]
template<class T > tmp (const refPtr< T > &) delete
tmp() [12/12]
template<class T > tmp (autoPtr< T > && rhs) inline explicit noexcept
Definition at line 182 of file tmpI.H.
~tmp()
template<class T > ~tmp () inline noexcept
Definition at line 191 of file tmpI.H.
References clear().
Member Function Documentation
New()
template<class T > template<class... Args> static tmp< T > New (Args &&... args) inline static
Definition at line 166 of file tmp.H.
References args, and T.
Referenced by lookup::a(), solidAbsorption::a(), boundaryRadiationProperties::absorptivity(), scene::addColourToMesh(), viscousDissipation::addSup(), adjointLaminar::adjointMeanFlowSource(), adjointSimple::adjointSimple(), boundaryAdjointContribution::adjointTMVariable1Source(), boundaryAdjointContribution::adjointTMVariable2Source(), acousticWaveTransmissiveFvPatchField< Type >::advectionSpeed(), pairGAMGAgglomeration::agglomerate(), GAMGInterface::agglomerateCoeffs(), StaticPhaseModel< BasePhaseModel >::alphaPhi(), ThermalDiffusivity< BasicTurbulenceModel >::alphat(), sensitivityVolBSplinesFI::assembleSensitivities(), variablesSet::autoCreateMeshMovementField(), adjointkOmegaSST::beta(), adjointkOmegaSST::beta(), kOmegaSSTBase< BasicEddyViscosityModel >::beta(), blendingFactor::blendingFactor(), alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField::calcAlphat(), atmNutkWallFunctionFvPatchScalarField::calcNut(), atmNutUWallFunctionFvPatchScalarField::calcNut(), atmNutWallFunctionFvPatchScalarField::calcNut(), nutkRoughWallFunctionFvPatchScalarField::calcNut(), nutkWallFunctionFvPatchScalarField::calcNut(), nutLowReWallFunctionFvPatchScalarField::calcNut(), nutUWallFunctionFvPatchScalarField::calcNut(), MassTransferPhaseSystem< BasePhaseSystem >::calculateL(), nutUTabulatedWallFunctionFvPatchScalarField::calcUPlus(), nutkFilmWallFunctionFvPatchScalarField::calcUTau(), nutUBlendedWallFunctionFvPatchScalarField::calcUTau(), nutUSpaldingWallFunctionFvPatchScalarField::calcUTau(), nutUWallFunctionFvPatchScalarField::calcYPlus(), deltaBoundary::cellCenters_d(), primitiveMeshTools::cellDeterminant(), treeDataFace::centres(), treeDataCell::centres(), treeDataEdge::centres(), treeDataPoint::centres(), kOmegaSST::computeG(), incompressibleAdjointSolver::computeGradDxDbMultiplier(), adjointEikonalSolver::computeYPhi(), polyLine::concat(), searchableBox::coordinates(), searchableCone::coordinates(), searchableCylinder::coordinates(), searchableDisk::coordinates(), searchablePlane::coordinates(), searchablePlate::coordinates(), searchableSphere::coordinates(), searchableSurfaceCollection::coordinates(), triSurfaceMesh::coordinates(), NURBS3DVolume::coordinates(), contactAngleForce::correct(), ReynoldsAnalogy::Cp(), twoPhaseMixtureThermo::Cp(), multiphaseMixtureThermo::Cp(), twoPhaseMixtureEThermo::Cp(), multiphaseInterSystem::Cp(), heThermo< BasicThermo, MixtureType >::Cp(), cellCellStencil::createField(), multiSolidBodyMotionSolver::curPoints(), solidBodyMotionSolver::curPoints(), displacementMeshMoverMotionSolver::curPoints(), triSurfaceTools::curvatures(), filmTurbulenceModel::Cw(), faMatrix< Type >::D(), fvMatrix< Type >::D(), MRFZoneList::DDt(), cyclicFaPatch::delta(), cyclicACMIFvPatch::delta(), cyclicAMIFvPatch::delta(), basicFvGeometryScheme::deltaCoeffs(), DESModelRegions::DESModelRegions(), RASModelVariables::devReff(), adjointkOmegaSST::devReff(), adjointSpalartAllmaras::devReff(), InterfaceCompositionModel< Thermo, OtherThermo >::Dfrom(), MovingPhaseModel< BasePhaseModel >::diffNo(), boundaryRadiationProperties::diffReflectivity(), solarCalculator::diffuseSolarRad(), adjointRASModel::diffusionCoeffVar1(), adjointRASModel::diffusionCoeffVar2(), adjointkOmegaSST::distanceSensitivities(), adjointLaminar::distanceSensitivities(), adjointSpalartAllmaras::distanceSensitivities(), momentumError::divDevRhoReff(), boundaryAdjointContribution::dJdGradU(), boundaryAdjointContribution::dJdnut(), kL< BasicTurbulenceModel >::DkEff(), kOmegaSSTBase< BasicEddyViscosityModel >::DkEff(), MassTransferPhaseSystem< BasePhaseSystem >::dmdt(), Bezier::dndbBasedSensitivities(), Bezier::dndbBasedSensitivities(), adjointSpalartAllmaras::DnuTildaEff(), SpalartAllmarasBase< BasicEddyViscosityModel >::DnuTildaEff(), kOmegaSSTBase< BasicEddyViscosityModel >::DomegaEff(), kEpsilonPhitF< BasicTurbulenceModel >::DphitEff(), multiphaseMangrovesSource::dragCoeff(), surfactantProperties::dSigma(), InterfaceCompositionModel< Thermo, OtherThermo >::Dto(), Bezier::dxdbFace(), Bezier::dxdbFace(), adjointRotatingWallVelocityFvPatchVectorField::dxdbMult(), lookup::e(), solidAbsorption::e(), faMesh::edgeLengthCorrection(), faPatch::edgeNormals(), PatchTools::edgeNormals(), cloudAbsorptionEmission::eDisp(), boundaryRadiationProperties::emissivity(), SpalartAllmarasBase< BasicEddyViscosityModel >::epsilon(), laminarModel< BasicTurbulenceModel >::epsilon(), LESModel< BasicTurbulenceModel >::epsilon(), sigma< BasicTurbulenceModel >::epsilon(), RASModel< BasicTurbulenceModel >::epsilon(), multiphaseMangrovesTurbulenceModel::epsilonCoeff(), age::execute(), energyTransport::execute(), boundedBackwardFaDdtScheme::facDdt(), boundBox::faceCentres(), primitiveMeshTools::faceConcavity(), primitiveMeshTools::faceFlatness(), polyMeshTools::faceOrthogonality(), primitiveMeshTools::faceOrthogonality(), mappedPatchBase::facePoints(), polyMeshTools::faceSkewness(), primitiveMeshTools::faceSkewness(), polyMeshTools::faceWeights(), DESModel< BasicTurbulenceModel >::fd(), parseDriver::field_cellCentre(), parseDriver::field_cellSelection(), parseDriver::field_faceSelection(), parseDriver::field_rand(), NURBS3DSurface::findClosestSurfacePoint(), adjointLaminar::FISensitivityTerm(), adjointSpalartAllmaras::FISensitivityTerm(), fft::forwardTransform(), fft::forwardTransform(), interfaceTrackingFvMesh::freeSurfacePressureJump(), interfaceTrackingFvMesh::freeSurfaceSnGradU(), interfaceTrackingFvMesh::freeSurfaceSnGradUn(), noiseFFT::frequencies(), SpalartAllmarasBase< BasicEddyViscosityModel >::ft2(), adjointkOmegaSST::gamma(), adjointkOmegaSST::gamma(), kOmegaSSTBase< BasicEddyViscosityModel >::gamma(), kOmegaSSTBase< BasicEddyViscosityModel >::GbyNu0(), multiphaseInterSystem::generatePhi(), Foam::getBoundedColours(), Foam::getField(), ATCstandard::getFISensitivityTerm(), cancelATC::getFISensitivityTerm(), InterfaceCompositionModel< Thermo, OtherThermo >::getSpecieMassFraction(), InterfaceCompositionModel< Thermo, OtherThermo >::getSpecieMassFraction(), blockMesh::globalPosition(), adjointEikonalSolver::gradEikonal(), transformFaPatchField< Type >::gradientInternalCoeffs(), transformFvPatchField< Type >::gradientInternalCoeffs(), lduMatrix::H1(), faMesh::haloFaceCentres(), faMesh::haloFaceNormals(), MassTransferPhaseSystem< BasePhaseSystem >::heatTransfer(), boundBox::hexCorners(), turbulenceFields::I(), multiphaseMangrovesSource::inertiaCoeff(), rotorDiskSource::inflowVelocity(), cyclicFaPatch::interfaceInternalField(), processorFaPatch::interfaceInternalField(), cyclicFvPatch::interfaceInternalField(), cyclicACMIFvPatch::interfaceInternalField(), cyclicAMIFvPatch::interfaceInternalField(), processorFvPatch::interfaceInternalField(), lduPrimitiveProcessorInterface::interfaceInternalField(), oversetFvPatch::interfaceInternalField(), cyclicACMIGAMGInterface::internalFieldTransfer(), cyclicGAMGInterface::internalFieldTransfer(), oversetGAMGInterface::internalFieldTransfer(), oversetFvPatch::internalFieldTransfer(), calculatedProcessorGAMGInterface::internalFieldTransfer(), oversetFvPatch::internalFieldTransfer(), AssemblyFvPatch< CyclicType >::internalFieldTransfer(), cyclicFaPatch::internalFieldTransfer(), leastSquaresEdgeInterpolation< Type >::interpolate(), Foam::inv(), Foam::inv(), coordinateSystem::invTransformPointImpl(), SpalartAllmarasBase< BasicEddyViscosityModel >::k(), laminarModel< BasicTurbulenceModel >::k(), sigma< BasicTurbulenceModel >::k(), interface::K(), multiphaseInterSystem::kappaEff(), multiphaseInterSystem::kappaEff(), multiphaseMangrovesTurbulenceModel::kCoeff(), diffusionGasEvaporation< Thermo, OtherThermo >::Kexp(), interfaceHeatResistance< Thermo, OtherThermo >::Kexp(), interfaceOxideRate< Thermo, OtherThermo >::Kexp(), kL< BasicTurbulenceModel >::kSource(), kOmegaSSTBase< BasicEddyViscosityModel >::kSource(), interfaceHeatResistance< Thermo, OtherThermo >::KSu(), turbulenceFields::L(), InterfaceCompositionModel< Thermo, OtherThermo >::L(), kOmegaSSTDES< BasicTurbulenceModel >::LESRegion(), SpalartAllmarasDES< BasicTurbulenceModel >::LESRegion(), LimitedScheme< Type, Limiter, LimitFunc >::limiter(), upwind< Type >::limiter(), cylindrical::localToGlobal(), meshRefinement::makeDisplacementField(), speciesSorptionFvPatchScalarField::mass(), noiseModel::meanPf(), incompressibleTwoPhaseMixture::mu(), incompressibleTwoPhaseMixture::muf(), laminar::mut(), InterfaceCompositionModel< Thermo, OtherThermo >::MwMixture(), multiphaseInterSystem::nearInterface(), processorFaPatch::neighbEdgeNormals(), faPatch::ngbPolyPatchFaceNormals(), faPatch::ngbPolyPatchPointNormals(), basicFvGeometryScheme::nonOrthCorrectionVectors(), basicFvGeometryScheme::nonOrthDeltaCoeffs(), limitTurbulenceViscosity::nu(), adjointTurbulenceModel::nuEff(), incompressibleTwoPhaseMixture::nuf(), Stokes< BasicTurbulenceModel >::nut(), generalizedNewtonian< BasicMomentumTransportModel >::nut(), turbulenceFields::nuTilda(), adjointRASModel::nutJacobianTMVar1(), adjointRASModel::nutJacobianTMVar2(), RASModelVariables::nutJacobianVar1(), SpalartAllmaras::nutJacobianVar1(), RASModelVariables::nutJacobianVar2(), noiseModel::octaves(), SpalartAllmarasBase< BasicEddyViscosityModel >::omega(), laminarModel< BasicTurbulenceModel >::omega(), LESModel< BasicTurbulenceModel >::omega(), RASModel< BasicTurbulenceModel >::omega(), kOmegaSSTBase< BasicEddyViscosityModel >::omegaSource(), NURBS3DVolume::patchDxDb(), NURBS3DVolume::patchDxDbFace(), enthalpySorptionFvPatchScalarField::patchSource(), speciesSorptionFvPatchScalarField::patchSource(), noiseModel::Pf(), noiseFFT::Pf(), StaticPhaseModel< BasePhaseModel >::phi(), semiPermeableBaffleMassFractionFvPatchScalarField::phiY(), PatchTools::pointNormals(), searchableCone::points(), searchableCylinder::points(), searchablePlate::points(), searchableSurfaceCollection::points(), treeBoundBox::points(), projectCurveEdge::position(), projectEdge::position(), blockEdge::position(), PhaseCompressibleTurbulenceModel< TransportModel >::pPrime(), PhaseIncompressibleTurbulenceModel< TransportModel >::pPrime(), PhaseCompressibleTurbulenceModel< TransportModel >::pPrimef(), PhaseIncompressibleTurbulenceModel< TransportModel >::pPrimef(), filmTurbulenceModel::primaryRegionFriction(), noiseModel::PSDf(), SpalartAllmarasDES< BasicTurbulenceModel >::psi(), noCombustion< ReactionThermo >::Qdot(), kOmegaSSTBase< BasicEddyViscosityModel >::Qsas(), dummy::R(), laminarModel< BasicTurbulenceModel >::R(), adjointSpalartAllmaras::r(), lookup::rDiff(), opaqueDiffusive::rDiff(), transparent::rDiff(), reader::readField(), fft::realTransform1D(), pointFieldReconstructor::reconstructField(), lduMatrix::residual(), fft::reverseTransform(), fft::reverseTransform(), forces::rho(), filmTurbulenceModel::rho(), ReynoldsAnalogy::rho(), forces::rho(), twoPhaseMixtureThermo::rhoEoS(), multiphaseMixtureThermo::rhoEoS(), twoPhaseMixtureEThermo::rhoEoS(), heThermo< BasicThermo, MixtureType >::rhoEoS(), coordinateSystem::rotationsImpl(), noRadiation::Rp(), opaqueSolid::Rp(), solarLoad::Rp(), viewFactor::Rp(), lookup::rSpec(), opaqueDiffusive::rSpec(), transparent::rSpec(), noRadiation::Ru(), opaqueSolid::Ru(), Foam::safeLog10(), mappedPatchBase::samplePoints(), kinematicSingleLayer::Sh(), noFilm::Sh(), noRadiation::Shs(), electrostaticDepositionFvPatchScalarField::sigma(), constantSurfaceTensionCoefficient::sigma(), constant::sigma(), temperatureDependent::sigma(), basicSymmetryFaPatchField< Type >::snGrad(), wedgeFaPatchField< Type >::snGrad(), basicSymmetryFvPatchField< Type >::snGrad(), symmetryPlaneFvPatchField< Type >::snGrad(), wedgeFvPatchField< Type >::snGrad(), fvMatrix< Type >::solveSegregated(), timeVaryingMassSorptionFvPatchScalarField::source(), boundaryRadiationProperties::specReflectivity(), kinematicSingleLayer::Srho(), noFilm::Srho(), kinematicSingleLayer::Srho(), noFilm::Srho(), stabilityBlendingFactor::stabilityBlendingFactor(), Foam::sumNeighbours(), multiphaseInterSystem::surfaceTensionForce(), interfaceTrackingFvMesh::surfaceTensionGrad(), ReactingCloud< CloudType >::SYi(), lookup::t(), opaqueDiffusive::t(), opaqueReflective::t(), transparent::t(), constantTransmissivity::t(), multiBandTransmissivity::t(), dynamicContactAngleForce::theta(), constantAlphaContactAngleFvPatchScalarField::theta(), dynamicAlphaContactAngleFvPatchScalarField::theta(), timeVaryingAlphaContactAngleFvPatchScalarField::theta(), targetCoeffTrim::thetag(), Spiegler::TLeid(), boundaryAdjointContribution::TMVariable1(), boundaryAdjointContribution::TMVariable1Diffusion(), boundaryAdjointContribution::TMVariable2(), boundaryAdjointContribution::TMVariable2Diffusion(), adjointkOmegaSST::topologySensitivities(), cyclicFaPatch::transfer(), coordinateSystem::transformPointImpl(), boundaryRadiationProperties::transmissivity(), multiphaseInterSystem::U(), StaticPhaseModel< BasePhaseModel >::U(), noiseModel::uniformFrequencies(), faMesh::unitLe(), fvMesh::unitSf(), resolutionIndexModel::V(), transformFvPatchField< Type >::valueInternalCoeffs(), triSurfaceTools::vertexNormals(), triSurfaceTools::vertexTriads(), blockMesh::vertices(), polyMeshTools::volRatio(), MassTransferPhaseSystem< BasePhaseSystem >::volTransfer(), waveModel::waterLevel(), surfaceFieldValue::weightingFactor(), basicFvGeometryScheme::weights(), electricPotential::write(), rotorDiskSource::writeField(), general::x(), TableBase< Type >::x(), general::y(), nutkWallFunctionFvPatchScalarField::yPlus(), alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField::yPlusTherm(), adjointkOmegaSST::zeroFirstCell(), and boundaryRadiationProperties::zoneTransmissivity().
NewImmovable()
template<class T > template<class... Args> static tmp< T > NewImmovable (bool immovable, Args &&... args) inline static
Definition at line 179 of file tmp.H.
References args, and T.
NewFrom()
template<class T > template<class U , class... Args> static tmp< T > NewFrom (Args &&... args) inline static
Definition at line 191 of file tmp.H.
References args, and U.
typeName()
template<class T > Foam::word typeName () inline static
Definition at line 28 of file tmpI.H.
References Foam::name(), and T.
Referenced by tmp< T >::tmp().
good()
template<class T > bool good () const inline noexcept
Definition at line 206 of file tmp.H.
is_const()
template<class T > bool is_const () const inline noexcept
Definition at line 200 of file tmpI.H.
is_pointer()
template<class T > bool is_pointer () const inline noexcept
Definition at line 207 of file tmpI.H.
Referenced by tmp< T >::isTmp().
is_reference()
template<class T > bool is_reference () const inline noexcept
Definition at line 215 of file tmpI.H.
movable()
template<class T > bool movable () const inline noexcept
Definition at line 223 of file tmpI.H.
get() [1/2]
template<class T > T * get () inline noexcept
Definition at line 224 of file tmp.H.
get() [2/2]
template<class T > const T * get () const inline noexcept
Definition at line 227 of file tmp.H.
cref() [1/6]
template<class T > const T & cref () const inline
Definition at line 230 of file tmpI.H.
Referenced by tmp< T >::constCast(), tmp< Foam::edgeInterpolationScheme< scalar > >::operator const Foam::edgeInterpolationScheme< scalar > &(), and tmp< T >::operator()().
ref() [1/5]
template<class T > T & ref () const inline
Definition at line 244 of file tmpI.H.
constCast()
template<class T > T & constCast () const inline
Definition at line 242 of file tmp.H.
References tmp< T >::cref(), and T.
ptr()
template<class T > T * ptr () const inline
Definition at line 265 of file tmpI.H.
References FatalErrorInFunction.
clear()
template<class T > void clear () const inline noexcept
Definition at line 298 of file tmpI.H.
reset() [1/5]
template<class T > void reset (tmp< T > && other) inline noexcept
Definition at line 333 of file tmpI.H.
Referenced by tmp< T >::operator=().
reset() [2/5]
template<class T > void reset (T * p = nullptr) inline noexcept
Definition at line 316 of file tmpI.H.
References clear(), and p.
reset() [3/5]
template<class T > void reset (bool immovable, T * p) inline noexcept
Definition at line 325 of file tmpI.H.
References p.
reset() [4/5]
template<class T > void reset (const autoPtr< T > &) delete
reset() [5/5]
template<class T > void reset (const refPtr< T > &) delete
cref() [2/6]
template<class T > void cref (const tmp< T > & other) inline noexcept
Definition at line 351 of file tmpI.H.
References clear().
cref() [3/6]
template<class T > void cref (const T & obj) inline noexcept
Definition at line 366 of file tmpI.H.
References clear(), and T.
cref() [4/6]
template<class T > void cref (const T * p) inline noexcept
Definition at line 375 of file tmpI.H.
References clear(), p, and T.
cref() [5/6]
template<class T > void cref (const autoPtr< T > &) delete
cref() [6/6]
template<class T > void cref (const refPtr< T > &) delete
ref() [2/5]
template<class T > void ref (T & obj) inline noexcept
Definition at line 384 of file tmpI.H.
References clear().
ref() [3/5]
template<class T > void ref (T * p) inline noexcept
Definition at line 393 of file tmpI.H.
References clear(), and p.
ref() [4/5]
template<class T > void ref (const autoPtr< T > &) delete
ref() [5/5]
template<class T > void ref (const refPtr< T > &) delete
swap()
template<class T > void swap (tmp< T > & other) inline noexcept
Definition at line 402 of file tmpI.H.
References p, and T.
operator->() [1/2]
template<class T > const T * operator-> () const inline
Definition at line 419 of file tmpI.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
operator->() [2/2]
template<class T > T * operator-> () inline
Definition at line 433 of file tmpI.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
operator()()
template<class T > const T & operator() () const inline
Definition at line 318 of file tmp.H.
References tmp< T >::cref().
operator bool()
template<class T > operator bool () const inline explicit noexcept
Definition at line 324 of file tmp.H.
operator const T &()
template<class T > operator const T & () const inline
Definition at line 327 of file tmp.H.
operator=() [1/4]
template<class T > void operator= (const tmp< T > & other) inline
Definition at line 454 of file tmpI.H.
References Foam::abort(), clear(), Foam::FatalError, FatalErrorInFunction, Foam::name(), and T.
operator=() [2/4]
template<class T > void operator= (tmp< T > && other) inline noexcept
Definition at line 491 of file tmpI.H.
References clear().
operator=() [3/4]
template<class T > void operator= (T * p) inline
Definition at line 509 of file tmpI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and p.
operator=() [4/4]
template<class T > void operator= (std::nullptr_t) inline noexcept
Definition at line 344 of file tmp.H.
References tmp< T >::reset().
valid()
template<class T > bool valid () const inline noexcept
Definition at line 350 of file tmp.H.
isTmp()
template<class T > bool isTmp () const inline noexcept
Definition at line 355 of file tmp.H.
References tmp< T >::is_pointer().
empty()
template<class T > bool empty () const inline noexcept
Definition at line 361 of file tmp.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/HashTables/HashPtrTable/HashPtrTable.H
src/OpenFOAM/memory/tmp/tmp.H
src/OpenFOAM/memory/tmp/tmpI.H