OpenFOAM: SDA Class Reference
SDA Class Reference
Ship design analysis (SDA) 3DoF motion function.
#include <SDA.H>
Public Member Functions
TypeName ("SDA")
SDA (const dictionary &SBMFCoeffs, const Time &runTime)
virtual autoPtr< solidBodyMotionFunction > clone () const
virtual ~SDA ()=default
virtual septernion transformation () const
virtual bool read (const dictionary &SBMFCoeffs)
Public Member Functions inherited from solidBodyMotionFunction
TypeName ("solidBodyMotionFunction")
declareRunTimeSelectionTable (autoPtr, solidBodyMotionFunction, dictionary,(const dictionary &SBMFCoeffs, const Time &runTime),(SBMFCoeffs, runTime))
solidBodyMotionFunction (const dictionary &SBMFCoeffs, const Time &runTime)
virtual ~solidBodyMotionFunction ()=default
virtual void writeData (Ostream &) const
Additional Inherited Members
Static Public Member Functions inherited from solidBodyMotionFunction
static autoPtr< solidBodyMotionFunction > New (const dictionary &SBMFCoeffs, const Time &runTime)
Protected Member Functions inherited from solidBodyMotionFunction
solidBodyMotionFunction (const solidBodyMotionFunction &)=delete
void operator= (const solidBodyMotionFunction &)=delete
Protected Attributes inherited from solidBodyMotionFunction
dictionary SBMFCoeffs_
const Time & time_
Detailed Description
Ship design analysis (SDA) 3DoF motion function.
Comprising sinusoidal roll (rotation about x), heave (z-translation) and sway (y-translation) motions with changing amplitude and phase.
See also
Foam::solidBodyMotionFunctions::tabulated6DoFMotion
Source files
SDA.H
SDA.C
Definition at line 55 of file SDA.H.
Constructor & Destructor Documentation
SDA()
SDA (const dictionary & SBMFCoeffs, const Time & runTime)
Definition at line 42 of file SDA.C.
References SDA::read().
~SDA()
virtual ~SDA () virtual default
Member Function Documentation
TypeName()
TypeName ("SDA")
clone()
virtual autoPtr< solidBodyMotionFunction > clone () const inline virtual
Implements solidBodyMotionFunction.
Definition at line 120 of file SDA.H.
References solidBodyMotionFunction::SBMFCoeffs_, and solidBodyMotionFunction::time_.
transformation()
Foam::septernion transformation () const virtual
Implements solidBodyMotionFunction.
Definition at line 57 of file SDA.C.
References DebugInFunction, Foam::endl(), Foam::exp(), Foam::log(), Foam::mag(), Foam::max(), Foam::constant::mathematical::pi(), Foam::constant::mathematical::piByTwo(), R, Foam::sin(), Foam::sqr(), T, Foam::constant::mathematical::twoPi(), and quaternion::XYZ.
read()
bool read (const dictionary & SBMFCoeffs) virtual
Implements solidBodyMotionFunction.
Definition at line 92 of file SDA.C.
References solidBodyMotionFunction::read(), and Foam::sqrt().
Referenced by SDA::SDA().
The documentation for this class was generated from the following files:
src/dynamicMesh/motionSolvers/displacement/solidBody/solidBodyMotionFunctions/SDA/SDA.H
src/dynamicMesh/motionSolvers/displacement/solidBody/solidBodyMotionFunctions/SDA/SDA.C