OpenFOAM: Vector< Cmpt > Class Template Reference
Vector< Cmpt > Class Template Reference
Templated 3D Vector derived from VectorSpace adding construction from 3 components, element access using x(), y() and z() member functions and the inner-product (dot-product) and cross-product operators.
#include <Vector.H>
Public Types
enum components { X , Y , Z }
typedef Vector< label > labelType
Public Types inherited from VectorSpace< Vector< Cmpt >, Cmpt, 3 >
typedef VectorSpace< Vector< Cmpt >, Cmpt, Ncmpts > vsType
typedef Cmpt cmptType
typedef Cmpt magType
typedef Cmpt * iterator
typedef const Cmpt * const_iterator
Public Member Functions
Vector ()=default
Vector (const Vector &)=default
Vector & operator= (const Vector &)=default
Vector (const Foam::zero)
template<class Cmpt2 >
Vector (const VectorSpace< Vector< Cmpt2 >, Cmpt2, 3 > &vs)
Vector (const Cmpt &vx, const Cmpt &vy, const Cmpt &vz)
Vector (Istream &is)
const Cmpt & x () const noexcept
const Cmpt & y () const noexcept
const Cmpt & z () const noexcept
Cmpt & x () noexcept
Cmpt & y () noexcept
Cmpt & z () noexcept
const Vector< Cmpt > & centre (const Foam::UList< Vector< Cmpt > > &) const noexcept
scalar mag () const
scalar magSqr () const
scalar dist (const Vector< Cmpt > &v2) const
scalar distSqr (const Vector< Cmpt > &v2) const
Vector< Cmpt > & normalise (const scalar tol=ROOTVSMALL)
Vector< Cmpt > & removeCollinear (const Vector< Cmpt > &unitVec)
Cmpt inner (const Vector< Cmpt > &v2) const
Vector< Cmpt > cross (const Vector< Cmpt > &v2) const
Public Member Functions inherited from VectorSpace< Vector< Cmpt >, Cmpt, 3 >
VectorSpace ()=default
VectorSpace (const Foam::zero)
VectorSpace (const VectorSpace< Vector< Cmpt >, Cmpt, Ncmpts > &vs)
VectorSpace (const VectorSpace< Form2, Cmpt2, Ncmpts > &)
VectorSpace (Istream &is)
const Cmpt & component (const direction) const
Cmpt & component (const direction)
void component (Cmpt &, const direction) const
void replace (const direction, const Cmpt &)
const Cmpt * cdata () const noexcept
Cmpt * data () noexcept
const ConstBlock< SubVector, BStart > block () const
const Foam::VectorSpace< Vector< Cmpt >, Cmpt, Ncmpts >::template ConstBlock< SubVector, BStart > block () const
const Cmpt & operator[] (const direction) const
Cmpt & operator[] (const direction)
void operator= (const VectorSpace< Vector< Cmpt >, Cmpt, Ncmpts > &)
void operator= (const Foam::zero)
void operator+= (const VectorSpace< Vector< Cmpt >, Cmpt, Ncmpts > &)
void operator-= (const VectorSpace< Vector< Cmpt >, Cmpt, Ncmpts > &)
void operator*= (const scalar)
void operator/= (const scalar)
iterator begin () noexcept
const_iterator begin () const noexcept
iterator end () noexcept
const_iterator end () const noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
Static Public Member Functions
static bool less_xyz (const Vector< Cmpt > &a, const Vector< Cmpt > &b)
static bool less_yzx (const Vector< Cmpt > &a, const Vector< Cmpt > &b)
static bool less_zxy (const Vector< Cmpt > &a, const Vector< Cmpt > &b)
Static Public Member Functions inherited from VectorSpace< Vector< Cmpt >, Cmpt, 3 >
static constexpr direction size () noexcept
static Vector< Cmpt > uniform (const Cmpt &s)
Static Public Attributes
static constexpr direction rank = 1
Static Public Attributes inherited from VectorSpace< Vector< Cmpt >, Cmpt, 3 >
static constexpr direction dim
static constexpr direction nComponents
static constexpr direction mRows
static constexpr direction nCols
static const char *const typeName
static const char *const componentNames []
static const Vector< Cmpt > zero
static const Vector< Cmpt > one
static const Vector< Cmpt > max
static const Vector< Cmpt > min
static const Vector< Cmpt > rootMax
static const Vector< Cmpt > rootMin
Additional Inherited Members
Public Attributes inherited from VectorSpace< Vector< Cmpt >, Cmpt, 3 >
Cmpt v_ [Ncmpts]
Detailed Description
template<class Cmpt>
class Foam::Vector< Cmpt >
Templated 3D Vector derived from VectorSpace adding construction from 3 components, element access using x(), y() and z() member functions and the inner-product (dot-product) and cross-product operators.
A centre() member function which returns the Vector for which it is called is defined so that point which is a typedef to Vector<scalar> behaves as other shapes in the shape hierarchy.
Source files
Vector.H
VectorI.H
Definition at line 58 of file Vector.H.
Member Typedef Documentation
labelType
template<class Cmpt > typedef Vector<label> labelType
Definition at line 67 of file Vector.H.
Member Enumeration Documentation
components
template<class Cmpt > enum components
Enumerator
X
Y
Z
Definition at line 77 of file Vector.H.
Constructor & Destructor Documentation
Vector() [1/6]
template<class Cmpt > Vector () default
Vector() [2/6]
template<class Cmpt > Vector (const Vector< Cmpt > &) default
Vector() [3/6]
template<class Cmpt > Vector (const Foam::zero) inline
Definition at line 25 of file VectorI.H.
Vector() [4/6]
template<class Cmpt > template<class Cmpt2 > Vector (const VectorSpace< Vector< Cmpt2 >, Cmpt2, 3 > & vs) inline
Definition at line 33 of file VectorI.H.
Vector() [5/6]
template<class Cmpt > Vector (const Cmpt & vx, const Cmpt & vy, const Cmpt & vz) inline
Definition at line 43 of file VectorI.H.
References Y.
Vector() [6/6]
template<class Cmpt > Vector (Istream & is) inline explicit
Definition at line 57 of file VectorI.H.
Member Function Documentation
operator=()
template<class Cmpt > Vector & operator= (const Vector< Cmpt > &) default
Referenced by triad::operator=().
x() [1/2]
template<class Cmpt > const Cmpt & x () const inline noexcept
Definition at line 113 of file Vector.H.
References VectorSpace< Vector< Cmpt >, Cmpt, 3 >::v_, and Vector< Cmpt >::X.
Referenced by biLinearFitPolynomial::addCoeffs(), cubicUpwindFitPolynomial::addCoeffs(), linearFitPolynomial::addCoeffs(), quadraticFitPolynomial::addCoeffs(), quadraticLinearFitPolynomial::addCoeffs(), quadraticLinearUpwindFitPolynomial::addCoeffs(), quadraticUpwindFitPolynomial::addCoeffs(), tetIndices::barycentricToPoint(), NURBS3DVolume::bound(), PDRblock::C(), energySpectrum::calcAndWriteSpectrum(), CentredFitSnGradData< Polynomial >::calcFit(), wedgePolyPatch::calcGeometry(), rotorDiskSource::calculate(), ijkAddressing::checkIndex(), molecule::constantProperties::constantProperties(), boundBox::contains(), boundBox::containsInside(), cyclicPolyPatch::coupledEdges(), cyclicPolyPatch::coupledPoints(), PDRblock::dx(), adjointRotatingWallVelocityFvPatchVectorField::dxdbMult(), pitchForkRing::energy(), treeBoundBox::faceBits(), boundBox::faceCentre(), pitchForkRing::force(), Foam::fromCartesian(), FIRECore::getFirePoint(), ellipsoidImplicitFunction::grad(), PDRblock::grid(), voxelMeshSearch::index(), ijkAddressing::index(), voxelMeshSearch::index(), voxelMeshSearch::index3(), voxelMeshSearch::index3(), cellShapeControlMesh::insert(), cellShapeControlMesh::insertFar(), treeBoundBox::intersects(), momentOfInertia::massPropertiesSolid(), FitData< CentredFitData< Polynomial >, extendedCentredCellToFaceStencil, Polynomial >::movePoints(), plane::planeIntersect(), ijkMesh::pointLabel(), polyTopoChange::pointRemoved(), tetrahedron< Point, PointRef >::pointToBarycentric(), treeBoundBox::posBits(), triad::primaryDirection(), FIRECore::putFirePoint(), quaternion::quaternion(), Foam::Ra(), AC3DsurfaceFormat< Face >::read(), PDRblock::reset(), euler::rotation(), treeBoundBox::searchOrder(), KinematicLookupTableInjection< CloudType >::setPositionAndCell(), ReactingLookupTableInjection< CloudType >::setPositionAndCell(), ReactingMultiphaseLookupTableInjection< CloudType >::setPositionAndCell(), ThermoLookupTableInjection< CloudType >::setPositionAndCell(), treeBoundBox::subOctant(), treeBoundBox::subOctant(), treeBoundBox::subOctant(), Foam::toCartesian(), controlPointsDefinition::transformControlPoints(), Foam::transformPrincipal_vector(), NURBS3DVolumeCylindrical::updateLocalCoordinateSystem(), PDRblock::V(), ellipsoidImplicitFunction::value(), paraboloidImplicitFunction::value(), ijkMesh::vertLabels(), SMESHsurfaceFormat< Face >::write(), STLtriangle::write(), triSurfaceTools::writeOBJ(), Foam::meshTools::writeOBJ(), Foam::meshTools::writeOBJ(), Foam::meshTools::writeOBJ(), coupledPolyPatch::writeOBJ(), cellCuts::writeOBJ(), Foam::meshTools::writeOBJ(), Cloud< ParticleType >::writePositions(), PDRobstacle::x(), PDRobstacle::x(), and Foam::Xinterpolate().
y() [1/2]
template<class Cmpt > const Cmpt & y () const inline noexcept
Definition at line 116 of file Vector.H.
References VectorSpace< Vector< Cmpt >, Cmpt, 3 >::v_, and Vector< Cmpt >::Y.
Referenced by biLinearFitPolynomial::addCoeffs(), cubicUpwindFitPolynomial::addCoeffs(), linearFitPolynomial::addCoeffs(), quadraticFitPolynomial::addCoeffs(), quadraticLinearFitPolynomial::addCoeffs(), quadraticLinearUpwindFitPolynomial::addCoeffs(), quadraticUpwindFitPolynomial::addCoeffs(), tetIndices::barycentricToPoint(), NURBS3DVolume::bound(), PDRblock::C(), energySpectrum::calcAndWriteSpectrum(), CentredFitSnGradData< Polynomial >::calcFit(), wedgePolyPatch::calcGeometry(), rotorDiskSource::calculate(), ijkAddressing::checkIndex(), molecule::constantProperties::constantProperties(), boundBox::contains(), boundBox::containsInside(), cyclicPolyPatch::coupledEdges(), cyclicPolyPatch::coupledPoints(), adjointRotatingWallVelocityFvPatchVectorField::dxdbMult(), PDRblock::dy(), pitchForkRing::energy(), treeBoundBox::faceBits(), boundBox::faceCentre(), pitchForkRing::force(), Foam::fromCartesian(), FIRECore::getFirePoint(), ellipsoidImplicitFunction::grad(), PDRblock::grid(), voxelMeshSearch::index(), ijkAddressing::index(), voxelMeshSearch::index(), voxelMeshSearch::index3(), voxelMeshSearch::index3(), cellShapeControlMesh::insert(), cellShapeControlMesh::insertFar(), treeBoundBox::intersects(), momentOfInertia::massPropertiesSolid(), FitData< CentredFitData< Polynomial >, extendedCentredCellToFaceStencil, Polynomial >::movePoints(), plane::planeIntersect(), ijkMesh::pointLabel(), polyTopoChange::pointRemoved(), tetrahedron< Point, PointRef >::pointToBarycentric(), treeBoundBox::posBits(), triad::primaryDirection(), FIRECore::putFirePoint(), quaternion::quaternion(), Foam::Ra(), AC3DsurfaceFormat< Face >::read(), PDRblock::reset(), euler::rotation(), treeBoundBox::searchOrder(), treeBoundBox::subOctant(), treeBoundBox::subOctant(), treeBoundBox::subOctant(), Foam::toCartesian(), controlPointsDefinition::transformControlPoints(), Foam::transformPrincipal_vector(), NURBS3DVolumeCylindrical::updateLocalCoordinateSystem(), PDRblock::V(), ellipsoidImplicitFunction::value(), paraboloidImplicitFunction::value(), ijkMesh::vertLabels(), SMESHsurfaceFormat< Face >::write(), STLtriangle::write(), triSurfaceTools::writeOBJ(), Foam::meshTools::writeOBJ(), Foam::meshTools::writeOBJ(), Foam::meshTools::writeOBJ(), coupledPolyPatch::writeOBJ(), cellCuts::writeOBJ(), Foam::meshTools::writeOBJ(), Cloud< ParticleType >::writePositions(), Foam::Xinterpolate(), PDRobstacle::y(), and PDRobstacle::y().
z() [1/2]
template<class Cmpt > const Cmpt & z () const inline noexcept
Definition at line 119 of file Vector.H.
References VectorSpace< Vector< Cmpt >, Cmpt, 3 >::v_, and Vector< Cmpt >::Z.
Referenced by biLinearFitPolynomial::addCoeffs(), cubicUpwindFitPolynomial::addCoeffs(), linearFitPolynomial::addCoeffs(), quadraticFitPolynomial::addCoeffs(), quadraticLinearFitPolynomial::addCoeffs(), quadraticLinearUpwindFitPolynomial::addCoeffs(), quadraticUpwindFitPolynomial::addCoeffs(), tetIndices::barycentricToPoint(), NURBS3DVolume::bound(), PDRblock::C(), energySpectrum::calcAndWriteSpectrum(), CentredFitSnGradData< Polynomial >::calcFit(), wedgePolyPatch::calcGeometry(), rotorDiskSource::calculate(), ijkAddressing::checkIndex(), molecule::constantProperties::constantProperties(), boundBox::contains(), boundBox::containsInside(), cyclicPolyPatch::coupledEdges(), cyclicPolyPatch::coupledPoints(), adjointRotatingWallVelocityFvPatchVectorField::dxdbMult(), PDRblock::dz(), pitchForkRing::energy(), treeBoundBox::faceBits(), boundBox::faceCentre(), pitchForkRing::force(), Foam::fromCartesian(), FIRECore::getFirePoint(), ellipsoidImplicitFunction::grad(), PDRblock::grid(), voxelMeshSearch::index(), ijkAddressing::index(), voxelMeshSearch::index3(), cellShapeControlMesh::insert(), cellShapeControlMesh::insertFar(), treeBoundBox::intersects(), momentOfInertia::massPropertiesSolid(), FitData< CentredFitData< Polynomial >, extendedCentredCellToFaceStencil, Polynomial >::movePoints(), plane::planeIntersect(), ijkMesh::pointLabel(), polyTopoChange::pointRemoved(), tetrahedron< Point, PointRef >::pointToBarycentric(), treeBoundBox::posBits(), triad::primaryDirection(), FIRECore::putFirePoint(), quaternion::quaternion(), Foam::Ra(), AC3DsurfaceFormat< Face >::read(), PDRblock::reset(), euler::rotation(), treeBoundBox::searchOrder(), treeBoundBox::subOctant(), treeBoundBox::subOctant(), treeBoundBox::subOctant(), Foam::toCartesian(), controlPointsDefinition::transformControlPoints(), Foam::transformPrincipal_vector(), PDRblock::V(), ellipsoidImplicitFunction::value(), paraboloidImplicitFunction::value(), ijkMesh::vertLabels(), SMESHsurfaceFormat< Face >::write(), STLtriangle::write(), triSurfaceTools::writeOBJ(), Foam::meshTools::writeOBJ(), Foam::meshTools::writeOBJ(), Foam::meshTools::writeOBJ(), coupledPolyPatch::writeOBJ(), cellCuts::writeOBJ(), Foam::meshTools::writeOBJ(), Cloud< ParticleType >::writePositions(), PDRobstacle::z(), and PDRobstacle::z().
x() [2/2]
template<class Cmpt > Cmpt & x () inline noexcept
Definition at line 122 of file Vector.H.
References VectorSpace< Vector< Cmpt >, Cmpt, 3 >::v_, and Vector< Cmpt >::X.
y() [2/2]
template<class Cmpt > Cmpt & y () inline noexcept
Definition at line 125 of file Vector.H.
References VectorSpace< Vector< Cmpt >, Cmpt, 3 >::v_, and Vector< Cmpt >::Y.
z() [2/2]
template<class Cmpt > Cmpt & z () inline noexcept
Definition at line 128 of file Vector.H.
References VectorSpace< Vector< Cmpt >, Cmpt, 3 >::v_, and Vector< Cmpt >::Z.
centre()
template<class Cmpt > const Foam::Vector< Cmpt > & centre (const Foam::UList< Vector< Cmpt > > &) const inline noexcept
Definition at line 66 of file VectorI.H.
Referenced by cellShape::centre(), and cyclicPolyPatch::coupledEdges().
mag()
template<class Cmpt > Foam::scalar mag () const inline
Definition at line 88 of file VectorI.H.
References Foam::magSqr().
magSqr()
template<class Cmpt > Foam::scalar magSqr () const inline
Definition at line 76 of file VectorI.H.
References Foam::magSqr(), x, and y.
Referenced by faNVDscheme< Type, NVDweight >::weights().
dist()
template<class Cmpt > Foam::scalar dist (const Vector< Cmpt > & v2) const inline
Definition at line 107 of file VectorI.H.
Referenced by triSurfaceTools::calcInterpolationWeights(), and treeBoundBox::maxDist().
distSqr()
template<class Cmpt > Foam::scalar distSqr (const Vector< Cmpt > & v2) const inline
Definition at line 95 of file VectorI.H.
Referenced by treeBoundBox::distanceCmp(), mapNearestMethod::findNearestCell(), dynamicTreeDataPoint::overlaps(), and treeDataPoint::overlaps().
normalise()
template<class Cmpt > Foam::Vector< Cmpt > & normalise (const scalar tol = ROOTVSMALL) inline
Definition at line 114 of file VectorI.H.
References Foam::mag(), s(), and Foam::Zero.
Referenced by wedgePolyPatch::calcGeometry(), ConeInjection< CloudType >::ConeInjection(), rotorDiskSource::createCoordinateSystem(), directionalPressureGradientExplicitSource::directionalPressureGradientExplicitSource(), fanMomentumSource::fanMomentumSource(), LISAAtomization< CloudType >::LISAAtomization(), surfaceFieldValue::processValues(), singleDirectionUniformBin::read(), setFlow::read(), propellerInfo::setCoordinateSystem(), searchableSphere::surfaceNormal(), surfaceIteratorPLIC::vofCutCell(), waveMakerPointPatchVectorField::waveMakerPointPatchVectorField(), and faNVDscheme< Type, NVDweight >::weights().
removeCollinear()
template<class Cmpt > Foam::Vector< Cmpt > & removeCollinear (const Vector< Cmpt > & unitVec) inline
Definition at line 133 of file VectorI.H.
Referenced by searchableSurfacesQueries::findNearest(), and faNVDscheme< Type, NVDweight >::weights().
inner()
template<class Cmpt > Cmpt inner (const Vector< Cmpt > & v2) const inline
Definition at line 143 of file VectorI.H.
cross()
template<class Cmpt > Foam::Vector< Cmpt > cross (const Vector< Cmpt > & v2) const inline
Definition at line 153 of file VectorI.H.
less_xyz()
template<class Cmpt > bool less_xyz (const Vector< Cmpt > & a, const Vector< Cmpt > & b) inline static
Definition at line 170 of file VectorI.H.
less_yzx()
template<class Cmpt > bool less_yzx (const Vector< Cmpt > & a, const Vector< Cmpt > & b) inline static
Definition at line 194 of file VectorI.H.
References b.
less_zxy()
template<class Cmpt > bool less_zxy (const Vector< Cmpt > & a, const Vector< Cmpt > & b) inline static
Definition at line 218 of file VectorI.H.
References b.
Member Data Documentation
rank
template<class Cmpt > constexpr direction rank = 1 static constexpr
Definition at line 73 of file Vector.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/Vector/Vector.H
src/OpenFOAM/primitives/Vector/VectorI.H