OpenFOAM: codedBase Class Reference
codedBase Class Reference abstract
Base class for function objects and boundary conditions using dynamic code that provides methods for managing loading/unloading/updating of a dynamic library. For these purposes, it uses a dynamicCodeContext object to maintain information about the state.
#include <codedBase.H>
Public Member Functions
ClassName ("codedBase")
codedBase (const codedBase &)=delete
void operator= (const codedBase &)=delete
codedBase ()=default
virtual ~codedBase ()=default
Protected Member Functions
dynamicCodeContext & codeContext ()
void setCodeContext (const dictionary &dict)
void append (const std::string &str)
void updateLibrary (const word &name, const dynamicCodeContext &context) const
void updateLibrary (const word &name, const dictionary &dict) const
void updateLibrary (const word &name) const
virtual dlLibraryTable & libs () const =0
virtual string description () const =0
virtual void clearRedirect () const =0
virtual const dictionary & codeDict () const =0
virtual void prepare (dynamicCode &dynCode, const dynamicCodeContext &context) const =0
Static Protected Member Functions
static void writeCodeDict (Ostream &os, const dictionary &dict)
static const dictionary & codeDict (const objectRegistry &obr, const word &dictName="codeDict")
Detailed Description
Base class for function objects and boundary conditions using dynamic code that provides methods for managing loading/unloading/updating of a dynamic library. For these purposes, it uses a dynamicCodeContext object to maintain information about the state.
For simple coded objects, the default state management is sufficient. When there are more complicated code segments (eg, functionObjects::codedFunctionObject), the state management must also register these elements as well, starting with an initial setCodeContext() call and followed by append() to register each element.
Source files
codedBase.H
codedBase.C
Definition at line 62 of file codedBase.H.
Constructor & Destructor Documentation
codedBase() [1/2]
codedBase (const codedBase &) delete
codedBase() [2/2]
codedBase () default
~codedBase()
virtual ~codedBase () virtual default
Member Function Documentation
writeCodeDict()
void writeCodeDict (Ostream & os, const dictionary & dict) static protected
Definition at line 81 of file codedBase.C.
References dict, os(), and Foam::writeEntryIfPresent().
Referenced by codedFixedValueFvPatchField< Type >::write(), codedMixedFvPatchField< Type >::write(), and codedFixedValuePointPatchField< Type >::write().
codeDict() [1/2]
const Foam::dictionary & codeDict (const objectRegistry & obr, const word & dictName = "codeDict") static protected
Definition at line 93 of file codedBase.C.
References dictName(), objectRegistry::getObjectPtr(), IOobjectOption::NO_WRITE, IOobjectOption::READ_MODIFIED, IOobjectOption::REGISTER, regIOobject::store(), and objectRegistry::time().
codeContext()
dynamicCodeContext & codeContext () inline protected
Definition at line 115 of file codedBase.H.
Referenced by codedFunctionObject::read(), and CodedSource< Type >::read().
setCodeContext()
void setCodeContext (const dictionary & dict) protected
Definition at line 258 of file codedBase.C.
References dict.
Referenced by CodedField< Type >::CodedField(), CodedFunction1< Type >::CodedFunction1(), codedFunctionObject::read(), and CodedSource< Type >::read().
append()
void append (const std::string & str) protected
Definition at line 264 of file codedBase.C.
References PtrList< T >::append().
updateLibrary() [1/3]
void updateLibrary (const word & name, const dynamicCodeContext & context) const protected
Definition at line 270 of file codedBase.C.
References dlLibraryTable::basename(), dynamicCode::checkSecurity(), DetailInfo, dynamicCodeContext::dict(), Foam::endl(), loadLibrary(), Foam::name(), Foam::returnReduceOr(), and dynamicCodeContext::sha1().
Referenced by CodedField< Type >::CodedField(), CodedFunction1< Type >::CodedFunction1(), and codedFunctionObject::codedFunctionObject().
updateLibrary() [2/3]
void updateLibrary (const word & name, const dictionary & dict) const protected
Definition at line 332 of file codedBase.C.
References dict, and Foam::name().
updateLibrary() [3/3]
void updateLibrary (const word & name) const protected
Definition at line 342 of file codedBase.C.
References Foam::name().
libs()
virtual dlLibraryTable & libs () const protected pure virtual
Implemented in codedPoints0MotionSolver, codedMixedFvPatchField< Type >, codedFunctionObject, CodedSource< Type >, CodedField< Type >, and CodedFunction1< Type >.
description()
virtual string description () const protected pure virtual
Implemented in codedPoints0MotionSolver, codedMixedFvPatchField< Type >, codedFunctionObject, CodedSource< Type >, CodedField< Type >, and CodedFunction1< Type >.
clearRedirect()
virtual void clearRedirect () const protected pure virtual
Implemented in codedPoints0MotionSolver, codedMixedFvPatchField< Type >, codedFunctionObject, CodedSource< Type >, CodedField< Type >, and CodedFunction1< Type >.
codeDict() [2/2]
virtual const dictionary & codeDict () const protected pure virtual
Implemented in codedPoints0MotionSolver, codedMixedFvPatchField< Type >, codedFunctionObject, CodedSource< Type >, CodedField< Type >, and CodedFunction1< Type >.
Referenced by codedMixedFvPatchField< Type >::codeDict().
prepare()
virtual void prepare (dynamicCode & dynCode, const dynamicCodeContext & context) const protected pure virtual
Implemented in codedPoints0MotionSolver, codedMixedFvPatchField< Type >, codedFunctionObject, CodedSource< Type >, CodedField< Type >, and CodedFunction1< Type >.
ClassName()
ClassName ("codedBase")
operator=()
void operator= (const codedBase &) delete
The documentation for this class was generated from the following files:
src/OpenFOAM/db/dynamicLibrary/codedBase/codedBase.H
src/OpenFOAM/db/dynamicLibrary/codedBase/codedBase.C