OpenFOAM: faGlobalMeshData Class Reference
faGlobalMeshData Class Reference
Various mesh related information for a parallel run.
#include <faGlobalMeshData.H>
Public Member Functions
ClassName ("faGlobalMeshData")
faGlobalMeshData (const faMesh &mesh)
~faGlobalMeshData ()
const faMesh & mesh () const noexcept
const processorTopology & topology () const noexcept
const lduSchedule & patchSchedule () const noexcept
label nGlobalPoints () const noexcept
const labelList & sharedPointLabels () const noexcept
const labelList & sharedPointAddr () const noexcept
void updateMesh ()
Detailed Description
Various mesh related information for a parallel run.
Author Zeljko Tukovic, FMENA Hrvoje Jasak, Wikki Ltd.
Definition at line 49 of file faGlobalMeshData.H.
Constructor & Destructor Documentation
faGlobalMeshData()
faGlobalMeshData (const faMesh & mesh) explicit
Definition at line 33 of file faGlobalMeshData.C.
References Foam::New(), and faGlobalMeshData::updateMesh().
~faGlobalMeshData()
~faGlobalMeshData ()
Definition at line 55 of file faGlobalMeshData.C.
Member Function Documentation
ClassName()
ClassName ("faGlobalMeshData")
mesh()
const Foam::faMesh & mesh () const noexcept
Definition at line 61 of file faGlobalMeshData.C.
topology()
const processorTopology & topology () const inline noexcept
Definition at line 109 of file faGlobalMeshData.H.
patchSchedule()
const lduSchedule & patchSchedule () const inline noexcept
Definition at line 116 of file faGlobalMeshData.H.
References processorTopology::patchSchedule().
nGlobalPoints()
label nGlobalPoints () const inline noexcept
Definition at line 125 of file faGlobalMeshData.H.
sharedPointLabels()
const labelList & sharedPointLabels () const inline noexcept
Definition at line 131 of file faGlobalMeshData.H.
sharedPointAddr()
const labelList & sharedPointAddr () const inline noexcept
Definition at line 137 of file faGlobalMeshData.H.
updateMesh()
void updateMesh ()
Definition at line 67 of file faGlobalMeshData.C.
References Pstream::combineReduce(), forAll, HashTable< T, Key, Hash >::found(), HashSet< Key, Hash >::insert(), PtrList< T >::setSize(), UPtrList< T >::size(), HashTable< T, Key, Hash >::toc(), and Foam::Zero.
Referenced by faGlobalMeshData::faGlobalMeshData().
The documentation for this class was generated from the following files:
src/finiteArea/faMesh/faGlobalMeshData/faGlobalMeshData.H
src/finiteArea/faMesh/faGlobalMeshData/faGlobalMeshData.C