OpenFOAM: TimePaths Class Reference
TimePaths Class Reference
Address the time paths without using the Time class.
#include <TimePaths.H>
Public Member Functions
TimePaths (const argList &args, const word &systemName="system", const word &constantName="constant")
TimePaths (const fileName &rootPath, const fileName &caseName, const word &systemName="system", const word &constantName="constant")
TimePaths (const bool processorCase, const fileName &rootPath, const bool distributed, const fileName &globalCaseName, const fileName &caseName, const word &systemName="system", const word &constantName="constant")
bool distributed () const noexcept
bool processorCase () const noexcept
bool processorCase (const bool isProcessorCase) noexcept
const fileName & rootPath () const noexcept
const fileName & globalCaseName () const noexcept
const fileName & caseName () const noexcept
fileName & caseName () noexcept
fileName path () const
fileName globalPath () const
fileName relativePath (const fileName &input, const bool caseTag=false) const
const word & constant () const noexcept
const word & system () const noexcept
fileName caseConstant () const
fileName caseSystem () const
fileName constantPath () const
fileName systemPath () const
instantList times () const
instant findClosestTime (const scalar t) const
Static Public Member Functions
static instantList findTimes (const fileName &directory, const word &constantName="constant")
static label findClosestTimeIndex (const instantList &timeDirs, const scalar t, const word &constantName="constant")
Detailed Description
Address the time paths without using the Time class.
Source files
TimePaths.H
TimePaths.C
Definition at line 52 of file TimePaths.H.
Constructor & Destructor Documentation
TimePaths() [1/3]
TimePaths (const argList & args, const word & systemName = "system", const word & constantName = "constant") explicit
Definition at line 61 of file TimePaths.C.
TimePaths() [2/3]
TimePaths (const fileName & rootPath, const fileName & caseName, const word & systemName = "system", const word & constantName = "constant")
Definition at line 83 of file TimePaths.C.
TimePaths() [3/3]
TimePaths (const bool processorCase, const fileName & rootPath, const bool distributed, const fileName & globalCaseName, const fileName & caseName, const word & systemName = "system", const word & constantName = "constant")
Definition at line 104 of file TimePaths.C.
Member Function Documentation
distributed()
bool distributed () const inline noexcept
Definition at line 23 of file TimePathsI.H.
Referenced by Time::readDict().
processorCase() [1/2]
bool processorCase () const inline noexcept
Definition at line 29 of file TimePathsI.H.
processorCase() [2/2]
bool processorCase (const bool isProcessorCase) inline noexcept
Definition at line 35 of file TimePathsI.H.
rootPath()
const Foam::fileName & rootPath () const inline noexcept
Definition at line 43 of file TimePathsI.H.
globalCaseName()
const Foam::fileName & globalCaseName () const inline noexcept
Definition at line 49 of file TimePathsI.H.
caseName() [1/2]
const Foam::fileName & caseName () const inline noexcept
Definition at line 55 of file TimePathsI.H.
caseName() [2/2]
Foam::fileName & caseName () inline noexcept
Definition at line 61 of file TimePathsI.H.
path()
Foam::fileName path () const inline
Definition at line 67 of file TimePathsI.H.
globalPath()
Foam::fileName globalPath () const inline
Definition at line 73 of file TimePathsI.H.
relativePath()
Foam::fileName relativePath (const fileName & input, const bool caseTag = false) const inline
Definition at line 79 of file TimePathsI.H.
References Foam::input().
constant()
const Foam::word & constant () const inline noexcept
Definition at line 89 of file TimePathsI.H.
Referenced by fileOperation::findInstance(), masterUncollatedFileOperation::findInstance(), timeSelector::select0(), Foam::selectReadIO(), triSurface::triSurfInstance(), FIREMeshWriter::write(), triSurfaceTools::writeCurvature(), and triSurfaceMesh::writeObject().
system()
const Foam::word & system () const inline noexcept
Definition at line 95 of file TimePathsI.H.
Referenced by triSurfaceMesh::writeObject().
caseConstant()
Foam::fileName caseConstant () const inline
Definition at line 101 of file TimePathsI.H.
Referenced by triSurfaceMesh::writeObject().
caseSystem()
Foam::fileName caseSystem () const inline
Definition at line 112 of file TimePathsI.H.
References Foam::system().
Referenced by triSurfaceMesh::writeObject().
constantPath()
Foam::fileName constantPath () const inline
Definition at line 123 of file TimePathsI.H.
References path().
systemPath()
Foam::fileName systemPath () const inline
Definition at line 129 of file TimePathsI.H.
findTimes()
Foam::instantList findTimes (const fileName & directory, const word & constantName = "constant") static
Definition at line 132 of file TimePaths.C.
References Foam::fileHandler.
Referenced by uniformInterpolatedDisplacementPointPatchVectorField::updateCoeffs().
findClosestTimeIndex()
Foam::label findClosestTimeIndex (const instantList & timeDirs, const scalar t, const word & constantName = "constant") static
Definition at line 148 of file TimePaths.C.
References Foam::diff(), Foam::mag(), Foam::name(), and UPtrList< T >::size().
Referenced by if(), and timeSelector::selected().
times()
Foam::instantList times () const
Definition at line 142 of file TimePaths.C.
References path().
Referenced by fileOperation::findInstance(), masterUncollatedFileOperation::findInstance(), timeSelector::select0(), and triSurface::triSurfInstance().
findClosestTime()
Foam::instant findClosestTime (const scalar t) const
Definition at line 176 of file TimePaths.C.
References Foam::diff(), UPtrList< T >::first(), UPtrList< T >::last(), Foam::mag(), path(), and UPtrList< T >::size().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/Time/TimePaths.H
src/OpenFOAM/db/Time/TimePaths.C
src/OpenFOAM/db/Time/TimePathsI.H