OpenFOAM: dummy Class Reference
dummy Class Reference
#include <dummy.H>
Public Member Functions
TypeName ("dummy")
dummy (const word &name, const IATE &iate, const dictionary &dict)
virtual ~dummy ()=default
virtual tmp< fvScalarMatrix > R (const volScalarField &alphai, volScalarField &kappai) const
TypeName ("dummy")
dummy (const word &name, const IATE &iate, const dictionary &dict)
virtual ~dummy ()=default
virtual tmp< volScalarField > R () const
Public Member Functions inherited from IATEsource
TypeName ("IATEsource")
declareRunTimeSelectionTable (autoPtr, IATEsource, dictionary,(const IATE &iate, const dictionary &dict),(iate, dict))
IATEsource (const IATE &iate)
autoPtr< IATEsource > clone () const
virtual ~IATEsource ()=default
const phaseModel & phase () const
const twoPhaseSystem & fluid () const
const phaseModel & otherPhase () const
scalar phi () const
tmp< volScalarField > Ur () const
tmp< volScalarField > Ut () const
tmp< volScalarField > Re () const
tmp< volScalarField > CD () const
tmp< volScalarField > Mo () const
tmp< volScalarField > Eo () const
tmp< volScalarField > We () const
TypeName ("IATEsource")
declareRunTimeSelectionTable (autoPtr, IATEsource, dictionary,(const IATE &iate, const dictionary &dict),(iate, dict))
IATEsource (const IATE &iate)
autoPtr< IATEsource > clone () const
virtual ~IATEsource ()=default
const phaseModel & phase () const
const twoPhaseSystem & fluid () const
const phaseModel & otherPhase () const
scalar phi () const
tmp< volScalarField > Ur () const
tmp< volScalarField > Ut () const
tmp< volScalarField > Re () const
tmp< volScalarField > CD () const
tmp< volScalarField > Mo () const
tmp< volScalarField > Eo () const
tmp< volScalarField > We () const
Additional Inherited Members
Static Public Member Functions inherited from IATEsource
static autoPtr< IATEsource > New (const word &type, const IATE &iate, const dictionary &dict)
static autoPtr< IATEsource > New (const word &type, const IATE &iate, const dictionary &dict)
Protected Attributes inherited from IATEsource
const IATE & iate_
Detailed Description
Source files
dummy.H
dummy.C
Source files
dummy.H
dummy.C
Definition at line 50 of file dummy.H.
Constructor & Destructor Documentation
dummy() [1/2]
dummy (const word & name, const IATE & iate, const dictionary & dict) inline
Definition at line 62 of file dummy.H.
~dummy() [1/2]
virtual ~dummy () virtual default
dummy() [2/2]
dummy (const word & name, const IATE & iate, const dictionary & dict) inline
Definition at line 62 of file dummy.H.
~dummy() [2/2]
virtual ~dummy () virtual default
Member Function Documentation
TypeName() [1/2]
TypeName ("dummy")
R() [1/2]
Foam::tmp< Foam::fvScalarMatrix > R (const volScalarField & alphai, volScalarField & kappai) const virtual
Implements IATEsource.
Definition at line 42 of file dummy.C.
References DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimTime, IATEsource::iate_, dummy::R(), and Foam::fvm::Su().
TypeName() [2/2]
TypeName ("dummy")
R() [2/2]
Foam::tmp< Foam::volScalarField > R () const virtual
Implements IATEsource.
Definition at line 42 of file dummy.C.
References Foam::dimless, Foam::dimTime, IATEsource::iate_, tmp< T >::New(), and Foam::Zero.
Referenced by dummy::R().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/twoPhaseSystem/diameterModels/IATE/IATEsources/dummy/dummy.H
src/phaseSystemModels/twoPhaseEuler/twoPhaseSystem/diameterModels/IATE/IATEsources/dummy/dummy.H
src/phaseSystemModels/reactingEuler/twoPhaseSystem/diameterModels/IATE/IATEsources/dummy/dummy.C
src/phaseSystemModels/twoPhaseEuler/twoPhaseSystem/diameterModels/IATE/IATEsources/dummy/dummy.C