OpenFOAM: fvMeshSubsetProxy Class Reference
fvMeshSubsetProxy Class Reference
Simple proxy for holding a mesh, or mesh-subset. The subMeshes are currently limited to cellSet or cellZone definitions.
#include <fvMeshSubsetProxy.H>
Public Types
enum subsetType { NONE , SET , ZONE , ZONES }
Public Member Functions
fvMeshSubsetProxy (fvMesh &baseMesh)
fvMeshSubsetProxy (fvMesh &baseMesh, const subsetType type, const word &selectionName, label exposedPatchId=-1)
fvMeshSubsetProxy (fvMesh &baseMesh, const wordRes &zoneNames, label exposedPatchId=-1)
fvMeshSubsetProxy (fvMesh &baseMesh, wordRes &&zoneNames, label exposedPatchId=-1)
const fvMesh & baseMesh () const noexcept
const fvMeshSubset & subsetter () const noexcept
fvMeshSubset & subsetter () noexcept
bool useSubMesh () const noexcept
const fvMesh & mesh () const
const word & name () const noexcept
const bitSet & selectedCells () const noexcept
void resetZones (const wordRes &zoneNames)
bool correct (bool verbose=false)
polyMesh::readUpdateState readUpdate ()
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > interpolateInternal (const DimensionedField< Type, volMesh > &df) const
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > interpolateInternal (const tmp< DimensionedField< Type, volMesh > > &tdf) const
template<class GeoField >
tmp< GeoField > interpolate (const GeoField &fld) const
template<class GeoField >
tmp< GeoField > interpolate (const tmp< GeoField > &fld) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > zeroGradientField (const DimensionedField< Type, volMesh > &df)
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > interpolateInternal (const fvMeshSubset &subsetter, const DimensionedField< Type, volMesh > &df)
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > interpolateInternal (const fvMeshSubset &subsetter, const tmp< DimensionedField< Type, volMesh > > &tdf)
template<class GeoField >
Foam::tmp< GeoField > interpolate (const fvMeshSubset &subsetter, const GeoField &fld)
template<class GeoField >
Foam::tmp< GeoField > interpolate (const fvMeshSubset &subsetter, const tmp< GeoField > &tfield)
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > interpolateInternal (const DimensionedField< Type, volMesh > &df) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > interpolateInternal (const tmp< DimensionedField< Type, volMesh > > &tdf) const
template<class GeoField >
Foam::tmp< GeoField > interpolate (const GeoField &fld) const
template<class GeoField >
Foam::tmp< GeoField > interpolate (const tmp< GeoField > &tfield) const
Static Public Member Functions
template<class Type >
static tmp< GeometricField< Type, fvPatchField, volMesh > > zeroGradientField (const DimensionedField< Type, volMesh > &df)
template<class Type >
static tmp< GeometricField< Type, fvPatchField, volMesh > > interpolateInternal (const fvMeshSubset &subsetter, const DimensionedField< Type, volMesh > &df)
template<class Type >
static tmp< GeometricField< Type, fvPatchField, volMesh > > interpolateInternal (const fvMeshSubset &subsetter, const tmp< DimensionedField< Type, volMesh > > &tdf)
template<class GeoField >
static tmp< GeoField > interpolate (const fvMeshSubset &subsetter, const GeoField &fld)
template<class GeoField >
static tmp< GeoField > interpolate (const fvMeshSubset &subsetter, const tmp< GeoField > &fld)
Detailed Description
Simple proxy for holding a mesh, or mesh-subset. The subMeshes are currently limited to cellSet or cellZone definitions.
Source files
fvMeshSubsetProxy.H
fvMeshSubsetProxy.C
fvMeshSubsetProxyTemplates.C
Definition at line 51 of file fvMeshSubsetProxy.H.
Member Enumeration Documentation
subsetType
enum subsetType
Enumerator
NONE
No subset.
SET
Subset with a cellSet.
ZONE
Subset with a cellZone.
ZONES
Subset with multiple cellZones.
Definition at line 58 of file fvMeshSubsetProxy.H.
Constructor & Destructor Documentation
fvMeshSubsetProxy() [1/4]
fvMeshSubsetProxy (fvMesh & baseMesh) explicit
Definition at line 40 of file fvMeshSubsetProxy.C.
fvMeshSubsetProxy() [2/4]
fvMeshSubsetProxy (fvMesh & baseMesh, const subsetType type, const word & selectionName, label exposedPatchId = -1)
Definition at line 52 of file fvMeshSubsetProxy.C.
References correct(), UList< T >::first(), List< T >::resize(), fvMeshSubsetProxy::SET, fvMeshSubsetProxy::ZONE, and fvMeshSubsetProxy::ZONES.
fvMeshSubsetProxy() [3/4]
fvMeshSubsetProxy (fvMesh & baseMesh, const wordRes & zoneNames, label exposedPatchId = -1)
Definition at line 83 of file fvMeshSubsetProxy.C.
References correct().
fvMeshSubsetProxy() [4/4]
fvMeshSubsetProxy (fvMesh & baseMesh, wordRes && zoneNames, label exposedPatchId = -1)
Definition at line 102 of file fvMeshSubsetProxy.C.
References correct().
Member Function Documentation
baseMesh()
const fvMesh & baseMesh () const inline noexcept
Definition at line 143 of file fvMeshSubsetProxy.H.
subsetter() [1/2]
const fvMeshSubset & subsetter () const inline noexcept
Definition at line 149 of file fvMeshSubsetProxy.H.
subsetter() [2/2]
fvMeshSubset & subsetter () inline noexcept
Definition at line 155 of file fvMeshSubsetProxy.H.
useSubMesh()
bool useSubMesh () const inline noexcept
Definition at line 161 of file fvMeshSubsetProxy.H.
References fvMeshSubsetProxy::NONE.
Referenced by fvMeshSubsetProxy::mesh().
mesh()
const fvMesh & mesh () const inline
Definition at line 167 of file fvMeshSubsetProxy.H.
References fvMeshSubset::subMesh(), and fvMeshSubsetProxy::useSubMesh().
name()
const word & name () const inline noexcept
Definition at line 178 of file fvMeshSubsetProxy.H.
selectedCells()
const bitSet & selectedCells () const inline noexcept
Definition at line 184 of file fvMeshSubsetProxy.H.
resetZones()
void resetZones (const wordRes & zoneNames)
Definition at line 123 of file fvMeshSubsetProxy.C.
References correct(), and UPtrList< T >::empty().
correct()
bool correct (bool verbose = false)
Definition at line 136 of file fvMeshSubsetProxy.C.
References PtrList< T >::clear(), UPtrList< T >::empty(), Foam::endl(), Foam::flatOutput(), Foam::Info, PackedList< Width >::resize(), Foam::returnReduceOr(), bitSet::set(), and PtrList< T >::transfer().
readUpdate()
Foam::polyMesh::readUpdateState readUpdate ()
Definition at line 200 of file fvMeshSubsetProxy.C.
References correct(), polyMesh::POINTS_MOVED, polyMesh::TOPO_CHANGE, and polyMesh::TOPO_PATCH_CHANGE.
zeroGradientField() [1/2]
template<class Type > static tmp< GeometricField< Type, fvPatchField, volMesh > > zeroGradientField (const DimensionedField< Type, volMesh > & df) static
interpolateInternal() [1/8]
template<class Type > static tmp< GeometricField< Type, fvPatchField, volMesh > > interpolateInternal (const fvMeshSubset & subsetter, const DimensionedField< Type, volMesh > & df) static
interpolateInternal() [2/8]
template<class Type > static tmp< GeometricField< Type, fvPatchField, volMesh > > interpolateInternal (const fvMeshSubset & subsetter, const tmp< DimensionedField< Type, volMesh > > & tdf) static
interpolate() [1/8]
template<class GeoField > static tmp< GeoField > interpolate (const fvMeshSubset & subsetter, const GeoField & fld) static
Referenced by vtkWrite::writeVolFieldsImpl(), vtkWrite::writeVolFieldsImpl(), and ensightWrite::writeVolFieldsImpl().
interpolate() [2/8]
template<class GeoField > static tmp< GeoField > interpolate (const fvMeshSubset & subsetter, const tmp< GeoField > & fld) static
interpolateInternal() [3/8]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > interpolateInternal (const DimensionedField< Type, volMesh > & df) const
interpolateInternal() [4/8]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > interpolateInternal (const tmp< DimensionedField< Type, volMesh > > & tdf) const
interpolate() [3/8]
template<class GeoField > tmp< GeoField > interpolate (const GeoField & fld) const
interpolate() [4/8]
template<class GeoField > tmp< GeoField > interpolate (const tmp< GeoField > & fld) const
zeroGradientField() [2/2]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > zeroGradientField (const DimensionedField< Type, volMesh > & df)
Definition at line 32 of file fvMeshSubsetProxyTemplates.C.
References io(), Foam::New(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, Foam::Zero, and fvPatchFieldBase::zeroGradientType().
interpolateInternal() [5/8]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > interpolateInternal (const fvMeshSubset & subsetter, const DimensionedField< Type, volMesh > & df)
Definition at line 59 of file fvMeshSubsetProxyTemplates.C.
References fvMeshSubset::hasSubMesh(), and Foam::interpolate().
interpolateInternal() [6/8]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > interpolateInternal (const fvMeshSubset & subsetter, const tmp< DimensionedField< Type, volMesh > > & tdf)
Definition at line 78 of file fvMeshSubsetProxyTemplates.C.
References PtrList< T >::clear(), fvMeshSubset::hasSubMesh(), and Foam::interpolate().
interpolate() [5/8]
template<class GeoField > Foam::tmp< GeoField > interpolate (const fvMeshSubset & subsetter, const GeoField & fld)
Definition at line 113 of file fvMeshSubsetProxyTemplates.C.
References fld(), fvMeshSubset::hasSubMesh(), and fvMeshSubset::interpolate().
interpolate() [6/8]
template<class GeoField > Foam::tmp< GeoField > interpolate (const fvMeshSubset & subsetter, const tmp< GeoField > & tfield)
Definition at line 134 of file fvMeshSubsetProxyTemplates.C.
References PtrList< T >::clear(), fvMeshSubset::hasSubMesh(), and Foam::interpolate().
interpolateInternal() [7/8]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > interpolateInternal (const DimensionedField< Type, volMesh > & df) const
Definition at line 157 of file fvMeshSubsetProxyTemplates.C.
interpolateInternal() [8/8]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > interpolateInternal (const tmp< DimensionedField< Type, volMesh > > & tdf) const
Definition at line 168 of file fvMeshSubsetProxyTemplates.C.
interpolate() [7/8]
template<class GeoField > Foam::tmp< GeoField > interpolate (const GeoField & fld) const
Definition at line 179 of file fvMeshSubsetProxyTemplates.C.
References fld(), and Foam::interpolate().
interpolate() [8/8]
template<class GeoField > Foam::tmp< GeoField > interpolate (const tmp< GeoField > & tfield) const
Definition at line 187 of file fvMeshSubsetProxyTemplates.C.
References Foam::interpolate().
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/fvMeshSubset/fvMeshSubsetProxy.H
src/finiteVolume/fvMesh/fvMeshSubset/fvMeshSubsetProxy.C
src/finiteVolume/fvMesh/fvMeshSubset/fvMeshSubsetProxyTemplates.C