OpenFOAM: writeFreeSurface Class Reference
writeFreeSurface Class Reference
A function object to write the control points on the free surface.
#include <writeFreeSurface.H>
Public Member Functions
TypeName ("writeFreeSurface")
writeFreeSurface (const word &name, const Time &runTime, const dictionary &dict)
virtual bool start ()
virtual bool execute ()
virtual bool read (const dictionary &dict)
virtual bool write ()
Public Member Functions inherited from functionObject
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name, const bool withNamePrefix=defaultUseNamePrefix)
autoPtr< functionObject > clone () const
virtual ~functionObject ()=default
virtual const word & type () const =0
const word & name () const noexcept
bool useNamePrefix () const noexcept
bool useNamePrefix (bool on) noexcept
virtual bool execute (const label subIndex)
virtual bool end ()
virtual bool adjustTimeStep ()
virtual bool filesModified () const
virtual void updateMesh (const mapPolyMesh &mpm)
virtual void movePoints (const polyMesh &mesh)
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &runTime, const dictionary &dict)
Public Attributes inherited from functionObject
bool log
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
static bool defaultUseNamePrefix
static word outputPrefix
Protected Member Functions inherited from functionObject
word scopedName (const word &name) const
Detailed Description
A function object to write the control points on the free surface.
Source files
writeFreeSurface.H
writeFreeSurface.C
Definition at line 49 of file writeFreeSurface.H.
Constructor & Destructor Documentation
writeFreeSurface()
writeFreeSurface (const word & name, const Time & runTime, const dictionary & dict)
Definition at line 67 of file writeFreeSurface.C.
References Foam::endl(), Foam::Info, functionObject::name(), and dictionary::readIfPresent().
Member Function Documentation
TypeName()
TypeName ("writeFreeSurface")
start()
bool start () virtual
Definition at line 87 of file writeFreeSurface.C.
References Foam::writeData().
execute()
bool execute () virtual
Implements functionObject.
Definition at line 93 of file writeFreeSurface.C.
References Foam::writeData().
read()
bool read (const dictionary & dict) virtual
Reimplemented from functionObject.
Definition at line 99 of file writeFreeSurface.C.
References dict, and dictionary::readIfPresent().
write()
virtual bool write () inline virtual
Implements functionObject.
Definition at line 105 of file writeFreeSurface.H.
The documentation for this class was generated from the following files:
src/dynamicFaMesh/interfaceTrackingFvMesh/functionObjects/writeFreeSurface/writeFreeSurface.H
src/dynamicFaMesh/interfaceTrackingFvMesh/functionObjects/writeFreeSurface/writeFreeSurface.C