OpenFOAM: objectHit Class Reference
objectHit Class Reference
This class describes a combination of target object index and success flag. Behaves somewhat like std::optional.
#include <objectHit.H>
Public Member Functions
constexpr objectHit () noexcept
objectHit (const bool success, const label index) noexcept
objectHit (Istream &is)
bool hit () const noexcept
label index () const noexcept
label hitObject () const noexcept
void reset () noexcept
void setHit () noexcept
void setMiss () noexcept
void setIndex (const label index) noexcept
Friends
Ostream & operator<< (Ostream &os, const objectHit &obj)
Detailed Description
This class describes a combination of target object index and success flag. Behaves somewhat like std::optional.
Definition at line 48 of file objectHit.H.
Constructor & Destructor Documentation
objectHit() [1/3]
constexpr objectHit () inline constexpr noexcept
Definition at line 64 of file objectHit.H.
objectHit() [2/3]
objectHit (const bool success, const label index) inline noexcept
Definition at line 71 of file objectHit.H.
objectHit() [3/3]
objectHit (Istream & is) inline explicit
Definition at line 78 of file objectHit.H.
Member Function Documentation
hit()
bool hit () const inline noexcept
Definition at line 90 of file objectHit.H.
Referenced by Foam::operator==().
index()
label index () const inline noexcept
Definition at line 96 of file objectHit.H.
Referenced by Foam::operator==(), and objectHit::setIndex().
hitObject()
label hitObject () const inline noexcept
Definition at line 102 of file objectHit.H.
reset()
void reset () inline noexcept
Definition at line 111 of file objectHit.H.
setHit()
void setHit () inline noexcept
Definition at line 118 of file objectHit.H.
setMiss()
void setMiss () inline noexcept
Definition at line 124 of file objectHit.H.
setIndex()
void setIndex (const label index) inline noexcept
Definition at line 130 of file objectHit.H.
References objectHit::index().
Friends And Related Symbol Documentation
operator<<
Ostream & operator<< (Ostream & os, const objectHit & obj) friend
Definition at line 138 of file objectHit.H.
The documentation for this class was generated from the following file:
src/OpenFOAM/meshes/primitiveShapes/objectHit/objectHit.H