OpenFOAM: thermoCloud Class Reference
thermoCloud Class Reference abstract
Virtual abstract base class for templated ThermoCloud.
#include <thermoCloud.H>
Public Member Functions
TypeName ("thermoCloud")
thermoCloud ()=default
virtual ~thermoCloud ()=default
virtual tmp< volScalarField > Ep () const =0
virtual tmp< volScalarField > ap () const =0
virtual tmp< volScalarField > sigmap () const =0
Detailed Description
Virtual abstract base class for templated ThermoCloud.
Source files
thermoCloud.H
thermoCloud.C
Definition at line 46 of file thermoCloud.H.
Constructor & Destructor Documentation
thermoCloud()
thermoCloud () default
~thermoCloud()
virtual ~thermoCloud () virtual default
Member Function Documentation
TypeName()
TypeName ("thermoCloud")
Ep()
virtual tmp< volScalarField > Ep () const pure virtual
Implemented in ThermoCloud< CloudType >, and ThermoCloud< Foam::DSMCCloud >.
Referenced by cloudAbsorptionEmission::EDisp().
ap()
virtual tmp< volScalarField > ap () const pure virtual
Implemented in ThermoCloud< CloudType >, and ThermoCloud< Foam::DSMCCloud >.
Referenced by cloudAbsorptionEmission::aDisp().
sigmap()
virtual tmp< volScalarField > sigmap () const pure virtual
Implemented in ThermoCloud< CloudType >, and ThermoCloud< Foam::DSMCCloud >.
Referenced by cloudScatter::sigmaEff().
The documentation for this class was generated from the following file:
src/lagrangian/intermediate/clouds/baseClasses/thermoCloud/thermoCloud.H