OpenFOAM: searchableSurfaceToFace Class Reference
searchableSurfaceToFace Class Reference
A topoSetFaceSource to select faces whose face centre enclosed by a given searchableSurface.
#include <searchableSurfaceToFace.H>
Public Member Functions
TypeName ("searchableSurfaceToFace")
searchableSurfaceToFace (const word &surfaceType, const polyMesh &mesh, const dictionary &dict)
searchableSurfaceToFace (const polyMesh &mesh, const dictionary &dict)
virtual ~searchableSurfaceToFace ()=default
virtual void applyToSet (const topoSetSource::setAction action, topoSet &set) const
Public Member Functions inherited from topoSetFaceSource
declareRunTimeSelectionTable (autoPtr, topoSetFaceSource, word,(const polyMesh &mesh, const dictionary &dict),(mesh, dict))
declareRunTimeSelectionTable (autoPtr, topoSetFaceSource, istream,(const polyMesh &mesh, Istream &is),(mesh, is))
topoSetFaceSource (const polyMesh &mesh)
topoSetFaceSource (const polyMesh &mesh, const dictionary &dict)
autoPtr< topoSetFaceSource > clone () const
virtual ~topoSetFaceSource ()=default
virtual topoSetSource::sourceType setType () const
Public Member Functions inherited from topoSetSource
TypeName ("topoSetSource")
declareRunTimeSelectionTable (autoPtr, topoSetSource, word,(const polyMesh &mesh, const dictionary &dict),(mesh, dict))
declareRunTimeSelectionTable (autoPtr, topoSetSource, istream,(const polyMesh &mesh, Istream &is),(mesh, is))
topoSetSource (const polyMesh &mesh, bool verbose=true)
topoSetSource (const polyMesh &mesh, const dictionary &dict)
autoPtr< topoSetSource > clone () const
virtual ~topoSetSource ()=default
const polyMesh & mesh () const noexcept
bool verbose () const noexcept
bool verbose (bool on) noexcept
void verbose (const dictionary &dict)
Additional Inherited Members
Public Types inherited from topoSetSource
enum sourceType {
UNKNOWN_SOURCE = 0 , CELL_TYPE = 0x1 , FACE_TYPE = 0x2 , POINT_TYPE = 0x4 ,
SET_SOURCE = 0x10 , CELLSET_SOURCE = (CELL_TYPE | SET_SOURCE) , FACESET_SOURCE = (FACE_TYPE | SET_SOURCE) , POINTSET_SOURCE = (POINT_TYPE | SET_SOURCE) ,
ZONE_SOURCE = 0x20 , CELLZONE_SOURCE = (CELL_TYPE | ZONE_SOURCE) , FACEZONE_SOURCE = (FACE_TYPE | ZONE_SOURCE) , POINTZONE_SOURCE = (POINT_TYPE | ZONE_SOURCE) ,
CELLSETSOURCE = CELLSET_SOURCE , FACESETSOURCE = FACESET_SOURCE , POINTSETSOURCE = POINTSET_SOURCE , CELLZONESOURCE = CELLZONE_SOURCE ,
FACEZONESOURCE = FACEZONE_SOURCE , POINTZONESOURCE = POINTZONE_SOURCE
}
enum setAction {
ADD , SUBTRACT , NEW , SUBSET ,
INVERT , CLEAR , REMOVE , LIST ,
IGNORE , DELETE = SUBTRACT
}
Static Public Member Functions inherited from topoSetFaceSource
static autoPtr< topoSetFaceSource > New (const word &sourceType, const polyMesh &mesh, const dictionary &dict)
static autoPtr< topoSetFaceSource > New (const word &sourceType, const polyMesh &mesh, Istream &is)
Static Public Member Functions inherited from topoSetSource
static Istream & checkIs (Istream &is)
static bool isSetSource (const sourceType t) noexcept
static bool isZoneSource (const sourceType t) noexcept
static bool isCell (const sourceType t) noexcept
static bool isFace (const sourceType t) noexcept
static bool isPoint (const sourceType t) noexcept
static const string & usage (const word &name)
static autoPtr< topoSetSource > New (const word &topoSetSourceType, const polyMesh &mesh, const dictionary &dict)
static autoPtr< topoSetSource > New (const word &topoSetSourceType, const polyMesh &mesh, Istream &is)
static setAction toAction (const word &actionName)
Static Public Attributes inherited from topoSetSource
static const Enum< setAction > actionNames
static const Enum< setAction > combineNames
Protected Member Functions inherited from topoSetSource
void addOrDelete (topoSet &set, const label id, const bool add) const
void addOrDelete (topoSet &set, const labelUList &labels, const bool add) const
void addOrDelete (topoSet &set, const bitSet &labels, const bool add) const
topoSetSource (const topoSetSource &)=delete
void operator= (const topoSetSource &)=delete
Static Protected Member Functions inherited from topoSetSource
static bool check (labelList &list, const label maxLabel)
Protected Attributes inherited from topoSetSource
const polyMesh & mesh_
bool verbose_
Static Protected Attributes inherited from topoSetSource
static const string illegalSource_
static HashTable< string > * usageTablePtr_ = nullptr
Detailed Description
A topoSetFaceSource to select faces whose face centre enclosed by a given searchableSurface.
The surface has to be closed - if not a warning will be given: "The surface XXX appears to be unclosed ... ignoring" and the surface will not be used.
Operands:
Operand Type Location
input triSurface $FOAM_CASE/constant/triSurface/<file>
output faceSet $FOAM_CASE/constant/polyMesh/sets/<set>
Usage
Minimal example by using system/topoSetDict.actions:
{
    // Mandatory (inherited) entries
    name        <name>;
    type        faceSet;
    action      <action>;
    // Mandatory entries
    source      searchableSurfaceToFace;
    surfaceType <surfaceTypeName>;
    // Optional entries
    surfaceName <surfaceName>;
}
where the entries mean:
Property Description Type Req'd Dflt
name Name of faceSet word yes -
type Type name: faceSet word yes -
action Action applied on faces - see below word yes -
source Source name: searchableSurfaceToFace word yes -
surfaceType The searchable surface type word yes -
surfaceName Name for the IOobject word no mesh-name
Options for the action entry:
      new      | Create a new faceSet from selected faces
      add      | Add selected faces into this faceSet
      subtract | Remove selected faces from this faceSet
See also
Foam::topoSetSource
Foam::topoSetFaceSource
Source files
searchableSurfaceToFace.H
searchableSurfaceToFace.C
Definition at line 153 of file searchableSurfaceToFace.H.
Constructor & Destructor Documentation
searchableSurfaceToFace() [1/2]
searchableSurfaceToFace (const word & surfaceType, const polyMesh & mesh, const dictionary & dict)
Definition at line 119 of file searchableSurfaceToFace.C.
References PtrList< T >::clear(), Foam::endl(), Foam::nl, and WarningInFunction.
searchableSurfaceToFace() [2/2]
searchableSurfaceToFace (const polyMesh & mesh, const dictionary & dict)
Definition at line 158 of file searchableSurfaceToFace.C.
~searchableSurfaceToFace()
virtual ~searchableSurfaceToFace () virtual default
Member Function Documentation
TypeName()
TypeName ("searchableSurfaceToFace")
applyToSet()
void applyToSet (const topoSetSource::setAction action, topoSet & set) const virtual
Implements topoSetSource.
Definition at line 175 of file searchableSurfaceToFace.C.
References topoSetSource::ADD, Foam::endl(), Foam::Info, topoSetSource::NEW, and topoSetSource::SUBTRACT.
The documentation for this class was generated from the following files:
src/meshTools/topoSet/faceSources/searchableSurfaceToFace/searchableSurfaceToFace.H
src/meshTools/topoSet/faceSources/searchableSurfaceToFace/searchableSurfaceToFace.C