OpenFOAM: cellVolumeWeight Class Reference
cellVolumeWeight Class Reference
Volume-weighted interpolation stencil.
#include <cellVolumeWeightCellCellStencil.H>
Public Member Functions
TypeName ("cellVolumeWeight")
cellVolumeWeight (const fvMesh &, const dictionary &, const bool doUpdate)
virtual ~cellVolumeWeight ()
scalar overlapTolerance () const
virtual bool update ()
virtual const labelUList & cellTypes () const
virtual const labelUList & interpolationCells () const
virtual const mapDistribute & cellInterpolationMap () const
virtual const labelListList & cellStencil () const
virtual const List< scalarList > & cellInterpolationWeights () const
virtual const scalarList & cellInterpolationWeight () const
virtual void stencilWeights (const point &sample, const pointList &donorCcs, scalarList &weights) const
Public Member Functions inherited from cellCellStencil
TypeName ("cellCellStencil")
declareRunTimeSelectionTable (autoPtr, cellCellStencil, mesh,(const fvMesh &mesh, const dictionary &dict, const bool update),(mesh, dict, update))
cellCellStencil (const fvMesh &)
virtual ~cellCellStencil ()
virtual const wordHashSet & nonInterpolatedFields () const
virtual wordHashSet & nonInterpolatedFields ()
bool localStencil (const labelUList &) const
const labelIOList & zoneID () const
template<class T >
void interpolate (const fvMesh &mesh, Field< T > &psi) const
template<class GeoField >
void interpolate (GeoField &psi) const
template<class GeoField >
void interpolate (const fvMesh &mesh, const wordHashSet &suppressed) const
void walkFront (const globalIndex &globalCells, const scalar layerRelax, const labelListList &allStencil, labelList &allCellTypes, scalarField &allWeight, const scalarList &compactCellVol, const labelListList &compactStencil, const labelList &zoneID, const label holeLayers, const label useLayer) const
void setUpFront (const labelList &allCellTypes, bitSet &isFront) const
void setUpFrontOnOversetPatch (const labelList &allCellTypes, bitSet &isFront) const
void seedCell (const label cellI, const scalar wantedFraction, bitSet &isFront, scalarField &fraction) const
InfoProxy< cellCellStencil > info () const noexcept
template<class Type >
Foam::tmp< Foam::volScalarField > createField (const fvMesh &mesh, const word &name, const UList< Type > &psi)
Protected Member Functions
void findHoles (const globalIndex &globalCells, const fvMesh &mesh, const labelList &zoneID, const labelListList &stencil, labelList &cellTypes) const
void markPatchCells (const fvMesh &mesh, const labelList &cellMap, labelList &patchCellTypes) const
void combineCellTypes (const label subZoneID, const fvMesh &subMesh, const labelList &subCellMap, const label donorZoneID, const labelListList &toOtherCells, const List< scalarList > &weights, const labelList &otherCells, const labelList &interpolatedOtherPatchTypes, labelListList &allStencil, scalarListList &allWeights, labelList &allCellTypes, labelList &allDonorID) const
void interpolatePatchTypes (const labelListList &addressing, const labelList &patchTypes, labelList &result) const
void interpolatePatchTypes (const autoPtr< mapDistribute > &mapPtr, const labelListList &addressing, const labelList &patchTypes, labelList &result) const
Protected Attributes
const dictionary dict_
scalar overlapTolerance_
labelList cellTypes_
labelList interpolationCells_
autoPtr< mapDistribute > cellInterpolationMap_
labelListList cellStencil_
List< scalarList > cellInterpolationWeights_
volScalarField cellInterpolationWeight_
const bool allowInterpolatedDonors_
Protected Attributes inherited from cellCellStencil
const fvMesh & mesh_
wordHashSet nonInterpolatedFields_
const dictionary dict_
Static Protected Attributes
static scalar defaultOverlapTolerance_ = 1e-6
Static Protected Attributes inherited from cellCellStencil
static const Enum< cellType > cellTypeNames_
Additional Inherited Members
Public Types inherited from cellCellStencil
enum patchCellType { OTHER = 0 , PATCH = 1 , OVERSET = 2 }
enum cellType {
CALCULATED = 0 , INTERPOLATED = 1 , HOLE = 2 , SPECIAL = 3 ,
POROUS = 4
}
Static Public Member Functions inherited from cellCellStencil
static autoPtr< cellCellStencil > New (const fvMesh &, const dictionary &dict, const bool update=true)
static const labelIOList & zoneID (const fvMesh &)
static labelList count (const label size, const labelUList &lst)
static void globalCellCells (const globalIndex &gi, const polyMesh &mesh, const boolList &isValidDonor, const labelList &selectedCells, labelListList &cellCells, pointListList &cellCellCentres)
template<class T >
static void interpolate (Field< T > &psi, const fvMesh &mesh, const cellCellStencil &overlap, const List< scalarList > &wghts)
template<class GeoField , class SuppressBC >
static void correctBoundaryConditions (GeoField &psi)
Static Protected Member Functions inherited from cellCellStencil
template<class Type >
static tmp< volScalarField > createField (const fvMesh &mesh, const word &name, const UList< Type > &)
static word baseName (const word &name)
Detailed Description
Volume-weighted interpolation stencil.
Source files
cellVolumeWeightCellCellStencil.H
cellVolumeWeightCellCellStencil.C
cellVolumeWeightCellCellStencilTemplates.C
Definition at line 50 of file cellVolumeWeightCellCellStencil.H.
Constructor & Destructor Documentation
cellVolumeWeight()
cellVolumeWeight (const fvMesh & mesh, const dictionary & dict, const bool doUpdate)
Definition at line 502 of file cellVolumeWeightCellCellStencil.C.
References cellVolumeWeight::cellTypes_, cellVolumeWeight::defaultOverlapTolerance_, cellVolumeWeight::dict_, Foam::endl(), forAll, HashSet< Key, Hash >::insert(), io(), cellCellStencil::mesh_, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, cellCellStencil::nonInterpolatedFields_, cellVolumeWeight::overlapTolerance_, Foam::Pout, IOobjectOption::READ_IF_PRESENT, cellVolumeWeight::update(), and cellCellStencil::zoneID().
~cellVolumeWeight()
~cellVolumeWeight () virtual
Definition at line 589 of file cellVolumeWeightCellCellStencil.C.
Member Function Documentation
findHoles()
void findHoles (const globalIndex & globalCells, const fvMesh & mesh, const labelList & zoneID, const labelListList & stencil, labelList & cellTypes) const protected
Definition at line 53 of file cellVolumeWeightCellCellStencil.C.
References cellVolumeWeight::cellTypes(), fvPatch::constraintType(), mapDistribute::distribute(), Foam::endl(), forAll, cellCellStencil::HOLE, Foam::Info, Pstream::listCombineReduce(), mesh, Foam::nl, pbm, Foam::returnReduceOr(), syncTools::swapBoundaryCellList(), Foam::type(), and Foam::Zero.
markPatchCells()
void markPatchCells (const fvMesh & mesh, const labelList & cellMap, labelList & patchCellTypes) const protected
Definition at line 285 of file cellVolumeWeightCellCellStencil.C.
References fvPatch::constraintType(), forAll, mesh, and pbm.
combineCellTypes()
void combineCellTypes (const label subZoneID, const fvMesh & subMesh, const labelList & subCellMap, const label donorZoneID, const labelListList & toOtherCells, const List< scalarList > & weights, const labelList & otherCells, const labelList & interpolatedOtherPatchTypes, labelListList & allStencil, scalarListList & allWeights, labelList & allCellTypes, labelList & allDonorID) const protected
Definition at line 394 of file cellVolumeWeightCellCellStencil.C.
References forAll, and Foam::mag().
interpolatePatchTypes() [1/2]
void interpolatePatchTypes (const labelListList & addressing, const labelList & patchTypes, labelList & result) const protected
Definition at line 325 of file cellVolumeWeightCellCellStencil.C.
References forAll, patchTypes(), and Foam::type().
interpolatePatchTypes() [2/2]
void interpolatePatchTypes (const autoPtr< mapDistribute > & mapPtr, const labelListList & addressing, const labelList & patchTypes, labelList & result) const protected
Definition at line 361 of file cellVolumeWeightCellCellStencil.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, patchTypes(), and UList< T >::size().
TypeName()
TypeName ("cellVolumeWeight")
overlapTolerance()
scalar overlapTolerance () const inline
Definition at line 178 of file cellVolumeWeightCellCellStencil.H.
References cellVolumeWeight::overlapTolerance_.
update()
bool update () virtual
Implements cellCellStencil.
Definition at line 595 of file cellVolumeWeightCellCellStencil.C.
References PtrList< T >::append(), PtrList< T >::clear(), oversetFvMeshBase::correctBoundaryConditions(), Foam::decrIndent(), mapDistribute::distribute(), Foam::endl(), forAll, Foam::gMax(), meshToMesh::imCellVolumeWeight, Foam::incrIndent(), Foam::indent(), Foam::Info, Pstream::listCombineReduce(), Foam::mkDir(), OFstream::name(), Foam::nl, meshToMesh::pmAABB, Foam::Pout, Foam::reduce(), Foam::returnReduce(), s(), PtrList< T >::set(), UPtrList< T >::size(), meshToMesh::srcMap(), meshToMesh::srcToTgtCellAddr(), meshToMesh::srcToTgtCellWght(), Foam::sum(), meshToMesh::tgtMap(), meshToMesh::tgtToSrcCellAddr(), meshToMesh::tgtToSrcCellWght(), PtrList< T >::transfer(), OBJstream::writeLine(), and Foam::Zero.
Referenced by cellVolumeWeight::cellInterpolationMap(), and cellVolumeWeight::cellVolumeWeight().
cellTypes()
virtual const labelUList & cellTypes () const inline virtual
Implements cellCellStencil.
Definition at line 187 of file cellVolumeWeightCellCellStencil.H.
References cellVolumeWeight::cellTypes_.
Referenced by cellVolumeWeight::findHoles().
interpolationCells()
virtual const labelUList & interpolationCells () const inline virtual
Implements cellCellStencil.
Definition at line 193 of file cellVolumeWeightCellCellStencil.H.
References cellVolumeWeight::interpolationCells_.
cellInterpolationMap()
virtual const mapDistribute & cellInterpolationMap () const inline virtual
Implements cellCellStencil.
Definition at line 199 of file cellVolumeWeightCellCellStencil.H.
References cellVolumeWeight::cellInterpolationMap_, and cellVolumeWeight::update().
cellStencil()
virtual const labelListList & cellStencil () const inline virtual
Implements cellCellStencil.
Definition at line 210 of file cellVolumeWeightCellCellStencil.H.
References cellVolumeWeight::cellStencil_.
cellInterpolationWeights()
virtual const List< scalarList > & cellInterpolationWeights () const inline virtual
Implements cellCellStencil.
Definition at line 216 of file cellVolumeWeightCellCellStencil.H.
References cellVolumeWeight::cellInterpolationWeights_.
cellInterpolationWeight()
virtual const scalarList & cellInterpolationWeight () const inline virtual
Implements cellCellStencil.
Definition at line 223 of file cellVolumeWeightCellCellStencil.H.
References cellVolumeWeight::cellInterpolationWeight_.
stencilWeights()
void stencilWeights (const point & sample, const pointList & donorCcs, scalarList & weights) const virtual
Implements cellCellStencil.
Definition at line 1114 of file cellVolumeWeightCellCellStencil.C.
References forAll, Foam::mag(), List< T >::setSize(), UPtrList< T >::size(), and Foam::sum().
Member Data Documentation
defaultOverlapTolerance_
Foam::scalar defaultOverlapTolerance_ = 1e-6 static protected
Definition at line 59 of file cellVolumeWeightCellCellStencil.H.
Referenced by cellVolumeWeight::cellVolumeWeight().
dict_
const dictionary dict_ protected
Definition at line 65 of file cellVolumeWeightCellCellStencil.H.
Referenced by cellVolumeWeight::cellVolumeWeight().
overlapTolerance_
scalar overlapTolerance_ protected
Definition at line 68 of file cellVolumeWeightCellCellStencil.H.
Referenced by cellVolumeWeight::cellVolumeWeight(), and cellVolumeWeight::overlapTolerance().
cellTypes_
labelList cellTypes_ protected
Definition at line 71 of file cellVolumeWeightCellCellStencil.H.
Referenced by cellVolumeWeight::cellTypes(), and cellVolumeWeight::cellVolumeWeight().
interpolationCells_
labelList interpolationCells_ protected
Definition at line 74 of file cellVolumeWeightCellCellStencil.H.
Referenced by cellVolumeWeight::interpolationCells().
cellInterpolationMap_
autoPtr<mapDistribute> cellInterpolationMap_ protected
Definition at line 77 of file cellVolumeWeightCellCellStencil.H.
Referenced by cellVolumeWeight::cellInterpolationMap().
cellStencil_
labelListList cellStencil_ protected
Definition at line 80 of file cellVolumeWeightCellCellStencil.H.
Referenced by cellVolumeWeight::cellStencil().
cellInterpolationWeights_
List<scalarList> cellInterpolationWeights_ protected
Definition at line 83 of file cellVolumeWeightCellCellStencil.H.
Referenced by cellVolumeWeight::cellInterpolationWeights().
cellInterpolationWeight_
volScalarField cellInterpolationWeight_ protected
Definition at line 86 of file cellVolumeWeightCellCellStencil.H.
Referenced by cellVolumeWeight::cellInterpolationWeight().
allowInterpolatedDonors_
const bool allowInterpolatedDonors_ protected
Definition at line 89 of file cellVolumeWeightCellCellStencil.H.
The documentation for this class was generated from the following files:
src/overset/cellCellStencil/cellVolumeWeight/cellVolumeWeightCellCellStencil.H
src/overset/cellCellStencil/cellVolumeWeight/cellVolumeWeightCellCellStencil.C