OpenFOAM: freestreamPressureFvPatchScalarField Class Reference
freestreamPressureFvPatchScalarField Class Reference
Boundary conditions » Inlet | Boundary conditions » Outlet
This boundary condition provides a free-stream condition for pressure.
#include <freestreamPressureFvPatchScalarField.H>
Public Member Functions
TypeName ("freestreamPressure")
freestreamPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
freestreamPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
freestreamPressureFvPatchScalarField (const freestreamPressureFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
freestreamPressureFvPatchScalarField (const freestreamPressureFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
freestreamPressureFvPatchScalarField (const freestreamPressureFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
const scalarField & freestreamValue () const
scalarField & freestreamValue ()
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
This boundary condition provides a free-stream condition for pressure.
It is an outlet-inlet condition that uses the velocity orientation to continuously blend between zero gradient for normal inlet and fixed value for normal outlet flow.
Usage
Property Description Required Default value
U velocity field name no U
freestreamValue freestream pressure yes
Example of the boundary condition specification:
    <patchName>
    {
        type            freestreamPressure;
        freestreamValue uniform 1e5;
    }
Note
This condition is designed to operate with a freestreamVelocity condition
See also
Foam::mixedFvPatchField Foam::freestreamFvPatchField
Source files
freestreamPressureFvPatchScalarField.H
freestreamPressureFvPatchScalarField.C
Definition at line 92 of file freestreamPressureFvPatchScalarField.H.
Constructor & Destructor Documentation
freestreamPressureFvPatchScalarField() [1/5]
freestreamPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 28 of file freestreamPressureFvPatchScalarField.C.
freestreamPressureFvPatchScalarField() [2/5]
freestreamPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 40 of file freestreamPressureFvPatchScalarField.C.
References dict, freestreamPressureFvPatchScalarField::freestreamValue(), fvPatchField< scalar >::operator=(), p, and Foam::Zero.
freestreamPressureFvPatchScalarField() [3/5]
freestreamPressureFvPatchScalarField (const freestreamPressureFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 63 of file freestreamPressureFvPatchScalarField.C.
freestreamPressureFvPatchScalarField() [4/5]
freestreamPressureFvPatchScalarField (const freestreamPressureFvPatchScalarField & wbppsf)
Definition at line 77 of file freestreamPressureFvPatchScalarField.C.
freestreamPressureFvPatchScalarField() [5/5]
freestreamPressureFvPatchScalarField (const freestreamPressureFvPatchScalarField & wbppsf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 88 of file freestreamPressureFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("freestreamPressure")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 142 of file freestreamPressureFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 158 of file freestreamPressureFvPatchScalarField.H.
freestreamValue() [1/2]
const scalarField & freestreamValue () const inline
Definition at line 173 of file freestreamPressureFvPatchScalarField.H.
Referenced by freestreamPressureFvPatchScalarField::freestreamPressureFvPatchScalarField().
freestreamValue() [2/2]
scalarField & freestreamValue () inline
Definition at line 176 of file freestreamPressureFvPatchScalarField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 102 of file freestreamPressureFvPatchScalarField.C.
References Foam::mag(), and fvPatchField< Type >::updateCoeffs().
write()
void write (Ostream & os) const virtual
Definition at line 118 of file freestreamPressureFvPatchScalarField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntryIfDifferent(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/freestreamPressure/freestreamPressureFvPatchScalarField.H
src/finiteVolume/fields/fvPatchFields/derived/freestreamPressure/freestreamPressureFvPatchScalarField.C