OpenFOAM: hTabulatedThermo< EquationOfState > Class Template Reference
hTabulatedThermo< EquationOfState > Class Template Reference
Enthalpy based thermodynamics package using non-uniform tabulated data for heat capacity vs temperature.
#include <hTabulatedThermo.H>
Public Member Functions
hTabulatedThermo (const dictionary &dict)
hTabulatedThermo (const word &, const hTabulatedThermo &)
scalar limit (const scalar T) const
scalar Cp (const scalar p, const scalar T) const
scalar Ha (const scalar p, const scalar T) const
scalar Hs (const scalar p, const scalar T) const
scalar Hc () const
scalar S (const scalar p, const scalar T) const
scalar Gstd (const scalar T) const
scalar dCpdT (const scalar p, const scalar T) const
void write (Ostream &os) const
Static Public Member Functions
static word typeName ()
Friends
Ostream & operator<< (Ostream &, const hTabulatedThermo &)
Detailed Description
template<class EquationOfState>
class Foam::hTabulatedThermo< EquationOfState >
Enthalpy based thermodynamics package using non-uniform tabulated data for heat capacity vs temperature.
Usage
Property Description
Hf Heat of formation
Sf Standard entropy
Cp Specific heat at constant pressure vs temperature table
Example of the specification of the thermodynamic properties:
    thermodynamics
    {
        Hf              0;
        Sf              0;
        Cp
        (
            (200     1005)
            (350     1010)
            (400     1020)
        );
    }
Source files
hTabulatedThermo.H
hTabulatedThermoI.H
hTabulatedThermo.C
See also
Foam::thermophysicalFunctions::nonUniformTable
Definition at line 101 of file hTabulatedThermo.H.
Constructor & Destructor Documentation
hTabulatedThermo() [1/2]
template<class EquationOfState > hTabulatedThermo (const dictionary & dict) explicit
Definition at line 28 of file hTabulatedThermo.C.
hTabulatedThermo() [2/2]
template<class EquationOfState > hTabulatedThermo (const word & name, const hTabulatedThermo< EquationOfState > & pt) inline
Definition at line 26 of file hTabulatedThermoI.H.
References Foam::name().
Member Function Documentation
typeName()
template<class EquationOfState > static word typeName () inline static
Definition at line 137 of file hTabulatedThermo.H.
limit()
template<class EquationOfState > Foam::scalar limit (const scalar T) const inline
Definition at line 42 of file hTabulatedThermoI.H.
References T.
Cp()
template<class EquationOfState > Foam::scalar Cp (const scalar p, const scalar T) const inline
Definition at line 52 of file hTabulatedThermoI.H.
References p, and T.
Ha()
template<class EquationOfState > Foam::scalar Ha (const scalar p, const scalar T) const inline
Definition at line 63 of file hTabulatedThermoI.H.
References Hs(), p, and T.
Hs()
template<class EquationOfState > Foam::scalar Hs (const scalar p, const scalar T) const inline
Definition at line 74 of file hTabulatedThermoI.H.
References p, and T.
Hc()
template<class EquationOfState > Foam::scalar Hc () const inline
Definition at line 85 of file hTabulatedThermoI.H.
S()
template<class EquationOfState > Foam::scalar S (const scalar p, const scalar T) const inline
Definition at line 93 of file hTabulatedThermoI.H.
References p, and T.
Gstd()
template<class EquationOfState > Foam::scalar Gstd (const scalar T) const inline
Definition at line 104 of file hTabulatedThermoI.H.
References T.
dCpdT()
template<class EquationOfState > Foam::scalar dCpdT (const scalar p, const scalar T) const inline
Definition at line 114 of file hTabulatedThermoI.H.
References p, and T.
write()
template<class EquationOfState > void write (Ostream & os) const
Definition at line 43 of file hTabulatedThermo.C.
References Ostream::beginBlock(), Ostream::endBlock(), os(), and Ostream::writeEntry().
Friends And Related Symbol Documentation
operator<<
template<class EquationOfState > Ostream & operator<< (Ostream & , const hTabulatedThermo< EquationOfState > &) friend
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/thermo/hTabulated/hTabulatedThermo.H
src/thermophysicalModels/specie/thermo/hTabulated/hTabulatedThermo.C
src/thermophysicalModels/specie/thermo/hTabulated/hTabulatedThermoI.H