OpenFOAM: shellSurfaces Class Reference
shellSurfaces Class Reference
Encapsulates queries for volume refinement ('refine all cells within shell').
#include <shellSurfaces.H>
Public Types
enum refineMode { INSIDE , OUTSIDE , DISTANCE }
Public Member Functions
shellSurfaces (const searchableSurfaces &allGeometry, const dictionary &shellsDict, const bool dryRun=false)
const labelList & shells () const
const List< List< FixedList< label, 3 > > > & extendedGapLevel () const
const List< List< volumeType > > & extendedGapMode () const
const boolListList & gapSelf () const
label maxLevel () const
labelList maxGapLevel () const
labelPairList directionalSelectLevel () const
void findHigherLevel (const pointField &pt, const labelList &ptLevel, labelList &maxLevel) const
void findHigherGapLevel (const pointField &pt, const labelList &ptLevel, labelList &gapShell, List< FixedList< label, 3 > > &gapInfo, List< volumeType > &gapMode) const
void findHigherGapLevel (const pointField &pt, const labelList &ptLevel, List< FixedList< label, 3 > > &gapInfo, List< volumeType > &gapMode) const
void findLevel (const pointField &pt, const labelList &ptLevel, labelList &shell) const
void findDirectionalLevel (const pointField &pt, const labelList &ptLevel, const labelList &dirLevel, const direction dir, labelList &shell) const
const vectorField & smoothDirection () const
const labelList & nSmoothExpansion () const
const labelList & nSmoothPosition () const
Detailed Description
Encapsulates queries for volume refinement ('refine all cells within shell').
Source files
shellSurfaces.H
shellSurfaces.C
Definition at line 53 of file shellSurfaces.H.
Member Enumeration Documentation
refineMode
enum refineMode
Enumerator
INSIDE
OUTSIDE
DISTANCE
Definition at line 60 of file shellSurfaces.H.
Constructor & Destructor Documentation
shellSurfaces()
shellSurfaces (const searchableSurfaces & allGeometry, const dictionary & shellsDict, const bool dryRun = false)
Definition at line 585 of file shellSurfaces.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, UPtrList< T >::first(), forAll, UPtrList< T >::get(), Foam::Info, shellSurfaces::INSIDE, IOWarningInFunction, Foam::labelMax, Foam::labelMin, volumeType::MIXED, shellSurfaces::OUTSIDE, keyType::REGEX, regionNames, List< T >::setSize(), PtrList< T >::setSize(), UPtrList< T >::size(), WarningInFunction, and VectorSpace< Form, Cmpt, Ncmpts >::zero.
Member Function Documentation
shells()
const labelList & shells () const inline
Definition at line 182 of file shellSurfaces.H.
extendedGapLevel()
const List< List< FixedList< label, 3 > > > & extendedGapLevel () const inline
Definition at line 188 of file shellSurfaces.H.
extendedGapMode()
const List< List< volumeType > > & extendedGapMode () const inline
Definition at line 194 of file shellSurfaces.H.
gapSelf()
const boolListList & gapSelf () const inline
Definition at line 200 of file shellSurfaces.H.
maxLevel()
Foam::label maxLevel () const
Definition at line 819 of file shellSurfaces.C.
References forAll, and Foam::max().
maxGapLevel()
Foam::labelList maxGapLevel () const
Definition at line 830 of file shellSurfaces.C.
References forAll, Foam::max(), and Foam::Zero.
directionalSelectLevel()
Foam::labelPairList directionalSelectLevel () const
Definition at line 846 of file shellSurfaces.C.
References UList< T >::first(), and forAll.
findHigherLevel()
void findHigherLevel (const pointField & pt, const labelList & ptLevel, labelList & maxLevel) const
Definition at line 875 of file shellSurfaces.C.
References forAll.
findHigherGapLevel() [1/2]
void findHigherGapLevel (const pointField & pt, const labelList & ptLevel, labelList & gapShell, List< FixedList< label, 3 > > & gapInfo, List< volumeType > & gapMode) const
Definition at line 892 of file shellSurfaces.C.
References forAll, volumeType::MIXED, PtrList< T >::setSize(), and UList< T >::size().
findHigherGapLevel() [2/2]
void findHigherGapLevel (const pointField & pt, const labelList & ptLevel, List< FixedList< label, 3 > > & gapInfo, List< volumeType > & gapMode) const
Definition at line 917 of file shellSurfaces.C.
findLevel()
void findLevel (const pointField & pt, const labelList & ptLevel, labelList & shell) const
Definition at line 930 of file shellSurfaces.C.
References forAll, PtrList< T >::setSize(), and UList< T >::size().
findDirectionalLevel()
void findDirectionalLevel (const pointField & pt, const labelList & ptLevel, const labelList & dirLevel, const direction dir, labelList & shell) const
Definition at line 949 of file shellSurfaces.C.
References PtrList< T >::append(), PtrList< T >::clear(), UPtrList< T >::first(), forAll, volumeType::INSIDE, volumeType::OUTSIDE, PtrList< T >::setSize(), and UList< T >::size().
smoothDirection()
const Foam::vectorField & smoothDirection () const
Definition at line 863 of file shellSurfaces.C.
nSmoothExpansion()
const Foam::labelList & nSmoothExpansion () const
Definition at line 857 of file shellSurfaces.C.
nSmoothPosition()
const Foam::labelList & nSmoothPosition () const
Definition at line 869 of file shellSurfaces.C.
The documentation for this class was generated from the following files:
src/mesh/snappyHexMesh/shellSurfaces/shellSurfaces.H
src/mesh/snappyHexMesh/shellSurfaces/shellSurfaces.C