OpenFOAM: faceCells Class Reference
faceCells Class Reference
Smooth ATC in cells next to a set of patches supplied by type.
#include <faceCells.H>
Public Member Functions
TypeName ("faceCells")
faceCells (const fvMesh &mesh, const dictionary &dict)
virtual ~faceCells ()=default
Public Member Functions inherited from zeroATCcells
TypeName ("zeroATCcells")
declareRunTimeSelectionTable (autoPtr, zeroATCcells, dictionary,(const fvMesh &mesh, const dictionary &dict),(mesh, dict))
zeroATCcells (const fvMesh &mesh, const dictionary &dict)
virtual ~zeroATCcells ()=default
const labelList & getZeroATCcells ()
Additional Inherited Members
Static Public Member Functions inherited from zeroATCcells
static autoPtr< zeroATCcells > New (const fvMesh &mesh, const dictionary &dict)
Protected Attributes inherited from zeroATCcells
const fvMesh & mesh_
wordList zeroATCPatches_
labelList zeroATCZones_
labelList zeroATCcells_
Detailed Description
Smooth ATC in cells next to a set of patches supplied by type.
Source files
faceCells.H
faceCells.C
Definition at line 52 of file faceCells.H.
Constructor & Destructor Documentation
faceCells()
faceCells (const fvMesh & mesh, const dictionary & dict)
Definition at line 40 of file faceCells.C.
References List< T >::append(), Foam::endl(), Foam::Info, zeroATCcells::mesh_, Foam::nl, Foam::returnReduce(), UList< T >::size(), zeroATCcells::zeroATCcells_, zeroATCcells::zeroATCPatches_, and zeroATCcells::zeroATCZones_.
~faceCells()
virtual ~faceCells () virtual default
Member Function Documentation
TypeName()
TypeName ("faceCells")
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/ATCModel/zeroATCcells/faceCells/faceCells.H
src/optimisation/adjointOptimisation/adjoint/ATCModel/zeroATCcells/faceCells/faceCells.C