OpenFOAM: labelRanges Class Reference
labelRanges Class Reference
A list of labelRange.
#include <labelRanges.H>
Classes
class const_iterator
Public Member Functions
labelRanges ()=default
labelRanges (const label nElem)
labelRanges (Istream &is)
bool contains (const label value) const
bool found (const label value) const
bool add (const labelRange &range)
bool remove (const labelRange &range)
const_iterator cbegin () const noexcept
const const_iterator cend () const noexcept
const_iterator begin () const noexcept
const const_iterator end () const noexcept
Friends
Istream & operator>> (Istream &is, labelRanges &ranges)
Ostream & operator<< (Ostream &os, const labelRanges &ranges)
Detailed Description
A list of labelRange.
Source files
labelRanges.H
labelRanges.C
Definition at line 53 of file labelRanges.H.
Constructor & Destructor Documentation
labelRanges() [1/3]
labelRanges () default
labelRanges() [2/3]
labelRanges (const label nElem) inline explicit
Definition at line 24 of file labelRangesI.H.
labelRanges() [3/3]
labelRanges (Istream & is)
Definition at line 121 of file labelRanges.C.
Member Function Documentation
contains()
bool contains (const label value) const inline
Definition at line 133 of file labelRangesI.H.
References range.
Referenced by labelRanges::found().
found()
bool found (const label value) const inline
Definition at line 102 of file labelRanges.H.
References labelRanges::contains().
add()
bool add (const labelRange & range)
Definition at line 129 of file labelRanges.C.
References PtrList< T >::clear(), UPtrList< T >::empty(), forAll, and range.
remove()
bool remove (const labelRange & range)
Definition at line 189 of file labelRanges.C.
References labelRange::debug, UPtrList< T >::empty(), Foam::endl(), forAll, Foam::Info, Foam::printRange(), and range.
cbegin()
Foam::labelRanges::const_iterator cbegin () const inline noexcept
Definition at line 106 of file labelRangesI.H.
cend()
const Foam::labelRanges::const_iterator cend () const inline noexcept
Definition at line 113 of file labelRangesI.H.
begin()
Foam::labelRanges::const_iterator begin () const inline noexcept
Definition at line 120 of file labelRangesI.H.
end()
const Foam::labelRanges::const_iterator end () const inline noexcept
Definition at line 127 of file labelRangesI.H.
Friends And Related Symbol Documentation
operator>>
Istream & operator>> (Istream & is, labelRanges & ranges) friend
operator<<
Ostream & operator<< (Ostream & os, const labelRanges & ranges) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/ranges/labelRange/labelRanges.H
src/OpenFOAM/primitives/ranges/labelRange/labelRanges.C
src/OpenFOAM/primitives/ranges/labelRange/labelRangesI.H