OpenFOAM: departureFrequencyModel Class Reference
departureFrequencyModel Class Reference abstract
Base class for bubble departure frequency models for boiling flows.
#include <departureFrequencyModel.H>
Public Member Functions
TypeName ("departureFrequencyModel")
declareRunTimeSelectionTable (autoPtr, departureFrequencyModel, dictionary,(const dictionary &dict),(dict))
departureFrequencyModel ()=default
virtual ~departureFrequencyModel ()=default
virtual tmp< scalarField > fDeparture (const phaseModel &liquid, const phaseModel &vapor, const label patchi, const scalarField &dDep) const =0
virtual void write (Ostream &os) const
Static Public Member Functions
static autoPtr< departureFrequencyModel > New (const dictionary &dict)
Detailed Description
Base class for bubble departure frequency models for boiling flows.
Source files
departureFrequencyModel.H
departureFrequencyModel.C
Definition at line 53 of file departureFrequencyModel.H.
Constructor & Destructor Documentation
departureFrequencyModel()
departureFrequencyModel () default
~departureFrequencyModel()
virtual ~departureFrequencyModel () virtual default
Member Function Documentation
TypeName()
TypeName ("departureFrequencyModel")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , departureFrequencyModel , dictionary , (const dictionary &dict) , (dict))
New()
Foam::autoPtr< Foam::wallBoilingModels::departureFrequencyModel > New (const dictionary & dict) static
Definition at line 39 of file departureFrequencyModel.C.
References Foam::abort(), dict, Foam::endl(), Foam::FatalIOError, FatalIOErrorInLookup, and Foam::Info.
Referenced by alphatWallBoilingWallFunctionFvPatchScalarField::alphatWallBoilingWallFunctionFvPatchScalarField().
fDeparture()
virtual tmp< scalarField > fDeparture (const phaseModel & liquid, const phaseModel & vapor, const label patchi, const scalarField & dDep) const pure virtual
Implemented in Cole.
write()
void write (Ostream & os) const virtual
Definition at line 67 of file departureFrequencyModel.C.
References os(), and Foam::type().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/wallBoilingSubModels/departureFrequencyModels/departureFrequencyModel/departureFrequencyModel.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/wallBoilingSubModels/departureFrequencyModels/departureFrequencyModel/departureFrequencyModel.C