OpenFOAM: treeDataEdge Class Reference
treeDataEdge Class Reference
Holds data for octree to work on an edges subset.
#include <treeDataEdge.H>
Classes
class findIntersectOp
class findNearestOp
Public Member Functions
ClassNameNoDebug ("treeDataEdge")
treeDataEdge (const bool cacheBb, const edgeList &edges, const pointField &points)
treeDataEdge (const bool cacheBb, const edgeList &edges, const pointField &points, const labelRange &range)
treeDataEdge (const bool cacheBb, const edgeList &edges, const pointField &points, const labelUList &edgeLabels)
treeDataEdge (const bool cacheBb, const edgeList &edges, const pointField &points, labelList &&edgeLabels)
treeDataEdge (const edgeList &edges, const pointField &points)
treeDataEdge (const edgeList &edges, const pointField &points, const labelRange &range)
treeDataEdge (const edgeList &edges, const pointField &points, const labelUList &edgeLabels)
treeDataEdge (const edgeList &edges, const pointField &points, labelList &&edgeLabels)
int nDim () const noexcept
treeBoundBox bounds (const labelUList &indices) const
const pointField & points () const noexcept
const edgeList & edges () const noexcept
const labelList & edgeLabels () const noexcept
bool useSubset () const noexcept
bool empty () const noexcept
label size () const noexcept
label objectIndex (const label index) const
const edge & operator[] (const label index) const
const linePointRef line (const label index) const
point centre (const label index) const
tmp< pointField > centres () const
volumeType getVolumeType (const indexedOctree< treeDataEdge > &, const point &) const
bool overlaps (const label index, const treeBoundBox &searchBox) const
bool overlaps (const label index, const point &centre, const scalar radiusSqr) const
void findNearest (const labelUList &indices, const point &sample, scalar &nearestDistSqr, label &nearestIndex, point &nearestPoint) const
Static Public Member Functions
static treeBoundBoxList boxes (const edgeList &edges, const pointField &points)
static treeBoundBoxList boxes (const edgeList &edges, const pointField &points, const labelRange &range)
static treeBoundBoxList boxes (const edgeList &edges, const pointField &points, const labelUList &edgeIds)
static treeBoundBox bounds (const edgeList &edges, const pointField &points)
static treeBoundBox bounds (const edgeList &edges, const pointField &points, const labelRange &range)
static treeBoundBox bounds (const edgeList &edges, const pointField &points, const labelUList &edgeIds)
Detailed Description
Holds data for octree to work on an edges subset.
Source files
treeDataEdge.H
treeDataEdge.C
Definition at line 53 of file treeDataEdge.H.
Constructor & Destructor Documentation
treeDataEdge() [1/8]
treeDataEdge (const bool cacheBb, const edgeList & edges, const pointField & points)
Definition at line 197 of file treeDataEdge.C.
treeDataEdge() [2/8]
treeDataEdge (const bool cacheBb, const edgeList & edges, const pointField & points, const labelRange & range)
Definition at line 214 of file treeDataEdge.C.
treeDataEdge() [3/8]
treeDataEdge (const bool cacheBb, const edgeList & edges, const pointField & points, const labelUList & edgeLabels)
Definition at line 232 of file treeDataEdge.C.
treeDataEdge() [4/8]
treeDataEdge (const bool cacheBb, const edgeList & edges, const pointField & points, labelList && edgeLabels)
Definition at line 250 of file treeDataEdge.C.
treeDataEdge() [5/8]
treeDataEdge (const edgeList & edges, const pointField & points) inline
Definition at line 186 of file treeDataEdge.H.
treeDataEdge() [6/8]
treeDataEdge (const edgeList & edges, const pointField & points, const labelRange & range) inline
Definition at line 193 of file treeDataEdge.H.
treeDataEdge() [7/8]
treeDataEdge (const edgeList & edges, const pointField & points, const labelUList & edgeLabels) inline
Definition at line 205 of file treeDataEdge.H.
treeDataEdge() [8/8]
treeDataEdge (const edgeList & edges, const pointField & points, labelList && edgeLabels) inline
Definition at line 217 of file treeDataEdge.H.
Member Function Documentation
ClassNameNoDebug()
ClassNameNoDebug ("treeDataEdge")
boxes() [1/3]
Foam::treeBoundBoxList boxes (const edgeList & edges, const pointField & points) static
Definition at line 91 of file treeDataEdge.C.
References UPtrList< T >::begin(), UPtrList< T >::cbegin(), UPtrList< T >::cend(), e, treeDataEdge::edges(), and UPtrList< T >::size().
boxes() [2/3]
Foam::treeBoundBoxList boxes (const edgeList & edges, const pointField & points, const labelRange & range) static
Definition at line 112 of file treeDataEdge.C.
References Foam::boxesImpl(), points, and range.
boxes() [3/3]
Foam::treeBoundBoxList boxes (const edgeList & edges, const pointField & points, const labelUList & edgeIds) static
Definition at line 124 of file treeDataEdge.C.
References Foam::boxesImpl(), and points.
bounds() [1/4]
Foam::treeBoundBox bounds (const edgeList & edges, const pointField & points) static
Definition at line 136 of file treeDataEdge.C.
References boundBox::add(), e, UList< T >::first(), and points.
Referenced by treeDataEdge::bounds().
bounds() [2/4]
Foam::treeBoundBox bounds (const edgeList & edges, const pointField & points, const labelRange & range) static
Definition at line 154 of file treeDataEdge.C.
References Foam::boundsImpl(), points, and range.
bounds() [3/4]
Foam::treeBoundBox bounds (const edgeList & edges, const pointField & points, const labelUList & edgeIds) static
Definition at line 166 of file treeDataEdge.C.
References Foam::boundsImpl(), and points.
nDim()
int nDim () const inline noexcept
Definition at line 280 of file treeDataEdge.H.
bounds() [4/4]
Foam::treeBoundBox bounds (const labelUList & indices) const
Definition at line 270 of file treeDataEdge.C.
References boundBox::add(), treeDataEdge::bounds(), e, and UList< T >::first().
points()
const pointField & points () const inline noexcept
Definition at line 289 of file treeDataEdge.H.
edges()
const edgeList & edges () const inline noexcept
Definition at line 292 of file treeDataEdge.H.
Referenced by treeDataEdge::boxes().
edgeLabels()
const labelList & edgeLabels () const inline noexcept
Definition at line 295 of file treeDataEdge.H.
useSubset()
bool useSubset () const inline noexcept
Definition at line 298 of file treeDataEdge.H.
empty()
bool empty () const inline noexcept
Definition at line 301 of file treeDataEdge.H.
References UList< T >::empty().
size()
label size () const inline noexcept
Definition at line 307 of file treeDataEdge.H.
References UList< T >::size().
objectIndex()
label objectIndex (const label index) const inline
Definition at line 313 of file treeDataEdge.H.
Referenced by treeDataEdge::centre(), treeDataEdge::line(), and treeDataEdge::operator[]().
operator[]()
const edge & operator[] (const label index) const inline
Definition at line 319 of file treeDataEdge.H.
References treeDataEdge::objectIndex().
line()
const linePointRef line (const label index) const inline
Definition at line 325 of file treeDataEdge.H.
References treeDataEdge::objectIndex().
Referenced by treeDataEdge::findNearestOp::operator()().
centre()
point centre (const label index) const inline
Definition at line 331 of file treeDataEdge.H.
References treeDataEdge::objectIndex().
centres()
Foam::tmp< Foam::pointField > centres () const
Definition at line 290 of file treeDataEdge.C.
References UPtrList< T >::begin(), e, and tmp< T >::New().
getVolumeType()
Foam::volumeType getVolumeType (const indexedOctree< treeDataEdge > & oc, const point & sample) const
Definition at line 323 of file treeDataEdge.C.
References volumeType::UNKNOWN.
overlaps() [1/2]
bool overlaps (const label index, const treeBoundBox & searchBox) const
Definition at line 333 of file treeDataEdge.C.
overlaps() [2/2]
bool overlaps (const label index, const point & centre, const scalar radiusSqr) const
Definition at line 344 of file treeDataEdge.C.
References line< Point, PointRef >::nearestDist(), and Foam::sqr().
findNearest()
void findNearest (const labelUList & indices, const point & sample, scalar & nearestDistSqr, label & nearestIndex, point & nearestPoint) const
Definition at line 375 of file treeDataEdge.C.
References line< Point, PointRef >::nearestDist(), and Foam::sqr().
The documentation for this class was generated from the following files:
src/OpenFOAM/algorithms/indexedOctree/treeDataEdge.H
src/OpenFOAM/algorithms/indexedOctree/treeDataEdge.C