OpenFOAM: fvFieldReconstructor Class Reference
fvFieldReconstructor Class Reference
Finite volume reconstructor for volume and surface fields.
#include <fvFieldReconstructor.H>
Classes
class fvPatchFieldReconstructor
Public Member Functions
fvFieldReconstructor (fvMesh &mesh, const PtrList< fvMesh > &procMeshes, const PtrList< labelIOList > &faceProcAddressing, const PtrList< labelIOList > &cellProcAddressing, const PtrList< labelIOList > &boundaryProcAddressing)
label nReconstructed () const noexcept
template<class Type >
tmp< DimensionedField< Type, volMesh > > reconstructField (const IOobject &fieldObject, const PtrList< DimensionedField< Type, volMesh > > &procFields) const
template<class Type >
tmp< DimensionedField< Type, volMesh > > reconstructInternalField (const IOobject &fieldObject) const
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > reconstructField (const IOobject &fieldObject, const PtrList< GeometricField< Type, fvPatchField, volMesh > > &) const
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > reconstructVolumeField (const IOobject &fieldObject) const
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > reconstructField (const IOobject &fieldObject, const PtrList< GeometricField< Type, fvsPatchField, surfaceMesh > > &) const
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > reconstructSurfaceField (const IOobject &fieldObject) const
template<class Type >
label reconstructInternalFields (const UPtrList< const IOobject > &fieldObjects)
template<class Type >
label reconstructVolumeFields (const UPtrList< const IOobject > &fieldObjects)
template<class Type >
label reconstructSurfaceFields (const UPtrList< const IOobject > &fieldObjects)
template<class Type >
label reconstructInternalFields (const IOobjectList &objects, const wordRes &selectedFields=wordRes())
template<class Type >
label reconstructVolumeFields (const IOobjectList &objects, const wordRes &selectedFields=wordRes())
template<class Type >
label reconstructSurfaceFields (const IOobjectList &objects, const wordRes &selectedFields=wordRes())
label reconstructAllFields (const IOobjectList &objects, const wordRes &selectedFields=wordRes())
template<class Type >
Foam::tmp< Foam::DimensionedField< Type, Foam::volMesh > > reconstructField (const IOobject &fieldObject, const PtrList< DimensionedField< Type, volMesh > > &procFields) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > reconstructField (const IOobject &fieldObject, const PtrList< GeometricField< Type, fvPatchField, volMesh > > &procFields) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > reconstructField (const IOobject &fieldObject, const PtrList< GeometricField< Type, fvsPatchField, surfaceMesh > > &procFields) const
template<class Type >
Foam::tmp< Foam::DimensionedField< Type, Foam::volMesh > > reconstructInternalField (const IOobject &fieldObject) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > reconstructVolumeField (const IOobject &fieldObject) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > reconstructSurfaceField (const IOobject &fieldObject) const
template<class Type >
Foam::label reconstructInternalFields (const UPtrList< const IOobject > &fieldObjects)
template<class Type >
Foam::label reconstructVolumeFields (const UPtrList< const IOobject > &fieldObjects)
template<class Type >
Foam::label reconstructSurfaceFields (const UPtrList< const IOobject > &fieldObjects)
template<class Type >
Foam::label reconstructInternalFields (const IOobjectList &objects, const wordRes &selectedFields)
template<class Type >
Foam::label reconstructVolumeFields (const IOobjectList &objects, const wordRes &selectedFields)
template<class Type >
Foam::label reconstructSurfaceFields (const IOobjectList &objects, const wordRes &selectedFields)
Static Public Attributes
static int verbose_ = 1
Detailed Description
Finite volume reconstructor for volume and surface fields.
Source files
fvFieldReconstructor.H
fvFieldReconstructor.C
fvFieldReconstructorTemplates.C
Definition at line 52 of file fvFieldReconstructor.H.
Constructor & Destructor Documentation
fvFieldReconstructor()
fvFieldReconstructor (fvMesh & mesh, const PtrList< fvMesh > & procMeshes, const PtrList< labelIOList > & faceProcAddressing, const PtrList< labelIOList > & cellProcAddressing, const PtrList< labelIOList > & boundaryProcAddressing)
Definition at line 33 of file fvFieldReconstructor.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, and UPtrList< T >::size().
Member Function Documentation
nReconstructed()
label nReconstructed () const inline noexcept
Definition at line 152 of file fvFieldReconstructor.H.
reconstructField() [1/6]
template<class Type > tmp< DimensionedField< Type, volMesh > > reconstructField (const IOobject & fieldObject, const PtrList< DimensionedField< Type, volMesh > > & procFields) const
reconstructInternalField() [1/2]
template<class Type > tmp< DimensionedField< Type, volMesh > > reconstructInternalField (const IOobject & fieldObject) const
reconstructField() [2/6]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > reconstructField (const IOobject & fieldObject, const PtrList< GeometricField< Type, fvPatchField, volMesh > > &) const
reconstructVolumeField() [1/2]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > reconstructVolumeField (const IOobject & fieldObject) const
reconstructField() [3/6]
template<class Type > tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > reconstructField (const IOobject & fieldObject, const PtrList< GeometricField< Type, fvsPatchField, surfaceMesh > > &) const
reconstructSurfaceField() [1/2]
template<class Type > tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > reconstructSurfaceField (const IOobject & fieldObject) const
reconstructInternalFields() [1/4]
template<class Type > label reconstructInternalFields (const UPtrList< const IOobject > & fieldObjects)
reconstructVolumeFields() [1/4]
template<class Type > label reconstructVolumeFields (const UPtrList< const IOobject > & fieldObjects)
reconstructSurfaceFields() [1/4]
template<class Type > label reconstructSurfaceFields (const UPtrList< const IOobject > & fieldObjects)
reconstructInternalFields() [2/4]
template<class Type > label reconstructInternalFields (const IOobjectList & objects, const wordRes & selectedFields = wordRes())
reconstructVolumeFields() [2/4]
template<class Type > label reconstructVolumeFields (const IOobjectList & objects, const wordRes & selectedFields = wordRes())
reconstructSurfaceFields() [2/4]
template<class Type > label reconstructSurfaceFields (const IOobjectList & objects, const wordRes & selectedFields = wordRes())
reconstructAllFields()
Foam::label reconstructAllFields (const IOobjectList & objects, const wordRes & selectedFields = wordRes())
Definition at line 77 of file fvFieldReconstructor.C.
References doLocalCode.
reconstructField() [4/6]
template<class Type > Foam::tmp< Foam::DimensionedField< Type, Foam::volMesh > > reconstructField (const IOobject & fieldObject, const PtrList< DimensionedField< Type, volMesh > > & procFields) const
Definition at line 34 of file fvFieldReconstructorTemplates.C.
References forAll, primitiveMesh::nCells(), and Foam::New().
reconstructField() [5/6]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > reconstructField (const IOobject & fieldObject, const PtrList< GeometricField< Type, fvPatchField, volMesh > > & procFields) const
Definition at line 71 of file fvFieldReconstructorTemplates.C.
References cp, Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::New(), PtrList< T >::set(), and UPtrList< T >::size().
reconstructField() [6/6]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > reconstructField (const IOobject & fieldObject, const PtrList< GeometricField< Type, fvsPatchField, surfaceMesh > > & procFields) const
Definition at line 249 of file fvFieldReconstructorTemplates.C.
References cp, Foam::faceMap(), forAll, Foam::mag(), Foam::New(), PtrList< T >::set(), and UPtrList< T >::size().
reconstructInternalField() [2/2]
template<class Type > Foam::tmp< Foam::DimensionedField< Type, Foam::volMesh > > reconstructInternalField (const IOobject & fieldObject) const
Definition at line 442 of file fvFieldReconstructorTemplates.C.
References forAll, IOobjectOption::MUST_READ, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, and PtrList< T >::set().
reconstructVolumeField() [2/2]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > reconstructVolumeField (const IOobject & fieldObject) const
Definition at line 490 of file fvFieldReconstructorTemplates.C.
References forAll, IOobjectOption::MUST_READ, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, and PtrList< T >::set().
reconstructSurfaceField() [2/2]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > reconstructSurfaceField (const IOobject & fieldObject) const
Definition at line 538 of file fvFieldReconstructorTemplates.C.
References forAll, IOobjectOption::MUST_READ, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, and PtrList< T >::set().
reconstructInternalFields() [3/4]
template<class Type > Foam::label reconstructInternalFields (const UPtrList< const IOobject > & fieldObjects)
Definition at line 585 of file fvFieldReconstructorTemplates.C.
References Foam::endl(), Foam::Info, io(), IOobject::isHeaderClass(), IOobject::name(), Foam::nl, and write().
reconstructVolumeFields() [3/4]
template<class Type > Foam::label reconstructVolumeFields (const UPtrList< const IOobject > & fieldObjects)
Definition at line 620 of file fvFieldReconstructorTemplates.C.
References Foam::endl(), Foam::Info, io(), IOobject::isHeaderClass(), IOobject::name(), Foam::nl, and write().
reconstructSurfaceFields() [3/4]
template<class Type > Foam::label reconstructSurfaceFields (const UPtrList< const IOobject > & fieldObjects)
Definition at line 655 of file fvFieldReconstructorTemplates.C.
References Foam::endl(), Foam::Info, io(), IOobject::isHeaderClass(), IOobject::name(), Foam::nl, and write().
reconstructInternalFields() [4/4]
template<class Type > Foam::label reconstructInternalFields (const IOobjectList & objects, const wordRes & selectedFields)
Definition at line 691 of file fvFieldReconstructorTemplates.C.
References UPtrList< T >::empty().
reconstructVolumeFields() [4/4]
template<class Type > Foam::label reconstructVolumeFields (const IOobjectList & objects, const wordRes & selectedFields)
Definition at line 711 of file fvFieldReconstructorTemplates.C.
References UPtrList< T >::empty().
reconstructSurfaceFields() [4/4]
template<class Type > Foam::label reconstructSurfaceFields (const IOobjectList & objects, const wordRes & selectedFields)
Definition at line 731 of file fvFieldReconstructorTemplates.C.
References UPtrList< T >::empty().
Member Data Documentation
verbose_
int verbose_ = 1 static
Definition at line 133 of file fvFieldReconstructor.H.
The documentation for this class was generated from the following files:
src/parallel/reconstruct/reconstruct/fvFieldReconstructor.H
src/parallel/reconstruct/reconstruct/fvFieldReconstructor.C
src/parallel/reconstruct/reconstruct/fvFieldReconstructorTemplates.C