OpenFOAM: mapDistributeBase Class Reference
mapDistributeBase Class Reference
Class containing processor-to-processor mapping information.
#include <mapDistributeBase.H>
Public Member Functions
ClassName ("mapDistributeBase")
mapDistributeBase ()
mapDistributeBase (const label comm)
mapDistributeBase (const mapDistributeBase &map)
mapDistributeBase (mapDistributeBase &&map)
mapDistributeBase (const dictionary &dict, const label comm=UPstream::worldComm)
mapDistributeBase (const label constructSize, labelListList &&subMap, labelListList &&constructMap, const bool subHasFlip=false, const bool constructHasFlip=false, const label comm=UPstream::worldComm)
mapDistributeBase (const labelUList &sendProcs, const labelUList &recvProcs, const label comm=UPstream::worldComm)
mapDistributeBase (const globalIndex &, labelList &elements, List< Map< label > > &compactMap, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm)
mapDistributeBase (const globalIndex &, labelListList &cellCells, List< Map< label > > &compactMap, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm)
mapDistributeBase (labelListList &&subMap, const bool subHasFlip=false, const bool constructHasFlip=false, const label comm=UPstream::worldComm)
mapDistributeBase (Istream &is)
label constructSize () const noexcept
label & constructSize () noexcept
const labelListList & subMap () const noexcept
labelListList & subMap () noexcept
const labelListList & constructMap () const noexcept
labelListList & constructMap () noexcept
bool subHasFlip () const noexcept
bool & subHasFlip () noexcept
bool constructHasFlip () const noexcept
bool & constructHasFlip () noexcept
label comm () const noexcept
label nMaps () const noexcept
labelList subMapSizes () const
labelList constructMapSizes () const
const List< labelPair > & schedule () const
const List< labelPair > & whichSchedule (const UPstream::commsTypes commsType) const
void clear ()
void transfer (mapDistributeBase &rhs)
void compactLocalData (const bitSet &allowedLocalElems, const int tag=UPstream::msgType(), const bool doRenumber=false)
void compactRemoteData (const bitSet &allowedRemoteElems, const int tag=UPstream::msgType(), const bool doRenumber=false)
void compactLocalData (const bitSet &allowedLocalElems, labelList &oldToNewSub, labelList &oldToNewConstruct, const label localSize=-1, const int tag=UPstream::msgType())
void compactRemoteData (const bitSet &allowedRemoteElems, labelList &oldToNewSub, labelList &oldToNewConstruct, const label localSize=-1, const int tag=UPstream::msgType())
void compactData (const labelUList &localElements, const labelUList &remoteElements, labelList &oldToNewSub, labelList &oldToNewConstruct, const label localSize=-1, const int tag=UPstream::msgType())
void compactLocalData (const labelUList &localElements, labelList &oldToNewSub, labelList &oldToNewConstruct, const label localSize=-1, const int tag=UPstream::msgType())
void compactRemoteData (const labelUList &remoteElements, labelList &oldToNewSub, labelList &oldToNewConstruct, const label localSize=-1, const int tag=UPstream::msgType())
template<class T >
void distribute (List< T > &values, const int tag=UPstream::msgType()) const
template<class T >
void distribute (DynamicList< T > &values, const int tag=UPstream::msgType()) const
template<class T , class NegateOp >
void distribute (List< T > &values, const NegateOp &negOp, const int tag=UPstream::msgType()) const
template<class T , class NegateOp >
void distribute (const Pstream::commsTypes commsType, List< T > &values, const NegateOp &negOp, const int tag=UPstream::msgType()) const
template<class T , class NegateOp >
void distribute (const Pstream::commsTypes commsType, const T &nullValue, List< T > &values, const NegateOp &negOp, const int tag=UPstream::msgType()) const
template<class T >
void reverseDistribute (const label constructSize, List< T > &values, const int tag=UPstream::msgType()) const
template<class T >
void reverseDistribute (const label constructSize, const T &nullValue, List< T > &values, const int tag=UPstream::msgType()) const
template<class T >
void reverseDistribute (const Pstream::commsTypes commsType, const label constructSize, List< T > &values, const int tag=UPstream::msgType()) const
template<class T , class NegateOp >
void reverseDistribute (const Pstream::commsTypes commsType, const label constructSize, List< T > &values, const NegateOp &negOp, const int tag=UPstream::msgType()) const
template<class T >
void reverseDistribute (const Pstream::commsTypes commsType, const label constructSize, const T &nullValue, List< T > &values, const int tag=UPstream::msgType()) const
template<class T >
void send (PstreamBuffers &pBufs, const List< T > &field) const
template<class T >
void receive (PstreamBuffers &pBufs, List< T > &field) const
template<class T >
void send (const UList< T > &field, labelRange &requests, PtrList< List< T > > &sendFields, PtrList< List< T > > &recvFields, const int tag=UPstream::msgType()) const
template<class T >
void receive (const labelRange &requests, const UPtrList< List< T > > &sendFields, const UPtrList< List< T > > &recvFields, List< T > &field, const int tag=UPstream::msgType()) const
void printLayout (Ostream &os) const
void operator= (const mapDistributeBase &rhs)
void operator= (mapDistributeBase &&rhs)
InfoProxy< mapDistributeBase > info () const noexcept
void readDict (const dictionary &dict)
void writeEntries (Ostream &os) const
void updateMesh (const mapPolyMesh &)
void compact (const boolList &remoteElemUsed, const int tag=UPstream::msgType())
void compact (const boolList &remoteElemUsed, const label localSize, labelList &oldToNewSub, labelList &oldToNewConstruct, const int tag=UPstream::msgType())
template<class T , class NegateOp >
Foam::List< T > accessAndFlip (const UList< T > &values, const labelUList &indices, const bool hasFlip, const NegateOp &negOp)
Static Public Member Functions
static bool hasFlipAddressing (const labelUList &map)
static bool hasFlipAddressing (const labelListList &maps)
static label countUnmapped (const labelUList &elements, const labelListList &maps, const bool hasFlip)
static List< labelPair > schedule (const labelListList &subMap, const labelListList &constructMap, const int tag, const label comm=UPstream::worldComm)
static label renumber (const globalIndex &, const List< Map< label > > &compactMap, const label globalElement)
static label renumberMap (labelListList &mapElements, const labelUList &oldToNew, const bool hasFlip)
template<class T , class NegateOp >
static void distribute (const Pstream::commsTypes commsType, const List< labelPair > &schedule, const label constructSize, const labelListList &subMap, const bool subHasFlip, const labelListList &constructMap, const bool constructHasFlip, List< T > &field, const NegateOp &negOp, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm)
template<class T , class CombineOp , class NegateOp >
static void distribute (const Pstream::commsTypes commsType, const List< labelPair > &schedule, const label constructSize, const labelListList &subMap, const bool subHasFlip, const labelListList &constructMap, const bool constructHasFlip, List< T > &field, const T &nullValue, const CombineOp &cop, const NegateOp &negOp, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm)
template<class T , class negateOp >
static void send (const labelListList &subMap, const bool subHasFlip, const labelListList &constructMap, const bool constructHasFlip, const UList< T > &field, labelRange &requests, PtrList< List< T > > &sendFields, PtrList< List< T > > &recvFields, const negateOp &negOp, const int tag, const label comm)
template<class T , class CombineOp , class negateOp >
static void receive (const label constructSize, const labelListList &constructMap, const bool constructHasFlip, const UPtrList< List< T > > &sendFields, const UPtrList< List< T > > &recvFields, const labelRange &requests, List< T > &field, const CombineOp &cop, const negateOp &negOp, const int tag, const label comm)
Protected Member Functions
void calcCompactAddressing (const globalIndex &globalNumbering, const labelUList &elements, List< Map< label > > &compactMap) const
void calcCompactAddressing (const globalIndex &globalNumbering, const labelListList &elements, List< Map< label > > &compactMap) const
void exchangeAddressing (const int tag, const globalIndex &globalNumbering, labelList &elements, List< Map< label > > &compactMap, labelList &compactStart)
void exchangeAddressing (const int tag, const globalIndex &globalNumbering, labelListList &elements, List< Map< label > > &compactMap, labelList &compactStart)
Static Protected Member Functions
static void checkReceivedSize (const label proci, const label expectedSize, const label receivedSize)
static label getMappedSize (const labelListList &maps, const bool hasFlip)
static void exchangeMasks (const UList< bitSet > &sendMasks, UList< bitSet > &recvMasks, const int tag, const label comm)
static void unionCombineMasks (UList< bitSet > &sendMasks, UList< bitSet > &recvMasks, const int tag, const label comm)
template<class T , class CombineOp , class NegateOp >
static void flipAndCombine (const labelUList &map, const bool hasFlip, const UList< T > &rhs, const CombineOp &cop, const NegateOp &negOp, List< T > &lhs)
template<class T , class NegateOp >
static T accessAndFlip (const UList< T > &values, const label index, const bool hasFlip, const NegateOp &negOp)
template<class T , class NegateOp >
static List< T > accessAndFlip (const UList< T > &values, const labelUList &indices, const bool hasFlip, const NegateOp &negOp)
Friends
Istream & operator>> (Istream &, mapDistributeBase &)
Ostream & operator<< (Ostream &, const mapDistributeBase &)
Detailed Description
Class containing processor-to-processor mapping information.
We store mapping from the bits-to-send to the complete starting list (subXXXMap) and from the received bits to their location in the new list (constructXXXMap).
Note: Schedule is a list of processor pairs (one send, one receive. One of them will be myself) which forms a scheduled (i.e. non-buffered) exchange. See distribute on how to use it. Note2: number of items sent on one processor have to equal the number of items received on the other processor.
To aid constructing these maps there are the constructors from global numbering, either with or without transforms.
Constructors using compact numbering: layout is
all my own elements first (whether used or not)
followed by used-only remote elements sorted by remote processor. So e.g 4 procs and on proc 1 the compact table will first have all globalIndex.localSize() elements from proc1 followed by used-only elements of proc0, proc2, proc3. The constructed mapDistributeBase sends the local elements from and receives the remote elements into their compact position. compactMap[proci] is the position of elements from proci in the compact map. compactMap[myProcNo()] is empty since trivial addressing.
It rewrites the input global indices into indices into the constructed data.
When constructing from components optionally a 'flip' on the maps can be specified. This will interpret the map values as index+flip, similar to e.g. faceProcAddressing. The flip will only be applied to fieldTypes (scalar, vector, .. triad)
Source files
mapDistributeBase.H
mapDistributeBase.C
mapDistributeBaseIO.C
mapDistributeBaseTemplates.C
Definition at line 103 of file mapDistributeBase.H.
Constructor & Destructor Documentation
mapDistributeBase() [1/11]
mapDistributeBase ()
Definition at line 647 of file mapDistributeBase.C.
mapDistributeBase() [2/11]
mapDistributeBase (const label comm) explicit
Definition at line 653 of file mapDistributeBase.C.
mapDistributeBase() [3/11]
mapDistributeBase (const mapDistributeBase & map)
Definition at line 665 of file mapDistributeBase.C.
mapDistributeBase() [4/11]
mapDistributeBase (mapDistributeBase && map)
Definition at line 677 of file mapDistributeBase.C.
References mapDistributeBase::transfer().
mapDistributeBase() [5/11]
mapDistributeBase (const dictionary & dict, const label comm = UPstream::worldComm) explicit
Definition at line 73 of file mapDistributeBaseIO.C.
References dict, and mapDistributeBase::readDict().
mapDistributeBase() [6/11]
mapDistributeBase (const label constructSize, labelListList && subMap, labelListList && constructMap, const bool subHasFlip = false, const bool constructHasFlip = false, const label comm = UPstream::worldComm)
Definition at line 685 of file mapDistributeBase.C.
mapDistributeBase() [7/11]
mapDistributeBase (const labelUList & sendProcs, const labelUList & recvProcs, const label comm = UPstream::worldComm)
Definition at line 705 of file mapDistributeBase.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, UPstream::myProcNo(), UPstream::nProcs(), List< T >::setSize(), UPtrList< T >::size(), and Foam::Zero.
mapDistributeBase() [8/11]
mapDistributeBase (const globalIndex & globalNumbering, labelList & elements, List< Map< label > > & compactMap, const int tag = UPstream::msgType(), const label comm = UPstream::worldComm)
Definition at line 790 of file mapDistributeBase.C.
References mapDistributeBase::calcCompactAddressing(), mapDistributeBase::exchangeAddressing(), Foam::Pout, and mapDistributeBase::printLayout().
mapDistributeBase() [9/11]
mapDistributeBase (const globalIndex & globalNumbering, labelListList & cellCells, List< Map< label > > & compactMap, const int tag = UPstream::msgType(), const label comm = UPstream::worldComm)
Definition at line 853 of file mapDistributeBase.C.
References mapDistributeBase::calcCompactAddressing(), mapDistributeBase::exchangeAddressing(), Foam::Pout, and mapDistributeBase::printLayout().
mapDistributeBase() [10/11]
mapDistributeBase (labelListList && subMap, const bool subHasFlip = false, const bool constructHasFlip = false, const label comm = UPstream::worldComm) explicit
Definition at line 916 of file mapDistributeBase.C.
References Pstream::exchangeSizes(), forAll, Foam::identity(), UPstream::myProcNo(), UPstream::nProcs(), and List< T >::resize().
mapDistributeBase() [11/11]
mapDistributeBase (Istream & is) explicit
Definition at line 85 of file mapDistributeBaseIO.C.
Member Function Documentation
checkReceivedSize()
void checkReceivedSize (const label proci, const label expectedSize, const label receivedSize) static protected
Definition at line 159 of file mapDistributeBase.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
getMappedSize()
Foam::label getMappedSize (const labelListList & maps, const bool hasFlip) static protected
Definition at line 82 of file mapDistributeBase.C.
References Foam::mag(), and Foam::max().
calcCompactAddressing() [1/2]
void calcCompactAddressing (const globalIndex & globalNumbering, const labelUList & elements, List< Map< label > > & compactMap) const protected
Definition at line 380 of file mapDistributeBase.C.
References UPstream::myProcNo(), UPstream::nProcs(), and Foam::Zero.
Referenced by mapDistribute::mapDistribute(), mapDistribute::mapDistribute(), mapDistributeBase::mapDistributeBase(), and mapDistributeBase::mapDistributeBase().
calcCompactAddressing() [2/2]
void calcCompactAddressing (const globalIndex & globalNumbering, const labelListList & elements, List< Map< label > > & compactMap) const protected
Definition at line 428 of file mapDistributeBase.C.
exchangeAddressing() [1/2]
void exchangeAddressing (const int tag, const globalIndex & globalNumbering, labelList & elements, List< Map< label > > & compactMap, labelList & compactStart) protected
Definition at line 482 of file mapDistributeBase.C.
References forAll, forAllIters, Foam::identity(), globalIndex::localSize(), UPstream::myProcNo(), UPstream::nProcs(), Foam::renumber(), PtrList< T >::setSize(), and UPtrList< T >::size().
Referenced by mapDistribute::mapDistribute(), mapDistribute::mapDistribute(), mapDistributeBase::mapDistributeBase(), and mapDistributeBase::mapDistributeBase().
exchangeAddressing() [2/2]
void exchangeAddressing (const int tag, const globalIndex & globalNumbering, labelListList & elements, List< Map< label > > & compactMap, labelList & compactStart) protected
Definition at line 562 of file mapDistributeBase.C.
References forAll, forAllIters, Foam::identity(), globalIndex::localSize(), UPstream::myProcNo(), UPstream::nProcs(), Foam::renumber(), PtrList< T >::setSize(), and UPtrList< T >::size().
exchangeMasks()
void exchangeMasks (const UList< bitSet > & sendMasks, UList< bitSet > & recvMasks, const int tag, const label comm) static protected
Definition at line 112 of file mapDistributeBaseSubset.C.
References Foam::abort(), mapDistributeBase::comm(), Foam::FatalError, FatalErrorInFunction, forAll, UPstream::myProcNo(), Foam::nl, UPstream::nonBlocking, UPstream::nProcs(), UPstream::nRequests(), UPstream::parRun(), UIPstream::read(), UPtrList< T >::size(), UPstream::waitRequests(), and UOPstream::write().
unionCombineMasks()
void unionCombineMasks (UList< bitSet > & sendMasks, UList< bitSet > & recvMasks, const int tag, const label comm) static protected
Definition at line 191 of file mapDistributeBaseSubset.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, UPstream::myProcNo(), Foam::nl, UPstream::parRun(), PtrList< T >::resize(), and UPtrList< T >::size().
flipAndCombine()
template<class T , class CombineOp , class NegateOp > void flipAndCombine (const labelUList & map, const bool hasFlip, const UList< T > & rhs, const CombineOp & cop, const NegateOp & negOp, List< T > & lhs) static protected
Definition at line 29 of file mapDistributeBaseTemplates.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, UPtrList< T >::size(), and UList< T >::size().
accessAndFlip() [1/3]
template<class T , class NegateOp > T accessAndFlip (const UList< T > & values, const label index, const bool hasFlip, const NegateOp & negOp) static protected
Definition at line 74 of file mapDistributeBaseTemplates.C.
References Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
accessAndFlip() [2/3]
template<class T , class NegateOp > static List< T > accessAndFlip (const UList< T > & values, const labelUList & indices, const bool hasFlip, const NegateOp & negOp) static protected
ClassName()
ClassName ("mapDistributeBase")
hasFlipAddressing() [1/2]
bool hasFlipAddressing (const labelUList & map) static
Definition at line 39 of file mapDistributeBase.C.
hasFlipAddressing() [2/2]
bool hasFlipAddressing (const labelListList & maps) static
Definition at line 59 of file mapDistributeBase.C.
countUnmapped()
Foam::label countUnmapped (const labelUList & elements, const labelListList & maps, const bool hasFlip) static
Definition at line 107 of file mapDistributeBase.C.
References UPtrList< T >::count(), UList< T >::empty(), and Foam::mag().
constructSize() [1/2]
label constructSize () const inline noexcept
Definition at line 483 of file mapDistributeBase.H.
Referenced by AMIInterpolation::agglomerate(), extendedCellToFaceStencil::collectData(), extendedFaceToCellStencil::collectData(), meshRefinement::countEdgeFaces(), faMeshBoundaryHalo::distributeSparse(), PatchTools::edgeNormals(), mapDistribute::mapDistribute(), mapDistribute::mapDistribute(), PatchTools::pointNormals(), and DistributedFieldMapper< DirectFieldMapperType >::size().
constructSize() [2/2]
label & constructSize () inline noexcept
Definition at line 489 of file mapDistributeBase.H.
subMap() [1/2]
const labelListList & subMap () const inline noexcept
Definition at line 495 of file mapDistributeBase.H.
Referenced by AMIInterpolation::agglomerate(), distributedTriSurfaceMesh::getVolumeType(), and extendedCellToFaceStencil::writeStencilStats().
subMap() [2/2]
labelListList & subMap () inline noexcept
Definition at line 501 of file mapDistributeBase.H.
constructMap() [1/2]
const labelListList & constructMap () const inline noexcept
Definition at line 507 of file mapDistributeBase.H.
Referenced by AMIInterpolation::agglomerate(), and distributedTriSurfaceMesh::getVolumeType().
constructMap() [2/2]
labelListList & constructMap () inline noexcept
Definition at line 513 of file mapDistributeBase.H.
subHasFlip() [1/2]
bool subHasFlip () const inline noexcept
Definition at line 519 of file mapDistributeBase.H.
Referenced by distributedTriSurfaceMesh::getVolumeType().
subHasFlip() [2/2]
bool & subHasFlip () inline noexcept
Definition at line 525 of file mapDistributeBase.H.
constructHasFlip() [1/2]
bool constructHasFlip () const inline noexcept
Definition at line 531 of file mapDistributeBase.H.
Referenced by distributedTriSurfaceMesh::getVolumeType().
constructHasFlip() [2/2]
bool & constructHasFlip () inline noexcept
Definition at line 537 of file mapDistributeBase.H.
comm()
label comm () const inline noexcept
Definition at line 543 of file mapDistributeBase.H.
Referenced by mapDistributeBase::exchangeMasks(), distributedTriSurfaceMesh::getVolumeType(), mapDistribute::mapDistribute(), and mapDistribute::mapDistribute().
nMaps()
label nMaps () const inline noexcept
Definition at line 549 of file mapDistributeBase.H.
References UList< T >::size().
subMapSizes()
Foam::labelList subMapSizes () const
Definition at line 968 of file mapDistributeBase.C.
References forAll, and UList< T >::size().
constructMapSizes()
Foam::labelList constructMapSizes () const
Definition at line 980 of file mapDistributeBase.C.
References forAll, and UList< T >::size().
schedule() [1/2]
Foam::List< Foam::labelPair > schedule (const labelListList & subMap, const labelListList & constructMap, const int tag, const label comm = UPstream::worldComm) static
Definition at line 179 of file mapDistributeBase.C.
References Pstream::broadcast(), forAll, UPstream::master(), UPstream::masterNo(), UPstream::myProcNo(), UPstream::nProcs(), UPstream::parRun(), UPstream::scheduled, and UPstream::subProcs().
schedule() [2/2]
const Foam::List< Foam::labelPair > & schedule () const
Definition at line 273 of file mapDistributeBase.C.
References UPstream::msgType().
whichSchedule()
const Foam::List< Foam::labelPair > & whichSchedule (const UPstream::commsTypes commsType) const
Definition at line 290 of file mapDistributeBase.C.
References List< T >::null(), and UPstream::scheduled.
clear()
void clear ()
Definition at line 992 of file mapDistributeBase.C.
References PtrList< T >::clear().
Referenced by mapDistribute::clear().
transfer()
void transfer (mapDistributeBase & rhs)
Definition at line 1004 of file mapDistributeBase.C.
References PtrList< T >::transfer().
Referenced by mapDistributeBase::mapDistributeBase(), and mapDistribute::transfer().
renumber()
Foam::label renumber (const globalIndex & globalNumbering, const List< Map< label > > & compactMap, const label globalElement) static
Definition at line 1026 of file mapDistributeBase.C.
References globalIndex::isLocal(), globalIndex::toLocal(), and globalIndex::whichProcID().
renumberMap()
Foam::label renumberMap (labelListList & mapElements, const labelUList & oldToNew, const bool hasFlip) static
Definition at line 273 of file mapDistributeBaseSubset.C.
References Foam::mag(), and Foam::max().
Referenced by faMeshDistributor::distribute().
compactLocalData() [1/3]
void compactLocalData (const bitSet & allowedLocalElems, const int tag = UPstream::msgType(), const bool doRenumber = false)
Definition at line 794 of file mapDistributeBaseSubset.C.
compactRemoteData() [1/3]
void compactRemoteData (const bitSet & allowedRemoteElems, const int tag = UPstream::msgType(), const bool doRenumber = false)
Definition at line 816 of file mapDistributeBaseSubset.C.
compactLocalData() [2/3]
void compactLocalData (const bitSet & allowedLocalElems, labelList & oldToNewSub, labelList & oldToNewConstruct, const label localSize = -1, const int tag = UPstream::msgType())
Definition at line 838 of file mapDistributeBaseSubset.C.
compactRemoteData() [2/3]
void compactRemoteData (const bitSet & allowedRemoteElems, labelList & oldToNewSub, labelList & oldToNewConstruct, const label localSize = -1, const int tag = UPstream::msgType())
Definition at line 869 of file mapDistributeBaseSubset.C.
compactData()
void compactData (const labelUList & localElements, const labelUList & remoteElements, labelList & oldToNewSub, labelList & oldToNewConstruct, const label localSize = -1, const int tag = UPstream::msgType())
Definition at line 622 of file mapDistributeBaseSubset.C.
compactLocalData() [3/3]
void compactLocalData (const labelUList & localElements, labelList & oldToNewSub, labelList & oldToNewConstruct, const label localSize = -1, const int tag = UPstream::msgType())
Definition at line 674 of file mapDistributeBaseSubset.C.
compactRemoteData() [3/3]
void compactRemoteData (const labelUList & remoteElements, labelList & oldToNewSub, labelList & oldToNewConstruct, const label localSize = -1, const int tag = UPstream::msgType())
Definition at line 716 of file mapDistributeBaseSubset.C.
distribute() [1/7]
template<class T , class NegateOp > void distribute (const Pstream::commsTypes commsType, const List< labelPair > & schedule, const label constructSize, const labelListList & subMap, const bool subHasFlip, const labelListList & constructMap, const bool constructHasFlip, List< T > & field, const NegateOp & negOp, const int tag = UPstream::msgType(), const label comm = UPstream::worldComm) static
Definition at line 411 of file mapDistributeBaseTemplates.C.
References Foam::abort(), UPstream::allProcs(), UPstream::blocking, Foam::FatalError, FatalErrorInFunction, field(), UPstream::myProcNo(), UPstream::nonBlocking, UPstream::nProcs(), UPstream::nRequests(), UPstream::parRun(), UIPstream::read(), PtrList< T >::resize(), UPstream::scheduled, PtrList< T >::setSize(), UPtrList< T >::size(), UList< T >::size(), PtrList< T >::transfer(), UPstream::waitRequests(), and UOPstream::write().
Referenced by faceAreaWeightAMI::calculate(), faceAreaWeightAMI2D::calculate(), mapDistribute::distribute(), mappedPatchBase::distribute(), distributedTriSurfaceMesh::findNearest(), distributedTriSurfaceMesh::getVolumeType(), mappedPatchBase::reverseDistribute(), and streamLineBase::writeToFile().
distribute() [2/7]
template<class T , class CombineOp , class NegateOp > void distribute (const Pstream::commsTypes commsType, const List< labelPair > & schedule, const label constructSize, const labelListList & subMap, const bool subHasFlip, const labelListList & constructMap, const bool constructHasFlip, List< T > & field, const T & nullValue, const CombineOp & cop, const NegateOp & negOp, const int tag = UPstream::msgType(), const label comm = UPstream::worldComm) static
Definition at line 873 of file mapDistributeBaseTemplates.C.
References Foam::abort(), UPstream::allProcs(), UPstream::blocking, Foam::FatalError, FatalErrorInFunction, field(), UPstream::myProcNo(), UPstream::nonBlocking, UPstream::nProcs(), UPstream::nRequests(), UPstream::parRun(), UIPstream::read(), PtrList< T >::resize(), UPstream::scheduled, UPtrList< T >::size(), UList< T >::size(), PtrList< T >::transfer(), UPstream::waitRequests(), and UOPstream::write().
distribute() [3/7]
template<class T > void distribute (List< T > & values, const int tag = UPstream::msgType()) const
Definition at line 1469 of file mapDistributeBaseTemplates.C.
distribute() [4/7]
template<class T > void distribute (DynamicList< T > & values, const int tag = UPstream::msgType()) const
Definition at line 1480 of file mapDistributeBaseTemplates.C.
References UPtrList< T >::size().
distribute() [5/7]
template<class T , class NegateOp > void distribute (List< T > & values, const NegateOp & negOp, const int tag = UPstream::msgType()) const
Definition at line 1454 of file mapDistributeBaseTemplates.C.
References UPstream::defaultCommsType.
distribute() [6/7]
template<class T , class NegateOp > void distribute (const Pstream::commsTypes commsType, List< T > & values, const NegateOp & negOp, const int tag = UPstream::msgType()) const
Definition at line 1399 of file mapDistributeBaseTemplates.C.
distribute() [7/7]
template<class T , class NegateOp > void distribute (const Pstream::commsTypes commsType, const T & nullValue, List< T > & values, const NegateOp & negOp, const int tag = UPstream::msgType()) const
Definition at line 1425 of file mapDistributeBaseTemplates.C.
reverseDistribute() [1/5]
template<class T > void reverseDistribute (const label constructSize, List< T > & values, const int tag = UPstream::msgType()) const
Definition at line 1575 of file mapDistributeBaseTemplates.C.
References UPstream::defaultCommsType.
Referenced by mapDistribute::reverseDistribute(), and mapDistribute::reverseDistribute().
reverseDistribute() [2/5]
template<class T > void reverseDistribute (const label constructSize, const T & nullValue, List< T > & values, const int tag = UPstream::msgType()) const
Definition at line 1593 of file mapDistributeBaseTemplates.C.
References UPstream::defaultCommsType.
reverseDistribute() [3/5]
template<class T > void reverseDistribute (const Pstream::commsTypes commsType, const label constructSize, List< T > & values, const int tag = UPstream::msgType()) const
Definition at line 1497 of file mapDistributeBaseTemplates.C.
reverseDistribute() [4/5]
template<class T , class NegateOp > void reverseDistribute (const Pstream::commsTypes commsType, const label constructSize, List< T > & values, const NegateOp & negOp, const int tag = UPstream::msgType()) const
Definition at line 1517 of file mapDistributeBaseTemplates.C.
reverseDistribute() [5/5]
template<class T > void reverseDistribute (const Pstream::commsTypes commsType, const label constructSize, const T & nullValue, List< T > & values, const int tag = UPstream::msgType()) const
Definition at line 1544 of file mapDistributeBaseTemplates.C.
send() [1/3]
template<class T > void send (PstreamBuffers & pBufs, const List< T > & field) const
Definition at line 1332 of file mapDistributeBaseTemplates.C.
References UPstream::allProcs(), field(), and UList< T >::size().
receive() [1/3]
template<class T > void receive (PstreamBuffers & pBufs, List< T > & field) const
Definition at line 1360 of file mapDistributeBaseTemplates.C.
References Foam::abort(), UPstream::allProcs(), Foam::FatalError, FatalErrorInFunction, field(), UPtrList< T >::size(), and UList< T >::size().
send() [2/3]
template<class T , class negateOp > void send (const labelListList & subMap, const bool subHasFlip, const labelListList & constructMap, const bool constructHasFlip, const UList< T > & field, labelRange & requests, PtrList< List< T > > & sendFields, PtrList< List< T > > & recvFields, const negateOp & negOp, const int tag, const label comm) static
Definition at line 157 of file mapDistributeBaseTemplates.C.
References UPstream::allProcs(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, field(), forAll, PtrList< T >::free(), UPstream::myProcNo(), UPstream::nonBlocking, UPstream::nProcs(), UPstream::nRequests(), UIPstream::read(), PtrList< T >::resize(), PtrList< T >::set(), List< T >::set(), UPtrList< T >::size(), UList< T >::size(), and UOPstream::write().
send() [3/3]
template<class T > void send (const UList< T > & field, labelRange & requests, PtrList< List< T > > & sendFields, PtrList< List< T > > & recvFields, const int tag = UPstream::msgType()) const
Definition at line 273 of file mapDistributeBaseTemplates.C.
References field().
receive() [2/3]
template<class T , class CombineOp , class negateOp > void receive (const label constructSize, const labelListList & constructMap, const bool constructHasFlip, const UPtrList< List< T > > & sendFields, const UPtrList< List< T > > & recvFields, const labelRange & requests, List< T > & field, const CombineOp & cop, const negateOp & negOp, const int tag, const label comm) static
Definition at line 300 of file mapDistributeBaseTemplates.C.
References UPstream::allProcs(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, field(), UPstream::myProcNo(), PtrList< T >::resize(), PtrList< T >::set(), UPtrList< T >::size(), UList< T >::size(), and UPstream::waitRequests().
receive() [3/3]
template<class T > void receive (const labelRange & requests, const UPtrList< List< T > > & sendFields, const UPtrList< List< T > > & recvFields, List< T > & field, const int tag = UPstream::msgType()) const
Definition at line 384 of file mapDistributeBaseTemplates.C.
References field().
printLayout()
void printLayout (Ostream & os) const
Definition at line 304 of file mapDistributeBase.C.
References Foam::endl(), forAll, Foam::labelMax, Foam::labelMin, Foam::mag(), Foam::max(), Foam::min(), UPstream::myProcNo(), Foam::nl, UPstream::nProcs(), and os().
Referenced by mapDistributeBase::mapDistributeBase(), mapDistributeBase::mapDistributeBase(), and mapDistribute::printLayout().
operator=() [1/2]
void operator= (const mapDistributeBase & rhs)
Definition at line 1052 of file mapDistributeBase.C.
Referenced by mapDistribute::operator=().
operator=() [2/2]
void operator= (mapDistributeBase && rhs)
Definition at line 1069 of file mapDistributeBase.C.
info()
InfoProxy< mapDistributeBase > info () const inline noexcept
Definition at line 1034 of file mapDistributeBase.H.
readDict()
void readDict (const dictionary & dict)
Definition at line 93 of file mapDistributeBaseIO.C.
References dict, dictionary::get(), and dictionary::subDict().
Referenced by mapDistributeBase::mapDistributeBase(), and mapDistribute::readDict().
writeEntries()
void writeEntries (Ostream & os) const
Definition at line 115 of file mapDistributeBaseIO.C.
References Ostream::beginBlock(), Ostream::endBlock(), Foam::nl, os(), Ostream::writeEntry(), and Foam::writeMaps().
Referenced by mapDistribute::writeEntries().
updateMesh()
void updateMesh (const mapPolyMesh &) inline
Definition at line 1055 of file mapDistributeBase.H.
References NotImplemented.
compact() [1/2]
void compact (const boolList & remoteElemUsed, const int tag = UPstream::msgType())
Definition at line 902 of file mapDistributeBaseSubset.C.
compact() [2/2]
void compact (const boolList & remoteElemUsed, const label localSize, labelList & oldToNewSub, labelList & oldToNewConstruct, const int tag = UPstream::msgType())
Definition at line 913 of file mapDistributeBaseSubset.C.
accessAndFlip() [3/3]
template<class T , class NegateOp > Foam::List< T > accessAndFlip (const UList< T > & values, const labelUList & indices, const bool hasFlip, const NegateOp & negOp)
Definition at line 107 of file mapDistributeBaseTemplates.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::output(), and UList< T >::size().
Friends And Related Symbol Documentation
operator>>
Istream & operator>> (Istream & , mapDistributeBase &) friend
operator<<
Ostream & operator<< (Ostream & , const mapDistributeBase &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/mapDistribute/mapDistributeBase.H
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/mapDistribute/mapDistributeBase.C
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/mapDistribute/mapDistributeBaseIO.C
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/mapDistribute/mapDistributeBaseSubset.C
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/mapDistribute/mapDistributeBaseTemplates.C