OpenFOAM: gaussGrad< Type > Class Template Reference
gaussGrad< Type > Class Template Reference
Basic second-order gradient scheme using face-interpolation and Gauss' theorem.
#include <gaussFaGrad.H>
Public Member Functions
TypeName ("Gauss")
gaussGrad (const faMesh &mesh)
gaussGrad (const faMesh &mesh, Istream &is)
virtual tmp< GeometricField< typename outerProduct< vector, Type >::type, faPatchField, areaMesh > > calcGrad (const GeometricField< Type, faPatchField, areaMesh > &vsf, const word &name) const
Public Member Functions inherited from gradScheme< Type >
declareRunTimeSelectionTable (tmp, gradScheme, Istream,(const faMesh &mesh, Istream &schemeData),(mesh, schemeData))
gradScheme (const faMesh &mesh)
virtual ~gradScheme ()=default
const faMesh & mesh () const
tmp< GeometricField< typename outerProduct< vector, Type >::type, faPatchField, areaMesh > > grad (const GeometricField< Type, faPatchField, areaMesh > &, const word &name) const
tmp< GeometricField< typename outerProduct< vector, Type >::type, faPatchField, areaMesh > > grad (const GeometricField< Type, faPatchField, areaMesh > &) const
tmp< GeometricField< typename outerProduct< vector, Type >::type, faPatchField, areaMesh > > grad (const tmp< GeometricField< Type, faPatchField, areaMesh > > &) const
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Static Public Member Functions
static tmp< GeometricField< typename outerProduct< vector, Type >::type, faPatchField, areaMesh > > gradf (const GeometricField< Type, faePatchField, edgeMesh > &, const word &name)
static void correctBoundaryConditions (const GeometricField< Type, faPatchField, areaMesh > &, GeometricField< typename outerProduct< vector, Type >::type, faPatchField, areaMesh > &)
Static Public Member Functions inherited from gradScheme< Type >
static tmp< gradScheme< Type > > New (const faMesh &mesh, Istream &schemeData)
Detailed Description
template<class Type>
class Foam::fa::gaussGrad< Type >
Basic second-order gradient scheme using face-interpolation and Gauss' theorem.
Source files
gaussFaGrad.H
gaussFaGrad.C
gaussFaGrads.C
Definition at line 57 of file gaussFaGrad.H.
Constructor & Destructor Documentation
gaussGrad() [1/2]
template<class Type > gaussGrad (const faMesh & mesh) inline
Definition at line 85 of file gaussFaGrad.H.
gaussGrad() [2/2]
template<class Type > gaussGrad (const faMesh & mesh, Istream & is) inline
Definition at line 92 of file gaussFaGrad.H.
References gradScheme< Type >::mesh(), and edgeInterpolationScheme< Type >::New().
Member Function Documentation
TypeName()
template<class Type > TypeName ("Gauss")
gradf()
template<class Type > tmp< GeometricField< typename outerProduct< vector, Type >::type, faPatchField, areaMesh > > gradf (const GeometricField< Type, faePatchField, edgeMesh > & ssf, const word & name) static
Definition at line 49 of file gaussFaGrad.C.
References Foam::fac::edgeIntegrate(), and n.
Referenced by Foam::fac::grad().
calcGrad()
template<class Type > tmp< GeometricField< typename outerProduct< vector, Type >::type, faPatchField, areaMesh > > calcGrad (const GeometricField< Type, faPatchField, areaMesh > & vsf, const word & name) const virtual
Implements gradScheme< Type >.
Definition at line 80 of file gaussFaGrad.C.
References correctBoundaryConditions(), Foam::fac::edgeIntegrate(), Foam::interpolate(), and Foam::name().
correctBoundaryConditions()
template<class Type > void correctBoundaryConditions (const GeometricField< Type, faPatchField, areaMesh > & vsf, GeometricField< typename outerProduct< vector, Type >::type, faPatchField, areaMesh > & gGrad) static
Definition at line 109 of file gaussFaGrad.C.
References forAll.
Referenced by leastSquaresFaGrad< Type >::calcGrad(), makeFaGradScheme(), and makeFaGradScheme().
The documentation for this class was generated from the following files:
src/finiteArea/finiteArea/gradSchemes/gaussFaGrad/gaussFaGrad.H
src/finiteArea/finiteArea/gradSchemes/gaussFaGrad/gaussFaGrad.C