OpenFOAM: cloud Class Reference
cloud Class Reference
A cloud is a registry collection of lagrangian particles.
#include <cloud.H>
Public Types
enum class geometryType { COORDINATES , POSITIONS }
Public Types inherited from IOobject
enum objectState : char { GOOD , BAD }
enum fileCheckTypes : char { timeStamp , timeStampMaster , inotify , inotifyMaster }
Public Types inherited from IOobjectOption
enum readOption : unsigned char {
NO_READ = 0 , MUST_READ = 0x1 , READ_MODIFIED = 0x3 , MUST_READ_IF_MODIFIED = 0x3 ,
LAZY_READ = 0x4 , READ_IF_PRESENT = 0x4
}
enum writeOption : unsigned char { NO_WRITE = 0 , AUTO_WRITE = 0x10 }
enum registerOption : unsigned char { NO_REGISTER = 0 , REGISTER = 1 }
Public Types inherited from HashTable< regIOobject * >
typedef HashTable< regIOobject *, word, Foam::Hash< word > > this_type
typedef std::conditional< std::is_same< Foam::zero, typenamestd::remove_cv< regIOobject * >::type >::value, Detail::HashTableSingle< word >, Detail::HashTablePair< word, regIOobject * > >::type node_type
typedef word key_type
typedef regIOobject * mapped_type
typedef regIOobject * value_type
typedef Foam::Hash< word > hasher
typedef regIOobject * * pointer
typedef regIOobject * & reference
typedef const regIOobject * * const_pointer
typedef const regIOobject * & const_reference
typedef label difference_type
typedef label size_type
using key_iterator = key_iterator_base< iterator >
using const_key_iterator = key_iterator_base< const_iterator >
Public Member Functions
TypeName ("cloud")
cloud (const objectRegistry &obr)
cloud (const objectRegistry &obr, const word &cloudName)
virtual ~cloud ()=default
virtual label nParcels () const
virtual void autoMap (const mapPolyMesh &)
virtual void readObjects (const objectRegistry &obr)
virtual void writeObjects (objectRegistry &obr) const
template<class Type >
Foam::IOField< Type > & createIOField (const word &fieldName, const label nParticle, objectRegistry &obr)
Public Member Functions inherited from objectRegistry
TypeName ("objectRegistry")
objectRegistry (const Time &db, const label nObjects=128)
objectRegistry (const IOobject &io, const label nObjects=128)
virtual ~objectRegistry ()
const objectRegistry & thisDb () const noexcept
const objectRegistry & parent () const noexcept
const Time & time () const noexcept
bool isTimeDb () const noexcept
virtual const fileName & dbDir () const
HashTable< wordHashSet > classes () const
template<class MatchPredicate >
HashTable< wordHashSet > classes (const MatchPredicate &matchName) const
UPtrList< const regIOobject > csorted () const
UPtrList< const regIOobject > sorted () const
UPtrList< regIOobject > sorted ()
template<class Type >
UPtrList< const Type > csorted () const
template<class Type >
UPtrList< const Type > sorted () const
template<class Type >
UPtrList< Type > sorted ()
template<class Type , class MatchPredicate >
UPtrList< const Type > csorted (const MatchPredicate &matchName) const
template<class Type , class MatchPredicate >
UPtrList< const Type > sorted (const MatchPredicate &matchName) const
template<class Type , class MatchPredicate >
UPtrList< Type > sorted (const MatchPredicate &matchName)
label count (const char *clsName) const
template<class MatchPredicate >
label count (const MatchPredicate &matchClass) const
template<class MatchPredicate1 , class MatchPredicate2 >
label count (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName) const
template<class Type >
label count (const bool strict=false) const
template<class Type , class MatchPredicate >
label count (const MatchPredicate &matchName) const
wordList names () const
wordList names (const char *clsName) const
template<class MatchPredicate >
wordList names (const MatchPredicate &matchClass) const
template<class MatchPredicate1 , class MatchPredicate2 >
wordList names (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName) const
template<class Type >
wordList names () const
template<class Type , class MatchPredicate >
wordList names (const MatchPredicate &matchName) const
wordList sortedNames () const
wordList sortedNames (const char *clsName) const
template<class MatchPredicate >
wordList sortedNames (const MatchPredicate &matchClass) const
template<class MatchPredicate1 , class MatchPredicate2 >
wordList sortedNames (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName) const
template<class Type >
wordList sortedNames () const
template<class Type , class MatchPredicate >
wordList sortedNames (const MatchPredicate &matchName) const
const objectRegistry & subRegistry (const word &name, const bool forceCreate=false, const bool recursive=false) const
template<class Type >
HashTable< const Type * > lookupClass (const bool strict=false) const
template<class Type >
HashTable< Type * > lookupClass (const bool strict=false)
const regIOobject * cfindIOobject (const word &name, const bool recursive=false) const
bool contains (const word &name, const bool recursive=false) const
template<class Type >
bool foundObject (const word &name, const bool recursive=false) const
template<class Type >
const Type * cfindObject (const word &name, const bool recursive=false) const
template<class Type >
const Type * findObject (const word &name, const bool recursive=false) const
template<class Type >
Type * findObject (const word &name, const bool recursive=false)
template<class Type >
Type * getObjectPtr (const word &name, const bool recursive=false) const
template<class Type >
const Type & lookupObject (const word &name, const bool recursive=false) const
template<class Type >
Type & lookupObjectRef (const word &name, const bool recursive=false) const
label getEvent () const
bool checkIn (regIOobject *io) const
bool checkIn (regIOobject &io) const
bool checkOut (regIOobject *io) const
bool checkOut (regIOobject &io) const
bool checkOut (const word &key) const
void clear ()
void clearStorage ()
bool erase (const iterator &iter)
bool erase (const word &key)
label erase (std::initializer_list< word > keys)
label erase (const UList< word > &keys)
virtual void rename (const word &newName)
bool cacheTemporaryObject (const word &name) const
template<class Type >
bool cacheTemporaryObject (Type &obj) const
void resetCacheTemporaryObject (const regIOobject *io) const
void resetCacheTemporaryObject (const regIOobject &io) const
bool checkCacheTemporaryObjects () const
virtual bool modified () const
void readModifiedObjects ()
virtual bool readIfModified ()
virtual bool writeData (Ostream &) const
virtual bool writeObject (IOstreamOption streamOpt, const bool writeOnProc) const
bool found (const word &name, bool recursive=false) const
template<class Type >
const Type * lookupObjectPtr (const word &name, bool recursive=false) const
template<class Type >
Type * lookupObjectRefPtr (const word &name, bool recursive=false) const
template<class MatchPredicate >
Foam::HashTable< Foam::wordHashSet > classesImpl (const objectRegistry &list, const MatchPredicate &matchName)
template<class MatchPredicate1 , class MatchPredicate2 >
Foam::label countImpl (const objectRegistry &list, const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName)
template<class Type , class MatchPredicate >
Foam::label countTypeImpl (const objectRegistry &list, const MatchPredicate &matchName)
template<class MatchPredicate1 , class MatchPredicate2 >
Foam::wordList namesImpl (const objectRegistry &list, const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName, const bool doSort)
template<class Type , class MatchPredicate >
Foam::wordList namesTypeImpl (const objectRegistry &list, const MatchPredicate &matchName, const bool doSort)
template<class Type , class MatchPredicate >
Foam::UPtrList< Type > objectsTypeImpl (const objectRegistry &list, const MatchPredicate &matchName)
template<class MatchPredicate >
Foam::HashTable< Foam::wordHashSet > classes (const MatchPredicate &matchName) const
template<class MatchPredicate >
Foam::label count (const MatchPredicate &matchClass) const
template<class MatchPredicate1 , class MatchPredicate2 >
Foam::label count (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName) const
template<class Type , class MatchPredicate >
Foam::label count (const MatchPredicate &matchName) const
template<class Type >
Foam::label count (const bool strict) const
template<class Type >
Foam::UPtrList< const Type > csorted () const
template<class Type >
Foam::UPtrList< const Type > sorted () const
template<class Type >
Foam::UPtrList< Type > sorted ()
template<class Type , class MatchPredicate >
Foam::UPtrList< const Type > csorted (const MatchPredicate &matchName) const
template<class Type , class MatchPredicate >
Foam::UPtrList< const Type > sorted (const MatchPredicate &matchName) const
template<class Type , class MatchPredicate >
Foam::UPtrList< Type > sorted (const MatchPredicate &matchName)
template<class MatchPredicate >
Foam::wordList names (const MatchPredicate &matchClass) const
template<class MatchPredicate1 , class MatchPredicate2 >
Foam::wordList names (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName) const
template<class Type >
Foam::wordList names () const
template<class Type , class MatchPredicate >
Foam::wordList names (const MatchPredicate &matchName) const
template<class MatchPredicate >
Foam::wordList sortedNames (const MatchPredicate &matchClass) const
template<class MatchPredicate1 , class MatchPredicate2 >
Foam::wordList sortedNames (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName) const
template<class Type >
Foam::wordList sortedNames () const
template<class Type , class MatchPredicate >
Foam::wordList sortedNames (const MatchPredicate &matchName) const
template<class Type >
Foam::HashTable< const Type * > lookupClass (const bool strict) const
template<class Type >
Foam::HashTable< Type * > lookupClass (const bool strict)
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
regIOobject (const IOobject &io, const bool isTimeObject=false)
regIOobject (const regIOobject &rio)
regIOobject (const regIOobject &rio, bool registerCopy)
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
regIOobject (const IOobject &io, const regIOobject &rio)
virtual ~regIOobject ()
bool checkIn ()
bool checkOut ()
virtual void addWatch ()
bool registered () const noexcept
bool ownedByRegistry () const noexcept
bool store ()
void release (const bool unregister=false) noexcept
label eventNo () const noexcept
label & eventNo () noexcept
bool upToDate (const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
void setUpToDate ()
const dictionary * findMetaData () const noexcept
dictionary & getMetaData () noexcept
void removeMetaData ()
virtual void updateMetaData ()
virtual fileName filePath () const
bool headerOk ()
Istream & readStream (const word &, const bool readOnProc=true)
void close ()
virtual bool readData (Istream &)
virtual bool read ()
virtual label addWatch (const fileName &)
const labelList & watchIndices () const noexcept
labelList & watchIndices () noexcept
virtual bool write (const bool writeOnProc=true) const
virtual bool global () const
void operator= (const IOobject &io)
virtual bool writeObject (IOstreamOption::streamFormat fmt, IOstreamOption::versionNumber ver, IOstreamOption::compressionType cmp, const bool writeOnProc) const
Public Member Functions inherited from IOobject
TypeName ("IOobject")
IOobject (const IOobject &)=default
virtual ~IOobject ()=default
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const fileName &path, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const fileName &path, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const IOobject &io, const objectRegistry &registry)
IOobject (const IOobject &io, const word &name)
IOobject (const IOobject &io, const word &name, const fileName &local)
IOobject (const IOobject &io, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt)
IOobject (const IOobject &io, IOobjectOption::registerOption regOpt)
autoPtr< IOobject > clone () const
autoPtr< IOobject > clone (const objectRegistry &registry) const
const objectRegistry & db () const noexcept
const Time & time () const noexcept
const word & name () const noexcept
const word & headerClassName () const noexcept
word & headerClassName () noexcept
const string & note () const noexcept
string & note () noexcept
unsigned labelByteSize () const noexcept
unsigned scalarByteSize () const noexcept
void resetHeader (const word &newName=word::null)
bool hasHeaderClass () const noexcept
template<class Type >
bool isHeaderClass () const
template<class Type >
bool isHeaderClassName () const
word group () const
word member () const
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const noexcept
fileName & instance () noexcept
const fileName & local () const noexcept
fileName path () const
fileName path (const word &instance, const fileName &local=fileName::null) const
fileName objectPath () const
fileName objectRelPath () const
fileName localFilePath (const word &typeName, const bool search=true) const
fileName globalFilePath (const word &typeName, const bool search=true) const
IOstreamOption parseHeader (const dictionary &headerDict)
bool readHeader (Istream &is)
bool readHeader (dictionary &headerDict, Istream &is)
template<class Type >
bool typeHeaderOk (const bool checkType=true, const bool search=true, const bool verbose=true)
template<class Type >
void warnNoRereading () const
bool writeHeader (Ostream &os) const
bool writeHeader (Ostream &os, const word &objectType) const
void writeHeader (dictionary &dict, IOstreamOption streamOpt) const
void writeHeader (dictionary &dict, const word &objectType, IOstreamOption streamOpt) const
bool good () const noexcept
bool bad () const noexcept
InfoProxy< IOobject > info () const noexcept
void operator= (const IOobject &io)
template<>
bool isHeaderClass () const
template<class StringType >
Foam::word groupName (StringType base, const word &group)
Public Member Functions inherited from IOobjectOption
constexpr IOobjectOption (readOption rOpt=readOption::NO_READ, writeOption wOpt=writeOption::NO_WRITE, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (readOption rOpt, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (writeOption wOpt, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (registerOption registerObject, bool globalObject=false) noexcept
constexpr IOobjectOption (readOption rOpt, writeOption wOpt, bool registerObject, bool globalObject=false) noexcept
constexpr IOobjectOption (bool registerObject, bool globalObject=false) noexcept
readOption readOpt () const noexcept
readOption readOpt (readOption opt) noexcept
writeOption writeOpt () const noexcept
writeOption writeOpt (writeOption opt) noexcept
bool registerObject () const noexcept
bool registerObject (bool on) noexcept
bool globalObject () const noexcept
bool globalObject (bool on) noexcept
bool isAnyRead () const noexcept
bool isReadRequired () const noexcept
bool isReadOptional () const noexcept
readOption & readOpt () noexcept
writeOption & writeOpt () noexcept
bool & registerObject () noexcept
bool & globalObject () noexcept
Public Member Functions inherited from HashTable< regIOobject * >
HashTable ()
HashTable (const label size)
HashTable (Istream &is, const label size=128)
HashTable (const this_type &ht)
HashTable (this_type &&rhs)
HashTable (std::initializer_list< std::pair< word, regIOobject * > > list)
~HashTable ()
bool empty () const noexcept
label size () const noexcept
label capacity () const noexcept
regIOobject * & at (const word &key)
const regIOobject * & at (const word &key) const
bool contains (const word &key) const
iterator find (const word &key)
const_iterator find (const word &key) const
const_iterator cfind (const word &key) const
const regIOobject * & lookup (const word &key, const regIOobject * &deflt) const
List< word > toc () const
List< word > sortedToc () const
List< word > sortedToc (const Compare &comp) const
Foam::List< word > sortedToc (const Compare &comp) const
List< word > tocKeys (const UnaryPredicate &pred, const bool invert=false) const
Foam::List< word > tocKeys (const UnaryPredicate &pred, const bool invert) const
List< word > tocValues (const UnaryPredicate &pred, const bool invert=false) const
Foam::List< word > tocValues (const UnaryPredicate &pred, const bool invert) const
List< word > tocEntries (const BinaryPredicate &pred, const bool invert=false) const
Foam::List< word > tocEntries (const BinaryPredicate &pred, const bool invert) const
UPtrList< const node_type > csorted () const
UPtrList< const node_type > sorted () const
UPtrList< node_type > sorted ()
label countKeys (const UnaryPredicate &pred, const bool invert=false) const
Foam::label countKeys (const UnaryPredicate &pred, const bool invert) const
label countValues (const UnaryPredicate &pred, const bool invert=false) const
Foam::label countValues (const UnaryPredicate &pred, const bool invert) const
label countEntries (const BinaryPredicate &pred, const bool invert=false) const
Foam::label countEntries (const BinaryPredicate &pred, const bool invert) const
bool emplace (const word &key, Args &&... args)
bool emplace_set (const word &key, Args &&... args)
bool insert (const word &key, const regIOobject * &obj)
bool insert (const word &key, regIOobject * &&obj)
bool set (const word &key, const regIOobject * &obj)
bool set (const word &key, regIOobject * &&obj)
bool erase (const iterator &iter)
bool erase (const word &key)
label erase (const HashTable< AnyType, word, AnyHash > &other)
label erase (std::initializer_list< word > keys)
label erase (InputIter first, InputIter last)
label erase (const FixedList< word, N > &keys)
label erase (const UList< word > &keys)
Foam::label erase (InputIter first, InputIter last)
Foam::label erase (const FixedList< word, N > &keys)
Foam::label erase (const HashTable< AnyType, word, AnyHash > &other)
label retain (const HashTable< AnyType, word, AnyHash > &other)
Foam::label retain (const HashTable< AnyType, word, AnyHash > &other)
label filterKeys (const UnaryPredicate &pred, const bool pruning=false)
Foam::label filterKeys (const UnaryPredicate &pred, const bool pruning)
label filterValues (const UnaryPredicate &pred, const bool pruning=false)
Foam::label filterValues (const UnaryPredicate &pred, const bool pruning)
label filterEntries (const BinaryPredicate &pred, const bool pruning=false)
Foam::label filterEntries (const BinaryPredicate &pred, const bool pruning)
void resize (const label sz)
void clear ()
void clearStorage ()
void swap (HashTable< regIOobject *, word, Foam::Hash< word > > &rhs)
void transfer (HashTable< regIOobject *, word, Foam::Hash< word > > &rhs)
void merge (HashTable< regIOobject *, word, Foam::Hash< word > > &source)
void merge (HashTable< regIOobject *, word, Foam::Hash< word > > &&source)
regIOobject * & operator[] (const word &key)
const regIOobject * & operator[] (const word &key) const
regIOobject * & operator() (const word &key)
regIOobject * & operator() (const word &key, const regIOobject * &deflt)
void operator= (const this_type &rhs)
void operator= (std::initializer_list< std::pair< word, regIOobject * > > rhs)
void operator= (this_type &&rhs)
bool operator== (const this_type &rhs) const
bool operator!= (const this_type &rhs) const
this_type & operator+= (const this_type &rhs)
const_iterator_pair< const_key_iterator, this_type > keys () const
iterator begin ()
const_iterator begin () const
const_iterator cbegin () const
iterator end () noexcept
const_iterator end () const noexcept
constexpr const_iterator cend () const noexcept
Ostream & printInfo (Ostream &os) const
Ostream & writeKeys (Ostream &os, const label shortLen=0) const
bool found (const word &key) const
Public Member Functions inherited from HashTableCore
ClassName ("HashTable")
HashTableCore () noexcept=default
Static Public Member Functions
template<class Type >
static IOField< Type > & createIOField (const word &fieldName, const label nParticle, objectRegistry &obr)
template<class Type >
static const IOField< Type > * findIOField (const word &fieldName, const objectRegistry &obr)
static const IOField< point > * findIOPosition (const objectRegistry &obr)
template<class Type >
static const IOField< Type > & lookupIOField (const word &fieldName, const objectRegistry &obr)
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *p)
template<class Type >
static Type & store (autoPtr< Type > &ptr)
template<class Type >
static Type & store (autoPtr< Type > &&ptr)
template<class Type >
static Type & store (refPtr< Type > &ptr)
template<class Type >
static Type & store (refPtr< Type > &&ptr)
template<class Type >
static Type & store (tmp< Type > &ptr)
template<class Type >
static Type & store (tmp< Type > &&ptr)
Static Public Member Functions inherited from IOobject
static bool bannerEnabled () noexcept
static bool bannerEnabled (bool on) noexcept
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
template<class StringType >
static word groupName (StringType base, const word &group)
static word group (const word &name)
static word member (const word &name)
static word scopedName (const std::string &scope, const word &name)
static IOobject selectIO (const IOobject &io, const fileName &altFile, const word &ioName="")
static Ostream & writeBanner (Ostream &os, const bool noSyntaxHint=false)
static Ostream & writeDivider (Ostream &os)
static Ostream & writeEndDivider (Ostream &os)
Static Public Member Functions inherited from IOobjectOption
static bool isAnyRead (readOption opt) noexcept
static bool isReadRequired (readOption opt) noexcept
static bool isReadOptional (readOption opt) noexcept
static readOption lazierRead (readOption opt) noexcept
Static Public Member Functions inherited from HashTableCore
static label canonicalSize (const label requested_size)
Static Public Attributes
static const Enum< geometryType > geometryTypeNames
static const word prefix
static word defaultName
Static Public Attributes inherited from IOobject
static const Enum< fileCheckTypes > fileCheckTypesNames
static char scopeSeparator
static fileCheckTypes fileModificationChecking
static float fileModificationSkew
static int maxFileModificationPolls
Static Public Attributes inherited from HashTableCore
static const label maxTableSize
Additional Inherited Members
Protected Member Functions inherited from regIOobject
bool readHeaderOk (const IOstreamOption::streamFormat fmt, const word &typeName)
Protected Member Functions inherited from IOobject
void setBad (const string &s)
Static Protected Member Functions inherited from IOobject
static void writeHeaderContent (Ostream &os, const IOobject &io, const word &objectType, const dictionary *metaDataDict=nullptr)
static void writeHeaderContent (dictionary &dict, const IOobject &io, const word &objectType, IOstreamOption streamOpt, const dictionary *metaDataDict=nullptr)
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
Detailed Description
A cloud is a registry collection of lagrangian particles.
Source files
cloud.H
cloud.C
Definition at line 53 of file cloud.H.
Member Enumeration Documentation
geometryType
enum class geometryType strong
Enumerator
COORDINATES
barycentric coordinates
POSITIONS
positions
Definition at line 70 of file cloud.H.
Constructor & Destructor Documentation
cloud() [1/2]
cloud (const objectRegistry & obr) explicit
Definition at line 45 of file cloud.C.
cloud() [2/2]
cloud (const objectRegistry & obr, const word & cloudName)
Definition at line 51 of file cloud.C.
~cloud()
virtual ~cloud () virtual default
Member Function Documentation
TypeName()
TypeName ("cloud")
nParcels()
Foam::label nParcels () const virtual
Reimplemented in Cloud< ParticleType >, Cloud< basicKinematicCollidingParcel >, Cloud< Foam::DTRMParticle >, Cloud< Foam::molecule >, Cloud< Foam::passiveParticle >, Cloud< indexedParticle >, Cloud< injectedParticle >, Cloud< molecule >, Cloud< ParcelType >, Cloud< parcelType >, Cloud< passiveParticle >, Cloud< passivePositionParticle >, Cloud< solidParticle >, Cloud< streamLineParticle >, Cloud< typename CloudType::parcelType >, Cloud< wallBoundedStreamLineParticle >, KinematicCloud< CloudType >, KinematicCloud< Cloud< basicKinematicCollidingParcel > >, and KinematicCloud< Foam::DSMCCloud >.
Definition at line 70 of file cloud.C.
References NotImplemented.
Referenced by KinematicCloud< CloudType >::nParcels().
autoMap()
void autoMap (const mapPolyMesh &) virtual
Reimplemented in unmappedPassivePositionParticleCloud, Cloud< ParticleType >, Cloud< basicKinematicCollidingParcel >, Cloud< Foam::DTRMParticle >, Cloud< Foam::molecule >, Cloud< Foam::passiveParticle >, Cloud< indexedParticle >, Cloud< injectedParticle >, Cloud< molecule >, Cloud< ParcelType >, Cloud< parcelType >, Cloud< passiveParticle >, Cloud< passivePositionParticle >, Cloud< solidParticle >, Cloud< streamLineParticle >, Cloud< typename CloudType::parcelType >, Cloud< wallBoundedStreamLineParticle >, DSMCCloud< ParcelType >, KinematicCloud< CloudType >, KinematicCloud< Cloud< basicKinematicCollidingParcel > >, KinematicCloud< Foam::DSMCCloud >, ReactingCloud< CloudType >, ReactingCloud< Foam::DSMCCloud >, ReactingHeterogeneousCloud< CloudType >, ReactingHeterogeneousCloud< Foam::DSMCCloud >, ReactingMultiphaseCloud< CloudType >, ReactingMultiphaseCloud< Foam::DSMCCloud >, ThermoCloud< CloudType >, and ThermoCloud< Foam::DSMCCloud >.
Definition at line 77 of file cloud.C.
References NotImplemented.
readObjects()
void readObjects (const objectRegistry & obr) virtual
Reimplemented in injectedParticleCloud, KinematicCloud< CloudType >, KinematicCloud< Cloud< basicKinematicCollidingParcel > >, KinematicCloud< Foam::DSMCCloud >, ReactingHeterogeneousCloud< CloudType >, and ReactingHeterogeneousCloud< Foam::DSMCCloud >.
Definition at line 83 of file cloud.C.
References NotImplemented.
Referenced by ReactingHeterogeneousCloud< CloudType >::readObjects().
writeObjects()
void writeObjects (objectRegistry & obr) const virtual
Reimplemented in injectedParticleCloud, KinematicCloud< CloudType >, KinematicCloud< Cloud< basicKinematicCollidingParcel > >, KinematicCloud< Foam::DSMCCloud >, ReactingCloud< CloudType >, ReactingCloud< Foam::DSMCCloud >, ReactingHeterogeneousCloud< CloudType >, and ReactingHeterogeneousCloud< Foam::DSMCCloud >.
Definition at line 89 of file cloud.C.
References NotImplemented.
Referenced by ReactingCloud< CloudType >::writeObjects(), and ReactingHeterogeneousCloud< CloudType >::writeObjects().
createIOField() [1/2]
template<class Type > static IOField< Type > & createIOField (const word & fieldName, const label nParticle, objectRegistry & obr) static
findIOField()
template<class Type > static const IOField< Type > * findIOField (const word & fieldName, const objectRegistry & obr) inline static
Definition at line 137 of file cloud.H.
References objectRegistry::cfindObject().
findIOPosition()
static const IOField< point > * findIOPosition (const objectRegistry & obr) inline static
Definition at line 148 of file cloud.H.
References objectRegistry::cfindObject().
Referenced by parcelSelection::calculateFilter(), and particle< Type >::readObjects().
lookupIOField()
template<class Type > static const IOField< Type > & lookupIOField (const word & fieldName, const objectRegistry & obr) inline static
Definition at line 159 of file cloud.H.
References objectRegistry::lookupObject().
createIOField() [2/2]
template<class Type > Foam::IOField< Type > & createIOField (const word & fieldName, const label nParticle, objectRegistry & obr)
Definition at line 26 of file cloudTemplates.C.
References IOobjectOption::AUTO_WRITE, IOobjectOption::NO_READ, IOobjectOption::REGISTER, and objectRegistry::time().
Member Data Documentation
geometryTypeNames
const Foam::Enum< Foam::cloud::geometryType > geometryTypeNames static
Definition at line 76 of file cloud.H.
prefix
const Foam::word prefix static
Definition at line 83 of file cloud.H.
Referenced by lagrangianFieldDecomposer::decomposeField(), lagrangianFieldDecomposer::decomposeFieldField(), CloudSubModelBase< CloudType >::localPath(), Foam::MapLagrangianFields(), Foam::MapLagrangianFields(), ensightCase::newCloud(), lagrangianReconstructor::reconstructField(), lagrangianReconstructor::reconstructFieldField(), Foam::reconstructLagrangian(), particleDistribution::write(), ensightCase::write(), and molecule::writeFields().
defaultName
Foam::word defaultName static
Definition at line 86 of file cloud.H.
Referenced by nearWallFields::calcAddressing(), dataCloud::read(), and vtkCloud::read().
The documentation for this class was generated from the following files:
src/OpenFOAM/fields/cloud/cloud.H
src/OpenFOAM/fields/cloud/cloud.C
src/OpenFOAM/fields/cloud/cloudTemplates.C