OpenFOAM: cyclicGAMGInterface Class Reference
cyclicGAMGInterface Class Reference
GAMG agglomerated cyclic interface.
#include <cyclicGAMGInterface.H>
Public Member Functions
TypeName ("cyclic")
cyclicGAMGInterface (const label index, const lduInterfacePtrsList &coarseInterfaces, const lduInterface &fineInterface, const labelField &restrictAddressing, const labelField &neighbourRestrictAddressing, const label fineLevelIndex, const label coarseComm)
cyclicGAMGInterface (const label index, const lduInterfacePtrsList &coarseInterfaces, Istream &is)
virtual ~cyclicGAMGInterface ()=default
virtual tmp< labelField > internalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &iF) const
virtual label neighbPatchID () const
virtual bool owner () const
virtual const cyclicGAMGInterface & neighbPatch () const
virtual const tensorField & forwardT () const
virtual const tensorField & reverseT () const
virtual void write (Ostream &os) const
Public Member Functions inherited from GAMGInterface
TypeName ("GAMGInterface")
declareRunTimeSelectionTable (autoPtr, GAMGInterface, lduInterface,(const label index, const lduInterfacePtrsList &coarseInterfaces, const lduInterface &fineInterface, const labelField &localRestrictAddressing, const labelField &neighbourRestrictAddressing, const label fineLevelIndex, const label coarseComm),(index, coarseInterfaces, fineInterface, localRestrictAddressing, neighbourRestrictAddressing, fineLevelIndex, coarseComm))
declareRunTimeSelectionTable (autoPtr, GAMGInterface, Istream,(const label index, const lduInterfacePtrsList &coarseInterfaces, Istream &is),(index, coarseInterfaces, is))
GAMGInterface (const label index, const lduInterfacePtrsList &coarseInterfaces)
GAMGInterface (const label index, const lduInterfacePtrsList &coarseInterfaces, const labelUList &faceCells, const labelUList &faceRestrictAddressing)
GAMGInterface (const label index, const lduInterfacePtrsList &coarseInterfaces, Istream &is)
virtual label size () const
virtual label index () const
virtual const lduInterfacePtrsList & coarseInterfaces () const
virtual const labelUList & faceCells () const
virtual const labelList & faceRestrictAddressing () const
virtual labelList & faceRestrictAddressing ()
template<class Type >
tmp< Field< Type > > interfaceInternalField (const UList< Type > &internalData) const
template<class Type >
tmp< Field< Type > > interfaceInternalField (const UList< Type > &internalData, const labelUList &faceCells) const
template<class Type >
void interfaceInternalField (const UList< Type > &internalData, List< Type > &) const
virtual tmp< labelField > interfaceInternalField (const labelUList &internalData) const
virtual tmp< labelField > interfaceInternalField (const labelUList &internalData, const labelUList &faceCells) const
void combine (const GAMGInterface &)
virtual tmp< scalarField > agglomerateCoeffs (const scalarField &fineCoeffs) const
template<class Type >
Foam::tmp< Foam::Field< Type > > interfaceInternalField (const UList< Type > &iF) const
template<class Type >
Foam::tmp< Foam::Field< Type > > interfaceInternalField (const UList< Type > &iF, const labelUList &faceCells) const
Public Member Functions inherited from lduInterface
TypeNameNoDebug ("lduInterface")
lduInterface () noexcept=default
virtual ~lduInterface ()=default
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &iF) const
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &iF, const labelUList &faceCells) const
Public Member Functions inherited from cyclicLduInterface
TypeNameNoDebug ("cyclicLduInterface")
cyclicLduInterface () noexcept=default
virtual ~cyclicLduInterface ()=default
Additional Inherited Members
Static Public Member Functions inherited from GAMGInterface
static autoPtr< GAMGInterface > New (const label index, const lduInterfacePtrsList &coarseInterfaces, const lduInterface &fineInterface, const labelField &localRestrictAddressing, const labelField &neighbourRestrictAddressing, const label fineLevelIndex, const label coarseComm)
static autoPtr< GAMGInterface > New (const word &coupleType, const label index, const lduInterfacePtrsList &coarseInterfaces, Istream &is)
Protected Member Functions inherited from GAMGInterface
GAMGInterface (const GAMGInterface &)=delete
void operator= (const GAMGInterface &)=delete
Protected Attributes inherited from GAMGInterface
const label index_
const lduInterfacePtrsList & coarseInterfaces_
labelList faceCells_
labelList faceRestrictAddressing_
Detailed Description
GAMG agglomerated cyclic interface.
Source files
cyclicGAMGInterface.H
cyclicGAMGInterface.C
Definition at line 48 of file cyclicGAMGInterface.H.
Constructor & Destructor Documentation
cyclicGAMGInterface() [1/2]
cyclicGAMGInterface (const label index, const lduInterfacePtrsList & coarseInterfaces, const lduInterface & fineInterface, const labelField & restrictAddressing, const labelField & neighbourRestrictAddressing, const label fineLevelIndex, const label coarseComm)
Definition at line 65 of file cyclicGAMGInterface.C.
References PtrList< T >::append(), GAMGInterface::faceCells_, GAMGInterface::faceRestrictAddressing_, forAll, cyclicGAMGInterface::owner(), Foam::refCast(), UPtrList< T >::size(), and List< T >::transfer().
cyclicGAMGInterface() [2/2]
cyclicGAMGInterface (const label index, const lduInterfacePtrsList & coarseInterfaces, Istream & is)
Definition at line 143 of file cyclicGAMGInterface.C.
~cyclicGAMGInterface()
virtual ~cyclicGAMGInterface () virtual default
Member Function Documentation
TypeName()
TypeName ("cyclic")
internalFieldTransfer()
Foam::tmp< Foam::labelField > internalFieldTransfer (const Pstream::commsTypes commsType, const labelUList & iF) const virtual
Implements lduInterface.
Definition at line 160 of file cyclicGAMGInterface.C.
References forAll, and tmp< T >::New().
neighbPatchID()
virtual label neighbPatchID () const inline virtual
Implements cyclicLduInterface.
Definition at line 126 of file cyclicGAMGInterface.H.
Referenced by cyclicGAMGInterface::neighbPatch().
owner()
virtual bool owner () const inline virtual
Implements cyclicLduInterface.
Definition at line 131 of file cyclicGAMGInterface.H.
Referenced by cyclicGAMGInterface::cyclicGAMGInterface().
neighbPatch()
virtual const cyclicGAMGInterface & neighbPatch () const inline virtual
Implements cyclicLduInterface.
Definition at line 136 of file cyclicGAMGInterface.H.
References GAMGInterface::coarseInterfaces_, and cyclicGAMGInterface::neighbPatchID().
forwardT()
virtual const tensorField & forwardT () const inline virtual
Implements cyclicLduInterface.
Definition at line 145 of file cyclicGAMGInterface.H.
Referenced by cyclicGAMGInterfaceField::forwardT().
reverseT()
virtual const tensorField & reverseT () const inline virtual
Implements cyclicLduInterface.
Definition at line 151 of file cyclicGAMGInterface.H.
Referenced by cyclicGAMGInterfaceField::reverseT().
write()
void write (Ostream & os) const virtual
Implements GAMGInterface.
Definition at line 181 of file cyclicGAMGInterface.C.
References os(), token::SPACE, and GAMGInterface::write().
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/interfaces/cyclicGAMGInterface/cyclicGAMGInterface.H
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/interfaces/cyclicGAMGInterface/cyclicGAMGInterface.C