OpenFOAM: CoulaloglouTavlaridesCoalescence Class Reference
CoulaloglouTavlaridesCoalescence Class Reference
Model of Coulaloglou and Tavlarides (1977). The coalescence rate is calculated by.
#include <CoulaloglouTavlaridesCoalescence.H>
Public Member Functions
TypeName ("CoulaloglouTavlarides")
CoulaloglouTavlaridesCoalescence (const populationBalanceModel &popBal, const dictionary &dict)
virtual ~CoulaloglouTavlaridesCoalescence ()=default
virtual void addToCoalescenceRate (volScalarField &coalescenceRate, const label i, const label j)
Public Member Functions inherited from coalescenceModel
TypeName ("coalescenceModel")
declareRunTimeSelectionTable (autoPtr, coalescenceModel, dictionary,(const populationBalanceModel &popBal, const dictionary &dict),(popBal, dict))
coalescenceModel (const populationBalanceModel &popBal, const dictionary &dict)
autoPtr< coalescenceModel > clone () const
virtual ~coalescenceModel ()=default
virtual void correct ()
Additional Inherited Members
Static Public Member Functions inherited from coalescenceModel
static autoPtr< coalescenceModel > New (const word &type, const populationBalanceModel &popBal, const dictionary &dict)
Protected Attributes inherited from coalescenceModel
const populationBalanceModel & popBal_
Detailed Description
Model of Coulaloglou and Tavlarides (1977). The coalescence rate is calculated by.
where
= Surface tension [N/m]
= Volume of droplet i [m3]
= Volume of droplet j [m3]
= Turbulent dissipation rate of continuous phase [m2/s3]
= Total void fraction of disperse phase [-]
= Molecular dynamic viscosity of liquid phase [Pa s]
= Density of continuous phase [kg/m3]
References:
        Coulaloglou, C. A., & Tavlarides, L. L. (1977).
        Description of interaction processes in agitated liquid-liquid
        dispersions.
        Chemical Engineering Science, 32(11), 1289-1297.
        Eq. 37, p. 1294.
Usage
Property Description Required Default value
C1 Coefficient C1 no 2.8
C2 Coefficient C2 no 1.83e9
Source files
CoulaloglouTavlaridesCoalescence.H
CoulaloglouTavlaridesCoalescence.C
Definition at line 135 of file CoulaloglouTavlaridesCoalescence.H.
Constructor & Destructor Documentation
CoulaloglouTavlaridesCoalescence()
CoulaloglouTavlaridesCoalescence (const populationBalanceModel & popBal, const dictionary & dict)
Definition at line 48 of file CoulaloglouTavlaridesCoalescence.C.
References Foam::dimArea, Foam::dimless, and Foam::inv().
~CoulaloglouTavlaridesCoalescence()
virtual ~CoulaloglouTavlaridesCoalescence () virtual default
Member Function Documentation
TypeName()
TypeName ("CoulaloglouTavlarides")
addToCoalescenceRate()
void addToCoalescenceRate (volScalarField & coalescenceRate, const label i, const label j) virtual
Implements coalescenceModel.
Definition at line 64 of file CoulaloglouTavlaridesCoalescence.C.
References Foam::cbrt(), Foam::exp(), phaseModel::mu(), Foam::pow(), Foam::pow3(), Foam::pow4(), phaseModel::rho(), Foam::sqr(), and Foam::sqrt().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/populationBalanceModel/coalescenceModels/CoulaloglouTavlaridesCoalescence/CoulaloglouTavlaridesCoalescence.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/populationBalanceModel/coalescenceModels/CoulaloglouTavlaridesCoalescence/CoulaloglouTavlaridesCoalescence.C