OpenFOAM: solidChemistryModel< CompType, SolidThermo > Class Template Reference
solidChemistryModel< CompType, SolidThermo > Class Template Reference abstract
Extends base solid chemistry model by adding a thermo package, and ODE functions.
#include <solidChemistryModel.H>
Public Member Functions
TypeName ("solidChemistryModel")
solidChemistryModel (typename CompType::reactionThermo &thermo)
virtual ~solidChemistryModel ()
const PtrList< Reaction< SolidThermo > > & reactions () const
label nReaction () const
virtual scalarField omega (const scalarField &c, const scalar T, const scalar p, const bool updateC0=false) const =0
virtual scalar omega (const Reaction< SolidThermo > &r, const scalarField &c, const scalar T, const scalar p, scalar &pf, scalar &cf, label &lRef, scalar &pr, scalar &cr, label &rRef) const =0
virtual scalar omegaI (label iReaction, const scalarField &c, const scalar T, const scalar p, scalar &pf, scalar &cf, label &lRef, scalar &pr, scalar &cr, label &rRef) const =0
virtual void calculate ()=0
const volScalarField::Internal & RRs (const label i) const
tmp< volScalarField::Internal > RRs () const
tmp< DimensionedField< scalar, volMesh > > RRsHs () const
virtual scalar solve (const scalar deltaT)=0
virtual scalar solve (const scalarField &deltaT)
virtual tmp< volScalarField > tc () const
virtual tmp< volScalarField > Qdot () const
virtual label nEqns () const =0
virtual void derivatives (const scalar t, const scalarField &c, scalarField &dcdt) const =0
virtual void jacobian (const scalar t, const scalarField &c, scalarField &dcdt, scalarSquareMatrix &dfdc) const =0
virtual void solve (scalarField &c, scalar &T, scalar &p, scalar &deltaT, scalar &subDeltaT) const =0
Public Member Functions inherited from ODESystem
ODESystem ()
virtual ~ODESystem ()=default
Protected Member Functions
PtrList< volScalarField::Internal > & RRs ()
void setCellReacting (const label celli, const bool active)
Protected Attributes
PtrList< volScalarField > & Ys_
const PtrList< Reaction< SolidThermo > > & reactions_
const PtrList< SolidThermo > & solidThermo_
label nSolids_
label nReaction_
PtrList< volScalarField::Internal > RRs_
List< bool > reactingCells_
Detailed Description
template<class CompType, class SolidThermo>
class Foam::solidChemistryModel< CompType, SolidThermo >
Extends base solid chemistry model by adding a thermo package, and ODE functions.
Introduces chemistry equation system and evaluation of chemical source terms.
Source files
solidChemistryModel.H
solidChemistryModelI.H
solidChemistryModel.C
Definition at line 59 of file solidChemistryModel.H.
Constructor & Destructor Documentation
solidChemistryModel()
template<class CompType , class SolidThermo > solidChemistryModel (typename CompType::reactionThermo & thermo)
Definition at line 27 of file solidChemistryModel.C.
References Foam::dimMass, Foam::dimTime, Foam::dimVolume, forAll, mesh, Foam::name(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, solidChemistryModel< CompType, SolidThermo >::RRs_, PtrList< T >::set(), timeName, solidChemistryModel< CompType, SolidThermo >::Ys_, and Foam::Zero.
~solidChemistryModel()
template<class CompType , class SolidThermo > ~solidChemistryModel () virtual
Definition at line 81 of file solidChemistryModel.C.
Member Function Documentation
RRs() [1/3]
template<class CompType , class SolidThermo > Foam::PtrList< Foam::DimensionedField< Foam::scalar, Foam::volMesh > > & RRs () inline protected
Definition at line 28 of file solidChemistryModelI.H.
setCellReacting()
template<class CompType , class SolidThermo > void setCellReacting (const label celli, const bool active) protected
Definition at line 149 of file solidChemistryModel.C.
TypeName()
template<class CompType , class SolidThermo > TypeName ("solidChemistryModel< CompType, SolidThermo >")
reactions()
template<class CompType , class SolidThermo > const Foam::PtrList< Foam::Reaction< SolidThermo > > & reactions () const inline
Definition at line 36 of file solidChemistryModelI.H.
nReaction()
template<class CompType , class SolidThermo > Foam::label nReaction () const inline
Definition at line 44 of file solidChemistryModelI.H.
omega() [1/2]
template<class CompType , class SolidThermo > virtual scalarField omega (const scalarField & c, const scalar T, const scalar p, const bool updateC0 = false) const pure virtual
Implemented in pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >.
omega() [2/2]
template<class CompType , class SolidThermo > virtual scalar omega (const Reaction< SolidThermo > & r, const scalarField & c, const scalar T, const scalar p, scalar & pf, scalar & cf, label & lRef, scalar & pr, scalar & cr, label & rRef) const pure virtual
Implemented in pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >.
omegaI()
template<class CompType , class SolidThermo > virtual scalar omegaI (label iReaction, const scalarField & c, const scalar T, const scalar p, scalar & pf, scalar & cf, label & lRef, scalar & pr, scalar & cr, label & rRef) const pure virtual
Implemented in pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >.
calculate()
template<class CompType , class SolidThermo > virtual void calculate () pure virtual
Implemented in pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >.
RRs() [2/3]
template<class CompType , class SolidThermo > const Foam::DimensionedField< Foam::scalar, Foam::volMesh > & RRs (const label i) const inline
Definition at line 53 of file solidChemistryModelI.H.
RRs() [3/3]
template<class CompType , class SolidThermo > Foam::tmp< Foam::DimensionedField< Foam::scalar, Foam::volMesh > > RRs () const inline
Definition at line 64 of file solidChemistryModelI.H.
References Foam::dimMass, Foam::dimTime, Foam::dimVolume, mesh, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, timeName, and Foam::Zero.
RRsHs()
template<class CompType , class SolidThermo > Foam::tmp< Foam::DimensionedField< Foam::scalar, Foam::volMesh > > RRsHs () const inline
Definition at line 97 of file solidChemistryModelI.H.
References Foam::dimEnergy, Foam::dimTime, Foam::dimVolume, forAll, mesh, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, p, basicThermo::p(), T, basicThermo::T(), timeName, and Foam::Zero.
solve() [1/3]
template<class CompType , class SolidThermo > virtual scalar solve (const scalar deltaT) pure virtual
Implemented in pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >.
solve() [2/3]
template<class CompType , class SolidThermo > Foam::scalar solve (const scalarField & deltaT) virtual
Definition at line 89 of file solidChemistryModel.C.
References NotImplemented.
tc()
template<class CompType , class SolidThermo > Foam::tmp< Foam::volScalarField > tc () const virtual
Definition at line 101 of file solidChemistryModel.C.
References NotImplemented, and GeometricField< scalar, fvPatchField, volMesh >::null().
Qdot()
template<class CompType , class SolidThermo > Foam::tmp< Foam::volScalarField > Qdot () const virtual
Definition at line 110 of file solidChemistryModel.C.
References IOobjectOption::AUTO_WRITE, Foam::dimEnergy, Foam::dimTime, Foam::dimVolume, forAll, IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, Qdot, and Foam::Zero.
nEqns()
template<class CompType , class SolidThermo > virtual label nEqns () const pure virtual
Implements ODESystem.
Implemented in pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >.
derivatives()
template<class CompType , class SolidThermo > virtual void derivatives (const scalar t, const scalarField & c, scalarField & dcdt) const pure virtual
Implements ODESystem.
Implemented in pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >.
jacobian()
template<class CompType , class SolidThermo > virtual void jacobian (const scalar t, const scalarField & c, scalarField & dcdt, scalarSquareMatrix & dfdc) const pure virtual
Implements ODESystem.
Implemented in pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >.
solve() [3/3]
template<class CompType , class SolidThermo > virtual void solve (scalarField & c, scalar & T, scalar & p, scalar & deltaT, scalar & subDeltaT) const pure virtual
Implemented in pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >.
Member Data Documentation
Ys_
template<class CompType , class SolidThermo > PtrList<volScalarField>& Ys_ protected
Definition at line 76 of file solidChemistryModel.H.
Referenced by pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::pyrolysisChemistryModel(), and solidChemistryModel< CompType, SolidThermo >::solidChemistryModel().
reactions_
template<class CompType , class SolidThermo > const PtrList<Reaction<SolidThermo> >& reactions_ protected
Definition at line 79 of file solidChemistryModel.H.
Referenced by pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::pyrolysisChemistryModel().
solidThermo_
template<class CompType , class SolidThermo > const PtrList<SolidThermo>& solidThermo_ protected
Definition at line 82 of file solidChemistryModel.H.
nSolids_
template<class CompType , class SolidThermo > label nSolids_ protected
Definition at line 85 of file solidChemistryModel.H.
Referenced by pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::pyrolysisChemistryModel().
nReaction_
template<class CompType , class SolidThermo > label nReaction_ protected
Definition at line 88 of file solidChemistryModel.H.
RRs_
template<class CompType , class SolidThermo > PtrList<volScalarField::Internal> RRs_ protected
Definition at line 91 of file solidChemistryModel.H.
Referenced by pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::pyrolysisChemistryModel(), and solidChemistryModel< CompType, SolidThermo >::solidChemistryModel().
reactingCells_
template<class CompType , class SolidThermo > List<bool> reactingCells_ protected
Definition at line 94 of file solidChemistryModel.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/solidChemistryModel/solidChemistryModel/solidChemistryModel.H
src/thermophysicalModels/solidChemistryModel/solidChemistryModel/solidChemistryModel.C
src/thermophysicalModels/solidChemistryModel/solidChemistryModel/solidChemistryModelI.H