OpenFOAM: messageStream Class Reference
messageStream Class Reference
Handle output messages in a simple, consistent stream-based manner.
#include <messageStream.H>
Public Types
enum errorSeverity {
INFO = 1 , INFO_STDERR , WARNING , SERIOUS ,
FATAL
}
Public Member Functions
messageStream (const string &title, const errorSeverity severity, const int maxErrors=0)
messageStream (const dictionary &dict)
const string & title () const noexcept
int maxErrors () const noexcept
int maxErrors (int nErrors) noexcept
OSstream & stream (OSstream *alternative=nullptr)
OSstream & masterStream (const label communicator)
std::ostream & stdStream ()
OSstream & deprecated (const int afterVersion, const char *functionName, const char *sourceFileName, const int sourceFileLineNumber=0)
operator OSstream & ()
OSstream & operator() ()
OSstream & operator() (const std::string &functionName)
OSstream & operator() (const char *functionName, const char *sourceFileName, const int sourceFileLineNumber=0)
OSstream & operator() (const std::string &functionName, const char *sourceFileName, const int sourceFileLineNumber=0)
OSstream & operator() (const char *functionName, const char *sourceFileName, const int sourceFileLineNumber, const std::string &ioFileName, const label ioStartLineNumber=-1, const label ioEndLineNumber=-1)
OSstream & operator() (const char *functionName, const char *sourceFileName, const int sourceFileLineNumber, const IOstream &)
OSstream & operator() (const char *functionName, const char *sourceFileName, const int sourceFileLineNumber, const dictionary &)
Static Public Attributes
static int level
static int redirect
Protected Attributes
string title_
errorSeverity severity_
int maxErrors_
int errorCount_
Detailed Description
Handle output messages in a simple, consistent stream-based manner.
The messageStream class is globally instantiated with a title string and a severity (which controls the program termination), optionally with a max number of errors before termination.
Errors, messages and other data are sent to the messageStream class in the standard manner.
For parallel applications, the output for 'standard' messages (Info, Warnings) is effectively suppressed on all sub-processes, which results in a single output message instead of a flood of output messages from each process. The error type of messages do, however, retain output on all processes, which ensures that parallel termination occurs correctly and the source of the problem is properly traceable to the originating processor.
Source files
messageStream.H
messageStream.C
Definition at line 70 of file messageStream.H.
Member Enumeration Documentation
errorSeverity
enum errorSeverity
Enumerator
INFO
General information output (stdout)
INFO_STDERR
General information output (stderr)
WARNING
Warning of possible problem.
SERIOUS
A serious problem - eg, data corruption.
FATAL
A fatal error.
Definition at line 75 of file messageStream.H.
Constructor & Destructor Documentation
messageStream() [1/2]
messageStream (const string & title, const errorSeverity severity, const int maxErrors = 0)
Definition at line 43 of file messageStream.C.
messageStream() [2/2]
messageStream (const dictionary & dict) explicit
Definition at line 57 of file messageStream.C.
Member Function Documentation
title()
const string & title () const inline noexcept
Definition at line 134 of file messageStream.H.
References messageStream::title_.
maxErrors() [1/2]
int maxErrors () const inline noexcept
Definition at line 140 of file messageStream.H.
References messageStream::maxErrors_.
maxErrors() [2/2]
int maxErrors (int nErrors) inline noexcept
Definition at line 147 of file messageStream.H.
References messageStream::maxErrors_.
stream()
Foam::OSstream & stream (OSstream * alternative = nullptr)
Definition at line 68 of file messageStream.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, Foam::infoDetailLevel, UPstream::master(), UPstream::parRun(), Foam::Perr, Foam::Pout, Foam::Serr, Foam::Snull, and Foam::Sout.
Referenced by objectRegistry::checkCacheTemporaryObjects(), messageStream::operator OSstream &(), messageStream::operator()(), and GAMGAgglomeration::printLevels().
masterStream()
Foam::OSstream & masterStream (const label communicator)
Definition at line 137 of file messageStream.C.
References Foam::endl(), UPstream::master(), Foam::Pout, error::printStack(), Foam::Snull, UPstream::warnComm, and UPstream::worldComm.
Referenced by viewFactor::calculate(), fvMatrix< Type >::fvSolver::solve(), GAMGSolver::solve(), smoothSolver::solve(), fvMatrix< Type >::solveCoupled(), fvMatrix< Type >::solver(), fvMatrix< Type >::solveSegregated(), fvMatrix< Type >::solveSegregated(), and fvMatrix< Type >::solveSegregatedOrCoupled().
stdStream()
std::ostream & stdStream ()
Definition at line 154 of file messageStream.C.
References OFstream::stdStream().
Referenced by argList::argList(), argList::parse(), Foam::printTimingDetail(), and argList::printUsage().
deprecated()
Foam::OSstream & deprecated (const int afterVersion, const char * functionName, const char * sourceFileName, const int sourceFileLineNumber = 0)
Definition at line 179 of file messageStream.C.
References Foam::foamVersion::api, Foam::nl, and os().
operator OSstream &()
operator OSstream & () inline
Definition at line 181 of file messageStream.H.
References messageStream::stream().
operator()() [1/7]
OSstream & operator() () inline
Definition at line 187 of file messageStream.H.
References messageStream::stream().
operator()() [2/7]
Foam::OSstream & operator() (const std::string & functionName)
Definition at line 162 of file messageStream.C.
References Foam::nl, and os().
operator()() [3/7]
Foam::OSstream & operator() (const char * functionName, const char * sourceFileName, const int sourceFileLineNumber = 0)
Definition at line 230 of file messageStream.C.
References Foam::nl, and os().
operator()() [4/7]
Foam::OSstream & operator() (const std::string & functionName, const char * sourceFileName, const int sourceFileLineNumber = 0)
Definition at line 249 of file messageStream.C.
operator()() [5/7]
Foam::OSstream & operator() (const char * functionName, const char * sourceFileName, const int sourceFileLineNumber, const std::string & ioFileName, const label ioStartLineNumber = -1, const label ioEndLineNumber = -1)
Definition at line 265 of file messageStream.C.
References Foam::endl(), Foam::nl, and os().
operator()() [6/7]
Foam::OSstream & operator() (const char * functionName, const char * sourceFileName, const int sourceFileLineNumber, const IOstream & ioStream)
Parameters
ioStream Provides name and lineNumber
Definition at line 299 of file messageStream.C.
operator()() [7/7]
Foam::OSstream & operator() (const char * functionName, const char * sourceFileName, const int sourceFileLineNumber, const dictionary & dict)
Parameters
dict Provides name, startLine, endLine
Definition at line 319 of file messageStream.C.
References dict, dictionary::endLineNumber(), dictionary::relativeName(), and dictionary::startLineNumber().
Member Data Documentation
title_
string title_ protected
Definition at line 92 of file messageStream.H.
Referenced by messageStream::title().
severity_
errorSeverity severity_ protected
Definition at line 93 of file messageStream.H.
maxErrors_
int maxErrors_ protected
Definition at line 94 of file messageStream.H.
Referenced by messageStream::maxErrors(), and messageStream::maxErrors().
errorCount_
int errorCount_ protected
Definition at line 95 of file messageStream.H.
level
int level static
Definition at line 109 of file messageStream.H.
Referenced by IOobject::setBad(), error::write(), and IOerror::write().
redirect
int redirect static
Definition at line 114 of file messageStream.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/db/error/messageStream.H
src/OpenFOAM/db/error/messageStream.C