OpenFOAM: phaseProperties Class Reference
phaseProperties Class Reference
Helper class to manage multi-specie phase properties.
#include <phaseProperties.H>
Public Types
enum phaseType { GAS , LIQUID , SOLID , UNKNOWN }
Public Member Functions
phaseProperties ()
phaseProperties (Istream &is)
void reorder (const wordList &gasNames, const wordList &liquidNames, const wordList &solidNames)
phaseType phase () const
const word & stateLabel () const
word phaseTypeName () const
const List< word > & names () const
const word & name (const label speciei) const
const scalarField & Y () const
scalar & Y (const label speciei)
const labelList & carrierIds () const
label id (const word &specieName) const
Static Public Attributes
static const Enum< phaseType > phaseTypeNames
Friends
Istream & operator>> (Istream &, phaseProperties &)
Ostream & operator<< (Ostream &, const phaseProperties &)
Detailed Description
Helper class to manage multi-specie phase properties.
Source files
phaseProperties.H
phaseProperties.C
phasePropertiesIO.C
Definition at line 56 of file phaseProperties.H.
Member Enumeration Documentation
phaseType
enum phaseType
Enumerator
GAS
LIQUID
SOLID
UNKNOWN
Definition at line 63 of file phaseProperties.H.
Constructor & Destructor Documentation
phaseProperties() [1/2]
phaseProperties ()
Definition at line 175 of file phaseProperties.C.
phaseProperties() [2/2]
phaseProperties (Istream & is) explicit
Definition at line 26 of file phasePropertiesIO.C.
Member Function Documentation
reorder()
void reorder (const wordList & gasNames, const wordList & liquidNames, const wordList & solidNames)
Definition at line 187 of file phaseProperties.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::nl, Foam::reorder(), and solidNames().
phase()
Foam::phaseProperties::phaseType phase () const
Definition at line 235 of file phaseProperties.C.
Referenced by CompositionModel< CloudType >::Cp(), CompositionModel< CloudType >::H(), CompositionModel< CloudType >::Hc(), CompositionModel< CloudType >::Hs(), CompositionModel< Foam::ReactingCloud< Foam::DSMCCloud > >::Hs(), and CompositionModel< CloudType >::L().
stateLabel()
const Foam::word & stateLabel () const
Definition at line 241 of file phaseProperties.C.
phaseTypeName()
Foam::word phaseTypeName () const
Definition at line 247 of file phaseProperties.C.
names()
const Foam::List< Foam::word > & names () const
Definition at line 253 of file phaseProperties.C.
name()
const Foam::word & name (const label speciei) const
Definition at line 259 of file phaseProperties.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::nl, and UPtrList< T >::size().
Y() [1/2]
const Foam::scalarField & Y () const
Definition at line 273 of file phaseProperties.C.
Y() [2/2]
Foam::scalar & Y (const label speciei)
Definition at line 279 of file phaseProperties.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::nl, and UPtrList< T >::size().
carrierIds()
const Foam::labelList & carrierIds () const
Definition at line 293 of file phaseProperties.C.
Referenced by CompositionModel< CloudType >::Cp(), CompositionModel< CloudType >::H(), CompositionModel< CloudType >::Hc(), CompositionModel< Foam::ReactingCloud< Foam::DSMCCloud > >::Hc(), and CompositionModel< CloudType >::Hs().
id()
Foam::label id (const word & specieName) const
Definition at line 299 of file phaseProperties.C.
Friends And Related Symbol Documentation
operator>>
Istream & operator>> (Istream & , phaseProperties &) friend
operator<<
Ostream & operator<< (Ostream & , const phaseProperties &) friend
Member Data Documentation
phaseTypeNames
const Foam::Enum< Foam::phaseProperties::phaseType > phaseTypeNames static
Definition at line 72 of file phaseProperties.H.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/phaseProperties/phaseProperties/phaseProperties.H
src/lagrangian/intermediate/phaseProperties/phaseProperties/phaseProperties.C
src/lagrangian/intermediate/phaseProperties/phaseProperties/phasePropertiesIO.C