OpenFOAM: cyclicAMILduInterface Class Reference
cyclicAMILduInterface Class Reference abstract
An abstract base class for cyclic AMI coupled interfaces.
#include <cyclicAMILduInterface.H>
Public Member Functions
TypeNameNoDebug ("cyclicAMILduInterface")
cyclicAMILduInterface () noexcept=default
virtual ~cyclicAMILduInterface ()=default
virtual label neighbPatchID () const =0
virtual bool owner () const =0
virtual const cyclicAMILduInterface & neighbPatch () const =0
virtual const AMIPatchToPatchInterpolation & AMI () const =0
virtual const tensorField & forwardT () const =0
virtual const tensorField & reverseT () const =0
Detailed Description
An abstract base class for cyclic AMI coupled interfaces.
Source files
cyclicAMILduInterface.H
cyclicAMILduInterface.C
Definition at line 48 of file cyclicAMILduInterface.H.
Constructor & Destructor Documentation
cyclicAMILduInterface()
cyclicAMILduInterface () default noexcept
~cyclicAMILduInterface()
virtual ~cyclicAMILduInterface () virtual default
Member Function Documentation
TypeNameNoDebug()
TypeNameNoDebug ("cyclicAMILduInterface")
neighbPatchID()
virtual label neighbPatchID () const pure virtual
Implemented in cyclicACMIFvPatch, cyclicAMIFvPatch, cyclicACMIGAMGInterface, and cyclicAMIGAMGInterface.
Referenced by cyclicACMIGAMGInterface::neighbPatchID(), and cyclicAMIGAMGInterface::neighbPatchID().
owner()
virtual bool owner () const pure virtual
Implemented in cyclicACMIFvPatch, cyclicAMIFvPatch, cyclicACMIGAMGInterface, and cyclicAMIGAMGInterface.
Referenced by cyclicACMIGAMGInterface::owner(), and cyclicAMIGAMGInterface::owner().
neighbPatch()
virtual const cyclicAMILduInterface & neighbPatch () const pure virtual
Implemented in cyclicACMIFvPatch, cyclicAMIFvPatch, cyclicACMIGAMGInterface, and cyclicAMIGAMGInterface.
AMI()
virtual const AMIPatchToPatchInterpolation & AMI () const pure virtual
Implemented in cyclicACMIFvPatch, cyclicAMIFvPatch, cyclicACMIGAMGInterface, and cyclicAMIGAMGInterface.
forwardT()
virtual const tensorField & forwardT () const pure virtual
Implemented in cyclicACMIFvPatch, cyclicAMIFvPatch, cyclicACMIGAMGInterface, and cyclicAMIGAMGInterface.
Referenced by cyclicACMIGAMGInterface::forwardT(), and cyclicAMIGAMGInterface::forwardT().
reverseT()
virtual const tensorField & reverseT () const pure virtual
Implemented in cyclicACMIFvPatch, cyclicAMIFvPatch, cyclicACMIGAMGInterface, and cyclicAMIGAMGInterface.
Referenced by cyclicACMIGAMGInterface::reverseT(), and cyclicAMIGAMGInterface::reverseT().
The documentation for this class was generated from the following file:
src/meshTools/AMIInterpolation/patches/cyclicAMI/cyclicAMILduInterfaceField/cyclicAMILduInterface.H