OpenFOAM: CrankNicolsonDdtScheme< Type > Class Template Reference
CrankNicolsonDdtScheme< Type > Class Template Reference
Numerics » Finite volume numerical schemes » Time schemes
Second-oder Crank-Nicolson implicit ddt using the current and previous time-step fields as well as the previous time-step ddt.
#include <CrankNicolsonDdtScheme.H>
Public Types
typedef ddtScheme< Type >::fluxFieldType fluxFieldType
Public Types inherited from ddtScheme< Type >
typedef GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > fluxFieldType
Public Member Functions
TypeName ("CrankNicolson")
CrankNicolsonDdtScheme (const fvMesh &mesh)
CrankNicolsonDdtScheme (const fvMesh &mesh, Istream &is)
const fvMesh & mesh () const
scalar ocCoeff () const
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const dimensioned< Type > &)
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const GeometricField< Type, fvPatchField, volMesh > &)
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const dimensionedScalar &, const GeometricField< Type, fvPatchField, volMesh > &)
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const volScalarField &, const GeometricField< Type, fvPatchField, volMesh > &)
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const volScalarField &alpha, const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &psi)
tmp< fvMatrix< Type > > fvmDdt (const GeometricField< Type, fvPatchField, volMesh > &)
tmp< fvMatrix< Type > > fvmDdt (const dimensionedScalar &, const GeometricField< Type, fvPatchField, volMesh > &)
tmp< fvMatrix< Type > > fvmDdt (const volScalarField &, const GeometricField< Type, fvPatchField, volMesh > &)
tmp< fvMatrix< Type > > fvmDdt (const volScalarField &alpha, const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &psi)
tmp< fluxFieldType > fvcDdtUfCorr (const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< Type, fvsPatchField, surfaceMesh > &Uf)
tmp< fluxFieldType > fvcDdtPhiCorr (const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi)
tmp< fluxFieldType > fvcDdtUfCorr (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< Type, fvsPatchField, surfaceMesh > &Uf)
tmp< fluxFieldType > fvcDdtPhiCorr (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi)
tmp< surfaceScalarField > meshPhi (const GeometricField< Type, fvPatchField, volMesh > &)
template<class GeoField >
CrankNicolsonDdtScheme< Type >::template DDt0Field< GeoField > & ddt0_ (const word &name, const dimensionSet &dims)
tmp< surfaceScalarField > fvcDdtUfCorr (const GeometricField< scalar, fvPatchField, volMesh > &U, const GeometricField< scalar, fvsPatchField, surfaceMesh > &Uf)
tmp< surfaceScalarField > fvcDdtPhiCorr (const volScalarField &U, const surfaceScalarField &phi)
tmp< surfaceScalarField > fvcDdtUfCorr (const volScalarField &rho, const volScalarField &U, const surfaceScalarField &Uf)
tmp< surfaceScalarField > fvcDdtPhiCorr (const volScalarField &rho, const volScalarField &U, const surfaceScalarField &phi)
Public Member Functions inherited from ddtScheme< Type >
virtual const word & type () const =0
declareRunTimeSelectionTable (tmp, ddtScheme, Istream,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
ddtScheme (const fvMesh &mesh)
ddtScheme (const fvMesh &mesh, Istream &is)
virtual ~ddtScheme ()=default
const fvMesh & mesh () const
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > fvcDdt (const GeometricField< Type, fvsPatchField, surfaceMesh > &)
tmp< surfaceScalarField > fvcDdtPhiCoeff (const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi, const fluxFieldType &phiCorr)
tmp< surfaceScalarField > fvcDdtPhiCoeffExperimental (const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi, const fluxFieldType &phiCorr)
tmp< surfaceScalarField > fvcDdtPhiCoeff (const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi, const fluxFieldType &phiCorr, const volScalarField &rho)
tmp< surfaceScalarField > fvcDdtPhiCoeff (const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi)
tmp< surfaceScalarField > fvcDdtPhiCoeff (const GeometricField< Type, fvPatchField, volMesh > &rhoU, const fluxFieldType &phi, const volScalarField &rho)
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Public Member Functions inherited from ddtSchemeBase
ddtSchemeBase ()
ddtSchemeBase ()
Additional Inherited Members
Static Public Member Functions inherited from ddtScheme< Type >
static tmp< ddtScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Static Public Attributes inherited from ddtSchemeBase
static bool experimentalDdtCorr
Protected Member Functions inherited from ddtScheme< Type >
ddtScheme (const ddtScheme &)=delete
void operator= (const ddtScheme &)=delete
Protected Attributes inherited from ddtScheme< Type >
const fvMesh & mesh_
scalar ddtPhiCoeff_
Detailed Description
template<class Type>
class Foam::fv::CrankNicolsonDdtScheme< Type >
Second-oder Crank-Nicolson implicit ddt using the current and previous time-step fields as well as the previous time-step ddt.
The Crank-Nicolson scheme is often unstable for complex flows in complex geometries and it is necessary to "off-centre" the scheme to stabilize it while retaining greater temporal accuracy than the first-order Euler-implicit scheme. Off-centering is specified via the mandatory coefficient ocCoeff in the range [0,1] following the scheme name e.g.
ddtSchemes
{
    default         CrankNicolson 0.9;
}
or with an optional "ramp" function to transition from the Euler scheme to Crank-Nicolson over a initial period to avoid start-up problems, e.g.
ddtSchemes
{
    default         CrankNicolson
    ocCoeff
    {
        type scale;
        scale linearRamp;
        duration 0.01;
        value 0.9;
    };
}
With a coefficient of 1 the scheme is fully centred and second-order, with a coefficient of 0 the scheme is equivalent to Euler-implicit. A coefficient of 0.9 has been found to be suitable for a range of cases for which higher-order accuracy in time is needed and provides similar accuracy and stability to the backward scheme. However, the backward scheme has been found to be more robust and provides formal second-order accuracy in time.
The advantage of the Crank-Nicolson scheme over backward is that only the new and old-time values are needed, the additional terms relating to the fluxes and sources are evaluated at the mid-point of the time-step which provides the opportunity to limit the fluxes in such a way as to ensure boundedness while maintaining greater accuracy in time compared to the Euler-implicit scheme. This approach is now used with MULES in the interFoam family of solvers. Boundedness cannot be guaranteed with the backward scheme.
Note
The Crank-Nicolson coefficient for the implicit part of the RHS is related to the off-centering coefficient by
    cnCoeff = 1.0/(1.0 + ocCoeff);
See also
Foam::Euler Foam::backward
Source files
CrankNicolsonDdtScheme.H
CrankNicolsonDdtScheme.C
Definition at line 112 of file CrankNicolsonDdtScheme.H.
Member Typedef Documentation
fluxFieldType
template<class Type > typedef ddtScheme<Type>::fluxFieldType fluxFieldType
Definition at line 288 of file CrankNicolsonDdtScheme.H.
Constructor & Destructor Documentation
CrankNicolsonDdtScheme() [1/2]
template<class Type > CrankNicolsonDdtScheme (const fvMesh & mesh)
Definition at line 279 of file CrankNicolsonDdtScheme.C.
References CrankNicolsonDdtScheme< Type >::mesh().
CrankNicolsonDdtScheme() [2/2]
template<class Type > CrankNicolsonDdtScheme (const fvMesh & mesh, Istream & is)
Definition at line 294 of file CrankNicolsonDdtScheme.C.
References dict, Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, CrankNicolsonDdtScheme< Type >::mesh(), and CrankNicolsonDdtScheme< Type >::ocCoeff().
Member Function Documentation
TypeName()
template<class Type > TypeName ("CrankNicolson")
mesh()
template<class Type > const fvMesh & mesh () const inline
Definition at line 224 of file CrankNicolsonDdtScheme.H.
References ddtScheme< Type >::mesh().
Referenced by CrankNicolsonDdtScheme< Type >::CrankNicolsonDdtScheme(), CrankNicolsonDdtScheme< Type >::CrankNicolsonDdtScheme(), and CrankNicolsonDdtScheme< Type >::ocCoeff().
ocCoeff()
template<class Type > scalar ocCoeff () const inline
Definition at line 230 of file CrankNicolsonDdtScheme.H.
References CrankNicolsonDdtScheme< Type >::mesh().
Referenced by CrankNicolsonDdtScheme< Type >::CrankNicolsonDdtScheme().
fvcDdt() [1/5]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const dimensioned< Type > & dt) virtual
Implements ddtScheme< Type >.
Definition at line 340 of file CrankNicolsonDdtScheme.C.
References Foam::dimTime, mesh, timeName, and Foam::Zero.
fvcDdt() [2/5]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 402 of file CrankNicolsonDdtScheme.C.
References Foam::fv::ff(), mesh, and timeName.
fvcDdt() [3/5]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const dimensionedScalar & rho, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 496 of file CrankNicolsonDdtScheme.C.
References Foam::fv::ff(), mesh, rho, and timeName.
fvcDdt() [4/5]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 593 of file CrankNicolsonDdtScheme.C.
References Foam::fv::ff(), mesh, rho, and timeName.
fvcDdt() [5/5]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const volScalarField & alpha, const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & psi) virtual
Implements ddtScheme< Type >.
Definition at line 700 of file CrankNicolsonDdtScheme.C.
References alpha, Foam::fv::ff(), mesh, rho, and timeName.
fvmDdt() [1/4]
template<class Type > tmp< fvMatrix< Type > > fvmDdt (const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 837 of file CrankNicolsonDdtScheme.C.
References Foam::dimTime, Foam::dimVol, Foam::fv::ff(), and mesh.
fvmDdt() [2/4]
template<class Type > tmp< fvMatrix< Type > > fvmDdt (const dimensionedScalar & rho, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 920 of file CrankNicolsonDdtScheme.C.
References Foam::dimTime, Foam::dimVol, Foam::fv::ff(), mesh, and rho.
fvmDdt() [3/4]
template<class Type > tmp< fvMatrix< Type > > fvmDdt (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 1002 of file CrankNicolsonDdtScheme.C.
References Foam::dimTime, Foam::dimVol, Foam::fv::ff(), mesh, and rho.
fvmDdt() [4/4]
template<class Type > tmp< fvMatrix< Type > > fvmDdt (const volScalarField & alpha, const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & psi) virtual
Implements ddtScheme< Type >.
Definition at line 1092 of file CrankNicolsonDdtScheme.C.
References alpha, Foam::dimTime, Foam::dimVol, Foam::fv::ff(), mesh, and rho.
fvcDdtUfCorr() [1/4]
template<class Type > tmp< typename CrankNicolsonDdtScheme< Type >::fluxFieldType > fvcDdtUfCorr (const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< Type, fvsPatchField, surfaceMesh > & Uf) virtual
Implements ddtScheme< Type >.
Definition at line 1203 of file CrankNicolsonDdtScheme.C.
References Foam::fvc::interpolate(), mesh, timeName, U, and Uf.
fvcDdtPhiCorr() [1/4]
template<class Type > tmp< typename CrankNicolsonDdtScheme< Type >::fluxFieldType > fvcDdtPhiCorr (const GeometricField< Type, fvPatchField, volMesh > & U, const fluxFieldType & phi) virtual
Implements ddtScheme< Type >.
Definition at line 1264 of file CrankNicolsonDdtScheme.C.
References Foam::fvc::dotInterpolate(), mesh, phi, timeName, and U.
fvcDdtUfCorr() [2/4]
template<class Type > tmp< typename CrankNicolsonDdtScheme< Type >::fluxFieldType > fvcDdtUfCorr (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< Type, fvsPatchField, surfaceMesh > & Uf) virtual
Implements ddtScheme< Type >.
Definition at line 1327 of file CrankNicolsonDdtScheme.C.
References Foam::abort(), Foam::dimVelocity, Foam::FatalError, FatalErrorInFunction, Foam::fvc::interpolate(), mesh, rho, timeName, U, and Uf.
fvcDdtPhiCorr() [2/4]
template<class Type > tmp< typename CrankNicolsonDdtScheme< Type >::fluxFieldType > fvcDdtPhiCorr (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & U, const fluxFieldType & phi) virtual
Implements ddtScheme< Type >.
Definition at line 1484 of file CrankNicolsonDdtScheme.C.
References Foam::abort(), Foam::dimArea, Foam::dimVelocity, Foam::fvc::dotInterpolate(), Foam::FatalError, FatalErrorInFunction, mesh, phi, rho, timeName, and U.
meshPhi()
template<class Type > tmp< surfaceScalarField > meshPhi (const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 1629 of file CrankNicolsonDdtScheme.C.
References Foam::dimVolume, mesh, Foam::name(), IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, phi, and timeName.
ddt0_()
template<class Type > template<class GeoField > CrankNicolsonDdtScheme< Type >::template DDt0Field< GeoField > & ddt0_ (const word & name, const dimensionSet & dims)
Definition at line 102 of file CrankNicolsonDdtScheme.C.
References Foam::dimTime, mesh, Foam::name(), runTime, objectRegistry::time(), and timeName.
fvcDdtUfCorr() [3/4]
tmp< surfaceScalarField > fvcDdtUfCorr (const GeometricField< scalar, fvPatchField, volMesh > & U, const GeometricField< scalar, fvsPatchField, surfaceMesh > & Uf)
fvcDdtPhiCorr() [3/4]
tmp< surfaceScalarField > fvcDdtPhiCorr (const volScalarField & U, const surfaceScalarField & phi)
fvcDdtUfCorr() [4/4]
tmp< surfaceScalarField > fvcDdtUfCorr (const volScalarField & rho, const volScalarField & U, const surfaceScalarField & Uf)
fvcDdtPhiCorr() [4/4]
tmp< surfaceScalarField > fvcDdtPhiCorr (const volScalarField & rho, const volScalarField & U, const surfaceScalarField & phi)
The documentation for this class was generated from the following files:
src/finiteVolume/finiteVolume/ddtSchemes/CrankNicolsonDdtScheme/CrankNicolsonDdtScheme.H
src/finiteVolume/finiteVolume/ddtSchemes/CrankNicolsonDdtScheme/CrankNicolsonDdtScheme.C