OpenFOAM: boundaryCutter Class Reference
boundaryCutter Class Reference
Does modifications to boundary faces.
#include <boundaryCutter.H>
Public Member Functions
ClassName ("boundaryCutter")
boundaryCutter (const polyMesh &mesh)
~boundaryCutter ()=default
void setRefinement (const Map< point > &pointToPos, const Map< List< point > > &edgeToCuts, const Map< labelPair > &faceToSplit, const Map< point > &faceToFeaturePoint, polyTopoChange &meshMod)
void updateMesh (const mapPolyMesh &)
const EdgeMap< labelList > & edgeAddedPoints () const
const Map< label > & faceAddedPoint () const
Detailed Description
Does modifications to boundary faces.
Does
move boundary points
split boundary edges (multiple per edge if necessary)
face-centre decomposes boundary faces
diagonal split of boundary faces
Source files
boundaryCutter.H
boundaryCutter.C
Definition at line 64 of file boundaryCutter.H.
Constructor & Destructor Documentation
boundaryCutter()
boundaryCutter (const polyMesh & mesh) explicit
Definition at line 381 of file boundaryCutter.C.
~boundaryCutter()
~boundaryCutter () default
Member Function Documentation
ClassName()
ClassName ("boundaryCutter")
setRefinement()
void setRefinement (const Map< point > & pointToPos, const Map< List< point > > & edgeToCuts, const Map< labelPair > & faceToSplit, const Map< point > & faceToFeaturePoint, polyTopoChange & meshMod)
Definition at line 391 of file boundaryCutter.C.
References Foam::abort(), PtrList< T >::append(), PtrList< T >::clear(), Foam::diag(), e, Foam::endl(), f(), Foam::FatalError, FatalErrorInFunction, UList< T >::find(), forAll, forAllConstIters, face::nextLabel(), patchID, Foam::Pout, PtrList< T >::resize(), polyTopoChange::setAction(), List< T >::setSize(), UPtrList< T >::size(), and UList< T >::size().
updateMesh()
void updateMesh (const mapPolyMesh & morphMap)
Definition at line 818 of file boundaryCutter.C.
References e, UList< T >::end(), forAll, forAllConstIters, newPointi, PtrList< T >::setSize(), UList< T >::size(), and PtrList< T >::transfer().
edgeAddedPoints()
const EdgeMap< labelList > & edgeAddedPoints () const inline
Definition at line 160 of file boundaryCutter.H.
faceAddedPoint()
const Map< label > & faceAddedPoint () const inline
Definition at line 166 of file boundaryCutter.H.
The documentation for this class was generated from the following files:
src/dynamicMesh/meshCut/meshModifiers/boundaryCutter/boundaryCutter.H
src/dynamicMesh/meshCut/meshModifiers/boundaryCutter/boundaryCutter.C