OpenFOAM: mergedSurf Class Reference
mergedSurf Class Reference
Simple class to manage surface merging information.
#include <mergedSurf.H>
Public Member Functions
mergedSurf () noexcept=default
mergedSurf (const mergedSurf &)=default
mergedSurf (mergedSurf &&)=default
mergedSurf & operator= (const mergedSurf &)=default
mergedSurf & operator= (mergedSurf &&)=default
mergedSurf (const meshedSurf &unmergedSurface, const scalar mergeDim)
mergedSurf (const pointField &unmergedPoints, const faceList &unmergedFaces, const scalar mergeDim)
mergedSurf (const pointField &unmergedPoints, const faceList &unmergedFaces, const labelList &origZoneIds, const labelList &origFaceIds, const scalar mergeDim)
virtual ~mergedSurf ()=default
label size () const noexcept
virtual const pointField & points () const noexcept
virtual const faceList & faces () const noexcept
virtual const labelList & zoneIds () const noexcept
virtual const labelList & faceIds () const noexcept
const labelList & pointsMap () const noexcept
const globalIndex & pointGlobalIndex () const noexcept
const globalIndex & faceGlobalIndex () const noexcept
void clear ()
bool merge (const meshedSurf &unmergedSurface, const scalar mergeDim)
bool merge (const pointField &unmergedPoints, const faceList &unmergedFaces, const scalar mergeDim)
bool merge (const pointField &unmergedPoints, const faceList &unmergedFaces, const labelList &origZoneIds, const labelList &origFaceIds, const scalar mergeDim)
Public Member Functions inherited from meshedSurf
constexpr meshedSurf () noexcept=default
virtual ~meshedSurf ()=default
Detailed Description
Simple class to manage surface merging information.
Merging is done with PatchTools::gatherAndMerge()
Source files
mergedSurf.H
mergedSurf.C
Definition at line 50 of file mergedSurf.H.
Constructor & Destructor Documentation
mergedSurf() [1/6]
mergedSurf () default noexcept
mergedSurf() [2/6]
mergedSurf (const mergedSurf &) default
mergedSurf() [3/6]
mergedSurf (mergedSurf &&) default
mergedSurf() [4/6]
mergedSurf (const meshedSurf & unmergedSurface, const scalar mergeDim)
Definition at line 26 of file mergedSurf.C.
References mergedSurf::merge().
mergedSurf() [5/6]
mergedSurf (const pointField & unmergedPoints, const faceList & unmergedFaces, const scalar mergeDim)
Definition at line 36 of file mergedSurf.C.
mergedSurf() [6/6]
mergedSurf (const pointField & unmergedPoints, const faceList & unmergedFaces, const labelList & origZoneIds, const labelList & origFaceIds, const scalar mergeDim)
Definition at line 47 of file mergedSurf.C.
~mergedSurf()
virtual ~mergedSurf () virtual default
Member Function Documentation
operator=() [1/2]
mergedSurf & operator= (const mergedSurf &) default
operator=() [2/2]
mergedSurf & operator= (mergedSurf &&) default
size()
label size () const inline noexcept
Definition at line 125 of file mergedSurf.H.
References UList< T >::size().
points()
virtual const pointField & points () const inline virtual noexcept
Implements meshedSurf.
Definition at line 131 of file mergedSurf.H.
Referenced by debugWriter::mergeField().
faces()
virtual const faceList & faces () const inline virtual noexcept
Implements meshedSurf.
Definition at line 137 of file mergedSurf.H.
zoneIds()
virtual const labelList & zoneIds () const inline virtual noexcept
Reimplemented from meshedSurf.
Definition at line 143 of file mergedSurf.H.
faceIds()
virtual const labelList & faceIds () const inline virtual noexcept
Reimplemented from meshedSurf.
Definition at line 149 of file mergedSurf.H.
pointsMap()
const labelList & pointsMap () const inline noexcept
Definition at line 155 of file mergedSurf.H.
Referenced by debugWriter::mergeField().
pointGlobalIndex()
const globalIndex & pointGlobalIndex () const inline noexcept
Definition at line 161 of file mergedSurf.H.
Referenced by debugWriter::mergeField().
faceGlobalIndex()
const globalIndex & faceGlobalIndex () const inline noexcept
Definition at line 167 of file mergedSurf.H.
Referenced by debugWriter::mergeField().
clear()
void clear ()
Definition at line 69 of file mergedSurf.C.
References PtrList< T >::clear().
merge() [1/3]
bool merge (const meshedSurf & unmergedSurface, const scalar mergeDim)
Definition at line 83 of file mergedSurf.C.
Referenced by mergedSurf::mergedSurf().
merge() [2/3]
bool merge (const pointField & unmergedPoints, const faceList & unmergedFaces, const scalar mergeDim)
Definition at line 101 of file mergedSurf.C.
References List< label >::null().
merge() [3/3]
bool merge (const pointField & unmergedPoints, const faceList & unmergedFaces, const labelList & origZoneIds, const labelList & origFaceIds, const scalar mergeDim)
Definition at line 120 of file mergedSurf.C.
References clear(), PatchTools::gatherAndMerge(), globalIndex::gatherOp(), Foam::notNull(), and UPstream::parRun().
The documentation for this class was generated from the following files:
src/surfMesh/mergedSurf/mergedSurf.H
src/surfMesh/mergedSurf/mergedSurf.C