OpenFOAM: fvsPatchFieldBase Class Reference
fvsPatchFieldBase Class Reference
#include <fvsPatchField.H>
Public Member Functions
TypeName ("fvsPatchField")
fvsPatchFieldBase (const fvPatch &p)
fvsPatchFieldBase (const fvPatch &p, const dictionary &dict)
fvsPatchFieldBase (const fvsPatchFieldBase &rhs, const fvPatch &p)
fvsPatchFieldBase (const fvsPatchFieldBase &rhs)
virtual ~fvsPatchFieldBase ()=default
virtual bool fixesValue () const
virtual bool coupled () const
const objectRegistry & db () const
const fvPatch & patch () const noexcept
bool updated () const noexcept
bool manipulatedMatrix () const noexcept
void checkPatch (const fvsPatchFieldBase &rhs) const
Static Public Member Functions
static const word & emptyType () noexcept
static const word & calculatedType () noexcept
Static Public Attributes
static int disallowGenericPatchField
Protected Member Functions
virtual void readDict (const dictionary &dict)
void setUpdated (bool state) noexcept
void setManipulated (bool state) noexcept
Detailed Description
Definition at line 74 of file fvsPatchField.H.
Constructor & Destructor Documentation
fvsPatchFieldBase() [1/4]
fvsPatchFieldBase (const fvPatch & p) explicit
Definition at line 39 of file fvsPatchFieldBase.C.
fvsPatchFieldBase() [2/4]
fvsPatchFieldBase (const fvPatch & p, const dictionary & dict)
Definition at line 45 of file fvsPatchFieldBase.C.
fvsPatchFieldBase() [3/4]
fvsPatchFieldBase (const fvsPatchFieldBase & rhs, const fvPatch & p)
Definition at line 55 of file fvsPatchFieldBase.C.
fvsPatchFieldBase() [4/4]
fvsPatchFieldBase (const fvsPatchFieldBase & rhs)
Definition at line 65 of file fvsPatchFieldBase.C.
~fvsPatchFieldBase()
virtual ~fvsPatchFieldBase () virtual default
Member Function Documentation
readDict()
void readDict (const dictionary & dict) protected virtual
Definition at line 73 of file fvsPatchFieldBase.C.
Referenced by slicedFvsPatchField< Type >::slicedFvsPatchField().
setUpdated()
void setUpdated (bool state) inline protected noexcept
Definition at line 90 of file fvsPatchField.H.
setManipulated()
void setManipulated (bool state) inline protected noexcept
Definition at line 94 of file fvsPatchField.H.
TypeName()
TypeName ("fvsPatchField")
emptyType()
static const word & emptyType () inline static noexcept
Definition at line 129 of file fvsPatchField.H.
References Foam::fieldTypes::emptyType.
calculatedType()
static const word & calculatedType () inline static noexcept
Definition at line 135 of file fvsPatchField.H.
References Foam::fieldTypes::calculatedType.
Referenced by meshRefinement::appendPatch(), fvFieldDecomposer::decomposeField(), fvMeshSubset::interpolate(), phaseModel::phaseModel(), and phaseModel::phaseModel().
fixesValue()
virtual bool fixesValue () const inline virtual
Reimplemented in calculatedFvsPatchField< Type >, fixedValueFvsPatchField< Type >, and slicedFvsPatchField< Type >.
Definition at line 148 of file fvsPatchField.H.
coupled()
virtual bool coupled () const inline virtual
Reimplemented in coupledFvsPatchField< Type >, cyclicACMIFvsPatchField< Type >, cyclicAMIFvsPatchField< Type >, processorFvsPatchField< Type >, and processorCyclicFvsPatchField< Type >.
Definition at line 154 of file fvsPatchField.H.
db()
const Foam::objectRegistry & db () const
Definition at line 77 of file fvsPatchFieldBase.C.
patch()
const fvPatch & patch () const inline noexcept
Definition at line 166 of file fvsPatchField.H.
Referenced by cyclicACMIFvsPatchField< Type >::cyclicACMIFvsPatchField(), cyclicACMIFvsPatchField< Type >::cyclicACMIFvsPatchField(), cyclicAMIFvsPatchField< Type >::cyclicAMIFvsPatchField(), cyclicAMIFvsPatchField< Type >::cyclicAMIFvsPatchField(), cyclicFvsPatchField< Type >::cyclicFvsPatchField(), cyclicFvsPatchField< Type >::cyclicFvsPatchField(), emptyFvsPatchField< Type >::emptyFvsPatchField(), emptyFvsPatchField< Type >::emptyFvsPatchField(), genericFvsPatchField< Type >::genericFvsPatchField(), genericFvsPatchField< Type >::genericFvsPatchField(), processorCyclicFvsPatchField< Type >::processorCyclicFvsPatchField(), processorCyclicFvsPatchField< Type >::processorCyclicFvsPatchField(), processorFvsPatchField< Type >::processorFvsPatchField(), processorFvsPatchField< Type >::processorFvsPatchField(), fvsPatchField< Type >::readValueEntry(), symmetryFvsPatchField< Type >::symmetryFvsPatchField(), symmetryFvsPatchField< Type >::symmetryFvsPatchField(), symmetryPlaneFvsPatchField< Type >::symmetryPlaneFvsPatchField(), symmetryPlaneFvsPatchField< Type >::symmetryPlaneFvsPatchField(), wedgeFvsPatchField< Type >::wedgeFvsPatchField(), and wedgeFvsPatchField< Type >::wedgeFvsPatchField().
updated()
bool updated () const inline noexcept
Definition at line 176 of file fvsPatchField.H.
manipulatedMatrix()
bool manipulatedMatrix () const inline noexcept
Definition at line 182 of file fvsPatchField.H.
checkPatch()
void checkPatch (const fvsPatchFieldBase & rhs) const
Definition at line 83 of file fvsPatchFieldBase.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Referenced by fvsPatchField< Type >::check(), fvsPatchField< Type >::operator*=(), fvsPatchField< Type >::operator+=(), fvsPatchField< Type >::operator-=(), fvsPatchField< Type >::operator/=(), and fvsPatchField< Type >::operator=().
Member Data Documentation
disallowGenericPatchField
int disallowGenericPatchField static
Definition at line 101 of file fvsPatchField.H.
Referenced by fvsPatchField< Type >::New().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvsPatchFields/fvsPatchField/fvsPatchField.H
src/finiteVolume/fields/fvsPatchFields/fvsPatchField/fvsPatchFieldBase.C