OpenFOAM: InteractionLists< ParticleType > Class Template Reference
InteractionLists< ParticleType > Class Template Reference
Builds direct interaction list, specifying which local (real) cells are potentially in range of each other.
#include <InteractionLists.H>
Public Member Functions
InteractionLists (const polyMesh &mesh)
InteractionLists (const polyMesh &mesh, scalar maxDistance, bool writeCloud=false, const word &UName="U")
~InteractionLists ()
void sendReferredData (const List< DynamicList< ParticleType * > > &cellOccupancy, PstreamBuffers &pBufs)
void receiveReferredData (PstreamBuffers &pBufs, const label startReq=0)
const polyMesh & mesh () const
const mapDistribute & cellMap () const
const mapDistribute & wallFaceMap () const
const labelListList & dil () const
const labelListList & dwfil () const
const labelListList & ril () const
const labelListList & rilInverse () const
const labelListList & rwfil () const
const labelListList & rwfilInverse () const
const List< labelPair > & cellIndexAndTransformToDistribute () const
const List< labelPair > & wallFaceIndexAndTransformToDistribute () const
const List< referredWallFace > & referredWallFaces () const
const word & UName () const
const List< vector > & referredWallData () const
const List< IDLList< ParticleType > > & referredParticles () const
List< IDLList< ParticleType > > & referredParticles ()
Detailed Description
template<class ParticleType>
class Foam::InteractionLists< ParticleType >
Builds direct interaction list, specifying which local (real) cells are potentially in range of each other.
Builds referred interaction list, specifying which cells are required to provide interactions across coupled patches (cyclic or processor). Generates referred cells, and refers particles to the correct processor, applying the appropriate transform.
Simultaneous communication and computation is possible using:
PstreamBuffers pBufs(Pstream::commsTypes::nonBlocking);
label startOfRequests = Pstream::nRequests();
il_.sendReferredData(cellOccupancy_, pBufs);
// Do other things
il_.receiveReferredData(pBufs, startOfRequests);
Requiring data:
List<DynamicList<typename CloudType::parcelType*>> cellOccupancy_;
Source files
InteractionLists.H
InteractionListsI.H
InteractionLists.C
InteractionListsIO.C
Definition at line 77 of file InteractionLists.H.
Constructor & Destructor Documentation
InteractionLists() [1/2]
template<class ParticleType > InteractionLists (const polyMesh & mesh)
Definition at line 1004 of file InteractionLists.C.
InteractionLists() [2/2]
template<class ParticleType > InteractionLists (const polyMesh & mesh, scalar maxDistance, bool writeCloud = false, const word & UName = "U")
Definition at line 1026 of file InteractionLists.C.
~InteractionLists()
template<class ParticleType > ~InteractionLists ()
Definition at line 1058 of file InteractionLists.C.
Member Function Documentation
sendReferredData()
template<class ParticleType > void sendReferredData (const List< DynamicList< ParticleType * > > & cellOccupancy, PstreamBuffers & pBufs)
Definition at line 1065 of file InteractionLists.C.
References UPstream::allProcs(), cellOccupancy, Foam::endl(), forAll, UList< T >::size(), and WarningInFunction.
receiveReferredData()
template<class ParticleType > void receiveReferredData (PstreamBuffers & pBufs, const label startReq = 0)
Definition at line 1113 of file InteractionLists.C.
References UPstream::allProcs(), forAll, p, UList< T >::size(), and UPstream::waitRequests().
mesh()
template<class ParticleType > const Foam::polyMesh & mesh () const inline
Definition at line 26 of file InteractionListsI.H.
cellMap()
template<class ParticleType > const Foam::mapDistribute & cellMap () const inline
Definition at line 34 of file InteractionListsI.H.
wallFaceMap()
template<class ParticleType > const Foam::mapDistribute & wallFaceMap () const inline
Definition at line 42 of file InteractionListsI.H.
dil()
template<class ParticleType > const Foam::labelListList & dil () const inline
Definition at line 49 of file InteractionListsI.H.
dwfil()
template<class ParticleType > const Foam::labelListList & dwfil () const inline
Definition at line 57 of file InteractionListsI.H.
ril()
template<class ParticleType > const Foam::labelListList & ril () const inline
Definition at line 64 of file InteractionListsI.H.
rilInverse()
template<class ParticleType > const Foam::labelListList & rilInverse () const inline
Definition at line 72 of file InteractionListsI.H.
rwfil()
template<class ParticleType > const Foam::labelListList & rwfil () const inline
Definition at line 79 of file InteractionListsI.H.
rwfilInverse()
template<class ParticleType > const Foam::labelListList & rwfilInverse () const inline
Definition at line 87 of file InteractionListsI.H.
cellIndexAndTransformToDistribute()
template<class ParticleType > const Foam::List< Foam::labelPair > & cellIndexAndTransformToDistribute () const inline
Definition at line 95 of file InteractionListsI.H.
wallFaceIndexAndTransformToDistribute()
template<class ParticleType > const Foam::List< Foam::labelPair > & wallFaceIndexAndTransformToDistribute () const inline
Definition at line 103 of file InteractionListsI.H.
referredWallFaces()
template<class ParticleType > const Foam::List< Foam::referredWallFace > & referredWallFaces () const inline
Definition at line 112 of file InteractionListsI.H.
UName()
template<class ParticleType > const Foam::word & UName () const inline
Definition at line 119 of file InteractionListsI.H.
referredWallData()
template<class ParticleType > const Foam::List< Foam::vector > & referredWallData () const inline
Definition at line 127 of file InteractionListsI.H.
referredParticles() [1/2]
template<class ParticleType > const Foam::List< Foam::IDLList< ParticleType > > & referredParticles () const inline
Definition at line 135 of file InteractionListsI.H.
referredParticles() [2/2]
template<class ParticleType > Foam::List< Foam::IDLList< ParticleType > > & referredParticles () inline
Definition at line 143 of file InteractionListsI.H.
The documentation for this class was generated from the following files:
src/lagrangian/basic/InteractionLists/InteractionLists.H
src/lagrangian/basic/InteractionLists/InteractionLists.C
src/lagrangian/basic/InteractionLists/InteractionListsI.H