OpenFOAM: igzstream Class Reference
igzstream Class Reference
#include <gzstream.h>
Public Member Functions
igzstream ()
igzstream (const char *_name, int _open_mode=std::ios::in)
igzstream (const std::string &_name, int _open_mode=std::ios::in)
gzstreambuf * rdbuf ()
void open (const char *_name, int _open_mode=std::ios::in)
void open (const std::string &_name, int _open_mode=std::ios::in)
Public Member Functions inherited from gzstreambase
gzstreambase ()
gzstreambase (const char *_name, int _open_mode)
~gzstreambase ()
void open (const char *_name, int _open_mode)
void close ()
gzstreambuf * rdbuf ()
Additional Inherited Members
Protected Attributes inherited from gzstreambase
gzstreambuf buf
Detailed Description
Definition at line 153 of file gzstream.h.
Constructor & Destructor Documentation
igzstream() [1/3]
igzstream () inline
Definition at line 161 of file gzstream.h.
igzstream() [2/3]
igzstream (const char * _name, int _open_mode = std::ios::in) inline explicit
Definition at line 165 of file gzstream.h.
igzstream() [3/3]
igzstream (const std::string & _name, int _open_mode = std::ios::in) inline explicit
Definition at line 171 of file gzstream.h.
Member Function Documentation
rdbuf()
gzstreambuf * rdbuf () inline
Definition at line 177 of file gzstream.h.
References gzstreambase::rdbuf().
open() [1/2]
void open (const char * _name, int _open_mode = std::ios::in) inline
Definition at line 181 of file gzstream.h.
References gzstreambase::open().
open() [2/2]
void open (const std::string & _name, int _open_mode = std::ios::in) inline
Definition at line 186 of file gzstream.h.
References gzstreambase::open().
The documentation for this class was generated from the following file:
src/OpenFOAM/db/IOstreams/gzstream/gzstream.h