OpenFOAM: semiPermeableBaffleMassFractionFvPatchScalarField Class Reference
semiPermeableBaffleMassFractionFvPatchScalarField Class Reference
Boundary conditions » Generic
This is a mass-fraction boundary condition for a semi-permeable baffle.
#include <semiPermeableBaffleMassFractionFvPatchScalarField.H>
Public Member Functions
TypeName ("semiPermeableBaffleMassFraction")
semiPermeableBaffleMassFractionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
semiPermeableBaffleMassFractionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
semiPermeableBaffleMassFractionFvPatchScalarField (const semiPermeableBaffleMassFractionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
semiPermeableBaffleMassFractionFvPatchScalarField (const semiPermeableBaffleMassFractionFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
semiPermeableBaffleMassFractionFvPatchScalarField (const semiPermeableBaffleMassFractionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
tmp< scalarField > phiY () const
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Public Member Functions inherited from mappedPatchBase
TypeName ("mappedPatchBase")
mappedPatchBase (const polyPatch &)
mappedPatchBase (const polyPatch &pp, const word &sampleRegion, const sampleMode sampleMode, const word &samplePatch, const vectorField &offsets)
mappedPatchBase (const polyPatch &pp, const word &sampleRegion, const sampleMode sampleMode, const word &samplePatch, const vector &uniformOffset)
mappedPatchBase (const polyPatch &pp, const word &sampleRegion, const sampleMode sampleMode, const word &samplePatch, const scalar normalDistance)
mappedPatchBase (const polyPatch &, const dictionary &)
mappedPatchBase (const polyPatch &, const sampleMode, const dictionary &)
mappedPatchBase (const polyPatch &, const mappedPatchBase &)
mappedPatchBase (const polyPatch &, const mappedPatchBase &, const labelUList &mapAddressing)
virtual ~mappedPatchBase ()
void clearOut ()
void setOffset (const scalar normalDist)
void setOffset (const vector &uniformOffset)
void setOffset (const vectorField &offsets)
sampleMode mode () const noexcept
const word & sampleWorld () const noexcept
const word & sampleRegion () const
const word & samplePatch () const
const word & coupleGroup () const
label sampleSize () const
const vector & offset () const noexcept
const vectorField & offsets () const noexcept
label getCommunicator () const
label comm () const
bool sameWorld () const
bool masterWorld () const
bool sameRegion () const noexcept
uniformDimensionedScalarField & updateSampleMeshTime () const
uniformDimensionedScalarField & updateMeshTime () const
bool upToDate () const
const mapDistribute & map () const
const AMIPatchToPatchInterpolation & AMI (const bool forceUpdate=false) const
bool owner () const
const autoPtr< Foam::searchableSurface > & surfPtr () const
const polyMesh & sampleMesh () const
const polyPatch & samplePolyPatch () const
tmp< pointField > samplePoints () const
const fileName & sampleDatabasePath () const
bool sampleDatabase () const
virtual fileName sendPath (const label proci) const
virtual fileName receivePath (const label proci) const
template<class Type >
void distribute (List< Type > &lst) const
template<class Type , class CombineOp >
void distribute (List< Type > &lst, const CombineOp &cop) const
template<class Type >
void reverseDistribute (List< Type > &lst) const
template<class Type , class CombineOp >
void reverseDistribute (List< Type > &lst, const CombineOp &cop) const
Additional Inherited Members
Public Types inherited from mappedPatchBase
enum sampleMode {
NEARESTCELL , NEARESTPATCHFACE , NEARESTPATCHFACEAMI , NEARESTPATCHPOINT ,
NEARESTFACE , NEARESTONLYCELL
}
enum offsetMode { UNIFORM , NONUNIFORM , NORMAL }
typedef Tuple2< pointIndexHit, Tuple2< scalar, label > > nearInfo
typedef Tuple2< nearInfo, label > nearInfoWorld
Static Public Member Functions inherited from mappedPatchBase
static pointIndexHit facePoint (const polyMesh &, const label facei, const polyMesh::cellDecomposition)
static fileName sendPath (const fileName &root, const label proci)
static fileName receivePath (const fileName &root, const label proci)
static const objectRegistry & subRegistry (const objectRegistry &obr, const fileName &path)
template<class Type >
static void storeField (objectRegistry &obr, const word &fieldName, const Field< Type > &values)
static void writeDict (const objectRegistry &obr, dictionary &dict)
static void readDict (const dictionary &d, objectRegistry &obr)
Static Public Attributes inherited from mappedPatchBase
static const Enum< sampleMode > sampleModeNames_
static const Enum< offsetMode > offsetModeNames_
Protected Member Functions inherited from mappedPatchBase
bool addWorldConnection ()
label getWorldCommunicator () const
const polyMesh & lookupMesh (const word &region) const
const polyPatch & lookupPatch (const word &sampleRegion, const word &samplePatch) const
tmp< pointField > facePoints (const polyPatch &) const
void collectSamples (const label mySampleWorld, const pointField &facePoints, pointField &samples, labelList &patchFaceWorlds, labelList &patchFaceProcs, labelList &patchFaces, pointField &patchFc) const
void findLocalSamples (const sampleMode mode, const label sampleWorld, const word &sampleRegion, const word &samplePatch, const pointField &samplePoints, List< nearInfoWorld > &nearest) const
void findSamples (const sampleMode mode, const label myWorldIndex, const pointField &, const labelList &wantedWorlds, const labelList &origProcs, labelList &sampleProcs, labelList &sampleIndices, pointField &sampleLocations) const
tmp< pointField > samplePoints (const pointField &) const
void calcMapping () const
void calcAMI () const
Static Protected Member Functions inherited from mappedPatchBase
static autoPtr< fileName > readDatabase (const dictionary &dict)
static const objectRegistry & subRegistry (const objectRegistry &obr, const wordList &names, const label index)
template<class Type >
static bool writeIOField (const regIOobject &obj, dictionary &dict)
template<class Type >
static bool constructIOField (const word &name, token &tok, Istream &is, objectRegistry &obr)
Protected Attributes inherited from mappedPatchBase
const polyPatch & patch_
word sampleWorld_
word sampleRegion_
const sampleMode mode_
word samplePatch_
const coupleGroupIdentifier coupleGroup_
const autoPtr< fileName > sampleDatabasePtr_
offsetMode offsetMode_
vector offset_
vectorField offsets_
scalar distance_
label communicator_
bool sameRegion_
autoPtr< mapDistribute > mapPtr_
const bool AMIReverse_
autoPtr< AMIPatchToPatchInterpolation > AMIPtr_
autoPtr< searchableSurface > surfPtr_
dictionary surfDict_
autoPtr< uniformDimensionedScalarField > updateMeshTimePtr_
autoPtr< uniformDimensionedScalarField > updateSampleMeshTimePtr_
Detailed Description
This is a mass-fraction boundary condition for a semi-permeable baffle.
This condition models a baffle which is permeable to a some species and impermeable to others. It must be used in conjunction with the corresponding velocity condition, semiPermeableBaffleVelocityFvPatchVectorField.
The mass flux of a species is calculated as a coefficient multiplied by the difference in mass fraction across the baffle.
where
= flux of the permeable species [kg/s]
= transfer coefficient [kg/m2/s]
= patch face area [m2]
= mass fraction on the patch []
= mass fraction on the neighbour patch []
A species that the baffle is permable to will, therefore, have a coefficient greater than zero, whilst a species that does not transfer will have a coefficient equal to zero.
This condition calculates the species flux. The fluxes are summed up by the velocity consition to generate the net mass transfer across the baffle. This mass-fraction condition then generates a corrective diffusive flux to ensure that the correct amounts of the permeable species are transferred.
Usage
Property Description Req'd? Default
c Transfer coefficient no 0
phi Name of the flux field no phi
See also
Foam::semiPermeableBaffleVelocityFvPatchVectorField
Source files
semiPermeableBaffleMassFractionFvPatchScalarField.H
semiPermeableBaffleMassFractionFvPatchScalarField.C
Definition at line 123 of file semiPermeableBaffleMassFractionFvPatchScalarField.H.
Constructor & Destructor Documentation
semiPermeableBaffleMassFractionFvPatchScalarField() [1/5]
semiPermeableBaffleMassFractionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 31 of file semiPermeableBaffleMassFractionFvPatchScalarField.C.
References Foam::Zero.
semiPermeableBaffleMassFractionFvPatchScalarField() [2/5]
semiPermeableBaffleMassFractionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 49 of file semiPermeableBaffleMassFractionFvPatchScalarField.C.
References dict, IOobjectOption::MUST_READ, and Foam::Zero.
semiPermeableBaffleMassFractionFvPatchScalarField() [3/5]
semiPermeableBaffleMassFractionFvPatchScalarField (const semiPermeableBaffleMassFractionFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 70 of file semiPermeableBaffleMassFractionFvPatchScalarField.C.
semiPermeableBaffleMassFractionFvPatchScalarField() [4/5]
semiPermeableBaffleMassFractionFvPatchScalarField (const semiPermeableBaffleMassFractionFvPatchScalarField & ptf)
Definition at line 86 of file semiPermeableBaffleMassFractionFvPatchScalarField.C.
semiPermeableBaffleMassFractionFvPatchScalarField() [5/5]
semiPermeableBaffleMassFractionFvPatchScalarField (const semiPermeableBaffleMassFractionFvPatchScalarField & ptf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 99 of file semiPermeableBaffleMassFractionFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("semiPermeableBaffleMassFraction")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 177 of file semiPermeableBaffleMassFractionFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 193 of file semiPermeableBaffleMassFractionFvPatchScalarField.H.
phiY()
Foam::tmp< Foam::scalarField > phiY () const
Definition at line 116 of file semiPermeableBaffleMassFractionFvPatchScalarField.C.
References mappedPatchBase::map(), tmp< T >::New(), and Foam::Zero.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 136 of file semiPermeableBaffleMassFractionFvPatchScalarField.C.
References turbulenceModel::propertiesName.
write()
void write (Ostream & os) const virtual
Reimplemented from mappedPatchBase.
Definition at line 161 of file semiPermeableBaffleMassFractionFvPatchScalarField.C.
References os(), fvPatchField< Type >::write(), mappedPatchBase::write(), Ostream::writeEntryIfDifferent(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/thermoTools/derivedFvPatchFields/semiPermeableBaffle/semiPermeableBaffleMassFraction/semiPermeableBaffleMassFractionFvPatchScalarField.H
src/thermoTools/derivedFvPatchFields/semiPermeableBaffle/semiPermeableBaffleMassFraction/semiPermeableBaffleMassFractionFvPatchScalarField.C