OpenFOAM: BreenWestwater Class Reference
BreenWestwater Class Reference
Boiling film correlation. A correlation for boiling film modelling based on Breen & Westwater (1965) for boiling flows.
#include <BreenWestwater.H>
Public Member Functions
TypeName ("BreenWestwater")
BreenWestwater (const dictionary &dict)
virtual ~BreenWestwater ()=default
virtual tmp< scalarField > htcFilmBoil (const phaseModel &liquid, const phaseModel &vapor, const label patchi, const scalarField &Tl, const scalarField &Tsatw, const scalarField &L) const
virtual void write (Ostream &os) const
Public Member Functions inherited from filmBoilingModel
TypeName ("filmBoilingModel")
declareRunTimeSelectionTable (autoPtr, filmBoilingModel, dictionary,(const dictionary &dict),(dict))
filmBoilingModel ()=default
virtual ~filmBoilingModel ()=default
Additional Inherited Members
Static Public Member Functions inherited from filmBoilingModel
static autoPtr< filmBoilingModel > New (const dictionary &dict)
Detailed Description
Boiling film correlation. A correlation for boiling film modelling based on Breen & Westwater (1965) for boiling flows.
References:
    Breen B.P. & Westwater J. W. (1965)
    Effect of diameter of horizontal
    tubes on film boiling heat tranfer.
    Chem. Eng. Progr. 58. No 7.
Usage
Example of the model specification:
filmBoilingModel
{
    // Mandatory entries
    type            BreenWestwater;
    // Optional entries
    Cn              <scalar>;
    an              <scalar>;
    bn              <scalar>;
    n               <scalar>;
}
where the entries mean:
Property Description Type Reqd Deflt
type Type name: BreenWestwater word yes -
Cn Model coefficient scalar no 0.37
Source files
BreenWestwater.H
BreenWestwater.C
Definition at line 101 of file BreenWestwater.H.
Constructor & Destructor Documentation
BreenWestwater()
BreenWestwater (const dictionary & dict)
Definition at line 48 of file BreenWestwater.C.
~BreenWestwater()
virtual ~BreenWestwater () virtual default
Member Function Documentation
TypeName()
TypeName ("BreenWestwater")
htcFilmBoil()
Foam::tmp< Foam::scalarField > htcFilmBoil (const phaseModel & liquid, const phaseModel & vapor, const label patchi, const scalarField & Tl, const scalarField & Tsatw, const scalarField & L) const virtual
Implements filmBoilingModel.
Definition at line 61 of file BreenWestwater.C.
References cells, e, g, liquid::kappa(), L, Foam::mag(), Foam::max(), Foam::pow(), Foam::pow3(), liquid::sigma(), Foam::sqr(), and tCp.
write()
void write (Ostream & os) const virtual
Reimplemented from filmBoilingModel.
Definition at line 119 of file BreenWestwater.C.
References os(), and filmBoilingModel::write().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/wallBoilingSubModels/filmBoilingModels/BreenWestwater/BreenWestwater.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/wallBoilingSubModels/filmBoilingModels/BreenWestwater/BreenWestwater.C