OpenFOAM: displacementMethodelasticityMotionSolver Class Reference
displacementMethodelasticityMotionSolver Class Reference
Wrapper class for the elasticityMotionSolver motion solver.
#include <displacementMethodelasticityMotionSolver.H>
Public Member Functions
TypeName ("elasticityMotionSolver")
displacementMethodelasticityMotionSolver (fvMesh &mesh, const labelList &patchIDs)
virtual ~displacementMethodelasticityMotionSolver ()=default
void setMotionField (const pointVectorField &pointMovement)
void setMotionField (const volVectorField &cellMovement)
void setControlField (const vectorField &controlField)
void setControlField (const scalarField &controlField)
Public Member Functions inherited from displacementMethod
TypeName ("displacementMethod")
declareRunTimeSelectionTable (autoPtr, displacementMethod, dictionary,(fvMesh &mesh, const labelList &patchIDs),(mesh, patchIDs))
displacementMethod (fvMesh &mesh, const labelList &patchIDs)
virtual ~displacementMethod ()=default
virtual void boundControlField (vectorField &controlField)
autoPtr< motionSolver > & getMotionSolver ()
scalar getMaxDisplacement () const
void update ()
Protected Attributes
pointVectorField & pointMotionU_
volVectorField & cellMotionU_
bool resetFields_
Protected Attributes inherited from displacementMethod
fvMesh & mesh_
const labelList & patchIDs_
autoPtr< motionSolver > motionPtr_
scalar maxDisplacement_
Additional Inherited Members
Static Public Member Functions inherited from displacementMethod
static autoPtr< displacementMethod > New (fvMesh &mesh, const labelList &patchIDs)
Detailed Description
Wrapper class for the elasticityMotionSolver motion solver.
Source files
displacementMethodelasticityMotionSolver.H
displacementMethodelasticityMotionSolver.C
Definition at line 49 of file displacementMethodelasticityMotionSolver.H.
Constructor & Destructor Documentation
displacementMethodelasticityMotionSolver()
displacementMethodelasticityMotionSolver (fvMesh & mesh, const labelList & patchIDs)
Definition at line 44 of file displacementMethodelasticityMotionSolver.C.
~displacementMethodelasticityMotionSolver()
virtual ~displacementMethodelasticityMotionSolver () virtual default
Member Function Documentation
TypeName()
TypeName ("elasticityMotionSolver")
setMotionField() [1/2]
void setMotionField (const pointVectorField & pointMovement) virtual
Implements displacementMethod.
Definition at line 94 of file displacementMethodelasticityMotionSolver.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), polyMesh::boundaryMesh(), displacementMethodelasticityMotionSolver::cellMotionU_, GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), forAll, Foam::gMax(), Foam::mag(), Foam::max(), displacementMethod::maxDisplacement_, displacementMethod::mesh_, displacementMethod::patchIDs_, displacementMethodelasticityMotionSolver::pointMotionU_, points, polyMesh::points(), GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef(), displacementMethodelasticityMotionSolver::resetFields_, and VectorSpace< Form, Cmpt, Ncmpts >::zero.
setMotionField() [2/2]
void setMotionField (const volVectorField & cellMovement) virtual
Implements displacementMethod.
Definition at line 155 of file displacementMethodelasticityMotionSolver.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), displacementMethodelasticityMotionSolver::cellMotionU_, forAll, Foam::gMax(), Foam::mag(), Foam::max(), displacementMethod::maxDisplacement_, and displacementMethod::patchIDs_.
setControlField() [1/2]
void setControlField (const vectorField & controlField) virtual
Implements displacementMethod.
Definition at line 185 of file displacementMethodelasticityMotionSolver.C.
References NotImplemented.
setControlField() [2/2]
void setControlField (const scalarField & controlField) virtual
Implements displacementMethod.
Definition at line 194 of file displacementMethodelasticityMotionSolver.C.
References NotImplemented.
Member Data Documentation
pointMotionU_
pointVectorField& pointMotionU_ protected
Definition at line 57 of file displacementMethodelasticityMotionSolver.H.
Referenced by displacementMethodelasticityMotionSolver::setMotionField().
cellMotionU_
volVectorField& cellMotionU_ protected
Definition at line 59 of file displacementMethodelasticityMotionSolver.H.
Referenced by displacementMethodelasticityMotionSolver::setMotionField(), and displacementMethodelasticityMotionSolver::setMotionField().
resetFields_
bool resetFields_ protected
Definition at line 61 of file displacementMethodelasticityMotionSolver.H.
Referenced by displacementMethodelasticityMotionSolver::setMotionField().
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/displacementMethod/displacementMethodelasticityMotionSolver/displacementMethodelasticityMotionSolver.H
src/optimisation/adjointOptimisation/adjoint/displacementMethod/displacementMethodelasticityMotionSolver/displacementMethodelasticityMotionSolver.C