OpenFOAM: Casson Class Reference
Casson Class Reference
An incompressible Casson non-Newtonian viscosity model.
#include <Casson.H>
Public Member Functions
TypeName ("Casson")
Casson (const word &name, const dictionary &viscosityProperties, const volVectorField &U, const surfaceScalarField &phi)
virtual ~Casson ()=default
virtual tmp< volScalarField > nu () const
virtual tmp< scalarField > nu (const label patchi) const
virtual void correct ()
virtual bool read (const dictionary &viscosityProperties)
Public Member Functions inherited from viscosityModel
TypeName ("viscosityModel")
declareRunTimeSelectionTable (autoPtr, viscosityModel, dictionary,(const word &name, const dictionary &viscosityProperties, const volVectorField &U, const surfaceScalarField &phi),(name, viscosityProperties, U, phi))
viscosityModel (const word &name, const dictionary &viscosityProperties, const volVectorField &U, const surfaceScalarField &phi)
virtual ~viscosityModel ()=default
const dictionary & viscosityProperties () const
tmp< volScalarField > strainRate () const
Protected Member Functions
tmp< volScalarField > calcNu () const
Protected Member Functions inherited from viscosityModel
viscosityModel (const viscosityModel &)=delete
void operator= (const viscosityModel &)=delete
Protected Attributes
volScalarField nu_
Protected Attributes inherited from viscosityModel
word name_
dictionary viscosityProperties_
const volVectorField & U_
const surfaceScalarField & phi_
Additional Inherited Members
Static Public Member Functions inherited from viscosityModel
static autoPtr< viscosityModel > New (const word &name, const dictionary &viscosityProperties, const volVectorField &U, const surfaceScalarField &phi)
Detailed Description
An incompressible Casson non-Newtonian viscosity model.
References:
    Casson, N. (1959).
    Rheology of disperse systems.
    In Proceedings of a Conference Organized by the
    British Society of Rheology.
    Pergamon Press, New York.
    Fournier, R. L. (2011).
    Basic transport phenomena in biomedical engineering.
    CRC Press.
Example specification for blood:
     transportModel  Casson;
     CassonCoeffs
     {
         m       3.934986e-6;
         tau0    2.9032e-6;
         nuMax   13.3333e-6;
         nuMin   3.9047e-6;
     }
Source files
Casson.H
Casson.C
Definition at line 78 of file Casson.H.
Constructor & Destructor Documentation
Casson()
Casson (const word & name, const dictionary & viscosityProperties, const volVectorField & U, const surfaceScalarField & phi)
Definition at line 73 of file Casson.C.
~Casson()
virtual ~Casson () virtual default
Member Function Documentation
calcNu()
Foam::tmp< Foam::volScalarField > calcNu () const protected
Definition at line 46 of file Casson.C.
References Foam::dimless, Foam::dimTime, Foam::max(), Foam::min(), Foam::sqr(), Foam::sqrt(), and viscosityModel::strainRate().
Referenced by Casson::correct().
TypeName()
TypeName ("Casson")
nu() [1/2]
virtual tmp< volScalarField > nu () const inline virtual
Implements viscosityModel.
Definition at line 131 of file Casson.H.
References Casson::nu_.
nu() [2/2]
virtual tmp< scalarField > nu (const label patchi) const inline virtual
Implements viscosityModel.
Definition at line 137 of file Casson.H.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), and Casson::nu_.
correct()
virtual void correct () inline virtual
Implements viscosityModel.
Definition at line 143 of file Casson.H.
References Casson::calcNu(), and Casson::nu_.
read()
bool read (const dictionary & viscosityProperties) virtual
Implements viscosityModel.
Definition at line 104 of file Casson.C.
References dictionary::optionalSubDict(), and viscosityModel::read().
Member Data Documentation
nu_
volScalarField nu_ protected
Definition at line 97 of file Casson.H.
Referenced by Casson::correct(), Casson::nu(), and Casson::nu().
The documentation for this class was generated from the following files:
src/transportModels/incompressible/viscosityModels/Casson/Casson.H
src/transportModels/incompressible/viscosityModels/Casson/Casson.C