OpenFOAM: snappySnapDriver Class Reference
snappySnapDriver Class Reference
All to do with snapping to surface.
#include <snappySnapDriver.H>
Public Member Functions
ClassName ("snappySnapDriver")
snappySnapDriver (meshRefinement &meshRefiner, const labelList &globalToMasterPatch, const labelList &globalToSlavePatch, const bool dryRun=false)
autoPtr< mapPolyMesh > mergeZoneBaffles (const List< labelPair > &)
void detectNearSurfaces (const scalar planarCos, const indirectPrimitivePatch &, const pointField &nearestPoint, const vectorField &nearestNormal, vectorField &disp) const
void smoothDisplacement (const snapParameters &snapParams, motionSmoother &) const
bool scaleMesh (const snapParameters &snapParams, const label nInitErrors, const List< labelPair > &baffles, motionSmoother &)
autoPtr< mapPolyMesh > repatchToSurface (const snapParameters &snapParams, const labelList &adaptPatchIDs, const labelList &preserveFaces)
void doSnap (const dictionary &snapDict, const dictionary &motionDict, const meshRefinement::FaceMergeType mergeType, const scalar featureCos, const scalar planarAngle, const snapParameters &snapParams)
template<class FaceList >
Foam::labelList getFacePoints (const indirectPrimitivePatch &pp, const FaceList &faces)
Static Public Member Functions
static scalarField calcSnapDistance (const fvMesh &mesh, const snapParameters &snapParams, const indirectPrimitivePatch &)
static void preSmoothPatch (const meshRefinement &meshRefiner, const snapParameters &snapParams, const label nInitErrors, const List< labelPair > &baffles, motionSmoother &)
static tmp< pointField > avgCellCentres (const fvMesh &mesh, const indirectPrimitivePatch &)
static vectorField calcNearestSurface (const bool strictRegionSnap, const meshRefinement &meshRefiner, const labelList &globalToMasterPatch, const labelList &globalToSlavePatch, const scalarField &snapDist, const indirectPrimitivePatch &, pointField &nearestPoint, vectorField &nearestNormal)
Detailed Description
All to do with snapping to surface.
Source files
snappySnapDriver.H
snappySnapDriver.C
snappySnapDriverFeature.C
Definition at line 55 of file snappySnapDriver.H.
Constructor & Destructor Documentation
snappySnapDriver()
snappySnapDriver (meshRefinement & meshRefiner, const labelList & globalToMasterPatch, const labelList & globalToSlavePatch, const bool dryRun = false)
Definition at line 805 of file snappySnapDriver.C.
Member Function Documentation
ClassName()
ClassName ("snappySnapDriver")
mergeZoneBaffles()
autoPtr< mapPolyMesh > mergeZoneBaffles (const List< labelPair > &)
calcSnapDistance()
Foam::scalarField calcSnapDistance (const fvMesh & mesh, const snapParameters & snapParams, const indirectPrimitivePatch & pp) static
Definition at line 822 of file snappySnapDriver.C.
References e, PrimitivePatch< FaceList, PointField >::edges(), forAll, PrimitivePatch< FaceList, PointField >::localPoints(), Foam::max(), mesh, PrimitivePatch< FaceList, PointField >::meshPoints(), PrimitivePatch< FaceList, PointField >::pointEdges(), pp(), UList< T >::size(), and syncTools::syncPointList().
preSmoothPatch()
void preSmoothPatch (const meshRefinement & meshRefiner, const snapParameters & snapParams, const label nInitErrors, const List< labelPair > & baffles, motionSmoother & meshMover) static
Definition at line 862 of file snappySnapDriver.C.
References addProfiling, motionSmootherAlgo::correct(), Foam::endl(), forAll, Foam::Info, mesh, meshRefinement::MESH, primitiveMesh::nFaces(), Foam::nl, motionSmootherAlgo::pointDisplacement(), GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef(), motionSmootherAlgo::scaleMesh(), motionSmootherAlgo::setDisplacement(), motionSmootherAlgo::setErrorReduction(), List< T >::setSize(), fvMesh::time(), meshRefinement::writeLevel(), and meshRefinement::WRITEMESH.
avgCellCentres()
Foam::tmp< Foam::pointField > avgCellCentres (const fvMesh & mesh, const indirectPrimitivePatch & pp) static
Definition at line 1024 of file snappySnapDriver.C.
References primitiveMesh::cellCentres(), polyMesh::faceOwner(), UPtrList< T >::first(), forAll, weightedPosition::getPoints(), mesh, PrimitivePatch< FaceList, PointField >::meshPoints(), pFaces, PrimitivePatch< FaceList, PointField >::pointFaces(), pp(), UPtrList< T >::size(), UList< T >::size(), and weightedPosition::syncPoints().
detectNearSurfaces()
void detectNearSurfaces (const scalar planarCos, const indirectPrimitivePatch & pp, const pointField & nearestPoint, const vectorField & nearestNormal, vectorField & disp) const
Definition at line 1109 of file snappySnapDriver.C.
References meshRefinement::ATTRACTION, Foam::endl(), refinementSurfaces::findNearestIntersection(), forAll, meshRefinement::getMasterPoints(), surfaceZonesInfo::getNamedSurfaces(), surfaceZonesInfo::getUnnamedSurfaces(), Foam::Info, PrimitivePatch< FaceList, PointField >::localPoints(), mesh, PrimitivePatch< FaceList, PointField >::meshPoints(), PrimitivePatch< FaceList, PointField >::nPoints(), pp(), Foam::returnReduce(), refinementSurfaces::surfaces(), refinementSurfaces::surfZones(), and fvMesh::time().
calcNearestSurface()
Foam::vectorField calcNearestSurface (const bool strictRegionSnap, const meshRefinement & meshRefiner, const labelList & globalToMasterPatch, const labelList & globalToSlavePatch, const scalarField & snapDist, const indirectPrimitivePatch & pp, pointField & nearestPoint, vectorField & nearestNormal) static
Definition at line 1787 of file snappySnapDriver.C.
References polyMesh::boundaryMesh(), Foam::endl(), refinementSurfaces::findNearest(), refinementSurfaces::findNearestRegion(), forAll, meshRefinement::gAverage(), refinementSurfaces::geometry(), meshRefinement::getMasterPoints(), surfaceZonesInfo::getNamedSurfaces(), surfaceZonesInfo::getUnnamedSurfaces(), refinementSurfaces::globalRegion(), Foam::gMax(), Foam::gMin(), Foam::identity(), Foam::Info, PrimitivePatch< FaceList, PointField >::localPoints(), Foam::mag(), mesh, PrimitivePatch< FaceList, PointField >::meshPoints(), Foam::nl, PrimitivePatch< FaceList, PointField >::nPoints(), Foam::Pout, pp(), Foam::returnReduceOr(), UPtrList< T >::size(), UList< T >::size(), Foam::sqr(), refinementSurfaces::surfaces(), refinementSurfaces::surfZones(), syncTools::syncPointList(), fvMesh::time(), WarningInFunction, and Foam::Zero.
smoothDisplacement()
void smoothDisplacement (const snapParameters & snapParams, motionSmoother & meshMover) const
Definition at line 2122 of file snappySnapDriver.C.
References motionSmootherData::displacement(), Foam::endl(), Foam::Info, PrimitivePatch< FaceList, PointField >::localPoints(), Foam::mag(), mesh, meshRefinement::MESH, PrimitivePatch< FaceList, PointField >::meshPoints(), Foam::nl, motionSmootherAlgo::patch(), motionSmootherAlgo::pMesh(), pp(), motionSmootherAlgo::smooth(), fvMesh::time(), Ostream::write(), meshRefinement::writeLevel(), and meshRefinement::WRITEMESH.
scaleMesh()
bool scaleMesh (const snapParameters & snapParams, const label nInitErrors, const List< labelPair > & baffles, motionSmoother & meshMover)
Definition at line 2196 of file snappySnapDriver.C.
References addProfiling, motionSmootherData::displacement(), Foam::endl(), Foam::identity(), Foam::Info, Foam::mag(), mesh, meshRefinement::MESH, primitiveMesh::nFaces(), Foam::nl, motionSmootherAlgo::scaleMesh(), motionSmootherAlgo::setErrorReduction(), fvMesh::time(), fvMesh::write(), and regIOobject::write().
repatchToSurface()
Foam::autoPtr< Foam::mapPolyMesh > repatchToSurface (const snapParameters & snapParams, const labelList & adaptPatchIDs, const labelList & preserveFaces)
Definition at line 2263 of file snappySnapDriver.C.
References polyMesh::boundaryMesh(), Foam::endl(), f(), primitiveMesh::faceCentres(), polyMesh::faceZones(), refinementSurfaces::findNearestRegion(), forAll, surfaceZonesInfo::getNamedSurfaces(), surfaceZonesInfo::getUnnamedSurfaces(), refinementSurfaces::globalRegion(), Foam::Info, PrimitivePatch< FaceList, PointField >::localFaces(), meshRefinement::makePatch(), Foam::max(), mesh, primitiveMesh::nFaces(), Foam::nl, patches, pp(), Foam::returnReduce(), PtrList< T >::set(), Foam::sqr(), refinementSurfaces::surfaces(), refinementSurfaces::surfZones(), UPtrList< T >::test(), and fvMesh::time().
doSnap()
void doSnap (const dictionary & snapDict, const dictionary & motionDict, const meshRefinement::FaceMergeType mergeType, const scalar featureCos, const scalar planarAngle, const snapParameters & snapParams)
Definition at line 2562 of file snappySnapDriver.C.
References addProfiling, PtrList< T >::append(), meshRefinement::ATTRACTION, motionSmootherAlgo::checkMesh(), PtrList< T >::clear(), motionSmootherAlgo::correct(), Foam::cos(), Foam::degToRad(), motionSmootherData::displacement(), Foam::endl(), Foam::exit(), primitiveMesh::faceCentres(), polyMesh::faceZones(), Foam::FatalError, FatalErrorInFunction, localPointRegion::findDuplicateFacePairs(), forAll, meshRefinement::GEOMETRIC, Foam::identity(), meshRefinement::IGNOREPATCH, Foam::Info, surfaceZonesInfo::INTERNAL, PrimitivePatch< FaceList, PointField >::localPoints(), Foam::mag(), meshRefinement::makeDisplacementField(), meshRefinement::makePatch(), VectorSpace< Form, Cmpt, Ncmpts >::max, mesh, meshRefinement::MESH, Foam::name(), MeshObject< polyMesh, UpdateableMeshObject, pointMesh >::New(), primitiveMesh::nFaces(), Foam::nl, PrimitivePatch< FaceList, PointField >::nPoints(), p, pp(), Foam::returnReduce(), motionSmootherAlgo::setDisplacement(), List< T >::setSize(), PtrList< T >::setSize(), UPtrList< T >::size(), fvMesh::time(), WarningInFunction, regIOobject::write(), Ostream::write(), meshRefinement::writeLevel(), meshRefinement::WRITEMESH, and Foam::Zero.
getFacePoints()
template<class FaceList > Foam::labelList getFacePoints (const indirectPrimitivePatch & pp, const FaceList & faces)
Definition at line 27 of file snappySnapDriverTemplates.C.
References f(), Foam::findIndices(), forAll, and pp().
The documentation for this class was generated from the following files:
src/mesh/snappyHexMesh/snappyHexMeshDriver/snappySnapDriver.H
src/mesh/snappyHexMesh/snappyHexMeshDriver/snappySnapDriver.C
src/mesh/snappyHexMesh/snappyHexMeshDriver/snappySnapDriverFeature.C
src/mesh/snappyHexMesh/snappyHexMeshDriver/snappySnapDriverTemplates.C