OpenFOAM: FaceCellWaveBase Class Reference
FaceCellWaveBase Class Reference
#include <FaceCellWave.H>
Public Member Functions
ClassName ("FaceCellWave")
FaceCellWaveBase (const polyMesh &mesh)
const polyMesh & mesh () const noexcept
label nChangedCells () const noexcept
label nChangedFaces () const noexcept
label nUnvisitedCells () const noexcept
label nUnvisitedFaces () const noexcept
Static Public Member Functions
static scalar propagationTol () noexcept
static scalar setPropagationTol (const scalar tol) noexcept
Static Public Attributes
static int dummyTrackData_ = 12345
Protected Attributes
const polyMesh & mesh_
PstreamBuffers pBufs_
bitSet changedFace_
bitSet changedCell_
DynamicList< label > changedFaces_
DynamicList< label > changedCells_
label nUnvisitedFaces_
label nUnvisitedCells_
Static Protected Attributes
static const scalar geomTol_ = 1e-6
static scalar propagationTol_ = 0.01
Detailed Description
Definition at line 67 of file FaceCellWave.H.
Constructor & Destructor Documentation
FaceCellWaveBase()
FaceCellWaveBase (const polyMesh & mesh) explicit
Definition at line 42 of file FaceCellWaveBase.C.
References PstreamBuffers::allowClearRecv(), and FaceCellWaveBase::pBufs_.
Member Function Documentation
ClassName()
ClassName ("FaceCellWave")
propagationTol()
static scalar propagationTol () inline static noexcept
Definition at line 123 of file FaceCellWave.H.
References FaceCellWaveBase::propagationTol_.
Referenced by hexRef8::consistentSlowRefinement2().
setPropagationTol()
static scalar setPropagationTol (const scalar tol) inline static noexcept
Definition at line 129 of file FaceCellWave.H.
References FaceCellWaveBase::propagationTol_.
mesh()
const polyMesh & mesh () const inline noexcept
Definition at line 140 of file FaceCellWave.H.
References FaceCellWaveBase::mesh_.
nChangedCells()
label nChangedCells () const inline noexcept
Definition at line 146 of file FaceCellWave.H.
References FaceCellWaveBase::changedCells_, and UList< T >::size().
Referenced by FaceCellWave< Type, TrackingData >::FaceCellWave(), FaceCellWave< Type, TrackingData >::FaceCellWave(), and OppositeFaceCellWave< Type, TrackingData >::OppositeFaceCellWave().
nChangedFaces()
label nChangedFaces () const inline noexcept
Definition at line 149 of file FaceCellWave.H.
References FaceCellWaveBase::changedFaces_, and UList< T >::size().
Referenced by FaceCellWave< Type, TrackingData >::FaceCellWave(), FaceCellWave< Type, TrackingData >::FaceCellWave(), and OppositeFaceCellWave< Type, TrackingData >::OppositeFaceCellWave().
nUnvisitedCells()
label nUnvisitedCells () const inline noexcept
Definition at line 157 of file FaceCellWave.H.
References FaceCellWaveBase::nUnvisitedCells_.
nUnvisitedFaces()
label nUnvisitedFaces () const inline noexcept
Definition at line 160 of file FaceCellWave.H.
References FaceCellWaveBase::nUnvisitedFaces_.
Member Data Documentation
geomTol_
const Foam::scalar geomTol_ = 1e-6 static protected
Definition at line 73 of file FaceCellWave.H.
propagationTol_
Foam::scalar propagationTol_ = 0.01 static protected
Definition at line 74 of file FaceCellWave.H.
Referenced by FaceCellWaveBase::propagationTol(), and FaceCellWaveBase::setPropagationTol().
mesh_
const polyMesh& mesh_ protected
Definition at line 80 of file FaceCellWave.H.
Referenced by FaceCellWave< Type, TrackingData >::FaceCellWave(), FaceCellWave< Type, TrackingData >::FaceCellWave(), FaceCellWave< Type, TrackingData >::FaceCellWave(), and FaceCellWaveBase::mesh().
pBufs_
PstreamBuffers pBufs_ protected
Definition at line 83 of file FaceCellWave.H.
Referenced by FaceCellWaveBase::FaceCellWaveBase().
changedFace_
bitSet changedFace_ protected
Definition at line 86 of file FaceCellWave.H.
changedCell_
bitSet changedCell_ protected
Definition at line 89 of file FaceCellWave.H.
changedFaces_
DynamicList<label> changedFaces_ protected
Definition at line 92 of file FaceCellWave.H.
Referenced by FaceCellWaveBase::nChangedFaces().
changedCells_
DynamicList<label> changedCells_ protected
Definition at line 95 of file FaceCellWave.H.
Referenced by FaceCellWaveBase::nChangedCells().
nUnvisitedFaces_
label nUnvisitedFaces_ protected
Definition at line 98 of file FaceCellWave.H.
Referenced by FaceCellWaveBase::nUnvisitedFaces().
nUnvisitedCells_
label nUnvisitedCells_ protected
Definition at line 101 of file FaceCellWave.H.
Referenced by FaceCellWaveBase::nUnvisitedCells().
dummyTrackData_
int dummyTrackData_ = 12345 static
Definition at line 107 of file FaceCellWave.H.
The documentation for this class was generated from the following files:
src/meshTools/algorithms/MeshWave/FaceCellWave.H
src/meshTools/algorithms/MeshWave/FaceCellWaveBase.C