OpenFOAM: processorGAMGInterface Class Reference
processorGAMGInterface Class Reference
GAMG agglomerated processor interface.
#include <processorGAMGInterface.H>
Public Member Functions
TypeName ("processor")
processorGAMGInterface (const label index, const lduInterfacePtrsList &coarseInterfaces, const lduInterface &fineInterface, const labelField &restrictAddressing, const labelField &neighbourRestrictAddressing, const label fineLevelIndex, const label coarseComm)
processorGAMGInterface (const label index, const lduInterfacePtrsList &coarseInterfaces, const labelUList &faceCells, const labelUList &faceRestrictAddresssing, const label coarseComm, const label myProcNo, const label neighbProcNo, const tensorField &forwardT, const int tag)
processorGAMGInterface (const label index, const lduInterfacePtrsList &coarseInterfaces, Istream &is)
virtual ~processorGAMGInterface ()=default
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &iF) const
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &iF, const labelUList &faceCells) const
virtual tmp< labelField > internalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &iF) const
virtual label comm () const
virtual int myProcNo () const
virtual int neighbProcNo () const
virtual const tensorField & forwardT () const
virtual int tag () const
virtual void write (Ostream &os) const
Public Member Functions inherited from GAMGInterface
TypeName ("GAMGInterface")
declareRunTimeSelectionTable (autoPtr, GAMGInterface, lduInterface,(const label index, const lduInterfacePtrsList &coarseInterfaces, const lduInterface &fineInterface, const labelField &localRestrictAddressing, const labelField &neighbourRestrictAddressing, const label fineLevelIndex, const label coarseComm),(index, coarseInterfaces, fineInterface, localRestrictAddressing, neighbourRestrictAddressing, fineLevelIndex, coarseComm))
declareRunTimeSelectionTable (autoPtr, GAMGInterface, Istream,(const label index, const lduInterfacePtrsList &coarseInterfaces, Istream &is),(index, coarseInterfaces, is))
GAMGInterface (const label index, const lduInterfacePtrsList &coarseInterfaces)
GAMGInterface (const label index, const lduInterfacePtrsList &coarseInterfaces, const labelUList &faceCells, const labelUList &faceRestrictAddressing)
GAMGInterface (const label index, const lduInterfacePtrsList &coarseInterfaces, Istream &is)
virtual label size () const
virtual label index () const
virtual const lduInterfacePtrsList & coarseInterfaces () const
virtual const labelUList & faceCells () const
virtual const labelList & faceRestrictAddressing () const
virtual labelList & faceRestrictAddressing ()
template<class Type >
tmp< Field< Type > > interfaceInternalField (const UList< Type > &internalData) const
template<class Type >
tmp< Field< Type > > interfaceInternalField (const UList< Type > &internalData, const labelUList &faceCells) const
template<class Type >
void interfaceInternalField (const UList< Type > &internalData, List< Type > &) const
virtual tmp< labelField > interfaceInternalField (const labelUList &internalData) const
virtual tmp< labelField > interfaceInternalField (const labelUList &internalData, const labelUList &faceCells) const
void combine (const GAMGInterface &)
virtual tmp< scalarField > agglomerateCoeffs (const scalarField &fineCoeffs) const
template<class Type >
Foam::tmp< Foam::Field< Type > > interfaceInternalField (const UList< Type > &iF) const
template<class Type >
Foam::tmp< Foam::Field< Type > > interfaceInternalField (const UList< Type > &iF, const labelUList &faceCells) const
Public Member Functions inherited from lduInterface
TypeNameNoDebug ("lduInterface")
lduInterface () noexcept=default
virtual ~lduInterface ()=default
Public Member Functions inherited from processorLduInterface
TypeNameNoDebug ("processorLduInterface")
processorLduInterface () noexcept=default
virtual ~processorLduInterface ()=default
template<class Type >
void send (const UPstream::commsTypes commsType, const UList< Type > &f) const
template<class Type >
void receive (const UPstream::commsTypes commsType, UList< Type > &f) const
template<class Type >
tmp< Field< Type > > receive (const UPstream::commsTypes commsType, const label size) const
template<class Type >
void compressedSend (const UPstream::commsTypes commsType, const UList< Type > &f) const
template<class Type >
void compressedReceive (const UPstream::commsTypes commsType, UList< Type > &f) const
template<class Type >
tmp< Field< Type > > compressedReceive (const UPstream::commsTypes commsType, const label size) const
template<class Type >
Foam::tmp< Foam::Field< Type > > receive (const UPstream::commsTypes commsType, const label size) const
template<class Type >
Foam::tmp< Foam::Field< Type > > compressedReceive (const UPstream::commsTypes commsType, const label size) const
Additional Inherited Members
Static Public Member Functions inherited from GAMGInterface
static autoPtr< GAMGInterface > New (const label index, const lduInterfacePtrsList &coarseInterfaces, const lduInterface &fineInterface, const labelField &localRestrictAddressing, const labelField &neighbourRestrictAddressing, const label fineLevelIndex, const label coarseComm)
static autoPtr< GAMGInterface > New (const word &coupleType, const label index, const lduInterfacePtrsList &coarseInterfaces, Istream &is)
Protected Member Functions inherited from GAMGInterface
GAMGInterface (const GAMGInterface &)=delete
void operator= (const GAMGInterface &)=delete
Protected Attributes inherited from GAMGInterface
const label index_
const lduInterfacePtrsList & coarseInterfaces_
labelList faceCells_
labelList faceRestrictAddressing_
Detailed Description
GAMG agglomerated processor interface.
Source files
processorGAMGInterface.H
processorGAMGInterface.C
Definition at line 48 of file processorGAMGInterface.H.
Constructor & Destructor Documentation
processorGAMGInterface() [1/3]
processorGAMGInterface (const label index, const lduInterfacePtrsList & coarseInterfaces, const lduInterface & fineInterface, const labelField & restrictAddressing, const labelField & neighbourRestrictAddressing, const label fineLevelIndex, const label coarseComm)
Definition at line 48 of file processorGAMGInterface.C.
References PtrList< T >::append(), GAMGInterface::faceCells_, GAMGInterface::faceRestrictAddressing_, forAll, processorGAMGInterface::myProcNo(), processorGAMGInterface::neighbProcNo(), Foam::refCast(), UPtrList< T >::size(), and List< T >::transfer().
processorGAMGInterface() [2/3]
processorGAMGInterface (const label index, const lduInterfacePtrsList & coarseInterfaces, const labelUList & faceCells, const labelUList & faceRestrictAddresssing, const label coarseComm, const label myProcNo, const label neighbProcNo, const tensorField & forwardT, const int tag)
Definition at line 131 of file processorGAMGInterface.C.
processorGAMGInterface() [3/3]
processorGAMGInterface (const label index, const lduInterfacePtrsList & coarseInterfaces, Istream & is)
Definition at line 159 of file processorGAMGInterface.C.
~processorGAMGInterface()
virtual ~processorGAMGInterface () virtual default
Member Function Documentation
TypeName()
TypeName ("processor")
initInternalFieldTransfer() [1/2]
void initInternalFieldTransfer (const Pstream::commsTypes commsType, const labelUList & iF) const virtual
Reimplemented from lduInterface.
Definition at line 177 of file processorGAMGInterface.C.
initInternalFieldTransfer() [2/2]
void initInternalFieldTransfer (const Pstream::commsTypes commsType, const labelUList & iF, const labelUList & faceCells) const virtual
Reimplemented from lduInterface.
Definition at line 187 of file processorGAMGInterface.C.
internalFieldTransfer()
Foam::tmp< Foam::labelField > internalFieldTransfer (const Pstream::commsTypes commsType, const labelUList & iF) const virtual
Implements lduInterface.
Definition at line 198 of file processorGAMGInterface.C.
comm()
virtual label comm () const inline virtual
Implements processorLduInterface.
Definition at line 158 of file processorGAMGInterface.H.
Referenced by processorGAMGInterfaceField::comm().
myProcNo()
virtual int myProcNo () const inline virtual
Implements processorLduInterface.
Definition at line 164 of file processorGAMGInterface.H.
Referenced by processorGAMGInterfaceField::myProcNo(), and processorGAMGInterface::processorGAMGInterface().
neighbProcNo()
virtual int neighbProcNo () const inline virtual
Implements processorLduInterface.
Definition at line 170 of file processorGAMGInterface.H.
Referenced by processorGAMGInterfaceField::neighbProcNo(), and processorGAMGInterface::processorGAMGInterface().
forwardT()
virtual const tensorField & forwardT () const inline virtual
Implements processorLduInterface.
Definition at line 176 of file processorGAMGInterface.H.
Referenced by processorGAMGInterfaceField::forwardT().
tag()
virtual int tag () const inline virtual
Implements processorLduInterface.
Definition at line 182 of file processorGAMGInterface.H.
write()
void write (Ostream & os) const virtual
Implements GAMGInterface.
Definition at line 210 of file processorGAMGInterface.C.
References os(), token::SPACE, and GAMGInterface::write().
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/interfaces/processorGAMGInterface/processorGAMGInterface.H
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/interfaces/processorGAMGInterface/processorGAMGInterface.C