OpenFOAM: uniformTotalPressureFvPatchScalarField Class Reference
uniformTotalPressureFvPatchScalarField Class Reference
Boundary conditions » Inlet | Boundary conditions » Outlet
This boundary condition provides a time-varying form of the uniform total pressure boundary condition Foam::totalPressureFvPatchField.
#include <uniformTotalPressureFvPatchScalarField.H>
Public Member Functions
TypeName ("uniformTotalPressure")
uniformTotalPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
uniformTotalPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
uniformTotalPressureFvPatchScalarField (const uniformTotalPressureFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
uniformTotalPressureFvPatchScalarField (const uniformTotalPressureFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
uniformTotalPressureFvPatchScalarField (const uniformTotalPressureFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
const word & UName () const
word & UName ()
scalar gamma () const
scalar & gamma ()
virtual void updateCoeffs (const vectorField &Up)
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
This boundary condition provides a time-varying form of the uniform total pressure boundary condition Foam::totalPressureFvPatchField.
Usage
Property Description Required Default value
U Velocity field name no U
phi Flux field name no phi
rho Density field name no rho
psi Compressibility field name no none
gamma (Cp/Cv) no 1
p0 Total pressure as a function of time yes
Example of the boundary condition specification:
    <patchName>
    {
        type            uniformTotalPressure;
        p0              uniform 1e5;
    }
The p0 entry is specified as a Function1 type, able to describe time varying functions.
See also
Foam::Function1Types Foam::uniformFixedValueFvPatchField Foam::totalPressureFvPatchField
Source files
uniformTotalPressureFvPatchScalarField.H
uniformTotalPressureFvPatchScalarField.C
Definition at line 114 of file uniformTotalPressureFvPatchScalarField.H.
Constructor & Destructor Documentation
uniformTotalPressureFvPatchScalarField() [1/5]
uniformTotalPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 30 of file uniformTotalPressureFvPatchScalarField.C.
uniformTotalPressureFvPatchScalarField() [2/5]
uniformTotalPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 47 of file uniformTotalPressureFvPatchScalarField.C.
References dict, and fvPatchField< scalar >::operator==().
uniformTotalPressureFvPatchScalarField() [3/5]
uniformTotalPressureFvPatchScalarField (const uniformTotalPressureFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 71 of file uniformTotalPressureFvPatchScalarField.C.
References fvPatchField< scalar >::operator==().
uniformTotalPressureFvPatchScalarField() [4/5]
uniformTotalPressureFvPatchScalarField (const uniformTotalPressureFvPatchScalarField & ptf)
Definition at line 97 of file uniformTotalPressureFvPatchScalarField.C.
uniformTotalPressureFvPatchScalarField() [5/5]
uniformTotalPressureFvPatchScalarField (const uniformTotalPressureFvPatchScalarField & ptf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 113 of file uniformTotalPressureFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("uniformTotalPressure")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 179 of file uniformTotalPressureFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 195 of file uniformTotalPressureFvPatchScalarField.H.
UName() [1/2]
const word & UName () const inline
Definition at line 212 of file uniformTotalPressureFvPatchScalarField.H.
UName() [2/2]
word & UName () inline
Definition at line 219 of file uniformTotalPressureFvPatchScalarField.H.
gamma() [1/2]
scalar gamma () const inline
Definition at line 225 of file uniformTotalPressureFvPatchScalarField.H.
gamma() [2/2]
scalar & gamma () inline
Definition at line 231 of file uniformTotalPressureFvPatchScalarField.H.
updateCoeffs() [1/2]
void updateCoeffs (const vectorField & Up) virtual
Definition at line 132 of file uniformTotalPressureFvPatchScalarField.C.
References Foam::dimDensity, Foam::dimPressure, Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::magSqr(), Foam::neg(), Foam::nl, Foam::operator==(), p0, Foam::pow(), and rho.
updateCoeffs() [2/2]
void updateCoeffs () virtual
Definition at line 209 of file uniformTotalPressureFvPatchScalarField.C.
write()
void write (Ostream & os) const virtual
Definition at line 215 of file uniformTotalPressureFvPatchScalarField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntry(), Ostream::writeEntryIfDifferent(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/uniformTotalPressure/uniformTotalPressureFvPatchScalarField.H
src/finiteVolume/fields/fvPatchFields/derived/uniformTotalPressure/uniformTotalPressureFvPatchScalarField.C