OpenFOAM: atmNutkWallFunctionFvPatchScalarField Class Reference
atmNutkWallFunctionFvPatchScalarField Class Reference
This boundary condition provides a wall constraint on the turbulent viscosity (i.e. nut) based on the turbulent kinetic energy (i.e. k) for atmospheric boundary layer modelling. It is designed to be used in conjunction with the atmBoundaryLayerInletVelocity boundary condition.
#include <atmNutkWallFunctionFvPatchScalarField.H>
Public Member Functions
TypeName ("atmNutkWallFunction")
atmNutkWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
atmNutkWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
atmNutkWallFunctionFvPatchScalarField (const atmNutkWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
atmNutkWallFunctionFvPatchScalarField (const atmNutkWallFunctionFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
atmNutkWallFunctionFvPatchScalarField (const atmNutkWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual void autoMap (const fvPatchFieldMapper &)
virtual void rmap (const fvPatchScalarField &, const labelList &)
virtual void write (Ostream &) const
Public Member Functions inherited from nutkWallFunctionFvPatchScalarField
TypeName ("nutkWallFunction")
nutkWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
nutkWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
nutkWallFunctionFvPatchScalarField (const nutkWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
nutkWallFunctionFvPatchScalarField (const nutkWallFunctionFvPatchScalarField &)
nutkWallFunctionFvPatchScalarField (const nutkWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< scalarField > yPlus () const
Public Member Functions inherited from nutWallFunctionFvPatchScalarField
TypeName ("nutWallFunction")
nutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
nutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &)
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
const wallFunctionCoefficients & wallCoeffs () const noexcept
virtual void updateCoeffs ()
Protected Member Functions
virtual tmp< scalarField > calcNut () const
void writeLocalEntries (Ostream &) const
Protected Member Functions inherited from nutkWallFunctionFvPatchScalarField
void writeLocalEntries (Ostream &) const
Protected Member Functions inherited from nutWallFunctionFvPatchScalarField
virtual const volVectorField & U (const turbulenceModel &turb) const
virtual void checkType ()
void writeLocalEntries (Ostream &) const
Additional Inherited Members
Static Public Member Functions inherited from nutWallFunctionFvPatchScalarField
static const nutWallFunctionFvPatchScalarField & nutw (const turbulenceModel &turbModel, const label patchi)
Protected Attributes inherited from nutWallFunctionFvPatchScalarField
word UName_
wallFunctionCoefficients wallCoeffs_
Detailed Description
This boundary condition provides a wall constraint on the turbulent viscosity (i.e. nut) based on the turbulent kinetic energy (i.e. k) for atmospheric boundary layer modelling. It is designed to be used in conjunction with the atmBoundaryLayerInletVelocity boundary condition.
The governing equation of the boundary condition:
where
= Friction velocity
= von Kármán constant
= Surface roughness length [m]
= Ground-normal coordinate
Required fields:
      nut    | Turbulent viscosity              [m2/s]
      k      | Turbulent kinetic energy         [m2/s2]
References:
        Theoretical expressions (tag:HW):
            Hargreaves, D. M., & Wright, N. G. (2007).
            On the use of the k–ε model in commercial CFD software to model
            the neutral atmospheric boundary layer.
            J. of wind engineering and industrial aerodynamics, 95(5), 355-369.
            DOI:10.1016/j.jweia.2006.08.002
Required fields:
      nut    | Turbulent viscosity              [m2/s]
      k      | Turbulent kinetic energy         [m2/s2]
Usage
Example of the boundary condition specification:
<patchName>
{
    // Mandatory entries
    type            atmNutkWallFunction;
    z0              <PatchFunction1<scalar>>;
    // Optional entries
    boundNut        <bool>;
    // Inherited entries
    ...
}
where the entries mean:
Property Description Type Reqd Deflt
type Type name: atmNutkWallFunction word yes -
z0 Surface roughness length [m] PatchFunction1<scalar> yes -
boundNut Flag to zero-bound nut near wall bool no false
The inherited entries are elaborated in:
nutkWallFunctionFvPatchScalarField.H
PatchFunction1.H
Note
boundNut entry is set false for backward compatibility reasons.
nutkAtmRoughWallFunction was renamed to atmNutkWallFunction.
Source files
atmNutkWallFunctionFvPatchScalarField.H
atmNutkWallFunctionFvPatchScalarField.C
Definition at line 164 of file atmNutkWallFunctionFvPatchScalarField.H.
Constructor & Destructor Documentation
atmNutkWallFunctionFvPatchScalarField() [1/5]
atmNutkWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 119 of file atmNutkWallFunctionFvPatchScalarField.C.
atmNutkWallFunctionFvPatchScalarField() [2/5]
atmNutkWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 145 of file atmNutkWallFunctionFvPatchScalarField.C.
atmNutkWallFunctionFvPatchScalarField() [3/5]
atmNutkWallFunctionFvPatchScalarField (const atmNutkWallFunctionFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 131 of file atmNutkWallFunctionFvPatchScalarField.C.
atmNutkWallFunctionFvPatchScalarField() [4/5]
atmNutkWallFunctionFvPatchScalarField (const atmNutkWallFunctionFvPatchScalarField & rwfpsf)
Definition at line 158 of file atmNutkWallFunctionFvPatchScalarField.C.
atmNutkWallFunctionFvPatchScalarField() [5/5]
atmNutkWallFunctionFvPatchScalarField (const atmNutkWallFunctionFvPatchScalarField & rwfpsf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 169 of file atmNutkWallFunctionFvPatchScalarField.C.
Member Function Documentation
calcNut()
tmp< scalarField > calcNut () const protected virtual
Reimplemented from nutkWallFunctionFvPatchScalarField.
Definition at line 37 of file atmNutkWallFunctionFvPatchScalarField.C.
References wallFunctionCoefficients::Cmu(), e, Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, IOobject::groupName(), k, wallFunctionCoefficients::kappa(), Foam::log(), Foam::max(), tmp< T >::New(), nutWallFunctionFvPatchScalarField::nutw(), Foam::pow025(), turbulenceModel::propertiesName, Foam::sqrt(), nutWallFunctionFvPatchScalarField::wallCoeffs_, y, and nutkWallFunctionFvPatchScalarField::yPlus().
writeLocalEntries()
void writeLocalEntries (Ostream & os) const protected
Definition at line 103 of file atmNutkWallFunctionFvPatchScalarField.C.
References os(), and Ostream::writeEntryIfDifferent().
Referenced by atmNutkWallFunctionFvPatchScalarField::write().
TypeName()
TypeName ("atmNutkWallFunction")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Reimplemented from nutkWallFunctionFvPatchScalarField.
Definition at line 230 of file atmNutkWallFunctionFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Reimplemented from nutkWallFunctionFvPatchScalarField.
Definition at line 246 of file atmNutkWallFunctionFvPatchScalarField.H.
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Definition at line 183 of file atmNutkWallFunctionFvPatchScalarField.C.
rmap()
void rmap (const fvPatchScalarField & ptf, const labelList & addr) virtual
Definition at line 197 of file atmNutkWallFunctionFvPatchScalarField.C.
write()
void write (Ostream & os) const virtual
Reimplemented from nutkWallFunctionFvPatchScalarField.
Definition at line 215 of file atmNutkWallFunctionFvPatchScalarField.C.
References os(), nutWallFunctionFvPatchScalarField::write(), atmNutkWallFunctionFvPatchScalarField::writeLocalEntries(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/atmosphericModels/derivedFvPatchFields/wallFunctions/atmNutkWallFunction/atmNutkWallFunctionFvPatchScalarField.H
src/atmosphericModels/derivedFvPatchFields/wallFunctions/atmNutkWallFunction/atmNutkWallFunctionFvPatchScalarField.C