OpenFOAM: symGaussSeidelSmoother Class Reference
symGaussSeidelSmoother Class Reference
Numerics » Matrix manipulation and solvers » Smoothers
A lduMatrix::smoother for symmetric Gauss-Seidel.
#include <symGaussSeidelSmoother.H>
Public Member Functions
TypeName ("symGaussSeidel")
symGaussSeidelSmoother (const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces)
virtual void smooth (solveScalarField &psi, const scalarField &Source, const direction cmpt, const label nSweeps) const
virtual void scalarSmooth (solveScalarField &psi, const solveScalarField &source, const direction cmpt, const label nSweeps) const
Public Member Functions inherited from lduMatrix::smoother
virtual const word & type () const =0
declareRunTimeSelectionTable (autoPtr, smoother, symMatrix,(const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces),(fieldName, matrix, interfaceBouCoeffs, interfaceIntCoeffs, interfaces))
declareRunTimeSelectionTable (autoPtr, smoother, asymMatrix,(const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces),(fieldName, matrix, interfaceBouCoeffs, interfaceIntCoeffs, interfaces))
smoother (const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces)
virtual ~smoother ()=default
const word & fieldName () const noexcept
const lduMatrix & matrix () const noexcept
const FieldField< Field, scalar > & interfaceBouCoeffs () const noexcept
const FieldField< Field, scalar > & interfaceIntCoeffs () const noexcept
const lduInterfaceFieldPtrsList & interfaces () const noexcept
Static Public Member Functions
static void smooth (const word &fieldName, solveScalarField &psi, const lduMatrix &matrix, const solveScalarField &source, const FieldField< Field, scalar > &interfaceBouCoeffs, const lduInterfaceFieldPtrsList &interfaces, const direction cmpt, const label nSweeps)
Static Public Member Functions inherited from lduMatrix::smoother
static word getName (const dictionary &)
static autoPtr< smoother > New (const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces, const dictionary &solverControls)
Additional Inherited Members
Protected Attributes inherited from lduMatrix::smoother
word fieldName_
const lduMatrix & matrix_
const FieldField< Field, scalar > & interfaceBouCoeffs_
const FieldField< Field, scalar > & interfaceIntCoeffs_
const lduInterfaceFieldPtrsList & interfaces_
Detailed Description
A lduMatrix::smoother for symmetric Gauss-Seidel.
Source files
symGaussSeidelSmoother.H
symGaussSeidelSmoother.C
Definition at line 50 of file symGaussSeidelSmoother.H.
Constructor & Destructor Documentation
symGaussSeidelSmoother()
symGaussSeidelSmoother (const word & fieldName, const lduMatrix & matrix, const FieldField< Field, scalar > & interfaceBouCoeffs, const FieldField< Field, scalar > & interfaceIntCoeffs, const lduInterfaceFieldPtrsList & interfaces)
Definition at line 41 of file symGaussSeidelSmoother.C.
Member Function Documentation
TypeName()
TypeName ("symGaussSeidel")
smooth() [1/2]
void smooth (const word & fieldName, solveScalarField & psi, const lduMatrix & matrix, const solveScalarField & source, const FieldField< Field, scalar > & interfaceBouCoeffs, const lduInterfaceFieldPtrsList & interfaces, const direction cmpt, const label nSweeps) static
Definition at line 63 of file symGaussSeidelSmoother.C.
References UPtrList< T >::begin(), UList< T >::begin(), lduMatrix::diag(), lduMatrix::initMatrixInterfaces(), lduMatrix::lduAddr(), lduMatrix::lower(), UPstream::nRequests(), psi, UPtrList< T >::size(), lduMatrix::updateMatrixInterfaces(), and lduMatrix::upper().
smooth() [2/2]
void smooth (solveScalarField & psi, const scalarField & Source, const direction cmpt, const label nSweeps) const virtual
Implements lduMatrix::smoother.
Definition at line 216 of file symGaussSeidelSmoother.C.
References psi.
scalarSmooth()
void scalarSmooth (solveScalarField & psi, const solveScalarField & source, const direction cmpt, const label nSweeps) const virtual
Implements lduMatrix::smoother.
Definition at line 194 of file symGaussSeidelSmoother.C.
References psi.
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/lduMatrix/smoothers/symGaussSeidel/symGaussSeidelSmoother.H
src/OpenFOAM/matrices/lduMatrix/smoothers/symGaussSeidel/symGaussSeidelSmoother.C