OpenFOAM: EBRSM< BasicTurbulenceModel > Class Template Reference
EBRSM< BasicTurbulenceModel > Class Template Reference
Turbulence models » RAS turbulence
Manceau (2015)'s elliptic-blending Reynolds-stress turbulence model for incompressible and compressible flows.
#include <EBRSM.H>
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from ReynoldsStress< RASModel< BasicTurbulenceModel > >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from RASModel< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("EBRSM")
EBRSM (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
virtual ~EBRSM ()=default
virtual tmp< volScalarField > epsilon () const
virtual bool read ()
virtual void correct ()
Public Member Functions inherited from ReynoldsStress< RASModel< BasicTurbulenceModel > >
Foam::tmp< Foam::fvVectorMatrix > DivDevRhoReff (const RhoFieldType &rho, volVectorField &U) const
ReynoldsStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~ReynoldsStress ()=default
virtual tmp< volScalarField > nut () const
virtual tmp< scalarField > nut (const label patchi) const
virtual tmp< volScalarField > k () const
virtual tmp< volSymmTensorField > R () const
virtual tmp< volSymmTensorField > devRhoReff () const
virtual tmp< volSymmTensorField > devRhoReff (const volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
virtual void validate ()
Public Member Functions inherited from RASModel< BasicTurbulenceModel >
TypeName ("RAS")
declareRunTimeSelectionTable (autoPtr, RASModel, dictionary,(const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName),(alpha, rho, U, alphaRhoPhi, phi, transport, propertiesName))
RASModel (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~RASModel ()=default
const dimensionedScalar & kMin () const noexcept
const dimensionedScalar & epsilonMin () const noexcept
const dimensionedScalar & omegaMin () const noexcept
dimensionedScalar & kMin () noexcept
dimensionedScalar & epsilonMin () noexcept
dimensionedScalar & omegaMin () noexcept
virtual const dictionary & coeffDict () const
virtual tmp< volScalarField > nuEff () const
virtual tmp< scalarField > nuEff (const label patchi) const
virtual tmp< volScalarField > omega () const
Public Member Functions inherited from RASModelBase
ClassName ("RASModelBase")
RASModelBase () noexcept=default
virtual ~RASModelBase ()=default
Additional Inherited Members
Static Public Member Functions inherited from RASModel< BasicTurbulenceModel >
static autoPtr< RASModel > New (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Protected Member Functions inherited from ReynoldsStress< RASModel< BasicTurbulenceModel > >
void boundNormalStress (volSymmTensorField &R) const
void correctWallShearStress (volSymmTensorField &R) const
void checkRealizabilityConditions (const volSymmTensorField &R) const
tmp< fvVectorMatrix > DivDevRhoReff (const RhoFieldType &rho, volVectorField &U) const
Protected Member Functions inherited from RASModel< BasicTurbulenceModel >
virtual void printCoeffs (const word &type)
RASModel (const RASModel &)=delete
void operator= (const RASModel &)=delete
Protected Attributes inherited from ReynoldsStress< RASModel< BasicTurbulenceModel > >
dimensionedScalar couplingFactor_
volSymmTensorField R_
volScalarField nut_
Protected Attributes inherited from RASModel< BasicTurbulenceModel >
dictionary RASDict_
Switch turbulence_
Switch printCoeffs_
dictionary coeffDict_
dimensionedScalar kMin_
dimensionedScalar epsilonMin_
dimensionedScalar omegaMin_
Detailed Description
template<class BasicTurbulenceModel>
class Foam::RASModels::EBRSM< BasicTurbulenceModel >
Manceau (2015)'s elliptic-blending Reynolds-stress turbulence model for incompressible and compressible flows.
References:
    Standard model (tag:M):
        Manceau, R. (2015).
        Recent progress in the development of the elliptic
        blending Reynolds-stress model.
        International Journal of Heat and Fluid Flow, 51, 195-220.
        DOI:10.1016/j.ijheatfluidflow.2014.09.002
    Simple gradient diffusion hypothesis (tag:LM):
        Lardeau, S., & Manceau, R. (2014).
        Computations of complex flow configurations using
        a modified elliptic-blending Reynolds-stress model.
        10th International ERCOFTAC Symposium on Engineering
        Turbulence Modelling and Measurements. Marbella, Spain.
        https://hal.archives-ouvertes.fr/hal-01051799
The default model coefficients are (M:p. 219):
    EBRSMCoeffs
    {
        g1          3.4;
        g1star      1.8;
        g3          0.8;
        g3star      1.3;
        g4          1.25;
        g5          0.2;
        Cmu         0.21;
        Ceps1       1.44;
        Ceps2       1.83;
        sigmaK      1.0;
        sigmaEps    1.15;
        A1          0.065;
        Ct          6.0;
        Cl          0.133;
        Ceta        80.0;
        Cstability  10.0;
        simpleGradientDiffusion  false;
    }
Note
g5 coefficient has been changed from its original value of 0.4 to 0.2 after obtaining better results in smooth-wall plane channel flow cases.
Source files
EBRSM.H
EBRSM.C
Definition at line 101 of file EBRSM.H.
Member Typedef Documentation
alphaField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 183 of file EBRSM.H.
rhoField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 184 of file EBRSM.H.
transportModel
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 185 of file EBRSM.H.
Constructor & Destructor Documentation
EBRSM()
template<class BasicTurbulenceModel > EBRSM (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Definition at line 135 of file EBRSM.C.
References Foam::bound(), ReynoldsStress< RASModel< BasicTurbulenceModel > >::boundNormalStress(), RASModel< BasicTurbulenceModel >::epsilonMin_, RASModel< BasicTurbulenceModel >::kMin_, RASModel< BasicTurbulenceModel >::printCoeffs(), and ReynoldsStress< RASModel< BasicTurbulenceModel > >::R_.
~EBRSM()
template<class BasicTurbulenceModel > virtual ~EBRSM () virtual default
Member Function Documentation
TypeName()
template<class BasicTurbulenceModel > TypeName ("EBRSM< BasicTurbulenceModel >")
epsilon()
template<class BasicTurbulenceModel > virtual tmp< volScalarField > epsilon () const inline virtual
Reimplemented from RASModel< BasicTurbulenceModel >.
Definition at line 215 of file EBRSM.H.
read()
template<class BasicTurbulenceModel > bool read () virtual
Implements ReynoldsStress< RASModel< BasicTurbulenceModel > >.
Definition at line 365 of file EBRSM.C.
References Foam::read().
correct()
template<class BasicTurbulenceModel > void correct () virtual
Implements ReynoldsStress< RASModel< BasicTurbulenceModel > >.
Definition at line 399 of file EBRSM.C.
References alpha, B, Foam::bound(), PtrList< T >::clear(), correct(), D, Foam::fvm::ddt(), Foam::devTwoSymm(), Foam::fvm::div(), fvOptions, Foam::fvc::grad(), Foam::I, Foam::fvm::laplacian(), Foam::mag(), n, options::New(), Foam::oneThirdI, Foam::pow3(), R, rho, solve(), Foam::fvm::Sp(), Foam::sqr(), Foam::symm(), GeometricField< Type, PatchField, GeoMesh >::T(), Foam::tr(), Foam::twoSymm(), Foam::twoThirdsI, and U.
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/RAS/EBRSM/EBRSM.H
src/TurbulenceModels/turbulenceModels/RAS/EBRSM/EBRSM.C