OpenFOAM: polyTopoChange Class Reference
polyTopoChange Class Reference
Direct mesh changes based on v1.3 polyTopoChange syntax.
#include <polyTopoChange.H>
Public Member Functions
ClassName ("polyTopoChange")
polyTopoChange (const label nPatches, const bool strict=true)
polyTopoChange (const polyMesh &mesh, const bool strict=true)
const DynamicList< point > & points () const
const DynamicList< face > & faces () const
const DynamicList< label > & region () const
const DynamicList< label > & faceOwner () const
const DynamicList< label > & faceNeighbour () const
bool pointRemoved (const label pointi) const
bool faceRemoved (const label facei) const
bool cellRemoved (const label celli) const
void clear ()
void addMesh (const polyMesh &mesh, const labelUList &patchMap, const labelUList &pointZoneMap, const labelUList &faceZoneMap, const labelUList &cellZoneMap)
void setCapacity (const label nPoints, const label nFaces, const label nCells)
void shrink ()
void movePoints (const pointField &newPoints)
label setAction (const topoAction &action)
label addPoint (const point &pt, const label masterPointID, const label zoneID, const bool inCell)
void modifyPoint (const label pointi, const point &pt, const label zoneID, const bool inCell)
void removePoint (const label pointi, const label mergePointi)
label addFace (const face &f, const label own, const label nei, const label masterPointID, const label masterEdgeID, const label masterFaceID, const bool flipFaceFlux, const label patchID, const label zoneID, const bool zoneFlip)
void modifyFace (const face &f, const label facei, const label own, const label nei, const bool flipFaceFlux, const label patchID, const label zoneID, const bool zoneFlip)
void removeFace (const label facei, const label mergeFacei)
label addCell (const label masterPointID, const label masterEdgeID, const label masterFaceID, const label masterCellID, const label zoneID)
void modifyCell (const label celli, const label zoneID)
void removeCell (const label celli, const label mergeCelli)
void setNumPatches (const label nPatches)
autoPtr< mapPolyMesh > changeMesh (polyMesh &mesh, const labelUList &patchMap, const bool inflate, const bool syncParallel=true, const bool orderCells=false, const bool orderPoints=false)
autoPtr< mapPolyMesh > changeMesh (polyMesh &mesh, const bool inflate, const bool syncParallel=true, const bool orderCells=false, const bool orderPoints=false)
template<class Type >
autoPtr< mapPolyMesh > makeMesh (autoPtr< Type > &newMesh, const IOobject &io, const polyMesh &mesh, const labelUList &patchMap, const bool syncParallel=true, const bool orderCells=false, const bool orderPoints=false)
template<class Type >
autoPtr< mapPolyMesh > makeMesh (autoPtr< Type > &newMesh, const IOobject &io, const polyMesh &mesh, const bool syncParallel=true, const bool orderCells=false, const bool orderPoints=false)
template<class Type >
Foam::autoPtr< Foam::mapPolyMesh > makeMesh (autoPtr< Type > &newMeshPtr, const IOobject &io, const polyMesh &mesh, const labelUList &patchMap, const bool syncParallel, const bool orderCells, const bool orderPoints)
template<class Type >
Foam::autoPtr< Foam::mapPolyMesh > makeMesh (autoPtr< Type > &newMeshPtr, const IOobject &io, const polyMesh &mesh, const bool syncParallel, const bool orderCells, const bool orderPoints)
Detailed Description
Direct mesh changes based on v1.3 polyTopoChange syntax.
Instead of recording changes and executing them all in one go (as did v1.3 polyTopoChange) this class actually holds the current points/faces/cells and does the change immediately. It can be asked to compress out all unused points/faces/cells and renumber everything to be consistent.
Note:
polyTopoChange can be copied.
adding a face using non-existing cells causes all intermediate cells to be added. So always first add cells/points and then faces. (or set strict checking)
strict checking:
any added/modified face can only use already existing vertices
any added face can only use already existing cells
no item can be removed more than once.
removed cell: cell set to 0 faces.
removed face: face set to 0 vertices.
removed point: coordinate set to vector::max (VGREAT,VGREAT,VGREAT). Note that this might give problems if this value is used already. To see if point is equal to above value we don't use == (which might give problems with roundoff error) but instead compare the individual component with >.
coupled patches: the reorderCoupledFaces routine (borrowed from the couplePatches utility) reorders coupled patch faces and uses the cyclicPolyPatch,processorPolyPatch functionality.
Source files
polyTopoChange.H
polyTopoChange.C
polyTopoChangeI.H
polyTopoChangeTemplates.C
Definition at line 95 of file polyTopoChange.H.
Constructor & Destructor Documentation
polyTopoChange() [1/2]
polyTopoChange (const label nPatches, const bool strict = true)
Definition at line 2150 of file polyTopoChange.C.
polyTopoChange() [2/2]
polyTopoChange (const polyMesh & mesh, const bool strict = true)
Definition at line 2181 of file polyTopoChange.C.
References polyTopoChange::addMesh(), Foam::identity(), and mesh.
Member Function Documentation
ClassName()
ClassName ("polyTopoChange")
points()
const DynamicList< point > & points () const inline
Definition at line 446 of file polyTopoChange.H.
Referenced by addPatchCellLayer::setRefinement(), duplicatePoints::setRefinement(), and meshRefinement::splitFacesUndo().
faces()
const DynamicList< face > & faces () const inline
Definition at line 451 of file polyTopoChange.H.
Referenced by meshRefinement::splitFacesUndo().
region()
const DynamicList< label > & region () const inline
Definition at line 456 of file polyTopoChange.H.
faceOwner()
const DynamicList< label > & faceOwner () const inline
Definition at line 461 of file polyTopoChange.H.
faceNeighbour()
const DynamicList< label > & faceNeighbour () const inline
Definition at line 466 of file polyTopoChange.H.
pointRemoved()
bool pointRemoved (const label pointi) const inline
Definition at line 25 of file polyTopoChangeI.H.
References VectorSpace< Form, Cmpt, Ncmpts >::max, Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
faceRemoved()
bool faceRemoved (const label facei) const inline
Definition at line 36 of file polyTopoChangeI.H.
References UPtrList< T >::empty().
cellRemoved()
bool cellRemoved (const label celli) const inline
Definition at line 42 of file polyTopoChangeI.H.
clear()
void clear ()
Definition at line 2226 of file polyTopoChange.C.
addMesh()
void addMesh (const polyMesh & mesh, const labelUList & patchMap, const labelUList & pointZoneMap, const labelUList & faceZoneMap, const labelUList & cellZoneMap)
Definition at line 2256 of file polyTopoChange.C.
References Foam::abort(), polyMesh::boundaryMesh(), primitiveMesh::cellCentres(), polyMesh::cellZones(), Foam::endl(), faceLabels(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), polyMesh::faces(), polyMesh::faceZones(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::max(), mesh, IOobject::name(), primitiveMesh::nCells(), primitiveMesh::nInternalFaces(), primitiveMesh::nPoints(), patches, pointLabels(), points, polyMesh::points(), polyMesh::pointZones(), pp(), PtrList< T >::resize(), UPtrList< T >::size(), and WarningInFunction.
Referenced by polyTopoChange::polyTopoChange().
setCapacity()
void setCapacity (const label nPoints, const label nFaces, const label nCells)
Definition at line 2461 of file polyTopoChange.C.
References nPoints, and PtrList< T >::resize().
Referenced by fvMeshAdder::add(), and meshRefinement::splitFacesUndo().
shrink()
void shrink ()
Definition at line 904 of file polyTopoChange.C.
Referenced by snappyLayerDriver::addLayers().
movePoints()
void movePoints (const pointField & newPoints)
Definition at line 2693 of file polyTopoChange.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, UPtrList< T >::size(), and UList< T >::size().
setAction()
Foam::label setAction (const topoAction & action)
Definition at line 2494 of file polyTopoChange.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Referenced by meshRefinement::mergeBaffles(), polyMeshAdder::mergePoints(), removeCells::setRefinement(), removePoints::setRefinement(), meshCutter::setRefinement(), addPatchCellLayer::setRefinement(), meshCutAndRemove::setRefinement(), hexRef8::setRefinement(), faceCollapser::setRefinement(), removeFaces::setRefinement(), combineFaces::setRefinement(), boundaryCutter::setRefinement(), removePoints::setUnrefinement(), and combineFaces::setUnrefinement().
addPoint()
Foam::label addPoint (const point & pt, const label masterPointID, const label zoneID, const bool inCell)
Definition at line 2622 of file polyTopoChange.C.
References PtrList< T >::append(), and UPtrList< T >::size().
Referenced by polyMeshAdder::add(), tetDecomposer::setRefinement(), duplicatePoints::setRefinement(), and createShellMesh::setRefinement().
modifyPoint()
void modifyPoint (const label pointi, const point & pt, const label zoneID, const bool inCell)
Definition at line 2650 of file polyTopoChange.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, and UPtrList< T >::size().
Referenced by edgeCollapser::setRefinement().
removePoint()
void removePoint (const label pointi, const label mergePointi)
Definition at line 2711 of file polyTopoChange.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, VectorSpace< Form, Cmpt, Ncmpts >::max, Foam::nl, and UPtrList< T >::size().
Referenced by polyMeshAdder::mergePoints(), and edgeCollapser::setRefinement().
addFace()
Foam::label addFace (const face & f, const label own, const label nei, const label masterPointID, const label masterEdgeID, const label masterFaceID, const bool flipFaceFlux, const label patchID, const label zoneID, const bool zoneFlip)
Definition at line 2759 of file polyTopoChange.C.
References PtrList< T >::append(), f(), patchID, PtrList< T >::set(), and UPtrList< T >::size().
Referenced by polyMeshAdder::add(), meshRefinement::doSplitFaces(), and createShellMesh::setRefinement().
modifyFace()
void modifyFace (const face & f, const label facei, const label own, const label nei, const bool flipFaceFlux, const label patchID, const label zoneID, const bool zoneFlip)
Definition at line 2823 of file polyTopoChange.C.
References f(), patchID, and PtrList< T >::set().
Referenced by meshRefinement::doSplitFaces(), addPatchCellLayer::setRefinement(), edgeCollapser::setRefinement(), duplicatePoints::setRefinement(), and meshRefinement::splitFacesUndo().
removeFace()
void removeFace (const label facei, const label mergeFacei)
Definition at line 2860 of file polyTopoChange.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, and UPtrList< T >::size().
Referenced by edgeCollapser::setRefinement(), and meshRefinement::splitFacesUndo().
addCell()
Foam::label addCell (const label masterPointID, const label masterEdgeID, const label masterFaceID, const label masterCellID, const label zoneID)
Definition at line 2907 of file polyTopoChange.C.
References PtrList< T >::append(), and UPtrList< T >::size().
Referenced by polyMeshAdder::add(), tetDecomposer::setRefinement(), and createShellMesh::setRefinement().
modifyCell()
void modifyCell (const label celli, const label zoneID)
Definition at line 2944 of file polyTopoChange.C.
removeCell()
void removeCell (const label celli, const label mergeCelli)
Definition at line 2954 of file polyTopoChange.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, and UPtrList< T >::size().
Referenced by edgeCollapser::setRefinement().
setNumPatches()
void setNumPatches (const label nPatches) inline
Definition at line 48 of file polyTopoChangeI.H.
References nPatches.
changeMesh() [1/2]
Foam::autoPtr< Foam::mapPolyMesh > changeMesh (polyMesh & mesh, const labelUList & patchMap, const bool inflate, const bool syncParallel = true, const bool orderCells = false, const bool orderPoints = false)
Definition at line 2992 of file polyTopoChange.C.
References polyMesh::boundaryMesh(), primitiveMesh::cellVolumes(), polyMesh::cellZones(), Foam::endl(), polyMesh::faceZones(), forAll, mesh, primitiveMesh::nCells(), autoPtr< T >::New(), newPointi, primitiveMesh::nFaces(), Foam::nl, primitiveMesh::nPoints(), polyMesh::points(), polyMesh::pointZones(), Foam::Pout, polyMesh::resetPrimitives(), UPtrList< T >::size(), UList< T >::size(), polyMesh::topoChanging(), Foam::HashSetOps::used(), and Foam::Zero.
Referenced by fvMeshAdder::add(), snappyLayerDriver::addLayers(), snappyLayerDriver::addLayersSinglePass(), meshRefinement::createBaffles(), meshRefinement::directionalRefine(), meshRefinement::doRemoveCells(), meshRefinement::doRemovePoints(), meshRefinement::doRestorePoints(), meshRefinement::dupNonManifoldPoints(), meshRefinement::mergeBaffles(), meshRefinement::mergePatchFaces(), meshRefinement::mergePatchFacesUndo(), meshRefinement::mergePoints(), dynamicRefineFvMesh::refine(), meshRefinement::refine(), refinementIterator::setRefinement(), meshRefinement::splitFacesUndo(), dynamicRefineFvMesh::unrefine(), and meshRefinement::zonify().
changeMesh() [2/2]
Foam::autoPtr< Foam::mapPolyMesh > changeMesh (polyMesh & mesh, const bool inflate, const bool syncParallel = true, const bool orderCells = false, const bool orderPoints = false)
Definition at line 3258 of file polyTopoChange.C.
References polyMesh::boundaryMesh(), Foam::identity(), mesh, and UPtrList< T >::size().
makeMesh() [1/4]
template<class Type > autoPtr< mapPolyMesh > makeMesh (autoPtr< Type > & newMesh, const IOobject & io, const polyMesh & mesh, const labelUList & patchMap, const bool syncParallel = true, const bool orderCells = false, const bool orderPoints = false)
Referenced by snappyLayerDriver::addLayers().
makeMesh() [2/4]
template<class Type > autoPtr< mapPolyMesh > makeMesh (autoPtr< Type > & newMesh, const IOobject & io, const polyMesh & mesh, const bool syncParallel = true, const bool orderCells = false, const bool orderPoints = false)
makeMesh() [3/4]
template<class Type > Foam::autoPtr< Foam::mapPolyMesh > makeMesh (autoPtr< Type > & newMeshPtr, const IOobject & io, const polyMesh & mesh, const labelUList & patchMap, const bool syncParallel, const bool orderCells, const bool orderPoints)
Definition at line 97 of file polyTopoChangeTemplates.C.
References polyMesh::boundaryMesh(), primitiveMesh::cellVolumes(), polyMesh::cellZones(), Foam::endl(), polyMesh::faceZones(), forAll, io(), mesh, Foam::name(), primitiveMesh::nCells(), autoPtr< T >::New(), primitiveMesh::nFaces(), Foam::nl, primitiveMesh::nPoints(), word::null, polyMesh::pointZones(), Foam::Pout, PtrList< T >::set(), UPtrList< T >::size(), UList< T >::size(), and Foam::HashSetOps::used().
makeMesh() [4/4]
template<class Type > Foam::autoPtr< Foam::mapPolyMesh > makeMesh (autoPtr< Type > & newMeshPtr, const IOobject & io, const polyMesh & mesh, const bool syncParallel, const bool orderCells, const bool orderPoints)
Definition at line 417 of file polyTopoChangeTemplates.C.
References polyMesh::boundaryMesh(), Foam::identity(), io(), mesh, and UPtrList< T >::size().
The documentation for this class was generated from the following files:
src/meshTools/polyTopoChange/polyTopoChange.H
src/meshTools/polyTopoChange/polyTopoChange.C
src/meshTools/polyTopoChange/polyTopoChangeI.H
src/meshTools/polyTopoChange/polyTopoChangeTemplates.C