OpenFOAM: flowRateOutletVelocityFvPatchVectorField Class Reference
flowRateOutletVelocityFvPatchVectorField Class Reference
Boundary conditions » Outlet
Velocity outlet boundary condition which corrects the extrapolated velocity to match the specified flow rate.
#include <flowRateOutletVelocityFvPatchVectorField.H>
Public Member Functions
TypeName ("flowRateOutletVelocity")
flowRateOutletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
flowRateOutletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
flowRateOutletVelocityFvPatchVectorField (const flowRateOutletVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
flowRateOutletVelocityFvPatchVectorField (const flowRateOutletVelocityFvPatchVectorField &)
virtual tmp< fvPatchVectorField > clone () const
flowRateOutletVelocityFvPatchVectorField (const flowRateOutletVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
Velocity outlet boundary condition which corrects the extrapolated velocity to match the specified flow rate.
For a mass-based flux:
the flow rate should be provided in kg/s
if rho is "none" the flow rate is in m^3/s
otherwise rho should correspond to the name of the density field
if the density field cannot be found in the database, the user must specify the outlet density using the rhoOutlet entry
For a volumetric-based flux:
the flow rate is in m^3/s
Usage
Property Description Required Default value
massFlowRate mass flow rate [kg/s] no
volumetricFlowRate volumetric flow rate [m^3/s] no
rho density field name no rho
rhoOutlet outlet density no
Example of the boundary condition specification for a volumetric flow rate:
    <patchName>
    {
        type                flowRateOutletVelocity;
        volumetricFlowRate  0.2;
        value               uniform (0 0 0);
    }
Example of the boundary condition specification for a mass flow rate:
    <patchName>
    {
        type                flowRateOutletVelocity;
        massFlowRate        0.2;
        rhoOutlet           1.0;
        value               uniform (0 0 0);
    }
The flowRate entry is a Function1 of time, see Foam::Function1Types.
Note
rhoOutlet is required for the case of a mass flow rate, where the density field is not available at start-up
The value is positive out of the domain (as an outlet)
May not work correctly for transonic outlets
Strange behaviour with potentialFoam since the U equation is not solved
See also
Foam::fixedValueFvPatchField Foam::Function1Types Foam::flowRateInletVelocityFvPatchVectorField
Source files
flowRateOutletVelocityFvPatchVectorField.H
flowRateOutletVelocityFvPatchVectorField.C
Definition at line 130 of file flowRateOutletVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
flowRateOutletVelocityFvPatchVectorField() [1/5]
flowRateOutletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Definition at line 29 of file flowRateOutletVelocityFvPatchVectorField.C.
flowRateOutletVelocityFvPatchVectorField() [2/5]
flowRateOutletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Definition at line 44 of file flowRateOutletVelocityFvPatchVectorField.C.
References UPstream::blocking, dict, Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, Function1< Type >::NewIfPresent(), and Foam::nl.
flowRateOutletVelocityFvPatchVectorField() [3/5]
flowRateOutletVelocityFvPatchVectorField (const flowRateOutletVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 88 of file flowRateOutletVelocityFvPatchVectorField.C.
flowRateOutletVelocityFvPatchVectorField() [4/5]
flowRateOutletVelocityFvPatchVectorField (const flowRateOutletVelocityFvPatchVectorField & ptf)
Definition at line 105 of file flowRateOutletVelocityFvPatchVectorField.C.
flowRateOutletVelocityFvPatchVectorField() [5/5]
flowRateOutletVelocityFvPatchVectorField (const flowRateOutletVelocityFvPatchVectorField & ptf, const DimensionedField< vector, volMesh > & iF)
Definition at line 119 of file flowRateOutletVelocityFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("flowRateOutletVelocity")
clone() [1/2]
virtual tmp< fvPatchVectorField > clone () const inline virtual
Definition at line 197 of file flowRateOutletVelocityFvPatchVectorField.H.
clone() [2/2]
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Definition at line 213 of file flowRateOutletVelocityFvPatchVectorField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 178 of file flowRateOutletVelocityFvPatchVectorField.C.
References Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
write()
void write (Ostream & os) const virtual
Definition at line 218 of file flowRateOutletVelocityFvPatchVectorField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntryIfDifferent(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/flowRateOutletVelocity/flowRateOutletVelocityFvPatchVectorField.H
src/finiteVolume/fields/fvPatchFields/derived/flowRateOutletVelocity/flowRateOutletVelocityFvPatchVectorField.C