OpenFOAM: CelikNuIndex Class Reference
CelikNuIndex Class Reference
Computes a single-mesh resolution index according to Celik et al.'s index using effective viscosity, which is used as a LES/DES quality/post verification metric that does not require any experimental or DNS data.
#include <CelikNuIndex.H>
Public Member Functions
TypeName ("CelikNuIndex")
CelikNuIndex (const word &name, const fvMesh &mesh, const dictionary &dict)
CelikNuIndex (const CelikNuIndex &)=delete
void operator= (const CelikNuIndex &)=delete
virtual ~CelikNuIndex ()=default
virtual bool read (const dictionary &dict)
virtual bool execute ()
virtual bool write ()
Public Member Functions inherited from resolutionIndexModel
TypeName ("resolutionIndexModel")
declareRunTimeSelectionTable (autoPtr, resolutionIndexModel, dictionary,(const word &name, const fvMesh &mesh, const dictionary &dict),(name, mesh, dict))
resolutionIndexModel (const word &name, const fvMesh &mesh, const dictionary &dict)
resolutionIndexModel (const resolutionIndexModel &)=delete
void operator= (const resolutionIndexModel &)=delete
virtual ~resolutionIndexModel ()=default
const fvMesh & mesh () const noexcept
const word & resultName () const noexcept
Additional Inherited Members
Static Public Member Functions inherited from resolutionIndexModel
static autoPtr< resolutionIndexModel > New (const word &name, const fvMesh &mesh, const dictionary &dict)
Protected Member Functions inherited from resolutionIndexModel
template<class GeoFieldType >
GeoFieldType & getOrReadField (const word &fieldName) const
tmp< volScalarField > V () const
Detailed Description
Computes a single-mesh resolution index according to Celik et al.'s index using effective viscosity, which is used as a LES/DES quality/post verification metric that does not require any experimental or DNS data.
with
where
= Celik et al.'s index [-]
= Empirical constant [-]
= Effective eddy viscosity [m^2/s]
= Numerical eddy viscosity [m^2/s]
= Subgrid-scale eddy viscosity [m^2/s]
= Kinematic viscosity of fluid [m^2/s]
= Empirical exponent [-]
= Numerical turbulent kinetic energy [m^2/s^2]
= Empirical constant [-]
= Filter length scale [m]
= Empirical constant [-]
= Characteristic length scale with [m]
= Cell volume [m^3]
= Subgrid-scale turbulent kinetic energy [m^2/s^2]
Criterion for acceptable-quality resolution:
Required fields:
      k        | Subgrid scale turbulent kinetic energy [m^2/s^2]
      delta    | Filter length                          [m]
      nu       | Kinematic viscosity                    [m^2/s]
      nut      | Subgrid-scale eddy viscosity           [m^2/s]
References:
        Governing equations (tag:CCY):
            Celik, I. B., Cehreli Z. N., Yavuz I. (2005).
            Index of resolution quality for large eddy simulations.
            Journal of Fluids Engineering. 127:949–958.
            DOI:10.1115/1.1990201
        Governing equations (tag:CKJ):
            Celik, I., Klein, M., & Janicka, J. (2009).
            Assessment measures for engineering LES applications.
            Journal of fluids engineering, 131(3).
            DOI:10.1115/1.3059703
Usage
Minimal example by using system/controlDict.functions:
resolutionIndex1
{
    // Inherited entries
    ...
    model       CelikNuIndex;
    // Optional entries
    alphaNu     <scalar>;
    n           <scalar>;
    Cnu         <scalar>;
    Cn          <scalar>;
    k           <word>;
    delta       <word>;
    nu          <word>;
    nut         <word>;
}
where the entries mean:
Property Description Type Reqd Deflt
model Model name: CelikNuIndex word yes -
alphaNu Empirical constant scalar no 0.05
n Empirical exponent scalar no 0.53
Cnu Empirical constant scalar no 0.1
Cn Empirical constant scalar no 1.0
k
Name of subgrid-scale turbulent kinetic energy field
word no k
delta Name of filter field word no delta
nu Name of kinematic viscosity field word no nu
nut Name of subgrid-scale eddy viscosity field word no nut
Source files
CelikNuIndex.H
CelikNuIndex.C
Definition at line 270 of file CelikNuIndex.H.
Constructor & Destructor Documentation
CelikNuIndex() [1/2]
CelikNuIndex (const word & name, const fvMesh & mesh, const dictionary & dict)
Definition at line 66 of file CelikNuIndex.C.
References dict, and CelikNuIndex::read().
CelikNuIndex() [2/2]
CelikNuIndex (const CelikNuIndex &) delete
~CelikNuIndex()
virtual ~CelikNuIndex () virtual default
Member Function Documentation
TypeName()
TypeName ("CelikNuIndex")
operator=()
void operator= (const CelikNuIndex &) delete
read()
bool read (const dictionary & dict) virtual
Reimplemented from resolutionIndexModel.
Definition at line 89 of file CelikNuIndex.C.
References dict, and resolutionIndexModel::read().
Referenced by CelikNuIndex::CelikNuIndex().
execute()
bool execute () virtual
Implements resolutionIndexModel.
Definition at line 110 of file CelikNuIndex.C.
References nu, and Foam::pow().
write()
bool write () virtual
Implements resolutionIndexModel.
Definition at line 129 of file CelikNuIndex.C.
References Foam::endl(), Foam::Info, Foam::tab, and Ostream::write().
The documentation for this class was generated from the following files:
src/functionObjects/field/resolutionIndex/resolutionIndexModels/CelikNuIndex/CelikNuIndex.H
src/functionObjects/field/resolutionIndex/resolutionIndexModels/CelikNuIndex/CelikNuIndex.C