OpenFOAM: PointIndexHit< PointType > Class Template Reference
PointIndexHit< PointType > Class Template Reference
This class describes the interaction of an object (often a face) and a point. It carries the info of a successful hit and (if successful), returns the interaction point.
#include <pointIndexHit.H>
Public Types
typedef PointType point_type
Public Member Functions
PointIndexHit ()
PointIndexHit (const point_type &p)
PointIndexHit (const PointHit< point_type > &p, label index=-1)
PointIndexHit (const PointIndexHit< point_type > &p, label index)
PointIndexHit (bool success, const point_type &p, label index)
PointIndexHit (Istream &is)
bool hit () const noexcept
label index () const noexcept
const point_type & point () const noexcept
point_type & point () noexcept
const point_type & hitPoint () const
const point_type & missPoint () const
const point_type & rawPoint () const noexcept
point_type & rawPoint () noexcept
void setHit () noexcept
void setMiss () noexcept
void setPoint (const point_type &p)
void setIndex (const label index) noexcept
void hitPoint (const point_type &p)
void hitPoint (const point_type &p, const label index)
void write (Ostream &os)
bool operator== (const PointIndexHit &rhs) const
bool operator!= (const PointIndexHit &rhs) const
Friends
Ostream & operator<< (Ostream &os, const PointIndexHit &pHit)
Istream & operator>> (Istream &is, PointIndexHit &pHit)
Detailed Description
template<class PointType>
class Foam::PointIndexHit< PointType >
This class describes the interaction of an object (often a face) and a point. It carries the info of a successful hit and (if successful), returns the interaction point.
Like pointHit but carries object (eg, face, cell, edge etc.) index
Definition at line 66 of file pointIndexHit.H.
Member Typedef Documentation
point_type
template<class PointType > typedef PointType point_type
Definition at line 85 of file pointIndexHit.H.
Constructor & Destructor Documentation
PointIndexHit() [1/6]
template<class PointType > PointIndexHit () inline
Definition at line 91 of file pointIndexHit.H.
PointIndexHit() [2/6]
template<class PointType > PointIndexHit (const point_type & p) inline explicit
Definition at line 99 of file pointIndexHit.H.
PointIndexHit() [3/6]
template<class PointType > PointIndexHit (const PointHit< point_type > & p, label index = -1) inline explicit
Definition at line 107 of file pointIndexHit.H.
PointIndexHit() [4/6]
template<class PointType > PointIndexHit (const PointIndexHit< point_type > & p, label index) inline
Definition at line 115 of file pointIndexHit.H.
PointIndexHit() [5/6]
template<class PointType > PointIndexHit (bool success, const point_type & p, label index) inline
Definition at line 123 of file pointIndexHit.H.
PointIndexHit() [6/6]
template<class PointType > PointIndexHit (Istream & is) inline explicit
Definition at line 131 of file pointIndexHit.H.
Member Function Documentation
hit()
template<class PointType > bool hit () const inline noexcept
Definition at line 142 of file pointIndexHit.H.
Referenced by nearestFaceAMI::calculate(), patchProbes::findElements(), mapNearestMethod::findInitialSeeds(), distributedTriSurfaceMesh::findNearest(), meshSearch::findNearestBoundaryFace(), refinementFeatures::findNearestEdge(), refinementFeatures::findNearestPoint(), refinementFeatures::findNearestRegionEdge(), surfaceFeatures::nearestEdges(), surfaceFeatures::nearestSamples(), surfaceFeatures::nearestSamples(), surfaceFeatures::nearestSurfEdge(), surfaceFeatures::nearestSurfEdge(), powerLawLopesdaCostaZone::powerLawLopesdaCostaZone(), and triSurfaceTools::trackToEdge().
index()
template<class PointType > label index () const inline noexcept
Definition at line 148 of file pointIndexHit.H.
Referenced by nearestFaceAMI::calculate(), patchProbes::findElements(), mapNearestMethod::findInitialSeeds(), searchableBox::findLine(), distributedTriSurfaceMesh::findNearest(), meshSearch::findNearestBoundaryFace(), refinementFeatures::findNearestEdge(), refinementFeatures::findNearestPoint(), refinementFeatures::findNearestRegionEdge(), treeDataFace::getVolumeType(), treeDataPrimitivePatch< PatchType >::getVolumeType(), treeDataPrimitivePatch< PatchType >::getVolumeType(), PointIndexHit< PointType >::hitPoint(), surfaceFeatures::nearestEdges(), surfaceFeatures::nearestSamples(), surfaceFeatures::nearestSamples(), surfaceFeatures::nearestSurfEdge(), surfaceFeatures::nearestSurfEdge(), surfaceLocation::normal(), PointIndexHit< PointType >::setIndex(), and triSurfaceTools::trackToEdge().
point() [1/2]
template<class PointType > const point_type & point () const inline noexcept
Definition at line 154 of file pointIndexHit.H.
Referenced by patchProbes::findElements(), searchableBox::findLine(), distributedTriSurfaceMesh::findNearest(), refinementFeatures::findNearestEdge(), searchableBox::findNearestOnEdge(), refinementFeatures::findNearestPoint(), refinementFeatures::findNearestRegionEdge(), surfaceFeatures::nearestEdges(), surfaceFeatures::nearestSamples(), surfaceFeatures::nearestSurfEdge(), powerLawLopesdaCostaZone::powerLawLopesdaCostaZone(), and triSurfaceTools::trackToEdge().
point() [2/2]
template<class PointType > point_type & point () inline noexcept
Definition at line 160 of file pointIndexHit.H.
hitPoint() [1/3]
template<class PointType > const point_type & hitPoint () const inline
Definition at line 166 of file pointIndexHit.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
missPoint()
template<class PointType > const point_type & missPoint () const inline
Definition at line 178 of file pointIndexHit.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
rawPoint() [1/2]
template<class PointType > const point_type & rawPoint () const inline noexcept
Definition at line 191 of file pointIndexHit.H.
rawPoint() [2/2]
template<class PointType > point_type & rawPoint () inline noexcept
Definition at line 195 of file pointIndexHit.H.
setHit()
template<class PointType > void setHit () inline noexcept
Definition at line 201 of file pointIndexHit.H.
Referenced by triSurfaceTools::classify(), and searchableBox::findLine().
setMiss()
template<class PointType > void setMiss () inline noexcept
Definition at line 207 of file pointIndexHit.H.
Referenced by triSurfaceTools::classify(), searchableBox::findNearestOnEdge(), and triSurfaceTools::trackToEdge().
setPoint()
template<class PointType > void setPoint (const point_type & p) inline
Definition at line 213 of file pointIndexHit.H.
References p.
Referenced by triSurfaceTools::classify().
setIndex()
template<class PointType > void setIndex (const label index) inline noexcept
Definition at line 219 of file pointIndexHit.H.
References PointIndexHit< PointType >::index().
Referenced by triSurfaceTools::classify(), searchableBox::findLine(), and searchableBox::findNearestOnEdge().
hitPoint() [2/3]
template<class PointType > void hitPoint (const point_type & p) inline
Definition at line 225 of file pointIndexHit.H.
References p.
hitPoint() [3/3]
template<class PointType > void hitPoint (const point_type & p, const label index) inline
Definition at line 232 of file pointIndexHit.H.
References PointIndexHit< PointType >::index(), and p.
write()
template<class PointType > void write (Ostream & os) inline
Definition at line 243 of file pointIndexHit.H.
References os().
operator==()
template<class PointType > bool operator== (const PointIndexHit< PointType > & rhs) const inline
Definition at line 253 of file pointIndexHit.H.
operator!=()
template<class PointType > bool operator!= (const PointIndexHit< PointType > & rhs) const inline
Definition at line 264 of file pointIndexHit.H.
Friends And Related Symbol Documentation
operator<<
template<class PointType > Ostream & operator<< (Ostream & os, const PointIndexHit< PointType > & pHit) friend
Definition at line 272 of file pointIndexHit.H.
operator>>
template<class PointType > Istream & operator>> (Istream & is, PointIndexHit< PointType > & pHit) friend
Definition at line 294 of file pointIndexHit.H.
The documentation for this class was generated from the following file:
src/OpenFOAM/meshes/primitiveShapes/objectHit/pointIndexHit.H