OpenFOAM: lumpedPointIOMovement Class Reference
lumpedPointIOMovement Class Reference
IO-registered version of lumpedPointMovement.
#include <lumpedPointIOMovement.H>
Public Member Functions
TypeNameNoDebug ("lumpedPointMovement")
lumpedPointIOMovement (const IOobject &io, label ownerId=-1)
virtual ~lumpedPointIOMovement ()=default
bool readData (Istream &is)
bool writeData (Ostream &os) const
Public Member Functions inherited from lumpedPointMovement
lumpedPointMovement ()
lumpedPointMovement (const dictionary &dict, label ownerId=-1)
virtual ~lumpedPointMovement ()=default
void readDict (const dictionary &dict)
bool empty () const
label size () const
label ownerId () const
void ownerId (label id)
const externalFileCoupler & coupler () const
externalFileCoupler & coupler ()
bool couplingPending (const label timeIndex) const
void couplingCompleted (const label timeIndex) const
const lumpedPointState & state0 () const
const lumpedPointState & state () const
const point & origin () const
void scalePoints (lumpedPointState &state) const
scalar relax () const
scalar & relax ()
const word & inputName () const
const word & outputName () const
const word & logName () const
lumpedPointState::inputFormatType inputFormat () const
lumpedPointMovement::outputFormatType outputFormat () const
quaternion::eulerOrder rotationOrder () const
bool degrees () const
bool hasPatchControl (const label patchIndex) const
bool hasPatchControl (const polyPatch &pp) const
bool hasInterpolator (const pointPatch &fpatch) const
void checkPatchControl (const polyPatch &pp) const
void setPatchControl (const polyPatch &pp, const wordList &ctrlNames, const pointField &points0)
void setMapping (const polyMesh &mesh, const labelUList &patchIds, const pointField &points0)
void setInterpolator (const pointPatch &fpatch, const pointField &points0)
bool hasMapping () const
bool hasInterpolator (const label patchIndex) const
List< scalar > areas (const polyMesh &pmesh) const
bool forcesAndMoments (const polyMesh &pmesh, List< vector > &forces, List< vector > &moments) const
tmp< pointField > pointsDisplacement (const pointPatch &fpatch, const pointField &points0) const
tmp< pointField > pointsDisplacement (const lumpedPointState &state, const pointPatch &fpatch, const pointField &points0) const
tmp< pointField > pointsPosition (const lumpedPointState &state, const pointPatch &fpatch, const pointField &points0) const
void writeDict (Ostream &os) const
bool writeData (Ostream &os, const UList< vector > &forces, const UList< vector > &moments, const outputFormatType fmt=outputFormatType::PLAIN, const Tuple2< scalar, scalar > *timesWritten=nullptr) const
bool writeData (const UList< vector > &forces, const UList< vector > &moments=List< vector >(), const Tuple2< scalar, scalar > *timesWritten=nullptr) const
bool readState ()
void writeStateVTP (const lumpedPointState &state, const fileName &file) const
void writeStateVTP (const fileName &file) const
void writeForcesAndMomentsVTP (const fileName &file, const UList< vector > &forces, const UList< vector > &moments) const
void writeZonesVTP (const fileName &file, const polyMesh &mesh, const pointField &points0) const
void writeVTP (const fileName &file, const polyMesh &mesh, const pointField &points0) const
void writeVTP (const fileName &file, const lumpedPointState &state, const polyMesh &mesh, const pointField &points0) const
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
regIOobject (const IOobject &io, const bool isTimeObject=false)
regIOobject (const regIOobject &rio)
regIOobject (const regIOobject &rio, bool registerCopy)
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
regIOobject (const IOobject &io, const regIOobject &rio)
virtual ~regIOobject ()
bool checkIn ()
bool checkOut ()
virtual void addWatch ()
bool registered () const noexcept
bool ownedByRegistry () const noexcept
bool store ()
void release (const bool unregister=false) noexcept
label eventNo () const noexcept
label & eventNo () noexcept
bool upToDate (const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
void setUpToDate ()
virtual void rename (const word &newName)
const dictionary * findMetaData () const noexcept
dictionary & getMetaData () noexcept
void removeMetaData ()
virtual void updateMetaData ()
virtual fileName filePath () const
bool headerOk ()
Istream & readStream (const word &, const bool readOnProc=true)
void close ()
virtual bool read ()
virtual label addWatch (const fileName &)
const labelList & watchIndices () const noexcept
labelList & watchIndices () noexcept
virtual bool modified () const
virtual bool readIfModified ()
virtual bool writeObject (IOstreamOption streamOpt, const bool writeOnProc) const
virtual bool write (const bool writeOnProc=true) const
virtual bool global () const
void operator= (const IOobject &io)
virtual bool writeObject (IOstreamOption::streamFormat fmt, IOstreamOption::versionNumber ver, IOstreamOption::compressionType cmp, const bool writeOnProc) const
Public Member Functions inherited from IOobject
TypeName ("IOobject")
IOobject (const IOobject &)=default
virtual ~IOobject ()=default
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const fileName &path, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const fileName &path, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const IOobject &io, const objectRegistry &registry)
IOobject (const IOobject &io, const word &name)
IOobject (const IOobject &io, const word &name, const fileName &local)
IOobject (const IOobject &io, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt)
IOobject (const IOobject &io, IOobjectOption::registerOption regOpt)
autoPtr< IOobject > clone () const
autoPtr< IOobject > clone (const objectRegistry &registry) const
const objectRegistry & db () const noexcept
const Time & time () const noexcept
const word & name () const noexcept
const word & headerClassName () const noexcept
word & headerClassName () noexcept
const string & note () const noexcept
string & note () noexcept
unsigned labelByteSize () const noexcept
unsigned scalarByteSize () const noexcept
void resetHeader (const word &newName=word::null)
bool hasHeaderClass () const noexcept
template<class Type >
bool isHeaderClass () const
template<class Type >
bool isHeaderClassName () const
word group () const
word member () const
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const noexcept
fileName & instance () noexcept
const fileName & local () const noexcept
fileName path () const
fileName path (const word &instance, const fileName &local=fileName::null) const
fileName objectPath () const
fileName objectRelPath () const
fileName localFilePath (const word &typeName, const bool search=true) const
fileName globalFilePath (const word &typeName, const bool search=true) const
IOstreamOption parseHeader (const dictionary &headerDict)
bool readHeader (Istream &is)
bool readHeader (dictionary &headerDict, Istream &is)
template<class Type >
bool typeHeaderOk (const bool checkType=true, const bool search=true, const bool verbose=true)
template<class Type >
void warnNoRereading () const
bool writeHeader (Ostream &os) const
bool writeHeader (Ostream &os, const word &objectType) const
void writeHeader (dictionary &dict, IOstreamOption streamOpt) const
void writeHeader (dictionary &dict, const word &objectType, IOstreamOption streamOpt) const
bool good () const noexcept
bool bad () const noexcept
InfoProxy< IOobject > info () const noexcept
void operator= (const IOobject &io)
template<>
bool isHeaderClass () const
template<class StringType >
Foam::word groupName (StringType base, const word &group)
Public Member Functions inherited from IOobjectOption
constexpr IOobjectOption (readOption rOpt=readOption::NO_READ, writeOption wOpt=writeOption::NO_WRITE, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (readOption rOpt, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (writeOption wOpt, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (registerOption registerObject, bool globalObject=false) noexcept
constexpr IOobjectOption (readOption rOpt, writeOption wOpt, bool registerObject, bool globalObject=false) noexcept
constexpr IOobjectOption (bool registerObject, bool globalObject=false) noexcept
readOption readOpt () const noexcept
readOption readOpt (readOption opt) noexcept
writeOption writeOpt () const noexcept
writeOption writeOpt (writeOption opt) noexcept
bool registerObject () const noexcept
bool registerObject (bool on) noexcept
bool globalObject () const noexcept
bool globalObject (bool on) noexcept
bool isAnyRead () const noexcept
bool isReadRequired () const noexcept
bool isReadOptional () const noexcept
readOption & readOpt () noexcept
writeOption & writeOpt () noexcept
bool & registerObject () noexcept
bool & globalObject () noexcept
Static Public Member Functions
static lumpedPointIOMovement * getMovementObject (const objectRegistry &obr)
static autoPtr< lumpedPointIOMovement > New (const objectRegistry &obr, label ownerId=-1)
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *p)
template<class Type >
static Type & store (autoPtr< Type > &ptr)
template<class Type >
static Type & store (autoPtr< Type > &&ptr)
template<class Type >
static Type & store (refPtr< Type > &ptr)
template<class Type >
static Type & store (refPtr< Type > &&ptr)
template<class Type >
static Type & store (tmp< Type > &ptr)
template<class Type >
static Type & store (tmp< Type > &&ptr)
Static Public Member Functions inherited from IOobject
static bool bannerEnabled () noexcept
static bool bannerEnabled (bool on) noexcept
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
template<class StringType >
static word groupName (StringType base, const word &group)
static word group (const word &name)
static word member (const word &name)
static word scopedName (const std::string &scope, const word &name)
static IOobject selectIO (const IOobject &io, const fileName &altFile, const word &ioName="")
static Ostream & writeBanner (Ostream &os, const bool noSyntaxHint=false)
static Ostream & writeDivider (Ostream &os)
static Ostream & writeEndDivider (Ostream &os)
Static Public Member Functions inherited from IOobjectOption
static bool isAnyRead (readOption opt) noexcept
static bool isReadRequired (readOption opt) noexcept
static bool isReadOptional (readOption opt) noexcept
static readOption lazierRead (readOption opt) noexcept
Additional Inherited Members
Public Types inherited from lumpedPointMovement
enum class outputFormatType { PLAIN , DICTIONARY }
enum scalingType { LENGTH = 0 , FORCE , MOMENT }
Public Types inherited from IOobject
enum objectState : char { GOOD , BAD }
enum fileCheckTypes : char { timeStamp , timeStampMaster , inotify , inotifyMaster }
Public Types inherited from IOobjectOption
enum readOption : unsigned char {
NO_READ = 0 , MUST_READ = 0x1 , READ_MODIFIED = 0x3 , MUST_READ_IF_MODIFIED = 0x3 ,
LAZY_READ = 0x4 , READ_IF_PRESENT = 0x4
}
enum writeOption : unsigned char { NO_WRITE = 0 , AUTO_WRITE = 0x10 }
enum registerOption : unsigned char { NO_REGISTER = 0 , REGISTER = 1 }
Static Public Attributes inherited from lumpedPointMovement
static const Enum< outputFormatType > formatNames
static const Enum< scalingType > scalingNames
static int debug
static const word canonicalName
Static Public Attributes inherited from IOobject
static const Enum< fileCheckTypes > fileCheckTypesNames
static char scopeSeparator
static fileCheckTypes fileModificationChecking
static float fileModificationSkew
static int maxFileModificationPolls
Protected Member Functions inherited from regIOobject
bool readHeaderOk (const IOstreamOption::streamFormat fmt, const word &typeName)
Protected Member Functions inherited from IOobject
void setBad (const string &s)
Static Protected Member Functions inherited from IOobject
static void writeHeaderContent (Ostream &os, const IOobject &io, const word &objectType, const dictionary *metaDataDict=nullptr)
static void writeHeaderContent (dictionary &dict, const IOobject &io, const word &objectType, IOstreamOption streamOpt, const dictionary *metaDataDict=nullptr)
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
Detailed Description
IO-registered version of lumpedPointMovement.
Source files
lumpedPointIOMovement.H
lumpedPointMovement.C
Definition at line 48 of file lumpedPointIOMovement.H.
Constructor & Destructor Documentation
lumpedPointIOMovement()
lumpedPointIOMovement (const IOobject & io, label ownerId = -1) explicit
Definition at line 69 of file lumpedPointIOMovement.C.
References regIOobject::close(), IOobjectOption::isReadRequired(), lumpedPointMovement::ownerId(), lumpedPointIOMovement::readData(), and regIOobject::readStream().
~lumpedPointIOMovement()
virtual ~lumpedPointIOMovement () virtual default
Member Function Documentation
TypeNameNoDebug()
TypeNameNoDebug ("lumpedPointMovement")
getMovementObject()
Foam::lumpedPointIOMovement * getMovementObject (const objectRegistry & obr) static
Definition at line 35 of file lumpedPointIOMovement.C.
References lumpedPointMovement::canonicalName, and objectRegistry::getObjectPtr().
Referenced by lumpedPointDisplacementPointPatchVectorField::movement(), and lumpedPointDisplacementPointPatchVectorField::~lumpedPointDisplacementPointPatchVectorField().
New()
Foam::autoPtr< Foam::lumpedPointIOMovement > New (const objectRegistry & obr, label ownerId = -1) static
Definition at line 45 of file lumpedPointIOMovement.C.
References lumpedPointMovement::canonicalName, IOobjectOption::MUST_READ, autoPtr< T >::New(), IOobjectOption::NO_WRITE, IOobjectOption::REGISTER, and objectRegistry::time().
Referenced by lumpedPointDisplacementPointPatchVectorField::movement().
readData()
bool readData (Istream & is) virtual
Reimplemented from regIOobject.
Definition at line 93 of file lumpedPointIOMovement.C.
References dict, and FUNCTION_NAME.
Referenced by lumpedPointIOMovement::lumpedPointIOMovement().
writeData()
bool writeData (Ostream & os) const virtual
Implements regIOobject.
Definition at line 103 of file lumpedPointIOMovement.C.
References IOstream::good(), and os().
The documentation for this class was generated from the following files:
src/lumpedPointMotion/movement/lumpedPointIOMovement.H
src/lumpedPointMotion/movement/lumpedPointIOMovement.C