OpenFOAM: ddtScheme< Type > Class Template Reference
ddtScheme< Type > Class Template Reference abstract
Numerics » Finite volume numerical schemes » Time schemes
Abstract base class for ddt schemes.
#include <ddtScheme.H>
Public Types
typedef GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > fluxFieldType
Public Member Functions
virtual const word & type () const =0
declareRunTimeSelectionTable (tmp, ddtScheme, Istream,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
ddtScheme (const fvMesh &mesh)
ddtScheme (const fvMesh &mesh, Istream &is)
virtual ~ddtScheme ()=default
const fvMesh & mesh () const
virtual tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const dimensioned< Type > &)=0
virtual tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const GeometricField< Type, fvPatchField, volMesh > &)=0
virtual tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const dimensionedScalar &, const GeometricField< Type, fvPatchField, volMesh > &)=0
virtual tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const volScalarField &, const GeometricField< Type, fvPatchField, volMesh > &)=0
virtual tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const volScalarField &alpha, const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &)=0
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > fvcDdt (const GeometricField< Type, fvsPatchField, surfaceMesh > &)
virtual tmp< fvMatrix< Type > > fvmDdt (const GeometricField< Type, fvPatchField, volMesh > &)=0
virtual tmp< fvMatrix< Type > > fvmDdt (const dimensionedScalar &, const GeometricField< Type, fvPatchField, volMesh > &)=0
virtual tmp< fvMatrix< Type > > fvmDdt (const volScalarField &, const GeometricField< Type, fvPatchField, volMesh > &)=0
virtual tmp< fvMatrix< Type > > fvmDdt (const volScalarField &alpha, const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &vf)=0
tmp< surfaceScalarField > fvcDdtPhiCoeff (const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi, const fluxFieldType &phiCorr)
tmp< surfaceScalarField > fvcDdtPhiCoeffExperimental (const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi, const fluxFieldType &phiCorr)
tmp< surfaceScalarField > fvcDdtPhiCoeff (const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi, const fluxFieldType &phiCorr, const volScalarField &rho)
tmp< surfaceScalarField > fvcDdtPhiCoeff (const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi)
tmp< surfaceScalarField > fvcDdtPhiCoeff (const GeometricField< Type, fvPatchField, volMesh > &rhoU, const fluxFieldType &phi, const volScalarField &rho)
virtual tmp< fluxFieldType > fvcDdtUfCorr (const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< Type, fvsPatchField, surfaceMesh > &Uf)=0
virtual tmp< fluxFieldType > fvcDdtPhiCorr (const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi)=0
virtual tmp< fluxFieldType > fvcDdtUfCorr (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< Type, fvsPatchField, surfaceMesh > &Uf)=0
virtual tmp< fluxFieldType > fvcDdtPhiCorr (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi)=0
virtual tmp< surfaceScalarField > meshPhi (const GeometricField< Type, fvPatchField, volMesh > &)=0
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Public Member Functions inherited from ddtSchemeBase
ddtSchemeBase ()
ddtSchemeBase ()
Static Public Member Functions
static tmp< ddtScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Protected Member Functions
ddtScheme (const ddtScheme &)=delete
void operator= (const ddtScheme &)=delete
Protected Attributes
const fvMesh & mesh_
scalar ddtPhiCoeff_
Additional Inherited Members
Static Public Attributes inherited from ddtSchemeBase
static bool experimentalDdtCorr
Detailed Description
template<class Type>
class Foam::fv::ddtScheme< Type >
Abstract base class for ddt schemes.
Source files
ddtScheme.H
ddtScheme.C
Definition at line 79 of file ddtScheme.H.
Member Typedef Documentation
fluxFieldType
template<class Type > typedef GeometricField< typename flux<Type>::type, fvsPatchField, surfaceMesh > fluxFieldType
Definition at line 226 of file ddtScheme.H.
Constructor & Destructor Documentation
ddtScheme() [1/3]
template<class Type > ddtScheme (const ddtScheme< Type > &) protected delete
ddtScheme() [2/3]
template<class Type > ddtScheme (const fvMesh & mesh) inline
Definition at line 127 of file ddtScheme.H.
ddtScheme() [3/3]
template<class Type > ddtScheme (const fvMesh & mesh, Istream & is) inline
Definition at line 134 of file ddtScheme.H.
~ddtScheme()
template<class Type > virtual ~ddtScheme () virtual default
Member Function Documentation
operator=()
template<class Type > void operator= (const ddtScheme< Type > &) protected delete
type()
template<class Type > virtual const word & type () const pure virtual
declareRunTimeSelectionTable()
template<class Type > declareRunTimeSelectionTable (tmp , ddtScheme< Type > , Istream , (const fvMesh &mesh, Istream &schemeData) , (mesh, schemeData))
New()
template<class Type > tmp< ddtScheme< Type > > New (const fvMesh & mesh, Istream & schemeData) static
Definition at line 42 of file ddtScheme.C.
References Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, FatalIOErrorInLookup, InfoInFunction, and mesh.
Referenced by Foam::fvc::ddt(), Foam::fvc::ddt(), Foam::fvm::ddt(), Foam::fvc::ddt(), Foam::fvm::ddt(), Foam::fvc::ddt(), Foam::fvc::ddt(), Foam::fvm::ddt(), Foam::fvc::ddt(), Foam::fvm::ddt(), Foam::fvc::ddtCorr(), Foam::fvc::ddtCorr(), Foam::fvc::ddtCorr(), and Foam::fvc::ddtCorr().
mesh()
template<class Type > const fvMesh & mesh () const inline
Definition at line 158 of file ddtScheme.H.
References ddtScheme< Type >::mesh_.
Referenced by backwardDdtScheme< Type >::mesh(), boundedDdtScheme< Type >::mesh(), CoEulerDdtScheme< Type >::mesh(), CrankNicolsonDdtScheme< Type >::mesh(), EulerDdtScheme< Type >::mesh(), localEulerDdtScheme< Type >::mesh(), SLTSDdtScheme< Type >::mesh(), and steadyStateDdtScheme< Type >::mesh().
fvcDdt() [1/6]
template<class Type > virtual tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const dimensioned< Type > &) pure virtual
Implemented in backwardDdtScheme< Type >, boundedDdtScheme< Type >, CoEulerDdtScheme< Type >, CrankNicolsonDdtScheme< Type >, EulerDdtScheme< Type >, localEulerDdtScheme< Type >, SLTSDdtScheme< Type >, and steadyStateDdtScheme< Type >.
fvcDdt() [2/6]
template<class Type > virtual tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const GeometricField< Type, fvPatchField, volMesh > &) pure virtual
Implemented in backwardDdtScheme< Type >, boundedDdtScheme< Type >, CoEulerDdtScheme< Type >, CrankNicolsonDdtScheme< Type >, EulerDdtScheme< Type >, localEulerDdtScheme< Type >, SLTSDdtScheme< Type >, and steadyStateDdtScheme< Type >.
fvcDdt() [3/6]
template<class Type > virtual tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const dimensionedScalar & , const GeometricField< Type, fvPatchField, volMesh > &) pure virtual
Implemented in backwardDdtScheme< Type >, boundedDdtScheme< Type >, CoEulerDdtScheme< Type >, CrankNicolsonDdtScheme< Type >, EulerDdtScheme< Type >, localEulerDdtScheme< Type >, SLTSDdtScheme< Type >, and steadyStateDdtScheme< Type >.
fvcDdt() [4/6]
template<class Type > virtual tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const volScalarField & , const GeometricField< Type, fvPatchField, volMesh > &) pure virtual
Implemented in backwardDdtScheme< Type >, boundedDdtScheme< Type >, CoEulerDdtScheme< Type >, CrankNicolsonDdtScheme< Type >, EulerDdtScheme< Type >, localEulerDdtScheme< Type >, SLTSDdtScheme< Type >, and steadyStateDdtScheme< Type >.
fvcDdt() [5/6]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const volScalarField & alpha, const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & vf) pure virtual
Implemented in backwardDdtScheme< Type >, boundedDdtScheme< Type >, CoEulerDdtScheme< Type >, CrankNicolsonDdtScheme< Type >, EulerDdtScheme< Type >, localEulerDdtScheme< Type >, SLTSDdtScheme< Type >, and steadyStateDdtScheme< Type >.
Definition at line 84 of file ddtScheme.C.
References NotImplemented, and GeometricField< Type, PatchField, GeoMesh >::null().
fvcDdt() [6/6]
template<class Type > tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > fvcDdt (const GeometricField< Type, fvsPatchField, surfaceMesh > & sf) virtual
Reimplemented in EulerDdtScheme< Type >, and localEulerDdtScheme< Type >.
Definition at line 120 of file ddtScheme.C.
References NotImplemented, and GeometricField< Type, PatchField, GeoMesh >::null().
fvmDdt() [1/4]
template<class Type > virtual tmp< fvMatrix< Type > > fvmDdt (const GeometricField< Type, fvPatchField, volMesh > &) pure virtual
Implemented in backwardDdtScheme< Type >, boundedDdtScheme< Type >, CoEulerDdtScheme< Type >, CrankNicolsonDdtScheme< Type >, EulerDdtScheme< Type >, localEulerDdtScheme< Type >, SLTSDdtScheme< Type >, and steadyStateDdtScheme< Type >.
fvmDdt() [2/4]
template<class Type > virtual tmp< fvMatrix< Type > > fvmDdt (const dimensionedScalar & , const GeometricField< Type, fvPatchField, volMesh > &) pure virtual
Implemented in backwardDdtScheme< Type >, boundedDdtScheme< Type >, CoEulerDdtScheme< Type >, CrankNicolsonDdtScheme< Type >, EulerDdtScheme< Type >, localEulerDdtScheme< Type >, SLTSDdtScheme< Type >, and steadyStateDdtScheme< Type >.
fvmDdt() [3/4]
template<class Type > virtual tmp< fvMatrix< Type > > fvmDdt (const volScalarField & , const GeometricField< Type, fvPatchField, volMesh > &) pure virtual
Implemented in backwardDdtScheme< Type >, boundedDdtScheme< Type >, CoEulerDdtScheme< Type >, CrankNicolsonDdtScheme< Type >, EulerDdtScheme< Type >, localEulerDdtScheme< Type >, SLTSDdtScheme< Type >, and steadyStateDdtScheme< Type >.
fvmDdt() [4/4]
template<class Type > tmp< fvMatrix< Type > > fvmDdt (const volScalarField & alpha, const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & vf) pure virtual
Implemented in backwardDdtScheme< Type >, boundedDdtScheme< Type >, CoEulerDdtScheme< Type >, CrankNicolsonDdtScheme< Type >, EulerDdtScheme< Type >, localEulerDdtScheme< Type >, SLTSDdtScheme< Type >, and steadyStateDdtScheme< Type >.
Definition at line 101 of file ddtScheme.C.
References alpha, Foam::dimTime, Foam::dimVol, Foam::New(), NotImplemented, and rho.
fvcDdtPhiCoeff() [1/4]
template<class Type > tmp< surfaceScalarField > fvcDdtPhiCoeff (const GeometricField< Type, fvPatchField, volMesh > & U, const fluxFieldType & phi, const fluxFieldType & phiCorr)
Definition at line 136 of file ddtScheme.C.
References boundary, Foam::dimless, Foam::endl(), forAll, Foam::gAverage(), Foam::gMax(), Foam::gMin(), InfoInFunction, Foam::mag(), mesh, Foam::min(), phi, and U.
fvcDdtPhiCoeffExperimental()
template<class Type > tmp< surfaceScalarField > fvcDdtPhiCoeffExperimental (const GeometricField< Type, fvPatchField, volMesh > & U, const fluxFieldType & phi, const fluxFieldType & phiCorr)
Definition at line 210 of file ddtScheme.C.
References boundary, Foam::dimless, Foam::endl(), forAll, Foam::gAverage(), Foam::gMax(), Foam::gMin(), InfoInFunction, Foam::mag(), mesh, Foam::min(), and U.
fvcDdtPhiCoeff() [2/4]
template<class Type > tmp< surfaceScalarField > fvcDdtPhiCoeff (const GeometricField< Type, fvPatchField, volMesh > & U, const fluxFieldType & phi, const fluxFieldType & phiCorr, const volScalarField & rho)
Definition at line 291 of file ddtScheme.C.
References Foam::fvc::interpolate(), phi, rho, and U.
fvcDdtPhiCoeff() [3/4]
template<class Type > tmp< surfaceScalarField > fvcDdtPhiCoeff (const GeometricField< Type, fvPatchField, volMesh > & U, const fluxFieldType & phi)
Definition at line 317 of file ddtScheme.C.
References Foam::fvc::dotInterpolate(), mesh, phi, and U.
fvcDdtPhiCoeff() [4/4]
template<class Type > tmp< surfaceScalarField > fvcDdtPhiCoeff (const GeometricField< Type, fvPatchField, volMesh > & rhoU, const fluxFieldType & phi, const volScalarField & rho)
Definition at line 347 of file ddtScheme.C.
References Foam::fvc::dotInterpolate(), Foam::fvc::interpolate(), mesh, phi, and rho.
fvcDdtUfCorr() [1/2]
template<class Type > virtual tmp< fluxFieldType > fvcDdtUfCorr (const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< Type, fvsPatchField, surfaceMesh > & Uf) pure virtual
Implemented in backwardDdtScheme< Type >, boundedDdtScheme< Type >, CoEulerDdtScheme< Type >, CrankNicolsonDdtScheme< Type >, EulerDdtScheme< Type >, localEulerDdtScheme< Type >, SLTSDdtScheme< Type >, and steadyStateDdtScheme< Type >.
fvcDdtPhiCorr() [1/2]
template<class Type > virtual tmp< fluxFieldType > fvcDdtPhiCorr (const GeometricField< Type, fvPatchField, volMesh > & U, const fluxFieldType & phi) pure virtual
Implemented in backwardDdtScheme< Type >, boundedDdtScheme< Type >, CoEulerDdtScheme< Type >, CrankNicolsonDdtScheme< Type >, EulerDdtScheme< Type >, localEulerDdtScheme< Type >, SLTSDdtScheme< Type >, and steadyStateDdtScheme< Type >.
fvcDdtUfCorr() [2/2]
template<class Type > virtual tmp< fluxFieldType > fvcDdtUfCorr (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< Type, fvsPatchField, surfaceMesh > & Uf) pure virtual
Implemented in backwardDdtScheme< Type >, boundedDdtScheme< Type >, CoEulerDdtScheme< Type >, CrankNicolsonDdtScheme< Type >, EulerDdtScheme< Type >, localEulerDdtScheme< Type >, SLTSDdtScheme< Type >, and steadyStateDdtScheme< Type >.
fvcDdtPhiCorr() [2/2]
template<class Type > virtual tmp< fluxFieldType > fvcDdtPhiCorr (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & U, const fluxFieldType & phi) pure virtual
Implemented in backwardDdtScheme< Type >, boundedDdtScheme< Type >, CoEulerDdtScheme< Type >, CrankNicolsonDdtScheme< Type >, EulerDdtScheme< Type >, localEulerDdtScheme< Type >, SLTSDdtScheme< Type >, and steadyStateDdtScheme< Type >.
meshPhi()
template<class Type > virtual tmp< surfaceScalarField > meshPhi (const GeometricField< Type, fvPatchField, volMesh > &) pure virtual
Implemented in backwardDdtScheme< Type >, boundedDdtScheme< Type >, CoEulerDdtScheme< Type >, CrankNicolsonDdtScheme< Type >, EulerDdtScheme< Type >, localEulerDdtScheme< Type >, SLTSDdtScheme< Type >, and steadyStateDdtScheme< Type >.
Referenced by Foam::fvc::meshPhi(), Foam::fvc::meshPhi(), and Foam::fvc::meshPhi().
Member Data Documentation
mesh_
template<class Type > const fvMesh& mesh_ protected
Definition at line 89 of file ddtScheme.H.
Referenced by ddtScheme< Type >::mesh().
ddtPhiCoeff_
template<class Type > scalar ddtPhiCoeff_ protected
Definition at line 94 of file ddtScheme.H.
Referenced by backwardDdtScheme< Type >::backwardDdtScheme().
The documentation for this class was generated from the following files:
src/finiteVolume/finiteVolume/ddtSchemes/ddtScheme/ddtScheme.H
src/finiteVolume/finiteVolume/ddtSchemes/ddtScheme/ddtScheme.C