OpenFOAM: kEpsilonLopesdaCosta< BasicTurbulenceModel > Class Template Reference
kEpsilonLopesdaCosta< BasicTurbulenceModel > Class Template Reference
Turbulence models » RAS turbulence
Variant of the standard k-epsilon turbulence model with additional source terms to handle the changes in turbulence in porous regions represented by the powerLawLopesdaCosta porosity model.
#include <kEpsilonLopesdaCosta.H>
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from linearViscousStress< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("kEpsilonLopesdaCosta")
kEpsilonLopesdaCosta (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
virtual ~kEpsilonLopesdaCosta ()=default
virtual bool read ()
tmp< volScalarField > DkEff () const
tmp< volScalarField > DepsilonEff () const
virtual tmp< volScalarField > k () const
virtual tmp< volScalarField > epsilon () const
virtual void correct ()
Public Member Functions inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
eddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~eddyViscosity ()=default
virtual tmp< volScalarField > nut () const
virtual tmp< scalarField > nut (const label patchi) const
virtual tmp< volSymmTensorField > R () const
virtual void validate ()
Public Member Functions inherited from linearViscousStress< BasicTurbulenceModel >
linearViscousStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~linearViscousStress ()=default
virtual tmp< volSymmTensorField > devRhoReff () const
virtual tmp< volSymmTensorField > devRhoReff (const volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Protected Member Functions
void setPorosityCoefficient (volScalarField::Internal &C, const porosityModels::powerLawLopesdaCosta &pm)
void setCdSigma (volScalarField::Internal &C, const porosityModels::powerLawLopesdaCosta &pm)
void setPorosityCoefficients ()
virtual void correctNut ()
virtual tmp< fvScalarMatrix > kSource (const volScalarField::Internal &magU, const volScalarField::Internal &magU3) const
virtual tmp< fvScalarMatrix > epsilonSource (const volScalarField::Internal &magU, const volScalarField::Internal &magU3) const
Protected Attributes
volScalarField Cmu_
volScalarField::Internal C1_
volScalarField::Internal C2_
volScalarField sigmak_
volScalarField sigmaEps_
volScalarField::Internal CdSigma_
volScalarField::Internal betap_
volScalarField::Internal betad_
volScalarField::Internal C4_
volScalarField::Internal C5_
volScalarField k_
volScalarField epsilon_
Protected Attributes inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
volScalarField nut_
Detailed Description
template<class BasicTurbulenceModel>
class Foam::RASModels::kEpsilonLopesdaCosta< BasicTurbulenceModel >
Variant of the standard k-epsilon turbulence model with additional source terms to handle the changes in turbulence in porous regions represented by the powerLawLopesdaCosta porosity model.
Reference:
    Costa, J. C. P. L. D. (2007).
    Atmospheric flow over forested and non-forested complex terrain.
The default model coefficients are
    kEpsilonLopesdaCostaCoeffs
    {
        Cmu         0.09;
        C1          1.44;
        C2          1.92;
        sigmak      1.0;
        sigmaEps    1.3;
    }
See also
Foam::RASModels::kEpsilon Foam::porosityModels::powerLawLopesdaCosta
Source files
kEpsilonLopesdaCosta.H
kEpsilonLopesdaCosta.C
Definition at line 79 of file kEpsilonLopesdaCosta.H.
Member Typedef Documentation
alphaField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 152 of file kEpsilonLopesdaCosta.H.
rhoField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 153 of file kEpsilonLopesdaCosta.H.
transportModel
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 154 of file kEpsilonLopesdaCosta.H.
Constructor & Destructor Documentation
kEpsilonLopesdaCosta()
template<class BasicTurbulenceModel > kEpsilonLopesdaCosta (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Definition at line 172 of file kEpsilonLopesdaCosta.C.
References Foam::bound(), kEpsilonLopesdaCosta< BasicTurbulenceModel >::epsilon_, kEpsilonLopesdaCosta< BasicTurbulenceModel >::k_, kEpsilonLopesdaCosta< BasicTurbulenceModel >::setPorosityCoefficients(), and Foam::type().
~kEpsilonLopesdaCosta()
template<class BasicTurbulenceModel > virtual ~kEpsilonLopesdaCosta () virtual default
Member Function Documentation
setPorosityCoefficient()
template<class BasicTurbulenceModel > void setPorosityCoefficient (volScalarField::Internal & C, const porosityModels::powerLawLopesdaCosta & pm) protected
Definition at line 37 of file kEpsilonLopesdaCosta.C.
References cells, and UPtrList< T >::get().
setCdSigma()
template<class BasicTurbulenceModel > void setCdSigma (volScalarField::Internal & C, const porosityModels::powerLawLopesdaCosta & pm) protected
Definition at line 63 of file kEpsilonLopesdaCosta.C.
References cells, forAll, and UPtrList< T >::get().
setPorosityCoefficients()
template<class BasicTurbulenceModel > void setPorosityCoefficients () protected
Definition at line 91 of file kEpsilonLopesdaCosta.C.
References forAll, fvOptions, options::New(), and optionList::optionList().
Referenced by kEpsilonLopesdaCosta< BasicTurbulenceModel >::kEpsilonLopesdaCosta().
correctNut()
template<class BasicTurbulenceModel > void correctNut () protected virtual
Implements eddyViscosity< RASModel< BasicTurbulenceModel > >.
Definition at line 131 of file kEpsilonLopesdaCosta.C.
References options::New(), and Foam::sqr().
kSource()
template<class BasicTurbulenceModel > tmp< fvScalarMatrix > kSource (const volScalarField::Internal & magU, const volScalarField::Internal & magU3) const protected virtual
Definition at line 142 of file kEpsilonLopesdaCosta.C.
References Foam::fvm::Su().
epsilonSource()
template<class BasicTurbulenceModel > tmp< fvScalarMatrix > epsilonSource (const volScalarField::Internal & magU, const volScalarField::Internal & magU3) const protected virtual
Definition at line 154 of file kEpsilonLopesdaCosta.C.
References Foam::fvm::Su().
TypeName()
template<class BasicTurbulenceModel > TypeName ("kEpsilonLopesdaCosta< BasicTurbulenceModel >")
read()
template<class BasicTurbulenceModel > bool read () virtual
Implements eddyViscosity< RASModel< BasicTurbulenceModel > >.
Definition at line 373 of file kEpsilonLopesdaCosta.C.
References Foam::read().
DkEff()
template<class BasicTurbulenceModel > tmp< volScalarField > DkEff () const inline
Definition at line 187 of file kEpsilonLopesdaCosta.H.
References nu, and eddyViscosity< RASModel< BasicTurbulenceModel > >::nut_.
DepsilonEff()
template<class BasicTurbulenceModel > tmp< volScalarField > DepsilonEff () const inline
Definition at line 200 of file kEpsilonLopesdaCosta.H.
References nu, and eddyViscosity< RASModel< BasicTurbulenceModel > >::nut_.
k()
template<class BasicTurbulenceModel > virtual tmp< volScalarField > k () const inline virtual
Implements eddyViscosity< RASModel< BasicTurbulenceModel > >.
Definition at line 213 of file kEpsilonLopesdaCosta.H.
References kEpsilonLopesdaCosta< BasicTurbulenceModel >::k_.
epsilon()
template<class BasicTurbulenceModel > virtual tmp< volScalarField > epsilon () const inline virtual
Definition at line 219 of file kEpsilonLopesdaCosta.H.
References kEpsilonLopesdaCosta< BasicTurbulenceModel >::epsilon_.
correct()
template<class BasicTurbulenceModel > void correct () virtual
Implements eddyViscosity< RASModel< BasicTurbulenceModel > >.
Definition at line 385 of file kEpsilonLopesdaCosta.C.
References Foam::fvc::absolute(), alpha, Foam::bound(), PtrList< T >::clear(), correct(), Foam::fvm::ddt(), Foam::devTwoSymm(), Foam::fvc::div(), Foam::fvm::div(), divU, fvOptions, Foam::fvc::grad(), Foam::fvm::laplacian(), Foam::mag(), options::New(), nut, phi, Foam::pow3(), rho, solve(), Foam::fvm::Sp(), Foam::fvm::SuSp(), and U.
Member Data Documentation
Cmu_
template<class BasicTurbulenceModel > volScalarField Cmu_ protected
Definition at line 98 of file kEpsilonLopesdaCosta.H.
C1_
template<class BasicTurbulenceModel > volScalarField::Internal C1_ protected
Definition at line 99 of file kEpsilonLopesdaCosta.H.
C2_
template<class BasicTurbulenceModel > volScalarField::Internal C2_ protected
Definition at line 100 of file kEpsilonLopesdaCosta.H.
sigmak_
template<class BasicTurbulenceModel > volScalarField sigmak_ protected
Definition at line 101 of file kEpsilonLopesdaCosta.H.
sigmaEps_
template<class BasicTurbulenceModel > volScalarField sigmaEps_ protected
Definition at line 102 of file kEpsilonLopesdaCosta.H.
CdSigma_
template<class BasicTurbulenceModel > volScalarField::Internal CdSigma_ protected
Definition at line 106 of file kEpsilonLopesdaCosta.H.
betap_
template<class BasicTurbulenceModel > volScalarField::Internal betap_ protected
Definition at line 107 of file kEpsilonLopesdaCosta.H.
betad_
template<class BasicTurbulenceModel > volScalarField::Internal betad_ protected
Definition at line 108 of file kEpsilonLopesdaCosta.H.
C4_
template<class BasicTurbulenceModel > volScalarField::Internal C4_ protected
Definition at line 109 of file kEpsilonLopesdaCosta.H.
C5_
template<class BasicTurbulenceModel > volScalarField::Internal C5_ protected
Definition at line 110 of file kEpsilonLopesdaCosta.H.
k_
template<class BasicTurbulenceModel > volScalarField k_ protected
Definition at line 115 of file kEpsilonLopesdaCosta.H.
Referenced by kEpsilonLopesdaCosta< BasicTurbulenceModel >::k(), and kEpsilonLopesdaCosta< BasicTurbulenceModel >::kEpsilonLopesdaCosta().
epsilon_
template<class BasicTurbulenceModel > volScalarField epsilon_ protected
Definition at line 116 of file kEpsilonLopesdaCosta.H.
Referenced by kEpsilonLopesdaCosta< BasicTurbulenceModel >::epsilon(), and kEpsilonLopesdaCosta< BasicTurbulenceModel >::kEpsilonLopesdaCosta().
The documentation for this class was generated from the following files:
src/atmosphericModels/turbulenceModels/RAS/kEpsilonLopesdaCosta/kEpsilonLopesdaCosta.H
src/atmosphericModels/turbulenceModels/RAS/kEpsilonLopesdaCosta/kEpsilonLopesdaCosta.C