OpenFOAM: wallPoints Class Reference
wallPoints Class Reference
For use with FaceCellWave. Determines topological distance to starting faces.
#include <wallPoints.H>
Classes
class trackData
Public Member Functions
wallPoints ()
wallPoints (const UList< point > &origin, const UList< scalar > &distSqr, const UList< FixedList< label, 3 > > &surface)
const List< point > & origin () const
const List< scalar > & distSqr () const
const List< FixedList< label, 3 > > & surface () const
template<class TrackingData >
bool valid (TrackingData &td) const
template<class TrackingData >
bool sameGeometry (const polyMesh &, const wallPoints &, const scalar, TrackingData &td) const
template<class TrackingData >
void leaveDomain (const polyMesh &, const polyPatch &, const label patchFacei, const point &faceCentre, TrackingData &td)
template<class TrackingData >
void enterDomain (const polyMesh &, const polyPatch &, const label patchFacei, const point &faceCentre, TrackingData &td)
template<class TrackingData >
void transform (const polyMesh &, const tensor &, TrackingData &td)
template<class TrackingData >
bool updateCell (const polyMesh &, const label thisCelli, const label neighbourFacei, const wallPoints &neighbourInfo, const scalar tol, TrackingData &td)
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFacei, const label neighbourCelli, const wallPoints &neighbourInfo, const scalar tol, TrackingData &td)
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFacei, const wallPoints &neighbourInfo, const scalar tol, TrackingData &td)
template<class TrackingData >
bool equal (const wallPoints &, TrackingData &) const
bool operator== (const wallPoints &) const
bool operator!= (const wallPoints &) const
Protected Member Functions
template<class TrackingData >
bool update (const point &pt, const label index1, const wallPoints &w2, const label index2, const scalar tol, TrackingData &td)
Protected Attributes
DynamicList< point > origin_
DynamicList< scalar > distSqr_
DynamicList< FixedList< label, 3 > > surface_
Friends
Ostream & operator<< (Ostream &, const wallPoints &)
Istream & operator>> (Istream &, wallPoints &)
Detailed Description
For use with FaceCellWave. Determines topological distance to starting faces.
Source files
wallPoints.H
wallPointsI.H
wallPoints.C
Definition at line 59 of file wallPoints.H.
Constructor & Destructor Documentation
wallPoints() [1/2]
wallPoints () inline
Definition at line 83 of file wallPointsI.H.
wallPoints() [2/2]
wallPoints (const UList< point > & origin, const UList< scalar > & distSqr, const UList< FixedList< label, 3 > > & surface) inline
Definition at line 92 of file wallPointsI.H.
Member Function Documentation
update()
template<class TrackingData > bool update (const point & pt, const label index1, const wallPoints & w2, const label index2, const scalar tol, TrackingData & td) inline protected
Definition at line 27 of file wallPointsI.H.
References Foam::diff(), wallPoints::distSqr_, Foam::magSqr(), wallPoints::origin_, wallPoints::surface_, wallPoints::valid(), and w2.
origin()
const List< point > & origin () const inline
Definition at line 142 of file wallPoints.H.
References wallPoints::origin_.
distSqr()
const List< scalar > & distSqr () const inline
Definition at line 146 of file wallPoints.H.
References wallPoints::distSqr_.
surface()
const List< FixedList< label, 3 > > & surface () const inline
Definition at line 151 of file wallPoints.H.
References wallPoints::surface_.
valid()
template<class TrackingData > bool valid (TrackingData & td) const inline
Definition at line 110 of file wallPointsI.H.
References UPtrList< T >::size().
Referenced by wallPoints::update().
sameGeometry()
template<class TrackingData > bool sameGeometry (const polyMesh & , const wallPoints & , const scalar , TrackingData & td) const inline
Definition at line 118 of file wallPointsI.H.
leaveDomain()
template<class TrackingData > void leaveDomain (const polyMesh & , const polyPatch & patch, const label patchFacei, const point & faceCentre, TrackingData & td) inline
Definition at line 132 of file wallPointsI.H.
enterDomain()
template<class TrackingData > void enterDomain (const polyMesh & , const polyPatch & patch, const label patchFacei, const point & faceCentre, TrackingData & td) inline
Definition at line 166 of file wallPointsI.H.
transform()
template<class TrackingData > void transform (const polyMesh & , const tensor & rotTensor, TrackingData & td) inline
Definition at line 150 of file wallPointsI.H.
References Foam::transform().
updateCell()
template<class TrackingData > bool updateCell (const polyMesh & mesh, const label thisCelli, const label neighbourFacei, const wallPoints & neighbourInfo, const scalar tol, TrackingData & td) inline
Definition at line 185 of file wallPointsI.H.
References PtrList< T >::append(), primitiveMesh::cellCentres(), forAll, Foam::magSqr(), mesh, Foam::sqr(), and update().
updateFace() [1/2]
template<class TrackingData > bool updateFace (const polyMesh & mesh, const label thisFacei, const label neighbourCelli, const wallPoints & neighbourInfo, const scalar tol, TrackingData & td) inline
Definition at line 255 of file wallPointsI.H.
References PtrList< T >::append(), primitiveMesh::faceCentres(), forAll, Foam::magSqr(), mesh, Foam::sqr(), and update().
updateFace() [2/2]
template<class TrackingData > bool updateFace (const polyMesh & mesh, const label thisFacei, const wallPoints & neighbourInfo, const scalar tol, TrackingData & td) inline
Definition at line 324 of file wallPointsI.H.
References PtrList< T >::append(), primitiveMesh::faceCentres(), forAll, Foam::magSqr(), mesh, Foam::sqr(), and update().
equal()
template<class TrackingData > bool equal (const wallPoints & rhs, TrackingData & td) const inline
Definition at line 391 of file wallPointsI.H.
References Foam::operator==().
operator==()
bool operator== (const wallPoints & rhs) const inline
Definition at line 403 of file wallPointsI.H.
operator!=()
bool operator!= (const wallPoints & rhs) const inline
Definition at line 416 of file wallPointsI.H.
Friends And Related Symbol Documentation
operator<<
Ostream & operator<< (Ostream & , const wallPoints &) friend
operator>>
Istream & operator>> (Istream & , wallPoints &) friend
Member Data Documentation
origin_
DynamicList<point> origin_ protected
Definition at line 91 of file wallPoints.H.
Referenced by wallPoints::origin(), and wallPoints::update().
distSqr_
DynamicList<scalar> distSqr_ protected
Definition at line 94 of file wallPoints.H.
Referenced by wallPoints::distSqr(), and wallPoints::update().
surface_
DynamicList<FixedList<label, 3> > surface_ protected
Definition at line 97 of file wallPoints.H.
Referenced by wallPoints::surface(), and wallPoints::update().
The documentation for this class was generated from the following files:
src/mesh/snappyHexMesh/meshRefinement/wallPoints.H
src/mesh/snappyHexMesh/meshRefinement/wallPointsI.H