OpenFOAM: cutFace Class Reference
cutFace Class Reference
Base class for cutting a face, faceI, of an fvMesh, mesh_, at its intersections.
#include <cutFace.H>
Public Member Functions
cutFace (const fvMesh &mesh)
Static Public Attributes
static int debug = 0
Protected Member Functions
void calcSubFace (const label faceI, const scalarList &pointStatus, label firstFullySubmergedPoint, DynamicList< point > &subFacePoints, DynamicList< point > &surfacePoints, label &faceStatus, vector &subFaceCentre, vector &subFaceArea)
void calcSubFace (const label faceI, const scalarList &pointStatus, const scalarList &weights, label firstFullySubmergedPoint, DynamicList< point > &subFacePoints, DynamicList< point > &surfacePoints, label &faceStatus, vector &subFaceCentre, vector &subFaceArea)
void calcSubFaceCentreAndArea (DynamicList< point > &subFacePoints, vector &subFaceCentre, vector &subFaceArea)
void calcSubFace (const face &f, const pointField &points, const scalarList &pointStatus, label firstFullySubmergedPoint, DynamicList< point > &subFacePoints, DynamicList< point > &surfacePoints, label &faceStatus, vector &subFaceCentre, vector &subFaceArea)
Detailed Description
Base class for cutting a face, faceI, of an fvMesh, mesh_, at its intersections.
Original code supplied by Johan Roenby, DHI (2016) Henning Scheufler, DLR (2019)
Source files
cutFace.H
cutFace.C
Definition at line 55 of file cutFace.H.
Constructor & Destructor Documentation
cutFace()
cutFace (const fvMesh & mesh) explicit
Definition at line 333 of file cutFace.C.
Member Function Documentation
calcSubFace() [1/3]
void calcSubFace (const label faceI, const scalarList & pointStatus, label firstFullySubmergedPoint, DynamicList< point > & subFacePoints, DynamicList< point > & surfacePoints, label & faceStatus, vector & subFaceCentre, vector & subFaceArea) protected
Definition at line 32 of file cutFace.C.
References PtrList< T >::append(), cutFace::calcSubFaceCentreAndArea(), f(), p, points, UPtrList< T >::size(), and Foam::Zero.
Referenced by cutFaceAdvect::calcSubFace(), cutFaceAdvect::calcSubFace(), cutFaceIso::calcSubFace(), cutFaceAdvect::calcSubFace(), and cutFacePLIC::calcSubFace().
calcSubFace() [2/3]
void calcSubFace (const label faceI, const scalarList & pointStatus, const scalarList & weights, label firstFullySubmergedPoint, DynamicList< point > & subFacePoints, DynamicList< point > & surfacePoints, label & faceStatus, vector & subFaceCentre, vector & subFaceArea) protected
Definition at line 109 of file cutFace.C.
References PtrList< T >::append(), f(), p, points, UPtrList< T >::size(), UList< T >::size(), and Foam::Zero.
calcSubFaceCentreAndArea()
void calcSubFaceCentreAndArea (DynamicList< point > & subFacePoints, vector & subFaceCentre, vector & subFaceArea) protected
Definition at line 258 of file cutFace.C.
References triangle< Point, PointRef >::areaNormal(), triangle< Point, PointRef >::centre(), Foam::mag(), n, nPoints, UPtrList< T >::size(), and Foam::Zero.
Referenced by cutFace::calcSubFace().
calcSubFace() [3/3]
void calcSubFace (const face & f, const pointField & points, const scalarList & pointStatus, label firstFullySubmergedPoint, DynamicList< point > & subFacePoints, DynamicList< point > & surfacePoints, label & faceStatus, vector & subFaceCentre, vector & subFaceArea) protected
Definition at line 184 of file cutFace.C.
References PtrList< T >::append(), f(), p, points, UPtrList< T >::size(), UList< T >::size(), and Foam::Zero.
Member Data Documentation
debug
int debug = 0 static
Definition at line 130 of file cutFace.H.
Referenced by isoAdvection::isoAdvection().
The documentation for this class was generated from the following files:
src/transportModels/geometricVoF/cellCuts/cutFace/cutFace.H
src/transportModels/geometricVoF/cellCuts/cutFace/cutFace.C