OpenFOAM: alphatJayatillekeWallFunctionFvPatchScalarField Class Reference
alphatJayatillekeWallFunctionFvPatchScalarField Class Reference
Turbulence models » Compressible turbulence » Boundary conditions » Wall functions
This boundary condition provides a thermal wall function for turbulent thermal diffusivity (usuallyalphat) based on the Jayatilleke model.
#include <alphatJayatillekeWallFunctionFvPatchScalarField.H>
Public Member Functions
TypeName ("compressible::alphatJayatillekeWallFunction")
alphatJayatillekeWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
alphatJayatillekeWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
alphatJayatillekeWallFunctionFvPatchScalarField (const alphatJayatillekeWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
alphatJayatillekeWallFunctionFvPatchScalarField (const alphatJayatillekeWallFunctionFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
alphatJayatillekeWallFunctionFvPatchScalarField (const alphatJayatillekeWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual void updateCoeffs ()
void write (Ostream &) const
Detailed Description
This boundary condition provides a thermal wall function for turbulent thermal diffusivity (usuallyalphat) based on the Jayatilleke model.
Usage
Example of the boundary condition specification:
<patchName>
{
    // Mandatory entries
    type            alphatJayatillekeWallFunction;
    // Optional entries
    Prt             <scalar>;
    kappa           <scalar>;
    E               <scalar>;
    // Inherited entries
    ...
}
where the entries mean:
Property Description Type Reqd Deflt
type Type name: alphatJayatillekeWallFunction word yes -
Prt Turbulent Prandtl number scalar no 0.85
kappa von Karman constant scalar no 0.41
E Wall roughness parameter scalar no 9.8
The inherited entries are elaborated in:
fixedValueFvPatchFields.H
Source files
alphatJayatillekeWallFunctionFvPatchScalarField.H
alphatJayatillekeWallFunctionFvPatchScalarField.C
Definition at line 114 of file alphatJayatillekeWallFunctionFvPatchScalarField.H.
Constructor & Destructor Documentation
alphatJayatillekeWallFunctionFvPatchScalarField() [1/5]
alphatJayatillekeWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 131 of file alphatJayatillekeWallFunctionFvPatchScalarField.C.
alphatJayatillekeWallFunctionFvPatchScalarField() [2/5]
alphatJayatillekeWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 163 of file alphatJayatillekeWallFunctionFvPatchScalarField.C.
alphatJayatillekeWallFunctionFvPatchScalarField() [3/5]
alphatJayatillekeWallFunctionFvPatchScalarField (const alphatJayatillekeWallFunctionFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 147 of file alphatJayatillekeWallFunctionFvPatchScalarField.C.
alphatJayatillekeWallFunctionFvPatchScalarField() [4/5]
alphatJayatillekeWallFunctionFvPatchScalarField (const alphatJayatillekeWallFunctionFvPatchScalarField & awfpsf)
Definition at line 180 of file alphatJayatillekeWallFunctionFvPatchScalarField.C.
alphatJayatillekeWallFunctionFvPatchScalarField() [5/5]
alphatJayatillekeWallFunctionFvPatchScalarField (const alphatJayatillekeWallFunctionFvPatchScalarField & awfpsf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 195 of file alphatJayatillekeWallFunctionFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("compressible::alphatJayatillekeWallFunction")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 200 of file alphatJayatillekeWallFunctionFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 216 of file alphatJayatillekeWallFunctionFvPatchScalarField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 213 of file alphatJayatillekeWallFunctionFvPatchScalarField.C.
References A, alphaEff(), B, Foam::endl(), forAll, IOobject::groupName(), Foam::Info, Foam::log(), Foam::mag(), magUp, Foam::max(), Foam::nl, fvPatchField< Type >::patchInternalField(), Pr(), fvPatchField< Type >::snGrad(), Foam::sqr(), fvPatchField< Type >::updateCoeffs(), uTau, y, and yPlus.
write()
void write (Ostream & os) const
Definition at line 320 of file alphatJayatillekeWallFunctionFvPatchScalarField.C.
References os(), fvPatchField< Type >::write(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/thermoTools/derivedFvPatchFields/wallFunctions/alphatWallFunctions/alphatJayatillekeWallFunction/alphatJayatillekeWallFunctionFvPatchScalarField.H
src/thermoTools/derivedFvPatchFields/wallFunctions/alphatWallFunctions/alphatJayatillekeWallFunction/alphatJayatillekeWallFunctionFvPatchScalarField.C