OpenFOAM: edgeSurface Class Reference
edgeSurface Class Reference
Description of surface in form of 'cloud of edges'.
#include <edgeSurface.H>
Public Member Functions
ClassName ("edgeSurface")
edgeSurface (const triSurface &surf, const bool isFirstSurface, const surfaceIntersection &inter)
const pointField & points () const
label nSurfacePoints () const
const edgeList & edges () const
label nSurfaceEdges () const
bool isSurfaceEdge (const label edgeI) const
label parentEdge (const label edgeI) const
const labelListList & faceEdges () const
const labelListList & pointEdges () const
void addIntersectionEdges (const label facei, const edgeList &)
Detailed Description
Description of surface in form of 'cloud of edges'.
The 'cloud of edges':
points
edges
faceEdges
parentEdge (edge on surface this edge originates from) and nothing more.
(pointEdges constructed from above data)
Constructed from triSurface and surfaceIntersection. (uses localPoints of surface of course)
Used to easily insert cuts and split faces.
Note
points with surface (local)points first, intersection points last
edges with (split) surface edges first, intersection edges last.
Source files
edgeSurface.H
edgeSurface.C
Definition at line 71 of file edgeSurface.H.
Constructor & Destructor Documentation
edgeSurface()
edgeSurface (const triSurface & surf, const bool isFirstSurface, const surfaceIntersection & inter)
Definition at line 107 of file edgeSurface.C.
References PtrList< T >::append(), e, PrimitivePatch< FaceList, PointField >::edgeFaces(), PrimitivePatch< FaceList, PointField >::edges(), UPtrList< T >::empty(), UPtrList< T >::end(), Foam::endl(), forAll, forAllConstIters, UPtrList< T >::last(), PrimitivePatch< FaceList, PointField >::localPoints(), Foam::name(), PrimitivePatch< FaceList, PointField >::nEdges(), Foam::Pout, UPtrList< T >::size(), UList< T >::size(), List< T >::transfer(), OBJstream::write(), and Foam::writeObjEdges().
Member Function Documentation
ClassName()
ClassName ("edgeSurface")
points()
const pointField & points () const inline
Definition at line 122 of file edgeSurface.H.
nSurfacePoints()
label nSurfacePoints () const inline
Definition at line 127 of file edgeSurface.H.
edges()
const edgeList & edges () const inline
Definition at line 132 of file edgeSurface.H.
nSurfaceEdges()
label nSurfaceEdges () const inline
Definition at line 137 of file edgeSurface.H.
isSurfaceEdge()
bool isSurfaceEdge (const label edgeI) const inline
Definition at line 142 of file edgeSurface.H.
parentEdge()
label parentEdge (const label edgeI) const inline
Definition at line 149 of file edgeSurface.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
faceEdges()
const labelListList & faceEdges () const inline
Definition at line 166 of file edgeSurface.H.
pointEdges()
const labelListList & pointEdges () const inline
Definition at line 172 of file edgeSurface.H.
addIntersectionEdges()
void addIntersectionEdges (const label facei, const edgeList & additionalEdges)
Definition at line 308 of file edgeSurface.C.
References e, UList< T >::end(), Foam::endl(), forAll, Foam::Pout, PtrList< T >::setSize(), and UPtrList< T >::size().
The documentation for this class was generated from the following files:
src/meshTools/triSurface/booleanOps/intersectedSurface/edgeSurface.H
src/meshTools/triSurface/booleanOps/intersectedSurface/edgeSurface.C