OpenFOAM: interfaceEntry Class Reference
interfaceEntry Class Reference
#include <ccmInterfaceDefinitions.H>
Public Member Functions
interfaceEntry ()
interfaceEntry (const label index)
interfaceEntry (const label index, const label boundary0, const label boundary1)
bool inInterface (label bndId) const
bool valid () const
word canonicalName0 () const
word canonicalName1 () const
word canonicalName (label bndId) const
Static Public Member Functions
static bool isInPlace (const std::string &configurationType)
Public Attributes
label id
label bnd0
label bnd1
Friends
Ostream & operator<< (Ostream &os, const interfaceEntry &entry)
Detailed Description
Definition at line 51 of file ccmInterfaceDefinitions.H.
Constructor & Destructor Documentation
interfaceEntry() [1/3]
interfaceEntry () inline
Definition at line 69 of file ccmInterfaceDefinitions.H.
interfaceEntry() [2/3]
interfaceEntry (const label index) inline
Definition at line 78 of file ccmInterfaceDefinitions.H.
interfaceEntry() [3/3]
interfaceEntry (const label index, const label boundary0, const label boundary1) inline
Definition at line 87 of file ccmInterfaceDefinitions.H.
Member Function Documentation
isInPlace()
static bool isInPlace (const std::string & configurationType) inline static
Definition at line 103 of file ccmInterfaceDefinitions.H.
inInterface()
bool inInterface (label bndId) const inline
Definition at line 110 of file ccmInterfaceDefinitions.H.
References interfaceEntry::bnd0, and interfaceEntry::bnd1.
valid()
bool valid () const inline
Definition at line 116 of file ccmInterfaceDefinitions.H.
References interfaceEntry::bnd0, and interfaceEntry::bnd1.
canonicalName0()
word canonicalName0 () const inline
Definition at line 123 of file ccmInterfaceDefinitions.H.
References Foam::name().
Referenced by interfaceEntry::canonicalName().
canonicalName1()
word canonicalName1 () const inline
Definition at line 129 of file ccmInterfaceDefinitions.H.
References Foam::name().
Referenced by interfaceEntry::canonicalName().
canonicalName()
word canonicalName (label bndId) const inline
Definition at line 135 of file ccmInterfaceDefinitions.H.
References interfaceEntry::bnd0, interfaceEntry::bnd1, interfaceEntry::canonicalName0(), interfaceEntry::canonicalName1(), and word::null.
Friends And Related Symbol Documentation
operator<<
Ostream & operator<< (Ostream & os, const interfaceEntry & entry) friend
Definition at line 154 of file ccmInterfaceDefinitions.H.
Member Data Documentation
id
label id
Definition at line 57 of file ccmInterfaceDefinitions.H.
bnd0
label bnd0
Definition at line 60 of file ccmInterfaceDefinitions.H.
Referenced by interfaceEntry::canonicalName(), interfaceEntry::inInterface(), and interfaceEntry::valid().
bnd1
label bnd1
Definition at line 63 of file ccmInterfaceDefinitions.H.
Referenced by interfaceEntry::canonicalName(), interfaceEntry::inInterface(), and interfaceEntry::valid().
The documentation for this class was generated from the following file:
src/conversion/ccm/reader/ccmInterfaceDefinitions.H