OpenFOAM: Istream Class Reference
Istream Class Reference abstract
An Istream is an abstract base class for all input systems (streams, files, token lists etc). The basic operations are construct, close, read token, read primitive and read binary block.
#include <Istream.H>
Public Member Functions
Istream (const Istream &)=default
virtual ~Istream ()=default
Istream (IOstreamOption streamOpt=IOstreamOption())
Istream (IOstreamOption::streamFormat fmt, IOstreamOption::compressionType cmp=IOstreamOption::UNCOMPRESSED)
const token & peekBack () const noexcept
bool peekBack (token &tok)
void putBack (const token &tok)
bool getBack (token &tok)
virtual Istream & read (token &)=0
virtual Istream & read (char &)=0
virtual Istream & read (word &)=0
virtual Istream & read (string &)=0
virtual Istream & read (label &)=0
virtual Istream & read (float &)=0
virtual Istream & read (double &)=0
virtual Istream & read (char *data, std::streamsize count)=0
virtual bool beginRawRead ()=0
virtual bool endRawRead ()=0
virtual Istream & readRaw (char *data, std::streamsize count)=0
virtual void rewind ()=0
bool readBegin (const char *funcName)
bool readEnd (const char *funcName)
char readBeginList (const char *funcName)
char readEndList (const char *funcName)
Istream & operator() () const
Public Member Functions inherited from IOstream
IOstream (const IOstream &)=default
virtual ~IOstream ()=default
IOstream (IOstreamOption streamOpt=IOstreamOption())
IOstream (IOstreamOption::streamFormat fmt, IOstreamOption::versionNumber ver, IOstreamOption::compressionType cmp=IOstreamOption::UNCOMPRESSED)
virtual const fileName & name () const
fileName relativeName () const
virtual bool check (const char *operation) const
bool fatalCheck (const char *operation) const
bool opened () const noexcept
bool closed () const noexcept
bool good () const noexcept
bool eof () const noexcept
bool fail () const noexcept
bool bad () const noexcept
operator bool () const noexcept
bool operator! () const noexcept
unsigned labelByteSize () const noexcept
unsigned scalarByteSize () const noexcept
void setLabelByteSize (unsigned nbytes) noexcept
void setScalarByteSize (unsigned nbytes) noexcept
template<class T = label>
std::enable_if< std::is_integral< T >::value, bool >::type checkLabelSize () const noexcept
template<class T = scalar>
std::enable_if< std::is_floating_point< T >::value, bool >::type checkScalarSize () const noexcept
label lineNumber () const noexcept
label & lineNumber () noexcept
label lineNumber (const label num) noexcept
virtual ios_base::fmtflags flags () const =0
void setEof () noexcept
void setFail () noexcept
void setBad ()
virtual ios_base::fmtflags flags (const ios_base::fmtflags f)=0
ios_base::fmtflags setf (const ios_base::fmtflags f)
ios_base::fmtflags setf (const ios_base::fmtflags f, const ios_base::fmtflags mask)
void unsetf (const ios_base::fmtflags f)
virtual void print (Ostream &os) const
void print (Ostream &os, const int streamState) const
InfoProxy< IOstream > info () const noexcept
Public Member Functions inherited from IOstreamOption
constexpr IOstreamOption (streamFormat fmt=streamFormat::ASCII, compressionType comp=compressionType::UNCOMPRESSED) noexcept
constexpr IOstreamOption (streamFormat fmt, compressionType comp, versionNumber ver) noexcept
constexpr IOstreamOption (streamFormat fmt, versionNumber ver, compressionType comp=compressionType::UNCOMPRESSED) noexcept
IOstreamOption (const IOstreamOption &opt, streamFormat fmt) noexcept
streamFormat format () const noexcept
streamFormat format (const streamFormat fmt) noexcept
streamFormat format (const word &formatName)
compressionType compression () const noexcept
compressionType compression (const compressionType comp) noexcept
compressionType compression (const word &compName)
versionNumber version () const noexcept
versionNumber version (const versionNumber ver) noexcept
versionNumber version (const token &tok)
Protected Member Functions
bool hasPutback () const noexcept
Protected Member Functions inherited from IOstream
void setOpened () noexcept
void setClosed () noexcept
void setState (std::ios_base::iostate state) noexcept
void setGood () noexcept
Additional Inherited Members
Public Types inherited from IOstream
enum streamAccess : char { CLOSED = 0 , OPENED }
Public Types inherited from IOstreamOption
enum streamFormat : char { ASCII = 0 , BINARY }
enum compressionType : char { UNCOMPRESSED = 0 , COMPRESSED }
enum appendType : char { NON_APPEND = 0 , APPEND }
enum atomicType : char { NON_ATOMIC = 0 , ATOMIC }
Static Public Member Functions inherited from IOstream
static unsigned int defaultPrecision () noexcept
static unsigned int defaultPrecision (unsigned int prec) noexcept
Static Public Member Functions inherited from IOstreamOption
static streamFormat formatEnum (const word &formatName, const streamFormat deflt=streamFormat::ASCII)
static streamFormat formatEnum (const word &key, const dictionary &dict, const streamFormat deflt=streamFormat::ASCII)
static compressionType compressionEnum (const word &compName, const compressionType deflt=compressionType::UNCOMPRESSED)
static compressionType compressionEnum (const word &key, const dictionary &dict, const compressionType deflt=compressionType::UNCOMPRESSED)
Static Public Attributes inherited from IOstream
static unsigned int precision_
Static Public Attributes inherited from IOstreamOption
static const Enum< streamFormat > formatNames
static const versionNumber currentVersion
Protected Attributes inherited from IOstream
std::ios_base::iostate ioState_
streamAccess openClosed_
unsigned char sizeofLabel_
unsigned char sizeofScalar_
label lineNumber_
Static Protected Attributes inherited from IOstream
static fileName staticName_
Detailed Description
An Istream is an abstract base class for all input systems (streams, files, token lists etc). The basic operations are construct, close, read token, read primitive and read binary block.
In addition, version control and line number counting is incorporated. Usually one would use the read primitive member functions, but if one were reading a stream on unknown data sequence one can read token by token, and then analyse.
Source files
Istream.H
Istream.C
Definition at line 57 of file Istream.H.
Constructor & Destructor Documentation
Istream() [1/3]
Istream (const Istream &) default
~Istream()
virtual ~Istream () virtual default
Istream() [2/3]
Istream (IOstreamOption streamOpt = IOstreamOption()) inline explicit
Definition at line 96 of file Istream.H.
Istream() [3/3]
Istream (IOstreamOption::streamFormat fmt, IOstreamOption::compressionType cmp = IOstreamOption::UNCOMPRESSED) inline explicit
Definition at line 103 of file Istream.H.
Member Function Documentation
hasPutback()
bool hasPutback () const inline protected noexcept
Definition at line 75 of file Istream.H.
Referenced by ITstream::hasPutback().
peekBack() [1/2]
const Foam::token & peekBack () const noexcept
Definition at line 42 of file Istream.C.
References token::undefinedToken.
peekBack() [2/2]
bool peekBack (token & tok)
Definition at line 48 of file Istream.C.
putBack()
void putBack (const token & tok)
Definition at line 63 of file Istream.C.
References Foam::exit(), Foam::FatalIOError, and FatalIOErrorInFunction.
getBack()
bool getBack (token & tok)
Definition at line 85 of file Istream.C.
References Foam::exit(), Foam::FatalIOError, and FatalIOErrorInFunction.
Referenced by UIPstreamBase::read(), ISstream::read(), and ITstream::read().
read() [1/8]
virtual Istream & read (token &) pure virtual
Implemented in dummyISstream, ensightReadFile, UIPstreamBase, UIPstream, UIPBstream, ISstream, primitiveEntry, and ITstream.
read() [2/8]
virtual Istream & read (char &) pure virtual
Implemented in primitiveEntry, dummyISstream, ITstream, ensightReadFile, UIPstreamBase, UIPstream, UIPBstream, and ISstream.
read() [3/8]
virtual Istream & read (word &) pure virtual
Implemented in primitiveEntry, dummyISstream, ITstream, ensightReadFile, UIPstreamBase, UIPstream, UIPBstream, and ISstream.
read() [4/8]
virtual Istream & read (string &) pure virtual
Implemented in primitiveEntry, dummyISstream, ITstream, ensightReadFile, UIPstreamBase, UIPstream, UIPBstream, ISstream, and ensightReadFile.
read() [5/8]
virtual Istream & read (label &) pure virtual
Implemented in primitiveEntry, dummyISstream, ITstream, ensightReadFile, UIPstreamBase, UIPstream, UIPBstream, ISstream, and ensightReadFile.
read() [6/8]
virtual Istream & read (float &) pure virtual
Implemented in primitiveEntry, dummyISstream, ITstream, ensightReadFile, UIPstreamBase, UIPstream, UIPBstream, ISstream, and ensightReadFile.
read() [7/8]
virtual Istream & read (double &) pure virtual
Implemented in primitiveEntry, dummyISstream, ITstream, ensightReadFile, UIPstreamBase, UIPstream, UIPBstream, ISstream, and ensightReadFile.
read() [8/8]
virtual Istream & read (char * data, std::streamsize count) pure virtual
Implemented in dummyISstream, ensightReadFile, UIPstreamBase, UIPstream, UIPBstream, ISstream, ensightReadFile, primitiveEntry, and ITstream.
beginRawRead()
virtual bool beginRawRead () pure virtual
Implemented in dummyISstream, UIPstreamBase, ISstream, and ITstream.
endRawRead()
virtual bool endRawRead () pure virtual
Implemented in dummyISstream, UIPstreamBase, ISstream, and ITstream.
readRaw()
virtual Istream & readRaw (char * data, std::streamsize count) pure virtual
Implemented in dummyISstream, UIPstreamBase, ISstream, and ITstream.
rewind()
virtual void rewind () pure virtual
Implemented in dummyISstream, IFstream, IListStream, UIListStream, UIPstreamBase, ISstream, and ITstream.
readBegin()
bool readBegin (const char * funcName)
Definition at line 104 of file Istream.C.
References token::BEGIN_LIST, Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, and Foam::nl.
readEnd()
bool readEnd (const char * funcName)
Definition at line 122 of file Istream.C.
References token::END_LIST, Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, and Foam::nl.
readBeginList()
char readBeginList (const char * funcName)
Definition at line 141 of file Istream.C.
References token::BEGIN_BLOCK, token::BEGIN_LIST, Foam::exit(), Foam::FatalIOError, and FatalIOErrorInFunction.
readEndList()
char readEndList (const char * funcName)
Definition at line 162 of file Istream.C.
References token::END_BLOCK, token::END_LIST, Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, and Foam::nl.
operator()()
Foam::Istream & operator() () const
Definition at line 184 of file Istream.C.
References Foam::check(), IOerror::exit(), Foam::FatalIOError, and FUNCTION_NAME.
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOstreams/IOstreams/Istream.H
src/OpenFOAM/db/IOstreams/IOstreams/Istream.C