OpenFOAM: NVDVTVDV Class Reference
NVDVTVDV Class Reference
Foam::NVDVTVDV.
#include <NVDVTVDV.H>
Public Types
typedef vector phiType
typedef tensor gradPhiType
Public Member Functions
NVDVTVDV ()
scalar phict (const scalar faceFlux, const vector &phiP, const vector &phiN, const tensor &gradcP, const tensor &gradcN, const vector &d) const
scalar r (const scalar faceFlux, const vector &phiP, const vector &phiN, const tensor &gradcP, const tensor &gradcN, const vector &d) const
Detailed Description
Foam::NVDVTVDV.
Definition at line 39 of file NVDVTVDV.H.
Member Typedef Documentation
phiType
typedef vector phiType
Definition at line 44 of file NVDVTVDV.H.
gradPhiType
typedef tensor gradPhiType
Definition at line 45 of file NVDVTVDV.H.
Constructor & Destructor Documentation
NVDVTVDV()
NVDVTVDV () inline
Definition at line 49 of file NVDVTVDV.H.
Member Function Documentation
phict()
scalar phict (const scalar faceFlux, const vector & phiP, const vector & phiN, const tensor & gradcP, const tensor & gradcN, const vector & d) const inline
Definition at line 55 of file NVDVTVDV.H.
References Foam::mag(), and Foam::sign().
r()
scalar r (const scalar faceFlux, const vector & phiP, const vector & phiN, const tensor & gradcP, const tensor & gradcN, const vector & d) const inline
Definition at line 90 of file NVDVTVDV.H.
References Foam::mag(), and Foam::sign().
The documentation for this class was generated from the following file:
src/finiteVolume/interpolation/surfaceInterpolation/limitedSchemes/LimitedScheme/NVDVTVDV.H