OpenFOAM: atmBoundaryLayerInletKFvPatchScalarField Class Reference
atmBoundaryLayerInletKFvPatchScalarField Class Reference
Turbulence models » RAS turbulence » Boundary conditions | Boundary conditions » Inlet
This boundary condition provides a log-law type ground-normal inlet boundary condition for the turbulent kinetic energy (i.e. k) for homogeneous, two-dimensional, dry-air, equilibrium and neutral atmospheric boundary layer modelling.
#include <atmBoundaryLayerInletKFvPatchScalarField.H>
Public Member Functions
TypeName ("atmBoundaryLayerInletK")
atmBoundaryLayerInletKFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
atmBoundaryLayerInletKFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
atmBoundaryLayerInletKFvPatchScalarField (const atmBoundaryLayerInletKFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
virtual tmp< fvPatchScalarField > clone () const
atmBoundaryLayerInletKFvPatchScalarField (const atmBoundaryLayerInletKFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual void updateCoeffs ()
virtual void autoMap (const fvPatchFieldMapper &)
virtual void rmap (const fvPatchScalarField &, const labelList &)
virtual void write (Ostream &) const
Public Member Functions inherited from atmBoundaryLayer
atmBoundaryLayer (const Time &time, const polyPatch &pp)
atmBoundaryLayer (const Time &time, const polyPatch &pp, const dictionary &dict)
atmBoundaryLayer (const atmBoundaryLayer &abl, const fvPatch &patch, const fvPatchFieldMapper &mapper)
atmBoundaryLayer (const atmBoundaryLayer &)
vector flowDir () const
vector zDir () const
tmp< scalarField > Ustar (const scalarField &z0) const
void autoMap (const fvPatchFieldMapper &)
void rmap (const atmBoundaryLayer &, const labelList &)
tmp< vectorField > U (const vectorField &pCf) const
tmp< scalarField > k (const vectorField &pCf) const
tmp< scalarField > epsilon (const vectorField &pCf) const
tmp< scalarField > omega (const vectorField &pCf) const
void write (Ostream &) const
Additional Inherited Members
Protected Attributes inherited from atmBoundaryLayer
bool initABL_
Detailed Description
This boundary condition provides a log-law type ground-normal inlet boundary condition for the turbulent kinetic energy (i.e. k) for homogeneous, two-dimensional, dry-air, equilibrium and neutral atmospheric boundary layer modelling.
The ground-normal k profile expression:
where
= Ground-normal turbulent kinetic energy profile [m^2/s^3]
= Friction velocity [m/s]
= Empirical model constant [-]
= Curve-fitting coefficient for YGCJ profiles [-]
= Curve-fitting coefficient for YGCJ profiles [-]
Required fields:
        k    | Turbulent kinetic energy                         [m2/s2]
Usage
Example of the boundary condition specification:
inlet
{
    // Mandatory entries (unmodifiable)
    type            atmBoundaryLayerInletK;
    // Mandatory/Optional (inherited) entries (unmodifiable)
    ...
    flowDir         (1 0 0);    // not used
    zDir            (0 0 1);    // not used
}
where the entries mean:
Property Description Type Reqd Deflt
type Type name: atmBoundaryLayerInletK word yes -
The inherited entries are elaborated in:
atmBoundaryLayer.H
inletOutletFvPatchField.H
See also
Foam::atmBoundaryLayer
Foam::atmBoundaryLayerInletVelocityFvPatchVectorField
Foam::atmBoundaryLayerInletEpsilonFvPatchScalarField
Foam::atmBoundaryLayerInletOmegaFvPatchScalarField
Source files
atmBoundaryLayerInletKFvPatchScalarField.H
atmBoundaryLayerInletKFvPatchScalarField.C
Definition at line 139 of file atmBoundaryLayerInletKFvPatchScalarField.H.
Constructor & Destructor Documentation
atmBoundaryLayerInletKFvPatchScalarField() [1/4]
atmBoundaryLayerInletKFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 35 of file atmBoundaryLayerInletKFvPatchScalarField.C.
atmBoundaryLayerInletKFvPatchScalarField() [2/4]
atmBoundaryLayerInletKFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 47 of file atmBoundaryLayerInletKFvPatchScalarField.C.
References dict, atmBoundaryLayer::initABL_, k, IOobjectOption::MUST_READ, and Field< scalar >::operator=().
atmBoundaryLayerInletKFvPatchScalarField() [3/4]
atmBoundaryLayerInletKFvPatchScalarField (const atmBoundaryLayerInletKFvPatchScalarField & psf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 76 of file atmBoundaryLayerInletKFvPatchScalarField.C.
atmBoundaryLayerInletKFvPatchScalarField() [4/4]
atmBoundaryLayerInletKFvPatchScalarField (const atmBoundaryLayerInletKFvPatchScalarField & psf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 90 of file atmBoundaryLayerInletKFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("atmBoundaryLayerInletK")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 179 of file atmBoundaryLayerInletKFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 195 of file atmBoundaryLayerInletKFvPatchScalarField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 104 of file atmBoundaryLayerInletKFvPatchScalarField.C.
References k.
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Definition at line 117 of file atmBoundaryLayerInletKFvPatchScalarField.C.
References atmBoundaryLayer::autoMap().
rmap()
void rmap (const fvPatchScalarField & psf, const labelList & addr) virtual
Definition at line 127 of file atmBoundaryLayerInletKFvPatchScalarField.C.
References atmBoundaryLayer::rmap().
write()
void write (Ostream & os) const virtual
Definition at line 142 of file atmBoundaryLayerInletKFvPatchScalarField.C.
References os(), atmBoundaryLayer::write(), fvPatchField< Type >::write(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/atmosphericModels/derivedFvPatchFields/atmBoundaryLayerInletK/atmBoundaryLayerInletKFvPatchScalarField.H
src/atmosphericModels/derivedFvPatchFields/atmBoundaryLayerInletK/atmBoundaryLayerInletKFvPatchScalarField.C