OpenFOAM: isoAdvection Class Reference
isoAdvection Class Reference
An implementation of the isoAdvector geometric Volume-of-Fluid method advancing the provided volume fraction field (alpha1) in time using the given velocity field, U, and corresponding face fluxes, phi.
#include <isoAdvection.H>
Public Member Functions
TypeName ("isoAdvection")
isoAdvection (volScalarField &alpha1, const surfaceScalarField &phi, const volVectorField &U)
virtual ~isoAdvection ()=default
template<class SpType , class SuType >
void advect (const SpType &Sp, const SuType &Su)
reconstructionSchemes & surf () noexcept
const volScalarField & alpha () const noexcept
const dictionary & dict () const noexcept
void writeSurfaceCells () const
tmp< surfaceScalarField > getRhoPhi (const dimensionedScalar rho1, const dimensionedScalar rho2) const
tmp< surfaceScalarField > getRhoPhi (const volScalarField &rho1, const volScalarField &rho2)
const surfaceScalarField & alphaPhi () const noexcept
scalar advectionTime () const noexcept
void writeIsoFaces (const DynamicList< List< point > > &isoFacePts) const
Detailed Description
An implementation of the isoAdvector geometric Volume-of-Fluid method advancing the provided volume fraction field (alpha1) in time using the given velocity field, U, and corresponding face fluxes, phi.
References:
Main isoAdvector idea:
    Roenby, J., Bredmose, H. and Jasak, H. (2016).
    A computational method for sharp interface advection
    Royal Society Open Science, 3
    doi 10.1098/rsos.160405
Calculation of rhoPhi:
    Roenby, J., Bredmose, H., & Jasak, H. (2019).
    IsoAdvector: Geometric VOF on general meshes.
    OpenFOAM® (pp. 281-296). Springer, Cham.
Extension to porous media flows:
    Missios, K., Jacobsen, N. G., Moeller, K., & Roenby, J.
    Using the isoAdvector Geometric VOF Method for Interfacial Flows
    Through Porous Media. MARINE 2021.
Original code supplied by Johan Roenby, DHI (2016) Modified Henning Scheufler, DLR
Source files
isoAdvection.H
isoAdvection.C
isoAdvectionTemplates.C
Definition at line 87 of file isoAdvection.H.
Constructor & Destructor Documentation
isoAdvection()
isoAdvection (volScalarField & alpha1, const surfaceScalarField & phi, const volVectorField & U)
Definition at line 48 of file isoAdvection.C.
References cutFace::debug, Foam::dimTime, Foam::dimVol, Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::gMax(), Foam::gMin(), Foam::name(), Foam::New(), IOobjectOption::NO_WRITE, UPstream::parRun(), porosityProperties(), GeometricField< Type, PatchField, GeoMesh >::primitiveField(), and IOobjectOption::READ_IF_PRESENT.
~isoAdvection()
virtual ~isoAdvection () virtual default
Member Function Documentation
TypeName()
TypeName ("isoAdvection")
advect()
template<class SpType , class SuType > void advect (const SpType & Sp, const SuType & Su)
Definition at line 384 of file isoAdvectionTemplates.C.
References addProfilingInFunction, DebugInfo, DebugInFunction, Foam::endl(), zeroField::field(), Foam::gMax(), Foam::gMin(), Foam::Info, Sp, Su, and Foam::fvc::surfaceIntegrate().
surf()
reconstructionSchemes & surf () inline noexcept
Definition at line 330 of file isoAdvection.H.
alpha()
const volScalarField & alpha () const inline noexcept
Definition at line 336 of file isoAdvection.H.
dict()
const dictionary & dict () const inline noexcept
Definition at line 342 of file isoAdvection.H.
writeSurfaceCells()
void writeSurfaceCells () const
Definition at line 641 of file isoAdvection.C.
References IOobjectOption::NO_READ.
getRhoPhi() [1/2]
tmp< surfaceScalarField > getRhoPhi (const dimensionedScalar rho1, const dimensionedScalar rho2) const inline
Definition at line 351 of file isoAdvection.H.
References rho1, rho2, and fvMesh::time().
getRhoPhi() [2/2]
tmp< surfaceScalarField > getRhoPhi (const volScalarField & rho1, const volScalarField & rho2) inline
Definition at line 368 of file isoAdvection.H.
References Foam::fvc::interpolate(), rho1, and rho2.
alphaPhi()
const surfaceScalarField & alphaPhi () const inline noexcept
Definition at line 386 of file isoAdvection.H.
advectionTime()
scalar advectionTime () const inline noexcept
Definition at line 392 of file isoAdvection.H.
writeIsoFaces()
void writeIsoFaces (const DynamicList< List< point > > & isoFacePts) const
Definition at line 665 of file isoAdvection.C.
References Foam::endl(), Pstream::gatherList(), Foam::Info, UPstream::master(), Foam::mkDir(), UPstream::myProcNo(), OFstream::name(), Foam::nl, UPstream::nProcs(), os(), UPstream::parRun(), word::printf(), and OBJstream::writeFace().
The documentation for this class was generated from the following files:
src/transportModels/geometricVoF/advectionSchemes/isoAdvection/isoAdvection.H
src/transportModels/geometricVoF/advectionSchemes/isoAdvection/isoAdvection.C
src/transportModels/geometricVoF/advectionSchemes/isoAdvection/isoAdvectionTemplates.C