OpenFOAM: boundaryRadiationProperties Class Reference
boundaryRadiationProperties Class Reference
Boundary radiation properties holder.
#include <boundaryRadiationProperties.H>
Public Member Functions
TypeName ("boundaryRadiationProperties")
boundaryRadiationProperties (const fvMesh &)
const labelList faceZoneIds () const
tmp< scalarField > emissivity (const label patchI, const label bandI=0, vectorField *incomingDirection=nullptr, scalarField *T=nullptr) const
scalar faceEmissivity (const label patchI, const label faceI, const label bandI=0, vector incomingDirection=Zero, scalar T=0) const
tmp< scalarField > absorptivity (const label patchI, const label bandI=0, vectorField *incomingDirection=nullptr, scalarField *T=nullptr) const
scalar faceAbsorptivity (const label patchI, const label faceI, const label bandI=0, vector incomingDirection=Zero, scalar T=0) const
tmp< scalarField > transmissivity (const label patchI, const label bandI=0, vectorField *incomingDirection=nullptr, scalarField *T=nullptr) const
scalar faceTransmissivity (const label patchI, const label faceI, const label bandI=0, vector incomingDirection=Zero, scalar T=0) const
tmp< scalarField > zoneTransmissivity (const label zoneI, const labelUList &faceIDs, const label bandI=0, vector incomingDirection=Zero, scalar T=0) const
tmp< scalarField > diffReflectivity (const label patchI, const label bandI=0, vectorField *incomingDirection=nullptr, scalarField *T=nullptr) const
scalar faceDiffReflectivity (const label patchI, const label faceI, const label bandI=0, vector incomingDirection=Zero, scalar T=0) const
tmp< scalarField > specReflectivity (const label patchI, const label bandI=0, vectorField *incomingDirection=nullptr, scalarField *T=nullptr) const
scalar faceSpecReflectivity (const label patchI, const label faceI, const label bandI=0, vector incomingDirection=Zero, scalar T=0) const
~boundaryRadiationProperties ()=default
Public Member Functions inherited from MeshObject< fvMesh, Foam::GeometricMeshObject, boundaryRadiationProperties >
MeshObject (const fvMesh &mesh)
MeshObject (const word &objName, const fvMesh &mesh)
virtual ~MeshObject ()=default
const fvMesh & mesh () const noexcept
virtual bool writeData (Ostream &os) const
Additional Inherited Members
Static Public Member Functions inherited from MeshObject< fvMesh, Foam::GeometricMeshObject, boundaryRadiationProperties >
static const boundaryRadiationProperties & New (const fvMesh &mesh, Args &&... args)
static const boundaryRadiationProperties & New (const word &objName, const fvMesh &mesh, Args &&... args)
static bool Delete (const word &objName, const fvMesh &mesh)
static bool Delete (const fvMesh &mesh)
Protected Attributes inherited from MeshObject< fvMesh, Foam::GeometricMeshObject, boundaryRadiationProperties >
const fvMesh & mesh_
Detailed Description
Boundary radiation properties holder.
Source files
boundaryRadiationProperties.H
boundaryRadiationProperties.C
Definition at line 52 of file boundaryRadiationProperties.H.
Constructor & Destructor Documentation
boundaryRadiationProperties()
boundaryRadiationProperties (const fvMesh & mesh) explicit
Definition at line 37 of file boundaryRadiationProperties.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, keyType::LITERAL, MeshObject< fvMesh, Foam::GeometricMeshObject, boundaryRadiationProperties >::mesh(), IOobjectOption::MUST_READ, boundaryRadiationPropertiesPatch::New(), Foam::nl, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, pbm, pp(), radiation(), keyType::REGEX, and PtrList< T >::set().
~boundaryRadiationProperties()
~boundaryRadiationProperties () default
Member Function Documentation
TypeName()
TypeName ("boundaryRadiationProperties")
faceZoneIds()
const labelList faceZoneIds () const inline
Definition at line 87 of file boundaryRadiationProperties.H.
References PtrList< T >::append(), forAll, and UPtrList< T >::test().
emissivity()
Foam::tmp< Foam::scalarField > emissivity (const label patchI, const label bandI = 0, vectorField * incomingDirection = nullptr, scalarField * T = nullptr) const
Definition at line 181 of file boundaryRadiationProperties.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, mesh, tmp< T >::New(), and T.
faceEmissivity()
Foam::scalar faceEmissivity (const label patchI, const label faceI, const label bandI = 0, vector incomingDirection = Zero, scalar T = 0) const
Definition at line 209 of file boundaryRadiationProperties.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, mesh, T, and Foam::Zero.
absorptivity()
Foam::tmp< Foam::scalarField > absorptivity (const label patchI, const label bandI = 0, vectorField * incomingDirection = nullptr, scalarField * T = nullptr) const
Definition at line 240 of file boundaryRadiationProperties.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, mesh, tmp< T >::New(), and T.
faceAbsorptivity()
Foam::scalar faceAbsorptivity (const label patchI, const label faceI, const label bandI = 0, vector incomingDirection = Zero, scalar T = 0) const
Definition at line 268 of file boundaryRadiationProperties.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, mesh, T, and Foam::Zero.
transmissivity()
Foam::tmp< Foam::scalarField > transmissivity (const label patchI, const label bandI = 0, vectorField * incomingDirection = nullptr, scalarField * T = nullptr) const
Definition at line 299 of file boundaryRadiationProperties.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, mesh, tmp< T >::New(), and T.
faceTransmissivity()
Foam::scalar faceTransmissivity (const label patchI, const label faceI, const label bandI = 0, vector incomingDirection = Zero, scalar T = 0) const
Definition at line 327 of file boundaryRadiationProperties.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, mesh, T, and Foam::Zero.
zoneTransmissivity()
Foam::tmp< Foam::scalarField > zoneTransmissivity (const label zoneI, const labelUList & faceIDs, const label bandI = 0, vector incomingDirection = Zero, scalar T = 0) const
Definition at line 358 of file boundaryRadiationProperties.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, fld(), forAll, mesh, tmp< T >::New(), UPtrList< T >::size(), and T.
diffReflectivity()
Foam::tmp< Foam::scalarField > diffReflectivity (const label patchI, const label bandI = 0, vectorField * incomingDirection = nullptr, scalarField * T = nullptr) const
Definition at line 395 of file boundaryRadiationProperties.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, mesh, tmp< T >::New(), and T.
faceDiffReflectivity()
Foam::scalar faceDiffReflectivity (const label patchI, const label faceI, const label bandI = 0, vector incomingDirection = Zero, scalar T = 0) const
Definition at line 423 of file boundaryRadiationProperties.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, mesh, T, and Foam::Zero.
specReflectivity()
Foam::tmp< Foam::scalarField > specReflectivity (const label patchI, const label bandI = 0, vectorField * incomingDirection = nullptr, scalarField * T = nullptr) const
Definition at line 454 of file boundaryRadiationProperties.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, mesh, tmp< T >::New(), and T.
faceSpecReflectivity()
Foam::scalar faceSpecReflectivity (const label patchI, const label faceI, const label bandI = 0, vector incomingDirection = Zero, scalar T = 0) const
Definition at line 482 of file boundaryRadiationProperties.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, mesh, T, and Foam::Zero.
The documentation for this class was generated from the following files:
src/thermophysicalModels/radiation/submodels/boundaryRadiationProperties/boundaryRadiationProperties.H
src/thermophysicalModels/radiation/submodels/boundaryRadiationProperties/boundaryRadiationProperties.C