OpenFOAM: solidAbsorption Class Reference
solidAbsorption Class Reference
Radiation absorptivity-emissivity model to be used on walls on inter-region patches when the solid opaque radiation model is used in the solid and the wall emissivity and absorptivity are taken from the solid radiation properties.
#include <solidAbsorption.H>
Public Member Functions
TypeName ("solidAbsorption")
solidAbsorption (const dictionary &dict, const polyPatch &pp)
virtual ~solidAbsorption ()
tmp< scalarField > a (const label bandI=0, vectorField *incomingDirection=nullptr, scalarField *T=nullptr) const
scalar a (const label faceI, const label bandI=0, const vector dir=Zero, const scalar T=0) const
tmp< scalarField > e (const label bandI=0, vectorField *incomingDirection=nullptr, scalarField *T=nullptr) const
scalar e (const label faceI, const label bandI=0, const vector dir=Zero, const scalar T=0) const
bool isGrey () const
label nBands () const
Public Member Functions inherited from wallAbsorptionEmissionModel
TypeName ("wallAbsorptionEmissionModel")
declareRunTimeSelectionTable (autoPtr, wallAbsorptionEmissionModel, dictionary,(const dictionary &dict, const polyPatch &pp),(dict, pp))
wallAbsorptionEmissionModel (const dictionary &dict, const polyPatch &pp)
virtual ~wallAbsorptionEmissionModel ()
Additional Inherited Members
Static Public Member Functions inherited from wallAbsorptionEmissionModel
static autoPtr< wallAbsorptionEmissionModel > New (const dictionary &dict, const polyPatch &pp)
Protected Attributes inherited from wallAbsorptionEmissionModel
const polyPatch & pp_
Detailed Description
Radiation absorptivity-emissivity model to be used on walls on inter-region patches when the solid opaque radiation model is used in the solid and the wall emissivity and absorptivity are taken from the solid radiation properties.
Usage
Example usage
    wallAbsorptionEmissionModel
    {
        type            solidAbsorption;
    };
Source files
solidAbsorption.H
solidAbsorption.C
Definition at line 63 of file solidAbsorption.H.
Constructor & Destructor Documentation
solidAbsorption()
solidAbsorption (const dictionary & dict, const polyPatch & pp)
Definition at line 63 of file solidAbsorption.C.
References Foam::abort(), FatalErrorInFunction, Foam::FatalIOError, and pp().
~solidAbsorption()
~solidAbsorption () virtual
Definition at line 84 of file solidAbsorption.C.
Member Function Documentation
TypeName()
TypeName ("solidAbsorption")
a() [1/2]
Foam::tmp< Foam::scalarField > a (const label bandI = 0, vectorField * incomingDirection = nullptr, scalarField * T = nullptr) const virtual
Implements wallAbsorptionEmissionModel.
Definition at line 90 of file solidAbsorption.C.
References UPstream::msgType(), tmp< T >::New(), and radiation().
a() [2/2]
Foam::scalar a (const label faceI, const label bandI = 0, const vector dir = Zero, const scalar T = 0) const virtual
Implements wallAbsorptionEmissionModel.
Definition at line 132 of file solidAbsorption.C.
e() [1/2]
Foam::tmp< Foam::scalarField > e (const label bandI = 0, vectorField * incomingDirection = nullptr, scalarField * T = nullptr) const virtual
Implements wallAbsorptionEmissionModel.
Definition at line 143 of file solidAbsorption.C.
References UPstream::msgType(), tmp< T >::New(), and radiation().
e() [2/2]
Foam::scalar e (const label faceI, const label bandI = 0, const vector dir = Zero, const scalar T = 0) const virtual
Implements wallAbsorptionEmissionModel.
Definition at line 186 of file solidAbsorption.C.
References e.
isGrey()
bool isGrey () const inline virtual
Implements wallAbsorptionEmissionModel.
Definition at line 130 of file solidAbsorption.H.
nBands()
Foam::label nBands () const inline virtual
Implements wallAbsorptionEmissionModel.
Definition at line 198 of file solidAbsorption.C.
References radiation().
The documentation for this class was generated from the following files:
src/thermophysicalModels/radiation/submodels/wallAbsorptionEmissionModel/solidAbsorption/solidAbsorption.H
src/thermophysicalModels/radiation/submodels/wallAbsorptionEmissionModel/solidAbsorption/solidAbsorption.C