OpenFOAM: cellTable Class Reference
cellTable Class Reference
The cellTable persistent data saved as a Map<dictionary>.
#include <cellTable.H>
Public Member Functions
cellTable ()
cellTable (const objectRegistry &, const word &name="cellTable", const fileName &instance="constant")
~cellTable ()=default
label append (const dictionary &)
label findIndex (const word &name) const
word name (const label id) const
Map< word > names () const
Map< word > names (const wordRes &patterns) const
Map< word > selectType (const word &materialType) const
Map< word > fluids () const
Map< word > shells () const
Map< word > solids () const
Map< word > materialTypes () const
void setMaterial (const label, const word &)
void setName (const label, const word &)
void setName (const label)
void readDict (const objectRegistry &, const word &name="cellTable", const fileName &instance="constant")
void writeDict (const objectRegistry &, const word &name="cellTable", const fileName &instance="constant") const
void operator= (const cellTable &)
void operator= (const Map< dictionary > &)
void operator= (const polyMesh &)
void addCellZones (polyMesh &, const labelList &tableIds) const
void combine (const dictionary &mapDict, labelList &tableIds)
Public Member Functions inherited from Map< dictionary >
Map ()
Map (const label size)
Map (Istream &is)
Map (const this_type &map)
Map (this_type &&map)
Map (std::initializer_list< std::pair< label, dictionary > > map)
void operator= (const this_type &rhs)
void operator= (this_type &&rhs)
Public Member Functions inherited from HashTable< T, Key, Hash >
HashTable ()
HashTable (const label size)
HashTable (Istream &is, const label size=128)
HashTable (const this_type &ht)
HashTable (this_type &&rhs)
HashTable (std::initializer_list< std::pair< Key, T > > list)
~HashTable ()
bool empty () const noexcept
label size () const noexcept
label capacity () const noexcept
T & at (const Key &key)
const T & at (const Key &key) const
bool contains (const Key &key) const
iterator find (const Key &key)
const_iterator find (const Key &key) const
const_iterator cfind (const Key &key) const
const T & lookup (const Key &key, const T &deflt) const
List< Key > toc () const
List< Key > sortedToc () const
template<class Compare >
List< Key > sortedToc (const Compare &comp) const
template<class UnaryPredicate >
List< Key > tocKeys (const UnaryPredicate &pred, const bool invert=false) const
template<class UnaryPredicate >
List< Key > tocValues (const UnaryPredicate &pred, const bool invert=false) const
template<class BinaryPredicate >
List< Key > tocEntries (const BinaryPredicate &pred, const bool invert=false) const
UPtrList< const node_type > csorted () const
UPtrList< const node_type > sorted () const
UPtrList< node_type > sorted ()
template<class UnaryPredicate >
label countKeys (const UnaryPredicate &pred, const bool invert=false) const
template<class UnaryPredicate >
label countValues (const UnaryPredicate &pred, const bool invert=false) const
template<class BinaryPredicate >
label countEntries (const BinaryPredicate &pred, const bool invert=false) const
template<class... Args>
bool emplace (const Key &key, Args &&... args)
template<class... Args>
bool emplace_set (const Key &key, Args &&... args)
bool insert (const Key &key, const T &obj)
bool insert (const Key &key, T &&obj)
bool set (const Key &key, const T &obj)
bool set (const Key &key, T &&obj)
bool erase (const iterator &iter)
bool erase (const Key &key)
template<class AnyType , class AnyHash >
label erase (const HashTable< AnyType, Key, AnyHash > &other)
label erase (std::initializer_list< Key > keys)
template<class InputIter >
label erase (InputIter first, InputIter last)
template<unsigned N>
label erase (const FixedList< Key, N > &keys)
label erase (const UList< Key > &keys)
template<class AnyType , class AnyHash >
label retain (const HashTable< AnyType, Key, AnyHash > &other)
template<class UnaryPredicate >
label filterKeys (const UnaryPredicate &pred, const bool pruning=false)
template<class UnaryPredicate >
label filterValues (const UnaryPredicate &pred, const bool pruning=false)
template<class BinaryPredicate >
label filterEntries (const BinaryPredicate &pred, const bool pruning=false)
void resize (const label sz)
void clear ()
void clearStorage ()
void swap (HashTable< T, Key, Hash > &rhs)
void transfer (HashTable< T, Key, Hash > &rhs)
void merge (HashTable< T, Key, Hash > &source)
void merge (HashTable< T, Key, Hash > &&source)
T & operator[] (const Key &key)
const T & operator[] (const Key &key) const
T & operator() (const Key &key)
T & operator() (const Key &key, const T &deflt)
void operator= (const this_type &rhs)
void operator= (std::initializer_list< std::pair< Key, T > > rhs)
void operator= (this_type &&rhs)
bool operator== (const this_type &rhs) const
bool operator!= (const this_type &rhs) const
this_type & operator+= (const this_type &rhs)
const_iterator_pair< const_key_iterator, this_type > keys () const
iterator begin ()
const_iterator begin () const
const_iterator cbegin () const
iterator end () noexcept
const_iterator end () const noexcept
constexpr const_iterator cend () const noexcept
Ostream & printInfo (Ostream &os) const
Ostream & writeKeys (Ostream &os, const label shortLen=0) const
bool found (const Key &key) const
template<class Compare >
Foam::List< Key > sortedToc (const Compare &comp) const
template<class UnaryPredicate >
Foam::List< Key > tocKeys (const UnaryPredicate &pred, const bool invert) const
template<class UnaryPredicate >
Foam::List< Key > tocValues (const UnaryPredicate &pred, const bool invert) const
template<class BinaryPredicate >
Foam::List< Key > tocEntries (const BinaryPredicate &pred, const bool invert) const
template<class UnaryPredicate >
Foam::label countKeys (const UnaryPredicate &pred, const bool invert) const
template<class UnaryPredicate >
Foam::label countValues (const UnaryPredicate &pred, const bool invert) const
template<class BinaryPredicate >
Foam::label countEntries (const BinaryPredicate &pred, const bool invert) const
template<class InputIter >
Foam::label erase (InputIter first, InputIter last)
template<unsigned N>
Foam::label erase (const FixedList< Key, N > &keys)
template<class AnyType , class AnyHash >
Foam::label erase (const HashTable< AnyType, Key, AnyHash > &other)
template<class AnyType , class AnyHash >
Foam::label retain (const HashTable< AnyType, Key, AnyHash > &other)
template<class UnaryPredicate >
Foam::label filterKeys (const UnaryPredicate &pred, const bool pruning)
template<class UnaryPredicate >
Foam::label filterValues (const UnaryPredicate &pred, const bool pruning)
template<class BinaryPredicate >
Foam::label filterEntries (const BinaryPredicate &pred, const bool pruning)
Public Member Functions inherited from HashTableCore
ClassName ("HashTable")
HashTableCore () noexcept=default
Additional Inherited Members
Public Types inherited from Map< dictionary >
typedef Map< dictionary > this_type
typedef HashTable< dictionary, label, Hash< label > > parent_type
using iterator = typename parent_type::iterator
using const_iterator = typename parent_type::const_iterator
Public Types inherited from HashTable< T, Key, Hash >
typedef HashTable< T, Key, Hash > this_type
typedef std::conditional< std::is_same< Foam::zero, typenamestd::remove_cv< T >::type >::value, Detail::HashTableSingle< Key >, Detail::HashTablePair< Key, T > >::type node_type
typedef Key key_type
typedef T mapped_type
typedef T value_type
typedef Hash hasher
typedef T * pointer
typedef T & reference
typedef const T * const_pointer
typedef const T & const_reference
typedef label difference_type
typedef label size_type
using key_iterator = key_iterator_base< iterator >
using const_key_iterator = key_iterator_base< const_iterator >
Static Public Member Functions inherited from HashTableCore
static label canonicalSize (const label requested_size)
Static Public Attributes inherited from HashTableCore
static const label maxTableSize
Detailed Description
The cellTable persistent data saved as a Map<dictionary>.
The meshReader supports cellTable information.
The constant/cellTable file is an IOMap<dictionary> that is used to save the information persistently. It contains the cellTable information of the following form:
    (
        ID
        {
            Label           WORD;
            MaterialType    WORD;
            MaterialId      INT;
            PorosityId      INT;
            ColorIdx        INT;
            ...
        }
    ...
    )
If the Label is missing, a value cellTable_{ID} will be inferred. If the MaterialType is missing, the value fluid will be inferred.
Source files
cellTable.H
cellTable.C
Definition at line 76 of file cellTable.H.
Constructor & Destructor Documentation
cellTable() [1/2]
cellTable ()
Definition at line 98 of file cellTable.C.
cellTable() [2/2]
cellTable (const objectRegistry & registry, const word & name = "cellTable", const fileName & instance = "constant")
Definition at line 104 of file cellTable.C.
References cellTable::name(), and cellTable::readDict().
~cellTable()
~cellTable () default
Member Function Documentation
append()
Foam::label append (const dictionary & dict)
Definition at line 119 of file cellTable.C.
References dict, forAllConstIters, and insert().
findIndex()
Foam::label findIndex (const word & name) const
Definition at line 195 of file cellTable.C.
References forAllConstIters, Foam::name(), and word::null.
name()
Foam::word name (const label id) const
Definition at line 181 of file cellTable.C.
References HashTable< T, Key, Hash >::Iterator< Const >::good(), and Foam::name().
Referenced by cellTable::cellTable().
names() [1/2]
Foam::Map< Foam::word > names () const
Definition at line 135 of file cellTable.C.
References forAllConstIters, and Foam::name().
names() [2/2]
Foam::Map< Foam::word > names (const wordRes & patterns) const
Definition at line 156 of file cellTable.C.
References forAllConstIters, and Foam::name().
selectType()
Foam::Map< Foam::word > selectType (const word & materialType) const
Definition at line 231 of file cellTable.C.
References dict, forAllConstIters, dictionary::getOrDefault(), and Foam::name().
fluids()
Foam::Map< Foam::word > fluids () const
Definition at line 262 of file cellTable.C.
Referenced by reader::fluids().
shells()
Foam::Map< Foam::word > shells () const
Definition at line 274 of file cellTable.C.
solids()
Foam::Map< Foam::word > solids () const
Definition at line 268 of file cellTable.C.
Referenced by reader::solids().
materialTypes()
Foam::Map< Foam::word > materialTypes () const
Definition at line 214 of file cellTable.C.
References forAllConstIters.
setMaterial()
void setMaterial (const label id, const word & matlType)
Definition at line 281 of file cellTable.C.
setName() [1/2]
void setName (const label id, const word & name)
Definition at line 287 of file cellTable.C.
References Foam::name().
setName() [2/2]
void setName (const label id)
Definition at line 293 of file cellTable.C.
References found, HashTable< T, Key, Hash >::Iterator< Const >::good(), and Foam::name().
readDict()
void readDict (const objectRegistry & registry, const word & name = "cellTable", const fileName & instance = "constant")
Definition at line 304 of file cellTable.C.
References clear(), Foam::endl(), Foam::Info, Foam::name(), IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, and IOobjectOption::READ_IF_PRESENT.
Referenced by cellTable::cellTable(), STARCDMeshReader::readAux(), and STARCDMeshWriter::STARCDMeshWriter().
writeDict()
void writeDict (const objectRegistry & registry, const word & name = "cellTable", const fileName & instance = "constant") const
Definition at line 339 of file cellTable.C.
References Foam::endl(), Foam::Info, Foam::name(), IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, and os().
operator=() [1/3]
void operator= (const cellTable & rhs)
Definition at line 373 of file cellTable.C.
References Map< T >::operator=().
operator=() [2/3]
void operator= (const Map< dictionary > & rhs)
Definition at line 380 of file cellTable.C.
References Map< T >::operator=().
operator=() [3/3]
void operator= (const polyMesh & mesh)
Definition at line 387 of file cellTable.C.
References dictionary::add(), polyMesh::cellZones(), PtrList< T >::clear(), dict, forAll, mesh, primitiveMesh::nCells(), Map< T >::operator=(), and UPtrList< T >::size().
addCellZones()
void addCellZones (polyMesh & mesh, const labelList & tableIds) const
Definition at line 432 of file cellTable.C.
References PtrList< T >::append(), IOobjectOption::AUTO_WRITE, polyMesh::cellZones(), PtrList< T >::clear(), Foam::endl(), forAll, Foam::Info, mesh, PtrList< T >::set(), PtrList< T >::setSize(), and UPtrList< T >::size().
combine()
void combine (const dictionary & mapDict, labelList & tableIds)
Definition at line 499 of file cellTable.C.
References UPtrList< T >::empty(), Foam::endl(), erase(), Foam::findIndex(), forAllConstIters, Foam::identity(), Foam::Info, Foam::inplaceRenumber(), Foam::max(), Foam::min(), and UPtrList< T >::size().
The documentation for this class was generated from the following files:
src/conversion/common/tables/cellTable.H
src/conversion/common/tables/cellTable.C