OpenFOAM: processorPointPatch Class Reference
processorPointPatch Class Reference
Processor patch boundary needs to be such that the ordering of points in the patch is the same on both sides.
#include <processorPointPatch.H>
Public Member Functions
TypeName (processorPolyPatch::typeName_())
processorPointPatch (const polyPatch &patch, const pointBoundaryMesh &bm)
virtual ~processorPointPatch ()=default
virtual int tag () const
virtual label comm () const
virtual const word & constraintType () const
int myProcNo () const
int neighbProcNo () const
bool owner () const
bool neighbour () const
const processorPolyPatch & procPolyPatch () const
const labelList & reverseMeshPoints () const
Public Member Functions inherited from coupledFacePointPatch
TypeName (coupledPolyPatch::typeName_())
coupledFacePointPatch (const polyPatch &patch, const pointBoundaryMesh &bm)
virtual ~coupledFacePointPatch ()=default
Public Member Functions inherited from facePointPatch
TypeName (polyPatch::typeName_())
declareRunTimeSelectionTable (autoPtr, facePointPatch, polyPatch,(const polyPatch &patch, const pointBoundaryMesh &bm),(patch, bm))
facePointPatch (const polyPatch &p, const pointBoundaryMesh &pm)
virtual ~facePointPatch ()=default
virtual const polyPatch & patch () const
virtual const word & name () const
virtual label size () const
virtual label index () const
virtual bool coupled () const
virtual const labelList & meshPoints () const
virtual const pointField & localPoints () const
virtual const vectorField & pointNormals () const
Public Member Functions inherited from pointPatch
TypeName ("basePatch")
pointPatch (const pointBoundaryMesh &bm)
virtual ~pointPatch ()=default
const pointBoundaryMesh & boundaryMesh () const
virtual void applyConstraint (const label pointi, pointConstraint &) const
Public Member Functions inherited from coupledPointPatch
TypeName (coupledPolyPatch::typeName_())
coupledPointPatch (const pointBoundaryMesh &bm)
virtual ~coupledPointPatch ()=default
Additional Inherited Members
Static Public Member Functions inherited from facePointPatch
static autoPtr< facePointPatch > New (const polyPatch &, const pointBoundaryMesh &)
Protected Member Functions inherited from coupledFacePointPatch
coupledFacePointPatch (const coupledFacePointPatch &)=delete
void operator= (const coupledFacePointPatch &)=delete
Protected Member Functions inherited from facePointPatch
facePointPatch (const facePointPatch &)=delete
void operator= (const facePointPatch &)=delete
Protected Member Functions inherited from pointPatch
pointPatch (const pointPatch &)=delete
void operator= (const pointPatch &)=delete
Protected Member Functions inherited from coupledPointPatch
coupledPointPatch (const coupledPointPatch &)=delete
void operator= (const coupledPointPatch &)=delete
Protected Attributes inherited from facePointPatch
const polyPatch & polyPatch_
Detailed Description
Processor patch boundary needs to be such that the ordering of points in the patch is the same on both sides.
Looking at the creation of the faces on both sides of the processor patch they need to be identical on both sides with the normals pointing in opposite directions. This is achieved by calling the reverseFace function in the decomposition. It is therefore possible to re-create the ordering of patch points on the neighbour side by reversing all the patch faces of the owner.
Source files
processorPointPatch.H
processorPointPatch.C
Definition at line 56 of file processorPointPatch.H.
Constructor & Destructor Documentation
processorPointPatch()
processorPointPatch (const polyPatch & patch, const pointBoundaryMesh & bm)
Definition at line 102 of file processorPointPatch.C.
~processorPointPatch()
virtual ~processorPointPatch () virtual default
Member Function Documentation
TypeName()
TypeName (processorPolyPatch::typeName_())
tag()
virtual int tag () const inline virtual
Reimplemented in processorCyclicPointPatch.
Definition at line 117 of file processorPointPatch.H.
References processorPolyPatch::tag().
comm()
virtual label comm () const inline virtual
Definition at line 123 of file processorPointPatch.H.
References processorPolyPatch::comm().
constraintType()
virtual const word & constraintType () const inline virtual
Reimplemented from pointPatch.
Definition at line 129 of file processorPointPatch.H.
References Foam::type().
myProcNo()
int myProcNo () const inline
Definition at line 135 of file processorPointPatch.H.
References processorPolyPatch::myProcNo().
neighbProcNo()
int neighbProcNo () const inline
Definition at line 141 of file processorPointPatch.H.
References processorPolyPatch::neighbProcNo().
owner()
bool owner () const inline
Definition at line 147 of file processorPointPatch.H.
References processorPolyPatch::owner().
Referenced by processorPointPatch::neighbour().
neighbour()
bool neighbour () const inline
Definition at line 153 of file processorPointPatch.H.
References processorPointPatch::owner().
procPolyPatch()
const processorPolyPatch & procPolyPatch () const inline
Definition at line 159 of file processorPointPatch.H.
Referenced by processorPointPatchField< Type >::doTransform(), and processorCyclicPointPatchField< Type >::doTransform().
reverseMeshPoints()
const labelList & reverseMeshPoints () const inline
Definition at line 165 of file processorPointPatch.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/pointMesh/pointPatches/constraint/processor/processorPointPatch.H
src/OpenFOAM/meshes/pointMesh/pointPatches/constraint/processor/processorPointPatch.C