OpenFOAM: highAspectRatioFvGeometryScheme Class Reference
highAspectRatioFvGeometryScheme Class Reference
Geometry calculation scheme with automatic stabilisation for high-aspect ratio cells.
#include <highAspectRatioFvGeometryScheme.H>
Public Member Functions
TypeName ("highAspectRatio")
highAspectRatioFvGeometryScheme (const fvMesh &mesh, const dictionary &dict)
virtual ~highAspectRatioFvGeometryScheme ()=default
virtual void movePoints ()
Public Member Functions inherited from basicFvGeometryScheme
TypeName ("basic")
basicFvGeometryScheme (const fvMesh &mesh, const dictionary &dict)
virtual ~basicFvGeometryScheme ()=default
virtual tmp< surfaceScalarField > weights () const
virtual tmp< surfaceScalarField > deltaCoeffs () const
virtual tmp< surfaceScalarField > nonOrthDeltaCoeffs () const
virtual tmp< surfaceVectorField > nonOrthCorrectionVectors () const
Public Member Functions inherited from fvGeometryScheme
TypeName ("fvGeometryScheme")
declareRunTimeSelectionTable (tmp, fvGeometryScheme, dict,(const fvMesh &mesh, const dictionary &dict),(mesh, dict))
fvGeometryScheme (const fvMesh &mesh, const dictionary &dict)
virtual ~fvGeometryScheme ()=default
const fvMesh & mesh () const
virtual void updateMesh (const mapPolyMesh &mpm)
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Protected Member Functions
void calcAspectRatioWeights (scalarField &cellWeight, scalarField &faceWeight) const
Protected Member Functions inherited from fvGeometryScheme
bool setMeshPhi () const
Static Protected Member Functions
static void makeAverageCentres (const polyMesh &mesh, const pointField &points, const pointField &faceAreas, const scalarField &magFaceAreas, pointField &faceCentres, pointField &cellCentres)
Protected Attributes
const scalar minAspect_
const scalar maxAspect_
Protected Attributes inherited from fvGeometryScheme
const fvMesh & mesh_
Additional Inherited Members
Static Public Member Functions inherited from fvGeometryScheme
static tmp< fvGeometryScheme > New (const fvMesh &mesh, const dictionary &dict, const word &defaultScheme)
Detailed Description
Geometry calculation scheme with automatic stabilisation for high-aspect ratio cells.
Source files
highAspectRatioFvGeometryScheme.H
highAspectRatioFvGeometryScheme.C
Definition at line 50 of file highAspectRatioFvGeometryScheme.H.
Constructor & Destructor Documentation
highAspectRatioFvGeometryScheme()
highAspectRatioFvGeometryScheme (const fvMesh & mesh, const dictionary & dict)
Definition at line 341 of file highAspectRatioFvGeometryScheme.C.
References dict, Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, highAspectRatioFvGeometryScheme::maxAspect_, highAspectRatioFvGeometryScheme::minAspect_, and highAspectRatioFvGeometryScheme::movePoints().
~highAspectRatioFvGeometryScheme()
virtual ~highAspectRatioFvGeometryScheme () virtual default
Member Function Documentation
calcAspectRatioWeights()
void calcAspectRatioWeights (scalarField & cellWeight, scalarField & faceWeight) const protected
Definition at line 156 of file highAspectRatioFvGeometryScheme.C.
References Foam::clamp(), delta, Foam::max(), highAspectRatioFvGeometryScheme::maxAspect_, fvGeometryScheme::mesh_, highAspectRatioFvGeometryScheme::minAspect_, PtrList< T >::setSize(), and syncTools::swapBoundaryCellList().
makeAverageCentres()
void makeAverageCentres (const polyMesh & mesh, const pointField & points, const pointField & faceAreas, const scalarField & magFaceAreas, pointField & faceCentres, pointField & cellCentres) static protected
Definition at line 219 of file highAspectRatioFvGeometryScheme.C.
References polyMesh::boundaryMesh(), triangle< Point, PointRef >::centre(), Foam::endl(), f(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), polyMesh::faces(), forAll, Foam::mag(), mesh, primitiveMesh::nCells(), primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), nPoints, p, pbm, Foam::Pout, pp(), List< T >::setSize(), UList< T >::size(), and Foam::Zero.
TypeName()
TypeName ("highAspectRatio")
movePoints()
void movePoints () virtual
Reimplemented from basicFvGeometryScheme.
Reimplemented in averageNeighbourFvGeometryScheme.
Definition at line 373 of file highAspectRatioFvGeometryScheme.C.
References Foam::endl(), Foam::gAverage(), Foam::gMax(), Foam::gMin(), Foam::mag(), fvGeometryScheme::movePoints(), Foam::Pout, primitiveMesh::resetGeometry(), and primitiveMesh::updateGeom().
Referenced by highAspectRatioFvGeometryScheme::highAspectRatioFvGeometryScheme(), and averageNeighbourFvGeometryScheme::movePoints().
Member Data Documentation
minAspect_
const scalar minAspect_ protected
Definition at line 56 of file highAspectRatioFvGeometryScheme.H.
Referenced by highAspectRatioFvGeometryScheme::calcAspectRatioWeights(), and highAspectRatioFvGeometryScheme::highAspectRatioFvGeometryScheme().
maxAspect_
const scalar maxAspect_ protected
Definition at line 58 of file highAspectRatioFvGeometryScheme.H.
Referenced by highAspectRatioFvGeometryScheme::calcAspectRatioWeights(), and highAspectRatioFvGeometryScheme::highAspectRatioFvGeometryScheme().
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/fvGeometryScheme/highAspectRatio/highAspectRatioFvGeometryScheme.H
src/finiteVolume/fvMesh/fvGeometryScheme/highAspectRatio/highAspectRatioFvGeometryScheme.C