OpenFOAM: rhoConst< Specie > Class Template Reference
rhoConst< Specie > Class Template Reference
Thermophysical models » Specie » Equation of state
RhoConst (rho = const) of state.
#include <rhoConst.H>
Public Member Functions
rhoConst (const Specie &sp, const scalar rho)
rhoConst (const dictionary &dict)
rhoConst (const word &name, const rhoConst &)
autoPtr< rhoConst > clone () const
scalar rho (scalar p, scalar T) const
scalar H (const scalar p, const scalar T) const
scalar Cp (scalar p, scalar T) const
scalar E (const scalar p, const scalar T) const
scalar Cv (scalar p, scalar T) const
scalar S (const scalar p, const scalar T) const
scalar psi (scalar p, scalar T) const
scalar Z (scalar p, scalar T) const
scalar CpMCv (scalar p, scalar T) const
void write (Ostream &os) const
void operator+= (const rhoConst &)
void operator*= (const scalar)
Static Public Member Functions
static word typeName ()
Static Public Attributes
static const bool incompressible = true
static const bool isochoric = true
Friends
rhoConst operator+ (const rhoConst &, const rhoConst &)
rhoConst operator* (const scalar s, const rhoConst &)
rhoConst operator== (const rhoConst &, const rhoConst &)
Ostream & operator<< (Ostream &, const rhoConst &)
Detailed Description
template<class Specie>
class Foam::rhoConst< Specie >
RhoConst (rho = const) of state.
Source files
rhoConst.H
rhoConstI.H
rhoConst.C
Definition at line 84 of file rhoConst.H.
Constructor & Destructor Documentation
rhoConst() [1/3]
template<class Specie > rhoConst (const Specie & sp, const scalar rho) inline
Definition at line 26 of file rhoConstI.H.
rhoConst() [2/3]
template<class Specie > rhoConst (const dictionary & dict)
Definition at line 27 of file rhoConst.C.
rhoConst() [3/3]
template<class Specie > rhoConst (const word & name, const rhoConst< Specie > &) inline
Member Function Documentation
clone()
template<class Specie > Foam::autoPtr< Foam::rhoConst< Specie > > clone () const inline
Definition at line 53 of file rhoConstI.H.
References Foam::New().
typeName()
template<class Specie > static word typeName () inline static
Definition at line 114 of file rhoConst.H.
rho()
template<class Specie > Foam::scalar rho (scalar p, scalar T) const inline
Definition at line 62 of file rhoConstI.H.
H()
template<class Specie > Foam::scalar H (const scalar p, const scalar T) const inline
Definition at line 69 of file rhoConstI.H.
Cp()
template<class Specie > Foam::scalar Cp (scalar p, scalar T) const inline
Definition at line 76 of file rhoConstI.H.
E()
template<class Specie > Foam::scalar E (const scalar p, const scalar T) const inline
Definition at line 83 of file rhoConstI.H.
Cv()
template<class Specie > Foam::scalar Cv (scalar p, scalar T) const inline
Definition at line 90 of file rhoConstI.H.
S()
template<class Specie > Foam::scalar S (const scalar p, const scalar T) const inline
Definition at line 97 of file rhoConstI.H.
psi()
template<class Specie > Foam::scalar psi (scalar p, scalar T) const inline
Definition at line 104 of file rhoConstI.H.
Z()
template<class Specie > Foam::scalar Z (scalar p, scalar T) const inline
Definition at line 111 of file rhoConstI.H.
CpMCv()
template<class Specie > Foam::scalar CpMCv (scalar p, scalar T) const inline
Definition at line 118 of file rhoConstI.H.
write()
template<class Specie > void write (Ostream & os) const
Definition at line 37 of file rhoConst.C.
References Ostream::beginBlock(), Ostream::endBlock(), os(), and Ostream::writeEntry().
operator+=()
template<class Specie > void operator+= (const rhoConst< Specie > &) inline
Definition at line 127 of file rhoConstI.H.
References Foam::mag(), and Y.
operator*=()
template<class Specie > void operator*= (const scalar s) inline
Definition at line 143 of file rhoConstI.H.
References s().
Friends And Related Symbol Documentation
operator+
template<class Specie > rhoConst operator+ (const rhoConst< Specie > & , const rhoConst< Specie > &) friend
operator*
template<class Specie > rhoConst operator* (const scalar s, const rhoConst< Specie > &) friend
operator==
template<class Specie > rhoConst operator== (const rhoConst< Specie > & , const rhoConst< Specie > &) friend
operator<<
template<class Specie > Ostream & operator<< (Ostream & , const rhoConst< Specie > &) friend
Member Data Documentation
incompressible
template<class Specie > const bool incompressible = true static
Definition at line 123 of file rhoConst.H.
isochoric
template<class Specie > const bool isochoric = true static
Definition at line 126 of file rhoConst.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/equationOfState/rhoConst/rhoConst.H
src/thermophysicalModels/specie/equationOfState/rhoConst/rhoConst.C
src/thermophysicalModels/specie/equationOfState/rhoConst/rhoConstI.H