OpenFOAM: hPowerThermo< EquationOfState > Class Template Reference
hPowerThermo< EquationOfState > Class Template Reference
Thermophysical models » Specie » Thermodynamics
Power-function based thermodynamics package templated on EquationOfState.
#include <hPowerThermo.H>
Public Member Functions
hPowerThermo (const dictionary &)
hPowerThermo (const word &, const hPowerThermo &)
autoPtr< hPowerThermo > clone () const
scalar limit (const scalar T) const
scalar Cp (const scalar p, const scalar T) const
scalar Ha (const scalar p, const scalar T) const
scalar Hs (const scalar p, const scalar T) const
scalar Hc () const
scalar S (const scalar p, const scalar T) const
scalar Gstd (const scalar T) const
scalar dCpdT (const scalar p, const scalar T) const
void operator+= (const hPowerThermo &)
Static Public Member Functions
static autoPtr< hPowerThermo > New (const dictionary &dict)
static word typeName ()
Friends
hPowerThermo operator+ (const hPowerThermo &, const hPowerThermo &)
hPowerThermo operator* (const scalar, const hPowerThermo &)
hPowerThermo operator== (const hPowerThermo &, const hPowerThermo &)
Ostream & operator<< (Ostream &, const hPowerThermo &)
Detailed Description
template<class EquationOfState>
class Foam::hPowerThermo< EquationOfState >
Power-function based thermodynamics package templated on EquationOfState.
In this thermodynamics package the heat capacity is a simple power of temperature:
Cp(T) = c0*(T/Tref)^n0;
which is particularly suitable for solids.
Source files
hPowerThermo.H
hPowerThermoI.H
hPowerThermo.C
Definition at line 94 of file hPowerThermo.H.
Constructor & Destructor Documentation
hPowerThermo() [1/2]
template<class EquationOfState > hPowerThermo (const dictionary & dict)
Definition at line 27 of file hPowerThermo.C.
hPowerThermo() [2/2]
template<class EquationOfState > hPowerThermo (const word & name, const hPowerThermo< EquationOfState > & jt) inline
Definition at line 44 of file hPowerThermoI.H.
Member Function Documentation
clone()
template<class EquationOfState > Foam::autoPtr< Foam::hPowerThermo< EquationOfState > > clone () const inline
Definition at line 80 of file hPowerThermoI.H.
References Foam::New().
New()
template<class EquationOfState > Foam::autoPtr< Foam::hPowerThermo< EquationOfState > > New (const dictionary & dict) inline static
Definition at line 88 of file hPowerThermoI.H.
References dict, and Foam::New().
typeName()
template<class EquationOfState > static word typeName () inline static
Definition at line 146 of file hPowerThermo.H.
limit()
template<class EquationOfState > Foam::scalar limit (const scalar T) const inline
Definition at line 97 of file hPowerThermoI.H.
References T.
Cp()
template<class EquationOfState > Foam::scalar Cp (const scalar p, const scalar T) const inline
Definition at line 107 of file hPowerThermoI.H.
References p, Foam::pow(), and T.
Ha()
template<class EquationOfState > Foam::scalar Ha (const scalar p, const scalar T) const inline
Definition at line 117 of file hPowerThermoI.H.
References Hs(), p, and T.
Hs()
template<class EquationOfState > Foam::scalar Hs (const scalar p, const scalar T) const inline
Definition at line 127 of file hPowerThermoI.H.
References p, Foam::pow(), T, and Foam::constant::thermodynamic::Tstd.
Hc()
template<class EquationOfState > Foam::scalar Hc () const inline
Definition at line 139 of file hPowerThermoI.H.
S()
template<class EquationOfState > Foam::scalar S (const scalar p, const scalar T) const inline
Definition at line 146 of file hPowerThermoI.H.
References p, Foam::pow(), T, and Foam::constant::thermodynamic::Tstd.
Gstd()
template<class EquationOfState > Foam::scalar Gstd (const scalar T) const inline
Definition at line 158 of file hPowerThermoI.H.
References Foam::pow(), T, and Foam::constant::thermodynamic::Tstd.
dCpdT()
template<class EquationOfState > Foam::scalar dCpdT (const scalar p, const scalar T) const inline
Definition at line 171 of file hPowerThermoI.H.
References NotImplemented.
operator+=()
template<class EquationOfState > void operator+= (const hPowerThermo< EquationOfState > &) inline
Definition at line 185 of file hPowerThermoI.H.
References Foam::mag(), and Y.
Friends And Related Symbol Documentation
operator+
template<class EquationOfState > hPowerThermo operator+ (const hPowerThermo< EquationOfState > & , const hPowerThermo< EquationOfState > &) friend
operator*
template<class EquationOfState > hPowerThermo operator* (const scalar , const hPowerThermo< EquationOfState > &) friend
operator==
template<class EquationOfState > hPowerThermo operator== (const hPowerThermo< EquationOfState > & , const hPowerThermo< EquationOfState > &) friend
operator<<
template<class EquationOfState > Ostream & operator<< (Ostream & , const hPowerThermo< EquationOfState > &) friend
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/thermo/hPower/hPowerThermo.H
src/thermophysicalModels/specie/thermo/hPower/hPowerThermo.C
src/thermophysicalModels/specie/thermo/hPower/hPowerThermoI.H