OpenFOAM: volRegion Class Reference
volRegion Class Reference
FunctionObjects » Field function objects
Volume (cell) region selection class.
#include <volRegion.H>
Public Types
enum regionTypes : char { vrtAll = 0 , vrtCellSet , vrtCellZone }
Public Member Functions
TypeName ("volRegion")
volRegion (const fvMesh &mesh, const dictionary &dict)
virtual ~volRegion ()=default
regionTypes regionType () const noexcept
const labelList & cellIDs () const
label nCells () const
scalar V () const
bool update ()
virtual bool read (const dictionary &dict)
virtual void updateMesh (const mapPolyMesh &)
virtual void movePoints (const polyMesh &)
Static Public Attributes
static const Enum< regionTypes > regionTypeNames_
Protected Member Functions
bool useAllCells () const noexcept
void writeFileHeader (const writeFile &wf, Ostream &file) const
Protected Attributes
regionTypes regionType_
wordRe regionName_
Detailed Description
Volume (cell) region selection class.
The adjustments for mesh changes have been implemented with a lazy evaluation, to avoid unnecessary recalculation until the values are actually required. The update() method is used to ensure the cache values are up-to-date.
Examples of function object specification:
volRegion0
{
    .
    .
    regionType      cellZone;
    name            c0;
    .
    .
}
volRegionAll
{
    .
    .
    regionType      all;
    .
    .
}
Usage
Property Description Required Default
regionType Selection type: all/cellSet/cellZone no all
name Name of cellSet/cellZone if required conditional
See also
Foam::functionObject
Source files
volRegion.H
volRegion.C
Definition at line 111 of file volRegion.H.
Member Enumeration Documentation
regionTypes
enum regionTypes : char
Enumerator
vrtAll
All cells.
vrtCellSet
A cellSet.
vrtCellZone
A cellZone.
Definition at line 118 of file volRegion.H.
Constructor & Destructor Documentation
volRegion()
volRegion (const fvMesh & mesh, const dictionary & dict)
Definition at line 142 of file volRegion.C.
References dict, and volRegion::read().
~volRegion()
virtual ~volRegion () virtual default
Member Function Documentation
useAllCells()
bool useAllCells () const inline protected noexcept
Definition at line 24 of file volRegionI.H.
References volRegion::regionType_, and volRegion::vrtAll.
Referenced by volFieldValue::filterField(), specieReactionRates< ChemistryModelType >::write(), momentum::writeFileHeader(), and momentum::writeValues().
writeFileHeader()
void writeFileHeader (const writeFile & wf, Ostream & file) const protected
Definition at line 126 of file volRegion.C.
References Foam::endl(), and Foam::setw().
Referenced by volFieldValue::writeFileHeader().
TypeName()
TypeName ("volRegion")
regionType()
Foam::functionObjects::volRegion::regionTypes regionType () const inline noexcept
Definition at line 31 of file volRegionI.H.
cellIDs()
const Foam::labelList & cellIDs () const
Definition at line 203 of file volRegion.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::nl, and List< label >::null().
nCells()
Foam::label nCells () const inline
Definition at line 37 of file volRegionI.H.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and Foam::nl.
V()
Foam::scalar V () const inline
Definition at line 52 of file volRegionI.H.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and Foam::nl.
Referenced by specieReactionRates< ChemistryModelType >::write(), and momentum::writeValues().
update()
bool update ()
Definition at line 243 of file volRegion.C.
Referenced by randomise::calc(), volFieldValue::write(), and specieReactionRates< ChemistryModelType >::write().
read()
bool read (const dictionary & dict) virtual
Reimplemented in momentum, volFieldValue, randomise, and specieReactionRates< ChemistryModelType >.
Definition at line 171 of file volRegion.C.
References dict, Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, Foam::flatOutput(), and Foam::nl.
Referenced by momentum::read(), randomise::read(), and volRegion::volRegion().
updateMesh()
void updateMesh (const mapPolyMesh &) virtual
Reimplemented in momentum.
Definition at line 255 of file volRegion.C.
Referenced by momentum::updateMesh().
movePoints()
void movePoints (const polyMesh &) virtual
Reimplemented in momentum.
Definition at line 261 of file volRegion.C.
Referenced by momentum::movePoints().
Member Data Documentation
regionTypeNames_
const Foam::Enum< Foam::functionObjects::volRegion::regionTypes > regionTypeNames_ static
Definition at line 126 of file volRegion.H.
regionType_
regionTypes regionType_ protected
Definition at line 163 of file volRegion.H.
Referenced by volRegion::useAllCells().
regionName_
wordRe regionName_ protected
Definition at line 166 of file volRegion.H.
Referenced by volFieldValue::writeValues().
The documentation for this class was generated from the following files:
src/finiteVolume/functionObjects/volRegion/volRegion.H
src/finiteVolume/functionObjects/volRegion/volRegion.C
src/finiteVolume/functionObjects/volRegion/volRegionI.H