OpenFOAM: correlationFunction< Type > Class Template Reference
correlationFunction< Type > Class Template Reference
#include <correlationFunction.H>
Public Types
typedef pTraits< Type >::cmptType cmptType
Public Types inherited from bufferedAccumulator< scalar >
typedef pTraits< scalar >::cmptType cmptType
Public Types inherited from List< T >
typedef SubList< T > subList
Public Types inherited from UList< T >
typedef T value_type
typedef T * pointer
typedef const T * const_pointer
typedef T & reference
typedef const T & const_reference
typedef T * iterator
typedef const T * const_iterator
typedef label size_type
typedef label difference_type
typedef std::reverse_iterator< iterator > reverse_iterator
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
Public Member Functions
correlationFunction (const polyMesh &, const dictionary &, const label tZeroBufferSize)
correlationFunction (const polyMesh &, const label tZeroBufferSize, const scalar duration, const scalar sampleInterval, const scalar averagingInterval)
~correlationFunction ()
void calculateCorrelationFunction (const Field< Type > &)
void calculateCorrelationFunction (const Type &)
scalar integral () const
bool writeAveraged (Ostream &) const
const Field< Field< Type > > & tZeroBuffers () const
scalar duration () const
scalar sampleInterval () const
scalar averagingInterval () const
label sampleSteps () const
label measurandFieldSize () const
Public Member Functions inherited from bufferedAccumulator< scalar >
bufferedAccumulator ()
bufferedAccumulator (const label nBuffers, const label bufferLength, const label bufferingInterval)
bufferedAccumulator (const bufferedAccumulator< scalar > &)
~bufferedAccumulator ()
label addToBuffers (const List< scalar > &valuesToAdd)
Field< scalar > averaged () const
void resetAveraging ()
label averagesTaken () const
label nBuffers () const
label bufferLength () const
const List< label > & bufferOffsets () const
void setSizes (const label nBuffers, const label bufferLength, const label bufferingInterval)
void operator= (const bufferedAccumulator< scalar > &)
Public Member Functions inherited from List< T >
constexpr List () noexcept
List (const label len)
List (const label len, const T &val)
List (const label len, const Foam::zero)
List (const Foam::one, const T &val)
List (const Foam::one, T &&val)
List (const Foam::one, const Foam::zero)
List (const List< T > &a)
List (const UList< T > &a)
List (List< T > &a, bool reuse)
List (const UList< T > &list, const labelUList &indices)
template<unsigned N>
List (const UList< T > &list, const FixedList< label, N > &indices)
template<unsigned N>
List (const FixedList< T, N > &list)
List (const PtrList< T > &list)
List (const SLList< T > &list)
template<class Addr >
List (const IndirectListBase< T, Addr > &list)
List (std::initializer_list< T > list)
List (List< T > &&list)
template<int SizeMin>
List (DynamicList< T, SizeMin > &&list)
List (SLList< T > &&list)
List (Istream &is)
autoPtr< List< T > > clone () const
~List ()
void clear ()
void resize (const label len)
void resize (const label len, const T &val)
void resize_nocopy (const label len)
void setSize (const label n)
void setSize (const label n, const T &val)
void transfer (List< T > &list)
template<int SizeMin>
void transfer (DynamicList< T, SizeMin > &list)
T & newElmt (const label i)
template<class... Args>
T & emplace_back (Args &&... args)
void push_back (const T &val)
void push_back (T &&val)
void push_back (const UList< T > &list)
template<class Addr >
void push_back (const IndirectListBase< T, Addr > &list)
label push_uniq (const T &val)
void pop_back (label n=1)
void operator= (const UList< T > &a)
void operator= (const List< T > &list)
void operator= (const SLList< T > &list)
template<class Addr >
void operator= (const IndirectListBase< T, Addr > &list)
template<unsigned N>
void operator= (const FixedList< T, N > &list)
void operator= (std::initializer_list< T > list)
void operator= (const T &val)
void operator= (const Foam::zero)
void operator= (List< T > &&list)
template<int SizeMin>
void operator= (DynamicList< T, SizeMin > &&list)
void operator= (SLList< T > &&list)
Istream & readList (Istream &is)
void shallowCopy (const UList< T > &)=delete
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type set (const label i, bool val=true)
void append (const T &val)
void append (T &&val)
void append (const UList< T > &list)
template<class Addr >
void append (const IndirectListBase< T, Addr > &list)
label appendUniq (const T &val)
Istream & readList (Istream &is)
void resize (const label newLen)
Istream & readList (Istream &is)
Public Member Functions inherited from UList< T >
UList (const UList< T > &)=default
constexpr UList () noexcept
UList (T *__restrict__ v, const label len) noexcept
label fcIndex (const label i) const noexcept
label rcIndex (const label i) const noexcept
const T & fcValue (const label i) const
T & fcValue (const label i)
const T & rcValue (const label i) const
T & rcValue (const label i)
const T * cdata () const noexcept
T * data () noexcept
const char * cdata_bytes () const noexcept
char * data_bytes () noexcept
T & front ()
const T & front () const
T & back ()
const T & back () const
std::streamsize size_bytes () const noexcept
std::streamsize byteSize () const
void checkStart (const label start) const
void checkSize (const label size) const
void checkRange (const label start, const label len) const
void checkIndex (const label i) const
bool uniform () const
label find (const T &val, label pos=0) const
label rfind (const T &val, label pos=-1) const
bool contains (const T &val, label pos=0) const
void moveFirst (const label i)
void moveLast (const label i)
void swapFirst (const label i)
void swapLast (const label i)
void shallowCopy (const UList< T > &list)
void deepCopy (const UList< T > &list)
template<class Addr >
void deepCopy (const IndirectListBase< T, Addr > &list)
SubList< T > slice (const label pos, label len=-1)
const SubList< T > slice (const label pos, label len=-1) const
SubList< T > slice (const labelRange &range)
const SubList< T > slice (const labelRange &range) const
T & operator[] (const label i)
const T & operator[] (const label i) const
operator const Foam::List< T > & () const
void operator= (const T &val)
void operator= (const Foam::zero)
iterator begin () noexcept
iterator end () noexcept
iterator begin (const label i) noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
const_iterator begin () const noexcept
const_iterator end () const noexcept
const_iterator cbegin (const label i) const noexcept
const_iterator begin (const label i) const noexcept
reverse_iterator rbegin ()
reverse_iterator rend ()
const_reverse_iterator crbegin () const
const_reverse_iterator crend () const
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
bool empty () const noexcept
label size () const noexcept
void swap (UList< T > &list)
bool operator== (const UList< T > &a) const
bool operator!= (const UList< T > &a) const
bool operator< (const UList< T > &list) const
bool operator> (const UList< T > &a) const
bool operator<= (const UList< T > &a) const
bool operator>= (const UList< T > &a) const
Istream & readList (Istream &is)
void writeEntry (const word &keyword, Ostream &os) const
Ostream & writeList (Ostream &os, const label shortLen=0) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type test (const label i) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type get (const label i) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type unset (const label i)
T & first ()
const T & first () const
T & last ()
const T & last () const
bool found (const T &val, label pos=0) const
Istream & readList (Istream &is)
Ostream & writeList (Ostream &os, const label) const
const bool & operator[] (const label i) const
UPstream::commsStruct & operator[] (const label procID)
const UPstream::commsStruct & operator[] (const label procID) const
Foam::UPstream::commsStruct & operator[] (const label procID)
const Foam::UPstream::commsStruct & operator[] (const label procID) const
Ostream & writeList (Ostream &os, const label) const
Istream & readList (Istream &is)
Static Public Attributes
static const char *const typeName
Static Public Attributes inherited from bufferedAccumulator< scalar >
static const char *const typeName
Friends
Ostream & operator<< (Ostream &, const correlationFunction< Type > &)
Additional Inherited Members
Static Public Member Functions inherited from List< T >
static const List< T > & null ()
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
static constexpr label max_size () noexcept
Protected Member Functions inherited from UList< T >
void setAddressableSize (const label n) noexcept
void size (const label n)
void writeEntry (Ostream &os) const
labelRange validateRange (const labelRange &requestedRange) const
UList< T > & operator= (const UList< T > &)=delete
void writeEntry (Ostream &os) const
void writeEntry (Ostream &os) const
Detailed Description
template<class Type>
class Foam::correlationFunction< Type >
Source files
correlationFunction.H
correlationFunctionI.H
correlationFunction.C
correlationFunctionIO.C
Definition at line 59 of file correlationFunction.H.
Member Typedef Documentation
cmptType
template<class Type > typedef pTraits<Type>::cmptType cmptType
Definition at line 90 of file correlationFunction.H.
Constructor & Destructor Documentation
correlationFunction() [1/2]
template<class Type > correlationFunction (const polyMesh & mesh, const dictionary & dict, const label tZeroBufferSize)
Definition at line 75 of file correlationFunction.C.
correlationFunction() [2/2]
template<class Type > correlationFunction (const polyMesh & mesh, const label tZeroBufferSize, const scalar duration, const scalar sampleInterval, const scalar averagingInterval)
Definition at line 93 of file correlationFunction.C.
~correlationFunction()
template<class Type > ~correlationFunction ()
Definition at line 115 of file correlationFunction.C.
Member Function Documentation
calculateCorrelationFunction() [1/2]
template<class Type > void calculateCorrelationFunction (const Field< Type > & currentValues)
Definition at line 122 of file correlationFunction.C.
References Foam::abort(), Foam::component(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::nl, UPtrList< T >::size(), and Foam::Zero.
calculateCorrelationFunction() [2/2]
template<class Type > void calculateCorrelationFunction (const Type & currentValue)
Definition at line 174 of file correlationFunction.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
integral()
template<class Type > Foam::scalar integral () const
Definition at line 193 of file correlationFunction.C.
References UPtrList< T >::size().
writeAveraged()
template<class Type > bool writeAveraged (Ostream & os) const
Definition at line 25 of file correlationFunctionIO.C.
References forAll, Foam::nl, os(), PtrList< T >::PtrList(), and token::SPACE.
tZeroBuffers()
template<class Type > const Foam::Field< Foam::Field< Type > > & tZeroBuffers () const inline
Definition at line 23 of file correlationFunctionI.H.
duration()
template<class Type > Foam::scalar duration () const inline
Definition at line 30 of file correlationFunctionI.H.
sampleInterval()
template<class Type > Foam::scalar sampleInterval () const inline
Definition at line 37 of file correlationFunctionI.H.
averagingInterval()
template<class Type > Foam::scalar averagingInterval () const inline
Definition at line 44 of file correlationFunctionI.H.
sampleSteps()
template<class Type > Foam::label sampleSteps () const inline
Definition at line 51 of file correlationFunctionI.H.
measurandFieldSize()
template<class Type > Foam::label measurandFieldSize () const inline
Definition at line 58 of file correlationFunctionI.H.
References UPtrList< T >::size().
Friends And Related Symbol Documentation
operator<<
template<class Type > Ostream & operator<< (Ostream & , const correlationFunction< Type > &) friend
Member Data Documentation
typeName
template<class Type > const char *const typeName static
Definition at line 95 of file correlationFunction.H.
The documentation for this class was generated from the following files:
src/lagrangian/molecularDynamics/molecularMeasurements/correlationFunction/correlationFunction.H
src/lagrangian/molecularDynamics/molecularMeasurements/correlationFunction/correlationFunction.C
src/lagrangian/molecularDynamics/molecularMeasurements/correlationFunction/correlationFunctionI.H
src/lagrangian/molecularDynamics/molecularMeasurements/correlationFunction/correlationFunctionIO.C