OpenFOAM: thermalBaffleFvPatchScalarField Class Reference
thermalBaffleFvPatchScalarField Class Reference
Boundary conditions » Thermophysical
This boundary condition provides a coupled temperature condition between multiple mesh regions.
#include <thermalBaffleFvPatchScalarField.H>
Public Member Functions
TypeName ("compressible::thermalBaffle")
thermalBaffleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
thermalBaffleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
thermalBaffleFvPatchScalarField (const thermalBaffleFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
virtual tmp< fvPatchScalarField > clone () const
thermalBaffleFvPatchScalarField (const thermalBaffleFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Public Member Functions inherited from turbulentTemperatureRadCoupledMixedFvPatchScalarField
TypeName ("compressible::turbulentTemperatureRadCoupledMixed")
turbulentTemperatureRadCoupledMixedFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
turbulentTemperatureRadCoupledMixedFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
turbulentTemperatureRadCoupledMixedFvPatchScalarField (const turbulentTemperatureRadCoupledMixedFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
turbulentTemperatureRadCoupledMixedFvPatchScalarField (const turbulentTemperatureRadCoupledMixedFvPatchScalarField &)
turbulentTemperatureRadCoupledMixedFvPatchScalarField (const turbulentTemperatureRadCoupledMixedFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual void autoMap (const fvPatchFieldMapper &)
virtual void rmap (const fvPatchField< scalar > &, const labelList &)
virtual tmp< scalarField > kappa (const scalarField &Tp) const
virtual void manipulateMatrix (fvMatrix< scalar > &m, const label iMatrix, const direction cmpt)
Public Member Functions inherited from temperatureCoupledBase
temperatureCoupledBase (const fvPatch &patch, const KMethodType method=KMethodType::mtFluidThermo)
temperatureCoupledBase (const fvPatch &patch, const KMethodType method, const word &kappaName, const word &alphaName, const word &alphaAniName)
temperatureCoupledBase (const fvPatch &patch, const dictionary &dict)
temperatureCoupledBase (const fvPatch &patch, const temperatureCoupledBase &base)
temperatureCoupledBase (const temperatureCoupledBase &base)
virtual ~temperatureCoupledBase ()=default
word KMethod () const
const word & kappaName () const noexcept
const word & alphaName () const noexcept
virtual tmp< scalarField > alpha (const scalarField &Tp) const
void write (Ostream &os) const
Public Member Functions inherited from mappedPatchFieldBase< scalar >
mappedPatchFieldBase (const mappedPatchBase &mapper, const fvPatchField< scalar > &patchField, const word &fieldName, const bool setAverage, const scalar average, const word &interpolationScheme)
mappedPatchFieldBase (const mappedPatchBase &mapper, const fvPatchField< scalar > &patchField, const dictionary &dict)
mappedPatchFieldBase (const mappedPatchBase &mapper, const fvPatchField< scalar > &patchField, const dictionary &dict, const Field< scalar > &fld)
mappedPatchFieldBase (const mappedPatchBase &mapper, const fvPatchField< scalar > &patchField)
mappedPatchFieldBase (const mappedPatchFieldBase< scalar > &mapper)
mappedPatchFieldBase (const mappedPatchBase &mapper, const fvPatchField< scalar > &patchField, const mappedPatchFieldBase< scalar > &base)
virtual ~mappedPatchFieldBase ()=default
const GeometricField< T, fvPatchField, volMesh > & sampleField (const word &fieldName) const
const GeometricField< scalar, fvPatchField, volMesh > & sampleField () const
const Foam::GeometricField< Type2, Foam::fvPatchField, Foam::volMesh > & sampleField (const word &fieldName) const
virtual tmp< Field< scalar > > mappedField () const
virtual tmp< Field< scalar > > mappedInternalField () const
virtual tmp< scalarField > mappedWeightField () const
virtual void mappedWeightField (const word &weightFieldName, tmp< scalarField > &thisWeights, tmp< scalarField > &nbrWeights) const
void distribute (const word &fieldName, Field< T > &newValues) const
Public Member Functions inherited from writeFile
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name="undefined", const bool writeToFile=true)
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name, const dictionary &dict, const bool writeToFile=true)
writeFile (const writeFile &wf)
virtual ~writeFile ()=default
virtual bool read (const dictionary &dict)
virtual OFstream & file ()
virtual bool writeToFile () const
virtual bool canWriteToFile () const
virtual bool canResetFile () const
virtual bool canWriteHeader () const
virtual label charWidth () const
virtual void writeCommented (Ostream &os, const string &str) const
virtual void writeTabbed (Ostream &os, const string &str) const
virtual void writeHeader (Ostream &os, const string &str) const
virtual void writeCurrentTime (Ostream &os) const
virtual void writeBreak (Ostream &os) const
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
template<class Type >
void writeValue (Ostream &os, const Type &val) const
Additional Inherited Members
Public Types inherited from temperatureCoupledBase
enum KMethodType {
mtFluidThermo , mtSolidThermo , mtDirectionalSolidThermo , mtLookup ,
mtFunction
}
Static Public Member Functions inherited from mappedPatchFieldBase< scalar >
static const mappedPatchBase & mapper (const fvPatch &p, const DimensionedField< scalar, volMesh > &iF)
Static Public Attributes inherited from writeFile
static label addChars = 8
Protected Member Functions inherited from mappedPatchFieldBase< scalar >
void initRetrieveField (const objectRegistry &obr, const word &region, const word &patch, const labelListList &map, const word &fieldName, const Field< T > &fld) const
void initRetrieveField (const word &fieldName, const Field< T > &fld) const
bool storeAndRetrieveField (const word &fieldName, const label myComm, const labelListList &subMap, const label constructSize, const labelListList &constructMap, const labelListList &address, const scalarListList &weights, Field< T > &fld) const
void storeField (const objectRegistry &obr, const word &region, const word &patch, const label myComm, const labelListList &procToMap, const word &fieldName, const Field< T > &fld) const
bool retrieveField (const bool allowUnset, const objectRegistry &obr, const word &region, const word &patch, const label myComm, const labelListList &procToMap, const word &fieldName, Field< T > &fld) const
Protected Member Functions inherited from writeFile
void initStream (Ostream &os) const
fileName baseFileDir () const
fileName baseTimeDir () const
fileName filePath (const fileName &fName) const
virtual autoPtr< OFstream > newFile (const fileName &fName) const
virtual autoPtr< OFstream > newFileAtTime (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > newFileAtStartTime (const word &name) const
virtual void resetFile (const word &name)
Omanip< int > valueWidth (const label offset=0) const
void operator= (const writeFile &)=delete
virtual autoPtr< OFstream > createFile (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > createFile (const word &name) const
Protected Attributes inherited from temperatureCoupledBase
const fvPatch & patch_
const KMethodType method_
const word kappaName_
const word alphaName_
const word alphaAniName_
autoPtr< PatchFunction1< scalar > > kappaFunction1_
autoPtr< PatchFunction1< scalar > > alphaFunction1_
Protected Attributes inherited from mappedPatchFieldBase< scalar >
const mappedPatchBase & mapper_
const fvPatchField< scalar > & patchField_
word fieldName_
const bool setAverage_
const scalar average_
word interpolationScheme_
Protected Attributes inherited from writeFile
const objectRegistry & fileObr_
const fileName prefix_
word fileName_
autoPtr< OFstream > filePtr_
label writePrecision_
bool writeToFile_
bool updateHeader_
bool writtenHeader_
bool useUserTime_
scalar startTime_
Static Protected Attributes inherited from temperatureCoupledBase
static const Enum< KMethodType > KMethodTypeNames_
Detailed Description
This boundary condition provides a coupled temperature condition between multiple mesh regions.
The regions are generally referred to as the:
primary region,
and baffle region.
The primary region creates the baffle region and evolves its energy equation either:
1-D, normal to each patch face
3-D, normal and tangential components
The thermodynamic properties of the baffle material are specified via dictionary entries on the master patch.
The underlying polyPatch on the primary region needs to be defined as a complete mappedWall. i.e:
    type            mappedWall;
    sampleMode      nearestPatchFace;
    samplePatch     <patchName>;
    sampleRegion    <regionName>;
    coupleGroup     <coupleGroupName>;
The /keyword{internal} is true when the thermal baffle is used on internal faces and the baffle is coupled on both sides (bottom and top).
If this baffle is used on a patch set internal = false. By default is true.
Property Description Required Default value
Tnbr name of the field no T
qrNbr name of the radiative flux in the nbr region no none
qr name of the radiative flux in this region no none
thicknessLayers inherited from temperatureCoupledBase inherited
kappaLayers inherited from temperatureCoupledBase inherited
kappaMethod inherited from temperatureCoupledBase inherited
kappa inherited from temperatureCoupledBase inherited
thermalInertia Add thermal inertia to wall node no false
region Name of the solid region yes
active Active yes
internal Is the baffle an internal regiion no true
thermoType Solid thermo type yes
mixture Mixture solid yes
radiation Radiation model in the solid yes
extrudeModel Extrude model yes
nLayers Number of cell across the ragion yes
expansionRatio Expansion ratio for the solid region yes
columnCells true for 1D or false for 3D region yes
Usage
Example of the boundary condition specification:
<masterPatchName>
{
    type                compressible::thermalBaffle;
    // Underlying coupled boundary condition
    Tnbr               T;
    kappaMethod        fluidThermo; // or solidThermo
    kappa              none;
    qrNbr              qr;//or none.Name of qr field on neighbourregion
    qr                 none;// or none.Name of qr field on localregion
    value              uniform 300;
    // Baffle region name
    region              baffleRegion;
    active              yes;
    internal            yes;
    // Solid thermo in solid region
    thermoType
    {
        type            heSolidThermo;
        mixture         pureMixture;
        transport       constIso;
        thermo          hConst;
        equationOfState rhoConst;
        specie          specie;
        energy          sensibleEnthalpy;
    }
    mixture
    {
        specie
        {
            molWeight       20;
        }
        transport
        {
            kappa           0.01;
        }
        thermodynamics
        {
            Hf              0;
            Cp              15;
        }
        density
        {
            rho             80;
        }
    }
    radiation
    {
        radiationModel  opaqueSolid;
        absorptionEmissionModel none;
        scatterModel    none;
    }
    // Extrude model for new region
    extrudeModel        linearNormal;
    nLayers             50;
    expansionRatio      1;
    columnCells         false; //3D or 1D
    linearNormalCoeffs
    {
        thickness           0.02;
    }
}
If the thermal baffle is used on internal faces of the primary region, then the slave in this region is defined as :
Slave patch on primary region:
<slavePatchName>
{
    type                compressible::thermalBaffle;
    kappaMethod         fluidThermo;
    kappa               none;
    value               uniform 300;
Patches on baffle region:
bottom
{
    type                compressible::thermalBaffle;
    kappaMethod         solidThermo;
    kappa               none;
    value               uniform 300;
}
top
{
    type                compressible::thermalBaffle;
    kappaMethod         solidThermo;
    kappa               none;
    value               uniform 300;
}
See also
Foam::compressible::turbulentTemperatureCoupledBaffleMixedFvPatchScalarField Foam::regionModels::thermalBaffleModels::thermalBaffleModel
Source files
thermalBaffleFvPatchScalarField.H
thermalBaffleFvPatchScalarField.C
Definition at line 306 of file thermalBaffleFvPatchScalarField.H.
Constructor & Destructor Documentation
thermalBaffleFvPatchScalarField() [1/4]
thermalBaffleFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 36 of file thermalBaffleFvPatchScalarField.C.
thermalBaffleFvPatchScalarField() [2/4]
thermalBaffleFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 74 of file thermalBaffleFvPatchScalarField.C.
References dict, thermalBaffleModel::New(), dictionary::readIfPresent(), and regionName.
thermalBaffleFvPatchScalarField() [3/4]
thermalBaffleFvPatchScalarField (const thermalBaffleFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 51 of file thermalBaffleFvPatchScalarField.C.
thermalBaffleFvPatchScalarField() [4/4]
thermalBaffleFvPatchScalarField (const thermalBaffleFvPatchScalarField & ptf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 116 of file thermalBaffleFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("compressible::thermalBaffle")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Reimplemented from turbulentTemperatureRadCoupledMixedFvPatchScalarField.
Definition at line 384 of file thermalBaffleFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Reimplemented from turbulentTemperatureRadCoupledMixedFvPatchScalarField.
Definition at line 400 of file thermalBaffleFvPatchScalarField.H.
updateCoeffs()
void updateCoeffs () virtual
Reimplemented from turbulentTemperatureRadCoupledMixedFvPatchScalarField.
Definition at line 229 of file thermalBaffleFvPatchScalarField.C.
References turbulentTemperatureRadCoupledMixedFvPatchScalarField::updateCoeffs().
write()
void write (Ostream & os) const virtual
Reimplemented from turbulentTemperatureRadCoupledMixedFvPatchScalarField.
Definition at line 245 of file thermalBaffleFvPatchScalarField.C.
References dictionary::get(), os(), dictionary::subDict(), and turbulentTemperatureRadCoupledMixedFvPatchScalarField::write().
The documentation for this class was generated from the following files:
src/regionModels/thermalBaffleModels/derivedFvPatchFields/thermalBaffle/thermalBaffleFvPatchScalarField.H
src/regionModels/thermalBaffleModels/derivedFvPatchFields/thermalBaffle/thermalBaffleFvPatchScalarField.C