OpenFOAM: phasePair::const_iterator Class Reference
phasePair::const_iterator Class Reference
#include <phasePair.H>
Public Member Functions
const_iterator (const phasePair &)
label index () const
bool operator== (const const_iterator &) const
bool operator!= (const const_iterator &) const
const phaseModel & operator* () const
const phaseModel & operator() () const
const phaseModel & otherPhase () const
const_iterator & operator++ ()
const_iterator operator++ (int)
Friends
class phasePair
Detailed Description
Definition at line 176 of file phasePair.H.
Constructor & Destructor Documentation
const_iterator()
const_iterator (const phasePair & pair) inline explicit
Definition at line 105 of file phasePairI.H.
Member Function Documentation
index()
Foam::label index () const inline
Definition at line 111 of file phasePairI.H.
References phasePair::const_iterator::index().
Referenced by phasePair::const_iterator::index().
operator==()
bool operator== (const const_iterator & iter) const inline
Definition at line 117 of file phasePairI.H.
operator!=()
bool operator!= (const const_iterator & iter) const inline
Definition at line 126 of file phasePairI.H.
References phasePairKey::operator==.
operator*()
const Foam::phaseModel & operator* () const inline
Definition at line 136 of file phasePairI.H.
References phasePair::const_iterator::operator*().
Referenced by phasePair::const_iterator::operator*().
operator()()
const Foam::phaseModel & operator() () const inline
Definition at line 150 of file phasePairI.H.
References phasePair::const_iterator::operator()(), and Foam::operator*().
Referenced by phasePair::const_iterator::operator()().
otherPhase()
const Foam::phaseModel & otherPhase () const inline
Definition at line 157 of file phasePairI.H.
References phasePair::const_iterator::otherPhase().
Referenced by phasePair::const_iterator::otherPhase().
operator++() [1/2]
Foam::phasePair::const_iterator & operator++ () inline
Definition at line 171 of file phasePairI.H.
References phasePair::const_iterator::operator++().
Referenced by phasePair::const_iterator::operator++(), and phasePair::const_iterator::operator++().
operator++() [2/2]
Foam::phasePair::const_iterator operator++ (int) inline
Definition at line 179 of file phasePairI.H.
References phasePair::const_iterator::operator++().
Friends And Related Symbol Documentation
phasePair
friend class phasePair friend
Definition at line 191 of file phasePair.H.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/phasePair/phasePair.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/phasePair/phasePairI.H