OpenFOAM: graph Class Reference
graph Class Reference
Class to create, store and output qgraph files.
#include <graph.H>
Classes
class writer
Public Member Functions
graph (const string &title, const string &xName, const string &yName, const scalarField &x)
graph (const string &title, const string &xName, const string &yName, const scalarField &x, const scalarField &y)
graph (const string &title, const string &xName, const string &yName, Istream &is)
graph (Istream &is)
const string & title () const
const string & xName () const
const string & yName () const
const scalarField & x () const
scalarField & x ()
const scalarField & y () const
scalarField & y ()
void setXRange (const scalar x0, const scalar x1)
void writeTable (Ostream &) const
void write (Ostream &, const word &format) const
void write (const fileName &pName, const word &format) const
void write (const fileName &path, const word &name, const word &format) const
Public Member Functions inherited from HashPtrTable< curve >
HashPtrTable ()=default
HashPtrTable (const label size)
HashPtrTable (const this_type &rhs)
HashPtrTable (this_type &&rhs)
HashPtrTable (Istream &is, const INew &inew)
HashPtrTable (Istream &is)
HashPtrTable (const dictionary &dict)
~HashPtrTable ()
const curve * test (const word &key) const
const curve * get (const word &key) const
autoPtr< curve > release (iterator &iter)
autoPtr< curve > release (const word &key)
autoPtr< curve > remove (iterator &iter)
autoPtr< curve > remove (const word &key)
bool erase (iterator &iter)
bool erase (const word &key)
void clear ()
void merge (HashPtrTable< curve, word, Foam::Hash< word > > &source)
void merge (HashPtrTable< curve, word, Foam::Hash< word > > &&source)
void write (Ostream &os) const
void operator= (const this_type &rhs)
void operator= (this_type &&rhs)
bool emplace (const word &key, Args &&... args)
curve & emplace_set (const word &key, Args &&... args)
bool insert (const word &, curve *)=delete
bool insert (const word &key, std::unique_ptr< curve > &&ptr)
bool insert (const word &key, autoPtr< curve > &&ptr)
bool insert (const word &key, autoPtr< curve > &ptr)
bool set (const word &key, curve *ptr)
bool set (const word &key, std::unique_ptr< curve > &&ptr)
bool set (const word &key, autoPtr< curve > &&ptr)
bool set (const word &key, const refPtr< curve > &ptr)
bool set (const word &key, const tmp< curve > &ptr)
bool set (const word &key, autoPtr< curve > &ptr)
Public Member Functions inherited from HashTable< T, Key, Hash >
HashTable ()
HashTable (const label size)
HashTable (Istream &is, const label size=128)
HashTable (const this_type &ht)
HashTable (this_type &&rhs)
HashTable (std::initializer_list< std::pair< Key, T > > list)
~HashTable ()
bool empty () const noexcept
label size () const noexcept
label capacity () const noexcept
T & at (const Key &key)
const T & at (const Key &key) const
bool contains (const Key &key) const
iterator find (const Key &key)
const_iterator find (const Key &key) const
const_iterator cfind (const Key &key) const
const T & lookup (const Key &key, const T &deflt) const
List< Key > toc () const
List< Key > sortedToc () const
template<class Compare >
List< Key > sortedToc (const Compare &comp) const
template<class UnaryPredicate >
List< Key > tocKeys (const UnaryPredicate &pred, const bool invert=false) const
template<class UnaryPredicate >
List< Key > tocValues (const UnaryPredicate &pred, const bool invert=false) const
template<class BinaryPredicate >
List< Key > tocEntries (const BinaryPredicate &pred, const bool invert=false) const
UPtrList< const node_type > csorted () const
UPtrList< const node_type > sorted () const
UPtrList< node_type > sorted ()
template<class UnaryPredicate >
label countKeys (const UnaryPredicate &pred, const bool invert=false) const
template<class UnaryPredicate >
label countValues (const UnaryPredicate &pred, const bool invert=false) const
template<class BinaryPredicate >
label countEntries (const BinaryPredicate &pred, const bool invert=false) const
template<class... Args>
bool emplace (const Key &key, Args &&... args)
template<class... Args>
bool emplace_set (const Key &key, Args &&... args)
bool insert (const Key &key, const T &obj)
bool insert (const Key &key, T &&obj)
bool set (const Key &key, const T &obj)
bool set (const Key &key, T &&obj)
bool erase (const iterator &iter)
bool erase (const Key &key)
template<class AnyType , class AnyHash >
label erase (const HashTable< AnyType, Key, AnyHash > &other)
label erase (std::initializer_list< Key > keys)
template<class InputIter >
label erase (InputIter first, InputIter last)
template<unsigned N>
label erase (const FixedList< Key, N > &keys)
label erase (const UList< Key > &keys)
template<class AnyType , class AnyHash >
label retain (const HashTable< AnyType, Key, AnyHash > &other)
template<class UnaryPredicate >
label filterKeys (const UnaryPredicate &pred, const bool pruning=false)
template<class UnaryPredicate >
label filterValues (const UnaryPredicate &pred, const bool pruning=false)
template<class BinaryPredicate >
label filterEntries (const BinaryPredicate &pred, const bool pruning=false)
void resize (const label sz)
void clear ()
void clearStorage ()
void swap (HashTable< T, Key, Hash > &rhs)
void transfer (HashTable< T, Key, Hash > &rhs)
void merge (HashTable< T, Key, Hash > &source)
void merge (HashTable< T, Key, Hash > &&source)
T & operator[] (const Key &key)
const T & operator[] (const Key &key) const
T & operator() (const Key &key)
T & operator() (const Key &key, const T &deflt)
void operator= (const this_type &rhs)
void operator= (std::initializer_list< std::pair< Key, T > > rhs)
void operator= (this_type &&rhs)
bool operator== (const this_type &rhs) const
bool operator!= (const this_type &rhs) const
this_type & operator+= (const this_type &rhs)
const_iterator_pair< const_key_iterator, this_type > keys () const
iterator begin ()
const_iterator begin () const
const_iterator cbegin () const
iterator end () noexcept
const_iterator end () const noexcept
constexpr const_iterator cend () const noexcept
Ostream & printInfo (Ostream &os) const
Ostream & writeKeys (Ostream &os, const label shortLen=0) const
bool found (const Key &key) const
template<class Compare >
Foam::List< Key > sortedToc (const Compare &comp) const
template<class UnaryPredicate >
Foam::List< Key > tocKeys (const UnaryPredicate &pred, const bool invert) const
template<class UnaryPredicate >
Foam::List< Key > tocValues (const UnaryPredicate &pred, const bool invert) const
template<class BinaryPredicate >
Foam::List< Key > tocEntries (const BinaryPredicate &pred, const bool invert) const
template<class UnaryPredicate >
Foam::label countKeys (const UnaryPredicate &pred, const bool invert) const
template<class UnaryPredicate >
Foam::label countValues (const UnaryPredicate &pred, const bool invert) const
template<class BinaryPredicate >
Foam::label countEntries (const BinaryPredicate &pred, const bool invert) const
template<class InputIter >
Foam::label erase (InputIter first, InputIter last)
template<unsigned N>
Foam::label erase (const FixedList< Key, N > &keys)
template<class AnyType , class AnyHash >
Foam::label erase (const HashTable< AnyType, Key, AnyHash > &other)
template<class AnyType , class AnyHash >
Foam::label retain (const HashTable< AnyType, Key, AnyHash > &other)
template<class UnaryPredicate >
Foam::label filterKeys (const UnaryPredicate &pred, const bool pruning)
template<class UnaryPredicate >
Foam::label filterValues (const UnaryPredicate &pred, const bool pruning)
template<class BinaryPredicate >
Foam::label filterEntries (const BinaryPredicate &pred, const bool pruning)
Public Member Functions inherited from HashTableCore
ClassName ("HashTable")
HashTableCore () noexcept=default
Static Public Member Functions
static word wordify (const string &sname)
Static Public Member Functions inherited from HashTableCore
static label canonicalSize (const label requested_size)
Friends
Ostream & operator<< (Ostream &, const graph &)
Additional Inherited Members
Public Types inherited from HashPtrTable< curve >
typedef HashPtrTable< curve, word, Foam::Hash< word > > this_type
typedef HashTable< curve *, word, Foam::Hash< word > > parent_type
using iterator = typename parent_type::iterator
using const_iterator = typename parent_type::const_iterator
Public Types inherited from HashTable< T, Key, Hash >
typedef HashTable< T, Key, Hash > this_type
typedef std::conditional< std::is_same< Foam::zero, typenamestd::remove_cv< T >::type >::value, Detail::HashTableSingle< Key >, Detail::HashTablePair< Key, T > >::type node_type
typedef Key key_type
typedef T mapped_type
typedef T value_type
typedef Hash hasher
typedef T * pointer
typedef T & reference
typedef const T * const_pointer
typedef const T & const_reference
typedef label difference_type
typedef label size_type
using key_iterator = key_iterator_base< iterator >
using const_key_iterator = key_iterator_base< const_iterator >
Static Public Attributes inherited from HashTableCore
static const label maxTableSize
Detailed Description
Class to create, store and output qgraph files.
Source files
graph.H
graph.C
Definition at line 53 of file graph.H.
Constructor & Destructor Documentation
graph() [1/4]
graph (const string & title, const string & xName, const string & yName, const scalarField & x)
Definition at line 74 of file graph.C.
graph() [2/4]
graph (const string & title, const string & xName, const string & yName, const scalarField & x, const scalarField & y)
Definition at line 89 of file graph.C.
References curve::curveStyle::CONTINUOUS, HashPtrTable< curve >::set(), graph::wordify(), graph::y(), and graph::yName().
graph() [3/4]
graph (const string & title, const string & xName, const string & yName, Istream & is)
Definition at line 111 of file graph.C.
graph() [4/4]
graph (Istream & is) explicit
Definition at line 127 of file graph.C.
Member Function Documentation
title()
const string & title () const inline
Definition at line 141 of file graph.H.
xName()
const string & xName () const inline
Definition at line 146 of file graph.H.
yName()
const string & yName () const inline
Definition at line 151 of file graph.H.
Referenced by graph::graph().
x() [1/2]
const scalarField & x () const inline
Definition at line 157 of file graph.H.
x() [2/2]
scalarField & x () inline
Definition at line 162 of file graph.H.
y() [1/2]
const Foam::scalarField & y () const
Definition at line 137 of file graph.C.
References Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
Referenced by graph::graph().
y() [2/2]
Foam::scalarField & y ()
Definition at line 150 of file graph.C.
References Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
setXRange()
void setXRange (const scalar x0, const scalar x1)
Definition at line 163 of file graph.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, forAllIters, Foam::nl, and PtrList< T >::transfer().
writeTable()
void writeTable (Ostream & os) const
Definition at line 244 of file graph.C.
References Foam::endl(), forAll, forAllConstIters, os(), Foam::setw(), and token::SPACE.
write() [1/3]
void write (Ostream & os, const word & format) const
Definition at line 259 of file graph.C.
References format(), os(), and write().
Referenced by Foam::makeGraph(), Foam::writeCellGraph(), and Foam::writePatchGraph().
write() [2/3]
void write (const fileName & pName, const word & format) const
Definition at line 265 of file graph.C.
References Foam::endl(), format(), WarningInFunction, write(), and writer().
write() [3/3]
void write (const fileName & path, const word & name, const word & format) const
Definition at line 284 of file graph.C.
References format(), Foam::mkDir(), Foam::name(), path(), and write().
wordify()
Foam::word wordify (const string & sname) static
Definition at line 40 of file graph.C.
Referenced by graph::graph().
Friends And Related Symbol Documentation
operator<<
Ostream & operator<< (Ostream & , const graph &) friend
The documentation for this class was generated from the following files:
src/meshTools/graph/graph.H
src/meshTools/graph/graph.C