OpenFOAM: CoBlended< Type > Class Template Reference
CoBlended< Type > Class Template Reference
Numerics » Finite volume numerical schemes » Surface interpolation schemes
Two-scheme Courant number based blending differencing scheme.
#include <CoBlended.H>
Public Member Functions
TypeName ("CoBlended")
CoBlended (const fvMesh &mesh, Istream &is)
CoBlended (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &is)
virtual tmp< surfaceScalarField > blendingFactor (const GeometricField< Type, fvPatchField, volMesh > &vf) const
tmp< surfaceScalarField > weights (const GeometricField< Type, fvPatchField, volMesh > &vf) const
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &vf) const
virtual bool corrected () const
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > &vf) const
Public Member Functions inherited from surfaceInterpolationScheme< Type >
TypeName ("surfaceInterpolationScheme")
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, Mesh,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, MeshFlux,(const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
surfaceInterpolationScheme (const fvMesh &mesh)
virtual ~surfaceInterpolationScheme ()=default
const fvMesh & mesh () const
virtual tmp< GeometricField< typename innerProduct< vector, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf) const
tmp< GeometricField< typename innerProduct< vector, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const tmp< GeometricField< Type, fvPatchField, volMesh > > &) const
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > &) const
template<class SFType >
Foam::tmp< Foam::GeometricField< typename Foam::innerProduct< typename SFType::value_type, Type >::type, Foam::fvsPatchField, Foam::surfaceMesh > > dotInterpolate (const SFType &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf, const tmp< surfaceScalarField > &tlambdas)
tmp< GeometricField< typename innerProduct< vector, scalar >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const GeometricField< scalar, fvPatchField, volMesh > &) const
Foam::tmp< Foam::GeometricField< typename Foam::innerProduct< Foam::vector, Foam::scalar >::type, Foam::fvsPatchField, Foam::surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const GeometricField< scalar, fvPatchField, volMesh > &) const
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Public Member Functions inherited from blendedSchemeBase< Type >
blendedSchemeBase ()=default
virtual ~blendedSchemeBase ()=default
Additional Inherited Members
Static Public Member Functions inherited from surfaceInterpolationScheme< Type >
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData)
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &, const tmp< surfaceScalarField > &)
template<class SFType >
static tmp< GeometricField< typename innerProduct< typename SFType::value_type, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const SFType &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf, const tmp< surfaceScalarField > &tlambdas)
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &)
Detailed Description
template<class Type>
class Foam::CoBlended< Type >
Two-scheme Courant number based blending differencing scheme.
Similar to localBlended but uses a blending factor computed from the face-based Courant number and the lower and upper Courant number limits supplied:
where
= Courant number below which scheme1 is used
= Courant number above which scheme2 is used
The weight applies to the first scheme and 1-weight to the second scheme.
Usage
Example of the CoBlended scheme specification using LUST for Courant numbers less than 1 and linearUpwind for Courant numbers greater than 10:
divSchemes
{
    .
    .
    div(phi,U)      Gauss CoBlended 1 LUST grad(U) 10 linearUpwind grad(U);
    .
    .
}
Source files
CoBlended.H
CoBlended.C
Definition at line 88 of file CoBlended.H.
Constructor & Destructor Documentation
CoBlended() [1/2]
template<class Type > CoBlended (const fvMesh & mesh, Istream & is) inline
Definition at line 131 of file CoBlended.H.
References Foam::exit(), Foam::FatalIOError, and FatalIOErrorInFunction.
CoBlended() [2/2]
template<class Type > CoBlended (const fvMesh & mesh, const surfaceScalarField & faceFlux, Istream & is) inline
Definition at line 164 of file CoBlended.H.
References Foam::exit(), Foam::FatalIOError, and FatalIOErrorInFunction.
Member Function Documentation
TypeName()
template<class Type > TypeName ("CoBlended< Type >")
blendingFactor()
template<class Type > virtual tmp< surfaceScalarField > blendingFactor (const GeometricField< Type, fvPatchField, volMesh > & vf) const inline virtual
Implements blendedSchemeBase< Type >.
Definition at line 197 of file CoBlended.H.
References Foam::clamp(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimMass, Foam::dimTime, Foam::dimVolume, Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::fvc::interpolate(), Foam::mag(), surfaceInterpolationScheme< Type >::mesh(), and rho.
Referenced by CoBlended< Type >::correction(), CoBlended< Type >::interpolate(), and CoBlended< Type >::weights().
weights()
template<class Type > tmp< surfaceScalarField > weights (const GeometricField< Type, fvPatchField, volMesh > & vf) const inline virtual
Implements surfaceInterpolationScheme< Type >.
Definition at line 244 of file CoBlended.H.
References CoBlended< Type >::blendingFactor().
interpolate()
template<class Type > tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > & vf) const inline virtual
Reimplemented from surfaceInterpolationScheme< Type >.
Definition at line 260 of file CoBlended.H.
References CoBlended< Type >::blendingFactor().
corrected()
template<class Type > virtual bool corrected () const inline virtual
Reimplemented from surfaceInterpolationScheme< Type >.
Definition at line 274 of file CoBlended.H.
Referenced by CoBlended< Type >::correction().
correction()
template<class Type > virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > & vf) const inline virtual
Reimplemented from surfaceInterpolationScheme< Type >.
Definition at line 283 of file CoBlended.H.
References CoBlended< Type >::blendingFactor(), CoBlended< Type >::corrected(), and CoBlended< Type >::correction().
Referenced by CoBlended< Type >::correction().
The documentation for this class was generated from the following file:
src/finiteVolume/interpolation/surfaceInterpolation/schemes/CoBlended/CoBlended.H