OpenFOAM: areaWrite Class Reference
areaWrite Class Reference
Write finite area mesh/fields to standard output formats.
#include <areaWrite.H>
Public Member Functions
TypeName ("areaWrite")
areaWrite (const word &name, const Time &runTime, const dictionary &dict)
areaWrite (const word &name, const objectRegistry &obr, const dictionary &dict, const bool loadFromFiles=false)
virtual ~areaWrite ()=default
bool verbose (const bool on) noexcept
virtual bool read (const dictionary &dict)
virtual bool execute ()
virtual bool write ()
virtual void updateMesh (const mapPolyMesh &mpm)
virtual void movePoints (const polyMesh &mesh)
virtual void readUpdate (const polyMesh::readUpdateState state)
Public Member Functions inherited from fvMeshFunctionObject
TypeName ("fvMeshFunctionObject")
fvMeshFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
fvMeshFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
virtual ~fvMeshFunctionObject ()=default
Public Member Functions inherited from regionFunctionObject
TypeName ("regionFunctionObject")
regionFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
regionFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
virtual ~regionFunctionObject ()=default
template<class ObjectType >
const ObjectType * lookupObjectPtr (const word &fieldName) const
template<class ObjectType >
ObjectType * lookupObjectRefPtr (const word &fieldName) const
Public Member Functions inherited from stateFunctionObject
stateFunctionObject (const word &name, const Time &runTime)
virtual ~stateFunctionObject ()=default
dictionary & propertyDict ()
bool foundProperty (const word &entryName) const
void clearTrigger ()
label getTrigger () const
bool setTrigger (const label triggeri)
bool getDict (const word &entryName, dictionary &dict) const
bool getObjectDict (const word &objectName, const word &entryName, dictionary &dict) const
template<class Type >
Type getProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getProperty (const word &entryName, Type &value) const
template<class Type >
void setProperty (const word &entryName, const Type &value)
template<class Type >
Type getObjectProperty (const word &objectName, const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getObjectProperty (const word &objectName, const word &entryName, Type &value) const
template<class Type >
void setObjectProperty (const word &objectName, const word &entryName, const Type &value)
template<class Type >
void setResult (const word &entryName, const Type &value)
template<class Type >
void setObjectResult (const word &objectName, const word &entryName, const Type &value)
template<class Type >
Type getResult (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
Type getObjectResult (const word &objectName, const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getObjectResult (const word &objectName, const word &entryName, Type &value) const
word resultType (const word &entryName) const
word objectResultType (const word &objectName, const word &entryName) const
wordList objectResultEntries () const
wordList objectResultEntries (const word &objectName) const
void writeResultEntries (Ostream &os) const
void writeResultEntries (const word &objectName, Ostream &os) const
void writeAllResultEntries (Ostream &os) const
Public Member Functions inherited from timeFunctionObject
timeFunctionObject (const word &name, const Time &runTime)
virtual ~timeFunctionObject ()=default
const Time & time () const
objectRegistry & storedObjects ()
const objectRegistry & storedObjects () const
Public Member Functions inherited from functionObject
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name, const bool withNamePrefix=defaultUseNamePrefix)
autoPtr< functionObject > clone () const
virtual ~functionObject ()=default
virtual const word & type () const =0
const word & name () const noexcept
bool useNamePrefix () const noexcept
bool useNamePrefix (bool on) noexcept
virtual bool execute (const label subIndex)
virtual bool end ()
virtual bool adjustTimeStep ()
virtual bool filesModified () const
Static Public Member Functions
static scalar mergeTol () noexcept
static scalar mergeTol (const scalar tol) noexcept
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &runTime, const dictionary &dict)
Additional Inherited Members
Public Attributes inherited from functionObject
bool log
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
static bool defaultUseNamePrefix
static word outputPrefix
Protected Member Functions inherited from fvMeshFunctionObject
fvMeshFunctionObject (const fvMeshFunctionObject &)=delete
void operator= (const fvMeshFunctionObject &)=delete
Protected Member Functions inherited from regionFunctionObject
virtual const objectRegistry & obr () const
template<class ObjectType >
bool foundObject (const word &fieldName) const
template<class ObjectType >
const ObjectType * cfindObject (const word &fieldName) const
template<class ObjectType >
const ObjectType * findObject (const word &fieldName) const
template<class ObjectType >
ObjectType * findObject (const word &fieldName)
template<class ObjectType >
ObjectType * getObjectPtr (const word &fieldName) const
template<class ObjectType >
const ObjectType & lookupObject (const word &fieldName) const
template<class ObjectType >
ObjectType & lookupObjectRef (const word &fieldName) const
template<class ObjectType >
bool store (word &fieldName, const tmp< ObjectType > &tfield, bool cacheable=false)
template<class ObjectType >
bool storeInDb (const word &fieldName, const tmp< ObjectType > &tfield, const objectRegistry &obr)
bool writeObject (const word &fieldName)
bool clearObject (const word &fieldName)
void clearObjects (const wordList &objNames)
regionFunctionObject (const regionFunctionObject &)=delete
void operator= (const regionFunctionObject &)=delete
Protected Member Functions inherited from stateFunctionObject
const functionObjects::properties & stateDict () const
functionObjects::properties & stateDict ()
stateFunctionObject (const stateFunctionObject &)=delete
void operator= (const stateFunctionObject &)=delete
Protected Member Functions inherited from timeFunctionObject
void clearOutputObjects (const wordList &objNames)
timeFunctionObject (const timeFunctionObject &)=delete
void operator= (const timeFunctionObject &)=delete
Protected Member Functions inherited from functionObject
word scopedName (const word &name) const
Protected Attributes inherited from fvMeshFunctionObject
const fvMesh & mesh_
Protected Attributes inherited from regionFunctionObject
word subRegistryName_
const objectRegistry & obr_
const objectRegistry * obrPtr_
Protected Attributes inherited from timeFunctionObject
const Time & time_
Detailed Description
Write finite area mesh/fields to standard output formats.
Example of function object specification:
surfaces
{
    type    areaWrite;
    libs    (utilityFunctionObjects);
    // Write at same frequency as fields
    writeControl    outputTime;
    writeInterval   1;
    // Fields to be sampled
    fields          (p U);
    // Output surface format
    surfaceFormat   vtk;
    formatOptions
    {
        vtk
        {
            precision  10;
        }
    }
}
Entries:
Property Description Required Default
type Type-name: areaWrite yes
region name for a single region no region0
area select a single area no
areas wordRe list of multiple areas no
fields wordRe list of fields yes
surfaceFormat output surface format yes
formatOptions dictionary of format options no
Source files
areaWrite.H
areaWrite.C
areaWriteTemplates.C
Definition at line 136 of file areaWrite.H.
Constructor & Destructor Documentation
areaWrite() [1/2]
areaWrite (const word & name, const Time & runTime, const dictionary & dict)
Definition at line 55 of file areaWrite.C.
References fileName::clean(), dict, Foam::name(), and areaWrite::read().
areaWrite() [2/2]
areaWrite (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false)
Definition at line 81 of file areaWrite.C.
References fileName::clean(), dict, and areaWrite::read().
~areaWrite()
virtual ~areaWrite () virtual default
Member Function Documentation
TypeName()
TypeName ("areaWrite")
verbose()
bool verbose (const bool on) noexcept
Definition at line 110 of file areaWrite.C.
read()
bool read (const dictionary & dict) virtual
Reimplemented from regionFunctionObject.
Definition at line 118 of file areaWrite.C.
References dict, UPtrList< T >::empty(), UList< T >::first(), surfaceWriter::formatOptions(), dictionary::get(), dictionary::getOrDefault(), surfaceWriter::New(), IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, dictionary::readEntry(), dictionary::readIfPresent(), PtrList< T >::set(), and UList< T >::size().
Referenced by areaWrite::areaWrite(), and areaWrite::areaWrite().
execute()
bool execute () virtual
Implements functionObject.
Definition at line 204 of file areaWrite.C.
write()
bool write () virtual
Implements functionObject.
Definition at line 210 of file areaWrite.C.
References PtrList< T >::append(), Foam::fieldTypes::area, Foam::fieldTypes::area_internal, PtrList< T >::clear(), doLocalCode, Foam::endl(), forAll, forAllConstIters, found, Foam::ListOps::found(), Pstream::mapCombineReduce(), n, Foam::nl, pts, UPtrList< T >::size(), GeoMesh< MESH >::thisDb(), PtrList< T >::transfer(), and WarningInFunction.
updateMesh()
void updateMesh (const mapPolyMesh & mpm) virtual
Reimplemented from functionObject.
Definition at line 393 of file areaWrite.C.
movePoints()
void movePoints (const polyMesh & mesh) virtual
Reimplemented from functionObject.
Definition at line 402 of file areaWrite.C.
References mesh.
readUpdate()
void readUpdate (const polyMesh::readUpdateState state) virtual
Definition at line 411 of file areaWrite.C.
References polyMesh::UNCHANGED.
mergeTol() [1/2]
Foam::scalar mergeTol () static noexcept
Definition at line 420 of file areaWrite.C.
mergeTol() [2/2]
Foam::scalar mergeTol (const scalar tol) static noexcept
Definition at line 426 of file areaWrite.C.
The documentation for this class was generated from the following files:
src/functionObjects/utilities/areaWrite/areaWrite.H
src/functionObjects/utilities/areaWrite/areaWrite.C
src/functionObjects/utilities/areaWrite/areaWriteImpl.C