OpenFOAM: PackedList< Width > Class Template Reference
PackedList< Width > Class Template Reference
A dynamic list of packed unsigned integers, with the number of bits per item specified by the <Width> template parameter.
#include <PackedList.H>
Classes
struct hasher
class reference
Public Types
typedef unsigned int block_type
typedef unsigned int const_reference
Public Member Functions
constexpr PackedList () noexcept
PackedList (const label numElem)
PackedList (const label numElem, const unsigned int val)
PackedList (Istream &is)
PackedList (const PackedList< Width > &list)
PackedList (PackedList< Width > &&list)
PackedList (const PackedList< Width > &list, const labelUList &addr)
template<class Addr >
PackedList (const PackedList< Width > &list, const IndirectListBase< label, Addr > &addr)
PackedList (const PackedList< Width > &list, const labelRange &range)
PackedList (const labelUList &values)
template<class Addr >
PackedList (const IndirectListBase< label, Addr > &values)
autoPtr< PackedList< Width > > clone () const
void checkIndex (const label i) const
bool empty () const noexcept
label size () const noexcept
label capacity () const noexcept
bool uniform () const
bool equal (const PackedList< Width > &other) const
unsigned int get (const label i) const
bool set (const label i, unsigned int val=~0u)
bool unset (const label i)
labelList values () const
template<class IntType = unsigned int>
List< IntType > unpack () const
template<class IntType = unsigned int>
List< IntType > unpack (const labelRange &range) const
template<class IntType = unsigned int>
List< IntType > unpack (const labelUList &locations) const
void fill (const unsigned int val)
bool trim (label minpos=-1)
void reset ()
void setCapacity (const label numElem)
void resize (const label numElem, const unsigned int val=0u)
void resize_nocopy (const label numElem)
void reserve (const label numElem)
void clear ()
void clearStorage ()
void shrink ()
void swap (PackedList< Width > &rhs)
void transfer (PackedList< Width > &rhs)
label nBlocks () const
const List< unsigned int > & storage () const
List< unsigned int > & storage ()
const unsigned int * cdata () const noexcept
unsigned int * data () noexcept
const char * cdata_bytes () const noexcept
char * data_bytes () noexcept
std::streamsize size_data () const noexcept
std::streamsize size_bytes () const noexcept
std::streamsize byteSize () const noexcept
Ostream & printBits (Ostream &os, bool debugOutput=false) const
Istream & readList (Istream &is)
Ostream & writeList (Ostream &os, const label shortLen=0) const
void writeEntry (const word &keyword, Ostream &os) const
void push_back (const unsigned int val)
void pop_back (label n=1)
unsigned int remove ()
unsigned int operator[] (const label i) const
reference operator[] (const label i)
void operator= (const PackedList< Width > &lst)
void operator= (PackedList< Width > &&lst)
void operator= (const unsigned int val)
InfoProxy< PackedList< Width > > info () const noexcept
void assign (const unsigned int val)
void assign (const PackedList< Width > &rhs)
void setSize (const label n, unsigned int val=0u)
PackedList< Width > & append (const unsigned int val)
template<class IntType >
Foam::List< IntType > unpack () const
template<class IntType >
Foam::List< IntType > unpack (const labelRange &range) const
template<class IntType >
Foam::List< IntType > unpack (const labelUList &locations) const
Public Member Functions inherited from PackedListCore
ClassNameNoDebug ("PackedList")
Static Public Member Functions
static constexpr label num_blocks (label numElem) noexcept
static constexpr block_type mask_lower (unsigned elementOffset)
Static Public Attributes
static constexpr unsigned bits_per_block = (std::numeric_limits<block_type>::digits)
static constexpr unsigned element_width = (Width)
static constexpr unsigned elem_per_block = (bits_per_block / Width)
static constexpr block_type max_value = ((1u << Width) - 1)
Protected Types
typedef List< block_type > block_container
Protected Member Functions
void setPair (Istream &is)
void writeEntry (Ostream &os) const
void clear_trailing_bits ()
void copyAssign (const PackedList< Width > &rhs)
unsigned int repeated_value (unsigned val)
unsigned int readValue (Istream &is)
void setPair (Istream &is)
Static Protected Member Functions
static unsigned int repeated_value (unsigned val)
static unsigned int readValue (Istream &is)
Protected Attributes
block_container blocks_
label size_
Friends
Ostream & operator<< (Ostream &os, const InfoProxy< PackedList< Width > > &info)
Istream & operator>> (Istream &is, PackedList< Width > &list)
Detailed Description
template<unsigned Width>
class Foam::PackedList< Width >
A dynamic list of packed unsigned integers, with the number of bits per item specified by the <Width> template parameter.
Resizing is similar to DynamicList so that clear() and resize() affect the addressed size, but not the allocated size. The reserve() and setCapacity() methods can be used to influence the allocation.
Note
In a const context, the '[]' operator simply returns the stored value, with out-of-range elements returned as zero.
In a non-const context, the '[]' operator returns a reference to an existing value. When accessing out-of-range elements, some caution is required to ensure that the const version of the [] operator is actually being called. The get() method is functionally identical the the '[]' operator, but is always const access.
The set() and unset() methods return a bool if the value changed.
With const access, the get() method and 'operator[]' are identical. With non-const access, the 'operator[]' may be marginally slower get().
The set() method may be marginally faster than using the 'operator[]' supports auto-vivification and also returns a bool if the value changed, which can be useful for branching on changed values.
list.set(5, 4);
changed = list.set(5, 8);
if (changed) ...
In a const context, reading an out-of-range element returns zero without affecting the list size. For example,
list.resize(4);
Info<< list.get(10) << "\n";    // print zero, but doesn't adjust list
list.set(8);                    // auto-vivify
Also note that all unused internal storage elements are guaranteed to always be bit-wise zero. This property must not be violated by any inheriting classes.
Note
Iterators for this class have been intentionally removed, for performance reasons.
See also
Foam::BitOps Foam::DynamicList
Source files
PackedList.H
PackedListI.H
PackedList.C
PackedListIO.C
Definition at line 122 of file PackedList.H.
Member Typedef Documentation
block_type
template<unsigned Width> typedef unsigned int block_type
Definition at line 132 of file PackedList.H.
block_container
template<unsigned Width> typedef List<block_type> block_container protected
Definition at line 177 of file PackedList.H.
const_reference
template<unsigned Width> typedef unsigned int const_reference
Definition at line 225 of file PackedList.H.
Constructor & Destructor Documentation
PackedList() [1/11]
template<unsigned Width> constexpr PackedList () inline constexpr noexcept
Definition at line 170 of file PackedListI.H.
PackedList() [2/11]
template<unsigned Width> PackedList (const label numElem) inline explicit
Definition at line 178 of file PackedListI.H.
PackedList() [3/11]
template<unsigned Width> PackedList (const label numElem, const unsigned int val) inline
Definition at line 186 of file PackedListI.H.
References PackedList< Width >::operator=().
PackedList() [4/11]
template<unsigned Width> PackedList (Istream & is) inline
Definition at line 203 of file PackedListI.H.
PackedList() [5/11]
template<unsigned Width> PackedList (const PackedList< Width > & list) inline
Definition at line 213 of file PackedListI.H.
PackedList() [6/11]
template<unsigned Width> PackedList (PackedList< Width > && list) inline
Definition at line 221 of file PackedListI.H.
PackedList() [7/11]
template<unsigned Width> PackedList (const PackedList< Width > & list, const labelUList & addr)
Definition at line 27 of file PackedList.C.
References UPtrList< T >::get(), PackedList< Width >::set(), and UPtrList< T >::size().
PackedList() [8/11]
template<unsigned Width> template<class Addr > PackedList (const PackedList< Width > & list, const IndirectListBase< label, Addr > & addr)
Definition at line 46 of file PackedList.C.
References UPtrList< T >::get(), PackedList< Width >::set(), and UPtrList< T >::size().
PackedList() [9/11]
template<unsigned Width> PackedList (const PackedList< Width > & list, const labelRange & range)
Definition at line 64 of file PackedList.C.
References UPtrList< T >::get(), Foam::pos(), range, PackedList< Width >::set(), and UPtrList< T >::size().
PackedList() [10/11]
template<unsigned Width> PackedList (const labelUList & values) inline explicit
Definition at line 231 of file PackedListI.H.
PackedList() [11/11]
template<unsigned Width> template<class Addr > PackedList (const IndirectListBase< label, Addr > & values) inline explicit
Definition at line 251 of file PackedListI.H.
References UList< T >::size(), and PackedList< Width >::values().
Member Function Documentation
num_blocks()
template<unsigned Width> static constexpr label num_blocks (label numElem) inline static constexpr noexcept
Definition at line 159 of file PackedList.H.
References PackedList< Width >::elem_per_block.
mask_lower()
template<unsigned Width> static constexpr block_type mask_lower (unsigned elementOffset) inline static constexpr
Definition at line 166 of file PackedList.H.
References PackedList< Width >::bits_per_block.
repeated_value() [1/2]
template<unsigned Width> unsigned int repeated_value (unsigned val) inline static protected
Definition at line 27 of file PackedListI.H.
readValue() [1/2]
template<unsigned Width> unsigned int readValue (Istream & is) inline static protected
Definition at line 34 of file PackedListI.H.
References Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, and Foam::readLabel().
setPair() [1/2]
template<unsigned Width> void setPair (Istream & is) inline protected
Definition at line 51 of file PackedListI.H.
References Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, FUNCTION_NAME, and Foam::readLabel().
writeEntry() [1/2]
template<unsigned Width> void writeEntry (Ostream & os) const protected
Definition at line 27 of file PackedListIO.C.
References os().
clear_trailing_bits()
template<unsigned Width> void clear_trailing_bits () inline protected
Definition at line 76 of file PackedListI.H.
copyAssign()
template<unsigned Width> void copyAssign (const PackedList< Width > & rhs) inline protected
Definition at line 135 of file PackedListI.H.
clone()
template<unsigned Width> Foam::autoPtr< Foam::PackedList< Width > > clone () const inline
Definition at line 274 of file PackedListI.H.
References Foam::New().
checkIndex()
template<unsigned Width> void checkIndex (const label i) const inline
Definition at line 352 of file PackedListI.H.
empty()
template<unsigned Width> bool empty () const inline noexcept
Definition at line 282 of file PackedList.H.
References PackedList< Width >::size_.
Referenced by dynamicRefineFvMesh::calculateProtectedCells(), and ensightMesh::correct().
size()
template<unsigned Width> label size () const inline noexcept
Definition at line 285 of file PackedList.H.
References PackedList< Width >::size_.
Referenced by bitSet::andEq(), Foam::apply(), bitSet::bound(), polyDualMesh::calcFeatures(), bitSet::extend(), bitSet::intersects(), Foam::invert(), bitSet::minusEq(), Foam::operator<<(), bitSet::orEq(), ensightCase::printTimeset(), Foam::reorder(), and bitSet::xorEq().
capacity()
template<unsigned Width> Foam::label capacity () const inline noexcept
Definition at line 370 of file PackedListI.H.
References UPtrList< T >::size().
Referenced by Foam::operator<<().
uniform()
template<unsigned Width> bool uniform () const
Definition at line 86 of file PackedList.C.
equal()
template<unsigned Width> bool equal (const PackedList< Width > & other) const
Definition at line 145 of file PackedList.C.
References UPtrList< T >::size().
get()
template<unsigned Width> unsigned int get (const label i) const inline
Definition at line 616 of file PackedListI.H.
References Foam::endl(), PackedList< Width >::reference::get(), and WarningInFunction.
Referenced by bitSet::bitSet(), bitSet::bitSet(), and bitSet::bitSet().
set()
template<unsigned Width> bool set (const label i, unsigned int val = ~0u) inline
Definition at line 638 of file PackedListI.H.
References Foam::endl(), resize(), PackedList< Width >::reference::set(), and WarningInFunction.
Referenced by PackedList< 1 >::PackedList(), PackedList< Width >::PackedList(), PackedList< Width >::PackedList(), and PackedList< Width >::PackedList().
unset()
template<unsigned Width> bool unset (const label i) inline
Definition at line 670 of file PackedListI.H.
References PackedList< Width >::reference::set().
values()
template<unsigned Width> Foam::labelList values () const
Definition at line 168 of file PackedList.C.
Referenced by PackedList< Width >::PackedList(), and PackedList< 1 >::PackedList().
unpack() [1/6]
template<unsigned Width> template<class IntType = unsigned int> List< IntType > unpack () const
unpack() [2/6]
template<unsigned Width> template<class IntType = unsigned int> List< IntType > unpack (const labelRange & range) const
unpack() [3/6]
template<unsigned Width> template<class IntType = unsigned int> List< IntType > unpack (const labelUList & locations) const
fill()
template<unsigned Width> void fill (const unsigned int val) inline
Definition at line 726 of file PackedListI.H.
Referenced by PackedList< Width >::assign().
trim()
template<unsigned Width> bool trim (label minpos = -1) inline
Definition at line 90 of file PackedListI.H.
Referenced by Foam::reorder().
reset()
template<unsigned Width> void reset () inline
Definition at line 484 of file PackedListI.H.
Referenced by Foam::calcElementMasks(), parcelSelection::calculateFilter(), and topoBitSet::reset().
setCapacity()
template<unsigned Width> void setCapacity (const label numElem) inline
Definition at line 450 of file PackedListI.H.
resize()
template<unsigned Width> void resize (const label numElem, const unsigned int val = 0u) inline
Definition at line 387 of file PackedListI.H.
Referenced by Foam::calcElementMasks(), parcelSelection::calculateFilter(), ensightMesh::correct(), fvMeshSubsetProxy::correct(), PackedList< Width >::setSize(), topoBitSet::topoBitSet(), topoBitSet::topoBitSet(), and topoBitSet::topoBitSet().
resize_nocopy()
template<unsigned Width> void resize_nocopy (const label numElem) inline
Definition at line 377 of file PackedListI.H.
reserve()
template<unsigned Width> void reserve (const label numElem) inline
Definition at line 465 of file PackedListI.H.
References Foam::max(), and UPtrList< T >::size().
Referenced by Foam::reorder().
clear()
template<unsigned Width> void clear () inline
Definition at line 491 of file PackedListI.H.
Referenced by parcelSelection::calculateFilter().
clearStorage()
template<unsigned Width> void clearStorage () inline
Definition at line 499 of file PackedListI.H.
References PtrList< T >::clear().
Referenced by ensightMesh::correct().
shrink()
template<unsigned Width> void shrink () inline
Definition at line 507 of file PackedListI.H.
References UPtrList< T >::size().
swap()
template<unsigned Width> void swap (PackedList< Width > & rhs) inline
Definition at line 589 of file PackedListI.H.
References UPtrList< T >::swap().
Referenced by bitSet::swap().
transfer()
template<unsigned Width> void transfer (PackedList< Width > & rhs) inline
Definition at line 602 of file PackedListI.H.
References PtrList< T >::transfer().
Referenced by bitSet::transfer().
nBlocks()
template<unsigned Width> Foam::label nBlocks () const inline
Definition at line 533 of file PackedListI.H.
storage() [1/2]
template<unsigned Width> const Foam::List< unsigned int > & storage () const inline
Definition at line 526 of file PackedListI.H.
storage() [2/2]
template<unsigned Width> Foam::List< unsigned int > & storage () inline
Definition at line 519 of file PackedListI.H.
cdata()
template<unsigned Width> const unsigned int * cdata () const inline noexcept
Definition at line 540 of file PackedListI.H.
data()
template<unsigned Width> unsigned int * data () inline noexcept
Definition at line 547 of file PackedListI.H.
cdata_bytes()
template<unsigned Width> const char * cdata_bytes () const inline noexcept
Definition at line 554 of file PackedListI.H.
data_bytes()
template<unsigned Width> char * data_bytes () inline noexcept
Definition at line 561 of file PackedListI.H.
size_data()
template<unsigned Width> std::streamsize size_data () const inline noexcept
Definition at line 568 of file PackedListI.H.
size_bytes()
template<unsigned Width> std::streamsize size_bytes () const inline noexcept
Definition at line 575 of file PackedListI.H.
byteSize()
template<unsigned Width> std::streamsize byteSize () const inline noexcept
Definition at line 582 of file PackedListI.H.
printBits()
template<unsigned Width> Foam::Ostream & printBits (Ostream & os, bool debugOutput = false) const
Definition at line 36 of file PackedListIO.C.
References token::BEGIN_LIST, token::END_LIST, Foam::nl, os(), Foam::BitOps::print(), and UPtrList< T >::size().
readList()
template<unsigned Width> Foam::Istream & readList (Istream & is)
Definition at line 57 of file PackedListIO.C.
References token::BEGIN_BLOCK, token::BEGIN_LIST, IOstreamOption::BINARY, PtrList< T >::clear(), token::END_BLOCK, token::END_LIST, Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, FUNCTION_NAME, Foam::nl, PtrList< T >::push_back(), PtrList< T >::resize(), and PtrList< T >::set().
writeList()
template<unsigned Width> Foam::Ostream & writeList (Ostream & os, const label shortLen = 0) const
Definition at line 171 of file PackedListIO.C.
References token::BEGIN_BLOCK, token::BEGIN_LIST, IOstreamOption::BINARY, token::END_BLOCK, IOstreamOption::format(), UPtrList< T >::get(), Foam::nl, os(), UPtrList< T >::size(), token::SPACE, and OBJstream::write().
Referenced by Foam::operator<<().
writeEntry() [2/2]
template<unsigned Width> void writeEntry (const word & keyword, Ostream & os) const
Definition at line 236 of file PackedListIO.C.
References token::END_STATEMENT, Foam::endl(), os(), and Ostream::writeKeyword().
push_back()
template<unsigned Width> void push_back (const unsigned int val) inline
Definition at line 682 of file PackedListI.H.
References reserve(), and PackedList< Width >::reference::set().
Referenced by PackedList< Width >::append().
pop_back()
template<unsigned Width> void pop_back (label n = 1) inline
Definition at line 693 of file PackedListI.H.
References clear(), n, and resize().
remove()
template<unsigned Width> unsigned int remove () inline
Definition at line 707 of file PackedListI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, PackedList< Width >::reference::get(), and resize().
operator[]() [1/2]
template<unsigned Width> unsigned int operator[] (const label i) const inline
Definition at line 753 of file PackedListI.H.
operator[]() [2/2]
template<unsigned Width> Foam::PackedList< Width >::reference operator[] (const label i) inline
Definition at line 761 of file PackedListI.H.
operator=() [1/3]
template<unsigned Width> void operator= (const PackedList< Width > & lst) inline
Definition at line 771 of file PackedListI.H.
Referenced by bitSet::operator=(), and PackedList< Width >::PackedList().
operator=() [2/3]
template<unsigned Width> void operator= (PackedList< Width > && lst) inline
Definition at line 778 of file PackedListI.H.
operator=() [3/3]
template<unsigned Width> void operator= (const unsigned int val) inline
Definition at line 785 of file PackedListI.H.
info()
template<unsigned Width> InfoProxy< PackedList< Width > > info () const inline noexcept
Definition at line 513 of file PackedList.H.
assign() [1/2]
template<unsigned Width> void assign (const unsigned int val) inline
Definition at line 553 of file PackedList.H.
References PackedList< Width >::fill().
assign() [2/2]
template<unsigned Width> void assign (const PackedList< Width > & rhs) inline
Definition at line 557 of file PackedList.H.
setSize()
template<unsigned Width> void setSize (const label n, unsigned int val = 0u) inline
Definition at line 560 of file PackedList.H.
References n, and PackedList< Width >::resize().
append()
template<unsigned Width> PackedList< Width > & append (const unsigned int val) inline
Definition at line 564 of file PackedList.H.
References PackedList< Width >::push_back().
unpack() [4/6]
template<unsigned Width> template<class IntType > Foam::List< IntType > unpack () const
Definition at line 177 of file PackedList.C.
References Foam::output().
unpack() [5/6]
template<unsigned Width> template<class IntType > Foam::List< IntType > unpack (const labelRange & range) const
Definition at line 229 of file PackedList.C.
References Foam::output(), Foam::pos(), range, and UPtrList< T >::size().
unpack() [6/6]
template<unsigned Width> template<class IntType > Foam::List< IntType > unpack (const labelUList & locations) const
Definition at line 263 of file PackedList.C.
References Foam::output(), Foam::pos(), and UPtrList< T >::size().
repeated_value() [2/2]
unsigned int repeated_value (unsigned val) inline protected
Definition at line 149 of file PackedListI.H.
References PtrList< T >::PtrList().
readValue() [2/2]
unsigned int readValue (Istream & is) inline protected
Definition at line 154 of file PackedListI.H.
References Foam::readBool().
setPair() [2/2]
void setPair (Istream & is) inline protected
Definition at line 159 of file PackedListI.H.
References Foam::readLabel(), and PtrList< T >::set().
Friends And Related Symbol Documentation
operator<<
template<unsigned Width> Ostream & operator<< (Ostream & os, const InfoProxy< PackedList< Width > > & info) friend
operator>>
template<unsigned Width> Istream & operator>> (Istream & is, PackedList< Width > & list) friend
Member Data Documentation
bits_per_block
template<unsigned Width> constexpr unsigned bits_per_block = (std::numeric_limits<block_type>::digits) static constexpr
Definition at line 136 of file PackedList.H.
Referenced by PackedList< Width >::mask_lower().
element_width
template<unsigned Width> constexpr unsigned element_width = (Width) static constexpr
Definition at line 140 of file PackedList.H.
elem_per_block
template<unsigned Width> constexpr unsigned elem_per_block = (bits_per_block / Width) static constexpr
Definition at line 143 of file PackedList.H.
Referenced by PackedList< Width >::num_blocks().
max_value
template<unsigned Width> constexpr block_type max_value = ((1u << Width) - 1) static constexpr
Definition at line 148 of file PackedList.H.
blocks_
template<unsigned Width> block_container blocks_ protected
Definition at line 180 of file PackedList.H.
Referenced by bitSet::andEq(), bitSet::intersects(), bitSet::minusEq(), bitSet::orEq(), and bitSet::xorEq().
size_
template<unsigned Width> label size_ protected
Definition at line 183 of file PackedList.H.
Referenced by PackedList< Width >::empty(), and PackedList< Width >::size().
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/Bits/PackedList/PackedList.H
src/OpenFOAM/containers/Bits/PackedList/PackedList.C
src/OpenFOAM/containers/Bits/PackedList/PackedListI.H
src/OpenFOAM/containers/Bits/PackedList/PackedListIO.C