OpenFOAM: interfaceDefinitions Class Reference
interfaceDefinitions Class Reference
#include <ccmInterfaceDefinitions.H>
Public Member Functions
interfaceDefinitions ()
label size () const
bool empty () const
void clear ()
bool add (const interfaceEntry &entry)
bool isInterface (label bndId)
word interfaceName (label bndId)
Public Member Functions inherited from Map< interfaceEntry >
Map ()
Map (const label size)
Map (Istream &is)
Map (const this_type &map)
Map (this_type &&map)
Map (std::initializer_list< std::pair< label, interfaceEntry > > map)
void operator= (const this_type &rhs)
void operator= (this_type &&rhs)
Public Member Functions inherited from HashTable< T, Key, Hash >
HashTable ()
HashTable (const label size)
HashTable (Istream &is, const label size=128)
HashTable (const this_type &ht)
HashTable (this_type &&rhs)
HashTable (std::initializer_list< std::pair< Key, T > > list)
~HashTable ()
bool empty () const noexcept
label size () const noexcept
label capacity () const noexcept
T & at (const Key &key)
const T & at (const Key &key) const
bool contains (const Key &key) const
iterator find (const Key &key)
const_iterator find (const Key &key) const
const_iterator cfind (const Key &key) const
const T & lookup (const Key &key, const T &deflt) const
List< Key > toc () const
List< Key > sortedToc () const
template<class Compare >
List< Key > sortedToc (const Compare &comp) const
template<class UnaryPredicate >
List< Key > tocKeys (const UnaryPredicate &pred, const bool invert=false) const
template<class UnaryPredicate >
List< Key > tocValues (const UnaryPredicate &pred, const bool invert=false) const
template<class BinaryPredicate >
List< Key > tocEntries (const BinaryPredicate &pred, const bool invert=false) const
UPtrList< const node_type > csorted () const
UPtrList< const node_type > sorted () const
UPtrList< node_type > sorted ()
template<class UnaryPredicate >
label countKeys (const UnaryPredicate &pred, const bool invert=false) const
template<class UnaryPredicate >
label countValues (const UnaryPredicate &pred, const bool invert=false) const
template<class BinaryPredicate >
label countEntries (const BinaryPredicate &pred, const bool invert=false) const
template<class... Args>
bool emplace (const Key &key, Args &&... args)
template<class... Args>
bool emplace_set (const Key &key, Args &&... args)
bool insert (const Key &key, const T &obj)
bool insert (const Key &key, T &&obj)
bool set (const Key &key, const T &obj)
bool set (const Key &key, T &&obj)
bool erase (const iterator &iter)
bool erase (const Key &key)
template<class AnyType , class AnyHash >
label erase (const HashTable< AnyType, Key, AnyHash > &other)
label erase (std::initializer_list< Key > keys)
template<class InputIter >
label erase (InputIter first, InputIter last)
template<unsigned N>
label erase (const FixedList< Key, N > &keys)
label erase (const UList< Key > &keys)
template<class AnyType , class AnyHash >
label retain (const HashTable< AnyType, Key, AnyHash > &other)
template<class UnaryPredicate >
label filterKeys (const UnaryPredicate &pred, const bool pruning=false)
template<class UnaryPredicate >
label filterValues (const UnaryPredicate &pred, const bool pruning=false)
template<class BinaryPredicate >
label filterEntries (const BinaryPredicate &pred, const bool pruning=false)
void resize (const label sz)
void clear ()
void clearStorage ()
void swap (HashTable< T, Key, Hash > &rhs)
void transfer (HashTable< T, Key, Hash > &rhs)
void merge (HashTable< T, Key, Hash > &source)
void merge (HashTable< T, Key, Hash > &&source)
T & operator[] (const Key &key)
const T & operator[] (const Key &key) const
T & operator() (const Key &key)
T & operator() (const Key &key, const T &deflt)
void operator= (const this_type &rhs)
void operator= (std::initializer_list< std::pair< Key, T > > rhs)
void operator= (this_type &&rhs)
bool operator== (const this_type &rhs) const
bool operator!= (const this_type &rhs) const
this_type & operator+= (const this_type &rhs)
const_iterator_pair< const_key_iterator, this_type > keys () const
iterator begin ()
const_iterator begin () const
const_iterator cbegin () const
iterator end () noexcept
const_iterator end () const noexcept
constexpr const_iterator cend () const noexcept
Ostream & printInfo (Ostream &os) const
Ostream & writeKeys (Ostream &os, const label shortLen=0) const
bool found (const Key &key) const
template<class Compare >
Foam::List< Key > sortedToc (const Compare &comp) const
template<class UnaryPredicate >
Foam::List< Key > tocKeys (const UnaryPredicate &pred, const bool invert) const
template<class UnaryPredicate >
Foam::List< Key > tocValues (const UnaryPredicate &pred, const bool invert) const
template<class BinaryPredicate >
Foam::List< Key > tocEntries (const BinaryPredicate &pred, const bool invert) const
template<class UnaryPredicate >
Foam::label countKeys (const UnaryPredicate &pred, const bool invert) const
template<class UnaryPredicate >
Foam::label countValues (const UnaryPredicate &pred, const bool invert) const
template<class BinaryPredicate >
Foam::label countEntries (const BinaryPredicate &pred, const bool invert) const
template<class InputIter >
Foam::label erase (InputIter first, InputIter last)
template<unsigned N>
Foam::label erase (const FixedList< Key, N > &keys)
template<class AnyType , class AnyHash >
Foam::label erase (const HashTable< AnyType, Key, AnyHash > &other)
template<class AnyType , class AnyHash >
Foam::label retain (const HashTable< AnyType, Key, AnyHash > &other)
template<class UnaryPredicate >
Foam::label filterKeys (const UnaryPredicate &pred, const bool pruning)
template<class UnaryPredicate >
Foam::label filterValues (const UnaryPredicate &pred, const bool pruning)
template<class BinaryPredicate >
Foam::label filterEntries (const BinaryPredicate &pred, const bool pruning)
Public Member Functions inherited from HashTableCore
ClassName ("HashTable")
HashTableCore () noexcept=default
Friends
Ostream & operator<< (Ostream &os, const interfaceDefinitions &defs)
Additional Inherited Members
Public Types inherited from Map< interfaceEntry >
typedef Map< interfaceEntry > this_type
typedef HashTable< interfaceEntry, label, Hash< label > > parent_type
using iterator = typename parent_type::iterator
using const_iterator = typename parent_type::const_iterator
Public Types inherited from HashTable< T, Key, Hash >
typedef HashTable< T, Key, Hash > this_type
typedef std::conditional< std::is_same< Foam::zero, typenamestd::remove_cv< T >::type >::value, Detail::HashTableSingle< Key >, Detail::HashTablePair< Key, T > >::type node_type
typedef Key key_type
typedef T mapped_type
typedef T value_type
typedef Hash hasher
typedef T * pointer
typedef T & reference
typedef const T * const_pointer
typedef const T & const_reference
typedef label difference_type
typedef label size_type
using key_iterator = key_iterator_base< iterator >
using const_key_iterator = key_iterator_base< const_iterator >
Static Public Member Functions inherited from HashTableCore
static label canonicalSize (const label requested_size)
Static Public Attributes inherited from HashTableCore
static const label maxTableSize
Detailed Description
Definition at line 174 of file ccmInterfaceDefinitions.H.
Constructor & Destructor Documentation
interfaceDefinitions()
interfaceDefinitions () inline
Definition at line 194 of file ccmInterfaceDefinitions.H.
Member Function Documentation
size()
label size () const inline
Definition at line 198 of file ccmInterfaceDefinitions.H.
References HashTable< T, Key, Hash >::size().
empty()
bool empty () const inline
Definition at line 204 of file ccmInterfaceDefinitions.H.
References HashTable< T, Key, Hash >::empty().
clear()
void clear () inline
Definition at line 210 of file ccmInterfaceDefinitions.H.
References HashTable< T, Key, Hash >::clear().
add()
bool add (const interfaceEntry & entry) inline
Definition at line 217 of file ccmInterfaceDefinitions.H.
References HashTable< T, Key, Hash >::set().
isInterface()
bool isInterface (label bndId) inline
Definition at line 224 of file ccmInterfaceDefinitions.H.
References forAllConstIters.
interfaceName()
word interfaceName (label bndId) inline
Definition at line 239 of file ccmInterfaceDefinitions.H.
References UPtrList< T >::empty(), and forAllConstIters.
Friends And Related Symbol Documentation
operator<<
Ostream & operator<< (Ostream & os, const interfaceDefinitions & defs) friend
Definition at line 257 of file ccmInterfaceDefinitions.H.
The documentation for this class was generated from the following file:
src/conversion/ccm/reader/ccmInterfaceDefinitions.H