OpenFOAM: UOPstream Class Reference
UOPstream Class Reference
#include <UOPstream.H>
Public Member Functions
UOPstream (const UPstream::commsTypes commsType, const int toProcNo, DynamicList< char > &sendBuf, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm, const bool sendAtDestruct=true, IOstreamOption::streamFormat fmt=IOstreamOption::BINARY)
UOPstream (const int toProcNo, PstreamBuffers &buffers)
UOPstream (DynamicList< char > &sendBuf, IOstreamOption::streamFormat fmt=IOstreamOption::BINARY)
virtual ~UOPstream ()
virtual bool write (const token &tok)
virtual Ostream & write (const char c)
virtual Ostream & write (const char *str)
virtual Ostream & write (const word &str)
virtual Ostream & write (const string &str)
virtual Ostream & write (const int32_t val)
virtual Ostream & write (const int64_t val)
virtual Ostream & write (const float val)
virtual Ostream & write (const double val)
virtual Ostream & write (const char *data, std::streamsize count)
Public Member Functions inherited from UOPstreamBase
virtual ~UOPstreamBase ()
virtual ios_base::fmtflags flags () const
virtual Ostream & writeQuoted (const std::string &str, const bool quoted=true)
virtual Ostream & writeRaw (const char *data, std::streamsize count)
virtual bool beginRawWrite (std::streamsize count)
virtual bool endRawWrite ()
virtual void indent ()
virtual void flush ()
virtual void endl ()
virtual char fill () const
virtual char fill (const char)
virtual int width () const
virtual int width (const int)
virtual int precision () const
virtual int precision (const int)
virtual void rewind ()
virtual ios_base::fmtflags flags (const ios_base::fmtflags)
void print (Ostream &os) const
Public Member Functions inherited from UPstream
ClassName ("UPstream")
UPstream (const commsTypes commsType) noexcept
commsTypes commsType () const noexcept
commsTypes commsType (const commsTypes ct) noexcept
template<class T >
Foam::List< T > allGatherValues (const T &localValue, const label comm)
template<class T >
Foam::List< T > listGatherValues (const T &localValue, const label comm)
Public Member Functions inherited from Ostream
Ostream (const Ostream &)=default
virtual ~Ostream ()=default
Ostream (IOstreamOption streamOpt=IOstreamOption())
Ostream (IOstreamOption::streamFormat fmt, IOstreamOption::compressionType cmp=IOstreamOption::UNCOMPRESSED)
virtual Ostream & write (const keyType &kw)
unsigned short indentSize () const noexcept
unsigned short indentSize (unsigned short val) noexcept
unsigned short indentLevel () const noexcept
unsigned short indentLevel (unsigned short val) noexcept
void incrIndent () noexcept
void decrIndent ()
virtual Ostream & writeKeyword (const keyType &kw)
virtual Ostream & beginBlock (const keyType &kw)
virtual Ostream & beginBlock ()
virtual Ostream & endBlock ()
virtual Ostream & endEntry ()
template<class T >
Ostream & writeEntry (const keyType &key, const T &value)
template<class T >
Ostream & writeEntryIfDifferent (const word &key, const T &value1, const T &value2)
Ostream & operator() () const
unsigned short & indentLevel () noexcept
unsigned short & indentSize () noexcept
Public Member Functions inherited from IOstream
IOstream (const IOstream &)=default
virtual ~IOstream ()=default
IOstream (IOstreamOption streamOpt=IOstreamOption())
IOstream (IOstreamOption::streamFormat fmt, IOstreamOption::versionNumber ver, IOstreamOption::compressionType cmp=IOstreamOption::UNCOMPRESSED)
virtual const fileName & name () const
fileName relativeName () const
virtual bool check (const char *operation) const
bool fatalCheck (const char *operation) const
bool opened () const noexcept
bool closed () const noexcept
bool good () const noexcept
bool eof () const noexcept
bool fail () const noexcept
bool bad () const noexcept
operator bool () const noexcept
bool operator! () const noexcept
unsigned labelByteSize () const noexcept
unsigned scalarByteSize () const noexcept
void setLabelByteSize (unsigned nbytes) noexcept
void setScalarByteSize (unsigned nbytes) noexcept
template<class T = label>
std::enable_if< std::is_integral< T >::value, bool >::type checkLabelSize () const noexcept
template<class T = scalar>
std::enable_if< std::is_floating_point< T >::value, bool >::type checkScalarSize () const noexcept
label lineNumber () const noexcept
label & lineNumber () noexcept
label lineNumber (const label num) noexcept
void setEof () noexcept
void setFail () noexcept
void setBad ()
ios_base::fmtflags setf (const ios_base::fmtflags f)
ios_base::fmtflags setf (const ios_base::fmtflags f, const ios_base::fmtflags mask)
void unsetf (const ios_base::fmtflags f)
void print (Ostream &os, const int streamState) const
InfoProxy< IOstream > info () const noexcept
Public Member Functions inherited from IOstreamOption
constexpr IOstreamOption (streamFormat fmt=streamFormat::ASCII, compressionType comp=compressionType::UNCOMPRESSED) noexcept
constexpr IOstreamOption (streamFormat fmt, compressionType comp, versionNumber ver) noexcept
constexpr IOstreamOption (streamFormat fmt, versionNumber ver, compressionType comp=compressionType::UNCOMPRESSED) noexcept
IOstreamOption (const IOstreamOption &opt, streamFormat fmt) noexcept
streamFormat format () const noexcept
streamFormat format (const streamFormat fmt) noexcept
streamFormat format (const word &formatName)
compressionType compression () const noexcept
compressionType compression (const compressionType comp) noexcept
compressionType compression (const word &compName)
versionNumber version () const noexcept
versionNumber version (const versionNumber ver) noexcept
versionNumber version (const token &tok)
Static Public Member Functions
static bool write (const UPstream::commsTypes commsType, const int toProcNo, const char *buf, const std::streamsize bufSize, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm, UPstream::Request *req=nullptr, const UPstream::sendModes sendMode=UPstream::sendModes::normal)
static bool write (UPstream::Request &req, const int toProcNo, const char *buf, const std::streamsize bufSize, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm, const UPstream::sendModes sendMode=UPstream::sendModes::normal)
template<class Type >
static bool write (const UPstream::commsTypes commsType, const int toProcNo, const UList< Type > &buffer, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm, UPstream::Request *req=nullptr, const UPstream::sendModes sendMode=UPstream::sendModes::normal)
template<class Type >
static bool write (UPstream::Request &req, const int toProcNo, const UList< Type > &buffer, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm, const UPstream::sendModes sendMode=UPstream::sendModes::normal)
Static Public Member Functions inherited from UPstream
static constexpr label commGlobal () noexcept
static constexpr label commSelf () noexcept
static label commWorld () noexcept
static label commWorld (const label communicator) noexcept
static label commWarn (const label communicator) noexcept
static label nComms () noexcept
static void printCommTree (const label communicator)
static label commIntraHost ()
static label commInterHost ()
static bool hasHostComms ()
static void clearHostComms ()
static label allocateCommunicator (const label parent, const labelRange &subRanks, const bool withComponents=true)
static label allocateCommunicator (const label parent, const labelUList &subRanks, const bool withComponents=true)
static void freeCommunicator (const label communicator, const bool withComponents=true)
static label allocateInterHostCommunicator (const label parentCommunicator=worldComm)
static label allocateIntraHostCommunicator (const label parentCommunicator=worldComm)
static int baseProcNo (label comm, int procID)
static label procNo (const label comm, const int baseProcID)
static label procNo (const label comm, const label currentComm, const int currentProcID)
static void addValidParOptions (HashTable< string > &validParOptions)
static bool init (int &argc, char **&argv, const bool needsThread)
static bool initNull ()
static void barrier (const label communicator, UPstream::Request *req=nullptr)
static std::pair< int, int > probeMessage (const UPstream::commsTypes commsType, const int fromProcNo, const int tag=UPstream::msgType(), const label communicator=worldComm)
static label nRequests () noexcept
static void resetRequests (const label n)
static void addRequest (UPstream::Request &req)
static void cancelRequest (const label i)
static void cancelRequest (UPstream::Request &req)
static void cancelRequests (UList< UPstream::Request > &requests)
static void freeRequest (UPstream::Request &req)
static void freeRequests (UList< UPstream::Request > &requests)
static void waitRequests (const label pos, label len=-1)
static void waitRequests (UList< UPstream::Request > &requests)
static bool waitAnyRequest (const label pos, label len=-1)
static bool waitSomeRequests (const label pos, DynamicList< int > *indices=nullptr)
static label waitAnyRequest (UList< UPstream::Request > &requests)
static void waitRequest (const label i)
static void waitRequest (UPstream::Request &req)
static bool finishedRequest (const label i)
static bool finishedRequest (UPstream::Request &req)
static bool finishedRequests (const label pos, label len=-1)
static bool finishedRequests (UList< UPstream::Request > &requests)
static bool finishedRequestPair (label &req0, label &req1)
static void waitRequestPair (label &req0, label &req1)
static bool parRun (const bool on) noexcept
static bool & parRun () noexcept
static bool haveThreads () noexcept
static constexpr int masterNo () noexcept
static label nProcs (const label communicator=worldComm)
static int myProcNo (const label communicator=worldComm)
static bool master (const label communicator=worldComm)
static bool is_rank (const label communicator=worldComm)
static bool is_subrank (const label communicator=worldComm)
static bool is_parallel (const label communicator=worldComm)
static label parent (const label communicator)
static List< int > & procID (const label communicator)
static const wordList & allWorlds () noexcept
static const labelList & worldIDs () noexcept
static label myWorldID ()
static const word & myWorld ()
static rangeType allProcs (const label communicator=worldComm)
static rangeType subProcs (const label communicator=worldComm)
static const List< commsStruct > & linearCommunication (const label communicator=worldComm)
static const List< commsStruct > & treeCommunication (const label communicator=worldComm)
static const List< commsStruct > & whichCommunication (const label communicator=worldComm)
static int & msgType () noexcept
static void shutdown (int errNo=0)
static void abort ()
static void exit (int errNo=1)
static void allToAll (const UList< int32_t > &sendData, UList< int32_t > &recvData, const label communicator=worldComm)
static void allToAll (const UList< int64_t > &sendData, UList< int64_t > &recvData, const label communicator=worldComm)
static void allToAllConsensus (const UList< int32_t > &sendData, UList< int32_t > &recvData, const int tag, const label communicator=worldComm)
static void allToAllConsensus (const UList< int64_t > &sendData, UList< int64_t > &recvData, const int tag, const label communicator=worldComm)
static void allToAllConsensus (const Map< int32_t > &sendData, Map< int32_t > &recvData, const int tag, const label communicator=worldComm)
static void allToAllConsensus (const Map< int64_t > &sendData, Map< int64_t > &recvData, const int tag, const label communicator=worldComm)
static void mpiGather (const char *sendData, char *recvData, int count, const label communicator=worldComm)
Receive identically-sized char data from all ranks.
static void mpiScatter (const char *sendData, char *recvData, int count, const label communicator=worldComm)
Send identically-sized char data to all ranks.
static void mpiAllGather (char *allData, int count, const label communicator=worldComm)
Gather/scatter identically-sized char data.
static void gather (const char *sendData, int sendCount, char *recvData, const UList< int > &recvCounts, const UList< int > &recvOffsets, const label communicator=worldComm)
Receive variable length char data from all ranks.
static void scatter (const char *sendData, const UList< int > &sendCounts, const UList< int > &sendOffsets, char *recvData, int recvCount, const label communicator=worldComm)
Send variable length char data to all ranks.
static void gather (const int32_t *sendData, int sendCount, int32_t *recvData, const UList< int > &recvCounts, const UList< int > &recvOffsets, const label communicator=worldComm)
Receive variable length int32_t data from all ranks.
static void scatter (const int32_t *sendData, const UList< int > &sendCounts, const UList< int > &sendOffsets, int32_t *recvData, int recvCount, const label communicator=worldComm)
Send variable length int32_t data to all ranks.
static void gather (const int64_t *sendData, int sendCount, int64_t *recvData, const UList< int > &recvCounts, const UList< int > &recvOffsets, const label communicator=worldComm)
Receive variable length int64_t data from all ranks.
static void scatter (const int64_t *sendData, const UList< int > &sendCounts, const UList< int > &sendOffsets, int64_t *recvData, int recvCount, const label communicator=worldComm)
Send variable length int64_t data to all ranks.
static void gather (const uint32_t *sendData, int sendCount, uint32_t *recvData, const UList< int > &recvCounts, const UList< int > &recvOffsets, const label communicator=worldComm)
Receive variable length uint32_t data from all ranks.
static void scatter (const uint32_t *sendData, const UList< int > &sendCounts, const UList< int > &sendOffsets, uint32_t *recvData, int recvCount, const label communicator=worldComm)
Send variable length uint32_t data to all ranks.
static void gather (const uint64_t *sendData, int sendCount, uint64_t *recvData, const UList< int > &recvCounts, const UList< int > &recvOffsets, const label communicator=worldComm)
Receive variable length uint64_t data from all ranks.
static void scatter (const uint64_t *sendData, const UList< int > &sendCounts, const UList< int > &sendOffsets, uint64_t *recvData, int recvCount, const label communicator=worldComm)
Send variable length uint64_t data to all ranks.
static void gather (const float *sendData, int sendCount, float *recvData, const UList< int > &recvCounts, const UList< int > &recvOffsets, const label communicator=worldComm)
Receive variable length float data from all ranks.
static void scatter (const float *sendData, const UList< int > &sendCounts, const UList< int > &sendOffsets, float *recvData, int recvCount, const label communicator=worldComm)
Send variable length float data to all ranks.
static void gather (const double *sendData, int sendCount, double *recvData, const UList< int > &recvCounts, const UList< int > &recvOffsets, const label communicator=worldComm)
Receive variable length double data from all ranks.
static void scatter (const double *sendData, const UList< int > &sendCounts, const UList< int > &sendOffsets, double *recvData, int recvCount, const label communicator=worldComm)
Send variable length double data to all ranks.
template<class T >
static List< T > allGatherValues (const T &localValue, const label communicator=worldComm)
template<class T >
static List< T > listGatherValues (const T &localValue, const label communicator=worldComm)
template<class T >
static T listScatterValues (const UList< T > &allValues, const label communicator=worldComm)
static bool broadcast (char *buf, const std::streamsize bufSize, const label communicator, const int rootProcNo=masterNo())
static void reduceAnd (bool &value, const label communicator=worldComm)
static void reduceOr (bool &value, const label communicator=worldComm)
static void waitRequests ()
static constexpr int firstSlave () noexcept
static int lastSlave (const label communicator=worldComm)
Static Public Member Functions inherited from IOstream
static unsigned int defaultPrecision () noexcept
static unsigned int defaultPrecision (unsigned int prec) noexcept
Static Public Member Functions inherited from IOstreamOption
static streamFormat formatEnum (const word &formatName, const streamFormat deflt=streamFormat::ASCII)
static streamFormat formatEnum (const word &key, const dictionary &dict, const streamFormat deflt=streamFormat::ASCII)
static compressionType compressionEnum (const word &compName, const compressionType deflt=compressionType::UNCOMPRESSED)
static compressionType compressionEnum (const word &key, const dictionary &dict, const compressionType deflt=compressionType::UNCOMPRESSED)
Additional Inherited Members
Public Types inherited from UPstream
enum class commsTypes : char { blocking , scheduled , nonBlocking }
enum class sendModes : char { normal , sync }
typedef IntRange< int > rangeType
Public Types inherited from IOstream
enum streamAccess : char { CLOSED = 0 , OPENED }
Public Types inherited from IOstreamOption
enum streamFormat : char { ASCII = 0 , BINARY }
enum compressionType : char { UNCOMPRESSED = 0 , COMPRESSED }
enum appendType : char { NON_APPEND = 0 , APPEND }
enum atomicType : char { NON_ATOMIC = 0 , ATOMIC }
Static Public Attributes inherited from UPstream
static const Enum< commsTypes > commsTypeNames
static bool floatTransfer
static int nProcsSimpleSum
static int nProcsNonblockingExchange
static int nPollProcInterfaces
static commsTypes defaultCommsType
static int maxCommsSize
static int tuning_NBX_
static const int mpiBufferSize
static label worldComm
static label warnComm
Static Public Attributes inherited from IOstream
static unsigned int precision_
Static Public Attributes inherited from IOstreamOption
static const Enum< streamFormat > formatNames
static const versionNumber currentVersion
Protected Member Functions inherited from UOPstreamBase
UOPstreamBase (const UPstream::commsTypes commsType, const int toProcNo, DynamicList< char > &sendBuf, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm, const bool sendAtDestruct=true, IOstreamOption::streamFormat fmt=IOstreamOption::BINARY)
UOPstreamBase (const int toProcNo, PstreamBuffers &buffers)
UOPstreamBase (DynamicList< char > &sendBuf, IOstreamOption::streamFormat fmt)
Protected Member Functions inherited from IOstream
void setOpened () noexcept
void setClosed () noexcept
void setState (std::ios_base::iostate state) noexcept
void setGood () noexcept
Protected Attributes inherited from UOPstreamBase
const int toProcNo_
const int tag_
const int comm_
const bool sendAtDestruct_
DynamicList< char > & sendBuf_
Protected Attributes inherited from Ostream
unsigned short indentSize_ = 4
unsigned short indentLevel_ = 0
Protected Attributes inherited from IOstream
std::ios_base::iostate ioState_
streamAccess openClosed_
unsigned char sizeofLabel_
unsigned char sizeofScalar_
label lineNumber_
Static Protected Attributes inherited from Ostream
static constexpr const unsigned short entryIndentation_ = 16
Static Protected Attributes inherited from IOstream
static fileName staticName_
Detailed Description
Definition at line 290 of file UOPstream.H.
Constructor & Destructor Documentation
UOPstream() [1/3]
UOPstream (const UPstream::commsTypes commsType, const int toProcNo, DynamicList< char > & sendBuf, const int tag = UPstream::msgType(), const label comm = UPstream::worldComm, const bool sendAtDestruct = true, IOstreamOption::streamFormat fmt = IOstreamOption::BINARY)
Definition at line 27 of file OPstreams.C.
UOPstream() [2/3]
UOPstream (const int toProcNo, PstreamBuffers & buffers)
Definition at line 42 of file OPstreams.C.
UOPstream() [3/3]
UOPstream (DynamicList< char > & sendBuf, IOstreamOption::streamFormat fmt = IOstreamOption::BINARY) explicit
Definition at line 48 of file OPstreams.C.
~UOPstream()
~UOPstream () virtual
Definition at line 84 of file OPstreams.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and UPtrList< T >::size().
Member Function Documentation
write() [1/14]
bool write (const UPstream::commsTypes commsType, const int toProcNo, const char * buf, const std::streamsize bufSize, const int tag = UPstream::msgType(), const label comm = UPstream::worldComm, UPstream::Request * req = nullptr, const UPstream::sendModes sendMode = UPstream::sendModes::normal) static
Parameters
[out] req request information (for non-blocking)
Definition at line 35 of file UOPstreamWrite.C.
References NotImplemented.
Referenced by Pstream::combineGather(), Pstream::combineScatter(), processorLduInterface::compressedSend(), metisLikeDecomp::decomposeGeneral(), mapDistributeBase::distribute(), mapDistributeBase::distribute(), Foam::PstreamDetail::exchangeBuf(), Foam::PstreamDetail::exchangeConsensus(), Foam::PstreamDetail::exchangeConsensus(), Foam::PstreamDetail::exchangeContainer(), Foam::PstreamDetail::exchangeContainer(), mapDistributeBase::exchangeMasks(), Pstream::exchangeSizes(), globalIndex::gather(), Pstream::gather(), Pstream::gatherList(), globalIndex::gatherValues(), processorFaPatchField< Type >::initEvaluate(), calculatedProcessorFvPatchField< Type >::initEvaluate(), processorFvPatchField< Type >::initEvaluate(), processorFaPatchField< Type >::initInterfaceMatrixUpdate(), processorFvPatchField< Type >::initInterfaceMatrixUpdate(), processorFaPatchField< Type >::initInterfaceMatrixUpdate(), calculatedProcessorFvPatchField< Type >::initInterfaceMatrixUpdate(), processorFvPatchField< Type >::initInterfaceMatrixUpdate(), lduCalculatedProcessorField< Type >::initInterfaceMatrixUpdate(), processorGAMGInterfaceField::initInterfaceMatrixUpdate(), calculatedProcessorGAMGInterfaceField::initInterfaceMatrixUpdate(), processorCyclicPointPatchField< Type >::initSwapAddSeparated(), Pstream::listCombineGather(), Pstream::listCombineScatter(), globalIndex::scatter(), Pstream::scatter(), Pstream::scatterList(), distributedDILUPreconditioner::send(), mapDistributeBase::send(), processorLduInterface::send(), LUscalarMatrix::solve(), syncTools::syncBoundaryFaceList(), syncTools::syncFaceList(), UOPstream::write(), OFstreamCollator::write(), UOPstream::write(), UOPstream::write(), and decomposedBlockData::writeBlocks().
write() [2/14]
static bool write (UPstream::Request & req, const int toProcNo, const char * buf, const std::streamsize bufSize, const int tag = UPstream::msgType(), const label comm = UPstream::worldComm, const UPstream::sendModes sendMode = UPstream::sendModes::normal) inline static
Parameters
[out] req request information
Definition at line 359 of file UOPstream.H.
References UPstream::nonBlocking, and UOPstream::write().
write() [3/14]
template<class Type > static bool write (const UPstream::commsTypes commsType, const int toProcNo, const UList< Type > & buffer, const int tag = UPstream::msgType(), const label comm = UPstream::worldComm, UPstream::Request * req = nullptr, const UPstream::sendModes sendMode = UPstream::sendModes::normal) inline static
Parameters
[out] req request information (for non-blocking)
Definition at line 388 of file UOPstream.H.
References UPstream::commsType(), and UOPstream::write().
write() [4/14]
template<class Type > static bool write (UPstream::Request & req, const int toProcNo, const UList< Type > & buffer, const int tag = UPstream::msgType(), const label comm = UPstream::worldComm, const UPstream::sendModes sendMode = UPstream::sendModes::normal) inline static
Parameters
[out] req request information
Definition at line 417 of file UOPstream.H.
References UPstream::nonBlocking, and UOPstream::write().
write() [5/14]
bool write (const token & tok) virtual
Reimplemented from UOPstreamBase.
Definition at line 153 of file UOPstreamBase.C.
write() [6/14]
Foam::Ostream & write (const char c) virtual
Reimplemented from UOPstreamBase.
Definition at line 156 of file UOPstreamBase.C.
write() [7/14]
Foam::Ostream & write (const char * str) virtual
Reimplemented from UOPstreamBase.
Definition at line 160 of file UOPstreamBase.C.
write() [8/14]
Foam::Ostream & write (const word & str) virtual
Reimplemented from UOPstreamBase.
Definition at line 163 of file UOPstreamBase.C.
write() [9/14]
Foam::Ostream & write (const string & str) virtual
Reimplemented from UOPstreamBase.
Definition at line 166 of file UOPstreamBase.C.
write() [10/14]
Foam::Ostream & write (const int32_t val) virtual
Reimplemented from UOPstreamBase.
Definition at line 177 of file UOPstreamBase.C.
write() [11/14]
Foam::Ostream & write (const int64_t val) virtual
Reimplemented from UOPstreamBase.
Definition at line 180 of file UOPstreamBase.C.
write() [12/14]
Foam::Ostream & write (const float val) virtual
Reimplemented from UOPstreamBase.
Definition at line 183 of file UOPstreamBase.C.
write() [13/14]
Foam::Ostream & write (const double val) virtual
Reimplemented from UOPstreamBase.
Definition at line 186 of file UOPstreamBase.C.
write() [14/14]
Foam::Ostream & write (const char * data, std::streamsize count) virtual
Reimplemented from UOPstreamBase.
Definition at line 189 of file UOPstreamBase.C.
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOstreams/Pstreams/UOPstream.H
src/OpenFOAM/db/IOstreams/Pstreams/OPstreams.C
src/Pstream/dummy/UOPstreamWrite.C
src/Pstream/mpi/UOPstreamWrite.C