OpenFOAM: Jeschar Class Reference
Jeschar Class Reference
#include <Jeschar.H>
Public Member Functions
TypeName ("Jeschar")
Jeschar (const dictionary &dict)
virtual ~Jeschar ()=default
virtual tmp< scalarField > MHF (const phaseModel &liquid, const phaseModel &vapor, const label patchi, const scalarField &Tl, const scalarField &Tsatw, const scalarField &L) const
virtual void write (Ostream &os) const
Public Member Functions inherited from MHFModel
TypeName ("MHFModel")
declareRunTimeSelectionTable (autoPtr, MHFModel, dictionary,(const dictionary &dict),(dict))
MHFModel ()=default
virtual ~MHFModel ()=default
Additional Inherited Members
Static Public Member Functions inherited from MHFModel
static autoPtr< MHFModel > New (const dictionary &dict)
Detailed Description
Definition at line 99 of file Jeschar.H.
Constructor & Destructor Documentation
Jeschar()
Jeschar (const dictionary & dict)
Definition at line 49 of file Jeschar.C.
~Jeschar()
virtual ~Jeschar () virtual default
Member Function Documentation
TypeName()
TypeName ("Jeschar")
MHF()
Foam::tmp< Foam::scalarField > MHF (const phaseModel & liquid, const phaseModel & vapor, const label patchi, const scalarField & Tl, const scalarField & Tsatw, const scalarField & L) const virtual
Implements MHFModel.
Definition at line 62 of file Jeschar.C.
References cells, g, L, Foam::mag(), Foam::pow(), liquid::sigma(), and Foam::sqrt().
write()
void write (Ostream & os) const virtual
Reimplemented from MHFModel.
Definition at line 103 of file Jeschar.C.
References os(), and MHFModel::write().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/wallBoilingSubModels/MHFModels/Jeschar/Jeschar.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/wallBoilingSubModels/MHFModels/Jeschar/Jeschar.C