OpenFOAM: fvMeshSubsetter Class Reference
fvMeshSubsetter Class Reference
Extends Foam::fvMeshSubset with two-step subsetting (uses polyTopoChange modification).
#include <fvMeshSubsetter.H>
Public Member Functions
labelList getExposedFaces (const bitSet &selectedCells, const bool syncPar=true) const
labelList getExposedFaces (const label regioni, const labelUList &regions, const bool syncPar=true) const
void setCellSubset (const bitSet &selectedCells, const labelList &exposedFaces, const labelList &patchIDs, const bool syncPar=true)
void setCellSubset (const label regioni, const labelList &regions, const labelList &exposedFaces, const labelList &patchIDs, const bool syncPar=true)
fvMeshSubset (const fvMeshSubset &)=delete
fvMeshSubset (const fvMesh &baseMesh)
fvMeshSubset (const fvMesh &baseMesh, const Foam::zero)
fvMeshSubset (const fvMesh &baseMesh, const bitSet &selectedCells, const label patchID=-1, const bool syncPar=true)
fvMeshSubset (const fvMesh &baseMesh, const labelUList &selectedCells, const label patchID=-1, const bool syncPar=true)
fvMeshSubset (const fvMesh &baseMesh, const labelHashSet &selectedCells, const label patchID=-1, const bool syncPar=true)
fvMeshSubset (const fvMesh &baseMesh, const label regioni, const labelUList &regions, const label patchID=-1, const bool syncPar=true)
void setCellSubset (const bitSet &selectedCells, const label patchID=-1, const bool syncPar=true)
void setCellSubset (const labelUList &selectedCells, const label patchID=-1, const bool syncPar=true)
void setCellSubset (const labelHashSet &selectedCells, const label patchID=-1, const bool syncPar=true)
void setCellSubset (const label regioni, const labelUList &regions, const label patchID=-1, const bool syncPar=true)
Public Member Functions inherited from fvMeshSubset
fvMeshSubset (const fvMesh &baseMesh)
fvMeshSubset (const fvMesh &baseMesh, const Foam::zero)
fvMeshSubset (const fvMesh &baseMesh, const bitSet &selectedCells, const label patchID=-1, const bool syncPar=true)
fvMeshSubset (const fvMesh &baseMesh, const labelUList &selectedCells, const label patchID=-1, const bool syncPar=true)
fvMeshSubset (const fvMesh &baseMesh, const labelHashSet &selectedCells, const label patchID=-1, const bool syncPar=true)
fvMeshSubset (const fvMesh &baseMesh, const label regioni, const labelUList &regions, const label patchID=-1, const bool syncPar=true)
const fvMesh & baseMesh () const noexcept
const fvMesh & mesh () const noexcept
bool hasSubMesh () const noexcept
const fvMesh & subMesh () const
fvMesh & subMesh ()
const labelList & pointMap () const
const labelList & faceMap () const
const labelList & faceFlipMap () const
const labelList & cellMap () const
const labelList & patchMap () const
void clear ()
void reset ()
void reset (const Foam::zero)
void reset (autoPtr< fvMesh > &&subMeshPtr, labelList &&pointMap, labelList &&faceMap, labelList &&cellMap, labelList &&patchMap)
void reset (const bitSet &selectedCells, const label patchID=-1, const bool syncPar=true)
void reset (const labelUList &selectedCells, const label patchID=-1, const bool syncPar=true)
void reset (const labelHashSet &selectedCells, const label patchID=-1, const bool syncPar=true)
void reset (const label regioni, const labelUList &regions, const label patchID=-1, const bool syncCouples=true)
void setCellSubset (const bitSet &selectedCells, const label patchID=-1, const bool syncPar=true)
void setCellSubset (const labelUList &selectedCells, const label patchID=-1, const bool syncPar=true)
void setCellSubset (const labelHashSet &selectedCells, const label patchID=-1, const bool syncPar=true)
void setCellSubset (const label regioni, const labelUList &regions, const label patchID=-1, const bool syncPar=true)
template<class Type >
tmp< DimensionedField< Type, volMesh > > interpolate (const DimensionedField< Type, volMesh > &, const bool allowUnmapped=false) const
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const bool allowUnmapped=false) const
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvsPatchField, surfaceMesh > &, const bool allowUnmapped=false) const
template<class Type >
tmp< GeometricField< Type, pointPatchField, pointMesh > > interpolate (const GeometricField< Type, pointPatchField, pointMesh > &, const bool allowUnmapped=false) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &vf, const fvMesh &sMesh, const labelUList &patchMap, const labelUList &cellMap, const labelUList &faceMap, const bool allowUnmapped)
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &vf, const bool allowUnmapped) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > interpolate (const GeometricField< Type, fvsPatchField, surfaceMesh > &vf, const fvMesh &sMesh, const labelUList &patchMap, const labelUList &cellMap, const labelUList &faceMap)
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > interpolate (const GeometricField< Type, fvsPatchField, surfaceMesh > &sf, const bool allowUnmapped) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::pointPatchField, Foam::pointMesh > > interpolate (const GeometricField< Type, pointPatchField, pointMesh > &vf, const pointMesh &sMesh, const labelUList &patchMap, const labelUList &pointMap)
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::pointPatchField, Foam::pointMesh > > interpolate (const GeometricField< Type, pointPatchField, pointMesh > &sf, const bool allowUnmapped) const
template<class Type >
Foam::tmp< Foam::DimensionedField< Type, Foam::volMesh > > interpolate (const DimensionedField< Type, volMesh > &df, const fvMesh &sMesh, const labelUList &cellMap)
template<class Type >
Foam::tmp< Foam::DimensionedField< Type, Foam::volMesh > > interpolate (const DimensionedField< Type, volMesh > &df, const bool allowUnmapped) const
Additional Inherited Members
Static Public Member Functions inherited from fvMeshSubset
template<class Type >
static tmp< DimensionedField< Type, volMesh > > interpolate (const DimensionedField< Type, volMesh > &, const fvMesh &sMesh, const labelUList &cellMap)
template<class Type >
static tmp< GeometricField< Type, fvPatchField, volMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const fvMesh &sMesh, const labelUList &patchMap, const labelUList &cellMap, const labelUList &faceMap, const bool allowUnmapped=false)
template<class Type >
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvsPatchField, surfaceMesh > &, const fvMesh &sMesh, const labelUList &patchMap, const labelUList &cellMap, const labelUList &faceMap)
template<class Type >
static tmp< GeometricField< Type, pointPatchField, pointMesh > > interpolate (const GeometricField< Type, pointPatchField, pointMesh > &, const pointMesh &sMesh, const labelUList &patchMap, const labelUList &pointMap)
Static Public Attributes inherited from fvMeshSubset
static word exposedPatchName
Protected Member Functions inherited from fvMeshSubset
bool checkHasSubMesh () const
fvMeshSubset (const fvMeshSubset &)=delete
void operator= (const fvMeshSubset &)=delete
Detailed Description
Extends Foam::fvMeshSubset with two-step subsetting (uses polyTopoChange modification).
Source files
fvMeshSubsetter.H
fvMeshSubsetter.C
Definition at line 48 of file fvMeshSubsetter.H.
Member Function Documentation
getExposedFaces() [1/2]
Foam::labelList getExposedFaces (const bitSet & selectedCells, const bool syncPar = true) const
Definition at line 128 of file fvMeshSubsetter.C.
References removeCells::getExposedFaces(), and Foam::invertCellSelection().
getExposedFaces() [2/2]
Foam::labelList getExposedFaces (const label regioni, const labelUList & regions, const bool syncPar = true) const
Definition at line 142 of file fvMeshSubsetter.C.
References removeCells::getExposedFaces(), and Foam::invertCellSelection().
setCellSubset() [1/6]
void setCellSubset (const bitSet & selectedCells, const labelList & exposedFaces, const labelList & patchIDs, const bool syncPar = true)
Definition at line 157 of file fvMeshSubsetter.C.
References Foam::invertCellSelection(), and patchIDs().
setCellSubset() [2/6]
void setCellSubset (const label regioni, const labelList & regions, const labelList & exposedFaces, const labelList & patchIDs, const bool syncPar = true)
Definition at line 175 of file fvMeshSubsetter.C.
References Foam::invertCellSelection(), and patchIDs().
fvMeshSubset() [1/7]
fvMeshSubset (const fvMeshSubset &) delete
fvMeshSubset() [2/7]
fvMeshSubset (const fvMesh & baseMesh) explicit
Definition at line 142 of file fvMeshSubset.C.
fvMeshSubset() [3/7]
fvMeshSubset (const fvMesh & baseMesh, const Foam::zero)
Definition at line 145 of file fvMeshSubset.C.
fvMeshSubset() [4/7]
fvMeshSubset (const fvMesh & baseMesh, const bitSet & selectedCells, const label patchID = -1, const bool syncPar = true)
Definition at line 149 of file fvMeshSubset.C.
fvMeshSubset() [5/7]
fvMeshSubset (const fvMesh & baseMesh, const labelUList & selectedCells, const label patchID = -1, const bool syncPar = true)
Definition at line 159 of file fvMeshSubset.C.
References UPstream::parRun().
fvMeshSubset() [6/7]
fvMeshSubset (const fvMesh & baseMesh, const labelHashSet & selectedCells, const label patchID = -1, const bool syncPar = true)
Definition at line 169 of file fvMeshSubset.C.
References UPtrList< T >::empty(), UPstream::nonBlocking, and pp().
fvMeshSubset() [7/7]
fvMeshSubset (const fvMesh & baseMesh, const label regioni, const labelUList & regions, const label patchID = -1, const bool syncPar = true)
Definition at line 179 of file fvMeshSubset.C.
References pp().
setCellSubset() [3/6]
void setCellSubset (const bitSet & selectedCells, const label patchID = -1, const bool syncPar = true) inline
Definition at line 290 of file fvMeshSubset.H.
setCellSubset() [4/6]
void setCellSubset (const labelUList & selectedCells, const label patchID = -1, const bool syncPar = true) inline
Definition at line 301 of file fvMeshSubset.H.
setCellSubset() [5/6]
void setCellSubset (const labelHashSet & selectedCells, const label patchID = -1, const bool syncPar = true) inline
Definition at line 312 of file fvMeshSubset.H.
setCellSubset() [6/6]
void setCellSubset (const label regioni, const labelUList & regions, const label patchID = -1, const bool syncPar = true) inline
Definition at line 323 of file fvMeshSubset.H.
The documentation for this class was generated from the following files:
src/dynamicMesh/fvMeshSubset/fvMeshSubsetter.H
src/dynamicMesh/fvMeshSubset/fvMeshSubsetter.C