OpenFOAM: steadyStateDdtScheme< Type > Class Template Reference
steadyStateDdtScheme< Type > Class Template Reference
Numerics » Finite volume numerical schemes » Time schemes
SteadyState implicit/explicit ddt which returns 0.
#include <steadyStateDdtScheme.H>
Public Types
typedef ddtScheme< Type >::fluxFieldType fluxFieldType
Public Types inherited from ddtScheme< Type >
typedef GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > fluxFieldType
Public Member Functions
TypeName ("steadyState")
steadyStateDdtScheme (const fvMesh &mesh)
steadyStateDdtScheme (const fvMesh &mesh, Istream &is)
const fvMesh & mesh () const
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const dimensioned< Type > &)
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const GeometricField< Type, fvPatchField, volMesh > &)
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const dimensionedScalar &, const GeometricField< Type, fvPatchField, volMesh > &)
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const volScalarField &, const GeometricField< Type, fvPatchField, volMesh > &)
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const volScalarField &alpha, const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &psi)
tmp< fvMatrix< Type > > fvmDdt (const GeometricField< Type, fvPatchField, volMesh > &)
tmp< fvMatrix< Type > > fvmDdt (const dimensionedScalar &, const GeometricField< Type, fvPatchField, volMesh > &)
tmp< fvMatrix< Type > > fvmDdt (const volScalarField &, const GeometricField< Type, fvPatchField, volMesh > &)
tmp< fvMatrix< Type > > fvmDdt (const volScalarField &alpha, const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &psi)
tmp< fluxFieldType > fvcDdtUfCorr (const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< Type, fvsPatchField, surfaceMesh > &Uf)
tmp< fluxFieldType > fvcDdtPhiCorr (const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi)
tmp< fluxFieldType > fvcDdtUfCorr (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< Type, fvsPatchField, surfaceMesh > &Uf)
tmp< fluxFieldType > fvcDdtPhiCorr (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi)
tmp< surfaceScalarField > meshPhi (const GeometricField< Type, fvPatchField, volMesh > &)
tmp< surfaceScalarField > fvcDdtUfCorr (const GeometricField< scalar, fvPatchField, volMesh > &U, const GeometricField< scalar, fvsPatchField, surfaceMesh > &Uf)
tmp< surfaceScalarField > fvcDdtPhiCorr (const volScalarField &U, const surfaceScalarField &phi)
tmp< surfaceScalarField > fvcDdtUfCorr (const volScalarField &rho, const volScalarField &U, const surfaceScalarField &Uf)
tmp< surfaceScalarField > fvcDdtPhiCorr (const volScalarField &rho, const volScalarField &U, const surfaceScalarField &phi)
Public Member Functions inherited from ddtScheme< Type >
virtual const word & type () const =0
declareRunTimeSelectionTable (tmp, ddtScheme, Istream,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
ddtScheme (const fvMesh &mesh)
ddtScheme (const fvMesh &mesh, Istream &is)
virtual ~ddtScheme ()=default
const fvMesh & mesh () const
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > fvcDdt (const GeometricField< Type, fvsPatchField, surfaceMesh > &)
tmp< surfaceScalarField > fvcDdtPhiCoeff (const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi, const fluxFieldType &phiCorr)
tmp< surfaceScalarField > fvcDdtPhiCoeffExperimental (const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi, const fluxFieldType &phiCorr)
tmp< surfaceScalarField > fvcDdtPhiCoeff (const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi, const fluxFieldType &phiCorr, const volScalarField &rho)
tmp< surfaceScalarField > fvcDdtPhiCoeff (const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi)
tmp< surfaceScalarField > fvcDdtPhiCoeff (const GeometricField< Type, fvPatchField, volMesh > &rhoU, const fluxFieldType &phi, const volScalarField &rho)
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Public Member Functions inherited from ddtSchemeBase
ddtSchemeBase ()
ddtSchemeBase ()
Additional Inherited Members
Static Public Member Functions inherited from ddtScheme< Type >
static tmp< ddtScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Static Public Attributes inherited from ddtSchemeBase
static bool experimentalDdtCorr
Protected Member Functions inherited from ddtScheme< Type >
ddtScheme (const ddtScheme &)=delete
void operator= (const ddtScheme &)=delete
Protected Attributes inherited from ddtScheme< Type >
const fvMesh & mesh_
scalar ddtPhiCoeff_
Detailed Description
template<class Type>
class Foam::fv::steadyStateDdtScheme< Type >
SteadyState implicit/explicit ddt which returns 0.
Source files
steadyStateDdtScheme.H
steadyStateDdtScheme.C
Definition at line 55 of file steadyStateDdtScheme.H.
Member Typedef Documentation
fluxFieldType
template<class Type > typedef ddtScheme<Type>::fluxFieldType fluxFieldType
Definition at line 150 of file steadyStateDdtScheme.H.
Constructor & Destructor Documentation
steadyStateDdtScheme() [1/2]
template<class Type > steadyStateDdtScheme (const fvMesh & mesh) inline
Definition at line 77 of file steadyStateDdtScheme.H.
steadyStateDdtScheme() [2/2]
template<class Type > steadyStateDdtScheme (const fvMesh & mesh, Istream & is) inline
Definition at line 83 of file steadyStateDdtScheme.H.
Member Function Documentation
TypeName()
template<class Type > TypeName ("steadyState")
mesh()
template<class Type > const fvMesh & mesh () const inline
Definition at line 92 of file steadyStateDdtScheme.H.
References ddtScheme< Type >::mesh().
fvcDdt() [1/5]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const dimensioned< Type > & dt) virtual
Implements ddtScheme< Type >.
Definition at line 40 of file steadyStateDdtScheme.C.
References Foam::dimTime, mesh, Foam::New(), timeName, and Foam::Zero.
fvcDdt() [2/5]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 61 of file steadyStateDdtScheme.C.
References Foam::dimTime, mesh, Foam::New(), timeName, and Foam::Zero.
fvcDdt() [3/5]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const dimensionedScalar & rho, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 82 of file steadyStateDdtScheme.C.
References Foam::dimTime, mesh, Foam::New(), rho, timeName, and Foam::Zero.
fvcDdt() [4/5]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 104 of file steadyStateDdtScheme.C.
References Foam::dimTime, mesh, Foam::New(), rho, timeName, and Foam::Zero.
fvcDdt() [5/5]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const volScalarField & alpha, const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & psi) virtual
Implements ddtScheme< Type >.
Definition at line 126 of file steadyStateDdtScheme.C.
References alpha, Foam::dimTime, mesh, Foam::New(), rho, timeName, and Foam::Zero.
fvmDdt() [1/4]
template<class Type > tmp< fvMatrix< Type > > fvmDdt (const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 149 of file steadyStateDdtScheme.C.
References Foam::dimTime, and Foam::dimVol.
fvmDdt() [2/4]
template<class Type > tmp< fvMatrix< Type > > fvmDdt (const dimensionedScalar & rho, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 169 of file steadyStateDdtScheme.C.
References Foam::dimTime, Foam::dimVol, and rho.
fvmDdt() [3/4]
template<class Type > tmp< fvMatrix< Type > > fvmDdt (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 190 of file steadyStateDdtScheme.C.
References Foam::dimTime, Foam::dimVol, and rho.
fvmDdt() [4/4]
template<class Type > tmp< fvMatrix< Type > > fvmDdt (const volScalarField & alpha, const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & psi) virtual
Implements ddtScheme< Type >.
Definition at line 211 of file steadyStateDdtScheme.C.
References alpha, Foam::dimTime, Foam::dimVol, and rho.
fvcDdtUfCorr() [1/4]
template<class Type > tmp< typename steadyStateDdtScheme< Type >::fluxFieldType > fvcDdtUfCorr (const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< Type, fvsPatchField, surfaceMesh > & Uf) virtual
Implements ddtScheme< Type >.
Definition at line 233 of file steadyStateDdtScheme.C.
References Foam::dimArea, Foam::dimTime, mesh, timeName, U, Uf, and Foam::Zero.
fvcDdtPhiCorr() [1/4]
template<class Type > tmp< typename steadyStateDdtScheme< Type >::fluxFieldType > fvcDdtPhiCorr (const GeometricField< Type, fvPatchField, volMesh > & U, const fluxFieldType & phi) virtual
Implements ddtScheme< Type >.
Definition at line 265 of file steadyStateDdtScheme.C.
References Foam::dimTime, mesh, phi, timeName, U, and Foam::Zero.
fvcDdtUfCorr() [2/4]
template<class Type > tmp< typename steadyStateDdtScheme< Type >::fluxFieldType > fvcDdtUfCorr (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< Type, fvsPatchField, surfaceMesh > & Uf) virtual
Implements ddtScheme< Type >.
Definition at line 297 of file steadyStateDdtScheme.C.
References Foam::dimArea, Foam::dimTime, mesh, rho, timeName, U, Uf, and Foam::Zero.
fvcDdtPhiCorr() [2/4]
template<class Type > tmp< typename steadyStateDdtScheme< Type >::fluxFieldType > fvcDdtPhiCorr (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & U, const fluxFieldType & phi) virtual
Implements ddtScheme< Type >.
Definition at line 332 of file steadyStateDdtScheme.C.
References Foam::dimTime, mesh, phi, rho, timeName, U, and Foam::Zero.
meshPhi()
template<class Type > tmp< surfaceScalarField > meshPhi (const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 366 of file steadyStateDdtScheme.C.
References Foam::dimTime, Foam::dimVolume, mesh, IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, timeName, and Foam::Zero.
fvcDdtUfCorr() [3/4]
tmp< surfaceScalarField > fvcDdtUfCorr (const GeometricField< scalar, fvPatchField, volMesh > & U, const GeometricField< scalar, fvsPatchField, surfaceMesh > & Uf)
fvcDdtPhiCorr() [3/4]
tmp< surfaceScalarField > fvcDdtPhiCorr (const volScalarField & U, const surfaceScalarField & phi)
fvcDdtUfCorr() [4/4]
tmp< surfaceScalarField > fvcDdtUfCorr (const volScalarField & rho, const volScalarField & U, const surfaceScalarField & Uf)
fvcDdtPhiCorr() [4/4]
tmp< surfaceScalarField > fvcDdtPhiCorr (const volScalarField & rho, const volScalarField & U, const surfaceScalarField & phi)
The documentation for this class was generated from the following files:
src/finiteVolume/finiteVolume/ddtSchemes/steadyStateDdtScheme/steadyStateDdtScheme.H
src/finiteVolume/finiteVolume/ddtSchemes/steadyStateDdtScheme/steadyStateDdtScheme.C