OpenFOAM: zoneDistribute Class Reference
zoneDistribute Class Reference
Class for parallel communication in a narrow band. It either provides a Map with the neighbouring values of the selected region or returns a Map of the required values in global addressing. Also holds a reference to the stencil Before the data transfer the communication has to be set up: exchangeFields_.setUpCommforZone(interfaceCell_); Is used in the plicRDF.
#include <zoneDistribute.H>
Public Member Functions
TypeName ("zoneDistribute")
zoneDistribute (const fvMesh &)
virtual ~zoneDistribute ()=default
void setUpCommforZone (const boolList &zone, bool updateStencil=true)
void updateStencil (const boolList &zone)
const labelListList & getStencil () noexcept
const globalIndex & globalNumbering () const noexcept
template<typename Type >
Type getValue (const VolumeField< Type > &phi, const Map< Type > &valuesFromOtherProc, const label gblIdx) const
template<typename Type >
Map< Field< Type > > getFields (const boolList &zone, const VolumeField< Type > &phi)
template<typename Type >
Map< Type > getDatafromOtherProc (const boolList &zone, const VolumeField< Type > &phi)
template<typename Type >
Foam::Map< Foam::Field< Type > > getFields (const boolList &zone, const VolumeField< Type > &phi)
template<typename Type >
Foam::Map< Type > getDatafromOtherProc (const boolList &zone, const VolumeField< Type > &phi)
Public Member Functions inherited from MeshObject< fvMesh, TopologicalMeshObject, zoneDistribute >
MeshObject (const fvMesh &mesh)
MeshObject (const word &objName, const fvMesh &mesh)
virtual ~MeshObject ()=default
const fvMesh & mesh () const noexcept
virtual bool writeData (Ostream &os) const
Static Public Member Functions
static zoneDistribute & New (const fvMesh &)
Static Public Member Functions inherited from MeshObject< fvMesh, TopologicalMeshObject, zoneDistribute >
static const zoneDistribute & New (const fvMesh &mesh, Args &&... args)
static const zoneDistribute & New (const word &objName, const fvMesh &mesh, Args &&... args)
static bool Delete (const word &objName, const fvMesh &mesh)
static bool Delete (const fvMesh &mesh)
Additional Inherited Members
Protected Attributes inherited from MeshObject< fvMesh, TopologicalMeshObject, zoneDistribute >
const fvMesh & mesh_
Detailed Description
Class for parallel communication in a narrow band. It either provides a Map with the neighbouring values of the selected region or returns a Map of the required values in global addressing. Also holds a reference to the stencil Before the data transfer the communication has to be set up: exchangeFields_.setUpCommforZone(interfaceCell_); Is used in the plicRDF.
Original code supplied by Henning Scheufler, DLR (2019)
Additional optimization of processor communication provided by Tetsuo AOYAGI, RIST (2022), to use a more compact exchange of sizes with an updated version of PstreamBuffers. This optimization uses additional sendTo/recvFrom member data to track the topological connectivity, acting like an on-the-fly sub-communicator, and respects corner connectivity.
Initially topological connections are empty (or all false).
Scan the stencil global cellIds (active zones only) and split into sub-lists according the originating processor (the sender).
If an originating processor appears/disappears, need to update the connectivity information (requires an all-to-all).
When possible, the topological send/recv is used in PstreamBuffers finishedSends (minimizes communication).
Source files
zoneDistribute.H
zoneDistributeI.H
zoneDistribute.C
Definition at line 76 of file zoneDistribute.H.
Constructor & Destructor Documentation
zoneDistribute()
zoneDistribute (const fvMesh & mesh) explicit
Definition at line 34 of file zoneDistribute.C.
References PstreamBuffers::allowClearRecv(), and Foam::New().
~zoneDistribute()
virtual ~zoneDistribute () virtual default
Member Function Documentation
TypeName()
TypeName ("zoneDistribute")
New()
Foam::zoneDistribute & New (const fvMesh & mesh) static
Definition at line 49 of file zoneDistribute.C.
References mesh, regIOobject::store(), and fvMesh::thisDb().
Referenced by plicRDF::reconstruct().
setUpCommforZone()
void setUpCommforZone (const boolList & zone, bool updateStencil = true)
Definition at line 71 of file zoneDistribute.C.
References PtrList< T >::clear(), UPtrList< T >::empty(), UPstream::myProcNo(), zoneCellStencils::needsComm(), zoneCPCStencil::New(), UPstream::nProcs(), UPstream::parRun(), and zoneCellStencils::updateStencil().
Referenced by reconstructedDistanceFunction::constructRDF().
updateStencil()
void updateStencil (const boolList & zone)
Definition at line 65 of file zoneDistribute.C.
References zoneCPCStencil::New().
getStencil()
const labelListList & getStencil () inline noexcept
Definition at line 152 of file zoneDistribute.H.
Referenced by reconstructedDistanceFunction::constructRDF().
globalNumbering()
const globalIndex & globalNumbering () const inline noexcept
Definition at line 158 of file zoneDistribute.H.
getValue()
template<typename Type > Type getValue (const VolumeField< Type > & phi, const Map< Type > & valuesFromOtherProc, const label gblIdx) const
Definition at line 72 of file zoneDistributeI.H.
References phi.
Referenced by reconstructedDistanceFunction::constructRDF().
getFields() [1/2]
template<typename Type > Map< Field< Type > > getFields (const boolList & zone, const VolumeField< Type > & phi)
getDatafromOtherProc() [1/2]
template<typename Type > Map< Type > getDatafromOtherProc (const boolList & zone, const VolumeField< Type > & phi)
Referenced by reconstructedDistanceFunction::constructRDF().
getFields() [2/2]
template<typename Type > Foam::Map< Foam::Field< Type > > getFields (const boolList & zone, const VolumeField< Type > & phi)
Definition at line 93 of file zoneDistributeI.H.
References PtrList< T >::append(), PtrList< T >::clear(), PtrList< T >::emplace(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, phi, UPtrList< T >::size(), and UList< T >::size().
getDatafromOtherProc() [2/2]
template<typename Type > Foam::Map< Type > getDatafromOtherProc (const boolList & zone, const VolumeField< Type > & phi)
Definition at line 136 of file zoneDistributeI.H.
References UPtrList< T >::empty(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, UPstream::myProcNo(), UPstream::parRun(), phi, UPtrList< T >::size(), UList< T >::size(), and WarningInFunction.
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/zoneDistribute/zoneDistribute.H
src/finiteVolume/fvMesh/zoneDistribute/zoneDistribute.C
src/finiteVolume/fvMesh/zoneDistribute/zoneDistributeI.H