OpenFOAM: Pxyz Class Reference
Pxyz Class Reference
Mesh motion » Rigid body dynamics » Joints
Prismatic joint for translation in the x/y/z directions.
#include <Pxyz.H>
Public Member Functions
TypeName ("Pxyz")
Pxyz ()
Pxyz (const dictionary &dict)
virtual autoPtr< joint > clone () const
virtual ~Pxyz ()
virtual void jcalc (joint::XSvc &J, const scalarField &q, const scalarField &qDot) const
Public Member Functions inherited from joint
TypeName ("joint")
declareRunTimeSelectionTable (autoPtr, joint, dictionary,(const dictionary &dict),(dict))
joint (const label nDoF)
virtual ~joint ()
label nDoF () const
virtual bool unitQuaternion () const
label index () const
label qIndex () const
const List< spatialVector > & S () const
virtual void write (Ostream &) const
quaternion unitQuaternion (const scalarField &q) const
void unitQuaternion (const quaternion &quat, scalarField &q) const
Additional Inherited Members
Static Public Member Functions inherited from joint
static autoPtr< joint > New (joint *jointPtr)
static autoPtr< joint > New (const dictionary &dict)
Protected Attributes inherited from joint
List< spatialVector > S_
label index_
label qIndex_
Detailed Description
Prismatic joint for translation in the x/y/z directions.
Reference:
    Featherstone, R. (2008).
    Rigid body dynamics algorithms.
    Springer.
    Chapter 4.
Source files
Pxyz.H
Pxyz.C
Definition at line 61 of file Pxyz.H.
Constructor & Destructor Documentation
Pxyz() [1/2]
Pxyz ()
Definition at line 48 of file Pxyz.C.
References joint::S_.
Pxyz() [2/2]
Pxyz (const dictionary & dict)
Definition at line 58 of file Pxyz.C.
References joint::S_.
~Pxyz()
~Pxyz () virtual
Definition at line 76 of file Pxyz.C.
Member Function Documentation
TypeName()
TypeName ("Pxyz")
clone()
Foam::autoPtr< Foam::RBD::joint > clone () const virtual
Implements joint.
Definition at line 68 of file Pxyz.C.
jcalc()
void jcalc (joint::XSvc & J, const scalarField & q, const scalarField & qDot) const virtual
Implements joint.
Definition at line 82 of file Pxyz.C.
References Field< Type >::block(), joint::XSvc::c, spatialTransform::E(), Tensor< scalar >::I, spatialTransform::r(), joint::XSvc::S, joint::XSvc::v, joint::XSvc::X, and Foam::Zero.
The documentation for this class was generated from the following files:
src/rigidBodyDynamics/joints/Pxyz/Pxyz.H
src/rigidBodyDynamics/joints/Pxyz/Pxyz.C