OpenFOAM: triPoints Class Reference
triPoints Class Reference
#include <triangle.H>
Public Member Functions
triPoints ()=default
void front ()=delete
void back ()=delete
triPoints (const point &p0, const point &p1, const point &p2)
triPoints (const triPointRef &pts)
triPoints (const FixedList< point, 3 > &pts)
triPoints (const UList< point > &points, const FixedList< label, 3 > &indices)
const point & a () const noexcept
const point & b () const noexcept
const point & c () const noexcept
point & a () noexcept
point & b () noexcept
point & c () noexcept
void flip ()
triPointRef tri () const
point centre () const
vector areaNormal () const
vector unitNormal () const
scalar mag () const
Pair< point > box () const
vector vecA () const
vector vecB () const
vector vecC () const
Public Member Functions inherited from FixedList< point, 3 >
void writeEntry (const word &keyword, Ostream &os) const
FixedList ()=default
FixedList (const point &val)
FixedList (const Foam::zero)
FixedList (const point list[N])
FixedList (const FixedList< point, N > &list)
FixedList (FixedList< point, N > &&list)
FixedList (std::initializer_list< point > list)
FixedList (const UList< point > &list)
FixedList (const FixedList< point, AnyNum > &list, const FixedList< label, N > &indices)
FixedList (const UList< point > &list, const FixedList< label, N > &indices)
FixedList (const SLList< point > &list)
FixedList (Istream &is)
autoPtr< FixedList< point, N > > clone () const
const point * cdata () const noexcept
point * data () noexcept
const char * cdata_bytes () const noexcept
char * data_bytes () noexcept
point & get () noexcept
const point & get () const noexcept
point & front () noexcept
const point & front () const noexcept
point & back () noexcept
const point & back () const noexcept
label fcIndex (const label i) const
const point & fcValue (const label i) const
point & fcValue (const label i)
label rcIndex (const label i) const
const point & rcValue (const label i) const
point & rcValue (const label i)
void checkStart (const label start) const
void checkSize (const label size) const
void checkIndex (const label i) const
bool uniform () const
label find (const point &val, label pos=0) const
label rfind (const point &val, label pos=-1) const
bool contains (const point &val, label pos=0) const
void resize (const label n)
void resize_nocopy (const label n)
void setSize (const label n)
void fill (const point &val)
void fill (const Foam::zero)
void moveFirst (const label i)
void moveLast (const label i)
void swapFirst (const label i)
void swapLast (const label i)
void transfer (FixedList< point, N > &list)
point & operator[] (const label i)
const point & operator[] (const label i) const
void operator= (const point list[N])
void operator= (const UList< point > &list)
void operator= (const SLList< point > &list)
void operator= (std::initializer_list< point > list)
void operator= (const point &val)
void operator= (const Foam::zero)
void operator= (const FixedList< point, N > &list)
void operator= (FixedList< point, N > &&list)
iterator begin () noexcept
const_iterator begin () const noexcept
iterator end () noexcept
const_iterator end () const noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
const_reverse_iterator crbegin () const
const_reverse_iterator crend () const
void swap (FixedList< point, N > &other)
bool operator== (const FixedList< point, N > &list) const
bool operator!= (const FixedList< point, N > &list) const
bool operator< (const FixedList< point, N > &list) const
bool operator> (const FixedList< point, N > &list) const
bool operator<= (const FixedList< point, N > &list) const
bool operator>= (const FixedList< point, N > &list) const
Istream & readList (Istream &is)
Ostream & writeList (Ostream &os, const label shortLen=0) const
point & first () noexcept
const point & first () const noexcept
point & last () noexcept
const point & last () const noexcept
bool found (const point &val, label pos=0) const
Additional Inherited Members
Public Types inherited from FixedList< point, 3 >
typedef point value_type
typedef point * pointer
typedef const point * const_pointer
typedef point & reference
typedef const point & const_reference
typedef point * iterator
typedef const point * const_iterator
typedef label size_type
typedef label difference_type
typedef std::reverse_iterator< iterator > reverse_iterator
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
Static Public Member Functions inherited from FixedList< point, 3 >
static const FixedList< point, N > & null ()
static std::streamsize size_bytes () noexcept
static std::streamsize byteSize ()
static constexpr bool empty () noexcept
static constexpr label size () noexcept
static constexpr unsigned max_size () noexcept
Protected Member Functions inherited from FixedList< point, 3 >
void writeEntry (Ostream &os) const
Detailed Description
Definition at line 74 of file triangle.H.
Constructor & Destructor Documentation
triPoints() [1/5]
triPoints () default
triPoints() [2/5]
triPoints (const point & p0, const point & p1, const point & p2) inline
Definition at line 28 of file triangleI.H.
References triPoints::a(), triPoints::b(), triPoints::c(), and p0.
triPoints() [3/5]
triPoints (const triPointRef & pts) inline explicit
Definition at line 41 of file triangleI.H.
References b, and pts.
triPoints() [4/5]
triPoints (const FixedList< point, 3 > & pts) inline
Definition at line 49 of file triangleI.H.
triPoints() [5/5]
triPoints (const UList< point > & points, const FixedList< label, 3 > & indices) inline
Definition at line 55 of file triangleI.H.
Member Function Documentation
front()
void front () delete
back()
void back () delete
a() [1/2]
const point & a () const inline noexcept
Definition at line 114 of file triangle.H.
Referenced by triPoints::triPoints().
b() [1/2]
const point & b () const inline noexcept
Definition at line 117 of file triangle.H.
Referenced by triPoints::triPoints().
c() [1/2]
const point & c () const inline noexcept
Definition at line 120 of file triangle.H.
Referenced by triPoints::triPoints().
a() [2/2]
point & a () inline noexcept
Definition at line 123 of file triangle.H.
b() [2/2]
point & b () inline noexcept
Definition at line 126 of file triangle.H.
c() [2/2]
point & c () inline noexcept
Definition at line 129 of file triangle.H.
flip()
void flip () inline
Definition at line 264 of file triangleI.H.
References b.
tri()
Foam::triPointRef tri () const inline
Definition at line 258 of file triangleI.H.
References b.
centre()
Foam::point centre () const inline
Definition at line 132 of file triangleI.H.
References b, and triangle< Point, PointRef >::centre().
areaNormal()
Foam::vector areaNormal () const inline
Definition at line 157 of file triangleI.H.
References triangle< Point, PointRef >::areaNormal(), and b.
unitNormal()
Foam::vector unitNormal () const inline
Definition at line 184 of file triangleI.H.
References b, and triangle< Point, PointRef >::unitNormal().
mag()
Foam::scalar mag () const inline
Definition at line 273 of file triangleI.H.
box()
Foam::Pair< Foam::point > box () const inline
Definition at line 213 of file triangleI.H.
References b, and triangle< Point, PointRef >::box().
vecA()
Foam::vector vecA () const inline
Definition at line 238 of file triangleI.H.
References b.
vecB()
Foam::vector vecB () const inline
Definition at line 244 of file triangleI.H.
vecC()
Foam::vector vecC () const inline
Definition at line 250 of file triangleI.H.
References b.
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/primitiveShapes/triangle/triangle.H
src/OpenFOAM/meshes/primitiveShapes/triangle/triangleI.H