OpenFOAM: duplicatePoints Class Reference
duplicatePoints Class Reference
Duplicate points.
#include <duplicatePoints.H>
Public Member Functions
ClassName ("duplicatePoints")
duplicatePoints (const polyMesh &mesh)
const labelListList & duplicates () const
void setRefinement (const localPointRegion &regionSide, polyTopoChange &)
void updateMesh (const mapPolyMesh &)
Detailed Description
Duplicate points.
Source files
duplicatePoints.H
duplicatePoints.C
Definition at line 55 of file duplicatePoints.H.
Constructor & Destructor Documentation
duplicatePoints()
duplicatePoints (const polyMesh & mesh) explicit
Definition at line 42 of file duplicatePoints.C.
Member Function Documentation
ClassName()
ClassName ("duplicatePoints")
duplicates()
const labelListList & duplicates () const inline
Definition at line 93 of file duplicatePoints.H.
setRefinement()
void setRefinement (const localPointRegion & regionSide, polyTopoChange & meshMod)
Definition at line 51 of file duplicatePoints.C.
References polyTopoChange::addPoint(), UPtrList< T >::end(), f(), UList< T >::find(), forAll, forAllConstIters, polyTopoChange::modifyFace(), patches, polyTopoChange::points(), List< T >::setSize(), PtrList< T >::setSize(), UPtrList< T >::size(), UList< T >::size(), and Foam::meshTools::writeOBJ().
updateMesh()
void updateMesh (const mapPolyMesh & map)
Definition at line 202 of file duplicatePoints.C.
References forAll, Foam::inplaceRenumber(), and mapPolyMesh::reversePointMap().
The documentation for this class was generated from the following files:
src/dynamicMesh/polyTopoChange/polyTopoChange/duplicatePoints.H
src/dynamicMesh/polyTopoChange/polyTopoChange/duplicatePoints.C