OpenFOAM: inclinedFilmNusseltHeightFvPatchScalarField Class Reference
inclinedFilmNusseltHeightFvPatchScalarField Class Reference
Film height boundary condition for inclined films that imposes a sinusoidal perturbation on top of a mean flow rate, where the height is calculated using the Nusselt solution.
#include <inclinedFilmNusseltHeightFvPatchScalarField.H>
Public Member Functions
TypeName ("inclinedFilmNusseltHeight")
inclinedFilmNusseltHeightFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
inclinedFilmNusseltHeightFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
inclinedFilmNusseltHeightFvPatchScalarField (const inclinedFilmNusseltHeightFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
inclinedFilmNusseltHeightFvPatchScalarField (const inclinedFilmNusseltHeightFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
inclinedFilmNusseltHeightFvPatchScalarField (const inclinedFilmNusseltHeightFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
Film height boundary condition for inclined films that imposes a sinusoidal perturbation on top of a mean flow rate, where the height is calculated using the Nusselt solution.
Source files
inclinedFilmNusseltHeightFvPatchScalarField.H
inclinedFilmNusseltHeightFvPatchScalarField.C
Definition at line 50 of file inclinedFilmNusseltHeightFvPatchScalarField.H.
Constructor & Destructor Documentation
inclinedFilmNusseltHeightFvPatchScalarField() [1/5]
inclinedFilmNusseltHeightFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 29 of file inclinedFilmNusseltHeightFvPatchScalarField.C.
inclinedFilmNusseltHeightFvPatchScalarField() [2/5]
inclinedFilmNusseltHeightFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 61 of file inclinedFilmNusseltHeightFvPatchScalarField.C.
inclinedFilmNusseltHeightFvPatchScalarField() [3/5]
inclinedFilmNusseltHeightFvPatchScalarField (const inclinedFilmNusseltHeightFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 44 of file inclinedFilmNusseltHeightFvPatchScalarField.C.
inclinedFilmNusseltHeightFvPatchScalarField() [4/5]
inclinedFilmNusseltHeightFvPatchScalarField (const inclinedFilmNusseltHeightFvPatchScalarField & wmfrhpsf)
Definition at line 80 of file inclinedFilmNusseltHeightFvPatchScalarField.C.
inclinedFilmNusseltHeightFvPatchScalarField() [5/5]
inclinedFilmNusseltHeightFvPatchScalarField (const inclinedFilmNusseltHeightFvPatchScalarField & wmfrhpsf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 94 of file inclinedFilmNusseltHeightFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("inclinedFilmNusseltHeight")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 109 of file inclinedFilmNusseltHeightFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 125 of file inclinedFilmNusseltHeightFvPatchScalarField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 111 of file inclinedFilmNusseltHeightFvPatchScalarField.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), Foam::cbrt(), Foam::endl(), Foam::mag(), Foam::max(), mu, n, Foam::Re(), rho, Foam::sin(), Foam::sqr(), regionModel::time(), Foam::constant::mathematical::twoPi(), and WarningInFunction.
write()
void write (Ostream & os) const virtual
Definition at line 185 of file inclinedFilmNusseltHeightFvPatchScalarField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntryIfDifferent(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/regionModels/surfaceFilmModels/derivedFvPatchFields/inclinedFilmNusseltHeight/inclinedFilmNusseltHeightFvPatchScalarField.H
src/regionModels/surfaceFilmModels/derivedFvPatchFields/inclinedFilmNusseltHeight/inclinedFilmNusseltHeightFvPatchScalarField.C