OpenFOAM: springRenumber Class Reference
springRenumber Class Reference
Use spring analogy - attract neighbouring cells according to the distance of their cell indices.
#include <springRenumber.H>
Public Member Functions
TypeName ("spring")
springRenumber (const dictionary &dict)
virtual ~springRenumber ()=default
virtual labelList renumber (const pointField &) const
virtual labelList renumber (const polyMesh &mesh, const pointField &) const
virtual labelList renumber (const CompactListList< label > &cellCells, const pointField &cellCentres) const
virtual labelList renumber (const labelListList &cellCells, const pointField &cellCentres) const
template<class ConnectionListListType >
Foam::labelList renumberImpl (const ConnectionListListType &cellCells) const
Public Member Functions inherited from renumberMethod
TypeName ("renumberMethod")
declareRunTimeSelectionTable (autoPtr, renumberMethod, dictionary,(const dictionary &renumberDict),(renumberDict))
renumberMethod (const dictionary &dict)
virtual ~renumberMethod ()=default
virtual labelList renumber (const labelList &cellCells, const labelList &offsets, const pointField &) const
virtual labelList renumber (const polyMesh &mesh, const labelList &fineToCoarse, const pointField &coarsePoints) const
Additional Inherited Members
Static Public Member Functions inherited from renumberMethod
static autoPtr< renumberMethod > New (const dictionary &renumberDict)
Protected Member Functions inherited from renumberMethod
renumberMethod (const renumberMethod &)=delete
void operator= (const renumberMethod &)=delete
Protected Attributes inherited from renumberMethod
const dictionary & renumberDict_
Detailed Description
Use spring analogy - attract neighbouring cells according to the distance of their cell indices.
Maximum jump of cell indices. Is fraction of number of cells maxCo 0.1;
Limit the amount of movement; the fraction maxCo gets decreased with every iteration. freezeFraction 0.9;
Maximum number of iterations maxIter 1000;
Source files
springRenumber.H
springRenumber.C
Definition at line 56 of file springRenumber.H.
Constructor & Destructor Documentation
springRenumber()
springRenumber (const dictionary & dict) explicit
Definition at line 43 of file springRenumber.C.
~springRenumber()
virtual ~springRenumber () virtual default
Member Function Documentation
TypeName()
TypeName ("spring")
renumber() [1/4]
virtual labelList renumber (const pointField &) const inline virtual
Reimplemented from renumberMethod.
Definition at line 109 of file springRenumber.H.
References NotImplemented.
renumber() [2/4]
Foam::labelList renumber (const polyMesh & mesh, const pointField &) const virtual
Reimplemented from renumberMethod.
Definition at line 153 of file springRenumber.C.
References decompositionMethod::calcCellCells(), Foam::identity(), mesh, and primitiveMesh::nCells().
renumber() [3/4]
Foam::labelList renumber (const CompactListList< label > & cellCells, const pointField & cellCentres) const virtual
Reimplemented from renumberMethod.
Definition at line 173 of file springRenumber.C.
renumber() [4/4]
Foam::labelList renumber (const labelListList & cellCells, const pointField & cellCentres) const virtual
Implements renumberMethod.
Definition at line 183 of file springRenumber.C.
renumberImpl()
template<class ConnectionListListType > Foam::labelList renumberImpl (const ConnectionListListType & cellCells) const
Definition at line 56 of file springRenumber.C.
References Foam::average(), Foam::endl(), forAll, Foam::identity(), Foam::Info, Foam::inplaceReorder(), Foam::invert(), Foam::mag(), Foam::max(), maxCo, Foam::min(), Foam::shuffle(), UPtrList< T >::size(), UList< T >::size(), Foam::sortedOrder(), and Foam::Zero.
The documentation for this class was generated from the following files:
src/renumber/renumberMethods/springRenumber/springRenumber.H
src/renumber/renumberMethods/springRenumber/springRenumber.C