OpenFOAM: Boussinesq< Specie > Class Template Reference
Boussinesq< Specie > Class Template Reference
Thermophysical models » Specie » Equation of state
Incompressible gas equation of state using the Boussinesq approximation for the density as a function of temperature only:
#include <Boussinesq.H>
Public Member Functions
Boussinesq (const Specie &sp, const scalar rho0, const scalar T0, const scalar beta)
Boussinesq (const dictionary &dict)
Boussinesq (const word &name, const Boussinesq &)
autoPtr< Boussinesq > clone () const
scalar rho (scalar p, scalar T) const
scalar H (const scalar p, const scalar T) const
scalar Cp (scalar p, scalar T) const
scalar E (const scalar p, const scalar T) const
scalar Cv (scalar p, scalar T) const
scalar S (const scalar p, const scalar T) const
scalar psi (scalar p, scalar T) const
scalar Z (scalar p, scalar T) const
scalar CpMCv (scalar p, scalar T) const
void write (Ostream &os) const
void operator= (const Boussinesq &)
void operator+= (const Boussinesq &)
void operator*= (const scalar)
Static Public Member Functions
static autoPtr< Boussinesq > New (const dictionary &dict)
static word typeName ()
Static Public Attributes
static const bool incompressible = true
static const bool isochoric = false
Friends
Boussinesq operator+ (const Boussinesq &, const Boussinesq &)
Boussinesq operator* (const scalar s, const Boussinesq &)
Boussinesq operator== (const Boussinesq &, const Boussinesq &)
Ostream & operator<< (Ostream &, const Boussinesq &)
Detailed Description
template<class Specie>
class Foam::Boussinesq< Specie >
Incompressible gas equation of state using the Boussinesq approximation for the density as a function of temperature only:
    rho = rho0*(1 - beta*(T - T0))
Source files
Boussinesq.H
BoussinesqI.H
Boussinesq.C
Definition at line 89 of file Boussinesq.H.
Constructor & Destructor Documentation
Boussinesq() [1/3]
template<class Specie > Boussinesq (const Specie & sp, const scalar rho0, const scalar T0, const scalar beta) inline
Definition at line 27 of file BoussinesqI.H.
Boussinesq() [2/3]
template<class Specie > Boussinesq (const dictionary & dict)
Definition at line 27 of file Boussinesq.C.
Boussinesq() [3/3]
template<class Specie > Boussinesq (const word & name, const Boussinesq< Specie > &) inline
Member Function Documentation
clone()
template<class Specie > Foam::autoPtr< Foam::Boussinesq< Specie > > clone () const inline
Definition at line 55 of file BoussinesqI.H.
References Foam::New().
New()
template<class Specie > Foam::autoPtr< Foam::Boussinesq< Specie > > New (const dictionary & dict) inline static
Definition at line 63 of file BoussinesqI.H.
References dict, and Foam::New().
typeName()
template<class Specie > static word typeName () inline static
Definition at line 141 of file Boussinesq.H.
rho()
template<class Specie > Foam::scalar rho (scalar p, scalar T) const inline
Definition at line 75 of file BoussinesqI.H.
References T.
H()
template<class Specie > Foam::scalar H (const scalar p, const scalar T) const inline
Definition at line 86 of file BoussinesqI.H.
Cp()
template<class Specie > Foam::scalar Cp (scalar p, scalar T) const inline
Definition at line 93 of file BoussinesqI.H.
E()
template<class Specie > Foam::scalar E (const scalar p, const scalar T) const inline
Definition at line 99 of file BoussinesqI.H.
Cv()
template<class Specie > Foam::scalar Cv (scalar p, scalar T) const inline
Definition at line 106 of file BoussinesqI.H.
S()
template<class Specie > Foam::scalar S (const scalar p, const scalar T) const inline
Definition at line 113 of file BoussinesqI.H.
psi()
template<class Specie > Foam::scalar psi (scalar p, scalar T) const inline
Definition at line 124 of file BoussinesqI.H.
Z()
template<class Specie > Foam::scalar Z (scalar p, scalar T) const inline
Definition at line 135 of file BoussinesqI.H.
CpMCv()
template<class Specie > Foam::scalar CpMCv (scalar p, scalar T) const inline
Definition at line 146 of file BoussinesqI.H.
write()
template<class Specie > void write (Ostream & os) const
Definition at line 42 of file Boussinesq.C.
References Ostream::beginBlock(), Ostream::endBlock(), os(), and Ostream::writeEntry().
operator=()
template<class Specie > void operator= (const Boussinesq< Specie > &) inline
Definition at line 159 of file BoussinesqI.H.
References b.
operator+=()
template<class Specie > void operator+= (const Boussinesq< Specie > &) inline
Definition at line 173 of file BoussinesqI.H.
References b, Foam::mag(), and Y.
operator*=()
template<class Specie > void operator*= (const scalar s) inline
Definition at line 194 of file BoussinesqI.H.
References s().
Friends And Related Symbol Documentation
operator+
template<class Specie > Boussinesq operator+ (const Boussinesq< Specie > & , const Boussinesq< Specie > &) friend
operator*
template<class Specie > Boussinesq operator* (const scalar s, const Boussinesq< Specie > &) friend
operator==
template<class Specie > Boussinesq operator== (const Boussinesq< Specie > & , const Boussinesq< Specie > &) friend
operator<<
template<class Specie > Ostream & operator<< (Ostream & , const Boussinesq< Specie > &) friend
Member Data Documentation
incompressible
template<class Specie > const bool incompressible = true static
Definition at line 152 of file Boussinesq.H.
isochoric
template<class Specie > const bool isochoric = false static
Definition at line 155 of file Boussinesq.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/equationOfState/Boussinesq/Boussinesq.H
src/thermophysicalModels/specie/equationOfState/Boussinesq/Boussinesq.C
src/thermophysicalModels/specie/equationOfState/Boussinesq/BoussinesqI.H