OpenFOAM: tabulatedAnIsoSolidTransport< Thermo > Class Template Reference
tabulatedAnIsoSolidTransport< Thermo > Class Template Reference
Transport properties package using Function1 type data for anisotropic thermal conductivity.
#include <tabulatedAnIsoSolidTransport.H>
Public Member Functions
tabulatedAnIsoSolidTransport (const word &, const tabulatedAnIsoSolidTransport &)
tabulatedAnIsoSolidTransport (const dictionary &dict)
autoPtr< tabulatedAnIsoSolidTransport > clone () const
scalar mu (const scalar p, const scalar T) const
scalar kappa (const scalar p, const scalar T) const
vector Kappa (const scalar p, const scalar T) const
scalar alphah (const scalar p, const scalar T) const
void write (Ostream &os) const
Static Public Member Functions
static autoPtr< tabulatedAnIsoSolidTransport > New (const dictionary &dict)
static word typeName ()
Static Public Attributes
static const bool isotropic = false
Friends
Ostream & operator<< (Ostream &, const tabulatedAnIsoSolidTransport &)
Detailed Description
template<class Thermo>
class Foam::tabulatedAnIsoSolidTransport< Thermo >
Transport properties package using Function1 type data for anisotropic thermal conductivity.
Usage
Example of the specification of the transport properties:
transport
{
    // kappa      <Function1<vector>>;
    kappa         table
    (
        // T      kappa
        (  200    (2.56e-5 2e-5 2e-5) )
        (  350    (3.33e-5 1e-5 1e-5) )
        (  400    (4.72e-5 3e-5 3-e5) )
    );
}
where the entries mean:
Property Description Type Reqd Deflt
kappa Thermal conductivity Function1<vector> yes -
Source files
tabulatedAnIsoSolidTransport.H
tabulatedAnIsoSolidTransportI.H
tabulatedAnIsoSolidTransport.C
Definition at line 91 of file tabulatedAnIsoSolidTransport.H.
Constructor & Destructor Documentation
tabulatedAnIsoSolidTransport() [1/2]
template<class Thermo > tabulatedAnIsoSolidTransport (const word & name, const tabulatedAnIsoSolidTransport< Thermo > & pt) inline
Definition at line 39 of file tabulatedAnIsoSolidTransportI.H.
References Foam::name().
tabulatedAnIsoSolidTransport() [2/2]
template<class Thermo > tabulatedAnIsoSolidTransport (const dictionary & dict) explicit
Definition at line 27 of file tabulatedAnIsoSolidTransport.C.
References Foam::New().
Member Function Documentation
clone()
template<class Thermo > Foam::autoPtr< Foam::tabulatedAnIsoSolidTransport< Thermo > > clone () const inline
Definition at line 52 of file tabulatedAnIsoSolidTransportI.H.
References Foam::New().
New()
template<class Thermo > Foam::autoPtr< Foam::tabulatedAnIsoSolidTransport< Thermo > > New (const dictionary & dict) inline static
Definition at line 60 of file tabulatedAnIsoSolidTransportI.H.
References dict, and Foam::New().
typeName()
template<class Thermo > static word typeName () inline static
Definition at line 138 of file tabulatedAnIsoSolidTransport.H.
mu()
template<class Thermo > Foam::scalar mu (const scalar p, const scalar T) const inline
Definition at line 69 of file tabulatedAnIsoSolidTransportI.H.
References NotImplemented.
kappa()
template<class Thermo > Foam::scalar kappa (const scalar p, const scalar T) const inline
Definition at line 81 of file tabulatedAnIsoSolidTransportI.H.
References Foam::mag(), and T.
Kappa()
template<class Thermo > Foam::vector Kappa (const scalar p, const scalar T) const inline
Definition at line 92 of file tabulatedAnIsoSolidTransportI.H.
References T.
alphah()
template<class Thermo > Foam::scalar alphah (const scalar p, const scalar T) const inline
Definition at line 103 of file tabulatedAnIsoSolidTransportI.H.
References Cp, p, and T.
write()
template<class Thermo > void write (Ostream & os) const
Definition at line 40 of file tabulatedAnIsoSolidTransport.C.
References Ostream::beginBlock(), Ostream::endBlock(), Foam::name(), and os().
Friends And Related Symbol Documentation
operator<<
template<class Thermo > Ostream & operator<< (Ostream & , const tabulatedAnIsoSolidTransport< Thermo > &) friend
Member Data Documentation
isotropic
template<class Thermo > const bool isotropic = false static
Definition at line 144 of file tabulatedAnIsoSolidTransport.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/solidSpecie/transport/tabulated/tabulatedAnIsoSolidTransport.H
src/thermophysicalModels/solidSpecie/transport/tabulated/tabulatedAnIsoSolidTransport.C
src/thermophysicalModels/solidSpecie/transport/tabulated/tabulatedAnIsoSolidTransportI.H