OpenFOAM: polyMeshGeometry Class Reference
polyMeshGeometry Class Reference
Updateable mesh geometry and checking routines.
#include <polyMeshGeometry.H>
Public Member Functions
ClassName ("polyMeshGeometry")
polyMeshGeometry (const polyMesh &)
const polyMesh & mesh () const
const vectorField & faceAreas () const
const vectorField & faceCentres () const
const vectorField & cellCentres () const
const scalarField & cellVolumes () const
void correct ()
void correct (const pointField &p, const labelList &changedFaces)
bool checkFaceDotProduct (const bool report, const scalar orthWarn, const labelList &checkFaces, const List< labelPair > &baffles, labelHashSet *setPtr) const
bool checkFacePyramids (const bool report, const scalar minPyrVol, const pointField &p, const labelList &checkFaces, const List< labelPair > &baffles, labelHashSet *setPtr) const
bool checkFaceTets (const bool report, const scalar minTetQuality, const pointField &p, const labelList &checkFaces, const List< labelPair > &baffles, labelHashSet *setPtr) const
bool checkFaceWeights (const bool report, const scalar warnWeight, const labelList &checkFaces, const List< labelPair > &baffles, labelHashSet *setPtr) const
bool checkVolRatio (const bool report, const scalar warnRatio, const labelList &checkFaces, const List< labelPair > &baffles, labelHashSet *setPtr) const
bool checkFaceAngles (const bool report, const scalar maxDeg, const pointField &p, const labelList &checkFaces, labelHashSet *setPtr) const
bool checkFaceTwist (const bool report, const scalar minTwist, const pointField &p, const labelList &checkFaces, labelHashSet *setPtr) const
bool checkTriangleTwist (const bool report, const scalar minTwist, const pointField &p, const labelList &checkFaces, labelHashSet *setPtr) const
bool checkFaceFlatness (const bool report, const scalar minFlatness, const pointField &p, const labelList &checkFaces, labelHashSet *setPtr) const
bool checkFaceArea (const bool report, const scalar minArea, const labelList &checkFaces, labelHashSet *setPtr) const
bool checkCellDeterminant (const bool report, const scalar warnDet, const labelList &checkFaces, const labelList &affectedCells, labelHashSet *setPtr) const
bool checkEdgeLength (const bool report, const scalar minEdgeLength, const labelList &checkFaces, labelHashSet *pointSetPtr) const
Static Public Member Functions
static labelList affectedCells (const polyMesh &, const labelList &changedFaces)
static bool checkFaceDotProduct (const bool report, const scalar orthWarn, const polyMesh &, const vectorField &cellCentres, const vectorField &faceAreas, const labelList &checkFaces, const List< labelPair > &baffles, labelHashSet *setPtr)
static bool checkFacePyramids (const bool report, const scalar minPyrVol, const polyMesh &, const vectorField &cellCentres, const pointField &p, const labelList &checkFaces, const List< labelPair > &baffles, labelHashSet *)
static bool checkFaceTets (const bool report, const scalar minPyrVol, const polyMesh &, const vectorField &cellCentres, const vectorField &faceCentres, const pointField &p, const labelList &checkFaces, const List< labelPair > &baffles, labelHashSet *)
static bool checkFaceSkewness (const bool report, const scalar internalSkew, const scalar boundarySkew, const polyMesh &mesh, const pointField &points, const vectorField &cellCentres, const vectorField &faceCentres, const vectorField &faceAreas, const labelList &checkFaces, const List< labelPair > &baffles, labelHashSet *setPtr)
static bool checkFaceWeights (const bool report, const scalar warnWeight, const polyMesh &mesh, const vectorField &cellCentres, const vectorField &faceCentres, const vectorField &faceAreas, const labelList &checkFaces, const List< labelPair > &baffles, labelHashSet *setPtr)
static bool checkVolRatio (const bool report, const scalar warnRatio, const polyMesh &mesh, const scalarField &cellVolumes, const labelList &checkFaces, const List< labelPair > &baffles, labelHashSet *setPtr)
static bool checkFaceAngles (const bool report, const scalar maxDeg, const polyMesh &mesh, const vectorField &faceAreas, const pointField &p, const labelList &checkFaces, labelHashSet *setPtr)
static bool checkFaceTwist (const bool report, const scalar minTwist, const polyMesh &, const vectorField &cellCentres, const vectorField &faceAreas, const vectorField &faceCentres, const pointField &p, const labelList &checkFaces, labelHashSet *setPtr)
static bool checkTriangleTwist (const bool report, const scalar minTwist, const polyMesh &, const vectorField &faceAreas, const vectorField &faceCentres, const pointField &p, const labelList &checkFaces, labelHashSet *setPtr)
static bool checkFaceFlatness (const bool report, const scalar minFlatness, const polyMesh &, const vectorField &faceAreas, const vectorField &faceCentres, const pointField &p, const labelList &checkFaces, labelHashSet *setPtr)
static bool checkFaceArea (const bool report, const scalar minArea, const polyMesh &, const vectorField &faceAreas, const labelList &checkFaces, labelHashSet *setPtr)
static bool checkCellDeterminant (const bool report, const scalar minDet, const polyMesh &, const vectorField &faceAreas, const labelList &checkFaces, const labelList &affectedCells, labelHashSet *setPtr)
static bool checkEdgeLength (const bool report, const scalar minEdgeLength, const polyMesh &mesh, const labelList &checkFaces, labelHashSet *pointSetPtr)
Detailed Description
Updateable mesh geometry and checking routines.
non-ortho done across coupled faces.
faceWeight (delta factors) done across coupled faces.
Source files
polyMeshGeometry.H
polyMeshGeometry.C
Definition at line 51 of file polyMeshGeometry.H.
Constructor & Destructor Documentation
polyMeshGeometry()
polyMeshGeometry (const polyMesh & mesh) explicit
Definition at line 330 of file polyMeshGeometry.C.
References polyMeshGeometry::correct().
Member Function Documentation
ClassName()
ClassName ("polyMeshGeometry")
mesh()
const polyMesh & mesh () const inline
Definition at line 137 of file polyMeshGeometry.H.
faceAreas()
const vectorField & faceAreas () const inline
Definition at line 142 of file polyMeshGeometry.H.
faceCentres()
const vectorField & faceCentres () const inline
Definition at line 146 of file polyMeshGeometry.H.
cellCentres()
const vectorField & cellCentres () const inline
Definition at line 150 of file polyMeshGeometry.H.
cellVolumes()
const scalarField & cellVolumes () const inline
Definition at line 154 of file polyMeshGeometry.H.
correct() [1/2]
void correct ()
Definition at line 340 of file polyMeshGeometry.C.
Referenced by polyMeshGeometry::polyMeshGeometry().
correct() [2/2]
void correct (const pointField & p, const labelList & changedFaces)
Definition at line 349 of file polyMeshGeometry.C.
References p.
affectedCells()
Foam::labelList affectedCells (const polyMesh & mesh, const labelList & changedFaces) static
Definition at line 185 of file polyMeshGeometry.C.
References polyMesh::faceNeighbour(), polyMesh::faceOwner(), HashSet< Key, Hash >::insert(), primitiveMesh::isInternalFace(), mesh, UPtrList< T >::size(), and HashTable< T, Key, Hash >::toc().
Referenced by motionSmootherAlgo::checkMesh(), and motionSmootherAlgo::checkMesh().
checkFaceDotProduct() [1/2]
bool checkFaceDotProduct (const bool report, const scalar orthWarn, const polyMesh & mesh, const vectorField & cellCentres, const vectorField & faceAreas, const labelList & checkFaces, const List< labelPair > & baffles, labelHashSet * setPtr) static
Definition at line 362 of file polyMeshGeometry.C.
References Foam::acos(), polyMesh::boundaryMesh(), Foam::cos(), coupled(), Foam::degToRad(), Foam::endl(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), UPtrList< T >::first(), Foam::Info, primitiveMesh::isInternalFace(), mesh, primitiveMesh::nBoundaryFaces(), primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), patches, Foam::radToDeg(), Foam::reduce(), SeriousErrorInFunction, and syncTools::swapBoundaryFacePositions().
Referenced by motionSmootherAlgo::checkMesh().
checkFacePyramids() [1/2]
bool checkFacePyramids (const bool report, const scalar minPyrVol, const polyMesh & mesh, const vectorField & cellCentres, const pointField & p, const labelList & checkFaces, const List< labelPair > & baffles, labelHashSet * setPtr) static
Definition at line 540 of file polyMeshGeometry.C.
References primitiveMesh::cells(), Foam::endl(), f(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), polyMesh::faces(), UPtrList< T >::first(), Foam::Info, primitiveMesh::isInternalFace(), mesh, p, Foam::Pout, Foam::reduce(), and SeriousErrorInFunction.
Referenced by motionSmootherAlgo::checkMesh().
checkFaceTets() [1/2]
bool checkFaceTets (const bool report, const scalar minPyrVol, const polyMesh & mesh, const vectorField & cellCentres, const vectorField & faceCentres, const pointField & p, const labelList & checkFaces, const List< labelPair > & baffles, labelHashSet * setPtr) static
Definition at line 711 of file polyMeshGeometry.C.
References polyMesh::boundaryMesh(), coupled(), Foam::endl(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), polyMeshTetDecomposition::findBasePoint(), polyMeshTetDecomposition::findSharedBasePoint(), UPtrList< T >::first(), Foam::Info, primitiveMesh::isInternalFace(), mesh, primitiveMesh::nBoundaryFaces(), primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), p, patches, Foam::reduce(), SeriousErrorInFunction, and syncTools::swapBoundaryFacePositions().
Referenced by motionSmootherAlgo::checkMesh().
checkFaceSkewness()
bool checkFaceSkewness (const bool report, const scalar internalSkew, const scalar boundarySkew, const polyMesh & mesh, const pointField & points, const vectorField & cellCentres, const vectorField & faceCentres, const vectorField & faceAreas, const labelList & checkFaces, const List< labelPair > & baffles, labelHashSet * setPtr) static
Definition at line 932 of file polyMeshGeometry.C.
References primitiveMeshTools::boundaryFaceSkewness(), polyMesh::boundaryMesh(), Foam::endl(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), polyMesh::faces(), primitiveMeshTools::faceSkewness(), UPtrList< T >::first(), Foam::Info, primitiveMesh::isInternalFace(), Foam::max(), mesh, primitiveMesh::nInternalFaces(), Foam::nl, patches, points, Foam::Pout, Foam::reduce(), syncTools::swapBoundaryCellPositions(), and WarningInFunction.
Referenced by motionSmootherAlgo::checkMesh(), and motionSmootherAlgo::checkMesh().
checkFaceWeights() [1/2]
bool checkFaceWeights (const bool report, const scalar warnWeight, const polyMesh & mesh, const vectorField & cellCentres, const vectorField & faceCentres, const vectorField & faceAreas, const labelList & checkFaces, const List< labelPair > & baffles, labelHashSet * setPtr) static
Definition at line 1138 of file polyMeshGeometry.C.
References polyMesh::boundaryMesh(), coupled(), Foam::endl(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), UPtrList< T >::first(), Foam::Info, primitiveMesh::isInternalFace(), Foam::mag(), mesh, Foam::min(), primitiveMesh::nBoundaryFaces(), primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), Foam::nl, patches, Foam::Pout, Foam::reduce(), syncTools::swapBoundaryFacePositions(), and WarningInFunction.
Referenced by motionSmootherAlgo::checkMesh().
checkVolRatio() [1/2]
bool checkVolRatio (const bool report, const scalar warnRatio, const polyMesh & mesh, const scalarField & cellVolumes, const labelList & checkFaces, const List< labelPair > & baffles, labelHashSet * setPtr) static
Definition at line 1286 of file polyMeshGeometry.C.
References polyMesh::boundaryMesh(), coupled(), Foam::endl(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), UPtrList< T >::first(), Foam::Info, primitiveMesh::isInternalFace(), Foam::mag(), Foam::max(), mesh, Foam::min(), primitiveMesh::nBoundaryFaces(), primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), Foam::nl, patches, Foam::Pout, Foam::reduce(), syncTools::swapBoundaryFaceList(), and WarningInFunction.
Referenced by motionSmootherAlgo::checkMesh().
checkFaceAngles() [1/2]
bool checkFaceAngles (const bool report, const scalar maxDeg, const polyMesh & mesh, const vectorField & faceAreas, const pointField & p, const labelList & checkFaces, labelHashSet * setPtr) static
Definition at line 1422 of file polyMeshGeometry.C.
References Foam::abort(), Foam::asin(), Foam::degToRad(), Foam::endl(), f(), polyMesh::faces(), Foam::FatalError, FatalErrorInFunction, UList< T >::first(), forAll, Foam::Info, UList< T >::last(), Foam::mag(), Foam::max(), mesh, Foam::min(), Foam::normalised(), p, Foam::radToDeg(), Foam::reduce(), Foam::sin(), and WarningInFunction.
Referenced by motionSmootherAlgo::checkMesh().
checkFaceTwist() [1/2]
bool checkFaceTwist (const bool report, const scalar minTwist, const polyMesh & mesh, const vectorField & cellCentres, const vectorField & faceAreas, const vectorField & faceCentres, const pointField & p, const labelList & checkFaces, labelHashSet * setPtr) static
Definition at line 1547 of file polyMeshGeometry.C.
References Foam::abort(), triangle< Point, PointRef >::areaNormal(), polyMesh::boundaryMesh(), Foam::endl(), f(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), polyMesh::faces(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::Info, primitiveMesh::isInternalFace(), Foam::mag(), mesh, primitiveMesh::nBoundaryFaces(), primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), Foam::nl, Foam::normalised(), p, patches, Foam::reduce(), UList< T >::size(), syncTools::swapBoundaryFacePositions(), WarningInFunction, Foam::Zero, and VectorSpace< Form, Cmpt, Ncmpts >::zero.
Referenced by motionSmootherAlgo::checkMesh().
checkTriangleTwist() [1/2]
bool checkTriangleTwist (const bool report, const scalar minTwist, const polyMesh & mesh, const vectorField & faceAreas, const vectorField & faceCentres, const pointField & p, const labelList & checkFaces, labelHashSet * setPtr) static
Definition at line 1693 of file polyMeshGeometry.C.
References Foam::abort(), triangle< Point, PointRef >::areaNormal(), Foam::endl(), f(), polyMesh::faces(), Foam::FatalError, FatalErrorInFunction, UList< T >::fcIndex(), forAll, Foam::Info, Foam::mag(), mesh, Foam::nl, p, Foam::reduce(), UList< T >::size(), and WarningInFunction.
Referenced by motionSmootherAlgo::checkMesh().
checkFaceFlatness() [1/2]
bool checkFaceFlatness (const bool report, const scalar minFlatness, const polyMesh & mesh, const vectorField & faceAreas, const vectorField & faceCentres, const pointField & p, const labelList & checkFaces, labelHashSet * setPtr) static
Definition at line 1839 of file polyMeshGeometry.C.
References Foam::abort(), Foam::endl(), f(), polyMesh::faces(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::Info, Foam::mag(), mesh, Foam::nl, p, Foam::reduce(), UList< T >::size(), and WarningInFunction.
Referenced by motionSmootherAlgo::checkMesh().
checkFaceArea() [1/2]
bool checkFaceArea (const bool report, const scalar minArea, const polyMesh & mesh, const vectorField & faceAreas, const labelList & checkFaces, labelHashSet * setPtr) static
Definition at line 1932 of file polyMeshGeometry.C.
References Foam::endl(), Foam::Info, Foam::mag(), Foam::nl, Foam::reduce(), and WarningInFunction.
Referenced by motionSmootherAlgo::checkMesh().
checkCellDeterminant() [1/2]
bool checkCellDeterminant (const bool report, const scalar minDet, const polyMesh & mesh, const vectorField & faceAreas, const labelList & checkFaces, const labelList & affectedCells, labelHashSet * setPtr) static
Definition at line 1989 of file polyMeshGeometry.C.
References cells, primitiveMesh::cells(), Foam::det(), Foam::endl(), Foam::Info, Foam::mag(), mesh, Foam::min(), Foam::nl, Foam::reduce(), WarningInFunction, and Foam::Zero.
Referenced by motionSmootherAlgo::checkMesh().
checkEdgeLength() [1/2]
bool checkEdgeLength (const bool report, const scalar minEdgeLength, const polyMesh & mesh, const labelList & checkFaces, labelHashSet * pointSetPtr) static
Definition at line 2081 of file polyMeshGeometry.C.
References Foam::endl(), f(), polyMesh::faces(), UList< T >::fcIndex(), forAll, Foam::Info, Foam::magSqr(), Foam::max(), mesh, Foam::min(), points, polyMesh::points(), Foam::reduce(), Foam::sqr(), and Foam::sqrt().
Referenced by motionSmootherAlgo::checkMesh().
checkFaceDotProduct() [2/2]
bool checkFaceDotProduct (const bool report, const scalar orthWarn, const labelList & checkFaces, const List< labelPair > & baffles, labelHashSet * setPtr) const
Definition at line 2150 of file polyMeshGeometry.C.
checkFacePyramids() [2/2]
bool checkFacePyramids (const bool report, const scalar minPyrVol, const pointField & p, const labelList & checkFaces, const List< labelPair > & baffles, labelHashSet * setPtr) const
Definition at line 2173 of file polyMeshGeometry.C.
References p.
checkFaceTets() [2/2]
bool checkFaceTets (const bool report, const scalar minTetQuality, const pointField & p, const labelList & checkFaces, const List< labelPair > & baffles, labelHashSet * setPtr) const
Definition at line 2197 of file polyMeshGeometry.C.
References p.
checkFaceWeights() [2/2]
bool checkFaceWeights (const bool report, const scalar warnWeight, const labelList & checkFaces, const List< labelPair > & baffles, labelHashSet * setPtr) const
Definition at line 2248 of file polyMeshGeometry.C.
checkVolRatio() [2/2]
bool checkVolRatio (const bool report, const scalar warnRatio, const labelList & checkFaces, const List< labelPair > & baffles, labelHashSet * setPtr) const
Definition at line 2272 of file polyMeshGeometry.C.
checkFaceAngles() [2/2]
bool checkFaceAngles (const bool report, const scalar maxDeg, const pointField & p, const labelList & checkFaces, labelHashSet * setPtr) const
Definition at line 2294 of file polyMeshGeometry.C.
References p.
checkFaceTwist() [2/2]
bool checkFaceTwist (const bool report, const scalar minTwist, const pointField & p, const labelList & checkFaces, labelHashSet * setPtr) const
Definition at line 2316 of file polyMeshGeometry.C.
References p.
checkTriangleTwist() [2/2]
bool checkTriangleTwist (const bool report, const scalar minTwist, const pointField & p, const labelList & checkFaces, labelHashSet * setPtr) const
Definition at line 2340 of file polyMeshGeometry.C.
References p.
checkFaceFlatness() [2/2]
bool checkFaceFlatness (const bool report, const scalar minFlatness, const pointField & p, const labelList & checkFaces, labelHashSet * setPtr) const
Definition at line 2363 of file polyMeshGeometry.C.
References p.
checkFaceArea() [2/2]
bool checkFaceArea (const bool report, const scalar minArea, const labelList & checkFaces, labelHashSet * setPtr) const
Definition at line 2386 of file polyMeshGeometry.C.
checkCellDeterminant() [2/2]
bool checkCellDeterminant (const bool report, const scalar warnDet, const labelList & checkFaces, const labelList & affectedCells, labelHashSet * setPtr) const
Definition at line 2406 of file polyMeshGeometry.C.
checkEdgeLength() [2/2]
bool checkEdgeLength (const bool report, const scalar minEdgeLength, const labelList & checkFaces, labelHashSet * pointSetPtr) const
Definition at line 2428 of file polyMeshGeometry.C.
The documentation for this class was generated from the following files:
src/dynamicMesh/motionSmoother/polyMeshGeometry/polyMeshGeometry.H
src/dynamicMesh/motionSmoother/polyMeshGeometry/polyMeshGeometry.C