OpenFOAM: cutFaceIso Class Reference
cutFaceIso Class Reference
Class for cutting a face, faceI, of an fvMesh, mesh_, at its intersection with an isosurface defined by the mesh point values f_ and the isovalue, cutValue.
#include <cutFaceIso.H>
Public Member Functions
cutFaceIso (const fvMesh &mesh, scalarField &f)
label calcSubFace (const label faceI, const scalar cutValue)
const point & subFaceCentre () const noexcept
const vector & subFaceArea () const noexcept
const DynamicList< point > & subFacePoints () const noexcept
const DynamicList< point > & surfacePoints () const noexcept
void clearStorage ()
Public Member Functions inherited from cutFace
cutFace (const fvMesh &mesh)
Additional Inherited Members
Static Public Attributes inherited from cutFace
static int debug = 0
Protected Member Functions inherited from cutFace
void calcSubFace (const label faceI, const scalarList &pointStatus, label firstFullySubmergedPoint, DynamicList< point > &subFacePoints, DynamicList< point > &surfacePoints, label &faceStatus, vector &subFaceCentre, vector &subFaceArea)
void calcSubFace (const label faceI, const scalarList &pointStatus, const scalarList &weights, label firstFullySubmergedPoint, DynamicList< point > &subFacePoints, DynamicList< point > &surfacePoints, label &faceStatus, vector &subFaceCentre, vector &subFaceArea)
void calcSubFaceCentreAndArea (DynamicList< point > &subFacePoints, vector &subFaceCentre, vector &subFaceArea)
void calcSubFace (const face &f, const pointField &points, const scalarList &pointStatus, label firstFullySubmergedPoint, DynamicList< point > &subFacePoints, DynamicList< point > &surfacePoints, label &faceStatus, vector &subFaceCentre, vector &subFaceArea)
Detailed Description
Class for cutting a face, faceI, of an fvMesh, mesh_, at its intersection with an isosurface defined by the mesh point values f_ and the isovalue, cutValue.
Reference:
    Roenby, J., Bredmose, H. and Jasak, H. (2016).
    A computational method for sharp interface advection
    Royal Society Open Science, 3
    doi 10.1098/rsos.160405
Original code supplied by Johan Roenby, DHI (2016)
Source files
cutFaceIso.H
cutFaceIso.C
Definition at line 64 of file cutFaceIso.H.
Constructor & Destructor Documentation
cutFaceIso()
cutFaceIso (const fvMesh & mesh, scalarField & f)
Definition at line 27 of file cutFaceIso.C.
References cutFaceIso::clearStorage().
Member Function Documentation
calcSubFace()
Foam::label calcSubFace (const label faceI, const scalar cutValue)
Definition at line 46 of file cutFaceIso.C.
References PtrList< T >::append(), cutFace::calcSubFace(), f(), forAll, Foam::mag(), UList< T >::size(), and Foam::Zero.
subFaceCentre()
const point & subFaceCentre () const inline noexcept
Definition at line 122 of file cutFaceIso.H.
subFaceArea()
const vector & subFaceArea () const inline noexcept
Definition at line 128 of file cutFaceIso.H.
subFacePoints()
const DynamicList< point > & subFacePoints () const inline noexcept
Definition at line 134 of file cutFaceIso.H.
surfacePoints()
const DynamicList< point > & surfacePoints () const inline noexcept
Definition at line 140 of file cutFaceIso.H.
clearStorage()
void clearStorage ()
Definition at line 107 of file cutFaceIso.C.
References PtrList< T >::clear(), and Foam::Zero.
Referenced by cutFaceIso::cutFaceIso().
The documentation for this class was generated from the following files:
src/transportModels/geometricVoF/cellCuts/cutFace/cutFaceIso.H
src/transportModels/geometricVoF/cellCuts/cutFace/cutFaceIso.C