OpenFOAM: solverControl Class Reference
solverControl Class Reference
Base class for solver control classes.
#include <solverControl.H>
Public Member Functions
TypeName ("solverControl")
solverControl (const solver &solver)
virtual ~solverControl ()=default
virtual const dictionary solverDict () const
virtual const dictionary solutionDict () const
bool printMaxMags () const
bool storeInitValues () const
label iter () const
label & averageIter ()
label averageIter () const
label averageStartIter () const
bool doAverageIter () const
bool useAveragedFields () const
bool average () const
Protected Member Functions
virtual bool read ()
Protected Attributes
const solver & solver_
bool printMaxMags_
label iter_
label averageIter_
label averageStartIter_
bool storeInitValues_
bool average_
Detailed Description
Base class for solver control classes.
Definition at line 45 of file solverControl.H.
Constructor & Destructor Documentation
solverControl()
solverControl (const solver & solver)
Definition at line 49 of file solverControl.C.
References solverControl::read().
~solverControl()
virtual ~solverControl () virtual default
Member Function Documentation
read()
bool read () protected virtual
Reimplemented in SIMPLEControlOpt, SIMPLEControl, and SIMPLEControlSingleRun.
Definition at line 34 of file solverControl.C.
References solverControl::averageStartIter_, solverControl::printMaxMags_, and solverControl::solutionDict().
Referenced by SIMPLEControl::read(), and solverControl::solverControl().
TypeName()
TypeName ("solverControl")
solverDict()
const Foam::dictionary solverDict () const inline virtual
Definition at line 26 of file solverControlI.H.
References solverControl::solver_.
solutionDict()
const Foam::dictionary solutionDict () const inline virtual
Definition at line 32 of file solverControlI.H.
Referenced by SIMPLEControl::dict(), and solverControl::read().
printMaxMags()
bool printMaxMags () const inline
Definition at line 38 of file solverControlI.H.
storeInitValues()
bool storeInitValues () const inline
Definition at line 44 of file solverControlI.H.
Referenced by incompressibleVars::restoreInitValues(), incompressibleVars::setInitFields(), and incompressibleVars::storeInitValues().
iter()
Foam::label iter () const inline
Definition at line 50 of file solverControlI.H.
averageIter() [1/2]
Foam::label & averageIter () inline
Definition at line 56 of file solverControlI.H.
Referenced by objective::accumulateJMean(), incompressibleVars::computeMeanFields(), incompressibleAdjointVars::computeMeanFields(), incompressibleVars::resetMeanFields(), and incompressibleAdjointVars::resetMeanFields().
averageIter() [2/2]
Foam::label averageIter () const inline
Definition at line 62 of file solverControlI.H.
averageStartIter()
Foam::label averageStartIter () const inline
Definition at line 68 of file solverControlI.H.
doAverageIter()
bool doAverageIter () const inline
Definition at line 74 of file solverControlI.H.
Referenced by objective::accumulateJMean(), incompressibleVars::computeMeanFields(), and incompressibleAdjointVars::computeMeanFields().
useAveragedFields()
bool useAveragedFields () const inline
Definition at line 87 of file solverControlI.H.
Referenced by incompressibleVars::p(), incompressibleVars::p(), incompressibleAdjointMeanFlowVars::pa(), incompressibleAdjointMeanFlowVars::pa(), incompressibleVars::phi(), incompressibleVars::phi(), incompressibleAdjointMeanFlowVars::phia(), incompressibleAdjointMeanFlowVars::phia(), incompressibleVars::U(), incompressibleVars::U(), incompressibleAdjointMeanFlowVars::Ua(), and incompressibleAdjointMeanFlowVars::Ua().
average()
bool average () const inline
Definition at line 100 of file solverControlI.H.
Referenced by incompressibleVars::computeMeanFields(), incompressibleAdjointMeanFlowVars::computeMeanFields(), incompressibleVars::correctNonTurbulentBoundaryConditions(), incompressibleVars::resetMeanFields(), incompressibleAdjointVars::resetMeanFields(), incompressibleVars::setMeanFields(), and incompressibleAdjointMeanFlowVars::setMeanFields().
Member Data Documentation
solver_
const solver& solver_ protected
Definition at line 52 of file solverControl.H.
Referenced by solverControl::solverDict().
printMaxMags_
bool printMaxMags_ protected
Definition at line 58 of file solverControl.H.
Referenced by solverControl::read().
iter_
label iter_ protected
Definition at line 64 of file solverControl.H.
averageIter_
label averageIter_ protected
Definition at line 67 of file solverControl.H.
averageStartIter_
label averageStartIter_ protected
Definition at line 70 of file solverControl.H.
Referenced by solverControl::read().
storeInitValues_
bool storeInitValues_ protected
Definition at line 76 of file solverControl.H.
average_
bool average_ protected
Definition at line 79 of file solverControl.H.
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/solvers/solverControl/solverControl/solverControl.H
src/optimisation/adjointOptimisation/adjoint/solvers/solverControl/solverControl/solverControl.C
src/optimisation/adjointOptimisation/adjoint/solvers/solverControl/solverControl/solverControlI.H