OpenFOAM: EddyDiffusivity< BasicTurbulenceModel > Class Template Reference
EddyDiffusivity< BasicTurbulenceModel > Class Template Reference
Templated abstract base class for single-phase compressible turbulence models.
#include <EddyDiffusivity.H>
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
EddyDiffusivity (const word &type, const alphaField &alpha, const volScalarField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~EddyDiffusivity ()=default
virtual bool read ()
virtual tmp< volScalarField > alphat () const
virtual tmp< scalarField > alphat (const label patchi) const
virtual tmp< volScalarField > kappaEff () const
virtual tmp< scalarField > kappaEff (const label patchi) const
virtual tmp< volScalarField > alphaEff () const
virtual tmp< scalarField > alphaEff (const label patchi) const
virtual void correctEnergyTransport ()
Protected Member Functions
virtual void correctNut ()
Protected Attributes
dimensionedScalar Prt_
volScalarField alphat_
Detailed Description
template<class BasicTurbulenceModel>
class Foam::EddyDiffusivity< BasicTurbulenceModel >
Templated abstract base class for single-phase compressible turbulence models.
Source files
EddyDiffusivity.H
EddyDiffusivity.C
Definition at line 47 of file EddyDiffusivity.H.
Member Typedef Documentation
alphaField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 72 of file EddyDiffusivity.H.
rhoField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 73 of file EddyDiffusivity.H.
transportModel
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 74 of file EddyDiffusivity.H.
Constructor & Destructor Documentation
EddyDiffusivity()
template<class BasicTurbulenceModel > EddyDiffusivity (const word & type, const alphaField & alpha, const volScalarField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName)
Definition at line 39 of file EddyDiffusivity.C.
~EddyDiffusivity()
template<class BasicTurbulenceModel > virtual ~EddyDiffusivity () virtual default
Member Function Documentation
correctNut()
template<class BasicTurbulenceModel > void correctNut () protected virtual
Definition at line 27 of file EddyDiffusivity.C.
References Foam::dimless, and nut.
read()
template<class BasicTurbulenceModel > bool read () virtual
Reimplemented in RASModel< EddyDiffusivity< compressible::turbulenceModel > >, RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > >, RASModel< EddyDiffusivity< ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > > > >, linearViscousStress< RASModel< EddyDiffusivity< compressible::turbulenceModel > > >, linearViscousStress< RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > > >, and linearViscousStress< RASModel< EddyDiffusivity< ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > > > > >.
Definition at line 84 of file EddyDiffusivity.C.
alphat() [1/2]
template<class BasicTurbulenceModel > virtual tmp< volScalarField > alphat () const inline virtual
Definition at line 103 of file EddyDiffusivity.H.
References EddyDiffusivity< BasicTurbulenceModel >::alphat_.
Referenced by EddyDiffusivity< BasicTurbulenceModel >::alphaEff(), EddyDiffusivity< BasicTurbulenceModel >::alphaEff(), EddyDiffusivity< BasicTurbulenceModel >::alphat(), EddyDiffusivity< BasicTurbulenceModel >::kappaEff(), and EddyDiffusivity< BasicTurbulenceModel >::kappaEff().
alphat() [2/2]
template<class BasicTurbulenceModel > virtual tmp< scalarField > alphat (const label patchi) const inline virtual
Definition at line 110 of file EddyDiffusivity.H.
References EddyDiffusivity< BasicTurbulenceModel >::alphat().
kappaEff() [1/2]
template<class BasicTurbulenceModel > virtual tmp< volScalarField > kappaEff () const inline virtual
Definition at line 117 of file EddyDiffusivity.H.
References EddyDiffusivity< BasicTurbulenceModel >::alphat().
kappaEff() [2/2]
template<class BasicTurbulenceModel > virtual tmp< scalarField > kappaEff (const label patchi) const inline virtual
Definition at line 124 of file EddyDiffusivity.H.
References EddyDiffusivity< BasicTurbulenceModel >::alphat().
alphaEff() [1/2]
template<class BasicTurbulenceModel > virtual tmp< volScalarField > alphaEff () const inline virtual
Definition at line 131 of file EddyDiffusivity.H.
References EddyDiffusivity< BasicTurbulenceModel >::alphat().
alphaEff() [2/2]
template<class BasicTurbulenceModel > virtual tmp< scalarField > alphaEff (const label patchi) const inline virtual
Definition at line 138 of file EddyDiffusivity.H.
References EddyDiffusivity< BasicTurbulenceModel >::alphat().
correctEnergyTransport()
template<class BasicTurbulenceModel > void correctEnergyTransport () virtual
Definition at line 98 of file EddyDiffusivity.C.
Member Data Documentation
Prt_
template<class BasicTurbulenceModel > dimensionedScalar Prt_ protected
Definition at line 58 of file EddyDiffusivity.H.
alphat_
template<class BasicTurbulenceModel > volScalarField alphat_ protected
Definition at line 62 of file EddyDiffusivity.H.
Referenced by EddyDiffusivity< BasicTurbulenceModel >::alphat().
The documentation for this class was generated from the following files:
src/TurbulenceModels/compressible/EddyDiffusivity/EddyDiffusivity.H
src/TurbulenceModels/compressible/EddyDiffusivity/EddyDiffusivity.C