OpenFOAM: jouleHeatingSource Class Reference
jouleHeatingSource Class Reference
Numerics » Finite volume Options » Sources
Evolves an electrical potential equation.
#include <jouleHeatingSource.H>
Public Member Functions
TypeName ("jouleHeatingSource")
jouleHeatingSource (const word &sourceName, const word &modelType, const dictionary &dict, const fvMesh &mesh)
jouleHeatingSource (const jouleHeatingSource &)=delete
void operator= (const jouleHeatingSource &)=delete
virtual ~jouleHeatingSource ()=default
virtual void addSup (const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldi)
virtual bool read (const dictionary &dict)
Public Member Functions inherited from option
TypeName ("option")
declareRunTimeSelectionTable (autoPtr, option, dictionary,(const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh),(name, modelType, dict, mesh))
option (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
autoPtr< option > clone () const
virtual ~option ()=default
const word & name () const noexcept
const fvMesh & mesh () const noexcept
const dictionary & coeffs () const noexcept
bool active () const noexcept
void setApplied (const label fieldi)
bool active (const bool on) noexcept
virtual bool isActive ()
virtual label applyToField (const word &fieldName) const
virtual void checkApplied () const
virtual void addSup (fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (fvMatrix< vector > &eqn, const label fieldi)
virtual void addSup (fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (fvMatrix< tensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< scalar > &eqn, const label fieldi)
virtual void constrain (fvMatrix< vector > &eqn, const label fieldi)
virtual void constrain (fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< tensor > &eqn, const label fieldi)
virtual void correct (volScalarField &field)
virtual void correct (volVectorField &field)
virtual void correct (volSphericalTensorField &field)
virtual void correct (volSymmTensorField &field)
virtual void correct (volTensorField &field)
virtual void postProcessSens (scalarField &sensField, const word &fieldName=word::null, const word &designVariablesName=word::null)
virtual void postProcessSens (vectorField &sensField, const word &fieldName=word::null, const word &designVariablesName=word::null)
virtual void postProcessSens (tensorField &sensField, const word &fieldName=word::null, const word &designVariablesName=word::null)
virtual void writeHeader (Ostream &) const
virtual void writeFooter (Ostream &) const
virtual void writeData (Ostream &) const
Additional Inherited Members
Static Public Member Functions inherited from option
static autoPtr< option > New (const word &name, const dictionary &dict, const fvMesh &mesh)
Public Attributes inherited from option
bool log
Protected Member Functions inherited from option
void resetApplied ()
Protected Attributes inherited from option
const word name_
const word modelType_
const fvMesh & mesh_
dictionary dict_
dictionary coeffs_
wordList fieldNames_
List< bool > applied_
bool active_
Detailed Description
Evolves an electrical potential equation.
where is electrical potential and is the electrical current.
To provide a Joule heating contribution according to:
Differential form of Joule heating - power per unit volume:
where is the current density and the electric field. If no magnetic field is present:
The electric field given by
Therefore:
Usage
Minimal example by using constant/fvOptions:
jouleHeatingSource1
{
    // Mandatory entries (unmodifiable)
    type                 jouleHeatingSource;
    // Mandatory entries (runtime modifiable)
    anisotropicElectricalConductivity true;
    // Optional entries (runtime modifiable)
    T       <Tname>;
    // Conditional mandatory entries (runtime modifiable)
        // when anisotropicElectricalConductivity=true
        coordinateSystem
        {
            origin  (0 0 0);
            e1      (1 0 0);
            e3      (0 0 1);
        }
    // Conditional optional entries (runtime modifiable)
        // when anisotropicElectricalConductivity=false
        // Specify the conductivity as a function of temperature
        // If not supplied, this will be read from the time directory
        sigma           table
        (
            (273        1e5)
            (1000       1e5)
        );
        // when anisotropicElectricalConductivity=true
        sigma           (31900 63800 127600);
        //sigma           table
        //(
        //    (0      (0 0 0))
        //    (1000   (127600 127600 127600))
        //);
    // Mandatory/Optional (inherited) entries
    ...
}
where the entries mean:
Property Description Type Reqd Dflt
type Type name: jouleHeatingSource word yes -
anisotropicElectricalConductivity
Flag to indicate that
if the electrical conductivity is anisotropic
bool yes -
T Name of operand temperature field word no T
sigma
Electrical conductivity as a function of temperature
table no -
coordinateSystem User-specified coordinate system coordSystem no -
The inherited entries are elaborated in:
fvOption.H
Note
anisotropicElectricalConductivity=true enables anisotropic (vectorial) electrical conductivity.
anisotropicElectricalConductivity=false enables isotropic (scalar) electrical conductivity.
The electrical conductivity can be specified using either:
If the sigma entry is present the electrical conductivity is specified as a function of temperature using a Function1 type.
If not present the sigma field will be read from file.
If the anisotropicElectricalConductivity flag is set to true, sigma should be specified as a vector quantity.
See also
Foam::Function1
Foam::coordSystem
Source files
jouleHeatingSource.H
jouleHeatingSource.C
jouleHeatingSourceTemplates.C
Definition at line 213 of file jouleHeatingSource.H.
Constructor & Destructor Documentation
jouleHeatingSource() [1/2]
jouleHeatingSource (const word & sourceName, const word & modelType, const dictionary & dict, const fvMesh & mesh)
Definition at line 97 of file jouleHeatingSource.C.
References dict, basicThermo::dictName, option::fieldNames_, fv(), option::mesh_, jouleHeatingSource::read(), option::resetApplied(), and List< T >::resize().
jouleHeatingSource() [2/2]
jouleHeatingSource (const jouleHeatingSource &) delete
~jouleHeatingSource()
virtual ~jouleHeatingSource () virtual default
Member Function Documentation
TypeName()
TypeName ("jouleHeatingSource")
operator=()
void operator= (const jouleHeatingSource &) delete
addSup()
void addSup (const volScalarField & rho, fvMatrix< scalar > & eqn, const label fieldi) virtual
Reimplemented from option.
Definition at line 140 of file jouleHeatingSource.C.
References DebugInfo, Foam::endl(), Foam::fvc::grad(), Foam::fvm::laplacian(), and Foam::name().
read()
bool read (const dictionary & dict) virtual
Reimplemented from option.
Definition at line 197 of file jouleHeatingSource.C.
References dict, Foam::endl(), UPtrList< T >::get(), Foam::Info, and option::read().
Referenced by jouleHeatingSource::jouleHeatingSource().
The documentation for this class was generated from the following files:
src/fvOptions/sources/derived/jouleHeatingSource/jouleHeatingSource.H
src/fvOptions/sources/derived/jouleHeatingSource/jouleHeatingSource.C
src/fvOptions/sources/derived/jouleHeatingSource/jouleHeatingSourceTemplates.C