OpenFOAM: sixDoFRigidBodyMotionState Class Reference
sixDoFRigidBodyMotionState Class Reference
Holds the motion state of sixDoF object. Wrapped up together to allow rapid scatter to other processors. The processors must all maintain exactly the same state data to avoid any drift or inconsistency.
#include <sixDoFRigidBodyMotionState.H>
Public Member Functions
sixDoFRigidBodyMotionState ()
sixDoFRigidBodyMotionState (const dictionary &dict)
const point & centreOfRotation () const
const tensor & Q () const
const vector & v () const
const vector & a () const
const vector & pi () const
const vector & tau () const
point & centreOfRotation ()
tensor & Q ()
vector & v ()
vector & a ()
vector & pi ()
vector & tau ()
void write (dictionary &dict) const
void write (Ostream &os) const
Friends
Istream & operator>> (Istream &, sixDoFRigidBodyMotionState &)
Ostream & operator<< (Ostream &, const sixDoFRigidBodyMotionState &)
Detailed Description
Holds the motion state of sixDoF object. Wrapped up together to allow rapid scatter to other processors. The processors must all maintain exactly the same state data to avoid any drift or inconsistency.
Source files
sixDoFRigidBodyMotionState.H
sixDoFRigidBodyMotionStateI.H
sixDoFRigidBodyMotionState.C
sixDoFRigidBodyMotionStateIO.C
Definition at line 61 of file sixDoFRigidBodyMotionState.H.
Constructor & Destructor Documentation
sixDoFRigidBodyMotionState() [1/2]
sixDoFRigidBodyMotionState ()
Definition at line 26 of file sixDoFRigidBodyMotionState.C.
sixDoFRigidBodyMotionState() [2/2]
sixDoFRigidBodyMotionState (const dictionary & dict)
Definition at line 37 of file sixDoFRigidBodyMotionState.C.
Member Function Documentation
centreOfRotation() [1/2]
const Foam::point & centreOfRotation () const inline
Definition at line 24 of file sixDoFRigidBodyMotionStateI.H.
Referenced by sixDoFSolver::centreOfRotation(), and sixDoFRigidBodyMotion::sixDoFRigidBodyMotion().
Q() [1/2]
const Foam::tensor & Q () const inline
Definition at line 30 of file sixDoFRigidBodyMotionStateI.H.
v() [1/2]
const Foam::vector & v () const inline
Definition at line 36 of file sixDoFRigidBodyMotionStateI.H.
a() [1/2]
const Foam::vector & a () const inline
Definition at line 42 of file sixDoFRigidBodyMotionStateI.H.
pi() [1/2]
const Foam::vector & pi () const inline
Definition at line 48 of file sixDoFRigidBodyMotionStateI.H.
tau() [1/2]
const Foam::vector & tau () const inline
Definition at line 54 of file sixDoFRigidBodyMotionStateI.H.
centreOfRotation() [2/2]
Foam::point & centreOfRotation () inline
Definition at line 60 of file sixDoFRigidBodyMotionStateI.H.
Q() [2/2]
Foam::tensor & Q () inline
Definition at line 66 of file sixDoFRigidBodyMotionStateI.H.
v() [2/2]
Foam::vector & v () inline
Definition at line 72 of file sixDoFRigidBodyMotionStateI.H.
a() [2/2]
Foam::vector & a () inline
Definition at line 78 of file sixDoFRigidBodyMotionStateI.H.
pi() [2/2]
Foam::vector & pi () inline
Definition at line 84 of file sixDoFRigidBodyMotionStateI.H.
tau() [2/2]
Foam::vector & tau () inline
Definition at line 90 of file sixDoFRigidBodyMotionStateI.H.
write() [1/2]
void write (dictionary & dict) const
Definition at line 26 of file sixDoFRigidBodyMotionStateIO.C.
References dict.
write() [2/2]
void write (Ostream & os) const
Definition at line 37 of file sixDoFRigidBodyMotionStateIO.C.
References os(), and Ostream::writeEntry().
Friends And Related Symbol Documentation
operator>>
Istream & operator>> (Istream & , sixDoFRigidBodyMotionState &) friend
operator<<
Ostream & operator<< (Ostream & , const sixDoFRigidBodyMotionState &) friend
The documentation for this class was generated from the following files:
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/sixDoFRigidBodyMotionState.H
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/sixDoFRigidBodyMotionState.C
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/sixDoFRigidBodyMotionStateI.H
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/sixDoFRigidBodyMotionStateIO.C