OpenFOAM: xmgraceWriter Class Reference
xmgraceWriter Class Reference
Output and agr file for xmgrace (http://plasma-gate.weizmann.ac.il/Grace/)
#include <xmgraceGraphWriter.H>
Public Member Functions
TypeNameNoDebug ("xmgr")
xmgraceWriter ()=default
~xmgraceWriter ()=default
word ext () const
void write (const graph &, Ostream &os) const
Public Member Functions inherited from graph::writer
TypeName ("writer")
declareRunTimeSelectionTable (autoPtr, writer, word,(),())
writer ()=default
virtual ~writer ()=default
Additional Inherited Members
Static Public Member Functions inherited from graph::writer
static autoPtr< writer > New (const word &writeFormat)
Protected Member Functions inherited from graph::writer
void writeXY (const scalarField &x, const scalarField &y, Ostream &) const
Detailed Description
Output and agr file for xmgrace (http://plasma-gate.weizmann.ac.il/Grace/)
Source files
xmgraceGraphWriter.H
xmgraceGraphWriter.C
Definition at line 50 of file xmgraceGraphWriter.H.
Constructor & Destructor Documentation
xmgraceWriter()
xmgraceWriter () default
~xmgraceWriter()
~xmgraceWriter () default
Member Function Documentation
TypeNameNoDebug()
TypeNameNoDebug ("xmgr")
ext()
word ext () const inline virtual
Implements graph::writer.
Definition at line 69 of file xmgraceGraphWriter.H.
write()
void write (const graph & g, Ostream & os) const virtual
Implements graph::writer.
Definition at line 42 of file xmgraceGraphWriter.C.
References Foam::endl(), forAllConstIters, g, Foam::nl, os(), and graph::writer::writeXY().
The documentation for this class was generated from the following files:
src/meshTools/graph/writers/xmgrace/xmgraceGraphWriter.H
src/meshTools/graph/writers/xmgrace/xmgraceGraphWriter.C