OpenFOAM: janafThermo< EquationOfState > Class Template Reference
janafThermo< EquationOfState > Class Template Reference
Thermophysical models » Specie » Thermodynamics
JANAF tables based thermodynamics package templated into the equation of state.
#include <janafThermo.H>
Public Types
typedef FixedList< scalar, nCoeffs_ > coeffArray
Public Member Functions
janafThermo (const EquationOfState &st, const scalar Tlow, const scalar Thigh, const scalar Tcommon, const coeffArray &highCpCoeffs, const coeffArray &lowCpCoeffs, const bool convertCoeffs=false)
janafThermo (const dictionary &dict)
janafThermo (const word &, const janafThermo &)
scalar limit (const scalar T) const
scalar Tlow () const
scalar Thigh () const
scalar Tcommon () const
const coeffArray & highCpCoeffs () const
const coeffArray & lowCpCoeffs () const
scalar Cp (const scalar p, const scalar T) const
scalar Ha (const scalar p, const scalar T) const
scalar Hs (const scalar p, const scalar T) const
scalar Hc () const
scalar S (const scalar p, const scalar T) const
scalar Gstd (const scalar T) const
scalar dCpdT (const scalar p, const scalar T) const
void write (Ostream &os) const
void operator+= (const janafThermo &)
Static Public Member Functions
static word typeName ()
Static Public Attributes
static constexpr int nCoeffs_ = 7
Friends
janafThermo operator+ (const janafThermo &, const janafThermo &)
janafThermo operator* (const scalar, const janafThermo &)
janafThermo operator== (const janafThermo &, const janafThermo &)
Ostream & operator<< (Ostream &, const janafThermo &)
Detailed Description
template<class EquationOfState>
class Foam::janafThermo< EquationOfState >
JANAF tables based thermodynamics package templated into the equation of state.
Source files
janafThermo.H
janafThermoI.H
janafThermo.C
Definition at line 87 of file janafThermo.H.
Member Typedef Documentation
coeffArray
template<class EquationOfState > typedef FixedList<scalar, nCoeffs_> coeffArray
Definition at line 96 of file janafThermo.H.
Constructor & Destructor Documentation
janafThermo() [1/3]
template<class EquationOfState > janafThermo (const EquationOfState & st, const scalar Tlow, const scalar Thigh, const scalar Tcommon, const coeffArray & highCpCoeffs, const coeffArray & lowCpCoeffs, const bool convertCoeffs = false) inline
janafThermo() [2/3]
template<class EquationOfState > janafThermo (const dictionary & dict)
Definition at line 55 of file janafThermo.C.
References janafThermo< EquationOfState >::nCoeffs_, and R.
janafThermo() [3/3]
template<class EquationOfState > janafThermo (const word & name, const janafThermo< EquationOfState > & jt) inline
Definition at line 84 of file janafThermoI.H.
References janafThermo< EquationOfState >::nCoeffs_.
Member Function Documentation
typeName()
template<class EquationOfState > static word typeName () inline static
Definition at line 145 of file janafThermo.H.
limit()
template<class EquationOfState > Foam::scalar limit (const scalar T) const inline
Definition at line 106 of file janafThermoI.H.
References Foam::clamp(), Foam::endl(), T, and WarningInFunction.
Tlow()
template<class EquationOfState > Foam::scalar Tlow () const inline
Definition at line 127 of file janafThermoI.H.
Thigh()
template<class EquationOfState > Foam::scalar Thigh () const inline
Definition at line 134 of file janafThermoI.H.
Tcommon()
template<class EquationOfState > Foam::scalar Tcommon () const inline
Definition at line 141 of file janafThermoI.H.
highCpCoeffs()
template<class EquationOfState > const Foam::janafThermo< EquationOfState >::coeffArray & highCpCoeffs () const inline
Definition at line 149 of file janafThermoI.H.
lowCpCoeffs()
template<class EquationOfState > const Foam::janafThermo< EquationOfState >::coeffArray & lowCpCoeffs () const inline
Definition at line 157 of file janafThermoI.H.
Cp()
template<class EquationOfState > Foam::scalar Cp (const scalar p, const scalar T) const inline
Definition at line 164 of file janafThermoI.H.
References p, and T.
Ha()
template<class EquationOfState > Foam::scalar Ha (const scalar p, const scalar T) const inline
Definition at line 178 of file janafThermoI.H.
References p, and T.
Hs()
template<class EquationOfState > Foam::scalar Hs (const scalar p, const scalar T) const inline
Definition at line 194 of file janafThermoI.H.
References Ha(), p, and T.
Hc()
template<class EquationOfState > Foam::scalar Hc () const inline
Definition at line 205 of file janafThermoI.H.
References Foam::constant::thermodynamic::Tstd.
S()
template<class EquationOfState > Foam::scalar S (const scalar p, const scalar T) const inline
Definition at line 219 of file janafThermoI.H.
References Foam::log(), p, and T.
Gstd()
template<class EquationOfState > Foam::scalar Gstd (const scalar T) const inline
Definition at line 235 of file janafThermoI.H.
References Foam::log(), and T.
dCpdT()
template<class EquationOfState > Foam::scalar dCpdT (const scalar p, const scalar T) const inline
Definition at line 254 of file janafThermoI.H.
References T.
write()
template<class EquationOfState > void write (Ostream & os) const
Definition at line 78 of file janafThermo.C.
References Ostream::beginBlock(), Ostream::endBlock(), os(), R, and Ostream::writeEntry().
operator+=()
template<class EquationOfState > void operator+= (const janafThermo< EquationOfState > &) inline
Definition at line 268 of file janafThermoI.H.
References Foam::equal(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::mag(), Foam::max(), Foam::min(), Foam::name(), UPtrList< T >::size(), and Y.
Friends And Related Symbol Documentation
operator+
template<class EquationOfState > janafThermo operator+ (const janafThermo< EquationOfState > & , const janafThermo< EquationOfState > &) friend
operator*
template<class EquationOfState > janafThermo operator* (const scalar , const janafThermo< EquationOfState > &) friend
operator==
template<class EquationOfState > janafThermo operator== (const janafThermo< EquationOfState > & , const janafThermo< EquationOfState > &) friend
operator<<
template<class EquationOfState > Ostream & operator<< (Ostream & , const janafThermo< EquationOfState > &) friend
Member Data Documentation
nCoeffs_
template<class EquationOfState > constexpr int nCoeffs_ = 7 static constexpr
Definition at line 95 of file janafThermo.H.
Referenced by janafThermo< EquationOfState >::janafThermo(), and janafThermo< EquationOfState >::janafThermo().
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/thermo/janaf/janafThermo.H
src/thermophysicalModels/specie/thermo/janaf/janafThermo.C
src/thermophysicalModels/specie/thermo/janaf/janafThermoI.H