OpenFOAM: UOPstreamBase Class Reference
UOPstreamBase Class Reference
Base class for output inter-processor communications stream (ie, parallel streams). Not to be used directly, thus contructors are protected.
#include <UOPstream.H>
Public Member Functions
virtual ~UOPstreamBase ()
virtual ios_base::fmtflags flags () const
virtual bool write (const token &tok)
virtual Ostream & write (const char c)
virtual Ostream & write (const char *str)
virtual Ostream & write (const word &str)
virtual Ostream & write (const string &str)
virtual Ostream & writeQuoted (const std::string &str, const bool quoted=true)
virtual Ostream & write (const int32_t val)
virtual Ostream & write (const int64_t val)
virtual Ostream & write (const float val)
virtual Ostream & write (const double val)
virtual Ostream & write (const char *data, std::streamsize count)
virtual Ostream & writeRaw (const char *data, std::streamsize count)
virtual bool beginRawWrite (std::streamsize count)
virtual bool endRawWrite ()
virtual void indent ()
virtual void flush ()
virtual void endl ()
virtual char fill () const
virtual char fill (const char)
virtual int width () const
virtual int width (const int)
virtual int precision () const
virtual int precision (const int)
virtual void rewind ()
virtual ios_base::fmtflags flags (const ios_base::fmtflags)
void print (Ostream &os) const
Public Member Functions inherited from UPstream
ClassName ("UPstream")
UPstream (const commsTypes commsType) noexcept
commsTypes commsType () const noexcept
commsTypes commsType (const commsTypes ct) noexcept
template<class T >
Foam::List< T > allGatherValues (const T &localValue, const label comm)
template<class T >
Foam::List< T > listGatherValues (const T &localValue, const label comm)
Public Member Functions inherited from Ostream
Ostream (const Ostream &)=default
virtual ~Ostream ()=default
Ostream (IOstreamOption streamOpt=IOstreamOption())
Ostream (IOstreamOption::streamFormat fmt, IOstreamOption::compressionType cmp=IOstreamOption::UNCOMPRESSED)
virtual Ostream & write (const keyType &kw)
unsigned short indentSize () const noexcept
unsigned short indentSize (unsigned short val) noexcept
unsigned short indentLevel () const noexcept
unsigned short indentLevel (unsigned short val) noexcept
void incrIndent () noexcept
void decrIndent ()
virtual Ostream & writeKeyword (const keyType &kw)
virtual Ostream & beginBlock (const keyType &kw)
virtual Ostream & beginBlock ()
virtual Ostream & endBlock ()
virtual Ostream & endEntry ()
template<class T >
Ostream & writeEntry (const keyType &key, const T &value)
template<class T >
Ostream & writeEntryIfDifferent (const word &key, const T &value1, const T &value2)
Ostream & operator() () const
unsigned short & indentLevel () noexcept
unsigned short & indentSize () noexcept
Public Member Functions inherited from IOstream
IOstream (const IOstream &)=default
virtual ~IOstream ()=default
IOstream (IOstreamOption streamOpt=IOstreamOption())
IOstream (IOstreamOption::streamFormat fmt, IOstreamOption::versionNumber ver, IOstreamOption::compressionType cmp=IOstreamOption::UNCOMPRESSED)
virtual const fileName & name () const
fileName relativeName () const
virtual bool check (const char *operation) const
bool fatalCheck (const char *operation) const
bool opened () const noexcept
bool closed () const noexcept
bool good () const noexcept
bool eof () const noexcept
bool fail () const noexcept
bool bad () const noexcept
operator bool () const noexcept
bool operator! () const noexcept
unsigned labelByteSize () const noexcept
unsigned scalarByteSize () const noexcept
void setLabelByteSize (unsigned nbytes) noexcept
void setScalarByteSize (unsigned nbytes) noexcept
template<class T = label>
std::enable_if< std::is_integral< T >::value, bool >::type checkLabelSize () const noexcept
template<class T = scalar>
std::enable_if< std::is_floating_point< T >::value, bool >::type checkScalarSize () const noexcept
label lineNumber () const noexcept
label & lineNumber () noexcept
label lineNumber (const label num) noexcept
void setEof () noexcept
void setFail () noexcept
void setBad ()
ios_base::fmtflags setf (const ios_base::fmtflags f)
ios_base::fmtflags setf (const ios_base::fmtflags f, const ios_base::fmtflags mask)
void unsetf (const ios_base::fmtflags f)
void print (Ostream &os, const int streamState) const
InfoProxy< IOstream > info () const noexcept
Public Member Functions inherited from IOstreamOption
constexpr IOstreamOption (streamFormat fmt=streamFormat::ASCII, compressionType comp=compressionType::UNCOMPRESSED) noexcept
constexpr IOstreamOption (streamFormat fmt, compressionType comp, versionNumber ver) noexcept
constexpr IOstreamOption (streamFormat fmt, versionNumber ver, compressionType comp=compressionType::UNCOMPRESSED) noexcept
IOstreamOption (const IOstreamOption &opt, streamFormat fmt) noexcept
streamFormat format () const noexcept
streamFormat format (const streamFormat fmt) noexcept
streamFormat format (const word &formatName)
compressionType compression () const noexcept
compressionType compression (const compressionType comp) noexcept
compressionType compression (const word &compName)
versionNumber version () const noexcept
versionNumber version (const versionNumber ver) noexcept
versionNumber version (const token &tok)
Protected Member Functions
UOPstreamBase (const UPstream::commsTypes commsType, const int toProcNo, DynamicList< char > &sendBuf, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm, const bool sendAtDestruct=true, IOstreamOption::streamFormat fmt=IOstreamOption::BINARY)
UOPstreamBase (const int toProcNo, PstreamBuffers &buffers)
UOPstreamBase (DynamicList< char > &sendBuf, IOstreamOption::streamFormat fmt)
Protected Member Functions inherited from IOstream
void setOpened () noexcept
void setClosed () noexcept
void setState (std::ios_base::iostate state) noexcept
void setGood () noexcept
Protected Attributes
const int toProcNo_
const int tag_
const int comm_
const bool sendAtDestruct_
DynamicList< char > & sendBuf_
Protected Attributes inherited from Ostream
unsigned short indentSize_ = 4
unsigned short indentLevel_ = 0
Protected Attributes inherited from IOstream
std::ios_base::iostate ioState_
streamAccess openClosed_
unsigned char sizeofLabel_
unsigned char sizeofScalar_
label lineNumber_
Additional Inherited Members
Public Types inherited from UPstream
enum class commsTypes : char { blocking , scheduled , nonBlocking }
enum class sendModes : char { normal , sync }
typedef IntRange< int > rangeType
Public Types inherited from IOstream
enum streamAccess : char { CLOSED = 0 , OPENED }
Public Types inherited from IOstreamOption
enum streamFormat : char { ASCII = 0 , BINARY }
enum compressionType : char { UNCOMPRESSED = 0 , COMPRESSED }
enum appendType : char { NON_APPEND = 0 , APPEND }
enum atomicType : char { NON_ATOMIC = 0 , ATOMIC }
Static Public Member Functions inherited from UPstream
static constexpr label commGlobal () noexcept
static constexpr label commSelf () noexcept
static label commWorld () noexcept
static label commWorld (const label communicator) noexcept
static label commWarn (const label communicator) noexcept
static label nComms () noexcept
static void printCommTree (const label communicator)
static label commIntraHost ()
static label commInterHost ()
static bool hasHostComms ()
static void clearHostComms ()
static label allocateCommunicator (const label parent, const labelRange &subRanks, const bool withComponents=true)
static label allocateCommunicator (const label parent, const labelUList &subRanks, const bool withComponents=true)
static void freeCommunicator (const label communicator, const bool withComponents=true)
static label allocateInterHostCommunicator (const label parentCommunicator=worldComm)
static label allocateIntraHostCommunicator (const label parentCommunicator=worldComm)
static int baseProcNo (label comm, int procID)
static label procNo (const label comm, const int baseProcID)
static label procNo (const label comm, const label currentComm, const int currentProcID)
static void addValidParOptions (HashTable< string > &validParOptions)
static bool init (int &argc, char **&argv, const bool needsThread)
static bool initNull ()
static void barrier (const label communicator, UPstream::Request *req=nullptr)
static std::pair< int, int > probeMessage (const UPstream::commsTypes commsType, const int fromProcNo, const int tag=UPstream::msgType(), const label communicator=worldComm)
static label nRequests () noexcept
static void resetRequests (const label n)
static void addRequest (UPstream::Request &req)
static void cancelRequest (const label i)
static void cancelRequest (UPstream::Request &req)
static void cancelRequests (UList< UPstream::Request > &requests)
static void freeRequest (UPstream::Request &req)
static void freeRequests (UList< UPstream::Request > &requests)
static void waitRequests (const label pos, label len=-1)
static void waitRequests (UList< UPstream::Request > &requests)
static bool waitAnyRequest (const label pos, label len=-1)
static bool waitSomeRequests (const label pos, DynamicList< int > *indices=nullptr)
static label waitAnyRequest (UList< UPstream::Request > &requests)
static void waitRequest (const label i)
static void waitRequest (UPstream::Request &req)
static bool finishedRequest (const label i)
static bool finishedRequest (UPstream::Request &req)
static bool finishedRequests (const label pos, label len=-1)
static bool finishedRequests (UList< UPstream::Request > &requests)
static bool finishedRequestPair (label &req0, label &req1)
static void waitRequestPair (label &req0, label &req1)
static bool parRun (const bool on) noexcept
static bool & parRun () noexcept
static bool haveThreads () noexcept
static constexpr int masterNo () noexcept
static label nProcs (const label communicator=worldComm)
static int myProcNo (const label communicator=worldComm)
static bool master (const label communicator=worldComm)
static bool is_rank (const label communicator=worldComm)
static bool is_subrank (const label communicator=worldComm)
static bool is_parallel (const label communicator=worldComm)
static label parent (const label communicator)
static List< int > & procID (const label communicator)
static const wordList & allWorlds () noexcept
static const labelList & worldIDs () noexcept
static label myWorldID ()
static const word & myWorld ()
static rangeType allProcs (const label communicator=worldComm)
static rangeType subProcs (const label communicator=worldComm)
static const List< commsStruct > & linearCommunication (const label communicator=worldComm)
static const List< commsStruct > & treeCommunication (const label communicator=worldComm)
static const List< commsStruct > & whichCommunication (const label communicator=worldComm)
static int & msgType () noexcept
static void shutdown (int errNo=0)
static void abort ()
static void exit (int errNo=1)
static void allToAll (const UList< int32_t > &sendData, UList< int32_t > &recvData, const label communicator=worldComm)
static void allToAll (const UList< int64_t > &sendData, UList< int64_t > &recvData, const label communicator=worldComm)
static void allToAllConsensus (const UList< int32_t > &sendData, UList< int32_t > &recvData, const int tag, const label communicator=worldComm)
static void allToAllConsensus (const UList< int64_t > &sendData, UList< int64_t > &recvData, const int tag, const label communicator=worldComm)
static void allToAllConsensus (const Map< int32_t > &sendData, Map< int32_t > &recvData, const int tag, const label communicator=worldComm)
static void allToAllConsensus (const Map< int64_t > &sendData, Map< int64_t > &recvData, const int tag, const label communicator=worldComm)
static void mpiGather (const char *sendData, char *recvData, int count, const label communicator=worldComm)
Receive identically-sized char data from all ranks.
static void mpiScatter (const char *sendData, char *recvData, int count, const label communicator=worldComm)
Send identically-sized char data to all ranks.
static void mpiAllGather (char *allData, int count, const label communicator=worldComm)
Gather/scatter identically-sized char data.
static void gather (const char *sendData, int sendCount, char *recvData, const UList< int > &recvCounts, const UList< int > &recvOffsets, const label communicator=worldComm)
Receive variable length char data from all ranks.
static void scatter (const char *sendData, const UList< int > &sendCounts, const UList< int > &sendOffsets, char *recvData, int recvCount, const label communicator=worldComm)
Send variable length char data to all ranks.
static void gather (const int32_t *sendData, int sendCount, int32_t *recvData, const UList< int > &recvCounts, const UList< int > &recvOffsets, const label communicator=worldComm)
Receive variable length int32_t data from all ranks.
static void scatter (const int32_t *sendData, const UList< int > &sendCounts, const UList< int > &sendOffsets, int32_t *recvData, int recvCount, const label communicator=worldComm)
Send variable length int32_t data to all ranks.
static void gather (const int64_t *sendData, int sendCount, int64_t *recvData, const UList< int > &recvCounts, const UList< int > &recvOffsets, const label communicator=worldComm)
Receive variable length int64_t data from all ranks.
static void scatter (const int64_t *sendData, const UList< int > &sendCounts, const UList< int > &sendOffsets, int64_t *recvData, int recvCount, const label communicator=worldComm)
Send variable length int64_t data to all ranks.
static void gather (const uint32_t *sendData, int sendCount, uint32_t *recvData, const UList< int > &recvCounts, const UList< int > &recvOffsets, const label communicator=worldComm)
Receive variable length uint32_t data from all ranks.
static void scatter (const uint32_t *sendData, const UList< int > &sendCounts, const UList< int > &sendOffsets, uint32_t *recvData, int recvCount, const label communicator=worldComm)
Send variable length uint32_t data to all ranks.
static void gather (const uint64_t *sendData, int sendCount, uint64_t *recvData, const UList< int > &recvCounts, const UList< int > &recvOffsets, const label communicator=worldComm)
Receive variable length uint64_t data from all ranks.
static void scatter (const uint64_t *sendData, const UList< int > &sendCounts, const UList< int > &sendOffsets, uint64_t *recvData, int recvCount, const label communicator=worldComm)
Send variable length uint64_t data to all ranks.
static void gather (const float *sendData, int sendCount, float *recvData, const UList< int > &recvCounts, const UList< int > &recvOffsets, const label communicator=worldComm)
Receive variable length float data from all ranks.
static void scatter (const float *sendData, const UList< int > &sendCounts, const UList< int > &sendOffsets, float *recvData, int recvCount, const label communicator=worldComm)
Send variable length float data to all ranks.
static void gather (const double *sendData, int sendCount, double *recvData, const UList< int > &recvCounts, const UList< int > &recvOffsets, const label communicator=worldComm)
Receive variable length double data from all ranks.
static void scatter (const double *sendData, const UList< int > &sendCounts, const UList< int > &sendOffsets, double *recvData, int recvCount, const label communicator=worldComm)
Send variable length double data to all ranks.
template<class T >
static List< T > allGatherValues (const T &localValue, const label communicator=worldComm)
template<class T >
static List< T > listGatherValues (const T &localValue, const label communicator=worldComm)
template<class T >
static T listScatterValues (const UList< T > &allValues, const label communicator=worldComm)
static bool broadcast (char *buf, const std::streamsize bufSize, const label communicator, const int rootProcNo=masterNo())
static void reduceAnd (bool &value, const label communicator=worldComm)
static void reduceOr (bool &value, const label communicator=worldComm)
static void waitRequests ()
static constexpr int firstSlave () noexcept
static int lastSlave (const label communicator=worldComm)
Static Public Member Functions inherited from IOstream
static unsigned int defaultPrecision () noexcept
static unsigned int defaultPrecision (unsigned int prec) noexcept
Static Public Member Functions inherited from IOstreamOption
static streamFormat formatEnum (const word &formatName, const streamFormat deflt=streamFormat::ASCII)
static streamFormat formatEnum (const word &key, const dictionary &dict, const streamFormat deflt=streamFormat::ASCII)
static compressionType compressionEnum (const word &compName, const compressionType deflt=compressionType::UNCOMPRESSED)
static compressionType compressionEnum (const word &key, const dictionary &dict, const compressionType deflt=compressionType::UNCOMPRESSED)
Static Public Attributes inherited from UPstream
static const Enum< commsTypes > commsTypeNames
static bool floatTransfer
static int nProcsSimpleSum
static int nProcsNonblockingExchange
static int nPollProcInterfaces
static commsTypes defaultCommsType
static int maxCommsSize
static int tuning_NBX_
static const int mpiBufferSize
static label worldComm
static label warnComm
Static Public Attributes inherited from IOstream
static unsigned int precision_
Static Public Attributes inherited from IOstreamOption
static const Enum< streamFormat > formatNames
static const versionNumber currentVersion
Static Protected Attributes inherited from Ostream
static constexpr const unsigned short entryIndentation_ = 16
Static Protected Attributes inherited from IOstream
static fileName staticName_
Detailed Description
Base class for output inter-processor communications stream (ie, parallel streams). Not to be used directly, thus contructors are protected.
Source files
UOPstream.H
UOPstreamBase.C
Definition at line 54 of file UOPstream.H.
Constructor & Destructor Documentation
UOPstreamBase() [1/3]
UOPstreamBase (const UPstream::commsTypes commsType, const int toProcNo, DynamicList< char > & sendBuf, const int tag = UPstream::msgType(), const label comm = UPstream::worldComm, const bool sendAtDestruct = true, IOstreamOption::streamFormat fmt = IOstreamOption::BINARY) protected
Definition at line 127 of file UOPstreamBase.C.
References IOstream::setGood(), and IOstream::setOpened().
UOPstreamBase() [2/3]
UOPstreamBase (const int toProcNo, PstreamBuffers & buffers) protected
Definition at line 151 of file UOPstreamBase.C.
UOPstreamBase() [3/3]
UOPstreamBase (DynamicList< char > & sendBuf, IOstreamOption::streamFormat fmt) protected
Definition at line 166 of file UOPstreamBase.C.
~UOPstreamBase()
~UOPstreamBase () virtual
Definition at line 188 of file UOPstreamBase.C.
Member Function Documentation
flags() [1/2]
virtual ios_base::fmtflags flags () const inline virtual
Implements IOstream.
Definition at line 143 of file UOPstream.H.
write() [1/10]
bool write (const token & tok) virtual
Implements Ostream.
Reimplemented in UOPstream, and UOPBstream.
Definition at line 194 of file UOPstreamBase.C.
References token::DIRECTIVE, token::EXPRESSION, token::FLAG, token::STRING, token::VARIABLE, token::VERBATIM, and token::WORD.
write() [2/10]
Foam::Ostream & write (const char c) virtual
Implements Ostream.
Reimplemented in UOPstream, and UOPBstream.
Definition at line 238 of file UOPstreamBase.C.
References Foam::isspace().
write() [3/10]
Foam::Ostream & write (const char * str) virtual
Implements Ostream.
Reimplemented in UOPstream, and UOPBstream.
Definition at line 249 of file UOPstreamBase.C.
References UPtrList< T >::size(), and write().
write() [4/10]
Foam::Ostream & write (const word & str) virtual
Implements Ostream.
Reimplemented in UOPstream, and UOPBstream.
Definition at line 266 of file UOPstreamBase.C.
References token::WORD.
write() [5/10]
Foam::Ostream & write (const string & str) virtual
Implements Ostream.
Reimplemented in UOPstream, and UOPBstream.
Definition at line 275 of file UOPstreamBase.C.
References token::STRING.
writeQuoted()
Foam::Ostream & writeQuoted (const std::string & str, const bool quoted = true) virtual
Implements Ostream.
Definition at line 284 of file UOPstreamBase.C.
References token::STRING, and token::WORD.
write() [6/10]
Foam::Ostream & write (const int32_t val) virtual
Implements Ostream.
Reimplemented in UOPstream, and UOPBstream.
Definition at line 304 of file UOPstreamBase.C.
References token::LABEL.
write() [7/10]
Foam::Ostream & write (const int64_t val) virtual
Implements Ostream.
Reimplemented in UOPstream, and UOPBstream.
Definition at line 312 of file UOPstreamBase.C.
References token::LABEL.
write() [8/10]
Foam::Ostream & write (const float val) virtual
Implements Ostream.
Reimplemented in UOPstream, and UOPBstream.
Definition at line 320 of file UOPstreamBase.C.
References token::FLOAT.
write() [9/10]
Foam::Ostream & write (const double val) virtual
Implements Ostream.
Reimplemented in UOPstream, and UOPBstream.
Definition at line 328 of file UOPstreamBase.C.
References token::DOUBLE.
write() [10/10]
Foam::Ostream & write (const char * data, std::streamsize count) virtual
Implements Ostream.
Reimplemented in UOPstream, and UOPBstream.
Definition at line 336 of file UOPstreamBase.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and format().
writeRaw()
Foam::Ostream & writeRaw (const char * data, std::streamsize count) virtual
Implements Ostream.
Definition at line 356 of file UOPstreamBase.C.
beginRawWrite()
bool beginRawWrite (std::streamsize count) virtual
Implements Ostream.
Definition at line 372 of file UOPstreamBase.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and format().
endRawWrite()
virtual bool endRawWrite () inline virtual
Implements Ostream.
Definition at line 200 of file UOPstream.H.
indent()
virtual void indent () inline virtual
Implements Ostream.
Definition at line 206 of file UOPstream.H.
flush()
virtual void flush () inline virtual
Implements Ostream.
Definition at line 213 of file UOPstream.H.
endl()
virtual void endl () inline virtual
Implements Ostream.
Definition at line 217 of file UOPstream.H.
fill() [1/2]
virtual char fill () const inline virtual
Implements Ostream.
Definition at line 222 of file UOPstream.H.
fill() [2/2]
virtual char fill (const char) inline virtual
Implements Ostream.
Definition at line 228 of file UOPstream.H.
width() [1/2]
virtual int width () const inline virtual
Implements Ostream.
Definition at line 234 of file UOPstream.H.
width() [2/2]
virtual int width (const int) inline virtual
Implements Ostream.
Definition at line 241 of file UOPstream.H.
precision() [1/2]
virtual int precision () const inline virtual
Implements Ostream.
Definition at line 247 of file UOPstream.H.
precision() [2/2]
virtual int precision (const int) inline virtual
Implements Ostream.
Definition at line 254 of file UOPstream.H.
rewind()
void rewind () virtual
//- The current put position (tellp) in the buffer label pos() const;
Foam::label Foam::UOPstreamBase::pos() const { return sendBuf_.size(); }
Definition at line 400 of file UOPstreamBase.C.
References PtrList< T >::clear().
flags() [2/2]
virtual ios_base::fmtflags flags (const ios_base::fmtflags) inline virtual
Implements IOstream.
Definition at line 269 of file UOPstream.H.
print()
void print (Ostream & os) const virtual
Reimplemented from IOstream.
Definition at line 408 of file UOPstreamBase.C.
References Foam::endl(), and os().
Member Data Documentation
toProcNo_
const int toProcNo_ protected
Definition at line 91 of file UOPstream.H.
tag_
const int tag_ protected
Definition at line 94 of file UOPstream.H.
comm_
const int comm_ protected
Definition at line 97 of file UOPstream.H.
sendAtDestruct_
const bool sendAtDestruct_ protected
Definition at line 100 of file UOPstream.H.
sendBuf_
DynamicList<char>& sendBuf_ protected
Definition at line 103 of file UOPstream.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOstreams/Pstreams/UOPstream.H
src/OpenFOAM/db/IOstreams/Pstreams/UOPstreamBase.C