OpenFOAM: FilterField Class Reference
FilterField Class Reference
The FilterField helper class provides a multi-sweep median filter for a Field of data associated with a geometric point cloud.
#include <MappedFileFilterField.H>
Public Types
enum RBF_type { RBF_linear , RBF_quadratic }
Public Member Functions
ClassName ("filterField")
FilterField () noexcept=default
FilterField (const pointField &points, const scalar radius, const RBF_type interp=RBF_type::RBF_linear)
FilterField (const meshedSurface &geom, const scalar radius, const bool relative=false, const RBF_type interp=RBF_type::RBF_linear)
void reset ()
void reset (const pointField &points, const scalar radius, const RBF_type interp=RBF_type::RBF_linear)
void reset (const meshedSurface &geom, const scalar radius, const bool relative=false, const RBF_type interp=RBF_type::RBF_linear)
template<class Type >
tmp< Field< Type > > evaluate (const tmp< Field< Type > > &tinput, const label nSweeps) const
template<class Type >
Foam::tmp< Foam::Field< Type > > evaluate (const tmp< Field< Type > > &tinput, const label nSweeps) const
Detailed Description
The FilterField helper class provides a multi-sweep median filter for a Field of data associated with a geometric point cloud.
The points can be freestanding or the faceCentres (or points) of a meshedSurface, for example.
Using an initial specified search radius, the nearest point neighbours are gathered and addressing/weights are built for them. This currently uses an area-weighted, linear RBF interpolator with provision for quadratic RBF interpolator etc.
After the weights and addressing are established, the evaluate() method can be called to apply a median filter to data fields, with a specified number of sweeps.
Note
When handling large search radii and/or an extensive number of filter sweeps, compiling with openmp can yield some speedup.
Source files
MappedFileFilterField.H
MappedFileFilterField.C
MappedFileFilterFieldTemplates.C
Definition at line 70 of file MappedFileFilterField.H.
Member Enumeration Documentation
RBF_type
enum RBF_type
Enumerator
RBF_linear
RBF_quadratic
Definition at line 77 of file MappedFileFilterField.H.
Constructor & Destructor Documentation
FilterField() [1/3]
FilterField () default noexcept
FilterField() [2/3]
FilterField (const pointField & points, const scalar radius, const RBF_type interp = RBF_type::RBF_linear)
Definition at line 238 of file MappedFileFilterField.C.
References points.
FilterField() [3/3]
FilterField (const meshedSurface & geom, const scalar radius, const bool relative = false, const RBF_type interp = RBF_type::RBF_linear)
Definition at line 249 of file MappedFileFilterField.C.
Member Function Documentation
ClassName()
ClassName ("filterField")
reset() [1/3]
void reset ()
Definition at line 263 of file MappedFileFilterField.C.
References PtrList< T >::clear().
reset() [2/3]
void reset (const pointField & points, const scalar radius, const RBF_type interp = RBF_type::RBF_linear)
Definition at line 270 of file MappedFileFilterField.C.
References Foam::createTree(), Foam::endl(), Foam::linearWeight(), Foam::nl, points, Foam::Pout, Foam::quadraticWeight(), and Foam::sqr().
reset() [3/3]
void reset (const meshedSurface & geom, const scalar radius, const bool relative = false, const RBF_type interp = RBF_type::RBF_linear)
Definition at line 310 of file MappedFileFilterField.C.
References Foam::createTree(), Foam::endl(), Foam::linearWeight(), Foam::nl, Foam::Pout, Foam::quadraticWeight(), and Foam::sqr().
evaluate() [1/2]
template<class Type > tmp< Field< Type > > evaluate (const tmp< Field< Type > > & tinput, const label nSweeps) const
evaluate() [2/2]
template<class Type > Foam::tmp< Foam::Field< Type > > evaluate (const tmp< Field< Type > > & tinput, const label nSweeps) const
Definition at line 28 of file MappedFileFilterFieldTemplates.C.
References PtrList< T >::clear(), UPtrList< T >::empty(), Foam::endl(), forAll, Foam::input(), Foam::New(), nPoints, Foam::output(), UPtrList< T >::size(), UList< T >::size(), UPtrList< T >::swap(), WarningInFunction, and Foam::Zero.
The documentation for this class was generated from the following files:
src/meshTools/PatchFunction1/MappedFile/MappedFileFilterField.H
src/meshTools/PatchFunction1/MappedFile/MappedFileFilterField.C
src/meshTools/PatchFunction1/MappedFile/MappedFileFilterFieldTemplates.C