OpenFOAM: MRFZoneList Class Reference
MRFZoneList Class Reference
List container for MRF zomes.
#include <MRFZoneList.H>
Public Member Functions
MRFZoneList (const fvMesh &mesh, const dictionary &dict)
~MRFZoneList ()=default
bool active (const bool warn=false) const
void reset (const dictionary &dict)
const MRFZone & getFromName (const word &name) const
void addAcceleration (const volVectorField &U, volVectorField &ddtU) const
void addAcceleration (fvVectorMatrix &UEqn) const
void addAcceleration (const volScalarField &rho, fvVectorMatrix &UEqn) const
tmp< volVectorField > DDt (const volVectorField &U) const
tmp< volVectorField > DDt (const volScalarField &rho, const volVectorField &U) const
void makeRelative (volVectorField &U) const
void makeRelative (surfaceScalarField &phi) const
tmp< surfaceScalarField > relative (const tmp< surfaceScalarField > &phi) const
tmp< FieldField< fvsPatchField, scalar > > relative (const tmp< FieldField< fvsPatchField, scalar > > &tphi) const
tmp< Field< scalar > > relative (const tmp< Field< scalar > > &tphi, const label patchi) const
void makeRelative (const surfaceScalarField &rho, surfaceScalarField &phi) const
void makeAbsolute (volVectorField &U) const
void makeAbsolute (surfaceScalarField &phi) const
tmp< surfaceScalarField > absolute (const tmp< surfaceScalarField > &phi) const
void makeAbsolute (const surfaceScalarField &rho, surfaceScalarField &phi) const
void correctBoundaryVelocity (volVectorField &U) const
void correctBoundaryFlux (const volVectorField &U, surfaceScalarField &phi) const
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > zeroFilter (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > &tphi) const
void update ()
bool read (const dictionary &dict)
bool writeData (Ostream &os) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > zeroFilter (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > &tphi) const
Public Member Functions inherited from PtrList< MRFZone >
constexpr PtrList () noexcept
PtrList (const label len)
PtrList (const PtrList< MRFZone > &list)
PtrList (PtrList< MRFZone > &&list)
PtrList (UList< MRFZone * > &list)
PtrList (const PtrList< MRFZone > &list, const CloneArg &cloneArgs)
PtrList (PtrList< MRFZone > &list, bool reuse)
PtrList (const SLPtrList< MRFZone > &list)
PtrList (Istream &is, const INew &inew)
PtrList (Istream &is)
~PtrList ()
PtrList< MRFZone > clone (Args &&... args) const
Foam::PtrList< MRFZone > clone (Args &&... args) const
const MRFZone * set (const label i) const
autoPtr< MRFZone > set (const label i, MRFZone *ptr)
autoPtr< MRFZone > set (const label i, std::unique_ptr< MRFZone > &&ptr)
autoPtr< MRFZone > set (const label i, autoPtr< MRFZone > &&ptr)
autoPtr< MRFZone > set (const label i, const refPtr< MRFZone > &ptr)
autoPtr< MRFZone > set (const label i, const tmp< MRFZone > &ptr)
autoPtr< MRFZone > set (const label i, autoPtr< MRFZone > &ptr)
void clear ()
void free ()
void resize (const label newLen)
MRFZone & emplace_back (Args &&... args)
void push_back (MRFZone *ptr)
void push_back (std::unique_ptr< MRFZone > &&ptr)
void push_back (autoPtr< MRFZone > &&ptr)
void push_back (const refPtr< MRFZone > &ptr)
void push_back (const tmp< MRFZone > &ptr)
void push_back (PtrList< MRFZone > &&other)
void push_back (autoPtr< MRFZone > &ptr)=delete
MRFZone & emplace_set (const label i, Args &&... args)
MRFZone & emplace (const label i, Args &&... args)
autoPtr< MRFZone > release (const label i)
void transfer (PtrList< MRFZone > &list)
void operator= (const PtrList< MRFZone > &list)
void operator= (PtrList< MRFZone > &&list)
void setSize (const label newLen)
void append (autoPtr< MRFZone > &ptr)
void append (MRFZone *ptr)
void append (std::unique_ptr< MRFZone > &&ptr)
void append (autoPtr< MRFZone > &&ptr)
void append (const refPtr< MRFZone > &ptr)
void append (const tmp< MRFZone > &ptr)
void append (PtrList< MRFZone > &&other)
Public Member Functions inherited from UPtrList< T >
constexpr UPtrList () noexcept
UPtrList (const label len)
UPtrList (const UPtrList< T > &list)
UPtrList (UPtrList< T > &&list)
UPtrList (UPtrList< T > &list, bool reuse)
UPtrList (PtrList< T > &list)
UPtrList (const UList< T * > &list)
UPtrList (UList< T > &list)
bool empty () const noexcept
label size () const noexcept
label count () const noexcept
T & front ()
const T & front () const
T & back ()
const T & back () const
const T * test (const label i) const
const T * get (const label i) const
T * get (const label i)
const T * set (const label i) const
void clear ()
void free ()
void resize (const label newLen)
label squeezeNull ()
void trimTrailingNull ()
void push_back (T *ptr)
void push_back (UPtrList< T > &&other)
void swap (UPtrList< T > &list)
void transfer (UPtrList< T > &list)
T * set (const label i, T *ptr)
void reorder (const labelUList &oldToNew, const bool check=false)
void sortOrder (const labelUList &order, const bool check=false)
void checkNonNull () const
const T & at (const label i) const
T & at (const label i)
const T & operator[] (const label i) const
T & operator[] (const label i)
FOAM_DEPRECATED_FOR (2022-09, "get(), set() or test() methods") const T *operator()(const label i) const
void operator= (const UPtrList< T > &list)
void operator= (UPtrList< T > &&list)
T ** begin_ptr () noexcept
T ** end_ptr () noexcept
iterator begin ()
iterator end () noexcept
const_iterator cbegin () const
const_iterator cend () const noexcept
const_iterator begin () const
const_iterator end () const noexcept
void setSize (const label n)
T & first ()
const T & first () const
T & last ()
const T & last () const
void append (T *ptr)
void append (UPtrList< T > &&other)
Protected Attributes
const fvMesh & mesh_
Protected Attributes inherited from UPtrList< T >
Detail::PtrListDetail< T > ptrs_
Friends
Ostream & operator<< (Ostream &os, const MRFZoneList &models)
Additional Inherited Members
Public Types inherited from UPtrList< T >
typedef T value_type
typedef T & reference
typedef const T & const_reference
Protected Member Functions inherited from PtrList< MRFZone >
void readIstream (Istream &is, const INew &inew)
Protected Member Functions inherited from UPtrList< T >
void setAddressableSize (const label n) noexcept
label find_next (label pos) const
UPtrList (Detail::PtrListDetail< T > &&ptrs)
Detailed Description
List container for MRF zomes.
Source files
MRFZoneList.H
MRFZoneList.C
Definition at line 54 of file MRFZoneList.H.
Constructor & Destructor Documentation
MRFZoneList()
MRFZoneList (const fvMesh & mesh, const dictionary & dict)
Definition at line 28 of file MRFZoneList.C.
References MRFZoneList::active(), dict, and MRFZoneList::reset().
~MRFZoneList()
~MRFZoneList () default
Member Function Documentation
active()
bool active (const bool warn = false) const
Definition at line 45 of file MRFZoneList.C.
References Foam::endl(), forAll, and Foam::Info.
Referenced by MRFZoneList::MRFZoneList().
reset()
void reset (const dictionary & dict)
Definition at line 62 of file MRFZoneList.C.
References dict, Foam::endl(), Foam::Info, Foam::name(), and resize().
Referenced by MRFZoneList::MRFZoneList().
getFromName()
const Foam::MRFZone & getFromName (const word & name) const
Definition at line 95 of file MRFZoneList.C.
References List< T >::append(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, and Foam::name().
addAcceleration() [1/3]
void addAcceleration (const volVectorField & U, volVectorField & ddtU) const
Definition at line 144 of file MRFZoneList.C.
References U.
addAcceleration() [2/3]
void addAcceleration (fvVectorMatrix & UEqn) const
Definition at line 157 of file MRFZoneList.C.
References UEqn.
addAcceleration() [3/3]
void addAcceleration (const volScalarField & rho, fvVectorMatrix & UEqn) const
Definition at line 166 of file MRFZoneList.C.
References rho, and UEqn.
DDt() [1/2]
Foam::tmp< Foam::volVectorField > DDt (const volVectorField & U) const
Definition at line 179 of file MRFZoneList.C.
References Foam::dimTime, tmp< T >::New(), U, and Foam::Zero.
DDt() [2/2]
Foam::tmp< Foam::volVectorField > DDt (const volScalarField & rho, const volVectorField & U) const
Definition at line 207 of file MRFZoneList.C.
References rho, and U.
makeRelative() [1/3]
void makeRelative (volVectorField & U) const
Definition at line 217 of file MRFZoneList.C.
References U.
makeRelative() [2/3]
void makeRelative (surfaceScalarField & phi) const
Definition at line 226 of file MRFZoneList.C.
References phi.
relative() [1/3]
Foam::tmp< Foam::surfaceScalarField > relative (const tmp< surfaceScalarField > & phi) const
Definition at line 235 of file MRFZoneList.C.
References PtrList< T >::clear(), makeRelative(), Foam::name(), and Foam::New().
relative() [2/3]
Foam::tmp< Foam::FieldField< Foam::fvsPatchField, Foam::scalar > > relative (const tmp< FieldField< fvsPatchField, scalar > > & tphi) const
Definition at line 267 of file MRFZoneList.C.
References PtrList< T >::clear(), and Foam::New().
relative() [3/3]
Foam::tmp< Foam::Field< Foam::scalar > > relative (const tmp< Field< scalar > > & tphi, const label patchi) const
Definition at line 293 of file MRFZoneList.C.
References PtrList< T >::clear(), and Foam::New().
makeRelative() [3/3]
void makeRelative (const surfaceScalarField & rho, surfaceScalarField & phi) const
Definition at line 319 of file MRFZoneList.C.
References phi, and rho.
makeAbsolute() [1/3]
void makeAbsolute (volVectorField & U) const
Definition at line 332 of file MRFZoneList.C.
References U.
makeAbsolute() [2/3]
void makeAbsolute (surfaceScalarField & phi) const
Definition at line 341 of file MRFZoneList.C.
References phi.
absolute()
Foam::tmp< Foam::surfaceScalarField > absolute (const tmp< surfaceScalarField > & phi) const
Definition at line 350 of file MRFZoneList.C.
References PtrList< T >::clear(), Foam::name(), and Foam::New().
makeAbsolute() [3/3]
void makeAbsolute (const surfaceScalarField & rho, surfaceScalarField & phi) const
Definition at line 381 of file MRFZoneList.C.
References phi, and rho.
correctBoundaryVelocity()
void correctBoundaryVelocity (volVectorField & U) const
Definition at line 394 of file MRFZoneList.C.
References U.
correctBoundaryFlux()
void correctBoundaryFlux (const volVectorField & U, surfaceScalarField & phi) const
Definition at line 403 of file MRFZoneList.C.
References forAll, phi, U, and Uf.
zeroFilter() [1/2]
template<class Type > tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > zeroFilter (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > & tphi) const
update()
void update ()
Definition at line 426 of file MRFZoneList.C.
read()
bool read (const dictionary & dict)
Definition at line 120 of file MRFZoneList.C.
References dict, and dictionary::subDict().
Referenced by IOMRFZoneList::read().
writeData()
bool writeData (Ostream & os) const
Definition at line 132 of file MRFZoneList.C.
References IOstream::good(), Foam::nl, and os().
zeroFilter() [2/2]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > zeroFilter (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > & tphi) const
Definition at line 27 of file MRFZoneListTemplates.C.
References forAll, Foam::name(), Foam::New(), UPtrList< T >::operator[](), PtrList< MRFZone >::PtrList(), and UPtrList< T >::size().
Friends And Related Symbol Documentation
operator<<
Ostream & operator<< (Ostream & os, const MRFZoneList & models) friend
Member Data Documentation
mesh_
const fvMesh& mesh_ protected
Definition at line 72 of file MRFZoneList.H.
The documentation for this class was generated from the following files:
src/finiteVolume/cfdTools/general/MRF/MRFZoneList.H
src/finiteVolume/cfdTools/general/MRF/MRFZoneList.C
src/finiteVolume/cfdTools/general/MRF/MRFZoneListTemplates.C