OpenFOAM: DictionaryBase< IDLListType, T > Class Template Reference
DictionaryBase< IDLListType, T > Class Template Reference
Base dictionary class templated on both the form of doubly-linked list it uses as well as the type it holds.
#include <DictionaryBase.H>
Public Member Functions
DictionaryBase (const label size=128)
DictionaryBase (const DictionaryBase &dict)
template<class INew >
DictionaryBase (Istream &is, const INew &inew)
DictionaryBase (Istream &is)
bool contains (const word &keyword) const
const T * cfind (const word &keyword) const
T * find (const word &keyword)
const T * lookup (const word &keyword) const
T * lookup (const word &keyword)
wordList toc () const
wordList sortedToc () const
template<class Compare >
wordList sortedToc (const Compare &comp) const
void push_front (const word &keyword, T *ptr)
void push_back (const word &keyword, T *ptr)
T * remove (const word &keyword)
void clear ()
void transfer (DictionaryBase< IDLListType, T > &dict)
void operator= (const DictionaryBase &)
const T * operator[] (const word &key) const
T * operator[] (const word &key)
bool found (const word &key) const
const T * lookupPtr (const word &keyword) const
T * lookupPtr (const word &keyword)
void insert (const word &keyword, T *ptr)
void prepend (const word &keyword, T *ptr)
void append (const word &keyword, T *ptr)
template<class Compare >
Foam::wordList sortedToc (const Compare &comp) const
Protected Member Functions
void addEntries ()
Protected Attributes
HashTable< T * > hashedTs_
Friends
Ostream & operator (Ostream &, const DictionaryBase< IDLListType, T > &)
Detailed Description
template<class IDLListType, class T>
class Foam::DictionaryBase< IDLListType, T >
Base dictionary class templated on both the form of doubly-linked list it uses as well as the type it holds.
The double templating allows for the instantiation of forms with or without storage management.
Note
The IDLListType parameter should itself be a template but this confused gcc 2.95.2 so it has to be instantiated for T when an instantiation of DictionaryBase is requested
See also
Dictionary and UDictionary
Source files
DictionaryBase.H
DictionaryBase.C
DictionaryBaseIO.C
Definition at line 71 of file DictionaryBase.H.
Constructor & Destructor Documentation
DictionaryBase() [1/4]
template<class IDLListType , class T > DictionaryBase (const label size = 128) explicit
Definition at line 39 of file DictionaryBase.C.
DictionaryBase() [2/4]
template<class IDLListType , class T > DictionaryBase (const DictionaryBase< IDLListType, T > & dict)
Definition at line 46 of file DictionaryBase.C.
References DictionaryBase< IDLListType, T >::addEntries().
DictionaryBase() [3/4]
template<class IDLListType , class T > template<class INew > DictionaryBase (Istream & is, const INew & inew)
Definition at line 59 of file DictionaryBase.C.
References DictionaryBase< IDLListType, T >::addEntries().
DictionaryBase() [4/4]
template<class IDLListType , class T > DictionaryBase (Istream & is)
Definition at line 72 of file DictionaryBase.C.
References DictionaryBase< IDLListType, T >::addEntries().
Member Function Documentation
addEntries()
template<class IDLListType , class T > void addEntries () protected
Definition at line 27 of file DictionaryBase.C.
References UPtrList< T >::begin(), and UPtrList< T >::end().
Referenced by DictionaryBase< IDLListType, T >::DictionaryBase(), DictionaryBase< IDLListType, T >::DictionaryBase(), and DictionaryBase< IDLListType, T >::DictionaryBase().
contains()
template<class IDLListType , class T > bool contains (const word & keyword) const
Definition at line 83 of file DictionaryBase.C.
Referenced by DictionaryBase< IDLListType, T >::found().
cfind()
template<class IDLListType , class T > const T * cfind (const word & keyword) const
Definition at line 90 of file DictionaryBase.C.
Referenced by DictionaryBase< IDLListType, T >::lookupPtr().
find()
template<class IDLListType , class T > T * find (const word & keyword)
Definition at line 107 of file DictionaryBase.C.
Referenced by Foam::appendNamedEntry(), DictionaryBase< IDLListType, T >::lookupPtr(), and simpleObjectRegistry::setValues().
lookup() [1/2]
template<class IDLListType , class T > const T * lookup (const word & keyword) const
Definition at line 121 of file DictionaryBase.C.
lookup() [2/2]
template<class IDLListType , class T > T * lookup (const word & keyword)
Definition at line 137 of file DictionaryBase.C.
toc()
template<class IDLListType , class T > Foam::wordList toc () const
Definition at line 153 of file DictionaryBase.C.
Referenced by phaseSystem::phaseSystem().
sortedToc() [1/3]
template<class IDLListType , class T > Foam::wordList sortedToc () const
Definition at line 163 of file DictionaryBase.C.
sortedToc() [2/3]
template<class IDLListType , class T > template<class Compare > wordList sortedToc (const Compare & comp) const
push_front()
template<class IDLListType , class T > void push_front (const word & keyword, T * ptr)
Definition at line 181 of file DictionaryBase.C.
Referenced by DictionaryBase< IDLListType, T >::insert(), and DictionaryBase< IDLListType, T >::prepend().
push_back()
template<class IDLListType , class T > void push_back (const word & keyword, T * ptr)
Definition at line 194 of file DictionaryBase.C.
Referenced by DictionaryBase< IDLListType, T >::append().
remove()
template<class IDLListType , class T > T * remove (const word & keyword)
Definition at line 207 of file DictionaryBase.C.
References T.
clear()
template<class IDLListType , class T > void clear ()
Definition at line 223 of file DictionaryBase.C.
transfer()
template<class IDLListType , class T > void transfer (DictionaryBase< IDLListType, T > & dict)
Definition at line 231 of file DictionaryBase.C.
References dict.
operator=()
template<class IDLListType , class T > void operator= (const DictionaryBase< IDLListType, T > &)
Definition at line 249 of file DictionaryBase.C.
References dict.
operator[]() [1/2]
template<class IDLListType , class T > const T * operator[] (const word & key) const inline
Definition at line 163 of file DictionaryBase.H.
operator[]() [2/2]
template<class IDLListType , class T > T * operator[] (const word & key) inline
Definition at line 169 of file DictionaryBase.H.
found()
template<class IDLListType , class T > bool found (const word & key) const inline
Definition at line 187 of file DictionaryBase.H.
References DictionaryBase< IDLListType, T >::contains().
lookupPtr() [1/2]
template<class IDLListType , class T > const T * lookupPtr (const word & keyword) const inline
Definition at line 192 of file DictionaryBase.H.
References DictionaryBase< IDLListType, T >::cfind().
lookupPtr() [2/2]
template<class IDLListType , class T > T * lookupPtr (const word & keyword) inline
Definition at line 200 of file DictionaryBase.H.
References DictionaryBase< IDLListType, T >::find().
insert()
template<class IDLListType , class T > void insert (const word & keyword, T * ptr) inline
Definition at line 207 of file DictionaryBase.H.
References DictionaryBase< IDLListType, T >::push_front().
prepend()
template<class IDLListType , class T > void prepend (const word & keyword, T * ptr) inline
Definition at line 214 of file DictionaryBase.H.
References DictionaryBase< IDLListType, T >::push_front().
append()
template<class IDLListType , class T > void append (const word & keyword, T * ptr) inline
Definition at line 221 of file DictionaryBase.H.
References DictionaryBase< IDLListType, T >::push_back().
Referenced by Foam::appendNamedEntry().
sortedToc() [3/3]
template<class IDLListType , class T > template<class Compare > Foam::wordList sortedToc (const Compare & comp) const
Definition at line 171 of file DictionaryBase.C.
Friends And Related Symbol Documentation
operator
template<class IDLListType , class T > Ostream & operator (Ostream & , const DictionaryBase< IDLListType, T > &) friend
Member Data Documentation
hashedTs_
template<class IDLListType , class T > HashTable<T*> hashedTs_ protected
Definition at line 80 of file DictionaryBase.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/Dictionaries/DictionaryBase/DictionaryBase.H
src/OpenFOAM/containers/Dictionaries/DictionaryBase/DictionaryBase.C