OpenFOAM: isoSurfaceParams Class Reference
isoSurfaceParams Class Reference
Preferences for controlling iso-surface algorithms.
#include <isoSurfaceParams.H>
Public Types
enum algorithmType : uint8_t { ALGO_DEFAULT = 0 , ALGO_TOPO , ALGO_CELL , ALGO_POINT }
enum class filterType : uint8_t {
NONE = 0 , CELL , DIAGCELL , NONMANIFOLD ,
PARTIAL = CELL , FULL = DIAGCELL , CLEAN = NONMANIFOLD
}
Public Member Functions
isoSurfaceParams (const algorithmType algo=algorithmType::ALGO_DEFAULT, const filterType filter=filterType::DIAGCELL) noexcept
isoSurfaceParams (const dictionary &dict, const isoSurfaceParams &params=isoSurfaceParams())
isoSurfaceParams (const dictionary &dict, const algorithmType algo, const filterType filter=filterType::DIAGCELL)
algorithmType algorithm () const noexcept
void algorithm (algorithmType algo) noexcept
filterType filter () const noexcept
void filter (filterType fltr) noexcept
bool snap () const noexcept
void snap (bool on) noexcept
scalar mergeTol () const noexcept
void mergeTol (const scalar relTol) noexcept
const boundBox & getClipBounds () const noexcept
boundBox & getClipBounds () noexcept
void setClipBounds (const boundBox &bb)
void print (Ostream &os) const
Static Public Member Functions
static algorithmType getAlgorithmType (const dictionary &dict, const algorithmType deflt)
static filterType getFilterType (const dictionary &dict, const filterType deflt)
Static Public Attributes
static const Enum< algorithmType > algorithmNames
static const Enum< filterType > filterNames
Detailed Description
Preferences for controlling iso-surface algorithms.
Some common dictionary properties:
Property Description Required Default
isoMethod Algorithm (cell/topo/point/default) no default
regularise Face simplification (enum or bool) no true
mergeTol Point merge tolerance (cell/point) no 1e-6
snap Point snapping (topo) no true
bounds Optional clip bounds no inverted
The default algorithm denotes the use of the current standard algorithm.
Filtering types (for topological iso-surface)
none : leave tet cuts untouched
partial , cell : Combine intra-cell faces
full , diagcell : Perform partial and remove face-diagonal points
clean : Perform full and eliminate open edges as well. (May cause excessive erosion!)
Source files
isoSurfaceParams.H
isoSurfaceParams.C
Definition at line 102 of file isoSurfaceParams.H.
Member Enumeration Documentation
algorithmType
enum algorithmType : uint8_t
Enumerator
ALGO_DEFAULT
Use current 'standard' algorithm.
ALGO_TOPO
ALGO_CELL
ALGO_POINT
Definition at line 109 of file isoSurfaceParams.H.
filterType
enum class filterType : uint8_t strong
Enumerator
NONE
No filtering.
CELL
Remove pyramid edge points.
DIAGCELL
Remove pyramid edge points, face-diagonals.
NONMANIFOLD
Remove pyramid edge points, face-diagonals and non-manifold faces
PARTIAL
Same as CELL.
FULL
Same as DIAGCELL.
CLEAN
Same as NONMANIFOLD.
Definition at line 118 of file isoSurfaceParams.H.
Constructor & Destructor Documentation
isoSurfaceParams() [1/3]
isoSurfaceParams (const algorithmType algo = algorithmType::ALGO_DEFAULT, const filterType filter = filterType::DIAGCELL) explicit noexcept
Definition at line 127 of file isoSurfaceParams.C.
isoSurfaceParams() [2/3]
isoSurfaceParams (const dictionary & dict, const isoSurfaceParams & params = isoSurfaceParams()) explicit
Definition at line 141 of file isoSurfaceParams.C.
References dict, isoSurfaceParams::getAlgorithmType(), and isoSurfaceParams::getFilterType().
isoSurfaceParams() [3/3]
isoSurfaceParams (const dictionary & dict, const algorithmType algo, const filterType filter = filterType::DIAGCELL) explicit
Definition at line 157 of file isoSurfaceParams.C.
Member Function Documentation
getAlgorithmType()
Foam::isoSurfaceParams::algorithmType getAlgorithmType (const dictionary & dict, const algorithmType deflt) static
Definition at line 60 of file isoSurfaceParams.C.
References dict.
Referenced by isoSurfaceParams::isoSurfaceParams().
getFilterType()
Foam::isoSurfaceParams::filterType getFilterType (const dictionary & dict, const filterType deflt) static
Definition at line 92 of file isoSurfaceParams.C.
References dict, Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, Switch::find(), keyType::LITERAL, Foam::nl, and dictionary::readIfPresent().
Referenced by isoSurfaceParams::isoSurfaceParams().
algorithm() [1/2]
algorithmType algorithm () const inline noexcept
Definition at line 208 of file isoSurfaceParams.H.
Referenced by sampledCuttingPlane::sampledCuttingPlane(), and sampledIsoSurface::sampledIsoSurface().
algorithm() [2/2]
void algorithm (algorithmType algo) inline noexcept
Definition at line 214 of file isoSurfaceParams.H.
filter() [1/2]
filterType filter () const inline noexcept
Definition at line 220 of file isoSurfaceParams.H.
Referenced by sampledIsoSurface::sampledIsoSurface().
filter() [2/2]
void filter (filterType fltr) inline noexcept
Definition at line 226 of file isoSurfaceParams.H.
snap() [1/2]
bool snap () const inline noexcept
Definition at line 232 of file isoSurfaceParams.H.
Referenced by isoSurfaceTopo::isoSurfaceTopo().
snap() [2/2]
void snap (bool on) inline noexcept
Definition at line 238 of file isoSurfaceParams.H.
mergeTol() [1/2]
scalar mergeTol () const inline noexcept
Definition at line 244 of file isoSurfaceParams.H.
mergeTol() [2/2]
void mergeTol (const scalar relTol) inline noexcept
Definition at line 250 of file isoSurfaceParams.H.
getClipBounds() [1/2]
const boundBox & getClipBounds () const inline noexcept
Definition at line 256 of file isoSurfaceParams.H.
Referenced by isoSurfaceCell::isoSurfaceCell(), and isoSurfacePoint::isoSurfacePoint().
getClipBounds() [2/2]
boundBox & getClipBounds () inline noexcept
Definition at line 262 of file isoSurfaceParams.H.
setClipBounds()
void setClipBounds (const boundBox & bb)
Definition at line 170 of file isoSurfaceParams.C.
print()
void print (Ostream & os) const
Definition at line 176 of file isoSurfaceParams.C.
References os().
Member Data Documentation
algorithmNames
const Foam::Enum< Foam::isoSurfaceParams::algorithmType > algorithmNames static
Definition at line 157 of file isoSurfaceParams.H.
filterNames
const Foam::Enum< Foam::isoSurfaceParams::filterType > filterNames static
Definition at line 160 of file isoSurfaceParams.H.
Referenced by isoSurfaceTopo::isoSurfaceTopo().
The documentation for this class was generated from the following files:
src/sampling/surface/isoSurface/isoSurfaceParams.H
src/sampling/surface/isoSurface/isoSurfaceParams.C