OpenFOAM: controlPointsDefinition Class Reference
controlPointsDefinition Class Reference abstract
Abstract base for selecting how to construct the control points of a volumetric B-Splines morpher.
#include <controlPointsDefinition.H>
Public Member Functions
TypeName ("controlPointsDefinition")
declareRunTimeSelectionTable (autoPtr, controlPointsDefinition, dictionary,(NURBS3DVolume &box),(box))
controlPointsDefinition (NURBS3DVolume &box)
virtual ~controlPointsDefinition ()=default
Static Public Member Functions
static autoPtr< controlPointsDefinition > New (NURBS3DVolume &box)
Protected Member Functions
virtual void computeControlPoints ()=0
void transformControlPoints (const vector &geometryMin, const vector &geometryMax)
Protected Attributes
NURBS3DVolume & box_
vectorField & cps_
Detailed Description
Abstract base for selecting how to construct the control points of a volumetric B-Splines morpher.
Source files
controlPointsDefinition.H
controlPointsDefinition.C
Definition at line 48 of file controlPointsDefinition.H.
Constructor & Destructor Documentation
controlPointsDefinition()
controlPointsDefinition (NURBS3DVolume & box)
Definition at line 93 of file controlPointsDefinition.C.
~controlPointsDefinition()
virtual ~controlPointsDefinition () virtual default
Member Function Documentation
computeControlPoints()
virtual void computeControlPoints () protected pure virtual
Implemented in axisAligned, fromFile, and transformBox.
transformControlPoints()
void transformControlPoints (const vector & geometryMin, const vector & geometryMax) protected
Definition at line 39 of file controlPointsDefinition.C.
References controlPointsDefinition::box_, Foam::cmptMultiply(), Foam::cos(), controlPointsDefinition::cps_, dict, NURBS3DVolume::dict(), Foam::constant::mathematical::pi(), R, Foam::Rx(), Foam::Ry(), Foam::Rz(), Foam::sin(), Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
Referenced by transformBox::computeControlPoints().
TypeName()
TypeName ("controlPointsDefinition")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , controlPointsDefinition , dictionary , (NURBS3DVolume &box) , (box))
New()
Foam::autoPtr< Foam::controlPointsDefinition > New (NURBS3DVolume & box) static
Definition at line 105 of file controlPointsDefinition.C.
References dict, NURBS3DVolume::dict(), Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), Foam::Info, and Foam::type().
Member Data Documentation
box_
NURBS3DVolume& box_ protected
Definition at line 55 of file controlPointsDefinition.H.
Referenced by axisAligned::computeControlPoints(), fromFile::computeControlPoints(), transformBox::computeControlPoints(), and controlPointsDefinition::transformControlPoints().
cps_
vectorField& cps_ protected
Definition at line 58 of file controlPointsDefinition.H.
Referenced by axisAligned::computeControlPoints(), fromFile::computeControlPoints(), transformBox::computeControlPoints(), and controlPointsDefinition::transformControlPoints().
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/parameterization/NURBS/NURBS3DVolume/controlPointsDefinition/controlPointsDefinition/controlPointsDefinition.H
src/optimisation/adjointOptimisation/adjoint/parameterization/NURBS/NURBS3DVolume/controlPointsDefinition/controlPointsDefinition/controlPointsDefinition.C