OpenFOAM: pointMVCWeight Class Reference
pointMVCWeight Class Reference
Container to calculate weights for interpolating directly from vertices of cell using Mean Value Coordinates.
#include <pointMVCWeight.H>
Public Member Functions
pointMVCWeight (const polyMesh &mesh, const vector &position, const label celli, const label facei=-1)
label cell () const noexcept
const scalarField & weights () const noexcept
template<class Type >
Type interpolate (const GeometricField< Type, pointPatchField, pointMesh > &psip) const
Static Public Attributes
static int debug
static scalar tol
Protected Member Functions
void calcWeights (const Map< label > &toLocal, const face &f, const DynamicList< point > &u, const scalarField &dist, scalarField &weights) const
void calcWeights (const polyMesh &mesh, const labelList &toGlobal, const Map< label > &toLocal, const vector &position, const vectorField &uVec, const scalarField &dist, scalarField &weights) const
Protected Attributes
const label cellIndex_
scalarField weights_
Detailed Description
Container to calculate weights for interpolating directly from vertices of cell using Mean Value Coordinates.
Based on (VTK's vtkMeanValueCoordinatesInterpolator's) implementation of "Spherical Barycentric Coordinates" 2006 paper Eurographics Symposium on Geometry Processing by Torsten Langer, Alexander Belyaev and Hans-Peter Seide
Source files
pointMVCWeight.H
pointMVCWeight.C
Definition at line 64 of file pointMVCWeight.H.
Constructor & Destructor Documentation
pointMVCWeight()
pointMVCWeight (const polyMesh & mesh, const vector & position, const label celli, const label facei = -1)
Definition at line 238 of file pointMVCWeight.C.
References pointMVCWeight::calcWeights(), pointMVCWeight::cellIndex_, f(), forAll, Foam::mag(), mesh, Foam::pid(), List< T >::setSize(), UList< T >::size(), pointMVCWeight::tol, and pointMVCWeight::weights_.
Member Function Documentation
calcWeights() [1/2]
void calcWeights (const Map< label > & toLocal, const face & f, const DynamicList< point > & u, const scalarField & dist, scalarField & weights) const protected
Definition at line 36 of file pointMVCWeight.C.
References Foam::asin(), f(), forAll, Foam::mag(), Foam::pid(), PtrList< T >::setSize(), UPtrList< T >::size(), Foam::tan(), pointMVCWeight::tol, and pointMVCWeight::weights().
Referenced by pointMVCWeight::pointMVCWeight().
calcWeights() [2/2]
void calcWeights (const polyMesh & mesh, const labelList & toGlobal, const Map< label > & toLocal, const vector & position, const vectorField & uVec, const scalarField & dist, scalarField & weights) const protected
Definition at line 77 of file pointMVCWeight.C.
References alpha, Foam::asin(), primitiveMesh::cells(), f(), polyMesh::faces(), UList< T >::fcIndex(), forAll, Foam::mag(), mesh, Foam::min(), Foam::normalised(), Foam::pid(), UList< T >::rcIndex(), Foam::sin(), Foam::sum(), Foam::tan(), and Foam::Zero.
cell()
label cell () const inline noexcept
Definition at line 126 of file pointMVCWeight.H.
References pointMVCWeight::cellIndex_.
weights()
const scalarField & weights () const inline noexcept
Definition at line 132 of file pointMVCWeight.H.
References pointMVCWeight::weights_.
Referenced by pointMVCWeight::calcWeights().
interpolate()
template<class Type > Type interpolate (const GeometricField< Type, pointPatchField, pointMesh > & psip) const inline
Definition at line 26 of file pointMVCWeightI.H.
References pointMVCWeight::cellIndex_, forAll, Foam::vertices(), pointMVCWeight::weights_, and Foam::Zero.
Member Data Documentation
cellIndex_
const label cellIndex_ protected
Definition at line 71 of file pointMVCWeight.H.
Referenced by pointMVCWeight::cell(), pointMVCWeight::interpolate(), and pointMVCWeight::pointMVCWeight().
weights_
scalarField weights_ protected
Definition at line 74 of file pointMVCWeight.H.
Referenced by pointMVCWeight::interpolate(), pointMVCWeight::pointMVCWeight(), and pointMVCWeight::weights().
debug
int debug static
Definition at line 104 of file pointMVCWeight.H.
tol
Foam::scalar tol static
Definition at line 108 of file pointMVCWeight.H.
Referenced by pointMVCWeight::calcWeights(), and pointMVCWeight::pointMVCWeight().
The documentation for this class was generated from the following files:
src/finiteVolume/interpolation/interpolation/interpolationPointMVC/pointMVCWeight.H
src/finiteVolume/interpolation/interpolation/interpolationPointMVC/pointMVCWeight.C
src/finiteVolume/interpolation/interpolation/interpolationPointMVC/pointMVCWeightI.H