OpenFOAM: linearUpwindWeight Class Reference
linearUpwindWeight Class Reference
Class with operator() which returns the weighting factors for the linear-upwind differencing scheme. Note that the weighting factors are not bounded between upwind and central-differencing, some downwind contribution is possible although the interpolate is limited to be between the upwind and downwind cell values.
#include <linearUpwind.H>
Public Member Functions
linearUpwindWeight (Istream &)
scalar weight (scalar cdWeight, scalar faceFlux, scalar phiP, scalar phiN, const vector &gradcP, const vector &gradcN, const vector &d) const
Detailed Description
Class with operator() which returns the weighting factors for the linear-upwind differencing scheme. Note that the weighting factors are not bounded between upwind and central-differencing, some downwind contribution is possible although the interpolate is limited to be between the upwind and downwind cell values.
Used in conjunction with the template class NVDscheme although this scheme is not NVD.
Source files
linearUpwind.H
linearUpwindMake.C
Definition at line 54 of file linearUpwind.H.
Constructor & Destructor Documentation
linearUpwindWeight()
linearUpwindWeight (Istream &) inline
Definition at line 59 of file linearUpwind.H.
Member Function Documentation
weight()
scalar weight (scalar cdWeight, scalar faceFlux, scalar phiP, scalar phiN, const vector & gradcP, const vector & gradcN, const vector & d) const inline
Definition at line 62 of file linearUpwind.H.
References Foam::max(), Foam::min(), and Foam::stabilise().
The documentation for this class was generated from the following file:
src/finiteArea/interpolation/edgeInterpolation/schemes/linearUpwind/linearUpwind.H