OpenFOAM: semiPermeableBaffleVelocityFvPatchVectorField Class Reference
semiPermeableBaffleVelocityFvPatchVectorField Class Reference
Boundary conditions » Generic
This is a velocity boundary condition for a semi-permeable baffle.
#include <semiPermeableBaffleVelocityFvPatchVectorField.H>
Public Member Functions
TypeName ("semiPermeableBaffleVelocity")
semiPermeableBaffleVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
semiPermeableBaffleVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
semiPermeableBaffleVelocityFvPatchVectorField (const semiPermeableBaffleVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
semiPermeableBaffleVelocityFvPatchVectorField (const semiPermeableBaffleVelocityFvPatchVectorField &)
virtual tmp< fvPatchVectorField > clone () const
semiPermeableBaffleVelocityFvPatchVectorField (const semiPermeableBaffleVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
This is a velocity boundary condition for a semi-permeable baffle.
This is a velocity boundary condition for baffles which are permeable to a some species and impermeable to others. It must be used in conjunction with the corresponding mass-fraction condition, semiPermeableBaffleMassFractionFvPatchScalarField.
This condition sums the species fluxes generated by the the mass-fraction conditions, and uses this total to set the velocity.
Usage
Property Description Req'd? Default
rho Name of the density field no rho
See also
Foam::semiPermeableBaffleMassFractionFvPatchScalarField
Source files
semiPermeableBaffleVelocityFvPatchVectorField.H
semiPermeableBaffleVelocityFvPatchVectorField.C
Definition at line 79 of file semiPermeableBaffleVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
semiPermeableBaffleVelocityFvPatchVectorField() [1/5]
semiPermeableBaffleVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Definition at line 59 of file semiPermeableBaffleVelocityFvPatchVectorField.C.
semiPermeableBaffleVelocityFvPatchVectorField() [2/5]
semiPermeableBaffleVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Definition at line 71 of file semiPermeableBaffleVelocityFvPatchVectorField.C.
References dict, and IOobjectOption::MUST_READ.
semiPermeableBaffleVelocityFvPatchVectorField() [3/5]
semiPermeableBaffleVelocityFvPatchVectorField (const semiPermeableBaffleVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 86 of file semiPermeableBaffleVelocityFvPatchVectorField.C.
semiPermeableBaffleVelocityFvPatchVectorField() [4/5]
semiPermeableBaffleVelocityFvPatchVectorField (const semiPermeableBaffleVelocityFvPatchVectorField & ptf)
Definition at line 100 of file semiPermeableBaffleVelocityFvPatchVectorField.C.
semiPermeableBaffleVelocityFvPatchVectorField() [5/5]
semiPermeableBaffleVelocityFvPatchVectorField (const semiPermeableBaffleVelocityFvPatchVectorField & ptf, const DimensionedField< vector, volMesh > & iF)
Definition at line 111 of file semiPermeableBaffleVelocityFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("semiPermeableBaffleVelocity")
clone() [1/2]
virtual tmp< fvPatchVectorField > clone () const inline virtual
Definition at line 135 of file semiPermeableBaffleVelocityFvPatchVectorField.H.
clone() [2/2]
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Definition at line 151 of file semiPermeableBaffleVelocityFvPatchVectorField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 125 of file semiPermeableBaffleVelocityFvPatchVectorField.C.
References composition, Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::operator==(), Y, basicMultiComponentMixture::Y(), and Foam::Zero.
write()
void write (Ostream & os) const virtual
Definition at line 161 of file semiPermeableBaffleVelocityFvPatchVectorField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntryIfDifferent(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/thermoTools/derivedFvPatchFields/semiPermeableBaffle/semiPermeableBaffleVelocity/semiPermeableBaffleVelocityFvPatchVectorField.H
src/thermoTools/derivedFvPatchFields/semiPermeableBaffle/semiPermeableBaffleVelocity/semiPermeableBaffleVelocityFvPatchVectorField.C