OpenFOAM: ensightSurfaceReader Class Reference
ensightSurfaceReader Class Reference
Ensight format surface reader.
#include <ensightSurfaceReader.H>
Public Member Functions
TypeName ("ensight")
ensightSurfaceReader (const fileName &fName, const dictionary &options=dictionary())
virtual ~ensightSurfaceReader ()=default
virtual const meshedSurface & geometry (const label timeIndex)
virtual instantList times () const
virtual wordList fieldNames (const label timeIndex) const
virtual tmp< Field< scalar > > field (const label timeIndex, const label fieldIndex, const scalar &refValue=pTraits< scalar >::zero) const
virtual tmp< Field< vector > > field (const label timeIndex, const label fieldIndex, const vector &refValue=pTraits< vector >::zero) const
virtual tmp< Field< sphericalTensor > > field (const label timeIndex, const label fieldIndex, const sphericalTensor &refValue=pTraits< sphericalTensor >::zero) const
virtual tmp< Field< symmTensor > > field (const label timeIndex, const label fieldIndex, const symmTensor &refValue=pTraits< symmTensor >::zero) const
virtual tmp< Field< tensor > > field (const label timeIndex, const label fieldIndex, const tensor &refValue=pTraits< tensor >::zero) const
template<class Type >
Foam::tmp< Foam::Field< Type > > readField (const fileName &dataFile, const word &fieldName) const
template<class Type >
Foam::tmp< Foam::Field< Type > > readField (const label timeIndex, const label fieldIndex) const
Public Member Functions inherited from surfaceReader
TypeName ("surfaceReader")
declareRunTimeSelectionTable (autoPtr, surfaceReader, fileName,(const fileName &fName, const dictionary &options),(fName, options))
surfaceReader (const fileName &fName)
surfaceReader (const fileName &fName, const dictionary &options)
virtual ~surfaceReader ()=default
Protected Types
enum idTypes : unsigned char { NONE = 0 , IGNORE = 1 , GIVEN = 2 }
typedef Tuple2< ensightFaces::elemType, label > faceInfoTuple
Protected Member Functions
void skip (const label n, Istream &is) const
void readLine (ISstream &is, string &buffer) const
void debugSection (const word &expected, ISstream &is) const
Pair< idTypes > readGeometryHeader (ensightReadFile &is) const
void readCase (ISstream &is)
meshedSurface readGeometry (const fileName &geometryFile)
template<class Type >
void readFromLine (const label nSkip, Istream &is, Type &value) const
template<class Type >
void readFromLine (const label nSkip, const string &buffer, Type &value) const
template<class Type >
tmp< Field< Type > > readField (const fileName &dataFile, const word &fieldName) const
template<class Type >
tmp< Field< Type > > readField (const label timeIndex, const label fieldIndex) const
Static Protected Member Functions
static fileName replaceMask (const fileName &fName, const label timeIndex)
Protected Attributes
bool masterOnly_
IOstreamOption::streamFormat readFormat_
fileName baseDir_
fileName meshFileName_
List< word > fieldNames_
List< string > fieldFileNames_
label nTimeSteps_
label timeStartIndex_
label timeIncrement_
instantList timeValues_
autoPtr< meshedSurface > surfPtr_
List< faceInfoTuple > faceTypeInfo_
Protected Attributes inherited from surfaceReader
fileName fileName_
Additional Inherited Members
Static Public Member Functions inherited from surfaceReader
static dictionary formatOptions (const dictionary &dict, const word &formatName, const word &entryName="formatOptions")
static autoPtr< surfaceReader > New (const word &readType, const fileName &fName, const dictionary &options=dictionary())
Detailed Description
Ensight format surface reader.
readOptions
{
    ensight
    {
        debug       false;
        masterOnly  false;
    }
}
Format options for ensight:
Property Description Required Default
debug Add debug flag no false
masterOnly Read files on master and broadcast values no true
Source files
ensightSurfaceReader.H
ensightSurfaceReader.C
ensightSurfaceReaderTemplates.C
Definition at line 84 of file ensightSurfaceReader.H.
Member Typedef Documentation
faceInfoTuple
typedef Tuple2<ensightFaces::elemType, label> faceInfoTuple protected
Definition at line 102 of file ensightSurfaceReader.H.
Member Enumeration Documentation
idTypes
enum idTypes : unsigned char protected
Enumerator
NONE
"off", "assign"
IGNORE
Read but "ignore".
GIVEN
Use "given" values (not supported)
Definition at line 93 of file ensightSurfaceReader.H.
Constructor & Destructor Documentation
ensightSurfaceReader()
ensightSurfaceReader (const fileName & fName, const dictionary & options = dictionary()) explicit
Definition at line 333 of file ensightSurfaceReader.C.
References Pstream::broadcasts(), ensightSurfaceReader::fieldFileNames_, ensightSurfaceReader::fieldNames_, dictionary::getOrDefault(), UPstream::master(), ensightSurfaceReader::masterOnly_, ensightSurfaceReader::meshFileName_, ensightSurfaceReader::nTimeSteps_, UPstream::parRun(), ensightSurfaceReader::readCase(), ensightSurfaceReader::timeIncrement_, ensightSurfaceReader::timeStartIndex_, ensightSurfaceReader::timeValues_, and UPstream::worldComm.
~ensightSurfaceReader()
virtual ~ensightSurfaceReader () virtual default
Member Function Documentation
skip()
void skip (const label n, Istream & is) const protected
Definition at line 58 of file ensightSurfaceReader.C.
References DebugInfo, n, Foam::nl, and WarningInFunction.
Referenced by ensightSurfaceReader::readFromLine().
readLine()
void readLine (ISstream & is, string & buffer) const protected
Definition at line 81 of file ensightSurfaceReader.C.
References Foam::stringOps::inplaceTrimRight(), and Foam::pos().
debugSection()
void debugSection (const word & expected, ISstream & is) const protected
Definition at line 99 of file ensightSurfaceReader.C.
References DebugInfo, Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, and Foam::nl.
replaceMask()
Foam::fileName replaceMask (const fileName & fName, const label timeIndex) static protected
Definition at line 121 of file ensightSurfaceReader.C.
References Foam::stringOps::count(), ensightCase::padded(), string::replace(), and timeIndex.
readGeometryHeader()
Foam::Pair< Foam::ensightSurfaceReader::idTypes > readGeometryHeader (ensightReadFile & is) const protected
Definition at line 146 of file ensightSurfaceReader.C.
References string::contains(), DebugInfo, UPtrList< T >::first(), and Foam::nl.
readCase()
void readCase (ISstream & is) protected
Definition at line 223 of file ensightSurfaceReader.C.
References UPtrList< T >::back(), string::contains(), DebugInfo, DebugInFunction, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::Info, Foam::name(), Foam::nl, PtrList< T >::push_back(), s(), UPtrList< T >::size(), Foam::stringOps::splitSpace(), PtrList< T >::transfer(), and WarningInFunction.
Referenced by ensightSurfaceReader::ensightSurfaceReader().
readGeometry()
Foam::meshedSurface readGeometry (const fileName & geometryFile) protected
Definition at line 386 of file ensightSurfaceReader.C.
References DebugInfo, DebugInFunction, ensightFaces::elemNames, Foam::endl(), f(), UPtrList< T >::first(), IOstreamOption::formatNames, VectorSpace< Form, Cmpt, Ncmpts >::nComponents, Foam::nl, nPoints, ensightFaces::NSIDED, p, points, PtrList< T >::push_back(), ensightFaces::QUAD4, UList< T >::size(), PtrList< T >::transfer(), ensightFaces::TRIA3, and WarningInFunction.
readFromLine() [1/2]
template<class Type > void readFromLine (const label nSkip, Istream & is, Type & value) const protected
Definition at line 27 of file ensightSurfaceReaderTemplates.C.
References ensightSurfaceReader::skip().
readFromLine() [2/2]
template<class Type > void readFromLine (const label nSkip, const string & buffer, Type & value) const protected
Definition at line 41 of file ensightSurfaceReaderTemplates.C.
readField() [1/4]
template<class Type > tmp< Field< Type > > readField (const fileName & dataFile, const word & fieldName) const protected
readField() [2/4]
template<class Type > tmp< Field< Type > > readField (const label timeIndex, const label fieldIndex) const protected
TypeName()
TypeName ("ensight")
geometry()
const Foam::meshedSurface & geometry (const label timeIndex) virtual
Implements surfaceReader.
Definition at line 621 of file ensightSurfaceReader.C.
References Pstream::broadcast(), DebugInFunction, Foam::endl(), UPstream::master(), UPstream::parRun(), timeIndex, and UPstream::worldComm.
times()
Foam::instantList times () const virtual
Implements surfaceReader.
Definition at line 651 of file ensightSurfaceReader.C.
fieldNames()
Foam::wordList fieldNames (const label timeIndex) const virtual
Implements surfaceReader.
Definition at line 657 of file ensightSurfaceReader.C.
field() [1/5]
Foam::tmp< Foam::Field< Foam::scalar > > field (const label timeIndex, const label fieldIndex, const scalar & refValue = pTraits<scalar>::zero) const virtual
Implements surfaceReader.
Definition at line 666 of file ensightSurfaceReader.C.
References timeIndex.
field() [2/5]
Foam::tmp< Foam::Field< Foam::vector > > field (const label timeIndex, const label fieldIndex, const vector & refValue = pTraits<vector>::zero) const virtual
Implements surfaceReader.
Definition at line 677 of file ensightSurfaceReader.C.
References timeIndex.
field() [3/5]
Foam::tmp< Foam::Field< Foam::sphericalTensor > > field (const label timeIndex, const label fieldIndex, const sphericalTensor & refValue = pTraits<sphericalTensor>::zero) const virtual
Implements surfaceReader.
Definition at line 689 of file ensightSurfaceReader.C.
References timeIndex.
field() [4/5]
Foam::tmp< Foam::Field< Foam::symmTensor > > field (const label timeIndex, const label fieldIndex, const symmTensor & refValue = pTraits<symmTensor>::zero) const virtual
Implements surfaceReader.
Definition at line 700 of file ensightSurfaceReader.C.
References timeIndex.
field() [5/5]
Foam::tmp< Foam::Field< Foam::tensor > > field (const label timeIndex, const label fieldIndex, const tensor & refValue = pTraits<tensor>::zero) const virtual
Implements surfaceReader.
Definition at line 711 of file ensightSurfaceReader.C.
References timeIndex.
readField() [3/4]
template<class Type > Foam::tmp< Foam::Field< Type > > readField (const fileName & dataFile, const word & fieldName) const
Definition at line 55 of file ensightSurfaceReaderTemplates.C.
References Pstream::broadcast(), DebugInfo, ensightFaces::elemNames, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, field(), UPtrList< T >::first(), IOWarningInFunction, UPstream::master(), Foam::New(), Foam::nl, UPstream::parRun(), Foam::setComponent(), UPstream::worldComm, and Foam::Zero.
readField() [4/4]
template<class Type > Foam::tmp< Foam::Field< Type > > readField (const label timeIndex, const label fieldIndex) const
Definition at line 162 of file ensightSurfaceReaderTemplates.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::flatOutput(), Foam::nl, Foam::Pout, UPtrList< T >::size(), and timeIndex.
Member Data Documentation
masterOnly_
bool masterOnly_ protected
Definition at line 108 of file ensightSurfaceReader.H.
Referenced by ensightSurfaceReader::ensightSurfaceReader().
readFormat_
IOstreamOption::streamFormat readFormat_ protected
Definition at line 111 of file ensightSurfaceReader.H.
baseDir_
fileName baseDir_ protected
Definition at line 114 of file ensightSurfaceReader.H.
meshFileName_
fileName meshFileName_ protected
Definition at line 117 of file ensightSurfaceReader.H.
Referenced by ensightSurfaceReader::ensightSurfaceReader().
fieldNames_
List<word> fieldNames_ protected
Definition at line 120 of file ensightSurfaceReader.H.
Referenced by ensightSurfaceReader::ensightSurfaceReader().
fieldFileNames_
List<string> fieldFileNames_ protected
Definition at line 123 of file ensightSurfaceReader.H.
Referenced by ensightSurfaceReader::ensightSurfaceReader().
nTimeSteps_
label nTimeSteps_ protected
Definition at line 126 of file ensightSurfaceReader.H.
Referenced by ensightSurfaceReader::ensightSurfaceReader().
timeStartIndex_
label timeStartIndex_ protected
Definition at line 129 of file ensightSurfaceReader.H.
Referenced by ensightSurfaceReader::ensightSurfaceReader().
timeIncrement_
label timeIncrement_ protected
Definition at line 132 of file ensightSurfaceReader.H.
Referenced by ensightSurfaceReader::ensightSurfaceReader().
timeValues_
instantList timeValues_ protected
Definition at line 135 of file ensightSurfaceReader.H.
Referenced by ensightSurfaceReader::ensightSurfaceReader().
surfPtr_
autoPtr<meshedSurface> surfPtr_ protected
Definition at line 138 of file ensightSurfaceReader.H.
faceTypeInfo_
List<faceInfoTuple> faceTypeInfo_ protected
Definition at line 141 of file ensightSurfaceReader.H.
The documentation for this class was generated from the following files:
src/surfMesh/readers/ensight/ensightSurfaceReader.H
src/surfMesh/readers/ensight/ensightSurfaceReader.C
src/surfMesh/readers/ensight/ensightSurfaceReaderTemplates.C