OpenFOAM: phasePressureModel Class Reference
phasePressureModel Class Reference
Particle-particle phase-pressure RAS model.
#include <phasePressureModel.H>
Public Member Functions
TypeName ("phasePressure")
phasePressureModel (const volScalarField &alpha, const volScalarField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const phaseModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
virtual ~phasePressureModel ()=default
virtual bool read ()
virtual tmp< volScalarField > nuEff () const
virtual tmp< scalarField > nuEff (const label patchi) const
virtual tmp< volScalarField > k () const
virtual tmp< volScalarField > epsilon () const
virtual tmp< volScalarField > omega () const
virtual tmp< volSymmTensorField > R () const
virtual tmp< volScalarField > pPrime () const
virtual tmp< surfaceScalarField > pPrimef () const
virtual tmp< volSymmTensorField > devRhoReff () const
virtual tmp< volSymmTensorField > devRhoReff (const volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
virtual void correct ()
TypeName ("phasePressure")
phasePressureModel (const volScalarField &alpha, const volScalarField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const phaseModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
virtual ~phasePressureModel ()=default
virtual bool read ()
virtual tmp< volScalarField > nuEff () const
virtual tmp< scalarField > nuEff (const label patchi) const
virtual tmp< volScalarField > k () const
virtual tmp< volScalarField > epsilon () const
virtual tmp< volScalarField > omega () const
virtual tmp< volSymmTensorField > R () const
virtual tmp< volScalarField > pPrime () const
virtual tmp< surfaceScalarField > pPrimef () const
virtual tmp< volSymmTensorField > devRhoReff () const
virtual tmp< volSymmTensorField > devRhoReff (const volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
virtual void correct ()
Public Member Functions inherited from eddyViscosity< RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > > >
eddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~eddyViscosity ()=default
virtual tmp< volScalarField > nut () const
virtual tmp< scalarField > nut (const label patchi) const
virtual void validate ()
Public Member Functions inherited from linearViscousStress< BasicTurbulenceModel >
linearViscousStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~linearViscousStress ()=default
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Public Member Functions inherited from eddyViscosity< RASModel< EddyDiffusivity< ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > > > > >
eddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~eddyViscosity ()=default
virtual tmp< volScalarField > nut () const
virtual tmp< scalarField > nut (const label patchi) const
virtual void validate ()
Additional Inherited Members
Public Types inherited from eddyViscosity< RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > > >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from linearViscousStress< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from eddyViscosity< RASModel< EddyDiffusivity< ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > > > > >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Protected Attributes inherited from eddyViscosity< RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > > >
volScalarField nut_
Protected Attributes inherited from eddyViscosity< RASModel< EddyDiffusivity< ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > > > > >
volScalarField nut_
Detailed Description
Particle-particle phase-pressure RAS model.
The derivative of the phase-pressure with respect to the phase-fraction is evaluated as
g0*min(exp(preAlphaExp*(alpha - alphaMax)), expMax)
The default model coefficients correspond to the following:
    phasePressureCoeffs
    {
        preAlphaExp     500;
        expMax          1000;
        alphaMax        0.62;
        g0              1000;
    }
Source files
phasePressureModel.H
phasePressureModel.C
Definition at line 69 of file phasePressureModel.H.
Constructor & Destructor Documentation
phasePressureModel() [1/2]
phasePressureModel (const volScalarField & alpha, const volScalarField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const phaseModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
~phasePressureModel() [1/2]
virtual ~phasePressureModel () virtual default
phasePressureModel() [2/2]
phasePressureModel (const volScalarField & alpha, const volScalarField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const phaseModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
~phasePressureModel() [2/2]
virtual ~phasePressureModel () virtual default
Member Function Documentation
TypeName() [1/2]
TypeName ("phasePressure")
read() [1/2]
bool read () virtual
Implements eddyViscosity< RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > > >.
Definition at line 70 of file phasePressureModel.C.
References phasePressureModel::read(), and dimensioned< Type >::readIfPresent().
Referenced by phasePressureModel::read().
nuEff() [1/4]
virtual tmp< volScalarField > nuEff () const inline virtual
Definition at line 138 of file phasePressureModel.H.
References eddyViscosity< RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > > >::nut().
nuEff() [2/4]
virtual tmp< scalarField > nuEff (const label patchi) const inline virtual
Definition at line 144 of file phasePressureModel.H.
References eddyViscosity< RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > > >::nut().
k() [1/2]
Foam::tmp< Foam::volScalarField > k () const virtual
Implements eddyViscosity< RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > > >.
Definition at line 93 of file phasePressureModel.C.
References NotImplemented.
epsilon() [1/2]
Foam::tmp< Foam::volScalarField > epsilon () const virtual
Definition at line 101 of file phasePressureModel.C.
References NotImplemented.
omega() [1/2]
Foam::tmp< Foam::volScalarField > omega () const virtual
Definition at line 109 of file phasePressureModel.C.
References NotImplemented.
R() [1/2]
Foam::tmp< Foam::volSymmTensorField > R () const virtual
Reimplemented from eddyViscosity< RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > > >.
Definition at line 117 of file phasePressureModel.C.
References IOobject::groupName(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, and Foam::Zero.
pPrime() [1/2]
Foam::tmp< Foam::volScalarField > pPrime () const virtual
Definition at line 139 of file phasePressureModel.C.
References coupled(), Foam::exp(), forAll, and Foam::min().
pPrimef() [1/2]
Foam::tmp< Foam::surfaceScalarField > pPrimef () const virtual
Definition at line 167 of file phasePressureModel.C.
References coupled(), Foam::exp(), forAll, Foam::fvc::interpolate(), and Foam::min().
devRhoReff() [1/4]
Foam::tmp< Foam::volSymmTensorField > devRhoReff () const virtual
Reimplemented from linearViscousStress< BasicTurbulenceModel >.
Definition at line 195 of file phasePressureModel.C.
devRhoReff() [2/4]
Foam::tmp< Foam::volSymmTensorField > devRhoReff (const volVectorField & U) const virtual
Reimplemented from linearViscousStress< BasicTurbulenceModel >.
Definition at line 202 of file phasePressureModel.C.
References IOobject::groupName(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, U, and Foam::Zero.
divDevRhoReff() [1/2]
Foam::tmp< Foam::fvVectorMatrix > divDevRhoReff (volVectorField & U) const virtual
Reimplemented from linearViscousStress< BasicTurbulenceModel >.
Definition at line 232 of file phasePressureModel.C.
References U.
correct() [1/2]
void correct () virtual
Implements eddyViscosity< RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > > >.
Definition at line 248 of file phasePressureModel.C.
TypeName() [2/2]
TypeName ("phasePressure")
read() [2/2]
virtual bool read () virtual
Implements eddyViscosity< RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > > >.
nuEff() [3/4]
virtual tmp< volScalarField > nuEff () const inline virtual
Definition at line 142 of file phasePressureModel.H.
References eddyViscosity< RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > > >::nut().
nuEff() [4/4]
virtual tmp< scalarField > nuEff (const label patchi) const inline virtual
Definition at line 148 of file phasePressureModel.H.
References eddyViscosity< RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > > >::nut().
k() [2/2]
virtual tmp< volScalarField > k () const virtual
Implements eddyViscosity< RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > > >.
epsilon() [2/2]
virtual tmp< volScalarField > epsilon () const virtual
omega() [2/2]
virtual tmp< volScalarField > omega () const virtual
R() [2/2]
virtual tmp< volSymmTensorField > R () const virtual
Reimplemented from eddyViscosity< RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > > >.
pPrime() [2/2]
virtual tmp< volScalarField > pPrime () const virtual
pPrimef() [2/2]
virtual tmp< surfaceScalarField > pPrimef () const virtual
devRhoReff() [3/4]
virtual tmp< volSymmTensorField > devRhoReff () const virtual
Reimplemented from linearViscousStress< BasicTurbulenceModel >.
devRhoReff() [4/4]
virtual tmp< volSymmTensorField > devRhoReff (const volVectorField & U) const virtual
Reimplemented from linearViscousStress< BasicTurbulenceModel >.
divDevRhoReff() [2/2]
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField & U) const virtual
Reimplemented from linearViscousStress< BasicTurbulenceModel >.
correct() [2/2]
virtual void correct () virtual
Implements eddyViscosity< RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > > >.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/twoPhaseCompressibleTurbulenceModels/phasePressureModel/phasePressureModel.H
src/phaseSystemModels/twoPhaseEuler/phaseCompressibleTurbulenceModels/phasePressureModel/phasePressureModel.H
src/phaseSystemModels/reactingEuler/twoPhaseCompressibleTurbulenceModels/phasePressureModel/phasePressureModel.C
src/phaseSystemModels/twoPhaseEuler/phaseCompressibleTurbulenceModels/phasePressureModel/phasePressureModel.C