OpenFOAM: wideBandAbsorptionEmission Class Reference
wideBandAbsorptionEmission Class Reference
Thermophysical models » Radiation models » Sub-models » Absorption and emission sub-models
wideBandAbsorptionEmission radiation absorption and emission coefficients for continuous phase.
#include <wideBandAbsorptionEmission.H>
Public Member Functions
TypeName ("wideBandAbsorptionEmission")
wideBandAbsorptionEmission (const dictionary &dict, const fvMesh &mesh)
virtual ~wideBandAbsorptionEmission ()
tmp< volScalarField > aCont (const label bandi=0) const
tmp< volScalarField > eCont (const label bandi=0) const
tmp< volScalarField > ECont (const label bandi=0) const
bool isGrey () const
label nBands () const
const Vector2D< scalar > & bands (const label bandi) const
void correct (volScalarField &a, PtrList< volScalarField > &aLambda) const
Public Member Functions inherited from absorptionEmissionModel
TypeName ("absorptionEmissionModel")
declareRunTimeSelectionTable (autoPtr, absorptionEmissionModel, dictionary,(const dictionary &dict, const fvMesh &mesh),(dict, mesh))
absorptionEmissionModel (const dictionary &dict, const fvMesh &mesh)
virtual ~absorptionEmissionModel ()
const fvMesh & mesh () const
const dictionary & dict () const
virtual tmp< volScalarField > a (const label bandI=0) const
virtual tmp< volScalarField > aDisp (const label bandI=0) const
virtual tmp< volScalarField > e (const label bandI=0) const
virtual tmp< volScalarField > eDisp (const label bandI=0) const
virtual tmp< volScalarField > E (const label bandI=0) const
virtual tmp< volScalarField > EDisp (const label bandI=0) const
Public Attributes
FixedList< FixedList< absorptionCoeffs, nSpecies_ >, maxBands_ > coeffs_
Static Public Attributes
static const int nSpecies_ = 5
static const int maxBands_ = 10
Additional Inherited Members
Static Public Member Functions inherited from absorptionEmissionModel
static autoPtr< absorptionEmissionModel > New (const dictionary &dict, const fvMesh &mesh)
Protected Attributes inherited from absorptionEmissionModel
const dictionary dict_
const fvMesh & mesh_
Detailed Description
wideBandAbsorptionEmission radiation absorption and emission coefficients for continuous phase.
All the bands should have the same number of species and have to be entered in the same order.
There is no check of continuity of the bands. They should not ovelap or have gaps.
The emission constant proportionality is specified per band (EhrrCoeff).
The coefficients for the species have to be specified for use in moles x P [atm], i.e. (k[i] = species[i]*p*9.869231e-6).
The look Up table file should be in the constant directory.
band dictionary:
    band0
    {
        bandLimits (1.0e-6 2.63e-6);
        EhrrCoeff       0.0;
        species
        {
            CH4
            {
                Tcommon         300.;
                Tlow            300.;
                Thigh           2500.;
                invTemp         false;
                loTcoeffs (0 0 0 0 0 0) ;
                hiTcoeffs (.1 0 0 0 0 0);
            }
            CO2
            {
                Tcommon         300.;
                Tlow            300.;
                Thigh           2500.;
                invTemp         false;
                loTcoeffs (0 0 0 0 0 0) ;
                hiTcoeffs (.1 0 0 0 0 0);
            }
            H2O
            {
                Tcommon         300.;
                Tlow            300.;
                Thigh           2500.;
                invTemp         false;
                loTcoeffs (0 0 0 0 0 0) ;
                hiTcoeffs (.1 0 0 0 0 0);
            }
            Ysoot
            {
                Tcommon         300.;
                Tlow            300.;
                Thigh           2500.;
                invTemp         false;
                loTcoeffs (0 0 0 0 0 0) ;
                hiTcoeffs (.1 0 0 0 0 0);
            }
        }
    }
Source files
wideBandAbsorptionEmission.H
wideBandAbsorptionEmission.C
Definition at line 119 of file wideBandAbsorptionEmission.H.
Constructor & Destructor Documentation
wideBandAbsorptionEmission()
wideBandAbsorptionEmission (const dictionary & dict, const fvMesh & mesh)
Definition at line 47 of file wideBandAbsorptionEmission.C.
References wideBandAbsorptionEmission::coeffs_, absorptionEmissionModel::dict(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAllConstIters, HashTable< T, Key, Hash >::found(), dictionary::found(), dictionary::get(), Foam::Info, HashTable< T, Key, Hash >::insert(), absorptionEmissionModel::mesh(), Foam::nl, and PtrList< T >::set().
~wideBandAbsorptionEmission()
~wideBandAbsorptionEmission () virtual
Definition at line 187 of file wideBandAbsorptionEmission.C.
Member Function Documentation
TypeName()
TypeName ("wideBandAbsorptionEmission")
aCont()
Foam::tmp< Foam::volScalarField > aCont (const label bandi = 0) const virtual
Reimplemented from absorptionEmissionModel.
Definition at line 194 of file wideBandAbsorptionEmission.C.
References b, Foam::dimLength, Foam::dimless, UList< T >::find(), forAll, forAllConstIters, mesh, n, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, p, Foam::paToAtm(), s(), T, GeometricField< Type, PatchField, GeoMesh >::T(), timeName, and Foam::Zero.
eCont()
Foam::tmp< Foam::volScalarField > eCont (const label bandi = 0) const virtual
Reimplemented from absorptionEmissionModel.
Definition at line 277 of file wideBandAbsorptionEmission.C.
ECont()
Foam::tmp< Foam::volScalarField > ECont (const label bandi = 0) const virtual
Reimplemented from absorptionEmissionModel.
Definition at line 284 of file wideBandAbsorptionEmission.C.
References Foam::dimEnergy, Foam::dimLength, Foam::dimMass, Foam::dimTime, Foam::dimVolume, Foam::endl(), mesh, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, Foam::pow3(), Qdot, timeName, WarningInFunction, and Foam::Zero.
isGrey()
bool isGrey () const inline virtual
Reimplemented from absorptionEmissionModel.
Definition at line 200 of file wideBandAbsorptionEmission.H.
nBands()
label nBands () const inline virtual
Reimplemented from absorptionEmissionModel.
Definition at line 206 of file wideBandAbsorptionEmission.H.
bands()
const Vector2D< scalar > & bands (const label bandi) const inline virtual
Reimplemented from absorptionEmissionModel.
Definition at line 212 of file wideBandAbsorptionEmission.H.
correct()
void correct (volScalarField & a, PtrList< volScalarField > & aLambda) const virtual
Reimplemented from absorptionEmissionModel.
Definition at line 337 of file wideBandAbsorptionEmission.C.
References Foam::dimLength, Foam::dimless, GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef(), and Foam::Zero.
Member Data Documentation
nSpecies_
const int nSpecies_ = 5 static
Definition at line 128 of file wideBandAbsorptionEmission.H.
maxBands_
const int maxBands_ = 10 static
Definition at line 131 of file wideBandAbsorptionEmission.H.
coeffs_
FixedList<FixedList<absorptionCoeffs, nSpecies_>, maxBands_> coeffs_
Definition at line 134 of file wideBandAbsorptionEmission.H.
Referenced by wideBandAbsorptionEmission::wideBandAbsorptionEmission().
The documentation for this class was generated from the following files:
src/thermophysicalModels/radiation/submodels/absorptionEmissionModel/wideBandAbsorptionEmission/wideBandAbsorptionEmission.H
src/thermophysicalModels/radiation/submodels/absorptionEmissionModel/wideBandAbsorptionEmission/wideBandAbsorptionEmission.C