OpenFOAM: Tensor< Cmpt > Class Template Reference
Tensor< Cmpt > Class Template Reference
A templated (3 x 3) tensor of objects of <T> derived from MatrixSpace.
#include <Tensor.H>
Public Types
enum components {
XX , XY , XZ , YX ,
YY , YZ , ZX , ZY ,
ZZ
}
typedef Tensor< label > labelType
Public Types inherited from MatrixSpace< Tensor< Cmpt >, Cmpt, 3, 3 >
typedef MatrixSpace< Tensor< Cmpt >, Cmpt, Mrows, Ncols > msType
Public Types inherited from VectorSpace< Form, Cmpt, Ncmpts >
typedef VectorSpace< Form, Cmpt, Ncmpts > vsType
typedef Cmpt cmptType
typedef Cmpt magType
typedef Cmpt * iterator
typedef const Cmpt * const_iterator
Public Member Functions
Tensor ()=default
Tensor (const Tensor &)=default
Tensor & operator= (const Tensor &)=default
Tensor (const Foam::zero)
template<class Cmpt2 >
Tensor (const MatrixSpace< Tensor< Cmpt2 >, Cmpt2, 3, 3 > &vs)
template<class Cmpt2 >
Tensor (const VectorSpace< Tensor< Cmpt2 >, Cmpt2, 9 > &vs)
Tensor (const SphericalTensor< Cmpt > &st)
Tensor (const SymmTensor< Cmpt > &st)
Tensor (const Vector< Vector< Cmpt > > &vecs, const bool transposed=false)
Tensor (const Vector< Cmpt > &x, const Vector< Cmpt > &y, const Vector< Cmpt > &z, const bool transposed=false)
Tensor (const Cmpt txx, const Cmpt txy, const Cmpt txz, const Cmpt tyx, const Cmpt tyy, const Cmpt tyz, const Cmpt tzx, const Cmpt tzy, const Cmpt tzz)
template<template< class, direction, direction > class Block2, direction BRowStart, direction BColStart>
Tensor (const Block2< Tensor< Cmpt >, BRowStart, BColStart > &block)
Tensor (Istream &is)
const Cmpt & xx () const noexcept
const Cmpt & xy () const noexcept
const Cmpt & xz () const noexcept
const Cmpt & yx () const noexcept
const Cmpt & yy () const noexcept
const Cmpt & yz () const noexcept
const Cmpt & zx () const noexcept
const Cmpt & zy () const noexcept
const Cmpt & zz () const noexcept
Cmpt & xx () noexcept
Cmpt & xy () noexcept
Cmpt & xz () noexcept
Cmpt & yx () noexcept
Cmpt & yy () noexcept
Cmpt & yz () noexcept
Cmpt & zx () noexcept
Cmpt & zy () noexcept
Cmpt & zz () noexcept
Vector< Cmpt > cx () const
Vector< Cmpt > cy () const
Vector< Cmpt > cz () const
template<direction Idx>
Vector< Cmpt > col () const
Vector< Cmpt > col (const direction c) const
template<direction Idx>
void col (const Vector< Cmpt > &v)
void col (const direction c, const Vector< Cmpt > &v)
void cols (const Vector< Cmpt > &x, const Vector< Cmpt > &y, const Vector< Cmpt > &z)
Vector< Cmpt > x () const
Vector< Cmpt > y () const
Vector< Cmpt > z () const
template<direction Idx>
Vector< Cmpt > row () const
Vector< Cmpt > row (const direction r) const
template<direction Idx>
void row (const Vector< Cmpt > &v)
void row (const direction r, const Vector< Cmpt > &v)
void rows (const Vector< Cmpt > &x, const Vector< Cmpt > &y, const Vector< Cmpt > &z)
Vector< Cmpt > diag () const
void diag (const Vector< Cmpt > &v)
void addDiag (const Vector< Cmpt > &v)
void subtractDiag (const Vector< Cmpt > &v)
scalar diagSqr () const
bool is_identity (const scalar tol=ROOTVSMALL) const
Tensor< Cmpt > T () const
Cmpt det () const
Cmpt det2D (const direction excludeCmpt) const
Tensor< Cmpt > adjunct () const
Tensor< Cmpt > cof () const
Tensor< Cmpt > adjunct2D (const direction excludeCmpt) const
Tensor< Cmpt > inv () const
Tensor< Cmpt > safeInv () const
Tensor< Cmpt > inv2D (const direction excludeCmpt) const
Tensor< Cmpt > inner (const Tensor< Cmpt > &t2) const
Tensor< Cmpt > schur (const Tensor< Cmpt > &t2) const
void operator&= (const Tensor< Cmpt > &t)
template<class Cmpt2 >
void operator= (const VectorSpace< Tensor< Cmpt2 >, Cmpt2, 9 > &)
void operator= (const SphericalTensor< Cmpt > &)
void operator= (const SymmTensor< Cmpt > &)
void operator= (const Vector< Vector< Cmpt > > &)
Vector< Cmpt > vectorComponent (const direction cmpt) const
const Foam::Tensor< float > I (1, 0, 0, 0, 1, 0, 0, 0, 1)
const Foam::Tensor< double > I (1, 0, 0, 0, 1, 0, 0, 0, 1)
template<Foam::direction Idx>
Foam::Vector< Cmpt > col () const
template<Foam::direction Idx>
Foam::Vector< Cmpt > row () const
Public Member Functions inherited from MatrixSpace< Tensor< Cmpt >, Cmpt, 3, 3 >
MatrixSpace ()=default
MatrixSpace (const Foam::zero)
MatrixSpace (const VectorSpace< Form2, Cmpt2, Mrows *Ncols > &)
MatrixSpace (const Block2< Tensor< Cmpt >, BRowStart, BColStart > &block)
MatrixSpace (Istream &is)
const Cmpt & elmt () const noexcept
Cmpt & elmt () noexcept
const Cmpt & xx () const noexcept
Cmpt & xx () noexcept
const Cmpt & xy () const noexcept
Cmpt & xy () noexcept
const Cmpt & xz () const noexcept
Cmpt & xz () noexcept
const Cmpt & yx () const noexcept
Cmpt & yx () noexcept
const Cmpt & yy () const noexcept
Cmpt & yy () noexcept
const Cmpt & yz () const noexcept
Cmpt & yz () noexcept
const Cmpt & zx () const noexcept
Cmpt & zx () noexcept
const Cmpt & zy () const noexcept
Cmpt & zy () noexcept
const Cmpt & zz () const noexcept
Cmpt & zz () noexcept
typeOfTranspose< Cmpt, Tensor< Cmpt > >::type T () const
ConstBlock< SubTensor, BRowStart, BColStart > block () const
Block< SubTensor, BRowStart, BColStart > block ()
Foam::MatrixSpace< Tensor< Cmpt >, Cmpt, Mrows, Ncols >::template ConstBlock< SubTensor, BRowStart, BColStart > block () const
Foam::MatrixSpace< Tensor< Cmpt >, Cmpt, Mrows, Ncols >::template Block< SubTensor, BRowStart, BColStart > block ()
const Cmpt & operator() (const direction &i, const direction &j) const
Cmpt & operator() (const direction &i, const direction &j)
void operator= (const Foam::zero)
void operator= (const Block2< Tensor< Cmpt >, BRowStart, BColStart > &block)
void operator&= (const MatrixSpace< Tensor< Cmpt >, Cmpt, Ncols, Ncols > &matrix)
Public Member Functions inherited from VectorSpace< Form, Cmpt, Ncmpts >
VectorSpace ()=default
VectorSpace (const Foam::zero)
VectorSpace (const VectorSpace< Form, Cmpt, Ncmpts > &vs)
template<class Form2 , class Cmpt2 >
VectorSpace (const VectorSpace< Form2, Cmpt2, Ncmpts > &)
VectorSpace (Istream &is)
const Cmpt & component (const direction) const
Cmpt & component (const direction)
void component (Cmpt &, const direction) const
void replace (const direction, const Cmpt &)
const Cmpt * cdata () const noexcept
Cmpt * data () noexcept
template<class SubVector , direction BStart>
const ConstBlock< SubVector, BStart > block () const
const Cmpt & operator[] (const direction) const
Cmpt & operator[] (const direction)
void operator= (const VectorSpace< Form, Cmpt, Ncmpts > &)
void operator+= (const VectorSpace< Form, Cmpt, Ncmpts > &)
void operator-= (const VectorSpace< Form, Cmpt, Ncmpts > &)
void operator= (const Foam::zero)
void operator*= (const scalar)
void operator/= (const scalar)
iterator begin () noexcept
iterator end () noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
const_iterator begin () const noexcept
const_iterator end () const noexcept
template<class SubVector , Foam::direction BStart>
const Foam::VectorSpace< Form, Cmpt, Ncmpts >::template ConstBlock< SubVector, BStart > block () const
Static Public Attributes
static constexpr direction rank = 2
static const Tensor I
Static Public Attributes inherited from MatrixSpace< Tensor< Cmpt >, Cmpt, 3, 3 >
static constexpr direction mRows
static constexpr direction nCols
Static Public Attributes inherited from VectorSpace< Form, Cmpt, Ncmpts >
static constexpr direction dim = 3
static constexpr direction nComponents = Ncmpts
static constexpr direction mRows = Ncmpts
static constexpr direction nCols = 1
static const char *const typeName = "diagTensor"
static const char *const componentNames []
static const Form zero
static const Form one
static const Form max
static const Form min
static const Form rootMax
static const Form rootMin
Additional Inherited Members
Static Public Member Functions inherited from MatrixSpace< Tensor< Cmpt >, Cmpt, 3, 3 >
static direction m () noexcept
static direction n () noexcept
static msType identity ()
Static Public Member Functions inherited from VectorSpace< Form, Cmpt, Ncmpts >
static constexpr direction size () noexcept
static Form uniform (const Cmpt &s)
Public Attributes inherited from VectorSpace< Form, Cmpt, Ncmpts >
Cmpt v_ [Ncmpts]
Detailed Description
template<class Cmpt>
class Foam::Tensor< Cmpt >
A templated (3 x 3) tensor of objects of <T> derived from MatrixSpace.
Source files
Tensor.H
TensorI.H
See also
Foam::MatrixSpace Foam::Vector
Definition at line 57 of file Tensor.H.
Member Typedef Documentation
labelType
template<class Cmpt > typedef Tensor<label> labelType
Definition at line 66 of file Tensor.H.
Member Enumeration Documentation
components
template<class Cmpt > enum components
Enumerator
XX
XY
XZ
YX
YY
YZ
ZX
ZY
ZZ
Definition at line 81 of file Tensor.H.
Constructor & Destructor Documentation
Tensor() [1/12]
template<class Cmpt > Tensor () default
Tensor() [2/12]
template<class Cmpt > Tensor (const Tensor< Cmpt > &) default
Tensor() [3/12]
template<class Cmpt > Tensor (const Foam::zero) inline
Definition at line 29 of file TensorI.H.
Tensor() [4/12]
template<class Cmpt > template<class Cmpt2 > Tensor (const MatrixSpace< Tensor< Cmpt2 >, Cmpt2, 3, 3 > & vs) inline
Definition at line 37 of file TensorI.H.
Tensor() [5/12]
template<class Cmpt > template<class Cmpt2 > Tensor (const VectorSpace< Tensor< Cmpt2 >, Cmpt2, 9 > & vs) inline
Definition at line 48 of file TensorI.H.
Tensor() [6/12]
template<class Cmpt > Tensor (const SphericalTensor< Cmpt > & st) inline
Definition at line 58 of file TensorI.H.
References Foam::Zero.
Tensor() [7/12]
template<class Cmpt > Tensor (const SymmTensor< Cmpt > & st) inline
Definition at line 67 of file TensorI.H.
Tensor() [8/12]
template<class Cmpt > Tensor (const Vector< Vector< Cmpt > > & vecs, const bool transposed = false) inline
Definition at line 76 of file TensorI.H.
Tensor() [9/12]
template<class Cmpt > Tensor (const Vector< Cmpt > & x, const Vector< Cmpt > & y, const Vector< Cmpt > & z, const bool transposed = false) inline
Definition at line 87 of file TensorI.H.
References x, and y.
Tensor() [10/12]
template<class Cmpt > Tensor (const Cmpt txx, const Cmpt txy, const Cmpt txz, const Cmpt tyx, const Cmpt tyy, const Cmpt tyz, const Cmpt tzx, const Cmpt tzy, const Cmpt tzz) inline
Definition at line 107 of file TensorI.H.
Tensor() [11/12]
template<class Cmpt > template<template< class, Foam::direction, Foam::direction > class Block2, Foam::direction BRowStart, Foam::direction BColStart> Tensor (const Block2< Tensor< Cmpt >, BRowStart, BColStart > & block) inline
Definition at line 127 of file TensorI.H.
Tensor() [12/12]
template<class Cmpt > Tensor (Istream & is) inline explicit
Definition at line 137 of file TensorI.H.
Member Function Documentation
operator=() [1/5]
template<class Cmpt > Tensor & operator= (const Tensor< Cmpt > &) default
xx() [1/2]
template<class Cmpt > const Cmpt & xx () const inline noexcept
Definition at line 161 of file Tensor.H.
References VectorSpace< Form, Cmpt, Ncmpts >::v_, and Tensor< Cmpt >::XX.
Referenced by momentOfInertia::massPropertiesSolid(), Foam::pinv(), and quaternion::quaternion().
xy() [1/2]
template<class Cmpt > const Cmpt & xy () const inline noexcept
Definition at line 162 of file Tensor.H.
References VectorSpace< Form, Cmpt, Ncmpts >::v_, and Tensor< Cmpt >::XY.
Referenced by momentOfInertia::massPropertiesSolid(), Foam::pinv(), and quaternion::quaternion().
xz() [1/2]
template<class Cmpt > const Cmpt & xz () const inline noexcept
Definition at line 163 of file Tensor.H.
References VectorSpace< Form, Cmpt, Ncmpts >::v_, and Tensor< Cmpt >::XZ.
Referenced by momentOfInertia::massPropertiesSolid(), Foam::pinv(), and quaternion::quaternion().
yx() [1/2]
template<class Cmpt > const Cmpt & yx () const inline noexcept
Definition at line 164 of file Tensor.H.
References VectorSpace< Form, Cmpt, Ncmpts >::v_, and Tensor< Cmpt >::YX.
Referenced by momentOfInertia::massPropertiesSolid(), Foam::pinv(), and quaternion::quaternion().
yy() [1/2]
template<class Cmpt > const Cmpt & yy () const inline noexcept
Definition at line 165 of file Tensor.H.
References VectorSpace< Form, Cmpt, Ncmpts >::v_, and Tensor< Cmpt >::YY.
Referenced by momentOfInertia::massPropertiesSolid(), Foam::pinv(), and quaternion::quaternion().
yz() [1/2]
template<class Cmpt > const Cmpt & yz () const inline noexcept
Definition at line 166 of file Tensor.H.
References VectorSpace< Form, Cmpt, Ncmpts >::v_, and Tensor< Cmpt >::YZ.
Referenced by momentOfInertia::massPropertiesSolid(), Foam::pinv(), and quaternion::quaternion().
zx() [1/2]
template<class Cmpt > const Cmpt & zx () const inline noexcept
Definition at line 167 of file Tensor.H.
References VectorSpace< Form, Cmpt, Ncmpts >::v_, and Tensor< Cmpt >::ZX.
Referenced by momentOfInertia::massPropertiesSolid(), Foam::pinv(), and quaternion::quaternion().
zy() [1/2]
template<class Cmpt > const Cmpt & zy () const inline noexcept
Definition at line 168 of file Tensor.H.
References VectorSpace< Form, Cmpt, Ncmpts >::v_, and Tensor< Cmpt >::ZY.
Referenced by momentOfInertia::massPropertiesSolid(), Foam::pinv(), and quaternion::quaternion().
zz() [1/2]
template<class Cmpt > const Cmpt & zz () const inline noexcept
Definition at line 169 of file Tensor.H.
References VectorSpace< Form, Cmpt, Ncmpts >::v_, and Tensor< Cmpt >::ZZ.
Referenced by momentOfInertia::massPropertiesSolid(), Foam::pinv(), and quaternion::quaternion().
xx() [2/2]
template<class Cmpt > Cmpt & xx () inline noexcept
Definition at line 171 of file Tensor.H.
References VectorSpace< Form, Cmpt, Ncmpts >::v_, and Tensor< Cmpt >::XX.
xy() [2/2]
template<class Cmpt > Cmpt & xy () inline noexcept
Definition at line 172 of file Tensor.H.
References VectorSpace< Form, Cmpt, Ncmpts >::v_, and Tensor< Cmpt >::XY.
xz() [2/2]
template<class Cmpt > Cmpt & xz () inline noexcept
Definition at line 173 of file Tensor.H.
References VectorSpace< Form, Cmpt, Ncmpts >::v_, and Tensor< Cmpt >::XZ.
yx() [2/2]
template<class Cmpt > Cmpt & yx () inline noexcept
Definition at line 174 of file Tensor.H.
References VectorSpace< Form, Cmpt, Ncmpts >::v_, and Tensor< Cmpt >::YX.
yy() [2/2]
template<class Cmpt > Cmpt & yy () inline noexcept
Definition at line 175 of file Tensor.H.
References VectorSpace< Form, Cmpt, Ncmpts >::v_, and Tensor< Cmpt >::YY.
yz() [2/2]
template<class Cmpt > Cmpt & yz () inline noexcept
Definition at line 176 of file Tensor.H.
References VectorSpace< Form, Cmpt, Ncmpts >::v_, and Tensor< Cmpt >::YZ.
zx() [2/2]
template<class Cmpt > Cmpt & zx () inline noexcept
Definition at line 177 of file Tensor.H.
References VectorSpace< Form, Cmpt, Ncmpts >::v_, and Tensor< Cmpt >::ZX.
zy() [2/2]
template<class Cmpt > Cmpt & zy () inline noexcept
Definition at line 178 of file Tensor.H.
References VectorSpace< Form, Cmpt, Ncmpts >::v_, and Tensor< Cmpt >::ZY.
zz() [2/2]
template<class Cmpt > Cmpt & zz () inline noexcept
Definition at line 179 of file Tensor.H.
References VectorSpace< Form, Cmpt, Ncmpts >::v_, and Tensor< Cmpt >::ZZ.
cx()
template<class Cmpt > Foam::Vector< Cmpt > cx () const inline
Definition at line 167 of file TensorI.H.
Referenced by coordinateSystem::e1().
cy()
template<class Cmpt > Foam::Vector< Cmpt > cy () const inline
Definition at line 174 of file TensorI.H.
Referenced by coordinateSystem::e2().
cz()
template<class Cmpt > Foam::Vector< Cmpt > cz () const inline
Definition at line 181 of file TensorI.H.
Referenced by coordinateSystem::e3().
col() [1/5]
template<class Cmpt > template<direction Idx> Vector< Cmpt > col () const inline
col() [2/5]
template<class Cmpt > Foam::Vector< Cmpt > col (const direction c) const inline
Definition at line 201 of file TensorI.H.
col() [3/5]
template<class Cmpt > template<Foam::direction Idx> void col (const Vector< Cmpt > & v) inline
Definition at line 249 of file TensorI.H.
col() [4/5]
template<class Cmpt > void col (const direction c, const Vector< Cmpt > & v) inline
Definition at line 324 of file TensorI.H.
cols()
template<class Cmpt > void cols (const Vector< Cmpt > & x, const Vector< Cmpt > & y, const Vector< Cmpt > & z) inline
Definition at line 296 of file TensorI.H.
x()
template<class Cmpt > Foam::Vector< Cmpt > x () const inline
Definition at line 146 of file TensorI.H.
Referenced by triad::operator=(), and triad::triad().
y()
template<class Cmpt > Foam::Vector< Cmpt > y () const inline
Definition at line 153 of file TensorI.H.
Referenced by triad::operator=(), and triad::triad().
z()
template<class Cmpt > Foam::Vector< Cmpt > z () const inline
Definition at line 160 of file TensorI.H.
Referenced by triad::operator=(), and triad::triad().
row() [1/5]
template<class Cmpt > template<direction Idx> Vector< Cmpt > row () const inline
Referenced by Tensor< Cmpt >::vectorComponent().
row() [2/5]
template<class Cmpt > Foam::Vector< Cmpt > row (const direction r) const inline
Definition at line 231 of file TensorI.H.
row() [3/5]
template<class Cmpt > template<Foam::direction Idx> void row (const Vector< Cmpt > & v) inline
Definition at line 276 of file TensorI.H.
row() [4/5]
template<class Cmpt > void row (const direction r, const Vector< Cmpt > & v) inline
Definition at line 343 of file TensorI.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
rows()
template<class Cmpt > void rows (const Vector< Cmpt > & x, const Vector< Cmpt > & y, const Vector< Cmpt > & z) inline
Definition at line 310 of file TensorI.H.
diag() [1/2]
template<class Cmpt > Foam::Vector< Cmpt > diag () const inline
Definition at line 362 of file TensorI.H.
diag() [2/2]
template<class Cmpt > void diag (const Vector< Cmpt > & v) inline
Definition at line 369 of file TensorI.H.
addDiag()
template<class Cmpt > void addDiag (const Vector< Cmpt > & v) inline
Definition at line 376 of file TensorI.H.
subtractDiag()
template<class Cmpt > void subtractDiag (const Vector< Cmpt > & v) inline
Definition at line 383 of file TensorI.H.
diagSqr()
template<class Cmpt > Foam::scalar diagSqr () const inline
Definition at line 390 of file TensorI.H.
References Foam::magSqr().
is_identity()
template<class Cmpt > bool is_identity (const scalar tol = ROOTVSMALL) const inline
Definition at line 402 of file TensorI.H.
References Foam::mag().
T()
template<class Cmpt > Foam::Tensor< Cmpt > T () const inline
Definition at line 419 of file TensorI.H.
Referenced by eddy::eddy(), triangle< Point, PointRef >::inertia(), spatialTransform::inv(), Moment< Type >::Moment(), and triad::triad().
det()
template<class Cmpt > Cmpt det () const inline
Definition at line 431 of file TensorI.H.
Referenced by Foam::pinv().
det2D()
template<class Cmpt > Cmpt det2D (const direction excludeCmpt) const inline
Definition at line 443 of file TensorI.H.
adjunct()
template<class Cmpt > Foam::Tensor< Cmpt > adjunct () const inline
Definition at line 464 of file TensorI.H.
cof()
template<class Cmpt > Foam::Tensor< Cmpt > cof () const inline
Definition at line 476 of file TensorI.H.
adjunct2D()
template<class Cmpt > Foam::Tensor< Cmpt > adjunct2D (const direction excludeCmpt) const inline
Definition at line 483 of file TensorI.H.
References Foam::Zero.
inv()
template<class Cmpt > Foam::Tensor< Cmpt > inv () const inline
Definition at line 573 of file TensorI.H.
References Foam::abort(), Foam::det(), Foam::FatalError, FatalErrorInFunction, Foam::mag(), and Foam::nl.
safeInv()
template<class Cmpt > Foam::Tensor< Cmpt > safeInv () const inline
Definition at line 593 of file TensorI.H.
References Foam::det(), Foam::mag(), Foam::magSqr(), and Foam::Zero.
inv2D()
template<class Cmpt > Foam::Tensor< Cmpt > inv2D (const direction excludeCmpt) const inline
Definition at line 522 of file TensorI.H.
inner()
template<class Cmpt > Foam::Tensor< Cmpt > inner (const Tensor< Cmpt > & t2) const inline
Definition at line 535 of file TensorI.H.
schur()
template<class Cmpt > Foam::Tensor< Cmpt > schur (const Tensor< Cmpt > & t2) const inline
Definition at line 558 of file TensorI.H.
operator&=()
template<class Cmpt > void operator&= (const Tensor< Cmpt > & t) inline
Definition at line 652 of file TensorI.H.
operator=() [2/5]
template<class Cmpt > template<class Cmpt2 > void operator= (const VectorSpace< Tensor< Cmpt2 >, Cmpt2, 9 > & vs) inline
Definition at line 660 of file TensorI.H.
operator=() [3/5]
template<class Cmpt > void operator= (const SphericalTensor< Cmpt > & st) inline
Definition at line 670 of file TensorI.H.
References Foam::Zero.
operator=() [4/5]
template<class Cmpt > void operator= (const SymmTensor< Cmpt > & st) inline
Definition at line 679 of file TensorI.H.
operator=() [5/5]
template<class Cmpt > void operator= (const Vector< Vector< Cmpt > > & tr) inline
Definition at line 688 of file TensorI.H.
References Foam::tr().
vectorComponent()
template<class Cmpt > Vector< Cmpt > vectorComponent (const direction cmpt) const inline
Definition at line 336 of file Tensor.H.
References Tensor< Cmpt >::row().
I() [1/2]
const Foam::Tensor< float > I (1 , 0 , 0 , 0 , 1 , 0 , 0 , 0 , 1)
I() [2/2]
const Foam::Tensor< double > I (1 , 0 , 0 , 0 , 1 , 0 , 0 , 0 , 1)
col() [5/5]
template<class Cmpt > template<Foam::direction Idx> Foam::Vector< Cmpt > col () const inline
Definition at line 189 of file TensorI.H.
row() [5/5]
template<class Cmpt > template<Foam::direction Idx> Foam::Vector< Cmpt > row () const inline
Definition at line 219 of file TensorI.H.
References x.
Member Data Documentation
rank
template<class Cmpt > constexpr direction rank = 2 static constexpr
Definition at line 72 of file Tensor.H.
I
const Foam::labelTensor I static
Definition at line 77 of file Tensor.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/complex/complexI.H
src/OpenFOAM/primitives/Tensor/Tensor.H
src/OpenFOAM/primitives/Tensor/ints/labelTensor.C
src/OpenFOAM/primitives/Tensor/TensorI.H