OpenFOAM: RASModelVariables Class Reference
RASModelVariables Class Reference
Abstract base class for objective functions. No point in making this runTime selectable since its children will have different constructors.
#include <RASModelVariables.H>
Public Member Functions
TypeName ("RASModelVariables")
declareRunTimeSelectionTable (autoPtr, RASModelVariables, dictionary,(const fvMesh &mesh, const solverControl &SolverControl),(mesh, SolverControl))
RASModelVariables (const fvMesh &mesh, const solverControl &SolverControl)
RASModelVariables (const RASModelVariables &rmv)
autoPtr< RASModelVariables > clone () const
virtual ~RASModelVariables ()=default
const word & TMVar1BaseName () const
const word & TMVar2BaseName () const
const word & nutBaseName () const
virtual bool hasTMVar1 () const
virtual bool hasTMVar2 () const
virtual bool hasNut () const
bool hasDist () const
const volScalarField & TMVar1 () const
volScalarField & TMVar1 ()
const volScalarField & TMVar2 () const
volScalarField & TMVar2 ()
const volScalarField & nutRef () const
volScalarField & nutRef ()
const volScalarField & d () const
volScalarField & d ()
const volScalarField & TMVar1Inst () const
volScalarField & TMVar1Inst ()
const volScalarField & TMVar2Inst () const
volScalarField & TMVar2Inst ()
const volScalarField & nutRefInst () const
volScalarField & nutRefInst ()
virtual tmp< volScalarField > nutJacobianVar1 (const singlePhaseTransportModel &laminarTransport) const
virtual tmp< volScalarField > nutJacobianVar2 (const singlePhaseTransportModel &laminarTransport) const
virtual tmp< volScalarField::Internal > G ()
void restoreInitValues ()
void resetMeanFields ()
virtual void computeMeanFields ()
tmp< volSymmTensorField > devReff (const singlePhaseTransportModel &laminarTransport, const volVectorField &U) const
virtual void correctBoundaryConditions (const incompressible::turbulenceModel &turbulence)
virtual void transfer (RASModelVariables &rmv)
Static Public Member Functions
static autoPtr< RASModelVariables > New (const fvMesh &mesh, const solverControl &SolverControl)
Protected Member Functions
virtual void allocateInitValues ()
virtual void allocateMeanFields ()
refPtr< volScalarField > cloneRefPtr (const refPtr< volScalarField > &obj) const
void copyAndRename (volScalarField &f1, volScalarField &f2)
void operator= (const RASModelVariables &)=delete
Protected Attributes
const fvMesh & mesh_
const solverControl & solverControl_
word TMVar1BaseName_
word TMVar2BaseName_
word nutBaseName_
refPtr< volScalarField > TMVar1Ptr_
refPtr< volScalarField > TMVar2Ptr_
refPtr< volScalarField > nutPtr_
refPtr< volScalarField > distPtr_
refPtr< volScalarField > TMVar1InitPtr_
refPtr< volScalarField > TMVar2InitPtr_
refPtr< volScalarField > nutInitPtr_
refPtr< volScalarField > TMVar1MeanPtr_
refPtr< volScalarField > TMVar2MeanPtr_
refPtr< volScalarField > nutMeanPtr_
Detailed Description
Abstract base class for objective functions. No point in making this runTime selectable since its children will have different constructors.
Source files
RASModelVariables.H
RASModelVariables.C
Definition at line 55 of file RASModelVariables.H.
Constructor & Destructor Documentation
RASModelVariables() [1/2]
RASModelVariables (const fvMesh & mesh, const solverControl & SolverControl)
Definition at line 175 of file RASModelVariables.C.
RASModelVariables() [2/2]
RASModelVariables (const RASModelVariables & rmv)
Definition at line 203 of file RASModelVariables.C.
~RASModelVariables()
virtual ~RASModelVariables () virtual default
Member Function Documentation
allocateInitValues()
void allocateInitValues () protected virtual
Definition at line 41 of file RASModelVariables.C.
References Foam::endl(), RASModelVariables::hasNut(), RASModelVariables::hasTMVar1(), RASModelVariables::hasTMVar2(), Foam::Info, Foam::name(), RASModelVariables::nutInitPtr_, RASModelVariables::nutRefInst(), RASModelVariables::solverControl_, RASModelVariables::TMVar1InitPtr_, RASModelVariables::TMVar1Inst(), RASModelVariables::TMVar2InitPtr_, and RASModelVariables::TMVar2Inst().
Referenced by kEpsilon::kEpsilon(), kOmegaSST::kOmegaSST(), laminar::laminar(), LaunderSharmaKE::LaunderSharmaKE(), and SpalartAllmaras::SpalartAllmaras().
allocateMeanFields()
void allocateMeanFields () protected virtual
Reimplemented in kOmegaSST.
Definition at line 74 of file RASModelVariables.C.
References IOobjectOption::AUTO_WRITE, Foam::endl(), RASModelVariables::hasNut(), RASModelVariables::hasTMVar1(), RASModelVariables::hasTMVar2(), Foam::Info, RASModelVariables::mesh_, Foam::name(), RASModelVariables::nutMeanPtr_, RASModelVariables::nutRefInst(), IOobjectOption::READ_IF_PRESENT, RASModelVariables::solverControl_, RASModelVariables::TMVar1Inst(), RASModelVariables::TMVar1MeanPtr_, RASModelVariables::TMVar2Inst(), and RASModelVariables::TMVar2MeanPtr_.
Referenced by kOmegaSST::allocateMeanFields(), kEpsilon::kEpsilon(), LaunderSharmaKE::LaunderSharmaKE(), and SpalartAllmaras::SpalartAllmaras().
cloneRefPtr()
Foam::refPtr< Foam::volScalarField > cloneRefPtr (const refPtr< volScalarField > & obj) const protected
Definition at line 141 of file RASModelVariables.C.
References RASModelVariables::mesh_, refPtr< T >::New(), and timeName.
copyAndRename()
void copyAndRename (volScalarField & f1, volScalarField & f2) protected
Definition at line 156 of file RASModelVariables.C.
References IOobject::name(), and regIOobject::rename().
Referenced by RASModelVariables::transfer().
operator=()
void operator= (const RASModelVariables &) protected delete
TypeName()
TypeName ("RASModelVariables")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , RASModelVariables , dictionary , (const fvMesh &mesh, const solverControl &SolverControl) , (mesh, SolverControl))
clone()
autoPtr< RASModelVariables > clone () const
Definition at line 230 of file RASModelVariables.C.
References autoPtr< T >::New().
New()
autoPtr< RASModelVariables > New (const fvMesh & mesh, const solverControl & SolverControl) static
Definition at line 238 of file RASModelVariables.C.
References Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::findDict(), Foam::Info, mesh, IOobjectOption::MUST_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, dictionary::null, and turbulenceModel::propertiesName.
Referenced by incompressibleVars::setFields().
TMVar1BaseName()
const word & TMVar1BaseName () const inline
Definition at line 31 of file RASModelVariablesI.H.
References RASModelVariables::TMVar1BaseName_.
TMVar2BaseName()
const word & TMVar2BaseName () const inline
Definition at line 37 of file RASModelVariablesI.H.
References RASModelVariables::TMVar2BaseName_.
nutBaseName()
const word & nutBaseName () const inline
Definition at line 43 of file RASModelVariablesI.H.
References RASModelVariables::nutBaseName_.
hasTMVar1()
bool hasTMVar1 () const inline virtual
Reimplemented in kEpsilon, kOmegaSST, laminar, LaunderSharmaKE, and SpalartAllmaras.
Definition at line 49 of file RASModelVariablesI.H.
References RASModelVariables::TMVar1Ptr_.
Referenced by RASModelVariables::allocateInitValues(), RASModelVariables::allocateMeanFields(), RASModelVariables::computeMeanFields(), RASModelVariables::correctBoundaryConditions(), RASModelVariables::resetMeanFields(), RASModelVariables::restoreInitValues(), and RASModelVariables::transfer().
hasTMVar2()
bool hasTMVar2 () const inline virtual
Reimplemented in kEpsilon, kOmegaSST, laminar, LaunderSharmaKE, and SpalartAllmaras.
Definition at line 55 of file RASModelVariablesI.H.
References RASModelVariables::TMVar2Ptr_.
Referenced by RASModelVariables::allocateInitValues(), RASModelVariables::allocateMeanFields(), RASModelVariables::computeMeanFields(), RASModelVariables::correctBoundaryConditions(), RASModelVariables::resetMeanFields(), RASModelVariables::restoreInitValues(), and RASModelVariables::transfer().
hasNut()
bool hasNut () const inline virtual
Reimplemented in kEpsilon, kOmegaSST, laminar, LaunderSharmaKE, and SpalartAllmaras.
Definition at line 61 of file RASModelVariablesI.H.
References RASModelVariables::nutPtr_.
Referenced by RASModelVariables::allocateInitValues(), RASModelVariables::allocateMeanFields(), RASModelVariables::computeMeanFields(), RASModelVariables::correctBoundaryConditions(), RASModelVariables::resetMeanFields(), RASModelVariables::restoreInitValues(), and RASModelVariables::transfer().
hasDist()
bool hasDist () const inline
Definition at line 67 of file RASModelVariablesI.H.
References RASModelVariables::distPtr_.
Referenced by RASModelVariables::transfer().
TMVar1() [1/2]
const volScalarField & TMVar1 () const inline
Definition at line 73 of file RASModelVariablesI.H.
References RASModelVariables::solverControl_, RASModelVariables::TMVar1MeanPtr_, and RASModelVariables::TMVar1Ptr_.
Referenced by SpalartAllmaras::nutJacobianVar1().
TMVar1() [2/2]
volScalarField & TMVar1 () inline
Definition at line 84 of file RASModelVariablesI.H.
References RASModelVariables::solverControl_, RASModelVariables::TMVar1MeanPtr_, and RASModelVariables::TMVar1Ptr_.
TMVar2() [1/2]
const volScalarField & TMVar2 () const inline
Definition at line 95 of file RASModelVariablesI.H.
References RASModelVariables::solverControl_, RASModelVariables::TMVar2MeanPtr_, and RASModelVariables::TMVar2Ptr_.
Referenced by kOmegaSST::computeG().
TMVar2() [2/2]
volScalarField & TMVar2 () inline
Definition at line 105 of file RASModelVariablesI.H.
References RASModelVariables::solverControl_, RASModelVariables::TMVar2MeanPtr_, and RASModelVariables::TMVar2Ptr_.
nutRef() [1/2]
const volScalarField & nutRef () const inline
Definition at line 115 of file RASModelVariablesI.H.
References RASModelVariables::nutMeanPtr_, RASModelVariables::nutPtr_, and RASModelVariables::solverControl_.
Referenced by kOmegaSST::correctBoundaryConditions(), and RASModelVariables::devReff().
nutRef() [2/2]
volScalarField & nutRef () inline
Definition at line 126 of file RASModelVariablesI.H.
References RASModelVariables::nutMeanPtr_, RASModelVariables::nutPtr_, and RASModelVariables::solverControl_.
d() [1/2]
const volScalarField & d () const inline
Definition at line 137 of file RASModelVariablesI.H.
References RASModelVariables::distPtr_.
Referenced by RASModelVariables::transfer().
d() [2/2]
volScalarField & d () inline
Definition at line 143 of file RASModelVariablesI.H.
References RASModelVariables::distPtr_.
TMVar1Inst() [1/2]
const volScalarField & TMVar1Inst () const inline
Definition at line 149 of file RASModelVariablesI.H.
References RASModelVariables::TMVar1Ptr_.
Referenced by RASModelVariables::allocateInitValues(), RASModelVariables::allocateMeanFields(), RASModelVariables::computeMeanFields(), RASModelVariables::correctBoundaryConditions(), RASModelVariables::resetMeanFields(), RASModelVariables::restoreInitValues(), and RASModelVariables::transfer().
TMVar1Inst() [2/2]
volScalarField & TMVar1Inst () inline
Definition at line 155 of file RASModelVariablesI.H.
References RASModelVariables::TMVar1Ptr_.
TMVar2Inst() [1/2]
const volScalarField & TMVar2Inst () const inline
Definition at line 161 of file RASModelVariablesI.H.
References RASModelVariables::TMVar2Ptr_.
Referenced by RASModelVariables::allocateInitValues(), RASModelVariables::allocateMeanFields(), kOmegaSST::computeG(), RASModelVariables::computeMeanFields(), RASModelVariables::correctBoundaryConditions(), RASModelVariables::resetMeanFields(), RASModelVariables::restoreInitValues(), and RASModelVariables::transfer().
TMVar2Inst() [2/2]
volScalarField & TMVar2Inst () inline
Definition at line 167 of file RASModelVariablesI.H.
References RASModelVariables::TMVar2Ptr_.
nutRefInst() [1/2]
const volScalarField & nutRefInst () const inline
Definition at line 173 of file RASModelVariablesI.H.
References RASModelVariables::nutPtr_.
Referenced by RASModelVariables::allocateInitValues(), RASModelVariables::allocateMeanFields(), kOmegaSST::computeG(), RASModelVariables::computeMeanFields(), RASModelVariables::correctBoundaryConditions(), RASModelVariables::resetMeanFields(), RASModelVariables::restoreInitValues(), and RASModelVariables::transfer().
nutRefInst() [2/2]
volScalarField & nutRefInst () inline
Definition at line 179 of file RASModelVariablesI.H.
References RASModelVariables::nutPtr_.
nutJacobianVar1()
tmp< volScalarField > nutJacobianVar1 (const singlePhaseTransportModel & laminarTransport) const virtual
Reimplemented in SpalartAllmaras.
Definition at line 292 of file RASModelVariables.C.
References Foam::dimless, Foam::endl(), RASModelVariables::mesh_, tmp< T >::New(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, WarningInFunction, and Foam::Zero.
nutJacobianVar2()
tmp< volScalarField > nutJacobianVar2 (const singlePhaseTransportModel & laminarTransport) const virtual
Definition at line 317 of file RASModelVariables.C.
References Foam::dimless, Foam::endl(), RASModelVariables::mesh_, tmp< T >::New(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, WarningInFunction, and Foam::Zero.
G()
virtual tmp< volScalarField::Internal > G () inline virtual
Reimplemented in kOmegaSST.
Definition at line 216 of file RASModelVariables.H.
References NotImplemented.
restoreInitValues()
void restoreInitValues ()
Definition at line 342 of file RASModelVariables.C.
References RASModelVariables::hasNut(), RASModelVariables::hasTMVar1(), RASModelVariables::hasTMVar2(), RASModelVariables::nutInitPtr_, RASModelVariables::nutRefInst(), RASModelVariables::solverControl_, RASModelVariables::TMVar1InitPtr_, RASModelVariables::TMVar1Inst(), RASModelVariables::TMVar2InitPtr_, and RASModelVariables::TMVar2Inst().
resetMeanFields()
void resetMeanFields ()
Definition at line 362 of file RASModelVariables.C.
References Foam::endl(), RASModelVariables::hasNut(), RASModelVariables::hasTMVar1(), RASModelVariables::hasTMVar2(), Foam::Info, RASModelVariables::nutMeanPtr_, RASModelVariables::nutRefInst(), RASModelVariables::solverControl_, RASModelVariables::TMVar1Inst(), RASModelVariables::TMVar1MeanPtr_, RASModelVariables::TMVar2Inst(), RASModelVariables::TMVar2MeanPtr_, and Foam::Zero.
computeMeanFields()
void computeMeanFields () virtual
Reimplemented in kOmegaSST.
Definition at line 388 of file RASModelVariables.C.
References RASModelVariables::hasNut(), RASModelVariables::hasTMVar1(), RASModelVariables::hasTMVar2(), RASModelVariables::nutMeanPtr_, RASModelVariables::nutRefInst(), RASModelVariables::solverControl_, RASModelVariables::TMVar1Inst(), RASModelVariables::TMVar1MeanPtr_, RASModelVariables::TMVar2Inst(), and RASModelVariables::TMVar2MeanPtr_.
Referenced by kOmegaSST::computeMeanFields().
devReff()
tmp< volSymmTensorField > devReff (const singlePhaseTransportModel & laminarTransport, const volVectorField & U) const
Definition at line 416 of file RASModelVariables.C.
References Foam::devTwoSymm(), Foam::fvc::grad(), laminarTransport(), RASModelVariables::mesh_, tmp< T >::New(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, RASModelVariables::nutRef(), and U.
correctBoundaryConditions()
void correctBoundaryConditions (const incompressible::turbulenceModel & turbulence) virtual
Reimplemented in kOmegaSST.
Definition at line 437 of file RASModelVariables.C.
References RASModelVariables::hasNut(), RASModelVariables::hasTMVar1(), RASModelVariables::hasTMVar2(), RASModelVariables::nutMeanPtr_, RASModelVariables::nutRefInst(), RASModelVariables::solverControl_, RASModelVariables::TMVar1Inst(), RASModelVariables::TMVar1MeanPtr_, RASModelVariables::TMVar2Inst(), and RASModelVariables::TMVar2MeanPtr_.
Referenced by kOmegaSST::correctBoundaryConditions().
transfer()
void transfer (RASModelVariables & rmv) virtual
Definition at line 471 of file RASModelVariables.C.
References RASModelVariables::copyAndRename(), RASModelVariables::d(), RASModelVariables::hasDist(), RASModelVariables::hasNut(), RASModelVariables::hasTMVar1(), RASModelVariables::hasTMVar2(), RASModelVariables::nutRefInst(), RASModelVariables::TMVar1Inst(), and RASModelVariables::TMVar2Inst().
Member Data Documentation
mesh_
const fvMesh& mesh_ protected
Definition at line 61 of file RASModelVariables.H.
Referenced by kOmegaSST::allocateMeanFields(), RASModelVariables::allocateMeanFields(), RASModelVariables::cloneRefPtr(), kOmegaSST::computeG(), RASModelVariables::devReff(), kEpsilon::kEpsilon(), kOmegaSST::kOmegaSST(), LaunderSharmaKE::LaunderSharmaKE(), RASModelVariables::nutJacobianVar1(), SpalartAllmaras::nutJacobianVar1(), RASModelVariables::nutJacobianVar2(), and SpalartAllmaras::SpalartAllmaras().
solverControl_
const solverControl& solverControl_ protected
Definition at line 62 of file RASModelVariables.H.
Referenced by RASModelVariables::allocateInitValues(), kOmegaSST::allocateMeanFields(), RASModelVariables::allocateMeanFields(), kOmegaSST::computeMeanFields(), RASModelVariables::computeMeanFields(), RASModelVariables::correctBoundaryConditions(), kOmegaSST::G(), RASModelVariables::nutRef(), RASModelVariables::nutRef(), RASModelVariables::resetMeanFields(), RASModelVariables::restoreInitValues(), RASModelVariables::TMVar1(), RASModelVariables::TMVar1(), RASModelVariables::TMVar2(), and RASModelVariables::TMVar2().
TMVar1BaseName_
word TMVar1BaseName_ protected
Definition at line 65 of file RASModelVariables.H.
Referenced by kEpsilon::kEpsilon(), kOmegaSST::kOmegaSST(), LaunderSharmaKE::LaunderSharmaKE(), SpalartAllmaras::SpalartAllmaras(), and RASModelVariables::TMVar1BaseName().
TMVar2BaseName_
word TMVar2BaseName_ protected
Definition at line 66 of file RASModelVariables.H.
Referenced by kEpsilon::kEpsilon(), kOmegaSST::kOmegaSST(), LaunderSharmaKE::LaunderSharmaKE(), and RASModelVariables::TMVar2BaseName().
nutBaseName_
word nutBaseName_ protected
Definition at line 67 of file RASModelVariables.H.
Referenced by kEpsilon::kEpsilon(), kOmegaSST::kOmegaSST(), LaunderSharmaKE::LaunderSharmaKE(), RASModelVariables::nutBaseName(), and SpalartAllmaras::SpalartAllmaras().
TMVar1Ptr_
refPtr<volScalarField> TMVar1Ptr_ protected
Definition at line 69 of file RASModelVariables.H.
Referenced by RASModelVariables::hasTMVar1(), kEpsilon::kEpsilon(), kOmegaSST::kOmegaSST(), laminar::laminar(), LaunderSharmaKE::LaunderSharmaKE(), SpalartAllmaras::SpalartAllmaras(), RASModelVariables::TMVar1(), RASModelVariables::TMVar1(), RASModelVariables::TMVar1Inst(), and RASModelVariables::TMVar1Inst().
TMVar2Ptr_
refPtr<volScalarField> TMVar2Ptr_ protected
Definition at line 70 of file RASModelVariables.H.
Referenced by RASModelVariables::hasTMVar2(), kEpsilon::kEpsilon(), kOmegaSST::kOmegaSST(), laminar::laminar(), LaunderSharmaKE::LaunderSharmaKE(), SpalartAllmaras::SpalartAllmaras(), RASModelVariables::TMVar2(), RASModelVariables::TMVar2(), RASModelVariables::TMVar2Inst(), and RASModelVariables::TMVar2Inst().
nutPtr_
refPtr<volScalarField> nutPtr_ protected
Definition at line 71 of file RASModelVariables.H.
Referenced by RASModelVariables::hasNut(), kEpsilon::kEpsilon(), kOmegaSST::kOmegaSST(), laminar::laminar(), LaunderSharmaKE::LaunderSharmaKE(), RASModelVariables::nutRef(), RASModelVariables::nutRef(), RASModelVariables::nutRefInst(), RASModelVariables::nutRefInst(), and SpalartAllmaras::SpalartAllmaras().
distPtr_
refPtr<volScalarField> distPtr_ protected
Definition at line 72 of file RASModelVariables.H.
Referenced by RASModelVariables::d(), RASModelVariables::d(), RASModelVariables::hasDist(), kOmegaSST::kOmegaSST(), and SpalartAllmaras::SpalartAllmaras().
TMVar1InitPtr_
refPtr<volScalarField> TMVar1InitPtr_ protected
Definition at line 76 of file RASModelVariables.H.
Referenced by RASModelVariables::allocateInitValues(), and RASModelVariables::restoreInitValues().
TMVar2InitPtr_
refPtr<volScalarField> TMVar2InitPtr_ protected
Definition at line 77 of file RASModelVariables.H.
Referenced by RASModelVariables::allocateInitValues(), and RASModelVariables::restoreInitValues().
nutInitPtr_
refPtr<volScalarField> nutInitPtr_ protected
Definition at line 78 of file RASModelVariables.H.
Referenced by RASModelVariables::allocateInitValues(), and RASModelVariables::restoreInitValues().
TMVar1MeanPtr_
refPtr<volScalarField> TMVar1MeanPtr_ protected
Definition at line 81 of file RASModelVariables.H.
Referenced by RASModelVariables::allocateMeanFields(), RASModelVariables::computeMeanFields(), RASModelVariables::correctBoundaryConditions(), RASModelVariables::resetMeanFields(), RASModelVariables::TMVar1(), and RASModelVariables::TMVar1().
TMVar2MeanPtr_
refPtr<volScalarField> TMVar2MeanPtr_ protected
Definition at line 82 of file RASModelVariables.H.
Referenced by RASModelVariables::allocateMeanFields(), RASModelVariables::computeMeanFields(), RASModelVariables::correctBoundaryConditions(), RASModelVariables::resetMeanFields(), RASModelVariables::TMVar2(), and RASModelVariables::TMVar2().
nutMeanPtr_
refPtr<volScalarField> nutMeanPtr_ protected
Definition at line 83 of file RASModelVariables.H.
Referenced by RASModelVariables::allocateMeanFields(), RASModelVariables::computeMeanFields(), RASModelVariables::correctBoundaryConditions(), RASModelVariables::nutRef(), RASModelVariables::nutRef(), and RASModelVariables::resetMeanFields().
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/turbulenceModels/turbulenceModelVariables/RAS/RASModelVariables/RASModelVariables.H
src/optimisation/adjointOptimisation/adjoint/turbulenceModels/turbulenceModelVariables/RAS/RASModelVariables/RASModelVariables.C
src/optimisation/adjointOptimisation/adjoint/turbulenceModels/turbulenceModelVariables/RAS/RASModelVariables/RASModelVariablesI.H