OpenFOAM: primitiveMesh Class Reference
primitiveMesh Class Reference abstract
Cell-face mesh analysis engine.
#include <primitiveMesh.H>
Public Member Functions
ClassName ("primitiveMesh")
primitiveMesh (const label nPoints, const label nInternalFaces, const label nFaces, const label nCells)
virtual ~primitiveMesh ()
void reset (const label nPoints, const label nInternalFaces, const label nFaces, const label nCells)
void reset (const label nPoints, const label nInternalFaces, const label nFaces, const label nCells, cellList &cells)
void resetGeometry (pointField &&faceCentres, pointField &&faceAreas, pointField &&cellCentres, scalarField &&cellVolumes)
virtual bool init (const bool doInit)
label nPoints () const noexcept
label nEdges () const
label nFaces () const noexcept
label nCells () const noexcept
label nInternalFaces () const noexcept
label nBoundaryFaces () const noexcept
label nInternalPoints () const noexcept
label nInternal0Edges () const
label nInternal1Edges () const
label nInternalEdges () const
virtual const pointField & points () const =0
virtual const faceList & faces () const =0
virtual const labelList & faceOwner () const =0
virtual const labelList & faceNeighbour () const =0
virtual const pointField & oldPoints () const =0
const cellShapeList & cellShapes () const
const edgeList & edges () const
const labelListList & cellCells () const
const labelListList & edgeCells () const
const labelListList & pointCells () const
const cellList & cells () const
const labelListList & edgeFaces () const
const labelListList & pointFaces () const
const labelListList & cellEdges () const
const labelListList & faceEdges () const
const labelListList & pointEdges () const
const labelListList & pointPoints () const
const labelListList & cellPoints () const
const vectorField & cellCentres () const
const vectorField & faceCentres () const
const scalarField & cellVolumes () const
const vectorField & faceAreas () const
void movePoints (const pointField &p, const pointField &oldP)
bool isInternalFace (const label faceIndex) const noexcept
virtual bool checkUpperTriangular (const bool report=false, labelHashSet *setPtr=nullptr) const
virtual bool checkCellsZipUp (const bool report=false, labelHashSet *setPtr=nullptr) const
virtual bool checkFaceVertices (const bool report=false, labelHashSet *setPtr=nullptr) const
virtual bool checkPoints (const bool report=false, labelHashSet *setPtr=nullptr) const
virtual bool checkFaceFaces (const bool report=false, labelHashSet *setPtr=nullptr) const
virtual bool checkClosedBoundary (const bool report=false) const
virtual bool checkClosedCells (const bool report=false, labelHashSet *setPtr=nullptr, labelHashSet *highAspectSetPtr=nullptr, const Vector< label > &solutionD=Vector< label >::one) const
virtual bool checkFaceAreas (const bool report=false, labelHashSet *setPtr=nullptr) const
virtual bool checkCellVolumes (const bool report=false, labelHashSet *setPtr=nullptr) const
virtual bool checkFaceOrthogonality (const bool report=false, labelHashSet *setPtr=nullptr) const
virtual bool checkFacePyramids (const bool report=false, const scalar minPyrVol=-SMALL, labelHashSet *setPtr=nullptr) const
virtual bool checkFaceSkewness (const bool report=false, labelHashSet *setPtr=nullptr) const
virtual bool checkFaceAngles (const bool report=false, const scalar maxSin=10, labelHashSet *setPtr=nullptr) const
virtual bool checkFaceFlatness (const bool report, const scalar warnFlatness, labelHashSet *setPtr) const
virtual bool checkPointNearness (const bool report, const scalar reportDistSqr, labelHashSet *setPtr=nullptr) const
virtual bool checkEdgeLength (const bool report, const scalar minLenSqr, labelHashSet *setPtr=nullptr) const
virtual bool checkConcaveCells (const bool report=false, labelHashSet *setPtr=nullptr) const
virtual bool checkTopology (const bool report=false) const
virtual bool checkGeometry (const bool report=false) const
virtual bool checkMesh (const bool report=false) const
boundBox cellBb (const label celli) const
bool pointInCellBB (const point &p, label celli, scalar inflationFraction=0) const
bool pointInCell (const point &p, label celli) const
label findNearestCell (const point &location) const
label findCell (const point &location) const
void printAllocated () const
bool hasCellShapes () const noexcept
bool hasEdges () const noexcept
bool hasCellCells () const noexcept
bool hasEdgeCells () const noexcept
bool hasPointCells () const noexcept
bool hasCells () const noexcept
bool hasEdgeFaces () const noexcept
bool hasPointFaces () const noexcept
bool hasCellEdges () const noexcept
bool hasFaceEdges () const noexcept
bool hasPointEdges () const noexcept
bool hasPointPoints () const noexcept
bool hasCellPoints () const noexcept
bool hasCellCentres () const noexcept
bool hasCellVolumes () const noexcept
bool hasFaceCentres () const noexcept
bool hasFaceAreas () const noexcept
const labelList & cellCells (const label celli, DynamicList< label > &) const
const labelList & cellCells (const label celli) const
const labelList & cellPoints (const label celli, labelHashSet &, DynamicList< label > &) const
const labelList & cellPoints (const label celli) const
const labelList & pointCells (const label pointi, DynamicList< label > &) const
const labelList & pointCells (const label pointi) const
const labelList & pointPoints (const label pointi, DynamicList< label > &) const
const labelList & pointPoints (const label pointi) const
const labelList & faceEdges (const label facei, DynamicList< label > &) const
const labelList & faceEdges (const label facei) const
const labelList & edgeFaces (const label edgeI, DynamicList< label > &) const
const labelList & edgeFaces (const label edgeI) const
const labelList & edgeCells (const label edgeI, DynamicList< label > &) const
const labelList & edgeCells (const label edgeI) const
const labelList & cellEdges (const label celli, labelHashSet &, DynamicList< label > &) const
const labelList & cellEdges (const label celli) const
virtual void updateGeom ()
void clearGeom ()
void clearCellGeom ()
void clearAddressing ()
void clearOut ()
Static Public Member Functions
static void calcCells (cellList &, const labelUList &own, const labelUList &nei, const label nCells=-1)
static bool calcPointOrder (label &nInternalPoints, labelList &pointMap, const faceList &, const label nInternalFaces, const label nPoints)
static scalar setClosedThreshold (const scalar)
static scalar setAspectThreshold (const scalar)
static scalar setNonOrthThreshold (const scalar)
static scalar setSkewThreshold (const scalar)
Static Public Attributes
static const unsigned cellsPerEdge_ = 4
static const unsigned cellsPerPoint_ = 8
static const unsigned facesPerCell_ = 6
static const unsigned facesPerEdge_ = 4
static const unsigned facesPerPoint_ = 12
static const unsigned edgesPerCell_ = 12
static const unsigned edgesPerFace_ = 4
static const unsigned edgesPerPoint_ = 6
static const unsigned pointsPerCell_ = 8
static const unsigned pointsPerFace_ = 4
Protected Member Functions
void calcFaceCentresAndAreas () const
void calcCellCentresAndVols () const
void calcEdgeVectors () const
bool checkDuplicateFaces (const label, const Map< label > &, label &nBaffleFaces, labelHashSet *) const
bool checkCommonOrder (const label, const Map< label > &, labelHashSet *) const
bool checkClosedBoundary (const vectorField &areas, const bool report, const bitSet &internalOrCoupledFaces) const
bool checkClosedCells (const vectorField &faceAreas, const scalarField &cellVolumes, const bool report, labelHashSet *setPtr, labelHashSet *aspectSetPtr, const Vector< label > &meshD) const
bool checkFaceAreas (const vectorField &faceAreas, const bool report, const bool detailedReport, labelHashSet *setPtr) const
bool checkCellVolumes (const scalarField &vols, const bool report, const bool detailedReport, labelHashSet *setPtr) const
bool checkFaceOrthogonality (const vectorField &fAreas, const vectorField &cellCtrs, const bool report, labelHashSet *setPtr) const
bool checkFacePyramids (const pointField &points, const vectorField &ctrs, const bool report, const bool detailedReport, const scalar minPyrVol, labelHashSet *setPtr) const
bool checkFaceSkewness (const pointField &points, const vectorField &fCtrs, const vectorField &fAreas, const vectorField &cellCtrs, const bool report, labelHashSet *setPtr) const
bool checkFaceAngles (const pointField &points, const vectorField &faceAreas, const bool report, const scalar maxDeg, labelHashSet *setPtr) const
bool checkFaceFlatness (const pointField &points, const vectorField &faceCentres, const vectorField &faceAreas, const bool report, const scalar warnFlatness, labelHashSet *setPtr) const
bool checkConcaveCells (const vectorField &fAreas, const pointField &fCentres, const bool report, labelHashSet *setPtr) const
primitiveMesh ()
Static Protected Attributes
static scalar closedThreshold_ = 1.0e-6
static scalar aspectThreshold_ = 1000
static scalar nonOrthThreshold_ = 70
static scalar skewThreshold_ = 4
static scalar planarCosAngle_ = 1.0e-6
Detailed Description
Cell-face mesh analysis engine.
Source files
primitiveMesh.H
primitiveMeshI.H
primitiveMesh.C
primitiveMeshClear.C
primitiveMeshCellCells.C
primitiveMeshEdgeCells.C
primitiveMeshPointCells.C
primitiveMeshCells.C
primitiveMeshEdgeFaces.C
primitiveMeshPointFaces.C
primitiveMeshCellEdges.C
primitiveMeshPointEdges.C
primitiveMeshPointPoints.C
primitiveMeshEdges.C
primitiveMeshCellCentresAndVols.C
primitiveMeshFaceCentresAndAreas.C
primitiveMeshFindCell.C
Definition at line 75 of file primitiveMesh.H.
Constructor & Destructor Documentation
primitiveMesh() [1/2]
primitiveMesh () protected
Definition at line 34 of file primitiveMesh.C.
primitiveMesh() [2/2]
primitiveMesh (const label nPoints, const label nInternalFaces, const label nFaces, const label nCells)
Definition at line 71 of file primitiveMesh.C.
~primitiveMesh()
~primitiveMesh () virtual
Definition at line 113 of file primitiveMesh.C.
Member Function Documentation
calcFaceCentresAndAreas()
void calcFaceCentresAndAreas () const protected
Definition at line 35 of file primitiveMeshFaceCentresAndAreas.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, primitiveMeshTools::makeFaceCentresAndAreas(), primitiveMesh::nFaces(), primitiveMesh::points(), and Foam::Pout.
calcCellCentresAndVols()
void calcCellCentresAndVols () const protected
Definition at line 32 of file primitiveMeshCellCentresAndVols.C.
References Foam::abort(), cellVols, Foam::endl(), primitiveMesh::faceAreas(), primitiveMesh::faceCentres(), Foam::FatalError, FatalErrorInFunction, primitiveMeshTools::makeCellCentresAndVols(), primitiveMesh::nCells(), Foam::Pout, and Foam::Zero.
calcEdgeVectors()
void calcEdgeVectors () const protected
checkDuplicateFaces()
bool checkDuplicateFaces (const label facei, const Map< label > & nCommonPoints, label & nBaffleFaces, labelHashSet * setPtr) const protected
Definition at line 1293 of file primitiveMeshCheck.C.
References forAllConstIters, and UPtrList< T >::size().
checkCommonOrder()
bool checkCommonOrder (const label facei, const Map< label > & nCommonPoints, labelHashSet * setPtr) const protected
Definition at line 1334 of file primitiveMeshCheck.C.
References forAll, forAllConstIters, Foam::labelMax, and UPtrList< T >::size().
checkClosedBoundary() [1/2]
bool checkClosedBoundary (const vectorField & areas, const bool report, const bitSet & internalOrCoupledFaces) const protected
Definition at line 41 of file primitiveMeshCheck.C.
References primitiveMesh::closedThreshold_, Foam::cmptMag(), Foam::cmptMax(), DebugInFunction, Foam::endl(), Foam::Info, Foam::mag(), primitiveMesh::nInternalFaces(), Foam::reduce(), UPtrList< T >::size(), UList< T >::size(), and Foam::Zero.
checkClosedCells() [1/2]
bool checkClosedCells (const vectorField & faceAreas, const scalarField & cellVolumes, const bool report, labelHashSet * setPtr, labelHashSet * aspectSetPtr, const Vector< label > & meshD) const protected
Definition at line 92 of file primitiveMeshCheck.C.
References primitiveMeshTools::cellClosedness(), cells, DebugInFunction, Foam::endl(), forAll, Foam::Info, Foam::max(), Foam::min(), Foam::nl, and Foam::reduce().
checkFaceAreas() [1/2]
bool checkFaceAreas (const vectorField & faceAreas, const bool report, const bool detailedReport, labelHashSet * setPtr) const protected
Definition at line 220 of file primitiveMeshCheck.C.
References DebugInFunction, Foam::endl(), forAll, Foam::Info, Foam::mag(), Foam::max(), Foam::min(), Foam::Pout, and Foam::reduce().
checkCellVolumes() [1/2]
bool checkCellVolumes (const scalarField & vols, const bool report, const bool detailedReport, labelHashSet * setPtr) const protected
Definition at line 293 of file primitiveMeshCheck.C.
References DebugInFunction, Foam::endl(), forAll, Foam::gSum(), Foam::Info, Foam::max(), Foam::min(), Foam::Pout, and Foam::reduce().
checkFaceOrthogonality() [1/2]
bool checkFaceOrthogonality (const vectorField & fAreas, const vectorField & cellCtrs, const bool report, labelHashSet * setPtr) const protected
Definition at line 358 of file primitiveMeshCheck.C.
References Foam::acos(), Foam::cos(), DebugInFunction, Foam::degToRad(), Foam::endl(), primitiveMeshTools::faceOrthogonality(), forAll, Foam::Info, Foam::min(), Foam::radToDeg(), Foam::reduce(), Foam::returnReduce(), UPtrList< T >::size(), and Foam::sum().
checkFacePyramids() [1/2]
bool checkFacePyramids (const pointField & points, const vectorField & ctrs, const bool report, const bool detailedReport, const scalar minPyrVol, labelHashSet * setPtr) const protected
Definition at line 461 of file primitiveMeshCheck.C.
References cells, DebugInFunction, Foam::endl(), f(), primitiveMeshTools::facePyramidVolume(), forAll, Foam::Info, Foam::nl, points, Foam::Pout, and Foam::reduce().
checkFaceSkewness() [1/2]
bool checkFaceSkewness (const pointField & points, const vectorField & fCtrs, const vectorField & fAreas, const vectorField & cellCtrs, const bool report, labelHashSet * setPtr) const protected
Definition at line 558 of file primitiveMeshCheck.C.
References DebugInFunction, Foam::endl(), primitiveMeshTools::faceSkewness(), forAll, Foam::Info, Foam::max(), points, and Foam::reduce().
checkFaceAngles() [1/2]
bool checkFaceAngles (const pointField & points, const vectorField & faceAreas, const bool report, const scalar maxDeg, labelHashSet * setPtr) const protected
Definition at line 626 of file primitiveMeshCheck.C.
References Foam::asin(), DebugInFunction, Foam::degToRad(), Foam::endl(), Foam::exit(), primitiveMeshTools::faceConcavity(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::Info, Foam::max(), Foam::min(), points, Foam::radToDeg(), Foam::reduce(), and Foam::sin().
checkFaceFlatness() [1/2]
bool checkFaceFlatness (const pointField & points, const vectorField & faceCentres, const vectorField & faceAreas, const bool report, const scalar warnFlatness, labelHashSet * setPtr) const protected
Definition at line 701 of file primitiveMeshCheck.C.
References DebugInFunction, Foam::endl(), Foam::exit(), primitiveMeshTools::faceFlatness(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::Info, Foam::mag(), Foam::min(), points, and Foam::reduce().
checkConcaveCells() [1/2]
bool checkConcaveCells (const vectorField & fAreas, const pointField & fCentres, const bool report, labelHashSet * setPtr) const protected
Definition at line 801 of file primitiveMeshCheck.C.
References cells, DebugInFunction, Foam::endl(), forAll, Foam::Info, Foam::mag(), Foam::max(), and Foam::reduce().
ClassName()
ClassName ("primitiveMesh")
reset() [1/2]
void reset (const label nPoints, const label nInternalFaces, const label nFaces, const label nCells)
Definition at line 196 of file primitiveMesh.C.
References Foam::endl(), nPoints, and Foam::Pout.
Referenced by distanceSurface::createGeometry(), LocalInteraction< CloudType >::massEscape(), LocalInteraction< CloudType >::massStick(), VoidFraction< CloudType >::preEvolve(), and ParticleErosion< CloudType >::resetQ().
reset() [2/2]
void reset (const label nPoints, const label nInternalFaces, const label nFaces, const label nCells, cellList & cells)
Definition at line 252 of file primitiveMesh.C.
References nPoints.
resetGeometry()
void resetGeometry (pointField && faceCentres, pointField && faceAreas, pointField && cellCentres, scalarField && cellVolumes)
Definition at line 273 of file primitiveMesh.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, and Foam::Pout.
Referenced by averageNeighbourFvGeometryScheme::movePoints(), highAspectRatioFvGeometryScheme::movePoints(), solidBodyFvGeometryScheme::movePoints(), and stabilisedFvGeometryScheme::movePoints().
init()
virtual bool init (const bool doInit) inline virtual
Reimplemented in interfaceTrackingFvMesh, dynamicFvMesh, dynamicMotionSolverFvMesh, dynamicMotionSolverFvMeshAMI, dynamicMotionSolverListFvMesh, dynamicMultiMotionSolverFvMesh, dynamicRefineFvMesh, fvMesh, polyMesh, dynamicMotionSolverTopoFvMesh, and movingConeTopoFvMesh.
Definition at line 462 of file primitiveMesh.H.
Referenced by polyMesh::init().
nPoints()
Foam::label nPoints () const inline noexcept
Definition at line 30 of file primitiveMeshI.H.
Referenced by fvMeshAdder::add(), polyMeshAdder::add(), polyTopoChange::addMesh(), motionSmootherAlgo::avg(), polyTopoChange::changeMesh(), primitiveMesh::checkEdgeLength(), motionSmootherAlgo::checkMesh(), pointZone::checkParallelSync(), Foam::createReconstructMap(), Foam::createReconstructMap(), displacementInterpolationMotionSolver::curPoints(), polyMeshFilter::filterEdges(), surfaceSets::getHangingCells(), syncTools::getMasterPoints(), Foam::getMeshPointRef(), hexRef8Data::hexRef8Data(), polyTopoChange::makeMesh(), pointBitSet::maxSize(), pointSet::maxSize(), pointZoneSet::maxSize(), sampledSurface::pointAverage(), primitiveMesh::pointFaces(), polyMesh::polyMesh(), fvMeshDistribute::printMeshInfo(), processorMeshes::reconstructPoints(), motionSmootherAlgo::setDisplacement(), Foam::simpleGeometricFilter(), rigidBodyMeshMotion::solve(), rigidBodyMeshMotionSolver::solve(), sixDoFRigidBodyMotionSolver::solve(), hexRef8Data::sync(), pointSet::sync(), syncTools::syncPointList(), syncTools::syncPointList(), weightedPosition::syncPoints(), meshRefinement::testSyncPointList(), meshRefinement::testSyncPointList(), inverseDistance::update(), trackingInverseDistance::update(), faMeshTools::writeProcAddressing(), and fvMeshTools::writeProcAddressing().
nEdges()
Foam::label nEdges () const inline
Definition at line 60 of file primitiveMeshI.H.
References UPtrList< T >::size().
Referenced by Foam::createReconstructMap(), primitiveMesh::edgeCells(), primitiveMesh::edgeFaces(), directionInfo::edgeToFaceIndex(), syncTools::getMasterEdges(), addPatchCellLayer::globalEdgeFaces(), syncTools::syncEdgeList(), syncTools::syncEdgeList(), faBoundaryMesh::whichPatch(), and faMeshTools::writeProcAddressing().
nFaces()
Foam::label nFaces () const inline noexcept
Definition at line 83 of file primitiveMeshI.H.
Referenced by fvMeshAdder::add(), polyMeshAdder::add(), snappyLayerDriver::addLayers(), snappyLayerDriver::addLayers(), meshRefinement::addPatch(), holeToFace::calcClosure(), curvatureSeparation::calcCosAngle(), primitiveMesh::calcFaceCentresAndAreas(), CentredFitSnGradData< Polynomial >::calcFit(), dynamicRefineFvMesh::calculateProtectedCells(), polyTopoChange::changeMesh(), polyMeshGeometry::checkFaceDotProduct(), polyMeshGeometry::checkFaceTets(), polyMeshTetDecomposition::checkFaceTets(), polyMeshGeometry::checkFaceTwist(), polyMeshGeometry::checkFaceWeights(), motionSmootherAlgo::checkMesh(), polyMeshGeometry::checkVolRatio(), curvatureSeparation::correct(), Foam::createReconstructMap(), Foam::createReconstructMap(), structuredDecomp::decompose(), decompositionMethod::decompose(), snappyLayerDriver::doLayers(), snappySnapDriver::doSnap(), treeDataFace::empty(), primitiveMeshTools::faceConcavity(), primitiveMeshTools::faceFlatness(), primitiveMeshTools::facePyramidVolume(), polyMeshTools::faceSkewness(), primitiveMeshTools::faceSkewness(), polyMeshTools::faceWeights(), polyMeshTetDecomposition::findFaceBasePts(), syncTools::getInternalOrCoupledFaces(), syncTools::getInternalOrMasterFaces(), syncTools::getMasterFaces(), highAspectRatioFvGeometryScheme::makeAverageCentres(), polyTopoChange::makeMesh(), dynamicRefineFvMesh::mapNewInternalFaces(), meshRefinement::markOutsideFaces(), faceBitSet::maxSize(), faceBoolSet::maxSize(), faceSet::maxSize(), faceZoneSet::maxSize(), snappyLayerDriver::mergePatchFacesUndo(), polyMesh::polyMesh(), polyMesh::polyMesh(), snappySnapDriver::preSmoothPatch(), fvMeshDistribute::printMeshInfo(), structuredRenumber::renumber(), snappySnapDriver::repatchToSurface(), snappySnapDriver::scaleMesh(), decompositionMethod::setConstraints(), treeDataFace::size(), meshRefinement::subsetBaffles(), faceSet::sync(), faceZoneSet::sync(), syncTools::syncEdgeMap(), syncTools::syncFaceList(), polyMeshTools::volRatio(), polyBoundaryMesh::whichPatchFace(), faMeshTools::writeProcAddressing(), and fvMeshTools::writeProcAddressing().
nCells()
Foam::label nCells () const inline noexcept
Definition at line 89 of file primitiveMeshI.H.
Referenced by fvMeshAdder::add(), polyMeshAdder::add(), snappyLayerDriver::addLayers(), polyTopoChange::addMesh(), primitiveMesh::calcCellCentresAndVols(), primitiveMesh::calcCells(), holeToFace::calcClosure(), primitiveMeshTools::cellClosedness(), primitiveMeshTools::cellDeterminant(), cuttingSurfaceBase::cellSelection(), polyTopoChange::changeMesh(), ensightCells::classify(), Foam::createReconstructMap(), metisLikeDecomp::decompose(), randomDecomp::decompose(), metisLikeDecomp::decompose(), structuredDecomp::decompose(), decompositionMethod::decompose(), refinementHistory::distribute(), snappyLayerDriver::doLayers(), snappyRefineDriver::doRefine(), treeDataCell::empty(), refinementParameters::findCells(), meshRefinement::findRegions(), get_number_of_vertices(), surfaceSets::getHangingCells(), cellCellStencil::globalCellCells(), hexRef8Data::hexRef8Data(), highAspectRatioFvGeometryScheme::makeAverageCentres(), primitiveMeshTools::makeCellCentresAndVols(), polyTopoChange::makeMesh(), cellBitSet::maxSize(), cellSet::maxSize(), cellZoneSet::maxSize(), momentOfInertia::meshInertia(), cellTable::operator=(), cuttingPlane::performCut(), cuttingSurface::performCut(), cuttingSurfaceBase::performCut(), sampledSurface::pointAverage(), polyMesh::polyMesh(), fvMeshDistribute::printMeshInfo(), fvFieldReconstructor::reconstructField(), Foam::reconstructLagrangian(), renumberMethod::renumber(), springRenumber::renumber(), CuthillMcKeeRenumber::renumber(), structuredRenumber::renumber(), SloanRenumber::renumber(), zoltanRenumber::renumber(), cellBitSet::select(), Foam::simpleGeometricFilter(), treeDataCell::size(), Foam::sumNeighbours(), reconstructionSchemes::surface(), syncTools::swapBoundaryCellList(), hexRef8Data::sync(), fvMeshTools::writeProcAddressing(), and cellCellStencil::zoneID().
nInternalFaces()
Foam::label nInternalFaces () const inline noexcept
Definition at line 71 of file primitiveMeshI.H.
Referenced by polyMeshAdder::add(), snappyLayerDriver::addLayers(), polyTopoChange::addMesh(), oversetFvPatchField< Type >::adjustPsi(), decompositionMethod::calcCellCells(), decompositionMethod::calcCellCells(), polyDualMesh::calcFeatures(), CentredFitSnGradData< Polynomial >::calcFit(), dynamicRefineFvMesh::calculateProtectedCells(), primitiveMesh::checkClosedBoundary(), meshRefinement::checkCoupledFaceZones(), polyBoundaryMesh::checkDefinition(), polyMeshGeometry::checkFaceDotProduct(), polyMeshGeometry::checkFaceSkewness(), polyMeshGeometry::checkFaceTets(), polyMeshTetDecomposition::checkFaceTets(), polyMeshGeometry::checkFaceTwist(), polyMeshGeometry::checkFaceWeights(), faceZone::checkParallelSync(), polyMeshGeometry::checkVolRatio(), inverseFaceDistanceDiffusivity::correct(), inversePointDistanceDiffusivity::correct(), decompositionMethod::decompose(), snappyLayerDriver::doLayers(), primitiveMeshTools::faceOrthogonality(), primitiveMeshTools::facePyramidVolume(), polyMeshTools::faceSkewness(), primitiveMeshTools::faceSkewness(), polyMeshTools::faceWeights(), localPointRegion::findDuplicateFacePairs(), localPointRegion::findDuplicateFaces(), polyMeshTetDecomposition::findFaceBasePts(), volPointInterpolation::flatBoundaryField(), boundaryMesh::getNearest(), cellCellStencil::globalCellCells(), cellToCellStencil::insertFaceCells(), cellToFaceStencil::insertFaceCells(), highAspectRatioFvGeometryScheme::makeAverageCentres(), dynamicRefineFvMesh::mapNewInternalFaces(), meshRefinement::markOutsideFaces(), fvMeshTools::newMesh(), polyMeshAdder::patchFacePairs(), boundaryMesh::patchify(), fvMeshDistribute::printCoupleInfo(), fvMeshDistribute::printMeshInfo(), fvSurfaceMapper::size(), oversetFvPatchField< Type >::storeFringeCoefficients(), faceZoneSet::sync(), syncTools::syncBoundaryFaceList(), syncTools::syncEdgeMap(), syncTools::syncFaceList(), cellToCellStencil::validBoundaryFaces(), cellToFaceStencil::validBoundaryFaces(), polyMeshTools::volRatio(), extendedCellToFaceStencil::weightedSum(), and polyBoundaryMesh::whichPatchFace().
nBoundaryFaces()
Foam::label nBoundaryFaces () const inline noexcept
Definition at line 77 of file primitiveMeshI.H.
Referenced by decompositionMethod::calcCellCells(), decompositionMethod::calcCellCells(), polyDualMesh::calcFeatures(), dynamicRefineFvMesh::calculateProtectedCells(), meshRefinement::checkCoupledFaceZones(), polyMeshGeometry::checkFaceDotProduct(), polyMeshGeometry::checkFaceTets(), polyMeshTetDecomposition::checkFaceTets(), polyMeshGeometry::checkFaceTwist(), polyMeshGeometry::checkFaceWeights(), faceZone::checkParallelSync(), polyMeshGeometry::checkVolRatio(), localPointRegion::findDuplicateFacePairs(), polyMeshTetDecomposition::findFaceBasePts(), volPointInterpolation::flatBoundaryField(), boundaryMesh::getNearest(), meshRefinement::markOutsideFaces(), meshRefinement::mergePatchFaces(), boundaryMesh::patchify(), boundaryMesh::read(), SloanRenumber::renumber(), mappedPatchBase::sampleSize(), syncTools::swapBoundaryCellList(), faceZoneSet::sync(), syncTools::syncBoundaryFaceList(), triSurfaceTools::triangulate(), and triSurfaceTools::triangulateFaceCentre().
nInternalPoints()
Foam::label nInternalPoints () const inline noexcept
Definition at line 24 of file primitiveMeshI.H.
nInternal0Edges()
Foam::label nInternal0Edges () const inline
Definition at line 36 of file primitiveMeshI.H.
nInternal1Edges()
Foam::label nInternal1Edges () const inline
Definition at line 44 of file primitiveMeshI.H.
nInternalEdges()
Foam::label nInternalEdges () const inline
Definition at line 52 of file primitiveMeshI.H.
Referenced by faBoundaryMesh::checkDefinition().
points()
virtual const pointField & points () const pure virtual
Implemented in polyMesh.
Referenced by primitiveMesh::calcFaceCentresAndAreas(), primitiveMesh::cellBb(), primitiveMesh::checkEdgeLength(), primitiveMesh::checkPointNearness(), and boundaryMesh::getNearest().
faces()
virtual const faceList & faces () const pure virtual
Implemented in polyMesh.
Referenced by primitiveMesh::cellBb(), primitiveMesh::checkEdgeLength(), boundaryMesh::getNearest(), treeDataFace::operator[](), and primitiveMesh::pointFaces().
faceOwner()
virtual const labelList & faceOwner () const pure virtual
Implemented in polyMesh.
faceNeighbour()
virtual const labelList & faceNeighbour () const pure virtual
Implemented in polyMesh.
oldPoints()
virtual const pointField & oldPoints () const pure virtual
Implemented in polyMesh.
cellShapes()
const Foam::cellShapeList & cellShapes () const
Definition at line 325 of file primitiveMesh.C.
edges()
const Foam::edgeList & edges () const
Definition at line 510 of file primitiveMeshEdges.C.
Referenced by motionSmootherAlgo::avg(), addPatchCellLayer::calcExtrudeInfo(), polyDualMesh::calcFeatures(), edgeVertex::coord(), geomCellLooper::cut(), topoCellLooper::cut(), directionInfo::edgeToFaceIndex(), searchableExtrudedCircle::findParametricNearest(), cellLooper::getFirstVertEdge(), searchableExtrudedCircle::getNormal(), addPatchCellLayer::globalEdgeFaces(), boundaryMesh::setFeatureEdges(), meshCutter::setRefinement(), meshCutAndRemove::setRefinement(), syncTools::syncEdgeList(), syncTools::syncEdgeList(), directionInfo::updateCell(), externalPointEdgePoint::updateEdge(), pointEdgePoint::updateEdge(), and edgeVertex::writeCut().
calcCells()
void calcCells (cellList & cellFaceAddr, const labelUList & own, const labelUList & nei, const label nCells = -1) static
Definition at line 25 of file primitiveMeshCells.C.
References forAll, Foam::max(), primitiveMesh::nCells(), PtrList< T >::setSize(), UPtrList< T >::size(), and Foam::Zero.
calcPointOrder()
bool calcPointOrder (label & nInternalPoints, labelList & pointMap, const faceList & faces, const label nInternalFaces, const label nPoints) static
Definition at line 121 of file primitiveMesh.C.
References f(), forAll, nPoints, and UList< T >::size().
cellCells() [1/3]
const Foam::labelListList & cellCells () const
Definition at line 95 of file primitiveMeshCellCells.C.
Referenced by meshToMeshMethod::appendNbrCells().
edgeCells() [1/3]
const Foam::labelListList & edgeCells () const
Definition at line 27 of file primitiveMeshEdgeCells.C.
References Foam::abort(), primitiveMesh::cellEdges(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, Foam::invertManyToMany(), primitiveMesh::nEdges(), and Foam::Pout.
pointCells() [1/3]
const Foam::labelListList & pointCells () const
Definition at line 185 of file primitiveMeshPointCells.C.
Referenced by cellDistFuncs::correctBoundaryPointCells(), volPointInterpolation::interpolateDimensionedInternalField(), and sampledSurface::pointAverage().
cells()
const Foam::cellList & cells () const
Definition at line 131 of file primitiveMeshCells.C.
Referenced by polyMeshTetDecomposition::adjustTetBasePtIs(), treeDataCell::bounds(), pointMVCWeight::calcWeights(), primitiveMesh::cellBb(), primitiveMeshTools::cellDeterminant(), manifoldCellsMeshObject::cells(), polyMeshTetDecomposition::cellTetIndices(), layerAdditionRemoval::changeTopology(), polyMeshGeometry::checkCellDeterminant(), primitiveMeshGeometry::checkCellDeterminant(), polyMeshGeometry::checkFacePyramids(), primitiveMeshGeometry::checkFacePyramids(), inversePointDistanceDiffusivity::correct(), outletStabilised< Type >::correction(), wallBoundedParticle::crossEdgeConnectedFace(), geomCellLooper::cut(), topoCellLooper::cut(), probes::findElements(), sampledSet::findNearFace(), polyMeshTetDecomposition::findTet(), surfaceSets::getHangingCells(), cellCellStencil::globalCellCells(), prismMatcher::isA(), tetWedgeMatcher::isA(), wedgeMatcher::isA(), Foam::markGrowFaceCellFace(), degenerateMatcher::match(), hexMatcher::matches(), prismMatcher::matches(), pyrMatcher::matches(), tetMatcher::matches(), tetWedgeMatcher::matches(), wedgeMatcher::matches(), polyMesh::polyMesh(), polyMesh::polyMesh(), polyMesh::polyMesh(), cyclicACMIPolyPatch::scalePatchFaceAreas(), meshCutter::setRefinement(), fvMatrix< Type >::setValuesFromList(), hexMatcher::test(), pyrMatcher::test(), tetMatcher::test(), primitiveMeshTools::updateCellCentresAndVols(), and outletStabilised< Type >::weights().
edgeFaces() [1/3]
const Foam::labelListList & edgeFaces () const
Definition at line 27 of file primitiveMeshEdgeFaces.C.
References Foam::abort(), Foam::endl(), primitiveMesh::faceEdges(), Foam::FatalError, FatalErrorInFunction, Foam::invertManyToMany(), primitiveMesh::nEdges(), and Foam::Pout.
Referenced by addPatchCellLayer::calcExtrudeInfo(), boundaryMesh::setFeatureEdges(), meshCutter::setRefinement(), and meshCutAndRemove::setRefinement().
pointFaces()
const Foam::labelListList & pointFaces () const
Definition at line 26 of file primitiveMeshPointFaces.C.
References Foam::endl(), primitiveMesh::faces(), Foam::invertManyToMany(), primitiveMesh::nPoints(), and Foam::Pout.
Referenced by motionSmootherAlgo::checkMesh(), decompositionMethod::decompose(), cellLooper::getVertFacesNonEdge(), and perfectInterface::setRefinement().
cellEdges() [1/3]
const Foam::labelListList & cellEdges () const
Definition at line 114 of file primitiveMeshCellEdges.C.
Referenced by polyDualMesh::calcFeatures(), geomCellLooper::cut(), primitiveMesh::edgeCells(), cellLooper::getMisAlignedEdge(), and meshCutter::setRefinement().
faceEdges() [1/3]
const Foam::labelListList & faceEdges () const
Definition at line 533 of file primitiveMeshEdges.C.
References Foam::endl(), f(), UList< T >::fcIndex(), forAll, Foam::Pout, PtrList< T >::setSize(), UPtrList< T >::size(), and UList< T >::size().
Referenced by primitiveMesh::edgeFaces(), cellLooper::getFirstVertEdge(), cellLooper::getVertEdgesNonFace(), faMatrix< Type >::setValuesFromList(), and directionInfo::updateCell().
pointEdges()
const Foam::labelListList & pointEdges () const
Definition at line 521 of file primitiveMeshEdges.C.
Referenced by addPatchCellLayer::calcExtrudeInfo(), searchableExtrudedCircle::findParametricNearest(), cellLooper::getVertEdgesNonFace(), and addPatchCellLayer::globalEdgeFaces().
pointPoints() [1/3]
const Foam::labelListList & pointPoints () const
Definition at line 87 of file primitiveMeshPointPoints.C.
cellPoints() [1/3]
const Foam::labelListList & cellPoints () const
Definition at line 104 of file primitiveMeshCellPoints.C.
Referenced by treeDataCell::bounds(), primitiveMesh::cellBb(), tetOverlapVolume::overlappingCells(), meshCutAndRemove::setRefinement(), and Foam::simpleGeometricFilter().
cellCentres()
const Foam::vectorField & cellCentres () const
Definition at line 78 of file primitiveMeshCellCentresAndVols.C.
References primitiveMesh::updateGeom().
Referenced by polyMeshAdder::add(), polyTopoChange::addMesh(), snappySnapDriver::avgCellCentres(), tetIndices::barycentricToPoint(), treeDataCell::centre(), polyMeshTetDecomposition::checkFaceTets(), motionSmootherAlgo::checkMesh(), cellDistFuncs::correctBoundaryFaceCells(), cellDistFuncs::correctBoundaryPointCells(), structuredDecomp::decompose(), decompositionMethod::decompose(), mappedPatchBase::facePoint(), polyMeshTetDecomposition::findBasePoint(), probes::findElements(), polyMeshTetDecomposition::findFaceBasePts(), mappedPatchBase::findLocalSamples(), polyMeshTetDecomposition::findSharedBasePoint(), polyMeshTetDecomposition::findSharedBasePoint(), Foam::getMeshPointRef(), cellCellStencil::globalCellCells(), volPointInterpolation::interpolateDimensionedInternalField(), oversetFvPatchField< Type >::manipulateMatrix(), polyMeshTetDecomposition::minQuality(), InflationInjection< CloudType >::parcelsToInject(), sampledSet::pushIn(), cyclicACMIPolyPatch::scalePatchFaceAreas(), patchInjectionBase::setPositionAndCell(), tetIndices::tet(), meshToMeshData::updateCell(), refinementDistanceData::updateCell(), sweepData::updateCell(), wallPoint::updateCell(), wallPoints::updateCell(), polyMesh::updateMesh(), cellSet::writeDebug(), and cellBitSet::writeDebug().
faceCentres()
const Foam::vectorField & faceCentres () const
Definition at line 71 of file primitiveMeshFaceCentresAndAreas.C.
References primitiveMesh::updateGeom().
Referenced by primitiveMesh::calcCellCentresAndVols(), FitData< FitDataType, ExtendedStencil, Polynomial >::calcFit(), CentredFitSnGradData< Polynomial >::calcFit(), sampledSet::calcSign(), treeDataFace::centre(), polyMeshTetDecomposition::checkFaceTets(), motionSmootherAlgo::checkMesh(), decompositionMethod::decompose(), snappySnapDriver::doSnap(), mappedPatchBase::facePoint(), localPointRegion::findDuplicateFacePairs(), probes::findElements(), polyMeshTetDecomposition::findFaceBasePts(), mappedPatchBase::findLocalSamples(), boundaryMesh::getNearest(), fvMeshDistribute::printCoupleInfo(), sampledSet::pushIn(), snappySnapDriver::repatchToSurface(), cyclicACMIPolyPatch::scalePatchFaceAreas(), fvMeshDistribute::testField(), wallBoundedParticle::trackToEdge(), triSurfaceTools::triangulateFaceCentre(), wallPointData< scalar >::updateCell(), refinementDistanceData::updateFace(), sweepData::updateFace(), wallPoint::updateFace(), wallPoints::updateFace(), refinementDistanceData::updateFace(), sweepData::updateFace(), wallPoint::updateFace(), wallPoints::updateFace(), transportData::updateFace(), wallPointAddressing::updateFace(), transportData::updateFace(), wallPointAddressing::updateFace(), wallPointData< scalar >::updateFace(), faceSet::writeDebug(), faceBitSet::writeDebug(), and faceBoolSet::writeDebug().
cellVolumes()
const Foam::scalarField & cellVolumes () const
Definition at line 90 of file primitiveMeshCellCentresAndVols.C.
References primitiveMesh::updateGeom().
Referenced by polyTopoChange::changeMesh(), layerAdditionRemoval::changeTopology(), motionSmootherAlgo::checkMesh(), polyTopoChange::makeMesh(), KinematicParcel< ParcelType >::massCell(), cyclicACMIPolyPatch::scalePatchFaceAreas(), cyclicACMIPolyPatch::scalePatchFaceAreas(), and elasticityMotionSolver::solve().
faceAreas()
const Foam::vectorField & faceAreas () const
Definition at line 83 of file primitiveMeshFaceCentresAndAreas.C.
References primitiveMesh::updateGeom().
Referenced by decompositionMethod::calcCellCells(), primitiveMesh::calcCellCentresAndVols(), layerAdditionRemoval::changeTopology(), motionSmootherAlgo::checkMesh(), FitData< FitDataType, ExtendedStencil, Polynomial >::findFaceDirs(), cellPointWeight::findTriangle(), boundaryMesh::getNearest(), fvMesh::makeSf(), and cyclicACMIPolyPatch::scalePatchFaceAreas().
movePoints()
void movePoints (const pointField & p, const pointField & oldP)
Definition at line 311 of file primitiveMesh.C.
Referenced by polyMesh::movePoints().
isInternalFace()
bool isInternalFace (const label faceIndex) const inline noexcept
Definition at line 95 of file primitiveMeshI.H.
Referenced by polyMeshTetDecomposition::adjustTetBasePtIs(), polyMeshGeometry::affectedCells(), addPatchCellLayer::calcExtrudeInfo(), polyMeshGeometry::checkFaceDotProduct(), primitiveMeshGeometry::checkFaceDotProduct(), polyMeshGeometry::checkFacePyramids(), primitiveMeshGeometry::checkFacePyramids(), polyMeshGeometry::checkFaceSkewness(), primitiveMeshGeometry::checkFaceSkewness(), polyMeshGeometry::checkFaceTets(), polyMeshTetDecomposition::checkFaceTets(), polyMeshGeometry::checkFaceTwist(), polyMeshGeometry::checkFaceWeights(), primitiveMeshGeometry::checkFaceWeights(), faceZone::checkParallelSync(), polyMeshGeometry::checkVolRatio(), outletStabilised< Type >::correction(), decompositionMethod::decompose(), primitiveMeshTools::facePyramidVolume(), Foam::markGrowFaceCellFace(), polyMeshTetDecomposition::minQuality(), perfectInterface::setRefinement(), fvMatrix< Type >::setValuesFromList(), sampledFaceZone::update(), and outletStabilised< Type >::weights().
checkUpperTriangular()
bool checkUpperTriangular (const bool report = false, labelHashSet * setPtr = nullptr) const virtual
Definition at line 907 of file primitiveMeshCheck.C.
References cells, DebugInFunction, Foam::endl(), forAll, Foam::Info, Foam::labelMax, Foam::reduce(), UPstream::reduceOr(), and UPtrList< T >::size().
checkCellsZipUp()
bool checkCellsZipUp (const bool report = false, labelHashSet * setPtr = nullptr) const virtual
Definition at line 1065 of file primitiveMeshCheck.C.
References cells, DebugInFunction, Foam::endl(), f(), forAll, Foam::Info, Foam::reduce(), UList< T >::size(), and Foam::Zero.
checkFaceVertices()
bool checkFaceVertices (const bool report = false, labelHashSet * setPtr = nullptr) const virtual
Definition at line 1158 of file primitiveMeshCheck.C.
References DebugInFunction, Foam::endl(), f(), forAll, Foam::Info, HashSet< Key, Hash >::insert(), Foam::max(), Foam::min(), nPoints, Foam::reduce(), and UPtrList< T >::size().
checkPoints()
bool checkPoints (const bool report = false, labelHashSet * setPtr = nullptr) const virtual
Definition at line 1226 of file primitiveMeshCheck.C.
References DebugInFunction, UList< T >::empty(), Foam::endl(), forAll, Foam::Info, and Foam::reduce().
checkFaceFaces()
bool checkFaceFaces (const bool report = false, labelHashSet * setPtr = nullptr) const virtual
Definition at line 1495 of file primitiveMeshCheck.C.
References PtrList< T >::clear(), DebugInFunction, Foam::endl(), forAll, Foam::Info, and Foam::reduce().
checkClosedBoundary() [2/2]
bool checkClosedBoundary (const bool report = false) const virtual
Definition at line 1591 of file primitiveMeshCheck.C.
checkClosedCells() [2/2]
bool checkClosedCells (const bool report = false, labelHashSet * setPtr = nullptr, labelHashSet * highAspectSetPtr = nullptr, const Vector< label > & solutionD = Vector<label>::one) const virtual
Definition at line 1597 of file primitiveMeshCheck.C.
checkFaceAreas() [2/2]
bool checkFaceAreas (const bool report = false, labelHashSet * setPtr = nullptr) const virtual
Definition at line 1617 of file primitiveMeshCheck.C.
checkCellVolumes() [2/2]
bool checkCellVolumes (const bool report = false, labelHashSet * setPtr = nullptr) const virtual
Definition at line 1633 of file primitiveMeshCheck.C.
checkFaceOrthogonality() [2/2]
bool checkFaceOrthogonality (const bool report = false, labelHashSet * setPtr = nullptr) const virtual
Reimplemented in polyMesh.
Definition at line 1649 of file primitiveMeshCheck.C.
checkFacePyramids() [2/2]
bool checkFacePyramids (const bool report = false, const scalar minPyrVol = -SMALL, labelHashSet * setPtr = nullptr) const virtual
Definition at line 1665 of file primitiveMeshCheck.C.
References points.
checkFaceSkewness() [2/2]
bool checkFaceSkewness (const bool report = false, labelHashSet * setPtr = nullptr) const virtual
Reimplemented in polyMesh.
Definition at line 1684 of file primitiveMeshCheck.C.
References points.
checkFaceAngles() [2/2]
bool checkFaceAngles (const bool report = false, const scalar maxSin = 10, labelHashSet * setPtr = nullptr) const virtual
Definition at line 1702 of file primitiveMeshCheck.C.
References points.
checkFaceFlatness() [2/2]
bool checkFaceFlatness (const bool report, const scalar warnFlatness, labelHashSet * setPtr) const virtual
Definition at line 1720 of file primitiveMeshCheck.C.
References points.
checkPointNearness()
bool checkPointNearness (const bool report, const scalar reportDistSqr, labelHashSet * setPtr = nullptr) const virtual
Definition at line 27 of file primitiveMeshCheckPointNearness.C.
References Foam::endl(), Foam::Info, Foam::magSqr(), primitiveMesh::points(), Foam::reduce(), UPtrList< T >::size(), and Foam::sqrt().
checkEdgeLength()
bool checkEdgeLength (const bool report, const scalar minLenSqr, labelHashSet * setPtr = nullptr) const virtual
Definition at line 26 of file primitiveMeshCheckEdgeLength.C.
References Foam::endl(), f(), primitiveMesh::faces(), forAll, Foam::Info, Foam::magSqr(), Foam::max(), Foam::min(), primitiveMesh::nPoints(), primitiveMesh::points(), Foam::reduce(), Foam::returnReduce(), UPtrList< T >::size(), Foam::sqr(), Foam::sqrt(), and PtrList< T >::transfer().
checkConcaveCells() [2/2]
bool checkConcaveCells (const bool report = false, labelHashSet * setPtr = nullptr) const virtual
Definition at line 1739 of file primitiveMeshCheck.C.
checkTopology()
bool checkTopology (const bool report = false) const virtual
Definition at line 1755 of file primitiveMeshCheck.C.
References Foam::endl(), and Foam::Info.
checkGeometry()
bool checkGeometry (const bool report = false) const virtual
Definition at line 1785 of file primitiveMeshCheck.C.
References Foam::endl(), and Foam::Info.
checkMesh()
bool checkMesh (const bool report = false) const virtual
Definition at line 1817 of file primitiveMeshCheck.C.
References Foam::checkGeometry(), Foam::checkTopology(), DebugInFunction, Foam::endl(), and Foam::Info.
Referenced by polyMesh::polyMesh(), and polyMesh::polyMesh().
setClosedThreshold()
Foam::scalar setClosedThreshold (const scalar val) static
Definition at line 1843 of file primitiveMeshCheck.C.
setAspectThreshold()
Foam::scalar setAspectThreshold (const scalar val) static
Definition at line 1852 of file primitiveMeshCheck.C.
setNonOrthThreshold()
Foam::scalar setNonOrthThreshold (const scalar val) static
Definition at line 1861 of file primitiveMeshCheck.C.
setSkewThreshold()
Foam::scalar setSkewThreshold (const scalar val) static
Definition at line 1870 of file primitiveMeshCheck.C.
cellBb()
Foam::boundBox cellBb (const label celli) const
Definition at line 28 of file primitiveMeshFindCell.C.
References primitiveMesh::cellPoints(), primitiveMesh::cells(), primitiveMesh::faces(), primitiveMesh::hasCellPoints(), and primitiveMesh::points().
Referenced by Foam::simpleGeometricFilter().
pointInCellBB()
bool pointInCellBB (const point & p, label celli, scalar inflationFraction = 0) const
Definition at line 40 of file primitiveMeshFindCell.C.
References boundBox::contains(), boundBox::inflate(), and p.
pointInCell()
bool pointInCell (const point & p, label celli) const
Definition at line 58 of file primitiveMeshFindCell.C.
References cells, f(), forAll, and p.
Referenced by polyMesh::pointInCell().
findNearestCell()
Foam::label findNearestCell (const point & location) const
Definition at line 85 of file primitiveMeshFindCell.C.
References Foam::magSqr(), and UList< T >::size().
findCell()
Foam::label findCell (const point & location) const
Definition at line 112 of file primitiveMeshFindCell.C.
References n.
printAllocated()
void printAllocated () const
Definition at line 26 of file primitiveMeshClear.C.
References Foam::endl(), and Foam::Pout.
hasCellShapes()
bool hasCellShapes () const inline noexcept
Definition at line 104 of file primitiveMeshI.H.
hasEdges()
bool hasEdges () const inline noexcept
Definition at line 110 of file primitiveMeshI.H.
hasCellCells()
bool hasCellCells () const inline noexcept
Definition at line 116 of file primitiveMeshI.H.
hasEdgeCells()
bool hasEdgeCells () const inline noexcept
Definition at line 122 of file primitiveMeshI.H.
hasPointCells()
bool hasPointCells () const inline noexcept
Definition at line 128 of file primitiveMeshI.H.
hasCells()
bool hasCells () const inline noexcept
Definition at line 134 of file primitiveMeshI.H.
hasEdgeFaces()
bool hasEdgeFaces () const inline noexcept
Definition at line 140 of file primitiveMeshI.H.
hasPointFaces()
bool hasPointFaces () const inline noexcept
Definition at line 146 of file primitiveMeshI.H.
hasCellEdges()
bool hasCellEdges () const inline noexcept
Definition at line 152 of file primitiveMeshI.H.
hasFaceEdges()
bool hasFaceEdges () const inline noexcept
Definition at line 158 of file primitiveMeshI.H.
hasPointEdges()
bool hasPointEdges () const inline noexcept
Definition at line 164 of file primitiveMeshI.H.
hasPointPoints()
bool hasPointPoints () const inline noexcept
Definition at line 170 of file primitiveMeshI.H.
hasCellPoints()
bool hasCellPoints () const inline noexcept
Definition at line 176 of file primitiveMeshI.H.
Referenced by treeDataCell::bounds(), Foam::boxesImpl(), and primitiveMesh::cellBb().
hasCellCentres()
bool hasCellCentres () const inline noexcept
Definition at line 182 of file primitiveMeshI.H.
hasCellVolumes()
bool hasCellVolumes () const inline noexcept
Definition at line 188 of file primitiveMeshI.H.
hasFaceCentres()
bool hasFaceCentres () const inline noexcept
Definition at line 194 of file primitiveMeshI.H.
hasFaceAreas()
bool hasFaceAreas () const inline noexcept
Definition at line 200 of file primitiveMeshI.H.
Referenced by cyclicACMIPolyPatch::resetAMI().
cellCells() [2/3]
const Foam::labelList & cellCells (const label celli, DynamicList< label > & storage) const
Definition at line 106 of file primitiveMeshCellCells.C.
References cells, PtrList< T >::clear(), and PtrList< T >::push_back().
cellCells() [3/3]
const Foam::labelList & cellCells (const label celli) const
Definition at line 144 of file primitiveMeshCellCells.C.
cellPoints() [2/3]
const Foam::labelList & cellPoints (const label celli, labelHashSet & set, DynamicList< label > & storage) const
Definition at line 115 of file primitiveMeshCellPoints.C.
References cells, PtrList< T >::clear(), PtrList< T >::push_back(), and UPtrList< T >::size().
cellPoints() [3/3]
const Foam::labelList & cellPoints (const label celli) const
Definition at line 152 of file primitiveMeshCellPoints.C.
pointCells() [2/3]
const Foam::labelList & pointCells (const label pointi, DynamicList< label > & storage) const
Definition at line 196 of file primitiveMeshPointCells.C.
References UPtrList< T >::begin(), PtrList< T >::clear(), UPtrList< T >::end(), pFaces, PtrList< T >::push_back(), PtrList< T >::resize(), and UPtrList< T >::size().
pointCells() [3/3]
const Foam::labelList & pointCells (const label pointi) const
Definition at line 239 of file primitiveMeshPointCells.C.
pointPoints() [2/3]
const Foam::labelList & pointPoints (const label pointi, DynamicList< label > & storage) const
Definition at line 98 of file primitiveMeshPointPoints.C.
References PtrList< T >::clear(), PtrList< T >::push_back(), and UPtrList< T >::size().
pointPoints() [3/3]
const Foam::labelList & pointPoints (const label pointi) const
Definition at line 130 of file primitiveMeshPointPoints.C.
faceEdges() [2/3]
const Foam::labelList & faceEdges (const label facei, DynamicList< label > & storage) const
Definition at line 594 of file primitiveMeshEdges.C.
References PtrList< T >::clear(), f(), Foam::findFirstCommonElementFromSortedLists(), forAll, PtrList< T >::push_back(), and UList< T >::size().
faceEdges() [3/3]
const Foam::labelList & faceEdges (const label facei) const
Definition at line 630 of file primitiveMeshEdges.C.
edgeFaces() [2/3]
const Foam::labelList & edgeFaces (const label edgeI, DynamicList< label > & storage) const
Definition at line 53 of file primitiveMeshEdgeFaces.C.
References PtrList< T >::append(), PtrList< T >::clear(), e, f(), UList< T >::fcIndex(), UList< T >::find(), UList< T >::rcIndex(), and UPtrList< T >::size().
edgeFaces() [3/3]
const Foam::labelList & edgeFaces (const label edgeI) const
Definition at line 119 of file primitiveMeshEdgeFaces.C.
edgeCells() [2/3]
const Foam::labelList & edgeCells (const label edgeI, DynamicList< label > & storage) const
Definition at line 52 of file primitiveMeshEdgeCells.C.
References PtrList< T >::clear(), and PtrList< T >::push_back().
edgeCells() [3/3]
const Foam::labelList & edgeCells (const label edgeI) const
Definition at line 99 of file primitiveMeshEdgeCells.C.
cellEdges() [2/3]
const Foam::labelList & cellEdges (const label celli, labelHashSet & set, DynamicList< label > & storage) const
Definition at line 636 of file primitiveMeshEdges.C.
References cells, PtrList< T >::clear(), PtrList< T >::push_back(), and UPtrList< T >::size().
cellEdges() [3/3]
const Foam::labelList & cellEdges (const label celli) const
Definition at line 672 of file primitiveMeshEdges.C.
updateGeom()
void updateGeom () virtual
Reimplemented in fvMesh.
Definition at line 336 of file primitiveMesh.C.
Referenced by primitiveMesh::cellCentres(), primitiveMesh::cellVolumes(), primitiveMesh::faceAreas(), primitiveMesh::faceCentres(), basicFvGeometryScheme::movePoints(), highAspectRatioFvGeometryScheme::movePoints(), and solidBodyFvGeometryScheme::movePoints().
clearGeom()
void clearGeom ()
Definition at line 119 of file primitiveMeshClear.C.
References Foam::deleteDemandDrivenData(), Foam::endl(), and Foam::Pout.
Referenced by polyMesh::clearGeom(), fvGeometryScheme::movePoints(), solidBodyFvGeometryScheme::movePoints(), and polyMesh::updateGeomPoints().
clearCellGeom()
void clearCellGeom ()
Definition at line 135 of file primitiveMeshClear.C.
References Foam::deleteDemandDrivenData(), Foam::endl(), and Foam::Pout.
clearAddressing()
void clearAddressing ()
Definition at line 149 of file primitiveMeshClear.C.
References Foam::deleteDemandDrivenData(), Foam::endl(), and Foam::Pout.
Referenced by polyMesh::clearAddressing().
clearOut()
void clearOut ()
Definition at line 178 of file primitiveMeshClear.C.
Member Data Documentation
closedThreshold_
Foam::scalar closedThreshold_ = 1.0e-6 static protected
Definition at line 225 of file primitiveMesh.H.
Referenced by primitiveMesh::checkClosedBoundary().
aspectThreshold_
Foam::scalar aspectThreshold_ = 1000 static protected
Definition at line 228 of file primitiveMesh.H.
nonOrthThreshold_
Foam::scalar nonOrthThreshold_ = 70 static protected
Definition at line 231 of file primitiveMesh.H.
skewThreshold_
Foam::scalar skewThreshold_ = 4 static protected
Definition at line 234 of file primitiveMesh.H.
planarCosAngle_
Foam::scalar planarCosAngle_ = 1.0e-6 static protected
Definition at line 237 of file primitiveMesh.H.
cellsPerEdge_
const unsigned cellsPerEdge_ = 4 static
Definition at line 385 of file primitiveMesh.H.
cellsPerPoint_
const unsigned cellsPerPoint_ = 8 static
Definition at line 388 of file primitiveMesh.H.
facesPerCell_
const unsigned facesPerCell_ = 6 static
Definition at line 391 of file primitiveMesh.H.
facesPerEdge_
const unsigned facesPerEdge_ = 4 static
Definition at line 394 of file primitiveMesh.H.
facesPerPoint_
const unsigned facesPerPoint_ = 12 static
Definition at line 397 of file primitiveMesh.H.
edgesPerCell_
const unsigned edgesPerCell_ = 12 static
Definition at line 400 of file primitiveMesh.H.
edgesPerFace_
const unsigned edgesPerFace_ = 4 static
Definition at line 403 of file primitiveMesh.H.
edgesPerPoint_
const unsigned edgesPerPoint_ = 6 static
Definition at line 406 of file primitiveMesh.H.
pointsPerCell_
const unsigned pointsPerCell_ = 8 static
Definition at line 409 of file primitiveMesh.H.
pointsPerFace_
const unsigned pointsPerFace_ = 4 static
Definition at line 412 of file primitiveMesh.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/primitiveMesh/primitiveMesh.H
src/OpenFOAM/meshes/primitiveMesh/primitiveMesh.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshCalcCellShapes.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshCellCells.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshCellCentresAndVols.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshCellEdges.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshCellPoints.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshCells.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshCheck/primitiveMeshCheck.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshCheck/primitiveMeshCheckEdgeLength.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshCheck/primitiveMeshCheckPointNearness.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshClear.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshEdgeCells.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshEdgeFaces.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshEdges.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshFaceCentresAndAreas.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshFindCell.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshI.H
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshPointCells.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshPointFaces.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshPointPoints.C