OpenFOAM: functionObject Class Reference
functionObject Class Reference abstract
Abstract base-class for Time/database function objects.
#include <functionObject.H>
Classes
class unavailableFunctionObject
Public Member Functions
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name, const bool withNamePrefix=defaultUseNamePrefix)
autoPtr< functionObject > clone () const
virtual ~functionObject ()=default
virtual const word & type () const =0
const word & name () const noexcept
bool useNamePrefix () const noexcept
bool useNamePrefix (bool on) noexcept
virtual bool read (const dictionary &dict)
virtual bool execute ()=0
virtual bool execute (const label subIndex)
virtual bool write ()=0
virtual bool end ()
virtual bool adjustTimeStep ()
virtual bool filesModified () const
virtual void updateMesh (const mapPolyMesh &mpm)
virtual void movePoints (const polyMesh &mesh)
Static Public Member Functions
static autoPtr< functionObject > New (const word &name, const Time &runTime, const dictionary &dict)
Public Attributes
bool log
Static Public Attributes
static int debug
static bool postProcess
static bool defaultUseNamePrefix
static word outputPrefix
Protected Member Functions
word scopedName (const word &name) const
Detailed Description
Abstract base-class for Time/database function objects.
See also
Foam::functionObjectList
Foam::functionObjects::timeControl
Source files
functionObject.H
functionObject.C
Definition at line 329 of file functionObject.H.
Constructor & Destructor Documentation
functionObject()
functionObject (const word & name, const bool withNamePrefix = defaultUseNamePrefix) explicit
Definition at line 57 of file functionObject.C.
~functionObject()
virtual ~functionObject () virtual default
Member Function Documentation
scopedName()
Foam::word scopedName (const word & name) const protected
Definition at line 44 of file functionObject.C.
References functionObject::name(), and IOobject::scopedName().
Referenced by momentumError::momentumError(), proudmanAcousticPower::proudmanAcousticPower(), fieldExpression::setResultName(), wallHeatFlux::wallHeatFlux(), wallShearStress::wallShearStress(), and yPlus::yPlus().
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , functionObject , dictionary , (const word &name, const Time &runTime, const dictionary &dict) , (name, runTime, dict))
clone()
autoPtr< functionObject > clone () const inline
Definition at line 398 of file functionObject.H.
References NotImplemented.
New()
Foam::autoPtr< Foam::functionObject > New (const word & name, const Time & runTime, const dictionary & dict) static
Definition at line 71 of file functionObject.C.
References dictionary::csearchCompat(), DebugInfo, dict, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, FatalErrorInLookup, dictionary::get(), Time::libs(), Foam::name(), Foam::nl, dlLibraryTable::open(), and runTime.
Referenced by functionObjectList::read(), multiFieldValue::read(), multiRegion::read(), and codedFunctionObject::redirectFunctionObject().
type()
virtual const word & type () const pure virtual
Referenced by functionObject::unavailableFunctionObject::carp(), extractEulerianParticles::checkFaceZone(), fieldsExpression::fieldsExpression(), fieldExpression::foundObject(), sizeDistribution::initialise(), and fieldAverage::initialize().
name()
const Foam::word & name () const noexcept
Definition at line 136 of file functionObject.C.
Referenced by extractEulerianParticles::checkFaceZone(), extractEulerianParticles::extractEulerianParticles(), fieldsExpression::fieldsExpression(), fieldExpression::foundObject(), sizeDistribution::initialise(), fieldAverage::initialize(), moleFractions< ThermoType >::moleFractions(), fieldValue::New(), pointHistory::pointHistory(), functionObject::scopedName(), sizeDistribution::sizeDistribution(), DESModelRegions::write(), wallHeatFlux::write(), wallShearStress::write(), yPlus::write(), and writeFreeSurface::writeFreeSurface().
useNamePrefix() [1/2]
bool useNamePrefix () const noexcept
Definition at line 142 of file functionObject.C.
useNamePrefix() [2/2]
bool useNamePrefix (bool on) noexcept
Definition at line 148 of file functionObject.C.
read()
bool read (const dictionary & dict) virtual
Reimplemented in age, AMIWeights, blendingFactor, comfort, continuityError, CourantNo, Curle, ddt2, DESModelRegions, extractEulerianParticles, fieldAverage, fieldExtents, fieldMinMax, interfaceHeight, log, mapFields, momentum, momentumError, norm, particleDistribution, PecletNo, pow, pressure, processorField, proudmanAcousticPower, reactionsSensitivityAnalysis< chemistryType >, regionSizeDistribution, stabilityBlendingFactor, streamLine, streamLineBase, surfaceDistance, surfaceInterpolate, turbulenceFields, valueAverage, wallBoundedStreamLine, wallShearStress, writeCellCentres, writeCellVolumes, XiReactionRate, yPlus, propellerInfo, dsmcFields, icoUncoupledKinematicCloud, energySpectrum, energyTransport, scalarTransport, codedFunctionObject, runTimeControl, solverInfo, syncObjects, thermoCoupleProbes, timeActivatedFileUpdate, writeDictionary, writeObjects, timeControl, filmFlux, patchProbes, probes, sampledSets, sixDoFRigidBodyState, BilgerMixtureFraction, ObukhovLength, pointHistory, writeFreeSurface, binField, columnAverage, derivedFields, DMD, fvExpressionField, externalCoupled, fieldExpression, fieldsExpression, fieldValue, surfaceFieldValue, volFieldValue, fluxSummary, heatTransferCoeff, multiphaseInterHtcModel, reactingEulerHtcModel, histogram, limitFields, multiFieldValue, nearWallFields, randomise, readFields, reference, resolutionIndex, setFlow, wallHeatFlux, zeroGradient, forceCoeffs, forces, hydrostaticPressure, cloudInfo, dataCloud, vtkCloud, phaseForces, sizeDistribution, electricPotential, abort, areaWrite, ensightWrite, multiRegion, removeRegisteredObject, setTimeStepFunctionObject, systemCall, timeInfo, vtkWrite, regionFunctionObject, setTimeStepFaRegionsFunctionObject, sampledSurfaces, specieReactionRates< ChemistryModelType >, and moleFractions< ThermoType >.
Definition at line 156 of file functionObject.C.
References dict, dictionary::getOrDefault(), keyType::LITERAL, and Foam::log().
Referenced by age::read(), AMIWeights::read(), comfort::read(), continuityError::read(), Curle::read(), ddt2::read(), DESModelRegions::read(), extractEulerianParticles::read(), fieldAverage::read(), fieldExtents::read(), fieldMinMax::read(), log::read(), mapFields::read(), momentum::read(), momentumError::read(), particleDistribution::read(), pow::read(), processorField::read(), proudmanAcousticPower::read(), reactionsSensitivityAnalysis< chemistryType >::read(), regionSizeDistribution::read(), streamLineBase::read(), surfaceDistance::read(), surfaceInterpolate::read(), turbulenceFields::read(), wallShearStress::read(), writeCellCentres::read(), writeCellVolumes::read(), XiReactionRate::read(), yPlus::read(), dsmcFields::read(), icoUncoupledKinematicCloud::read(), energySpectrum::read(), energyTransport::read(), scalarTransport::read(), codedFunctionObject::read(), runTimeControl::read(), solverInfo::read(), syncObjects::read(), timeActivatedFileUpdate::read(), writeObjects::read(), filmFlux::read(), sixDoFRigidBodyState::read(), BilgerMixtureFraction::read(), ObukhovLength::read(), binField::read(), columnAverage::read(), derivedFields::read(), DMD::read(), fvExpressionField::read(), externalCoupled::read(), fieldExpression::read(), fieldsExpression::read(), fieldValue::read(), fluxSummary::read(), histogram::read(), limitFields::read(), multiFieldValue::read(), nearWallFields::read(), readFields::read(), resolutionIndex::read(), setFlow::read(), wallHeatFlux::read(), zeroGradient::read(), forces::read(), hydrostaticPressure::read(), dataCloud::read(), vtkCloud::read(), phaseForces::read(), sizeDistribution::read(), electricPotential::read(), abort::read(), ensightWrite::read(), multiRegion::read(), setTimeStepFunctionObject::read(), systemCall::read(), timeInfo::read(), vtkWrite::read(), regionFunctionObject::read(), setTimeStepFaRegionsFunctionObject::read(), and moleFractions< ThermoType >::read().
execute() [1/2]
virtual bool execute () pure virtual
Implemented in ObukhovLength, pointHistory, writeFreeSurface, age, AMIWeights, binField, columnAverage, comfort, continuityError, Curle, ddt2, derivedFields, DESModelRegions, DMD, fvExpressionField, externalCoupled, extractEulerianParticles, fieldAverage, fieldExpression, fieldExtents, fieldMinMax, fieldsExpression, fieldValue, fluxSummary, histogram, interfaceHeight, limitFields, mapFields, momentum, momentumError, multiFieldValue, nearWallFields, particleDistribution, processorField, proudmanAcousticPower, reactionsSensitivityAnalysis< chemistryType >, readFields, regionSizeDistribution, resolutionIndex, setFlow, streamLineBase, surfaceDistance, surfaceInterpolate, turbulenceFields, valueAverage, wallHeatFlux, wallShearStress, writeCellCentres, writeCellVolumes, XiReactionRate, yPlus, zeroGradient, forceCoeffs, forces, propellerInfo, hydrostaticPressure, cloudInfo, dataCloud, dsmcFields, icoUncoupledKinematicCloud, vtkCloud, phaseForces, sizeDistribution, energySpectrum, electricPotential, energyTransport, scalarTransport, abort, areaWrite, codedFunctionObject, ensightWrite, multiRegion, parProfiling, removeRegisteredObject, runTimeControl, setTimeStepFunctionObject, solverInfo, syncObjects, systemCall, thermoCoupleProbes, timeActivatedFileUpdate, timeInfo, vtkWrite, writeDictionary, writeObjects, functionObject::unavailableFunctionObject, timeControl, setTimeStepFaRegionsFunctionObject, filmFlux, patchProbes, probes, sampledSets, sampledSurfaces, sixDoFRigidBodyState, BilgerMixtureFraction, specieReactionRates< ChemistryModelType >, and moleFractions< ThermoType >.
execute() [2/2]
bool execute (const label subIndex) virtual
Reimplemented in externalCoupled, and timeControl.
Definition at line 179 of file functionObject.C.
write()
virtual bool write () pure virtual
Implemented in ObukhovLength, pointHistory, writeFreeSurface, age, AMIWeights, binField, blendingFactor, columnAverage, comfort, components, continuityError, Curle, ddt2, derivedFields, DESModelRegions, div, DMD, fvExpressionField, externalCoupled, extractEulerianParticles, fieldAverage, fieldExpression, fieldExtents, fieldMinMax, fieldsExpression, fieldValue, surfaceFieldValue, volFieldValue, fluxSummary, histogram, interfaceHeight, limitFields, mapFields, momentum, momentumError, multiFieldValue, nearWallFields, particleDistribution, processorField, proudmanAcousticPower, reactionsSensitivityAnalysis< chemistryType >, readFields, regionSizeDistribution, resolutionIndex, setFlow, stabilityBlendingFactor, streamLineBase, surfaceDistance, surfaceInterpolate, turbulenceFields, valueAverage, wallHeatFlux, wallShearStress, writeCellCentres, writeCellVolumes, XiReactionRate, yPlus, zeroGradient, forceCoeffs, forces, propellerInfo, hydrostaticPressure, cloudInfo, dataCloud, dsmcFields, icoUncoupledKinematicCloud, vtkCloud, phaseForces, sizeDistribution, energySpectrum, electricPotential, energyTransport, scalarTransport, abort, areaWrite, codedFunctionObject, ensightWrite, multiRegion, parProfiling, removeRegisteredObject, runTimeControl, setTimeStepFunctionObject, solverInfo, syncObjects, systemCall, thermoCoupleProbes, timeActivatedFileUpdate, timeInfo, vtkWrite, writeDictionary, writeObjects, functionObject::unavailableFunctionObject, timeControl, setTimeStepFaRegionsFunctionObject, filmFlux, patchProbes, probes, sampledSets, sampledSurfaces, sixDoFRigidBodyState, BilgerMixtureFraction, specieReactionRates< ChemistryModelType >, and moleFractions< ThermoType >.
end()
bool end () virtual
Reimplemented in DMD, externalCoupled, interfaceHeight, abort, codedFunctionObject, ensightWrite, parProfiling, systemCall, vtkWrite, and timeControl.
Definition at line 185 of file functionObject.C.
Referenced by nearWallFields::calcAddressing(), and externalCoupled::end().
adjustTimeStep()
bool adjustTimeStep () virtual
Reimplemented in setTimeStepFunctionObject, timeControl, and setTimeStepFaRegionsFunctionObject.
Definition at line 191 of file functionObject.C.
filesModified()
bool filesModified () const virtual
Reimplemented in timeActivatedFileUpdate, and timeControl.
Definition at line 197 of file functionObject.C.
updateMesh()
void updateMesh (const mapPolyMesh & mpm) virtual
Reimplemented in momentum, streamLineBase, probes, sampledSets, ObukhovLength, binField, derivedFields, surfaceFieldValue, processorField, areaWrite, ensightWrite, vtkWrite, timeControl, and sampledSurfaces.
Definition at line 203 of file functionObject.C.
movePoints()
void movePoints (const polyMesh & mesh) virtual
Reimplemented in momentum, streamLineBase, probes, sampledSets, ObukhovLength, derivedFields, binField, surfaceFieldValue, propellerInfo, areaWrite, vtkWrite, timeControl, sampledSurfaces, and ensightWrite.
Definition at line 207 of file functionObject.C.
Member Data Documentation
log
bool log
Definition at line 358 of file functionObject.H.
debug
int debug static
Definition at line 364 of file functionObject.H.
Referenced by nearWallFields::calcAddressing(), patchProbes::findElements(), and fieldExpression::foundObject().
postProcess
bool postProcess static
Definition at line 367 of file functionObject.H.
Referenced by readFields::execute(), and runTimeControl::read().
defaultUseNamePrefix
bool defaultUseNamePrefix static
Definition at line 370 of file functionObject.H.
Referenced by functionObjectList::read().
outputPrefix
Foam::word outputPrefix static
Definition at line 373 of file functionObject.H.
Referenced by writeFile::baseFileDir(), CloudFunctionObject< CloudType >::CloudFunctionObject(), if(), averageNeighbourFvGeometryScheme::movePoints(), dynamicFvMesh::New(), dataCloud::read(), vtkCloud::read(), ensightWrite::read(), vtkWrite::read(), shortestPathSet::shortestPathSet(), and streamLineBase::writeToFile().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/functionObjects/functionObject/functionObject.H
src/OpenFOAM/db/functionObjects/functionObject/functionObject.C