OpenFOAM: optMeshMovement Class Reference
optMeshMovement Class Reference abstract
Abstract base class for translating an update of the design variables into mesh movement.
#include <optMeshMovement.H>
Public Member Functions
TypeName ("optMeshMovement")
declareRunTimeSelectionTable (autoPtr, optMeshMovement, dictionary,(fvMesh &mesh, const dictionary &dict, const labelList &patchIDs),(mesh, dict, patchIDs))
optMeshMovement (fvMesh &mesh, const dictionary &dict, const labelList &patchIDs)
virtual ~optMeshMovement ()=default
void setCorrection (const scalarField &correction)
virtual void moveMesh ()
autoPtr< displacementMethod > & returnDisplacementMethod ()
const labelList & getPatchIDs ()
void writeMeshQualityMetrics ()
virtual void storeDesignVariables ()
virtual void resetDesignVariables ()
virtual scalar computeEta (const scalarField &correction)=0
bool maxAllowedDisplacementSet () const
virtual labelList getActiveDesignVariables () const
Static Public Member Functions
static autoPtr< optMeshMovement > New (fvMesh &mesh, const dictionary &dict, const labelList &patchIDs)
Protected Member Functions
scalar getMaxAllowedDisplacement () const
Protected Attributes
fvMesh & mesh_
const dictionary & dict_
scalarField correction_
labelList patchIDs_
vectorField pointsInit_
autoPtr< displacementMethod > displMethodPtr_
bool writeMeshQualityMetrics_
Detailed Description
Abstract base class for translating an update of the design variables into mesh movement.
Source files
optMeshMovement.H
optMeshMovement.C
Definition at line 50 of file optMeshMovement.H.
Constructor & Destructor Documentation
optMeshMovement()
optMeshMovement (fvMesh & mesh, const dictionary & dict, const labelList & patchIDs)
Definition at line 53 of file optMeshMovement.C.
References dict, and autoPtr< T >::reset().
~optMeshMovement()
virtual ~optMeshMovement () virtual default
Member Function Documentation
getMaxAllowedDisplacement()
Foam::scalar getMaxAllowedDisplacement () const protected
Definition at line 38 of file optMeshMovement.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and Foam::nl.
TypeName()
TypeName ("optMeshMovement")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , optMeshMovement , dictionary , (fvMesh &mesh, const dictionary &dict, const labelList &patchIDs) , (mesh, dict, patchIDs))
New()
Foam::autoPtr< Foam::optMeshMovement > New (fvMesh & mesh, const dictionary & dict, const labelList & patchIDs) static
Definition at line 85 of file optMeshMovement.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), Foam::Info, mesh, and patchIDs().
Referenced by shapeOptimisation::shapeOptimisation().
setCorrection()
void setCorrection (const scalarField & correction)
Definition at line 115 of file optMeshMovement.C.
References Foam::correction().
moveMesh()
void moveMesh () virtual
Reimplemented in optMeshMovementBezier, optMeshMovementNULL, optMeshMovementVolumetricBSplines, and optMeshMovementVolumetricBSplinesExternalMotionSolver.
Definition at line 121 of file optMeshMovement.C.
Referenced by optMeshMovementBezier::moveMesh(), optMeshMovementVolumetricBSplines::moveMesh(), and optMeshMovementVolumetricBSplinesExternalMotionSolver::moveMesh().
returnDisplacementMethod()
Foam::autoPtr< Foam::displacementMethod > & returnDisplacementMethod ()
Definition at line 135 of file optMeshMovement.C.
getPatchIDs()
const Foam::labelList & getPatchIDs ()
Definition at line 141 of file optMeshMovement.C.
writeMeshQualityMetrics()
void writeMeshQualityMetrics ()
Definition at line 147 of file optMeshMovement.C.
References Foam::dimless, Foam::endl(), Foam::gAverage(), Foam::gMax(), and Foam::Info.
storeDesignVariables()
void storeDesignVariables () virtual
Reimplemented in optMeshMovementVolumetricBSplines.
Definition at line 175 of file optMeshMovement.C.
Referenced by optMeshMovementVolumetricBSplines::storeDesignVariables().
resetDesignVariables()
void resetDesignVariables () virtual
Reimplemented in optMeshMovementVolumetricBSplines.
Definition at line 181 of file optMeshMovement.C.
References Foam::endl(), and Foam::Info.
Referenced by optMeshMovementVolumetricBSplines::resetDesignVariables().
computeEta()
virtual scalar computeEta (const scalarField & correction) pure virtual
Implemented in optMeshMovementBezier, optMeshMovementNULL, optMeshMovementVolumetricBSplines, and optMeshMovementVolumetricBSplinesExternalMotionSolver.
maxAllowedDisplacementSet()
bool maxAllowedDisplacementSet () const
Definition at line 188 of file optMeshMovement.C.
getActiveDesignVariables()
Foam::labelList getActiveDesignVariables () const virtual
Reimplemented in optMeshMovementBezier, optMeshMovementVolumetricBSplines, and optMeshMovementVolumetricBSplinesExternalMotionSolver.
Definition at line 194 of file optMeshMovement.C.
References NotImplemented.
Member Data Documentation
mesh_
fvMesh& mesh_ protected
Definition at line 73 of file optMeshMovement.H.
dict_
const dictionary& dict_ protected
Definition at line 74 of file optMeshMovement.H.
correction_
scalarField correction_ protected
Definition at line 77 of file optMeshMovement.H.
patchIDs_
labelList patchIDs_ protected
Definition at line 80 of file optMeshMovement.H.
Referenced by optMeshMovementVolumetricBSplinesExternalMotionSolver::computeBoundaryMovement().
pointsInit_
vectorField pointsInit_ protected
Definition at line 83 of file optMeshMovement.H.
displMethodPtr_
autoPtr<displacementMethod> displMethodPtr_ protected
Definition at line 87 of file optMeshMovement.H.
Referenced by optMeshMovementVolumetricBSplines::controlPointMovement().
writeMeshQualityMetrics_
bool writeMeshQualityMetrics_ protected
Definition at line 91 of file optMeshMovement.H.
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/optimisation/optMeshMovement/optMeshMovement/optMeshMovement.H
src/optimisation/adjointOptimisation/adjoint/optimisation/optMeshMovement/optMeshMovement/optMeshMovement.C