OpenFOAM: mappedPatchBase Class Reference
mappedPatchBase Class Reference
Determines a mapping between patch face centres and mesh cell or face centres and processors they're on.
#include <mappedPatchBase.H>
Classes
class maxProcEqOp
class nearestEqOp
class nearestWorldEqOp
Public Types
enum sampleMode {
NEARESTCELL , NEARESTPATCHFACE , NEARESTPATCHFACEAMI , NEARESTPATCHPOINT ,
NEARESTFACE , NEARESTONLYCELL
}
enum offsetMode { UNIFORM , NONUNIFORM , NORMAL }
typedef Tuple2< pointIndexHit, Tuple2< scalar, label > > nearInfo
typedef Tuple2< nearInfo, label > nearInfoWorld
Public Member Functions
TypeName ("mappedPatchBase")
mappedPatchBase (const polyPatch &)
mappedPatchBase (const polyPatch &pp, const word &sampleRegion, const sampleMode sampleMode, const word &samplePatch, const vectorField &offsets)
mappedPatchBase (const polyPatch &pp, const word &sampleRegion, const sampleMode sampleMode, const word &samplePatch, const vector &uniformOffset)
mappedPatchBase (const polyPatch &pp, const word &sampleRegion, const sampleMode sampleMode, const word &samplePatch, const scalar normalDistance)
mappedPatchBase (const polyPatch &, const dictionary &)
mappedPatchBase (const polyPatch &, const sampleMode, const dictionary &)
mappedPatchBase (const polyPatch &, const mappedPatchBase &)
mappedPatchBase (const polyPatch &, const mappedPatchBase &, const labelUList &mapAddressing)
virtual ~mappedPatchBase ()
void clearOut ()
void setOffset (const scalar normalDist)
void setOffset (const vector &uniformOffset)
void setOffset (const vectorField &offsets)
sampleMode mode () const noexcept
const word & sampleWorld () const noexcept
const word & sampleRegion () const
const word & samplePatch () const
const word & coupleGroup () const
label sampleSize () const
const vector & offset () const noexcept
const vectorField & offsets () const noexcept
label getCommunicator () const
label comm () const
bool sameWorld () const
bool masterWorld () const
bool sameRegion () const noexcept
uniformDimensionedScalarField & updateSampleMeshTime () const
uniformDimensionedScalarField & updateMeshTime () const
bool upToDate () const
const mapDistribute & map () const
const AMIPatchToPatchInterpolation & AMI (const bool forceUpdate=false) const
bool owner () const
const autoPtr< Foam::searchableSurface > & surfPtr () const
const polyMesh & sampleMesh () const
const polyPatch & samplePolyPatch () const
tmp< pointField > samplePoints () const
const fileName & sampleDatabasePath () const
bool sampleDatabase () const
virtual fileName sendPath (const label proci) const
virtual fileName receivePath (const label proci) const
template<class Type >
void distribute (List< Type > &lst) const
template<class Type , class CombineOp >
void distribute (List< Type > &lst, const CombineOp &cop) const
template<class Type >
void reverseDistribute (List< Type > &lst) const
template<class Type , class CombineOp >
void reverseDistribute (List< Type > &lst, const CombineOp &cop) const
virtual void write (Ostream &os) const
Static Public Member Functions
static pointIndexHit facePoint (const polyMesh &, const label facei, const polyMesh::cellDecomposition)
static fileName sendPath (const fileName &root, const label proci)
static fileName receivePath (const fileName &root, const label proci)
static const objectRegistry & subRegistry (const objectRegistry &obr, const fileName &path)
template<class Type >
static void storeField (objectRegistry &obr, const word &fieldName, const Field< Type > &values)
static void writeDict (const objectRegistry &obr, dictionary &dict)
static void readDict (const dictionary &d, objectRegistry &obr)
Static Public Attributes
static const Enum< sampleMode > sampleModeNames_
static const Enum< offsetMode > offsetModeNames_
Protected Member Functions
bool addWorldConnection ()
label getWorldCommunicator () const
const polyMesh & lookupMesh (const word &region) const
const polyPatch & lookupPatch (const word &sampleRegion, const word &samplePatch) const
tmp< pointField > facePoints (const polyPatch &) const
void collectSamples (const label mySampleWorld, const pointField &facePoints, pointField &samples, labelList &patchFaceWorlds, labelList &patchFaceProcs, labelList &patchFaces, pointField &patchFc) const
void findLocalSamples (const sampleMode mode, const label sampleWorld, const word &sampleRegion, const word &samplePatch, const pointField &samplePoints, List< nearInfoWorld > &nearest) const
void findSamples (const sampleMode mode, const label myWorldIndex, const pointField &, const labelList &wantedWorlds, const labelList &origProcs, labelList &sampleProcs, labelList &sampleIndices, pointField &sampleLocations) const
tmp< pointField > samplePoints (const pointField &) const
void calcMapping () const
void calcAMI () const
Static Protected Member Functions
static autoPtr< fileName > readDatabase (const dictionary &dict)
static const objectRegistry & subRegistry (const objectRegistry &obr, const wordList &names, const label index)
template<class Type >
static bool writeIOField (const regIOobject &obj, dictionary &dict)
template<class Type >
static bool constructIOField (const word &name, token &tok, Istream &is, objectRegistry &obr)
Protected Attributes
const polyPatch & patch_
word sampleWorld_
word sampleRegion_
const sampleMode mode_
word samplePatch_
const coupleGroupIdentifier coupleGroup_
const autoPtr< fileName > sampleDatabasePtr_
offsetMode offsetMode_
vector offset_
vectorField offsets_
scalar distance_
label communicator_
bool sameRegion_
autoPtr< mapDistribute > mapPtr_
const bool AMIReverse_
autoPtr< AMIPatchToPatchInterpolation > AMIPtr_
autoPtr< searchableSurface > surfPtr_
dictionary surfDict_
autoPtr< uniformDimensionedScalarField > updateMeshTimePtr_
autoPtr< uniformDimensionedScalarField > updateSampleMeshTimePtr_
Detailed Description
Determines a mapping between patch face centres and mesh cell or face centres and processors they're on.
If constructed from dictionary:
    // Optional world to sample (default is all)
    //sampleWorld solidSim;
    // Optional explicit coupling (requires functionObject to synchronise
    // databases. Default is close coupling (bc to bc)
    //sampleDatabase true;
    // Region to sample (default is region0)
    sampleRegion region0;
    // What to sample:
    // - nearestCell         : sample cell containing point
    // - nearestOnlyCell     : nearest sample cell (even if not containing
    //                         point)
    // - nearestPatchFace    : nearest face on selected patch
    // - nearestPatchFaceAMI : nearest face on selected patch
                               - patches need not conform
                               - uses AMI interpolation
    // - nearestFace         : nearest boundary face on any patch
    // - nearestPatchPoint   : nearest patch point (for coupled points
    //                         this might be any of the points so you have
    //                         to guarantee the point data is synchronised
    //                         beforehand)
    sampleMode nearestCell;
    // If sampleMode is nearestPatchFace : patch to find faces of
    samplePatch movingWall;
    // If sampleMode is nearestPatchFace : specify patchgroup to find
    // samplePatch and sampleRegion (if not provided)
    coupleGroup baffleGroup;
    // How to supply offset (w.r.t. my patch face centres):
    // - uniform : single offset vector
    // - nonuniform : per-face offset vector
    // - normal : using supplied distance and face normal
    offsetMode uniform;
    // According to offsetMode (see above) supply one of
    // offset, offsets or distance
    offset  (1 0 0);
Note: if offsetMode is normal it uses outwards pointing normals. So supply a negative distance if sampling inside the domain.
Note
Storage is not optimal. It temporary collects all (patch)face centres on all processors to keep the addressing calculation simple.
Source files
mappedPatchBase.H
mappedPatchBase.C
Definition at line 109 of file mappedPatchBase.H.
Member Typedef Documentation
nearInfo
typedef Tuple2<pointIndexHit, Tuple2<scalar, label> > nearInfo
Definition at line 144 of file mappedPatchBase.H.
nearInfoWorld
typedef Tuple2<nearInfo, label> nearInfoWorld
Definition at line 189 of file mappedPatchBase.H.
Member Enumeration Documentation
sampleMode
enum sampleMode
Enumerator
NEARESTCELL
nearest cell containing sample
NEARESTPATCHFACE
nearest face on selected patch
NEARESTPATCHFACEAMI
nearest patch face + AMI interpolation
NEARESTPATCHPOINT
nearest point on selected patch
NEARESTFACE
nearest face
NEARESTONLYCELL
nearest cell (even if not containing cell)
Definition at line 116 of file mappedPatchBase.H.
offsetMode
enum offsetMode
Enumerator
UNIFORM
single offset vector
NONUNIFORM
per-face offset vector
NORMAL
use face normal + distance
Definition at line 127 of file mappedPatchBase.H.
Constructor & Destructor Documentation
mappedPatchBase() [1/8]
mappedPatchBase (const polyPatch & pp) explicit
Definition at line 1202 of file mappedPatchBase.C.
mappedPatchBase() [2/8]
mappedPatchBase (const polyPatch & pp, const word & sampleRegion, const sampleMode sampleMode, const word & samplePatch, const vectorField & offsets)
Definition at line 1227 of file mappedPatchBase.C.
References mappedPatchBase::offsets(), and mappedPatchBase::setOffset().
mappedPatchBase() [3/8]
mappedPatchBase (const polyPatch & pp, const word & sampleRegion, const sampleMode sampleMode, const word & samplePatch, const vector & uniformOffset)
Definition at line 1249 of file mappedPatchBase.C.
References mappedPatchBase::setOffset().
mappedPatchBase() [4/8]
mappedPatchBase (const polyPatch & pp, const word & sampleRegion, const sampleMode sampleMode, const word & samplePatch, const scalar normalDistance)
Definition at line 1271 of file mappedPatchBase.C.
References mappedPatchBase::addWorldConnection().
mappedPatchBase() [5/8]
mappedPatchBase (const polyPatch & pp, const dictionary & dict)
Definition at line 1307 of file mappedPatchBase.C.
References mappedPatchBase::addWorldConnection(), mappedPatchBase::coupleGroup_, dict, mappedPatchBase::distance_, Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, mappedPatchBase::mode_, mappedPatchBase::NEARESTPATCHFACE, mappedPatchBase::NEARESTPATCHFACEAMI, mappedPatchBase::NONUNIFORM, mappedPatchBase::NORMAL, mappedPatchBase::offset_, mappedPatchBase::offsetMode_, mappedPatchBase::offsetModeNames_, mappedPatchBase::offsets_, mappedPatchBase::patch_, mappedPatchBase::sameRegion_, mappedPatchBase::sampleRegion_, mappedPatchBase::sampleWorld_, UPtrList< T >::size(), and mappedPatchBase::UNIFORM.
mappedPatchBase() [6/8]
mappedPatchBase (const polyPatch & pp, const sampleMode mode, const dictionary & dict)
Definition at line 1409 of file mappedPatchBase.C.
References mappedPatchBase::addWorldConnection(), mappedPatchBase::coupleGroup_, dict, Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, mappedPatchBase::mode(), mappedPatchBase::NEARESTPATCHFACE, mappedPatchBase::NEARESTPATCHFACEAMI, mappedPatchBase::patch_, mappedPatchBase::sameRegion_, mappedPatchBase::sampleModeNames_, mappedPatchBase::sampleRegion_, and mappedPatchBase::sampleWorld_.
mappedPatchBase() [7/8]
mappedPatchBase (const polyPatch & pp, const mappedPatchBase & mpb)
Definition at line 1482 of file mappedPatchBase.C.
mappedPatchBase() [8/8]
mappedPatchBase (const polyPatch & pp, const mappedPatchBase & mpb, const labelUList & mapAddressing)
Definition at line 1514 of file mappedPatchBase.C.
~mappedPatchBase()
~mappedPatchBase () virtual
Definition at line 1554 of file mappedPatchBase.C.
Member Function Documentation
addWorldConnection()
bool addWorldConnection () protected
Definition at line 110 of file mappedPatchBase.C.
References multiWorldConnections::New(), runTime, and objectRegistry::time().
Referenced by mappedPatchBase::mappedPatchBase(), mappedPatchBase::mappedPatchBase(), and mappedPatchBase::mappedPatchBase().
getWorldCommunicator()
Foam::label getWorldCommunicator () const protected
Definition at line 125 of file mappedPatchBase.C.
References UPstream::commWorld(), multiWorldConnections::New(), runTime, and objectRegistry::time().
lookupMesh()
const Foam::polyMesh & lookupMesh (const word & region) const protected
Definition at line 1600 of file mappedPatchBase.C.
lookupPatch()
const Foam::polyPatch & lookupPatch (const word & sampleRegion, const word & samplePatch) const protected
Definition at line 1615 of file mappedPatchBase.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
Referenced by mappedPolyPatch::nbrCells(), mappedWallPolyPatch::nbrCells(), mappedPolyPatch::neighbPolyPatchID(), mappedWallPolyPatch::neighbPolyPatchID(), mappedPolyPatch::newInternalProcFaces(), and mappedWallPolyPatch::newInternalProcFaces().
facePoints()
Foam::tmp< Foam::pointField > facePoints (const polyPatch & pp) const protected
Definition at line 138 of file mappedPatchBase.C.
References polyMesh::FACE_DIAG_TRIS, Foam::facePoint(), forAll, mesh, tmp< T >::New(), pp(), and polyMesh::tetBasePtIs().
collectSamples()
void collectSamples (const label mySampleWorld, const pointField & facePoints, pointField & samples, labelList & patchFaceWorlds, labelList & patchFaceProcs, labelList & patchFaces, pointField & patchFc) const protected
Definition at line 166 of file mappedPatchBase.C.
References Pstream::allGatherList(), UPstream::commWarn(), DebugInFunction, Foam::endl(), forAll, Foam::identity(), UPstream::msgType(), UPstream::myProcNo(), OSstream::name(), Foam::nl, UPstream::nProcs(), Foam::Perr, PtrList< T >::resize(), samples(), and UList< T >::size().
findLocalSamples()
void findLocalSamples (const sampleMode mode, const label sampleWorld, const word & sampleRegion, const word & samplePatch, const pointField & samplePoints, List< nearInfoWorld > & nearest) const protected
Definition at line 263 of file mappedPatchBase.C.
References Foam::abort(), primitiveMesh::cellCentres(), polyMesh::cellTree(), DebugInFunction, e, Foam::exit(), treeBoundBox::extend(), primitiveMesh::faceCentres(), Foam::FatalError, FatalErrorInFunction, UPtrList< T >::first(), forAll, mesh, PrimitivePatch< FaceList, PointField >::meshPoints(), Foam::mode(), UPstream::myProcNo(), MeshObject< polyMesh, GeometricMeshObject, meshSearchMeshObject >::New(), Foam::nl, polyMesh::points(), PrimitivePatch< FaceList, PointField >::points(), pp(), rndGen, samples(), PtrList< T >::setSize(), UList< T >::size(), Foam::sqr(), and tree().
findSamples()
void findSamples (const sampleMode mode, const label myWorldIndex, const pointField & samples, const labelList & wantedWorlds, const labelList & origProcs, labelList & sampleProcs, labelList & sampleIndices, pointField & sampleLocations) const protected
Definition at line 563 of file mappedPatchBase.C.
References Pstream::allGatherList(), PtrList< T >::append(), UPstream::commWarn(), DebugInFunction, Foam::endl(), UPtrList< T >::first(), forAll, Pstream::listCombineReduce(), VectorSpace< Form, Cmpt, Ncmpts >::max, Foam::mode(), UPstream::msgType(), UPstream::myProcNo(), Foam::nl, UPstream::nProcs(), Foam::Pout, samples(), PtrList< T >::setSize(), UPtrList< T >::size(), UList< T >::size(), and Foam::sqr().
samplePoints() [1/2]
Foam::tmp< Foam::pointField > samplePoints (const pointField & fc) const protected
Definition at line 1668 of file mappedPatchBase.C.
References fld(), Foam::mag(), n, and tmp< T >::New().
calcMapping()
void calcMapping () const protected
Definition at line 709 of file mappedPatchBase.C.
References Foam::abort(), UPstream::allWorlds(), PtrList< T >::append(), DebugInFunction, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::gAverage(), Foam::mag(), UPstream::master(), UPstream::msgType(), UPstream::myWorld(), UPstream::myWorldID(), OFstream::name(), IOstream::name(), Foam::nl, Foam::Pout, Foam::reduce(), samples(), HashSet< Key, Hash >::set(), UPtrList< T >::size(), HashSet< Key, Hash >::test(), Foam::type(), WarningInFunction, and Foam::meshTools::writeOBJ().
calcAMI()
void calcAMI () const protected
Definition at line 1081 of file mappedPatchBase.C.
References UPstream::commWarn(), UPstream::commWorld(), DebugInFunction, Foam::endl(), Foam::nl, os(), UPtrList< T >::size(), and Foam::meshTools::writeOBJ().
readDatabase()
Foam::autoPtr< Foam::fileName > readDatabase (const dictionary & dict) static protected
Definition at line 82 of file mappedPatchBase.C.
References dict, autoPtr< T >::New(), and fileName::null.
subRegistry() [1/2]
const Foam::objectRegistry & subRegistry (const objectRegistry & obr, const wordList & names, const label index) static protected
Definition at line 1181 of file mappedPatchBase.C.
References UList< T >::size(), and objectRegistry::subRegistry().
Referenced by mappedPatchFieldBase< scalar >::mappedPatchFieldBase(), mappedPatchFieldBase< Type >::retrieveField(), mappedPatchFieldBase< Type >::storeField(), and syncObjects::sync().
writeIOField()
template<class Type > bool writeIOField (const regIOobject & obj, dictionary & dict) static protected
Definition at line 241 of file mappedPatchBaseTemplates.C.
References dict, fld(), and dictionary::set().
constructIOField()
template<class Type > bool constructIOField (const word & name, token & tok, Istream & is, objectRegistry & obr) static protected
Definition at line 276 of file mappedPatchBaseTemplates.C.
References Foam::dynamicCast(), objectRegistry::getObjectPtr(), Foam::name(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, IOobjectOption::REGISTER, regIOobject::store(), and PtrList< T >::transfer().
TypeName()
TypeName ("mappedPatchBase")
clearOut()
void clearOut ()
Definition at line 1560 of file mappedPatchBase.C.
Referenced by mappedFieldFvPatchField< Type >::autoMap(), mappedMixedFieldFvPatchField< Type >::autoMap(), thermalBaffle1DFvPatchScalarField< solidType >::autoMap(), mappedPolyPatch::calcGeometry(), mappedWallPolyPatch::calcGeometry(), mappedPolyPatch::movePoints(), mappedWallPolyPatch::movePoints(), mappedFieldFvPatchField< Type >::rmap(), mappedMixedFieldFvPatchField< Type >::rmap(), mappedPolyPatch::updateMesh(), mappedWallPolyPatch::updateMesh(), mappedPolyPatch::~mappedPolyPatch(), and mappedWallPolyPatch::~mappedWallPolyPatch().
setOffset() [1/3]
void setOffset (const scalar normalDist)
Definition at line 1570 of file mappedPatchBase.C.
References PtrList< T >::clear(), and Foam::Zero.
Referenced by mappedPatchBase::mappedPatchBase(), and mappedPatchBase::mappedPatchBase().
setOffset() [2/3]
void setOffset (const vector & uniformOffset)
Definition at line 1580 of file mappedPatchBase.C.
References PtrList< T >::clear(), and Foam::Zero.
setOffset() [3/3]
void setOffset (const vectorField & offsets)
Definition at line 1590 of file mappedPatchBase.C.
References Foam::Zero.
mode()
Foam::mappedPatchBase::sampleMode mode () const inline noexcept
Definition at line 23 of file mappedPatchBaseI.H.
References mappedPatchBase::mode_.
Referenced by mappedPatchBase::mappedPatchBase(), and Sampled< Type >::Sampled().
sampleWorld()
const Foam::word & sampleWorld () const inline noexcept
Definition at line 29 of file mappedPatchBaseI.H.
sampleRegion()
const Foam::word & sampleRegion () const inline
Definition at line 35 of file mappedPatchBaseI.H.
References Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
samplePatch()
const Foam::word & samplePatch () const inline
Definition at line 61 of file mappedPatchBaseI.H.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and Foam::nl.
coupleGroup()
const Foam::word & coupleGroup () const inline
Definition at line 87 of file mappedPatchBaseI.H.
sampleSize()
Foam::label sampleSize () const inline
Definition at line 93 of file mappedPatchBaseI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, mesh, primitiveMesh::nBoundaryFaces(), and UPtrList< T >::size().
offset()
const Foam::vector & offset () const inline noexcept
Definition at line 128 of file mappedPatchBaseI.H.
offsets()
const Foam::vectorField & offsets () const inline noexcept
Definition at line 134 of file mappedPatchBaseI.H.
Referenced by mappedPatchBase::mappedPatchBase().
getCommunicator()
Foam::label getCommunicator () const inline
Definition at line 140 of file mappedPatchBaseI.H.
Referenced by mappedPatchBase::distribute().
comm()
Foam::label comm () const inline
Definition at line 151 of file mappedPatchBaseI.H.
sameWorld()
bool sameWorld () const inline
Definition at line 162 of file mappedPatchBaseI.H.
References UPstream::allWorlds(), UPtrList< T >::empty(), and UPstream::myWorld().
Referenced by mappedPatchBase::distribute().
masterWorld()
bool masterWorld () const inline
Definition at line 173 of file mappedPatchBaseI.H.
References UPstream::allWorlds(), and UPstream::myWorldID().
Referenced by mappedPatchBase::distribute().
sameRegion()
bool sameRegion () const inline noexcept
Definition at line 186 of file mappedPatchBaseI.H.
updateSampleMeshTime()
Foam::uniformDimensionedScalarField & updateSampleMeshTime () const inline
Definition at line 193 of file mappedPatchBaseI.H.
References mesh, IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, polyMesh::pointsInstance(), and fvMesh::thisDb().
updateMeshTime()
Foam::uniformDimensionedScalarField & updateMeshTime () const inline
Definition at line 221 of file mappedPatchBaseI.H.
References polyMesh::boundaryMesh(), mesh, IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, polyMesh::pointsInstance(), and fvMesh::thisDb().
upToDate()
bool upToDate () const inline
Definition at line 248 of file mappedPatchBaseI.H.
map()
const Foam::mapDistribute & map () const inline
Definition at line 267 of file mappedPatchBaseI.H.
Referenced by mappedPatchBase::distribute(), mappedPolyPatch::mapCollocatedFaces(), mappedWallPolyPatch::mapCollocatedFaces(), semiPermeableBaffleMassFractionFvPatchScalarField::phiY(), and thermalBaffle1DFvPatchScalarField< solidType >::updateCoeffs().
AMI()
const Foam::AMIPatchToPatchInterpolation & AMI (const bool forceUpdate = false) const inline
Definition at line 288 of file mappedPatchBaseI.H.
Referenced by mappedPatchBase::distribute().
owner()
bool owner () const inline
Definition at line 310 of file mappedPatchBaseI.H.
Referenced by mappedPolyPatch::masterImplicit(), and mappedWallPolyPatch::masterImplicit().
surfPtr()
const Foam::autoPtr< Foam::searchableSurface > & surfPtr () const
Definition at line 1049 of file mappedPatchBase.C.
References polyMesh::boundaryMesh(), mesh, IOobjectOption::MUST_READ, searchableSurface::New(), IOobjectOption::NO_WRITE, and fvMesh::time().
sampleMesh()
const Foam::polyMesh & sampleMesh () const
Definition at line 1636 of file mappedPatchBase.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and UPstream::myWorld().
samplePolyPatch()
const Foam::polyPatch & samplePolyPatch () const
Definition at line 1649 of file mappedPatchBase.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
samplePoints() [2/2]
Foam::tmp< Foam::pointField > samplePoints () const
Definition at line 1703 of file mappedPatchBase.C.
facePoint()
Foam::pointIndexHit facePoint (const polyMesh & mesh, const label facei, const polyMesh::cellDecomposition decompMode) static
Definition at line 1709 of file mappedPatchBase.C.
References Foam::abort(), polyMesh::CELL_TETS, primitiveMesh::cellCentres(), f(), polyMesh::FACE_CENTRE_TRIS, polyMesh::FACE_DIAG_TRIS, polyMesh::FACE_PLANES, primitiveMesh::faceCentres(), polyMesh::faceOwner(), polyMesh::faces(), Foam::FatalError, FatalErrorInFunction, UList< T >::fcIndex(), intersection::HALF_RAY, triangle< Point, PointRef >::intersection(), mesh, p, polyMesh::points(), UList< T >::size(), and polyMesh::tetBasePtIs().
Referenced by nearWallFields::calcAddressing().
sampleDatabasePath()
const fileName & sampleDatabasePath () const inline
Definition at line 575 of file mappedPatchBase.H.
References mappedPatchBase::sampleDatabasePtr_.
sampleDatabase()
bool sampleDatabase () const inline
Definition at line 580 of file mappedPatchBase.H.
References mappedPatchBase::sampleDatabasePtr_.
sendPath() [1/2]
Foam::fileName sendPath (const fileName & root, const label proci) static
Definition at line 1814 of file mappedPatchBase.C.
References Foam::name().
Referenced by syncObjects::sync().
sendPath() [2/2]
Foam::fileName sendPath (const label proci) const virtual
Definition at line 1825 of file mappedPatchBase.C.
receivePath() [1/2]
Foam::fileName receivePath (const fileName & root, const label proci) static
Definition at line 1831 of file mappedPatchBase.C.
References Foam::name().
Referenced by syncObjects::sync().
receivePath() [2/2]
Foam::fileName receivePath (const label proci) const virtual
Definition at line 1842 of file mappedPatchBase.C.
subRegistry() [2/2]
const Foam::objectRegistry & subRegistry (const objectRegistry & obr, const fileName & path) static
Definition at line 1790 of file mappedPatchBase.C.
References UList< T >::empty(), and path().
storeField()
template<class Type > void storeField (objectRegistry & obr, const word & fieldName, const Field< Type > & values) static
Definition at line 332 of file mappedPatchBaseTemplates.C.
References objectRegistry::getObjectPtr(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, IOobjectOption::REGISTER, and regIOobject::store().
Referenced by mappedPatchFieldBase< Type >::storeField().
writeDict()
void writeDict (const objectRegistry & obr, dictionary & dict) static
Definition at line 1848 of file mappedPatchBase.C.
References dictionary::add(), dict, forAllIters, os(), and dictionary::subDictOrAdd().
Referenced by syncObjects::sync().
readDict()
void readDict (const dictionary & d, objectRegistry & obr) static
Definition at line 1888 of file mappedPatchBase.C.
References e, Foam::exit(), Foam::FatalError, FatalErrorInFunction, and objectRegistry::subRegistry().
Referenced by syncObjects::sync().
distribute() [1/2]
template<class Type > void distribute (List< Type > & lst) const
Definition at line 23 of file mappedPatchBaseTemplates.C.
References mappedPatchBase::AMI(), UPstream::commWarn(), UPstream::commWorld(), mappedPatchBase::getCommunicator(), mappedPatchBase::map(), mappedPatchBase::masterWorld(), mappedPatchBase::mode_, mappedPatchBase::NEARESTPATCHFACEAMI, and mappedPatchBase::sameWorld().
distribute() [2/2]
template<class Type , class CombineOp > void distribute (List< Type > & lst, const CombineOp & cop) const
Definition at line 100 of file mappedPatchBaseTemplates.C.
References UPstream::commWarn(), UPstream::commWorld(), UPstream::defaultCommsType, mapDistributeBase::distribute(), UPstream::msgType(), and Foam::Zero.
reverseDistribute() [1/2]
template<class Type > void reverseDistribute (List< Type > & lst) const
Definition at line 152 of file mappedPatchBaseTemplates.C.
References UPstream::commWarn(), and UPstream::commWorld().
reverseDistribute() [2/2]
template<class Type , class CombineOp > void reverseDistribute (List< Type > & lst, const CombineOp & cop) const
Definition at line 186 of file mappedPatchBaseTemplates.C.
References UPstream::commWarn(), UPstream::commWorld(), UPstream::defaultCommsType, mapDistributeBase::distribute(), UPstream::msgType(), and Foam::Zero.
write()
void write (Ostream & os) const virtual
Reimplemented in mappedFieldFvPatchField< Type >, mappedMixedFieldFvPatchField< Type >, mappedPolyPatch, mappedVariableThicknessWallPolyPatch, mappedWallPolyPatch, semiPermeableBaffleMassFractionFvPatchScalarField, and thermalBaffle1DFvPatchScalarField< solidType >.
Definition at line 1929 of file mappedPatchBase.C.
References Switch::name(), fileName::null, word::null, os(), Ostream::write(), Ostream::writeEntry(), Ostream::writeEntryIfDifferent(), and VectorSpace< Form, Cmpt, Ncmpts >::zero.
Referenced by mappedFieldFvPatchField< Type >::write(), mappedMixedFieldFvPatchField< Type >::write(), mappedPolyPatch::write(), mappedWallPolyPatch::write(), semiPermeableBaffleMassFractionFvPatchScalarField::write(), thermalBaffle1DFvPatchScalarField< solidType >::write(), and Sampled< Type >::writeData().
Member Data Documentation
sampleModeNames_
const Foam::Enum< Foam::mappedPatchBase::sampleMode > sampleModeNames_ static
Definition at line 134 of file mappedPatchBase.H.
Referenced by mappedPatchBase::mappedPatchBase(), mappedPatchFieldBase< Type >::mappedPatchFieldBase(), and mappedFixedInternalValueFvPatchField< Type >::updateCoeffs().
offsetModeNames_
const Foam::Enum< Foam::mappedPatchBase::offsetMode > offsetModeNames_ static
Definition at line 136 of file mappedPatchBase.H.
Referenced by mappedPatchBase::mappedPatchBase(), and sampledPatchInternalField::sampledPatchInternalField().
patch_
const polyPatch& patch_ protected
Definition at line 223 of file mappedPatchBase.H.
Referenced by Sampled< Type >::haveSampleField(), mappedPolyPatch::mapCollocatedFaces(), mappedWallPolyPatch::mapCollocatedFaces(), mappedPatchBase::mappedPatchBase(), mappedPatchBase::mappedPatchBase(), mappedPolyPatch::newInternalProcFaces(), mappedWallPolyPatch::newInternalProcFaces(), Sampled< Type >::sampleField(), and Sampled< Type >::value().
sampleWorld_
word sampleWorld_ mutable protected
Definition at line 226 of file mappedPatchBase.H.
Referenced by mappedPatchBase::mappedPatchBase(), and mappedPatchBase::mappedPatchBase().
sampleRegion_
word sampleRegion_ mutable protected
Definition at line 229 of file mappedPatchBase.H.
Referenced by mappedPatchBase::mappedPatchBase(), mappedPatchBase::mappedPatchBase(), mappedPolyPatch::nbrCells(), mappedWallPolyPatch::nbrCells(), mappedPolyPatch::neighbPolyPatchID(), mappedWallPolyPatch::neighbPolyPatchID(), mappedPolyPatch::neighbRegionID(), mappedWallPolyPatch::neighbRegionID(), mappedPolyPatch::newInternalProcFaces(), and mappedWallPolyPatch::newInternalProcFaces().
mode_
const sampleMode mode_ protected
Definition at line 232 of file mappedPatchBase.H.
Referenced by mappedPatchBase::distribute(), mappedPatchBase::mappedPatchBase(), and mappedPatchBase::mode().
samplePatch_
word samplePatch_ mutable protected
Definition at line 235 of file mappedPatchBase.H.
Referenced by mappedPolyPatch::nbrCells(), mappedWallPolyPatch::nbrCells(), mappedPolyPatch::neighbPolyPatchID(), mappedWallPolyPatch::neighbPolyPatchID(), mappedPolyPatch::newInternalProcFaces(), and mappedWallPolyPatch::newInternalProcFaces().
coupleGroup_
const coupleGroupIdentifier coupleGroup_ protected
Definition at line 238 of file mappedPatchBase.H.
Referenced by mappedPatchBase::mappedPatchBase(), and mappedPatchBase::mappedPatchBase().
sampleDatabasePtr_
const autoPtr<fileName> sampleDatabasePtr_ protected
Definition at line 241 of file mappedPatchBase.H.
Referenced by mappedPatchBase::sampleDatabase(), and mappedPatchBase::sampleDatabasePath().
offsetMode_
offsetMode offsetMode_ protected
Definition at line 244 of file mappedPatchBase.H.
Referenced by mappedPatchBase::mappedPatchBase().
offset_
vector offset_ protected
Definition at line 247 of file mappedPatchBase.H.
Referenced by mappedPatchBase::mappedPatchBase().
offsets_
vectorField offsets_ protected
Definition at line 250 of file mappedPatchBase.H.
Referenced by mappedPatchBase::mappedPatchBase().
distance_
scalar distance_ protected
Definition at line 253 of file mappedPatchBase.H.
Referenced by mappedPatchBase::mappedPatchBase().
communicator_
label communicator_ protected
Definition at line 256 of file mappedPatchBase.H.
sameRegion_
bool sameRegion_ mutable protected
Definition at line 259 of file mappedPatchBase.H.
Referenced by mappedPatchBase::mappedPatchBase(), and mappedPatchBase::mappedPatchBase().
mapPtr_
autoPtr<mapDistribute> mapPtr_ mutable protected
Definition at line 269 of file mappedPatchBase.H.
AMIReverse_
const bool AMIReverse_ protected
Definition at line 275 of file mappedPatchBase.H.
AMIPtr_
autoPtr<AMIPatchToPatchInterpolation> AMIPtr_ mutable protected
Definition at line 278 of file mappedPatchBase.H.
surfPtr_
autoPtr<searchableSurface> surfPtr_ mutable protected
Definition at line 281 of file mappedPatchBase.H.
surfDict_
dictionary surfDict_ protected
Definition at line 284 of file mappedPatchBase.H.
updateMeshTimePtr_
autoPtr<uniformDimensionedScalarField> updateMeshTimePtr_ mutable protected
Definition at line 290 of file mappedPatchBase.H.
updateSampleMeshTimePtr_
autoPtr<uniformDimensionedScalarField> updateSampleMeshTimePtr_ mutable protected
Definition at line 294 of file mappedPatchBase.H.
The documentation for this class was generated from the following files:
src/meshTools/mappedPatches/mappedPolyPatch/mappedPatchBase.H
src/meshTools/mappedPatches/mappedPolyPatch/mappedPatchBase.C
src/meshTools/mappedPatches/mappedPolyPatch/mappedPatchBaseI.H
src/meshTools/mappedPatches/mappedPolyPatch/mappedPatchBaseTemplates.C