OpenFOAM: cubic< Type > Class Template Reference
cubic< Type > Class Template Reference
Numerics » Finite volume numerical schemes » Surface interpolation schemes
Cubic interpolation scheme class derived from linear and returns linear weighting factors but also applies an explicit correction.
#include <cubic.H>
Public Member Functions
TypeName ("cubic")
cubic (const fvMesh &mesh)
cubic (const fvMesh &mesh, Istream &)
cubic (const fvMesh &mesh, const surfaceScalarField &, Istream &)
virtual bool corrected () const
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > &vf) const
Public Member Functions inherited from linear< Type >
TypeName ("linear")
linear (const fvMesh &mesh)
linear (const fvMesh &mesh, Istream &)
linear (const fvMesh &mesh, const surfaceScalarField &, Istream &)
tmp< surfaceScalarField > weights (const GeometricField< Type, fvPatchField, volMesh > &) const
linear (const Specie &sp, const scalar psi, const scalar rho0)
linear (const dictionary &dict)
linear (const word &name, const linear &)
autoPtr< linear > clone () const
scalar rho (scalar p, scalar T) const
scalar H (const scalar p, const scalar T) const
scalar Cp (scalar p, scalar T) const
scalar E (const scalar p, const scalar T) const
scalar Cv (scalar p, scalar T) const
scalar S (const scalar p, const scalar T) const
scalar psi (scalar p, scalar T) const
scalar Z (scalar p, scalar T) const
scalar CpMCv (scalar p, scalar T) const
void write (Ostream &os) const
void operator+= (const linear &)
void operator*= (const scalar)
Public Member Functions inherited from surfaceInterpolationScheme< Type >
TypeName ("surfaceInterpolationScheme")
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, Mesh,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, MeshFlux,(const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
surfaceInterpolationScheme (const fvMesh &mesh)
virtual ~surfaceInterpolationScheme ()=default
const fvMesh & mesh () const
virtual tmp< GeometricField< typename innerProduct< vector, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf) const
tmp< GeometricField< typename innerProduct< vector, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const tmp< GeometricField< Type, fvPatchField, volMesh > > &) const
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &) const
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > &) const
template<class SFType >
Foam::tmp< Foam::GeometricField< typename Foam::innerProduct< typename SFType::value_type, Type >::type, Foam::fvsPatchField, Foam::surfaceMesh > > dotInterpolate (const SFType &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf, const tmp< surfaceScalarField > &tlambdas)
tmp< GeometricField< typename innerProduct< vector, scalar >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const GeometricField< scalar, fvPatchField, volMesh > &) const
Foam::tmp< Foam::GeometricField< typename Foam::innerProduct< Foam::vector, Foam::scalar >::type, Foam::fvsPatchField, Foam::surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const GeometricField< scalar, fvPatchField, volMesh > &) const
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Additional Inherited Members
Static Public Member Functions inherited from linear< Type >
static autoPtr< linear > New (const dictionary &dict)
static word typeName ()
Static Public Member Functions inherited from surfaceInterpolationScheme< Type >
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData)
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &, const tmp< surfaceScalarField > &)
template<class SFType >
static tmp< GeometricField< typename innerProduct< typename SFType::value_type, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const SFType &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf, const tmp< surfaceScalarField > &tlambdas)
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &)
Static Public Attributes inherited from linear< Type >
static const bool incompressible = false
static const bool isochoric = false
Detailed Description
template<class Type>
class Foam::cubic< Type >
Cubic interpolation scheme class derived from linear and returns linear weighting factors but also applies an explicit correction.
Source files
cubic.H
cubic.C
Definition at line 52 of file cubic.H.
Constructor & Destructor Documentation
cubic() [1/3]
template<class Type > cubic (const fvMesh & mesh) inline
Definition at line 74 of file cubic.H.
cubic() [2/3]
template<class Type > cubic (const fvMesh & mesh, Istream &) inline
Definition at line 80 of file cubic.H.
cubic() [3/3]
template<class Type > cubic (const fvMesh & mesh, const surfaceScalarField & , Istream &) inline
Definition at line 90 of file cubic.H.
Member Function Documentation
TypeName()
template<class Type > TypeName ("cubic< Type >")
corrected()
template<class Type > virtual bool corrected () const inline virtual
Reimplemented from surfaceInterpolationScheme< Type >.
Definition at line 104 of file cubic.H.
correction()
template<class Type > virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > & vf) const inline virtual
Reimplemented from surfaceInterpolationScheme< Type >.
Definition at line 111 of file cubic.H.
References coupled(), forAll, surfaceInterpolationScheme< Type >::interpolate(), lambda(), surfaceInterpolationScheme< Type >::mesh(), IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, Foam::sqr(), Foam::type(), and Foam::Zero.
The documentation for this class was generated from the following file:
src/finiteVolume/interpolation/surfaceInterpolation/schemes/cubic/cubic.H