OpenFOAM: token Class Reference
token Class Reference
A token holds an item read from Istream.
#include <token.H>
Classes
class compound
class Compound
Public Types
enum tokenType : char {
UNDEFINED = '\0' , ERROR = '\x80' , FLAG , PUNCTUATION ,
BOOL , LABEL , FLOAT , DOUBLE ,
WORD , STRING , COMPOUND , DIRECTIVE ,
EXPRESSION , VARIABLE , VERBATIM , FLOAT_SCALAR = FLOAT ,
DOUBLE_SCALAR = DOUBLE , VERBATIMSTRING = VERBATIM
}
enum flagType { NO_FLAG = 0 , ASCII = 1 , BINARY = 2 }
enum punctuationToken : char {
NULL_TOKEN = '\0' , TAB = '\t' , NL = '\n' , SPACE = ' ' ,
COLON = ':' , SEMICOLON = ';' , COMMA = ',' , HASH = '#' ,
DOLLAR = '$' , QUESTION = '?' , ATSYM = '@' , SQUOTE = '\'' ,
DQUOTE = '"' , ASSIGN = '=' , PLUS = '+' , MINUS = '-' ,
MULTIPLY = '*' , DIVIDE = '/' , LPAREN = '(' , RPAREN = ')' ,
LSQUARE = '[' , RSQUARE = ']' , LBRACE = '{' , RBRACE = '}' ,
ADD = PLUS , SUBTRACT = MINUS , END_STATEMENT = SEMICOLON , BEGIN_LIST = LPAREN ,
END_LIST = RPAREN , BEGIN_SQR = LSQUARE , END_SQR = RSQUARE , BEGIN_BLOCK = LBRACE ,
END_BLOCK = RBRACE , BEGIN_STRING = DQUOTE , END_STRING = DQUOTE
}
Public Member Functions
constexpr token () noexcept
token (const token &t)
token (token &&t) noexcept
token (punctuationToken p, label lineNum=0) noexcept
token (const label val, label lineNum=0) noexcept
token (const float val, label lineNum=0) noexcept
token (const double val, label lineNum=0) noexcept
token (const word &w, label lineNum=0)
token (const string &str, label lineNum=0)
token (word &&w, label lineNum=0)
token (string &&str, label lineNum=0)
token (token::compound *ptr, label lineNum=0)
token (Istream &is)
~token ()
word name () const
tokenType type () const noexcept
bool setType (const tokenType tokType) noexcept
label lineNumber () const noexcept
label lineNumber (const label lineNum) noexcept
bool good () const noexcept
bool undefined () const noexcept
bool error () const noexcept
bool isBool () const noexcept
bool isFlag () const noexcept
bool isPunctuation () const noexcept
bool isPunctuation (const punctuationToken p) const noexcept
bool isSeparator () const noexcept
bool isLabel () const noexcept
bool isLabel (const label val) const noexcept
bool isFloat () const noexcept
bool isDouble () const noexcept
bool isScalar () const noexcept
bool isNumber () const noexcept
bool isWord () const noexcept
bool isWord (const std::string &s) const
bool isDirective () const noexcept
bool isQuotedString () const noexcept
bool isString () const noexcept
bool isExpression () const noexcept
bool isVariable () const noexcept
bool isVerbatim () const noexcept
bool isStringType () const noexcept
bool isCompound () const noexcept
bool boolToken () const
int flagToken () const
punctuationToken pToken () const
label labelToken () const
float floatToken () const
double doubleToken () const
scalar scalarToken () const
scalar number () const
const word & wordToken () const
const string & stringToken () const
const compound & compoundToken () const
compound & transferCompoundToken ()
compound & transferCompoundToken (const Istream &is)
void reset ()
void setBad ()
void swap (token &tok)
InfoProxy< token > info () const noexcept
void operator= (const token &tok)
void operator= (token &&tok)
void operator= (const punctuationToken p)
void operator= (const label val)
void operator= (const float val)
void operator= (const double val)
void operator= (const word &w)
void operator= (const string &str)
void operator= (word &&w)
void operator= (string &&str)
void operator= (token::compound *ptr)
void operator= (autoPtr< token::compound > &&ptr)
bool operator== (const token &tok) const
bool operator== (const punctuationToken p) const noexcept
bool operator== (const label val) const noexcept
bool operator== (const float val) const noexcept
bool operator== (const double val) const noexcept
bool operator== (const std::string &s) const
bool operator!= (const token &tok) const
bool operator!= (const punctuationToken p) const noexcept
bool operator!= (const label val) const noexcept
bool operator!= (const float val) const noexcept
bool operator!= (const double val) const noexcept
bool operator!= (const std::string &s) const
label & lineNumber () noexcept
bool isFloatScalar () const
bool isDoubleScalar () const
float floatScalarToken () const
double doubleScalarToken () const
void operator= (word *)=delete
void operator= (string *)=delete
Static Public Member Functions
static token boolean (bool on) noexcept
static token flag (int bitmask) noexcept
static bool isseparator (int c) noexcept
Static Public Attributes
static const token undefinedToken
static constexpr const char *const typeName = "token"
Friends
Ostream & operator<< (Ostream &os, const token &tok)
Ostream & operator<< (Ostream &os, const punctuationToken &pt)
ostream & operator<< (ostream &os, const punctuationToken &pt)
ostream & operator<< (ostream &os, const InfoProxy< token > &ip)
Detailed Description
A token holds an item read from Istream.
Source files
token.H
tokenI.H
token.C
tokenIO.C
Definition at line 64 of file token.H.
Member Enumeration Documentation
tokenType
enum tokenType : char
Enumerator
UNDEFINED
An undefined token-type.
ERROR
Token error encountered.
FLAG
stream flag (1-byte bitmask)
PUNCTUATION
single character punctuation
BOOL
boolean type
LABEL
label (integer) type
FLOAT
float (single-precision) type
DOUBLE
double (double-precision) type
WORD
Foam::word.
STRING
Foam::string (usually double-quoted)
COMPOUND
Compound type such as List<label> etc.
DIRECTIVE
Word-variant: dictionary #directive stored with sigil
EXPRESSION
String-variant: math expression for evaluation stored with delimiters
VARIABLE
String-variant: dictionary $variable stored with sigil
VERBATIM
String-variant: verbatim string content stored without delimiters
FLOAT_SCALAR
DOUBLE_SCALAR
VERBATIMSTRING
Definition at line 72 of file token.H.
flagType
enum flagType
Enumerator
NO_FLAG
No flags.
ASCII
ASCII-mode stream.
BINARY
BINARY-mode stream.
Definition at line 107 of file token.H.
punctuationToken
enum punctuationToken : char
Enumerator
NULL_TOKEN
Nul character.
TAB
Tab [isspace].
NL
Newline [isspace].
SPACE
Space [isspace].
COLON
Colon [isseparator].
SEMICOLON
Semicolon [isseparator].
COMMA
Comma [isseparator].
HASH
Hash - directive or start verbatim string.
DOLLAR
Dollar - start variable or expression.
QUESTION
Question mark (eg, ternary)
ATSYM
The 'at' symbol.
SQUOTE
Single quote.
DQUOTE
Double quote.
ASSIGN
Assignment/equals [isseparator].
PLUS
Addition [isseparator].
MINUS
Subtract or start of negative number.
MULTIPLY
Multiply [isseparator].
DIVIDE
Divide [isseparator].
LPAREN
Left parenthesis [isseparator].
RPAREN
Right parenthesis [isseparator].
LSQUARE
Left square bracket [isseparator].
RSQUARE
Right square bracket [isseparator].
LBRACE
Left brace [isseparator].
RBRACE
Right brace [isseparator].
ADD
Addition [isseparator].
SUBTRACT
Subtract or start of negative number.
END_STATEMENT
End entry [isseparator].
BEGIN_LIST
Begin list [isseparator].
END_LIST
End list [isseparator].
BEGIN_SQR
Begin dimensions [isseparator].
END_SQR
End dimensions [isseparator].
BEGIN_BLOCK
Begin block [isseparator].
END_BLOCK
End block [isseparator].
BEGIN_STRING
Begin string with double quote.
END_STRING
End string with double quote.
Definition at line 116 of file token.H.
Constructor & Destructor Documentation
token() [1/13]
constexpr token () inline constexpr noexcept
Definition at line 90 of file tokenI.H.
token() [2/13]
token (const token & t) inline
Definition at line 98 of file tokenI.H.
References token::COMPOUND, token::DIRECTIVE, token::EXPRESSION, token::STRING, token::VARIABLE, token::VERBATIM, and token::WORD.
token() [3/13]
token (token && t) inline noexcept
Definition at line 139 of file tokenI.H.
token() [4/13]
token (punctuationToken p, label lineNum = 0) inline explicit noexcept
Definition at line 150 of file tokenI.H.
References p.
token() [5/13]
token (const label val, label lineNum = 0) inline explicit noexcept
Definition at line 160 of file tokenI.H.
token() [6/13]
token (const float val, label lineNum = 0) inline explicit noexcept
Definition at line 170 of file tokenI.H.
token() [7/13]
token (const double val, label lineNum = 0) inline explicit noexcept
Definition at line 180 of file tokenI.H.
token() [8/13]
token (const word & w, label lineNum = 0) inline explicit
Definition at line 190 of file tokenI.H.
token() [9/13]
token (const string & str, label lineNum = 0) inline explicit
Definition at line 200 of file tokenI.H.
token() [10/13]
token (word && w, label lineNum = 0) inline explicit
Definition at line 210 of file tokenI.H.
token() [11/13]
token (string && str, label lineNum = 0) inline explicit
Definition at line 220 of file tokenI.H.
token() [12/13]
token (token::compound * ptr, label lineNum = 0) inline explicit
Definition at line 230 of file tokenI.H.
token() [13/13]
token (Istream & is) explicit
Definition at line 117 of file tokenIO.C.
~token()
~token () inline
Definition at line 242 of file tokenI.H.
Member Function Documentation
boolean()
Foam::token boolean (bool on) inline static noexcept
Definition at line 26 of file tokenI.H.
flag()
Foam::token flag (int bitmask) inline static noexcept
Definition at line 36 of file tokenI.H.
isseparator()
bool isseparator (int c) inline static noexcept
Definition at line 46 of file tokenI.H.
name()
Foam::word name () const
Definition at line 127 of file tokenIO.C.
References token::BOOL, token::COMPOUND, token::DIRECTIVE, token::DOUBLE, token::ERROR, token::EXPRESSION, token::FLAG, token::FLOAT, token::LABEL, token::PUNCTUATION, token::STRING, token::UNDEFINED, token::VARIABLE, token::VERBATIM, and token::WORD.
type()
Foam::token::tokenType type () const inline noexcept
Definition at line 304 of file tokenI.H.
setType()
bool setType (const tokenType tokType) inline noexcept
Definition at line 310 of file tokenI.H.
Referenced by UIPstreamBase::read(), and ISstream::read().
lineNumber() [1/3]
Foam::label lineNumber () const inline noexcept
Definition at line 384 of file tokenI.H.
Referenced by UIPstreamBase::read(), and ISstream::read().
lineNumber() [2/3]
Foam::label lineNumber (const label lineNum) inline noexcept
Definition at line 390 of file tokenI.H.
good()
bool good () const inline noexcept
Definition at line 398 of file tokenI.H.
Referenced by Foam::operator>>(), Foam::operator>>(), Foam::operator>>(), Foam::operator>>(), Foam::operator>>(), Foam::operator>>(), and Foam::operator>>().
undefined()
bool undefined () const inline noexcept
Definition at line 404 of file tokenI.H.
error()
bool error () const inline noexcept
Definition at line 410 of file tokenI.H.
isBool()
bool isBool () const inline noexcept
Definition at line 416 of file tokenI.H.
isFlag()
bool isFlag () const inline noexcept
Definition at line 434 of file tokenI.H.
Referenced by UIPstreamBase::read().
isPunctuation() [1/2]
bool isPunctuation () const inline noexcept
Definition at line 452 of file tokenI.H.
Referenced by blockDescriptor::blockDescriptor(), Reaction< ThermoType >::New(), Foam::operator>>(), Foam::operator>>(), Foam::operator>>(), Foam::operator>>(), and Foam::operator>>().
isPunctuation() [2/2]
bool isPunctuation (const punctuationToken p) const inline noexcept
Definition at line 458 of file tokenI.H.
References p.
isSeparator()
bool isSeparator () const inline noexcept
Definition at line 468 of file tokenI.H.
isLabel() [1/2]
bool isLabel () const inline noexcept
Definition at line 490 of file tokenI.H.
Referenced by Foam::operator>>(), Foam::operator>>(), Foam::operator>>(), Foam::operator>>(), Foam::operator>>(), Foam::operator>>(), Foam::operator>>(), and Foam::blockMeshTools::read().
isLabel() [2/2]
bool isLabel (const label val) const inline noexcept
Definition at line 496 of file tokenI.H.
isFloat()
bool isFloat () const inline noexcept
Definition at line 518 of file tokenI.H.
Referenced by token::isFloatScalar().
isDouble()
bool isDouble () const inline noexcept
Definition at line 536 of file tokenI.H.
Referenced by token::isDoubleScalar().
isScalar()
bool isScalar () const inline noexcept
Definition at line 554 of file tokenI.H.
Referenced by Foam::operator>>(), Foam::operator>>(), Foam::operator>>(), and Foam::operator>>().
isNumber()
bool isNumber () const inline noexcept
Definition at line 580 of file tokenI.H.
Referenced by Foam::getLazyPair(), Foam::getRadius(), Foam::operator>>(), Foam::operator>>(), Foam::operator>>(), dimensionSet::read(), dimensionSet::read(), and Reaction< ReactionThermo >::specieCoeffs::specieCoeffs().
isWord() [1/2]
bool isWord () const inline noexcept
Definition at line 602 of file tokenI.H.
Referenced by blockDescriptor::blockDescriptor(), Foam::operator>>(), Foam::blockMeshTools::read(), and dimensionSet::read().
isWord() [2/2]
bool isWord (const std::string & s) const inline
Definition at line 612 of file tokenI.H.
References s().
isDirective()
bool isDirective () const inline noexcept
Definition at line 618 of file tokenI.H.
Referenced by ifeqEntry::evaluate(), and ifeqEntry::execute().
isQuotedString()
bool isQuotedString () const inline noexcept
Definition at line 640 of file tokenI.H.
isString()
bool isString () const inline noexcept
Definition at line 646 of file tokenI.H.
isExpression()
bool isExpression () const inline noexcept
Definition at line 658 of file tokenI.H.
isVariable()
bool isVariable () const inline noexcept
Definition at line 664 of file tokenI.H.
isVerbatim()
bool isVerbatim () const inline noexcept
Definition at line 670 of file tokenI.H.
isStringType()
bool isStringType () const inline noexcept
Definition at line 676 of file tokenI.H.
isCompound()
bool isCompound () const inline noexcept
Definition at line 709 of file tokenI.H.
boolToken()
bool boolToken () const inline
Definition at line 422 of file tokenI.H.
flagToken()
int flagToken () const inline
Definition at line 440 of file tokenI.H.
Referenced by UIPstreamBase::read().
pToken()
Foam::token::punctuationToken pToken () const inline
Definition at line 478 of file tokenI.H.
Referenced by blockDescriptor::blockDescriptor(), Foam::operator>>(), Foam::operator>>(), Foam::operator>>(), and Foam::operator>>().
labelToken()
Foam::label labelToken () const inline
Definition at line 506 of file tokenI.H.
Referenced by Foam::operator>>(), Foam::operator>>(), Foam::operator>>(), Foam::operator>>(), Foam::operator>>(), Foam::operator>>(), Foam::operator>>(), and Foam::blockMeshTools::read().
floatToken()
float floatToken () const inline
Definition at line 524 of file tokenI.H.
Referenced by token::floatScalarToken().
doubleToken()
double doubleToken () const inline
Definition at line 542 of file tokenI.H.
Referenced by token::doubleScalarToken().
scalarToken()
Foam::scalar scalarToken () const inline
Definition at line 564 of file tokenI.H.
Referenced by Foam::operator>>(), Foam::operator>>(), Foam::operator>>(), and Foam::operator>>().
number()
Foam::scalar number () const inline
Definition at line 586 of file tokenI.H.
Referenced by Foam::operator>>(), Foam::operator>>(), Foam::operator>>(), dimensionSet::read(), dimensionSet::read(), and Reaction< ReactionThermo >::specieCoeffs::specieCoeffs().
wordToken()
const Foam::word & wordToken () const inline
Definition at line 624 of file tokenI.H.
References word::null.
Referenced by blockDescriptor::blockDescriptor(), ifeqEntry::evaluate(), ifeqEntry::execute(), Foam::operator>>(), Reaction< ThermoType >::Reaction(), Foam::blockMeshTools::read(), and dimensionSet::read().
stringToken()
const Foam::string & stringToken () const inline
Definition at line 682 of file tokenI.H.
References string::null.
compoundToken()
const Foam::token::compound & compoundToken () const inline
Definition at line 715 of file tokenI.H.
transferCompoundToken() [1/2]
Foam::token::compound & transferCompoundToken ()
Definition at line 86 of file token.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
transferCompoundToken() [2/2]
Foam::token::compound & transferCompoundToken (const Istream & is)
Definition at line 108 of file token.C.
References Foam::abort(), Foam::FatalIOError, and FatalIOErrorInFunction.
reset()
void reset () inline
Definition at line 250 of file tokenI.H.
setBad()
void setBad () inline
Definition at line 727 of file tokenI.H.
Referenced by UIPstreamBase::read(), and ISstream::read().
swap()
void swap (token & tok) inline
Definition at line 291 of file tokenI.H.
info()
InfoProxy< token > info () const inline noexcept
Definition at line 583 of file token.H.
Referenced by blockDescriptor::blockDescriptor(), entry::New(), Foam::operator>>(), Foam::operator>>(), Foam::operator>>(), Foam::operator>>(), Foam::operator>>(), Foam::operator>>(), Foam::operator>>(), Foam::operator>>(), and Foam::blockMeshTools::read().
operator=() [1/14]
void operator= (const token & tok) inline
Definition at line 736 of file tokenI.H.
operator=() [2/14]
void operator= (token && tok) inline
Definition at line 784 of file tokenI.H.
operator=() [3/14]
void operator= (const punctuationToken p) inline
Definition at line 797 of file tokenI.H.
References p.
operator=() [4/14]
void operator= (const label val) inline
Definition at line 805 of file tokenI.H.
operator=() [5/14]
void operator= (const float val) inline
Definition at line 813 of file tokenI.H.
operator=() [6/14]
void operator= (const double val) inline
Definition at line 821 of file tokenI.H.
operator=() [7/14]
void operator= (const word & w) inline
Definition at line 829 of file tokenI.H.
operator=() [8/14]
void operator= (const string & str) inline
Definition at line 837 of file tokenI.H.
operator=() [9/14]
void operator= (word && w) inline
Definition at line 845 of file tokenI.H.
operator=() [10/14]
void operator= (string && str) inline
Definition at line 853 of file tokenI.H.
References s().
operator=() [11/14]
void operator= (token::compound * ptr) inline
Definition at line 861 of file tokenI.H.
operator=() [12/14]
void operator= (autoPtr< token::compound > && ptr) inline
Definition at line 869 of file tokenI.H.
operator==() [1/6]
bool operator== (const token & tok) const inline
Definition at line 877 of file tokenI.H.
References Foam::equal().
operator==() [2/6]
bool operator== (const punctuationToken p) const inline noexcept
Definition at line 928 of file tokenI.H.
References p.
operator==() [3/6]
bool operator== (const label val) const inline noexcept
Definition at line 945 of file tokenI.H.
operator==() [4/6]
bool operator== (const float val) const inline noexcept
Definition at line 951 of file tokenI.H.
References Foam::equal().
operator==() [5/6]
bool operator== (const double val) const inline noexcept
Definition at line 961 of file tokenI.H.
References Foam::equal().
operator==() [6/6]
bool operator== (const std::string & s) const inline
Definition at line 934 of file tokenI.H.
References s().
operator!=() [1/6]
bool operator!= (const token & tok) const inline
Definition at line 971 of file tokenI.H.
References Foam::operator==().
operator!=() [2/6]
bool operator!= (const punctuationToken p) const inline noexcept
Definition at line 977 of file tokenI.H.
References p.
operator!=() [3/6]
bool operator!= (const label val) const inline noexcept
Definition at line 983 of file tokenI.H.
References Foam::operator==().
operator!=() [4/6]
bool operator!= (const float val) const inline noexcept
Definition at line 989 of file tokenI.H.
References Foam::operator==().
operator!=() [5/6]
bool operator!= (const double val) const inline noexcept
Definition at line 995 of file tokenI.H.
References Foam::operator==().
operator!=() [6/6]
bool operator!= (const std::string & s) const inline
Definition at line 1001 of file tokenI.H.
References Foam::operator==(), and s().
lineNumber() [3/3]
label & lineNumber () inline noexcept
Definition at line 661 of file token.H.
isFloatScalar()
bool isFloatScalar () const inline
Definition at line 665 of file token.H.
References token::isFloat().
isDoubleScalar()
bool isDoubleScalar () const inline
Definition at line 669 of file token.H.
References token::isDouble().
floatScalarToken()
float floatScalarToken () const inline
Definition at line 673 of file token.H.
References token::floatToken().
doubleScalarToken()
double doubleScalarToken () const inline
Definition at line 677 of file token.H.
References token::doubleToken().
operator=() [13/14]
void operator= (word *) delete
operator=() [14/14]
void operator= (string *) delete
Friends And Related Symbol Documentation
operator<< [1/4]
Ostream & operator<< (Ostream & os, const token & tok) friend
operator<< [2/4]
Ostream & operator<< (Ostream & os, const punctuationToken & pt) friend
operator<< [3/4]
ostream & operator<< (ostream & os, const punctuationToken & pt) friend
operator<< [4/4]
ostream & operator<< (ostream & os, const InfoProxy< token > & ip) friend
Member Data Documentation
undefinedToken
const Foam::token undefinedToken static
Definition at line 290 of file token.H.
Referenced by Istream::peekBack().
typeName
constexpr const char* const typeName = "token" static constexpr
Definition at line 342 of file token.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOstreams/token/token.H
src/OpenFOAM/db/IOstreams/token/token.C
src/OpenFOAM/db/IOstreams/token/tokenI.H
src/OpenFOAM/db/IOstreams/token/tokenIO.C