OpenFOAM: accessor Class Reference
accessor Class Reference
glTF accessor
#include <foamGltfAccessor.H>
Public Member Functions
accessor ()
accessor (const word &name)
~accessor ()=default
label & bufferViewId () noexcept
label & byteOffset () noexcept
label & componentType () noexcept
label & count () noexcept
string & type () noexcept
template<class Type >
void set (const Field< Type > &fld, bool calcMinMax=true)
void write (Ostream &os) const
template<class Type >
Foam::string getValueType ()
template<class Type >
Foam::string toString (const Type &val)
Public Member Functions inherited from base
base ()
base (const word &name)
~base ()=default
label & id () noexcept
const word & name () const noexcept
void write (Ostream &os) const
void operator= (const base &gltf)
Static Protected Member Functions
template<class Type >
static string getValueType ()
template<class Type >
static string toString (const Type &val)
Protected Attributes
label bufferViewId_
label byteOffset_
label componentType_
label count_
string type_
string max_
string min_
bool minMax_
Protected Attributes inherited from base
word name_
label id_
Detailed Description
glTF accessor
Note
Implements the glTF v2 specification
Source files
foamGltfAccessor.H
foamGltfAccessor.C
foamGltfAccessorTemplates.C
Definition at line 62 of file foamGltfAccessor.H.
Constructor & Destructor Documentation
accessor() [1/2]
accessor ()
Definition at line 25 of file foamGltfAccessor.C.
accessor() [2/2]
accessor (const word & name) explicit
Definition at line 39 of file foamGltfAccessor.C.
~accessor()
~accessor () default
Member Function Documentation
getValueType() [1/2]
template<class Type > static string getValueType () static protected
toString() [1/2]
template<class Type > static string toString (const Type & val) static protected
Referenced by accessor::set().
bufferViewId()
Foam::label & bufferViewId () noexcept
Definition at line 55 of file foamGltfAccessor.C.
byteOffset()
Foam::label & byteOffset () noexcept
Definition at line 61 of file foamGltfAccessor.C.
componentType()
Foam::label & componentType () noexcept
Definition at line 67 of file foamGltfAccessor.C.
count()
Foam::label & count () noexcept
Definition at line 73 of file foamGltfAccessor.C.
type()
Foam::string & type () noexcept
Definition at line 79 of file foamGltfAccessor.C.
set()
template<class Type > void set (const Field< Type > & fld, bool calcMinMax = true)
Definition at line 79 of file foamGltfAccessorTemplates.C.
References fld(), Foam::glTF::FLOAT, Foam::glTF::key(), Foam::max(), maxValue, Foam::min(), minValue, UPtrList< T >::size(), and accessor::toString().
write()
void write (Ostream & os) const
Definition at line 85 of file foamGltfAccessor.C.
References Foam::indent(), Foam::nl, os(), and base::write().
getValueType() [2/2]
template<class Type > Foam::string getValueType ()
Definition at line 27 of file foamGltfAccessorTemplates.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
toString() [2/2]
template<class Type > Foam::string toString (const Type & val)
Definition at line 61 of file foamGltfAccessorTemplates.C.
References Foam::component(), and StringStreamAllocator< StreamType >::str().
Member Data Documentation
bufferViewId_
label bufferViewId_ protected
Definition at line 71 of file foamGltfAccessor.H.
byteOffset_
label byteOffset_ protected
Definition at line 74 of file foamGltfAccessor.H.
componentType_
label componentType_ protected
Definition at line 77 of file foamGltfAccessor.H.
count_
label count_ protected
Definition at line 80 of file foamGltfAccessor.H.
type_
string type_ protected
Definition at line 83 of file foamGltfAccessor.H.
max_
string max_ protected
Definition at line 86 of file foamGltfAccessor.H.
min_
string min_ protected
Definition at line 89 of file foamGltfAccessor.H.
minMax_
bool minMax_ protected
Definition at line 92 of file foamGltfAccessor.H.
The documentation for this class was generated from the following files:
src/fileFormats/gltf/foamGltfAccessor.H
src/fileFormats/gltf/foamGltfAccessor.C
src/fileFormats/gltf/foamGltfAccessorTemplates.C