OpenFOAM: laminarFlameSpeed Class Reference
laminarFlameSpeed Class Reference abstract
Abstract class for laminar flame speed.
#include <laminarFlameSpeed.H>
Public Member Functions
TypeName ("laminarFlameSpeed")
declareRunTimeSelectionTable (autoPtr, laminarFlameSpeed, dictionary,(const dictionary &dict, const psiuReactionThermo &ct),(dict, ct))
laminarFlameSpeed (const dictionary &, const psiuReactionThermo &)
virtual ~laminarFlameSpeed ()
virtual tmp< volScalarField > operator() () const =0
Static Public Member Functions
static autoPtr< laminarFlameSpeed > New (const psiuReactionThermo &)
Protected Attributes
const psiuReactionThermo & psiuReactionThermo_
word fuel_
scalar equivalenceRatio_
Detailed Description
Abstract class for laminar flame speed.
Source files
laminarFlameSpeed.H
laminarFlameSpeed.C
laminarFlameSpeedNew.C
Definition at line 57 of file laminarFlameSpeed.H.
Constructor & Destructor Documentation
laminarFlameSpeed()
laminarFlameSpeed (const dictionary & dict, const psiuReactionThermo & ct)
Definition at line 36 of file laminarFlameSpeed.C.
References dict, Foam::dimless, laminarFlameSpeed::equivalenceRatio_, laminarFlameSpeed::psiuReactionThermo_, and dimensioned< Type >::value().
~laminarFlameSpeed()
~laminarFlameSpeed () virtual
Definition at line 56 of file laminarFlameSpeed.C.
Member Function Documentation
TypeName()
TypeName ("laminarFlameSpeed")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , laminarFlameSpeed , dictionary , (const dictionary &dict, const psiuReactionThermo &ct) , (dict, ct))
New()
Foam::autoPtr< Foam::laminarFlameSpeed > New (const psiuReactionThermo & ct) static
Definition at line 26 of file laminarFlameSpeedNew.C.
References Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, UPtrList< T >::get(), Foam::Info, IOobjectOption::MUST_READ_IF_MODIFIED, IOobjectOption::NO_REGISTER, and IOobjectOption::NO_WRITE.
operator()()
virtual tmp< volScalarField > operator() () const pure virtual
Implemented in SCOPE, constant, Gulders, GuldersEGR, and RaviPetersen.
Member Data Documentation
psiuReactionThermo_
const psiuReactionThermo& psiuReactionThermo_ protected
Definition at line 64 of file laminarFlameSpeed.H.
Referenced by laminarFlameSpeed::laminarFlameSpeed().
fuel_
word fuel_ protected
Definition at line 67 of file laminarFlameSpeed.H.
equivalenceRatio_
scalar equivalenceRatio_ protected
Definition at line 70 of file laminarFlameSpeed.H.
Referenced by laminarFlameSpeed::laminarFlameSpeed().
The documentation for this class was generated from the following files:
src/thermophysicalModels/laminarFlameSpeed/laminarFlameSpeed/laminarFlameSpeed.H
src/thermophysicalModels/laminarFlameSpeed/laminarFlameSpeed/laminarFlameSpeed.C
src/thermophysicalModels/laminarFlameSpeed/laminarFlameSpeed/laminarFlameSpeedNew.C