OpenFOAM: sampledSurface Class Reference
sampledSurface Class Reference abstract
FunctionObjects » Utility function objects
An abstract class for surfaces with sampling.
#include <sampledSurface.H>
Classes
class iNew
class iNewCapture
Public Member Functions
TypeName ("sampledSurface")
declareRunTimeSelectionTable (autoPtr, sampledSurface, word,(const word &name, const polyMesh &mesh, const dictionary &dict),(name, mesh, dict))
sampledSurface (const word &name, const polyMesh &mesh, const bool interpolateToPoints=false)
sampledSurface (const word &name, const polyMesh &mesh, const dictionary &dict)
autoPtr< sampledSurface > clone () const
virtual ~sampledSurface ()
const polyMesh & mesh () const noexcept
const word & name () const noexcept
bool enabled () const noexcept
bool invariant () const noexcept
bool isPointData () const noexcept
virtual bool isPointData (const bool on)
virtual bool needsUpdate () const =0
virtual bool expire ()=0
virtual bool update ()=0
virtual const pointField & points () const =0
virtual const faceList & faces () const =0
virtual const vectorField & Sf () const =0
virtual const scalarField & magSf () const =0
virtual const vectorField & Cf () const =0
scalar area () const
virtual bool hasFaceIds () const
polySurface * getRegistrySurface (const objectRegistry &obr, word lookupName="") const
polySurface * storeRegistrySurface (objectRegistry &obr, word lookupName="") const
bool removeRegistrySurface (objectRegistry &obr, word lookupName="") const
template<class Type , class GeoMeshType >
bool storeRegistryField (const objectRegistry &obr, const word &fieldName, const dimensionSet &dims, const Field< Type > &values, word lookupName="") const
template<class Type , class GeoMeshType >
bool storeRegistryField (const objectRegistry &obr, const word &fieldName, const dimensionSet &dims, Field< Type > &&values, word lookupName="") const
virtual tmp< scalarField > sample (const interpolation< scalar > &sampler) const =0
virtual tmp< vectorField > sample (const interpolation< vector > &sampler) const =0
virtual tmp< sphericalTensorField > sample (const interpolation< sphericalTensor > &sampler) const =0
virtual tmp< symmTensorField > sample (const interpolation< symmTensor > &sampler) const =0
virtual tmp< tensorField > sample (const interpolation< tensor > &sampler) const =0
virtual bool withSurfaceFields () const
virtual tmp< scalarField > sample (const surfaceScalarField &sField) const
virtual tmp< vectorField > sample (const surfaceVectorField &sField) const
virtual tmp< sphericalTensorField > sample (const surfaceSphericalTensorField &sField) const
virtual tmp< symmTensorField > sample (const surfaceSymmTensorField &sField) const
virtual tmp< tensorField > sample (const surfaceTensorField &sField) const
virtual tmp< scalarField > interpolate (const interpolation< scalar > &interpolator) const =0
virtual tmp< vectorField > interpolate (const interpolation< vector > &interpolator) const =0
virtual tmp< sphericalTensorField > interpolate (const interpolation< sphericalTensor > &interpolator) const =0
virtual tmp< symmTensorField > interpolate (const interpolation< symmTensor > &interpolator) const =0
virtual tmp< tensorField > interpolate (const interpolation< tensor > &interpolator) const =0
virtual void rename (const word &newName)
virtual void print (Ostream &os, int level=0) const
bool interpolate () const noexcept
template<class Type >
Foam::tmp< Foam::Field< Type > > sampleOnFaces (const interpolation< Type > &sampler, const labelUList &elements, const faceList &fcs, const pointField &pts, const Type &defaultValue)
template<class Type >
Foam::tmp< Foam::Field< Type > > sampleOnPoints (const interpolation< Type > &interpolator, const labelUList &elements, const faceList &fcs, const pointField &pts)
template<class Type >
Foam::tmp< Foam::VolumeField< Type > > pointAverage (const PointField< Type > &pfld)
Public Member Functions inherited from meshedSurf
constexpr meshedSurf () noexcept=default
virtual ~meshedSurf ()=default
virtual const labelList & zoneIds () const
virtual const labelList & faceIds () const
Static Public Member Functions
static autoPtr< sampledSurface > New (const word &name, const polyMesh &mesh, const dictionary &dict)
Protected Member Functions
virtual void clearGeom () const
sampledSurface (const word &name, std::nullptr_t)
Static Protected Member Functions
template<class Type >
static tmp< Field< Type > > sampleOnFaces (const interpolation< Type > &sampler, const labelUList &elements, const faceList &fcs, const pointField &pts, const Type &defaultValue=Type(Zero))
template<class Type >
static tmp< Field< Type > > sampleOnPoints (const interpolation< Type > &interpolator, const labelUList &elements, const faceList &fcs, const pointField &pts)
template<class Type >
static tmp< VolumeField< Type > > pointAverage (const PointField< Type > &pfld)
Detailed Description
An abstract class for surfaces with sampling.
The constructors for the derived classes should generally start in a 'expired' condition (ie, needsUpdate() == true) and rely on a subsequent call to the update() method to complete the initialization. Delaying the final construction as late as possible allows the construction of surfaces that may depend on intermediate calculation results (eg, iso-surfaces) and also avoids the unnecessary reconstruction of surfaces between sampling intervals.
It is the responsibility of the caller to ensure that the surface update() is called before the surface is used. The update() method implementation should do nothing when the surface is already up-to-date.
Any sampler is assumed to work for the standard volume field types. Some may also support surface fields.
Dictionary entries:
Property Description Required Default
name Alternative name no
enabled Enable/disable the surface? no yes
interpolate Interpolate to nodes instead of faces no false
invariant Invariant with geometry change (use with caution!) no false
Note
The invariant switch is an advanced feature to declare that the surface is unaffected by changes in the general mesh geometry. For example, if sampling on a static patch while some other motion occurs elsewhere. If used improperly, there is a significant possibility for problems (caveat emptor).
Source files
sampledSurface.H
sampledSurface.C
sampledSurfaceTemplates.C
Definition at line 116 of file sampledSurface.H.
Constructor & Destructor Documentation
sampledSurface() [1/3]
sampledSurface (const word & name, std::nullptr_t) explicit protected
Definition at line 75 of file sampledSurface.C.
sampledSurface() [2/3]
sampledSurface (const word & name, const polyMesh & mesh, const bool interpolateToPoints = false)
Definition at line 86 of file sampledSurface.C.
sampledSurface() [3/3]
sampledSurface (const word & name, const polyMesh & mesh, const dictionary & dict)
Definition at line 102 of file sampledSurface.C.
~sampledSurface()
~sampledSurface () virtual
Definition at line 120 of file sampledSurface.C.
Member Function Documentation
sampleOnFaces() [1/2]
template<class Type > static tmp< Field< Type > > sampleOnFaces (const interpolation< Type > & sampler, const labelUList & elements, const faceList & fcs, const pointField & pts, const Type & defaultValue = Type(Zero)) static protected
Referenced by sampledDistanceSurface::sampleOnFaces(), sampledIsoSurface::sampleOnFaces(), sampledCuttingPlane::sampleOnFaces(), sampledCuttingSurface::sampleOnFaces(), sampledMeshedSurface::sampleOnFaces(), sampledPlane::sampleOnFaces(), sampledThresholdCellFaces::sampleOnFaces(), and sampledInterface::sampleOnFaces().
sampleOnPoints() [1/2]
template<class Type > static tmp< Field< Type > > sampleOnPoints (const interpolation< Type > & interpolator, const labelUList & elements, const faceList & fcs, const pointField & pts) static protected
Referenced by sampledDistanceSurface::sampleOnPoints(), sampledIsoSurface::sampleOnPoints(), sampledCuttingPlane::sampleOnPoints(), sampledCuttingSurface::sampleOnPoints(), sampledPlane::sampleOnPoints(), and sampledThresholdCellFaces::sampleOnPoints().
pointAverage() [1/2]
template<class Type > static tmp< VolumeField< Type > > pointAverage (const PointField< Type > & pfld) static protected
clearGeom()
void clearGeom () const protected virtual
Definition at line 36 of file sampledSurface.C.
Referenced by sampledIsoSurface::expire(), sampledCuttingPlane::expire(), sampledCuttingSurface::expire(), sampledFaceZone::expire(), sampledMeshedSurface::expire(), sampledPatch::expire(), sampledPlane::expire(), sampledCuttingSurface::update(), and sampledPlane::update().
TypeName()
TypeName ("sampledSurface")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , sampledSurface , word , (const word &name, const polyMesh &mesh, const dictionary &dict) , (name, mesh, dict))
clone()
autoPtr< sampledSurface > clone () const inline
Definition at line 274 of file sampledSurface.H.
References NotImplemented.
New()
Foam::autoPtr< Foam::sampledSurface > New (const word & name, const polyMesh & mesh, const dictionary & dict) static
Definition at line 44 of file sampledSurface.C.
References DebugInfo, dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), mesh, and Foam::name().
Referenced by sampledSurface::iNew::operator()(), sampledSurface::iNewCapture::operator()(), surfaceFieldValue::read(), sampledSurfaces::read(), sampledFaceZone::sampleOnFaces(), sampledMeshedSurface::sampleOnFaces(), sampledPatch::sampleOnFaces(), and sampledSurface::sampleOnFaces().
mesh()
const polyMesh & mesh () const inline noexcept
Definition at line 301 of file sampledSurface.H.
Referenced by sampledCuttingPlane::sampledCuttingPlane(), sampledInterface::sampledInterface(), sampledIsoSurface::sampledIsoSurface(), sampledPatchInternalField::sampledPatchInternalField(), sampledPlane::sampledPlane(), sampledPlane::sampledPlane(), sampledFaceZone::sampleOnFaces(), and sampledMeshedSurface::sampleOnFaces().
name()
const word & name () const inline noexcept
Definition at line 307 of file sampledSurface.H.
Referenced by sampledSurface::getRegistrySurface(), sampledSurface::iNew::operator()(), sampledSurface::iNewCapture::operator()(), and sampledPlane::sampledPlane().
enabled()
bool enabled () const inline noexcept
Definition at line 313 of file sampledSurface.H.
invariant()
bool invariant () const inline noexcept
Definition at line 319 of file sampledSurface.H.
isPointData() [1/2]
bool isPointData () const inline noexcept
Definition at line 325 of file sampledSurface.H.
isPointData() [2/2]
bool isPointData (const bool on) virtual
Definition at line 139 of file sampledSurface.C.
needsUpdate()
virtual bool needsUpdate () const pure virtual
Implemented in sampledDistanceSurface, sampledIsoSurface, sampledCuttingPlane, sampledCuttingSurface, sampledFaceZone, sampledMeshedSurface, sampledNone, sampledPatch, sampledPlane, sampledThresholdCellFaces, and sampledInterface.
expire()
virtual bool expire () pure virtual
Implemented in sampledDistanceSurface, sampledIsoSurface, sampledCuttingPlane, sampledCuttingSurface, sampledFaceZone, sampledMeshedSurface, sampledNone, sampledPatch, sampledPlane, sampledThresholdCellFaces, and sampledInterface.
update()
virtual bool update () pure virtual
Implemented in sampledDistanceSurface, sampledIsoSurface, sampledCuttingPlane, sampledCuttingSurface, sampledFaceZone, sampledMeshedSurface, sampledNone, sampledPatch, sampledPlane, sampledThresholdCellFaces, and sampledInterface.
points()
virtual const pointField & points () const pure virtual
Implements meshedSurf.
Implemented in sampledDistanceSurface, sampledIsoSurface, sampledCuttingPlane, sampledCuttingSurface, sampledFaceZone, sampledMeshedSurface, sampledNone, sampledPatch, sampledPlane, sampledThresholdCellFaces, and sampledInterface.
faces()
virtual const faceList & faces () const pure virtual
Implements meshedSurf.
Implemented in sampledDistanceSurface, sampledIsoSurface, sampledCuttingPlane, sampledCuttingSurface, sampledFaceZone, sampledMeshedSurface, sampledNone, sampledPatch, sampledPlane, sampledThresholdCellFaces, and sampledInterface.
Sf()
virtual const vectorField & Sf () const pure virtual
Implemented in sampledDistanceSurface, sampledIsoSurface, sampledCuttingPlane, sampledCuttingSurface, sampledFaceZone, sampledMeshedSurface, sampledNone, sampledPatch, sampledPlane, sampledThresholdCellFaces, and sampledInterface.
magSf()
virtual const scalarField & magSf () const pure virtual
Implemented in sampledDistanceSurface, sampledIsoSurface, sampledCuttingPlane, sampledCuttingSurface, sampledFaceZone, sampledMeshedSurface, sampledNone, sampledPatch, sampledPlane, sampledThresholdCellFaces, and sampledInterface.
Cf()
virtual const vectorField & Cf () const pure virtual
Implemented in sampledDistanceSurface, sampledIsoSurface, sampledCuttingPlane, sampledCuttingSurface, sampledFaceZone, sampledMeshedSurface, sampledNone, sampledPatch, sampledPlane, sampledThresholdCellFaces, and sampledInterface.
area()
Foam::scalar area () const
Definition at line 128 of file sampledSurface.C.
References Foam::gSum().
hasFaceIds()
virtual bool hasFaceIds () const inline virtual
Reimplemented in sampledMeshedSurface.
Definition at line 365 of file sampledSurface.H.
getRegistrySurface()
Foam::polySurface * getRegistrySurface (const objectRegistry & obr, word lookupName = "") const
Definition at line 26 of file sampledSurfaceRegister.C.
References UPtrList< T >::empty(), objectRegistry::getObjectPtr(), and sampledSurface::name().
storeRegistrySurface()
Foam::polySurface * storeRegistrySurface (objectRegistry & obr, word lookupName = "") const
Definition at line 41 of file sampledSurfaceRegister.C.
References UPtrList< T >::empty(), and Foam::name().
removeRegistrySurface()
bool removeRegistrySurface (objectRegistry & obr, word lookupName = "") const
Definition at line 66 of file sampledSurfaceRegister.C.
References objectRegistry::checkOut().
storeRegistryField() [1/2]
template<class Type , class GeoMeshType > bool storeRegistryField (const objectRegistry & obr, const word & fieldName, const dimensionSet & dims, const Field< Type > & values, word lookupName = "") const
Definition at line 174 of file sampledSurfaceTemplates.C.
storeRegistryField() [2/2]
template<class Type , class GeoMeshType > bool storeRegistryField (const objectRegistry & obr, const word & fieldName, const dimensionSet & dims, Field< Type > && values, word lookupName = "") const
Definition at line 198 of file sampledSurfaceTemplates.C.
sample() [1/10]
virtual tmp< scalarField > sample (const interpolation< scalar > & sampler) const pure virtual
Implemented in sampledDistanceSurface, sampledIsoSurface, sampledCuttingPlane, sampledCuttingSurface, sampledFaceZone, sampledMeshedSurface, sampledMeshedSurfaceNormal, sampledNone, sampledPatch, sampledPatchInternalField, sampledPlane, sampledThresholdCellFaces, and sampledInterface.
sample() [2/10]
virtual tmp< vectorField > sample (const interpolation< vector > & sampler) const pure virtual
Implemented in sampledDistanceSurface, sampledIsoSurface, sampledCuttingPlane, sampledCuttingSurface, sampledFaceZone, sampledMeshedSurface, sampledMeshedSurfaceNormal, sampledNone, sampledPatch, sampledPatchInternalField, sampledPlane, sampledThresholdCellFaces, and sampledInterface.
sample() [3/10]
virtual tmp< sphericalTensorField > sample (const interpolation< sphericalTensor > & sampler) const pure virtual
Implemented in sampledDistanceSurface, sampledIsoSurface, sampledCuttingPlane, sampledCuttingSurface, sampledFaceZone, sampledMeshedSurface, sampledMeshedSurfaceNormal, sampledNone, sampledPatch, sampledPatchInternalField, sampledPlane, sampledThresholdCellFaces, and sampledInterface.
sample() [4/10]
virtual tmp< symmTensorField > sample (const interpolation< symmTensor > & sampler) const pure virtual
Implemented in sampledDistanceSurface, sampledIsoSurface, sampledCuttingPlane, sampledCuttingSurface, sampledFaceZone, sampledMeshedSurface, sampledMeshedSurfaceNormal, sampledNone, sampledPatch, sampledPatchInternalField, sampledPlane, sampledThresholdCellFaces, and sampledInterface.
sample() [5/10]
virtual tmp< tensorField > sample (const interpolation< tensor > & sampler) const pure virtual
Implemented in sampledDistanceSurface, sampledIsoSurface, sampledCuttingPlane, sampledCuttingSurface, sampledFaceZone, sampledMeshedSurface, sampledMeshedSurfaceNormal, sampledNone, sampledPatch, sampledPatchInternalField, sampledPlane, sampledThresholdCellFaces, and sampledInterface.
withSurfaceFields()
bool withSurfaceFields () const virtual
Reimplemented in sampledFaceZone, and sampledPatch.
Definition at line 147 of file sampledSurface.C.
sample() [6/10]
Foam::tmp< Foam::scalarField > sample (const surfaceScalarField & sField) const virtual
Reimplemented in sampledFaceZone, and sampledPatch.
Definition at line 153 of file sampledSurface.C.
References NotImplemented.
sample() [7/10]
Foam::tmp< Foam::vectorField > sample (const surfaceVectorField & sField) const virtual
Reimplemented in sampledFaceZone, and sampledPatch.
Definition at line 163 of file sampledSurface.C.
References NotImplemented.
sample() [8/10]
Foam::tmp< Foam::tensorField > sample (const surfaceSphericalTensorField & sField) const virtual
Reimplemented in sampledFaceZone, sampledPatch, sampledFaceZone, sampledPatch, sampledFaceZone, and sampledPatch.
Definition at line 173 of file sampledSurface.C.
References NotImplemented.
sample() [9/10]
virtual tmp< symmTensorField > sample (const surfaceSymmTensorField & sField) const virtual
Reimplemented in sampledFaceZone, sampledPatch, sampledFaceZone, sampledPatch, sampledFaceZone, and sampledPatch.
sample() [10/10]
virtual tmp< tensorField > sample (const surfaceTensorField & sField) const virtual
Reimplemented in sampledFaceZone, sampledPatch, sampledFaceZone, sampledPatch, sampledFaceZone, and sampledPatch.
interpolate() [1/6]
virtual tmp< scalarField > interpolate (const interpolation< scalar > & interpolator) const pure virtual
Implemented in sampledDistanceSurface, sampledIsoSurface, sampledCuttingPlane, sampledCuttingSurface, sampledFaceZone, sampledMeshedSurface, sampledMeshedSurfaceNormal, sampledNone, sampledPatch, sampledPatchInternalField, sampledPlane, sampledThresholdCellFaces, and sampledInterface.
interpolate() [2/6]
virtual tmp< vectorField > interpolate (const interpolation< vector > & interpolator) const pure virtual
Implemented in sampledDistanceSurface, sampledIsoSurface, sampledCuttingPlane, sampledCuttingSurface, sampledFaceZone, sampledMeshedSurface, sampledMeshedSurfaceNormal, sampledNone, sampledPatch, sampledPatchInternalField, sampledPlane, sampledThresholdCellFaces, and sampledInterface.
interpolate() [3/6]
virtual tmp< sphericalTensorField > interpolate (const interpolation< sphericalTensor > & interpolator) const pure virtual
Implemented in sampledDistanceSurface, sampledIsoSurface, sampledCuttingPlane, sampledCuttingSurface, sampledFaceZone, sampledMeshedSurface, sampledMeshedSurfaceNormal, sampledNone, sampledPatch, sampledPatchInternalField, sampledPlane, sampledThresholdCellFaces, and sampledInterface.
interpolate() [4/6]
virtual tmp< symmTensorField > interpolate (const interpolation< symmTensor > & interpolator) const pure virtual
Implemented in sampledDistanceSurface, sampledIsoSurface, sampledCuttingPlane, sampledCuttingSurface, sampledFaceZone, sampledMeshedSurface, sampledMeshedSurfaceNormal, sampledNone, sampledPatch, sampledPatchInternalField, sampledPlane, sampledThresholdCellFaces, and sampledInterface.
interpolate() [5/6]
virtual tmp< tensorField > interpolate (const interpolation< tensor > & interpolator) const pure virtual
Implemented in sampledDistanceSurface, sampledIsoSurface, sampledCuttingPlane, sampledCuttingSurface, sampledFaceZone, sampledMeshedSurface, sampledMeshedSurfaceNormal, sampledNone, sampledPatch, sampledPatchInternalField, sampledPlane, sampledThresholdCellFaces, and sampledInterface.
rename()
virtual void rename (const word & newName) inline virtual
Definition at line 530 of file sampledSurface.H.
print()
void print (Ostream & os, int level = 0) const virtual
Reimplemented in sampledDistanceSurface, sampledIsoSurface, sampledCuttingPlane, sampledFaceZone, sampledMeshedSurface, sampledPatch, sampledPatchInternalField, sampledPlane, sampledThresholdCellFaces, and sampledInterface.
Definition at line 203 of file sampledSurface.C.
References os(), and Foam::type().
interpolate() [6/6]
bool interpolate () const inline noexcept
Definition at line 545 of file sampledSurface.H.
Referenced by sampledMeshedSurfaceNormal::interpolate().
sampleOnFaces() [2/2]
template<class Type > Foam::tmp< Foam::Field< Type > > sampleOnFaces (const interpolation< Type > & sampler, const labelUList & elements, const faceList & fcs, const pointField & pts, const Type & defaultValue)
Definition at line 28 of file sampledSurfaceTemplates.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, sampledSurface::New(), pts, UPtrList< T >::size(), and UList< T >::size().
sampleOnPoints() [2/2]
template<class Type > Foam::tmp< Foam::Field< Type > > sampleOnPoints (const interpolation< Type > & interpolator, const labelUList & elements, const faceList & fcs, const pointField & pts)
Definition at line 72 of file sampledSurfaceTemplates.C.
References Foam::exit(), f(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::New(), pts, PtrList< T >::set(), UPtrList< T >::size(), UList< T >::size(), and Foam::Zero.
pointAverage() [2/2]
template<class Type > Foam::tmp< Foam::VolumeField< Type > > pointAverage (const PointField< Type > & pfld)
Definition at line 122 of file sampledSurfaceTemplates.C.
References Foam::dimless, forAll, mesh, primitiveMesh::nCells(), Foam::New(), IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, primitiveMesh::nPoints(), primitiveMesh::pointCells(), fvMesh::time(), and Foam::Zero.
The documentation for this class was generated from the following files:
src/sampling/sampledSurface/sampledSurface/sampledSurface.H
src/sampling/sampledSurface/sampledSurface/sampledSurface.C
src/sampling/sampledSurface/sampledSurface/sampledSurfaceRegister.C
src/sampling/sampledSurface/sampledSurface/sampledSurfaceTemplates.C