OpenFOAM: pyrolysisChemistryModel< CompType, SolidThermo, GasThermo > Class Template Reference
pyrolysisChemistryModel< CompType, SolidThermo, GasThermo > Class Template Reference
Pyrolysis chemistry model. It includes gas phase in the solid reaction.
#include <pyrolysisChemistryModel.H>
Public Member Functions
TypeName ("pyrolysis")
pyrolysisChemistryModel (typename CompType::reactionThermo &thermo)
virtual ~pyrolysisChemistryModel ()
const PtrList< GasThermo > & gasThermo () const
const speciesTable & gasTable () const
label nSpecie () const
label nGases () const
virtual scalarField omega (const scalarField &c, const scalar T, const scalar p, const bool updateC0=false) const
virtual scalar omega (const Reaction< SolidThermo > &r, const scalarField &c, const scalar T, const scalar p, scalar &pf, scalar &cf, label &lRef, scalar &pr, scalar &cr, label &rRef) const
virtual scalar omegaI (label iReaction, const scalarField &c, const scalar T, const scalar p, scalar &pf, scalar &cf, label &lRef, scalar &pr, scalar &cr, label &rRef) const
virtual void calculate ()
const volScalarField::Internal & RRg (const label i) const
tmp< volScalarField::Internal > RRg () const
virtual tmp< volScalarField > gasHs (const volScalarField &p, const volScalarField &T, const label i) const
virtual scalar solve (const scalar deltaT)
virtual label nEqns () const
virtual void derivatives (const scalar t, const scalarField &c, scalarField &dcdt) const
virtual void jacobian (const scalar t, const scalarField &c, scalarField &dcdt, scalarSquareMatrix &dfdc) const
virtual void solve (scalarField &c, scalar &T, scalar &p, scalar &deltaT, scalar &subDeltaT) const
Public Member Functions inherited from solidChemistryModel< CompType, SolidThermo >
TypeName ("solidChemistryModel")
solidChemistryModel (typename CompType::reactionThermo &thermo)
virtual ~solidChemistryModel ()
const PtrList< Reaction< SolidThermo > > & reactions () const
label nReaction () const
const volScalarField::Internal & RRs (const label i) const
tmp< volScalarField::Internal > RRs () const
tmp< DimensionedField< scalar, volMesh > > RRsHs () const
virtual scalar solve (const scalarField &deltaT)
virtual tmp< volScalarField > tc () const
virtual tmp< volScalarField > Qdot () const
Public Member Functions inherited from ODESystem
ODESystem ()
virtual ~ODESystem ()=default
Protected Member Functions
PtrList< volScalarField::Internal > & RRg ()
void operator= (const pyrolysisChemistryModel &)=delete
Protected Member Functions inherited from solidChemistryModel< CompType, SolidThermo >
PtrList< volScalarField::Internal > & RRs ()
void setCellReacting (const label celli, const bool active)
Protected Attributes
speciesTable pyrolisisGases_
PtrList< GasThermo > gasThermo_
label nGases_
label nSpecie_
PtrList< volScalarField::Internal > RRg_
PtrList< volScalarField > Ys0_
Protected Attributes inherited from solidChemistryModel< CompType, SolidThermo >
PtrList< volScalarField > & Ys_
const PtrList< Reaction< SolidThermo > > & reactions_
const PtrList< SolidThermo > & solidThermo_
label nSolids_
label nReaction_
PtrList< volScalarField::Internal > RRs_
List< bool > reactingCells_
Detailed Description
template<class CompType, class SolidThermo, class GasThermo>
class Foam::pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >
Pyrolysis chemistry model. It includes gas phase in the solid reaction.
Source files
pyrolysisChemistryModel.H
pyrolysisChemistryModelI.H
pyrolysisChemistryModel.C
Definition at line 54 of file pyrolysisChemistryModel.H.
Constructor & Destructor Documentation
pyrolysisChemistryModel()
template<class CompType , class SolidThermo , class GasThermo > pyrolysisChemistryModel (typename CompType::reactionThermo & thermo)
Definition at line 29 of file pyrolysisChemistryModel.C.
References IOobjectOption::AUTO_WRITE, basicThermo::dictName, Foam::dimMass, Foam::dimTime, Foam::dimVolume, forAll, pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::gasThermo_, Foam::indent(), Foam::Info, Foam::max(), mesh, IOobjectOption::MUST_READ, Foam::name(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::nGases_, Foam::nl, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, solidChemistryModel< CompType, SolidThermo >::nSolids_, pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::pyrolisisGases_, solidChemistryModel< CompType, SolidThermo >::reactions_, solidThermo::rho(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::RRg_, solidChemistryModel< CompType, SolidThermo >::RRs_, PtrList< T >::set(), thermoDict, timeName, IOobject::typeHeaderOk(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::Ys0_, solidChemistryModel< CompType, SolidThermo >::Ys_, and Foam::Zero.
~pyrolysisChemistryModel()
template<class CompType , class SolidThermo , class GasThermo > ~pyrolysisChemistryModel () virtual
Definition at line 166 of file pyrolysisChemistryModel.C.
Member Function Documentation
RRg() [1/3]
template<class CompType , class SolidThermo , class GasThermo > Foam::PtrList< Foam::DimensionedField< Foam::scalar, Foam::volMesh > > & RRg () inline protected
Definition at line 28 of file pyrolysisChemistryModelI.H.
operator=()
template<class CompType , class SolidThermo , class GasThermo > void operator= (const pyrolysisChemistryModel< CompType, SolidThermo, GasThermo > &) protected delete
TypeName()
template<class CompType , class SolidThermo , class GasThermo > TypeName ("pyrolysis")
gasThermo()
template<class CompType , class SolidThermo , class GasThermo > const Foam::PtrList< GasThermo > & gasThermo () const inline
Definition at line 36 of file pyrolysisChemistryModelI.H.
gasTable()
template<class CompType , class SolidThermo , class GasThermo > const Foam::speciesTable & gasTable () const inline
Definition at line 45 of file pyrolysisChemistryModelI.H.
nSpecie()
template<class CompType , class SolidThermo , class GasThermo > Foam::label nSpecie () const inline
Definition at line 54 of file pyrolysisChemistryModelI.H.
nGases()
template<class CompType , class SolidThermo , class GasThermo > label nGases () const inline
omega() [1/2]
template<class CompType , class SolidThermo , class GasThermo > Foam::scalarField omega (const scalarField & c, const scalar T, const scalar p, const bool updateC0 = false) const virtual
Implements solidChemistryModel< CompType, SolidThermo >.
Definition at line 175 of file pyrolysisChemistryModel.C.
References forAll, g, om, p, R, s(), T, and Foam::Zero.
omega() [2/2]
template<class CompType , class SolidThermo , class GasThermo > Foam::scalar omega (const Reaction< SolidThermo > & r, const scalarField & c, const scalar T, const scalar p, scalar & pf, scalar & cf, label & lRef, scalar & pr, scalar & cr, label & rRef) const virtual
Implements solidChemistryModel< CompType, SolidThermo >.
Definition at line 231 of file pyrolysisChemistryModel.C.
References Foam::exp(), Foam::max(), p, Foam::pow(), R, s(), UPtrList< T >::size(), T, and Foam::Zero.
omegaI()
template<class CompType , class SolidThermo , class GasThermo > Foam::scalar omegaI (label iReaction, const scalarField & c, const scalar T, const scalar p, scalar & pf, scalar & cf, label & lRef, scalar & pr, scalar & cr, label & rRef) const virtual
Implements solidChemistryModel< CompType, SolidThermo >.
Definition at line 273 of file pyrolysisChemistryModel.C.
References p, R, and T.
calculate()
template<class CompType , class SolidThermo , class GasThermo > void calculate () virtual
Implements solidChemistryModel< CompType, SolidThermo >.
Definition at line 444 of file pyrolysisChemistryModel.C.
References delta, forAll, mesh, IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, basicThermo::p(), rho, basicThermo::T(), timeName, fvMesh::V(), and Foam::Zero.
RRg() [2/3]
template<class CompType , class SolidThermo , class GasThermo > const Foam::DimensionedField< Foam::scalar, Foam::volMesh > & RRg (const label i) const inline
Definition at line 63 of file pyrolysisChemistryModelI.H.
RRg() [3/3]
template<class CompType , class SolidThermo , class GasThermo > Foam::tmp< Foam::DimensionedField< Foam::scalar, Foam::volMesh > > RRg () const inline
Definition at line 74 of file pyrolysisChemistryModelI.H.
References Foam::dimMass, Foam::dimTime, Foam::dimVolume, mesh, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, timeName, and Foam::Zero.
gasHs()
template<class CompType , class SolidThermo , class GasThermo > Foam::tmp< Foam::volScalarField > gasHs (const volScalarField & p, const volScalarField & T, const label i) const virtual
Definition at line 610 of file pyrolysisChemistryModel.C.
References Foam::dimEnergy, Foam::dimMass, forAll, IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, p, T, and Foam::Zero.
solve() [1/2]
template<class CompType , class SolidThermo , class GasThermo > Foam::scalar solve (const scalar deltaT) virtual
Implements solidChemistryModel< CompType, SolidThermo >.
Definition at line 512 of file pyrolysisChemistryModel.C.
References delta, forAll, mesh, Foam::min(), IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, p, basicThermo::p(), rho, solve(), T, basicThermo::T(), timeName, and Foam::Zero.
nEqns()
template<class CompType , class SolidThermo , class GasThermo > Foam::label nEqns () const virtual
Implements solidChemistryModel< CompType, SolidThermo >.
Definition at line 436 of file pyrolysisChemistryModel.C.
derivatives()
template<class CompType , class SolidThermo , class GasThermo > void derivatives (const scalar t, const scalarField & c, scalarField & dcdt) const virtual
Implements solidChemistryModel< CompType, SolidThermo >.
Definition at line 296 of file pyrolysisChemistryModel.C.
References Foam::mag(), Foam::min(), p, and T.
jacobian()
template<class CompType , class SolidThermo , class GasThermo > void jacobian (const scalar t, const scalarField & c, scalarField & dcdt, scalarSquareMatrix & dfdc) const virtual
Implements solidChemistryModel< CompType, SolidThermo >.
Definition at line 338 of file pyrolysisChemistryModel.C.
References delta, Foam::endl(), Foam::exp(), forAll, Foam::Info, Foam::max(), p, Foam::pow(), R, UPtrList< T >::size(), T, and Foam::Zero.
solve() [2/2]
template<class CompType , class SolidThermo , class GasThermo > void solve (scalarField & c, scalar & T, scalar & p, scalar & deltaT, scalar & subDeltaT) const virtual
Implements solidChemistryModel< CompType, SolidThermo >.
Definition at line 649 of file pyrolysisChemistryModel.C.
References NotImplemented.
Member Data Documentation
pyrolisisGases_
template<class CompType , class SolidThermo , class GasThermo > speciesTable pyrolisisGases_ protected
Definition at line 63 of file pyrolysisChemistryModel.H.
Referenced by pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::pyrolysisChemistryModel().
gasThermo_
template<class CompType , class SolidThermo , class GasThermo > PtrList<GasThermo> gasThermo_ protected
Definition at line 66 of file pyrolysisChemistryModel.H.
Referenced by pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::pyrolysisChemistryModel().
nGases_
template<class CompType , class SolidThermo , class GasThermo > label nGases_ protected
Definition at line 69 of file pyrolysisChemistryModel.H.
Referenced by pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::pyrolysisChemistryModel().
nSpecie_
template<class CompType , class SolidThermo , class GasThermo > label nSpecie_ protected
Definition at line 72 of file pyrolysisChemistryModel.H.
RRg_
template<class CompType , class SolidThermo , class GasThermo > PtrList<volScalarField::Internal> RRg_ protected
Definition at line 75 of file pyrolysisChemistryModel.H.
Referenced by pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::pyrolysisChemistryModel().
Ys0_
template<class CompType , class SolidThermo , class GasThermo > PtrList<volScalarField> Ys0_ mutable protected
Definition at line 78 of file pyrolysisChemistryModel.H.
Referenced by pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::pyrolysisChemistryModel().
The documentation for this class was generated from the following files:
src/thermophysicalModels/solidChemistryModel/pyrolysisChemistryModel/pyrolysisChemistryModel.H
src/thermophysicalModels/solidChemistryModel/pyrolysisChemistryModel/pyrolysisChemistryModel.C
src/thermophysicalModels/solidChemistryModel/pyrolysisChemistryModel/pyrolysisChemistryModelI.H