OpenFOAM: searchableBox Class Reference
searchableBox Class Reference
Searching on bounding box.
#include <searchableBox.H>
Public Member Functions
TypeName ("searchableBox")
searchableBox (const IOobject &io, const treeBoundBox &bb)
searchableBox (const IOobject &io, const dictionary &dict)
virtual ~searchableBox ()=default
virtual const wordList & regions () const
virtual bool hasVolumeType () const
virtual volumeType outsideVolumeType () const
virtual label size () const
virtual tmp< pointField > coordinates () const
virtual void boundingSpheres (pointField &centres, scalarField &radiusSqr) const
virtual tmp< pointField > points () const
virtual bool overlaps (const boundBox &bb) const
pointIndexHit findNearest (const point &sample, const scalar nearestDistSqr) const
pointIndexHit findNearestOnEdge (const point &sample, const scalar nearestDistSqr) const
pointIndexHit findNearest (const linePointRef &ln, treeBoundBox &tightest, point &linePoint) const
pointIndexHit findLine (const point &start, const point &end) const
pointIndexHit findLineAny (const point &start, const point &end) const
virtual void findNearest (const pointField &sample, const scalarField &nearestDistSqr, List< pointIndexHit > &) const
virtual void findLine (const pointField &start, const pointField &end, List< pointIndexHit > &) const
virtual void findLineAny (const pointField &start, const pointField &end, List< pointIndexHit > &) const
virtual void findLineAll (const pointField &start, const pointField &end, List< List< pointIndexHit > > &) const
virtual void getRegion (const List< pointIndexHit > &, labelList &region) const
virtual void getNormal (const List< pointIndexHit > &, vectorField &normal) const
virtual void getVolumeType (const pointField &points, List< volumeType > &volType) const
bool writeData (Ostream &) const
Public Member Functions inherited from searchableSurface
TypeName ("searchableSurface")
declareRunTimeSelectionTable (autoPtr, searchableSurface, dict,(const IOobject &io, const dictionary &dict),(io, dict))
searchableSurface (const IOobject &io)
virtual autoPtr< searchableSurface > clone () const
virtual ~searchableSurface ()=default
virtual bool global () const
virtual fileName filePath () const
virtual const boundBox & bounds () const
virtual boundBox & bounds ()
virtual label globalSize () const
virtual void distribute (const List< treeBoundBox > &, const bool keepNonLocal, autoPtr< mapDistribute > &faceMap, autoPtr< mapDistribute > &pointMap)
virtual void setField (const labelList &values)
virtual void getField (const List< pointIndexHit > &, labelList &values) const
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
regIOobject (const IOobject &io, const bool isTimeObject=false)
regIOobject (const regIOobject &rio)
regIOobject (const regIOobject &rio, bool registerCopy)
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
regIOobject (const IOobject &io, const regIOobject &rio)
virtual ~regIOobject ()
bool checkIn ()
bool checkOut ()
virtual void addWatch ()
bool registered () const noexcept
bool ownedByRegistry () const noexcept
bool store ()
void release (const bool unregister=false) noexcept
label eventNo () const noexcept
label & eventNo () noexcept
bool upToDate (const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
void setUpToDate ()
virtual void rename (const word &newName)
const dictionary * findMetaData () const noexcept
dictionary & getMetaData () noexcept
void removeMetaData ()
virtual void updateMetaData ()
bool headerOk ()
Istream & readStream (const word &, const bool readOnProc=true)
void close ()
virtual bool readData (Istream &)
virtual bool read ()
virtual label addWatch (const fileName &)
const labelList & watchIndices () const noexcept
labelList & watchIndices () noexcept
virtual bool modified () const
virtual bool readIfModified ()
virtual bool writeObject (IOstreamOption streamOpt, const bool writeOnProc) const
virtual bool write (const bool writeOnProc=true) const
void operator= (const IOobject &io)
virtual bool writeObject (IOstreamOption::streamFormat fmt, IOstreamOption::versionNumber ver, IOstreamOption::compressionType cmp, const bool writeOnProc) const
Public Member Functions inherited from IOobject
TypeName ("IOobject")
IOobject (const IOobject &)=default
virtual ~IOobject ()=default
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const fileName &path, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const fileName &path, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const IOobject &io, const objectRegistry &registry)
IOobject (const IOobject &io, const word &name)
IOobject (const IOobject &io, const word &name, const fileName &local)
IOobject (const IOobject &io, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt)
IOobject (const IOobject &io, IOobjectOption::registerOption regOpt)
autoPtr< IOobject > clone () const
autoPtr< IOobject > clone (const objectRegistry &registry) const
const objectRegistry & db () const noexcept
const Time & time () const noexcept
const word & name () const noexcept
const word & headerClassName () const noexcept
word & headerClassName () noexcept
const string & note () const noexcept
string & note () noexcept
unsigned labelByteSize () const noexcept
unsigned scalarByteSize () const noexcept
void resetHeader (const word &newName=word::null)
bool hasHeaderClass () const noexcept
template<class Type >
bool isHeaderClass () const
template<class Type >
bool isHeaderClassName () const
word group () const
word member () const
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const noexcept
fileName & instance () noexcept
const fileName & local () const noexcept
fileName path () const
fileName path (const word &instance, const fileName &local=fileName::null) const
fileName objectPath () const
fileName objectRelPath () const
fileName localFilePath (const word &typeName, const bool search=true) const
fileName globalFilePath (const word &typeName, const bool search=true) const
IOstreamOption parseHeader (const dictionary &headerDict)
bool readHeader (Istream &is)
bool readHeader (dictionary &headerDict, Istream &is)
template<class Type >
bool typeHeaderOk (const bool checkType=true, const bool search=true, const bool verbose=true)
template<class Type >
void warnNoRereading () const
bool writeHeader (Ostream &os) const
bool writeHeader (Ostream &os, const word &objectType) const
void writeHeader (dictionary &dict, IOstreamOption streamOpt) const
void writeHeader (dictionary &dict, const word &objectType, IOstreamOption streamOpt) const
bool good () const noexcept
bool bad () const noexcept
InfoProxy< IOobject > info () const noexcept
void operator= (const IOobject &io)
template<>
bool isHeaderClass () const
template<class StringType >
Foam::word groupName (StringType base, const word &group)
Public Member Functions inherited from IOobjectOption
constexpr IOobjectOption (readOption rOpt=readOption::NO_READ, writeOption wOpt=writeOption::NO_WRITE, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (readOption rOpt, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (writeOption wOpt, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (registerOption registerObject, bool globalObject=false) noexcept
constexpr IOobjectOption (readOption rOpt, writeOption wOpt, bool registerObject, bool globalObject=false) noexcept
constexpr IOobjectOption (bool registerObject, bool globalObject=false) noexcept
readOption readOpt () const noexcept
readOption readOpt (readOption opt) noexcept
writeOption writeOpt () const noexcept
writeOption writeOpt (writeOption opt) noexcept
bool registerObject () const noexcept
bool registerObject (bool on) noexcept
bool globalObject () const noexcept
bool globalObject (bool on) noexcept
bool isAnyRead () const noexcept
bool isReadRequired () const noexcept
bool isReadOptional () const noexcept
readOption & readOpt () noexcept
writeOption & writeOpt () noexcept
bool & registerObject () noexcept
bool & globalObject () noexcept
Public Member Functions inherited from treeBoundBox
treeBoundBox ()=default
treeBoundBox (const treeBoundBox &)=default
treeBoundBox & operator= (const treeBoundBox &)=default
treeBoundBox (const boundBox &bb)
void operator= (const boundBox &bb)
treeBoundBox (const Foam::zero_one)
treeBoundBox (const point &p)
treeBoundBox (const point &min, const point &max)
treeBoundBox (const Pair< point > &bb)
treeBoundBox (const UList< point > &points)
treeBoundBox (const UList< point > &points, const labelUList &indices)
template<unsigned N>
treeBoundBox (const UList< point > &points, const FixedList< label, N > &indices)
treeBoundBox (Istream &is)
tmp< pointField > points () const
point corner (const direction octant) const
treeBoundBox subBbox (const direction octant) const
treeBoundBox subBbox (const point &mid, const direction) const
treeBoundBox subHalf (const direction whichFace) const
treeBoundBox subHalf (const scalar mid, const direction whichFace) const
direction subOctant (const point &pt) const
direction subOctant (const point &pt, bool &onEdge) const
void searchOrder (const point &pt, FixedList< direction, 8 > &octantOrder) const
FixedList< direction, 8 > searchOrder (const point &pt) const
bool subOverlaps (const direction octant, const boundBox &bb) const
bool subOverlaps (const direction octant, const point &centre, const scalar radiusSqr) const
bool intersects (const point &overallStart, const vector &overallVec, const point &start, const point &end, point &pt, direction &ptBits) const
bool intersects (const point &start, const point &end, point &pt) const
bool intersects (const linePointRef &ln, point &pt) const
bool contains (const vector &dir, const point &) const
direction faceBits (const point &pt) const
direction posBits (const point &pt) const
void calcExtremities (const point &pt, point &nearest, point &furthest) const
scalar maxDist (const point &pt) const
label distanceCmp (const point &pt, const treeBoundBox &other) const
treeBoundBox extend (Random &rndGen, const scalar s) const
treeBoundBox extend (Random &rndGen, const scalar s, const scalar delta) const
scalar typDim () const
bool overlaps (const boundBox &bb) const
bool overlaps (const point &centre, const scalar radiusSqr) const
bool intersects (const plane &pln) const
bool intersects (const triPointRef &tri) const
bool contains (const point &pt) const
bool contains (const boundBox &bb) const
bool contains (const UList< point > &points) const
template<unsigned N>
bool contains (const UList< point > &points, const FixedList< label, N > &indices) const
template<class IntContainer >
bool contains (const UList< point > &points, const IntContainer &indices) const
Public Member Functions inherited from boundBox
boundBox ()
boundBox (const boundBox &)=default
boundBox & operator= (const boundBox &)=default
boundBox (const boundBox &bb, bool doReduce)
boundBox (const point &p)
boundBox (const Foam::zero_one)
boundBox (const point &min, const point &max)
boundBox (const Pair< point > &bb)
boundBox (const UList< point > &points, bool doReduce=true)
boundBox (const tmp< pointField > &tpoints, bool doReduce=true)
boundBox (const UList< point > &points, const labelUList &indices, bool doReduce=true)
template<unsigned N>
boundBox (const UList< point > &points, const FixedList< label, N > &indices, bool doReduce=true)
boundBox (Istream &is)
bool empty () const
bool good () const
bool valid () const
const point & min () const noexcept
const point & max () const noexcept
point & min () noexcept
point & max () noexcept
point centre () const
vector span () const
scalar mag () const
scalar magSqr () const
scalar volume () const
scalar minDim () const
scalar maxDim () const
scalar avgDim () const
direction minDir () const
direction maxDir () const
int nDim () const
template<direction CornerNumber>
point hexCorner () const
tmp< pointField > hexCorners () const
tmp< pointField > points () const
tmp< pointField > faceCentres () const
point faceCentre (const direction facei) const
void reset ()
void reset (const Foam::zero_one)
void reset (const point &pt)
void reset (const point &min, const point &max)
void clear ()
void add (const boundBox &bb)
void add (const point &pt)
void add (const point &pt0, const point &pt1)
void add (const Pair< point > &points)
void add (const UList< point > &points)
void add (const tmp< pointField > &tpoints)
template<unsigned N>
void add (const FixedList< point, N > &points)
template<unsigned N>
void add (const UList< point > &points, const FixedList< label, N > &indices)
template<class IntContainer >
void add (const UList< point > &points, const IntContainer &indices)
void grow (const scalar delta)
void grow (const vector &delta)
void inflate (const scalar factor)
void inflate (Random &rndGen, const scalar factor)
void inflate (Random &r, const scalar factor, const scalar delta)
void reduce ()
bool intersects (const plane &pln) const
bool intersects (const triPointRef &tri) const
bool overlaps (const boundBox &bb) const
bool overlaps (const point &centre, const scalar radiusSqr) const
bool contains (const point &pt) const
bool contains (const boundBox &bb) const
bool containsInside (const point &pt) const
bool contains (const UList< point > &points) const
template<unsigned N>
bool contains (const UList< point > &points, const FixedList< label, N > &indices) const
template<class IntContainer >
bool contains (const UList< point > &points, const IntContainer &indices) const
bool containsAny (const UList< point > &points) const
template<unsigned N>
bool containsAny (const UList< point > &points, const FixedList< label, N > &indices) const
template<class IntContainer >
bool containsAny (const UList< point > &points, const IntContainer &indices) const
point nearest (const point &p) const
void operator&= (const boundBox &bb)
void operator+= (const boundBox &bb)
bool intersect (const boundBox &bb)
point midpoint () const
template<>
Foam::point hexCorner () const
template<>
Foam::point hexCorner () const
template<>
Foam::point hexCorner () const
template<>
Foam::point hexCorner () const
template<>
Foam::point hexCorner () const
template<>
Foam::point hexCorner () const
template<>
Foam::point hexCorner () const
template<>
Foam::point hexCorner () const
template<Foam::direction CornerNumber>
Foam::point hexCorner () const
Additional Inherited Members
Public Types inherited from IOobject
enum objectState : char { GOOD , BAD }
enum fileCheckTypes : char { timeStamp , timeStampMaster , inotify , inotifyMaster }
Public Types inherited from IOobjectOption
enum readOption : unsigned char {
NO_READ = 0 , MUST_READ = 0x1 , READ_MODIFIED = 0x3 , MUST_READ_IF_MODIFIED = 0x3 ,
LAZY_READ = 0x4 , READ_IF_PRESENT = 0x4
}
enum writeOption : unsigned char { NO_WRITE = 0 , AUTO_WRITE = 0x10 }
enum registerOption : unsigned char { NO_REGISTER = 0 , REGISTER = 1 }
Public Types inherited from treeBoundBox
enum octantBit : direction { RIGHTHALF = 1 , TOPHALF = 2 , FRONTHALF = 4 }
enum faceId : direction {
LEFT = 0 , RIGHT = 1 , BOTTOM = 2 , TOP = 3 ,
BACK = 4 , FRONT = 5
}
enum faceBit : direction {
NOFACE = 0 , LEFTBIT = (1 << LEFT) , RIGHTBIT = (1 << RIGHT) , BOTTOMBIT = (1 << BOTTOM) ,
TOPBIT = (1 << TOP) , BACKBIT = (1 << BACK) , FRONTBIT = (1 << FRONT)
}
enum edgeId {
E01 = 0 , E13 = 1 , E23 = 2 , E02 = 3 ,
E45 = 4 , E57 = 5 , E67 = 6 , E46 = 7 ,
E04 = 8 , E15 = 9 , E37 = 10 , E26 = 11
}
Public Types inherited from boundBox
enum directionBit : direction { XDIR = 1 , YDIR = 2 , ZDIR = 4 }
Static Public Member Functions inherited from searchableSurface
static autoPtr< searchableSurface > New (const word &surfaceType, const IOobject &io, const dictionary &dict)
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *p)
template<class Type >
static Type & store (autoPtr< Type > &ptr)
template<class Type >
static Type & store (autoPtr< Type > &&ptr)
template<class Type >
static Type & store (refPtr< Type > &ptr)
template<class Type >
static Type & store (refPtr< Type > &&ptr)
template<class Type >
static Type & store (tmp< Type > &ptr)
template<class Type >
static Type & store (tmp< Type > &&ptr)
Static Public Member Functions inherited from IOobject
static bool bannerEnabled () noexcept
static bool bannerEnabled (bool on) noexcept
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
template<class StringType >
static word groupName (StringType base, const word &group)
static word group (const word &name)
static word member (const word &name)
static word scopedName (const std::string &scope, const word &name)
static IOobject selectIO (const IOobject &io, const fileName &altFile, const word &ioName="")
static Ostream & writeBanner (Ostream &os, const bool noSyntaxHint=false)
static Ostream & writeDivider (Ostream &os)
static Ostream & writeEndDivider (Ostream &os)
Static Public Member Functions inherited from IOobjectOption
static bool isAnyRead (readOption opt) noexcept
static bool isReadRequired (readOption opt) noexcept
static bool isReadOptional (readOption opt) noexcept
static readOption lazierRead (readOption opt) noexcept
Static Public Member Functions inherited from treeBoundBox
static const treeBoundBox & null () noexcept
static direction subOctant (const point &mid, const point &pt)
static direction subOctant (const point &mid, const point &pt, bool &onEdge)
static direction subOctant (const point &mid, const vector &dir, const point &pt, bool &onEdge)
Static Public Member Functions inherited from boundBox
static const boundBox & null () noexcept
static const Foam::faceList & hexFaces ()
static constexpr label nPoints () noexcept
static constexpr label nEdges () noexcept
static constexpr label nFaces () noexcept
static boundBox returnReduce (const boundBox &bb)
Static Public Attributes inherited from IOobject
static const Enum< fileCheckTypes > fileCheckTypesNames
static char scopeSeparator
static fileCheckTypes fileModificationChecking
static float fileModificationSkew
static int maxFileModificationPolls
Static Public Attributes inherited from treeBoundBox
static const faceList faces
static const edgeList edges
Static Public Attributes inherited from boundBox
static const boundBox greatBox
static const boundBox invertedBox
static const FixedList< vector, 6 > faceNormals
Protected Member Functions inherited from regIOobject
bool readHeaderOk (const IOstreamOption::streamFormat fmt, const word &typeName)
Protected Member Functions inherited from IOobject
void setBad (const string &s)
Static Protected Member Functions inherited from IOobject
static void writeHeaderContent (Ostream &os, const IOobject &io, const word &objectType, const dictionary *metaDataDict=nullptr)
static void writeHeaderContent (dictionary &dict, const IOobject &io, const word &objectType, IOstreamOption streamOpt, const dictionary *metaDataDict=nullptr)
Static Protected Member Functions inherited from boundBox
static bool box_box_overlaps (const point &minA, const point &maxA, const point &minB, const point &maxB)
static bool box_sphere_overlaps (const point &corner0, const point &corner1, const point &centre, const scalar radiusSqr)
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
Detailed Description
Searching on bounding box.
Dictionary parameters
Property Description Required Default
type box selector
min Minimum point for bounding box yes
max Maximum point for bounding box yes
span Box width cond'l
Note
The order of precedence from the highest to the lowest is min-max or min-span pair
Longer type name : searchableBox
Source files
searchableBox.H
searchableBox.C
Definition at line 89 of file searchableBox.H.
Constructor & Destructor Documentation
searchableBox() [1/2]
searchableBox (const IOobject & io, const treeBoundBox & bb)
Definition at line 193 of file searchableBox.C.
References searchableSurface::bounds(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::nl, and boundBox::valid().
searchableBox() [2/2]
searchableBox (const IOobject & io, const dictionary & dict)
Definition at line 214 of file searchableBox.C.
References searchableSurface::bounds(), dict, Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::nl, Foam::readBoxDim(), and boundBox::valid().
~searchableBox()
virtual ~searchableBox () virtual default
Member Function Documentation
TypeName()
TypeName ("searchableBox")
regions()
const Foam::wordList & regions () const virtual
Implements searchableSurface.
Definition at line 239 of file searchableBox.C.
References PtrList< T >::resize().
hasVolumeType()
virtual bool hasVolumeType () const inline virtual
Reimplemented from searchableSurface.
Definition at line 157 of file searchableBox.H.
outsideVolumeType()
virtual volumeType outsideVolumeType () const inline virtual
Implements searchableSurface.
Definition at line 162 of file searchableBox.H.
References volumeType::OUTSIDE.
size()
virtual label size () const inline virtual
Implements searchableSurface.
Definition at line 168 of file searchableBox.H.
coordinates()
Foam::tmp< Foam::pointField > coordinates () const virtual
Implements searchableSurface.
Definition at line 250 of file searchableBox.C.
References treeBoundBox::faces, forAll, tmp< T >::New(), treeBoundBox::points(), and pts.
boundingSpheres()
void boundingSpheres (pointField & centres, scalarField & radiusSqr) const virtual
Implements searchableSurface.
Definition at line 267 of file searchableBox.C.
References f(), treeBoundBox::faces, forAll, Foam::max(), treeBoundBox::points(), pts, List< T >::setSize(), PtrList< T >::setSize(), Foam::sqr(), and Foam::Zero.
points()
Foam::tmp< Foam::pointField > points () const virtual
Implements searchableSurface.
Definition at line 298 of file searchableBox.C.
References treeBoundBox::points().
Referenced by searchableRotatedBox::searchableRotatedBox().
overlaps()
virtual bool overlaps (const boundBox & bb) const inline virtual
Implements searchableSurface.
Definition at line 189 of file searchableBox.H.
References boundBox::overlaps().
findNearest() [1/3]
Foam::pointIndexHit findNearest (const point & sample, const scalar nearestDistSqr) const
Definition at line 304 of file searchableBox.C.
findNearestOnEdge()
Foam::pointIndexHit findNearestOnEdge (const point & sample, const scalar nearestDistSqr) const
Definition at line 314 of file searchableBox.C.
References Foam::cmptMag(), Foam::max(), Foam::min(), VectorSpace< Form, Cmpt, Ncmpts >::nComponents, PointIndexHit< PointType >::point(), PointIndexHit< PointType >::setIndex(), and PointIndexHit< PointType >::setMiss().
findNearest() [2/3]
Foam::pointIndexHit findNearest (const linePointRef & ln, treeBoundBox & tightest, point & linePoint) const
Definition at line 384 of file searchableBox.C.
References NotImplemented.
findLine() [1/2]
Foam::pointIndexHit findLine (const point & start, const point & end) const
Definition at line 396 of file searchableBox.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, PointIndexHit< PointType >::index(), Foam::max(), Foam::min(), VectorSpace< Form, Cmpt, Ncmpts >::nComponents, PointIndexHit< PointType >::point(), PointIndexHit< PointType >::setHit(), and PointIndexHit< PointType >::setIndex().
findLineAny() [1/2]
Foam::pointIndexHit findLineAny (const point & start, const point & end) const
Definition at line 459 of file searchableBox.C.
findNearest() [3/3]
void findNearest (const pointField & sample, const scalarField & nearestDistSqr, List< pointIndexHit > & info) const virtual
Implements searchableSurface.
Definition at line 469 of file searchableBox.C.
References forAll, samples(), PtrList< T >::setSize(), and UList< T >::size().
findLine() [2/2]
void findLine (const pointField & start, const pointField & end, List< pointIndexHit > & info) const virtual
Implements searchableSurface.
Definition at line 487 of file searchableBox.C.
References forAll, PtrList< T >::setSize(), and UList< T >::size().
findLineAny() [2/2]
void findLineAny (const pointField & start, const pointField & end, List< pointIndexHit > & info) const virtual
Implements searchableSurface.
Definition at line 503 of file searchableBox.C.
References forAll, PtrList< T >::setSize(), and UList< T >::size().
findLineAll()
void findLineAll (const pointField & start, const pointField & end, List< List< pointIndexHit > > & info) const virtual
Implements searchableSurface.
Definition at line 519 of file searchableBox.C.
References PtrList< T >::append(), PtrList< T >::clear(), forAll, UPtrList< T >::last(), Foam::magSqr(), PtrList< T >::setSize(), UList< T >::size(), PtrList< T >::transfer(), and VectorSpace< Form, Cmpt, Ncmpts >::uniform().
getRegion()
void getRegion (const List< pointIndexHit > & info, labelList & region) const virtual
Implements searchableSurface.
Definition at line 586 of file searchableBox.C.
References List< T >::setSize(), and UPtrList< T >::size().
getNormal()
void getNormal (const List< pointIndexHit > & info, vectorField & normal) const virtual
Implements searchableSurface.
Definition at line 597 of file searchableBox.C.
References boundBox::faceNormals, forAll, List< T >::setSize(), UPtrList< T >::size(), and Foam::Zero.
getVolumeType()
void getVolumeType (const pointField & points, List< volumeType > & volType) const virtual
Implements searchableSurface.
Definition at line 620 of file searchableBox.C.
References treeBoundBox::contains(), forAll, volumeType::INSIDE, volumeType::OUTSIDE, points, and UPtrList< T >::size().
writeData()
bool writeData (Ostream &) const inline virtual
Implements regIOobject.
Definition at line 303 of file searchableBox.H.
References NotImplemented.
The documentation for this class was generated from the following files:
src/meshTools/searchableSurfaces/searchableBox/searchableBox.H
src/meshTools/searchableSurfaces/searchableBox/searchableBox.C