OpenFOAM: cyclicAMIPointPatch Class Reference
cyclicAMIPointPatch Class Reference
Cyclic AMI point patch - place holder only.
#include <cyclicAMIPointPatch.H>
Public Member Functions
TypeName (cyclicAMIPolyPatch::typeName_())
cyclicAMIPointPatch (const polyPatch &patch, const pointBoundaryMesh &bm)
virtual ~cyclicAMIPointPatch ()
virtual bool coupled () const
virtual const word & constraintType () const
const cyclicAMIPolyPatch & cyclicAMIPatch () const
const cyclicAMIPointPatch & neighbPatch () const
bool parallel () const
const tensorField & forwardT () const
const tensorField & reverseT () const
Public Member Functions inherited from coupledFacePointPatch
TypeName (coupledPolyPatch::typeName_())
coupledFacePointPatch (const polyPatch &patch, const pointBoundaryMesh &bm)
virtual ~coupledFacePointPatch ()=default
Public Member Functions inherited from facePointPatch
TypeName (polyPatch::typeName_())
declareRunTimeSelectionTable (autoPtr, facePointPatch, polyPatch,(const polyPatch &patch, const pointBoundaryMesh &bm),(patch, bm))
facePointPatch (const polyPatch &p, const pointBoundaryMesh &pm)
virtual ~facePointPatch ()=default
virtual const polyPatch & patch () const
virtual const word & name () const
virtual label size () const
virtual label index () const
virtual const labelList & meshPoints () const
virtual const pointField & localPoints () const
virtual const vectorField & pointNormals () const
Public Member Functions inherited from pointPatch
TypeName ("basePatch")
pointPatch (const pointBoundaryMesh &bm)
virtual ~pointPatch ()=default
const pointBoundaryMesh & boundaryMesh () const
virtual void applyConstraint (const label pointi, pointConstraint &) const
Public Member Functions inherited from coupledPointPatch
TypeName (coupledPolyPatch::typeName_())
coupledPointPatch (const pointBoundaryMesh &bm)
virtual ~coupledPointPatch ()=default
Protected Member Functions
virtual void initGeometry (PstreamBuffers &)
virtual void calcGeometry (PstreamBuffers &)
virtual void initMovePoints (PstreamBuffers &, const pointField &)
virtual void movePoints (PstreamBuffers &, const pointField &)
virtual void initUpdateMesh (PstreamBuffers &)
virtual void updateMesh (PstreamBuffers &)
Protected Member Functions inherited from coupledFacePointPatch
coupledFacePointPatch (const coupledFacePointPatch &)=delete
void operator= (const coupledFacePointPatch &)=delete
Protected Member Functions inherited from facePointPatch
facePointPatch (const facePointPatch &)=delete
void operator= (const facePointPatch &)=delete
Protected Member Functions inherited from pointPatch
pointPatch (const pointPatch &)=delete
void operator= (const pointPatch &)=delete
Protected Member Functions inherited from coupledPointPatch
coupledPointPatch (const coupledPointPatch &)=delete
void operator= (const coupledPointPatch &)=delete
Additional Inherited Members
Static Public Member Functions inherited from facePointPatch
static autoPtr< facePointPatch > New (const polyPatch &, const pointBoundaryMesh &)
Protected Attributes inherited from facePointPatch
const polyPatch & polyPatch_
Detailed Description
Cyclic AMI point patch - place holder only.
Source files
cyclicAMIPointPatch.H
cyclicAMIPointPatch.C
Definition at line 48 of file cyclicAMIPointPatch.H.
Constructor & Destructor Documentation
cyclicAMIPointPatch()
cyclicAMIPointPatch (const polyPatch & patch, const pointBoundaryMesh & bm)
Definition at line 86 of file cyclicAMIPointPatch.C.
~cyclicAMIPointPatch()
~cyclicAMIPointPatch () virtual
Definition at line 99 of file cyclicAMIPointPatch.C.
Member Function Documentation
initGeometry()
void initGeometry (PstreamBuffers &) protected virtual
Reimplemented from facePointPatch.
Definition at line 50 of file cyclicAMIPointPatch.C.
calcGeometry()
void calcGeometry (PstreamBuffers &) protected virtual
Implements coupledFacePointPatch.
Definition at line 54 of file cyclicAMIPointPatch.C.
initMovePoints()
void initMovePoints (PstreamBuffers & , const pointField &) protected virtual
Reimplemented from facePointPatch.
Definition at line 58 of file cyclicAMIPointPatch.C.
movePoints()
void movePoints (PstreamBuffers & , const pointField &) protected virtual
Reimplemented from facePointPatch.
Definition at line 66 of file cyclicAMIPointPatch.C.
initUpdateMesh()
void initUpdateMesh (PstreamBuffers & pBufs) protected virtual
Reimplemented from facePointPatch.
Definition at line 70 of file cyclicAMIPointPatch.C.
References facePointPatch::initUpdateMesh().
updateMesh()
void updateMesh (PstreamBuffers & pBufs) protected virtual
Reimplemented from facePointPatch.
Definition at line 77 of file cyclicAMIPointPatch.C.
References facePointPatch::updateMesh().
TypeName()
TypeName (cyclicAMIPolyPatch::typeName_())
coupled()
bool coupled () const virtual
Reimplemented from facePointPatch.
Definition at line 105 of file cyclicAMIPointPatch.C.
References boundaryMesh::mesh(), and UPstream::parRun().
constraintType()
virtual const word & constraintType () const inline virtual
Reimplemented from pointPatch.
Definition at line 116 of file cyclicAMIPointPatch.H.
References Foam::type().
cyclicAMIPatch()
const cyclicAMIPolyPatch & cyclicAMIPatch () const inline
Definition at line 122 of file cyclicAMIPointPatch.H.
neighbPatch()
const cyclicAMIPointPatch & neighbPatch () const inline
Definition at line 128 of file cyclicAMIPointPatch.H.
References cyclicAMIPolyPatch::neighbPatchID(), and pp().
parallel()
bool parallel () const inline
Definition at line 136 of file cyclicAMIPointPatch.H.
References coupledPolyPatch::parallel().
Referenced by cyclicAMIPointPatchField< Type >::doTransform().
forwardT()
const tensorField & forwardT () const inline
Definition at line 142 of file cyclicAMIPointPatch.H.
References coupledPolyPatch::forwardT().
Referenced by cyclicAMIPointPatchField< Type >::forwardT().
reverseT()
const tensorField & reverseT () const inline
Definition at line 148 of file cyclicAMIPointPatch.H.
References coupledPolyPatch::reverseT().
Referenced by cyclicAMIPointPatchField< Type >::reverseT().
The documentation for this class was generated from the following files:
src/meshTools/AMIInterpolation/patches/cyclicAMI/cyclicAMIPointPatch/cyclicAMIPointPatch.H
src/meshTools/AMIInterpolation/patches/cyclicAMI/cyclicAMIPointPatch/cyclicAMIPointPatch.C