OpenFOAM: alphaFixedPressureFvPatchScalarField Class Reference
alphaFixedPressureFvPatchScalarField Class Reference
A fixed-pressure alphaContactAngle boundary.
#include <alphaFixedPressureFvPatchScalarField.H>
Public Member Functions
TypeName ("alphaFixedPressure")
alphaFixedPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
alphaFixedPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
alphaFixedPressureFvPatchScalarField (const alphaFixedPressureFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
alphaFixedPressureFvPatchScalarField (const alphaFixedPressureFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
alphaFixedPressureFvPatchScalarField (const alphaFixedPressureFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
const scalarField & p () const
scalarField & p ()
virtual void autoMap (const fvPatchFieldMapper &)
virtual void rmap (const fvPatchScalarField &, const labelList &)
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
A fixed-pressure alphaContactAngle boundary.
Source files
alphaFixedPressureFvPatchScalarField.H
alphaFixedPressureFvPatchScalarField.C
Definition at line 46 of file alphaFixedPressureFvPatchScalarField.H.
Constructor & Destructor Documentation
alphaFixedPressureFvPatchScalarField() [1/5]
alphaFixedPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 31 of file alphaFixedPressureFvPatchScalarField.C.
alphaFixedPressureFvPatchScalarField() [2/5]
alphaFixedPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 57 of file alphaFixedPressureFvPatchScalarField.C.
References dict, and fvPatchField< Type >::operator=().
alphaFixedPressureFvPatchScalarField() [3/5]
alphaFixedPressureFvPatchScalarField (const alphaFixedPressureFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 43 of file alphaFixedPressureFvPatchScalarField.C.
alphaFixedPressureFvPatchScalarField() [4/5]
alphaFixedPressureFvPatchScalarField (const alphaFixedPressureFvPatchScalarField & tppsf)
Definition at line 76 of file alphaFixedPressureFvPatchScalarField.C.
alphaFixedPressureFvPatchScalarField() [5/5]
alphaFixedPressureFvPatchScalarField (const alphaFixedPressureFvPatchScalarField & tppsf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 87 of file alphaFixedPressureFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("alphaFixedPressure")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 96 of file alphaFixedPressureFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 112 of file alphaFixedPressureFvPatchScalarField.H.
p() [1/2]
const scalarField & p () const inline
Definition at line 129 of file alphaFixedPressureFvPatchScalarField.H.
p() [2/2]
scalarField & p () inline
Definition at line 135 of file alphaFixedPressureFvPatchScalarField.H.
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Definition at line 101 of file alphaFixedPressureFvPatchScalarField.C.
References Field< scalar >::autoMap().
rmap()
void rmap (const fvPatchScalarField & ptf, const labelList & addr) virtual
Definition at line 111 of file alphaFixedPressureFvPatchScalarField.C.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 126 of file alphaFixedPressureFvPatchScalarField.C.
References g, gravity::New(), Foam::operator==(), and rho.
write()
void write (Ostream & os) const virtual
Definition at line 144 of file alphaFixedPressureFvPatchScalarField.C.
References os(), fvPatchField< Type >::write(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/transportModels/twoPhaseProperties/alphaFixedPressure/alphaFixedPressureFvPatchScalarField.H
src/transportModels/twoPhaseProperties/alphaFixedPressure/alphaFixedPressureFvPatchScalarField.C