OpenFOAM: OTstream Class Reference
OTstream Class Reference
A simple output token stream that can be used to build token lists. Always UNCOMPRESSED.
#include <OTstream.H>
Public Member Functions
OTstream (IOstreamOption streamOpt=IOstreamOption())
OTstream (const OTstream &os)
OTstream (OTstream &&os)
~OTstream ()=default
const DynamicList< token > & tokens () const noexcept
DynamicList< token > & tokens () noexcept
virtual bool write (const token &tok)
virtual Ostream & write (const char c)
virtual Ostream & write (const char *str)
virtual Ostream & write (const word &str)
virtual Ostream & write (const string &str)
virtual Ostream & writeQuoted (const std::string &str, const bool quoted=true)
virtual Ostream & write (const int32_t val)
virtual Ostream & write (const int64_t val)
virtual Ostream & write (const float val)
virtual Ostream & write (const double val)
virtual Ostream & write (const char *data, std::streamsize count)
virtual Ostream & writeRaw (const char *data, std::streamsize count)
virtual bool beginRawWrite (std::streamsize count)
virtual bool endRawWrite ()
virtual void indent ()
virtual ios_base::fmtflags flags () const
std::ios_base::fmtflags flags (const ios_base::fmtflags)
virtual void flush ()
virtual void endl ()
virtual char fill () const
virtual char fill (const char)
virtual int width () const
virtual int width (const int)
virtual int precision () const
virtual int precision (const int)
void reset ()
virtual void rewind ()
void print (Ostream &os) const
Public Member Functions inherited from Ostream
Ostream (const Ostream &)=default
virtual ~Ostream ()=default
Ostream (IOstreamOption streamOpt=IOstreamOption())
Ostream (IOstreamOption::streamFormat fmt, IOstreamOption::compressionType cmp=IOstreamOption::UNCOMPRESSED)
virtual Ostream & write (const keyType &kw)
unsigned short indentSize () const noexcept
unsigned short indentSize (unsigned short val) noexcept
unsigned short indentLevel () const noexcept
unsigned short indentLevel (unsigned short val) noexcept
void incrIndent () noexcept
void decrIndent ()
virtual Ostream & writeKeyword (const keyType &kw)
virtual Ostream & beginBlock (const keyType &kw)
virtual Ostream & beginBlock ()
virtual Ostream & endBlock ()
virtual Ostream & endEntry ()
template<class T >
Ostream & writeEntry (const keyType &key, const T &value)
template<class T >
Ostream & writeEntryIfDifferent (const word &key, const T &value1, const T &value2)
Ostream & operator() () const
unsigned short & indentLevel () noexcept
unsigned short & indentSize () noexcept
Public Member Functions inherited from IOstream
IOstream (const IOstream &)=default
virtual ~IOstream ()=default
IOstream (IOstreamOption streamOpt=IOstreamOption())
IOstream (IOstreamOption::streamFormat fmt, IOstreamOption::versionNumber ver, IOstreamOption::compressionType cmp=IOstreamOption::UNCOMPRESSED)
virtual const fileName & name () const
fileName relativeName () const
virtual bool check (const char *operation) const
bool fatalCheck (const char *operation) const
bool opened () const noexcept
bool closed () const noexcept
bool good () const noexcept
bool eof () const noexcept
bool fail () const noexcept
bool bad () const noexcept
operator bool () const noexcept
bool operator! () const noexcept
unsigned labelByteSize () const noexcept
unsigned scalarByteSize () const noexcept
void setLabelByteSize (unsigned nbytes) noexcept
void setScalarByteSize (unsigned nbytes) noexcept
template<class T = label>
std::enable_if< std::is_integral< T >::value, bool >::type checkLabelSize () const noexcept
template<class T = scalar>
std::enable_if< std::is_floating_point< T >::value, bool >::type checkScalarSize () const noexcept
label lineNumber () const noexcept
label & lineNumber () noexcept
label lineNumber (const label num) noexcept
void setEof () noexcept
void setFail () noexcept
void setBad ()
ios_base::fmtflags setf (const ios_base::fmtflags f)
ios_base::fmtflags setf (const ios_base::fmtflags f, const ios_base::fmtflags mask)
void unsetf (const ios_base::fmtflags f)
void print (Ostream &os, const int streamState) const
InfoProxy< IOstream > info () const noexcept
Public Member Functions inherited from IOstreamOption
constexpr IOstreamOption (streamFormat fmt=streamFormat::ASCII, compressionType comp=compressionType::UNCOMPRESSED) noexcept
constexpr IOstreamOption (streamFormat fmt, compressionType comp, versionNumber ver) noexcept
constexpr IOstreamOption (streamFormat fmt, versionNumber ver, compressionType comp=compressionType::UNCOMPRESSED) noexcept
IOstreamOption (const IOstreamOption &opt, streamFormat fmt) noexcept
streamFormat format () const noexcept
streamFormat format (const streamFormat fmt) noexcept
streamFormat format (const word &formatName)
compressionType compression () const noexcept
compressionType compression (const compressionType comp) noexcept
compressionType compression (const word &compName)
versionNumber version () const noexcept
versionNumber version (const versionNumber ver) noexcept
versionNumber version (const token &tok)
Public Member Functions inherited from DynamicList< token >
constexpr DynamicList () noexcept
DynamicList (const label len)
DynamicList (const label len, const token &val)
DynamicList (const label len, const Foam::zero)
DynamicList (const DynamicList< token, 16 > &lst)
DynamicList (const DynamicList< token, AnySizeMin > &lst)
DynamicList (const UList< token > &lst)
DynamicList (const UList< token > &list, const labelUList &indices)
DynamicList (const FixedList< token, N > &lst)
DynamicList (std::initializer_list< token > lst)
DynamicList (const IndirectListBase< token, Addr > &lst)
DynamicList (DynamicList< token, 16 > &&lst)
DynamicList (DynamicList< token, AnySizeMin > &&lst)
DynamicList (List< token > &&lst)
DynamicList (Istream &is)
label capacity () const noexcept
std::streamsize capacity_bytes () const noexcept
void setCapacity (const label len)
void setCapacity_nocopy (const label len)
void setCapacity_unsafe (const label len) noexcept
void reserve (const label len)
void reserve_nocopy (const label len)
void resize (const label len)
void resize (const label len, const token &val)
void resize_nocopy (const label len)
void setSize (const label n)
void setSize (const label n, const token &val)
void clear () noexcept
void clearStorage ()
label expandStorage () noexcept
void shrinkStorage ()
DynamicList< token, 16 > & shrink ()
void swap (DynamicList< token, AnySizeMin > &other)
void transfer (List< token > &list)
void transfer (DynamicList< token, AnySizeMin > &list)
token & emplace_back (Args &&... args)
void push_back (const token &val)
void push_back (token &&val)
void push_back (const UList< token > &list)
void push_back (const FixedList< token, N > &list)
void push_back (std::initializer_list< token > list)
void push_back (const IndirectListBase< token, Addr > &lst)
void push_back (List< token > &&list)
void push_back (DynamicList< token, AnySizeMin > &&list)
label push_uniq (const token &val)
void pop_back (label n=1)
token remove ()
token remove (const label idx, const bool fast=false)
label remove (const labelRange &range)
label remove (std::initializer_list< label > start_size)
label subset (const labelRange &range)
label subset (std::initializer_list< label > start_size)
token & operator() (const label i)
void operator= (const token &val)
void operator= (const Foam::zero)
void operator= (const UList< token > &lst)
void operator= (const FixedList< token, N > &lst)
void operator= (const DynamicList< token, 16 > &lst)
void operator= (const DynamicList< token, AnySizeMin > &lst)
void operator= (std::initializer_list< token > lst)
void operator= (const IndirectListBase< token, Addr > &lst)
void operator= (List< token > &&lst)
void operator= (DynamicList< token, 16 > &&lst)
void operator= (DynamicList< token, AnySizeMin > &&lst)
Istream & readList (Istream &is)
void append (const token &val)
void append (token &&val)
void append (const UList< token > &list)
void append (const FixedList< token, N > &list)
void append (std::initializer_list< token > list)
void append (const IndirectListBase< token, Addr > &list)
void append (List< token > &&list)
void append (DynamicList< token, AnySizeMin > &&list)
label appendUniq (const token &val)
Public Member Functions inherited from List< T >
constexpr List () noexcept
List (const label len)
List (const label len, const T &val)
List (const label len, const Foam::zero)
List (const Foam::one, const T &val)
List (const Foam::one, T &&val)
List (const Foam::one, const Foam::zero)
List (const List< T > &a)
List (const UList< T > &a)
List (List< T > &a, bool reuse)
List (const UList< T > &list, const labelUList &indices)
template<unsigned N>
List (const UList< T > &list, const FixedList< label, N > &indices)
template<unsigned N>
List (const FixedList< T, N > &list)
List (const PtrList< T > &list)
List (const SLList< T > &list)
template<class Addr >
List (const IndirectListBase< T, Addr > &list)
List (std::initializer_list< T > list)
List (List< T > &&list)
template<int SizeMin>
List (DynamicList< T, SizeMin > &&list)
List (SLList< T > &&list)
List (Istream &is)
autoPtr< List< T > > clone () const
~List ()
void clear ()
void resize (const label len)
void resize (const label len, const T &val)
void resize_nocopy (const label len)
void setSize (const label n)
void setSize (const label n, const T &val)
void transfer (List< T > &list)
template<int SizeMin>
void transfer (DynamicList< T, SizeMin > &list)
T & newElmt (const label i)
template<class... Args>
T & emplace_back (Args &&... args)
void push_back (const T &val)
void push_back (T &&val)
void push_back (const UList< T > &list)
template<class Addr >
void push_back (const IndirectListBase< T, Addr > &list)
label push_uniq (const T &val)
void pop_back (label n=1)
void operator= (const UList< T > &a)
void operator= (const List< T > &list)
void operator= (const SLList< T > &list)
template<class Addr >
void operator= (const IndirectListBase< T, Addr > &list)
template<unsigned N>
void operator= (const FixedList< T, N > &list)
void operator= (std::initializer_list< T > list)
void operator= (const T &val)
void operator= (const Foam::zero)
void operator= (List< T > &&list)
template<int SizeMin>
void operator= (DynamicList< T, SizeMin > &&list)
void operator= (SLList< T > &&list)
Istream & readList (Istream &is)
void shallowCopy (const UList< T > &)=delete
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type set (const label i, bool val=true)
void append (const T &val)
void append (T &&val)
void append (const UList< T > &list)
template<class Addr >
void append (const IndirectListBase< T, Addr > &list)
label appendUniq (const T &val)
Istream & readList (Istream &is)
void resize (const label newLen)
Istream & readList (Istream &is)
Public Member Functions inherited from UList< T >
UList (const UList< T > &)=default
constexpr UList () noexcept
UList (T *__restrict__ v, const label len) noexcept
label fcIndex (const label i) const noexcept
label rcIndex (const label i) const noexcept
const T & fcValue (const label i) const
T & fcValue (const label i)
const T & rcValue (const label i) const
T & rcValue (const label i)
const T * cdata () const noexcept
T * data () noexcept
const char * cdata_bytes () const noexcept
char * data_bytes () noexcept
T & front ()
const T & front () const
T & back ()
const T & back () const
std::streamsize size_bytes () const noexcept
std::streamsize byteSize () const
void checkStart (const label start) const
void checkSize (const label size) const
void checkRange (const label start, const label len) const
void checkIndex (const label i) const
bool uniform () const
label find (const T &val, label pos=0) const
label rfind (const T &val, label pos=-1) const
bool contains (const T &val, label pos=0) const
void moveFirst (const label i)
void moveLast (const label i)
void swapFirst (const label i)
void swapLast (const label i)
void shallowCopy (const UList< T > &list)
void deepCopy (const UList< T > &list)
template<class Addr >
void deepCopy (const IndirectListBase< T, Addr > &list)
SubList< T > slice (const label pos, label len=-1)
const SubList< T > slice (const label pos, label len=-1) const
SubList< T > slice (const labelRange &range)
const SubList< T > slice (const labelRange &range) const
T & operator[] (const label i)
const T & operator[] (const label i) const
operator const Foam::List< T > & () const
void operator= (const T &val)
void operator= (const Foam::zero)
iterator begin () noexcept
iterator end () noexcept
iterator begin (const label i) noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
const_iterator begin () const noexcept
const_iterator end () const noexcept
const_iterator cbegin (const label i) const noexcept
const_iterator begin (const label i) const noexcept
reverse_iterator rbegin ()
reverse_iterator rend ()
const_reverse_iterator crbegin () const
const_reverse_iterator crend () const
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
bool empty () const noexcept
label size () const noexcept
void swap (UList< T > &list)
bool operator== (const UList< T > &a) const
bool operator!= (const UList< T > &a) const
bool operator< (const UList< T > &list) const
bool operator> (const UList< T > &a) const
bool operator<= (const UList< T > &a) const
bool operator>= (const UList< T > &a) const
Istream & readList (Istream &is)
void writeEntry (const word &keyword, Ostream &os) const
Ostream & writeList (Ostream &os, const label shortLen=0) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type test (const label i) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type get (const label i) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type unset (const label i)
T & first ()
const T & first () const
T & last ()
const T & last () const
bool found (const T &val, label pos=0) const
Istream & readList (Istream &is)
Ostream & writeList (Ostream &os, const label) const
const bool & operator[] (const label i) const
UPstream::commsStruct & operator[] (const label procID)
const UPstream::commsStruct & operator[] (const label procID) const
Foam::UPstream::commsStruct & operator[] (const label procID)
const Foam::UPstream::commsStruct & operator[] (const label procID) const
Ostream & writeList (Ostream &os, const label) const
Istream & readList (Istream &is)
Additional Inherited Members
Public Types inherited from IOstream
enum streamAccess : char { CLOSED = 0 , OPENED }
Public Types inherited from IOstreamOption
enum streamFormat : char { ASCII = 0 , BINARY }
enum compressionType : char { UNCOMPRESSED = 0 , COMPRESSED }
enum appendType : char { NON_APPEND = 0 , APPEND }
enum atomicType : char { NON_ATOMIC = 0 , ATOMIC }
Public Types inherited from List< T >
typedef SubList< T > subList
Public Types inherited from UList< T >
typedef T value_type
typedef T * pointer
typedef const T * const_pointer
typedef T & reference
typedef const T & const_reference
typedef T * iterator
typedef const T * const_iterator
typedef label size_type
typedef label difference_type
typedef std::reverse_iterator< iterator > reverse_iterator
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
Static Public Member Functions inherited from IOstream
static unsigned int defaultPrecision () noexcept
static unsigned int defaultPrecision (unsigned int prec) noexcept
Static Public Member Functions inherited from IOstreamOption
static streamFormat formatEnum (const word &formatName, const streamFormat deflt=streamFormat::ASCII)
static streamFormat formatEnum (const word &key, const dictionary &dict, const streamFormat deflt=streamFormat::ASCII)
static compressionType compressionEnum (const word &compName, const compressionType deflt=compressionType::UNCOMPRESSED)
static compressionType compressionEnum (const word &key, const dictionary &dict, const compressionType deflt=compressionType::UNCOMPRESSED)
Static Public Member Functions inherited from DynamicList< token >
static constexpr label min_size () noexcept
Static Public Member Functions inherited from List< T >
static const List< T > & null ()
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
static constexpr label max_size () noexcept
Static Public Attributes inherited from IOstream
static unsigned int precision_
Static Public Attributes inherited from IOstreamOption
static const Enum< streamFormat > formatNames
static const versionNumber currentVersion
Protected Member Functions inherited from IOstream
void setOpened () noexcept
void setClosed () noexcept
void setState (std::ios_base::iostate state) noexcept
void setGood () noexcept
Protected Member Functions inherited from UList< T >
void setAddressableSize (const label n) noexcept
void size (const label n)
void writeEntry (Ostream &os) const
labelRange validateRange (const labelRange &requestedRange) const
UList< T > & operator= (const UList< T > &)=delete
void writeEntry (Ostream &os) const
void writeEntry (Ostream &os) const
Protected Attributes inherited from Ostream
unsigned short indentSize_ = 4
unsigned short indentLevel_ = 0
Protected Attributes inherited from IOstream
std::ios_base::iostate ioState_
streamAccess openClosed_
unsigned char sizeofLabel_
unsigned char sizeofScalar_
label lineNumber_
Static Protected Attributes inherited from Ostream
static constexpr const unsigned short entryIndentation_ = 16
Static Protected Attributes inherited from IOstream
static fileName staticName_
Detailed Description
A simple output token stream that can be used to build token lists. Always UNCOMPRESSED.
Note
Appending single characters to token list is fragile.
Source files
OTstream.H
OTstream.C
Definition at line 52 of file OTstream.H.
Constructor & Destructor Documentation
OTstream() [1/3]
OTstream (IOstreamOption streamOpt = IOstreamOption()) inline explicit
Definition at line 62 of file OTstream.H.
References IOstream::setGood(), and IOstream::setOpened().
OTstream() [2/3]
OTstream (const OTstream & os) inline
Definition at line 72 of file OTstream.H.
References IOstream::setGood(), and IOstream::setOpened().
OTstream() [3/3]
OTstream (OTstream && os) inline
Definition at line 82 of file OTstream.H.
References IOstream::setGood(), and IOstream::setOpened().
~OTstream()
~OTstream () default
Member Function Documentation
tokens() [1/2]
const DynamicList< token > & tokens () const inline noexcept
Definition at line 99 of file OTstream.H.
Referenced by OTstream::write().
tokens() [2/2]
DynamicList< token > & tokens () inline noexcept
Definition at line 105 of file OTstream.H.
write() [1/10]
bool write (const token & tok) virtual
Implements Ostream.
Definition at line 27 of file OTstream.C.
References PtrList< T >::push_back(), and OTstream::tokens().
write() [2/10]
Foam::Ostream & write (const char c) virtual
Implements Ostream.
Definition at line 39 of file OTstream.C.
References PtrList< T >::push_back().
write() [3/10]
Foam::Ostream & write (const char * str) virtual
Implements Ostream.
Definition at line 51 of file OTstream.C.
References UPtrList< T >::size(), and write().
write() [4/10]
Foam::Ostream & write (const word & str) virtual
Implements Ostream.
Definition at line 70 of file OTstream.C.
References PtrList< T >::push_back().
write() [5/10]
Foam::Ostream & write (const string & str) virtual
Implements Ostream.
Definition at line 78 of file OTstream.C.
References PtrList< T >::push_back().
writeQuoted()
Foam::Ostream & writeQuoted (const std::string & str, const bool quoted = true) virtual
Implements Ostream.
Definition at line 86 of file OTstream.C.
References PtrList< T >::push_back().
write() [6/10]
Foam::Ostream & write (const int32_t val) virtual
Implements Ostream.
Definition at line 105 of file OTstream.C.
References PtrList< T >::push_back().
write() [7/10]
Foam::Ostream & write (const int64_t val) virtual
Implements Ostream.
Definition at line 113 of file OTstream.C.
References PtrList< T >::push_back().
write() [8/10]
Foam::Ostream & write (const float val) virtual
Implements Ostream.
Definition at line 121 of file OTstream.C.
References PtrList< T >::push_back().
write() [9/10]
Foam::Ostream & write (const double val) virtual
Implements Ostream.
Definition at line 129 of file OTstream.C.
References PtrList< T >::push_back().
write() [10/10]
Foam::Ostream & write (const char * data, std::streamsize count) virtual
Implements Ostream.
Definition at line 137 of file OTstream.C.
References Foam::abort(), IOstreamOption::BINARY, Foam::FatalError, FatalErrorInFunction, format(), and NotImplemented.
writeRaw()
Foam::Ostream & writeRaw (const char * data, std::streamsize count) virtual
Implements Ostream.
Definition at line 152 of file OTstream.C.
References NotImplemented.
beginRawWrite()
bool beginRawWrite (std::streamsize count) virtual
Implements Ostream.
Definition at line 167 of file OTstream.C.
References Foam::abort(), IOstreamOption::BINARY, Foam::FatalError, FatalErrorInFunction, format(), and NotImplemented.
endRawWrite()
virtual bool endRawWrite () inline virtual
Implements Ostream.
Definition at line 162 of file OTstream.H.
indent()
virtual void indent () inline virtual
Implements Ostream.
Definition at line 168 of file OTstream.H.
flags() [1/2]
virtual ios_base::fmtflags flags () const inline virtual
Implements IOstream.
Definition at line 175 of file OTstream.H.
flags() [2/2]
std::ios_base::fmtflags flags (const ios_base::fmtflags) inline virtual
Implements IOstream.
Definition at line 181 of file OTstream.H.
flush()
virtual void flush () inline virtual
Implements Ostream.
Definition at line 187 of file OTstream.H.
endl()
virtual void endl () inline virtual
Implements Ostream.
Definition at line 191 of file OTstream.H.
fill() [1/2]
virtual char fill () const inline virtual
Implements Ostream.
Definition at line 196 of file OTstream.H.
fill() [2/2]
virtual char fill (const char) inline virtual
Implements Ostream.
Definition at line 202 of file OTstream.H.
width() [1/2]
virtual int width () const inline virtual
Implements Ostream.
Definition at line 208 of file OTstream.H.
width() [2/2]
virtual int width (const int) inline virtual
Implements Ostream.
Definition at line 215 of file OTstream.H.
precision() [1/2]
virtual int precision () const inline virtual
Implements Ostream.
Definition at line 221 of file OTstream.H.
precision() [2/2]
virtual int precision (const int) inline virtual
Implements Ostream.
Definition at line 228 of file OTstream.H.
reset()
void reset () inline
Definition at line 237 of file OTstream.H.
References OTstream::rewind().
rewind()
virtual void rewind () inline virtual
Definition at line 243 of file OTstream.H.
References DynamicList< T, SizeMin >::clear(), IOstream::setGood(), and IOstream::setOpened().
Referenced by OTstream::reset().
print()
void print (Ostream & os) const virtual
Reimplemented from IOstream.
Definition at line 182 of file OTstream.C.
References Foam::name(), os(), and IOstream::print().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOstreams/Tstreams/OTstream.H
src/OpenFOAM/db/IOstreams/Tstreams/OTstream.C