OpenFOAM: nutkRoughWallFunctionFvPatchScalarField Class Reference
nutkRoughWallFunctionFvPatchScalarField Class Reference
Turbulence models » Boundary conditions » Wall functions
This boundary condition provides a wall-function for the turbulent viscosity (i.e. nut) when using wall functions for rough walls, based on the turbulent kinetic energy (i.e. k). The condition manipulates the wall roughness parameter (i.e. E) to account for roughness effects.
#include <nutkRoughWallFunctionFvPatchScalarField.H>
Public Member Functions
TypeName ("nutkRoughWallFunction")
nutkRoughWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
nutkRoughWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
nutkRoughWallFunctionFvPatchScalarField (const nutkRoughWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
nutkRoughWallFunctionFvPatchScalarField (const nutkRoughWallFunctionFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
nutkRoughWallFunctionFvPatchScalarField (const nutkRoughWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
scalarField & Ks ()
scalarField & Cs ()
virtual void autoMap (const fvPatchFieldMapper &)
virtual void rmap (const fvPatchScalarField &, const labelList &)
virtual void write (Ostream &) const
Public Member Functions inherited from nutkWallFunctionFvPatchScalarField
TypeName ("nutkWallFunction")
nutkWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
nutkWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
nutkWallFunctionFvPatchScalarField (const nutkWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
nutkWallFunctionFvPatchScalarField (const nutkWallFunctionFvPatchScalarField &)
nutkWallFunctionFvPatchScalarField (const nutkWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< scalarField > yPlus () const
Public Member Functions inherited from nutWallFunctionFvPatchScalarField
TypeName ("nutWallFunction")
nutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
nutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &)
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
const wallFunctionCoefficients & wallCoeffs () const noexcept
virtual void updateCoeffs ()
Protected Member Functions
virtual scalar fnRough (const scalar KsPlus, const scalar Cs) const
virtual tmp< scalarField > calcNut () const
void writeLocalEntries (Ostream &os) const
Protected Member Functions inherited from nutkWallFunctionFvPatchScalarField
void writeLocalEntries (Ostream &) const
Protected Member Functions inherited from nutWallFunctionFvPatchScalarField
virtual const volVectorField & U (const turbulenceModel &turb) const
virtual void checkType ()
void writeLocalEntries (Ostream &) const
Protected Attributes
scalarField Ks_
scalarField Cs_
Protected Attributes inherited from nutWallFunctionFvPatchScalarField
word UName_
wallFunctionCoefficients wallCoeffs_
Additional Inherited Members
Static Public Member Functions inherited from nutWallFunctionFvPatchScalarField
static const nutWallFunctionFvPatchScalarField & nutw (const turbulenceModel &turbModel, const label patchi)
Detailed Description
This boundary condition provides a wall-function for the turbulent viscosity (i.e. nut) when using wall functions for rough walls, based on the turbulent kinetic energy (i.e. k). The condition manipulates the wall roughness parameter (i.e. E) to account for roughness effects.
Parameter ranges:
roughness height (i.e. Ks)= sand-grain roughness (0 for smooth walls)
roughness constant (i.e. Cs) = 0.5-1.0
Usage
Example of the boundary condition specification:
<patchName>
{
    // Mandatory entries
    type            nutkRoughWallFunction;
    Ks              uniform 0;
    Cs              uniform 0.5;
    // Inherited entries
    ...
}
where the entries mean:
Property Description Type Reqd Dflt
type Type name: nutkRoughWallFunction word yes -
Ks Sand-grain roughness height scalarField yes -
Cs Roughness constant scalarField yes -
The inherited entries are elaborated in:
nutkWallFunctionFvPatchScalarField.H
Source files
nutkRoughWallFunctionFvPatchScalarField.H
nutkRoughWallFunctionFvPatchScalarField.C
Definition at line 108 of file nutkRoughWallFunctionFvPatchScalarField.H.
Constructor & Destructor Documentation
nutkRoughWallFunctionFvPatchScalarField() [1/5]
nutkRoughWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 135 of file nutkRoughWallFunctionFvPatchScalarField.C.
nutkRoughWallFunctionFvPatchScalarField() [2/5]
nutkRoughWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 163 of file nutkRoughWallFunctionFvPatchScalarField.C.
nutkRoughWallFunctionFvPatchScalarField() [3/5]
nutkRoughWallFunctionFvPatchScalarField (const nutkRoughWallFunctionFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 148 of file nutkRoughWallFunctionFvPatchScalarField.C.
nutkRoughWallFunctionFvPatchScalarField() [4/5]
nutkRoughWallFunctionFvPatchScalarField (const nutkRoughWallFunctionFvPatchScalarField & rwfpsf)
Definition at line 177 of file nutkRoughWallFunctionFvPatchScalarField.C.
nutkRoughWallFunctionFvPatchScalarField() [5/5]
nutkRoughWallFunctionFvPatchScalarField (const nutkRoughWallFunctionFvPatchScalarField & rwfpsf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 189 of file nutkRoughWallFunctionFvPatchScalarField.C.
Member Function Documentation
fnRough()
Foam::scalar fnRough (const scalar KsPlus, const scalar Cs) const protected virtual
Definition at line 30 of file nutkRoughWallFunctionFvPatchScalarField.C.
References nutkRoughWallFunctionFvPatchScalarField::Cs(), Foam::log(), Foam::pow(), and Foam::sin().
calcNut()
Foam::tmp< Foam::scalarField > calcNut () const protected virtual
Reimplemented from nutkWallFunctionFvPatchScalarField.
Definition at line 51 of file nutkRoughWallFunctionFvPatchScalarField.C.
References e, Foam::endl(), forAll, IOobject::groupName(), Foam::Info, k, Foam::log(), Foam::max(), Foam::min(), tmp< T >::New(), Foam::pow025(), turbulenceModel::propertiesName, Foam::sqrt(), y, and yPlus.
writeLocalEntries()
void writeLocalEntries (Ostream & os) const protected
Definition at line 123 of file nutkRoughWallFunctionFvPatchScalarField.C.
References os().
TypeName()
TypeName ("nutkRoughWallFunction")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Reimplemented from nutkWallFunctionFvPatchScalarField.
Definition at line 176 of file nutkRoughWallFunctionFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Reimplemented from nutkWallFunctionFvPatchScalarField.
Definition at line 192 of file nutkRoughWallFunctionFvPatchScalarField.H.
Ks()
scalarField & Ks () inline
Definition at line 209 of file nutkRoughWallFunctionFvPatchScalarField.H.
References nutkRoughWallFunctionFvPatchScalarField::Ks_.
Cs()
scalarField & Cs () inline
Definition at line 215 of file nutkRoughWallFunctionFvPatchScalarField.H.
References nutkRoughWallFunctionFvPatchScalarField::Cs_.
Referenced by nutkRoughWallFunctionFvPatchScalarField::fnRough().
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Definition at line 204 of file nutkRoughWallFunctionFvPatchScalarField.C.
rmap()
void rmap (const fvPatchScalarField & ptf, const labelList & addr) virtual
Definition at line 215 of file nutkRoughWallFunctionFvPatchScalarField.C.
write()
void write (Ostream & os) const virtual
Reimplemented from nutkWallFunctionFvPatchScalarField.
Definition at line 231 of file nutkRoughWallFunctionFvPatchScalarField.C.
References os(), nutWallFunctionFvPatchScalarField::write(), and fvPatchField< Type >::writeValueEntry().
Member Data Documentation
Ks_
scalarField Ks_ protected
Definition at line 117 of file nutkRoughWallFunctionFvPatchScalarField.H.
Referenced by nutkRoughWallFunctionFvPatchScalarField::Ks().
Cs_
scalarField Cs_ protected
Definition at line 120 of file nutkRoughWallFunctionFvPatchScalarField.H.
Referenced by nutkRoughWallFunctionFvPatchScalarField::Cs().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/derivedFvPatchFields/wallFunctions/nutWallFunctions/nutkRoughWallFunction/nutkRoughWallFunctionFvPatchScalarField.H
src/TurbulenceModels/turbulenceModels/derivedFvPatchFields/wallFunctions/nutWallFunctions/nutkRoughWallFunction/nutkRoughWallFunctionFvPatchScalarField.C