OpenFOAM: sixDoFRigidBodyMotion Class Reference
sixDoFRigidBodyMotion Class Reference
Six degree of freedom motion for a rigid body.
#include <sixDoFRigidBodyMotion.H>
Public Member Functions
sixDoFRigidBodyMotion (const Time &)
sixDoFRigidBodyMotion (const dictionary &dict, const dictionary &stateDict, const Time &time)
sixDoFRigidBodyMotion (const sixDoFRigidBodyMotion &)
~sixDoFRigidBodyMotion ()
scalar mass () const
const diagTensor & momentOfInertia () const
const sixDoFRigidBodyMotionState & state () const
const point & centreOfRotation () const
const point & initialCentreOfMass () const
point centreOfMass () const
const tensor & orientation () const
vector omega () const
const vector & v () const
vector & v ()
vector momentArm () const
bool report () const
bool updateConstraints () const
const Time & time () const
void newTime ()
point & centreOfRotation ()
void addRestraints (const dictionary &dict)
void addConstraints (const dictionary &dict)
void update (bool firstIter, const vector &fGlobal, const vector &tauGlobal, scalar deltaT, scalar deltaT0)
void status () const
point velocity (const point &pt) const
point transform (const point &initialPoints) const
tmp< pointField > transform (const pointField &initialPoints) const
tmp< pointField > transform (const pointField &initialPoints, const scalarField &scale) const
void write (Ostream &) const
bool read (const dictionary &dict)
Friends
class sixDoFSolver
Detailed Description
Six degree of freedom motion for a rigid body.
Angular momentum stored in body fixed reference frame. Reference orientation of the body (where Q = I) must align with the cartesian axes such that the Inertia tensor is in principle component form. Can add restraints (e.g. a spring) and constraints (e.g. motion may only be on a plane).
The time-integrator for the motion is run-time selectable with options for symplectic (explicit), Crank-Nicolson and Newmark schemes.
Source files
sixDoFRigidBodyMotion.H
sixDoFRigidBodyMotionI.H
sixDoFRigidBodyMotion.C
sixDoFRigidBodyMotionIO.C
Definition at line 65 of file sixDoFRigidBodyMotion.H.
Constructor & Destructor Documentation
sixDoFRigidBodyMotion() [1/3]
sixDoFRigidBodyMotion (const Time & time)
Definition at line 69 of file sixDoFRigidBodyMotion.C.
sixDoFRigidBodyMotion() [2/3]
sixDoFRigidBodyMotion (const dictionary & dict, const dictionary & stateDict, const Time & time)
Definition at line 91 of file sixDoFRigidBodyMotion.C.
References sixDoFRigidBodyMotion::addConstraints(), sixDoFRigidBodyMotion::addRestraints(), sixDoFRigidBodyMotionState::centreOfRotation(), Foam::diag(), dict, dictionary::found(), Foam::I, Foam::magSqr(), R, and Foam::sqr().
sixDoFRigidBodyMotion() [3/3]
sixDoFRigidBodyMotion (const sixDoFRigidBodyMotion & sDoFRBM)
Definition at line 156 of file sixDoFRigidBodyMotion.C.
~sixDoFRigidBodyMotion()
~sixDoFRigidBodyMotion ()
Definition at line 183 of file sixDoFRigidBodyMotion.C.
Member Function Documentation
mass()
Foam::scalar mass () const inline
Definition at line 204 of file sixDoFRigidBodyMotionI.H.
Referenced by linearSpringDamper::restrain(), softWall::restrain(), sixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs(), and uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs().
momentOfInertia()
const Foam::diagTensor & momentOfInertia () const inline
Definition at line 211 of file sixDoFRigidBodyMotionI.H.
state()
const Foam::sixDoFRigidBodyMotionState & state () const inline
Definition at line 218 of file sixDoFRigidBodyMotionI.H.
centreOfRotation() [1/2]
const Foam::point & centreOfRotation () const inline
Definition at line 224 of file sixDoFRigidBodyMotionI.H.
Referenced by linearAxialAngularSpring::restrain(), sphericalAngularSpring::restrain(), tabulatedAxialAngularSpring::restrain(), sixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs(), and sixDoFRigidBodyState::write().
initialCentreOfMass()
const Foam::point & initialCentreOfMass () const inline
Definition at line 231 of file sixDoFRigidBodyMotionI.H.
centreOfMass()
Foam::point centreOfMass () const inline
Definition at line 237 of file sixDoFRigidBodyMotionI.H.
References Foam::transform().
Referenced by sixDoFRigidBodyState::write().
orientation()
const Foam::tensor & orientation () const inline
Definition at line 250 of file sixDoFRigidBodyMotionI.H.
Referenced by linearAxialAngularSpring::restrain(), sphericalAngularSpring::restrain(), tabulatedAxialAngularSpring::restrain(), and sixDoFRigidBodyState::write().
omega()
Foam::vector omega () const inline
Definition at line 256 of file sixDoFRigidBodyMotionI.H.
References Foam::inv().
Referenced by linearAxialAngularSpring::restrain(), sphericalAngularDamper::restrain(), sphericalAngularSpring::restrain(), tabulatedAxialAngularSpring::restrain(), and sixDoFRigidBodyState::write().
v() [1/2]
const Foam::vector & v () const inline
Definition at line 136 of file sixDoFRigidBodyMotionI.H.
Referenced by linearDamper::restrain(), and sixDoFRigidBodyState::write().
v() [2/2]
Foam::vector & v () inline
Definition at line 178 of file sixDoFRigidBodyMotionI.H.
momentArm()
Foam::vector momentArm () const inline
Definition at line 243 of file sixDoFRigidBodyMotionI.H.
Referenced by sixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs().
report()
bool report () const inline
Definition at line 266 of file sixDoFRigidBodyMotionI.H.
Referenced by linearAxialAngularSpring::restrain(), linearDamper::restrain(), linearSpring::restrain(), linearSpringDamper::restrain(), softWall::restrain(), sphericalAngularDamper::restrain(), sphericalAngularSpring::restrain(), and tabulatedAxialAngularSpring::restrain().
updateConstraints()
bool updateConstraints () const inline
Definition at line 271 of file sixDoFRigidBodyMotionI.H.
time()
const Foam::Time & time () const inline
Definition at line 261 of file sixDoFRigidBodyMotionI.H.
Referenced by linearSpringDamper::restrain().
newTime()
void newTime () inline
Definition at line 277 of file sixDoFRigidBodyMotionI.H.
Referenced by sixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs(), and uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs().
centreOfRotation() [2/2]
Foam::point & centreOfRotation () inline
Definition at line 283 of file sixDoFRigidBodyMotionI.H.
addRestraints()
void addRestraints (const dictionary & dict)
Definition at line 189 of file sixDoFRigidBodyMotion.C.
References dict, dictionary::found(), sixDoFRigidBodyMotionRestraint::New(), PtrList< T >::set(), PtrList< T >::setSize(), UPtrList< T >::size(), and dictionary::subDict().
Referenced by sixDoFRigidBodyMotion::read(), and sixDoFRigidBodyMotion::sixDoFRigidBodyMotion().
addConstraints()
void addConstraints (const dictionary & dict)
Definition at line 223 of file sixDoFRigidBodyMotion.C.
References dict, Foam::endl(), dictionary::found(), Foam::Info, sixDoFRigidBodyMotionConstraint::New(), Foam::nl, PtrList< T >::set(), PtrList< T >::setSize(), UPtrList< T >::size(), and dictionary::subDict().
Referenced by sixDoFRigidBodyMotion::read(), and sixDoFRigidBodyMotion::sixDoFRigidBodyMotion().
update()
void update (bool firstIter, const vector & fGlobal, const vector & tauGlobal, scalar deltaT, scalar deltaT0)
Definition at line 328 of file sixDoFRigidBodyMotion.C.
References Pstream::broadcast(), and UPstream::master().
Referenced by sixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs(), and uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs().
status()
void status () const
Definition at line 351 of file sixDoFRigidBodyMotion.C.
References Foam::endl(), Foam::Info, and Foam::nl.
velocity()
Foam::point velocity (const point & pt) const inline
Definition at line 289 of file sixDoFRigidBodyMotionI.H.
Referenced by linearSpring::restrain(), linearSpringDamper::restrain(), and softWall::restrain().
transform() [1/3]
Foam::point transform (const point & initialPoints) const inline
Definition at line 298 of file sixDoFRigidBodyMotionI.H.
Referenced by linearSpring::restrain(), linearSpringDamper::restrain(), softWall::restrain(), sixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs(), and uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs().
transform() [2/3]
Foam::tmp< Foam::pointField > transform (const pointField & initialPoints) const
Definition at line 363 of file sixDoFRigidBodyMotion.C.
transform() [3/3]
Foam::tmp< Foam::pointField > transform (const pointField & initialPoints, const scalarField & scale) const
Definition at line 376 of file sixDoFRigidBodyMotion.C.
References forAll, septernion::I, points, s(), Foam::slerp(), T, and Foam::transform().
write()
void write (Ostream & os) const
Definition at line 47 of file sixDoFRigidBodyMotionIO.C.
References Ostream::beginBlock(), Ostream::endBlock(), forAll, Foam::indent(), Foam::name(), os(), Foam::type(), Ostream::write(), and Ostream::writeEntry().
Referenced by sixDoFRigidBodyDisplacementPointPatchVectorField::write(), and uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField::write().
read()
bool read (const dictionary & dict)
Definition at line 28 of file sixDoFRigidBodyMotionIO.C.
References sixDoFRigidBodyMotion::addConstraints(), sixDoFRigidBodyMotion::addRestraints(), PtrList< T >::clear(), and dict.
Friends And Related Symbol Documentation
sixDoFSolver
friend class sixDoFSolver friend
Definition at line 67 of file sixDoFRigidBodyMotion.H.
The documentation for this class was generated from the following files:
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion.H
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion.C
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/sixDoFRigidBodyMotionI.H
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/sixDoFRigidBodyMotionIO.C