OpenFOAM: MultiInteraction< CloudType > Class Template Reference
MultiInteraction< CloudType > Class Template Reference
Lagrangian particle models » Submodels » Kinematic » Patch interaction
Runs multiple patch interaction models in turn. Takes dictionary where all the subdictionaries are the interaction models.
#include <MultiInteraction.H>
Public Member Functions
TypeName ("multiInteraction")
MultiInteraction (const dictionary &dict, CloudType &cloud)
MultiInteraction (const MultiInteraction< CloudType > &pim)
virtual autoPtr< PatchInteractionModel< CloudType > > clone () const
virtual ~MultiInteraction ()=default
virtual bool active () const
virtual bool correct (typename CloudType::parcelType &p, const polyPatch &pp, bool &keepParticle)
virtual void postEvolve ()
virtual void info ()
Public Member Functions inherited from PatchInteractionModel< CloudType >
TypeName ("patchInteractionModel")
declareRunTimeSelectionTable (autoPtr, PatchInteractionModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
PatchInteractionModel (CloudType &owner)
PatchInteractionModel (const dictionary &dict, CloudType &owner, const word &type)
PatchInteractionModel (const PatchInteractionModel< CloudType > &pim)
virtual ~PatchInteractionModel ()=default
const word & UName () const
const scalar & Urmax () const
virtual void addToEscapedParcels (const scalar mass)
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
virtual ~CloudSubModelBase ()=default
const CloudType & owner () const
virtual bool writeTime () const
virtual fileName localPath () const
CloudType & owner ()
virtual void write (Ostream &os) const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
subModelBase (const subModelBase &smb)
virtual ~subModelBase ()=default
const word & modelName () const
const dictionary & dict () const
const word & baseName () const
const word & modelType () const
const dictionary & coeffDict () const
const dictionary & properties () const
virtual bool defaultCoeffs (const bool printMsg) const
virtual void cacheFields (const bool store)
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
bool getModelDict (const word &entryName, dictionary &dict) const
template<class Type >
bool getModelProperty (const word &entryName, Type &value) const
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Public Member Functions inherited from writeFile
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name="undefined", const bool writeToFile=true)
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name, const dictionary &dict, const bool writeToFile=true)
writeFile (const writeFile &wf)
virtual ~writeFile ()=default
virtual OFstream & file ()
virtual bool writeToFile () const
virtual bool canWriteToFile () const
virtual bool canResetFile () const
virtual bool canWriteHeader () const
virtual label charWidth () const
virtual void writeCommented (Ostream &os, const string &str) const
virtual void writeTabbed (Ostream &os, const string &str) const
virtual void writeHeader (Ostream &os, const string &str) const
virtual void writeCurrentTime (Ostream &os) const
virtual void writeBreak (Ostream &os) const
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
template<class Type >
void writeValue (Ostream &os, const Type &val) const
Additional Inherited Members
Public Types inherited from PatchInteractionModel< CloudType >
enum interactionType {
itNone , itRebound , itStick , itEscape ,
itOther
}
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Static Public Member Functions inherited from PatchInteractionModel< CloudType >
static autoPtr< PatchInteractionModel< CloudType > > New (const dictionary &dict, CloudType &owner)
static word interactionTypeToWord (const interactionType &itEnum)
static interactionType wordToInteractionType (const word &itWord)
Public Attributes inherited from subModelBase
bool log
Static Public Attributes inherited from PatchInteractionModel< CloudType >
static wordList interactionTypeNames_
Static Public Attributes inherited from writeFile
static label addChars = 8
Protected Member Functions inherited from PatchInteractionModel< CloudType >
virtual void writeFileHeader (Ostream &os)
Protected Member Functions inherited from subModelBase
bool inLine () const
Protected Member Functions inherited from writeFile
void initStream (Ostream &os) const
fileName baseFileDir () const
fileName baseTimeDir () const
fileName filePath (const fileName &fName) const
virtual autoPtr< OFstream > newFile (const fileName &fName) const
virtual autoPtr< OFstream > newFileAtTime (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > newFileAtStartTime (const word &name) const
virtual void resetFile (const word &name)
Omanip< int > valueWidth (const label offset=0) const
void operator= (const writeFile &)=delete
virtual autoPtr< OFstream > createFile (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > createFile (const word &name) const
Protected Attributes inherited from PatchInteractionModel< CloudType >
const word UName_
label escapedParcels_
scalar escapedMass_
scalar Urmax_
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Protected Attributes inherited from subModelBase
const word modelName_
dictionary & properties_
const dictionary dict_
const word baseName_
const word modelType_
const dictionary coeffDict_
Protected Attributes inherited from writeFile
const objectRegistry & fileObr_
const fileName prefix_
word fileName_
autoPtr< OFstream > filePtr_
label writePrecision_
bool writeToFile_
bool updateHeader_
bool writtenHeader_
bool useUserTime_
scalar startTime_
Detailed Description
template<class CloudType>
class Foam::MultiInteraction< CloudType >
Runs multiple patch interaction models in turn. Takes dictionary where all the subdictionaries are the interaction models.
Exit upon first successful interaction or continue doing other models. Returned interaction status will be true if there has been any interaction (so logical or) oneInteractionOnly true;
model1 { patchInteractionModel coincidentBaffleInteraction; coincidentBaffleInteractionCoeffs { coincidentPatches ((pipetteWall_A pipetteCyclic_half0) (pipetteWall_B pipetteCyclic_half1)); } } model2 { patchInteractionModel localInteraction; localInteractionCoeffs { patches (cWall { type rebound; } pipetteWall_A { type rebound; } pipetteWall_B { type rebound; }); } }
Definition at line 86 of file MultiInteraction.H.
Constructor & Destructor Documentation
MultiInteraction() [1/2]
template<class CloudType > MultiInteraction (const dictionary & dict, CloudType & cloud)
Definition at line 82 of file MultiInteraction.C.
References subModelBase::coeffDict().
MultiInteraction() [2/2]
template<class CloudType > MultiInteraction (const MultiInteraction< CloudType > & pim)
Definition at line 95 of file MultiInteraction.C.
~MultiInteraction()
template<class CloudType > virtual ~MultiInteraction () virtual default
Member Function Documentation
TypeName()
template<class CloudType > TypeName ("multiInteraction")
clone()
template<class CloudType > virtual autoPtr< PatchInteractionModel< CloudType > > clone () const inline virtual
Implements PatchInteractionModel< CloudType >.
Definition at line 118 of file MultiInteraction.H.
active()
template<class CloudType > bool active () const virtual
Reimplemented from subModelBase.
Definition at line 109 of file MultiInteraction.C.
References forAll.
correct()
template<class CloudType > bool correct (typename CloudType::parcelType & p, const polyPatch & pp, bool & keepParticle) virtual
Implements PatchInteractionModel< CloudType >.
Definition at line 123 of file MultiInteraction.C.
References forAll, p, and pp().
postEvolve()
template<class CloudType > void postEvolve () virtual
Reimplemented from PatchInteractionModel< CloudType >.
Definition at line 173 of file MultiInteraction.C.
info()
template<class CloudType > void info () virtual
Reimplemented from PatchInteractionModel< CloudType >.
Definition at line 183 of file MultiInteraction.C.
References Foam::endl(), PatchInteractionModel< CloudType >::info(), IOstream::info(), and Log_.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/Kinematic/PatchInteractionModel/MultiInteraction/MultiInteraction.H
src/lagrangian/intermediate/submodels/Kinematic/PatchInteractionModel/MultiInteraction/MultiInteraction.C