OpenFOAM: BreakupModel< CloudType > Class Template Reference
BreakupModel< CloudType > Class Template Reference abstract
Lagrangian particle models » Submodels » Reacting » Breakup
Templated break-up model class.
#include <BreakupModel.H>
Public Member Functions
TypeName ("breakupModel")
declareRunTimeSelectionTable (autoPtr, BreakupModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
BreakupModel (CloudType &owner)
BreakupModel (const dictionary &dict, CloudType &owner, const word &type, bool solveOscillationEq=false)
BreakupModel (const BreakupModel< CloudType > &bum)
virtual autoPtr< BreakupModel< CloudType > > clone () const =0
virtual ~BreakupModel ()
bool solveOscillationEq () const
const scalar & y0 () const
const scalar & yDot0 () const
const scalar & TABComega () const
const scalar & TABCmu () const
const scalar & TABtwoWeCrit () const
virtual bool update (const scalar dt, const vector &g, scalar &d, scalar &tc, scalar &ms, scalar &nParticle, scalar &KHindex, scalar &y, scalar &yDot, const scalar d0, const scalar rho, const scalar mu, const scalar sigma, const vector &U, const scalar rhoc, const scalar muc, const vector &Urel, const scalar Urmag, const scalar tMom, scalar &dChild, scalar &massChild)=0
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
virtual ~CloudSubModelBase ()=default
const CloudType & owner () const
virtual bool writeTime () const
virtual fileName localPath () const
CloudType & owner ()
virtual void info ()
virtual void write (Ostream &os) const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
subModelBase (const subModelBase &smb)
virtual ~subModelBase ()=default
const word & modelName () const
const dictionary & dict () const
const word & baseName () const
const word & modelType () const
const dictionary & coeffDict () const
const dictionary & properties () const
virtual bool defaultCoeffs (const bool printMsg) const
virtual bool active () const
virtual void cacheFields (const bool store)
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
bool getModelDict (const word &entryName, dictionary &dict) const
template<class Type >
bool getModelProperty (const word &entryName, Type &value) const
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Static Public Member Functions
static autoPtr< BreakupModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Protected Attributes
bool solveOscillationEq_
scalar y0_
scalar yDot0_
scalar TABComega_
scalar TABCmu_
scalar TABtwoWeCrit_
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Protected Attributes inherited from subModelBase
const word modelName_
dictionary & properties_
const dictionary dict_
const word baseName_
const word modelType_
const dictionary coeffDict_
Additional Inherited Members
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Public Attributes inherited from subModelBase
bool log
Protected Member Functions inherited from subModelBase
bool inLine () const
Detailed Description
template<class CloudType>
class Foam::BreakupModel< CloudType >
Templated break-up model class.
Source files
BreakupModel.H
BreakupModel.C
BreakupModelNew.C
Definition at line 54 of file BreakupModel.H.
Constructor & Destructor Documentation
BreakupModel() [1/3]
template<class CloudType > BreakupModel (CloudType & owner)
Definition at line 27 of file BreakupModel.C.
BreakupModel() [2/3]
template<class CloudType > BreakupModel (const dictionary & dict, CloudType & owner, const word & type, bool solveOscillationEq = false)
Definition at line 59 of file BreakupModel.C.
References subModelBase::dict(), dictionary::get(), dictionary::readEntry(), BreakupModel< CloudType >::solveOscillationEq_, BreakupModel< CloudType >::TABCmu_, BreakupModel< CloudType >::TABComega_, and BreakupModel< CloudType >::TABtwoWeCrit_.
BreakupModel() [3/3]
template<class CloudType > BreakupModel (const BreakupModel< CloudType > & bum)
Definition at line 43 of file BreakupModel.C.
~BreakupModel()
template<class CloudType > ~BreakupModel () virtual
Definition at line 90 of file BreakupModel.C.
Member Function Documentation
TypeName()
template<class CloudType > TypeName ("breakupModel")
declareRunTimeSelectionTable()
template<class CloudType > declareRunTimeSelectionTable (autoPtr , BreakupModel< CloudType > , dictionary , (const dictionary &dict, CloudType &owner) , (dict, owner))
clone()
template<class CloudType > virtual autoPtr< BreakupModel< CloudType > > clone () const pure virtual
Implemented in ETAB< CloudType >, NoBreakup< CloudType >, PilchErdman< CloudType >, ReitzDiwakar< CloudType >, ReitzKHRT< CloudType >, SHF< CloudType >, and TAB< CloudType >.
New()
template<class CloudType > Foam::autoPtr< Foam::BreakupModel< CloudType > > New (const dictionary & dict, CloudType & owner) static
Definition at line 28 of file BreakupModelNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, Foam::Info, and PtrList< T >::PtrList().
solveOscillationEq()
template<class CloudType > bool solveOscillationEq () const inline
Definition at line 127 of file BreakupModel.H.
References BreakupModel< CloudType >::solveOscillationEq_.
y0()
template<class CloudType > const scalar & y0 () const inline
Definition at line 132 of file BreakupModel.H.
References BreakupModel< CloudType >::y0_.
yDot0()
template<class CloudType > const scalar & yDot0 () const inline
Definition at line 137 of file BreakupModel.H.
References BreakupModel< CloudType >::yDot0_.
TABComega()
template<class CloudType > const scalar & TABComega () const inline
Definition at line 142 of file BreakupModel.H.
References BreakupModel< CloudType >::TABComega_.
TABCmu()
template<class CloudType > const scalar & TABCmu () const inline
Definition at line 147 of file BreakupModel.H.
References BreakupModel< CloudType >::TABCmu_.
TABtwoWeCrit()
template<class CloudType > const scalar & TABtwoWeCrit () const inline
Definition at line 152 of file BreakupModel.H.
References BreakupModel< CloudType >::TABtwoWeCrit_.
update()
template<class CloudType > virtual bool update (const scalar dt, const vector & g, scalar & d, scalar & tc, scalar & ms, scalar & nParticle, scalar & KHindex, scalar & y, scalar & yDot, const scalar d0, const scalar rho, const scalar mu, const scalar sigma, const vector & U, const scalar rhoc, const scalar muc, const vector & Urel, const scalar Urmag, const scalar tMom, scalar & dChild, scalar & massChild) pure virtual
Implemented in ETAB< CloudType >, NoBreakup< CloudType >, PilchErdman< CloudType >, ReitzDiwakar< CloudType >, ReitzKHRT< CloudType >, SHF< CloudType >, and TAB< CloudType >.
Member Data Documentation
solveOscillationEq_
template<class CloudType > bool solveOscillationEq_ protected
Definition at line 63 of file BreakupModel.H.
Referenced by BreakupModel< CloudType >::BreakupModel(), and BreakupModel< CloudType >::solveOscillationEq().
y0_
template<class CloudType > scalar y0_ protected
Definition at line 65 of file BreakupModel.H.
Referenced by BreakupModel< CloudType >::y0().
yDot0_
template<class CloudType > scalar yDot0_ protected
Definition at line 66 of file BreakupModel.H.
Referenced by BreakupModel< CloudType >::yDot0().
TABComega_
template<class CloudType > scalar TABComega_ protected
Definition at line 68 of file BreakupModel.H.
Referenced by BreakupModel< CloudType >::BreakupModel(), and BreakupModel< CloudType >::TABComega().
TABCmu_
template<class CloudType > scalar TABCmu_ protected
Definition at line 69 of file BreakupModel.H.
Referenced by BreakupModel< CloudType >::BreakupModel(), and BreakupModel< CloudType >::TABCmu().
TABtwoWeCrit_
template<class CloudType > scalar TABtwoWeCrit_ protected
Definition at line 70 of file BreakupModel.H.
Referenced by BreakupModel< CloudType >::BreakupModel(), and BreakupModel< CloudType >::TABtwoWeCrit().
The documentation for this class was generated from the following files:
src/lagrangian/spray/clouds/Templates/SprayCloud/SprayCloud.H
src/lagrangian/spray/submodels/BreakupModel/BreakupModel/BreakupModel.H
src/lagrangian/spray/submodels/BreakupModel/BreakupModel/BreakupModel.C
src/lagrangian/spray/submodels/BreakupModel/BreakupModel/BreakupModelNew.C