OpenFOAM: SRFFreestreamVelocityFvPatchVectorField Class Reference
SRFFreestreamVelocityFvPatchVectorField Class Reference
Freestream velocity condition to be used in conjunction with the single rotating frame (SRF) model (see: SRFModel class)
#include <SRFFreestreamVelocityFvPatchVectorField.H>
Public Member Functions
TypeName ("SRFFreestreamVelocity")
SRFFreestreamVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
SRFFreestreamVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
SRFFreestreamVelocityFvPatchVectorField (const SRFFreestreamVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
SRFFreestreamVelocityFvPatchVectorField (const SRFFreestreamVelocityFvPatchVectorField &)
virtual tmp< fvPatchVectorField > clone () const
SRFFreestreamVelocityFvPatchVectorField (const SRFFreestreamVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
const vector & UInf () const
vector & UInf ()
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
Freestream velocity condition to be used in conjunction with the single rotating frame (SRF) model (see: SRFModel class)
Given the free stream velocity in the absolute frame, the condition applies the appropriate rotation transformation in time and space to determine the local velocity using:
where
= patch velocity [m/s]
= free stream velocity in the absolute frame [m/s]
= swept angle [rad]
= axis direction of the SRF
= SRF velocity of the patch [m/s]
Usage
Property Description Required Default value
UInf freestream velocity yes
relative UInf relative to the SRF? no
Example of the boundary condition specification:
    <patchName>
    {
        type            SRFFreestreamVelocity;
        UInf            uniform (0 0 0);
        relative        no;
        value           uniform (0 0 0);    // initial value
    }
See also
Foam::freestreamFvPatchField Foam::SRFVelocityFvPatchVectorField
Source files
SRFFreestreamVelocityFvPatchVectorField.H
SRFFreestreamVelocityFvPatchVectorField.C
Definition at line 124 of file SRFFreestreamVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
SRFFreestreamVelocityFvPatchVectorField() [1/5]
SRFFreestreamVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Definition at line 32 of file SRFFreestreamVelocityFvPatchVectorField.C.
SRFFreestreamVelocityFvPatchVectorField() [2/5]
SRFFreestreamVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Definition at line 60 of file SRFFreestreamVelocityFvPatchVectorField.C.
References dict, and IOobjectOption::MUST_READ.
SRFFreestreamVelocityFvPatchVectorField() [3/5]
SRFFreestreamVelocityFvPatchVectorField (const SRFFreestreamVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 45 of file SRFFreestreamVelocityFvPatchVectorField.C.
SRFFreestreamVelocityFvPatchVectorField() [4/5]
SRFFreestreamVelocityFvPatchVectorField (const SRFFreestreamVelocityFvPatchVectorField & srfvpvf)
Definition at line 77 of file SRFFreestreamVelocityFvPatchVectorField.C.
SRFFreestreamVelocityFvPatchVectorField() [5/5]
SRFFreestreamVelocityFvPatchVectorField (const SRFFreestreamVelocityFvPatchVectorField & srfvpvf, const DimensionedField< vector, volMesh > & iF)
Definition at line 89 of file SRFFreestreamVelocityFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("SRFFreestreamVelocity")
clone() [1/2]
virtual tmp< fvPatchVectorField > clone () const inline virtual
Definition at line 177 of file SRFFreestreamVelocityFvPatchVectorField.H.
clone() [2/2]
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Definition at line 193 of file SRFFreestreamVelocityFvPatchVectorField.H.
UInf() [1/2]
const vector & UInf () const inline
Definition at line 210 of file SRFFreestreamVelocityFvPatchVectorField.H.
UInf() [2/2]
vector & UInf () inline
Definition at line 216 of file SRFFreestreamVelocityFvPatchVectorField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 104 of file SRFFreestreamVelocityFvPatchVectorField.C.
References Foam::cos(), Foam::mag(), mesh, Foam::name(), Foam::neg(), Foam::sin(), and fvPatchField< Type >::updateCoeffs().
write()
void write (Ostream & os) const virtual
Definition at line 153 of file SRFFreestreamVelocityFvPatchVectorField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntry(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/finiteVolume/cfdTools/general/SRF/derivedFvPatchFields/SRFFreestreamVelocityFvPatchVectorField/SRFFreestreamVelocityFvPatchVectorField.H
src/finiteVolume/cfdTools/general/SRF/derivedFvPatchFields/SRFFreestreamVelocityFvPatchVectorField/SRFFreestreamVelocityFvPatchVectorField.C