OpenFOAM: TwoResistanceHeatTransferPhaseSystem< BasePhaseSystem > Class Template Reference
TwoResistanceHeatTransferPhaseSystem< BasePhaseSystem > Class Template Reference
Class which models interfacial heat transfer between a number of phases. Two heat transfer models are stored at each interface, one for each phase. This permits definition of an interface temperature with which heat transfer occurs. It also allows derived systems to define other thermodynamic properties at the interface and therefore represent phase changes.
#include <TwoResistanceHeatTransferPhaseSystem.H>
Public Member Functions
TwoResistanceHeatTransferPhaseSystem (const fvMesh &)
virtual ~TwoResistanceHeatTransferPhaseSystem ()
virtual autoPtr< phaseSystem::heatTransferTable > heatTransfer () const
virtual void correctEnergyTransport ()
virtual void correctInterfaceThermo ()
virtual bool read ()
Protected Types
typedef HashTable< Pair< autoPtr< BlendedInterfacialModel< heatTransferModel > > >, phasePairKey, phasePairKey::hash > heatTransferModelTable
Protected Attributes
HashPtrTable< volScalarField, phasePairKey, phasePairKey::hash > Tf_
heatTransferModelTable heatTransferModels_
Detailed Description
template<class BasePhaseSystem>
class Foam::TwoResistanceHeatTransferPhaseSystem< BasePhaseSystem >
Class which models interfacial heat transfer between a number of phases. Two heat transfer models are stored at each interface, one for each phase. This permits definition of an interface temperature with which heat transfer occurs. It also allows derived systems to define other thermodynamic properties at the interface and therefore represent phase changes.
See also
OneResistanceHeatTransferPhaseSystem
Source files
TwoResistanceHeatTransferPhaseSystem.H
TwoResistanceHeatTransferPhaseSystem.C
Definition at line 60 of file TwoResistanceHeatTransferPhaseSystem.H.
Member Typedef Documentation
heatTransferModelTable
template<class BasePhaseSystem > typedef HashTable< Pair<autoPtr<BlendedInterfacialModel<heatTransferModel> > >, phasePairKey, phasePairKey::hash > heatTransferModelTable protected
Definition at line 73 of file TwoResistanceHeatTransferPhaseSystem.H.
Constructor & Destructor Documentation
TwoResistanceHeatTransferPhaseSystem()
template<class BasePhaseSystem > TwoResistanceHeatTransferPhaseSystem (const fvMesh & mesh)
Definition at line 36 of file TwoResistanceHeatTransferPhaseSystem.C.
References IOobjectOption::AUTO_WRITE, heatTransferModel::dimK, Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAllConstIter, IOobject::groupName(), TwoResistanceHeatTransferPhaseSystem< BasePhaseSystem >::heatTransferModels_, Foam::max(), phasePair::name(), IOobjectOption::NO_READ, phase1, phasePair::phase1(), phase2, phasePair::phase2(), HashPtrTable< T, Key, Hash >::set(), and TwoResistanceHeatTransferPhaseSystem< BasePhaseSystem >::Tf_.
~TwoResistanceHeatTransferPhaseSystem()
template<class BasePhaseSystem > ~TwoResistanceHeatTransferPhaseSystem () virtual
Definition at line 120 of file TwoResistanceHeatTransferPhaseSystem.C.
Member Function Documentation
heatTransfer()
template<class BasePhaseSystem > Foam::autoPtr< Foam::phaseSystem::heatTransferTable > heatTransfer () const virtual
Definition at line 129 of file TwoResistanceHeatTransferPhaseSystem.C.
References Foam::dimEnergy, Foam::dimTime, forAll, forAllConstIter, he, he2, phaseModel::K(), K1, K2, phase::name(), phaseModel::name(), Foam::negPart(), phasePairKey::ordered(), phase1, phasePair::phase1(), phase2, phasePair::phase2(), phasei, Foam::posPart(), PtrList< T >::set(), Foam::fvm::Sp(), GeometricField< Type, PatchField, GeoMesh >::T(), and phaseModel::thermo().
correctEnergyTransport()
template<class BasePhaseSystem > void correctEnergyTransport () virtual
Definition at line 240 of file TwoResistanceHeatTransferPhaseSystem.C.
correctInterfaceThermo()
template<class BasePhaseSystem > void correctInterfaceThermo () virtual
Definition at line 250 of file TwoResistanceHeatTransferPhaseSystem.C.
References Foam::average(), GeometricField< Type, PatchField, GeoMesh >::clamp_min(), Foam::endl(), forAllConstIter, Foam::Info, L, Foam::max(), Foam::min(), phasePair::name(), p, phase1, phasePair::phase1(), phase2, phasePair::phase2(), GeometricField< Type, PatchField, GeoMesh >::primitiveField(), and phaseModel::thermo().
read()
template<class BasePhaseSystem > bool read () virtual
Definition at line 308 of file TwoResistanceHeatTransferPhaseSystem.C.
Member Data Documentation
Tf_
template<class BasePhaseSystem > HashPtrTable<volScalarField, phasePairKey, phasePairKey::hash> Tf_ protected
Definition at line 79 of file TwoResistanceHeatTransferPhaseSystem.H.
Referenced by TwoResistanceHeatTransferPhaseSystem< BasePhaseSystem >::TwoResistanceHeatTransferPhaseSystem().
heatTransferModels_
template<class BasePhaseSystem > heatTransferModelTable heatTransferModels_ protected
Definition at line 84 of file TwoResistanceHeatTransferPhaseSystem.H.
Referenced by TwoResistanceHeatTransferPhaseSystem< BasePhaseSystem >::TwoResistanceHeatTransferPhaseSystem().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/PhaseSystems/TwoResistanceHeatTransferPhaseSystem/TwoResistanceHeatTransferPhaseSystem.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/PhaseSystems/TwoResistanceHeatTransferPhaseSystem/TwoResistanceHeatTransferPhaseSystem.C