OpenFOAM: convectiveHeatTransferFvPatchScalarField Class Reference
convectiveHeatTransferFvPatchScalarField Class Reference
This boundary condition provides a convective heat transfer coefficient condition.
#include <convectiveHeatTransferFvPatchScalarField.H>
Public Member Functions
TypeName ("convectiveHeatTransfer")
convectiveHeatTransferFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
convectiveHeatTransferFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
convectiveHeatTransferFvPatchScalarField (const convectiveHeatTransferFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
convectiveHeatTransferFvPatchScalarField (const convectiveHeatTransferFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
convectiveHeatTransferFvPatchScalarField (const convectiveHeatTransferFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Protected Attributes
const scalar L_
Detailed Description
This boundary condition provides a convective heat transfer coefficient condition.
if Re > 500000
else
where
= patch convective heat transfer coefficient
= Reynolds number
= Prandtl number
= thermal conductivity
= length scale
Usage
Property Description Required Default value
L Length scale [m] yes
Example of the boundary condition specification:
    <patchName>
    {
        type            convectiveHeatTransfer;
        L               0.1;
    }
See also
Foam::fixedValueFvPatchField
Source files
convectiveHeatTransferFvPatchScalarField.H
convectiveHeatTransferFvPatchScalarField.C
Definition at line 119 of file convectiveHeatTransferFvPatchScalarField.H.
Constructor & Destructor Documentation
convectiveHeatTransferFvPatchScalarField() [1/5]
convectiveHeatTransferFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 35 of file convectiveHeatTransferFvPatchScalarField.C.
convectiveHeatTransferFvPatchScalarField() [2/5]
convectiveHeatTransferFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 61 of file convectiveHeatTransferFvPatchScalarField.C.
convectiveHeatTransferFvPatchScalarField() [3/5]
convectiveHeatTransferFvPatchScalarField (const convectiveHeatTransferFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 47 of file convectiveHeatTransferFvPatchScalarField.C.
convectiveHeatTransferFvPatchScalarField() [4/5]
convectiveHeatTransferFvPatchScalarField (const convectiveHeatTransferFvPatchScalarField & htcpsf)
Definition at line 74 of file convectiveHeatTransferFvPatchScalarField.C.
convectiveHeatTransferFvPatchScalarField() [5/5]
convectiveHeatTransferFvPatchScalarField (const convectiveHeatTransferFvPatchScalarField & htcpsf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 85 of file convectiveHeatTransferFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("convectiveHeatTransfer")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 172 of file convectiveHeatTransferFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 188 of file convectiveHeatTransferFvPatchScalarField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 99 of file convectiveHeatTransferFvPatchScalarField.C.
References Foam::cbrt(), forAll, IOobject::groupName(), convectiveHeatTransferFvPatchScalarField::L_, Foam::mag(), Foam::pow(), Pr(), Foam::Re(), and Foam::sqrt().
write()
void write (Ostream & os) const virtual
Definition at line 156 of file convectiveHeatTransferFvPatchScalarField.C.
References convectiveHeatTransferFvPatchScalarField::L_, os(), fvPatchField< Type >::write(), and fvPatchField< Type >::writeValueEntry().
Member Data Documentation
L_
const scalar L_ protected
Definition at line 128 of file convectiveHeatTransferFvPatchScalarField.H.
Referenced by convectiveHeatTransferFvPatchScalarField::updateCoeffs(), and convectiveHeatTransferFvPatchScalarField::write().
The documentation for this class was generated from the following files:
src/thermoTools/derivedFvPatchFields/convectiveHeatTransfer/convectiveHeatTransferFvPatchScalarField.H
src/thermoTools/derivedFvPatchFields/convectiveHeatTransfer/convectiveHeatTransferFvPatchScalarField.C