OpenFOAM: triFace Class Reference
triFace Class Reference
A triangular face using a FixedList of labels corresponding to mesh vertices.
#include <triFace.H>
Classes
struct Hash
struct hasher
Public Member Functions
void front ()=delete
void back ()=delete
triFace ()
triFace (const label p0, const label p1, const label p2) noexcept
triFace (std::initializer_list< label > list)
triFace (const labelUList &list)
triFace (const labelUList &list, const FixedList< label, 3 > &indices)
triFace (Istream &is)
label a () const noexcept
label b () const noexcept
label c () const noexcept
label & a () noexcept
label & b () noexcept
label & c () noexcept
bool good () const noexcept
label collapse ()
void flip ()
pointField points (const UList< point > &pts) const
face triFaceFace () const
triPointRef tri (const UList< point > &points) const
point centre (const UList< point > &points) const
template<class Type >
Type average (const UList< point > &unused, const Field< Type > &fld) const
vector areaNormal (const UList< point > &points) const
vector unitNormal (const UList< point > &points) const
FOAM_DEPRECATED_FOR (2018-12, "areaNormal() or unitNormal()") vector normal(const UList< point > &points) const
scalar mag (const UList< point > &points) const
Pair< point > box (const UList< point > &points) const
label nTriangles () const noexcept
triFace reverseFace () const
label which (const label vertex) const
label nextLabel (const label i) const
label prevLabel (const label i) const
label thisLabel (const label i) const
scalar sweptVol (const UList< point > &opts, const UList< point > &npts) const
tensor inertia (const UList< point > &points, const point &refPt=vector::zero, scalar density=1.0) const
pointHit ray (const point &p, const vector &q, const UList< point > &points, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction dir=intersection::VECTOR) const
pointHit intersection (const point &p, const vector &q, const UList< point > &points, const intersection::algorithm alg, const scalar tol=0.0) const
pointHit intersection (const point &p, const vector &q, const point &ctr, const UList< point > &points, const intersection::algorithm alg, const scalar tol=0.0) const
pointHit nearestPoint (const point &p, const UList< point > &points) const
pointHit nearestPointClassify (const point &p, const UList< point > &points, label &nearType, label &nearLabel) const
int sign (const point &p, const UList< point > &points, const scalar tol=SMALL) const
label nEdges () const noexcept
Foam::edge edge (const label edgei) const
vector edge (const label edgei, const UList< point > &pts) const
Foam::edge rcEdge (const label edgei) const
vector rcEdge (const label edgei, const UList< point > &pts) const
edgeList edges () const
edgeList rcEdges () const
int edgeDirection (const Foam::edge &e) const
void operator+= (const label vertexOffset)
unsigned hash_code (unsigned seed=0) const
bool valid () const noexcept
Foam::edge faceEdge (label edgei) const
Public Member Functions inherited from FixedList< label, 3 >
void writeEntry (const word &keyword, Ostream &os) const
FixedList ()=default
FixedList (const label &val)
FixedList (const Foam::zero)
FixedList (const label list[N])
FixedList (const FixedList< label, N > &list)
FixedList (FixedList< label, N > &&list)
FixedList (std::initializer_list< label > list)
FixedList (const UList< label > &list)
FixedList (const FixedList< label, AnyNum > &list, const FixedList< label, N > &indices)
FixedList (const UList< label > &list, const FixedList< label, N > &indices)
FixedList (const SLList< label > &list)
FixedList (Istream &is)
autoPtr< FixedList< label, N > > clone () const
const label * cdata () const noexcept
label * data () noexcept
const char * cdata_bytes () const noexcept
char * data_bytes () noexcept
label & get () noexcept
const label & get () const noexcept
label & front () noexcept
const label & front () const noexcept
label & back () noexcept
const label & back () const noexcept
label fcIndex (const label i) const
const label & fcValue (const label i) const
label & fcValue (const label i)
label rcIndex (const label i) const
const label & rcValue (const label i) const
label & rcValue (const label i)
void checkStart (const label start) const
void checkSize (const label size) const
void checkIndex (const label i) const
bool uniform () const
label find (const label &val, label pos=0) const
label rfind (const label &val, label pos=-1) const
bool contains (const label &val, label pos=0) const
void resize (const label n)
void resize_nocopy (const label n)
void setSize (const label n)
void fill (const label &val)
void fill (const Foam::zero)
void moveFirst (const label i)
void moveLast (const label i)
void swapFirst (const label i)
void swapLast (const label i)
void transfer (FixedList< label, N > &list)
label & operator[] (const label i)
const label & operator[] (const label i) const
void operator= (const label list[N])
void operator= (const UList< label > &list)
void operator= (const SLList< label > &list)
void operator= (std::initializer_list< label > list)
void operator= (const label &val)
void operator= (const Foam::zero)
void operator= (const FixedList< label, N > &list)
void operator= (FixedList< label, N > &&list)
iterator begin () noexcept
const_iterator begin () const noexcept
iterator end () noexcept
const_iterator end () const noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
const_reverse_iterator crbegin () const
const_reverse_iterator crend () const
void swap (FixedList< label, N > &other)
bool operator== (const FixedList< label, N > &list) const
bool operator!= (const FixedList< label, N > &list) const
bool operator< (const FixedList< label, N > &list) const
bool operator> (const FixedList< label, N > &list) const
bool operator<= (const FixedList< label, N > &list) const
bool operator>= (const FixedList< label, N > &list) const
Istream & readList (Istream &is)
Ostream & writeList (Ostream &os, const label shortLen=0) const
label & first () noexcept
const label & first () const noexcept
label & last () noexcept
const label & last () const noexcept
bool found (const label &val, label pos=0) const
Static Public Member Functions
static int compare (const triFace &a, const triFace &b)
Static Public Member Functions inherited from FixedList< label, 3 >
static const FixedList< label, N > & null ()
static std::streamsize size_bytes () noexcept
static std::streamsize byteSize ()
static constexpr bool empty () noexcept
static constexpr label size () noexcept
static constexpr unsigned max_size () noexcept
Additional Inherited Members
Public Types inherited from FixedList< label, 3 >
typedef label value_type
typedef label * pointer
typedef const label * const_pointer
typedef label & reference
typedef const label & const_reference
typedef label * iterator
typedef const label * const_iterator
typedef label size_type
typedef label difference_type
typedef std::reverse_iterator< iterator > reverse_iterator
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
Protected Member Functions inherited from FixedList< label, 3 >
void writeEntry (Ostream &os) const
Detailed Description
A triangular face using a FixedList of labels corresponding to mesh vertices.
See also
Foam::face, Foam::triangle
Source files
triFace.H
triFaceI.H
triFaceTemplates.C
Definition at line 65 of file triFace.H.
Constructor & Destructor Documentation
triFace() [1/6]
triFace () inline
Definition at line 56 of file triFaceI.H.
triFace() [2/6]
triFace (const label p0, const label p1, const label p2) inline noexcept
Definition at line 62 of file triFaceI.H.
References b, and p0.
triFace() [3/6]
triFace (std::initializer_list< label > list) inline explicit
Definition at line 75 of file triFaceI.H.
triFace() [4/6]
triFace (const labelUList & list) inline explicit
Definition at line 81 of file triFaceI.H.
triFace() [5/6]
triFace (const labelUList & list, const FixedList< label, 3 > & indices) inline
Definition at line 87 of file triFaceI.H.
triFace() [6/6]
triFace (Istream & is) inline
Definition at line 97 of file triFaceI.H.
Member Function Documentation
front()
void front () delete
back()
void back () delete
a() [1/2]
label a () const inline noexcept
Definition at line 110 of file triFace.H.
Referenced by triFace::average(), and triFace::compare().
b() [1/2]
label b () const inline noexcept
Definition at line 113 of file triFace.H.
Referenced by triFace::average(), and triFace::compare().
c() [1/2]
label c () const inline noexcept
Definition at line 116 of file triFace.H.
Referenced by triFace::average().
a() [2/2]
label & a () inline noexcept
Definition at line 119 of file triFace.H.
b() [2/2]
label & b () inline noexcept
Definition at line 122 of file triFace.H.
c() [2/2]
label & c () inline noexcept
Definition at line 125 of file triFace.H.
good()
bool good () const inline noexcept
Definition at line 105 of file triFaceI.H.
References b.
Referenced by triFace::valid().
collapse()
Foam::label collapse () inline
Definition at line 116 of file triFaceI.H.
References n.
flip()
void flip () inline
Definition at line 143 of file triFaceI.H.
points()
Foam::pointField points (const UList< point > & pts) const inline
Definition at line 149 of file triFaceI.H.
References b, p, and pts.
triFaceFace()
Foam::face triFaceFace () const inline
Definition at line 161 of file triFaceI.H.
tri()
Foam::triPointRef tri (const UList< point > & points) const inline
Definition at line 167 of file triFaceI.H.
References b, and points.
centre()
Foam::point centre (const UList< point > & points) const inline
Definition at line 173 of file triFaceI.H.
References b, triangle< Point, PointRef >::centre(), and points.
average()
template<class Type > Type average (const UList< point > & unused, const Field< Type > & fld) const
Definition at line 26 of file triFaceTemplates.C.
References triFace::a(), triFace::b(), triFace::c(), and fld().
areaNormal()
Foam::vector areaNormal (const UList< point > & points) const inline
Definition at line 179 of file triFaceI.H.
References triangle< Point, PointRef >::areaNormal(), b, and points.
Referenced by triFace::FOAM_DEPRECATED_FOR().
unitNormal()
Foam::vector unitNormal (const UList< point > & points) const inline
Definition at line 185 of file triFaceI.H.
References b, points, and triangle< Point, PointRef >::unitNormal().
Referenced by wallBoundedParticle::trackToEdge().
FOAM_DEPRECATED_FOR()
FOAM_DEPRECATED_FOR (2018- 12, "areaNormal() or unitNormal()") const & inline
Definition at line 170 of file triFace.H.
References triFace::areaNormal(), and points.
mag()
Foam::scalar mag (const UList< point > & points) const inline
Definition at line 191 of file triFaceI.H.
References points.
box()
Foam::Pair< Foam::point > box (const UList< point > & points) const inline
Definition at line 198 of file triFaceI.H.
References b, triangle< Point, PointRef >::box(), and points.
nTriangles()
Foam::label nTriangles () const inline noexcept
Definition at line 204 of file triFaceI.H.
reverseFace()
Foam::triFace reverseFace () const inline
Definition at line 210 of file triFaceI.H.
References b.
which()
Foam::label which (const label vertex) const inline
Definition at line 217 of file triFaceI.H.
References FixedList< T, N >::find().
nextLabel()
Foam::label nextLabel (const label i) const inline
Definition at line 229 of file triFaceI.H.
prevLabel()
Foam::label prevLabel (const label i) const inline
Definition at line 235 of file triFaceI.H.
thisLabel()
Foam::label thisLabel (const label i) const inline
Definition at line 223 of file triFaceI.H.
sweptVol()
Foam::scalar sweptVol (const UList< point > & opts, const UList< point > & npts) const inline
Definition at line 241 of file triFaceI.H.
inertia()
Foam::tensor inertia (const UList< point > & points, const point & refPt = vector::zero, scalar density = 1.0) const inline
Definition at line 274 of file triFaceI.H.
References points.
ray()
Foam::pointHit ray (const point & p, const vector & q, const UList< point > & points, const intersection::algorithm alg = intersection::FULL_RAY, const intersection::direction dir = intersection::VECTOR) const inline
Definition at line 286 of file triFaceI.H.
References p, and points.
intersection() [1/2]
Foam::pointHit intersection (const point & p, const vector & q, const UList< point > & points, const intersection::algorithm alg, const scalar tol = 0.0) const inline
Definition at line 300 of file triFaceI.H.
References p, and points.
intersection() [2/2]
Foam::pointHit intersection (const point & p, const vector & q, const point & ctr, const UList< point > & points, const intersection::algorithm alg, const scalar tol = 0.0) const inline
Definition at line 313 of file triFaceI.H.
References p, and points.
nearestPoint()
Foam::pointHit nearestPoint (const point & p, const UList< point > & points) const inline
Definition at line 327 of file triFaceI.H.
References p, and points.
nearestPointClassify()
Foam::pointHit nearestPointClassify (const point & p, const UList< point > & points, label & nearType, label & nearLabel) const inline
Definition at line 337 of file triFaceI.H.
References p, and points.
sign()
int sign (const point & p, const UList< point > & points, const scalar tol = SMALL) const inline
Definition at line 349 of file triFaceI.H.
References p, and points.
nEdges()
Foam::label nEdges () const inline noexcept
Definition at line 360 of file triFaceI.H.
edge() [1/2]
Foam::edge edge (const label edgei) const inline
Definition at line 366 of file triFaceI.H.
edge() [2/2]
Foam::vector edge (const label edgei, const UList< point > & pts) const inline
Definition at line 372 of file triFaceI.H.
References pts.
rcEdge() [1/2]
Foam::edge rcEdge (const label edgei) const inline
Definition at line 382 of file triFaceI.H.
rcEdge() [2/2]
Foam::vector rcEdge (const label edgei, const UList< point > & pts) const inline
Definition at line 391 of file triFaceI.H.
References pts.
edges()
Foam::edgeList edges () const inline
Definition at line 404 of file triFaceI.H.
References b, and UPtrList< T >::first().
rcEdges()
Foam::edgeList rcEdges () const inline
Definition at line 421 of file triFaceI.H.
References b, and UPtrList< T >::first().
edgeDirection()
int edgeDirection (const Foam::edge & e) const inline
Definition at line 438 of file triFaceI.H.
References b, e, and UList< T >::first().
compare()
int compare (const triFace & a, const triFace & b) inline static
Definition at line 27 of file triFaceI.H.
References triFace::a(), and triFace::b().
Referenced by Foam::operator!=(), and Foam::operator==().
operator+=()
void operator+= (const label vertexOffset) inline
Definition at line 462 of file triFaceI.H.
hash_code()
unsigned hash_code (unsigned seed = 0) const inline
Definition at line 341 of file triFace.H.
valid()
bool valid () const inline noexcept
Definition at line 374 of file triFace.H.
References triFace::good().
faceEdge()
Foam::edge faceEdge (label edgei) const inline
Definition at line 377 of file triFace.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/meshShapes/triFace/triFace.H
src/OpenFOAM/meshes/meshShapes/triFace/triFaceI.H
src/OpenFOAM/meshes/meshShapes/triFace/triFaceTemplates.C