OpenFOAM: filmThermoModel Class Reference
filmThermoModel Class Reference abstract
Base class for film thermo models.
#include <filmThermoModel.H>
Public Member Functions
TypeName ("filmThermoModel")
declareRunTimeSelectionTable (autoPtr, filmThermoModel, dictionary,(surfaceFilmRegionModel &film, const dictionary &dict),(film, dict))
filmThermoModel (surfaceFilmRegionModel &film)
filmThermoModel (const word &modelType, surfaceFilmRegionModel &film, const dictionary &dict)
virtual ~filmThermoModel ()
virtual const word & name () const =0
virtual scalar rho (const scalar p, const scalar T) const =0
virtual scalar mu (const scalar p, const scalar T) const =0
virtual scalar sigma (const scalar p, const scalar T) const =0
virtual scalar Cp (const scalar p, const scalar T) const =0
virtual scalar kappa (const scalar p, const scalar T) const =0
virtual scalar D (const scalar p, const scalar T) const =0
virtual scalar hl (const scalar p, const scalar T) const =0
virtual scalar pv (const scalar p, const scalar T) const =0
virtual scalar W () const =0
virtual scalar Tb (const scalar p) const =0
virtual tmp< volScalarField > rho () const =0
virtual tmp< volScalarField > mu () const =0
virtual tmp< volScalarField > sigma () const =0
virtual tmp< volScalarField > Cp () const =0
virtual tmp< volScalarField > kappa () const =0
Public Member Functions inherited from filmSubModelBase
filmSubModelBase (surfaceFilmRegionModel &film)
filmSubModelBase (surfaceFilmRegionModel &film, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
filmSubModelBase (const word &modelName, surfaceFilmRegionModel &film, const dictionary &dict, const word &baseName, const word &modelType)
virtual ~filmSubModelBase ()
virtual bool writeTime () const
const surfaceFilmRegionModel & film () const
surfaceFilmRegionModel & film ()
template<class FilmType >
const FilmType & filmType () const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
subModelBase (const subModelBase &smb)
virtual ~subModelBase ()=default
const word & modelName () const
const dictionary & dict () const
const word & baseName () const
const word & modelType () const
const dictionary & coeffDict () const
const dictionary & properties () const
virtual bool defaultCoeffs (const bool printMsg) const
virtual bool active () const
virtual void cacheFields (const bool store)
virtual fileName localPath () const
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
bool getModelDict (const word &entryName, dictionary &dict) const
template<class Type >
bool getModelProperty (const word &entryName, Type &value) const
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
virtual void write (Ostream &os) const
Static Public Member Functions
static autoPtr< filmThermoModel > New (surfaceFilmRegionModel &film, const dictionary &dict)
Additional Inherited Members
Public Attributes inherited from subModelBase
bool log
Protected Member Functions inherited from subModelBase
bool inLine () const
Protected Attributes inherited from filmSubModelBase
surfaceFilmRegionModel & filmModel_
Protected Attributes inherited from subModelBase
const word modelName_
dictionary & properties_
const dictionary dict_
const word baseName_
const word modelType_
const dictionary coeffDict_
Detailed Description
Base class for film thermo models.
Source files
filmThermoModel.H
filmThermoModel.C
filmThermoModelNew.C
Definition at line 52 of file filmThermoModel.H.
Constructor & Destructor Documentation
filmThermoModel() [1/2]
filmThermoModel (surfaceFilmRegionModel & film)
Definition at line 39 of file filmThermoModel.C.
filmThermoModel() [2/2]
filmThermoModel (const word & modelType, surfaceFilmRegionModel & film, const dictionary & dict)
Definition at line 48 of file filmThermoModel.C.
~filmThermoModel()
~filmThermoModel () virtual
Definition at line 61 of file filmThermoModel.C.
Member Function Documentation
TypeName()
TypeName ("filmThermoModel")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , filmThermoModel , dictionary , (surfaceFilmRegionModel &film, const dictionary &dict) , (film, dict))
New()
autoPtr< filmThermoModel > New (surfaceFilmRegionModel & film, const dictionary & dict) static
Definition at line 35 of file filmThermoModelNew.C.
References subModelBase::dict(), Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, UPtrList< T >::get(), Foam::Info, and subModelBase::modelType().
name()
virtual const word & name () const pure virtual
Implemented in constantFilmThermo, and liquidFilmThermo.
Referenced by standardPhaseChange::correctModel(), and waxSolventEvaporation::correctModel().
rho() [1/2]
virtual scalar rho (const scalar p, const scalar T) const pure virtual
Implemented in constantFilmThermo, and liquidFilmThermo.
mu() [1/2]
virtual scalar mu (const scalar p, const scalar T) const pure virtual
Implemented in constantFilmThermo, and liquidFilmThermo.
sigma() [1/2]
virtual scalar sigma (const scalar p, const scalar T) const pure virtual
Implemented in constantFilmThermo, and liquidFilmThermo.
Cp() [1/2]
virtual scalar Cp (const scalar p, const scalar T) const pure virtual
Implemented in constantFilmThermo, and liquidFilmThermo.
Referenced by standardPhaseChange::correctModel().
kappa() [1/2]
virtual scalar kappa (const scalar p, const scalar T) const pure virtual
Implemented in constantFilmThermo, and liquidFilmThermo.
D()
virtual scalar D (const scalar p, const scalar T) const pure virtual
Implemented in constantFilmThermo, and liquidFilmThermo.
Referenced by standardPhaseChange::correctModel(), and waxSolventEvaporation::correctModel().
hl()
virtual scalar hl (const scalar p, const scalar T) const pure virtual
Implemented in constantFilmThermo, and liquidFilmThermo.
Referenced by standardPhaseChange::correctModel().
pv()
virtual scalar pv (const scalar p, const scalar T) const pure virtual
Implemented in constantFilmThermo, and liquidFilmThermo.
Referenced by standardPhaseChange::correctModel(), and waxSolventEvaporation::correctModel().
W()
virtual scalar W () const pure virtual
Implemented in constantFilmThermo, and liquidFilmThermo.
Referenced by standardPhaseChange::correctModel().
Tb()
virtual scalar Tb (const scalar p) const pure virtual
Implemented in constantFilmThermo, and liquidFilmThermo.
Referenced by standardPhaseChange::correctModel(), and waxSolventEvaporation::correctModel().
rho() [2/2]
virtual tmp< volScalarField > rho () const pure virtual
Implemented in constantFilmThermo, and liquidFilmThermo.
mu() [2/2]
virtual tmp< volScalarField > mu () const pure virtual
Implemented in constantFilmThermo, and liquidFilmThermo.
sigma() [2/2]
virtual tmp< volScalarField > sigma () const pure virtual
Implemented in constantFilmThermo, and liquidFilmThermo.
Cp() [2/2]
virtual tmp< volScalarField > Cp () const pure virtual
Implemented in constantFilmThermo, and liquidFilmThermo.
kappa() [2/2]
virtual tmp< volScalarField > kappa () const pure virtual
Implemented in constantFilmThermo, and liquidFilmThermo.
The documentation for this class was generated from the following files:
src/regionModels/surfaceFilmModels/submodels/kinematic/filmThermoModel/filmThermoModel/filmThermoModel.H
src/regionModels/surfaceFilmModels/submodels/kinematic/filmThermoModel/filmThermoModel/filmThermoModel.C
src/regionModels/surfaceFilmModels/submodels/kinematic/filmThermoModel/filmThermoModel/filmThermoModelNew.C