OpenFOAM: boundedConvectionScheme< Type > Class Template Reference
boundedConvectionScheme< Type > Class Template Reference
Numerics » Finite volume numerical schemes » Convection schemes
Bounded form of the selected convection scheme.
#include <boundedConvectionScheme.H>
Public Member Functions
TypeName ("bounded")
boundedConvectionScheme (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &is)
const convectionScheme< Type > & scheme () const
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const surfaceScalarField &, const GeometricField< Type, fvPatchField, volMesh > &) const
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const surfaceScalarField &, const GeometricField< Type, fvPatchField, volMesh > &) const
tmp< fvMatrix< Type > > fvmDiv (const surfaceScalarField &, const GeometricField< Type, fvPatchField, volMesh > &) const
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDiv (const surfaceScalarField &, const GeometricField< Type, fvPatchField, volMesh > &) const
Public Member Functions inherited from convectionScheme< Type >
virtual const word & type () const =0
declareRunTimeSelectionTable (tmp, convectionScheme, Istream,(const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
declareRunTimeSelectionTable (tmp, convectionScheme, Multivariate,(const fvMesh &mesh, const typename multivariateSurfaceInterpolationScheme< Type >::fieldTable &fields, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, fields, faceFlux, schemeData))
convectionScheme (const convectionScheme &)
convectionScheme (const fvMesh &mesh, const surfaceScalarField &)
virtual ~convectionScheme ()
const fvMesh & mesh () const
void operator= (const convectionScheme< Type > &)
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Additional Inherited Members
Static Public Member Functions inherited from convectionScheme< Type >
static tmp< convectionScheme< Type > > New (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData)
static tmp< convectionScheme< Type > > New (const fvMesh &mesh, const typename multivariateSurfaceInterpolationScheme< Type >::fieldTable &fields, const surfaceScalarField &faceFlux, Istream &schemeData)
Detailed Description
template<class Type>
class Foam::fv::boundedConvectionScheme< Type >
Bounded form of the selected convection scheme.
Boundedness is achieved by subtracting div(phi)*vf or Sp(div(phi), vf) which is non-conservative if div(phi) != 0 but conservative otherwise.
Can be used for convection of bounded scalar properties in steady-state solvers to improve stability if insufficient convergence of the pressure equation causes temporary divergence of the flux field.
Source files
boundedConvectionScheme.H
boundedConvectionScheme.C
Definition at line 62 of file boundedConvectionScheme.H.
Constructor & Destructor Documentation
boundedConvectionScheme()
template<class Type > boundedConvectionScheme (const fvMesh & mesh, const surfaceScalarField & faceFlux, Istream & is) inline
Definition at line 89 of file boundedConvectionScheme.H.
References fv().
Member Function Documentation
TypeName()
template<class Type > TypeName ("bounded")
scheme()
template<class Type > const convectionScheme< Type > & scheme () const
Definition at line 39 of file boundedConvectionScheme.C.
interpolate()
template<class Type > tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const surfaceScalarField & phi, const GeometricField< Type, fvPatchField, volMesh > & vf) const virtual
Implements convectionScheme< Type >.
Definition at line 47 of file boundedConvectionScheme.C.
References phi.
flux()
template<class Type > tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const surfaceScalarField & faceFlux, const GeometricField< Type, fvPatchField, volMesh > & vf) const virtual
Implements convectionScheme< Type >.
Definition at line 59 of file boundedConvectionScheme.C.
fvmDiv()
template<class Type > tmp< fvMatrix< Type > > fvmDiv (const surfaceScalarField & faceFlux, const GeometricField< Type, fvPatchField, volMesh > & vf) const virtual
Implements convectionScheme< Type >.
Definition at line 71 of file boundedConvectionScheme.C.
References Foam::fvm::Sp(), and Foam::fvc::surfaceIntegrate().
fvcDiv()
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDiv (const surfaceScalarField & faceFlux, const GeometricField< Type, fvPatchField, volMesh > & vf) const virtual
Implements convectionScheme< Type >.
Definition at line 85 of file boundedConvectionScheme.C.
References Foam::fvc::surfaceIntegrate().
The documentation for this class was generated from the following files:
src/finiteVolume/finiteVolume/convectionSchemes/boundedConvectionScheme/boundedConvectionScheme.H
src/finiteVolume/finiteVolume/convectionSchemes/boundedConvectionScheme/boundedConvectionScheme.C