OpenFOAM: UPstream::commsStruct Class Reference
UPstream::commsStruct Class Reference
#include <UPstream.H>
Public Member Functions
commsStruct () noexcept
commsStruct (const label above, labelList &&below, labelList &&allBelow, labelList &&allNotBelow)
commsStruct (const label numProcs, const label myProcID, const label above, const labelUList &below, const labelUList &allBelow)
label nProcs () const
label above () const noexcept
const labelList & below () const noexcept
const labelList & allBelow () const noexcept
const labelList & allNotBelow () const noexcept
void reset ()
void reset (const label procID, const label numProcs)
bool operator== (const commsStruct &) const
bool operator!= (const commsStruct &) const
Static Public Member Functions
static void printGraph (Ostream &os, const UList< UPstream::commsStruct > &comms, const label proci=0)
Friends
Ostream & operator<< (Ostream &, const commsStruct &)
Detailed Description
Definition at line 94 of file UPstream.H.
Constructor & Destructor Documentation
commsStruct() [1/3]
commsStruct () inline noexcept
Definition at line 118 of file UPstream.H.
commsStruct() [2/3]
commsStruct (const label above, labelList && below, labelList && allBelow, labelList && allNotBelow)
Definition at line 26 of file UPstreamCommsStruct.C.
commsStruct() [3/3]
commsStruct (const label numProcs, const label myProcID, const label above, const labelUList & below, const labelUList & allBelow)
Definition at line 41 of file UPstreamCommsStruct.C.
References Foam::abort(), UPstream::commsStruct::allBelow(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::nl, and UList< T >::size().
Member Function Documentation
printGraph()
void printGraph (Ostream & os, const UList< UPstream::commsStruct > & comms, const label proci = 0) static
Definition at line 88 of file UPstreamCommsStruct.C.
References Foam::indent(), Foam::nl, os(), and Foam::pos().
nProcs()
Foam::label nProcs () const
Definition at line 154 of file UPstreamCommsStruct.C.
above()
label above () const inline noexcept
Definition at line 157 of file UPstream.H.
Referenced by Foam::operator<<(), and UPstream::commsStruct::operator==().
below()
const labelList & below () const inline noexcept
Definition at line 160 of file UPstream.H.
Referenced by Foam::operator<<(), and UPstream::commsStruct::operator==().
allBelow()
const labelList & allBelow () const inline noexcept
Definition at line 164 of file UPstream.H.
Referenced by UPstream::commsStruct::commsStruct(), and Foam::operator<<().
allNotBelow()
const labelList & allNotBelow () const inline noexcept
Definition at line 168 of file UPstream.H.
Referenced by Foam::operator<<().
reset() [1/2]
void reset ()
Definition at line 160 of file UPstreamCommsStruct.C.
References PtrList< T >::clear().
Referenced by UList< T >::operator[]().
reset() [2/2]
void reset (const label procID, const label numProcs)
Definition at line 169 of file UPstreamCommsStruct.C.
References Foam::identity(), UPstream::nProcsSimpleSum, UPstream::procID(), and PtrList< T >::push_back().
operator==()
bool operator== (const commsStruct & comm) const
Definition at line 292 of file UPstreamCommsStruct.C.
References UPstream::commsStruct::above(), and UPstream::commsStruct::below().
operator!=()
bool operator!= (const commsStruct & comm) const
Definition at line 304 of file UPstreamCommsStruct.C.
References Foam::operator==().
Friends And Related Symbol Documentation
operator<<
Ostream & operator<< (Ostream & , const commsStruct &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOstreams/Pstreams/UPstream.H
src/OpenFOAM/db/IOstreams/Pstreams/UPstreamCommsStruct.C