OpenFOAM: swarmCorrection Class Reference
swarmCorrection Class Reference abstract
#include <swarmCorrection.H>
Public Member Functions
TypeName ("swarmCorrection")
declareRunTimeSelectionTable (autoPtr, swarmCorrection, dictionary,(const dictionary &dict, const phasePair &pair),(dict, pair))
swarmCorrection (const dictionary &dict, const phasePair &pair)
virtual ~swarmCorrection ()=default
virtual tmp< volScalarField > Cs () const =0
TypeName ("swarmCorrection")
declareRunTimeSelectionTable (autoPtr, swarmCorrection, dictionary,(const dictionary &dict, const phasePair &pair),(dict, pair))
swarmCorrection (const dictionary &dict, const phasePair &pair)
virtual ~swarmCorrection ()=default
virtual tmp< volScalarField > Cs () const =0
Static Public Member Functions
static autoPtr< swarmCorrection > New (const dictionary &dict, const phasePair &pair)
static autoPtr< swarmCorrection > New (const dictionary &dict, const phasePair &pair)
Protected Attributes
const phasePair & pair_
Detailed Description
Source files
swarmCorrection.H
swarmCorrection.C
Source files
swarmCorrection.H
swarmCorrection.C
Definition at line 51 of file swarmCorrection.H.
Constructor & Destructor Documentation
swarmCorrection() [1/2]
swarmCorrection (const dictionary & dict, const phasePair & pair)
Definition at line 36 of file swarmCorrection.C.
~swarmCorrection() [1/2]
virtual ~swarmCorrection () virtual default
swarmCorrection() [2/2]
swarmCorrection (const dictionary & dict, const phasePair & pair)
~swarmCorrection() [2/2]
virtual ~swarmCorrection () virtual default
Member Function Documentation
TypeName() [1/2]
TypeName ("swarmCorrection")
declareRunTimeSelectionTable() [1/2]
declareRunTimeSelectionTable (autoPtr , swarmCorrection , dictionary , (const dictionary &dict, const phasePair &pair) , (dict, pair))
New() [1/2]
Foam::autoPtr< Foam::swarmCorrection > New (const dictionary & dict, const phasePair & pair) static
Definition at line 49 of file swarmCorrection.C.
References Foam::abort(), dict, Foam::endl(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), and Foam::Info.
Cs() [1/2]
virtual tmp< volScalarField > Cs () const pure virtual
Implemented in noSwarm, TomiyamaSwarm, noSwarm, and TomiyamaSwarm.
TypeName() [2/2]
TypeName ("swarmCorrection")
declareRunTimeSelectionTable() [2/2]
declareRunTimeSelectionTable (autoPtr , swarmCorrection , dictionary , (const dictionary &dict, const phasePair &pair) , (dict, pair))
New() [2/2]
static autoPtr< swarmCorrection > New (const dictionary & dict, const phasePair & pair) static
Cs() [2/2]
virtual tmp< volScalarField > Cs () const pure virtual
Implemented in noSwarm, TomiyamaSwarm, noSwarm, and TomiyamaSwarm.
Member Data Documentation
pair_
const phasePair & pair_ protected
Definition at line 58 of file swarmCorrection.H.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/interfacialModels/swarmCorrections/swarmCorrection/swarmCorrection.H
src/phaseSystemModels/twoPhaseEuler/twoPhaseSystem/interfacialModels/swarmCorrections/swarmCorrection/swarmCorrection.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/interfacialModels/swarmCorrections/swarmCorrection/swarmCorrection.C
src/phaseSystemModels/twoPhaseEuler/twoPhaseSystem/interfacialModels/swarmCorrections/swarmCorrection/swarmCorrection.C