OpenFOAM: CloudFunctionObject< CloudType > Class Template Reference
CloudFunctionObject< CloudType > Class Template Reference
Lagrangian particle models » Submodels » Function objects
Templated cloud function object base class.
#include <CloudFunctionObject.H>
Public Member Functions
TypeName ("cloudFunctionObject")
declareRunTimeSelectionTable (autoPtr, CloudFunctionObject, dictionary,(const dictionary &dict, CloudType &owner, const word &modelName),(dict, owner, modelName))
CloudFunctionObject (CloudType &owner)
CloudFunctionObject (const dictionary &dict, CloudType &owner, const word &objectType, const word &modelName)
CloudFunctionObject (const CloudFunctionObject< CloudType > &ppm)
virtual autoPtr< CloudFunctionObject< CloudType > > clone () const
virtual ~CloudFunctionObject ()=default
virtual void preEvolve (const typename parcelType::trackingData &td)
virtual void postEvolve (const typename parcelType::trackingData &td)
virtual void postMove (parcelType &p, const scalar dt, const point &position0, bool &keepParticle)
virtual void postPatch (const parcelType &p, const polyPatch &pp, bool &keepParticle)
virtual void postFace (const parcelType &p, bool &keepParticle)
const fileName & outputDir () const
fileName writeTimeDir () const
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
virtual ~CloudSubModelBase ()=default
const CloudType & owner () const
virtual bool writeTime () const
virtual fileName localPath () const
CloudType & owner ()
virtual void info ()
virtual void write (Ostream &os) const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
subModelBase (const subModelBase &smb)
virtual ~subModelBase ()=default
const word & modelName () const
const dictionary & dict () const
const word & baseName () const
const word & modelType () const
const dictionary & coeffDict () const
const dictionary & properties () const
virtual bool defaultCoeffs (const bool printMsg) const
virtual bool active () const
virtual void cacheFields (const bool store)
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
bool getModelDict (const word &entryName, dictionary &dict) const
template<class Type >
bool getModelProperty (const word &entryName, Type &value) const
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Static Public Member Functions
static autoPtr< CloudFunctionObject< CloudType > > New (const dictionary &dict, CloudType &owner, const word &objectType, const word &modelName)
Additional Inherited Members
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Public Attributes inherited from subModelBase
bool log
Protected Member Functions inherited from subModelBase
bool inLine () const
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Protected Attributes inherited from subModelBase
const word modelName_
dictionary & properties_
const dictionary dict_
const word baseName_
const word modelType_
const dictionary coeffDict_
Detailed Description
template<class CloudType>
class Foam::CloudFunctionObject< CloudType >
Templated cloud function object base class.
Source files
CloudFunctionObject.H
CloudFunctionObject.C
CloudFunctionObjectNew.C
Definition at line 58 of file CloudFunctionObject.H.
Constructor & Destructor Documentation
CloudFunctionObject() [1/3]
template<class CloudType > CloudFunctionObject (CloudType & owner)
Definition at line 37 of file CloudFunctionObject.C.
CloudFunctionObject() [2/3]
template<class CloudType > CloudFunctionObject (const dictionary & dict, CloudType & owner, const word & objectType, const word & modelName)
Definition at line 45 of file CloudFunctionObject.C.
References fileName::clean(), CloudSubModelBase< CloudType >::localPath(), functionObject::outputPrefix, and CloudSubModelBase< CloudType >::owner().
CloudFunctionObject() [3/3]
template<class CloudType > CloudFunctionObject (const CloudFunctionObject< CloudType > & ppm)
Definition at line 71 of file CloudFunctionObject.C.
~CloudFunctionObject()
template<class CloudType > virtual ~CloudFunctionObject () virtual default
Member Function Documentation
TypeName()
template<class CloudType > TypeName ("cloudFunctionObject")
declareRunTimeSelectionTable()
template<class CloudType > declareRunTimeSelectionTable (autoPtr , CloudFunctionObject< CloudType > , dictionary , (const dictionary &dict, CloudType &owner, const word &modelName) , (dict, owner, modelName))
clone()
template<class CloudType > virtual autoPtr< CloudFunctionObject< CloudType > > clone () const inline virtual
Reimplemented in FaceInteraction< CloudType >, FacePostProcessing< CloudType >, HeatTransferCoeff< CloudType >, KinematicReynoldsNumber< CloudType >, NusseltNumber< CloudType >, ParticleCollector< CloudType >, ParticleDose< CloudType >, ParticleErosion< CloudType >, ParticleHistogram< CloudType >, ParticlePostProcessing< CloudType >, ParticleTracks< CloudType >, ParticleTrap< CloudType >, ParticleZoneInfo< CloudType >, PatchCollisionDensity< CloudType >, PatchInteractionFields< CloudType >, RemoveParcels< CloudType >, ThermoReynoldsNumber< CloudType >, VoidFraction< CloudType >, and WeberNumberReacting< CloudType >.
Definition at line 120 of file CloudFunctionObject.H.
New()
template<class CloudType > Foam::autoPtr< Foam::CloudFunctionObject< CloudType > > New (const dictionary & dict, CloudType & owner, const word & objectType, const word & modelName) static
Definition at line 28 of file CloudFunctionObjectNew.C.
References Foam::abort(), dict, Foam::endl(), Foam::FatalIOError, FatalIOErrorInLookup, Foam::Info, and PtrList< T >::PtrList().
preEvolve()
template<class CloudType > void preEvolve (const typename parcelType::trackingData & td) virtual
Reimplemented in ParticleErosion< CloudType >, ParticleTracks< CloudType >, ParticleTrap< CloudType >, ParticleZoneInfo< CloudType >, PatchInteractionFields< CloudType >, and VoidFraction< CloudType >.
Definition at line 84 of file CloudFunctionObject.C.
postEvolve()
template<class CloudType > void postEvolve (const typename parcelType::trackingData & td) virtual
Reimplemented in HeatTransferCoeff< CloudType >, KinematicReynoldsNumber< CloudType >, NusseltNumber< CloudType >, ParticleDose< CloudType >, ParticleTrap< CloudType >, ParticleZoneInfo< CloudType >, RemoveParcels< CloudType >, ThermoReynoldsNumber< CloudType >, VoidFraction< CloudType >, and WeberNumberReacting< CloudType >.
Definition at line 92 of file CloudFunctionObject.C.
References write().
Referenced by ParticleZoneInfo< CloudType >::postEvolve(), RemoveParcels< CloudType >::postEvolve(), and VoidFraction< CloudType >::postEvolve().
postMove()
template<class CloudType > void postMove (parcelType & p, const scalar dt, const point & position0, bool & keepParticle) virtual
Reimplemented in ParticleTrap< CloudType >, ParticleZoneInfo< CloudType >, and VoidFraction< CloudType >.
Definition at line 105 of file CloudFunctionObject.C.
postPatch()
template<class CloudType > void postPatch (const parcelType & p, const polyPatch & pp, bool & keepParticle) virtual
Reimplemented in ParticleErosion< CloudType >, ParticleHistogram< CloudType >, ParticlePostProcessing< CloudType >, PatchCollisionDensity< CloudType >, and PatchInteractionFields< CloudType >.
Definition at line 116 of file CloudFunctionObject.C.
postFace()
template<class CloudType > void postFace (const parcelType & p, bool & keepParticle) virtual
Reimplemented in ParticleHistogram< CloudType >, ParticlePostProcessing< CloudType >, ParticleTracks< CloudType >, and RemoveParcels< CloudType >.
Definition at line 126 of file CloudFunctionObject.C.
outputDir()
template<class CloudType > const Foam::fileName & outputDir () const
Definition at line 135 of file CloudFunctionObject.C.
writeTimeDir()
template<class CloudType > Foam::fileName writeTimeDir () const
Definition at line 142 of file CloudFunctionObject.C.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/CloudFunctionObjects/CloudFunctionObject/CloudFunctionObject.H
src/lagrangian/intermediate/submodels/CloudFunctionObjects/CloudFunctionObject/CloudFunctionObject.C
src/lagrangian/intermediate/submodels/CloudFunctionObjects/CloudFunctionObject/CloudFunctionObjectNew.C