OpenFOAM: WallInteractionModel< CloudType > Class Template Reference
WallInteractionModel< CloudType > Class Template Reference abstract
Templated wall interaction model class.
#include <WallInteractionModel.H>
Public Member Functions
TypeName ("WallInteractionModel")
declareRunTimeSelectionTable (autoPtr, WallInteractionModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
WallInteractionModel (CloudType &owner)
WallInteractionModel (const dictionary &dict, CloudType &owner, const word &type)
virtual ~WallInteractionModel ()
const CloudType & owner () const
CloudType & owner ()
const dictionary & dict () const
const dictionary & coeffDict () const
virtual void correct (typename CloudType::parcelType &p)=0
Static Public Member Functions
static autoPtr< WallInteractionModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Detailed Description
template<class CloudType>
class Foam::WallInteractionModel< CloudType >
Templated wall interaction model class.
Source files
WallInteractionModel.H
WallInteractionModel.C
WallInteractionModelNew.C
Definition at line 50 of file WallInteractionModel.H.
Constructor & Destructor Documentation
WallInteractionModel() [1/2]
template<class CloudType > WallInteractionModel (CloudType & owner)
Definition at line 27 of file WallInteractionModel.C.
WallInteractionModel() [2/2]
template<class CloudType > WallInteractionModel (const dictionary & dict, CloudType & owner, const word & type)
Definition at line 36 of file WallInteractionModel.C.
~WallInteractionModel()
template<class CloudType > ~WallInteractionModel () virtual
Definition at line 52 of file WallInteractionModel.C.
Member Function Documentation
TypeName()
template<class CloudType > TypeName ("WallInteractionModel< CloudType >")
declareRunTimeSelectionTable()
template<class CloudType > declareRunTimeSelectionTable (autoPtr , WallInteractionModel< CloudType > , dictionary , (const dictionary &dict, CloudType &owner) , (dict, owner))
New()
template<class CloudType > Foam::autoPtr< Foam::WallInteractionModel< CloudType > > New (const dictionary & dict, CloudType & owner) static
Definition at line 28 of file WallInteractionModelNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, Foam::Info, and PtrList< T >::PtrList().
owner() [1/2]
template<class CloudType > const CloudType & owner () const
Definition at line 59 of file WallInteractionModel.C.
owner() [2/2]
template<class CloudType > CloudType & owner ()
Definition at line 66 of file WallInteractionModel.C.
dict()
template<class CloudType > const Foam::dictionary & dict () const
Definition at line 73 of file WallInteractionModel.C.
coeffDict()
template<class CloudType > const Foam::dictionary & coeffDict () const
Definition at line 81 of file WallInteractionModel.C.
correct()
template<class CloudType > virtual void correct (typename CloudType::parcelType & p) pure virtual
Implemented in MaxwellianThermal< CloudType >, MixedDiffuseSpecular< CloudType >, and SpecularReflection< CloudType >.
The documentation for this class was generated from the following files:
src/lagrangian/DSMC/clouds/Templates/DSMCCloud/DSMCCloud.H
src/lagrangian/DSMC/submodels/WallInteractionModel/WallInteractionModel/WallInteractionModel.H
src/lagrangian/DSMC/submodels/WallInteractionModel/WallInteractionModel/WallInteractionModel.C
src/lagrangian/DSMC/submodels/WallInteractionModel/WallInteractionModel/WallInteractionModelNew.C