OpenFOAM: continuousGasKEpsilon< BasicTurbulenceModel > Class Template Reference
continuousGasKEpsilon< BasicTurbulenceModel > Class Template Reference
Turbulence models » RAS turbulence
k-epsilon model for the gas-phase in a two-phase system supporting phase-inversion.
#include <continuousGasKEpsilon.H>
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from kEpsilon< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from linearViscousStress< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("continuousGasKEpsilon")
continuousGasKEpsilon (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
virtual ~continuousGasKEpsilon ()=default
virtual bool read ()
const turbulenceModel & liquidTurbulence () const
virtual tmp< volScalarField > nuEff () const
virtual tmp< volScalarField > rhoEff () const
virtual tmp< volSymmTensorField > R () const
Public Member Functions inherited from kEpsilon< BasicTurbulenceModel >
TypeName ("kEpsilon")
kEpsilon (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
virtual ~kEpsilon ()=default
tmp< volScalarField > DkEff () const
tmp< volScalarField > DepsilonEff () const
virtual tmp< volScalarField > k () const
virtual tmp< volScalarField > epsilon () const
virtual void correct ()
Public Member Functions inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
eddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~eddyViscosity ()=default
virtual tmp< volScalarField > nut () const
virtual tmp< scalarField > nut (const label patchi) const
virtual void validate ()
Public Member Functions inherited from linearViscousStress< BasicTurbulenceModel >
linearViscousStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~linearViscousStress ()=default
virtual tmp< volSymmTensorField > devRhoReff () const
virtual tmp< volSymmTensorField > devRhoReff (const volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Protected Member Functions
virtual void correctNut ()
tmp< volScalarField > phaseTransferCoeff () const
virtual tmp< fvScalarMatrix > kSource () const
virtual tmp< fvScalarMatrix > epsilonSource () const
Protected Attributes
dimensionedScalar alphaInversion_
Protected Attributes inherited from kEpsilon< BasicTurbulenceModel >
dimensionedScalar Cmu_
dimensionedScalar C1_
dimensionedScalar C2_
dimensionedScalar C3_
dimensionedScalar sigmak_
dimensionedScalar sigmaEps_
volScalarField k_
volScalarField epsilon_
Protected Attributes inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
volScalarField nut_
Detailed Description
template<class BasicTurbulenceModel>
class Foam::RASModels::continuousGasKEpsilon< BasicTurbulenceModel >
k-epsilon model for the gas-phase in a two-phase system supporting phase-inversion.
In the limit that the gas-phase fraction approaches zero a contribution from the other phase is blended into the k and epsilon equations up to the phase-fraction of alphaInversion at which point phase-inversion is considered to have occurred and the model reverts to the pure single-phase form.
This model is unpublished and is provided as a stable numerical framework on which a more physical model may be built.
The default model coefficients are
    continuousGasKEpsilonCoeffs
    {
        Cmu             0.09;
        C1              1.44;
        C2              1.92;
        C3              -0.33;
        sigmak          1.0;
        sigmaEps        1.3;
        alphaInversion  0.7;
    }
Source files
continuousGasKEpsilon.H
continuousGasKEpsilon.C
Definition at line 77 of file continuousGasKEpsilon.H.
Member Typedef Documentation
alphaField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 116 of file continuousGasKEpsilon.H.
rhoField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 117 of file continuousGasKEpsilon.H.
transportModel
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 118 of file continuousGasKEpsilon.H.
Constructor & Destructor Documentation
continuousGasKEpsilon()
template<class BasicTurbulenceModel > continuousGasKEpsilon (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Definition at line 38 of file continuousGasKEpsilon.C.
References Foam::type().
~continuousGasKEpsilon()
template<class BasicTurbulenceModel > virtual ~continuousGasKEpsilon () virtual default
Member Function Documentation
correctNut()
template<class BasicTurbulenceModel > void correctNut () protected virtual
Reimplemented from kEpsilon< BasicTurbulenceModel >.
Definition at line 111 of file continuousGasKEpsilon.C.
References kEpsilon< BasicTurbulenceModel >::correctNut(), turbulenceModel::epsilon(), Foam::exp(), fluid, turbulenceModel::k(), Foam::min(), options::New(), turbulenceModel::nut(), liquid::rho(), and Foam::sqr().
phaseTransferCoeff()
template<class BasicTurbulenceModel > tmp< volScalarField > phaseTransferCoeff () const protected
Definition at line 223 of file continuousGasKEpsilon.C.
References alpha, turbulenceModel::epsilon(), turbulenceModel::k(), Foam::max(), Foam::min(), rho, and U.
kSource()
template<class BasicTurbulenceModel > tmp< fvScalarMatrix > kSource () const protected virtual
Reimplemented from kEpsilon< BasicTurbulenceModel >.
Definition at line 246 of file continuousGasKEpsilon.C.
References turbulenceModel::k(), and Foam::fvm::Sp().
epsilonSource()
template<class BasicTurbulenceModel > tmp< fvScalarMatrix > epsilonSource () const protected virtual
Reimplemented from kEpsilon< BasicTurbulenceModel >.
Definition at line 259 of file continuousGasKEpsilon.C.
References turbulenceModel::epsilon(), and Foam::fvm::Sp().
TypeName()
template<class BasicTurbulenceModel > TypeName ("continuousGasKEpsilon< BasicTurbulenceModel >")
read()
template<class BasicTurbulenceModel > bool read () virtual
Reimplemented from kEpsilon< BasicTurbulenceModel >.
Definition at line 97 of file continuousGasKEpsilon.C.
liquidTurbulence()
template<class BasicTurbulenceModel > const turbulenceModel & liquidTurbulence () const
Definition at line 143 of file continuousGasKEpsilon.C.
References fluid, IOobject::groupName(), turbulenceModel::propertiesName, and U.
nuEff()
template<class BasicTurbulenceModel > tmp< Foam::volScalarField > nuEff () const virtual
Definition at line 171 of file continuousGasKEpsilon.C.
References IOobject::groupName(), Foam::max(), Foam::min(), nu, and rho.
rhoEff()
template<class BasicTurbulenceModel > tmp< Foam::volScalarField > rhoEff () const virtual
Definition at line 201 of file continuousGasKEpsilon.C.
References fluid, IOobject::groupName(), and liquid::rho().
R()
template<class BasicTurbulenceModel > tmp< volSymmTensorField > R () const virtual
Reimplemented from eddyViscosity< RASModel< BasicTurbulenceModel > >.
Definition at line 272 of file continuousGasKEpsilon.C.
References Foam::devTwoSymm(), Foam::fvc::grad(), IOobject::groupName(), Foam::I, k, IOobjectOption::NO_READ, and IOobjectOption::NO_WRITE.
Member Data Documentation
alphaInversion_
template<class BasicTurbulenceModel > dimensionedScalar alphaInversion_ protected
Definition at line 103 of file continuousGasKEpsilon.H.
The documentation for this class was generated from the following files:
src/TurbulenceModels/phaseCompressible/RAS/continuousGasKEpsilon/continuousGasKEpsilon.H
src/TurbulenceModels/phaseCompressible/RAS/continuousGasKEpsilon/continuousGasKEpsilon.C