OpenFOAM: lduPrimitiveProcessorInterface Class Reference
lduPrimitiveProcessorInterface Class Reference
Concrete implementation of processor interface. Used to temporarily store settings.
#include <lduPrimitiveProcessorInterface.H>
Public Member Functions
TypeNameNoDebug ("processorInterface")
void operator= (const lduPrimitiveProcessorInterface &)=delete
lduPrimitiveProcessorInterface (const labelUList &faceCells, const label myProcNo, const label neighbProcNo, const tensorField &forwardT, const int tag, const label comm=UPstream::worldComm)
lduPrimitiveProcessorInterface (const lduPrimitiveProcessorInterface &)
virtual ~lduPrimitiveProcessorInterface ()=default
virtual const labelUList & faceCells () const
virtual tmp< labelField > interfaceInternalField (const labelUList &internalData) const
virtual tmp< labelField > interfaceInternalField (const labelUList &internalData, const labelUList &faceCells) const
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &iF) const
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &iF, const labelUList &faceCells) const
virtual tmp< labelField > internalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &iF) const
virtual label comm () const
virtual int myProcNo () const
virtual int neighbProcNo () const
virtual const tensorField & forwardT () const
virtual int tag () const
int & tag ()
Public Member Functions inherited from lduInterface
TypeNameNoDebug ("lduInterface")
lduInterface () noexcept=default
virtual ~lduInterface ()=default
Public Member Functions inherited from processorLduInterface
TypeNameNoDebug ("processorLduInterface")
processorLduInterface () noexcept=default
virtual ~processorLduInterface ()=default
template<class Type >
void send (const UPstream::commsTypes commsType, const UList< Type > &f) const
template<class Type >
void receive (const UPstream::commsTypes commsType, UList< Type > &f) const
template<class Type >
tmp< Field< Type > > receive (const UPstream::commsTypes commsType, const label size) const
template<class Type >
void compressedSend (const UPstream::commsTypes commsType, const UList< Type > &f) const
template<class Type >
void compressedReceive (const UPstream::commsTypes commsType, UList< Type > &f) const
template<class Type >
tmp< Field< Type > > compressedReceive (const UPstream::commsTypes commsType, const label size) const
template<class Type >
Foam::tmp< Foam::Field< Type > > receive (const UPstream::commsTypes commsType, const label size) const
template<class Type >
Foam::tmp< Foam::Field< Type > > compressedReceive (const UPstream::commsTypes commsType, const label size) const
Detailed Description
Concrete implementation of processor interface. Used to temporarily store settings.
Source files
lduPrimitiveProcessorInterface.H
lduPrimitiveProcessorInterface.C
Definition at line 49 of file lduPrimitiveProcessorInterface.H.
Constructor & Destructor Documentation
lduPrimitiveProcessorInterface() [1/2]
lduPrimitiveProcessorInterface (const labelUList & faceCells, const label myProcNo, const label neighbProcNo, const tensorField & forwardT, const int tag, const label comm = UPstream::worldComm)
Definition at line 48 of file lduPrimitiveProcessorInterface.C.
lduPrimitiveProcessorInterface() [2/2]
lduPrimitiveProcessorInterface (const lduPrimitiveProcessorInterface & p)
Definition at line 34 of file lduPrimitiveProcessorInterface.C.
~lduPrimitiveProcessorInterface()
virtual ~lduPrimitiveProcessorInterface () virtual default
Member Function Documentation
TypeNameNoDebug()
TypeNameNoDebug ("processorInterface")
operator=()
void operator= (const lduPrimitiveProcessorInterface &) delete
faceCells()
virtual const labelUList & faceCells () const inline virtual
Implements lduInterface.
Definition at line 116 of file lduPrimitiveProcessorInterface.H.
interfaceInternalField() [1/2]
Foam::tmp< Foam::labelField > interfaceInternalField (const labelUList & internalData) const virtual
Implements lduInterface.
Definition at line 70 of file lduPrimitiveProcessorInterface.C.
interfaceInternalField() [2/2]
Foam::tmp< Foam::labelField > interfaceInternalField (const labelUList & internalData, const labelUList & faceCells) const virtual
Implements lduInterface.
Definition at line 80 of file lduPrimitiveProcessorInterface.C.
References fld(), forAll, and tmp< T >::New().
initInternalFieldTransfer() [1/2]
void initInternalFieldTransfer (const Pstream::commsTypes commsType, const labelUList & iF) const virtual
Reimplemented from lduInterface.
Definition at line 97 of file lduPrimitiveProcessorInterface.C.
References processorLduInterface::send().
initInternalFieldTransfer() [2/2]
void initInternalFieldTransfer (const Pstream::commsTypes commsType, const labelUList & iF, const labelUList & faceCells) const virtual
Reimplemented from lduInterface.
Definition at line 107 of file lduPrimitiveProcessorInterface.C.
References processorLduInterface::send().
internalFieldTransfer()
Foam::tmp< Foam::labelField > internalFieldTransfer (const Pstream::commsTypes commsType, const labelUList & iF) const virtual
Implements lduInterface.
Definition at line 123 of file lduPrimitiveProcessorInterface.C.
comm()
virtual label comm () const inline virtual
Implements processorLduInterface.
Definition at line 165 of file lduPrimitiveProcessorInterface.H.
myProcNo()
virtual int myProcNo () const inline virtual
Implements processorLduInterface.
Definition at line 171 of file lduPrimitiveProcessorInterface.H.
neighbProcNo()
virtual int neighbProcNo () const inline virtual
Implements processorLduInterface.
Definition at line 177 of file lduPrimitiveProcessorInterface.H.
forwardT()
virtual const tensorField & forwardT () const inline virtual
Implements processorLduInterface.
Definition at line 183 of file lduPrimitiveProcessorInterface.H.
tag() [1/2]
virtual int tag () const inline virtual
Implements processorLduInterface.
Definition at line 189 of file lduPrimitiveProcessorInterface.H.
tag() [2/2]
int & tag () inline
Definition at line 198 of file lduPrimitiveProcessorInterface.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/lduMatrix/lduAddressing/lduInterface/lduPrimitiveProcessorInterface.H
src/OpenFOAM/matrices/lduMatrix/lduAddressing/lduInterface/lduPrimitiveProcessorInterface.C