OpenFOAM: faEdgeMapper Class Reference
faEdgeMapper Class Reference
FA edge mapper. Currently, edge-based finite area data is not mapped, but only resized, since edge-based mapping data is not available.
#include <faEdgeMapper.H>
Public Member Functions
faEdgeMapper (const faMesh &mesh, const mapPolyMesh &mpm)
virtual ~faEdgeMapper ()
virtual label size () const
virtual label sizeBeforeMapping () const
virtual bool direct () const
virtual bool hasUnmapped () const
virtual const labelUList & directAddressing () const
virtual const labelListList & addressing () const
virtual const scalarListList & weights () const
virtual bool insertedObjects () const
virtual const labelList & insertedObjectLabels () const
Public Member Functions inherited from morphFieldMapper
morphFieldMapper ()=default
virtual ~morphFieldMapper ()=default
Public Member Functions inherited from FieldMapper
FieldMapper ()=default
virtual ~FieldMapper ()=default
virtual bool distributed () const
virtual const mapDistributeBase & distributeMap () const
template<class Type >
tmp< Field< Type > > operator() (const Field< Type > &fld) const
Detailed Description
FA edge mapper. Currently, edge-based finite area data is not mapped, but only resized, since edge-based mapping data is not available.
Author Zeljko Tukovic, FMENA Hrvoje Jasak, Wikki Ltd.
Source files
faEdgeMapper.H
faEdgeMapper.C
Definition at line 55 of file faEdgeMapper.H.
Constructor & Destructor Documentation
faEdgeMapper()
faEdgeMapper (const faMesh & mesh, const mapPolyMesh & mpm)
Definition at line 52 of file faEdgeMapper.C.
~faEdgeMapper()
~faEdgeMapper () virtual
Definition at line 68 of file faEdgeMapper.C.
Member Function Documentation
size()
virtual label size () const inline virtual
Implements FieldMapper.
Definition at line 111 of file faEdgeMapper.H.
References faMesh::nInternalEdges().
sizeBeforeMapping()
virtual label sizeBeforeMapping () const inline virtual
Implements morphFieldMapper.
Definition at line 117 of file faEdgeMapper.H.
direct()
virtual bool direct () const inline virtual
Implements FieldMapper.
Definition at line 123 of file faEdgeMapper.H.
hasUnmapped()
virtual bool hasUnmapped () const inline virtual
Implements FieldMapper.
Definition at line 128 of file faEdgeMapper.H.
directAddressing()
const Foam::labelUList & directAddressing () const virtual
Reimplemented from FieldMapper.
Definition at line 76 of file faEdgeMapper.C.
addressing()
const Foam::labelListList & addressing () const virtual
Reimplemented from FieldMapper.
Definition at line 87 of file faEdgeMapper.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and List< labelList >::null().
weights()
const Foam::scalarListList & weights () const virtual
Reimplemented from FieldMapper.
Definition at line 97 of file faEdgeMapper.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and List< scalarList >::null().
insertedObjects()
virtual bool insertedObjects () const inline virtual
Implements morphFieldMapper.
Definition at line 143 of file faEdgeMapper.H.
insertedObjectLabels()
virtual const labelList & insertedObjectLabels () const inline virtual
Implements morphFieldMapper.
Definition at line 149 of file faEdgeMapper.H.
References List< label >::null().
The documentation for this class was generated from the following files:
src/finiteArea/faMesh/faMeshMapper/faEdgeMapper.H
src/finiteArea/faMesh/faMeshMapper/faEdgeMapper.C