OpenFOAM: polynomialSolidTransport< Thermo, PolySize > Class Template Reference
polynomialSolidTransport< Thermo, PolySize > Class Template Reference
Transport package using polynomial functions for solid kappa.
#include <polynomialSolidTransport.H>
Public Member Functions
polynomialSolidTransport (const word &, const polynomialSolidTransport &)
polynomialSolidTransport (const dictionary &dict)
autoPtr< polynomialSolidTransport > clone () const
scalar mu (const scalar p, const scalar T) const
scalar kappa (const scalar p, const scalar T) const
vector Kappa (const scalar p, const scalar T) const
scalar alphah (const scalar p, const scalar T) const
void write (Ostream &os) const
void operator+= (const polynomialSolidTransport &)
void operator*= (const scalar)
Static Public Member Functions
static autoPtr< polynomialSolidTransport > New (const dictionary &dict)
static word typeName ()
Static Public Attributes
static const bool isotropic = true
Friends
polynomialSolidTransport operator+ (const polynomialSolidTransport &, const polynomialSolidTransport &)
polynomialSolidTransport operator* (const scalar, const polynomialSolidTransport &)
Ostream & operator (Ostream &, const polynomialSolidTransport &)
Detailed Description
template<class Thermo, int PolySize = 8>
class Foam::polynomialSolidTransport< Thermo, PolySize >
Transport package using polynomial functions for solid kappa.
Usage
Property Description
kappaCoeffs<8> Thermal conductivity polynomial coefficients
Example of the specification of the transport properties:
    transport
    {
        kappaCoeffs<8>     ( 1000 -0.05 0.003 0 0 0 0 0 );
    }
The polynomial expression is evaluated as so:
Note
Thermal conductivity polynomial coefficients evaluate to an expression in [W/m/K].
Source files
polynomialSolidTransport.H
polynomialSolidTransportI.H
polynomialSolidTransport.C
See also
Foam::Polynomial
Definition at line 109 of file polynomialSolidTransport.H.
Constructor & Destructor Documentation
polynomialSolidTransport() [1/2]
template<class Thermo , int PolySize> polynomialSolidTransport (const word & name, const polynomialSolidTransport< Thermo, PolySize > & pt) inline
Definition at line 39 of file polynomialSolidTransportI.H.
References Foam::name().
polynomialSolidTransport() [2/2]
template<class Thermo , int PolySize> polynomialSolidTransport (const dictionary & dict) explicit
Definition at line 27 of file polynomialSolidTransport.C.
Member Function Documentation
clone()
template<class Thermo , int PolySize> Foam::autoPtr< Foam::polynomialSolidTransport< Thermo, PolySize > > clone () const inline
Definition at line 53 of file polynomialSolidTransportI.H.
References Foam::New().
New()
template<class Thermo , int PolySize> Foam::autoPtr< Foam::polynomialSolidTransport< Thermo, PolySize > > New (const dictionary & dict) inline static
Definition at line 61 of file polynomialSolidTransportI.H.
References dict, and Foam::New().
typeName()
template<class Thermo , int PolySize = 8> static word typeName () inline static
Definition at line 166 of file polynomialSolidTransport.H.
mu()
template<class Thermo , int PolySize> Foam::scalar mu (const scalar p, const scalar T) const inline
Definition at line 70 of file polynomialSolidTransportI.H.
References NotImplemented.
kappa()
template<class Thermo , int PolySize> Foam::scalar kappa (const scalar p, const scalar T) const inline
Definition at line 82 of file polynomialSolidTransportI.H.
References T.
Kappa()
template<class Thermo , int PolySize> Foam::vector Kappa (const scalar p, const scalar T) const inline
Definition at line 93 of file polynomialSolidTransportI.H.
References T.
alphah()
template<class Thermo , int PolySize> Foam::scalar alphah (const scalar p, const scalar T) const inline
Definition at line 105 of file polynomialSolidTransportI.H.
References Cp, p, and T.
write()
template<class Thermo , int PolySize> void write (Ostream & os) const
Definition at line 40 of file polynomialSolidTransport.C.
References Ostream::beginBlock(), Ostream::endBlock(), os(), and Ostream::writeEntry().
operator+=()
template<class Thermo , int PolySize = 8> void operator+= (const polynomialSolidTransport< Thermo, PolySize > &) inline
Definition at line 117 of file polynomialSolidTransportI.H.
References Y.
operator*=()
template<class Thermo , int PolySize> void operator*= (const scalar s) inline
Definition at line 134 of file polynomialSolidTransportI.H.
References s().
Friends And Related Symbol Documentation
operator+
template<class Thermo , int PolySize = 8> polynomialSolidTransport operator+ (const polynomialSolidTransport< Thermo, PolySize > & , const polynomialSolidTransport< Thermo, PolySize > &) friend
operator*
template<class Thermo , int PolySize = 8> polynomialSolidTransport operator* (const scalar , const polynomialSolidTransport< Thermo, PolySize > &) friend
operator
template<class Thermo , int PolySize = 8> Ostream & operator (Ostream & , const polynomialSolidTransport< Thermo, PolySize > &) friend
Member Data Documentation
isotropic
template<class Thermo , int PolySize = 8> const bool isotropic = true static
Definition at line 172 of file polynomialSolidTransport.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/solidSpecie/transport/polynomial/polynomialSolidTransport.H
src/thermophysicalModels/solidSpecie/transport/polynomial/polynomialSolidTransport.C
src/thermophysicalModels/solidSpecie/transport/polynomial/polynomialSolidTransportI.H