OpenFOAM: CodedSource< Type > Class Template Reference
CodedSource< Type > Class Template Reference
#include <CodedFvSource.H>
Public Member Functions
TypeName ("coded")
CodedSource (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
fv::option & redirectOption () const
virtual void correct (GeometricField< Type, fvPatchField, volMesh > &)
virtual void addSup (fvMatrix< Type > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< Type > &eqn, const label fieldi)
virtual void constrain (fvMatrix< Type > &eqn, const label fieldi)
virtual bool read (const dictionary &dict)
Public Member Functions inherited from cellSetOption
TypeName ("cellSetOption")
cellSetOption (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
virtual ~cellSetOption ()=default
scalar timeStart () const noexcept
scalar duration () const noexcept
bool inTimeLimits (const scalar timeValue) const
bool useSubMesh () const noexcept
selectionModeType selectionMode () const noexcept
const wordRes & selectionNames () const noexcept
const wordRe & zoneName () const
scalar V () const noexcept
const labelList & cells () const noexcept
scalar timeStart (scalar val) noexcept
scalar duration (scalar val) noexcept
virtual bool isActive ()
const word & cellSetName () const
Public Member Functions inherited from option
TypeName ("option")
declareRunTimeSelectionTable (autoPtr, option, dictionary,(const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh),(name, modelType, dict, mesh))
option (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
autoPtr< option > clone () const
virtual ~option ()=default
const word & name () const noexcept
const fvMesh & mesh () const noexcept
const dictionary & coeffs () const noexcept
bool active () const noexcept
void setApplied (const label fieldi)
bool active (const bool on) noexcept
virtual label applyToField (const word &fieldName) const
virtual void checkApplied () const
virtual void addSup (fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (fvMatrix< vector > &eqn, const label fieldi)
virtual void addSup (fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (fvMatrix< tensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< scalar > &eqn, const label fieldi)
virtual void constrain (fvMatrix< vector > &eqn, const label fieldi)
virtual void constrain (fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< tensor > &eqn, const label fieldi)
virtual void correct (volScalarField &field)
virtual void correct (volVectorField &field)
virtual void correct (volSphericalTensorField &field)
virtual void correct (volSymmTensorField &field)
virtual void correct (volTensorField &field)
virtual void postProcessSens (scalarField &sensField, const word &fieldName=word::null, const word &designVariablesName=word::null)
virtual void postProcessSens (vectorField &sensField, const word &fieldName=word::null, const word &designVariablesName=word::null)
virtual void postProcessSens (tensorField &sensField, const word &fieldName=word::null, const word &designVariablesName=word::null)
virtual void writeHeader (Ostream &) const
virtual void writeFooter (Ostream &) const
virtual void writeData (Ostream &) const
Static Public Attributes
static constexpr const char *const codeTemplateC = "codedFvOptionTemplate.C"
static constexpr const char *const codeTemplateH = "codedFvOptionTemplate.H"
Static Public Attributes inherited from cellSetOption
static const Enum< selectionModeType > selectionModeTypeNames_
Protected Member Functions
virtual dlLibraryTable & libs () const
virtual string description () const
virtual void clearRedirect () const
virtual const dictionary & codeDict () const
virtual void prepare (dynamicCode &, const dynamicCodeContext &) const
Protected Member Functions inherited from cellSetOption
void setSelection (const dictionary &dict)
void setCellSelection ()
void setVol ()
Protected Member Functions inherited from option
void resetApplied ()
Protected Member Functions inherited from codedBase
dynamicCodeContext & codeContext ()
void setCodeContext (const dictionary &dict)
void append (const std::string &str)
void updateLibrary (const word &name, const dynamicCodeContext &context) const
void updateLibrary (const word &name, const dictionary &dict) const
void updateLibrary (const word &name) const
ClassName ("codedBase")
codedBase (const codedBase &)=delete
void operator= (const codedBase &)=delete
codedBase ()=default
virtual ~codedBase ()=default
Protected Attributes
word name_
string codeCorrect_
string codeAddSup_
string codeAddSupRho_
string codeConstrain_
autoPtr< fv::option > redirectOptionPtr_
Protected Attributes inherited from cellSetOption
scalar timeStart_
scalar duration_
selectionModeType selectionMode_
wordRes selectionNames_
List< point > points_
dictionary geometricSelection_
labelList cells_
scalar V_
Protected Attributes inherited from option
const word name_
const word modelType_
const fvMesh & mesh_
dictionary dict_
dictionary coeffs_
wordList fieldNames_
List< bool > applied_
bool active_
Additional Inherited Members
Public Types inherited from cellSetOption
enum selectionModeType {
smAll , smCellSet , smCellZone , smPoints ,
smGeometric , smCellType
}
Static Public Member Functions inherited from option
static autoPtr< option > New (const word &name, const dictionary &dict, const fvMesh &mesh)
Public Attributes inherited from option
bool log
Static Protected Member Functions inherited from codedBase
static void writeCodeDict (Ostream &os, const dictionary &dict)
static const dictionary & codeDict (const objectRegistry &obr, const word &dictName="codeDict")
Detailed Description
template<class Type>
class Foam::fv::CodedSource< Type >
Definition at line 149 of file CodedFvSource.H.
Constructor & Destructor Documentation
CodedSource()
template<class Type > CodedSource (const word & name, const word & modelType, const dictionary & dict, const fvMesh & mesh)
Definition at line 133 of file CodedFvSource.C.
References dict, Foam::name(), and CodedSource< Type >::read().
Member Function Documentation
libs()
template<class Type > Foam::dlLibraryTable & libs () const protected virtual
Implements codedBase.
Definition at line 32 of file CodedFvSource.C.
description()
template<class Type > Foam::string description () const protected virtual
Implements codedBase.
Definition at line 39 of file CodedFvSource.C.
clearRedirect()
template<class Type > void clearRedirect () const protected virtual
Implements codedBase.
Definition at line 46 of file CodedFvSource.C.
codeDict()
template<class Type > const Foam::dictionary & codeDict () const protected virtual
Implements codedBase.
Definition at line 53 of file CodedFvSource.C.
prepare()
template<class Type > void prepare (dynamicCode & dynCode, const dynamicCodeContext & context) const protected virtual
Implements codedBase.
Definition at line 60 of file CodedFvSource.C.
References DetailInfo, Foam::endl(), dynamicCodeContext::libs(), dynamicCodeContext::options(), and dynamicCodeContext::sha1().
TypeName()
template<class Type > TypeName ("coded")
redirectOption()
template<class Type > Foam::fv::option & redirectOption () const
Definition at line 201 of file CodedFvSource.C.
References option::New(), and PtrList< T >::set().
correct()
template<class Type > void correct (GeometricField< Type, fvPatchField, volMesh > & field) virtual
Definition at line 221 of file CodedFvSource.C.
References DebugInfo, Foam::endl(), and field().
addSup() [1/2]
template<class Type > void addSup (fvMatrix< Type > & eqn, const label fieldi) virtual
Definition at line 236 of file CodedFvSource.C.
References DebugInfo, and Foam::endl().
addSup() [2/2]
template<class Type > void addSup (const volScalarField & rho, fvMatrix< Type > & eqn, const label fieldi) virtual
Definition at line 252 of file CodedFvSource.C.
References DebugInfo, Foam::endl(), and rho.
constrain()
template<class Type > void constrain (fvMatrix< Type > & eqn, const label fieldi) virtual
Definition at line 269 of file CodedFvSource.C.
References DebugInfo, and Foam::endl().
read()
template<class Type > bool read (const dictionary & dict) virtual
Reimplemented from cellSetOption.
Definition at line 150 of file CodedFvSource.C.
References codedBase::codeContext(), dict, keyType::LITERAL, cellSetOption::read(), option::resetApplied(), and codedBase::setCodeContext().
Referenced by CodedSource< Type >::CodedSource().
Member Data Documentation
name_
template<class Type > word name_ protected
Definition at line 158 of file CodedFvSource.H.
codeCorrect_
template<class Type > string codeCorrect_ protected
Definition at line 160 of file CodedFvSource.H.
codeAddSup_
template<class Type > string codeAddSup_ protected
Definition at line 161 of file CodedFvSource.H.
codeAddSupRho_
template<class Type > string codeAddSupRho_ protected
Definition at line 162 of file CodedFvSource.H.
codeConstrain_
template<class Type > string codeConstrain_ protected
Definition at line 163 of file CodedFvSource.H.
redirectOptionPtr_
template<class Type > autoPtr<fv::option> redirectOptionPtr_ mutable protected
Definition at line 166 of file CodedFvSource.H.
codeTemplateC
template<class Type > constexpr const char* const codeTemplateC = "codedFvOptionTemplate.C" static constexpr
Definition at line 192 of file CodedFvSource.H.
codeTemplateH
template<class Type > constexpr const char* const codeTemplateH = "codedFvOptionTemplate.H" static constexpr
Definition at line 196 of file CodedFvSource.H.
The documentation for this class was generated from the following files:
src/fvOptions/sources/general/codedSource/CodedFvSource.H
src/fvOptions/sources/general/codedSource/CodedFvSource.C