OpenFOAM: surfaceInterpolation Class Reference
surfaceInterpolation Class Reference
Cell to surface interpolation scheme. Included in fvMesh.
#include <surfaceInterpolation.H>
Public Member Functions
ClassName ("surfaceInterpolation")
surfaceInterpolation (const fvMesh &)
virtual ~surfaceInterpolation ()
virtual const fvGeometryScheme & geometry () const
void geometry (tmp< fvGeometryScheme > &)
virtual const surfaceScalarField & weights () const
virtual const surfaceScalarField & deltaCoeffs () const
virtual const surfaceScalarField & nonOrthDeltaCoeffs () const
virtual const surfaceVectorField & nonOrthCorrectionVectors () const
virtual bool movePoints ()
virtual void updateGeom ()
bool hasWeights () const noexcept
virtual void updateMesh (const mapPolyMesh &mpm)
Protected Member Functions
void clearOut ()
Detailed Description
Cell to surface interpolation scheme. Included in fvMesh.
Source files
surfaceInterpolation.H
surfaceInterpolation.C
Definition at line 56 of file surfaceInterpolation.H.
Constructor & Destructor Documentation
surfaceInterpolation()
surfaceInterpolation (const fvMesh & fvm) explicit
Definition at line 56 of file surfaceInterpolation.C.
~surfaceInterpolation()
~surfaceInterpolation () virtual
Definition at line 69 of file surfaceInterpolation.C.
Member Function Documentation
clearOut()
void clearOut () protected
Definition at line 43 of file surfaceInterpolation.C.
References PtrList< T >::clear().
Referenced by fvMesh::clearOutLocal(), dynamicRefineFvMesh::mapFields(), and fvMesh::movePoints().
ClassName()
ClassName ("surfaceInterpolation")
geometry() [1/2]
const Foam::fvGeometryScheme & geometry () const virtual
Definition at line 77 of file surfaceInterpolation.C.
References fvGeometryScheme::New().
Referenced by fvMeshTools::setBasicGeometry().
geometry() [2/2]
void geometry (tmp< fvGeometryScheme > & schemePtr)
Definition at line 93 of file surfaceInterpolation.C.
weights()
const Foam::surfaceScalarField & weights () const virtual
Definition at line 99 of file surfaceInterpolation.C.
Referenced by limitedSurfaceInterpolationScheme< Type >::weights().
deltaCoeffs()
const Foam::surfaceScalarField & deltaCoeffs () const virtual
Definition at line 110 of file surfaceInterpolation.C.
Referenced by reactingOneDim::solidRegionDiffNo().
nonOrthDeltaCoeffs()
const Foam::surfaceScalarField & nonOrthDeltaCoeffs () const virtual
Definition at line 122 of file surfaceInterpolation.C.
Referenced by CentredFitSnGradData< Polynomial >::calcFit().
nonOrthCorrectionVectors()
const Foam::surfaceVectorField & nonOrthCorrectionVectors () const virtual
Definition at line 134 of file surfaceInterpolation.C.
movePoints()
bool movePoints () virtual
Reimplemented in fvMesh.
Definition at line 148 of file surfaceInterpolation.C.
References Foam::endl(), and Foam::Pout.
updateGeom()
void updateGeom () virtual
Reimplemented in fvMesh.
Definition at line 166 of file surfaceInterpolation.C.
References Foam::endl(), and Foam::Pout.
Referenced by fvMesh::updateGeom().
hasWeights()
bool hasWeights () const inline noexcept
Definition at line 139 of file surfaceInterpolation.H.
updateMesh()
void updateMesh (const mapPolyMesh & mpm) virtual
Reimplemented in fvMesh.
Definition at line 180 of file surfaceInterpolation.C.
References Foam::endl(), and Foam::Pout.
Referenced by fvMesh::updateMesh().
The documentation for this class was generated from the following files:
src/finiteVolume/interpolation/surfaceInterpolation/surfaceInterpolation/surfaceInterpolation.H
src/finiteVolume/interpolation/surfaceInterpolation/surfaceInterpolation/surfaceInterpolation.C