OpenFOAM: indirect Class Reference
indirect Class Reference
A coordinate system forward to a global coordinate system that is normally provided by the constant/coordinateSystems file.
#include <indirectCS.H>
Public Member Functions
TypeName ("indirect")
indirect ()=delete
indirect (const indirect &csys)
indirect (indirect &&csys)
indirect (const objectRegistry &obr, const word &name)
indirect (const objectRegistry &obr, const dictionary &dict, IOobjectOption::readOption readOrigin=IOobjectOption::NO_READ)
virtual autoPtr< coordinateSystem > clone () const
virtual ~indirect ()=default
virtual bool valid () const
virtual bool uniform () const
virtual const coordinateSystem & cs () const
virtual const point & origin () const
virtual const coordinateRotation & rotation () const
virtual const word & name () const
virtual const string & note () const
virtual const tensor & R () const
virtual const vector e1 () const
virtual const vector e2 () const
virtual const vector e3 () const
void rename (const word &newName)
string & note ()
virtual point & origin ()
virtual void clear ()
virtual void rotation (autoPtr< coordinateRotation > &&crot)
virtual void write (Ostream &os) const
virtual void writeEntry (Ostream &os) const
virtual void writeEntry (const word &keyword, Ostream &os) const
void operator= (const coordinateSystem &csys)=delete
void operator= (coordinateSystem &&csys)=delete
virtual tensor R (const point &global) const
virtual tmp< tensorField > R (const UList< point > &global) const
virtual tmp< tensorField > R (const pointUIndList &global) const
Public Member Functions inherited from coordinateSystem
TypeName ("coordinateSystem")
coordinateSystem ()
coordinateSystem (const coordinateRotation &crot)
coordinateSystem (coordinateRotation &&crot)
coordinateSystem (const coordinateSystem &csys)
coordinateSystem (coordinateSystem &&csys)
coordinateSystem (autoPtr< coordinateSystem > &&csys)
coordinateSystem (const word &name, const coordinateSystem &csys)
coordinateSystem (const point &origin, const coordinateRotation &crot)
coordinateSystem (const point &origin, const vector &axis, const vector &dirn)
coordinateSystem (const word &name, const point &origin, const coordinateRotation &crot)
coordinateSystem (const word &name, const point &origin, const vector &axis, const vector &dirn)
coordinateSystem (const dictionary &dict, IOobjectOption::readOption readOrigin=IOobjectOption::MUST_READ)
coordinateSystem (const dictionary &dict, const word &dictName, IOobjectOption::readOption readOrigin=IOobjectOption::MUST_READ)
declareRunTimeSelectionTable (autoPtr, coordinateSystem, dictionary,(const dictionary &dict, IOobjectOption::readOption readOrigin),(dict, readOrigin))
declareRunTimeSelectionTable (autoPtr, coordinateSystem, registry,(const objectRegistry &obr, const dictionary &dict, IOobjectOption::readOption readOrigin),(obr, dict, readOrigin))
virtual ~coordinateSystem ()=default
void operator= (const coordinateSystem &csys)
void operator= (coordinateSystem &&csys)
void operator= (const autoPtr< coordinateSystem > &csys)
void operator= (autoPtr< coordinateSystem > &&csys)
point transformPoint (const point &localCart) const
tmp< pointField > transformPoint (const UList< point > &localCart) const
tmp< pointField > transformPoint (const pointUIndList &localCart) const
point invTransformPoint (const point &global) const
tmp< pointField > invTransformPoint (const UList< point > &global) const
tmp< pointField > invTransformPoint (const pointUIndList &global) const
point globalPosition (const point &local) const
tmp< pointField > globalPosition (const pointField &local) const
point localPosition (const point &global) const
tmp< pointField > localPosition (const pointField &global) const
vector globalVector (const vector &local) const
tmp< vectorField > globalVector (const vectorField &local) const
vector localVector (const vector &global) const
tmp< vectorField > localVector (const vectorField &global) const
virtual symmTensor transformPrincipal (const vector &input) const
With constant rotation tensor.
virtual tmp< Field< symmTensor > > transformPrincipal (const UList< vector > &input) const
With constant rotation tensor.
virtual symmTensor transformPrincipal (const point &global, const vector &input) const
With rotation tensor at given global position.
virtual tmp< Field< symmTensor > > transformPrincipal (const UList< point > &global, const vector &input) const
With rotation tensors at given global positions.
virtual tmp< Field< symmTensor > > transformPrincipal (const pointUIndList &global, const vector &input) const
With rotation tensors at given global positions.
virtual tmp< Field< symmTensor > > transformPrincipal (const UList< point > &global, const UList< vector > &input) const
With rotation tensors at given global positions.
virtual tmp< Field< symmTensor > > transformPrincipal (const pointUIndList &global, const UList< vector > &input) const
With rotation tensors at given global positions.
virtual scalar transform (const scalar &input) const
With constant rotation tensor.
virtual tmp< Field< scalar > > transform (const UList< scalar > &input) const
With constant rotation tensor.
virtual scalar transform (const point &global, const scalar &input) const
With rotation tensor at given global position.
virtual tmp< Field< scalar > > transform (const UList< point > &global, const scalar &input) const
With rotation tensors at given global positions.
virtual tmp< Field< scalar > > transform (const pointUIndList &global, const scalar &input) const
With rotation tensors at given global positions.
virtual tmp< Field< scalar > > transform (const UList< point > &global, const UList< scalar > &input) const
With rotation tensors at given global positions.
virtual tmp< Field< scalar > > transform (const pointUIndList &global, const UList< scalar > &input) const
With rotation tensors at given global positions.
virtual vector transform (const vector &input) const
With constant rotation tensor.
virtual tmp< Field< vector > > transform (const UList< vector > &input) const
With constant rotation tensor.
virtual vector transform (const point &global, const vector &input) const
With rotation tensor at given global position.
virtual tmp< Field< vector > > transform (const UList< point > &global, const vector &input) const
With rotation tensors at given global positions.
virtual tmp< Field< vector > > transform (const pointUIndList &global, const vector &input) const
With rotation tensors at given global positions.
virtual tmp< Field< vector > > transform (const UList< point > &global, const UList< vector > &input) const
With rotation tensors at given global positions.
virtual tmp< Field< vector > > transform (const pointUIndList &global, const UList< vector > &input) const
With rotation tensors at given global positions.
virtual sphericalTensor transform (const sphericalTensor &input) const
With constant rotation tensor.
virtual tmp< Field< sphericalTensor > > transform (const UList< sphericalTensor > &input) const
With constant rotation tensor.
virtual sphericalTensor transform (const point &global, const sphericalTensor &input) const
With rotation tensor at given global position.
virtual tmp< Field< sphericalTensor > > transform (const UList< point > &global, const sphericalTensor &input) const
With rotation tensors at given global positions.
virtual tmp< Field< sphericalTensor > > transform (const pointUIndList &global, const sphericalTensor &input) const
With rotation tensors at given global positions.
virtual tmp< Field< sphericalTensor > > transform (const UList< point > &global, const UList< sphericalTensor > &input) const
With rotation tensors at given global positions.
virtual tmp< Field< sphericalTensor > > transform (const pointUIndList &global, const UList< sphericalTensor > &input) const
With rotation tensors at given global positions.
virtual symmTensor transform (const symmTensor &input) const
With constant rotation tensor.
virtual tmp< Field< symmTensor > > transform (const UList< symmTensor > &input) const
With constant rotation tensor.
virtual symmTensor transform (const point &global, const symmTensor &input) const
With rotation tensor at given global position.
virtual tmp< Field< symmTensor > > transform (const UList< point > &global, const symmTensor &input) const
With rotation tensors at given global positions.
virtual tmp< Field< symmTensor > > transform (const pointUIndList &global, const symmTensor &input) const
With rotation tensors at given global positions.
virtual tmp< Field< symmTensor > > transform (const UList< point > &global, const UList< symmTensor > &input) const
With rotation tensors at given global positions.
virtual tmp< Field< symmTensor > > transform (const pointUIndList &global, const UList< symmTensor > &input) const
With rotation tensors at given global positions.
virtual tensor transform (const tensor &input) const
With constant rotation tensor.
virtual tmp< Field< tensor > > transform (const UList< tensor > &input) const
With constant rotation tensor.
virtual tensor transform (const point &global, const tensor &input) const
With rotation tensor at given global position.
virtual tmp< Field< tensor > > transform (const UList< point > &global, const tensor &input) const
With rotation tensors at given global positions.
virtual tmp< Field< tensor > > transform (const pointUIndList &global, const tensor &input) const
With rotation tensors at given global positions.
virtual tmp< Field< tensor > > transform (const UList< point > &global, const UList< tensor > &input) const
With rotation tensors at given global positions.
virtual tmp< Field< tensor > > transform (const pointUIndList &global, const UList< tensor > &input) const
With rotation tensors at given global positions.
virtual scalar invTransform (const scalar &input) const
With constant rotation tensor.
virtual tmp< Field< scalar > > invTransform (const UList< scalar > &input) const
With constant rotation tensor.
virtual scalar invTransform (const point &global, const scalar &input) const
With rotation tensor at given global position.
virtual tmp< Field< scalar > > invTransform (const UList< point > &global, const scalar &input) const
With rotation tensors at given global positions.
virtual tmp< Field< scalar > > invTransform (const pointUIndList &global, const scalar &input) const
With rotation tensors at given global positions.
virtual tmp< Field< scalar > > invTransform (const UList< point > &global, const UList< scalar > &input) const
With rotation tensors at given global positions.
virtual tmp< Field< scalar > > invTransform (const pointUIndList &global, const UList< scalar > &input) const
With rotation tensors at given global positions.
virtual vector invTransform (const vector &input) const
With constant rotation tensor.
virtual tmp< Field< vector > > invTransform (const UList< vector > &input) const
With constant rotation tensor.
virtual vector invTransform (const point &global, const vector &input) const
With rotation tensor at given global position.
virtual tmp< Field< vector > > invTransform (const UList< point > &global, const vector &input) const
With rotation tensors at given global positions.
virtual tmp< Field< vector > > invTransform (const pointUIndList &global, const vector &input) const
With rotation tensors at given global positions.
virtual tmp< Field< vector > > invTransform (const UList< point > &global, const UList< vector > &input) const
With rotation tensors at given global positions.
virtual tmp< Field< vector > > invTransform (const pointUIndList &global, const UList< vector > &input) const
With rotation tensors at given global positions.
virtual sphericalTensor invTransform (const sphericalTensor &input) const
With constant rotation tensor.
virtual tmp< Field< sphericalTensor > > invTransform (const UList< sphericalTensor > &input) const
With constant rotation tensor.
virtual sphericalTensor invTransform (const point &global, const sphericalTensor &input) const
With rotation tensor at given global position.
virtual tmp< Field< sphericalTensor > > invTransform (const UList< point > &global, const sphericalTensor &input) const
With rotation tensors at given global positions.
virtual tmp< Field< sphericalTensor > > invTransform (const pointUIndList &global, const sphericalTensor &input) const
With rotation tensors at given global positions.
virtual tmp< Field< sphericalTensor > > invTransform (const UList< point > &global, const UList< sphericalTensor > &input) const
With rotation tensors at given global positions.
virtual tmp< Field< sphericalTensor > > invTransform (const pointUIndList &global, const UList< sphericalTensor > &input) const
With rotation tensors at given global positions.
virtual symmTensor invTransform (const symmTensor &input) const
With constant rotation tensor.
virtual tmp< Field< symmTensor > > invTransform (const UList< symmTensor > &input) const
With constant rotation tensor.
virtual symmTensor invTransform (const point &global, const symmTensor &input) const
With rotation tensor at given global position.
virtual tmp< Field< symmTensor > > invTransform (const UList< point > &global, const symmTensor &input) const
With rotation tensors at given global positions.
virtual tmp< Field< symmTensor > > invTransform (const pointUIndList &global, const symmTensor &input) const
With rotation tensors at given global positions.
virtual tmp< Field< symmTensor > > invTransform (const UList< point > &global, const UList< symmTensor > &input) const
With rotation tensors at given global positions.
virtual tmp< Field< symmTensor > > invTransform (const pointUIndList &global, const UList< symmTensor > &input) const
With rotation tensors at given global positions.
virtual tensor invTransform (const tensor &input) const
With constant rotation tensor.
virtual tmp< Field< tensor > > invTransform (const UList< tensor > &input) const
With constant rotation tensor.
virtual tensor invTransform (const point &global, const tensor &input) const
With rotation tensor at given global position.
virtual tmp< Field< tensor > > invTransform (const UList< point > &global, const tensor &input) const
With rotation tensors at given global positions.
virtual tmp< Field< tensor > > invTransform (const pointUIndList &global, const tensor &input) const
With rotation tensors at given global positions.
virtual tmp< Field< tensor > > invTransform (const UList< point > &global, const UList< tensor > &input) const
With rotation tensors at given global positions.
virtual tmp< Field< tensor > > invTransform (const pointUIndList &global, const UList< tensor > &input) const
With rotation tensors at given global positions.
template<class PointField >
Foam::tmp< Foam::tensorField > rotationsImpl (const PointField &global) const
template<class PointField >
Foam::tmp< Foam::pointField > transformPointImpl (const PointField &localCart) const
template<class PointField >
Foam::tmp< Foam::pointField > invTransformPointImpl (const PointField &global) const
template<class RetType , class Type , class BinaryOp >
Foam::tmp< Foam::Field< RetType > > manyTimesImpl (const tensor &tt, const UList< Type > &input, const BinaryOp &bop)
template<class RetType , class PointField , class Type , class BinaryOp >
Foam::tmp< Foam::Field< RetType > > oneToOneImpl (const PointField &global, const UList< Type > &input, const BinaryOp &bop) const
template<class RetType , class PointField , class Type , class BinaryOp >
Foam::tmp< Foam::Field< RetType > > oneToManyImpl (const PointField &global, const Type &input, const BinaryOp &bop) const
Protected Member Functions
virtual vector localToGlobal (const vector &local, bool translate) const
virtual tmp< vectorField > localToGlobal (const vectorField &local, bool translate) const
virtual vector globalToLocal (const vector &global, bool translate) const
virtual tmp< vectorField > globalToLocal (const vectorField &global, bool translate) const
Protected Member Functions inherited from coordinateSystem
template<class PointField >
tmp< tensorField > rotationsImpl (const PointField &global) const
template<class PointField >
tmp< pointField > transformPointImpl (const PointField &localCart) const
template<class PointField >
tmp< pointField > invTransformPointImpl (const PointField &global) const
template<class RetType , class PointField , class Type , class BinaryOp >
tmp< Field< RetType > > oneToOneImpl (const PointField &global, const UList< Type > &input, const BinaryOp &bop) const
template<class RetType , class PointField , class Type , class BinaryOp >
tmp< Field< RetType > > oneToManyImpl (const PointField &global, const Type &input, const BinaryOp &bop) const
void assign (const dictionary &dict, IOobjectOption::readOption readOrigin=IOobjectOption::MUST_READ)
coordinateSystem (std::nullptr_t)
Additional Inherited Members
Static Public Member Functions inherited from coordinateSystem
static autoPtr< coordinateSystem > New (const word &modelType, const objectRegistry &obr, const dictionary &dict, IOobjectOption::readOption readOrigin=IOobjectOption::MUST_READ)
static autoPtr< coordinateSystem > New (const word &modelType, const dictionary &dict, IOobjectOption::readOption readOrigin=IOobjectOption::MUST_READ)
static autoPtr< coordinateSystem > New (const objectRegistry &obr, const dictionary &dict, const word &dictName=word::null, IOobjectOption::readOption readOrigin=IOobjectOption::MUST_READ)
static autoPtr< coordinateSystem > New (const dictionary &dict, const word &dictName=word::null, IOobjectOption::readOption readOrigin=IOobjectOption::MUST_READ)
static autoPtr< coordinateSystem > New (Istream &is, IOobjectOption::readOption readOrigin=IOobjectOption::MUST_READ)
static autoPtr< coordinateSystem > NewIfPresent (const objectRegistry &obr, const dictionary &dict, const word &dictName=coordinateSystem::typeName)
static autoPtr< coordinateSystem > NewIfPresent (const dictionary &dict, const word &dictName=coordinateSystem::typeName)
Static Protected Member Functions inherited from coordinateSystem
template<class RetType , class Type , class BinaryOp >
static tmp< Field< RetType > > manyTimesImpl (const tensor &tt, const UList< Type > &input, const BinaryOp &bop)
Protected Attributes inherited from coordinateSystem
autoPtr< coordinateRotation > spec_
point origin_
tensor rot_
word name_
string note_
Static Protected Attributes inherited from coordinateSystem
static coordinateSystem dummy_
Detailed Description
A coordinate system forward to a global coordinate system that is normally provided by the constant/coordinateSystems file.
Dictionary entries
Property Description Required Default
type Type name: indirect yes
name Name of the referenced system yes
Source files
indirectCS.H
indirectCS.C
Definition at line 71 of file indirectCS.H.
Constructor & Destructor Documentation
indirect() [1/5]
indirect () delete
indirect() [2/5]
indirect (const indirect & csys)
Definition at line 39 of file indirectCS.C.
indirect() [3/5]
indirect (indirect && csys)
Definition at line 46 of file indirectCS.C.
indirect() [4/5]
indirect (const objectRegistry & obr, const word & name)
Definition at line 54 of file indirectCS.C.
indirect() [5/5]
indirect (const objectRegistry & obr, const dictionary & dict, IOobjectOption::readOption readOrigin = IOobjectOption::NO_READ)
Definition at line 65 of file indirectCS.C.
~indirect()
virtual ~indirect () virtual default
Member Function Documentation
localToGlobal() [1/2]
virtual vector localToGlobal (const vector & local, bool translate) const inline protected virtual
Reimplemented from coordinateSystem.
Definition at line 87 of file indirectCS.H.
References local, and coordinateSystem::localToGlobal().
localToGlobal() [2/2]
virtual tmp< vectorField > localToGlobal (const vectorField & local, bool translate) const inline protected virtual
Reimplemented from coordinateSystem.
Definition at line 98 of file indirectCS.H.
References local, and coordinateSystem::localToGlobal().
globalToLocal() [1/2]
virtual vector globalToLocal (const vector & global, bool translate) const inline protected virtual
Reimplemented from coordinateSystem.
Definition at line 109 of file indirectCS.H.
References coordinateSystem::globalToLocal().
globalToLocal() [2/2]
virtual tmp< vectorField > globalToLocal (const vectorField & global, bool translate) const inline protected virtual
Reimplemented from coordinateSystem.
Definition at line 120 of file indirectCS.H.
References coordinateSystem::globalToLocal().
TypeName()
TypeName ("indirect")
clone()
virtual autoPtr< coordinateSystem > clone () const inline virtual
Reimplemented from coordinateSystem.
Definition at line 160 of file indirectCS.H.
valid()
virtual bool valid () const inline virtual
Reimplemented from coordinateSystem.
Definition at line 175 of file indirectCS.H.
References coordinateSystem::valid().
uniform()
virtual bool uniform () const inline virtual
Reimplemented from coordinateSystem.
Definition at line 181 of file indirectCS.H.
References coordinateSystem::uniform().
cs()
virtual const coordinateSystem & cs () const inline virtual
Definition at line 190 of file indirectCS.H.
origin() [1/2]
virtual const point & origin () const inline virtual
Reimplemented from coordinateSystem.
Definition at line 196 of file indirectCS.H.
References coordinateSystem::origin().
rotation() [1/2]
virtual const coordinateRotation & rotation () const inline virtual
Reimplemented from coordinateSystem.
Definition at line 202 of file indirectCS.H.
References coordinateSystem::rotation().
name()
virtual const word & name () const inline virtual
Reimplemented from coordinateSystem.
Definition at line 208 of file indirectCS.H.
References coordinateSystem::name_.
note() [1/2]
virtual const string & note () const inline virtual
Reimplemented from coordinateSystem.
Definition at line 214 of file indirectCS.H.
References coordinateSystem::note().
R() [1/4]
virtual const tensor & R () const inline virtual
Reimplemented from coordinateSystem.
Definition at line 220 of file indirectCS.H.
References coordinateSystem::R().
e1()
virtual const vector e1 () const inline virtual
Reimplemented from coordinateSystem.
Definition at line 226 of file indirectCS.H.
References coordinateSystem::e1().
e2()
virtual const vector e2 () const inline virtual
Reimplemented from coordinateSystem.
Definition at line 232 of file indirectCS.H.
References coordinateSystem::e2().
e3()
virtual const vector e3 () const inline virtual
Reimplemented from coordinateSystem.
Definition at line 238 of file indirectCS.H.
References coordinateSystem::e3().
rename()
void rename (const word & newName) inline virtual
Reimplemented from coordinateSystem.
Definition at line 247 of file indirectCS.H.
note() [2/2]
string & note () inline virtual
Reimplemented from coordinateSystem.
Definition at line 250 of file indirectCS.H.
References coordinateSystem::dummy_, and NotImplemented.
origin() [2/2]
virtual point & origin () inline virtual
Reimplemented from coordinateSystem.
Definition at line 257 of file indirectCS.H.
References coordinateSystem::dummy_, and NotImplemented.
clear()
virtual void clear () inline virtual
Reimplemented from coordinateSystem.
Definition at line 264 of file indirectCS.H.
rotation() [2/2]
virtual void rotation (autoPtr< coordinateRotation > && crot) inline virtual
Reimplemented from coordinateSystem.
Definition at line 267 of file indirectCS.H.
References NotImplemented.
write()
void write (Ostream & os) const virtual
Reimplemented from coordinateSystem.
Definition at line 78 of file indirectCS.C.
References os().
writeEntry() [1/2]
void writeEntry (Ostream & os) const virtual
Reimplemented from coordinateSystem.
Definition at line 84 of file indirectCS.C.
References os().
writeEntry() [2/2]
void writeEntry (const word & keyword, Ostream & os) const virtual
Reimplemented from coordinateSystem.
Definition at line 90 of file indirectCS.C.
References Foam::name(), os(), and Foam::type().
operator=() [1/2]
void operator= (const coordinateSystem & csys) delete
operator=() [2/2]
void operator= (coordinateSystem && csys) delete
R() [2/4]
virtual tensor R (const point & global) const inline virtual
Reimplemented from coordinateSystem.
Definition at line 297 of file indirectCS.H.
References coordinateSystem::R().
R() [3/4]
virtual tmp< tensorField > R (const UList< point > & global) const inline virtual
Reimplemented from coordinateSystem.
Definition at line 303 of file indirectCS.H.
References coordinateSystem::R().
R() [4/4]
virtual tmp< tensorField > R (const pointUIndList & global) const inline virtual
Reimplemented from coordinateSystem.
Definition at line 309 of file indirectCS.H.
References coordinateSystem::R().
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/coordinate/systems/indirectCS.H
src/OpenFOAM/primitives/coordinate/systems/indirectCS.C