OpenFOAM: logPolynomialTransport< Thermo, PolySize > Class Template Reference
logPolynomialTransport< Thermo, PolySize > Class Template Reference
Thermophysical models » Specie » Transport
Transport package using polynomial functions of ln(T) for mu and kappa:
#include <logPolynomialTransport.H>
Public Member Functions
logPolynomialTransport (const word &, const logPolynomialTransport &)
logPolynomialTransport (const dictionary &dict)
autoPtr< logPolynomialTransport > clone () const
scalar mu (const scalar p, const scalar T) const
scalar kappa (const scalar p, const scalar T) const
scalar alphah (const scalar p, const scalar T) const
void write (Ostream &os) const
void operator+= (const logPolynomialTransport &)
void operator*= (const scalar)
Static Public Member Functions
static autoPtr< logPolynomialTransport > New (const dictionary &dict)
static word typeName ()
Friends
logPolynomialTransport operator+ (const logPolynomialTransport &, const logPolynomialTransport &)
logPolynomialTransport operator* (const scalar, const logPolynomialTransport &)
Ostream & operator (Ostream &, const logPolynomialTransport &)
Detailed Description
template<class Thermo, int PolySize = 8>
class Foam::logPolynomialTransport< Thermo, PolySize >
Transport package using polynomial functions of ln(T) for mu and kappa:
Usage
Property Description
muCoeffs<8> Dynamic viscosity polynomial coefficients
kappaCoeffs<8> Thermal conductivity polynomial coefficients
Example of the specification of the transport properties:
    transport
    {
        muCoeffs<8>     ( 1000 -0.05 0.003 0 0 0 0 0 );
        kappaCoeffs<8>  ( 2000 -0.15 0.023 0 0 0 0 0 );
    }
The polynomial expressions are evaluated as so:
Note
Dynamic viscosity polynomial coefficients evaluate to an expression in [Pa.s], but internally uses [Pa.s/kmol].
Thermal conductivity polynomial coefficients evaluate to an expression in [W/m/K], but internally uses [W/m/K/kmol].
Source files
logPolynomialTransport.H
logPolynomialTransportI.H
logPolynomialTransport.C
See also
Foam::Polynomial
Definition at line 132 of file logPolynomialTransport.H.
Constructor & Destructor Documentation
logPolynomialTransport() [1/2]
template<class Thermo , int PolySize> logPolynomialTransport (const word & name, const logPolynomialTransport< Thermo, PolySize > & pt) inline
Definition at line 40 of file logPolynomialTransportI.H.
References Foam::name().
logPolynomialTransport() [2/2]
template<class Thermo , int PolySize> logPolynomialTransport (const dictionary & dict) explicit
Definition at line 27 of file logPolynomialTransport.C.
Member Function Documentation
clone()
template<class Thermo , int PolySize> Foam::autoPtr< Foam::logPolynomialTransport< Thermo, PolySize > > clone () const inline
Definition at line 54 of file logPolynomialTransportI.H.
References Foam::New().
New()
template<class Thermo , int PolySize> Foam::autoPtr< Foam::logPolynomialTransport< Thermo, PolySize > > New (const dictionary & dict) inline static
Definition at line 62 of file logPolynomialTransportI.H.
References dict, and Foam::New().
typeName()
template<class Thermo , int PolySize = 8> static word typeName () inline static
Definition at line 194 of file logPolynomialTransport.H.
mu()
template<class Thermo , int PolySize> Foam::scalar mu (const scalar p, const scalar T) const inline
Definition at line 71 of file logPolynomialTransportI.H.
References Foam::exp(), Foam::log(), and T.
kappa()
template<class Thermo , int PolySize> Foam::scalar kappa (const scalar p, const scalar T) const inline
Definition at line 82 of file logPolynomialTransportI.H.
References Foam::exp(), Foam::log(), and T.
alphah()
template<class Thermo , int PolySize> Foam::scalar alphah (const scalar p, const scalar T) const inline
Definition at line 93 of file logPolynomialTransportI.H.
References Cp, p, and T.
write()
template<class Thermo , int PolySize> void write (Ostream & os) const
Definition at line 41 of file logPolynomialTransport.C.
References Ostream::beginBlock(), Ostream::endBlock(), Foam::name(), os(), and Ostream::writeEntry().
operator+=()
template<class Thermo , int PolySize = 8> void operator+= (const logPolynomialTransport< Thermo, PolySize > &) inline
Definition at line 105 of file logPolynomialTransportI.H.
References Foam::mag(), and Y.
operator*=()
template<class Thermo , int PolySize> void operator*= (const scalar s) inline
Definition at line 126 of file logPolynomialTransportI.H.
References s().
Friends And Related Symbol Documentation
operator+
template<class Thermo , int PolySize = 8> logPolynomialTransport operator+ (const logPolynomialTransport< Thermo, PolySize > & , const logPolynomialTransport< Thermo, PolySize > &) friend
operator*
template<class Thermo , int PolySize = 8> logPolynomialTransport operator* (const scalar , const logPolynomialTransport< Thermo, PolySize > &) friend
operator
template<class Thermo , int PolySize = 8> Ostream & operator (Ostream & , const logPolynomialTransport< Thermo, PolySize > &) friend
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/transport/logPolynomial/logPolynomialTransport.H
src/thermophysicalModels/specie/transport/logPolynomial/logPolynomialTransport.C
src/thermophysicalModels/specie/transport/logPolynomial/logPolynomialTransportI.H