OpenFOAM: renumberMethod Class Reference
renumberMethod Class Reference abstract
Abstract base class for renumbering.
#include <renumberMethod.H>
Public Member Functions
TypeName ("renumberMethod")
declareRunTimeSelectionTable (autoPtr, renumberMethod, dictionary,(const dictionary &renumberDict),(renumberDict))
renumberMethod (const dictionary &dict)
virtual ~renumberMethod ()=default
virtual labelList renumber (const pointField &) const
virtual labelList renumber (const polyMesh &, const pointField &) const
virtual labelList renumber (const labelList &cellCells, const labelList &offsets, const pointField &) const
virtual labelList renumber (const polyMesh &mesh, const labelList &fineToCoarse, const pointField &coarsePoints) const
virtual labelList renumber (const CompactListList< label > &cellCells, const pointField &cellCentres) const
virtual labelList renumber (const labelListList &cellCells, const pointField &cellCentres) const =0
Static Public Member Functions
static autoPtr< renumberMethod > New (const dictionary &renumberDict)
Protected Member Functions
renumberMethod (const renumberMethod &)=delete
void operator= (const renumberMethod &)=delete
Protected Attributes
const dictionary & renumberDict_
Detailed Description
Abstract base class for renumbering.
Source files
renumberMethod.H
renumberMethod.C
Definition at line 47 of file renumberMethod.H.
Constructor & Destructor Documentation
renumberMethod() [1/2]
renumberMethod (const renumberMethod &) protected delete
renumberMethod() [2/2]
renumberMethod (const dictionary & dict) inline explicit
Definition at line 97 of file renumberMethod.H.
~renumberMethod()
virtual ~renumberMethod () virtual default
Member Function Documentation
operator=()
void operator= (const renumberMethod &) protected delete
TypeName()
TypeName ("renumberMethod")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , renumberMethod , dictionary , (const dictionary &renumberDict) , (renumberDict))
New()
Foam::autoPtr< Foam::renumberMethod > New (const dictionary & renumberDict) static
Definition at line 35 of file renumberMethod.C.
References dict, Foam::exit(), Foam::FatalIOError, and FatalIOErrorInLookup.
renumber() [1/6]
virtual labelList renumber (const pointField &) const inline virtual
Reimplemented in CuthillMcKeeRenumber, manualRenumber, randomRenumber, springRenumber, structuredRenumber, SloanRenumber, and zoltanRenumber.
Definition at line 112 of file renumberMethod.H.
References NotImplemented.
renumber() [2/6]
Foam::labelList renumber (const polyMesh & mesh, const pointField & points) const virtual
Reimplemented in randomRenumber, springRenumber, CuthillMcKeeRenumber, manualRenumber, structuredRenumber, SloanRenumber, and zoltanRenumber.
Definition at line 63 of file renumberMethod.C.
References decompositionMethod::calcCellCells(), Foam::identity(), mesh, primitiveMesh::nCells(), points, and Foam::renumber().
renumber() [3/6]
Foam::labelList renumber (const labelList & cellCells, const labelList & offsets, const pointField & cc) const virtual
Reimplemented in CuthillMcKeeRenumber.
Definition at line 93 of file renumberMethod.C.
References NotImplemented.
renumber() [4/6]
Foam::labelList renumber (const polyMesh & mesh, const labelList & fineToCoarse, const pointField & coarsePoints) const virtual
Definition at line 105 of file renumberMethod.C.
References decompositionMethod::calcCellCells(), forAll, mesh, Foam::renumber(), and UPtrList< T >::size().
renumber() [5/6]
Foam::labelList renumber (const CompactListList< label > & cellCells, const pointField & cellCentres) const virtual
Reimplemented in CuthillMcKeeRenumber, manualRenumber, randomRenumber, springRenumber, structuredRenumber, SloanRenumber, and zoltanRenumber.
Definition at line 83 of file renumberMethod.C.
References points, and Foam::renumber().
renumber() [6/6]
virtual labelList renumber (const labelListList & cellCells, const pointField & cellCentres) const pure virtual
Implemented in SloanRenumber, CuthillMcKeeRenumber, manualRenumber, randomRenumber, springRenumber, structuredRenumber, and zoltanRenumber.
Member Data Documentation
renumberDict_
const dictionary& renumberDict_ protected
Definition at line 53 of file renumberMethod.H.
The documentation for this class was generated from the following files:
src/renumber/renumberMethods/renumberMethod/renumberMethod.H
src/renumber/renumberMethods/renumberMethod/renumberMethod.C