OpenFOAM: motionDirectionalDiffusivity Class Reference
motionDirectionalDiffusivity Class Reference
MotionDirectional finite volume mesh motion diffusivity.
#include <motionDirectionalDiffusivity.H>
Public Member Functions
TypeName ("motionDirectional")
motionDirectionalDiffusivity (const fvMesh &mesh, Istream &mdData)
virtual ~motionDirectionalDiffusivity ()
virtual void correct ()
Public Member Functions inherited from uniformDiffusivity
TypeName ("uniform")
uniformDiffusivity (const fvMesh &mesh, Istream &mdData)
virtual ~uniformDiffusivity ()
virtual tmp< surfaceScalarField > operator() () const
Public Member Functions inherited from motionDiffusivity
TypeName ("motionDiffusivity")
declareRunTimeSelectionTable (autoPtr, motionDiffusivity, Istream,(const fvMesh &mesh, Istream &mdData),(mesh, mdData))
motionDiffusivity (const fvMesh &mesh)
virtual ~motionDiffusivity ()
const fvMesh & mesh () const
Additional Inherited Members
Static Public Member Functions inherited from motionDiffusivity
static autoPtr< motionDiffusivity > New (const fvMesh &mesh, Istream &mdData)
Protected Attributes inherited from uniformDiffusivity
surfaceScalarField faceDiffusivity_
Detailed Description
MotionDirectional finite volume mesh motion diffusivity.
Source files
motionDirectionalDiffusivity.H
motionDirectionalDiffusivity.C
Definition at line 46 of file motionDirectionalDiffusivity.H.
Constructor & Destructor Documentation
motionDirectionalDiffusivity()
motionDirectionalDiffusivity (const fvMesh & mesh, Istream & mdData)
Definition at line 44 of file motionDirectionalDiffusivity.C.
~motionDirectionalDiffusivity()
~motionDirectionalDiffusivity () virtual
Definition at line 57 of file motionDirectionalDiffusivity.C.
Member Function Documentation
TypeName()
TypeName ("motionDirectional")
correct()
void correct () virtual
Reimplemented from uniformDiffusivity.
Definition at line 63 of file motionDirectionalDiffusivity.C.
References Foam::cmptMultiply(), correct(), D, Foam::dimVelocity, Foam::fvc::interpolate(), objectRegistry::lookupObject(), Foam::mag(), mesh, n, VectorSpace< Form, Cmpt, Ncmpts >::one, solve(), timeName, and fvPatchFieldBase::zeroGradientType().
The documentation for this class was generated from the following files:
src/fvMotionSolver/motionDiffusivity/motionDirectional/motionDirectionalDiffusivity.H
src/fvMotionSolver/motionDiffusivity/motionDirectional/motionDirectionalDiffusivity.C