OpenFOAM: snappyLayerDriver Class Reference
snappyLayerDriver Class Reference
All to do with adding layers.
#include <snappyLayerDriver.H>
Public Types
enum extrudeMode { NOEXTRUDE , EXTRUDE , EXTRUDEREMOVE }
Public Member Functions
ClassName ("snappyLayerDriver")
snappyLayerDriver (meshRefinement &meshRefiner, const labelList &globalToMasterPatch, const labelList &globalToSlavePatch, const bool dryRun=false)
void mergePatchFacesUndo (const layerParameters &layerParams, const dictionary &motionDict, const meshRefinement::FaceMergeType mergeType)
void addLayers (const layerParameters &layerParams, const label nLayerIter, const dictionary &motionDict, const label nRelaxedIter, const label nAllowableErrors, const labelList &patchIDs, const labelList &internalFaceZones, const List< labelPair > &baffles, const labelList &numLayers, const label nIdealTotAddedCells, const globalIndex &globalFaces, indirectPrimitivePatch &pp, const labelListList &edgeGlobalFaces, const labelList &edgePatchID, const labelList &edgeZoneID, const boolList &edgeFlip, const labelList &inflateFaceID, const scalarField &thickness, const scalarIOField &minThickness, const scalarField &expansionRatio, vectorField &patchDisp, labelList &patchNLayers, List< extrudeMode > &extrudeStatus, polyTopoChange &savedMeshMod, labelList &cellNLayers, scalarField &faceRealThickness)
void addLayers (const layerParameters &layerParams, const dictionary &motionDict, const labelList &patchIDs, const label nAllowableErrors, decompositionMethod &decomposer, fvMeshDistribute &distributor)
void addLayersSinglePass (const layerParameters &layerParams, const dictionary &motionDict, const labelList &patchIDs, const label nAllowableErrors, decompositionMethod &decomposer, fvMeshDistribute &distributor)
void doLayers (const dictionary &shrinkDict, const dictionary &motionDict, const layerParameters &layerParams, const meshRefinement::FaceMergeType mergeType, const bool preBalance, decompositionMethod &decomposer, fvMeshDistribute &distributor)
Detailed Description
All to do with adding layers.
Source files
snappyLayerDriver.H
snappyLayerDriver.C
snappyLayerDriverOneByOne.C
Definition at line 58 of file snappyLayerDriver.H.
Member Enumeration Documentation
extrudeMode
enum extrudeMode
Enumerator
NOEXTRUDE
Do not extrude. No layers added.
EXTRUDE
Extrude.
EXTRUDEREMOVE
Extrude but afterwards remove added faces locally
Definition at line 65 of file snappyLayerDriver.H.
Constructor & Destructor Documentation
snappyLayerDriver()
snappyLayerDriver (meshRefinement & meshRefiner, const labelList & globalToMasterPatch, const labelList & globalToSlavePatch, const bool dryRun = false)
Definition at line 4608 of file snappyLayerDriver.C.
Member Function Documentation
ClassName()
ClassName ("snappyLayerDriver")
mergePatchFacesUndo()
void mergePatchFacesUndo (const layerParameters & layerParams, const dictionary & motionDict, const meshRefinement::FaceMergeType mergeType)
Definition at line 4625 of file snappyLayerDriver.C.
References Foam::cos(), Foam::degToRad(), Foam::endl(), localPointRegion::findDuplicateFacePairs(), forAll, Foam::Info, mesh, primitiveMesh::nFaces(), and Foam::nl.
addLayers() [1/2]
void addLayers (const layerParameters & layerParams, const label nLayerIter, const dictionary & motionDict, const label nRelaxedIter, const label nAllowableErrors, const labelList & patchIDs, const labelList & internalFaceZones, const List< labelPair > & baffles, const labelList & numLayers, const label nIdealTotAddedCells, const globalIndex & globalFaces, indirectPrimitivePatch & pp, const labelListList & edgeGlobalFaces, const labelList & edgePatchID, const labelList & edgeZoneID, const boolList & edgeFlip, const labelList & inflateFaceID, const scalarField & thickness, const scalarIOField & minThickness, const scalarField & expansionRatio, vectorField & patchDisp, labelList & patchNLayers, List< extrudeMode > & extrudeStatus, polyTopoChange & savedMeshMod, labelList & cellNLayers, scalarField & faceRealThickness)
Definition at line 3912 of file snappyLayerDriver.C.
References addProfiling, fvMesh::clearOut(), Foam::endl(), mapPolyMesh::faceMap(), layerParameters::finalLayerThicknessRatio(), forAll, mapPolyMesh::hasMotionPoints(), Foam::identity(), Foam::Info, IOobject::instance(), meshRefinement::LAYERINFO, PrimitivePatch< FaceList, PointField >::localPoints(), Foam::mag(), polyTopoChange::makeMesh(), mesh, meshRefinement::MESH, PrimitivePatch< FaceList, PointField >::movePoints(), fvMesh::movePoints(), polyMesh::moving(), fvMesh::name(), IOobject::name(), MeshObject< polyMesh, UpdateableMeshObject, pointMesh >::New(), primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), Foam::nl, PrimitivePatch< FaceList, PointField >::nPoints(), p, patchIDs(), polyMesh::points(), pp(), mapPolyMesh::preMotionPoints(), IOobjectOption::READ_IF_PRESENT, Foam::returnReduce(), motionSmootherAlgo::setDisplacement(), polyMesh::setInstance(), PtrList< T >::setSize(), polyTopoChange::shrink(), UPtrList< T >::size(), meshRefinement::subsetBaffles(), fvMesh::time(), fvMesh::updateMesh(), fvMesh::write(), Ostream::write(), meshRefinement::writeLevel(), meshRefinement::WRITEMESH, IOobjectOption::writeOpt(), and Foam::Zero.
Referenced by snappyLayerDriver::addLayersSinglePass().
addLayers() [2/2]
void addLayers (const layerParameters & layerParams, const dictionary & motionDict, const labelList & patchIDs, const label nAllowableErrors, decompositionMethod & decomposer, fvMeshDistribute & distributor)
Definition at line 4678 of file snappyLayerDriver.C.
References surfaceZonesInfo::BAFFLE, polyMesh::boundaryMesh(), mapPolyMesh::cellMap(), polyTopoChange::changeMesh(), fvMesh::clearOut(), Foam::endl(), mapPolyMesh::faceMap(), polyMesh::faceZones(), UPtrList< T >::first(), forAll, addPatchCellLayer::globalEdgeFaces(), Foam::gSum(), mapPolyMesh::hasMotionPoints(), Foam::identity(), Foam::Info, surfaceZonesInfo::INTERNAL, meshRefinement::LAYERINFO, layerParameters::layerThickness(), meshRefinement::makePatch(), Foam::max(), mesh, meshRefinement::MESH, PrimitivePatch< FaceList, PointField >::meshPointMap(), PrimitivePatch< FaceList, PointField >::meshPoints(), Foam::min(), fvMesh::movePoints(), polyMesh::moving(), primitiveMesh::nCells(), primitiveMesh::nFaces(), Foam::nl, IOobjectOption::NO_READ, mapPolyMesh::nOldCells(), mapPolyMesh::nOldFaces(), nPoints, UPstream::parRun(), patchIDs(), pbm, pp(), mapPolyMesh::preMotionPoints(), polyMesh::setInstance(), PtrList< T >::setSize(), UPtrList< T >::size(), fvMesh::time(), VectorSpace< Form, Cmpt, Ncmpts >::uniform(), meshRefinement::updateList(), fvMesh::updateMesh(), Ostream::write(), meshRefinement::writeLevel(), meshRefinement::WRITEMESH, and Foam::Zero.
addLayersSinglePass()
void addLayersSinglePass (const layerParameters & layerParams, const dictionary & motionDict, const labelList & patchIDs, const label nAllowableErrors, decompositionMethod & decomposer, fvMeshDistribute & distributor)
Definition at line 41 of file snappyLayerDriverSinglePass.C.
References snappyLayerDriver::addLayers(), surfaceZonesInfo::BAFFLE, meshRefinement::balance(), polyTopoChange::changeMesh(), meshRefinement::createZoneBaffles(), meshRefinement::dupNonManifoldBoundaryPoints(), Foam::endl(), snappyLayerDriver::EXTRUDE, mapPolyMesh::faceMap(), UPtrList< T >::first(), forAll, meshRefinement::getFaceZoneInfo(), meshRefinement::getZones(), addPatchCellLayer::globalEdgeFaces(), mapPolyMesh::hasMotionPoints(), Foam::identity(), Foam::Info, surfaceZonesInfo::INTERNAL, meshRefinement::LAYERINFO, meshRefinement::makePatch(), mesh, meshRefinement::MESH, meshRefinement::mesh(), meshRefinement::meshCutter(), Foam::nl, IOobjectOption::NO_READ, nPoints, UPstream::parRun(), patchIDs(), pbm, pp(), mapPolyMesh::preMotionPoints(), meshRefinement::timeName(), meshRefinement::updateList(), meshRefinement::updateMesh(), meshRefinement::write(), meshRefinement::writeLevel(), meshRefinement::WRITEMESH, and Foam::Zero.
doLayers()
void doLayers (const dictionary & shrinkDict, const dictionary & motionDict, const layerParameters & layerParams, const meshRefinement::FaceMergeType mergeType, const bool preBalance, decompositionMethod & decomposer, fvMeshDistribute & distributor)
Definition at line 5354 of file snappyLayerDriver.C.
References addProfiling, PtrList< T >::append(), polyMesh::boundaryMesh(), cellIDs, motionSmootherAlgo::checkMesh(), Foam::endl(), polyMesh::faceZones(), forAll, meshRefinement::GEOMETRIC, syncTools::getInternalOrCoupledFaces(), meshRefinement::IGNOREPATCH, Foam::Info, mesh, Foam::name(), primitiveMesh::nCells(), primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), Foam::nl, UPstream::parRun(), patchIDs(), pp(), UPstream::reduceOr(), Foam::returnReduce(), Foam::returnReduceOr(), PtrList< T >::set(), UPtrList< T >::size(), UList< T >::size(), UPtrList< T >::test(), and WarningInFunction.
The documentation for this class was generated from the following files:
src/mesh/snappyHexMesh/snappyHexMeshDriver/snappyLayerDriver.H
src/mesh/snappyHexMesh/snappyHexMeshDriver/snappyLayerDriver.C
src/mesh/snappyHexMesh/snappyHexMeshDriver/snappyLayerDriverSinglePass.C
src/mesh/snappyHexMesh/snappyHexMeshDriver/snappyLayerDriverTemplates.C