OpenFOAM: standardRadiation Class Reference
standardRadiation Class Reference
Standard radiation model.
#include <standardRadiation.H>
Public Member Functions
TypeName ("standardRadiation")
standardRadiation (surfaceFilmRegionModel &film, const dictionary &dict)
virtual ~standardRadiation ()=default
virtual void correct ()
virtual tmp< volScalarField > Shs ()
Public Member Functions inherited from filmRadiationModel
TypeName ("radiationModel")
declareRunTimeSelectionTable (autoPtr, filmRadiationModel, dictionary,(surfaceFilmRegionModel &film, const dictionary &dict),(film, dict))
filmRadiationModel (surfaceFilmRegionModel &film)
filmRadiationModel (const word &modelType, surfaceFilmRegionModel &film, const dictionary &dict)
virtual ~filmRadiationModel ()
Public Member Functions inherited from filmSubModelBase
filmSubModelBase (surfaceFilmRegionModel &film)
filmSubModelBase (surfaceFilmRegionModel &film, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
filmSubModelBase (const word &modelName, surfaceFilmRegionModel &film, const dictionary &dict, const word &baseName, const word &modelType)
virtual ~filmSubModelBase ()
virtual bool writeTime () const
const surfaceFilmRegionModel & film () const
surfaceFilmRegionModel & film ()
template<class FilmType >
const FilmType & filmType () const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
subModelBase (const subModelBase &smb)
virtual ~subModelBase ()=default
const word & modelName () const
const dictionary & dict () const
const word & baseName () const
const word & modelType () const
const dictionary & coeffDict () const
const dictionary & properties () const
virtual bool defaultCoeffs (const bool printMsg) const
virtual bool active () const
virtual void cacheFields (const bool store)
virtual fileName localPath () const
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
bool getModelDict (const word &entryName, dictionary &dict) const
template<class Type >
bool getModelProperty (const word &entryName, Type &value) const
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
virtual void write (Ostream &os) const
Additional Inherited Members
Static Public Member Functions inherited from filmRadiationModel
static autoPtr< filmRadiationModel > New (surfaceFilmRegionModel &film, const dictionary &dict)
Public Attributes inherited from subModelBase
bool log
Protected Member Functions inherited from subModelBase
bool inLine () const
Protected Attributes inherited from filmSubModelBase
surfaceFilmRegionModel & filmModel_
Protected Attributes inherited from subModelBase
const word modelName_
dictionary & properties_
const dictionary dict_
const word baseName_
const word modelType_
const dictionary coeffDict_
Detailed Description
Standard radiation model.
Source files
standardRadiation.H
standardRadiation.C
Definition at line 51 of file standardRadiation.H.
Constructor & Destructor Documentation
standardRadiation()
standardRadiation (surfaceFilmRegionModel & film, const dictionary & dict)
Definition at line 48 of file standardRadiation.C.
~standardRadiation()
virtual ~standardRadiation () virtual default
Member Function Documentation
TypeName()
TypeName ("standardRadiation")
correct()
void correct () virtual
Implements filmRadiationModel.
Definition at line 90 of file standardRadiation.C.
References GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions().
Shs()
tmp< volScalarField > Shs () virtual
Implements filmRadiationModel.
Definition at line 97 of file standardRadiation.C.
References alpha, surfaceFilmRegionModel::alpha(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), delta, surfaceFilmRegionModel::delta(), Foam::dimMass, Foam::dimTime, Foam::exp(), filmSubModelBase::film(), filmSubModelBase::filmModel_, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, Foam::pow3(), GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef(), standardRadiation::Shs(), timeName, and Foam::Zero.
Referenced by standardRadiation::Shs().
The documentation for this class was generated from the following files:
src/regionModels/surfaceFilmModels/submodels/thermo/filmRadiationModel/standardRadiation/standardRadiation.H
src/regionModels/surfaceFilmModels/submodels/thermo/filmRadiationModel/standardRadiation/standardRadiation.C