OpenFOAM: triangle< Point, PointRef > Class Template Reference
triangle< Point, PointRef > Class Template Reference
A triangle primitive used to calculate face normals and swept volumes. Uses referred points.
#include <triangle.H>
Classes
class dummyOp
class storeOp
class sumAreaOp
Public Types
enum proxType { NONE = 0 , POINT , EDGE }
typedef Point point_type
typedef FixedList< triPoints, 27 > triIntersectionList
Public Member Functions
triangle (const Point &p0, const Point &p1, const Point &p2)
triangle (const FixedList< Point, 3 > &pts)
triangle (const UList< Point > &points, const FixedList< label, 3 > &indices)
triangle (Istream &is)
const Point & a () const noexcept
const Point & b () const noexcept
const Point & c () const noexcept
Point centre () const
vector areaNormal () const
vector unitNormal () const
FOAM_DEPRECATED_FOR (2018-12, "areaNormal() or unitNormal()") vector normal() const
scalar mag () const
Pair< Point > box () const
Point vecA () const
Point vecB () const
Point vecC () const
Point circumCentre () const
scalar circumRadius () const
scalar quality () const
scalar sweptVol (const triangle &t) const
tensor inertia (PointRef refPt=Zero, scalar density=1.0) const
Point randomPoint (Random &rndGen) const
Point barycentricToPoint (const barycentric2D &bary) const
barycentric2D pointToBarycentric (const point &pt) const
scalar pointToBarycentric (const point &pt, barycentric2D &bary) const
bool intersects (const point &origin, const vector &normal) const
bool intersects (const point &origin, const vector::components axis) const
pointHit ray (const point &p, const vector &q, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction dir=intersection::VECTOR) const
pointHit intersection (const point &p, const vector &q, const intersection::algorithm alg, const scalar tol=0.0) const
pointHit nearestPointClassify (const point &p, label &nearType, label &nearLabel) const
pointHit nearestPoint (const point &p) const
bool classify (const point &p, label &nearType, label &nearLabel) const
pointHit nearestPoint (const linePointRef &edge, pointHit &edgePoint) const
int sign (const point &p, const scalar tol=SMALL) const
template<class AboveOp , class BelowOp >
void sliceWithPlane (const plane &pln, AboveOp &aboveOp, BelowOp &belowOp) const
template<class InsideOp , class OutsideOp >
void triangleOverlap (const vector &n, const triangle< Point, PointRef > &tri, InsideOp &insideOp, OutsideOp &outsideOp) const
Static Public Member Functions
static Point centre (const Point &p0, const Point &p1, const Point &p2)
static vector areaNormal (const Point &p0, const Point &p1, const Point &p2)
static vector unitNormal (const Point &p0, const Point &p1, const Point &p2)
static Pair< Point > box (const Point &p0, const Point &p1, const Point &p2)
Friends
Istream & operator>> (Istream &, triangle &)
Ostream & operator (Ostream &, const triangle &)
Detailed Description
template<class Point, class PointRef>
class Foam::triangle< Point, PointRef >
A triangle primitive used to calculate face normals and swept volumes. Uses referred points.
Source files
triangle.H
triangleI.H
triangle.C
Definition at line 171 of file triangle.H.
Member Typedef Documentation
point_type
template<class Point , class PointRef > typedef Point point_type
Definition at line 178 of file triangle.H.
triIntersectionList
template<class Point , class PointRef > typedef FixedList<triPoints, 27> triIntersectionList
Definition at line 182 of file triangle.H.
Member Enumeration Documentation
proxType
template<class Point , class PointRef > enum proxType
Enumerator
NONE
Unknown proximity.
POINT
Close to point.
EDGE
Close to edge.
Definition at line 185 of file triangle.H.
Constructor & Destructor Documentation
triangle() [1/4]
template<class Point , class PointRef > triangle (const Point & p0, const Point & p1, const Point & p2) inline
Definition at line 66 of file triangleI.H.
triangle() [2/4]
template<class Point , class PointRef > triangle (const FixedList< Point, 3 > & pts) inline
Definition at line 80 of file triangleI.H.
triangle() [3/4]
template<class Point , class PointRef > triangle (const UList< Point > & points, const FixedList< label, 3 > & indices) inline
Definition at line 92 of file triangleI.H.
triangle() [4/4]
template<class Point , class PointRef > triangle (Istream & is) inline explicit
Definition at line 105 of file triangleI.H.
Member Function Documentation
a()
template<class Point , class PointRef > const Point & a () const inline noexcept
Definition at line 292 of file triangle.H.
Referenced by triSurfaceTools::calcInterpolationWeights(), triangleFuncs::intersectBb(), and boundBox::intersects().
b()
template<class Point , class PointRef > const Point & b () const inline noexcept
Definition at line 295 of file triangle.H.
Referenced by triSurfaceTools::calcInterpolationWeights(), triangleFuncs::intersectBb(), and boundBox::intersects().
c()
template<class Point , class PointRef > const Point & c () const inline noexcept
Definition at line 298 of file triangle.H.
Referenced by triSurfaceTools::calcInterpolationWeights(), triangleFuncs::intersectBb(), and boundBox::intersects().
centre() [1/2]
template<class Point , class PointRef > Point centre (const Point & p0, const Point & p1, const Point & p2) inline static
Definition at line 114 of file triangleI.H.
References p0.
Referenced by momentOfInertia::massPropertiesShell(), polyMesh::pointInCell(), and wallBoundedStreamLine::pushIn().
areaNormal() [1/2]
template<class Point , class PointRef > Foam::vector areaNormal (const Point & p0, const Point & p1, const Point & p2) inline static
Definition at line 139 of file triangleI.H.
References p0.
Referenced by boundBox::intersects(), and polyMesh::pointInCell().
unitNormal() [1/2]
template<class Point , class PointRef > Foam::vector unitNormal (const Point & p0, const Point & p1, const Point & p2) inline static
Definition at line 164 of file triangleI.H.
References Foam::mag(), n, p0, s(), and Foam::Zero.
box() [1/2]
template<class Point , class PointRef > Foam::Pair< Point > box (const Point & p0, const Point & p1, const Point & p2) inline static
Definition at line 191 of file triangleI.H.
References Foam::max(), Foam::min(), and p0.
centre() [2/2]
template<class Point , class PointRef > Point centre () const inline
Definition at line 126 of file triangleI.H.
Referenced by cutFace::calcSubFaceCentreAndArea(), triPoints::centre(), face::centre(), triFace::centre(), highAspectRatioFvGeometryScheme::makeAverageCentres(), stabilisedFvGeometryScheme::makeFaceCentresAndAreas(), primitiveMeshTools::makeFaceCentresAndAreas(), and primitiveMeshTools::updateFaceCentresAndAreas().
areaNormal() [2/2]
template<class Point , class PointRef > Foam::vector areaNormal () const inline
Definition at line 151 of file triangleI.H.
Referenced by triPoints::areaNormal(), face::areaNormal(), triFace::areaNormal(), Foam::areaNormalFaceTriangle(), cutFace::calcSubFaceCentreAndArea(), polyMeshGeometry::checkFaceTwist(), primitiveMeshGeometry::checkFaceTwist(), polyMeshGeometry::checkTriangleTwist(), triangle< Point, PointRef >::FOAM_DEPRECATED_FOR(), stabilisedFvGeometryScheme::makeFaceCentresAndAreas(), primitiveMeshTools::makeFaceCentresAndAreas(), areaOp::operator()(), tetrahedron< Point, PointRef >::Sa(), tetrahedron< Point, PointRef >::Sb(), tetrahedron< Point, PointRef >::Sc(), tetrahedron< Point, PointRef >::Sd(), and primitiveMeshTools::updateFaceCentresAndAreas().
unitNormal() [2/2]
template<class Point , class PointRef > Foam::vector unitNormal () const inline
Definition at line 178 of file triangleI.H.
References triangle< Point, PointRef >::unitNormal().
Referenced by particle< Type >::patchData(), triPoints::unitNormal(), triangle< Point, PointRef >::unitNormal(), triFace::unitNormal(), and STLtriangle::write().
FOAM_DEPRECATED_FOR()
template<class Point , class PointRef > FOAM_DEPRECATED_FOR (2018- 12, "areaNormal() or unitNormal()") const inline
Definition at line 351 of file triangle.H.
References triangle< Point, PointRef >::areaNormal().
mag()
template<class Point , class PointRef > Foam::scalar mag () const inline
Definition at line 280 of file triangleI.H.
Referenced by momentOfInertia::massPropertiesShell().
box() [2/2]
template<class Point , class PointRef > Foam::Pair< Point > box () const inline
Definition at line 207 of file triangleI.H.
References triangle< Point, PointRef >::box().
Referenced by triPoints::box(), triangle< Point, PointRef >::box(), and triFace::box().
vecA()
template<class Point , class PointRef > Point vecA () const inline
Definition at line 220 of file triangleI.H.
Referenced by boundBox::intersects().
vecB()
template<class Point , class PointRef > Point vecB () const inline
Definition at line 226 of file triangleI.H.
Referenced by boundBox::intersects().
vecC()
template<class Point , class PointRef > Point vecC () const inline
Definition at line 232 of file triangleI.H.
Referenced by boundBox::intersects().
circumCentre()
template<class Point , class PointRef > Point circumCentre () const inline
Definition at line 287 of file triangleI.H.
References Foam::mag().
Referenced by Foam::edgeMeshTools::featureProximity().
circumRadius()
template<class Point , class PointRef > Foam::scalar circumRadius () const inline
Definition at line 314 of file triangleI.H.
References Foam::clamp(), Foam::mag(), and Foam::sqrt().
Referenced by Foam::edgeMeshTools::featureProximity().
quality()
template<class Point , class PointRef > Foam::scalar quality () const inline
Definition at line 335 of file triangleI.H.
References Foam::mag(), Foam::sqr(), and Foam::sqrt().
sweptVol()
template<class Point , class PointRef > Foam::scalar sweptVol (const triangle< Point, PointRef > & t) const inline
Definition at line 350 of file triangleI.H.
inertia()
template<class Point , class PointRef > Foam::tensor inertia (PointRef refPt = Zero, scalar density = 1.0) const inline
Definition at line 369 of file triangleI.H.
References Foam::I, Foam::mag(), VectorSpace< Form, Cmpt, Mrows *Ncols >::one, and Tensor< Cmpt >::T().
randomPoint()
template<class Point , class PointRef > Point randomPoint (Random & rndGen) const inline
Definition at line 406 of file triangleI.H.
References Foam::barycentric2D01(), and rndGen.
Referenced by patchInjectionBase::setPositionAndCell().
barycentricToPoint()
template<class Point , class PointRef > Point barycentricToPoint (const barycentric2D & bary) const inline
Definition at line 413 of file triangleI.H.
pointToBarycentric() [1/2]
template<class Point , class PointRef > Foam::barycentric2D pointToBarycentric (const point & pt) const inline
Definition at line 423 of file triangleI.H.
pointToBarycentric() [2/2]
template<class Point , class PointRef > Foam::scalar pointToBarycentric (const point & pt, barycentric2D & bary) const inline
Definition at line 435 of file triangleI.H.
References Foam::mag().
intersects() [1/2]
template<class Point , class PointRef > bool intersects (const point & origin, const vector & normal) const inline
Definition at line 474 of file triangleI.H.
intersects() [2/2]
template<class Point , class PointRef > bool intersects (const point & origin, const vector::components axis) const inline
Parameters
origin Origin of the plane
axis Normal of the plane (vector::X, vector::Y, vector::Z)
Definition at line 494 of file triangleI.H.
ray()
template<class Point , class PointRef > Foam::pointHit ray (const point & p, const vector & q, const intersection::algorithm alg = intersection::FULL_RAY, const intersection::direction dir = intersection::VECTOR) const inline
Definition at line 514 of file triangleI.H.
References intersection::CONTACT_SPHERE, intersection::FULL_RAY, intersection::HALF_RAY, Foam::mag(), Foam::min(), n, p, intersection::planarTol(), intersection::VECTOR, and intersection::VISIBLE.
intersection()
template<class Point , class PointRef > Foam::pointHit intersection (const point & p, const vector & q, const intersection::algorithm alg, const scalar tol = 0.0) const inline
Definition at line 629 of file triangleI.H.
References Foam::det(), intersection::FULL_RAY, intersection::HALF_RAY, intersection::VISIBLE, and Foam::Zero.
Referenced by mappedPatchBase::facePoint(), and triangleFuncs::intersectBb().
nearestPointClassify()
template<class Point , class PointRef > Foam::pointHit nearestPointClassify (const point & p, label & nearType, label & nearLabel) const
Definition at line 711 of file triangleI.H.
References cp, Foam::mag(), and p.
Referenced by triSurfaceTools::calcInterpolationWeights(), and face::nearestPointClassify().
nearestPoint() [1/2]
template<class Point , class PointRef > Foam::pointHit nearestPoint (const point & p) const inline
Definition at line 860 of file triangleI.H.
References p.
Referenced by wallBoundedStreamLine::findNearestTet().
classify()
template<class Point , class PointRef > bool classify (const point & p, label & nearType, label & nearLabel) const inline
Definition at line 874 of file triangleI.H.
References p.
nearestPoint() [2/2]
template<class Point , class PointRef > Foam::pointHit nearestPoint (const linePointRef & edge, pointHit & edgePoint) const inline
Definition at line 886 of file triangleI.H.
References UPtrList< T >::end(), intersection::FULL_RAY, Foam::ln(), and Foam::mag().
sign()
template<class Point , class PointRef > int sign (const point & p, const scalar tol = SMALL) const inline
Definition at line 1010 of file triangleI.H.
References p.
sliceWithPlane()
template<class Point , class PointRef > template<class AboveOp , class BelowOp > void sliceWithPlane (const plane & pln, AboveOp & aboveOp, BelowOp & belowOp) const inline
Definition at line 106 of file triangle.C.
triangleOverlap()
template<class Point , class PointRef > template<class InsideOp , class OutsideOp > void triangleOverlap (const vector & n, const triangle< Point, PointRef > & tri, InsideOp & insideOp, OutsideOp & outsideOp) const inline
Definition at line 119 of file triangle.C.
References Foam::mag(), n, and s().
Friends And Related Symbol Documentation
operator>>
template<class Point , class PointRef > Istream & operator>> (Istream & , triangle< Point, PointRef > &) friend
operator
template<class Point , class PointRef > Ostream & operator (Ostream & , const triangle< Point, PointRef > &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/primitiveShapes/triangle/triangle.H
src/OpenFOAM/meshes/primitiveShapes/triangle/triangle.C
src/OpenFOAM/meshes/primitiveShapes/triangle/triangleI.H