OpenFOAM: directionalMeshWave Class Reference
directionalMeshWave Class Reference
Variant of meshWave distance-to-patch method.
#include <directionalMeshWavePatchDistMethod.H>
Public Member Functions
TypeName ("directionalMeshWave")
directionalMeshWave (const dictionary &dict, const fvMesh &mesh, const labelHashSet &patchIDs)
virtual bool correct (volScalarField &y)
virtual bool correct (volScalarField &y, volVectorField &n)
Public Member Functions inherited from meshWave
TypeName ("meshWave")
meshWave (const dictionary &dict, const fvMesh &mesh, const labelHashSet &patchIDs)
meshWave (const fvMesh &mesh, const labelHashSet &patchIDs, const bool correctWalls=true)
Public Member Functions inherited from patchDistMethod
TypeName ("patchDistMethod")
declareRunTimeSelectionTable (autoPtr, patchDistMethod, dictionary,(const dictionary &dict, const fvMesh &mesh, const labelHashSet &patchIDs),(dict, mesh, patchIDs))
patchDistMethod (const fvMesh &mesh, const labelHashSet &patchIDs)
virtual ~patchDistMethod ()
const labelHashSet & patchIDs () const
virtual bool movePoints ()
virtual void updateMesh (const mapPolyMesh &)
template<class Type >
Foam::wordList patchTypes (const fvMesh &mesh, const labelHashSet &patchIDs)
Additional Inherited Members
Static Public Member Functions inherited from patchDistMethod
static autoPtr< patchDistMethod > New (const dictionary &dict, const fvMesh &mesh, const labelHashSet &patchIDs, const word &defaultPatchDistMethod=word::null)
template<class Type >
static wordList patchTypes (const fvMesh &mesh, const labelHashSet &patchIDs)
Protected Member Functions inherited from patchDistMethod
patchDistMethod (const patchDistMethod &)=delete
void operator= (const patchDistMethod &)=delete
Protected Attributes inherited from meshWave
const bool correctWalls_
label nUnset_
Protected Attributes inherited from patchDistMethod
const fvMesh & mesh_
const labelHashSet patchIDs_
Detailed Description
Variant of meshWave distance-to-patch method.
Ignores the component in the specified direction. Can be used e.g. to calculate the distance in the z-direction only.
Usage
Example of specification in fvSchemes.wallDist:
    wallDist
    {
        // Mandatory entries (unmodifiable)
        method      directionalMeshWave;
        n           (0 0 1);
        // Optional (inherited) entries (unmodifiable)
        ...
    }
where the entries mean:
Property Description Type Req'd Dflt
method Method name: directionalMeshWave word yes -
n The direction component to ignore vector yes -
The inherited entries are elaborated in:
meshWavePatchDistMethod.H
See also
Foam::wallDist Foam::patchDistMethod::meshWave Foam::patchDistMethod::Poisson Foam::directionalWallPoint
Source files
directionalMeshWavePatchDistMethod.H
directionalMeshWavePatchDistMethod.C
Definition at line 99 of file directionalMeshWavePatchDistMethod.H.
Constructor & Destructor Documentation
directionalMeshWave()
directionalMeshWave (const dictionary & dict, const fvMesh & mesh, const labelHashSet & patchIDs)
Definition at line 47 of file directionalMeshWavePatchDistMethod.C.
Member Function Documentation
TypeName()
TypeName ("directionalMeshWave")
correct() [1/2]
bool correct (volScalarField & y) virtual
Reimplemented from meshWave.
Definition at line 61 of file directionalMeshWavePatchDistMethod.C.
References correct(), Foam::dimLength, Foam::dimless, n, IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, patches, y, and Foam::Zero.
correct() [2/2]
bool correct (volScalarField & y, volVectorField & n) virtual
Reimplemented from meshWave.
Definition at line 94 of file directionalMeshWavePatchDistMethod.C.
References Foam::dimLength, forAll, n, PtrList< T >::set(), PtrList< T >::transfer(), and y.
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/wallDist/patchDistMethods/directionalMeshWave/directionalMeshWavePatchDistMethod.H
src/finiteVolume/fvMesh/wallDist/patchDistMethods/directionalMeshWave/directionalMeshWavePatchDistMethod.C