OpenFOAM: PrecisionAdaptor< Type, InputType, Container > Class Template Reference
PrecisionAdaptor< Type, InputType, Container > Class Template Reference
Conversion adaptor for Field/List that either wrap the input as a reference, or creates a temporary pointer and copies the values on construction/destruction.
#include <PrecisionAdaptor.H>
Public Types
typedef Container< Type > FieldType
Public Types inherited from refPtr< T >
typedef T element_type
typedef T * pointer
typedef Foam::refCount::zero refCount
Public Member Functions
PrecisionAdaptor ()=default
PrecisionAdaptor (Container< InputType > &input, const bool doCopy=true)
~PrecisionAdaptor ()
bool active () const noexcept
void commit ()
void set (Container< InputType > &input, const bool doCopy=true)
Public Member Functions inherited from refPtr< T >
constexpr refPtr () noexcept
constexpr refPtr (std::nullptr_t) noexcept
constexpr refPtr (T *p) noexcept
constexpr refPtr (const T &obj) noexcept
refPtr (refPtr< T > &&rhs) noexcept
refPtr (const refPtr< T > &rhs)
refPtr (const refPtr< T > &rhs, bool reuse)
refPtr (std::unique_ptr< T > &&rhs) noexcept
refPtr (const autoPtr< T > &)=delete
refPtr (autoPtr< T > &&rhs) noexcept
refPtr (const tmp< T > &rhs, bool reuse)
refPtr (const tmp< T > &rhs)
refPtr (tmp< T > &&rhs)
~refPtr () noexcept
bool good () const noexcept
bool is_const () const noexcept
bool is_pointer () const noexcept
bool is_reference () const noexcept
bool movable () const noexcept
T * get () noexcept
const T * get () const noexcept
const T & cref () const
T & ref () const
T & constCast () const
refPtr< T > shallowClone () const noexcept
T * release () noexcept
T * ptr () const
void clear () const noexcept
void reset (T *p=nullptr) noexcept
void reset (refPtr< T > &&other) noexcept
void reset (const autoPtr< T > &)=delete
void reset (autoPtr< T > &&other) noexcept
void reset (std::unique_ptr< T > &&other)
void reset (tmp< T > &rhs, bool reuse)
void cref (const refPtr< T > &other) noexcept
void cref (const T &obj) noexcept
void cref (const T *p) noexcept
void cref (const autoPtr< T > &)=delete
void cref (const tmp< T > &)=delete
void ref (T &obj) noexcept
void ref (T *p) noexcept
void ref (const autoPtr< T > &)=delete
void ref (const tmp< T > &)=delete
void swap (refPtr< T > &other) noexcept
const T & operator* () const
T & operator* ()
const T * operator-> () const
T * operator-> ()
const T & operator() () const
operator bool () const noexcept
operator const T & () const
void operator= (const refPtr< T > &other)
void operator= (refPtr< T > &&other) noexcept
void operator= (T *p)=delete
void operator= (std::nullptr_t) noexcept
void operator= (const autoPtr< T > &)=delete
void operator= (autoPtr< T > &&other) noexcept
void operator= (std::unique_ptr< T > &&other)
void operator= (const tmp< T > &)=delete
void operator= (tmp< T > &&other)
operator tmp< T > ()
bool valid () const noexcept
bool empty () const noexcept
Additional Inherited Members
Static Public Member Functions inherited from refPtr< T >
template<class... Args>
static refPtr< T > New (Args &&... args)
template<class U , class... Args>
static refPtr< T > NewFrom (Args &&... args)
static word typeName ()
Detailed Description
template<class Type, class InputType, template< class > class Container = Field>
class Foam::PrecisionAdaptor< Type, InputType, Container >
Conversion adaptor for Field/List that either wrap the input as a reference, or creates a temporary pointer and copies the values on construction/destruction.
This provides, for example, automatic conversion between types for linear solvers able to run mixed precision.
Definition at line 184 of file PrecisionAdaptor.H.
Member Typedef Documentation
FieldType
template<class Type , class InputType , template< class > class Container = Field> typedef Container<Type> FieldType
Definition at line 219 of file PrecisionAdaptor.H.
Constructor & Destructor Documentation
PrecisionAdaptor() [1/2]
template<class Type , class InputType , template< class > class Container = Field> PrecisionAdaptor () default
PrecisionAdaptor() [2/2]
template<class Type , class InputType , template< class > class Container = Field> PrecisionAdaptor (Container< InputType > & input, const bool doCopy = true) inline explicit
Definition at line 229 of file PrecisionAdaptor.H.
References Foam::input().
~PrecisionAdaptor()
template<class Type , class InputType , template< class > class Container = Field> ~PrecisionAdaptor () inline
Definition at line 240 of file PrecisionAdaptor.H.
References refPtr< T >::clear(), and PrecisionAdaptor< Type, InputType, Container >::commit().
Member Function Documentation
active()
template<class Type , class InputType , template< class > class Container = Field> bool active () const inline noexcept
Definition at line 250 of file PrecisionAdaptor.H.
References refPtr< T >::good(), and refPtr< T >::is_pointer().
Referenced by PrecisionAdaptor< Type, InputType, Container >::commit().
commit()
template<class Type , class InputType , template< class > class Container = Field> void commit () inline
Definition at line 257 of file PrecisionAdaptor.H.
References PrecisionAdaptor< Type, InputType, Container >::active(), UPtrList< T >::begin(), UPtrList< T >::cbegin(), UPtrList< T >::cend(), refPtr< T >::cref(), Foam::input(), PtrList< T >::resize(), and UPtrList< T >::size().
Referenced by PrecisionAdaptor< Type, InputType, Container >::set(), and PrecisionAdaptor< Type, InputType, Container >::~PrecisionAdaptor().
set()
template<class Type , class InputType , template< class > class Container = Field> void set (Container< InputType > & input, const bool doCopy = true) inline
Definition at line 269 of file PrecisionAdaptor.H.
References PrecisionAdaptor< Type, InputType, Container >::commit(), UPtrList< T >::get(), and Foam::input().
The documentation for this class was generated from the following file:
src/OpenFOAM/memory/PrecisionAdaptor/PrecisionAdaptor.H