OpenFOAM: zoneIdentifier Class Reference
zoneIdentifier Class Reference
Identifies a mesh zone by name and index, with optional physical type and group information.
#include <zoneIdentifier.H>
Public Member Functions
zoneIdentifier (const zoneIdentifier &)=default
zoneIdentifier & operator= (const zoneIdentifier &)=default
virtual ~zoneIdentifier ()=default
zoneIdentifier ()
zoneIdentifier (const word &name, const label index)
zoneIdentifier (const word &name, const label index, const word &physicalType, const wordList &inGroups=wordList())
zoneIdentifier (const word &name, const dictionary &dict, const label index)
zoneIdentifier (const zoneIdentifier &ident, const label index)
const word & name () const noexcept
word & name () noexcept
label index () const noexcept
label & index () noexcept
const word & physicalType () const noexcept
word & physicalType () noexcept
const wordList & inGroups () const noexcept
wordList & inGroups () noexcept
bool inGroup (const word &name) const
void write (Ostream &os) const
Detailed Description
Identifies a mesh zone by name and index, with optional physical type and group information.
See also
patchIdentifier
Source files
zoneIdentifier.H
zoneIdentifier.C
Definition at line 53 of file zoneIdentifier.H.
Constructor & Destructor Documentation
zoneIdentifier() [1/6]
zoneIdentifier (const zoneIdentifier &) default
~zoneIdentifier()
virtual ~zoneIdentifier () virtual default
zoneIdentifier() [2/6]
zoneIdentifier ()
Definition at line 26 of file zoneIdentifier.C.
zoneIdentifier() [3/6]
zoneIdentifier (const word & name, const label index)
Definition at line 33 of file zoneIdentifier.C.
zoneIdentifier() [4/6]
zoneIdentifier (const word & name, const label index, const word & physicalType, const wordList & inGroups = wordList())
Definition at line 44 of file zoneIdentifier.C.
zoneIdentifier() [5/6]
zoneIdentifier (const word & name, const dictionary & dict, const label index)
Definition at line 59 of file zoneIdentifier.C.
References dict.
zoneIdentifier() [6/6]
zoneIdentifier (const zoneIdentifier & ident, const label index)
Definition at line 73 of file zoneIdentifier.C.
Member Function Documentation
operator=()
zoneIdentifier & operator= (const zoneIdentifier &) default
name() [1/2]
const word & name () const inline noexcept
Definition at line 119 of file zoneIdentifier.H.
Referenced by zoneIdentifier::inGroup(), cellZone::New(), faceZone::New(), pointZone::New(), fvMeshDistribute::printMeshInfo(), ABAQUSsurfaceFormat< Face >::write(), AC3DsurfaceFormat< Face >::write(), OBJsurfaceFormat< Face >::write(), OFFsurfaceFormat< Face >::write(), AC3DsurfaceFormat< Face >::write(), FLMAsurfaceFormat< Face >::write(), STLsurfaceFormat< Face >::writeAscii(), and meshRefinement::zonify().
name() [2/2]
word & name () inline noexcept
Definition at line 125 of file zoneIdentifier.H.
index() [1/2]
label index () const inline noexcept
Definition at line 131 of file zoneIdentifier.H.
Referenced by cellZone::clone(), faceZone::clone(), faceZone::clone(), cellZone::clone(), pointZone::clone(), pointZone::clone(), cellZone::New(), faceZone::New(), and pointZone::New().
index() [2/2]
label & index () inline noexcept
Definition at line 137 of file zoneIdentifier.H.
physicalType() [1/2]
const word & physicalType () const inline noexcept
Definition at line 143 of file zoneIdentifier.H.
physicalType() [2/2]
word & physicalType () inline noexcept
Definition at line 149 of file zoneIdentifier.H.
inGroups() [1/2]
const wordList & inGroups () const inline noexcept
Definition at line 155 of file zoneIdentifier.H.
inGroups() [2/2]
wordList & inGroups () inline noexcept
Definition at line 161 of file zoneIdentifier.H.
inGroup()
bool inGroup (const word & name) const inline
Definition at line 167 of file zoneIdentifier.H.
References UList< T >::found(), and zoneIdentifier::name().
write()
void write (Ostream & os) const
Definition at line 88 of file zoneIdentifier.C.
References token::END_STATEMENT, Foam::nl, os(), Ostream::writeEntry(), and Ostream::writeKeyword().
Referenced by cellZone::writeDict(), faceZone::writeDict(), and pointZone::writeDict().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/Identifiers/zone/zoneIdentifier.H
src/OpenFOAM/meshes/Identifiers/zone/zoneIdentifier.C