OpenFOAM: fvMeshTools Class Reference
fvMeshTools Class Reference
A collection of tools for operating on an fvMesh.
#include <fvMeshTools.H>
Static Public Member Functions
static label addPatch (fvMesh &mesh, const polyPatch &patch, const dictionary &patchFieldDict, const word &defaultPatchFieldType, const bool validBoundary)
static void setPatchFields (fvMesh &mesh, const label patchi, const dictionary &patchFieldDict)
static void zeroPatchFields (fvMesh &mesh, const label patchi)
static void reorderPatches (fvMesh &, const labelList &oldToNew, const label nPatches, const bool validBoundary)
static labelList removeEmptyPatches (fvMesh &, const bool validBoundary)
static void setBasicGeometry (fvMesh &mesh)
static autoPtr< fvMesh > newMesh (const IOobject &io, const bool masterOnlyReading, const bool verbose=false)
static autoPtr< fvMesh > loadOrCreateMesh (const IOobject &io, const bool decompose, const bool verbose=false)
static autoPtr< fvMesh > loadOrCreateMesh (const IOobject &io, refPtr< fileOperation > &readHandler, const bool verbose=true)
static void createDummyFvMeshFiles (const objectRegistry &parent, const word &regionName, const bool verbose=false)
static autoPtr< mapDistributePolyMesh > readProcAddressing (const fvMesh &procMesh, const autoPtr< fvMesh > &baseMeshPtr)
static void writeProcAddressing (const fvMesh &procMesh, const mapDistributePolyMesh &map, const bool decompose, refPtr< fileOperation > &writeHandler)
Detailed Description
A collection of tools for operating on an fvMesh.
Source files
fvMeshTools.H
fvMeshTools.C
fvMeshToolsProcAddr.C
fvMeshToolsTemplates.C
Definition at line 53 of file fvMeshTools.H.
Member Function Documentation
addPatch()
Foam::label addPatch (fvMesh & mesh, const polyPatch & patch, const dictionary & patchFieldDict, const word & defaultPatchFieldType, const bool validBoundary) static
Definition at line 37 of file fvMeshTools.C.
References PtrList< T >::clone(), doLocalCode, forAll, Foam::identity(), mesh, fvPatch::New(), pp(), UPtrList< T >::reorder(), PtrList< T >::resize(), PtrList< T >::set(), and UPtrList< T >::size().
setPatchFields()
void setPatchFields (fvMesh & mesh, const label patchi, const dictionary & patchFieldDict) static
Definition at line 188 of file fvMeshTools.C.
References doLocalCode.
zeroPatchFields()
void zeroPatchFields (fvMesh & mesh, const label patchi) static
Definition at line 223 of file fvMeshTools.C.
References doLocalCode.
reorderPatches()
void reorderPatches (fvMesh & mesh, const labelList & oldToNew, const label nPatches, const bool validBoundary) static
Definition at line 316 of file fvMeshTools.C.
References fvMesh::boundary(), polyMesh::boundaryMesh(), doLocalCode, mesh, and UPtrList< T >::reorder().
removeEmptyPatches()
Foam::labelList removeEmptyPatches (fvMesh & mesh, const bool validBoundary) static
Definition at line 362 of file fvMeshTools.C.
References polyMesh::boundaryMesh(), forAll, mesh, pbm, pp(), Foam::reduce(), PtrList< T >::resize(), and UPtrList< T >::size().
setBasicGeometry()
void setBasicGeometry (fvMesh & mesh) static
Definition at line 425 of file fvMeshTools.C.
References surfaceInterpolation::geometry(), and mesh.
newMesh()
Foam::autoPtr< Foam::fvMesh > newMesh (const IOobject & io, const bool masterOnlyReading, const bool verbose = false) static
Definition at line 445 of file fvMeshTools.C.
References fvMesh::addFvPatches(), polyMesh::addZones(), PtrList< T >::append(), fvMesh::boundary(), polyMesh::boundaryMesh(), Pstream::broadcasts(), polyMesh::cellZones(), PtrList< T >::clear(), PtrList< T >::clone(), IOobject::db(), e, UPtrList< T >::empty(), polyMesh::faceZones(), IOobject::fileModificationChecking, forAll, UList< T >::get(), io(), Foam::isDir(), UPstream::master(), mesh, meshPtr, polyMesh::meshSubDir, IOobjectOption::MUST_READ, IOobject::name(), Foam::name(), autoPtr< T >::New(), polyPatch::New(), primitiveMesh::nInternalFaces(), IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, nPatches, UPstream::parRun(), points, polyMesh::pointZones(), IOobjectOption::READ_IF_PRESENT, polyMesh::regionName(), fvMesh::removeFvBoundary(), Foam::returnReduceOr(), PtrList< T >::set(), UPtrList< T >::size(), UList< T >::size(), IOobject::time(), IOobject::timeStamp, Foam::type(), and UPstream::worldComm.
loadOrCreateMesh() [1/2]
Foam::autoPtr< Foam::fvMesh > loadOrCreateMesh (const IOobject & io, const bool decompose, const bool verbose = false) static
Definition at line 1182 of file fvMeshTools.C.
References io().
loadOrCreateMesh() [2/2]
Foam::autoPtr< Foam::fvMesh > loadOrCreateMesh (const IOobject & io, refPtr< fileOperation > & readHandler, const bool verbose = true) static
Parameters
readHandler Non-null reference if a mesh exists on given processor
Definition at line 1200 of file fvMeshTools.C.
References io().
createDummyFvMeshFiles()
void createDummyFvMeshFiles (const objectRegistry & parent, const word & regionName, const bool verbose = false) static
Definition at line 1217 of file fvMeshTools.C.
References dictionary::add(), dict, Foam::endl(), Foam::Info, io(), mesh, IOobject::name(), IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, regionName, fvMesh::thisDb(), fvMesh::time(), and IOobject::typeHeaderOk().
Referenced by voxelMeshSearch::makeMesh().
readProcAddressing()
Foam::autoPtr< Foam::mapDistributePolyMesh > readProcAddressing (const fvMesh & procMesh, const autoPtr< fvMesh > & baseMeshPtr) static
Definition at line 212 of file fvMeshToolsProcAddr.C.
References Foam::createReconstructMap(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::Info, mesh, polyMesh::meshSubDir, Foam::nl, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, IOobject::objectRelPath(), IOobjectOption::READ_IF_PRESENT, UPtrList< T >::size(), UList< T >::size(), and Foam::Zero.
writeProcAddressing()
void writeProcAddressing (const fvMesh & procMesh, const mapDistributePolyMesh & map, const bool decompose, refPtr< fileOperation > & writeHandler) static
Definition at line 294 of file fvMeshToolsProcAddr.C.
References polyMesh::boundaryMesh(), mapDistributePolyMesh::cellMap(), mapDistributePolyMesh::distributeCellData(), mapDistributePolyMesh::distributePointData(), Foam::endl(), mapDistributePolyMesh::faceMap(), Foam::faceMap(), polyMesh::facesInstance(), fileOperation::fileHandler(), Foam::identity(), Foam::Info, mesh, polyMesh::meshSubDir, primitiveMesh::nCells(), primitiveMesh::nFaces(), IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, mapDistributePolyMesh::nOldCells(), mapDistributePolyMesh::nOldFaces(), mapDistributePolyMesh::nOldPoints(), UPstream::nonBlocking, primitiveMesh::nPoints(), IOobject::objectRelPath(), mapDistributePolyMesh::oldPatchSizes(), mapDistributePolyMesh::patchMap(), mapDistributePolyMesh::pointMap(), UPtrList< T >::size(), fvMesh::thisDb(), WarningInFunction, regIOobject::write(), and Foam::Zero.
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/fvMeshTools/fvMeshTools.H
src/finiteVolume/fvMesh/fvMeshTools/fvMeshTools.C
src/finiteVolume/fvMesh/fvMeshTools/fvMeshToolsProcAddr.C
src/finiteVolume/fvMesh/fvMeshTools/fvMeshToolsTemplates.C