OpenFOAM: ijkAddressing Class Reference
ijkAddressing Class Reference
A simple i-j-k (row-major order) to linear addressing.
#include <ijkAddressing.H>
Public Member Functions
ijkAddressing ()
ijkAddressing (const labelVector &ijk)
ijkAddressing (const label ni, const label nj, const label nk)
bool empty () const
const labelVector & sizes () const
labelVector & sizes ()
label size () const
const label & size (const vector::components cmpt) const
void clear ()
void reset (const label ni, const label nj, const label nk)
void reset (const labelVector &newSizes)
label index (const label i, const label j, const label k) const
label index (const labelVector &ijk) const
labelVector index (const label idx) const
void checkIndex (const label i, const label j, const label k, const bool allowExtra=false) const
void checkIndex (const labelVector &ijk, const bool allowExtra=false) const
void checkSizes () const
void checkSizes (const labelVector &other) const
void checkSizes (const label nTotal) const
Detailed Description
A simple i-j-k (row-major order) to linear addressing.
Source files
ijkAddressing.H
ijkAddressingI.H
Definition at line 47 of file ijkAddressing.H.
Constructor & Destructor Documentation
ijkAddressing() [1/3]
ijkAddressing () inline
Definition at line 23 of file ijkAddressingI.H.
ijkAddressing() [2/3]
ijkAddressing (const labelVector & ijk) inline explicit
Definition at line 29 of file ijkAddressingI.H.
References ijkAddressing::checkSizes().
ijkAddressing() [3/3]
ijkAddressing (const label ni, const label nj, const label nk) inline
Definition at line 39 of file ijkAddressingI.H.
References ijkAddressing::checkSizes().
Member Function Documentation
empty()
bool empty () const inline
Definition at line 56 of file ijkAddressingI.H.
Referenced by ijkMesh::nBoundaryFaces(), ijkMesh::nBoundaryFaces(), ijkMesh::nFaces(), ijkMesh::nInternalFaces(), and ijkMesh::nPoints().
sizes() [1/2]
const Foam::labelVector & sizes () const inline
Definition at line 62 of file ijkAddressingI.H.
Referenced by blockDescriptor::blockDescriptor(), PDRblock::blockMeshDict(), blockDescriptor::density(), ijkMesh::nBoundaryFaces(), ijkMesh::nBoundaryFaces(), ijkMesh::nFaces(), ijkMesh::nInternalFaces(), and ijkMesh::nPoints().
sizes() [2/2]
Foam::labelVector & sizes () inline
Definition at line 68 of file ijkAddressingI.H.
size() [1/2]
Foam::label size () const inline
Definition at line 74 of file ijkAddressingI.H.
Referenced by ijkMesh::nCells().
size() [2/2]
const Foam::label & size (const vector::components cmpt) const inline
Definition at line 81 of file ijkAddressingI.H.
clear()
void clear () inline
Definition at line 90 of file ijkAddressingI.H.
References Foam::Zero.
reset() [1/2]
void reset (const label ni, const label nj, const label nk) inline
Definition at line 96 of file ijkAddressingI.H.
reset() [2/2]
void reset (const labelVector & newSizes) inline
Definition at line 113 of file ijkAddressingI.H.
index() [1/3]
Foam::label index (const label i, const label j, const label k) const inline
Definition at line 123 of file ijkAddressingI.H.
References k.
Referenced by ijkMesh::cellLabel(), ijkMesh::cellLabel(), and namedBlock::namedBlock().
index() [2/3]
Foam::label index (const labelVector & ijk) const inline
Definition at line 138 of file ijkAddressingI.H.
References Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
index() [3/3]
Foam::labelVector index (const label idx) const inline
Definition at line 148 of file ijkAddressingI.H.
checkIndex() [1/2]
void checkIndex (const label i, const label j, const label k, const bool allowExtra = false) const inline
Definition at line 161 of file ijkAddressingI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, k, and Foam::nl.
Referenced by PDRblock::location::C(), and PDRblock::location::width().
checkIndex() [2/2]
void checkIndex (const labelVector & ijk, const bool allowExtra = false) const inline
Definition at line 195 of file ijkAddressingI.H.
References Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
checkSizes() [1/3]
void checkSizes () const inline
Definition at line 205 of file ijkAddressingI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and Foam::nl.
Referenced by ijkAddressing::ijkAddressing(), and ijkAddressing::ijkAddressing().
checkSizes() [2/3]
void checkSizes (const labelVector & other) const inline
Definition at line 228 of file ijkAddressingI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and Foam::nl.
checkSizes() [3/3]
void checkSizes (const label nTotal) const inline
Definition at line 240 of file ijkAddressingI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and Foam::nl.
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/ijkMesh/ijkAddressing.H
src/OpenFOAM/meshes/ijkMesh/ijkAddressingI.H