OpenFOAM: meshedSurf Class Reference
meshedSurf Class Reference abstract
Abstract definition of a meshed surface defined by faces and points.
#include <meshedSurf.H>
Classes
class emptySurface
Public Member Functions
constexpr meshedSurf () noexcept=default
virtual ~meshedSurf ()=default
virtual const pointField & points () const =0
virtual const faceList & faces () const =0
virtual const labelList & zoneIds () const
virtual const labelList & faceIds () const
Detailed Description
Abstract definition of a meshed surface defined by faces and points.
Definition at line 43 of file meshedSurf.H.
Constructor & Destructor Documentation
meshedSurf()
constexpr meshedSurf () constexpr default noexcept
~meshedSurf()
virtual ~meshedSurf () virtual default
Member Function Documentation
points()
virtual const pointField & points () const pure virtual
Implemented in sampledDistanceSurface, sampledIsoSurface, sampledCuttingPlane, sampledCuttingSurface, sampledFaceZone, sampledMeshedSurface, sampledNone, sampledPatch, sampledPlane, sampledThresholdCellFaces, meshedSurf::emptySurface, meshedSurfRef, polySurface, sampledInterface, sampledSurface, and mergedSurf.
Referenced by polySurface::copySurface(), and surfMesh::copySurface().
faces()
virtual const faceList & faces () const pure virtual
Implemented in sampledDistanceSurface, sampledIsoSurface, sampledCuttingPlane, sampledCuttingSurface, sampledFaceZone, sampledMeshedSurface, sampledNone, sampledPatch, sampledPlane, sampledThresholdCellFaces, meshedSurf::emptySurface, meshedSurfRef, polySurface, sampledInterface, sampledSurface, and mergedSurf.
Referenced by polySurface::copySurface(), surfMesh::copySurface(), and debugWriter::write().
zoneIds()
virtual const labelList & zoneIds () const inline virtual
Reimplemented in sampledDistanceSurface, sampledIsoSurface, sampledCuttingPlane, sampledCuttingSurface, sampledFaceZone, sampledMeshedSurface, sampledNone, sampledPatch, sampledPlane, sampledThresholdCellFaces, meshedSurfRef, polySurface, sampledInterface, and mergedSurf.
Definition at line 71 of file meshedSurf.H.
References List< label >::null().
Referenced by polySurface::copySurface().
faceIds()
virtual const labelList & faceIds () const inline virtual
Reimplemented in sampledMeshedSurface, meshedSurfRef, and mergedSurf.
Definition at line 77 of file meshedSurf.H.
References List< label >::null().
The documentation for this class was generated from the following file:
src/surfMesh/meshedSurf/meshedSurf.H