OpenFOAM: filmFlux Class Reference
filmFlux Class Reference
FunctionObjects » Field function objects
Calculates the mass flux for surface film models.
#include <filmFlux.H>
Public Member Functions
TypeName ("filmFlux")
filmFlux (const word &name, const Time &runTime, const dictionary &dict)
filmFlux (const filmFlux &)=delete
void operator= (const filmFlux &)=delete
virtual ~filmFlux ()=default
virtual bool read (const dictionary &)
virtual bool execute ()
virtual bool write ()
Public Member Functions inherited from stateFunctionObject
stateFunctionObject (const word &name, const Time &runTime)
virtual ~stateFunctionObject ()=default
dictionary & propertyDict ()
bool foundProperty (const word &entryName) const
void clearTrigger ()
label getTrigger () const
bool setTrigger (const label triggeri)
bool getDict (const word &entryName, dictionary &dict) const
bool getObjectDict (const word &objectName, const word &entryName, dictionary &dict) const
template<class Type >
Type getProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getProperty (const word &entryName, Type &value) const
template<class Type >
void setProperty (const word &entryName, const Type &value)
template<class Type >
Type getObjectProperty (const word &objectName, const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getObjectProperty (const word &objectName, const word &entryName, Type &value) const
template<class Type >
void setObjectProperty (const word &objectName, const word &entryName, const Type &value)
template<class Type >
void setResult (const word &entryName, const Type &value)
template<class Type >
void setObjectResult (const word &objectName, const word &entryName, const Type &value)
template<class Type >
Type getResult (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
Type getObjectResult (const word &objectName, const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getObjectResult (const word &objectName, const word &entryName, Type &value) const
word resultType (const word &entryName) const
word objectResultType (const word &objectName, const word &entryName) const
wordList objectResultEntries () const
wordList objectResultEntries (const word &objectName) const
void writeResultEntries (Ostream &os) const
void writeResultEntries (const word &objectName, Ostream &os) const
void writeAllResultEntries (Ostream &os) const
Public Member Functions inherited from timeFunctionObject
timeFunctionObject (const word &name, const Time &runTime)
virtual ~timeFunctionObject ()=default
const Time & time () const
objectRegistry & storedObjects ()
const objectRegistry & storedObjects () const
Public Member Functions inherited from functionObject
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name, const bool withNamePrefix=defaultUseNamePrefix)
autoPtr< functionObject > clone () const
virtual ~functionObject ()=default
virtual const word & type () const =0
const word & name () const noexcept
bool useNamePrefix () const noexcept
bool useNamePrefix (bool on) noexcept
virtual bool execute (const label subIndex)
virtual bool end ()
virtual bool adjustTimeStep ()
virtual bool filesModified () const
virtual void updateMesh (const mapPolyMesh &mpm)
virtual void movePoints (const polyMesh &mesh)
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &runTime, const dictionary &dict)
Public Attributes inherited from functionObject
bool log
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
static bool defaultUseNamePrefix
static word outputPrefix
Protected Member Functions inherited from stateFunctionObject
const functionObjects::properties & stateDict () const
functionObjects::properties & stateDict ()
stateFunctionObject (const stateFunctionObject &)=delete
void operator= (const stateFunctionObject &)=delete
Protected Member Functions inherited from timeFunctionObject
void clearOutputObjects (const wordList &objNames)
timeFunctionObject (const timeFunctionObject &)=delete
void operator= (const timeFunctionObject &)=delete
Protected Member Functions inherited from functionObject
word scopedName (const word &name) const
Protected Attributes inherited from timeFunctionObject
const Time & time_
Detailed Description
Calculates the mass flux for surface film models.
Operands:
Operand Type Location
input dictionary constant/<surfaceFilmProperties>
output file - -
output field
surfaceScalarField
<time>/<filmRegion>/<outField>
Usage
Minimal example by using system/controlDict.functions:
filmFlux1
{
    // Mandatory entries (unmodifiable)
    type        filmFlux;
    // Optional entries (runtime modifiable)
    film        <surfaceFilmPropertiesDictionary>;
    result      <resultName>;
    // Optional (inherited) entries
    ...
}
where the entries mean:
Property Description Type Reqd Dflt
type Type name: filmFlux word yes -
film
Name of surface film properties dictionary
dict no surfaceFilmProperties
result Name of result field word no filmFlux
The inherited entries are elaborated in:
stateFunctionObject.H
Usage by the postProcess utility is not available.
See also
Foam::functionObjects::stateFunctionObject
Source files
filmFlux.H
flux.C
Definition at line 139 of file filmFlux.H.
Constructor & Destructor Documentation
filmFlux() [1/2]
filmFlux (const word & name, const Time & runTime, const dictionary & dict)
Definition at line 48 of file filmFlux.C.
References dict, and filmFlux::read().
filmFlux() [2/2]
filmFlux (const filmFlux &) delete
~filmFlux()
virtual ~filmFlux () virtual default
Member Function Documentation
TypeName()
TypeName ("filmFlux")
operator=()
void operator= (const filmFlux &) delete
read()
bool read (const dictionary & dict) virtual
Reimplemented from functionObject.
Definition at line 65 of file filmFlux.C.
References dict, and functionObject::read().
Referenced by filmFlux::filmFlux().
execute()
bool execute () virtual
Implements functionObject.
Definition at line 79 of file filmFlux.C.
References GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), Foam::dimLength, Foam::dimMass, Foam::dimTime, Foam::fvc::interpolate(), Foam::max(), IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, phi, GeometricField< Type, PatchField, GeoMesh >::ref(), IOobjectOption::REGISTER, Foam::Zero, and fvPatchFieldBase::zeroGradientType().
write()
bool write () virtual
Implements functionObject.
Definition at line 140 of file filmFlux.C.
References write().
The documentation for this class was generated from the following files:
src/regionModels/surfaceFilmModels/functionObjects/filmFlux/filmFlux.H
src/regionModels/surfaceFilmModels/functionObjects/filmFlux/filmFlux.C