OpenFOAM: booleanSurface Class Reference
booleanSurface Class Reference
Surface-surface intersection. Given two surfaces construct combined surface.
#include <booleanSurface.H>
Public Types
enum booleanOpType { UNION , INTERSECTION , DIFFERENCE , ALL }
Public Types inherited from triSurface
typedef bool BoundaryMesh
typedef labelledTri face_type
typedef point point_type
Public Types inherited from PrimitivePatch<::Foam::List< labelledTri >, pointField >
enum surfaceTopo
typedef std::remove_reference< ::Foam::List< labelledTri > >::type::value_type face_type
typedef std::remove_reference< pointField >::type::value_type point_type
typedef ::Foam::List< labelledTri > FaceListType
typedef pointField PointFieldType
typedef face_type FaceType
Public Types inherited from List< labelledTri >
typedef SubList< labelledTri > subList
Public Types inherited from UList< T >
typedef T value_type
typedef T * pointer
typedef const T * const_pointer
typedef T & reference
typedef const T & const_reference
typedef T * iterator
typedef const T * const_iterator
typedef label size_type
typedef label difference_type
typedef std::reverse_iterator< iterator > reverse_iterator
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
Public Member Functions
ClassName ("booleanSurface")
booleanSurface ()
booleanSurface (const triSurface &surf1, const triSurface &surf2, const surfaceIntersection &inter, const label includeFace1, const label includeFace2)
booleanSurface (const triSurface &surf1, const triSurface &surf2, const surfaceIntersection &inter, const label booleanOp)
const labelList & faceMap () const
bool from1 (const label facei) const
bool surf1Face (const label facei) const
bool surf2Face (const label facei) const
Public Member Functions inherited from triSurface
ClassName ("triSurface")
triSurface ()
triSurface (const triSurface &surf)
triSurface (triSurface &&surf)
triSurface (const List< labelledTri > &triangles, const geometricSurfacePatchList &patches, const pointField &pts)
triSurface (List< labelledTri > &triangles, const geometricSurfacePatchList &patches, pointField &pts, const bool reuse)
triSurface (const List< labelledTri > &triangles, const pointField &pts)
triSurface (const triFaceList &triangles, const pointField &pts)
triSurface (const fileName &name, const scalar scaleFactor=-1)
triSurface (const fileName &name, const word &fileType, const scalar scaleFactor=-1)
triSurface (Istream &is)
triSurface (const Time &d)
triSurface (const IOobject &io, const dictionary &dict, const bool isGlobal=true)
virtual ~triSurface ()
void clearOut ()
void clearTopology ()
void clearPatchMeshAddr ()
void swap (triSurface &surf)
const geometricSurfacePatchList & patches () const noexcept
geometricSurfacePatchList & patches () noexcept
const List< labelledTri > & surfFaces () const noexcept
const labelListList & sortedEdgeFaces () const
const labelList & edgeOwner () const
const vectorField & Sf () const
const scalarField & magSf () const
const vectorField & Cf () const
List< surfZone > sortedZones (labelList &faceMap) const
void triFaceFaces (List< face > &plainFaceList) const
virtual void movePoints (const pointField &pts)
virtual void swapPoints (pointField &pts)
virtual void scalePoints (const scalar scaleFactor)
void checkTriangles (const bool verbose)
void checkEdges (const bool verbose)
void cleanup (const bool verbose)
void compactPoints (labelList &pointMap=const_cast< labelList & >(labelList::null()))
void markZone (const boolList &borderEdge, const label facei, const label currentZone, labelList &faceZone) const
label markZones (const boolList &borderEdge, labelList &faceZone) const
template<class BoolListType >
void subsetMeshMap (const BoolListType &include, labelList &pointMap, labelList &faceMap) const
triSurface subsetMesh (const UList< bool > &include, labelList &pointMap, labelList &faceMap) const
triSurface subsetMesh (const bitSet &include, labelList &pointMap, labelList &faceMap) const
triSurface subsetMesh (const UList< bool > &include) const
triSurface subsetMesh (const bitSet &include) const
triSurface subsetMesh (const wordRes &includeNames, const wordRes &excludeNames=wordRes()) const
void swapFaces (List< labelledTri > &faceLst)
void transfer (triSurface &surf)
void transfer (MeshedSurface< labelledTri > &surf)
void write (Ostream &os) const
void write (const fileName &, const bool sortByRegion=false) const
void write (const fileName &filename, const word &fileType, const bool sortByRegion=false) const
void write (const Time &d) const
void writeStats (Ostream &os) const
void operator= (const triSurface &surf)
void operator= (triSurface &&surf)
void operator= (MeshedSurface< labelledTri > &&surf)
Public Member Functions inherited from PrimitivePatch<::Foam::List< labelledTri >, pointField >
PrimitivePatch (const ::Foam::List< labelledTri > &faces, const pointField &points)
PrimitivePatch (::Foam::List< labelledTri > &&faces, const pointField &points)
PrimitivePatch (::Foam::List< labelledTri > &faces, pointField &points, const bool reuse)
PrimitivePatch (const PrimitivePatch< ::Foam::List< labelledTri >, pointField > &pp)
virtual ~PrimitivePatch ()
void clearOut ()
void clearGeom ()
void clearTopology ()
void clearPatchMeshAddr ()
void swap (PrimitivePatch &)=delete
const Field< point_type > & points () const noexcept
label nFaces () const noexcept
label nPoints () const
label nEdges () const
const edgeList & edges () const
const edgeList::subList internalEdges () const
const edgeList::subList boundaryEdges () const
label nInternalEdges () const
label nBoundaryEdges () const
bool isInternalEdge (const label edgei) const
const labelList & boundaryPoints () const
const labelListList & faceFaces () const
const labelListList & edgeFaces () const
const labelListList & faceEdges () const
const labelListList & pointEdges () const
const labelListList & pointFaces () const
const List< face_type > & localFaces () const
labelList boundaryFaces () const
labelList uniqBoundaryFaces () const
const labelList & meshPoints () const
const Map< label > & meshPointMap () const
const Field< point_type > & localPoints () const
const labelList & localPointOrder () const
label whichPoint (const label gp) const
edge meshEdge (const label edgei) const
edge meshEdge (const edge &e) const
label meshEdge (const label edgei, const edgeList &allEdges, const labelListList &pointEdges) const
label findEdge (const edge &e) const
labelList meshEdges (const edgeList &allEdges, const labelListList &cellEdges, const labelList &faceCells) const
labelList meshEdges (const edgeList &allEdges, const labelListList &pointEdges) const
labelList meshEdges (const labelUList &edgeLabels, const edgeList &allEdges, const labelListList &pointEdges) const
const Field< point_type > & faceCentres () const
const Field< point_type > & faceAreas () const
const Field< scalar > & magFaceAreas () const
const Field< point_type > & faceNormals () const
const Field< point_type > & pointNormals () const
Pair< point_type > box () const
scalar sphere (const label facei) const
bool hasFaceAreas () const
bool hasFaceCentres () const
bool hasFaceNormals () const
bool hasPointNormals () const
bool hasBoundaryPoints () const
bool hasEdges () const
bool hasFaceFaces () const
bool hasEdgeFaces () const
bool hasFaceEdges () const
bool hasPointEdges () const
bool hasPointFaces () const
bool hasMeshPoints () const
bool hasMeshPointMap () const
List< objectHit > projectPoints (const ToPatch &targetPatch, const Field< point_type > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Foam::List< Foam::objectHit > projectPoints (const ToPatch &targetPatch, const Field< typename Foam::PrimitivePatch< ::Foam::List< labelledTri >, pointField >::point_type > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
List< objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< point_type > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Foam::List< Foam::objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< typename Foam::PrimitivePatch< ::Foam::List< labelledTri >, pointField >::point_type > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
const labelListList & edgeLoops () const
surfaceTopo surfaceType (labelHashSet *badEdgesPtr=nullptr) const
bool checkTopology (const bool report=false, labelHashSet *pointSetPtr=nullptr) const
bool checkPointManifold (const bool report=false, labelHashSet *pointSetPtr=nullptr) const
virtual void movePoints (const Field< point_type > &)
void operator= (const PrimitivePatch< ::Foam::List< labelledTri >, pointField > &rhs)
void operator= (PrimitivePatch< ::Foam::List< labelledTri >, pointField > &&rhs)
label whichEdge (const edge &e) const
Public Member Functions inherited from PrimitivePatchBase
ClassName ("PrimitivePatch")
PrimitivePatchBase ()=default
Public Member Functions inherited from List< labelledTri >
constexpr List () noexcept
List (const label len)
List (const label len, const labelledTri &val)
List (const label len, const Foam::zero)
List (const Foam::one, const labelledTri &val)
List (const Foam::one, labelledTri &&val)
List (const Foam::one, const Foam::zero)
List (const List< labelledTri > &a)
List (const UList< labelledTri > &a)
List (List< labelledTri > &a, bool reuse)
List (const UList< labelledTri > &list, const labelUList &indices)
List (const UList< labelledTri > &list, const FixedList< label, N > &indices)
List (const FixedList< labelledTri, N > &list)
List (const PtrList< labelledTri > &list)
List (const SLList< labelledTri > &list)
List (const IndirectListBase< labelledTri, Addr > &list)
List (std::initializer_list< labelledTri > list)
List (List< labelledTri > &&list)
List (DynamicList< labelledTri, SizeMin > &&list)
List (SLList< labelledTri > &&list)
List (Istream &is)
autoPtr< List< labelledTri > > clone () const
~List ()
void clear ()
void resize (const label len)
void resize (const label len, const labelledTri &val)
void resize (const label newLen)
void resize_nocopy (const label len)
void setSize (const label n)
void setSize (const label n, const labelledTri &val)
void transfer (List< labelledTri > &list)
void transfer (DynamicList< labelledTri, SizeMin > &list)
labelledTri & newElmt (const label i)
labelledTri & emplace_back (Args &&... args)
void push_back (const labelledTri &val)
void push_back (labelledTri &&val)
void push_back (const UList< labelledTri > &list)
void push_back (const IndirectListBase< labelledTri, Addr > &list)
label push_uniq (const labelledTri &val)
void pop_back (label n=1)
void operator= (const UList< labelledTri > &a)
void operator= (const List< labelledTri > &list)
void operator= (const SLList< labelledTri > &list)
void operator= (const IndirectListBase< labelledTri, Addr > &list)
void operator= (const FixedList< labelledTri, N > &list)
void operator= (std::initializer_list< labelledTri > list)
void operator= (const labelledTri &val)
void operator= (const Foam::zero)
void operator= (List< labelledTri > &&list)
void operator= (DynamicList< labelledTri, SizeMin > &&list)
void operator= (SLList< labelledTri > &&list)
Istream & readList (Istream &is)
Istream & readList (Istream &is)
Istream & readList (Istream &is)
void shallowCopy (const UList< labelledTri > &)=delete
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type set (const label i, bool val=true)
void append (const labelledTri &val)
void append (labelledTri &&val)
void append (const UList< labelledTri > &list)
void append (const IndirectListBase< labelledTri, Addr > &list)
label appendUniq (const labelledTri &val)
Public Member Functions inherited from UList< T >
UList (const UList< T > &)=default
constexpr UList () noexcept
UList (T *__restrict__ v, const label len) noexcept
label fcIndex (const label i) const noexcept
label rcIndex (const label i) const noexcept
const T & fcValue (const label i) const
T & fcValue (const label i)
const T & rcValue (const label i) const
T & rcValue (const label i)
const T * cdata () const noexcept
T * data () noexcept
const char * cdata_bytes () const noexcept
char * data_bytes () noexcept
T & front ()
const T & front () const
T & back ()
const T & back () const
std::streamsize size_bytes () const noexcept
std::streamsize byteSize () const
void checkStart (const label start) const
void checkSize (const label size) const
void checkRange (const label start, const label len) const
void checkIndex (const label i) const
bool uniform () const
label find (const T &val, label pos=0) const
label rfind (const T &val, label pos=-1) const
bool contains (const T &val, label pos=0) const
void moveFirst (const label i)
void moveLast (const label i)
void swapFirst (const label i)
void swapLast (const label i)
void shallowCopy (const UList< T > &list)
void deepCopy (const UList< T > &list)
template<class Addr >
void deepCopy (const IndirectListBase< T, Addr > &list)
SubList< T > slice (const label pos, label len=-1)
const SubList< T > slice (const label pos, label len=-1) const
SubList< T > slice (const labelRange &range)
const SubList< T > slice (const labelRange &range) const
T & operator[] (const label i)
const T & operator[] (const label i) const
operator const Foam::List< T > & () const
void operator= (const T &val)
void operator= (const Foam::zero)
iterator begin () noexcept
iterator end () noexcept
iterator begin (const label i) noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
const_iterator begin () const noexcept
const_iterator end () const noexcept
const_iterator cbegin (const label i) const noexcept
const_iterator begin (const label i) const noexcept
reverse_iterator rbegin ()
reverse_iterator rend ()
const_reverse_iterator crbegin () const
const_reverse_iterator crend () const
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
bool empty () const noexcept
label size () const noexcept
void swap (UList< T > &list)
bool operator== (const UList< T > &a) const
bool operator!= (const UList< T > &a) const
bool operator< (const UList< T > &list) const
bool operator> (const UList< T > &a) const
bool operator<= (const UList< T > &a) const
bool operator>= (const UList< T > &a) const
Istream & readList (Istream &is)
void writeEntry (const word &keyword, Ostream &os) const
Ostream & writeList (Ostream &os, const label shortLen=0) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type test (const label i) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type get (const label i) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type unset (const label i)
T & first ()
const T & first () const
T & last ()
const T & last () const
bool found (const T &val, label pos=0) const
Istream & readList (Istream &is)
Ostream & writeList (Ostream &os, const label) const
const bool & operator[] (const label i) const
UPstream::commsStruct & operator[] (const label procID)
const UPstream::commsStruct & operator[] (const label procID) const
Foam::UPstream::commsStruct & operator[] (const label procID)
const Foam::UPstream::commsStruct & operator[] (const label procID) const
Ostream & writeList (Ostream &os, const label) const
Istream & readList (Istream &is)
Static Public Attributes
static const Enum< booleanOpType > booleanOpTypeNames
Additional Inherited Members
Static Public Member Functions inherited from triSurface
static fileName triSurfInstance (const Time &)
static wordHashSet readTypes ()
static wordHashSet writeTypes ()
static bool canReadType (const word &fileType, bool verbose=false)
static bool canWriteType (const word &fileType, bool verbose=false)
static bool canRead (const fileName &name, bool verbose=false)
static fileName relativeFilePath (const IOobject &io, const fileName &f, const bool isGlobal=true)
static fileName checkFile (const IOobject &io, const bool isGlobal=true)
static fileName checkFile (const IOobject &io, const dictionary &dict, const bool isGlobal=true)
static fileName findFile (const IOobject &io, const bool isGlobal=true)
static fileName findFile (const IOobject &io, const dictionary &dict, const bool isGlobal=true)
static autoPtr< triSurface > New (const fileName &name, const word &fileType)
static autoPtr< triSurface > New (const fileName &name)
Static Public Member Functions inherited from List< labelledTri >
static const List< labelledTri > & null ()
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
static constexpr label max_size () noexcept
Protected Member Functions inherited from triSurface
pointField & storedPoints ()
List< labelledTri > & storedFaces ()
Protected Member Functions inherited from UList< T >
void setAddressableSize (const label n) noexcept
void size (const label n)
void writeEntry (Ostream &os) const
labelRange validateRange (const labelRange &requestedRange) const
UList< T > & operator= (const UList< T > &)=delete
void writeEntry (Ostream &os) const
void writeEntry (Ostream &os) const
Detailed Description
Surface-surface intersection. Given two surfaces construct combined surface.
Called 'boolean' since the volume of resulting surface will encompass the volumes of the original surface according to some boolean operation:
all which is in surface1 AND in surface2 (intersection)
all which is in surface1 AND NOT in surface2 (surface1 minus surface2)
all which is in surface1 OR in surface2 (union)
Algorithm:
find edge-surface intersection. Class 'surfaceIntersection'.
combine intersection with both surfaces. Class 'intersectedSurface'.
subset surfaces upto intersection. The 'side' of the surface to include is based on the faces that can be reached from a user-supplied face index.
merge surfaces. Only the points on the intersection are shared.
Source files
booleanSurface.H
booleanSurface.C
Definition at line 67 of file booleanSurface.H.
Member Enumeration Documentation
booleanOpType
enum booleanOpType
Enumerator
UNION
INTERSECTION
DIFFERENCE
ALL
Definition at line 162 of file booleanSurface.H.
Constructor & Destructor Documentation
booleanSurface() [1/3]
booleanSurface ()
Definition at line 380 of file booleanSurface.C.
booleanSurface() [2/3]
booleanSurface (const triSurface & surf1, const triSurface & surf2, const surfaceIntersection & inter, const label includeFace1, const label includeFace2)
Definition at line 387 of file booleanSurface.C.
References Foam::endl(), Foam::exit(), f(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::Pout, List< T >::setSize(), UPtrList< T >::size(), and triSurface::triSurface().
booleanSurface() [3/3]
booleanSurface (const triSurface & surf1, const triSurface & surf2, const surfaceIntersection & inter, const label booleanOp)
Definition at line 698 of file booleanSurface.C.
References booleanSurface::ALL, PrimitivePatch<::Foam::List< labelledTri >, pointField >::edgeFaces(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, booleanSurface::INTERSECTION, Foam::nl, triSurface::operator=(), Foam::Pout, pts, labelledTri::region(), List< T >::setSize(), UPtrList< T >::size(), boundBox::span(), booleanSurface::UNION, WarningInFunction, and Foam::Zero.
Member Function Documentation
ClassName()
ClassName ("booleanSurface")
faceMap()
const labelList & faceMap () const inline
Definition at line 210 of file booleanSurface.H.
from1()
bool from1 (const label facei) const inline
Definition at line 215 of file booleanSurface.H.
Referenced by booleanSurface::surf1Face(), and booleanSurface::surf2Face().
surf1Face()
bool surf1Face (const label facei) const inline
Definition at line 220 of file booleanSurface.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and booleanSurface::from1().
surf2Face()
bool surf2Face (const label facei) const inline
Definition at line 231 of file booleanSurface.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and booleanSurface::from1().
Member Data Documentation
booleanOpTypeNames
const Foam::Enum< Foam::booleanSurface::booleanOpType > booleanOpTypeNames static
Definition at line 173 of file booleanSurface.H.
The documentation for this class was generated from the following files:
src/meshTools/triSurface/booleanOps/booleanSurface/booleanSurface.H
src/meshTools/triSurface/booleanOps/booleanSurface/booleanSurface.C