OpenFOAM: orientedType Class Reference
orientedType Class Reference
Class to determine the 'oriented' status of surface fields.
#include <orientedType.H>
Public Types
enum orientedOption : unsigned char { UNKNOWN = 0 , ORIENTED = 1 , UNORIENTED = 2 }
Public Member Functions
orientedType (const orientedType &) noexcept=default
orientedType & operator= (const orientedType &) noexcept=default
constexpr orientedType () noexcept
orientedType (orientedOption opt) noexcept
constexpr orientedType (const bool isOriented) noexcept
orientedType (Istream &is)
orientedOption oriented () const noexcept
orientedOption & oriented () noexcept
bool is_oriented () const noexcept
void setOriented (bool on=true) noexcept
void read (const dictionary &dict)
bool writeEntry (Ostream &os) const
void operator+= (const orientedType &ot)
void operator-= (const orientedType &ot)
void operator*= (const orientedType &ot)
void operator/= (const orientedType &ot)
void operator*= (const scalar s)
void operator/= (const scalar s)
bool operator() () const noexcept
Static Public Member Functions
static bool checkType (const orientedType &a, const orientedType &b) noexcept
Static Public Attributes
static const Enum< orientedOption > orientedOptionNames
Friends
Istream & operator>> (Istream &is, orientedType &ot)
Ostream & operator<< (Ostream &os, const orientedType &ot)
Detailed Description
Class to determine the 'oriented' status of surface fields.
Source files
orientedType.H
orientedType.C
Definition at line 52 of file orientedType.H.
Member Enumeration Documentation
orientedOption
enum orientedOption : unsigned char
Enumerator
UNKNOWN
Unknown/undefined orientation.
ORIENTED
Is oriented.
UNORIENTED
Is unoriented.
Definition at line 59 of file orientedType.H.
Constructor & Destructor Documentation
orientedType() [1/5]
orientedType (const orientedType &) default noexcept
orientedType() [2/5]
constexpr orientedType () inline constexpr noexcept
Definition at line 95 of file orientedType.H.
orientedType() [3/5]
orientedType (orientedOption opt) inline noexcept
Definition at line 101 of file orientedType.H.
orientedType() [4/5]
constexpr orientedType (const bool isOriented) inline explicit constexpr noexcept
Definition at line 107 of file orientedType.H.
orientedType() [5/5]
orientedType (Istream & is) explicit
Definition at line 94 of file orientedType.C.
References FUNCTION_NAME.
Member Function Documentation
operator=()
orientedType & operator= (const orientedType &) default noexcept
checkType()
bool checkType (const orientedType & a, const orientedType & b) static noexcept
Definition at line 42 of file orientedType.C.
References b.
oriented() [1/2]
orientedOption oriented () const inline noexcept
Definition at line 126 of file orientedType.H.
Referenced by Foam::checkTypes().
oriented() [2/2]
orientedOption & oriented () inline noexcept
Definition at line 129 of file orientedType.H.
is_oriented()
bool is_oriented () const inline noexcept
Definition at line 132 of file orientedType.H.
References orientedType::ORIENTED.
Referenced by Foam::lerp(), and orientedType::operator()().
setOriented()
void setOriented (bool on = true) inline noexcept
Definition at line 135 of file orientedType.H.
References orientedType::ORIENTED, and orientedType::UNORIENTED.
read()
void read (const dictionary & dict)
Definition at line 104 of file orientedType.C.
References dict.
writeEntry()
bool writeEntry (Ostream & os) const
Definition at line 116 of file orientedType.C.
References os(), Foam::output(), and Ostream::writeEntry().
operator+=()
void operator+= (const orientedType & ot)
Definition at line 131 of file orientedType.C.
References Foam::checkTypes().
operator-=()
void operator-= (const orientedType & ot)
Definition at line 143 of file orientedType.C.
References Foam::checkTypes().
operator*=() [1/2]
void operator*= (const orientedType & ot)
Definition at line 155 of file orientedType.C.
References setOriented().
operator/=() [1/2]
void operator/= (const orientedType & ot)
Definition at line 161 of file orientedType.C.
References setOriented().
operator*=() [2/2]
void operator*= (const scalar s)
Definition at line 167 of file orientedType.C.
operator/=() [2/2]
void operator/= (const scalar s)
Definition at line 173 of file orientedType.C.
operator()()
bool operator() () const inline noexcept
Definition at line 158 of file orientedType.H.
References orientedType::is_oriented().
Friends And Related Symbol Documentation
operator>>
Istream & operator>> (Istream & is, orientedType & ot) friend
operator<<
Ostream & operator<< (Ostream & os, const orientedType & ot) friend
Member Data Documentation
orientedOptionNames
const Foam::Enum< Foam::orientedType::orientedOption > orientedOptionNames static
Definition at line 70 of file orientedType.H.
Referenced by Foam::checkTypes(), Foam::operator<<(), and Foam::operator>>().
The documentation for this class was generated from the following files:
src/OpenFOAM/orientedType/orientedType.H
src/OpenFOAM/orientedType/orientedType.C