OpenFOAM: InertPhaseModel< BasePhaseModel > Class Template Reference
InertPhaseModel< BasePhaseModel > Class Template Reference
Class which represents an inert phase, with no reactions. Returns zero reaction rate and heat.
#include <InertPhaseModel.H>
Public Member Functions
InertPhaseModel (const phaseSystem &fluid, const word &phaseName, const label index)
virtual ~InertPhaseModel ()
virtual tmp< fvScalarMatrix > R (volScalarField &Yi) const
virtual tmp< volScalarField > Qdot () const
Detailed Description
template<class BasePhaseModel>
class Foam::InertPhaseModel< BasePhaseModel >
Class which represents an inert phase, with no reactions. Returns zero reaction rate and heat.
Source files
InertPhaseModel.H
InertPhaseModel.C
Definition at line 48 of file InertPhaseModel.H.
Constructor & Destructor Documentation
InertPhaseModel()
template<class BasePhaseModel > InertPhaseModel (const phaseSystem & fluid, const word & phaseName, const label index)
Definition at line 27 of file InertPhaseModel.C.
~InertPhaseModel()
template<class BasePhaseModel > ~InertPhaseModel () virtual
Definition at line 41 of file InertPhaseModel.C.
Member Function Documentation
R()
template<class BasePhaseModel > Foam::tmp< Foam::fvScalarMatrix > R (volScalarField & Yi) const virtual
Definition at line 49 of file InertPhaseModel.C.
References Foam::dimMass, and Foam::dimTime.
Qdot()
template<class BasePhaseModel > Foam::tmp< Foam::volScalarField > Qdot () const virtual
Definition at line 63 of file InertPhaseModel.C.
References Foam::dimEnergy, Foam::dimTime, Foam::dimVolume, IOobject::groupName(), mesh, Foam::name(), and GeometricField< scalar, fvPatchField, volMesh >::New().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/phaseModel/InertPhaseModel/InertPhaseModel.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/phaseModel/InertPhaseModel/InertPhaseModel.C