OpenFOAM: chemistryTabulationMethod< CompType, ThermoType > Class Template Reference
chemistryTabulationMethod< CompType, ThermoType > Class Template Reference abstract
An abstract class for chemistry tabulation.
#include <chemistryTabulationMethod.H>
Public Member Functions
TypeName ("chemistryTabulationMethod")
declareRunTimeSelectionTable (autoPtr, chemistryTabulationMethod, dictionary,(const dictionary &dict, TDACChemistryModel< CompType, ThermoType > &chemistry),(dict, chemistry))
chemistryTabulationMethod (const dictionary &dict, TDACChemistryModel< CompType, ThermoType > &chemistry)
virtual ~chemistryTabulationMethod ()
bool active ()
bool log ()
bool variableTimeStep ()
scalar tolerance () const
virtual label size ()=0
virtual void writePerformance ()=0
virtual bool retrieve (const scalarField &phiQ, scalarField &RphiQ)=0
virtual label add (const scalarField &phiQ, const scalarField &RphiQ, const scalar rho, const scalar deltaT)=0
virtual bool update ()=0
Static Public Member Functions
static autoPtr< chemistryTabulationMethod > New (const IOdictionary &dict, TDACChemistryModel< CompType, ThermoType > &chemistry)
Protected Attributes
const dictionary & dict_
const dictionary coeffsDict_
Switch active_
Switch log_
TDACChemistryModel< CompType, ThermoType > & chemistry_
scalar tolerance_
Detailed Description
template<class CompType, class ThermoType>
class Foam::chemistryTabulationMethod< CompType, ThermoType >
An abstract class for chemistry tabulation.
Source files
chemistryTabulationMethod.H
chemistryTabulationMethod.C
Definition at line 55 of file chemistryTabulationMethod.H.
Constructor & Destructor Documentation
chemistryTabulationMethod()
template<class CompType , class ThermoType > chemistryTabulationMethod (const dictionary & dict, TDACChemistryModel< CompType, ThermoType > & chemistry)
Definition at line 28 of file chemistryTabulationMethod.C.
~chemistryTabulationMethod()
template<class CompType , class ThermoType > ~chemistryTabulationMethod () virtual
Definition at line 46 of file chemistryTabulationMethod.C.
Member Function Documentation
TypeName()
template<class CompType , class ThermoType > TypeName ("chemistryTabulationMethod< CompType, ThermoType >")
declareRunTimeSelectionTable()
template<class CompType , class ThermoType > declareRunTimeSelectionTable (autoPtr , chemistryTabulationMethod< CompType, ThermoType > , dictionary , (const dictionary &dict, TDACChemistryModel< CompType, ThermoType > &chemistry) , (dict, chemistry))
New()
template<class CompType , class ThermoType > Foam::autoPtr< Foam::chemistryTabulationMethod< CompType, ThermoType > > New (const IOdictionary & dict, TDACChemistryModel< CompType, ThermoType > & chemistry) static
DynamicList<word> thisCmpts(6); thisCmpts.append(CompType::typeName); thisCmpts.append (basicThermo::splitThermoName(ThermoType::typeName(), 5));
DynamicList<word> validNames;
if (thisCmpts == SubList<word>(cmpts, 6, 1)) { validNames.append(cmpts[0]); }
Definition at line 29 of file chemistryTabulationMethodNew.C.
References PtrList< T >::append(), dict, UPtrList< T >::empty(), Foam::endl(), Foam::FatalError, FatalErrorInLookup, UPtrList< T >::get(), Foam::Info, Foam::nl, PtrList< T >::PtrList(), UPtrList< T >::size(), and basicThermo::splitThermoName().
Referenced by TDACChemistryModel< ReactionThermo, ThermoType >::TDACChemistryModel().
active()
template<class CompType , class ThermoType > bool active () inline
Definition at line 120 of file chemistryTabulationMethod.H.
References chemistryTabulationMethod< CompType, ThermoType >::active_.
log()
template<class CompType , class ThermoType > bool log () inline
Definition at line 125 of file chemistryTabulationMethod.H.
References chemistryTabulationMethod< CompType, ThermoType >::active_, and chemistryTabulationMethod< CompType, ThermoType >::log_.
Referenced by ISAT< CompType, ThermoType >::ISAT().
variableTimeStep()
template<class CompType , class ThermoType > bool variableTimeStep () inline
Definition at line 130 of file chemistryTabulationMethod.H.
References chemistryTabulationMethod< CompType, ThermoType >::chemistry_, and TDACChemistryModel< ReactionThermo, ThermoType >::variableTimeStep().
Referenced by ISAT< CompType, ThermoType >::ISAT().
tolerance()
template<class CompType , class ThermoType > scalar tolerance () const inline
Definition at line 135 of file chemistryTabulationMethod.H.
References chemistryTabulationMethod< CompType, ThermoType >::tolerance_.
size()
template<class CompType , class ThermoType > virtual label size () pure virtual
Implemented in ISAT< CompType, ThermoType >, and none< CompType, ThermoType >.
writePerformance()
template<class CompType , class ThermoType > virtual void writePerformance () pure virtual
Implemented in ISAT< CompType, ThermoType >, and none< CompType, ThermoType >.
retrieve()
template<class CompType , class ThermoType > virtual bool retrieve (const scalarField & phiQ, scalarField & RphiQ) pure virtual
Implemented in ISAT< CompType, ThermoType >, and none< CompType, ThermoType >.
add()
template<class CompType , class ThermoType > virtual label add (const scalarField & phiQ, const scalarField & RphiQ, const scalar rho, const scalar deltaT) pure virtual
Implemented in ISAT< CompType, ThermoType >, and none< CompType, ThermoType >.
update()
template<class CompType , class ThermoType > virtual bool update () pure virtual
Implemented in ISAT< CompType, ThermoType >, and none< CompType, ThermoType >.
Member Data Documentation
dict_
template<class CompType , class ThermoType > const dictionary& dict_ protected
Definition at line 60 of file chemistryTabulationMethod.H.
coeffsDict_
template<class CompType , class ThermoType > const dictionary coeffsDict_ protected
Definition at line 62 of file chemistryTabulationMethod.H.
Referenced by ISAT< CompType, ThermoType >::ISAT().
active_
template<class CompType , class ThermoType > Switch active_ protected
Definition at line 65 of file chemistryTabulationMethod.H.
Referenced by chemistryTabulationMethod< CompType, ThermoType >::active(), ISAT< CompType, ThermoType >::ISAT(), chemistryTabulationMethod< CompType, ThermoType >::log(), and none< CompType, ThermoType >::none().
log_
template<class CompType , class ThermoType > Switch log_ protected
Definition at line 68 of file chemistryTabulationMethod.H.
Referenced by chemistryTabulationMethod< CompType, ThermoType >::log().
chemistry_
template<class CompType , class ThermoType > TDACChemistryModel<CompType, ThermoType>& chemistry_ protected
Definition at line 70 of file chemistryTabulationMethod.H.
Referenced by ISAT< CompType, ThermoType >::ISAT(), and chemistryTabulationMethod< CompType, ThermoType >::variableTimeStep().
tolerance_
template<class CompType , class ThermoType > scalar tolerance_ protected
Definition at line 72 of file chemistryTabulationMethod.H.
Referenced by chemistryTabulationMethod< CompType, ThermoType >::tolerance().
The documentation for this class was generated from the following files:
src/thermophysicalModels/chemistryModel/chemistryModel/TDACChemistryModel/tabulation/chemistryTabulationMethod/chemistryTabulationMethod.H
src/thermophysicalModels/chemistryModel/chemistryModel/TDACChemistryModel/tabulation/chemistryTabulationMethod/chemistryTabulationMethod.C
src/thermophysicalModels/chemistryModel/chemistryModel/TDACChemistryModel/tabulation/chemistryTabulationMethod/chemistryTabulationMethodNew.C