OpenFOAM: lagrangianWriter Class Reference
lagrangianWriter Class Reference
Write lagrangian (cloud) positions and fields (as PointData) in VTP format. Legacy VTK format is intentionally not supported since the VTP format provides much better field selection in ParaView, and for consistency with the Foam::functionObjects::vtkCloud function object.
#include <foamVtkLagrangianWriter.H>
Public Member Functions
lagrangianWriter (const fvMesh &mesh, const word &cloudName, const vtk::outputOptions opts=vtk::formatType::INLINE_BASE64, bool useVerts=false)
lagrangianWriter (const fvMesh &mesh, const word &cloudName, const fileName &file, bool parallel=Pstream::parRun())
lagrangianWriter (const fvMesh &mesh, const word &cloudName, const vtk::outputOptions opts, const fileName &file, bool parallel=Pstream::parRun())
virtual ~lagrangianWriter ()=default
virtual bool beginFile (std::string title="")
virtual bool writeGeometry ()
bool beginParcelData ()
bool endParcelData ()
template<class Type >
void write (const IOField< Type > &field)
template<class Type >
label writeFields (const wordList &fieldNames, bool verbose=true)
template<class Type >
label writeFields (const IOobjectList &objects, bool verbose=true)
template<class Type >
Foam::label writeFields (const wordList &fieldNames, bool verbose)
template<class Type >
Foam::label writeFields (const IOobjectList &objects, const bool verbose)
Public Member Functions inherited from fileWriter
fileWriter (const vtk::fileTag contentType, const vtk::outputOptions opts)
virtual ~fileWriter ()
vtk::fileTag contentType () const noexcept
vtk::outputOptions opts () const noexcept
word ext () const
bool legacy () const noexcept
bool parallel () const noexcept
const word & state () const
const fileName & output () const noexcept
virtual bool open (const fileName &file, bool parallel=UPstream::parRun())
void close ()
bool beginFieldData (label nFields=0)
bool isCellData () const noexcept
bool isPointData () const noexcept
label nCellData () const noexcept
label nPointData () const noexcept
bool endFieldData ()
bool endCellData ()
bool endPointData ()
void writeTimeValue (scalar timeValue)
Static Public Member Functions
static word ext (vtk::outputOptions)
Protected Member Functions
virtual bool beginCellData (label nFields=0)
virtual bool beginPointData (label nFields=0)
Protected Member Functions inherited from fileWriter
void checkFormatterValidity () const
Ostream & reportBadState (Ostream &, outputState expected) const
Ostream & reportBadState (Ostream &, outputState, outputState) const
std::ofstream & os () noexcept
vtk::formatter & format ()
bool isState (outputState test) const noexcept
bool notState (outputState test) const noexcept
template<class Type >
void beginDataArray (const word &fieldName, const label nValues)
void endDataArray ()
void beginPoints (const label nPoints)
void endPoints ()
bool enter_Piece ()
bool endPiece ()
bool enter_CellData (label nEntries, label nFields)
bool enter_PointData (label nEntries, label nFields)
bool exit_File ()
template<class Type >
void writeUniform (const word &fieldName, const Type &val, const label nValues)
template<class Type >
void writeBasicField (const word &fieldName, const UList< Type > &field)
bool writeProcIDs (const label nValues)
fileWriter (const fileWriter &)=delete
void operator= (const fileWriter &)=delete
Additional Inherited Members
Protected Types inherited from fileWriter
enum outputState : uint8_t {
CLOSED = 0 , OPENED , DECLARED , FIELD_DATA ,
PIECE , CELL_DATA , POINT_DATA
}
Protected Attributes inherited from fileWriter
outputState state_
vtk::fileTag contentType_
bool parallel_
vtk::outputOptions opts_
label nCellData_
label nPointData_
fileName outputFile_
autoPtr< vtk::formatter > format_
std::ofstream os_
Static Protected Attributes inherited from fileWriter
static const Enum< outputState > stateNames
Detailed Description
Write lagrangian (cloud) positions and fields (as PointData) in VTP format. Legacy VTK format is intentionally not supported since the VTP format provides much better field selection in ParaView, and for consistency with the Foam::functionObjects::vtkCloud function object.
The file output states are managed by the Foam::vtk::fileWriter class. FieldData (eg, TimeValue) must appear before any geometry pieces.
Note
If fields should be CellData instead of PointData (default), this must be decided at construction time.
Source files
foamVtkLagrangianWriter.H
lagrangianWriter.C
lagrangianWriterTemplates.C
Definition at line 66 of file foamVtkLagrangianWriter.H.
Constructor & Destructor Documentation
lagrangianWriter() [1/3]
lagrangianWriter (const fvMesh & mesh, const word & cloudName, const vtk::outputOptions opts = vtk::formatType::INLINE_BASE64, bool useVerts = false)
Definition at line 110 of file foamVtkLagrangianWriter.C.
References outputOptions::append(), outputOptions::legacy(), and fileWriter::opts_.
lagrangianWriter() [2/3]
lagrangianWriter (const fvMesh & mesh, const word & cloudName, const fileName & file, bool parallel = Pstream::parRun())
Definition at line 129 of file foamVtkLagrangianWriter.C.
References fileWriter::open(), and fileWriter::parallel().
lagrangianWriter() [3/3]
lagrangianWriter (const fvMesh & mesh, const word & cloudName, const vtk::outputOptions opts, const fileName & file, bool parallel = Pstream::parRun())
Definition at line 143 of file foamVtkLagrangianWriter.C.
References fileWriter::open(), and fileWriter::parallel().
~lagrangianWriter()
virtual ~lagrangianWriter () virtual default
Member Function Documentation
beginCellData()
bool beginCellData (label nFields = 0) protected virtual
Implements fileWriter.
Definition at line 96 of file foamVtkLagrangianWriter.C.
beginPointData()
bool beginPointData (label nFields = 0) protected virtual
Implements fileWriter.
Definition at line 102 of file foamVtkLagrangianWriter.C.
ext()
static word ext (vtk::outputOptions) inline static
Definition at line 174 of file foamVtkLagrangianWriter.H.
References Foam::vtk::fileExtension, and Foam::vtk::POLY_DATA.
beginFile()
bool beginFile (std::string title = "") virtual
Reimplemented from fileWriter.
Definition at line 160 of file foamVtkLagrangianWriter.C.
References fileWriter::beginFile(), and Foam::name().
writeGeometry()
bool writeGeometry () virtual
Implements fileWriter.
Definition at line 182 of file foamVtkLagrangianWriter.C.
References format(), Foam::vtk::NUMBER_OF_POINTS, Foam::vtk::NUMBER_OF_VERTS, Foam::vtk::PIECE, Foam::vtk::POINTS, Foam::reduce(), UPtrList< T >::size(), Foam::vtk::writeList(), and Foam::vtk::writeListParallel().
beginParcelData()
bool beginParcelData ()
Definition at line 271 of file foamVtkLagrangianWriter.C.
References beginCellData(), and beginPointData().
endParcelData()
bool endParcelData ()
Definition at line 284 of file foamVtkLagrangianWriter.C.
write()
template<class Type > void write (const IOField< Type > & field)
Definition at line 28 of file foamVtkLagrangianWriterTemplates.C.
References fileWriter::CELL_DATA, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, field(), fileWriter::isState(), IOstream::name(), fileWriter::nCellData_, Foam::nl, fileWriter::nPointData_, fileWriter::POINT_DATA, and fileWriter::reportBadState().
writeFields() [1/4]
template<class Type > label writeFields (const wordList & fieldNames, bool verbose = true)
writeFields() [2/4]
template<class Type > label writeFields (const IOobjectList & objects, bool verbose = true)
writeFields() [3/4]
template<class Type > Foam::label writeFields (const wordList & fieldNames, bool verbose)
Definition at line 67 of file foamVtkLagrangianWriterTemplates.C.
References Foam::endl(), field(), Foam::Info, io(), IOobjectOption::READ_IF_PRESENT, and Foam::returnReduceOr().
writeFields() [4/4]
template<class Type > Foam::label writeFields (const IOobjectList & objects, const bool verbose)
Definition at line 126 of file foamVtkLagrangianWriterTemplates.C.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/conversion/vtk/foamVtkLagrangianWriter.H
src/lagrangian/intermediate/conversion/vtk/foamVtkLagrangianWriter.C
src/lagrangian/intermediate/conversion/vtk/foamVtkLagrangianWriterTemplates.C