OpenFOAM: meanVelocityForce Class Reference
meanVelocityForce Class Reference
Numerics » Finite volume Options » Sources
Applies the force within a specified region to maintain the specified mean velocity for incompressible flows.
#include <meanVelocityForce.H>
Public Member Functions
TypeName ("meanVelocityForce")
meanVelocityForce (const word &sourceName, const word &modelType, const dictionary &dict, const fvMesh &mesh)
meanVelocityForce (const meanVelocityForce &)=delete
void operator= (const meanVelocityForce &)=delete
virtual ~meanVelocityForce ()=default
virtual void correct (volVectorField &U)
virtual void addSup (fvMatrix< vector > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldi)
virtual void constrain (fvMatrix< vector > &eqn, const label fieldi)
virtual bool read (const dictionary &dict)
Public Member Functions inherited from cellSetOption
TypeName ("cellSetOption")
cellSetOption (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
virtual ~cellSetOption ()=default
scalar timeStart () const noexcept
scalar duration () const noexcept
bool inTimeLimits (const scalar timeValue) const
bool useSubMesh () const noexcept
selectionModeType selectionMode () const noexcept
const wordRes & selectionNames () const noexcept
const wordRe & zoneName () const
scalar V () const noexcept
const labelList & cells () const noexcept
scalar timeStart (scalar val) noexcept
scalar duration (scalar val) noexcept
virtual bool isActive ()
const word & cellSetName () const
Public Member Functions inherited from option
TypeName ("option")
declareRunTimeSelectionTable (autoPtr, option, dictionary,(const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh),(name, modelType, dict, mesh))
option (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
autoPtr< option > clone () const
virtual ~option ()=default
const word & name () const noexcept
const fvMesh & mesh () const noexcept
const dictionary & coeffs () const noexcept
bool active () const noexcept
void setApplied (const label fieldi)
bool active (const bool on) noexcept
virtual label applyToField (const word &fieldName) const
virtual void checkApplied () const
virtual void addSup (fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (fvMatrix< tensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< scalar > &eqn, const label fieldi)
virtual void constrain (fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< tensor > &eqn, const label fieldi)
virtual void correct (volScalarField &field)
virtual void correct (volSphericalTensorField &field)
virtual void correct (volSymmTensorField &field)
virtual void correct (volTensorField &field)
virtual void postProcessSens (scalarField &sensField, const word &fieldName=word::null, const word &designVariablesName=word::null)
virtual void postProcessSens (vectorField &sensField, const word &fieldName=word::null, const word &designVariablesName=word::null)
virtual void postProcessSens (tensorField &sensField, const word &fieldName=word::null, const word &designVariablesName=word::null)
virtual void writeHeader (Ostream &) const
virtual void writeFooter (Ostream &) const
virtual void writeData (Ostream &) const
Protected Member Functions
virtual scalar magUbarAve (const volVectorField &U) const
void writeProps (const scalar gradP) const
void update (fvMatrix< vector > &eqn)
Protected Member Functions inherited from cellSetOption
void setSelection (const dictionary &dict)
void setCellSelection ()
void setVol ()
Protected Member Functions inherited from option
void resetApplied ()
Protected Attributes
vector Ubar_
scalar gradP0_
scalar dGradP_
vector flowDir_
scalar relaxation_
autoPtr< volScalarField > rAPtr_
Protected Attributes inherited from cellSetOption
scalar timeStart_
scalar duration_
selectionModeType selectionMode_
wordRes selectionNames_
List< point > points_
dictionary geometricSelection_
labelList cells_
scalar V_
Protected Attributes inherited from option
const word name_
const word modelType_
const fvMesh & mesh_
dictionary dict_
dictionary coeffs_
wordList fieldNames_
List< bool > applied_
bool active_
Additional Inherited Members
Public Types inherited from cellSetOption
enum selectionModeType {
smAll , smCellSet , smCellZone , smPoints ,
smGeometric , smCellType
}
Static Public Member Functions inherited from option
static autoPtr< option > New (const word &name, const dictionary &dict, const fvMesh &mesh)
Public Attributes inherited from option
bool log
Static Public Attributes inherited from cellSetOption
static const Enum< selectionModeType > selectionModeTypeNames_
Detailed Description
Applies the force within a specified region to maintain the specified mean velocity for incompressible flows.
Sources applied to:
  U         | Velocity                                   [m/s]
Required fields:
  U         | Velocity                                   [m/s]
Usage
Minimal example by using constant/fvOptions:
meanVelocityForce1
{
    // Mandatory entries (unmodifiable)
    type                 meanVelocityForce;
    // Mandatory entries (unmodifiable)
    Ubar             (1 0 0);
    fields           (<fieldName>);
    // Optional entries (unmodifiable)
    relaxation       1.0;
    // Conditional mandatory entries (unmodifiable)
        // when <timePath>/uniform/<name>Properties file exists
        gradient    <vectorField>; // reading from the aforementioned file
    // Mandatory/Optional (inherited) entries
    ...
}
where the entries mean:
Property Description Type Reqd Dflt
type Type name: meanVelocityForce word yes -
Ubar Desired mean velocity vector yes -
fields Name of operand velocity field word yes -
relaxation Relaxation factor scalar no 1
gradient Initial pressure gradient field vectorField cndtnl -
The inherited entries are elaborated in:
fvOption.H
cellSetOption.H
Note
Currently only handles kinematic pressure (incompressible solvers).
Source files
meanVelocityForce.H
meanVelocityForce.C
Definition at line 144 of file meanVelocityForce.H.
Constructor & Destructor Documentation
meanVelocityForce() [1/2]
meanVelocityForce (const word & sourceName, const word & modelType, const dictionary & dict, const fvMesh & mesh)
Definition at line 70 of file meanVelocityForce.C.
References option::coeffs_, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, option::fieldNames_, fv(), meanVelocityForce::gradP0_, Foam::Info, option::mesh_, option::name_, Foam::nl, propsDict(), dictionary::readEntry(), option::resetApplied(), and UList< T >::size().
meanVelocityForce() [2/2]
meanVelocityForce (const meanVelocityForce &) delete
~meanVelocityForce()
virtual ~meanVelocityForce () virtual default
Member Function Documentation
magUbarAve()
Foam::scalar magUbarAve (const volVectorField & U) const protected virtual
Reimplemented in patchMeanVelocityForce.
Definition at line 115 of file meanVelocityForce.C.
References forAll, Foam::reduce(), and U.
writeProps()
void writeProps (const scalar gradP) const protected
Definition at line 42 of file meanVelocityForce.C.
References gradP(), option::mesh_, option::name_, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, and propsDict().
update()
void update (fvMatrix< vector > & eqn) protected
TypeName()
TypeName ("meanVelocityForce")
operator=()
void operator= (const meanVelocityForce &) delete
correct()
void correct (volVectorField & U) virtual
Reimplemented from option.
Definition at line 138 of file meanVelocityForce.C.
References Foam::endl(), forAll, gradP(), Foam::Info, Foam::mag(), rAU, Foam::reduce(), and U.
addSup() [1/2]
void addSup (fvMatrix< vector > & eqn, const label fieldi) virtual
Reimplemented from option.
Definition at line 182 of file meanVelocityForce.C.
References Foam::dimVolume, gradP(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, Su, and Foam::Zero.
addSup() [2/2]
void addSup (const volScalarField & rho, fvMatrix< vector > & eqn, const label fieldi) virtual
Reimplemented from option.
Definition at line 210 of file meanVelocityForce.C.
constrain()
void constrain (fvMatrix< vector > & eqn, const label fieldi) virtual
Reimplemented from option.
Definition at line 221 of file meanVelocityForce.C.
References IOobjectOption::NO_READ, and IOobjectOption::NO_WRITE.
read()
bool read (const dictionary & dict) virtual
Reimplemented from cellSetOption.
Definition at line 255 of file meanVelocityForce.C.
References NotImplemented.
Member Data Documentation
Ubar_
vector Ubar_ protected
Definition at line 153 of file meanVelocityForce.H.
gradP0_
scalar gradP0_ protected
Definition at line 156 of file meanVelocityForce.H.
Referenced by meanVelocityForce::meanVelocityForce().
dGradP_
scalar dGradP_ protected
Definition at line 159 of file meanVelocityForce.H.
flowDir_
vector flowDir_ protected
Definition at line 162 of file meanVelocityForce.H.
relaxation_
scalar relaxation_ protected
Definition at line 165 of file meanVelocityForce.H.
rAPtr_
autoPtr<volScalarField> rAPtr_ protected
Definition at line 168 of file meanVelocityForce.H.
The documentation for this class was generated from the following files:
src/fvOptions/sources/derived/meanVelocityForce/meanVelocityForce.H
src/fvOptions/sources/derived/meanVelocityForce/meanVelocityForce.C