OpenFOAM: treeDataCell Class Reference
treeDataCell Class Reference
Encapsulation of data needed to search in/for cells. Used to find the cell containing a point (e.g. cell-cell mapping).
#include <treeDataCell.H>
Classes
class findIntersectOp
class findNearestOp
Public Member Functions
ClassNameNoDebug ("treeDataCell")
treeDataCell (const bool cacheBb, const polyMesh &mesh, polyMesh::cellDecomposition decompMode)
treeDataCell (const bool cacheBb, const polyMesh &mesh, const labelUList &cellLabels, polyMesh::cellDecomposition decompMode)
treeDataCell (const bool cacheBb, const polyMesh &mesh, labelList &&cellLabels, polyMesh::cellDecomposition decompMode)
treeDataCell (const polyMesh &mesh, polyMesh::cellDecomposition decompMode)
treeDataCell (const polyMesh &mesh, const labelUList &cellLabels, polyMesh::cellDecomposition decompMode)
treeDataCell (const polyMesh &mesh, labelList &&cellLabels, polyMesh::cellDecomposition decompMode)
int nDim () const noexcept
treeBoundBox bounds (const labelUList &indices) const
const polyMesh & mesh () const noexcept
polyMesh::cellDecomposition decompMode () const noexcept
const labelList & cellLabels () const noexcept
bool useSubset () const noexcept
bool empty () const noexcept
label size () const noexcept
label objectIndex (const label index) const
const point & centre (const label index) const
tmp< pointField > centres () const
volumeType getVolumeType (const indexedOctree< treeDataCell > &, const point &) const
bool overlaps (const label index, const treeBoundBox &searchBox) const
bool contains (const label index, const point &sample) const
void findNearest (const labelUList &indices, const point &sample, scalar &nearestDistSqr, label &nearestIndex, point &nearestPoint) const
Static Public Member Functions
static treeBoundBoxList boxes (const primitiveMesh &mesh)
static treeBoundBoxList boxes (const primitiveMesh &mesh, const labelUList &cellIds)
static treeBoundBox bounds (const primitiveMesh &mesh, const labelUList &cellIds)
Detailed Description
Encapsulation of data needed to search in/for cells. Used to find the cell containing a point (e.g. cell-cell mapping).
Source files
treeDataCell.H
treeDataCell.C
Definition at line 53 of file treeDataCell.H.
Constructor & Destructor Documentation
treeDataCell() [1/6]
treeDataCell (const bool cacheBb, const polyMesh & mesh, polyMesh::cellDecomposition decompMode)
Definition at line 158 of file treeDataCell.C.
treeDataCell() [2/6]
treeDataCell (const bool cacheBb, const polyMesh & mesh, const labelUList & cellLabels, polyMesh::cellDecomposition decompMode)
Definition at line 175 of file treeDataCell.C.
treeDataCell() [3/6]
treeDataCell (const bool cacheBb, const polyMesh & mesh, labelList && cellLabels, polyMesh::cellDecomposition decompMode)
Definition at line 193 of file treeDataCell.C.
treeDataCell() [4/6]
treeDataCell (const polyMesh & mesh, polyMesh::cellDecomposition decompMode) inline
Definition at line 172 of file treeDataCell.H.
treeDataCell() [5/6]
treeDataCell (const polyMesh & mesh, const labelUList & cellLabels, polyMesh::cellDecomposition decompMode) inline
Definition at line 182 of file treeDataCell.H.
treeDataCell() [6/6]
treeDataCell (const polyMesh & mesh, labelList && cellLabels, polyMesh::cellDecomposition decompMode) inline
Definition at line 193 of file treeDataCell.H.
Member Function Documentation
ClassNameNoDebug()
ClassNameNoDebug ("treeDataCell")
boxes() [1/2]
Foam::treeBoundBoxList boxes (const primitiveMesh & mesh) static
Definition at line 85 of file treeDataCell.C.
References Foam::boxesImpl(), and treeDataCell::mesh().
boxes() [2/2]
Foam::treeBoundBoxList boxes (const primitiveMesh & mesh, const labelUList & cellIds) static
Definition at line 93 of file treeDataCell.C.
References Foam::boxesImpl(), and mesh.
bounds() [1/2]
Foam::treeBoundBox bounds (const primitiveMesh & mesh, const labelUList & cellIds) static
Definition at line 104 of file treeDataCell.C.
References boundBox::add(), primitiveMesh::cellPoints(), primitiveMesh::cells(), primitiveMesh::hasCellPoints(), mesh, and polyMesh::points().
Referenced by treeDataCell::bounds().
nDim()
int nDim () const inline noexcept
Definition at line 230 of file treeDataCell.H.
bounds() [2/2]
Foam::treeBoundBox bounds (const labelUList & indices) const
Definition at line 214 of file treeDataCell.C.
References boundBox::add(), and treeDataCell::bounds().
mesh()
const polyMesh & mesh () const inline noexcept
Definition at line 239 of file treeDataCell.H.
Referenced by treeDataCell::boxes(), and treeDataCell::findIntersectOp::operator()().
decompMode()
polyMesh::cellDecomposition decompMode () const inline noexcept
Definition at line 242 of file treeDataCell.H.
cellLabels()
const labelList & cellLabels () const inline noexcept
Definition at line 248 of file treeDataCell.H.
useSubset()
bool useSubset () const inline noexcept
Definition at line 251 of file treeDataCell.H.
empty()
bool empty () const inline noexcept
Definition at line 254 of file treeDataCell.H.
References UList< T >::empty(), and primitiveMesh::nCells().
size()
label size () const inline noexcept
Definition at line 260 of file treeDataCell.H.
References primitiveMesh::nCells(), and UList< T >::size().
objectIndex()
label objectIndex (const label index) const inline
Definition at line 266 of file treeDataCell.H.
Referenced by treeDataCell::centre(), and treeDataCell::findIntersectOp::operator()().
centre()
const point & centre (const label index) const inline
const cell& operator[](const label index) const { return mesh_.cells()[objectIndex(index)]; }
Definition at line 276 of file treeDataCell.H.
References primitiveMesh::cellCentres(), and treeDataCell::objectIndex().
Referenced by treeDataCell::findNearest().
centres()
Foam::tmp< Foam::pointField > centres () const
Definition at line 246 of file treeDataCell.C.
References tmp< T >::New().
getVolumeType()
volumeType getVolumeType (const indexedOctree< treeDataCell > & , const point &) const inline
Definition at line 290 of file treeDataCell.H.
References NotImplemented, and volumeType::UNKNOWN.
overlaps()
bool overlaps (const label index, const treeBoundBox & searchBox) const
Definition at line 257 of file treeDataCell.C.
contains()
bool contains (const label index, const point & sample) const
Definition at line 272 of file treeDataCell.C.
findNearest()
void findNearest (const labelUList & indices, const point & sample, scalar & nearestDistSqr, label & nearestIndex, point & nearestPoint) const
Definition at line 302 of file treeDataCell.C.
References treeDataCell::centre().
The documentation for this class was generated from the following files:
src/OpenFOAM/algorithms/indexedOctree/treeDataCell.H
src/OpenFOAM/algorithms/indexedOctree/treeDataCell.C