OpenFOAM: extendedEdgeMeshFormat Class Reference
extendedEdgeMeshFormat Class Reference
Provide a means of reading/writing the single-file OpenFOAM extendedEdgeMesh format.
#include <extendedEdgeMeshFormat.H>
Public Member Functions
extendedEdgeMeshFormat (const fileName &)
virtual ~extendedEdgeMeshFormat ()=default
virtual bool read (const fileName &)
Public Member Functions inherited from extendedEdgeMesh
TypeName ("extendedEdgeMesh")
extendedEdgeMesh ()
extendedEdgeMesh (const extendedEdgeMesh &fem)
extendedEdgeMesh (const fileName &name)
extendedEdgeMesh (const fileName &name, const word &fileType)
extendedEdgeMesh (Istream &is)
extendedEdgeMesh (const pointField &points, const edgeList &edges)
extendedEdgeMesh (pointField &&points, edgeList &&edges)
extendedEdgeMesh (const surfaceFeatures &sFeat, const boolList &surfBaffleRegions)
extendedEdgeMesh (const PrimitivePatch< faceList, pointField > &surf, const labelUList &featureEdges, const labelUList &regionFeatureEdges, const labelUList &featurePoints)
extendedEdgeMesh (const pointField &pts, const edgeList &eds, label concaveStart, label mixedStart, label nonFeatureStart, label internalStart, label flatStart, label openStart, label multipleStart, const vectorField &normals, const List< sideVolumeType > &normalVolumeTypes, const vectorField &edgeDirections, const labelListList &normalDirections, const labelListList &edgeNormals, const labelListList &featurePointNormals, const labelListList &featurePointEdges, const labelList &regionEdges)
declareRunTimeSelectionTable (autoPtr, extendedEdgeMesh, fileExtension,(const fileName &name),(name))
~extendedEdgeMesh ()=default
void nearestFeaturePoint (const point &sample, scalar searchDistSqr, pointIndexHit &info) const
void nearestFeatureEdge (const point &sample, scalar searchDistSqr, pointIndexHit &info) const
void nearestFeatureEdge (const pointField &samples, const scalarField &searchDistSqr, List< pointIndexHit > &info) const
void nearestFeatureEdgeByType (const point &sample, const scalarField &searchDistSqr, List< pointIndexHit > &info) const
void allNearestFeaturePoints (const point &sample, scalar searchRadiusSqr, List< pointIndexHit > &info) const
void allNearestFeatureEdges (const point &sample, const scalar searchRadiusSqr, List< pointIndexHit > &info) const
label convexStart () const
label concaveStart () const
label mixedStart () const
label nonFeatureStart () const
label externalStart () const
label internalStart () const
label flatStart () const
label openStart () const
label multipleStart () const
bool featurePoint (label ptI) const
const vectorField & normals () const
const List< sideVolumeType > & normalVolumeTypes () const
const vectorField & edgeDirections () const
const labelListList & normalDirections () const
vector edgeDirection (label edgeI, label ptI) const
const labelListList & edgeNormals () const
vectorField edgeNormals (const labelList &edgeNormIs) const
vectorField edgeNormals (label edgeI) const
const labelListList & featurePointNormals () const
vectorField featurePointNormals (label ptI) const
const labelListList & featurePointEdges () const
const labelList & regionEdges () const
pointStatus getPointStatus (label ptI) const
edgeStatus getEdgeStatus (label edgeI) const
PackedList< 2 > edgeBaffles (label edgeI) const
const indexedOctree< treeDataPoint > & pointTree () const
const indexedOctree< treeDataEdge > & edgeTree () const
const PtrList< indexedOctree< treeDataEdge > > & edgeTreesByType () const
void transfer (extendedEdgeMesh &mesh)
virtual void clear ()
void add (const extendedEdgeMesh &fem)
void flipNormals ()
void autoMap (const pointField &subPoints, const edgeList &subEdges, const labelList &pointMap, const labelList &edgeMap)
void trim (const searchableSurface &surf, const volumeType volType, labelList &pointMap, labelList &edgeMap)
void setFromStatus (const List< extendedEdgeMesh::pointStatus > &pointStat, const List< extendedEdgeMesh::edgeStatus > &edgeStat, labelList &sortedToOriginalPoint, labelList &sortedToOriginalEdge)
bool mergePointsAndSort (const scalar mergeDist, labelList &pointMap, labelList &edgeMap)
bool read (const fileName &name, const word &ext)
void writeObj (const fileName &prefix) const
virtual void writeStats (Ostream &os) const
Public Member Functions inherited from edgeMesh
edgeMesh (const faMesh &mesh)
label size () const
const edgeVectorField & C () const
TypeName ("edgeMesh")
edgeMesh ()
edgeMesh (const edgeMesh &em)
edgeMesh (edgeMesh &&em)
edgeMesh (const pointField &points, const edgeList &edges)
edgeMesh (pointField &&pointLst, edgeList &&edgeLst)
edgeMesh (const fileName &name)
edgeMesh (const fileName &name, const word &fileType)
declareRunTimeSelectionTable (autoPtr, edgeMesh, fileExtension,(const fileName &name),(name))
virtual ~edgeMesh ()=default
declareMemberFunctionSelectionTable (void, edgeMesh, write, fileExtension,(const fileName &name, const edgeMesh &mesh, IOstreamOption streamOpt, const dictionary &options),(name, mesh, streamOpt, options))
void transfer (edgeMesh &mesh)
bool read (const fileName &name, const word &fileType)
const pointField & points () const noexcept
const edgeList & edges () const noexcept
const labelListList & pointEdges () const
label regions (labelList &edgeRegion) const
virtual void scalePoints (const scalar scaleFactor)
virtual void mergePoints (const scalar mergeDist)
virtual void mergeEdges ()
virtual void write (const fileName &name, IOstreamOption streamOpt=IOstreamOption(), const dictionary &options=dictionary::null) const
virtual void write (const fileName &name, const word &fileType, IOstreamOption streamOpt=IOstreamOption(), const dictionary &options=dictionary::null) const
void operator= (const edgeMesh &rhs)
void operator= (edgeMesh &&rhs)
Public Member Functions inherited from GeoMesh< faMesh >
GeoMesh (const faMesh &mesh)
bool hasDb () const
const objectRegistry & thisDb () const
const faMesh & operator() () const
Public Member Functions inherited from edgeMeshFormatsCore
edgeMeshFormatsCore ()=default
virtual ~edgeMeshFormatsCore ()=default
Additional Inherited Members
Public Types inherited from extendedEdgeMesh
enum pointStatus { CONVEX , CONCAVE , MIXED , NONFEATURE }
enum edgeStatus {
EXTERNAL , INTERNAL , FLAT , OPEN ,
MULTIPLE , NONE
}
enum sideVolumeType { INSIDE = 0 , OUTSIDE = 1 , BOTH = 2 , NEITHER = 3 }
Public Types inherited from GeoMesh< faMesh >
typedef faMesh Mesh
typedef MESH::BoundaryMesh BoundaryMesh
Static Public Member Functions inherited from extendedEdgeMesh
static wordHashSet readTypes ()
static wordHashSet writeTypes ()
static bool canReadType (const word &fileType, bool verbose=false)
static bool canWriteType (const word &fileType, bool verbose=false)
static bool canRead (const fileName &name, bool verbose=false)
static autoPtr< extendedEdgeMesh > New (const fileName &name, const word &fileType)
static autoPtr< extendedEdgeMesh > New (const fileName &name)
static edgeStatus classifyEdge (const List< vector > &norms, const labelList &edNorms, const vector &fC0tofC1)
static void sortedOrder (const List< extendedEdgeMesh::pointStatus > &pointStat, const List< extendedEdgeMesh::edgeStatus > &edgeStat, labelList &sortedToOriginalPoint, labelList &sortedToOriginalEdge, label &pointConcaveStart, label &pointMixedStart, label &pointNonFeatStart, label &edgeInternalStart, label &edgeFlatStart, label &edgeOpenStart, label &edgeMultipleStart)
Static Public Member Functions inherited from edgeMesh
static label size (const Mesh &mesh)
static wordHashSet readTypes ()
static wordHashSet writeTypes ()
static bool canReadType (const word &fileType, bool verbose=false)
static bool canWriteType (const word &fileType, bool verbose=false)
static bool canRead (const fileName &name, bool verbose=false)
static autoPtr< edgeMesh > New (const fileName &name, const word &fileType)
static autoPtr< edgeMesh > New (const fileName &name)
static void write (const fileName &name, const edgeMesh &mesh, IOstreamOption streamOpt=IOstreamOption(), const dictionary &options=dictionary::null)
static void write (const fileName &name, const word &fileType, const edgeMesh &mesh, IOstreamOption streamOpt=IOstreamOption(), const dictionary &options=dictionary::null)
Static Public Member Functions inherited from edgeMeshFormatsCore
static bool checkSupport (const wordHashSet &available, const word &fileType, const bool verbose=false, const char *functionName=nullptr)
Static Public Attributes inherited from extendedEdgeMesh
static const Enum< pointStatus > pointStatusNames_
static const Enum< edgeStatus > edgeStatusNames_
static const Enum< sideVolumeType > sideVolumeTypeNames_
static scalar cosNormalAngleTol_
static constexpr label nPointTypes = 4
static constexpr label nEdgeTypes = 5
Static Public Attributes inherited from edgeMeshFormatsCore
static word nativeExt
Protected Member Functions inherited from extendedEdgeMesh
extendedEdgeMesh (std::nullptr_t)
pointStatus classifyFeaturePoint (label ptI) const
void cut (const searchableSurface &, labelList &pMap, labelList &eMap, labelList &pointsFromEdge, labelList &oldEdge, labelList &surfTri)
void select (const searchableSurface &surf, const volumeType volType, labelList &pMap, labelList &eMap)
template<class Patch >
void sortPointsAndEdges (const Patch &, const labelUList &featureEdges, const labelUList &regionFeatureEdges, const labelUList &feaurePoints)
Protected Member Functions inherited from edgeMesh
pointField & storedPoints () noexcept
edgeList & storedEdges () noexcept
Static Protected Member Functions inherited from edgeMeshFormatsCore
static string getLineNoComment (ISstream &is, const char comment='#')
Protected Attributes inherited from extendedEdgeMesh
label concaveStart_
label mixedStart_
label nonFeatureStart_
label internalStart_
label flatStart_
label openStart_
label multipleStart_
vectorField normals_
List< sideVolumeType > normalVolumeTypes_
vectorField edgeDirections_
labelListList normalDirections_
labelListList edgeNormals_
labelListList featurePointNormals_
labelListList featurePointEdges_
labelList regionEdges_
std::unique_ptr< indexedOctree< treeDataPoint > > pointTree_
std::unique_ptr< indexedOctree< treeDataEdge > > edgeTree_
PtrList< indexedOctree< treeDataEdge > > edgeTreesByType_
Protected Attributes inherited from GeoMesh< faMesh >
const faMesh & mesh_
Static Protected Attributes inherited from extendedEdgeMesh
static label convexStart_ = 0
static label externalStart_ = 0
Detailed Description
Provide a means of reading/writing the single-file OpenFOAM extendedEdgeMesh format.
Source files
extendedEdgeMeshFormat.H
extendedEdgeMeshFormat.C
Definition at line 50 of file extendedEdgeMeshFormat.H.
Constructor & Destructor Documentation
extendedEdgeMeshFormat()
extendedEdgeMeshFormat (const fileName & filename)
Definition at line 29 of file extendedEdgeMeshFormat.C.
References extendedEdgeMeshFormat::read().
~extendedEdgeMeshFormat()
virtual ~extendedEdgeMeshFormat () virtual default
Member Function Documentation
read()
bool read (const fileName & filename) virtual
Reimplemented from extendedEdgeMesh.
Definition at line 40 of file extendedEdgeMeshFormat.C.
References clear(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, io(), Time::New(), IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, and IOobjectOption::NO_WRITE.
Referenced by extendedEdgeMeshFormat::extendedEdgeMeshFormat().
The documentation for this class was generated from the following files:
src/meshTools/edgeMesh/extendedEdgeMesh/extendedEdgeMeshFormat.H
src/meshTools/edgeMesh/extendedEdgeMesh/extendedEdgeMeshFormat.C