OpenFOAM: mapDistribute::transformPosition Class Reference
mapDistribute::transformPosition Class Reference
#include <mapDistribute.H>
Public Member Functions
void operator() (const vectorTensorTransform &vt, const bool forward, List< point > &fld) const
void operator() (const vectorTensorTransform &vt, const bool forward, List< List< point > > &flds) const
void operator() (const coupledPolyPatch &cpp, pointField &fld) const
template<template< class > class Container>
void operator() (const coupledPolyPatch &cpp, Container< point > &map) const
Detailed Description
Definition at line 255 of file mapDistribute.H.
Member Function Documentation
operator()() [1/4]
void operator() (const vectorTensorTransform & vt, const bool forward, List< point > & fld) const inline
Definition at line 259 of file mapDistribute.H.
References fld().
Referenced by mapDistribute::transformPosition::operator()().
operator()() [2/4]
void operator() (const vectorTensorTransform & vt, const bool forward, List< List< point > > & flds) const inline
Definition at line 277 of file mapDistribute.H.
References fld(), and mapDistribute::transformPosition::operator()().
operator()() [3/4]
void operator() (const coupledPolyPatch & cpp, pointField & fld) const inline
Definition at line 291 of file mapDistribute.H.
References fld().
operator()() [4/4]
template<template< class > class Container> void operator() (const coupledPolyPatch & cpp, Container< point > & map) const inline
Definition at line 297 of file mapDistribute.H.
References fld(), forAllConstIters, forAllIters, and UPtrList< T >::size().
The documentation for this class was generated from the following file:
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/mapDistribute/mapDistribute.H