OpenFOAM: enginePiston Class Reference
enginePiston Class Reference
Foam::enginePiston.
#include <enginePiston.H>
Public Member Functions
enginePiston (const polyMesh &mesh, const word &pistonPatchName, const autoPtr< coordinateSystem > &pistonCS, const scalar minLayer, const scalar maxLayer)
enginePiston (const polyMesh &mesh, const dictionary &dict)
~enginePiston ()=default
const coordinateSystem & cs () const
const polyPatchID & patchID () const
scalar minLayer () const
scalar maxLayer () const
void writeDict (Ostream &) const
Detailed Description
Foam::enginePiston.
Source files
enginePiston.H
enginePiston.C
Definition at line 51 of file enginePiston.H.
Constructor & Destructor Documentation
enginePiston() [1/2]
enginePiston (const polyMesh & mesh, const word & pistonPatchName, const autoPtr< coordinateSystem > & pistonCS, const scalar minLayer, const scalar maxLayer)
Definition at line 28 of file enginePiston.C.
References Foam::refCast().
enginePiston() [2/2]
enginePiston (const polyMesh & mesh, const dictionary & dict)
Definition at line 46 of file enginePiston.C.
~enginePiston()
~enginePiston () default
Member Function Documentation
cs()
const coordinateSystem & cs () const inline
Definition at line 119 of file enginePiston.H.
patchID()
const polyPatchID & patchID () const inline
Definition at line 125 of file enginePiston.H.
minLayer()
scalar minLayer () const inline
Definition at line 132 of file enginePiston.H.
maxLayer()
scalar maxLayer () const inline
Definition at line 137 of file enginePiston.H.
writeDict()
void writeDict (Ostream & os) const
Definition at line 66 of file enginePiston.C.
References token::BEGIN_BLOCK, token::END_BLOCK, token::END_STATEMENT, Foam::endl(), Foam::nl, and os().
The documentation for this class was generated from the following files:
src/engine/enginePiston/enginePiston.H
src/engine/enginePiston/enginePiston.C