OpenFOAM: faceZoneSet Class Reference
faceZoneSet Class Reference
Like faceSet but -reads data from faceZone -updates faceZone when writing.
#include <faceZoneSet.H>
Public Member Functions
TypeName ("faceZoneSet")
faceZoneSet (const polyMesh &mesh, const word &name, IOobjectOption::readOption rOpt=IOobjectOption::MUST_READ, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE)
faceZoneSet (const polyMesh &mesh, const word &name, const label size, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE)
faceZoneSet (const polyMesh &mesh, const word &name, const topoSet &set, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE)
virtual ~faceZoneSet ()=default
const labelList & addressing () const noexcept
labelList & addressing () noexcept
const boolList & flipMap () const noexcept
boolList & flipMap () noexcept
void updateSet ()
virtual void invert (const label maxLen)
virtual void subset (const topoSet &set)
virtual void addSet (const topoSet &set)
virtual void subtractSet (const topoSet &set)
virtual void sync (const polyMesh &mesh)
virtual void writeDebug (Ostream &os, const primitiveMesh &, const label maxLen) const
virtual bool writeObject (IOstreamOption streamOpt, const bool writeOnProc) const
virtual void updateMesh (const mapPolyMesh &morphMap)
virtual label maxSize (const polyMesh &mesh) const
Public Member Functions inherited from faceSet
TypeName ("faceSet")
faceSet (const IOobject &io)
faceSet (const polyMesh &mesh, const word &name, IOobjectOption::readOption rOpt=IOobjectOption::MUST_READ, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE)
faceSet (const polyMesh &mesh, const word &name, const label size, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE)
faceSet (const polyMesh &mesh, const word &name, const topoSet &set, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE)
faceSet (const polyMesh &mesh, const word &name, const labelHashSet &labels, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE)
faceSet (const polyMesh &mesh, const word &name, labelHashSet &&labels, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE)
faceSet (const polyMesh &mesh, const word &name, const labelUList &labels, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE)
virtual ~faceSet ()=default
virtual void distribute (const mapDistributePolyMesh &map)
Public Member Functions inherited from topoSet
TypeName ("topoSet")
declareRunTimeSelectionTable (autoPtr, topoSet, word,(const polyMesh &mesh, const word &name, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt),(mesh, name, rOpt, wOpt))
declareRunTimeSelectionTable (autoPtr, topoSet, size,(const polyMesh &mesh, const word &name, const label size, IOobjectOption::writeOption wOpt),(mesh, name, size, wOpt))
declareRunTimeSelectionTable (autoPtr, topoSet, set,(const polyMesh &mesh, const word &name, const topoSet &set, IOobjectOption::writeOption wOpt),(mesh, name, set, wOpt))
topoSet (const IOobject &io, const word &wantedType)
topoSet (const polyMesh &mesh, const word &wantedType, const word &name, IOobjectOption::readOption rOpt=IOobjectOption::MUST_READ, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE)
topoSet (const polyMesh &mesh, const word &name, const label size, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE)
topoSet (const polyMesh &mesh, const word &name, const labelHashSet &labels, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE)
topoSet (const polyMesh &mesh, const word &name, labelHashSet &&labels, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE)
topoSet (const polyMesh &mesh, const word &name, const labelUList &labels, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE)
topoSet (const IOobject &io, const label size)
topoSet (const IOobject &io, const labelHashSet &labels)
topoSet (const IOobject &io, labelHashSet &&labels)
autoPtr< topoSet > clone () const
virtual ~topoSet ()=default
virtual bool found (const label id) const
virtual bool set (const label id)
virtual bool unset (const label id)
virtual void set (const labelUList &labels)
virtual void unset (const labelUList &labels)
virtual void writeDebug (Ostream &os, const label maxLen) const
virtual bool writeData (Ostream &) const
void operator= (const topoSet &)
virtual void deleteSet (const topoSet &set)
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
regIOobject (const IOobject &io, const bool isTimeObject=false)
regIOobject (const regIOobject &rio)
regIOobject (const regIOobject &rio, bool registerCopy)
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
regIOobject (const IOobject &io, const regIOobject &rio)
virtual ~regIOobject ()
bool checkIn ()
bool checkOut ()
virtual void addWatch ()
bool registered () const noexcept
bool ownedByRegistry () const noexcept
bool store ()
void release (const bool unregister=false) noexcept
label eventNo () const noexcept
label & eventNo () noexcept
bool upToDate (const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
void setUpToDate ()
virtual void rename (const word &newName)
const dictionary * findMetaData () const noexcept
dictionary & getMetaData () noexcept
void removeMetaData ()
virtual void updateMetaData ()
virtual fileName filePath () const
bool headerOk ()
Istream & readStream (const word &, const bool readOnProc=true)
void close ()
virtual bool readData (Istream &)
virtual bool read ()
virtual label addWatch (const fileName &)
const labelList & watchIndices () const noexcept
labelList & watchIndices () noexcept
virtual bool modified () const
virtual bool readIfModified ()
virtual bool write (const bool writeOnProc=true) const
virtual bool global () const
void operator= (const IOobject &io)
virtual bool writeObject (IOstreamOption::streamFormat fmt, IOstreamOption::versionNumber ver, IOstreamOption::compressionType cmp, const bool writeOnProc) const
Public Member Functions inherited from IOobject
TypeName ("IOobject")
IOobject (const IOobject &)=default
virtual ~IOobject ()=default
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const fileName &path, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const fileName &path, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const IOobject &io, const objectRegistry &registry)
IOobject (const IOobject &io, const word &name)
IOobject (const IOobject &io, const word &name, const fileName &local)
IOobject (const IOobject &io, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt)
IOobject (const IOobject &io, IOobjectOption::registerOption regOpt)
autoPtr< IOobject > clone () const
autoPtr< IOobject > clone (const objectRegistry &registry) const
const objectRegistry & db () const noexcept
const Time & time () const noexcept
const word & name () const noexcept
const word & headerClassName () const noexcept
word & headerClassName () noexcept
const string & note () const noexcept
string & note () noexcept
unsigned labelByteSize () const noexcept
unsigned scalarByteSize () const noexcept
void resetHeader (const word &newName=word::null)
bool hasHeaderClass () const noexcept
template<class Type >
bool isHeaderClass () const
template<class Type >
bool isHeaderClassName () const
word group () const
word member () const
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const noexcept
fileName & instance () noexcept
const fileName & local () const noexcept
fileName path () const
fileName path (const word &instance, const fileName &local=fileName::null) const
fileName objectPath () const
fileName objectRelPath () const
fileName localFilePath (const word &typeName, const bool search=true) const
fileName globalFilePath (const word &typeName, const bool search=true) const
IOstreamOption parseHeader (const dictionary &headerDict)
bool readHeader (Istream &is)
bool readHeader (dictionary &headerDict, Istream &is)
template<class Type >
bool typeHeaderOk (const bool checkType=true, const bool search=true, const bool verbose=true)
template<class Type >
void warnNoRereading () const
bool writeHeader (Ostream &os) const
bool writeHeader (Ostream &os, const word &objectType) const
void writeHeader (dictionary &dict, IOstreamOption streamOpt) const
void writeHeader (dictionary &dict, const word &objectType, IOstreamOption streamOpt) const
bool good () const noexcept
bool bad () const noexcept
InfoProxy< IOobject > info () const noexcept
void operator= (const IOobject &io)
template<>
bool isHeaderClass () const
template<class StringType >
Foam::word groupName (StringType base, const word &group)
Public Member Functions inherited from IOobjectOption
constexpr IOobjectOption (readOption rOpt=readOption::NO_READ, writeOption wOpt=writeOption::NO_WRITE, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (readOption rOpt, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (writeOption wOpt, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (registerOption registerObject, bool globalObject=false) noexcept
constexpr IOobjectOption (readOption rOpt, writeOption wOpt, bool registerObject, bool globalObject=false) noexcept
constexpr IOobjectOption (bool registerObject, bool globalObject=false) noexcept
readOption readOpt () const noexcept
readOption readOpt (readOption opt) noexcept
writeOption writeOpt () const noexcept
writeOption writeOpt (writeOption opt) noexcept
bool registerObject () const noexcept
bool registerObject (bool on) noexcept
bool globalObject () const noexcept
bool globalObject (bool on) noexcept
bool isAnyRead () const noexcept
bool isReadRequired () const noexcept
bool isReadOptional () const noexcept
readOption & readOpt () noexcept
writeOption & writeOpt () noexcept
bool & registerObject () noexcept
bool & globalObject () noexcept
Public Member Functions inherited from HashSet< label, Hash< label > >
Foam::label assignMany (const label nItems, InputIter first, InputIter last)
HashSet ()
HashSet (const this_type &rhs)
HashSet (this_type &&rhs)
HashSet (const label size)
HashSet (Istream &is)
HashSet (const FixedList< label, N > &list)
HashSet (const UList< label > &list)
HashSet (const IndirectListBase< label, Addr > &list)
HashSet (std::initializer_list< label > list)
HashSet (const HashTable< AnyType, label, AnyHash > &tbl)
bool test (const label &key) const
bool insert (const label &key)
label insert (InputIter first, InputIter last)
label insert (std::initializer_list< label > list)
label insert (const FixedList< label, N > &list)
label insert (const UList< label > &list)
label insert (const IndirectListBase< label, Addr > &list)
Foam::label insert (InputIter first, InputIter last)
Foam::label insert (const FixedList< label, N > &list)
Foam::label insert (const IndirectListBase< label, Addr > &list)
bool set (const label &key)
label set (InputIter first, InputIter last)
label set (std::initializer_list< label > list)
label set (const FixedList< label, N > &list)
label set (const UList< label > &list)
label set (const IndirectListBase< label, Addr > &list)
bool unset (const label &key)
label unset (InputIter first, InputIter last)
label unset (std::initializer_list< label > list)
label unset (const FixedList< label, N > &list)
label unset (const UList< label > &list)
label unset (const IndirectListBase< label, Addr > &list)
Foam::label unset (InputIter first, InputIter last)
Foam::label unset (const FixedList< label, N > &list)
Foam::label unset (const IndirectListBase< label, Addr > &list)
void merge (HashSet< label, Hash< label > > &source)
void merge (HashSet< label, Hash< label > > &&source)
label setMany (InputIter first, InputIter last)
iterator begin ()
const_iterator begin () const
const_iterator cbegin () const
iterator end () noexcept
const_iterator end () const noexcept
constexpr const_iterator cend () const noexcept
Ostream & writeList (Ostream &os, const label shortLen=0) const
bool operator() (const label &key) const noexcept
bool operator[] (const label &key) const noexcept
void operator= (const this_type &rhs)
void operator= (this_type &&rhs)
void operator= (const UList< label > &rhs)
void operator= (const FixedList< label, N > &rhs)
void operator= (std::initializer_list< label > rhs)
bool operator== (const this_type &rhs) const
bool operator!= (const this_type &rhs) const
this_type & operator|= (const this_type &rhs)
this_type & operator&= (const this_type &rhs)
this_type & operator^= (const this_type &rhs)
this_type & operator+= (const this_type &rhs)
this_type & operator-= (const this_type &rhs)
List< label > tocValues (const UnaryPredicate &, const bool)=delete
List< label > tocEntries (const BinaryPredicate &, const bool)=delete
label countValues (const UnaryPredicate &, const bool)=delete
label countEntries (const BinaryPredicate &, const bool)=delete
label filterValues (const UnaryPredicate &, const bool)=delete
label filterEntries (const BinaryPredicate &, const bool)=delete
Public Member Functions inherited from HashTable< T, Key, Hash >
HashTable ()
HashTable (const label size)
HashTable (Istream &is, const label size=128)
HashTable (const this_type &ht)
HashTable (this_type &&rhs)
HashTable (std::initializer_list< std::pair< Key, T > > list)
~HashTable ()
bool empty () const noexcept
label size () const noexcept
label capacity () const noexcept
T & at (const Key &key)
const T & at (const Key &key) const
bool contains (const Key &key) const
iterator find (const Key &key)
const_iterator find (const Key &key) const
const_iterator cfind (const Key &key) const
const T & lookup (const Key &key, const T &deflt) const
List< Key > toc () const
List< Key > sortedToc () const
template<class Compare >
List< Key > sortedToc (const Compare &comp) const
template<class UnaryPredicate >
List< Key > tocKeys (const UnaryPredicate &pred, const bool invert=false) const
template<class UnaryPredicate >
List< Key > tocValues (const UnaryPredicate &pred, const bool invert=false) const
template<class BinaryPredicate >
List< Key > tocEntries (const BinaryPredicate &pred, const bool invert=false) const
UPtrList< const node_type > csorted () const
UPtrList< const node_type > sorted () const
UPtrList< node_type > sorted ()
template<class UnaryPredicate >
label countKeys (const UnaryPredicate &pred, const bool invert=false) const
template<class UnaryPredicate >
label countValues (const UnaryPredicate &pred, const bool invert=false) const
template<class BinaryPredicate >
label countEntries (const BinaryPredicate &pred, const bool invert=false) const
template<class... Args>
bool emplace (const Key &key, Args &&... args)
template<class... Args>
bool emplace_set (const Key &key, Args &&... args)
bool insert (const Key &key, const T &obj)
bool insert (const Key &key, T &&obj)
bool set (const Key &key, const T &obj)
bool set (const Key &key, T &&obj)
bool erase (const iterator &iter)
bool erase (const Key &key)
template<class AnyType , class AnyHash >
label erase (const HashTable< AnyType, Key, AnyHash > &other)
label erase (std::initializer_list< Key > keys)
template<class InputIter >
label erase (InputIter first, InputIter last)
template<unsigned N>
label erase (const FixedList< Key, N > &keys)
label erase (const UList< Key > &keys)
template<class AnyType , class AnyHash >
label retain (const HashTable< AnyType, Key, AnyHash > &other)
template<class UnaryPredicate >
label filterKeys (const UnaryPredicate &pred, const bool pruning=false)
template<class UnaryPredicate >
label filterValues (const UnaryPredicate &pred, const bool pruning=false)
template<class BinaryPredicate >
label filterEntries (const BinaryPredicate &pred, const bool pruning=false)
void resize (const label sz)
void clear ()
void clearStorage ()
void swap (HashTable< T, Key, Hash > &rhs)
void transfer (HashTable< T, Key, Hash > &rhs)
void merge (HashTable< T, Key, Hash > &source)
void merge (HashTable< T, Key, Hash > &&source)
T & operator[] (const Key &key)
const T & operator[] (const Key &key) const
T & operator() (const Key &key)
T & operator() (const Key &key, const T &deflt)
void operator= (const this_type &rhs)
void operator= (std::initializer_list< std::pair< Key, T > > rhs)
void operator= (this_type &&rhs)
bool operator== (const this_type &rhs) const
bool operator!= (const this_type &rhs) const
this_type & operator+= (const this_type &rhs)
const_iterator_pair< const_key_iterator, this_type > keys () const
iterator begin ()
const_iterator begin () const
const_iterator cbegin () const
iterator end () noexcept
const_iterator end () const noexcept
constexpr const_iterator cend () const noexcept
Ostream & printInfo (Ostream &os) const
Ostream & writeKeys (Ostream &os, const label shortLen=0) const
bool found (const Key &key) const
template<class Compare >
Foam::List< Key > sortedToc (const Compare &comp) const
template<class UnaryPredicate >
Foam::List< Key > tocKeys (const UnaryPredicate &pred, const bool invert) const
template<class UnaryPredicate >
Foam::List< Key > tocValues (const UnaryPredicate &pred, const bool invert) const
template<class BinaryPredicate >
Foam::List< Key > tocEntries (const BinaryPredicate &pred, const bool invert) const
template<class UnaryPredicate >
Foam::label countKeys (const UnaryPredicate &pred, const bool invert) const
template<class UnaryPredicate >
Foam::label countValues (const UnaryPredicate &pred, const bool invert) const
template<class BinaryPredicate >
Foam::label countEntries (const BinaryPredicate &pred, const bool invert) const
template<class InputIter >
Foam::label erase (InputIter first, InputIter last)
template<unsigned N>
Foam::label erase (const FixedList< Key, N > &keys)
template<class AnyType , class AnyHash >
Foam::label erase (const HashTable< AnyType, Key, AnyHash > &other)
template<class AnyType , class AnyHash >
Foam::label retain (const HashTable< AnyType, Key, AnyHash > &other)
template<class UnaryPredicate >
Foam::label filterKeys (const UnaryPredicate &pred, const bool pruning)
template<class UnaryPredicate >
Foam::label filterValues (const UnaryPredicate &pred, const bool pruning)
template<class BinaryPredicate >
Foam::label filterEntries (const BinaryPredicate &pred, const bool pruning)
Public Member Functions inherited from HashTableCore
ClassName ("HashTable")
HashTableCore () noexcept=default
Additional Inherited Members
Public Types inherited from IOobject
enum objectState : char { GOOD , BAD }
enum fileCheckTypes : char { timeStamp , timeStampMaster , inotify , inotifyMaster }
Public Types inherited from IOobjectOption
enum readOption : unsigned char {
NO_READ = 0 , MUST_READ = 0x1 , READ_MODIFIED = 0x3 , MUST_READ_IF_MODIFIED = 0x3 ,
LAZY_READ = 0x4 , READ_IF_PRESENT = 0x4
}
enum writeOption : unsigned char { NO_WRITE = 0 , AUTO_WRITE = 0x10 }
enum registerOption : unsigned char { NO_REGISTER = 0 , REGISTER = 1 }
Public Types inherited from HashSet< label, Hash< label > >
typedef HashSet< label, Hash< label > > this_type
typedef HashTable< Foam::zero, label, Hash< label > > parent_type
using iterator = typename parent_type::key_iterator
using const_iterator = typename parent_type::const_key_iterator
Public Types inherited from HashTable< T, Key, Hash >
typedef HashTable< T, Key, Hash > this_type
typedef std::conditional< std::is_same< Foam::zero, typenamestd::remove_cv< T >::type >::value, Detail::HashTableSingle< Key >, Detail::HashTablePair< Key, T > >::type node_type
typedef Key key_type
typedef T mapped_type
typedef T value_type
typedef Hash hasher
typedef T * pointer
typedef T & reference
typedef const T * const_pointer
typedef const T & const_reference
typedef label difference_type
typedef label size_type
using key_iterator = key_iterator_base< iterator >
using const_key_iterator = key_iterator_base< const_iterator >
Static Public Member Functions inherited from topoSet
static fileName localPath (const polyMesh &mesh, const word &name)
static IOobject findIOobject (const polyMesh &mesh, const word &name, IOobjectOption::readOption rOpt=IOobjectOption::MUST_READ, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE)
static IOobject findIOobject (const Time &runTime, const word &name, IOobjectOption::readOption rOpt=IOobjectOption::MUST_READ, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE)
static autoPtr< topoSet > New (const word &setType, const polyMesh &mesh, const word &name, IOobjectOption::readOption rOpt=IOobjectOption::MUST_READ, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE)
static autoPtr< topoSet > New (const word &setType, const polyMesh &mesh, const word &name, const label size, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE)
static autoPtr< topoSet > New (const word &setType, const polyMesh &mesh, const word &name, const topoSet &set, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE)
template<class Container >
static void updateMesh (const fileName &instance, const mapPolyMesh &, Container &)
template<class Container >
static void setInstance (const fileName &instance, Container &)
static void removeFiles (const polyMesh &)
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *p)
template<class Type >
static Type & store (autoPtr< Type > &ptr)
template<class Type >
static Type & store (autoPtr< Type > &&ptr)
template<class Type >
static Type & store (refPtr< Type > &ptr)
template<class Type >
static Type & store (refPtr< Type > &&ptr)
template<class Type >
static Type & store (tmp< Type > &ptr)
template<class Type >
static Type & store (tmp< Type > &&ptr)
Static Public Member Functions inherited from IOobject
static bool bannerEnabled () noexcept
static bool bannerEnabled (bool on) noexcept
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
template<class StringType >
static word groupName (StringType base, const word &group)
static word group (const word &name)
static word member (const word &name)
static word scopedName (const std::string &scope, const word &name)
static IOobject selectIO (const IOobject &io, const fileName &altFile, const word &ioName="")
static Ostream & writeBanner (Ostream &os, const bool noSyntaxHint=false)
static Ostream & writeDivider (Ostream &os)
static Ostream & writeEndDivider (Ostream &os)
Static Public Member Functions inherited from IOobjectOption
static bool isAnyRead (readOption opt) noexcept
static bool isReadRequired (readOption opt) noexcept
static bool isReadOptional (readOption opt) noexcept
static readOption lazierRead (readOption opt) noexcept
Static Public Member Functions inherited from HashTableCore
static label canonicalSize (const label requested_size)
Static Public Attributes inherited from topoSet
static int disallowGenericSets
Static Public Attributes inherited from IOobject
static const Enum< fileCheckTypes > fileCheckTypesNames
static char scopeSeparator
static fileCheckTypes fileModificationChecking
static float fileModificationSkew
static int maxFileModificationPolls
Static Public Attributes inherited from HashTableCore
static const label maxTableSize
Protected Member Functions inherited from topoSet
virtual void updateLabels (const labelUList &map)
virtual void check (const label maxSize)
void writeDebug (Ostream &os, const label maxElem, topoSet::const_iterator &iter, label &elemI) const
void writeDebug (Ostream &os, const pointField &coords, const label maxElem, topoSet::const_iterator &iter, label &elemI) const
void writeDebug (Ostream &os, const pointField &coords, const label maxLen) const
topoSet (const topoSet &)=delete
Protected Member Functions inherited from regIOobject
bool readHeaderOk (const IOstreamOption::streamFormat fmt, const word &typeName)
Protected Member Functions inherited from IOobject
void setBad (const string &s)
Static Protected Member Functions inherited from IOobject
static void writeHeaderContent (Ostream &os, const IOobject &io, const word &objectType, const dictionary *metaDataDict=nullptr)
static void writeHeaderContent (dictionary &dict, const IOobject &io, const word &objectType, IOstreamOption streamOpt, const dictionary *metaDataDict=nullptr)
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
Detailed Description
Like faceSet but -reads data from faceZone -updates faceZone when writing.
Source files
faceZoneSet.H
faceZoneSet.C
Definition at line 47 of file faceZoneSet.H.
Constructor & Destructor Documentation
faceZoneSet() [1/3]
faceZoneSet (const polyMesh & mesh, const word & name, IOobjectOption::readOption rOpt = IOobjectOption::MUST_READ, IOobjectOption::writeOption wOpt = IOobjectOption::NO_WRITE)
Definition at line 58 of file faceZoneSet.C.
References topoSet::check(), ZoneMesh< ZoneType, MeshType >::findZoneID(), IOobjectOption::isReadOptional(), IOobjectOption::isReadRequired(), mesh, IOobject::name(), and faceZoneSet::updateSet().
faceZoneSet() [2/3]
faceZoneSet (const polyMesh & mesh, const word & name, const label size, IOobjectOption::writeOption wOpt = IOobjectOption::NO_WRITE)
Definition at line 91 of file faceZoneSet.C.
References faceZoneSet::updateSet().
faceZoneSet() [3/3]
faceZoneSet (const polyMesh & mesh, const word & name, const topoSet & set, IOobjectOption::writeOption wOpt = IOobjectOption::NO_WRITE)
Definition at line 108 of file faceZoneSet.C.
References faceZoneSet::updateSet().
~faceZoneSet()
virtual ~faceZoneSet () virtual default
Member Function Documentation
TypeName()
TypeName ("faceZoneSet")
addressing() [1/2]
const labelList & addressing () const inline noexcept
Definition at line 102 of file faceZoneSet.H.
addressing() [2/2]
labelList & addressing () inline noexcept
Definition at line 107 of file faceZoneSet.H.
flipMap() [1/2]
const boolList & flipMap () const inline noexcept
Definition at line 113 of file faceZoneSet.H.
flipMap() [2/2]
boolList & flipMap () inline noexcept
Definition at line 118 of file faceZoneSet.H.
updateSet()
void updateSet ()
Definition at line 44 of file faceZoneSet.C.
References HashTable< T, Key, Hash >::clearStorage(), HashTable< T, Key, Hash >::resize(), topoSet::set(), UList< T >::size(), and Foam::sortedOrder().
Referenced by faceZoneSet::faceZoneSet(), faceZoneSet::faceZoneSet(), and faceZoneSet::faceZoneSet().
invert()
void invert (const label maxLen) virtual
Reimplemented from topoSet.
Definition at line 127 of file faceZoneSet.C.
References found, n, and PtrList< T >::setSize().
subset()
void subset (const topoSet & set) virtual
Reimplemented from topoSet.
Definition at line 158 of file faceZoneSet.C.
References PtrList< T >::append(), Foam::endl(), forAll, Foam::name(), and WarningInFunction.
addSet()
void addSet (const topoSet & set) virtual
Reimplemented from topoSet.
Definition at line 206 of file faceZoneSet.C.
References PtrList< T >::append(), Foam::endl(), forAll, Foam::name(), and WarningInFunction.
subtractSet()
void subtractSet (const topoSet & set) virtual
Reimplemented from topoSet.
Definition at line 257 of file faceZoneSet.C.
References PtrList< T >::append(), Foam::endl(), forAll, Foam::name(), UPtrList< T >::size(), and WarningInFunction.
sync()
void sync (const polyMesh & mesh) virtual
Reimplemented from faceSet.
Definition at line 309 of file faceZoneSet.C.
References PtrList< T >::append(), Foam::endl(), forAll, syncTools::getMasterFaces(), mesh, primitiveMesh::nBoundaryFaces(), primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), Foam::returnReduce(), UPtrList< T >::size(), syncTools::swapBoundaryFaceList(), PtrList< T >::transfer(), WarningInFunction, and Foam::Zero.
writeDebug()
void writeDebug (Ostream & os, const primitiveMesh & mesh, const label maxLen) const virtual
Reimplemented from faceSet.
Definition at line 510 of file faceZoneSet.C.
References mesh, os(), and faceSet::writeDebug().
writeObject()
bool writeObject (IOstreamOption streamOpt, const bool writeOnProc) const virtual
Reimplemented from regIOobject.
Definition at line 438 of file faceZoneSet.C.
References ZoneMesh< ZoneType, MeshType >::clearAddressing(), ZoneMesh< ZoneType, MeshType >::findZoneID(), Foam::name(), PtrList< T >::set(), PtrList< T >::setSize(), UPtrList< T >::size(), Foam::type(), regIOobject::write(), and regIOobject::writeObject().
updateMesh()
void updateMesh (const mapPolyMesh & morphMap) virtual
Reimplemented from faceSet.
Definition at line 482 of file faceZoneSet.C.
References forAll, n, PtrList< T >::setSize(), and PtrList< T >::transfer().
maxSize()
Foam::label maxSize (const polyMesh & mesh) const virtual
Reimplemented from faceSet.
Definition at line 432 of file faceZoneSet.C.
References mesh, and primitiveMesh::nFaces().
The documentation for this class was generated from the following files:
src/meshTools/topoSet/topoSets/faceZoneSet.H
src/meshTools/topoSet/topoSets/faceZoneSet.C