OpenFOAM: HashPtrTable< T, Key, Hash > Class Template Reference
HashPtrTable< T, Key, Hash > Class Template Reference
A HashTable of pointers to objects of type <T>, with deallocation management of the pointers.
#include <HashPtrTable.H>
Public Types
typedef HashPtrTable< T, Key, Hash > this_type
typedef HashTable< T *, Key, Hash > parent_type
using iterator = typename parent_type::iterator
using const_iterator = typename parent_type::const_iterator
Public Types inherited from HashTable< T, Key, Hash >
typedef HashTable< T, Key, Hash > this_type
typedef std::conditional< std::is_same< Foam::zero, typenamestd::remove_cv< T >::type >::value, Detail::HashTableSingle< Key >, Detail::HashTablePair< Key, T > >::type node_type
typedef Key key_type
typedef T mapped_type
typedef T value_type
typedef Hash hasher
typedef T * pointer
typedef T & reference
typedef const T * const_pointer
typedef const T & const_reference
typedef label difference_type
typedef label size_type
using key_iterator = key_iterator_base< iterator >
using const_key_iterator = key_iterator_base< const_iterator >
Public Member Functions
HashPtrTable ()=default
HashPtrTable (const label size)
HashPtrTable (const this_type &rhs)
HashPtrTable (this_type &&rhs)
template<class INew >
HashPtrTable (Istream &is, const INew &inew)
HashPtrTable (Istream &is)
HashPtrTable (const dictionary &dict)
~HashPtrTable ()
const T * test (const Key &key) const
const T * get (const Key &key) const
autoPtr< T > release (iterator &iter)
autoPtr< T > release (const Key &key)
autoPtr< T > remove (iterator &iter)
autoPtr< T > remove (const Key &key)
bool erase (iterator &iter)
bool erase (const Key &key)
void clear ()
void merge (HashPtrTable< T, Key, Hash > &source)
void merge (HashPtrTable< T, Key, Hash > &&source)
void write (Ostream &os) const
void operator= (const this_type &rhs)
void operator= (this_type &&rhs)
template<class... Args>
bool emplace (const Key &key, Args &&... args)
template<class... Args>
T & emplace_set (const Key &key, Args &&... args)
bool insert (const Key &, T *)=delete
bool insert (const Key &key, std::unique_ptr< T > &&ptr)
bool insert (const Key &key, autoPtr< T > &&ptr)
bool set (const Key &key, T *ptr)
bool set (const Key &key, std::unique_ptr< T > &&ptr)
bool set (const Key &key, autoPtr< T > &&ptr)
bool set (const Key &key, const refPtr< T > &ptr)
bool set (const Key &key, const tmp< T > &ptr)
bool insert (const Key &key, autoPtr< T > &ptr)
bool set (const Key &key, autoPtr< T > &ptr)
Public Member Functions inherited from HashTable< T, Key, Hash >
HashTable ()
HashTable (const label size)
HashTable (Istream &is, const label size=128)
HashTable (const this_type &ht)
HashTable (this_type &&rhs)
HashTable (std::initializer_list< std::pair< Key, T > > list)
~HashTable ()
bool empty () const noexcept
label size () const noexcept
label capacity () const noexcept
T & at (const Key &key)
const T & at (const Key &key) const
bool contains (const Key &key) const
iterator find (const Key &key)
const_iterator find (const Key &key) const
const_iterator cfind (const Key &key) const
const T & lookup (const Key &key, const T &deflt) const
List< Key > toc () const
List< Key > sortedToc () const
template<class Compare >
List< Key > sortedToc (const Compare &comp) const
template<class UnaryPredicate >
List< Key > tocKeys (const UnaryPredicate &pred, const bool invert=false) const
template<class UnaryPredicate >
List< Key > tocValues (const UnaryPredicate &pred, const bool invert=false) const
template<class BinaryPredicate >
List< Key > tocEntries (const BinaryPredicate &pred, const bool invert=false) const
UPtrList< const node_type > csorted () const
UPtrList< const node_type > sorted () const
UPtrList< node_type > sorted ()
template<class UnaryPredicate >
label countKeys (const UnaryPredicate &pred, const bool invert=false) const
template<class UnaryPredicate >
label countValues (const UnaryPredicate &pred, const bool invert=false) const
template<class BinaryPredicate >
label countEntries (const BinaryPredicate &pred, const bool invert=false) const
template<class... Args>
bool emplace (const Key &key, Args &&... args)
template<class... Args>
bool emplace_set (const Key &key, Args &&... args)
bool insert (const Key &key, const T &obj)
bool insert (const Key &key, T &&obj)
bool set (const Key &key, const T &obj)
bool set (const Key &key, T &&obj)
bool erase (const iterator &iter)
bool erase (const Key &key)
template<class AnyType , class AnyHash >
label erase (const HashTable< AnyType, Key, AnyHash > &other)
label erase (std::initializer_list< Key > keys)
template<class InputIter >
label erase (InputIter first, InputIter last)
template<unsigned N>
label erase (const FixedList< Key, N > &keys)
label erase (const UList< Key > &keys)
template<class AnyType , class AnyHash >
label retain (const HashTable< AnyType, Key, AnyHash > &other)
template<class UnaryPredicate >
label filterKeys (const UnaryPredicate &pred, const bool pruning=false)
template<class UnaryPredicate >
label filterValues (const UnaryPredicate &pred, const bool pruning=false)
template<class BinaryPredicate >
label filterEntries (const BinaryPredicate &pred, const bool pruning=false)
void resize (const label sz)
void clear ()
void clearStorage ()
void swap (HashTable< T, Key, Hash > &rhs)
void transfer (HashTable< T, Key, Hash > &rhs)
void merge (HashTable< T, Key, Hash > &source)
void merge (HashTable< T, Key, Hash > &&source)
T & operator[] (const Key &key)
const T & operator[] (const Key &key) const
T & operator() (const Key &key)
T & operator() (const Key &key, const T &deflt)
void operator= (const this_type &rhs)
void operator= (std::initializer_list< std::pair< Key, T > > rhs)
void operator= (this_type &&rhs)
bool operator== (const this_type &rhs) const
bool operator!= (const this_type &rhs) const
this_type & operator+= (const this_type &rhs)
const_iterator_pair< const_key_iterator, this_type > keys () const
iterator begin ()
const_iterator begin () const
const_iterator cbegin () const
iterator end () noexcept
const_iterator end () const noexcept
constexpr const_iterator cend () const noexcept
Ostream & printInfo (Ostream &os) const
Ostream & writeKeys (Ostream &os, const label shortLen=0) const
bool found (const Key &key) const
template<class Compare >
Foam::List< Key > sortedToc (const Compare &comp) const
template<class UnaryPredicate >
Foam::List< Key > tocKeys (const UnaryPredicate &pred, const bool invert) const
template<class UnaryPredicate >
Foam::List< Key > tocValues (const UnaryPredicate &pred, const bool invert) const
template<class BinaryPredicate >
Foam::List< Key > tocEntries (const BinaryPredicate &pred, const bool invert) const
template<class UnaryPredicate >
Foam::label countKeys (const UnaryPredicate &pred, const bool invert) const
template<class UnaryPredicate >
Foam::label countValues (const UnaryPredicate &pred, const bool invert) const
template<class BinaryPredicate >
Foam::label countEntries (const BinaryPredicate &pred, const bool invert) const
template<class InputIter >
Foam::label erase (InputIter first, InputIter last)
template<unsigned N>
Foam::label erase (const FixedList< Key, N > &keys)
template<class AnyType , class AnyHash >
Foam::label erase (const HashTable< AnyType, Key, AnyHash > &other)
template<class AnyType , class AnyHash >
Foam::label retain (const HashTable< AnyType, Key, AnyHash > &other)
template<class UnaryPredicate >
Foam::label filterKeys (const UnaryPredicate &pred, const bool pruning)
template<class UnaryPredicate >
Foam::label filterValues (const UnaryPredicate &pred, const bool pruning)
template<class BinaryPredicate >
Foam::label filterEntries (const BinaryPredicate &pred, const bool pruning)
Public Member Functions inherited from HashTableCore
ClassName ("HashTable")
HashTableCore () noexcept=default
Friends
Istream & operator>> (Istream &is, HashPtrTable< T, Key, Hash > &tbl)
Additional Inherited Members
Static Public Member Functions inherited from HashTableCore
static label canonicalSize (const label requested_size)
Static Public Attributes inherited from HashTableCore
static const label maxTableSize
Detailed Description
template<class T, class Key = word, class Hash = Foam::Hash<Key>>
class Foam::HashPtrTable< T, Key, Hash >
A HashTable of pointers to objects of type <T>, with deallocation management of the pointers.
Source files
HashPtrTable.H
HashPtrTable.C
HashPtrTableI.H
HashPtrTableIO.C
Definition at line 62 of file HashPtrTable.H.
Member Typedef Documentation
this_type
template<class T , class Key = word, class Hash = Foam::Hash<Key>> typedef HashPtrTable<T, Key, Hash> this_type
Definition at line 80 of file HashPtrTable.H.
parent_type
template<class T , class Key = word, class Hash = Foam::Hash<Key>> typedef HashTable<T*, Key, Hash> parent_type
Definition at line 83 of file HashPtrTable.H.
iterator
template<class T , class Key = word, class Hash = Foam::Hash<Key>> using iterator = typename parent_type::iterator
Definition at line 85 of file HashPtrTable.H.
const_iterator
template<class T , class Key = word, class Hash = Foam::Hash<Key>> using const_iterator = typename parent_type::const_iterator
Definition at line 86 of file HashPtrTable.H.
Constructor & Destructor Documentation
HashPtrTable() [1/7]
template<class T , class Key = word, class Hash = Foam::Hash<Key>> HashPtrTable () default
HashPtrTable() [2/7]
template<class T , class Key , class Hash > HashPtrTable (const label size) inline explicit
Definition at line 28 of file HashPtrTableI.H.
HashPtrTable() [3/7]
template<class T , class Key = word, class Hash = Foam::Hash<Key>> HashPtrTable (const this_type & rhs)
HashPtrTable() [4/7]
template<class T , class Key = word, class Hash = Foam::Hash<Key>> HashPtrTable (this_type && rhs) inline
HashPtrTable() [5/7]
template<class T , class Key , class Hash > template<class INew > HashPtrTable (Istream & is, const INew & inew)
Definition at line 154 of file HashPtrTableIO.C.
HashPtrTable() [6/7]
template<class T , class Key , class Hash > HashPtrTable (Istream & is)
Definition at line 161 of file HashPtrTableIO.C.
HashPtrTable() [7/7]
template<class T , class Key , class Hash > HashPtrTable (const dictionary & dict) explicit
Definition at line 168 of file HashPtrTableIO.C.
References Foam::read().
~HashPtrTable()
template<class T , class Key , class Hash > ~HashPtrTable ()
Definition at line 56 of file HashPtrTable.C.
References PtrList< T >::clear().
Member Function Documentation
test()
template<class T , class Key , class Hash > const T * test (const Key & key) const inline
Definition at line 47 of file HashPtrTableI.H.
get()
template<class T , class Key , class Hash > const T * get (const Key & key) const inline
Definition at line 60 of file HashPtrTableI.H.
release() [1/2]
template<class T , class Key , class Hash > Foam::autoPtr< T > release (iterator & iter)
Definition at line 65 of file HashPtrTable.C.
release() [2/2]
template<class T , class Key , class Hash > Foam::autoPtr< T > release (const Key & key)
Definition at line 79 of file HashPtrTable.C.
remove() [1/2]
template<class T , class Key , class Hash > Foam::autoPtr< T > remove (iterator & iter)
Definition at line 87 of file HashPtrTable.C.
remove() [2/2]
template<class T , class Key , class Hash > Foam::autoPtr< T > remove (const Key & key)
Definition at line 101 of file HashPtrTable.C.
erase() [1/2]
template<class T , class Key , class Hash > bool erase (iterator & iter)
Definition at line 109 of file HashPtrTable.C.
References T.
erase() [2/2]
template<class T , class Key , class Hash > bool erase (const Key & key)
Definition at line 127 of file HashPtrTable.C.
References erase().
clear()
template<class T , class Key , class Hash > void clear ()
Definition at line 135 of file HashPtrTable.C.
merge() [1/2]
template<class T , class Key , class Hash > void merge (HashPtrTable< T, Key, Hash > & source)
Definition at line 147 of file HashPtrTable.C.
merge() [2/2]
template<class T , class Key , class Hash > void merge (HashPtrTable< T, Key, Hash > && source)
Definition at line 159 of file HashPtrTable.C.
write()
template<class T , class Key , class Hash > void write (Ostream & os) const
Definition at line 137 of file HashPtrTableIO.C.
References os(), and T.
operator=() [1/2]
template<class T , class Key = word, class Hash = Foam::Hash<Key>> void operator= (const this_type & rhs)
operator=() [2/2]
template<class T , class Key = word, class Hash = Foam::Hash<Key>> void operator= (this_type && rhs)
emplace()
template<class T , class Key , class Hash > template<class... Args> bool emplace (const Key & key, Args &&... args) inline
Definition at line 74 of file HashPtrTableI.H.
References args, and T.
emplace_set()
template<class T , class Key , class Hash > template<class... Args> T & emplace_set (const Key & key, Args &&... args) inline
Definition at line 91 of file HashPtrTableI.H.
insert() [1/4]
template<class T , class Key = word, class Hash = Foam::Hash<Key>> bool insert (const Key & , T *) inline delete
insert() [2/4]
template<class T , class Key , class Hash > bool insert (const Key & key, std::unique_ptr< T > && ptr) inline
Definition at line 104 of file HashPtrTableI.H.
References UPtrList< T >::get(), and PtrList< T >::release().
insert() [3/4]
template<class T , class Key , class Hash > bool insert (const Key & key, autoPtr< T > && ptr) inline
Definition at line 121 of file HashPtrTableI.H.
set() [1/6]
template<class T , class Key , class Hash > bool set (const Key & key, T * ptr) inline
Definition at line 138 of file HashPtrTableI.H.
References T.
Referenced by InterfaceCompositionPhaseChangePhaseSystem< BasePhaseSystem >::InterfaceCompositionPhaseChangePhaseSystem(), MassTransferPhaseSystem< BasePhaseSystem >::MassTransferPhaseSystem(), MomentumTransferPhaseSystem< BasePhaseSystem >::MomentumTransferPhaseSystem(), multiphaseSystem::multiphaseSystem(), PhaseTransferPhaseSystem< BasePhaseSystem >::PhaseTransferPhaseSystem(), PopulationBalancePhaseSystem< BasePhaseSystem >::PopulationBalancePhaseSystem(), HashPtrTable< T, Key, Hash >::set(), ThermalPhaseChangePhaseSystem< BasePhaseSystem >::ThermalPhaseChangePhaseSystem(), and TwoResistanceHeatTransferPhaseSystem< BasePhaseSystem >::TwoResistanceHeatTransferPhaseSystem().
set() [2/6]
template<class T , class Key , class Hash > bool set (const Key & key, std::unique_ptr< T > && ptr) inline
Definition at line 158 of file HashPtrTableI.H.
References PtrList< T >::release().
set() [3/6]
template<class T , class Key , class Hash > bool set (const Key & key, autoPtr< T > && ptr) inline
Definition at line 169 of file HashPtrTableI.H.
References PtrList< T >::release().
set() [4/6]
template<class T , class Key , class Hash > bool set (const Key & key, const refPtr< T > & ptr) inline
Definition at line 180 of file HashPtrTableI.H.
set() [5/6]
template<class T , class Key , class Hash > bool set (const Key & key, const tmp< T > & ptr) inline
Definition at line 191 of file HashPtrTableI.H.
insert() [4/4]
template<class T , class Key = word, class Hash = Foam::Hash<Key>> bool insert (const Key & key, autoPtr< T > & ptr) inline
Definition at line 251 of file HashPtrTable.H.
References insert().
set() [6/6]
template<class T , class Key = word, class Hash = Foam::Hash<Key>> bool set (const Key & key, autoPtr< T > & ptr) inline
Definition at line 257 of file HashPtrTable.H.
References HashPtrTable< T, Key, Hash >::set().
Friends And Related Symbol Documentation
operator>>
template<class T , class Key = word, class Hash = Foam::Hash<Key>> Istream & operator>> (Istream & is, HashPtrTable< T, Key, Hash > & tbl) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/HashTables/HashPtrTable/HashPtrTable.H
src/OpenFOAM/containers/HashTables/HashPtrTable/HashPtrTable.C
src/OpenFOAM/containers/HashTables/HashPtrTable/HashPtrTableI.H
src/OpenFOAM/containers/HashTables/HashPtrTable/HashPtrTableIO.C