OpenFOAM: triSurfacePointGeoMesh Class Reference
triSurfacePointGeoMesh Class Reference
#include <triSurfacePointGeoMesh.H>
Public Member Functions
triSurfacePointGeoMesh (const triSurface &mesh)
label size () const
Public Member Functions inherited from GeoMesh< triSurface >
GeoMesh (const triSurface &mesh)
bool hasDb () const
const objectRegistry & thisDb () const
const triSurface & operator() () const
Static Public Member Functions
static label size (const Mesh &mesh)
Additional Inherited Members
Public Types inherited from GeoMesh< triSurface >
typedef triSurface Mesh
typedef MESH::BoundaryMesh BoundaryMesh
Protected Attributes inherited from GeoMesh< triSurface >
const triSurface & mesh_
Detailed Description
Definition at line 41 of file triSurfacePointGeoMesh.H.
Constructor & Destructor Documentation
triSurfacePointGeoMesh()
triSurfacePointGeoMesh (const triSurface & mesh) inline explicit
Definition at line 50 of file triSurfacePointGeoMesh.H.
Member Function Documentation
size() [1/2]
static label size (const Mesh & mesh) inline static
Definition at line 59 of file triSurfacePointGeoMesh.H.
References mesh, and UPtrList< T >::size().
size() [2/2]
label size () const inline
Definition at line 65 of file triSurfacePointGeoMesh.H.
References GeoMesh< triSurface >::mesh_, and triSurfacePointGeoMesh::size().
Referenced by triSurfacePointGeoMesh::size().
The documentation for this class was generated from the following file:
src/surfMesh/triSurface/fields/triSurfacePointGeoMesh.H