OpenFOAM: regionFunctionObject Class Reference
regionFunctionObject Class Reference
Specialization of Foam::functionObject for a region and providing a reference to the region Foam::objectRegistry.
#include <regionFunctionObject.H>
Public Member Functions
TypeName ("regionFunctionObject")
regionFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
regionFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
virtual ~regionFunctionObject ()=default
virtual bool read (const dictionary &dict)
template<class ObjectType >
const ObjectType * lookupObjectPtr (const word &fieldName) const
template<class ObjectType >
ObjectType * lookupObjectRefPtr (const word &fieldName) const
Public Member Functions inherited from stateFunctionObject
stateFunctionObject (const word &name, const Time &runTime)
virtual ~stateFunctionObject ()=default
dictionary & propertyDict ()
bool foundProperty (const word &entryName) const
void clearTrigger ()
label getTrigger () const
bool setTrigger (const label triggeri)
bool getDict (const word &entryName, dictionary &dict) const
bool getObjectDict (const word &objectName, const word &entryName, dictionary &dict) const
template<class Type >
Type getProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getProperty (const word &entryName, Type &value) const
template<class Type >
void setProperty (const word &entryName, const Type &value)
template<class Type >
Type getObjectProperty (const word &objectName, const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getObjectProperty (const word &objectName, const word &entryName, Type &value) const
template<class Type >
void setObjectProperty (const word &objectName, const word &entryName, const Type &value)
template<class Type >
void setResult (const word &entryName, const Type &value)
template<class Type >
void setObjectResult (const word &objectName, const word &entryName, const Type &value)
template<class Type >
Type getResult (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
Type getObjectResult (const word &objectName, const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getObjectResult (const word &objectName, const word &entryName, Type &value) const
word resultType (const word &entryName) const
word objectResultType (const word &objectName, const word &entryName) const
wordList objectResultEntries () const
wordList objectResultEntries (const word &objectName) const
void writeResultEntries (Ostream &os) const
void writeResultEntries (const word &objectName, Ostream &os) const
void writeAllResultEntries (Ostream &os) const
Public Member Functions inherited from timeFunctionObject
timeFunctionObject (const word &name, const Time &runTime)
virtual ~timeFunctionObject ()=default
const Time & time () const
objectRegistry & storedObjects ()
const objectRegistry & storedObjects () const
Public Member Functions inherited from functionObject
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name, const bool withNamePrefix=defaultUseNamePrefix)
autoPtr< functionObject > clone () const
virtual ~functionObject ()=default
virtual const word & type () const =0
const word & name () const noexcept
bool useNamePrefix () const noexcept
bool useNamePrefix (bool on) noexcept
virtual bool execute ()=0
virtual bool execute (const label subIndex)
virtual bool write ()=0
virtual bool end ()
virtual bool adjustTimeStep ()
virtual bool filesModified () const
virtual void updateMesh (const mapPolyMesh &mpm)
virtual void movePoints (const polyMesh &mesh)
Protected Member Functions
virtual const objectRegistry & obr () const
template<class ObjectType >
bool foundObject (const word &fieldName) const
template<class ObjectType >
const ObjectType * cfindObject (const word &fieldName) const
template<class ObjectType >
const ObjectType * findObject (const word &fieldName) const
template<class ObjectType >
ObjectType * findObject (const word &fieldName)
template<class ObjectType >
ObjectType * getObjectPtr (const word &fieldName) const
template<class ObjectType >
const ObjectType & lookupObject (const word &fieldName) const
template<class ObjectType >
ObjectType & lookupObjectRef (const word &fieldName) const
template<class ObjectType >
bool store (word &fieldName, const tmp< ObjectType > &tfield, bool cacheable=false)
template<class ObjectType >
bool storeInDb (const word &fieldName, const tmp< ObjectType > &tfield, const objectRegistry &obr)
bool writeObject (const word &fieldName)
bool clearObject (const word &fieldName)
void clearObjects (const wordList &objNames)
regionFunctionObject (const regionFunctionObject &)=delete
void operator= (const regionFunctionObject &)=delete
Protected Member Functions inherited from stateFunctionObject
const functionObjects::properties & stateDict () const
functionObjects::properties & stateDict ()
stateFunctionObject (const stateFunctionObject &)=delete
void operator= (const stateFunctionObject &)=delete
Protected Member Functions inherited from timeFunctionObject
void clearOutputObjects (const wordList &objNames)
timeFunctionObject (const timeFunctionObject &)=delete
void operator= (const timeFunctionObject &)=delete
Protected Member Functions inherited from functionObject
word scopedName (const word &name) const
Protected Attributes
word subRegistryName_
const objectRegistry & obr_
const objectRegistry * obrPtr_
Protected Attributes inherited from timeFunctionObject
const Time & time_
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &runTime, const dictionary &dict)
Public Attributes inherited from functionObject
bool log
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
static bool defaultUseNamePrefix
static word outputPrefix
Detailed Description
Specialization of Foam::functionObject for a region and providing a reference to the region Foam::objectRegistry.
Also provides support for referencing an alternative objectRegistry that can hold fields. This may be used, for example, to access stored surfaces and fields.
Dictionary controls
Property Description Type Req'd Dflt
region Name of the mesh region word no region0
subRegion Name for alternative objectRegistry word no ""
See also
Foam::functionObjects::stateFunctionObject
Source files
regionFunctionObject.H
regionFunctionObject.C
Definition at line 86 of file regionFunctionObject.H.
Constructor & Destructor Documentation
regionFunctionObject() [1/3]
regionFunctionObject (const regionFunctionObject &) protected delete
regionFunctionObject() [2/3]
regionFunctionObject (const word & name, const Time & runTime, const dictionary & dict)
Definition at line 130 of file regionFunctionObject.C.
regionFunctionObject() [3/3]
regionFunctionObject (const word & name, const objectRegistry & obr, const dictionary & dict)
Definition at line 150 of file regionFunctionObject.C.
~regionFunctionObject()
virtual ~regionFunctionObject () virtual default
Member Function Documentation
obr()
const Foam::objectRegistry & obr () const protected virtual
Reimplemented in surfaceFieldValue.
Definition at line 40 of file regionFunctionObject.C.
References objectRegistry::cfindObject(), Foam::nl, regionFunctionObject::obr_, regionFunctionObject::obrPtr_, timeFunctionObject::storedObjects(), regionFunctionObject::subRegistryName_, and WarningInFunction.
Referenced by fieldAverage::addMeanFieldType(), regionFunctionObject::foundObject(), fieldAverage::initialize(), and particleDistribution::processField().
foundObject()
template<class ObjectType > bool foundObject (const word & fieldName) const protected
Definition at line 28 of file regionFunctionObjectTemplates.C.
References regionFunctionObject::obr().
cfindObject()
template<class ObjectType > const ObjectType * cfindObject (const word & fieldName) const protected
Definition at line 38 of file regionFunctionObjectTemplates.C.
findObject() [1/2]
template<class ObjectType > const ObjectType * findObject (const word & fieldName) const protected
Definition at line 48 of file regionFunctionObjectTemplates.C.
findObject() [2/2]
template<class ObjectType > ObjectType * findObject (const word & fieldName) protected
Definition at line 58 of file regionFunctionObjectTemplates.C.
getObjectPtr()
template<class ObjectType > ObjectType * getObjectPtr (const word & fieldName) const protected
Definition at line 69 of file regionFunctionObjectTemplates.C.
lookupObject()
template<class ObjectType > const ObjectType & lookupObject (const word & fieldName) const protected
Definition at line 79 of file regionFunctionObjectTemplates.C.
Referenced by wallShearStress::write(), and yPlus::write().
lookupObjectRef()
template<class ObjectType > ObjectType & lookupObjectRef (const word & fieldName) const protected
Definition at line 89 of file regionFunctionObjectTemplates.C.
Referenced by wallShearStress::execute().
store()
template<class ObjectType > bool store (word & fieldName, const tmp< ObjectType > & tfield, bool cacheable = false) protected
Definition at line 99 of file regionFunctionObjectTemplates.C.
References Foam::endl(), Foam::name(), Foam::nl, and WarningInFunction.
Referenced by blendingFactor::blendingFactor(), fieldsExpression::calcFieldTypes(), DESModelRegions::DESModelRegions(), surfaceInterpolate::interpolateFields(), and stabilityBlendingFactor::stabilityBlendingFactor().
storeInDb()
template<class ObjectType > bool storeInDb (const word & fieldName, const tmp< ObjectType > & tfield, const objectRegistry & obr) protected
Definition at line 157 of file regionFunctionObjectTemplates.C.
References objectRegistry::getObjectPtr().
writeObject()
bool writeObject (const word & fieldName) protected
Definition at line 66 of file regionFunctionObject.C.
References Foam::endl(), Log, IOobject::name(), Foam::name(), Foam::type(), and regIOobject::write().
clearObject()
bool clearObject (const word & fieldName) protected
Definition at line 87 of file regionFunctionObject.C.
References regIOobject::checkOut(), and regIOobject::ownedByRegistry().
clearObjects()
void clearObjects (const wordList & objNames) protected
Definition at line 111 of file regionFunctionObject.C.
References regIOobject::checkOut(), and regIOobject::ownedByRegistry().
operator=()
void operator= (const regionFunctionObject &) protected delete
TypeName()
TypeName ("regionFunctionObject")
read()
bool read (const dictionary & dict) virtual
Reimplemented from functionObject.
Reimplemented in age, AMIWeights, blendingFactor, comfort, continuityError, CourantNo, Curle, ddt2, DESModelRegions, extractEulerianParticles, fieldAverage, fieldExtents, fieldMinMax, interfaceHeight, log, mapFields, momentum, momentumError, norm, particleDistribution, PecletNo, pow, pressure, processorField, proudmanAcousticPower, reactionsSensitivityAnalysis< chemistryType >, regionSizeDistribution, stabilityBlendingFactor, streamLine, streamLineBase, surfaceDistance, surfaceInterpolate, turbulenceFields, valueAverage, wallBoundedStreamLine, wallShearStress, writeCellCentres, writeCellVolumes, XiReactionRate, yPlus, propellerInfo, dsmcFields, icoUncoupledKinematicCloud, energySpectrum, energyTransport, scalarTransport, runTimeControl, solverInfo, thermoCoupleProbes, writeDictionary, patchProbes, probes, sampledSets, sixDoFRigidBodyState, BilgerMixtureFraction, ObukhovLength, binField, columnAverage, derivedFields, DMD, fvExpressionField, fieldExpression, fieldsExpression, fieldValue, surfaceFieldValue, volFieldValue, fluxSummary, heatTransferCoeff, multiphaseInterHtcModel, reactingEulerHtcModel, histogram, limitFields, nearWallFields, randomise, readFields, reference, resolutionIndex, setFlow, wallHeatFlux, zeroGradient, forceCoeffs, forces, hydrostaticPressure, cloudInfo, dataCloud, vtkCloud, phaseForces, sizeDistribution, electricPotential, areaWrite, ensightWrite, removeRegisteredObject, sampledSurfaces, specieReactionRates< ChemistryModelType >, and moleFractions< ThermoType >.
Definition at line 166 of file regionFunctionObject.C.
References dict, word::null, and functionObject::read().
Referenced by valueAverage::read(), writeDictionary::read(), cloudInfo::read(), removeRegisteredObject::read(), and specieReactionRates< ChemistryModelType >::read().
lookupObjectPtr()
template<class ObjectType > const ObjectType * lookupObjectPtr (const word & fieldName) const inline
Definition at line 231 of file regionFunctionObject.H.
lookupObjectRefPtr()
template<class ObjectType > ObjectType * lookupObjectRefPtr (const word & fieldName) const inline
Definition at line 240 of file regionFunctionObject.H.
Member Data Documentation
subRegistryName_
word subRegistryName_ protected
Definition at line 95 of file regionFunctionObject.H.
Referenced by regionFunctionObject::obr().
obr_
const objectRegistry& obr_ protected
Definition at line 98 of file regionFunctionObject.H.
Referenced by nearWallFields::createFields(), turbulenceFields::initialise(), surfaceInterpolate::interpolateFields(), limitFields::limitScalarField(), sizeDistribution::mesh(), regionFunctionObject::obr(), turbulenceFields::processField(), forces::setCoordinateSystem(), and volFieldValue::validField().
obrPtr_
const objectRegistry* obrPtr_ mutable protected
Definition at line 102 of file regionFunctionObject.H.
Referenced by regionFunctionObject::obr().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/functionObjects/regionFunctionObject/regionFunctionObject.H
src/OpenFOAM/db/functionObjects/regionFunctionObject/regionFunctionObject.C
src/OpenFOAM/db/functionObjects/regionFunctionObject/regionFunctionObjectTemplates.C