OpenFOAM: wallHeatTransferFvPatchScalarField Class Reference
wallHeatTransferFvPatchScalarField Class Reference
Boundary conditions » Thermophysical | Boundary conditions » Wall
This boundary condition provides an enthalpy condition for wall heat transfer.
#include <wallHeatTransferFvPatchScalarField.H>
Public Member Functions
TypeName ("wallHeatTransfer")
wallHeatTransferFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
wallHeatTransferFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
wallHeatTransferFvPatchScalarField (const wallHeatTransferFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
wallHeatTransferFvPatchScalarField (const wallHeatTransferFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
wallHeatTransferFvPatchScalarField (const wallHeatTransferFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
const scalarField & Tinf () const
scalarField & Tinf ()
const scalarField & alphaWall () const
scalarField & alphaWall ()
virtual void autoMap (const fvPatchFieldMapper &)
virtual void rmap (const fvPatchScalarField &, const labelList &)
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
This boundary condition provides an enthalpy condition for wall heat transfer.
Usage
Property Description Required Default value
Tinf wall temperature yes
alphaWall thermal diffusivity yes
Example of the boundary condition specification:
    <patchName>
    {
        type            wallHeatTransfer;
        Tinf            uniform 500;
        alphaWall       uniform 1;
    }
Source files
wallHeatTransferFvPatchScalarField.H
wallHeatTransferFvPatchScalarField.C
Definition at line 82 of file wallHeatTransferFvPatchScalarField.H.
Constructor & Destructor Documentation
wallHeatTransferFvPatchScalarField() [1/5]
wallHeatTransferFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 28 of file wallHeatTransferFvPatchScalarField.C.
References Foam::Zero.
wallHeatTransferFvPatchScalarField() [2/5]
wallHeatTransferFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 58 of file wallHeatTransferFvPatchScalarField.C.
References dict, and Foam::Zero.
wallHeatTransferFvPatchScalarField() [3/5]
wallHeatTransferFvPatchScalarField (const wallHeatTransferFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 44 of file wallHeatTransferFvPatchScalarField.C.
wallHeatTransferFvPatchScalarField() [4/5]
wallHeatTransferFvPatchScalarField (const wallHeatTransferFvPatchScalarField & tppsf)
Definition at line 80 of file wallHeatTransferFvPatchScalarField.C.
wallHeatTransferFvPatchScalarField() [5/5]
wallHeatTransferFvPatchScalarField (const wallHeatTransferFvPatchScalarField & tppsf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 91 of file wallHeatTransferFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("wallHeatTransfer")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 135 of file wallHeatTransferFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 151 of file wallHeatTransferFvPatchScalarField.H.
Tinf() [1/2]
const scalarField & Tinf () const inline
Definition at line 168 of file wallHeatTransferFvPatchScalarField.H.
Tinf() [2/2]
scalarField & Tinf () inline
Definition at line 174 of file wallHeatTransferFvPatchScalarField.H.
alphaWall() [1/2]
const scalarField & alphaWall () const inline
Definition at line 180 of file wallHeatTransferFvPatchScalarField.H.
alphaWall() [2/2]
scalarField & alphaWall () inline
Definition at line 186 of file wallHeatTransferFvPatchScalarField.H.
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Definition at line 105 of file wallHeatTransferFvPatchScalarField.C.
References Field< scalar >::autoMap().
rmap()
void rmap (const fvPatchScalarField & ptf, const labelList & addr) virtual
Definition at line 116 of file wallHeatTransferFvPatchScalarField.C.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 132 of file wallHeatTransferFvPatchScalarField.C.
References IOobject::groupName(), and turbulenceModel::propertiesName.
write()
void write (Ostream & os) const virtual
Definition at line 162 of file wallHeatTransferFvPatchScalarField.C.
References os(), fvPatchField< Type >::write(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/thermoTools/derivedFvPatchFields/wallHeatTransfer/wallHeatTransferFvPatchScalarField.H
src/thermoTools/derivedFvPatchFields/wallHeatTransfer/wallHeatTransferFvPatchScalarField.C