OpenFOAM: RanzMarshall< CloudType > Class Template Reference
RanzMarshall< CloudType > Class Template Reference
Lagrangian particle models » Submodels » Thermodynamic » Heat transfer
Nusselt-number model using the empirical Ranz-Marshall correlation to be used in modelling of the fluid-particle heat transfer coefficient:
#include <RanzMarshall.H>
Public Member Functions
TypeName ("RanzMarshall")
void operator= (const RanzMarshall &)=delete
RanzMarshall (const dictionary &dict, CloudType &cloud)
RanzMarshall (const RanzMarshall< CloudType > &im)
virtual autoPtr< HeatTransferModel< CloudType > > clone () const
virtual ~RanzMarshall ()=default
virtual scalar Nu (const scalar Re, const scalar Pr) const
Public Member Functions inherited from HeatTransferModel< CloudType >
TypeName ("heatTransferModel")
declareRunTimeSelectionTable (autoPtr, HeatTransferModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
void operator= (const HeatTransferModel< CloudType > &)=delete
HeatTransferModel (CloudType &owner)
HeatTransferModel (const dictionary &dict, CloudType &owner, const word &type)
HeatTransferModel (const HeatTransferModel< CloudType > &htm)
virtual ~HeatTransferModel ()=default
bool BirdCorrection () const noexcept
virtual scalar htc (const scalar dp, const scalar Re, const scalar Pr, const scalar kappa, const scalar NCpW) const
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
virtual ~CloudSubModelBase ()=default
const CloudType & owner () const
virtual bool writeTime () const
virtual fileName localPath () const
CloudType & owner ()
virtual void info ()
virtual void write (Ostream &os) const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
subModelBase (const subModelBase &smb)
virtual ~subModelBase ()=default
const word & modelName () const
const dictionary & dict () const
const word & baseName () const
const word & modelType () const
const dictionary & coeffDict () const
const dictionary & properties () const
virtual bool defaultCoeffs (const bool printMsg) const
virtual bool active () const
virtual void cacheFields (const bool store)
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
bool getModelDict (const word &entryName, dictionary &dict) const
template<class Type >
bool getModelProperty (const word &entryName, Type &value) const
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Additional Inherited Members
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Static Public Member Functions inherited from HeatTransferModel< CloudType >
static autoPtr< HeatTransferModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Public Attributes inherited from subModelBase
bool log
Protected Member Functions inherited from subModelBase
bool inLine () const
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Protected Attributes inherited from subModelBase
const word modelName_
dictionary & properties_
const dictionary dict_
const word baseName_
const word modelType_
const dictionary coeffDict_
Detailed Description
template<class CloudType>
class Foam::RanzMarshall< CloudType >
Nusselt-number model using the empirical Ranz-Marshall correlation to be used in modelling of the fluid-particle heat transfer coefficient:
with
where
= Nusselt number
= Particle Reynolds number
= Prandtl number
= Particle diameter
= Density of carrier in the film surrounding particle
= Dynamic viscosity of carrier in the film surrounding particle
= Relative velocity between particle and carrier
= Correlation coefficient
= Correlation coefficient
= Correlation exponent of particle Reynolds number
= Correlation exponent of Prandtl number
= Specific heat capacity
= Thermal conductivity of carrier in the film
Reference:
        Standard model:
            Ranz, W. E., & Marshall, W. R. (1952).
            Evaporation from drops - part 1.
            Chem. Eng. Prog, 48, 22, pp. 141-146.
            Ranz, W. E., & Marshall, W. R. (1952).
            Evaporation from drops - part 2.
            Chem. Eng. Prog, 48, 4, pp. 173-180.
        Expressions (tag:AOB), p. 18:
            Amsden, A. A., O'Rourke, P. J., & Butler, T. D. (1989).
            KIVA-II: A computer program for chemically
            reactive flows with sprays (No. LA-11560-MS).
            Los Alamos National Lab.(LANL), Los Alamos, NM (United States).
            DOI:10.2172/6228444
Usage
Minimal example by using constant/<CloudProperties>:
subModels
{
    // Mandatory entries
    heatTransferModel    RanzMarshall;
    // Optional entries
    RanzMarshallCoeffs
    {
        a    2.0;
        b    0.6;
        m    0.5;
        n    0.66666;
    }
}
where the entries mean:
Property Description Type Reqd Deflt
heatTransferModel Type name: RanzMarshall word yes -
a Correlation coefficient scalar no 2.0
b Correlation coefficient scalar no 0.6
m Correlation exponent of particle Reynolds number scalar no 0.5
n Correlation exponent of Prandtl number scalar no 1.0/3.0
Source files
RanzMarshall.H
RanzMarshall.C
Definition at line 219 of file RanzMarshall.H.
Constructor & Destructor Documentation
RanzMarshall() [1/2]
template<class CloudType > RanzMarshall (const dictionary & dict, CloudType & cloud)
Definition at line 27 of file RanzMarshall.C.
RanzMarshall() [2/2]
template<class CloudType > RanzMarshall (const RanzMarshall< CloudType > & im)
Definition at line 42 of file RanzMarshall.C.
~RanzMarshall()
template<class CloudType > virtual ~RanzMarshall () virtual default
Member Function Documentation
TypeName()
template<class CloudType > TypeName ("RanzMarshall< CloudType >")
operator=()
template<class CloudType > void operator= (const RanzMarshall< CloudType > &) delete
clone()
template<class CloudType > virtual autoPtr< HeatTransferModel< CloudType > > clone () const inline virtual
Implements HeatTransferModel< CloudType >.
Definition at line 259 of file RanzMarshall.H.
Nu()
template<class CloudType > Foam::scalar Nu (const scalar Re, const scalar Pr) const virtual
Implements HeatTransferModel< CloudType >.
Definition at line 55 of file RanzMarshall.C.
References Foam::pow(), Pr(), and Foam::Re().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/Thermodynamic/HeatTransferModel/RanzMarshall/RanzMarshall.H
src/lagrangian/intermediate/submodels/Thermodynamic/HeatTransferModel/RanzMarshall/RanzMarshall.C