OpenFOAM: faceCollapser Class Reference
faceCollapser Class Reference
Collapses faces into edges. Used to remove sliver faces (faces with small area but non-zero span).
#include <faceCollapser.H>
Public Member Functions
ClassName ("faceCollapser")
faceCollapser (const polyMesh &mesh)
void setRefinement (const labelList &faceLabels, const labelList &fpA, const labelList &fpB, polyTopoChange &) const
void updateMesh (const mapPolyMesh &)
Detailed Description
Collapses faces into edges. Used to remove sliver faces (faces with small area but non-zero span).
Passed in as
face label
the two indices in the face (fpA, fpB) which delimit the vertices to be kept.
Takes the vertices outside the range fpA..fpB and projects them onto the kept edges (edges using kept vertices only).
Note:
Use in combination with edge collapse to cleanup meshes.
Can not remove cells so will mess up trying to remove a face on a tet.
WIP. Should be combined with edge collapsing and cell collapsing into proper 'collapser'.
Caller is responsible for making sure kept vertices (fpA..fpB) for one face are not the vertices to be removed for another face.
Source files
faceCollapser.H
faceCollapser.C
Definition at line 74 of file faceCollapser.H.
Constructor & Destructor Documentation
faceCollapser()
faceCollapser (const polyMesh & mesh) explicit
Definition at line 196 of file faceCollapser.C.
Member Function Documentation
ClassName()
ClassName ("faceCollapser")
setRefinement()
void setRefinement (const labelList & faceLabels, const labelList & fpA, const labelList & fpB, polyTopoChange & meshMod) const
Definition at line 204 of file faceCollapser.C.
References Foam::abort(), PtrList< T >::append(), e, Foam::endl(), f(), faceLabels(), Foam::FatalError, FatalErrorInFunction, UList< T >::fcIndex(), forAll, forAllConstIters, insert(), Foam::magSqr(), Foam::nl, points, Foam::Pout, UList< T >::rcIndex(), Foam::reverse(), polyTopoChange::setAction(), UPtrList< T >::size(), UList< T >::size(), Foam::sqrt(), and Foam::meshTools::writeOBJ().
updateMesh()
void updateMesh (const mapPolyMesh &) inline
Definition at line 147 of file faceCollapser.H.
The documentation for this class was generated from the following files:
src/dynamicMesh/polyTopoChange/polyTopoChange/faceCollapser.H
src/dynamicMesh/polyTopoChange/polyTopoChange/faceCollapser.C