OpenFOAM: LarsenBorgnakkeVariableHardSphere< CloudType > Class Template Reference
LarsenBorgnakkeVariableHardSphere< CloudType > Class Template Reference
Variable Hard Sphere BinaryCollision Model with Larsen Borgnakke internal energy redistribution. Based on the INELRS subroutine in Bird's DSMC0R.FOR.
#include <LarsenBorgnakkeVariableHardSphere.H>
Public Member Functions
TypeName ("LarsenBorgnakkeVariableHardSphere")
LarsenBorgnakkeVariableHardSphere (const dictionary &dict, CloudType &cloud)
virtual ~LarsenBorgnakkeVariableHardSphere ()
virtual bool active () const
virtual scalar sigmaTcR (const typename CloudType::parcelType &pP, const typename CloudType::parcelType &pQ) const
virtual void collide (typename CloudType::parcelType &pP, typename CloudType::parcelType &pQ)
Public Member Functions inherited from BinaryCollisionModel< CloudType >
TypeName ("BinaryCollisionModel")
declareRunTimeSelectionTable (autoPtr, BinaryCollisionModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
BinaryCollisionModel (CloudType &owner)
BinaryCollisionModel (const dictionary &dict, CloudType &owner, const word &type)
virtual ~BinaryCollisionModel ()
const CloudType & owner () const
CloudType & owner ()
const dictionary & dict () const
const dictionary & coeffDict () const
Additional Inherited Members
Static Public Member Functions inherited from BinaryCollisionModel< CloudType >
static autoPtr< BinaryCollisionModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Detailed Description
template<class CloudType>
class Foam::LarsenBorgnakkeVariableHardSphere< CloudType >
Variable Hard Sphere BinaryCollision Model with Larsen Borgnakke internal energy redistribution. Based on the INELRS subroutine in Bird's DSMC0R.FOR.
Definition at line 42 of file LarsenBorgnakkeVariableHardSphere.H.
Constructor & Destructor Documentation
LarsenBorgnakkeVariableHardSphere()
template<class CloudType > LarsenBorgnakkeVariableHardSphere (const dictionary & dict, CloudType & cloud)
Definition at line 88 of file LarsenBorgnakkeVariableHardSphere.C.
~LarsenBorgnakkeVariableHardSphere()
template<class CloudType > ~LarsenBorgnakkeVariableHardSphere () virtual
Definition at line 107 of file LarsenBorgnakkeVariableHardSphere.C.
Member Function Documentation
TypeName()
template<class CloudType > TypeName ("LarsenBorgnakkeVariableHardSphere< CloudType >")
active()
template<class CloudType > bool active () const virtual
Implements BinaryCollisionModel< CloudType >.
Definition at line 115 of file LarsenBorgnakkeVariableHardSphere.C.
sigmaTcR()
template<class CloudType > Foam::scalar sigmaTcR (const typename CloudType::parcelType & pP, const typename CloudType::parcelType & pQ) const virtual
Implements BinaryCollisionModel< CloudType >.
Definition at line 122 of file LarsenBorgnakkeVariableHardSphere.C.
References Foam::exp(), Foam::lgamma(), Foam::mag(), Foam::constant::mathematical::pi(), and Foam::pow().
collide()
template<class CloudType > void collide (typename CloudType::parcelType & pP, typename CloudType::parcelType & pQ) virtual
Implements BinaryCollisionModel< CloudType >.
Definition at line 169 of file LarsenBorgnakkeVariableHardSphere.C.
References Foam::cos(), Foam::magSqr(), phi, Foam::pow(), rndGen, Random::sample01(), Foam::sin(), Foam::sqrt(), and Foam::constant::mathematical::twoPi().
The documentation for this class was generated from the following files:
src/lagrangian/DSMC/submodels/BinaryCollisionModel/LarsenBorgnakkeVariableHardSphere/LarsenBorgnakkeVariableHardSphere.H
src/lagrangian/DSMC/submodels/BinaryCollisionModel/LarsenBorgnakkeVariableHardSphere/LarsenBorgnakkeVariableHardSphere.C