OpenFOAM: shapeOptimisation Class Reference
shapeOptimisation Class Reference
Calculates shape sensitivities using the adjoint approach, computes boundaryMesh movement and propagates it to the volume mesh.
#include <shapeOptimisationIncompressible.H>
Public Member Functions
TypeName ("shapeOptimisation")
shapeOptimisation (fvMesh &mesh, const dictionary &dict, PtrList< adjointSolverManager > &adjointSolverManagers)
virtual ~shapeOptimisation ()=default
virtual void storeDesignVariables ()
virtual void resetDesignVariables ()
virtual void write ()
Public Member Functions inherited from optimisationType
TypeName ("optimisationType")
declareRunTimeSelectionTable (autoPtr, optimisationType, dictionary,(fvMesh &mesh, const dictionary &dict, PtrList< adjointSolverManager > &adjointSolverManagers),(mesh, dict, adjointSolverManagers))
optimisationType (fvMesh &mesh, const dictionary &dict, PtrList< adjointSolverManager > &adjointSolverManagers)
virtual ~optimisationType ()=default
virtual void update ()
virtual void update (scalarField &correction)
virtual tmp< scalarField > computeDirection ()
virtual void updateGradientsAndValues (scalarField &objectiveSens, PtrList< scalarField > &constraintSens, scalar &objectiveValue, scalarField &constraintValues)
virtual scalar computeMeritFunction ()
virtual scalar meritFunctionDirectionalDerivative ()
virtual void updateOldCorrection (const scalarField &)
const autoPtr< volScalarField > & sourcePtr ()
autoPtr< lineSearch > & getLineSearch ()
Protected Member Functions
virtual void updateDesignVariables (scalarField &correction)
virtual void computeEta (scalarField &correction)
Protected Attributes
autoPtr< optMeshMovement > optMeshMovement_
bool writeEachMesh_
bool updateGeometry_
Protected Attributes inherited from optimisationType
fvMesh & mesh_
const dictionary dict_
PtrList< adjointSolverManager > & adjointSolvManagers_
autoPtr< updateMethod > updateMethod_
autoPtr< volScalarField > sourcePtr_
autoPtr< lineSearch > lineSearch_
Additional Inherited Members
Static Public Member Functions inherited from optimisationType
static autoPtr< optimisationType > New (fvMesh &mesh, const dictionary &dict, PtrList< adjointSolverManager > &adjointSolverManagers)
Detailed Description
Calculates shape sensitivities using the adjoint approach, computes boundaryMesh movement and propagates it to the volume mesh.
Source files
shapeOptimisationIncompressible.H
shapeOptimisation.C
Definition at line 59 of file shapeOptimisationIncompressible.H.
Constructor & Destructor Documentation
shapeOptimisation()
shapeOptimisation (fvMesh & mesh, const dictionary & dict, PtrList< adjointSolverManager > & adjointSolverManagers)
Definition at line 112 of file shapeOptimisationIncompressible.C.
References polyMesh::boundaryMesh(), optimisationType::dict_, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, UPtrList< T >::get(), optimisationType::mesh_, optMeshMovement::New(), Foam::nl, shapeOptimisation::optMeshMovement_, patches, optimisationType::updateMethod_, and WarningInFunction.
~shapeOptimisation()
virtual ~shapeOptimisation () virtual default
Member Function Documentation
updateDesignVariables()
void updateDesignVariables (scalarField & correction) protected virtual
Implements optimisationType.
Definition at line 46 of file shapeOptimisationIncompressible.C.
References Foam::correction(), Foam::endl(), Foam::Info, optimisationType::mesh_, polyMesh::meshSubDir, IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, shapeOptimisation::optMeshMovement_, points, polyMesh::points(), polyMesh::pointsInstance(), shapeOptimisation::updateGeometry_, and shapeOptimisation::writeEachMesh_.
computeEta()
void computeEta (scalarField & correction) protected virtual
Implements optimisationType.
Definition at line 79 of file shapeOptimisationIncompressible.C.
References Foam::correction(), shapeOptimisation::optMeshMovement_, and optimisationType::updateMethod_.
TypeName()
TypeName ("shapeOptimisation")
storeDesignVariables()
void storeDesignVariables () virtual
Implements optimisationType.
Definition at line 176 of file shapeOptimisationIncompressible.C.
References shapeOptimisation::optMeshMovement_.
resetDesignVariables()
void resetDesignVariables () virtual
Implements optimisationType.
Definition at line 182 of file shapeOptimisationIncompressible.C.
References shapeOptimisation::optMeshMovement_.
write()
void write () virtual
Reimplemented from optimisationType.
Definition at line 188 of file shapeOptimisationIncompressible.C.
References optimisationType::updateMethod_, and optimisationType::write().
Member Data Documentation
optMeshMovement_
autoPtr<optMeshMovement> optMeshMovement_ protected
Definition at line 67 of file shapeOptimisationIncompressible.H.
Referenced by shapeOptimisation::computeEta(), shapeOptimisation::resetDesignVariables(), shapeOptimisation::shapeOptimisation(), shapeOptimisation::storeDesignVariables(), and shapeOptimisation::updateDesignVariables().
writeEachMesh_
bool writeEachMesh_ protected
Definition at line 69 of file shapeOptimisationIncompressible.H.
Referenced by shapeOptimisation::updateDesignVariables().
updateGeometry_
bool updateGeometry_ protected
Definition at line 70 of file shapeOptimisationIncompressible.H.
Referenced by shapeOptimisation::updateDesignVariables().
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/optimisation/optimisationType/incompressible/shapeOptimisation/shapeOptimisationIncompressible.H
src/optimisation/adjointOptimisation/adjoint/optimisation/optimisationType/incompressible/shapeOptimisation/shapeOptimisationIncompressible.C