OpenFOAM: APIdiffCoefFunc Class Reference
APIdiffCoefFunc Class Reference
API function for vapour mass diffusivity.
#include <APIdiffCoefFunc.H>
Public Member Functions
TypeName ("APIdiffCoefFunc")
APIdiffCoefFunc (const scalar a, const scalar b, const scalar wf, const scalar wa)
APIdiffCoefFunc (const dictionary &dict)
scalar f (scalar p, scalar T) const
scalar f (scalar p, scalar T, scalar Wa) const
void writeData (Ostream &os) const
Public Member Functions inherited from thermophysicalFunction
TypeName ("thermophysicalFunction")
declareRunTimeSelectionTable (autoPtr, thermophysicalFunction, Istream,(Istream &is),(is))
declareRunTimeSelectionTable (autoPtr, thermophysicalFunction, dictionary,(const dictionary &dict),(dict))
thermophysicalFunction ()
virtual ~thermophysicalFunction ()=default
Friends
Ostream & operator<< (Ostream &os, const APIdiffCoefFunc &f)
Additional Inherited Members
Static Public Member Functions inherited from thermophysicalFunction
static autoPtr< thermophysicalFunction > New (Istream &is)
static autoPtr< thermophysicalFunction > New (const dictionary &dict)
Detailed Description
API function for vapour mass diffusivity.
Source:
        API (American Petroleum Institute)
                Technical Data Book
Definition at line 47 of file APIdiffCoefFunc.H.
Constructor & Destructor Documentation
APIdiffCoefFunc() [1/2]
APIdiffCoefFunc (const scalar a, const scalar b, const scalar wf, const scalar wa)
Definition at line 39 of file APIdiffCoefFunc.C.
References Foam::cbrt(), Foam::sqr(), and Foam::sqrt().
APIdiffCoefFunc() [2/2]
APIdiffCoefFunc (const dictionary & dict)
Definition at line 56 of file APIdiffCoefFunc.C.
Member Function Documentation
TypeName()
TypeName ("APIdiffCoefFunc")
f() [1/2]
scalar f (scalar p, scalar T) const inline virtual
Implements thermophysicalFunction.
Definition at line 85 of file APIdiffCoefFunc.H.
References p, Foam::pow(), and T.
f() [2/2]
scalar f (scalar p, scalar T, scalar Wa) const inline
Definition at line 92 of file APIdiffCoefFunc.H.
References p, Foam::pow(), Foam::sqrt(), and T.
writeData()
void writeData (Ostream & os) const inline virtual
Implements thermophysicalFunction.
Definition at line 99 of file APIdiffCoefFunc.H.
References os(), and token::SPACE.
Friends And Related Symbol Documentation
operator<<
Ostream & operator<< (Ostream & os, const APIdiffCoefFunc & f) friend
Definition at line 110 of file APIdiffCoefFunc.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/thermophysicalProperties/thermophysicalFunctions/APIfunctions/APIdiffCoefFunc/APIdiffCoefFunc.H
src/thermophysicalModels/thermophysicalProperties/thermophysicalFunctions/APIfunctions/APIdiffCoefFunc/APIdiffCoefFunc.C