OpenFOAM: perturbedTemperatureDependentContactAngleForce Class Reference
perturbedTemperatureDependentContactAngleForce Class Reference
Temperature dependent contact angle force with a stochastic perturbation.
#include <perturbedTemperatureDependentContactAngleForce.H>
Public Member Functions
TypeName ("perturbedTemperatureDependentContactAngle")
perturbedTemperatureDependentContactAngleForce (surfaceFilmRegionModel &film, const dictionary &dict)
virtual ~perturbedTemperatureDependentContactAngleForce ()
Public Member Functions inherited from contactAngleForce
TypeName ("contactAngle")
contactAngleForce (const word &typeName, surfaceFilmRegionModel &film, const dictionary &dict)
virtual ~contactAngleForce ()
virtual tmp< fvVectorMatrix > correct (volVectorField &U)
Public Member Functions inherited from force
TypeName ("force")
declareRunTimeSelectionTable (autoPtr, force, dictionary,(surfaceFilmRegionModel &film, const dictionary &dict),(film, dict))
force (surfaceFilmRegionModel &film)
force (const word &modelType, surfaceFilmRegionModel &film, const dictionary &dict)
virtual ~force ()
Public Member Functions inherited from filmSubModelBase
filmSubModelBase (surfaceFilmRegionModel &film)
filmSubModelBase (surfaceFilmRegionModel &film, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
filmSubModelBase (const word &modelName, surfaceFilmRegionModel &film, const dictionary &dict, const word &baseName, const word &modelType)
virtual ~filmSubModelBase ()
virtual bool writeTime () const
const surfaceFilmRegionModel & film () const
surfaceFilmRegionModel & film ()
template<class FilmType >
const FilmType & filmType () const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
subModelBase (const subModelBase &smb)
virtual ~subModelBase ()=default
const word & modelName () const
const dictionary & dict () const
const word & baseName () const
const word & modelType () const
const dictionary & coeffDict () const
const dictionary & properties () const
virtual bool defaultCoeffs (const bool printMsg) const
virtual bool active () const
virtual void cacheFields (const bool store)
virtual fileName localPath () const
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
bool getModelDict (const word &entryName, dictionary &dict) const
template<class Type >
bool getModelProperty (const word &entryName, Type &value) const
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
virtual void write (Ostream &os) const
Protected Member Functions
virtual tmp< volScalarField > theta () const
Protected Member Functions inherited from subModelBase
bool inLine () const
Additional Inherited Members
Static Public Member Functions inherited from force
static autoPtr< force > New (surfaceFilmRegionModel &film, const dictionary &dict, const word &modelType)
Public Attributes inherited from subModelBase
bool log
Protected Attributes inherited from filmSubModelBase
surfaceFilmRegionModel & filmModel_
Protected Attributes inherited from subModelBase
const word modelName_
dictionary & properties_
const dictionary dict_
const word baseName_
const word modelType_
const dictionary coeffDict_
Detailed Description
Temperature dependent contact angle force with a stochastic perturbation.
The contact angle in degrees is specified as a Foam::Function1 type, to enable the use of, e.g. constant, polynomial, table values and the stochastic perturbation obtained from a Foam::distributionModels::distributionModel
See also
Foam::regionModels::surfaceFilmModels::contactAngleForce Foam::regionModels::surfaceFilmModels::temperatureDependentContactAngleForce Foam::regionModels::surfaceFilmModels::distributionContactAngleForce Foam::Function1Types Foam::distributionModel
Source files
perturbedTemperatureDependentContactAngleForce.H
perturbedTemperatureDependentContactAngleForce.C
Definition at line 65 of file perturbedTemperatureDependentContactAngleForce.H.
Constructor & Destructor Documentation
perturbedTemperatureDependentContactAngleForce()
perturbedTemperatureDependentContactAngleForce (surfaceFilmRegionModel & film, const dictionary & dict)
Definition at line 46 of file perturbedTemperatureDependentContactAngleForce.C.
~perturbedTemperatureDependentContactAngleForce()
~perturbedTemperatureDependentContactAngleForce () virtual
Definition at line 69 of file perturbedTemperatureDependentContactAngleForce.C.
Member Function Documentation
theta()
tmp< volScalarField > theta () const protected virtual
Implements contactAngleForce.
Definition at line 77 of file perturbedTemperatureDependentContactAngleForce.C.
References Foam::dimless, filmSubModelBase::filmModel_, forAll, regionModel::isCoupledPatch(), regionModel::regionMesh(), T, surfaceFilmRegionModel::T(), perturbedTemperatureDependentContactAngleForce::theta(), regionModel::time(), and Foam::Zero.
Referenced by perturbedTemperatureDependentContactAngleForce::theta().
TypeName()
TypeName ("perturbedTemperatureDependentContactAngle")
The documentation for this class was generated from the following files:
src/regionModels/surfaceFilmModels/submodels/kinematic/force/contactAngleForces/perturbedTemperatureDependent/perturbedTemperatureDependentContactAngleForce.H
src/regionModels/surfaceFilmModels/submodels/kinematic/force/contactAngleForces/perturbedTemperatureDependent/perturbedTemperatureDependentContactAngleForce.C