OpenFOAM: meshToMeshMethod Class Reference
meshToMeshMethod Class Reference abstract
Base class for mesh-to-mesh calculation methods.
#include <meshToMeshMethod.H>
Public Member Functions
TypeName ("meshToMeshMethod")
declareRunTimeSelectionTable (autoPtr, meshToMeshMethod, components,(const polyMesh &src, const polyMesh &tgt),(src, tgt))
meshToMeshMethod (const polyMesh &src, const polyMesh &tgt)
virtual ~meshToMeshMethod ()
virtual void calculate (labelListList &srcToTgtAddr, scalarListList &srcToTgtWght, pointListList &srcToTgtVec, labelListList &tgtToSrcAddr, scalarListList &tgtToSrcWght, pointListList &tgtToSrcVec)=0
const polyMesh & src () const
const polyMesh & tgt () const
scalar V () const
void writeConnectivity (const polyMesh &mesh1, const polyMesh &mesh2, const labelListList &mesh1ToMesh2Addr) const
Static Public Member Functions
static autoPtr< meshToMeshMethod > New (const word &methodName, const polyMesh &src, const polyMesh &tgt)
Protected Member Functions
labelList maskCells () const
virtual bool intersect (const label srcCelli, const label tgtCelli) const
virtual scalar interVol (const label srcCelli, const label tgtCelli) const
virtual Tuple2< scalar, point > interVolAndCentroid (const label srcCellI, const label tgtCellI)
virtual void appendNbrCells (const label tgtCelli, const polyMesh &mesh, const DynamicList< label > &visitedTgtCells, DynamicList< label > &nbrTgtCellIDs) const
virtual bool initialise (labelListList &srcToTgtAddr, scalarListList &srcToTgtWght, labelListList &tgtToTgtAddr, scalarListList &tgtToTgtWght) const
Protected Attributes
const polyMesh & src_
const polyMesh & tgt_
scalar V_
Static Protected Attributes
static scalar tolerance_ = 1e-6
Detailed Description
Base class for mesh-to-mesh calculation methods.
Source files
meshToMeshMethod.H
meshToMeshMethod.C
Definition at line 47 of file meshToMeshMethod.H.
Constructor & Destructor Documentation
meshToMeshMethod()
meshToMeshMethod (const polyMesh & src, const polyMesh & tgt)
Definition at line 204 of file meshToMeshMethod.C.
References Foam::endl(), Foam::Pout, meshToMeshMethod::src_, and meshToMeshMethod::tgt_.
~meshToMeshMethod()
~meshToMeshMethod () virtual
Definition at line 228 of file meshToMeshMethod.C.
Member Function Documentation
maskCells()
Foam::labelList maskCells () const protected
Definition at line 40 of file meshToMeshMethod.C.
References cells, Foam::endl(), boundBox::inflate(), boundBox::overlaps(), Foam::Pout, meshToMeshMethod::src_, and meshToMeshMethod::tgt_.
intersect()
bool intersect (const label srcCelli, const label tgtCelli) const protected virtual
Reimplemented in directMethod.
Definition at line 66 of file meshToMeshMethod.C.
Referenced by cellVolumeWeightMethod::findInitialSeeds().
interVol()
Foam::scalar interVol (const label srcCelli, const label tgtCelli) const protected virtual
Definition at line 90 of file meshToMeshMethod.C.
interVolAndCentroid()
Foam::Tuple2< Foam::scalar, Foam::point > interVolAndCentroid (const label srcCellI, const label tgtCellI) protected virtual
Definition at line 114 of file meshToMeshMethod.C.
References UPtrList< T >::first(), and Foam::Zero.
Referenced by correctedCellVolumeWeightMethod::calculateAddressing().
appendNbrCells()
void appendNbrCells (const label tgtCelli, const polyMesh & mesh, const DynamicList< label > & visitedTgtCells, DynamicList< label > & nbrTgtCellIDs) const protected virtual
Definition at line 149 of file meshToMeshMethod.C.
References primitiveMesh::cellCells(), and mesh.
Referenced by correctedCellVolumeWeightMethod::calculateAddressing().
initialise()
bool initialise (labelListList & srcToTgtAddr, scalarListList & srcToTgtWght, labelListList & tgtToTgtAddr, scalarListList & tgtToTgtWght) const protected virtual
Definition at line 170 of file meshToMeshMethod.C.
References Foam::endl(), Foam::Pout, and PtrList< T >::setSize().
TypeName()
TypeName ("meshToMeshMethod")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , meshToMeshMethod , components , (const polyMesh &src, const polyMesh &tgt) , (src, tgt))
New()
Foam::autoPtr< Foam::meshToMeshMethod > New (const word & methodName, const polyMesh & src, const polyMesh & tgt) static
Definition at line 26 of file meshToMeshMethodNew.C.
References DebugInfo, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInLookup, meshToMeshMethod::src(), and meshToMeshMethod::tgt().
calculate()
virtual void calculate (labelListList & srcToTgtAddr, scalarListList & srcToTgtWght, pointListList & srcToTgtVec, labelListList & tgtToSrcAddr, scalarListList & tgtToSrcWght, pointListList & tgtToSrcVec) pure virtual
Implemented in waveMethod, cellVolumeWeightMethod, correctedCellVolumeWeightMethod, directMethod, and mapNearestMethod.
src()
const Foam::polyMesh & src () const inline
Definition at line 21 of file meshToMeshMethodI.H.
References meshToMeshMethod::src_.
Referenced by waveMethod::calculate(), and meshToMeshMethod::New().
tgt()
const Foam::polyMesh & tgt () const inline
Definition at line 27 of file meshToMeshMethodI.H.
Referenced by waveMethod::calculate(), and meshToMeshMethod::New().
V()
Foam::scalar V () const inline
Definition at line 33 of file meshToMeshMethodI.H.
writeConnectivity()
void writeConnectivity (const polyMesh & mesh1, const polyMesh & mesh2, const labelListList & mesh1ToMesh2Addr) const
Definition at line 234 of file meshToMeshMethod.C.
References Foam::endl(), forAll, UPstream::myProcNo(), Foam::name(), Foam::nl, os(), p, UPstream::parRun(), Foam::Pout, and pts.
Member Data Documentation
src_
const polyMesh& src_ protected
Definition at line 55 of file meshToMeshMethod.H.
Referenced by correctedCellVolumeWeightMethod::calculateAddressing(), cellVolumeWeightMethod::findInitialSeeds(), mapNearestMethod::findInitialSeeds(), directMethod::intersect(), meshToMeshMethod::maskCells(), meshToMeshMethod::meshToMeshMethod(), and meshToMeshMethod::src().
tgt_
const polyMesh& tgt_ protected
Definition at line 58 of file meshToMeshMethod.H.
Referenced by correctedCellVolumeWeightMethod::calculateAddressing(), cellVolumeWeightMethod::findInitialSeeds(), mapNearestMethod::findInitialSeeds(), directMethod::intersect(), meshToMeshMethod::maskCells(), and meshToMeshMethod::meshToMeshMethod().
V_
scalar V_ protected
Definition at line 61 of file meshToMeshMethod.H.
Referenced by correctedCellVolumeWeightMethod::calculateAddressing().
tolerance_
Foam::scalar tolerance_ = 1e-6 static protected
Definition at line 64 of file meshToMeshMethod.H.
Referenced by correctedCellVolumeWeightMethod::calculateAddressing().
The documentation for this class was generated from the following files:
src/sampling/meshToMesh/calcMethod/meshToMeshMethod/meshToMeshMethod.H
src/sampling/meshToMesh/calcMethod/meshToMeshMethod/meshToMeshMethod.C
src/sampling/meshToMesh/calcMethod/meshToMeshMethod/meshToMeshMethodI.H
src/sampling/meshToMesh/calcMethod/meshToMeshMethod/meshToMeshMethodNew.C