OpenFOAM: memInfo Class Reference
memInfo Class Reference
Memory usage information for the current process, and the system memory that is free.
#include <memInfo.H>
Public Member Functions
memInfo ()
~memInfo ()=default
bool good () const noexcept
void clear () noexcept
const memInfo & update ()
int peak () const noexcept
int size () const noexcept
int rss () const noexcept
int free () const noexcept
void write (Ostream &os) const
bool valid () const noexcept
Friends
Istream & operator>> (Istream &is, memInfo &m)
Ostream & operator<< (Ostream &os, const memInfo &m)
Detailed Description
Memory usage information for the current process, and the system memory that is free.
Note
Uses the information from /proc/PID/status and from /proc/meminfo
Source files
memInfo.H
memInfo.C
Definition at line 58 of file memInfo.H.
Constructor & Destructor Documentation
memInfo()
memInfo ()
Definition at line 31 of file memInfo.C.
References memInfo::update().
~memInfo()
~memInfo () default
Member Function Documentation
good()
bool good () const noexcept
Definition at line 44 of file memInfo.C.
Referenced by memInfo::valid().
clear()
void clear () noexcept
Definition at line 50 of file memInfo.C.
update()
const Foam::memInfo & update ()
Definition at line 57 of file memInfo.C.
References clear(), and Foam::pid().
Referenced by memInfo::memInfo().
peak()
int peak () const inline noexcept
Definition at line 99 of file memInfo.H.
size()
int size () const inline noexcept
Definition at line 102 of file memInfo.H.
Referenced by indexedOctree< Type >::indexedOctree().
rss()
int rss () const inline noexcept
Definition at line 105 of file memInfo.H.
free()
int free () const inline noexcept
Definition at line 108 of file memInfo.H.
write()
void write (Ostream & os) const
Definition at line 154 of file memInfo.C.
References os(), and Ostream::writeEntry().
valid()
bool valid () const inline noexcept
Definition at line 129 of file memInfo.H.
References memInfo::good().
Friends And Related Symbol Documentation
operator>>
Istream & operator>> (Istream & is, memInfo & m) friend
operator<<
Ostream & operator<< (Ostream & os, const memInfo & m) friend
The documentation for this class was generated from the following files:
src/OSspecific/POSIX/memInfo/memInfo.H
src/OSspecific/POSIX/memInfo/memInfo.C