OpenFOAM: refineCell Class Reference
refineCell Class Reference
Container with cells to refine. Refinement given as single direction.
#include <refineCell.H>
Public Member Functions
refineCell ()
refineCell (const label celli, const vector &direction)
refineCell (Istream &is)
label cellNo () const
const vector & direction () const
Friends
bool operator== (const refineCell &rc1, const refineCell &rc2)
bool operator!= (const refineCell &rc1, const refineCell &rc2)
Ostream & operator<< (Ostream &, const refineCell &)
Detailed Description
Container with cells to refine. Refinement given as single direction.
Source files
refineCell.H
refineCell.C
Definition at line 52 of file refineCell.H.
Constructor & Destructor Documentation
refineCell() [1/3]
refineCell ()
Definition at line 27 of file refineCell.C.
refineCell() [2/3]
refineCell (const label celli, const vector & direction)
Definition at line 34 of file refineCell.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and Foam::mag().
refineCell() [3/3]
refineCell (Istream & is) explicit
Definition at line 55 of file refineCell.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and Foam::mag().
Member Function Documentation
cellNo()
label cellNo () const inline
Definition at line 79 of file refineCell.H.
Referenced by Foam::operator<<(), refinementIterator::setRefinement(), and edgeVertex::updateLabels().
direction()
const vector & direction () const inline
Definition at line 84 of file refineCell.H.
Referenced by Foam::operator<<(), refinementIterator::setRefinement(), and edgeVertex::updateLabels().
Friends And Related Symbol Documentation
operator==
bool operator== (const refineCell & rc1, const refineCell & rc2) friend
Definition at line 92 of file refineCell.H.
operator!=
bool operator!= (const refineCell & rc1, const refineCell & rc2) friend
Definition at line 101 of file refineCell.H.
operator<<
Ostream & operator<< (Ostream & , const refineCell &) friend
The documentation for this class was generated from the following files:
src/dynamicMesh/meshCut/refineCell/refineCell.H
src/dynamicMesh/meshCut/refineCell/refineCell.C