OpenFOAM: doubleSigmoid Class Reference
doubleSigmoid Class Reference
#include <doubleSigmoid.H>
Public Member Functions
TypeName ("doubleSigmoid")
doubleSigmoid (const word &name, const dictionary &energyScalingFunctionProperties, const pairPotential &pairPot)
~doubleSigmoid ()
void scaleEnergy (scalar &e, const scalar r) const
bool read (const dictionary &energyScalingFunctionProperties)
Public Member Functions inherited from energyScalingFunction
TypeName ("energyScalingFunction")
declareRunTimeSelectionTable (autoPtr, energyScalingFunction, dictionary,(const word &name, const dictionary &energyScalingFunctionProperties, const pairPotential &pairPot),(name, energyScalingFunctionProperties, pairPot))
energyScalingFunction (const word &name, const dictionary &energyScalingFunctionProperties, const pairPotential &pairPot)
virtual ~energyScalingFunction ()=default
const dictionary & energyScalingFunctionProperties () const
Additional Inherited Members
Static Public Member Functions inherited from energyScalingFunction
static autoPtr< energyScalingFunction > New (const word &name, const dictionary &energyScalingFunctionProperties, const pairPotential &pairPot)
Protected Member Functions inherited from energyScalingFunction
energyScalingFunction (const energyScalingFunction &)=delete
void operator= (const energyScalingFunction &)=delete
Protected Attributes inherited from energyScalingFunction
word name_
dictionary energyScalingFunctionProperties_
const pairPotential & pairPot_
Detailed Description
Source files
doubleSigmoid.H
doubleSigmoid.C
Definition at line 48 of file doubleSigmoid.H.
Constructor & Destructor Documentation
doubleSigmoid()
doubleSigmoid (const word & name, const dictionary & energyScalingFunctionProperties, const pairPotential & pairPot)
Definition at line 57 of file doubleSigmoid.C.
~doubleSigmoid()
~doubleSigmoid () inline
Definition at line 90 of file doubleSigmoid.H.
Member Function Documentation
TypeName()
TypeName ("doubleSigmoid")
scaleEnergy()
void scaleEnergy (scalar & e, const scalar r) const virtual
Implements energyScalingFunction.
Definition at line 78 of file doubleSigmoid.C.
References e.
read()
bool read (const dictionary & energyScalingFunctionProperties) virtual
Implements energyScalingFunction.
Definition at line 84 of file doubleSigmoid.C.
References energyScalingFunction::energyScalingFunctionProperties(), energyScalingFunction::read(), and dictionary::readEntry().
The documentation for this class was generated from the following files:
src/lagrangian/molecularDynamics/potential/energyScalingFunction/derived/doubleSigmoid/doubleSigmoid.H
src/lagrangian/molecularDynamics/potential/energyScalingFunction/derived/doubleSigmoid/doubleSigmoid.C