OpenFOAM: HashTable< T, Key, Hash > Class Template Reference
HashTable< T, Key, Hash > Class Template Reference
A HashTable similar to std::unordered_map.
#include <HashTable.H>
Inherits HashTableCore.
Inherited by EdgeMap< Foam::List >, EdgeMap< label >, EdgeMap< scalar >, HashPtrTable< IOobject >, HashPtrTable< T, label, Hash< label > >, HashPtrTable< exprResult >, HashPtrTable< curve >, HashPtrTable< HashPtrTable< volScalarField >, phasePairKey, phasePairKey::hash >, HashPtrTable< volScalarField, phasePairKey, phasePairKey::hash >, HashPtrTable< surfaceScalarField, phasePairKey, phasePairKey::hash >, HashPtrTable< Foam::GeometricField >, HashPtrTable< ThermoType >, HashPtrTable< Foam::GeometricField, Foam::phasePairKey, Foam::phasePairKey::hasher >, HashPtrTable< Foam::surfaceWriter >, HashPtrTable< Foam::sutherlandTransport >, HashPtrTable< Foam::colourTable >, HashPtrTable< Foam::coordSystem::cylindrical, label, Hash< label > >, HashPtrTable< Foam::DynamicList< Foam::instant > >, HashPtrTable< Foam::Function1< Type > >, HashPtrTable< Foam::Function1< scalar > >, HashPtrTable< Foam::expressions::volumeExpr::parseDriver >, HashPtrTable< Foam::Field >, HashPtrTable< Foam::lumpedPointController >, HashPtrTable< multiphaseEuler::dragModel, interfacePair, interfacePair::symmHash >, HashPtrTable< Foam::OFstream >, HashSet< labelPairPair >, HashSet< Foam::string >, HashSet< label, Hash< label > >, HashSet< word, Hash< word > >, HashSet< edge, Hash< edge > >, HashSet< Foam::fileName >, Map< dictionary >, Map< interfaceEntry >, Map< label >, Map< Foam::edge >, Map< Foam::Vector >, Map< scalar >, Map< Foam::ensightCells >, Map< Foam::ensightFaces >, Map< Foam::FixedList< int, 6 > >, Map< patchControl >, Map< Foam::splitCell * >, HashPtrTable< T, Key, Hash >, and HashSet< Key, Hash >.
Classes
class const_iterator
class Iterator
class iterator
class key_iterator_base
Public Types
typedef HashTable< T, Key, Hash > this_type
typedef std::conditional< std::is_same< Foam::zero, typenamestd::remove_cv< T >::type >::value, Detail::HashTableSingle< Key >, Detail::HashTablePair< Key, T > >::type node_type
typedef Key key_type
typedef T mapped_type
typedef T value_type
typedef Hash hasher
typedef T * pointer
typedef T & reference
typedef const T * const_pointer
typedef const T & const_reference
typedef label difference_type
typedef label size_type
using key_iterator = key_iterator_base< iterator >
using const_key_iterator = key_iterator_base< const_iterator >
Public Member Functions
HashTable ()
HashTable (const label size)
HashTable (Istream &is, const label size=128)
HashTable (const this_type &ht)
HashTable (this_type &&rhs)
HashTable (std::initializer_list< std::pair< Key, T > > list)
~HashTable ()
bool empty () const noexcept
label size () const noexcept
label capacity () const noexcept
T & at (const Key &key)
const T & at (const Key &key) const
bool contains (const Key &key) const
iterator find (const Key &key)
const_iterator find (const Key &key) const
const_iterator cfind (const Key &key) const
const T & lookup (const Key &key, const T &deflt) const
List< Key > toc () const
List< Key > sortedToc () const
template<class Compare >
List< Key > sortedToc (const Compare &comp) const
template<class UnaryPredicate >
List< Key > tocKeys (const UnaryPredicate &pred, const bool invert=false) const
template<class UnaryPredicate >
List< Key > tocValues (const UnaryPredicate &pred, const bool invert=false) const
template<class BinaryPredicate >
List< Key > tocEntries (const BinaryPredicate &pred, const bool invert=false) const
UPtrList< const node_type > csorted () const
UPtrList< const node_type > sorted () const
UPtrList< node_type > sorted ()
template<class UnaryPredicate >
label countKeys (const UnaryPredicate &pred, const bool invert=false) const
template<class UnaryPredicate >
label countValues (const UnaryPredicate &pred, const bool invert=false) const
template<class BinaryPredicate >
label countEntries (const BinaryPredicate &pred, const bool invert=false) const
template<class... Args>
bool emplace (const Key &key, Args &&... args)
template<class... Args>
bool emplace_set (const Key &key, Args &&... args)
bool insert (const Key &key, const T &obj)
bool insert (const Key &key, T &&obj)
bool set (const Key &key, const T &obj)
bool set (const Key &key, T &&obj)
bool erase (const iterator &iter)
bool erase (const Key &key)
template<class AnyType , class AnyHash >
label erase (const HashTable< AnyType, Key, AnyHash > &other)
label erase (std::initializer_list< Key > keys)
template<class InputIter >
label erase (InputIter first, InputIter last)
template<unsigned N>
label erase (const FixedList< Key, N > &keys)
label erase (const UList< Key > &keys)
template<class AnyType , class AnyHash >
label retain (const HashTable< AnyType, Key, AnyHash > &other)
template<class UnaryPredicate >
label filterKeys (const UnaryPredicate &pred, const bool pruning=false)
template<class UnaryPredicate >
label filterValues (const UnaryPredicate &pred, const bool pruning=false)
template<class BinaryPredicate >
label filterEntries (const BinaryPredicate &pred, const bool pruning=false)
void resize (const label sz)
void clear ()
void clearStorage ()
void swap (HashTable< T, Key, Hash > &rhs)
void transfer (HashTable< T, Key, Hash > &rhs)
void merge (HashTable< T, Key, Hash > &source)
void merge (HashTable< T, Key, Hash > &&source)
T & operator[] (const Key &key)
const T & operator[] (const Key &key) const
T & operator() (const Key &key)
T & operator() (const Key &key, const T &deflt)
void operator= (const this_type &rhs)
void operator= (std::initializer_list< std::pair< Key, T > > rhs)
void operator= (this_type &&rhs)
bool operator== (const this_type &rhs) const
bool operator!= (const this_type &rhs) const
this_type & operator+= (const this_type &rhs)
const_iterator_pair< const_key_iterator, this_type > keys () const
iterator begin ()
const_iterator begin () const
const_iterator cbegin () const
iterator end () noexcept
const_iterator end () const noexcept
constexpr const_iterator cend () const noexcept
Ostream & printInfo (Ostream &os) const
Ostream & writeKeys (Ostream &os, const label shortLen=0) const
bool found (const Key &key) const
template<class Compare >
Foam::List< Key > sortedToc (const Compare &comp) const
template<class UnaryPredicate >
Foam::List< Key > tocKeys (const UnaryPredicate &pred, const bool invert) const
template<class UnaryPredicate >
Foam::List< Key > tocValues (const UnaryPredicate &pred, const bool invert) const
template<class BinaryPredicate >
Foam::List< Key > tocEntries (const BinaryPredicate &pred, const bool invert) const
template<class UnaryPredicate >
Foam::label countKeys (const UnaryPredicate &pred, const bool invert) const
template<class UnaryPredicate >
Foam::label countValues (const UnaryPredicate &pred, const bool invert) const
template<class BinaryPredicate >
Foam::label countEntries (const BinaryPredicate &pred, const bool invert) const
template<class InputIter >
Foam::label erase (InputIter first, InputIter last)
template<unsigned N>
Foam::label erase (const FixedList< Key, N > &keys)
template<class AnyType , class AnyHash >
Foam::label erase (const HashTable< AnyType, Key, AnyHash > &other)
template<class AnyType , class AnyHash >
Foam::label retain (const HashTable< AnyType, Key, AnyHash > &other)
template<class UnaryPredicate >
Foam::label filterKeys (const UnaryPredicate &pred, const bool pruning)
template<class UnaryPredicate >
Foam::label filterValues (const UnaryPredicate &pred, const bool pruning)
template<class BinaryPredicate >
Foam::label filterEntries (const BinaryPredicate &pred, const bool pruning)
Public Member Functions inherited from HashTableCore
ClassName ("HashTable")
HashTableCore () noexcept=default
Friends
class Iterator< true >
class Iterator< false >
Istream & operator>> (Istream &, HashTable< T, Key, Hash > &tbl)
Ostream & operator (Ostream &, const HashTable< T, Key, Hash > &tbl)
Additional Inherited Members
Static Public Member Functions inherited from HashTableCore
static label canonicalSize (const label requested_size)
Static Public Attributes inherited from HashTableCore
static const label maxTableSize
Detailed Description
template<class T, class Key = word, class Hash = Foam::Hash<Key>>
class Foam::HashTable< T, Key, Hash >
A HashTable similar to std::unordered_map.
The entries are considered unordered since their placement depends on the method used to generate the hash key index, the table capacity, insertion order etc. When the key order is important, use the sortedToc() method to obtain a list of sorted keys and use that for further access, or the sorted() method to obtain a UPtrList of entries to traverse in sorted order.
Internally the table uses closed addressing into a flat storage space with collisions handled by linked-list chaining.
The end iterator of all hash-tables has a nullptr to the hash entry. Thus avoid separate allocation for each table and use a single one with a nullptr. The hash-table iterators always have an entry-pointer as the first member data, which allows reinterpret_cast from anything else with a nullptr as its first data member. The nullObject is such an item (with a nullptr data member).
Note
For historical reasons, dereferencing the table iterator (eg, *iter) returns a reference to the stored object value rather than the stored key/val pair like std::unordered_map does.
The HashTable iterator:
forAllConstIters(table, iter)
{
    Info<< "val:" << *iter << nl
        << "key:" << iter.key() << nl
        << "val:" << iter.val() << nl;
}
whereas for the std::unordered_map iterator:
forAllConstIters(stdmap, iter)
{
    Info<< "key/val:" << *iter << nl
        << "key:" << iter->first << nl
        << "val:" << iter->second << nl;
}
This difference is most evident when using range-for syntax.
Source files
HashTable.H
HashTableI.H
HashTableIterI.H
HashTable.C
HashTableIO.C
HashTableIter.C
Definition at line 115 of file HashTable.H.
Member Typedef Documentation
this_type
template<class T , class Key = word, class Hash = Foam::Hash<Key>> typedef HashTable<T, Key, Hash> this_type
Definition at line 124 of file HashTable.H.
node_type
template<class T , class Key = word, class Hash = Foam::Hash<Key>> typedef std::conditional<std::is_same<Foam::zero,typenamestd::remove_cv<T>::type>::value,Detail::HashTableSingle<Key>,Detail::HashTablePair<Key,T>>::type node_type
Definition at line 133 of file HashTable.H.
key_type
template<class T , class Key = word, class Hash = Foam::Hash<Key>> typedef Key key_type
Definition at line 139 of file HashTable.H.
mapped_type
template<class T , class Key = word, class Hash = Foam::Hash<Key>> typedef T mapped_type
Definition at line 142 of file HashTable.H.
value_type
template<class T , class Key = word, class Hash = Foam::Hash<Key>> typedef T value_type
Definition at line 146 of file HashTable.H.
hasher
template<class T , class Key = word, class Hash = Foam::Hash<Key>> typedef Hash hasher
Definition at line 149 of file HashTable.H.
pointer
template<class T , class Key = word, class Hash = Foam::Hash<Key>> typedef T* pointer
Definition at line 153 of file HashTable.H.
reference
template<class T , class Key = word, class Hash = Foam::Hash<Key>> typedef T& reference
Definition at line 157 of file HashTable.H.
const_pointer
template<class T , class Key = word, class Hash = Foam::Hash<Key>> typedef const T* const_pointer
Definition at line 160 of file HashTable.H.
const_reference
template<class T , class Key = word, class Hash = Foam::Hash<Key>> typedef const T& const_reference
Definition at line 163 of file HashTable.H.
difference_type
template<class T , class Key = word, class Hash = Foam::Hash<Key>> typedef label difference_type
Definition at line 166 of file HashTable.H.
size_type
template<class T , class Key = word, class Hash = Foam::Hash<Key>> typedef label size_type
Definition at line 169 of file HashTable.H.
key_iterator
template<class T , class Key = word, class Hash = Foam::Hash<Key>> using key_iterator = key_iterator_base<iterator>
Definition at line 937 of file HashTable.H.
const_key_iterator
template<class T , class Key = word, class Hash = Foam::Hash<Key>> using const_key_iterator = key_iterator_base<const_iterator>
Definition at line 940 of file HashTable.H.
Constructor & Destructor Documentation
HashTable() [1/6]
template<class T , class Key , class Hash > HashTable ()
Definition at line 33 of file HashTable.C.
HashTable() [2/6]
template<class T , class Key , class Hash > HashTable (const label size) explicit
Definition at line 40 of file HashTable.C.
HashTable() [3/6]
template<class T , class Key , class Hash > HashTable (Istream & is, const label size = 128)
Definition at line 29 of file HashTableIO.C.
References HashTable< T, Key, Hash >::operator>>.
HashTable() [4/6]
template<class T , class Key = word, class Hash = Foam::Hash<Key>> HashTable (const this_type & ht)
HashTable() [5/6]
template<class T , class Key = word, class Hash = Foam::Hash<Key>> HashTable (this_type && rhs)
HashTable() [6/6]
template<class T , class Key , class Hash > HashTable (std::initializer_list< std::pair< Key, T > > list)
Definition at line 85 of file HashTable.C.
References UPtrList< T >::first(), and HashTable< T, Key, Hash >::set().
~HashTable()
template<class T , class Key , class Hash > ~HashTable ()
Definition at line 102 of file HashTable.C.
References clear().
Member Function Documentation
empty()
template<class T , class Key = word, class Hash = Foam::Hash<Key>> bool empty () const inline noexcept
Definition at line 255 of file HashTable.H.
Referenced by interfaceDefinitions::empty(), exprDriver::hasContextObjects(), faMeshTools::newMesh(), objectiveForce::objectiveForce(), objectiveMoment::objectiveMoment(), RecycleInteraction< CloudType >::RecycleInteraction(), and StandardWallInteraction< CloudType >::StandardWallInteraction().
size()
template<class T , class Key = word, class Hash = Foam::Hash<Key>> label size () const inline noexcept
Definition at line 258 of file HashTable.H.
Referenced by boundaryMesh::changeFaces(), IOobjectList::classesImpl(), objectRegistry::classesImpl(), fvMeshDistribute::distribute(), Foam::eraseImpl(), dynamicIndexedOctree< Type >::findBox(), indexedOctree< Type >::findBox(), dynamicIndexedOctree< Type >::findSphere(), indexedOctree< Type >::findSphere(), combineFaces::getMergeSets(), InjectedParticleInjection< CloudType >::initialise(), viewFactor::initialise(), injectionModelList::injectionModelList(), injectionModelList::injectionModelList(), isoSurfacePoint::isoSurfacePoint(), IOobjectList::lookupClassImpl(), IOobjectList::lookupClassTypeImpl(), IOobjectList::lookupImpl(), multiphaseSystem::multiphaseSystem(), IOobjectList::namesImpl(), objectRegistry::namesImpl(), IOobjectList::namesTypeImpl(), objectRegistry::namesTypeImpl(), IOobjectList::objectsTypeImpl(), objectRegistry::objectsTypeImpl(), Foam::operator<<(), wallBoundedStreamLine::read(), hexRef8::setRefinement(), interfaceDefinitions::size(), topoBitSet::topoBitSet(), topoBitSet::topoBitSet(), topoBitSet::topoBitSet(), topoBoolSet::topoBoolSet(), topoBoolSet::topoBoolSet(), topoBoolSet::topoBoolSet(), transferModelList::transferModelList(), and topoSet::updateLabels().
capacity()
template<class T , class Key = word, class Hash = Foam::Hash<Key>> label capacity () const inline noexcept
Definition at line 261 of file HashTable.H.
Referenced by dynamicIndexedOctree< Type >::findBox(), indexedOctree< Type >::findBox(), dynamicIndexedOctree< Type >::findSphere(), and indexedOctree< Type >::findSphere().
at() [1/2]
template<class T , class Key , class Hash > T & at (const Key & key) inline
Definition at line 38 of file HashTableI.H.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, HashTable< T, Key, Hash >::Iterator< Const >::good(), and HashTable< T, Key, Hash >::iterator::val().
at() [2/2]
template<class T , class Key , class Hash > const T & at (const Key & key) const inline
Definition at line 55 of file HashTableI.H.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, HashTable< T, Key, Hash >::Iterator< Const >::good(), and HashTable< T, Key, Hash >::const_iterator::val().
contains()
template<class T , class Key , class Hash > bool contains (const Key & key) const inline
Definition at line 72 of file HashTableI.H.
Referenced by HashTable< T, Key, Hash >::found(), and HashSet< Key, Hash >::test().
find() [1/2]
template<class T , class Key , class Hash > Foam::HashTable< T, Key, Hash >::iterator find (const Key & key) inline
Definition at line 85 of file HashTableI.H.
Referenced by objectRegistry::checkIn(), objectRegistry::checkOut(), FreeStream< CloudType >::FreeStream(), and meshToMesh0::meshToMesh0().
find() [2/2]
template<class T , class Key , class Hash > Foam::HashTable< T, Key, Hash >::const_iterator find (const Key & key) const inline
Definition at line 101 of file HashTableI.H.
cfind()
template<class T , class Key , class Hash > Foam::HashTable< T, Key, Hash >::const_iterator cfind (const Key & key) const inline
Definition at line 112 of file HashTableI.H.
Referenced by STLAsciiParse::beginSolid().
lookup()
template<class T , class Key , class Hash > const T & lookup (const Key & key, const T & deflt) const inline
Definition at line 221 of file HashTableI.H.
References HashTable< T, Key, Hash >::Iterator< Const >::good(), and HashTable< T, Key, Hash >::const_iterator::val().
toc()
template<class T , class Key , class Hash > Foam::List< Key > toc () const
Definition at line 115 of file HashTable.C.
Referenced by primitiveMeshGeometry::affectedCells(), polyMeshGeometry::affectedCells(), nearWallFields::createFields(), dynamicIndexedOctree< Type >::findBox(), indexedOctree< Type >::findBox(), dynamicIndexedOctree< Type >::findSphere(), indexedOctree< Type >::findSphere(), IOobjectList::names(), objectRegistry::names(), faceAreaWeightAMI2D::overlappingTgtFaces(), uniformInterpolatedDisplacementPointPatchVectorField::updateCoeffs(), faGlobalMeshData::updateMesh(), and zoneMotion::zoneMotion().
sortedToc() [1/3]
template<class T , class Key , class Hash > Foam::List< Key > sortedToc () const
Definition at line 130 of file HashTable.C.
References Foam::sort().
Referenced by edgeMeshFormatsCore::checkSupport(), surfaceFormatsCore::checkSupport(), DispersionRASModel< CloudType >::epsilonModel(), forAll(), viewFactor::initialise(), DispersionRASModel< CloudType >::kModel(), functionObjectList::list(), writeDictionary::read(), externalCoupled::read(), cellSetOption::setCellSelection(), IOobjectList::sortedNames(), and objectRegistry::sortedNames().
sortedToc() [2/3]
template<class T , class Key = word, class Hash = Foam::Hash<Key>> template<class Compare > List< Key > sortedToc (const Compare & comp) const
tocKeys() [1/2]
template<class T , class Key = word, class Hash = Foam::Hash<Key>> template<class UnaryPredicate > List< Key > tocKeys (const UnaryPredicate & pred, const bool invert = false) const
tocValues() [1/2]
template<class T , class Key = word, class Hash = Foam::Hash<Key>> template<class UnaryPredicate > List< Key > tocValues (const UnaryPredicate & pred, const bool invert = false) const
tocEntries() [1/2]
template<class T , class Key = word, class Hash = Foam::Hash<Key>> template<class BinaryPredicate > List< Key > tocEntries (const BinaryPredicate & pred, const bool invert = false) const
csorted()
template<class T , class Key , class Hash > Foam::UPtrList< const typename Foam::HashTable< T, Key, Hash >::node_type > csorted () const
Definition at line 155 of file HashTable.C.
References PtrList< T >::set(), and Foam::sort().
sorted() [1/2]
template<class T , class Key , class Hash > Foam::UPtrList< const typename Foam::HashTable< T, Key, Hash >::node_type > sorted () const
Definition at line 174 of file HashTable.C.
sorted() [2/2]
template<class T , class Key , class Hash > Foam::UPtrList< typename Foam::HashTable< T, Key, Hash >::node_type > sorted ()
Definition at line 182 of file HashTable.C.
References PtrList< T >::set(), and Foam::sort().
countKeys() [1/2]
template<class T , class Key = word, class Hash = Foam::Hash<Key>> template<class UnaryPredicate > label countKeys (const UnaryPredicate & pred, const bool invert = false) const
countValues() [1/2]
template<class T , class Key = word, class Hash = Foam::Hash<Key>> template<class UnaryPredicate > label countValues (const UnaryPredicate & pred, const bool invert = false) const
countEntries() [1/2]
template<class T , class Key = word, class Hash = Foam::Hash<Key>> template<class BinaryPredicate > label countEntries (const BinaryPredicate & pred, const bool invert = false) const
emplace()
template<class T , class Key , class Hash > template<class... Args> bool emplace (const Key & key, Args &&... args) inline
Definition at line 128 of file HashTableI.H.
References args.
emplace_set()
template<class T , class Key , class Hash > template<class... Args> bool emplace_set (const Key & key, Args &&... args) inline
Definition at line 140 of file HashTableI.H.
References args.
insert() [1/2]
template<class T , class Key , class Hash > bool insert (const Key & key, const T & obj) inline
Definition at line 151 of file HashTableI.H.
Referenced by STLAsciiParse::beginSolid(), objectRegistry::checkIn(), greyMeanAbsorptionEmission::greyMeanAbsorptionEmission(), greyMeanSolidAbsorptionEmission::greyMeanSolidAbsorptionEmission(), LocalInteraction< CloudType >::LocalInteraction(), meshToMesh0::meshToMesh0(), meshToMesh0::meshToMesh0(), multiphaseSystem::multiphaseSystem(), nastranWriter::nastranWriter(), phaseSystem::phaseSystem(), RecycleInteraction< CloudType >::RecycleInteraction(), hashedWordList::rehash(), StandardWallInteraction< CloudType >::StandardWallInteraction(), twoPhaseSystem::twoPhaseSystem(), and wideBandAbsorptionEmission::wideBandAbsorptionEmission().
insert() [2/2]
template<class T , class Key , class Hash > bool insert (const Key & key, T && obj) inline
Definition at line 162 of file HashTableI.H.
set() [1/2]
template<class T , class Key , class Hash > bool set (const Key & key, const T & obj) inline
Definition at line 173 of file HashTableI.H.
Referenced by interfaceDefinitions::add(), and HashTable< T, Key, Hash >::HashTable().
set() [2/2]
template<class T , class Key , class Hash > bool set (const Key & key, T && obj) inline
Definition at line 184 of file HashTableI.H.
erase() [1/10]
template<class T , class Key , class Hash > bool erase (const iterator & iter)
Definition at line 473 of file HashTable.C.
Referenced by objectRegistry::erase().
erase() [2/10]
template<class T , class Key , class Hash > bool erase (const Key & key)
Definition at line 485 of file HashTable.C.
erase() [3/10]
template<class T , class Key = word, class Hash = Foam::Hash<Key>> template<class AnyType , class AnyHash > label erase (const HashTable< AnyType, Key, AnyHash > & other)
erase() [4/10]
template<class T , class Key , class Hash > Foam::label erase (std::initializer_list< Key > keys) inline
Definition at line 520 of file HashTable.C.
References erase().
erase() [5/10]
template<class T , class Key = word, class Hash = Foam::Hash<Key>> template<class InputIter > label erase (InputIter first, InputIter last) inline
erase() [6/10]
template<class T , class Key = word, class Hash = Foam::Hash<Key>> template<unsigned N> label erase (const FixedList< Key, N > & keys) inline
erase() [7/10]
template<class T , class Key , class Hash > Foam::label erase (const UList< Key > & keys) inline
Definition at line 541 of file HashTable.C.
retain() [1/2]
template<class T , class Key = word, class Hash = Foam::Hash<Key>> template<class AnyType , class AnyHash > label retain (const HashTable< AnyType, Key, AnyHash > & other)
filterKeys() [1/2]
template<class T , class Key = word, class Hash = Foam::Hash<Key>> template<class UnaryPredicate > label filterKeys (const UnaryPredicate & pred, const bool pruning = false)
Referenced by IOobjectList::prune_0().
filterValues() [1/2]
template<class T , class Key = word, class Hash = Foam::Hash<Key>> template<class UnaryPredicate > label filterValues (const UnaryPredicate & pred, const bool pruning = false)
filterEntries() [1/2]
template<class T , class Key = word, class Hash = Foam::Hash<Key>> template<class BinaryPredicate > label filterEntries (const BinaryPredicate & pred, const bool pruning = false)
resize()
template<class T , class Key , class Hash > void resize (const label sz)
Definition at line 632 of file HashTable.C.
References HashTableCore::canonicalSize(), Foam::nl, and WarningInFunction.
Referenced by pointSet::distribute(), cellSet::distribute(), faceSet::distribute(), dynamicIndexedOctree< Type >::findBox(), indexedOctree< Type >::findBox(), dynamicIndexedOctree< Type >::findSphere(), indexedOctree< Type >::findSphere(), hashedWordList::rehash(), cellZoneSet::updateSet(), faceZoneSet::updateSet(), pointZoneSet::updateSet(), and Foam::HashSetOps::used().
clear()
template<class T , class Key , class Hash > void clear ()
Definition at line 705 of file HashTable.C.
Referenced by decompositionMethod::calcCellCells(), decompositionMethod::calcCellCells(), interfaceDefinitions::clear(), objectRegistry::clear(), pointSet::distribute(), cellSet::distribute(), faceSet::distribute(), dynamicIndexedOctree< Type >::findBox(), indexedOctree< Type >::findBox(), dynamicIndexedOctree< Type >::findSphere(), indexedOctree< Type >::findSphere(), hashedWordList::rehash(), surfaceIntersection::surfaceIntersection(), and PrimitivePatch< FaceList, PointField >::surfaceType().
clearStorage()
template<class T , class Key , class Hash > void clearStorage ()
Definition at line 724 of file HashTable.C.
References clear(), and resize().
Referenced by objectRegistry::clearStorage(), cellZoneSet::updateSet(), faceZoneSet::updateSet(), and pointZoneSet::updateSet().
swap()
template<class T , class Key , class Hash > void swap (HashTable< T, Key, Hash > & rhs)
Definition at line 732 of file HashTable.C.
transfer()
template<class T , class Key , class Hash > void transfer (HashTable< T, Key, Hash > & rhs)
Definition at line 746 of file HashTable.C.
References clear().
Referenced by extendedEdgeMesh::transfer(), and topoSet::updateLabels().
merge() [1/2]
template<class T , class Key , class Hash > void merge (HashTable< T, Key, Hash > & source)
Definition at line 840 of file HashTable.C.
References UPtrList< T >::begin(), and UPtrList< T >::end().
merge() [2/2]
template<class T , class Key , class Hash > void merge (HashTable< T, Key, Hash > && source)
Definition at line 873 of file HashTable.C.
operator[]() [1/2]
template<class T , class Key , class Hash > T & operator[] (const Key & key) inline
Definition at line 235 of file HashTableI.H.
operator[]() [2/2]
template<class T , class Key , class Hash > const T & operator[] (const Key & key) const inline
Definition at line 242 of file HashTableI.H.
operator()() [1/2]
template<class T , class Key , class Hash > T & operator() (const Key & key) inline
Definition at line 249 of file HashTableI.H.
References HashTable< T, Key, Hash >::Iterator< Const >::good(), and HashTable< T, Key, Hash >::iterator::val().
operator()() [2/2]
template<class T , class Key , class Hash > T & operator() (const Key & key, const T & deflt) inline
Definition at line 264 of file HashTableI.H.
operator=() [1/3]
template<class T , class Key = word, class Hash = Foam::Hash<Key>> void operator= (const this_type & rhs)
operator=() [2/3]
template<class T , class Key , class Hash > void operator= (std::initializer_list< std::pair< Key, T > > rhs)
Definition at line 910 of file HashTable.C.
References clear(), UPtrList< T >::first(), and resize().
operator=() [3/3]
template<class T , class Key = word, class Hash = Foam::Hash<Key>> void operator= (this_type && rhs)
operator==()
template<class T , class Key = word, class Hash = Foam::Hash<Key>> bool operator== (const this_type & rhs) const
Definition at line 948 of file HashTable.C.
References HashTable< T, Key, Hash >::Iterator< Const >::good(), and HashTable< T, Key, Hash >::const_iterator::val().
operator!=()
template<class T , class Key = word, class Hash = Foam::Hash<Key>> bool operator!= (const this_type & rhs) const
Definition at line 974 of file HashTable.C.
References Foam::operator==().
operator+=()
template<class T , class Key = word, class Hash = Foam::Hash<Key>> Foam::HashTable< T, Key, Hash > & operator+= (const this_type & rhs)
Definition at line 984 of file HashTable.C.
References insert().
keys()
template<class T , class Key = word, class Hash = Foam::Hash<Key>> const_iterator_pair< const_key_iterator, this_type > keys () const inline
Definition at line 943 of file HashTable.H.
begin() [1/2]
template<class T , class Key , class Hash > Foam::HashTable< T, Key, Hash >::iterator begin () inline
Definition at line 167 of file HashTableIterI.H.
begin() [2/2]
template<class T , class Key , class Hash > Foam::HashTable< T, Key, Hash >::const_iterator begin () const inline
Definition at line 175 of file HashTableIterI.H.
cbegin()
template<class T , class Key , class Hash > Foam::HashTable< T, Key, Hash >::const_iterator cbegin () const inline
Definition at line 183 of file HashTableIterI.H.
end() [1/2]
template<class T , class Key , class Hash > Foam::HashTable< T, Key, Hash >::iterator end () inline noexcept
Definition at line 191 of file HashTableIterI.H.
end() [2/2]
template<class T , class Key , class Hash > Foam::HashTable< T, Key, Hash >::const_iterator end () const inline noexcept
Definition at line 199 of file HashTableIterI.H.
cend()
template<class T , class Key , class Hash > constexpr Foam::HashTable< T, Key, Hash >::const_iterator cend () const inline constexpr noexcept
Definition at line 207 of file HashTableIterI.H.
printInfo()
template<class T , class Key , class Hash > Foam::Ostream & printInfo (Ostream & os) const
Definition at line 53 of file HashTableIO.C.
References Foam::endl(), and os().
writeKeys()
template<class T , class Key , class Hash > Foam::Ostream & writeKeys (Ostream & os, const label shortLen = 0) const
Definition at line 89 of file HashTableIO.C.
References token::BEGIN_LIST, IOstream::check(), token::END_LIST, FUNCTION_NAME, Foam::nl, os(), and token::SPACE.
Referenced by HashSet< Key, Hash >::writeList().
found()
template<class T , class Key = word, class Hash = Foam::Hash<Key>> bool found (const Key & key) const inline
Definition at line 999 of file HashTable.H.
References HashTable< T, Key, Hash >::contains().
Referenced by edgeMeshFormatsCore::checkSupport(), surfaceFormatsCore::checkSupport(), inverseFaceDistanceDiffusivity::correct(), inversePointDistanceDiffusivity::correct(), topoSet::found(), MassTransferPhaseSystem< BasePhaseSystem >::MassTransferPhaseSystem(), meshToMesh0::meshToMesh0(), multiphaseSystem::multiphaseSystem(), twoPhaseSystem::twoPhaseSystem(), faGlobalMeshData::updateMesh(), and wideBandAbsorptionEmission::wideBandAbsorptionEmission().
sortedToc() [3/3]
template<class T , class Key = word, class Hash = Foam::Hash<Key>> template<class Compare > Foam::List< Key > sortedToc (const Compare & comp) const
Definition at line 141 of file HashTable.C.
References Foam::sort().
tocKeys() [2/2]
template<class T , class Key = word, class Hash = Foam::Hash<Key>> template<class UnaryPredicate > Foam::List< Key > tocKeys (const UnaryPredicate & pred, const bool invert) const
Definition at line 202 of file HashTable.C.
References Foam::invert(), PtrList< T >::resize(), and Foam::sort().
tocValues() [2/2]
template<class T , class Key = word, class Hash = Foam::Hash<Key>> template<class UnaryPredicate > Foam::List< Key > tocValues (const UnaryPredicate & pred, const bool invert) const
Definition at line 228 of file HashTable.C.
tocEntries() [2/2]
template<class T , class Key = word, class Hash = Foam::Hash<Key>> template<class BinaryPredicate > Foam::List< Key > tocEntries (const BinaryPredicate & pred, const bool invert) const
Definition at line 254 of file HashTable.C.
References Foam::invert(), PtrList< T >::resize(), and Foam::sort().
countKeys() [2/2]
template<class T , class Key = word, class Hash = Foam::Hash<Key>> template<class UnaryPredicate > Foam::label countKeys (const UnaryPredicate & pred, const bool invert) const
Definition at line 280 of file HashTable.C.
References Foam::invert().
countValues() [2/2]
template<class T , class Key = word, class Hash = Foam::Hash<Key>> template<class UnaryPredicate > Foam::label countValues (const UnaryPredicate & pred, const bool invert) const
Definition at line 302 of file HashTable.C.
References Foam::invert().
countEntries() [2/2]
template<class T , class Key = word, class Hash = Foam::Hash<Key>> template<class BinaryPredicate > Foam::label countEntries (const BinaryPredicate & pred, const bool invert) const
Definition at line 324 of file HashTable.C.
References Foam::invert().
erase() [8/10]
template<class T , class Key = word, class Hash = Foam::Hash<Key>> template<class InputIter > Foam::label erase (InputIter first, InputIter last) inline
Definition at line 494 of file HashTable.C.
References erase().
erase() [9/10]
template<class T , class Key = word, class Hash = Foam::Hash<Key>> template<unsigned N> Foam::label erase (const FixedList< Key, N > & keys) inline
Definition at line 531 of file HashTable.C.
erase() [10/10]
template<class T , class Key = word, class Hash = Foam::Hash<Key>> template<class AnyType , class AnyHash > Foam::label erase (const HashTable< AnyType, Key, AnyHash > & other)
Definition at line 552 of file HashTable.C.
References UPtrList< T >::cbegin(), UPtrList< T >::cend(), erase(), and UPtrList< T >::size().
retain() [2/2]
template<class T , class Key = word, class Hash = Foam::Hash<Key>> template<class AnyType , class AnyHash > Foam::label retain (const HashTable< AnyType, Key, AnyHash > & other)
Definition at line 600 of file HashTable.C.
References clear(), UPtrList< T >::empty(), and erase().
filterKeys() [2/2]
template<class T , class Key = word, class Hash = Foam::Hash<Key>> template<class UnaryPredicate > Foam::label filterKeys (const UnaryPredicate & pred, const bool pruning)
Definition at line 760 of file HashTable.C.
References erase().
filterValues() [2/2]
template<class T , class Key = word, class Hash = Foam::Hash<Key>> template<class UnaryPredicate > Foam::label filterValues (const UnaryPredicate & pred, const bool pruning)
Definition at line 787 of file HashTable.C.
References erase().
filterEntries() [2/2]
template<class T , class Key = word, class Hash = Foam::Hash<Key>> template<class BinaryPredicate > Foam::label filterEntries (const BinaryPredicate & pred, const bool pruning)
Definition at line 814 of file HashTable.C.
References erase().
Friends And Related Symbol Documentation
Iterator< true >
template<class T , class Key = word, class Hash = Foam::Hash<Key>> friend class Iterator< true > friend
Definition at line 588 of file HashTable.H.
Iterator< false >
template<class T , class Key = word, class Hash = Foam::Hash<Key>> friend class Iterator< false > friend
Definition at line 588 of file HashTable.H.
operator>>
template<class T , class Key = word, class Hash = Foam::Hash<Key>> Istream & operator>> (Istream & , HashTable< T, Key, Hash > & tbl) friend
Referenced by HashTable< T, Key, Hash >::HashTable().
operator
template<class T , class Key = word, class Hash = Foam::Hash<Key>> Ostream & operator (Ostream & , const HashTable< T, Key, Hash > & tbl) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/HashTables/HashTable/HashTable.H
src/OpenFOAM/containers/HashTables/HashTable/HashTable.C
src/OpenFOAM/containers/HashTables/HashTable/HashTableI.H
src/OpenFOAM/containers/HashTables/HashTable/HashTableIO.C
src/OpenFOAM/containers/HashTables/HashTable/HashTableIter.C
src/OpenFOAM/containers/HashTables/HashTable/HashTableIterI.H