OpenFOAM: seriesProfile Class Reference
seriesProfile Class Reference
Profile model where polar lift and drag coefficients are computed as sum of trigonometric series by using an input angle of attack.
#include <seriesProfile.H>
Public Member Functions
TypeName ("series")
seriesProfile (const dictionary &dict, const word &modelName)
seriesProfile (const seriesProfile &)=delete
void operator= (const seriesProfile &)=delete
~seriesProfile ()=default
virtual void Cdl (const scalar alpha, scalar &Cd, scalar &Cl) const
Public Member Functions inherited from profileModel
TypeName ("profileModel")
declareRunTimeSelectionTable (autoPtr, profileModel, dictionary,(const dictionary &dict, const word &modelName),(dict, modelName))
profileModel (const dictionary &dict, const word &modelName)
virtual ~profileModel ()=default
const word & name () const
Protected Member Functions
scalar evaluateDrag (const scalar &xIn, const List< scalar > &values) const
scalar evaluateLift (const scalar &xIn, const List< scalar > &values) const
Protected Member Functions inherited from profileModel
bool readFromFile () const
Protected Attributes
List< scalar > CdCoeffs_
List< scalar > ClCoeffs_
Protected Attributes inherited from profileModel
const dictionary dict_
const word name_
fileName fName_
Additional Inherited Members
Static Public Member Functions inherited from profileModel
static autoPtr< profileModel > New (const dictionary &dict)
Detailed Description
Profile model where polar lift and drag coefficients are computed as sum of trigonometric series by using an input angle of attack.
where
= Drag coefficient
= Lift coefficient
= Angle of attack [deg]
Usage
Minimal example by using constant/fvOptions: rotorDiskSource1 { Mandatory/Optional (inherited) entries ...
Mandatory entries (runtime modifiable) profiles { Mandatory entries (runtime modifiable) <profile1> { Mandatory entries (runtime modifiable) type series; CdCoeffs (coeff1 coeff2 ... coeffN); ClCoeffs (coeff1 coeff2 ... coeffN); }
Mandatory/Optional (inherited) entries ... } }
where the entries mean:
Property Description Type Reqd Dflt
CdCoeffs List of drag coefficients scalarList yes -
ClCoeffs List of lift coefficients scalarList yes -
Note
Angle of attack is internally converted from [deg] to [rad].
See also
Foam::fv::rotorDiskSource
Foam::profileModel
Foam::seriesProfile
Source files
seriesProfile.H
seriesProfile.C
Definition at line 133 of file seriesProfile.H.
Constructor & Destructor Documentation
seriesProfile() [1/2]
seriesProfile (const dictionary & dict, const word & modelName)
Definition at line 75 of file seriesProfile.C.
References seriesProfile::CdCoeffs_, seriesProfile::ClCoeffs_, dict, UList< T >::empty(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, profileModel::fName_, and profileModel::readFromFile().
seriesProfile() [2/2]
seriesProfile (const seriesProfile &) delete
~seriesProfile()
~seriesProfile () default
Member Function Documentation
evaluateDrag()
Foam::scalar evaluateDrag (const scalar & xIn, const List< scalar > & values) const protected
Definition at line 37 of file seriesProfile.C.
References Foam::cos(), and forAll.
evaluateLift()
Foam::scalar evaluateLift (const scalar & xIn, const List< scalar > & values) const protected
Definition at line 54 of file seriesProfile.C.
References forAll, and Foam::sin().
TypeName()
TypeName ("series")
operator=()
void operator= (const seriesProfile &) delete
Cdl()
void Cdl (const scalar alpha, scalar & Cd, scalar & Cl) const virtual
Implements profileModel.
Definition at line 114 of file seriesProfile.C.
References alpha.
Member Data Documentation
CdCoeffs_
List<scalar> CdCoeffs_ protected
Definition at line 142 of file seriesProfile.H.
Referenced by seriesProfile::seriesProfile().
ClCoeffs_
List<scalar> ClCoeffs_ protected
Definition at line 145 of file seriesProfile.H.
Referenced by seriesProfile::seriesProfile().
The documentation for this class was generated from the following files:
src/fvOptions/sources/derived/rotorDiskSource/profileModel/series/seriesProfile.H
src/fvOptions/sources/derived/rotorDiskSource/profileModel/series/seriesProfile.C