OpenFOAM: fileMonitorWatcher Class Reference
fileMonitorWatcher Class Reference
Public Member Functions
fileMonitorWatcher (const bool useInotify, const label sz=20)
~fileMonitorWatcher ()
bool addWatch (const label watchFd, const fileName &fName)
bool removeWatch (const label watchFd)
Public Attributes
const bool useInotify_
int inotifyFd_
DynamicList< label > dirWatches_
DynamicList< fileName > dirFiles_
DynamicList< double > lastMod_
Detailed Description
Definition at line 102 of file fileMonitor.C.
Constructor & Destructor Documentation
fileMonitorWatcher()
fileMonitorWatcher (const bool useInotify, const label sz = 20) inline
Definition at line 125 of file fileMonitor.C.
References fileMonitorWatcher::dirFiles_, fileMonitorWatcher::dirWatches_, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, fileMonitorWatcher::inotifyFd_, fileMonitorWatcher::lastMod_, DynamicList< T, SizeMin >::setCapacity(), fileMonitorWatcher::useInotify_, and WarningInFunction.
~fileMonitorWatcher()
~fileMonitorWatcher () inline
Definition at line 174 of file fileMonitor.C.
References fileMonitorWatcher::dirWatches_, Foam::endl(), forAll, fileMonitorWatcher::inotifyFd_, fileMonitorWatcher::useInotify_, and WarningInFunction.
Member Function Documentation
addWatch()
bool addWatch (const label watchFd, const fileName & fName) inline
Definition at line 195 of file fileMonitor.C.
References Foam::abort(), fileMonitorWatcher::dirFiles_, fileMonitorWatcher::dirWatches_, Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::highResLastModified(), fileMonitorWatcher::inotifyFd_, Foam::isDir(), fileMonitorWatcher::lastMod_, fileName::name(), fileName::path(), UList< T >::size(), and fileMonitorWatcher::useInotify_.
removeWatch()
bool removeWatch (const label watchFd) inline
Definition at line 261 of file fileMonitor.C.
References fileMonitorWatcher::dirWatches_, fileMonitorWatcher::inotifyFd_, fileMonitorWatcher::lastMod_, and fileMonitorWatcher::useInotify_.
Member Data Documentation
useInotify_
const bool useInotify_
Definition at line 106 of file fileMonitor.C.
Referenced by fileMonitorWatcher::addWatch(), fileMonitorWatcher::fileMonitorWatcher(), fileMonitorWatcher::removeWatch(), and fileMonitorWatcher::~fileMonitorWatcher().
inotifyFd_
int inotifyFd_
Definition at line 111 of file fileMonitor.C.
Referenced by fileMonitorWatcher::addWatch(), fileMonitorWatcher::fileMonitorWatcher(), fileMonitorWatcher::removeWatch(), and fileMonitorWatcher::~fileMonitorWatcher().
dirWatches_
DynamicList<label> dirWatches_
Definition at line 114 of file fileMonitor.C.
Referenced by fileMonitorWatcher::addWatch(), fileMonitorWatcher::fileMonitorWatcher(), fileMonitorWatcher::removeWatch(), and fileMonitorWatcher::~fileMonitorWatcher().
dirFiles_
DynamicList<fileName> dirFiles_
Definition at line 115 of file fileMonitor.C.
Referenced by fileMonitorWatcher::addWatch(), and fileMonitorWatcher::fileMonitorWatcher().
lastMod_
DynamicList<double> lastMod_
Definition at line 120 of file fileMonitor.C.
Referenced by fileMonitorWatcher::addWatch(), fileMonitorWatcher::fileMonitorWatcher(), and fileMonitorWatcher::removeWatch().
The documentation for this class was generated from the following file:
src/OSspecific/POSIX/fileMonitor/fileMonitor.C