OpenFOAM: GeometricBoundaryField< Type, PatchField, GeoMesh > Class Template Reference
GeometricBoundaryField< Type, PatchField, GeoMesh > Class Template Reference
Generic GeometricBoundaryField class.
#include <GeometricBoundaryField.H>
Public Types
typedef GeoMesh::BoundaryMesh BoundaryMesh
typedef DimensionedField< Type, GeoMesh > Internal
typedef PatchField< Type > Patch
Public Types inherited from FieldField< PatchField, Type >
typedef pTraits< Type >::cmptType cmptType
Public Types inherited from UPtrList< T >
typedef T value_type
typedef T & reference
typedef const T & const_reference
Public Member Functions
GeometricBoundaryField (const BoundaryMesh &bmesh)
GeometricBoundaryField (const BoundaryMesh &bmesh, const DimensionedField< Type, GeoMesh > &field, const word &patchFieldType=PatchField< Type >::calculatedType())
GeometricBoundaryField (const BoundaryMesh &bmesh, const DimensionedField< Type, GeoMesh > &field, const wordList &wantedPatchTypes, const wordList &actualPatchTypes=wordList())
GeometricBoundaryField (const BoundaryMesh &bmesh, const DimensionedField< Type, GeoMesh > &field, const PtrList< PatchField< Type > > &ptfl)
GeometricBoundaryField (const DimensionedField< Type, GeoMesh > &field, const GeometricBoundaryField< Type, PatchField, GeoMesh > &btf)
GeometricBoundaryField (const DimensionedField< Type, GeoMesh > &field, const GeometricBoundaryField< Type, PatchField, GeoMesh > &btf, const labelList &patchIDs, const word &patchFieldName)
GeometricBoundaryField (const GeometricBoundaryField &btf)
GeometricBoundaryField (const BoundaryMesh &bmesh, const DimensionedField< Type, GeoMesh > &field, const dictionary &dict)
void readField (const DimensionedField< Type, GeoMesh > &field, const dictionary &dict)
void updateCoeffs ()
void evaluate ()
template<class CoupledPatchType >
void evaluateCoupled ()
wordList types () const
GeometricBoundaryField boundaryInternalField () const
LduInterfaceFieldPtrsList< Type > interfaces () const
lduInterfaceFieldPtrsList scalarInterfaces () const
void writeEntry (const word &keyword, Ostream &os) const
void writeEntries (Ostream &os) const
void operator= (const GeometricBoundaryField &bf)
void operator= (const FieldField< PatchField, Type > &bf)
void operator= (const Type &val)
void operator== (const GeometricBoundaryField &bf)
void operator== (const FieldField< PatchField, Type > &bf)
void operator== (const Type &val)
Public Member Functions inherited from FieldField< PatchField, Type >
constexpr FieldField () noexcept
FieldField (const label size)
FieldField (const word &type, const FieldField< PatchField, Type > &ff)
FieldField (const FieldField< PatchField, Type > &ff)
FieldField (FieldField< PatchField, Type > &&ff)
FieldField (FieldField< PatchField, Type > &ff, bool reuse)
FieldField (const PtrList< PatchField< Type > > &list)
FieldField (PtrList< PatchField< Type > > &&list)
FieldField (const tmp< FieldField< PatchField, Type > > &tf)
FieldField (Istream &is)
tmp< FieldField< PatchField, Type > > clone () const
void negate ()
void normalise ()
tmp< FieldField< PatchField, cmptType > > component (const direction) const
void replace (const direction, const FieldField< PatchField, cmptType > &)
void replace (const direction, const cmptType &)
void clamp_min (const Type &lower)
void clamp_max (const Type &upper)
void clamp_range (const Type &lower, const Type &upper)
void clamp_range (const MinMax< Type > &range)
tmp< FieldField< PatchField, Type > > T () const
const Type & operator[] (const labelPair &index) const
Type & operator[] (const labelPair &index)
void operator= (const FieldField< PatchField, Type > &)
void operator= (FieldField< PatchField, Type > &&)
void operator= (const tmp< FieldField< PatchField, Type > > &)
void operator= (const Type &val)
void operator= (const Foam::zero)
void operator+= (const FieldField< PatchField, Type > &)
void operator+= (const tmp< FieldField< PatchField, Type > > &)
void operator+= (const Type &)
void operator-= (const FieldField< PatchField, Type > &)
void operator-= (const tmp< FieldField< PatchField, Type > > &)
void operator-= (const Type &)
void operator*= (const FieldField< PatchField, scalar > &)
void operator*= (const tmp< FieldField< PatchField, scalar > > &)
void operator*= (const scalar &)
void operator/= (const FieldField< PatchField, scalar > &)
void operator/= (const tmp< FieldField< PatchField, scalar > > &)
void operator/= (const scalar &)
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Public Member Functions inherited from PtrList< T >
constexpr PtrList () noexcept
PtrList (const label len)
PtrList (const PtrList< T > &list)
PtrList (PtrList< T > &&list)
PtrList (UList< T * > &list)
template<class CloneArg >
PtrList (const PtrList< T > &list, const CloneArg &cloneArgs)
PtrList (PtrList< T > &list, bool reuse)
PtrList (const SLPtrList< T > &list)
template<class INew >
PtrList (Istream &is, const INew &inew)
PtrList (Istream &is)
~PtrList ()
template<class... Args>
PtrList< T > clone (Args &&... args) const
const T * set (const label i) const
void clear ()
void free ()
void resize (const label newLen)
template<class... Args>
T & emplace_back (Args &&... args)
void push_back (T *ptr)
void push_back (std::unique_ptr< T > &&ptr)
void push_back (autoPtr< T > &&ptr)
void push_back (const refPtr< T > &ptr)
void push_back (const tmp< T > &ptr)
void push_back (PtrList< T > &&other)
template<class... Args>
T & emplace_set (const label i, Args &&... args)
template<class... Args>
T & emplace (const label i, Args &&... args)
autoPtr< T > set (const label i, T *ptr)
autoPtr< T > set (const label i, std::unique_ptr< T > &&ptr)
autoPtr< T > set (const label i, autoPtr< T > &&ptr)
autoPtr< T > set (const label i, const refPtr< T > &ptr)
autoPtr< T > set (const label i, const tmp< T > &ptr)
autoPtr< T > release (const label i)
void transfer (PtrList< T > &list)
void operator= (const PtrList< T > &list)
void operator= (PtrList< T > &&list)
void push_back (autoPtr< T > &ptr)=delete
autoPtr< T > set (const label i, autoPtr< T > &ptr)
void setSize (const label newLen)
void append (autoPtr< T > &ptr)
void append (T *ptr)
void append (std::unique_ptr< T > &&ptr)
void append (autoPtr< T > &&ptr)
void append (const refPtr< T > &ptr)
void append (const tmp< T > &ptr)
void append (PtrList< T > &&other)
template<class... Args>
Foam::PtrList< T > clone (Args &&... args) const
Public Member Functions inherited from UPtrList< T >
constexpr UPtrList () noexcept
UPtrList (const label len)
UPtrList (const UPtrList< T > &list)
UPtrList (UPtrList< T > &&list)
UPtrList (UPtrList< T > &list, bool reuse)
UPtrList (PtrList< T > &list)
UPtrList (const UList< T * > &list)
UPtrList (UList< T > &list)
bool empty () const noexcept
label size () const noexcept
label count () const noexcept
T & front ()
const T & front () const
T & back ()
const T & back () const
const T * test (const label i) const
const T * get (const label i) const
T * get (const label i)
const T * set (const label i) const
void clear ()
void free ()
void resize (const label newLen)
label squeezeNull ()
void trimTrailingNull ()
void push_back (T *ptr)
void push_back (UPtrList< T > &&other)
void swap (UPtrList< T > &list)
void transfer (UPtrList< T > &list)
T * set (const label i, T *ptr)
void reorder (const labelUList &oldToNew, const bool check=false)
void sortOrder (const labelUList &order, const bool check=false)
void checkNonNull () const
const T & at (const label i) const
T & at (const label i)
const T & operator[] (const label i) const
T & operator[] (const label i)
FOAM_DEPRECATED_FOR (2022-09, "get(), set() or test() methods") const T *operator()(const label i) const
void operator= (const UPtrList< T > &list)
void operator= (UPtrList< T > &&list)
T ** begin_ptr () noexcept
T ** end_ptr () noexcept
iterator begin ()
iterator end () noexcept
const_iterator cbegin () const
const_iterator cend () const noexcept
const_iterator begin () const
const_iterator end () const noexcept
void setSize (const label n)
T & first ()
const T & first () const
T & last ()
const T & last () const
void append (T *ptr)
void append (UPtrList< T > &&other)
Additional Inherited Members
Static Public Member Functions inherited from FieldField< PatchField, Type >
static tmp< FieldField< PatchField, Type > > NewCalculatedType (const FieldField< PatchField, Type2 > &ff)
Protected Member Functions inherited from PtrList< T >
template<class INew >
void readIstream (Istream &is, const INew &inew)
Protected Member Functions inherited from UPtrList< T >
void setAddressableSize (const label n) noexcept
label find_next (label pos) const
UPtrList (Detail::PtrListDetail< T > &&ptrs)
Protected Attributes inherited from UPtrList< T >
Detail::PtrListDetail< T > ptrs_
Detailed Description
template<class Type, template< class > class PatchField, class GeoMesh>
class Foam::GeometricBoundaryField< Type, PatchField, GeoMesh >
Generic GeometricBoundaryField class.
Source files
GeometricBoundaryField.H
GeometricBoundaryField.C
Definition at line 58 of file GeometricBoundaryField.H.
Member Typedef Documentation
BoundaryMesh
template<class Type , template< class > class PatchField, class GeoMesh > typedef GeoMesh::BoundaryMesh BoundaryMesh
Definition at line 67 of file GeometricBoundaryField.H.
Internal
template<class Type , template< class > class PatchField, class GeoMesh > typedef DimensionedField<Type, GeoMesh> Internal
Definition at line 70 of file GeometricBoundaryField.H.
Patch
template<class Type , template< class > class PatchField, class GeoMesh > typedef PatchField<Type> Patch
Definition at line 73 of file GeometricBoundaryField.H.
Constructor & Destructor Documentation
GeometricBoundaryField() [1/8]
template<class Type , template< class > class PatchField, class GeoMesh > GeometricBoundaryField (const BoundaryMesh & bmesh) explicit
Definition at line 182 of file GeometricBoundaryField.C.
GeometricBoundaryField() [2/8]
template<class Type , template< class > class PatchField, class GeoMesh > GeometricBoundaryField (const BoundaryMesh & bmesh, const DimensionedField< Type, GeoMesh > & field, const word & patchFieldType = PatchField<Type>::calculatedType())
if (GeometricField<Type, PatchField, GeoMesh::debug) { InfoInFunction << nl; }
Definition at line 193 of file GeometricBoundaryField.C.
GeometricBoundaryField() [3/8]
template<class Type , template< class > class PatchField, class GeoMesh > GeometricBoundaryField (const BoundaryMesh & bmesh, const DimensionedField< Type, GeoMesh > & field, const wordList & wantedPatchTypes, const wordList & actualPatchTypes = wordList())
if (GeometricField<Type, PatchField, GeoMesh::debug) { InfoInFunction << nl; }
Definition at line 225 of file GeometricBoundaryField.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, field(), forAll, Foam::nl, PtrList< T >::set(), UPtrList< T >::size(), and UList< T >::size().
GeometricBoundaryField() [4/8]
template<class Type , template< class > class PatchField, class GeoMesh > GeometricBoundaryField (const BoundaryMesh & bmesh, const DimensionedField< Type, GeoMesh > & field, const PtrList< PatchField< Type > > & ptfl)
if (GeometricField<Type, PatchField, GeoMesh::debug) { InfoInFunction << nl; }
Definition at line 292 of file GeometricBoundaryField.C.
References FieldField< PatchField, Type >::clone(), field(), forAll, and PtrList< T >::set().
GeometricBoundaryField() [5/8]
template<class Type , template< class > class PatchField, class GeoMesh > GeometricBoundaryField (const DimensionedField< Type, GeoMesh > & field, const GeometricBoundaryField< Type, PatchField, GeoMesh > & btf)
if (GeometricField<Type, PatchField, GeoMesh::debug) { InfoInFunction << nl; }
Definition at line 315 of file GeometricBoundaryField.C.
References FieldField< PatchField, Type >::clone(), field(), forAll, and PtrList< T >::set().
GeometricBoundaryField() [6/8]
template<class Type , template< class > class PatchField, class GeoMesh > GeometricBoundaryField (const DimensionedField< Type, GeoMesh > & field, const GeometricBoundaryField< Type, PatchField, GeoMesh > & btf, const labelList & patchIDs, const word & patchFieldName)
if (GeometricField<Type, PatchField, GeoMesh::debug) { InfoInFunction << nl; }
Definition at line 337 of file GeometricBoundaryField.C.
References FieldField< PatchField, Type >::clone(), field(), forAll, patchIDs(), and PtrList< T >::set().
GeometricBoundaryField() [7/8]
template<class Type , template< class > class PatchField, class GeoMesh > GeometricBoundaryField (const GeometricBoundaryField< Type, PatchField, GeoMesh > & btf)
GeometricBoundaryField() [8/8]
template<class Type , template< class > class PatchField, class GeoMesh > GeometricBoundaryField (const BoundaryMesh & bmesh, const DimensionedField< Type, GeoMesh > & field, const dictionary & dict)
Definition at line 394 of file GeometricBoundaryField.C.
References dict, field(), and GeometricBoundaryField< Type, PatchField, GeoMesh >::readField().
Member Function Documentation
readField()
template<class Type , template< class > class PatchField, class GeoMesh > void readField (const DimensionedField< Type, GeoMesh > & field, const dictionary & dict)
if (GeometricField<Type, PatchField, GeoMesh::debug) { InfoInFunction << nl; }
Definition at line 30 of file GeometricBoundaryField.C.
References PtrList< T >::clear(), dict, field(), PtrList< T >::resize(), PtrList< T >::set(), and UPtrList< T >::size().
Referenced by GeometricBoundaryField< Type, PatchField, GeoMesh >::GeometricBoundaryField().
updateCoeffs()
template<class Type , template< class > class PatchField, class GeoMesh > void updateCoeffs ()
if (GeometricField<Type, PatchField, GeoMesh::debug) { InfoInFunction << nl; }
Definition at line 411 of file GeometricBoundaryField.C.
Referenced by kkLOmega::correct(), LamBremhorstKE::correct(), LienCubicKE::correct(), LienLeschziner::correct(), ShihQuadraticKE::correct(), mixtureKEpsilon< BasicTurbulenceModel >::correct(), elasticityMotionSolver::setBoundaryConditions(), and laplacianMotionSolver::setBoundaryConditions().
evaluate()
template<class Type , template< class > class PatchField, class GeoMesh > void evaluate ()
if (GeometricField<Type, PatchField, GeoMesh::debug) { InfoInFunction << nl; }
Definition at line 426 of file GeometricBoundaryField.C.
References UPstream::blocking, UPstream::commsTypeNames, UPstream::defaultCommsType, Foam::exit(), Foam::FatalError, FatalErrorInFunction, UPstream::nonBlocking, UPstream::nRequests(), UPstream::scheduled, and UPstream::waitRequests().
evaluateCoupled()
template<class Type , template< class > class PatchField, class GeoMesh > template<class CoupledPatchType > void evaluateCoupled ()
if (GeometricField<Type, PatchField, GeoMesh::debug) { InfoInFunction << nl; }
Definition at line 490 of file GeometricBoundaryField.C.
References UPstream::blocking, UPstream::commsTypeNames, UPstream::defaultCommsType, Foam::exit(), Foam::FatalError, FatalErrorInFunction, UPstream::nonBlocking, UPstream::nRequests(), UPstream::scheduled, and UPstream::waitRequests().
Referenced by kkLOmega::correct(), LamBremhorstKE::correct(), LienCubicKE::correct(), LienLeschziner::correct(), ShihQuadraticKE::correct(), and mixtureKEpsilon< BasicTurbulenceModel >::correct().
types()
template<class Type , template< class > class PatchField, class GeoMesh > Foam::wordList types () const
Definition at line 569 of file GeometricBoundaryField.C.
References forAll, and UPtrList< T >::size().
boundaryInternalField()
template<class Type , template< class > class PatchField, class GeoMesh > Foam::GeometricBoundaryField< Type, PatchField, GeoMesh > boundaryInternalField () const
Definition at line 586 of file GeometricBoundaryField.C.
References forAll.
interfaces()
template<class Type , template< class > class PatchField, class GeoMesh > Foam::LduInterfaceFieldPtrsList< Type > interfaces () const
Definition at line 602 of file GeometricBoundaryField.C.
References forAll, and PtrList< T >::set().
scalarInterfaces()
template<class Type , template< class > class PatchField, class GeoMesh > Foam::lduInterfaceFieldPtrsList scalarInterfaces () const
Definition at line 623 of file GeometricBoundaryField.C.
References forAll, and UPtrList< T >::set().
writeEntry()
template<class Type , template< class > class PatchField, class GeoMesh > void writeEntry (const word & keyword, Ostream & os) const
Definition at line 644 of file GeometricBoundaryField.C.
References Ostream::beginBlock(), IOstream::check(), Ostream::endBlock(), FUNCTION_NAME, and os().
writeEntries()
template<class Type , template< class > class PatchField, class GeoMesh > void writeEntries (Ostream & os) const
Definition at line 659 of file GeometricBoundaryField.C.
References Ostream::beginBlock(), Ostream::endBlock(), and os().
operator=() [1/3]
template<class Type , template< class > class PatchField, class GeoMesh > void operator= (const GeometricBoundaryField< Type, PatchField, GeoMesh > & bf)
operator=() [2/3]
template<class Type , template< class > class PatchField, class GeoMesh > void operator= (const FieldField< PatchField, Type > & bf)
Definition at line 686 of file GeometricBoundaryField.C.
References FieldField< Field, Type >::operator=().
operator=() [3/3]
template<class Type , template< class > class PatchField, class GeoMesh > void operator= (const Type & val)
Definition at line 696 of file GeometricBoundaryField.C.
References FieldField< Field, Type >::operator=().
operator==() [1/3]
template<class Type , template< class > class PatchField, class GeoMesh > void operator== (const GeometricBoundaryField< Type, PatchField, GeoMesh > & bf)
operator==() [2/3]
template<class Type , template< class > class PatchField, class GeoMesh > void operator== (const FieldField< PatchField, Type > & bf)
Definition at line 719 of file GeometricBoundaryField.C.
References forAll.
operator==() [3/3]
template<class Type , template< class > class PatchField, class GeoMesh > void operator== (const Type & val)
Definition at line 732 of file GeometricBoundaryField.C.
References forAll.
The documentation for this class was generated from the following files:
src/finiteArea/fields/areaFields/areaFieldsFwd.H
src/OpenFOAM/fields/GeometricFields/GeometricField/GeometricBoundaryField.H
src/OpenFOAM/fields/GeometricFields/GeometricField/GeometricBoundaryField.C