OpenFOAM: weightedPosition Class Reference
weightedPosition Class Reference
Wrapper for position + weight to be used in e.g. averaging.
#include <weightedPosition.H>
Public Member Functions
weightedPosition ()
weightedPosition (const scalar s, const point &p)
void operator() (const vectorTensorTransform &vt, const bool forward, List< weightedPosition > &fld) const
void operator() (const vectorTensorTransform &vt, const bool forward, List< List< weightedPosition > > &flds) const
void operator() (const coupledPolyPatch &cpp, Field< weightedPosition > &fld) const
template<template< class > class Container>
void operator() (const coupledPolyPatch &cpp, Container< weightedPosition > &map) const
Public Member Functions inherited from Tuple2< scalar, point >
Tuple2 ()=default
Tuple2 (const scalar &f, const point &s)
Tuple2 (scalar &&f, point &&s)
Tuple2 (const std::pair< scalar, point > &vals)
Tuple2 (std::pair< scalar, point > &&vals)
Tuple2 (Istream &is)
const scalar & first () const noexcept
scalar & first () noexcept
const point & second () const noexcept
point & second () noexcept
Static Public Member Functions
static void getPoints (const UList< weightedPosition > &in, List< point > &out)
static void setPoints (const UList< point > &in, List< weightedPosition > &out)
static void plusEqOp (weightedPosition &x, const weightedPosition &y)
static void syncPoints (const polyMesh &mesh, List< weightedPosition > &)
static void syncPoints (const polyMesh &mesh, const labelUList &meshPoints, List< weightedPosition > &)
Additional Inherited Members
Public Types inherited from Tuple2< scalar, point >
typedef scalar first_type
typedef point second_type
Detailed Description
Wrapper for position + weight to be used in e.g. averaging.
This avoids the problems when synchronising locations with e.g. parallel cyclics. The separation vector only applies to locations and not e.g. summed locations. Note that there is no corresponding problem for rotational cyclics.
Typical use might be to e.g. average face centres to points on a patch
const labelListList& pointFaces = pp.pointFaces(); const vectorField::subField faceCentres = pp.faceCentres();
Field<weightedPosition> avgBoundary(pointFaces.size());
forAll(pointFaces, pointi) { const labelList& pFaces = pointFaces[pointi]; avgBoundary[pointi].first() = pFaces.size(); avgBoundary[pointi].second() = sum(pointField(faceCentres, pFaces)); } syncTools::syncPointList (mesh, pp.meshPoints(), avgBoundary, weightedPosition::plusEqOp, // combine op pTraits<weightedPosition>::zero,// null value (not used) pTraits<weightedPosition>::zero // transform class);
Source files
weightedPosition.H
weightedPosition.C
Definition at line 95 of file weightedPosition.H.
Constructor & Destructor Documentation
weightedPosition() [1/2]
weightedPosition ()
Definition at line 38 of file weightedPosition.C.
weightedPosition() [2/2]
weightedPosition (const scalar s, const point & p)
Definition at line 44 of file weightedPosition.C.
Member Function Documentation
getPoints()
void getPoints (const UList< weightedPosition > & in, List< point > & out) static
Definition at line 52 of file weightedPosition.C.
References UPtrList< T >::first(), forAll, Foam::mag(), PtrList< T >::setSize(), and UPtrList< T >::size().
Referenced by snappySnapDriver::avgCellCentres().
setPoints()
void setPoints (const UList< point > & in, List< weightedPosition > & out) static
Definition at line 71 of file weightedPosition.C.
References UPtrList< T >::first(), forAll, PtrList< T >::setSize(), and UPtrList< T >::size().
plusEqOp()
void plusEqOp (weightedPosition & x, const weightedPosition & y) static
Definition at line 85 of file weightedPosition.C.
References UPtrList< T >::first(), x, and y.
Referenced by weightedPosition::syncPoints(), and weightedPosition::syncPoints().
operator()() [1/4]
void operator() (const vectorTensorTransform & vt, const bool forward, List< weightedPosition > & fld) const
Definition at line 96 of file weightedPosition.C.
References fld().
operator()() [2/4]
void operator() (const vectorTensorTransform & vt, const bool forward, List< List< weightedPosition > > & flds) const
Definition at line 119 of file weightedPosition.C.
References fld().
operator()() [3/4]
void operator() (const coupledPolyPatch & cpp, Field< weightedPosition > & fld) const
Definition at line 133 of file weightedPosition.C.
References fld().
operator()() [4/4]
template<template< class > class Container> void operator() (const coupledPolyPatch & cpp, Container< weightedPosition > & map) const
Definition at line 27 of file weightedPositionTemplates.C.
References UPtrList< T >::first(), fld(), forAllConstIters, forAllIters, and Foam::mag().
syncPoints() [1/2]
void syncPoints (const polyMesh & mesh, List< weightedPosition > & fld) static
Definition at line 148 of file weightedPosition.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, fld(), mesh, primitiveMesh::nPoints(), weightedPosition::plusEqOp(), UPtrList< T >::size(), and syncTools::syncPointList().
Referenced by snappySnapDriver::avgCellCentres().
syncPoints() [2/2]
void syncPoints (const polyMesh & mesh, const labelUList & meshPoints, List< weightedPosition > & fld) static
Definition at line 172 of file weightedPosition.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, fld(), mesh, weightedPosition::plusEqOp(), UPtrList< T >::size(), UList< T >::size(), and syncTools::syncPointList().
The documentation for this class was generated from the following files:
src/mesh/snappyHexMesh/meshRefinement/weightedPosition.H
src/mesh/snappyHexMesh/meshRefinement/weightedPosition.C
src/mesh/snappyHexMesh/meshRefinement/weightedPositionTemplates.C