OpenFOAM: stabilisedFvGeometryScheme Class Reference
stabilisedFvGeometryScheme Class Reference
Geometry calculation scheme that implements face geometry calculation using normal-component-of-area weighted triangle contributions.
#include <stabilisedFvGeometryScheme.H>
Public Member Functions
TypeName ("stabilised")
stabilisedFvGeometryScheme (const fvMesh &mesh, const dictionary &dict)
virtual ~stabilisedFvGeometryScheme ()=default
virtual void movePoints ()
Public Member Functions inherited from basicFvGeometryScheme
TypeName ("basic")
basicFvGeometryScheme (const fvMesh &mesh, const dictionary &dict)
virtual ~basicFvGeometryScheme ()=default
virtual tmp< surfaceScalarField > weights () const
virtual tmp< surfaceScalarField > deltaCoeffs () const
virtual tmp< surfaceScalarField > nonOrthDeltaCoeffs () const
virtual tmp< surfaceVectorField > nonOrthCorrectionVectors () const
Public Member Functions inherited from fvGeometryScheme
TypeName ("fvGeometryScheme")
declareRunTimeSelectionTable (tmp, fvGeometryScheme, dict,(const fvMesh &mesh, const dictionary &dict),(mesh, dict))
fvGeometryScheme (const fvMesh &mesh, const dictionary &dict)
virtual ~fvGeometryScheme ()=default
const fvMesh & mesh () const
virtual void updateMesh (const mapPolyMesh &mpm)
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Static Protected Member Functions
static void makeFaceCentresAndAreas (const polyMesh &mesh, const pointField &p, vectorField &fCtrs, vectorField &fAreas)
Additional Inherited Members
Static Public Member Functions inherited from fvGeometryScheme
static tmp< fvGeometryScheme > New (const fvMesh &mesh, const dictionary &dict, const word &defaultScheme)
Protected Member Functions inherited from fvGeometryScheme
bool setMeshPhi () const
Protected Attributes inherited from fvGeometryScheme
const fvMesh & mesh_
Detailed Description
Geometry calculation scheme that implements face geometry calculation using normal-component-of-area weighted triangle contributions.
This implements the Foundation 'Corrected face-centre calculations' as a separate geometry scheme. Only implements the primitiveMesh parts, not the individual face calculation.
Source files
stabilisedFvGeometryScheme.H
stabilisedFvGeometryScheme.C
Definition at line 54 of file stabilisedFvGeometryScheme.H.
Constructor & Destructor Documentation
stabilisedFvGeometryScheme()
stabilisedFvGeometryScheme (const fvMesh & mesh, const dictionary & dict)
Definition at line 137 of file stabilisedFvGeometryScheme.C.
References stabilisedFvGeometryScheme::movePoints().
~stabilisedFvGeometryScheme()
virtual ~stabilisedFvGeometryScheme () virtual default
Member Function Documentation
makeFaceCentresAndAreas()
void makeFaceCentresAndAreas (const polyMesh & mesh, const pointField & p, vectorField & fCtrs, vectorField & fAreas) static protected
Definition at line 45 of file stabilisedFvGeometryScheme.C.
References triangle< Point, PointRef >::areaNormal(), triangle< Point, PointRef >::centre(), f(), forAll, fvGeometryScheme::mesh(), Foam::normalised(), nPoints, p, UPtrList< T >::size(), and Foam::Zero.
TypeName()
TypeName ("stabilised")
movePoints()
void movePoints () virtual
Reimplemented from basicFvGeometryScheme.
Definition at line 152 of file stabilisedFvGeometryScheme.C.
References Foam::endl(), primitiveMeshTools::makeCellCentresAndVols(), fvGeometryScheme::movePoints(), Foam::Pout, and primitiveMesh::resetGeometry().
Referenced by stabilisedFvGeometryScheme::stabilisedFvGeometryScheme().
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/fvGeometryScheme/stabilised/stabilisedFvGeometryScheme.H
src/finiteVolume/fvMesh/fvGeometryScheme/stabilised/stabilisedFvGeometryScheme.C