OpenFOAM: pointFieldDecomposer Class Reference
pointFieldDecomposer Class Reference
Point field decomposer.
#include <pointFieldDecomposer.H>
Classes
class fieldsCache
class patchFieldDecomposer
Public Member Functions
pointFieldDecomposer (const Foam::zero, const pointMesh &procMesh, const labelList &pointAddressing, const labelList &boundaryAddressing)
pointFieldDecomposer (const pointMesh &completeMesh, const pointMesh &procMesh, const labelList &pointAddressing, const labelList &boundaryAddressing)
~pointFieldDecomposer ()=default
bool empty () const
void clear ()
void reset (const pointMesh &completeMesh)
template<class Type >
tmp< GeometricField< Type, pointPatchField, pointMesh > > decomposeField (const GeometricField< Type, pointPatchField, pointMesh > &) const
template<class GeoField >
void decomposeFields (const PtrList< GeoField > &fields) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::pointPatchField, Foam::pointMesh > > decomposeField (const GeometricField< Type, pointPatchField, pointMesh > &field) const
Detailed Description
Point field decomposer.
Source files
pointFieldDecomposer.H
pointFieldDecomposer.C
pointFieldDecomposerCache.C
pointFieldDecomposerTemplates.C
Definition at line 54 of file pointFieldDecomposer.H.
Constructor & Destructor Documentation
pointFieldDecomposer() [1/2]
pointFieldDecomposer (const Foam::zero , const pointMesh & procMesh, const labelList & pointAddressing, const labelList & boundaryAddressing)
Definition at line 73 of file pointFieldDecomposer.C.
pointFieldDecomposer() [2/2]
pointFieldDecomposer (const pointMesh & completeMesh, const pointMesh & procMesh, const labelList & pointAddressing, const labelList & boundaryAddressing)
Definition at line 89 of file pointFieldDecomposer.C.
References pointFieldDecomposer::reset().
~pointFieldDecomposer()
~pointFieldDecomposer () default
Member Function Documentation
empty()
bool empty () const
Definition at line 111 of file pointFieldDecomposer.C.
References UPtrList< T >::empty().
clear()
void clear ()
Definition at line 117 of file pointFieldDecomposer.C.
References PtrList< T >::clear().
reset()
void reset (const pointMesh & completeMesh)
Definition at line 123 of file pointFieldDecomposer.C.
References clear(), forAll, PtrList< T >::resize(), PtrList< T >::set(), and UPtrList< T >::size().
Referenced by pointFieldDecomposer::pointFieldDecomposer().
decomposeField() [1/2]
template<class Type > tmp< GeometricField< Type, pointPatchField, pointMesh > > decomposeField (const GeometricField< Type, pointPatchField, pointMesh > &) const
decomposeFields()
template<class GeoField > void decomposeFields (const PtrList< GeoField > & fields) const
Definition at line 93 of file pointFieldDecomposerTemplates.C.
References fields, fld(), and write().
Referenced by pointFieldDecomposer::fieldsCache::privateCache::decompose().
decomposeField() [2/2]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::pointPatchField, Foam::pointMesh > > decomposeField (const GeometricField< Type, pointPatchField, pointMesh > & field) const
Definition at line 29 of file pointFieldDecomposerTemplates.C.
References field(), forAll, Foam::New(), IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, PtrList< T >::set(), and UPtrList< T >::size().
The documentation for this class was generated from the following files:
src/parallel/decompose/decompose/pointFieldDecomposer.H
src/parallel/decompose/decompose/pointFieldDecomposer.C
src/parallel/decompose/decompose/pointFieldDecomposerTemplates.C