OpenFOAM: boundaryAdjointContributionIncompressible Class Reference
boundaryAdjointContributionIncompressible Class Reference
Contributions of objective function differentiation to adjoint boundary conditions for incompressible flows.
#include <boundaryAdjointContributionIncompressible.H>
Public Member Functions
TypeName ("incompressible")
boundaryAdjointContributionIncompressible (const word &managerName, const word &adjointSolverName, const word &simulationType, const fvPatch &patch)
virtual ~boundaryAdjointContributionIncompressible ()=default
tmp< scalarField > pressureSource ()
tmp< vectorField > velocitySource ()
tmp< vectorField > tangentVelocitySource ()
tmp< vectorField > normalVelocitySource ()
tmp< scalarField > energySource ()
tmp< scalarField > adjointTMVariable1Source ()
tmp< scalarField > adjointTMVariable2Source ()
tmp< scalarField > dJdnut ()
tmp< tensorField > dJdGradU ()
tmp< scalarField > momentumDiffusion ()
tmp< scalarField > laminarDiffusivity ()
tmp< scalarField > thermalDiffusion ()
tmp< scalarField > wallDistance ()
tmp< scalarField > TMVariable1Diffusion ()
tmp< scalarField > TMVariable2Diffusion ()
tmp< scalarField > TMVariable1 ()
tmp< scalarField > TMVariable2 ()
const fvPatchVectorField & Ub () const
const fvPatchScalarField & pb () const
const fvsPatchScalarField & phib () const
const fvPatchScalarField & turbulentDiffusivity () const
const fvPatchVectorField & Uab () const
const fvPatchScalarField & pab () const
const fvsPatchScalarField & phiab () const
const word primalSolverName () const
const word adjointSolverName () const
const incompressibleVars & primalVars () const
const incompressibleAdjointVars & adjointVars () const
objectiveManager & getObjectiveManager ()
template<class returnType , class sourceType , class castType >
Foam::tmp< Foam::Field< returnType > > sumContributions (PtrList< sourceType > &sourceList, const fvPatchField< returnType > &(castType::*boundaryFunction)(const label))
Public Member Functions inherited from boundaryAdjointContribution
TypeName ("boundaryAdjointContribution")
declareRunTimeSelectionTable (autoPtr, boundaryAdjointContribution, dictionary,(const word &managerName, const word &adjointSolverName, const word &simulationType, const fvPatch &patch),(managerName, adjointSolverName, simulationType, patch))
boundaryAdjointContribution (const word &managerName, const word &adjointSolverName, const word &simulationType, const fvPatch &patch)
virtual ~boundaryAdjointContribution ()=default
Protected Member Functions
template<class returnType , class sourceType , class castType >
tmp< Field< returnType > > sumContributions (PtrList< sourceType > &sourceList, const fvPatchField< returnType > &(castType::*boundaryFunction)(const label))
Protected Attributes
objectiveManager & objectiveManager_
const incompressibleVars & primalVars_
const incompressibleAdjointSolver & adjointSolver_
Protected Attributes inherited from boundaryAdjointContribution
const fvPatch & patch_
Additional Inherited Members
Static Public Member Functions inherited from boundaryAdjointContribution
static autoPtr< boundaryAdjointContribution > New (const word &managerName, const word &adjointSolverName, const word &simulationType, const fvPatch &patch)
Detailed Description
Contributions of objective function differentiation to adjoint boundary conditions for incompressible flows.
Source files
boundaryAdjointContributionIncompressible.H
boundaryAdjointContributionIncompressible.C
Definition at line 57 of file boundaryAdjointContributionIncompressible.H.
Constructor & Destructor Documentation
boundaryAdjointContributionIncompressible()
boundaryAdjointContributionIncompressible (const word & managerName, const word & adjointSolverName, const word & simulationType, const fvPatch & patch)
Definition at line 45 of file boundaryAdjointContributionIncompressible.C.
~boundaryAdjointContributionIncompressible()
virtual ~boundaryAdjointContributionIncompressible () virtual default
Member Function Documentation
sumContributions() [1/2]
template<class returnType , class sourceType , class castType > tmp< Field< returnType > > sumContributions (PtrList< sourceType > & sourceList, const fvPatchField< returnType > &(castType::*)(const label) boundaryFunction) protected
Referenced by boundaryAdjointContributionIncompressible::adjointTMVariable1Source(), boundaryAdjointContributionIncompressible::adjointTMVariable2Source(), boundaryAdjointContributionIncompressible::dJdGradU(), boundaryAdjointContributionIncompressible::dJdnut(), boundaryAdjointContributionIncompressible::energySource(), boundaryAdjointContributionIncompressible::normalVelocitySource(), boundaryAdjointContributionIncompressible::pressureSource(), boundaryAdjointContributionIncompressible::tangentVelocitySource(), and boundaryAdjointContributionIncompressible::velocitySource().
TypeName()
TypeName ("incompressible")
pressureSource()
tmp< scalarField > pressureSource () virtual
Implements boundaryAdjointContribution.
Definition at line 102 of file boundaryAdjointContributionIncompressible.C.
References boundaryAdjointContributionIncompressible::adjointVars(), objectiveIncompressible::boundarydJdvn(), objectiveManager::getObjectiveFunctions(), boundaryAdjointContributionIncompressible::objectiveManager_, boundaryAdjointContribution::patch_, and boundaryAdjointContributionIncompressible::sumContributions().
velocitySource()
tmp< vectorField > velocitySource () virtual
Implements boundaryAdjointContribution.
Definition at line 82 of file boundaryAdjointContributionIncompressible.C.
References boundaryAdjointContributionIncompressible::adjointVars(), objectiveIncompressible::boundarydJdv(), objectiveManager::getObjectiveFunctions(), boundaryAdjointContributionIncompressible::objectiveManager_, boundaryAdjointContribution::patch_, and boundaryAdjointContributionIncompressible::sumContributions().
tangentVelocitySource()
tmp< vectorField > tangentVelocitySource () virtual
Implements boundaryAdjointContribution.
Definition at line 127 of file boundaryAdjointContributionIncompressible.C.
References boundaryAdjointContributionIncompressible::adjointVars(), objectiveIncompressible::boundarydJdvt(), objectiveManager::getObjectiveFunctions(), boundaryAdjointContributionIncompressible::objectiveManager_, boundaryAdjointContribution::patch_, and boundaryAdjointContributionIncompressible::sumContributions().
normalVelocitySource()
tmp< vectorField > normalVelocitySource () virtual
Implements boundaryAdjointContribution.
Definition at line 155 of file boundaryAdjointContributionIncompressible.C.
References objectiveIncompressible::boundarydJdp(), objectiveManager::getObjectiveFunctions(), boundaryAdjointContributionIncompressible::objectiveManager_, and boundaryAdjointContributionIncompressible::sumContributions().
energySource()
tmp< scalarField > energySource () virtual
Implements boundaryAdjointContribution.
Definition at line 167 of file boundaryAdjointContributionIncompressible.C.
References objectiveIncompressible::boundarydJdT(), objectiveManager::getObjectiveFunctions(), boundaryAdjointContributionIncompressible::objectiveManager_, and boundaryAdjointContributionIncompressible::sumContributions().
adjointTMVariable1Source()
tmp< scalarField > adjointTMVariable1Source () virtual
Reimplemented from boundaryAdjointContribution.
Definition at line 180 of file boundaryAdjointContributionIncompressible.C.
References objectiveIncompressible::boundarydJdTMvar1(), objectiveManager::getObjectiveFunctions(), boundaryAdjointContributionIncompressible::objectiveManager_, and boundaryAdjointContributionIncompressible::sumContributions().
adjointTMVariable2Source()
tmp< scalarField > adjointTMVariable2Source () virtual
Reimplemented from boundaryAdjointContribution.
Definition at line 193 of file boundaryAdjointContributionIncompressible.C.
References objectiveIncompressible::boundarydJdTMvar2(), objectiveManager::getObjectiveFunctions(), boundaryAdjointContributionIncompressible::objectiveManager_, and boundaryAdjointContributionIncompressible::sumContributions().
dJdnut()
tmp< scalarField > dJdnut () virtual
Reimplemented from boundaryAdjointContribution.
Definition at line 206 of file boundaryAdjointContributionIncompressible.C.
References objectiveIncompressible::boundarydJdnut(), objectiveManager::getObjectiveFunctions(), boundaryAdjointContributionIncompressible::objectiveManager_, and boundaryAdjointContributionIncompressible::sumContributions().
dJdGradU()
tmp< tensorField > dJdGradU () virtual
Reimplemented from boundaryAdjointContribution.
Definition at line 218 of file boundaryAdjointContributionIncompressible.C.
References objectiveIncompressible::boundarydJdGradU(), objectiveManager::getObjectiveFunctions(), boundaryAdjointContributionIncompressible::objectiveManager_, and boundaryAdjointContributionIncompressible::sumContributions().
momentumDiffusion()
tmp< scalarField > momentumDiffusion () virtual
Implements boundaryAdjointContribution.
Definition at line 229 of file boundaryAdjointContributionIncompressible.C.
References boundaryAdjointContributionIncompressible::adjointVars(), and boundaryAdjointContribution::patch_.
laminarDiffusivity()
tmp< scalarField > laminarDiffusivity () virtual
Implements boundaryAdjointContribution.
Definition at line 236 of file boundaryAdjointContributionIncompressible.C.
References nu, turbulenceModel::nu(), boundaryAdjointContribution::patch_, boundaryAdjointContributionIncompressible::primalVars_, UPtrList< T >::size(), and Foam::Zero.
thermalDiffusion()
tmp< scalarField > thermalDiffusion () virtual
Implements boundaryAdjointContribution.
Definition at line 250 of file boundaryAdjointContributionIncompressible.C.
References boundaryAdjointContribution::patch_, UPtrList< T >::size(), WarningInFunction, and Foam::Zero.
wallDistance()
tmp< scalarField > wallDistance () virtual
Implements boundaryAdjointContribution.
Definition at line 269 of file boundaryAdjointContributionIncompressible.C.
References boundaryAdjointContribution::patch_, and boundaryAdjointContributionIncompressible::primalVars_.
TMVariable1Diffusion()
tmp< scalarField > TMVariable1Diffusion () virtual
Reimplemented from boundaryAdjointContribution.
Definition at line 276 of file boundaryAdjointContributionIncompressible.C.
References boundaryAdjointContributionIncompressible::adjointVars(), and boundaryAdjointContribution::patch_.
TMVariable2Diffusion()
tmp< scalarField > TMVariable2Diffusion () virtual
Reimplemented from boundaryAdjointContribution.
Definition at line 285 of file boundaryAdjointContributionIncompressible.C.
References boundaryAdjointContributionIncompressible::adjointVars(), and boundaryAdjointContribution::patch_.
TMVariable1()
tmp< scalarField > TMVariable1 () virtual
Reimplemented from boundaryAdjointContribution.
Definition at line 292 of file boundaryAdjointContributionIncompressible.C.
References boundaryAdjointContribution::patch_, and boundaryAdjointContributionIncompressible::primalVars_.
TMVariable2()
tmp< scalarField > TMVariable2 () virtual
Reimplemented from boundaryAdjointContribution.
Definition at line 300 of file boundaryAdjointContributionIncompressible.C.
References boundaryAdjointContribution::patch_, and boundaryAdjointContributionIncompressible::primalVars_.
Ub()
const fvPatchVectorField & Ub () const virtual
Implements boundaryAdjointContribution.
Definition at line 308 of file boundaryAdjointContributionIncompressible.C.
References boundaryAdjointContribution::patch_, and boundaryAdjointContributionIncompressible::primalVars_.
pb()
const fvPatchScalarField & pb () const virtual
Implements boundaryAdjointContribution.
Definition at line 314 of file boundaryAdjointContributionIncompressible.C.
References boundaryAdjointContribution::patch_, and boundaryAdjointContributionIncompressible::primalVars_.
phib()
const fvsPatchScalarField & phib () const virtual
Implements boundaryAdjointContribution.
Definition at line 321 of file boundaryAdjointContributionIncompressible.C.
References boundaryAdjointContribution::patch_, and boundaryAdjointContributionIncompressible::primalVars_.
turbulentDiffusivity()
const fvPatchScalarField & turbulentDiffusivity () const virtual
Implements boundaryAdjointContribution.
Definition at line 328 of file boundaryAdjointContributionIncompressible.C.
References boundaryAdjointContribution::patch_, and boundaryAdjointContributionIncompressible::primalVars_.
Uab()
const fvPatchVectorField & Uab () const virtual
Implements boundaryAdjointContribution.
Definition at line 338 of file boundaryAdjointContributionIncompressible.C.
References boundaryAdjointContributionIncompressible::adjointVars(), and boundaryAdjointContribution::patch_.
pab()
const fvPatchScalarField & pab () const virtual
Implements boundaryAdjointContribution.
Definition at line 344 of file boundaryAdjointContributionIncompressible.C.
References boundaryAdjointContributionIncompressible::adjointVars(), and boundaryAdjointContribution::patch_.
phiab()
const fvsPatchScalarField & phiab () const virtual
Implements boundaryAdjointContribution.
Definition at line 351 of file boundaryAdjointContributionIncompressible.C.
References boundaryAdjointContributionIncompressible::adjointVars(), and boundaryAdjointContribution::patch_.
primalSolverName()
const word primalSolverName () const virtual
Implements boundaryAdjointContribution.
Definition at line 357 of file boundaryAdjointContributionIncompressible.C.
References boundaryAdjointContributionIncompressible::primalVars_.
adjointSolverName()
const word adjointSolverName () const virtual
Implements boundaryAdjointContribution.
Definition at line 363 of file boundaryAdjointContributionIncompressible.C.
References boundaryAdjointContributionIncompressible::adjointVars().
primalVars()
const incompressibleVars & primalVars () const
Definition at line 370 of file boundaryAdjointContributionIncompressible.C.
References boundaryAdjointContributionIncompressible::primalVars_.
adjointVars()
const incompressibleAdjointVars & adjointVars () const
Definition at line 377 of file boundaryAdjointContributionIncompressible.C.
References boundaryAdjointContributionIncompressible::adjointSolver_.
Referenced by boundaryAdjointContributionIncompressible::adjointSolverName(), boundaryAdjointContributionIncompressible::momentumDiffusion(), boundaryAdjointContributionIncompressible::pab(), boundaryAdjointContributionIncompressible::phiab(), boundaryAdjointContributionIncompressible::pressureSource(), boundaryAdjointContributionIncompressible::tangentVelocitySource(), boundaryAdjointContributionIncompressible::TMVariable1Diffusion(), boundaryAdjointContributionIncompressible::TMVariable2Diffusion(), boundaryAdjointContributionIncompressible::Uab(), and boundaryAdjointContributionIncompressible::velocitySource().
getObjectiveManager()
objectiveManager & getObjectiveManager ()
Definition at line 384 of file boundaryAdjointContributionIncompressible.C.
References boundaryAdjointContributionIncompressible::objectiveManager_.
sumContributions() [2/2]
template<class returnType , class sourceType , class castType > Foam::tmp< Foam::Field< returnType > > sumContributions (PtrList< sourceType > & sourceList, const fvPatchField< returnType > &(castType::*)(const label) boundaryFunction)
Definition at line 27 of file boundaryAdjointContributionIncompressibleTemplates.C.
References boundaryAdjointContribution::New(), boundaryAdjointContribution::patch_, UPtrList< T >::size(), and Foam::Zero.
Member Data Documentation
objectiveManager_
objectiveManager& objectiveManager_ protected
Definition at line 82 of file boundaryAdjointContributionIncompressible.H.
Referenced by boundaryAdjointContributionIncompressible::adjointTMVariable1Source(), boundaryAdjointContributionIncompressible::adjointTMVariable2Source(), boundaryAdjointContributionIncompressible::dJdGradU(), boundaryAdjointContributionIncompressible::dJdnut(), boundaryAdjointContributionIncompressible::energySource(), boundaryAdjointContributionIncompressible::getObjectiveManager(), boundaryAdjointContributionIncompressible::normalVelocitySource(), boundaryAdjointContributionIncompressible::pressureSource(), boundaryAdjointContributionIncompressible::tangentVelocitySource(), and boundaryAdjointContributionIncompressible::velocitySource().
primalVars_
const incompressibleVars& primalVars_ protected
Definition at line 84 of file boundaryAdjointContributionIncompressible.H.
Referenced by boundaryAdjointContributionIncompressible::laminarDiffusivity(), boundaryAdjointContributionIncompressible::pb(), boundaryAdjointContributionIncompressible::phib(), boundaryAdjointContributionIncompressible::primalSolverName(), boundaryAdjointContributionIncompressible::primalVars(), boundaryAdjointContributionIncompressible::TMVariable1(), boundaryAdjointContributionIncompressible::TMVariable2(), boundaryAdjointContributionIncompressible::turbulentDiffusivity(), boundaryAdjointContributionIncompressible::Ub(), and boundaryAdjointContributionIncompressible::wallDistance().
adjointSolver_
const incompressibleAdjointSolver& adjointSolver_ protected
Definition at line 91 of file boundaryAdjointContributionIncompressible.H.
Referenced by boundaryAdjointContributionIncompressible::adjointVars().
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/boundaryAdjointContributions/boundaryAdjointContributionIncompressible/boundaryAdjointContributionIncompressible.H
src/optimisation/adjointOptimisation/adjoint/boundaryAdjointContributions/boundaryAdjointContributionIncompressible/boundaryAdjointContributionIncompressible.C
src/optimisation/adjointOptimisation/adjoint/boundaryAdjointContributions/boundaryAdjointContributionIncompressible/boundaryAdjointContributionIncompressibleTemplates.C