OpenFOAM: meshSearch Class Reference
meshSearch Class Reference
Various (local, not parallel) searches on polyMesh; uses (demand driven) octree to search.
#include <meshSearch.H>
Public Member Functions
ClassName ("meshSearch")
meshSearch (const polyMesh &mesh, const polyMesh::cellDecomposition=polyMesh::CELL_TETS)
meshSearch (const polyMesh &mesh, const treeBoundBox &bb, const polyMesh::cellDecomposition=polyMesh::CELL_TETS)
~meshSearch ()
const polyMesh & mesh () const
polyMesh::cellDecomposition decompMode () const
const indexedOctree< treeDataFace > & boundaryTree () const
const indexedOctree< treeDataFace > & nonCoupledBoundaryTree () const
const indexedOctree< treeDataCell > & cellTree () const
label findNearestCell (const point &location, const label seedCelli=-1, const bool useTreeSearch=true) const
label findNearestFace (const point &location, const label seedFacei=-1, const bool useTreeSearch=true) const
label findCell (const point &location, const label seedCelli=-1, const bool useTreeSearch=true) const
label findNearestBoundaryFace (const point &location, const label seedFacei=-1, const bool useTreeSearch=true) const
pointIndexHit intersection (const point &pStart, const point &pEnd) const
List< pointIndexHit > intersections (const point &pStart, const point &pEnd) const
bool isInside (const point &) const
void clearOut ()
void correct ()
Static Public Attributes
static scalar tol_ = 1e-3
Detailed Description
Various (local, not parallel) searches on polyMesh; uses (demand driven) octree to search.
Source files
meshSearch.H
meshSearch.C
Definition at line 56 of file meshSearch.H.
Constructor & Destructor Documentation
meshSearch() [1/2]
meshSearch (const polyMesh & mesh, const polyMesh::cellDecomposition cellDecompMode = polyMesh::CELL_TETS) explicit
Definition at line 533 of file meshSearch.C.
References polyMesh::CELL_TETS, polyMesh::FACE_DIAG_TRIS, and meshSearch::mesh().
meshSearch() [2/2]
meshSearch (const polyMesh & mesh, const treeBoundBox & bb, const polyMesh::cellDecomposition cellDecompMode = polyMesh::CELL_TETS)
Definition at line 554 of file meshSearch.C.
References polyMesh::CELL_TETS, polyMesh::FACE_DIAG_TRIS, and meshSearch::mesh().
~meshSearch()
~meshSearch ()
Definition at line 580 of file meshSearch.C.
Member Function Documentation
ClassName()
ClassName ("meshSearch")
mesh()
const polyMesh & mesh () const inline
Definition at line 191 of file meshSearch.H.
Referenced by meshSearch::meshSearch(), and meshSearch::meshSearch().
decompMode()
polyMesh::cellDecomposition decompMode () const inline
Definition at line 196 of file meshSearch.H.
boundaryTree()
const Foam::indexedOctree< Foam::treeDataFace > & boundaryTree () const
Definition at line 609 of file meshSearch.C.
nonCoupledBoundaryTree()
const Foam::indexedOctree< Foam::treeDataFace > & nonCoupledBoundaryTree () const
Definition at line 640 of file meshSearch.C.
References forAll, patches, pp(), and PtrList< T >::resize().
cellTree()
const Foam::indexedOctree< Foam::treeDataCell > & cellTree () const
Definition at line 681 of file meshSearch.C.
findNearestCell()
Foam::label findNearestCell (const point & location, const label seedCelli = -1, const bool useTreeSearch = true) const
Definition at line 707 of file meshSearch.C.
findNearestFace()
Foam::label findNearestFace (const point & location, const label seedFacei = -1, const bool useTreeSearch = true) const
Definition at line 730 of file meshSearch.C.
findCell()
Foam::label findCell (const point & location, const label seedCelli = -1, const bool useTreeSearch = true) const
Definition at line 753 of file meshSearch.C.
findNearestBoundaryFace()
Foam::label findNearestBoundaryFace (const point & location, const label seedFacei = -1, const bool useTreeSearch = true) const
Definition at line 777 of file meshSearch.C.
References f(), PointIndexHit< PointType >::hit(), PointIndexHit< PointType >::index(), Foam::sqr(), and tree().
intersection()
Foam::pointIndexHit intersection (const point & pStart, const point & pEnd) const
Definition at line 843 of file meshSearch.C.
intersections()
Foam::List< Foam::pointIndexHit > intersections (const point & pStart, const point & pEnd) const
Definition at line 860 of file meshSearch.C.
References PtrList< T >::append().
isInside()
bool isInside (const point & p) const
Definition at line 887 of file meshSearch.C.
References volumeType::INSIDE, and p.
clearOut()
void clearOut ()
Definition at line 893 of file meshSearch.C.
References PtrList< T >::clear().
correct()
void correct ()
Definition at line 901 of file meshSearch.C.
Member Data Documentation
tol_
scalar tol_ = 1e-3 static
Definition at line 159 of file meshSearch.H.
The documentation for this class was generated from the following files:
src/meshTools/meshSearch/meshSearch.H
src/meshTools/meshSearch/meshSearch.C