OpenFOAM: StringStreamAllocator< StreamType > Class Template Reference
StringStreamAllocator< StreamType > Class Template Reference
#include <StringStream.H>
Public Member Functions
Foam::string str () const
void str (const std::string &s)
Protected Types
typedef StreamType stream_type
Protected Member Functions
StringStreamAllocator ()=default
StringStreamAllocator (const std::string &s)
Protected Attributes
stream_type stream_
Detailed Description
template<class StreamType>
class Foam::Detail::StringStreamAllocator< StreamType >
Definition at line 56 of file StringStream.H.
Member Typedef Documentation
stream_type
template<class StreamType > typedef StreamType stream_type protected
Definition at line 63 of file StringStream.H.
Constructor & Destructor Documentation
StringStreamAllocator() [1/2]
template<class StreamType > StringStreamAllocator () protected default
StringStreamAllocator() [2/2]
template<class StreamType > StringStreamAllocator (const std::string & s) inline protected
Definition at line 75 of file StringStream.H.
Member Function Documentation
str() [1/2]
template<class StreamType > Foam::string str () const inline
Definition at line 86 of file StringStream.H.
References StringStreamAllocator< StreamType >::stream_.
Referenced by Foam::entryToString(), Foam::name(), Foam::name(), Foam::name(), expressionEntry::toExprStr(), accessor::toString(), and decomposedBlockData::writeBlockEntry().
str() [2/2]
template<class StreamType > void str (const std::string & s) inline
Definition at line 92 of file StringStream.H.
References s(), and StringStreamAllocator< StreamType >::stream_.
Member Data Documentation
stream_
template<class StreamType > stream_type stream_ protected
Definition at line 66 of file StringStream.H.
Referenced by StringStreamAllocator< StreamType >::str(), and StringStreamAllocator< StreamType >::str().
The documentation for this class was generated from the following file:
src/OpenFOAM/db/IOstreams/StringStreams/StringStream.H