OpenFOAM: optionList Class Reference
optionList Class Reference
List of finite volume options.
#include <fvOptionList.H>
Public Member Functions
TypeName ("optionList")
optionList (const fvMesh &mesh)
optionList (const fvMesh &mesh, const dictionary &dict)
virtual ~optionList ()=default
void reset (const dictionary &dict)
bool appliesToField (const word &fieldName) const
template<class Type >
tmp< fvMatrix< Type > > operator() (GeometricField< Type, fvPatchField, volMesh > &field)
template<class Type >
tmp< fvMatrix< Type > > operator() (GeometricField< Type, fvPatchField, volMesh > &field, const word &fieldName)
template<class Type >
tmp< fvMatrix< Type > > operator() (const volScalarField &rho, GeometricField< Type, fvPatchField, volMesh > &field)
template<class Type >
tmp< fvMatrix< Type > > operator() (const volScalarField &rho, GeometricField< Type, fvPatchField, volMesh > &field, const word &fieldName)
template<class Type >
tmp< fvMatrix< Type > > operator() (const volScalarField &alpha, const volScalarField &rho, GeometricField< Type, fvPatchField, volMesh > &field)
template<class Type >
tmp< fvMatrix< Type > > operator() (const volScalarField &alpha, const volScalarField &rho, GeometricField< Type, fvPatchField, volMesh > &field, const word &fieldName)
template<class Type >
tmp< fvMatrix< Type > > operator() (const volScalarField &alpha, const geometricOneField &rho, GeometricField< Type, fvPatchField, volMesh > &field)
template<class Type >
tmp< fvMatrix< Type > > operator() (const geometricOneField &alpha, const volScalarField &rho, GeometricField< Type, fvPatchField, volMesh > &field)
template<class Type >
tmp< fvMatrix< Type > > operator() (const geometricOneField &alpha, const geometricOneField &rho, GeometricField< Type, fvPatchField, volMesh > &field)
template<class Type >
tmp< fvMatrix< Type > > d2dt2 (GeometricField< Type, fvPatchField, volMesh > &field)
template<class Type >
tmp< fvMatrix< Type > > d2dt2 (GeometricField< Type, fvPatchField, volMesh > &field, const word &fieldName)
template<class Type >
void constrain (fvMatrix< Type > &eqn)
template<class Type >
void correct (GeometricField< Type, fvPatchField, volMesh > &field)
template<class Type >
void postProcessSens (Field< Type > &sensField, const word &fieldName=word::null, const word &designVariablesName=word::null)
virtual bool read (const dictionary &dict)
virtual bool writeData (Ostream &os) const
Public Member Functions inherited from PtrList< fv::option >
constexpr PtrList () noexcept
PtrList (const label len)
PtrList (const PtrList< fv::option > &list)
PtrList (PtrList< fv::option > &&list)
PtrList (UList< fv::option * > &list)
PtrList (const PtrList< fv::option > &list, const CloneArg &cloneArgs)
PtrList (PtrList< fv::option > &list, bool reuse)
PtrList (const SLPtrList< fv::option > &list)
PtrList (Istream &is, const INew &inew)
PtrList (Istream &is)
~PtrList ()
PtrList< fv::option > clone (Args &&... args) const
Foam::PtrList< fv::option > clone (Args &&... args) const
const fv::option * set (const label i) const
autoPtr< fv::option > set (const label i, fv::option *ptr)
autoPtr< fv::option > set (const label i, std::unique_ptr< fv::option > &&ptr)
autoPtr< fv::option > set (const label i, autoPtr< fv::option > &&ptr)
autoPtr< fv::option > set (const label i, const refPtr< fv::option > &ptr)
autoPtr< fv::option > set (const label i, const tmp< fv::option > &ptr)
autoPtr< fv::option > set (const label i, autoPtr< fv::option > &ptr)
void clear ()
void free ()
void resize (const label newLen)
fv::option & emplace_back (Args &&... args)
void push_back (fv::option *ptr)
void push_back (std::unique_ptr< fv::option > &&ptr)
void push_back (autoPtr< fv::option > &&ptr)
void push_back (const refPtr< fv::option > &ptr)
void push_back (const tmp< fv::option > &ptr)
void push_back (PtrList< fv::option > &&other)
void push_back (autoPtr< fv::option > &ptr)=delete
fv::option & emplace_set (const label i, Args &&... args)
fv::option & emplace (const label i, Args &&... args)
autoPtr< fv::option > release (const label i)
void transfer (PtrList< fv::option > &list)
void operator= (const PtrList< fv::option > &list)
void operator= (PtrList< fv::option > &&list)
void setSize (const label newLen)
void append (autoPtr< fv::option > &ptr)
void append (fv::option *ptr)
void append (std::unique_ptr< fv::option > &&ptr)
void append (autoPtr< fv::option > &&ptr)
void append (const refPtr< fv::option > &ptr)
void append (const tmp< fv::option > &ptr)
void append (PtrList< fv::option > &&other)
Public Member Functions inherited from UPtrList< T >
constexpr UPtrList () noexcept
UPtrList (const label len)
UPtrList (const UPtrList< T > &list)
UPtrList (UPtrList< T > &&list)
UPtrList (UPtrList< T > &list, bool reuse)
UPtrList (PtrList< T > &list)
UPtrList (const UList< T * > &list)
UPtrList (UList< T > &list)
bool empty () const noexcept
label size () const noexcept
label count () const noexcept
T & front ()
const T & front () const
T & back ()
const T & back () const
const T * test (const label i) const
const T * get (const label i) const
T * get (const label i)
const T * set (const label i) const
void clear ()
void free ()
void resize (const label newLen)
label squeezeNull ()
void trimTrailingNull ()
void push_back (T *ptr)
void push_back (UPtrList< T > &&other)
void swap (UPtrList< T > &list)
void transfer (UPtrList< T > &list)
T * set (const label i, T *ptr)
void reorder (const labelUList &oldToNew, const bool check=false)
void sortOrder (const labelUList &order, const bool check=false)
void checkNonNull () const
const T & at (const label i) const
T & at (const label i)
const T & operator[] (const label i) const
T & operator[] (const label i)
FOAM_DEPRECATED_FOR (2022-09, "get(), set() or test() methods") const T *operator()(const label i) const
void operator= (const UPtrList< T > &list)
void operator= (UPtrList< T > &&list)
T ** begin_ptr () noexcept
T ** end_ptr () noexcept
iterator begin ()
iterator end () noexcept
const_iterator cbegin () const
const_iterator cend () const noexcept
const_iterator begin () const
const_iterator end () const noexcept
void setSize (const label n)
T & first ()
const T & first () const
T & last ()
const T & last () const
void append (T *ptr)
void append (UPtrList< T > &&other)
Protected Member Functions
bool readOptions (const dictionary &dict)
void checkApplied () const
template<class Type >
tmp< fvMatrix< Type > > source (GeometricField< Type, fvPatchField, volMesh > &field, const word &fieldName, const dimensionSet &ds)
optionList (const optionList &)=delete
void operator= (const optionList &)=delete
Protected Member Functions inherited from PtrList< fv::option >
void readIstream (Istream &is, const INew &inew)
Protected Member Functions inherited from UPtrList< T >
void setAddressableSize (const label n) noexcept
label find_next (label pos) const
UPtrList (Detail::PtrListDetail< T > &&ptrs)
Static Protected Member Functions
static const dictionary & optionsDict (const dictionary &dict)
Protected Attributes
const fvMesh & mesh_
label checkTimeIndex_
Protected Attributes inherited from UPtrList< T >
Detail::PtrListDetail< T > ptrs_
Friends
Ostream & operator<< (Ostream &os, const optionList &options)
Additional Inherited Members
Public Types inherited from UPtrList< T >
typedef T value_type
typedef T & reference
typedef const T & const_reference
Detailed Description
List of finite volume options.
SourceFile optionList.C
Definition at line 63 of file fvOptionList.H.
Constructor & Destructor Documentation
optionList() [1/3]
optionList (const optionList &) protected delete
Referenced by kEpsilonLopesdaCosta< BasicTurbulenceModel >::setPorosityCoefficients().
optionList() [2/3]
optionList (const fvMesh & mesh) explicit
Definition at line 77 of file fvOptionList.C.
References fv().
optionList() [3/3]
optionList (const fvMesh & mesh, const dictionary & dict)
Definition at line 85 of file fvOptionList.C.
References dict, fv(), optionList::optionsDict(), and optionList::reset().
~optionList()
virtual ~optionList () virtual default
Member Function Documentation
optionsDict()
const Foam::dictionary & optionsDict (const dictionary & dict) static protected
Definition at line 38 of file fvOptionList.C.
References dict, and keyType::LITERAL.
Referenced by optionList::optionList().
readOptions()
bool readOptions (const dictionary & dict) protected
Definition at line 49 of file fvOptionList.C.
References dict.
checkApplied()
void checkApplied () const protected
Definition at line 63 of file fvOptionList.C.
Referenced by optionList::source().
source()
template<class Type > tmp< fvMatrix< Type > > source (GeometricField< Type, fvPatchField, volMesh > & field, const word & fieldName, const dimensionSet & ds) protected
Referenced by optionList::source().
operator=()
void operator= (const optionList &) protected delete
TypeName()
TypeName ("optionList")
reset()
void reset (const dictionary & dict)
Definition at line 95 of file fvOptionList.C.
References dict, Foam::name(), option::New(), and resize().
Referenced by optionList::optionList().
appliesToField()
bool appliesToField (const word & fieldName) const
Definition at line 127 of file fvOptionList.C.
operator()() [1/9]
template<class Type > tmp< fvMatrix< Type > > operator() (GeometricField< Type, fvPatchField, volMesh > & field)
operator()() [2/9]
template<class Type > tmp< fvMatrix< Type > > operator() (GeometricField< Type, fvPatchField, volMesh > & field, const word & fieldName)
operator()() [3/9]
template<class Type > tmp< fvMatrix< Type > > operator() (const volScalarField & rho, GeometricField< Type, fvPatchField, volMesh > & field)
operator()() [4/9]
template<class Type > tmp< fvMatrix< Type > > operator() (const volScalarField & rho, GeometricField< Type, fvPatchField, volMesh > & field, const word & fieldName)
operator()() [5/9]
template<class Type > tmp< fvMatrix< Type > > operator() (const volScalarField & alpha, const volScalarField & rho, GeometricField< Type, fvPatchField, volMesh > & field)
operator()() [6/9]
template<class Type > tmp< fvMatrix< Type > > operator() (const volScalarField & alpha, const volScalarField & rho, GeometricField< Type, fvPatchField, volMesh > & field, const word & fieldName)
operator()() [7/9]
template<class Type > tmp< fvMatrix< Type > > operator() (const volScalarField & alpha, const geometricOneField & rho, GeometricField< Type, fvPatchField, volMesh > & field)
operator()() [8/9]
template<class Type > tmp< fvMatrix< Type > > operator() (const geometricOneField & alpha, const volScalarField & rho, GeometricField< Type, fvPatchField, volMesh > & field)
operator()() [9/9]
template<class Type > tmp< fvMatrix< Type > > operator() (const geometricOneField & alpha, const geometricOneField & rho, GeometricField< Type, fvPatchField, volMesh > & field)
d2dt2() [1/2]
template<class Type > tmp< fvMatrix< Type > > d2dt2 (GeometricField< Type, fvPatchField, volMesh > & field)
d2dt2() [2/2]
template<class Type > tmp< fvMatrix< Type > > d2dt2 (GeometricField< Type, fvPatchField, volMesh > & field, const word & fieldName)
constrain()
template<class Type > void constrain (fvMatrix< Type > & eqn)
Definition at line 307 of file fvOptionListTemplates.C.
References addProfiling, Foam::endl(), and Foam::Info.
Referenced by incompressiblePrimalSolver::correctBoundaryConditions(), adjointSimple::mainIter(), simple::mainIter(), displacementComponentLaplacianFvMotionSolver::solve(), velocityComponentLaplacianFvMotionSolver::solve(), displacementLaplacianFvMotionSolver::solve(), displacementSBRStressFvMotionSolver::solve(), solidBodyDisplacementLaplacianFvMotionSolver::solve(), surfaceAlignedSBRStressFvMotionSolver::solve(), and velocityLaplacianFvMotionSolver::solve().
correct()
template<class Type > void correct (GeometricField< Type, fvPatchField, volMesh > & field)
Definition at line 347 of file fvOptionListTemplates.C.
References addProfiling, Foam::endl(), field(), and Foam::Info.
Referenced by adjointSimple::mainIter(), simple::mainIter(), displacementComponentLaplacianFvMotionSolver::solve(), velocityComponentLaplacianFvMotionSolver::solve(), displacementLaplacianFvMotionSolver::solve(), displacementSBRStressFvMotionSolver::solve(), solidBodyDisplacementLaplacianFvMotionSolver::solve(), surfaceAlignedSBRStressFvMotionSolver::solve(), and velocityLaplacianFvMotionSolver::solve().
postProcessSens()
template<class Type > void postProcessSens (Field< Type > & sensField, const word & fieldName = word::null, const word & designVariablesName = word::null)
Definition at line 390 of file fvOptionListTemplates.C.
References addProfiling, Foam::endl(), and Foam::Info.
read()
bool read (const dictionary & dict) virtual
Reimplemented in options.
Definition at line 143 of file fvOptionList.C.
References dict.
Referenced by options::read().
writeData()
bool writeData (Ostream & os) const virtual
Definition at line 149 of file fvOptionList.C.
References Foam::nl, and os().
Referenced by Foam::operator<<().
Friends And Related Symbol Documentation
operator<<
Ostream & operator<< (Ostream & os, const optionList & options) friend
Member Data Documentation
mesh_
const fvMesh& mesh_ protected
Definition at line 72 of file fvOptionList.H.
checkTimeIndex_
label checkTimeIndex_ protected
Definition at line 75 of file fvOptionList.H.
The documentation for this class was generated from the following files:
src/finiteVolume/cfdTools/general/fvOptions/fvOptionList.H
src/finiteVolume/cfdTools/general/fvOptions/fvOptionList.C
src/finiteVolume/cfdTools/general/fvOptions/fvOptionListTemplates.C