OpenFOAM: linearViscousStress< BasicTurbulenceModel > Class Template Reference
linearViscousStress< BasicTurbulenceModel > Class Template Reference abstract
Turbulence models
Linear viscous stress turbulence model base class.
#include <linearViscousStress.H>
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
linearViscousStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~linearViscousStress ()=default
virtual bool read ()=0
virtual tmp< volSymmTensorField > devRhoReff () const
virtual tmp< volSymmTensorField > devRhoReff (const volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
virtual void correct ()=0
Detailed Description
template<class BasicTurbulenceModel>
class Foam::linearViscousStress< BasicTurbulenceModel >
Linear viscous stress turbulence model base class.
Source files
linearViscousStress.H
linearViscousStress.C
Definition at line 49 of file linearViscousStress.H.
Member Typedef Documentation
alphaField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 56 of file linearViscousStress.H.
rhoField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 57 of file linearViscousStress.H.
transportModel
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 58 of file linearViscousStress.H.
Constructor & Destructor Documentation
linearViscousStress()
template<class BasicTurbulenceModel > linearViscousStress (const word & modelName, const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName)
Definition at line 29 of file linearViscousStress.C.
~linearViscousStress()
template<class BasicTurbulenceModel > virtual ~linearViscousStress () virtual default
Member Function Documentation
read()
template<class BasicTurbulenceModel > bool read () pure virtual
Implemented in PDRkEpsilon, kEpsilonLopesdaCosta< BasicTurbulenceModel >, kL< BasicTurbulenceModel >, kineticTheoryModel, phasePressureModel, kineticTheoryModel, phasePressureModel, buoyantKEpsilon< BasicTurbulenceModel >, kkLOmega, LamBremhorstKE, LienCubicKE, LienLeschziner, qZeta, ShihQuadraticKE, continuousGasKEqn< BasicTurbulenceModel >, NicenoKEqn< BasicTurbulenceModel >, SmagorinskyZhang< BasicTurbulenceModel >, continuousGasKEpsilon< BasicTurbulenceModel >, kOmegaSSTSato< BasicTurbulenceModel >, LaheyKEpsilon< BasicTurbulenceModel >, mixtureKEpsilon< BasicTurbulenceModel >, kOmegaSSTBase< eddyViscosity< RASModel< BasicTurbulenceModel > > >, SpalartAllmarasBase< eddyViscosity< RASModel< BasicTurbulenceModel > > >, DESModel< BasicTurbulenceModel >, generalizedNewtonian< BasicMomentumTransportModel >, Stokes< BasicTurbulenceModel >, dynamicKEqn< BasicTurbulenceModel >, dynamicLagrangian< BasicTurbulenceModel >, kEqn< BasicTurbulenceModel >, LESeddyViscosity< BasicTurbulenceModel >, sigma< BasicTurbulenceModel >, Smagorinsky< BasicTurbulenceModel >, WALE< BasicTurbulenceModel >, kEpsilon< BasicTurbulenceModel >, kEpsilon< EddyDiffusivity< compressible::turbulenceModel > >, kEpsilonPhitF< BasicTurbulenceModel >, kOmega< BasicTurbulenceModel >, kOmegaSSTLM< BasicTurbulenceModel >, kOmegaSSTSAS< BasicTurbulenceModel >, LaunderSharmaKE< BasicTurbulenceModel >, realizableKE< BasicTurbulenceModel >, RNGkEpsilon< BasicTurbulenceModel >, eddyViscosity< BasicTurbulenceModel >, eddyViscosity< incompressible::RASModel >, eddyViscosity< LESModel< BasicTurbulenceModel > >, eddyViscosity< RASModel< BasicTurbulenceModel > >, eddyViscosity< RASModel< EddyDiffusivity< compressible::turbulenceModel > > >, eddyViscosity< RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > > >, and eddyViscosity< RASModel< EddyDiffusivity< ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > > > > >.
Definition at line 58 of file linearViscousStress.C.
devRhoReff() [1/2]
template<class BasicTurbulenceModel > Foam::tmp< Foam::volSymmTensorField > devRhoReff () const virtual
Reimplemented in kineticTheoryModel, phasePressureModel, kineticTheoryModel, phasePressureModel, nonlinearEddyViscosity< BasicTurbulenceModel >, and nonlinearEddyViscosity< incompressible::RASModel >.
Definition at line 66 of file linearViscousStress.C.
devRhoReff() [2/2]
template<class BasicTurbulenceModel > Foam::tmp< Foam::volSymmTensorField > devRhoReff (const volVectorField & U) const virtual
Reimplemented in kineticTheoryModel, phasePressureModel, kineticTheoryModel, phasePressureModel, nonlinearEddyViscosity< BasicTurbulenceModel >, and nonlinearEddyViscosity< incompressible::RASModel >.
Definition at line 74 of file linearViscousStress.C.
divDevRhoReff() [1/2]
template<class BasicTurbulenceModel > Foam::tmp< Foam::fvVectorMatrix > divDevRhoReff (volVectorField & U) const virtual
Reimplemented in kineticTheoryModel, phasePressureModel, kineticTheoryModel, phasePressureModel, nonlinearEddyViscosity< BasicTurbulenceModel >, and nonlinearEddyViscosity< incompressible::RASModel >.
Definition at line 100 of file linearViscousStress.C.
divDevRhoReff() [2/2]
template<class BasicTurbulenceModel > Foam::tmp< Foam::fvVectorMatrix > divDevRhoReff (const volScalarField & rho, volVectorField & U) const virtual
Reimplemented in nonlinearEddyViscosity< BasicTurbulenceModel >, and nonlinearEddyViscosity< incompressible::RASModel >.
Definition at line 115 of file linearViscousStress.C.
References Foam::dev2(), Foam::fvc::div(), Foam::fvc::grad(), Foam::fvm::laplacian(), rho, T, and U.
correct()
template<class BasicTurbulenceModel > void correct () pure virtual
Implemented in PDRkEpsilon, kEpsilonLopesdaCosta< BasicTurbulenceModel >, kL< BasicTurbulenceModel >, kineticTheoryModel, phasePressureModel, kineticTheoryModel, phasePressureModel, kkLOmega, LamBremhorstKE, LienCubicKE, LienLeschziner, qZeta, ShihQuadraticKE, kOmegaSSTSato< BasicTurbulenceModel >, LaheyKEpsilon< BasicTurbulenceModel >, mixtureKEpsilon< BasicTurbulenceModel >, kOmegaSSTBase< eddyViscosity< RASModel< BasicTurbulenceModel > > >, SpalartAllmarasBase< eddyViscosity< RASModel< BasicTurbulenceModel > > >, generalizedNewtonian< BasicMomentumTransportModel >, Stokes< BasicTurbulenceModel >, dynamicKEqn< BasicTurbulenceModel >, dynamicLagrangian< BasicTurbulenceModel >, kEqn< BasicTurbulenceModel >, sigma< BasicTurbulenceModel >, Smagorinsky< BasicTurbulenceModel >, WALE< BasicTurbulenceModel >, kEpsilon< BasicTurbulenceModel >, kEpsilon< EddyDiffusivity< compressible::turbulenceModel > >, kEpsilonPhitF< BasicTurbulenceModel >, kOmega< BasicTurbulenceModel >, kOmegaSSTLM< BasicTurbulenceModel >, LaunderSharmaKE< BasicTurbulenceModel >, realizableKE< BasicTurbulenceModel >, RNGkEpsilon< BasicTurbulenceModel >, eddyViscosity< BasicTurbulenceModel >, eddyViscosity< incompressible::RASModel >, eddyViscosity< LESModel< BasicTurbulenceModel > >, eddyViscosity< RASModel< BasicTurbulenceModel > >, eddyViscosity< RASModel< EddyDiffusivity< compressible::turbulenceModel > > >, eddyViscosity< RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > > >, and eddyViscosity< RASModel< EddyDiffusivity< ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > > > > >.
Definition at line 130 of file linearViscousStress.C.
Referenced by kOmegaSSTSato< BasicTurbulenceModel >::correct(), dynamicKEqn< BasicTurbulenceModel >::correct(), dynamicLagrangian< BasicTurbulenceModel >::correct(), kEqn< BasicTurbulenceModel >::correct(), sigma< BasicTurbulenceModel >::correct(), Smagorinsky< BasicTurbulenceModel >::correct(), WALE< BasicTurbulenceModel >::correct(), and kOmegaSSTLM< BasicTurbulenceModel >::correct().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/linearViscousStress/linearViscousStress.H
src/TurbulenceModels/turbulenceModels/linearViscousStress/linearViscousStress.C