OpenFOAM: meshToMeshData Class Reference
meshToMeshData Class Reference
Transfers refinement levels such that slow transition between levels is maintained. Used in FaceCellWave.
#include <meshToMeshData.H>
Classes
class trackData
Public Member Functions
meshToMeshData ()
meshToMeshData (const label tgtCelli)
label tgtCell () const
label & tgtCell ()
template<class TrackingData >
bool valid (TrackingData &) const
template<class TrackingData >
bool sameGeometry (const polyMesh &, const meshToMeshData &, const scalar, TrackingData &) const
template<class TrackingData >
void leaveDomain (const polyMesh &, const polyPatch &, const label patchFacei, const point &faceCentre, TrackingData &)
template<class TrackingData >
void enterDomain (const polyMesh &, const polyPatch &, const label patchFacei, const point &faceCentre, TrackingData &)
template<class TrackingData >
void transform (const polyMesh &, const tensor &, TrackingData &)
template<class TrackingData >
bool updateCell (const polyMesh &, const label thisCelli, const label neighbourFacei, const meshToMeshData &neighbourInfo, const scalar tol, TrackingData &)
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFacei, const label neighbourCelli, const meshToMeshData &neighbourInfo, const scalar tol, TrackingData &)
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFacei, const meshToMeshData &neighbourInfo, const scalar tol, TrackingData &)
template<class TrackingData >
bool equal (const meshToMeshData &, TrackingData &) const
bool operator== (const meshToMeshData &) const
bool operator!= (const meshToMeshData &) const
Friends
Ostream & operator<< (Ostream &, const meshToMeshData &)
Istream & operator>> (Istream &, meshToMeshData &)
Detailed Description
Transfers refinement levels such that slow transition between levels is maintained. Used in FaceCellWave.
Source files
meshToMeshData.H
meshToMeshDataI.H
meshToMeshData.C
Definition at line 58 of file meshToMeshData.H.
Constructor & Destructor Documentation
meshToMeshData() [1/2]
meshToMeshData () inline
Definition at line 25 of file meshToMeshDataI.H.
meshToMeshData() [2/2]
meshToMeshData (const label tgtCelli) inline
Definition at line 31 of file meshToMeshDataI.H.
Member Function Documentation
tgtCell() [1/2]
label tgtCell () const inline
Definition at line 97 of file meshToMeshData.H.
tgtCell() [2/2]
label & tgtCell () inline
Definition at line 101 of file meshToMeshData.H.
valid()
template<class TrackingData > bool valid (TrackingData & td) const inline
Definition at line 40 of file meshToMeshDataI.H.
Referenced by meshToMeshData::equal().
sameGeometry()
template<class TrackingData > bool sameGeometry (const polyMesh & , const meshToMeshData & , const scalar , TrackingData & td) const inline
Definition at line 48 of file meshToMeshDataI.H.
leaveDomain()
template<class TrackingData > void leaveDomain (const polyMesh & , const polyPatch & patch, const label patchFacei, const point & faceCentre, TrackingData & td) inline
Definition at line 61 of file meshToMeshDataI.H.
enterDomain()
template<class TrackingData > void enterDomain (const polyMesh & , const polyPatch & patch, const label patchFacei, const point & faceCentre, TrackingData & td) inline
Definition at line 84 of file meshToMeshDataI.H.
transform()
template<class TrackingData > void transform (const polyMesh & , const tensor & rotTensor, TrackingData & td) inline
Definition at line 73 of file meshToMeshDataI.H.
updateCell()
template<class TrackingData > bool updateCell (const polyMesh & mesh, const label thisCelli, const label neighbourFacei, const meshToMeshData & neighbourInfo, const scalar tol, TrackingData & td) inline
Definition at line 97 of file meshToMeshDataI.H.
References polyMesh::CELL_TETS, primitiveMesh::cellCentres(), and mesh.
updateFace() [1/2]
template<class TrackingData > bool updateFace (const polyMesh & mesh, const label thisFacei, const label neighbourCelli, const meshToMeshData & neighbourInfo, const scalar tol, TrackingData & td) inline
Definition at line 142 of file meshToMeshDataI.H.
updateFace() [2/2]
template<class TrackingData > bool updateFace (const polyMesh & mesh, const label thisFacei, const meshToMeshData & neighbourInfo, const scalar tol, TrackingData & td) inline
Definition at line 164 of file meshToMeshDataI.H.
equal()
template<class TrackingData > bool equal (const meshToMeshData & rhs, TrackingData & td) const inline
Definition at line 184 of file meshToMeshDataI.H.
References Foam::operator==(), and meshToMeshData::valid().
operator==()
bool operator== (const meshToMeshData & rhs) const inline
Definition at line 203 of file meshToMeshDataI.H.
operator!=()
bool operator!= (const meshToMeshData & rhs) const inline
Definition at line 212 of file meshToMeshDataI.H.
Friends And Related Symbol Documentation
operator<<
Ostream & operator<< (Ostream & , const meshToMeshData &) friend
operator>>
Istream & operator>> (Istream & , meshToMeshData &) friend
The documentation for this class was generated from the following files:
src/overset/cellCellStencil/inverseDistance/meshToMeshData.H
src/overset/cellCellStencil/inverseDistance/meshToMeshDataI.H