OpenFOAM: phasePair Class Reference
phasePair Class Reference
Description for mass transfer between a pair of phases. The direction of the mass transfer is from the phase 'from' to the phasse 'to'.
#include <phasePair.H>
Classes
class const_iterator
Public Types
typedef HashTable< dictionary, phasePairKey, phasePairKey::hash > dictTable
typedef HashTable< scalar, phasePairKey, phasePairKey::hash > scalarTable
typedef HashTable< dictionary, phasePairKey, phasePairKey::hash > dictTable
typedef HashTable< scalar, phasePairKey, phasePairKey::hash > scalarTable
Public Types inherited from phasePairKey
using hash = phasePairKey::hasher
using hash = phasePairKey::hasher
using hash = phasePairKey::hasher
Public Types inherited from FixedList< T, N >
typedef T value_type
typedef T * pointer
typedef const T * const_pointer
typedef T & reference
typedef const T & const_reference
typedef T * iterator
typedef const T * const_iterator
typedef label size_type
typedef label difference_type
typedef std::reverse_iterator< iterator > reverse_iterator
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
Public Member Functions
phasePair (const multiphaseInter::phaseModel &phase1, const multiphaseInter::phaseModel &phase2, const bool ordered=false)
virtual ~phasePair ()=default
virtual const multiphaseInter::phaseModel & from () const
virtual const multiphaseInter::phaseModel & to () const
virtual word name () const
const multiphaseInter::phaseModel & phase1 () const
const multiphaseInter::phaseModel & phase2 () const
phasePair (const phaseModel &phase1, const phaseModel &phase2, const bool ordered=false)
virtual ~phasePair ()
virtual const phaseModel & dispersed () const
virtual const phaseModel & continuous () const
virtual word name () const
virtual word otherName () const
tmp< volScalarField > rho () const
tmp< volScalarField > magUr () const
tmp< volVectorField > Ur () const
tmp< volScalarField > Re () const
tmp< volScalarField > Pr () const
tmp< volScalarField > Eo () const
tmp< volScalarField > EoH1 () const
tmp< volScalarField > EoH2 () const
tmp< volScalarField > sigma () const
tmp< volScalarField > Mo () const
tmp< volScalarField > Ta () const
virtual tmp< volScalarField > E () const
const phaseModel & phase1 () const
const phaseModel & phase2 () const
bool contains (const phaseModel &phase) const
const phaseModel & otherPhase (const phaseModel &phase) const
label index (const phaseModel &phase) const
const uniformDimensionedVectorField & g () const
const_iterator cbegin () const
const_iterator cend () const
const_iterator begin () const
const_iterator end () const
phasePair (const phaseModel &phase1, const phaseModel &phase2, const dimensionedVector &g, const scalarTable &sigmaTable, const bool ordered=false)
virtual ~phasePair ()
virtual const phaseModel & dispersed () const
virtual const phaseModel & continuous () const
virtual word name () const
tmp< volScalarField > rho () const
tmp< volScalarField > magUr () const
tmp< volVectorField > Ur () const
tmp< volScalarField > Re () const
tmp< volScalarField > Pr () const
tmp< volScalarField > Eo () const
tmp< volScalarField > EoH1 () const
tmp< volScalarField > EoH2 () const
tmp< volScalarField > Mo () const
tmp< volScalarField > Ta () const
virtual tmp< volScalarField > E () const
const phaseModel & phase1 () const
const phaseModel & phase2 () const
const dimensionedVector & g () const
const dimensionedScalar & sigma () const
Public Member Functions inherited from phasePairKey
phasePairKey ()=default
phasePairKey (const word &name1, const word &name2, const bool ordered=false)
virtual ~phasePairKey ()=default
bool ordered () const noexcept
phasePairKey ()=default
phasePairKey (const word &name1, const word &name2, const bool ordered=false)
virtual ~phasePairKey ()=default
bool ordered () const noexcept
phasePairKey ()=default
phasePairKey (const word &name1, const word &name2, const bool ordered=false)
virtual ~phasePairKey ()=default
bool ordered () const noexcept
Public Member Functions inherited from Pair< word >
Pair ()=default
Pair (const word &f, const word &s)
Pair (word &&f, word &&s)
Pair (const std::pair< word, word > &vals)
Pair (std::pair< word, word > &&vals)
Pair (const FixedList< word, 2 > &list)
Pair (const word &f, const word &s, const bool doSort)
Pair (const FixedList< word, 2 > &list, const bool doSort)
Pair (Istream &is)
void front ()=delete
void back ()=delete
const word & first () const noexcept
word & first () noexcept
const word & second () const noexcept
word & second () noexcept
const word & other (const word &a) const
bool sorted () const
void flip ()
void sort ()
Public Member Functions inherited from FixedList< T, N >
FixedList ()=default
FixedList (const T &val)
FixedList (const Foam::zero)
FixedList (const T list[N])
FixedList (const FixedList< T, N > &list)
FixedList (FixedList< T, N > &&list)
FixedList (std::initializer_list< T > list)
FixedList (const UList< T > &list)
template<unsigned AnyNum>
FixedList (const FixedList< T, AnyNum > &list, const FixedList< label, N > &indices)
FixedList (const UList< T > &list, const FixedList< label, N > &indices)
FixedList (const SLList< T > &list)
FixedList (Istream &is)
autoPtr< FixedList< T, N > > clone () const
const T * cdata () const noexcept
T * data () noexcept
const char * cdata_bytes () const noexcept
char * data_bytes () noexcept
template<unsigned Index>
T & get () noexcept
template<unsigned Index>
const T & get () const noexcept
T & front () noexcept
const T & front () const noexcept
T & back () noexcept
const T & back () const noexcept
label fcIndex (const label i) const
const T & fcValue (const label i) const
T & fcValue (const label i)
label rcIndex (const label i) const
const T & rcValue (const label i) const
T & rcValue (const label i)
void checkStart (const label start) const
void checkSize (const label size) const
void checkIndex (const label i) const
bool uniform () const
label find (const T &val, label pos=0) const
label rfind (const T &val, label pos=-1) const
bool contains (const T &val, label pos=0) const
void resize (const label n)
void resize_nocopy (const label n)
void setSize (const label n)
void fill (const T &val)
void fill (const Foam::zero)
void moveFirst (const label i)
void moveLast (const label i)
void swapFirst (const label i)
void swapLast (const label i)
void transfer (FixedList< T, N > &list)
T & operator[] (const label i)
const T & operator[] (const label i) const
void operator= (const T list[N])
void operator= (const UList< T > &list)
void operator= (const SLList< T > &list)
void operator= (std::initializer_list< T > list)
void operator= (const T &val)
void operator= (const Foam::zero)
void operator= (const FixedList< T, N > &list)
void operator= (FixedList< T, N > &&list)
iterator begin () noexcept
iterator end () noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
const_iterator begin () const noexcept
const_iterator end () const noexcept
reverse_iterator rbegin ()
reverse_iterator rend ()
const_reverse_iterator crbegin () const
const_reverse_iterator crend () const
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
void swap (FixedList< T, N > &other)
bool operator== (const FixedList< T, N > &list) const
bool operator!= (const FixedList< T, N > &list) const
bool operator< (const FixedList< T, N > &list) const
bool operator> (const FixedList< T, N > &list) const
bool operator<= (const FixedList< T, N > &list) const
bool operator>= (const FixedList< T, N > &list) const
Istream & readList (Istream &is)
void writeEntry (const word &keyword, Ostream &os) const
Ostream & writeList (Ostream &os, const label shortLen=0) const
T & first () noexcept
const T & first () const noexcept
T & last () noexcept
const T & last () const noexcept
bool found (const T &val, label pos=0) const
Additional Inherited Members
Static Public Member Functions inherited from Pair< word >
static int compare (const Pair< word > &a, const Pair< word > &b)
Static Public Member Functions inherited from FixedList< T, N >
static const FixedList< T, N > & null ()
static std::streamsize size_bytes () noexcept
static std::streamsize byteSize ()
static constexpr bool empty () noexcept
static constexpr label size () noexcept
static constexpr unsigned max_size () noexcept
Protected Member Functions inherited from FixedList< T, N >
void writeEntry (Ostream &os) const
Detailed Description
Description for mass transfer between a pair of phases. The direction of the mass transfer is from the phase 'from' to the phasse 'to'.
Source files
phasePair.H
phasePair.C
Source files
phasePair.H
phasePair.C
Source files
phasePair.H
phasePair.C
Definition at line 49 of file phasePair.H.
Member Typedef Documentation
dictTable [1/2]
typedef HashTable<dictionary, phasePairKey, phasePairKey::hash> dictTable
Definition at line 57 of file phasePair.H.
scalarTable [1/2]
typedef HashTable<scalar, phasePairKey, phasePairKey::hash> scalarTable
Definition at line 61 of file phasePair.H.
dictTable [2/2]
typedef HashTable<dictionary, phasePairKey, phasePairKey::hash> dictTable
Definition at line 56 of file phasePair.H.
scalarTable [2/2]
typedef HashTable<scalar, phasePairKey, phasePairKey::hash> scalarTable
Definition at line 60 of file phasePair.H.
Constructor & Destructor Documentation
phasePair() [1/3]
phasePair (const multiphaseInter::phaseModel & phase1, const multiphaseInter::phaseModel & phase2, const bool ordered = false)
Definition at line 27 of file phasePair.C.
References Foam::name().
~phasePair() [1/3]
~phasePair () virtual default
Definition at line 59 of file phasePair.C.
phasePair() [2/3]
phasePair (const phaseModel & phase1, const phaseModel & phase2, const bool ordered = false)
Definition at line 43 of file phasePair.C.
~phasePair() [2/3]
virtual ~phasePair () virtual
phasePair() [3/3]
phasePair (const phaseModel & phase1, const phaseModel & phase2, const dimensionedVector & g, const scalarTable & sigmaTable, const bool ordered = false)
Definition at line 40 of file phasePair.C.
~phasePair() [3/3]
virtual ~phasePair () virtual
Member Function Documentation
from()
const Foam::multiphaseInter::phaseModel & from () const virtual
Reimplemented in orderedPhasePair.
Definition at line 42 of file phasePair.C.
References Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
to()
const Foam::multiphaseInter::phaseModel & to () const virtual
Reimplemented in orderedPhasePair.
Definition at line 52 of file phasePair.C.
References Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
name() [1/3]
Foam::word name () const virtual
Reimplemented in orderedPhasePair, orderedPhasePair, and orderedPhasePair.
Definition at line 62 of file phasePair.C.
Referenced by phaseChange::addToDriftRate(), InterfaceCompositionPhaseChangePhaseSystem< BasePhaseSystem >::correctInterfaceThermo(), ThermalPhaseChangePhaseSystem< BasePhaseSystem >::correctInterfaceThermo(), TwoResistanceHeatTransferPhaseSystem< BasePhaseSystem >::correctInterfaceThermo(), InterfaceCompositionPhaseChangePhaseSystem< BasePhaseSystem >::InterfaceCompositionPhaseChangePhaseSystem(), MomentumTransferPhaseSystem< BasePhaseSystem >::MomentumTransferPhaseSystem(), phaseChange::phaseChange(), PopulationBalancePhaseSystem< BasePhaseSystem >::PopulationBalancePhaseSystem(), ThermalPhaseChangePhaseSystem< BasePhaseSystem >::ThermalPhaseChangePhaseSystem(), and TwoResistanceHeatTransferPhaseSystem< BasePhaseSystem >::TwoResistanceHeatTransferPhaseSystem().
phase1() [1/3]
const Foam::phaseModel & phase1 () const inline
Definition at line 23 of file phasePairI.H.
Referenced by MassTransferPhaseSystem< BasePhaseSystem >::alphaTransfer(), InterfaceCompositionPhaseChangePhaseSystem< BasePhaseSystem >::correctInterfaceThermo(), ThermalPhaseChangePhaseSystem< BasePhaseSystem >::correctInterfaceThermo(), TwoResistanceHeatTransferPhaseSystem< BasePhaseSystem >::correctInterfaceThermo(), InterfaceCompositionPhaseChangePhaseSystem< BasePhaseSystem >::dmdts(), PhaseTransferPhaseSystem< BasePhaseSystem >::dmdts(), PopulationBalancePhaseSystem< BasePhaseSystem >::dmdts(), ThermalPhaseChangePhaseSystem< BasePhaseSystem >::dmdts(), OneResistanceHeatTransferPhaseSystem< BasePhaseSystem >::heatTransfer(), ThermalPhaseChangePhaseSystem< BasePhaseSystem >::heatTransfer(), TwoResistanceHeatTransferPhaseSystem< BasePhaseSystem >::heatTransfer(), InterfaceCompositionPhaseChangePhaseSystem< BasePhaseSystem >::InterfaceCompositionPhaseChangePhaseSystem(), InterfaceCompositionPhaseChangePhaseSystem< BasePhaseSystem >::massTransfer(), PhaseTransferPhaseSystem< BasePhaseSystem >::massTransfer(), PopulationBalancePhaseSystem< BasePhaseSystem >::massTransfer(), ThermalPhaseChangePhaseSystem< BasePhaseSystem >::massTransfer(), interfaceCompositionModel::New(), phaseForces::nonDragForce(), MomentumTransferPhaseSystem< BasePhaseSystem >::partialElimination(), MomentumTransferPhaseSystem< BasePhaseSystem >::partialEliminationf(), MomentumTransferPhaseSystem< BasePhaseSystem >::phiFfs(), MomentumTransferPhaseSystem< BasePhaseSystem >::phiFs(), TwoResistanceHeatTransferPhaseSystem< BasePhaseSystem >::TwoResistanceHeatTransferPhaseSystem(), and MassTransferPhaseSystem< BasePhaseSystem >::volTransfer().
phase2() [1/3]
const Foam::phaseModel & phase2 () const inline
Definition at line 29 of file phasePairI.H.
Referenced by MassTransferPhaseSystem< BasePhaseSystem >::alphaTransfer(), InterfaceCompositionPhaseChangePhaseSystem< BasePhaseSystem >::correctInterfaceThermo(), ThermalPhaseChangePhaseSystem< BasePhaseSystem >::correctInterfaceThermo(), TwoResistanceHeatTransferPhaseSystem< BasePhaseSystem >::correctInterfaceThermo(), InterfaceCompositionPhaseChangePhaseSystem< BasePhaseSystem >::dmdts(), PhaseTransferPhaseSystem< BasePhaseSystem >::dmdts(), PopulationBalancePhaseSystem< BasePhaseSystem >::dmdts(), ThermalPhaseChangePhaseSystem< BasePhaseSystem >::dmdts(), OneResistanceHeatTransferPhaseSystem< BasePhaseSystem >::heatTransfer(), ThermalPhaseChangePhaseSystem< BasePhaseSystem >::heatTransfer(), TwoResistanceHeatTransferPhaseSystem< BasePhaseSystem >::heatTransfer(), InterfaceCompositionPhaseChangePhaseSystem< BasePhaseSystem >::InterfaceCompositionPhaseChangePhaseSystem(), InterfaceCompositionPhaseChangePhaseSystem< BasePhaseSystem >::massTransfer(), PhaseTransferPhaseSystem< BasePhaseSystem >::massTransfer(), PopulationBalancePhaseSystem< BasePhaseSystem >::massTransfer(), ThermalPhaseChangePhaseSystem< BasePhaseSystem >::massTransfer(), interfaceCompositionModel::New(), MomentumTransferPhaseSystem< BasePhaseSystem >::partialElimination(), MomentumTransferPhaseSystem< BasePhaseSystem >::partialEliminationf(), MomentumTransferPhaseSystem< BasePhaseSystem >::phiFfs(), MomentumTransferPhaseSystem< BasePhaseSystem >::phiFs(), TwoResistanceHeatTransferPhaseSystem< BasePhaseSystem >::TwoResistanceHeatTransferPhaseSystem(), and MassTransferPhaseSystem< BasePhaseSystem >::volTransfer().
dispersed() [1/2]
const Foam::phaseModel & dispersed () const virtual
Reimplemented in orderedPhasePair, and orderedPhasePair.
Definition at line 65 of file phasePair.C.
References Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
continuous() [1/2]
const Foam::phaseModel & continuous () const virtual
Reimplemented in orderedPhasePair, and orderedPhasePair.
Definition at line 75 of file phasePair.C.
References Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
name() [2/3]
virtual word name () const virtual
Reimplemented in orderedPhasePair, orderedPhasePair, and orderedPhasePair.
otherName()
Foam::word otherName () const virtual
Reimplemented in orderedPhasePair.
Definition at line 93 of file phasePair.C.
rho() [1/2]
Foam::tmp< Foam::volScalarField > rho () const
Definition at line 101 of file phasePair.C.
References phase1, phase2, and phaseModel::rho().
magUr() [1/2]
Foam::tmp< Foam::volScalarField > magUr () const
Definition at line 107 of file phasePair.C.
References Foam::mag(), phase1, phase2, and U.
Ur() [1/2]
Foam::tmp< Foam::volVectorField > Ur () const
Definition at line 113 of file phasePair.C.
Re() [1/2]
Foam::tmp< Foam::volScalarField > Re () const
Definition at line 119 of file phasePair.C.
Pr() [1/2]
Foam::tmp< Foam::volScalarField > Pr () const
Definition at line 125 of file phasePair.C.
Eo() [1/2]
Foam::tmp< Foam::volScalarField > Eo () const
Definition at line 135 of file phasePair.C.
EoH1() [1/2]
Foam::tmp< Foam::volScalarField > EoH1 () const
Definition at line 141 of file phasePair.C.
References Foam::cbrt(), and Foam::pow().
EoH2() [1/2]
Foam::tmp< Foam::volScalarField > EoH2 () const
Definition at line 152 of file phasePair.C.
References Foam::cbrt().
sigma() [1/2]
const Foam::dimensionedScalar & sigma () const inline
Definition at line 163 of file phasePair.C.
References phaseModel::fluid(), phase1, and phase2.
Mo() [1/2]
Foam::tmp< Foam::volScalarField > Mo () const
Definition at line 174 of file phasePair.C.
References g, Foam::mag(), nu, Foam::pow3(), and rho.
Ta() [1/2]
Foam::tmp< Foam::volScalarField > Ta () const
Definition at line 188 of file phasePair.C.
References Foam::pow(), and Foam::Re().
E() [1/2]
Foam::tmp< Foam::volScalarField > E () const virtual
Reimplemented in orderedPhasePair, and orderedPhasePair.
Definition at line 194 of file phasePair.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and phase1.
phase1() [2/3]
const phaseModel & phase1 () const inline
phase2() [2/3]
const phaseModel & phase2 () const inline
contains()
bool contains (const phaseModel & phase) const inline
Definition at line 35 of file phasePairI.H.
Referenced by phaseChange::addToDriftRate(), phaseChange::correct(), phaseForces::execute(), phaseSystem::generatePairsAndSubModels(), and phaseForces::phaseForces().
otherPhase()
const Foam::phaseModel & otherPhase (const phaseModel & phase) const inline
Definition at line 41 of file phasePairI.H.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and phase::name().
Referenced by phaseForces::execute().
index()
Foam::label index (const phaseModel & phase) const inline
Definition at line 65 of file phasePairI.H.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and phase::name().
Referenced by phaseSystem::generatePairsAndSubModels().
g() [1/2]
const Foam::dimensionedVector & g () const inline
Definition at line 86 of file phasePairI.H.
cbegin()
Foam::phasePair::const_iterator cbegin () const inline
Definition at line 187 of file phasePairI.H.
cend()
Foam::phasePair::const_iterator cend () const inline
Definition at line 193 of file phasePairI.H.
begin()
Foam::phasePair::const_iterator begin () const inline
Definition at line 199 of file phasePairI.H.
end()
Foam::phasePair::const_iterator end () const inline
Definition at line 205 of file phasePairI.H.
dispersed() [2/2]
virtual const phaseModel & dispersed () const virtual
Reimplemented in orderedPhasePair, and orderedPhasePair.
continuous() [2/2]
virtual const phaseModel & continuous () const virtual
Reimplemented in orderedPhasePair, and orderedPhasePair.
name() [3/3]
virtual word name () const virtual
Reimplemented in orderedPhasePair, orderedPhasePair, and orderedPhasePair.
rho() [2/2]
tmp< volScalarField > rho () const
magUr() [2/2]
tmp< volScalarField > magUr () const
Ur() [2/2]
tmp< volVectorField > Ur () const
Re() [2/2]
tmp< volScalarField > Re () const
Pr() [2/2]
tmp< volScalarField > Pr () const
Eo() [2/2]
tmp< volScalarField > Eo () const
EoH1() [2/2]
tmp< volScalarField > EoH1 () const
EoH2() [2/2]
tmp< volScalarField > EoH2 () const
Mo() [2/2]
tmp< volScalarField > Mo () const
Ta() [2/2]
tmp< volScalarField > Ta () const
E() [2/2]
virtual tmp< volScalarField > E () const virtual
Reimplemented in orderedPhasePair, and orderedPhasePair.
phase1() [3/3]
const phaseModel & phase1 () const inline
phase2() [3/3]
const phaseModel & phase2 () const inline
g() [2/2]
const dimensionedVector & g () const inline
sigma() [2/2]
const dimensionedScalar & sigma () const inline
The documentation for this class was generated from the following files:
src/phaseSystemModels/multiphaseInter/phasesSystem/phasePair/phasePair.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/phasePair/phasePair.H
src/phaseSystemModels/twoPhaseEuler/twoPhaseSystem/phasePair/phasePair.H
src/phaseSystemModels/multiphaseInter/phasesSystem/phasePair/phasePair.C
src/phaseSystemModels/multiphaseInter/phasesSystem/phasePair/phasePairI.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/phasePair/phasePair.C
src/phaseSystemModels/reactingEuler/multiphaseSystem/phasePair/phasePairI.H
src/phaseSystemModels/twoPhaseEuler/twoPhaseSystem/phasePair/phasePair.C
src/phaseSystemModels/twoPhaseEuler/twoPhaseSystem/phasePair/phasePairI.H