OpenFOAM: joint Class Reference
joint Class Reference abstract
Abstract base-class for all rigid-body joints.
#include <joint.H>
Classes
class iNew
class XSvc
Public Member Functions
TypeName ("joint")
declareRunTimeSelectionTable (autoPtr, joint, dictionary,(const dictionary &dict),(dict))
joint (const label nDoF)
virtual autoPtr< joint > clone () const =0
virtual ~joint ()
label nDoF () const
virtual bool unitQuaternion () const
label index () const
label qIndex () const
const List< spatialVector > & S () const
virtual void jcalc (XSvc &J, const scalarField &q, const scalarField &qDot) const =0
virtual void write (Ostream &) const
quaternion unitQuaternion (const scalarField &q) const
void unitQuaternion (const quaternion &quat, scalarField &q) const
Static Public Member Functions
static autoPtr< joint > New (joint *jointPtr)
static autoPtr< joint > New (const dictionary &dict)
Protected Attributes
List< spatialVector > S_
label index_
label qIndex_
Friends
class rigidBodyModel
Ostream & operator<< (Ostream &, const joint &)
Detailed Description
Abstract base-class for all rigid-body joints.
Reference:
    Featherstone, R. (2008).
    Rigid body dynamics algorithms.
    Springer.
    Chapter 4.
Source files
joint.H
jointI.H
joint.C
Definition at line 81 of file joint.H.
Constructor & Destructor Documentation
joint()
joint (const label nDoF) inline
Definition at line 23 of file jointI.H.
~joint()
~joint () virtual
Definition at line 71 of file joint.C.
Member Function Documentation
TypeName()
TypeName ("joint")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , joint , dictionary , (const dictionary &dict) , (dict))
clone()
virtual autoPtr< joint > clone () const pure virtual
Implemented in composite, floating, null, Pa, Px, Pxyz, Py, Pz, Ra, Rs, Rx, Rxyz, Ry, Ryxz, Rz, and Rzyx.
New() [1/2]
Foam::autoPtr< Foam::RBD::joint > New (joint * jointPtr) static
Definition at line 39 of file joint.C.
Referenced by rigidBodyModel::rigidBodyModel().
New() [2/2]
Foam::autoPtr< Foam::RBD::joint > New (const dictionary & dict) static
Definition at line 45 of file joint.C.
References dict, Foam::exit(), Foam::FatalIOError, and FatalIOErrorInLookup.
nDoF()
Foam::label nDoF () const inline
Definition at line 33 of file jointI.H.
References UPtrList< T >::size().
unitQuaternion() [1/3]
bool unitQuaternion () const inline virtual
Reimplemented in Rs.
Definition at line 38 of file jointI.H.
Referenced by Rs::jcalc().
index()
Foam::label index () const inline
Definition at line 43 of file jointI.H.
qIndex()
Foam::label qIndex () const inline
Definition at line 48 of file jointI.H.
S()
const Foam::List< Foam::spatialVector > & S () const inline
Definition at line 53 of file jointI.H.
jcalc()
virtual void jcalc (XSvc & J, const scalarField & q, const scalarField & qDot) const pure virtual
Implemented in composite, null, Pa, Px, Pxyz, Py, Pz, Ra, Rs, Rx, Rxyz, Ry, Ryxz, Rz, and Rzyx.
write()
void write (Ostream & os) const virtual
Reimplemented in composite, floating, Pa, and Ra.
Definition at line 77 of file joint.C.
References os(), and Foam::type().
Referenced by Foam::RBD::operator<<(), composite::write(), floating::write(), Pa::write(), and Ra::write().
unitQuaternion() [2/3]
Foam::quaternion unitQuaternion (const scalarField & q) const inline
Definition at line 61 of file jointI.H.
References Foam::abort(), Field< Type >::block(), Foam::FatalError, FatalErrorInFunction, and quaternion::unit().
unitQuaternion() [3/3]
void unitQuaternion (const quaternion & quat, scalarField & q) const inline
Definition at line 77 of file jointI.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Friends And Related Symbol Documentation
rigidBodyModel
friend class rigidBodyModel friend
Definition at line 118 of file joint.H.
operator<<
Ostream & operator<< (Ostream & , const joint &) friend
Member Data Documentation
S_
List<spatialVector> S_ protected
Definition at line 89 of file joint.H.
Referenced by Pa::Pa(), Px::Px(), Px::Px(), Pxyz::Pxyz(), Pxyz::Pxyz(), Py::Py(), Py::Py(), Pz::Pz(), Pz::Pz(), Ra::Ra(), Rs::Rs(), Rs::Rs(), Rx::Rx(), Rx::Rx(), Rxyz::Rxyz(), Rxyz::Rxyz(), Ry::Ry(), Ry::Ry(), Ryxz::Ryxz(), Ryxz::Ryxz(), Rz::Rz(), Rz::Rz(), Rzyx::Rzyx(), and Rzyx::Rzyx().
index_
label index_ protected
Definition at line 92 of file joint.H.
qIndex_
label qIndex_ protected
Definition at line 95 of file joint.H.
The documentation for this class was generated from the following files:
src/rigidBodyDynamics/joints/joint/joint.H
src/rigidBodyDynamics/joints/joint/joint.C
src/rigidBodyDynamics/joints/joint/jointI.H