OpenFOAM: variableHeightFlowRateInletVelocityFvPatchVectorField Class Reference
variableHeightFlowRateInletVelocityFvPatchVectorField Class Reference
Boundary conditions » Inlet
This boundary condition provides a velocity boundary condition for multphase flow based on a user-specified volumetric flow rate.
#include <variableHeightFlowRateInletVelocityFvPatchVectorField.H>
Public Member Functions
TypeName ("variableHeightFlowRateInletVelocity")
variableHeightFlowRateInletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
variableHeightFlowRateInletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
variableHeightFlowRateInletVelocityFvPatchVectorField (const variableHeightFlowRateInletVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
variableHeightFlowRateInletVelocityFvPatchVectorField (const variableHeightFlowRateInletVelocityFvPatchVectorField &)
virtual tmp< fvPatchVectorField > clone () const
variableHeightFlowRateInletVelocityFvPatchVectorField (const variableHeightFlowRateInletVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
This boundary condition provides a velocity boundary condition for multphase flow based on a user-specified volumetric flow rate.
The flow rate is made proportional to the phase fraction alpha at each face of the patch and alpha is ensured to be bound between 0 and 1.
Usage
Property Description Required Default value
flowRate volumetric flow rate [m3/s] yes
alpha phase-fraction field yes
Example of the boundary condition specification:
    <patchName>
    {
        type            variableHeightFlowRateInletVelocity;
        flowRate        0.2;
        alpha           alpha.water;
        value           uniform (0 0 0); // placeholder
    }
The flowRate entry is a Function1 of time, see Foam::Function1Types.
Note
the value is positive into the domain
may not work correctly for transonic inlets
strange behaviour with potentialFoam since the momentum equation is not solved
See also
Foam::fixedValueFvPatchField Foam::Function1Types
Source files
variableHeightFlowRateInletVelocityFvPatchVectorField.H
variableHeightFlowRateInletVelocityFvPatchVectorField.C
Definition at line 98 of file variableHeightFlowRateInletVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
variableHeightFlowRateInletVelocityFvPatchVectorField() [1/5]
variableHeightFlowRateInletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Definition at line 28 of file variableHeightFlowRateInletVelocityFvPatchVectorField.C.
variableHeightFlowRateInletVelocityFvPatchVectorField() [2/5]
variableHeightFlowRateInletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Definition at line 41 of file variableHeightFlowRateInletVelocityFvPatchVectorField.C.
variableHeightFlowRateInletVelocityFvPatchVectorField() [3/5]
variableHeightFlowRateInletVelocityFvPatchVectorField (const variableHeightFlowRateInletVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 55 of file variableHeightFlowRateInletVelocityFvPatchVectorField.C.
variableHeightFlowRateInletVelocityFvPatchVectorField() [4/5]
variableHeightFlowRateInletVelocityFvPatchVectorField (const variableHeightFlowRateInletVelocityFvPatchVectorField & ptf)
Definition at line 70 of file variableHeightFlowRateInletVelocityFvPatchVectorField.C.
variableHeightFlowRateInletVelocityFvPatchVectorField() [5/5]
variableHeightFlowRateInletVelocityFvPatchVectorField (const variableHeightFlowRateInletVelocityFvPatchVectorField & ptf, const DimensionedField< vector, volMesh > & iF)
Definition at line 82 of file variableHeightFlowRateInletVelocityFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("variableHeightFlowRateInletVelocity")
clone() [1/2]
virtual tmp< fvPatchVectorField > clone () const inline virtual
Definition at line 152 of file variableHeightFlowRateInletVelocityFvPatchVectorField.H.
clone() [2/2]
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Definition at line 168 of file variableHeightFlowRateInletVelocityFvPatchVectorField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 97 of file variableHeightFlowRateInletVelocityFvPatchVectorField.C.
References Foam::gSum(), Foam::max(), Foam::min(), n, Foam::operator==(), and fvPatchField< Type >::updateCoeffs().
write()
void write (Ostream & os) const virtual
Definition at line 127 of file variableHeightFlowRateInletVelocityFvPatchVectorField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntry(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/variableHeightFlowRateInletVelocity/variableHeightFlowRateInletVelocityFvPatchVectorField.H
src/finiteVolume/fields/fvPatchFields/derived/variableHeightFlowRateInletVelocity/variableHeightFlowRateInletVelocityFvPatchVectorField.C