OpenFOAM: polyAddCell Class Reference
polyAddCell Class Reference
Class containing data for cell addition.
#include <polyAddCell.H>
Public Member Functions
TypeName ("addCell")
polyAddCell ()
polyAddCell (const label masterPointID, const label masterEdgeID, const label masterFaceID, const label masterCellID, const label zoneID)
virtual autoPtr< topoAction > clone () const
bool isPointMaster () const
bool isEdgeMaster () const
bool isFaceMaster () const
bool isCellMaster () const
bool appended () const
label masterPointID () const
label masterEdgeID () const
label masterFaceID () const
label masterCellID () const
bool isInZone () const
label zoneID () const
Public Member Functions inherited from topoAction
TypeName ("topoAction")
topoAction ()
virtual ~topoAction ()=default
Detailed Description
Class containing data for cell addition.
Definition at line 42 of file polyAddCell.H.
Constructor & Destructor Documentation
polyAddCell() [1/2]
polyAddCell () inline
Definition at line 75 of file polyAddCell.H.
Referenced by polyAddCell::clone().
polyAddCell() [2/2]
polyAddCell (const label masterPointID, const label masterEdgeID, const label masterFaceID, const label masterCellID, const label zoneID) inline
Definition at line 85 of file polyAddCell.H.
Member Function Documentation
TypeName()
TypeName ("addCell")
clone()
virtual autoPtr< topoAction > clone () const inline virtual
Implements topoAction.
Definition at line 102 of file polyAddCell.H.
References polyAddCell::polyAddCell().
isPointMaster()
bool isPointMaster () const inline
Definition at line 114 of file polyAddCell.H.
Referenced by polyAddCell::appended().
isEdgeMaster()
bool isEdgeMaster () const inline
Definition at line 120 of file polyAddCell.H.
Referenced by polyAddCell::appended().
isFaceMaster()
bool isFaceMaster () const inline
Definition at line 126 of file polyAddCell.H.
Referenced by polyAddCell::appended().
isCellMaster()
bool isCellMaster () const inline
Definition at line 132 of file polyAddCell.H.
Referenced by polyAddCell::appended().
appended()
bool appended () const inline
Definition at line 138 of file polyAddCell.H.
References polyAddCell::isCellMaster(), polyAddCell::isEdgeMaster(), polyAddCell::isFaceMaster(), and polyAddCell::isPointMaster().
masterPointID()
label masterPointID () const inline
Definition at line 146 of file polyAddCell.H.
masterEdgeID()
label masterEdgeID () const inline
Definition at line 152 of file polyAddCell.H.
masterFaceID()
label masterFaceID () const inline
Definition at line 158 of file polyAddCell.H.
masterCellID()
label masterCellID () const inline
Definition at line 164 of file polyAddCell.H.
isInZone()
bool isInZone () const inline
Definition at line 170 of file polyAddCell.H.
zoneID()
label zoneID () const inline
Definition at line 176 of file polyAddCell.H.
The documentation for this class was generated from the following file:
src/meshTools/polyTopoChange/addObject/polyAddCell.H