OpenFOAM: IntRange< IntType > Class Template Reference
IntRange< IntType > Class Template Reference
An interval of (signed) integers defined by a start and a size.
#include <IntRange.H>
Classes
class const_iterator
class const_reverse_iterator
struct ge0
struct gt0
struct le0
struct lt0
Public Types
typedef IntType value_type
typedef IntType size_type
Public Member Functions
constexpr IntRange () noexcept
constexpr IntRange (const IntType len) noexcept
constexpr IntRange (const IntType beg, const IntType len) noexcept
bool empty () const noexcept
IntType size () const noexcept
IntType & size () noexcept
IntType start () const noexcept
IntType & start () noexcept
IntType min () const noexcept
IntType max () const noexcept
void clear () noexcept
void reset (const IntType beg, const IntType len) noexcept
void setStart (const IntType i) noexcept
void setSize (const IntType n) noexcept
void resize (const IntType n) noexcept
void clampSize () noexcept
bool contains (const IntType value) const noexcept
bool found (const IntType val) const noexcept
const_iterator at (const IntType i) const
constexpr IntType operator[] (const IntType i) const noexcept
bool operator() (const IntType i) const noexcept
IntType operator++ () noexcept
IntType operator++ (int) noexcept
IntType operator+= (const IntType n) noexcept
IntType operator-- () noexcept
IntType operator-- (int) noexcept
IntType operator-= (const IntType n) noexcept
operator bool () const noexcept
IntType begin_value () const noexcept
IntType end_value () const noexcept
IntType rbegin_value () const noexcept
IntType rend_value () const noexcept
const_iterator begin () const noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
const_iterator end () const noexcept
const_reverse_iterator rbegin () const noexcept
const_reverse_iterator crbegin () const noexcept
const_reverse_iterator rend () const noexcept
const_reverse_iterator crend () const noexcept
Detailed Description
template<class IntType>
class Foam::IntRange< IntType >
An interval of (signed) integers defined by a start and a size.
Note
Only a minimum of IO operators are defined, to avoid incurring too many dependencies or cyclic dependencies.
Source files
IntRange.H
IntRangeI.H
IntRanges.C
Definition at line 59 of file IntRange.H.
Member Typedef Documentation
value_type
template<class IntType > typedef IntType value_type
Definition at line 77 of file IntRange.H.
size_type
template<class IntType > typedef IntType size_type
Definition at line 80 of file IntRange.H.
Constructor & Destructor Documentation
IntRange() [1/3]
template<class IntType > constexpr IntRange () inline constexpr noexcept
Definition at line 24 of file IntRangeI.H.
IntRange() [2/3]
template<class IntType > constexpr IntRange (const IntType len) inline explicit constexpr noexcept
Definition at line 32 of file IntRangeI.H.
IntRange() [3/3]
template<class IntType > constexpr IntRange (const IntType beg, const IntType len) inline constexpr noexcept
Definition at line 43 of file IntRangeI.H.
Member Function Documentation
empty()
template<class IntType > bool empty () const inline noexcept
Definition at line 156 of file IntRange.H.
Referenced by bitSet::set(), Foam::BitOps::set(), and bitSet::unset().
size() [1/2]
template<class IntType > IntType size () const inline noexcept
Definition at line 159 of file IntRange.H.
Referenced by UPstream::allocateCommunicator().
size() [2/2]
template<class IntType > IntType & size () inline noexcept
Definition at line 162 of file IntRange.H.
start() [1/2]
template<class IntType > IntType start () const inline noexcept
Definition at line 165 of file IntRange.H.
Referenced by ensightFaces::classify().
start() [2/2]
template<class IntType > IntType & start () inline noexcept
Definition at line 168 of file IntRange.H.
min()
template<class IntType > IntType min () const inline noexcept
Definition at line 172 of file IntRange.H.
Referenced by labelRange::join(), labelRange::labelRange(), and labelRange::subset().
max()
template<class IntType > IntType max () const inline noexcept
Definition at line 176 of file IntRange.H.
Referenced by labelRange::join(), and labelRange::subset().
clear()
template<class IntType > void clear () inline noexcept
Definition at line 397 of file IntRangeI.H.
reset()
template<class IntType > void reset (const IntType beg, const IntType len) inline noexcept
Definition at line 404 of file IntRangeI.H.
setStart()
template<class IntType > void setStart (const IntType i) inline noexcept
Definition at line 416 of file IntRangeI.H.
setSize()
template<class IntType > void setSize (const IntType n) inline noexcept
Definition at line 423 of file IntRangeI.H.
resize()
template<class IntType > void resize (const IntType n) inline noexcept
Definition at line 430 of file IntRangeI.H.
clampSize()
template<class IntType > void clampSize () inline noexcept
Definition at line 437 of file IntRangeI.H.
contains()
template<class IntType > bool contains (const IntType value) const inline noexcept
Definition at line 444 of file IntRangeI.H.
Referenced by IntRange< IntType >::found(), and IntRange< IntType >::operator()().
found()
template<class IntType > bool found (const IntType val) const inline noexcept
Definition at line 206 of file IntRange.H.
References IntRange< IntType >::contains().
at()
template<class IntType > Foam::IntRange< IntType >::const_iterator at (const IntType i) const inline
Definition at line 324 of file IntRangeI.H.
operator[]()
template<class IntType > constexpr IntType operator[] (const IntType i) const inline constexpr noexcept
Definition at line 457 of file IntRangeI.H.
operator()()
template<class IntType > bool operator() (const IntType i) const inline noexcept
Definition at line 222 of file IntRange.H.
References IntRange< IntType >::contains().
operator++() [1/2]
template<class IntType > IntType operator++ () inline noexcept
Definition at line 465 of file IntRangeI.H.
operator++() [2/2]
template<class IntType > IntType operator++ (int) inline noexcept
Definition at line 473 of file IntRangeI.H.
operator+=()
template<class IntType > IntType operator+= (const IntType n) inline noexcept
Definition at line 502 of file IntRangeI.H.
operator--() [1/2]
template<class IntType > IntType operator-- () inline noexcept
Definition at line 481 of file IntRangeI.H.
operator--() [2/2]
template<class IntType > IntType operator-- (int) inline noexcept
Definition at line 491 of file IntRangeI.H.
operator-=()
template<class IntType > IntType operator-= (const IntType n) inline noexcept
Definition at line 511 of file IntRangeI.H.
References n.
operator bool()
template<class IntType > operator bool () const inline explicit noexcept
Definition at line 239 of file IntRange.H.
begin_value()
template<class IntType > IntType begin_value () const inline noexcept
Definition at line 57 of file IntRangeI.H.
Referenced by bitSet::set(), and bitSet::unset().
end_value()
template<class IntType > IntType end_value () const inline noexcept
Definition at line 64 of file IntRangeI.H.
Referenced by bitSet::set(), Foam::BitOps::set(), and bitSet::unset().
rbegin_value()
template<class IntType > IntType rbegin_value () const inline noexcept
Definition at line 71 of file IntRangeI.H.
rend_value()
template<class IntType > IntType rend_value () const inline noexcept
Definition at line 78 of file IntRangeI.H.
begin()
template<class IntType > Foam::IntRange< IntType >::const_iterator begin () const inline noexcept
Definition at line 332 of file IntRangeI.H.
cbegin()
template<class IntType > Foam::IntRange< IntType >::const_iterator cbegin () const inline noexcept
Definition at line 340 of file IntRangeI.H.
cend()
template<class IntType > Foam::IntRange< IntType >::const_iterator cend () const inline noexcept
Definition at line 356 of file IntRangeI.H.
end()
template<class IntType > Foam::IntRange< IntType >::const_iterator end () const inline noexcept
Definition at line 348 of file IntRangeI.H.
rbegin()
template<class IntType > Foam::IntRange< IntType >::const_reverse_iterator rbegin () const inline noexcept
Definition at line 364 of file IntRangeI.H.
crbegin()
template<class IntType > Foam::IntRange< IntType >::const_reverse_iterator crbegin () const inline noexcept
Definition at line 372 of file IntRangeI.H.
rend()
template<class IntType > Foam::IntRange< IntType >::const_reverse_iterator rend () const inline noexcept
Definition at line 380 of file IntRangeI.H.
crend()
template<class IntType > Foam::IntRange< IntType >::const_reverse_iterator crend () const inline noexcept
Definition at line 388 of file IntRangeI.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/ranges/IntRange/IntRange.H
src/OpenFOAM/primitives/ranges/IntRange/IntRangeI.H