OpenFOAM: faceAreaIntersect Class Reference
faceAreaIntersect Class Reference
Face intersection class.
#include <faceAreaIntersect.H>
Public Types
enum triangulationMode { tmFan , tmMesh }
Public Member Functions
faceAreaIntersect (const pointField &pointsA, const pointField &pointsB, const DynamicList< face > &trisA, const DynamicList< face > &trisB, const bool reverseB=false, const bool cacheTriangulation=false)
bool cacheTriangulation () const
const DynamicList< triPoints > triangles () const
DynamicList< triPoints > & triangles ()
void calc (const face &faceA, const face &faceB, const vector &n, scalar &area, vector &centroid) const
bool overlaps (const face &faceA, const face &faceB, const vector &n, const scalar threshold) const
Static Public Member Functions
static scalar & tolerance ()
static void triangulate (const face &f, const pointField &points, const triangulationMode &triMode, faceList &faceTris)
static void triangleFan (const face &f, DynamicList< face > &faces)
Static Public Attributes
static const Enum< triangulationMode > triangulationModeNames_
Detailed Description
Face intersection class.
calculates intersection area by sub-dividing face into triangles and cutting
Source files
faceAreaIntersect.H
faceAreaIntersect.C
Definition at line 55 of file faceAreaIntersect.H.
Member Enumeration Documentation
triangulationMode
enum triangulationMode
Enumerator
tmFan
tmMesh
Definition at line 59 of file faceAreaIntersect.H.
Constructor & Destructor Documentation
faceAreaIntersect()
faceAreaIntersect (const pointField & pointsA, const pointField & pointsB, const DynamicList< face > & trisA, const DynamicList< face > & trisB, const bool reverseB = false, const bool cacheTriangulation = false)
Definition at line 378 of file faceAreaIntersect.C.
Member Function Documentation
tolerance()
Foam::scalar & tolerance () inline static
Definition at line 105 of file faceAreaIntersectI.H.
Referenced by faceAreaWeightAMI::processSourceFace(), and faceAreaWeightAMI::setNextFaces().
triangulate()
void triangulate (const face & f, const pointField & points, const triangulationMode & triMode, faceList & faceTris) static
Definition at line 400 of file faceAreaIntersect.C.
References Foam::exit(), f(), Foam::FatalError, FatalErrorInFunction, points, and PtrList< T >::resize().
cacheTriangulation()
bool cacheTriangulation () const inline
Definition at line 111 of file faceAreaIntersectI.H.
triangles() [1/2]
const Foam::DynamicList< Foam::triPoints > triangles () const inline
Definition at line 118 of file faceAreaIntersectI.H.
triangles() [2/2]
Foam::DynamicList< Foam::triPoints > & triangles () inline
Definition at line 124 of file faceAreaIntersectI.H.
triangleFan()
void triangleFan (const face & f, DynamicList< face > & faces) inline static
Definition at line 24 of file faceAreaIntersectI.H.
References PtrList< T >::append(), f(), and UPtrList< T >::size().
Referenced by advancingFrontAMI::triangulatePatch().
calc()
void calc (const face & faceA, const face & faceB, const vector & n, scalar & area, vector & centroid) const
Definition at line 443 of file faceAreaIntersect.C.
References PtrList< T >::clear(), n, and VectorSpace< Form, Cmpt, Ncmpts >::zero.
overlaps()
bool overlaps (const face & faceA, const face & faceB, const vector & n, const scalar threshold) const
Definition at line 504 of file faceAreaIntersect.C.
References n, and Foam::Zero.
Member Data Documentation
triangulationModeNames_
const Foam::Enum< Foam::faceAreaIntersect::triangulationMode > triangulationModeNames_ static
Definition at line 65 of file faceAreaIntersect.H.
Referenced by advancingFrontAMI::advancingFrontAMI(), and advancingFrontAMI::write().
The documentation for this class was generated from the following files:
src/meshTools/AMIInterpolation/faceAreaIntersect/faceAreaIntersect.H
src/meshTools/AMIInterpolation/faceAreaIntersect/faceAreaIntersect.C
src/meshTools/AMIInterpolation/faceAreaIntersect/faceAreaIntersectI.H