OpenFOAM: MPPICParcel< ParcelType > Class Template Reference
MPPICParcel< ParcelType > Class Template Reference
Lagrangian particle models » Parcels
Wrapper around kinematic parcel types to add MPPIC modelling.
#include <MPPICParcel.H>
Classes
class iNew
class trackingData
Public Member Functions
TypeName ("MPPICParcel")
AddToPropertyList (ParcelType, " (UCorrectx UCorrecty UCorrectz)")
MPPICParcel (const polyMesh &mesh, const barycentric &coordinates, const label celli, const label tetFacei, const label tetPti)
MPPICParcel (const polyMesh &mesh, const vector &position, const label celli)
MPPICParcel (const polyMesh &mesh, const barycentric &coordinates, const label celli, const label tetFacei, const label tetPti, const label typeId, const scalar nParticle0, const scalar d0, const scalar dTarget0, const vector &U0, const vector &UCorrect0, const typename ParcelType::constantProperties &constProps)
MPPICParcel (const polyMesh &mesh, Istream &is, bool readFields=true, bool newFormat=true)
MPPICParcel (const MPPICParcel &p)
MPPICParcel (const MPPICParcel &p, const polyMesh &mesh)
virtual autoPtr< particle > clone () const
virtual autoPtr< particle > clone (const polyMesh &mesh) const
const vector & UCorrect () const
vector & UCorrect ()
template<class TrackCloudType >
bool move (TrackCloudType &cloud, trackingData &td, const scalar trackTime)
void writeProperties (Ostream &os, const wordRes &filters, const word &delim, const bool namesOnly=false) const
Static Public Member Functions
template<class CloudType >
static void readFields (CloudType &c)
template<class CloudType >
static void writeFields (const CloudType &c)
template<class CloudType >
static void readObjects (CloudType &c, const objectRegistry &obr)
template<class CloudType >
static void writeObjects (const CloudType &c, objectRegistry &obr)
Static Public Attributes
static const std::size_t sizeofFields
Protected Attributes
vector UCorrect_
Friends
Ostream & operator<< (Ostream &, const MPPICParcel< ParcelType > &)
Detailed Description
template<class ParcelType>
class Foam::MPPICParcel< ParcelType >
Wrapper around kinematic parcel types to add MPPIC modelling.
Source files
MPPICParcel.H
MPPICParcelI.H
MPPICParcelTrackingDataI.H
MPPICParcel.C
MPPICParcelIO.C
Definition at line 73 of file MPPICParcel.H.
Constructor & Destructor Documentation
MPPICParcel() [1/6]
template<class ParcelType > MPPICParcel (const polyMesh & mesh, const barycentric & coordinates, const label celli, const label tetFacei, const label tetPti) inline
Definition at line 24 of file MPPICParcelI.H.
MPPICParcel() [2/6]
template<class ParcelType > MPPICParcel (const polyMesh & mesh, const vector & position, const label celli) inline
Definition at line 39 of file MPPICParcelI.H.
MPPICParcel() [3/6]
template<class ParcelType > MPPICParcel (const polyMesh & mesh, const barycentric & coordinates, const label celli, const label tetFacei, const label tetPti, const label typeId, const scalar nParticle0, const scalar d0, const scalar dTarget0, const vector & U0, const vector & UCorrect0, const typename ParcelType::constantProperties & constProps) inline
Definition at line 52 of file MPPICParcelI.H.
MPPICParcel() [4/6]
template<class ParcelType > MPPICParcel (const polyMesh & mesh, Istream & is, bool readFields = true, bool newFormat = true)
Definition at line 43 of file MPPICParcelIO.C.
References IOstreamOption::ASCII, VectorSpace< Form, Cmpt, Ncmpts >::data(), FUNCTION_NAME, VectorSpace< Form, Cmpt, Ncmpts >::nComponents, MPPICParcel< ParcelType >::readFields(), Foam::readFields(), MPPICParcel< ParcelType >::sizeofFields, and MPPICParcel< ParcelType >::UCorrect_.
MPPICParcel() [5/6]
template<class ParcelType > MPPICParcel (const MPPICParcel< ParcelType > & p)
MPPICParcel() [6/6]
template<class ParcelType > MPPICParcel (const MPPICParcel< ParcelType > & p, const polyMesh & mesh)
Member Function Documentation
TypeName()
template<class ParcelType > TypeName ("MPPICParcel< ParcelType >")
AddToPropertyList()
template<class ParcelType > AddToPropertyList (ParcelType , " (UCorrectx UCorrecty UCorrectz)")
clone() [1/2]
template<class ParcelType > virtual autoPtr< particle > clone () const inline virtual
Definition at line 237 of file MPPICParcel.H.
clone() [2/2]
template<class ParcelType > virtual autoPtr< particle > clone (const polyMesh & mesh) const inline virtual
Definition at line 243 of file MPPICParcel.H.
References mesh.
UCorrect() [1/2]
template<class ParcelType > const Foam::vector & UCorrect () const inline
Definition at line 89 of file MPPICParcelI.H.
UCorrect() [2/2]
template<class ParcelType > Foam::vector & UCorrect () inline
Definition at line 96 of file MPPICParcelI.H.
move()
template<class ParcelType > template<class TrackCloudType > bool move (TrackCloudType & cloud, trackingData & td, const scalar trackTime)
Definition at line 52 of file MPPICParcel.C.
References f(), p, and U.
readFields()
template<class ParcelType > template<class CloudType > void readFields (CloudType & c) static
Definition at line 82 of file MPPICParcelIO.C.
References IOobjectOption::MUST_READ, p, and UPtrList< T >::size().
Referenced by MPPICParcel< ParcelType >::MPPICParcel().
writeFields()
template<class ParcelType > template<class CloudType > void writeFields (const CloudType & c) static
Definition at line 107 of file MPPICParcelIO.C.
References IOobjectOption::NO_READ, p, and UPtrList< T >::size().
writeProperties()
template<class ParcelType > void writeProperties (Ostream & os, const wordRes & filters, const word & delim, const bool namesOnly = false) const
Definition at line 131 of file MPPICParcelIO.C.
References os(), and writeProp.
readObjects()
template<class ParcelType > template<class CloudType > void readObjects (CloudType & c, const objectRegistry & obr) static
Definition at line 153 of file MPPICParcelIO.C.
References p, and UPtrList< T >::size().
writeObjects()
template<class ParcelType > template<class CloudType > void writeObjects (const CloudType & c, objectRegistry & obr) static
Definition at line 178 of file MPPICParcelIO.C.
References p, and UPtrList< T >::size().
Friends And Related Symbol Documentation
operator<<
template<class ParcelType > Ostream & operator<< (Ostream & , const MPPICParcel< ParcelType > &) friend
Member Data Documentation
sizeofFields
template<class ParcelType > const std::size_t sizeofFields static
Definition at line 80 of file MPPICParcel.H.
Referenced by MPPICParcel< ParcelType >::MPPICParcel().
UCorrect_
template<class ParcelType > vector UCorrect_ protected
Definition at line 164 of file MPPICParcel.H.
Referenced by MPPICParcel< ParcelType >::MPPICParcel().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/parcels/Templates/MPPICParcel/MPPICParcel.H
src/lagrangian/intermediate/parcels/Templates/MPPICParcel/MPPICParcel.C
src/lagrangian/intermediate/parcels/Templates/MPPICParcel/MPPICParcelI.H
src/lagrangian/intermediate/parcels/Templates/MPPICParcel/MPPICParcelIO.C