OpenFOAM: faMeshReconstructor Class Reference
faMeshReconstructor Class Reference
A bare-bones reconstructor for finiteArea meshes when processor meshes are available (in parallel) but an equivalent serial faMesh is needed for reconstruction or decomposition. In these situations, a serial version of the faMesh is needed, but preferably without reconstructing the entire volume mesh.
#include <faMeshReconstructor.H>
Public Member Functions
faMeshReconstructor (const faMesh &procMesh, IOobjectOption::readOption readVolProcAddr=IOobjectOption::MUST_READ)
faMeshReconstructor (const faMesh &procMesh, const labelUList &fvFaceProcAddressing)
~faMeshReconstructor ()
void clearGeom ()
bool good () const noexcept
const labelList & pointProcAddressing () const noexcept
const labelList & edgeProcAddressing () const noexcept
const labelList & faceProcAddressing () const noexcept
const labelList & boundaryProcAddressing () const noexcept
const primitivePatch & patch () const
primitivePatch & patch ()
const faMesh & mesh () const
void writeAddressing () const
void writeAddressing (const word &timeName) const
void writeMesh () const
void writeMesh (const word &timeName) const
Static Public Attributes
static int debug = 0
Detailed Description
A bare-bones reconstructor for finiteArea meshes when processor meshes are available (in parallel) but an equivalent serial faMesh is needed for reconstruction or decomposition. In these situations, a serial version of the faMesh is needed, but preferably without reconstructing the entire volume mesh.
It uses the finiteVolume faceProcAddressing in addition to the geometric information available from the underlying polyMesh.
The resulting equivalent faMesh can be used for basic operations, but caution should be exercised before attempting large operations.
Source files
faMeshReconstructor.H
faMeshReconstructor.C
Definition at line 60 of file faMeshReconstructor.H.
Constructor & Destructor Documentation
faMeshReconstructor() [1/2]
faMeshReconstructor (const faMesh & procMesh, IOobjectOption::readOption readVolProcAddr = IOobjectOption::MUST_READ) explicit
Definition at line 537 of file faMeshReconstructor.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, polyMesh::meshSubDir, Foam::nl, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, UPstream::parRun(), and UPstream::reduceAnd().
faMeshReconstructor() [2/2]
faMeshReconstructor (const faMesh & procMesh, const labelUList & fvFaceProcAddressing)
Definition at line 599 of file faMeshReconstructor.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::nl, and UPstream::parRun().
~faMeshReconstructor()
~faMeshReconstructor ()
Definition at line 621 of file faMeshReconstructor.C.
Member Function Documentation
clearGeom()
void clearGeom ()
Definition at line 627 of file faMeshReconstructor.C.
good()
bool good () const inline noexcept
Definition at line 169 of file faMeshReconstructor.H.
pointProcAddressing()
const labelList & pointProcAddressing () const inline noexcept
Definition at line 172 of file faMeshReconstructor.H.
edgeProcAddressing()
const labelList & edgeProcAddressing () const inline noexcept
Definition at line 178 of file faMeshReconstructor.H.
faceProcAddressing()
const labelList & faceProcAddressing () const inline noexcept
Definition at line 184 of file faMeshReconstructor.H.
boundaryProcAddressing()
const labelList & boundaryProcAddressing () const inline noexcept
Definition at line 190 of file faMeshReconstructor.H.
patch() [1/2]
const Foam::primitivePatch & patch () const
Definition at line 635 of file faMeshReconstructor.C.
patch() [2/2]
Foam::primitivePatch & patch ()
Definition at line 646 of file faMeshReconstructor.C.
mesh()
const Foam::faMesh & mesh () const
Definition at line 657 of file faMeshReconstructor.C.
writeAddressing() [1/2]
void writeAddressing () const
Definition at line 668 of file faMeshReconstructor.C.
writeAddressing() [2/2]
void writeAddressing (const word & timeName) const
Definition at line 674 of file faMeshReconstructor.C.
References faMesh::meshSubDir, IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, and timeName.
writeMesh() [1/2]
void writeMesh () const
Definition at line 707 of file faMeshReconstructor.C.
writeMesh() [2/2]
void writeMesh (const word & timeName) const
Definition at line 713 of file faMeshReconstructor.C.
References fileOperation::fileHandler(), Foam::fileHandler, io(), UPstream::master(), mesh, fileOperation::NewUncollated(), UPstream::parRun(), and IOobject::rename().
Member Data Documentation
debug
int debug = 0 static
Definition at line 139 of file faMeshReconstructor.H.
The documentation for this class was generated from the following files:
src/parallel/reconstruct/faReconstruct/faMeshReconstructor.H
src/parallel/reconstruct/faReconstruct/faMeshReconstructor.C