OpenFOAM: laplacianScheme< Type, GType > Class Template Reference
laplacianScheme< Type, GType > Class Template Reference abstract
Numerics » Finite volume numerical schemes » Laplacian schemes
Abstract base class for laplacian schemes.
#include <laplacianScheme.H>
Public Member Functions
virtual const word & type () const =0
declareRunTimeSelectionTable (tmp, laplacianScheme, Istream,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
laplacianScheme (const fvMesh &mesh)
laplacianScheme (const fvMesh &mesh, Istream &is)
laplacianScheme (const fvMesh &mesh, const tmp< surfaceInterpolationScheme< GType > > &igs, const tmp< snGradScheme< Type > > &sngs)
virtual ~laplacianScheme ()=default
const fvMesh & mesh () const
virtual tmp< fvMatrix< Type > > fvmLaplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > &, const GeometricField< Type, fvPatchField, volMesh > &)=0
virtual tmp< fvMatrix< Type > > fvmLaplacian (const GeometricField< GType, fvPatchField, volMesh > &, const GeometricField< Type, fvPatchField, volMesh > &)
virtual tmp< GeometricField< Type, fvPatchField, volMesh > > fvcLaplacian (const GeometricField< Type, fvPatchField, volMesh > &)=0
virtual tmp< GeometricField< Type, fvPatchField, volMesh > > fvcLaplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > &, const GeometricField< Type, fvPatchField, volMesh > &)=0
virtual tmp< GeometricField< Type, fvPatchField, volMesh > > fvcLaplacian (const GeometricField< GType, fvPatchField, volMesh > &, const GeometricField< Type, fvPatchField, volMesh > &)
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Static Public Member Functions
static tmp< laplacianScheme< Type, GType > > New (const fvMesh &mesh, Istream &schemeData)
Protected Attributes
const fvMesh & mesh_
tmp< surfaceInterpolationScheme< GType > > tinterpGammaScheme_
tmp< snGradScheme< Type > > tsnGradScheme_
Detailed Description
template<class Type, class GType>
class Foam::fv::laplacianScheme< Type, GType >
Abstract base class for laplacian schemes.
Source files
laplacianScheme.H
laplacianScheme.C
Definition at line 66 of file laplacianScheme.H.
Constructor & Destructor Documentation
laplacianScheme() [1/3]
template<class Type , class GType > laplacianScheme (const fvMesh & mesh) inline
Definition at line 112 of file laplacianScheme.H.
laplacianScheme() [2/3]
template<class Type , class GType > laplacianScheme (const fvMesh & mesh, Istream & is) inline
Definition at line 120 of file laplacianScheme.H.
References laplacianScheme< Type, GType >::mesh(), snGradScheme< Type >::New(), surfaceInterpolationScheme< Type >::New(), laplacianScheme< Type, GType >::tinterpGammaScheme_, and laplacianScheme< Type, GType >::tsnGradScheme_.
laplacianScheme() [3/3]
template<class Type , class GType > laplacianScheme (const fvMesh & mesh, const tmp< surfaceInterpolationScheme< GType > > & igs, const tmp< snGradScheme< Type > > & sngs) inline
Definition at line 138 of file laplacianScheme.H.
~laplacianScheme()
template<class Type , class GType > virtual ~laplacianScheme () virtual default
Member Function Documentation
type()
template<class Type , class GType > virtual const word & type () const pure virtual
declareRunTimeSelectionTable()
template<class Type , class GType > declareRunTimeSelectionTable (tmp , laplacianScheme< Type, GType > , Istream , (const fvMesh &mesh, Istream &schemeData) , (mesh, schemeData))
New()
template<class Type , class GType > tmp< laplacianScheme< Type, GType > > New (const fvMesh & mesh, Istream & schemeData) static
Definition at line 40 of file laplacianScheme.C.
References Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, FatalIOErrorInLookup, InfoInFunction, and mesh.
Referenced by Foam::fvc::laplacian(), Foam::fvm::laplacian(), Foam::fvc::laplacian(), Foam::fvm::laplacian(), and Foam::fvc::laplacian().
mesh()
template<class Type , class GType > const fvMesh & mesh () const inline
Definition at line 168 of file laplacianScheme.H.
References laplacianScheme< Type, GType >::mesh_.
Referenced by laplacianScheme< Type, GType >::laplacianScheme().
fvmLaplacian() [1/2]
template<class Type , class GType > virtual tmp< fvMatrix< Type > > fvmLaplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > & , const GeometricField< Type, fvPatchField, volMesh > &) pure virtual
Implemented in gaussLaplacianScheme< Type, GType >, and relaxedNonOrthoGaussLaplacianScheme< Type, GType >.
fvmLaplacian() [2/2]
template<class Type , class GType > tmp< fvMatrix< Type > > fvmLaplacian (const GeometricField< GType, fvPatchField, volMesh > & gamma, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Definition at line 83 of file laplacianScheme.C.
References gamma, and Foam::interpolate().
fvcLaplacian() [1/3]
template<class Type , class GType > virtual tmp< GeometricField< Type, fvPatchField, volMesh > > fvcLaplacian (const GeometricField< Type, fvPatchField, volMesh > &) pure virtual
Implemented in gaussLaplacianScheme< Type, GType >, and relaxedNonOrthoGaussLaplacianScheme< Type, GType >.
fvcLaplacian() [2/3]
template<class Type , class GType > virtual tmp< GeometricField< Type, fvPatchField, volMesh > > fvcLaplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > & , const GeometricField< Type, fvPatchField, volMesh > &) pure virtual
Implemented in gaussLaplacianScheme< Type, GType >, and relaxedNonOrthoGaussLaplacianScheme< Type, GType >.
fvcLaplacian() [3/3]
template<class Type , class GType > tmp< GeometricField< Type, fvPatchField, volMesh > > fvcLaplacian (const GeometricField< GType, fvPatchField, volMesh > & gamma, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Definition at line 95 of file laplacianScheme.C.
References gamma, and Foam::interpolate().
Member Data Documentation
mesh_
template<class Type , class GType > const fvMesh& mesh_ protected
Definition at line 75 of file laplacianScheme.H.
Referenced by laplacianScheme< Type, GType >::mesh().
tinterpGammaScheme_
template<class Type , class GType > tmp<surfaceInterpolationScheme<GType> > tinterpGammaScheme_ protected
Definition at line 76 of file laplacianScheme.H.
Referenced by laplacianScheme< Type, GType >::laplacianScheme().
tsnGradScheme_
template<class Type , class GType > tmp<snGradScheme<Type> > tsnGradScheme_ protected
Definition at line 77 of file laplacianScheme.H.
Referenced by laplacianScheme< Type, GType >::laplacianScheme().
The documentation for this class was generated from the following files:
src/finiteVolume/finiteVolume/laplacianSchemes/laplacianScheme/laplacianScheme.H
src/finiteVolume/finiteVolume/laplacianSchemes/laplacianScheme/laplacianScheme.C