OpenFOAM: surfaceFieldWriter Class Reference
surfaceFieldWriter Class Reference
Write surfaces fields (as PointData) in VTP format. Legacy VTK format is intentionally not supported.
#include <foamVtkSurfaceFieldWriter.H>
Public Member Functions
surfaceFieldWriter (const fvMesh &mesh, const vtk::outputOptions opts=vtk::formatType::INLINE_BASE64)
surfaceFieldWriter (const fvMesh &mesh, const fileName &file, bool parallel=Pstream::parRun())
surfaceFieldWriter (const fvMesh &mesh, const vtk::outputOptions opts, const fileName &file, bool parallel=Pstream::parRun())
virtual ~surfaceFieldWriter ()=default
virtual bool beginFile (std::string title="")
virtual bool writeGeometry ()
virtual bool beginCellData (label nFields=0)
virtual bool beginPointData (label nFields=0)
void write (const surfaceVectorField &field)
Public Member Functions inherited from fileWriter
fileWriter (const vtk::fileTag contentType, const vtk::outputOptions opts)
virtual ~fileWriter ()
vtk::fileTag contentType () const noexcept
vtk::outputOptions opts () const noexcept
word ext () const
bool legacy () const noexcept
bool parallel () const noexcept
const word & state () const
const fileName & output () const noexcept
virtual bool open (const fileName &file, bool parallel=UPstream::parRun())
void close ()
bool beginFieldData (label nFields=0)
bool isCellData () const noexcept
bool isPointData () const noexcept
label nCellData () const noexcept
label nPointData () const noexcept
bool endFieldData ()
bool endCellData ()
bool endPointData ()
void writeTimeValue (scalar timeValue)
Static Public Member Functions
static word ext (vtk::outputOptions)
Additional Inherited Members
Protected Types inherited from fileWriter
enum outputState : uint8_t {
CLOSED = 0 , OPENED , DECLARED , FIELD_DATA ,
PIECE , CELL_DATA , POINT_DATA
}
Protected Member Functions inherited from fileWriter
void checkFormatterValidity () const
Ostream & reportBadState (Ostream &, outputState expected) const
Ostream & reportBadState (Ostream &, outputState, outputState) const
std::ofstream & os () noexcept
vtk::formatter & format ()
bool isState (outputState test) const noexcept
bool notState (outputState test) const noexcept
template<class Type >
void beginDataArray (const word &fieldName, const label nValues)
void endDataArray ()
void beginPoints (const label nPoints)
void endPoints ()
bool enter_Piece ()
bool endPiece ()
bool enter_CellData (label nEntries, label nFields)
bool enter_PointData (label nEntries, label nFields)
bool exit_File ()
template<class Type >
void writeUniform (const word &fieldName, const Type &val, const label nValues)
template<class Type >
void writeBasicField (const word &fieldName, const UList< Type > &field)
bool writeProcIDs (const label nValues)
fileWriter (const fileWriter &)=delete
void operator= (const fileWriter &)=delete
Protected Attributes inherited from fileWriter
outputState state_
vtk::fileTag contentType_
bool parallel_
vtk::outputOptions opts_
label nCellData_
label nPointData_
fileName outputFile_
autoPtr< vtk::formatter > format_
std::ofstream os_
Static Protected Attributes inherited from fileWriter
static const Enum< outputState > stateNames
Detailed Description
Write surfaces fields (as PointData) in VTP format. Legacy VTK format is intentionally not supported.
The file output is structured as HEAD, FIELD_DATA, PIECE followed by any CELL_DATA or POINT_DATA. These states are tracked internally to help detect logic errors.
The FieldData element is to be placed prior to writing any geometry Piece. This moves the information to the front of the output file for visibility and simplifies the logic.
Note
Parallel output is combined into a single Piece without point merging, which is similar to using multi-piece data sets, but allows more convenient creation as a streaming process. In the future, the duplicate points at processor connections may be addressed using ghost points.
Source files
foamVtkSurfaceFieldWriter.H
surfaceFieldWriter.C
Definition at line 67 of file foamVtkSurfaceFieldWriter.H.
Constructor & Destructor Documentation
surfaceFieldWriter() [1/3]
surfaceFieldWriter (const fvMesh & mesh, const vtk::outputOptions opts = vtk::formatType::INLINE_BASE64)
Definition at line 54 of file foamVtkSurfaceFieldWriter.C.
References outputOptions::append(), outputOptions::legacy(), and fileWriter::opts_.
surfaceFieldWriter() [2/3]
surfaceFieldWriter (const fvMesh & mesh, const fileName & file, bool parallel = Pstream::parRun())
Definition at line 69 of file foamVtkSurfaceFieldWriter.C.
References fileWriter::open(), and fileWriter::parallel().
surfaceFieldWriter() [3/3]
surfaceFieldWriter (const fvMesh & mesh, const vtk::outputOptions opts, const fileName & file, bool parallel = Pstream::parRun())
Definition at line 82 of file foamVtkSurfaceFieldWriter.C.
References fileWriter::open(), and fileWriter::parallel().
~surfaceFieldWriter()
virtual ~surfaceFieldWriter () virtual default
Member Function Documentation
ext()
static word ext (vtk::outputOptions) inline static
Definition at line 135 of file foamVtkSurfaceFieldWriter.H.
References Foam::vtk::fileExtension, and Foam::vtk::POLY_DATA.
beginFile()
bool beginFile (std::string title = "") virtual
Reimplemented from fileWriter.
Definition at line 98 of file foamVtkSurfaceFieldWriter.C.
References fileWriter::beginFile(), and Foam::name().
writeGeometry()
bool writeGeometry () virtual
Implements fileWriter.
Definition at line 128 of file foamVtkSurfaceFieldWriter.C.
References format(), Foam::vtk::NUMBER_OF_POINTS, Foam::vtk::PIECE, Foam::reduce(), UList< T >::size(), Foam::vtk::writeList(), and Foam::vtk::writeListParallel().
beginCellData()
bool beginCellData (label nFields = 0) virtual
Implements fileWriter.
Definition at line 187 of file foamVtkSurfaceFieldWriter.C.
beginPointData()
bool beginPointData (label nFields = 0) virtual
Implements fileWriter.
Definition at line 194 of file foamVtkSurfaceFieldWriter.C.
write()
void write (const surfaceVectorField & field)
Definition at line 201 of file foamVtkSurfaceFieldWriter.C.
References boundary, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, field(), Foam::nl, Foam::reduce(), Foam::vtk::writeList(), and Foam::vtk::writeListParallel().
The documentation for this class was generated from the following files:
src/conversion/vtk/output/foamVtkSurfaceFieldWriter.H
src/conversion/vtk/output/foamVtkSurfaceFieldWriter.C