OpenFOAM: gradientEnergyFvPatchScalarField Class Reference
gradientEnergyFvPatchScalarField Class Reference
Boundary conditions » Thermophysical
This boundary condition provides a gradient condition for internal energy, where the gradient is calculated using:
#include <gradientEnergyFvPatchScalarField.H>
Public Member Functions
TypeName ("gradientEnergy")
gradientEnergyFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
gradientEnergyFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
gradientEnergyFvPatchScalarField (const gradientEnergyFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
gradientEnergyFvPatchScalarField (const gradientEnergyFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
gradientEnergyFvPatchScalarField (const gradientEnergyFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
This boundary condition provides a gradient condition for internal energy, where the gradient is calculated using:
where
= energy at patch faces [J]
= energy at patch internal cells [J]
= pressure [bar]
= temperature [K]
= specific heat [J/kg/K]
= distance between patch face and internal cell centres [m]
Usage
Example of the boundary condition specification:
<patchName>
{
    type            gradientEnergy;
    gradient        uniform 10;
}
See also
Foam::fixedGradientFvPatchField
Source files
gradientEnergyFvPatchScalarField.H
gradientEnergyFvPatchScalarField.C
Definition at line 101 of file gradientEnergyFvPatchScalarField.H.
Constructor & Destructor Documentation
gradientEnergyFvPatchScalarField() [1/5]
gradientEnergyFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 29 of file gradientEnergyFvPatchScalarField.C.
gradientEnergyFvPatchScalarField() [2/5]
gradientEnergyFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 53 of file gradientEnergyFvPatchScalarField.C.
gradientEnergyFvPatchScalarField() [3/5]
gradientEnergyFvPatchScalarField (const gradientEnergyFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 40 of file gradientEnergyFvPatchScalarField.C.
gradientEnergyFvPatchScalarField() [4/5]
gradientEnergyFvPatchScalarField (const gradientEnergyFvPatchScalarField & tppsf)
Definition at line 65 of file gradientEnergyFvPatchScalarField.C.
gradientEnergyFvPatchScalarField() [5/5]
gradientEnergyFvPatchScalarField (const gradientEnergyFvPatchScalarField & tppsf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 75 of file gradientEnergyFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("gradientEnergy")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 146 of file gradientEnergyFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 162 of file gradientEnergyFvPatchScalarField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 88 of file gradientEnergyFvPatchScalarField.C.
References fvPatchField< Type >::evaluate(), basicThermo::lookupThermo(), and fvPatchField< Type >::snGrad().
write()
void write (Ostream & os) const virtual
Definition at line 115 of file gradientEnergyFvPatchScalarField.C.
References os(), fixedGradientFvPatchField< Type >::write(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/thermophysicalModels/basic/derivedFvPatchFields/gradientEnergy/gradientEnergyFvPatchScalarField.H
src/thermophysicalModels/basic/derivedFvPatchFields/gradientEnergy/gradientEnergyFvPatchScalarField.C