OpenFOAM: List< T > Class Template Reference
List< T > Class Template Reference
A 1D array of objects of type <T>, where the size of the vector is known and used for subscript bounds checking, etc.
#include <List.H>
Inherits UList< T >.
Inherited by CompactIOList< face, label >, PtrListDetail< CloudFunctionObject< CloudType > >, PtrListDetail< Field< Type > >, PtrListDetail< PatchField< Type > >, PtrListDetail< InjectionModel< CloudType > >, PtrListDetail< fvPatchField< symmTensor > >, PtrListDetail< fvPatchField< scalar > >, PtrListDetail< MRFZone >, PtrListDetail< pointPatchField< Type > >, PtrListDetail< ParticleForce< CloudType > >, PtrListDetail< joint >, PtrListDetail< ZoneType >, PtrListDetail< block >, PtrListDetail< coalCloud >, PtrListDetail< coordinateSystem >, PtrListDetail< fa::option >, PtrListDetail< entry >, PtrListDetail< faPatchMapper >, PtrListDetail< functionObject >, PtrListDetail< fv::option >, PtrListDetail< fvPatchMapper >, PtrListDetail< pairPotential >, PtrListDetail< pointPatchMapper >, PtrListDetail< polyMeshModifier >, PtrListDetail< porosityModel >, PtrListDetail< profileModel >, PtrListDetail< Reaction< ThermoType > >, PtrListDetail< extendedFeatureEdgeMesh >, PtrListDetail< force >, PtrListDetail< injectionModel >, PtrListDetail< pyrolysisModel >, PtrListDetail< regionModelFunctionObject >, PtrListDetail< transferModel >, PtrListDetail< sampledSet >, PtrListDetail< sampledSurface >, PtrListDetail< searchableSurface >, PtrListDetail< tetherPotential >, PtrListDetail< fvPatchField< vector > >, PtrListDetail< fvPatchField< tensor > >, PtrListDetail< Foam::GeometricField >, PtrListDetail< Foam::fvPatchField< scalar > >, PtrListDetail< Foam::fvPatchField< Foam::Vector > >, PtrListDetail< Foam::pointPatchField< Foam::Vector > >, PtrListDetail< Foam::radiation::reflectionModel >, PtrListDetail< Field< Foam::Vector > >, PtrListDetail< Field< scalar > >, PtrListDetail< Foam::OFstream >, PtrListDetail< Foam::Field >, PtrListDetail< Foam::List >, PtrListDetail< Foam::lduPrimitiveMesh >, PtrListDetail< Foam::lduMatrix >, PtrListDetail< Foam::PtrList< Foam::lduInterfaceField > >, PtrListDetail< Foam::lduInterfaceField >, PtrListDetail< Foam::UPtrList >, PtrListDetail< Foam::FieldField< Foam::Field, scalar > >, PtrListDetail< Foam::Field< scalar > >, PtrListDetail< Foam::distributionModels::general >, PtrListDetail< ParticleForce< KinematicCloud< Foam::DSMCCloud > > >, PtrListDetail< CloudFunctionObject< KinematicCloud< Foam::DSMCCloud > > >, PtrListDetail< InjectionModel< Foam::KinematicCloud< Foam::DSMCCloud > > >, PtrListDetail< ParticleForce< KinematicCloud< CloudType > > >, PtrListDetail< CloudFunctionObject< KinematicCloud< CloudType > > >, PtrListDetail< Foam::regionModels::areaSurfaceFilmModels::liquidFilmBase >, PtrListDetail< Type >, PtrListDetail< Foam::Field< LUType > >, PtrListDetail< fvsPatchField< scalar > >, PtrListDetail< Foam::PatchInteractionModel< Foam::DSMCCloud > >, PtrListDetail< Foam::List< char > >, PtrListDetail< boundaryEntry >, PtrListDetail< Foam::diameterModels::populationBalanceModel >, PtrListDetail< Foam::RBD::rigidBody >, PtrListDetail< Foam::RBD::subBody >, PtrListDetail< Foam::RBD::joint >, PtrListDetail< Foam::RBD::restraint >, PtrListDetail< Foam::DimensionedField >, PtrListDetail< Foam::patchInjectionBase >, PtrListDetail< Foam::Reaction< ThermoType > >, PtrListDetail< ThermoType >, PtrListDetail< Foam::adjointSolver >, PtrListDetail< Foam::Function1< scalar > >, PtrListDetail< blockVertex >, PtrListDetail< blockEdge >, PtrListDetail< blockFace >, PtrListDetail< Foam::entry >, PtrListDetail< Foam::boundaryPatch >, PtrListDetail< Foam::fvMeshSubset >, PtrListDetail< Foam::cellModel >, PtrListDetail< Foam::cellSizeAndAlignmentControl >, PtrListDetail< pointPatchField< scalar > >, PtrListDetail< Foam::extendedFeatureEdgeMesh >, PtrListDetail< Foam::surfaceZonesInfo >, PtrListDetail< Foam::dictionary >, PtrListDetail< const Foam::coordSet >, PtrListDetail< Foam::Field< label > >, PtrListDetail< Foam::Field< Foam::Vector > >, PtrListDetail< Foam::Field< Foam::SphericalTensor > >, PtrListDetail< Foam::Field< Foam::SymmTensor > >, PtrListDetail< Foam::Field< Foam::Tensor > >, PtrListDetail< Foam::Function1< Type > >, PtrListDetail< Foam::topoSetFaceSource >, PtrListDetail< Foam::decompositionConstraint >, PtrListDetail< Foam::diameterModels::IATEsource >, PtrListDetail< Foam::PtrList< Foam::dimensioned > >, PtrListDetail< Foam::dimensioned >, PtrListDetail< Foam::diameterModels::velocityGroup >, PtrListDetail< Foam::diameterModels::sizeGroup >, PtrListDetail< Foam::diameterModels::coalescenceModel >, PtrListDetail< Foam::diameterModels::breakupModel >, PtrListDetail< Foam::diameterModels::binaryBreakupModel >, PtrListDetail< Foam::diameterModels::driftModel >, PtrListDetail< Foam::diameterModels::nucleationModel >, PtrListDetail< pointPatchField< vector > >, PtrListDetail< Foam::Field< solveScalar > >, PtrListDetail< Foam::FieldField< Foam::Field, solveScalar > >, PtrListDetail< Foam::motionSolver >, PtrListDetail< Foam::indexedOctree< Foam::treeDataEdge > >, PtrListDetail< temperatureCoupling >, PtrListDetail< Foam::PatchFunction1Types::MappedFile< scalar > >, PtrListDetail< faPatchField< scalar > >, PtrListDetail< Foam::faFieldDecomposer::patchFieldDecomposer >, PtrListDetail< Foam::faFieldDecomposer::processorAreaPatchFieldDecomposer >, PtrListDetail< Foam::faFieldDecomposer::processorEdgePatchFieldDecomposer >, PtrListDetail< Foam::GeometricField< scalar, Foam::faPatchField, Foam::areaMesh > >, PtrListDetail< Foam::faPatchField< scalar > >, PtrListDetail< Foam::GeometricField< scalar, Foam::faePatchField, Foam::edgeMesh > >, PtrListDetail< Foam::faePatchField< scalar > >, PtrListDetail< Foam::GeometricField< Foam::Vector, Foam::faPatchField, Foam::areaMesh > >, PtrListDetail< Foam::faPatchField< Foam::Vector > >, PtrListDetail< Foam::GeometricField< Foam::Vector, Foam::faePatchField, Foam::edgeMesh > >, PtrListDetail< Foam::faePatchField< Foam::Vector > >, PtrListDetail< Foam::GeometricField< Foam::SphericalTensor, Foam::faPatchField, Foam::areaMesh > >, PtrListDetail< Foam::faPatchField< Foam::SphericalTensor > >, PtrListDetail< Foam::GeometricField< Foam::SphericalTensor, Foam::faePatchField, Foam::edgeMesh > >, PtrListDetail< Foam::faePatchField< Foam::SphericalTensor > >, PtrListDetail< Foam::GeometricField< Foam::SymmTensor, Foam::faPatchField, Foam::areaMesh > >, PtrListDetail< Foam::faPatchField< Foam::SymmTensor > >, PtrListDetail< Foam::GeometricField< Foam::SymmTensor, Foam::faePatchField, Foam::edgeMesh > >, PtrListDetail< Foam::faePatchField< Foam::SymmTensor > >, PtrListDetail< Foam::GeometricField< Foam::Tensor, Foam::faPatchField, Foam::areaMesh > >, PtrListDetail< Foam::faPatchField< Foam::Tensor > >, PtrListDetail< Foam::GeometricField< Foam::Tensor, Foam::faePatchField, Foam::edgeMesh > >, PtrListDetail< Foam::faePatchField< Foam::Tensor > >, PtrListDetail< Foam::faMesh >, PtrListDetail< Foam::IOList >, PtrListDetail< Foam::Field< Type > >, PtrListDetail< Foam::mapDistributeBase >, PtrListDetail< const Foam::UList >, PtrListDetail< Foam::functionObject >, PtrListDetail< ParticleForce< KinematicCloud< Cloud< basicKinematicCollidingParcel > > > >, PtrListDetail< CloudFunctionObject< KinematicCloud< Cloud< basicKinematicCollidingParcel > > > >, PtrListDetail< Foam::functionObjects::runTimeControls::runTimeCondition >, PtrListDetail< Foam::vtk::vtuCells >, PtrListDetail< Foam::fvFieldDecomposer::patchFieldDecomposer >, PtrListDetail< Foam::fvFieldDecomposer::processorVolPatchFieldDecomposer >, PtrListDetail< Foam::fvFieldDecomposer::processorSurfacePatchFieldDecomposer >, PtrListDetail< Foam::DimensionedField< scalar, Foam::volMesh > >, PtrListDetail< Foam::GeometricField< scalar, Foam::fvPatchField, Foam::volMesh > >, PtrListDetail< Foam::GeometricField< scalar, Foam::fvsPatchField, Foam::surfaceMesh > >, PtrListDetail< Foam::fvsPatchField< scalar > >, PtrListDetail< Foam::DimensionedField< Foam::Vector, Foam::volMesh > >, PtrListDetail< Foam::GeometricField< Foam::Vector, Foam::fvPatchField, Foam::volMesh > >, PtrListDetail< Foam::GeometricField< Foam::Vector, Foam::fvsPatchField, Foam::surfaceMesh > >, PtrListDetail< Foam::fvsPatchField< Foam::Vector > >, PtrListDetail< Foam::DimensionedField< Foam::SphericalTensor, Foam::volMesh > >, PtrListDetail< Foam::GeometricField< Foam::SphericalTensor, Foam::fvPatchField, Foam::volMesh > >, PtrListDetail< Foam::fvPatchField< Foam::SphericalTensor > >, PtrListDetail< Foam::GeometricField< Foam::SphericalTensor, Foam::fvsPatchField, Foam::surfaceMesh > >, PtrListDetail< Foam::fvsPatchField< Foam::SphericalTensor > >, PtrListDetail< Foam::DimensionedField< Foam::SymmTensor, Foam::volMesh > >, PtrListDetail< Foam::GeometricField< Foam::SymmTensor, Foam::fvPatchField, Foam::volMesh > >, PtrListDetail< Foam::fvPatchField< Foam::SymmTensor > >, PtrListDetail< Foam::GeometricField< Foam::SymmTensor, Foam::fvsPatchField, Foam::surfaceMesh > >, PtrListDetail< Foam::fvsPatchField< Foam::SymmTensor > >, PtrListDetail< Foam::DimensionedField< Foam::Tensor, Foam::volMesh > >, PtrListDetail< Foam::GeometricField< Foam::Tensor, Foam::fvPatchField, Foam::volMesh > >, PtrListDetail< Foam::fvPatchField< Foam::Tensor > >, PtrListDetail< Foam::GeometricField< Foam::Tensor, Foam::fvsPatchField, Foam::surfaceMesh > >, PtrListDetail< Foam::fvsPatchField< Foam::Tensor > >, PtrListDetail< Foam::fvMesh >, PtrListDetail< Foam::fvMatrix< Type > >, PtrListDetail< Foam::ignitionSite >, PtrListDetail< Foam::implicitFunction >, PtrListDetail< Foam::adjointSolverManager >, PtrListDetail< Foam::incompressible::adjointSensitivity >, PtrListDetail< Foam::fvPatchField< Type > >, PtrListDetail< Foam::pointPatchField< Type > >, PtrListDetail< Foam::fvsPatchField< Type > >, PtrListDetail< Foam::PtrList< Foam::IOField< label > > >, PtrListDetail< Foam::IOField< label > >, PtrListDetail< Foam::PtrList< Foam::CompactIOField< Foam::Field< label >, label > > >, PtrListDetail< Foam::CompactIOField< Foam::Field< label >, label > >, PtrListDetail< Foam::PtrList< Foam::IOField< scalar > > >, PtrListDetail< Foam::IOField< scalar > >, PtrListDetail< Foam::PtrList< Foam::CompactIOField< Foam::Field< scalar >, scalar > > >, PtrListDetail< Foam::CompactIOField< Foam::Field< scalar >, scalar > >, PtrListDetail< Foam::PtrList< Foam::IOField< Foam::Vector > > >, PtrListDetail< Foam::IOField< Foam::Vector > >, PtrListDetail< Foam::PtrList< Foam::CompactIOField< Foam::Field< Foam::Vector >, Foam::Vector > > >, PtrListDetail< Foam::CompactIOField< Foam::Field< Foam::Vector >, Foam::Vector > >, PtrListDetail< Foam::PtrList< Foam::IOField< Foam::SphericalTensor > > >, PtrListDetail< Foam::IOField< Foam::SphericalTensor > >, PtrListDetail< Foam::PtrList< Foam::CompactIOField< Foam::Field< Foam::SphericalTensor >, Foam::SphericalTensor > > >, PtrListDetail< Foam::CompactIOField< Foam::Field< Foam::SphericalTensor >, Foam::SphericalTensor > >, PtrListDetail< Foam::PtrList< Foam::IOField< Foam::SymmTensor > > >, PtrListDetail< Foam::IOField< Foam::SymmTensor > >, PtrListDetail< Foam::PtrList< Foam::CompactIOField< Foam::Field< Foam::SymmTensor >, Foam::SymmTensor > > >, PtrListDetail< Foam::CompactIOField< Foam::Field< Foam::SymmTensor >, Foam::SymmTensor > >, PtrListDetail< Foam::PtrList< Foam::IOField< Foam::Tensor > > >, PtrListDetail< Foam::IOField< Foam::Tensor > >, PtrListDetail< Foam::PtrList< Foam::CompactIOField< Foam::Field< Foam::Tensor >, Foam::Tensor > > >, PtrListDetail< Foam::CompactIOField< Foam::Field< Foam::Tensor >, Foam::Tensor > >, PtrListDetail< const lduInterfaceField >, PtrListDetail< const lduInterface >, PtrListDetail< const Foam::lduInterface >, PtrListDetail< Foam::lduMesh >, PtrListDetail< fvsPatchField< vector > >, PtrListDetail< Foam::liquidProperties >, PtrListDetail< Foam::AMIInterpolation >, PtrListDetail< Foam::decompositionMethod >, PtrListDetail< Foam::solidBodyMotionFunction >, PtrListDetail< Foam::multiphaseInter::phaseModel >, PtrListDetail< Foam::objective >, PtrListDetail< Foam::primalSolver >, PtrListDetail< const Foam::lduPrimitiveProcessorInterface >, PtrListDetail< Foam::PrimitivePatch >, PtrListDetail< phaseModel >, PtrListDetail< Foam::pointFieldDecomposer::patchFieldDecomposer >, PtrListDetail< Foam::GeometricField< scalar, Foam::pointPatchField, Foam::pointMesh > >, PtrListDetail< Foam::pointPatchField< scalar > >, PtrListDetail< Foam::GeometricField< Foam::Vector, Foam::pointPatchField, Foam::pointMesh > >, PtrListDetail< Foam::GeometricField< Foam::SphericalTensor, Foam::pointPatchField, Foam::pointMesh > >, PtrListDetail< Foam::pointPatchField< Foam::SphericalTensor > >, PtrListDetail< Foam::GeometricField< Foam::SymmTensor, Foam::pointPatchField, Foam::pointMesh > >, PtrListDetail< Foam::pointPatchField< Foam::SymmTensor > >, PtrListDetail< Foam::GeometricField< Foam::Tensor, Foam::pointPatchField, Foam::pointMesh > >, PtrListDetail< Foam::pointPatchField< Foam::Tensor > >, PtrListDetail< Foam::pointMesh >, PtrListDetail< Foam::PrimitivePatchInterpolation >, PtrListDetail< pointZone >, PtrListDetail< faceZone >, PtrListDetail< cellZone >, PtrListDetail< Foam::procLduInterface >, PtrListDetail< Foam::Time >, PtrListDetail< Foam::profilingInformation >, PtrListDetail< GasThermo >, PtrListDetail< Foam::radiation::boundaryRadiationPropertiesPatch >, PtrListDetail< Foam::radiation::radiativeIntensityRay >, PtrListDetail< Foam::indexedOctree< Foam::treeDataPoint > >, PtrListDetail< faPatchField< tensor > >, PtrListDetail< faPatchField< vector > >, PtrListDetail< faePatchField< scalar > >, PtrListDetail< Foam::PtrList< Foam::AMIInterpolation > >, PtrListDetail< bodyMesh >, PtrListDetail< Foam::mappedPatchBase >, PtrListDetail< Foam::coordSetWriter >, PtrListDetail< Foam::coordSet >, PtrListDetail< Foam::surfaceWriter >, PtrListDetail< Foam::coordSystem::cartesian >, PtrListDetail< Foam::searchableSurface >, PtrListDetail< Foam::cellSizeFunction >, PtrListDetail< Foam::sixDoFRigidBodyMotionRestraint >, PtrListDetail< Foam::sixDoFRigidBodyMotionConstraint >, PtrListDetail< Foam::Reaction< SolidThermo > >, PtrListDetail< SolidThermo >, PtrListDetail< Foam::solidProperties >, PtrListDetail< Foam::dimensionSet >, PtrListDetail< Foam::interpolation< scalar > >, PtrListDetail< Foam::interpolation< Foam::Vector > >, PtrListDetail< Foam::triSurfaceMesh >, PtrListDetail< Foam::indexedOctree >, PtrListDetail< Foam::Function1< Foam::Vector > >, PtrListDetail< Foam::Function1< Foam::SymmTensor > >, PtrListDetail< Foam::Function1< TypeR > >, PtrListDetail< Foam::NURBS3DVolume >, PtrListDetail< const Foam::Field >, DiagonalMatrix< cmptType >, DiagonalMatrix< scalar >, DynamicList< label >, DynamicList< token >, DynamicList< taggedInfoType >, DynamicList< point >, DynamicList< FixedList< point, N > >, DynamicList< Foam::labelRange >, DynamicList< word >, DynamicList< Foam::PairCollisionRecord< vector > >, DynamicList< Foam::WallCollisionRecord< vector > >, DynamicList< Foam::PairCollisionRecord< PairType > >, DynamicList< Foam::WallCollisionRecord< WallType > >, DynamicList< ParcelType * >, DynamicList< Foam::STLpoint >, DynamicList< Foam::word >, DynamicList< tokenType, 16 >, DynamicList< Foam::Tuple2 >, DynamicList< parcelType * >, DynamicList< scalar >, DynamicList< Foam::string >, DynamicList< Foam::particleInfo >, DynamicList< char >, DynamicList< Foam::spatialTransform >, DynamicList< Foam::SpatialVector >, DynamicList< Foam::SpatialTensor >, DynamicList< Foam::CompactSpatialTensor >, DynamicList< Foam::Tensor >, DynamicList< Foam::Vector >, DynamicList< int >, DynamicList< Foam::List< int > >, DynamicList< Foam::List< Foam::UPstream::commsStruct > >, DynamicList< Foam::face >, DynamicList< node >, DynamicList< Foam::DynamicList< label > >, DynamicList< Foam::DynamicList< Foam::Vector > >, DynamicList< Foam::UPstream::Request >, DynamicList< void * >, DynamicList< Foam::fileName >, DynamicList< Foam::Tuple2< Foam::fileName, std::string > >, DynamicList< Foam::triPoints >, DynamicList< Foam::List >, DynamicList< ABAQUSCore::shapeType >, DynamicList< fileState >, DynamicList< double >, DynamicList< Foam::wordRe >, DynamicList< Foam::List< Foam::Vector > >, DynamicList< List< vector > >, DynamicList< Type >, DynamicList< Foam::glTF::animation::glTFSampler >, DynamicList< Foam::glTF::animation::glTFChannel >, DynamicList< Foam::Tuple2< Foam::string, label > >, DynamicList< Foam::glTF::object >, DynamicList< Foam::glTF::mesh >, DynamicList< Foam::glTF::bufferView >, DynamicList< Foam::glTF::accessor >, DynamicList< Foam::glTF::animation >, DynamicList< vector >, DynamicList< Foam::FixedList< label, 3 > >, DynamicList< Foam::FixedList< scalar, 3 > >, DynamicList< bool >, DynamicList< Foam::edge >, DynamicList< Foam::cellShape >, DynamicList< Foam::dictionary >, DynamicList< Foam::molecule * >, DynamicList< Foam::DynamicList< Foam::profilingInformation *, 16 > >, DynamicList< Foam::profilingInformation *, 16 >, DynamicList< Foam::profilingInformation * >, DynamicList< Foam::clockValue >, DynamicList< Foam::refinementHistory::splitCell8 >, DynamicList< Foam::Instant >, DynamicList< vtmEntry >, Field< T >, Field< symmTensor >, Field< scalar >, Field< vector >, Field< tensor >, Field< TypeGrad >, Field< Foam::SymmTensor >, Field< solveScalar >, Field< Foam::Vector >, Field< DType >, Field< Foam::Field >, Field< LUType >, Field< Foam::Vector< bool > >, Field< InputType >, Field< bool >, Field< label >, Field< complexVector >, Field< Foam::SphericalTensor >, Field< Foam::Tensor >, Field< Foam::Field< Type > >, Field< Foam::Field< label > >, Field< Foam::Field< scalar > >, Field< Foam::Field< Foam::Vector > >, Field< Foam::Field< Foam::SphericalTensor > >, Field< Foam::Field< Foam::SymmTensor > >, Field< Foam::Field< Foam::Tensor > >, Field< Foam::Vector2D >, GlobalIOList< kinematicParcelInjectionData >, GlobalIOList< reactingParcelInjectionData >, GlobalIOList< reactingMultiphaseParcelInjectionData >, IOList< label >, IOList< labelList >, bufferedAccumulator< scalar >, interpolation2DTable< scalar >, interpolationTable< scalar >, uniformInterpolationTable< scalar >, BinSum< IndexType, List, CombineOp >, CompactIOList< T, BaseType >, DynamicList< T, SizeMin >, IOList< T >, SortableList< T >, faceTriangulation, and pTraits< List< T > >.
Public Types
typedef SubList< T > subList
Public Types inherited from UList< T >
typedef T value_type
typedef T * pointer
typedef const T * const_pointer
typedef T & reference
typedef const T & const_reference
typedef T * iterator
typedef const T * const_iterator
typedef label size_type
typedef label difference_type
typedef std::reverse_iterator< iterator > reverse_iterator
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
Public Member Functions
constexpr List () noexcept
List (const label len)
List (const label len, const T &val)
List (const label len, const Foam::zero)
List (const Foam::one, const T &val)
List (const Foam::one, T &&val)
List (const Foam::one, const Foam::zero)
List (const List< T > &a)
List (const UList< T > &a)
List (List< T > &a, bool reuse)
List (const UList< T > &list, const labelUList &indices)
template<unsigned N>
List (const UList< T > &list, const FixedList< label, N > &indices)
template<unsigned N>
List (const FixedList< T, N > &list)
List (const PtrList< T > &list)
List (const SLList< T > &list)
template<class Addr >
List (const IndirectListBase< T, Addr > &list)
List (std::initializer_list< T > list)
List (List< T > &&list)
template<int SizeMin>
List (DynamicList< T, SizeMin > &&list)
List (SLList< T > &&list)
List (Istream &is)
autoPtr< List< T > > clone () const
~List ()
void clear ()
void resize (const label len)
void resize (const label len, const T &val)
void resize_nocopy (const label len)
void setSize (const label n)
void setSize (const label n, const T &val)
void transfer (List< T > &list)
template<int SizeMin>
void transfer (DynamicList< T, SizeMin > &list)
T & newElmt (const label i)
template<class... Args>
T & emplace_back (Args &&... args)
void push_back (const T &val)
void push_back (T &&val)
void push_back (const UList< T > &list)
template<class Addr >
void push_back (const IndirectListBase< T, Addr > &list)
label push_uniq (const T &val)
void pop_back (label n=1)
void operator= (const UList< T > &a)
void operator= (const List< T > &list)
void operator= (const SLList< T > &list)
template<class Addr >
void operator= (const IndirectListBase< T, Addr > &list)
template<unsigned N>
void operator= (const FixedList< T, N > &list)
void operator= (std::initializer_list< T > list)
void operator= (const T &val)
void operator= (const Foam::zero)
void operator= (List< T > &&list)
template<int SizeMin>
void operator= (DynamicList< T, SizeMin > &&list)
void operator= (SLList< T > &&list)
Istream & readList (Istream &is)
void shallowCopy (const UList< T > &)=delete
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type set (const label i, bool val=true)
void append (const T &val)
void append (T &&val)
void append (const UList< T > &list)
template<class Addr >
void append (const IndirectListBase< T, Addr > &list)
label appendUniq (const T &val)
Istream & readList (Istream &is)
void resize (const label newLen)
Istream & readList (Istream &is)
Public Member Functions inherited from UList< T >
UList (const UList< T > &)=default
constexpr UList () noexcept
UList (T *__restrict__ v, const label len) noexcept
label fcIndex (const label i) const noexcept
label rcIndex (const label i) const noexcept
const T & fcValue (const label i) const
T & fcValue (const label i)
const T & rcValue (const label i) const
T & rcValue (const label i)
const T * cdata () const noexcept
T * data () noexcept
const char * cdata_bytes () const noexcept
char * data_bytes () noexcept
T & front ()
const T & front () const
T & back ()
const T & back () const
std::streamsize size_bytes () const noexcept
std::streamsize byteSize () const
void checkStart (const label start) const
void checkSize (const label size) const
void checkRange (const label start, const label len) const
void checkIndex (const label i) const
bool uniform () const
label find (const T &val, label pos=0) const
label rfind (const T &val, label pos=-1) const
bool contains (const T &val, label pos=0) const
void moveFirst (const label i)
void moveLast (const label i)
void swapFirst (const label i)
void swapLast (const label i)
void shallowCopy (const UList< T > &list)
void deepCopy (const UList< T > &list)
template<class Addr >
void deepCopy (const IndirectListBase< T, Addr > &list)
SubList< T > slice (const label pos, label len=-1)
const SubList< T > slice (const label pos, label len=-1) const
SubList< T > slice (const labelRange &range)
const SubList< T > slice (const labelRange &range) const
T & operator[] (const label i)
const T & operator[] (const label i) const
operator const Foam::List< T > & () const
void operator= (const T &val)
void operator= (const Foam::zero)
iterator begin () noexcept
iterator end () noexcept
iterator begin (const label i) noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
const_iterator begin () const noexcept
const_iterator end () const noexcept
const_iterator cbegin (const label i) const noexcept
const_iterator begin (const label i) const noexcept
reverse_iterator rbegin ()
reverse_iterator rend ()
const_reverse_iterator crbegin () const
const_reverse_iterator crend () const
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
bool empty () const noexcept
label size () const noexcept
void swap (UList< T > &list)
bool operator== (const UList< T > &a) const
bool operator!= (const UList< T > &a) const
bool operator< (const UList< T > &list) const
bool operator> (const UList< T > &a) const
bool operator<= (const UList< T > &a) const
bool operator>= (const UList< T > &a) const
Istream & readList (Istream &is)
void writeEntry (const word &keyword, Ostream &os) const
Ostream & writeList (Ostream &os, const label shortLen=0) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type test (const label i) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type get (const label i) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type unset (const label i)
T & first ()
const T & first () const
T & last ()
const T & last () const
bool found (const T &val, label pos=0) const
Istream & readList (Istream &is)
Ostream & writeList (Ostream &os, const label) const
const bool & operator[] (const label i) const
UPstream::commsStruct & operator[] (const label procID)
const UPstream::commsStruct & operator[] (const label procID) const
Foam::UPstream::commsStruct & operator[] (const label procID)
const Foam::UPstream::commsStruct & operator[] (const label procID) const
Ostream & writeList (Ostream &os, const label) const
Istream & readList (Istream &is)
Static Public Member Functions
static const List< T > & null ()
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
static constexpr label max_size () noexcept
Friends
Istream & operator>> (Istream &is, List< T > &list)
Additional Inherited Members
Protected Member Functions inherited from UList< T >
void setAddressableSize (const label n) noexcept
void size (const label n)
void writeEntry (Ostream &os) const
labelRange validateRange (const labelRange &requestedRange) const
UList< T > & operator= (const UList< T > &)=delete
void writeEntry (Ostream &os) const
void writeEntry (Ostream &os) const
Detailed Description
template<class T>
class Foam::List< T >
A 1D array of objects of type <T>, where the size of the vector is known and used for subscript bounds checking, etc.
Storage is allocated on free-store during construction.
Source files
List.H
List.C
ListI.H
ListIO.C
Definition at line 70 of file List.H.
Member Typedef Documentation
subList
template<class T > typedef SubList<T> subList
Definition at line 107 of file List.H.
Constructor & Destructor Documentation
List() [1/21]
template<class T > constexpr List () inline constexpr noexcept
Definition at line 88 of file ListI.H.
List() [2/21]
template<class T > List (const label len) explicit
Definition at line 103 of file List.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
List() [3/21]
template<class T > List (const label len, const T & val)
Definition at line 119 of file List.C.
List() [4/21]
template<class T > List (const label len, const Foam::zero)
Definition at line 144 of file List.C.
List() [5/21]
template<class T > List (const Foam::one , const T & val)
Definition at line 169 of file List.C.
List() [6/21]
template<class T > List (const Foam::one , T && val)
Definition at line 178 of file List.C.
List() [7/21]
template<class T > List (const Foam::one , const Foam::zero)
Definition at line 187 of file List.C.
List() [8/21]
template<class T > List (const List< T > & a)
Definition at line 229 of file List.C.
References List_ACCESS, List_CONST_ACCESS, and T.
List() [9/21]
template<class T > List (const UList< T > & a) explicit
Definition at line 196 of file List.C.
List() [10/21]
template<class T > List (List< T > & a, bool reuse)
Definition at line 262 of file List.C.
List() [11/21]
template<class T > List (const UList< T > & list, const labelUList< T > & indices)
Definition at line 304 of file List.C.
List() [12/21]
template<class T > template<unsigned N> List (const UList< T > & list, const FixedList< label, N > & indices)
Definition at line 326 of file List.C.
References List_ACCESS, N(), and T.
List() [13/21]
template<class T > template<unsigned N> List (const FixedList< T, N > & list) explicit
Definition at line 349 of file List.C.
List() [14/21]
template<class T > List (const PtrList< T > & list) explicit
Definition at line 359 of file List.C.
List() [15/21]
template<class T > List (const SLList< T > & list) explicit
Definition at line 369 of file List.C.
List() [16/21]
template<class T > template<class Addr > List (const IndirectListBase< T, Addr > & list) explicit
Definition at line 377 of file List.C.
List() [17/21]
template<class T > List (std::initializer_list< T > list)
Definition at line 387 of file List.C.
List() [18/21]
template<class T > List (List< T > && list)
Definition at line 394 of file List.C.
References List< T >::transfer().
List() [19/21]
template<class T > template<int SizeMin> List (DynamicList< T, SizeMin > && list)
Definition at line 405 of file List.C.
References List< T >::transfer().
List() [20/21]
template<class T > List (SLList< T > && list)
Definition at line 414 of file List.C.
References List< T >::operator=().
List() [21/21]
template<class T > List (Istream & is)
Definition at line 31 of file ListIO.C.
References List< T >::readList().
~List()
template<class T > ~List ()
Definition at line 425 of file List.C.
Member Function Documentation
null()
template<class T > const Foam::List< T > & null () inline static
Definition at line 102 of file ListI.H.
Referenced by inverseDistance::createStencil(), and mapDistributeBase::whichSchedule().
clone()
template<class T > Foam::autoPtr< Foam::List< T > > clone () const inline
Definition at line 93 of file ListI.H.
References Foam::New().
clear()
template<class T > void clear () inline
Definition at line 109 of file ListI.H.
Referenced by polyMeshAdder::add(), coupledFaPatch::calcTransformTensors(), coupledFaPatch::calcTransformTensors(), ensightPart::clear(), SortableList< T >::clear(), meshedSurfRef::clear(), DynamicList< T, SizeMin >::clearStorage(), IListStreamAllocator::clearStorage(), DynamicField< T, SizeMin >::clearStorage(), polySurface::copySurface(), surfMesh::copySurface(), Foam::duplicateOrder(), isoSurfaceTopo::isoSurfaceTopo(), Cloud< ParticleType >::move(), meshedSurfRef::movePoints(), argList::parse(), Foam::parseStream(), ParticleZoneInfo< CloudType >::postEvolve(), contactHeatFluxSource::read(), externalFileSource::read(), VTKsurfaceFormat< Face >::read(), surfMesh::removeZones(), particleTracksSampler::reset(), meshedSurfRef::reset(), meshedSurfRef::resetPoints(), PtrListDetail< T >::resize(), cyclicAMIPolyPatch::restoreScaledGeometry(), faceSetOption::setSelection(), cellSetOption::setSelection(), MeshedSurface< Face >::stitchFaces(), PatchTools::subsetMap(), and cuttingSurfaceBase::walkCellCuts().
resize() [1/3]
template<class T > void resize (const label len) inline
Definition at line 132 of file ListI.H.
Referenced by object::addData(), pairGAMGAgglomeration::agglomerate(), argList::argList(), Field< T >::assign(), atmNutSource::atmNutSource(), atmPlantCanopyTSource::atmPlantCanopyTSource(), atmPlantCanopyTurbSource::atmPlantCanopyTurbSource(), atmPlantCanopyUSource::atmPlantCanopyUSource(), searchableDisk::boundingSpheres(), searchablePlane::boundingSpheres(), searchablePlate::boundingSpheres(), searchableSphere::boundingSpheres(), boxToCell::boxToCell(), boxToFace::boxToFace(), boxToPoint::boxToPoint(), coupledFaPatch::calcTransformTensors(), cellToCell::cellToCell(), cellToFace::cellToFace(), cellToFaceZone::cellToFaceZone(), cellToPoint::cellToPoint(), topoSetSource::check(), collector::collector(), multiWorldConnections::comms(), contactHeatFluxSource::contactHeatFluxSource(), directions::directions(), Foam::duplicateOrder(), Foam::etcDirs(), externalFileSource::externalFileSource(), externalHeatFluxSource::externalHeatFluxSource(), externalWallHeatFluxTemperatureFvPatchScalarField::externalWallHeatFluxTemperatureFvPatchScalarField(), externalWallHeatFluxTemperatureFvPatchScalarField::externalWallHeatFluxTemperatureFvPatchScalarField(), faceToCell::faceToCell(), faceToFace::faceToFace(), faceToPoint::faceToPoint(), faceZone::faceZone(), faceZone::faceZone(), faceZoneToCell::faceZoneToCell(), fanMomentumSource::fanMomentumSource(), patchProbes::findElements(), fixedTemperatureConstraint::fixedTemperatureConstraint(), fvMeshSubsetProxy::fvMeshSubsetProxy(), searchableSphere::getNormal(), searchableDisk::getNormal(), searchableDisk::getRegion(), searchableSphere::getRegion(), GlobalIOList< Type >::GlobalIOList(), heatExchangerSource::heatExchangerSource(), holeToFace::holeToFace(), if(), fluxSummary::initialiseFaceZone(), fluxSummary::initialiseFaceZoneAndDirection(), interRegionExplicitPorositySource::interRegionExplicitPorositySource(), IOList< label >::IOList(), isoSurfaceTopo::isoSurfaceTopo(), jouleHeatingSource::jouleHeatingSource(), lagrangianFieldDecomposer::lagrangianFieldDecomposer(), lumpedPointState::lumpedPointState(), Field< T >::map(), mapDistributeBase::mapDistributeBase(), scalars::matching(), scalars::matching(), wordRes::matching(), multiphaseStabilizedTurbulence::multiphaseStabilizedTurbulence(), multiSolidBodyMotionSolver::multiSolidBodyMotionSolver(), Foam::nonProcessorPatchNames(), polynomialFunction::operator+=(), polynomialFunction::operator-=(), argList::parse(), scalarRanges::parse(), Foam::parseStream(), patchCellsSource::patchCellsSource(), patchToCell::patchToCell(), patchToFace::patchToFace(), PhaseLimitStabilization< Type >::PhaseLimitStabilization(), pointToCell::pointToCell(), pointToFace::pointToFace(), pointToPoint::pointToPoint(), polyDegree1::polyDegree1(), KinematicReynoldsNumber< CloudType >::postEvolve(), ThermoReynoldsNumber< CloudType >::postEvolve(), faFieldDecomposer::processorAreaPatchFieldDecomposer::processorAreaPatchFieldDecomposer(), faFieldDecomposer::processorEdgePatchFieldDecomposer::processorEdgePatchFieldDecomposer(), fvFieldDecomposer::processorSurfacePatchFieldDecomposer::processorSurfacePatchFieldDecomposer(), projectCurveEdge::projectCurveEdge(), projectEdge::projectEdge(), radiation::radiation(), pointNoise::read(), surfaceNoise::read(), masterUncollatedFileOperation::readHeader(), faMeshBoundaryHalo::reset(), PtrListDetail< T >::resize(), PDRblock::gridControl::resize(), sampledCuttingPlane::sampledCuttingPlane(), sampledCuttingSurface::sampledCuttingSurface(), sampledInterface::sampledInterface(), sampledIsoSurface::sampledIsoSurface(), sampledPlane::sampledPlane(), List< T >::set(), Foam::BitOps::set(), Foam::BitOps::set(), faBoundaryMesh::setGroup(), polyBoundaryMesh::setGroup(), ZoneMesh< ZoneType, MeshType >::setGroup(), faceSetOption::setSelection(), cellSetOption::setSelection(), List< T >::setSize(), List< T >::setSize(), DynamicList< T, SizeMin >::shrinkStorage(), DynamicField< T, SizeMin >::shrinkStorage(), solidificationMeltingSource::solidificationMeltingSource(), fileOperation::sortTimes(), surfZoneIOList::surfZoneIOList(), masterUncollatedFileOperation::sync(), tabulatedAccelerationSource::tabulatedAccelerationSource(), topoBoolSet::topoBoolSet(), topoBoolSet::topoBoolSet(), topoBoolSet::topoBoolSet(), hashedWordList::uniq(), Foam::uniqueOrder(), viscousDissipation::viscousDissipation(), CompactIOList< face, label >::writeObject(), lumpedPointMovement::writeStateVTP(), zeroATCcells::zeroATCcells(), adjointkOmegaSST::zeroFirstCell(), zoneToCell::zoneToCell(), zoneToFace::zoneToFace(), and zoneToPoint::zoneToPoint().
resize() [2/3]
template<class T > void resize (const label len, const T & val)
Definition at line 437 of file List.C.
References List_ACCESS, and T.
resize_nocopy()
template<class T > void resize_nocopy (const label len) inline
Definition at line 139 of file ListI.H.
Referenced by fvPatchField< Type >::autoMap(), distributedDILUPreconditioner::calcReciprocalD(), processorColour::cellColour(), commSchedule::commSchedule(), distributedDILUPreconditioner::distributedDILUPreconditioner(), patchProbes::findElements(), fvMesh::mapFields(), PDRblock::location::reset(), option::resetApplied(), particleTracksSampler::resetCloud(), Foam::sortedOrder(), and Foam::sortedOrder().
setSize() [1/2]
template<class T > void setSize (const label n) inline
Definition at line 214 of file List.H.
References List< T >::resize().
Referenced by polyMeshAdder::add(), polyMeshAdder::add(), fvMeshPrimitiveLduAddressing::addAddressing(), adjointkOmegaSST::adjointkOmegaSST(), adjointSolverManager::adjointSolverManager(), adjointSpalartAllmaras::adjointSpalartAllmaras(), AMIInterpolation::agglomerate(), Bezier::Bezier(), bladeModel::bladeModel(), booleanSurface::booleanSurface(), booleanSurface::booleanSurface(), searchableBox::boundingSpheres(), searchableCone::boundingSpheres(), searchableCylinder::boundingSpheres(), searchableSurfaceCollection::boundingSpheres(), nearWallFields::calcAddressing(), coupledPolyPatch::calcTransformTensors(), extractEulerianParticles::checkFaceZone(), GAMGAgglomeration::compactLevels(), axisAligned::computeControlPoints(), transformBox::computeControlPoints(), sensitivitySurface::computeDerivativesSize(), optimisationType::computeMeritFunction(), NURBS3DVolume::computeParametricCoordinates(), ConeInjection< CloudType >::ConeInjection(), cyclicPolyPatch::coupledEdges(), cyclicPolyPatch::coupledPoints(), epsilonWallFunctionFvPatchScalarField::createAveragingWeights(), omegaWallFunctionFvPatchScalarField::createAveragingWeights(), geomCellLooper::cut(), hexCellLooper::cut(), cyclicAMIPolyPatch::cyclicAMIPolyPatch(), DAC< CompType, ThermoType >::DAC(), dimensionSets::dimensionSets(), fvMeshDistribute::distribute(), distributedDILUPreconditioner::distributedDILUPreconditioner(), snappySnapDriver::doSnap(), electrostaticDepositionFvPatchScalarField::electrostaticDepositionFvPatchScalarField(), energyTransport::energyTransport(), extendedEdgeMesh::extendedEdgeMesh(), extendedFeatureEdgeMesh::extendedFeatureEdgeMesh(), extendedUpwindCellToFaceStencil::extendedUpwindCellToFaceStencil(), FaceInteraction< CloudType >::FaceInteraction(), FacePostProcessing< CloudType >::FacePostProcessing(), faceTriangulation::faceTriangulation(), faceTriangulation::faceTriangulation(), FieldActivatedInjection< CloudType >::FieldActivatedInjection(), searchableSurfacesQueries::findAnyIntersection(), refinementSurfaces::findHigherIntersection(), distributedTriSurfaceMesh::findLineAll(), NURBS3DVolume::findPointsInBox(), FreeStream< CloudType >::FreeStream(), GAMGAgglomeration::GAMGAgglomeration(), surfaceZonesInfo::getAllClosedNamedSurfaces(), surfaceZonesInfo::getClosedNamedSurfaces(), surfaceZonesInfo::getInsidePointNamedSurfaces(), searchableBox::getNormal(), searchableCone::getNormal(), searchableCylinder::getNormal(), searchableExtrudedCircle::getNormal(), searchablePlate::getNormal(), searchableSurfaceCollection::getNormal(), triSurfaceMesh::getNormal(), distributedTriSurfaceMesh::getNormal(), searchableBox::getRegion(), searchableCone::getRegion(), searchableCylinder::getRegion(), searchableExtrudedCircle::getRegion(), searchablePlane::getRegion(), searchablePlate::getRegion(), searchableRotatedBox::getRegion(), searchableSurfaceCollection::getRegion(), triSurfaceMesh::getRegion(), distributedTriSurfaceMesh::getRegion(), cellCellStencil::globalCellCells(), GAMGProcAgglomeration::globalCellCells(), lduPrimitiveMesh::globalCellCells(), triSurfaceTools::greenRefine(), indexedOctree< Type >::indexedOctree(), viewFactor::initialise(), surfaceNoise::initialise(), objectivePtLosses::initialize(), objectiveUniformityPatch::initialize(), InjectedParticleInjection< CloudType >::InjectedParticleInjection(), linearInterpolationWeights::integrationWeights(), interpolationLookUpTable< scalar >::interpolationLookUpTable(), intersectedSurface::intersectedSurface(), isoSurfaceCell::isoSurfaceCell(), isoSurfacePoint::isoSurfacePoint(), lduPrimitiveMesh::lduPrimitiveMesh(), limitVelocity::limitVelocity(), LocalInteraction< CloudType >::LocalInteraction(), lookupProfile::lookupProfile(), LUscalarMatrix::LUscalarMatrix(), highAspectRatioFvGeometryScheme::makeAverageCentres(), voxelMeshSearch::makeMesh(), averageNeighbourFvGeometryScheme::makeNonOrthoWeights(), mappedPolyPatch::mapCollocatedFaces(), mappedWallPolyPatch::mapCollocatedFaces(), cyclicPolyPatch::mapCollocatedFaces(), mapDistribute::mapDistribute(), mapDistribute::mapDistribute(), mapDistributeBase::mapDistributeBase(), faMesh::mapOldAreas(), triSurface::markZones(), PatchTools::markZones(), globalMeshData::mergePoints(), extendedEdgeMesh::mergePointsAndSort(), fileOperation::mergeTimes(), multiBandZoneAbsorptionEmission::multiBandZoneAbsorptionEmission(), objectiveFlowRatePartition::objectiveFlowRatePartition(), optMeshMovementVolumetricBSplines::optMeshMovementVolumetricBSplines(), cyclicAMIPolyPatch::order(), cyclicPolyPatch::order(), oldCyclicPolyPatch::order(), processorPolyPatch::order(), outletMappedUniformInletFvPatchField< Type >::outletMappedUniformInletFvPatchField(), ParticleCollector< CloudType >::ParticleCollector(), patchInjection::patchInjection(), phasePropertiesList::phasePropertiesList(), pointFieldReconstructor::pointFieldReconstructor(), pointMVCWeight::pointMVCWeight(), Foam::polyMeshZipUpCells(), powerLawLopesdaCostaZone::powerLawLopesdaCostaZone(), snappySnapDriver::preSmoothPatch(), projectVertex::projectVertex(), pureZoneMixture< ThermoType >::pureZoneMixture(), reactionsSensitivityAnalysis< chemistryType >::reactionsSensitivityAnalysis(), STARCDMeshReader::readBoundary(), STARCDMeshReader::readCells(), FIREMeshReader::readFaces(), ReactingHeterogeneousParcel< ParcelType >::readFields(), ReactingMultiphaseParcel< ParcelType >::readFields(), ReactingParcel< ParcelType >::readFields(), RecycleInteraction< CloudType >::RecycleInteraction(), DAC< CompType, ThermoType >::reduceMechanism(), DRGEP< CompType, ThermoType >::reduceMechanism(), EFA< CompType, ThermoType >::reduceMechanism(), PFA< CompType, ThermoType >::reduceMechanism(), refinementHistory::refinementHistory(), refinementHistory::refinementHistory(), refinementHistory::refinementHistory(), refinementParameters::refinementParameters(), refinementSurfaces::refinementSurfaces(), RemoveParcels< CloudType >::RemoveParcels(), fvMeshSubset::reset(), searchableSurfaceCollection::searchableSurfaceCollection(), searchableSurfaces::searchableSurfaces(), extendedEdgeMesh::select(), removePoints::setRefinement(), tetDecomposer::setRefinement(), addPatchCellLayer::setRefinement(), hexRef8::setRefinement(), duplicatePoints::setRefinement(), boundaryCutter::setRefinement(), propellerInfo::setSampleDiskGeometry(), SortableListDRGEP< Type >::setSize(), SortableListEFA< Type >::setSize(), removePoints::setUnrefinement(), shellSurfaces::shellSurfaces(), snappyVoxelMeshDriver::snappyVoxelMeshDriver(), StandardWallInteraction< CloudType >::StandardWallInteraction(), cellVolumeWeight::stencilWeights(), inverseDistance::stencilWeights(), leastSquares::stencilWeights(), surfaceZonesInfo::surfaceZonesInfo(), trackingInverseDistance::trackingInverseDistance(), triSurfaceTools::triangulate(), lduPrimitiveMeshAssembly::update(), oversetFvMeshBase::updateAddressing(), optimisationType::updateGradientsAndValues(), linearInterpolationWeights::valueWeights(), splineInterpolationWeights::valueWeights(), volBSplinesBase::volBSplinesBase(), WallLocalSpringSliderDashpot< CloudType >::WallLocalSpringSliderDashpot(), waveMakerPointPatchVectorField::waveMakerPointPatchVectorField(), and adjointkOmegaSST::zeroFirstCell().
setSize() [2/2]
template<class T > void setSize (const label n, const T & val) inline
Definition at line 217 of file List.H.
References List< T >::resize().
transfer() [1/2]
template<class T > void transfer (List< T > & list)
Definition at line 452 of file List.C.
References clear().
Referenced by AABBTree< Type >::AABBTree(), faceAreaWeightAMI::calcAddressing(), polyDualMesh::calcFeatures(), cellVolumeWeightMethod::calculateAddressing(), directMethod::calculateAddressing(), mapNearestMethod::calculateAddressing(), correctedCellVolumeWeightMethod::calculateAddressing(), calculatedProcessorGAMGInterface::calculatedProcessorGAMGInterface(), CompactIOList< T, BaseType >::CompactIOList(), triSurface::compactPoints(), geomCellLooper::cut(), extendedEdgeMesh::cut(), topoCellLooper::cut(), cyclicACMIGAMGInterface::cyclicACMIGAMGInterface(), cyclicAMIGAMGInterface::cyclicAMIGAMGInterface(), cyclicGAMGInterface::cyclicGAMGInterface(), fvMeshDistribute::distribute(), edgeSurface::edgeSurface(), extendedEdgeMesh::extendedEdgeMesh(), extendedUpwindCellToFaceStencil::extendedUpwindCellToFaceStencil(), extendedUpwindCellToFaceStencil::extendedUpwindCellToFaceStencil(), FaceInteraction< CloudType >::FaceInteraction(), FacePostProcessing< CloudType >::FacePostProcessing(), Field< Type >::Field(), Field< Type >::Field(), Field< Type >::Field(), pointNoise::filterTimeData(), for(), FreeStream< CloudType >::FreeStream(), PatchTools::gatherAndMerge(), GlobalIOList< Type >::GlobalIOList(), indexedOctree< Type >::indexedOctree(), viewFactor::initialise(), objectivePtLosses::initialize(), objectiveUniformityPatch::initialize(), isoSurfaceCell::isoSurfaceCell(), isoSurfacePoint::isoSurfacePoint(), isoSurfaceTopo::isoSurfaceTopo(), List< T >::List(), List< T >::List(), voxelMeshSearch::makeMesh(), polyBoundaryMesh::matchGroups(), fileOperation::mergeTimes(), meshedSurfRef::movePoints(), properties::objectResultEntries(), Field< Type >::operator=(), Field< Type >::operator=(), IjkField< Type >::operator=(), SortableList< T >::operator=(), Field< Type >::operator=(), PtrListDetail< T >::operator=(), oversetGAMGInterface::oversetGAMGInterface(), SortableList< T >::partialReverseSort(), SortableList< T >::partialSort(), patchInteractionDataList::patchInteractionDataList(), processorGAMGInterface::processorGAMGInterface(), ReactingHeterogeneousParcel< ParcelType >::ReactingHeterogeneousParcel(), ReactingMultiphaseParcel< ParcelType >::ReactingMultiphaseParcel(), ReactingParcel< ParcelType >::ReactingParcel(), streamLineParticle::readFields(), wallBoundedStreamLineParticle::readFields(), RemoveParcels< CloudType >::RemoveParcels(), SortableList< T >::reverseSort(), hexRef8::setRefinement(), SortableList< T >::sort(), SortableListDRGEP< Type >::sort(), SortableListEFA< Type >::sort(), SortableListDRGEP< Type >::stableSort(), SortableListEFA< Type >::stableSort(), surfaceIntersection::surfaceIntersection(), surfaceIntersection::surfaceIntersection(), surfaceIntersection::surfaceIntersection(), DynamicList< T, SizeMin >::transfer(), DynamicList< T, SizeMin >::transfer(), uniformInterpolatedDisplacementPointPatchVectorField::updateCoeffs(), topoBoolSet::updateLabels(), hexRef8Data::updateMesh(), cuttingSurfaceBase::walkCellCuts(), and cellCellStencil::walkFront().
transfer() [2/2]
template<class T > template<int SizeMin> void transfer (DynamicList< T, SizeMin > & list)
Definition at line 471 of file List.C.
newElmt()
template<class T > T & newElmt (const label i) inline
Definition at line 146 of file ListI.H.
References n, UList< T >::operator[](), and resize().
Referenced by Foam::parseStream().
emplace_back()
template<class T > template<class... Args> T & emplace_back (Args &&... args) inline
Definition at line 169 of file ListI.H.
References args, resize(), and T.
push_back() [1/4]
template<class T > void push_back (const T & val) inline
Definition at line 185 of file ListI.H.
Referenced by List< T >::append(), List< T >::append(), List< T >::append(), and List< T >::append().
push_back() [2/4]
template<class T > void push_back (T && val) inline
Definition at line 195 of file ListI.H.
push_back() [3/4]
template<class T > void push_back (const UList< T > & list) inline
Definition at line 205 of file ListI.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
push_back() [4/4]
template<class T > template<class Addr > void push_back (const IndirectListBase< T, Addr > & list) inline
Definition at line 227 of file ListI.H.
References n, resize(), and UPtrList< T >::size().
push_uniq()
template<class T > Foam::label push_uniq (const T & val) inline
Definition at line 242 of file ListI.H.
Referenced by List< T >::appendUniq().
pop_back()
template<class T > void pop_back (label n = 1) inline
Definition at line 257 of file ListI.H.
operator=() [1/11]
template<class T > void operator= (const UList< T > & a)
Definition at line 485 of file List.C.
References List_ACCESS, List_CONST_ACCESS, and T.
Referenced by Field< T >::Field(), GlobalIOList< kinematicParcelInjectionData >::GlobalIOList(), IOList< label >::IOList(), List< T >::List(), CompactIOList< face, label >::operator=(), CompactIOList< T, BaseType >::operator=(), Field< Type >::operator=(), Field< Type >::operator=(), GlobalIOList< Type >::operator=(), Field< Type >::operator=(), IOList< T >::operator=(), SortableList< T >::operator=(), SortableListDRGEP< Type >::operator=(), SortableListEFA< Type >::operator=(), Field< Type >::operator=(), Field< Type >::operator=(), Field< Type >::operator=(), SortableList< T >::operator=(), SortableList< T >::operator=(), and PtrListDetail< CloudFunctionObject< CloudType > >::resize().
operator=() [2/11]
template<class T > void operator= (const List< T > & list)
Definition at line 521 of file List.C.
operator=() [3/11]
template<class T > void operator= (const SLList< T > & list)
Definition at line 533 of file List.C.
References UPtrList< T >::size(), and T.
operator=() [4/11]
template<class T > template<class Addr > void operator= (const IndirectListBase< T, Addr > & list)
Definition at line 570 of file List.C.
References List_ACCESS, UPtrList< T >::size(), and T.
operator=() [5/11]
template<class T > template<unsigned N> void operator= (const FixedList< T, N > & list)
Definition at line 554 of file List.C.
References N(), and T.
operator=() [6/11]
template<class T > void operator= (std::initializer_list< T > list)
Definition at line 589 of file List.C.
References UPtrList< T >::size(), and T.
operator=() [7/11]
template<class T > void operator= (const T & val) inline
Definition at line 273 of file ListI.H.
References UList< T >::operator=().
operator=() [8/11]
template<class T > void operator= (const Foam::zero) inline
Definition at line 280 of file ListI.H.
References UList< T >::operator=(), and Foam::Zero.
operator=() [9/11]
template<class T > void operator= (List< T > && list)
Definition at line 609 of file List.C.
operator=() [10/11]
template<class T > template<int SizeMin> void operator= (DynamicList< T, SizeMin > && list)
Definition at line 622 of file List.C.
operator=() [11/11]
template<class T > void operator= (SLList< T > && list)
Definition at line 629 of file List.C.
References UPtrList< T >::size(), and T.
readList() [1/3]
template<class T > Foam::Istream & readList (Istream & is)
Definition at line 42 of file ListIO.C.
References token::BEGIN_LIST, IOstreamOption::BINARY, PtrList< T >::clear(), Foam::dynamicCast(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, FUNCTION_NAME, Foam::nl, PtrList< T >::resize(), T, and PtrList< T >::transfer().
Referenced by List< T >::List().
shallowCopy()
template<class T > void shallowCopy (const UList< T > &) delete
Referenced by ODESolver::resizeField().
set()
template<class T > template<class TypeT = T> std::enable_if< std::is_same< bool, TypeT >::value, bool >::type set (const label i, bool val = true) inline
Definition at line 338 of file List.H.
References List< T >::resize(), and UList< T >::size().
Referenced by pointSet::distribute(), cellSet::distribute(), faceSet::distribute(), phaseSystem::fillFields(), forAll(), forAll(), ABAQUSCore::readHelper::purge_solids(), mapDistributeBase::send(), Foam::BitOps::set(), fvMatrix< Type >::setBounAndInterCoeffs(), faceSet::sync(), pointSet::sync(), and while().
append() [1/4]
template<class T > void append (const T & val) inline
Definition at line 363 of file List.H.
References List< T >::push_back().
Referenced by PDRblock::gridControl::append(), Foam::appendNamedEntry(), distributedDILUPreconditioner::distributedDILUPreconditioner(), faceCells::faceCells(), Foam::findEtcEntries(), for(), MRFZoneList::getFromName(), fluxSummary::initialiseCellZoneAndDirection(), fluxSummary::initialiseFaceZone(), fluxSummary::initialiseFaceZoneAndDirection(), fluxSummary::initialiseSurface(), fluxSummary::initialiseSurfaceAndDirection(), ParticlePostProcessing< CloudType >::postFace(), ParticlePostProcessing< CloudType >::postPatch(), refinementParameters::refinementParameters(), timeSelector::select0(), and uniformInterpolatedDisplacementPointPatchVectorField::updateCoeffs().
append() [2/4]
template<class T > void append (T && val) inline
Definition at line 368 of file List.H.
References List< T >::push_back().
append() [3/4]
template<class T > void append (const UList< T > & list) inline
Definition at line 373 of file List.H.
References List< T >::push_back().
append() [4/4]
template<class T > template<class Addr > void append (const IndirectListBase< T, Addr > & list) inline
Definition at line 379 of file List.H.
References List< T >::push_back().
appendUniq()
template<class T > label appendUniq (const T & val) inline
Definition at line 386 of file List.H.
References List< T >::push_uniq().
readList() [2/3]
Istream & readList (Istream & is)
resize() [3/3]
void resize (const label newLen) inline
Definition at line 124 of file ListI.H.
References PtrList< T >::resize().
readList() [3/3]
Istream & readList (Istream & is)
Definition at line 42 of file charList.C.
References IOstreamOption::BINARY, PtrList< T >::clear(), Foam::dynamicCast(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, FUNCTION_NAME, Foam::nl, PtrList< T >::PtrList(), PtrList< T >::resize(), and PtrList< T >::transfer().
Friends And Related Symbol Documentation
operator>>
template<class T > Istream & operator>> (Istream & is, List< T > & list) friend
Definition at line 412 of file List.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/Bits/BitOps/BitOps.H
src/OpenFOAM/containers/Lists/List/List.H
src/OpenFOAM/containers/Lists/List/List.C
src/OpenFOAM/containers/Lists/List/ListI.H
src/OpenFOAM/containers/Lists/List/ListIO.C