OpenFOAM: polyMeshTools Class Reference
polyMeshTools Class Reference
Collection of static functions operating on polyMesh (mainly checks) so that need access to patch information.
#include <polyMeshTools.H>
Static Public Member Functions
static tmp< scalarField > faceOrthogonality (const polyMesh &mesh, const vectorField &fAreas, const vectorField &cellCtrs)
static tmp< scalarField > faceSkewness (const polyMesh &mesh, const pointField &points, const vectorField &fCtrs, const vectorField &fAreas, const vectorField &cellCtrs)
static tmp< scalarField > faceWeights (const polyMesh &mesh, const vectorField &fCtrs, const vectorField &fAreas, const vectorField &cellCtrs)
static tmp< scalarField > volRatio (const polyMesh &mesh, const scalarField &vol)
static polyMesh::readUpdateState combine (const polyMesh::readUpdateState &state0, const polyMesh::readUpdateState &state1)
Static Public Member Functions inherited from primitiveMeshTools
static void updateFaceCentresAndAreas (const primitiveMesh &mesh, const UList< label > &faceIDs, const pointField &p, vectorField &fCtrs, vectorField &fAreas)
static void updateCellCentresAndVols (const primitiveMesh &mesh, const vectorField &fCtrs, const vectorField &fAreas, const List< label > &cellIDs, const List< cell > &cells, vectorField &cellCtrs_s, scalarField &cellVols_s)
static void makeFaceCentresAndAreas (const UList< face > &faces, const pointField &p, vectorField &fCtrs, vectorField &fAreas)
static void makeFaceCentresAndAreas (const primitiveMesh &mesh, const pointField &p, vectorField &fCtrs, vectorField &fAreas)
static void makeCellCentresAndVols (const primitiveMesh &mesh, const vectorField &fCtrs, const vectorField &fAreas, vectorField &cellCtrs, scalarField &cellVols)
static tmp< scalarField > faceOrthogonality (const primitiveMesh &mesh, const vectorField &fAreas, const vectorField &cellCtrs)
static void facePyramidVolume (const primitiveMesh &mesh, const pointField &points, const vectorField &cellCtrs, scalarField &ownPyrVol, scalarField &neiPyrVol)
static tmp< scalarField > faceSkewness (const primitiveMesh &mesh, const pointField &points, const vectorField &fCtrs, const vectorField &fAreas, const vectorField &cellCtrs)
static void cellClosedness (const primitiveMesh &mesh, const Vector< label > &meshD, const vectorField &areas, const scalarField &vols, scalarField &openness, scalarField &aratio)
static tmp< scalarField > faceConcavity (const scalar maxSin, const primitiveMesh &mesh, const pointField &p, const vectorField &faceAreas)
static tmp< scalarField > faceFlatness (const primitiveMesh &mesh, const pointField &p, const vectorField &fCtrs, const vectorField &faceAreas)
static tmp< scalarField > edgeAlignment (const primitiveMesh &mesh, const Vector< label > &directions, const pointField &p)
static tmp< scalarField > cellDeterminant (const primitiveMesh &mesh, const Vector< label > &directions, const vectorField &faceAreas, const bitSet &internalOrCoupledFace)
static scalar faceSkewness (const UList< face > &faces, const pointField &p, const vectorField &fCtrs, const vectorField &fAreas, const label facei, const point &ownCc, const point &neiCc)
static scalar boundaryFaceSkewness (const UList< face > &faces, const pointField &p, const vectorField &fCtrs, const vectorField &fAreas, const label facei, const point &ownCc)
static scalar faceSkewness (const primitiveMesh &mesh, const pointField &p, const vectorField &fCtrs, const vectorField &fAreas, const label facei, const point &ownCc, const point &neiCc)
static scalar boundaryFaceSkewness (const primitiveMesh &mesh, const pointField &p, const vectorField &fCtrs, const vectorField &fAreas, const label facei, const point &ownCc)
static scalar faceOrthogonality (const point &ownCc, const point &neiCc, const vector &s)
Detailed Description
Collection of static functions operating on polyMesh (mainly checks) so that need access to patch information.
Source files
polyMeshTools.H
polyMeshTools.C
Definition at line 49 of file polyMeshTools.H.
Member Function Documentation
faceOrthogonality()
Foam::tmp< Foam::scalarField > faceOrthogonality (const polyMesh & mesh, const vectorField & fAreas, const vectorField & cellCtrs) static
Definition at line 29 of file polyMeshTools.C.
References primitiveMeshTools::faceOrthogonality(), forAll, mesh, tmp< T >::New(), pbm, pp(), and syncTools::swapBoundaryCellPositions().
Referenced by averageNeighbourFvGeometryScheme::makeNonOrthoWeights(), and averageNeighbourFvGeometryScheme::movePoints().
faceSkewness()
Foam::tmp< Foam::scalarField > faceSkewness (const polyMesh & mesh, const pointField & points, const vectorField & fCtrs, const vectorField & fAreas, const vectorField & cellCtrs) static
Definition at line 83 of file polyMeshTools.C.
References primitiveMeshTools::boundaryFaceSkewness(), polyMesh::boundaryMesh(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), polyMesh::faces(), primitiveMeshTools::faceSkewness(), forAll, mesh, tmp< T >::New(), primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), p, pbm, pp(), Foam::skew(), and syncTools::swapBoundaryCellPositions().
faceWeights()
Foam::tmp< Foam::scalarField > faceWeights (const polyMesh & mesh, const vectorField & fCtrs, const vectorField & fAreas, const vectorField & cellCtrs) static
Definition at line 168 of file polyMeshTools.C.
References polyMesh::boundaryMesh(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), forAll, Foam::mag(), mesh, Foam::min(), tmp< T >::New(), primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), pbm, pp(), and syncTools::swapBoundaryCellPositions().
volRatio()
Foam::tmp< Foam::scalarField > volRatio (const polyMesh & mesh, const scalarField & vol) static
Definition at line 225 of file polyMeshTools.C.
References polyMesh::boundaryMesh(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), forAll, Foam::max(), mesh, Foam::min(), tmp< T >::New(), primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), pbm, pp(), and syncTools::swapBoundaryCellList().
combine()
Foam::polyMesh::readUpdateState combine (const polyMesh::readUpdateState & state0, const polyMesh::readUpdateState & state1) static
Definition at line 274 of file polyMeshTools.C.
References polyMesh::POINTS_MOVED, polyMesh::TOPO_CHANGE, polyMesh::TOPO_PATCH_CHANGE, and polyMesh::UNCHANGED.
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/polyMeshCheck/polyMeshTools.H
src/OpenFOAM/meshes/polyMesh/polyMeshCheck/polyMeshTools.C