OpenFOAM: faFieldDecomposer Class Reference
faFieldDecomposer Class Reference
Finite Area area and edge field decomposer.
#include <faFieldDecomposer.H>
Classes
class fieldsCache
class patchFieldDecomposer
class processorAreaPatchFieldDecomposer
class processorEdgePatchFieldDecomposer
Public Member Functions
faFieldDecomposer (const Foam::zero, const faMesh &procMesh, const labelList &edgeAddressing, const labelList &faceAddressing, const labelList &boundaryAddressing)
faFieldDecomposer (const faMesh &completeMesh, const faMesh &procMesh, const labelList &edgeAddressing, const labelList &faceAddressing, const labelList &boundaryAddressing)
faFieldDecomposer (const label nTotalFaces, const List< labelRange > &boundaryRanges, const labelUList &edgeOwner, const labelUList &edgeNeigbour, const faMesh &procMesh, const labelList &edgeAddressing, const labelList &faceAddressing, const labelList &boundaryAddressing)
~faFieldDecomposer ()=default
bool empty () const
void clear ()
void reset (const faMesh &completeMesh)
void reset (const label nTotalFaces, const List< labelRange > &boundaryRanges, const labelUList &edgeOwner, const labelUList &edgeNeigbour)
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > decomposeField (const GeometricField< Type, faPatchField, areaMesh > &field) const
template<class Type >
tmp< GeometricField< Type, faePatchField, edgeMesh > > decomposeField (const GeometricField< Type, faePatchField, edgeMesh > &field) const
template<class GeoField >
void decomposeFields (const PtrList< GeoField > &fields) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::faPatchField, Foam::areaMesh > > decomposeField (const GeometricField< Type, faPatchField, areaMesh > &field) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::faePatchField, Foam::edgeMesh > > decomposeField (const GeometricField< Type, faePatchField, edgeMesh > &field) const
Static Public Member Functions
template<class Type , template< class > class PatchField, class GeoMesh >
static void readFields (const typename GeoMesh::Mesh &mesh, const IOobjectList &objects, PtrList< GeometricField< Type, PatchField, GeoMesh > > &fields, const bool readOldTime)
template<class Mesh , class GeoField >
static void readFields (const Mesh &mesh, const IOobjectList &objects, PtrList< GeoField > &fields)
Detailed Description
Finite Area area and edge field decomposer.
Author Zeljko Tukovic, FSB Zagreb Hrvoje Jasak, Wikki Ltd.
Source files
faFieldDecomposer.H
faFieldDecomposer.C
fvFieldDecomposerCache.C
faFieldDecomposerTemplates.C
Definition at line 59 of file faFieldDecomposer.H.
Constructor & Destructor Documentation
faFieldDecomposer() [1/3]
faFieldDecomposer (const Foam::zero , const faMesh & procMesh, const labelList & edgeAddressing, const labelList & faceAddressing, const labelList & boundaryAddressing)
Definition at line 155 of file faFieldDecomposer.C.
faFieldDecomposer() [2/3]
faFieldDecomposer (const faMesh & completeMesh, const faMesh & procMesh, const labelList & edgeAddressing, const labelList & faceAddressing, const labelList & boundaryAddressing)
Definition at line 175 of file faFieldDecomposer.C.
References faFieldDecomposer::reset().
faFieldDecomposer() [3/3]
faFieldDecomposer (const label nTotalFaces, const List< labelRange > & boundaryRanges, const labelUList & edgeOwner, const labelUList & edgeNeigbour, const faMesh & procMesh, const labelList & edgeAddressing, const labelList & faceAddressing, const labelList & boundaryAddressing)
Definition at line 197 of file faFieldDecomposer.C.
References faFieldDecomposer::reset().
~faFieldDecomposer()
~faFieldDecomposer () default
Member Function Documentation
empty()
bool empty () const
Definition at line 225 of file faFieldDecomposer.C.
References UPtrList< T >::empty().
clear()
void clear ()
Definition at line 231 of file faFieldDecomposer.C.
References PtrList< T >::clear().
reset() [1/2]
void reset (const faMesh & completeMesh)
Definition at line 301 of file faFieldDecomposer.C.
References clear(), forAll, PtrList< T >::resize(), and UPtrList< T >::size().
Referenced by faFieldDecomposer::faFieldDecomposer(), and faFieldDecomposer::faFieldDecomposer().
reset() [2/2]
void reset (const label nTotalFaces, const List< labelRange > & boundaryRanges, const labelUList & edgeOwner, const labelUList & edgeNeigbour)
Definition at line 239 of file faFieldDecomposer.C.
References clear(), forAll, PtrList< T >::resize(), and UPtrList< T >::size().
decomposeField() [1/4]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > decomposeField (const GeometricField< Type, faPatchField, areaMesh > & field) const
decomposeField() [2/4]
template<class Type > tmp< GeometricField< Type, faePatchField, edgeMesh > > decomposeField (const GeometricField< Type, faePatchField, edgeMesh > & field) const
decomposeFields()
template<class GeoField > void decomposeFields (const PtrList< GeoField > & fields) const
Definition at line 212 of file faFieldDecomposerTemplates.C.
References fields, forAll, and write().
Referenced by faFieldDecomposer::fieldsCache::privateCache::decompose().
readFields() [1/2]
template<class Type , template< class > class PatchField, class GeoMesh > static void readFields (const typename GeoMesh::Mesh & mesh, const IOobjectList & objects, PtrList< GeometricField< Type, PatchField, GeoMesh > > & fields, const bool readOldTime) static
readFields() [2/2]
template<class Mesh , class GeoField > static void readFields (const Mesh & mesh, const IOobjectList & objects, PtrList< GeoField > & fields) static
decomposeField() [3/4]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::faPatchField, Foam::areaMesh > > decomposeField (const GeometricField< Type, faPatchField, areaMesh > & field) const
Definition at line 32 of file faFieldDecomposerTemplates.C.
References field(), forAll, Foam::New(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, PtrList< T >::set(), and UPtrList< T >::size().
decomposeField() [4/4]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::faePatchField, Foam::edgeMesh > > decomposeField (const GeometricField< Type, faePatchField, edgeMesh > & field) const
Definition at line 102 of file faFieldDecomposerTemplates.C.
References field(), forAll, Foam::New(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, p, and PtrList< T >::set().
The documentation for this class was generated from the following files:
src/parallel/decompose/faDecompose/faFieldDecomposer.H
src/parallel/decompose/faDecompose/faFieldDecomposer.C
src/parallel/decompose/faDecompose/faFieldDecomposerTemplates.C