OpenFOAM: blackBodyEmission Class Reference
blackBodyEmission Class Reference
Class black body emission.
#include <blackBodyEmission.H>
Public Member Functions
blackBodyEmission (const label nLambda, const volScalarField &T)
~blackBodyEmission ()
const volScalarField & bLambda (const label lambdaI) const
dimensionedScalar EblambdaT (const dimensionedScalar &T, const scalar lambda) const
tmp< Foam::volScalarField > deltaLambdaT (const volScalarField &T, const Vector2D< scalar > &band) const
tmp< Foam::volScalarField > EbDeltaLambdaT (const volScalarField &T, const Vector2D< scalar > &band) const
void correct (const label lambdaI, const Vector2D< scalar > &band)
Static Public Attributes
static const List< Tuple2< scalar, scalar > > emissivePowerTable
Detailed Description
Class black body emission.
Table of black body emissive power from: Modest, "Radiative Heat Transfer", pp.775-777, 1993
Source files
blackBodyEmission.H
blackBodyEmission.C
Definition at line 54 of file blackBodyEmission.H.
Constructor & Destructor Documentation
blackBodyEmission()
blackBodyEmission (const label nLambda, const volScalarField & T)
Definition at line 133 of file blackBodyEmission.C.
References forAll, Foam::name(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, Foam::pow4(), PtrList< T >::set(), Foam::constant::physicoChemical::sigma, and T.
~blackBodyEmission()
~blackBodyEmission ()
Definition at line 175 of file blackBodyEmission.C.
Member Function Documentation
bLambda()
const volScalarField & bLambda (const label lambdaI) const inline
Definition at line 108 of file blackBodyEmission.H.
EblambdaT()
dimensionedScalar EblambdaT (const dimensionedScalar & T, const scalar lambda) const inline
Definition at line 114 of file blackBodyEmission.H.
References Foam::exp(), lambda(), Foam::pow5(), and T.
deltaLambdaT()
Foam::tmp< Foam::volScalarField > deltaLambdaT (const volScalarField & T, const Vector2D< scalar > & band) const
Definition at line 191 of file blackBodyEmission.C.
References Foam::dimless, forAll, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, and T.
EbDeltaLambdaT()
Foam::tmp< Foam::volScalarField > EbDeltaLambdaT (const volScalarField & T, const Vector2D< scalar > & band) const
Definition at line 229 of file blackBodyEmission.C.
References forAll, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, Foam::pow4(), Foam::constant::physicoChemical::sigma, and T.
correct()
void correct (const label lambdaI, const Vector2D< scalar > & band)
Definition at line 285 of file blackBodyEmission.C.
Member Data Documentation
emissivePowerTable
const Foam::List< Foam::Tuple2< Foam::scalar, Foam::scalar > > emissivePowerTable static
Definition at line 29 of file blackBodyEmission.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/radiation/radiationModels/fvDOM/blackBodyEmission/blackBodyEmission.H
src/thermophysicalModels/radiation/radiationModels/fvDOM/blackBodyEmission/blackBodyEmission.C