OpenFOAM: singleProcessorFaceSets Class Reference
singleProcessorFaceSets Class Reference
Constraint to keep all cells connected to face or point of faceSet on a single processor.
#include <singleProcessorFaceSetsConstraint.H>
Public Member Functions
TypeName ("singleProcessorFaceSets")
singleProcessorFaceSets (const dictionary &dict)
singleProcessorFaceSets (const List< Tuple2< word, label > > &setNameAndProcs)
singleProcessorFaceSets (Istream &is)
virtual ~singleProcessorFaceSets ()=default
virtual void add (const polyMesh &mesh, boolList &blockedFace, PtrList< labelList > &specifiedProcessorFaces, labelList &specifiedProcessor, List< labelPair > &explicitConnections) const
virtual void apply (const polyMesh &mesh, const boolList &blockedFace, const PtrList< labelList > &specifiedProcessorFaces, const labelList &specifiedProcessor, const List< labelPair > &explicitConnections, labelList &decomposition) const
Public Member Functions inherited from decompositionConstraint
TypeName ("decompositionConstraint")
declareRunTimeSelectionTable (autoPtr, decompositionConstraint, dictionary,(const dictionary &dict),(dict))
decompositionConstraint (const dictionary &constraintDict)
decompositionConstraint (const dictionary &constraintDict, const word &modelType)
virtual ~decompositionConstraint ()=default
Additional Inherited Members
Static Public Member Functions inherited from decompositionConstraint
static autoPtr< decompositionConstraint > New (const dictionary &constraintDict)
static autoPtr< decompositionConstraint > New (const dictionary &constraintDict, const word &modelType)
Protected Member Functions inherited from decompositionConstraint
void getMinBoundaryValue (const polyMesh &mesh, const labelList &decomposition, labelList &destProc) const
decompositionConstraint (const decompositionConstraint &)=delete
void operator= (const decompositionConstraint &)=delete
Protected Attributes inherited from decompositionConstraint
dictionary coeffDict_
Detailed Description
Constraint to keep all cells connected to face or point of faceSet on a single processor.
Dictionary parameters
Property Description Required Default
type singleProcessorFaceSets yes
sets List of sets and processers yes
Example,
    constraints
    {
        procs
        {
            type    singleProcessorFaceSets;
            sets
            (
                (faceSet1   0)
                (faceSet5   12)
                (faceSet25 510)
            );
        }
    }
Source files
singleProcessorFaceSetsConstraint.H
singleProcessorFaceSetsConstraint.C
Definition at line 90 of file singleProcessorFaceSetsConstraint.H.
Constructor & Destructor Documentation
singleProcessorFaceSets() [1/3]
singleProcessorFaceSets (const dictionary & dict) explicit
Definition at line 59 of file singleProcessorFaceSetsConstraint.C.
singleProcessorFaceSets() [2/3]
singleProcessorFaceSets (const List< Tuple2< word, label > > & setNameAndProcs) explicit
Definition at line 81 of file singleProcessorFaceSetsConstraint.C.
References Foam::endl(), Foam::Info, and Foam::type().
singleProcessorFaceSets() [3/3]
singleProcessorFaceSets (Istream & is) explicit
Definition at line 100 of file singleProcessorFaceSetsConstraint.C.
References Foam::endl(), Foam::Info, and Foam::type().
~singleProcessorFaceSets()
virtual ~singleProcessorFaceSets () virtual default
Member Function Documentation
TypeName()
TypeName ("singleProcessorFaceSets")
add()
void add (const polyMesh & mesh, boolList & blockedFace, PtrList< labelList > & specifiedProcessorFaces, labelList & specifiedProcessor, List< labelPair > & explicitConnections) const virtual
Implements decompositionConstraint.
Definition at line 121 of file singleProcessorFaceSetsConstraint.C.
References PtrList< T >::append(), Foam::endl(), f(), faceLabels(), forAll, Foam::Info, mesh, pFaces, PtrList< T >::resize(), Foam::returnReduce(), Foam::returnReduceOr(), UPtrList< T >::size(), syncTools::syncFaceList(), syncTools::syncPointList(), Foam::type(), WarningInFunction, and Foam::Zero.
apply()
void apply (const polyMesh & mesh, const boolList & blockedFace, const PtrList< labelList > & specifiedProcessorFaces, const labelList & specifiedProcessor, const List< labelPair > & explicitConnections, labelList & decomposition) const virtual
Reimplemented from decompositionConstraint.
Definition at line 253 of file singleProcessorFaceSetsConstraint.C.
References Foam::endl(), f(), forAll, Foam::Info, mesh, pFaces, Foam::reduce(), Foam::returnReduce(), UPtrList< T >::size(), syncTools::syncPointList(), and Foam::type().
The documentation for this class was generated from the following files:
src/parallel/decompose/decompositionMethods/decompositionConstraints/singleProcessorFaceSets/singleProcessorFaceSetsConstraint.H
src/parallel/decompose/decompositionMethods/decompositionConstraints/singleProcessorFaceSets/singleProcessorFaceSetsConstraint.C