OpenFOAM: lineDivide Class Reference
lineDivide Class Reference
Divides a line into segments.
#include <lineDivide.H>
Public Member Functions
lineDivide (const blockEdge &cedge, const label nDiv, const gradingDescriptors &gd=gradingDescriptors())
const pointField & points () const noexcept
const scalarList & lambdaDivisions () const noexcept
Detailed Description
Divides a line into segments.
Source files
lineDivide.H
lineDivide.C
Definition at line 52 of file lineDivide.H.
Constructor & Destructor Documentation
lineDivide()
lineDivide (const blockEdge & cedge, const label nDiv, const gradingDescriptors & gd = gradingDescriptors())
Definition at line 39 of file lineDivide.C.
References Foam::calcGexp(), Foam::equal(), forAll, Foam::pow(), and UPtrList< T >::size().
Member Function Documentation
points()
const Foam::pointField & points () const noexcept
Definition at line 136 of file lineDivide.C.
lambdaDivisions()
const Foam::scalarList & lambdaDivisions () const noexcept
Definition at line 142 of file lineDivide.C.
The documentation for this class was generated from the following files:
src/mesh/blockMesh/blockEdges/lineDivide/lineDivide.H
src/mesh/blockMesh/blockEdges/lineDivide/lineDivide.C