OpenFOAM: timeSelector Class Reference
timeSelector Class Reference
A List of scalarRange for selecting times.
#include <timeSelector.H>
Public Member Functions
timeSelector () noexcept=default
timeSelector (const std::string &str)
bool contains (const scalar value) const
bool contains (const instant &t) const
bool selected (const instant &t) const
List< bool > selected (const instantList &times) const
instantList select (const instantList &times) const
void inplaceSelect (instantList &times) const
Static Public Member Functions
static void addOptions (const bool constant=true, const bool withZero=false)
static instantList select (const instantList &times, const argList &args, const word &constantName="constant")
static instantList select0 (Time &runTime, const argList &args)
static instantList selectIfPresent (Time &runTime, const argList &args)
Detailed Description
A List of scalarRange for selecting times.
The timeSelector provides a convenient means of selecting multiple times. A typical use would be the following:
timeSelector::addOptions();
// add other options
#include "setRootCase.H"
#include "createTime.H"
instantList timeDirs = timeSelector::select0(runTime, args);
...
forAll(timeDirs, timei)
{
    ...
}
The result program would receive -time, -latestTime, -constant and -noZero options. The -constant option explicitly includes the constant/ directory in the time list and the -noZero option explicitly excludes the 0/ directory from the time list.
There may however also be many cases in which neither the constant/ directory nor the 0/ directory contain particularly relevant information. This might occur, for example, when post-processing results. In this case, addOptions is called with optional boolean arguments.
timeSelector::addOptions(false, true);
The first argument avoids adding the -constant option. The second argument adds an additional -withZero option and also prevents the 0/ directory from being included in the default time range and in the -latestTime selection.
Source files
timeSelector.H
timeSelector.C
Definition at line 88 of file timeSelector.H.
Constructor & Destructor Documentation
timeSelector() [1/2]
timeSelector () default noexcept
timeSelector() [2/2]
timeSelector (const std::string & str) explicit
Definition at line 29 of file timeSelector.C.
Member Function Documentation
contains() [1/2]
bool contains (const scalar value) const
Definition at line 37 of file timeSelector.C.
Referenced by timeSelector::selected().
contains() [2/2]
bool contains (const instant & t) const
Definition at line 43 of file timeSelector.C.
References Instant< T >::value().
selected() [1/2]
bool selected (const instant & t) const inline
Definition at line 116 of file timeSelector.H.
References timeSelector::contains().
Referenced by timeSelector::select().
selected() [2/2]
Foam::List< bool > selected (const instantList & times) const
Definition at line 49 of file timeSelector.C.
References TimePaths::findClosestTimeIndex(), forAll, range, and UList< T >::size().
select() [1/2]
Foam::instantList select (const instantList & times) const
Definition at line 88 of file timeSelector.C.
References Foam::subset().
Referenced by timeSelector::select0().
inplaceSelect()
void inplaceSelect (instantList & times) const
Definition at line 94 of file timeSelector.C.
References Foam::inplaceSubset().
addOptions()
void addOptions (const bool constant = true, const bool withZero = false) static
Definition at line 100 of file timeSelector.C.
References argList::addBoolOption(), and argList::addOption().
Referenced by if().
select() [2/2]
Foam::instantList select (const instantList & times, const argList & args, const word & constantName = "constant") static
Definition at line 146 of file timeSelector.C.
References args, forAll, found, argList::found(), Foam::name(), timeSelector::selected(), UList< T >::size(), Foam::subset(), and argList::validOptions.
select0()
Foam::instantList select0 (Time & runTime, const argList & args) static
Definition at line 233 of file timeSelector.C.
References List< T >::append(), args, TimePaths::constant(), UList< T >::empty(), Foam::endl(), UList< T >::first(), runTime, timeSelector::select(), Time::setTime(), TimePaths::times(), and WarningInFunction.
Referenced by if().
selectIfPresent()
Foam::instantList selectIfPresent (Time & runTime, const argList & args) static
Definition at line 264 of file timeSelector.C.
References args, argList::found(), runTime, Time::timeName(), and dimensioned< Type >::value().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/Time/timeSelector.H
src/OpenFOAM/db/Time/timeSelector.C