OpenFOAM: syncTools Class Reference
syncTools Class Reference
Various tools to aid synchronizing lists across coupled patches. WIP.
#include <syncTools.H>
Static Public Member Functions
template<class T , class CombineOp , class TransformOp >
static void syncPointMap (const polyMesh &mesh, Map< T > &pointValues, const CombineOp &cop, const TransformOp &top)
template<class T , class CombineOp , class TransformOp >
static void syncEdgeMap (const polyMesh &mesh, EdgeMap< T > &edgeValues, const CombineOp &cop, const TransformOp &top)
template<class T , class CombineOp , class TransformOp >
static void syncPointList (const polyMesh &mesh, List< T > &pointValues, const CombineOp &cop, const T &nullValue, const TransformOp &top)
template<class T , class CombineOp , class TransformOp >
static void syncPointList (const polyMesh &mesh, const labelUList &meshPoints, List< T > &pointValues, const CombineOp &cop, const T &nullValue, const TransformOp &top)
template<class T , class CombineOp , class TransformOp , class FlipOp >
static void syncEdgeList (const polyMesh &mesh, List< T > &edgeValues, const CombineOp &cop, const T &nullValue, const TransformOp &top, const FlipOp &fop)
template<class T , class CombineOp , class TransformOp , class FlipOp >
static void syncEdgeList (const polyMesh &mesh, const labelList &meshEdges, List< T > &edgeValues, const CombineOp &cop, const T &nullValue, const TransformOp &top, const FlipOp &fop)
template<class T , class CombineOp , class TransformOp >
static void syncBoundaryFaceList (const polyMesh &mesh, UList< T > &faceValues, const CombineOp &cop, const TransformOp &top, const bool parRun=UPstream::parRun())
template<class T , class CombineOp >
static void syncPointList (const polyMesh &mesh, List< T > &pointValues, const CombineOp &cop, const T &nullValue)
template<class CombineOp >
static void syncPointPositions (const polyMesh &mesh, List< point > &positions, const CombineOp &cop, const point &nullValue)
template<class T , class CombineOp >
static void syncPointList (const polyMesh &mesh, const labelList &meshPoints, List< T > &pointValues, const CombineOp &cop, const T &nullValue)
template<class CombineOp >
static void syncPointPositions (const polyMesh &mesh, const labelList &meshPoints, List< point > &positions, const CombineOp &cop, const point &nullValue)
template<class T , class CombineOp >
static void syncEdgeList (const polyMesh &mesh, List< T > &edgeValues, const CombineOp &cop, const T &nullValue)
template<class CombineOp >
static void syncEdgePositions (const polyMesh &mesh, List< point > &positions, const CombineOp &cop, const point &nullValue)
template<class T , class CombineOp >
static void syncEdgeList (const polyMesh &mesh, const labelList &meshEdges, List< T > &edgeValues, const CombineOp &cop, const T &nullValue)
template<class CombineOp >
static void syncEdgePositions (const polyMesh &mesh, const labelList &meshEdges, List< point > &positions, const CombineOp &cop, const point &nullValue)
template<class T , class CombineOp >
static void syncBoundaryFaceList (const polyMesh &mesh, UList< T > &faceValues, const CombineOp &cop)
template<class CombineOp >
static void syncBoundaryFacePositions (const polyMesh &mesh, UList< point > &positions, const CombineOp &cop)
template<class T , class CombineOp >
static void syncFaceList (const polyMesh &mesh, UList< T > &faceValues, const CombineOp &cop)
template<class CombineOp >
static void syncFacePositions (const polyMesh &mesh, UList< point > &positions, const CombineOp &cop)
template<class T >
static void swapBoundaryFaceList (const polyMesh &mesh, UList< T > &faceValues)
static void swapBoundaryFacePositions (const polyMesh &mesh, UList< point > &positions)
template<class T >
static void swapFaceList (const polyMesh &mesh, UList< T > &faceValues)
template<class T >
static void swapBoundaryCellList (const polyMesh &mesh, const UList< T > &cellData, List< T > &neighbourCellData)
static void swapBoundaryCellPositions (const polyMesh &mesh, const UList< point > &cellData, List< point > &neighbourCellData)
template<class T , class CombineOp >
static void syncPointMap (const polyMesh &mesh, Map< T > &pointValues, const CombineOp &cop)
template<class CombineOp >
static void syncPointPositions (const polyMesh &mesh, Map< point > &positions, const CombineOp &cop)
template<class T , class CombineOp >
static void syncEdgeMap (const polyMesh &mesh, EdgeMap< T > &edgeValues, const CombineOp &cop)
template<class CombineOp >
static void syncEdgePositions (const polyMesh &mesh, EdgeMap< point > &edgePositions, const CombineOp &cop)
template<unsigned Width, class CombineOp >
static void syncFaceList (const polyMesh &mesh, const bool isBoundaryOnly, PackedList< Width > &faceValues, const CombineOp &cop, const bool parRun=UPstream::parRun())
template<unsigned Width, class CombineOp >
static void syncFaceList (const polyMesh &mesh, PackedList< Width > &faceValues, const CombineOp &cop, const bool parRun=UPstream::parRun())
template<unsigned Width, class CombineOp >
static void syncBoundaryFaceList (const polyMesh &mesh, PackedList< Width > &faceValues, const CombineOp &cop, const bool parRun=UPstream::parRun())
template<unsigned Width>
static void swapFaceList (const polyMesh &mesh, PackedList< Width > &faceValues)
template<unsigned Width>
static void swapBoundaryFaceList (const polyMesh &mesh, PackedList< Width > &faceValues)
template<unsigned Width, class CombineOp >
static void syncPointList (const polyMesh &mesh, PackedList< Width > &pointValues, const CombineOp &cop, const unsigned int nullValue)
template<unsigned Width, class CombineOp >
static void syncEdgeList (const polyMesh &mesh, PackedList< Width > &edgeValues, const CombineOp &cop, const unsigned int nullValue)
static bitSet getMasterPoints (const polyMesh &mesh)
static bitSet getMasterEdges (const polyMesh &mesh)
static bitSet getMasterFaces (const polyMesh &mesh)
static bitSet getInternalOrMasterFaces (const polyMesh &mesh)
static bitSet getInternalOrCoupledFaces (const polyMesh &mesh)
Detailed Description
Various tools to aid synchronizing lists across coupled patches. WIP.
Require
combineOperator (e.g. sumEqOp - not sumOp!) that is defined for the type be defined.
null value which gets overridden by any valid value.
transform function
Source files
syncTools.H
syncTools.C
syncToolsTemplates.C
Definition at line 62 of file syncTools.H.
Member Function Documentation
syncPointMap() [1/2]
template<class T , class CombineOp , class TransformOp > void syncPointMap (const polyMesh & mesh, Map< T > & pointValues, const CombineOp & cop, const TransformOp & top) static
Definition at line 76 of file syncToolsTemplates.C.
References polyMesh::boundaryMesh(), Pstream::broadcast(), e, UPtrList< T >::empty(), forAll, forAllConstIters, polyMesh::globalData(), UPstream::master(), UPstream::masterNo(), mesh, UPstream::nonBlocking, PrimitivePatch< FaceList, PointField >::nPoints(), UPstream::parRun(), patches, pp(), PtrList< T >::push_back(), PtrList< T >::resize(), UPstream::scheduled, PtrList< T >::set(), UPtrList< T >::size(), and UPstream::subProcs().
Referenced by reconstructedDistanceFunction::markCellsNearSurf(), syncTools::syncPointMap(), and syncTools::syncPointPositions().
syncEdgeMap() [1/2]
template<class T , class CombineOp , class TransformOp > void syncEdgeMap (const polyMesh & mesh, EdgeMap< T > & edgeValues, const CombineOp & cop, const TransformOp & top) static
Definition at line 397 of file syncToolsTemplates.C.
References polyMesh::boundaryMesh(), Pstream::broadcast(), e, UPtrList< T >::empty(), f(), polyMesh::faces(), UList< T >::fcIndex(), forAll, forAllConstIters, polyMesh::globalData(), UPstream::master(), UPstream::masterNo(), mesh, PrimitivePatch< FaceList, PointField >::nEdges(), primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), UPstream::nonBlocking, UPstream::parRun(), patches, pp(), PtrList< T >::push_back(), UPstream::scheduled, UPtrList< T >::size(), UList< T >::size(), and UPstream::subProcs().
Referenced by holeToFace::calcClosure(), patchPatchDist::correct(), syncTools::syncEdgeMap(), and syncTools::syncEdgePositions().
syncPointList() [1/5]
template<class T , class CombineOp , class TransformOp > void syncPointList (const polyMesh & mesh, List< T > & pointValues, const CombineOp & cop, const T & nullValue, const TransformOp & top) static
Definition at line 793 of file syncToolsTemplates.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, polyMesh::globalData(), mesh, primitiveMesh::nPoints(), and UPtrList< T >::size().
Referenced by singleProcessorFaceSets::add(), sensitivitySurface::addGeometricSens(), singleProcessorFaceSets::apply(), sensitivitySurfacePoints::assembleSensitivities(), motionSmootherAlgo::avg(), meshRefinement::blockLeakFaces(), snappySnapDriver::calcNearestSurface(), snappySnapDriver::calcSnapDistance(), edgeCollapser::checkMeshQuality(), pointZone::checkParallelSync(), hexRef8::checkRefinementLevels(), edgeCollapser::consistentCollapse(), hexRef8::consistentSlowRefinement(), sensitivitySurfacePoints::constructGlobalPointNormalsAndAreas(), motionSmootherAlgo::correctBoundaryConditions(), removePoints::countPointUsage(), meshRefinement::dupNonManifoldBoundaryPoints(), meshRefinement::getMasterPoints(), dynamicMultiMotionSolverFvMesh::init(), patchTransformedInterpolation::interpolate(), multiSolidBodyMotionSolver::multiSolidBodyMotionSolver(), motionSmootherAlgo::scaleMesh(), dynamicRefineFvMesh::selectUnrefinePoints(), motionSmootherAlgo::setDisplacement(), addPatchCellLayer::setRefinement(), removeFaces::setRefinement(), combineFaces::setRefinement(), fieldSmoother::smoothNormals(), pointBitSet::sync(), pointSet::sync(), syncTools::syncPointList(), syncTools::syncPointList(), syncTools::syncPointPositions(), syncTools::syncPointPositions(), weightedPosition::syncPoints(), weightedPosition::syncPoints(), meshRefinement::testSyncPointList(), meshRefinement::testSyncPointList(), meshRefinement::weightedSum(), and zoneMotion::zoneMotion().
syncPointList() [2/5]
template<class T , class CombineOp , class TransformOp > void syncPointList (const polyMesh & mesh, const labelUList & meshPoints, List< T > & pointValues, const CombineOp & cop, const T & nullValue, const TransformOp & top) static
Definition at line 815 of file syncToolsTemplates.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, polyMesh::globalData(), mesh, UPtrList< T >::size(), UList< T >::size(), and globalMeshData::syncData().
syncEdgeList() [1/5]
template<class T , class CombineOp , class TransformOp , class FlipOp > void syncEdgeList (const polyMesh & mesh, List< T > & edgeValues, const CombineOp & cop, const T & nullValue, const TransformOp & top, const FlipOp & fop) static
Definition at line 872 of file syncToolsTemplates.C.
References Foam::abort(), edge::compare(), primitiveMesh::edges(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, polyMesh::globalData(), mesh, primitiveMesh::nEdges(), polyMesh::points(), UPtrList< T >::size(), UList< T >::size(), and globalMeshData::syncData().
Referenced by edgeCollapser::consistentCollapse(), meshRefinement::getMasterEdges(), addPatchCellLayer::globalEdgeFaces(), meshCutter::setRefinement(), addPatchCellLayer::setRefinement(), hexRef8::setRefinement(), removeFaces::setRefinement(), syncTools::syncEdgeList(), syncTools::syncEdgeList(), syncTools::syncEdgePositions(), and syncTools::syncEdgePositions().
syncEdgeList() [2/5]
template<class T , class CombineOp , class TransformOp , class FlipOp > void syncEdgeList (const polyMesh & mesh, const labelList & meshEdges, List< T > & edgeValues, const CombineOp & cop, const T & nullValue, const TransformOp & top, const FlipOp & fop) static
Definition at line 969 of file syncToolsTemplates.C.
References Foam::abort(), edge::compare(), primitiveMesh::edges(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, polyMesh::globalData(), mesh, polyMesh::points(), UPtrList< T >::size(), UList< T >::size(), and globalMeshData::syncData().
syncBoundaryFaceList() [1/3]
template<class T , class CombineOp , class TransformOp > void syncBoundaryFaceList (const polyMesh & mesh, UList< T > & faceValues, const CombineOp & cop, const TransformOp & top, const bool parRun = UPstream::parRun()) static
Definition at line 1070 of file syncToolsTemplates.C.
References Foam::abort(), polyMesh::boundaryMesh(), UPstream::defaultCommsType, Foam::FatalError, FatalErrorInFunction, fld(), forAll, mesh, primitiveMesh::nBoundaryFaces(), primitiveMesh::nInternalFaces(), Foam::nl, UPstream::nonBlocking, UPstream::nRequests(), patches, pp(), UIPstream::read(), UPtrList< T >::size(), UPstream::waitRequests(), and UOPstream::write().
Referenced by cellToFaceStencil::calcFaceStencil(), polyMeshTetDecomposition::findFaceBasePts(), removeCells::getExposedFaces(), decompositionConstraint::getMinBoundaryValue(), removePoints::getUnrefimentSet(), addPatchCellLayer::setRefinement(), syncTools::swapBoundaryFaceList(), syncTools::swapBoundaryFacePositions(), syncTools::swapFaceList(), syncTools::syncBoundaryFaceList(), syncTools::syncBoundaryFacePositions(), syncTools::syncFaceList(), and syncTools::syncFacePositions().
syncPointList() [3/5]
template<class T , class CombineOp > static void syncPointList (const polyMesh & mesh, List< T > & pointValues, const CombineOp & cop, const T & nullValue) inline static
Definition at line 176 of file syncTools.H.
References mesh, and syncTools::syncPointList().
syncPointPositions() [1/3]
template<class CombineOp > static void syncPointPositions (const polyMesh & mesh, List< point > & positions, const CombineOp & cop, const point & nullValue) inline static
Definition at line 196 of file syncTools.H.
References mesh, and syncTools::syncPointList().
syncPointList() [4/5]
template<class T , class CombineOp > static void syncPointList (const polyMesh & mesh, const labelList & meshPoints, List< T > & pointValues, const CombineOp & cop, const T & nullValue) inline static
Definition at line 216 of file syncTools.H.
References mesh, and syncTools::syncPointList().
syncPointPositions() [2/3]
template<class CombineOp > static void syncPointPositions (const polyMesh & mesh, const labelList & meshPoints, List< point > & positions, const CombineOp & cop, const point & nullValue) inline static
Definition at line 238 of file syncTools.H.
References mesh, and syncTools::syncPointList().
syncEdgeList() [3/5]
template<class T , class CombineOp > static void syncEdgeList (const polyMesh & mesh, List< T > & edgeValues, const CombineOp & cop, const T & nullValue) inline static
Definition at line 263 of file syncTools.H.
References mesh, and syncTools::syncEdgeList().
syncEdgePositions() [1/3]
template<class CombineOp > static void syncEdgePositions (const polyMesh & mesh, List< point > & positions, const CombineOp & cop, const point & nullValue) inline static
Definition at line 284 of file syncTools.H.
References mesh, and syncTools::syncEdgeList().
Referenced by hexRef8::setRefinement().
syncEdgeList() [4/5]
template<class T , class CombineOp > static void syncEdgeList (const polyMesh & mesh, const labelList & meshEdges, List< T > & edgeValues, const CombineOp & cop, const T & nullValue) inline static
Definition at line 305 of file syncTools.H.
References mesh, and syncTools::syncEdgeList().
syncEdgePositions() [2/3]
template<class CombineOp > static void syncEdgePositions (const polyMesh & mesh, const labelList & meshEdges, List< point > & positions, const CombineOp & cop, const point & nullValue) inline static
Definition at line 328 of file syncTools.H.
References mesh, and syncTools::syncEdgeList().
syncBoundaryFaceList() [2/3]
template<class T , class CombineOp > static void syncBoundaryFaceList (const polyMesh & mesh, UList< T > & faceValues, const CombineOp & cop) inline static
Definition at line 355 of file syncTools.H.
References mesh, and syncTools::syncBoundaryFaceList().
syncBoundaryFacePositions()
template<class CombineOp > static void syncBoundaryFacePositions (const polyMesh & mesh, UList< point > & positions, const CombineOp & cop) inline static
Definition at line 373 of file syncTools.H.
References mesh, and syncTools::syncBoundaryFaceList().
Referenced by meshRefinement::checkData(), and hexRef8::setRefinement().
syncFaceList() [1/3]
template<class T , class CombineOp > static void syncFaceList (const polyMesh & mesh, UList< T > & faceValues, const CombineOp & cop) inline static
Definition at line 391 of file syncTools.H.
References mesh, and syncTools::syncBoundaryFaceList().
Referenced by refinementHistory::add(), geometric::add(), preserveBaffles::add(), preserveFaceZones::add(), preservePatches::add(), singleProcessorFaceSets::add(), polyMeshTetDecomposition::adjustTetBasePtIs(), meshRefinement::balance(), holeToFace::calcClosure(), dynamicRefineFvMesh::calculateProtectedCells(), meshRefinement::collectFaces(), meshRefinement::createBaffles(), dynamicRefineFvMesh::extendMarkedCells(), distanceSurface::filterPrepareRegionSplit(), meshRefinement::growFaceCellFace(), meshRefinement::growFaceCellFace(), dynamicRefineFvMesh::init(), oversetFvMeshBase::normalisation(), hexRef8::setRefinement(), meshRefinement::splitMesh(), faceBitSet::sync(), faceBoolSet::sync(), faceSet::sync(), meshRefinement::updateIntersections(), and cellCellStencil::walkFront().
syncFacePositions()
template<class CombineOp > static void syncFacePositions (const polyMesh & mesh, UList< point > & positions, const CombineOp & cop) inline static
Definition at line 416 of file syncTools.H.
References mesh, and syncTools::syncBoundaryFaceList().
swapBoundaryFaceList() [1/2]
template<class T > static void swapBoundaryFaceList (const polyMesh & mesh, UList< T > & faceValues) inline static
Definition at line 440 of file syncTools.H.
References mesh, and syncTools::syncBoundaryFaceList().
Referenced by decompositionMethod::calcCellCells(), decompositionMethod::calcCellCells(), dynamicRefineFvMesh::calculateProtectedCells(), meshRefinement::checkCoupledFaceZones(), meshRefinement::checkData(), hexRef8::checkMesh(), faceZone::checkParallelSync(), hexRef8::checkRefinementLevels(), polyMeshGeometry::checkVolRatio(), hexRef8::consistentSlowRefinement(), hexRef8::consistentUnrefinement(), fluxSummary::initialiseCellZoneAndDirection(), SloanRenumber::renumber(), rotorDiskSource::setFaceArea(), tetDecomposer::setRefinement(), addPatchCellLayer::setRefinement(), hexRef8::setRefinement(), syncTools::swapBoundaryCellList(), and faceZoneSet::sync().
swapBoundaryFacePositions()
static void swapBoundaryFacePositions (const polyMesh & mesh, UList< point > & positions) inline static
Definition at line 456 of file syncTools.H.
References mesh, and syncTools::syncBoundaryFaceList().
Referenced by polyMeshGeometry::checkFaceDotProduct(), polyMeshGeometry::checkFaceTets(), polyMeshTetDecomposition::checkFaceTets(), polyMeshGeometry::checkFaceTwist(), polyMeshGeometry::checkFaceWeights(), polyMeshTetDecomposition::findFaceBasePts(), and syncTools::swapBoundaryCellPositions().
swapFaceList() [1/2]
template<class T > static void swapFaceList (const polyMesh & mesh, UList< T > & faceValues) inline static
Definition at line 473 of file syncTools.H.
References mesh, and syncTools::syncBoundaryFaceList().
Referenced by dynamicRefineFvMesh::init(), and removeFaces::setRefinement().
swapBoundaryCellList()
template<class T > void swapBoundaryCellList (const polyMesh & mesh, const UList< T > & cellData, List< T > & neighbourCellData) static
Definition at line 1473 of file syncToolsTemplates.C.
References Foam::abort(), polyMesh::boundaryMesh(), Foam::FatalError, FatalErrorInFunction, mesh, primitiveMesh::nBoundaryFaces(), primitiveMesh::nCells(), patches, pp(), PtrList< T >::resize(), UPtrList< T >::size(), and syncTools::swapBoundaryFaceList().
Referenced by oversetFvPatchField< Type >::adjustPsi(), highAspectRatioFvGeometryScheme::calcAspectRatioWeights(), decompositionMethod::decompose(), cellVolumeWeight::findHoles(), inverseDistance::findHoles(), cellCellStencil::globalCellCells(), inverseDistance::holeExtrapolationStencil(), meshRefinement::markOutsideFaces(), oversetFvMeshBase::normalisation(), cellCellStencil::setUpFront(), oversetFvPatchField< Type >::storeFringeCoefficients(), polyMeshTools::volRatio(), and meshRefinement::zonify().
swapBoundaryCellPositions()
void swapBoundaryCellPositions (const polyMesh & mesh, const UList< point > & cellData, List< point > & neighbourCellData) static
Definition at line 26 of file syncTools.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, mesh, patches, pp(), PtrList< T >::resize(), UPtrList< T >::size(), and syncTools::swapBoundaryFacePositions().
Referenced by searchableSurfaceToFaceZone::applyToSet(), averageNeighbourFvGeometryScheme::averageCentres(), averageNeighbourFvGeometryScheme::averageNeighbourCentres(), polyMeshGeometry::checkFaceSkewness(), polyMeshTools::faceOrthogonality(), polyMeshTools::faceSkewness(), and polyMeshTools::faceWeights().
syncPointMap() [2/2]
template<class T , class CombineOp > static void syncPointMap (const polyMesh & mesh, Map< T > & pointValues, const CombineOp & cop) inline static
Definition at line 516 of file syncTools.H.
References mesh, and syncTools::syncPointMap().
syncPointPositions() [3/3]
template<class CombineOp > static void syncPointPositions (const polyMesh & mesh, Map< point > & positions, const CombineOp & cop) inline static
Definition at line 534 of file syncTools.H.
References mesh, and syncTools::syncPointMap().
syncEdgeMap() [2/2]
template<class T , class CombineOp > static void syncEdgeMap (const polyMesh & mesh, EdgeMap< T > & edgeValues, const CombineOp & cop) inline static
Definition at line 554 of file syncTools.H.
References mesh, and syncTools::syncEdgeMap().
syncEdgePositions() [3/3]
template<class CombineOp > static void syncEdgePositions (const polyMesh & mesh, EdgeMap< point > & edgePositions, const CombineOp & cop) inline static
Definition at line 572 of file syncTools.H.
References mesh, and syncTools::syncEdgeMap().
syncFaceList() [2/3]
template<unsigned Width, class CombineOp > void syncFaceList (const polyMesh & mesh, const bool isBoundaryOnly, PackedList< Width > & faceValues, const CombineOp & cop, const bool parRun = UPstream::parRun()) static
Definition at line 1314 of file syncToolsTemplates.C.
References Foam::abort(), polyMesh::boundaryMesh(), Foam::FatalError, FatalErrorInFunction, mesh, primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), Foam::nl, UPstream::nonBlocking, UPstream::nRequests(), patches, pp(), range, UIPstream::read(), PtrList< T >::set(), UPtrList< T >::size(), UPstream::waitRequests(), and UOPstream::write().
syncFaceList() [3/3]
template<unsigned Width, class CombineOp > void syncFaceList (const polyMesh & mesh, PackedList< Width > & faceValues, const CombineOp & cop, const bool parRun = UPstream::parRun()) static
Definition at line 1507 of file syncToolsTemplates.C.
References mesh.
syncBoundaryFaceList() [3/3]
template<unsigned Width, class CombineOp > void syncBoundaryFaceList (const polyMesh & mesh, PackedList< Width > & faceValues, const CombineOp & cop, const bool parRun = UPstream::parRun()) static
Definition at line 1520 of file syncToolsTemplates.C.
References mesh.
swapFaceList() [2/2]
template<unsigned Width> void swapFaceList (const polyMesh & mesh, PackedList< Width > & faceValues) static
Definition at line 1533 of file syncToolsTemplates.C.
References mesh.
swapBoundaryFaceList() [2/2]
template<unsigned Width> void swapBoundaryFaceList (const polyMesh & mesh, PackedList< Width > & faceValues) static
Definition at line 1544 of file syncToolsTemplates.C.
References mesh.
syncPointList() [5/5]
template<unsigned Width, class CombineOp > void syncPointList (const polyMesh & mesh, PackedList< Width > & pointValues, const CombineOp & cop, const unsigned int nullValue) static
Definition at line 1555 of file syncToolsTemplates.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, polyMesh::globalData(), mesh, primitiveMesh::nPoints(), UPtrList< T >::size(), and globalMeshData::syncData().
syncEdgeList() [5/5]
template<unsigned Width, class CombineOp > void syncEdgeList (const polyMesh & mesh, PackedList< Width > & edgeValues, const CombineOp & cop, const unsigned int nullValue) static
Definition at line 1598 of file syncToolsTemplates.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, polyMesh::globalData(), mesh, primitiveMesh::nEdges(), UPtrList< T >::size(), and globalMeshData::syncData().
getMasterPoints()
Foam::bitSet getMasterPoints (const polyMesh & mesh) static
Definition at line 61 of file syncTools.C.
References globalMeshData::coupledPatch(), forAll, polyMesh::globalData(), globalMeshData::globalPointSlaves(), globalMeshData::globalPointTransformedSlaves(), mesh, primitiveMesh::nPoints(), and bitSet::set().
Referenced by meshRefinement::printMeshInfo().
getMasterEdges()
Foam::bitSet getMasterEdges (const polyMesh & mesh) static
Definition at line 90 of file syncTools.C.
References globalMeshData::coupledPatchMeshEdges(), forAll, polyMesh::globalData(), globalMeshData::globalEdgeSlaves(), globalMeshData::globalEdgeTransformedSlaves(), mesh, primitiveMesh::nEdges(), and bitSet::set().
Referenced by motionSmootherAlgo::updateMesh().
getMasterFaces()
Foam::bitSet getMasterFaces (const polyMesh & mesh) static
Definition at line 119 of file syncTools.C.
References polyMesh::boundaryMesh(), mesh, primitiveMesh::nFaces(), patches, pp(), and bitSet::unset().
Referenced by meshRefinement::countHits(), meshRefinement::printMeshInfo(), faceZoneSet::sync(), meshRefinement::updateIntersections(), and meshRefinement::zonify().
getInternalOrMasterFaces()
Foam::bitSet getInternalOrMasterFaces (const polyMesh & mesh) static
Definition at line 140 of file syncTools.C.
References polyMesh::boundaryMesh(), mesh, primitiveMesh::nFaces(), patches, pp(), and bitSet::unset().
getInternalOrCoupledFaces()
Foam::bitSet getInternalOrCoupledFaces (const polyMesh & mesh) static
Definition at line 168 of file syncTools.C.
References polyMesh::boundaryMesh(), mesh, primitiveMesh::nFaces(), patches, pp(), and bitSet::unset().
Referenced by snappyLayerDriver::doLayers(), and meshRefinement::getZoneFaces().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/syncTools/syncTools.H
src/OpenFOAM/meshes/polyMesh/syncTools/syncTools.C
src/OpenFOAM/meshes/polyMesh/syncTools/syncToolsTemplates.C