OpenFOAM: maitlandSmith Class Reference
maitlandSmith Class Reference
Reference:
#include <maitlandSmith.H>
Public Member Functions
TypeName ("maitlandSmith")
maitlandSmith (const word &name, const dictionary &pairPotentialProperties)
~maitlandSmith ()
scalar unscaledEnergy (const scalar r) const
bool read (const dictionary &pairPotentialProperties)
Public Member Functions inherited from pairPotential
TypeName ("pairPotential")
declareRunTimeSelectionTable (autoPtr, pairPotential, dictionary,(const word &name, const dictionary &pairPotentialProperties),(name, pairPotentialProperties))
pairPotential (const word &name, const dictionary &pairPotentialProperties)
virtual ~pairPotential ()=default
void setLookupTables ()
scalar rMin () const
scalar dr () const
scalar rCut () const
scalar rCutSqr () const
scalar energy (const scalar r) const
scalar force (const scalar r) const
List< Pair< scalar > > energyTable () const
List< Pair< scalar > > forceTable () const
bool writeTables () const
scalar scaledEnergy (const scalar r) const
scalar energyDerivative (const scalar r, const bool scaledEnergyDerivative=true) const
const dictionary & pairPotentialProperties () const
bool writeEnergyAndForceTables (Ostream &os) const
Additional Inherited Members
Static Public Member Functions inherited from pairPotential
static autoPtr< pairPotential > New (const word &name, const dictionary &pairPotentialProperties)
Protected Member Functions inherited from pairPotential
void scaleEnergy (scalar &e, const scalar r) const
pairPotential (const pairPotential &)=delete
void operator= (const pairPotential &)=delete
Protected Attributes inherited from pairPotential
word name_
dictionary pairPotentialProperties_
scalar rCut_
scalar rCutSqr_
scalar rMin_
scalar dr_
List< scalar > forceLookup_
List< scalar > energyLookup_
energyScalingFunction * esfPtr_
bool writeTables_
Detailed Description
Reference:
    Maitland, G. C., & Smith, E. B. (1973).
    A simplified representation of intermolecular potential energy.
    Chemical Physics Letters, 22(3), 443-446.
Parameters for other monoatomics from:
    Maitland, G. C., Rigby, M., Smith, E., Wakeham, W. (1981).
    Intermolecular forces: Their origin and determination.
    Oxford: Clarendon Press.
Source files
maitlandSmith.H
maitlandSmith.C
Definition at line 62 of file maitlandSmith.H.
Constructor & Destructor Documentation
maitlandSmith()
maitlandSmith (const word & name, const dictionary & pairPotentialProperties)
Definition at line 45 of file maitlandSmith.C.
References pairPotential::setLookupTables().
~maitlandSmith()
~maitlandSmith () inline
Definition at line 93 of file maitlandSmith.H.
Member Function Documentation
TypeName()
TypeName ("maitlandSmith")
unscaledEnergy()
scalar unscaledEnergy (const scalar r) const virtual
Implements pairPotential.
Definition at line 64 of file maitlandSmith.C.
References Foam::pow().
read()
bool read (const dictionary & pairPotentialProperties) virtual
Implements pairPotential.
Definition at line 76 of file maitlandSmith.C.
References pairPotential::read(), and dictionary::readEntry().
The documentation for this class was generated from the following files:
src/lagrangian/molecularDynamics/potential/pairPotential/derived/maitlandSmith/maitlandSmith.H
src/lagrangian/molecularDynamics/potential/pairPotential/derived/maitlandSmith/maitlandSmith.C