OpenFOAM: momentOfInertia Class Reference
momentOfInertia Class Reference
Calculates the inertia tensor and principal axes and moments of a polyhedra/cells/triSurfaces. Inertia can either be of the solid body or of a thin shell.
#include <momentOfInertia.H>
Static Public Member Functions
static void massPropertiesSolid (const pointField &pts, const triFaceList &triFaces, scalar density, scalar &mass, vector &cM, tensor &J)
static void massPropertiesShell (const pointField &pts, const triFaceList &triFaces, scalar density, scalar &mass, vector &cM, tensor &J, bool doReduce=false)
static void massPropertiesSolid (const triSurface &surf, scalar density, scalar &mass, vector &cM, tensor &J)
static void massPropertiesShell (const triSurface &surf, scalar density, scalar &mass, vector &cM, tensor &J, bool doReduce=false)
static void massPropertiesPatch (const polyPatch &pp, scalar density, scalar &mass, vector &cM, tensor &J, bool doReduce=false)
static tensor applyParallelAxisTheorem (scalar mass, const vector &cM, const tensor &J, const vector &refPt)
static tmp< tensorField > meshInertia (const polyMesh &mesh)
static tensor meshInertia (const polyMesh &mesh, label celli)
Detailed Description
Calculates the inertia tensor and principal axes and moments of a polyhedra/cells/triSurfaces. Inertia can either be of the solid body or of a thin shell.
References:
    "Fast and Accurate Computation of Polyhedral Mass Properties",
    Brian Mirtich,
    Journal of Graphics Tools, Volume 1, Number 2, 1996.
https://people.eecs.berkeley.edu/~jfc/mirtich/massProps.html https://people.eecs.berkeley.edu/~jfc/mirtich/papers/volInt.ps.gz https://people.eecs.berkeley.edu/~jfc/mirtich/code/volumeIntegration.tar
Source files
momentOfInertia.H
momentOfInertia.H
Definition at line 61 of file momentOfInertia.H.
Member Function Documentation
massPropertiesSolid() [1/2]
void massPropertiesSolid (const pointField & pts, const triFaceList & triFaces, scalar density, scalar & mass, vector & cM, tensor & J) static
Definition at line 27 of file momentOfInertia.C.
References forAll, Foam::I, n, pts, Vector< Cmpt >::x(), Tensor< Cmpt >::xx(), Tensor< Cmpt >::xy(), Tensor< Cmpt >::xz(), Vector< Cmpt >::y(), Tensor< Cmpt >::yx(), Tensor< Cmpt >::yy(), Tensor< Cmpt >::yz(), Vector< Cmpt >::z(), Foam::Zero, Tensor< Cmpt >::zx(), Tensor< Cmpt >::zy(), and Tensor< Cmpt >::zz().
massPropertiesShell() [1/2]
void massPropertiesShell (const pointField & pts, const triFaceList & triFaces, scalar density, scalar & mass, vector & cM, tensor & J, bool doReduce = false) static
Definition at line 184 of file momentOfInertia.C.
References triangle< Point, PointRef >::centre(), forAll, triangle< Point, PointRef >::mag(), pts, Foam::reduce(), and Foam::Zero.
massPropertiesSolid() [2/2]
void massPropertiesSolid (const triSurface & surf, scalar density, scalar & mass, vector & cM, tensor & J) static
Definition at line 252 of file momentOfInertia.C.
References forAll, PrimitivePatch< FaceList, PointField >::points(), and UList< T >::size().
massPropertiesShell() [2/2]
void massPropertiesShell (const triSurface & surf, scalar density, scalar & mass, vector & cM, tensor & J, bool doReduce = false) static
Definition at line 272 of file momentOfInertia.C.
References forAll, PrimitivePatch< FaceList, PointField >::points(), and UList< T >::size().
massPropertiesPatch()
void massPropertiesPatch (const polyPatch & pp, scalar density, scalar & mass, vector & cM, tensor & J, bool doReduce = false) static
Definition at line 293 of file momentOfInertia.C.
References PtrList< T >::append(), f(), forAll, PrimitivePatch< FaceList, PointField >::points(), pp(), UList< T >::size(), and PtrList< T >::transfer().
applyParallelAxisTheorem()
Foam::tensor applyParallelAxisTheorem (scalar mass, const vector & cM, const tensor & J, const vector & refPt) static
Definition at line 327 of file momentOfInertia.C.
References Foam::I.
meshInertia() [1/2]
Foam::tmp< Foam::tensorField > meshInertia (const polyMesh & mesh) static
Definition at line 345 of file momentOfInertia.C.
References forAll, mesh, and primitiveMesh::nCells().
meshInertia() [2/2]
Foam::tensor meshInertia (const polyMesh & mesh, label celli) static
Definition at line 363 of file momentOfInertia.C.
References polyMeshTetDecomposition::cellTetIndices(), forAll, mesh, polyMesh::points(), UPtrList< T >::size(), and Foam::Zero.
The documentation for this class was generated from the following files:
src/meshTools/momentOfInertia/momentOfInertia.H
src/meshTools/momentOfInertia/momentOfInertia.C