OpenFOAM: Schroeder Class Reference
Schroeder Class Reference
A model for departure from nucleation boiling based on Schroeder-Richter and Bartsch (1994) for boiling flows.
#include <Schroeder.H>
Public Member Functions
TypeName ("Schroeder")
Schroeder (const dictionary &dict)
virtual ~Schroeder ()=default
virtual tmp< scalarField > TDNB (const phaseModel &liquid, const phaseModel &vapor, const label patchi, const scalarField &Tl, const scalarField &Tsatw, const scalarField &L) const
virtual void write (Ostream &os) const
Public Member Functions inherited from TDNBModel
TypeName ("TDNBModel")
declareRunTimeSelectionTable (autoPtr, TDNBModel, dictionary,(const dictionary &dict),(dict))
TDNBModel ()=default
virtual ~TDNBModel ()=default
Additional Inherited Members
Static Public Member Functions inherited from TDNBModel
static autoPtr< TDNBModel > New (const dictionary &dict)
Detailed Description
A model for departure from nucleation boiling based on Schroeder-Richter and Bartsch (1994) for boiling flows.
Reference:
    Schroeder-Richter, D., & Bartsch, G. (1994).
    Analytical calculation of DNB-superheating by a postulated
    thermo-mechanical effect of nucleate boiling.
    International journal of multiphase flow, 20(6), 1143-1167.
    DOI:10.1016/0301-9322(94)90060-4
    Theler, G., & Freis, D. (2011).
    Theoretical critical heat flux prediction based on non-equilibrium
    thermodynamics considerations of the subcooled boiling phenomenon.
    Mecánica Computacional, 30(19), 1713-1732.
Usage
Example of the model specification:
TDNBModel
{
    // Mandatory entries
    type            Schroeder;
    // Optional entries
    kg              <scalar>;
}
where the entries mean:
Property Description Type Reqd Deflt
type Type name: Schroeder word yes -
kg Isoentropic expansion factor for ideal gases scalar no 1.666
Source files
Schroeder.H
Schroeder.C
Definition at line 103 of file Schroeder.H.
Constructor & Destructor Documentation
Schroeder()
Schroeder (const dictionary & dict)
Definition at line 50 of file Schroeder.C.
~Schroeder()
virtual ~Schroeder () virtual default
Member Function Documentation
TypeName()
TypeName ("Schroeder")
TDNB()
Foam::tmp< Foam::scalarField > TDNB (const phaseModel & liquid, const phaseModel & vapor, const label patchi, const scalarField & Tl, const scalarField & Tsatw, const scalarField & L) const virtual
Implements TDNBModel.
Definition at line 63 of file Schroeder.C.
References e, L, Foam::log(), R, and thermophysicalProperties::W().
write()
void write (Ostream & os) const virtual
Reimplemented from TDNBModel.
Definition at line 87 of file Schroeder.C.
References os(), and TDNBModel::write().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/wallBoilingSubModels/TDNBModels/Schroeder/Schroeder.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/wallBoilingSubModels/TDNBModels/Schroeder/Schroeder.C