OpenFOAM: variableHeatTransfer Class Reference
variableHeatTransfer Class Reference
Numerics » Finite volume Options » Sources
Applies a variable heat transfer model depending on local values for inter-region heat exchanges.
#include <variableHeatTransfer.H>
Public Member Functions
TypeName ("variableHeatTransfer")
variableHeatTransfer (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
variableHeatTransfer (const variableHeatTransfer &)=delete
void operator= (const variableHeatTransfer &)=delete
virtual ~variableHeatTransfer ()=default
virtual void calculateHtc ()
virtual bool read (const dictionary &dict)
Public Member Functions inherited from interRegionHeatTransferModel
TypeName ("interRegionHeatTransferModel")
interRegionHeatTransferModel (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
virtual ~interRegionHeatTransferModel ()=default
const word & nbrRegionName () const
const meshToMesh & meshInterp () const
const volScalarField & htc () const
const interRegionHeatTransferModel & nbrModel () const
interRegionHeatTransferModel & nbrModel ()
virtual void addSup (fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldi)
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolate (const interRegionHeatTransferModel &nbrModel, const Field< Type > &field) const
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolate (const Field< Type > &field) const
Public Member Functions inherited from interRegionOption
TypeName ("interRegionOption")
interRegionOption (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
interRegionOption (const interRegionOption &)=delete
void operator= (const interRegionOption &)=delete
virtual ~interRegionOption ()=default
const word & nbrRegionName () const
const meshToMesh & meshInterp () const
Public Member Functions inherited from option
TypeName ("option")
declareRunTimeSelectionTable (autoPtr, option, dictionary,(const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh),(name, modelType, dict, mesh))
option (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
autoPtr< option > clone () const
virtual ~option ()=default
const word & name () const noexcept
const fvMesh & mesh () const noexcept
const dictionary & coeffs () const noexcept
bool active () const noexcept
void setApplied (const label fieldi)
bool active (const bool on) noexcept
virtual bool isActive ()
virtual label applyToField (const word &fieldName) const
virtual void checkApplied () const
virtual void addSup (fvMatrix< vector > &eqn, const label fieldi)
virtual void addSup (fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (fvMatrix< tensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< scalar > &eqn, const label fieldi)
virtual void constrain (fvMatrix< vector > &eqn, const label fieldi)
virtual void constrain (fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< tensor > &eqn, const label fieldi)
virtual void correct (volScalarField &field)
virtual void correct (volVectorField &field)
virtual void correct (volSphericalTensorField &field)
virtual void correct (volSymmTensorField &field)
virtual void correct (volTensorField &field)
virtual void postProcessSens (scalarField &sensField, const word &fieldName=word::null, const word &designVariablesName=word::null)
virtual void postProcessSens (vectorField &sensField, const word &fieldName=word::null, const word &designVariablesName=word::null)
virtual void postProcessSens (tensorField &sensField, const word &fieldName=word::null, const word &designVariablesName=word::null)
virtual void writeHeader (Ostream &) const
virtual void writeFooter (Ostream &) const
virtual void writeData (Ostream &) const
Additional Inherited Members
Static Public Member Functions inherited from option
static autoPtr< option > New (const word &name, const dictionary &dict, const fvMesh &mesh)
Public Attributes inherited from option
bool log
Protected Member Functions inherited from interRegionHeatTransferModel
void setNbrModel ()
void correct ()
template<class Type >
tmp< Field< Type > > interpolate (const interRegionHeatTransferModel &nbrModel, const Field< Type > &field) const
template<class Type >
tmp< Field< Type > > interpolate (const Field< Type > &field) const
template<class Type >
void interpolate (const interRegionHeatTransferModel &nbrModel, const Field< Type > &field, Field< Type > &result) const
template<class Type >
void interpolate (const Field< Type > &field, Field< Type > &result) const
Protected Member Functions inherited from interRegionOption
void setMapper ()
Protected Member Functions inherited from option
void resetApplied ()
Protected Attributes inherited from interRegionHeatTransferModel
word nbrModelName_
interRegionHeatTransferModel * nbrModel_
bool firstIter_
bool semiImplicit_
label timeIndex_
volScalarField htc_
word TName_
word TNbrName_
Protected Attributes inherited from interRegionOption
bool master_
word nbrRegionName_
autoPtr< meshToMesh > meshInterpPtr_
Protected Attributes inherited from option
const word name_
const word modelType_
const fvMesh & mesh_
dictionary dict_
dictionary coeffs_
wordList fieldNames_
List< bool > applied_
bool active_
Detailed Description
Applies a variable heat transfer model depending on local values for inter-region heat exchanges.
The area of contact between regions (area) must be provided. The Nu number is calculated as:
and the heat transfer coefficient as:
where
= Heat transfer coefficient
= Nusselt number
= Reynolds number
= Fluid Prandtl number
= Heat conduction
= Strut diameter
= Model constants
Required fields:
      AoV       | Area per unit volume of heat exchanger    [1/m]
Usage
Minimal example by using constant/fvOptions:
variableHeatTransfer1
{
    // Mandatory entries (unmodifiable)
    type             variableHeatTransfer;
    // Optional entries (runtime modifiable)
    UNbr             U;
    a                0.0;
    b                0.0;
    c                0.0;
    ds               0.0;
    Pr               0.0;
    // Mandatory/Optional (inherited) entries
    ...
}
where the entries mean:
Property Description Type Reqd Dflt
type Type name: variableHeatTransfer word yes -
UNbr Name of operand neighbour velocity field word no U
a Model constant scalar no 0
b Model constant scalar no 0
c Model constant scalar no 0
ds Struct diameter scalar no 0
Pr Fluid Prandtl number scalar no 0
The inherited entries are elaborated in:
interRegionHeatTransfer.H
See also
Foam::fv::interRegionHeatTransferModel
Foam::fv::tabulatedHeatTransfer
Foam::fv::tabulatedNTUHeatTransfer
Foam::fv::constantHeatTransfer
Source files
variableHeatTransfer.H
variableHeatTransfer.C
Definition at line 201 of file variableHeatTransfer.H.
Constructor & Destructor Documentation
variableHeatTransfer() [1/2]
variableHeatTransfer (const word & name, const word & modelType, const dictionary & dict, const fvMesh & mesh)
Definition at line 40 of file variableHeatTransfer.C.
References IOobjectOption::AUTO_WRITE, option::coeffs_, interRegionOption::master_, option::mesh_, IOobjectOption::MUST_READ, Foam::name(), and dictionary::readEntry().
variableHeatTransfer() [2/2]
variableHeatTransfer (const variableHeatTransfer &) delete
~variableHeatTransfer()
virtual ~variableHeatTransfer () virtual default
Member Function Documentation
TypeName()
TypeName ("variableHeatTransfer")
operator=()
void operator= (const variableHeatTransfer &) delete
calculateHtc()
void calculateHtc () virtual
Implements interRegionHeatTransferModel.
Definition at line 86 of file variableHeatTransfer.C.
References basicThermo::dictName, Foam::interpolate(), Foam::mag(), Foam::pow(), and turbulenceModel::propertiesName.
read()
bool read (const dictionary & dict) virtual
Reimplemented from interRegionHeatTransferModel.
Definition at line 113 of file variableHeatTransfer.C.
References dict, and interRegionHeatTransferModel::read().
The documentation for this class was generated from the following files:
src/fvOptions/sources/interRegion/interRegionHeatTransfer/variableHeatTransfer/variableHeatTransfer.H
src/fvOptions/sources/interRegion/interRegionHeatTransfer/variableHeatTransfer/variableHeatTransfer.C