OpenFOAM: Lavieville Class Reference
Lavieville Class Reference
A model for wall heat flux partitioning based on Lavieville et al. (2006) for boiling flows.
#include <Lavieville.H>
Public Member Functions
TypeName ("Lavieville")
Lavieville (const dictionary &dict)
virtual ~Lavieville ()
virtual tmp< scalarField > fLiquid (const scalarField &alphaLiquid) const
virtual void write (Ostream &os) const
Public Member Functions inherited from partitioningModel
TypeName ("partitioningModel")
declareRunTimeSelectionTable (autoPtr, partitioningModel, dictionary,(const dictionary &dict),(dict))
partitioningModel ()=default
virtual ~partitioningModel ()=default
Additional Inherited Members
Static Public Member Functions inherited from partitioningModel
static autoPtr< partitioningModel > New (const dictionary &dict)
Detailed Description
A model for wall heat flux partitioning based on Lavieville et al. (2006) for boiling flows.
Reference:
    Lavieville, J., Quemerais, E., Mimouni, S.,
    Boucker, M., & Mechitoua, N. (2006).
    NEPTUNE CFD V1.0 theory manual.
    NEPTUNE report Nept_2004_L1, 2(3).
Usage
Example of the model specification:
partitioningModel
{
    // Mandatory entries
    type            Lavieville;
    alphaCrit       <scalar>;
}
where the entries mean:
Property Description Type Reqd Deflt
type Type name: Lavieville word yes -
alphaCrit Critical liquid fraction scalar yes -
Source files
Lavieville.H
Lavieville.C
Definition at line 96 of file Lavieville.H.
Constructor & Destructor Documentation
Lavieville()
Lavieville (const dictionary & dict)
Definition at line 47 of file Lavieville.C.
~Lavieville()
~Lavieville () virtual
Definition at line 57 of file Lavieville.C.
Member Function Documentation
TypeName()
TypeName ("Lavieville")
fLiquid()
Foam::tmp< Foam::scalarField > fLiquid (const scalarField & alphaLiquid) const virtual
Implements partitioningModel.
Definition at line 65 of file Lavieville.C.
References Foam::exp(), Foam::neg(), Foam::pos0(), and Foam::pow().
write()
void write (Ostream & os) const virtual
Reimplemented from partitioningModel.
Definition at line 83 of file Lavieville.C.
References os(), and partitioningModel::write().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/wallBoilingSubModels/partitioningModels/Lavieville/Lavieville.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/wallBoilingSubModels/partitioningModels/Lavieville/Lavieville.C