OpenFOAM: linearAxialAngularSpring Class Reference
linearAxialAngularSpring Class Reference
sixDoFRigidBodyMotionRestraints model. Linear axial angular spring.
#include <linearAxialAngularSpring.H>
Public Member Functions
TypeName ("linearAxialAngularSpring")
linearAxialAngularSpring (const word &name, const dictionary &sDoFRBMRDict)
virtual autoPtr< sixDoFRigidBodyMotionRestraint > clone () const
virtual ~linearAxialAngularSpring ()
virtual void restrain (const sixDoFRigidBodyMotion &motion, vector &restraintPosition, vector &restraintForce, vector &restraintMoment) const
virtual bool read (const dictionary &sDoFRBMRCoeff)
virtual void write (Ostream &) const
Public Member Functions inherited from sixDoFRigidBodyMotionRestraint
TypeName ("sixDoFRigidBodyMotionRestraint")
declareRunTimeSelectionTable (autoPtr, sixDoFRigidBodyMotionRestraint, dictionary,(const word &name, const dictionary &sDoFRBMRDict),(name, sDoFRBMRDict))
sixDoFRigidBodyMotionRestraint (const word &name, const dictionary &sDoFRBMRDict)
virtual ~sixDoFRigidBodyMotionRestraint ()
const word & name () const
const dictionary & coeffDict () const
Additional Inherited Members
Static Public Member Functions inherited from sixDoFRigidBodyMotionRestraint
static autoPtr< sixDoFRigidBodyMotionRestraint > New (const word &name, const dictionary &sDoFRBMRDict)
Protected Attributes inherited from sixDoFRigidBodyMotionRestraint
word name_
dictionary sDoFRBMRCoeffs_
Detailed Description
sixDoFRigidBodyMotionRestraints model. Linear axial angular spring.
Source files
linearAxialAngularSpring.H
linearAxialAngularSpring.C
Definition at line 51 of file linearAxialAngularSpring.H.
Constructor & Destructor Documentation
linearAxialAngularSpring()
linearAxialAngularSpring (const word & name, const dictionary & sDoFRBMRDict)
Definition at line 47 of file linearAxialAngularSpring.C.
References Foam::name(), and linearAxialAngularSpring::read().
~linearAxialAngularSpring()
~linearAxialAngularSpring () virtual
Definition at line 66 of file linearAxialAngularSpring.C.
Member Function Documentation
TypeName()
TypeName ("linearAxialAngularSpring")
clone()
virtual autoPtr< sixDoFRigidBodyMotionRestraint > clone () const inline virtual
Implements sixDoFRigidBodyMotionRestraint.
Definition at line 86 of file linearAxialAngularSpring.H.
restrain()
void restrain (const sixDoFRigidBodyMotion & motion, vector & restraintPosition, vector & restraintForce, vector & restraintMoment) const virtual
Implements sixDoFRigidBodyMotionRestraint.
Definition at line 74 of file linearAxialAngularSpring.C.
References Foam::acos(), sixDoFRigidBodyMotion::centreOfRotation(), Foam::endl(), Foam::Info, Foam::mag(), Foam::min(), sixDoFRigidBodyMotion::omega(), sixDoFRigidBodyMotion::orientation(), sixDoFRigidBodyMotion::report(), Foam::rotationTensor(), Foam::sign(), and Foam::Zero.
read()
bool read (const dictionary & sDoFRBMRCoeff) virtual
Reimplemented from sixDoFRigidBodyMotionRestraint.
Definition at line 140 of file linearAxialAngularSpring.C.
References Foam::abort(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::I, Foam::mag(), Foam::nl, sixDoFRigidBodyMotionRestraint::read(), and Foam::sqrt().
Referenced by linearAxialAngularSpring::linearAxialAngularSpring().
write()
void write (Ostream & os) const virtual
Implements sixDoFRigidBodyMotionRestraint.
Definition at line 180 of file linearAxialAngularSpring.C.
References os().
The documentation for this class was generated from the following files:
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/restraints/linearAxialAngularSpring/linearAxialAngularSpring.H
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/restraints/linearAxialAngularSpring/linearAxialAngularSpring.C