OpenFOAM: incompressibleAdjointVars Class Reference
incompressibleAdjointVars Class Reference
Class including all adjoint fields for incompressible flows.
#include <incompressibleAdjointVars.H>
Public Member Functions
TypeName ("incompressibleAdjointVars")
incompressibleAdjointVars (fvMesh &mesh, solverControl &SolverControl, objectiveManager &objManager, incompressibleVars &primalVars)
virtual ~incompressibleAdjointVars ()
const autoPtr< incompressibleAdjoint::adjointRASModel > & adjointTurbulence () const
autoPtr< incompressibleAdjoint::adjointRASModel > & adjointTurbulence ()
void resetMeanFields ()
void computeMeanFields ()
virtual void nullify ()
virtual void updatePrimalBasedQuantities ()
Public Member Functions inherited from incompressibleAdjointMeanFlowVars
TypeName ("incompressibleAdjointMeanFlowVars")
incompressibleAdjointMeanFlowVars (fvMesh &mesh, solverControl &SolverControl, incompressibleVars &primalVars)
virtual ~incompressibleAdjointMeanFlowVars ()=default
const incompressibleVars & primalVars () const
const volScalarField & pa () const
volScalarField & pa ()
const volVectorField & Ua () const
volVectorField & Ua ()
const surfaceScalarField & phia () const
surfaceScalarField & phia ()
const volScalarField & paInst () const
volScalarField & paInst ()
const volVectorField & UaInst () const
volVectorField & UaInst ()
const surfaceScalarField & phiaInst () const
surfaceScalarField & phiaInst ()
bool computeMeanFields () const
const solverControl & getSolverControl () const
Public Member Functions inherited from variablesSet
TypeName ("variablesSet")
variablesSet (fvMesh &mesh, const dictionary &dict)
virtual autoPtr< variablesSet > clone () const
virtual ~variablesSet ()=default
const word & solverName () const
bool useSolverNameForFields () const
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > allocateField (const fvMesh &mesh, const word &baseName, const word &solverName, const bool useSolverNameForFields)
template<class Type >
void renameTurbulenceField (GeometricField< Type, fvPatchField, volMesh > &baseField, const word &solverName)
tmp< surfaceScalarField > allocateFluxField (const fvMesh &mesh, const volVectorField &velocity, const word &baseName, const word &solverName, const bool useSolverNameForFields)
virtual void transfer (variablesSet &vars)
Protected Member Functions
incompressibleAdjointVars (const incompressibleAdjointVars &)
void operator= (const incompressibleAdjointVars &)
Protected Member Functions inherited from incompressibleAdjointMeanFlowVars
void setFields ()
void setMeanFields ()
Protected Member Functions inherited from variablesSet
template<class Type , template< class > class PatchField, class GeoMesh >
autoPtr< GeometricField< Type, PatchField, GeoMesh > > allocateRenamedField (const autoPtr< GeometricField< Type, PatchField, GeoMesh > > &bf)
template<class Type , template< class > class PatchField, class GeoMesh >
void swapAndRename (autoPtr< GeometricField< Type, PatchField, GeoMesh > > &p1, autoPtr< GeometricField< Type, PatchField, GeoMesh > > &p2)
Protected Attributes
objectiveManager & objectiveManager_
autoPtr< incompressibleAdjoint::adjointRASModel > adjointTurbulence_
Protected Attributes inherited from incompressibleAdjointMeanFlowVars
solverControl & solverControl_
incompressibleVars & primalVars_
autoPtr< volScalarField > paPtr_
autoPtr< volVectorField > UaPtr_
autoPtr< surfaceScalarField > phiaPtr_
autoPtr< volScalarField > paMeanPtr_
autoPtr< volVectorField > UaMeanPtr_
autoPtr< surfaceScalarField > phiaMeanPtr_
Protected Attributes inherited from variablesSet
fvMesh & mesh_
word solverName_
bool useSolverNameForFields_
Additional Inherited Members
Static Public Member Functions inherited from variablesSet
template<class Type >
static void setField (autoPtr< GeometricField< Type, fvPatchField, volMesh > > &fieldPtr, const fvMesh &mesh, const word &baseName, const word &solverName, const bool useSolverNameForFields)
static void setFluxField (autoPtr< surfaceScalarField > &fieldPtr, const fvMesh &mesh, const volVectorField &velocity, const word &baseName, const word &solverName, const bool useSolverNameForFields)
static tmp< volVectorField > autoCreateMeshMovementField (const fvMesh &mesh, const word &name, const dimensionSet &dims)
template<class Type , template< class > class PatchField, class GeoMesh >
static void nullifyField (GeometricField< Type, PatchField, GeoMesh > &fieldPtr)
Detailed Description
Class including all adjoint fields for incompressible flows.
Definition at line 46 of file incompressibleAdjointVars.H.
Constructor & Destructor Documentation
incompressibleAdjointVars() [1/2]
incompressibleAdjointVars (const incompressibleAdjointVars &) protected
incompressibleAdjointVars() [2/2]
incompressibleAdjointVars (fvMesh & mesh, solverControl & SolverControl, objectiveManager & objManager, incompressibleVars & primalVars)
Definition at line 38 of file incompressibleAdjointVars.C.
~incompressibleAdjointVars()
virtual ~incompressibleAdjointVars () inline virtual
Definition at line 92 of file incompressibleAdjointVars.H.
Member Function Documentation
operator=()
void operator= (const incompressibleAdjointVars &) protected
TypeName()
TypeName ("incompressibleAdjointVars")
adjointTurbulence() [1/2]
const Foam::autoPtr< Foam::incompressibleAdjoint::adjointRASModel > & adjointTurbulence () const inline
Definition at line 25 of file incompressibleAdjointVarsI.H.
References incompressibleAdjointVars::adjointTurbulence_.
Referenced by sensitivitySurface::accumulateIntegrand(), sensitivitySurfacePoints::accumulateIntegrand(), shapeSensitivities::dvdbMult(), FIBase::read(), sensitivitySurface::read(), and sensitivitySurfacePoints::read().
adjointTurbulence() [2/2]
Foam::autoPtr< Foam::incompressibleAdjoint::adjointRASModel > & adjointTurbulence () inline
Definition at line 32 of file incompressibleAdjointVarsI.H.
resetMeanFields()
void resetMeanFields ()
Definition at line 63 of file incompressibleAdjointVars.C.
References incompressibleAdjointVars::adjointTurbulence_, solverControl::average(), solverControl::averageIter(), Foam::endl(), Foam::Info, incompressibleAdjointMeanFlowVars::paMeanPtr_, incompressibleAdjointMeanFlowVars::paPtr_, incompressibleAdjointMeanFlowVars::phiaMeanPtr_, incompressibleAdjointMeanFlowVars::phiaPtr_, incompressibleAdjointMeanFlowVars::solverControl_, incompressibleAdjointMeanFlowVars::UaMeanPtr_, incompressibleAdjointMeanFlowVars::UaPtr_, and Foam::Zero.
computeMeanFields()
void computeMeanFields ()
Definition at line 81 of file incompressibleAdjointVars.C.
References incompressibleAdjointVars::adjointTurbulence_, solverControl::averageIter(), solverControl::doAverageIter(), Foam::endl(), Foam::Info, incompressibleAdjointMeanFlowVars::paMeanPtr_, incompressibleAdjointMeanFlowVars::paPtr_, incompressibleAdjointMeanFlowVars::phiaMeanPtr_, incompressibleAdjointMeanFlowVars::phiaPtr_, incompressibleAdjointMeanFlowVars::solverControl_, incompressibleAdjointMeanFlowVars::UaMeanPtr_, and incompressibleAdjointMeanFlowVars::UaPtr_.
nullify()
void nullify () virtual
Reimplemented from incompressibleAdjointMeanFlowVars.
Definition at line 99 of file incompressibleAdjointVars.C.
References incompressibleAdjointVars::adjointTurbulence_, and incompressibleAdjointMeanFlowVars::nullify().
updatePrimalBasedQuantities()
void updatePrimalBasedQuantities () virtual
Definition at line 106 of file incompressibleAdjointVars.C.
Member Data Documentation
objectiveManager_
objectiveManager& objectiveManager_ protected
Definition at line 55 of file incompressibleAdjointVars.H.
adjointTurbulence_
autoPtr<incompressibleAdjoint::adjointRASModel> adjointTurbulence_ protected
Definition at line 58 of file incompressibleAdjointVars.H.
Referenced by incompressibleAdjointVars::adjointTurbulence(), incompressibleAdjointVars::computeMeanFields(), incompressibleAdjointVars::nullify(), and incompressibleAdjointVars::resetMeanFields().
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/solvers/variablesSet/incompressibleAdjoint/incompressibleAdjointVars.H
src/optimisation/adjointOptimisation/adjoint/solvers/variablesSet/incompressibleAdjoint/incompressibleAdjointVars.C
src/optimisation/adjointOptimisation/adjoint/solvers/variablesSet/incompressibleAdjoint/incompressibleAdjointVarsI.H