OpenFOAM: fieldSmoother Class Reference
fieldSmoother Class Reference
Utility functions for mesh motion solvers.
#include <fieldSmoother.H>
Public Member Functions
TypeName ("fieldSmoother")
fieldSmoother (const polyMesh &)
virtual ~fieldSmoother ()
void smoothNormals (const label nIter, const bitSet &isMeshMasterPoint, const bitSet &isMeshMasterEdge, const labelList &fixedPoints, pointVectorField &normals) const
void smoothPatchNormals (const label nIter, const bitSet &isPatchMasterPoint, const bitSet &isPatchMasterEdge, const indirectPrimitivePatch &adaptPatch, pointField &normals) const
template<class Type >
void minSmoothField (const label nIter, const bitSet &isPatchMasterPoint, const bitSet &isPatchMasterEdge, const indirectPrimitivePatch &adaptPatch, const scalarField &fieldMin, Field< Type > &field) const
void smoothLambdaMuDisplacement (const label nIter, const bitSet &isMeshMasterPoint, const bitSet &isMeshMasterEdge, const bitSet &isSmoothable, vectorField &displacement) const
Detailed Description
Utility functions for mesh motion solvers.
Source files
fieldSmoother.H
fieldSmoother.C
Definition at line 46 of file fieldSmoother.H.
Constructor & Destructor Documentation
fieldSmoother()
fieldSmoother (const polyMesh & mesh)
Definition at line 33 of file fieldSmoother.C.
~fieldSmoother()
~fieldSmoother () virtual
Definition at line 41 of file fieldSmoother.C.
Member Function Documentation
TypeName()
TypeName ("fieldSmoother")
smoothNormals()
void smoothNormals (const label nIter, const bitSet & isMeshMasterPoint, const bitSet & isMeshMasterEdge, const labelList & fixedPoints, pointVectorField & normals) const
Definition at line 47 of file fieldSmoother.C.
References Foam::average(), meshRefinement::calculateEdgeWeights(), Foam::endl(), forAll, meshRefinement::gAverage(), Foam::identity(), Foam::Info, Foam::mag(), Foam::normalised(), PtrList< T >::set(), UList< T >::size(), syncTools::syncPointList(), UPtrList< T >::test(), and meshRefinement::weightedSum().
smoothPatchNormals()
void smoothPatchNormals (const label nIter, const bitSet & isPatchMasterPoint, const bitSet & isPatchMasterEdge, const indirectPrimitivePatch & adaptPatch, pointField & normals) const
Definition at line 134 of file fieldSmoother.C.
References Foam::average(), meshRefinement::calculateEdgeWeights(), Foam::endl(), forAll, meshRefinement::gAverage(), Foam::Info, Foam::mag(), Foam::normalised(), UList< T >::size(), and meshRefinement::weightedSum().
minSmoothField()
template<class Type > void minSmoothField (const label nIter, const bitSet & isPatchMasterPoint, const bitSet & isPatchMasterEdge, const indirectPrimitivePatch & adaptPatch, const scalarField & fieldMin, Field< Type > & field) const
Definition at line 24 of file fieldSmootherTemplates.C.
References Foam::average(), meshRefinement::calculateEdgeWeights(), Foam::endl(), field(), forAll, meshRefinement::gAverage(), Foam::Info, Foam::mag(), UList< T >::size(), and meshRefinement::weightedSum().
smoothLambdaMuDisplacement()
void smoothLambdaMuDisplacement (const label nIter, const bitSet & isMeshMasterPoint, const bitSet & isMeshMasterEdge, const bitSet & isSmoothable, vectorField & displacement) const
Definition at line 199 of file fieldSmoother.C.
References Foam::average(), meshRefinement::calculateEdgeWeights(), Foam::endl(), forAll, meshRefinement::gAverage(), Foam::identity(), Foam::Info, lambda(), Foam::mag(), mu, UList< T >::size(), UPtrList< T >::test(), and meshRefinement::weightedSum().
The documentation for this class was generated from the following files:
src/mesh/snappyHexMesh/externalDisplacementMeshMover/fieldSmoother/fieldSmoother.H
src/mesh/snappyHexMesh/externalDisplacementMeshMover/fieldSmoother/fieldSmoother.C
src/mesh/snappyHexMesh/externalDisplacementMeshMover/fieldSmoother/fieldSmootherTemplates.C