OpenFOAM: createShellMesh Class Reference
createShellMesh Class Reference
Creates mesh by extruding a patch.
#include <createShellMesh.H>
Public Member Functions
ClassName ("createShellMesh")
createShellMesh (const primitiveFacePatch &patch, const faceList &pointRegions, const labelList &regionPoints)
const labelList & cellToFaceMap () const
const labelList & faceToFaceMap () const
const labelList & faceToEdgeMap () const
const labelList & pointToPointMap () const
void setRefinement (const pointField &firstLayerThickness, const scalar expansionRatio, const label nLayers, const labelList &topPatchID, const labelList &bottomPatchID, const labelListList &extrudeEdgePatches, polyTopoChange &meshMod)
void updateMesh (const mapPolyMesh &)
Static Public Member Functions
static void calcPointRegions (const globalMeshData &globalData, const primitiveFacePatch &patch, const bitSet &nonManifoldEdge, const bool syncNonCollocated, faceList &pointGlobalRegions, faceList &pointLocalRegions, labelList &localToGlobalRegion)
Detailed Description
Creates mesh by extruding a patch.
Source files
createShellMesh.H
createShellMesh.C
Extrudes into thickness direction.
bottom faces originate from reversed original faces (have turning index)
top faces originate from original faces (no turning index)
Definition at line 57 of file createShellMesh.H.
Constructor & Destructor Documentation
createShellMesh()
createShellMesh (const primitiveFacePatch & patch, const faceList & pointRegions, const labelList & regionPoints)
Definition at line 416 of file createShellMesh.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, UPtrList< T >::size(), and UList< T >::size().
Member Function Documentation
ClassName()
ClassName ("createShellMesh")
cellToFaceMap()
const labelList & cellToFaceMap () const inline
Definition at line 126 of file createShellMesh.H.
faceToFaceMap()
const labelList & faceToFaceMap () const inline
Definition at line 137 of file createShellMesh.H.
faceToEdgeMap()
const labelList & faceToEdgeMap () const inline
Definition at line 143 of file createShellMesh.H.
pointToPointMap()
const labelList & pointToPointMap () const inline
Definition at line 149 of file createShellMesh.H.
calcPointRegions()
void calcPointRegions (const globalMeshData & globalData, const primitiveFacePatch & patch, const bitSet & nonManifoldEdge, const bool syncNonCollocated, faceList & pointGlobalRegions, faceList & pointLocalRegions, labelList & localToGlobalRegion) static
Definition at line 149 of file createShellMesh.C.
References PtrList< T >::append(), PtrList< T >::clear(), globalMeshData::coupledPatch(), e, UPtrList< T >::empty(), f(), UList< T >::find(), forAll, Foam::labelMax, PatchTools::matchEdges(), Foam::returnReduceAnd(), PtrList< T >::set(), PtrList< T >::setSize(), UPtrList< T >::size(), UList< T >::size(), and PtrList< T >::transfer().
setRefinement()
void setRefinement (const pointField & firstLayerThickness, const scalar expansionRatio, const label nLayers, const labelList & topPatchID, const labelList & bottomPatchID, const labelListList & extrudeEdgePatches, polyTopoChange & meshMod)
Definition at line 439 of file createShellMesh.C.
References polyTopoChange::addCell(), polyTopoChange::addFace(), polyTopoChange::addPoint(), PtrList< T >::append(), e, Foam::exit(), f(), Foam::FatalError, FatalErrorInFunction, UList< T >::fcIndex(), UList< T >::find(), forAll, UPtrList< T >::last(), UList< T >::rcIndex(), UPtrList< T >::size(), UList< T >::size(), and PtrList< T >::transfer().
updateMesh()
void updateMesh (const mapPolyMesh & map)
Definition at line 900 of file createShellMesh.C.
References Foam::inplaceReorder(), mapPolyMesh::reverseCellMap(), mapPolyMesh::reverseFaceMap(), and mapPolyMesh::reversePointMap().
The documentation for this class was generated from the following files:
src/dynamicMesh/createShellMesh/createShellMesh.H
src/dynamicMesh/createShellMesh/createShellMesh.C