OpenFOAM: WLFTransport< Thermo > Class Template Reference
WLFTransport< Thermo > Class Template Reference
Transport package using the Williams-Landel-Ferry model.
#include <WLFTransport.H>
Public Member Functions
WLFTransport (const word &, const WLFTransport &)
WLFTransport (const dictionary &dict)
autoPtr< WLFTransport > clone () const
scalar mu (const scalar p, const scalar T) const
scalar kappa (const scalar p, const scalar T) const
scalar alphah (const scalar p, const scalar T) const
void write (Ostream &os) const
void operator+= (const WLFTransport &)
void operator*= (const scalar)
Static Public Member Functions
static autoPtr< WLFTransport > New (const dictionary &dict)
static word typeName ()
Friends
WLFTransport operator+ (const WLFTransport &, const WLFTransport &)
WLFTransport operator* (const scalar, const WLFTransport &)
Ostream & operator<< (Ostream &, const WLFTransport &)
Detailed Description
template<class Thermo>
class Foam::WLFTransport< Thermo >
Transport package using the Williams-Landel-Ferry model.
Templated into a given thermodynamics package (needed for thermal conductivity).
Dynamic viscosity [kg/m.s]
References:
    Williams, M. L., Landel, R. F., & Ferry, J. D. (1955).
    The temperature dependence of relaxation mechanisms
    in amorphous polymers and other glass-forming liquids.
    Journal of the American Chemical society, 77(14), 3701-3707.
Source files
WLFTransport.H
WLFTransportI.H
WLFTransport.C
Definition at line 89 of file WLFTransport.H.
Constructor & Destructor Documentation
WLFTransport() [1/2]
template<class Thermo > WLFTransport (const word & name, const WLFTransport< Thermo > & wlft) inline
Definition at line 26 of file WLFTransportI.H.
References Foam::name().
WLFTransport() [2/2]
template<class Thermo > WLFTransport (const dictionary & dict) explicit
Definition at line 28 of file WLFTransport.C.
Member Function Documentation
clone()
template<class Thermo > Foam::autoPtr< Foam::WLFTransport< Thermo > > clone () const inline
Definition at line 43 of file WLFTransportI.H.
New()
template<class Thermo > Foam::autoPtr< Foam::WLFTransport< Thermo > > New (const dictionary & dict) inline static
Definition at line 54 of file WLFTransportI.H.
References dict.
typeName()
template<class Thermo > static word typeName () inline static
Definition at line 143 of file WLFTransport.H.
mu()
template<class Thermo > Foam::scalar mu (const scalar p, const scalar T) const inline
Definition at line 69 of file WLFTransportI.H.
References Foam::exp(), and T.
kappa()
template<class Thermo > Foam::scalar kappa (const scalar p, const scalar T) const inline
Definition at line 80 of file WLFTransportI.H.
References Cp, mu, p, and T.
alphah()
template<class Thermo > Foam::scalar alphah (const scalar p, const scalar T) const inline
Definition at line 90 of file WLFTransportI.H.
References mu, p, and T.
write()
template<class Thermo > void write (Ostream & os) const
Definition at line 42 of file WLFTransport.C.
References Ostream::beginBlock(), Ostream::endBlock(), specie::name(), os(), and Ostream::writeEntry().
operator+=()
template<class Thermo > void operator+= (const WLFTransport< Thermo > &) inline
Definition at line 104 of file WLFTransportI.H.
References Foam::mag(), and Y.
operator*=()
template<class Thermo > void operator*= (const scalar s) inline
Definition at line 128 of file WLFTransportI.H.
References s().
Friends And Related Symbol Documentation
operator+
template<class Thermo > WLFTransport operator+ (const WLFTransport< Thermo > & , const WLFTransport< Thermo > &) friend
operator*
template<class Thermo > WLFTransport operator* (const scalar , const WLFTransport< Thermo > &) friend
operator<<
template<class Thermo > Ostream & operator<< (Ostream & , const WLFTransport< Thermo > &) friend
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/transport/WLF/WLFTransport.H
src/thermophysicalModels/specie/transport/WLF/WLFTransport.C
src/thermophysicalModels/specie/transport/WLF/WLFTransportI.H