OpenFOAM: labelledTri Class Reference
labelledTri Class Reference
A triFace with additional (region) index.
#include <labelledTri.H>
Public Member Functions
labelledTri ()
labelledTri (const triFace &tri, const label region=0)
labelledTri (const label p0, const label p1, const label p2, const label region=0)
labelledTri (const labelUList &list)
labelledTri (std::initializer_list< label >)
labelledTri (const labelUList &list, const FixedList< label, 3 > &triIndices, const label region=0)
labelledTri (const labelUList &list, const labelledTri &triIndices)
labelledTri (Istream &is)
label index () const noexcept
label & index () noexcept
void setIndex (const label idx) noexcept
label region () const noexcept
label & region () noexcept
Public Member Functions inherited from triFace
void front ()=delete
void back ()=delete
triFace ()
triFace (const label p0, const label p1, const label p2) noexcept
triFace (std::initializer_list< label > list)
triFace (const labelUList &list)
triFace (const labelUList &list, const FixedList< label, 3 > &indices)
triFace (Istream &is)
label a () const noexcept
label b () const noexcept
label c () const noexcept
label & a () noexcept
label & b () noexcept
label & c () noexcept
bool good () const noexcept
label collapse ()
void flip ()
pointField points (const UList< point > &pts) const
face triFaceFace () const
triPointRef tri (const UList< point > &points) const
point centre (const UList< point > &points) const
template<class Type >
Type average (const UList< point > &unused, const Field< Type > &fld) const
vector areaNormal (const UList< point > &points) const
vector unitNormal (const UList< point > &points) const
FOAM_DEPRECATED_FOR (2018-12, "areaNormal() or unitNormal()") vector normal(const UList< point > &points) const
scalar mag (const UList< point > &points) const
Pair< point > box (const UList< point > &points) const
label nTriangles () const noexcept
triFace reverseFace () const
label which (const label vertex) const
label nextLabel (const label i) const
label prevLabel (const label i) const
label thisLabel (const label i) const
scalar sweptVol (const UList< point > &opts, const UList< point > &npts) const
tensor inertia (const UList< point > &points, const point &refPt=vector::zero, scalar density=1.0) const
pointHit ray (const point &p, const vector &q, const UList< point > &points, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction dir=intersection::VECTOR) const
pointHit intersection (const point &p, const vector &q, const UList< point > &points, const intersection::algorithm alg, const scalar tol=0.0) const
pointHit intersection (const point &p, const vector &q, const point &ctr, const UList< point > &points, const intersection::algorithm alg, const scalar tol=0.0) const
pointHit nearestPoint (const point &p, const UList< point > &points) const
pointHit nearestPointClassify (const point &p, const UList< point > &points, label &nearType, label &nearLabel) const
int sign (const point &p, const UList< point > &points, const scalar tol=SMALL) const
label nEdges () const noexcept
Foam::edge edge (const label edgei) const
vector edge (const label edgei, const UList< point > &pts) const
Foam::edge rcEdge (const label edgei) const
vector rcEdge (const label edgei, const UList< point > &pts) const
edgeList edges () const
edgeList rcEdges () const
int edgeDirection (const Foam::edge &e) const
void operator+= (const label vertexOffset)
unsigned hash_code (unsigned seed=0) const
bool valid () const noexcept
Foam::edge faceEdge (label edgei) const
Public Member Functions inherited from FixedList< label, 3 >
void writeEntry (const word &keyword, Ostream &os) const
FixedList ()=default
FixedList (const label &val)
FixedList (const Foam::zero)
FixedList (const label list[N])
FixedList (const FixedList< label, N > &list)
FixedList (FixedList< label, N > &&list)
FixedList (std::initializer_list< label > list)
FixedList (const UList< label > &list)
FixedList (const FixedList< label, AnyNum > &list, const FixedList< label, N > &indices)
FixedList (const UList< label > &list, const FixedList< label, N > &indices)
FixedList (const SLList< label > &list)
FixedList (Istream &is)
autoPtr< FixedList< label, N > > clone () const
const label * cdata () const noexcept
label * data () noexcept
const char * cdata_bytes () const noexcept
char * data_bytes () noexcept
label & get () noexcept
const label & get () const noexcept
label & front () noexcept
const label & front () const noexcept
label & back () noexcept
const label & back () const noexcept
label fcIndex (const label i) const
const label & fcValue (const label i) const
label & fcValue (const label i)
label rcIndex (const label i) const
const label & rcValue (const label i) const
label & rcValue (const label i)
void checkStart (const label start) const
void checkSize (const label size) const
void checkIndex (const label i) const
bool uniform () const
label find (const label &val, label pos=0) const
label rfind (const label &val, label pos=-1) const
bool contains (const label &val, label pos=0) const
void resize (const label n)
void resize_nocopy (const label n)
void setSize (const label n)
void fill (const label &val)
void fill (const Foam::zero)
void moveFirst (const label i)
void moveLast (const label i)
void swapFirst (const label i)
void swapLast (const label i)
void transfer (FixedList< label, N > &list)
label & operator[] (const label i)
const label & operator[] (const label i) const
void operator= (const label list[N])
void operator= (const UList< label > &list)
void operator= (const SLList< label > &list)
void operator= (std::initializer_list< label > list)
void operator= (const label &val)
void operator= (const Foam::zero)
void operator= (const FixedList< label, N > &list)
void operator= (FixedList< label, N > &&list)
iterator begin () noexcept
const_iterator begin () const noexcept
iterator end () noexcept
const_iterator end () const noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
const_reverse_iterator crbegin () const
const_reverse_iterator crend () const
void swap (FixedList< label, N > &other)
bool operator== (const FixedList< label, N > &list) const
bool operator!= (const FixedList< label, N > &list) const
bool operator< (const FixedList< label, N > &list) const
bool operator> (const FixedList< label, N > &list) const
bool operator<= (const FixedList< label, N > &list) const
bool operator>= (const FixedList< label, N > &list) const
Istream & readList (Istream &is)
Ostream & writeList (Ostream &os, const label shortLen=0) const
label & first () noexcept
const label & first () const noexcept
label & last () noexcept
const label & last () const noexcept
bool found (const label &val, label pos=0) const
Friends
Istream & operator>> (Istream &, labelledTri &)
Ostream & operator<< (Ostream &, const labelledTri &)
Additional Inherited Members
Public Types inherited from FixedList< label, 3 >
typedef label value_type
typedef label * pointer
typedef const label * const_pointer
typedef label & reference
typedef const label & const_reference
typedef label * iterator
typedef const label * const_iterator
typedef label size_type
typedef label difference_type
typedef std::reverse_iterator< iterator > reverse_iterator
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
Static Public Member Functions inherited from triFace
static int compare (const triFace &a, const triFace &b)
Static Public Member Functions inherited from FixedList< label, 3 >
static const FixedList< label, N > & null ()
static std::streamsize size_bytes () noexcept
static std::streamsize byteSize ()
static constexpr bool empty () noexcept
static constexpr label size () noexcept
static constexpr unsigned max_size () noexcept
Protected Member Functions inherited from FixedList< label, 3 >
void writeEntry (Ostream &os) const
Detailed Description
A triFace with additional (region) index.
Source files
labelledTri.H
labelledTriI.H
Definition at line 53 of file labelledTri.H.
Constructor & Destructor Documentation
labelledTri() [1/8]
labelledTri () inline
Definition at line 53 of file labelledTriI.H.
labelledTri() [2/8]
labelledTri (const triFace & tri, const label region = 0) inline
Definition at line 60 of file labelledTriI.H.
labelledTri() [3/8]
labelledTri (const label p0, const label p1, const label p2, const label region = 0) inline
Definition at line 71 of file labelledTriI.H.
labelledTri() [4/8]
labelledTri (const labelUList & list) inline explicit
Definition at line 84 of file labelledTriI.H.
labelledTri() [5/8]
labelledTri (std::initializer_list< label > list) inline explicit
Definition at line 93 of file labelledTriI.H.
labelledTri() [6/8]
labelledTri (const labelUList & list, const FixedList< label, 3 > & triIndices, const label region = 0) inline
Definition at line 102 of file labelledTriI.H.
labelledTri() [7/8]
labelledTri (const labelUList & list, const labelledTri & triIndices) inline
Definition at line 114 of file labelledTriI.H.
labelledTri() [8/8]
labelledTri (Istream & is) inline
Definition at line 125 of file labelledTriI.H.
References Foam::operator>>().
Member Function Documentation
index() [1/2]
label index () const inline noexcept
Definition at line 125 of file labelledTri.H.
Referenced by Foam::operator<<(), and Foam::operator>>().
index() [2/2]
label & index () inline noexcept
Definition at line 131 of file labelledTri.H.
setIndex()
void setIndex (const label idx) inline noexcept
Definition at line 137 of file labelledTri.H.
region() [1/2]
label region () const inline noexcept
Definition at line 143 of file labelledTri.H.
Referenced by booleanSurface::booleanSurface(), and boundaryMesh::readTriSurface().
region() [2/2]
label & region () inline noexcept
Definition at line 149 of file labelledTri.H.
Friends And Related Symbol Documentation
operator>>
Istream & operator>> (Istream & , labelledTri &) friend
operator<<
Ostream & operator<< (Ostream & , const labelledTri &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/meshShapes/labelledTri/labelledTri.H
src/OpenFOAM/meshes/meshShapes/labelledTri/labelledTriI.H