OpenFOAM: curvatureSeparation Class Reference
curvatureSeparation Class Reference
Curvature film separation model.
#include <curvatureSeparation.H>
Public Member Functions
TypeName ("curvatureSeparation")
curvatureSeparation (liquidFilmBase &film, const dictionary &dict)
virtual ~curvatureSeparation ()=default
virtual void correct (scalarField &availableMass, scalarField &massToInject, scalarField &diameterToInject)
Public Member Functions inherited from injectionModel
TypeName ("injectionModel")
declareRunTimeSelectionTable (autoPtr, injectionModel, dictionary,(liquidFilmBase &film, const dictionary &dict),(film, dict))
injectionModel (liquidFilmBase &film)
injectionModel (const word &modelType, liquidFilmBase &film, const dictionary &dict)
virtual ~injectionModel ()
virtual scalar injectedMassTotal () const
virtual void patchInjectedMassTotals (scalar &patchMasses) const
Public Member Functions inherited from filmSubModelBase
filmSubModelBase (liquidFilmBase &film)
filmSubModelBase (liquidFilmBase &film, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
filmSubModelBase (const word &modelName, liquidFilmBase &film, const dictionary &dict, const word &baseName, const word &modelType)
virtual ~filmSubModelBase ()
virtual bool writeTime () const
const liquidFilmBase & film () const
liquidFilmBase & film ()
template<class FilmType >
const FilmType & filmType () const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
subModelBase (const subModelBase &smb)
virtual ~subModelBase ()=default
const word & modelName () const
const dictionary & dict () const
const word & baseName () const
const word & modelType () const
const dictionary & coeffDict () const
const dictionary & properties () const
virtual bool defaultCoeffs (const bool printMsg) const
virtual bool active () const
virtual void cacheFields (const bool store)
virtual fileName localPath () const
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
bool getModelDict (const word &entryName, dictionary &dict) const
template<class Type >
bool getModelProperty (const word &entryName, Type &value) const
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
virtual void write (Ostream &os) const
Protected Member Functions
tmp< areaScalarField > calcInvR1 (const areaVectorField &U, const scalarField &calcCosAngle) const
tmp< scalarField > calcCosAngle (const edgeScalarField &phi) const
Protected Member Functions inherited from injectionModel
void addToInjectedMass (const scalar dMass)
void correct ()
Protected Member Functions inherited from subModelBase
bool inLine () const
Protected Attributes
areaTensorField gradNHat_
scalar deltaByR1Min_
scalar definedPatchRadii_
scalar magG_
vector gHat_
scalar fThreshold_
scalar minInvR1_
Protected Attributes inherited from filmSubModelBase
liquidFilmBase & filmModel_
Protected Attributes inherited from subModelBase
const word modelName_
dictionary & properties_
const dictionary dict_
const word baseName_
const word modelType_
const dictionary coeffDict_
Additional Inherited Members
Static Public Member Functions inherited from injectionModel
static autoPtr< injectionModel > New (liquidFilmBase &film, const dictionary &dict, const word &mdoelType)
Public Attributes inherited from subModelBase
bool log
Detailed Description
Curvature film separation model.
Assesses film curvature via the mesh geometry and calculates a force balance of the form:
F_sum = F_inertial + F_body + F_surface
If F_sum < 0, the film separates. Similarly, if F_sum > 0 the film will remain attached.
Based on description given by Owen and D. J. Ryley. The flow of thin liquid films around corners. International Journal of Multiphase Flow, 11(1):51-62, 1985.
Source files
curvatureSeparation.H
curvatureSeparation.C
Definition at line 64 of file curvatureSeparation.H.
Constructor & Destructor Documentation
curvatureSeparation()
curvatureSeparation (liquidFilmBase & film, const dictionary & dict)
Definition at line 150 of file curvatureSeparation.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, filmSubModelBase::film(), curvatureSeparation::gHat_, and curvatureSeparation::magG_.
~curvatureSeparation()
virtual ~curvatureSeparation () virtual default
Member Function Documentation
calcInvR1()
tmp< areaScalarField > calcInvR1 (const areaVectorField & U, const scalarField & calcCosAngle) const protected
Definition at line 49 of file curvatureSeparation.C.
References curvatureSeparation::definedPatchRadii_, Foam::dimVelocity, e, forAll, curvatureSeparation::gradNHat_, Foam::mag(), Foam::max(), and U.
Referenced by curvatureSeparation::calcCosAngle(), and curvatureSeparation::correct().
calcCosAngle()
tmp< scalarField > calcCosAngle (const edgeScalarField & phi) const protected
Definition at line 87 of file curvatureSeparation.C.
References curvatureSeparation::calcInvR1(), Foam::clamp(), Foam::dimless, Foam::dimVelocity, filmSubModelBase::film(), forAll, curvatureSeparation::gHat_, Foam::mag(), mesh, primitiveMesh::nFaces(), IOobjectOption::NO_READ, phi, Foam::pos(), UPtrList< T >::size(), fvMesh::time(), timeName, U, and Foam::Zero.
Referenced by curvatureSeparation::correct().
TypeName()
TypeName ("curvatureSeparation")
correct()
void correct (scalarField & availableMass, scalarField & massToInject, scalarField & diameterToInject) virtual
Implements injectionModel.
Definition at line 187 of file curvatureSeparation.C.
References injectionModel::addToInjectedMass(), curvatureSeparation::calcCosAngle(), curvatureSeparation::calcInvR1(), injectionModel::correct(), delta, curvatureSeparation::deltaByR1Min_, Foam::dimForce, Foam::dimLength, Foam::dimMass, filmSubModelBase::film(), forAll, curvatureSeparation::fThreshold_, Foam::inv(), curvatureSeparation::magG_, Foam::magSqr(), mesh, curvatureSeparation::minInvR1_, primitiveMesh::nFaces(), IOobjectOption::NO_READ, phi, rho, Foam::sqr(), Foam::sum(), fvMesh::time(), timeName, U, Uf, and Foam::Zero.
Member Data Documentation
gradNHat_
areaTensorField gradNHat_ protected
Definition at line 82 of file curvatureSeparation.H.
Referenced by curvatureSeparation::calcInvR1().
deltaByR1Min_
scalar deltaByR1Min_ protected
Definition at line 85 of file curvatureSeparation.H.
Referenced by curvatureSeparation::correct().
definedPatchRadii_
scalar definedPatchRadii_ protected
Definition at line 89 of file curvatureSeparation.H.
Referenced by curvatureSeparation::calcInvR1().
magG_
scalar magG_ protected
Definition at line 92 of file curvatureSeparation.H.
Referenced by curvatureSeparation::correct(), and curvatureSeparation::curvatureSeparation().
gHat_
vector gHat_ protected
Definition at line 95 of file curvatureSeparation.H.
Referenced by curvatureSeparation::calcCosAngle(), and curvatureSeparation::curvatureSeparation().
fThreshold_
scalar fThreshold_ protected
Definition at line 98 of file curvatureSeparation.H.
Referenced by curvatureSeparation::correct().
minInvR1_
scalar minInvR1_ protected
Definition at line 101 of file curvatureSeparation.H.
Referenced by curvatureSeparation::correct().
The documentation for this class was generated from the following files:
src/regionFaModels/liquidFilm/subModels/kinematic/injectionModel/curvatureSeparation/curvatureSeparation.H
src/regionFaModels/liquidFilm/subModels/kinematic/injectionModel/curvatureSeparation/curvatureSeparation.C