OpenFOAM: heheuPsiThermo< BasicPsiThermo, MixtureType > Class Template Reference
heheuPsiThermo< BasicPsiThermo, MixtureType > Class Template Reference
#include <heheuPsiThermo.H>
Public Member Functions
TypeName ("heheuPsiThermo")
heheuPsiThermo (const fvMesh &, const word &phaseName)
heheuPsiThermo (const fvMesh &, const word &phaseName, const word &dictName)
virtual ~heheuPsiThermo ()
virtual void correct ()
virtual volScalarField & heu ()
virtual const volScalarField & heu () const
virtual const volScalarField & Tu () const
virtual tmp< scalarField > heu (const scalarField &p, const scalarField &T, const labelList &cells) const
virtual tmp< scalarField > heu (const scalarField &p, const scalarField &T, const label patchi) const
virtual tmp< volScalarField > Tb () const
virtual tmp< volScalarField > psiu () const
virtual tmp< volScalarField > psib () const
virtual tmp< volScalarField > muu () const
virtual tmp< volScalarField > mub () const
Public Member Functions inherited from heThermo< BasicPsiThermo, MixtureType >
heThermo (const fvMesh &, const word &phaseName)
heThermo (const fvMesh &, const dictionary &, const word &phaseName)
heThermo (const fvMesh &, const word &phaseName, const word &dictionaryName)
virtual ~heThermo ()
virtual MixtureType::basicMixtureType & composition ()
virtual const MixtureType::basicMixtureType & composition () const
virtual word thermoName () const
virtual bool incompressible () const
virtual bool isochoric () const
virtual volScalarField & he ()
virtual const volScalarField & he () const
virtual tmp< volScalarField > he (const volScalarField &p, const volScalarField &T) const
virtual tmp< scalarField > he (const scalarField &p, const scalarField &T, const labelList &cells) const
virtual tmp< scalarField > he (const scalarField &p, const scalarField &T, const label patchi) const
virtual tmp< volScalarField > hc () const
virtual tmp< scalarField > THE (const scalarField &he, const scalarField &p, const scalarField &T0, const labelList &cells) const
virtual tmp< scalarField > THE (const scalarField &he, const scalarField &p, const scalarField &T0, const label patchi) const
virtual tmp< scalarField > Cp (const scalarField &p, const scalarField &T, const label patchi) const
virtual tmp< scalarField > Cp (const scalarField &p, const scalarField &T, const labelList &cells) const
virtual tmp< volScalarField > Cp () const
virtual tmp< scalarField > Cv (const scalarField &p, const scalarField &T, const label patchi) const
virtual tmp< volScalarField > Cv () const
virtual tmp< scalarField > rhoEoS (const scalarField &p, const scalarField &T, const labelList &cells) const
virtual tmp< volScalarField > gamma () const
virtual tmp< scalarField > gamma (const scalarField &p, const scalarField &T, const label patchi) const
virtual tmp< scalarField > Cpv (const scalarField &p, const scalarField &T, const label patchi) const
virtual tmp< volScalarField > Cpv () const
virtual tmp< volScalarField > CpByCpv () const
virtual tmp< scalarField > CpByCpv (const scalarField &p, const scalarField &T, const label patchi) const
virtual tmp< volScalarField > W () const
virtual tmp< volScalarField > kappa () const
virtual tmp< scalarField > kappa (const label patchi) const
virtual tmp< volScalarField > alphahe () const
virtual tmp< scalarField > alphahe (const label patchi) const
virtual tmp< volScalarField > kappaEff (const volScalarField &) const
virtual tmp< scalarField > kappaEff (const scalarField &alphat, const label patchi) const
virtual tmp< volScalarField > alphaEff (const volScalarField &alphat) const
virtual tmp< scalarField > alphaEff (const scalarField &alphat, const label patchi) const
virtual bool read ()
Additional Inherited Members
Protected Member Functions inherited from heThermo< BasicPsiThermo, MixtureType >
void heBoundaryCorrection (volScalarField &he)
Protected Attributes inherited from heThermo< BasicPsiThermo, MixtureType >
volScalarField he_
Detailed Description
template<class BasicPsiThermo, class MixtureType>
class Foam::heheuPsiThermo< BasicPsiThermo, MixtureType >
Definition at line 48 of file heheuPsiThermo.H.
Constructor & Destructor Documentation
heheuPsiThermo() [1/2]
template<class BasicPsiThermo , class MixtureType > heheuPsiThermo (const fvMesh & mesh, const word & phaseName)
Definition at line 234 of file heheuPsiThermo.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), forAll, pp(), and GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef().
heheuPsiThermo() [2/2]
template<class BasicPsiThermo , class MixtureType > heheuPsiThermo (const fvMesh & mesh, const word & phaseName, const word & dictName)
Definition at line 308 of file heheuPsiThermo.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), forAll, pp(), and GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef().
~heheuPsiThermo()
template<class BasicPsiThermo , class MixtureType > ~heheuPsiThermo () virtual
Definition at line 385 of file heheuPsiThermo.C.
Member Function Documentation
TypeName()
template<class BasicPsiThermo , class MixtureType > TypeName ("heheuPsiThermo< BasicPsiThermo, MixtureType >")
correct()
template<class BasicPsiThermo , class MixtureType > void correct () virtual
Definition at line 392 of file heheuPsiThermo.C.
References DebugInfo, DebugInFunction, and Foam::endl().
heu() [1/4]
template<class BasicPsiThermo , class MixtureType > virtual volScalarField & heu () inline virtual
Definition at line 115 of file heheuPsiThermo.H.
heu() [2/4]
template<class BasicPsiThermo , class MixtureType > virtual const volScalarField & heu () const inline virtual
Definition at line 121 of file heheuPsiThermo.H.
Tu()
template<class BasicPsiThermo , class MixtureType > virtual const volScalarField & Tu () const inline virtual
Definition at line 127 of file heheuPsiThermo.H.
heu() [3/4]
template<class BasicPsiThermo , class MixtureType > Foam::tmp< Foam::scalarField > heu (const scalarField & p, const scalarField & T, const labelList & cells) const virtual
Definition at line 418 of file heheuPsiThermo.C.
References cells, forAll, p, and UList< T >::size().
heu() [4/4]
template<class BasicPsiThermo , class MixtureType > Foam::tmp< Foam::scalarField > heu (const scalarField & p, const scalarField & T, const label patchi) const virtual
Definition at line 439 of file heheuPsiThermo.C.
References forAll, p, and UList< T >::size().
Tb()
template<class BasicPsiThermo , class MixtureType > Foam::tmp< Foam::volScalarField > Tb () const virtual
Definition at line 461 of file heheuPsiThermo.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), forAll, IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, pp(), and GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef().
psiu()
template<class BasicPsiThermo , class MixtureType > Foam::tmp< Foam::volScalarField > psiu () const virtual
Definition at line 520 of file heheuPsiThermo.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), forAll, IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, pp(), and GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef().
psib()
template<class BasicPsiThermo , class MixtureType > Foam::tmp< Foam::volScalarField > psib () const virtual
Definition at line 574 of file heheuPsiThermo.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), forAll, IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, pp(), and GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef().
muu()
template<class BasicPsiThermo , class MixtureType > Foam::tmp< Foam::volScalarField > muu () const virtual
Definition at line 629 of file heheuPsiThermo.C.
References forAll, IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, and pp().
mub()
template<class BasicPsiThermo , class MixtureType > Foam::tmp< Foam::volScalarField > mub () const virtual
Definition at line 687 of file heheuPsiThermo.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), forAll, IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, and pp().
The documentation for this class was generated from the following files:
src/thermophysicalModels/reactionThermo/psiuReactionThermo/heheuPsiThermo.H
src/thermophysicalModels/reactionThermo/psiuReactionThermo/heheuPsiThermo.C