OpenFOAM: PstreamBuffers Class Reference
PstreamBuffers Class Reference
Buffers for inter-processor communications streams (UOPstream, UIPstream).
#include <PstreamBuffers.H>
Public Member Functions
PstreamBuffers (UPstream::commsTypes commsType=UPstream::commsTypes::nonBlocking, int tag=UPstream::msgType(), label communicator=UPstream::worldComm, IOstreamOption::streamFormat fmt=IOstreamOption::BINARY)
PstreamBuffers (label communicator, UPstream::commsTypes commsType=UPstream::commsTypes::nonBlocking, int tag=UPstream::msgType(), IOstreamOption::streamFormat fmt=IOstreamOption::BINARY)
PstreamBuffers (label communicator, int tag, UPstream::commsTypes commsType=UPstream::commsTypes::nonBlocking, IOstreamOption::streamFormat fmt=IOstreamOption::BINARY)
~PstreamBuffers ()
IOstreamOption::streamFormat format () const noexcept
UPstream::commsTypes commsType () const noexcept
int tag () const noexcept
label comm () const noexcept
label nProcs () const noexcept
UPstream::rangeType allProcs () const noexcept
UPstream::rangeType subProcs () const noexcept
bool finished () const noexcept
bool allowClearRecv () const noexcept
bool hasSendData () const
bool hasRecvData () const
label sendDataCount (const label proci) const
label recvDataCount (const label proci) const
labelList recvDataCounts () const
label maxRecvCount () const
label maxNonLocalRecvCount () const
label maxNonLocalRecvCount (const label excludeProci) const
const UList< char > peekRecvData (const label proci) const
void clear ()
void clearSends ()
void clearRecvs ()
void clearSend (const label proci)
void clearRecv (const label proci)
void clearStorage ()
bool allowClearRecv (bool on) noexcept
void finishedSends (const bool wait=true)
void finishedSends (labelList &recvSizes, const bool wait=true)
void finishedNeighbourSends (const labelUList &neighProcs, const bool wait=true)
void finishedNeighbourSends (const labelUList &neighProcs, labelList &recvSizes, const bool wait=true)
bool finishedSends (bitSet &sendConnections, DynamicList< label > &sendProcs, DynamicList< label > &recvProcs, const bool wait=true)
void finishedGathers (const bool wait=true)
void finishedGathers (labelList &recvSizes, const bool wait=true)
void finishedScatters (const bool wait=true)
void finishedScatters (labelList &recvSizes, const bool wait=true)
Static Public Attributes
static int algorithm
Friends
class UOPstreamBase
class UIPstreamBase
Detailed Description
Buffers for inter-processor communications streams (UOPstream, UIPstream).
Use UOPstream to stream data into buffers, call finishedSends() to notify that data is in buffers and then use IUPstream to get data out of received buffers. Works with both blocking and nonBlocking. Does not make much sense with scheduled since there you would not need these explicit buffers.
Example usage:
PstreamBuffers pBufs(UPstream::commsTypes::nonBlocking);
for (const int proci : UPstream::allProcs())
{
    if (proci != UPstream::myProcNo())
    {
        someObject vals;
        UOPstream send(proci, pBufs);
        send << vals;
    }
}
pBufs.finishedSends();   // no-op for blocking
for (const int proci : UPstream::allProcs())
{
    if (proci != UPstream::myProcNo())
    {
        UIPstream recv(proci, pBufs);
        someObject vals(recv);
    }
}
There are additional special versions of finishedSends() for restricted neighbour communication as well as for special one-to-all and all-to-one communication patterns. For example,
PstreamBuffers pBufs(UPstream::commsTypes::nonBlocking);
if (UPstream::master())
{
    someObject vals;
    for (const int proci : UPstream::subProcs())
    {
        UOPstream send(proci, pBufs);
        send << vals;
    }
}
pBufs.finishedScatters();
if (!UPstream::master())
{
    UIPstream recv(UPstream::masterNo(), pBufs);
    someObject vals(recv);
}
Source files
PstreamBuffers.H
PstreamBuffers.C
Definition at line 113 of file PstreamBuffers.H.
Constructor & Destructor Documentation
PstreamBuffers() [1/3]
PstreamBuffers (UPstream::commsTypes commsType = UPstream::commsTypes::nonBlocking, int tag = UPstream::msgType(), label communicator = UPstream::worldComm, IOstreamOption::streamFormat fmt = IOstreamOption::BINARY) explicit
Definition at line 281 of file PstreamBuffers.C.
PstreamBuffers() [2/3]
PstreamBuffers (label communicator, UPstream::commsTypes commsType = UPstream::commsTypes::nonBlocking, int tag = UPstream::msgType(), IOstreamOption::streamFormat fmt = IOstreamOption::BINARY) inline explicit
Definition at line 219 of file PstreamBuffers.H.
PstreamBuffers() [3/3]
PstreamBuffers (label communicator, int tag, UPstream::commsTypes commsType = UPstream::commsTypes::nonBlocking, IOstreamOption::streamFormat fmt = IOstreamOption::BINARY) inline
Definition at line 232 of file PstreamBuffers.H.
~PstreamBuffers()
~PstreamBuffers ()
Definition at line 304 of file PstreamBuffers.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::nl, Foam::pos(), and UPtrList< T >::size().
Member Function Documentation
format()
IOstreamOption::streamFormat format () const inline noexcept
Definition at line 253 of file PstreamBuffers.H.
commsType()
UPstream::commsTypes commsType () const inline noexcept
Definition at line 259 of file PstreamBuffers.H.
tag()
int tag () const inline noexcept
Definition at line 265 of file PstreamBuffers.H.
comm()
label comm () const inline noexcept
Definition at line 271 of file PstreamBuffers.H.
nProcs()
label nProcs () const inline noexcept
Definition at line 277 of file PstreamBuffers.H.
allProcs()
UPstream::rangeType allProcs () const inline noexcept
Definition at line 286 of file PstreamBuffers.H.
subProcs()
UPstream::rangeType subProcs () const inline noexcept
Definition at line 293 of file PstreamBuffers.H.
finished()
bool finished () const inline noexcept
Definition at line 303 of file PstreamBuffers.H.
allowClearRecv() [1/2]
bool allowClearRecv () const inline noexcept
Definition at line 310 of file PstreamBuffers.H.
Referenced by FaceCellWaveBase::FaceCellWaveBase(), PointEdgeWaveBase::PointEdgeWaveBase(), and zoneDistribute::zoneDistribute().
hasSendData()
bool hasSendData () const
Definition at line 409 of file PstreamBuffers.C.
hasRecvData()
bool hasRecvData () const
Definition at line 422 of file PstreamBuffers.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and forAll.
sendDataCount()
Foam::label sendDataCount (const label proci) const
Definition at line 446 of file PstreamBuffers.C.
References UPtrList< T >::size().
recvDataCount()
Foam::label recvDataCount (const label proci) const
Definition at line 452 of file PstreamBuffers.C.
References Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
recvDataCounts()
Foam::labelList recvDataCounts () const
Definition at line 475 of file PstreamBuffers.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, and Foam::Zero.
maxRecvCount()
Foam::label maxRecvCount () const
Definition at line 533 of file PstreamBuffers.C.
maxNonLocalRecvCount() [1/2]
Foam::label maxNonLocalRecvCount () const
Definition at line 540 of file PstreamBuffers.C.
References UPstream::myProcNo().
maxNonLocalRecvCount() [2/2]
Foam::label maxNonLocalRecvCount (const label excludeProci) const
Definition at line 503 of file PstreamBuffers.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, and Foam::max().
peekRecvData()
const Foam::UList< char > peekRecvData (const label proci) const
Definition at line 547 of file PstreamBuffers.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::pos(), and UPtrList< T >::size().
clear()
void clear ()
Definition at line 370 of file PstreamBuffers.C.
clearSends()
void clearSends ()
Definition at line 351 of file PstreamBuffers.C.
References PtrList< T >::clear().
clearRecvs()
void clearRecvs ()
Definition at line 360 of file PstreamBuffers.C.
References PtrList< T >::clear(), and Foam::Zero.
clearSend()
void clearSend (const label proci)
Definition at line 378 of file PstreamBuffers.C.
References PtrList< T >::clear().
clearRecv()
void clearRecv (const label proci)
Definition at line 384 of file PstreamBuffers.C.
References PtrList< T >::clear().
clearStorage()
void clearStorage ()
Definition at line 391 of file PstreamBuffers.C.
References Foam::Zero.
allowClearRecv() [2/2]
bool allowClearRecv (bool on) noexcept
Definition at line 575 of file PstreamBuffers.C.
finishedSends() [1/3]
void finishedSends (const bool wait = true)
Definition at line 583 of file PstreamBuffers.C.
finishedSends() [2/3]
void finishedSends (labelList & recvSizes, const bool wait = true)
Definition at line 590 of file PstreamBuffers.C.
References UPstream::commsTypeNames, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, and UPstream::nonBlocking.
finishedNeighbourSends() [1/2]
void finishedNeighbourSends (const labelUList & neighProcs, const bool wait = true)
Definition at line 626 of file PstreamBuffers.C.
finishedNeighbourSends() [2/2]
void finishedNeighbourSends (const labelUList & neighProcs, labelList & recvSizes, const bool wait = true)
Definition at line 615 of file PstreamBuffers.C.
finishedSends() [3/3]
bool finishedSends (bitSet & sendConnections, DynamicList< label > & sendProcs, DynamicList< label > & recvProcs, const bool wait = true)
Definition at line 637 of file PstreamBuffers.C.
References PtrList< T >::clear(), forAll, PtrList< T >::push_back(), UPstream::reduceOr(), PtrList< T >::resize(), PtrList< T >::set(), and UPtrList< T >::size().
finishedGathers() [1/2]
void finishedGathers (const bool wait = true)
Definition at line 701 of file PstreamBuffers.C.
finishedGathers() [2/2]
void finishedGathers (labelList & recvSizes, const bool wait = true)
Definition at line 715 of file PstreamBuffers.C.
References UPstream::commsTypeNames, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, and UPstream::nonBlocking.
finishedScatters() [1/2]
void finishedScatters (const bool wait = true)
Definition at line 708 of file PstreamBuffers.C.
finishedScatters() [2/2]
void finishedScatters (labelList & recvSizes, const bool wait = true)
Definition at line 737 of file PstreamBuffers.C.
References UPstream::commsTypeNames, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, and UPstream::nonBlocking.
Friends And Related Symbol Documentation
UOPstreamBase
friend class UOPstreamBase friend
Definition at line 193 of file PstreamBuffers.H.
UIPstreamBase
friend class UIPstreamBase friend
Definition at line 194 of file PstreamBuffers.H.
Member Data Documentation
algorithm
int algorithm static
Definition at line 202 of file PstreamBuffers.H.
Referenced by argList::parse().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOstreams/Pstreams/PstreamBuffers.H
src/OpenFOAM/db/IOstreams/Pstreams/PstreamBuffers.C