OpenFOAM: wallDampingModel Class Reference
wallDampingModel Class Reference abstract
#include <wallDampingModel.H>
Public Member Functions
TypeName ("wallDampingModel")
declareRunTimeSelectionTable (autoPtr, wallDampingModel, dictionary,(const dictionary &dict, const phasePair &pair),(dict, pair))
wallDampingModel (const dictionary &dict, const phasePair &pair)
virtual ~wallDampingModel ()=default
virtual tmp< volScalarField > damp (const tmp< volScalarField > &) const =0
virtual tmp< volVectorField > damp (const tmp< volVectorField > &) const =0
virtual tmp< surfaceScalarField > damp (const tmp< surfaceScalarField > &) const =0
Public Member Functions inherited from wallDependentModel
wallDependentModel (const fvMesh &mesh)
virtual ~wallDependentModel ()
const volScalarField & yWall () const
const volVectorField & nWall () const
wallDependentModel (const fvMesh &mesh)
virtual ~wallDependentModel ()
const volScalarField & yWall () const
const volVectorField & nWall () const
Static Public Member Functions
static autoPtr< wallDampingModel > New (const dictionary &dict, const phasePair &pair)
Static Public Attributes
static const dimensionSet dimF
Protected Attributes
const phasePair & pair_
Detailed Description
Source files
wallDampingModel.H
wallDampingModel.C
Definition at line 52 of file wallDampingModel.H.
Constructor & Destructor Documentation
wallDampingModel()
wallDampingModel (const dictionary & dict, const phasePair & pair)
Definition at line 38 of file wallDampingModel.C.
~wallDampingModel()
virtual ~wallDampingModel () virtual default
Member Function Documentation
TypeName()
TypeName ("wallDampingModel")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , wallDampingModel , dictionary , (const dictionary &dict, const phasePair &pair) , (dict, pair))
New()
Foam::autoPtr< Foam::wallDampingModel > New (const dictionary & dict, const phasePair & pair) static
Definition at line 52 of file wallDampingModel.C.
References Foam::abort(), dict, Foam::endl(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), and Foam::Info.
damp() [1/3]
virtual tmp< volScalarField > damp (const tmp< volScalarField > &) const pure virtual
Implemented in interpolated, and noWallDamping.
damp() [2/3]
virtual tmp< volVectorField > damp (const tmp< volVectorField > &) const pure virtual
Implemented in interpolated, and noWallDamping.
damp() [3/3]
virtual tmp< surfaceScalarField > damp (const tmp< surfaceScalarField > &) const pure virtual
Implemented in interpolated, and noWallDamping.
Member Data Documentation
pair_
const phasePair& pair_ protected
Definition at line 61 of file wallDampingModel.H.
Referenced by cosine::limiter(), linear::limiter(), and sine::limiter().
dimF
const Foam::dimensionSet dimF static
Definition at line 88 of file wallDampingModel.H.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/interfacialModels/wallDampingModels/wallDampingModel/wallDampingModel.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/interfacialModels/wallDampingModels/wallDampingModel/wallDampingModel.C