OpenFOAM: powerLawLopesdaCostaZone Class Reference
powerLawLopesdaCostaZone Class Reference
#include <powerLawLopesdaCosta.H>
Public Member Functions
powerLawLopesdaCostaZone (const word &name, const word &modelType, const fvMesh &mesh, const dictionary &dict)
const scalarField & Sigma () const
Protected Attributes
const word zoneName_
scalarField Sigma_
Detailed Description
Definition at line 85 of file powerLawLopesdaCosta.H.
Constructor & Destructor Documentation
powerLawLopesdaCostaZone()
powerLawLopesdaCostaZone (const word & name, const word & modelType, const fvMesh & mesh, const dictionary & dict)
Definition at line 43 of file powerLawLopesdaCosta.C.
References Foam::abort(), Pstream::allGatherList(), dict, Foam::FatalError, FatalErrorInFunction, ZoneMesh< ZoneType, MeshType >::findZoneID(), forAll, dictionary::get(), PointIndexHit< PointType >::hit(), mesh, UPstream::myProcNo(), Foam::name(), nPoints, UPstream::nProcs(), UPstream::parRun(), PointIndexHit< PointType >::point(), PtrList< T >::set(), List< T >::setSize(), PtrList< T >::setSize(), powerLawLopesdaCostaZone::Sigma_, UPtrList< T >::size(), triSurfaceTools::triangulate(), and powerLawLopesdaCostaZone::zoneName_.
Member Function Documentation
Sigma()
const Foam::scalarField & Sigma () const
Definition at line 317 of file powerLawLopesdaCosta.C.
Member Data Documentation
zoneName_
const word zoneName_ protected
Definition at line 92 of file powerLawLopesdaCosta.H.
Referenced by powerLawLopesdaCostaZone::powerLawLopesdaCostaZone().
Sigma_
scalarField Sigma_ protected
Definition at line 95 of file powerLawLopesdaCosta.H.
Referenced by powerLawLopesdaCostaZone::powerLawLopesdaCostaZone().
The documentation for this class was generated from the following files:
src/atmosphericModels/porosityModels/powerLawLopesdaCosta/powerLawLopesdaCosta.H
src/atmosphericModels/porosityModels/powerLawLopesdaCosta/powerLawLopesdaCosta.C