OpenFOAM: MRFZone Class Reference
MRFZone Class Reference
MRF zone definition based on cell zone and parameters obtained from a control dictionary constructed from the given stream.
#include <MRFZone.H>
Public Member Functions
ClassName ("MRFZone")
MRFZone (const word &name, const fvMesh &mesh, const dictionary &dict, const word &cellZoneName=word::null)
autoPtr< MRFZone > clone () const
const word & name () const
bool active () const
const vector & origin () const
const vector & axis () const
vector Omega () const
void updateMesh (const mapPolyMesh &mpm)
void addCoriolis (const volVectorField &U, volVectorField &ddtU) const
void addCoriolis (fvVectorMatrix &UEqn, const bool rhs=false) const
void addCoriolis (const volScalarField &rho, fvVectorMatrix &UEqn, const bool rhs=false) const
void makeRelative (volVectorField &U) const
void makeRelative (surfaceScalarField &phi) const
void makeRelative (FieldField< fvsPatchField, scalar > &phi) const
void makeRelative (Field< scalar > &phi, const label patchi) const
void makeRelative (const surfaceScalarField &rho, surfaceScalarField &phi) const
void makeAbsolute (volVectorField &U) const
void makeAbsolute (surfaceScalarField &phi) const
void makeAbsolute (const surfaceScalarField &rho, surfaceScalarField &phi) const
void correctBoundaryVelocity (volVectorField &U) const
template<class Type >
void zero (GeometricField< Type, fvsPatchField, surfaceMesh > &phi) const
void update ()
void writeData (Ostream &os) const
bool read (const dictionary &dict)
Detailed Description
MRF zone definition based on cell zone and parameters obtained from a control dictionary constructed from the given stream.
The rotation of the MRF region is defined by an origin and axis of rotation and an angular speed.
Source files
MRFZone.H
MRFZone.C
Definition at line 64 of file MRFZone.H.
Constructor & Destructor Documentation
MRFZone()
MRFZone (const word & name, const fvMesh & mesh, const dictionary & dict, const word & cellZoneName = word::null)
Definition at line 232 of file MRFZone.C.
References dict, and MRFZone::read().
Member Function Documentation
ClassName()
ClassName ("MRFZone")
clone()
autoPtr< MRFZone > clone () const inline
Definition at line 174 of file MRFZone.H.
References NotImplemented.
name()
const Foam::word & name () const inline
Definition at line 22 of file MRFZoneI.H.
active()
bool active () const inline
Definition at line 28 of file MRFZoneI.H.
origin()
const Foam::vector & origin () const inline
Definition at line 34 of file MRFZoneI.H.
axis()
const Foam::vector & axis () const inline
Definition at line 40 of file MRFZoneI.H.
Omega()
Foam::vector Omega () const
Definition at line 257 of file MRFZone.C.
updateMesh()
void updateMesh (const mapPolyMesh & mpm) inline
Definition at line 199 of file MRFZone.H.
addCoriolis() [1/3]
void addCoriolis (const volVectorField & U, volVectorField & ddtU) const
Definition at line 263 of file MRFZone.C.
References cells, forAll, and U.
addCoriolis() [2/3]
void addCoriolis (fvVectorMatrix & UEqn, const bool rhs = false) const
Definition at line 288 of file MRFZone.C.
References cells, forAll, fvMatrix< Type >::psi(), fvMatrix< Type >::source(), U, and UEqn.
addCoriolis() [3/3]
void addCoriolis (const volScalarField & rho, fvVectorMatrix & UEqn, const bool rhs = false) const
Definition at line 321 of file MRFZone.C.
References cells, forAll, fvMatrix< Type >::psi(), rho, fvMatrix< Type >::source(), U, and UEqn.
makeRelative() [1/5]
void makeRelative (volVectorField & U) const
Definition at line 359 of file MRFZone.C.
References cells, forAll, U, and Foam::Zero.
makeRelative() [2/5]
void makeRelative (surfaceScalarField & phi) const
Definition at line 405 of file MRFZone.C.
References phi.
makeRelative() [3/5]
void makeRelative (FieldField< fvsPatchField, scalar > & phi) const
Definition at line 411 of file MRFZone.C.
References phi.
makeRelative() [4/5]
void makeRelative (Field< scalar > & phi, const label patchi) const
Definition at line 417 of file MRFZone.C.
References phi.
makeRelative() [5/5]
void makeRelative (const surfaceScalarField & rho, surfaceScalarField & phi) const
Definition at line 423 of file MRFZone.C.
References phi, and rho.
makeAbsolute() [1/3]
void makeAbsolute (volVectorField & U) const
Definition at line 433 of file MRFZone.C.
References cells, forAll, and U.
makeAbsolute() [2/3]
void makeAbsolute (surfaceScalarField & phi) const
Definition at line 478 of file MRFZone.C.
References phi.
makeAbsolute() [3/3]
void makeAbsolute (const surfaceScalarField & rho, surfaceScalarField & phi) const
Definition at line 484 of file MRFZone.C.
References phi, and rho.
correctBoundaryVelocity()
void correctBoundaryVelocity (volVectorField & U) const
Definition at line 494 of file MRFZone.C.
References forAll, and U.
zero()
template<class Type > void zero (GeometricField< Type, fvsPatchField, surfaceMesh > & phi) const
Definition at line 206 of file MRFZoneTemplates.C.
References forAll, phi, and Foam::Zero.
update()
void update ()
Definition at line 603 of file MRFZone.C.
writeData()
void writeData (Ostream & os) const
Definition at line 524 of file MRFZone.C.
References Ostream::beginBlock(), Ostream::endBlock(), Foam::nl, os(), and Ostream::writeEntry().
read()
bool read (const dictionary & dict)
Definition at line 544 of file MRFZone.C.
References dict, Foam::exit(), Foam::FatalError, FatalErrorInFunction, UPtrList< T >::get(), word::null, dictionary::readIfPresent(), Foam::returnReduceOr(), and UPtrList< T >::size().
Referenced by MRFZone::MRFZone().
The documentation for this class was generated from the following files:
src/finiteVolume/cfdTools/general/MRF/MRFZone.H
src/finiteVolume/cfdTools/general/MRF/MRFZone.C
src/finiteVolume/cfdTools/general/MRF/MRFZoneI.H
src/finiteVolume/cfdTools/general/MRF/MRFZoneTemplates.C