OpenFOAM: cutFaceAdvect Class Reference
cutFaceAdvect Class Reference
Calculates the face fluxes.
#include <cutFaceAdvect.H>
Public Member Functions
cutFaceAdvect (const fvMesh &mesh, const volScalarField &alpha1)
label calcSubFace (const label faceI, const vector &normal, const vector &base)
label calcSubFace (const face &f, const pointField &points, const scalarField &val, const scalar cutValue)
label calcSubFace (const label faceI, const label sign, const scalar cutValue)
scalar timeIntegratedFaceFlux (const label faceI, const vector &x0, const vector &n0, const scalar Un0, const scalar dt, const scalar phi, const scalar magSf)
scalar timeIntegratedFaceFlux (const label faceI, const scalarField &times, const scalar Un0, const scalar dt, const scalar phi, const scalar magSf)
scalar timeIntegratedArea (const label faceI, const scalar dt, const scalar magSf, const scalar Un0)
scalar timeIntegratedArea (const pointField &fPts, const scalarField &pTimes, const scalar dt, const scalar magSf, const scalar Un0)
void quadAreaCoeffs (const DynamicPointList &pf0, const DynamicPointList &pf1, scalar &quadArea, scalar &intQuadArea) const
void cutPoints (const label faceI, const scalar f0, DynamicList< point > &cutPoints)
void cutPoints (const pointField &pts, const scalarField &f, const scalar f0, DynamicList< point > &cutPoints)
const point & subFaceCentre () const noexcept
const vector & subFaceArea () const noexcept
const DynamicList< point > & subFacePoints () const noexcept
const DynamicList< point > & surfacePoints () const noexcept
void clearStorage ()
Public Member Functions inherited from cutFace
cutFace (const fvMesh &mesh)
Additional Inherited Members
Static Public Attributes inherited from cutFace
static int debug = 0
Protected Member Functions inherited from cutFace
void calcSubFace (const label faceI, const scalarList &pointStatus, label firstFullySubmergedPoint, DynamicList< point > &subFacePoints, DynamicList< point > &surfacePoints, label &faceStatus, vector &subFaceCentre, vector &subFaceArea)
void calcSubFace (const label faceI, const scalarList &pointStatus, const scalarList &weights, label firstFullySubmergedPoint, DynamicList< point > &subFacePoints, DynamicList< point > &surfacePoints, label &faceStatus, vector &subFaceCentre, vector &subFaceArea)
void calcSubFaceCentreAndArea (DynamicList< point > &subFacePoints, vector &subFaceCentre, vector &subFaceArea)
void calcSubFace (const face &f, const pointField &points, const scalarList &pointStatus, label firstFullySubmergedPoint, DynamicList< point > &subFacePoints, DynamicList< point > &surfacePoints, label &faceStatus, vector &subFaceCentre, vector &subFaceArea)
Detailed Description
Calculates the face fluxes.
Reference:
    Roenby, J., Bredmose, H. and Jasak, H. (2016).
    A computational method for sharp interface advection
    Royal Society Open Science, 3
    doi 10.1098/rsos.160405
Original code supplied by Johan Roenby, DHI (2016)
Source files
cutFaceAdvect.H
cutFaceAdvect.C
Definition at line 62 of file cutFaceAdvect.H.
Constructor & Destructor Documentation
cutFaceAdvect()
cutFaceAdvect (const fvMesh & mesh, const volScalarField & alpha1)
Definition at line 28 of file cutFaceAdvect.C.
References cutFaceAdvect::clearStorage().
Member Function Documentation
calcSubFace() [1/3]
Foam::label calcSubFace (const label faceI, const vector & normal, const vector & base)
Definition at line 52 of file cutFaceAdvect.C.
References PtrList< T >::append(), cutFace::calcSubFace(), f(), forAll, Foam::mag(), UList< T >::size(), and Foam::Zero.
calcSubFace() [2/3]
Foam::label calcSubFace (const face & f, const pointField & points, const scalarField & val, const scalar cutValue)
Definition at line 116 of file cutFaceAdvect.C.
References cutFace::calcSubFace(), f(), forAll, Foam::mag(), points, UList< T >::size(), and Foam::Zero.
calcSubFace() [3/3]
Foam::label calcSubFace (const label faceI, const label sign, const scalar cutValue)
Definition at line 569 of file cutFaceAdvect.C.
References PtrList< T >::append(), cutFace::calcSubFace(), f(), forAll, Foam::mag(), Foam::sign(), UList< T >::size(), and Foam::Zero.
timeIntegratedFaceFlux() [1/2]
Foam::scalar timeIntegratedFaceFlux (const label faceI, const vector & x0, const vector & n0, const scalar Un0, const scalar dt, const scalar phi, const scalar magSf)
Definition at line 180 of file cutFaceAdvect.C.
References PtrList< T >::append(), e, Foam::endl(), f(), forAll, Foam::mag(), nPoints, phi, Foam::sign(), UList< T >::size(), and WarningInFunction.
timeIntegratedFaceFlux() [2/2]
Foam::scalar timeIntegratedFaceFlux (const label faceI, const scalarField & times, const scalar Un0, const scalar dt, const scalar phi, const scalar magSf)
Definition at line 327 of file cutFaceAdvect.C.
References PtrList< T >::append(), forAll, nPoints, phi, Foam::sign(), and UList< T >::size().
timeIntegratedArea() [1/2]
Foam::scalar timeIntegratedArea (const label faceI, const scalar dt, const scalar magSf, const scalar Un0)
Definition at line 632 of file cutFaceAdvect.C.
References alpha, PtrList< T >::append(), beta(), e, UList< T >::first(), UList< T >::last(), Foam::mag(), Foam::max(), Foam::neg(), Foam::pos0(), Foam::sign(), and Foam::sortedOrder().
timeIntegratedArea() [2/2]
Foam::scalar timeIntegratedArea (const pointField & fPts, const scalarField & pTimes, const scalar dt, const scalar magSf, const scalar Un0)
Definition at line 374 of file cutFaceAdvect.C.
References alpha, PtrList< T >::append(), beta(), e, UList< T >::first(), Foam::identity(), UList< T >::last(), Foam::mag(), Foam::max(), Foam::neg(), Foam::pos0(), Foam::sign(), UPtrList< T >::size(), and Foam::sortedOrder().
quadAreaCoeffs()
void quadAreaCoeffs (const DynamicPointList & pf0, const DynamicPointList & pf1, scalar & quadArea, scalar & intQuadArea) const
Definition at line 772 of file cutFaceAdvect.C.
References A, alpha, B, beta(), D, Foam::endl(), Foam::mag(), UPtrList< T >::size(), WarningInFunction, and Foam::Zero.
cutPoints() [1/2]
void cutPoints (const label faceI, const scalar f0, DynamicList< point > & cutPoints)
Definition at line 874 of file cutFaceAdvect.C.
References PtrList< T >::append(), Foam::endl(), f(), forAll, Foam::mag(), nPoints, s(), UPtrList< T >::size(), UList< T >::size(), and WarningInFunction.
cutPoints() [2/2]
void cutPoints (const pointField & pts, const scalarField & f, const scalar f0, DynamicList< point > & cutPoints)
Definition at line 929 of file cutFaceAdvect.C.
References PtrList< T >::append(), Foam::endl(), f(), forAll, Foam::mag(), nPoints, pts, s(), UPtrList< T >::size(), and WarningInFunction.
subFaceCentre()
const point & subFaceCentre () const inline noexcept
Definition at line 230 of file cutFaceAdvect.H.
subFaceArea()
const vector & subFaceArea () const inline noexcept
Definition at line 236 of file cutFaceAdvect.H.
subFacePoints()
const DynamicList< point > & subFacePoints () const inline noexcept
Definition at line 242 of file cutFaceAdvect.H.
surfacePoints()
const DynamicList< point > & surfacePoints () const inline noexcept
Definition at line 248 of file cutFaceAdvect.H.
clearStorage()
void clearStorage ()
Definition at line 979 of file cutFaceAdvect.C.
References PtrList< T >::clear(), and Foam::Zero.
Referenced by cutFaceAdvect::cutFaceAdvect().
The documentation for this class was generated from the following files:
src/transportModels/geometricVoF/cellCuts/cutFace/cutFaceAdvect.H
src/transportModels/geometricVoF/cellCuts/cutFace/cutFaceAdvect.C