OpenFOAM: decompositionMethod Class Reference
decompositionMethod Class Reference abstract
Abstract base class for domain decomposition.
#include <decompositionMethod.H>
Public Member Functions
TypeName ("decompositionMethod")
declareRunTimeSelectionTable (autoPtr, decompositionMethod, dictionary,(const dictionary &decompDict, const word &regionName),(decompDict, regionName))
decompositionMethod (const dictionary &decompDict, const word &regionName="")
virtual ~decompositionMethod ()=default
label nDomains () const noexcept
virtual bool parallelAware () const =0
virtual labelList decompose (const pointField &points, const scalarField &pointWeights) const
virtual labelList decompose (const pointField &points) const
virtual labelList decompose (const polyMesh &mesh, const pointField &points, const scalarField &pointWeights) const =0
virtual labelList decompose (const polyMesh &mesh, const pointField &points) const
virtual labelList decompose (const polyMesh &mesh, const labelList &cellToRegion, const pointField &regionPoints, const scalarField &regionWeights) const
virtual labelList decompose (const polyMesh &mesh, const labelList &cellToRegion, const pointField &regionPoints) const
virtual labelList decompose (const labelListList &globalCellCells, const pointField &cc, const scalarField &cWeights) const =0
virtual labelList decompose (const labelListList &globalCellCells, const pointField &cc) const
void setConstraints (const polyMesh &mesh, boolList &blockedFace, PtrList< labelList > &specifiedProcessorFaces, labelList &specifiedProcessor, List< labelPair > &explicitConnections) const
void applyConstraints (const polyMesh &mesh, const boolList &blockedFace, const PtrList< labelList > &specifiedProcessorFaces, const labelList &specifiedProcessor, const List< labelPair > &explicitConnections, labelList &finalDecomp) const
virtual labelList decompose (const polyMesh &mesh, const scalarField &cellWeights, const boolList &blockedFace, const PtrList< labelList > &specifiedProcessorFaces, const labelList &specifiedProcessor, const List< labelPair > &explicitConnections) const
labelList decompose (const polyMesh &mesh, const scalarField &cWeights) const
Static Public Member Functions
static label nDomains (const dictionary &decompDict, const word &regionName="")
static const dictionary & optionalRegionDict (const dictionary &decompDict, const word &regionName)
static autoPtr< decompositionMethod > New (const dictionary &decompDict, const word &regionName="")
static void calcCellCells (const polyMesh &mesh, const labelList &agglom, const label nLocalCoarse, const bool global, CompactListList< label > &cellCells)
static void calcCellCells (const polyMesh &mesh, const labelList &agglom, const label nLocalCoarse, const bool parallel, CompactListList< label > &cellCells, CompactListList< scalar > &cellCellWeights)
Protected Types
enum selectionType { DEFAULT = 0 , EXACT = 1 , MANDATORY = 2 , NULL_DICT = 4 }
Protected Member Functions
const dictionary & findCoeffsDict (const word &coeffsName, int select=selectionType::DEFAULT) const
Static Protected Member Functions
static const dictionary & findCoeffsDict (const dictionary &dict, const word &coeffsName, int select=selectionType::DEFAULT)
Protected Attributes
const dictionary & decompDict_
const dictionary & decompRegionDict_
label nDomains_
PtrList< decompositionConstraint > constraints_
Detailed Description
Abstract base class for domain decomposition.
Source files
decompositionMethod.H
decompositionMethod.C
Definition at line 47 of file decompositionMethod.H.
Member Enumeration Documentation
selectionType
enum selectionType protected
Enumerator
DEFAULT
Default request.
EXACT
No fallback to "coeffs" if main name not found.
MANDATORY
Fatal if dictionary could not be found.
NULL_DICT
On failure, return dictionary::null instead of the top-level enclosing dictionary.
Definition at line 72 of file decompositionMethod.H.
Constructor & Destructor Documentation
decompositionMethod()
decompositionMethod (const dictionary & decompDict, const word & regionName = "") explicit
Definition at line 327 of file decompositionMethod.C.
~decompositionMethod()
virtual ~decompositionMethod () virtual default
Member Function Documentation
findCoeffsDict() [1/2]
const Foam::dictionary & findCoeffsDict (const dictionary & dict, const word & coeffsName, int select = selectionType::DEFAULT) static protected
Definition at line 246 of file decompositionMethod.C.
Referenced by randomDecomp::randomDecomp().
findCoeffsDict() [2/2]
const Foam::dictionary & findCoeffsDict (const word & coeffsName, int select = selectionType::DEFAULT) const protected
Definition at line 281 of file decompositionMethod.C.
TypeName()
TypeName ("decompositionMethod")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , decompositionMethod , dictionary , (const dictionary &decompDict, const word &regionName) , (decompDict, regionName))
nDomains() [1/2]
Foam::label nDomains (const dictionary & decompDict, const word & regionName = "") static
Definition at line 74 of file decompositionMethod.C.
References Foam::endl(), IOobjectOption::LAZY_READ, IOobjectOption::MUST_READ, Foam::nl, UPstream::nProcs(), decompositionMethod::optionalRegionDict(), UPstream::parRun(), keyType::REGEX, regionName, and WarningInFunction.
optionalRegionDict()
const Foam::dictionary & optionalRegionDict (const dictionary & decompDict, const word & regionName) static
Definition at line 118 of file decompositionMethod.C.
References dictionary::null, and regionName.
Referenced by decompositionMethod::nDomains().
New()
Foam::autoPtr< Foam::decompositionMethod > New (const dictionary & decompDict, const word & regionName = "") static
Definition at line 346 of file decompositionMethod.C.
References FatalIOErrorInLookup, UPtrList< T >::get(), and regionName.
Referenced by decompositionModel::decomposer(), and structuredDecomp::structuredDecomp().
nDomains() [2/2]
label nDomains () const inline noexcept
Definition at line 205 of file decompositionMethod.H.
References decompositionMethod::nDomains_.
Referenced by structuredDecomp::structuredDecomp().
parallelAware()
virtual bool parallelAware () const pure virtual
Implemented in hierarchGeomDecomp, manualDecomp, multiLevelDecomp, noDecomp, randomDecomp, simpleGeomDecomp, structuredDecomp, kahipDecomp, metisDecomp, ptscotchDecomp, and scotchDecomp.
decompose() [1/10]
Foam::labelList decompose (const pointField & points, const scalarField & pointWeights) const virtual
Reimplemented in hierarchGeomDecomp, metisLikeDecomp, multiLevelDecomp, randomDecomp, ptscotchDecomp, scotchDecomp, geomDecomp, and simpleGeomDecomp.
Definition at line 1314 of file decompositionMethod.C.
References NotImplemented.
Referenced by meshRefinement::balance().
decompose() [2/10]
Foam::labelList decompose (const pointField & points) const virtual
Reimplemented in hierarchGeomDecomp, metisLikeDecomp, multiLevelDecomp, randomDecomp, simpleGeomDecomp, ptscotchDecomp, scotchDecomp, and geomDecomp.
Definition at line 1325 of file decompositionMethod.C.
References NotImplemented.
decompose() [3/10]
virtual labelList decompose (const polyMesh & mesh, const pointField & points, const scalarField & pointWeights) const pure virtual
Implemented in hierarchGeomDecomp, manualDecomp, noDecomp, randomDecomp, metisLikeDecomp, multiLevelDecomp, structuredDecomp, ptscotchDecomp, scotchDecomp, metisLikeDecomp, multiLevelDecomp, ptscotchDecomp, scotchDecomp, and simpleGeomDecomp.
decompose() [4/10]
Foam::labelList decompose (const polyMesh & mesh, const pointField & points) const virtual
Reimplemented in hierarchGeomDecomp, metisLikeDecomp, multiLevelDecomp, simpleGeomDecomp, ptscotchDecomp, and scotchDecomp.
Definition at line 386 of file decompositionMethod.C.
References mesh, points, and UPtrList< T >::size().
decompose() [5/10]
Foam::labelList decompose (const polyMesh & mesh, const labelList & cellToRegion, const pointField & regionPoints, const scalarField & regionWeights) const virtual
Reimplemented in metisLikeDecomp, ptscotchDecomp, scotchDecomp, metisLikeDecomp, multiLevelDecomp, ptscotchDecomp, and scotchDecomp.
Definition at line 398 of file decompositionMethod.C.
References forAll, mesh, and UPtrList< T >::size().
decompose() [6/10]
Foam::labelList decompose (const polyMesh & mesh, const labelList & cellToRegion, const pointField & regionPoints) const virtual
Reimplemented in metisLikeDecomp, multiLevelDecomp, ptscotchDecomp, and scotchDecomp.
Definition at line 439 of file decompositionMethod.C.
References mesh, and UPtrList< T >::size().
decompose() [7/10]
virtual labelList decompose (const labelListList & globalCellCells, const pointField & cc, const scalarField & cWeights) const pure virtual
Implemented in hierarchGeomDecomp, manualDecomp, multiLevelDecomp, noDecomp, randomDecomp, simpleGeomDecomp, structuredDecomp, ptscotchDecomp, scotchDecomp, metisLikeDecomp, multiLevelDecomp, ptscotchDecomp, scotchDecomp, and metisLikeDecomp.
decompose() [8/10]
Foam::labelList decompose (const labelListList & globalCellCells, const pointField & cc) const virtual
Reimplemented in hierarchGeomDecomp, metisLikeDecomp, multiLevelDecomp, ptscotchDecomp, and scotchDecomp.
Definition at line 458 of file decompositionMethod.C.
References UPtrList< T >::size().
calcCellCells() [1/2]
void calcCellCells (const polyMesh & mesh, const labelList & agglom, const label nLocalCoarse, const bool global, CompactListList< label > & cellCells) static
Definition at line 470 of file decompositionMethod.C.
References polyMesh::boundaryMesh(), HashTable< T, Key, Hash >::clear(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), forAll, HashSet< Key, Hash >::insert(), mesh, primitiveMesh::nBoundaryFaces(), primitiveMesh::nInternalFaces(), patches, pp(), PtrList< T >::setSize(), UPtrList< T >::size(), syncTools::swapBoundaryFaceList(), UPstream::worldComm, and Foam::Zero.
Referenced by renumberMethod::renumber(), renumberMethod::renumber(), springRenumber::renumber(), and CuthillMcKeeRenumber::renumber().
calcCellCells() [2/2]
void calcCellCells (const polyMesh & mesh, const labelList & agglom, const label nLocalCoarse, const bool parallel, CompactListList< label > & cellCells, CompactListList< scalar > & cellCellWeights) static
Definition at line 662 of file decompositionMethod.C.
References polyMesh::boundaryMesh(), HashTable< T, Key, Hash >::clear(), primitiveMesh::faceAreas(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), forAll, HashSet< Key, Hash >::insert(), Foam::mag(), mesh, primitiveMesh::nBoundaryFaces(), primitiveMesh::nInternalFaces(), patches, pp(), PtrList< T >::setSize(), UPtrList< T >::size(), syncTools::swapBoundaryFaceList(), UPstream::worldComm, and Foam::Zero.
setConstraints()
void setConstraints (const polyMesh & mesh, boolList & blockedFace, PtrList< labelList > & specifiedProcessorFaces, labelList & specifiedProcessor, List< labelPair > & explicitConnections) const
Definition at line 1206 of file decompositionMethod.C.
References PtrList< T >::clear(), mesh, primitiveMesh::nFaces(), and PtrList< T >::setSize().
Referenced by meshRefinement::balance().
applyConstraints()
void applyConstraints (const polyMesh & mesh, const boolList & blockedFace, const PtrList< labelList > & specifiedProcessorFaces, const labelList & specifiedProcessor, const List< labelPair > & explicitConnections, labelList & finalDecomp) const
Definition at line 1235 of file decompositionMethod.C.
References mesh.
decompose() [9/10]
Foam::labelList decompose (const polyMesh & mesh, const scalarField & cellWeights, const boolList & blockedFace, const PtrList< labelList > & specifiedProcessorFaces, const labelList & specifiedProcessor, const List< labelPair > & explicitConnections) const virtual
Reimplemented in metisLikeDecomp, multiLevelDecomp, ptscotchDecomp, and scotchDecomp.
Definition at line 857 of file decompositionMethod.C.
References Foam::BitOps::all(), polyMesh::boundaryMesh(), primitiveMesh::cellCentres(), Foam::BitOps::count(), UPtrList< T >::empty(), Foam::endl(), Foam::exit(), f(), primitiveMesh::faceCentres(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), polyMesh::faces(), Foam::FatalError, FatalErrorInFunction, UPtrList< T >::first(), forAll, polyMesh::globalData(), Foam::Info, primitiveMesh::isInternalFace(), VectorSpace< Form, Cmpt, Ncmpts >::max, mesh, primitiveMesh::nCells(), primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), Foam::nl, UPstream::parRun(), patches, pFaces, primitiveMesh::pointFaces(), pp(), Foam::reduce(), Foam::returnReduce(), Foam::returnReduceOr(), UPtrList< T >::size(), syncTools::swapBoundaryCellList(), and Foam::Zero.
decompose() [10/10]
Foam::labelList decompose (const polyMesh & mesh, const scalarField & cWeights) const
Definition at line 1260 of file decompositionMethod.C.
References mesh.
Member Data Documentation
decompDict_
const dictionary& decompDict_ protected
Definition at line 85 of file decompositionMethod.H.
decompRegionDict_
const dictionary& decompRegionDict_ protected
Definition at line 88 of file decompositionMethod.H.
nDomains_
label nDomains_ protected
Definition at line 91 of file decompositionMethod.H.
Referenced by decompositionMethod::nDomains().
constraints_
PtrList<decompositionConstraint> constraints_ protected
Definition at line 94 of file decompositionMethod.H.
The documentation for this class was generated from the following files:
src/parallel/decompose/decompositionMethods/decompositionMethod/decompositionMethod.H
src/parallel/decompose/decompositionMethods/decompositionMethod/decompositionMethod.C