OpenFOAM: profilingInformation Class Reference
profilingInformation Class Reference
Code profiling information in terms of time spent, number of calls etc.
#include <profilingInformation.H>
Public Member Functions
profilingInformation (profilingInformation *parent, const string &descr, const label id)
~profilingInformation ()=default
label id () const noexcept
const string & description () const noexcept
profilingInformation & parent () const noexcept
label calls () const noexcept
scalar totalTime () const noexcept
scalar childTime () const noexcept
int maxMem () const noexcept
bool active () const noexcept
void update (const scalar elapsedTime)
Ostream & write (Ostream &os, const bool offset=false, const scalar elapsedTime=0, const scalar childTime=0) const
Protected Member Functions
profilingInformation ()
void setActive (bool state) const
profilingInformation (const profilingInformation &)=delete
void operator= (const profilingInformation &)=delete
Friends
class profiling
Detailed Description
Code profiling information in terms of time spent, number of calls etc.
Source files
profilingInformation.H
profilingInformation.C
Definition at line 52 of file profilingInformation.H.
Constructor & Destructor Documentation
profilingInformation() [1/3]
profilingInformation () protected
Definition at line 28 of file profilingInformation.C.
profilingInformation() [2/3]
profilingInformation (const profilingInformation &) protected delete
profilingInformation() [3/3]
profilingInformation (profilingInformation * parent, const string & descr, const label id)
Definition at line 41 of file profilingInformation.C.
~profilingInformation()
~profilingInformation () default
Member Function Documentation
setActive()
void setActive (bool state) const protected
Definition at line 75 of file profilingInformation.C.
Referenced by profiling::beginTimer(), and profiling::endTimer().
operator=()
void operator= (const profilingInformation &) protected delete
id()
label id () const inline noexcept
Definition at line 128 of file profilingInformation.H.
Referenced by profiling::create(), and profiling::unstack().
description()
const string & description () const inline noexcept
Definition at line 130 of file profilingInformation.H.
Referenced by profiling::unstack().
parent()
profilingInformation & parent () const inline noexcept
Definition at line 132 of file profilingInformation.H.
calls()
label calls () const inline noexcept
Definition at line 134 of file profilingInformation.H.
totalTime()
scalar totalTime () const inline noexcept
Definition at line 136 of file profilingInformation.H.
childTime()
scalar childTime () const inline noexcept
Definition at line 138 of file profilingInformation.H.
maxMem()
int maxMem () const inline noexcept
Definition at line 140 of file profilingInformation.H.
active()
bool active () const inline noexcept
Definition at line 142 of file profilingInformation.H.
update()
void update (const scalar elapsedTime)
Definition at line 61 of file profilingInformation.C.
Referenced by profiling::endTimer().
write()
Foam::Ostream & write (Ostream & os, const bool offset = false, const scalar elapsedTime = 0, const scalar childTime = 0) const
Definition at line 81 of file profilingInformation.C.
References Ostream::beginBlock(), Ostream::endBlock(), Switch::name(), Foam::name(), os(), Ostream::writeEntry(), and Ostream::writeEntryIfDifferent().
Referenced by Foam::operator<<().
Friends And Related Symbol Documentation
profiling
friend class profiling friend
Definition at line 87 of file profilingInformation.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/global/profiling/profilingInformation.H
src/OpenFOAM/global/profiling/profilingInformation.C