OpenFOAM: greyMeanAbsorptionEmission Class Reference
greyMeanAbsorptionEmission Class Reference
Thermophysical models » Radiation models » Sub-models » Absorption and emission sub-models
greyMeanAbsorptionEmission radiation absorption and emission coefficients for continuous phase
#include <greyMeanAbsorptionEmission.H>
Public Member Functions
TypeName ("greyMeanAbsorptionEmission")
greyMeanAbsorptionEmission (const dictionary &dict, const fvMesh &mesh)
virtual ~greyMeanAbsorptionEmission ()
tmp< volScalarField > aCont (const label bandI=0) const
tmp< volScalarField > eCont (const label bandI=0) const
tmp< volScalarField > ECont (const label bandI=0) const
bool isGrey () const
Public Member Functions inherited from absorptionEmissionModel
TypeName ("absorptionEmissionModel")
declareRunTimeSelectionTable (autoPtr, absorptionEmissionModel, dictionary,(const dictionary &dict, const fvMesh &mesh),(dict, mesh))
absorptionEmissionModel (const dictionary &dict, const fvMesh &mesh)
virtual ~absorptionEmissionModel ()
const fvMesh & mesh () const
const dictionary & dict () const
virtual tmp< volScalarField > a (const label bandI=0) const
virtual tmp< volScalarField > aDisp (const label bandI=0) const
virtual tmp< volScalarField > e (const label bandI=0) const
virtual tmp< volScalarField > eDisp (const label bandI=0) const
virtual tmp< volScalarField > E (const label bandI=0) const
virtual tmp< volScalarField > EDisp (const label bandI=0) const
virtual label nBands () const
virtual const Vector2D< scalar > & bands (const label n) const
virtual void correct (volScalarField &a, PtrList< volScalarField > &aj) const
Public Attributes
absorptionCoeffs coeffs_ [nSpecies_]
Static Public Attributes
static const int nSpecies_ = 5
Additional Inherited Members
Static Public Member Functions inherited from absorptionEmissionModel
static autoPtr< absorptionEmissionModel > New (const dictionary &dict, const fvMesh &mesh)
Protected Attributes inherited from absorptionEmissionModel
const dictionary dict_
const fvMesh & mesh_
Detailed Description
greyMeanAbsorptionEmission radiation absorption and emission coefficients for continuous phase
The coefficients for the species in the Look up table have to be specified for use in moles x P [atm], i.e. (k[i] = species[i]*p*9.869231e-6).
The coefficients for CO and soot or any other added are multiplied by the respective mass fraction being solved
All the species in the dictionary need either to be in the look-up table or being solved. Conversely, all the species solved do not need to be included in the calculation of the absorption coefficient
The names of the species in the absorption dictionary must match exactly the name in the look-up table or the name of the field being solved
The look-up table ("speciesTable") file should be in constant
i.e. dictionary
    LookUpTableFileName     "speciesTable";
    EhrrCoeff       0.0;
    CO2
    {
        Tcommon     300.;   // Common Temp
        invTemp     true;   // Is the polynomial using inverse temperature?
        Tlow        300.;   // Low Temp
        Thigh       2500.;  // High Temp
        loTcoeffs           // coeffs for T < Tcommon
        (
            0               //  a0            +
            0               //  a1*T          +
            0               //  a2*T^(+/-)2   +
            0               //  a3*T^(+/-)3   +
            0               //  a4*T^(+/-)4   +
            0               //  a5*T^(+/-)5   +
        );
        hiTcoeffs           // coeffs for T > Tcommon
        (
            18.741
            -121.31e3
            273.5e6
            -194.05e9
            56.31e12
            -5.8169e15
        );
    }
Source files
greyMeanAbsorptionEmission.H
greyMeanAbsorptionEmission.C
Definition at line 105 of file greyMeanAbsorptionEmission.H.
Constructor & Destructor Documentation
greyMeanAbsorptionEmission()
greyMeanAbsorptionEmission (const dictionary & dict, const fvMesh & mesh)
Definition at line 48 of file greyMeanAbsorptionEmission.C.
References Foam::abort(), greyMeanAbsorptionEmission::coeffs_, absorptionEmissionModel::dict(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAllConstIters, dictionary::found(), dictionary::get(), Foam::Info, absorptionCoeffs::initialise(), HashTable< T, Key, Hash >::insert(), absorptionEmissionModel::mesh(), Foam::nl, and PtrList< T >::set().
~greyMeanAbsorptionEmission()
~greyMeanAbsorptionEmission () virtual
Definition at line 174 of file greyMeanAbsorptionEmission.C.
Member Function Documentation
TypeName()
TypeName ("greyMeanAbsorptionEmission")
aCont()
Foam::tmp< Foam::volScalarField > aCont (const label bandI = 0) const virtual
Reimplemented from absorptionEmissionModel.
Definition at line 181 of file greyMeanAbsorptionEmission.C.
References b, Foam::dimLength, Foam::dimless, fvPatchFieldBase::extrapolatedCalculatedType(), UList< T >::find(), forAll, forAllConstIters, mesh, n, Foam::name(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, p, Foam::paToAtm(), s(), T, GeometricField< Type, PatchField, GeoMesh >::T(), timeName, and Foam::Zero.
eCont()
Foam::tmp< Foam::volScalarField > eCont (const label bandI = 0) const virtual
Reimplemented from absorptionEmissionModel.
Definition at line 262 of file greyMeanAbsorptionEmission.C.
ECont()
Foam::tmp< Foam::volScalarField > ECont (const label bandI = 0) const virtual
Reimplemented from absorptionEmissionModel.
Definition at line 269 of file greyMeanAbsorptionEmission.C.
References Foam::dimEnergy, Foam::dimLength, Foam::dimMass, Foam::dimTime, Foam::dimVolume, Foam::endl(), Foam::name(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, Foam::pow3(), Qdot, WarningInFunction, and Foam::Zero.
isGrey()
bool isGrey () const inline virtual
Reimplemented from absorptionEmissionModel.
Definition at line 186 of file greyMeanAbsorptionEmission.H.
Member Data Documentation
nSpecies_
const int nSpecies_ = 5 static
Definition at line 114 of file greyMeanAbsorptionEmission.H.
coeffs_
absorptionCoeffs coeffs_[nSpecies_]
Definition at line 117 of file greyMeanAbsorptionEmission.H.
Referenced by greyMeanAbsorptionEmission::greyMeanAbsorptionEmission().
The documentation for this class was generated from the following files:
src/thermophysicalModels/radiation/submodels/absorptionEmissionModel/greyMeanAbsorptionEmission/greyMeanAbsorptionEmission.H
src/thermophysicalModels/radiation/submodels/absorptionEmissionModel/greyMeanAbsorptionEmission/greyMeanAbsorptionEmission.C