OpenFOAM: TomiyamaLift Class Reference
TomiyamaLift Class Reference
Lift model of Tomiyama et al.
#include <TomiyamaLift.H>
Public Member Functions
TypeName ("Tomiyama")
TomiyamaLift (const dictionary &dict, const phasePair &pair)
virtual ~TomiyamaLift ()
virtual tmp< volScalarField > Cl () const
TypeName ("Tomiyama")
TomiyamaLift (const dictionary &dict, const phasePair &pair)
virtual ~TomiyamaLift ()
virtual tmp< volScalarField > Cl () const
Public Member Functions inherited from liftModel
TypeName ("liftModel")
declareRunTimeSelectionTable (autoPtr, liftModel, dictionary,(const dictionary &dict, const phasePair &pair),(dict, pair))
liftModel (const dictionary &dict, const phasePair &pair)
virtual ~liftModel ()=default
virtual tmp< volVectorField > Fi () const
virtual tmp< volVectorField > F () const
virtual tmp< surfaceScalarField > Ff () const
TypeName ("liftModel")
declareRunTimeSelectionTable (autoPtr, liftModel, dictionary,(const dictionary &dict, const phasePair &pair),(dict, pair))
liftModel (const dictionary &dict, const phasePair &pair)
virtual ~liftModel ()=default
virtual tmp< volVectorField > Fi () const
virtual tmp< volVectorField > F () const
virtual tmp< surfaceScalarField > Ff () const
Additional Inherited Members
Static Public Member Functions inherited from liftModel
static autoPtr< liftModel > New (const dictionary &dict, const phasePair &pair)
static autoPtr< liftModel > New (const dictionary &dict, const phasePair &pair)
Static Public Attributes inherited from liftModel
static const dimensionSet dimF
Protected Attributes inherited from liftModel
const phasePair & pair_
Detailed Description
Lift model of Tomiyama et al.
Reference:
    Tomiyama, A., Tamai, H., Zun, I., & Hosokawa, S. (2002).
    Transverse migration of single bubbles in simple shear flows.
    Chemical Engineering Science, 57(11), 1849-1858.
The coefficient for pow3(EoH) proposed by Tomiyama (2002) has been modified to make the model continuous at EoH = 10.7 while maintaining the lift coefficient proposed by Tomiyama (2002) when EoH >= 10.7.
Source files
TomiyamaLift.H
TomiyamaLift.C
Reference:
    "Transverse migration of single bubbles in simple shear flows"
    Tomiyama, A., Tamai, H., Zun, I., Hosokawa, S.,
    Chemical Engineering Science
    Volume 57, Issue 11, June 2002, pp. 1849-1858
The coefficient for pow3(EoH) proposed by Tomiyama (2002) has been modified to make the model continuous at EoH = 10.7 while maintaining the lift coefficient proposed by Tomiyama (2002) when EoH >= 10.7.
Source files
TomiyamaLift.H
TomiyamaLift.C
Definition at line 62 of file TomiyamaLift.H.
Constructor & Destructor Documentation
TomiyamaLift() [1/2]
TomiyamaLift (const dictionary & dict, const phasePair & pair)
Definition at line 39 of file TomiyamaLift.C.
~TomiyamaLift() [1/2]
~TomiyamaLift () virtual
Definition at line 51 of file TomiyamaLift.C.
TomiyamaLift() [2/2]
TomiyamaLift (const dictionary & dict, const phasePair & pair)
~TomiyamaLift() [2/2]
virtual ~TomiyamaLift () virtual
Member Function Documentation
TypeName() [1/2]
TypeName ("Tomiyama")
Cl() [1/2]
Foam::tmp< Foam::volScalarField > Cl () const virtual
Implements liftModel.
Definition at line 57 of file TomiyamaLift.C.
References f(), Foam::min(), Foam::neg(), Foam::pos0(), Foam::pow3(), Foam::sqr(), and Foam::tanh().
TypeName() [2/2]
TypeName ("Tomiyama")
Cl() [2/2]
virtual tmp< volScalarField > Cl () const virtual
Implements liftModel.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/interfacialModels/liftModels/TomiyamaLift/TomiyamaLift.H
src/phaseSystemModels/twoPhaseEuler/twoPhaseSystem/interfacialModels/liftModels/TomiyamaLift/TomiyamaLift.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/interfacialModels/liftModels/TomiyamaLift/TomiyamaLift.C
src/phaseSystemModels/twoPhaseEuler/twoPhaseSystem/interfacialModels/liftModels/TomiyamaLift/TomiyamaLift.C