OpenFOAM: COxidationIntrinsicRate< CloudType > Class Template Reference
COxidationIntrinsicRate< CloudType > Class Template Reference
Lagrangian particle models » Submodels » Reacting multiphase » Surface reaction
Intrinsic char surface reaction mndel.
#include <COxidationIntrinsicRate.H>
Public Member Functions
TypeName ("COxidationIntrinsicRate")
COxidationIntrinsicRate (const dictionary &dict, CloudType &owner)
COxidationIntrinsicRate (const COxidationIntrinsicRate< CloudType > &srm)
virtual autoPtr< SurfaceReactionModel< CloudType > > clone () const
virtual ~COxidationIntrinsicRate ()=default
virtual scalar calculate (const scalar dt, const scalar Re, const scalar nu, const label celli, const scalar d, const scalar T, const scalar Tc, const scalar pc, const scalar rhoc, const scalar mass, const scalarField &YGas, const scalarField &YLiquid, const scalarField &YSolid, const scalarField &YMixture, const scalar N, scalarField &dMassGas, scalarField &dMassLiquid, scalarField &dMassSolid, scalarField &dMassSRCarrier) const
Public Member Functions inherited from SurfaceReactionModel< CloudType >
TypeName ("surfaceReactionModel")
declareRunTimeSelectionTable (autoPtr, SurfaceReactionModel, dictionary,(const dictionary &dict, CloudType &cloud),(dict, cloud))
SurfaceReactionModel (CloudType &owner)
SurfaceReactionModel (const dictionary &dict, CloudType &cloud, const word &type)
SurfaceReactionModel (const SurfaceReactionModel< CloudType > &srm)
virtual ~SurfaceReactionModel ()=default
void addToSurfaceReactionMass (const scalar dMass)
virtual void info ()
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
virtual ~CloudSubModelBase ()=default
const CloudType & owner () const
virtual bool writeTime () const
virtual fileName localPath () const
CloudType & owner ()
virtual void write (Ostream &os) const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
subModelBase (const subModelBase &smb)
virtual ~subModelBase ()=default
const word & modelName () const
const dictionary & dict () const
const word & baseName () const
const word & modelType () const
const dictionary & coeffDict () const
const dictionary & properties () const
virtual bool defaultCoeffs (const bool printMsg) const
virtual bool active () const
virtual void cacheFields (const bool store)
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
bool getModelDict (const word &entryName, dictionary &dict) const
template<class Type >
bool getModelProperty (const word &entryName, Type &value) const
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Additional Inherited Members
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Static Public Member Functions inherited from SurfaceReactionModel< CloudType >
static autoPtr< SurfaceReactionModel< CloudType > > New (const dictionary &dict, CloudType &cloud)
Public Attributes inherited from subModelBase
bool log
Protected Member Functions inherited from subModelBase
bool inLine () const
Protected Attributes inherited from SurfaceReactionModel< CloudType >
scalar dMass_
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Protected Attributes inherited from subModelBase
const word modelName_
dictionary & properties_
const dictionary dict_
const word baseName_
const word modelType_
const dictionary coeffDict_
Detailed Description
template<class CloudType>
class Foam::COxidationIntrinsicRate< CloudType >
Intrinsic char surface reaction mndel.
C(s) + Sb*O2 -> CO2
where Sb is the stoichiometry of the reaction
Definition at line 56 of file COxidationIntrinsicRate.H.
Constructor & Destructor Documentation
COxidationIntrinsicRate() [1/2]
template<class CloudType > COxidationIntrinsicRate (const dictionary & dict, CloudType & owner)
Definition at line 30 of file COxidationIntrinsicRate.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::Info, Foam::nl, CloudSubModelBase< CloudType >::owner(), and Foam::sqrt().
COxidationIntrinsicRate() [2/2]
template<class CloudType > COxidationIntrinsicRate (const COxidationIntrinsicRate< CloudType > & srm)
Definition at line 77 of file COxidationIntrinsicRate.C.
~COxidationIntrinsicRate()
template<class CloudType > virtual ~COxidationIntrinsicRate () virtual default
Member Function Documentation
TypeName()
template<class CloudType > TypeName ("COxidationIntrinsicRate< CloudType >")
clone()
template<class CloudType > virtual autoPtr< SurfaceReactionModel< CloudType > > clone () const inline virtual
Implements SurfaceReactionModel< CloudType >.
Definition at line 135 of file COxidationIntrinsicRate.H.
calculate()
template<class CloudType > Foam::scalar calculate (const scalar dt, const scalar Re, const scalar nu, const label celli, const scalar d, const scalar T, const scalar Tc, const scalar pc, const scalar rhoc, const scalar mass, const scalarField & YGas, const scalarField & YLiquid, const scalarField & YSolid, const scalarField & YMixture, const scalar N, scalarField & dMassGas, scalarField & dMassLiquid, scalarField & dMassSolid, scalarField & dMassSRCarrier) const virtual
Implements SurfaceReactionModel< CloudType >.
Definition at line 103 of file COxidationIntrinsicRate.C.
References Foam::exp(), Foam::max(), Foam::min(), phi, Foam::constant::mathematical::pi(), Foam::pow(), Foam::pow3(), R, Foam::sqr(), Foam::sqrt(), T, and Foam::tanh().
The documentation for this class was generated from the following files:
src/lagrangian/coalCombustion/submodels/surfaceReactionModel/COxidationIntrinsicRate/COxidationIntrinsicRate.H
src/lagrangian/coalCombustion/submodels/surfaceReactionModel/COxidationIntrinsicRate/COxidationIntrinsicRate.C