OpenFOAM: JohnsonJacksonParticleThetaFvPatchScalarField Class Reference
JohnsonJacksonParticleThetaFvPatchScalarField Class Reference
Robin condition for the particulate granular temperature.
#include <JohnsonJacksonParticleThetaFvPatchScalarField.H>
Public Member Functions
TypeName ("JohnsonJacksonParticleTheta")
JohnsonJacksonParticleThetaFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
JohnsonJacksonParticleThetaFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
JohnsonJacksonParticleThetaFvPatchScalarField (const JohnsonJacksonParticleThetaFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
JohnsonJacksonParticleThetaFvPatchScalarField (const JohnsonJacksonParticleThetaFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
JohnsonJacksonParticleThetaFvPatchScalarField (const JohnsonJacksonParticleThetaFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual void autoMap (const fvPatchFieldMapper &)
virtual void rmap (const fvPatchScalarField &, const labelList &)
virtual void updateCoeffs ()
virtual void write (Ostream &) const
TypeName ("JohnsonJacksonParticleTheta")
JohnsonJacksonParticleThetaFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
JohnsonJacksonParticleThetaFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
JohnsonJacksonParticleThetaFvPatchScalarField (const JohnsonJacksonParticleThetaFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
JohnsonJacksonParticleThetaFvPatchScalarField (const JohnsonJacksonParticleThetaFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
JohnsonJacksonParticleThetaFvPatchScalarField (const JohnsonJacksonParticleThetaFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual void autoMap (const fvPatchFieldMapper &)
virtual void rmap (const fvPatchScalarField &, const labelList &)
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
Robin condition for the particulate granular temperature.
References:
    Reuge, N., Cadoret, L., Coufort-Saudejaud, C., Pannala, S., Syamlal, M.,
    & Caussat, B. (2008).
    Multifluid Eulerian modeling of dense gas–solids fluidized bed
    hydrodynamics: influence of the dissipation parameters.
    Chemical Engineering Science, 63(22), 5540-5551.
    Johnson, P. C., & Jackson, R. (1987).
    Frictional–collisional constitutive relations for granular materials,
    with application to plane shearing.
    Journal of fluid Mechanics, 176, 67-93.
Source files
JohnsonJacksonParticleThetaFvPatchScalarField.H
JohnsonJacksonParticleThetaFvPatchScalarField.C
References:
    "Multifluid Eulerian modeling of dense gas–solids fluidized bed
     hydrodynamics: Influence of the dissipation parameters"
    Reuge, N.,
    Chemical Engineering Science
    Volume 63, Issue 22, November 2008, pp. 5540-5551
    "Frictional-collisional constitutive relations for granular materials,
     with application to plane shearing"
    Johnson, P.C., and Jackson, R.,
    Journal of Fluid Mechanics
    Volume 176, March 1987, pp. 67-93
Source files
JohnsonJacksonParticleThetaFvPatchScalarField.H
JohnsonJacksonParticleThetaFvPatchScalarField.C
Definition at line 62 of file JohnsonJacksonParticleThetaFvPatchScalarField.H.
Constructor & Destructor Documentation
JohnsonJacksonParticleThetaFvPatchScalarField() [1/10]
JohnsonJacksonParticleThetaFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 38 of file JohnsonJacksonParticleThetaFvPatchScalarField.C.
References Foam::dimless.
JohnsonJacksonParticleThetaFvPatchScalarField() [2/10]
JohnsonJacksonParticleThetaFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 67 of file JohnsonJacksonParticleThetaFvPatchScalarField.C.
References Foam::abort(), dict, Foam::FatalError, FatalErrorInFunction, IOobjectOption::MUST_READ, and dimensioned< Type >::value().
JohnsonJacksonParticleThetaFvPatchScalarField() [3/10]
JohnsonJacksonParticleThetaFvPatchScalarField (const JohnsonJacksonParticleThetaFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 51 of file JohnsonJacksonParticleThetaFvPatchScalarField.C.
JohnsonJacksonParticleThetaFvPatchScalarField() [4/10]
JohnsonJacksonParticleThetaFvPatchScalarField (const JohnsonJacksonParticleThetaFvPatchScalarField & ptf)
Definition at line 105 of file JohnsonJacksonParticleThetaFvPatchScalarField.C.
JohnsonJacksonParticleThetaFvPatchScalarField() [5/10]
JohnsonJacksonParticleThetaFvPatchScalarField (const JohnsonJacksonParticleThetaFvPatchScalarField & ptf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 117 of file JohnsonJacksonParticleThetaFvPatchScalarField.C.
JohnsonJacksonParticleThetaFvPatchScalarField() [6/10]
JohnsonJacksonParticleThetaFvPatchScalarField (const fvPatch & , const DimensionedField< scalar, volMesh > &)
JohnsonJacksonParticleThetaFvPatchScalarField() [7/10]
JohnsonJacksonParticleThetaFvPatchScalarField (const fvPatch & , const DimensionedField< scalar, volMesh > & , const dictionary &)
JohnsonJacksonParticleThetaFvPatchScalarField() [8/10]
JohnsonJacksonParticleThetaFvPatchScalarField (const JohnsonJacksonParticleThetaFvPatchScalarField & , const fvPatch & , const DimensionedField< scalar, volMesh > & , const fvPatchFieldMapper &)
JohnsonJacksonParticleThetaFvPatchScalarField() [9/10]
JohnsonJacksonParticleThetaFvPatchScalarField (const JohnsonJacksonParticleThetaFvPatchScalarField &)
JohnsonJacksonParticleThetaFvPatchScalarField() [10/10]
JohnsonJacksonParticleThetaFvPatchScalarField (const JohnsonJacksonParticleThetaFvPatchScalarField & , const DimensionedField< scalar, volMesh > &)
Member Function Documentation
TypeName() [1/2]
TypeName ("JohnsonJacksonParticleTheta")
clone() [1/4]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 114 of file JohnsonJacksonParticleThetaFvPatchScalarField.H.
clone() [2/4]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 130 of file JohnsonJacksonParticleThetaFvPatchScalarField.H.
autoMap() [1/2]
void autoMap (const fvPatchFieldMapper & m) virtual
Definition at line 132 of file JohnsonJacksonParticleThetaFvPatchScalarField.C.
rmap() [1/2]
void rmap (const fvPatchScalarField & ptf, const labelList & addr) virtual
Definition at line 141 of file JohnsonJacksonParticleThetaFvPatchScalarField.C.
updateCoeffs() [1/2]
void updateCoeffs () virtual
Definition at line 151 of file JohnsonJacksonParticleThetaFvPatchScalarField.C.
References alpha, alphaMax(), Foam::dimless, fluid, IOobject::groupName(), Foam::magSqr(), Foam::max(), twoPhaseSystem::phase1(), twoPhaseSystem::phase2(), Foam::constant::mathematical::pi(), Foam::pos0(), Foam::sqr(), Foam::sqrt(), U, and dimensioned< Type >::value().
write() [1/2]
void write (Ostream & os) const virtual
Definition at line 267 of file JohnsonJacksonParticleThetaFvPatchScalarField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntry(), and fvPatchField< Type >::writeValueEntry().
TypeName() [2/2]
TypeName ("JohnsonJacksonParticleTheta")
clone() [3/4]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 115 of file JohnsonJacksonParticleThetaFvPatchScalarField.H.
clone() [4/4]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 131 of file JohnsonJacksonParticleThetaFvPatchScalarField.H.
autoMap() [2/2]
virtual void autoMap (const fvPatchFieldMapper &) virtual
rmap() [2/2]
virtual void rmap (const fvPatchScalarField & , const labelList &) virtual
updateCoeffs() [2/2]
virtual void updateCoeffs () virtual
write() [2/2]
virtual void write (Ostream &) const virtual
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/twoPhaseCompressibleTurbulenceModels/kineticTheoryModels/derivedFvPatchFields/JohnsonJacksonParticleTheta/JohnsonJacksonParticleThetaFvPatchScalarField.H
src/phaseSystemModels/twoPhaseEuler/phaseCompressibleTurbulenceModels/kineticTheoryModels/derivedFvPatchFields/JohnsonJacksonParticleTheta/JohnsonJacksonParticleThetaFvPatchScalarField.H
src/phaseSystemModels/reactingEuler/twoPhaseCompressibleTurbulenceModels/kineticTheoryModels/derivedFvPatchFields/JohnsonJacksonParticleTheta/JohnsonJacksonParticleThetaFvPatchScalarField.C
src/phaseSystemModels/twoPhaseEuler/phaseCompressibleTurbulenceModels/kineticTheoryModels/derivedFvPatchFields/JohnsonJacksonParticleTheta/JohnsonJacksonParticleThetaFvPatchScalarField.C