OpenFOAM: wallFunctionCoefficients Class Reference
wallFunctionCoefficients Class Reference
Class to host the wall-function coefficients being used in the wall function boundary conditions.
#include <wallFunctionCoefficients.H>
Public Member Functions
wallFunctionCoefficients ()
wallFunctionCoefficients (const dictionary &dict)
scalar Cmu () const noexcept
scalar kappa () const noexcept
scalar E () const noexcept
scalar yPlusLam () const noexcept
void writeEntries (Ostream &) const
Detailed Description
Class to host the wall-function coefficients being used in the wall function boundary conditions.
Usage
Example of the boundary condition specification:
<patchName>
{
    // Top-level entries
    ...
    // Optional entries
    Cmu             0.09;
    kappa           0.41;
    E               9.8;
    // Inherited entries
    ...
}
where the entries mean:
Property Description Type Reqd Deflt
Cmu Empirical model coefficient scalar no 0.09
kappa von Karman constant scalar no 0.41
E Wall roughness parameter scalar no 9.8
Source files
wallFunctionCoefficients.H
wallFunctionCoefficients.C
Definition at line 101 of file wallFunctionCoefficients.H.
Constructor & Destructor Documentation
wallFunctionCoefficients() [1/2]
wallFunctionCoefficients ()
Definition at line 54 of file wallFunctionCoefficients.C.
References Foam::calcYPlusLam().
wallFunctionCoefficients() [2/2]
wallFunctionCoefficients (const dictionary & dict) explicit
Definition at line 63 of file wallFunctionCoefficients.C.
Member Function Documentation
Cmu()
scalar Cmu () const inline noexcept
Definition at line 135 of file wallFunctionCoefficients.H.
Referenced by adjointkOmegaSST::addWallFunctionTerms(), adjointkOmegaSST::adjointMeanFlowSource(), atmNutkWallFunctionFvPatchScalarField::calcNut(), atmNutWallFunctionFvPatchScalarField::calcNut(), nutkWallFunctionFvPatchScalarField::calcNut(), atmEpsilonWallFunctionFvPatchScalarField::calculate(), atmOmegaWallFunctionFvPatchScalarField::calculate(), nutkFilmWallFunctionFvPatchScalarField::calcUTau(), and kaqRWallFunctionFvPatchScalarField::manipulateMatrix().
kappa()
scalar kappa () const inline noexcept
Definition at line 141 of file wallFunctionCoefficients.H.
Referenced by adjointkOmegaSST::addWallFunctionTerms(), adjointkOmegaSST::adjointMeanFlowSource(), atmNutkWallFunctionFvPatchScalarField::calcNut(), atmNutUWallFunctionFvPatchScalarField::calcNut(), atmNutWallFunctionFvPatchScalarField::calcNut(), nutkWallFunctionFvPatchScalarField::calcNut(), nutUWallFunctionFvPatchScalarField::calcNut(), atmEpsilonWallFunctionFvPatchScalarField::calculate(), atmOmegaWallFunctionFvPatchScalarField::calculate(), nutkFilmWallFunctionFvPatchScalarField::calcUTau(), and kaqRWallFunctionFvPatchScalarField::manipulateMatrix().
E()
scalar E () const inline noexcept
Definition at line 147 of file wallFunctionCoefficients.H.
Referenced by adjointkOmegaSST::addWallFunctionTerms(), nutkWallFunctionFvPatchScalarField::calcNut(), nutUWallFunctionFvPatchScalarField::calcNut(), and kaqRWallFunctionFvPatchScalarField::manipulateMatrix().
yPlusLam()
scalar yPlusLam () const inline noexcept
Definition at line 153 of file wallFunctionCoefficients.H.
Referenced by adjointkOmegaSST::addWallFunctionTerms(), nutkWallFunctionFvPatchScalarField::calcNut(), nutUWallFunctionFvPatchScalarField::calcNut(), atmEpsilonWallFunctionFvPatchScalarField::calculate(), and kaqRWallFunctionFvPatchScalarField::manipulateMatrix().
writeEntries()
void writeEntries (Ostream & os) const
Definition at line 80 of file wallFunctionCoefficients.C.
References os(), and Ostream::writeEntryIfDifferent().
Referenced by kLowReWallFunctionFvPatchScalarField::writeLocalEntries().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/derivedFvPatchFields/wallFunctions/wallFunction/wallFunctionCoefficients/wallFunctionCoefficients.H
src/TurbulenceModels/turbulenceModels/derivedFvPatchFields/wallFunctions/wallFunction/wallFunctionCoefficients/wallFunctionCoefficients.C