OpenFOAM: SIBase Class Reference
SIBase Class Reference abstract
Base class for Surface Integral-based sensitivity derivatives.
#include <SIBaseIncompressible.H>
Public Member Functions
TypeName ("volumetricBSplinesFI")
SIBase (const fvMesh &mesh, const dictionary &dict, incompressibleAdjointSolver &adjointSolver)
virtual ~SIBase ()=default
virtual bool readDict (const dictionary &dict)
virtual void accumulateIntegrand (const scalar dt)
virtual void assembleSensitivities ()=0
virtual void clearSensitivities ()
const sensitivitySurface & getSurfaceSensitivities () const
virtual void write (const word &baseName=word::null)
Public Member Functions inherited from shapeSensitivities
TypeName ("shapeSensitivities")
shapeSensitivities (const fvMesh &mesh, const dictionary &dict, incompressibleAdjointSolver &adjointSolver)
virtual ~shapeSensitivities ()=default
Public Member Functions inherited from adjointSensitivity
TypeName ("adjointSensitivity")
declareRunTimeSelectionTable (autoPtr, adjointSensitivity, dictionary,(const fvMesh &mesh, const dictionary &dict, incompressibleAdjointSolver &adjointSolver),(mesh, dict, adjointSolver))
adjointSensitivity (const fvMesh &mesh, const dictionary &dict, incompressibleAdjointSolver &adjointSolver)
virtual ~adjointSensitivity ()=default
const incompressibleVars & primalVars () const
const incompressibleAdjointVars & adjointVars () const
const incompressibleAdjointSolver & adjointSolver () const
virtual const scalarField & calculateSensitivities ()
const scalarField & getSensitivities () const
tmp< volTensorField > computeGradDxDbMultiplier ()
tmp< volVectorField > adjointMeshMovementSource ()
Public Member Functions inherited from sensitivity
TypeName ("sensitivity")
sensitivity (const fvMesh &mesh, const dictionary &dict)
virtual ~sensitivity ()=default
const dictionary & dict () const
virtual void computeDerivativesSize ()
Protected Member Functions
void read ()
Protected Member Functions inherited from shapeSensitivities
virtual void accumulateDirectSensitivityIntegrand (const scalar dt)
virtual void accumulateBCSensitivityIntegrand (const scalar dt)
tmp< boundaryVectorField > dvdbMult () const
Protected Attributes
sensitivitySurface surfaceSensitivity_
bool includeObjective_
bool writeSensitivityMap_
Protected Attributes inherited from shapeSensitivities
autoPtr< boundaryVectorField > dSfdbMult_
autoPtr< boundaryVectorField > dnfdbMult_
autoPtr< boundaryVectorField > dxdbDirectMult_
autoPtr< boundaryVectorField > bcDxDbMult_
Protected Attributes inherited from adjointSensitivity
scalarField derivatives_
incompressibleAdjointSolver & adjointSolver_
const incompressibleVars & primalVars_
incompressibleAdjointVars & adjointVars_
objectiveManager & objectiveManager_
Protected Attributes inherited from sensitivity
const fvMesh & mesh_
dictionary dict_
autoPtr< volScalarField > fieldSensPtr_
Additional Inherited Members
Static Public Member Functions inherited from adjointSensitivity
static autoPtr< adjointSensitivity > New (const fvMesh &mesh, const dictionary &dict, incompressibleAdjointSolver &adjointSolver)
Detailed Description
Base class for Surface Integral-based sensitivity derivatives.
Source files
SIBaseIncompressible.H
SIBase.C
Definition at line 53 of file SIBaseIncompressible.H.
Constructor & Destructor Documentation
SIBase()
SIBase (const fvMesh & mesh, const dictionary & dict, incompressibleAdjointSolver & adjointSolver)
Definition at line 71 of file SIBaseIncompressible.C.
References SIBase::read().
~SIBase()
virtual ~SIBase () virtual default
Member Function Documentation
read()
void read () protected
Definition at line 41 of file SIBaseIncompressible.C.
References sensitivity::dict(), Foam::endl(), sensitivitySurface::getIncludeObjective(), SIBase::includeObjective_, Foam::nl, sensitivitySurface::read(), sensitivitySurface::setIncludeObjective(), sensitivitySurface::setIncludeSurfaceArea(), SIBase::surfaceSensitivity_, WarningInFunction, and SIBase::writeSensitivityMap_.
Referenced by SIBase::SIBase().
TypeName()
TypeName ("volumetricBSplinesFI")
readDict()
bool readDict (const dictionary & dict) virtual
Reimplemented from sensitivity.
Definition at line 98 of file SIBaseIncompressible.C.
References sensitivity::dict(), sensitivitySurface::readDict(), sensitivity::readDict(), and SIBase::surfaceSensitivity_.
accumulateIntegrand()
void accumulateIntegrand (const scalar dt) virtual
Implements shapeSensitivities.
Definition at line 114 of file SIBaseIncompressible.C.
References shapeSensitivities::accumulateBCSensitivityIntegrand(), shapeSensitivities::accumulateDirectSensitivityIntegrand(), sensitivitySurface::accumulateIntegrand(), SIBase::includeObjective_, and SIBase::surfaceSensitivity_.
assembleSensitivities()
virtual void assembleSensitivities () pure virtual
Implements shapeSensitivities.
Implemented in sensitivityBezier, and sensitivityVolBSplines.
clearSensitivities()
void clearSensitivities () virtual
Reimplemented from shapeSensitivities.
Reimplemented in sensitivityBezier, and sensitivityVolBSplines.
Definition at line 130 of file SIBaseIncompressible.C.
References sensitivitySurface::clearSensitivities(), shapeSensitivities::clearSensitivities(), and SIBase::surfaceSensitivity_.
Referenced by sensitivityBezier::clearSensitivities(), and sensitivityVolBSplines::clearSensitivities().
getSurfaceSensitivities()
const sensitivitySurface & getSurfaceSensitivities () const
Definition at line 137 of file SIBaseIncompressible.C.
References SIBase::surfaceSensitivity_.
write()
void write (const word & baseName = word::null) virtual
Reimplemented from shapeSensitivities.
Reimplemented in sensitivityBezier, and sensitivityVolBSplines.
Definition at line 143 of file SIBaseIncompressible.C.
References SIBase::surfaceSensitivity_, sensitivitySurface::write(), shapeSensitivities::write(), and SIBase::writeSensitivityMap_.
Referenced by sensitivityBezier::write(), and sensitivityVolBSplines::write().
Member Data Documentation
surfaceSensitivity_
sensitivitySurface surfaceSensitivity_ protected
Definition at line 62 of file SIBaseIncompressible.H.
Referenced by SIBase::accumulateIntegrand(), sensitivityBezier::assembleSensitivities(), sensitivityVolBSplines::assembleSensitivities(), SIBase::clearSensitivities(), SIBase::getSurfaceSensitivities(), SIBase::read(), SIBase::readDict(), and SIBase::write().
includeObjective_
bool includeObjective_ protected
Definition at line 68 of file SIBaseIncompressible.H.
Referenced by SIBase::accumulateIntegrand(), sensitivityBezier::assembleSensitivities(), sensitivityVolBSplines::computeObjectiveContributions(), and SIBase::read().
writeSensitivityMap_
bool writeSensitivityMap_ protected
Definition at line 71 of file SIBaseIncompressible.H.
Referenced by SIBase::read(), and SIBase::write().
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/optimisation/adjointSensitivity/incompressible/SIBase/SIBaseIncompressible.H
src/optimisation/adjointOptimisation/adjoint/optimisation/adjointSensitivity/incompressible/SIBase/SIBaseIncompressible.C