OpenFOAM: partitioningModel Class Reference
partitioningModel Class Reference abstract
Base class for wall heat flux partitioning models.
#include <partitioningModel.H>
Public Member Functions
TypeName ("partitioningModel")
declareRunTimeSelectionTable (autoPtr, partitioningModel, dictionary,(const dictionary &dict),(dict))
partitioningModel ()=default
virtual ~partitioningModel ()=default
virtual tmp< scalarField > fLiquid (const scalarField &alphaLiquid) const =0
virtual void write (Ostream &os) const
Static Public Member Functions
static autoPtr< partitioningModel > New (const dictionary &dict)
Detailed Description
Base class for wall heat flux partitioning models.
Source files
partitioningModel.H
partitioningModel.C
Definition at line 51 of file partitioningModel.H.
Constructor & Destructor Documentation
partitioningModel()
partitioningModel () default
~partitioningModel()
virtual ~partitioningModel () virtual default
Member Function Documentation
TypeName()
TypeName ("partitioningModel")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , partitioningModel , dictionary , (const dictionary &dict) , (dict))
New()
Foam::autoPtr< Foam::wallBoilingModels::partitioningModel > New (const dictionary & dict) static
Definition at line 39 of file partitioningModel.C.
References Foam::abort(), dict, Foam::endl(), Foam::FatalIOError, FatalIOErrorInLookup, and Foam::Info.
Referenced by alphatWallBoilingWallFunctionFvPatchScalarField::alphatWallBoilingWallFunctionFvPatchScalarField().
fLiquid()
virtual tmp< scalarField > fLiquid (const scalarField & alphaLiquid) const pure virtual
Implemented in cosine, Lavieville, linear, and phaseFraction.
write()
void write (Ostream & os) const virtual
Reimplemented in cosine, Lavieville, and linear.
Definition at line 68 of file partitioningModel.C.
References os(), and Foam::type().
Referenced by cosine::write(), Lavieville::write(), and linear::write().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/wallBoilingSubModels/partitioningModels/partitioningModel/partitioningModel.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/wallBoilingSubModels/partitioningModels/partitioningModel/partitioningModel.C