OpenFOAM: energyScalingFunction Class Reference
energyScalingFunction Class Reference abstract
#include <energyScalingFunction.H>
Public Member Functions
TypeName ("energyScalingFunction")
declareRunTimeSelectionTable (autoPtr, energyScalingFunction, dictionary,(const word &name, const dictionary &energyScalingFunctionProperties, const pairPotential &pairPot),(name, energyScalingFunctionProperties, pairPot))
energyScalingFunction (const word &name, const dictionary &energyScalingFunctionProperties, const pairPotential &pairPot)
virtual ~energyScalingFunction ()=default
virtual void scaleEnergy (scalar &e, const scalar r) const =0
const dictionary & energyScalingFunctionProperties () const
virtual bool read (const dictionary &energyScalingFunctionProperties)=0
Static Public Member Functions
static autoPtr< energyScalingFunction > New (const word &name, const dictionary &energyScalingFunctionProperties, const pairPotential &pairPot)
Protected Member Functions
energyScalingFunction (const energyScalingFunction &)=delete
void operator= (const energyScalingFunction &)=delete
Protected Attributes
word name_
dictionary energyScalingFunctionProperties_
const pairPotential & pairPot_
Detailed Description
Source files
energyScalingFunction.H
energyScalingFunction.C
energyScalingFunctionNew.C
Definition at line 51 of file energyScalingFunction.H.
Constructor & Destructor Documentation
energyScalingFunction() [1/2]
energyScalingFunction (const energyScalingFunction &) protected delete
energyScalingFunction() [2/2]
energyScalingFunction (const word & name, const dictionary & energyScalingFunctionProperties, const pairPotential & pairPot)
Definition at line 34 of file energyScalingFunction.C.
References Foam::name().
~energyScalingFunction()
virtual ~energyScalingFunction () virtual default
Member Function Documentation
operator=()
void operator= (const energyScalingFunction &) protected delete
TypeName()
TypeName ("energyScalingFunction")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , energyScalingFunction , dictionary , (const word &name, const dictionary &energyScalingFunctionProperties, const pairPotential &pairPot) , (name, energyScalingFunctionProperties, pairPot))
New()
Foam::autoPtr< Foam::energyScalingFunction > New (const word & name, const dictionary & energyScalingFunctionProperties, const pairPotential & pairPot) static
Definition at line 27 of file energyScalingFunctionNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, Foam::Info, and Foam::name().
Referenced by pairPotential::scaleEnergy().
scaleEnergy()
virtual void scaleEnergy (scalar & e, const scalar r) const pure virtual
Implemented in doubleSigmoid, noScaling, shifted, shiftedForce, and sigmoid.
Referenced by pairPotential::scaleEnergy().
energyScalingFunctionProperties()
const dictionary & energyScalingFunctionProperties () const inline
Definition at line 126 of file energyScalingFunction.H.
References energyScalingFunction::energyScalingFunctionProperties_.
Referenced by doubleSigmoid::read(), noScaling::read(), shifted::read(), shiftedForce::read(), and sigmoid::read().
read()
bool read (const dictionary & energyScalingFunctionProperties) pure virtual
Implemented in doubleSigmoid, noScaling, shifted, shiftedForce, and sigmoid.
Definition at line 50 of file energyScalingFunction.C.
Referenced by doubleSigmoid::read(), noScaling::read(), shifted::read(), shiftedForce::read(), and sigmoid::read().
Member Data Documentation
name_
word name_ protected
Definition at line 58 of file energyScalingFunction.H.
energyScalingFunctionProperties_
dictionary energyScalingFunctionProperties_ protected
Definition at line 60 of file energyScalingFunction.H.
Referenced by energyScalingFunction::energyScalingFunctionProperties().
pairPot_
const pairPotential& pairPot_ protected
Definition at line 62 of file energyScalingFunction.H.
The documentation for this class was generated from the following files:
src/lagrangian/molecularDynamics/potential/energyScalingFunction/basic/energyScalingFunction.H
src/lagrangian/molecularDynamics/potential/energyScalingFunction/basic/energyScalingFunction.C
src/lagrangian/molecularDynamics/potential/energyScalingFunction/basic/energyScalingFunctionNew.C