OpenFOAM: outletMachNumberPressureFvPatchScalarField Class Reference
outletMachNumberPressureFvPatchScalarField Class Reference
Boundary conditions » Outlet
This boundary condition maintains a certain subsonic Mach number at an outlet patch by dynamically adjusting the static outlet pressure. It makes it possible, for example, to simulate the flow in a preturbine engine exhaust manifold, without resolving details of the flow inside the turbine. In general, the flow in a choked nozzle can be non-trivial and expensive to simulate.
#include <outletMachNumberPressureFvPatchScalarField.H>
Public Member Functions
TypeName ("outletMachNumberPressure")
outletMachNumberPressureFvPatchScalarField (const fvPatch &p, const DimensionedField< scalar, volMesh > &iF)
outletMachNumberPressureFvPatchScalarField (const fvPatch &p, const DimensionedField< scalar, volMesh > &iF, const dictionary &dict)
outletMachNumberPressureFvPatchScalarField (const outletMachNumberPressureFvPatchScalarField &ptf, const fvPatch &p, const DimensionedField< scalar, volMesh > &iF, const fvPatchFieldMapper &mapper)
outletMachNumberPressureFvPatchScalarField (const outletMachNumberPressureFvPatchScalarField &tppsf)
virtual tmp< fvPatchScalarField > clone () const
outletMachNumberPressureFvPatchScalarField (const outletMachNumberPressureFvPatchScalarField &tppsf, const DimensionedField< scalar, volMesh > &iF)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual void updateCoeffs ()
virtual void write (Ostream &os) const
Detailed Description
This boundary condition maintains a certain subsonic Mach number at an outlet patch by dynamically adjusting the static outlet pressure. It makes it possible, for example, to simulate the flow in a preturbine engine exhaust manifold, without resolving details of the flow inside the turbine. In general, the flow in a choked nozzle can be non-trivial and expensive to simulate.
This formulation is derived from a simple model of the gas flow through a nozzle with fixed geometry. The nozzle flow is assumed to be quasi-steady, 1D, isentropic and compressible.
This gives the following general relationship between pressure ratio and Mach number in any cross section inside the nozzle:
where the constant ratio of heat capacities is . The Mach number in the cross section is , where is the speed of sound and V is the uniform velocity in the streamwise direction.
Overall pressure difference across the nozzle is
When , the flow in the nozzle throat becomes choked when and non-choked otherwise. This implementation is not applicable when where backflow would occur.
The nozzle model assumption locks the relationship between nozzle cross sectional areas and Mach numbers. For a choked flow it is only the Mach number on the outlet patch, , that needs to be stated in the boundary dictionary.
Care should be taken however to ensure that the entries in the input dictionary and the CFD geometry satisfy the following equation
where compensate for non-uniform outlet profiles, is geometrical outlet patch area and is assumed nozzle throat area.
In the non-choked case the outlet patch Mach number is calculated as
The accompanying boundary conditions for velocity should be pressureInletOutletVelocity.
Author: Jens Dahl Kunoy
Reference:
   Fox, R.W & McDonald, A. T. (1994).
   Introduction to Fluid Mechanics (4ed SI).
   Wiley
Usage
Property Description Required Default value
choked Defines nozzle conditions Yes None
relax underrelaxation of static pressure Yes 0
M outlet Mach number Yes (choked) None
A1 Nozzle throat area [m2] Yes (non-choked) 0
pBack Pressure downstream of nozzle Yes (non-choked) None
c1 Correction factor for non-uniform profiles
No (non-choked) 0.0
Example of the boundary condition specification:
    <patchName>
    {
        type            outletMachNumberPressure;
        pBack           101325;
        c1              1;
        A1              0.008;
        relax           0.1;
        choked          false;
        value           uniform 200000;
    }
Source files
outletMachNumberPressureFvPatchScalarField.H
outletMachNumberPressureFvPatchScalarField.C
Definition at line 178 of file outletMachNumberPressureFvPatchScalarField.H.
Constructor & Destructor Documentation
outletMachNumberPressureFvPatchScalarField() [1/5]
outletMachNumberPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 31 of file outletMachNumberPressureFvPatchScalarField.C.
outletMachNumberPressureFvPatchScalarField() [2/5]
outletMachNumberPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 51 of file outletMachNumberPressureFvPatchScalarField.C.
outletMachNumberPressureFvPatchScalarField() [3/5]
outletMachNumberPressureFvPatchScalarField (const outletMachNumberPressureFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 72 of file outletMachNumberPressureFvPatchScalarField.C.
outletMachNumberPressureFvPatchScalarField() [4/5]
outletMachNumberPressureFvPatchScalarField (const outletMachNumberPressureFvPatchScalarField & tppsf)
Definition at line 94 of file outletMachNumberPressureFvPatchScalarField.C.
outletMachNumberPressureFvPatchScalarField() [5/5]
outletMachNumberPressureFvPatchScalarField (const outletMachNumberPressureFvPatchScalarField & tppsf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 113 of file outletMachNumberPressureFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("outletMachNumberPressure")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 252 of file outletMachNumberPressureFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 268 of file outletMachNumberPressureFvPatchScalarField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 135 of file outletMachNumberPressureFvPatchScalarField.C.
References basicThermo::dictName, Foam::dimMass, Foam::dimTime, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, gamma, Foam::gAverage(), Foam::gSum(), M, Foam::mag(), GeometricField< Type, PatchField, GeoMesh >::oldTime(), Foam::operator==(), p, phi, Foam::pow(), rho, Foam::sqr(), Foam::sqrt(), U, and WarningInFunction.
write()
void write (Ostream & os) const virtual
Definition at line 238 of file outletMachNumberPressureFvPatchScalarField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntry(), Ostream::writeEntryIfDifferent(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/thermoTools/derivedFvPatchFields/outletMachNumberPressure/outletMachNumberPressureFvPatchScalarField.H
src/thermoTools/derivedFvPatchFields/outletMachNumberPressure/outletMachNumberPressureFvPatchScalarField.C