OpenFOAM: limitedSurfaceInterpolationScheme< Type > Class Template Reference
limitedSurfaceInterpolationScheme< Type > Class Template Reference abstract
Numerics » Finite volume numerical schemes » Surface interpolation schemes » Limited interpolation schemes
Abstract base class for limited surface interpolation schemes.
#include <limitedSurfaceInterpolationScheme.H>
Public Member Functions
TypeName ("limitedSurfaceInterpolationScheme")
declareRunTimeSelectionTable (tmp, limitedSurfaceInterpolationScheme, Mesh,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
declareRunTimeSelectionTable (tmp, limitedSurfaceInterpolationScheme, MeshFlux,(const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
limitedSurfaceInterpolationScheme (const fvMesh &mesh, const surfaceScalarField &faceFlux)
limitedSurfaceInterpolationScheme (const fvMesh &mesh, Istream &is)
virtual ~limitedSurfaceInterpolationScheme ()
virtual tmp< surfaceScalarField > limiter (const GeometricField< Type, fvPatchField, volMesh > &) const =0
tmp< surfaceScalarField > weights (const GeometricField< Type, fvPatchField, volMesh > &, const surfaceScalarField &CDweights, tmp< surfaceScalarField > tLimiter) const
virtual tmp< surfaceScalarField > weights (const GeometricField< Type, fvPatchField, volMesh > &) const
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const GeometricField< Type, fvPatchField, volMesh > &) const
Public Member Functions inherited from surfaceInterpolationScheme< Type >
TypeName ("surfaceInterpolationScheme")
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, Mesh,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, MeshFlux,(const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
surfaceInterpolationScheme (const fvMesh &mesh)
virtual ~surfaceInterpolationScheme ()=default
const fvMesh & mesh () const
virtual bool corrected () const
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > &) const
virtual tmp< GeometricField< typename innerProduct< vector, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf) const
tmp< GeometricField< typename innerProduct< vector, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const tmp< GeometricField< Type, fvPatchField, volMesh > > &) const
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &) const
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > &) const
template<class SFType >
Foam::tmp< Foam::GeometricField< typename Foam::innerProduct< typename SFType::value_type, Type >::type, Foam::fvsPatchField, Foam::surfaceMesh > > dotInterpolate (const SFType &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf, const tmp< surfaceScalarField > &tlambdas)
tmp< GeometricField< typename innerProduct< vector, scalar >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const GeometricField< scalar, fvPatchField, volMesh > &) const
Foam::tmp< Foam::GeometricField< typename Foam::innerProduct< Foam::vector, Foam::scalar >::type, Foam::fvsPatchField, Foam::surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const GeometricField< scalar, fvPatchField, volMesh > &) const
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Static Public Member Functions
static tmp< limitedSurfaceInterpolationScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
static tmp< limitedSurfaceInterpolationScheme< Type > > New (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData)
Static Public Member Functions inherited from surfaceInterpolationScheme< Type >
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData)
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &, const tmp< surfaceScalarField > &)
template<class SFType >
static tmp< GeometricField< typename innerProduct< typename SFType::value_type, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const SFType &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf, const tmp< surfaceScalarField > &tlambdas)
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &)
Protected Attributes
const surfaceScalarField & faceFlux_
Detailed Description
template<class Type>
class Foam::limitedSurfaceInterpolationScheme< Type >
Abstract base class for limited surface interpolation schemes.
Source files
limitedSurfaceInterpolationScheme.H
limitedSurfaceInterpolationScheme.C
Definition at line 50 of file limitedSurfaceInterpolationScheme.H.
Constructor & Destructor Documentation
limitedSurfaceInterpolationScheme() [1/2]
template<class Type > limitedSurfaceInterpolationScheme (const fvMesh & mesh, const surfaceScalarField & faceFlux) inline
Definition at line 110 of file limitedSurfaceInterpolationScheme.H.
limitedSurfaceInterpolationScheme() [2/2]
template<class Type > limitedSurfaceInterpolationScheme (const fvMesh & mesh, Istream & is) inline
Definition at line 124 of file limitedSurfaceInterpolationScheme.H.
~limitedSurfaceInterpolationScheme()
template<class Type > ~limitedSurfaceInterpolationScheme () virtual
Definition at line 120 of file limitedSurfaceInterpolationScheme.C.
Member Function Documentation
TypeName()
template<class Type > TypeName ("limitedSurfaceInterpolationScheme< Type >")
declareRunTimeSelectionTable() [1/2]
template<class Type > declareRunTimeSelectionTable (tmp , limitedSurfaceInterpolationScheme< Type > , Mesh , (const fvMesh &mesh, Istream &schemeData) , (mesh, schemeData))
declareRunTimeSelectionTable() [2/2]
template<class Type > declareRunTimeSelectionTable (tmp , limitedSurfaceInterpolationScheme< Type > , MeshFlux , (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData) , (mesh, faceFlux, schemeData))
New() [1/2]
template<class Type > Foam::tmp< Foam::limitedSurfaceInterpolationScheme< Type > > New (const fvMesh & mesh, Istream & schemeData) static
Definition at line 31 of file limitedSurfaceInterpolationScheme.C.
References Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, FatalIOErrorInLookup, InfoInFunction, mesh, and PtrList< T >::PtrList().
New() [2/2]
template<class Type > Foam::tmp< Foam::limitedSurfaceInterpolationScheme< Type > > New (const fvMesh & mesh, const surfaceScalarField & faceFlux, Istream & schemeData) static
Definition at line 74 of file limitedSurfaceInterpolationScheme.C.
References Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, FatalIOErrorInLookup, InfoInFunction, and mesh.
limiter()
template<class Type > virtual tmp< surfaceScalarField > limiter (const GeometricField< Type, fvPatchField, volMesh > &) const pure virtual
Implemented in blended< Type >, LimitedScheme< Type, Limiter, LimitFunc >, PhiScheme< Type, PhiLimiter >, and upwind< Type >.
weights() [1/2]
template<class Type > Foam::tmp< Foam::surfaceScalarField > weights (const GeometricField< Type, fvPatchField, volMesh > & phi, const surfaceScalarField & CDweights, tmp< surfaceScalarField > tLimiter) const
Definition at line 129 of file limitedSurfaceInterpolationScheme.C.
References forAll, and Foam::pos0().
weights() [2/2]
template<class Type > Foam::tmp< Foam::surfaceScalarField > weights (const GeometricField< Type, fvPatchField, volMesh > & phi) const virtual
Implements surfaceInterpolationScheme< Type >.
Reimplemented in upwind< Type >, LUST< Type >, and blended< Type >.
Definition at line 172 of file limitedSurfaceInterpolationScheme.C.
References Foam::limiter(), mesh, phi, and surfaceInterpolation::weights().
flux()
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > flux (const GeometricField< Type, fvPatchField, volMesh > & phi) const virtual
Definition at line 187 of file limitedSurfaceInterpolationScheme.C.
References Foam::interpolate().
Member Data Documentation
faceFlux_
template<class Type > const surfaceScalarField& faceFlux_ protected
Definition at line 70 of file limitedSurfaceInterpolationScheme.H.
Referenced by PureUpwindFitScheme< Type, Polynomial, Stencil >::correction(), upwind< Type >::weights(), and blended< Type >::weights().
The documentation for this class was generated from the following files:
src/finiteVolume/interpolation/surfaceInterpolation/limitedSchemes/limitedSurfaceInterpolationScheme/limitedSurfaceInterpolationScheme.H
src/finiteVolume/interpolation/surfaceInterpolation/limitedSchemes/limitedSurfaceInterpolationScheme/limitedSurfaceInterpolationScheme.C