OpenFOAM: minMaxCondition Class Reference
minMaxCondition Class Reference
#include <minMaxCondition.H>
Public Types
enum modeType { mdMin , mdMax }
Public Member Functions
TypeName ("minMax")
minMaxCondition (const word &name, const objectRegistry &obr, const dictionary &dict, stateFunctionObject &state)
virtual ~minMaxCondition ()=default
virtual bool apply ()
virtual void write ()
virtual void reset ()
Public Member Functions inherited from runTimeCondition
TypeName ("runTimeCondition")
declareRunTimeSelectionTable (autoPtr, runTimeCondition, dictionary,(const word &name, const objectRegistry &obr, const dictionary &dict, stateFunctionObject &state),(name, obr, dict, state))
runTimeCondition (const word &name, const objectRegistry &obr, const dictionary &dict, stateFunctionObject &state)
virtual ~runTimeCondition ()=default
virtual const word & name () const
virtual bool active () const
virtual label groupID () const
Static Public Attributes
static const Enum< modeType > modeTypeNames_
Protected Member Functions
template<class Type >
void setValue (const word &valueType, const word &fieldName, scalar &value) const
Protected Member Functions inherited from runTimeCondition
dictionary & setConditionDict ()
const dictionary & conditionDict () const
dictionary & conditionDict ()
Protected Attributes
word functionObjectName_
modeType mode_
const wordList fieldNames_
const scalar value_
Protected Attributes inherited from runTimeCondition
word name_
const objectRegistry & obr_
stateFunctionObject & state_
bool active_
dictionary & conditionDict_
label groupID_
Additional Inherited Members
Static Public Member Functions inherited from runTimeCondition
static autoPtr< runTimeCondition > New (const word &conditionName, const objectRegistry &obr, const dictionary &dict, stateFunctionObject &state)
Public Attributes inherited from runTimeCondition
Switch log
Detailed Description
Definition at line 54 of file minMaxCondition.H.
Member Enumeration Documentation
modeType
enum modeType
Enumerator
mdMin
Minimum.
mdMax
Maximum.
Definition at line 63 of file minMaxCondition.H.
Constructor & Destructor Documentation
minMaxCondition()
minMaxCondition (const word & name, const objectRegistry & obr, const dictionary & dict, stateFunctionObject & state)
Definition at line 73 of file minMaxCondition.C.
References Foam::name().
~minMaxCondition()
virtual ~minMaxCondition () virtual default
Member Function Documentation
setValue()
template<class Type > void setValue (const word & valueType, const word & fieldName, scalar & value) const protected
Definition at line 25 of file minMaxConditionTemplates.C.
References minMaxCondition::functionObjectName_, stateFunctionObject::getObjectResult(), and runTimeCondition::state_.
TypeName()
TypeName ("minMax")
apply()
bool apply () virtual
Implements runTimeCondition.
Definition at line 91 of file minMaxCondition.C.
References Foam::endl(), Log, word::null, Foam::type(), and WarningInFunction.
write()
void write () virtual
Implements runTimeCondition.
Definition at line 156 of file minMaxCondition.C.
reset()
void reset () virtual
Implements runTimeCondition.
Definition at line 162 of file minMaxCondition.C.
Member Data Documentation
modeTypeNames_
const Foam::Enum< Foam::functionObjects::runTimeControls::minMaxCondition::modeType > modeTypeNames_ static
Definition at line 69 of file minMaxCondition.H.
functionObjectName_
word functionObjectName_ protected
Definition at line 77 of file minMaxCondition.H.
Referenced by minMaxCondition::setValue().
mode_
modeType mode_ protected
Definition at line 80 of file minMaxCondition.H.
fieldNames_
const wordList fieldNames_ protected
Definition at line 83 of file minMaxCondition.H.
value_
const scalar value_ protected
Definition at line 86 of file minMaxCondition.H.
The documentation for this class was generated from the following files:
src/functionObjects/utilities/runTimeControl/runTimeCondition/minMaxCondition/minMaxCondition.H
src/functionObjects/utilities/runTimeControl/runTimeCondition/minMaxCondition/minMaxCondition.C
src/functionObjects/utilities/runTimeControl/runTimeCondition/minMaxCondition/minMaxConditionTemplates.C