OpenFOAM: MeshedSurfaceIOAllocator Class Reference
MeshedSurfaceIOAllocator Class Reference
A helper class for storing points and faces with IO capabilities.
#include <MeshedSurfaceIOAllocator.H>
Public Member Functions
MeshedSurfaceIOAllocator (const IOobject &ioPoints, const IOobject &ioFaces)
MeshedSurfaceIOAllocator (const IOobject &ioPoints, const pointField &points, const IOobject &ioFaces, const faceList &faces)
MeshedSurfaceIOAllocator (const IOobject &ioPoints, pointField &&points, const IOobject &ioFaces, faceList &&faces)
virtual ~MeshedSurfaceIOAllocator ()
void setInstance (const fileName &inst)
void setWriteOption (IOobjectOption::writeOption wOpt)
pointIOField & storedIOPoints ()
faceCompactIOList & storedIOFaces ()
const pointIOField & storedIOPoints () const
const faceCompactIOList & storedIOFaces () const
void clear ()
virtual bool writeObject (IOstreamOption streamOpt, const bool writeOnProc) const
Detailed Description
A helper class for storing points and faces with IO capabilities.
Source files
MeshedSurfaceIOAllocator.H
MeshedSurfaceIOAllocator.C
Definition at line 50 of file MeshedSurfaceIOAllocator.H.
Constructor & Destructor Documentation
MeshedSurfaceIOAllocator() [1/3]
MeshedSurfaceIOAllocator (const IOobject & ioPoints, const IOobject & ioFaces)
Definition at line 26 of file MeshedSurfaceIOAllocator.C.
MeshedSurfaceIOAllocator() [2/3]
MeshedSurfaceIOAllocator (const IOobject & ioPoints, const pointField & points, const IOobject & ioFaces, const faceList & faces)
Definition at line 37 of file MeshedSurfaceIOAllocator.C.
MeshedSurfaceIOAllocator() [3/3]
MeshedSurfaceIOAllocator (const IOobject & ioPoints, pointField && points, const IOobject & ioFaces, faceList && faces)
Definition at line 48 of file MeshedSurfaceIOAllocator.C.
~MeshedSurfaceIOAllocator()
~MeshedSurfaceIOAllocator () virtual
Definition at line 61 of file MeshedSurfaceIOAllocator.C.
References clear().
Member Function Documentation
setInstance()
void setInstance (const fileName & inst)
Definition at line 69 of file MeshedSurfaceIOAllocator.C.
Referenced by surfMesh::setInstance().
setWriteOption()
void setWriteOption (IOobjectOption::writeOption wOpt)
Definition at line 79 of file MeshedSurfaceIOAllocator.C.
storedIOPoints() [1/2]
pointIOField & storedIOPoints () inline
Definition at line 114 of file MeshedSurfaceIOAllocator.H.
Referenced by surfMesh::storedPoints().
storedIOFaces() [1/2]
faceCompactIOList & storedIOFaces () inline
Definition at line 120 of file MeshedSurfaceIOAllocator.H.
Referenced by surfMesh::storedFaces().
storedIOPoints() [2/2]
const pointIOField & storedIOPoints () const inline
Definition at line 126 of file MeshedSurfaceIOAllocator.H.
storedIOFaces() [2/2]
const faceCompactIOList & storedIOFaces () const inline
Definition at line 132 of file MeshedSurfaceIOAllocator.H.
clear()
void clear ()
Definition at line 89 of file MeshedSurfaceIOAllocator.C.
References PtrList< T >::clear().
writeObject()
bool writeObject (IOstreamOption streamOpt, const bool writeOnProc) const virtual
Reimplemented in surfMesh.
Definition at line 96 of file MeshedSurfaceIOAllocator.C.
The documentation for this class was generated from the following files:
src/surfMesh/MeshedSurfaceAllocator/MeshedSurfaceIOAllocator.H
src/surfMesh/MeshedSurfaceAllocator/MeshedSurfaceIOAllocator.C