OpenFOAM: cloudInfo Class Reference
cloudInfo Class Reference
FunctionObjects » Lagrangian function objects
Outputs Lagrangian cloud information to a file.
#include <cloudInfo.H>
Public Member Functions
TypeName ("cloudInfo")
cloudInfo (const word &name, const Time &runTime, const dictionary &)
virtual ~cloudInfo ()=default
virtual bool read (const dictionary &dict)
virtual bool execute ()
virtual bool write ()
Public Member Functions inherited from regionFunctionObject
TypeName ("regionFunctionObject")
regionFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
regionFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
virtual ~regionFunctionObject ()=default
template<class ObjectType >
const ObjectType * lookupObjectPtr (const word &fieldName) const
template<class ObjectType >
ObjectType * lookupObjectRefPtr (const word &fieldName) const
Public Member Functions inherited from stateFunctionObject
stateFunctionObject (const word &name, const Time &runTime)
virtual ~stateFunctionObject ()=default
dictionary & propertyDict ()
bool foundProperty (const word &entryName) const
void clearTrigger ()
label getTrigger () const
bool setTrigger (const label triggeri)
bool getDict (const word &entryName, dictionary &dict) const
bool getObjectDict (const word &objectName, const word &entryName, dictionary &dict) const
template<class Type >
Type getProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getProperty (const word &entryName, Type &value) const
template<class Type >
void setProperty (const word &entryName, const Type &value)
template<class Type >
Type getObjectProperty (const word &objectName, const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getObjectProperty (const word &objectName, const word &entryName, Type &value) const
template<class Type >
void setObjectProperty (const word &objectName, const word &entryName, const Type &value)
template<class Type >
void setResult (const word &entryName, const Type &value)
template<class Type >
void setObjectResult (const word &objectName, const word &entryName, const Type &value)
template<class Type >
Type getResult (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
Type getObjectResult (const word &objectName, const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getObjectResult (const word &objectName, const word &entryName, Type &value) const
word resultType (const word &entryName) const
word objectResultType (const word &objectName, const word &entryName) const
wordList objectResultEntries () const
wordList objectResultEntries (const word &objectName) const
void writeResultEntries (Ostream &os) const
void writeResultEntries (const word &objectName, Ostream &os) const
void writeAllResultEntries (Ostream &os) const
Public Member Functions inherited from timeFunctionObject
timeFunctionObject (const word &name, const Time &runTime)
virtual ~timeFunctionObject ()=default
const Time & time () const
objectRegistry & storedObjects ()
const objectRegistry & storedObjects () const
Public Member Functions inherited from functionObject
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name, const bool withNamePrefix=defaultUseNamePrefix)
autoPtr< functionObject > clone () const
virtual ~functionObject ()=default
virtual const word & type () const =0
const word & name () const noexcept
bool useNamePrefix () const noexcept
bool useNamePrefix (bool on) noexcept
virtual bool execute (const label subIndex)
virtual bool end ()
virtual bool adjustTimeStep ()
virtual bool filesModified () const
virtual void updateMesh (const mapPolyMesh &mpm)
virtual void movePoints (const polyMesh &mesh)
Public Member Functions inherited from logFiles
logFiles (const objectRegistry &obr, const word &prefix)
logFiles (const objectRegistry &obr, const word &prefix, const dictionary &dict)
virtual ~logFiles ()=default
const wordList & names () const
PtrList< OFstream > & files ()
OFstream & files (const label i)
Public Member Functions inherited from writeFile
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name="undefined", const bool writeToFile=true)
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name, const dictionary &dict, const bool writeToFile=true)
writeFile (const writeFile &wf)
virtual ~writeFile ()=default
virtual OFstream & file ()
virtual bool writeToFile () const
virtual bool canWriteToFile () const
virtual bool canResetFile () const
virtual bool canWriteHeader () const
virtual label charWidth () const
virtual void writeCommented (Ostream &os, const string &str) const
virtual void writeTabbed (Ostream &os, const string &str) const
virtual void writeHeader (Ostream &os, const string &str) const
virtual void writeCurrentTime (Ostream &os) const
virtual void writeBreak (Ostream &os) const
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
template<class Type >
void writeValue (Ostream &os, const Type &val) const
Public Member Functions inherited from parcelSelection
parcelSelection ()=default
virtual ~parcelSelection ()=default
Protected Types
enum sampleActionType : unsigned { ACTION_NONE = 0 , ACTION_WRITE = 0x1 , ACTION_STORE = 0x2 , ACTION_ALL = 0xF }
Protected Member Functions
virtual void writeFileHeader (Ostream &os) const
bool performAction (unsigned request)
cloudInfo (const cloudInfo &)=delete
void operator= (const cloudInfo &)=delete
Protected Member Functions inherited from regionFunctionObject
virtual const objectRegistry & obr () const
template<class ObjectType >
bool foundObject (const word &fieldName) const
template<class ObjectType >
const ObjectType * cfindObject (const word &fieldName) const
template<class ObjectType >
const ObjectType * findObject (const word &fieldName) const
template<class ObjectType >
ObjectType * findObject (const word &fieldName)
template<class ObjectType >
ObjectType * getObjectPtr (const word &fieldName) const
template<class ObjectType >
const ObjectType & lookupObject (const word &fieldName) const
template<class ObjectType >
ObjectType & lookupObjectRef (const word &fieldName) const
template<class ObjectType >
bool store (word &fieldName, const tmp< ObjectType > &tfield, bool cacheable=false)
template<class ObjectType >
bool storeInDb (const word &fieldName, const tmp< ObjectType > &tfield, const objectRegistry &obr)
bool writeObject (const word &fieldName)
bool clearObject (const word &fieldName)
void clearObjects (const wordList &objNames)
regionFunctionObject (const regionFunctionObject &)=delete
void operator= (const regionFunctionObject &)=delete
Protected Member Functions inherited from stateFunctionObject
const functionObjects::properties & stateDict () const
functionObjects::properties & stateDict ()
stateFunctionObject (const stateFunctionObject &)=delete
void operator= (const stateFunctionObject &)=delete
Protected Member Functions inherited from timeFunctionObject
void clearOutputObjects (const wordList &objNames)
timeFunctionObject (const timeFunctionObject &)=delete
void operator= (const timeFunctionObject &)=delete
Protected Member Functions inherited from functionObject
word scopedName (const word &name) const
Protected Member Functions inherited from logFiles
virtual void createFiles ()
virtual void resetNames (const wordList &names)
virtual void resetName (const word &name)
Protected Member Functions inherited from writeFile
void initStream (Ostream &os) const
fileName baseFileDir () const
fileName baseTimeDir () const
fileName filePath (const fileName &fName) const
virtual autoPtr< OFstream > newFile (const fileName &fName) const
virtual autoPtr< OFstream > newFileAtTime (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > newFileAtStartTime (const word &name) const
virtual void resetFile (const word &name)
Omanip< int > valueWidth (const label offset=0) const
void operator= (const writeFile &)=delete
virtual autoPtr< OFstream > createFile (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > createFile (const word &name) const
Protected Member Functions inherited from parcelSelection
bool calculateFilter (const objectRegistry &obrTmp, const bool log=true)
Protected Attributes
bool verbose_
bool onExecute_
wordList cloudNames_
PtrList< OFstream > filePtrs_
Protected Attributes inherited from regionFunctionObject
word subRegistryName_
const objectRegistry & obr_
const objectRegistry * obrPtr_
Protected Attributes inherited from timeFunctionObject
const Time & time_
Protected Attributes inherited from logFiles
wordList names_
PtrList< OFstream > filePtrs_
Protected Attributes inherited from writeFile
const objectRegistry & fileObr_
const fileName prefix_
word fileName_
autoPtr< OFstream > filePtr_
label writePrecision_
bool writeToFile_
bool updateHeader_
bool writtenHeader_
bool useUserTime_
scalar startTime_
Protected Attributes inherited from parcelSelection
dictionary parcelSelect_
bitSet parcelAddr_
Additional Inherited Members
Public Types inherited from parcelSelection
enum actionType {
ALL , CLEAR , INVERT , ADD ,
SUBTRACT , SUBSET , USE , IGNORE
}
enum sourceType { FIELD , STRIDE }
enum logicType { AND , OR }
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &runTime, const dictionary &dict)
Public Attributes inherited from functionObject
bool log
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
static bool defaultUseNamePrefix
static word outputPrefix
Static Public Attributes inherited from writeFile
static label addChars = 8
Static Public Attributes inherited from parcelSelection
static const Enum< actionType > actionNames
static const Enum< sourceType > sourceNames
static const Enum< logicType > logicNames
Detailed Description
Outputs Lagrangian cloud information to a file.
The current outputs include:
total current number of parcels
total current mass of parcels
Usage
Example of function object specification:
cloudInfo1
{
    type        cloudInfo;
    libs        (lagrangianFunctionObjects);
    ...
    clouds
    (
        kinematicCloud1
        thermoCloud1
    );
}
Where the entries comprise:
Property Description Required Default
type type name: cloudInfo yes
clouds list of clouds names to process yes
selection Parcel selection control no empty-dict
sampleOnExecute Sample/report (on execute) without writing no false
The output data of each cloud is written to a file named <cloudName>.dat
See also
Foam::functionObject Foam::functionObjects::regionFunctionObject Foam::functionObjects::logFiles
Source files
cloudInfo.H
cloudInfo.C
Definition at line 115 of file cloudInfo.H.
Member Enumeration Documentation
sampleActionType
enum sampleActionType : unsigned protected
Enumerator
ACTION_NONE
ACTION_WRITE
ACTION_STORE
ACTION_ALL
Definition at line 126 of file cloudInfo.H.
Constructor & Destructor Documentation
cloudInfo() [1/2]
cloudInfo (const cloudInfo &) protected delete
cloudInfo() [2/2]
cloudInfo (const word & name, const Time & runTime, const dictionary & dict)
Definition at line 65 of file cloudInfo.C.
References dict, and cloudInfo::read().
~cloudInfo()
virtual ~cloudInfo () virtual default
Member Function Documentation
writeFileHeader()
void writeFileHeader (Ostream & os) const protected virtual
Definition at line 50 of file cloudInfo.C.
References Foam::endl(), os(), writeFile::writeCommented(), writeFile::writeHeader(), and writeFile::writeTabbed().
performAction()
bool performAction (unsigned request) protected
Definition at line 127 of file cloudInfo.C.
References cloudName(), doLocalCode, Foam::endl(), forAll, Log, Foam::max(), Foam::name(), Foam::nl, IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, os(), Foam::constant::mathematical::pi(), Foam::pow3(), Foam::reduce(), Foam::returnReduce(), rho, Foam::sqr(), token::TAB, Foam::type(), and Foam::Zero.
operator=()
void operator= (const cloudInfo &) protected delete
TypeName()
TypeName ("cloudInfo")
read()
bool read (const dictionary & dict) virtual
Reimplemented from regionFunctionObject.
Definition at line 83 of file cloudInfo.C.
References PtrList< T >::clear(), dict, Foam::endl(), forAll, Foam::Info, Foam::name(), Foam::nl, regionFunctionObject::read(), writeFile::read(), logFiles::resetNames(), and Foam::type().
Referenced by cloudInfo::cloudInfo().
execute()
bool execute () virtual
Implements functionObject.
Definition at line 282 of file cloudInfo.C.
write()
bool write () virtual
Implements functionObject.
Definition at line 293 of file cloudInfo.C.
Member Data Documentation
verbose_
bool verbose_ protected
Definition at line 138 of file cloudInfo.H.
onExecute_
bool onExecute_ protected
Definition at line 141 of file cloudInfo.H.
cloudNames_
wordList cloudNames_ protected
Definition at line 144 of file cloudInfo.H.
filePtrs_
PtrList<OFstream> filePtrs_ protected
Definition at line 147 of file cloudInfo.H.
The documentation for this class was generated from the following files:
src/functionObjects/lagrangian/cloudInfo/cloudInfo.H
src/functionObjects/lagrangian/cloudInfo/cloudInfo.C