OpenFOAM: PatchToPatchInterpolation< FromPatch, ToPatch > Class Template Reference
PatchToPatchInterpolation< FromPatch, ToPatch > Class Template Reference
Interpolation class dealing with transfer of data between two primitivePatches.
#include <PatchToPatchInterpolation.H>
Public Member Functions
PatchToPatchInterpolation (const FromPatch &fromPatch, const ToPatch &toPatch, const intersection::algorithm alg=intersection::FULL_RAY, const intersection::direction dir=intersection::VECTOR)
~PatchToPatchInterpolation ()
intersection::algorithm projectionAlgo () const
intersection::direction projectionDir () const
const scalarField & pointDistanceToIntersection () const
const scalarField & faceDistanceToIntersection () const
bool movePoints ()
template<class Type >
tmp< Field< Type > > pointInterpolate (const Field< Type > &pf) const
template<class Type >
tmp< Field< Type > > pointInterpolate (const tmp< Field< Type > > &tpf) const
template<class Type >
tmp< Field< Type > > faceInterpolate (const Field< Type > &pf) const
template<class Type >
tmp< Field< Type > > faceInterpolate (const tmp< Field< Type > > &tpf) const
Public Member Functions inherited from PatchToPatchInterpolationBase
ClassName ("PatchToPatchInterpolation")
PatchToPatchInterpolationBase () noexcept=default
Additional Inherited Members
Static Public Member Functions inherited from PatchToPatchInterpolationBase
static scalar projectionTol () noexcept
static scalar setProjectionTol (const scalar tol)
Static Protected Attributes inherited from PatchToPatchInterpolationBase
static scalar projectionTol_ = 0.05
static const scalar directHitTol = 1e-5
Detailed Description
template<class FromPatch, class ToPatch>
class Foam::PatchToPatchInterpolation< FromPatch, ToPatch >
Interpolation class dealing with transfer of data between two primitivePatches.
Source files
PatchToPatchInterpolation.H
PatchToPatchInterpolation.C
PatchToPatchInterpolate.C
CalcPatchToPatchWeights.C
Definition at line 109 of file PatchToPatchInterpolation.H.
Constructor & Destructor Documentation
PatchToPatchInterpolation()
template<class FromPatch , class ToPatch > PatchToPatchInterpolation (const FromPatch & fromPatch, const ToPatch & toPatch, const intersection::algorithm alg = intersection::FULL_RAY, const intersection::direction dir = intersection::VECTOR)
Definition at line 98 of file PatchToPatchInterpolation.C.
~PatchToPatchInterpolation()
template<class FromPatch , class ToPatch > ~PatchToPatchInterpolation ()
Definition at line 122 of file PatchToPatchInterpolation.C.
Member Function Documentation
projectionAlgo()
template<class FromPatch , class ToPatch > intersection::algorithm projectionAlgo () const inline
Definition at line 204 of file PatchToPatchInterpolation.H.
projectionDir()
template<class FromPatch , class ToPatch > intersection::direction projectionDir () const inline
Definition at line 210 of file PatchToPatchInterpolation.H.
pointDistanceToIntersection()
template<class FromPatch , class ToPatch > const scalarField & pointDistanceToIntersection () const
Definition at line 133 of file PatchToPatchInterpolation.C.
faceDistanceToIntersection()
template<class FromPatch , class ToPatch > const scalarField & faceDistanceToIntersection () const
Definition at line 147 of file PatchToPatchInterpolation.C.
movePoints()
template<class FromPatch , class ToPatch > bool movePoints ()
Definition at line 159 of file PatchToPatchInterpolation.C.
pointInterpolate() [1/2]
template<class FromPatch , class ToPatch > template<class Type > tmp< Field< Type > > pointInterpolate (const Field< Type > & pf) const
Definition at line 36 of file PatchToPatchInterpolate.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::New(), PtrList< T >::PtrList(), UPtrList< T >::size(), and Foam::Zero.
pointInterpolate() [2/2]
template<class FromPatch , class ToPatch > template<class Type > tmp< Field< Type > > pointInterpolate (const tmp< Field< Type > > & tpf) const
Definition at line 81 of file PatchToPatchInterpolate.C.
References PtrList< T >::clear(), and PtrList< T >::PtrList().
faceInterpolate() [1/2]
template<class FromPatch , class ToPatch > template<class Type > tmp< Field< Type > > faceInterpolate (const Field< Type > & pf) const
Definition at line 95 of file PatchToPatchInterpolate.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::New(), PtrList< T >::PtrList(), UPtrList< T >::size(), and Foam::Zero.
faceInterpolate() [2/2]
template<class FromPatch , class ToPatch > template<class Type > tmp< Field< Type > > faceInterpolate (const tmp< Field< Type > > & tpf) const
Definition at line 143 of file PatchToPatchInterpolate.C.
References PtrList< T >::clear(), and PtrList< T >::PtrList().
The documentation for this class was generated from the following files:
src/OpenFOAM/interpolations/patchToPatchInterpolation/PatchToPatchInterpolation.H
src/OpenFOAM/interpolations/patchToPatchInterpolation/CalcPatchToPatchWeights.C
src/OpenFOAM/interpolations/patchToPatchInterpolation/PatchToPatchInterpolate.C
src/OpenFOAM/interpolations/patchToPatchInterpolation/PatchToPatchInterpolation.C