OpenFOAM: adaptiveSolver Class Reference
adaptiveSolver Class Reference abstract
Numerics » Ordinary Differential Equation (ODE) solvers
#include <adaptiveSolver.H>
Public Member Functions
adaptiveSolver (const ODESystem &ode, const dictionary &dict)
virtual ~adaptiveSolver ()=default
bool resize (const label n)
virtual scalar solve (const scalar x0, const scalarField &y0, const scalarField &dydx0, const scalar dx, scalarField &y) const =0
void solve (const ODESystem &ode, scalar &x, scalarField &y, scalar &dxTry) const
Detailed Description
Source files
adaptiveSolver.H
adaptiveSolver.C
Definition at line 49 of file adaptiveSolver.H.
Constructor & Destructor Documentation
adaptiveSolver()
adaptiveSolver (const ODESystem & ode, const dictionary & dict)
Definition at line 27 of file adaptiveSolver.C.
~adaptiveSolver()
virtual ~adaptiveSolver () virtual default
Member Function Documentation
resize()
bool resize (const label n)
Definition at line 45 of file adaptiveSolver.C.
References n, and ODESolver::resizeField().
Referenced by Euler::resize(), EulerSI::resize(), RKCK45::resize(), RKDP45::resize(), RKF45::resize(), rodas23::resize(), rodas34::resize(), Rosenbrock12::resize(), Rosenbrock23::resize(), Rosenbrock34::resize(), and Trapezoid::resize().
solve() [1/2]
virtual scalar solve (const scalar x0, const scalarField & y0, const scalarField & dydx0, const scalar dx, scalarField & y) const pure virtual
Implemented in Euler, EulerSI, RKCK45, RKDP45, RKF45, rodas23, rodas34, Rosenbrock12, Rosenbrock23, Rosenbrock34, and Trapezoid.
Referenced by Euler::solve(), EulerSI::solve(), RKCK45::solve(), RKDP45::solve(), RKF45::solve(), rodas23::solve(), rodas34::solve(), Rosenbrock12::solve(), Rosenbrock23::solve(), Rosenbrock34::solve(), and Trapezoid::solve().
solve() [2/2]
void solve (const ODESystem & ode, scalar & x, scalarField & y, scalar & dxTry) const
Definition at line 54 of file adaptiveSolver.C.
References Foam::clamp(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::max(), Foam::pow(), solve(), x, and y.
The documentation for this class was generated from the following files:
src/ODE/ODESolvers/adaptiveSolver/adaptiveSolver.H
src/ODE/ODESolvers/adaptiveSolver/adaptiveSolver.C