OpenFOAM: strainRateFunction Class Reference
strainRateFunction Class Reference
Run-time selected strain-rate function generalized Newtonian viscosity model.
#include <strainRateFunction.H>
Public Member Functions
TypeName ("strainRateFunction")
strainRateFunction (const dictionary &viscosityProperties)
virtual ~strainRateFunction ()=default
virtual bool read (const dictionary &viscosityProperties)
virtual tmp< volScalarField > nu (const volScalarField &nu0, const volScalarField &strainRate) const
Public Member Functions inherited from generalizedNewtonianViscosityModel
TypeName ("generalizedNewtonianViscosityModel")
declareRunTimeSelectionTable (autoPtr, generalizedNewtonianViscosityModel, dictionary,(const dictionary &viscosityProperties),(viscosityProperties))
generalizedNewtonianViscosityModel (const generalizedNewtonianViscosityModel &)=delete
void operator= (const generalizedNewtonianViscosityModel &)=delete
generalizedNewtonianViscosityModel (const dictionary &viscosityProperties)
virtual ~generalizedNewtonianViscosityModel ()=default
const dictionary & viscosityProperties () const
Additional Inherited Members
Static Public Member Functions inherited from generalizedNewtonianViscosityModel
static autoPtr< generalizedNewtonianViscosityModel > New (const dictionary &dict)
Protected Attributes inherited from generalizedNewtonianViscosityModel
dictionary viscosityProperties_
Detailed Description
Run-time selected strain-rate function generalized Newtonian viscosity model.
Example linear function of strain-rate:
    generalizedNewtonianModel strainRateFunction;
    function polynomial ((0 0.1) (1 1.3));
See also
Foam::generalizedNewtonianViscosityModel Foam::Function1
Source files
strainRateFunction.H
strainRateFunction.C
Definition at line 63 of file strainRateFunction.H.
Constructor & Destructor Documentation
strainRateFunction()
strainRateFunction (const dictionary & viscosityProperties) explicit
Definition at line 49 of file strainRateFunction.C.
References Foam::New().
~strainRateFunction()
virtual ~strainRateFunction () virtual default
Member Function Documentation
TypeName()
TypeName ("strainRateFunction")
read()
bool read (const dictionary & viscosityProperties) virtual
Implements generalizedNewtonianViscosityModel.
Definition at line 69 of file strainRateFunction.C.
References dictionary::optionalSubDict(), and generalizedNewtonianViscosityModel::read().
nu()
Foam::tmp< Foam::volScalarField > nu (const volScalarField & nu0, const volScalarField & strainRate) const virtual
Implements generalizedNewtonianViscosityModel.
Definition at line 92 of file strainRateFunction.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), Foam::dimViscosity, forAll, IOobject::group(), IOobject::groupName(), DimensionedField< Type, GeoMesh >::mesh(), GeometricField< scalar, fvPatchField, volMesh >::New(), IOobject::scopedName(), Foam::type(), and Foam::Zero.
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/laminar/generalizedNewtonian/generalizedNewtonianViscosityModels/strainRateFunction/strainRateFunction.H
src/TurbulenceModels/turbulenceModels/laminar/generalizedNewtonian/generalizedNewtonianViscosityModels/strainRateFunction/strainRateFunction.C