OpenFOAM: phaseHydrostaticPressureFvPatchScalarField Class Reference
phaseHydrostaticPressureFvPatchScalarField Class Reference
Boundary conditions » Generic
This boundary condition provides a phase-based hydrostatic pressure condition, calculated as:
#include <phaseHydrostaticPressureFvPatchScalarField.H>
Public Member Functions
TypeName ("phaseHydrostaticPressure")
phaseHydrostaticPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
phaseHydrostaticPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
phaseHydrostaticPressureFvPatchScalarField (const phaseHydrostaticPressureFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
phaseHydrostaticPressureFvPatchScalarField (const phaseHydrostaticPressureFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
phaseHydrostaticPressureFvPatchScalarField (const phaseHydrostaticPressureFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual bool assignable () const
const word & phaseFraction () const
word & phaseFraction ()
scalar rho () const
scalar & rho ()
scalar pRefValue () const
scalar & pRefValue ()
const vector & pRefPoint () const
vector & pRefPoint ()
virtual void updateCoeffs ()
virtual void write (Ostream &) const
virtual void operator= (const fvPatchScalarField &pvf)
Protected Attributes
word phaseFraction_
scalar rho_
scalar pRefValue_
vector pRefPoint_
Detailed Description
This boundary condition provides a phase-based hydrostatic pressure condition, calculated as:
where
= hyrostatic pressure [Pa]
= reference pressure [Pa]
= reference point in Cartesian coordinates
= density (assumed uniform)
= acceleration due to gravity [m/s2]
The values are assigned according to the phase-fraction field:
1: apply
0: apply a zero-gradient condition
Usage
Property Description Required Default value
phaseFraction phase-fraction field name no alpha
rho density field name no rho
pRefValue reference pressure [Pa] yes
pRefPoint reference pressure location yes
Example of the boundary condition specification:
    <patchName>
    {
        type            phaseHydrostaticPressure;
        phaseFraction   alpha1;
        rho             rho;
        pRefValue       1e5;
        pRefPoint       (0 0 0);
        value           uniform 0; // optional initial value
    }
See also
Foam::mixedFvPatchScalarField
Source files
phaseHydrostaticPressureFvPatchScalarField.H
phaseHydrostaticPressureFvPatchScalarField.C
Definition at line 137 of file phaseHydrostaticPressureFvPatchScalarField.H.
Constructor & Destructor Documentation
phaseHydrostaticPressureFvPatchScalarField() [1/5]
phaseHydrostaticPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 31 of file phaseHydrostaticPressureFvPatchScalarField.C.
phaseHydrostaticPressureFvPatchScalarField() [2/5]
phaseHydrostaticPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 50 of file phaseHydrostaticPressureFvPatchScalarField.C.
References dict, fvPatchField< scalar >::operator=(), phaseHydrostaticPressureFvPatchScalarField::pRefValue_, and fvPatchFieldBase::readDict().
phaseHydrostaticPressureFvPatchScalarField() [3/5]
phaseHydrostaticPressureFvPatchScalarField (const phaseHydrostaticPressureFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 78 of file phaseHydrostaticPressureFvPatchScalarField.C.
phaseHydrostaticPressureFvPatchScalarField() [4/5]
phaseHydrostaticPressureFvPatchScalarField (const phaseHydrostaticPressureFvPatchScalarField & ptf)
Definition at line 95 of file phaseHydrostaticPressureFvPatchScalarField.C.
phaseHydrostaticPressureFvPatchScalarField() [5/5]
phaseHydrostaticPressureFvPatchScalarField (const phaseHydrostaticPressureFvPatchScalarField & ptf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 106 of file phaseHydrostaticPressureFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("phaseHydrostaticPressure")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 199 of file phaseHydrostaticPressureFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 215 of file phaseHydrostaticPressureFvPatchScalarField.H.
assignable()
virtual bool assignable () const inline virtual
Definition at line 230 of file phaseHydrostaticPressureFvPatchScalarField.H.
phaseFraction() [1/2]
const word & phaseFraction () const inline
Definition at line 236 of file phaseHydrostaticPressureFvPatchScalarField.H.
References phaseHydrostaticPressureFvPatchScalarField::phaseFraction_.
phaseFraction() [2/2]
word & phaseFraction () inline
Definition at line 242 of file phaseHydrostaticPressureFvPatchScalarField.H.
References phaseHydrostaticPressureFvPatchScalarField::phaseFraction_.
rho() [1/2]
scalar rho () const inline
Definition at line 248 of file phaseHydrostaticPressureFvPatchScalarField.H.
References phaseHydrostaticPressureFvPatchScalarField::rho_.
rho() [2/2]
scalar & rho () inline
Definition at line 255 of file phaseHydrostaticPressureFvPatchScalarField.H.
References phaseHydrostaticPressureFvPatchScalarField::rho_.
pRefValue() [1/2]
scalar pRefValue () const inline
Definition at line 261 of file phaseHydrostaticPressureFvPatchScalarField.H.
References phaseHydrostaticPressureFvPatchScalarField::pRefValue_.
pRefValue() [2/2]
scalar & pRefValue () inline
Definition at line 267 of file phaseHydrostaticPressureFvPatchScalarField.H.
References phaseHydrostaticPressureFvPatchScalarField::pRefValue_.
pRefPoint() [1/2]
const vector & pRefPoint () const inline
Definition at line 273 of file phaseHydrostaticPressureFvPatchScalarField.H.
References phaseHydrostaticPressureFvPatchScalarField::pRefPoint_.
pRefPoint() [2/2]
vector & pRefPoint () inline
Definition at line 280 of file phaseHydrostaticPressureFvPatchScalarField.H.
References phaseHydrostaticPressureFvPatchScalarField::pRefPoint_.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 123 of file phaseHydrostaticPressureFvPatchScalarField.C.
References Foam::clamp(), g, and gravity::New().
write()
void write (Ostream & os) const virtual
Definition at line 149 of file phaseHydrostaticPressureFvPatchScalarField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntry(), Ostream::writeEntryIfDifferent(), and fvPatchField< Type >::writeValueEntry().
operator=()
void operator= (const fvPatchScalarField & pvf) virtual
Definition at line 162 of file phaseHydrostaticPressureFvPatchScalarField.C.
References Foam::lerp().
Member Data Documentation
phaseFraction_
word phaseFraction_ protected
Definition at line 147 of file phaseHydrostaticPressureFvPatchScalarField.H.
Referenced by phaseHydrostaticPressureFvPatchScalarField::phaseFraction(), and phaseHydrostaticPressureFvPatchScalarField::phaseFraction().
rho_
scalar rho_ protected
Definition at line 150 of file phaseHydrostaticPressureFvPatchScalarField.H.
Referenced by phaseHydrostaticPressureFvPatchScalarField::rho(), and phaseHydrostaticPressureFvPatchScalarField::rho().
pRefValue_
scalar pRefValue_ protected
Definition at line 153 of file phaseHydrostaticPressureFvPatchScalarField.H.
Referenced by phaseHydrostaticPressureFvPatchScalarField::phaseHydrostaticPressureFvPatchScalarField(), phaseHydrostaticPressureFvPatchScalarField::pRefValue(), and phaseHydrostaticPressureFvPatchScalarField::pRefValue().
pRefPoint_
vector pRefPoint_ protected
Definition at line 156 of file phaseHydrostaticPressureFvPatchScalarField.H.
Referenced by phaseHydrostaticPressureFvPatchScalarField::pRefPoint(), and phaseHydrostaticPressureFvPatchScalarField::pRefPoint().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/phaseHydrostaticPressure/phaseHydrostaticPressureFvPatchScalarField.H
src/finiteVolume/fields/fvPatchFields/derived/phaseHydrostaticPressure/phaseHydrostaticPressureFvPatchScalarField.C