OpenFOAM: constTransport< Thermo > Class Template Reference
constTransport< Thermo > Class Template Reference
Thermophysical models » Specie » Transport
Constant properties Transport package. Templated into a given thermodynamics package (needed for thermal conductivity).
#include <constTransport.H>
Public Member Functions
constTransport (const word &, const constTransport &)
constTransport (const dictionary &dict)
autoPtr< constTransport > clone () const
scalar mu (const scalar p, const scalar T) const
scalar kappa (const scalar p, const scalar T) const
scalar alphah (const scalar p, const scalar T) const
void write (Ostream &os) const
void operator+= (const constTransport &)
void operator*= (const scalar)
Static Public Member Functions
static autoPtr< constTransport > New (const dictionary &dict)
static word typeName ()
Friends
constTransport operator+ (const constTransport &, const constTransport &)
constTransport operator* (const scalar, const constTransport &)
Ostream & operator<< (Ostream &, const constTransport &)
Detailed Description
template<class Thermo>
class Foam::constTransport< Thermo >
Constant properties Transport package. Templated into a given thermodynamics package (needed for thermal conductivity).
Source files
constTransport.H
constTransportI.H
constTransport.C
Definition at line 78 of file constTransport.H.
Constructor & Destructor Documentation
constTransport() [1/2]
template<class Thermo > constTransport (const word & name, const constTransport< Thermo > & ct) inline
Definition at line 38 of file constTransportI.H.
References Foam::name().
constTransport() [2/2]
template<class Thermo > constTransport (const dictionary & dict) explicit
Definition at line 27 of file constTransport.C.
Member Function Documentation
clone()
template<class Thermo > Foam::autoPtr< Foam::constTransport< Thermo > > clone () const inline
Definition at line 52 of file constTransportI.H.
References Foam::New().
New()
template<class Thermo > Foam::autoPtr< Foam::constTransport< Thermo > > New (const dictionary & dict) inline static
Definition at line 60 of file constTransportI.H.
References dict, and Foam::New().
typeName()
template<class Thermo > static word typeName () inline static
Definition at line 125 of file constTransport.H.
mu()
template<class Thermo > Foam::scalar mu (const scalar p, const scalar T) const inline
Definition at line 72 of file constTransportI.H.
kappa()
template<class Thermo > Foam::scalar kappa (const scalar p, const scalar T) const inline
Definition at line 83 of file constTransportI.H.
References Cp, mu, p, and T.
alphah()
template<class Thermo > Foam::scalar alphah (const scalar p, const scalar T) const inline
Definition at line 94 of file constTransportI.H.
References mu, p, and T.
write()
template<class Thermo > void write (Ostream & os) const
operator+=()
template<class Thermo > void operator+= (const constTransport< Thermo > &) inline
Definition at line 107 of file constTransportI.H.
References Foam::mag(), and Y.
operator*=()
template<class Thermo > void operator*= (const scalar s) inline
Definition at line 128 of file constTransportI.H.
References s().
Friends And Related Symbol Documentation
operator+
template<class Thermo > constTransport operator+ (const constTransport< Thermo > & , const constTransport< Thermo > &) friend
operator*
template<class Thermo > constTransport operator* (const scalar , const constTransport< Thermo > &) friend
operator<<
template<class Thermo > Ostream & operator<< (Ostream & , const constTransport< Thermo > &) friend
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/transport/const/constTransport.H
src/thermophysicalModels/specie/transport/const/constTransport.C
src/thermophysicalModels/specie/transport/const/constTransportI.H