OpenFOAM: kineticTheoryModel Class Reference
kineticTheoryModel Class Reference
Kinetic theory particle phase RAS model.
#include <kineticTheoryModel.H>
Public Member Functions
TypeName ("kineticTheory")
kineticTheoryModel (const volScalarField &alpha, const volScalarField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const phaseModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
virtual ~kineticTheoryModel ()
virtual bool read ()
virtual tmp< volScalarField > nuEff () const
virtual tmp< scalarField > nuEff (const label patchi) const
virtual tmp< volScalarField > k () const
virtual tmp< volScalarField > epsilon () const
virtual tmp< volScalarField > omega () const
virtual tmp< volSymmTensorField > R () const
virtual tmp< volScalarField > pPrime () const
virtual tmp< surfaceScalarField > pPrimef () const
virtual tmp< volSymmTensorField > devRhoReff () const
virtual tmp< volSymmTensorField > devRhoReff (const volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
virtual void correct ()
TypeName ("kineticTheory")
kineticTheoryModel (const volScalarField &alpha, const volScalarField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const phaseModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
virtual ~kineticTheoryModel ()
virtual bool read ()
virtual tmp< volScalarField > nuEff () const
virtual tmp< scalarField > nuEff (const label patchi) const
virtual tmp< volScalarField > k () const
virtual tmp< volScalarField > epsilon () const
virtual tmp< volScalarField > omega () const
virtual tmp< volSymmTensorField > R () const
virtual tmp< volScalarField > pPrime () const
virtual tmp< surfaceScalarField > pPrimef () const
virtual tmp< volSymmTensorField > devRhoReff () const
virtual tmp< volSymmTensorField > devRhoReff (const volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
virtual void correct ()
Public Member Functions inherited from eddyViscosity< RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > > >
eddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~eddyViscosity ()=default
virtual tmp< volScalarField > nut () const
virtual tmp< scalarField > nut (const label patchi) const
virtual void validate ()
Public Member Functions inherited from linearViscousStress< BasicTurbulenceModel >
linearViscousStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~linearViscousStress ()=default
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Additional Inherited Members
Public Types inherited from eddyViscosity< RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > > >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from linearViscousStress< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Protected Attributes inherited from eddyViscosity< RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > > >
volScalarField nut_
Detailed Description
Kinetic theory particle phase RAS model.
Reference:
    van Wachem, B. G. M. (2000).
    Derivation, implementation, and validation of computer simulation models
    for gas-solid fluidized beds.
    PhD Thesis, TU Delft.
There are no default model coefficients.
Source files
kineticTheoryModel.H
kineticTheoryModel.C
Definition at line 70 of file kineticTheoryModel.H.
Constructor & Destructor Documentation
kineticTheoryModel() [1/2]
kineticTheoryModel (const volScalarField & alpha, const volScalarField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const phaseModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
~kineticTheoryModel() [1/2]
~kineticTheoryModel () virtual
Definition at line 179 of file kineticTheoryModel.C.
kineticTheoryModel() [2/2]
kineticTheoryModel (const volScalarField & alpha, const volScalarField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const phaseModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
~kineticTheoryModel() [2/2]
virtual ~kineticTheoryModel () virtual
Member Function Documentation
TypeName() [1/2]
TypeName ("kineticTheory")
read() [1/2]
bool read () virtual
Implements eddyViscosity< RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > > >.
Definition at line 185 of file kineticTheoryModel.C.
References Foam::read().
nuEff() [1/4]
virtual tmp< volScalarField > nuEff () const inline virtual
Definition at line 187 of file kineticTheoryModel.H.
References eddyViscosity< RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > > >::nut().
nuEff() [2/4]
virtual tmp< scalarField > nuEff (const label patchi) const inline virtual
Definition at line 193 of file kineticTheoryModel.H.
References eddyViscosity< RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > > >::nut().
k() [1/2]
Foam::tmp< Foam::volScalarField > k () const virtual
Implements eddyViscosity< RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > > >.
Definition at line 214 of file kineticTheoryModel.C.
References NotImplemented.
epsilon() [1/2]
Foam::tmp< Foam::volScalarField > epsilon () const virtual
Definition at line 222 of file kineticTheoryModel.C.
References NotImplemented.
omega() [1/2]
Foam::tmp< Foam::volScalarField > omega () const virtual
Definition at line 230 of file kineticTheoryModel.C.
References NotImplemented.
R() [1/2]
Foam::tmp< Foam::volSymmTensorField > R () const virtual
Reimplemented from eddyViscosity< RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > > >.
Definition at line 238 of file kineticTheoryModel.C.
References Foam::devTwoSymm(), Foam::fvc::div(), Foam::fvc::grad(), IOobject::groupName(), SymmTensor< scalar >::I, IOobjectOption::NO_READ, and IOobjectOption::NO_WRITE.
pPrime() [1/2]
Foam::tmp< Foam::volScalarField > pPrime () const virtual
Definition at line 260 of file kineticTheoryModel.C.
References coupled(), forAll, and rho.
pPrimef() [1/2]
Foam::tmp< Foam::surfaceScalarField > pPrimef () const virtual
Definition at line 299 of file kineticTheoryModel.C.
References Foam::fvc::interpolate().
devRhoReff() [1/4]
Foam::tmp< Foam::volSymmTensorField > devRhoReff () const virtual
Reimplemented from linearViscousStress< BasicTurbulenceModel >.
Definition at line 306 of file kineticTheoryModel.C.
devRhoReff() [2/4]
Foam::tmp< Foam::volSymmTensorField > devRhoReff (const volVectorField & U) const virtual
Reimplemented from linearViscousStress< BasicTurbulenceModel >.
Definition at line 313 of file kineticTheoryModel.C.
References Foam::devTwoSymm(), Foam::fvc::div(), Foam::fvc::grad(), IOobject::groupName(), SymmTensor< scalar >::I, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, and U.
divDevRhoReff() [1/2]
Foam::tmp< Foam::fvVectorMatrix > divDevRhoReff (volVectorField & U) const virtual
Reimplemented from linearViscousStress< BasicTurbulenceModel >.
Definition at line 339 of file kineticTheoryModel.C.
References Foam::dev2(), Foam::dimless, Foam::fvc::div(), Foam::fvc::grad(), SymmTensor< scalar >::I, Foam::fvm::laplacian(), T, and U.
correct() [1/2]
void correct () virtual
Implements eddyViscosity< RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > > >.
Definition at line 357 of file kineticTheoryModel.C.
References alpha, beta(), D, Foam::fvc::ddt(), Foam::fvm::ddt(), Foam::fvc::div(), Foam::fvm::div(), e, Foam::endl(), fvOptions, Foam::fvc::grad(), Foam::I, Foam::Info, K1, K2, K3, K4, Foam::fvm::laplacian(), Foam::magSqr(), Foam::max(), Foam::min(), options::New(), Foam::nl, Foam::constant::mathematical::pi(), rho, Foam::fvm::Sp(), Foam::fvc::Sp(), Foam::sqr(), Foam::sqrt(), Foam::fvm::SuSp(), Foam::symm(), Foam::tr(), and U.
TypeName() [2/2]
TypeName ("kineticTheory")
read() [2/2]
virtual bool read () virtual
Implements eddyViscosity< RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > > >.
nuEff() [3/4]
virtual tmp< volScalarField > nuEff () const inline virtual
Definition at line 187 of file kineticTheoryModel.H.
References eddyViscosity< RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > > >::nut().
nuEff() [4/4]
virtual tmp< scalarField > nuEff (const label patchi) const inline virtual
Definition at line 193 of file kineticTheoryModel.H.
References eddyViscosity< RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > > >::nut().
k() [2/2]
virtual tmp< volScalarField > k () const virtual
Implements eddyViscosity< RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > > >.
epsilon() [2/2]
virtual tmp< volScalarField > epsilon () const virtual
omega() [2/2]
virtual tmp< volScalarField > omega () const virtual
R() [2/2]
virtual tmp< volSymmTensorField > R () const virtual
Reimplemented from eddyViscosity< RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > > >.
pPrime() [2/2]
virtual tmp< volScalarField > pPrime () const virtual
pPrimef() [2/2]
virtual tmp< surfaceScalarField > pPrimef () const virtual
devRhoReff() [3/4]
virtual tmp< volSymmTensorField > devRhoReff () const virtual
Reimplemented from linearViscousStress< BasicTurbulenceModel >.
devRhoReff() [4/4]
virtual tmp< volSymmTensorField > devRhoReff (const volVectorField & U) const virtual
Reimplemented from linearViscousStress< BasicTurbulenceModel >.
divDevRhoReff() [2/2]
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField & U) const virtual
Reimplemented from linearViscousStress< BasicTurbulenceModel >.
correct() [2/2]
virtual void correct () virtual
Implements eddyViscosity< RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > > >.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/twoPhaseCompressibleTurbulenceModels/kineticTheoryModels/kineticTheoryModel/kineticTheoryModel.H
src/phaseSystemModels/twoPhaseEuler/phaseCompressibleTurbulenceModels/kineticTheoryModels/kineticTheoryModel/kineticTheoryModel.H
src/phaseSystemModels/reactingEuler/twoPhaseCompressibleTurbulenceModels/kineticTheoryModels/kineticTheoryModel/kineticTheoryModel.C
src/phaseSystemModels/twoPhaseEuler/phaseCompressibleTurbulenceModels/kineticTheoryModels/kineticTheoryModel/kineticTheoryModel.C