OpenFOAM: noSlipFvPatchVectorField Class Reference
noSlipFvPatchVectorField Class Reference
Boundary conditions » Wall
This boundary condition fixes the velocity to zero at walls.
#include <noSlipFvPatchVectorField.H>
Public Member Functions
TypeName ("noSlip")
noSlipFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
noSlipFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
noSlipFvPatchVectorField (const noSlipFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
noSlipFvPatchVectorField (const noSlipFvPatchVectorField &)
virtual tmp< fvPatchVectorField > clone () const
noSlipFvPatchVectorField (const noSlipFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
virtual void write (Ostream &) const
Detailed Description
This boundary condition fixes the velocity to zero at walls.
Usage
Example of the boundary condition specification:
<patchName>
{
    type            noSlip;
}
See also
Foam::fixedValueFvPatchVectorField
Source files
noSlipFvPatchVectorField.H
noSlipFvPatchVectorField.C
Definition at line 61 of file noSlipFvPatchVectorField.H.
Constructor & Destructor Documentation
noSlipFvPatchVectorField() [1/5]
noSlipFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Definition at line 27 of file noSlipFvPatchVectorField.C.
noSlipFvPatchVectorField() [2/5]
noSlipFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Definition at line 37 of file noSlipFvPatchVectorField.C.
References dict, and fvPatchFieldBase::readDict().
noSlipFvPatchVectorField() [3/5]
noSlipFvPatchVectorField (const noSlipFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 50 of file noSlipFvPatchVectorField.C.
noSlipFvPatchVectorField() [4/5]
noSlipFvPatchVectorField (const noSlipFvPatchVectorField & mwvpvf)
Definition at line 62 of file noSlipFvPatchVectorField.C.
noSlipFvPatchVectorField() [5/5]
noSlipFvPatchVectorField (const noSlipFvPatchVectorField & mwvpvf, const DimensionedField< vector, volMesh > & iF)
Definition at line 71 of file noSlipFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("noSlip")
clone() [1/2]
virtual tmp< fvPatchVectorField > clone () const inline virtual
Definition at line 106 of file noSlipFvPatchVectorField.H.
clone() [2/2]
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Definition at line 122 of file noSlipFvPatchVectorField.H.
write()
void write (Ostream & os) const virtual
Definition at line 83 of file noSlipFvPatchVectorField.C.
References os(), and fvPatchField< Type >::write().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/noSlip/noSlipFvPatchVectorField.H
src/finiteVolume/fields/fvPatchFields/derived/noSlip/noSlipFvPatchVectorField.C