OpenFOAM: trackingInverseDistance Class Reference
trackingInverseDistance Class Reference
Inverse-distance-weighted interpolation stencil.
#include <trackingInverseDistanceCellCellStencil.H>
Public Member Functions
TypeName ("trackingInverseDistance")
trackingInverseDistance (const fvMesh &, const dictionary &, const bool)
virtual ~trackingInverseDistance ()
virtual bool update ()
Public Member Functions inherited from inverseDistance
TypeName ("inverseDistance")
inverseDistance (const fvMesh &, const dictionary &, const bool)
virtual ~inverseDistance ()
virtual const labelUList & cellTypes () const
virtual const labelUList & interpolationCells () const
virtual const mapDistribute & cellInterpolationMap () const
virtual const labelListList & cellStencil () const
virtual const scalarListList & cellInterpolationWeights () const
virtual const scalarList & cellInterpolationWeight () const
virtual void stencilWeights (const point &sample, const pointList &donorCcs, scalarList &weights) const
Public Member Functions inherited from cellCellStencil
TypeName ("cellCellStencil")
declareRunTimeSelectionTable (autoPtr, cellCellStencil, mesh,(const fvMesh &mesh, const dictionary &dict, const bool update),(mesh, dict, update))
cellCellStencil (const fvMesh &)
virtual ~cellCellStencil ()
virtual const wordHashSet & nonInterpolatedFields () const
virtual wordHashSet & nonInterpolatedFields ()
bool localStencil (const labelUList &) const
const labelIOList & zoneID () const
template<class T >
void interpolate (const fvMesh &mesh, Field< T > &psi) const
template<class GeoField >
void interpolate (GeoField &psi) const
template<class GeoField >
void interpolate (const fvMesh &mesh, const wordHashSet &suppressed) const
void walkFront (const globalIndex &globalCells, const scalar layerRelax, const labelListList &allStencil, labelList &allCellTypes, scalarField &allWeight, const scalarList &compactCellVol, const labelListList &compactStencil, const labelList &zoneID, const label holeLayers, const label useLayer) const
void setUpFront (const labelList &allCellTypes, bitSet &isFront) const
void setUpFrontOnOversetPatch (const labelList &allCellTypes, bitSet &isFront) const
void seedCell (const label cellI, const scalar wantedFraction, bitSet &isFront, scalarField &fraction) const
InfoProxy< cellCellStencil > info () const noexcept
template<class Type >
Foam::tmp< Foam::volScalarField > createField (const fvMesh &mesh, const word &name, const UList< Type > &psi)
Protected Member Functions
void markPatchesAsHoles (PstreamBuffers &pBufs, const List< treeBoundBoxList > &patchBb, const List< labelVector > &patchDivisions, const PtrList< PackedList< 2 > > &patchParts, const label srcI, const label tgtI, labelList &allCellTypes) const
void markDonors (PstreamBuffers &pBufs, const List< treeBoundBoxList > &meshBb, const PtrList< voxelMeshSearch > &meshSearches, const labelList &allCellTypes, const label srcI, const label tgtI, labelListList &allStencil, labelList &allDonor) const
Protected Member Functions inherited from inverseDistance
void markPatchesAsHoles (PstreamBuffers &pBufs, const PtrList< fvMeshSubset > &meshParts, const List< treeBoundBoxList > &patchBb, const List< labelVector > &patchDivisions, const PtrList< PackedList< 2 > > &patchParts, const label srcI, const label tgtI, labelList &allCellTypes) const
bool betterDonor (const label destMesh, const label currentDonorMesh, const label newDonorMesh) const
void markDonors (const globalIndex &globalCells, PstreamBuffers &pBufs, const PtrList< fvMeshSubset > &meshParts, const List< treeBoundBoxList > &meshBb, const labelList &allCellTypes, const label srcI, const label tgtI, labelListList &allStencil, labelList &allDonor) const
void uncompactedRegionSplit (const fvMesh &mesh, const globalIndex &globalFaces, const label nZones, const labelList &zoneID, const labelList &cellTypes, const boolList &isBlockedFace, labelList &cellRegion) const
autoPtr< globalIndex > compactedRegionSplit (const fvMesh &mesh, const globalIndex &globalFaces, labelList &cellRegion) const
void findHoles (const globalIndex &globalCells, const fvMesh &mesh, const labelList &zoneID, const labelListList &stencil, labelList &cellTypes) const
void seedCell (const label cellI, const scalar wantedFraction, bitSet &isFront, scalarField &fraction) const
virtual void createStencil (const globalIndex &, const bool allowHoleDonors)
void holeExtrapolationStencil (const globalIndex &globalCells)
Static Protected Member Functions
static bool markBoundaries (const fvMesh &mesh, const vector &smallVec, const boundBox &bb, labelVector &nDivs, PackedList< 2 > &patchTypes, const labelList &cellMap, labelList &patchCellTypes)
Static Protected Member Functions inherited from inverseDistance
static label index (const labelVector &nDivs, const labelVector &)
static labelVector index3 (const labelVector &nDivs, const label)
static labelVector index3 (const boundBox &bb, const labelVector &nDivs, const point &pt)
static point position (const boundBox &bb, const labelVector &nDivs, const label boxI)
static void fill (PackedList< 2 > &elems, const boundBox &bb, const labelVector &nDivs, const boundBox &subBb, const unsigned int val)
static bool overlaps (const boundBox &bb, const labelVector &nDivs, const PackedList< 2 > &voxels, const treeBoundBox &subBb, const unsigned int val)
static void markBoundaries (const fvMesh &mesh, const vector &smallVec, const boundBox &bb, const labelVector &nDivs, PackedList< 2 > &patchTypes, const labelList &cellMap, labelList &patchCellTypes)
Static Protected Member Functions inherited from cellCellStencil
template<class Type >
static tmp< volScalarField > createField (const fvMesh &mesh, const word &name, const UList< Type > &)
static word baseName (const word &name)
Protected Attributes
globalIndex globalCells_
labelList globalDonor_
PtrList< fvMeshSubset > meshParts_
Protected Attributes inherited from inverseDistance
const dictionary dict_
const bool allowHoleDonors_
const bool allowInterpolatedDonors_
vector smallVec_
labelList cellTypes_
labelList interpolationCells_
autoPtr< mapDistribute > cellInterpolationMap_
labelListList cellStencil_
scalarListList cellInterpolationWeights_
volScalarField cellInterpolationWeight_
Protected Attributes inherited from cellCellStencil
const fvMesh & mesh_
wordHashSet nonInterpolatedFields_
const dictionary dict_
Additional Inherited Members
Public Types inherited from cellCellStencil
enum patchCellType { OTHER = 0 , PATCH = 1 , OVERSET = 2 }
enum cellType {
CALCULATED = 0 , INTERPOLATED = 1 , HOLE = 2 , SPECIAL = 3 ,
POROUS = 4
}
Static Public Member Functions inherited from cellCellStencil
static autoPtr< cellCellStencil > New (const fvMesh &, const dictionary &dict, const bool update=true)
static const labelIOList & zoneID (const fvMesh &)
static labelList count (const label size, const labelUList &lst)
static void globalCellCells (const globalIndex &gi, const polyMesh &mesh, const boolList &isValidDonor, const labelList &selectedCells, labelListList &cellCells, pointListList &cellCellCentres)
template<class T >
static void interpolate (Field< T > &psi, const fvMesh &mesh, const cellCellStencil &overlap, const List< scalarList > &wghts)
template<class GeoField , class SuppressBC >
static void correctBoundaryConditions (GeoField &psi)
Static Protected Attributes inherited from cellCellStencil
static const Enum< cellType > cellTypeNames_
Detailed Description
Inverse-distance-weighted interpolation stencil.
Source files
trackingInverseDistanceCellCellStencil.H
trackingInverseDistanceCellCellStencil.C
Definition at line 52 of file trackingInverseDistanceCellCellStencil.H.
Constructor & Destructor Documentation
trackingInverseDistance()
trackingInverseDistance (const fvMesh & mesh, const dictionary & dict, const bool doUpdate)
Definition at line 492 of file trackingInverseDistanceCellCellStencil.C.
References Foam::decrIndent(), Foam::endl(), forAll, trackingInverseDistance::globalDonor_, Foam::gMax(), Foam::incrIndent(), Foam::indent(), Foam::Info, Pstream::listCombineReduce(), cellCellStencil::mesh_, trackingInverseDistance::meshParts_, PtrList< T >::set(), List< T >::setSize(), PtrList< T >::setSize(), trackingInverseDistance::update(), Foam::Zero, and cellCellStencil::zoneID().
~trackingInverseDistance()
~trackingInverseDistance () virtual
Definition at line 557 of file trackingInverseDistanceCellCellStencil.C.
Member Function Documentation
markBoundaries()
bool markBoundaries (const fvMesh & mesh, const vector & smallVec, const boundBox & bb, labelVector & nDivs, PackedList< 2 > & patchTypes, const labelList & cellMap, labelList & patchCellTypes) static protected
Definition at line 48 of file trackingInverseDistanceCellCellStencil.C.
References fvPatch::constraintType(), boundBox::contains(), Foam::endl(), voxelMeshSearch::fill(), forAll, mesh, cellCellStencil::OTHER, boundBox::overlaps(), voxelMeshSearch::overlaps(), cellCellStencil::OVERSET, cellCellStencil::PATCH, patchTypes(), pbm, Foam::Pout, pp(), and WarningInFunction.
markPatchesAsHoles()
void markPatchesAsHoles (PstreamBuffers & pBufs, const List< treeBoundBoxList > & patchBb, const List< labelVector > & patchDivisions, const PtrList< PackedList< 2 > > & patchParts, const label srcI, const label tgtI, labelList & allCellTypes) const protected
Definition at line 189 of file trackingInverseDistanceCellCellStencil.C.
References UPstream::allProcs(), PtrList< T >::clear(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, UPstream::myProcNo(), os(), and voxelMeshSearch::overlaps().
markDonors()
void markDonors (PstreamBuffers & pBufs, const List< treeBoundBoxList > & meshBb, const PtrList< voxelMeshSearch > & meshSearches, const labelList & allCellTypes, const label srcI, const label tgtI, labelListList & allStencil, labelList & allDonor) const protected
Definition at line 310 of file trackingInverseDistanceCellCellStencil.C.
References Foam::abort(), UPstream::allProcs(), PtrList< T >::append(), waveMethod::calculate(), polyMesh::CELL_TETS, cellIDs, PtrList< T >::clear(), Foam::FatalError, FatalErrorInFunction, forAll, meshBb(), UPstream::myProcNo(), UPstream::nProcs(), os(), samples(), PtrList< T >::setSize(), and UPtrList< T >::size().
TypeName()
TypeName ("trackingInverseDistance")
update()
bool update () virtual
Reimplemented from inverseDistance.
Definition at line 563 of file trackingInverseDistanceCellCellStencil.C.
References Pstream::allGatherList(), PtrList< T >::append(), PtrList< T >::clear(), Foam::cmptProduct(), oversetFvMeshBase::correctBoundaryConditions(), DebugInfo, Foam::decrIndent(), mapDistribute::distribute(), e, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, forAll, FUNCTION_NAME, Foam::incrIndent(), Foam::indent(), Foam::Info, meshBb(), Foam::mkDir(), fvMesh::movePoints(), UPstream::myProcNo(), OFstream::name(), Foam::name(), Foam::nl, IOobjectOption::NO_READ, UPstream::nonBlocking, primitiveMesh::nPoints(), UPstream::nProcs(), polyMesh::points(), Foam::Pout, Foam::reduce(), Foam::returnReduce(), PtrList< T >::set(), PtrList< T >::setSize(), UPtrList< T >::size(), PtrList< T >::transfer(), OBJstream::writeLine(), and Foam::Zero.
Referenced by trackingInverseDistance::trackingInverseDistance().
Member Data Documentation
globalCells_
globalIndex globalCells_ protected
Definition at line 61 of file trackingInverseDistanceCellCellStencil.H.
globalDonor_
labelList globalDonor_ protected
Definition at line 64 of file trackingInverseDistanceCellCellStencil.H.
Referenced by trackingInverseDistance::trackingInverseDistance().
meshParts_
PtrList<fvMeshSubset> meshParts_ protected
Definition at line 67 of file trackingInverseDistanceCellCellStencil.H.
Referenced by trackingInverseDistance::trackingInverseDistance().
The documentation for this class was generated from the following files:
src/overset/cellCellStencil/trackingInverseDistance/trackingInverseDistanceCellCellStencil.H
src/overset/cellCellStencil/trackingInverseDistance/trackingInverseDistanceCellCellStencil.C