OpenFOAM: genericRagelLemonDriver Class Reference
genericRagelLemonDriver Class Reference
Generic interface code for Ragel/Lemon combination Subclasses should implement one or more process() methods.
#include <genericRagelLemonDriver.H>
Public Types
typedef size_t location_type
Public Member Functions
genericRagelLemonDriver ()
genericRagelLemonDriver (const genericRagelLemonDriver &rhs)=default
genericRagelLemonDriver (genericRagelLemonDriver &&rhs)=default
virtual ~genericRagelLemonDriver ()=default
void clear ()
const std::string & content () const
void content (const std::string &s, size_t pos=0, size_t len=std::string::npos)
std::string::const_iterator cbegin () const
std::string::const_iterator cend () const
size_t parsePosition () const
size_t & parsePosition ()
Ostream & printBuffer (Ostream &os) const
void reportFatal (const std::string &msg) const
void reportFatal (const std::string &msg, size_t pos) const
Protected Attributes
std::reference_wrapper< const std::string > content_
size_t start_
size_t length_
size_t position_
Detailed Description
Generic interface code for Ragel/Lemon combination Subclasses should implement one or more process() methods.
The scanner will often be implemented as localized lexer class. The parser may be embedded into the scanner as file-scope, or use a separate interface class.
Source files
genericRagelLemonDriver.H
genericRagelLemonDriver.C
Definition at line 55 of file genericRagelLemonDriver.H.
Member Typedef Documentation
location_type
typedef size_t location_type
Definition at line 80 of file genericRagelLemonDriver.H.
Constructor & Destructor Documentation
genericRagelLemonDriver() [1/3]
genericRagelLemonDriver ()
Definition at line 27 of file genericRagelLemonDriver.C.
genericRagelLemonDriver() [2/3]
genericRagelLemonDriver (const genericRagelLemonDriver & rhs) default
genericRagelLemonDriver() [3/3]
genericRagelLemonDriver (genericRagelLemonDriver && rhs) default
~genericRagelLemonDriver()
virtual ~genericRagelLemonDriver () virtual default
Member Function Documentation
clear()
void clear ()
Definition at line 38 of file genericRagelLemonDriver.C.
References string::null.
content() [1/2]
const std::string & content () const inline
Definition at line 105 of file genericRagelLemonDriver.H.
References genericRagelLemonDriver::content_, and UPtrList< T >::get().
content() [2/2]
void content (const std::string & s, size_t pos = 0, size_t len = std::string::npos)
Definition at line 47 of file genericRagelLemonDriver.C.
References Foam::pos(), and s().
cbegin()
std::string::const_iterator cbegin () const
Definition at line 62 of file genericRagelLemonDriver.C.
References UPtrList< T >::cend(), UPtrList< T >::get(), and s().
cend()
std::string::const_iterator cend () const
Definition at line 76 of file genericRagelLemonDriver.C.
References UPtrList< T >::cend(), UPtrList< T >::const_iterator::get(), and s().
parsePosition() [1/2]
size_t parsePosition () const inline
Definition at line 126 of file genericRagelLemonDriver.H.
References genericRagelLemonDriver::position_.
parsePosition() [2/2]
size_t & parsePosition () inline
Definition at line 132 of file genericRagelLemonDriver.H.
References genericRagelLemonDriver::position_.
printBuffer()
Foam::Ostream & printBuffer (Ostream & os) const
Definition at line 96 of file genericRagelLemonDriver.C.
References os().
reportFatal() [1/2]
void reportFatal (const std::string & msg) const
Definition at line 124 of file genericRagelLemonDriver.C.
References Foam::exit(), Foam::FatalIOError, FUNCTION_NAME, Foam::nl, and os().
reportFatal() [2/2]
void reportFatal (const std::string & msg, size_t pos) const
Definition at line 153 of file genericRagelLemonDriver.C.
References Foam::exit(), Foam::FatalIOError, FUNCTION_NAME, Foam::nl, os(), and Foam::pos().
Member Data Documentation
content_
std::reference_wrapper<const std::string> content_ protected
Definition at line 62 of file genericRagelLemonDriver.H.
Referenced by genericRagelLemonDriver::content().
start_
size_t start_ protected
Definition at line 65 of file genericRagelLemonDriver.H.
length_
size_t length_ protected
Definition at line 68 of file genericRagelLemonDriver.H.
position_
size_t position_ protected
Definition at line 71 of file genericRagelLemonDriver.H.
Referenced by genericRagelLemonDriver::parsePosition(), and genericRagelLemonDriver::parsePosition().
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/strings/parsing/genericRagelLemonDriver.H
src/OpenFOAM/primitives/strings/parsing/genericRagelLemonDriver.C