OpenFOAM: patchIdentifier Class Reference
patchIdentifier Class Reference
Identifies a patch by name and index, with optional physical type and group information.
#include <patchIdentifier.H>
Public Member Functions
patchIdentifier (const patchIdentifier &)=default
patchIdentifier & operator= (const patchIdentifier &)=default
virtual ~patchIdentifier ()=default
patchIdentifier ()
patchIdentifier (const word &name, const label index)
patchIdentifier (const word &name, const label index, const word &physicalType, const wordList &inGroups=wordList())
patchIdentifier (const word &name, const dictionary &dict, const label index)
patchIdentifier (const patchIdentifier &ident, const label index)
const word & name () const noexcept
word & name () noexcept
label index () const noexcept
label & index () noexcept
const word & physicalType () const noexcept
word & physicalType () noexcept
const wordList & inGroups () const noexcept
wordList & inGroups () noexcept
bool inGroup (const word &name) const
void write (Ostream &os) const
Static Public Member Functions
static word defaultName (const label n=-1)
Detailed Description
Identifies a patch by name and index, with optional physical type and group information.
Source files
patchIdentifier.H
patchIdentifier.C
Definition at line 51 of file patchIdentifier.H.
Constructor & Destructor Documentation
patchIdentifier() [1/6]
patchIdentifier (const patchIdentifier &) default
~patchIdentifier()
virtual ~patchIdentifier () virtual default
patchIdentifier() [2/6]
patchIdentifier ()
Definition at line 27 of file patchIdentifier.C.
patchIdentifier() [3/6]
patchIdentifier (const word & name, const label index)
Definition at line 34 of file patchIdentifier.C.
patchIdentifier() [4/6]
patchIdentifier (const word & name, const label index, const word & physicalType, const wordList & inGroups = wordList())
Definition at line 45 of file patchIdentifier.C.
patchIdentifier() [5/6]
patchIdentifier (const word & name, const dictionary & dict, const label index)
Definition at line 60 of file patchIdentifier.C.
References dict.
patchIdentifier() [6/6]
patchIdentifier (const patchIdentifier & ident, const label index)
Definition at line 74 of file patchIdentifier.C.
Member Function Documentation
defaultName()
static word defaultName (const label n = -1) inline static
Definition at line 72 of file patchIdentifier.H.
References n.
Referenced by voxelMeshSearch::makeMesh().
operator=()
patchIdentifier & operator= (const patchIdentifier &) default
Referenced by polyPatch::operator=().
name() [1/2]
const word & name () const inline noexcept
Definition at line 131 of file patchIdentifier.H.
Referenced by symmetryPlanePolyPatch::calcGeometry(), wedgePolyPatch::calcGeometry(), ConstantField< Type >::ConstantField(), cyclicACMIPolyPatch::cyclicACMIPolyPatch(), cyclicACMIPolyPatch::cyclicACMIPolyPatch(), cyclicAMIPolyPatch::cyclicAMIPolyPatch(), cyclicAMIPolyPatch::cyclicAMIPolyPatch(), cyclicPolyPatch::cyclicPolyPatch(), cyclicPolyPatch::cyclicPolyPatch(), patchIdentifier::inGroup(), faPatch::lookupPatchField(), fvPatch::name(), faPatch::New(), polyPatch::New(), oldCyclicPolyPatch::oldCyclicPolyPatch(), cyclicACMIPolyPatch::resetAMI(), cyclicAMIPolyPatch::restoreScaledGeometry(), cyclicACMIPolyPatch::scalePatchFaceAreas(), cyclicACMIPolyPatch::scalePatchFaceAreas(), symmetryFaPatch::symmetryFaPatch(), cyclicPolyPatch::transformGlobalFace(), cyclicACMIPolyPatch::updateAreas(), and wedgeFaPatch::wedgeFaPatch().
name() [2/2]
word & name () inline noexcept
Definition at line 137 of file patchIdentifier.H.
index() [1/2]
label index () const inline noexcept
Definition at line 143 of file patchIdentifier.H.
Referenced by boundaryPatch::boundaryPatch(), symmetryFaPatch::clone(), faPatch::clone(), emptyFaPatch::clone(), ignoreFaPatch::clone(), cyclicACMIPolyPatch::clone(), cyclicAMIPolyPatch::clone(), cyclicPeriodicAMIPolyPatch::clone(), mappedPolyPatch::clone(), mappedVariableThicknessWallPolyPatch::clone(), mappedWallPolyPatch::clone(), genericPolyPatch::clone(), cyclicPolyPatch::clone(), cyclicSlipPolyPatch::clone(), emptyPolyPatch::clone(), nonuniformTransformCyclicPolyPatch::clone(), oldCyclicPolyPatch::clone(), processorPolyPatch::clone(), processorCyclicPolyPatch::clone(), symmetryPolyPatch::clone(), symmetryPlanePolyPatch::clone(), wedgePolyPatch::clone(), wallPolyPatch::clone(), polyPatch::clone(), oversetPolyPatch::clone(), processorCyclicPolyPatch::clone(), cyclicACMIPolyPatch::clone(), cyclicAMIPolyPatch::clone(), cyclicPeriodicAMIPolyPatch::clone(), mappedPolyPatch::clone(), mappedVariableThicknessWallPolyPatch::clone(), mappedWallPolyPatch::clone(), genericPolyPatch::clone(), cyclicPolyPatch::clone(), cyclicSlipPolyPatch::clone(), emptyPolyPatch::clone(), nonuniformTransformCyclicPolyPatch::clone(), processorPolyPatch::clone(), processorCyclicPolyPatch::clone(), symmetryPolyPatch::clone(), symmetryPlanePolyPatch::clone(), wedgePolyPatch::clone(), wallPolyPatch::clone(), polyPatch::clone(), oversetPolyPatch::clone(), fvPatch::index(), faPatch::lookupPatchField(), cyclicFaPatch::neighbPatchID(), faPatch::New(), polyPatch::New(), and cyclicPolyPatch::owner().
index() [2/2]
label & index () inline noexcept
Definition at line 149 of file patchIdentifier.H.
physicalType() [1/2]
const word & physicalType () const inline noexcept
Definition at line 155 of file patchIdentifier.H.
physicalType() [2/2]
word & physicalType () inline noexcept
Definition at line 161 of file patchIdentifier.H.
inGroups() [1/2]
const wordList & inGroups () const inline noexcept
Definition at line 167 of file patchIdentifier.H.
Referenced by faPatch::faPatch(), faPatch::faPatch(), mappedPolyPatch::mappedPolyPatch(), mappedPolyPatch::mappedPolyPatch(), mappedWallPolyPatch::mappedWallPolyPatch(), mappedWallPolyPatch::mappedWallPolyPatch(), oversetPolyPatch::oversetPolyPatch(), oversetPolyPatch::oversetPolyPatch(), polyPatch::polyPatch(), polyPatch::polyPatch(), wallPolyPatch::wallPolyPatch(), and wallPolyPatch::wallPolyPatch().
inGroups() [2/2]
wordList & inGroups () inline noexcept
Definition at line 173 of file patchIdentifier.H.
inGroup()
bool inGroup (const word & name) const inline
Definition at line 179 of file patchIdentifier.H.
References UList< T >::found(), and patchIdentifier::name().
write()
void write (Ostream & os) const
Definition at line 89 of file patchIdentifier.C.
References token::END_STATEMENT, Foam::nl, os(), Ostream::writeEntry(), and Ostream::writeKeyword().
Referenced by faPatch::write(), mappedWallPolyPatch::write(), genericPolyPatch::write(), oldCyclicPolyPatch::write(), boundaryPatch::write(), and polyPatch::write().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/Identifiers/patch/patchIdentifier.H
src/OpenFOAM/meshes/Identifiers/patch/patchIdentifier.C