OpenFOAM: treeDataPrimitivePatch< PatchType >::findSelfIntersectOp Class Reference
treeDataPrimitivePatch< PatchType >::findSelfIntersectOp Class Reference
#include <treeDataPrimitivePatch.H>
Public Member Functions
findSelfIntersectOp (const indexedOctree< treeDataPrimitivePatch > &tree, const label edgeID)
bool operator() (const label index, const point &start, const point &end, point &intersectionPoint) const
Detailed Description
template<class PatchType>
class Foam::treeDataPrimitivePatch< PatchType >::findSelfIntersectOp
Definition at line 169 of file treeDataPrimitivePatch.H.
Constructor & Destructor Documentation
findSelfIntersectOp()
template<class PatchType > findSelfIntersectOp (const indexedOctree< treeDataPrimitivePatch > & tree, const label edgeID)
Definition at line 126 of file treeDataPrimitivePatch.C.
Member Function Documentation
operator()()
template<class PatchType > bool operator() (const label index, const point & start, const point & end, point & intersectionPoint) const
Definition at line 583 of file treeDataPrimitivePatch.C.
References e, Foam::exit(), f(), Foam::FatalError, FatalErrorInFunction, treeDataPrimitivePatch< PatchType >::findIntersection(), and treeDataPrimitivePatch< PatchType >::patch().
The documentation for this class was generated from the following files:
src/meshTools/indexedOctree/treeDataPrimitivePatch.H
src/meshTools/indexedOctree/treeDataPrimitivePatch.C