OpenFOAM: masterCoarsestGAMGProcAgglomeration Class Reference
masterCoarsestGAMGProcAgglomeration Class Reference
Processor agglomeration of GAMGAgglomerations.
#include <masterCoarsestGAMGProcAgglomeration.H>
Public Member Functions
TypeName ("masterCoarsest")
masterCoarsestGAMGProcAgglomeration (GAMGAgglomeration &agglom, const dictionary &controlDict)
virtual ~masterCoarsestGAMGProcAgglomeration ()
virtual bool agglomerate ()
Public Member Functions inherited from GAMGProcAgglomeration
TypeName ("GAMGProcAgglomeration")
declareRunTimeSelectionTable (autoPtr, GAMGProcAgglomeration, GAMGAgglomeration,(GAMGAgglomeration &agglom, const dictionary &controlDict),(agglom, controlDict))
GAMGProcAgglomeration (const GAMGProcAgglomeration &)=delete
void operator= (const GAMGProcAgglomeration &)=delete
GAMGProcAgglomeration (GAMGAgglomeration &agglom, const dictionary &controlDict)
virtual ~GAMGProcAgglomeration ()
Additional Inherited Members
Static Public Member Functions inherited from GAMGProcAgglomeration
static autoPtr< GAMGProcAgglomeration > New (const word &type, GAMGAgglomeration &agglom, const dictionary &controlDict)
Protected Member Functions inherited from GAMGProcAgglomeration
void printStats (Ostream &os, GAMGAgglomeration &agglom) const
bool agglomerate (const label fineLevelIndex, const labelList &procAgglomMap, const labelList &masterProcs, const List< label > &agglomProcIDs, const label procAgglomComm)
void clearCommunicators ()
Static Protected Member Functions inherited from GAMGProcAgglomeration
static labelListList globalCellCells (const lduMesh &)
Protected Attributes inherited from GAMGProcAgglomeration
GAMGAgglomeration & agglom_
DynamicList< label > comms_
Detailed Description
Processor agglomeration of GAMGAgglomerations.
by default agglomerates onto the master processor
optionally have multiple masters through the nProcessorsPerMaster parameter. e.g.
p { solver GAMG; tolerance 1e-06; relTol 0.1; smoother GaussSeidel;
nCellsInCoarsestLevel 10;
processorAgglomerator masterCoarsest; Groups of 32 cores get combined so each 'master' gets (roughly) 32*nCellsInCoarsestLevel cells. nProcessorsPerMaster 32;
Alternative : specify number of (equi-distributed) masters nMasters 2;
Restart local agglomeration after processor agglomeration. Used as nCellsInCoarsestLevel. Only applicable for pair-wise local agglomeration methods. nCellsInMasterLevel 1; }
Source files
masterCoarsestGAMGProcAgglomeration.H
masterCoarsestGAMGProcAgglomeration.C
Definition at line 77 of file masterCoarsestGAMGProcAgglomeration.H.
Constructor & Destructor Documentation
masterCoarsestGAMGProcAgglomeration()
masterCoarsestGAMGProcAgglomeration (GAMGAgglomeration & agglom, const dictionary & controlDict)
Definition at line 43 of file masterCoarsestGAMGProcAgglomeration.C.
References controlDict(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, keyType::LITERAL, UPstream::nProcs(), and Foam::readLabel().
~masterCoarsestGAMGProcAgglomeration()
~masterCoarsestGAMGProcAgglomeration () virtual
Definition at line 99 of file masterCoarsestGAMGProcAgglomeration.C.
Member Function Documentation
TypeName()
TypeName ("masterCoarsest")
agglomerate()
bool agglomerate () virtual
Implements GAMGProcAgglomeration.
Definition at line 106 of file masterCoarsestGAMGProcAgglomeration.C.
References GAMGProcAgglomeration::agglomerate(), UPstream::allocateCommunicator(), UPtrList< T >::back(), GAMGAgglomeration::calculateRegionMaster(), Foam::endl(), Foam::flatOutput(), forAll, Foam::Info, Foam::invertOneToMany(), UPstream::myProcNo(), Foam::nl, UPstream::nProcs(), p, Foam::Pout, UPtrList< T >::size(), UList< T >::size(), and Foam::Zero.
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/GAMGProcAgglomerations/masterCoarsestGAMGProcAgglomeration/masterCoarsestGAMGProcAgglomeration.H
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/GAMGProcAgglomerations/masterCoarsestGAMGProcAgglomeration/masterCoarsestGAMGProcAgglomeration.C