OpenFOAM: driftModel Class Reference
driftModel Class Reference abstract
Base class for drift models.
#include <driftModel.H>
Classes
class iNew
Public Member Functions
TypeName ("driftModel")
declareRunTimeSelectionTable (autoPtr, driftModel, dictionary,(const populationBalanceModel &popBal, const dictionary &dict),(popBal, dict))
driftModel (const populationBalanceModel &popBal, const dictionary &dict)
autoPtr< driftModel > clone () const
virtual ~driftModel ()=default
const populationBalanceModel & popBal () const
virtual void correct ()
virtual void addToDriftRate (volScalarField &driftRate, const label i)=0
Static Public Member Functions
static autoPtr< driftModel > New (const word &type, const populationBalanceModel &popBal, const dictionary &dict)
Protected Attributes
const populationBalanceModel & popBal_
Detailed Description
Base class for drift models.
Source files
driftModel.H
driftModel.C
Definition at line 48 of file driftModel.H.
Constructor & Destructor Documentation
driftModel()
driftModel (const populationBalanceModel & popBal, const dictionary & dict)
Definition at line 66 of file driftModel.C.
~driftModel()
virtual ~driftModel () virtual default
Member Function Documentation
TypeName()
TypeName ("driftModel")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , driftModel , dictionary , (const populationBalanceModel &popBal, const dictionary &dict) , (popBal, dict))
clone()
autoPtr< driftModel > clone () const inline
Definition at line 109 of file driftModel.H.
References NotImplemented.
New()
Foam::autoPtr< Foam::diameterModels::driftModel > New (const word & type, const populationBalanceModel & popBal, const dictionary & dict) static
Definition at line 40 of file driftModel.C.
References dict, Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, driftModel::popBal(), and Foam::type().
Referenced by driftModel::iNew::operator()().
popBal()
const populationBalanceModel & popBal () const inline
Definition at line 133 of file driftModel.H.
References driftModel::popBal_.
Referenced by driftModel::New().
correct()
void correct () virtual
Reimplemented in constantDrift, and phaseChange.
Definition at line 78 of file driftModel.C.
addToDriftRate()
virtual void addToDriftRate (volScalarField & driftRate, const label i) pure virtual
Implemented in constantDrift, densityChangeDrift, and phaseChange.
Member Data Documentation
popBal_
const populationBalanceModel& popBal_ protected
Definition at line 55 of file driftModel.H.
Referenced by phaseChange::phaseChange(), and driftModel::popBal().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/populationBalanceModel/driftModels/driftModel/driftModel.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/populationBalanceModel/driftModels/driftModel/driftModel.C