OpenFOAM: GAMGInterface Class Reference
GAMGInterface Class Reference abstract
Abstract base class for GAMG agglomerated interfaces.
#include <GAMGInterface.H>
Public Member Functions
TypeName ("GAMGInterface")
declareRunTimeSelectionTable (autoPtr, GAMGInterface, lduInterface,(const label index, const lduInterfacePtrsList &coarseInterfaces, const lduInterface &fineInterface, const labelField &localRestrictAddressing, const labelField &neighbourRestrictAddressing, const label fineLevelIndex, const label coarseComm),(index, coarseInterfaces, fineInterface, localRestrictAddressing, neighbourRestrictAddressing, fineLevelIndex, coarseComm))
declareRunTimeSelectionTable (autoPtr, GAMGInterface, Istream,(const label index, const lduInterfacePtrsList &coarseInterfaces, Istream &is),(index, coarseInterfaces, is))
GAMGInterface (const label index, const lduInterfacePtrsList &coarseInterfaces)
GAMGInterface (const label index, const lduInterfacePtrsList &coarseInterfaces, const labelUList &faceCells, const labelUList &faceRestrictAddressing)
GAMGInterface (const label index, const lduInterfacePtrsList &coarseInterfaces, Istream &is)
virtual label size () const
virtual label index () const
virtual const lduInterfacePtrsList & coarseInterfaces () const
virtual const labelUList & faceCells () const
virtual const labelList & faceRestrictAddressing () const
virtual labelList & faceRestrictAddressing ()
template<class Type >
tmp< Field< Type > > interfaceInternalField (const UList< Type > &internalData) const
template<class Type >
tmp< Field< Type > > interfaceInternalField (const UList< Type > &internalData, const labelUList &faceCells) const
template<class Type >
void interfaceInternalField (const UList< Type > &internalData, List< Type > &) const
virtual tmp< labelField > interfaceInternalField (const labelUList &internalData) const
virtual tmp< labelField > interfaceInternalField (const labelUList &internalData, const labelUList &faceCells) const
void combine (const GAMGInterface &)
virtual tmp< scalarField > agglomerateCoeffs (const scalarField &fineCoeffs) const
virtual void write (Ostream &) const =0
template<class Type >
Foam::tmp< Foam::Field< Type > > interfaceInternalField (const UList< Type > &iF) const
template<class Type >
Foam::tmp< Foam::Field< Type > > interfaceInternalField (const UList< Type > &iF, const labelUList &faceCells) const
Public Member Functions inherited from lduInterface
TypeNameNoDebug ("lduInterface")
lduInterface () noexcept=default
virtual ~lduInterface ()=default
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &iF) const
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &iF, const labelUList &faceCells) const
virtual tmp< labelField > internalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &iF) const =0
Static Public Member Functions
static autoPtr< GAMGInterface > New (const label index, const lduInterfacePtrsList &coarseInterfaces, const lduInterface &fineInterface, const labelField &localRestrictAddressing, const labelField &neighbourRestrictAddressing, const label fineLevelIndex, const label coarseComm)
static autoPtr< GAMGInterface > New (const word &coupleType, const label index, const lduInterfacePtrsList &coarseInterfaces, Istream &is)
Protected Member Functions
GAMGInterface (const GAMGInterface &)=delete
void operator= (const GAMGInterface &)=delete
Protected Attributes
const label index_
const lduInterfacePtrsList & coarseInterfaces_
labelList faceCells_
labelList faceRestrictAddressing_
Detailed Description
Abstract base class for GAMG agglomerated interfaces.
Source files
GAMGInterface.H
GAMGInterface.C
newAmgInterface.C
Definition at line 50 of file GAMGInterface.H.
Constructor & Destructor Documentation
GAMGInterface() [1/4]
GAMGInterface (const GAMGInterface &) protected delete
GAMGInterface() [2/4]
GAMGInterface (const label index, const lduInterfacePtrsList & coarseInterfaces) inline
Definition at line 160 of file GAMGInterface.H.
GAMGInterface() [3/4]
GAMGInterface (const label index, const lduInterfacePtrsList & coarseInterfaces, const labelUList & faceCells, const labelUList & faceRestrictAddressing) inline
Definition at line 172 of file GAMGInterface.H.
GAMGInterface() [4/4]
GAMGInterface (const label index, const lduInterfacePtrsList & coarseInterfaces, Istream & is)
Definition at line 36 of file GAMGInterface.C.
Member Function Documentation
operator=()
void operator= (const GAMGInterface &) protected delete
TypeName()
TypeName ("GAMGInterface")
declareRunTimeSelectionTable() [1/2]
declareRunTimeSelectionTable (autoPtr , GAMGInterface , lduInterface , (const label index, const lduInterfacePtrsList &coarseInterfaces, const lduInterface &fineInterface, const labelField &localRestrictAddressing, const labelField &neighbourRestrictAddressing, const label fineLevelIndex, const label coarseComm) , (index, coarseInterfaces, fineInterface, localRestrictAddressing, neighbourRestrictAddressing, fineLevelIndex, coarseComm))
declareRunTimeSelectionTable() [2/2]
declareRunTimeSelectionTable (autoPtr , GAMGInterface , Istream , (const label index, const lduInterfacePtrsList &coarseInterfaces, Istream &is) , (index, coarseInterfaces, is))
New() [1/2]
Foam::autoPtr< Foam::GAMGInterface > New (const label index, const lduInterfacePtrsList & coarseInterfaces, const lduInterface & fineInterface, const labelField & localRestrictAddressing, const labelField & neighbourRestrictAddressing, const label fineLevelIndex, const label coarseComm) static
Definition at line 29 of file GAMGInterfaceNew.C.
References GAMGInterface::coarseInterfaces(), Foam::exit(), Foam::FatalError, FatalErrorInLookup, and GAMGInterface::index().
Referenced by GAMGAgglomeration::agglomerateLduAddressing(), GAMGSolver::GAMGSolver(), lduPrimitiveMesh::gather(), and GAMGInterface::interfaceInternalField().
New() [2/2]
Foam::autoPtr< Foam::GAMGInterface > New (const word & coupleType, const label index, const lduInterfacePtrsList & coarseInterfaces, Istream & is) static
Definition at line 70 of file GAMGInterfaceNew.C.
References Foam::exit(), Foam::FatalError, and FatalErrorInLookup.
size()
virtual label size () const inline virtual
Definition at line 201 of file GAMGInterface.H.
References GAMGInterface::faceCells_, and UList< T >::size().
Referenced by GAMGInterface::interfaceInternalField(), cyclicACMIGAMGInterfaceField::size(), cyclicAMIGAMGInterfaceField::size(), cyclicGAMGInterfaceField::size(), processorGAMGInterfaceField::size(), and calculatedProcessorGAMGInterfaceField::size().
index()
virtual label index () const inline virtual
Definition at line 206 of file GAMGInterface.H.
References GAMGInterface::index_.
Referenced by GAMGInterface::New().
coarseInterfaces()
virtual const lduInterfacePtrsList & coarseInterfaces () const inline virtual
Definition at line 211 of file GAMGInterface.H.
References GAMGInterface::coarseInterfaces_.
Referenced by GAMGInterface::New().
faceCells()
virtual const labelUList & faceCells () const inline virtual
Implements lduInterface.
Definition at line 217 of file GAMGInterface.H.
References GAMGInterface::faceCells_.
faceRestrictAddressing() [1/2]
virtual const labelList & faceRestrictAddressing () const inline virtual
Definition at line 223 of file GAMGInterface.H.
References GAMGInterface::faceRestrictAddressing_.
faceRestrictAddressing() [2/2]
virtual labelList & faceRestrictAddressing () inline virtual
Definition at line 229 of file GAMGInterface.H.
References GAMGInterface::faceRestrictAddressing_.
interfaceInternalField() [1/7]
template<class Type > tmp< Field< Type > > interfaceInternalField (const UList< Type > & internalData) const
Referenced by GAMGInterface::interfaceInternalField().
interfaceInternalField() [2/7]
template<class Type > tmp< Field< Type > > interfaceInternalField (const UList< Type > & internalData, const labelUList & faceCells) const
interfaceInternalField() [3/7]
template<class Type > void interfaceInternalField (const UList< Type > & internalData, List< Type > & result) const
Definition at line 57 of file GAMGInterfaceTemplates.C.
References forAll, and PtrList< T >::resize().
interfaceInternalField() [4/7]
Foam::tmp< Foam::labelField > interfaceInternalField (const labelUList & internalData) const virtual
Implements lduInterface.
Definition at line 65 of file GAMGInterface.C.
interfaceInternalField() [5/7]
Foam::tmp< Foam::labelField > interfaceInternalField (const labelUList & internalData, const labelUList & faceCells) const virtual
Implements lduInterface.
Definition at line 74 of file GAMGInterface.C.
combine()
void combine (const GAMGInterface & coarseGi)
Definition at line 52 of file GAMGInterface.C.
References forAll.
agglomerateCoeffs()
Foam::tmp< Foam::scalarField > agglomerateCoeffs (const scalarField & fineCoeffs) const virtual
Definition at line 84 of file GAMGInterface.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::max(), tmp< T >::New(), UPtrList< T >::size(), and Foam::Zero.
write()
void write (Ostream & os) const pure virtual
Implemented in cyclicACMIGAMGInterface, cyclicAMIGAMGInterface, oversetGAMGInterface, cyclicGAMGInterface, processorGAMGInterface, and calculatedProcessorGAMGInterface.
Definition at line 118 of file GAMGInterface.C.
References os(), and token::SPACE.
Referenced by cyclicGAMGInterface::write(), processorGAMGInterface::write(), and calculatedProcessorGAMGInterface::write().
interfaceInternalField() [6/7]
template<class Type > Foam::tmp< Foam::Field< Type > > interfaceInternalField (const UList< Type > & iF) const
Definition at line 27 of file GAMGInterfaceTemplates.C.
References GAMGInterface::interfaceInternalField(), GAMGInterface::New(), and GAMGInterface::size().
interfaceInternalField() [7/7]
template<class Type > Foam::tmp< Foam::Field< Type > > interfaceInternalField (const UList< Type > & iF, const labelUList & faceCells) const
Definition at line 39 of file GAMGInterfaceTemplates.C.
References forAll, and Foam::New().
Member Data Documentation
index_
const label index_ protected
Definition at line 59 of file GAMGInterface.H.
Referenced by GAMGInterface::index().
coarseInterfaces_
const lduInterfacePtrsList& coarseInterfaces_ protected
Definition at line 62 of file GAMGInterface.H.
Referenced by GAMGInterface::coarseInterfaces(), cyclicACMIGAMGInterface::neighbPatch(), cyclicAMIGAMGInterface::neighbPatch(), and cyclicGAMGInterface::neighbPatch().
faceCells_
labelList faceCells_ protected
Definition at line 65 of file GAMGInterface.H.
Referenced by calculatedProcessorGAMGInterface::calculatedProcessorGAMGInterface(), cyclicACMIGAMGInterface::cyclicACMIGAMGInterface(), cyclicAMIGAMGInterface::cyclicAMIGAMGInterface(), cyclicGAMGInterface::cyclicGAMGInterface(), GAMGInterface::faceCells(), oversetGAMGInterface::oversetGAMGInterface(), processorGAMGInterface::processorGAMGInterface(), and GAMGInterface::size().
faceRestrictAddressing_
labelList faceRestrictAddressing_ protected
Definition at line 68 of file GAMGInterface.H.
Referenced by calculatedProcessorGAMGInterface::calculatedProcessorGAMGInterface(), cyclicACMIGAMGInterface::cyclicACMIGAMGInterface(), cyclicAMIGAMGInterface::cyclicAMIGAMGInterface(), cyclicGAMGInterface::cyclicGAMGInterface(), GAMGInterface::faceRestrictAddressing(), GAMGInterface::faceRestrictAddressing(), oversetGAMGInterface::oversetGAMGInterface(), and processorGAMGInterface::processorGAMGInterface().
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/interfaces/GAMGInterface/GAMGInterface.H
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/interfaces/GAMGInterface/GAMGInterface.C
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/interfaces/GAMGInterface/GAMGInterfaceNew.C
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/interfaces/GAMGInterface/GAMGInterfaceTemplates.C