OpenFOAM: dynamicCode Class Reference
dynamicCode Class Reference
Tools for handling dynamic code compilation.
#include <dynamicCode.H>
Public Member Functions
dynamicCode (const dynamicCode &)=delete
void operator= (const dynamicCode &)=delete
dynamicCode (const word &codeName, const word &codeDirName="")
const word & codeName () const noexcept
const word & codeDirName () const noexcept
const fileName & codeRoot () const noexcept
const fileName & libSubDir () const noexcept
fileName codePath () const
fileName codeRelPath () const
fileName libPath () const
fileName libRelPath () const
fileName digestFile () const
void clear ()
void reset (const dynamicCodeContext &)
void addCompileFile (const fileName &name)
void addCopyFile (const fileName &name)
void addCreateFile (const fileName &name, const std::string &contents)
void setFilterContext (const dynamicCodeContext &)
void setFilterVariable (const word &key, const std::string &value)
void setMakeOptions (const std::string &content)
bool upToDate (const dynamicCodeContext &context) const
bool upToDate (const SHA1Digest &sha1) const
bool copyOrCreateFiles (const bool verbose=false) const
bool wmakeLibso () const
template<class Type >
void setFieldTemplates ()
Static Public Member Functions
static void checkSecurity (const char *title, const dictionary &)
static void waitForFile (const fileName &file, const dictionary &contextDict)
Static Public Attributes
static const word codeTemplateEnvName = "FOAM_CODE_TEMPLATES"
static const fileName codeTemplateDirName = "codeTemplates/dynamicCode"
static int allowSystemOperations
Protected Member Functions
bool writeCommentSHA1 (Ostream &) const
bool createMakeFiles () const
bool createMakeOptions () const
bool writeDigest (const SHA1Digest &) const
bool writeDigest (const std::string &) const
Static Protected Member Functions
static void copyAndFilter (ISstream &, OSstream &, const HashTable< string > &mapping)
static bool resolveTemplates (const UList< fileName > &templateNames, DynamicList< fileName > &resolvedFiles, DynamicList< fileName > &badFiles)
Static Protected Attributes
static const char *const targetLibDir = "LIB = $(PWD)/../platforms/$(WM_OPTIONS)/lib"
static const char *const topDirName = "dynamicCode"
Detailed Description
Tools for handling dynamic code compilation.
Source files
dynamicCode.H
dynamicCode.C
Definition at line 56 of file dynamicCode.H.
Constructor & Destructor Documentation
dynamicCode() [1/2]
dynamicCode (const dynamicCode &) delete
dynamicCode() [2/2]
dynamicCode (const word & codeName, const word & codeDirName = "") explicit
Definition at line 284 of file dynamicCode.C.
References dynamicCode::clear().
Member Function Documentation
copyAndFilter()
void copyAndFilter (ISstream & is, OSstream & os, const HashTable< string > & mapping) static protected
Definition at line 95 of file dynamicCode.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, IOstream::good(), Foam::stringOps::inplaceExpand(), OFstream::name(), Foam::nl, os(), and OBJstream::writeQuoted().
resolveTemplates()
bool resolveTemplates (const UList< fileName > & templateNames, DynamicList< fileName > & resolvedFiles, DynamicList< fileName > & badFiles) static protected
Definition at line 132 of file dynamicCode.C.
References UPtrList< T >::empty(), Foam::findEtcFile(), Foam::getEnv(), Foam::isDir(), Foam::isFile(), and PtrList< T >::push_back().
writeCommentSHA1()
bool writeCommentSHA1 (Ostream & os) const protected
Definition at line 176 of file dynamicCode.C.
References os(), and OBJstream::writeQuoted().
createMakeFiles()
bool createMakeFiles () const protected
Definition at line 190 of file dynamicCode.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, IOstream::good(), Foam::mkDir(), Foam::nl, os(), and OBJstream::writeQuoted().
createMakeOptions()
bool createMakeOptions () const protected
Definition at line 228 of file dynamicCode.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, IOstream::good(), Foam::mkDir(), Foam::nl, os(), and OBJstream::writeQuoted().
writeDigest() [1/2]
bool writeDigest (const SHA1Digest & sha1) const protected
Definition at line 257 of file dynamicCode.C.
References IOstream::good(), Foam::mkDir(), Foam::nl, os(), fileName::path(), and SHA1Digest::write().
writeDigest() [2/2]
bool writeDigest (const std::string & sha1) const protected
Definition at line 269 of file dynamicCode.C.
References IOstream::good(), Foam::mkDir(), Foam::nl, os(), fileName::path(), and OBJstream::writeQuoted().
checkSecurity()
void checkSecurity (const char * title, const dictionary & dict) static
Definition at line 58 of file dynamicCode.C.
References dynamicCode::allowSystemOperations, Foam::foamVersion::api, dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, Foam::isAdministrator(), and Foam::nl.
Referenced by codeStream::evaluate(), and codedBase::updateLibrary().
operator=()
void operator= (const dynamicCode &) delete
codeName()
const word & codeName () const inline noexcept
Definition at line 180 of file dynamicCode.H.
codeDirName()
const word & codeDirName () const inline noexcept
Definition at line 183 of file dynamicCode.H.
codeRoot()
const fileName & codeRoot () const inline noexcept
Definition at line 187 of file dynamicCode.H.
libSubDir()
const fileName & libSubDir () const inline noexcept
Definition at line 191 of file dynamicCode.H.
codePath()
fileName codePath () const inline
Definition at line 195 of file dynamicCode.H.
codeRelPath()
Foam::fileName codeRelPath () const
Definition at line 302 of file dynamicCode.C.
libPath()
Foam::fileName libPath () const
Definition at line 308 of file dynamicCode.C.
References dlLibraryTable::fullname().
libRelPath()
Foam::fileName libRelPath () const
Definition at line 314 of file dynamicCode.C.
References dlLibraryTable::fullname().
digestFile()
fileName digestFile () const inline
Definition at line 216 of file dynamicCode.H.
clear()
void clear ()
Definition at line 320 of file dynamicCode.C.
References PtrList< T >::clear(), and PtrList< T >::set().
Referenced by dynamicCode::dynamicCode().
reset()
void reset (const dynamicCodeContext & context)
Definition at line 336 of file dynamicCode.C.
References clear().
addCompileFile()
void addCompileFile (const fileName & name)
Definition at line 346 of file dynamicCode.C.
References Foam::name(), and PtrList< T >::push_back().
addCopyFile()
void addCopyFile (const fileName & name)
Definition at line 352 of file dynamicCode.C.
References Foam::name(), and PtrList< T >::push_back().
addCreateFile()
void addCreateFile (const fileName & name, const std::string & contents)
Definition at line 358 of file dynamicCode.C.
References PtrList< T >::emplace_back(), and Foam::name().
setFilterContext()
void setFilterContext (const dynamicCodeContext & context)
Definition at line 368 of file dynamicCode.C.
References dynamicCodeContext::code(), dynamicCodeContext::include(), dynamicCodeContext::localCode(), PtrList< T >::set(), and dynamicCodeContext::sha1().
setFilterVariable()
void setFilterVariable (const word & key, const std::string & value)
Definition at line 380 of file dynamicCode.C.
References PtrList< T >::set().
Referenced by dynamicCode::setFieldTemplates().
setMakeOptions()
void setMakeOptions (const std::string & content)
Definition at line 390 of file dynamicCode.C.
upToDate() [1/2]
bool upToDate (const dynamicCodeContext & context) const
Definition at line 523 of file dynamicCode.C.
References dynamicCodeContext::sha1().
upToDate() [2/2]
bool upToDate (const SHA1Digest & sha1) const
Definition at line 510 of file dynamicCode.C.
References Foam::exists().
copyOrCreateFiles()
bool copyOrCreateFiles (const bool verbose = false) const
Definition at line 396 of file dynamicCode.C.
References DetailInfo, UPtrList< T >::empty(), Foam::endl(), Foam::exit(), Foam::stringOps::expand(), Foam::FatalError, FatalErrorInFunction, IOstream::good(), Foam::mkDir(), Foam::nl, os(), UPtrList< T >::size(), and OBJstream::writeQuoted().
wmakeLibso()
bool wmakeLibso () const
Definition at line 488 of file dynamicCode.C.
References Foam::endl(), Foam::Info, Foam::infoDetailLevel, Foam::InfoErr, os(), and Foam::system().
waitForFile()
void waitForFile (const fileName & file, const dictionary & contextDict) static
Definition at line 531 of file dynamicCode.C.
References Pstream::broadcast(), DebugPout, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, IOobject::fileModificationSkew, Foam::fileSize(), IOobject::maxFileModificationPolls, UPstream::myProcNo(), Foam::nl, UPstream::parRun(), and Foam::sleep().
Referenced by codeStream::getFunction().
setFieldTemplates()
template<class Type > void setFieldTemplates () inline
Definition at line 277 of file dynamicCode.H.
References dynamicCode::setFilterVariable().
Member Data Documentation
targetLibDir
const char *const targetLibDir = "LIB = $(PWD)/../platforms/$(WM_OPTIONS)/lib" static protected
Definition at line 93 of file dynamicCode.H.
topDirName
const char *const topDirName = "dynamicCode" static protected
Definition at line 96 of file dynamicCode.H.
codeTemplateEnvName
const Foam::word codeTemplateEnvName = "FOAM_CODE_TEMPLATES" static
Definition at line 141 of file dynamicCode.H.
codeTemplateDirName
const Foam::fileName codeTemplateDirName = "codeTemplates/dynamicCode" static
Definition at line 145 of file dynamicCode.H.
allowSystemOperations
int allowSystemOperations static
Definition at line 148 of file dynamicCode.H.
Referenced by dynamicCode::checkSecurity(), argList::parse(), and systemCall::read().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/dynamicLibrary/dynamicCode/dynamicCode.H
src/OpenFOAM/db/dynamicLibrary/dynamicCode/dynamicCode.C