OpenFOAM: pressureInletUniformVelocityFvPatchVectorField Class Reference
pressureInletUniformVelocityFvPatchVectorField Class Reference
Boundary conditions » Inlet
This velocity inlet boundary condition is applied to patches where the pressure is specified. The uniform inflow velocity is obtained by averaging the flux over the patch, and then applying it in the direction normal to the patch faces.
#include <pressureInletUniformVelocityFvPatchVectorField.H>
Public Member Functions
TypeName ("pressureInletUniformVelocity")
pressureInletUniformVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
pressureInletUniformVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
pressureInletUniformVelocityFvPatchVectorField (const pressureInletUniformVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
pressureInletUniformVelocityFvPatchVectorField (const pressureInletUniformVelocityFvPatchVectorField &)
virtual tmp< fvPatchVectorField > clone () const
pressureInletUniformVelocityFvPatchVectorField (const pressureInletUniformVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
virtual bool assignable () const
virtual void updateCoeffs ()
virtual void operator= (const fvPatchField< vector > &pvf)
Public Member Functions inherited from pressureInletVelocityFvPatchVectorField
TypeName ("pressureInletVelocity")
pressureInletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
pressureInletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
pressureInletVelocityFvPatchVectorField (const pressureInletVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
pressureInletVelocityFvPatchVectorField (const pressureInletVelocityFvPatchVectorField &)
pressureInletVelocityFvPatchVectorField (const pressureInletVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
const word & rhoName () const
word & rhoName ()
const word & phiName () const
word & phiName ()
virtual void write (Ostream &) const
Detailed Description
This velocity inlet boundary condition is applied to patches where the pressure is specified. The uniform inflow velocity is obtained by averaging the flux over the patch, and then applying it in the direction normal to the patch faces.
Usage
Example of the boundary condition specification:
<patchName>
{
    type            pressureInletUniformVelocity;
    value           uniform 0;
}
Source files
pressureInletUniformVelocityFvPatchVectorField.H
pressureInletUniformVelocityFvPatchVectorField.C
Definition at line 62 of file pressureInletUniformVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
pressureInletUniformVelocityFvPatchVectorField() [1/5]
pressureInletUniformVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Definition at line 28 of file pressureInletUniformVelocityFvPatchVectorField.C.
pressureInletUniformVelocityFvPatchVectorField() [2/5]
pressureInletUniformVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Definition at line 52 of file pressureInletUniformVelocityFvPatchVectorField.C.
pressureInletUniformVelocityFvPatchVectorField() [3/5]
pressureInletUniformVelocityFvPatchVectorField (const pressureInletUniformVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 39 of file pressureInletUniformVelocityFvPatchVectorField.C.
pressureInletUniformVelocityFvPatchVectorField() [4/5]
pressureInletUniformVelocityFvPatchVectorField (const pressureInletUniformVelocityFvPatchVectorField & pivpvf)
Definition at line 64 of file pressureInletUniformVelocityFvPatchVectorField.C.
pressureInletUniformVelocityFvPatchVectorField() [5/5]
pressureInletUniformVelocityFvPatchVectorField (const pressureInletUniformVelocityFvPatchVectorField & pivpvf, const DimensionedField< vector, volMesh > & iF)
Definition at line 74 of file pressureInletUniformVelocityFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("pressureInletUniformVelocity")
clone() [1/2]
virtual tmp< fvPatchVectorField > clone () const inline virtual
Reimplemented from pressureInletVelocityFvPatchVectorField.
Definition at line 107 of file pressureInletUniformVelocityFvPatchVectorField.H.
clone() [2/2]
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Reimplemented from pressureInletVelocityFvPatchVectorField.
Definition at line 123 of file pressureInletUniformVelocityFvPatchVectorField.H.
assignable()
virtual bool assignable () const inline virtual
Reimplemented from pressureInletVelocityFvPatchVectorField.
Definition at line 138 of file pressureInletUniformVelocityFvPatchVectorField.H.
updateCoeffs()
void updateCoeffs () virtual
Reimplemented from pressureInletVelocityFvPatchVectorField.
Definition at line 87 of file pressureInletUniformVelocityFvPatchVectorField.C.
References Foam::gSum(), Foam::operator==(), and pressureInletVelocityFvPatchVectorField::updateCoeffs().
operator=()
void operator= (const fvPatchField< vector > & pvf) virtual
Reimplemented from pressureInletVelocityFvPatchVectorField.
Definition at line 102 of file pressureInletUniformVelocityFvPatchVectorField.C.
References Foam::gSum(), and Foam::operator==().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/pressureInletUniformVelocity/pressureInletUniformVelocityFvPatchVectorField.H
src/finiteVolume/fields/fvPatchFields/derived/pressureInletUniformVelocity/pressureInletUniformVelocityFvPatchVectorField.C