OpenFOAM: vtuSizing Class Reference
vtuSizing Class Reference
Sizing descriptions and routines for transcribing an OpenFOAM volume mesh into a VTK unstructured grid, with possible decomposition of polyhedral cells into primitive cell types.
#include <foamVtuSizing.H>
Public Types
enum contentType : char { LEGACY , XML , INTERNAL1 , INTERNAL2 }
enum slotType : char { CELLS , CELLS_OFFSETS , FACES , FACES_OFFSETS }
enum selectionModeType : char { FULL_MESH , SUBSET_MESH , SHAPE_MESH }
Public Member Functions
vtuSizing () noexcept
vtuSizing (const polyMesh &mesh)
vtuSizing (const polyMesh &mesh, const bool decompose)
void reset (const polyMesh &mesh, const bool decompose=false)
void reset (const polyMesh &mesh, const labelUList &subsetCellsIds, const bool decompose=false)
void resetShapes (const UList< cellShape > &shapes)
void clear () noexcept
bool decompose () const noexcept
bool manifold () const noexcept
selectionModeType selectionMode () const noexcept
label nCells () const noexcept
label nPoints () const noexcept
label nVertLabels () const noexcept
label nFaceLabels () const noexcept
label nCellsPoly () const noexcept
label nVertPoly () const noexcept
label nAddCells () const noexcept
label nAddPoints () const noexcept
label nAddVerts () const noexcept
label nFieldCells () const noexcept
label nFieldPoints () const noexcept
void setNumPoints (label n) noexcept
void setNumAddPoints (label n) noexcept
label sizeOf (const enum contentType output, const enum slotType slot) const
label sizeLegacy () const
label sizeLegacy (const enum slotType slot) const
label sizeXml (const enum slotType slot) const
label sizeInternal1 (const enum slotType slot) const
label sizeInternal2 (const enum slotType slot) const
void populateLegacy (const polyMesh &mesh, UList< uint8_t > &cellTypes, labelUList &connectivity, foamVtkMeshMaps &maps) const
void populateXml (const polyMesh &mesh, UList< uint8_t > &cellTypes, labelUList &connectivity, labelUList &offsets, labelUList &faces, labelUList &facesOffsets, foamVtkMeshMaps &maps) const
void populateInternal (const polyMesh &mesh, UList< uint8_t > &cellTypes, UList< int > &connectivity, UList< int > &offsets, UList< int > &faces, UList< int > &facesOffsets, foamVtkMeshMaps &maps, const enum contentType output) const
Populate lists for Internal VTK format.
void populateInternal (const polyMesh &mesh, UList< uint8_t > &cellTypes, UList< int > &connectivity, UList< int > &offsets, UList< int > &faces, UList< int > &facesOffsets, labelUList &cellMap, labelUList &addPointsIds, const enum contentType output) const
Populate lists for Internal VTK format.
void populateInternal (const polyMesh &mesh, UList< uint8_t > &cellTypes, UList< long > &connectivity, UList< long > &offsets, UList< long > &faces, UList< long > &facesOffsets, foamVtkMeshMaps &maps, const enum contentType output) const
Populate lists for Internal VTK format.
void populateInternal (const polyMesh &mesh, UList< uint8_t > &cellTypes, UList< long > &connectivity, UList< long > &offsets, UList< long > &faces, UList< long > &facesOffsets, labelUList &cellMap, labelUList &addPointsIds, const enum contentType output) const
Populate lists for Internal VTK format.
void populateInternal (const polyMesh &mesh, UList< uint8_t > &cellTypes, UList< long long > &connectivity, UList< long long > &offsets, UList< long long > &faces, UList< long long > &facesOffsets, foamVtkMeshMaps &maps, const enum contentType output) const
Populate lists for Internal VTK format.
void populateInternal (const polyMesh &mesh, UList< uint8_t > &cellTypes, UList< long long > &connectivity, UList< long long > &offsets, UList< long long > &faces, UList< long long > &facesOffsets, labelUList &cellMap, labelUList &addPointsIds, const enum contentType output) const
Populate lists for Internal VTK format.
void info (Ostream &os) const
bool operator== (const vtuSizing &rhs) const
bool operator!= (const vtuSizing &rhs) const
Static Public Member Functions
static labelList copyVertLabelsLegacy (const labelUList &connectivity, const label globalPointOffset)
static labelList copyVertLabelsXml (const labelUList &connectivity, const label globalPointOffset)
static labelList copyFaceLabelsXml (const labelUList &faceLabels, const label globalPointOffset)
static labelList copyFaceOffsetsXml (const labelUList &faceOffsets, const label prevOffset)
static void renumberVertLabelsLegacy (labelUList &connectivity, const label globalPointOffset)
static void renumberVertLabelsXml (labelUList &connectivity, const label globalPointOffset)
static void renumberFaceLabelsXml (labelUList &faceLabels, const label globalPointOffset)
static void renumberFaceOffsetsXml (labelUList &faceOffsets, const label prevOffset)
Protected Member Functions
void populateShapesLegacy (const UList< cellShape > &shapes, UList< uint8_t > &cellTypes, labelUList &connectivity, foamVtkMeshMaps &maps) const
void populateShapesXml (const UList< cellShape > &shapes, UList< uint8_t > &cellTypes, labelUList &connectivity, labelUList &offsets, labelUList &faces, labelUList &facesOffsets, foamVtkMeshMaps &maps) const
Detailed Description
Sizing descriptions and routines for transcribing an OpenFOAM volume mesh into a VTK unstructured grid, with possible decomposition of polyhedral cells into primitive cell types.
This class is intended to populate externally allocated arrays with content that is compatible with what VTK expects. This approach allows an improved separation of the OpenFOAM mesh description and the storage, and allows support of alternative storage containers (eg, std::vector, vtkDataArray). The ideal goal would be a zero-copy mechanism, but this does not work for several reasons:
OpenFOAM and VTK have different point ordering for prism
polyhedral decomposition
face-stream are required for VTK
VTK internal storage includes list size as part of the data
VTK includes storage may be a different base size (eg, long long) compared to the OpenFOAM label.
Data Entries (slots)
These are the storage entries normally associate with each output-type:
legacy output (vtk DataFile Version 2.0)
types vtk cell type (1-255)
cells nLabels and unique vertex labels used by the cell, or
[nLabels nFaces, nFace0Pts, id1, id2, ..., nFace1Pts, id1, id2, ...]
xml output
types vtk cell type (1-255)
connectivity unique vertex labels used by the cell
offsets end offset for each of connectivity
faces face stream for polyhedral cells
[nFaces, nFace0Pts, id1, id2, ..., nFace1Pts, id1, id2, ...]
faceoffsets end offset for each of faces, with -1 for primitive cells
internal1 storage (VTK-8 and earlier)
types vtk cell type (1-255)
connectivity nLabels and unique vertex labels used by the cell
location begin location for each of connectivity
faces face stream for polyhedral cells
[nFaces, nFace0Pts, id1, id2, ..., nFace1Pts, id1, id2, ...]
facelocation begin location for each of faces, with -1 for primitive cells
internal2 storage (with VTK_CELL_ARRAY_V2)
types vtk cell type (1-255)
connectivity unique vertex labels used by the cell
offsets begin/end offsets for connectivity
faces face stream for polyhedral cells
[nFaces, nFace0Pts, id1, id2, ..., nFace1Pts, id1, id2, ...]
facelocation begin location for each of faces, with -1 for primitive cells
The VTK storage concept for "connectivity" and "faces" somewhat resemble a CompactListList.
Note
It is possible to specify a global point offset (via the globalIndex) so that the cell point labels will use global numbering. There is no support for point renumbering with merged mesh points, since it likely more efficient to use VTK point-blanking to mark duplicate points instead of merging points ourselves.
The VTK_CELL_ARRAY_V2 define (from vtkCellArray.h) indicates if the new (internal2) new format is being used.
Source files
foamVtuSizing.H
foamVtuSizing.C
foamVtuSizingI.H
Definition at line 197 of file foamVtuSizing.H.
Member Enumeration Documentation
contentType
enum contentType : char
Enumerator
LEGACY
Legacy VTK content.
XML
XML (VTU) content.
INTERNAL1
Internal vtkUnstructuredGrid content.
INTERNAL2
Internal vtkUnstructuredGrid content, VTK_CELL_ARRAY_V2.
Definition at line 204 of file foamVtuSizing.H.
slotType
enum slotType : char
Enumerator
CELLS
Cell connectivity (ALL)
CELLS_OFFSETS
Cell end-offsets (XML), locations (INTERNAL1) or begin/end offsets (INTERNAL2)
FACES
Face-stream (XML, INTERNAL)
FACES_OFFSETS
Faces end-offsets (XML) or locations (INTERNAL1)
Definition at line 213 of file foamVtuSizing.H.
selectionModeType
enum selectionModeType : char
Enumerator
FULL_MESH
SUBSET_MESH
SHAPE_MESH
Definition at line 223 of file foamVtuSizing.H.
Constructor & Destructor Documentation
vtuSizing() [1/3]
vtuSizing () noexcept
Definition at line 197 of file foamVtuSizing.C.
References clear().
vtuSizing() [2/3]
vtuSizing (const polyMesh & mesh) explicit
vtuSizing() [3/3]
vtuSizing (const polyMesh & mesh, const bool decompose)
Definition at line 203 of file foamVtuSizing.C.
References clear(), and mesh.
Member Function Documentation
populateShapesLegacy()
void populateShapesLegacy (const UList< cellShape > & shapes, UList< uint8_t > & cellTypes, labelUList & connectivity, foamVtkMeshMaps & maps) const protected
Definition at line 609 of file foamVtuSizing.C.
References cellTypes.
populateShapesXml()
void populateShapesXml (const UList< cellShape > & shapes, UList< uint8_t > & cellTypes, labelUList & connectivity, labelUList & offsets, labelUList & faces, labelUList & facesOffsets, foamVtkMeshMaps & maps) const protected
Definition at line 667 of file foamVtuSizing.C.
References cellTypes.
reset() [1/2]
void reset (const polyMesh & mesh, const bool decompose = false)
Definition at line 235 of file foamVtuSizing.C.
References mesh, and UList< label >::null().
Referenced by vtuCells::reset(), and vtuCells::reset().
reset() [2/2]
void reset (const polyMesh & mesh, const labelUList & subsetCellsIds, const bool decompose = false)
const cellList& meshCells = mesh.cells();
Definition at line 245 of file foamVtuSizing.C.
References PtrList< T >::clear(), f(), Foam::hex(), cellModel::HEX, mesh, MeshObject< polyMesh, UpdateableMeshObject, manifoldCellsMeshObject >::New(), Foam::notNull(), cellModel::PRISM, cellModel::PYR, cellModel::ref(), UPtrList< T >::size(), UList< T >::size(), cellModel::TET, cellModel::TETWEDGE, and cellModel::WEDGE.
resetShapes()
void resetShapes (const UList< cellShape > & shapes)
Definition at line 404 of file foamVtuSizing.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::hex(), cellModel::HEX, Foam::max(), cellShape::model(), Foam::nl, cellModel::PRISM, cellModel::PYR, cellModel::ref(), UPtrList< T >::size(), UList< T >::size(), and cellModel::TET.
Referenced by vtuCells::resetShapes().
clear()
void clear () noexcept
Definition at line 216 of file foamVtuSizing.C.
Referenced by vtuCells::clear().
decompose()
bool decompose () const inline noexcept
Definition at line 25 of file foamVtuSizingI.H.
Referenced by vtuSizing::operator==().
manifold()
bool manifold () const inline noexcept
Definition at line 31 of file foamVtuSizingI.H.
selectionMode()
Foam::vtk::vtuSizing::selectionModeType selectionMode () const inline noexcept
Definition at line 38 of file foamVtuSizingI.H.
nCells()
Foam::label nCells () const inline noexcept
Definition at line 44 of file foamVtuSizingI.H.
Referenced by vtuSizing::operator==(), and vtuCells::resetShapes().
nPoints()
Foam::label nPoints () const inline noexcept
Definition at line 50 of file foamVtuSizingI.H.
Referenced by vtuSizing::operator==().
nVertLabels()
Foam::label nVertLabels () const inline noexcept
Definition at line 56 of file foamVtuSizingI.H.
Referenced by vtuSizing::operator==().
nFaceLabels()
Foam::label nFaceLabels () const inline noexcept
Definition at line 62 of file foamVtuSizingI.H.
Referenced by vtuSizing::operator==().
nCellsPoly()
Foam::label nCellsPoly () const inline noexcept
Definition at line 68 of file foamVtuSizingI.H.
Referenced by vtuSizing::operator==().
nVertPoly()
Foam::label nVertPoly () const inline noexcept
Definition at line 74 of file foamVtuSizingI.H.
Referenced by vtuSizing::operator==().
nAddCells()
Foam::label nAddCells () const inline noexcept
Definition at line 80 of file foamVtuSizingI.H.
Referenced by vtuSizing::operator==().
nAddPoints()
Foam::label nAddPoints () const inline noexcept
Definition at line 86 of file foamVtuSizingI.H.
Referenced by vtuSizing::operator==().
nAddVerts()
Foam::label nAddVerts () const inline noexcept
Definition at line 92 of file foamVtuSizingI.H.
Referenced by vtuSizing::operator==().
nFieldCells()
Foam::label nFieldCells () const inline noexcept
Definition at line 98 of file foamVtuSizingI.H.
Referenced by vtuAdaptor::internal().
nFieldPoints()
Foam::label nFieldPoints () const inline noexcept
Definition at line 104 of file foamVtuSizingI.H.
Referenced by isoSurfaceTopo::isoSurfaceTopo().
setNumPoints()
void setNumPoints (label n) inline noexcept
Definition at line 460 of file foamVtuSizing.H.
References n.
Referenced by isoSurfaceTopo::isoSurfaceTopo().
setNumAddPoints()
void setNumAddPoints (label n) inline noexcept
Definition at line 463 of file foamVtuSizing.H.
References n.
sizeOf()
Foam::label sizeOf (const enum contentType output, const enum slotType slot) const
Definition at line 473 of file foamVtuSizing.C.
References nFaceLabels, and Foam::output().
Referenced by vtuAdaptor::internal().
sizeLegacy() [1/2]
Foam::label sizeLegacy () const inline
Definition at line 110 of file foamVtuSizingI.H.
sizeLegacy() [2/2]
Foam::label sizeLegacy (const enum slotType slot) const inline
Definition at line 116 of file foamVtuSizingI.H.
sizeXml()
Foam::label sizeXml (const enum slotType slot) const inline
Definition at line 125 of file foamVtuSizingI.H.
sizeInternal1()
Foam::label sizeInternal1 (const enum slotType slot) const inline
Definition at line 134 of file foamVtuSizingI.H.
sizeInternal2()
Foam::label sizeInternal2 (const enum slotType slot) const inline
Definition at line 143 of file foamVtuSizingI.H.
populateLegacy()
void populateLegacy (const polyMesh & mesh, UList< uint8_t > & cellTypes, labelUList & connectivity, foamVtkMeshMaps & maps) const
Definition at line 580 of file foamVtuSizing.C.
References cellTypes, and mesh.
populateXml()
void populateXml (const polyMesh & mesh, UList< uint8_t > & cellTypes, labelUList & connectivity, labelUList & offsets, labelUList & faces, labelUList & facesOffsets, foamVtkMeshMaps & maps) const
Definition at line 638 of file foamVtuSizing.C.
References cellTypes, and mesh.
populateInternal() [1/6]
void populateInternal (const polyMesh & mesh, UList< uint8_t > & cellTypes, UList< int > & connectivity, UList< int > & offsets, UList< int > & faces, UList< int > & facesOffsets, foamVtkMeshMaps & maps, const enum contentType output) const
Populate lists for Internal VTK format.
Definition at line 760 of file foamVtuSizing.C.
Referenced by vtuAdaptor::internal().
populateInternal() [2/6]
void populateInternal (const polyMesh & mesh, UList< uint8_t > & cellTypes, UList< int > & connectivity, UList< int > & offsets, UList< int > & faces, UList< int > & facesOffsets, labelUList & cellMap, labelUList & addPointsIds, const enum contentType output) const
Populate lists for Internal VTK format.
Definition at line 760 of file foamVtuSizing.C.
populateInternal() [3/6]
void populateInternal (const polyMesh & mesh, UList< uint8_t > & cellTypes, UList< long > & connectivity, UList< long > & offsets, UList< long > & faces, UList< long > & facesOffsets, foamVtkMeshMaps & maps, const enum contentType output) const
Populate lists for Internal VTK format.
Definition at line 761 of file foamVtuSizing.C.
populateInternal() [4/6]
void populateInternal (const polyMesh & mesh, UList< uint8_t > & cellTypes, UList< long > & connectivity, UList< long > & offsets, UList< long > & faces, UList< long > & facesOffsets, labelUList & cellMap, labelUList & addPointsIds, const enum contentType output) const
Populate lists for Internal VTK format.
Definition at line 761 of file foamVtuSizing.C.
populateInternal() [5/6]
void populateInternal (const polyMesh & mesh, UList< uint8_t > & cellTypes, UList< long long > & connectivity, UList< long long > & offsets, UList< long long > & faces, UList< long long > & facesOffsets, foamVtkMeshMaps & maps, const enum contentType output) const
Populate lists for Internal VTK format.
Definition at line 762 of file foamVtuSizing.C.
populateInternal() [6/6]
void populateInternal (const polyMesh & mesh, UList< uint8_t > & cellTypes, UList< long long > & connectivity, UList< long long > & offsets, UList< long long > & faces, UList< long long > & facesOffsets, labelUList & cellMap, labelUList & addPointsIds, const enum contentType output) const
Populate lists for Internal VTK format.
Definition at line 762 of file foamVtuSizing.C.
copyVertLabelsLegacy()
Foam::labelList copyVertLabelsLegacy (const labelUList & connectivity, const label globalPointOffset) static
Definition at line 770 of file foamVtuSizing.C.
References Foam::output().
copyVertLabelsXml()
Foam::labelList copyVertLabelsXml (const labelUList & connectivity, const label globalPointOffset) static
Definition at line 853 of file foamVtuSizing.C.
References Foam::output().
copyFaceLabelsXml()
Foam::labelList copyFaceLabelsXml (const labelUList & faceLabels, const label globalPointOffset) static
Definition at line 892 of file foamVtuSizing.C.
References faceLabels(), and Foam::output().
copyFaceOffsetsXml()
Foam::labelList copyFaceOffsetsXml (const labelUList & faceOffsets, const label prevOffset) static
Definition at line 947 of file foamVtuSizing.C.
References Foam::output().
renumberVertLabelsLegacy()
void renumberVertLabelsLegacy (labelUList & connectivity, const label globalPointOffset) static
Definition at line 788 of file foamVtuSizing.C.
References UList< T >::begin(), and UList< T >::end().
renumberVertLabelsXml()
void renumberVertLabelsXml (labelUList & connectivity, const label globalPointOffset) static
Definition at line 871 of file foamVtuSizing.C.
renumberFaceLabelsXml()
void renumberFaceLabelsXml (labelUList & faceLabels, const label globalPointOffset) static
Definition at line 910 of file foamVtuSizing.C.
References UPtrList< T >::begin(), and faceLabels().
renumberFaceOffsetsXml()
void renumberFaceOffsetsXml (labelUList & faceOffsets, const label prevOffset) static
Definition at line 965 of file foamVtuSizing.C.
info()
void info (Ostream & os) const
Definition at line 991 of file foamVtuSizing.C.
References os().
operator==()
bool operator== (const vtuSizing & rhs) const
Definition at line 1026 of file foamVtuSizing.C.
References vtuSizing::decompose(), vtuSizing::nAddCells(), vtuSizing::nAddPoints(), vtuSizing::nAddVerts(), vtuSizing::nCells(), vtuSizing::nCellsPoly(), nFaceLabels, vtuSizing::nFaceLabels(), nPoints, vtuSizing::nPoints(), vtuSizing::nVertLabels(), and vtuSizing::nVertPoly().
operator!=()
bool operator!= (const vtuSizing & rhs) const
Definition at line 1045 of file foamVtuSizing.C.
References Foam::operator==().
The documentation for this class was generated from the following files:
src/fileFormats/vtk/part/foamVtuSizing.H
src/fileFormats/vtk/part/foamVtuSizing.C
src/fileFormats/vtk/part/foamVtuSizingI.H
src/fileFormats/vtk/part/foamVtuSizingImpl.C