OpenFOAM: adjointEikonalSolver Class Reference
adjointEikonalSolver Class Reference
Solver of the adjoint to the eikonal PDE.
#include <adjointEikonalSolverIncompressible.H>
Public Member Functions
TypeName ("adjointEikonalSolver")
adjointEikonalSolver (const fvMesh &mesh, const dictionary &dict, const autoPtr< incompressible::RASModelVariables > &RASModelVars, incompressibleAdjointVars &adjointVars, const labelHashSet &sensitivityPatchIDs)
virtual ~adjointEikonalSolver ()=default
virtual bool readDict (const dictionary &dict)
void accumulateIntegrand (const scalar dt)
void solve ()
void reset ()
boundaryVectorField & distanceSensitivities ()
tmp< volTensorField > getFISensitivityTerm () const
const volScalarField & da ()
const volScalarField & d ()
tmp< volVectorField > gradEikonal ()
Protected Member Functions
wordList patchTypes () const
tmp< surfaceScalarField > computeYPhi ()
void read ()
Protected Attributes
const fvMesh & mesh_
dictionary dict_
const autoPtr< incompressible::RASModelVariables > & RASModelVars_
autoPtr< Foam::incompressibleAdjoint::adjointRASModel > & adjointTurbulence_
const labelHashSet & sensitivityPatchIDs_
label nEikonalIters_
scalar tolerance_
scalar epsilon_
labelHashSet wallPatchIDs_
volScalarField da_
volScalarField source_
autoPtr< boundaryVectorField > distanceSensPtr_
Detailed Description
Solver of the adjoint to the eikonal PDE.
Reference:
    For the development of the adjoint eikonal PDE and its boundary
    conditions
        Papoutsis-Kiachagias, E. M., & Giannakoglou, K. C. (2014).
        Continuous Adjoint Methods for Turbulent Flows, Applied to Shape
        and Topology Optimization: Industrial Applications.
        Archives of Computational Methods in Engineering, 23(2), 255-299.
        http://doi.org/10.1007/s11831-014-9141-9
To be as consistent as possible, it is recommended to use the advectionDiffusion wallDist method in fvSchemes, instead of the more widely used meshWave
Example of the adjointEikonalSolver specification in optimisationDict:
    optimisation
    {
        sensitivities
        {
            includeDistance true;
            adjointEikonalSolver
            {
                // epsilon should be the same as the one used
                // in fvSchemes/wallDist/advectionDiffusionCoeffs
                epsilon   0.1;
                iters     1000;
                tolerance 1e-6;
            }
        }
    }
Example of the entries in fvSchemes:
    divSchemes
    {
        .
        .
        // avoid bounded schemes since yPhi is not conservative
        div(-yPhi,da) Gauss linearUpwind grad(da);
        .
        .
    }
    laplacianSchemes
    {
        .
        .
        laplacian(yWall,da) Gauss linear corrected;
        .
        .
    }
Also, the solver specification and a relaxation factor for da are required in fvSolution
    da
    {
        solver          PBiCGStab;
        preconditioner  DILU;
        tolerance       1e-9;
        relTol          0.1;
    }
    relaxationFactors
    {
        equations
        {
            .
            .
            da           0.5;
            .
            .
        }
    }
See also
Foam::patchDistMethod::advectionDiffusion Foam::wallDist
Source files
adjointEikonalSolverIncompressible.H
adjointEikonalSolver.C
Definition at line 142 of file adjointEikonalSolverIncompressible.H.
Constructor & Destructor Documentation
adjointEikonalSolver()
adjointEikonalSolver (const fvMesh & mesh, const dictionary & dict, const autoPtr< incompressible::RASModelVariables > & RASModelVars, incompressibleAdjointVars & adjointVars, const labelHashSet & sensitivityPatchIDs)
Definition at line 110 of file adjointEikonalSolverIncompressible.C.
References adjointEikonalSolver::read().
~adjointEikonalSolver()
virtual ~adjointEikonalSolver () virtual default
Member Function Documentation
patchTypes()
wordList patchTypes () const protected
Definition at line 41 of file adjointEikonalSolverIncompressible.C.
References adjointEikonalSolver::mesh_, UPtrList< T >::size(), adjointEikonalSolver::wallPatchIDs_, and fvPatchFieldBase::zeroGradientType().
computeYPhi()
tmp< surfaceScalarField > computeYPhi () protected
Definition at line 71 of file adjointEikonalSolverIncompressible.C.
References adjointEikonalSolver::d(), Foam::dimless, Foam::fvc::grad(), Foam::fvc::interpolate(), adjointEikonalSolver::mesh_, tmp< T >::New(), IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, patches, adjointEikonalSolver::RASModelVars_, adjointEikonalSolver::wallPatchIDs_, and Foam::Zero.
Referenced by adjointEikonalSolver::solve().
read()
void read () protected
Definition at line 58 of file adjointEikonalSolverIncompressible.C.
References adjointEikonalSolver::dict_, e, adjointEikonalSolver::epsilon_, dictionary::getOrDefault(), adjointEikonalSolver::mesh_, adjointEikonalSolver::nEikonalIters_, and adjointEikonalSolver::tolerance_.
Referenced by adjointEikonalSolver::adjointEikonalSolver(), and adjointEikonalSolver::solve().
TypeName()
TypeName ("adjointEikonalSolver")
readDict()
bool readDict (const dictionary & dict) virtual
Definition at line 168 of file adjointEikonalSolverIncompressible.C.
References dict, adjointEikonalSolver::dict_, and dictionary::subOrEmptyDict().
accumulateIntegrand()
void accumulateIntegrand (const scalar dt)
Definition at line 176 of file adjointEikonalSolverIncompressible.C.
References adjointEikonalSolver::adjointTurbulence_, and adjointEikonalSolver::source_.
solve()
void solve ()
Definition at line 183 of file adjointEikonalSolverIncompressible.C.
References adjointEikonalSolver::computeYPhi(), adjointEikonalSolver::d(), adjointEikonalSolver::da_, Foam::fvm::div(), Foam::endl(), adjointEikonalSolver::epsilon_, Foam::gMax(), Foam::Info, Foam::fvc::laplacian(), Foam::fvm::laplacian(), Foam::mag(), adjointEikonalSolver::mesh_, adjointEikonalSolver::nEikonalIters_, adjointEikonalSolver::RASModelVars_, adjointEikonalSolver::read(), adjointEikonalSolver::source_, Foam::fvm::SuSp(), adjointEikonalSolver::tolerance_, and regIOobject::write().
reset()
void reset ()
Definition at line 230 of file adjointEikonalSolverIncompressible.C.
References DimensionedField< Type, GeoMesh >::dimensions(), adjointEikonalSolver::distanceSensPtr_, adjointEikonalSolver::source_, Foam::Zero, and VectorSpace< Form, Cmpt, Ncmpts >::zero.
distanceSensitivities()
boundaryVectorField & distanceSensitivities ()
Definition at line 237 of file adjointEikonalSolverIncompressible.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), adjointEikonalSolver::d(), adjointEikonalSolver::da_, adjointEikonalSolver::distanceSensPtr_, Foam::endl(), Foam::Info, adjointEikonalSolver::mesh_, adjointEikonalSolver::RASModelVars_, and adjointEikonalSolver::sensitivityPatchIDs_.
getFISensitivityTerm()
tmp< volTensorField > getFISensitivityTerm () const
Definition at line 258 of file adjointEikonalSolverIncompressible.C.
References IOobjectOption::AUTO_WRITE, adjointEikonalSolver::d(), adjointEikonalSolver::da_, DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimLength, Foam::endl(), adjointEikonalSolver::epsilon_, Foam::fvc::grad(), Foam::Info, adjointEikonalSolver::mesh_, IOobjectOption::NO_READ, adjointEikonalSolver::RASModelVars_, adjointEikonalSolver::wallPatchIDs_, and Foam::Zero.
da()
const volScalarField & da ()
Definition at line 308 of file adjointEikonalSolverIncompressible.C.
References adjointEikonalSolver::da_.
d()
const volScalarField & d ()
Referenced by adjointEikonalSolver::computeYPhi(), adjointEikonalSolver::distanceSensitivities(), adjointEikonalSolver::getFISensitivityTerm(), adjointEikonalSolver::gradEikonal(), and adjointEikonalSolver::solve().
gradEikonal()
tmp< volVectorField > gradEikonal ()
Definition at line 314 of file adjointEikonalSolverIncompressible.C.
References adjointEikonalSolver::d(), Foam::fvc::grad(), tmp< T >::New(), and adjointEikonalSolver::RASModelVars_.
Member Data Documentation
mesh_
const fvMesh& mesh_ protected
Definition at line 159 of file adjointEikonalSolverIncompressible.H.
Referenced by adjointEikonalSolver::computeYPhi(), adjointEikonalSolver::distanceSensitivities(), adjointEikonalSolver::getFISensitivityTerm(), adjointEikonalSolver::patchTypes(), adjointEikonalSolver::read(), and adjointEikonalSolver::solve().
dict_
dictionary dict_ protected
Definition at line 161 of file adjointEikonalSolverIncompressible.H.
Referenced by adjointEikonalSolver::read(), and adjointEikonalSolver::readDict().
RASModelVars_
const autoPtr<incompressible::RASModelVariables>& RASModelVars_ protected
Definition at line 163 of file adjointEikonalSolverIncompressible.H.
Referenced by adjointEikonalSolver::computeYPhi(), adjointEikonalSolver::distanceSensitivities(), adjointEikonalSolver::getFISensitivityTerm(), adjointEikonalSolver::gradEikonal(), and adjointEikonalSolver::solve().
adjointTurbulence_
autoPtr<Foam::incompressibleAdjoint::adjointRASModel>& adjointTurbulence_ protected
Definition at line 166 of file adjointEikonalSolverIncompressible.H.
Referenced by adjointEikonalSolver::accumulateIntegrand().
sensitivityPatchIDs_
const labelHashSet& sensitivityPatchIDs_ protected
Definition at line 168 of file adjointEikonalSolverIncompressible.H.
Referenced by adjointEikonalSolver::distanceSensitivities().
nEikonalIters_
label nEikonalIters_ protected
Definition at line 170 of file adjointEikonalSolverIncompressible.H.
Referenced by adjointEikonalSolver::read(), and adjointEikonalSolver::solve().
tolerance_
scalar tolerance_ protected
Definition at line 172 of file adjointEikonalSolverIncompressible.H.
Referenced by adjointEikonalSolver::read(), and adjointEikonalSolver::solve().
epsilon_
scalar epsilon_ protected
Definition at line 174 of file adjointEikonalSolverIncompressible.H.
Referenced by adjointEikonalSolver::getFISensitivityTerm(), adjointEikonalSolver::read(), and adjointEikonalSolver::solve().
wallPatchIDs_
labelHashSet wallPatchIDs_ protected
Definition at line 176 of file adjointEikonalSolverIncompressible.H.
Referenced by adjointEikonalSolver::computeYPhi(), adjointEikonalSolver::getFISensitivityTerm(), and adjointEikonalSolver::patchTypes().
da_
volScalarField da_ protected
Definition at line 178 of file adjointEikonalSolverIncompressible.H.
Referenced by adjointEikonalSolver::da(), adjointEikonalSolver::distanceSensitivities(), adjointEikonalSolver::getFISensitivityTerm(), and adjointEikonalSolver::solve().
source_
volScalarField source_ protected
Definition at line 180 of file adjointEikonalSolverIncompressible.H.
Referenced by adjointEikonalSolver::accumulateIntegrand(), adjointEikonalSolver::reset(), and adjointEikonalSolver::solve().
distanceSensPtr_
autoPtr<boundaryVectorField> distanceSensPtr_ protected
Definition at line 183 of file adjointEikonalSolverIncompressible.H.
Referenced by adjointEikonalSolver::distanceSensitivities(), and adjointEikonalSolver::reset().
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/optimisation/adjointSensitivity/incompressible/adjointEikonalSolver/adjointEikonalSolverIncompressible.H
src/optimisation/adjointOptimisation/adjoint/optimisation/adjointSensitivity/incompressible/adjointEikonalSolver/adjointEikonalSolverIncompressible.C