OpenFOAM: LIFOStack< T > Class Template Reference
LIFOStack< T > Class Template Reference
A LIFO stack based on a singly-linked list.
#include <LIFOStack.H>
Public Member Functions
const T & top () const
const T & bottom () const
void push (const T &elem)
void push (T &&elem)
T pop ()
Public Member Functions inherited from LList< LListBase, T >
LList ()=default
LList (const T &elem)
LList (T &&elem)
LList (Istream &is)
LList (const LList< LListBase, T > &lst)
LList (LList< LListBase, T > &&lst)
LList (std::initializer_list< T > lst)
~LList ()
reference front ()
const_reference front () const
reference back ()
const_reference back () const
void push_front (const T &elem)
void push_front (T &&elem)
void push_back (const T &elem)
void push_back (T &&elem)
void clear ()
void pop_front (label n=1)
T removeHead ()
T remove (link *item)
T remove (iterator &iter)
void transfer (LList< LListBase, T > &lst)
void operator= (const LList< LListBase, T > &lst)
void operator= (LList< LListBase, T > &&lst)
void operator= (std::initializer_list< T > lst)
Istream & readList (Istream &is)
Ostream & writeList (Ostream &os, const label shortLen=0) const
iterator begin ()
const_iterator cbegin () const
reverse_iterator rbegin ()
const_reverse_iterator crbegin () const
const_iterator begin () const
const_reverse_iterator rbegin () const
const iterator & end ()
const const_iterator & cend () const
const reverse_iterator & rend ()
const const_reverse_iterator & crend () const
const const_iterator & end () const
const const_reverse_iterator & rend () const
reference first ()
const_reference first () const
reference last ()
const_reference last () const
void prepend (const T &elem)
void prepend (T &&elem)
void append (const T &elem)
void append (T &&elem)
void insert (const T &elem)
void insert (T &&elem)
Additional Inherited Members
Public Types inherited from LList< LListBase, T >
typedef T value_type
typedef T * pointer
typedef const T * const_pointer
typedef T & reference
typedef const T & const_reference
typedef label size_type
typedef label difference_type
using base_iterator = typename LListBase::iterator
using const_base_iterator = typename LListBase::const_iterator
Detailed Description
template<class T>
class Foam::LIFOStack< T >
A LIFO stack based on a singly-linked list.
Stack operations are push(), pop(), top(), bottom().
Definition at line 45 of file LIFOStack.H.
Member Function Documentation
top()
template<class T > const T & top () const inline
Definition at line 60 of file LIFOStack.H.
References LList< LListBase, T >::front().
bottom()
template<class T > const T & bottom () const inline
Definition at line 66 of file LIFOStack.H.
References LList< LListBase, T >::back().
push() [1/2]
template<class T > void push (const T & elem) inline
Definition at line 72 of file LIFOStack.H.
References LList< LListBase, T >::push_front().
push() [2/2]
template<class T > void push (T && elem) inline
Definition at line 78 of file LIFOStack.H.
References LList< LListBase, T >::push_front().
pop()
template<class T > T pop () inline
Definition at line 84 of file LIFOStack.H.
References LList< LListBase, T >::removeHead().
The documentation for this class was generated from the following file:
src/OpenFOAM/containers/LinkedLists/user/LIFOStack.H