OpenFOAM: forceSuSp Class Reference
forceSuSp Class Reference
Helper container for force Su and Sp terms.
#include <forceSuSp.H>
Public Member Functions
forceSuSp ()=default
forceSuSp (const Foam::zero)
forceSuSp (const Tuple2< vector, scalar > &susp)
forceSuSp (const vector &Su, const scalar Sp)
forceSuSp (Istream &is)
const vector & Su () const
scalar Sp () const
vector & Su ()
scalar & Sp ()
void operator+= (const forceSuSp &susp)
void operator-= (const forceSuSp &susp)
Public Member Functions inherited from Tuple2< vector, scalar >
Tuple2 ()=default
Tuple2 (const vector &f, const scalar &s)
Tuple2 (vector &&f, scalar &&s)
Tuple2 (const std::pair< vector, scalar > &vals)
Tuple2 (std::pair< vector, scalar > &&vals)
Tuple2 (Istream &is)
const vector & first () const noexcept
vector & first () noexcept
const scalar & second () const noexcept
scalar & second () noexcept
Friends
forceSuSp operator* (const forceSuSp &susp1, const forceSuSp &susp2)
forceSuSp operator* (const scalar s, const forceSuSp &susp)
Additional Inherited Members
Public Types inherited from Tuple2< vector, scalar >
typedef vector first_type
typedef scalar second_type
Detailed Description
Helper container for force Su and Sp terms.
F = Sp(U - Up) + Su
Explicit contribution, Su specified as a force Implicit coefficient, Sp specified as force/velocity
Source files
forceSuSp.H
forceSuSpI.H
Definition at line 60 of file forceSuSp.H.
Constructor & Destructor Documentation
forceSuSp() [1/5]
forceSuSp () default
forceSuSp() [2/5]
forceSuSp (const Foam::zero) inline
Definition at line 24 of file forceSuSpI.H.
forceSuSp() [3/5]
forceSuSp (const Tuple2< vector, scalar > & susp) inline
Definition at line 30 of file forceSuSpI.H.
forceSuSp() [4/5]
forceSuSp (const vector & Su, const scalar Sp) inline
Definition at line 39 of file forceSuSpI.H.
References Sp, and Su.
forceSuSp() [5/5]
forceSuSp (Istream & is) inline explicit
Definition at line 46 of file forceSuSpI.H.
Member Function Documentation
Su() [1/2]
const Foam::vector & Su () const inline
Definition at line 54 of file forceSuSpI.H.
Referenced by LiftForce< CloudType >::calcCoupled(), ParticleForce< CloudType >::calcCoupled(), PressureGradientForce< CloudType >::calcCoupled(), VirtualMassForce< CloudType >::calcCoupled(), BrownianMotionForce< CloudType >::calcCoupled(), GravityForce< CloudType >::calcNonCoupled(), InterfaceForce< CloudType >::calcNonCoupled(), NonInertialFrameForce< CloudType >::calcNonCoupled(), ParamagneticForce< CloudType >::calcNonCoupled(), SRFForce< CloudType >::calcNonCoupled(), and ParticleForce< KinematicCloud< Foam::DSMCCloud > >::ParticleForce().
Sp() [1/2]
Foam::scalar Sp () const inline
Definition at line 60 of file forceSuSpI.H.
Referenced by ParticleForce< CloudType >::calcCoupled(), and ParticleForce< KinematicCloud< Foam::DSMCCloud > >::ParticleForce().
Su() [2/2]
Foam::vector & Su () inline
Definition at line 66 of file forceSuSpI.H.
Sp() [2/2]
Foam::scalar & Sp () inline
Definition at line 72 of file forceSuSpI.H.
operator+=()
void operator+= (const forceSuSp & susp) inline
Definition at line 80 of file forceSuSpI.H.
References UPtrList< T >::first().
operator-=()
void operator-= (const forceSuSp & susp) inline
Definition at line 87 of file forceSuSpI.H.
References UPtrList< T >::first().
Friends And Related Symbol Documentation
operator* [1/2]
forceSuSp operator* (const forceSuSp & susp1, const forceSuSp & susp2) friend
operator* [2/2]
forceSuSp operator* (const scalar s, const forceSuSp & susp) friend
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/Kinematic/ParticleForces/forceSuSp/forceSuSp.H
src/lagrangian/intermediate/submodels/Kinematic/ParticleForces/forceSuSp/forceSuSpI.H