OpenFOAM: clockValue Class Reference
clockValue Class Reference
Access to high-resolution clock value with some basic operations. Used to calculate time durations, elapsed times etc.
#include <clockValue.H>
Public Types
typedef std::chrono::high_resolution_clock::duration value_type
Public Member Functions
clockValue ()
clockValue (bool)
clockValue (const value_type &value)
const value_type & value () const
void clear ()
void update ()
long seconds () const
clockValue elapsed () const
double elapsedTime () const
std::string str () const
operator double () const
clockValue & operator-= (const clockValue &rhs)
clockValue & operator+= (const clockValue &rhs)
Static Public Member Functions
static clockValue now ()
Detailed Description
Access to high-resolution clock value with some basic operations. Used to calculate time durations, elapsed times etc.
Source files
clockValue.H
clockValueI.H
clockValue.C
Definition at line 49 of file clockValue.H.
Member Typedef Documentation
value_type
typedef std::chrono::high_resolution_clock::duration value_type
Definition at line 56 of file clockValue.H.
Constructor & Destructor Documentation
clockValue() [1/3]
clockValue () inline
Definition at line 31 of file clockValueI.H.
Referenced by clockValue::now().
clockValue() [2/3]
clockValue (bool) inline explicit
Definition at line 37 of file clockValueI.H.
clockValue() [3/3]
clockValue (const value_type & value) inline explicit
Definition at line 43 of file clockValueI.H.
Member Function Documentation
now()
Foam::clockValue now () inline static
Definition at line 23 of file clockValueI.H.
References clockValue::clockValue().
Referenced by profiling::beginTimer(), clockValue::elapsed(), and profiling::writeData().
value()
const value_type & value () const inline
Definition at line 91 of file clockValue.H.
Referenced by Foam::operator+(), and Foam::operator-().
clear()
void clear () inline
Definition at line 51 of file clockValueI.H.
update()
void update () inline
Definition at line 57 of file clockValueI.H.
seconds()
long seconds () const inline
Definition at line 63 of file clockValueI.H.
References UPtrList< T >::count().
elapsed()
Foam::clockValue elapsed () const inline
Definition at line 69 of file clockValueI.H.
References clockValue::now().
elapsedTime()
double elapsedTime () const inline
Definition at line 75 of file clockValueI.H.
str()
std::string str () const
Definition at line 27 of file clockValue.C.
References UPtrList< T >::count(), and os().
operator double()
operator double () const inline
Definition at line 83 of file clockValueI.H.
operator-=()
Foam::clockValue & operator-= (const clockValue & rhs) inline
Definition at line 93 of file clockValueI.H.
operator+=()
Foam::clockValue & operator+= (const clockValue & rhs) inline
Definition at line 100 of file clockValueI.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/global/clockValue/clockValue.H
src/OpenFOAM/global/clockValue/clockValue.C
src/OpenFOAM/global/clockValue/clockValueI.H