OpenFOAM: gradScheme< Type > Class Template Reference
gradScheme< Type > Class Template Reference abstract
Abstract base class for finite area calculus gradient schemes.
#include <faGradScheme.H>
Public Member Functions
declareRunTimeSelectionTable (tmp, gradScheme, Istream,(const faMesh &mesh, Istream &schemeData),(mesh, schemeData))
gradScheme (const faMesh &mesh)
virtual ~gradScheme ()=default
const faMesh & mesh () const
virtual tmp< GeometricField< typename outerProduct< vector, Type >::type, faPatchField, areaMesh > > calcGrad (const GeometricField< Type, faPatchField, areaMesh > &, const word &name) const =0
tmp< GeometricField< typename outerProduct< vector, Type >::type, faPatchField, areaMesh > > grad (const GeometricField< Type, faPatchField, areaMesh > &, const word &name) const
tmp< GeometricField< typename outerProduct< vector, Type >::type, faPatchField, areaMesh > > grad (const GeometricField< Type, faPatchField, areaMesh > &) const
tmp< GeometricField< typename outerProduct< vector, Type >::type, faPatchField, areaMesh > > grad (const tmp< GeometricField< Type, faPatchField, areaMesh > > &) const
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Static Public Member Functions
static tmp< gradScheme< Type > > New (const faMesh &mesh, Istream &schemeData)
Detailed Description
template<class Type>
class Foam::fa::gradScheme< Type >
Abstract base class for finite area calculus gradient schemes.
Source files
faGradScheme.H
faGradScheme.C
faGradSchemes.C
Definition at line 60 of file faGradScheme.H.
Constructor & Destructor Documentation
gradScheme()
template<class Type > gradScheme (const faMesh & mesh) inline
Definition at line 95 of file faGradScheme.H.
~gradScheme()
template<class Type > virtual ~gradScheme () virtual default
Member Function Documentation
declareRunTimeSelectionTable()
template<class Type > declareRunTimeSelectionTable (tmp , gradScheme< Type > , Istream , (const faMesh &mesh, Istream &schemeData) , (mesh, schemeData))
New()
template<class Type > tmp< gradScheme< Type > > New (const faMesh & mesh, Istream & schemeData) static
Definition at line 40 of file faGradScheme.C.
References Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, FatalIOErrorInLookup, InfoInFunction, mesh, and Foam::nl.
Referenced by Foam::fac::grad(), and Foam::fac::ngrad().
mesh()
template<class Type > const faMesh & mesh () const inline
Definition at line 118 of file faGradScheme.H.
Referenced by gaussGrad< Type >::gaussGrad().
calcGrad()
template<class Type > virtual tmp< GeometricField< typename outerProduct< vector, Type >::type, faPatchField, areaMesh > > calcGrad (const GeometricField< Type, faPatchField, areaMesh > & , const word & name) const pure virtual
Implemented in gaussGrad< Type >, leastSquaresFaGrad< Type >, edgeLimitedGrad< Type >, and faceLimitedGrad< Type >.
grad() [1/3]
template<class Type > tmp< GeometricField< typename outerProduct< vector, Type >::type, faPatchField, areaMesh > > grad (const GeometricField< Type, faPatchField, areaMesh > & vsf, const word & name) const
Definition at line 93 of file faGradScheme.C.
References solution::cachePrintMessage(), mesh, Foam::name(), and regIOobject::store().
Referenced by leastSquaresEdgeInterpolation< Type >::interpolate().
grad() [2/3]
template<class Type > tmp< GeometricField< typename outerProduct< vector, Type >::type, faPatchField, areaMesh > > grad (const GeometricField< Type, faPatchField, areaMesh > & vsf) const
Definition at line 156 of file faGradScheme.C.
grad() [3/3]
template<class Type > tmp< GeometricField< typename outerProduct< vector, Type >::type, faPatchField, areaMesh > > grad (const tmp< GeometricField< Type, faPatchField, areaMesh > > & tvsf) const
Definition at line 175 of file faGradScheme.C.
References PtrList< T >::clear().
The documentation for this class was generated from the following files:
src/finiteArea/finiteArea/gradSchemes/faGradScheme/faGradScheme.H
src/finiteArea/finiteArea/gradSchemes/faGradScheme/faGradScheme.C