OpenFOAM: faceLimitedGrad< Type > Class Template Reference
faceLimitedGrad< Type > Class Template Reference
Numerics » Finite volume numerical schemes » Gradient schemes
faceLimitedGrad gradient scheme applied to a runTime selected base gradient scheme.
#include <faceLimitedGrad.H>
Public Member Functions
TypeName ("faceLimited")
faceLimitedGrad (const fvMesh &mesh, Istream &schemeData)
virtual tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > calcGrad (const GeometricField< Type, fvPatchField, volMesh > &vsf, const word &name) const
tmp< volVectorField > calcGrad (const volScalarField &vsf, const word &name) const
tmp< volTensorField > calcGrad (const volVectorField &vsf, const word &name) const
Foam::tmp< Foam::volTensorField > calcGrad (const volVectorField &vvf, const word &name) const
Public Member Functions inherited from gradScheme< Type >
virtual const word & type () const =0
declareRunTimeSelectionTable (tmp, gradScheme, Istream,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
gradScheme (const fvMesh &mesh)
virtual ~gradScheme ()=default
const fvMesh & mesh () const
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > grad (const GeometricField< Type, fvPatchField, volMesh > &, const word &name) const
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > grad (const GeometricField< Type, fvPatchField, volMesh > &) const
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > grad (const tmp< GeometricField< Type, fvPatchField, volMesh > > &) const
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Additional Inherited Members
Static Public Member Functions inherited from gradScheme< Type >
static tmp< gradScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Detailed Description
template<class Type>
class Foam::fv::faceLimitedGrad< Type >
faceLimitedGrad gradient scheme applied to a runTime selected base gradient scheme.
The scalar limiter based on limiting the extrapolated face values between the face-neighbour cell values and is applied to all components of the gradient.
Source files
faceLimitedGrad.H
faceLimitedGrad.C
Definition at line 61 of file faceLimitedGrad.H.
Constructor & Destructor Documentation
faceLimitedGrad()
template<class Type > faceLimitedGrad (const fvMesh & mesh, Istream & schemeData) inline
Definition at line 101 of file faceLimitedGrad.H.
References Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, and fv().
Member Function Documentation
TypeName()
template<class Type > TypeName ("faceLimited")
calcGrad() [1/4]
template<class Type > virtual tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > calcGrad (const GeometricField< Type, fvPatchField, volMesh > & vsf, const word & name) const inline virtual
Implements gradScheme< Type >.
Definition at line 125 of file faceLimitedGrad.H.
References gradScheme< Type >::grad().
calcGrad() [2/4]
tmp< volVectorField > calcGrad (const volScalarField & vsf, const word & name) const
calcGrad() [3/4]
tmp< volTensorField > calcGrad (const volVectorField & vsf, const word & name) const
calcGrad() [4/4]
Foam::tmp< Foam::volTensorField > calcGrad (const volVectorField & vvf, const word & name) const
Definition at line 174 of file faceLimitedGrads.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), Foam::endl(), forAll, g, Foam::gAverage(), Foam::gMax(), Foam::gMin(), Foam::Info, Foam::limiter(), Foam::magSqr(), Foam::max(), mesh, Foam::min(), Foam::name(), and UPtrList< T >::size().
The documentation for this class was generated from the following file:
src/finiteVolume/finiteVolume/gradSchemes/limitedGradSchemes/faceLimitedGrad/faceLimitedGrad.H