OpenFOAM: writeFile Class Reference
writeFile Class Reference
Base class for writing single files from the function objects.
#include <writeFile.H>
Public Member Functions
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name="undefined", const bool writeToFile=true)
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name, const dictionary &dict, const bool writeToFile=true)
writeFile (const writeFile &wf)
virtual ~writeFile ()=default
virtual bool read (const dictionary &dict)
virtual OFstream & file ()
virtual bool writeToFile () const
virtual bool canWriteToFile () const
virtual bool canResetFile () const
virtual bool canWriteHeader () const
virtual label charWidth () const
virtual void writeCommented (Ostream &os, const string &str) const
virtual void writeTabbed (Ostream &os, const string &str) const
virtual void writeHeader (Ostream &os, const string &str) const
virtual void writeCurrentTime (Ostream &os) const
virtual void writeBreak (Ostream &os) const
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
template<class Type >
void writeValue (Ostream &os, const Type &val) const
Static Public Attributes
static label addChars = 8
Protected Member Functions
void initStream (Ostream &os) const
fileName baseFileDir () const
fileName baseTimeDir () const
fileName filePath (const fileName &fName) const
virtual autoPtr< OFstream > newFile (const fileName &fName) const
virtual autoPtr< OFstream > newFileAtTime (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > newFileAtStartTime (const word &name) const
virtual void resetFile (const word &name)
Omanip< int > valueWidth (const label offset=0) const
void operator= (const writeFile &)=delete
virtual autoPtr< OFstream > createFile (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > createFile (const word &name) const
Protected Attributes
const objectRegistry & fileObr_
const fileName prefix_
word fileName_
autoPtr< OFstream > filePtr_
label writePrecision_
bool writeToFile_
bool updateHeader_
bool writtenHeader_
bool useUserTime_
scalar startTime_
Detailed Description
Base class for writing single files from the function objects.
Usage
<dictName>
{
    // Inherited entries
    ...
    // Optional entries
    writePrecision    <int>;
    writeToFile       <bool>;
    useUserTime       <bool>;
    updateHeader      <bool>;
}
where the entries mean:
Property Description Type Reqd Deflt
writePrecision Number of decimal points int no <system dflt>
writeToFile Produce text file output? bool no true
useUserTime Use user time (e.g. degrees)? bool no true
updateHeader Update header on mesh changes? bool no true
Note
The file header is normally updated whenver the mesh points or topology changes. In some cases, the function object is actually unaffected by these changes. Use the updateHeader flag to override the default behaviour.
Source files
writeFile.H
writeFile.C
writeFileTemplates.C
Definition at line 112 of file writeFile.H.
Constructor & Destructor Documentation
writeFile() [1/3]
writeFile (const objectRegistry & obr, const fileName & prefix, const word & name = "undefined", const bool writeToFile = true)
Definition at line 198 of file writeFile.C.
writeFile() [2/3]
writeFile (const objectRegistry & obr, const fileName & prefix, const word & name, const dictionary & dict, const bool writeToFile = true)
Definition at line 219 of file writeFile.C.
References dict, writeFile::fileName_, writeFile::filePtr_, writeFile::newFileAtStartTime(), writeFile::read(), and writeFile::writeToFile_.
writeFile() [3/3]
writeFile (const writeFile & wf)
Definition at line 183 of file writeFile.C.
~writeFile()
virtual ~writeFile () virtual default
Member Function Documentation
initStream()
void initStream (Ostream & os) const protected
Definition at line 35 of file writeFile.C.
References writeFile::charWidth(), os(), and writeFile::writePrecision_.
Referenced by logFiles::createFiles().
baseFileDir()
Foam::fileName baseFileDir () const protected
Definition at line 43 of file writeFile.C.
References meshPtr, and functionObject::outputPrefix.
Referenced by surfaceNoise::calculate(), and pointNoise::processData().
baseTimeDir()
Foam::fileName baseTimeDir () const protected
Definition at line 66 of file writeFile.C.
Referenced by regionSizeDistribution::write().
filePath()
Foam::fileName filePath (const fileName & fName) const protected
Definition at line 72 of file writeFile.C.
Referenced by surfaceNoise::calculate().
newFile()
Foam::autoPtr< Foam::OFstream > newFile (const fileName & fName) const protected virtual
Definition at line 81 of file writeFile.C.
References Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, UPstream::master(), Foam::mkDir(), fileName::name(), and path().
Referenced by surfaceNoise::calculate(), and pointNoise::processData().
newFileAtTime()
Foam::autoPtr< Foam::OFstream > newFileAtTime (const word & name, scalar timeValue) const protected virtual
Definition at line 109 of file writeFile.C.
References Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, UPstream::master(), Foam::mkDir(), Foam::name(), timeName, and Time::timeName().
Referenced by writeFile::createFile().
newFileAtStartTime()
Foam::autoPtr< Foam::OFstream > newFileAtStartTime (const word & name) const protected virtual
Definition at line 155 of file writeFile.C.
References Foam::name().
Referenced by writeFile::createFile(), logFiles::createFiles(), FaceInteraction< CloudType >::FaceInteraction(), sizeDistribution::sizeDistribution(), and writeFile::writeFile().
resetFile()
void resetFile (const word & name) protected virtual
Definition at line 165 of file writeFile.C.
Referenced by logFiles::resetName(), sizeDistribution::sizeDistribution(), and turbulentTemperatureRadCoupledMixedFvPatchScalarField::updateCoeffs().
valueWidth()
Foam::Omanip< int > valueWidth (const label offset = 0) const protected
Definition at line 172 of file writeFile.C.
References Foam::setw().
operator=()
void operator= (const writeFile &) protected delete
createFile() [1/2]
virtual autoPtr< OFstream > createFile (const word & name, scalar timeValue) const inline protected virtual
Definition at line 199 of file writeFile.H.
References Foam::name(), and writeFile::newFileAtTime().
createFile() [2/2]
virtual autoPtr< OFstream > createFile (const word & name) const inline protected virtual
Definition at line 213 of file writeFile.H.
References Foam::name(), and writeFile::newFileAtStartTime().
read()
bool read (const dictionary & dict) virtual
Reimplemented in AMIWeights, blendingFactor, continuityError, Curle, DESModelRegions, extractEulerianParticles, fieldExtents, fieldMinMax, interfaceHeight, momentum, particleDistribution, reactionsSensitivityAnalysis< chemistryType >, regionSizeDistribution, stabilityBlendingFactor, valueAverage, wallShearStress, yPlus, propellerInfo, energySpectrum, solverInfo, sixDoFRigidBodyState, binModel, singleDirectionUniformBin, uniformBin, STDMD, fieldValue, surfaceFieldValue, volFieldValue, fluxSummary, equalBinWidth, histogramModel, unequalBinWidth, multiFieldValue, wallHeatFlux, forceCoeffs, forces, cloudInfo, sizeDistribution, timeInfo, velocityDampingConstraint, limitTemperature, limitTurbulenceViscosity, limitVelocity, actuationDiskSource, effectivenessTable, referenceTemperature, radialActuationDiskSource, valueAverageBase, noiseModel, pointNoise, surfaceNoise, specieReactionRates< ChemistryModelType >, DMDModel, and heatExchangerModel.
Definition at line 241 of file writeFile.C.
References IOstream::defaultPrecision(), dict, and UPstream::master().
Referenced by logFiles::logFiles(), AMIWeights::read(), blendingFactor::read(), continuityError::read(), Curle::read(), DESModelRegions::read(), extractEulerianParticles::read(), fieldExtents::read(), fieldMinMax::read(), momentum::read(), particleDistribution::read(), reactionsSensitivityAnalysis< chemistryType >::read(), regionSizeDistribution::read(), stabilityBlendingFactor::read(), wallShearStress::read(), yPlus::read(), energySpectrum::read(), binModel::read(), fieldValue::read(), fluxSummary::read(), histogramModel::read(), multiFieldValue::read(), wallHeatFlux::read(), forces::read(), cloudInfo::read(), sizeDistribution::read(), timeInfo::read(), valueAverageBase::read(), noiseModel::read(), and writeFile::writeFile().
file()
Foam::OFstream & file () virtual
Definition at line 264 of file writeFile.C.
References FatalErrorInFunction, and Foam::Snull.
Referenced by velocityDampingConstraint::addDamping(), blendingFactor::blendingFactor(), valueAverageBase::calc(), continuityError::continuityError(), DESModelRegions::DESModelRegions(), effectivenessTable::effectivenessTable(), fieldMinMax::output(), referenceTemperature::referenceTemperature(), sixDoFRigidBodyState::sixDoFRigidBodyState(), specieReactionRates< ChemistryModelType >::specieReactionRates(), stabilityBlendingFactor::stabilityBlendingFactor(), timeInfo::timeInfo(), turbulentTemperatureRadCoupledMixedFvPatchScalarField::updateCoeffs(), valueAverageBase::valueAverageBase(), volFieldValue::volFieldValue(), wallHeatFlux::wallHeatFlux(), wallShearStress::wallShearStress(), fieldMinMax::writeFileHeader(), solverInfo::writeFileHeader(), and yPlus::yPlus().
writeToFile()
bool writeToFile () const virtual
Definition at line 281 of file writeFile.C.
Referenced by FaceInteraction< CloudType >::FaceInteraction().
canWriteToFile()
bool canWriteToFile () const virtual
Definition at line 287 of file writeFile.C.
References UPstream::master().
Referenced by velocityDampingConstraint::addDamping(), and turbulentTemperatureRadCoupledMixedFvPatchScalarField::updateCoeffs().
canResetFile()
bool canResetFile () const virtual
Definition at line 293 of file writeFile.C.
References UPstream::master().
Referenced by turbulentTemperatureRadCoupledMixedFvPatchScalarField::updateCoeffs().
canWriteHeader()
bool canWriteHeader () const virtual
Definition at line 299 of file writeFile.C.
References UPstream::master().
Referenced by turbulentTemperatureRadCoupledMixedFvPatchScalarField::updateCoeffs().
charWidth()
Foam::label charWidth () const virtual
Definition at line 306 of file writeFile.C.
Referenced by writeFile::initStream(), and writeFile::writeHeaderValue().
writeCommented()
void writeCommented (Ostream & os, const string & str) const virtual
Definition at line 312 of file writeFile.C.
References os(), Foam::setf(), and Foam::setw().
Referenced by FaceInteraction< CloudType >::FaceInteraction(), multiFieldValue::writeFileHeader(), singleDirectionUniformBin::writeFileHeader(), uniformBin::writeFileHeader(), AMIWeights::writeFileHeader(), continuityError::writeFileHeader(), fieldExtents::writeFileHeader(), fieldMinMax::writeFileHeader(), histogramModel::writeFileHeader(), energySpectrum::writeFileHeader(), solverInfo::writeFileHeader(), timeInfo::writeFileHeader(), limitTemperature::writeFileHeader(), limitTurbulenceViscosity::writeFileHeader(), limitVelocity::writeFileHeader(), sixDoFRigidBodyState::writeFileHeader(), blendingFactor::writeFileHeader(), DESModelRegions::writeFileHeader(), wallHeatFlux::writeFileHeader(), wallShearStress::writeFileHeader(), cloudInfo::writeFileHeader(), and valueAverageBase::writeFileHeader().
writeTabbed()
void writeTabbed (Ostream & os, const string & str) const virtual
Definition at line 328 of file writeFile.C.
References os(), Foam::setw(), and Foam::tab.
Referenced by FaceInteraction< CloudType >::FaceInteraction(), fieldMinMax::output(), multiFieldValue::writeFileHeader(), singleDirectionUniformBin::writeFileHeader(), uniformBin::writeFileHeader(), AMIWeights::writeFileHeader(), fieldExtents::writeFileHeader(), fieldMinMax::writeFileHeader(), histogramModel::writeFileHeader(), timeInfo::writeFileHeader(), limitTemperature::writeFileHeader(), limitTurbulenceViscosity::writeFileHeader(), limitVelocity::writeFileHeader(), blendingFactor::writeFileHeader(), DESModelRegions::writeFileHeader(), wallHeatFlux::writeFileHeader(), wallShearStress::writeFileHeader(), cloudInfo::writeFileHeader(), valueAverageBase::writeFileHeader(), and solverInfo::writeFileHeader().
writeHeader()
void writeHeader (Ostream & os, const string & str) const virtual
Definition at line 338 of file writeFile.C.
References Foam::nl, and os().
Referenced by singleDirectionUniformBin::writeFileHeader(), uniformBin::writeFileHeader(), AMIWeights::writeFileHeader(), continuityError::writeFileHeader(), fieldExtents::writeFileHeader(), fieldMinMax::writeFileHeader(), histogramModel::writeFileHeader(), energySpectrum::writeFileHeader(), solverInfo::writeFileHeader(), sixDoFRigidBodyState::writeFileHeader(), blendingFactor::writeFileHeader(), DESModelRegions::writeFileHeader(), wallHeatFlux::writeFileHeader(), wallShearStress::writeFileHeader(), cloudInfo::writeFileHeader(), and valueAverageBase::writeFileHeader().
writeCurrentTime()
void writeCurrentTime (Ostream & os) const virtual
Definition at line 349 of file writeFile.C.
References os(), Foam::setw(), and Time::timeName().
Referenced by fieldMinMax::output().
writeBreak()
void writeBreak (Ostream & os) const virtual
Definition at line 362 of file writeFile.C.
References os(), and Foam::writeHeader().
Referenced by fieldExtents::writeFileHeader(), fieldMinMax::writeFileHeader(), and solverInfo::writeFileHeader().
writeHeaderValue()
template<class Type > void writeHeaderValue (Ostream & os, const string & property, const Type & value) const
Definition at line 25 of file writeFileTemplates.C.
References writeFile::charWidth(), Foam::nl, os(), Foam::setf(), and Foam::setw().
Referenced by FaceInteraction< CloudType >::FaceInteraction(), multiFieldValue::writeFileHeader(), singleDirectionUniformBin::writeFileHeader(), uniformBin::writeFileHeader(), fieldExtents::writeFileHeader(), limitTemperature::writeFileHeader(), limitTurbulenceViscosity::writeFileHeader(), limitVelocity::writeFileHeader(), and sixDoFRigidBodyState::writeFileHeader().
writeValue()
template<class Type > void writeValue (Ostream & os, const Type & val) const
Definition at line 39 of file writeFileTemplates.C.
References Foam::component(), and os().
Member Data Documentation
fileObr_
const objectRegistry& fileObr_ protected
Definition at line 119 of file writeFile.H.
Referenced by logFiles::createFiles(), surfaceNoise::initialise(), and pointNoise::processData().
prefix_
const fileName prefix_ protected
Definition at line 122 of file writeFile.H.
fileName_
word fileName_ protected
Definition at line 125 of file writeFile.H.
Referenced by writeFile::writeFile().
filePtr_
autoPtr<OFstream> filePtr_ protected
Definition at line 128 of file writeFile.H.
Referenced by writeFile::writeFile().
writePrecision_
label writePrecision_ protected
Definition at line 131 of file writeFile.H.
Referenced by writeFile::initStream(), and turbulentTemperatureRadCoupledMixedFvPatchScalarField::write().
writeToFile_
bool writeToFile_ protected
Definition at line 134 of file writeFile.H.
Referenced by stabilityBlendingFactor::stabilityBlendingFactor(), turbulentTemperatureRadCoupledMixedFvPatchScalarField::write(), and writeFile::writeFile().
updateHeader_
bool updateHeader_ protected
Definition at line 138 of file writeFile.H.
Referenced by turbulentTemperatureRadCoupledMixedFvPatchScalarField::write().
writtenHeader_
bool writtenHeader_ protected
Definition at line 141 of file writeFile.H.
Referenced by fieldExtents::writeFileHeader(), fieldMinMax::writeFileHeader(), solverInfo::writeFileHeader(), limitTemperature::writeFileHeader(), limitTurbulenceViscosity::writeFileHeader(), and limitVelocity::writeFileHeader().
useUserTime_
bool useUserTime_ protected
Definition at line 145 of file writeFile.H.
Referenced by turbulentTemperatureRadCoupledMixedFvPatchScalarField::write().
startTime_
scalar startTime_ protected
Definition at line 148 of file writeFile.H.
addChars
Foam::label addChars = 8 static
Definition at line 225 of file writeFile.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/db/functionObjects/writeFile/writeFile.H
src/OpenFOAM/db/functionObjects/writeFile/writeFile.C
src/OpenFOAM/db/functionObjects/writeFile/writeFileTemplates.C