OpenFOAM: fvPatchFieldBase Class Reference
fvPatchFieldBase Class Reference
#include <fvPatchField.H>
Public Member Functions
TypeName ("fvPatchField")
fvPatchFieldBase (const fvPatch &p)
fvPatchFieldBase (const fvPatch &p, const word &patchType)
fvPatchFieldBase (const fvPatch &p, const dictionary &dict)
fvPatchFieldBase (const fvPatchFieldBase &rhs, const fvPatch &p)
fvPatchFieldBase (const fvPatchFieldBase &rhs)
virtual ~fvPatchFieldBase ()=default
virtual bool assignable () const
virtual bool fixesValue () const
virtual bool coupled () const
const objectRegistry & db () const
const fvPatch & patch () const noexcept
const word & patchType () const noexcept
word & patchType () noexcept
bool updated () const noexcept
bool manipulatedMatrix () const noexcept
bool useImplicit () const noexcept
bool useImplicit (bool on) noexcept
void checkPatch (const fvPatchFieldBase &rhs) const
Static Public Member Functions
static const word & emptyType () noexcept
static const word & calculatedType () noexcept
static const word & extrapolatedCalculatedType () noexcept
static const word & zeroGradientType () noexcept
Static Public Attributes
static int disallowGenericPatchField
Protected Member Functions
virtual void readDict (const dictionary &dict)
void setUpdated (bool state) noexcept
void setManipulated (bool state) noexcept
Detailed Description
Definition at line 77 of file fvPatchField.H.
Constructor & Destructor Documentation
fvPatchFieldBase() [1/5]
fvPatchFieldBase (const fvPatch & p) explicit
Definition at line 39 of file fvPatchFieldBase.C.
fvPatchFieldBase() [2/5]
fvPatchFieldBase (const fvPatch & p, const word & patchType) explicit
Definition at line 49 of file fvPatchFieldBase.C.
References fvPatchFieldBase::patchType().
fvPatchFieldBase() [3/5]
fvPatchFieldBase (const fvPatch & p, const dictionary & dict)
Definition at line 61 of file fvPatchFieldBase.C.
References dict, and fvPatchFieldBase::readDict().
fvPatchFieldBase() [4/5]
fvPatchFieldBase (const fvPatchFieldBase & rhs, const fvPatch & p)
Definition at line 73 of file fvPatchFieldBase.C.
fvPatchFieldBase() [5/5]
fvPatchFieldBase (const fvPatchFieldBase & rhs)
Definition at line 87 of file fvPatchFieldBase.C.
~fvPatchFieldBase()
virtual ~fvPatchFieldBase () virtual default
Member Function Documentation
readDict()
void readDict (const dictionary & dict) protected virtual
Definition at line 99 of file fvPatchFieldBase.C.
References dict, keyType::LITERAL, and dictionary::readIfPresent().
Referenced by fixedFluxPressureFvPatchScalarField::fixedFluxPressureFvPatchScalarField(), fixedNormalInletOutletVelocityFvPatchVectorField::fixedNormalInletOutletVelocityFvPatchVectorField(), fixedNormalSlipFvPatchField< Type >::fixedNormalSlipFvPatchField(), freestreamFvPatchField< Type >::freestreamFvPatchField(), freeSurfaceVelocityFvPatchVectorField::freeSurfaceVelocityFvPatchVectorField(), fvPatchFieldBase::fvPatchFieldBase(), inletOutletFvPatchField< Type >::inletOutletFvPatchField(), inletOutletTotalTemperatureFvPatchScalarField::inletOutletTotalTemperatureFvPatchScalarField(), lumpedMassWallTemperatureFvPatchScalarField::lumpedMassWallTemperatureFvPatchScalarField(), mappedMixedFvPatchField< Type >::mappedMixedFvPatchField(), noSlipFvPatchVectorField::noSlipFvPatchVectorField(), outletInletFvPatchField< Type >::outletInletFvPatchField(), outletPhaseMeanVelocityFvPatchVectorField::outletPhaseMeanVelocityFvPatchVectorField(), partialSlipFvPatchField< Type >::partialSlipFvPatchField(), phaseHydrostaticPressureFvPatchScalarField::phaseHydrostaticPressureFvPatchScalarField(), pressureDirectedInletOutletVelocityFvPatchVectorField::pressureDirectedInletOutletVelocityFvPatchVectorField(), pressureInletOutletParSlipVelocityFvPatchVectorField::pressureInletOutletParSlipVelocityFvPatchVectorField(), pressureInletOutletVelocityFvPatchVectorField::pressureInletOutletVelocityFvPatchVectorField(), pressureNormalInletOutletVelocityFvPatchVectorField::pressureNormalInletOutletVelocityFvPatchVectorField(), pressurePermeableAlphaInletOutletVelocityFvPatchVectorField::pressurePermeableAlphaInletOutletVelocityFvPatchVectorField(), slicedFvPatchField< Type >::slicedFvPatchField(), supersonicFreestreamFvPatchVectorField::supersonicFreestreamFvPatchVectorField(), turbulentIntensityKineticEnergyInletFvPatchScalarField::turbulentIntensityKineticEnergyInletFvPatchScalarField(), uniformFixedGradientFvPatchField< Type >::uniformFixedGradientFvPatchField(), uniformInletOutletFvPatchField< Type >::uniformInletOutletFvPatchField(), uniformMixedFvPatchField< Type >::uniformMixedFvPatchField(), and variableHeightFlowRateFvPatchScalarField::variableHeightFlowRateFvPatchScalarField().
setUpdated()
void setUpdated (bool state) inline protected noexcept
Definition at line 111 of file fvPatchField.H.
Referenced by fvPatchField< Type >::evaluate(), fvPatchField< Type >::updateCoeffs(), and fvPatchField< Type >::updateWeightedCoeffs().
setManipulated()
void setManipulated (bool state) inline protected noexcept
Definition at line 117 of file fvPatchField.H.
Referenced by fvPatchField< Type >::evaluate(), fvPatchField< symmTensor >::fvPatchField(), fvPatchField< Type >::manipulateMatrix(), and fvPatchField< Type >::manipulateMatrix().
TypeName()
TypeName ("fvPatchField")
emptyType()
static const word & emptyType () inline static noexcept
Definition at line 157 of file fvPatchField.H.
References Foam::fieldTypes::emptyType.
calculatedType()
static const word & calculatedType () inline static noexcept
Definition at line 163 of file fvPatchField.H.
References Foam::fieldTypes::calculatedType.
Referenced by meshRefinement::appendPatch(), nearWallDist::correct(), nearWallFields::createFields(), Foam::createZeroBoundaryPtr(), fvFieldDecomposer::decomposeField(), eddyViscosity< LESModel< BasicTurbulenceModel > >::eddyViscosity(), backwardDdtScheme< Type >::fvcDdt(), CoEulerDdtScheme< Type >::fvcDdt(), EulerDdtScheme< Type >::fvcDdt(), localEulerDdtScheme< Type >::fvcDdt(), SLTSDdtScheme< Type >::fvcDdt(), singleCellFvMesh::interpolate(), fvMeshSubset::interpolate(), meshToMesh::mapSrcToTgt(), meshToMesh::mapTgtToSrc(), writeCellCentres::write(), writeCellVolumes::write(), and electricPotential::write().
extrapolatedCalculatedType()
static const word & extrapolatedCalculatedType () inline static noexcept
Definition at line 170 of file fvPatchField.H.
References Foam::fieldTypes::extrapolatedCalculatedType.
Referenced by fvMatrix< Type >::A(), greyMeanAbsorptionEmission::aCont(), cellCoBlended< Type >::blendingFactor(), fvMatrix< Type >::H(), fvMatrix< Type >::H1(), Foam::fvc::reconstruct(), Foam::fvc::reconstructMag(), constantFilmThermo::rho(), liquidFilmThermo::rho(), Foam::fvc::surfaceIntegrate(), Foam::fvc::surfaceSum(), StandardChemistryModel< ReactionThermo, ThermoType >::tc(), and laminar::Us().
zeroGradientType()
static const word & zeroGradientType () inline static noexcept
Definition at line 176 of file fvPatchField.H.
References Foam::fieldTypes::zeroGradientType.
Referenced by blendingFactor::blendingFactor(), Implicit< CloudType >::cacheFields(), curvatureSeparation::calcCosAngle(), ObukhovLength::calcOL(), diffusionMulticomponent< ReactionThermo, ThermoType >::correct(), inverseVolumeDiffusivity::correct(), motionDirectionalDiffusivity::correct(), curvatureSeparation::correct(), cellCellStencil::createField(), ATCModel::createLimiter(), meshRefinement::dumpRefinementLevel(), filmFlux::execute(), adjointkOmegaSST::FISensitivityTerm(), InterfaceCompositionModel< Thermo, OtherThermo >::getSpecieMassFraction(), InterfaceCompositionModel< Thermo, OtherThermo >::getSpecieMassFraction(), segregated::K(), InterfaceCompositionModel< Thermo, OtherThermo >::L(), Foam::makeZeroGradientField(), Foam::makeZeroGradientField(), singleLayerRegion::mappedFieldAndInternalPatchTypes(), singleLayerRegion::mappedPushedFieldPatchTypes(), InterfaceCompositionModel< Thermo, OtherThermo >::MwMixture(), adjointEikonalSolver::patchTypes(), patchDistMethod::patchTypes(), diffusionMulticomponent< ReactionThermo, ThermoType >::Qdot(), resolutionIndexModel::read(), eddyDissipationDiffusionModel< ReactionThermo, ThermoType >::rtDiff(), ATCModel::smoothFieldBasedOnCells(), resolutionIndexModel::V(), solverInfo::write(), oversetFvMeshBase::writeObject(), and fvMeshSubsetProxy::zeroGradientField().
assignable()
virtual bool assignable () const inline virtual
Reimplemented in directionMixedFvPatchField< Type >, fixedValueFvPatchField< Type >, fixedValueFvPatchField< scalar >, mixedFvPatchField< Type >, mixedFvPatchField< scalar >, mixedFvPatchField< vector >, slicedFvPatchField< Type >, transformFvPatchField< Type >, fixedNormalSlipFvPatchField< Type >, inletOutletFvPatchField< Type >, partialSlipFvPatchField< Type >, slipFvPatchField< Type >, and uniformInletOutletFvPatchField< Type >.
Definition at line 187 of file fvPatchField.H.
fixesValue()
virtual bool fixesValue () const inline virtual
Reimplemented in calculatedFvPatchField< Type >, directionMixedFvPatchField< Type >, fixedValueFvPatchField< Type >, fixedValueFvPatchField< scalar >, mixedFvPatchField< Type >, mixedFvPatchField< scalar >, mixedFvPatchField< vector >, slicedFvPatchField< Type >, and cyclicACMIFvPatchField< Type >.
Definition at line 195 of file fvPatchField.H.
Referenced by Foam::adjustPhi().
coupled()
virtual bool coupled () const inline virtual
Reimplemented in coupledFvPatchField< Type >, coupledFvPatchField< scalar >, coupledFvPatchField< vector >, calculatedProcessorFvPatchField< Type >, cyclicACMIFvPatchField< Type >, cyclicAMIFvPatchField< Type >, cyclicAMIFvPatchField< scalar >, and processorFvPatchField< Type >.
Definition at line 201 of file fvPatchField.H.
db()
const Foam::objectRegistry & db () const
Definition at line 106 of file fvPatchFieldBase.C.
Referenced by atmEpsilonWallFunctionFvPatchScalarField::calculate(), atmOmegaWallFunctionFvPatchScalarField::calculate(), externalCoupledTemperatureMixedFvPatchScalarField::externalCoupledTemperatureMixedFvPatchScalarField(), fanFvPatchField< Type >::fanFvPatchField(), outletMappedUniformInletFvPatchField< Type >::outletMappedUniformInletFvPatchField(), turbulentDigitalFilterInletFvPatchField< Type >::turbulentDigitalFilterInletFvPatchField(), uniformInletOutletFvPatchField< Type >::uniformInletOutletFvPatchField(), uniformInletOutletFvPatchField< Type >::uniformInletOutletFvPatchField(), uniformJumpAMIFvPatchField< Type >::uniformJumpAMIFvPatchField(), uniformJumpFvPatchField< Type >::uniformJumpFvPatchField(), velocityFilmShellFvPatchVectorField::updateCoeffs(), and vibrationShellFvPatchScalarField::updateCoeffs().
patch()
const fvPatch & patch () const inline noexcept
Definition at line 213 of file fvPatchField.H.
Referenced by advectiveFvPatchField< Type >::advectiveFvPatchField(), atmEpsilonWallFunctionFvPatchScalarField::calculate(), atmOmegaWallFunctionFvPatchScalarField::calculate(), ReynoldsAnalogy::Cf(), cyclicACMIFvPatchField< Type >::cyclicACMIFvPatchField(), cyclicAMIFvPatchField< Type >::cyclicAMIFvPatchField(), cyclicFvPatchField< Type >::cyclicFvPatchField(), fvPatchField< Type >::extrapolateInternal(), genericFvPatchField< Type >::genericFvPatchField(), genericFvPatchField< Type >::genericFvPatchField(), waWallFunctionFvPatchScalarField::manipulateMatrix(), Foam::oversetAdjustPhi(), processorCyclicFvPatchField< Type >::processorCyclicFvPatchField(), processorFvPatchField< Type >::processorFvPatchField(), fixedGradientFvPatchField< Type >::readGradientEntry(), mixedFvPatchField< Type >::readMixedEntries(), fvPatchField< Type >::readValueEntry(), symmetryFvPatchField< Type >::symmetryFvPatchField(), symmetryPlaneFvPatchField< Type >::symmetryPlaneFvPatchField(), uniformMixedFvPatchField< Type >::uniformMixedFvPatchField(), waWallFunctionFvPatchScalarField::updateCoeffs(), velocityFilmShellFvPatchVectorField::updateCoeffs(), thermalShellFvPatchScalarField::updateCoeffs(), vibrationShellFvPatchScalarField::updateCoeffs(), and wedgeFvPatchField< Type >::wedgeFvPatchField().
patchType() [1/2]
const word & patchType () const inline noexcept
Definition at line 219 of file fvPatchField.H.
Referenced by fvPatchFieldBase::fvPatchFieldBase(), and uniformInletOutletFvPatchField< Type >::uniformInletOutletFvPatchField().
patchType() [2/2]
word & patchType () inline noexcept
Definition at line 225 of file fvPatchField.H.
updated()
bool updated () const inline noexcept
Definition at line 234 of file fvPatchField.H.
Referenced by waWallFunctionFvPatchScalarField::updateCoeffs(), velocityFilmShellFvPatchVectorField::updateCoeffs(), thermalShellFvPatchScalarField::updateCoeffs(), and vibrationShellFvPatchScalarField::updateCoeffs().
manipulatedMatrix()
bool manipulatedMatrix () const inline noexcept
Definition at line 240 of file fvPatchField.H.
useImplicit() [1/2]
bool useImplicit () const inline noexcept
Definition at line 246 of file fvPatchField.H.
useImplicit() [2/2]
bool useImplicit (bool on) inline noexcept
Definition at line 253 of file fvPatchField.H.
checkPatch()
void checkPatch (const fvPatchFieldBase & rhs) const
Definition at line 112 of file fvPatchFieldBase.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Referenced by fvPatchField< Type >::check(), fvPatchField< symmTensor >::fvPatchField(), fvPatchField< symmTensor >::fvPatchField(), fvPatchField< Type >::operator+=(), fvPatchField< Type >::operator-=(), and fvPatchField< Type >::operator/=().
Member Data Documentation
disallowGenericPatchField
int disallowGenericPatchField static
Definition at line 126 of file fvPatchField.H.
Referenced by fvPatchField< Type >::New().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/fvPatchField/fvPatchField.H
src/finiteVolume/fields/fvPatchFields/fvPatchField/fvPatchFieldBase.C