OpenFOAM: conformalVoronoiMesh Class Reference
conformalVoronoiMesh Class Reference
#include <conformalVoronoiMesh.H>
Public Types
enum dualMeshPointType {
internal = 0 , surface = 1 , featureEdge = 2 , featurePoint = 3 ,
constrained = 4
}
typedef Delaunay::Vertex_handle Vertex_handle
typedef Delaunay::Cell_handle Cell_handle
typedef Delaunay::Edge Edge
typedef Delaunay::Facet Facet
typedef Delaunay::Point Point
typedef List< DynamicList< labelPairPair > > labelPairPairDynListList
typedef Tuple2< pointIndexHit, label > pointIndexHitAndFeature
typedef List< pointIndexHitAndFeature > pointIndexHitAndFeatureList
typedef DynamicList< pointIndexHitAndFeature > pointIndexHitAndFeatureDynList
Public Types inherited from DistributedDelaunayMesh< Delaunay >
typedef Triangulation::Vertex_handle Vertex_handle
typedef Triangulation::Cell_handle Cell_handle
typedef Triangulation::Point Point
typedef Triangulation::Finite_vertices_iterator Finite_vertices_iterator
typedef Triangulation::Finite_cells_iterator Finite_cells_iterator
typedef Triangulation::All_cells_iterator All_cells_iterator
Public Types inherited from DelaunayMesh< Triangulation >
typedef Triangulation::Cell_handle Cell_handle
typedef Triangulation::Vertex_handle Vertex_handle
typedef Triangulation::Edge Edge
typedef Triangulation::Point Point
typedef Triangulation::Facet Facet
typedef Triangulation::Finite_vertices_iterator Finite_vertices_iterator
typedef Triangulation::Finite_cells_iterator Finite_cells_iterator
typedef Triangulation::Finite_facets_iterator Finite_facets_iterator
Public Member Functions
ClassName ("conformalVoronoiMesh")
conformalVoronoiMesh (const Time &runTime, const dictionary &foamyHexMeshDict, const fileName &decompDictFile="")
~conformalVoronoiMesh ()
void initialiseForMotion ()
void initialiseForConformation ()
void move ()
const Time & time () const
Random & rndGen () const
const searchableSurfaces & allGeometry () const
const conformationSurfaces & geometryToConformTo () const
const backgroundMeshDecomposition & decomposition () const
const cellShapeControl & cellShapeControls () const
const cvControls & foamyHexMeshControls () const
scalar pointPairDistance (const Foam::point &pt) const
scalar mixedFeaturePointDistance (const Foam::point &pt) const
scalar featurePointExclusionDistanceSqr (const Foam::point &pt) const
scalar featureEdgeExclusionDistanceSqr (const Foam::point &pt) const
scalar surfacePtExclusionDistanceSqr (const Foam::point &pt) const
scalar surfaceSearchDistanceSqr (const Foam::point &pt) const
scalar maxSurfaceProtrusion (const Foam::point &pt) const
void createEdgePointGroup (const extendedFeatureEdgeMesh &feMesh, const pointIndexHit &edHit, DynamicList< Vb > &pts) const
void timeCheck (const string &description=string::null) const
void writeMesh (const fileName &instance)
void writeMesh (const word &meshName, const fileName &instance, pointField &points, labelList &boundaryPts, faceList &faces, labelList &owner, labelList &neighbour, const wordList &patchNames, const PtrList< dictionary > &patchDicts, const pointField &cellCentres, bitSet &boundaryFacesToRemove) const
void writeCellSizes (const fvMesh &mesh) const
void writeCellAlignments (const fvMesh &mesh) const
void writeCellCentres (const fvMesh &mesh) const
labelHashSet findRemainingProtrusionSet (const polyMesh &mesh) const
Public Member Functions inherited from DistributedDelaunayMesh< Delaunay >
DistributedDelaunayMesh (const Time &runTime)
DistributedDelaunayMesh (const Time &runTime, const word &meshName)
~DistributedDelaunayMesh ()=default
scalar calculateLoadUnbalance () const
bool distribute (const boundBox &bb)
autoPtr< mapDistribute > distribute (const backgroundMeshDecomposition &decomposition, List< Foam::point > &points)
void sync (const boundBox &bb)
void sync (const boundBox &bb, PtrList< labelPairHashSet > &referralVertices, labelPairHashSet &receivedVertices, bool iterateReferral=true)
labelPairHashSet rangeInsertReferredWithInfo (PointIterator begin, PointIterator end, bool printErrors=true)
Public Member Functions inherited from DelaunayMesh< Triangulation >
DelaunayMesh (const Time &runTime)
DelaunayMesh (const Time &runTime, const word &meshName)
~DelaunayMesh ()
const Time & time () const
void timeCheck (const string &description, const bool check=true) const
label getNewCellIndex () const
label getNewVertexIndex () const
label cellCount () const
label vertexCount () const
void resetCellCount ()
void resetVertexCount ()
void reset ()
Map< label > insertPoints (const List< Vb > &vertices, const bool reIndex)
template<class PointIterator >
Map< label > rangeInsertWithInfo (PointIterator begin, PointIterator end, bool printErrors=false, bool reIndex=true)
void printInfo (Ostream &os) const
void printVertexInfo (Ostream &os) const
autoPtr< polyMesh > createMesh (const fileName &name, labelPairLookup &vertexMap, labelList &cellMap, const bool writeDelaunayData=true) const
Static Public Member Functions
static void timeCheck (const Time &runTime, const string &description=string::null, const bool check=true)
Static Public Member Functions inherited from DistributedDelaunayMesh< Delaunay >
static autoPtr< mapDistribute > buildMap (const List< label > &toProc)
Static Public Attributes
static const Enum< dualMeshPointType > dualMeshPointTypeNames_
Detailed Description
Source files
conformalVoronoiMesh.H
conformalVoronoiMeshI.H
conformalVoronoiMesh.C
conformalVoronoiMeshZones.C
conformalVoronoiMeshIO.C
conformalVoronoiMeshConformToSurface.C
conformalVoronoiMeshFeaturePoints.C
conformalVoronoiMeshCalcDualMesh.C
conformalVoronoiMeshTemplates.C
Definition at line 92 of file conformalVoronoiMesh.H.
Member Typedef Documentation
Vertex_handle
typedef Delaunay::Vertex_handle Vertex_handle
Definition at line 98 of file conformalVoronoiMesh.H.
Cell_handle
typedef Delaunay::Cell_handle Cell_handle
Definition at line 99 of file conformalVoronoiMesh.H.
Edge
typedef Delaunay::Edge Edge
Definition at line 100 of file conformalVoronoiMesh.H.
Facet
typedef Delaunay::Facet Facet
Definition at line 101 of file conformalVoronoiMesh.H.
Point
typedef Delaunay::Point Point
Definition at line 102 of file conformalVoronoiMesh.H.
labelPairPairDynListList
typedef List<DynamicList<labelPairPair> > labelPairPairDynListList
Definition at line 104 of file conformalVoronoiMesh.H.
pointIndexHitAndFeature
typedef Tuple2<pointIndexHit, label> pointIndexHitAndFeature
Definition at line 106 of file conformalVoronoiMesh.H.
pointIndexHitAndFeatureList
typedef List<pointIndexHitAndFeature> pointIndexHitAndFeatureList
Definition at line 107 of file conformalVoronoiMesh.H.
pointIndexHitAndFeatureDynList
typedef DynamicList<pointIndexHitAndFeature> pointIndexHitAndFeatureDynList
Definition at line 108 of file conformalVoronoiMesh.H.
Member Enumeration Documentation
dualMeshPointType
enum dualMeshPointType
Enumerator
internal
surface
featureEdge
featurePoint
constrained
Definition at line 112 of file conformalVoronoiMesh.H.
Constructor & Destructor Documentation
conformalVoronoiMesh()
conformalVoronoiMesh (const Time & runTime, const dictionary & foamyHexMeshDict, const fileName & decompDictFile = "")
~conformalVoronoiMesh()
~conformalVoronoiMesh ()
Member Function Documentation
ClassName()
ClassName ("conformalVoronoiMesh")
initialiseForMotion()
void initialiseForMotion ()
initialiseForConformation()
void initialiseForConformation ()
move()
void move ()
time()
const Foam::Time & time () const inline
Definition at line 519 of file conformalVoronoiMeshI.H.
rndGen()
Foam::Random & rndGen () const inline
Definition at line 525 of file conformalVoronoiMeshI.H.
allGeometry()
const Foam::searchableSurfaces & allGeometry () const inline
Definition at line 532 of file conformalVoronoiMeshI.H.
geometryToConformTo()
const Foam::conformationSurfaces & geometryToConformTo () const inline
Definition at line 539 of file conformalVoronoiMeshI.H.
decomposition()
const Foam::backgroundMeshDecomposition & decomposition () const inline
Definition at line 546 of file conformalVoronoiMeshI.H.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, and UPstream::parRun().
cellShapeControls()
const Foam::cellShapeControl & cellShapeControls () const inline
Definition at line 560 of file conformalVoronoiMeshI.H.
foamyHexMeshControls()
const Foam::cvControls & foamyHexMeshControls () const inline
Definition at line 567 of file conformalVoronoiMeshI.H.
pointPairDistance()
Foam::scalar pointPairDistance (const Foam::point & pt) const inline
Definition at line 132 of file conformalVoronoiMeshI.H.
mixedFeaturePointDistance()
Foam::scalar mixedFeaturePointDistance (const Foam::point & pt) const inline
Definition at line 141 of file conformalVoronoiMeshI.H.
featurePointExclusionDistanceSqr()
Foam::scalar featurePointExclusionDistanceSqr (const Foam::point & pt) const inline
Definition at line 152 of file conformalVoronoiMeshI.H.
References Foam::sqr().
featureEdgeExclusionDistanceSqr()
Foam::scalar featureEdgeExclusionDistanceSqr (const Foam::point & pt) const inline
Definition at line 166 of file conformalVoronoiMeshI.H.
References Foam::sqr().
surfacePtExclusionDistanceSqr()
Foam::scalar surfacePtExclusionDistanceSqr (const Foam::point & pt) const inline
Definition at line 180 of file conformalVoronoiMeshI.H.
References Foam::sqr().
surfaceSearchDistanceSqr()
Foam::scalar surfaceSearchDistanceSqr (const Foam::point & pt) const inline
Definition at line 194 of file conformalVoronoiMeshI.H.
References Foam::sqr().
maxSurfaceProtrusion()
Foam::scalar maxSurfaceProtrusion (const Foam::point & pt) const inline
Definition at line 208 of file conformalVoronoiMeshI.H.
createEdgePointGroup()
void createEdgePointGroup (const extendedFeatureEdgeMesh & feMesh, const pointIndexHit & edHit, DynamicList< Vb > & pts) const
timeCheck() [1/2]
static void timeCheck (const Time & runTime, const string & description = string::null, const bool check = true) static
timeCheck() [2/2]
void timeCheck (const string & description = string::null) const
writeMesh() [1/2]
void writeMesh (const fileName & instance)
writeMesh() [2/2]
void writeMesh (const word & meshName, const fileName & instance, pointField & points, labelList & boundaryPts, faceList & faces, labelList & owner, labelList & neighbour, const wordList & patchNames, const PtrList< dictionary > & patchDicts, const pointField & cellCentres, bitSet & boundaryFacesToRemove) const
writeCellSizes()
void writeCellSizes (const fvMesh & mesh) const
writeCellAlignments()
void writeCellAlignments (const fvMesh & mesh) const
writeCellCentres()
void writeCellCentres (const fvMesh & mesh) const
findRemainingProtrusionSet()
labelHashSet findRemainingProtrusionSet (const polyMesh & mesh) const
Member Data Documentation
dualMeshPointTypeNames_
const Enum<dualMeshPointType> dualMeshPointTypeNames_ static
Definition at line 121 of file conformalVoronoiMesh.H.
The documentation for this class was generated from the following files:
applications/utilities/mesh/generation/foamyMesh/conformalVoronoiMesh/conformalVoronoiMesh/conformalVoronoiMesh.H
applications/utilities/mesh/generation/foamyMesh/conformalVoronoiMesh/conformalVoronoiMesh/conformalVoronoiMeshI.H