OpenFOAM: MovingPhaseModel< BasePhaseModel > Class Template Reference
MovingPhaseModel< BasePhaseModel > Class Template Reference
Class which represents a moving fluid phase. Holds the velocity, fluxes and turbulence model. Provides access to the turbulent quantities.
#include <MovingPhaseModel.H>
Public Member Functions
MovingPhaseModel (const multiphaseInterSystem &fluid, const word &phaseName)
virtual ~MovingPhaseModel ()=default
virtual void correct ()
virtual tmp< surfaceScalarField > phi () const
virtual const surfaceScalarField & phi ()
virtual tmp< surfaceScalarField > alphaPhi () const
virtual surfaceScalarField & alphaPhi ()
virtual tmp< volVectorField > U () const
virtual tmp< surfaceScalarField > diffNo () const
MovingPhaseModel (const phaseSystem &fluid, const word &phaseName, const label index)
virtual ~MovingPhaseModel ()=default
virtual void correct ()
virtual void correctKinematics ()
virtual void correctTurbulence ()
virtual void correctEnergyTransport ()
virtual bool stationary () const
virtual tmp< fvVectorMatrix > UEqn ()
virtual tmp< fvVectorMatrix > UfEqn ()
virtual tmp< volVectorField > U () const
virtual volVectorField & URef ()
virtual tmp< surfaceScalarField > phi () const
virtual surfaceScalarField & phiRef ()
virtual tmp< surfaceScalarField > alphaPhi () const
virtual surfaceScalarField & alphaPhiRef ()
virtual tmp< surfaceScalarField > alphaRhoPhi () const
virtual surfaceScalarField & alphaRhoPhiRef ()
virtual tmp< volVectorField > DUDt () const
virtual tmp< surfaceScalarField > DUDtf () const
virtual tmp< volScalarField > continuityError () const
virtual tmp< volScalarField > continuityErrorFlow () const
virtual tmp< volScalarField > continuityErrorSources () const
virtual tmp< volScalarField > K () const
virtual tmp< volScalarField > divU () const
virtual void divU (tmp< volScalarField > divU)
virtual tmp< volScalarField > mut () const
virtual tmp< volScalarField > muEff () const
virtual tmp< volScalarField > nut () const
virtual tmp< volScalarField > nuEff () const
virtual tmp< volScalarField > kappaEff () const
virtual tmp< scalarField > kappaEff (const label patchi) const
virtual tmp< volScalarField > alphaEff () const
virtual tmp< scalarField > alphaEff (const label patchi) const
virtual tmp< volScalarField > k () const
virtual tmp< volScalarField > pPrime () const
Protected Attributes
volVectorField U_
surfaceScalarField phi_
surfaceScalarField alphaRhoPhi_
tmp< volVectorField > DUDt_
tmp< surfaceScalarField > DUDtf_
tmp< volScalarField > divU_
autoPtr< phaseCompressibleTurbulenceModel > turbulence_
volScalarField continuityErrorFlow_
volScalarField continuityErrorSources_
tmp< volScalarField > K_
Detailed Description
template<class BasePhaseModel>
class Foam::MovingPhaseModel< BasePhaseModel >
Class which represents a moving fluid phase. Holds the velocity, fluxes and turbulence model. Provides access to the turbulent quantities.
Class which represents a moving fluid phase. Holds the velocity, fluxes and turbulence model and can generate the momentum equation. The interface is quite restrictive as it also has to support an equivalent stationary model, which does not store motion fields or a turbulence model.
Possible future extensions include separating the turbulent fuctionality into another layer.
Source files
MovingPhaseModel.H
MovingPhaseModel.C
Possible future extensions include separating the turbulent fuctionality into another layer.
See also
StationaryPhaseModel
Source files
MovingPhaseModel.H
MovingPhaseModel.C
Definition at line 51 of file MovingPhaseModel.H.
Constructor & Destructor Documentation
MovingPhaseModel() [1/2]
template<class BasePhaseModel > MovingPhaseModel (const multiphaseInterSystem & fluid, const word & phaseName)
Definition at line 40 of file MovingPhaseModel.C.
References Foam::name().
~MovingPhaseModel() [1/2]
template<class BasePhaseModel > virtual ~MovingPhaseModel () virtual default
MovingPhaseModel() [2/2]
template<class BasePhaseModel > MovingPhaseModel (const phaseSystem & fluid, const word & phaseName, const label index)
Definition at line 120 of file MovingPhaseModel.C.
References IOobjectOption::AUTO_WRITE, and MovingPhaseModel< BasePhaseModel >::correctKinematics().
~MovingPhaseModel() [2/2]
template<class BasePhaseModel > virtual ~MovingPhaseModel () virtual default
Member Function Documentation
correct() [1/2]
template<class BasePhaseModel > void correct () virtual
Definition at line 70 of file MovingPhaseModel.C.
phi() [1/3]
template<class BasePhaseModel > Foam::tmp< Foam::surfaceScalarField > phi () const virtual
Definition at line 78 of file MovingPhaseModel.C.
phi() [2/3]
template<class BasePhaseModel > const Foam::surfaceScalarField & phi () virtual
Definition at line 86 of file MovingPhaseModel.C.
alphaPhi() [1/3]
template<class BasePhaseModel > Foam::tmp< Foam::surfaceScalarField > alphaPhi () const virtual
Definition at line 94 of file MovingPhaseModel.C.
alphaPhi() [2/3]
template<class BasePhaseModel > Foam::surfaceScalarField & alphaPhi () virtual
Definition at line 102 of file MovingPhaseModel.C.
U() [1/2]
template<class BasePhaseModel > Foam::tmp< Foam::volVectorField > U () const virtual
Definition at line 110 of file MovingPhaseModel.C.
diffNo()
template<class BasePhaseModel > Foam::tmp< Foam::surfaceScalarField > diffNo () const virtual
Definition at line 117 of file MovingPhaseModel.C.
References Foam::dimless, IOobject::groupName(), phaseModel::name(), tmp< T >::New(), and Foam::Zero.
correct() [2/2]
template<class BasePhaseModel > virtual void correct () virtual
correctKinematics()
template<class BasePhaseModel > void correctKinematics () virtual
Definition at line 226 of file MovingPhaseModel.C.
References Foam::magSqr(), and U.
Referenced by MovingPhaseModel< BasePhaseModel >::MovingPhaseModel().
correctTurbulence()
template<class BasePhaseModel > void correctTurbulence () virtual
Definition at line 250 of file MovingPhaseModel.C.
correctEnergyTransport()
template<class BasePhaseModel > void correctEnergyTransport () virtual
Definition at line 259 of file MovingPhaseModel.C.
stationary()
template<class BasePhaseModel > bool stationary () const virtual
Definition at line 268 of file MovingPhaseModel.C.
UEqn()
template<class BasePhaseModel > Foam::tmp< Foam::fvVectorMatrix > UEqn () virtual
Definition at line 276 of file MovingPhaseModel.C.
References alpha, Foam::fvm::ddt(), Foam::fvm::div(), fluid, MRF, rho, and Foam::fvm::SuSp().
UfEqn()
template<class BasePhaseModel > Foam::tmp< Foam::fvVectorMatrix > UfEqn () virtual
Definition at line 294 of file MovingPhaseModel.C.
References alpha, Foam::fvc::div(), Foam::fvm::div(), fluid, MRF, rho, Foam::fvm::Sp(), and Foam::fvm::SuSp().
U() [2/2]
template<class BasePhaseModel > virtual tmp< volVectorField > U () const virtual
URef()
template<class BasePhaseModel > Foam::volVectorField & URef () virtual
Definition at line 322 of file MovingPhaseModel.C.
phi() [3/3]
template<class BasePhaseModel > virtual tmp< surfaceScalarField > phi () const virtual
phiRef()
template<class BasePhaseModel > Foam::surfaceScalarField & phiRef () virtual
Definition at line 338 of file MovingPhaseModel.C.
alphaPhi() [3/3]
template<class BasePhaseModel > virtual tmp< surfaceScalarField > alphaPhi () const virtual
alphaPhiRef()
template<class BasePhaseModel > Foam::surfaceScalarField & alphaPhiRef () virtual
Definition at line 354 of file MovingPhaseModel.C.
alphaRhoPhi()
template<class BasePhaseModel > Foam::tmp< Foam::surfaceScalarField > alphaRhoPhi () const virtual
Definition at line 362 of file MovingPhaseModel.C.
alphaRhoPhiRef()
template<class BasePhaseModel > Foam::surfaceScalarField & alphaRhoPhiRef () virtual
Definition at line 370 of file MovingPhaseModel.C.
DUDt()
template<class BasePhaseModel > Foam::tmp< Foam::volVectorField > DUDt () const virtual
Definition at line 378 of file MovingPhaseModel.C.
References Foam::fvc::ddt(), and Foam::fvc::div().
DUDtf()
template<class BasePhaseModel > Foam::tmp< Foam::surfaceScalarField > DUDtf () const virtual
Definition at line 391 of file MovingPhaseModel.C.
References Foam::byDt().
continuityError()
template<class BasePhaseModel > Foam::tmp< Foam::volScalarField > continuityError () const virtual
Definition at line 404 of file MovingPhaseModel.C.
continuityErrorFlow()
template<class BasePhaseModel > Foam::tmp< Foam::volScalarField > continuityErrorFlow () const virtual
Definition at line 412 of file MovingPhaseModel.C.
continuityErrorSources()
template<class BasePhaseModel > Foam::tmp< Foam::volScalarField > continuityErrorSources () const virtual
Definition at line 420 of file MovingPhaseModel.C.
K()
template<class BasePhaseModel > Foam::tmp< Foam::volScalarField > K () const virtual
Definition at line 428 of file MovingPhaseModel.C.
References IOobject::groupName(), Foam::magSqr(), Foam::name(), GeometricField< scalar, fvPatchField, volMesh >::New(), and U.
divU() [1/2]
template<class BasePhaseModel > Foam::tmp< Foam::volScalarField > divU () const virtual
Definition at line 445 of file MovingPhaseModel.C.
divU() [2/2]
template<class BasePhaseModel > void divU (tmp< volScalarField > divU) virtual
Definition at line 452 of file MovingPhaseModel.C.
References divU.
mut()
template<class BasePhaseModel > Foam::tmp< Foam::volScalarField > mut () const virtual
Definition at line 460 of file MovingPhaseModel.C.
muEff()
template<class BasePhaseModel > Foam::tmp< Foam::volScalarField > muEff () const virtual
Definition at line 468 of file MovingPhaseModel.C.
nut()
template<class BasePhaseModel > Foam::tmp< Foam::volScalarField > nut () const virtual
Definition at line 476 of file MovingPhaseModel.C.
nuEff()
template<class BasePhaseModel > Foam::tmp< Foam::volScalarField > nuEff () const virtual
Definition at line 484 of file MovingPhaseModel.C.
kappaEff() [1/2]
template<class BasePhaseModel > Foam::tmp< Foam::volScalarField > kappaEff () const virtual
Definition at line 492 of file MovingPhaseModel.C.
kappaEff() [2/2]
template<class BasePhaseModel > Foam::tmp< Foam::scalarField > kappaEff (const label patchi) const virtual
Definition at line 500 of file MovingPhaseModel.C.
alphaEff() [1/2]
template<class BasePhaseModel > Foam::tmp< Foam::volScalarField > alphaEff () const virtual
Definition at line 508 of file MovingPhaseModel.C.
alphaEff() [2/2]
template<class BasePhaseModel > Foam::tmp< Foam::scalarField > alphaEff (const label patchi) const virtual
Definition at line 516 of file MovingPhaseModel.C.
k()
template<class BasePhaseModel > Foam::tmp< Foam::volScalarField > k () const virtual
Definition at line 524 of file MovingPhaseModel.C.
pPrime()
template<class BasePhaseModel > Foam::tmp< Foam::volScalarField > pPrime () const virtual
Definition at line 532 of file MovingPhaseModel.C.
Member Data Documentation
U_
template<class BasePhaseModel > volVectorField U_ protected
Definition at line 67 of file MovingPhaseModel.H.
phi_
template<class BasePhaseModel > surfaceScalarField phi_ protected
Definition at line 70 of file MovingPhaseModel.H.
alphaRhoPhi_
template<class BasePhaseModel > surfaceScalarField alphaRhoPhi_ protected
Definition at line 76 of file MovingPhaseModel.H.
DUDt_
template<class BasePhaseModel > tmp<volVectorField> DUDt_ mutable protected
Definition at line 79 of file MovingPhaseModel.H.
DUDtf_
template<class BasePhaseModel > tmp<surfaceScalarField> DUDtf_ mutable protected
Definition at line 82 of file MovingPhaseModel.H.
divU_
template<class BasePhaseModel > tmp<volScalarField> divU_ protected
Definition at line 85 of file MovingPhaseModel.H.
turbulence_
template<class BasePhaseModel > autoPtr<phaseCompressibleTurbulenceModel> turbulence_ protected
Definition at line 88 of file MovingPhaseModel.H.
continuityErrorFlow_
template<class BasePhaseModel > volScalarField continuityErrorFlow_ protected
Definition at line 91 of file MovingPhaseModel.H.
continuityErrorSources_
template<class BasePhaseModel > volScalarField continuityErrorSources_ protected
Definition at line 94 of file MovingPhaseModel.H.
K_
template<class BasePhaseModel > tmp<volScalarField> K_ mutable protected
Definition at line 97 of file MovingPhaseModel.H.
The documentation for this class was generated from the following files:
src/phaseSystemModels/multiphaseInter/phasesSystem/phaseModel/MovingPhaseModel/MovingPhaseModel.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/phaseModel/MovingPhaseModel/MovingPhaseModel.H
src/phaseSystemModels/multiphaseInter/phasesSystem/phaseModel/MovingPhaseModel/MovingPhaseModel.C
src/phaseSystemModels/reactingEuler/multiphaseSystem/phaseModel/MovingPhaseModel/MovingPhaseModel.C