OpenFOAM: ensightMesh Class Reference
ensightMesh Class Reference
Encapsulation of volume meshes for writing in ensight format. It manages cellZones, facesZone, patches.
#include <ensightMesh.H>
Classes
class options
Public Member Functions
ensightMesh (const polyMesh &mesh)
ensightMesh (const polyMesh &mesh, const options &opts)
int verbose () const noexcept
int verbose (const int level) noexcept
const polyMesh & mesh () const noexcept
const ensightMesh::options & option () const
const Map< ensightCells > & cellZoneParts () const noexcept
const Map< ensightFaces > & faceZoneParts () const noexcept
const Map< ensightFaces > & boundaryParts () const noexcept
bool empty () const noexcept
label size () const noexcept
bool needsUpdate () const noexcept
bool expire ()
void correct ()
void write (ensightGeoFile &os, bool parallel=Pstream::parRun()) const
void write (autoPtr< ensightGeoFile > &os, bool parallel=Pstream::parRun()) const
Static Public Attributes
static const label internalZone = -1
Detailed Description
Encapsulation of volume meshes for writing in ensight format. It manages cellZones, facesZone, patches.
When cellZones are present (and not disabled), the cells are grouped in parts according to the zone. Any remaining unzoned cells are placed into the "internalMesh" part, which is always part 0. If cellZones are missing or disabled, all cells are placed into the "internalMesh" part.
If one or more cellZones are explicitly requested, all other cells (including any unzoned cells) are ignored.
The converted patch faces are restricted by the volume mesh coverage. Except when the entire internal mesh has been explicitly suppressed.
Note
The internal data management uses a Map for cellZones, faceZones and patches. The internalMesh is treated as cellZone with a special index.
Since the patches are subsetted by the internal mesh coverage, they are treated as indirect patches rather than regular poly patches.
Source files
ensightMesh.H
ensightMesh.C
ensightMeshI.H
ensightMeshOptions.C
Definition at line 78 of file ensightMesh.H.
Constructor & Destructor Documentation
ensightMesh() [1/2]
ensightMesh (const polyMesh & mesh) explicit
Definition at line 89 of file ensightMesh.C.
ensightMesh() [2/2]
ensightMesh (const polyMesh & mesh, const options & opts)
Definition at line 98 of file ensightMesh.C.
References ensightMesh::correct(), and ensightMesh::option().
Member Function Documentation
verbose() [1/2]
int verbose () const noexcept
Definition at line 118 of file ensightMesh.C.
verbose() [2/2]
int verbose (const int level) noexcept
Definition at line 124 of file ensightMesh.C.
mesh()
const polyMesh & mesh () const inline noexcept
Definition at line 155 of file ensightMesh.H.
Referenced by Foam::writeDimFields(), Foam::ensightOutput::writePointField(), Foam::writePointFields(), and Foam::writeVolFields().
option()
const Foam::ensightMesh::options & option () const inline
Definition at line 23 of file ensightMeshI.H.
Referenced by ensightMesh::ensightMesh().
cellZoneParts()
const Map< ensightCells > & cellZoneParts () const inline noexcept
Definition at line 166 of file ensightMesh.H.
Referenced by Foam::ensightOutput::writePointField(), and Foam::ensightOutput::writeVolField().
faceZoneParts()
const Map< ensightFaces > & faceZoneParts () const inline noexcept
Definition at line 173 of file ensightMesh.H.
Referenced by Foam::ensightOutput::writePointField(), and Foam::ensightOutput::writeVolField().
boundaryParts()
const Map< ensightFaces > & boundaryParts () const inline noexcept
Definition at line 180 of file ensightMesh.H.
Referenced by Foam::ensightOutput::writePointField(), and Foam::ensightOutput::writeVolField().
empty()
bool empty () const inline noexcept
Definition at line 44 of file ensightMeshI.H.
size()
Foam::label size () const inline noexcept
Definition at line 55 of file ensightMeshI.H.
needsUpdate()
bool needsUpdate () const inline noexcept
Definition at line 198 of file ensightMesh.H.
expire()
bool expire () inline
Definition at line 29 of file ensightMeshI.H.
References clear().
correct()
void correct ()
Definition at line 132 of file ensightMesh.C.
References bitSet::any(), ensightCells::classify(), ensightFaces::classify(), clear(), ensightCells::clear(), ensightFaces::clear(), PackedList< Width >::clearStorage(), PackedList< Width >::empty(), UPtrList< T >::empty(), Foam::stringListOps::findMatching(), bitSet::flip(), forAll, ensightPart::identifier(), Foam::identity(), ensightCells::info(), ensightFaces::info(), Foam::Info, bitSet::none(), Foam::nonProcessorPatchNames(), p, patchId(), patchIds, patchNames(), ensightCells::reduce(), ensightFaces::reduce(), ensightPart::rename(), Foam::renumber(), PtrList< T >::resize(), PackedList< Width >::resize(), Foam::returnReduceOr(), bitSet::set(), PtrList< T >::set(), UPtrList< T >::size(), bitSet::test(), and ensightFaces::total().
Referenced by ensightMesh::ensightMesh().
write() [1/2]
void write (ensightGeoFile & os, bool parallel = Pstream::parRun()) const
Definition at line 422 of file ensightMesh.C.
References os().
write() [2/2]
void write (autoPtr< ensightGeoFile > & os, bool parallel = Pstream::parRun()) const inline
Definition at line 66 of file ensightMeshI.H.
References os(), and write().
Member Data Documentation
internalZone
const Foam::label internalZone = -1 static
Definition at line 86 of file ensightMesh.H.
The documentation for this class was generated from the following files:
src/fileFormats/ensight/mesh/ensightMesh.H
src/fileFormats/ensight/mesh/ensightMesh.C
src/fileFormats/ensight/mesh/ensightMeshI.H