OpenFOAM: sphericalAngularDamper Class Reference
sphericalAngularDamper Class Reference
sixDoFRigidBodyMotionRestraints model. Spherical angular damper.
#include <sphericalAngularDamper.H>
Public Member Functions
TypeName ("sphericalAngularDamper")
sphericalAngularDamper (const word &name, const dictionary &sDoFRBMRDict)
virtual autoPtr< sixDoFRigidBodyMotionRestraint > clone () const
virtual ~sphericalAngularDamper ()
virtual void restrain (const sixDoFRigidBodyMotion &motion, vector &restraintPosition, vector &restraintForce, vector &restraintMoment) const
virtual bool read (const dictionary &sDoFRBMRCoeff)
virtual void write (Ostream &) const
Public Member Functions inherited from sixDoFRigidBodyMotionRestraint
TypeName ("sixDoFRigidBodyMotionRestraint")
declareRunTimeSelectionTable (autoPtr, sixDoFRigidBodyMotionRestraint, dictionary,(const word &name, const dictionary &sDoFRBMRDict),(name, sDoFRBMRDict))
sixDoFRigidBodyMotionRestraint (const word &name, const dictionary &sDoFRBMRDict)
virtual ~sixDoFRigidBodyMotionRestraint ()
const word & name () const
const dictionary & coeffDict () const
Additional Inherited Members
Static Public Member Functions inherited from sixDoFRigidBodyMotionRestraint
static autoPtr< sixDoFRigidBodyMotionRestraint > New (const word &name, const dictionary &sDoFRBMRDict)
Protected Attributes inherited from sixDoFRigidBodyMotionRestraint
word name_
dictionary sDoFRBMRCoeffs_
Detailed Description
sixDoFRigidBodyMotionRestraints model. Spherical angular damper.
Source files
sphericalAngularDamper.H
sphericalAngularDamper.C
Definition at line 49 of file sphericalAngularDamper.H.
Constructor & Destructor Documentation
sphericalAngularDamper()
sphericalAngularDamper (const word & name, const dictionary & sDoFRBMRDict)
Definition at line 45 of file sphericalAngularDamper.C.
References Foam::name(), and sphericalAngularDamper::read().
~sphericalAngularDamper()
~sphericalAngularDamper () virtual
Definition at line 61 of file sphericalAngularDamper.C.
Member Function Documentation
TypeName()
TypeName ("sphericalAngularDamper")
clone()
virtual autoPtr< sixDoFRigidBodyMotionRestraint > clone () const inline virtual
Implements sixDoFRigidBodyMotionRestraint.
Definition at line 75 of file sphericalAngularDamper.H.
restrain()
void restrain (const sixDoFRigidBodyMotion & motion, vector & restraintPosition, vector & restraintForce, vector & restraintMoment) const virtual
Implements sixDoFRigidBodyMotionRestraint.
Definition at line 68 of file sphericalAngularDamper.C.
References Foam::endl(), Foam::Info, sixDoFRigidBodyMotion::omega(), sixDoFRigidBodyMotion::report(), and Foam::Zero.
read()
bool read (const dictionary & sDoFRBMRCoeff) virtual
Reimplemented from sixDoFRigidBodyMotionRestraint.
Definition at line 87 of file sphericalAngularDamper.C.
References sixDoFRigidBodyMotionRestraint::read().
Referenced by sphericalAngularDamper::sphericalAngularDamper().
write()
void write (Ostream & os) const virtual
Implements sixDoFRigidBodyMotionRestraint.
Definition at line 100 of file sphericalAngularDamper.C.
References os().
The documentation for this class was generated from the following files:
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/restraints/sphericalAngularDamper/sphericalAngularDamper.H
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/restraints/sphericalAngularDamper/sphericalAngularDamper.C