OpenFOAM: Switch Class Reference
Switch Class Reference
A simple wrapper around bool so that it can be read as a word: true/false, on/off, yes/no, any/none. Also accepts 0/1 as a string and shortcuts t/f, y/n.
#include <Switch.H>
Public Types
enum switchType : unsigned char {
FALSE = 0 , TRUE = 1 , NO = 2 , YES = 3 ,
OFF = 4 , ON = 5 , NONE = 6 , ANY = 7 ,
INVALID = 8
}
Public Member Functions
Switch (const Switch &) noexcept=default
Switch & operator= (const Switch &) noexcept=default
constexpr Switch () noexcept
constexpr Switch (const switchType sw) noexcept
constexpr Switch (const bool b) noexcept
constexpr Switch (const int i) noexcept
Switch (const std::string &str)
Switch (const char *str)
Switch (const float val, const float tol=0.5)
Switch (const double val, const double tol=0.5)
Switch (const token &tok)
Switch (const word &key, const dictionary &dict)
Switch (const word &key, const dictionary &dict, const Switch deflt, const bool failsafe=false)
Switch (Istream &is)
bool good () const noexcept
bool bad () const noexcept
switchType type () const noexcept
void negate () noexcept
const char * c_str () const noexcept
std::string str () const
bool readIfPresent (const word &key, const dictionary &dict)
operator bool () const noexcept
Switch & operator= (const switchType sw) noexcept
Switch & operator= (const bool b) noexcept
Switch (const std::string &str, bool allowBad)
Switch (const char *str, bool allowBad)
FOAM_DEPRECATED_FOR (2019-02, "good() or static contains() method") bool valid() const noexcept
Static Public Member Functions
static Switch getOrAddToDict (const word &key, dictionary &dict, const Switch deflt=switchType::FALSE)
static const char * name (const bool b) noexcept
static bool contains (const std::string &str)
static Switch find (const std::string &str)
static bool found (const std::string &str)
static Switch lookupOrAddToDict (const word &name, dictionary &dict, const Switch deflt=switchType::FALSE)
Detailed Description
A simple wrapper around bool so that it can be read as a word: true/false, on/off, yes/no, any/none. Also accepts 0/1 as a string and shortcuts t/f, y/n.
Source files
Switch.H
Switch.C
Definition at line 77 of file Switch.H.
Member Enumeration Documentation
switchType
enum switchType : unsigned char
Enumerator
FALSE
"false"
TRUE
"true"
NO
"no"
YES
"yes"
OFF
"off"
ON
"on"
NONE
"none"
ANY
"any"
INVALID
"invalid" (output only)
Definition at line 88 of file Switch.H.
Constructor & Destructor Documentation
Switch() [1/15]
Switch (const Switch &) default noexcept
Switch() [2/15]
constexpr Switch () inline constexpr noexcept
Definition at line 127 of file Switch.H.
Switch() [3/15]
constexpr Switch (const switchType sw) inline constexpr noexcept
Definition at line 133 of file Switch.H.
Switch() [4/15]
constexpr Switch (const bool b) inline constexpr noexcept
Definition at line 139 of file Switch.H.
Switch() [5/15]
constexpr Switch (const int i) inline constexpr noexcept
Definition at line 145 of file Switch.H.
Switch() [6/15]
Switch (const std::string & str) explicit
Definition at line 172 of file Switch.C.
Switch() [7/15]
Switch (const char * str) explicit
Definition at line 178 of file Switch.C.
Switch() [8/15]
Switch (const float val, const float tol = 0.5) explicit
Definition at line 196 of file Switch.C.
Switch() [9/15]
Switch (const double val, const double tol = 0.5) explicit
Definition at line 202 of file Switch.C.
Switch() [10/15]
Switch (const token & tok) explicit
Definition at line 208 of file Switch.C.
Switch() [11/15]
Switch (const word & key, const dictionary & dict)
Parameters
key Lookup key. Uses LITERAL (not REGEX)
dict dictionary
Definition at line 230 of file Switch.C.
References dict, Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, keyType::LITERAL, and Foam::printTokenError().
Switch() [12/15]
Switch (const word & key, const dictionary & dict, const Switch deflt, const bool failsafe = false)
Parameters
key Lookup key. Uses LITERAL (not REGEX)
dict dictionary
deflt fallback if not found
failsafe Warn only on bad input
Definition at line 254 of file Switch.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, IOWarningInFunction, keyType::LITERAL, and Foam::printTokenError().
Switch() [13/15]
Switch (Istream & is) explicit
Definition at line 288 of file Switch.C.
Switch() [14/15]
Switch (const std::string & str, bool allowBad)
Definition at line 184 of file Switch.C.
Switch() [15/15]
Switch (const char * str, bool allowBad)
Definition at line 190 of file Switch.C.
Member Function Documentation
operator=() [1/3]
Switch & operator= (const Switch &) default noexcept
getOrAddToDict()
Foam::Switch getOrAddToDict (const word & key, dictionary & dict, const Switch deflt = switchType::FALSE) static
Parameters
key Lookup key. Uses LITERAL (not REGEX)
dict dictionary
deflt default value to add
Definition at line 159 of file Switch.C.
References dict, dictionary::getOrAdd(), and keyType::LITERAL.
Referenced by Switch::lookupOrAddToDict().
name()
const char * name (const bool b) static noexcept
Definition at line 141 of file Switch.C.
References b.
Referenced by surfaceNoise::calculate(), debugWriter::debugWriter(), boolEntry::evaluate(), fvExprDriver::getOrReadFieldImpl(), Switch::lookupOrAddToDict(), argList::parse(), ensightMesh::options::print(), mappedPatchBase::write(), profilingInformation::write(), and attachDetach::writeDict().
contains()
bool contains (const std::string & str) static
Definition at line 153 of file Switch.C.
Referenced by Switch::found().
find()
Foam::Switch find (const std::string & str) static
Definition at line 147 of file Switch.C.
Referenced by IOstreamOption::compressionEnum(), isoSurfaceParams::getFilterType(), isTrue(), scalarRange::parse(), and error::useAbort().
good()
bool good () const noexcept
Definition at line 296 of file Switch.C.
Referenced by Switch::bad(), Switch::FOAM_DEPRECATED_FOR(), and isTrue().
bad()
bool bad () const inline noexcept
Definition at line 225 of file Switch.H.
References Switch::good().
type()
Foam::Switch::switchType type () const noexcept
Definition at line 302 of file Switch.C.
negate()
void negate () noexcept
Definition at line 308 of file Switch.C.
c_str()
const char * c_str () const noexcept
Definition at line 318 of file Switch.C.
str()
std::string str () const
Definition at line 324 of file Switch.C.
Referenced by Switch::found().
readIfPresent()
bool readIfPresent (const word & key, const dictionary & dict)
Parameters
key Lookup key. Uses LITERAL (not REGEX)
dict dictionary
Definition at line 330 of file Switch.C.
References dict, keyType::LITERAL, and dictionary::readIfPresent().
Referenced by adjointkOmegaSST::read(), qZeta::read(), regionModel1D::regionModel1D(), and regionModel1D::regionModel1D().
operator bool()
operator bool () const inline noexcept
Definition at line 251 of file Switch.H.
operator=() [2/3]
Switch & operator= (const switchType sw) inline noexcept
Definition at line 257 of file Switch.H.
operator=() [3/3]
Switch & operator= (const bool b) inline noexcept
Definition at line 264 of file Switch.H.
References b, Switch::FALSE, and Switch::TRUE.
found()
static bool found (const std::string & str) inline static
Definition at line 274 of file Switch.H.
References Switch::contains(), and Switch::str().
FOAM_DEPRECATED_FOR()
FOAM_DEPRECATED_FOR (2019- 02, "good() or static contains() method") const inline noexcept
Definition at line 288 of file Switch.H.
References Switch::good().
lookupOrAddToDict()
static Switch lookupOrAddToDict (const word & name, dictionary & dict, const Switch deflt = switchType::FALSE) inline static
Definition at line 292 of file Switch.H.
References dict, Switch::getOrAddToDict(), and Switch::name().
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/bools/Switch/Switch.H
src/OpenFOAM/primitives/bools/Switch/Switch.C