OpenFOAM: populationBalanceModel Class Reference
populationBalanceModel Class Reference
Class that solves the univariate population balance equation by means of a class method (also called sectional or discrete method). The internal coordinate is set to the particle volume, so the equation is based on a transport equation of the volume-based number density function. The discretization is done using the fixed pivot technique of Kumar and Ramkrishna (1996). The source terms are written in a way that particle number and mass are preserved. Coalescence (aggregation), breakup, drift (growth and surface loss) as well as nucleation are supported. For the discrete breakup term two recipes are available, depending on the model choice. For models which state a total breakup rate and a separate daughter size distribution function, the formulation of Kumar and Ramkrishna (1996) is applied which is applicable for binary and multiple breakup events. The second formulation is given by Liao et al. (2018). It is useful for binary breakup models which give the breakup rate between a sizeGroup pair directly, without an explicit expression for the daughter size distribution. The drift term is implemented using a finite difference upwind scheme. Although it is diffusive, it ensures a stable and number-conservative solution.
#include <populationBalanceModel.H>
Classes
class iNew
Public Member Functions
populationBalanceModel (const phaseSystem &fluid, const word &name, HashPtrTable< volScalarField, phasePairKey, phasePairKey::hash > &pDmdt)
autoPtr< populationBalanceModel > clone () const
virtual ~populationBalanceModel ()
bool writeData (Ostream &) const
const phaseSystem & fluid () const
const fvMesh & mesh () const
const dictionary & dict () const
const phaseModel & continuousPhase () const
const UPtrList< velocityGroup > & velocityGroups () const
const UPtrList< sizeGroup > & sizeGroups () const
const phasePairTable & phasePairs () const
const PtrList< dimensionedScalar > & v () const
const volScalarField & alphas () const
const volVectorField & U () const
const dimensionedScalar gamma (const label i, const dimensionedScalar &v) const
const tmp< volScalarField > sigmaWithContinuousPhase (const phaseModel &dispersedPhase) const
const phaseCompressibleTurbulenceModel & continuousTurbulence () const
void solve ()
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
regIOobject (const IOobject &io, const bool isTimeObject=false)
regIOobject (const regIOobject &rio)
regIOobject (const regIOobject &rio, bool registerCopy)
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
regIOobject (const IOobject &io, const regIOobject &rio)
virtual ~regIOobject ()
bool checkIn ()
bool checkOut ()
virtual void addWatch ()
bool registered () const noexcept
bool ownedByRegistry () const noexcept
bool store ()
void release (const bool unregister=false) noexcept
label eventNo () const noexcept
label & eventNo () noexcept
bool upToDate (const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
void setUpToDate ()
virtual void rename (const word &newName)
const dictionary * findMetaData () const noexcept
dictionary & getMetaData () noexcept
void removeMetaData ()
virtual void updateMetaData ()
virtual fileName filePath () const
bool headerOk ()
Istream & readStream (const word &, const bool readOnProc=true)
void close ()
virtual bool readData (Istream &)
virtual bool read ()
virtual label addWatch (const fileName &)
const labelList & watchIndices () const noexcept
labelList & watchIndices () noexcept
virtual bool modified () const
virtual bool readIfModified ()
virtual bool writeObject (IOstreamOption streamOpt, const bool writeOnProc) const
virtual bool write (const bool writeOnProc=true) const
virtual bool global () const
void operator= (const IOobject &io)
virtual bool writeObject (IOstreamOption::streamFormat fmt, IOstreamOption::versionNumber ver, IOstreamOption::compressionType cmp, const bool writeOnProc) const
Public Member Functions inherited from IOobject
TypeName ("IOobject")
IOobject (const IOobject &)=default
virtual ~IOobject ()=default
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const fileName &path, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const fileName &path, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const IOobject &io, const objectRegistry &registry)
IOobject (const IOobject &io, const word &name)
IOobject (const IOobject &io, const word &name, const fileName &local)
IOobject (const IOobject &io, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt)
IOobject (const IOobject &io, IOobjectOption::registerOption regOpt)
autoPtr< IOobject > clone () const
autoPtr< IOobject > clone (const objectRegistry &registry) const
const objectRegistry & db () const noexcept
const Time & time () const noexcept
const word & name () const noexcept
const word & headerClassName () const noexcept
word & headerClassName () noexcept
const string & note () const noexcept
string & note () noexcept
unsigned labelByteSize () const noexcept
unsigned scalarByteSize () const noexcept
void resetHeader (const word &newName=word::null)
bool hasHeaderClass () const noexcept
template<class Type >
bool isHeaderClass () const
template<class Type >
bool isHeaderClassName () const
word group () const
word member () const
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const noexcept
fileName & instance () noexcept
const fileName & local () const noexcept
fileName path () const
fileName path (const word &instance, const fileName &local=fileName::null) const
fileName objectPath () const
fileName objectRelPath () const
fileName localFilePath (const word &typeName, const bool search=true) const
fileName globalFilePath (const word &typeName, const bool search=true) const
IOstreamOption parseHeader (const dictionary &headerDict)
bool readHeader (Istream &is)
bool readHeader (dictionary &headerDict, Istream &is)
template<class Type >
bool typeHeaderOk (const bool checkType=true, const bool search=true, const bool verbose=true)
template<class Type >
void warnNoRereading () const
bool writeHeader (Ostream &os) const
bool writeHeader (Ostream &os, const word &objectType) const
void writeHeader (dictionary &dict, IOstreamOption streamOpt) const
void writeHeader (dictionary &dict, const word &objectType, IOstreamOption streamOpt) const
bool good () const noexcept
bool bad () const noexcept
InfoProxy< IOobject > info () const noexcept
void operator= (const IOobject &io)
template<>
bool isHeaderClass () const
template<class StringType >
Foam::word groupName (StringType base, const word &group)
Public Member Functions inherited from IOobjectOption
constexpr IOobjectOption (readOption rOpt=readOption::NO_READ, writeOption wOpt=writeOption::NO_WRITE, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (readOption rOpt, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (writeOption wOpt, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (registerOption registerObject, bool globalObject=false) noexcept
constexpr IOobjectOption (readOption rOpt, writeOption wOpt, bool registerObject, bool globalObject=false) noexcept
constexpr IOobjectOption (bool registerObject, bool globalObject=false) noexcept
readOption readOpt () const noexcept
readOption readOpt (readOption opt) noexcept
writeOption writeOpt () const noexcept
writeOption writeOpt (writeOption opt) noexcept
bool registerObject () const noexcept
bool registerObject (bool on) noexcept
bool globalObject () const noexcept
bool globalObject (bool on) noexcept
bool isAnyRead () const noexcept
bool isReadRequired () const noexcept
bool isReadOptional () const noexcept
readOption & readOpt () noexcept
writeOption & writeOpt () noexcept
bool & registerObject () noexcept
bool & globalObject () noexcept
Friends
class sizeGroup
class velocityGroup
Additional Inherited Members
Public Types inherited from IOobject
enum objectState : char { GOOD , BAD }
enum fileCheckTypes : char { timeStamp , timeStampMaster , inotify , inotifyMaster }
Public Types inherited from IOobjectOption
enum readOption : unsigned char {
NO_READ = 0 , MUST_READ = 0x1 , READ_MODIFIED = 0x3 , MUST_READ_IF_MODIFIED = 0x3 ,
LAZY_READ = 0x4 , READ_IF_PRESENT = 0x4
}
enum writeOption : unsigned char { NO_WRITE = 0 , AUTO_WRITE = 0x10 }
enum registerOption : unsigned char { NO_REGISTER = 0 , REGISTER = 1 }
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *p)
template<class Type >
static Type & store (autoPtr< Type > &ptr)
template<class Type >
static Type & store (autoPtr< Type > &&ptr)
template<class Type >
static Type & store (refPtr< Type > &ptr)
template<class Type >
static Type & store (refPtr< Type > &&ptr)
template<class Type >
static Type & store (tmp< Type > &ptr)
template<class Type >
static Type & store (tmp< Type > &&ptr)
Static Public Member Functions inherited from IOobject
static bool bannerEnabled () noexcept
static bool bannerEnabled (bool on) noexcept
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
template<class StringType >
static word groupName (StringType base, const word &group)
static word group (const word &name)
static word member (const word &name)
static word scopedName (const std::string &scope, const word &name)
static IOobject selectIO (const IOobject &io, const fileName &altFile, const word &ioName="")
static Ostream & writeBanner (Ostream &os, const bool noSyntaxHint=false)
static Ostream & writeDivider (Ostream &os)
static Ostream & writeEndDivider (Ostream &os)
Static Public Member Functions inherited from IOobjectOption
static bool isAnyRead (readOption opt) noexcept
static bool isReadRequired (readOption opt) noexcept
static bool isReadOptional (readOption opt) noexcept
static readOption lazierRead (readOption opt) noexcept
Static Public Attributes inherited from IOobject
static const Enum< fileCheckTypes > fileCheckTypesNames
static char scopeSeparator
static fileCheckTypes fileModificationChecking
static float fileModificationSkew
static int maxFileModificationPolls
Protected Member Functions inherited from regIOobject
bool readHeaderOk (const IOstreamOption::streamFormat fmt, const word &typeName)
Protected Member Functions inherited from IOobject
void setBad (const string &s)
Static Protected Member Functions inherited from IOobject
static void writeHeaderContent (Ostream &os, const IOobject &io, const word &objectType, const dictionary *metaDataDict=nullptr)
static void writeHeaderContent (dictionary &dict, const IOobject &io, const word &objectType, IOstreamOption streamOpt, const dictionary *metaDataDict=nullptr)
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
Detailed Description
Class that solves the univariate population balance equation by means of a class method (also called sectional or discrete method). The internal coordinate is set to the particle volume, so the equation is based on a transport equation of the volume-based number density function. The discretization is done using the fixed pivot technique of Kumar and Ramkrishna (1996). The source terms are written in a way that particle number and mass are preserved. Coalescence (aggregation), breakup, drift (growth and surface loss) as well as nucleation are supported. For the discrete breakup term two recipes are available, depending on the model choice. For models which state a total breakup rate and a separate daughter size distribution function, the formulation of Kumar and Ramkrishna (1996) is applied which is applicable for binary and multiple breakup events. The second formulation is given by Liao et al. (2018). It is useful for binary breakup models which give the breakup rate between a sizeGroup pair directly, without an explicit expression for the daughter size distribution. The drift term is implemented using a finite difference upwind scheme. Although it is diffusive, it ensures a stable and number-conservative solution.
The implementation allows to split the population balance over multiple velocity fields using the capability of reactingMultiphaseEulerFoam to solve for n momentum equations. It is also possible to define multiple population balances, e.g. bubbles and droplets simultaneously.
References:
    Coalescence and breakup term formulation:
    Kumar, S., & Ramkrishna, D. (1996).
    On the solution of population balance equations by discretization-I. A
    fixed pivot technique.
    Chemical Engineering Science, 51(8), 1311-1332.
    Binary breakup term formulation:
    Liao, Y., Oertel, R., Kriebitzsch, S., Schlegel, F., & Lucas, D. (2018).
    A discrete population balance equation for binary breakage.
    International Journal for Numerical Methods in Fluids, 87(4), 202-215.
Usage
Example excerpt from a phaseProperties dictionary.
type populationBalanceTwoPhaseSystem;
phases (air water);
populationBalances (bubbles);
air
{
    type            purePhaseModel;
    diameterModel   velocityGroup;
    velocityGroupCoeffs
    {
        populationBalance    bubbles;
        formFactor      0.5235987756;
        sizeGroups
        (
            f0{d  1.00e-3; value 0;}
            f1{d  1.08e-3; value 0;}
            f2{d  1.16e-3; value 0.25;}
            f3{d  1.25e-3; value 0.5;}
            f4{d  1.36e-3; value 0.25;}
            f5{d  1.46e-3; value 0;}
            ...
        );
    }
    residualAlpha   1e-6;
}
populationBalanceCoeffs
{
    bubbles
    {
        continuousPhase water;
        coalescenceModels
        (
            hydrodynamic
            {
                C 0.25;
            }
        );
        binaryBreakupModels
        ();
        breakupModels
        (
            exponential
            {
                C 0.5;
                exponent 0.01;
                daughterSizeDistributionModel uniformBinary;
            }
        );
        driftModels
        (
            densityChange{}
        );
        nucleationModels
        ();
    }
}
See also
Foam::diameterModels::sizeGroup Foam::diameterModels::velocityGroup
Source files
populationBalanceModel.H
populationBalanceModel.C
Definition at line 175 of file populationBalanceModel.H.
Constructor & Destructor Documentation
populationBalanceModel()
populationBalanceModel (const phaseSystem & fluid, const word & name, HashPtrTable< volScalarField, phasePairKey, phasePairKey::hash > & pDmdt)
Definition at line 845 of file populationBalanceModel.C.
References IOobjectOption::AUTO_WRITE, Foam::dimLength, Foam::dimless, Foam::dimTime, Foam::dimVelocity, Foam::dimVolume, Foam::exit(), Foam::FatalError, FatalErrorInFunction, IOobject::groupName(), Foam::inv(), IOobject::name(), IOobjectOption::NO_READ, UPtrList< T >::size(), and Foam::Zero.
~populationBalanceModel()
~populationBalanceModel () virtual
Definition at line 1134 of file populationBalanceModel.C.
Member Function Documentation
clone()
Foam::autoPtr< Foam::diameterModels::populationBalanceModel > clone () const
Definition at line 1141 of file populationBalanceModel.C.
References NotImplemented.
writeData()
bool writeData (Ostream & os) const virtual
Implements regIOobject.
Definition at line 1148 of file populationBalanceModel.C.
References os().
fluid()
const Foam::phaseSystem & fluid () const inline
Definition at line 42 of file populationBalanceModelI.H.
mesh()
const Foam::fvMesh & mesh () const inline
Definition at line 49 of file populationBalanceModelI.H.
dict()
const Foam::dictionary & dict () const inline
Definition at line 56 of file populationBalanceModelI.H.
continuousPhase()
const Foam::phaseModel & continuousPhase () const inline
Definition at line 63 of file populationBalanceModelI.H.
velocityGroups()
const Foam::UPtrList< Foam::diameterModels::velocityGroup > & velocityGroups () const inline
Definition at line 70 of file populationBalanceModelI.H.
sizeGroups()
const Foam::UPtrList< Foam::diameterModels::sizeGroup > & sizeGroups () const inline
Definition at line 77 of file populationBalanceModelI.H.
phasePairs()
const Foam::diameterModels::populationBalanceModel::phasePairTable & phasePairs () const inline
Definition at line 84 of file populationBalanceModelI.H.
Referenced by PopulationBalancePhaseSystem< BasePhaseSystem >::PopulationBalancePhaseSystem().
v()
const Foam::PtrList< Foam::dimensionedScalar > & v () const inline
Definition at line 91 of file populationBalanceModelI.H.
alphas()
const Foam::volScalarField & alphas () const inline
Definition at line 98 of file populationBalanceModelI.H.
U()
const Foam::volVectorField & U () const inline
Definition at line 112 of file populationBalanceModelI.H.
gamma()
const Foam::dimensionedScalar gamma (const label i, const dimensionedScalar & v) const
Definition at line 1155 of file populationBalanceModel.C.
References UPtrList< T >::size(), and dimensioned< Type >::value().
sigmaWithContinuousPhase()
const Foam::tmp< Foam::volScalarField > sigmaWithContinuousPhase (const phaseModel & dispersedPhase) const
Definition at line 1199 of file populationBalanceModel.C.
continuousTurbulence()
const Foam::phaseCompressibleTurbulenceModel & continuousTurbulence () const
Definition at line 1213 of file populationBalanceModel.C.
References IOobject::groupName(), and turbulenceModel::propertiesName.
solve()
void solve ()
Definition at line 1227 of file populationBalanceModel.C.
References alpha, correct(), Foam::fvc::ddt(), Foam::fvm::ddt(), Foam::fvc::div(), Foam::endl(), forAll, UPtrList< T >::get(), Foam::Info, Foam::max(), mesh, Foam::name(), nCorr, rho, phase::rho(), Foam::fvm::Sp(), Foam::fvc::Su(), Foam::fvm::SuSp(), and DimensionedField< Type, GeoMesh >::weightedAverage().
Friends And Related Symbol Documentation
sizeGroup
friend class sizeGroup friend
Definition at line 331 of file populationBalanceModel.H.
velocityGroup
friend class velocityGroup friend
Definition at line 332 of file populationBalanceModel.H.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/populationBalanceModel/populationBalanceModel/populationBalanceModel.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/populationBalanceModel/populationBalanceModel/populationBalanceModel.C
src/phaseSystemModels/reactingEuler/multiphaseSystem/populationBalanceModel/populationBalanceModel/populationBalanceModelI.H