OpenFOAM: coupleGroupIdentifier Class Reference
coupleGroupIdentifier Class Reference
Encapsulates using "patchGroups" to specify coupled patch.
#include <coupleGroupIdentifier.H>
Public Member Functions
coupleGroupIdentifier ()=default
coupleGroupIdentifier (const word &patchGroupName)
coupleGroupIdentifier (const dictionary &dict)
const word & name () const noexcept
bool valid () const noexcept
label findOtherPatchID (const polyPatch &thisPatch) const
label findOtherPatchID (const polyPatch &thisPatch, word &otherRegion) const
void write (Ostream &os) const
Detailed Description
Encapsulates using "patchGroups" to specify coupled patch.
Source files
coupleGroupIdentifier.H
coupleGroupIdentifier.C
Definition at line 53 of file coupleGroupIdentifier.H.
Constructor & Destructor Documentation
coupleGroupIdentifier() [1/3]
coupleGroupIdentifier () default
coupleGroupIdentifier() [2/3]
coupleGroupIdentifier (const word & patchGroupName) inline explicit
Definition at line 83 of file coupleGroupIdentifier.H.
coupleGroupIdentifier() [3/3]
coupleGroupIdentifier (const dictionary & dict) explicit
Definition at line 126 of file coupleGroupIdentifier.C.
References dict, and dictionary::readIfPresent().
Member Function Documentation
name()
const word & name () const inline noexcept
Definition at line 95 of file coupleGroupIdentifier.H.
valid()
bool valid () const inline noexcept
Definition at line 101 of file coupleGroupIdentifier.H.
findOtherPatchID() [1/2]
Foam::label findOtherPatchID (const polyPatch & thisPatch) const
Definition at line 134 of file coupleGroupIdentifier.C.
References pbm.
findOtherPatchID() [2/2]
Foam::label findOtherPatchID (const polyPatch & thisPatch, word & otherRegion) const
Definition at line 145 of file coupleGroupIdentifier.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAllConstIters, objectRegistry::lookupClass(), mesh, fvMesh::name(), Foam::name(), patchID, pbm, and runTime.
write()
void write (Ostream & os) const
Definition at line 204 of file coupleGroupIdentifier.C.
References os(), and Ostream::writeEntry().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/Identifiers/patch/coupleGroupIdentifier.H
src/OpenFOAM/meshes/Identifiers/patch/coupleGroupIdentifier.C