OpenFOAM: displacementMethod Class Reference
displacementMethod Class Reference abstract
Abstract base class for displacement methods, which are a set or wrapper classes allowing to change the driving force of mesh motion solvers.
#include <displacementMethod.H>
Public Member Functions
TypeName ("displacementMethod")
declareRunTimeSelectionTable (autoPtr, displacementMethod, dictionary,(fvMesh &mesh, const labelList &patchIDs),(mesh, patchIDs))
displacementMethod (fvMesh &mesh, const labelList &patchIDs)
virtual ~displacementMethod ()=default
virtual void setMotionField (const pointVectorField &pointMovement)=0
virtual void setMotionField (const volVectorField &cellMovement)=0
virtual void setControlField (const vectorField &controlField)=0
virtual void setControlField (const scalarField &controlField)=0
virtual void boundControlField (vectorField &controlField)
autoPtr< motionSolver > & getMotionSolver ()
scalar getMaxDisplacement () const
void update ()
Static Public Member Functions
static autoPtr< displacementMethod > New (fvMesh &mesh, const labelList &patchIDs)
Protected Attributes
fvMesh & mesh_
const labelList & patchIDs_
autoPtr< motionSolver > motionPtr_
scalar maxDisplacement_
Detailed Description
Abstract base class for displacement methods, which are a set or wrapper classes allowing to change the driving force of mesh motion solvers.
Source files
displacementMethod.H
displacementMethod.C
Definition at line 55 of file displacementMethod.H.
Constructor & Destructor Documentation
displacementMethod()
displacementMethod (fvMesh & mesh, const labelList & patchIDs)
Definition at line 36 of file displacementMethod.C.
References Foam::New().
~displacementMethod()
virtual ~displacementMethod () virtual default
Member Function Documentation
TypeName()
TypeName ("displacementMethod")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , displacementMethod , dictionary , (fvMesh &mesh, const labelList &patchIDs) , (mesh, patchIDs))
New()
Foam::autoPtr< Foam::displacementMethod > New (fvMesh & mesh, const labelList & patchIDs) static
Definition at line 51 of file displacementMethod.C.
References Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, UPtrList< T >::get(), Foam::Info, mesh, IOobjectOption::MUST_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, patchIDs(), and fvMesh::time().
setMotionField() [1/2]
virtual void setMotionField (const pointVectorField & pointMovement) pure virtual
Implemented in displacementMethoddisplacementLaplacian, displacementMethodelasticityMotionSolver, displacementMethodlaplacianMotionSolver, displacementMethodvelocityLaplacian, and displacementMethodvolumetricBSplinesMotionSolver.
setMotionField() [2/2]
virtual void setMotionField (const volVectorField & cellMovement) pure virtual
Implemented in displacementMethoddisplacementLaplacian, displacementMethodelasticityMotionSolver, displacementMethodlaplacianMotionSolver, displacementMethodvelocityLaplacian, and displacementMethodvolumetricBSplinesMotionSolver.
setControlField() [1/2]
virtual void setControlField (const vectorField & controlField) pure virtual
Implemented in displacementMethoddisplacementLaplacian, displacementMethodelasticityMotionSolver, displacementMethodlaplacianMotionSolver, displacementMethodvelocityLaplacian, and displacementMethodvolumetricBSplinesMotionSolver.
setControlField() [2/2]
virtual void setControlField (const scalarField & controlField) pure virtual
Implemented in displacementMethoddisplacementLaplacian, displacementMethodelasticityMotionSolver, displacementMethodlaplacianMotionSolver, displacementMethodvelocityLaplacian, and displacementMethodvolumetricBSplinesMotionSolver.
boundControlField()
void boundControlField (vectorField & controlField) virtual
Reimplemented in displacementMethodvolumetricBSplinesMotionSolver.
Definition at line 93 of file displacementMethod.C.
getMotionSolver()
Foam::autoPtr< Foam::motionSolver > & getMotionSolver ()
Definition at line 99 of file displacementMethod.C.
getMaxDisplacement()
Foam::scalar getMaxDisplacement () const
Definition at line 105 of file displacementMethod.C.
update()
void update ()
Definition at line 111 of file displacementMethod.C.
References Foam::endl(), Foam::gMax(), Foam::Info, and Foam::mag().
Member Data Documentation
mesh_
fvMesh& mesh_ protected
Definition at line 61 of file displacementMethod.H.
Referenced by displacementMethodelasticityMotionSolver::setMotionField().
patchIDs_
const labelList& patchIDs_ protected
Definition at line 64 of file displacementMethod.H.
Referenced by displacementMethoddisplacementLaplacian::setMotionField(), displacementMethodelasticityMotionSolver::setMotionField(), displacementMethodlaplacianMotionSolver::setMotionField(), displacementMethodvelocityLaplacian::setMotionField(), and displacementMethodelasticityMotionSolver::setMotionField().
motionPtr_
autoPtr<motionSolver> motionPtr_ protected
Definition at line 66 of file displacementMethod.H.
Referenced by displacementMethodvolumetricBSplinesMotionSolver::boundControlField(), and displacementMethodvolumetricBSplinesMotionSolver::setControlField().
maxDisplacement_
scalar maxDisplacement_ protected
Definition at line 68 of file displacementMethod.H.
Referenced by displacementMethoddisplacementLaplacian::setMotionField(), displacementMethodelasticityMotionSolver::setMotionField(), displacementMethodlaplacianMotionSolver::setMotionField(), displacementMethodvelocityLaplacian::setMotionField(), and displacementMethodelasticityMotionSolver::setMotionField().
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/displacementMethod/displacementMethod/displacementMethod.H
src/optimisation/adjointOptimisation/adjoint/displacementMethod/displacementMethod/displacementMethod.C