OpenFOAM: Tensor2D< Cmpt > Class Template Reference
Tensor2D< Cmpt > Class Template Reference
A templated (2 x 2) tensor of objects of <T> derived from VectorSpace.
#include <Tensor2D.H>
Public Types
enum components { XX , XY , YX , YY }
typedef Tensor2D< label > labelType
Public Types inherited from VectorSpace< Tensor2D< Cmpt >, Cmpt, 4 >
typedef VectorSpace< Tensor2D< Cmpt >, Cmpt, Ncmpts > vsType
typedef Cmpt cmptType
typedef Cmpt magType
typedef Cmpt * iterator
typedef const Cmpt * const_iterator
Public Member Functions
Tensor2D ()=default
Tensor2D (const Tensor2D &)=default
Tensor2D & operator= (const Tensor2D &)=default
Tensor2D (const Foam::zero)
Tensor2D (const VectorSpace< Tensor2D< Cmpt >, Cmpt, 4 > &vs)
Tensor2D (const SymmTensor2D< Cmpt > &st)
Tensor2D (const SphericalTensor2D< Cmpt > &st)
Tensor2D (const Vector2D< Cmpt > &x, const Vector2D< Cmpt > &y)
Tensor2D (const Cmpt txx, const Cmpt txy, const Cmpt tyx, const Cmpt tyy)
Tensor2D (Istream &is)
const Cmpt & xx () const noexcept
const Cmpt & xy () const noexcept
const Cmpt & yx () const noexcept
const Cmpt & yy () const noexcept
Cmpt & xx () noexcept
Cmpt & xy () noexcept
Cmpt & yx () noexcept
Cmpt & yy () noexcept
Vector2D< Cmpt > cx () const
Vector2D< Cmpt > cy () const
template<direction Idx>
Vector2D< Cmpt > col () const
Vector2D< Cmpt > col (const direction c) const
template<direction Idx>
void col (const Vector2D< Cmpt > &v)
void col (const direction c, const Vector2D< Cmpt > &v)
void cols (const Vector2D< Cmpt > &x, const Vector2D< Cmpt > &y)
Vector2D< Cmpt > x () const
Vector2D< Cmpt > y () const
template<direction Idx>
Vector2D< Cmpt > row () const
Vector2D< Cmpt > row (const direction r) const
template<direction Idx>
void row (const Vector2D< Cmpt > &v)
void row (const direction r, const Vector2D< Cmpt > &v)
void rows (const Vector2D< Cmpt > &x, const Vector2D< Cmpt > &y)
Vector2D< Cmpt > diag () const
void diag (const Vector2D< Cmpt > &v)
scalar diagSqr () const
Tensor2D< Cmpt > T () const
Cmpt det () const
Tensor2D< Cmpt > adjunct () const
Tensor2D< Cmpt > cof () const
Tensor2D< Cmpt > inv () const
Tensor2D< Cmpt > inner (const Tensor2D< Cmpt > &t2) const
Tensor2D< Cmpt > schur (const Tensor2D< Cmpt > &t2) const
void operator= (const SymmTensor2D< Cmpt > &)
void operator= (const SphericalTensor2D< Cmpt > &)
Vector2D< Cmpt > vectorComponent (const direction cmpt) const
template<Foam::direction Idx>
Foam::Vector2D< Cmpt > col () const
template<Foam::direction Idx>
Foam::Vector2D< Cmpt > row () const
Public Member Functions inherited from VectorSpace< Tensor2D< Cmpt >, Cmpt, 4 >
VectorSpace ()=default
VectorSpace (const Foam::zero)
VectorSpace (const VectorSpace< Tensor2D< Cmpt >, Cmpt, Ncmpts > &vs)
VectorSpace (const VectorSpace< Form2, Cmpt2, Ncmpts > &)
VectorSpace (Istream &is)
const Cmpt & component (const direction) const
Cmpt & component (const direction)
void component (Cmpt &, const direction) const
void replace (const direction, const Cmpt &)
const Cmpt * cdata () const noexcept
Cmpt * data () noexcept
const ConstBlock< SubVector, BStart > block () const
const Foam::VectorSpace< Tensor2D< Cmpt >, Cmpt, Ncmpts >::template ConstBlock< SubVector, BStart > block () const
const Cmpt & operator[] (const direction) const
Cmpt & operator[] (const direction)
void operator= (const VectorSpace< Tensor2D< Cmpt >, Cmpt, Ncmpts > &)
void operator= (const Foam::zero)
void operator+= (const VectorSpace< Tensor2D< Cmpt >, Cmpt, Ncmpts > &)
void operator-= (const VectorSpace< Tensor2D< Cmpt >, Cmpt, Ncmpts > &)
void operator*= (const scalar)
void operator/= (const scalar)
iterator begin () noexcept
const_iterator begin () const noexcept
iterator end () noexcept
const_iterator end () const noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
Static Public Attributes
static constexpr direction rank = 2
static const Tensor2D I
Static Public Attributes inherited from VectorSpace< Tensor2D< Cmpt >, Cmpt, 4 >
static constexpr direction dim
static constexpr direction nComponents
static constexpr direction mRows
static constexpr direction nCols
static const char *const typeName
static const char *const componentNames []
static const Tensor2D< Cmpt > zero
static const Tensor2D< Cmpt > one
static const Tensor2D< Cmpt > max
static const Tensor2D< Cmpt > min
static const Tensor2D< Cmpt > rootMax
static const Tensor2D< Cmpt > rootMin
Additional Inherited Members
Static Public Member Functions inherited from VectorSpace< Tensor2D< Cmpt >, Cmpt, 4 >
static constexpr direction size () noexcept
static Tensor2D< Cmpt > uniform (const Cmpt &s)
Public Attributes inherited from VectorSpace< Tensor2D< Cmpt >, Cmpt, 4 >
Cmpt v_ [Ncmpts]
Detailed Description
template<class Cmpt>
class Foam::Tensor2D< Cmpt >
A templated (2 x 2) tensor of objects of <T> derived from VectorSpace.
Source files
Tensor2D.H
Tensor2DI.H
Definition at line 52 of file Tensor2D.H.
Member Typedef Documentation
labelType
template<class Cmpt > typedef Tensor2D<label> labelType
Definition at line 61 of file Tensor2D.H.
Member Enumeration Documentation
components
template<class Cmpt > enum components
Enumerator
XX
XY
YX
YY
Definition at line 76 of file Tensor2D.H.
Constructor & Destructor Documentation
Tensor2D() [1/9]
template<class Cmpt > Tensor2D () default
Tensor2D() [2/9]
template<class Cmpt > Tensor2D (const Tensor2D< Cmpt > &) default
Tensor2D() [3/9]
template<class Cmpt > Tensor2D (const Foam::zero) inline
Definition at line 25 of file Tensor2DI.H.
Tensor2D() [4/9]
template<class Cmpt > Tensor2D (const VectorSpace< Tensor2D< Cmpt >, Cmpt, 4 > & vs) inline
Definition at line 32 of file Tensor2DI.H.
Tensor2D() [5/9]
template<class Cmpt > Tensor2D (const SymmTensor2D< Cmpt > & st) inline
Definition at line 42 of file Tensor2DI.H.
Tensor2D() [6/9]
template<class Cmpt > Tensor2D (const SphericalTensor2D< Cmpt > & st) inline
Definition at line 50 of file Tensor2DI.H.
References Foam::Zero.
Tensor2D() [7/9]
template<class Cmpt > Tensor2D (const Vector2D< Cmpt > & x, const Vector2D< Cmpt > & y) inline
Definition at line 58 of file Tensor2DI.H.
References x, and y.
Tensor2D() [8/9]
template<class Cmpt > Tensor2D (const Cmpt txx, const Cmpt txy, const Cmpt tyx, const Cmpt tyy) inline
Definition at line 70 of file Tensor2DI.H.
Tensor2D() [9/9]
template<class Cmpt > Tensor2D (Istream & is) inline explicit
Definition at line 82 of file Tensor2DI.H.
Member Function Documentation
operator=() [1/3]
template<class Cmpt > Tensor2D & operator= (const Tensor2D< Cmpt > &) default
xx() [1/2]
template<class Cmpt > const Cmpt & xx () const inline noexcept
Definition at line 127 of file Tensor2D.H.
References VectorSpace< Tensor2D< Cmpt >, Cmpt, 4 >::v_, and Tensor2D< Cmpt >::XX.
xy() [1/2]
template<class Cmpt > const Cmpt & xy () const inline noexcept
Definition at line 128 of file Tensor2D.H.
References VectorSpace< Tensor2D< Cmpt >, Cmpt, 4 >::v_, and Tensor2D< Cmpt >::XY.
yx() [1/2]
template<class Cmpt > const Cmpt & yx () const inline noexcept
Definition at line 129 of file Tensor2D.H.
References VectorSpace< Tensor2D< Cmpt >, Cmpt, 4 >::v_, and Tensor2D< Cmpt >::YX.
yy() [1/2]
template<class Cmpt > const Cmpt & yy () const inline noexcept
Definition at line 130 of file Tensor2D.H.
References VectorSpace< Tensor2D< Cmpt >, Cmpt, 4 >::v_, and Tensor2D< Cmpt >::YY.
xx() [2/2]
template<class Cmpt > Cmpt & xx () inline noexcept
Definition at line 132 of file Tensor2D.H.
References VectorSpace< Tensor2D< Cmpt >, Cmpt, 4 >::v_, and Tensor2D< Cmpt >::XX.
xy() [2/2]
template<class Cmpt > Cmpt & xy () inline noexcept
Definition at line 133 of file Tensor2D.H.
References VectorSpace< Tensor2D< Cmpt >, Cmpt, 4 >::v_, and Tensor2D< Cmpt >::XY.
yx() [2/2]
template<class Cmpt > Cmpt & yx () inline noexcept
Definition at line 134 of file Tensor2D.H.
References VectorSpace< Tensor2D< Cmpt >, Cmpt, 4 >::v_, and Tensor2D< Cmpt >::YX.
yy() [2/2]
template<class Cmpt > Cmpt & yy () inline noexcept
Definition at line 135 of file Tensor2D.H.
References VectorSpace< Tensor2D< Cmpt >, Cmpt, 4 >::v_, and Tensor2D< Cmpt >::YY.
cx()
template<class Cmpt > Foam::Vector2D< Cmpt > cx () const inline
Definition at line 104 of file Tensor2DI.H.
cy()
template<class Cmpt > Foam::Vector2D< Cmpt > cy () const inline
Definition at line 110 of file Tensor2DI.H.
col() [1/5]
template<class Cmpt > template<direction Idx> Vector2D< Cmpt > col () const inline
col() [2/5]
template<class Cmpt > Foam::Vector2D< Cmpt > col (const direction c) const inline
Definition at line 129 of file Tensor2DI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and Foam::Zero.
col() [3/5]
template<class Cmpt > template<Foam::direction Idx> void col (const Vector2D< Cmpt > & v) inline
Definition at line 174 of file Tensor2DI.H.
col() [4/5]
template<class Cmpt > void col (const direction c, const Vector2D< Cmpt > & v) inline
Definition at line 233 of file Tensor2DI.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
cols()
template<class Cmpt > void cols (const Vector2D< Cmpt > & x, const Vector2D< Cmpt > & y) inline
Definition at line 209 of file Tensor2DI.H.
References x, and y.
x()
template<class Cmpt > Foam::Vector2D< Cmpt > x () const inline
Definition at line 91 of file Tensor2DI.H.
y()
template<class Cmpt > Foam::Vector2D< Cmpt > y () const inline
Definition at line 97 of file Tensor2DI.H.
row() [1/5]
template<class Cmpt > template<direction Idx> Vector2D< Cmpt > row () const inline
Referenced by Tensor2D< Cmpt >::vectorComponent().
row() [2/5]
template<class Cmpt > Foam::Vector2D< Cmpt > row (const direction r) const inline
Definition at line 157 of file Tensor2DI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, x, y, and Foam::Zero.
row() [3/5]
template<class Cmpt > template<Foam::direction Idx> void row (const Vector2D< Cmpt > & v) inline
Definition at line 193 of file Tensor2DI.H.
row() [4/5]
template<class Cmpt > void row (const direction r, const Vector2D< Cmpt > & v) inline
Definition at line 251 of file Tensor2DI.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
rows()
template<class Cmpt > void rows (const Vector2D< Cmpt > & x, const Vector2D< Cmpt > & y) inline
Definition at line 221 of file Tensor2DI.H.
References x, and y.
diag() [1/2]
template<class Cmpt > Foam::Vector2D< Cmpt > diag () const inline
Definition at line 269 of file Tensor2DI.H.
diag() [2/2]
template<class Cmpt > void diag (const Vector2D< Cmpt > & v) inline
Definition at line 276 of file Tensor2DI.H.
diagSqr()
template<class Cmpt > Foam::scalar diagSqr () const inline
Definition at line 283 of file Tensor2DI.H.
References Foam::magSqr().
T()
template<class Cmpt > Foam::Tensor2D< Cmpt > T () const inline
Definition at line 296 of file Tensor2DI.H.
det()
template<class Cmpt > Cmpt det () const inline
Definition at line 307 of file Tensor2DI.H.
adjunct()
template<class Cmpt > Foam::Tensor2D< Cmpt > adjunct () const inline
Definition at line 314 of file Tensor2DI.H.
cof()
template<class Cmpt > Foam::Tensor2D< Cmpt > cof () const inline
Definition at line 325 of file Tensor2DI.H.
inv()
template<class Cmpt > Foam::Tensor2D< Cmpt > inv () const inline
Definition at line 364 of file Tensor2DI.H.
References Foam::abort(), Foam::det(), Foam::FatalError, FatalErrorInFunction, Foam::mag(), and Foam::nl.
inner()
template<class Cmpt > Foam::Tensor2D< Cmpt > inner (const Tensor2D< Cmpt > & t2) const inline
Definition at line 333 of file Tensor2DI.H.
schur()
template<class Cmpt > Foam::Tensor2D< Cmpt > schur (const Tensor2D< Cmpt > & t2) const inline
Definition at line 350 of file Tensor2DI.H.
operator=() [2/3]
template<class Cmpt > void operator= (const SymmTensor2D< Cmpt > & st) inline
Definition at line 385 of file Tensor2DI.H.
operator=() [3/3]
template<class Cmpt > void operator= (const SphericalTensor2D< Cmpt > & st) inline
Definition at line 393 of file Tensor2DI.H.
References Foam::Zero.
vectorComponent()
template<class Cmpt > Vector2D< Cmpt > vectorComponent (const direction cmpt) const inline
Definition at line 239 of file Tensor2D.H.
References Tensor2D< Cmpt >::row().
col() [5/5]
template<class Cmpt > template<Foam::direction Idx> Foam::Vector2D< Cmpt > col () const inline
Definition at line 118 of file Tensor2DI.H.
References Foam::Zero.
row() [5/5]
template<class Cmpt > template<Foam::direction Idx> Foam::Vector2D< Cmpt > row () const inline
Definition at line 146 of file Tensor2DI.H.
References x, y, and Foam::Zero.
Member Data Documentation
rank
template<class Cmpt > constexpr direction rank = 2 static constexpr
Definition at line 67 of file Tensor2D.H.
I
const Foam::tensor2D I static
Definition at line 72 of file Tensor2D.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/Tensor2D/Tensor2D.H
src/OpenFOAM/primitives/Tensor2D/tensor2D/tensor2D.C
src/OpenFOAM/primitives/Tensor2D/Tensor2DI.H