OpenFOAM: pairPotential Class Reference
pairPotential Class Reference abstract
#include <pairPotential.H>
Public Member Functions
TypeName ("pairPotential")
declareRunTimeSelectionTable (autoPtr, pairPotential, dictionary,(const word &name, const dictionary &pairPotentialProperties),(name, pairPotentialProperties))
pairPotential (const word &name, const dictionary &pairPotentialProperties)
virtual ~pairPotential ()=default
void setLookupTables ()
scalar rMin () const
scalar dr () const
scalar rCut () const
scalar rCutSqr () const
scalar energy (const scalar r) const
scalar force (const scalar r) const
List< Pair< scalar > > energyTable () const
List< Pair< scalar > > forceTable () const
bool writeTables () const
virtual scalar unscaledEnergy (const scalar r) const =0
scalar scaledEnergy (const scalar r) const
scalar energyDerivative (const scalar r, const bool scaledEnergyDerivative=true) const
const dictionary & pairPotentialProperties () const
bool writeEnergyAndForceTables (Ostream &os) const
virtual bool read (const dictionary &pairPotentialProperties)=0
Static Public Member Functions
static autoPtr< pairPotential > New (const word &name, const dictionary &pairPotentialProperties)
Protected Member Functions
void scaleEnergy (scalar &e, const scalar r) const
pairPotential (const pairPotential &)=delete
void operator= (const pairPotential &)=delete
Protected Attributes
word name_
dictionary pairPotentialProperties_
scalar rCut_
scalar rCutSqr_
scalar rMin_
scalar dr_
List< scalar > forceLookup_
List< scalar > energyLookup_
energyScalingFunction * esfPtr_
bool writeTables_
Detailed Description
Source files
pairPotential.H
pairPotential.C
pairPotentialNew.C
Definition at line 56 of file pairPotential.H.
Constructor & Destructor Documentation
pairPotential() [1/2]
pairPotential (const pairPotential &) protected delete
pairPotential() [2/2]
pairPotential (const word & name, const dictionary & pairPotentialProperties)
Definition at line 51 of file pairPotential.C.
~pairPotential()
virtual ~pairPotential () virtual default
Member Function Documentation
scaleEnergy()
void scaleEnergy (scalar & e, const scalar r) const protected
Definition at line 35 of file pairPotential.C.
References e, pairPotential::esfPtr_, pairPotential::name_, energyScalingFunction::New(), pairPotential::pairPotentialProperties_, and energyScalingFunction::scaleEnergy().
operator=()
void operator= (const pairPotential &) protected delete
TypeName()
TypeName ("pairPotential")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , pairPotential , dictionary , (const word &name, const dictionary &pairPotentialProperties) , (name, pairPotentialProperties))
New()
Foam::autoPtr< Foam::pairPotential > New (const word & name, const dictionary & pairPotentialProperties) static
Definition at line 27 of file pairPotentialNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, Foam::Info, Foam::name(), and Foam::nl.
setLookupTables()
void setLookupTables ()
Definition at line 72 of file pairPotential.C.
References forAll, k, N(), and PtrList< T >::setSize().
Referenced by azizChen::azizChen(), coulomb::coulomb(), dampedCoulomb::dampedCoulomb(), exponentialRepulsion::exponentialRepulsion(), lennardJones::lennardJones(), maitlandSmith::maitlandSmith(), and noInteraction::noInteraction().
rMin()
Foam::scalar rMin () const inline
Definition at line 23 of file pairPotentialI.H.
References pairPotential::rMin_.
dr()
Foam::scalar dr () const inline
Definition at line 29 of file pairPotentialI.H.
rCut()
Foam::scalar rCut () const inline
Definition at line 35 of file pairPotentialI.H.
rCutSqr()
Foam::scalar rCutSqr () const inline
Definition at line 41 of file pairPotentialI.H.
energy()
Foam::scalar energy (const scalar r) const
Definition at line 126 of file pairPotential.C.
References Foam::abort(), e, Foam::FatalError, FatalErrorInFunction, k, and Foam::nl.
force()
Foam::scalar force (const scalar r) const
Definition at line 89 of file pairPotential.C.
References Foam::abort(), f(), Foam::FatalError, FatalErrorInFunction, k, and Foam::nl.
energyTable()
Foam::List< Foam::Pair< Foam::scalar > > energyTable () const
Definition at line 148 of file pairPotential.C.
References UPtrList< T >::first(), forAll, and k.
Referenced by pairPotential::writeEnergyAndForceTables().
forceTable()
Foam::List< Foam::Pair< Foam::scalar > > forceTable () const
Definition at line 111 of file pairPotential.C.
References UPtrList< T >::first(), forAll, and k.
Referenced by pairPotential::writeEnergyAndForceTables().
writeTables()
bool writeTables () const inline
Definition at line 47 of file pairPotentialI.H.
unscaledEnergy()
virtual scalar unscaledEnergy (const scalar r) const pure virtual
Implemented in azizChen, coulomb, dampedCoulomb, exponentialRepulsion, lennardJones, maitlandSmith, and noInteraction.
scaledEnergy()
Foam::scalar scaledEnergy (const scalar r) const
Definition at line 163 of file pairPotential.C.
References e.
energyDerivative()
Foam::scalar energyDerivative (const scalar r, const bool scaledEnergyDerivative = true) const
Definition at line 173 of file pairPotential.C.
References Ea().
pairPotentialProperties()
const dictionary & pairPotentialProperties () const inline
Definition at line 168 of file pairPotential.H.
References pairPotential::pairPotentialProperties_.
Referenced by coulomb::read(), dampedCoulomb::read(), lennardJones::read(), and noInteraction::read().
writeEnergyAndForceTables()
bool writeEnergyAndForceTables (Ostream & os) const
Definition at line 24 of file pairPotentialIO.C.
References e, Foam::endl(), pairPotential::energyTable(), UPtrList< T >::first(), forAll, pairPotential::forceTable(), Foam::Info, pairPotential::name_, Foam::nl, os(), and token::SPACE.
read()
bool read (const dictionary & pairPotentialProperties) pure virtual
Implemented in azizChen, coulomb, dampedCoulomb, exponentialRepulsion, lennardJones, maitlandSmith, and noInteraction.
Definition at line 217 of file pairPotential.C.
Referenced by azizChen::read(), coulomb::read(), dampedCoulomb::read(), exponentialRepulsion::read(), lennardJones::read(), maitlandSmith::read(), and noInteraction::read().
Member Data Documentation
name_
word name_ protected
Definition at line 63 of file pairPotential.H.
Referenced by pairPotential::scaleEnergy(), and pairPotential::writeEnergyAndForceTables().
pairPotentialProperties_
dictionary pairPotentialProperties_ protected
Definition at line 64 of file pairPotential.H.
Referenced by pairPotential::pairPotentialProperties(), and pairPotential::scaleEnergy().
rCut_
scalar rCut_ protected
Definition at line 66 of file pairPotential.H.
rCutSqr_
scalar rCutSqr_ protected
Definition at line 67 of file pairPotential.H.
rMin_
scalar rMin_ protected
Definition at line 69 of file pairPotential.H.
Referenced by pairPotential::rMin().
dr_
scalar dr_ protected
Definition at line 70 of file pairPotential.H.
forceLookup_
List<scalar> forceLookup_ protected
Definition at line 72 of file pairPotential.H.
energyLookup_
List<scalar> energyLookup_ protected
Definition at line 73 of file pairPotential.H.
esfPtr_
energyScalingFunction* esfPtr_ mutable protected
Definition at line 75 of file pairPotential.H.
Referenced by pairPotential::scaleEnergy().
writeTables_
bool writeTables_ protected
Definition at line 77 of file pairPotential.H.
The documentation for this class was generated from the following files:
src/lagrangian/molecularDynamics/potential/pairPotential/basic/pairPotential.H
src/lagrangian/molecularDynamics/potential/pairPotential/basic/pairPotential.C
src/lagrangian/molecularDynamics/potential/pairPotential/basic/pairPotentialI.H
src/lagrangian/molecularDynamics/potential/pairPotential/basic/pairPotentialIO.C
src/lagrangian/molecularDynamics/potential/pairPotential/basic/pairPotentialNew.C