OpenFOAM: thermo< Thermo, Type > Class Template Reference
thermo< Thermo, Type > Class Template Reference
#include <thermo.H>
Public Types
typedef thermo< Thermo, Type > thermoType
Public Member Functions
thermo (const Thermo &sp)
thermo (const dictionary &dict)
thermo (const word &name, const thermo &)
scalar Cpv (const scalar p, const scalar T) const
scalar gamma (const scalar p, const scalar T) const
scalar CpByCpv (const scalar p, const scalar T) const
scalar HE (const scalar p, const scalar T) const
scalar G (const scalar p, const scalar T) const
scalar A (const scalar p, const scalar T) const
scalar cp (const scalar p, const scalar T) const
scalar ha (const scalar p, const scalar T) const
scalar hs (const scalar p, const scalar T) const
scalar hc () const
scalar s (const scalar p, const scalar T) const
scalar he (const scalar p, const scalar T) const
scalar cv (const scalar p, const scalar T) const
scalar es (const scalar p, const scalar T) const
scalar ea (const scalar p, const scalar T) const
scalar g (const scalar p, const scalar T) const
scalar a (const scalar p, const scalar T) const
scalar K (const scalar p, const scalar T) const
scalar Kp (const scalar p, const scalar T) const
scalar Kc (const scalar p, const scalar T) const
scalar Kx (const scalar p, const scalar T) const
scalar Kn (const scalar p, const scalar T, const scalar n) const
scalar THE (const scalar H, const scalar p, const scalar T0) const
scalar THs (const scalar Hs, const scalar p, const scalar T0) const
scalar THa (const scalar H, const scalar p, const scalar T0) const
scalar TEs (const scalar E, const scalar p, const scalar T0) const
scalar TEa (const scalar E, const scalar p, const scalar T0) const
scalar dKcdTbyKc (const scalar p, const scalar T) const
scalar dcpdT (const scalar p, const scalar T) const
void write (Ostream &os) const
void operator+= (const thermo &)
void operator*= (const scalar)
Static Public Member Functions
static word typeName ()
static word heName ()
Friends
thermo operator+ (const thermo &, const thermo &)
thermo operator* (const scalar s, const thermo &)
thermo operator== (const thermo &, const thermo &)
Ostream & operator (Ostream &, const thermo &)
Detailed Description
template<class Thermo, template< class > class Type>
class Foam::species::thermo< Thermo, Type >
Definition at line 87 of file thermo.H.
Member Typedef Documentation
thermoType
template<class Thermo , template< class > class Type> typedef thermo<Thermo, Type> thermoType
Definition at line 120 of file thermo.H.
Constructor & Destructor Documentation
thermo() [1/3]
template<class Thermo , template< class > class Type> thermo (const Thermo & sp) inline
Definition at line 27 of file thermoI.H.
thermo() [2/3]
template<class Thermo , template< class > class Type> thermo (const dictionary & dict)
Definition at line 35 of file thermo.C.
thermo() [3/3]
template<class Thermo , template< class > class Type> thermo (const word & name, const thermo< Thermo, Type > & st) inline
Definition at line 88 of file thermoI.H.
Member Function Documentation
typeName()
template<class Thermo , template< class > class Type> static word typeName () inline static
Definition at line 138 of file thermo.H.
References thermo< Thermo, Type >::typeName().
Referenced by thermo< Thermo, Type >::typeName().
heName()
template<class Thermo , template< class > class Type> Foam::word heName () inline static
Definition at line 102 of file thermoI.H.
Cpv()
template<class Thermo , template< class > class Type> Foam::scalar Cpv (const scalar p, const scalar T) const inline
Definition at line 110 of file thermoI.H.
References p, and T.
gamma()
template<class Thermo , template< class > class Type> Foam::scalar gamma (const scalar p, const scalar T) const inline
Definition at line 118 of file thermoI.H.
References Cp, p, and T.
CpByCpv()
template<class Thermo , template< class > class Type> Foam::scalar CpByCpv (const scalar p, const scalar T) const inline
Definition at line 132 of file thermoI.H.
References p, and T.
HE()
template<class Thermo , template< class > class Type> Foam::scalar HE (const scalar p, const scalar T) const inline
Definition at line 144 of file thermoI.H.
References p, and T.
G()
template<class Thermo , template< class > class Type> Foam::scalar G (const scalar p, const scalar T) const inline
Definition at line 152 of file thermoI.H.
References Ha(), p, and T.
A()
template<class Thermo , template< class > class Type> Foam::scalar A (const scalar p, const scalar T) const inline
Definition at line 160 of file thermoI.H.
References Ea(), p, and T.
cp()
template<class Thermo , template< class > class Type> Foam::scalar cp (const scalar p, const scalar T) const inline
Definition at line 168 of file thermoI.H.
References Cp, and T.
ha()
template<class Thermo , template< class > class Type> Foam::scalar ha (const scalar p, const scalar T) const inline
Definition at line 176 of file thermoI.H.
References Ha(), and T.
hs()
template<class Thermo , template< class > class Type> Foam::scalar hs (const scalar p, const scalar T) const inline
Definition at line 184 of file thermoI.H.
References Hs(), and T.
hc()
template<class Thermo , template< class > class Type> Foam::scalar hc () const inline
Definition at line 192 of file thermoI.H.
s()
template<class Thermo , template< class > class Type> Foam::scalar s (const scalar p, const scalar T) const inline
Definition at line 200 of file thermoI.H.
References p, and T.
he()
template<class Thermo , template< class > class Type> Foam::scalar he (const scalar p, const scalar T) const inline
Definition at line 208 of file thermoI.H.
References p, and T.
cv()
template<class Thermo , template< class > class Type> Foam::scalar cv (const scalar p, const scalar T) const inline
Definition at line 216 of file thermoI.H.
References Cv, and T.
es()
template<class Thermo , template< class > class Type> Foam::scalar es (const scalar p, const scalar T) const inline
Definition at line 224 of file thermoI.H.
References Es(), and T.
ea()
template<class Thermo , template< class > class Type> Foam::scalar ea (const scalar p, const scalar T) const inline
Definition at line 232 of file thermoI.H.
References Ea(), and T.
g()
template<class Thermo , template< class > class Type> Foam::scalar g (const scalar p, const scalar T) const inline
Definition at line 240 of file thermoI.H.
References p, and T.
a()
template<class Thermo , template< class > class Type> Foam::scalar a (const scalar p, const scalar T) const inline
Definition at line 248 of file thermoI.H.
References A, and T.
K()
template<class Thermo , template< class > class Type> Foam::scalar K (const scalar p, const scalar T) const inline
Definition at line 256 of file thermoI.H.
References Foam::exp(), Foam::constant::thermodynamic::Pstd, Foam::constant::thermodynamic::RR, T, and Y.
Kp()
template<class Thermo , template< class > class Type> Foam::scalar Kp (const scalar p, const scalar T) const inline
Definition at line 273 of file thermoI.H.
References p, and T.
Kc()
template<class Thermo , template< class > class Type> Foam::scalar Kc (const scalar p, const scalar T) const inline
Definition at line 281 of file thermoI.H.
References Foam::equal(), p, Foam::pow(), Foam::constant::thermodynamic::Pstd, Foam::constant::thermodynamic::RR, T, and Y.
Kx()
template<class Thermo , template< class > class Type> Foam::scalar Kx (const scalar p, const scalar T) const inline
Definition at line 297 of file thermoI.H.
References Foam::equal(), p, Foam::pow(), Foam::constant::thermodynamic::Pstd, T, and Y.
Kn()
template<class Thermo , template< class > class Type> Foam::scalar Kn (const scalar p, const scalar T, const scalar n) const inline
Definition at line 317 of file thermoI.H.
References Foam::equal(), n, p, Foam::pow(), Foam::constant::thermodynamic::Pstd, T, and Y.
THE()
template<class Thermo , template< class > class Type> Foam::scalar THE (const scalar H, const scalar p, const scalar T0) const inline
Definition at line 338 of file thermoI.H.
References he, p, and T0.
THs()
template<class Thermo , template< class > class Type> Foam::scalar THs (const scalar Hs, const scalar p, const scalar T0) const inline
Definition at line 350 of file thermoI.H.
References p, T, and T0.
THa()
template<class Thermo , template< class > class Type> Foam::scalar THa (const scalar H, const scalar p, const scalar T0) const inline
Definition at line 370 of file thermoI.H.
References p, T, and T0.
TEs()
template<class Thermo , template< class > class Type> Foam::scalar TEs (const scalar E, const scalar p, const scalar T0) const inline
Definition at line 390 of file thermoI.H.
References p, T, and T0.
TEa()
template<class Thermo , template< class > class Type> Foam::scalar TEa (const scalar E, const scalar p, const scalar T0) const inline
Definition at line 410 of file thermoI.H.
References p, T, and T0.
dKcdTbyKc()
template<class Thermo , template< class > class Type> Foam::scalar dKcdTbyKc (const scalar p, const scalar T) const inline
Definition at line 431 of file thermoI.H.
References Foam::equal(), Foam::constant::thermodynamic::Pstd, Foam::constant::thermodynamic::RR, T, and Y.
dcpdT()
template<class Thermo , template< class > class Type> Foam::scalar dcpdT (const scalar p, const scalar T) const inline
Definition at line 454 of file thermoI.H.
References p, and T.
write()
template<class Thermo , template< class > class Type> void write (Ostream & os) const
Definition at line 44 of file thermo.C.
References os().
operator+=()
template<class Thermo , template< class > class Type> void operator+= (const thermo< Thermo, Type > &) inline
Definition at line 462 of file thermoI.H.
operator*=()
template<class Thermo , template< class > class Type> void operator*= (const scalar s) inline
Definition at line 472 of file thermoI.H.
References s().
Friends And Related Symbol Documentation
operator+
template<class Thermo , template< class > class Type> thermo operator+ (const thermo< Thermo, Type > & , const thermo< Thermo, Type > &) friend
operator*
template<class Thermo , template< class > class Type> thermo operator* (const scalar s, const thermo< Thermo, Type > &) friend
operator==
template<class Thermo , template< class > class Type> thermo operator== (const thermo< Thermo, Type > & , const thermo< Thermo, Type > &) friend
operator
template<class Thermo , template< class > class Type> Ostream & operator (Ostream & , const thermo< Thermo, Type > &) friend
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/thermo/thermo/thermo.H
src/thermophysicalModels/specie/thermo/thermo/thermo.C
src/thermophysicalModels/specie/thermo/thermo/thermoI.H