OpenFOAM: massRosinRammler Class Reference
massRosinRammler Class Reference
Particle-size distribution model wherein random samples are drawn from the two-parameter Rosin-Rammler (Weibull) probability density function corrected to take into account varying number of particles per parcels for fixed-mass parcels.
#include <massRosinRammler.H>
Public Member Functions
TypeName ("massRosinRammler")
massRosinRammler (const dictionary &dict, Random &rndGen)
massRosinRammler (const massRosinRammler &p)
virtual autoPtr< distributionModel > clone () const
void operator= (const massRosinRammler &)=delete
virtual ~massRosinRammler ()=default
virtual scalar sample () const
virtual scalar meanValue () const
Public Member Functions inherited from distributionModel
TypeName ("distributionModel")
declareRunTimeSelectionTable (autoPtr, distributionModel, dictionary,(const dictionary &dict, Random &rndGen),(dict, rndGen))
distributionModel (const word &name, const dictionary &dict, Random &rndGen)
distributionModel (const distributionModel &p)
virtual ~distributionModel ()=default
virtual scalar minValue () const
virtual scalar maxValue () const
Additional Inherited Members
Static Public Member Functions inherited from distributionModel
static autoPtr< distributionModel > New (const dictionary &dict, Random &rndGen)
Protected Member Functions inherited from distributionModel
virtual void check () const
Protected Attributes inherited from distributionModel
const dictionary distributionModelDict_
Random & rndGen_
scalar minValue_
scalar maxValue_
Detailed Description
Particle-size distribution model wherein random samples are drawn from the two-parameter Rosin-Rammler (Weibull) probability density function corrected to take into account varying number of particles per parcels for fixed-mass parcels.
"There is a factor of \_form#512 difference between the size distribution probability density function of individual particles and modeled parcels of particles, \_form#513, because the submodel parameter, \_form#514 (number of particles per parcel) is based on a fixed mass per parcel which weights the droplet distribution by a factor proportional to \_form#515 (i.e.\iline 35 \_form#516@_fakenl)." (YHD:p. 1374-1375).
massRosinRammler should be preferred over RosinRammler when parcelBasisType is based on mass:
    parcelBasisType mass;
The doubly-truncated mass-corrected Rosin-Rammler probability density function:
where
= Rosin-Rammler probability density function
= Scale parameter
= Shape parameter
= Sample
= Minimum of the distribution
= Maximum of the distribution
Constraints:
Random samples are generated by the inverse transform sampling technique by using the quantile function of the doubly-truncated two-parameter mass-corrected Rosin-Rammler (Weibull) probability density function:
with
where is the inverse of regularised lower incomplete gamma function, and is a sample drawn from the uniform probability density function on the interval :
where is the lower incomplete gamma function.
Reference:
        Standard model (tag:YHD):
            Yoon, S. S., Hewson, J. C., DesJardin, P. E.,
            Glaze, D. J., Black, A. R., & Skaggs, R. R. (2004).
            Numerical modeling and experimental measurements of a high speed
            solid-cone water spray for use in fire suppression applications.
            International Journal of Multiphase Flow, 30(11), 1369-1388.
            DOI:10.1016/j.ijmultiphaseflow.2004.07.006
Usage
Minimal example by using constant/<CloudProperties>:
subModels
{
    injectionModels
    {
        <name>
        {
            ...
            parcelBasisType  mass;
            ...
            sizeDistribution
            {
                type        massRosinRammler;
                massRosinRammlerDistribution
                {
                    lambda      <scaleParameterValue>;
                    n           <shapeParameterValue>;
                    minValue    <minValue>;
                    maxValue    <maxValue>;
                }
            }
        }
    }
}
where the entries mean:
Property Description Type Reqd Deflt
type Type name: massRosinRammler word yes -
massRosinRammlerDistribution Distribution settings dict yes -
lambda Scale parameter scalar yes -
n Shape parameter scalar yes -
minValue Minimum of the distribution scalar yes -
maxValue Maximum of the distribution scalar yes -
Note
In the current context, lambda (or d) is called "characteristic droplet size", and n "empirical dimensionless constant to specify the distribution width, sometimes referred to as the dispersion coefficient." (YHD:p. 1374).
Source files
massRosinRammler.H
massRosinRammler.C
Definition at line 245 of file massRosinRammler.H.
Constructor & Destructor Documentation
massRosinRammler() [1/2]
massRosinRammler (const dictionary & dict, Random & rndGen)
Definition at line 39 of file massRosinRammler.C.
massRosinRammler() [2/2]
massRosinRammler (const massRosinRammler & p)
Definition at line 62 of file massRosinRammler.C.
~massRosinRammler()
virtual ~massRosinRammler () virtual default
Member Function Documentation
TypeName()
TypeName ("massRosinRammler")
clone()
virtual autoPtr< distributionModel > clone () const inline virtual
Implements distributionModel.
Definition at line 273 of file massRosinRammler.H.
operator=()
void operator= (const massRosinRammler &) delete
sample()
Foam::scalar sample () const virtual
Implements distributionModel.
Definition at line 75 of file massRosinRammler.C.
References Foam::Math::incGamma_P(), Foam::Math::invIncGamma(), Foam::pow(), and x.
meanValue()
Foam::scalar meanValue () const virtual
Implements distributionModel.
Definition at line 95 of file massRosinRammler.C.
The documentation for this class was generated from the following files:
src/lagrangian/distributionModels/massRosinRammler/massRosinRammler.H
src/lagrangian/distributionModels/massRosinRammler/massRosinRammler.C