OpenFOAM: tetDecomposer Class Reference
tetDecomposer Class Reference
Decomposes polyMesh into tets or pyramids.
#include <tetDecomposer.H>
Public Types
enum decompositionType { FACE_CENTRE_TRIS , FACE_DIAG_TRIS , PYRAMID }
Public Member Functions
ClassName ("tetDecomposer")
tetDecomposer (const polyMesh &)
const labelList & cellToPoint () const
const labelList & faceToPoint () const
const labelListList & faceOwnerCells () const
const labelListList & faceNeighbourCells () const
void setRefinement (const decompositionType decomposeType, const bitSet &decomposeCell, polyTopoChange &meshMod)
void updateMesh (const mapPolyMesh &)
Static Public Attributes
static const Enum< decompositionType > decompositionTypeNames
Detailed Description
Decomposes polyMesh into tets or pyramids.
Cells neighbouring decomposed cells are not decomposed themselves so will be polyhedral.
Source files
tetDecomposer.H
tetDecomposer.C
Definition at line 59 of file tetDecomposer.H.
Member Enumeration Documentation
decompositionType
enum decompositionType
Enumerator
FACE_CENTRE_TRIS
FACE_DIAG_TRIS
PYRAMID
Definition at line 65 of file tetDecomposer.H.
Constructor & Destructor Documentation
tetDecomposer()
tetDecomposer (const polyMesh & mesh)
Definition at line 197 of file tetDecomposer.C.
Member Function Documentation
ClassName()
ClassName ("tetDecomposer")
cellToPoint()
const labelList & cellToPoint () const inline
Definition at line 154 of file tetDecomposer.H.
faceToPoint()
const labelList & faceToPoint () const inline
Definition at line 160 of file tetDecomposer.H.
faceOwnerCells()
const labelListList & faceOwnerCells () const inline
Definition at line 169 of file tetDecomposer.H.
faceNeighbourCells()
const labelListList & faceNeighbourCells () const inline
Definition at line 177 of file tetDecomposer.H.
setRefinement()
void setRefinement (const decompositionType decomposeType, const bitSet & decomposeCell, polyTopoChange & meshMod)
Definition at line 205 of file tetDecomposer.C.
References Foam::abort(), polyTopoChange::addCell(), polyTopoChange::addPoint(), PtrList< T >::clear(), e, UPtrList< T >::end(), f(), Foam::FatalError, FatalErrorInFunction, UList< T >::fcIndex(), forAll, Foam::max(), p0, UList< T >::rcIndex(), List< T >::setSize(), PtrList< T >::setSize(), UList< T >::size(), and syncTools::swapBoundaryFaceList().
updateMesh()
void updateMesh (const mapPolyMesh & map)
Definition at line 868 of file tetDecomposer.C.
References forAll, Foam::inplaceRenumber(), mapPolyMesh::reverseCellMap(), and mapPolyMesh::reversePointMap().
Member Data Documentation
decompositionTypeNames
const Foam::Enum< Foam::tetDecomposer::decompositionType > decompositionTypeNames static
Definition at line 72 of file tetDecomposer.H.
The documentation for this class was generated from the following files:
src/dynamicMesh/polyTopoChange/polyTopoChange/tetDecomposer.H
src/dynamicMesh/polyTopoChange/polyTopoChange/tetDecomposer.C