OpenFOAM: FixedList< T, N > Class Template Reference
FixedList< T, N > Class Template Reference
A 1D vector of objects of type <T> with a fixed length <N>.
#include <FixedList.H>
Classes
struct Hash
struct hasher
Public Types
typedef T value_type
typedef T * pointer
typedef const T * const_pointer
typedef T & reference
typedef const T & const_reference
typedef T * iterator
typedef const T * const_iterator
typedef label size_type
typedef label difference_type
typedef std::reverse_iterator< iterator > reverse_iterator
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
Public Member Functions
FixedList ()=default
FixedList (const T &val)
FixedList (const Foam::zero)
FixedList (const T list[N])
FixedList (const FixedList< T, N > &list)
FixedList (FixedList< T, N > &&list)
FixedList (std::initializer_list< T > list)
FixedList (const UList< T > &list)
template<unsigned AnyNum>
FixedList (const FixedList< T, AnyNum > &list, const FixedList< label, N > &indices)
FixedList (const UList< T > &list, const FixedList< label, N > &indices)
FixedList (const SLList< T > &list)
FixedList (Istream &is)
autoPtr< FixedList< T, N > > clone () const
const T * cdata () const noexcept
T * data () noexcept
const char * cdata_bytes () const noexcept
char * data_bytes () noexcept
template<unsigned Index>
T & get () noexcept
template<unsigned Index>
const T & get () const noexcept
T & front () noexcept
const T & front () const noexcept
T & back () noexcept
const T & back () const noexcept
label fcIndex (const label i) const
const T & fcValue (const label i) const
T & fcValue (const label i)
label rcIndex (const label i) const
const T & rcValue (const label i) const
T & rcValue (const label i)
void checkStart (const label start) const
void checkSize (const label size) const
void checkIndex (const label i) const
bool uniform () const
label find (const T &val, label pos=0) const
label rfind (const T &val, label pos=-1) const
bool contains (const T &val, label pos=0) const
void resize (const label n)
void resize_nocopy (const label n)
void setSize (const label n)
void fill (const T &val)
void fill (const Foam::zero)
void moveFirst (const label i)
void moveLast (const label i)
void swapFirst (const label i)
void swapLast (const label i)
void transfer (FixedList< T, N > &list)
T & operator[] (const label i)
const T & operator[] (const label i) const
void operator= (const T list[N])
void operator= (const UList< T > &list)
void operator= (const SLList< T > &list)
void operator= (std::initializer_list< T > list)
void operator= (const T &val)
void operator= (const Foam::zero)
void operator= (const FixedList< T, N > &list)
void operator= (FixedList< T, N > &&list)
iterator begin () noexcept
iterator end () noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
const_iterator begin () const noexcept
const_iterator end () const noexcept
reverse_iterator rbegin ()
reverse_iterator rend ()
const_reverse_iterator crbegin () const
const_reverse_iterator crend () const
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
void swap (FixedList< T, N > &other)
bool operator== (const FixedList< T, N > &list) const
bool operator!= (const FixedList< T, N > &list) const
bool operator< (const FixedList< T, N > &list) const
bool operator> (const FixedList< T, N > &list) const
bool operator<= (const FixedList< T, N > &list) const
bool operator>= (const FixedList< T, N > &list) const
Istream & readList (Istream &is)
void writeEntry (const word &keyword, Ostream &os) const
Ostream & writeList (Ostream &os, const label shortLen=0) const
T & first () noexcept
const T & first () const noexcept
T & last () noexcept
const T & last () const noexcept
bool found (const T &val, label pos=0) const
Static Public Member Functions
static const FixedList< T, N > & null ()
static std::streamsize size_bytes () noexcept
static std::streamsize byteSize ()
static constexpr bool empty () noexcept
static constexpr label size () noexcept
static constexpr unsigned max_size () noexcept
Protected Member Functions
void writeEntry (Ostream &os) const
Friends
Istream & operator>> (Istream &is, FixedList< T, N > &list)
Detailed Description
template<class T, unsigned N>
class Foam::FixedList< T, N >
A 1D vector of objects of type <T> with a fixed length <N>.
Source files
FixedList.H
FixedList.C
FixedListI.H
FixedListIO.C
Definition at line 75 of file FixedList.H.
Member Typedef Documentation
value_type
template<class T , unsigned N> typedef T value_type
Definition at line 102 of file FixedList.H.
pointer
template<class T , unsigned N> typedef T* pointer
Definition at line 105 of file FixedList.H.
const_pointer
template<class T , unsigned N> typedef const T* const_pointer
Definition at line 108 of file FixedList.H.
reference
template<class T , unsigned N> typedef T& reference
Definition at line 111 of file FixedList.H.
const_reference
template<class T , unsigned N> typedef const T& const_reference
Definition at line 114 of file FixedList.H.
iterator
template<class T , unsigned N> typedef T* iterator
Definition at line 117 of file FixedList.H.
const_iterator
template<class T , unsigned N> typedef const T* const_iterator
Definition at line 120 of file FixedList.H.
size_type
template<class T , unsigned N> typedef label size_type
Definition at line 123 of file FixedList.H.
difference_type
template<class T , unsigned N> typedef label difference_type
Definition at line 126 of file FixedList.H.
reverse_iterator
template<class T , unsigned N> typedef std::reverse_iterator<iterator> reverse_iterator
Definition at line 129 of file FixedList.H.
const_reverse_iterator
template<class T , unsigned N> typedef std::reverse_iterator<const_iterator> const_reverse_iterator
Definition at line 132 of file FixedList.H.
Constructor & Destructor Documentation
FixedList() [1/12]
template<class T , unsigned N> FixedList () default
FixedList() [2/12]
template<class T , unsigned N> FixedList (const T & val) inline explicit
Definition at line 37 of file FixedListI.H.
FixedList() [3/12]
template<class T , unsigned N> FixedList (const Foam::zero) inline explicit
Definition at line 44 of file FixedListI.H.
References Foam::Zero.
FixedList() [4/12]
template<class T , unsigned N> FixedList (const T list[N]) inline explicit
Definition at line 51 of file FixedListI.H.
References N().
FixedList() [5/12]
template<class T , unsigned N> FixedList (const FixedList< T, N > & list) inline
Definition at line 61 of file FixedListI.H.
References N().
FixedList() [6/12]
template<class T , unsigned N> FixedList (FixedList< T, N > && list) inline
Definition at line 71 of file FixedListI.H.
References N().
FixedList() [7/12]
template<class T , unsigned N> FixedList (std::initializer_list< T > list) inline
Definition at line 81 of file FixedListI.H.
References N().
FixedList() [8/12]
template<class T , unsigned N> FixedList (const UList< T > & list) inline explicit
Definition at line 95 of file FixedListI.H.
References N(), and UPtrList< T >::size().
FixedList() [9/12]
template<class T , unsigned N> template<unsigned AnyNum> FixedList (const FixedList< T, AnyNum > & list, const FixedList< label, N > & indices) inline
Definition at line 108 of file FixedListI.H.
References N().
FixedList() [10/12]
template<class T , unsigned N> FixedList (const UList< T > & list, const FixedList< label, N > & indices) inline
Definition at line 122 of file FixedListI.H.
References N().
FixedList() [11/12]
template<class T , unsigned N> FixedList (const SLList< T > & list) inline explicit
Definition at line 136 of file FixedListI.H.
FixedList() [12/12]
template<class T , unsigned N> FixedList (Istream & is) explicit
Definition at line 49 of file FixedListIO.C.
Member Function Documentation
writeEntry() [1/2]
template<class T , unsigned N> void writeEntry (Ostream & os) const protected
Definition at line 30 of file FixedListIO.C.
References IOstreamOption::BINARY, token::compound::isCompound(), N(), os(), PtrList< T >::PtrList(), and token::SPACE.
null()
template<class T , unsigned N> const Foam::FixedList< T, N > & null () inline static
Definition at line 28 of file FixedListI.H.
clone()
template<class T , unsigned N> Foam::autoPtr< Foam::FixedList< T, N > > clone () const inline
Definition at line 151 of file FixedListI.H.
cdata()
template<class T , unsigned N> const T * cdata () const inline noexcept
Definition at line 161 of file FixedListI.H.
data()
template<class T , unsigned N> T * data () inline noexcept
Definition at line 169 of file FixedListI.H.
cdata_bytes()
template<class T , unsigned N> const char * cdata_bytes () const inline noexcept
Definition at line 177 of file FixedListI.H.
data_bytes()
template<class T , unsigned N> char * data_bytes () inline noexcept
Definition at line 185 of file FixedListI.H.
size_bytes()
template<class T , unsigned N> std::streamsize size_bytes () inline static noexcept
Definition at line 192 of file FixedListI.H.
References N(), and T.
Referenced by FixedList< T, N >::byteSize().
byteSize()
template<class T , unsigned N> std::streamsize byteSize () static
Definition at line 28 of file FixedList.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and FixedList< T, N >::size_bytes().
get() [1/2]
template<class T , unsigned N> template<unsigned Index> T & get () inline noexcept
Definition at line 200 of file FixedListI.H.
get() [2/2]
template<class T , unsigned N> template<unsigned Index> const T & get () const inline noexcept
Definition at line 209 of file FixedListI.H.
front() [1/2]
template<class T , unsigned N> T & front () inline noexcept
Definition at line 217 of file FixedListI.H.
Referenced by FixedList< T, N >::first(), and FixedList< T, N >::first().
front() [2/2]
template<class T , unsigned N> const T & front () const inline noexcept
Definition at line 224 of file FixedListI.H.
back() [1/2]
template<class T , unsigned N> T & back () inline noexcept
Definition at line 231 of file FixedListI.H.
Referenced by FixedList< T, N >::last(), and FixedList< T, N >::last().
back() [2/2]
template<class T , unsigned N> const T & back () const inline noexcept
Definition at line 238 of file FixedListI.H.
fcIndex()
template<class T , unsigned N> Foam::label fcIndex (const label i) const inline
Definition at line 245 of file FixedListI.H.
Referenced by wallBoundedParticle::trackFaceTri().
fcValue() [1/2]
template<class T , unsigned N> const T & fcValue (const label i) const inline
Definition at line 252 of file FixedListI.H.
fcValue() [2/2]
template<class T , unsigned N> T & fcValue (const label i) inline
Definition at line 259 of file FixedListI.H.
rcIndex()
template<class T , unsigned N> Foam::label rcIndex (const label i) const inline
Definition at line 266 of file FixedListI.H.
rcValue() [1/2]
template<class T , unsigned N> const T & rcValue (const label i) const inline
Definition at line 273 of file FixedListI.H.
rcValue() [2/2]
template<class T , unsigned N> T & rcValue (const label i) inline
Definition at line 280 of file FixedListI.H.
checkStart()
template<class T , unsigned N> void checkStart (const label start) const inline
Definition at line 287 of file FixedListI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and N().
checkSize()
template<class T , unsigned N> void checkSize (const label size) const inline
Definition at line 300 of file FixedListI.H.
checkIndex()
template<class T , unsigned N> void checkIndex (const label i) const inline
Definition at line 312 of file FixedListI.H.
uniform()
template<class T , unsigned N> bool uniform () const inline
Definition at line 324 of file FixedListI.H.
References N().
find()
template<class T , unsigned N> Foam::label find (const T & val, label pos = 0) const
Definition at line 43 of file FixedList.C.
References List_CONST_ACCESS, N(), Foam::pos(), and T.
Referenced by triFace::which().
rfind()
template<class T , unsigned N> Foam::label rfind (const T & val, label pos = -1) const
Definition at line 65 of file FixedList.C.
References List_CONST_ACCESS, N(), Foam::pos(), and T.
contains()
template<class T , unsigned N> bool contains (const T & val, label pos = 0) const inline
Definition at line 341 of file FixedListI.H.
References Foam::pos().
Referenced by FixedList< T, N >::found().
resize()
template<class T , unsigned N> void resize (const label n) inline
Definition at line 348 of file FixedListI.H.
Referenced by FixedList< T, N >::setSize().
resize_nocopy()
template<class T , unsigned N> void resize_nocopy (const label n) inline
Definition at line 357 of file FixedListI.H.
setSize()
template<class T , unsigned N> void setSize (const label n) inline
Definition at line 307 of file FixedList.H.
References FixedList< T, N >::resize().
fill() [1/2]
template<class T , unsigned N> void fill (const T & val) inline
Definition at line 366 of file FixedListI.H.
fill() [2/2]
template<class T , unsigned N> void fill (const Foam::zero) inline
Definition at line 376 of file FixedListI.H.
moveFirst()
template<class T , unsigned N> void moveFirst (const label i)
Definition at line 90 of file FixedList.C.
References Foam::Swap().
moveLast()
template<class T , unsigned N> void moveLast (const label i)
Definition at line 102 of file FixedList.C.
References N(), and Foam::Swap().
swapFirst()
template<class T , unsigned N> void swapFirst (const label i)
Definition at line 114 of file FixedList.C.
References Foam::Swap().
swapLast()
template<class T , unsigned N> void swapLast (const label i)
Definition at line 126 of file FixedList.C.
References N(), and Foam::Swap().
transfer()
template<class T , unsigned N> void transfer (FixedList< T, N > & list) inline
Definition at line 401 of file FixedListI.H.
operator[]() [1/2]
template<class T , unsigned N> T & operator[] (const label i) inline
Definition at line 418 of file FixedListI.H.
operator[]() [2/2]
template<class T , unsigned N> const T & operator[] (const label i) const inline
Definition at line 428 of file FixedListI.H.
operator=() [1/8]
template<class T , unsigned N> void operator= (const T list[N]) inline
Definition at line 438 of file FixedListI.H.
References N().
Referenced by boolVector::operator=().
operator=() [2/8]
template<class T , unsigned N> void operator= (const UList< T > & list) inline
Definition at line 447 of file FixedListI.H.
References N(), and UPtrList< T >::size().
operator=() [3/8]
template<class T , unsigned N> void operator= (const SLList< T > & list) inline
Definition at line 458 of file FixedListI.H.
References UPtrList< T >::begin(), N(), and UPtrList< T >::size().
operator=() [4/8]
template<class T , unsigned N> void operator= (std::initializer_list< T > list) inline
Definition at line 471 of file FixedListI.H.
References N().
operator=() [5/8]
template<class T , unsigned N> void operator= (const T & val) inline
Definition at line 484 of file FixedListI.H.
operator=() [6/8]
template<class T , unsigned N> void operator= (const Foam::zero) inline
Definition at line 491 of file FixedListI.H.
References Foam::Zero.
operator=() [7/8]
template<class T , unsigned N> void operator= (const FixedList< T, N > & list) inline
Definition at line 498 of file FixedListI.H.
References N().
operator=() [8/8]
template<class T , unsigned N> void operator= (FixedList< T, N > && list) inline
Definition at line 512 of file FixedListI.H.
References N().
begin() [1/2]
template<class T , unsigned N> Foam::FixedList< T, N >::iterator begin () inline noexcept
Definition at line 530 of file FixedListI.H.
end() [1/2]
template<class T , unsigned N> Foam::FixedList< T, N >::iterator end () inline noexcept
Definition at line 554 of file FixedListI.H.
References N().
cbegin()
template<class T , unsigned N> Foam::FixedList< T, N >::const_iterator cbegin () const inline noexcept
Definition at line 546 of file FixedListI.H.
cend()
template<class T , unsigned N> Foam::FixedList< T, N >::const_iterator cend () const inline noexcept
Definition at line 570 of file FixedListI.H.
References N().
begin() [2/2]
template<class T , unsigned N> Foam::FixedList< T, N >::const_iterator begin () const inline noexcept
Definition at line 538 of file FixedListI.H.
end() [2/2]
template<class T , unsigned N> Foam::FixedList< T, N >::const_iterator end () const inline noexcept
Definition at line 562 of file FixedListI.H.
References N().
rbegin() [1/2]
template<class T , unsigned N> Foam::FixedList< T, N >::reverse_iterator rbegin () inline
Definition at line 578 of file FixedListI.H.
rend() [1/2]
template<class T , unsigned N> Foam::FixedList< T, N >::reverse_iterator rend () inline
Definition at line 602 of file FixedListI.H.
crbegin()
template<class T , unsigned N> Foam::FixedList< T, N >::const_reverse_iterator crbegin () const inline
Definition at line 594 of file FixedListI.H.
crend()
template<class T , unsigned N> Foam::FixedList< T, N >::const_reverse_iterator crend () const inline
Definition at line 618 of file FixedListI.H.
rbegin() [2/2]
template<class T , unsigned N> Foam::FixedList< T, N >::const_reverse_iterator rbegin () const inline
Definition at line 586 of file FixedListI.H.
rend() [2/2]
template<class T , unsigned N> Foam::FixedList< T, N >::const_reverse_iterator rend () const inline
Definition at line 610 of file FixedListI.H.
empty()
template<class T , unsigned N> static constexpr bool empty () inline static constexpr noexcept
Definition at line 416 of file FixedList.H.
References N().
size()
template<class T , unsigned N> static constexpr label size () inline static constexpr noexcept
Definition at line 419 of file FixedList.H.
References N().
Referenced by isoSurfacePoint::generateFaceTriPoints(), indexedCell< Gt, Cb >::globallyOrderedCellVertices(), isoSurfaceCell::isoSurfaceCell(), isoSurfacePoint::isoSurfacePoint(), indexedCell< Gt, Cb >::vertexGlobalIndices(), and lumpedPointState::writeVTP().
max_size()
template<class T , unsigned N> static constexpr unsigned max_size () inline static constexpr noexcept
Definition at line 422 of file FixedList.H.
References N().
swap()
template<class T , unsigned N> void swap (FixedList< T, N > & other) inline
Definition at line 386 of file FixedListI.H.
operator==()
template<class T , unsigned N> bool operator== (const FixedList< T, N > & list) const
Definition at line 142 of file FixedList.C.
References List_CONST_ACCESS, N(), and T.
operator!=()
template<class T , unsigned N> bool operator!= (const FixedList< T, N > & list) const
Definition at line 186 of file FixedList.C.
References Foam::operator==().
operator<()
template<class T , unsigned N> bool operator< (const FixedList< T, N > & list) const
Definition at line 162 of file FixedList.C.
References List_CONST_ACCESS, N(), and T.
operator>()
template<class T , unsigned N> bool operator> (const FixedList< T, N > & list) const
Definition at line 193 of file FixedList.C.
operator<=()
template<class T , unsigned N> bool operator<= (const FixedList< T, N > & list) const
Definition at line 200 of file FixedList.C.
operator>=()
template<class T , unsigned N> bool operator>= (const FixedList< T, N > & list) const
Definition at line 207 of file FixedList.C.
References Foam::operator<().
readList()
template<class T , unsigned N> Foam::Istream & readList (Istream & is)
Definition at line 145 of file FixedListIO.C.
References IOstreamOption::BINARY, and FUNCTION_NAME.
writeEntry() [2/2]
template<class T , unsigned N> void writeEntry (const word & keyword, Ostream & os) const
Definition at line 58 of file FixedListIO.C.
References token::END_STATEMENT, Foam::endl(), os(), and Ostream::writeKeyword().
writeList()
template<class T , unsigned N> Foam::Ostream & writeList (Ostream & os, const label shortLen = 0) const
Definition at line 74 of file FixedListIO.C.
References IOstreamOption::BINARY, IOstreamOption::format(), os(), and OBJstream::write().
first() [1/2]
template<class T , unsigned N> T & first () inline noexcept
Definition at line 511 of file FixedList.H.
References FixedList< T, N >::front().
first() [2/2]
template<class T , unsigned N> const T & first () const inline noexcept
Definition at line 514 of file FixedList.H.
References FixedList< T, N >::front().
last() [1/2]
template<class T , unsigned N> T & last () inline noexcept
Definition at line 517 of file FixedList.H.
References FixedList< T, N >::back().
last() [2/2]
template<class T , unsigned N> const T & last () const inline noexcept
Definition at line 520 of file FixedList.H.
References FixedList< T, N >::back().
found()
template<class T , unsigned N> bool found (const T & val, label pos = 0) const inline
Definition at line 523 of file FixedList.H.
References FixedList< T, N >::contains(), and Foam::pos().
Friends And Related Symbol Documentation
operator>>
template<class T , unsigned N> Istream & operator>> (Istream & is, FixedList< T, N > & list) friend
Definition at line 577 of file FixedList.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/HashTables/HashTable/HashTable.H
src/OpenFOAM/containers/Lists/FixedList/FixedList.H
src/OpenFOAM/containers/Lists/FixedList/FixedList.C
src/OpenFOAM/containers/Lists/FixedList/FixedListI.H
src/OpenFOAM/containers/Lists/FixedList/FixedListIO.C