OpenFOAM: boundBox Class Reference
boundBox Class Reference
A bounding box defined in terms of min/max extrema points.
#include <boundBox.H>
Public Types
enum directionBit : direction { XDIR = 1 , YDIR = 2 , ZDIR = 4 }
Public Member Functions
boundBox ()
boundBox (const boundBox &)=default
boundBox & operator= (const boundBox &)=default
boundBox (const boundBox &bb, bool doReduce)
boundBox (const point &p)
boundBox (const Foam::zero_one)
boundBox (const point &min, const point &max)
boundBox (const Pair< point > &bb)
boundBox (const UList< point > &points, bool doReduce=true)
boundBox (const tmp< pointField > &tpoints, bool doReduce=true)
boundBox (const UList< point > &points, const labelUList &indices, bool doReduce=true)
template<unsigned N>
boundBox (const UList< point > &points, const FixedList< label, N > &indices, bool doReduce=true)
boundBox (Istream &is)
bool empty () const
bool good () const
bool valid () const
const point & min () const noexcept
const point & max () const noexcept
point & min () noexcept
point & max () noexcept
point centre () const
vector span () const
scalar mag () const
scalar magSqr () const
scalar volume () const
scalar minDim () const
scalar maxDim () const
scalar avgDim () const
direction minDir () const
direction maxDir () const
int nDim () const
template<direction CornerNumber>
point hexCorner () const
tmp< pointField > hexCorners () const
tmp< pointField > points () const
tmp< pointField > faceCentres () const
point faceCentre (const direction facei) const
void reset ()
void reset (const Foam::zero_one)
void reset (const point &pt)
void reset (const point &min, const point &max)
void clear ()
void add (const boundBox &bb)
void add (const point &pt)
void add (const point &pt0, const point &pt1)
void add (const Pair< point > &points)
void add (const UList< point > &points)
void add (const tmp< pointField > &tpoints)
template<unsigned N>
void add (const FixedList< point, N > &points)
template<unsigned N>
void add (const UList< point > &points, const FixedList< label, N > &indices)
template<class IntContainer >
void add (const UList< point > &points, const IntContainer &indices)
void grow (const scalar delta)
void grow (const vector &delta)
void inflate (const scalar factor)
void inflate (Random &rndGen, const scalar factor)
void inflate (Random &r, const scalar factor, const scalar delta)
void reduce ()
bool intersects (const plane &pln) const
bool intersects (const triPointRef &tri) const
bool overlaps (const boundBox &bb) const
bool overlaps (const point &centre, const scalar radiusSqr) const
bool contains (const point &pt) const
bool contains (const boundBox &bb) const
bool containsInside (const point &pt) const
bool contains (const UList< point > &points) const
template<unsigned N>
bool contains (const UList< point > &points, const FixedList< label, N > &indices) const
template<class IntContainer >
bool contains (const UList< point > &points, const IntContainer &indices) const
bool containsAny (const UList< point > &points) const
template<unsigned N>
bool containsAny (const UList< point > &points, const FixedList< label, N > &indices) const
template<class IntContainer >
bool containsAny (const UList< point > &points, const IntContainer &indices) const
point nearest (const point &p) const
void operator&= (const boundBox &bb)
void operator+= (const boundBox &bb)
bool intersect (const boundBox &bb)
point midpoint () const
template<>
Foam::point hexCorner () const
template<>
Foam::point hexCorner () const
template<>
Foam::point hexCorner () const
template<>
Foam::point hexCorner () const
template<>
Foam::point hexCorner () const
template<>
Foam::point hexCorner () const
template<>
Foam::point hexCorner () const
template<>
Foam::point hexCorner () const
template<Foam::direction CornerNumber>
Foam::point hexCorner () const
Static Public Member Functions
static const boundBox & null () noexcept
static const Foam::faceList & hexFaces ()
static constexpr label nPoints () noexcept
static constexpr label nEdges () noexcept
static constexpr label nFaces () noexcept
static boundBox returnReduce (const boundBox &bb)
Static Public Attributes
static const boundBox greatBox
static const boundBox invertedBox
static const FixedList< vector, 6 > faceNormals
Static Protected Member Functions
static bool box_box_overlaps (const point &minA, const point &maxA, const point &minB, const point &maxB)
static bool box_sphere_overlaps (const point &corner0, const point &corner1, const point &centre, const scalar radiusSqr)
Friends
Istream & operator>> (Istream &is, boundBox &bb)
Ostream & operator<< (Ostream &os, const boundBox &bb)
Detailed Description
A bounding box defined in terms of min/max extrema points.
Note
When a bounding box is created without any points, it creates an inverted bounding box. Points can be added later and the bounding box will grow to include them.
See also
Foam::treeBoundBox
Definition at line 63 of file boundBox.H.
Member Enumeration Documentation
directionBit
enum directionBit : direction
Enumerator
XDIR
1: x-direction. Same as (1 << vector::X)
YDIR
2: y-direction. Same as (1 << vector::Y)
ZDIR
4: z-direction. Same as (1 << vector::Z)
Definition at line 100 of file boundBox.H.
Constructor & Destructor Documentation
boundBox() [1/12]
boundBox () inline
Definition at line 101 of file boundBoxI.H.
boundBox() [2/12]
boundBox (const boundBox &) default
boundBox() [3/12]
boundBox (const boundBox & bb, bool doReduce)
Definition at line 65 of file boundBox.C.
References boundBox::reduce().
boundBox() [4/12]
boundBox (const point & p) inline explicit
Definition at line 115 of file boundBoxI.H.
boundBox() [5/12]
boundBox (const Foam::zero_one) inline explicit
Definition at line 108 of file boundBoxI.H.
boundBox() [6/12]
boundBox (const point & min, const point & max) inline
Definition at line 122 of file boundBoxI.H.
boundBox() [7/12]
boundBox (const Pair< point > & bb) inline explicit
TBD: Construct from bound box min/max points inline explicit boundBox(const MinMax<point>& bb);
Definition at line 129 of file boundBoxI.H.
boundBox() [8/12]
boundBox (const UList< point > & points, bool doReduce = true) explicit
Definition at line 76 of file boundBox.C.
References boundBox::add(), boundBox::points(), and boundBox::reduce().
boundBox() [9/12]
boundBox (const tmp< pointField > & tpoints, bool doReduce = true) explicit
Definition at line 89 of file boundBox.C.
References boundBox::add(), and boundBox::reduce().
boundBox() [10/12]
boundBox (const UList< point > & points, const labelUList & indices, bool doReduce = true)
Definition at line 102 of file boundBox.C.
References boundBox::add(), boundBox::points(), and boundBox::reduce().
boundBox() [11/12]
template<unsigned N> boundBox (const UList< point > & points, const FixedList< label, N > & indices, bool doReduce = true)
Definition at line 28 of file boundBoxTemplates.C.
References boundBox::add(), boundBox::points(), and boundBox::reduce().
boundBox() [12/12]
boundBox (Istream & is) inline explicit
Definition at line 136 of file boundBoxI.H.
References Foam::operator>>().
Member Function Documentation
box_box_overlaps()
bool box_box_overlaps (const point & minA, const point & maxA, const point & minB, const point & maxB) inline static protected
Definition at line 387 of file boundBoxI.H.
box_sphere_overlaps()
bool box_sphere_overlaps (const point & corner0, const point & corner1, const point & centre, const scalar radiusSqr) inline static protected
Definition at line 402 of file boundBoxI.H.
References Foam::magSqr(), Foam::min(), and VectorSpace< Form, Cmpt, Ncmpts >::nComponents.
null()
static const boundBox & null () inline static noexcept
Definition at line 120 of file boundBox.H.
References boundBox::invertedBox.
hexFaces()
const Foam::faceList & hexFaces () static
Definition at line 57 of file boundBox.C.
References hexCell::modelFaces().
nPoints()
static constexpr label nPoints () inline static constexpr noexcept
Definition at line 130 of file boundBox.H.
Referenced by boundBox::hexCorners().
nEdges()
static constexpr label nEdges () inline static constexpr noexcept
Definition at line 133 of file boundBox.H.
nFaces()
static constexpr label nFaces () inline static constexpr noexcept
Definition at line 136 of file boundBox.H.
Referenced by boundBox::faceCentres().
operator=()
boundBox & operator= (const boundBox &) default
empty()
bool empty () const inline
Definition at line 144 of file boundBoxI.H.
good()
bool good () const inline
Definition at line 156 of file boundBoxI.H.
Referenced by boundBox::intersect(), sampledMeshedSurface::update(), and boundBox::valid().
valid()
bool valid () const inline
Definition at line 215 of file boundBox.H.
References boundBox::good().
Referenced by isoSurfaceBase::blockCells(), searchableSphere::overlaps(), searchableBox::searchableBox(), and searchableBox::searchableBox().
min() [1/2]
const Foam::point & min () const inline noexcept
Definition at line 162 of file boundBoxI.H.
Referenced by eddy::bounds(), fieldExtents::calcFieldExtents(), voxelMeshSearch::centre(), boundBox::contains(), AABBTree< Type >::createBoxes(), dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::getSide(), voxelMeshSearch::index(), voxelMeshSearch::index3(), inverseDistance::index3(), waveMakerPointPatchVectorField::initialiseGeometry(), waveModel::initialiseGeometry(), dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::insertIndex(), boundBox::intersects(), indexedOctree< treeType >::nLeafs(), projectVertex::operator point(), Foam::operator<(), Foam::operator==(), searchableSphere::overlaps(), boundBox::overlaps(), inverseDistance::position(), Foam::readBoxDim(), PDRblock::reset(), treeBoundBox::subBbox(), treeBoundBox::subHalf(), treeBoundBox::subOverlaps(), voxelMeshSearch::voxelMeshSearch(), topoSet::writeDebug(), and voxelMeshSearch::writeGrid().
max() [1/2]
const Foam::point & max () const inline noexcept
Definition at line 168 of file boundBoxI.H.
Referenced by eddy::bounds(), fieldExtents::calcFieldExtents(), boundBox::contains(), waveMakerPointPatchVectorField::initialiseGeometry(), waveModel::initialiseGeometry(), boundBox::intersects(), Kmesh::Kmesh(), projectVertex::operator point(), Foam::operator<(), Foam::operator==(), orientedSurface::orientedSurface(), searchableSphere::overlaps(), boundBox::overlaps(), Foam::readBoxDim(), PDRblock::reset(), treeBoundBox::subBbox(), treeBoundBox::subHalf(), treeBoundBox::subOverlaps(), voxelMeshSearch::voxelMeshSearch(), and topoSet::writeDebug().
min() [2/2]
Foam::point & min () inline noexcept
Definition at line 174 of file boundBoxI.H.
max() [2/2]
Foam::point & max () inline noexcept
Definition at line 180 of file boundBoxI.H.
centre()
Foam::point centre () const inline
Definition at line 186 of file boundBoxI.H.
Referenced by boundBox::faceCentre(), advancingFrontAMI::findTargetFace(), and boundBox::midpoint().
span()
Foam::vector span () const inline
Definition at line 192 of file boundBoxI.H.
Referenced by booleanSurface::booleanSurface(), voxelMeshSearch::centre(), sensitivitySurface::computeRadius(), AABBTree< Type >::createBoxes(), voxelMeshSearch::index(), voxelMeshSearch::index3(), inverseDistance::index3(), Kmesh::Kmesh(), orientedSurface::orientedSurface(), porosityModel::porosityModel(), inverseDistance::position(), energySpectrum::read(), snappyVoxelMeshDriver::snappyVoxelMeshDriver(), sampledMeshedSurface::update(), points0MotionSolver::updateMesh(), and voxelMeshSearch::writeGrid().
mag()
Foam::scalar mag () const inline
Definition at line 198 of file boundBoxI.H.
Referenced by searchableSurfaces::checkSizes(), and refinementFeatures::checkSizes().
magSqr()
Foam::scalar magSqr () const inline
Definition at line 204 of file boundBoxI.H.
Referenced by advancingFrontAMI::findTargetFace(), and projectVertex::operator point().
volume()
Foam::scalar volume () const inline
Definition at line 210 of file boundBoxI.H.
References Foam::cmptProduct().
minDim()
Foam::scalar minDim () const inline
Definition at line 216 of file boundBoxI.H.
References Foam::cmptMin().
maxDim()
Foam::scalar maxDim () const inline
Definition at line 222 of file boundBoxI.H.
References Foam::cmptMax().
avgDim()
Foam::scalar avgDim () const inline
Definition at line 228 of file boundBoxI.H.
References Foam::cmptAv().
Referenced by treeBoundBox::typDim().
minDir()
Foam::direction minDir () const inline
Definition at line 234 of file boundBoxI.H.
References VectorSpace< Form, Cmpt, Ncmpts >::nComponents.
maxDir()
Foam::direction maxDir () const inline
Definition at line 254 of file boundBoxI.H.
References VectorSpace< Form, Cmpt, Ncmpts >::nComponents.
Referenced by AABBTree< Type >::createBoxes().
nDim()
int nDim () const inline
Definition at line 274 of file boundBoxI.H.
References VectorSpace< Form, Cmpt, Ncmpts >::nComponents.
hexCorner() [1/10]
template<direction CornerNumber> point hexCorner () const inline
Referenced by boundBox::intersects().
hexCorners()
Foam::tmp< Foam::pointField > hexCorners () const
Definition at line 122 of file boundBox.C.
References tmp< T >::New(), boundBox::nPoints(), and pts.
Referenced by boundBox::points().
points()
tmp< pointField > points () const inline
Definition at line 276 of file boundBox.H.
References boundBox::hexCorners().
Referenced by boundBox::boundBox(), boundBox::boundBox(), boundBox::boundBox(), and searchableRotatedBox::overlaps().
faceCentres()
Foam::tmp< Foam::pointField > faceCentres () const
Definition at line 140 of file boundBox.C.
References tmp< T >::New(), boundBox::nFaces(), and pts.
faceCentre()
Foam::point faceCentre (const direction facei) const
Definition at line 154 of file boundBox.C.
References Foam::abort(), boundBox::centre(), Foam::FatalError, FatalErrorInFunction, Foam::max(), Foam::min(), Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
reset() [1/4]
void reset () inline
Definition at line 295 of file boundBoxI.H.
Referenced by PatchTools::calcBounds(), boundBox::clear(), and sampledMeshedSurface::update().
reset() [2/4]
void reset (const Foam::zero_one) inline
Definition at line 302 of file boundBoxI.H.
References VectorSpace< Form, Cmpt, Ncmpts >::one, and VectorSpace< Form, Cmpt, Ncmpts >::zero.
reset() [3/4]
void reset (const point & pt) inline
Definition at line 309 of file boundBoxI.H.
reset() [4/4]
void reset (const point & min, const point & max) inline
Definition at line 316 of file boundBoxI.H.
References Foam::max(), and Foam::min().
clear()
void clear () inline
Definition at line 300 of file boundBox.H.
References boundBox::reset().
add() [1/9]
void add (const boundBox & bb) inline
Definition at line 323 of file boundBoxI.H.
References Foam::max(), and Foam::min().
Referenced by boundBox::boundBox(), boundBox::boundBox(), boundBox::boundBox(), boundBox::boundBox(), treeDataEdge::bounds(), treeDataFace::bounds(), treeDataPrimitivePatch< PatchType >::bounds(), treeDataCell::bounds(), treeDataEdge::bounds(), treeDataPoint::bounds(), treeDataCell::bounds(), searchableSurfacesQueries::bounds(), Foam::boundsImpl(), Foam::boundsImpl(), PatchTools::calcBounds(), boundBox::operator+=(), porosityModel::porosityModel(), and triSurface::writeStats().
add() [2/9]
void add (const point & pt) inline
Definition at line 330 of file boundBoxI.H.
References Foam::max(), and Foam::min().
add() [3/9]
void add (const point & pt0, const point & pt1) inline
Definition at line 337 of file boundBoxI.H.
References Foam::add().
add() [4/9]
void add (const Pair< point > & points) inline
Definition at line 344 of file boundBoxI.H.
References Foam::add(), UPtrList< T >::first(), and points.
add() [5/9]
void add (const UList< point > & points) inline
Definition at line 351 of file boundBoxI.H.
References Foam::add(), p, and points.
add() [6/9]
void add (const tmp< pointField > & tpoints) inline
Definition at line 360 of file boundBoxI.H.
References Foam::add(), and PtrList< T >::clear().
add() [7/9]
template<unsigned N> void add (const FixedList< point, N > & points)
Definition at line 49 of file boundBoxTemplates.C.
References Foam::add(), p, and points.
add() [8/9]
template<unsigned N> void add (const UList< point > & points, const FixedList< label, N > & indices)
Definition at line 62 of file boundBoxTemplates.C.
References Foam::add(), points, and UPtrList< T >::size().
add() [9/9]
template<class IntContainer > void add (const UList< point > & points, const IntContainer & indices)
Definition at line 87 of file boundBoxTemplates.C.
References Foam::add(), points, and UPtrList< T >::size().
grow() [1/2]
void grow (const scalar delta) inline
Definition at line 367 of file boundBoxI.H.
References delta.
Referenced by Foam::createTree(), searchableExtrudedCircle::searchableExtrudedCircle(), and sampledMeshedSurface::update().
grow() [2/2]
void grow (const vector & delta) inline
Definition at line 374 of file boundBoxI.H.
References delta.
inflate() [1/3]
void inflate (const scalar factor) inline
Definition at line 381 of file boundBoxI.H.
References Foam::mag().
Referenced by AMIInterpolation::createTree(), triSurfaceMesh::edgeTree(), treeBoundBox::extend(), treeBoundBox::extend(), meshToMeshMethod::maskCells(), primitiveMesh::pointInCellBB(), refinementFeatures::regionEdgeTrees(), Foam::simpleGeometricFilter(), triSurfaceSearch::tree(), triSurfaceRegionSearch::treeByRegion(), sampledMeshedSurface::update(), and propellerInfo::updateSampleDiskCells().
inflate() [2/3]
void inflate (Random & rndGen, const scalar factor)
Definition at line 416 of file boundBox.C.
References Foam::cmptMultiply(), Foam::mag(), Foam::max(), VectorSpace< Form, Cmpt, Ncmpts >::nComponents, rndGen, and Random::sample01().
inflate() [3/3]
void inflate (Random & r, const scalar factor, const scalar delta)
Definition at line 433 of file boundBox.C.
References delta, and rndGen.
reduce()
void reduce ()
Definition at line 178 of file boundBox.C.
References Foam::reduce().
Referenced by boundBox::boundBox(), boundBox::boundBox(), boundBox::boundBox(), boundBox::boundBox(), boundBox::boundBox(), porosityModel::porosityModel(), and distributedTriSurfaceMesh::writeStats().
returnReduce()
Foam::boundBox returnReduce (const boundBox & bb) static
Definition at line 185 of file boundBox.C.
intersects() [1/2]
bool intersects (const plane & pln) const
Definition at line 193 of file boundBox.C.
References doLocalCode.
intersects() [2/2]
bool intersects (const triPointRef & tri) const
Definition at line 227 of file boundBox.C.
References triangle< Point, PointRef >::a(), triangle< Point, PointRef >::areaNormal(), triangle< Point, PointRef >::b(), triangle< Point, PointRef >::c(), boundBox::hexCorner(), boundBox::max(), boundBox::min(), VectorSpace< Form, Cmpt, Ncmpts >::nComponents, triangle< Point, PointRef >::vecA(), triangle< Point, PointRef >::vecB(), triangle< Point, PointRef >::vecC(), and Foam::Zero.
overlaps() [1/2]
bool overlaps (const boundBox & bb) const inline
Definition at line 439 of file boundBoxI.H.
References boundBox::max(), and boundBox::min().
Referenced by inverseDistance::markBoundaries(), trackingInverseDistance::markBoundaries(), meshToMeshMethod::maskCells(), searchableBox::overlaps(), searchablePlate::overlaps(), searchableRotatedBox::overlaps(), and searchableSphere::overlaps().
overlaps() [2/2]
bool overlaps (const point & centre, const scalar radiusSqr) const inline
Definition at line 445 of file boundBoxI.H.
contains() [1/5]
bool contains (const point & pt) const inline
Definition at line 455 of file boundBoxI.H.
References Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
Referenced by isoSurfaceBase::blockCells(), trackingInverseDistance::markBoundaries(), primitiveMesh::pointInCellBB(), and Foam::simpleGeometricFilter().
contains() [2/5]
bool contains (const boundBox & bb) const inline
Definition at line 466 of file boundBoxI.H.
References boundBox::max(), and boundBox::min().
containsInside()
bool containsInside (const point & pt) const inline
Definition at line 472 of file boundBoxI.H.
References Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
contains() [3/5]
bool contains (const UList< point > & points) const
Definition at line 366 of file boundBox.C.
References UPtrList< T >::empty(), p, and points.
contains() [4/5]
template<unsigned N> bool contains (const UList< point > & points, const FixedList< label, N > & indices) const inline
Definition at line 112 of file boundBoxTemplates.C.
References points, and UPtrList< T >::size().
contains() [5/5]
template<class IntContainer > bool contains (const UList< point > & points, const IntContainer & indices) const inline
Definition at line 141 of file boundBoxTemplates.C.
References points, and UPtrList< T >::size().
containsAny() [1/3]
bool containsAny (const UList< point > & points) const
Definition at line 385 of file boundBox.C.
References UPtrList< T >::empty(), p, and points.
Referenced by searchableRotatedBox::overlaps().
containsAny() [2/3]
template<unsigned N> bool containsAny (const UList< point > & points, const FixedList< label, N > & indices) const inline
Definition at line 170 of file boundBoxTemplates.C.
References points, and UPtrList< T >::size().
containsAny() [3/3]
template<class IntContainer > bool containsAny (const UList< point > & points, const IntContainer & indices) const inline
Definition at line 203 of file boundBoxTemplates.C.
References points, and UPtrList< T >::size().
nearest()
Foam::point nearest (const point & p) const
Definition at line 404 of file boundBox.C.
operator&=()
void operator&= (const boundBox & bb)
Definition at line 447 of file boundBox.C.
References Foam::max(), and Foam::min().
operator+=()
void operator+= (const boundBox & bb) inline
Definition at line 466 of file boundBox.H.
References boundBox::add().
intersect()
bool intersect (const boundBox & bb) inline
Definition at line 481 of file boundBox.H.
References boundBox::good().
midpoint()
point midpoint () const inline
Definition at line 484 of file boundBox.H.
References boundBox::centre().
hexCorner() [2/10]
template<> Foam::point hexCorner () const inline
Definition at line 32 of file boundBoxI.H.
hexCorner() [3/10]
template<> Foam::point hexCorner () const inline
Definition at line 39 of file boundBoxI.H.
hexCorner() [4/10]
template<> Foam::point hexCorner () const inline
Definition at line 46 of file boundBoxI.H.
hexCorner() [5/10]
template<> Foam::point hexCorner () const inline
Definition at line 53 of file boundBoxI.H.
hexCorner() [6/10]
template<> Foam::point hexCorner () const inline
Definition at line 60 of file boundBoxI.H.
hexCorner() [7/10]
template<> Foam::point hexCorner () const inline
Definition at line 67 of file boundBoxI.H.
hexCorner() [8/10]
template<> Foam::point hexCorner () const inline
Definition at line 74 of file boundBoxI.H.
hexCorner() [9/10]
template<> Foam::point hexCorner () const inline
Definition at line 81 of file boundBoxI.H.
hexCorner() [10/10]
template<Foam::direction CornerNumber> Foam::point hexCorner () const inline
Definition at line 92 of file boundBoxI.H.
Friends And Related Symbol Documentation
operator>>
Istream & operator>> (Istream & is, boundBox & bb) friend
operator<<
Ostream & operator<< (Ostream & os, const boundBox & bb) friend
Member Data Documentation
greatBox
const Foam::boundBox greatBox static
Definition at line 108 of file boundBox.H.
invertedBox
const Foam::boundBox invertedBox static
Definition at line 111 of file boundBox.H.
Referenced by boundBox::null(), and treeBoundBox::null().
faceNormals
const Foam::FixedList< Foam::vector, 6 > faceNormals static
Definition at line 114 of file boundBox.H.
Referenced by searchableBox::getNormal().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/boundBox/boundBox.H
src/OpenFOAM/meshes/boundBox/boundBox.C
src/OpenFOAM/meshes/boundBox/boundBoxI.H
src/OpenFOAM/meshes/boundBox/boundBoxTemplates.C