OpenFOAM: calculatedProcessorGAMGInterfaceField Class Reference
calculatedProcessorGAMGInterfaceField Class Reference
GAMG agglomerated processor interface field.
#include <calculatedProcessorGAMGInterfaceField.H>
Public Member Functions
TypeName ("calculatedProcessor")
calculatedProcessorGAMGInterfaceField (const GAMGInterface &GAMGCp, const lduInterfaceField &fineInterface)
calculatedProcessorGAMGInterfaceField (const GAMGInterface &GAMGCp, const bool doTransform, const int rank)
virtual ~calculatedProcessorGAMGInterfaceField ()=default
label size () const
virtual void initInterfaceMatrixUpdate (solveScalarField &result, const bool add, const lduAddressing &lduAddr, const label patchId, const solveScalarField &psiInternal, const scalarField &coeffs, const direction cmpt, const Pstream::commsTypes commsType) const
virtual void updateInterfaceMatrix (solveScalarField &result, const bool add, const lduAddressing &lduAddr, const label patchId, const solveScalarField &psiInternal, const scalarField &coeffs, const direction cmpt, const Pstream::commsTypes commsType) const
virtual label comm () const
virtual int myProcNo () const
virtual int neighbProcNo () const
virtual bool doTransform () const
virtual const tensorField & forwardT () const
virtual int rank () const
Public Member Functions inherited from GAMGInterfaceField
TypeName ("GAMGInterfaceField")
declareRunTimeSelectionTable (autoPtr, GAMGInterfaceField, lduInterfaceField,(const GAMGInterface &GAMGCp, const lduInterfaceField &fineInterface),(GAMGCp, fineInterface))
declareRunTimeSelectionTable (autoPtr, GAMGInterfaceField, lduInterface,(const GAMGInterface &GAMGCp, const bool doTransform, const int rank),(GAMGCp, doTransform, rank))
GAMGInterfaceField (const GAMGInterface &GAMGCp, const lduInterfaceField &)
GAMGInterfaceField (const GAMGInterface &GAMGCp, const bool doTransform, const int rank)
const GAMGInterface & interface () const
Public Member Functions inherited from lduInterfaceField
TypeName ("lduInterfaceField")
lduInterfaceField (const lduInterfaceField &)=delete
void operator= (const lduInterfaceField &)=delete
lduInterfaceField (const lduInterface &patch)
virtual ~lduInterfaceField ()=default
const lduInterface & interface () const noexcept
virtual const word & interfaceFieldType () const
virtual bool ready () const
bool updatedMatrix () const noexcept
bool updatedMatrix (bool flag) const noexcept
template<class Type >
void addToInternalField (Field< Type > &result, const bool add, const labelUList &faceCells, const scalarField &coeffs, const Field< Type > &vals) const
bool & updatedMatrix () noexcept
Public Member Functions inherited from processorLduInterfaceField
TypeName ("processorLduInterfaceField")
processorLduInterfaceField ()=default
virtual ~processorLduInterfaceField ()=default
template<class Type >
void transformCoupleField (Field< Type > &f) const
void transformCoupleField (solveScalarField &f, const direction cmpt) const
Additional Inherited Members
Static Public Member Functions inherited from GAMGInterfaceField
static autoPtr< GAMGInterfaceField > New (const GAMGInterface &GAMGCp, const lduInterfaceField &fineInterface)
static autoPtr< GAMGInterfaceField > New (const GAMGInterface &GAMGCp, const bool doTransform, const int rank)
Detailed Description
GAMG agglomerated processor interface field.
Source files
calculatedProcessorGAMGInterfaceField.H
calculatedProcessorGAMGInterfaceField.C
Definition at line 48 of file calculatedProcessorGAMGInterfaceField.H.
Constructor & Destructor Documentation
calculatedProcessorGAMGInterfaceField() [1/2]
calculatedProcessorGAMGInterfaceField (const GAMGInterface & GAMGCp, const lduInterfaceField & fineInterface)
Definition at line 47 of file calculatedProcessorGAMGInterfaceField.C.
References p, and Foam::refCast().
calculatedProcessorGAMGInterfaceField() [2/2]
calculatedProcessorGAMGInterfaceField (const GAMGInterface & GAMGCp, const bool doTransform, const int rank)
Definition at line 68 of file calculatedProcessorGAMGInterfaceField.C.
~calculatedProcessorGAMGInterfaceField()
virtual ~calculatedProcessorGAMGInterfaceField () virtual default
Member Function Documentation
TypeName()
TypeName ("calculatedProcessor")
size()
label size () const inline
Definition at line 126 of file calculatedProcessorGAMGInterfaceField.H.
References GAMGInterface::size().
initInterfaceMatrixUpdate()
void initInterfaceMatrixUpdate (solveScalarField & result, const bool add, const lduAddressing & lduAddr, const label patchId, const solveScalarField & psiInternal, const scalarField & coeffs, const direction cmpt, const Pstream::commsTypes commsType) const virtual
Reimplemented from lduInterfaceField.
Definition at line 87 of file calculatedProcessorGAMGInterfaceField.C.
References UPstream::floatTransfer, UPstream::nonBlocking, UPstream::nRequests(), UIPstream::read(), and UOPstream::write().
updateInterfaceMatrix()
void updateInterfaceMatrix (solveScalarField & result, const bool add, const lduAddressing & lduAddr, const label patchId, const solveScalarField & psiInternal, const scalarField & coeffs, const direction cmpt, const Pstream::commsTypes commsType) const virtual
Implements lduInterfaceField.
Definition at line 141 of file calculatedProcessorGAMGInterfaceField.C.
References Foam::add(), UPstream::finishedRequest(), UPstream::floatTransfer, UPstream::nonBlocking, lduAddressing::patchAddr(), patchId(), and UPstream::waitRequest().
comm()
virtual label comm () const inline virtual
Implements processorLduInterfaceField.
Definition at line 164 of file calculatedProcessorGAMGInterfaceField.H.
References calculatedProcessorGAMGInterface::comm().
myProcNo()
virtual int myProcNo () const inline virtual
Implements processorLduInterfaceField.
Definition at line 170 of file calculatedProcessorGAMGInterfaceField.H.
References calculatedProcessorGAMGInterface::myProcNo().
neighbProcNo()
virtual int neighbProcNo () const inline virtual
Implements processorLduInterfaceField.
Definition at line 176 of file calculatedProcessorGAMGInterfaceField.H.
References calculatedProcessorGAMGInterface::neighbProcNo().
doTransform()
virtual bool doTransform () const inline virtual
Implements processorLduInterfaceField.
Definition at line 182 of file calculatedProcessorGAMGInterfaceField.H.
forwardT()
virtual const tensorField & forwardT () const inline virtual
Implements processorLduInterfaceField.
Definition at line 188 of file calculatedProcessorGAMGInterfaceField.H.
References calculatedProcessorGAMGInterface::forwardT().
rank()
virtual int rank () const inline virtual
Implements processorLduInterfaceField.
Definition at line 194 of file calculatedProcessorGAMGInterfaceField.H.
The documentation for this class was generated from the following files:
src/overset/lduPrimitiveProcessorInterface/GAMG/calculatedProcessorGAMGInterfaceField.H
src/overset/lduPrimitiveProcessorInterface/GAMG/calculatedProcessorGAMGInterfaceField.C