OpenFOAM: snGradScheme< Type > Class Template Reference
snGradScheme< Type > Class Template Reference abstract
Numerics » Finite volume numerical schemes » Surface normal gradient schemes
Abstract base class for runtime selected snGrad surface normal gradient schemes.
#include <snGradScheme.H>
Public Member Functions
virtual const word & type () const =0
declareRunTimeSelectionTable (tmp, snGradScheme, Mesh,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
snGradScheme (const fvMesh &mesh)
virtual ~snGradScheme ()=default
const fvMesh & mesh () const
virtual tmp< surfaceScalarField > deltaCoeffs (const GeometricField< Type, fvPatchField, volMesh > &) const =0
virtual bool corrected () const noexcept
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > &) const
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const GeometricField< Type, fvPatchField, volMesh > &) const
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const tmp< GeometricField< Type, fvPatchField, volMesh > > &) const
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Static Public Member Functions
static tmp< snGradScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &, const word &snGradName="snGrad")
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > sndGrad (const GeometricField< Type, fvPatchField, volMesh > &, const word &snGradName="sndGrad")
Detailed Description
template<class Type>
class Foam::fv::snGradScheme< Type >
Abstract base class for runtime selected snGrad surface normal gradient schemes.
A surface normal gradient is evaluated at a cell face. It is the normal-to-face component of the gradient of values at the centres of two cells that the face connects.
Unit-surface-normal vector decomposition is based on the so-called over-relaxed approach. Orthogonal components are treated implicitly and non-orthogonal components are treated explicitly with (or without) various limiters.
Source files
snGradScheme.H
snGradScheme.C
Definition at line 72 of file snGradScheme.H.
Constructor & Destructor Documentation
snGradScheme()
template<class Type > snGradScheme (const fvMesh & mesh) inline
Definition at line 112 of file snGradScheme.H.
~snGradScheme()
template<class Type > virtual ~snGradScheme () virtual default
Member Function Documentation
type()
template<class Type > virtual const word & type () const pure virtual
declareRunTimeSelectionTable()
template<class Type > declareRunTimeSelectionTable (tmp , snGradScheme< Type > , Mesh , (const fvMesh &mesh, Istream &schemeData) , (mesh, schemeData))
New()
template<class Type > tmp< snGradScheme< Type > > New (const fvMesh & mesh, Istream & schemeData) static
Definition at line 41 of file snGradScheme.C.
References Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, FatalIOErrorInLookup, InfoInFunction, mesh, and Foam::nl.
Referenced by laplacianScheme< Type, GType >::laplacianScheme(), and Foam::fvc::snGrad().
mesh()
template<class Type > const fvMesh & mesh () const inline
Definition at line 135 of file snGradScheme.H.
Referenced by CentredFitSnGradScheme< Type, Polynomial, Stencil >::correction(), CentredFitSnGradScheme< Type, Polynomial, Stencil >::deltaCoeffs(), correctedSnGrad< Type >::deltaCoeffs(), faceCorrectedSnGrad< Type >::deltaCoeffs(), limitedSnGrad< Type >::deltaCoeffs(), orthogonalSnGrad< Type >::deltaCoeffs(), relaxedSnGrad< Type >::deltaCoeffs(), skewCorrectedSnGrad< Type >::deltaCoeffs(), and uncorrectedSnGrad< Type >::deltaCoeffs().
snGrad() [1/3]
template<class Type > tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const GeometricField< Type, fvPatchField, volMesh > & vf, const tmp< surfaceScalarField > & tdeltaCoeffs, const word & snGradName = "snGrad") static
Definition at line 85 of file snGradScheme.C.
References forAll, mesh, IOobjectOption::NO_READ, and IOobjectOption::NO_WRITE.
sndGrad()
template<class Type > tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > sndGrad (const GeometricField< Type, fvPatchField, volMesh > & vf, const word & snGradName = "sndGrad") static
Definition at line 150 of file snGradScheme.C.
deltaCoeffs()
template<class Type > virtual tmp< surfaceScalarField > deltaCoeffs (const GeometricField< Type, fvPatchField, volMesh > &) const pure virtual
Implemented in CentredFitSnGradScheme< Type, Polynomial, Stencil >, correctedSnGrad< Type >, faceCorrectedSnGrad< Type >, limitedSnGrad< Type >, orthogonalSnGrad< Type >, relaxedSnGrad< Type >, skewCorrectedSnGrad< Type >, and uncorrectedSnGrad< Type >.
corrected()
template<class Type > virtual bool corrected () const inline virtual noexcept
Reimplemented in CentredFitSnGradScheme< Type, Polynomial, Stencil >, correctedSnGrad< Type >, faceCorrectedSnGrad< Type >, limitedSnGrad< Type >, orthogonalSnGrad< Type >, relaxedSnGrad< Type >, skewCorrectedSnGrad< Type >, and uncorrectedSnGrad< Type >.
Definition at line 165 of file snGradScheme.H.
correction()
template<class Type > virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > &) const inline virtual
Reimplemented in correctedSnGrad< Type >, faceCorrectedSnGrad< Type >, limitedSnGrad< Type >, orthogonalSnGrad< Type >, relaxedSnGrad< Type >, skewCorrectedSnGrad< Type >, uncorrectedSnGrad< Type >, and CentredFitSnGradScheme< Type, Polynomial, Stencil >.
Definition at line 172 of file snGradScheme.H.
snGrad() [2/3]
template<class Type > tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const GeometricField< Type, fvPatchField, volMesh > & vf) const virtual
Definition at line 162 of file snGradScheme.C.
References Foam::correction().
snGrad() [3/3]
template<class Type > tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf) const
Definition at line 183 of file snGradScheme.C.
References PtrList< T >::clear().
The documentation for this class was generated from the following files:
src/finiteVolume/finiteVolume/snGradSchemes/snGradScheme/snGradScheme.H
src/finiteVolume/finiteVolume/snGradSchemes/snGradScheme/snGradScheme.C