OpenFOAM: CircularBuffer< T > Class Template Reference
CircularBuffer< T > Class Template Reference
A simple list of objects of type <T> that is intended to be used as a circular buffer (eg, a FIFO) when the alloc/free overhead associated with a linked-list approach is to be avoided.
#include <CircularBuffer.H>
Classes
class const_iterator
Public Types
typedef T value_type
typedef T * pointer
typedef const T * const_pointer
typedef T & reference
typedef const T & const_reference
typedef label size_type
typedef label difference_type
Public Member Functions
constexpr CircularBuffer () noexcept
CircularBuffer (const label len)
CircularBuffer (const CircularBuffer< T > &list)
CircularBuffer (CircularBuffer< T > &&list)
CircularBuffer (Istream &is)
label capacity () const noexcept
bool empty () const noexcept
label size () const noexcept
label space () const noexcept
labelRange range_one () const noexcept
labelRange range_two () const noexcept
SubList< T > array_one ()
SubList< T > array_two ()
const SubList< T > array_one () const
const SubList< T > array_two () const
T & front ()
T & back ()
const T & front () const
const T & back () const
void reserve (const label len)
void reserve_nocopy (const label len)
void clear () noexcept
void clearStorage ()
void swap (CircularBuffer< T > &other)
label find (const T &val, label pos=0) const
bool contains (const T &val, label pos=0) const
void push_front (const T &val)
void push_front (T &&val)
void push_back (const T &val)
void push_back (T &&val)
void pop_front (label n=1)
void pop_back (label n=1)
void push_back (const UList< T > &list)
template<class Addr >
void push_back (const IndirectListBase< T, Addr > &list)
label push_uniq (const T &val)
List< T > list () const
void reverse ()
List< T > operator() () const
T & operator[] (const label i)
const T & operator[] (const label i) const
void operator= (const CircularBuffer< T > &list)
void operator= (CircularBuffer< T > &&list)
void operator= (const T &val)
void operator= (const Foam::zero)
void operator= (const UList< T > &rhs)
template<class AnyAddr >
void operator= (const IndirectListBase< T, AnyAddr > &rhs)
Ostream & info (Ostream &os) const
Istream & readList (Istream &is)
Ostream & writeList (Ostream &os, const label shortLen=0) const
const_iterator cbegin () const
const_iterator cend () const
const_iterator begin () const
const_iterator end () const
bool found (const T &val, label pos=0) const
T & first ()
const T & first () const
T & last ()
const T & last () const
void append (const T &val)
void append (T &&val)
void append (const UList< T > &list)
label appendUniq (const T &val)
Static Public Member Functions
static constexpr label min_size () noexcept
Friends
Istream & operator>> (Istream &is, CircularBuffer< T > &list)
Ostream & operator<< (Ostream &os, const CircularBuffer< T > &list)
Detailed Description
template<class T>
class Foam::CircularBuffer< T >
A simple list of objects of type <T> that is intended to be used as a circular buffer (eg, a FIFO) when the alloc/free overhead associated with a linked-list approach is to be avoided.
The internal storage is addressed by independent begin/end markers.
The begin marker points to the front.
The end marker is a one-past the back.
This results in a variety ofr different possible buffer states:
empty (begin == end)
simple/linear (begin < end) has no wrapping:
   |.|.|.|a|b|c|d|.|.|.|
   beg ___^
   end ___________^
split (begin > end):
   |f|g|h|i|.|.|.|a|b|c|d|e|
   end _____^
   beg ___________^
The methods range_one(), range_two() return the internal indexing and the methods array_one(), array_two() provide direct access to the internal contents.
When filling the buffer, the internal storage will be resized (doubling strategy) as required. When this occurs, the new list will be linearized with begin = 0.
Simultaneously when filling, the storage buffer will be over-allocated to avoid ambiguity when (begin == end), which represents an empty buffer and not a full buffer. Eg,
    |c|d|.|a|b|
    end _^
    beg ___^
after appending one more, it would be incorrect to simply fill the available space:
    |c|d|e|a|b|
    end ___^        WRONG : would represent empty!
    beg ___^
the storage is instead increased (doubled) and rebalanced before the append occurs (old capacity 5, new capacity 10):
    |a|b|c|d|e|.|.|.|.|.|
    _^_ beg
    end _______^
Source files
CircularBuffer.H
CircularBuffer.C
CircularBufferI.H
CircularBufferIO.C
Definition at line 116 of file CircularBuffer.H.
Member Typedef Documentation
value_type
template<class T > typedef T value_type
Definition at line 156 of file CircularBuffer.H.
pointer
template<class T > typedef T* pointer
Definition at line 159 of file CircularBuffer.H.
const_pointer
template<class T > typedef const T* const_pointer
Definition at line 162 of file CircularBuffer.H.
reference
template<class T > typedef T& reference
Definition at line 165 of file CircularBuffer.H.
const_reference
template<class T > typedef const T& const_reference
Definition at line 168 of file CircularBuffer.H.
size_type
template<class T > typedef label size_type
Definition at line 171 of file CircularBuffer.H.
difference_type
template<class T > typedef label difference_type
Definition at line 174 of file CircularBuffer.H.
Constructor & Destructor Documentation
CircularBuffer() [1/5]
template<class T > constexpr CircularBuffer () inline constexpr noexcept
Definition at line 107 of file CircularBufferI.H.
CircularBuffer() [2/5]
template<class T > CircularBuffer (const label len) inline explicit
Definition at line 116 of file CircularBufferI.H.
CircularBuffer() [3/5]
template<class T > CircularBuffer (const CircularBuffer< T > & list) inline
Definition at line 125 of file CircularBufferI.H.
CircularBuffer() [4/5]
template<class T > CircularBuffer (CircularBuffer< T > && list) inline
Definition at line 137 of file CircularBufferI.H.
References CircularBuffer< T >::list().
CircularBuffer() [5/5]
template<class T > CircularBuffer (Istream & is) explicit
Definition at line 28 of file CircularBufferIO.C.
Member Function Documentation
min_size()
template<class T > static constexpr label min_size () inline static constexpr noexcept
Definition at line 203 of file CircularBuffer.H.
capacity()
template<class T > Foam::label capacity () const inline noexcept
Definition at line 154 of file CircularBufferI.H.
References UPtrList< T >::size().
empty()
template<class T > bool empty () const inline noexcept
Definition at line 161 of file CircularBufferI.H.
References UPtrList< T >::empty().
size()
template<class T > Foam::label size () const inline noexcept
Definition at line 168 of file CircularBufferI.H.
References Foam::diff().
Referenced by CircularBuffer< T >::cend().
space()
template<class T > Foam::label space () const inline noexcept
Definition at line 182 of file CircularBufferI.H.
range_one()
template<class T > Foam::labelRange range_one () const inline noexcept
Definition at line 189 of file CircularBufferI.H.
range_two()
template<class T > Foam::labelRange range_two () const inline noexcept
Definition at line 201 of file CircularBufferI.H.
array_one() [1/2]
template<class T > Foam::SubList< T > array_one ()
Definition at line 70 of file CircularBuffer.C.
array_two() [1/2]
template<class T > Foam::SubList< T > array_two ()
Definition at line 78 of file CircularBuffer.C.
array_one() [2/2]
template<class T > const Foam::SubList< T > array_one () const
Definition at line 86 of file CircularBuffer.C.
array_two() [2/2]
template<class T > const Foam::SubList< T > array_two () const
Definition at line 94 of file CircularBuffer.C.
front() [1/2]
template<class T > T & front () inline
Definition at line 259 of file CircularBufferI.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Referenced by CircularBuffer< T >::first(), and CircularBuffer< T >::first().
back() [1/2]
template<class T > T & back () inline
Definition at line 283 of file CircularBufferI.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Referenced by CircularBuffer< T >::last(), and CircularBuffer< T >::last().
front() [2/2]
template<class T > const T & front () const inline
Definition at line 271 of file CircularBufferI.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
back() [2/2]
template<class T > const T & back () const inline
Definition at line 295 of file CircularBufferI.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
reserve()
template<class T > void reserve (const label len) inline
Definition at line 238 of file CircularBufferI.H.
reserve_nocopy()
template<class T > void reserve_nocopy (const label len) inline
Definition at line 245 of file CircularBufferI.H.
clear()
template<class T > void clear () inline noexcept
Definition at line 208 of file CircularBufferI.H.
clearStorage()
template<class T > void clearStorage () inline
Definition at line 215 of file CircularBufferI.H.
References PtrList< T >::clear().
swap()
template<class T > void swap (CircularBuffer< T > & other) inline
Definition at line 223 of file CircularBufferI.H.
References UPtrList< T >::swap().
find()
template<class T > Foam::label find (const T & val, label pos = 0) const
Definition at line 102 of file CircularBuffer.C.
References Foam::pos(), and UPtrList< T >::size().
contains()
template<class T > bool contains (const T & val, label pos = 0) const inline
Definition at line 252 of file CircularBufferI.H.
References Foam::pos().
Referenced by CircularBuffer< T >::found().
push_front() [1/2]
template<class T > void push_front (const T & val) inline
Definition at line 307 of file CircularBufferI.H.
References reserve().
push_front() [2/2]
template<class T > void push_front (T && val) inline
Definition at line 319 of file CircularBufferI.H.
References reserve().
push_back() [1/4]
template<class T > void push_back (const T & val) inline
Definition at line 331 of file CircularBufferI.H.
References reserve().
Referenced by CircularBuffer< T >::append(), CircularBuffer< T >::append(), and CircularBuffer< T >::append().
push_back() [2/4]
template<class T > void push_back (T && val) inline
Definition at line 343 of file CircularBufferI.H.
References reserve().
pop_front()
template<class T > void pop_front (label n = 1) inline
Definition at line 355 of file CircularBufferI.H.
References n.
pop_back()
template<class T > void pop_back (label n = 1) inline
Definition at line 372 of file CircularBufferI.H.
References n.
push_back() [3/4]
template<class T > void push_back (const UList< T > & list) inline
Definition at line 404 of file CircularBufferI.H.
References reserve(), and UPtrList< T >::size().
push_back() [4/4]
template<class T > template<class Addr > void push_back (const IndirectListBase< T, Addr > & list) inline
Definition at line 425 of file CircularBufferI.H.
References reserve(), and UPtrList< T >::size().
push_uniq()
template<class T > Foam::label push_uniq (const T & val) inline
Definition at line 389 of file CircularBufferI.H.
Referenced by CircularBuffer< T >::appendUniq().
list()
template<class T > Foam::List< T > list () const
Definition at line 154 of file CircularBuffer.C.
References UPtrList< T >::size().
Referenced by CircularBuffer< T >::CircularBuffer(), and CircularBuffer< T >::operator()().
reverse()
template<class T > void reverse ()
Definition at line 141 of file CircularBuffer.C.
References n, and Foam::Swap().
operator()()
template<class T > List< T > operator() () const inline
Definition at line 338 of file CircularBuffer.H.
References CircularBuffer< T >::list().
operator[]() [1/2]
template<class T > T & operator[] (const label i) inline
Definition at line 450 of file CircularBufferI.H.
operator[]() [2/2]
template<class T > const T & operator[] (const label i) const inline
Definition at line 458 of file CircularBufferI.H.
operator=() [1/6]
template<class T > void operator= (const CircularBuffer< T > & list) inline
Definition at line 466 of file CircularBufferI.H.
References clear(), reserve(), UPtrList< T >::size(), and T.
operator=() [2/6]
template<class T > void operator= (CircularBuffer< T > && list) inline
Definition at line 503 of file CircularBufferI.H.
operator=() [3/6]
template<class T > void operator= (const T & val) inline
Definition at line 516 of file CircularBufferI.H.
operator=() [4/6]
template<class T > void operator= (const Foam::zero) inline
Definition at line 524 of file CircularBufferI.H.
References Foam::Zero.
operator=() [5/6]
template<class T > void operator= (const UList< T > & rhs) inline
Definition at line 532 of file CircularBufferI.H.
operator=() [6/6]
template<class T > template<class AnyAddr > void operator= (const IndirectListBase< T, AnyAddr > & rhs) inline
Definition at line 540 of file CircularBufferI.H.
info()
template<class T > Foam::Ostream & info (Ostream & os) const
<< " one=" << this->range_one() << this->array_one() << " two=" << this->range_two() << this->array_two()
Definition at line 37 of file CircularBufferIO.C.
References Foam::nl, and os().
readList()
template<class T > Foam::Istream & readList (Istream & is)
Definition at line 51 of file CircularBufferIO.C.
References token::BEGIN_LIST, Foam::dynamicCast(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, FUNCTION_NAME, Foam::nl, PtrList< T >::resize(), UPtrList< T >::size(), and PtrList< T >::transfer().
writeList()
template<class T > Foam::Ostream & writeList (Ostream & os, const label shortLen = 0) const
Definition at line 144 of file CircularBufferIO.C.
References Foam::abort(), token::BEGIN_LIST, OSstream::beginRawWrite(), IOstreamOption::BINARY, IOstream::check(), UPtrList< T >::empty(), token::END_LIST, OSstream::endRawWrite(), Foam::FatalError, FatalErrorInFunction, IOstreamOption::format(), FUNCTION_NAME, Foam::nl, os(), UPtrList< T >::size(), token::SPACE, T, and OSstream::writeRaw().
cbegin()
template<class T > const_iterator cbegin () const inline
Definition at line 458 of file CircularBuffer.H.
Referenced by CircularBuffer< T >::begin().
cend()
template<class T > const_iterator cend () const inline
Definition at line 464 of file CircularBuffer.H.
References CircularBuffer< T >::size().
Referenced by CircularBuffer< T >::end().
begin()
template<class T > const_iterator begin () const inline
Definition at line 470 of file CircularBuffer.H.
References CircularBuffer< T >::cbegin().
end()
template<class T > const_iterator end () const inline
Definition at line 473 of file CircularBuffer.H.
References CircularBuffer< T >::cend().
found()
template<class T > bool found (const T & val, label pos = 0) const inline
Definition at line 479 of file CircularBuffer.H.
References CircularBuffer< T >::contains(), and Foam::pos().
first() [1/2]
template<class T > T & first () inline
Definition at line 486 of file CircularBuffer.H.
References CircularBuffer< T >::front().
first() [2/2]
template<class T > const T & first () const inline
Definition at line 490 of file CircularBuffer.H.
References CircularBuffer< T >::front().
last() [1/2]
template<class T > T & last () inline
Definition at line 494 of file CircularBuffer.H.
References CircularBuffer< T >::back().
last() [2/2]
template<class T > const T & last () const inline
Definition at line 498 of file CircularBuffer.H.
References CircularBuffer< T >::back().
append() [1/3]
template<class T > void append (const T & val) inline
Definition at line 502 of file CircularBuffer.H.
References CircularBuffer< T >::push_back().
append() [2/3]
template<class T > void append (T && val) inline
Definition at line 506 of file CircularBuffer.H.
References CircularBuffer< T >::push_back().
append() [3/3]
template<class T > void append (const UList< T > & list) inline
Definition at line 510 of file CircularBuffer.H.
References CircularBuffer< T >::push_back().
appendUniq()
template<class T > label appendUniq (const T & val) inline
Definition at line 514 of file CircularBuffer.H.
References CircularBuffer< T >::push_uniq().
Friends And Related Symbol Documentation
operator>>
template<class T > Istream & operator>> (Istream & is, CircularBuffer< T > & list) friend
Definition at line 524 of file CircularBuffer.H.
operator<<
template<class T > Ostream & operator<< (Ostream & os, const CircularBuffer< T > & list) friend
Definition at line 535 of file CircularBuffer.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/Buffers/CircularBuffer.H
src/OpenFOAM/containers/Buffers/CircularBuffer.C
src/OpenFOAM/containers/Buffers/CircularBufferI.H
src/OpenFOAM/containers/Buffers/CircularBufferIO.C