OpenFOAM: turbulenceFields Class Reference
turbulenceFields Class Reference
FunctionObjects » Field function objects
Computes various turbulence-related quantities that are not typically output during calculations, and stores/writes them on the mesh database for further manipulation.
#include <turbulenceFields.H>
Public Types
enum compressibleField {
cfK , cfEpsilon , cfOmega , cfNuTilda ,
cfMut , cfMuEff , cfAlphat , cfAlphaEff ,
cfR , cfDevRhoReff , cfL , cfI ,
cfLESRegion , cffd
}
enum incompressibleField {
ifK , ifEpsilon , ifOmega , ifNuTilda ,
ifNut , ifNuEff , ifR , ifDevReff ,
ifL , ifI , ifLESRegion , iffd
}
Public Member Functions
TypeName ("turbulenceFields")
turbulenceFields (const word &name, const Time &runTime, const dictionary &dict)
turbulenceFields (const turbulenceFields &)=delete
void operator= (const turbulenceFields &)=delete
virtual ~turbulenceFields ()=default
virtual bool read (const dictionary &)
virtual bool execute ()
virtual bool write ()
template<class Model >
Foam::tmp< Foam::volScalarField > nuTilda (const Model &model) const
template<class Model >
Foam::tmp< Foam::volScalarField > L (const Model &model) const
template<class Model >
Foam::tmp< Foam::volScalarField > I (const Model &model) const
Public Member Functions inherited from fvMeshFunctionObject
TypeName ("fvMeshFunctionObject")
fvMeshFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
fvMeshFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
virtual ~fvMeshFunctionObject ()=default
Public Member Functions inherited from regionFunctionObject
TypeName ("regionFunctionObject")
regionFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
regionFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
virtual ~regionFunctionObject ()=default
template<class ObjectType >
const ObjectType * lookupObjectPtr (const word &fieldName) const
template<class ObjectType >
ObjectType * lookupObjectRefPtr (const word &fieldName) const
Public Member Functions inherited from stateFunctionObject
stateFunctionObject (const word &name, const Time &runTime)
virtual ~stateFunctionObject ()=default
dictionary & propertyDict ()
bool foundProperty (const word &entryName) const
void clearTrigger ()
label getTrigger () const
bool setTrigger (const label triggeri)
bool getDict (const word &entryName, dictionary &dict) const
bool getObjectDict (const word &objectName, const word &entryName, dictionary &dict) const
template<class Type >
Type getProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getProperty (const word &entryName, Type &value) const
template<class Type >
void setProperty (const word &entryName, const Type &value)
template<class Type >
Type getObjectProperty (const word &objectName, const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getObjectProperty (const word &objectName, const word &entryName, Type &value) const
template<class Type >
void setObjectProperty (const word &objectName, const word &entryName, const Type &value)
template<class Type >
void setResult (const word &entryName, const Type &value)
template<class Type >
void setObjectResult (const word &objectName, const word &entryName, const Type &value)
template<class Type >
Type getResult (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
Type getObjectResult (const word &objectName, const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getObjectResult (const word &objectName, const word &entryName, Type &value) const
word resultType (const word &entryName) const
word objectResultType (const word &objectName, const word &entryName) const
wordList objectResultEntries () const
wordList objectResultEntries (const word &objectName) const
void writeResultEntries (Ostream &os) const
void writeResultEntries (const word &objectName, Ostream &os) const
void writeAllResultEntries (Ostream &os) const
Public Member Functions inherited from timeFunctionObject
timeFunctionObject (const word &name, const Time &runTime)
virtual ~timeFunctionObject ()=default
const Time & time () const
objectRegistry & storedObjects ()
const objectRegistry & storedObjects () const
Public Member Functions inherited from functionObject
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name, const bool withNamePrefix=defaultUseNamePrefix)
autoPtr< functionObject > clone () const
virtual ~functionObject ()=default
virtual const word & type () const =0
const word & name () const noexcept
bool useNamePrefix () const noexcept
bool useNamePrefix (bool on) noexcept
virtual bool execute (const label subIndex)
virtual bool end ()
virtual bool adjustTimeStep ()
virtual bool filesModified () const
virtual void updateMesh (const mapPolyMesh &mpm)
virtual void movePoints (const polyMesh &mesh)
Static Public Attributes
static const Enum< compressibleField > compressibleFieldNames_
static const Enum< incompressibleField > incompressibleFieldNames_
static const word modelName_
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
static bool defaultUseNamePrefix
static word outputPrefix
Protected Member Functions
void initialise ()
bool compressible ()
template<class Type >
void processField (const word &fieldName, const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvalue)
template<class Model >
tmp< volScalarField > nuTilda (const Model &model) const
template<class Model >
tmp< volScalarField > L (const Model &model) const
template<class Model >
tmp< volScalarField > I (const Model &model) const
Protected Member Functions inherited from fvMeshFunctionObject
fvMeshFunctionObject (const fvMeshFunctionObject &)=delete
void operator= (const fvMeshFunctionObject &)=delete
Protected Member Functions inherited from regionFunctionObject
virtual const objectRegistry & obr () const
template<class ObjectType >
bool foundObject (const word &fieldName) const
template<class ObjectType >
const ObjectType * cfindObject (const word &fieldName) const
template<class ObjectType >
const ObjectType * findObject (const word &fieldName) const
template<class ObjectType >
ObjectType * findObject (const word &fieldName)
template<class ObjectType >
ObjectType * getObjectPtr (const word &fieldName) const
template<class ObjectType >
const ObjectType & lookupObject (const word &fieldName) const
template<class ObjectType >
ObjectType & lookupObjectRef (const word &fieldName) const
template<class ObjectType >
bool store (word &fieldName, const tmp< ObjectType > &tfield, bool cacheable=false)
template<class ObjectType >
bool storeInDb (const word &fieldName, const tmp< ObjectType > &tfield, const objectRegistry &obr)
bool writeObject (const word &fieldName)
bool clearObject (const word &fieldName)
void clearObjects (const wordList &objNames)
regionFunctionObject (const regionFunctionObject &)=delete
void operator= (const regionFunctionObject &)=delete
Protected Member Functions inherited from stateFunctionObject
const functionObjects::properties & stateDict () const
functionObjects::properties & stateDict ()
stateFunctionObject (const stateFunctionObject &)=delete
void operator= (const stateFunctionObject &)=delete
Protected Member Functions inherited from timeFunctionObject
void clearOutputObjects (const wordList &objNames)
timeFunctionObject (const timeFunctionObject &)=delete
void operator= (const timeFunctionObject &)=delete
Protected Member Functions inherited from functionObject
word scopedName (const word &name) const
Protected Attributes
bool initialised_
word prefix_
wordHashSet fieldSet_
Protected Attributes inherited from fvMeshFunctionObject
const fvMesh & mesh_
Protected Attributes inherited from regionFunctionObject
word subRegistryName_
const objectRegistry & obr_
const objectRegistry * obrPtr_
Protected Attributes inherited from timeFunctionObject
const Time & time_
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &runTime, const dictionary &dict)
Public Attributes inherited from functionObject
bool log
Detailed Description
Computes various turbulence-related quantities that are not typically output during calculations, and stores/writes them on the mesh database for further manipulation.
Fields are stored as copies of the original with a user-defined prefix e.g. a prefix of turbulenceModel yields the following for field R:
  turbulenceModel:R
Operands:
Operand Type Location
input - -
output file - -
output field vol<Type>Field $FOAM_CASE/<time>/<outField>
where <Type>=Scalar/SymmTensor.
References:
        Estimation expressions for L (tag:P), Eq. 10.37:
            Pope, S. B. (2000).
            Turbulent flows.
            Cambridge, UK: Cambridge Univ. Press
            DOI:10.1017/CBO9780511840531
Usage
Minimal example by using system/controlDict.functions:
turbulenceFields1
{
    // Mandatory entries (unmodifiable)
    type        turbulenceFields;
    libs        (fieldFunctionObjects);
    // Mandatory entries (runtime modifiable)
        // Either of the below
        // Option-1
        fields      (R devRhoReff);
        // Option-2
        field       R;
    // Optional entries (runtime modifiable)
    prefix          <word>;
    // Inherited entries
    ...
}
where the entries mean:
Property Description Type Reqd Deflt
type Type name: turbulenceFields word yes -
libs Library name: fieldFunctionObjects word yes -
fields Names of fields to store (see below) wordList yes -
field Name of a field to store (see below) word yes -
prefix Name of output-field prefix word no turbulenceProperties
where fields can include:
      k           | turbulent kinetic energy
      epsilon     | turbulent kinetic energy dissipation rate
      omega       | specific dissipation rate
      nuTilda     | modified turbulent viscosity
      nut         | turbulent viscosity (incompressible)
      nuEff       | effective turbulent viscosity (incompressible)
      mut         | turbulent viscosity (compressible)
      muEff       | effective turbulent viscosity (compressible)
      alphat      | turbulence thermal diffusivity (compressible)
      alphaEff    | effective turbulence thermal diffusivity (compressible)
      R           | Reynolds stress tensor
      devReff     | deviatoric part of the effective Reynolds stress
      devRhoReff  | divergence of the Reynolds stress
      L           | integral-length scale / mixing-length scale
      I           | turbulence intensity
The inherited entries are elaborated in:
functionObject.H
Minimal example by using the postProcess utility:
        <solver> -postProcess -func turbulenceFields
Note
Multiphase applications are not supported.
The governing expression of nuTilda is an approximation based on a dimensional analysis.
See also
Foam::functionObject
Foam::functionObjects::fvMeshFunctionObject
ExtendedCodeGuide::functionObjects::field::turbulenceFields
Source files
turbulenceFields.H
turbulenceFields.C
turbulenceFieldsTemplates.C
Definition at line 210 of file turbulenceFields.H.
Member Enumeration Documentation
compressibleField
enum compressibleField
Enumerator
cfK
"Turbulent kinetic energy"
cfEpsilon
"Turbulent kinetic energy dissipation rate"
cfOmega
"Specific dissipation rate"
cfNuTilda
"Modified turbulent viscosity"
cfMut
"Turbulent dynamic viscosity"
cfMuEff
"Effective turbulent dynamic viscosity"
cfAlphat
"Turbulence thermal diffusivity"
cfAlphaEff
"Effective turbulence thermal diffusivity"
cfR
"Reynolds stress tensor"
cfDevRhoReff
"Divergence of the Reynolds stress"
cfL
"Integral-length/Mixing-length scale"
cfI
"Turbulence intensity"
cfLESRegion
"DES model LES region indicator field"
cffd
"DES model shielding function"
Definition at line 219 of file turbulenceFields.H.
incompressibleField
enum incompressibleField
Enumerator
ifK
"Turbulent kinetic energy"
ifEpsilon
"Turbulent kinetic energy dissipation rate"
ifOmega
"Specific dissipation rate"
ifNuTilda
"Modified turbulent viscosity"
ifNut
"Turbulent viscosity"
ifNuEff
"Effective turbulent viscosity"
ifR
"Reynolds stress tensor"
ifDevReff
"Deviatoric part of the effective Reynolds stress"
ifL
"Integral-length/Mixing-length scale"
ifI
"Turbulence intensity"
ifLESRegion
"DES model LES region indicator field"
iffd
"DES model shielding function"
Definition at line 241 of file turbulenceFields.H.
Constructor & Destructor Documentation
turbulenceFields() [1/2]
turbulenceFields (const word & name, const Time & runTime, const dictionary & dict)
Definition at line 133 of file turbulenceFields.C.
References dict, and turbulenceFields::read().
turbulenceFields() [2/2]
turbulenceFields (const turbulenceFields &) delete
~turbulenceFields()
virtual ~turbulenceFields () virtual default
Member Function Documentation
initialise()
void initialise () protected
Definition at line 91 of file turbulenceFields.C.
References Foam::endl(), f(), turbulenceFields::fieldSet_, turbulenceFields::initialised_, Foam::nl, regionFunctionObject::obr_, turbulenceFields::prefix_, IOobject::scopedName(), HashSet< Key, Hash >::unset(), and WarningInFunction.
compressible()
bool compressible () protected
Definition at line 112 of file turbulenceFields.C.
References Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
processField()
template<class Type > void processField (const word & fieldName, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvalue) protected
Definition at line 27 of file turbulenceFieldsTemplates.C.
References IOobjectOption::LAZY_READ, IOobjectOption::NO_WRITE, regionFunctionObject::obr_, turbulenceFields::prefix_, IOobjectOption::REGISTER, and IOobject::scopedName().
nuTilda() [1/2]
template<class Model > tmp< volScalarField > nuTilda (const Model & model) const protected
L() [1/2]
template<class Model > tmp< volScalarField > L (const Model & model) const protected
I() [1/2]
template<class Model > tmp< volScalarField > I (const Model & model) const protected
TypeName()
TypeName ("turbulenceFields")
operator=()
void operator= (const turbulenceFields &) delete
read()
bool read (const dictionary & dict) virtual
Reimplemented from regionFunctionObject.
Definition at line 151 of file turbulenceFields.C.
References dict, Foam::endl(), f(), Foam::Info, initialised_(), Foam::name(), Foam::nl, functionObject::read(), IOobject::scopedName(), and Foam::type().
Referenced by turbulenceFields::turbulenceFields().
execute()
bool execute () virtual
Implements functionObject.
Definition at line 190 of file turbulenceFields.C.
References compressible, Foam::endl(), f(), Foam::FatalError, FatalErrorInFunction, Foam::I, initialised_(), L, and WarningInFunction.
write()
bool write () virtual
Implements functionObject.
Definition at line 408 of file turbulenceFields.C.
References Foam::endl(), f(), Foam::Info, and IOobject::scopedName().
nuTilda() [2/2]
template<class Model > Foam::tmp< Foam::volScalarField > nuTilda (const Model & model) const
Definition at line 66 of file turbulenceFieldsTemplates.C.
References Foam::dimless, Foam::dimTime, and tmp< T >::New().
L() [2/2]
template<class Model > Foam::tmp< Foam::volScalarField > L (const Model & model) const
Definition at line 83 of file turbulenceFieldsTemplates.C.
References Foam::dimTime, Foam::dimVelocity, tmp< T >::New(), and Foam::sqr().
I() [2/2]
template<class Model > Foam::tmp< Foam::volScalarField > I (const Model & model) const
Definition at line 102 of file turbulenceFieldsTemplates.C.
References Foam::dimVelocity, Foam::max(), tmp< T >::New(), and Foam::sqrt().
Member Data Documentation
compressibleFieldNames_
const Foam::Enum< Foam::functionObjects::turbulenceFields::compressibleField > compressibleFieldNames_ static
Definition at line 238 of file turbulenceFields.H.
incompressibleFieldNames_
const Foam::Enum< Foam::functionObjects::turbulenceFields::incompressibleField > incompressibleFieldNames_ static
Definition at line 258 of file turbulenceFields.H.
modelName_
const Foam::word modelName_ static
Definition at line 261 of file turbulenceFields.H.
initialised_
bool initialised_ protected
Definition at line 269 of file turbulenceFields.H.
Referenced by turbulenceFields::initialise().
prefix_
word prefix_ protected
Definition at line 272 of file turbulenceFields.H.
Referenced by turbulenceFields::initialise(), and turbulenceFields::processField().
fieldSet_
wordHashSet fieldSet_ protected
Definition at line 275 of file turbulenceFields.H.
Referenced by turbulenceFields::initialise().
The documentation for this class was generated from the following files:
src/functionObjects/field/turbulenceFields/turbulenceFields.H
src/functionObjects/field/turbulenceFields/turbulenceFields.C
src/functionObjects/field/turbulenceFields/turbulenceFieldsTemplates.C