OpenFOAM: humidityTemperatureCoupledMixedFvPatchScalarField Class Reference
humidityTemperatureCoupledMixedFvPatchScalarField Class Reference
#include <humidityTemperatureCoupledMixedFvPatchScalarField.H>
Public Types
enum massTransferMode { mtConstantMass , mtCondensation , mtEvaporation , mtCondensationAndEvaporation }
Public Types inherited from temperatureCoupledBase
enum KMethodType {
mtFluidThermo , mtSolidThermo , mtDirectionalSolidThermo , mtLookup ,
mtFunction
}
Public Member Functions
TypeName ("humidityTemperatureCoupledMixed")
humidityTemperatureCoupledMixedFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
humidityTemperatureCoupledMixedFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
humidityTemperatureCoupledMixedFvPatchScalarField (const humidityTemperatureCoupledMixedFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
virtual tmp< fvPatchScalarField > clone () const
humidityTemperatureCoupledMixedFvPatchScalarField (const humidityTemperatureCoupledMixedFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual void autoMap (const fvPatchFieldMapper &)
virtual void rmap (const fvPatchScalarField &, const labelList &)
const scalarField myKDelta () const
const scalarField mpCpTp () const
const scalarField dmHfg () const
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Public Member Functions inherited from temperatureCoupledBase
temperatureCoupledBase (const fvPatch &patch, const KMethodType method=KMethodType::mtFluidThermo)
temperatureCoupledBase (const fvPatch &patch, const KMethodType method, const word &kappaName, const word &alphaName, const word &alphaAniName)
temperatureCoupledBase (const fvPatch &patch, const dictionary &dict)
temperatureCoupledBase (const fvPatch &patch, const temperatureCoupledBase &base)
temperatureCoupledBase (const temperatureCoupledBase &base)
virtual ~temperatureCoupledBase ()=default
word KMethod () const
const word & kappaName () const noexcept
const word & alphaName () const noexcept
virtual tmp< scalarField > kappa (const scalarField &Tp) const
virtual tmp< scalarField > alpha (const scalarField &Tp) const
void write (Ostream &os) const
Additional Inherited Members
Protected Attributes inherited from temperatureCoupledBase
const fvPatch & patch_
const KMethodType method_
const word kappaName_
const word alphaName_
const word alphaAniName_
autoPtr< PatchFunction1< scalar > > kappaFunction1_
autoPtr< PatchFunction1< scalar > > alphaFunction1_
Static Protected Attributes inherited from temperatureCoupledBase
static const Enum< KMethodType > KMethodTypeNames_
Detailed Description
Definition at line 199 of file humidityTemperatureCoupledMixedFvPatchScalarField.H.
Member Enumeration Documentation
massTransferMode
enum massTransferMode
Enumerator
mtConstantMass
mtCondensation
mtEvaporation
mtCondensationAndEvaporation
Definition at line 209 of file humidityTemperatureCoupledMixedFvPatchScalarField.H.
Constructor & Destructor Documentation
humidityTemperatureCoupledMixedFvPatchScalarField() [1/4]
humidityTemperatureCoupledMixedFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 121 of file humidityTemperatureCoupledMixedFvPatchScalarField.C.
humidityTemperatureCoupledMixedFvPatchScalarField() [2/4]
humidityTemperatureCoupledMixedFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 199 of file humidityTemperatureCoupledMixedFvPatchScalarField.C.
References dict, Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, forAll, humidityTemperatureCoupledMixedFvPatchScalarField::mtCondensation, humidityTemperatureCoupledMixedFvPatchScalarField::mtCondensationAndEvaporation, humidityTemperatureCoupledMixedFvPatchScalarField::mtConstantMass, humidityTemperatureCoupledMixedFvPatchScalarField::mtEvaporation, IOobjectOption::MUST_READ, liquidProperties::New(), Foam::nl, p, and dictionary::subDict().
humidityTemperatureCoupledMixedFvPatchScalarField() [3/4]
humidityTemperatureCoupledMixedFvPatchScalarField (const humidityTemperatureCoupledMixedFvPatchScalarField & psf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 161 of file humidityTemperatureCoupledMixedFvPatchScalarField.C.
humidityTemperatureCoupledMixedFvPatchScalarField() [4/4]
humidityTemperatureCoupledMixedFvPatchScalarField (const humidityTemperatureCoupledMixedFvPatchScalarField & psf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 326 of file humidityTemperatureCoupledMixedFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("humidityTemperatureCoupledMixed")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 349 of file humidityTemperatureCoupledMixedFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 368 of file humidityTemperatureCoupledMixedFvPatchScalarField.H.
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Implements temperatureCoupledBase.
Definition at line 364 of file humidityTemperatureCoupledMixedFvPatchScalarField.C.
References temperatureCoupledBase::autoMap().
rmap()
void rmap (const fvPatchScalarField & ptf, const labelList & addr) virtual
Implements temperatureCoupledBase.
Definition at line 385 of file humidityTemperatureCoupledMixedFvPatchScalarField.C.
References temperatureCoupledBase::rmap().
myKDelta()
const scalarField myKDelta () const inline
Definition at line 403 of file humidityTemperatureCoupledMixedFvPatchScalarField.H.
mpCpTp()
const scalarField mpCpTp () const inline
Definition at line 409 of file humidityTemperatureCoupledMixedFvPatchScalarField.H.
dmHfg()
const scalarField dmHfg () const inline
Definition at line 415 of file humidityTemperatureCoupledMixedFvPatchScalarField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 413 of file humidityTemperatureCoupledMixedFvPatchScalarField.C.
References alpha, b, cp, Foam::endl(), forAll, Foam::gAverage(), Foam::gMax(), Foam::gMin(), Foam::gSum(), Foam::Info, Foam::log(), Foam::mag(), Foam::max(), mesh, Foam::min(), fvMesh::name(), Foam::nl, pp(), Foam::Re(), Foam::refCast(), rhof(), UList< T >::size(), T, fvMesh::time(), Uf, and Foam::Zero.
write()
void write (Ostream & os) const virtual
Definition at line 755 of file humidityTemperatureCoupledMixedFvPatchScalarField.C.
References os(), token::TAB, mixedFvPatchField< Type >::write(), temperatureCoupledBase::write(), Ostream::writeEntry(), and Ostream::writeEntryIfDifferent().
The documentation for this class was generated from the following files:
src/thermoTools/derivedFvPatchFields/humidityTemperatureCoupledMixed/humidityTemperatureCoupledMixedFvPatchScalarField.H
src/thermoTools/derivedFvPatchFields/humidityTemperatureCoupledMixed/humidityTemperatureCoupledMixedFvPatchScalarField.C