OpenFOAM: jouleHeatingSource Class Reference
jouleHeatingSource Class Reference
Evolves an electrical potential equation.
#include <jouleHeatingSource.H>
Public Member Functions
TypeName ("jouleHeatingSource")
jouleHeatingSource (const word &sourceName, const word &modelType, const dictionary &dict, const fvMesh &mesh)
jouleHeatingSource (const jouleHeatingSource &)=delete
void operator= (const jouleHeatingSource &)=delete
virtual ~jouleHeatingSource ()=default
virtual void addSup (const areaScalarField &h, const areaScalarField &rho, faMatrix< scalar > &eqn, const label fieldi)
virtual bool read (const dictionary &dict)
template<class Type >
const Foam::GeometricField< Type, Foam::faPatchField, Foam::areaMesh > & updateSigma (const autoPtr< Function1< Type > > &sigmaVsTPtr) const
template<class Type >
const Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > & updateSigma (const autoPtr< Function1< Type > > &sigmaVsTPtr) const
Public Member Functions inherited from faceSetOption
TypeName ("faceSetOption")
faceSetOption (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
virtual ~faceSetOption ()=default
scalar timeStart () const noexcept
scalar duration () const noexcept
bool inTimeLimits (const scalar timeValue) const
bool useSubMesh () const noexcept
selectionModeType selectionMode () const noexcept
const wordRes & selectionNames () const noexcept
const wordRe & zoneName () const
scalar A () const noexcept
const labelList & faces () const noexcept
scalar timeStart (scalar val) noexcept
scalar duration (scalar val) noexcept
virtual bool isActive ()
Public Member Functions inherited from option
TypeName ("option")
declareRunTimeSelectionTable (autoPtr, option, dictionary,(const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh),(name, modelType, dict, mesh))
option (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
autoPtr< option > clone () const
virtual ~option ()=default
const word & name () const noexcept
const fvMesh & mesh () const noexcept
const dictionary & coeffs () const noexcept
bool active () const noexcept
void setApplied (const label fieldi)
const word & regionName () const noexcept
const faMesh & regionMesh () const
const volSurfaceMapping & vsm () const
bool active (const bool on) noexcept
virtual label applyToField (const word &fieldName) const
virtual void checkApplied () const
virtual void addSup (const areaScalarField &h, faMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (const areaScalarField &h, faMatrix< vector > &eqn, const label fieldi)
virtual void addSup (const areaScalarField &h, faMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (const areaScalarField &h, faMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (const areaScalarField &h, faMatrix< tensor > &eqn, const label fieldi)
virtual void addSup (const areaScalarField &h, const areaScalarField &rho, faMatrix< vector > &eqn, const label fieldi)
virtual void addSup (const areaScalarField &h, const areaScalarField &rho, faMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (const areaScalarField &h, const areaScalarField &rho, faMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (const areaScalarField &h, const areaScalarField &rho, faMatrix< tensor > &eqn, const label fieldi)
virtual void constrain (faMatrix< scalar > &eqn, const label fieldi)
virtual void constrain (faMatrix< vector > &eqn, const label fieldi)
virtual void constrain (faMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void constrain (faMatrix< symmTensor > &eqn, const label fieldi)
virtual void constrain (faMatrix< tensor > &eqn, const label fieldi)
virtual void correct (areaScalarField &field)
virtual void correct (areaVectorField &field)
virtual void correct (areaSphericalTensorField &field)
virtual void correct (areaSymmTensorField &field)
virtual void correct (areaTensorField &field)
virtual void writeHeader (Ostream &) const
virtual void writeFooter (Ostream &) const
virtual void writeData (Ostream &) const
Additional Inherited Members
Public Types inherited from faceSetOption
enum selectionModeType { smAll , smFaceSet , smFaceZone , smPatch }
Static Public Member Functions inherited from option
static autoPtr< option > New (const word &name, const dictionary &dict, const fvMesh &mesh)
Public Attributes inherited from option
bool log
Static Public Attributes inherited from faceSetOption
static const Enum< selectionModeType > selectionModeTypeNames_
Protected Member Functions inherited from faceSetOption
void setSelection (const dictionary &dict)
void setFaceSelection ()
void setArea ()
template<class Type >
void subsetFilter (List< Type > &field) const
Protected Member Functions inherited from option
void resetApplied ()
Protected Attributes inherited from faceSetOption
scalar timeStart_
scalar duration_
selectionModeType selectionMode_
wordRes selectionNames_
labelList faces_
scalar A_
Protected Attributes inherited from option
const word name_
const word modelType_
const fvMesh & mesh_
dictionary dict_
dictionary coeffs_
wordList fieldNames_
List< bool > applied_
word regionName_
Detailed Description
Evolves an electrical potential equation.
where is electrical potential and is the electrical current.
To provide a Joule heating contribution according to:
Differential form of Joule heating - power per unit volume:
where is the current density and the electric field. If no magnetic field is present:
The electric field given by
Therefore:
Usage
Minimal example by using constant/faOptions:
jouleHeatingSource1
{
    // Mandatory entries (unmodifiable)
    type                 jouleHeatingSource;
    // Mandatory entries (runtime modifiable)
    anisotropicElectricalConductivity true;
    // Optional entries (runtime modifiable)
    T                   <Tname>;
    nIter               -1;
    // Conditional mandatory entries (runtime modifiable)
        // when the entry "sigma" is present
        sigma           <Function1>;
        // when when the entry "sigma" is not present
        // read "sigma" from file
    // Mandatory/Optional (inherited) entries
    ...
}
where the entries mean:
Property Description Type Reqd Dflt
type Type name: jouleHeatingSource word yes -
anisotropicElectricalConductivity
Flag to indicate that
if the electrical conductivity is anisotropic
bool yes -
T Name of operand temperature field word no T
sigma
Electrical conductivity as a function of temperature
table no -
nIter
Number of iterations for electrical potential equation
solution
label no -1
The inherited entries are elaborated in:
faOption.H
faceSetOption.H
Note
anisotropicElectricalConductivity=true enables anisotropic (tensorial) electrical conductivity.
anisotropicElectricalConductivity=false enables isotropic (scalar) electrical conductivity.
The electrical conductivity can be specified using either:
If the sigma entry is present the electrical conductivity is specified as a function of temperature using a Function1 type.
If not present the sigma field will be read from file.
If the anisotropicElectricalConductivity flag is set to true, sigma should be specified as a tensor quantity.
See also
Foam::Function1
Source files
jouleHeatingSource.H
jouleHeatingSource.C
jouleHeatingSourceTemplates.C
Definition at line 196 of file jouleHeatingSource.H.
Constructor & Destructor Documentation
jouleHeatingSource() [1/2]
jouleHeatingSource (const word & sourceName, const word & modelType, const dictionary & dict, const fvMesh & mesh)
Definition at line 40 of file jouleHeatingSource.C.
References option::coeffs_, dict, Foam::endl(), option::fieldNames_, Foam::Info, jouleHeatingSource::read(), option::resetApplied(), and List< T >::resize().
jouleHeatingSource() [2/2]
jouleHeatingSource (const jouleHeatingSource &) delete
~jouleHeatingSource()
virtual ~jouleHeatingSource () virtual default
Member Function Documentation
TypeName()
TypeName ("jouleHeatingSource")
operator=()
void operator= (const jouleHeatingSource &) delete
addSup()
void addSup (const areaScalarField & h, const areaScalarField & rho, faMatrix< scalar > & eqn, const label fieldi) virtual
Reimplemented from option.
Definition at line 91 of file jouleHeatingSource.C.
References DebugInfo, Foam::endl(), Foam::fac::grad(), h, Foam::fam::laplacian(), mesh, Foam::name(), faceSetOption::subsetFilter(), and timeIndex.
read()
bool read (const dictionary & dict) virtual
Reimplemented from faceSetOption.
Definition at line 176 of file jouleHeatingSource.C.
References dict, UPtrList< T >::get(), and option::read().
Referenced by jouleHeatingSource::jouleHeatingSource().
updateSigma() [1/2]
template<class Type > const Foam::GeometricField< Type, Foam::faPatchField, Foam::areaMesh > & updateSigma (const autoPtr< Function1< Type > > & sigmaVsTPtr) const
Definition at line 83 of file jouleHeatingSourceTemplates.C.
References forAll, mesh, and T.
updateSigma() [2/2]
template<class Type > const Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > & updateSigma (const autoPtr< Function1< Type > > & sigmaVsTPtr) const
Definition at line 81 of file jouleHeatingSourceTemplates.C.
References forAll, Foam::isA(), and T.
The documentation for this class was generated from the following files:
src/faOptions/sources/derived/jouleHeatingSource/jouleHeatingSource.H
src/faOptions/sources/derived/jouleHeatingSource/jouleHeatingSource.C
src/faOptions/sources/derived/jouleHeatingSource/jouleHeatingSourceTemplates.C
src/fvOptions/sources/derived/jouleHeatingSource/jouleHeatingSourceTemplates.C