OpenFOAM: LemmertChawla Class Reference
LemmertChawla Class Reference
A model for nucleation site density based on Lemmert-Chawla (1977) function and Egorov-Menter (2004) correlation for boiling flows.
#include <LemmertChawla.H>
Public Member Functions
TypeName ("LemmertChawla")
LemmertChawla (const dictionary &dict)
virtual ~LemmertChawla ()=default
virtual tmp< scalarField > N (const phaseModel &liquid, const phaseModel &vapor, const label patchi, const scalarField &Tl, const scalarField &Tsatw, const scalarField &L) const
virtual void write (Ostream &os) const
Public Member Functions inherited from nucleationSiteModel
TypeName ("nucleationSiteModel")
declareRunTimeSelectionTable (autoPtr, nucleationSiteModel, dictionary,(const dictionary &dict),(dict))
nucleationSiteModel ()=default
virtual ~nucleationSiteModel ()=default
Additional Inherited Members
Static Public Member Functions inherited from nucleationSiteModel
static autoPtr< nucleationSiteModel > New (const dictionary &dict)
Detailed Description
A model for nucleation site density based on Lemmert-Chawla (1977) function and Egorov-Menter (2004) correlation for boiling flows.
Reference:
    Lemmert, M., & Chawla, J. M. (1977).
    Influence of flow velocity on surface boiling heat transfer coefficient.
    Heat Transfer in Boiling, 237, 247.
    Egorov, Y., & Menter, F. (2004).
    Experimental implementation of the RPI wall boiling model in CFX-5.6.
    Staudenfeldweg, 12, 83624.
    Technical Report ANSYS/TR-04-10, ANSYS Gmbh.
Usage
Example of the model specification:
nucleationSiteModel
{
    // Mandatory entries
    type            LemmertChawla;
    // Optional entries
    Cn              <scalar>;
}
where the entries mean:
Property Description Type Reqd Deflt
type Type name: LemmertChawla word yes -
Cn Coefficient for nucleation site density scalar no 1.0
Source files
LemmertChawla.H
LemmertChawla.C
Definition at line 103 of file LemmertChawla.H.
Constructor & Destructor Documentation
LemmertChawla()
LemmertChawla (const dictionary & dict)
Definition at line 47 of file LemmertChawla.C.
~LemmertChawla()
virtual ~LemmertChawla () virtual default
Member Function Documentation
TypeName()
TypeName ("LemmertChawla")
N()
Foam::tmp< Foam::scalarField > N (const phaseModel & liquid, const phaseModel & vapor, const label patchi, const scalarField & Tl, const scalarField & Tsatw, const scalarField & L) const virtual
Implements nucleationSiteModel.
Definition at line 60 of file LemmertChawla.C.
References Foam::max(), and Foam::pow().
write()
void write (Ostream & os) const virtual
Reimplemented from nucleationSiteModel.
Definition at line 77 of file LemmertChawla.C.
References os(), and nucleationSiteModel::write().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/wallBoilingSubModels/nucleationSiteModels/LemmertChawla/LemmertChawla.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/wallBoilingSubModels/nucleationSiteModels/LemmertChawla/LemmertChawla.C