OpenFOAM: supersonicFreestreamFvPatchVectorField Class Reference
supersonicFreestreamFvPatchVectorField Class Reference
Boundary conditions » Inlet | Boundary conditions » Outlet
This boundary condition provides a supersonic free-stream condition.
#include <supersonicFreestreamFvPatchVectorField.H>
Public Member Functions
TypeName ("supersonicFreestream")
supersonicFreestreamFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
supersonicFreestreamFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
supersonicFreestreamFvPatchVectorField (const supersonicFreestreamFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
supersonicFreestreamFvPatchVectorField (const supersonicFreestreamFvPatchVectorField &)
virtual tmp< fvPatchVectorField > clone () const
supersonicFreestreamFvPatchVectorField (const supersonicFreestreamFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
const vector & UInf () const
vector & UInf ()
scalar pInf () const
scalar & pInf ()
scalar TInf () const
scalar & TInf ()
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
This boundary condition provides a supersonic free-stream condition.
supersonic outflow is vented according to ???
supersonic inflow is assumed to occur according to the Prandtl-Meyer expansion process.
subsonic outflow is applied via a zero-gradient condition from inside the domain.
Usage
Property Description Required Default value
T Temperature field name no T
p Pressure field name no p
psi Compressibility field name no thermo:psi
UInf free-stream velocity yes
pInf free-stream pressure yes
TInf free-stream temperature yes
gamma heat capacity ratio (cp/Cv) yes
Example of the boundary condition specification:
    <patchName>
    {
        type            supersonicFreestream;
        UInf            500;
        pInf            1e4;
        TInf            265;
        gamma           1.4;
    }
Note
This boundary condition is ill-posed if the free-stream flow is normal to the boundary.
Source files
supersonicFreestreamFvPatchVectorField.H
supersonicFreestreamFvPatchVectorField.C
Definition at line 124 of file supersonicFreestreamFvPatchVectorField.H.
Constructor & Destructor Documentation
supersonicFreestreamFvPatchVectorField() [1/5]
supersonicFreestreamFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Definition at line 29 of file supersonicFreestreamFvPatchVectorField.C.
References Foam::Zero.
supersonicFreestreamFvPatchVectorField() [2/5]
supersonicFreestreamFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Definition at line 51 of file supersonicFreestreamFvPatchVectorField.C.
References dict, Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, fvPatchFieldBase::readDict(), and Foam::Zero.
supersonicFreestreamFvPatchVectorField() [3/5]
supersonicFreestreamFvPatchVectorField (const supersonicFreestreamFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 91 of file supersonicFreestreamFvPatchVectorField.C.
supersonicFreestreamFvPatchVectorField() [4/5]
supersonicFreestreamFvPatchVectorField (const supersonicFreestreamFvPatchVectorField & sfspvf)
Definition at line 111 of file supersonicFreestreamFvPatchVectorField.C.
supersonicFreestreamFvPatchVectorField() [5/5]
supersonicFreestreamFvPatchVectorField (const supersonicFreestreamFvPatchVectorField & sfspvf, const DimensionedField< vector, volMesh > & iF)
Definition at line 128 of file supersonicFreestreamFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("supersonicFreestream")
clone() [1/2]
virtual tmp< fvPatchVectorField > clone () const inline virtual
Definition at line 192 of file supersonicFreestreamFvPatchVectorField.H.
clone() [2/2]
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Definition at line 208 of file supersonicFreestreamFvPatchVectorField.H.
UInf() [1/2]
const vector & UInf () const inline
Definition at line 225 of file supersonicFreestreamFvPatchVectorField.H.
UInf() [2/2]
vector & UInf () inline
Definition at line 231 of file supersonicFreestreamFvPatchVectorField.H.
pInf() [1/2]
scalar pInf () const inline
Definition at line 237 of file supersonicFreestreamFvPatchVectorField.H.
pInf() [2/2]
scalar & pInf () inline
Definition at line 243 of file supersonicFreestreamFvPatchVectorField.H.
TInf() [1/2]
scalar TInf () const inline
Definition at line 249 of file supersonicFreestreamFvPatchVectorField.H.
TInf() [2/2]
scalar & TInf () inline
Definition at line 256 of file supersonicFreestreamFvPatchVectorField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 148 of file supersonicFreestreamFvPatchVectorField.C.
References Foam::atan(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::log(), Foam::mag(), Foam::pow(), pp(), R, Foam::sqr(), Foam::sqrt(), and U.
write()
void write (Ostream & os) const virtual
Definition at line 281 of file supersonicFreestreamFvPatchVectorField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntry(), Ostream::writeEntryIfDifferent(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/supersonicFreestream/supersonicFreestreamFvPatchVectorField.H
src/finiteVolume/fields/fvPatchFields/derived/supersonicFreestream/supersonicFreestreamFvPatchVectorField.C