OpenFOAM: greyDiffusiveRadiationMixedFvPatchScalarField Class Reference
greyDiffusiveRadiationMixedFvPatchScalarField Class Reference
Boundary conditions » Thermophysical
This boundary condition provides a grey-diffuse condition for radiation intensity, I, for use with the finite-volume discrete-ordinates model (fvDOM), in which the radiation temperature is retrieved from the temperature field boundary condition.
#include <greyDiffusiveRadiationMixedFvPatchScalarField.H>
Public Member Functions
TypeName ("greyDiffusiveRadiation")
greyDiffusiveRadiationMixedFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
greyDiffusiveRadiationMixedFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
greyDiffusiveRadiationMixedFvPatchScalarField (const greyDiffusiveRadiationMixedFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
greyDiffusiveRadiationMixedFvPatchScalarField (const greyDiffusiveRadiationMixedFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
greyDiffusiveRadiationMixedFvPatchScalarField (const greyDiffusiveRadiationMixedFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
const word & TName () const noexcept
word & TName () noexcept
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
This boundary condition provides a grey-diffuse condition for radiation intensity, I, for use with the finite-volume discrete-ordinates model (fvDOM), in which the radiation temperature is retrieved from the temperature field boundary condition.
An external radiative heat flux can be added using qRadExt. If qRadExtDir is specified, this ray closest to this direction is used. Otherwise, the face normal is used as direction to set qRadExt.
Usage
Example of the boundary condition specification:
<patchName>
{
    // Mandatory entries
    type            greyDiffusiveRadiation;
    // Optional entries
    T               T;
    qRadExt         <scalar>;
    qRadExtDir      <vector>;
    // Inherited entries
    ...
}
where the entries mean:
Property Description Type Reqd Deflt
type Type name: greyDiffusiveRadiation word yes -
T Name of temperature field word no T
qRadExt Radiative external flux scalar no Zero
qRadExtDir Radiative external flux direction vector no Zero
The inherited entries are elaborated in:
mixedFvPatchFields.H
See also
Foam::radiation::radiationModel
Foam::radiation::fvDOM
Foam::radiationCoupledBase
Foam::mixedFvPatchField
Source files
greyDiffusiveRadiationMixedFvPatchScalarField.H
greyDiffusiveRadiationMixedFvPatchScalarField.C
Definition at line 124 of file greyDiffusiveRadiationMixedFvPatchScalarField.H.
Constructor & Destructor Documentation
greyDiffusiveRadiationMixedFvPatchScalarField() [1/5]
greyDiffusiveRadiationMixedFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 37 of file greyDiffusiveRadiationMixedFvPatchScalarField.C.
References Foam::Zero.
greyDiffusiveRadiationMixedFvPatchScalarField() [2/5]
greyDiffusiveRadiationMixedFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 71 of file greyDiffusiveRadiationMixedFvPatchScalarField.C.
References dict, IOobjectOption::MUST_READ, fvPatchField< scalar >::operator=(), and Foam::Zero.
greyDiffusiveRadiationMixedFvPatchScalarField() [3/5]
greyDiffusiveRadiationMixedFvPatchScalarField (const greyDiffusiveRadiationMixedFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 55 of file greyDiffusiveRadiationMixedFvPatchScalarField.C.
greyDiffusiveRadiationMixedFvPatchScalarField() [4/5]
greyDiffusiveRadiationMixedFvPatchScalarField (const greyDiffusiveRadiationMixedFvPatchScalarField & ptf)
Definition at line 100 of file greyDiffusiveRadiationMixedFvPatchScalarField.C.
greyDiffusiveRadiationMixedFvPatchScalarField() [5/5]
greyDiffusiveRadiationMixedFvPatchScalarField (const greyDiffusiveRadiationMixedFvPatchScalarField & ptf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 113 of file greyDiffusiveRadiationMixedFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("greyDiffusiveRadiation")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 180 of file greyDiffusiveRadiationMixedFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 196 of file greyDiffusiveRadiationMixedFvPatchScalarField.H.
TName() [1/2]
const word & TName () const inline noexcept
Definition at line 213 of file greyDiffusiveRadiationMixedFvPatchScalarField.H.
TName() [2/2]
word & TName () inline noexcept
Definition at line 220 of file greyDiffusiveRadiationMixedFvPatchScalarField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 129 of file greyDiffusiveRadiationMixedFvPatchScalarField.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), radiativeIntensityRay::dAve(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::mag(), mesh, UPstream::msgType(), n, MeshObject< fvMesh, Foam::GeometricMeshObject, boundaryRadiationProperties >::New(), Foam::nl, Foam::constant::mathematical::pi(), Foam::pow4(), radiativeIntensityRay::qem(), radiativeIntensityRay::qin(), radiativeIntensityRay::qr(), Foam::constant::physicoChemical::sigma, and Foam::Zero.
write()
void write (Ostream & os) const virtual
Definition at line 359 of file greyDiffusiveRadiationMixedFvPatchScalarField.C.
References os(), mixedFvPatchField< Type >::write(), and Foam::Zero.
The documentation for this class was generated from the following files:
src/thermophysicalModels/radiation/derivedFvPatchFields/greyDiffusiveRadiation/greyDiffusiveRadiationMixedFvPatchScalarField.H
src/thermophysicalModels/radiation/derivedFvPatchFields/greyDiffusiveRadiation/greyDiffusiveRadiationMixedFvPatchScalarField.C