OpenFOAM: fvPatchMapper Class Reference
fvPatchMapper Class Reference
Mapping class for a fvPatchField.
#include <fvPatchMapper.H>
Public Member Functions
fvPatchMapper (const fvPatch &patch, const faceMapper &faceMap)
virtual ~fvPatchMapper ()
virtual label size () const
virtual label sizeBeforeMapping () const
virtual bool direct () const
virtual bool hasUnmapped () const
virtual const labelUList & directAddressing () const
virtual const labelListList & addressing () const
virtual const scalarListList & weights () const
Public Member Functions inherited from fvPatchFieldMapper
fvPatchFieldMapper ()=default
Public Member Functions inherited from FieldMapper
FieldMapper ()=default
virtual ~FieldMapper ()=default
virtual bool distributed () const
virtual const mapDistributeBase & distributeMap () const
template<class Type >
tmp< Field< Type > > operator() (const Field< Type > &fld) const
Detailed Description
Mapping class for a fvPatchField.
Source files
fvPatchMapper.H
fvPatchMapper.C
Definition at line 53 of file fvPatchMapper.H.
Constructor & Destructor Documentation
fvPatchMapper()
fvPatchMapper (const fvPatch & patch, const faceMapper & faceMap)
Definition at line 203 of file fvPatchMapper.C.
~fvPatchMapper()
~fvPatchMapper () virtual
Definition at line 221 of file fvPatchMapper.C.
Member Function Documentation
size()
virtual label size () const inline virtual
Implements FieldMapper.
Definition at line 120 of file fvPatchMapper.H.
References fvPatch::size().
sizeBeforeMapping()
virtual label sizeBeforeMapping () const inline virtual
Definition at line 126 of file fvPatchMapper.H.
direct()
virtual bool direct () const inline virtual
Implements FieldMapper.
Definition at line 132 of file fvPatchMapper.H.
References faceMapper::direct().
hasUnmapped()
virtual bool hasUnmapped () const inline virtual
Implements FieldMapper.
Definition at line 137 of file fvPatchMapper.H.
directAddressing()
const Foam::labelUList & directAddressing () const virtual
Reimplemented from FieldMapper.
Definition at line 229 of file fvPatchMapper.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
addressing()
const Foam::labelListList & addressing () const virtual
Reimplemented from FieldMapper.
Definition at line 247 of file fvPatchMapper.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
weights()
const Foam::scalarListList & weights () const virtual
Reimplemented from FieldMapper.
Definition at line 265 of file fvPatchMapper.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/fvMeshMapper/fvPatchMapper.H
src/finiteVolume/fvMesh/fvMeshMapper/fvPatchMapper.C