OpenFOAM: LuoSvendsen Class Reference
LuoSvendsen Class Reference
Model of Luo and Svendsen (1996). The breakup rate is calculated by.
#include <LuoSvendsen.H>
Public Member Functions
TypeName ("LuoSvendsen")
LuoSvendsen (const populationBalanceModel &popBal, const dictionary &dict)
virtual ~LuoSvendsen ()=default
virtual void correct ()
virtual void addToBinaryBreakupRate (volScalarField &binaryBreakupRate, const label i, const label j)
Public Member Functions inherited from binaryBreakupModel
TypeName ("binaryBreakupModel")
declareRunTimeSelectionTable (autoPtr, binaryBreakupModel, dictionary,(const populationBalanceModel &popBal, const dictionary &dict),(popBal, dict))
binaryBreakupModel (const populationBalanceModel &popBal, const dictionary &dict)
autoPtr< binaryBreakupModel > clone () const
virtual ~binaryBreakupModel ()=default
Additional Inherited Members
Static Public Member Functions inherited from binaryBreakupModel
static autoPtr< binaryBreakupModel > New (const word &type, const populationBalanceModel &popBal, const dictionary &dict)
Protected Attributes inherited from binaryBreakupModel
const populationBalanceModel & popBal_
Detailed Description
Model of Luo and Svendsen (1996). The breakup rate is calculated by.
where
and
The integral in the first expression is solved by means of incomplete Gamma functions as given by Bannari et al. (2008):
where
and
Note that in the code, the upper incomplete gamma function is expressed as
= Void fraction of continuous phase [-]
= Turbulent dissipation rate of continuous phase [m2/s3]
= Diameter of mother bubble j [m3]
= Volume of daughter bubble i [m3]
= Volume of mother bubble j [m3]
= Integration variable [-]
= Lower bound of integral [-]
= Increase coefficient of surface area [-]
= Surface tension [N/m]
= Density of continuous phase [kg/m3]
= Kolmogorov length scale [m]
= Upper incomplete gamma function
= Regularized upper incomplete gamma function
= Gamma function
References:
        Luo, H., & Svendsen, H. F. (1996).
        Theoretical model for drop and bubble breakup in turbulent dispersions.
        AIChE Journal, 42(5), 1225-1233.
        Eq. 27, p. 1229.
        Bannari, R., Kerdouss, F., Selma, B., Bannari, A., & Proulx, P. (2008).
        Three-dimensional mathematical modeling of dispersed two-phase flow
        using class method of population balance in bubble columns.
        Computers & chemical engineering, 32(12), 3224-3237.
        Eq. 49, p. 3230.
Usage
Property Description Required Default value
C4 Coefficient C4 no 0.923
beta Coefficient beta no 2.05
C5 Minimum eddy ratio no 11.4
Source files
LuoSvendsen.H
LuoSvendsen.C
Definition at line 226 of file LuoSvendsen.H.
Constructor & Destructor Documentation
LuoSvendsen()
LuoSvendsen (const populationBalanceModel & popBal, const dictionary & dict)
Definition at line 50 of file LuoSvendsen.C.
References PtrList< T >::append(), Foam::bounds::CLAMP, Foam::dimLength, Foam::dimless, e, and Foam::Math::incGammaRatio_Q().
~LuoSvendsen()
virtual ~LuoSvendsen () virtual default
Member Function Documentation
TypeName()
TypeName ("LuoSvendsen")
correct()
void correct () virtual
Reimplemented from binaryBreakupModel.
Definition at line 150 of file LuoSvendsen.C.
References Foam::pow025(), and Foam::pow3().
addToBinaryBreakupRate()
void addToBinaryBreakupRate (volScalarField & binaryBreakupRate, const label i, const label j) virtual
Implements binaryBreakupModel.
Definition at line 165 of file LuoSvendsen.C.
References b, Foam::cbrt(), forAll, Foam::pow(), phaseModel::rho(), and Foam::sqr().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/populationBalanceModel/binaryBreakupModels/LuoSvendsen/LuoSvendsen.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/populationBalanceModel/binaryBreakupModels/LuoSvendsen/LuoSvendsen.C