OpenFOAM: SLADelta Class Reference
SLADelta Class Reference
Delta formulation that accounts for the orientation of the vorticity vector and a flow-sensitised function to detect 2D flow regions. Delta value is strongly reduced in these regions to accelerate the transition from RANS to LES in hybrid RANS/LES simulations.
#include <SLADelta.H>
Public Member Functions
TypeName ("SLADelta")
SLADelta (const word &name, const turbulenceModel &turbulence, const dictionary &)
virtual ~SLADelta ()=default
void read (const dictionary &)
const volScalarField & hmax () const
void correct ()
Public Member Functions inherited from LESdelta
TypeName ("LESdelta")
declareRunTimeSelectionTable (autoPtr, LESdelta, dictionary,(const word &name, const turbulenceModel &turbulence, const dictionary &dict),(name, turbulence, dict))
LESdelta (const word &name, const turbulenceModel &turbulence)
virtual ~LESdelta ()=default
const turbulenceModel & turbulence () const
virtual operator const volScalarField & () const
Additional Inherited Members
Static Public Member Functions inherited from LESdelta
static autoPtr< LESdelta > New (const word &name, const turbulenceModel &turbulence, const dictionary &dict, const word &lookupName="delta")
static autoPtr< LESdelta > New (const word &name, const turbulenceModel &turbulence, const dictionary &dict, const dictionaryConstructorTableType &additionalConstructors, const word &lookupName="delta")
Protected Member Functions inherited from LESdelta
LESdelta (const LESdelta &)=delete
void operator= (const LESdelta &)=delete
Protected Attributes inherited from LESdelta
const turbulenceModel & turbulenceModel_
volScalarField delta_
Detailed Description
Delta formulation that accounts for the orientation of the vorticity vector and a flow-sensitised function to detect 2D flow regions. Delta value is strongly reduced in these regions to accelerate the transition from RANS to LES in hybrid RANS/LES simulations.
Reference:
    Shur, M. L., Spalart, P. R., Strelets, M. K., & Travin, A. K. (2015).
    An enhanced version of DES with rapid transition
    from RANS to LES in separated flows.
    Flow, turbulence and combustion, 95(4), 709-737.
    DOI:10.1007/s10494-015-9618-0
Source files
SLADelta.H
SLADelta.C
Definition at line 61 of file SLADelta.H.
Constructor & Destructor Documentation
SLADelta()
SLADelta (const word & name, const turbulenceModel & turbulence, const dictionary & dict)
Definition at line 238 of file SLADelta.C.
References Foam::abort(), dict, Foam::endl(), Foam::FatalIOError, FatalIOErrorInFunction, found, IOobject::groupName(), Foam::Info, Foam::mag(), LESdelta::New(), turbulence, LESdelta::turbulence(), and Foam::type().
~SLADelta()
virtual ~SLADelta () virtual default
Member Function Documentation
TypeName()
TypeName ("SLADelta")
read()
void read (const dictionary & dict) virtual
Implements LESdelta.
Definition at line 375 of file SLADelta.C.
References dict, dictionary::readIfPresent(), and Foam::type().
hmax()
const volScalarField & hmax () const inline
Definition at line 125 of file SLADelta.H.
correct()
void correct () virtual
Implements LESdelta.
Definition at line 394 of file SLADelta.C.
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/LES/LESdeltas/SLADelta/SLADelta.H
src/TurbulenceModels/turbulenceModels/LES/LESdeltas/SLADelta/SLADelta.C