OpenFOAM: faMatrix< Type > Class Template Reference
faMatrix< Type > Class Template Reference
A special matrix type and solver, designed for finite area solutions of scalar equations. Face addressing is used to make all matrix assembly and solution loops vectorise.
#include <faMatrix.H>
Classes
class faSolver
Public Types
typedef GeometricField< Type, faPatchField, areaMesh > psiFieldType
typedef GeometricField< Type, faePatchField, edgeMesh > faceFluxFieldType
typedef GeometricField< Type, faePatchField, edgeMesh > * faceFluxFieldPtrType
Public Types inherited from lduMatrix
enum class normTypes : char { NO_NORM , DEFAULT_NORM , L1_SCALED_NORM }
Public Member Functions
ClassName ("faMatrix")
faMatrix (const GeometricField< Type, faPatchField, areaMesh > &psi, const dimensionSet &ds)
faMatrix (const faMatrix< Type > &)
faMatrix (const tmp< faMatrix< Type > > &)
faMatrix (const GeometricField< Type, faPatchField, areaMesh > &psi, Istream &is)
tmp< faMatrix< Type > > clone () const
virtual ~faMatrix ()
const GeometricField< Type, faPatchField, areaMesh > & psi () const
const dimensionSet & dimensions () const noexcept
Field< Type > & source () noexcept
const Field< Type > & source () const noexcept
const FieldField< Field, Type > & internalCoeffs () const noexcept
FieldField< Field, Type > & internalCoeffs () noexcept
const FieldField< Field, Type > & boundaryCoeffs () const noexcept
FieldField< Field, Type > & boundaryCoeffs () noexcept
faceFluxFieldPtrType & faceFluxCorrectionPtr ()
bool hasFaceFluxCorrection () const noexcept
void setValues (const labelUList &faceLabels, const Type &value)
void setValues (const labelUList &faceLabels, const UList< Type > &values)
void setValues (const labelUList &faceLabels, const UIndirectList< Type > &values)
void setReference (const label facei, const Type &value, const bool forceReference=false)
void setReferences (const labelUList &faceLabels, const Type &value, const bool forceReference=false)
void setReferences (const labelUList &faceLabels, const UList< Type > &values, const bool forceReference=false)
void setComponentReference (const label patchi, const label facei, const direction cmpt, const scalar value)
void relax (const scalar alpha)
void relax ()
SolverPerformance< Type > solve (const dictionary &)
SolverPerformance< Type > solve ()
tmp< Field< Type > > residual () const
tmp< scalarField > D () const
tmp< areaScalarField > A () const
tmp< GeometricField< Type, faPatchField, areaMesh > > H () const
tmp< GeometricField< Type, faePatchField, edgeMesh > > flux () const
void operator= (const faMatrix< Type > &)
void operator= (const tmp< faMatrix< Type > > &)
void negate ()
void operator+= (const faMatrix< Type > &)
void operator+= (const tmp< faMatrix< Type > > &)
void operator-= (const faMatrix< Type > &)
void operator-= (const tmp< faMatrix< Type > > &)
void operator+= (const DimensionedField< Type, areaMesh > &)
void operator+= (const tmp< DimensionedField< Type, areaMesh > > &)
void operator+= (const tmp< GeometricField< Type, faPatchField, areaMesh > > &)
void operator-= (const DimensionedField< Type, areaMesh > &)
void operator-= (const tmp< DimensionedField< Type, areaMesh > > &)
void operator-= (const tmp< GeometricField< Type, faPatchField, areaMesh > > &)
void operator+= (const dimensioned< Type > &)
void operator-= (const dimensioned< Type > &)
void operator+= (const Foam::zero)
void operator-= (const Foam::zero)
void operator*= (const areaScalarField::Internal &)
void operator*= (const tmp< areaScalarField::Internal > &)
void operator*= (const tmp< areaScalarField > &)
void operator*= (const dimensioned< scalar > &)
void setComponentReference (const label patchI, const label edgeI, const direction, const scalar value)
Foam::solverPerformance solve (const dictionary &solverControls)
Foam::tmp< Foam::scalarField > residual () const
Foam::tmp< Foam::areaScalarField > H () const
void setComponentReference (const label patchi, const label facei, const direction, const scalar value)
SolverPerformance< scalar > solve (const dictionary &)
tmp< scalarField > residual () const
tmp< areaScalarField > H () const
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Public Member Functions inherited from lduMatrix
ClassName ("lduMatrix")
lduMatrix (const lduMesh &)
lduMatrix (const lduMatrix &)
lduMatrix (lduMatrix &, bool reuse)
lduMatrix (const lduMesh &, Istream &)
~lduMatrix ()
const lduMesh & mesh () const noexcept
void setLduMesh (const lduMesh &m)
const lduAddressing & lduAddr () const
const lduSchedule & patchSchedule () const
scalarField & lower ()
scalarField & diag ()
scalarField & upper ()
scalarField & lower (const label size)
scalarField & diag (const label nCoeffs)
scalarField & upper (const label nCoeffs)
const scalarField & lower () const
const scalarField & diag () const
const scalarField & upper () const
bool hasDiag () const noexcept
bool hasUpper () const noexcept
bool hasLower () const noexcept
bool diagonal () const noexcept
bool symmetric () const noexcept
bool asymmetric () const noexcept
void sumDiag ()
void negSumDiag ()
void sumMagOffDiag (scalarField &sumOff) const
void Amul (solveScalarField &, const tmp< solveScalarField > &, const FieldField< Field, scalar > &, const lduInterfaceFieldPtrsList &, const direction cmpt) const
void Tmul (solveScalarField &, const tmp< solveScalarField > &, const FieldField< Field, scalar > &, const lduInterfaceFieldPtrsList &, const direction cmpt) const
void sumA (solveScalarField &, const FieldField< Field, scalar > &, const lduInterfaceFieldPtrsList &) const
void residual (solveScalarField &rA, const solveScalarField &psi, const scalarField &source, const FieldField< Field, scalar > &interfaceBouCoeffs, const lduInterfaceFieldPtrsList &interfaces, const direction cmpt) const
tmp< solveScalarField > residual (const solveScalarField &psi, const scalarField &source, const FieldField< Field, scalar > &interfaceBouCoeffs, const lduInterfaceFieldPtrsList &interfaces, const direction cmpt) const
void initMatrixInterfaces (const bool add, const FieldField< Field, scalar > &interfaceCoeffs, const lduInterfaceFieldPtrsList &interfaces, const solveScalarField &psiif, solveScalarField &result, const direction cmpt) const
void updateMatrixInterfaces (const bool add, const FieldField< Field, scalar > &interfaceCoeffs, const lduInterfaceFieldPtrsList &interfaces, const solveScalarField &psiif, solveScalarField &result, const direction cmpt, const label startRequest) const
void setResidualField (const scalarField &residual, const word &fieldName, const bool initial) const
template<class Type >
tmp< Field< Type > > H (const Field< Type > &) const
template<class Type >
tmp< Field< Type > > H (const tmp< Field< Type > > &) const
tmp< scalarField > H1 () const
template<class Type >
tmp< Field< Type > > faceH (const Field< Type > &) const
template<class Type >
tmp< Field< Type > > faceH (const tmp< Field< Type > > &) const
InfoProxy< lduMatrix > info () const noexcept
void operator= (const lduMatrix &)
void negate ()
void operator+= (const lduMatrix &)
void operator-= (const lduMatrix &)
void operator*= (const scalarField &)
void operator*= (scalar)
template<class Type >
Foam::tmp< Foam::Field< Type > > H (const Field< Type > &psi) const
template<class Type >
Foam::tmp< Foam::Field< Type > > H (const tmp< Field< Type > > &tpsi) const
template<class Type >
Foam::tmp< Foam::Field< Type > > faceH (const Field< Type > &psi) const
template<class Type >
Foam::tmp< Foam::Field< Type > > faceH (const tmp< Field< Type > > &tpsi) const
Protected Member Functions
template<class Type2 >
void addToInternalField (const labelUList &addr, const Field< Type2 > &pf, Field< Type2 > &intf) const
template<class Type2 >
void addToInternalField (const labelUList &addr, const tmp< Field< Type2 > > &tpf, Field< Type2 > &intf) const
template<class Type2 >
void subtractFromInternalField (const labelUList &addr, const Field< Type2 > &pf, Field< Type2 > &intf) const
template<class Type2 >
void subtractFromInternalField (const labelUList &addr, const tmp< Field< Type2 > > &tpf, Field< Type2 > &intf) const
void addBoundaryDiag (scalarField &diag, const direction cmpt) const
void addCmptAvBoundaryDiag (scalarField &diag) const
void addBoundarySource (Field< Type > &source, const bool couples=true) const
template<template< class > class ListType>
void setValuesFromList (const labelUList &faceLabels, const ListType< Type > &values)
Friends
class faSolver
tmp< GeometricField< Type, faPatchField, areaMesh > > operator& (const faMatrix< Type > &, const DimensionedField< Type, areaMesh > &)
tmp< GeometricField< Type, faPatchField, areaMesh > > operator& (const faMatrix< Type > &, const tmp< GeometricField< Type, faPatchField, areaMesh > > &)
tmp< GeometricField< Type, faPatchField, areaMesh > > operator& (const tmp< faMatrix< Type > > &, const DimensionedField< Type, areaMesh > &)
tmp< GeometricField< Type, faPatchField, areaMesh > > operator& (const tmp< faMatrix< Type > > &, const tmp< GeometricField< Type, faPatchField, areaMesh > > &)
Ostream & operator<< (Ostream &, const faMatrix< Type > &)
Additional Inherited Members
Static Public Attributes inherited from lduMatrix
static const Enum< normTypes > normTypesNames_
static constexpr const label defaultMaxIter = 1000
static const scalar defaultTolerance = 1e-6
Detailed Description
template<class Type>
class Foam::faMatrix< Type >
A special matrix type and solver, designed for finite area solutions of scalar equations. Face addressing is used to make all matrix assembly and solution loops vectorise.
Finite-Area matrix.
Author Zeljko Tukovic, FMENA Hrvoje Jasak, Wikki Ltd.
Source files
faMatrix.H
faMatrix.C
faMatrixSolve.C
Author Zeljko Tukovic, FMENA Hrvoje Jasak, Wikki Ltd.
Definition at line 108 of file faMatrix.H.
Member Typedef Documentation
psiFieldType
template<class Type > typedef GeometricField<Type, faPatchField, areaMesh> psiFieldType
Definition at line 120 of file faMatrix.H.
faceFluxFieldType
template<class Type > typedef GeometricField<Type, faePatchField, edgeMesh> faceFluxFieldType
Definition at line 125 of file faMatrix.H.
faceFluxFieldPtrType
template<class Type > typedef GeometricField<Type, faePatchField, edgeMesh>* faceFluxFieldPtrType
Definition at line 356 of file faMatrix.H.
Constructor & Destructor Documentation
faMatrix() [1/4]
template<class Type > faMatrix (const GeometricField< Type, faPatchField, areaMesh > & psi, const dimensionSet & ds)
Definition at line 178 of file faMatrix.C.
References DebugInFunction, Foam::endl(), forAll, faMatrix< Type >::psi(), PtrList< T >::set(), UPtrList< T >::size(), and Foam::Zero.
faMatrix() [2/4]
template<class Type > faMatrix (const faMatrix< Type > & fam)
Definition at line 223 of file faMatrix.C.
References DebugInFunction, and Foam::endl().
faMatrix() [3/4]
template<class Type > faMatrix (const tmp< faMatrix< Type > > & tmat)
Definition at line 248 of file faMatrix.C.
References PtrList< T >::clear(), DebugInFunction, and Foam::endl().
faMatrix() [4/4]
template<class Type > faMatrix (const GeometricField< Type, faPatchField, areaMesh > & psi, Istream & is) inline
Definition at line 282 of file faMatrix.H.
~faMatrix()
template<class Type > ~faMatrix () virtual
Definition at line 285 of file faMatrix.C.
References DebugInFunction, Foam::deleteDemandDrivenData(), and Foam::endl().
Member Function Documentation
addToInternalField() [1/2]
template<class Type > template<class Type2 > void addToInternalField (const labelUList & addr, const Field< Type2 > & pf, Field< Type2 > & intf) const protected
Definition at line 35 of file faMatrix.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, PtrList< T >::PtrList(), and UPtrList< T >::size().
addToInternalField() [2/2]
template<class Type > template<class Type2 > void addToInternalField (const labelUList & addr, const tmp< Field< Type2 > > & tpf, Field< Type2 > & intf) const protected
Definition at line 59 of file faMatrix.C.
References PtrList< T >::clear().
subtractFromInternalField() [1/2]
template<class Type > template<class Type2 > void subtractFromInternalField (const labelUList & addr, const Field< Type2 > & pf, Field< Type2 > & intf) const protected
Definition at line 73 of file faMatrix.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, and UPtrList< T >::size().
subtractFromInternalField() [2/2]
template<class Type > template<class Type2 > void subtractFromInternalField (const labelUList & addr, const tmp< Field< Type2 > > & tpf, Field< Type2 > & intf) const protected
Definition at line 97 of file faMatrix.C.
References PtrList< T >::clear().
addBoundaryDiag()
template<class Type > void addBoundaryDiag (scalarField & diag, const direction cmpt) const protected
Definition at line 110 of file faMatrix.C.
References Foam::component(), Foam::diag(), and forAll.
addCmptAvBoundaryDiag()
template<class Type > void addCmptAvBoundaryDiag (scalarField & diag) const protected
Definition at line 129 of file faMatrix.C.
References Foam::cmptAv(), Foam::diag(), and forAll.
addBoundarySource()
template<class Type > void addBoundarySource (Field< Type > & source, const bool couples = true) const protected
Definition at line 144 of file faMatrix.C.
References Foam::cmptMultiply(), and forAll.
setValuesFromList()
template<class Type > template<template< class > class ListType> void setValuesFromList (const labelUList & faceLabels, const ListType< Type > & values) protected
Definition at line 298 of file faMatrix.C.
References fvMesh::boundary(), Foam::diag(), primitiveMesh::faceEdges(), faceLabels(), forAll, mesh, fvMesh::neighbour(), fvMesh::owner(), primitiveFieldRef(), psi, and Foam::Zero.
ClassName()
template<class Type > ClassName ("faMatrix< Type >")
clone()
template<class Type > tmp< faMatrix< Type > > clone () const inline
Definition at line 292 of file faMatrix.H.
References Foam::New().
psi()
template<class Type > const GeometricField< Type, faPatchField, areaMesh > & psi () const inline
Definition at line 306 of file faMatrix.H.
Referenced by faMatrix< Type >::faMatrix().
dimensions()
template<class Type > const dimensionSet & dimensions () const inline noexcept
Definition at line 311 of file faMatrix.H.
source() [1/2]
template<class Type > Field< Type > & source () inline noexcept
Definition at line 316 of file faMatrix.H.
source() [2/2]
template<class Type > const Field< Type > & source () const inline noexcept
Definition at line 321 of file faMatrix.H.
internalCoeffs() [1/2]
template<class Type > const FieldField< Field, Type > & internalCoeffs () const inline noexcept
Definition at line 328 of file faMatrix.H.
internalCoeffs() [2/2]
template<class Type > FieldField< Field, Type > & internalCoeffs () inline noexcept
Definition at line 335 of file faMatrix.H.
boundaryCoeffs() [1/2]
template<class Type > const FieldField< Field, Type > & boundaryCoeffs () const inline noexcept
Definition at line 342 of file faMatrix.H.
boundaryCoeffs() [2/2]
template<class Type > FieldField< Field, Type > & boundaryCoeffs () inline noexcept
Definition at line 349 of file faMatrix.H.
faceFluxCorrectionPtr()
template<class Type > faceFluxFieldPtrType & faceFluxCorrectionPtr () inline
Definition at line 359 of file faMatrix.H.
hasFaceFluxCorrection()
template<class Type > bool hasFaceFluxCorrection () const inline noexcept
Definition at line 365 of file faMatrix.H.
setValues() [1/3]
template<class Type > void setValues (const labelUList & faceLabels, const Type & value)
Definition at line 401 of file faMatrix.C.
References faceLabels().
setValues() [2/3]
template<class Type > void setValues (const labelUList & faceLabels, const UList< Type > & values)
Definition at line 412 of file faMatrix.C.
References faceLabels().
setValues() [3/3]
template<class Type > void setValues (const labelUList & faceLabels, const UIndirectList< Type > & values)
Definition at line 423 of file faMatrix.C.
References faceLabels().
setReference()
template<class Type > void setReference (const label facei, const Type & value, const bool forceReference = false)
Definition at line 434 of file faMatrix.C.
References Foam::diag(), and UPstream::master().
setReferences() [1/2]
template<class Type > void setReferences (const labelUList & faceLabels, const Type & value, const bool forceReference = false)
Definition at line 453 of file faMatrix.C.
References Foam::diag(), faceId(), faceLabels(), and forAll.
setReferences() [2/2]
template<class Type > void setReferences (const labelUList & faceLabels, const UList< Type > & values, const bool forceReference = false)
Definition at line 476 of file faMatrix.C.
References Foam::diag(), faceId(), faceLabels(), and forAll.
setComponentReference() [1/3]
template<class Type > void setComponentReference (const label patchi, const label facei, const direction cmpt, const scalar value)
Definition at line 31 of file faMatrixSolve.C.
References Foam::diag().
relax() [1/2]
template<class Type > void relax (const scalar alpha)
Definition at line 499 of file faMatrix.C.
References alpha, Foam::cmptMag(), Foam::cmptMin(), Foam::cmptMultiply(), Foam::component(), D, Foam::diag(), forAll, Foam::mag(), Foam::max(), UPtrList< T >::size(), and Foam::Zero.
relax() [2/2]
template<class Type > void relax ()
Definition at line 589 of file faMatrix.C.
References DebugInFunction, Foam::endl(), and relax().
solve() [1/4]
template<class Type > Foam::SolverPerformance< Type > solve (const dictionary & solverControls)
Definition at line 48 of file faMatrixSolve.C.
References DebugInFunction, Foam::diag(), Foam::endl(), Foam::Info, lduMatrix::solver::New(), UPstream::nRequests(), and psi.
solve() [2/4]
template<class Type > Foam::SolverPerformance< Type > solve ()
Definition at line 173 of file faMatrixSolve.C.
References mesh, Foam::name(), psi, and solve().
residual() [1/3]
template<class Type > Foam::tmp< Foam::Field< Type > > residual () const
Definition at line 180 of file faMatrixSolve.C.
References lduMatrix::residual(), and Foam::Zero.
D()
template<class Type > Foam::tmp< Foam::scalarField > D () const
Definition at line 605 of file faMatrix.C.
References Foam::diag(), and tmp< T >::New().
A()
template<class Type > Foam::tmp< Foam::areaScalarField > A () const
Definition at line 614 of file faMatrix.C.
References D, Foam::dimArea, faPatchFieldBase::extrapolatedCalculatedType(), and GeometricField< scalar, faPatchField, areaMesh >::New().
H() [1/3]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::faPatchField, Foam::areaMesh > > H () const
Definition at line 633 of file faMatrix.C.
References Foam::dimArea, faPatchFieldBase::extrapolatedCalculatedType(), lduMatrix::H(), GeometricField< Type, PatchField, GeoMesh >::New(), and Foam::Zero.
flux()
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::faePatchField, Foam::edgeMesh > > flux () const
Definition at line 669 of file faMatrix.C.
References Foam::abort(), Foam::cmptMultiply(), lduMatrix::faceH(), Foam::FatalError, FatalErrorInFunction, forAll, and GeometricField< Type, PatchField, GeoMesh >::New().
operator=() [1/2]
template<class Type > void operator= (const faMatrix< Type > & famv)
Definition at line 741 of file faMatrix.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and lduMatrix::operator=().
operator=() [2/2]
template<class Type > void operator= (const tmp< faMatrix< Type > > & tfamv)
Definition at line 774 of file faMatrix.C.
References PtrList< T >::clear().
negate()
template<class Type > void negate ()
Definition at line 782 of file faMatrix.C.
References lduMatrix::negate().
operator+=() [1/7]
template<class Type > void operator+= (const faMatrix< Type > & famv)
Definition at line 797 of file faMatrix.C.
References Foam::checkMethod(), and lduMatrix::operator+=().
operator+=() [2/7]
template<class Type > void operator+= (const tmp< faMatrix< Type > > & tfamv)
Definition at line 823 of file faMatrix.C.
References PtrList< T >::clear().
operator-=() [1/7]
template<class Type > void operator-= (const faMatrix< Type > & famv)
Definition at line 831 of file faMatrix.C.
References Foam::checkMethod(), and lduMatrix::operator-=().
operator-=() [2/7]
template<class Type > void operator-= (const tmp< faMatrix< Type > > & tfamv)
Definition at line 855 of file faMatrix.C.
References PtrList< T >::clear().
operator+=() [3/7]
template<class Type > void operator+= (const DimensionedField< Type, areaMesh > & su)
Definition at line 863 of file faMatrix.C.
References Foam::checkMethod().
operator+=() [4/7]
template<class Type > void operator+= (const tmp< DimensionedField< Type, areaMesh > > & tsu)
Definition at line 874 of file faMatrix.C.
References PtrList< T >::clear().
operator+=() [5/7]
template<class Type > void operator+= (const tmp< GeometricField< Type, faPatchField, areaMesh > > & tsu)
Definition at line 885 of file faMatrix.C.
References PtrList< T >::clear().
operator-=() [3/7]
template<class Type > void operator-= (const DimensionedField< Type, areaMesh > & su)
Definition at line 896 of file faMatrix.C.
References Foam::checkMethod().
operator-=() [4/7]
template<class Type > void operator-= (const tmp< DimensionedField< Type, areaMesh > > & tsu)
Definition at line 907 of file faMatrix.C.
References PtrList< T >::clear().
operator-=() [5/7]
template<class Type > void operator-= (const tmp< GeometricField< Type, faPatchField, areaMesh > > & tsu)
Definition at line 918 of file faMatrix.C.
References PtrList< T >::clear().
operator+=() [6/7]
template<class Type > void operator+= (const dimensioned< Type > & su)
Definition at line 929 of file faMatrix.C.
References psi.
operator-=() [6/7]
template<class Type > void operator-= (const dimensioned< Type > & su)
Definition at line 939 of file faMatrix.C.
References psi.
operator+=() [7/7]
template<class Type > void operator+= (const Foam::zero)
Definition at line 949 of file faMatrix.C.
operator-=() [7/7]
template<class Type > void operator-= (const Foam::zero)
Definition at line 954 of file faMatrix.C.
operator*=() [1/4]
template<class Type > void operator*= (const areaScalarField::Internal & dsf)
Definition at line 959 of file faMatrix.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, and lduMatrix::operator*=().
operator*=() [2/4]
template<class Type > void operator*= (const tmp< areaScalarField::Internal > & tfld)
Definition at line 988 of file faMatrix.C.
References PtrList< T >::clear().
operator*=() [3/4]
template<class Type > void operator*= (const tmp< areaScalarField > & tfld)
Definition at line 999 of file faMatrix.C.
References PtrList< T >::clear().
operator*=() [4/4]
template<class Type > void operator*= (const dimensioned< scalar > & ds)
Definition at line 1010 of file faMatrix.C.
References lduMatrix::operator*=().
setComponentReference() [2/3]
void setComponentReference (const label patchI, const label edgeI, const direction , const scalar value)
Definition at line 30 of file faScalarMatrix.C.
References Foam::diag(), faceLabels(), and PtrList< T >::PtrList().
solve() [3/4]
Foam::solverPerformance solve (const dictionary & solverControls)
Definition at line 47 of file faScalarMatrix.C.
References DebugInFunction, Foam::diag(), Foam::endl(), Foam::Info, lduMatrix::solver::New(), and psi.
residual() [2/3]
Foam::tmp< Foam::scalarField > residual () const
Definition at line 99 of file faScalarMatrix.C.
References psi, lduMatrix::residual(), and Foam::Zero.
H() [2/3]
Foam::tmp< Foam::areaScalarField > H () const
Definition at line 128 of file faScalarMatrix.C.
References Foam::dimArea, faPatchFieldBase::extrapolatedCalculatedType(), lduMatrix::H(), and GeometricField< scalar, faPatchField, areaMesh >::New().
setComponentReference() [3/3]
void setComponentReference (const label patchi, const label facei, const direction , const scalar value)
solve() [4/4]
SolverPerformance< scalar > solve (const dictionary &)
residual() [3/3]
tmp< scalarField > residual () const
H() [3/3]
tmp< areaScalarField > H () const
Friends And Related Symbol Documentation
faSolver
template<class Type > friend class faSolver friend
Definition at line 159 of file faMatrix.H.
operator& [1/4]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > operator& (const faMatrix< Type > & , const DimensionedField< Type, areaMesh > &) friend
operator& [2/4]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > operator& (const faMatrix< Type > & , const tmp< GeometricField< Type, faPatchField, areaMesh > > &) friend
operator& [3/4]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > operator& (const tmp< faMatrix< Type > > & , const DimensionedField< Type, areaMesh > &) friend
operator& [4/4]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > operator& (const tmp< faMatrix< Type > > & , const tmp< GeometricField< Type, faPatchField, areaMesh > > &) friend
operator<<
template<class Type > Ostream & operator<< (Ostream & , const faMatrix< Type > &) friend
The documentation for this class was generated from the following files:
src/finiteArea/faMatrices/faMatricesFwd.H
src/finiteArea/faMatrices/faMatrix/faMatrix.H
src/finiteArea/faMatrices/faMatrix/faMatrix.C
src/finiteArea/faMatrices/faMatrix/faMatrixSolve.C