OpenFOAM: StochasticDispersionRAS< CloudType > Class Template Reference
StochasticDispersionRAS< CloudType > Class Template Reference
The velocity is perturbed in random direction, with a Gaussian random number distribution with variance sigma. where sigma is defined below.
#include <StochasticDispersionRAS.H>
Public Member Functions
TypeName ("stochasticDispersionRAS")
StochasticDispersionRAS (const dictionary &dict, CloudType &owner)
StochasticDispersionRAS (const StochasticDispersionRAS< CloudType > &dm)
virtual autoPtr< DispersionModel< CloudType > > clone () const
virtual ~StochasticDispersionRAS ()
virtual vector update (const scalar dt, const label celli, const vector &U, const vector &Uc, vector &UTurb, scalar &tTurb)
Public Member Functions inherited from DispersionRASModel< CloudType >
TypeName ("dispersionRASModel")
DispersionRASModel (const dictionary &dict, CloudType &owner)
DispersionRASModel (const DispersionRASModel< CloudType > &dm)
virtual ~DispersionRASModel ()
virtual void cacheFields (const bool store)
virtual void write (Ostream &os) const
Public Member Functions inherited from DispersionModel< CloudType >
TypeName ("dispersionModel")
declareRunTimeSelectionTable (autoPtr, DispersionModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
DispersionModel (CloudType &owner)
DispersionModel (const dictionary &dict, CloudType &owner, const word &type)
DispersionModel (const DispersionModel< CloudType > &dm)
virtual ~DispersionModel ()
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
virtual ~CloudSubModelBase ()=default
const CloudType & owner () const
virtual bool writeTime () const
virtual fileName localPath () const
CloudType & owner ()
virtual void info ()
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
subModelBase (const subModelBase &smb)
virtual ~subModelBase ()=default
const word & modelName () const
const dictionary & dict () const
const word & baseName () const
const word & modelType () const
const dictionary & coeffDict () const
const dictionary & properties () const
virtual bool defaultCoeffs (const bool printMsg) const
virtual bool active () const
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
bool getModelDict (const word &entryName, dictionary &dict) const
template<class Type >
bool getModelProperty (const word &entryName, Type &value) const
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Additional Inherited Members
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Static Public Member Functions inherited from DispersionModel< CloudType >
static autoPtr< DispersionModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Public Attributes inherited from subModelBase
bool log
Protected Member Functions inherited from DispersionRASModel< CloudType >
tmp< volScalarField > kModel () const
tmp< volScalarField > epsilonModel () const
Protected Member Functions inherited from subModelBase
bool inLine () const
Protected Attributes inherited from DispersionRASModel< CloudType >
const volScalarField * kPtr_
const volScalarField * epsilonPtr_
bool ownK_
bool ownEpsilon_
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Protected Attributes inherited from subModelBase
const word modelName_
dictionary & properties_
const dictionary dict_
const word baseName_
const word modelType_
const dictionary coeffDict_
Detailed Description
template<class CloudType>
class Foam::StochasticDispersionRAS< CloudType >
The velocity is perturbed in random direction, with a Gaussian random number distribution with variance sigma. where sigma is defined below.
Definition at line 44 of file StochasticDispersionRAS.H.
Constructor & Destructor Documentation
StochasticDispersionRAS() [1/2]
template<class CloudType > StochasticDispersionRAS (const dictionary & dict, CloudType & owner)
Definition at line 29 of file StochasticDispersionRAS.C.
StochasticDispersionRAS() [2/2]
template<class CloudType > StochasticDispersionRAS (const StochasticDispersionRAS< CloudType > & dm)
Definition at line 40 of file StochasticDispersionRAS.C.
~StochasticDispersionRAS()
template<class CloudType > ~StochasticDispersionRAS () virtual
Definition at line 52 of file StochasticDispersionRAS.C.
Member Function Documentation
TypeName()
template<class CloudType > TypeName ("stochasticDispersionRAS")
clone()
template<class CloudType > virtual autoPtr< DispersionModel< CloudType > > clone () const inline virtual
Implements DispersionRASModel< CloudType >.
Definition at line 63 of file StochasticDispersionRAS.H.
update()
template<class CloudType > Foam::vector update (const scalar dt, const label celli, const vector & U, const vector & Uc, vector & UTurb, scalar & tTurb) virtual
Implements DispersionRASModel< CloudType >.
Definition at line 59 of file StochasticDispersionRAS.C.
References Foam::cos(), epsilon, k, Foam::mag(), Foam::min(), Foam::pow(), Foam::sin(), Foam::sqr(), Foam::sqrt(), Foam::constant::mathematical::twoPi(), U, and Foam::Zero.
The documentation for this class was generated from the following files:
src/lagrangian/turbulence/submodels/Kinematic/DispersionModel/StochasticDispersionRAS/StochasticDispersionRAS.H
src/lagrangian/turbulence/submodels/Kinematic/DispersionModel/StochasticDispersionRAS/StochasticDispersionRAS.C