OpenFOAM: JohnsonJacksonParticleSlipFvPatchVectorField Class Reference
JohnsonJacksonParticleSlipFvPatchVectorField Class Reference
Partial slip boundary condition for the particulate velocity.
#include <JohnsonJacksonParticleSlipFvPatchVectorField.H>
Public Member Functions
TypeName ("JohnsonJacksonParticleSlip")
JohnsonJacksonParticleSlipFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
JohnsonJacksonParticleSlipFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
JohnsonJacksonParticleSlipFvPatchVectorField (const JohnsonJacksonParticleSlipFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
JohnsonJacksonParticleSlipFvPatchVectorField (const JohnsonJacksonParticleSlipFvPatchVectorField &)
virtual tmp< fvPatchVectorField > clone () const
JohnsonJacksonParticleSlipFvPatchVectorField (const JohnsonJacksonParticleSlipFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
virtual void autoMap (const fvPatchFieldMapper &)
virtual void rmap (const fvPatchVectorField &, const labelList &)
virtual void updateCoeffs ()
virtual void write (Ostream &) const
TypeName ("JohnsonJacksonParticleSlip")
JohnsonJacksonParticleSlipFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
JohnsonJacksonParticleSlipFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
JohnsonJacksonParticleSlipFvPatchVectorField (const JohnsonJacksonParticleSlipFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
JohnsonJacksonParticleSlipFvPatchVectorField (const JohnsonJacksonParticleSlipFvPatchVectorField &)
virtual tmp< fvPatchVectorField > clone () const
JohnsonJacksonParticleSlipFvPatchVectorField (const JohnsonJacksonParticleSlipFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
virtual void autoMap (const fvPatchFieldMapper &)
virtual void rmap (const fvPatchVectorField &, const labelList &)
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
Partial slip boundary condition for the particulate velocity.
References:
    Reuge, N., Cadoret, L., Coufort-Saudejaud, C., Pannala, S., Syamlal, M.,
    & Caussat, B. (2008).
    Multifluid Eulerian modeling of dense gas–solids fluidized bed
    hydrodynamics: influence of the dissipation parameters.
    Chemical Engineering Science, 63(22), 5540-5551.
    Johnson, P. C., & Jackson, R. (1987).
    Frictional–collisional constitutive relations for granular materials,
    with application to plane shearing.
    Journal of fluid Mechanics, 176, 67-93.
Source files
JohnsonJacksonParticleSlipFvPatchVectorField.H
JohnsonJacksonParticleSlipFvPatchVectorField.C
References:
    "Multifluid Eulerian modeling of dense gas–solids fluidized bed
     hydrodynamics: Influence of the dissipation parameters"
    Reuge, N.,
    Chemical Engineering Science
    Volume 63, Issue 22, November 2008, pp. 5540-5551
    "Frictional-collisional constitutive relations for granular materials,
     with application to plane shearing"
    Johnson, P.C., and Jackson, R.,
    Journal of Fluid Mechanics
    Volume 176, March 1987, pp. 67-93
Source files
JohnsonJacksonParticleSlipFvPatchVectorField.H
JohnsonJacksonParticleSlipFvPatchVectorField.C
Definition at line 62 of file JohnsonJacksonParticleSlipFvPatchVectorField.H.
Constructor & Destructor Documentation
JohnsonJacksonParticleSlipFvPatchVectorField() [1/10]
JohnsonJacksonParticleSlipFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Definition at line 39 of file JohnsonJacksonParticleSlipFvPatchVectorField.C.
References Foam::dimless.
JohnsonJacksonParticleSlipFvPatchVectorField() [2/10]
JohnsonJacksonParticleSlipFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Definition at line 65 of file JohnsonJacksonParticleSlipFvPatchVectorField.C.
References Foam::abort(), dict, Foam::FatalError, FatalErrorInFunction, IOobjectOption::MUST_READ, and dimensioned< Type >::value().
JohnsonJacksonParticleSlipFvPatchVectorField() [3/10]
JohnsonJacksonParticleSlipFvPatchVectorField (const JohnsonJacksonParticleSlipFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 51 of file JohnsonJacksonParticleSlipFvPatchVectorField.C.
JohnsonJacksonParticleSlipFvPatchVectorField() [4/10]
JohnsonJacksonParticleSlipFvPatchVectorField (const JohnsonJacksonParticleSlipFvPatchVectorField & ptf)
Definition at line 91 of file JohnsonJacksonParticleSlipFvPatchVectorField.C.
JohnsonJacksonParticleSlipFvPatchVectorField() [5/10]
JohnsonJacksonParticleSlipFvPatchVectorField (const JohnsonJacksonParticleSlipFvPatchVectorField & ptf, const DimensionedField< vector, volMesh > & iF)
Definition at line 102 of file JohnsonJacksonParticleSlipFvPatchVectorField.C.
JohnsonJacksonParticleSlipFvPatchVectorField() [6/10]
JohnsonJacksonParticleSlipFvPatchVectorField (const fvPatch & , const DimensionedField< vector, volMesh > &)
JohnsonJacksonParticleSlipFvPatchVectorField() [7/10]
JohnsonJacksonParticleSlipFvPatchVectorField (const fvPatch & , const DimensionedField< vector, volMesh > & , const dictionary &)
JohnsonJacksonParticleSlipFvPatchVectorField() [8/10]
JohnsonJacksonParticleSlipFvPatchVectorField (const JohnsonJacksonParticleSlipFvPatchVectorField & , const fvPatch & , const DimensionedField< vector, volMesh > & , const fvPatchFieldMapper &)
JohnsonJacksonParticleSlipFvPatchVectorField() [9/10]
JohnsonJacksonParticleSlipFvPatchVectorField (const JohnsonJacksonParticleSlipFvPatchVectorField &)
JohnsonJacksonParticleSlipFvPatchVectorField() [10/10]
JohnsonJacksonParticleSlipFvPatchVectorField (const JohnsonJacksonParticleSlipFvPatchVectorField & , const DimensionedField< vector, volMesh > &)
Member Function Documentation
TypeName() [1/2]
TypeName ("JohnsonJacksonParticleSlip")
clone() [1/4]
virtual tmp< fvPatchVectorField > clone () const inline virtual
Definition at line 111 of file JohnsonJacksonParticleSlipFvPatchVectorField.H.
clone() [2/4]
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Definition at line 127 of file JohnsonJacksonParticleSlipFvPatchVectorField.H.
autoMap() [1/2]
void autoMap (const fvPatchFieldMapper & m) virtual
Definition at line 116 of file JohnsonJacksonParticleSlipFvPatchVectorField.C.
rmap() [1/2]
void rmap (const fvPatchVectorField & ptf, const labelList & addr) virtual
Definition at line 125 of file JohnsonJacksonParticleSlipFvPatchVectorField.C.
updateCoeffs() [1/2]
void updateCoeffs () virtual
Definition at line 135 of file JohnsonJacksonParticleSlipFvPatchVectorField.C.
References alpha, alphaMax(), Foam::dimless, fluid, IOobject::groupName(), Foam::max(), nu, twoPhaseSystem::phase1(), twoPhaseSystem::phase2(), Foam::constant::mathematical::pi(), Foam::sqrt(), and dimensioned< Type >::value().
write() [1/2]
void write (Ostream & os) const virtual
Definition at line 228 of file JohnsonJacksonParticleSlipFvPatchVectorField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntry(), and fvPatchField< Type >::writeValueEntry().
TypeName() [2/2]
TypeName ("JohnsonJacksonParticleSlip")
clone() [3/4]
virtual tmp< fvPatchVectorField > clone () const inline virtual
Definition at line 112 of file JohnsonJacksonParticleSlipFvPatchVectorField.H.
clone() [4/4]
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Definition at line 128 of file JohnsonJacksonParticleSlipFvPatchVectorField.H.
autoMap() [2/2]
virtual void autoMap (const fvPatchFieldMapper &) virtual
rmap() [2/2]
virtual void rmap (const fvPatchVectorField & , const labelList &) virtual
updateCoeffs() [2/2]
virtual void updateCoeffs () virtual
write() [2/2]
virtual void write (Ostream &) const virtual
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/twoPhaseCompressibleTurbulenceModels/kineticTheoryModels/derivedFvPatchFields/JohnsonJacksonParticleSlip/JohnsonJacksonParticleSlipFvPatchVectorField.H
src/phaseSystemModels/twoPhaseEuler/phaseCompressibleTurbulenceModels/kineticTheoryModels/derivedFvPatchFields/JohnsonJacksonParticleSlip/JohnsonJacksonParticleSlipFvPatchVectorField.H
src/phaseSystemModels/reactingEuler/twoPhaseCompressibleTurbulenceModels/kineticTheoryModels/derivedFvPatchFields/JohnsonJacksonParticleSlip/JohnsonJacksonParticleSlipFvPatchVectorField.C
src/phaseSystemModels/twoPhaseEuler/phaseCompressibleTurbulenceModels/kineticTheoryModels/derivedFvPatchFields/JohnsonJacksonParticleSlip/JohnsonJacksonParticleSlipFvPatchVectorField.C