OpenFOAM: ThermalPhaseChangePhaseSystem< BasePhaseSystem > Class Template Reference
ThermalPhaseChangePhaseSystem< BasePhaseSystem > Class Template Reference
Class to provide interfacial heat and mass transfer between a number of phases according the interfacial temperature approximated by the saturation temperature.
#include <ThermalPhaseChangePhaseSystem.H>
Public Member Functions
ThermalPhaseChangePhaseSystem (const fvMesh &)
virtual ~ThermalPhaseChangePhaseSystem ()
const saturationModel & saturation () const
virtual tmp< volScalarField > dmdt (const phasePairKey &key) const
virtual PtrList< volScalarField > dmdts () const
virtual autoPtr< phaseSystem::heatTransferTable > heatTransfer () const
virtual autoPtr< phaseSystem::massTransferTable > massTransfer () const
virtual void correctInterfaceThermo ()
virtual bool read ()
Protected Types
typedef HashPtrTable< volScalarField, phasePairKey, phasePairKey::hash > iDmdtTable
typedef HashPtrTable< volScalarField, phasePairKey, phasePairKey::hash > wDmdtTable
typedef HashPtrTable< volScalarField, phasePairKey, phasePairKey::hash > wMDotLTable
Protected Member Functions
tmp< volScalarField > iDmdt (const phasePairKey &key) const
tmp< volScalarField > wDmdt (const phasePairKey &key) const
Protected Attributes
word volatile_
autoPtr< saturationModel > saturationModel_
Switch phaseChange_
iDmdtTable iDmdt_
wDmdtTable wDmdt_
wMDotLTable wMDotL_
Detailed Description
template<class BasePhaseSystem>
class Foam::ThermalPhaseChangePhaseSystem< BasePhaseSystem >
Class to provide interfacial heat and mass transfer between a number of phases according the interfacial temperature approximated by the saturation temperature.
Source files
ThermalPhaseChangePhaseSystem.H
ThermalPhaseChangePhaseSystem.C
Definition at line 51 of file ThermalPhaseChangePhaseSystem.H.
Member Typedef Documentation
iDmdtTable
template<class BasePhaseSystem > typedef HashPtrTable<volScalarField, phasePairKey, phasePairKey::hash> iDmdtTable protected
Definition at line 61 of file ThermalPhaseChangePhaseSystem.H.
wDmdtTable
template<class BasePhaseSystem > typedef HashPtrTable<volScalarField, phasePairKey, phasePairKey::hash> wDmdtTable protected
Definition at line 64 of file ThermalPhaseChangePhaseSystem.H.
wMDotLTable
template<class BasePhaseSystem > typedef HashPtrTable<volScalarField, phasePairKey, phasePairKey::hash> wMDotLTable protected
Definition at line 67 of file ThermalPhaseChangePhaseSystem.H.
Constructor & Destructor Documentation
ThermalPhaseChangePhaseSystem()
template<class BasePhaseSystem > ThermalPhaseChangePhaseSystem (const fvMesh & mesh)
Definition at line 68 of file ThermalPhaseChangePhaseSystem.C.
References IOobjectOption::AUTO_WRITE, Foam::dimDensity, Foam::dimEnergy, Foam::dimTime, Foam::dimVolume, forAllConstIter, IOobject::groupName(), ThermalPhaseChangePhaseSystem< BasePhaseSystem >::iDmdt_, phasePair::name(), phasePairKey::ordered(), IOobjectOption::READ_IF_PRESENT, HashPtrTable< T, Key, Hash >::set(), ThermalPhaseChangePhaseSystem< BasePhaseSystem >::wDmdt_, and ThermalPhaseChangePhaseSystem< BasePhaseSystem >::wMDotL_.
~ThermalPhaseChangePhaseSystem()
template<class BasePhaseSystem > ~ThermalPhaseChangePhaseSystem () virtual
Definition at line 160 of file ThermalPhaseChangePhaseSystem.C.
Member Function Documentation
iDmdt()
template<class BasePhaseSystem > Foam::tmp< Foam::volScalarField > iDmdt (const phasePairKey & key) const protected
Definition at line 31 of file ThermalPhaseChangePhaseSystem.C.
References phaseSystem::dmdt(), and PtrList< T >::PtrList().
wDmdt()
template<class BasePhaseSystem > Foam::tmp< Foam::volScalarField > wDmdt (const phasePairKey & key) const protected
Definition at line 49 of file ThermalPhaseChangePhaseSystem.C.
References phaseSystem::dmdt().
saturation()
template<class BasePhaseSystem > const Foam::saturationModel & saturation () const
Definition at line 169 of file ThermalPhaseChangePhaseSystem.C.
dmdt()
template<class BasePhaseSystem > Foam::tmp< Foam::volScalarField > dmdt (const phasePairKey & key) const virtual
Definition at line 177 of file ThermalPhaseChangePhaseSystem.C.
dmdts()
template<class BasePhaseSystem > Foam::PtrList< Foam::volScalarField > dmdts () const virtual
Definition at line 188 of file ThermalPhaseChangePhaseSystem.C.
References forAllConstIter, phasePair::phase1(), and phasePair::phase2().
heatTransfer()
template<class BasePhaseSystem > Foam::autoPtr< Foam::phaseSystem::heatTransferTable > heatTransfer () const virtual
Definition at line 216 of file ThermalPhaseChangePhaseSystem.C.
References forAllConstIter, phaseModel::name(), Foam::negPart(), phasePairKey::ordered(), phase1, phasePair::phase1(), phase2, phasePair::phase2(), Foam::posPart(), and phaseModel::thermo().
massTransfer()
template<class BasePhaseSystem > Foam::autoPtr< Foam::phaseSystem::massTransferTable > massTransfer () const virtual
Definition at line 278 of file ThermalPhaseChangePhaseSystem.C.
References forAll, forAllConstIter, IOobject::groupName(), phase::name(), phaseModel::name(), Foam::name(), phasePairKey::ordered(), phasePair::phase1(), and phasePair::phase2().
correctInterfaceThermo()
template<class BasePhaseSystem > void correctInterfaceThermo () virtual
Definition at line 337 of file ThermalPhaseChangePhaseSystem.C.
References fvMesh::boundary(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), GeometricField< Type, PatchField, GeoMesh >::clamp_min(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::fvc::domainIntegrate(), Foam::endl(), forAll, forAllConstIter, Foam::gAverage(), Foam::gMax(), Foam::gMin(), he2, Foam::Info, L, IOobject::member(), mesh, DimensionedField< Type, GeoMesh >::mesh(), phase::name(), phaseModel::name(), phasePair::name(), Foam::neg(), Foam::neg0(), phaseModel::otherPhase(), p, patches, phase1, phasePair::phase1(), phase2, phasePair::phase2(), Foam::pos(), Foam::pos0(), GeometricField< Type, PatchField, GeoMesh >::primitiveField(), phaseModel::rho(), Foam::sign(), and phaseModel::thermo().
read()
template<class BasePhaseSystem > bool read () virtual
Definition at line 533 of file ThermalPhaseChangePhaseSystem.C.
Member Data Documentation
volatile_
template<class BasePhaseSystem > word volatile_ protected
Definition at line 73 of file ThermalPhaseChangePhaseSystem.H.
saturationModel_
template<class BasePhaseSystem > autoPtr<saturationModel> saturationModel_ protected
Definition at line 76 of file ThermalPhaseChangePhaseSystem.H.
phaseChange_
template<class BasePhaseSystem > Switch phaseChange_ protected
Definition at line 79 of file ThermalPhaseChangePhaseSystem.H.
iDmdt_
template<class BasePhaseSystem > iDmdtTable iDmdt_ protected
Definition at line 82 of file ThermalPhaseChangePhaseSystem.H.
Referenced by ThermalPhaseChangePhaseSystem< BasePhaseSystem >::ThermalPhaseChangePhaseSystem().
wDmdt_
template<class BasePhaseSystem > wDmdtTable wDmdt_ protected
Definition at line 85 of file ThermalPhaseChangePhaseSystem.H.
Referenced by ThermalPhaseChangePhaseSystem< BasePhaseSystem >::ThermalPhaseChangePhaseSystem().
wMDotL_
template<class BasePhaseSystem > wMDotLTable wMDotL_ protected
Definition at line 88 of file ThermalPhaseChangePhaseSystem.H.
Referenced by ThermalPhaseChangePhaseSystem< BasePhaseSystem >::ThermalPhaseChangePhaseSystem().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/PhaseSystems/ThermalPhaseChangePhaseSystem/ThermalPhaseChangePhaseSystem.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/PhaseSystems/ThermalPhaseChangePhaseSystem/ThermalPhaseChangePhaseSystem.C