OpenFOAM: laplacianScheme< Type > Class Template Reference
laplacianScheme< Type > Class Template Reference abstract
Abstract base class for finite area calculus laplacian schemes.
#include <faLaplacianScheme.H>
Public Member Functions
declareRunTimeSelectionTable (tmp, laplacianScheme, Istream,(const faMesh &mesh, Istream &schemeData),(mesh, schemeData))
laplacianScheme (const faMesh &mesh)
laplacianScheme (const faMesh &mesh, Istream &is)
virtual ~laplacianScheme ()
const faMesh & mesh () const
virtual tmp< faMatrix< Type > > famLaplacian (const edgeScalarField &, const GeometricField< Type, faPatchField, areaMesh > &)=0
virtual tmp< faMatrix< Type > > famLaplacian (const areaScalarField &, const GeometricField< Type, faPatchField, areaMesh > &)
virtual tmp< GeometricField< Type, faPatchField, areaMesh > > facLaplacian (const GeometricField< Type, faPatchField, areaMesh > &)=0
virtual tmp< GeometricField< Type, faPatchField, areaMesh > > facLaplacian (const edgeScalarField &, const GeometricField< Type, faPatchField, areaMesh > &)=0
virtual tmp< GeometricField< Type, faPatchField, areaMesh > > facLaplacian (const areaScalarField &, const GeometricField< Type, faPatchField, areaMesh > &)
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Static Public Member Functions
static tmp< laplacianScheme< Type > > New (const faMesh &mesh, Istream &schemeData)
Protected Member Functions
laplacianScheme (const laplacianScheme &)=delete
void operator= (const laplacianScheme &)=delete
Protected Attributes
const faMesh & mesh_
tmp< edgeInterpolationScheme< scalar > > tinterpGammaScheme_
tmp< lnGradScheme< Type > > tlnGradScheme_
Detailed Description
template<class Type>
class Foam::fa::laplacianScheme< Type >
Abstract base class for finite area calculus laplacian schemes.
Source files
faLaplacianScheme.H
faLaplacianScheme.C
faLaplacianSchemes.C
Definition at line 64 of file faLaplacianScheme.H.
Constructor & Destructor Documentation
laplacianScheme() [1/3]
template<class Type > laplacianScheme (const laplacianScheme< Type > &) protected delete
laplacianScheme() [2/3]
template<class Type > laplacianScheme (const faMesh & mesh) inline
Definition at line 104 of file faLaplacianScheme.H.
laplacianScheme() [3/3]
template<class Type > laplacianScheme (const faMesh & mesh, Istream & is) inline
Definition at line 112 of file faLaplacianScheme.H.
References laplacianScheme< Type >::mesh(), lnGradScheme< Type >::New(), edgeInterpolationScheme< Type >::New(), laplacianScheme< Type >::tinterpGammaScheme_, and laplacianScheme< Type >::tlnGradScheme_.
~laplacianScheme()
template<class Type > ~laplacianScheme () virtual
Definition at line 83 of file faLaplacianScheme.C.
Member Function Documentation
operator=()
template<class Type > void operator= (const laplacianScheme< Type > &) protected delete
declareRunTimeSelectionTable()
template<class Type > declareRunTimeSelectionTable (tmp , laplacianScheme< Type > , Istream , (const faMesh &mesh, Istream &schemeData) , (mesh, schemeData))
New()
template<class Type > tmp< laplacianScheme< Type > > New (const faMesh & mesh, Istream & schemeData) static
Definition at line 39 of file faLaplacianScheme.C.
References Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, FatalIOErrorInLookup, InfoInFunction, mesh, and Foam::nl.
Referenced by Foam::fac::laplacian(), Foam::fam::laplacian(), and Foam::fac::laplacian().
mesh()
template<class Type > const faMesh & mesh () const inline
Definition at line 162 of file faLaplacianScheme.H.
References laplacianScheme< Type >::mesh_.
Referenced by laplacianScheme< Type >::laplacianScheme().
famLaplacian() [1/2]
template<class Type > virtual tmp< faMatrix< Type > > famLaplacian (const edgeScalarField & , const GeometricField< Type, faPatchField, areaMesh > &) pure virtual
Implemented in gaussLaplacianScheme< Type >.
famLaplacian() [2/2]
template<class Type > tmp< faMatrix< Type > > famLaplacian (const areaScalarField & gamma, const GeometricField< Type, faPatchField, areaMesh > & vf) virtual
Definition at line 91 of file faLaplacianScheme.C.
References gamma, and Foam::interpolate().
facLaplacian() [1/3]
template<class Type > virtual tmp< GeometricField< Type, faPatchField, areaMesh > > facLaplacian (const GeometricField< Type, faPatchField, areaMesh > &) pure virtual
Implemented in gaussLaplacianScheme< Type >.
facLaplacian() [2/3]
template<class Type > virtual tmp< GeometricField< Type, faPatchField, areaMesh > > facLaplacian (const edgeScalarField & , const GeometricField< Type, faPatchField, areaMesh > &) pure virtual
Implemented in gaussLaplacianScheme< Type >.
facLaplacian() [3/3]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > facLaplacian (const areaScalarField & gamma, const GeometricField< Type, faPatchField, areaMesh > & vf) virtual
Definition at line 103 of file faLaplacianScheme.C.
References gamma, and Foam::interpolate().
Member Data Documentation
mesh_
template<class Type > const faMesh& mesh_ protected
Definition at line 73 of file faLaplacianScheme.H.
Referenced by laplacianScheme< Type >::mesh().
tinterpGammaScheme_
template<class Type > tmp<edgeInterpolationScheme<scalar> > tinterpGammaScheme_ protected
Definition at line 74 of file faLaplacianScheme.H.
Referenced by laplacianScheme< Type >::laplacianScheme().
tlnGradScheme_
template<class Type > tmp<lnGradScheme<Type> > tlnGradScheme_ protected
Definition at line 75 of file faLaplacianScheme.H.
Referenced by laplacianScheme< Type >::laplacianScheme().
The documentation for this class was generated from the following files:
src/finiteArea/finiteArea/laplacianSchemes/faLaplacianScheme/faLaplacianScheme.H
src/finiteArea/finiteArea/laplacianSchemes/faLaplacianScheme/faLaplacianScheme.C