OpenFOAM: option Class Reference
option Class Reference
Base abstract class for handling finite volume options (i.e. fvOption).
#include <fvOption.H>
Classes
class iNew
Public Member Functions
TypeName ("option")
declareRunTimeSelectionTable (autoPtr, option, dictionary,(const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh),(name, modelType, dict, mesh))
option (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
autoPtr< option > clone () const
virtual ~option ()=default
const word & name () const noexcept
const fvMesh & mesh () const noexcept
const dictionary & coeffs () const noexcept
bool active () const noexcept
void setApplied (const label fieldi)
bool active (const bool on) noexcept
virtual bool isActive ()
virtual label applyToField (const word &fieldName) const
virtual void checkApplied () const
virtual void addSup (fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (fvMatrix< vector > &eqn, const label fieldi)
virtual void addSup (fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (fvMatrix< tensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< scalar > &eqn, const label fieldi)
virtual void constrain (fvMatrix< vector > &eqn, const label fieldi)
virtual void constrain (fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< tensor > &eqn, const label fieldi)
virtual void correct (volScalarField &field)
virtual void correct (volVectorField &field)
virtual void correct (volSphericalTensorField &field)
virtual void correct (volSymmTensorField &field)
virtual void correct (volTensorField &field)
virtual void postProcessSens (scalarField &sensField, const word &fieldName=word::null, const word &designVariablesName=word::null)
virtual void postProcessSens (vectorField &sensField, const word &fieldName=word::null, const word &designVariablesName=word::null)
virtual void postProcessSens (tensorField &sensField, const word &fieldName=word::null, const word &designVariablesName=word::null)
virtual void writeHeader (Ostream &) const
virtual void writeFooter (Ostream &) const
virtual void writeData (Ostream &) const
virtual bool read (const dictionary &dict)
Static Public Member Functions
static autoPtr< option > New (const word &name, const dictionary &dict, const fvMesh &mesh)
Public Attributes
bool log
Protected Member Functions
void resetApplied ()
Protected Attributes
const word name_
const word modelType_
const fvMesh & mesh_
dictionary dict_
dictionary coeffs_
wordList fieldNames_
List< bool > applied_
bool active_
Detailed Description
Base abstract class for handling finite volume options (i.e. fvOption).
Usage
Minimal example by using constant/fvOptions:
<userDefinedName1>
{
    // Mandatory entries (unmodifiable)
    type              <fvOptionName>;
    // Optional entries (unmodifiable/runtime modifiable)
    <fvOption>Coeffs
    {
        // subdictionary entries
    }
    // Optional entries (runtime modifiable)
    active            true;
    log               true;
}
where the entries mean:
Property Description Type Reqd Dflt
type Name of operand fvOption word yes -
<fvOption>Coeffs
Dictionary containing settings of
the selected fvOption settings
dictionary no -
active Flag to (de)activate fvOption bool no true
log Flag to log fvOption-related info bool no true
Source files
fvOption.H
fvOption.C
fvOptionIO.C
Definition at line 122 of file fvOption.H.
Constructor & Destructor Documentation
option()
option (const word & name, const word & modelType, const dictionary & dict, const fvMesh & mesh)
Definition at line 50 of file fvOption.C.
References Foam::decrIndent(), Foam::endl(), Foam::incrIndent(), Foam::indent(), Log, and option::name_.
~option()
virtual ~option () virtual default
Member Function Documentation
resetApplied()
void resetApplied () protected
Definition at line 41 of file fvOption.C.
References option::applied_, option::fieldNames_, List< T >::resize_nocopy(), and UList< T >::size().
Referenced by atmNutSource::atmNutSource(), atmPlantCanopyTSource::atmPlantCanopyTSource(), atmPlantCanopyTurbSource::atmPlantCanopyTurbSource(), atmPlantCanopyUSource::atmPlantCanopyUSource(), buoyancyEnergy::buoyancyEnergy(), buoyancyForce::buoyancyForce(), directionalPressureGradientExplicitSource::directionalPressureGradientExplicitSource(), fanMomentumSource::fanMomentumSource(), fixedTemperatureConstraint::fixedTemperatureConstraint(), heatExchangerSource::heatExchangerSource(), interRegionExplicitPorositySource::interRegionExplicitPorositySource(), interRegionHeatTransferModel::interRegionHeatTransferModel(), jouleHeatingSource::jouleHeatingSource(), meanVelocityForce::meanVelocityForce(), multiphaseStabilizedTurbulence::multiphaseStabilizedTurbulence(), patchCellsSource::patchCellsSource(), PhaseLimitStabilization< Type >::PhaseLimitStabilization(), radiation::radiation(), velocityDampingConstraint::read(), FixedValueConstraint< Type >::read(), limitTemperature::read(), limitTurbulenceViscosity::read(), limitVelocity::read(), acousticDampingSource::read(), explicitPorositySource::read(), rotorDiskSource::read(), CodedSource< Type >::read(), multiphaseMangrovesSource::read(), multiphaseMangrovesTurbulenceModel::read(), solidificationMeltingSource::solidificationMeltingSource(), tabulatedAccelerationSource::tabulatedAccelerationSource(), and viscousDissipation::viscousDissipation().
TypeName()
TypeName ("option")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , option , dictionary , (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh) , (name, modelType, dict, mesh))
clone()
autoPtr< option > clone () const inline
Definition at line 198 of file fvOption.H.
References NotImplemented.
New()
Foam::autoPtr< Foam::fv::option > New (const word & name, const dictionary & dict, const fvMesh & mesh) static
Definition at line 74 of file fvOption.C.
References Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), Foam::indent(), Foam::Info, mesh, and Foam::name().
Referenced by option::iNew::operator()(), CodedSource< Type >::redirectOption(), and optionList::reset().
name()
const Foam::word & name () const inline noexcept
Definition at line 24 of file fvOptionI.H.
References option::name_.
Referenced by directionalPressureGradientExplicitSource::directionalPressureGradientExplicitSource(), fanMomentumSource::fanMomentumSource(), and interRegionHeatTransferModel::setNbrModel().
mesh()
const Foam::fvMesh & mesh () const inline noexcept
Definition at line 30 of file fvOptionI.H.
Referenced by tabulatedAccelerationSource::tabulatedAccelerationSource().
coeffs()
const Foam::dictionary & coeffs () const inline noexcept
Definition at line 36 of file fvOptionI.H.
active() [1/2]
bool active () const inline noexcept
Definition at line 42 of file fvOptionI.H.
Referenced by constantHeatTransfer::constantHeatTransfer(), interRegionHeatTransferModel::interRegionHeatTransferModel(), and interRegionOption::interRegionOption().
setApplied()
void setApplied (const label fieldi) inline
Definition at line 56 of file fvOptionI.H.
active() [2/2]
bool active (const bool on) inline noexcept
Definition at line 48 of file fvOptionI.H.
isActive()
bool isActive () virtual
Reimplemented in cellSetOption.
Definition at line 112 of file fvOption.C.
Referenced by fanMomentumSource::fanMomentumSource(), and cellSetOption::isActive().
applyToField()
Foam::label applyToField (const word & fieldName) const virtual
Definition at line 118 of file fvOption.C.
checkApplied()
void checkApplied () const virtual
Definition at line 124 of file fvOption.C.
References Foam::endl(), forAll, and WarningInFunction.
addSup() [1/15]
void addSup (fvMatrix< scalar > & eqn, const label fieldi) virtual
Reimplemented in VoFSolidificationMeltingSource, atmAmbientTurbSource, atmBuoyancyTurbSource, atmLengthScaleTurbSource, atmPlantCanopyTSource, atmPlantCanopyTurbSource, buoyancyTurbSource, heatExchangerSource, multiphaseStabilizedTurbulence, solidificationMeltingSource, interRegionHeatTransferModel, and multiphaseMangrovesTurbulenceModel.
Definition at line 138 of file fvOption.C.
addSup() [2/15]
void addSup (fvMatrix< vector > & eqn, const label fieldi) virtual
Reimplemented in VoFSolidificationMeltingSource, atmCoriolisUSource, atmPlantCanopyUSource, acousticDampingSource, actuationDiskSource, buoyancyForce, directionalPressureGradientExplicitSource, explicitPorositySource, fanMomentumSource, meanVelocityForce, radialActuationDiskSource, rotorDiskSource, solidificationMeltingSource, tabulatedAccelerationSource, interRegionExplicitPorositySource, and multiphaseMangrovesSource.
Definition at line 146 of file fvOption.C.
addSup() [3/15]
void addSup (fvMatrix< symmTensor > & eqn, const label fieldi) virtual
Definition at line 162 of file fvOption.C.
addSup() [4/15]
void addSup (fvMatrix< sphericalTensor > & eqn, const label fieldi) virtual
Definition at line 154 of file fvOption.C.
addSup() [5/15]
void addSup (fvMatrix< tensor > & eqn, const label fieldi) virtual
Definition at line 170 of file fvOption.C.
addSup() [6/15]
void addSup (const volScalarField & rho, fvMatrix< scalar > & eqn, const label fieldi) virtual
Reimplemented in VoFSolidificationMeltingSource, atmAmbientTurbSource, atmBuoyancyTurbSource, atmLengthScaleTurbSource, atmPlantCanopyTSource, atmPlantCanopyTurbSource, buoyancyEnergy, buoyancyTurbSource, heatExchangerSource, jouleHeatingSource, multiphaseStabilizedTurbulence, patchCellsSource, solidificationMeltingSource, viscousDissipation, interRegionHeatTransferModel, radiation, and multiphaseMangrovesTurbulenceModel.
Definition at line 178 of file fvOption.C.
addSup() [7/15]
void addSup (const volScalarField & rho, fvMatrix< vector > & eqn, const label fieldi) virtual
Reimplemented in VoFSolidificationMeltingSource, atmCoriolisUSource, atmPlantCanopyUSource, acousticDampingSource, actuationDiskSource, buoyancyForce, directionalPressureGradientExplicitSource, explicitPorositySource, fanMomentumSource, meanVelocityForce, radialActuationDiskSource, rotorDiskSource, solidificationMeltingSource, tabulatedAccelerationSource, interRegionExplicitPorositySource, and multiphaseMangrovesSource.
Definition at line 187 of file fvOption.C.
addSup() [8/15]
void addSup (const volScalarField & rho, fvMatrix< symmTensor > & eqn, const label fieldi) virtual
Definition at line 205 of file fvOption.C.
addSup() [9/15]
void addSup (const volScalarField & rho, fvMatrix< sphericalTensor > & eqn, const label fieldi) virtual
Definition at line 196 of file fvOption.C.
addSup() [10/15]
void addSup (const volScalarField & rho, fvMatrix< tensor > & eqn, const label fieldi) virtual
Definition at line 214 of file fvOption.C.
addSup() [11/15]
void addSup (const volScalarField & alpha, const volScalarField & rho, fvMatrix< scalar > & eqn, const label fieldi) virtual
Reimplemented in atmAmbientTurbSource, atmBuoyancyTurbSource, atmLengthScaleTurbSource, atmPlantCanopyTSource, atmPlantCanopyTurbSource, and buoyancyTurbSource.
Definition at line 223 of file fvOption.C.
References alpha, and rho.
addSup() [12/15]
void addSup (const volScalarField & alpha, const volScalarField & rho, fvMatrix< vector > & eqn, const label fieldi) virtual
Reimplemented in atmCoriolisUSource, atmPlantCanopyUSource, acousticDampingSource, actuationDiskSource, and explicitPorositySource.
Definition at line 235 of file fvOption.C.
References alpha, and rho.
addSup() [13/15]
void addSup (const volScalarField & alpha, const volScalarField & rho, fvMatrix< symmTensor > & eqn, const label fieldi) virtual
Definition at line 259 of file fvOption.C.
References alpha, and rho.
addSup() [14/15]
void addSup (const volScalarField & alpha, const volScalarField & rho, fvMatrix< sphericalTensor > & eqn, const label fieldi) virtual
Definition at line 247 of file fvOption.C.
References alpha, and rho.
addSup() [15/15]
void addSup (const volScalarField & alpha, const volScalarField & rho, fvMatrix< tensor > & eqn, const label fieldi) virtual
Definition at line 271 of file fvOption.C.
References alpha, and rho.
constrain() [1/5]
void constrain (fvMatrix< scalar > & eqn, const label fieldi) virtual
Reimplemented in fixedTemperatureConstraint.
Definition at line 283 of file fvOption.C.
constrain() [2/5]
void constrain (fvMatrix< vector > & eqn, const label fieldi) virtual
Reimplemented in velocityDampingConstraint, directionalPressureGradientExplicitSource, and meanVelocityForce.
Definition at line 287 of file fvOption.C.
constrain() [3/5]
void constrain (fvMatrix< sphericalTensor > & eqn, const label fieldi) virtual
Definition at line 291 of file fvOption.C.
constrain() [4/5]
void constrain (fvMatrix< symmTensor > & eqn, const label fieldi) virtual
Definition at line 299 of file fvOption.C.
constrain() [5/5]
void constrain (fvMatrix< tensor > & eqn, const label fieldi) virtual
Definition at line 307 of file fvOption.C.
correct() [1/5]
void correct (volScalarField & field) virtual
Reimplemented in atmNutSource, multiphaseStabilizedTurbulence, limitTemperature, and limitTurbulenceViscosity.
Definition at line 311 of file fvOption.C.
correct() [2/5]
void correct (volVectorField & field) virtual
Reimplemented in limitVelocity, directionalPressureGradientExplicitSource, and meanVelocityForce.
Definition at line 315 of file fvOption.C.
correct() [3/5]
void correct (volSphericalTensorField & field) virtual
Definition at line 319 of file fvOption.C.
correct() [4/5]
void correct (volSymmTensorField & field) virtual
Definition at line 323 of file fvOption.C.
correct() [5/5]
void correct (volTensorField & field) virtual
Definition at line 327 of file fvOption.C.
postProcessSens() [1/3]
void postProcessSens (scalarField & sensField, const word & fieldName = word::null, const word & designVariablesName = word::null) virtual
Definition at line 331 of file fvOption.C.
postProcessSens() [2/3]
void postProcessSens (vectorField & sensField, const word & fieldName = word::null, const word & designVariablesName = word::null) virtual
Definition at line 340 of file fvOption.C.
postProcessSens() [3/3]
void postProcessSens (tensorField & sensField, const word & fieldName = word::null, const word & designVariablesName = word::null) virtual
Definition at line 349 of file fvOption.C.
writeHeader()
void writeHeader (Ostream & os) const virtual
Definition at line 26 of file fvOptionIO.C.
References option::name_, and os().
writeFooter()
void writeFooter (Ostream & os) const virtual
Definition at line 32 of file fvOptionIO.C.
References os().
writeData()
void writeData (Ostream & os) const virtual
Reimplemented in velocityDampingConstraint, and directionalPressureGradientExplicitSource.
Definition at line 38 of file fvOptionIO.C.
References Foam::nl, os(), and Foam::type().
read()
bool read (const dictionary & dict) virtual
Reimplemented in VoFSolidificationMeltingSource, atmAmbientTurbSource, atmBuoyancyTurbSource, atmCoriolisUSource, atmLengthScaleTurbSource, atmNutSource, atmPlantCanopyTSource, atmPlantCanopyTurbSource, atmPlantCanopyUSource, cellSetOption, fixedTemperatureConstraint, velocityDampingConstraint, FixedValueConstraint< Type >, limitTemperature, limitTurbulenceViscosity, limitVelocity, interRegionOption, acousticDampingSource, actuationDiskSource, buoyancyEnergy, buoyancyForce, buoyancyTurbSource, directionalPressureGradientExplicitSource, explicitPorositySource, fanMomentumSource, heatExchangerSource, jouleHeatingSource, meanVelocityForce, multiphaseStabilizedTurbulence, patchCellsSource, PhaseLimitStabilization< Type >, radialActuationDiskSource, rotorDiskSource, solidificationMeltingSource, tabulatedAccelerationSource, viscousDissipation, CodedSource< Type >, SemiImplicitSource< Type >, interRegionExplicitPorositySource, constantHeatTransfer, interRegionHeatTransferModel, tabulatedHeatTransfer, tabulatedNTUHeatTransfer, variableHeatTransfer, radiation, multiphaseMangrovesSource, and multiphaseMangrovesTurbulenceModel.
Definition at line 48 of file fvOptionIO.C.
References dict, dimensioned< Type >::getOrDefault(), and Foam::log().
Referenced by cellSetOption::read(), interRegionOption::read(), buoyancyEnergy::read(), jouleHeatingSource::read(), patchCellsSource::read(), PhaseLimitStabilization< Type >::read(), tabulatedAccelerationSource::read(), tabulatedNTUHeatTransfer::read(), radiation::read(), multiphaseMangrovesSource::read(), and multiphaseMangrovesTurbulenceModel::read().
Member Data Documentation
name_
const word name_ protected
Definition at line 129 of file fvOption.H.
Referenced by velocityDampingConstraint::addDamping(), directionalPressureGradientExplicitSource::directionalPressureGradientExplicitSource(), explicitPorositySource::explicitPorositySource(), fanMomentumSource::fanMomentumSource(), interRegionExplicitPorositySource::initialise(), meanVelocityForce::meanVelocityForce(), option::name(), option::option(), radialActuationDiskSource::radialActuationDiskSource(), option::writeHeader(), and meanVelocityForce::writeProps().
modelType_
const word modelType_ protected
Definition at line 132 of file fvOption.H.
mesh_
const fvMesh& mesh_ protected
Definition at line 135 of file fvOption.H.
Referenced by velocityDampingConstraint::addDamping(), atmNutSource::atmNutSource(), atmPlantCanopyTurbSource::atmPlantCanopyTurbSource(), rotorDiskSource::calculate(), constantHeatTransfer::constantHeatTransfer(), directionalPressureGradientExplicitSource::directionalPressureGradientExplicitSource(), multiphaseMangrovesSource::dragCoeff(), explicitPorositySource::explicitPorositySource(), fanMomentumSource::fanMomentumSource(), fixedTemperatureConstraint::fixedTemperatureConstraint(), heatExchangerSource::heatExchangerSource(), interRegionExplicitPorositySource::initialise(), jouleHeatingSource::jouleHeatingSource(), multiphaseMangrovesTurbulenceModel::kCoeff(), meanVelocityForce::meanVelocityForce(), multiphaseStabilizedTurbulence::multiphaseStabilizedTurbulence(), radiation::radiation(), acousticDampingSource::setBlendingFactor(), interRegionOption::setMapper(), interRegionHeatTransferModel::setNbrModel(), solidificationMeltingSource::solidificationMeltingSource(), variableHeatTransfer::variableHeatTransfer(), viscousDissipation::viscousDissipation(), and meanVelocityForce::writeProps().
dict_
dictionary dict_ protected
Definition at line 138 of file fvOption.H.
coeffs_
dictionary coeffs_ protected
Definition at line 141 of file fvOption.H.
Referenced by buoyancyEnergy::buoyancyEnergy(), buoyancyForce::buoyancyForce(), cellSetOption::cellSetOption(), rotorDiskSource::checkData(), directionalPressureGradientExplicitSource::directionalPressureGradientExplicitSource(), explicitPorositySource::explicitPorositySource(), fanMomentumSource::fanMomentumSource(), fixedTemperatureConstraint::fixedTemperatureConstraint(), interRegionExplicitPorositySource::initialise(), interRegionHeatTransferModel::interRegionHeatTransferModel(), meanVelocityForce::meanVelocityForce(), patchCellsSource::patchCellsSource(), interRegionOption::setMapper(), variableHeatTransfer::variableHeatTransfer(), and viscousDissipation::viscousDissipation().
fieldNames_
wordList fieldNames_ protected
Definition at line 144 of file fvOption.H.
Referenced by atmNutSource::atmNutSource(), atmPlantCanopyTSource::atmPlantCanopyTSource(), atmPlantCanopyTurbSource::atmPlantCanopyTurbSource(), atmPlantCanopyUSource::atmPlantCanopyUSource(), buoyancyEnergy::buoyancyEnergy(), buoyancyForce::buoyancyForce(), directionalPressureGradientExplicitSource::directionalPressureGradientExplicitSource(), fanMomentumSource::fanMomentumSource(), fixedTemperatureConstraint::fixedTemperatureConstraint(), heatExchangerSource::heatExchangerSource(), interRegionExplicitPorositySource::interRegionExplicitPorositySource(), interRegionHeatTransferModel::interRegionHeatTransferModel(), jouleHeatingSource::jouleHeatingSource(), meanVelocityForce::meanVelocityForce(), multiphaseStabilizedTurbulence::multiphaseStabilizedTurbulence(), patchCellsSource::patchCellsSource(), PhaseLimitStabilization< Type >::PhaseLimitStabilization(), radiation::radiation(), option::resetApplied(), solidificationMeltingSource::solidificationMeltingSource(), tabulatedAccelerationSource::tabulatedAccelerationSource(), and viscousDissipation::viscousDissipation().
applied_
List<bool> applied_ protected
Definition at line 147 of file fvOption.H.
Referenced by option::resetApplied().
active_
bool active_ protected
Definition at line 150 of file fvOption.H.
Referenced by interRegionExplicitPorositySource::interRegionExplicitPorositySource().
log
bool log
Definition at line 162 of file fvOption.H.
The documentation for this class was generated from the following files:
src/finiteVolume/cfdTools/general/fvOptions/fvOption.H
src/finiteVolume/cfdTools/general/fvOptions/fvOption.C
src/finiteVolume/cfdTools/general/fvOptions/fvOptionI.H
src/finiteVolume/cfdTools/general/fvOptions/fvOptionIO.C