OpenFOAM: TolubinskiKostanchuk Class Reference
TolubinskiKostanchuk Class Reference
A correlation for bubble departure diameter modelling based on Tolubinski-Kostanchuk (1970) for boiling flows.
#include <TolubinskiKostanchuk.H>
Public Member Functions
TypeName ("TolubinskiKostanchuk")
TolubinskiKostanchuk (const dictionary &dict)
virtual ~TolubinskiKostanchuk ()=default
virtual tmp< scalarField > dDeparture (const phaseModel &liquid, const phaseModel &vapor, const label patchi, const scalarField &Tl, const scalarField &Tsatw, const scalarField &L) const
virtual void write (Ostream &os) const
Public Member Functions inherited from departureDiameterModel
TypeName ("departureDiameterModel")
declareRunTimeSelectionTable (autoPtr, departureDiameterModel, dictionary,(const dictionary &dict),(dict))
departureDiameterModel ()=default
virtual ~departureDiameterModel ()=default
Additional Inherited Members
Static Public Member Functions inherited from departureDiameterModel
static autoPtr< departureDiameterModel > New (const dictionary &dict)
Detailed Description
A correlation for bubble departure diameter modelling based on Tolubinski-Kostanchuk (1970) for boiling flows.
Reference:
    Tolubinsky, V. I., & Kostanchuk, D. M. (1970).
    Vapour bubbles growth rate and heat transfer
    intensity at subcooled water boiling.
    In International Heat Transfer Conference 4 (Vol. 23). Begel House Inc..
Usage
Example of the model specification:
departureDiameterModel
{
    // Mandatory entries
    type            TolubinskiKostanchuk;
    // Optional entries
    dRef            <scalar>;
    dMax            <scalar>;
    dMin            <scalar>;
}
where the entries mean:
Property Description Type Reqd Deflt
type Type name: TolubinskiKostanchuk word yes -
dRef Coefficient of the temperature term scalar no 6e-4
dMax Maximum diameter scalar no 0.0014
dMin Minimum diameter scalar no 1e-6
Source files
TolubinskiKostanchuk.H
TolubinskiKostanchuk.C
Definition at line 114 of file TolubinskiKostanchuk.H.
Constructor & Destructor Documentation
TolubinskiKostanchuk()
TolubinskiKostanchuk (const dictionary & dict)
Definition at line 47 of file TolubinskiKostanchuk.C.
~TolubinskiKostanchuk()
virtual ~TolubinskiKostanchuk () virtual default
Member Function Documentation
TypeName()
TypeName ("TolubinskiKostanchuk")
dDeparture()
Foam::tmp< Foam::scalarField > dDeparture (const phaseModel & liquid, const phaseModel & vapor, const label patchi, const scalarField & Tl, const scalarField & Tsatw, const scalarField & L) const virtual
Implements departureDiameterModel.
Definition at line 63 of file TolubinskiKostanchuk.C.
References Foam::clamp(), and Foam::exp().
write()
void write (Ostream & os) const virtual
Reimplemented from departureDiameterModel.
Definition at line 82 of file TolubinskiKostanchuk.C.
References os(), and departureDiameterModel::write().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/wallBoilingSubModels/departureDiameterModels/TolubinskiKostanchuk/TolubinskiKostanchuk.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/wallBoilingSubModels/departureDiameterModels/TolubinskiKostanchuk/TolubinskiKostanchuk.C