OpenFOAM: ensightPart Class Reference
ensightPart Class Reference
Base class for ensightCells, ensightFaces, ensightOutputSurfaces.
#include <ensightPart.H>
Public Member Functions
TypeNameNoDebug ("ensightPart")
ensightPart ()
ensightPart (const string &description)
virtual ~ensightPart ()=default
label index () const noexcept
label & index () noexcept
label identifier () const noexcept
label & identifier () noexcept
bool empty () const noexcept
label size () const noexcept
const string & name () const noexcept
void rename (const string &value)
void rename (string &&value)
virtual void writeDict (Ostream &os, const bool full=false) const
label operator[] (const label i) const
Protected Member Functions
const labelList & addressing () const noexcept
labelList & addressing () noexcept
void clear ()
void incrAddressing (const label off)
void decrAddressing (const label off)
Detailed Description
Base class for ensightCells, ensightFaces, ensightOutputSurfaces.
Source files
ensightPart.H
ensightPart.C
Definition at line 49 of file ensightPart.H.
Constructor & Destructor Documentation
ensightPart() [1/2]
ensightPart ()
Definition at line 54 of file ensightPart.C.
ensightPart() [2/2]
ensightPart (const string & description) explicit
Definition at line 63 of file ensightPart.C.
~ensightPart()
virtual ~ensightPart () virtual default
Member Function Documentation
addressing() [1/2]
const labelList & addressing () const inline protected noexcept
Definition at line 72 of file ensightPart.H.
addressing() [2/2]
labelList & addressing () inline protected noexcept
Definition at line 78 of file ensightPart.H.
clear()
void clear () inline protected
Definition at line 84 of file ensightPart.H.
References List< T >::clear().
Referenced by ensightCells::clear(), and ensightFaces::clear().
incrAddressing()
void incrAddressing (const label off) protected
Definition at line 34 of file ensightPart.C.
decrAddressing()
void decrAddressing (const label off) protected
Definition at line 43 of file ensightPart.C.
TypeNameNoDebug()
TypeNameNoDebug ("ensightPart")
index() [1/2]
label index () const inline noexcept
Definition at line 120 of file ensightPart.H.
Referenced by ensightCells::write(), ensightFaces::write(), Foam::ensightOutput::Detail::writeFaceLocalField(), Foam::ensightOutput::Detail::writeFaceSubField(), Foam::ensightOutput::writeField(), Foam::ensightOutput::writeField(), ensightOutputSurface::writePointData(), and Foam::ensightOutput::writePointField().
index() [2/2]
label & index () inline noexcept
Definition at line 126 of file ensightPart.H.
identifier() [1/2]
label identifier () const inline noexcept
Definition at line 132 of file ensightPart.H.
Referenced by ensightMesh::correct(), and ensightFaMesh::correct().
identifier() [2/2]
label & identifier () inline noexcept
Definition at line 138 of file ensightPart.H.
empty()
bool empty () const inline noexcept
Definition at line 144 of file ensightPart.H.
References UList< T >::empty().
Referenced by ensightOutputSurface::writePointData().
size()
label size () const inline noexcept
Definition at line 150 of file ensightPart.H.
References UList< T >::size().
name()
const string & name () const inline noexcept
Definition at line 156 of file ensightPart.H.
Referenced by ensightCells::write(), and ensightFaces::write().
rename() [1/2]
void rename (const string & value) inline
Definition at line 162 of file ensightPart.H.
Referenced by ensightMesh::correct(), ensightFaMesh::correct(), ensightCells::ensightCells(), and ensightFaces::ensightFaces().
rename() [2/2]
void rename (string && value) inline
Definition at line 168 of file ensightPart.H.
writeDict()
virtual void writeDict (Ostream & os, const bool full = false) const inline virtual
Reimplemented in ensightCells, and ensightFaces.
Definition at line 178 of file ensightPart.H.
operator[]()
label operator[] (const label i) const inline
Definition at line 185 of file ensightPart.H.
The documentation for this class was generated from the following files:
src/fileFormats/ensight/part/part/ensightPart.H
src/fileFormats/ensight/part/part/ensightPart.C