OpenFOAM: filmSubModelBase Class Reference
filmSubModelBase Class Reference
Base class for surface film sub-models.
#include <filmSubModelBase.H>
Public Member Functions
filmSubModelBase (surfaceFilmRegionModel &film)
filmSubModelBase (surfaceFilmRegionModel &film, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
filmSubModelBase (const word &modelName, surfaceFilmRegionModel &film, const dictionary &dict, const word &baseName, const word &modelType)
virtual ~filmSubModelBase ()
virtual bool writeTime () const
const surfaceFilmRegionModel & film () const
surfaceFilmRegionModel & film ()
template<class FilmType >
const FilmType & filmType () const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
subModelBase (const subModelBase &smb)
virtual ~subModelBase ()=default
const word & modelName () const
const dictionary & dict () const
const word & baseName () const
const word & modelType () const
const dictionary & coeffDict () const
const dictionary & properties () const
virtual bool defaultCoeffs (const bool printMsg) const
virtual bool active () const
virtual void cacheFields (const bool store)
virtual fileName localPath () const
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
bool getModelDict (const word &entryName, dictionary &dict) const
template<class Type >
bool getModelProperty (const word &entryName, Type &value) const
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
virtual void write (Ostream &os) const
Protected Attributes
surfaceFilmRegionModel & filmModel_
Protected Attributes inherited from subModelBase
const word modelName_
dictionary & properties_
const dictionary dict_
const word baseName_
const word modelType_
const dictionary coeffDict_
Additional Inherited Members
Public Attributes inherited from subModelBase
bool log
Protected Member Functions inherited from subModelBase
bool inLine () const
Detailed Description
Base class for surface film sub-models.
Source files
filmSubModelBase.H
filmSubModelBaseI.H
filmSubModelBase.C
Source files
filmSubModelBase.H
filmSubModelBaseI.H
filmSubModelBase.C
Definition at line 52 of file filmSubModelBase.H.
Constructor & Destructor Documentation
filmSubModelBase() [1/3]
filmSubModelBase (surfaceFilmRegionModel & film)
Definition at line 34 of file filmSubModelBase.C.
filmSubModelBase() [2/3]
filmSubModelBase (surfaceFilmRegionModel & film, const dictionary & dict, const word & baseName, const word & modelType, const word & dictExt = "Coeffs")
Definition at line 41 of file filmSubModelBase.C.
filmSubModelBase() [3/3]
filmSubModelBase (const word & modelName, surfaceFilmRegionModel & film, const dictionary & dict, const word & baseName, const word & modelType)
Definition at line 62 of file filmSubModelBase.C.
~filmSubModelBase()
~filmSubModelBase () virtual
Definition at line 85 of file filmSubModelBase.C.
Member Function Documentation
writeTime()
bool writeTime () const virtual
Reimplemented from subModelBase.
Definition at line 91 of file filmSubModelBase.C.
References subModelBase::active(), filmSubModelBase::filmModel_, and regionModel::time().
Referenced by injectionModel::correct(), transferModel::correct(), phaseChangeModel::correct(), patchInjection::correct(), injectionModelList::info(), and transferModelList::info().
film() [1/2]
const surfaceFilmRegionModel & film () const inline
Definition at line 32 of file filmSubModelBaseI.H.
References filmSubModelBase::filmModel_.
Referenced by curvatureSeparation::calcCosAngle(), curvatureSeparation::calcInvR1(), liquidViscosity::correct(), thixotropicViscosity::correct(), BrunDrippingInjection::correct(), curvatureSeparation::correct(), drippingInjection::correct(), patchInjection::correct(), transferModel::correct(), injectionModelList::correct(), transferModelList::correct(), transferModelList::correct(), solidification::correctModel(), standardPhaseChange::correctModel(), waxSolventEvaporation::correctModel(), standardPhaseChange::correctModel(), waxSolventEvaporation::correctModel(), constantFilmThermo::Cp(), liquidFilmThermo::Cp(), curvatureSeparation::curvatureSeparation(), injectionModelList::info(), transferModelList::info(), injectionModelList::injectionModelList(), constantFilmThermo::kappa(), liquidFilmThermo::kappa(), constantFilmThermo::mu(), liquidFilmThermo::mu(), patchInjection::patchInjection(), constantFilmThermo::rho(), liquidFilmThermo::rho(), constantRadiation::Shs(), noRadiation::Shs(), primaryRadiation::Shs(), standardRadiation::Shs(), constantFilmThermo::sigma(), liquidFilmThermo::sigma(), laminar::Su(), and transferModelList::transferModelList().
film() [2/2]
surfaceFilmRegionModel & film () inline
Definition at line 38 of file filmSubModelBaseI.H.
References filmSubModelBase::filmModel_.
filmType()
template<class FilmType > const FilmType & filmType () const inline
Definition at line 31 of file filmSubModelBaseTemplates.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, filmSubModelBase::filmModel_, and subModelBase::modelType().
Member Data Documentation
filmModel_
surfaceFilmRegionModel& filmModel_ protected
Definition at line 61 of file filmSubModelBase.H.
Referenced by contactAngleForce::correct(), thermocapillaryForce::correct(), solidification::correctModel(), filmSubModelBase::film(), filmSubModelBase::film(), filmSubModelBase::filmType(), constantHeatTransfer::h(), phaseChangeModel::info(), liquidFilmThermo::initLiquid(), laminar::mut(), constantRadiation::Shs(), primaryRadiation::Shs(), standardRadiation::Shs(), laminar::Su(), liquidFilmThermo::thermoFilm(), distributionContactAngleForce::theta(), perturbedTemperatureDependentContactAngleForce::theta(), temperatureDependentContactAngleForce::theta(), laminar::Us(), and filmSubModelBase::writeTime().
The documentation for this class was generated from the following files:
src/regionModels/surfaceFilmModels/submodels/filmSubModelBase.H
src/regionModels/surfaceFilmModels/submodels/filmSubModelBase.C
src/regionModels/surfaceFilmModels/submodels/filmSubModelBaseI.H
src/regionModels/surfaceFilmModels/submodels/filmSubModelBaseTemplates.C