OpenFOAM: rigidBodyModelState Class Reference
rigidBodyModelState Class Reference
Holds the motion state of rigid-body model.
#include <rigidBodyModelState.H>
Public Member Functions
rigidBodyModelState (const rigidBodyModel &model)
rigidBodyModelState (const rigidBodyModel &model, const dictionary &dict)
const scalarField & q () const
const scalarField & qDot () const
const scalarField & qDdot () const
scalar t () const
scalar deltaT () const
scalarField & q ()
scalarField & qDot ()
scalarField & qDdot ()
scalar & t ()
scalar & deltaT ()
void write (dictionary &dict) const
void write (Ostream &) const
Friends
Istream & operator>> (Istream &, rigidBodyModelState &)
Ostream & operator<< (Ostream &, const rigidBodyModelState &)
Detailed Description
Holds the motion state of rigid-body model.
Source files
rigidBodyModelState.H
rigidBodyModelStateI.H
rigidBodyModelState.C
rigidBodyModelStateIO.C
Definition at line 58 of file rigidBodyModelState.H.
Constructor & Destructor Documentation
rigidBodyModelState() [1/2]
rigidBodyModelState (const rigidBodyModel & model)
Definition at line 26 of file rigidBodyModelState.C.
rigidBodyModelState() [2/2]
rigidBodyModelState (const rigidBodyModel & model, const dictionary & dict)
Definition at line 39 of file rigidBodyModelState.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, rigidBodyModel::nDoF(), and UList< T >::size().
Member Function Documentation
q() [1/2]
const Foam::scalarField & q () const inline
Definition at line 23 of file rigidBodyModelStateI.H.
Referenced by rigidBodyModel::forwardDynamics(), and rigidBodyModel::forwardDynamicsCorrection().
qDot() [1/2]
const Foam::scalarField & qDot () const inline
Definition at line 29 of file rigidBodyModelStateI.H.
Referenced by rigidBodyModel::forwardDynamics(), and rigidBodyModel::forwardDynamicsCorrection().
qDdot() [1/2]
const Foam::scalarField & qDdot () const inline
Definition at line 35 of file rigidBodyModelStateI.H.
Referenced by rigidBodyModel::forwardDynamics(), rigidBodyMotion::forwardDynamics(), and rigidBodyModel::forwardDynamicsCorrection().
t() [1/2]
Foam::scalar t () const inline
Definition at line 41 of file rigidBodyModelStateI.H.
Referenced by externalForce::restrain().
deltaT() [1/2]
Foam::scalar deltaT () const inline
Definition at line 47 of file rigidBodyModelStateI.H.
q() [2/2]
Foam::scalarField & q () inline
Definition at line 53 of file rigidBodyModelStateI.H.
qDot() [2/2]
Foam::scalarField & qDot () inline
Definition at line 59 of file rigidBodyModelStateI.H.
qDdot() [2/2]
Foam::scalarField & qDdot () inline
Definition at line 65 of file rigidBodyModelStateI.H.
t() [2/2]
Foam::scalar & t () inline
Definition at line 77 of file rigidBodyModelStateI.H.
deltaT() [2/2]
Foam::scalar & deltaT () inline
Definition at line 71 of file rigidBodyModelStateI.H.
write() [1/2]
void write (dictionary & dict) const
Definition at line 26 of file rigidBodyModelStateIO.C.
References dict.
write() [2/2]
void write (Ostream & os) const
Definition at line 36 of file rigidBodyModelStateIO.C.
References os().
Friends And Related Symbol Documentation
operator>>
Istream & operator>> (Istream & , rigidBodyModelState &) friend
operator<<
Ostream & operator<< (Ostream & , const rigidBodyModelState &) friend
The documentation for this class was generated from the following files:
src/rigidBodyDynamics/rigidBodyModelState/rigidBodyModelState.H
src/rigidBodyDynamics/rigidBodyModelState/rigidBodyModelState.C
src/rigidBodyDynamics/rigidBodyModelState/rigidBodyModelStateI.H
src/rigidBodyDynamics/rigidBodyModelState/rigidBodyModelStateIO.C