OpenFOAM: bladeModel Class Reference
bladeModel Class Reference
Blade model class calculates:
#include <bladeModel.H>
Public Member Functions
bladeModel (const dictionary &dict)
bladeModel (const bladeModel &)=delete
void operator= (const bladeModel &)=delete
virtual ~bladeModel ()=default
const List< word > & profileName () const
const List< label > & profileID () const
const List< scalar > & radius () const
const List< scalar > & twist () const
const List< scalar > & chord () const
List< label > & profileID ()
virtual void interpolate (const scalar radius, scalar &twist, scalar &chord, label &i1, label &i2, scalar &invDr) const
Protected Member Functions
bool readFromFile () const
void interpolateWeights (const scalar &xIn, const List< scalar > &values, label &i1, label &i2, scalar &ddx) const
Protected Attributes
List< word > profileName_
List< label > profileID_
List< scalar > radius_
List< scalar > twist_
List< scalar > chord_
fileName fName_
Detailed Description
Blade model class calculates:
Linear interpolated blade twist and chord based on radial position
Interpolation factor (for interpolating profile performance)
Usage
Minimal example by using constant/fvOptions: rotorDiskSource1 { Mandatory/Optional (inherited) entries ...
Mandatory entries (runtime modifiable) blade { Mandatory entries (runtime modifiable) data ((profile1 (radius1 twist1 chord1)) (profile1 (radius2 twist2 chord2)) ... ([0] ([1] [2] [3])));
Optional entries (runtime modifiable) file <fileName>; } }
where the entries mean:
Property Description Type Reqd Dflt
blade Dictionary name: blade word yes -
data Blade characteristics in list format list yes -
[0] (profile) Corresponding profile name per section word yes -
[1] (radius) Radial position of the blade section [m] scalar yes -
[2] (twist) Twist angle of the blade section [deg] scalar yes -
[3] (chord) Chord length of the blade section [m] scalar yes -
file Name of file containing blade characteristics word no -
Note
The entry twist is internally converted from [deg] to [rad].
See also
Foam::fv::rotorDiskSource
Source files
bladeModel.H
bladeModel.C
Definition at line 140 of file bladeModel.H.
Constructor & Destructor Documentation
bladeModel() [1/2]
bladeModel (const dictionary & dict)
Definition at line 85 of file bladeModel.C.
References bladeModel::chord_, Foam::degToRad(), dict, Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, UILList< LListBase, T >::first(), bladeModel::fName_, forAll, bladeModel::profileID_, bladeModel::profileName_, bladeModel::radius_, dictionary::readEntry(), bladeModel::readFromFile(), List< T >::setSize(), and bladeModel::twist_.
bladeModel() [2/2]
bladeModel (const bladeModel &) delete
~bladeModel()
virtual ~bladeModel () virtual default
Member Function Documentation
readFromFile()
bool readFromFile () const protected
Definition at line 30 of file bladeModel.C.
References bladeModel::fName_.
Referenced by bladeModel::bladeModel().
interpolateWeights()
void interpolateWeights (const scalar & xIn, const List< scalar > & values, label & i1, label & i2, scalar & ddx) const protected
Definition at line 36 of file bladeModel.C.
operator=()
void operator= (const bladeModel &) delete
profileName()
const Foam::List< Foam::word > & profileName () const
Definition at line 133 of file bladeModel.C.
Referenced by rotorDiskSource::checkData().
profileID() [1/2]
const Foam::List< Foam::label > & profileID () const
Definition at line 139 of file bladeModel.C.
Referenced by rotorDiskSource::calculate(), and rotorDiskSource::checkData().
radius()
const Foam::List< Foam::scalar > & radius () const
Definition at line 145 of file bladeModel.C.
twist()
const Foam::List< Foam::scalar > & twist () const
Definition at line 151 of file bladeModel.C.
chord()
const Foam::List< Foam::scalar > & chord () const
Definition at line 157 of file bladeModel.C.
profileID() [2/2]
Foam::List< Foam::label > & profileID ()
Definition at line 163 of file bladeModel.C.
interpolate()
void interpolate (const scalar radius, scalar & twist, scalar & chord, label & i1, label & i2, scalar & invDr) const virtual
Definition at line 169 of file bladeModel.C.
Referenced by rotorDiskSource::calculate().
Member Data Documentation
profileName_
List<word> profileName_ protected
Definition at line 147 of file bladeModel.H.
Referenced by bladeModel::bladeModel().
profileID_
List<label> profileID_ protected
Definition at line 150 of file bladeModel.H.
Referenced by bladeModel::bladeModel().
radius_
List<scalar> radius_ protected
Definition at line 153 of file bladeModel.H.
Referenced by bladeModel::bladeModel().
twist_
List<scalar> twist_ protected
Definition at line 156 of file bladeModel.H.
Referenced by bladeModel::bladeModel().
chord_
List<scalar> chord_ protected
Definition at line 159 of file bladeModel.H.
Referenced by bladeModel::bladeModel().
fName_
fileName fName_ protected
Definition at line 162 of file bladeModel.H.
Referenced by bladeModel::bladeModel(), and bladeModel::readFromFile().
The documentation for this class was generated from the following files:
src/fvOptions/sources/derived/rotorDiskSource/bladeModel/bladeModel.H
src/fvOptions/sources/derived/rotorDiskSource/bladeModel/bladeModel.C