OpenFOAM: cyclicFvPatch Class Reference
cyclicFvPatch Class Reference
Cyclic-plane patch.
#include <cyclicFvPatch.H>
Public Member Functions
TypeName (cyclicPolyPatch::typeName_())
cyclicFvPatch (const polyPatch &patch, const fvBoundaryMesh &bm)
const cyclicPolyPatch & cyclicPatch () const
virtual label neighbPatchID () const
virtual bool owner () const
virtual const cyclicFvPatch & neighbPatch () const
virtual bool parallel () const
virtual const tensorField & forwardT () const
virtual const tensorField & reverseT () const
const cyclicFvPatch & neighbFvPatch () const
virtual tmp< vectorField > delta () const
virtual tmp< labelField > interfaceInternalField (const labelUList &internalData) const
virtual tmp< labelField > interfaceInternalField (const labelUList &internalData, const labelUList &faceCell) const
virtual tmp< labelField > internalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &internalData) const
Public Member Functions inherited from coupledFvPatch
TypeNameNoDebug (coupledPolyPatch::typeName_())
coupledFvPatch (const polyPatch &patch, const fvBoundaryMesh &bm)
virtual ~coupledFvPatch ()=default
virtual bool coupled () const
virtual const labelUList & faceCells () const
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, labelUList &iF) const
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, labelUList &iF, const labelUList &faceCell) const
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &iF) const
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &iF, const labelUList &faceCells) const
Public Member Functions inherited from lduInterface
TypeNameNoDebug ("lduInterface")
lduInterface () noexcept=default
virtual ~lduInterface ()=default
Public Member Functions inherited from fvPatch
virtual void makeDeltaCoeffs (scalarField &) const
virtual void makeNonOrthoDeltaCoeffs (scalarField &) const
virtual void makeNonOrthoCorrVectors (vectorField &) const
virtual void initMovePoints ()
virtual void movePoints ()
TypeName (polyPatch::typeName_())
declareRunTimeSelectionTable (autoPtr, fvPatch, polyPatch,(const polyPatch &patch, const fvBoundaryMesh &bm),(patch, bm))
fvPatch (const polyPatch &, const fvBoundaryMesh &)
virtual ~fvPatch ()
const polyPatch & patch () const noexcept
virtual const word & name () const
label index () const noexcept
label start () const noexcept
virtual label size () const
const fvBoundaryMesh & boundaryMesh () const noexcept
template<class T >
const List< T >::subList patchSlice (const List< T > &values) const
template<class T >
const List< T >::subList boundarySlice (const List< T > &values) const
const vectorField & Cf () const
tmp< vectorField > Cn () const
const vectorField & Sf () const
const scalarField & magSf () const
tmp< vectorField > unitSf () const
tmp< vectorField > nf () const
const scalarField & weights () const
const scalarField & deltaCoeffs () const
template<class Type >
void patchInternalField (const UList< Type > &internalData, const labelUList &addressing, Field< Type > &pfld) const
template<class Type >
void patchInternalField (const UList< Type > &internalData, Field< Type > &pfld) const
template<class Type >
tmp< Field< Type > > patchInternalField (const UList< Type > &internalData) const
template<class GeometricField , class AnyType = bool>
const GeometricField::Patch & patchField (const GeometricField &gf) const
template<class GeometricField , class AnyType = bool>
const GeometricField::Patch & lookupPatchField (const word &name, const GeometricField *=nullptr, const AnyType *=nullptr) const
template<class Type >
Foam::tmp< Foam::Field< Type > > patchInternalField (const UList< Type > &internalData) const
Public Member Functions inherited from cyclicLduInterface
TypeNameNoDebug ("cyclicLduInterface")
cyclicLduInterface () noexcept=default
virtual ~cyclicLduInterface ()=default
Protected Member Functions
void makeWeights (scalarField &) const
Additional Inherited Members
Public Types inherited from fvPatch
typedef fvBoundaryMesh BoundaryMesh
Static Public Member Functions inherited from fvPatch
static autoPtr< fvPatch > New (const polyPatch &, const fvBoundaryMesh &)
static const fvPatch & lookupPatch (const polyPatch &p)
static bool constraintType (const word &patchType)
static wordList constraintTypes ()
Detailed Description
Cyclic-plane patch.
Source files
cyclicFvPatch.H
cyclicFvPatch.C
Definition at line 50 of file cyclicFvPatch.H.
Constructor & Destructor Documentation
cyclicFvPatch()
cyclicFvPatch (const polyPatch & patch, const fvBoundaryMesh & bm) inline
Definition at line 77 of file cyclicFvPatch.H.
Member Function Documentation
makeWeights()
void makeWeights (scalarField & w) const protected virtual
Implements coupledFvPatch.
Definition at line 38 of file cyclicFvPatch.C.
References coupledFvPatch::delta(), forAll, cyclicFvPatch::neighbFvPatch(), and fvPatch::nf().
TypeName()
TypeName (cyclicPolyPatch::typeName_())
cyclicPatch()
const cyclicPolyPatch & cyclicPatch () const inline
Definition at line 89 of file cyclicFvPatch.H.
neighbPatchID()
virtual label neighbPatchID () const inline virtual
Implements cyclicLduInterface.
Definition at line 95 of file cyclicFvPatch.H.
References cyclicPolyPatch::neighbPatchID().
owner()
virtual bool owner () const inline virtual
Implements cyclicLduInterface.
Definition at line 100 of file cyclicFvPatch.H.
References cyclicPolyPatch::owner().
neighbPatch()
virtual const cyclicFvPatch & neighbPatch () const inline virtual
Implements cyclicLduInterface.
Definition at line 106 of file cyclicFvPatch.H.
References cyclicPolyPatch::neighbPatchID().
parallel()
virtual bool parallel () const inline virtual
Implements coupledFvPatch.
Definition at line 115 of file cyclicFvPatch.H.
References coupledPolyPatch::parallel().
Referenced by cyclicFvPatchField< Type >::doTransform().
forwardT()
virtual const tensorField & forwardT () const inline virtual
Implements coupledFvPatch.
Definition at line 121 of file cyclicFvPatch.H.
References coupledPolyPatch::forwardT().
Referenced by cyclicFvPatchField< Type >::forwardT().
reverseT()
virtual const tensorField & reverseT () const inline virtual
Implements coupledFvPatch.
Definition at line 127 of file cyclicFvPatch.H.
References coupledPolyPatch::reverseT().
Referenced by cyclicFvPatchField< Type >::reverseT().
neighbFvPatch()
const cyclicFvPatch & neighbFvPatch () const inline
Definition at line 132 of file cyclicFvPatch.H.
References cyclicPolyPatch::neighbPatchID().
Referenced by cyclicFvPatch::makeWeights().
delta()
Foam::tmp< Foam::vectorField > delta () const virtual
Implements coupledFvPatch.
Definition at line 55 of file cyclicFvPatch.C.
References coupledFvPatch::delta(), forAll, UPtrList< T >::size(), and Foam::transform().
interfaceInternalField() [1/2]
Foam::tmp< Foam::labelField > interfaceInternalField (const labelUList & internalData) const virtual
Implements coupledFvPatch.
Definition at line 89 of file cyclicFvPatch.C.
interfaceInternalField() [2/2]
Foam::tmp< Foam::labelField > interfaceInternalField (const labelUList & internalData, const labelUList & faceCell) const virtual
Implements coupledFvPatch.
Definition at line 98 of file cyclicFvPatch.C.
References tmp< T >::New().
internalFieldTransfer()
Foam::tmp< Foam::labelField > internalFieldTransfer (const Pstream::commsTypes commsType, const labelUList & internalData) const virtual
Implements coupledFvPatch.
Definition at line 110 of file cyclicFvPatch.C.
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/fvPatches/constraint/cyclic/cyclicFvPatch.H
src/finiteVolume/fvMesh/fvPatches/constraint/cyclic/cyclicFvPatch.C