OpenFOAM: surfaceFieldValue Class Reference
surfaceFieldValue Class Reference
FunctionObjects » Field function objects
A face regionType variant of the fieldValues function object.
#include <surfaceFieldValue.H>
Public Types
enum regionTypes { stFaceZone = 0x01 , stPatch = 0x02 , stObject = 0x11 , stSampled = 0x12 }
enum operationVariant { typeBase = 0 , typeScalar = 0x100 , typeWeighted = 0x200 , typeAbsolute = 0x400 }
enum operationType {
opNone = 0 , opMin , opMax , opSum ,
opSumMag , opSumDirection , opSumDirectionBalance , opAverage ,
opAreaAverage , opAreaIntegrate , opCoV , opAreaNormalAverage = typeScalar ,
opAreaNormalIntegrate , opUniformity , opWeightedSum = (opSum | typeWeighted) , opWeightedAverage = (opAverage | typeWeighted) ,
opWeightedAreaAverage = (opAreaAverage | typeWeighted) , opWeightedAreaIntegrate = (opAreaIntegrate | typeWeighted) , opWeightedUniformity = (opUniformity | typeWeighted) , opAbsWeightedSum = (opWeightedSum | typeAbsolute) ,
opAbsWeightedAverage = (opWeightedAverage | typeAbsolute) , opAbsWeightedAreaAverage = (opWeightedAreaAverage | typeAbsolute) , opAbsWeightedAreaIntegrate , opAbsWeightedUniformity
}
enum postOperationType { postOpNone , postOpMag , postOpSqrt }
Public Member Functions
TypeName ("surfaceFieldValue")
surfaceFieldValue (const word &name, const Time &runTime, const dictionary &dict)
surfaceFieldValue (const word &name, const objectRegistry &obr, const dictionary &dict)
surfaceFieldValue (const surfaceFieldValue &)=delete
void operator= (const surfaceFieldValue &)=delete
virtual ~surfaceFieldValue ()
regionTypes regionType () const noexcept
fileName outputDir () const
virtual bool read (const dictionary &dict)
virtual bool write ()
virtual void updateMesh (const mapPolyMesh &mpm)
virtual void movePoints (const polyMesh &mesh)
template<>
Foam::scalar processValues (const Field< scalar > &values, const vectorField &Sf, const scalarField &weightField) const
template<>
Foam::vector processValues (const Field< vector > &values, const vectorField &Sf, const scalarField &weightField) const
template<>
Foam::tmp< Foam::scalarField > weightingFactor (const Field< scalar > &weightField, const bool useMag)
template<>
Foam::tmp< Foam::scalarField > weightingFactor (const Field< scalar > &weightField, const vectorField &Sf, const bool useMag)
template<>
Foam::tmp< Foam::scalarField > areaWeightingFactor (const Field< scalar > &weightField, const vectorField &Sf, const bool useMag)
template<>
Foam::tmp< Foam::scalarField > weightingFactor (const Field< vector > &weightField, const vectorField &Sf, const bool useMag)
template<>
Foam::tmp< Foam::scalarField > areaWeightingFactor (const Field< vector > &weightField, const vectorField &Sf, const bool useMag)
template<>
scalar processValues (const Field< scalar > &values, const vectorField &Sf, const scalarField &weightField) const
template<>
vector processValues (const Field< vector > &values, const vectorField &Sf, const scalarField &weightField) const
template<>
tmp< scalarField > weightingFactor (const Field< scalar > &weightField, const bool useMag)
template<>
tmp< scalarField > weightingFactor (const Field< scalar > &weightField, const vectorField &Sf, const bool useMag)
template<>
tmp< scalarField > areaWeightingFactor (const Field< scalar > &weightField, const vectorField &Sf, const bool useMag)
template<>
tmp< scalarField > weightingFactor (const Field< vector > &weightField, const vectorField &Sf, const bool useMag)
template<>
tmp< scalarField > areaWeightingFactor (const Field< vector > &weightField, const vectorField &Sf, const bool useMag)
template<class WeightType >
Foam::tmp< Foam::scalarField > weightingFactor (const Field< WeightType > &weightField, const bool useMag)
template<class Type >
Foam::tmp< Foam::Field< Type > > getFieldValues (const word &fieldName, const bool mandatory) const
template<class WeightType >
Foam::label writeAll (const vectorField &Sf, const Field< WeightType > &weightField, const pointField &points, const faceList &faces)
template<class Type >
Foam::tmp< Foam::Field< Type > > filterField (const GeometricField< Type, fvPatchField, volMesh > &field) const
template<class Type >
Foam::tmp< Foam::Field< Type > > filterField (const GeometricField< Type, fvsPatchField, surfaceMesh > &field) const
Public Member Functions inherited from fieldValue
TypeName ("fieldValue")
declareRunTimeSelectionTable (autoPtr, fieldValue, runTime,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
fieldValue (const word &name, const Time &runTime, const dictionary &dict, const word &valueType)
fieldValue (const word &name, const objectRegistry &obr, const dictionary &dict, const word &valueType)
virtual ~fieldValue ()=default
const dictionary & dict () const noexcept
const word & regionName () const noexcept
const wordList & fields () const noexcept
bool writeFields () const noexcept
virtual bool execute ()
Public Member Functions inherited from fvMeshFunctionObject
TypeName ("fvMeshFunctionObject")
fvMeshFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
fvMeshFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
virtual ~fvMeshFunctionObject ()=default
Public Member Functions inherited from regionFunctionObject
TypeName ("regionFunctionObject")
regionFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
regionFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
virtual ~regionFunctionObject ()=default
template<class ObjectType >
const ObjectType * lookupObjectPtr (const word &fieldName) const
template<class ObjectType >
ObjectType * lookupObjectRefPtr (const word &fieldName) const
Public Member Functions inherited from stateFunctionObject
stateFunctionObject (const word &name, const Time &runTime)
virtual ~stateFunctionObject ()=default
dictionary & propertyDict ()
bool foundProperty (const word &entryName) const
void clearTrigger ()
label getTrigger () const
bool setTrigger (const label triggeri)
bool getDict (const word &entryName, dictionary &dict) const
bool getObjectDict (const word &objectName, const word &entryName, dictionary &dict) const
template<class Type >
Type getProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getProperty (const word &entryName, Type &value) const
template<class Type >
void setProperty (const word &entryName, const Type &value)
template<class Type >
Type getObjectProperty (const word &objectName, const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getObjectProperty (const word &objectName, const word &entryName, Type &value) const
template<class Type >
void setObjectProperty (const word &objectName, const word &entryName, const Type &value)
template<class Type >
void setResult (const word &entryName, const Type &value)
template<class Type >
void setObjectResult (const word &objectName, const word &entryName, const Type &value)
template<class Type >
Type getResult (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
Type getObjectResult (const word &objectName, const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getObjectResult (const word &objectName, const word &entryName, Type &value) const
word resultType (const word &entryName) const
word objectResultType (const word &objectName, const word &entryName) const
wordList objectResultEntries () const
wordList objectResultEntries (const word &objectName) const
void writeResultEntries (Ostream &os) const
void writeResultEntries (const word &objectName, Ostream &os) const
void writeAllResultEntries (Ostream &os) const
Public Member Functions inherited from timeFunctionObject
timeFunctionObject (const word &name, const Time &runTime)
virtual ~timeFunctionObject ()=default
const Time & time () const
objectRegistry & storedObjects ()
const objectRegistry & storedObjects () const
Public Member Functions inherited from functionObject
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name, const bool withNamePrefix=defaultUseNamePrefix)
autoPtr< functionObject > clone () const
virtual ~functionObject ()=default
virtual const word & type () const =0
const word & name () const noexcept
bool useNamePrefix () const noexcept
bool useNamePrefix (bool on) noexcept
virtual bool execute (const label subIndex)
virtual bool end ()
virtual bool adjustTimeStep ()
virtual bool filesModified () const
Public Member Functions inherited from writeFile
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name="undefined", const bool writeToFile=true)
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name, const dictionary &dict, const bool writeToFile=true)
writeFile (const writeFile &wf)
virtual ~writeFile ()=default
virtual OFstream & file ()
virtual bool writeToFile () const
virtual bool canWriteToFile () const
virtual bool canResetFile () const
virtual bool canWriteHeader () const
virtual label charWidth () const
virtual void writeCommented (Ostream &os, const string &str) const
virtual void writeTabbed (Ostream &os, const string &str) const
virtual void writeHeader (Ostream &os, const string &str) const
virtual void writeCurrentTime (Ostream &os) const
virtual void writeBreak (Ostream &os) const
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
template<class Type >
void writeValue (Ostream &os, const Type &val) const
Static Public Attributes
static const Enum< regionTypes > regionTypeNames_
static const Enum< operationType > operationTypeNames_
static const Enum< postOperationType > postOperationTypeNames_
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
static bool defaultUseNamePrefix
static word outputPrefix
Static Public Attributes inherited from writeFile
static label addChars = 8
Protected Member Functions
const objectRegistry & obr () const
bool withSurfaceFields () const
bool withTopologicalMerge () const noexcept
const labelList & faceId () const noexcept
const labelList & facePatch () const noexcept
const boolList & faceFlip () const noexcept
bool usesSf () const noexcept
bool is_magOp () const noexcept
bool is_weightedOp () const noexcept
template<class WeightType >
bool canWeight (const Field< WeightType > &fld) const
bool update ()
template<class Type >
bool validField (const word &fieldName) const
template<class Type >
tmp< Field< Type > > getFieldValues (const word &fieldName, const bool mandatory=false) const
template<class Type , class WeightType >
Type processSameTypeValues (const Field< Type > &values, const vectorField &Sf, const Field< WeightType > &weightField) const
template<class Type , class WeightType >
Type processValues (const Field< Type > &values, const vectorField &Sf, const Field< WeightType > &weightField) const
template<class Type >
tmp< Field< Type > > filterField (const GeometricField< Type, fvsPatchField, surfaceMesh > &field) const
template<class Type >
tmp< Field< Type > > filterField (const GeometricField< Type, fvPatchField, volMesh > &field) const
template<class WeightType >
label writeAll (const vectorField &Sf, const Field< WeightType > &weightField, const pointField &points, const faceList &faces)
template<class Type , class WeightType >
bool writeValues (const word &fieldName, const vectorField &Sf, const Field< WeightType > &weightField, const pointField &points, const faceList &faces)
virtual void writeFileHeader (Ostream &os)
Protected Member Functions inherited from fieldValue
template<class Type >
void combineFields (Field< Type > &field)
template<class Type >
void combineFields (tmp< Field< Type > > &)
Protected Member Functions inherited from fvMeshFunctionObject
fvMeshFunctionObject (const fvMeshFunctionObject &)=delete
void operator= (const fvMeshFunctionObject &)=delete
Protected Member Functions inherited from regionFunctionObject
template<class ObjectType >
bool foundObject (const word &fieldName) const
template<class ObjectType >
const ObjectType * cfindObject (const word &fieldName) const
template<class ObjectType >
const ObjectType * findObject (const word &fieldName) const
template<class ObjectType >
ObjectType * findObject (const word &fieldName)
template<class ObjectType >
ObjectType * getObjectPtr (const word &fieldName) const
template<class ObjectType >
const ObjectType & lookupObject (const word &fieldName) const
template<class ObjectType >
ObjectType & lookupObjectRef (const word &fieldName) const
template<class ObjectType >
bool store (word &fieldName, const tmp< ObjectType > &tfield, bool cacheable=false)
template<class ObjectType >
bool storeInDb (const word &fieldName, const tmp< ObjectType > &tfield, const objectRegistry &obr)
bool writeObject (const word &fieldName)
bool clearObject (const word &fieldName)
void clearObjects (const wordList &objNames)
regionFunctionObject (const regionFunctionObject &)=delete
void operator= (const regionFunctionObject &)=delete
Protected Member Functions inherited from stateFunctionObject
const functionObjects::properties & stateDict () const
functionObjects::properties & stateDict ()
stateFunctionObject (const stateFunctionObject &)=delete
void operator= (const stateFunctionObject &)=delete
Protected Member Functions inherited from timeFunctionObject
void clearOutputObjects (const wordList &objNames)
timeFunctionObject (const timeFunctionObject &)=delete
void operator= (const timeFunctionObject &)=delete
Protected Member Functions inherited from functionObject
word scopedName (const word &name) const
Protected Member Functions inherited from writeFile
void initStream (Ostream &os) const
fileName baseFileDir () const
fileName baseTimeDir () const
fileName filePath (const fileName &fName) const
virtual autoPtr< OFstream > newFile (const fileName &fName) const
virtual autoPtr< OFstream > newFileAtTime (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > newFileAtStartTime (const word &name) const
virtual void resetFile (const word &name)
Omanip< int > valueWidth (const label offset=0) const
void operator= (const writeFile &)=delete
virtual autoPtr< OFstream > createFile (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > createFile (const word &name) const
Static Protected Member Functions
template<class WeightType >
static tmp< scalarField > weightingFactor (const Field< WeightType > &weightField, const bool useMag)
template<class WeightType >
static tmp< scalarField > weightingFactor (const Field< WeightType > &weightField, const vectorField &Sf, const bool useMag)
template<class WeightType >
static tmp< scalarField > areaWeightingFactor (const Field< WeightType > &weightField, const vectorField &Sf, const bool useMag)
Protected Attributes
regionTypes regionType_
operationType operation_
postOperationType postOperation_
bool needsUpdate_
bool writeArea_
wordRes selectionNames_
wordList weightFieldNames_
scalar totalArea_
label nFaces_
labelList faceId_
labelList facePatchId_
boolList faceFlip_
autoPtr< sampledSurface > sampledPtr_
autoPtr< surfaceWriter > surfaceWriterPtr_
Protected Attributes inherited from fieldValue
bool writeFields_
word regionName_
scalar scaleFactor_
dictionary dict_
wordList fields_
Protected Attributes inherited from fvMeshFunctionObject
const fvMesh & mesh_
Protected Attributes inherited from regionFunctionObject
word subRegistryName_
const objectRegistry & obr_
const objectRegistry * obrPtr_
Protected Attributes inherited from timeFunctionObject
const Time & time_
Protected Attributes inherited from writeFile
const objectRegistry & fileObr_
const fileName prefix_
word fileName_
autoPtr< OFstream > filePtr_
label writePrecision_
bool writeToFile_
bool updateHeader_
bool writtenHeader_
bool useUserTime_
scalar startTime_
Additional Inherited Members
Static Public Member Functions inherited from fieldValue
static autoPtr< fieldValue > New (const word &name, const Time &runTime, const dictionary &dict, const bool output=true)
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &runTime, const dictionary &dict)
Public Attributes inherited from functionObject
bool log
Detailed Description
A face regionType variant of the fieldValues function object.
Given a list of user-specified fields and a selection of mesh (or general surface) faces, a number of operations can be performed, such as sums, averages and integrations.
For example, to calculate the volumetric or mass flux across a patch, apply the sum operator to the flux field (typically phi).
Usage
A minimal example:
surfaceFieldValuePatch1
{
    // Mandatory entries (unmodifiable)
    type            surfaceFieldValue;
    libs            (fieldFunctionObjects);
    // Mandatory entries (runtime modifiable)
    fields          (<field1> <field2> ... <fieldN>);
    operation       <operationType>;
    regionType      patch;
    name            <patch>;
    // Optional entries (runtime modifiable)
    names           (<patch-name> <patch-regex>);
    postOperation   none;
    weightField     alpha1;
    scaleFactor     1.0;
    writeArea       false;
    surfaceFormat   none;
    // Optional (inherited) entries
    ...
}
surfaceFieldValueFaceZone1
{
    // Mandatory entries (unmodifiable)
    type            surfaceFieldValue;
    libs            (fieldFunctionObjects);
    // Mandatory entries (runtime modifiable)
    fields          (<field1> <field2> ... <fieldN>);
    operation       <operationType>;
    regionType      faceZone;
    name            <faceZone>;
    // Optional entries (runtime modifiable)
    names           (<zone-name> <zone-regex>);
    postOperation   none;
    weightFields    (rho U);
    scaleFactor     1.0;
    writeArea       false;
    surfaceFormat   none;
    // Optional (inherited) entries
    ...
}
where the entries mean:
Property Description Type Reqd Dflt
type Type name: surfaceFieldValue word yes -
libs Libraries: fieldFunctionObjects wordList yes -
regionType Face regionType: see below word yes -
fields Names of operand fields wordList yes -
name Name of the regionType word yes -
names Extended selection word/regex list no -
operation Operation type: see below word yes -
postOperation Post-operation type: see below word no none
weightField Name of field to apply weighting word maybe
weightFields Names of fields to apply weighting wordList maybe
scaleFactor Output value scaling factor scalar no 1.0
writeArea Write the surface area bool no false
surfaceFormat Output value format
word
conditional on writeFields none
The inherited entries are elaborated in:
fieldValue.H
Options for the regionType entry:
faceZone : The name entry specifies a faceZone. Supports names
patch : The name entry specifies a patch. Supports names
functionObjectSurface : The name entry specifies a polySurface
sampledSurface : A sampledSurfaceDict sub-dictionary and name
Options for the operation entry:
none : no operation
min : minimum
max : maximum
sum : sum
sumMag : sum of component magnitudes
sumDirection : sum values that are positive in given direction
sumDirectionBalance : sum of balance of values in given direction
average : ensemble average
areaAverage : area-weighted average
areaIntegrate : area integral
CoV : coefficient of variation: standard deviation/mean
areaNormalAverage : area-weighted average in face normal direction
areaNormalIntegrate : area-weighted integral in face normal directon
uniformity : uniformity index
weightedSum : weighted sum
weightedAverage : weighted average
weightedAreaAverage : weighted area average
weightedAreaIntegrate : weighted area integral
weightedUniformity : weighted uniformity index
absWeightedSum : sum using absolute weighting
absWeightedAverage : average using absolute weighting
absWeightedAreaAverage : area average using absolute weighting
absWeightedAreaIntegrate : area integral using absolute weighting
absWeightedUniformity : uniformity index using absolute weighting
Options for the postOperation entry:
none : No additional operation after calculation
mag : Component-wise mag() after normal operation
sqrt : Component-wise sqrt() after normal operation
Usage by the postProcess utility is not available.
Note
Some types (eg, patch or faceZone) support the selection of multiple entries, which can be specified as list of words or regular expressions by names entry.
If the names enty exists and contains a literal that can be used as a suitable value for name, the name entry becomes optional instead of being mandatory.
The values reported by the areaNormalAverage and areaNormalIntegrate operations are written as the first component of a field with the same rank as the input field.
Faces on empty patches are ignored.
Using functionObjectSurface:
The keyword subRegion should not be used to select surfaces. Instead specify the regionType 'functionObjectSurface' and provide the name.
Using sampledSurface:
surface fields only supported by some surfaces
default uses sampleScheme cell
each face in sampledSurface is logically only in one cell so sampling will be wrong when they are larger than cells. This can only happen for sampling on a triSurfaceMesh
take care when using isoSurfaces - these might have duplicate triangles and so integration might be wrong
Uniformity:
A velocity uniformity index is calculated with no weighting (W=1) and .
A scalar concentration uniformity index is calculated with either or for weighting and .
See also
Foam::functionObject
Foam::functionObjects::fieldValues::fieldValue
ExtendedCodeGuide::functionObjects::field::surfaceFieldValue
Source files
surfaceFieldValue.H
surfaceFieldValue.C
surfaceFieldValueTemplates.C
Definition at line 448 of file surfaceFieldValue.H.
Member Enumeration Documentation
regionTypes
enum regionTypes
Enumerator
stFaceZone
Calculate with faceZone(s)
stPatch
Calculate with patch(es)
stObject
Calculate with function object surface.
stSampled
Sample onto surface and calculate.
Definition at line 457 of file surfaceFieldValue.H.
operationVariant
enum operationVariant
Enumerator
typeBase
Base operation.
typeScalar
Operation returns a scalar.
typeWeighted
Operation using weighting.
typeAbsolute
Operation using mag (eg, for weighting)
Definition at line 469 of file surfaceFieldValue.H.
operationType
enum operationType
Enumerator
opNone
No operation.
opMin
Minimum value.
opMax
Maximum value.
opSum
Sum of values.
opSumMag
Sum of component magnitudes.
opSumDirection
Sum in a given direction.
opSumDirectionBalance
Sum of balance of values in given direction.
opAverage
Ensemble average.
opAreaAverage
Area average.
opAreaIntegrate
Area integral.
opCoV
Coefficient of variation.
opAreaNormalAverage
Area average in normal direction (output is always scalar)
opAreaNormalIntegrate
Area integral in normal direction (output is always scalar)
opUniformity
Uniformity index (output is always scalar)
opWeightedSum
Weighted sum.
opWeightedAverage
Weighted average.
opWeightedAreaAverage
Weighted area average.
opWeightedAreaIntegrate
Weighted area integral.
opWeightedUniformity
Weighted uniformity index.
opAbsWeightedSum
Sum using abs weighting.
opAbsWeightedAverage
Average using abs weighting.
opAbsWeightedAreaAverage
Area average using abs weighting.
opAbsWeightedAreaIntegrate
Area integral using abs weighting.
opAbsWeightedUniformity
Uniformity index using abs weighting.
Definition at line 478 of file surfaceFieldValue.H.
postOperationType
enum postOperationType
Enumerator
postOpNone
No additional operation after calculation.
postOpMag
Component-wise mag after normal operation.
postOpSqrt
Component-wise sqrt after normal operation.
Definition at line 550 of file surfaceFieldValue.H.
Constructor & Destructor Documentation
surfaceFieldValue() [1/3]
surfaceFieldValue (const word & name, const Time & runTime, const dictionary & dict)
Definition at line 909 of file surfaceFieldValue.C.
References fieldValue::dict(), and surfaceFieldValue::read().
surfaceFieldValue() [2/3]
surfaceFieldValue (const word & name, const objectRegistry & obr, const dictionary & dict)
Definition at line 943 of file surfaceFieldValue.C.
References fieldValue::dict(), and surfaceFieldValue::read().
surfaceFieldValue() [3/3]
surfaceFieldValue (const surfaceFieldValue &) delete
~surfaceFieldValue()
~surfaceFieldValue () virtual
Definition at line 980 of file surfaceFieldValue.C.
Member Function Documentation
weightingFactor() [1/9]
template<class WeightType > static tmp< scalarField > weightingFactor (const Field< WeightType > & weightField, const bool useMag) static protected
weightingFactor() [2/9]
template<class WeightType > static tmp< scalarField > weightingFactor (const Field< WeightType > & weightField, const vectorField & Sf, const bool useMag) static protected
areaWeightingFactor() [1/5]
template<class WeightType > static tmp< scalarField > areaWeightingFactor (const Field< WeightType > & weightField, const vectorField & Sf, const bool useMag) static protected
obr()
const Foam::objectRegistry & obr () const protected virtual
Reimplemented from regionFunctionObject.
Definition at line 112 of file surfaceFieldValue.C.
References objectRegistry::lookupObject(), fvMeshFunctionObject::mesh_, fieldValue::regionName_, surfaceFieldValue::regionType_, surfaceFieldValue::stObject, and timeFunctionObject::storedObjects().
withSurfaceFields()
bool withSurfaceFields () const inline protected
Definition at line 27 of file surfaceFieldValueI.H.
References surfaceFieldValue::regionType_, surfaceFieldValue::sampledPtr_, surfaceFieldValue::stFaceZone, and surfaceFieldValue::stPatch.
withTopologicalMerge()
bool withTopologicalMerge () const inline protected noexcept
Definition at line 39 of file surfaceFieldValueI.H.
faceId()
const Foam::labelList & faceId () const inline protected noexcept
Definition at line 47 of file surfaceFieldValueI.H.
facePatch()
const Foam::labelList & facePatch () const inline protected noexcept
Definition at line 55 of file surfaceFieldValueI.H.
faceFlip()
const Foam::boolList & faceFlip () const inline protected noexcept
Definition at line 63 of file surfaceFieldValueI.H.
usesSf()
bool usesSf () const protected noexcept
Definition at line 479 of file surfaceFieldValue.C.
is_magOp()
bool is_magOp () const inline protected noexcept
Definition at line 72 of file surfaceFieldValueI.H.
is_weightedOp()
bool is_weightedOp () const inline protected noexcept
Definition at line 81 of file surfaceFieldValueI.H.
canWeight()
template<class WeightType > bool canWeight (const Field< WeightType > & fld) const inline protected
Definition at line 50 of file surfaceFieldValueTemplates.C.
References fld(), and Foam::returnReduceOr().
update()
bool update () protected
Definition at line 499 of file surfaceFieldValue.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Log, Foam::name(), Foam::nl, Foam::returnReduce(), s(), and Foam::type().
validField()
template<class Type > bool validField (const word & fieldName) const protected
Definition at line 61 of file surfaceFieldValueTemplates.C.
getFieldValues() [1/2]
template<class Type > tmp< Field< Type > > getFieldValues (const word & fieldName, const bool mandatory = false) const protected
processSameTypeValues()
template<class Type , class WeightType > Type processSameTypeValues (const Field< Type > & values, const vectorField & Sf, const Field< WeightType > & weightField) const protected
Definition at line 131 of file surfaceFieldValueTemplates.C.
References Foam::cmptMag(), Foam::component(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::gMax(), Foam::gMin(), Foam::gSum(), n, Foam::returnReduce(), Foam::setComponent(), Foam::sqr(), Foam::sqrt(), and Foam::Zero.
processValues() [1/5]
template<class Type , class WeightType > Type processValues (const Field< Type > & values, const vectorField & Sf, const Field< WeightType > & weightField) const protected
Definition at line 310 of file surfaceFieldValueTemplates.C.
filterField() [1/4]
template<class Type > tmp< Field< Type > > filterField (const GeometricField< Type, fvsPatchField, surfaceMesh > & field) const protected
filterField() [2/4]
template<class Type > tmp< Field< Type > > filterField (const GeometricField< Type, fvPatchField, volMesh > & field) const protected
writeAll() [1/2]
template<class WeightType > label writeAll (const vectorField & Sf, const Field< WeightType > & weightField, const pointField & points, const faceList & faces) protected
writeValues()
template<class Type , class WeightType > bool writeValues (const word & fieldName, const vectorField & Sf, const Field< WeightType > & weightField, const pointField & points, const faceList & faces) protected
Definition at line 403 of file surfaceFieldValueTemplates.C.
References dictionary::add(), Foam::component(), Foam::endl(), Log, UPstream::master(), outputName(), propsDict(), Foam::setComponent(), Foam::sqrt(), and Foam::tab.
writeFileHeader()
void writeFileHeader (Ostream & os) protected virtual
Definition at line 559 of file surfaceFieldValue.C.
References Foam::endl(), Foam::flatOutput(), Foam::nl, os(), and Foam::tab.
TypeName()
TypeName ("surfaceFieldValue")
operator=()
void operator= (const surfaceFieldValue &) delete
regionType()
Foam::functionObjects::fieldValues::surfaceFieldValue::regionTypes regionType () const inline noexcept
Definition at line 90 of file surfaceFieldValueI.H.
outputDir()
Foam::fileName outputDir () const inline
Definition at line 98 of file surfaceFieldValueI.H.
References Foam::name().
read()
bool read (const dictionary & dict) virtual
Reimplemented from fieldValue.
Definition at line 986 of file surfaceFieldValue.C.
References PtrList< T >::clear(), dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, UPtrList< T >::first(), Foam::flatOutput(), surfaceWriter::formatOptions(), UPtrList< T >::get(), Foam::Info, keyType::LITERAL, IOobjectOption::MUST_READ, Foam::name(), sampledSurface::New(), surfaceWriter::New(), Foam::nl, fieldValue::read(), IOobjectOption::READ_IF_PRESENT, PtrList< T >::resize(), and Foam::type().
Referenced by surfaceFieldValue::surfaceFieldValue(), and surfaceFieldValue::surfaceFieldValue().
write()
bool write () virtual
Reimplemented from fieldValue.
Definition at line 1168 of file surfaceFieldValue.C.
References UPtrList< T >::empty(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, Foam::flatOutput(), Log, UPstream::master(), Foam::nl, points, Foam::returnReduceOr(), s(), UPtrList< T >::size(), Foam::tab, update(), and fieldValue::write().
updateMesh()
void updateMesh (const mapPolyMesh & mpm) virtual
Reimplemented from functionObject.
Definition at line 1312 of file surfaceFieldValue.C.
movePoints()
void movePoints (const polyMesh & mesh) virtual
Reimplemented from functionObject.
Definition at line 1321 of file surfaceFieldValue.C.
processValues() [2/5]
template<> Foam::scalar processValues (const Field< scalar > & values, const vectorField & Sf, const scalarField & weightField) const
Definition at line 606 of file surfaceFieldValue.C.
References Foam::clamp(), Foam::gSum(), n, Foam::neg(), and Foam::pos0().
processValues() [3/5]
template<> Foam::vector processValues (const Field< vector > & values, const vectorField & Sf, const scalarField & weightField) const
Definition at line 680 of file surfaceFieldValue.C.
References Foam::clamp(), Foam::gSum(), n, Vector< Cmpt >::normalise(), and Foam::pos0().
weightingFactor() [3/9]
template<> Foam::tmp< Foam::scalarField > weightingFactor (const Field< scalar > & weightField, const bool useMag)
Definition at line 768 of file surfaceFieldValue.C.
weightingFactor() [4/9]
template<> Foam::tmp< Foam::scalarField > weightingFactor (const Field< scalar > & weightField, const vectorField & Sf, const bool useMag)
if (returnReduceAnd(weightField.empty())) { // No weight field - revert to unweighted form? return tmp<scalarField>::New(Sf.size(), scalar(1)); }
Definition at line 786 of file surfaceFieldValue.C.
areaWeightingFactor() [2/5]
template<> Foam::tmp< Foam::scalarField > areaWeightingFactor (const Field< scalar > & weightField, const vectorField & Sf, const bool useMag)
if (returnReduceAnd(weightField.empty())) { // No weight field - revert to unweighted form return mag(Sf); }
Definition at line 814 of file surfaceFieldValue.C.
weightingFactor() [5/9]
template<> Foam::tmp< Foam::scalarField > weightingFactor (const Field< vector > & weightField, const vectorField & Sf, const bool useMag)
if (returnReduceAnd(weightField.empty())) { // No weight field - revert to unweighted form return tmp<scalarField>::New(Sf.size(), scalar(1)); }
Definition at line 841 of file surfaceFieldValue.C.
References tmp< T >::New(), Foam::normalised(), and UPtrList< T >::size().
areaWeightingFactor() [3/5]
template<> Foam::tmp< Foam::scalarField > areaWeightingFactor (const Field< vector > & weightField, const vectorField & Sf, const bool useMag)
if (returnReduceAnd(weightField.empty())) { // No weight field - revert to unweighted form return mag(Sf); }
Definition at line 882 of file surfaceFieldValue.C.
processValues() [4/5]
template<> scalar processValues (const Field< scalar > & values, const vectorField & Sf, const scalarField & weightField) const
processValues() [5/5]
template<> vector processValues (const Field< vector > & values, const vectorField & Sf, const scalarField & weightField) const
weightingFactor() [6/9]
template<> tmp< scalarField > weightingFactor (const Field< scalar > & weightField, const bool useMag)
weightingFactor() [7/9]
template<> tmp< scalarField > weightingFactor (const Field< scalar > & weightField, const vectorField & Sf, const bool useMag)
areaWeightingFactor() [4/5]
template<> tmp< scalarField > areaWeightingFactor (const Field< scalar > & weightField, const vectorField & Sf, const bool useMag)
weightingFactor() [8/9]
template<> tmp< scalarField > weightingFactor (const Field< vector > & weightField, const vectorField & Sf, const bool useMag)
areaWeightingFactor() [5/5]
template<> tmp< scalarField > areaWeightingFactor (const Field< vector > & weightField, const vectorField & Sf, const bool useMag)
weightingFactor() [9/9]
template<class WeightType > Foam::tmp< Foam::scalarField > weightingFactor (const Field< WeightType > & weightField, const bool useMag)
Definition at line 35 of file surfaceFieldValueTemplates.C.
getFieldValues() [2/2]
template<class Type > Foam::tmp< Foam::Field< Type > > getFieldValues (const word & fieldName, const bool mandatory) const
Definition at line 81 of file surfaceFieldValueTemplates.C.
References Foam::FatalError, FatalErrorInFunction, fld(), Foam::New(), and Foam::nl.
writeAll() [2/2]
template<class WeightType > Foam::label writeAll (const vectorField & Sf, const Field< WeightType > & weightField, const pointField & points, const faceList & faces)
Definition at line 322 of file surfaceFieldValueTemplates.C.
References PtrList< T >::clear(), Foam::endl(), UPstream::master(), points, WarningInFunction, Ostream::write(), and writer().
filterField() [3/4]
template<class Type > Foam::tmp< Foam::Field< Type > > filterField (const GeometricField< Type, fvPatchField, volMesh > & field) const
Definition at line 532 of file surfaceFieldValueTemplates.C.
References field(), forAll, and Foam::New().
filterField() [4/4]
template<class Type > Foam::tmp< Foam::Field< Type > > filterField (const GeometricField< Type, fvsPatchField, surfaceMesh > & field) const
Definition at line 568 of file surfaceFieldValueTemplates.C.
References Foam::endl(), field(), forAll, OSstream::name(), Foam::New(), and Foam::Pout.
Member Data Documentation
regionTypeNames_
const Foam::Enum< Foam::functionObjects::fieldValues::surfaceFieldValue::regionTypes > regionTypeNames_ static
Definition at line 466 of file surfaceFieldValue.H.
operationTypeNames_
const Foam::Enum< Foam::functionObjects::fieldValues::surfaceFieldValue::operationType > operationTypeNames_ static
Definition at line 546 of file surfaceFieldValue.H.
postOperationTypeNames_
const Foam::Enum< Foam::functionObjects::fieldValues::surfaceFieldValue::postOperationType > postOperationTypeNames_ static
Definition at line 558 of file surfaceFieldValue.H.
regionType_
regionTypes regionType_ protected
Definition at line 594 of file surfaceFieldValue.H.
Referenced by surfaceFieldValue::obr(), and surfaceFieldValue::withSurfaceFields().
operation_
operationType operation_ protected
Definition at line 597 of file surfaceFieldValue.H.
postOperation_
postOperationType postOperation_ protected
Definition at line 600 of file surfaceFieldValue.H.
needsUpdate_
bool needsUpdate_ protected
Definition at line 603 of file surfaceFieldValue.H.
writeArea_
bool writeArea_ protected
Definition at line 606 of file surfaceFieldValue.H.
selectionNames_
wordRes selectionNames_ protected
Definition at line 609 of file surfaceFieldValue.H.
weightFieldNames_
wordList weightFieldNames_ protected
Definition at line 612 of file surfaceFieldValue.H.
totalArea_
scalar totalArea_ protected
Definition at line 615 of file surfaceFieldValue.H.
nFaces_
label nFaces_ protected
Definition at line 618 of file surfaceFieldValue.H.
faceId_
labelList faceId_ protected
Definition at line 624 of file surfaceFieldValue.H.
facePatchId_
labelList facePatchId_ protected
Definition at line 627 of file surfaceFieldValue.H.
faceFlip_
boolList faceFlip_ protected
Definition at line 631 of file surfaceFieldValue.H.
sampledPtr_
autoPtr<sampledSurface> sampledPtr_ protected
Definition at line 637 of file surfaceFieldValue.H.
Referenced by surfaceFieldValue::withSurfaceFields().
surfaceWriterPtr_
autoPtr<surfaceWriter> surfaceWriterPtr_ protected
Definition at line 640 of file surfaceFieldValue.H.
The documentation for this class was generated from the following files:
src/functionObjects/field/fieldValues/surfaceFieldValue/surfaceFieldValue.H
src/functionObjects/field/fieldValues/surfaceFieldValue/surfaceFieldValue.C
src/functionObjects/field/fieldValues/surfaceFieldValue/surfaceFieldValueI.H
src/functionObjects/field/fieldValues/surfaceFieldValue/surfaceFieldValueTemplates.C