OpenFOAM: pointPatchField< Type > Class Template Reference
pointPatchField< Type > Class Template Reference abstract
Abstract base class for point-mesh patch fields.
#include <pointPatchField.H>
Public Types
typedef Type value_type
typedef DimensionedField< Type, pointMesh > Internal
typedef pointPatch Patch
typedef calculatedPointPatchField< Type > Calculated
Public Member Functions
declareRunTimeSelectionTable (autoPtr, pointPatchField, patch,(const pointPatch &p, const DimensionedField< Type, pointMesh > &iF),(p, iF))
declareRunTimeSelectionTable (autoPtr, pointPatchField, patchMapper,(const pointPatchField< Type > &ptf, const pointPatch &p, const DimensionedField< Type, pointMesh > &iF, const pointPatchFieldMapper &m),(dynamic_cast< const pointPatchFieldType & >(ptf), p, iF, m))
declareRunTimeSelectionTable (autoPtr, pointPatchField, dictionary,(const pointPatch &p, const DimensionedField< Type, pointMesh > &iF, const dictionary &dict),(p, iF, dict))
pointPatchField (const pointPatch &, const DimensionedField< Type, pointMesh > &)
pointPatchField (const pointPatch &, const DimensionedField< Type, pointMesh > &, const dictionary &)
pointPatchField (const pointPatchField< Type > &, const pointPatch &, const DimensionedField< Type, pointMesh > &, const pointPatchFieldMapper &)
pointPatchField (const pointPatchField< Type > &)
pointPatchField (const pointPatchField< Type > &, const DimensionedField< Type, pointMesh > &)
virtual autoPtr< pointPatchField< Type > > clone () const =0
virtual autoPtr< pointPatchField< Type > > clone (const DimensionedField< Type, pointMesh > &iF) const =0
virtual ~pointPatchField ()=default
label size () const
const DimensionedField< Type, pointMesh > & internalField () const noexcept
const Field< Type > & primitiveField () const noexcept
tmp< Field< Type > > patchInternalField () const
template<class Type1 >
tmp< Field< Type1 > > patchInternalField (const Field< Type1 > &iF) const
template<class Type1 >
tmp< Field< Type1 > > patchInternalField (const Field< Type1 > &iF, const labelUList &meshPoints) const
template<class Type1 >
void addToInternalField (Field< Type1 > &iF, const Field< Type1 > &pF) const
template<class Type1 >
void addToInternalField (Field< Type1 > &iF, const Field< Type1 > &pF, const labelUList &points) const
template<class Type1 >
void setInInternalField (Field< Type1 > &iF, const Field< Type1 > &pF, const labelUList &meshPoints) const
template<class Type1 >
void setInInternalField (Field< Type1 > &iF, const Field< Type1 > &pF) const
virtual void autoMap (const pointPatchFieldMapper &)
virtual void rmap (const pointPatchField< Type > &, const labelList &)
virtual void updateCoeffs ()
virtual void initEvaluate (const Pstream::commsTypes commsType=Pstream::commsTypes::blocking)
virtual void evaluate (const Pstream::commsTypes commsType=Pstream::commsTypes::blocking)
virtual void write (Ostream &os) const
virtual void operator= (const pointPatchField< Type > &)
virtual void operator+= (const pointPatchField< Type > &)
virtual void operator-= (const pointPatchField< Type > &)
virtual void operator*= (const pointPatchField< scalar > &)
virtual void operator/= (const pointPatchField< scalar > &)
virtual void operator= (const Field< Type > &)
virtual void operator+= (const Field< Type > &)
virtual void operator-= (const Field< Type > &)
virtual void operator*= (const Field< scalar > &)
virtual void operator/= (const Field< scalar > &)
virtual void operator= (const Type &)
virtual void operator+= (const Type &)
virtual void operator-= (const Type &)
virtual void operator*= (const scalar)
virtual void operator/= (const scalar)
virtual void operator== (const pointPatchField< Type > &)
virtual void operator== (const Field< Type > &)
virtual void operator== (const Type &)
void negate ()
void normalise ()
template<class Type2 >
Foam::autoPtr< Foam::pointPatchField< Type > > NewCalculatedType (const pointPatchField< Type2 > &pf)
template<class Type1 >
Foam::tmp< Foam::Field< Type1 > > patchInternalField (const Field< Type1 > &iF, const labelUList &meshPoints) const
template<class Type1 >
Foam::tmp< Foam::Field< Type1 > > patchInternalField (const Field< Type1 > &iF) const
Public Member Functions inherited from pointPatchFieldBase
TypeName ("pointPatchField")
pointPatchFieldBase (const pointPatch &p)
pointPatchFieldBase (const pointPatch &p, const word &patchType)
pointPatchFieldBase (const pointPatch &p, const dictionary &dict)
pointPatchFieldBase (const pointPatchFieldBase &, const pointPatch &p)
pointPatchFieldBase (const pointPatchFieldBase &)
virtual ~pointPatchFieldBase ()=default
virtual bool fixesValue () const
virtual bool coupled () const
virtual const word & constraintType () const
const objectRegistry & db () const
const pointPatch & patch () const noexcept
const word & patchType () const noexcept
word & patchType () noexcept
bool updated () const noexcept
bool manipulatedMatrix () const noexcept
void checkPatch (const pointPatchFieldBase &rhs) const
Static Public Member Functions
static autoPtr< pointPatchField< Type > > New (const word &patchFieldType, const pointPatch &p, const DimensionedField< Type, pointMesh > &iF)
static autoPtr< pointPatchField< Type > > New (const word &patchFieldType, const word &actualPatchType, const pointPatch &p, const DimensionedField< Type, pointMesh > &iF)
static autoPtr< pointPatchField< Type > > New (const pointPatchField< Type > &, const pointPatch &, const DimensionedField< Type, pointMesh > &, const pointPatchFieldMapper &)
static autoPtr< pointPatchField< Type > > New (const pointPatch &, const DimensionedField< Type, pointMesh > &, const dictionary &)
template<class Type2 >
static autoPtr< pointPatchField< Type > > NewCalculatedType (const pointPatchField< Type2 > &)
Static Public Member Functions inherited from pointPatchFieldBase
static const word & emptyType () noexcept
static const word & calculatedType () noexcept
static const word & zeroGradientType () noexcept
Friends
Ostream & operator<< (Ostream &, const pointPatchField< Type > &)
Additional Inherited Members
Static Public Attributes inherited from pointPatchFieldBase
static int disallowGenericPatchField
Protected Member Functions inherited from pointPatchFieldBase
virtual void readDict (const dictionary &dict)
void setUpdated (bool state) noexcept
void setManipulated (bool state) noexcept
Detailed Description
template<class Type>
class Foam::pointPatchField< Type >
Abstract base class for point-mesh patch fields.
The base-field does not store values as they are part of the "internal field". There are derived classes to store constraint values e.g. fixedValuePointPatchField derived from the generic valuePointPatchField which ensures the values in the "internal field" are reset to the fixed-values by applying the stored values.
Source files
pointPatchField.H
pointPatchField.C
pointPatchFieldNew.C
Definition at line 236 of file pointPatchField.H.
Member Typedef Documentation
value_type
template<class Type > typedef Type value_type
Definition at line 249 of file pointPatchField.H.
Internal
template<class Type > typedef DimensionedField<Type, pointMesh> Internal
Definition at line 252 of file pointPatchField.H.
Patch
template<class Type > typedef pointPatch Patch
Definition at line 255 of file pointPatchField.H.
Calculated
template<class Type > typedef calculatedPointPatchField<Type> Calculated
Definition at line 258 of file pointPatchField.H.
Constructor & Destructor Documentation
pointPatchField() [1/5]
template<class Type > pointPatchField (const pointPatch & p, const DimensionedField< Type, pointMesh > & iF)
Definition at line 29 of file pointPatchField.C.
pointPatchField() [2/5]
template<class Type > pointPatchField (const pointPatch & p, const DimensionedField< Type, pointMesh > & iF, const dictionary & dict)
Definition at line 41 of file pointPatchField.C.
pointPatchField() [3/5]
template<class Type > pointPatchField (const pointPatchField< Type > & ptf, const pointPatch & p, const DimensionedField< Type, pointMesh > & iF, const pointPatchFieldMapper &)
Definition at line 54 of file pointPatchField.C.
pointPatchField() [4/5]
template<class Type > pointPatchField (const pointPatchField< Type > & ptf)
Definition at line 68 of file pointPatchField.C.
pointPatchField() [5/5]
template<class Type > pointPatchField (const pointPatchField< Type > & ptf, const DimensionedField< Type, pointMesh > & iF)
Definition at line 79 of file pointPatchField.C.
~pointPatchField()
template<class Type > virtual ~pointPatchField () virtual default
Member Function Documentation
declareRunTimeSelectionTable() [1/3]
template<class Type > declareRunTimeSelectionTable (autoPtr , pointPatchField< Type > , patch , (const pointPatch &p, const DimensionedField< Type, pointMesh > &iF) , (p, iF))
declareRunTimeSelectionTable() [2/3]
template<class Type > declareRunTimeSelectionTable (autoPtr , pointPatchField< Type > , patchMapper , (const pointPatchField< Type > &ptf, const pointPatch &p, const DimensionedField< Type, pointMesh > &iF, const pointPatchFieldMapper &m) , (dynamic_cast< const pointPatchFieldType & >(ptf), p, iF, m))
declareRunTimeSelectionTable() [3/3]
template<class Type > declareRunTimeSelectionTable (autoPtr , pointPatchField< Type > , dictionary , (const pointPatch &p, const DimensionedField< Type, pointMesh > &iF, const dictionary &dict) , (p, iF, dict))
clone() [1/2]
template<class Type > virtual autoPtr< pointPatchField< Type > > clone () const pure virtual
Implemented in exprValuePointPatchField< Type >, angularOscillatingDisplacementPointPatchVectorField, angularOscillatingVelocityPointPatchVectorField, oscillatingDisplacementPointPatchVectorField, oscillatingVelocityPointPatchVectorField, surfaceSlipDisplacementPointPatchVectorField, timeVaryingMappedFixedValuePointPatchField< Type >, uniformInterpolatedDisplacementPointPatchVectorField, waveDisplacementPointPatchVectorField, genericPointPatchField< Type >, lumpedPointDisplacementPointPatchVectorField, zeroFixedValuePointPatchField< Type >, cyclicACMIPointPatchField< Type >, cyclicAMIPointPatchField< Type >, uniformFixedValuePointPatchField< Type >, basicSymmetryPointPatchField< Type >, calculatedPointPatchField< Type >, fixedValuePointPatchField< Type >, fixedValuePointPatchField< vector >, valuePointPatchField< Type >, valuePointPatchField< vector >, zeroGradientPointPatchField< Type >, cyclicPointPatchField< Type >, cyclicSlipPointPatchField< Type >, emptyPointPatchField< Type >, nonuniformTransformCyclicPointPatchField< Type >, processorPointPatchField< Type >, processorCyclicPointPatchField< Type >, symmetryPointPatchField< Type >, symmetryPlanePointPatchField< Type >, wedgePointPatchField< Type >, codedFixedValuePointPatchField< Type >, fixedNormalSlipPointPatchField< Type >, slipPointPatchField< Type >, timeVaryingUniformFixedValuePointPatchField< Type >, sixDoFRigidBodyDisplacementPointPatchVectorField, uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField, waveMakerPointPatchVectorField, and coupledPointPatchField< Type >.
clone() [2/2]
template<class Type > virtual autoPtr< pointPatchField< Type > > clone (const DimensionedField< Type, pointMesh > & iF) const pure virtual
Implemented in exprValuePointPatchField< Type >, timeVaryingMappedFixedValuePointPatchField< Type >, genericPointPatchField< Type >, zeroFixedValuePointPatchField< Type >, cyclicACMIPointPatchField< Type >, cyclicAMIPointPatchField< Type >, uniformFixedValuePointPatchField< Type >, basicSymmetryPointPatchField< Type >, calculatedPointPatchField< Type >, fixedValuePointPatchField< Type >, valuePointPatchField< Type >, zeroGradientPointPatchField< Type >, cyclicPointPatchField< Type >, cyclicSlipPointPatchField< Type >, emptyPointPatchField< Type >, nonuniformTransformCyclicPointPatchField< Type >, processorPointPatchField< Type >, processorCyclicPointPatchField< Type >, symmetryPointPatchField< Type >, symmetryPlanePointPatchField< Type >, wedgePointPatchField< Type >, codedFixedValuePointPatchField< Type >, fixedNormalSlipPointPatchField< Type >, slipPointPatchField< Type >, timeVaryingUniformFixedValuePointPatchField< Type >, coupledPointPatchField< Type >, and surfaceSlipDisplacementPointPatchVectorField.
New() [1/4]
template<class Type > Foam::autoPtr< Foam::pointPatchField< Type > > New (const word & patchFieldType, const pointPatch & p, const DimensionedField< Type, pointMesh > & iF) static
Definition at line 86 of file pointPatchFieldNew.C.
References Foam::New(), word::null, and p.
New() [2/4]
template<class Type > Foam::autoPtr< Foam::pointPatchField< Type > > New (const word & patchFieldType, const word & actualPatchType, const pointPatch & p, const DimensionedField< Type, pointMesh > & iF) static
Definition at line 25 of file pointPatchFieldNew.C.
References DebugInFunction, UPtrList< T >::empty(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, FatalErrorInLookup, p, and PtrList< T >::PtrList().
New() [3/4]
template<class Type > Foam::autoPtr< Foam::pointPatchField< Type > > New (const pointPatchField< Type > & ptf, const pointPatch & p, const DimensionedField< Type, pointMesh > & iF, const pointPatchFieldMapper & pfMapper) static
Definition at line 165 of file pointPatchFieldNew.C.
References DebugInFunction, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInLookup, IOobject::name(), and p.
New() [4/4]
template<class Type > Foam::autoPtr< Foam::pointPatchField< Type > > New (const pointPatch & p, const DimensionedField< Type, pointMesh > & iF, const dictionary & dict) static
Definition at line 98 of file pointPatchFieldNew.C.
References DebugInFunction, dict, pointPatchFieldBase::disallowGenericPatchField, UPtrList< T >::empty(), Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, dictionary::get(), keyType::LITERAL, IOobject::name(), Foam::nl, p, and dictionary::readIfPresent().
NewCalculatedType() [1/2]
template<class Type > template<class Type2 > static autoPtr< pointPatchField< Type > > NewCalculatedType (const pointPatchField< Type2 > &) static
size()
template<class Type > label size () const inline
Definition at line 411 of file pointPatchField.H.
References pointPatchFieldBase::patch(), and UPtrList< T >::size().
Referenced by genericPointPatchField< Type >::genericPointPatchField().
internalField()
template<class Type > const DimensionedField< Type, pointMesh > & internalField () const inline noexcept
Definition at line 417 of file pointPatchField.H.
Referenced by genericPointPatchField< Type >::genericPointPatchField(), genericPointPatchField< Type >::genericPointPatchField(), angularOscillatingDisplacementPointPatchVectorField::updateCoeffs(), angularOscillatingVelocityPointPatchVectorField::updateCoeffs(), oscillatingDisplacementPointPatchVectorField::updateCoeffs(), oscillatingVelocityPointPatchVectorField::updateCoeffs(), uniformInterpolatedDisplacementPointPatchVectorField::updateCoeffs(), sixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs(), and uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs().
primitiveField()
template<class Type > const Field< Type > & primitiveField () const inline noexcept
Definition at line 423 of file pointPatchField.H.
patchInternalField() [1/5]
template<class Type > Foam::tmp< Foam::Field< Type > > patchInternalField () const
Definition at line 106 of file pointPatchField.C.
Referenced by velocityDisplacementMotionSolver::solve(), and uniformInterpolatedDisplacementPointPatchVectorField::updateCoeffs().
patchInternalField() [2/5]
template<class Type > template<class Type1 > tmp< Field< Type1 > > patchInternalField (const Field< Type1 > & iF) const
patchInternalField() [3/5]
template<class Type > template<class Type1 > tmp< Field< Type1 > > patchInternalField (const Field< Type1 > & iF, const labelUList & meshPoints) const
addToInternalField() [1/2]
template<class Type > template<class Type1 > void addToInternalField (Field< Type1 > & iF, const Field< Type1 > & pF) const
Definition at line 149 of file pointPatchField.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, and UPtrList< T >::size().
addToInternalField() [2/2]
template<class Type > template<class Type1 > void addToInternalField (Field< Type1 > & iF, const Field< Type1 > & pF, const labelUList & points) const
Definition at line 186 of file pointPatchField.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, points, and UPtrList< T >::size().
setInInternalField() [1/2]
template<class Type > template<class Type1 > void setInInternalField (Field< Type1 > & iF, const Field< Type1 > & pF, const labelUList & meshPoints) const
Definition at line 225 of file pointPatchField.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, UPtrList< T >::size(), and UList< T >::size().
setInInternalField() [2/2]
template<class Type > template<class Type1 > void setInInternalField (Field< Type1 > & iF, const Field< Type1 > & pF) const
Definition at line 260 of file pointPatchField.C.
autoMap()
template<class Type > virtual void autoMap (const pointPatchFieldMapper &) inline virtual
Reimplemented in angularOscillatingDisplacementPointPatchVectorField, angularOscillatingVelocityPointPatchVectorField, oscillatingVelocityPointPatchVectorField, timeVaryingMappedFixedValuePointPatchField< Type >, genericPointPatchField< Type >, uniformFixedValuePointPatchField< Type >, valuePointPatchField< Type >, valuePointPatchField< vector >, sixDoFRigidBodyDisplacementPointPatchVectorField, and uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField.
Definition at line 493 of file pointPatchField.H.
rmap()
template<class Type > virtual void rmap (const pointPatchField< Type > & , const labelList &) inline virtual
Reimplemented in timeVaryingMappedFixedValuePointPatchField< Type >, genericPointPatchField< Type >, uniformFixedValuePointPatchField< Type >, valuePointPatchField< Type >, and valuePointPatchField< vector >.
Definition at line 500 of file pointPatchField.H.
updateCoeffs()
template<class Type > void updateCoeffs () virtual
Reimplemented in exprValuePointPatchField< Type >, angularOscillatingDisplacementPointPatchVectorField, angularOscillatingVelocityPointPatchVectorField, oscillatingDisplacementPointPatchVectorField, oscillatingVelocityPointPatchVectorField, timeVaryingMappedFixedValuePointPatchField< Type >, uniformInterpolatedDisplacementPointPatchVectorField, waveDisplacementPointPatchVectorField, lumpedPointDisplacementPointPatchVectorField, uniformFixedValuePointPatchField< Type >, valuePointPatchField< Type >, valuePointPatchField< vector >, codedFixedValuePointPatchField< Type >, timeVaryingUniformFixedValuePointPatchField< Type >, sixDoFRigidBodyDisplacementPointPatchVectorField, uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField, and waveMakerPointPatchVectorField.
Definition at line 271 of file pointPatchField.C.
References pointPatchFieldBase::setUpdated().
initEvaluate()
template<class Type > virtual void initEvaluate (const Pstream::commsTypes commsType = Pstream::commsTypes::blocking) inline virtual
Definition at line 515 of file pointPatchField.H.
evaluate()
template<class Type > void evaluate (const Pstream::commsTypes commsType = Pstream::commsTypes::blocking) virtual
Reimplemented in surfaceSlipDisplacementPointPatchVectorField, cyclicACMIPointPatchField< Type >, cyclicAMIPointPatchField< Type >, basicSymmetryPointPatchField< Type >, valuePointPatchField< Type >, valuePointPatchField< vector >, cyclicPointPatchField< Type >, cyclicSlipPointPatchField< Type >, nonuniformTransformCyclicPointPatchField< Type >, processorPointPatchField< Type >, processorCyclicPointPatchField< Type >, symmetryPlanePointPatchField< Type >, wedgePointPatchField< Type >, codedFixedValuePointPatchField< Type >, fixedNormalSlipPointPatchField< Type >, and coupledPointPatchField< Type >.
Definition at line 278 of file pointPatchField.C.
References pointPatchFieldBase::setUpdated().
Referenced by valuePointPatchField< vector >::rmap(), and timeVaryingMappedFixedValuePointPatchField< Type >::timeVaryingMappedFixedValuePointPatchField().
write()
template<class Type > void write (Ostream & os) const virtual
Reimplemented in angularOscillatingDisplacementPointPatchVectorField, angularOscillatingVelocityPointPatchVectorField, oscillatingDisplacementPointPatchVectorField, oscillatingVelocityPointPatchVectorField, surfaceSlipDisplacementPointPatchVectorField, timeVaryingMappedFixedValuePointPatchField< Type >, uniformInterpolatedDisplacementPointPatchVectorField, waveDisplacementPointPatchVectorField, genericPointPatchField< Type >, uniformFixedValuePointPatchField< Type >, valuePointPatchField< Type >, valuePointPatchField< vector >, codedFixedValuePointPatchField< Type >, fixedNormalSlipPointPatchField< Type >, timeVaryingUniformFixedValuePointPatchField< Type >, sixDoFRigidBodyDisplacementPointPatchVectorField, uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField, waveMakerPointPatchVectorField, exprValuePointPatchField< Type >, and lumpedPointDisplacementPointPatchVectorField.
Definition at line 93 of file pointPatchField.C.
References os(), Foam::type(), and Ostream::writeEntry().
Referenced by angularOscillatingDisplacementPointPatchVectorField::write(), angularOscillatingVelocityPointPatchVectorField::write(), oscillatingDisplacementPointPatchVectorField::write(), oscillatingVelocityPointPatchVectorField::write(), surfaceSlipDisplacementPointPatchVectorField::write(), uniformInterpolatedDisplacementPointPatchVectorField::write(), waveDisplacementPointPatchVectorField::write(), fixedNormalSlipPointPatchField< Type >::write(), sixDoFRigidBodyDisplacementPointPatchVectorField::write(), uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField::write(), waveMakerPointPatchVectorField::write(), and lumpedPointDisplacementPointPatchVectorField::write().
operator=() [1/3]
template<class Type > virtual void operator= (const pointPatchField< Type > &) inline virtual
Reimplemented in valuePointPatchField< Type >, and valuePointPatchField< vector >.
Definition at line 536 of file pointPatchField.H.
operator+=() [1/3]
template<class Type > virtual void operator+= (const pointPatchField< Type > &) inline virtual
Definition at line 537 of file pointPatchField.H.
operator-=() [1/3]
template<class Type > virtual void operator-= (const pointPatchField< Type > &) inline virtual
Definition at line 538 of file pointPatchField.H.
operator*=() [1/3]
template<class Type > virtual void operator*= (const pointPatchField< scalar > &) inline virtual
Definition at line 539 of file pointPatchField.H.
operator/=() [1/3]
template<class Type > virtual void operator/= (const pointPatchField< scalar > &) inline virtual
Definition at line 540 of file pointPatchField.H.
operator=() [2/3]
template<class Type > virtual void operator= (const Field< Type > &) inline virtual
Reimplemented in fixedValuePointPatchField< Type >, valuePointPatchField< Type >, and valuePointPatchField< vector >.
Definition at line 542 of file pointPatchField.H.
operator+=() [2/3]
template<class Type > virtual void operator+= (const Field< Type > &) inline virtual
Definition at line 543 of file pointPatchField.H.
operator-=() [2/3]
template<class Type > virtual void operator-= (const Field< Type > &) inline virtual
Definition at line 544 of file pointPatchField.H.
operator*=() [2/3]
template<class Type > virtual void operator*= (const Field< scalar > &) inline virtual
Definition at line 546 of file pointPatchField.H.
operator/=() [2/3]
template<class Type > virtual void operator/= (const Field< scalar > &) inline virtual
Definition at line 547 of file pointPatchField.H.
operator=() [3/3]
template<class Type > virtual void operator= (const Type &) inline virtual
Reimplemented in fixedValuePointPatchField< Type >, valuePointPatchField< Type >, and valuePointPatchField< vector >.
Definition at line 549 of file pointPatchField.H.
operator+=() [3/3]
template<class Type > virtual void operator+= (const Type &) inline virtual
Definition at line 550 of file pointPatchField.H.
operator-=() [3/3]
template<class Type > virtual void operator-= (const Type &) inline virtual
Definition at line 551 of file pointPatchField.H.
operator*=() [3/3]
template<class Type > virtual void operator*= (const scalar) inline virtual
Definition at line 552 of file pointPatchField.H.
operator/=() [3/3]
template<class Type > virtual void operator/= (const scalar) inline virtual
Definition at line 553 of file pointPatchField.H.
operator==() [1/3]
template<class Type > virtual void operator== (const pointPatchField< Type > &) inline virtual
Reimplemented in valuePointPatchField< Type >, and valuePointPatchField< vector >.
Definition at line 560 of file pointPatchField.H.
operator==() [2/3]
template<class Type > virtual void operator== (const Field< Type > &) inline virtual
Reimplemented in valuePointPatchField< Type >, and valuePointPatchField< vector >.
Definition at line 561 of file pointPatchField.H.
operator==() [3/3]
template<class Type > virtual void operator== (const Type &) inline virtual
Reimplemented in valuePointPatchField< Type >, and valuePointPatchField< vector >.
Definition at line 562 of file pointPatchField.H.
negate()
template<class Type > void negate () inline
Definition at line 577 of file pointPatchField.H.
normalise()
template<class Type > void normalise () inline
Definition at line 580 of file pointPatchField.H.
NewCalculatedType() [2/2]
template<class Type > template<class Type2 > Foam::autoPtr< Foam::pointPatchField< Type > > NewCalculatedType (const pointPatchField< Type2 > & pf)
Definition at line 76 of file calculatedPointPatchField.C.
patchInternalField() [4/5]
template<class Type > template<class Type1 > Foam::tmp< Foam::Field< Type1 > > patchInternalField (const Field< Type1 > & iF, const labelUList & meshPoints) const
Definition at line 115 of file pointPatchField.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, Foam::New(), and UPtrList< T >::size().
patchInternalField() [5/5]
template<class Type > template<class Type1 > Foam::tmp< Foam::Field< Type1 > > patchInternalField (const Field< Type1 > & iF) const
Definition at line 138 of file pointPatchField.C.
Friends And Related Symbol Documentation
operator<<
template<class Type > Ostream & operator<< (Ostream & , const pointPatchField< Type > &) friend
The documentation for this class was generated from the following files:
src/finiteVolume/interpolation/interpolation/interpolationPointMVC/pointMVCWeight.H
src/OpenFOAM/fields/pointPatchFields/pointPatchField/pointPatchField.H
src/OpenFOAM/fields/pointPatchFields/basic/calculated/calculatedPointPatchField.C
src/OpenFOAM/fields/pointPatchFields/pointPatchField/pointPatchField.C
src/OpenFOAM/fields/pointPatchFields/pointPatchField/pointPatchFieldNew.C