OpenFOAM: wallDistAddressing Class Reference
wallDistAddressing Class Reference
Variant of wallDist that uses meshWave and stores the addressing.
#include <wallDistAddressing.H>
Public Member Functions
ClassName ("wallDistAddressing")
wallDistAddressing (const fvMesh &mesh, const bool correctWalls=true, const label updateInterval=1)
wallDistAddressing (const word &patchTypeName, const fvMesh &mesh, const labelList &patchIDs, const bool correctWalls=true, const label updateInterval=1)
virtual ~wallDistAddressing ()
const labelUList & patchIDs () const noexcept
const volScalarField & y () const noexcept
virtual bool movePoints ()
virtual void updateMesh (const mapPolyMesh &)
template<class Container , class Type >
tmp< Field< Type > > collectPatchFields (const Container &bfld) const
template<class VolField >
void extract (const Field< typename VolField::value_type > &patchFld, VolField &fld) const
template<class VolField , class TransformOp >
const VolField & map (VolField &fld, const TransformOp &top=mapDistribute::transform()) const
template<class Container , class Type >
Foam::tmp< Foam::Field< Type > > collectPatchFields (const Container &bfld) const
Public Member Functions inherited from MeshObject< fvMesh, UpdateableMeshObject, wallDistAddressing >
MeshObject (const fvMesh &mesh)
MeshObject (const word &objName, const fvMesh &mesh)
virtual ~MeshObject ()=default
const fvMesh & mesh () const noexcept
virtual bool writeData (Ostream &os) const
Public Member Functions inherited from cellDistFuncs
ClassName ("cellDistFuncs")
cellDistFuncs (const polyMesh &mesh)
const polyMesh & mesh () const
labelHashSet getPatchIDs (const UList< wordRe > &patchNames) const
template<class Type >
labelHashSet getPatchIDs () const
scalar smallestDist (const point &p, const polyPatch &patch, const labelUList &wallFaces, label &meshFacei) const
void getPointNeighbours (const primitivePatch &, const label patchFacei, DynamicList< label > &) const
label maxPatchSize (const labelHashSet &patchIDs) const
label sumPatchSize (const labelHashSet &patchIDs) const
void correctBoundaryFaceCells (const labelHashSet &patchIDs, scalarField &wallDistCorrected, Map< label > &nearestFace) const
void correctBoundaryPointCells (const labelHashSet &patchIDs, scalarField &wallDistCorrected, Map< label > &nearestFace) const
template<class Type >
Foam::labelHashSet getPatchIDs () const
Protected Member Functions
label getValues (const FaceCellWave< wallPointAddressing > &wave, const List< wallPointAddressing > &allCellInfo, const List< wallPointAddressing > &allFaceInfo, volScalarField &y) const
void addItem (const label item, const labelPair &data, label &untransformi, label &transformi, labelPairList &transformedWallInfo)
void correct (volScalarField &y)
wallDistAddressing (const wallDistAddressing &)=delete
void operator= (const wallDistAddressing &)=delete
Protected Attributes
const labelList patchIDs_
const word patchTypeName_
const label updateInterval_
const bool correctWalls_
bool requireUpdate_
volScalarField y_
autoPtr< globalIndex > globalWallsPtr_
autoPtr< mapDistribute > mapPtr_
labelList untransformedItems_
labelList untransformedSlots_
labelList untransformedPatchStarts_
labelList transformedItems_
labelList transformedSlots_
labelList transformedPatchStarts_
Protected Attributes inherited from MeshObject< fvMesh, UpdateableMeshObject, wallDistAddressing >
const fvMesh & mesh_
Additional Inherited Members
Static Public Member Functions inherited from MeshObject< fvMesh, UpdateableMeshObject, wallDistAddressing >
static const wallDistAddressing & New (const fvMesh &mesh, Args &&... args)
static const wallDistAddressing & New (const word &objName, const fvMesh &mesh, Args &&... args)
static bool Delete (const word &objName, const fvMesh &mesh)
static bool Delete (const fvMesh &mesh)
Detailed Description
Variant of wallDist that uses meshWave and stores the addressing.
Can be used to transport other wall properties. For example getting the nearest-wall normal into a volVectorField
    // If not yet constructed construct from all wall patches
    const auto& wDist = wallDistAddressing::New(mesh);
    // Fill boundaryField with normal
    for (const label patchi : wDist.patchIDs())
    {
        auto& pnf = n.boundaryFieldRef()[patchi];
        pnf == pnf.patch().nf();
    }
    // Map data from nearest wall (using transformation if nearest is
    // reached through a coupled patch with transformation)
    wDist.map(n, mapDistribute::transform());
Another use is e.g. to get the distance to cyclic patches. This enforces registration under the supplied name.
    // If not yet constructed construct from selected patches
    const labelList& patchIDs = ..
    const auto& wDist = wallDistAddressing::New
    (
        "myPatches",    // registration name
        mesh,
        patchIDs
    );
    // Fill boundaryField with normal
    for (const label patchi : wDist.patchIDs())
    {
        auto& pnf = n.boundaryFieldRef()[patchi];
        pnf == pnf.patch().nf();
    }
    // Map data from nearest patch face (using transformation if nearest is
    // reached through a coupled patch with transformation)
    wDist.map(n, mapDistribute::transform());
Note
By default (correctWalls = true) all cells point-connected to a wall explicitly search for the nearest location on the point-surrouding wall faces (so override the wave behaviour). This gets only done for processor-local wall faces.
See also
Foam::wallDist
Source files
wallDistAddressing.H
wallDistAddressing.C
Definition at line 107 of file wallDistAddressing.H.
Constructor & Destructor Documentation
wallDistAddressing() [1/3]
wallDistAddressing (const wallDistAddressing &) protected delete
wallDistAddressing() [2/3]
wallDistAddressing (const fvMesh & mesh, const bool correctWalls = true, const label updateInterval = 1) explicit
Definition at line 375 of file wallDistAddressing.C.
References wallDistAddressing::movePoints().
wallDistAddressing() [3/3]
wallDistAddressing (const word & patchTypeName, const fvMesh & mesh, const labelList & patchIDs, const bool correctWalls = true, const label updateInterval = 1)
Definition at line 407 of file wallDistAddressing.C.
References wallDistAddressing::movePoints().
~wallDistAddressing()
~wallDistAddressing () virtual
Definition at line 446 of file wallDistAddressing.C.
Member Function Documentation
getValues()
Foam::label getValues (const FaceCellWave< wallPointAddressing > & wave, const List< wallPointAddressing > & allCellInfo, const List< wallPointAddressing > & allFaceInfo, volScalarField & y) const protected
Definition at line 40 of file wallDistAddressing.C.
References forAll, UPtrList< T >::size(), Foam::sqrt(), wallDistAddressing::y(), and Foam::Zero.
addItem()
void addItem (const label item, const labelPair & data, label & untransformi, label & transformi, labelPairList & transformedWallInfo) protected
Definition at line 97 of file wallDistAddressing.C.
correct()
void correct (volScalarField & y) protected
Definition at line 126 of file wallDistAddressing.C.
References UPtrList< T >::back(), Foam::dimLength, Foam::dimless, Foam::endl(), Foam::flatOutput(), forAll, UPstream::myProcNo(), OFstream::name(), IOobjectOption::NO_REGISTER, os(), Foam::Pout, pp(), PtrList< T >::resize(), wallNormal, OBJstream::write(), y, and Foam::Zero.
operator=()
void operator= (const wallDistAddressing &) protected delete
ClassName()
ClassName ("wallDistAddressing")
patchIDs()
const labelUList & patchIDs () const inline noexcept
Definition at line 226 of file wallDistAddressing.H.
References wallDistAddressing::patchIDs_.
y()
const volScalarField & y () const inline noexcept
Definition at line 233 of file wallDistAddressing.H.
References wallDistAddressing::y_.
Referenced by wallDistAddressing::getValues().
movePoints()
bool movePoints () virtual
Definition at line 452 of file wallDistAddressing.C.
References correct(), DebugInfo, and Foam::endl().
Referenced by wallDistAddressing::wallDistAddressing(), and wallDistAddressing::wallDistAddressing().
updateMesh()
void updateMesh (const mapPolyMesh & mpm) virtual
Definition at line 478 of file wallDistAddressing.C.
collectPatchFields() [1/2]
template<class Container , class Type > tmp< Field< Type > > collectPatchFields (const Container & bfld) const
extract()
template<class VolField > void extract (const Field< typename VolField::value_type > & patchFld, VolField & fld) const
Definition at line 52 of file wallDistAddressingTemplates.C.
References fld(), forAll, and UPtrList< T >::size().
map()
template<class VolField , class TransformOp > const VolField & map (VolField & fld, const TransformOp & top = mapDistribute::transform()) const
Definition at line 123 of file wallDistAddressingTemplates.C.
References fld().
collectPatchFields() [2/2]
template<class Container , class Type > Foam::tmp< Foam::Field< Type > > collectPatchFields (const Container & bfld) const
Definition at line 25 of file wallDistAddressingTemplates.C.
References n, MeshObject< fvMesh, UpdateableMeshObject, wallDistAddressing >::New(), wallDistAddressing::patchIDs_, and UPtrList< T >::size().
Member Data Documentation
patchIDs_
const labelList patchIDs_ protected
Definition at line 120 of file wallDistAddressing.H.
Referenced by wallDistAddressing::collectPatchFields(), and wallDistAddressing::patchIDs().
patchTypeName_
const word patchTypeName_ protected
Definition at line 123 of file wallDistAddressing.H.
updateInterval_
const label updateInterval_ protected
Definition at line 126 of file wallDistAddressing.H.
correctWalls_
const bool correctWalls_ protected
Definition at line 129 of file wallDistAddressing.H.
requireUpdate_
bool requireUpdate_ protected
Definition at line 132 of file wallDistAddressing.H.
y_
volScalarField y_ mutable protected
Definition at line 135 of file wallDistAddressing.H.
Referenced by wallDistAddressing::y().
globalWallsPtr_
autoPtr<globalIndex> globalWallsPtr_ protected
Definition at line 138 of file wallDistAddressing.H.
mapPtr_
autoPtr<mapDistribute> mapPtr_ protected
Definition at line 141 of file wallDistAddressing.H.
untransformedItems_
labelList untransformedItems_ protected
Definition at line 144 of file wallDistAddressing.H.
untransformedSlots_
labelList untransformedSlots_ protected
Definition at line 147 of file wallDistAddressing.H.
untransformedPatchStarts_
labelList untransformedPatchStarts_ protected
Definition at line 151 of file wallDistAddressing.H.
transformedItems_
labelList transformedItems_ protected
Definition at line 154 of file wallDistAddressing.H.
transformedSlots_
labelList transformedSlots_ protected
Definition at line 155 of file wallDistAddressing.H.
transformedPatchStarts_
labelList transformedPatchStarts_ protected
Definition at line 156 of file wallDistAddressing.H.
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/wallDist/wallDistAddressing/wallDistAddressing.H
src/finiteVolume/fvMesh/wallDist/wallDistAddressing/wallDistAddressing.C
src/finiteVolume/fvMesh/wallDist/wallDistAddressing/wallDistAddressingTemplates.C