OpenFOAM: general Class Reference
general Class Reference
Particle-size distribution model wherein random samples are drawn from a given arbitrary probability density function or cumulative distribution function. Input distributions are specified as pairs of (size, probability) (i.e. (point, value)).
#include <general.H>
Public Member Functions
TypeName ("general")
general (const dictionary &dict, Random &rndGen)
general (const UList< scalar > &sampleData, const scalar binWidth, Random &rndGen)
general (const general &p)
virtual autoPtr< distributionModel > clone () const
void operator= (const general &)=delete
virtual ~general ()=default
virtual tmp< scalarField > x () const
virtual tmp< scalarField > y () const
virtual scalar sample () const
virtual scalar meanValue () const
virtual void writeData (Ostream &os) const
virtual void readData (Istream &os)
virtual dictionary writeDict (const word &dictName) const
virtual void readDict (const dictionary &dict)
Public Member Functions inherited from distributionModel
TypeName ("distributionModel")
declareRunTimeSelectionTable (autoPtr, distributionModel, dictionary,(const dictionary &dict, Random &rndGen),(dict, rndGen))
distributionModel (const word &name, const dictionary &dict, Random &rndGen)
distributionModel (const distributionModel &p)
virtual ~distributionModel ()=default
virtual scalar minValue () const
virtual scalar maxValue () const
Additional Inherited Members
Static Public Member Functions inherited from distributionModel
static autoPtr< distributionModel > New (const dictionary &dict, Random &rndGen)
Protected Member Functions inherited from distributionModel
virtual void check () const
Protected Attributes inherited from distributionModel
const dictionary distributionModelDict_
Random & rndGen_
scalar minValue_
scalar maxValue_
Detailed Description
Particle-size distribution model wherein random samples are drawn from a given arbitrary probability density function or cumulative distribution function. Input distributions are specified as pairs of (size, probability) (i.e. (point, value)).
Usage
Minimal example by using constant/<CloudProperties>:
subModels
{
    injectionModels
    {
        <name>
        {
            ...
            sizeDistribution
            {
                type        general;
                generalDistribution
                {
                    cumulative      false;
                    distribution
                    (
                        (<size1>    <probability1>)
                        (<size2>    <probability2>)
                        ...
                        (<sizeN>    <probabilityN>)
                    );
                }
            }
        }
    }
}
where the entries mean:
Property Description Type Reqd Deflt
type Type name: general word yes -
generalDistribution Distribution settings dict yes -
distribution <size>-<probability> pairs dict yes -
<size> Particle size scalar yes -
<probability> Volume fraction/probability scalar yes -
cumulative
Flag to determine if input distribution is specified
as cumulative or as density
bool no false
Note
An example for a pair within distribution subdictionary can be given as follows: "(1e-07 1.3)" means 1.3% of particles are modelled with a particle diameter of "1e-7" [m], and so on.
Variation between input pairs is assumed to be linear.
Elements in the second column (i.e. probability) are normalised.
Elements in the second column for cumulative distribution functions must start from zero and must be non-decreasing (i.e. monotonic).
Elements in the first column (i.e. size) must be specified in an ascending order.
Input pairs cannot contain any negative element.
Source files
general.H
general.C
Definition at line 165 of file general.H.
Constructor & Destructor Documentation
general() [1/3]
general (const dictionary & dict, Random & rndGen)
Definition at line 89 of file general.C.
References distributionModel::check(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, distributionModel::maxValue_, distributionModel::minValue_, Foam::nl, and Foam::type().
general() [2/3]
general (const UList< scalar > & sampleData, const scalar binWidth, Random & rndGen)
Definition at line 159 of file general.C.
References Foam::endl(), forAll, Foam::max(), distributionModel::maxValue_, Foam::min(), distributionModel::minValue_, Foam::nl, and WarningInFunction.
general() [3/3]
general (const general & p)
Definition at line 216 of file general.C.
~general()
virtual ~general () virtual default
Member Function Documentation
TypeName()
TypeName ("general")
clone()
virtual autoPtr< distributionModel > clone () const inline virtual
Implements distributionModel.
Definition at line 219 of file general.H.
operator=()
void operator= (const general &) delete
x()
Foam::tmp< Foam::Field< Foam::scalar > > x () const virtual
Definition at line 327 of file general.C.
References forAll, tmp< T >::New(), and x.
y()
Foam::tmp< Foam::Field< Foam::scalar > > y () const virtual
Definition at line 341 of file general.C.
References forAll, tmp< T >::New(), and y.
sample()
Foam::scalar sample () const virtual
Implements distributionModel.
Definition at line 229 of file general.C.
References alpha, k, Foam::mag(), n, p, and Foam::sqrt().
meanValue()
Foam::scalar meanValue () const virtual
Implements distributionModel.
Definition at line 274 of file general.C.
writeData()
void writeData (Ostream & os) const virtual
Definition at line 288 of file general.C.
References os().
readData()
void readData (Istream & os) virtual
Definition at line 280 of file general.C.
writeDict()
Foam::dictionary writeDict (const word & dictName) const virtual
Definition at line 295 of file general.C.
References dict, dictName(), x, and y.
Referenced by InjectedParticleDistributionInjection< CloudType >::info().
readDict()
void readDict (const dictionary & dict) virtual
Definition at line 309 of file general.C.
References dict, forAll, x, and y.
The documentation for this class was generated from the following files:
src/lagrangian/distributionModels/general/general.H
src/lagrangian/distributionModels/general/general.C