OpenFOAM: PPCG Class Reference
PPCG Class Reference
Preconditioned pipelined conjugate gradient solver for symmetric lduMatrices using a run-time selectable preconditioner.
#include <PPCG.H>
Public Member Functions
TypeName ("PPCG")
PPCG (const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces, const dictionary &solverControls)
virtual ~PPCG ()=default
virtual solverPerformance solve (scalarField &psi, const scalarField &source, const direction cmpt=0) const
Public Member Functions inherited from lduMatrix::solver
virtual const word & type () const =0
declareRunTimeSelectionTable (autoPtr, solver, symMatrix,(const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces, const dictionary &solverControls),(fieldName, matrix, interfaceBouCoeffs, interfaceIntCoeffs, interfaces, solverControls))
declareRunTimeSelectionTable (autoPtr, solver, asymMatrix,(const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces, const dictionary &solverControls),(fieldName, matrix, interfaceBouCoeffs, interfaceIntCoeffs, interfaces, solverControls))
solver (const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces, const dictionary &solverControls)
virtual ~solver ()=default
const word & fieldName () const noexcept
const lduMatrix & matrix () const noexcept
const FieldField< Field, scalar > & interfaceBouCoeffs () const noexcept
const FieldField< Field, scalar > & interfaceIntCoeffs () const noexcept
const lduInterfaceFieldPtrsList & interfaces () const noexcept
virtual void read (const dictionary &)
virtual solverPerformance scalarSolve (solveScalarField &psi, const solveScalarField &source, const direction cmpt=0) const
solveScalarField::cmptType normFactor (const solveScalarField &psi, const solveScalarField &source, const solveScalarField &Apsi, solveScalarField &tmpField, const lduMatrix::normTypes normType) const
solveScalarField::cmptType normFactor (const solveScalarField &psi, const solveScalarField &source, const solveScalarField &Apsi, solveScalarField &tmpField) const
Protected Member Functions
solverPerformance scalarSolveCG (solveScalarField &psi, const solveScalarField &source, const direction cmpt, const bool cgMode) const
Protected Member Functions inherited from lduMatrix::solver
virtual void readControls ()
Additional Inherited Members
Static Public Member Functions inherited from lduMatrix::solver
static autoPtr< solver > New (const word &solverName, const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces, const dictionary &solverControls)
static autoPtr< solver > New (const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces, const dictionary &solverControls)
Protected Attributes inherited from lduMatrix::solver
word fieldName_
const lduMatrix & matrix_
const FieldField< Field, scalar > & interfaceBouCoeffs_
const FieldField< Field, scalar > & interfaceIntCoeffs_
lduInterfaceFieldPtrsList interfaces_
dictionary controlDict_
int log_
label minIter_
label maxIter_
lduMatrix::normTypes normType_
scalar tolerance_
scalar relTol_
profilingTrigger profiling_
Detailed Description
Preconditioned pipelined conjugate gradient solver for symmetric lduMatrices using a run-time selectable preconditioner.
Reference:
    P. Ghysels, W. Vanroose.
    "Hiding global synchronization latency in the
     preconditioned Conjugate Gradient algorithm"
and implementation details from
    Paul Eller, William Gropp
    "Scalable Non-blocking Preconditioned Conjugate Gradient Methods"
Source files
PPCG.H
PPCG.C
Definition at line 60 of file PPCG.H.
Constructor & Destructor Documentation
PPCG()
PPCG (const word & fieldName, const lduMatrix & matrix, const FieldField< Field, scalar > & interfaceBouCoeffs, const FieldField< Field, scalar > & interfaceIntCoeffs, const lduInterfaceFieldPtrsList & interfaces, const dictionary & solverControls)
Definition at line 264 of file PPCG.C.
~PPCG()
virtual ~PPCG () virtual default
Member Function Documentation
scalarSolveCG()
Foam::solverPerformance scalarSolveCG (solveScalarField & psi, const solveScalarField & source, const direction cmpt, const bool cgMode) const protected
Definition at line 74 of file PPCG.C.
References alpha, beta(), delta, Foam::endl(), gamma, lduMatrix::preconditioner::getName(), Foam::Info, n, lduMatrix::preconditioner::New(), p, psi, s(), UPtrList< T >::size(), and Foam::type().
Referenced by PPCR::solve().
TypeName()
TypeName ("PPCG")
solve()
Foam::solverPerformance solve (scalarField & psi, const scalarField & source, const direction cmpt = 0) const virtual
Implements lduMatrix::solver.
Reimplemented in PPCR.
Definition at line 288 of file PPCG.C.
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/lduMatrix/solvers/PPCG/PPCG.H
src/OpenFOAM/matrices/lduMatrix/solvers/PPCG/PPCG.C