OpenFOAM: optMeshMovementBezier Class Reference
optMeshMovementBezier Class Reference
Converts NURBS control points update to actual mesh movement.
#include <optMeshMovementBezier.H>
Public Member Functions
TypeName ("Bezier")
optMeshMovementBezier (fvMesh &mesh, const dictionary &dict, const labelList &patchIDs)
virtual ~optMeshMovementBezier ()=default
void moveMesh ()
virtual scalar computeEta (const scalarField &correction)
virtual labelList getActiveDesignVariables () const
Public Member Functions inherited from optMeshMovement
TypeName ("optMeshMovement")
declareRunTimeSelectionTable (autoPtr, optMeshMovement, dictionary,(fvMesh &mesh, const dictionary &dict, const labelList &patchIDs),(mesh, dict, patchIDs))
optMeshMovement (fvMesh &mesh, const dictionary &dict, const labelList &patchIDs)
virtual ~optMeshMovement ()=default
void setCorrection (const scalarField &correction)
autoPtr< displacementMethod > & returnDisplacementMethod ()
const labelList & getPatchIDs ()
void writeMeshQualityMetrics ()
virtual void storeDesignVariables ()
virtual void resetDesignVariables ()
bool maxAllowedDisplacementSet () const
Protected Member Functions
void computeBoundaryMovement (const scalarField &correction)
Protected Member Functions inherited from optMeshMovement
scalar getMaxAllowedDisplacement () const
Protected Attributes
Bezier Bezier_
pointVectorField dx_
vectorField cumulativeChange_
Protected Attributes inherited from optMeshMovement
fvMesh & mesh_
const dictionary & dict_
scalarField correction_
labelList patchIDs_
vectorField pointsInit_
autoPtr< displacementMethod > displMethodPtr_
bool writeMeshQualityMetrics_
Additional Inherited Members
Static Public Member Functions inherited from optMeshMovement
static autoPtr< optMeshMovement > New (fvMesh &mesh, const dictionary &dict, const labelList &patchIDs)
Detailed Description
Converts NURBS control points update to actual mesh movement.
Source files
optMeshMovementBezier.H
optMeshMovementBezier.C
Definition at line 50 of file optMeshMovementBezier.H.
Constructor & Destructor Documentation
optMeshMovementBezier()
optMeshMovementBezier (fvMesh & mesh, const dictionary & dict, const labelList & patchIDs)
Definition at line 86 of file optMeshMovementBezier.C.
~optMeshMovementBezier()
virtual ~optMeshMovementBezier () virtual default
Member Function Documentation
computeBoundaryMovement()
void computeBoundaryMovement (const scalarField & correction) protected
Definition at line 42 of file optMeshMovementBezier.C.
References optMeshMovementBezier::Bezier_, Bezier::confineXmovement(), Bezier::confineYmovement(), Bezier::confineZmovement(), Foam::correction(), optMeshMovementBezier::cumulativeChange_, optMeshMovementBezier::dx_, Bezier::dxidXj(), Foam::endl(), Foam::Info, Bezier::nBezier(), GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef(), Foam::Zero, and VectorSpace< Form, Cmpt, Ncmpts >::zero.
TypeName()
TypeName ("Bezier")
moveMesh()
void moveMesh () virtual
Reimplemented from optMeshMovement.
Definition at line 115 of file optMeshMovementBezier.C.
References optMeshMovement::moveMesh().
computeEta()
Foam::scalar computeEta (const scalarField & correction) virtual
Implements optMeshMovement.
Definition at line 129 of file optMeshMovementBezier.C.
References Foam::correction(), Foam::endl(), Foam::gMax(), Foam::Info, and Foam::mag().
getActiveDesignVariables()
Foam::labelList getActiveDesignVariables () const virtual
Reimplemented from optMeshMovement.
Definition at line 147 of file optMeshMovementBezier.C.
Member Data Documentation
Bezier_
Bezier Bezier_ protected
Definition at line 59 of file optMeshMovementBezier.H.
Referenced by optMeshMovementBezier::computeBoundaryMovement().
dx_
pointVectorField dx_ protected
Definition at line 62 of file optMeshMovementBezier.H.
Referenced by optMeshMovementBezier::computeBoundaryMovement().
cumulativeChange_
vectorField cumulativeChange_ protected
Definition at line 65 of file optMeshMovementBezier.H.
Referenced by optMeshMovementBezier::computeBoundaryMovement().
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/optimisation/optMeshMovement/optMeshMovementBezier/optMeshMovementBezier.H
src/optimisation/adjointOptimisation/adjoint/optimisation/optMeshMovement/optMeshMovementBezier/optMeshMovementBezier.C