OpenFOAM: LamBremhorstKE Class Reference
LamBremhorstKE Class Reference
Lam and Bremhorst low-Reynolds number k-epsilon turbulence model for incompressible flows.
#include <LamBremhorstKE.H>
Public Member Functions
TypeName ("LamBremhorstKE")
LamBremhorstKE (const geometricOneField &alpha, const geometricOneField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
virtual ~LamBremhorstKE ()=default
virtual bool read ()
tmp< volScalarField > DkEff () const
tmp< volScalarField > DepsilonEff () const
virtual tmp< volScalarField > k () const
virtual tmp< volScalarField > epsilon () const
virtual void correct ()
Public Member Functions inherited from eddyViscosity< incompressible::RASModel >
eddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~eddyViscosity ()=default
virtual tmp< volScalarField > nut () const
virtual tmp< scalarField > nut (const label patchi) const
virtual tmp< volSymmTensorField > R () const
virtual void validate ()
Public Member Functions inherited from linearViscousStress< BasicTurbulenceModel >
linearViscousStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~linearViscousStress ()=default
virtual tmp< volSymmTensorField > devRhoReff () const
virtual tmp< volSymmTensorField > devRhoReff (const volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Protected Member Functions
virtual void correctNut ()
Protected Attributes
dimensionedScalar Cmu_
dimensionedScalar Ceps1_
dimensionedScalar Ceps2_
dimensionedScalar sigmaEps_
volScalarField k_
volScalarField epsilon_
const volScalarField & y_
Protected Attributes inherited from eddyViscosity< incompressible::RASModel >
volScalarField nut_
Additional Inherited Members
Public Types inherited from eddyViscosity< incompressible::RASModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from linearViscousStress< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Detailed Description
Lam and Bremhorst low-Reynolds number k-epsilon turbulence model for incompressible flows.
This turbulence model is described in:
    Lam, C. K. G., & Bremhorst, K. (1981).
    A modified form of the k-ε model for predicting wall turbulence.
    Journal of Fluids Engineering, 103(3), 456-460.
Source files
LamBremhorstKE.H
LamBremhorstKE.C
Definition at line 63 of file LamBremhorstKE.H.
Constructor & Destructor Documentation
LamBremhorstKE()
LamBremhorstKE (const geometricOneField & alpha, const geometricOneField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Definition at line 85 of file LamBremhorstKE.C.
References Foam::bound(), LamBremhorstKE::epsilon_, LamBremhorstKE::k_, and Foam::type().
~LamBremhorstKE()
virtual ~LamBremhorstKE () virtual default
Member Function Documentation
correctNut()
void correctNut () protected virtual
Implements eddyViscosity< incompressible::RASModel >.
Definition at line 77 of file LamBremhorstKE.C.
References LamBremhorstKE::correctNut().
Referenced by LamBremhorstKE::correct(), and LamBremhorstKE::correctNut().
TypeName()
TypeName ("LamBremhorstKE")
read()
bool read () virtual
Implements eddyViscosity< incompressible::RASModel >.
Definition at line 186 of file LamBremhorstKE.C.
References LamBremhorstKE::Ceps1_, LamBremhorstKE::Ceps2_, LamBremhorstKE::Cmu_, dimensioned< Type >::readIfPresent(), and LamBremhorstKE::sigmaEps_.
DkEff()
tmp< volScalarField > DkEff () const inline
Definition at line 137 of file LamBremhorstKE.H.
References nu, and eddyViscosity< incompressible::RASModel >::nut_.
Referenced by LamBremhorstKE::correct().
DepsilonEff()
tmp< volScalarField > DepsilonEff () const inline
Definition at line 146 of file LamBremhorstKE.H.
References nu, eddyViscosity< incompressible::RASModel >::nut_, and LamBremhorstKE::sigmaEps_.
Referenced by LamBremhorstKE::correct().
k()
virtual tmp< volScalarField > k () const inline virtual
Implements eddyViscosity< incompressible::RASModel >.
Definition at line 155 of file LamBremhorstKE.H.
References LamBremhorstKE::k_.
epsilon()
virtual tmp< volScalarField > epsilon () const inline virtual
Definition at line 161 of file LamBremhorstKE.H.
References LamBremhorstKE::epsilon_.
correct()
void correct () virtual
Implements eddyViscosity< incompressible::RASModel >.
Definition at line 202 of file LamBremhorstKE.C.
References Foam::bound(), GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), LamBremhorstKE::Ceps1_, LamBremhorstKE::Ceps2_, PtrList< T >::clear(), eddyViscosity< BasicTurbulenceModel >::correct(), LamBremhorstKE::correctNut(), Foam::fvm::ddt(), LamBremhorstKE::DepsilonEff(), Foam::fvm::div(), LamBremhorstKE::DkEff(), LamBremhorstKE::epsilon_, GeometricBoundaryField< Type, PatchField, GeoMesh >::evaluateCoupled(), Foam::fvc::grad(), LamBremhorstKE::k_, Foam::fvm::laplacian(), eddyViscosity< incompressible::RASModel >::nut_, solve(), Foam::fvm::Sp(), Foam::twoSymm(), and GeometricBoundaryField< Type, PatchField, GeoMesh >::updateCoeffs().
Member Data Documentation
Cmu_
dimensionedScalar Cmu_ protected
Definition at line 86 of file LamBremhorstKE.H.
Referenced by LamBremhorstKE::read().
Ceps1_
dimensionedScalar Ceps1_ protected
Definition at line 87 of file LamBremhorstKE.H.
Referenced by LamBremhorstKE::correct(), and LamBremhorstKE::read().
Ceps2_
dimensionedScalar Ceps2_ protected
Definition at line 88 of file LamBremhorstKE.H.
Referenced by LamBremhorstKE::correct(), and LamBremhorstKE::read().
sigmaEps_
dimensionedScalar sigmaEps_ protected
Definition at line 89 of file LamBremhorstKE.H.
Referenced by LamBremhorstKE::DepsilonEff(), and LamBremhorstKE::read().
k_
volScalarField k_ protected
Definition at line 91 of file LamBremhorstKE.H.
Referenced by LamBremhorstKE::correct(), LamBremhorstKE::k(), and LamBremhorstKE::LamBremhorstKE().
epsilon_
volScalarField epsilon_ protected
Definition at line 92 of file LamBremhorstKE.H.
Referenced by LamBremhorstKE::correct(), LamBremhorstKE::epsilon(), and LamBremhorstKE::LamBremhorstKE().
y_
const volScalarField& y_ protected
Definition at line 97 of file LamBremhorstKE.H.
The documentation for this class was generated from the following files:
src/TurbulenceModels/incompressible/turbulentTransportModels/RAS/LamBremhorstKE/LamBremhorstKE.H
src/TurbulenceModels/incompressible/turbulentTransportModels/RAS/LamBremhorstKE/LamBremhorstKE.C