OpenFOAM: fixedEnergyFvPatchScalarField Class Reference
fixedEnergyFvPatchScalarField Class Reference
Boundary conditions » Thermophysical
This boundary condition provides a fixed condition for internal energy.
#include <fixedEnergyFvPatchScalarField.H>
Public Member Functions
TypeName ("fixedEnergy")
fixedEnergyFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
fixedEnergyFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
fixedEnergyFvPatchScalarField (const fixedEnergyFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
fixedEnergyFvPatchScalarField (const fixedEnergyFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
fixedEnergyFvPatchScalarField (const fixedEnergyFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual void updateCoeffs ()
Detailed Description
This boundary condition provides a fixed condition for internal energy.
Usage
Example of the boundary condition specification:
<patchName>
{
    type            fixedEnergy;
    value           uniform 100;
}
See also
Foam::fixedValueFvPatchField
Source files
fixedEnergyFvPatchScalarField.H
fixedEnergyFvPatchScalarField.C
Definition at line 62 of file fixedEnergyFvPatchScalarField.H.
Constructor & Destructor Documentation
fixedEnergyFvPatchScalarField() [1/5]
fixedEnergyFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 29 of file fixedEnergyFvPatchScalarField.C.
fixedEnergyFvPatchScalarField() [2/5]
fixedEnergyFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 53 of file fixedEnergyFvPatchScalarField.C.
fixedEnergyFvPatchScalarField() [3/5]
fixedEnergyFvPatchScalarField (const fixedEnergyFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 40 of file fixedEnergyFvPatchScalarField.C.
fixedEnergyFvPatchScalarField() [4/5]
fixedEnergyFvPatchScalarField (const fixedEnergyFvPatchScalarField & tppsf)
Definition at line 65 of file fixedEnergyFvPatchScalarField.C.
fixedEnergyFvPatchScalarField() [5/5]
fixedEnergyFvPatchScalarField (const fixedEnergyFvPatchScalarField & tppsf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 75 of file fixedEnergyFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("fixedEnergy")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 107 of file fixedEnergyFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 123 of file fixedEnergyFvPatchScalarField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 88 of file fixedEnergyFvPatchScalarField.C.
References fvPatchField< Type >::evaluate(), basicThermo::lookupThermo(), and Foam::operator==().
The documentation for this class was generated from the following files:
src/thermophysicalModels/basic/derivedFvPatchFields/fixedEnergy/fixedEnergyFvPatchScalarField.H
src/thermophysicalModels/basic/derivedFvPatchFields/fixedEnergy/fixedEnergyFvPatchScalarField.C