OpenFOAM: CodedFunction1< Type > Class Template Reference
CodedFunction1< Type > Class Template Reference
Function1 with the code supplied by an on-the-fly compiled C++ expression.
#include <CodedFunction1.H>
Public Member Functions
TypeName ("coded")
CodedFunction1 (const word &entryName, const dictionary &dict, const objectRegistry *obrPtr=nullptr)
CodedFunction1 (const CodedFunction1< Type > &rhs)
virtual tmp< Function1< Type > > clone () const
virtual ~CodedFunction1 ()=default
virtual Type value (const scalar x) const
virtual void writeData (Ostream &os) const
Public Member Functions inherited from Function1< Type >
TypeName ("Function1") declareRunTimeSelectionTable(autoPtr
Function1 (const word &entryName, const objectRegistry *obrPtr=nullptr)
Function1 (const word &entryName, const dictionary &dict, const objectRegistry *obrPtr=nullptr)
Function1 (const Function1< Type > &rhs)
virtual ~Function1 ()=default
virtual bool constant () const
virtual bool good () const
virtual tmp< Field< Type > > value (const scalarField &x) const
virtual Type integrate (const scalar x1, const scalar x2) const
virtual tmp< Field< Type > > integrate (const scalarField &x1, const scalarField &x2) const
virtual void writeEntries (Ostream &os) const
Public Member Functions inherited from function1Base
function1Base (const word &entryName, const objectRegistry *obrPtr=nullptr)
function1Base (const word &entryName, const dictionary &dict, const objectRegistry *obrPtr=nullptr)
function1Base (const function1Base &rhs)
virtual ~function1Base ()
const word & name () const noexcept
const objectRegistry * whichDb () const noexcept
void resetDb (const objectRegistry *obrPtr=nullptr) noexcept
void resetDb (const objectRegistry &db) noexcept
const objectRegistry & obr () const
bool isTime () const noexcept
const Time & time () const
template<class MeshType >
const MeshType & mesh (const word &regionName=word::null) const
virtual void userTimeToTime (const Time &t)
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Static Public Attributes
static constexpr const char *const codeTemplateC = "codedFunction1Template.C"
static constexpr const char *const codeTemplateH = "codedFunction1Template.H"
Protected Member Functions
virtual dlLibraryTable & libs () const
virtual string description () const
virtual void clearRedirect () const
virtual const dictionary & codeContext () const
virtual const dictionary & codeDict (const dictionary &dict) const
virtual const dictionary & codeDict () const
virtual void prepare (dynamicCode &, const dynamicCodeContext &) const
void operator= (const CodedFunction1< Type > &)=delete
Protected Member Functions inherited from Function1< Type >
void operator= (const Function1< Type > &)=delete
Protected Member Functions inherited from function1Base
void operator= (const function1Base &)=delete
Protected Member Functions inherited from codedBase
dynamicCodeContext & codeContext ()
void setCodeContext (const dictionary &dict)
void append (const std::string &str)
void updateLibrary (const word &name, const dynamicCodeContext &context) const
void updateLibrary (const word &name, const dictionary &dict) const
void updateLibrary (const word &name) const
ClassName ("codedBase")
codedBase (const codedBase &)=delete
void operator= (const codedBase &)=delete
codedBase ()=default
virtual ~codedBase ()=default
Additional Inherited Members
Public Types inherited from Function1< Type >
typedef Type returnType
Static Public Member Functions inherited from Function1< Type >
static autoPtr< Function1< Type > > New (const word &entryName, const dictionary &dict, const word &redirectType, const objectRegistry *obrPtr=nullptr, const bool mandatory=true)
static autoPtr< Function1< Type > > NewCompat (const word &entryName, std::initializer_list< std::pair< const char *, int > > compat, const dictionary &dict, const word &redirectType=word::null, const objectRegistry *obrPtr=nullptr, const bool mandatory=true)
static autoPtr< Function1< Type > > New (const word &entryName, const dictionary &dict, const objectRegistry *obrPtr=nullptr, const bool mandatory=true)
static autoPtr< Function1< Type > > NewIfPresent (const word &entryName, const dictionary &dict, const word &redirectType, const objectRegistry *obrPtr=nullptr)
static autoPtr< Function1< Type > > NewIfPresent (const word &entryName, const dictionary &dict, const objectRegistry *obrPtr=nullptr)
static refPtr< Function1< Type > > New (HashPtrTable< Function1< Type > > &cache, const word &entryName, const dictionary &dict, enum keyType::option matchOpt=keyType::LITERAL, const objectRegistry *obrPtr=nullptr, const bool mandatory=true)
Public Attributes inherited from Function1< Type >
Function1
dictionary
const word & entryName
const word const dictionary & dict
const word const dictionary const objectRegistry * obrPtr
const word const dictionary const objectRegistry entryName
const word const dictionary const objectRegistry dict
const word const dictionary const objectRegistry obrPtr
Static Protected Member Functions inherited from codedBase
static void writeCodeDict (Ostream &os, const dictionary &dict)
static const dictionary & codeDict (const objectRegistry &obr, const word &dictName="codeDict")
Protected Attributes inherited from function1Base
const word name_
const objectRegistry * obrPtr_
Detailed Description
template<class Type>
class Foam::Function1Types::CodedFunction1< Type >
Function1 with the code supplied by an on-the-fly compiled C++ expression.
The code entries:
codeInclude : include files
codeOptions : compiler line: added to EXE_INC (Make/options)
codeLibs : linker line: added to LIB_LIBS (Make/options)
localCode : c++; local static functions
code : c++; return the patch values at (scalar x)
Usage
Example:
<patchName>
{
    type            uniformFixedValue;
    uniformValue
    {
        type  coded;
        name  myExpression;  // Name of generated PatchFunction1
        code
        #{
            const polyPatch& pp = this->patch();
            Pout<< "** Patch size:" << pp.size() << endl;
            return tmp<vectorField>::New(pp.size(), vector(1, 0, 0))
        #};
        //codeInclude
        //#{
        //    #include "volFields.H"
        //#};
        //codeOptions
        //#{
        //    -I$(LIB_SRC)/finiteVolume/lnInclude
        //#};
    }
}
Note
The code context dictionary is simply the dictionary used to specify the PatchFunction1 coefficients.
See also
Foam::dynamicCode Foam::codedFixedValue Foam::functionEntries::codeStream
Source files
CodedFunction1.H
CodedFunction1.C
Definition at line 120 of file CodedFunction1.H.
Constructor & Destructor Documentation
CodedFunction1() [1/2]
template<class Type > CodedFunction1 (const word & entryName, const dictionary & dict, const objectRegistry * obrPtr = nullptr)
Definition at line 136 of file CodedFunction1.C.
References codedBase::setCodeContext(), and codedBase::updateLibrary().
CodedFunction1() [2/2]
template<class Type > CodedFunction1 (const CodedFunction1< Type > & rhs) explicit
Definition at line 157 of file CodedFunction1.C.
~CodedFunction1()
template<class Type > virtual ~CodedFunction1 () virtual default
Member Function Documentation
libs()
template<class Type > Foam::dlLibraryTable & libs () const protected virtual
Implements codedBase.
Definition at line 29 of file CodedFunction1.C.
description()
template<class Type > Foam::string description () const protected virtual
Implements codedBase.
Definition at line 37 of file CodedFunction1.C.
clearRedirect()
template<class Type > void clearRedirect () const protected virtual
Implements codedBase.
Definition at line 44 of file CodedFunction1.C.
codeContext()
template<class Type > const Foam::dictionary & codeContext () const protected virtual
Definition at line 52 of file CodedFunction1.C.
codeDict() [1/2]
template<class Type > const Foam::dictionary & codeDict (const dictionary & dict) const protected virtual
Definition at line 61 of file CodedFunction1.C.
References dict.
codeDict() [2/2]
template<class Type > const Foam::dictionary & codeDict () const protected virtual
Implements codedBase.
Definition at line 80 of file CodedFunction1.C.
prepare()
template<class Type > void prepare (dynamicCode & dynCode, const dynamicCodeContext & context) const protected virtual
Implements codedBase.
Definition at line 87 of file CodedFunction1.C.
References dynamicCodeContext::code(), DetailInfo, UPtrList< T >::empty(), Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, dynamicCodeContext::libs(), dynamicCodeContext::options(), and dynamicCodeContext::sha1().
operator=()
template<class Type > void operator= (const CodedFunction1< Type > &) protected delete
TypeName()
template<class Type > TypeName ("coded")
clone()
template<class Type > virtual tmp< Function1< Type > > clone () const inline virtual
Implements Function1< Type >.
Definition at line 203 of file CodedFunction1.H.
value()
template<class Type > Type value (const scalar x) const inline virtual
Reimplemented from Function1< Type >.
Definition at line 215 of file CodedFunction1.C.
References x.
writeData()
template<class Type > void writeData (Ostream & os) const virtual
Reimplemented from Function1< Type >.
Definition at line 228 of file CodedFunction1.C.
References Foam::name().
Member Data Documentation
codeTemplateC
template<class Type > constexpr const char* const codeTemplateC = "codedFunction1Template.C" static constexpr
Definition at line 177 of file CodedFunction1.H.
codeTemplateH
template<class Type > constexpr const char* const codeTemplateH = "codedFunction1Template.H" static constexpr
Definition at line 181 of file CodedFunction1.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/functions/Function1/Coded/CodedFunction1.H
src/OpenFOAM/primitives/functions/Function1/Coded/CodedFunction1.C