OpenFOAM: CompactListList< T > Class Template Reference
CompactListList< T > Class Template Reference
A packed storage unstructured matrix of objects of type <T> using an offset table for access.
#include <CompactListList.H>
Public Types
typedef T value_type
typedef T * pointer
typedef const T * const_pointer
typedef T & reference
typedef const T & const_reference
typedef label size_type
Public Member Functions
CompactListList () noexcept=default
CompactListList (const CompactListList< T > &list)
CompactListList (CompactListList< T > &&list)
CompactListList (CompactListList< T > &list, bool reuse)
CompactListList (const label mRows, const label nVals)
CompactListList (const label mRows, const label nVals, const Foam::zero)
CompactListList (const label mRows, const label nVals, const T &)
CompactListList (const labelUList &listSizes)
CompactListList (const labelUList &listSizes, const T &val)
CompactListList (Istream &is)
autoPtr< CompactListList< T > > clone () const
bool empty () const noexcept
label size () const noexcept
label totalSize () const
const labelList & offsets () const noexcept
labelList & offsets () noexcept
const List< T > & values () const noexcept
List< T > & values () noexcept
const T * cdata () const noexcept
T * data () noexcept
const char * cdata_bytes () const noexcept
char * data_bytes () noexcept
std::streamsize size_bytes () const noexcept
std::streamsize byteSize () const
labelList sizes () const
const labelUList localStarts () const
labelList localSizes () const
label localStart (const label i) const
label localEnd (const label i) const
label localSize (const label i) const
List< labelRange > ranges () const
labelRange range (const label i) const
label maxSize () const
void clear ()
void resize (const label mRows)
void resize (const label mRows, const label nVals)
void resize_nocopy (const label mRows, const label nVals)
void resize (const label mRows, const label nVals, const T &)
void resize (const labelUList &listSizes)
void setLocalSize (const label rowi, const label len)
void setSize (const label mRows)
void setSize (const label mRows, const label nVals)
void setSize (const label mRows, const label nVals, const T &)
void setSize (const labelUList &listSizes)
void swap (CompactListList< T > &other)
void transfer (CompactListList< T > &list)
label toGlobal (const label rowi, const label i) const
label toLocal (const label rowi, const label i) const
label findRow (const label i) const
label whichRow (const label i) const
template<class SubListType = List<T>>
List< SubListType > unpack () const
template<class SubListType = List<T>>
List< SubListType > unpack (const labelRange &range) const
void operator= (const CompactListList< T > &list)
void operator= (CompactListList< T > &&list)
void operator= (const T &val)
void operator= (const Foam::zero)
UList< T > localList (const label i)
const UList< T > localList (const label i) const
UList< T > operator[] (const label i)
const UList< T > operator[] (const label i) const
T & operator() (const label i, const label j)
const T & operator() (const label i, const label j) const
Istream & readList (Istream &is)
Ostream & writeList (Ostream &os, const label shortLen=0) const
const List< T > & m () const noexcept
List< T > & m () noexcept
label index (const label rowi, const label colj) const
label whichColumn (const label rowi, const label i) const
template<class ListListType >
Foam::CompactListList< T > packImpl (const ListListType &lists, const bool checkOverflow)
template<class SubListType >
Foam::CompactListList< T > pack (const UList< SubListType > &lists, const bool checkOverflow)
template<class SubListType , class Addr >
Foam::CompactListList< T > pack (const IndirectListBase< SubListType, Addr > &lists, const bool checkOverflow)
template<class SubListType >
Foam::List< SubListType > unpack () const
template<class SubListType >
Foam::List< SubListType > unpack (const labelRange &range) const
Static Public Member Functions
static const CompactListList< T > & null ()
template<class SubListType = List<T>>
static CompactListList< T > pack (const UList< SubListType > &lists, const bool checkOverflow=false)
template<class SubListType , class Addr >
static CompactListList< T > pack (const IndirectListBase< SubListType, Addr > &lists, const bool checkOverflow=false)
Friends
Istream & operator>> (Istream &, CompactListList< T > &)
Ostream & operator<< (Ostream &, const CompactListList< T > &)
Detailed Description
template<class T>
class Foam::CompactListList< T >
A packed storage unstructured matrix of objects of type <T> using an offset table for access.
The offset table is the size of the number of rows+1 whose elements are the accumulated sizes of the rows, i.e.
offset[i] gives the index of first element of row i
offset[i+1] - offset[i] is the number of elements in row i
Note that an empty CompactListList should have empty offsets (not size 1).
Source files
CompactListList.H
CompactListList.C
CompactListListI.H
CompactListListIO.C
Definition at line 67 of file CompactListList.H.
Member Typedef Documentation
value_type
template<class T > typedef T value_type
Definition at line 107 of file CompactListList.H.
pointer
template<class T > typedef T* pointer
Definition at line 110 of file CompactListList.H.
const_pointer
template<class T > typedef const T* const_pointer
Definition at line 113 of file CompactListList.H.
reference
template<class T > typedef T& reference
Definition at line 116 of file CompactListList.H.
const_reference
template<class T > typedef const T& const_reference
Definition at line 119 of file CompactListList.H.
size_type
template<class T > typedef label size_type
Definition at line 122 of file CompactListList.H.
Constructor & Destructor Documentation
CompactListList() [1/10]
template<class T > CompactListList () default noexcept
CompactListList() [2/10]
template<class T > CompactListList (const CompactListList< T > & list) inline
Definition at line 53 of file CompactListListI.H.
CompactListList() [3/10]
template<class T > CompactListList (CompactListList< T > && list) inline
Definition at line 64 of file CompactListListI.H.
CompactListList() [4/10]
template<class T > CompactListList (CompactListList< T > & list, bool reuse) inline
Definition at line 75 of file CompactListListI.H.
CompactListList() [5/10]
template<class T > CompactListList (const label mRows, const label nVals) inline
Definition at line 88 of file CompactListListI.H.
CompactListList() [6/10]
template<class T > CompactListList (const label mRows, const label nVals, const Foam::zero) inline
Definition at line 102 of file CompactListListI.H.
CompactListList() [7/10]
template<class T > CompactListList (const label mRows, const label nVals, const T & val) inline
Definition at line 117 of file CompactListListI.H.
CompactListList() [8/10]
template<class T > CompactListList (const labelUList & listSizes) explicit
Definition at line 139 of file CompactListList.C.
References PtrList< T >::resize(), and UPtrList< T >::size().
CompactListList() [9/10]
template<class T > CompactListList (const labelUList & listSizes, const T & val)
Definition at line 168 of file CompactListList.C.
References PtrList< T >::resize(), and UPtrList< T >::size().
CompactListList() [10/10]
template<class T > CompactListList (Istream & is) explicit
Definition at line 27 of file CompactListListIO.C.
Member Function Documentation
null()
template<class T > const Foam::CompactListList< T > & null () inline static
Definition at line 28 of file CompactListListI.H.
pack() [1/4]
template<class T > template<class SubListType = List<T>> static CompactListList< T > pack (const UList< SubListType > & lists, const bool checkOverflow = false) static
pack() [2/4]
template<class T > template<class SubListType , class Addr > static CompactListList< T > pack (const IndirectListBase< SubListType, Addr > & lists, const bool checkOverflow = false) static
clone()
template<class T > Foam::autoPtr< Foam::CompactListList< T > > clone () const inline
Definition at line 133 of file CompactListListI.H.
References Foam::New().
empty()
template<class T > bool empty () const inline noexcept
Definition at line 205 of file CompactListListI.H.
size()
template<class T > Foam::label size () const inline noexcept
Definition at line 212 of file CompactListListI.H.
totalSize()
template<class T > Foam::label totalSize () const inline
Definition at line 227 of file CompactListListI.H.
offsets() [1/2]
template<class T > const Foam::labelList & offsets () const inline noexcept
Definition at line 142 of file CompactListListI.H.
offsets() [2/2]
template<class T > Foam::labelList & offsets () inline noexcept
Definition at line 149 of file CompactListListI.H.
values() [1/2]
template<class T > const Foam::List< T > & values () const inline noexcept
Definition at line 156 of file CompactListListI.H.
values() [2/2]
template<class T > Foam::List< T > & values () inline noexcept
Definition at line 163 of file CompactListListI.H.
cdata()
template<class T > const T * cdata () const inline noexcept
Definition at line 170 of file CompactListListI.H.
data()
template<class T > T * data () inline noexcept
Definition at line 177 of file CompactListListI.H.
cdata_bytes()
template<class T > const char * cdata_bytes () const inline noexcept
Definition at line 184 of file CompactListListI.H.
data_bytes()
template<class T > char * data_bytes () inline noexcept
Definition at line 191 of file CompactListListI.H.
size_bytes()
template<class T > std::streamsize size_bytes () const inline noexcept
Definition at line 198 of file CompactListListI.H.
byteSize()
template<class T > std::streamsize byteSize () const
Definition at line 228 of file CompactListList.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
sizes()
template<class T > Foam::labelList sizes () const inline
Definition at line 220 of file CompactListListI.H.
localStarts()
template<class T > const Foam::labelUList localStarts () const inline
Definition at line 243 of file CompactListListI.H.
References UList< label >::null().
localSizes()
template<class T > Foam::labelList localSizes () const
Definition at line 323 of file CompactListList.C.
localStart()
template<class T > Foam::label localStart (const label i) const inline
Definition at line 254 of file CompactListListI.H.
localEnd()
template<class T > Foam::label localEnd (const label i) const inline
Definition at line 261 of file CompactListListI.H.
localSize()
template<class T > Foam::label localSize (const label i) const inline
Definition at line 268 of file CompactListListI.H.
ranges()
template<class T > Foam::List< Foam::labelRange > ranges () const
Definition at line 249 of file CompactListList.C.
range()
template<class T > Foam::labelRange range (const label i) const
Definition at line 241 of file CompactListList.C.
maxSize()
template<class T > Foam::label maxSize () const inline
Definition at line 235 of file CompactListListI.H.
clear()
template<class T > void clear () inline
Definition at line 347 of file CompactListListI.H.
References PtrList< T >::clear().
resize() [1/4]
template<class T > void resize (const label mRows) inline
Definition at line 355 of file CompactListListI.H.
References Foam::abort(), PtrList< T >::clear(), Foam::FatalError, FatalErrorInFunction, Foam::nl, and PtrList< T >::resize().
resize() [2/4]
template<class T > void resize (const label mRows, const label nVals) inline
Definition at line 382 of file CompactListListI.H.
References PtrList< T >::resize(), and Foam::Zero.
resize_nocopy()
template<class T > void resize_nocopy (const label mRows, const label nVals) inline
Definition at line 394 of file CompactListListI.H.
References PtrList< T >::resize(), and Foam::Zero.
resize() [3/4]
template<class T > void resize (const label mRows, const label nVals, const T & val) inline
Definition at line 406 of file CompactListListI.H.
References PtrList< T >::resize(), and Foam::Zero.
resize() [4/4]
template<class T > void resize (const labelUList & listSizes)
Definition at line 272 of file CompactListList.C.
References clear(), PtrList< T >::resize(), and UPtrList< T >::size().
setLocalSize()
template<class T > void setLocalSize (const label rowi, const label len)
Definition at line 304 of file CompactListList.C.
References delta, and UPtrList< T >::size().
setSize() [1/4]
template<class T > void setSize (const label mRows) inline
Definition at line 420 of file CompactListListI.H.
References resize().
setSize() [2/4]
template<class T > void setSize (const label mRows, const label nVals) inline
Definition at line 427 of file CompactListListI.H.
References resize().
setSize() [3/4]
template<class T > void setSize (const label mRows, const label nVals, const T & val) inline
Definition at line 438 of file CompactListListI.H.
References resize().
setSize() [4/4]
template<class T > void setSize (const labelUList & listSizes) inline
Definition at line 450 of file CompactListListI.H.
References resize().
swap()
template<class T > void swap (CompactListList< T > & other)
Definition at line 346 of file CompactListList.C.
References UPtrList< T >::swap().
transfer()
template<class T > void transfer (CompactListList< T > & list)
Definition at line 362 of file CompactListList.C.
References PtrList< T >::transfer().
Referenced by CompactListList< T >::operator=().
toGlobal()
template<class T > Foam::label toGlobal (const label rowi, const label i) const inline
Definition at line 291 of file CompactListListI.H.
Referenced by CompactListList< T >::index().
toLocal()
template<class T > Foam::label toLocal (const label rowi, const label i) const inline
Definition at line 302 of file CompactListListI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and Foam::nl.
Referenced by CompactListList< T >::whichColumn().
findRow()
template<class T > Foam::label findRow (const label i) const inline
Definition at line 323 of file CompactListListI.H.
References Foam::findLower().
whichRow()
template<class T > Foam::label whichRow (const label i) const inline
Definition at line 330 of file CompactListListI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and Foam::nl.
unpack() [1/4]
template<class T > template<class SubListType = List<T>> List< SubListType > unpack () const
unpack() [2/4]
template<class T > template<class SubListType = List<T>> List< SubListType > unpack (const labelRange & range) const
operator=() [1/4]
template<class T > void operator= (const CompactListList< T > & list) inline
Definition at line 462 of file CompactListListI.H.
operator=() [2/4]
template<class T > void operator= (CompactListList< T > && list) inline
Definition at line 478 of file CompactListListI.H.
References CompactListList< T >::transfer(), and PtrList< T >::transfer().
operator=() [3/4]
template<class T > void operator= (const T & val) inline
Definition at line 494 of file CompactListListI.H.
operator=() [4/4]
template<class T > void operator= (const Foam::zero) inline
Definition at line 501 of file CompactListListI.H.
References Foam::Zero.
localList() [1/2]
template<class T > Foam::UList< T > localList (const label i) inline
Definition at line 276 of file CompactListListI.H.
localList() [2/2]
template<class T > const Foam::UList< T > localList (const label i) const inline
Definition at line 284 of file CompactListListI.H.
operator[]() [1/2]
template<class T > Foam::UList< T > operator[] (const label i) inline
Definition at line 509 of file CompactListListI.H.
operator[]() [2/2]
template<class T > const Foam::UList< T > operator[] (const label i) const inline
Definition at line 517 of file CompactListListI.H.
operator()() [1/2]
template<class T > T & operator() (const label i, const label j) inline
Definition at line 524 of file CompactListListI.H.
operator()() [2/2]
template<class T > const T & operator() (const label i, const label j) const inline
Definition at line 535 of file CompactListListI.H.
readList()
template<class T > Foam::Istream & readList (Istream & is)
Definition at line 39 of file CompactListListIO.C.
writeList()
template<class T > Foam::Ostream & writeList (Ostream & os, const label shortLen = 0) const
Definition at line 49 of file CompactListListIO.C.
References os().
m() [1/2]
template<class T > const List< T > & m () const inline noexcept
Definition at line 413 of file CompactListList.H.
m() [2/2]
template<class T > List< T > & m () inline noexcept
Definition at line 416 of file CompactListList.H.
index()
template<class T > label index (const label rowi, const label colj) const inline
Definition at line 419 of file CompactListList.H.
References CompactListList< T >::toGlobal().
whichColumn()
template<class T > label whichColumn (const label rowi, const label i) const inline
Definition at line 425 of file CompactListList.H.
References CompactListList< T >::toLocal().
packImpl()
template<class T > template<class ListListType > Foam::CompactListList< T > packImpl (const ListListType & lists, const bool checkOverflow)
Definition at line 52 of file CompactListList.C.
References UPtrList< T >::begin(), forAll, PtrList< T >::resize(), UPtrList< T >::size(), and Foam::Zero.
pack() [3/4]
template<class T > template<class SubListType > Foam::CompactListList< T > pack (const UList< SubListType > & lists, const bool checkOverflow)
Definition at line 106 of file CompactListList.C.
pack() [4/4]
template<class T > template<class SubListType , class Addr > Foam::CompactListList< T > pack (const IndirectListBase< SubListType, Addr > & lists, const bool checkOverflow)
Definition at line 122 of file CompactListList.C.
unpack() [3/4]
template<class T > template<class SubListType > Foam::List< SubListType > unpack () const
Definition at line 380 of file CompactListList.C.
References forAll.
unpack() [4/4]
template<class T > template<class SubListType > Foam::List< SubListType > unpack (const labelRange & range) const
Definition at line 396 of file CompactListList.C.
References UPtrList< T >::begin(), range, and UPtrList< T >::size().
Friends And Related Symbol Documentation
operator>>
template<class T > Istream & operator>> (Istream & is, CompactListList< T > & list) friend
Definition at line 437 of file CompactListList.H.
operator<<
template<class T > Ostream & operator<< (Ostream & os, const CompactListList< T > & list) friend
Definition at line 443 of file CompactListList.H.
The documentation for this class was generated from the following files:
src/meshTools/polyTopoChange/polyTopoChange.H
src/OpenFOAM/containers/CompactLists/CompactListList/CompactListList.H
src/OpenFOAM/containers/CompactLists/CompactListList/CompactListList.C
src/OpenFOAM/containers/CompactLists/CompactListList/CompactListListI.H
src/OpenFOAM/containers/CompactLists/CompactListList/CompactListListIO.C