OpenFOAM: externalDisplacementMeshMover Class Reference
externalDisplacementMeshMover Class Reference abstract
Virtual base class for mesh movers with externally provided displacement field giving the boundary conditions. Move the mesh from the current location to a new location (so modify the mesh; v.s. motionSolver that only returns the new location).
#include <externalDisplacementMeshMover.H>
Public Member Functions
TypeName ("externalDisplacementMeshMover")
declareRunTimeSelectionTable (autoPtr, externalDisplacementMeshMover, dictionary,(const dictionary &dict, const List< labelPair > &baffles, pointVectorField &pointDisplacement, const bool dryRun),(dict, baffles, pointDisplacement, dryRun))
externalDisplacementMeshMover (const dictionary &dict, const List< labelPair > &baffles, pointVectorField &pointDisplacement, const bool dryRun)
virtual ~externalDisplacementMeshMover ()
pointVectorField & pointDisplacement ()
const pointVectorField & pointDisplacement () const
const pointMesh & pMesh () const
const polyMesh & mesh () const
virtual bool move (const dictionary &, const label nAllowableErrors, labelList &checkFaces)=0
virtual void movePoints (const pointField &)
virtual void updateMesh (const mapPolyMesh &)
Static Public Member Functions
static autoPtr< externalDisplacementMeshMover > New (const word &type, const dictionary &dict, const List< labelPair > &baffles, pointVectorField &pointDisplacement, const bool dryRun=false)
Static Protected Member Functions
static labelList getFixedValueBCs (const pointVectorField &)
static autoPtr< indirectPrimitivePatch > getPatch (const polyMesh &, const labelList &)
Protected Attributes
List< labelPair > baffles_
pointVectorField & pointDisplacement_
const bool dryRun_
Detailed Description
Virtual base class for mesh movers with externally provided displacement field giving the boundary conditions. Move the mesh from the current location to a new location (so modify the mesh; v.s. motionSolver that only returns the new location).
All mesh movers are expected to read the dictionary settings at invocation of move(), i.e. not cache any settings.
Source files
externalDisplacementMeshMover.H
externalDisplacementMeshMover.C
Definition at line 54 of file externalDisplacementMeshMover.H.
Constructor & Destructor Documentation
externalDisplacementMeshMover()
externalDisplacementMeshMover (const dictionary & dict, const List< labelPair > & baffles, pointVectorField & pointDisplacement, const bool dryRun)
Definition at line 112 of file externalDisplacementMeshMover.C.
~externalDisplacementMeshMover()
~externalDisplacementMeshMover () virtual
Definition at line 162 of file externalDisplacementMeshMover.C.
Member Function Documentation
getFixedValueBCs()
Foam::labelList getFixedValueBCs (const pointVectorField & field) static protected
Definition at line 37 of file externalDisplacementMeshMover.C.
References PtrList< T >::append(), field(), forAll, and Foam::isA().
getPatch()
Foam::autoPtr< Foam::indirectPrimitivePatch > getPatch (const polyMesh & mesh, const labelList & patchIDs) static protected
Definition at line 68 of file externalDisplacementMeshMover.C.
References polyMesh::boundaryMesh(), polyMesh::faces(), forAll, mesh, autoPtr< T >::New(), patches, patchIDs(), polyMesh::points(), and pp().
TypeName()
TypeName ("externalDisplacementMeshMover")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , externalDisplacementMeshMover , dictionary , (const dictionary &dict, const List< labelPair > &baffles, pointVectorField &pointDisplacement, const bool dryRun) , (dict, baffles, pointDisplacement, dryRun))
New()
Foam::autoPtr< Foam::externalDisplacementMeshMover > New (const word & type, const dictionary & dict, const List< labelPair > & baffles, pointVectorField & pointDisplacement, const bool dryRun = false) static
Definition at line 129 of file externalDisplacementMeshMover.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, Foam::Info, and Foam::type().
Referenced by displacementMeshMoverMotionSolver::meshMover().
pointDisplacement() [1/2]
pointVectorField & pointDisplacement () inline
Definition at line 155 of file externalDisplacementMeshMover.H.
References externalDisplacementMeshMover::pointDisplacement_.
pointDisplacement() [2/2]
const pointVectorField & pointDisplacement () const inline
Definition at line 161 of file externalDisplacementMeshMover.H.
References externalDisplacementMeshMover::pointDisplacement_.
pMesh()
const pointMesh & pMesh () const inline
Definition at line 166 of file externalDisplacementMeshMover.H.
References DimensionedField< Type, GeoMesh >::mesh(), and externalDisplacementMeshMover::pointDisplacement_.
Referenced by externalDisplacementMeshMover::mesh().
mesh()
const polyMesh & mesh () const inline
Definition at line 171 of file externalDisplacementMeshMover.H.
References externalDisplacementMeshMover::pMesh().
move()
virtual bool move (const dictionary & , const label nAllowableErrors, labelList & checkFaces) pure virtual
Implemented in displacementMotionSolverMeshMover, and medialAxisMeshMover.
movePoints()
void movePoints (const pointField &) virtual
Reimplemented in displacementMotionSolverMeshMover, and medialAxisMeshMover.
Definition at line 168 of file externalDisplacementMeshMover.C.
Referenced by displacementMotionSolverMeshMover::movePoints(), and medialAxisMeshMover::movePoints().
updateMesh()
void updateMesh (const mapPolyMesh & mpm) virtual
Reimplemented in displacementMotionSolverMeshMover, and medialAxisMeshMover.
Definition at line 174 of file externalDisplacementMeshMover.C.
References PtrList< T >::append(), forAll, and PtrList< T >::transfer().
Member Data Documentation
baffles_
List<labelPair> baffles_ protected
Definition at line 61 of file externalDisplacementMeshMover.H.
pointDisplacement_
pointVectorField& pointDisplacement_ protected
Definition at line 64 of file externalDisplacementMeshMover.H.
Referenced by externalDisplacementMeshMover::pMesh(), externalDisplacementMeshMover::pointDisplacement(), and externalDisplacementMeshMover::pointDisplacement().
dryRun_
const bool dryRun_ protected
Definition at line 67 of file externalDisplacementMeshMover.H.
The documentation for this class was generated from the following files:
src/mesh/snappyHexMesh/externalDisplacementMeshMover/externalDisplacementMeshMover.H
src/mesh/snappyHexMesh/externalDisplacementMeshMover/externalDisplacementMeshMover.C