OpenFOAM: refinementSurfaces Class Reference
refinementSurfaces Class Reference
Container for data on surfaces used for surface-driven refinement. Contains all the data about the level of refinement needed per surface.
#include <refinementSurfaces.H>
Public Member Functions
refinementSurfaces (const searchableSurfaces &allGeometry, const dictionary &, const label gapLevelIncrement, const bool dryRun)
refinementSurfaces (const searchableSurfaces &allGeometry, const labelList &surfaces, const wordList &names, const PtrList< surfaceZonesInfo > &surfZones, const labelList &regionOffset, const labelList &minLevel, const labelList &maxLevel, const labelList &gapLevel, const scalarField &perpendicularAngle, PtrList< dictionary > &patchInfo, const bool dryRun)
const searchableSurfaces & geometry () const
const labelList & surfaces () const
const wordList & names () const
const PtrList< surfaceZonesInfo > & surfZones () const
const labelList & regionOffset () const
const labelList & minLevel () const
const labelList & maxLevel () const
const labelList & gapLevel () const
const labelList & blockLevel () const
const labelList & leakLevel () const
const List< FixedList< label, 3 > > & extendedGapLevel () const
const List< volumeType > & extendedGapMode () const
const boolList & gapSelf () const
const List< FixedList< label, 4 > > & extendedCurvatureLevel () const
const scalarField & perpendicularAngle () const
const PtrList< dictionary > & patchInfo () const
label globalRegion (const label surfI, const label regionI) const
labelPair whichSurface (const label globalRegionI) const
label minLevel (const label surfI, const label regionI) const
label maxLevel (const label surfI, const label regionI) const
label nRegions () const
labelList maxGapLevel () const
labelList maxCurvatureLevel () const
void setMinLevelFields (const shellSurfaces &shells)
void setCurvatureMinLevelFields (const scalar cosAngle, const scalar level0EdgeLength)
void findHigherIntersection (const shellSurfaces &shells, const pointField &start, const pointField &end, const labelList &currentLevel, labelList &surfaces, labelList &surfaceLevel) const
void findAllIntersections (const pointField &start, const pointField &end, const labelList &currentLevel, const labelList &globalMinLevel, const labelList &globalMaxLevel, List< vectorList > &surfaceNormal, labelListList &surfaceLevel) const
void findAllIntersections (const pointField &start, const pointField &end, const labelList &currentLevel, const labelList &globalMinLevel, const labelList &globalMaxLevel, List< pointList > &surfaceLocation, List< vectorList > &surfaceNormal, labelListList &surfaceLevel) const
void findNearestIntersection (const labelList &surfacesToTest, const pointField &start, const pointField &end, labelList &surface1, List< pointIndexHit > &hit1, labelList &region1, labelList &surface2, List< pointIndexHit > &hit2, labelList &region2) const
void findNearestIntersection (const labelList &surfacesToTest, const pointField &start, const pointField &end, labelList &surface1, List< pointIndexHit > &hit1, labelList &region1, vectorField &normal1, labelList &surface2, List< pointIndexHit > &hit2, labelList &region2, vectorField &normal2) const
void findNearestIntersection (const pointField &start, const pointField &end, labelList &surfaces, vectorField &normal) const
void findNearestIntersection (const pointField &start, const pointField &end, labelList &surfaces, List< pointIndexHit > &, vectorField &normal) const
void findAnyIntersection (const pointField &start, const pointField &end, labelList &surfaces, List< pointIndexHit > &) const
void findNearest (const labelList &surfacesToTest, const pointField &samples, const scalarField &nearestDistSqr, labelList &surfaces, List< pointIndexHit > &) const
void findNearestRegion (const labelList &surfacesToTest, const pointField &samples, const scalarField &nearestDistSqr, labelList &hitSurface, labelList &hitRegion) const
void findNearestRegion (const labelList &surfacesToTest, const pointField &samples, const scalarField &nearestDistSqr, labelList &hitSurface, List< pointIndexHit > &hitInfo, labelList &hitRegion, vectorField &hitNormal) const
void findInside (const labelList &surfacesToTest, const pointField &pt, labelList &insideSurfaces) const
void findNearest (const labelList &surfacesToTest, const labelListList &regions, const pointField &samples, const scalarField &nearestDistSqr, labelList &hitSurface, List< pointIndexHit > &hitInfo) const
void findNearestRegion (const labelList &surfacesToTest, const labelListList &regions, const pointField &samples, const scalarField &nearestDistSqr, labelList &hitSurface, List< pointIndexHit > &hitInfo, labelList &hitRegion, vectorField &hitNormal) const
Detailed Description
Container for data on surfaces used for surface-driven refinement. Contains all the data about the level of refinement needed per surface.
Source files
refinementSurfaces.H
refinementSurfaces.C
Definition at line 59 of file refinementSurfaces.H.
Constructor & Destructor Documentation
refinementSurfaces() [1/2]
refinementSurfaces (const searchableSurfaces & allGeometry, const dictionary & surfacesDict, const label gapLevelIncrement, const bool dryRun)
Definition at line 149 of file refinementSurfaces.C.
References PtrList< T >::clone(), dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, forAll, forAllConstIters, UPtrList< T >::get(), IOWarningInFunction, Foam::labelMax, volumeType::MIXED, refinementSurfaces::nRegions(), keyType::REGEX, regionNames, PtrList< T >::set(), List< T >::setSize(), PtrList< T >::setSize(), UPtrList< T >::size(), volumeType::UNKNOWN, and Foam::Zero.
refinementSurfaces() [2/2]
refinementSurfaces (const searchableSurfaces & allGeometry, const labelList & surfaces, const wordList & names, const PtrList< surfaceZonesInfo > & surfZones, const labelList & regionOffset, const labelList & minLevel, const labelList & maxLevel, const labelList & gapLevel, const scalarField & perpendicularAngle, PtrList< dictionary > & patchInfo, const bool dryRun)
Definition at line 636 of file refinementSurfaces.C.
References forAll, refinementSurfaces::patchInfo(), and PtrList< T >::set().
Member Function Documentation
geometry()
const searchableSurfaces & geometry () const inline
Definition at line 181 of file refinementSurfaces.H.
Referenced by snappySnapDriver::calcNearestSurface().
surfaces()
const labelList & surfaces () const inline
Definition at line 186 of file refinementSurfaces.H.
Referenced by snappySnapDriver::calcNearestSurface(), snappySnapDriver::detectNearSurfaces(), and snappySnapDriver::repatchToSurface().
names()
const wordList & names () const inline
Definition at line 192 of file refinementSurfaces.H.
surfZones()
const PtrList< surfaceZonesInfo > & surfZones () const inline
Definition at line 197 of file refinementSurfaces.H.
Referenced by snappySnapDriver::calcNearestSurface(), snappySnapDriver::detectNearSurfaces(), and snappySnapDriver::repatchToSurface().
regionOffset()
const labelList & regionOffset () const inline
Definition at line 203 of file refinementSurfaces.H.
minLevel() [1/2]
const labelList & minLevel () const inline
Definition at line 209 of file refinementSurfaces.H.
maxLevel() [1/2]
const labelList & maxLevel () const inline
Definition at line 215 of file refinementSurfaces.H.
gapLevel()
const labelList & gapLevel () const inline
Definition at line 221 of file refinementSurfaces.H.
blockLevel()
const labelList & blockLevel () const inline
Definition at line 228 of file refinementSurfaces.H.
leakLevel()
const labelList & leakLevel () const inline
Definition at line 235 of file refinementSurfaces.H.
extendedGapLevel()
const List< FixedList< label, 3 > > & extendedGapLevel () const inline
Definition at line 246 of file refinementSurfaces.H.
extendedGapMode()
const List< volumeType > & extendedGapMode () const inline
Definition at line 252 of file refinementSurfaces.H.
gapSelf()
const boolList & gapSelf () const inline
Definition at line 259 of file refinementSurfaces.H.
extendedCurvatureLevel()
const List< FixedList< label, 4 > > & extendedCurvatureLevel () const inline
Definition at line 272 of file refinementSurfaces.H.
perpendicularAngle()
const scalarField & perpendicularAngle () const inline
Definition at line 278 of file refinementSurfaces.H.
patchInfo()
const PtrList< dictionary > & patchInfo () const inline
Definition at line 284 of file refinementSurfaces.H.
Referenced by refinementSurfaces::refinementSurfaces().
globalRegion()
label globalRegion (const label surfI, const label regionI) const inline
Definition at line 293 of file refinementSurfaces.H.
Referenced by snappySnapDriver::calcNearestSurface(), refinementSurfaces::maxLevel(), refinementSurfaces::minLevel(), and snappySnapDriver::repatchToSurface().
whichSurface()
Foam::labelPair whichSurface (const label globalRegionI) const
Definition at line 676 of file refinementSurfaces.C.
minLevel() [2/2]
label minLevel (const label surfI, const label regionI) const inline
Definition at line 302 of file refinementSurfaces.H.
References refinementSurfaces::globalRegion().
maxLevel() [2/2]
label maxLevel (const label surfI, const label regionI) const inline
Definition at line 308 of file refinementSurfaces.H.
References refinementSurfaces::globalRegion().
nRegions()
label nRegions () const inline
Definition at line 313 of file refinementSurfaces.H.
References UList< T >::size().
Referenced by refinementSurfaces::refinementSurfaces().
maxGapLevel()
Foam::labelList maxGapLevel () const
Definition at line 742 of file refinementSurfaces.C.
References forAll, Foam::max(), regionNames, and Foam::Zero.
maxCurvatureLevel()
Foam::labelList maxCurvatureLevel () const
Definition at line 761 of file refinementSurfaces.C.
References forAll, Foam::max(), regionNames, and Foam::Zero.
setMinLevelFields()
void setMinLevelFields (const shellSurfaces & shells)
Definition at line 783 of file refinementSurfaces.C.
References Foam::endl(), forAll, Foam::Info, Foam::labelMax, Foam::max(), Foam::min(), points, Foam::returnReduce(), setField(), UPtrList< T >::size(), and Foam::Zero.
setCurvatureMinLevelFields()
void setCurvatureMinLevelFields (const scalar cosAngle, const scalar level0EdgeLength)
Definition at line 917 of file refinementSurfaces.C.
References triSurfaceTools::curvatures(), f(), forAll, Foam::max(), Foam::min(), points, PtrList< T >::set(), setField(), UPtrList< T >::size(), and Foam::Zero.
findHigherIntersection()
void findHigherIntersection (const shellSurfaces & shells, const pointField & start, const pointField & end, const labelList & currentLevel, labelList & surfaces, labelList & surfaceLevel) const
Definition at line 1223 of file refinementSurfaces.C.
References forAll, Foam::identity(), p0, Foam::returnReduceAnd(), List< T >::setSize(), PtrList< T >::setSize(), UPtrList< T >::size(), and UList< T >::size().
findAllIntersections() [1/2]
void findAllIntersections (const pointField & start, const pointField & end, const labelList & currentLevel, const labelList & globalMinLevel, const labelList & globalMaxLevel, List< vectorList > & surfaceNormal, labelListList & surfaceLevel) const
Definition at line 1385 of file refinementSurfaces.C.
References PtrList< T >::clear(), forAll, n, PtrList< T >::setSize(), UPtrList< T >::size(), and UList< T >::size().
findAllIntersections() [2/2]
void findAllIntersections (const pointField & start, const pointField & end, const labelList & currentLevel, const labelList & globalMinLevel, const labelList & globalMaxLevel, List< pointList > & surfaceLocation, List< vectorList > & surfaceNormal, labelListList & surfaceLevel) const
Definition at line 1476 of file refinementSurfaces.C.
References forAll, n, PtrList< T >::setSize(), UPtrList< T >::size(), and UList< T >::size().
findNearestIntersection() [1/4]
void findNearestIntersection (const labelList & surfacesToTest, const pointField & start, const pointField & end, labelList & surface1, List< pointIndexHit > & hit1, labelList & region1, labelList & surface2, List< pointIndexHit > & hit2, labelList & region2) const
Definition at line 1653 of file refinementSurfaces.C.
References forAll, PtrList< T >::setSize(), and UList< T >::size().
Referenced by snappySnapDriver::detectNearSurfaces().
findNearestIntersection() [2/4]
void findNearestIntersection (const labelList & surfacesToTest, const pointField & start, const pointField & end, labelList & surface1, List< pointIndexHit > & hit1, labelList & region1, vectorField & normal1, labelList & surface2, List< pointIndexHit > & hit2, labelList & region2, vectorField & normal2) const
Definition at line 1783 of file refinementSurfaces.C.
References forAll, PtrList< T >::setSize(), UList< T >::size(), and Foam::Zero.
findNearestIntersection() [3/4]
void findNearestIntersection (const pointField & start, const pointField & end, labelList & surfaces, vectorField & normal) const
Definition at line 1906 of file refinementSurfaces.C.
References forAll, PtrList< T >::setSize(), UList< T >::size(), and Foam::Zero.
findNearestIntersection() [4/4]
void findNearestIntersection (const pointField & start, const pointField & end, labelList & surfaces, List< pointIndexHit > & hitInfo1, vectorField & normal) const
Definition at line 1949 of file refinementSurfaces.C.
References forAll, PtrList< T >::setSize(), UList< T >::size(), and Foam::Zero.
findAnyIntersection()
void findAnyIntersection (const pointField & start, const pointField & end, labelList & surfaces, List< pointIndexHit > & hitInfo) const
Definition at line 1999 of file refinementSurfaces.C.
References searchableSurfacesQueries::findAnyIntersection().
findNearest() [1/2]
void findNearest (const labelList & surfacesToTest, const pointField & samples, const scalarField & nearestDistSqr, labelList & surfaces, List< pointIndexHit > & hitInfo) const
Definition at line 2020 of file refinementSurfaces.C.
References searchableSurfacesQueries::findNearest(), forAll, and samples().
Referenced by snappySnapDriver::calcNearestSurface().
findNearestRegion() [1/3]
void findNearestRegion (const labelList & surfacesToTest, const pointField & samples, const scalarField & nearestDistSqr, labelList & hitSurface, labelList & hitRegion) const
Definition at line 2053 of file refinementSurfaces.C.
References Foam::findIndices(), searchableSurfacesQueries::findNearest(), forAll, samples(), PtrList< T >::setSize(), and UPtrList< T >::size().
Referenced by snappySnapDriver::calcNearestSurface(), and snappySnapDriver::repatchToSurface().
findNearestRegion() [2/3]
void findNearestRegion (const labelList & surfacesToTest, const pointField & samples, const scalarField & nearestDistSqr, labelList & hitSurface, List< pointIndexHit > & hitInfo, labelList & hitRegion, vectorField & hitNormal) const
Definition at line 2116 of file refinementSurfaces.C.
References Foam::findIndices(), searchableSurfacesQueries::findNearest(), forAll, samples(), PtrList< T >::setSize(), UPtrList< T >::size(), and Foam::Zero.
findInside()
void findInside (const labelList & surfacesToTest, const pointField & pt, labelList & insideSurfaces) const
Definition at line 2237 of file refinementSurfaces.C.
References surfaceZonesInfo::areaSelectionAlgoNames, Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, surfaceZonesInfo::INSIDE, volumeType::INSIDE, surfaceZonesInfo::OUTSIDE, volumeType::OUTSIDE, PtrList< T >::setSize(), and UList< T >::size().
findNearest() [2/2]
void findNearest (const labelList & surfacesToTest, const labelListList & regions, const pointField & samples, const scalarField & nearestDistSqr, labelList & hitSurface, List< pointIndexHit > & hitInfo) const
Definition at line 2300 of file refinementSurfaces.C.
References searchableSurfacesQueries::findNearest(), forAll, and samples().
findNearestRegion() [3/3]
void findNearestRegion (const labelList & surfacesToTest, const labelListList & regions, const pointField & samples, const scalarField & nearestDistSqr, labelList & hitSurface, List< pointIndexHit > & hitInfo, labelList & hitRegion, vectorField & hitNormal) const
Definition at line 2337 of file refinementSurfaces.C.
References Foam::findIndices(), searchableSurfacesQueries::findNearest(), forAll, samples(), PtrList< T >::setSize(), UPtrList< T >::size(), and Foam::Zero.
The documentation for this class was generated from the following files:
src/mesh/snappyHexMesh/refinementSurfaces/refinementSurfaces.H
src/mesh/snappyHexMesh/refinementSurfaces/refinementSurfaces.C