OpenFOAM: undoableMeshCutter Class Reference
undoableMeshCutter Class Reference
The main refinement handler. Gets cellCuts which is structure that describes which cells are to be cut and in what way. Maintains an undo list (if told so during construction). Apart from undo list is just wrapper around meshCutter.
#include <undoableMeshCutter.H>
Public Member Functions
ClassName ("undoableMeshCutter")
undoableMeshCutter (const polyMesh &mesh, const bool undoable=true)
~undoableMeshCutter ()
const Map< splitCell * > & liveSplitCells () const
const removeFaces & faceRemover () const
void setRefinement (const cellCuts &cuts, polyTopoChange &)
void updateMesh (const mapPolyMesh &morphMap)
labelList getSplitFaces () const
Map< label > getAddedCells () const
labelList removeSplitFaces (const labelList &splitFaces, polyTopoChange &)
Public Member Functions inherited from meshCutter
ClassName ("meshCutter")
meshCutter (const polyMesh &mesh)
~meshCutter ()=default
void setRefinement (const cellCuts &cuts, polyTopoChange &meshMod)
void updateMesh (const mapPolyMesh &)
const Map< label > & addedCells () const
const Map< label > & addedFaces () const
const EdgeMap< label > & addedPoints () const
Public Member Functions inherited from edgeVertex
edgeVertex (const polyMesh &mesh)
const polyMesh & mesh () const
bool isEdge (const label eVert) const
label getEdge (const label eVert) const
label getVertex (const label eVert) const
label vertToEVert (const label vertI) const
label edgeToEVert (const label edgeI) const
point coord (const label cut, const scalar weight) const
label cutPairToEdge (const label cut0, const label cut1) const
Ostream & writeCut (Ostream &os, const label cut, const scalar) const
Ostream & writeCuts (Ostream &os, const labelList &, const scalarField &) const
Additional Inherited Members
Static Public Member Functions inherited from edgeVertex
static void updateLabels (const labelList &map, List< refineCell > &)
static void updateLabels (const labelList &map, Map< label > &)
static void updateLabels (const labelList &map, labelHashSet &)
static bool isEdge (const primitiveMesh &mesh, const label eVert)
static label getEdge (const primitiveMesh &mesh, const label eVert)
static label getVertex (const primitiveMesh &mesh, const label eVert)
static label vertToEVert (const primitiveMesh &mesh, const label vertI)
static label edgeToEVert (const primitiveMesh &mesh, const label edgeI)
static point coord (const primitiveMesh &, const label cut, const scalar weight)
static label cutPairToEdge (const primitiveMesh &, const label cut0, const label cut1)
Detailed Description
The main refinement handler. Gets cellCuts which is structure that describes which cells are to be cut and in what way. Maintains an undo list (if told so during construction). Apart from undo list is just wrapper around meshCutter.
Undo list: contains a refinement tree (of type splitCell; cell labels are of no consequence) and a list of visible splitCells, i.e. the top of the tree (where the cell labels are valid). Now every cell added gets put on the tree and every updateMesh action updates the labels of visible splitcells.
We can now ask this structure for a list of visible split cells or the list of faces between these. These can be passed to removeFaces for actual deletion and we delete the top splitCell and update the now newly visible underlying cells for the new cell number (passed back from removeFaces).
NOTE: Undoing note properly tested. Expect it to fail if the faces to be removed cause other faces to be additionally removed (i.e. removeFaces adds additional faces to remove).
splitCell:
original cell number.
pointer to parent (null for first level splitCell)
two pointers to splitCell children. Both null (unrefined=visible cell) or both non-null.
live are: (-all unrefined cells (original cell without any splitCells)) -all splitCells with null children
liveSplitCells contains pointers to splitCells with null children.
Source files
undoableMeshCutter.H
undoableMeshCutter.C
Definition at line 89 of file undoableMeshCutter.H.
Constructor & Destructor Documentation
undoableMeshCutter()
undoableMeshCutter (const polyMesh & mesh, const bool undoable = true) explicit
Definition at line 170 of file undoableMeshCutter.C.
~undoableMeshCutter()
~undoableMeshCutter ()
Definition at line 189 of file undoableMeshCutter.C.
References forAllIters.
Member Function Documentation
ClassName()
ClassName ("undoableMeshCutter")
liveSplitCells()
const Map< splitCell * > & liveSplitCells () const inline
Definition at line 161 of file undoableMeshCutter.H.
faceRemover()
const removeFaces & faceRemover () const inline
Definition at line 166 of file undoableMeshCutter.H.
setRefinement()
void setRefinement (const cellCuts & cuts, polyTopoChange & meshMod)
Definition at line 223 of file undoableMeshCutter.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAllConstIters, Foam::Pout, and meshCutter::setRefinement().
updateMesh()
void updateMesh (const mapPolyMesh & morphMap)
Definition at line 316 of file undoableMeshCutter.C.
References meshCutter::updateMesh().
getSplitFaces()
Foam::labelList getSplitFaces () const
Definition at line 334 of file undoableMeshCutter.C.
References Foam::abort(), PtrList< T >::append(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAllConstIters, Foam::meshTools::getSharedFace(), and mesh.
getAddedCells()
Foam::Map< Foam::label > getAddedCells () const
Definition at line 393 of file undoableMeshCutter.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, and forAllConstIters.
removeSplitFaces()
Foam::labelList removeSplitFaces (const labelList & splitFaces, polyTopoChange & meshMod)
important: Redo search since ownFind entry deleted.
Definition at line 439 of file undoableMeshCutter.C.
References Foam::abort(), Foam::endl(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), Foam::FatalError, FatalErrorInFunction, forAll, mesh, Foam::Pout, and UPtrList< T >::size().
The documentation for this class was generated from the following files:
src/dynamicMesh/meshCut/meshModifiers/undoableMeshCutter/undoableMeshCutter.H
src/dynamicMesh/meshCut/meshModifiers/undoableMeshCutter/undoableMeshCutter.C