OpenFOAM: IndirectListBase< T, Addr > Class Template Reference
IndirectListBase< T, Addr > Class Template Reference
Base for lists with indirect addressing, templated on the list contents type and the addressing type. Storage for both values and addressing is held outside of the class.
#include <IndirectListBase.H>
Classes
class const_iterator
class iterator
Public Types
typedef T value_type
typedef T * pointer
typedef const T * const_pointer
typedef T & reference
typedef const T & const_reference
typedef label size_type
typedef label difference_type
typedef Addr addressing_type
Public Member Functions
IndirectListBase ()=delete
IndirectListBase (const UList< T > &values, const Addr &addr)
bool empty () const noexcept
label size () const noexcept
const UList< T > & values () const noexcept
UList< T > & values () noexcept
const Addr & addressing () const noexcept
bool uniform () const
const T & front () const
T & front ()
const T & back () const
T & back ()
label fcIndex (const label i) const
label rcIndex (const label i) const
const T & fcValue (const label i) const
T & fcValue (const label i)
const T & rcValue (const label i) const
T & rcValue (const label i)
List< T > list () const
label find (const T &val, label pos=0) const
label rfind (const T &val, label pos=-1) const
bool contains (const T &val, label pos=0) const
List< T > operator() () const
T & operator[] (const label i)
const T & operator[] (const label i) const
void operator= (const T &val)
void operator= (const Foam::zero)
void operator= (const UList< T > &rhs)
void operator= (const IndirectListBase< T, Addr > &rhs)
template<class AnyAddr >
void operator= (const IndirectListBase< T, AnyAddr > &rhs)
iterator begin ()
iterator end ()
const_iterator cbegin () const
const_iterator cend () const
const_iterator begin () const
const_iterator end () const
Ostream & writeList (Ostream &os, const label shortLen=0) const
T & first ()
const T & first () const
T & last ()
const T & last () const
bool found (const T &val, label pos=0) const
Protected Member Functions
template<class ListType >
void copyList (const ListType &rhs)
Detailed Description
template<class T, class Addr>
class Foam::IndirectListBase< T, Addr >
Base for lists with indirect addressing, templated on the list contents type and the addressing type. Storage for both values and addressing is held outside of the class.
Source files
IndirectListBase.H
IndirectListBase.C
IndirectListBaseI.H
IndirectListBaseIO.C
Definition at line 52 of file IndirectListBase.H.
Member Typedef Documentation
value_type
template<class T , class Addr > typedef T value_type
Definition at line 77 of file IndirectListBase.H.
pointer
template<class T , class Addr > typedef T* pointer
Definition at line 80 of file IndirectListBase.H.
const_pointer
template<class T , class Addr > typedef const T* const_pointer
Definition at line 83 of file IndirectListBase.H.
reference
template<class T , class Addr > typedef T& reference
Definition at line 86 of file IndirectListBase.H.
const_reference
template<class T , class Addr > typedef const T& const_reference
Definition at line 89 of file IndirectListBase.H.
size_type
template<class T , class Addr > typedef label size_type
Definition at line 92 of file IndirectListBase.H.
difference_type
template<class T , class Addr > typedef label difference_type
Definition at line 95 of file IndirectListBase.H.
addressing_type
template<class T , class Addr > typedef Addr addressing_type
Definition at line 104 of file IndirectListBase.H.
Constructor & Destructor Documentation
IndirectListBase() [1/2]
template<class T , class Addr > IndirectListBase () delete
IndirectListBase() [2/2]
template<class T , class Addr > IndirectListBase (const UList< T > & values, const Addr & addr) inline
Definition at line 57 of file IndirectListBaseI.H.
Member Function Documentation
copyList()
template<class T , class Addr > template<class ListType > void copyList (const ListType & rhs) inline protected
Definition at line 25 of file IndirectListBaseI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and UPtrList< T >::size().
empty()
template<class T , class Addr > bool empty () const inline noexcept
Definition at line 121 of file IndirectListBase.H.
References UPtrList< T >::empty().
size()
template<class T , class Addr > label size () const inline noexcept
Definition at line 124 of file IndirectListBase.H.
References UPtrList< T >::size().
values() [1/2]
template<class T , class Addr > const UList< T > & values () const inline noexcept
Definition at line 127 of file IndirectListBase.H.
values() [2/2]
template<class T , class Addr > UList< T > & values () inline noexcept
Definition at line 130 of file IndirectListBase.H.
addressing()
template<class T , class Addr > const Addr & addressing () const inline noexcept
Definition at line 133 of file IndirectListBase.H.
uniform()
template<class T , class Addr > bool uniform () const inline
Definition at line 71 of file IndirectListBaseI.H.
References T.
front() [1/2]
template<class T , class Addr > const T & front () const inline
Definition at line 120 of file IndirectListBaseI.H.
Referenced by IndirectListBase< T, Addr >::first(), and IndirectListBase< T, Addr >::first().
front() [2/2]
template<class T , class Addr > T & front () inline
Definition at line 126 of file IndirectListBaseI.H.
back() [1/2]
template<class T , class Addr > const T & back () const inline
Definition at line 133 of file IndirectListBaseI.H.
Referenced by IndirectListBase< T, Addr >::last(), and IndirectListBase< T, Addr >::last().
back() [2/2]
template<class T , class Addr > T & back () inline
Definition at line 139 of file IndirectListBaseI.H.
fcIndex()
template<class T , class Addr > Foam::label fcIndex (const label i) const inline
Definition at line 106 of file IndirectListBaseI.H.
References UPtrList< T >::size().
rcIndex()
template<class T , class Addr > Foam::label rcIndex (const label i) const inline
Definition at line 113 of file IndirectListBaseI.H.
fcValue() [1/2]
template<class T , class Addr > const T & fcValue (const label i) const inline
Definition at line 146 of file IndirectListBaseI.H.
fcValue() [2/2]
template<class T , class Addr > T & fcValue (const label i) inline
Definition at line 153 of file IndirectListBaseI.H.
rcValue() [1/2]
template<class T , class Addr > const T & rcValue (const label i) const inline
Definition at line 160 of file IndirectListBaseI.H.
rcValue() [2/2]
template<class T , class Addr > T & rcValue (const label i) inline
Definition at line 167 of file IndirectListBaseI.H.
list()
template<class T , class Addr > Foam::List< T > list () const inline
Definition at line 173 of file IndirectListBaseI.H.
References UPtrList< T >::size().
Referenced by IndirectListBase< T, Addr >::operator()().
find()
template<class T , class Addr > Foam::label find (const T & val, label pos = 0) const
Definition at line 24 of file IndirectListBase.C.
References UPtrList< T >::begin(), Foam::pos(), UPtrList< T >::size(), and T.
rfind()
template<class T , class Addr > Foam::label rfind (const T & val, label pos = -1) const
Definition at line 52 of file IndirectListBase.C.
References UPtrList< T >::begin(), Foam::pos(), UPtrList< T >::size(), and T.
contains()
template<class T , class Addr > bool contains (const T & val, label pos = 0) const inline
Definition at line 95 of file IndirectListBaseI.H.
References Foam::pos().
Referenced by IndirectListBase< T, Addr >::found().
operator()()
template<class T , class Addr > List< T > operator() () const inline
Definition at line 199 of file IndirectListBase.H.
References IndirectListBase< T, Addr >::list().
operator[]() [1/2]
template<class T , class Addr > T & operator[] (const label i) inline
Definition at line 192 of file IndirectListBaseI.H.
operator[]() [2/2]
template<class T , class Addr > const T & operator[] (const label i) const inline
Definition at line 200 of file IndirectListBaseI.H.
operator=() [1/5]
template<class T , class Addr > void operator= (const T & val) inline
Definition at line 207 of file IndirectListBaseI.H.
operator=() [2/5]
template<class T , class Addr > void operator= (const Foam::zero) inline
Definition at line 218 of file IndirectListBaseI.H.
operator=() [3/5]
template<class T , class Addr > void operator= (const UList< T > & rhs) inline
Definition at line 229 of file IndirectListBaseI.H.
operator=() [4/5]
template<class T , class Addr > void operator= (const IndirectListBase< T, Addr > & rhs) inline
Definition at line 239 of file IndirectListBaseI.H.
operator=() [5/5]
template<class T , class Addr > template<class AnyAddr > void operator= (const IndirectListBase< T, AnyAddr > & rhs) inline
Definition at line 250 of file IndirectListBaseI.H.
begin() [1/2]
template<class T , class Addr > iterator begin () inline
Definition at line 324 of file IndirectListBase.H.
References UPtrList< T >::cbegin().
end() [1/2]
template<class T , class Addr > iterator end () inline
Definition at line 330 of file IndirectListBase.H.
References UPtrList< T >::cend().
cbegin()
template<class T , class Addr > const_iterator cbegin () const inline
Definition at line 339 of file IndirectListBase.H.
References UPtrList< T >::cbegin().
Referenced by IndirectListBase< T, Addr >::begin().
cend()
template<class T , class Addr > const_iterator cend () const inline
Definition at line 345 of file IndirectListBase.H.
References UPtrList< T >::cend().
Referenced by IndirectListBase< T, Addr >::end().
begin() [2/2]
template<class T , class Addr > const_iterator begin () const inline
Definition at line 351 of file IndirectListBase.H.
References IndirectListBase< T, Addr >::cbegin().
end() [2/2]
template<class T , class Addr > const_iterator end () const inline
Definition at line 354 of file IndirectListBase.H.
References IndirectListBase< T, Addr >::cend().
writeList()
template<class T , class Addr > Foam::Ostream & writeList (Ostream & os, const label shortLen = 0) const
Definition at line 30 of file IndirectListBaseIO.C.
References token::BEGIN_BLOCK, token::BEGIN_LIST, IOstreamOption::BINARY, token::END_BLOCK, token::END_LIST, FUNCTION_NAME, Foam::nl, os(), UPtrList< T >::size(), token::SPACE, and T.
first() [1/2]
template<class T , class Addr > T & first () inline
Definition at line 368 of file IndirectListBase.H.
References IndirectListBase< T, Addr >::front().
first() [2/2]
template<class T , class Addr > const T & first () const inline
Definition at line 372 of file IndirectListBase.H.
References IndirectListBase< T, Addr >::front().
last() [1/2]
template<class T , class Addr > T & last () inline
Definition at line 376 of file IndirectListBase.H.
References IndirectListBase< T, Addr >::back().
last() [2/2]
template<class T , class Addr > const T & last () const inline
Definition at line 380 of file IndirectListBase.H.
References IndirectListBase< T, Addr >::back().
found()
template<class T , class Addr > bool found (const T & val, label pos = 0) const inline
Definition at line 383 of file IndirectListBase.H.
References IndirectListBase< T, Addr >::contains(), and Foam::pos().
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/IndirectLists/IndirectListBase/IndirectListBase.H
src/OpenFOAM/containers/IndirectLists/IndirectListBase/IndirectListBase.C
src/OpenFOAM/containers/IndirectLists/IndirectListBase/IndirectListBaseI.H
src/OpenFOAM/containers/IndirectLists/IndirectListBase/IndirectListBaseIO.C