OpenFOAM: wallLubricationModel Class Reference
wallLubricationModel Class Reference abstract
#include <wallLubricationModel.H>
Public Member Functions
TypeName ("wallLubricationModel")
declareRunTimeSelectionTable (autoPtr, wallLubricationModel, dictionary,(const dictionary &dict, const phasePair &pair),(dict, pair))
wallLubricationModel (const dictionary &dict, const phasePair &pair)
virtual ~wallLubricationModel ()=default
virtual tmp< volVectorField > Fi () const =0
virtual tmp< volVectorField > F () const
virtual tmp< surfaceScalarField > Ff () const
TypeName ("wallLubricationModel")
declareRunTimeSelectionTable (autoPtr, wallLubricationModel, dictionary,(const dictionary &dict, const phasePair &pair),(dict, pair))
wallLubricationModel (const dictionary &dict, const phasePair &pair)
virtual ~wallLubricationModel ()=default
virtual tmp< volVectorField > Fi () const =0
virtual tmp< volVectorField > F () const
virtual tmp< surfaceScalarField > Ff () const
Public Member Functions inherited from wallDependentModel
wallDependentModel (const fvMesh &mesh)
virtual ~wallDependentModel ()
const volScalarField & yWall () const
const volVectorField & nWall () const
wallDependentModel (const fvMesh &mesh)
virtual ~wallDependentModel ()
const volScalarField & yWall () const
const volVectorField & nWall () const
Static Public Member Functions
static autoPtr< wallLubricationModel > New (const dictionary &dict, const phasePair &pair)
static autoPtr< wallLubricationModel > New (const dictionary &dict, const phasePair &pair)
Static Public Attributes
static const dimensionSet dimF
Protected Member Functions
tmp< volVectorField > zeroGradWalls (tmp< volVectorField >) const
Protected Attributes
const phasePair & pair_
Detailed Description
Source files
wallLubricationModel.H
wallLubricationModel.C
Source files
wallLubricationModel.H
wallLubricationModel.C
Definition at line 52 of file wallLubricationModel.H.
Constructor & Destructor Documentation
wallLubricationModel() [1/2]
wallLubricationModel (const dictionary & dict, const phasePair & pair)
Definition at line 68 of file wallLubricationModel.C.
~wallLubricationModel() [1/2]
virtual ~wallLubricationModel () virtual default
wallLubricationModel() [2/2]
wallLubricationModel (const dictionary & dict, const phasePair & pair)
~wallLubricationModel() [2/2]
virtual ~wallLubricationModel () virtual default
Member Function Documentation
zeroGradWalls()
Foam::tmp< Foam::volVectorField > zeroGradWalls (tmp< volVectorField > tFi) const protected
Definition at line 43 of file wallLubricationModel.C.
References wallLubricationModel::Fi(), forAll, and patches.
TypeName() [1/2]
TypeName ("wallLubricationModel")
declareRunTimeSelectionTable() [1/2]
declareRunTimeSelectionTable (autoPtr , wallLubricationModel , dictionary , (const dictionary &dict, const phasePair &pair) , (dict, pair))
New() [1/2]
Foam::autoPtr< Foam::wallLubricationModel > New (const dictionary & dict, const phasePair & pair) static
Definition at line 82 of file wallLubricationModel.C.
References Foam::abort(), dict, Foam::endl(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), and Foam::Info.
Fi() [1/2]
virtual tmp< volVectorField > Fi () const pure virtual
Implemented in Antal, Frank, noWallLubrication, TomiyamaWallLubrication, Antal, Frank, noWallLubrication, and TomiyamaWallLubrication.
Referenced by wallLubricationModel::zeroGradWalls().
F() [1/2]
Foam::tmp< Foam::volVectorField > F () const virtual
Reimplemented in noWallLubrication, and noWallLubrication.
Definition at line 112 of file wallLubricationModel.C.
Ff() [1/2]
Foam::tmp< Foam::surfaceScalarField > Ff () const virtual
Definition at line 118 of file wallLubricationModel.C.
References Foam::fvc::flux(), and Foam::fvc::interpolate().
TypeName() [2/2]
TypeName ("wallLubricationModel")
declareRunTimeSelectionTable() [2/2]
declareRunTimeSelectionTable (autoPtr , wallLubricationModel , dictionary , (const dictionary &dict, const phasePair &pair) , (dict, pair))
New() [2/2]
static autoPtr< wallLubricationModel > New (const dictionary & dict, const phasePair & pair) static
Fi() [2/2]
virtual tmp< volVectorField > Fi () const pure virtual
Implemented in Antal, Frank, noWallLubrication, TomiyamaWallLubrication, Antal, Frank, noWallLubrication, and TomiyamaWallLubrication.
F() [2/2]
virtual tmp< volVectorField > F () const virtual
Reimplemented in noWallLubrication, and noWallLubrication.
Ff() [2/2]
virtual tmp< surfaceScalarField > Ff () const virtual
Member Data Documentation
pair_
const phasePair & pair_ protected
Definition at line 61 of file wallLubricationModel.H.
dimF
static const dimensionSet dimF static
Definition at line 94 of file wallLubricationModel.H.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/interfacialModels/wallLubricationModels/wallLubricationModel/wallLubricationModel.H
src/phaseSystemModels/twoPhaseEuler/twoPhaseSystem/interfacialModels/wallLubricationModels/wallLubricationModel/wallLubricationModel.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/interfacialModels/wallLubricationModels/wallLubricationModel/wallLubricationModel.C
src/phaseSystemModels/twoPhaseEuler/twoPhaseSystem/interfacialModels/wallLubricationModels/wallLubricationModel/wallLubricationModel.C