OpenFOAM: motionSmootherAlgo Class Reference
motionSmootherAlgo Class Reference
Given a displacement moves the mesh by scaling the displacement back until there are no more mesh errors.
#include <motionSmootherAlgo.H>
Public Member Functions
ClassName ("motionSmootherAlgo")
motionSmootherAlgo (polyMesh &, pointMesh &, indirectPrimitivePatch &pp, pointVectorField &displacement, pointScalarField &scale, pointField &oldPoints, const labelList &adaptPatchIDs, const dictionary &paramDict, const bool dryRun=false)
~motionSmootherAlgo ()
const polyMesh & mesh () const
const pointMesh & pMesh () const
const indirectPrimitivePatch & patch () const
const labelList & adaptPatchIDs () const
const dictionary & paramDict () const
pointVectorField & pointDisplacement ()
const pointVectorField & pointDisplacement () const
void correct ()
void setDisplacementPatchFields ()
void setDisplacement (pointField &patchDisp)
void correctBoundaryConditions (pointVectorField &) const
void modifyMotionPoints (pointField &newPoints) const
tmp< pointField > curPoints () const
scalar setErrorReduction (const scalar)
bool scaleMesh (labelList &checkFaces, const bool smoothMesh=true, const label nAllow=0)
bool scaleMesh (labelList &checkFaces, const List< labelPair > &baffles, const bool smoothMesh=true, const label nAllow=0)
bool scaleMesh (labelList &checkFaces, const List< labelPair > &baffles, const dictionary &paramDict, const dictionary &meshQualityDict, const bool smoothMesh=true, const label nAllow=0)
void movePoints ()
void updateMesh ()
template<class Type >
void smooth (const GeometricField< Type, pointPatchField, pointMesh > &fld, const scalarField &edgeWeight, GeometricField< Type, pointPatchField, pointMesh > &newFld) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::pointPatchField, Foam::pointMesh > > avg (const GeometricField< Type, pointPatchField, pointMesh > &fld, const scalarField &edgeWeight) const
Static Public Member Functions
static void setDisplacementPatchFields (const labelList &patchIDs, pointVectorField &pointDisplacement)
static void setDisplacement (const labelList &patchIDs, const indirectPrimitivePatch &pp, pointField &patchDisp, pointVectorField &displacement)
static bool checkMesh (const bool report, const polyMesh &mesh, const dictionary &dict, labelHashSet &wrongFaces, const bool dryRun=false)
static bool checkMesh (const bool report, const polyMesh &mesh, const dictionary &dict, const labelList &checkFaces, labelHashSet &wrongFaces, const bool dryRun=false)
static bool checkMesh (const bool report, const polyMesh &mesh, const dictionary &dict, const labelList &checkFaces, const List< labelPair > &baffles, labelHashSet &wrongFaces, const bool dryRun=false)
static bool checkMesh (const bool report, const dictionary &dict, const polyMeshGeometry &, const pointField &, const labelList &checkFaces, labelHashSet &wrongFaces, const bool dryRun=false)
static bool checkMesh (const bool report, const dictionary &dict, const polyMeshGeometry &, const pointField &, const labelList &checkFaces, const List< labelPair > &baffles, labelHashSet &wrongFaces, const bool dryRun=false)
template<class Type >
static Type get (const dictionary &dict, const word &keyword, const bool noExit, enum keyType::option matchOpt, const Type &defaultValue=Zero)
Detailed Description
Given a displacement moves the mesh by scaling the displacement back until there are no more mesh errors.
Holds displacement field (read upon construction since need boundary conditions) and scaling factor and optional patch number on which to scale back displacement.
E.g.
    // Construct iterative mesh mover.
    motionSmoother meshMover(mesh, labelList(1, patchi));
    // Set desired displacement:
    meshMover.displacement() = ..
    for (label iter = 0; iter < maxIter; iter++)
    {
        if (meshMover.scaleMesh(true))
        {
            Info<< "Successfully moved mesh" << endl;
            return true;
        }
    }
Note
Shared points (parallel): a processor can have points which are part of pp on another processor but have no pp itself (i.e. it has points and/or edges but no faces of pp). Hence we have to be careful when e.g. synchronising displacements that the value from the processor which has faces of pp get priority. This is currently handled in setDisplacement by resetting the internal displacement to zero on coupled points that are coupled to patch points before doing anything else. The combine operator used will give preference to non-zero values.
Various routines take baffles. These are sets of boundary faces that are treated as a single internal face. This is a hack used to apply movement to internal faces.
Mesh constraints are looked up from the supplied dictionary. (uses recursive lookup)
Source files
motionSmootherAlgo.H
motionSmootherAlgo.C
motionSmootherAlgoTemplates.C
Definition at line 96 of file motionSmootherAlgo.H.
Constructor & Destructor Documentation
motionSmootherAlgo()
motionSmootherAlgo (polyMesh & mesh, pointMesh & pMesh, indirectPrimitivePatch & pp, pointVectorField & displacement, pointScalarField & scale, pointField & oldPoints, const labelList & adaptPatchIDs, const dictionary & paramDict, const bool dryRun = false)
Definition at line 318 of file motionSmootherAlgo.C.
References motionSmootherAlgo::updateMesh().
~motionSmootherAlgo()
~motionSmootherAlgo ()
Definition at line 348 of file motionSmootherAlgo.C.
Member Function Documentation
ClassName()
ClassName ("motionSmootherAlgo")
mesh()
const Foam::polyMesh & mesh () const
Definition at line 354 of file motionSmootherAlgo.C.
Referenced by motionSmootherAlgo::checkMesh().
pMesh()
const Foam::pointMesh & pMesh () const
Definition at line 360 of file motionSmootherAlgo.C.
Referenced by snappySnapDriver::smoothDisplacement().
patch()
const Foam::indirectPrimitivePatch & patch () const
Definition at line 366 of file motionSmootherAlgo.C.
Referenced by snappySnapDriver::smoothDisplacement().
adaptPatchIDs()
const Foam::labelList & adaptPatchIDs () const
Definition at line 372 of file motionSmootherAlgo.C.
paramDict()
const Foam::dictionary & paramDict () const
Definition at line 378 of file motionSmootherAlgo.C.
pointDisplacement() [1/2]
pointVectorField & pointDisplacement () inline
Definition at line 335 of file motionSmootherAlgo.H.
Referenced by snappySnapDriver::preSmoothPatch().
pointDisplacement() [2/2]
const pointVectorField & pointDisplacement () const inline
Definition at line 341 of file motionSmootherAlgo.H.
correct()
void correct ()
Definition at line 384 of file motionSmootherAlgo.C.
Referenced by snappySnapDriver::doSnap(), and snappySnapDriver::preSmoothPatch().
setDisplacementPatchFields() [1/2]
void setDisplacementPatchFields (const labelList & patchIDs, pointVectorField & pointDisplacement) static
Definition at line 396 of file motionSmootherAlgo.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), DimensionedField< Type, GeoMesh >::mesh(), MeshObject< pointMesh, UpdateableMeshObject, pointConstraints >::New(), patchIDs(), and UPstream::scheduled.
setDisplacementPatchFields() [2/2]
void setDisplacementPatchFields ()
Definition at line 454 of file motionSmootherAlgo.C.
setDisplacement() [1/2]
void setDisplacement (const labelList & patchIDs, const indirectPrimitivePatch & pp, pointField & patchDisp, pointVectorField & displacement) static
Definition at line 460 of file motionSmootherAlgo.C.
References IOobject::db(), Foam::endl(), forAll, polyMesh::globalData(), Foam::mag(), mesh, DimensionedField< Type, GeoMesh >::mesh(), PrimitivePatch< FaceList, PointField >::meshPoints(), OFstream::name(), primitiveMesh::nPoints(), patchIDs(), polyMesh::points(), Foam::Pout, pp(), syncTools::syncPointList(), UPtrList< T >::test(), Foam::meshTools::writeOBJ(), Foam::Zero, and VectorSpace< Form, Cmpt, Ncmpts >::zero.
Referenced by snappyLayerDriver::addLayers(), snappySnapDriver::doSnap(), and snappySnapDriver::preSmoothPatch().
setDisplacement() [2/2]
void setDisplacement (pointField & patchDisp)
Definition at line 555 of file motionSmootherAlgo.C.
correctBoundaryConditions()
void correctBoundaryConditions (pointVectorField & displacement) const
Definition at line 562 of file motionSmootherAlgo.C.
References UPstream::blocking, GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), DimensionedField< Type, GeoMesh >::mesh(), MeshObject< pointMesh, UpdateableMeshObject, pointConstraints >::New(), syncTools::syncPointList(), and VectorSpace< Form, Cmpt, Ncmpts >::zero.
modifyMotionPoints()
void modifyMotionPoints (pointField & newPoints) const
Definition at line 629 of file motionSmootherAlgo.C.
References e, UList< T >::end(), Foam::endl(), forAll, Foam::Info, MeshObject< polyMesh, UpdateableMeshObject, twoDPointCorrector >::New(), Foam::Pout, and WarningInFunction.
curPoints()
Foam::tmp< Foam::pointField > curPoints () const
Definition at line 741 of file motionSmootherAlgo.C.
References correctBoundaryConditions(), e, Foam::endl(), forAll, Foam::isA(), IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, pbm, Foam::Pout, PtrList< T >::setSize(), UPtrList< T >::size(), and VectorSpace< Form, Cmpt, Ncmpts >::zero.
setErrorReduction()
Foam::scalar setErrorReduction (const scalar errorReduction)
Definition at line 689 of file motionSmootherAlgo.C.
References UPtrList< T >::get().
Referenced by snappySnapDriver::preSmoothPatch(), and snappySnapDriver::scaleMesh().
scaleMesh() [1/3]
bool scaleMesh (labelList & checkFaces, const bool smoothMesh = true, const label nAllow = 0)
Definition at line 703 of file motionSmootherAlgo.C.
Referenced by snappySnapDriver::preSmoothPatch(), and snappySnapDriver::scaleMesh().
scaleMesh() [2/3]
bool scaleMesh (labelList & checkFaces, const List< labelPair > & baffles, const bool smoothMesh = true, const label nAllow = 0)
Definition at line 721 of file motionSmootherAlgo.C.
scaleMesh() [3/3]
bool scaleMesh (labelList & checkFaces, const List< labelPair > & baffles, const dictionary & paramDict, const dictionary & meshQualityDict, const bool smoothMesh = true, const label nAllow = 0)
Definition at line 814 of file motionSmootherAlgo.C.
References coupled(), UPtrList< T >::empty(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::gMax(), Foam::gMin(), Foam::Info, Foam::mag(), Foam::nl, patches, Foam::Pout, pp(), keyType::REGEX_RECURSIVE, Foam::returnReduce(), UPtrList< T >::size(), syncTools::syncPointList(), PtrList< T >::transfer(), and VectorSpace< Form, Cmpt, Ncmpts >::zero.
movePoints()
void movePoints ()
Definition at line 680 of file motionSmootherAlgo.C.
updateMesh()
void updateMesh ()
Definition at line 1025 of file motionSmootherAlgo.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, syncTools::getMasterEdges(), Foam::nl, and patches.
Referenced by motionSmootherAlgo::motionSmootherAlgo().
checkMesh() [1/5]
bool checkMesh (const bool report, const polyMesh & mesh, const dictionary & dict, labelHashSet & wrongFaces, const bool dryRun = false) static
Definition at line 496 of file motionSmootherAlgoCheck.C.
References dict, Foam::identity(), mesh, and primitiveMesh::nFaces().
Referenced by edgeCollapser::checkBadFaces(), motionSmootherAlgo::checkMesh(), snappyLayerDriver::doLayers(), snappySnapDriver::doSnap(), meshRefinement::mergeEdgesUndo(), meshRefinement::mergePatchFacesUndo(), and meshRefinement::splitFacesUndo().
checkMesh() [2/5]
bool checkMesh (const bool report, const polyMesh & mesh, const dictionary & dict, const labelList & checkFaces, labelHashSet & wrongFaces, const bool dryRun = false) static
Definition at line 29 of file motionSmootherAlgoCheck.C.
References motionSmootherAlgo::checkMesh(), dict, and motionSmootherAlgo::mesh().
checkMesh() [3/5]
bool checkMesh (const bool report, const polyMesh & mesh, const dictionary & dict, const labelList & checkFaces, const List< labelPair > & baffles, labelHashSet & wrongFaces, const bool dryRun = false) static
Definition at line 52 of file motionSmootherAlgoCheck.C.
References polyMeshGeometry::affectedCells(), primitiveMesh::cellCentres(), primitiveMesh::cellVolumes(), polyMeshGeometry::checkCellDeterminant(), polyMeshGeometry::checkEdgeLength(), polyMeshGeometry::checkFaceAngles(), polyMeshGeometry::checkFaceArea(), polyMeshGeometry::checkFaceDotProduct(), polyMeshGeometry::checkFaceFlatness(), polyMeshGeometry::checkFacePyramids(), polyMeshGeometry::checkFaceSkewness(), polyMeshGeometry::checkFaceTets(), polyMeshGeometry::checkFaceTwist(), polyMeshGeometry::checkFaceWeights(), polyMeshGeometry::checkTriangleTwist(), polyMeshGeometry::checkVolRatio(), error::clear(), dict, Foam::endl(), primitiveMesh::faceAreas(), primitiveMesh::faceCentres(), Foam::FatalError, Foam::FatalIOError, dictionary::getOrDefault(), Foam::Info, IOWarningInFunction, mesh, error::message(), Foam::nl, primitiveMesh::nPoints(), pFaces, primitiveMesh::pointFaces(), polyMesh::points(), keyType::REGEX_RECURSIVE, Foam::returnReduce(), Foam::setw(), and UPtrList< T >::size().
checkMesh() [4/5]
bool checkMesh (const bool report, const dictionary & dict, const polyMeshGeometry & meshGeom, const pointField & points, const labelList & checkFaces, labelHashSet & wrongFaces, const bool dryRun = false) static
Definition at line 516 of file motionSmootherAlgoCheck.C.
References dict, and points.
checkMesh() [5/5]
bool checkMesh (const bool report, const dictionary & dict, const polyMeshGeometry & meshGeom, const pointField & points, const labelList & checkFaces, const List< labelPair > & baffles, labelHashSet & wrongFaces, const bool dryRun = false) static
Definition at line 543 of file motionSmootherAlgoCheck.C.
References polyMeshGeometry::affectedCells(), polyMeshGeometry::checkFaceSkewness(), error::clear(), dict, Foam::endl(), Foam::FatalError, Foam::FatalIOError, dictionary::getOrDefault(), Foam::Info, error::message(), Foam::nl, Foam::Perr, pFaces, points, dictionary::readIfPresent(), keyType::REGEX_RECURSIVE, Foam::returnReduce(), Foam::setw(), and UPtrList< T >::size().
smooth()
template<class Type > void smooth (const GeometricField< Type, pointPatchField, pointMesh > & fld, const scalarField & edgeWeight, GeometricField< Type, pointPatchField, pointMesh > & newFld) const
Definition at line 225 of file motionSmootherAlgoTemplates.C.
References fld(), forAll, and MeshObject< pointMesh, UpdateableMeshObject, pointConstraints >::New().
Referenced by snappySnapDriver::smoothDisplacement().
get()
template<class Type > Type get (const dictionary & dict, const word & keyword, const bool noExit, enum keyType::option matchOpt, const Type & defaultValue = Zero) static
Definition at line 287 of file motionSmootherAlgoTemplates.C.
References dict, Foam::endl(), Foam::FatalIOError, IOobjectOption::MUST_READ, dictionary::name(), IOobjectOption::READ_IF_PRESENT, and dictionary::readEntry().
avg()
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::pointPatchField, Foam::pointMesh > > avg (const GeometricField< Type, pointPatchField, pointMesh > & fld, const scalarField & edgeWeight) const
Definition at line 134 of file motionSmootherAlgoTemplates.C.
References e, primitiveMesh::edges(), fld(), forAll, Foam::mag(), mesh, MeshObject< pointMesh, UpdateableMeshObject, pointConstraints >::New(), Foam::New(), IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, primitiveMesh::nPoints(), syncTools::syncPointList(), and Foam::Zero.
The documentation for this class was generated from the following files:
src/dynamicMesh/motionSmoother/motionSmootherAlgo.H
src/dynamicMesh/motionSmoother/motionSmootherAlgo.C
src/dynamicMesh/motionSmoother/motionSmootherAlgoCheck.C
src/dynamicMesh/motionSmoother/motionSmootherAlgoTemplates.C