OpenFOAM: powerLaw Class Reference
powerLaw Class Reference
Standard power-law non-Newtonian viscosity model.
#include <powerLaw.H>
Public Member Functions
TypeName ("powerLaw")
powerLaw (const word &name, const dictionary &viscosityProperties, const volVectorField &U, const surfaceScalarField &phi)
virtual ~powerLaw ()=default
virtual tmp< volScalarField > nu () const
virtual tmp< scalarField > nu (const label patchi) const
virtual void correct ()
virtual bool read (const dictionary &viscosityProperties)
Public Member Functions inherited from viscosityModel
TypeName ("viscosityModel")
declareRunTimeSelectionTable (autoPtr, viscosityModel, dictionary,(const word &name, const dictionary &viscosityProperties, const volVectorField &U, const surfaceScalarField &phi),(name, viscosityProperties, U, phi))
viscosityModel (const word &name, const dictionary &viscosityProperties, const volVectorField &U, const surfaceScalarField &phi)
virtual ~viscosityModel ()=default
const dictionary & viscosityProperties () const
tmp< volScalarField > strainRate () const
Protected Member Functions
tmp< volScalarField > calcNu () const
Protected Member Functions inherited from viscosityModel
viscosityModel (const viscosityModel &)=delete
void operator= (const viscosityModel &)=delete
Protected Attributes
volScalarField nu_
Protected Attributes inherited from viscosityModel
word name_
dictionary viscosityProperties_
const volVectorField & U_
const surfaceScalarField & phi_
Additional Inherited Members
Static Public Member Functions inherited from viscosityModel
static autoPtr< viscosityModel > New (const word &name, const dictionary &viscosityProperties, const volVectorField &U, const surfaceScalarField &phi)
Detailed Description
Standard power-law non-Newtonian viscosity model.
Source files
powerLaw.H
powerLaw.C
Definition at line 51 of file powerLaw.H.
Constructor & Destructor Documentation
powerLaw()
powerLaw (const word & name, const dictionary & viscosityProperties, const volVectorField & U, const surfaceScalarField & phi)
Definition at line 71 of file powerLaw.C.
~powerLaw()
virtual ~powerLaw () virtual default
Member Function Documentation
calcNu()
Foam::tmp< Foam::volScalarField > calcNu () const protected
Definition at line 47 of file powerLaw.C.
References Foam::dimless, Foam::dimTime, Foam::max(), Foam::min(), Foam::pow(), viscosityModel::strainRate(), and dimensioned< Type >::value().
Referenced by powerLaw::correct().
TypeName()
TypeName ("powerLaw")
nu() [1/2]
virtual tmp< volScalarField > nu () const inline virtual
Implements viscosityModel.
Definition at line 103 of file powerLaw.H.
References powerLaw::nu_.
nu() [2/2]
virtual tmp< scalarField > nu (const label patchi) const inline virtual
Implements viscosityModel.
Definition at line 109 of file powerLaw.H.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), and powerLaw::nu_.
correct()
virtual void correct () inline virtual
Implements viscosityModel.
Definition at line 115 of file powerLaw.H.
References powerLaw::calcNu(), and powerLaw::nu_.
read()
bool read (const dictionary & viscosityProperties) virtual
Implements viscosityModel.
Definition at line 102 of file powerLaw.C.
References dictionary::optionalSubDict(), and viscosityModel::read().
Member Data Documentation
nu_
volScalarField nu_ protected
Definition at line 69 of file powerLaw.H.
Referenced by powerLaw::correct(), powerLaw::nu(), and powerLaw::nu().
The documentation for this class was generated from the following files:
src/transportModels/incompressible/viscosityModels/powerLaw/powerLaw.H
src/transportModels/incompressible/viscosityModels/powerLaw/powerLaw.C