OpenFOAM: pointCells Class Reference
pointCells Class Reference
Smooth ATC in cells having a point to a set of patches supplied by type.
#include <pointCells.H>
Public Member Functions
TypeName ("pointCells")
pointCells (const fvMesh &mesh, const dictionary &dict)
virtual ~pointCells ()=default
Public Member Functions inherited from zeroATCcells
TypeName ("zeroATCcells")
declareRunTimeSelectionTable (autoPtr, zeroATCcells, dictionary,(const fvMesh &mesh, const dictionary &dict),(mesh, dict))
zeroATCcells (const fvMesh &mesh, const dictionary &dict)
virtual ~zeroATCcells ()=default
const labelList & getZeroATCcells ()
Additional Inherited Members
Static Public Member Functions inherited from zeroATCcells
static autoPtr< zeroATCcells > New (const fvMesh &mesh, const dictionary &dict)
Protected Attributes inherited from zeroATCcells
const fvMesh & mesh_
wordList zeroATCPatches_
labelList zeroATCZones_
labelList zeroATCcells_
Detailed Description
Smooth ATC in cells having a point to a set of patches supplied by type.
Source files
pointCells.H
pointCells.C
Definition at line 52 of file pointCells.H.
Constructor & Destructor Documentation
pointCells()
pointCells (const fvMesh & mesh, const dictionary & dict)
Definition at line 40 of file pointCells.C.
References Foam::endl(), forAll, Foam::Info, zeroATCcells::mesh_, Foam::nl, PtrList< T >::resize(), Foam::returnReduce(), UList< T >::size(), zeroATCcells::zeroATCcells_, zeroATCcells::zeroATCPatches_, and zeroATCcells::zeroATCZones_.
~pointCells()
virtual ~pointCells () virtual default
Member Function Documentation
TypeName()
TypeName ("pointCells")
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/ATCModel/zeroATCcells/pointCells/pointCells.H
src/optimisation/adjointOptimisation/adjoint/ATCModel/zeroATCcells/pointCells/pointCells.C