OpenFOAM: copiedFixedValueFvPatchScalarField Class Reference
copiedFixedValueFvPatchScalarField Class Reference
Copies the boundary values from a user specified field.
#include <copiedFixedValueFvPatchScalarField.H>
Public Member Functions
TypeName ("copiedFixedValue")
copiedFixedValueFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
copiedFixedValueFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
copiedFixedValueFvPatchScalarField (const copiedFixedValueFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
copiedFixedValueFvPatchScalarField (const copiedFixedValueFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
copiedFixedValueFvPatchScalarField (const copiedFixedValueFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Protected Attributes
word sourceFieldName_
Detailed Description
Copies the boundary values from a user specified field.
Usage
Example of the boundary condition specification:
<patchName>
{
    // Mandatory entries
    type                copiedFixedValue;
    sourceFieldName     <word>;
    // Inherited entries
    ...
}
where the entries mean:
Property Description Type Reqd Deflt
type Type name: copiedFixedValue word yes -
sourceFieldName Name of the source field word yes -
The inherited entries are elaborated in:
fixedValueFvPatchFields.H
See also
Foam::fixedValueFvPatchField
Source files
copiedFixedValueFvPatchScalarField.H
copiedFixedValueFvPatchScalarField.C
Definition at line 92 of file copiedFixedValueFvPatchScalarField.H.
Constructor & Destructor Documentation
copiedFixedValueFvPatchScalarField() [1/5]
copiedFixedValueFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 28 of file copiedFixedValueFvPatchScalarField.C.
copiedFixedValueFvPatchScalarField() [2/5]
copiedFixedValueFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 39 of file copiedFixedValueFvPatchScalarField.C.
copiedFixedValueFvPatchScalarField() [3/5]
copiedFixedValueFvPatchScalarField (const copiedFixedValueFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 51 of file copiedFixedValueFvPatchScalarField.C.
copiedFixedValueFvPatchScalarField() [4/5]
copiedFixedValueFvPatchScalarField (const copiedFixedValueFvPatchScalarField & awfpsf)
Definition at line 64 of file copiedFixedValueFvPatchScalarField.C.
copiedFixedValueFvPatchScalarField() [5/5]
copiedFixedValueFvPatchScalarField (const copiedFixedValueFvPatchScalarField & awfpsf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 74 of file copiedFixedValueFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("copiedFixedValue")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 144 of file copiedFixedValueFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 160 of file copiedFixedValueFvPatchScalarField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 88 of file copiedFixedValueFvPatchScalarField.C.
write()
void write (Ostream & os) const virtual
Definition at line 104 of file copiedFixedValueFvPatchScalarField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntry(), and fvPatchField< Type >::writeValueEntry().
Member Data Documentation
sourceFieldName_
word sourceFieldName_ protected
Definition at line 101 of file copiedFixedValueFvPatchScalarField.H.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/copiedFixedValue/copiedFixedValueFvPatchScalarField.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/copiedFixedValue/copiedFixedValueFvPatchScalarField.C