OpenFOAM: GAMGPreconditioner Class Reference
GAMGPreconditioner Class Reference
Numerics » Matrix manipulation and solvers » Preconditioners
Geometric agglomerated algebraic multigrid preconditioner.
#include <GAMGPreconditioner.H>
Public Member Functions
TypeName ("GAMG")
GAMGPreconditioner (const lduMatrix::solver &, const dictionary &solverControls)
virtual ~GAMGPreconditioner ()=default
virtual void precondition (solveScalarField &wA, const solveScalarField &rA, const direction cmpt=0) const
Public Member Functions inherited from GAMGSolver
TypeName ("GAMG")
GAMGSolver (const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces, const dictionary &solverControls)
virtual ~GAMGSolver ()
virtual solverPerformance solve (scalarField &psi, const scalarField &source, const direction cmpt=0) const
Public Member Functions inherited from lduMatrix::solver
virtual const word & type () const =0
declareRunTimeSelectionTable (autoPtr, solver, symMatrix,(const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces, const dictionary &solverControls),(fieldName, matrix, interfaceBouCoeffs, interfaceIntCoeffs, interfaces, solverControls))
declareRunTimeSelectionTable (autoPtr, solver, asymMatrix,(const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces, const dictionary &solverControls),(fieldName, matrix, interfaceBouCoeffs, interfaceIntCoeffs, interfaces, solverControls))
solver (const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces, const dictionary &solverControls)
virtual ~solver ()=default
const word & fieldName () const noexcept
const lduMatrix & matrix () const noexcept
const FieldField< Field, scalar > & interfaceBouCoeffs () const noexcept
const FieldField< Field, scalar > & interfaceIntCoeffs () const noexcept
const lduInterfaceFieldPtrsList & interfaces () const noexcept
virtual void read (const dictionary &)
virtual solverPerformance scalarSolve (solveScalarField &psi, const solveScalarField &source, const direction cmpt=0) const
solveScalarField::cmptType normFactor (const solveScalarField &psi, const solveScalarField &source, const solveScalarField &Apsi, solveScalarField &tmpField, const lduMatrix::normTypes normType) const
solveScalarField::cmptType normFactor (const solveScalarField &psi, const solveScalarField &source, const solveScalarField &Apsi, solveScalarField &tmpField) const
Public Member Functions inherited from lduMatrix::preconditioner
virtual const word & type () const =0
declareRunTimeSelectionTable (autoPtr, preconditioner, symMatrix,(const solver &sol, const dictionary &solverControls),(sol, solverControls))
declareRunTimeSelectionTable (autoPtr, preconditioner, asymMatrix,(const solver &sol, const dictionary &solverControls),(sol, solverControls))
preconditioner (const solver &sol)
virtual ~preconditioner ()=default
virtual void read (const dictionary &)
virtual void preconditionT (solveScalarField &wT, const solveScalarField &rT, const direction cmpt=0) const
virtual void setFinished (const solverPerformance &perf) const
Protected Member Functions
virtual void readControls ()
Protected Attributes
label nVcycles_
Protected Attributes inherited from lduMatrix::solver
word fieldName_
const lduMatrix & matrix_
const FieldField< Field, scalar > & interfaceBouCoeffs_
const FieldField< Field, scalar > & interfaceIntCoeffs_
lduInterfaceFieldPtrsList interfaces_
dictionary controlDict_
int log_
label minIter_
label maxIter_
lduMatrix::normTypes normType_
scalar tolerance_
scalar relTol_
profilingTrigger profiling_
Protected Attributes inherited from lduMatrix::preconditioner
const solver & solver_
Additional Inherited Members
Static Public Member Functions inherited from lduMatrix::solver
static autoPtr< solver > New (const word &solverName, const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces, const dictionary &solverControls)
static autoPtr< solver > New (const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces, const dictionary &solverControls)
Static Public Member Functions inherited from lduMatrix::preconditioner
static word getName (const dictionary &)
static autoPtr< preconditioner > New (const solver &sol, const dictionary &solverControls)
Detailed Description
Geometric agglomerated algebraic multigrid preconditioner.
See also
GAMGSolver for more details.
Source files
GAMGPreconditioner.H
GAMGPreconditioner.C
Definition at line 53 of file GAMGPreconditioner.H.
Constructor & Destructor Documentation
GAMGPreconditioner()
GAMGPreconditioner (const lduMatrix::solver & sol, const dictionary & solverControls)
Definition at line 41 of file GAMGPreconditioner.C.
References GAMGPreconditioner::readControls().
~GAMGPreconditioner()
virtual ~GAMGPreconditioner () virtual default
Member Function Documentation
readControls()
void readControls () protected virtual
Reimplemented from GAMGSolver.
Definition at line 65 of file GAMGPreconditioner.C.
Referenced by GAMGPreconditioner::GAMGPreconditioner().
TypeName()
TypeName ("GAMG")
precondition()
void precondition (solveScalarField & wA, const solveScalarField & rA, const direction cmpt = 0) const virtual
Implements lduMatrix::preconditioner.
Definition at line 72 of file GAMGPreconditioner.C.
References UPtrList< T >::size(), and Foam::Zero.
Member Data Documentation
nVcycles_
label nVcycles_ protected
Definition at line 63 of file GAMGPreconditioner.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/lduMatrix/preconditioners/GAMGPreconditioner/GAMGPreconditioner.H
src/OpenFOAM/matrices/lduMatrix/preconditioners/GAMGPreconditioner/GAMGPreconditioner.C