OpenFOAM: cellSetOption Class Reference
cellSetOption Class Reference
Intermediate abstract class for handling cell-set options for the derived fvOptions.
#include <cellSetOption.H>
Public Types
enum selectionModeType {
smAll , smCellSet , smCellZone , smPoints ,
smGeometric , smCellType
}
Public Member Functions
TypeName ("cellSetOption")
cellSetOption (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
virtual ~cellSetOption ()=default
scalar timeStart () const noexcept
scalar duration () const noexcept
bool inTimeLimits (const scalar timeValue) const
bool useSubMesh () const noexcept
selectionModeType selectionMode () const noexcept
const wordRes & selectionNames () const noexcept
const wordRe & zoneName () const
scalar V () const noexcept
const labelList & cells () const noexcept
scalar timeStart (scalar val) noexcept
scalar duration (scalar val) noexcept
virtual bool isActive ()
virtual bool read (const dictionary &dict)
const word & cellSetName () const
Public Member Functions inherited from option
TypeName ("option")
declareRunTimeSelectionTable (autoPtr, option, dictionary,(const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh),(name, modelType, dict, mesh))
option (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
autoPtr< option > clone () const
virtual ~option ()=default
const word & name () const noexcept
const fvMesh & mesh () const noexcept
const dictionary & coeffs () const noexcept
bool active () const noexcept
void setApplied (const label fieldi)
bool active (const bool on) noexcept
virtual label applyToField (const word &fieldName) const
virtual void checkApplied () const
virtual void addSup (fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (fvMatrix< vector > &eqn, const label fieldi)
virtual void addSup (fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (fvMatrix< tensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< scalar > &eqn, const label fieldi)
virtual void constrain (fvMatrix< vector > &eqn, const label fieldi)
virtual void constrain (fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< tensor > &eqn, const label fieldi)
virtual void correct (volScalarField &field)
virtual void correct (volVectorField &field)
virtual void correct (volSphericalTensorField &field)
virtual void correct (volSymmTensorField &field)
virtual void correct (volTensorField &field)
virtual void postProcessSens (scalarField &sensField, const word &fieldName=word::null, const word &designVariablesName=word::null)
virtual void postProcessSens (vectorField &sensField, const word &fieldName=word::null, const word &designVariablesName=word::null)
virtual void postProcessSens (tensorField &sensField, const word &fieldName=word::null, const word &designVariablesName=word::null)
virtual void writeHeader (Ostream &) const
virtual void writeFooter (Ostream &) const
virtual void writeData (Ostream &) const
Static Public Attributes
static const Enum< selectionModeType > selectionModeTypeNames_
Protected Member Functions
void setSelection (const dictionary &dict)
void setCellSelection ()
void setVol ()
Protected Member Functions inherited from option
void resetApplied ()
Protected Attributes
scalar timeStart_
scalar duration_
selectionModeType selectionMode_
wordRes selectionNames_
List< point > points_
dictionary geometricSelection_
labelList cells_
scalar V_
Protected Attributes inherited from option
const word name_
const word modelType_
const fvMesh & mesh_
dictionary dict_
dictionary coeffs_
wordList fieldNames_
List< bool > applied_
bool active_
Additional Inherited Members
Static Public Member Functions inherited from option
static autoPtr< option > New (const word &name, const dictionary &dict, const fvMesh &mesh)
Public Attributes inherited from option
bool log
Detailed Description
Intermediate abstract class for handling cell-set options for the derived fvOptions.
Usage
Minimal example by using constant/fvOptions:
<userDefinedName1>
{
    // Mandatory/Optional (inherited) entries
    ...
    // Mandatory entries (unmodifiable)
    selectionMode     all;
    // Optional entries (runtime modifiable)
    timeStart         1.0;
    // Conditional mandatory entries (runtime modifiable)
        // when timeStart entry is present
        duration          1.4;
        // when selectionMode=cellSet
        cellSet           <name>;
        // when selectionMode=cellZone
        cellZone          <name>;
        //OR: cellZones   (<name> ...);
        // when selectionMode=points
        points            (<point1> <point2> ... <pointN>);
        // when selectionMode=geometric
        selection
        {
            box1
            {
                action  use;
                source  box;
                min     (-0.1 -0.01 -0.1);
                max     (0.1 0.30 0.1);
            }
            ball
            {
                action  add;
                source  sphere;
                origin  (-0.1 -0.01 -0.1);
                radius  0.25;
            }
            ...
        }
    // Mandatory/Optional (derived) entries
    ...
}
where the entries mean:
Property Description Type Reqd Dflt
selectionMode Mode of cell selection - see below word yes -
timeStart Start time of fvOption scalar no -1
duration
Duration of fvOption execution
starting from timeStart
scalar cndtnl 0
cellSet Name of operand cellSet word cndtnl -
cellZone Name of operand cellZone wordRe cndtnl -
cellZones Name of operand cellZones wordRes cndtnl -
points
Set of points in global coordinate
system
vectorList cndtnl -
selection Dictionary of geometric selections dict cndtnl -
Options for the selectionMode entry:
      all       | Use all cells in the computational domain
      cellZone  | Use specified cellZone
      cellSet   | Use specified cellSet
      points    | Use cells containing a given set of points
      geometric | Select cells based on topoSetCellSource actions
The inherited entries are elaborated in:
fvOption.H
The geometric selection uses topoSetCellSource to select cells. Any searchableSurface selections must describe a closed volume. Ie, its hasVolumeType() method must be true.
Note
Source/sink options are to be added to the right-hand side of equations.
See also
Foam::cellBitSet::select
Source files
cellSetOption.H
cellSetOption.C
Definition at line 203 of file cellSetOption.H.
Member Enumeration Documentation
selectionModeType
enum selectionModeType
Enumerator
smAll
"all" cells
smCellSet
"cellSet"
smCellZone
"cellZone"
smPoints
"points"
smGeometric
"geometric"
smCellType
"overset type cells"
Definition at line 212 of file cellSetOption.H.
Constructor & Destructor Documentation
cellSetOption()
cellSetOption (const word & name, const word & modelType, const dictionary & dict, const fvMesh & mesh)
Definition at line 272 of file cellSetOption.C.
References option::coeffs_, Foam::decrIndent(), dict, fv(), Foam::incrIndent(), Foam::Info, cellSetOption::read(), cellSetOption::setCellSelection(), cellSetOption::setSelection(), and cellSetOption::setVol().
~cellSetOption()
virtual ~cellSetOption () virtual default
Member Function Documentation
setSelection()
void setSelection (const dictionary & dict) protected
Definition at line 56 of file cellSetOption.C.
References List< T >::clear(), dict, UList< T >::empty(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, UList< T >::first(), cellSetOption::geometricSelection_, cellSetOption::points_, List< T >::resize(), cellSetOption::selectionMode_, cellSetOption::selectionModeTypeNames_, cellSetOption::selectionNames_, cellSetOption::smAll, cellSetOption::smCellSet, cellSetOption::smCellType, cellSetOption::smCellZone, cellSetOption::smGeometric, cellSetOption::smPoints, and dictionary::subDict().
Referenced by cellSetOption::cellSetOption().
setCellSelection()
void setCellSelection () protected
Definition at line 140 of file cellSetOption.C.
References cellTypes, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::flatOutput(), forAll, found, Foam::identity(), Foam::indent(), Foam::Info, HashSet< Key, Hash >::insert(), MeshObject< Mesh, MeshObjectType, Type >::New(), Foam::nl, overlap, p, cellCellStencil::POROUS, Foam::returnReduceAnd(), Foam::returnReduceOr(), cellBitSet::select(), bitSet::sortedToc(), HashTable< T, Key, Hash >::sortedToc(), WarningInFunction, and zoneIDs.
Referenced by cellSetOption::cellSetOption().
setVol()
void setVol () protected
Definition at line 112 of file cellSetOption.C.
References IOstream::defaultPrecision(), Foam::endl(), Foam::indent(), Foam::Info, Foam::reduce(), Foam::returnReduce(), and Time::timeName().
Referenced by cellSetOption::cellSetOption().
TypeName()
TypeName ("cellSetOption")
timeStart() [1/2]
Foam::scalar timeStart () const inline noexcept
Definition at line 24 of file cellSetOptionI.H.
References cellSetOption::timeStart_.
duration() [1/2]
Foam::scalar duration () const inline noexcept
Definition at line 30 of file cellSetOptionI.H.
inTimeLimits()
bool inTimeLimits (const scalar timeValue) const inline
Definition at line 36 of file cellSetOptionI.H.
useSubMesh()
bool useSubMesh () const inline noexcept
Definition at line 50 of file cellSetOptionI.H.
Referenced by limitTemperature::correct(), limitTurbulenceViscosity::correct(), and limitVelocity::correct().
selectionMode()
Foam::fv::cellSetOption::selectionModeType selectionMode () const inline noexcept
Definition at line 57 of file cellSetOptionI.H.
Referenced by rotorDiskSource::checkData().
selectionNames()
const Foam::wordRes & selectionNames () const inline noexcept
Definition at line 64 of file cellSetOptionI.H.
zoneName()
const Foam::wordRe & zoneName () const inline
Definition at line 70 of file cellSetOptionI.H.
References wordRe::null.
Referenced by cellSetOption::cellSetName(), and explicitPorositySource::explicitPorositySource().
V()
Foam::scalar V () const inline noexcept
Definition at line 76 of file cellSetOptionI.H.
Referenced by rotorDiskSource::calculate().
cells()
const Foam::labelList & cells () const inline noexcept
Definition at line 82 of file cellSetOptionI.H.
timeStart() [2/2]
Foam::scalar timeStart (scalar val) inline noexcept
Definition at line 88 of file cellSetOptionI.H.
duration() [2/2]
Foam::scalar duration (scalar val) inline noexcept
Definition at line 96 of file cellSetOptionI.H.
isActive()
bool isActive () virtual
Reimplemented from option.
Definition at line 300 of file cellSetOption.C.
References option::isActive().
Referenced by limitTemperature::limitTemperature(), and limitTurbulenceViscosity::limitTurbulenceViscosity().
read()
bool read (const dictionary & dict) virtual
Reimplemented from option.
Reimplemented in VoFSolidificationMeltingSource, atmAmbientTurbSource, atmBuoyancyTurbSource, atmCoriolisUSource, atmLengthScaleTurbSource, atmNutSource, atmPlantCanopyTSource, atmPlantCanopyTurbSource, atmPlantCanopyUSource, fixedTemperatureConstraint, velocityDampingConstraint, FixedValueConstraint< Type >, limitTemperature, limitTurbulenceViscosity, limitVelocity, acousticDampingSource, actuationDiskSource, buoyancyTurbSource, directionalPressureGradientExplicitSource, explicitPorositySource, fanMomentumSource, heatExchangerSource, meanVelocityForce, radialActuationDiskSource, rotorDiskSource, solidificationMeltingSource, CodedSource< Type >, and SemiImplicitSource< Type >.
Definition at line 335 of file cellSetOption.C.
References dict, and option::read().
Referenced by cellSetOption::cellSetOption(), atmPlantCanopyTurbSource::read(), atmPlantCanopyUSource::read(), fixedTemperatureConstraint::read(), velocityDampingConstraint::read(), FixedValueConstraint< Type >::read(), limitTemperature::read(), limitTurbulenceViscosity::read(), limitVelocity::read(), acousticDampingSource::read(), actuationDiskSource::read(), explicitPorositySource::read(), heatExchangerSource::read(), rotorDiskSource::read(), solidificationMeltingSource::read(), CodedSource< Type >::read(), and SemiImplicitSource< Type >::read().
cellSetName()
const word & cellSetName () const inline
Definition at line 347 of file cellSetOption.H.
References cellSetOption::zoneName().
Member Data Documentation
selectionModeTypeNames_
const Foam::Enum< Foam::fv::cellSetOption::selectionModeType > selectionModeTypeNames_ static
Definition at line 223 of file cellSetOption.H.
Referenced by rotorDiskSource::checkData(), and cellSetOption::setSelection().
timeStart_
scalar timeStart_ protected
Definition at line 231 of file cellSetOption.H.
Referenced by cellSetOption::timeStart().
duration_
scalar duration_ protected
Definition at line 234 of file cellSetOption.H.
selectionMode_
selectionModeType selectionMode_ protected
Definition at line 237 of file cellSetOption.H.
Referenced by cellSetOption::setSelection().
selectionNames_
wordRes selectionNames_ protected
Definition at line 240 of file cellSetOption.H.
Referenced by cellSetOption::setSelection().
points_
List<point> points_ protected
Definition at line 243 of file cellSetOption.H.
Referenced by cellSetOption::setSelection().
geometricSelection_
dictionary geometricSelection_ protected
Definition at line 246 of file cellSetOption.H.
Referenced by cellSetOption::setSelection().
cells_
labelList cells_ protected
Definition at line 249 of file cellSetOption.H.
Referenced by velocityDampingConstraint::addDamping(), rotorDiskSource::calculate(), and acousticDampingSource::setBlendingFactor().
V_
scalar V_ protected
Definition at line 252 of file cellSetOption.H.
The documentation for this class was generated from the following files:
src/fvOptions/cellSetOption/cellSetOption.H
src/fvOptions/cellSetOption/cellSetOption.C
src/fvOptions/cellSetOption/cellSetOptionI.H