OpenFOAM: cellCellStencil Class Reference
cellCellStencil Class Reference abstract
Calculation of interpolation stencils.
#include <cellCellStencil.H>
Public Types
enum patchCellType { OTHER = 0 , PATCH = 1 , OVERSET = 2 }
enum cellType {
CALCULATED = 0 , INTERPOLATED = 1 , HOLE = 2 , SPECIAL = 3 ,
POROUS = 4
}
Public Member Functions
TypeName ("cellCellStencil")
declareRunTimeSelectionTable (autoPtr, cellCellStencil, mesh,(const fvMesh &mesh, const dictionary &dict, const bool update),(mesh, dict, update))
cellCellStencil (const fvMesh &)
virtual ~cellCellStencil ()
virtual bool update ()=0
virtual const labelUList & cellTypes () const =0
virtual const labelUList & interpolationCells () const =0
virtual const mapDistribute & cellInterpolationMap () const =0
virtual const labelListList & cellStencil () const =0
virtual const List< scalarList > & cellInterpolationWeights () const =0
virtual const scalarList & cellInterpolationWeight () const =0
virtual void stencilWeights (const point &sample, const pointList &donorCcs, scalarList &weights) const =0
virtual const wordHashSet & nonInterpolatedFields () const
virtual wordHashSet & nonInterpolatedFields ()
bool localStencil (const labelUList &) const
const labelIOList & zoneID () const
template<class T >
void interpolate (const fvMesh &mesh, Field< T > &psi) const
template<class GeoField >
void interpolate (GeoField &psi) const
template<class GeoField >
void interpolate (const fvMesh &mesh, const wordHashSet &suppressed) const
void walkFront (const globalIndex &globalCells, const scalar layerRelax, const labelListList &allStencil, labelList &allCellTypes, scalarField &allWeight, const scalarList &compactCellVol, const labelListList &compactStencil, const labelList &zoneID, const label holeLayers, const label useLayer) const
void setUpFront (const labelList &allCellTypes, bitSet &isFront) const
void setUpFrontOnOversetPatch (const labelList &allCellTypes, bitSet &isFront) const
void seedCell (const label cellI, const scalar wantedFraction, bitSet &isFront, scalarField &fraction) const
InfoProxy< cellCellStencil > info () const noexcept
template<class Type >
Foam::tmp< Foam::volScalarField > createField (const fvMesh &mesh, const word &name, const UList< Type > &psi)
Static Public Member Functions
static autoPtr< cellCellStencil > New (const fvMesh &, const dictionary &dict, const bool update=true)
static const labelIOList & zoneID (const fvMesh &)
static labelList count (const label size, const labelUList &lst)
static void globalCellCells (const globalIndex &gi, const polyMesh &mesh, const boolList &isValidDonor, const labelList &selectedCells, labelListList &cellCells, pointListList &cellCellCentres)
template<class T >
static void interpolate (Field< T > &psi, const fvMesh &mesh, const cellCellStencil &overlap, const List< scalarList > &wghts)
template<class GeoField , class SuppressBC >
static void correctBoundaryConditions (GeoField &psi)
Static Protected Member Functions
template<class Type >
static tmp< volScalarField > createField (const fvMesh &mesh, const word &name, const UList< Type > &)
static word baseName (const word &name)
Protected Attributes
const fvMesh & mesh_
wordHashSet nonInterpolatedFields_
const dictionary dict_
Static Protected Attributes
static const Enum< cellType > cellTypeNames_
Detailed Description
Calculation of interpolation stencils.
Looks up zoneID labelIOList to give the zoning. Wrapped in MeshObject as cellCellStencilObject. Kept separate so meshes can implement more clever methods (e.g. solid body motion does not require full recalculation)
Source files
cellCellStencil.H
cellCellStencil.C
cellCellStencilObject.C
Definition at line 63 of file cellCellStencil.H.
Member Enumeration Documentation
patchCellType
enum patchCellType
Enumerator
OTHER
PATCH
OVERSET
Definition at line 67 of file cellCellStencil.H.
cellType
enum cellType
Enumerator
CALCULATED
INTERPOLATED
HOLE
SPECIAL
POROUS
Definition at line 74 of file cellCellStencil.H.
Constructor & Destructor Documentation
cellCellStencil()
cellCellStencil (const fvMesh & mesh)
Definition at line 52 of file cellCellStencil.C.
~cellCellStencil()
~cellCellStencil () virtual
Definition at line 89 of file cellCellStencil.C.
Member Function Documentation
createField() [1/2]
template<class Type > static tmp< volScalarField > createField (const fvMesh & mesh, const word & name, const UList< Type > &) static protected
baseName()
Foam::word baseName (const word & name) static protected
Definition at line 95 of file cellCellStencil.C.
References string::ends_with(), and Foam::name().
TypeName()
TypeName ("cellCellStencil")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , cellCellStencil , mesh , (const fvMesh &mesh, const dictionary &dict, const bool update) , (mesh, dict, update))
New()
Foam::autoPtr< Foam::cellCellStencil > New (const fvMesh & mesh, const dictionary & dict, const bool update = true) static
Definition at line 59 of file cellCellStencil.C.
References DebugInFunction, dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), mesh, and update().
update()
virtual bool update () pure virtual
Implemented in cellCellStencilObject, cellVolumeWeight, inverseDistance, and trackingInverseDistance.
cellTypes()
virtual const labelUList & cellTypes () const pure virtual
Implemented in cellCellStencilObject, cellVolumeWeight, and inverseDistance.
interpolationCells()
virtual const labelUList & interpolationCells () const pure virtual
Implemented in cellCellStencilObject, cellVolumeWeight, and inverseDistance.
cellInterpolationMap()
virtual const mapDistribute & cellInterpolationMap () const pure virtual
Implemented in cellCellStencilObject, cellVolumeWeight, and inverseDistance.
cellStencil()
virtual const labelListList & cellStencil () const pure virtual
Implemented in cellCellStencilObject, cellVolumeWeight, and inverseDistance.
cellInterpolationWeights()
virtual const List< scalarList > & cellInterpolationWeights () const pure virtual
Implemented in cellCellStencilObject, cellVolumeWeight, and inverseDistance.
cellInterpolationWeight()
virtual const scalarList & cellInterpolationWeight () const pure virtual
Implemented in cellCellStencilObject, cellVolumeWeight, and inverseDistance.
stencilWeights()
virtual void stencilWeights (const point & sample, const pointList & donorCcs, scalarList & weights) const pure virtual
Implemented in cellCellStencilObject, cellVolumeWeight, inverseDistance, and leastSquares.
nonInterpolatedFields() [1/2]
const Foam::wordHashSet & nonInterpolatedFields () const virtual
Reimplemented in cellCellStencilObject.
Definition at line 170 of file cellCellStencil.C.
nonInterpolatedFields() [2/2]
Foam::wordHashSet & nonInterpolatedFields () virtual
Definition at line 176 of file cellCellStencil.C.
localStencil()
bool localStencil (const labelUList & slots) const
Definition at line 182 of file cellCellStencil.C.
References forAll.
zoneID() [1/2]
const Foam::labelIOList & zoneID (const fvMesh & mesh) static
Definition at line 106 of file cellCellStencil.C.
References polyMesh::dbDir(), polyMesh::facesInstance(), forAll, objectRegistry::getObjectPtr(), mesh, polyMesh::meshSubDir, IOobjectOption::MUST_READ, primitiveMesh::nCells(), IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, IOobjectOption::REGISTER, and fvMesh::time().
zoneID() [2/2]
const labelIOList & zoneID () const inline
Definition at line 217 of file cellCellStencil.H.
References cellCellStencil::mesh_, and cellCellStencil::zoneID().
Referenced by cellVolumeWeight::cellVolumeWeight(), inverseDistance::inverseDistance(), trackingInverseDistance::trackingInverseDistance(), and cellCellStencil::zoneID().
count()
Foam::labelList count (const label size, const labelUList & lst) static
Definition at line 154 of file cellCellStencil.C.
References forAll, Pstream::listCombineGather(), and Foam::Zero.
Referenced by Foam::operator<<().
globalCellCells()
void globalCellCells (const globalIndex & gi, const polyMesh & mesh, const boolList & isValidDonor, const labelList & selectedCells, labelListList & cellCells, pointListList & cellCellCentres) static
Definition at line 195 of file cellCellStencil.C.
References primitiveMesh::cellCentres(), cells, primitiveMesh::cells(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), forAll, Foam::identity(), mesh, primitiveMesh::nCells(), primitiveMesh::nInternalFaces(), List< T >::setSize(), PtrList< T >::setSize(), UPtrList< T >::size(), UList< T >::size(), and syncTools::swapBoundaryCellList().
interpolate() [1/4]
template<class T > void interpolate (Field< T > & psi, const fvMesh & mesh, const cellCellStencil & overlap, const List< scalarList > & wghts) static
Definition at line 26 of file cellCellStencilTemplates.C.
References cellIDs, Foam::exit(), f(), Foam::FatalError, FatalErrorInFunction, forAll, mesh, UPstream::msgType(), overlap, psi, s(), UPtrList< T >::size(), UList< T >::size(), and T.
Referenced by oversetFvPatchField< Type >::initEvaluate(), and oversetFvPatchField< Type >::manipulateMatrix().
interpolate() [2/4]
template<class T > void interpolate (const fvMesh & mesh, Field< T > & psi) const
Definition at line 77 of file cellCellStencilTemplates.C.
References Foam::interpolate(), mesh, overlap, and psi.
interpolate() [3/4]
template<class GeoField > void interpolate (GeoField & psi) const
Definition at line 92 of file cellCellStencilTemplates.C.
References Foam::interpolate(), and psi.
interpolate() [4/4]
template<class GeoField > void interpolate (const fvMesh & mesh, const wordHashSet & suppressed) const
Definition at line 104 of file cellCellStencilTemplates.C.
References Foam::endl(), fld(), Foam::interpolate(), objectRegistry::lookupClass(), mesh, Foam::name(), overlap, and Foam::Pout.
correctBoundaryConditions()
template<class GeoField , class SuppressBC > void correctBoundaryConditions (GeoField & psi) static
Definition at line 180 of file cellCellStencilTemplates.C.
References forAll, UPstream::nonBlocking, UPstream::nRequests(), UPstream::parRun(), psi, and UPstream::waitRequests().
Referenced by oversetFvMeshBase::writeObject().
walkFront()
void walkFront (const globalIndex & globalCells, const scalar layerRelax, const labelListList & allStencil, labelList & allCellTypes, scalarField & allWeight, const scalarList & compactCellVol, const labelListList & compactStencil, const labelList & zoneID, const label holeLayers, const label useLayer) const
Definition at line 409 of file cellCellStencil.C.
References Foam::abort(), PtrList< T >::append(), UPtrList< T >::count(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, Foam::findMin(), forAll, Foam::gSum(), Foam::Info, Foam::mag(), Foam::name(), Foam::nl, Foam::reduce(), Foam::returnReduce(), PtrList< T >::set(), UPtrList< T >::size(), syncTools::syncFaceList(), UPtrList< T >::test(), List< T >::transfer(), PtrList< T >::transfer(), and Foam::Zero.
setUpFront()
void setUpFront (const labelList & allCellTypes, bitSet & isFront) const
Definition at line 332 of file cellCellStencil.C.
References PtrList< T >::set(), and syncTools::swapBoundaryCellList().
setUpFrontOnOversetPatch()
void setUpFrontOnOversetPatch (const labelList & allCellTypes, bitSet & isFront) const
Definition at line 380 of file cellCellStencil.C.
References fvBoundaryMesh::faceCells(), forAll, and PtrList< T >::set().
seedCell()
void seedCell (const label cellI, const scalar wantedFraction, bitSet & isFront, scalarField & fraction) const
Definition at line 311 of file cellCellStencil.C.
References forAll, and PtrList< T >::set().
info()
InfoProxy< cellCellStencil > info () const inline noexcept
Definition at line 313 of file cellCellStencil.H.
createField() [2/2]
template<class Type > Foam::tmp< Foam::volScalarField > createField (const fvMesh & mesh, const word & name, const UList< Type > & psi)
Definition at line 147 of file cellCellStencilTemplates.C.
References Foam::dimless, fld(), forAll, mesh, Foam::name(), tmp< T >::New(), IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, psi, fvMesh::time(), Foam::Zero, and fvPatchFieldBase::zeroGradientType().
Member Data Documentation
cellTypeNames_
const Foam::Enum< Foam::cellCellStencil::cellType > cellTypeNames_ static protected
Definition at line 89 of file cellCellStencil.H.
mesh_
const fvMesh& mesh_ protected
Definition at line 92 of file cellCellStencil.H.
Referenced by cellVolumeWeight::cellVolumeWeight(), inverseDistance::inverseDistance(), trackingInverseDistance::trackingInverseDistance(), and cellCellStencil::zoneID().
nonInterpolatedFields_
wordHashSet nonInterpolatedFields_ protected
Definition at line 95 of file cellCellStencil.H.
Referenced by cellVolumeWeight::cellVolumeWeight(), and inverseDistance::inverseDistance().
dict_
const dictionary dict_ protected
Definition at line 98 of file cellCellStencil.H.
The documentation for this class was generated from the following files:
src/overset/cellCellStencil/cellCellStencil/cellCellStencil.H
src/overset/cellCellStencil/cellCellStencil/cellCellStencil.C
src/overset/cellCellStencil/cellCellStencil/cellCellStencilTemplates.C