OpenFOAM: liftModel Class Reference
liftModel Class Reference abstract
#include <liftModel.H>
Public Member Functions
TypeName ("liftModel")
declareRunTimeSelectionTable (autoPtr, liftModel, dictionary,(const dictionary &dict, const phasePair &pair),(dict, pair))
liftModel (const dictionary &dict, const phasePair &pair)
virtual ~liftModel ()=default
virtual tmp< volScalarField > Cl () const =0
virtual tmp< volVectorField > Fi () const
virtual tmp< volVectorField > F () const
virtual tmp< surfaceScalarField > Ff () const
TypeName ("liftModel")
declareRunTimeSelectionTable (autoPtr, liftModel, dictionary,(const dictionary &dict, const phasePair &pair),(dict, pair))
liftModel (const dictionary &dict, const phasePair &pair)
virtual ~liftModel ()=default
virtual tmp< volScalarField > Cl () const =0
virtual tmp< volVectorField > Fi () const
virtual tmp< volVectorField > F () const
virtual tmp< surfaceScalarField > Ff () const
Static Public Member Functions
static autoPtr< liftModel > New (const dictionary &dict, const phasePair &pair)
static autoPtr< liftModel > New (const dictionary &dict, const phasePair &pair)
Static Public Attributes
static const dimensionSet dimF
Protected Attributes
const phasePair & pair_
Detailed Description
Source files
liftModel.H
liftModel.C
Source files
liftModel.H
liftModel.C
Definition at line 51 of file liftModel.H.
Constructor & Destructor Documentation
liftModel() [1/2]
liftModel (const dictionary & dict, const phasePair & pair)
Definition at line 43 of file liftModel.C.
~liftModel() [1/2]
virtual ~liftModel () virtual default
liftModel() [2/2]
liftModel (const dictionary & dict, const phasePair & pair)
~liftModel() [2/2]
virtual ~liftModel () virtual default
Member Function Documentation
TypeName() [1/2]
TypeName ("liftModel")
declareRunTimeSelectionTable() [1/2]
declareRunTimeSelectionTable (autoPtr , liftModel , dictionary , (const dictionary &dict, const phasePair &pair) , (dict, pair))
New() [1/2]
Foam::autoPtr< Foam::liftModel > New (const dictionary & dict, const phasePair & pair) static
Definition at line 56 of file liftModel.C.
References Foam::abort(), dict, Foam::endl(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), and Foam::Info.
Cl() [1/2]
virtual tmp< volScalarField > Cl () const pure virtual
Implemented in constantLiftCoefficient, LegendreMagnaudet, Moraga, noLift, TomiyamaLift, wallDamped, constantLiftCoefficient, LegendreMagnaudet, Moraga, noLift, and TomiyamaLift.
Fi() [1/2]
Foam::tmp< Foam::volVectorField > Fi () const virtual
Reimplemented in wallDamped.
Definition at line 86 of file liftModel.C.
References Foam::fvc::curl().
F() [1/2]
Foam::tmp< Foam::volVectorField > F () const virtual
Reimplemented in noLift, wallDamped, and noLift.
Definition at line 97 of file liftModel.C.
Ff() [1/2]
Foam::tmp< Foam::surfaceScalarField > Ff () const virtual
Reimplemented in noLift, wallDamped, and noLift.
Definition at line 103 of file liftModel.C.
References Foam::fvc::flux(), and Foam::fvc::interpolate().
TypeName() [2/2]
TypeName ("liftModel")
declareRunTimeSelectionTable() [2/2]
declareRunTimeSelectionTable (autoPtr , liftModel , dictionary , (const dictionary &dict, const phasePair &pair) , (dict, pair))
New() [2/2]
static autoPtr< liftModel > New (const dictionary & dict, const phasePair & pair) static
Cl() [2/2]
virtual tmp< volScalarField > Cl () const pure virtual
Implemented in constantLiftCoefficient, LegendreMagnaudet, Moraga, noLift, TomiyamaLift, wallDamped, constantLiftCoefficient, LegendreMagnaudet, Moraga, noLift, and TomiyamaLift.
Fi() [2/2]
virtual tmp< volVectorField > Fi () const virtual
Reimplemented in wallDamped.
F() [2/2]
virtual tmp< volVectorField > F () const virtual
Reimplemented in noLift, wallDamped, and noLift.
Ff() [2/2]
virtual tmp< surfaceScalarField > Ff () const virtual
Reimplemented in noLift, wallDamped, and noLift.
Member Data Documentation
pair_
const phasePair & pair_ protected
Definition at line 58 of file liftModel.H.
dimF
static const dimensionSet dimF static
Definition at line 85 of file liftModel.H.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/interfacialModels/liftModels/liftModel/liftModel.H
src/phaseSystemModels/twoPhaseEuler/twoPhaseSystem/interfacialModels/liftModels/liftModel/liftModel.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/interfacialModels/liftModels/liftModel/liftModel.C
src/phaseSystemModels/twoPhaseEuler/twoPhaseSystem/interfacialModels/liftModels/liftModel/liftModel.C