OpenFOAM: InterfaceCompositionModel< Thermo, OtherThermo > Class Template Reference
InterfaceCompositionModel< Thermo, OtherThermo > Class Template Reference
Base class for interface composition models, templated on the two thermodynamic models either side of the interface.
#include <InterfaceCompositionModel.H>
Public Member Functions
InterfaceCompositionModel (const dictionary &dict, const phasePair &pair)
virtual ~InterfaceCompositionModel ()=default
virtual tmp< volScalarField > dY (const word &speciesName, const volScalarField &Tf) const
virtual tmp< volScalarField > Yf (const word &speciesName, const volScalarField &Tf) const
virtual tmp< volScalarField > Dfrom (const word &speciesName) const
virtual tmp< volScalarField > Dto (const word &speciesName) const
virtual tmp< volScalarField > L (const word &speciesName, const volScalarField &Tf) const
InterfaceCompositionModel (const dictionary &dict, const phasePair &pair)
~InterfaceCompositionModel ()=default
virtual tmp< volScalarField > dY (const word &speciesName, const volScalarField &Tf) const
virtual tmp< volScalarField > D (const word &speciesName) const
virtual tmp< volScalarField > L (const word &speciesName, const volScalarField &Tf) const
virtual void addMDotL (const volScalarField &K, const volScalarField &Tf, volScalarField &mDotL, volScalarField &mDotLPrime) const
template<class ThermoType >
const Foam::multiComponentMixture< ThermoType >::thermoType & getLocalThermo (const word &speciesName, const multiComponentMixture< ThermoType > &globalThermo) const
template<class ThermoType >
const Foam::pureMixture< ThermoType >::thermoType & getLocalThermo (const word &speciesName, const pureMixture< ThermoType > &globalThermo) const
template<class ThermoType >
Foam::tmp< Foam::volScalarField > getSpecieMassFraction (const word &speciesName, const multiComponentMixture< ThermoType > &mixture) const
template<class ThermoType >
Foam::tmp< Foam::volScalarField > getSpecieMassFraction (const word &speciesName, const pureMixture< ThermoType > &mixture) const
template<class ThermoType >
Foam::tmp< Foam::volScalarField > MwMixture (const pureMixture< ThermoType > &mixture) const
template<class ThermoType >
Foam::tmp< Foam::volScalarField > MwMixture (const multiComponentMixture< ThermoType > &mixture) const
Public Member Functions inherited from interfaceCompositionModel
TypeName ("interfaceCompositionModel")
declareRunTimeSelectionTable (autoPtr, interfaceCompositionModel, dictionary,(const dictionary &dict, const phasePair &pair),(dict, pair))
interfaceCompositionModel (const dictionary &dict, const phasePair &pair)
virtual ~interfaceCompositionModel ()=default
const word transferSpecie () const
const phasePair & pair () const
const multiphaseInterSystem & fluid () const
virtual tmp< volScalarField > Kexp (const volScalarField &field)=0
virtual tmp< volScalarField > KSp (label modelVariable, const volScalarField &field)=0
virtual tmp< volScalarField > KSu (label modelVariable, const volScalarField &field)=0
virtual const dimensionedScalar & Tactivate () const noexcept=0
virtual bool includeDivU () const noexcept
bool includeVolChange ()
const word & variable () const
Protected Member Functions
template<class ThermoType >
const pureMixture< ThermoType >::thermoType & getLocalThermo (const word &speciesName, const pureMixture< ThermoType > &globalThermo) const
template<class ThermoType >
const multiComponentMixture< ThermoType >::thermoType & getLocalThermo (const word &speciesName, const multiComponentMixture< ThermoType > &globalThermo) const
template<class ThermoType >
tmp< volScalarField > getSpecieMassFraction (const word &speciesName, const pureMixture< ThermoType > &thermo) const
template<class ThermoType >
tmp< volScalarField > getSpecieMassFraction (const word &speciesName, const multiComponentMixture< ThermoType > &thermo) const
template<class ThermoType >
tmp< volScalarField > MwMixture (const pureMixture< ThermoType > &thermo) const
template<class ThermoType >
tmp< volScalarField > MwMixture (const multiComponentMixture< ThermoType > &) const
template<class ThermoType >
const pureMixture< ThermoType >::thermoType & getLocalThermo (const word &speciesName, const pureMixture< ThermoType > &globalThermo) const
template<class ThermoType >
const multiComponentMixture< ThermoType >::thermoType & getLocalThermo (const word &speciesName, const multiComponentMixture< ThermoType > &globalThermo) const
Protected Attributes
const Thermo & fromThermo_
const OtherThermo & toThermo_
const dimensionedScalar Le_
const Thermo & thermo_
const OtherThermo & otherThermo_
Protected Attributes inherited from interfaceCompositionModel
modelVariable modelVariable_
bool includeVolChange_
const phasePair & pair_
word speciesName_
const fvMesh & mesh_
Additional Inherited Members
Public Types inherited from interfaceCompositionModel
enum modelVariable { T , P , Y , alpha }
Static Public Member Functions inherited from interfaceCompositionModel
static autoPtr< interfaceCompositionModel > New (const dictionary &dict, const phasePair &pair)
Static Protected Attributes inherited from interfaceCompositionModel
static const Enum< modelVariable > modelVariableNames_
Detailed Description
template<class Thermo, class OtherThermo>
class Foam::InterfaceCompositionModel< Thermo, OtherThermo >
Base class for interface composition models, templated on the two thermodynamic models either side of the interface.
Source files
InterfaceCompositionModel.H
InterfaceCompositionModel.C
Source files
InterfaceCompositionModel.H
InterfaceCompositionModel.C
Definition at line 56 of file InterfaceCompositionModel.H.
Constructor & Destructor Documentation
InterfaceCompositionModel() [1/2]
template<class Thermo , class OtherThermo > InterfaceCompositionModel (const dictionary & dict, const phasePair & pair)
Definition at line 173 of file InterfaceCompositionModel.C.
~InterfaceCompositionModel() [1/2]
template<class Thermo , class OtherThermo > virtual ~InterfaceCompositionModel () virtual default
InterfaceCompositionModel() [2/2]
template<class Thermo , class OtherThermo > InterfaceCompositionModel (const dictionary & dict, const phasePair & pair)
~InterfaceCompositionModel() [2/2]
template<class Thermo , class OtherThermo > ~InterfaceCompositionModel () default
Member Function Documentation
getLocalThermo() [1/6]
template<class Thermo , class OtherThermo > template<class ThermoType > const pureMixture< ThermoType >::thermoType & getLocalThermo (const word & speciesName, const pureMixture< ThermoType > & globalThermo) const protected
Referenced by kineticGasEvaporation< Thermo, OtherThermo >::kineticGasEvaporation().
getLocalThermo() [2/6]
template<class Thermo , class OtherThermo > template<class ThermoType > const multiComponentMixture< ThermoType >::thermoType & getLocalThermo (const word & speciesName, const multiComponentMixture< ThermoType > & globalThermo) const protected
getSpecieMassFraction() [1/4]
template<class Thermo , class OtherThermo > template<class ThermoType > tmp< volScalarField > getSpecieMassFraction (const word & speciesName, const pureMixture< ThermoType > & thermo) const protected
getSpecieMassFraction() [2/4]
template<class Thermo , class OtherThermo > template<class ThermoType > tmp< volScalarField > getSpecieMassFraction (const word & speciesName, const multiComponentMixture< ThermoType > & thermo) const protected
MwMixture() [1/4]
template<class Thermo , class OtherThermo > template<class ThermoType > tmp< volScalarField > MwMixture (const pureMixture< ThermoType > & thermo) const protected
MwMixture() [2/4]
template<class Thermo , class OtherThermo > template<class ThermoType > tmp< volScalarField > MwMixture (const multiComponentMixture< ThermoType > &) const protected
dY() [1/2]
template<class Thermo , class OtherThermo > Foam::tmp< Foam::volScalarField > dY (const word & speciesName, const volScalarField & Tf) const virtual
Implements interfaceCompositionModel.
Definition at line 344 of file InterfaceCompositionModel.C.
References NotImplemented.
Yf()
template<class Thermo , class OtherThermo > Foam::tmp< Foam::volScalarField > Yf (const word & speciesName, const volScalarField & Tf) const virtual
Implements interfaceCompositionModel.
Reimplemented in Henry< Thermo, OtherThermo >, NonRandomTwoLiquid< Thermo, OtherThermo >, Raoult< Thermo, OtherThermo >, and Saturated< Thermo, OtherThermo >.
Definition at line 357 of file InterfaceCompositionModel.C.
References NotImplemented.
Dfrom()
template<class Thermo , class OtherThermo > Foam::tmp< Foam::volScalarField > Dfrom (const word & speciesName) const virtual
Implements interfaceCompositionModel.
Definition at line 256 of file InterfaceCompositionModel.C.
References D, Foam::dimArea, Foam::dimTime, forAll, IOobject::groupName(), DimensionedField< Type, GeoMesh >::mesh(), tmp< T >::New(), p, T, IOobject::time(), and Foam::Zero.
Dto()
template<class Thermo , class OtherThermo > Foam::tmp< Foam::volScalarField > Dto (const word & speciesName) const virtual
Implements interfaceCompositionModel.
Definition at line 210 of file InterfaceCompositionModel.C.
References D, Foam::dimArea, Foam::dimTime, forAll, IOobject::groupName(), DimensionedField< Type, GeoMesh >::mesh(), tmp< T >::New(), p, T, IOobject::time(), and Foam::Zero.
L() [1/2]
template<class Thermo , class OtherThermo > Foam::tmp< Foam::volScalarField > L (const word & speciesName, const volScalarField & Tf) const virtual
Implements interfaceCompositionModel.
Definition at line 302 of file InterfaceCompositionModel.C.
References Foam::dimEnergy, Foam::dimMass, forAll, IOobject::groupName(), L, DimensionedField< Type, GeoMesh >::mesh(), tmp< T >::New(), p, IOobject::time(), Foam::Zero, and fvPatchFieldBase::zeroGradientType().
getLocalThermo() [3/6]
template<class Thermo , class OtherThermo > template<class ThermoType > const pureMixture< ThermoType >::thermoType & getLocalThermo (const word & speciesName, const pureMixture< ThermoType > & globalThermo) const protected
getLocalThermo() [4/6]
template<class Thermo , class OtherThermo > template<class ThermoType > const multiComponentMixture< ThermoType >::thermoType & getLocalThermo (const word & speciesName, const multiComponentMixture< ThermoType > & globalThermo) const protected
dY() [2/2]
template<class Thermo , class OtherThermo > virtual tmp< volScalarField > dY (const word & speciesName, const volScalarField & Tf) const virtual
Implements interfaceCompositionModel.
D()
template<class Thermo , class OtherThermo > Foam::tmp< Foam::volScalarField > D (const word & speciesName) const virtual
Definition at line 109 of file InterfaceCompositionModel.C.
References D, Foam::dimArea, Foam::dimTime, forAll, IOobject::groupName(), DimensionedField< Type, GeoMesh >::mesh(), GeometricField< scalar, fvPatchField, volMesh >::New(), p, and T.
L() [2/2]
template<class Thermo , class OtherThermo > virtual tmp< volScalarField > L (const word & speciesName, const volScalarField & Tf) const virtual
Implements interfaceCompositionModel.
addMDotL()
template<class Thermo , class OtherThermo > void addMDotL (const volScalarField & K, const volScalarField & Tf, volScalarField & mDotL, volScalarField & mDotLPrime) const virtual
Definition at line 198 of file InterfaceCompositionModel.C.
References D, and L.
getLocalThermo() [5/6]
template<class Thermo , class OtherThermo > template<class ThermoType > const Foam::multiComponentMixture< ThermoType >::thermoType & getLocalThermo (const word & speciesName, const multiComponentMixture< ThermoType > & globalThermo) const
Definition at line 36 of file InterfaceCompositionModel.C.
getLocalThermo() [6/6]
template<class Thermo , class OtherThermo > template<class ThermoType > const Foam::pureMixture< ThermoType >::thermoType & getLocalThermo (const word & speciesName, const pureMixture< ThermoType > & globalThermo) const
Definition at line 53 of file InterfaceCompositionModel.C.
getSpecieMassFraction() [3/4]
template<class Thermo , class OtherThermo > template<class ThermoType > Foam::tmp< Foam::volScalarField > getSpecieMassFraction (const word & speciesName, const multiComponentMixture< ThermoType > & mixture) const
Definition at line 66 of file InterfaceCompositionModel.C.
References Foam::dimless, mesh, tmp< T >::New(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, fvMesh::time(), Foam::Zero, and fvPatchFieldBase::zeroGradientType().
getSpecieMassFraction() [4/4]
template<class Thermo , class OtherThermo > template<class ThermoType > Foam::tmp< Foam::volScalarField > getSpecieMassFraction (const word & speciesName, const pureMixture< ThermoType > & mixture) const
Definition at line 100 of file InterfaceCompositionModel.C.
References Foam::dimless, mesh, tmp< T >::New(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, fvMesh::time(), and fvPatchFieldBase::zeroGradientType().
MwMixture() [3/4]
template<class Thermo , class OtherThermo > template<class ThermoType > Foam::tmp< Foam::volScalarField > MwMixture (const pureMixture< ThermoType > & mixture) const
Definition at line 129 of file InterfaceCompositionModel.C.
References Foam::dimMass, Foam::dimMoles, e, mesh, tmp< T >::New(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, fvMesh::time(), and fvPatchFieldBase::zeroGradientType().
MwMixture() [4/4]
template<class Thermo , class OtherThermo > template<class ThermoType > Foam::tmp< Foam::volScalarField > MwMixture (const multiComponentMixture< ThermoType > & mixture) const
Definition at line 161 of file InterfaceCompositionModel.C.
Member Data Documentation
fromThermo_
template<class Thermo , class OtherThermo > const Thermo& fromThermo_ protected
Definition at line 65 of file InterfaceCompositionModel.H.
toThermo_
template<class Thermo , class OtherThermo > const OtherThermo& toThermo_ protected
Definition at line 68 of file InterfaceCompositionModel.H.
Referenced by kineticGasEvaporation< Thermo, OtherThermo >::kineticGasEvaporation().
Le_
template<class Thermo , class OtherThermo > const dimensionedScalar Le_ protected
Definition at line 71 of file InterfaceCompositionModel.H.
thermo_
template<class Thermo , class OtherThermo > const Thermo& thermo_ protected
Definition at line 63 of file InterfaceCompositionModel.H.
Referenced by NonRandomTwoLiquid< Thermo, OtherThermo >::NonRandomTwoLiquid().
otherThermo_
template<class Thermo , class OtherThermo > const OtherThermo& otherThermo_ protected
Definition at line 66 of file InterfaceCompositionModel.H.
The documentation for this class was generated from the following files:
src/phaseSystemModels/multiphaseInter/phasesSystem/InterfaceCompositionModel/InterfaceCompositionModel.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/interfacialCompositionModels/interfaceCompositionModels/InterfaceCompositionModel/InterfaceCompositionModel.H
src/phaseSystemModels/multiphaseInter/phasesSystem/InterfaceCompositionModel/InterfaceCompositionModel.C
src/phaseSystemModels/reactingEuler/multiphaseSystem/interfacialCompositionModels/interfaceCompositionModels/InterfaceCompositionModel/InterfaceCompositionModel.C