OpenFOAM: breakupModel Class Reference
breakupModel Class Reference abstract
Base class for breakup models which give a total breakup rate and a separate daughter size distribution function.
#include <breakupModel.H>
Classes
class iNew
Public Member Functions
TypeName ("breakupModel")
declareRunTimeSelectionTable (autoPtr, breakupModel, dictionary,(const populationBalanceModel &popBal, const dictionary &dict),(popBal, dict))
breakupModel (const populationBalanceModel &popBal, const dictionary &dict)
autoPtr< breakupModel > clone () const
virtual ~breakupModel ()=default
const populationBalanceModel & popBal () const
const autoPtr< daughterSizeDistributionModel > & dsdPtr () const
autoPtr< daughterSizeDistributionModel > & dsdPtr ()
virtual void correct ()
virtual void setBreakupRate (volScalarField &breakupRate, const label i)=0
Static Public Member Functions
static autoPtr< breakupModel > New (const word &modelType, const populationBalanceModel &popBal, const dictionary &dict)
Protected Attributes
const populationBalanceModel & popBal_
dictionary dict_
autoPtr< daughterSizeDistributionModel > dsd_
Detailed Description
Base class for breakup models which give a total breakup rate and a separate daughter size distribution function.
Source files
breakupModel.H
breakupModel.C
Definition at line 51 of file breakupModel.H.
Constructor & Destructor Documentation
breakupModel()
breakupModel (const populationBalanceModel & popBal, const dictionary & dict)
Definition at line 65 of file breakupModel.C.
References dict, breakupModel::dsd_, and daughterSizeDistributionModel::New().
~breakupModel()
virtual ~breakupModel () virtual default
Member Function Documentation
TypeName()
TypeName ("breakupModel")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , breakupModel , dictionary , (const populationBalanceModel &popBal, const dictionary &dict) , (popBal, dict))
clone()
autoPtr< breakupModel > clone () const inline
Definition at line 118 of file breakupModel.H.
References NotImplemented.
New()
Foam::autoPtr< Foam::diameterModels::breakupModel > New (const word & modelType, const populationBalanceModel & popBal, const dictionary & dict) static
Definition at line 39 of file breakupModel.C.
References Foam::abort(), dict, Foam::FatalIOError, FatalIOErrorInLookup, and breakupModel::popBal().
Referenced by breakupModel::iNew::operator()().
popBal()
const populationBalanceModel & popBal () const inline
Definition at line 142 of file breakupModel.H.
References breakupModel::popBal_.
Referenced by breakupModel::New().
dsdPtr() [1/2]
const autoPtr< daughterSizeDistributionModel > & dsdPtr () const inline
Definition at line 148 of file breakupModel.H.
References breakupModel::dsd_.
dsdPtr() [2/2]
autoPtr< daughterSizeDistributionModel > & dsdPtr () inline
Definition at line 154 of file breakupModel.H.
References breakupModel::dsd_.
correct()
void correct () virtual
Definition at line 80 of file breakupModel.C.
setBreakupRate()
virtual void setBreakupRate (volScalarField & breakupRate, const label i) pure virtual
Implemented in exponential, LaakkonenAlopaeusAittamaa, and powerLaw.
Member Data Documentation
popBal_
const populationBalanceModel& popBal_ protected
Definition at line 58 of file breakupModel.H.
Referenced by breakupModel::popBal().
dict_
dictionary dict_ protected
Definition at line 61 of file breakupModel.H.
dsd_
autoPtr<daughterSizeDistributionModel> dsd_ protected
Definition at line 64 of file breakupModel.H.
Referenced by breakupModel::breakupModel(), breakupModel::dsdPtr(), and breakupModel::dsdPtr().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/populationBalanceModel/breakupModels/breakupModel/breakupModel.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/populationBalanceModel/breakupModels/breakupModel/breakupModel.C