OpenFOAM: SHF< CloudType > Class Template Reference
SHF< CloudType > Class Template Reference
Lagrangian particle models » Submodels » Reacting » Breakup
Secondary Breakup Model to take account of the different breakup regimes, bag, molutimode, shear....
#include <SHF.H>
Public Member Functions
TypeName ("SHF")
SHF (const dictionary &, CloudType &)
SHF (const SHF< CloudType > &bum)
virtual autoPtr< BreakupModel< CloudType > > clone () const
virtual ~SHF ()
virtual bool update (const scalar dt, const vector &g, scalar &d, scalar &tc, scalar &ms, scalar &nParticle, scalar &KHindex, scalar &y, scalar &yDot, const scalar d0, const scalar rho, const scalar mu, const scalar sigma, const vector &U, const scalar rhoc, const scalar muc, const vector &Urel, const scalar Urmag, const scalar tMom, scalar &dChild, scalar &massChild)
Public Member Functions inherited from BreakupModel< CloudType >
TypeName ("breakupModel")
declareRunTimeSelectionTable (autoPtr, BreakupModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
BreakupModel (CloudType &owner)
BreakupModel (const dictionary &dict, CloudType &owner, const word &type, bool solveOscillationEq=false)
BreakupModel (const BreakupModel< CloudType > &bum)
virtual ~BreakupModel ()
bool solveOscillationEq () const
const scalar & y0 () const
const scalar & yDot0 () const
const scalar & TABComega () const
const scalar & TABCmu () const
const scalar & TABtwoWeCrit () const
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
virtual ~CloudSubModelBase ()=default
const CloudType & owner () const
virtual bool writeTime () const
virtual fileName localPath () const
CloudType & owner ()
virtual void info ()
virtual void write (Ostream &os) const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
subModelBase (const subModelBase &smb)
virtual ~subModelBase ()=default
const word & modelName () const
const dictionary & dict () const
const word & baseName () const
const word & modelType () const
const dictionary & coeffDict () const
const dictionary & properties () const
virtual bool defaultCoeffs (const bool printMsg) const
virtual bool active () const
virtual void cacheFields (const bool store)
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
bool getModelDict (const word &entryName, dictionary &dict) const
template<class Type >
bool getModelProperty (const word &entryName, Type &value) const
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Additional Inherited Members
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Static Public Member Functions inherited from BreakupModel< CloudType >
static autoPtr< BreakupModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Public Attributes inherited from subModelBase
bool log
Protected Member Functions inherited from subModelBase
bool inLine () const
Protected Attributes inherited from BreakupModel< CloudType >
bool solveOscillationEq_
scalar y0_
scalar yDot0_
scalar TABComega_
scalar TABCmu_
scalar TABtwoWeCrit_
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Protected Attributes inherited from subModelBase
const word modelName_
dictionary & properties_
const dictionary dict_
const word baseName_
const word modelType_
const dictionary coeffDict_
Detailed Description
template<class CloudType>
class Foam::SHF< CloudType >
Secondary Breakup Model to take account of the different breakup regimes, bag, molutimode, shear....
Accurate description in
R. Schmehl, G. Maier, S. Witting
"CFD Analysis of Fuel Atomization, Secondary Droplet Breakup and Spray
Dispersion in the Premix Duct of a LPP Combustor".
Eight International Conference on Liquid Atomization and Spray Systems, 2000
Definition at line 54 of file SHF.H.
Constructor & Destructor Documentation
SHF() [1/2]
template<class CloudType > SHF (const dictionary & dict, CloudType & owner)
Definition at line 26 of file SHF.C.
SHF() [2/2]
template<class CloudType > SHF (const SHF< CloudType > & bum)
Definition at line 66 of file SHF.C.
~SHF()
template<class CloudType > ~SHF () virtual
Definition at line 104 of file SHF.C.
Member Function Documentation
TypeName()
template<class CloudType > TypeName ("SHF< CloudType >")
clone()
template<class CloudType > virtual autoPtr< BreakupModel< CloudType > > clone () const inline virtual
Implements BreakupModel< CloudType >.
Definition at line 121 of file SHF.H.
update()
template<class CloudType > bool update (const scalar dt, const vector & g, scalar & d, scalar & tc, scalar & ms, scalar & nParticle, scalar & KHindex, scalar & y, scalar & yDot, const scalar d0, const scalar rho, const scalar mu, const scalar sigma, const vector & U, const scalar rhoc, const scalar muc, const vector & Urel, const scalar Urmag, const scalar tMom, scalar & dChild, scalar & massChild) virtual
Implements BreakupModel< CloudType >.
Definition at line 111 of file SHF.C.
References Foam::exp(), mu, p, Foam::constant::mathematical::pi(), Foam::pow(), Foam::pow3(), rho, rndGen, Random::sample01(), Foam::sqr(), Foam::sqrt(), success, Foam::constant::mathematical::twoPi(), and x.
The documentation for this class was generated from the following files:
src/lagrangian/spray/submodels/BreakupModel/SHF/SHF.H
src/lagrangian/spray/submodels/BreakupModel/SHF/SHF.C