OpenFOAM: timeVaryingMassSorptionFvPatchScalarField Class Reference
timeVaryingMassSorptionFvPatchScalarField Class Reference
Boundary conditions » Generic
This boundary condition provides a first order fixed-value condition for a given scalar field to model time-dependent adsorption-desoprtion processes to be used with the interfaceOxideRate mass model.
#include <timeVaryingMassSorptionFvPatchScalarField.H>
Public Types
enum ddtSchemeType { tsEuler , tsCrankNicolson , tsBackward }
Public Member Functions
TypeName ("timeVaryingMassSorption")
timeVaryingMassSorptionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
timeVaryingMassSorptionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
timeVaryingMassSorptionFvPatchScalarField (const timeVaryingMassSorptionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
timeVaryingMassSorptionFvPatchScalarField (const timeVaryingMassSorptionFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
timeVaryingMassSorptionFvPatchScalarField (const timeVaryingMassSorptionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual void autoMap (const fvPatchFieldMapper &)
virtual void rmap (const fvPatchScalarField &, const labelList &)
tmp< scalarField > source () const
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
This boundary condition provides a first order fixed-value condition for a given scalar field to model time-dependent adsorption-desoprtion processes to be used with the interfaceOxideRate mass model.
where
= Concentration at cell
= Concentration at wall
= Adsorption rate constant [1/s]
= Desorption rate constant [1/s]
= Weight function
= Max concentration at wall
Usage
Example of the boundary condition specification:
<patchName>
{
    // Mandatory entries
    type        timeVaryingMassSorption;
    kbas        <scalar>;
    max         <scalar>;
    // Optional entries
    kdes        <scalar>;
    // Inherited entries
    ...
}
where the entries mean:
Property Description Type Reqd Deflt
type Type name: timeVaryingAdsorption word yes -
kbas Adsorption rate constant scalar yes -
max Maximum concentation at wall scalar yes -
kdes Desorption rate constant scalar no 0
The inherited entries are elaborated in:
fixedValueFvPatchFields.H
Source files
timeVaryingMassSorptionFvPatchScalarField.H
timeVaryingMassSorptionFvPatchScalarField.C
Definition at line 154 of file timeVaryingMassSorptionFvPatchScalarField.H.
Member Enumeration Documentation
ddtSchemeType
enum ddtSchemeType
Enumerator
tsEuler
tsCrankNicolson
tsBackward
Definition at line 163 of file timeVaryingMassSorptionFvPatchScalarField.H.
Constructor & Destructor Documentation
timeVaryingMassSorptionFvPatchScalarField() [1/5]
timeVaryingMassSorptionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 54 of file timeVaryingMassSorptionFvPatchScalarField.C.
timeVaryingMassSorptionFvPatchScalarField() [2/5]
timeVaryingMassSorptionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 68 of file timeVaryingMassSorptionFvPatchScalarField.C.
References dict, fvPatchField< Type >::operator=(), and Foam::Zero.
timeVaryingMassSorptionFvPatchScalarField() [3/5]
timeVaryingMassSorptionFvPatchScalarField (const timeVaryingMassSorptionFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 88 of file timeVaryingMassSorptionFvPatchScalarField.C.
timeVaryingMassSorptionFvPatchScalarField() [4/5]
timeVaryingMassSorptionFvPatchScalarField (const timeVaryingMassSorptionFvPatchScalarField & ptf)
Definition at line 104 of file timeVaryingMassSorptionFvPatchScalarField.C.
timeVaryingMassSorptionFvPatchScalarField() [5/5]
timeVaryingMassSorptionFvPatchScalarField (const timeVaryingMassSorptionFvPatchScalarField & ptf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 117 of file timeVaryingMassSorptionFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("timeVaryingMassSorption")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 228 of file timeVaryingMassSorptionFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 244 of file timeVaryingMassSorptionFvPatchScalarField.H.
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Definition at line 133 of file timeVaryingMassSorptionFvPatchScalarField.C.
rmap()
void rmap (const fvPatchScalarField & ptf, const labelList & addr) virtual
Definition at line 142 of file timeVaryingMassSorptionFvPatchScalarField.C.
source()
Foam::tmp< Foam::scalarField > source () const
Definition at line 153 of file timeVaryingMassSorptionFvPatchScalarField.C.
References cp, Foam::max(), tmp< T >::New(), and Foam::Zero.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 169 of file timeVaryingMassSorptionFvPatchScalarField.C.
References cp, Foam::exit(), Foam::FatalError, FatalErrorInFunction, fld(), Foam::max(), Foam::nl, and Foam::operator==().
write()
void write (Ostream & os) const virtual
Definition at line 245 of file timeVaryingMassSorptionFvPatchScalarField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntry(), Ostream::writeEntryIfDifferent(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/phaseSystemModels/multiphaseInter/phasesSystem/derivedFvPatchFields/timeVaryingMassSorption/timeVaryingMassSorptionFvPatchScalarField.H
src/phaseSystemModels/multiphaseInter/phasesSystem/derivedFvPatchFields/timeVaryingMassSorption/timeVaryingMassSorptionFvPatchScalarField.C