OpenFOAM: nutUTabulatedWallFunctionFvPatchScalarField Class Reference
nutUTabulatedWallFunctionFvPatchScalarField Class Reference
Turbulence models » Boundary conditions » Wall functions
This boundary condition provides a wall constraint on the turbulent viscosity (i.e. nut) based on velocity (i.e. U), for low- and high-Reynolds number applications.
#include <nutUTabulatedWallFunctionFvPatchScalarField.H>
Public Member Functions
TypeName ("nutTabulatedWallFunction")
nutUTabulatedWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
nutUTabulatedWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
nutUTabulatedWallFunctionFvPatchScalarField (const nutUTabulatedWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
nutUTabulatedWallFunctionFvPatchScalarField (const nutUTabulatedWallFunctionFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
nutUTabulatedWallFunctionFvPatchScalarField (const nutUTabulatedWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual tmp< scalarField > yPlus () const
virtual void write (Ostream &os) const
Public Member Functions inherited from nutWallFunctionFvPatchScalarField
TypeName ("nutWallFunction")
nutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
nutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &)
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
const wallFunctionCoefficients & wallCoeffs () const noexcept
virtual void updateCoeffs ()
Protected Member Functions
virtual tmp< scalarField > calcNut () const
tmp< scalarField > calcUPlus (const scalarField &Rey) const
void writeLocalEntries (Ostream &) const
Protected Member Functions inherited from nutWallFunctionFvPatchScalarField
virtual const volVectorField & U (const turbulenceModel &turb) const
virtual void checkType ()
void writeLocalEntries (Ostream &) const
Protected Attributes
word uPlusTableName_
uniformInterpolationTable< scalar > uPlusTable_
Protected Attributes inherited from nutWallFunctionFvPatchScalarField
word UName_
wallFunctionCoefficients wallCoeffs_
Additional Inherited Members
Static Public Member Functions inherited from nutWallFunctionFvPatchScalarField
static const nutWallFunctionFvPatchScalarField & nutw (const turbulenceModel &turbModel, const label patchi)
Detailed Description
This boundary condition provides a wall constraint on the turbulent viscosity (i.e. nut) based on velocity (i.e. U), for low- and high-Reynolds number applications.
As input, the user specifies a look-up table of u+ as a function of near-wall Reynolds number.
The table should be located in the $FOAM_CASE/constant directory.
Usage
Example of the boundary condition specification:
<patchName>
{
    // Mandatory entries
    type            nutTabulatedWallFunction;
    uPlusTable      myUPlusTable;
    // Inherited entries
    ...
}
where the entries mean:
Property Description Type Reqd Deflt
type Type name: nutUTabulatedWallFunction word yes -
uPlusTable u+ as a function of Re table name word yes -
The inherited entries are elaborated in:
nutWallFunctionFvPatchScalarField.H
uniformInterpolationTable.H
Note
The tables are not registered since the same table object may be used for more than one patch.
Source files
nutUTabulatedWallFunctionFvPatchScalarField.H
nutUTabulatedWallFunctionFvPatchScalarField.C
Definition at line 105 of file nutUTabulatedWallFunctionFvPatchScalarField.H.
Constructor & Destructor Documentation
nutUTabulatedWallFunctionFvPatchScalarField() [1/5]
nutUTabulatedWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 93 of file nutUTabulatedWallFunctionFvPatchScalarField.C.
nutUTabulatedWallFunctionFvPatchScalarField() [2/5]
nutUTabulatedWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 133 of file nutUTabulatedWallFunctionFvPatchScalarField.C.
nutUTabulatedWallFunctionFvPatchScalarField() [3/5]
nutUTabulatedWallFunctionFvPatchScalarField (const nutUTabulatedWallFunctionFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 118 of file nutUTabulatedWallFunctionFvPatchScalarField.C.
nutUTabulatedWallFunctionFvPatchScalarField() [4/5]
nutUTabulatedWallFunctionFvPatchScalarField (const nutUTabulatedWallFunctionFvPatchScalarField & wfpsf)
Definition at line 159 of file nutUTabulatedWallFunctionFvPatchScalarField.C.
nutUTabulatedWallFunctionFvPatchScalarField() [5/5]
nutUTabulatedWallFunctionFvPatchScalarField (const nutUTabulatedWallFunctionFvPatchScalarField & wfpsf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 171 of file nutUTabulatedWallFunctionFvPatchScalarField.C.
Member Function Documentation
calcNut()
Foam::tmp< Foam::scalarField > calcNut () const protected virtual
Implements nutWallFunctionFvPatchScalarField.
Definition at line 31 of file nutUTabulatedWallFunctionFvPatchScalarField.C.
References nutUTabulatedWallFunctionFvPatchScalarField::calcUPlus(), IOobject::groupName(), Foam::mag(), magUp, Foam::max(), fvPatchField< Type >::patchInternalField(), turbulenceModel::propertiesName, fvPatchField< Type >::snGrad(), Foam::sqr(), U, and y.
calcUPlus()
Foam::tmp< Foam::scalarField > calcUPlus (const scalarField & Rey) const protected
Definition at line 65 of file nutUTabulatedWallFunctionFvPatchScalarField.C.
References forAll, tmp< T >::New(), Rey, uPlus, and Foam::Zero.
Referenced by nutUTabulatedWallFunctionFvPatchScalarField::calcNut().
writeLocalEntries()
void writeLocalEntries (Ostream & os) const protected
Definition at line 82 of file nutUTabulatedWallFunctionFvPatchScalarField.C.
References os(), and Ostream::writeEntry().
TypeName()
TypeName ("nutTabulatedWallFunction")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 173 of file nutUTabulatedWallFunctionFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 189 of file nutUTabulatedWallFunctionFvPatchScalarField.H.
yPlus()
Foam::tmp< Foam::scalarField > yPlus () const virtual
Implements nutWallFunctionFvPatchScalarField.
Definition at line 187 of file nutUTabulatedWallFunctionFvPatchScalarField.C.
References IOobject::groupName(), Foam::mag(), magUp, fvPatchField< Type >::patchInternalField(), turbulenceModel::propertiesName, Rey, U, and y.
write()
void write (Ostream & os) const virtual
Reimplemented from nutWallFunctionFvPatchScalarField.
Definition at line 214 of file nutUTabulatedWallFunctionFvPatchScalarField.C.
References os(), nutWallFunctionFvPatchScalarField::write(), and fvPatchField< Type >::writeValueEntry().
Member Data Documentation
uPlusTableName_
word uPlusTableName_ protected
Definition at line 114 of file nutUTabulatedWallFunctionFvPatchScalarField.H.
uPlusTable_
uniformInterpolationTable<scalar> uPlusTable_ protected
Definition at line 117 of file nutUTabulatedWallFunctionFvPatchScalarField.H.
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/derivedFvPatchFields/wallFunctions/nutWallFunctions/nutUTabulatedWallFunction/nutUTabulatedWallFunctionFvPatchScalarField.H
src/TurbulenceModels/turbulenceModels/derivedFvPatchFields/wallFunctions/nutWallFunctions/nutUTabulatedWallFunction/nutUTabulatedWallFunctionFvPatchScalarField.C