OpenFOAM: liquidProperties Class Reference
liquidProperties Class Reference abstract
The thermophysical properties of a liquid.
#include <liquidProperties.H>
Public Member Functions
TypeName ("liquid")
declareRunTimeSelectionTable (autoPtr, liquidProperties,,(),())
declareRunTimeSelectionTable (autoPtr, liquidProperties, dictionary,(const dictionary &dict),(dict))
liquidProperties (scalar W, scalar Tc, scalar Pc, scalar Vc, scalar Zc, scalar Tt, scalar Pt, scalar Tb, scalar dipm, scalar omega, scalar delta)
liquidProperties (const dictionary &dict)
virtual autoPtr< liquidProperties > clone () const =0
virtual ~liquidProperties ()=default
scalar Y () const
scalar Tc () const
scalar Pc () const
scalar Vc () const
scalar Zc () const
scalar Tt () const
scalar Pt () const
scalar Tb () const
scalar dipm () const
scalar omega () const
scalar delta () const
scalar limit (const scalar T) const
scalar psi (scalar p, scalar T) const
scalar CpMCv (scalar p, scalar T) const
scalar Ha (const scalar p, const scalar T) const
scalar Hs (const scalar p, const scalar T) const
scalar Hc () const
scalar S (const scalar p, const scalar T) const
virtual scalar pv (scalar p, scalar T) const =0
virtual scalar hl (scalar p, scalar T) const =0
virtual scalar h (scalar p, scalar T) const =0
virtual scalar Cpg (scalar p, scalar T) const =0
virtual scalar mu (scalar p, scalar T) const =0
virtual scalar mug (scalar p, scalar T) const =0
virtual scalar kappa (scalar p, scalar T) const =0
scalar alphah (const scalar p, const scalar T) const
virtual scalar kappag (scalar p, scalar T) const =0
virtual scalar sigma (scalar p, scalar T) const =0
virtual scalar D (scalar p, scalar T) const =0
virtual scalar D (scalar p, scalar T, scalar Wb) const =0
virtual scalar pvInvert (scalar p) const
void readIfPresent (const dictionary &dict)
template<class Func >
void readIfPresent (Func &f, const word &name, const dictionary &dict)
template<class Liquid >
void readIfPresent (Liquid &l, const dictionary &dict)
virtual void writeData (Ostream &os) const =0
template<class Liquid >
void writeData (const Liquid &l, Ostream &os) const
Public Member Functions inherited from thermophysicalProperties
TypeName ("thermophysicalProperties")
declareRunTimeSelectionTable (autoPtr, thermophysicalProperties,,(),())
declareRunTimeSelectionTable (autoPtr, thermophysicalProperties, dictionary,(const dictionary &dict),(dict))
thermophysicalProperties (scalar W)
thermophysicalProperties (const dictionary &dict)
virtual ~thermophysicalProperties ()=default
scalar W () const
scalar limit (const scalar T) const
virtual scalar rho (scalar p, scalar T) const =0
virtual scalar Cp (const scalar p, const scalar T) const =0
void readIfPresent (const dictionary &dict)
Static Public Member Functions
static autoPtr< liquidProperties > New (const word &name)
static autoPtr< liquidProperties > New (const dictionary &dict)
Static Public Member Functions inherited from thermophysicalProperties
static autoPtr< thermophysicalProperties > New (const word &name)
static autoPtr< thermophysicalProperties > New (const dictionary &dict)
Static Public Attributes
static const bool incompressible = true
static const bool isochoric = false
Friends
Ostream & operator<< (Ostream &os, const liquidProperties &l)
Detailed Description
The thermophysical properties of a liquid.
Source files
liquidProperties.H
liquidProperties.C
Definition at line 47 of file liquidProperties.H.
Constructor & Destructor Documentation
liquidProperties() [1/2]
liquidProperties (scalar W, scalar Tc, scalar Pc, scalar Vc, scalar Zc, scalar Tt, scalar Pt, scalar Tb, scalar dipm, scalar omega, scalar delta)
Definition at line 36 of file liquidProperties.C.
liquidProperties() [2/2]
liquidProperties (const dictionary & dict)
Definition at line 65 of file liquidProperties.C.
~liquidProperties()
virtual ~liquidProperties () virtual default
Member Function Documentation
TypeName()
TypeName ("liquid")
declareRunTimeSelectionTable() [1/2]
declareRunTimeSelectionTable (autoPtr , liquidProperties , () , ())
declareRunTimeSelectionTable() [2/2]
declareRunTimeSelectionTable (autoPtr , liquidProperties , dictionary , (const dictionary &dict) , (dict))
clone()
virtual autoPtr< liquidProperties > clone () const pure virtual
Implemented in aC10H7CH3, Ar, bC10H7CH3, C10H22, C12H26, C13H28, C14H30, C16H34, C2H5OH, C2H6, C2H6O, C3H6O, C3H8, C4H10O, C6H14, C6H6, C7H16, C7H8, C8H10, C8H18, C9H20, CH3OH, CH4N2O, H2O, iC3H8O, IC8H18, IDEA, liquid, MB, N2, and nC3H8O.
New() [1/2]
Foam::autoPtr< Foam::liquidProperties > New (const word & name) static
Definition at line 83 of file liquidProperties.C.
References DebugInFunction, Foam::exit(), Foam::FatalError, FatalErrorInLookup, Foam::name(), and Foam::nl.
Referenced by humidityTemperatureCoupledMixedFvPatchScalarField::humidityTemperatureCoupledMixedFvPatchScalarField(), liquidFilmThermo::initLiquid(), and liquidMixtureProperties::liquidMixtureProperties().
New() [2/2]
Foam::autoPtr< Foam::liquidProperties > New (const dictionary & dict) static
Definition at line 106 of file liquidProperties.C.
References DebugInFunction, dict, dictionary::dictName(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::found(), dictionary::get(), Foam::New(), Foam::nl, dictionary::optionalSubDict(), and dictionary::readIfPresent().
Y()
Foam::scalar Y () const inline
Definition at line 27 of file liquidPropertiesI.H.
Tc()
Foam::scalar Tc () const inline
Definition at line 33 of file liquidPropertiesI.H.
Pc()
Foam::scalar Pc () const inline
Definition at line 39 of file liquidPropertiesI.H.
Vc()
Foam::scalar Vc () const inline
Definition at line 45 of file liquidPropertiesI.H.
Zc()
Foam::scalar Zc () const inline
Definition at line 51 of file liquidPropertiesI.H.
Tt()
Foam::scalar Tt () const inline
Definition at line 57 of file liquidPropertiesI.H.
Pt()
Foam::scalar Pt () const inline
Definition at line 63 of file liquidPropertiesI.H.
Tb()
Foam::scalar Tb () const inline
Definition at line 69 of file liquidPropertiesI.H.
dipm()
Foam::scalar dipm () const inline
Definition at line 75 of file liquidPropertiesI.H.
omega()
Foam::scalar omega () const inline
Definition at line 81 of file liquidPropertiesI.H.
delta()
Foam::scalar delta () const inline
Definition at line 87 of file liquidPropertiesI.H.
limit()
Foam::scalar limit (const scalar T) const inline
Definition at line 21 of file liquidPropertiesI.H.
References T.
psi()
Foam::scalar psi (scalar p, scalar T) const inline virtual
Implements thermophysicalProperties.
Definition at line 93 of file liquidPropertiesI.H.
CpMCv()
Foam::scalar CpMCv (scalar p, scalar T) const inline virtual
Implements thermophysicalProperties.
Definition at line 99 of file liquidPropertiesI.H.
Ha()
Foam::scalar Ha (const scalar p, const scalar T) const inline virtual
Implements thermophysicalProperties.
Definition at line 105 of file liquidPropertiesI.H.
References h, p, and T.
Hs()
Foam::scalar Hs (const scalar p, const scalar T) const inline virtual
Implements thermophysicalProperties.
Definition at line 111 of file liquidPropertiesI.H.
References h, p, and T.
Hc()
Foam::scalar Hc () const inline virtual
Implements thermophysicalProperties.
Definition at line 117 of file liquidPropertiesI.H.
S()
Foam::scalar S (const scalar p, const scalar T) const virtual
Implements thermophysicalProperties.
Definition at line 167 of file liquidProperties.C.
References NotImplemented.
pv()
virtual scalar pv (scalar p, scalar T) const pure virtual
Implemented in aC10H7CH3, Ar, bC10H7CH3, C10H22, C12H26, C13H28, C14H30, C16H34, C2H5OH, C2H6, C2H6O, C3H6O, C3H8, C4H10O, C6H14, C6H6, C7H16, C7H8, C8H10, C8H18, C9H20, CH3OH, CH4N2O, H2O, iC3H8O, IC8H18, IDEA, liquid, MB, N2, and nC3H8O.
hl()
virtual scalar hl (scalar p, scalar T) const pure virtual
Implemented in aC10H7CH3, Ar, bC10H7CH3, C10H22, C12H26, C13H28, C14H30, C16H34, C2H5OH, C2H6, C2H6O, C3H6O, C3H8, C4H10O, C6H14, C6H6, C7H16, C7H8, C8H10, C8H18, C9H20, CH3OH, CH4N2O, H2O, iC3H8O, IC8H18, IDEA, liquid, MB, N2, and nC3H8O.
h()
virtual scalar h (scalar p, scalar T) const pure virtual
Implemented in aC10H7CH3, Ar, bC10H7CH3, C10H22, C12H26, C13H28, C14H30, C16H34, C2H5OH, C2H6, C2H6O, C3H6O, C3H8, C4H10O, C6H14, C6H6, C7H16, C7H8, C8H10, C8H18, C9H20, CH3OH, CH4N2O, H2O, iC3H8O, IC8H18, IDEA, liquid, MB, N2, and nC3H8O.
Cpg()
virtual scalar Cpg (scalar p, scalar T) const pure virtual
Implemented in aC10H7CH3, Ar, bC10H7CH3, C10H22, C12H26, C13H28, C14H30, C16H34, C2H5OH, C2H6, C2H6O, C3H6O, C3H8, C4H10O, C6H14, C6H6, C7H16, C7H8, C8H10, C8H18, C9H20, CH3OH, CH4N2O, H2O, iC3H8O, IC8H18, IDEA, liquid, MB, N2, and nC3H8O.
mu()
virtual scalar mu (scalar p, scalar T) const pure virtual
Implements thermophysicalProperties.
Implemented in aC10H7CH3, Ar, bC10H7CH3, C10H22, C12H26, C13H28, C14H30, C16H34, C2H5OH, C2H6, C2H6O, C3H6O, C3H8, C4H10O, C6H14, C6H6, C7H16, C7H8, C8H10, C8H18, C9H20, CH3OH, CH4N2O, H2O, iC3H8O, IC8H18, IDEA, liquid, MB, N2, and nC3H8O.
mug()
virtual scalar mug (scalar p, scalar T) const pure virtual
Implemented in aC10H7CH3, Ar, bC10H7CH3, C10H22, C12H26, C13H28, C14H30, C16H34, C2H5OH, C2H6, C2H6O, C3H6O, C3H8, C4H10O, C6H14, C6H6, C7H16, C7H8, C8H10, C8H18, C9H20, CH3OH, CH4N2O, H2O, iC3H8O, IC8H18, IDEA, liquid, MB, N2, and nC3H8O.
kappa()
virtual scalar kappa (scalar p, scalar T) const pure virtual
Implements thermophysicalProperties.
Implemented in aC10H7CH3, Ar, bC10H7CH3, C10H22, C12H26, C13H28, C14H30, C16H34, C2H5OH, C2H6, C2H6O, C3H6O, C3H8, C4H10O, C6H14, C6H6, C7H16, C7H8, C8H10, C8H18, C9H20, CH3OH, CH4N2O, H2O, iC3H8O, IC8H18, IDEA, liquid, MB, N2, and nC3H8O.
alphah()
Foam::scalar alphah (const scalar p, const scalar T) const inline virtual
Implements thermophysicalProperties.
Definition at line 123 of file liquidPropertiesI.H.
References Cp, p, and T.
kappag()
virtual scalar kappag (scalar p, scalar T) const pure virtual
Implemented in aC10H7CH3, Ar, bC10H7CH3, C10H22, C12H26, C13H28, C14H30, C16H34, C2H5OH, C2H6, C2H6O, C3H6O, C3H8, C4H10O, C6H14, C6H6, C7H16, C7H8, C8H10, C8H18, C9H20, CH3OH, CH4N2O, H2O, iC3H8O, IC8H18, IDEA, liquid, MB, N2, and nC3H8O.
sigma()
virtual scalar sigma (scalar p, scalar T) const pure virtual
Implemented in aC10H7CH3, Ar, bC10H7CH3, C10H22, C12H26, C13H28, C14H30, C16H34, C2H5OH, C2H6, C2H6O, C3H6O, C3H8, C4H10O, C6H14, C6H6, C7H16, C7H8, C8H10, C8H18, C9H20, CH3OH, CH4N2O, H2O, iC3H8O, IC8H18, IDEA, liquid, MB, N2, and nC3H8O.
D() [1/2]
virtual scalar D (scalar p, scalar T) const pure virtual
Implemented in aC10H7CH3, Ar, bC10H7CH3, C10H22, C12H26, C13H28, C14H30, C16H34, C2H5OH, C2H6, C2H6O, C3H6O, C3H8, C4H10O, C6H14, C6H6, C7H16, C7H8, C8H10, C8H18, C9H20, CH3OH, CH4N2O, H2O, iC3H8O, IC8H18, IDEA, liquid, MB, N2, and nC3H8O.
D() [2/2]
virtual scalar D (scalar p, scalar T, scalar Wb) const pure virtual
Implemented in aC10H7CH3, Ar, bC10H7CH3, C10H22, C12H26, C13H28, C14H30, C16H34, C2H5OH, C2H6, C2H6O, C3H6O, C3H8, C4H10O, C6H14, C6H6, C7H16, C7H8, C8H10, C8H18, C9H20, CH3OH, CH4N2O, H2O, iC3H8O, IC8H18, IDEA, liquid, MB, N2, and nC3H8O.
pvInvert()
Foam::scalar pvInvert (scalar p) const virtual
Definition at line 174 of file liquidProperties.C.
References Foam::endl(), Foam::nl, p, T, and WarningInFunction.
readIfPresent() [1/3]
void readIfPresent (const dictionary & dict)
Definition at line 217 of file liquidProperties.C.
References dict, thermophysicalProperties::readIfPresent(), and dictionary::readIfPresent().
Referenced by aC10H7CH3::aC10H7CH3(), Ar::Ar(), bC10H7CH3::bC10H7CH3(), C10H22::C10H22(), C12H26::C12H26(), C13H28::C13H28(), C14H30::C14H30(), C16H34::C16H34(), C2H5OH::C2H5OH(), C2H6::C2H6(), C2H6O::C2H6O(), C3H6O::C3H6O(), C3H8::C3H8(), C4H10O::C4H10O(), C6H14::C6H14(), C6H6::C6H6(), C7H16::C7H16(), C7H8::C7H8(), C8H10::C8H10(), C8H18::C8H18(), C9H20::C9H20(), CH3OH::CH3OH(), CH4N2O::CH4N2O(), H2O::H2O(), iC3H8O::iC3H8O(), IC8H18::IC8H18(), IDEA::IDEA(), MB::MB(), N2::N2(), and nC3H8O::nC3H8O().
readIfPresent() [2/3]
template<class Func > void readIfPresent (Func & f, const word & name, const dictionary & dict) inline
Definition at line 130 of file liquidPropertiesI.H.
References dict, f(), dictionary::found(), Foam::name(), and dictionary::subDict().
readIfPresent() [3/3]
template<class Liquid > void readIfPresent (Liquid & l, const dictionary & dict) inline
Definition at line 145 of file liquidPropertiesI.H.
References dict, and readIfPresent().
writeData() [1/2]
void writeData (Ostream & os) const pure virtual
Implements thermophysicalProperties.
Implemented in aC10H7CH3, Ar, bC10H7CH3, C10H22, C12H26, C13H28, C14H30, C16H34, C2H5OH, C2H6, C2H6O, C3H6O, C3H8, C4H10O, C6H14, C6H6, C7H16, C7H8, C8H10, C8H18, C9H20, CH3OH, CH4N2O, H2O, iC3H8O, IC8H18, IDEA, liquid, MB, N2, and nC3H8O.
Definition at line 233 of file liquidProperties.C.
References os(), token::SPACE, and thermophysicalProperties::writeData().
Referenced by Foam::operator<<(), aC10H7CH3::writeData(), Ar::writeData(), bC10H7CH3::writeData(), C10H22::writeData(), C12H26::writeData(), C13H28::writeData(), C14H30::writeData(), C16H34::writeData(), C2H5OH::writeData(), C2H6::writeData(), C2H6O::writeData(), C3H6O::writeData(), C3H8::writeData(), C4H10O::writeData(), C6H14::writeData(), C6H6::writeData(), C7H16::writeData(), C7H8::writeData(), C8H10::writeData(), C8H18::writeData(), C9H20::writeData(), CH3OH::writeData(), CH4N2O::writeData(), H2O::writeData(), iC3H8O::writeData(), IC8H18::writeData(), IDEA::writeData(), liquid::writeData(), MB::writeData(), N2::writeData(), and nC3H8O::writeData().
writeData() [2/2]
template<class Liquid > void writeData (const Liquid & l, Ostream & os) const inline
Definition at line 169 of file liquidPropertiesI.H.
References Foam::endl(), Foam::nl, and os().
Friends And Related Symbol Documentation
operator<<
Ostream & operator<< (Ostream & os, const liquidProperties & l) friend
Member Data Documentation
incompressible
const bool incompressible = true static
Definition at line 151 of file liquidProperties.H.
isochoric
const bool isochoric = false static
Definition at line 154 of file liquidProperties.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/thermophysicalProperties/liquidProperties/liquidProperties/liquidProperties.H
src/thermophysicalModels/thermophysicalProperties/liquidProperties/liquidProperties/liquidProperties.C
src/thermophysicalModels/thermophysicalProperties/liquidProperties/liquidProperties/liquidPropertiesI.H