OpenFOAM: extendedUpwindCellToFaceStencil Class Reference
extendedUpwindCellToFaceStencil Class Reference
Creates upwind stencil by shifting a centred stencil to upwind and downwind faces and optionally removing all non-(up/down)wind faces ('pureUpwind').
#include <extendedUpwindCellToFaceStencil.H>
Public Member Functions
extendedUpwindCellToFaceStencil (const cellToFaceStencil &, const bool pureUpwind, const scalar minOpposedness)
extendedUpwindCellToFaceStencil (const cellToFaceStencil &)
bool pureUpwind () const
const mapDistribute & ownMap () const
const mapDistribute & neiMap () const
const labelListList & ownStencil () const
const labelListList & neiStencil () const
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > weightedSum (const surfaceScalarField &phi, const GeometricField< Type, fvPatchField, volMesh > &fld, const List< List< scalar > > &ownWeights, const List< List< scalar > > &neiWeights) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > weightedSum (const surfaceScalarField &phi, const GeometricField< Type, fvPatchField, volMesh > &fld, const List< List< scalar > > &ownWeights, const List< List< scalar > > &neiWeights) const
Public Member Functions inherited from extendedCellToFaceStencil
ClassName ("extendedCellToFaceStencil")
extendedCellToFaceStencil (const polyMesh &)
template<class Type >
void collectData (const mapDistribute &map, const labelListList &stencil, const GeometricField< Type, fvPatchField, volMesh > &fld, List< List< Type > > &stencilFld)
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > weightedSum (const mapDistribute &map, const labelListList &stencil, const GeometricField< Type, fvPatchField, volMesh > &fld, const List< List< scalar > > &stencilWeights)
Additional Inherited Members
Static Public Member Functions inherited from extendedCellToFaceStencil
template<class T >
static void collectData (const mapDistribute &map, const labelListList &stencil, const GeometricField< T, fvPatchField, volMesh > &fld, List< List< T > > &stencilFld)
template<class Type >
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > weightedSum (const mapDistribute &map, const labelListList &stencil, const GeometricField< Type, fvPatchField, volMesh > &fld, const List< List< scalar > > &stencilWeights)
Static Protected Member Functions inherited from extendedCellToFaceStencil
static void writeStencilStats (Ostream &os, const labelListList &stencil, const mapDistribute &map)
Protected Attributes inherited from extendedCellToFaceStencil
const polyMesh & mesh_
Detailed Description
Creates upwind stencil by shifting a centred stencil to upwind and downwind faces and optionally removing all non-(up/down)wind faces ('pureUpwind').
Note: the minOpposedness parameter is to decide which upwind and downwind faces to combine the stencils from. If myArea is the local area and upwindArea the area of the possible upwind candidate it will be included if (upwindArea & myArea)/magSqr(myArea) > minOpposedness so this includes both cosine and area. WIP.
Source files
extendedUpwindCellToFaceStencil.H
extendedUpwindCellToFaceStencil.C
extendedUpwindCellToFaceStencilTemplates.C
Definition at line 57 of file extendedUpwindCellToFaceStencil.H.
Constructor & Destructor Documentation
extendedUpwindCellToFaceStencil() [1/2]
extendedUpwindCellToFaceStencil (const cellToFaceStencil & stencil, const bool pureUpwind, const scalar minOpposedness)
Definition at line 375 of file extendedUpwindCellToFaceStencil.C.
References PtrList< T >::append(), extendedCellToFaceStencil::collectData(), forAll, cellToFaceStencil::globalNumbering(), mesh, cellToFaceStencil::mesh(), UPstream::nProcs(), points, UPtrList< T >::size(), UList< T >::size(), and List< T >::transfer().
extendedUpwindCellToFaceStencil() [2/2]
extendedUpwindCellToFaceStencil (const cellToFaceStencil & stencil)
Definition at line 519 of file extendedUpwindCellToFaceStencil.C.
References PtrList< T >::append(), extendedCellToFaceStencil::collectData(), forAll, cellToFaceStencil::globalNumbering(), mesh, cellToFaceStencil::mesh(), UPstream::nProcs(), points, List< T >::setSize(), UPtrList< T >::size(), UList< T >::size(), and List< T >::transfer().
Member Function Documentation
pureUpwind()
bool pureUpwind () const inline
Definition at line 147 of file extendedUpwindCellToFaceStencil.H.
ownMap()
const mapDistribute & ownMap () const inline
Definition at line 153 of file extendedUpwindCellToFaceStencil.H.
Referenced by pureUpwindCFCCellToFaceStencilObject::pureUpwindCFCCellToFaceStencilObject(), upwindCECCellToFaceStencilObject::upwindCECCellToFaceStencilObject(), upwindCFCCellToFaceStencilObject::upwindCFCCellToFaceStencilObject(), upwindCPCCellToFaceStencilObject::upwindCPCCellToFaceStencilObject(), upwindFECCellToFaceStencilObject::upwindFECCellToFaceStencilObject(), and extendedUpwindCellToFaceStencil::weightedSum().
neiMap()
const mapDistribute & neiMap () const inline
Definition at line 159 of file extendedUpwindCellToFaceStencil.H.
Referenced by extendedUpwindCellToFaceStencil::weightedSum().
ownStencil()
const labelListList & ownStencil () const inline
Definition at line 165 of file extendedUpwindCellToFaceStencil.H.
Referenced by pureUpwindCFCCellToFaceStencilObject::pureUpwindCFCCellToFaceStencilObject(), upwindCECCellToFaceStencilObject::upwindCECCellToFaceStencilObject(), upwindCFCCellToFaceStencilObject::upwindCFCCellToFaceStencilObject(), upwindCPCCellToFaceStencilObject::upwindCPCCellToFaceStencilObject(), upwindFECCellToFaceStencilObject::upwindFECCellToFaceStencilObject(), and extendedUpwindCellToFaceStencil::weightedSum().
neiStencil()
const labelListList & neiStencil () const inline
Definition at line 171 of file extendedUpwindCellToFaceStencil.H.
Referenced by extendedUpwindCellToFaceStencil::weightedSum().
weightedSum() [1/2]
template<class Type > tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > weightedSum (const surfaceScalarField & phi, const GeometricField< Type, fvPatchField, volMesh > & fld, const List< List< scalar > > & ownWeights, const List< List< scalar > > & neiWeights) const
Referenced by PureUpwindFitScheme< Type, Polynomial, Stencil >::correction(), and UpwindFitScheme< Type, Polynomial, Stencil >::correction().
weightedSum() [2/2]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > weightedSum (const surfaceScalarField & phi, const GeometricField< Type, fvPatchField, volMesh > & fld, const List< List< scalar > > & ownWeights, const List< List< scalar > > & neiWeights) const
Definition at line 27 of file extendedUpwindCellToFaceStencilTemplates.C.
References extendedCellToFaceStencil::collectData(), fld(), forAll, mesh, extendedUpwindCellToFaceStencil::neiMap(), extendedUpwindCellToFaceStencil::neiStencil(), IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, extendedUpwindCellToFaceStencil::ownMap(), extendedUpwindCellToFaceStencil::ownStencil(), phi, and Foam::Zero.
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/extendedStencil/cellToFace/extendedUpwindCellToFaceStencil.H
src/finiteVolume/fvMesh/extendedStencil/cellToFace/extendedUpwindCellToFaceStencil.C
src/finiteVolume/fvMesh/extendedStencil/cellToFace/extendedUpwindCellToFaceStencilTemplates.C