OpenFOAM: dimensionSets Class Reference
dimensionSets Class Reference
#include <dimensionSets.H>
Public Member Functions
dimensionSets (const HashTable< dimensionedScalar > &, const wordList &unitNames)
const PtrList< dimensionedScalar > & units () const noexcept
bool valid () const noexcept
void coefficients (scalarField &exponents) const
Detailed Description
Definition at line 89 of file dimensionSets.H.
Constructor & Destructor Documentation
dimensionSets()
dimensionSets (const HashTable< dimensionedScalar > & units, const wordList & unitNames)
Definition at line 219 of file dimensionSets.C.
References forAll, Foam::LUDecompose(), Matrix< Form, Type >::m(), Matrix< Form, Type >::n(), PtrList< T >::set(), List< T >::setSize(), UPtrList< T >::size(), and dimensionSets::units().
Member Function Documentation
units()
const PtrList< dimensionedScalar > & units () const inline noexcept
Definition at line 121 of file dimensionSets.H.
Referenced by dimensionSets::dimensionSets().
valid()
bool valid () const inline noexcept
Definition at line 127 of file dimensionSets.H.
coefficients()
void coefficients (scalarField & exponents) const
Definition at line 263 of file dimensionSets.C.
References Foam::LUBacksubstitute().
The documentation for this class was generated from the following files:
src/OpenFOAM/dimensionSet/dimensionSets.H
src/OpenFOAM/dimensionSet/dimensionSets.C