OpenFOAM: Burns Class Reference
Burns Class Reference
Turbulent dispersion model of Burns et al.
#include <Burns.H>
Public Member Functions
TypeName ("Burns")
Burns (const dictionary &dict, const phasePair &pair)
virtual ~Burns ()
virtual tmp< volScalarField > D () const
TypeName ("Burns")
Burns (const dictionary &dict, const phasePair &pair)
virtual ~Burns ()
virtual tmp< volScalarField > D () const
Public Member Functions inherited from turbulentDispersionModel
TypeName ("turbulentDispersionModel")
declareRunTimeSelectionTable (autoPtr, turbulentDispersionModel, dictionary,(const dictionary &dict, const phasePair &pair),(dict, pair))
turbulentDispersionModel (const dictionary &dict, const phasePair &pair)
virtual ~turbulentDispersionModel ()=default
const phaseCompressibleTurbulenceModel & continuousTurbulence () const
virtual tmp< volVectorField > F () const
virtual tmp< surfaceScalarField > Ff () const
TypeName ("turbulentDispersionModel")
declareRunTimeSelectionTable (autoPtr, turbulentDispersionModel, dictionary,(const dictionary &dict, const phasePair &pair),(dict, pair))
turbulentDispersionModel (const dictionary &dict, const phasePair &pair)
virtual ~turbulentDispersionModel ()=default
virtual tmp< volVectorField > F () const
Additional Inherited Members
Static Public Member Functions inherited from turbulentDispersionModel
static autoPtr< turbulentDispersionModel > New (const dictionary &dict, const phasePair &pair)
static autoPtr< turbulentDispersionModel > New (const dictionary &dict, const phasePair &pair)
Static Public Attributes inherited from turbulentDispersionModel
static const dimensionSet dimD
static const dimensionSet dimF
Protected Attributes inherited from turbulentDispersionModel
const phasePair & pair_
Detailed Description
Turbulent dispersion model of Burns et al.
References:
    Otromke, M. (2013).
    Implementation and Comparison of Correlations for interfacial Forces in
    a Gas-Liquid System within an Euler-Euler Framework.
    PhD Thesis.
    Burns, A. D., Frank, T., Hamill, I., & Shi, J. M. (2004, May).
    The Favre averaged drag model for turbulent dispersion in Eulerian
    multi-phase flows.
    In 5th international conference on multiphase flow,
    ICMF (Vol. 4, pp. 1-17).
Source files
Burns.H
Burns.C
References:
    "Implementation and Comparison of Correlations for interfacial Forces
    in a Gas-Liquid System within an Euler-Euler Framework"
    Otromke, M.,
    PhD Thesis
    April 2013
    "The Favre averaged drag model for turbulent dispersion in Eulerian
     multi-phase flows"
    Burns, A.D., Frank, T., Hamill, I., Shi, J.M.,
    5th international conference on multiphase flow
    Volume 4, Paper 392, May 2004
Source files
Burns.H
Burns.C
Definition at line 67 of file Burns.H.
Constructor & Destructor Documentation
Burns() [1/2]
Burns (const dictionary & dict, const phasePair & pair)
Definition at line 47 of file Burns.C.
References Foam::dimless.
~Burns() [1/2]
~Burns () virtual
Definition at line 67 of file Burns.C.
Burns() [2/2]
Burns (const dictionary & dict, const phasePair & pair)
~Burns() [2/2]
virtual ~Burns () virtual
Member Function Documentation
TypeName() [1/2]
TypeName ("Burns")
D() [1/2]
Foam::tmp< Foam::volScalarField > D () const virtual
Implements turbulentDispersionModel.
Definition at line 74 of file Burns.C.
References dragModel::CdRe(), drag, IOobject::groupName(), Foam::max(), mesh, and Foam::sqr().
TypeName() [2/2]
TypeName ("Burns")
D() [2/2]
virtual tmp< volScalarField > D () const virtual
Implements turbulentDispersionModel.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/interfacialModels/turbulentDispersionModels/Burns/Burns.H
src/phaseSystemModels/twoPhaseEuler/twoPhaseSystem/interfacialModels/turbulentDispersionModels/Burns/Burns.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/interfacialModels/turbulentDispersionModels/Burns/Burns.C
src/phaseSystemModels/twoPhaseEuler/twoPhaseSystem/interfacialModels/turbulentDispersionModels/Burns/Burns.C