OpenFOAM: GammaWeight Class Reference
GammaWeight Class Reference
Class with operator() which returns the weighting factors for the Gamma differencing scheme. Used in conjunction with the template class NVDscheme.
#include <Gamma.H>
Public Member Functions
GammaWeight (Istream &is)
scalar weight (scalar cdWeight, scalar faceFlux, scalar phiP, scalar phiN, const vector &gradcP, const vector &gradcN, const vector &d) const
Detailed Description
Class with operator() which returns the weighting factors for the Gamma differencing scheme. Used in conjunction with the template class NVDscheme.
Source files
Gamma.H
GammaMake.C
Definition at line 50 of file Gamma.H.
Constructor & Destructor Documentation
GammaWeight()
GammaWeight (Istream & is) inline
Definition at line 56 of file Gamma.H.
References Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, and Foam::max().
Member Function Documentation
weight()
scalar weight (scalar cdWeight, scalar faceFlux, scalar phiP, scalar phiN, const vector & gradcP, const vector & gradcN, const vector & d) const inline
Definition at line 74 of file Gamma.H.
References Foam::clamp(), Foam::lerp(), Foam::limiter(), Foam::mag(), and Foam::stabilise().
The documentation for this class was generated from the following file:
src/finiteArea/interpolation/edgeInterpolation/schemes/Gamma/Gamma.H