OpenFOAM: timeControl Class Reference
timeControl Class Reference
Wrapper around functionObjects to add time control.
#include <timeControlFunctionObject.H>
Public Types
enum class controlMode { TIME , TRIGGER , TIME_OR_TRIGGER , TIME_AND_TRIGGER }
Public Member Functions
TypeName ("timeControl")
timeControl (const word &name, const Time &runTime, const dictionary &dict)
const dictionary & dict () const
const Foam::timeControl & executeControl () const
const Foam::timeControl & writeControl () const
const functionObject & filter () const
virtual bool execute ()
virtual bool execute (const label subIndex)
virtual bool write ()
virtual bool end ()
virtual bool adjustTimeStep ()
virtual bool filesModified () const
virtual bool read (const dictionary &)
virtual void updateMesh (const mapPolyMesh &mpm)
virtual void movePoints (const polyMesh &mesh)
Public Member Functions inherited from timeFunctionObject
timeFunctionObject (const word &name, const Time &runTime)
virtual ~timeFunctionObject ()=default
const Time & time () const
objectRegistry & storedObjects ()
const objectRegistry & storedObjects () const
Public Member Functions inherited from functionObject
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name, const bool withNamePrefix=defaultUseNamePrefix)
autoPtr< functionObject > clone () const
virtual ~functionObject ()=default
virtual const word & type () const =0
const word & name () const noexcept
bool useNamePrefix () const noexcept
bool useNamePrefix (bool on) noexcept
Static Public Member Functions
static bool entriesPresent (const dictionary &dict)
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &runTime, const dictionary &dict)
Static Public Attributes
static const Enum< controlMode > controlModeNames_
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
static bool defaultUseNamePrefix
static word outputPrefix
Additional Inherited Members
Public Attributes inherited from functionObject
bool log
Protected Member Functions inherited from timeFunctionObject
void clearOutputObjects (const wordList &objNames)
timeFunctionObject (const timeFunctionObject &)=delete
void operator= (const timeFunctionObject &)=delete
Protected Member Functions inherited from functionObject
word scopedName (const word &name) const
Protected Attributes inherited from timeFunctionObject
const Time & time_
Detailed Description
Wrapper around functionObjects to add time control.
Adds
timeStart, timeEnd activation
deltaT modification to hit writeInterval (note: if adjustableRunTime also in controlDict this has to be an integer multiple)
smooth deltaT variation through optional deltaTCoeff parameter
Note
Since the timeIndex is used directly from Foam::Time, it is unaffected by user-time conversions. For example, Foam::engineTime might cause writeInterval to be degrees crank angle, but the functionObject execution interval would still be in timestep.
The function object can be limited to operate within a time range using the timeStart and timEnd options. All objects are read (and the OutputFilter allocated) on construction. However, if a timeEnd is supplied, the object will call the 'end' function of the filter at the timeEnd time and destroy the filter. Any other callback (execute(), write(), timeSet() etc) will only operate if within the timeStart, timeEnd time range. Note that the time range uses 0.5 * deltaT as a comparison tolerance to account for precision errors.
Source files
timeControlFunctionObject.H
timeControlFunctionObject.C
Definition at line 72 of file timeControlFunctionObject.H.
Member Enumeration Documentation
controlMode
enum class controlMode strong
Enumerator
TIME
TRIGGER
TIME_OR_TRIGGER
TIME_AND_TRIGGER
Definition at line 81 of file timeControlFunctionObject.H.
Constructor & Destructor Documentation
timeControl()
timeControl (const word & name, const Time & runTime, const dictionary & dict)
Definition at line 449 of file timeControlFunctionObject.C.
Member Function Documentation
TypeName()
TypeName ("timeControl")
dict()
const Foam::dictionary & dict () const inline
Definition at line 23 of file timeControlFunctionObjectI.H.
executeControl()
const Foam::timeControl & executeControl () const inline
Definition at line 30 of file timeControlFunctionObjectI.H.
writeControl()
const Foam::timeControl & writeControl () const inline
Definition at line 37 of file timeControlFunctionObjectI.H.
filter()
const Foam::functionObject & filter () const inline
Definition at line 44 of file timeControlFunctionObjectI.H.
entriesPresent()
bool entriesPresent (const dictionary & dict) static
Definition at line 477 of file timeControlFunctionObject.C.
References dict, and timeControl::entriesPresent().
Referenced by functionObjectList::read(), and multiRegion::read().
execute() [1/2]
bool execute () virtual
Implements functionObject.
Definition at line 497 of file timeControlFunctionObject.C.
execute() [2/2]
bool execute (const label subIndex) virtual
Reimplemented from functionObject.
Definition at line 512 of file timeControlFunctionObject.C.
write()
bool write () virtual
Implements functionObject.
Definition at line 524 of file timeControlFunctionObject.C.
end()
bool end () virtual
Reimplemented from functionObject.
Definition at line 542 of file timeControlFunctionObject.C.
References UPtrList< T >::end().
adjustTimeStep()
bool adjustTimeStep () virtual
Reimplemented from functionObject.
Definition at line 553 of file timeControlFunctionObject.C.
References Foam::endl(), Foam::labelMax, Foam::log(), Foam::max(), Foam::min(), timeControl::ocAdjustableRunTime, and WarningInFunction.
filesModified()
bool filesModified () const virtual
Reimplemented from functionObject.
Definition at line 806 of file timeControlFunctionObject.C.
read()
bool read (const dictionary & dict) virtual
Reimplemented from functionObject.
Definition at line 788 of file timeControlFunctionObject.C.
References dict.
updateMesh()
void updateMesh (const mapPolyMesh & mpm) virtual
Reimplemented from functionObject.
Definition at line 812 of file timeControlFunctionObject.C.
movePoints()
void movePoints (const polyMesh & mesh) virtual
Reimplemented from functionObject.
Definition at line 821 of file timeControlFunctionObject.C.
References mesh.
Member Data Documentation
controlModeNames_
const Foam::Enum< Foam::functionObjects::timeControl::controlMode > controlModeNames_ static
Definition at line 89 of file timeControlFunctionObject.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/db/functionObjects/timeControl/timeControlFunctionObject.H
src/OpenFOAM/db/functionObjects/timeControl/timeControlFunctionObject.C
src/OpenFOAM/db/functionObjects/timeControl/timeControlFunctionObjectI.H