OpenFOAM: RanzMarshall Class Reference
RanzMarshall Class Reference
Ranz-Marshall correlation for turbulent heat transfer from the surface of a sphere to the surrounding fluid.
#include <RanzMarshall.H>
Public Member Functions
TypeName ("RanzMarshall")
RanzMarshall (const dictionary &dict, const phasePair &pair)
virtual ~RanzMarshall ()
tmp< volScalarField > K (const scalar residualAlpha) const
TypeName ("RanzMarshall")
RanzMarshall (const dictionary &dict, const phasePair &pair)
virtual ~RanzMarshall ()
tmp< volScalarField > K () const
Public Member Functions inherited from heatTransferModel
TypeName ("heatTransferModel")
declareRunTimeSelectionTable (autoPtr, heatTransferModel, dictionary,(const dictionary &dict, const phasePair &pair),(dict, pair))
heatTransferModel (const dictionary &dict, const phasePair &pair)
virtual ~heatTransferModel ()=default
tmp< volScalarField > K () const
TypeName ("heatTransferModel")
declareRunTimeSelectionTable (autoPtr, heatTransferModel, dictionary,(const dictionary &dict, const phasePair &pair),(dict, pair))
heatTransferModel (const dictionary &dict, const phasePair &pair)
virtual ~heatTransferModel ()=default
Additional Inherited Members
Static Public Member Functions inherited from heatTransferModel
static autoPtr< heatTransferModel > New (const dictionary &dict, const phasePair &pair)
static autoPtr< heatTransferModel > New (const dictionary &dict, const phasePair &pair)
Static Public Attributes inherited from heatTransferModel
static const dimensionSet dimK
Protected Attributes inherited from heatTransferModel
const phasePair & pair_
const dimensionedScalar residualAlpha_
Detailed Description
Ranz-Marshall correlation for turbulent heat transfer from the surface of a sphere to the surrounding fluid.
Source files
RanzMarshall.H
RanzMarshall.C
Source files
RanzMarshall.H
RanzMarshall.C
Definition at line 52 of file RanzMarshall.H.
Constructor & Destructor Documentation
RanzMarshall() [1/2]
RanzMarshall (const dictionary & dict, const phasePair & pair)
Definition at line 39 of file RanzMarshall.C.
~RanzMarshall() [1/2]
~RanzMarshall () virtual
Definition at line 51 of file RanzMarshall.C.
RanzMarshall() [2/2]
RanzMarshall (const dictionary & dict, const phasePair & pair)
~RanzMarshall() [2/2]
virtual ~RanzMarshall () virtual
Member Function Documentation
TypeName() [1/2]
TypeName ("RanzMarshall")
K() [1/2]
Foam::tmp< Foam::volScalarField > K (const scalar residualAlpha) const virtual
Implements heatTransferModel.
Definition at line 58 of file RanzMarshall.C.
References Foam::cbrt(), Foam::max(), Foam::sqr(), and Foam::sqrt().
TypeName() [2/2]
TypeName ("RanzMarshall")
K() [2/2]
Foam::tmp< Foam::volScalarField > K () const virtual
Implements heatTransferModel.
Definition at line 58 of file RanzMarshall.C.
References Foam::cbrt(), Foam::max(), Foam::sqr(), and Foam::sqrt().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/interfacialModels/heatTransferModels/RanzMarshall/RanzMarshall.H
src/phaseSystemModels/twoPhaseEuler/twoPhaseSystem/interfacialModels/heatTransferModels/RanzMarshall/RanzMarshall.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/interfacialModels/heatTransferModels/RanzMarshall/RanzMarshall.C
src/phaseSystemModels/twoPhaseEuler/twoPhaseSystem/interfacialModels/heatTransferModels/RanzMarshall/RanzMarshall.C