OpenFOAM: ReynoldsStress< BasicTurbulenceModel > Class Template Reference
ReynoldsStress< BasicTurbulenceModel > Class Template Reference abstract
Turbulence models
Reynolds-stress turbulence model base class.
#include <ReynoldsStress.H>
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
ReynoldsStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~ReynoldsStress ()=default
virtual bool read ()=0
virtual tmp< volScalarField > nut () const
virtual tmp< scalarField > nut (const label patchi) const
virtual tmp< volScalarField > k () const
virtual tmp< volSymmTensorField > R () const
virtual tmp< volSymmTensorField > devRhoReff () const
virtual tmp< volSymmTensorField > devRhoReff (const volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
virtual void validate ()
virtual void correct ()=0
template<class RhoFieldType >
Foam::tmp< Foam::fvVectorMatrix > DivDevRhoReff (const RhoFieldType &rho, volVectorField &U) const
Protected Member Functions
void boundNormalStress (volSymmTensorField &R) const
void correctWallShearStress (volSymmTensorField &R) const
void checkRealizabilityConditions (const volSymmTensorField &R) const
virtual void correctNut ()=0
template<class RhoFieldType >
tmp< fvVectorMatrix > DivDevRhoReff (const RhoFieldType &rho, volVectorField &U) const
Protected Attributes
dimensionedScalar couplingFactor_
volSymmTensorField R_
volScalarField nut_
Detailed Description
template<class BasicTurbulenceModel>
class Foam::ReynoldsStress< BasicTurbulenceModel >
Reynolds-stress turbulence model base class.
Reference:
    Realizability conditions (tag:S):
        Schumann, U. (1977).
        Realizability of Reynolds‐stress turbulence models.
        The Physics of Fluids, 20(5), 721-725.
        DOI:10.1063/1.861942
Source files
ReynoldsStress.H
ReynoldsStress.C
Definition at line 58 of file ReynoldsStress.H.
Member Typedef Documentation
alphaField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 97 of file ReynoldsStress.H.
rhoField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 98 of file ReynoldsStress.H.
transportModel
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 99 of file ReynoldsStress.H.
Constructor & Destructor Documentation
ReynoldsStress()
template<class BasicTurbulenceModel > ReynoldsStress (const word & modelName, const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName)
Definition at line 158 of file ReynoldsStress.C.
~ReynoldsStress()
template<class BasicTurbulenceModel > virtual ~ReynoldsStress () virtual default
Member Function Documentation
boundNormalStress()
template<class BasicTurbulenceModel > void boundNormalStress (volSymmTensorField & R) const protected
Definition at line 30 of file ReynoldsStress.C.
References R.
correctWallShearStress()
template<class BasicTurbulenceModel > void correctWallShearStress (volSymmTensorField & R) const protected
Definition at line 50 of file ReynoldsStress.C.
References forAll, patches, and R.
checkRealizabilityConditions()
template<class BasicTurbulenceModel > void checkRealizabilityConditions (const volSymmTensorField & R) const protected
Definition at line 97 of file ReynoldsStress.C.
correctNut()
template<class BasicTurbulenceModel > virtual void correctNut () protected pure virtual
Implemented in DeardorffDiffStress< BasicTurbulenceModel >, LRR< BasicTurbulenceModel >, and SSG< BasicTurbulenceModel >.
DivDevRhoReff() [1/2]
template<class BasicTurbulenceModel > template<class RhoFieldType > tmp< fvVectorMatrix > DivDevRhoReff (const RhoFieldType & rho, volVectorField & U) const protected
read()
template<class BasicTurbulenceModel > bool read () pure virtual
Implemented in DeardorffDiffStress< BasicTurbulenceModel >, EBRSM< BasicTurbulenceModel >, LRR< BasicTurbulenceModel >, and SSG< BasicTurbulenceModel >.
Definition at line 231 of file ReynoldsStress.C.
nut() [1/2]
template<class BasicTurbulenceModel > virtual tmp< volScalarField > nut () const inline virtual
Definition at line 128 of file ReynoldsStress.H.
References ReynoldsStress< BasicTurbulenceModel >::nut_.
nut() [2/2]
template<class BasicTurbulenceModel > virtual tmp< scalarField > nut (const label patchi) const inline virtual
Definition at line 134 of file ReynoldsStress.H.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), and ReynoldsStress< BasicTurbulenceModel >::nut_.
k()
template<class BasicTurbulenceModel > Foam::tmp< Foam::volScalarField > k () const virtual
Reimplemented in LRR< BasicTurbulenceModel >, and SSG< BasicTurbulenceModel >.
Definition at line 247 of file ReynoldsStress.C.
References Foam::tr().
R()
template<class BasicTurbulenceModel > Foam::tmp< Foam::volSymmTensorField > R () const virtual
Definition at line 239 of file ReynoldsStress.C.
devRhoReff() [1/2]
template<class BasicTurbulenceModel > Foam::tmp< Foam::volSymmTensorField > devRhoReff () const virtual
Definition at line 257 of file ReynoldsStress.C.
devRhoReff() [2/2]
template<class BasicTurbulenceModel > Foam::tmp< Foam::volSymmTensorField > devRhoReff (const volVectorField & U) const virtual
Definition at line 265 of file ReynoldsStress.C.
References Foam::devTwoSymm(), Foam::fvc::grad(), IOobject::groupName(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, and U.
divDevRhoReff() [1/2]
template<class BasicTurbulenceModel > Foam::tmp< Foam::fvVectorMatrix > divDevRhoReff (volVectorField & U) const virtual
Definition at line 340 of file ReynoldsStress.C.
References U.
divDevRhoReff() [2/2]
template<class BasicTurbulenceModel > Foam::tmp< Foam::fvVectorMatrix > divDevRhoReff (const volScalarField & rho, volVectorField & U) const virtual
Definition at line 351 of file ReynoldsStress.C.
References rho, and U.
validate()
template<class BasicTurbulenceModel > void validate () virtual
Definition at line 362 of file ReynoldsStress.C.
correct()
template<class BasicTurbulenceModel > void correct () pure virtual
Implemented in DeardorffDiffStress< BasicTurbulenceModel >, EBRSM< BasicTurbulenceModel >, LRR< BasicTurbulenceModel >, and SSG< BasicTurbulenceModel >.
Definition at line 369 of file ReynoldsStress.C.
DivDevRhoReff() [2/2]
template<class BasicTurbulenceModel > template<class RhoFieldType > Foam::tmp< Foam::fvVectorMatrix > DivDevRhoReff (const RhoFieldType & rho, volVectorField & U) const
Definition at line 293 of file ReynoldsStress.C.
References Foam::dev2(), Foam::fvc::div(), Foam::fvc::grad(), Foam::fvc::laplacian(), Foam::fvm::laplacian(), nu, nut, rho, T, and U.
Member Data Documentation
couplingFactor_
template<class BasicTurbulenceModel > dimensionedScalar couplingFactor_ protected
Definition at line 69 of file ReynoldsStress.H.
R_
template<class BasicTurbulenceModel > volSymmTensorField R_ protected
Definition at line 73 of file ReynoldsStress.H.
nut_
template<class BasicTurbulenceModel > volScalarField nut_ protected
Definition at line 74 of file ReynoldsStress.H.
Referenced by ReynoldsStress< BasicTurbulenceModel >::nut(), and ReynoldsStress< BasicTurbulenceModel >::nut().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/ReynoldsStress/ReynoldsStress.H
src/TurbulenceModels/turbulenceModels/ReynoldsStress/ReynoldsStress.C