OpenFOAM: subModelBase Class Reference
subModelBase Class Reference
Base class for generic sub-models requiring to be read from dictionary. Provides a mechanism to read and write properties from a dictionary to enable clean re-starts. Used by, e.g. clou dsub-models.
#include <subModelBase.H>
Public Member Functions
subModelBase (dictionary &properties)
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
subModelBase (const subModelBase &smb)
virtual ~subModelBase ()=default
const word & modelName () const
const dictionary & dict () const
const word & baseName () const
const word & modelType () const
const dictionary & coeffDict () const
const dictionary & properties () const
virtual bool defaultCoeffs (const bool printMsg) const
virtual bool active () const
virtual void cacheFields (const bool store)
virtual bool writeTime () const
virtual fileName localPath () const
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
bool getModelDict (const word &entryName, dictionary &dict) const
template<class Type >
bool getModelProperty (const word &entryName, Type &value) const
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
virtual void write (Ostream &os) const
Public Attributes
bool log
Protected Member Functions
bool inLine () const
Protected Attributes
const word modelName_
dictionary & properties_
const dictionary dict_
const word baseName_
const word modelType_
const dictionary coeffDict_
Detailed Description
Base class for generic sub-models requiring to be read from dictionary. Provides a mechanism to read and write properties from a dictionary to enable clean re-starts. Used by, e.g. clou dsub-models.
Source files
subModelBase.H
subModelBase.C
Definition at line 50 of file subModelBase.H.
Constructor & Destructor Documentation
subModelBase() [1/4]
subModelBase (dictionary & properties)
Definition at line 34 of file subModelBase.C.
References Foam::log().
subModelBase() [2/4]
subModelBase (dictionary & properties, const dictionary & dict, const word & baseName, const word & modelType, const word & dictExt = "Coeffs")
Definition at line 46 of file subModelBase.C.
subModelBase() [3/4]
subModelBase (const word & modelName, dictionary & properties, const dictionary & dict, const word & baseName, const word & modelType)
Definition at line 65 of file subModelBase.C.
subModelBase() [4/4]
subModelBase (const subModelBase & smb)
Definition at line 84 of file subModelBase.C.
~subModelBase()
virtual ~subModelBase () virtual default
Member Function Documentation
inLine()
bool inLine () const protected
modelName()
const Foam::word & modelName () const
Definition at line 98 of file subModelBase.C.
Referenced by InjectedParticleInjection< CloudType >::InjectedParticleInjection().
dict()
const Foam::dictionary & dict () const
Definition at line 104 of file subModelBase.C.
Referenced by BreakupModel< CloudType >::BreakupModel(), dynamicContactAngleForce::dynamicContactAngleForce(), liquidFilmThermo::initLiquid(), InjectedParticleDistributionInjection< CloudType >::InjectedParticleDistributionInjection(), injectionModelList::injectionModelList(), injectionModelList::injectionModelList(), injectionModel::New(), force::New(), filmThermoModel::New(), filmTurbulenceModel::New(), filmRadiationModel::New(), heatTransferModel::New(), phaseChangeModel::New(), injectionModel::New(), force::New(), transferModel::New(), filmViscosityModel::New(), and transferModelList::transferModelList().
baseName()
const Foam::word & baseName () const
Definition at line 110 of file subModelBase.C.
modelType()
const Foam::word & modelType () const
Definition at line 116 of file subModelBase.C.
Referenced by filmSubModelBase::filmType(), injectionModel::New(), force::New(), filmThermoModel::New(), filmTurbulenceModel::New(), filmRadiationModel::New(), heatTransferModel::New(), phaseChangeModel::New(), injectionModel::New(), force::New(), transferModel::New(), and filmViscosityModel::New().
coeffDict()
const Foam::dictionary & coeffDict () const
Definition at line 122 of file subModelBase.C.
Referenced by COxidationHurtMitchell< CloudType >::COxidationHurtMitchell(), ETAB< CloudType >::ETAB(), FaceInteraction< CloudType >::FaceInteraction(), FacePostProcessing< CloudType >::FacePostProcessing(), InflationInjection< CloudType >::InflationInjection(), KinematicSurfaceFilm< CloudType >::KinematicSurfaceFilm(), LiquidEvapFuchsKnudsen< CloudType >::LiquidEvapFuchsKnudsen(), LocalInteraction< CloudType >::LocalInteraction(), MUCSheterogeneousRate< CloudType >::MUCSheterogeneousRate(), MultiInteraction< CloudType >::MultiInteraction(), ParticleCollector< CloudType >::ParticleCollector(), ParticleErosion< CloudType >::ParticleErosion(), ParticleHistogram< CloudType >::ParticleHistogram(), ParticlePostProcessing< CloudType >::ParticlePostProcessing(), ParticleZoneInfo< CloudType >::ParticleZoneInfo(), PilchErdman< CloudType >::PilchErdman(), ReitzDiwakar< CloudType >::ReitzDiwakar(), ReitzKHRT< CloudType >::ReitzKHRT(), RemoveParcels< CloudType >::RemoveParcels(), SingleMixtureFraction< CloudType >::SingleMixtureFraction(), and StandardWallInteraction< CloudType >::StandardWallInteraction().
properties()
const Foam::dictionary & properties () const
Definition at line 128 of file subModelBase.C.
defaultCoeffs()
bool defaultCoeffs (const bool printMsg) const virtual
Definition at line 134 of file subModelBase.C.
References Foam::decrIndent(), Foam::endl(), Foam::incrIndent(), Foam::indent(), and Foam::Info.
Referenced by ETAB< CloudType >::ETAB(), PilchErdman< CloudType >::PilchErdman(), ReitzDiwakar< CloudType >::ReitzDiwakar(), and ReitzKHRT< CloudType >::ReitzKHRT().
active()
bool active () const virtual
Reimplemented in NoheterogeneousReacting< CloudType >, NoCollision< CloudType >, NoDispersion< CloudType >, NoInjection< CloudType >, MultiInteraction< CloudType >, NoInteraction< CloudType >, NoStochasticCollision< CloudType >, NoSurfaceFilm< CloudType >, NoDamping< CloudType >, NoIsotropy< CloudType >, NoPacking< CloudType >, NoPhaseChange< CloudType >, NoDevolatilisation< CloudType >, NoSurfaceReaction< CloudType >, NoHeatTransfer< CloudType >, NoAtomization< CloudType >, NoBreakup< CloudType >, and noPhaseChange.
Definition at line 149 of file subModelBase.C.
Referenced by phaseChangeModel::correct(), and filmSubModelBase::writeTime().
cacheFields()
void cacheFields (const bool store) virtual
Reimplemented in Relaxation< CloudType >, Explicit< CloudType >, Implicit< CloudType >, DispersionRASModel< CloudType >, and GradientDispersionRAS< CloudType >.
Definition at line 155 of file subModelBase.C.
Referenced by Explicit< CloudType >::cacheFields(), and Implicit< CloudType >::cacheFields().
writeTime()
bool writeTime () const virtual
Reimplemented in CloudSubModelBase< CloudType >, CloudSubModelBase< Foam::CollidingCloud< Foam::DSMCCloud > >, CloudSubModelBase< Foam::DSMCCloud >, CloudSubModelBase< Foam::KinematicCloud< Foam::DSMCCloud > >, CloudSubModelBase< Foam::MPPICCloud< Foam::DSMCCloud > >, CloudSubModelBase< Foam::ReactingCloud< Foam::DSMCCloud > >, CloudSubModelBase< Foam::ReactingHeterogeneousCloud< Foam::DSMCCloud > >, CloudSubModelBase< Foam::ReactingMultiphaseCloud< Foam::DSMCCloud > >, CloudSubModelBase< Foam::SprayCloud< Foam::DSMCCloud > >, CloudSubModelBase< Foam::ThermoCloud< Foam::DSMCCloud > >, CloudSubModelBase< KinematicCloud< Cloud< basicKinematicCollidingParcel > > >, CloudSubModelBase< KinematicCloud< CloudType > >, CloudSubModelBase< KinematicCloud< Foam::DSMCCloud > >, filmSubModelBase, and filmSubModelBase.
Definition at line 159 of file subModelBase.C.
localPath()
Foam::fileName localPath () const virtual
Reimplemented in CloudSubModelBase< CloudType >, CloudSubModelBase< Foam::CollidingCloud< Foam::DSMCCloud > >, CloudSubModelBase< Foam::DSMCCloud >, CloudSubModelBase< Foam::KinematicCloud< Foam::DSMCCloud > >, CloudSubModelBase< Foam::MPPICCloud< Foam::DSMCCloud > >, CloudSubModelBase< Foam::ReactingCloud< Foam::DSMCCloud > >, CloudSubModelBase< Foam::ReactingHeterogeneousCloud< Foam::DSMCCloud > >, CloudSubModelBase< Foam::ReactingMultiphaseCloud< Foam::DSMCCloud > >, CloudSubModelBase< Foam::SprayCloud< Foam::DSMCCloud > >, CloudSubModelBase< Foam::ThermoCloud< Foam::DSMCCloud > >, CloudSubModelBase< KinematicCloud< Cloud< basicKinematicCollidingParcel > > >, CloudSubModelBase< KinematicCloud< CloudType > >, and CloudSubModelBase< KinematicCloud< Foam::DSMCCloud > >.
Definition at line 165 of file subModelBase.C.
References word::null.
getBaseProperty() [1/2]
template<class Type > Type getBaseProperty (const word & entryName, const Type & defaultValue = Type(Zero)) const
Definition at line 24 of file subModelBaseTemplates.C.
References subModelBase::baseName_, dictionary::found(), subModelBase::properties_, and dictionary::subDict().
Referenced by injectionModelList::info(), and transferModelList::info().
getBaseProperty() [2/2]
template<class Type > void getBaseProperty (const word & entryName, Type & value) const
Definition at line 43 of file subModelBaseTemplates.C.
setBaseProperty()
template<class Type > void setBaseProperty (const word & entryName, const Type & value)
Definition at line 58 of file subModelBaseTemplates.C.
Referenced by injectionModelList::info(), and transferModelList::info().
getModelDict()
bool getModelDict (const word & entryName, dictionary & dict) const
Definition at line 176 of file subModelBase.C.
References dict, and dictionary::subOrEmptyDict().
Referenced by InjectedParticleDistributionInjection< CloudType >::InjectedParticleDistributionInjection().
getModelProperty() [1/2]
template<class Type > bool getModelProperty (const word & entryName, Type & value) const
Definition at line 78 of file subModelBaseTemplates.C.
Referenced by ParticleZoneInfo< CloudType >::ParticleZoneInfo(), and RemoveParcels< CloudType >::RemoveParcels().
getModelProperty() [2/2]
template<class Type > Type getModelProperty (const word & entryName, const Type & defaultValue = Type(Zero)) const
Definition at line 103 of file subModelBaseTemplates.C.
setModelProperty()
template<class Type > void setModelProperty (const word & entryName, const Type & value)
Definition at line 116 of file subModelBaseTemplates.C.
write()
void write (Ostream & os) const virtual
Reimplemented in CloudSubModelBase< CloudType >, CloudSubModelBase< Foam::CollidingCloud< Foam::DSMCCloud > >, CloudSubModelBase< Foam::DSMCCloud >, CloudSubModelBase< Foam::KinematicCloud< Foam::DSMCCloud > >, CloudSubModelBase< Foam::MPPICCloud< Foam::DSMCCloud > >, CloudSubModelBase< Foam::ReactingCloud< Foam::DSMCCloud > >, CloudSubModelBase< Foam::ReactingHeterogeneousCloud< Foam::DSMCCloud > >, CloudSubModelBase< Foam::ReactingMultiphaseCloud< Foam::DSMCCloud > >, CloudSubModelBase< Foam::SprayCloud< Foam::DSMCCloud > >, CloudSubModelBase< Foam::ThermoCloud< Foam::DSMCCloud > >, CloudSubModelBase< KinematicCloud< Cloud< basicKinematicCollidingParcel > > >, CloudSubModelBase< KinematicCloud< CloudType > >, CloudSubModelBase< KinematicCloud< Foam::DSMCCloud > >, and DispersionRASModel< CloudType >.
Definition at line 204 of file subModelBase.C.
References os().
Referenced by CloudSubModelBase< CloudType >::write().
Member Data Documentation
modelName_
const word modelName_ protected
Definition at line 63 of file subModelBase.H.
properties_
dictionary& properties_ protected
Definition at line 66 of file subModelBase.H.
Referenced by subModelBase::getBaseProperty().
dict_
const dictionary dict_ protected
Definition at line 69 of file subModelBase.H.
baseName_
const word baseName_ protected
Definition at line 72 of file subModelBase.H.
Referenced by subModelBase::getBaseProperty().
modelType_
const word modelType_ protected
Definition at line 75 of file subModelBase.H.
coeffDict_
const dictionary coeffDict_ protected
Definition at line 78 of file subModelBase.H.
Referenced by constantFilmThermo::Cp(), curvatureSeparation::curvatureSeparation(), constantFilmThermo::D(), constantFilmThermo::hl(), constantFilmThermo::kappa(), liquidFilmThermo::liquidFilmThermo(), constantFilmThermo::mu(), patchInjection::patchInjection(), constantFilmThermo::pv(), constantFilmThermo::rho(), constantFilmThermo::sigma(), constantFilmThermo::Tb(), and constantFilmThermo::W().
log
bool log
Definition at line 92 of file subModelBase.H.
Referenced by CloudSubModelBase< CloudType >::CloudSubModelBase(), and CloudSubModelBase< CloudType >::CloudSubModelBase().
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/subModelBase/subModelBase.H
src/OpenFOAM/primitives/subModelBase/subModelBase.C
src/OpenFOAM/primitives/subModelBase/subModelBaseTemplates.C