OpenFOAM: tetherPotential Class Reference
tetherPotential Class Reference abstract
#include <tetherPotential.H>
Public Member Functions
TypeName ("tetherPotential")
declareRunTimeSelectionTable (autoPtr, tetherPotential, dictionary,(const word &name, const dictionary &tetherPotentialProperties),(name, tetherPotentialProperties))
tetherPotential (const word &name, const dictionary &tetherPotentialProperties)
virtual ~tetherPotential ()=default
virtual scalar energy (const vector r) const =0
virtual vector force (const vector r) const =0
const dictionary & tetherPotentialProperties () const
virtual bool read (const dictionary &tetherPotentialProperties)=0
Static Public Member Functions
static autoPtr< tetherPotential > New (const word &name, const dictionary &tetherPotentialProperties)
Protected Member Functions
tetherPotential (const tetherPotential &)=delete
void operator= (const tetherPotential &)=delete
Protected Attributes
word name_
dictionary tetherPotentialProperties_
Detailed Description
Source files
tetherPotential.H
tetherPotential.C
tetherPotentialNew.C
Definition at line 51 of file tetherPotential.H.
Constructor & Destructor Documentation
tetherPotential() [1/2]
tetherPotential (const tetherPotential &) protected delete
tetherPotential() [2/2]
tetherPotential (const word & name, const dictionary & tetherPotentialProperties)
Definition at line 34 of file tetherPotential.C.
References Foam::name().
~tetherPotential()
virtual ~tetherPotential () virtual default
Member Function Documentation
operator=()
void operator= (const tetherPotential &) protected delete
TypeName()
TypeName ("tetherPotential")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , tetherPotential , dictionary , (const word &name, const dictionary &tetherPotentialProperties) , (name, tetherPotentialProperties))
New()
Foam::autoPtr< Foam::tetherPotential > New (const word & name, const dictionary & tetherPotentialProperties) static
Definition at line 26 of file tetherPotentialNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, Foam::Info, Foam::name(), and Foam::nl.
energy()
virtual scalar energy (const vector r) const pure virtual
Implemented in harmonicSpring, pitchForkRing, and restrainedHarmonicSpring.
force()
virtual vector force (const vector r) const pure virtual
Implemented in harmonicSpring, pitchForkRing, and restrainedHarmonicSpring.
tetherPotentialProperties()
const dictionary & tetherPotentialProperties () const inline
Definition at line 122 of file tetherPotential.H.
References tetherPotential::tetherPotentialProperties_.
Referenced by harmonicSpring::read(), pitchForkRing::read(), and restrainedHarmonicSpring::read().
read()
bool read (const dictionary & tetherPotentialProperties) pure virtual
Implemented in harmonicSpring, pitchForkRing, and restrainedHarmonicSpring.
Definition at line 48 of file tetherPotential.C.
Referenced by harmonicSpring::read(), pitchForkRing::read(), and restrainedHarmonicSpring::read().
Member Data Documentation
name_
word name_ protected
Definition at line 58 of file tetherPotential.H.
tetherPotentialProperties_
dictionary tetherPotentialProperties_ protected
Definition at line 59 of file tetherPotential.H.
Referenced by tetherPotential::tetherPotentialProperties().
The documentation for this class was generated from the following files:
src/lagrangian/molecularDynamics/potential/tetherPotential/basic/tetherPotential.H
src/lagrangian/molecularDynamics/potential/tetherPotential/basic/tetherPotential.C
src/lagrangian/molecularDynamics/potential/tetherPotential/basic/tetherPotentialNew.C