OpenFOAM: patchEdgeFaceRegions Class Reference
patchEdgeFaceRegions Class Reference
Transport of regions for use in PatchEdgeFaceWave.
#include <patchEdgeFaceRegions.H>
Public Member Functions
patchEdgeFaceRegions ()
patchEdgeFaceRegions (const labelList &regions)
patchEdgeFaceRegions (const labelPair &regions)
const labelList & regions () const
labelList & regions ()
template<class TrackingData >
bool valid (TrackingData &td) const
template<class Patch , class TrackingData >
void transform (const polyMesh &mesh, const Patch &patch, const tensor &rotTensor, const scalar tol, TrackingData &td)
template<class Patch , class TrackingData >
bool updateEdge (const polyMesh &mesh, const Patch &patch, const label edgeI, const label facei, const patchEdgeFaceRegions &faceInfo, const scalar tol, TrackingData &td)
template<class Patch , class TrackingData >
bool updateEdge (const polyMesh &mesh, const Patch &patch, const patchEdgeFaceRegions &edgeInfo, const bool sameOrientation, const scalar tol, TrackingData &td)
template<class Patch , class TrackingData >
bool updateFace (const polyMesh &mesh, const Patch &patch, const label facei, const label edgeI, const patchEdgeFaceRegions &edgeInfo, const scalar tol, TrackingData &td)
template<class TrackingData >
bool equal (const patchEdgeFaceRegions &, TrackingData &) const
bool operator== (const patchEdgeFaceRegions &) const
bool operator!= (const patchEdgeFaceRegions &) const
Friends
Ostream & operator<< (Ostream &, const patchEdgeFaceRegions &)
Istream & operator>> (Istream &, patchEdgeFaceRegions &)
Detailed Description
Transport of regions for use in PatchEdgeFaceWave.
Set element to -1 to denote blocked.
Source files
patchEdgeFaceRegions.H
patchEdgeFaceRegionsI.H
patchEdgeFaceRegions.C
Definition at line 59 of file patchEdgeFaceRegions.H.
Constructor & Destructor Documentation
patchEdgeFaceRegions() [1/3]
patchEdgeFaceRegions () inline
Definition at line 26 of file patchEdgeFaceRegionsI.H.
patchEdgeFaceRegions() [2/3]
patchEdgeFaceRegions (const labelList & regions) inline
Definition at line 30 of file patchEdgeFaceRegionsI.H.
patchEdgeFaceRegions() [3/3]
patchEdgeFaceRegions (const labelPair & regions) inline
Definition at line 39 of file patchEdgeFaceRegionsI.H.
References patchEdgeFaceRegions::regions().
Member Function Documentation
regions() [1/2]
const labelList & regions () const inline
Definition at line 84 of file patchEdgeFaceRegions.H.
Referenced by patchEdgeFaceRegions::patchEdgeFaceRegions().
regions() [2/2]
labelList & regions () inline
Definition at line 88 of file patchEdgeFaceRegions.H.
valid()
template<class TrackingData > bool valid (TrackingData & td) const inline
Definition at line 54 of file patchEdgeFaceRegionsI.H.
References Foam::labelMax, and UPtrList< T >::size().
transform()
template<class Patch , class TrackingData > void transform (const polyMesh & mesh, const Patch & patch, const tensor & rotTensor, const scalar tol, TrackingData & td) inline
Definition at line 61 of file patchEdgeFaceRegionsI.H.
updateEdge() [1/2]
template<class Patch , class TrackingData > bool updateEdge (const polyMesh & mesh, const Patch & patch, const label edgeI, const label facei, const patchEdgeFaceRegions & faceInfo, const scalar tol, TrackingData & td) inline
Definition at line 73 of file patchEdgeFaceRegionsI.H.
References Foam::abort(), e, f(), Foam::FatalError, FatalErrorInFunction, UList< T >::fcIndex(), forAll, Foam::labelMax, PtrList< T >::setSize(), and UPtrList< T >::size().
updateEdge() [2/2]
template<class Patch , class TrackingData > bool updateEdge (const polyMesh & mesh, const Patch & patch, const patchEdgeFaceRegions & edgeInfo, const bool sameOrientation, const scalar tol, TrackingData & td) inline
Definition at line 130 of file patchEdgeFaceRegionsI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::labelMax, PtrList< T >::setSize(), and UPtrList< T >::size().
updateFace()
template<class Patch , class TrackingData > bool updateFace (const polyMesh & mesh, const Patch & patch, const label facei, const label edgeI, const patchEdgeFaceRegions & edgeInfo, const scalar tol, TrackingData & td) inline
Definition at line 177 of file patchEdgeFaceRegionsI.H.
References Foam::abort(), e, f(), Foam::FatalError, FatalErrorInFunction, UList< T >::fcIndex(), Foam::labelMax, PtrList< T >::setSize(), and UList< T >::size().
equal()
template<class TrackingData > bool equal (const patchEdgeFaceRegions & rhs, TrackingData & td) const inline
Definition at line 242 of file patchEdgeFaceRegionsI.H.
References Foam::operator==().
operator==()
bool operator== (const patchEdgeFaceRegions & rhs) const inline
Definition at line 254 of file patchEdgeFaceRegionsI.H.
operator!=()
bool operator!= (const patchEdgeFaceRegions & rhs) const inline
Definition at line 263 of file patchEdgeFaceRegionsI.H.
Friends And Related Symbol Documentation
operator<<
Ostream & operator<< (Ostream & , const patchEdgeFaceRegions &) friend
operator>>
Istream & operator>> (Istream & , patchEdgeFaceRegions &) friend
The documentation for this class was generated from the following files:
src/meshTools/algorithms/PatchEdgeFaceWave/patchEdgeFaceRegions.H
src/meshTools/algorithms/PatchEdgeFaceWave/patchEdgeFaceRegionsI.H