OpenFOAM: combineFaces Class Reference
combineFaces Class Reference
Combines boundary faces into single face. The faces get the patch of the first face ('the master')
#include <combineFaces.H>
Public Member Functions
ClassName ("combineFaces")
combineFaces (const polyMesh &mesh, const bool undoable=false)
const labelList & masterFace () const
const labelList & savedPointLabels () const
labelListList getMergeSets (const scalar featureCos, const scalar minConcaveCos, const labelHashSet &boundaryCells, const bool mergeAcrossPatches=false) const
labelListList getMergeSets (const scalar featureCos, const scalar minConcaveCos, const bool mergeAcrossPatches=false) const
void setRefinement (const labelListList &, polyTopoChange &)
void updateMesh (const mapPolyMesh &)
void setUnrefinement (const labelList &masterFaces, polyTopoChange &meshMod, Map< label > &restoredPoints, Map< label > &restoredFaces, Map< label > &restoredCells)
Static Public Member Functions
static face getOutsideFace (const indirectPrimitivePatch &)
Detailed Description
Combines boundary faces into single face. The faces get the patch of the first face ('the master')
Source files
combineFaces.H
combineFaces.C
Definition at line 54 of file combineFaces.H.
Constructor & Destructor Documentation
combineFaces()
combineFaces (const polyMesh & mesh, const bool undoable = false) explicit
Definition at line 275 of file combineFaces.C.
Member Function Documentation
ClassName()
ClassName ("combineFaces")
masterFace()
const labelList & masterFace () const inline
Definition at line 138 of file combineFaces.H.
savedPointLabels()
const labelList & savedPointLabels () const inline
Definition at line 144 of file combineFaces.H.
getMergeSets() [1/2]
Foam::labelListList getMergeSets (const scalar featureCos, const scalar minConcaveCos, const labelHashSet & boundaryCells, const bool mergeAcrossPatches = false) const
Definition at line 292 of file combineFaces.C.
References PtrList< T >::append(), forAllConstIters, forAllIters, Foam::magSqr(), Foam::maxMagSqr(), PtrList< T >::setSize(), HashTable< T, Key, Hash >::size(), and UPtrList< T >::size().
getMergeSets() [2/2]
Foam::labelListList getMergeSets (const scalar featureCos, const scalar minConcaveCos, const bool mergeAcrossPatches = false) const
Definition at line 409 of file combineFaces.C.
References forAll, HashSet< Key, Hash >::insert(), and patches.
getOutsideFace()
Foam::face getOutsideFace (const indirectPrimitivePatch & fp) static
Definition at line 447 of file combineFaces.C.
References Foam::abort(), e, Foam::FatalError, FatalErrorInFunction, Foam::renumber(), Foam::reverse(), and UPtrList< T >::size().
setRefinement()
void setRefinement (const labelListList & faceSets, polyTopoChange & meshMod)
Definition at line 575 of file combineFaces.C.
References Foam::abort(), coupled(), f(), Foam::FatalError, FatalErrorInFunction, forAll, n, Foam::nl, patches, polyTopoChange::setAction(), PtrList< T >::setSize(), UPtrList< T >::size(), UList< T >::size(), syncTools::syncPointList(), and Foam::Zero.
updateMesh()
void updateMesh (const mapPolyMesh & map)
Definition at line 801 of file combineFaces.C.
References Foam::abort(), f(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::inplaceRenumber(), Foam::nl, mapPolyMesh::reverseFaceMap(), and mapPolyMesh::reversePointMap().
setUnrefinement()
void setUnrefinement (const labelList & masterFaces, polyTopoChange & meshMod, Map< label > & restoredPoints, Map< label > & restoredFaces, Map< label > & restoredCells)
Definition at line 849 of file combineFaces.C.
References Foam::abort(), PtrList< T >::clear(), UList< T >::empty(), Foam::exit(), f(), Foam::FatalError, FatalErrorInFunction, forAll, polyTopoChange::setAction(), and UList< T >::size().
The documentation for this class was generated from the following files:
src/dynamicMesh/polyTopoChange/polyTopoChange/combineFaces.H
src/dynamicMesh/polyTopoChange/polyTopoChange/combineFaces.C