OpenFOAM: shapeSensitivities Class Reference
shapeSensitivities Class Reference abstract
#include <shapeSensitivitiesIncompressible.H>
Public Member Functions
TypeName ("shapeSensitivities")
shapeSensitivities (const fvMesh &mesh, const dictionary &dict, incompressibleAdjointSolver &adjointSolver)
virtual ~shapeSensitivities ()=default
virtual void accumulateIntegrand (const scalar dt)=0
virtual void assembleSensitivities ()=0
virtual void clearSensitivities ()
virtual void write (const word &baseName=word::null)
Public Member Functions inherited from adjointSensitivity
TypeName ("adjointSensitivity")
declareRunTimeSelectionTable (autoPtr, adjointSensitivity, dictionary,(const fvMesh &mesh, const dictionary &dict, incompressibleAdjointSolver &adjointSolver),(mesh, dict, adjointSolver))
adjointSensitivity (const fvMesh &mesh, const dictionary &dict, incompressibleAdjointSolver &adjointSolver)
virtual ~adjointSensitivity ()=default
const incompressibleVars & primalVars () const
const incompressibleAdjointVars & adjointVars () const
const incompressibleAdjointSolver & adjointSolver () const
virtual const scalarField & calculateSensitivities ()
const scalarField & getSensitivities () const
tmp< volTensorField > computeGradDxDbMultiplier ()
tmp< volVectorField > adjointMeshMovementSource ()
Public Member Functions inherited from sensitivity
TypeName ("sensitivity")
sensitivity (const fvMesh &mesh, const dictionary &dict)
virtual ~sensitivity ()=default
const dictionary & dict () const
virtual bool readDict (const dictionary &dict)
virtual void computeDerivativesSize ()
Protected Member Functions
virtual void accumulateDirectSensitivityIntegrand (const scalar dt)
virtual void accumulateBCSensitivityIntegrand (const scalar dt)
tmp< boundaryVectorField > dvdbMult () const
Protected Attributes
autoPtr< boundaryVectorField > dSfdbMult_
autoPtr< boundaryVectorField > dnfdbMult_
autoPtr< boundaryVectorField > dxdbDirectMult_
autoPtr< boundaryVectorField > bcDxDbMult_
Protected Attributes inherited from adjointSensitivity
scalarField derivatives_
incompressibleAdjointSolver & adjointSolver_
const incompressibleVars & primalVars_
incompressibleAdjointVars & adjointVars_
objectiveManager & objectiveManager_
Protected Attributes inherited from sensitivity
const fvMesh & mesh_
dictionary dict_
autoPtr< volScalarField > fieldSensPtr_
Additional Inherited Members
Static Public Member Functions inherited from adjointSensitivity
static autoPtr< adjointSensitivity > New (const fvMesh &mesh, const dictionary &dict, incompressibleAdjointSolver &adjointSolver)
Detailed Description
Definition at line 51 of file shapeSensitivitiesIncompressible.H.
Constructor & Destructor Documentation
shapeSensitivities()
shapeSensitivities (const fvMesh & mesh, const dictionary & dict, incompressibleAdjointSolver & adjointSolver)
Definition at line 127 of file shapeSensitivitiesIncompressible.C.
~shapeSensitivities()
virtual ~shapeSensitivities () virtual default
Member Function Documentation
accumulateDirectSensitivityIntegrand()
void accumulateDirectSensitivityIntegrand (const scalar dt) protected virtual
Definition at line 40 of file shapeSensitivitiesIncompressible.C.
References shapeSensitivities::dnfdbMult_, shapeSensitivities::dSfdbMult_, shapeSensitivities::dxdbDirectMult_, objectiveManager::getObjectiveFunctions(), sensitivity::mesh_, and adjointSensitivity::objectiveManager_.
Referenced by FIBase::accumulateIntegrand(), and SIBase::accumulateIntegrand().
accumulateBCSensitivityIntegrand()
void accumulateBCSensitivityIntegrand (const scalar dt) protected virtual
Definition at line 59 of file shapeSensitivitiesIncompressible.C.
References adjointSensitivity::adjointVars_, shapeSensitivities::bcDxDbMult_, shapeSensitivities::dvdbMult(), sensitivity::mesh_, and incompressibleAdjointMeanFlowVars::Ua().
Referenced by FIBase::accumulateIntegrand(), and SIBase::accumulateIntegrand().
dvdbMult()
tmp< boundaryVectorField > dvdbMult () const protected
Definition at line 83 of file shapeSensitivitiesIncompressible.C.
References incompressibleAdjointVars::adjointTurbulence(), adjointSensitivity::adjointVars_, GeometricField< Type, PatchField, GeoMesh >::boundaryField(), Foam::fvc::grad(), incompressibleAdjointMeanFlowVars::pa(), adjointSensitivity::primalVars_, and incompressibleAdjointMeanFlowVars::Ua().
Referenced by shapeSensitivities::accumulateBCSensitivityIntegrand().
TypeName()
TypeName ("shapeSensitivities")
accumulateIntegrand()
virtual void accumulateIntegrand (const scalar dt) pure virtual
Implements adjointSensitivity.
Implemented in FIBase, and SIBase.
assembleSensitivities()
virtual void assembleSensitivities () pure virtual
Implements adjointSensitivity.
Implemented in sensitivityBezier, sensitivityBezierFI, sensitivityVolBSplines, sensitivityVolBSplinesFI, FIBase, and SIBase.
clearSensitivities()
void clearSensitivities () virtual
Reimplemented from adjointSensitivity.
Reimplemented in FIBase, sensitivityBezier, sensitivityBezierFI, sensitivityVolBSplines, sensitivityVolBSplinesFI, and SIBase.
Definition at line 145 of file shapeSensitivitiesIncompressible.C.
References shapeSensitivities::bcDxDbMult_, adjointSensitivity::clearSensitivities(), shapeSensitivitiesBase::clearSensitivities(), shapeSensitivities::dnfdbMult_, shapeSensitivities::dSfdbMult_, shapeSensitivities::dxdbDirectMult_, and VectorSpace< Form, Cmpt, Ncmpts >::zero.
Referenced by FIBase::clearSensitivities(), and SIBase::clearSensitivities().
write()
void write (const word & baseName = word::null) virtual
Reimplemented from adjointSensitivity.
Reimplemented in sensitivityBezier, sensitivityBezierFI, sensitivityVolBSplines, sensitivityVolBSplinesFI, and SIBase.
Definition at line 157 of file shapeSensitivitiesIncompressible.C.
References shapeSensitivitiesBase::write(), and adjointSensitivity::write().
Referenced by SIBase::write().
Member Data Documentation
dSfdbMult_
autoPtr<boundaryVectorField> dSfdbMult_ protected
Definition at line 61 of file shapeSensitivitiesIncompressible.H.
Referenced by shapeSensitivities::accumulateDirectSensitivityIntegrand(), sensitivityBezier::assembleSensitivities(), sensitivityBezierFI::assembleSensitivities(), sensitivityVolBSplinesFI::assembleSensitivities(), shapeSensitivities::clearSensitivities(), and sensitivityVolBSplines::computeObjectiveContributions().
dnfdbMult_
autoPtr<boundaryVectorField> dnfdbMult_ protected
Definition at line 62 of file shapeSensitivitiesIncompressible.H.
Referenced by shapeSensitivities::accumulateDirectSensitivityIntegrand(), sensitivityBezier::assembleSensitivities(), sensitivityBezierFI::assembleSensitivities(), sensitivityVolBSplinesFI::assembleSensitivities(), shapeSensitivities::clearSensitivities(), and sensitivityVolBSplines::computeObjectiveContributions().
dxdbDirectMult_
autoPtr<boundaryVectorField> dxdbDirectMult_ protected
Definition at line 63 of file shapeSensitivitiesIncompressible.H.
Referenced by shapeSensitivities::accumulateDirectSensitivityIntegrand(), sensitivityBezier::assembleSensitivities(), sensitivityBezierFI::assembleSensitivities(), sensitivityVolBSplinesFI::assembleSensitivities(), shapeSensitivities::clearSensitivities(), and sensitivityVolBSplines::computeObjectiveContributions().
bcDxDbMult_
autoPtr<boundaryVectorField> bcDxDbMult_ protected
Definition at line 64 of file shapeSensitivitiesIncompressible.H.
Referenced by shapeSensitivities::accumulateBCSensitivityIntegrand(), sensitivityBezier::assembleSensitivities(), sensitivityBezierFI::assembleSensitivities(), sensitivityVolBSplinesFI::assembleSensitivities(), shapeSensitivities::clearSensitivities(), and sensitivityVolBSplines::computeBCContributions().
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/optimisation/adjointSensitivity/incompressible/shapeSensitivities/shapeSensitivitiesIncompressible.H
src/optimisation/adjointOptimisation/adjoint/optimisation/adjointSensitivity/incompressible/shapeSensitivities/shapeSensitivitiesIncompressible.C