OpenFOAM: LaakkonenAlopaeusAittamaa Class Reference
LaakkonenAlopaeusAittamaa Class Reference
Model of Laakkonen et al. (2006). The total breakup rate is calculated by.
#include <LaakkonenAlopaeusAittamaa.H>
Public Member Functions
TypeName ("LaakkonenAlopaeusAittamaa")
LaakkonenAlopaeusAittamaa (const populationBalanceModel &popBal, const dictionary &dict)
virtual ~LaakkonenAlopaeusAittamaa ()=default
virtual void setBreakupRate (volScalarField &breakupRate, const label i)
Public Member Functions inherited from breakupModel
TypeName ("breakupModel")
declareRunTimeSelectionTable (autoPtr, breakupModel, dictionary,(const populationBalanceModel &popBal, const dictionary &dict),(popBal, dict))
breakupModel (const populationBalanceModel &popBal, const dictionary &dict)
autoPtr< breakupModel > clone () const
virtual ~breakupModel ()=default
const populationBalanceModel & popBal () const
const autoPtr< daughterSizeDistributionModel > & dsdPtr () const
autoPtr< daughterSizeDistributionModel > & dsdPtr ()
virtual void correct ()
Additional Inherited Members
Static Public Member Functions inherited from breakupModel
static autoPtr< breakupModel > New (const word &modelType, const populationBalanceModel &popBal, const dictionary &dict)
Protected Attributes inherited from breakupModel
const populationBalanceModel & popBal_
dictionary dict_
autoPtr< daughterSizeDistributionModel > dsd_
Detailed Description
Model of Laakkonen et al. (2006). The total breakup rate is calculated by.
where
= Surface tension [N/m]
= Volume of mother bubble i [m]
= Turbulent dissipation rate of continuous phase [m2/s3]
= Molecular dynamic viscosity of liquid phase [Pa s]
= Density of continuous phase [kg/m3]
= Density of disperse phase [kg/m3]
References:
        Laakkonen, M., Alopaeus, V., & Aittamaa, J. (2006).
        Validation of bubble breakage, coalescence and mass transfer models for
        gas-liquid dispersion in agitated vessel.
        Chemical engineering science, 61(1), 218-228.
        Eq. 2-3, p. 220.
Usage
Property Description Required Default value
C1 coefficient C1 no 6.0
C2 coefficient C2 no 0.04
C3 coefficient C3 no 0.01
daughterSizeDistributionModel inh. from breakupModel inherited
Source files
LaakkonenAlopaeusAittamaa.H
LaakkonenAlopaeusAittamaa.C
Definition at line 141 of file LaakkonenAlopaeusAittamaa.H.
Constructor & Destructor Documentation
LaakkonenAlopaeusAittamaa()
LaakkonenAlopaeusAittamaa (const populationBalanceModel & popBal, const dictionary & dict)
Definition at line 48 of file LaakkonenAlopaeusAittamaa.C.
References Foam::dimless.
~LaakkonenAlopaeusAittamaa()
virtual ~LaakkonenAlopaeusAittamaa () virtual default
Member Function Documentation
TypeName()
TypeName ("LaakkonenAlopaeusAittamaa")
setBreakupRate()
void setBreakupRate (volScalarField & breakupRate, const label i) virtual
Implements breakupModel.
Definition at line 74 of file LaakkonenAlopaeusAittamaa.C.
References Foam::cbrt(), Foam::erfc(), phaseModel::mu(), Foam::pow(), phaseModel::rho(), and Foam::sqrt().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/populationBalanceModel/breakupModels/LaakkonenAlopaeusAittamaa/LaakkonenAlopaeusAittamaa.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/populationBalanceModel/breakupModels/LaakkonenAlopaeusAittamaa/LaakkonenAlopaeusAittamaa.C