OpenFOAM: twoDPointCorrector Class Reference
twoDPointCorrector Class Reference
Class applies a two-dimensional correction to mesh motion point field.
#include <twoDPointCorrector.H>
Public Member Functions
ClassName ("twoDPointCorrector")
twoDPointCorrector (const polyMesh &mesh)
~twoDPointCorrector ()
bool required () const
const vector & planeNormal () const
const labelList & normalEdgeIndices () const
direction normalDir () const
void correctPoints (pointField &p) const
void correctDisplacement (const pointField &p, vectorField &disp) const
void updateMesh (const mapPolyMesh &)
bool movePoints ()
Public Member Functions inherited from MeshObject< polyMesh, UpdateableMeshObject, twoDPointCorrector >
MeshObject (const polyMesh &mesh)
MeshObject (const word &objName, const polyMesh &mesh)
virtual ~MeshObject ()=default
const polyMesh & mesh () const noexcept
virtual bool writeData (Ostream &os) const
Additional Inherited Members
Static Public Member Functions inherited from MeshObject< polyMesh, UpdateableMeshObject, twoDPointCorrector >
static const twoDPointCorrector & New (const polyMesh &mesh, Args &&... args)
static const twoDPointCorrector & New (const word &objName, const polyMesh &mesh, Args &&... args)
static bool Delete (const word &objName, const polyMesh &mesh)
static bool Delete (const polyMesh &mesh)
Protected Attributes inherited from MeshObject< polyMesh, UpdateableMeshObject, twoDPointCorrector >
const polyMesh & mesh_
Detailed Description
Class applies a two-dimensional correction to mesh motion point field.
The correction guarantees that the mesh does not get twisted during motion and thus introduce a third dimension into a 2-D problem.
The operation is performed by looping through all edges approximately normal to the plane and enforcing their orthogonality onto the plane by adjusting points on their ends.
Source files
twoDPointCorrector.H
twoDPointCorrector.C
Definition at line 59 of file twoDPointCorrector.H.
Constructor & Destructor Documentation
twoDPointCorrector()
twoDPointCorrector (const polyMesh & mesh)
Definition at line 193 of file twoDPointCorrector.C.
~twoDPointCorrector()
~twoDPointCorrector ()
Definition at line 208 of file twoDPointCorrector.C.
Member Function Documentation
ClassName()
ClassName ("twoDPointCorrector")
required()
bool required () const inline
Definition at line 128 of file twoDPointCorrector.H.
planeNormal()
const Foam::vector & planeNormal () const
Definition at line 242 of file twoDPointCorrector.C.
normalEdgeIndices()
const Foam::labelList & normalEdgeIndices () const
Definition at line 253 of file twoDPointCorrector.C.
normalDir()
Foam::direction normalDir () const
Definition at line 216 of file twoDPointCorrector.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, Foam::mag(), Foam::nl, Vector< scalar >::X, Vector< scalar >::Y, and Vector< scalar >::Z.
correctPoints()
void correctPoints (pointField & p) const
Definition at line 264 of file twoDPointCorrector.C.
References A, Foam::meshTools::constrainToMeshCentre(), and p.
correctDisplacement()
void correctDisplacement (const pointField & p, vectorField & disp) const
Definition at line 304 of file twoDPointCorrector.C.
References A, Foam::meshTools::constrainToMeshCentre(), e, UList< T >::end(), and p.
updateMesh()
void updateMesh (const mapPolyMesh &)
Definition at line 354 of file twoDPointCorrector.C.
movePoints()
bool movePoints ()
Definition at line 360 of file twoDPointCorrector.C.
The documentation for this class was generated from the following files:
src/meshTools/twoDPointCorrector/twoDPointCorrector.H
src/meshTools/twoDPointCorrector/twoDPointCorrector.C