OpenFOAM: edgeInterpolation Class Reference
edgeInterpolation Class Reference
Face to edge interpolation scheme. Included in faMesh.
#include <edgeInterpolation.H>
Public Member Functions
ClassName ("edgeInterpolation")
edgeInterpolation (const faMesh &)
~edgeInterpolation ()
const faMesh & mesh () const noexcept
const edgeScalarField & lPN () const
const edgeScalarField & weights () const
const edgeScalarField & deltaCoeffs () const
const edgeVectorField & correctionVectors () const
const edgeVectorField & skewCorrectionVectors () const
bool orthogonal () const
bool skew () const
bool movePoints () const
bool hasWeights () const noexcept
Protected Member Functions
void clearOut ()
Detailed Description
Face to edge interpolation scheme. Included in faMesh.
Author Zeljko Tukovic, FMENA Hrvoje Jasak, Wikki Ltd.
Source files
edgeInterpolation.H
edgeInterpolation.C
Definition at line 58 of file edgeInterpolation.H.
Constructor & Destructor Documentation
edgeInterpolation()
edgeInterpolation (const faMesh & fam) explicit
Definition at line 49 of file edgeInterpolation.C.
~edgeInterpolation()
~edgeInterpolation ()
Definition at line 64 of file edgeInterpolation.C.
Member Function Documentation
clearOut()
void clearOut () protected
Definition at line 37 of file edgeInterpolation.C.
References Foam::deleteDemandDrivenData().
ClassName()
ClassName ("edgeInterpolation")
mesh()
const faMesh & mesh () const inline noexcept
Definition at line 140 of file edgeInterpolation.H.
lPN()
const Foam::edgeScalarField & lPN () const
Definition at line 72 of file edgeInterpolation.C.
weights()
const Foam::edgeScalarField & weights () const
Definition at line 83 of file edgeInterpolation.C.
deltaCoeffs()
const Foam::edgeScalarField & deltaCoeffs () const
Definition at line 94 of file edgeInterpolation.C.
Referenced by liquidFilmBase::CourantNumber().
correctionVectors()
const Foam::edgeVectorField & correctionVectors () const
Definition at line 116 of file edgeInterpolation.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
skewCorrectionVectors()
const Foam::edgeVectorField & skewCorrectionVectors () const
Definition at line 141 of file edgeInterpolation.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and Foam::skew().
orthogonal()
bool orthogonal () const
Definition at line 105 of file edgeInterpolation.C.
skew()
bool skew () const
Definition at line 129 of file edgeInterpolation.C.
movePoints()
bool movePoints () const
Definition at line 154 of file edgeInterpolation.C.
References Foam::deleteDemandDrivenData().
Referenced by faMesh::movePoints(), and faMesh::updateMesh().
hasWeights()
bool hasWeights () const inline noexcept
Definition at line 176 of file edgeInterpolation.H.
The documentation for this class was generated from the following files:
src/finiteArea/interpolation/edgeInterpolation/edgeInterpolation.H
src/finiteArea/interpolation/edgeInterpolation/edgeInterpolation.C