OpenFOAM: prghPressureFvPatchScalarField Class Reference
prghPressureFvPatchScalarField Class Reference
Boundary conditions » Generic
This boundary condition provides static pressure condition for p_rgh, calculated as:
#include <prghPressureFvPatchScalarField.H>
Public Member Functions
TypeName ("prghPressure")
prghPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
prghPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
prghPressureFvPatchScalarField (const prghPressureFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
prghPressureFvPatchScalarField (const prghPressureFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
prghPressureFvPatchScalarField (const prghPressureFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
const scalarField & p () const
scalarField & p ()
virtual void autoMap (const fvPatchFieldMapper &)
virtual void rmap (const fvPatchScalarField &, const labelList &)
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Protected Attributes
word rhoName_
scalarField p_
Detailed Description
This boundary condition provides static pressure condition for p_rgh, calculated as:
where
= Pseudo hydrostatic pressure [Pa]
= Static pressure [Pa]
= Height in the opposite direction to gravity
= Reference height in the opposite direction to gravity
= density
= acceleration due to gravity [m/s^2]
Usage
Property Description Required Default value
rho rho field name no rho
p static pressure yes
Example of the boundary condition specification:
    <patchName>
    {
        type            prghPressure;
        rho             rho;
        p               uniform 0;
        value           uniform 0; // optional initial value
    }
See also
Foam::fixedValueFvPatchScalarField
Source files
prghPressureFvPatchScalarField.H
prghPressureFvPatchScalarField.C
Definition at line 124 of file prghPressureFvPatchScalarField.H.
Constructor & Destructor Documentation
prghPressureFvPatchScalarField() [1/5]
prghPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 30 of file prghPressureFvPatchScalarField.C.
prghPressureFvPatchScalarField() [2/5]
prghPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 43 of file prghPressureFvPatchScalarField.C.
References dict, fvPatchField< Type >::operator=(), and prghPressureFvPatchScalarField::p_.
prghPressureFvPatchScalarField() [3/5]
prghPressureFvPatchScalarField (const prghPressureFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 62 of file prghPressureFvPatchScalarField.C.
prghPressureFvPatchScalarField() [4/5]
prghPressureFvPatchScalarField (const prghPressureFvPatchScalarField & ptf)
Definition at line 77 of file prghPressureFvPatchScalarField.C.
prghPressureFvPatchScalarField() [5/5]
prghPressureFvPatchScalarField (const prghPressureFvPatchScalarField & ptf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 89 of file prghPressureFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("prghPressure")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 180 of file prghPressureFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 196 of file prghPressureFvPatchScalarField.H.
p() [1/2]
const scalarField & p () const inline
Definition at line 213 of file prghPressureFvPatchScalarField.H.
References prghPressureFvPatchScalarField::p_.
p() [2/2]
scalarField & p () inline
Definition at line 219 of file prghPressureFvPatchScalarField.H.
References prghPressureFvPatchScalarField::p_.
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Definition at line 104 of file prghPressureFvPatchScalarField.C.
rmap()
void rmap (const fvPatchScalarField & ptf, const labelList & addr) virtual
Definition at line 114 of file prghPressureFvPatchScalarField.C.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 129 of file prghPressureFvPatchScalarField.C.
References Foam::cmptMag(), Foam::dimLength, g, Foam::mag(), gravity::New(), and Foam::operator==().
write()
void write (Ostream & os) const virtual
Definition at line 158 of file prghPressureFvPatchScalarField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntryIfDifferent(), and fvPatchField< Type >::writeValueEntry().
Member Data Documentation
rhoName_
word rhoName_ protected
Definition at line 134 of file prghPressureFvPatchScalarField.H.
p_
scalarField p_ protected
Definition at line 137 of file prghPressureFvPatchScalarField.H.
Referenced by prghPressureFvPatchScalarField::p(), prghPressureFvPatchScalarField::p(), and prghPressureFvPatchScalarField::prghPressureFvPatchScalarField().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/prghPressure/prghPressureFvPatchScalarField.H
src/finiteVolume/fields/fvPatchFields/derived/prghPressure/prghPressureFvPatchScalarField.C