OpenFOAM: ParticleHistogram< CloudType > Class Template Reference
ParticleHistogram< CloudType > Class Template Reference
Computes a histogram for the distribution of particle diameters and corresponding number of particles hitting on a given list of patches or face zones.
#include <ParticleHistogram.H>
Public Member Functions
TypeName ("particleHistogram")
ParticleHistogram (const dictionary &dict, CloudType &owner, const word &modelName)
ParticleHistogram (const ParticleHistogram< CloudType > &ph)
void operator= (const ParticleHistogram< CloudType > &)=delete
virtual autoPtr< CloudFunctionObject< CloudType > > clone () const
virtual ~ParticleHistogram ()=default
virtual void postPatch (const parcelType &p, const polyPatch &pp, bool &keepParticle)
virtual void postFace (const parcelType &p, bool &keepParticle)
virtual void write ()
Public Member Functions inherited from CloudFunctionObject< CloudType >
TypeName ("cloudFunctionObject")
declareRunTimeSelectionTable (autoPtr, CloudFunctionObject, dictionary,(const dictionary &dict, CloudType &owner, const word &modelName),(dict, owner, modelName))
CloudFunctionObject (CloudType &owner)
CloudFunctionObject (const dictionary &dict, CloudType &owner, const word &objectType, const word &modelName)
CloudFunctionObject (const CloudFunctionObject< CloudType > &ppm)
virtual ~CloudFunctionObject ()=default
virtual void preEvolve (const typename parcelType::trackingData &td)
virtual void postEvolve (const typename parcelType::trackingData &td)
virtual void postMove (parcelType &p, const scalar dt, const point &position0, bool &keepParticle)
const fileName & outputDir () const
fileName writeTimeDir () const
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
virtual ~CloudSubModelBase ()=default
const CloudType & owner () const
virtual bool writeTime () const
virtual fileName localPath () const
CloudType & owner ()
virtual void info ()
virtual void write (Ostream &os) const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
subModelBase (const subModelBase &smb)
virtual ~subModelBase ()=default
const word & modelName () const
const dictionary & dict () const
const word & baseName () const
const word & modelType () const
const dictionary & coeffDict () const
const dictionary & properties () const
virtual bool defaultCoeffs (const bool printMsg) const
virtual bool active () const
virtual void cacheFields (const bool store)
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
bool getModelDict (const word &entryName, dictionary &dict) const
template<class Type >
bool getModelProperty (const word &entryName, Type &value) const
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Public Member Functions inherited from writeFile
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name="undefined", const bool writeToFile=true)
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name, const dictionary &dict, const bool writeToFile=true)
writeFile (const writeFile &wf)
virtual ~writeFile ()=default
virtual bool read (const dictionary &dict)
virtual OFstream & file ()
virtual bool writeToFile () const
virtual bool canWriteToFile () const
virtual bool canResetFile () const
virtual bool canWriteHeader () const
virtual label charWidth () const
virtual void writeCommented (Ostream &os, const string &str) const
virtual void writeTabbed (Ostream &os, const string &str) const
virtual void writeHeader (Ostream &os, const string &str) const
virtual void writeCurrentTime (Ostream &os) const
virtual void writeBreak (Ostream &os) const
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
template<class Type >
void writeValue (Ostream &os, const Type &val) const
Additional Inherited Members
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Static Public Member Functions inherited from CloudFunctionObject< CloudType >
static autoPtr< CloudFunctionObject< CloudType > > New (const dictionary &dict, CloudType &owner, const word &objectType, const word &modelName)
Public Attributes inherited from subModelBase
bool log
Static Public Attributes inherited from writeFile
static label addChars = 8
Protected Member Functions inherited from subModelBase
bool inLine () const
Protected Member Functions inherited from writeFile
void initStream (Ostream &os) const
fileName baseFileDir () const
fileName baseTimeDir () const
fileName filePath (const fileName &fName) const
virtual autoPtr< OFstream > newFile (const fileName &fName) const
virtual autoPtr< OFstream > newFileAtTime (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > newFileAtStartTime (const word &name) const
virtual void resetFile (const word &name)
Omanip< int > valueWidth (const label offset=0) const
void operator= (const writeFile &)=delete
virtual autoPtr< OFstream > createFile (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > createFile (const word &name) const
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Protected Attributes inherited from subModelBase
const word modelName_
dictionary & properties_
const dictionary dict_
const word baseName_
const word modelType_
const dictionary coeffDict_
Protected Attributes inherited from writeFile
const objectRegistry & fileObr_
const fileName prefix_
word fileName_
autoPtr< OFstream > filePtr_
label writePrecision_
bool writeToFile_
bool updateHeader_
bool writtenHeader_
bool useUserTime_
scalar startTime_
Detailed Description
template<class CloudType>
class Foam::ParticleHistogram< CloudType >
Computes a histogram for the distribution of particle diameters and corresponding number of particles hitting on a given list of patches or face zones.
Operands:
Operand Type Location
input - -
output file dat <case>/postProcessing/<FO>/<time>/<file>
output field - -
The output file contains four columns, from the first to the last:
= Left bin-edge of particle diameter
= Right bin-edge of particle diameter
= Number of particles falling into the corresponding bin
= Cumulative number of binned particles
Usage
Minimal example by using constant/reactingCloud1Properties.cloudFunctions:
particleHistogram1
{
    // Mandatory entries
    type                 particleHistogram;
    nBins                <label>;
    min                  <scalar>;
    max                  <scalar>;
    maxStoredParcels     <scalar>;
    // Conditional entries
        // Option-1
        patches          (<wordRes>);
        // Option-2
        faceZones        (<wordRes>);
    // Inherited entries
    ...
}
where the entries mean:
Property Description Type Reqd Deflt
type Type name: particleHistogram word yes -
nBins Number of histogram bins label yes -
max Maximum value of histogram data scalar yes -
min Minimum value of histogram data scalar yes -
maxStoredParcels Maximum number of parcels to process label yes -
patches Names of operand patches wordRes choice -
faceZones Names of operand face zones wordRes choice -
The inherited entries are elaborated in:
CloudFunctionObject.H
writeFile.H
Note
The underlying type of maxStoredParcels is set as a scalar for I/O.
Source files
ParticleHistogram.H
ParticleHistogram.C
Definition at line 193 of file ParticleHistogram.H.
Constructor & Destructor Documentation
ParticleHistogram() [1/2]
template<class CloudType > ParticleHistogram (const dictionary & dict, CloudType & owner, const word & modelName)
Definition at line 47 of file ParticleHistogram.C.
References subModelBase::coeffDict(), delta, Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, PtrList< T >::resize(), collector::size(), and Foam::Zero.
ParticleHistogram() [2/2]
template<class CloudType > ParticleHistogram (const ParticleHistogram< CloudType > & ph)
Definition at line 111 of file ParticleHistogram.C.
~ParticleHistogram()
template<class CloudType > virtual ~ParticleHistogram () virtual default
Member Function Documentation
TypeName()
template<class CloudType > TypeName ("particleHistogram")
operator=()
template<class CloudType > void operator= (const ParticleHistogram< CloudType > &) delete
clone()
template<class CloudType > virtual autoPtr< CloudFunctionObject< CloudType > > clone () const inline virtual
Reimplemented from CloudFunctionObject< CloudType >.
Definition at line 260 of file ParticleHistogram.H.
postPatch()
template<class CloudType > void postPatch (const parcelType & p, const polyPatch & pp, bool & keepParticle) virtual
Reimplemented from CloudFunctionObject< CloudType >.
Definition at line 132 of file ParticleHistogram.C.
References PtrList< T >::append(), p, and pp().
postFace()
template<class CloudType > void postFace (const parcelType & p, bool & keepParticle) virtual
Reimplemented from CloudFunctionObject< CloudType >.
Definition at line 160 of file ParticleHistogram.C.
References PtrList< T >::append(), forAll, and p.
write()
template<class CloudType > void write () virtual
Reimplemented from CloudFunctionObject< CloudType >.
Definition at line 200 of file ParticleHistogram.C.
References delta, forAll, Pstream::gatherList(), UPstream::master(), UPstream::myProcNo(), Foam::nl, UPstream::nProcs(), os(), Foam::tab, and Foam::Zero.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/CloudFunctionObjects/ParticleHistogram/ParticleHistogram.H
src/lagrangian/intermediate/submodels/CloudFunctionObjects/ParticleHistogram/ParticleHistogram.C