OpenFOAM: SRIFallOffFunction Class Reference
SRIFallOffFunction Class Reference
The SRI fall-off function.
#include <SRIFallOffFunction.H>
Public Member Functions
SRIFallOffFunction (const scalar a, const scalar b, const scalar c, const scalar d, const scalar e)
SRIFallOffFunction (const dictionary &dict)
scalar operator() (const scalar T, const scalar Pr) const
void write (Ostream &os) const
Static Public Member Functions
static word type ()
Friends
Ostream & operator<< (Ostream &, const SRIFallOffFunction &)
Detailed Description
The SRI fall-off function.
Source files
SRIFallOffFunction.H
SRIFallOffFunctionI.H
Definition at line 52 of file SRIFallOffFunction.H.
Constructor & Destructor Documentation
SRIFallOffFunction() [1/2]
SRIFallOffFunction (const scalar a, const scalar b, const scalar c, const scalar d, const scalar e) inline
Definition at line 23 of file SRIFallOffFunctionI.H.
SRIFallOffFunction() [2/2]
SRIFallOffFunction (const dictionary & dict) inline
Definition at line 40 of file SRIFallOffFunctionI.H.
Member Function Documentation
type()
static word type () inline static
Definition at line 80 of file SRIFallOffFunction.H.
operator()()
Foam::scalar operator() (const scalar T, const scalar Pr) const inline
Definition at line 52 of file SRIFallOffFunctionI.H.
References Foam::exp(), Foam::log10(), Foam::max(), Foam::pow(), Pr(), Foam::sqr(), and T.
write()
void write (Ostream & os) const inline
Definition at line 63 of file SRIFallOffFunctionI.H.
References os(), and Ostream::writeEntry().
Friends And Related Symbol Documentation
operator<<
Ostream & operator<< (Ostream & , const SRIFallOffFunction &) friend
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/reaction/reactionRate/fallOffFunctions/SRIFallOffFunction/SRIFallOffFunction.H
src/thermophysicalModels/specie/reaction/reactionRate/fallOffFunctions/SRIFallOffFunction/SRIFallOffFunctionI.H