OpenFOAM: refinementFeatures Class Reference
refinementFeatures Class Reference
Encapsulates queries for features.
#include <refinementFeatures.H>
Public Member Functions
refinementFeatures (const objectRegistry &io, const PtrList< dictionary > &featDicts, const bool dryRun=false)
const labelListList & levels () const
const List< scalarField > & distances () const
scalar maxDistance () const
void findNearestEdge (const pointField &samples, const scalarField &nearestDistSqr, labelList &nearFeature, List< pointIndexHit > &nearInfo, vectorField &nearNormal) const
void findNearestRegionEdge (const pointField &samples, const scalarField &nearestDistSqr, labelList &nearFeature, List< pointIndexHit > &nearInfo, vectorField &nearNormal) const
void findNearestPoint (const pointField &samples, const scalarField &nearestDistSqr, labelList &nearFeature, List< pointIndexHit > &nearInfo) const
void findHigherLevel (const pointField &pt, const labelList &ptLevel, labelList &maxLevel) const
bool checkSizes (const scalar maxRatio, const boundBox &meshBb, const bool report, Ostream &os) const
Public Member Functions inherited from PtrList< extendedFeatureEdgeMesh >
constexpr PtrList () noexcept
PtrList (const label len)
PtrList (const PtrList< extendedFeatureEdgeMesh > &list)
PtrList (PtrList< extendedFeatureEdgeMesh > &&list)
PtrList (UList< extendedFeatureEdgeMesh * > &list)
PtrList (const PtrList< extendedFeatureEdgeMesh > &list, const CloneArg &cloneArgs)
PtrList (PtrList< extendedFeatureEdgeMesh > &list, bool reuse)
PtrList (const SLPtrList< extendedFeatureEdgeMesh > &list)
PtrList (Istream &is, const INew &inew)
PtrList (Istream &is)
~PtrList ()
PtrList< extendedFeatureEdgeMesh > clone (Args &&... args) const
Foam::PtrList< extendedFeatureEdgeMesh > clone (Args &&... args) const
const extendedFeatureEdgeMesh * set (const label i) const
autoPtr< extendedFeatureEdgeMesh > set (const label i, extendedFeatureEdgeMesh *ptr)
autoPtr< extendedFeatureEdgeMesh > set (const label i, std::unique_ptr< extendedFeatureEdgeMesh > &&ptr)
autoPtr< extendedFeatureEdgeMesh > set (const label i, autoPtr< extendedFeatureEdgeMesh > &&ptr)
autoPtr< extendedFeatureEdgeMesh > set (const label i, const refPtr< extendedFeatureEdgeMesh > &ptr)
autoPtr< extendedFeatureEdgeMesh > set (const label i, const tmp< extendedFeatureEdgeMesh > &ptr)
autoPtr< extendedFeatureEdgeMesh > set (const label i, autoPtr< extendedFeatureEdgeMesh > &ptr)
void clear ()
void free ()
void resize (const label newLen)
extendedFeatureEdgeMesh & emplace_back (Args &&... args)
void push_back (extendedFeatureEdgeMesh *ptr)
void push_back (std::unique_ptr< extendedFeatureEdgeMesh > &&ptr)
void push_back (autoPtr< extendedFeatureEdgeMesh > &&ptr)
void push_back (const refPtr< extendedFeatureEdgeMesh > &ptr)
void push_back (const tmp< extendedFeatureEdgeMesh > &ptr)
void push_back (PtrList< extendedFeatureEdgeMesh > &&other)
void push_back (autoPtr< extendedFeatureEdgeMesh > &ptr)=delete
extendedFeatureEdgeMesh & emplace_set (const label i, Args &&... args)
extendedFeatureEdgeMesh & emplace (const label i, Args &&... args)
autoPtr< extendedFeatureEdgeMesh > release (const label i)
void transfer (PtrList< extendedFeatureEdgeMesh > &list)
void operator= (const PtrList< extendedFeatureEdgeMesh > &list)
void operator= (PtrList< extendedFeatureEdgeMesh > &&list)
void setSize (const label newLen)
void append (autoPtr< extendedFeatureEdgeMesh > &ptr)
void append (extendedFeatureEdgeMesh *ptr)
void append (std::unique_ptr< extendedFeatureEdgeMesh > &&ptr)
void append (autoPtr< extendedFeatureEdgeMesh > &&ptr)
void append (const refPtr< extendedFeatureEdgeMesh > &ptr)
void append (const tmp< extendedFeatureEdgeMesh > &ptr)
void append (PtrList< extendedFeatureEdgeMesh > &&other)
Public Member Functions inherited from UPtrList< T >
constexpr UPtrList () noexcept
UPtrList (const label len)
UPtrList (const UPtrList< T > &list)
UPtrList (UPtrList< T > &&list)
UPtrList (UPtrList< T > &list, bool reuse)
UPtrList (PtrList< T > &list)
UPtrList (const UList< T * > &list)
UPtrList (UList< T > &list)
bool empty () const noexcept
label size () const noexcept
label count () const noexcept
T & front ()
const T & front () const
T & back ()
const T & back () const
const T * test (const label i) const
const T * get (const label i) const
T * get (const label i)
const T * set (const label i) const
void clear ()
void free ()
void resize (const label newLen)
label squeezeNull ()
void trimTrailingNull ()
void push_back (T *ptr)
void push_back (UPtrList< T > &&other)
void swap (UPtrList< T > &list)
void transfer (UPtrList< T > &list)
T * set (const label i, T *ptr)
void reorder (const labelUList &oldToNew, const bool check=false)
void sortOrder (const labelUList &order, const bool check=false)
void checkNonNull () const
const T & at (const label i) const
T & at (const label i)
const T & operator[] (const label i) const
T & operator[] (const label i)
FOAM_DEPRECATED_FOR (2022-09, "get(), set() or test() methods") const T *operator()(const label i) const
void operator= (const UPtrList< T > &list)
void operator= (UPtrList< T > &&list)
T ** begin_ptr () noexcept
T ** end_ptr () noexcept
iterator begin ()
iterator end () noexcept
const_iterator cbegin () const
const_iterator cend () const noexcept
const_iterator begin () const
const_iterator end () const noexcept
void setSize (const label n)
T & first ()
const T & first () const
T & last ()
const T & last () const
void append (T *ptr)
void append (UPtrList< T > &&other)
Protected Member Functions
const PtrList< indexedOctree< treeDataEdge > > & edgeTrees () const
const PtrList< indexedOctree< treeDataPoint > > & pointTrees () const
const PtrList< indexedOctree< treeDataEdge > > & regionEdgeTrees () const
Protected Member Functions inherited from PtrList< extendedFeatureEdgeMesh >
void readIstream (Istream &is, const INew &inew)
Protected Member Functions inherited from UPtrList< T >
void setAddressableSize (const label n) noexcept
label find_next (label pos) const
UPtrList (Detail::PtrListDetail< T > &&ptrs)
Additional Inherited Members
Public Types inherited from UPtrList< T >
typedef T value_type
typedef T & reference
typedef const T & const_reference
Protected Attributes inherited from UPtrList< T >
Detail::PtrListDetail< T > ptrs_
Detailed Description
Encapsulates queries for features.
Source files
refinementFeatures.H
refinementFeatures.C
Definition at line 49 of file refinementFeatures.H.
Constructor & Destructor Documentation
refinementFeatures()
refinementFeatures (const objectRegistry & io, const PtrList< dictionary > & featDicts, const bool dryRun = false)
Definition at line 452 of file refinementFeatures.C.
References forAll, and io().
Member Function Documentation
edgeTrees()
const PtrList< indexedOctree< treeDataEdge > > & edgeTrees () const inline protected
Definition at line 94 of file refinementFeatures.H.
pointTrees()
const PtrList< indexedOctree< treeDataPoint > > & pointTrees () const inline protected
Definition at line 99 of file refinementFeatures.H.
regionEdgeTrees()
const Foam::PtrList< Foam::indexedOctree< Foam::treeDataEdge > > & regionEdgeTrees () const protected
Definition at line 404 of file refinementFeatures.C.
References e, forAll, boundBox::inflate(), points, rndGen, and PtrList< T >::set().
levels()
const labelListList & levels () const inline
Definition at line 125 of file refinementFeatures.H.
distances()
const List< scalarField > & distances () const inline
Definition at line 131 of file refinementFeatures.H.
maxDistance()
Foam::scalar maxDistance () const
Definition at line 852 of file refinementFeatures.C.
References forAll, and Foam::max().
findNearestEdge()
void findNearestEdge (const pointField & samples, const scalarField & nearestDistSqr, labelList & nearFeature, List< pointIndexHit > & nearInfo, vectorField & nearNormal) const
Definition at line 619 of file refinementFeatures.C.
References UPtrList< T >::empty(), forAll, PointIndexHit< PointType >::hit(), PointIndexHit< PointType >::index(), PointIndexHit< PointType >::point(), samples(), PtrList< T >::setSize(), UList< T >::size(), tree(), and Foam::Zero.
findNearestRegionEdge()
void findNearestRegionEdge (const pointField & samples, const scalarField & nearestDistSqr, labelList & nearFeature, List< pointIndexHit > & nearInfo, vectorField & nearNormal) const
Definition at line 675 of file refinementFeatures.C.
References forAll, PointIndexHit< PointType >::hit(), PointIndexHit< PointType >::index(), PointIndexHit< PointType >::point(), samples(), PtrList< T >::setSize(), UList< T >::size(), and Foam::Zero.
findNearestPoint()
void findNearestPoint (const pointField & samples, const scalarField & nearestDistSqr, labelList & nearFeature, List< pointIndexHit > & nearInfo) const
Definition at line 783 of file refinementFeatures.C.
References UPtrList< T >::empty(), forAll, PointIndexHit< PointType >::hit(), PointIndexHit< PointType >::index(), PointIndexHit< PointType >::point(), samples(), PtrList< T >::setSize(), UList< T >::size(), and tree().
findHigherLevel()
void findHigherLevel (const pointField & pt, const labelList & ptLevel, labelList & maxLevel) const
Definition at line 835 of file refinementFeatures.C.
References forAll.
checkSizes()
bool checkSizes (const scalar maxRatio, const boundBox & meshBb, const bool report, Ostream & os) const
Definition at line 549 of file refinementFeatures.C.
References UList< T >::contains(), Foam::endl(), forAll, boundBox::mag(), meshBb(), Foam::nl, os(), and Foam::returnReduceOr().
The documentation for this class was generated from the following files:
src/mesh/snappyHexMesh/refinementFeatures/refinementFeatures.H
src/mesh/snappyHexMesh/refinementFeatures/refinementFeatures.C