OpenFOAM: Bezier Class Reference
Bezier Class Reference
Calculation of adjoint based sensitivities for Bezier control points.
#include <Bezier.H>
Public Member Functions
TypeName ("Bezier")
Bezier (const fvMesh &mesh, const dictionary &dict)
virtual ~Bezier ()=default
label nBezier () const
PtrList< pointTensorField > & dxidXj ()
const boolList & confineXmovement () const
const boolList & confineYmovement () const
const boolList & confineZmovement () const
const boolListList & confineMovement () const
tmp< tensorField > dndbBasedSensitivities (const label patchI, const label cpI, bool returnDimensionedNormalSens=true) const
tmp< vectorField > dndbBasedSensitivities (const label patchI, const label cpI, const label idir, bool returnDimensionedNormalSens=true) const
tmp< tensorField > dxdbFace (const label patchI, const label cpI, bool useChainRule=true) const
tmp< vectorField > dxdbFace (const label patchI, const label cpI, const label idir, bool useChainRule=true) const
tensorField facePoints_d (const label globalFaceI, const label cpI) const
vectorField facePoints_d (const label globalFaceI, const label cpI, const label idir) const
const labelList & getActiveDesignVariables () const
Protected Attributes
const fvMesh & mesh_
const dictionary & dict_
label nBezier_
PtrList< pointTensorField > dxidXj_
boolList confineXmovement_
boolList confineYmovement_
boolList confineZmovement_
boolListList confineMovement_
labelList activeDesignVariables_
Detailed Description
Calculation of adjoint based sensitivities for Bezier control points.
Source files
Bezier.H
Bezier.C
Definition at line 54 of file Bezier.H.
Constructor & Destructor Documentation
Bezier()
Bezier (const fvMesh & mesh, const dictionary & dict)
Definition at line 40 of file Bezier.C.
References Bezier::activeDesignVariables_, IOobjectOption::AUTO_WRITE, Bezier::confineMovement_, Bezier::confineXmovement_, Bezier::confineYmovement_, Bezier::confineZmovement_, Bezier::dxidXj_, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Bezier::mesh_, IOobjectOption::MUST_READ, Foam::name(), Bezier::nBezier_, MeshObject< polyMesh, UpdateableMeshObject, pointMesh >::New(), PtrList< T >::set(), List< T >::setSize(), and UList< T >::size().
~Bezier()
virtual ~Bezier () virtual default
Member Function Documentation
TypeName()
TypeName ("Bezier")
nBezier()
label nBezier () const
Definition at line 120 of file Bezier.C.
References Bezier::nBezier_.
Referenced by sensitivityBezier::assembleSensitivities(), sensitivityBezierFI::assembleSensitivities(), optMeshMovementBezier::computeBoundaryMovement(), sensitivityBezier::sensitivityBezier(), sensitivityBezierFI::sensitivityBezierFI(), sensitivityBezier::write(), and sensitivityBezierFI::write().
dxidXj()
PtrList< pointTensorField > & dxidXj ()
Definition at line 126 of file Bezier.C.
References Bezier::dxidXj_.
Referenced by optMeshMovementBezier::computeBoundaryMovement().
confineXmovement()
const boolList & confineXmovement () const
Definition at line 132 of file Bezier.C.
References Bezier::confineXmovement_.
Referenced by sensitivityBezier::assembleSensitivities(), sensitivityBezierFI::assembleSensitivities(), and optMeshMovementBezier::computeBoundaryMovement().
confineYmovement()
const boolList & confineYmovement () const
Definition at line 138 of file Bezier.C.
References Bezier::confineYmovement_.
Referenced by sensitivityBezier::assembleSensitivities(), sensitivityBezierFI::assembleSensitivities(), and optMeshMovementBezier::computeBoundaryMovement().
confineZmovement()
const boolList & confineZmovement () const
Definition at line 144 of file Bezier.C.
References Bezier::confineZmovement_.
Referenced by sensitivityBezier::assembleSensitivities(), sensitivityBezierFI::assembleSensitivities(), and optMeshMovementBezier::computeBoundaryMovement().
confineMovement()
const boolListList & confineMovement () const
Definition at line 150 of file Bezier.C.
References Bezier::confineMovement_.
Referenced by sensitivityBezier::write(), and sensitivityBezierFI::write().
dndbBasedSensitivities() [1/2]
tmp< tensorField > dndbBasedSensitivities (const label patchI, const label cpI, bool returnDimensionedNormalSens = true) const
Definition at line 156 of file Bezier.C.
References Bezier::dxidXj_, forAll, deltaBoundary::makeFaceCentresAndAreas_d(), Bezier::mesh_, tmp< T >::New(), UPtrList< T >::size(), UList< T >::size(), and Foam::Zero.
Referenced by sensitivityBezier::assembleSensitivities(), and sensitivityBezierFI::assembleSensitivities().
dndbBasedSensitivities() [2/2]
tmp< vectorField > dndbBasedSensitivities (const label patchI, const label cpI, const label idir, bool returnDimensionedNormalSens = true) const
Definition at line 212 of file Bezier.C.
References Bezier::dxidXj_, forAll, deltaBoundary::makeFaceCentresAndAreas_d(), Bezier::mesh_, tmp< T >::New(), UPtrList< T >::size(), UList< T >::size(), Foam::unzipRow(), and Foam::Zero.
dxdbFace() [1/2]
tmp< tensorField > dxdbFace (const label patchI, const label cpI, bool useChainRule = true) const
Definition at line 271 of file Bezier.C.
References Bezier::dxdbFace(), Bezier::dxidXj_, forAll, deltaBoundary::makeFaceCentresAndAreas_d(), Bezier::mesh_, tmp< T >::New(), UPtrList< T >::size(), UList< T >::size(), and Foam::Zero.
Referenced by sensitivityBezier::assembleSensitivities(), sensitivityBezierFI::assembleSensitivities(), Bezier::dxdbFace(), Bezier::dxdbFace(), and sensitivityBezierFI::solveMeshMovementEqn().
dxdbFace() [2/2]
tmp< vectorField > dxdbFace (const label patchI, const label cpI, const label idir, bool useChainRule = true) const
Definition at line 323 of file Bezier.C.
References Foam::component(), Bezier::dxdbFace(), Bezier::dxidXj_, forAll, deltaBoundary::makeFaceCentresAndAreas_d(), Bezier::mesh_, tmp< T >::New(), UPtrList< T >::size(), UList< T >::size(), and Foam::Zero.
facePoints_d() [1/2]
tensorField facePoints_d (const label globalFaceI, const label cpI) const
Definition at line 385 of file Bezier.C.
References Bezier::dxidXj_, forAll, Bezier::mesh_, UPtrList< T >::size(), and Foam::Zero.
facePoints_d() [2/2]
vectorField facePoints_d (const label globalFaceI, const label cpI, const label idir) const
Definition at line 401 of file Bezier.C.
References Bezier::dxidXj_, forAll, Bezier::mesh_, UPtrList< T >::size(), and Foam::Zero.
getActiveDesignVariables()
const labelList & getActiveDesignVariables () const
Definition at line 421 of file Bezier.C.
References Bezier::activeDesignVariables_.
Member Data Documentation
mesh_
const fvMesh& mesh_ protected
Definition at line 71 of file Bezier.H.
Referenced by Bezier::Bezier(), Bezier::dndbBasedSensitivities(), Bezier::dndbBasedSensitivities(), Bezier::dxdbFace(), Bezier::dxdbFace(), Bezier::facePoints_d(), and Bezier::facePoints_d().
dict_
const dictionary& dict_ protected
Definition at line 72 of file Bezier.H.
nBezier_
label nBezier_ protected
Definition at line 74 of file Bezier.H.
Referenced by Bezier::Bezier(), and Bezier::nBezier().
dxidXj_
PtrList<pointTensorField> dxidXj_ protected
Definition at line 75 of file Bezier.H.
Referenced by Bezier::Bezier(), Bezier::dndbBasedSensitivities(), Bezier::dndbBasedSensitivities(), Bezier::dxdbFace(), Bezier::dxdbFace(), Bezier::dxidXj(), Bezier::facePoints_d(), and Bezier::facePoints_d().
confineXmovement_
boolList confineXmovement_ protected
Definition at line 77 of file Bezier.H.
Referenced by Bezier::Bezier(), and Bezier::confineXmovement().
confineYmovement_
boolList confineYmovement_ protected
Definition at line 78 of file Bezier.H.
Referenced by Bezier::Bezier(), and Bezier::confineYmovement().
confineZmovement_
boolList confineZmovement_ protected
Definition at line 79 of file Bezier.H.
Referenced by Bezier::Bezier(), and Bezier::confineZmovement().
confineMovement_
boolListList confineMovement_ protected
Definition at line 80 of file Bezier.H.
Referenced by Bezier::Bezier(), and Bezier::confineMovement().
activeDesignVariables_
labelList activeDesignVariables_ protected
Definition at line 81 of file Bezier.H.
Referenced by Bezier::Bezier(), and Bezier::getActiveDesignVariables().
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/parameterization/Bezier/Bezier.H
src/optimisation/adjointOptimisation/adjoint/parameterization/Bezier/Bezier.C