OpenFOAM: adjointBoundaryCondition< Type > Class Template Reference
adjointBoundaryCondition< Type > Class Template Reference
Base class for solution control classes.
#include <adjointBoundaryCondition.H>
Public Member Functions
TypeName ("adjointBoundaryCondition")
adjointBoundaryCondition (const fvPatch &p, const DimensionedField< Type, volMesh > &iF, const word &solverName)
adjointBoundaryCondition (const adjointBoundaryCondition< Type > &)
virtual ~adjointBoundaryCondition ()=default
const word & objectiveManagerName () const
const word & adjointSolverName () const
const word & simulationType () const
void setBoundaryContributionPtr ()
boundaryAdjointContribution & getBoundaryAdjContribution ()
const ATCModel & getATC () const
virtual tmp< Field< typename Foam::outerProduct< Foam::vector, Type >::type > > dxdbMult () const
virtual void updatePrimalBasedQuantities ()
Protected Member Functions
template<class Type2 >
tmp< Field< typename Foam::outerProduct< Foam::vector, Type2 >::type > > computePatchGrad (word name)
bool addATCUaGradUTerm ()
Protected Attributes
const fvPatch & patch_
word managerName_
word adjointSolverName_
word simulationType_
autoPtr< boundaryAdjointContribution > boundaryContrPtr_
Switch addATCUaGradUTerm_
Detailed Description
template<class Type>
class Foam::adjointBoundaryCondition< Type >
Base class for solution control classes.
Definition at line 47 of file adjointBoundaryCondition.H.
Constructor & Destructor Documentation
adjointBoundaryCondition() [1/2]
template<class Type > adjointBoundaryCondition (const fvPatch & p, const DimensionedField< Type, volMesh > & iF, const word & solverName)
Definition at line 205 of file adjointBoundaryCondition.C.
References adjointBoundaryCondition< Type >::setBoundaryContributionPtr().
adjointBoundaryCondition() [2/2]
template<class Type > adjointBoundaryCondition (const adjointBoundaryCondition< Type > & adjointBC)
Definition at line 179 of file adjointBoundaryCondition.C.
~adjointBoundaryCondition()
template<class Type > virtual ~adjointBoundaryCondition () virtual default
Member Function Documentation
computePatchGrad()
template<class Type > template<class Type2 > tmp< Field< typename Foam::outerProduct< Foam::vector, Type2 >::type > > computePatchGrad (word name) protected
Definition at line 43 of file adjointBoundaryCondition.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), polyMesh::boundaryMesh(), solution::cachePrintMessage(), cells, field(), forAll, Foam::interpolate(), mesh, Foam::name(), surfaceInterpolationScheme< Type >::New(), Foam::New(), patchID, PtrList< T >::PtrList(), regIOobject::store(), and Foam::Zero.
addATCUaGradUTerm()
template<class Type > bool addATCUaGradUTerm () protected
Definition at line 166 of file adjointBoundaryCondition.C.
References PtrList< T >::PtrList().
TypeName()
template<class Type > TypeName ("adjointBoundaryCondition< Type >")
objectiveManagerName()
template<class Type > const word & objectiveManagerName () const
Definition at line 227 of file adjointBoundaryCondition.C.
adjointSolverName()
template<class Type > const word & adjointSolverName () const
Definition at line 234 of file adjointBoundaryCondition.C.
simulationType()
template<class Type > const word & simulationType () const
Definition at line 241 of file adjointBoundaryCondition.C.
setBoundaryContributionPtr()
template<class Type > void setBoundaryContributionPtr ()
Definition at line 248 of file adjointBoundaryCondition.C.
References Foam::endl(), boundaryAdjointContribution::New(), Foam::nl, and WarningInFunction.
Referenced by adjointBoundaryCondition< Type >::adjointBoundaryCondition().
getBoundaryAdjContribution()
template<class Type > boundaryAdjointContribution & getBoundaryAdjContribution ()
Definition at line 281 of file adjointBoundaryCondition.C.
getATC()
template<class Type > const ATCModel & getATC () const
Definition at line 288 of file adjointBoundaryCondition.C.
References PtrList< T >::PtrList().
dxdbMult()
template<class Type > tmp< Field< typename Foam::outerProduct< Foam::vector, Type >::type > > dxdbMult () const virtual
Reimplemented in adjointRotatingWallVelocityFvPatchVectorField.
Definition at line 308 of file adjointBoundaryCondition.C.
References Foam::New(), and Foam::Zero.
updatePrimalBasedQuantities()
template<class Type > void updatePrimalBasedQuantities () virtual
Definition at line 297 of file adjointBoundaryCondition.C.
Member Data Documentation
patch_
template<class Type > const fvPatch& patch_ protected
Definition at line 54 of file adjointBoundaryCondition.H.
managerName_
template<class Type > word managerName_ protected
Definition at line 57 of file adjointBoundaryCondition.H.
Referenced by adjointInletNuaTildaFvPatchScalarField::clone().
adjointSolverName_
template<class Type > word adjointSolverName_ protected
Definition at line 60 of file adjointBoundaryCondition.H.
Referenced by adjointFarFieldNuaTildaFvPatchScalarField::write(), adjointFarFieldTMVar1FvPatchScalarField::write(), adjointFarFieldTMVar2FvPatchScalarField::write(), adjointInletNuaTildaFvPatchScalarField::write(), adjointOutletKaFvPatchScalarField::write(), adjointOutletNuaTildaFvPatchScalarField::write(), adjointOutletNuaTildaFluxFvPatchScalarField::write(), and adjointOutletWaFvPatchScalarField::write().
simulationType_
template<class Type > word simulationType_ protected
Definition at line 64 of file adjointBoundaryCondition.H.
boundaryContrPtr_
template<class Type > autoPtr<boundaryAdjointContribution> boundaryContrPtr_ protected
Definition at line 68 of file adjointBoundaryCondition.H.
Referenced by adjointFarFieldNuaTildaFvPatchScalarField::updateCoeffs(), adjointFarFieldTMVar1FvPatchScalarField::updateCoeffs(), adjointFarFieldTMVar2FvPatchScalarField::updateCoeffs(), adjointOutletKaFvPatchScalarField::updateCoeffs(), adjointOutletNuaTildaFvPatchScalarField::updateCoeffs(), adjointOutletWaFvPatchScalarField::updateCoeffs(), adjointFarFieldNuaTildaFvPatchScalarField::valueBoundaryCoeffs(), adjointFarFieldTMVar1FvPatchScalarField::valueBoundaryCoeffs(), adjointFarFieldTMVar2FvPatchScalarField::valueBoundaryCoeffs(), adjointFarFieldNuaTildaFvPatchScalarField::valueInternalCoeffs(), adjointFarFieldTMVar1FvPatchScalarField::valueInternalCoeffs(), and adjointFarFieldTMVar2FvPatchScalarField::valueInternalCoeffs().
addATCUaGradUTerm_
template<class Type > Switch addATCUaGradUTerm_ protected
Definition at line 73 of file adjointBoundaryCondition.H.
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/adjointBoundaryConditions/adjointBoundaryCondition/adjointBoundaryCondition.H
src/optimisation/adjointOptimisation/adjoint/adjointBoundaryConditions/adjointBoundaryCondition/adjointBoundaryCondition.C