OpenFOAM: structuredRenumber Class Reference
structuredRenumber Class Reference
Renumbering according to mesh layers. depthFirst = true: first column gets ids 0..nLayer-1, second nLayers..2*nLayers-1 etc. depthFirst = false: first layer gets ids 0,1,2 etc.
#include <structuredRenumber.H>
Classes
class layerLess
Public Member Functions
structuredRenumber (const structuredRenumber &)=delete
void operator= (const structuredRenumber &)=delete
TypeName ("structured")
structuredRenumber (const dictionary &dict)
virtual ~structuredRenumber ()=default
virtual labelList renumber (const pointField &) const
virtual labelList renumber (const polyMesh &mesh, const pointField &cc) const
virtual labelList renumber (const CompactListList< label > &cellCells, const pointField &cellCentres) const
virtual labelList renumber (const labelListList &cellCells, const pointField &cellCentres) const
Public Member Functions inherited from renumberMethod
TypeName ("renumberMethod")
declareRunTimeSelectionTable (autoPtr, renumberMethod, dictionary,(const dictionary &renumberDict),(renumberDict))
renumberMethod (const dictionary &dict)
virtual ~renumberMethod ()=default
virtual labelList renumber (const labelList &cellCells, const labelList &offsets, const pointField &) const
virtual labelList renumber (const polyMesh &mesh, const labelList &fineToCoarse, const pointField &coarsePoints) const
Public Attributes
const dictionary & coeffsDict_
const wordRes patches_
const label nLayers_
const bool depthFirst_
const bool reverse_
const autoPtr< renumberMethod > method_
Additional Inherited Members
Static Public Member Functions inherited from renumberMethod
static autoPtr< renumberMethod > New (const dictionary &renumberDict)
Protected Member Functions inherited from renumberMethod
renumberMethod (const renumberMethod &)=delete
void operator= (const renumberMethod &)=delete
Protected Attributes inherited from renumberMethod
const dictionary & renumberDict_
Detailed Description
Renumbering according to mesh layers. depthFirst = true: first column gets ids 0..nLayer-1, second nLayers..2*nLayers-1 etc. depthFirst = false: first layer gets ids 0,1,2 etc.
Source files
structuredRenumber.H
structuredRenumber.C
Definition at line 53 of file structuredRenumber.H.
Constructor & Destructor Documentation
structuredRenumber() [1/2]
structuredRenumber (const structuredRenumber &) delete
structuredRenumber() [2/2]
structuredRenumber (const dictionary & dict) explicit
Definition at line 45 of file structuredRenumber.C.
References Foam::labelMax, and Foam::New().
~structuredRenumber()
virtual ~structuredRenumber () virtual default
Member Function Documentation
operator=()
void operator= (const structuredRenumber &) delete
TypeName()
TypeName ("structured")
renumber() [1/4]
virtual labelList renumber (const pointField &) const inline virtual
Reimplemented from renumberMethod.
Definition at line 132 of file structuredRenumber.H.
References NotImplemented.
renumber() [2/4]
Foam::labelList renumber (const polyMesh & mesh, const pointField & cc) const virtual
Reimplemented from renumberMethod.
Definition at line 131 of file structuredRenumber.C.
References polyMesh::boundaryMesh(), fvMeshSubset::cellMap(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, polyMesh::globalData(), Foam::Info, Foam::invert(), mesh, primitiveMesh::nCells(), primitiveMesh::nFaces(), Foam::nl, patchId(), patchIDs(), pbm, points, pp(), Foam::renumber(), Foam::returnReduce(), Foam::reverse(), UPtrList< T >::size(), Foam::sortedOrder(), fvMeshSubset::subMesh(), and Foam::type().
renumber() [3/4]
virtual labelList renumber (const CompactListList< label > & cellCells, const pointField & cellCentres) const inline virtual
Reimplemented from renumberMethod.
Definition at line 149 of file structuredRenumber.H.
References NotImplemented.
renumber() [4/4]
virtual labelList renumber (const labelListList & cellCells, const pointField & cellCentres) const inline virtual
Implements renumberMethod.
Definition at line 161 of file structuredRenumber.H.
References NotImplemented.
Member Data Documentation
coeffsDict_
const dictionary& coeffsDict_
Definition at line 89 of file structuredRenumber.H.
patches_
const wordRes patches_
Definition at line 91 of file structuredRenumber.H.
nLayers_
const label nLayers_
Definition at line 93 of file structuredRenumber.H.
depthFirst_
const bool depthFirst_
Definition at line 95 of file structuredRenumber.H.
reverse_
const bool reverse_
Definition at line 97 of file structuredRenumber.H.
method_
const autoPtr<renumberMethod> method_
Definition at line 99 of file structuredRenumber.H.
The documentation for this class was generated from the following files:
src/renumber/renumberMethods/structuredRenumber/structuredRenumber.H
src/renumber/renumberMethods/structuredRenumber/structuredRenumber.C