OpenFOAM: mapDistributePolyMesh Class Reference
mapDistributePolyMesh Class Reference
Class containing mesh-to-mesh mapping information after a mesh distribution where we send parts of meshes (using subsetting) to other processors and receive and reconstruct mesh.
#include <mapDistributePolyMesh.H>
Public Member Functions
mapDistributePolyMesh ()
mapDistributePolyMesh (const label comm)
mapDistributePolyMesh (const dictionary &dict, const label comm=UPstream::worldComm)
mapDistributePolyMesh (const mapDistributePolyMesh &map)
mapDistributePolyMesh (mapDistributePolyMesh &&map)
mapDistributePolyMesh (mapDistributePolyMesh &map, bool reuse)
mapDistributePolyMesh (const polyMesh &mesh, const label nOldPoints, const label nOldFaces, const label nOldCells, labelList &&oldPatchStarts, labelList &&oldPatchNMeshPoints, labelListList &&subPointMap, labelListList &&subFaceMap, labelListList &&subCellMap, labelListList &&subPatchMap, labelListList &&constructPointMap, labelListList &&constructFaceMap, labelListList &&constructCellMap, labelListList &&constructPatchMap, const bool subFaceHasFlip=false, const bool constructFaceHasFlip=false)
mapDistributePolyMesh (const label nOldPoints, const label nOldFaces, const label nOldCells, labelList &&oldPatchStarts, labelList &&oldPatchNMeshPoints, mapDistribute &&pointMap, mapDistribute &&faceMap, mapDistribute &&cellMap, mapDistribute &&patchMap)
mapDistributePolyMesh (Istream &is)
label nOldPoints () const noexcept
label nOldFaces () const noexcept
label nOldCells () const noexcept
const labelList & oldPatchSizes () const noexcept
const labelList & oldPatchStarts () const noexcept
const labelList & oldPatchNMeshPoints () const noexcept
const mapDistribute & pointMap () const noexcept
const mapDistribute & faceMap () const noexcept
const mapDistribute & cellMap () const noexcept
const mapDistribute & patchMap () const noexcept
void clear ()
void transfer (mapDistributePolyMesh &map)
template<class T >
void distributePointData (List< T > &values) const
template<class T >
void distributeFaceData (List< T > &values) const
template<class T >
void distributeCellData (List< T > &values) const
template<class T >
void distributePatchData (List< T > &values) const
void distributePointIndices (labelList &pointIDs) const
void distributeFaceIndices (labelList &faceIDs) const
void distributeCellIndices (labelList &cellIDs) const
void distributePatchIndices (labelList &patchIDs) const
void operator= (const mapDistributePolyMesh &map)
void operator= (mapDistributePolyMesh &&map)
InfoProxy< mapDistributePolyMesh > info () const noexcept
void readDict (const dictionary &dict)
void writeCellMapEntries (Ostream &os) const
void writeFaceMapEntries (Ostream &os) const
void writePointMapEntries (Ostream &os) const
void writePatchMapEntries (Ostream &os) const
void writeEntries (Ostream &os) const
void updateMesh (const mapPolyMesh &)
Friends
Istream & operator>> (Istream &, mapDistributePolyMesh &)
Ostream & operator<< (Ostream &, const mapDistributePolyMesh &)
Detailed Description
Class containing mesh-to-mesh mapping information after a mesh distribution where we send parts of meshes (using subsetting) to other processors and receive and reconstruct mesh.
We store mapping from the bits-to-send to the complete starting mesh (subXXXMap) and from the received bits to their location in the new mesh (constructXXXMap).
Source files
mapDistributePolyMesh.H
mapDistributePolyMesh.C
Definition at line 65 of file mapDistributePolyMesh.H.
Constructor & Destructor Documentation
mapDistributePolyMesh() [1/9]
mapDistributePolyMesh ()
Definition at line 57 of file mapDistributePolyMesh.C.
mapDistributePolyMesh() [2/9]
mapDistributePolyMesh (const label comm) explicit
Definition at line 63 of file mapDistributePolyMesh.C.
mapDistributePolyMesh() [3/9]
mapDistributePolyMesh (const dictionary & dict, const label comm = UPstream::worldComm) explicit
Definition at line 26 of file mapDistributePolyMeshIO.C.
References dict, and mapDistributePolyMesh::readDict().
mapDistributePolyMesh() [4/9]
mapDistributePolyMesh (const mapDistributePolyMesh & map)
Definition at line 78 of file mapDistributePolyMesh.C.
mapDistributePolyMesh() [5/9]
mapDistributePolyMesh (mapDistributePolyMesh && map)
Definition at line 89 of file mapDistributePolyMesh.C.
References mapDistributePolyMesh::transfer().
mapDistributePolyMesh() [6/9]
mapDistributePolyMesh (mapDistributePolyMesh & map, bool reuse)
Definition at line 100 of file mapDistributePolyMesh.C.
References mapDistributePolyMesh::transfer().
mapDistributePolyMesh() [7/9]
mapDistributePolyMesh (const polyMesh & mesh, const label nOldPoints, const label nOldFaces, const label nOldCells, labelList && oldPatchStarts, labelList && oldPatchNMeshPoints, labelListList && subPointMap, labelListList && subFaceMap, labelListList && subCellMap, labelListList && subPatchMap, labelListList && constructPointMap, labelListList && constructFaceMap, labelListList && constructCellMap, labelListList && constructPatchMap, const bool subFaceHasFlip = false, const bool constructFaceHasFlip = false)
Definition at line 119 of file mapDistributePolyMesh.C.
mapDistributePolyMesh() [8/9]
mapDistributePolyMesh (const label nOldPoints, const label nOldFaces, const label nOldCells, labelList && oldPatchStarts, labelList && oldPatchNMeshPoints, mapDistribute && pointMap, mapDistribute && faceMap, mapDistribute && cellMap, mapDistribute && patchMap)
Definition at line 183 of file mapDistributePolyMesh.C.
mapDistributePolyMesh() [9/9]
mapDistributePolyMesh (Istream & is) explicit
Definition at line 38 of file mapDistributePolyMeshIO.C.
Member Function Documentation
nOldPoints()
label nOldPoints () const inline noexcept
Definition at line 188 of file mapDistributePolyMesh.H.
Referenced by pointSet::distribute(), faMeshTools::writeProcAddressing(), and fvMeshTools::writeProcAddressing().
nOldFaces()
label nOldFaces () const inline noexcept
Definition at line 194 of file mapDistributePolyMesh.H.
Referenced by faceSet::distribute(), faMeshTools::writeProcAddressing(), and fvMeshTools::writeProcAddressing().
nOldCells()
label nOldCells () const inline noexcept
Definition at line 200 of file mapDistributePolyMesh.H.
Referenced by cellSet::distribute(), faMeshTools::writeProcAddressing(), and fvMeshTools::writeProcAddressing().
oldPatchSizes()
const labelList & oldPatchSizes () const inline noexcept
Definition at line 206 of file mapDistributePolyMesh.H.
Referenced by faMeshTools::writeProcAddressing(), and fvMeshTools::writeProcAddressing().
oldPatchStarts()
const labelList & oldPatchStarts () const inline noexcept
Definition at line 212 of file mapDistributePolyMesh.H.
oldPatchNMeshPoints()
const labelList & oldPatchNMeshPoints () const inline noexcept
Definition at line 218 of file mapDistributePolyMesh.H.
pointMap()
const mapDistribute & pointMap () const inline noexcept
Definition at line 224 of file mapDistributePolyMesh.H.
Referenced by hexRef8Data::distribute(), faMeshTools::writeProcAddressing(), and fvMeshTools::writeProcAddressing().
faceMap()
const mapDistribute & faceMap () const inline noexcept
Definition at line 230 of file mapDistributePolyMesh.H.
Referenced by faMeshTools::writeProcAddressing(), and fvMeshTools::writeProcAddressing().
cellMap()
const mapDistribute & cellMap () const inline noexcept
Definition at line 236 of file mapDistributePolyMesh.H.
Referenced by hexRef8Data::distribute(), refinementHistory::distribute(), faMeshTools::writeProcAddressing(), and fvMeshTools::writeProcAddressing().
patchMap()
const mapDistribute & patchMap () const inline noexcept
Definition at line 242 of file mapDistributePolyMesh.H.
Referenced by faMeshTools::writeProcAddressing(), and fvMeshTools::writeProcAddressing().
clear()
void clear ()
Definition at line 216 of file mapDistributePolyMesh.C.
References PtrList< T >::clear().
transfer()
void transfer (mapDistributePolyMesh & map)
Definition at line 252 of file mapDistributePolyMesh.C.
References PtrList< T >::transfer().
Referenced by IOmapDistributePolyMesh::IOmapDistributePolyMesh(), mapDistributePolyMesh::mapDistributePolyMesh(), and mapDistributePolyMesh::mapDistributePolyMesh().
distributePointData()
template<class T > void distributePointData (List< T > & values) const inline
Definition at line 261 of file mapDistributePolyMesh.H.
References mapDistribute::distribute().
Referenced by hexRef8::distribute(), pointSet::distribute(), pointBitSet::distribute(), faMeshTools::writeProcAddressing(), and fvMeshTools::writeProcAddressing().
distributeFaceData()
template<class T > void distributeFaceData (List< T > & values) const inline
Definition at line 268 of file mapDistributePolyMesh.H.
References mapDistribute::distribute().
Referenced by meshRefinement::distribute(), faceBitSet::distribute(), faceBoolSet::distribute(), and faceSet::distribute().
distributeCellData()
template<class T > void distributeCellData (List< T > & values) const inline
Definition at line 275 of file mapDistributePolyMesh.H.
References mapDistribute::distribute().
Referenced by hexRef8::distribute(), cellSet::distribute(), and fvMeshTools::writeProcAddressing().
distributePatchData()
template<class T > void distributePatchData (List< T > & values) const inline
Definition at line 282 of file mapDistributePolyMesh.H.
References mapDistribute::distribute().
distributePointIndices()
void distributePointIndices (labelList & pointIDs) const
Definition at line 277 of file mapDistributePolyMesh.C.
References Foam::findIndices().
distributeFaceIndices()
void distributeFaceIndices (labelList & faceIDs) const
Definition at line 293 of file mapDistributePolyMesh.C.
References Foam::findIndices().
distributeCellIndices()
void distributeCellIndices (labelList & cellIDs) const
Definition at line 309 of file mapDistributePolyMesh.C.
References Foam::findIndices().
distributePatchIndices()
void distributePatchIndices (labelList & patchIDs) const
Definition at line 325 of file mapDistributePolyMesh.C.
References Foam::findIndices().
operator=() [1/2]
void operator= (const mapDistributePolyMesh & map)
Definition at line 349 of file mapDistributePolyMesh.C.
Referenced by IOmapDistributePolyMesh::IOmapDistributePolyMesh().
operator=() [2/2]
void operator= (mapDistributePolyMesh && map)
Definition at line 370 of file mapDistributePolyMesh.C.
info()
InfoProxy< mapDistributePolyMesh > info () const inline noexcept
Definition at line 311 of file mapDistributePolyMesh.H.
readDict()
void readDict (const dictionary & dict)
Definition at line 46 of file mapDistributePolyMeshIO.C.
References dict, and dictionary::subDict().
Referenced by mapDistributePolyMesh::mapDistributePolyMesh().
writeCellMapEntries()
void writeCellMapEntries (Ostream & os) const
Definition at line 84 of file mapDistributePolyMeshIO.C.
References Ostream::beginBlock(), Ostream::endBlock(), os(), and Ostream::writeEntry().
writeFaceMapEntries()
void writeFaceMapEntries (Ostream & os) const
Definition at line 93 of file mapDistributePolyMeshIO.C.
References Ostream::beginBlock(), Ostream::endBlock(), os(), and Ostream::writeEntry().
writePointMapEntries()
void writePointMapEntries (Ostream & os) const
Definition at line 102 of file mapDistributePolyMeshIO.C.
References Ostream::beginBlock(), Ostream::endBlock(), os(), and Ostream::writeEntry().
writePatchMapEntries()
void writePatchMapEntries (Ostream & os) const
Definition at line 111 of file mapDistributePolyMeshIO.C.
References Ostream::beginBlock(), Ostream::endBlock(), and os().
writeEntries()
void writeEntries (Ostream & os) const
Definition at line 122 of file mapDistributePolyMeshIO.C.
References Foam::nl, and os().
updateMesh()
void updateMesh (const mapPolyMesh &) inline
Definition at line 346 of file mapDistributePolyMesh.H.
References NotImplemented.
Friends And Related Symbol Documentation
operator>>
Istream & operator>> (Istream & , mapDistributePolyMesh &) friend
operator<<
Ostream & operator<< (Ostream & , const mapDistributePolyMesh &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/mapDistribute/mapDistributePolyMesh.H
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/mapDistribute/mapDistributePolyMesh.C
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/mapDistribute/mapDistributePolyMeshIO.C