OpenFOAM: manualGAMGProcAgglomeration Class Reference
manualGAMGProcAgglomeration Class Reference
Manual processor agglomeration of GAMGAgglomerations.
#include <manualGAMGProcAgglomeration.H>
Public Member Functions
TypeName ("manual")
manualGAMGProcAgglomeration (const manualGAMGProcAgglomeration &)=delete
void operator= (const manualGAMGProcAgglomeration &)=delete
manualGAMGProcAgglomeration (GAMGAgglomeration &agglom, const dictionary &controlDict)
virtual ~manualGAMGProcAgglomeration ()
virtual bool agglomerate ()
Public Member Functions inherited from GAMGProcAgglomeration
TypeName ("GAMGProcAgglomeration")
declareRunTimeSelectionTable (autoPtr, GAMGProcAgglomeration, GAMGAgglomeration,(GAMGAgglomeration &agglom, const dictionary &controlDict),(agglom, controlDict))
GAMGProcAgglomeration (const GAMGProcAgglomeration &)=delete
void operator= (const GAMGProcAgglomeration &)=delete
GAMGProcAgglomeration (GAMGAgglomeration &agglom, const dictionary &controlDict)
virtual ~GAMGProcAgglomeration ()
Additional Inherited Members
Static Public Member Functions inherited from GAMGProcAgglomeration
static autoPtr< GAMGProcAgglomeration > New (const word &type, GAMGAgglomeration &agglom, const dictionary &controlDict)
Protected Member Functions inherited from GAMGProcAgglomeration
void printStats (Ostream &os, GAMGAgglomeration &agglom) const
bool agglomerate (const label fineLevelIndex, const labelList &procAgglomMap, const labelList &masterProcs, const List< label > &agglomProcIDs, const label procAgglomComm)
void clearCommunicators ()
Static Protected Member Functions inherited from GAMGProcAgglomeration
static labelListList globalCellCells (const lduMesh &)
Protected Attributes inherited from GAMGProcAgglomeration
GAMGAgglomeration & agglom_
DynamicList< label > comms_
Detailed Description
Manual processor agglomeration of GAMGAgglomerations.
In the GAMG control dictionary:
processorAgglomerator manual; List of level+procagglomeration where procagglomeration is a set of labelLists. Each labelList is a cluster of processor which gets combined onto the first element in the list. processorAgglomeration ((3 //at level 3 ((0 1) //coarse 0 from 0,1 (and moved onto 0) (3 2) //coarse 1 from 2,3 (and moved onto 3))) (6 //at level6 ((0 1) //coarse 0 from 0,1 (and moved onto 0))));
Source files
manualGAMGProcAgglomeration.H
manualGAMGProcAgglomeration.C
Definition at line 72 of file manualGAMGProcAgglomeration.H.
Constructor & Destructor Documentation
manualGAMGProcAgglomeration() [1/2]
manualGAMGProcAgglomeration (const manualGAMGProcAgglomeration &) delete
manualGAMGProcAgglomeration() [2/2]
manualGAMGProcAgglomeration (GAMGAgglomeration & agglom, const dictionary & controlDict)
Definition at line 43 of file manualGAMGProcAgglomeration.C.
~manualGAMGProcAgglomeration()
~manualGAMGProcAgglomeration () virtual
Definition at line 56 of file manualGAMGProcAgglomeration.C.
Member Function Documentation
TypeName()
TypeName ("manual")
operator=()
void operator= (const manualGAMGProcAgglomeration &) delete
agglomerate()
bool agglomerate () virtual
Implements GAMGProcAgglomeration.
Definition at line 62 of file manualGAMGProcAgglomeration.C.
References GAMGProcAgglomeration::agglomerate(), UPstream::allocateCommunicator(), UList< T >::back(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, UList< T >::find(), UPtrList< T >::first(), forAll, UList< T >::found(), UPstream::myProcNo(), Foam::nl, UPstream::nProcs(), Foam::Pout, UPtrList< T >::size(), Foam::Swap(), and WarningInFunction.
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/GAMGProcAgglomerations/manualGAMGProcAgglomeration/manualGAMGProcAgglomeration.H
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/GAMGProcAgglomerations/manualGAMGProcAgglomeration/manualGAMGProcAgglomeration.C