OpenFOAM: faMeshMapper Class Reference
faMeshMapper Class Reference
Class holds all the necessary information for mapping fields associated with faMesh.
#include <faMeshMapper.H>
Public Member Functions
faMeshMapper (const faMesh &mesh, const mapPolyMesh &mpm)
const faMesh & mesh () const
const objectRegistry & thisDb () const
label nOldPoints () const
label nOldEdges () const
label nOldInternalEdges () const
label nOldFaces () const
const labelList & oldPatchSizes () const
const labelList & oldPatchStarts () const
const labelListList & oldPatchEdgeFaces () const
const faAreaMapper & areaMap () const
const faEdgeMapper & edgeMap () const
const faBoundaryMeshMapper & boundaryMap () const
Detailed Description
Class holds all the necessary information for mapping fields associated with faMesh.
Note
In order to capture all necessary mesh sizes and mapping data, mapper is created with the OLD mesh, and provides new mesh data. In the process, field mapping information is assembled from the old faMesh and the mapping data
Author Zeljko Tukovic, FMENA Hrvoje Jasak, Wikki Ltd.
Source files
faMeshMapper.H
faMeshMapper.C
Definition at line 64 of file faMeshMapper.H.
Constructor & Destructor Documentation
faMeshMapper()
faMeshMapper (const faMesh & mesh, const mapPolyMesh & mpm)
Definition at line 25 of file faMeshMapper.C.
References forAll, faMeshMapper::mesh(), patches, and UList< T >::size().
Member Function Documentation
mesh()
const faMesh & mesh () const inline
Definition at line 128 of file faMeshMapper.H.
Referenced by faMeshMapper::faMeshMapper().
thisDb()
const objectRegistry & thisDb () const inline
Definition at line 135 of file faMeshMapper.H.
References faMesh::thisDb().
nOldPoints()
label nOldPoints () const inline
Definition at line 144 of file faMeshMapper.H.
nOldEdges()
label nOldEdges () const inline
Definition at line 150 of file faMeshMapper.H.
nOldInternalEdges()
label nOldInternalEdges () const inline
Definition at line 156 of file faMeshMapper.H.
nOldFaces()
label nOldFaces () const inline
Definition at line 162 of file faMeshMapper.H.
oldPatchSizes()
const labelList & oldPatchSizes () const inline
Definition at line 168 of file faMeshMapper.H.
oldPatchStarts()
const labelList & oldPatchStarts () const inline
Definition at line 174 of file faMeshMapper.H.
oldPatchEdgeFaces()
const labelListList & oldPatchEdgeFaces () const inline
Definition at line 180 of file faMeshMapper.H.
Referenced by faMesh::updateMesh().
areaMap()
const faAreaMapper & areaMap () const inline
Definition at line 189 of file faMeshMapper.H.
Referenced by faMesh::mapOldAreas(), and faMesh::updateMesh().
edgeMap()
const faEdgeMapper & edgeMap () const inline
Definition at line 195 of file faMeshMapper.H.
boundaryMap()
const faBoundaryMeshMapper & boundaryMap () const inline
Definition at line 201 of file faMeshMapper.H.
The documentation for this class was generated from the following files:
src/finiteArea/faMesh/faMeshMapper/faMeshMapper.H
src/finiteArea/faMesh/faMeshMapper/faMeshMapper.C