OpenFOAM: fluxCorrectedVelocityFvPatchVectorField Class Reference
fluxCorrectedVelocityFvPatchVectorField Class Reference
Boundary conditions » Outlet
This boundary condition provides a velocity outlet boundary condition for patches where the pressure is specified. The outflow velocity is obtained by "zeroGradient" and then corrected from the flux:
#include <fluxCorrectedVelocityFvPatchVectorField.H>
Public Member Functions
TypeName ("fluxCorrectedVelocity")
fluxCorrectedVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
fluxCorrectedVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
fluxCorrectedVelocityFvPatchVectorField (const fluxCorrectedVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
virtual tmp< fvPatchVectorField > clone () const
fluxCorrectedVelocityFvPatchVectorField (const fluxCorrectedVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
virtual void evaluate (const Pstream::commsTypes commsType=Pstream::commsTypes::blocking)
virtual void write (Ostream &) const
Detailed Description
This boundary condition provides a velocity outlet boundary condition for patches where the pressure is specified. The outflow velocity is obtained by "zeroGradient" and then corrected from the flux:
where
= velocity at the patch [m/s]
= velocity in cells adjacent to the patch [m/s]
= patch normal vectors
= flux at the patch [m3/s or kg/s]
= patch face area vectors [m2]
where
Property Description Required Default value
phi name of flux field no phi
rho name of density field no rho
Example of the boundary condition specification:
    <patchName>
    {
        type            fluxCorrectedVelocity;
        phi             phi;
        rho             rho;
    }
Note
If reverse flow is possible or expected use the pressureInletOutletVelocity condition instead.
See also
Foam::zeroGradientFvPatchField Foam::pressureInletOutletVelocityFvPatchVectorField
Source files
fluxCorrectedVelocityFvPatchVectorField.H
fluxCorrectedVelocityFvPatchVectorField.C
Definition at line 127 of file fluxCorrectedVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
fluxCorrectedVelocityFvPatchVectorField() [1/4]
fluxCorrectedVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Definition at line 30 of file fluxCorrectedVelocityFvPatchVectorField.C.
fluxCorrectedVelocityFvPatchVectorField() [2/4]
fluxCorrectedVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Definition at line 58 of file fluxCorrectedVelocityFvPatchVectorField.C.
fluxCorrectedVelocityFvPatchVectorField() [3/4]
fluxCorrectedVelocityFvPatchVectorField (const fluxCorrectedVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 43 of file fluxCorrectedVelocityFvPatchVectorField.C.
fluxCorrectedVelocityFvPatchVectorField() [4/4]
fluxCorrectedVelocityFvPatchVectorField (const fluxCorrectedVelocityFvPatchVectorField & fcvpvf, const DimensionedField< vector, volMesh > & iF)
Definition at line 72 of file fluxCorrectedVelocityFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("fluxCorrectedVelocity")
clone() [1/2]
virtual tmp< fvPatchVectorField > clone () const inline virtual
Definition at line 174 of file fluxCorrectedVelocityFvPatchVectorField.H.
clone() [2/2]
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Definition at line 190 of file fluxCorrectedVelocityFvPatchVectorField.H.
evaluate()
void evaluate (const Pstream::commsTypes commsType = Pstream::commsTypes::blocking) virtual
Definition at line 87 of file fluxCorrectedVelocityFvPatchVectorField.C.
References Foam::dimMass, Foam::dimTime, Foam::dimVolume, Foam::exit(), Foam::FatalError, FatalErrorInFunction, n, and Foam::operator==().
write()
void write (Ostream & os) const virtual
Definition at line 126 of file fluxCorrectedVelocityFvPatchVectorField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntryIfDifferent(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/fluxCorrectedVelocity/fluxCorrectedVelocityFvPatchVectorField.H
src/finiteVolume/fields/fvPatchFields/derived/fluxCorrectedVelocity/fluxCorrectedVelocityFvPatchVectorField.C