OpenFOAM: AMIInterpolation Class Reference
AMIInterpolation Class Reference
Interpolation class dealing with transfer of data between two primitive patches with an arbitrary mesh interface (AMI).
#include <AMIInterpolation.H>
Public Member Functions
TypeName ("AMIInterpolation")
declareRunTimeSelectionTable (autoPtr, AMIInterpolation, dict,(const dictionary &dict, const bool reverseTarget),(dict, reverseTarget))
declareRunTimeSelectionTable (autoPtr, AMIInterpolation, component,(const bool requireMatch, const bool reverseTarget, const scalar lowWeightCorrection),(requireMatch, reverseTarget, lowWeightCorrection))
AMIInterpolation (const dictionary &dict, const bool reverseTarget=false)
AMIInterpolation (const bool requireMatch=true, const bool reverseTarget=false, const scalar lowWeightCorrection=-1)
AMIInterpolation (const AMIInterpolation &fineAMI, const labelList &sourceRestrictAddressing, const labelList &neighbourRestrictAddressing)
AMIInterpolation (const AMIInterpolation &ami)
virtual autoPtr< AMIInterpolation > clone () const
virtual ~AMIInterpolation ()=default
bool upToDate () const noexcept
bool upToDate (bool flag) noexcept
bool upToDate () noexcept
bool distributed () const
bool requireMatch () const
bool setRequireMatch (const bool flag)
bool mustMatchFaces () const
bool reverseTarget () const
scalar lowWeightCorrection () const
bool applyLowWeightCorrection () const
label singlePatchProc () const
const List< scalar > & srcMagSf () const
List< scalar > & srcMagSf ()
const labelListList & srcAddress () const
labelListList & srcAddress ()
const scalarListList & srcWeights () const
scalarListList & srcWeights ()
const scalarField & srcWeightsSum () const
scalarField & srcWeightsSum ()
const pointListList & srcCentroids () const
pointListList & srcCentroids ()
const mapDistribute & srcMap () const
const List< scalar > & tgtMagSf () const
List< scalar > & tgtMagSf ()
const labelListList & tgtAddress () const
labelListList & tgtAddress ()
const scalarListList & tgtWeights () const
scalarListList & tgtWeights ()
const scalarField & tgtWeightsSum () const
scalarField & tgtWeightsSum ()
const mapDistribute & tgtMap () const
virtual bool calculate (const primitivePatch &srcPatch, const primitivePatch &tgtPatch, const autoPtr< searchableSurface > &surfPtr=nullptr)
void reset (autoPtr< mapDistribute > &&srcToTgtMap, autoPtr< mapDistribute > &&tgtToSrcMap, labelListList &&srcAddress, scalarListList &&srcWeights, labelListList &&tgtAddress, scalarListList &&tgtWeights)
void append (const primitivePatch &srcPatch, const primitivePatch &tgtPatch)
void normaliseWeights (const bool conformal, const bool output)
template<class Type , class CombineOp >
void interpolateToSource (const UList< Type > &fld, const CombineOp &cop, List< Type > &result, const UList< Type > &defaultValues=UList< Type >::null()) const
template<class Type , class CombineOp >
void interpolateToTarget (const UList< Type > &fld, const CombineOp &cop, List< Type > &result, const UList< Type > &defaultValues=UList< Type >::null()) const
template<class Type , class CombineOp >
tmp< Field< Type > > interpolateToSource (const Field< Type > &fld, const CombineOp &cop, const UList< Type > &defaultValues=UList< Type >::null()) const
template<class Type , class CombineOp >
tmp< Field< Type > > interpolateToSource (const tmp< Field< Type > > &tFld, const CombineOp &cop, const UList< Type > &defaultValues=UList< Type >::null()) const
template<class Type , class CombineOp >
tmp< Field< Type > > interpolateToTarget (const Field< Type > &fld, const CombineOp &cop, const UList< Type > &defaultValues=UList< Type >::null()) const
template<class Type , class CombineOp >
tmp< Field< Type > > interpolateToTarget (const tmp< Field< Type > > &tFld, const CombineOp &cop, const UList< Type > &defaultValues=UList< Type >::null()) const
template<class Type >
tmp< Field< Type > > interpolateToSource (const Field< Type > &fld, const UList< Type > &defaultValues=UList< Type >::null()) const
template<class Type >
tmp< Field< Type > > interpolateToSource (const tmp< Field< Type > > &tFld, const UList< Type > &defaultValues=UList< Type >::null()) const
template<class Type >
tmp< Field< Type > > interpolateToTarget (const Field< Type > &fld, const UList< Type > &defaultValues=UList< Type >::null()) const
template<class Type >
tmp< Field< Type > > interpolateToTarget (const tmp< Field< Type > > &tFld, const UList< Type > &defaultValues=UList< Type >::null()) const
label srcPointFace (const primitivePatch &srcPatch, const primitivePatch &tgtPatch, const vector &n, const label tgtFacei, point &tgtPoint) const
label tgtPointFace (const primitivePatch &srcPatch, const primitivePatch &tgtPatch, const vector &n, const label srcFacei, point &srcPoint) const
bool checkSymmetricWeights (const bool log) const
void writeFaceConnectivity (const primitivePatch &srcPatch, const primitivePatch &tgtPatch, const labelListList &srcAddress) const
virtual void write (Ostream &os) const
template<class Type , class CombineOp >
Foam::tmp< Foam::Field< Type > > interpolateToSource (const Field< Type > &fld, const CombineOp &cop, const UList< Type > &defaultValues) const
template<class Type , class CombineOp >
Foam::tmp< Foam::Field< Type > > interpolateToSource (const tmp< Field< Type > > &tFld, const CombineOp &cop, const UList< Type > &defaultValues) const
template<class Type , class CombineOp >
Foam::tmp< Foam::Field< Type > > interpolateToTarget (const Field< Type > &fld, const CombineOp &cop, const UList< Type > &defaultValues) const
template<class Type , class CombineOp >
Foam::tmp< Foam::Field< Type > > interpolateToTarget (const tmp< Field< Type > > &tFld, const CombineOp &cop, const UList< Type > &defaultValues) const
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolateToSource (const Field< Type > &fld, const UList< Type > &defaultValues) const
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolateToSource (const tmp< Field< Type > > &tFld, const UList< Type > &defaultValues) const
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolateToTarget (const Field< Type > &fld, const UList< Type > &defaultValues) const
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolateToTarget (const tmp< Field< Type > > &tFld, const UList< Type > &defaultValues) const
Static Public Member Functions
static autoPtr< AMIInterpolation > New (const word &modelName, const dictionary &dict, const bool reverseTarget=false)
static autoPtr< AMIInterpolation > New (const word &modelName, const bool requireMatch=true, const bool reverseTarget=false, const scalar lowWeightCorrection=-1)
Static Public Attributes
static bool cacheIntersections_ = false
Protected Types
typedef treeDataPrimitivePatch< primitivePatch > treeType
Protected Member Functions
void operator= (const AMIInterpolation &)=delete
autoPtr< indexedOctree< treeType > > createTree (const primitivePatch &patch) const
label calcDistribution (const primitivePatch &srcPatch, const primitivePatch &tgtPatch) const
void projectPointsToSurface (const searchableSurface &surf, pointField &pts) const
const primitivePatch & srcPatch0 () const
const primitivePatch & tgtPatch0 () const
Static Protected Member Functions
static void normaliseWeights (const scalarList &patchAreas, const word &patchName, const labelListList &addr, scalarListList &wght, scalarField &wghtSum, const bool conformal, const bool output, const scalar lowWeightTol)
static void agglomerate (const autoPtr< mapDistribute > &targetMap, const scalarList &fineSrcMagSf, const labelListList &fineSrcAddress, const scalarListList &fineSrcWeights, const labelList &sourceRestrictAddressing, const labelList &targetRestrictAddressing, scalarList &srcMagSf, labelListList &srcAddress, scalarListList &srcWeights, scalarField &srcWeightsSum, autoPtr< mapDistribute > &tgtMap)
Protected Attributes
bool requireMatch_
const bool reverseTarget_
const scalar lowWeightCorrection_
label singlePatchProc_
scalarList srcMagSf_
labelListList srcAddress_
scalarListList srcWeights_
scalarField srcWeightsSum_
pointListList srcCentroids_
pointField srcPatchPts_
refPtr< primitivePatch > tsrcPatch0_
autoPtr< mapDistribute > srcMapPtr_
scalarList tgtMagSf_
labelListList tgtAddress_
scalarListList tgtWeights_
scalarField tgtWeightsSum_
pointListList tgtCentroids_
pointField tgtPatchPts_
refPtr< primitivePatch > ttgtPatch0_
autoPtr< mapDistribute > tgtMapPtr_
bool upToDate_
Detailed Description
Interpolation class dealing with transfer of data between two primitive patches with an arbitrary mesh interface (AMI).
Based on the algorithm given in:
Conservative interpolation between volume meshes by local Galerkin projection, Farrell PE and Maddison JR, 2011, Comput. Methods Appl. Mech Engrg, Volume 200, Issues 1-4, pp 89-100
Interpolation requires that the two patches should have opposite orientations (opposite normals). The 'reverseTarget' flag can be used to reverse the orientation of the target patch.
Source files
AMIInterpolation.H
AMIInterpolation.C
AMIInterpolationName.C
AMIInterpolationParallelOps.C
Definition at line 75 of file AMIInterpolation.H.
Member Typedef Documentation
treeType
typedef treeDataPrimitivePatch<primitivePatch> treeType protected
Definition at line 87 of file AMIInterpolation.H.
Constructor & Destructor Documentation
AMIInterpolation() [1/4]
AMIInterpolation (const dictionary & dict, const bool reverseTarget = false)
Definition at line 530 of file AMIInterpolation.C.
AMIInterpolation() [2/4]
AMIInterpolation (const bool requireMatch = true, const bool reverseTarget = false, const scalar lowWeightCorrection = -1)
Definition at line 556 of file AMIInterpolation.C.
AMIInterpolation() [3/4]
AMIInterpolation (const AMIInterpolation & fineAMI, const labelList & sourceRestrictAddressing, const labelList & neighbourRestrictAddressing)
Definition at line 585 of file AMIInterpolation.C.
References AMIInterpolation::agglomerate(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::max(), Foam::nl, Foam::Pout, UPtrList< T >::size(), AMIInterpolation::srcAddress_, AMIInterpolation::srcMagSf_, AMIInterpolation::srcMapPtr_, AMIInterpolation::srcWeights_, AMIInterpolation::srcWeightsSum_, AMIInterpolation::tgtAddress_, AMIInterpolation::tgtMagSf_, AMIInterpolation::tgtMapPtr_, AMIInterpolation::tgtWeights_, and AMIInterpolation::tgtWeightsSum_.
AMIInterpolation() [4/4]
AMIInterpolation (const AMIInterpolation & ami)
Definition at line 690 of file AMIInterpolation.C.
~AMIInterpolation()
virtual ~AMIInterpolation () virtual default
Member Function Documentation
operator=()
void operator= (const AMIInterpolation &) protected delete
createTree()
Foam::autoPtr< Foam::indexedOctree< Foam::AMIInterpolation::treeType > > createTree (const primitivePatch & patch) const protected
Definition at line 45 of file AMIInterpolation.C.
References boundBox::inflate(), and AMIInterpolation::New().
calcDistribution()
Foam::label calcDistribution (const primitivePatch & srcPatch, const primitivePatch & tgtPatch) const protected
Definition at line 69 of file AMIInterpolation.C.
References Pstream::broadcast(), UPtrList< T >::count(), DebugInFunction, Foam::endl(), and UPstream::parRun().
projectPointsToSurface()
void projectPointsToSurface (const searchableSurface & surf, pointField & pts) const protected
Definition at line 110 of file AMIInterpolation.C.
References Foam::abort(), addProfiling, DebugInfo, Foam::endl(), Foam::FatalError, FatalErrorInFunction, searchableSurface::findNearest(), forAll, pts, and UPtrList< T >::size().
srcPatch0()
const Foam::primitivePatch & srcPatch0 () const inline protected
Definition at line 22 of file AMIInterpolationI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and AMIInterpolation::tsrcPatch0_.
tgtPatch0()
const Foam::primitivePatch & tgtPatch0 () const inline protected
Definition at line 35 of file AMIInterpolationI.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
normaliseWeights() [1/2]
void normaliseWeights (const scalarList & patchAreas, const word & patchName, const labelListList & addr, scalarListList & wght, scalarField & wghtSum, const bool conformal, const bool output, const scalar lowWeightTol) static protected
Definition at line 150 of file AMIInterpolation.C.
References addProfiling, Foam::endl(), forAll, Foam::gAverage(), Foam::gMax(), Foam::gMin(), Foam::indent(), Foam::Info, Foam::nl, Foam::output(), Foam::returnReduce(), Foam::returnReduceOr(), s(), PtrList< T >::setSize(), UPtrList< T >::size(), UList< T >::size(), and Foam::sum().
agglomerate()
void agglomerate (const autoPtr< mapDistribute > & targetMap, const scalarList & fineSrcMagSf, const labelListList & fineSrcAddress, const scalarListList & fineSrcWeights, const labelList & sourceRestrictAddressing, const labelList & targetRestrictAddressing, scalarList & srcMagSf, labelListList & srcAddress, scalarListList & srcWeights, scalarField & srcWeightsSum, autoPtr< mapDistribute > & tgtMap) static protected
Definition at line 226 of file AMIInterpolation.C.
References addProfiling, PtrList< T >::append(), mapDistributeBase::constructMap(), mapDistributeBase::constructSize(), mapDistribute::distribute(), forAll, Foam::identity(), Foam::labelMin, Foam::max(), UPstream::myProcNo(), UPstream::nProcs(), List< T >::setSize(), PtrList< T >::setSize(), UPtrList< T >::size(), and mapDistributeBase::subMap().
Referenced by AMIInterpolation::AMIInterpolation().
TypeName()
TypeName ("AMIInterpolation")
declareRunTimeSelectionTable() [1/2]
declareRunTimeSelectionTable (autoPtr , AMIInterpolation , dict , (const dictionary &dict, const bool reverseTarget) , (dict, reverseTarget))
declareRunTimeSelectionTable() [2/2]
declareRunTimeSelectionTable (autoPtr , AMIInterpolation , component , (const bool requireMatch, const bool reverseTarget, const scalar lowWeightCorrection) , (requireMatch, reverseTarget, lowWeightCorrection))
New() [1/2]
Foam::autoPtr< Foam::AMIInterpolation > New (const word & modelName, const dictionary & dict, const bool reverseTarget = false) static
Definition at line 25 of file AMIInterpolationNew.C.
References DebugInfo, dict, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInLookup, and AMIInterpolation::reverseTarget().
Referenced by AMIInterpolation::createTree(), and regionModel::interRegionAMI().
New() [2/2]
Foam::autoPtr< Foam::AMIInterpolation > New (const word & modelName, const bool requireMatch = true, const bool reverseTarget = false, const scalar lowWeightCorrection = -1) static
Definition at line 50 of file AMIInterpolationNew.C.
References DebugInfo, Foam::endl(), Foam::exit(), Foam::FatalError, and FatalErrorInLookup.
clone()
virtual autoPtr< AMIInterpolation > clone () const inline virtual
Reimplemented in advancingFrontAMI, faceAreaWeightAMI, faceAreaWeightAMI2D, and nearestFaceAMI.
Definition at line 334 of file AMIInterpolation.H.
References autoPtr< T >::New().
upToDate() [1/3]
bool upToDate () const inline noexcept
Definition at line 349 of file AMIInterpolation.H.
References AMIInterpolation::upToDate_.
upToDate() [2/3]
bool upToDate (bool flag) inline noexcept
Definition at line 352 of file AMIInterpolation.H.
References AMIInterpolation::upToDate_.
upToDate() [3/3]
bool upToDate () inline noexcept
Definition at line 361 of file AMIInterpolation.H.
References AMIInterpolation::upToDate_.
distributed()
bool distributed () const inline
Definition at line 49 of file AMIInterpolationI.H.
Referenced by AMIInterpolation::interpolateToTarget().
requireMatch()
bool requireMatch () const inline
Definition at line 55 of file AMIInterpolationI.H.
setRequireMatch()
bool setRequireMatch (const bool flag) inline
Definition at line 61 of file AMIInterpolationI.H.
mustMatchFaces()
bool mustMatchFaces () const inline
Definition at line 68 of file AMIInterpolationI.H.
Referenced by faceAreaWeightAMI::calcAddressing().
reverseTarget()
bool reverseTarget () const inline
Definition at line 74 of file AMIInterpolationI.H.
Referenced by AMIInterpolation::New().
lowWeightCorrection()
Foam::scalar lowWeightCorrection () const inline
Definition at line 80 of file AMIInterpolationI.H.
applyLowWeightCorrection()
bool applyLowWeightCorrection () const inline
Definition at line 86 of file AMIInterpolationI.H.
singlePatchProc()
Foam::label singlePatchProc () const inline
Definition at line 92 of file AMIInterpolationI.H.
srcMagSf() [1/2]
const Foam::List< Foam::scalar > & srcMagSf () const inline
Definition at line 98 of file AMIInterpolationI.H.
srcMagSf() [2/2]
Foam::List< Foam::scalar > & srcMagSf () inline
Definition at line 104 of file AMIInterpolationI.H.
srcAddress() [1/2]
const Foam::labelListList & srcAddress () const inline
Definition at line 110 of file AMIInterpolationI.H.
Referenced by mappedPatchFieldBase< Type >::distribute().
srcAddress() [2/2]
Foam::labelListList & srcAddress () inline
Definition at line 116 of file AMIInterpolationI.H.
srcWeights() [1/2]
const Foam::scalarListList & srcWeights () const inline
Definition at line 122 of file AMIInterpolationI.H.
Referenced by mappedPatchFieldBase< Type >::distribute().
srcWeights() [2/2]
Foam::scalarListList & srcWeights () inline
Definition at line 128 of file AMIInterpolationI.H.
srcWeightsSum() [1/2]
const Foam::scalarField & srcWeightsSum () const inline
Definition at line 134 of file AMIInterpolationI.H.
Referenced by cyclicACMIPolyPatch::resetAMI().
srcWeightsSum() [2/2]
Foam::scalarField & srcWeightsSum () inline
Definition at line 140 of file AMIInterpolationI.H.
srcCentroids() [1/2]
const Foam::pointListList & srcCentroids () const inline
Definition at line 146 of file AMIInterpolationI.H.
srcCentroids() [2/2]
Foam::pointListList & srcCentroids () inline
Definition at line 152 of file AMIInterpolationI.H.
srcMap()
const Foam::mapDistribute & srcMap () const inline
Definition at line 158 of file AMIInterpolationI.H.
Referenced by mappedPatchFieldBase< Type >::distribute().
tgtMagSf() [1/2]
const Foam::List< Foam::scalar > & tgtMagSf () const inline
Definition at line 164 of file AMIInterpolationI.H.
tgtMagSf() [2/2]
Foam::List< Foam::scalar > & tgtMagSf () inline
Definition at line 170 of file AMIInterpolationI.H.
tgtAddress() [1/2]
const Foam::labelListList & tgtAddress () const inline
Definition at line 176 of file AMIInterpolationI.H.
Referenced by mappedPatchFieldBase< Type >::distribute().
tgtAddress() [2/2]
Foam::labelListList & tgtAddress () inline
Definition at line 182 of file AMIInterpolationI.H.
tgtWeights() [1/2]
const Foam::scalarListList & tgtWeights () const inline
Definition at line 188 of file AMIInterpolationI.H.
Referenced by mappedPatchFieldBase< Type >::distribute().
tgtWeights() [2/2]
Foam::scalarListList & tgtWeights () inline
Definition at line 194 of file AMIInterpolationI.H.
tgtWeightsSum() [1/2]
const Foam::scalarField & tgtWeightsSum () const inline
Definition at line 200 of file AMIInterpolationI.H.
Referenced by cyclicACMIPolyPatch::resetAMI().
tgtWeightsSum() [2/2]
Foam::scalarField & tgtWeightsSum () inline
Definition at line 206 of file AMIInterpolationI.H.
tgtMap()
const Foam::mapDistribute & tgtMap () const inline
Definition at line 212 of file AMIInterpolationI.H.
Referenced by mappedPatchFieldBase< Type >::distribute().
calculate()
bool calculate (const primitivePatch & srcPatch, const primitivePatch & tgtPatch, const autoPtr< searchableSurface > & surfPtr = nullptr) virtual
Reimplemented in advancingFrontAMI, faceAreaWeightAMI, faceAreaWeightAMI2D, and nearestFaceAMI.
Definition at line 714 of file AMIInterpolation.C.
References addProfiling, DebugInfo, Foam::endl(), Foam::indent(), Foam::Info, refPtr< T >::New(), Foam::nl, PrimitivePatch< FaceList, PointField >::points(), and Foam::returnReduce().
Referenced by advancingFrontAMI::calculate(), and nearestFaceAMI::calculate().
reset()
void reset (autoPtr< mapDistribute > && srcToTgtMap, autoPtr< mapDistribute > && tgtToSrcMap, labelListList && srcAddress, scalarListList && srcWeights, labelListList && tgtAddress, scalarListList && tgtWeights)
Definition at line 780 of file AMIInterpolation.C.
References DebugInFunction, Foam::endl(), forAll, and Foam::sum().
append()
void append (const primitivePatch & srcPatch, const primitivePatch & tgtPatch)
Definition at line 817 of file AMIInterpolation.C.
References addProfiling, PtrList< T >::append(), forAll, Foam::identity(), and UPtrList< T >::size().
normaliseWeights() [2/2]
void normaliseWeights (const bool conformal, const bool output)
Definition at line 996 of file AMIInterpolation.C.
References Foam::output().
interpolateToSource() [1/9]
template<class Type , class CombineOp > void interpolateToSource (const UList< Type > & fld, const CombineOp & cop, List< Type > & result, const UList< Type > & defaultValues = UList<Type>::null()) const
Definition at line 114 of file AMIInterpolationTemplates.C.
References Foam::abort(), addProfiling, mapDistribute::distribute(), Foam::FatalError, FatalErrorInFunction, fld(), forAll, Foam::nl, PtrList< T >::setSize(), and UPtrList< T >::size().
interpolateToTarget() [1/9]
template<class Type , class CombineOp > void interpolateToTarget (const UList< Type > & fld, const CombineOp & cop, List< Type > & result, const UList< Type > & defaultValues = UList<Type>::null()) const
Definition at line 28 of file AMIInterpolationTemplates.C.
References Foam::abort(), addProfiling, mapDistribute::distribute(), AMIInterpolation::distributed(), Foam::FatalError, FatalErrorInFunction, fld(), forAll, AMIInterpolation::lowWeightCorrection_, Foam::nl, PtrList< T >::setSize(), UPtrList< T >::size(), UList< T >::size(), AMIInterpolation::srcAddress_, AMIInterpolation::srcMapPtr_, AMIInterpolation::tgtAddress_, AMIInterpolation::tgtWeights_, and AMIInterpolation::tgtWeightsSum_.
interpolateToSource() [2/9]
template<class Type , class CombineOp > tmp< Field< Type > > interpolateToSource (const Field< Type > & fld, const CombineOp & cop, const UList< Type > & defaultValues = UList< Type >::null()) const
interpolateToSource() [3/9]
template<class Type , class CombineOp > tmp< Field< Type > > interpolateToSource (const tmp< Field< Type > > & tFld, const CombineOp & cop, const UList< Type > & defaultValues = UList< Type >::null()) const
interpolateToTarget() [2/9]
template<class Type , class CombineOp > tmp< Field< Type > > interpolateToTarget (const Field< Type > & fld, const CombineOp & cop, const UList< Type > & defaultValues = UList< Type >::null()) const
interpolateToTarget() [3/9]
template<class Type , class CombineOp > tmp< Field< Type > > interpolateToTarget (const tmp< Field< Type > > & tFld, const CombineOp & cop, const UList< Type > & defaultValues = UList< Type >::null()) const
interpolateToSource() [4/9]
template<class Type > tmp< Field< Type > > interpolateToSource (const Field< Type > & fld, const UList< Type > & defaultValues = UList< Type >::null()) const
interpolateToSource() [5/9]
template<class Type > tmp< Field< Type > > interpolateToSource (const tmp< Field< Type > > & tFld, const UList< Type > & defaultValues = UList< Type >::null()) const
interpolateToTarget() [4/9]
template<class Type > tmp< Field< Type > > interpolateToTarget (const Field< Type > & fld, const UList< Type > & defaultValues = UList< Type >::null()) const
interpolateToTarget() [5/9]
template<class Type > tmp< Field< Type > > interpolateToTarget (const tmp< Field< Type > > & tFld, const UList< Type > & defaultValues = UList< Type >::null()) const
srcPointFace()
Foam::label srcPointFace (const primitivePatch & srcPatch, const primitivePatch & tgtPatch, const vector & n, const label tgtFacei, point & tgtPoint) const
Definition at line 1028 of file AMIInterpolation.C.
References PointHit< PointType >::distance(), PointHit< PointType >::eligibleMiss(), f(), PointHit< PointType >::hit(), n, PointHit< PointType >::point(), PrimitivePatch< FaceList, PointField >::points(), PointHit< PointType >::setDistance(), and intersection::VISIBLE.
tgtPointFace()
Foam::label tgtPointFace (const primitivePatch & srcPatch, const primitivePatch & tgtPatch, const vector & n, const label srcFacei, point & srcPoint) const
Definition at line 1077 of file AMIInterpolation.C.
References PointHit< PointType >::distance(), PointHit< PointType >::eligibleMiss(), f(), PointHit< PointType >::hit(), n, PointHit< PointType >::point(), PrimitivePatch< FaceList, PointField >::points(), PointHit< PointType >::setDistance(), and intersection::VISIBLE.
checkSymmetricWeights()
bool checkSymmetricWeights (const bool log) const
Definition at line 1126 of file AMIInterpolation.C.
References Foam::endl(), forAll, found, Log, Foam::nl, and UPstream::parRun().
writeFaceConnectivity()
void writeFaceConnectivity (const primitivePatch & srcPatch, const primitivePatch & tgtPatch, const labelListList & srcAddress) const
Definition at line 1189 of file AMIInterpolation.C.
References Foam::endl(), PrimitivePatch< FaceList, PointField >::faceCentres(), forAll, UPstream::myProcNo(), Foam::name(), os(), and Foam::meshTools::writeOBJ().
write()
void write (Ostream & os) const virtual
Reimplemented in advancingFrontAMI, faceAreaWeightAMI, faceAreaWeightAMI2D, and nearestFaceAMI.
Definition at line 1221 of file AMIInterpolation.C.
References os(), Foam::type(), and Ostream::writeEntry().
Referenced by advancingFrontAMI::write(), and nearestFaceAMI::write().
interpolateToSource() [6/9]
template<class Type , class CombineOp > Foam::tmp< Foam::Field< Type > > interpolateToSource (const Field< Type > & fld, const CombineOp & cop, const UList< Type > & defaultValues) const
Definition at line 200 of file AMIInterpolationTemplates.C.
References fld(), Foam::New(), and Foam::Zero.
interpolateToSource() [7/9]
template<class Type , class CombineOp > Foam::tmp< Foam::Field< Type > > interpolateToSource (const tmp< Field< Type > > & tFld, const CombineOp & cop, const UList< Type > & defaultValues) const
Definition at line 222 of file AMIInterpolationTemplates.C.
interpolateToTarget() [6/9]
template<class Type , class CombineOp > Foam::tmp< Foam::Field< Type > > interpolateToTarget (const Field< Type > & fld, const CombineOp & cop, const UList< Type > & defaultValues) const
Definition at line 234 of file AMIInterpolationTemplates.C.
References fld(), Foam::New(), and Foam::Zero.
interpolateToTarget() [7/9]
template<class Type , class CombineOp > Foam::tmp< Foam::Field< Type > > interpolateToTarget (const tmp< Field< Type > > & tFld, const CombineOp & cop, const UList< Type > & defaultValues) const
Definition at line 256 of file AMIInterpolationTemplates.C.
interpolateToSource() [8/9]
template<class Type > Foam::tmp< Foam::Field< Type > > interpolateToSource (const Field< Type > & fld, const UList< Type > & defaultValues) const
Definition at line 268 of file AMIInterpolationTemplates.C.
References fld().
interpolateToSource() [9/9]
template<class Type > Foam::tmp< Foam::Field< Type > > interpolateToSource (const tmp< Field< Type > > & tFld, const UList< Type > & defaultValues) const
Definition at line 279 of file AMIInterpolationTemplates.C.
interpolateToTarget() [8/9]
template<class Type > Foam::tmp< Foam::Field< Type > > interpolateToTarget (const Field< Type > & fld, const UList< Type > & defaultValues) const
Definition at line 290 of file AMIInterpolationTemplates.C.
References fld().
interpolateToTarget() [9/9]
template<class Type > Foam::tmp< Foam::Field< Type > > interpolateToTarget (const tmp< Field< Type > > & tFld, const UList< Type > & defaultValues) const
Definition at line 301 of file AMIInterpolationTemplates.C.
Member Data Documentation
cacheIntersections_
bool cacheIntersections_ = false static
Definition at line 81 of file AMIInterpolation.H.
Referenced by faceAreaWeightAMI::calcInterArea(), and faceAreaWeightAMI::overlaps().
requireMatch_
bool requireMatch_ protected
Definition at line 93 of file AMIInterpolation.H.
Referenced by advancingFrontAMI::checkPatches().
reverseTarget_
const bool reverseTarget_ protected
Definition at line 97 of file AMIInterpolation.H.
lowWeightCorrection_
const scalar lowWeightCorrection_ protected
Definition at line 100 of file AMIInterpolation.H.
Referenced by AMIInterpolation::interpolateToTarget().
singlePatchProc_
label singlePatchProc_ protected
Definition at line 104 of file AMIInterpolation.H.
srcMagSf_
scalarList srcMagSf_ protected
Definition at line 110 of file AMIInterpolation.H.
Referenced by AMIInterpolation::AMIInterpolation().
srcAddress_
labelListList srcAddress_ protected
Definition at line 113 of file AMIInterpolation.H.
Referenced by AMIInterpolation::AMIInterpolation(), and AMIInterpolation::interpolateToTarget().
srcWeights_
scalarListList srcWeights_ protected
Definition at line 116 of file AMIInterpolation.H.
Referenced by AMIInterpolation::AMIInterpolation().
srcWeightsSum_
scalarField srcWeightsSum_ protected
Definition at line 119 of file AMIInterpolation.H.
Referenced by AMIInterpolation::AMIInterpolation().
srcCentroids_
pointListList srcCentroids_ protected
Definition at line 122 of file AMIInterpolation.H.
srcPatchPts_
pointField srcPatchPts_ protected
Definition at line 126 of file AMIInterpolation.H.
tsrcPatch0_
refPtr<primitivePatch> tsrcPatch0_ protected
Definition at line 129 of file AMIInterpolation.H.
Referenced by advancingFrontAMI::srcPatch(), and AMIInterpolation::srcPatch0().
srcMapPtr_
autoPtr<mapDistribute> srcMapPtr_ protected
Definition at line 132 of file AMIInterpolation.H.
Referenced by AMIInterpolation::AMIInterpolation(), and AMIInterpolation::interpolateToTarget().
tgtMagSf_
scalarList tgtMagSf_ protected
Definition at line 139 of file AMIInterpolation.H.
Referenced by AMIInterpolation::AMIInterpolation().
tgtAddress_
labelListList tgtAddress_ protected
Definition at line 142 of file AMIInterpolation.H.
Referenced by AMIInterpolation::AMIInterpolation(), and AMIInterpolation::interpolateToTarget().
tgtWeights_
scalarListList tgtWeights_ protected
Definition at line 145 of file AMIInterpolation.H.
Referenced by AMIInterpolation::AMIInterpolation(), and AMIInterpolation::interpolateToTarget().
tgtWeightsSum_
scalarField tgtWeightsSum_ protected
Definition at line 148 of file AMIInterpolation.H.
Referenced by AMIInterpolation::AMIInterpolation(), and AMIInterpolation::interpolateToTarget().
tgtCentroids_
pointListList tgtCentroids_ protected
Definition at line 151 of file AMIInterpolation.H.
tgtPatchPts_
pointField tgtPatchPts_ protected
Definition at line 155 of file AMIInterpolation.H.
ttgtPatch0_
refPtr<primitivePatch> ttgtPatch0_ protected
Definition at line 158 of file AMIInterpolation.H.
tgtMapPtr_
autoPtr<mapDistribute> tgtMapPtr_ protected
Definition at line 161 of file AMIInterpolation.H.
Referenced by AMIInterpolation::AMIInterpolation().
upToDate_
bool upToDate_ protected
Definition at line 164 of file AMIInterpolation.H.
Referenced by AMIInterpolation::upToDate(), AMIInterpolation::upToDate(), and AMIInterpolation::upToDate().
The documentation for this class was generated from the following files:
src/meshTools/AMIInterpolation/AMIInterpolation/AMIInterpolation.H
src/meshTools/AMIInterpolation/AMIInterpolation/AMIInterpolation.C
src/meshTools/AMIInterpolation/AMIInterpolation/AMIInterpolationI.H
src/meshTools/AMIInterpolation/AMIInterpolation/AMIInterpolationNew.C
src/meshTools/AMIInterpolation/AMIInterpolation/AMIInterpolationTemplates.C