OpenFOAM: integrationScheme Class Reference
integrationScheme Class Reference abstract
Base for a set of schemes which integrate simple ODEs which arise from semi-implcit rate expressions.
#include <integrationScheme.H>
Public Member Functions
TypeName ("integrationScheme")
declareRunTimeSelectionTable (autoPtr, integrationScheme, word,(),())
integrationScheme ()
virtual autoPtr< integrationScheme > clone () const =0
virtual ~integrationScheme ()
template<class Type >
Type delta (const Type &phi, const scalar dt, const Type &Alpha, const scalar Beta) const
template<class Type >
Type partialDelta (const Type &phi, const scalar dt, const Type &Alpha, const scalar Beta, const Type &alphai, const scalar betai) const
virtual scalar dtEff (const scalar dt, const scalar Beta) const =0
virtual scalar sumDtEff (const scalar dt, const scalar Beta) const =0
Static Public Member Functions
static autoPtr< integrationScheme > New (const word &phiName, const dictionary &dict)
template<class Type >
static Type explicitDelta (const Type &phi, const scalar dtEff, const Type &Alpha, const scalar Beta)
Detailed Description
Base for a set of schemes which integrate simple ODEs which arise from semi-implcit rate expressions.
The methods are defined in terms of the effective time-step by which the explicit rate is multiplied. The effective time-step is a function of the actual time step and the implicit coefficient, which must be implemented in each derived scheme.
This class also facilitates integration in stages. If the explicit and implicit coefficients, and , are a summation of differing contributions, and , then the integration can be split up to determine the effect of each contribution.
These partial calculations are defined in terms of the integral of the effective time-step, , which is also implemented in every derivation.
Source files
integrationScheme.H
integrationScheme.C
Definition at line 86 of file integrationScheme.H.
Constructor & Destructor Documentation
integrationScheme()
integrationScheme ()
Definition at line 33 of file integrationScheme.C.
~integrationScheme()
~integrationScheme () virtual
Definition at line 39 of file integrationScheme.C.
Member Function Documentation
TypeName()
TypeName ("integrationScheme")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , integrationScheme , word , () , ())
clone()
virtual autoPtr< integrationScheme > clone () const pure virtual
Implemented in analytical, and Euler.
New()
Foam::autoPtr< Foam::integrationScheme > New (const word & phiName, const dictionary & dict) static
Definition at line 27 of file integrationSchemeNew.C.
References Foam::abort(), dict, Foam::endl(), Foam::FatalIOError, FatalIOErrorInLookup, and Foam::Info.
Referenced by KinematicCloud< CloudType >::setModels(), and ThermoCloud< CloudType >::setModels().
explicitDelta()
template<class Type > Type explicitDelta (const Type & phi, const scalar dtEff, const Type & Alpha, const scalar Beta) inline static
Definition at line 26 of file integrationSchemeTemplates.C.
References integrationScheme::dtEff(), and phi.
delta()
template<class Type > Type delta (const Type & phi, const scalar dt, const Type & Alpha, const scalar Beta) const inline
Definition at line 39 of file integrationSchemeTemplates.C.
References phi.
partialDelta()
template<class Type > Type partialDelta (const Type & phi, const scalar dt, const Type & Alpha, const scalar Beta, const Type & alphai, const scalar betai) const inline
Definition at line 52 of file integrationSchemeTemplates.C.
References phi.
dtEff()
virtual scalar dtEff (const scalar dt, const scalar Beta) const pure virtual
Implemented in analytical, and Euler.
Referenced by integrationScheme::explicitDelta().
sumDtEff()
virtual scalar sumDtEff (const scalar dt, const scalar Beta) const pure virtual
Implemented in analytical, and Euler.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/integrationScheme/integrationScheme/integrationScheme.H
src/lagrangian/intermediate/integrationScheme/integrationScheme/integrationScheme.C
src/lagrangian/intermediate/integrationScheme/integrationScheme/integrationSchemeNew.C
src/lagrangian/intermediate/integrationScheme/integrationScheme/integrationSchemeTemplates.C