OpenFOAM: fvBoundaryMesh Class Reference
fvBoundaryMesh Class Reference
Foam::fvBoundaryMesh.
#include <fvBoundaryMesh.H>
Public Member Functions
fvBoundaryMesh (const fvMesh &)
fvBoundaryMesh (const fvMesh &, const polyBoundaryMesh &)
const fvMesh & mesh () const noexcept
UPtrList< const labelUList > faceCells () const
lduInterfacePtrsList interfaces () const
labelList indices (const wordRe &matcher, const bool useGroups) const
labelList indices (const wordRes &matcher, const bool useGroups) const
label findPatchID (const word &patchName) const
void movePoints ()
const fvPatch & operator[] (const word &patchName) const
fvPatch & operator[] (const word &patchName)
labelList findIndices (const wordRe &key, bool useGroups) const
Public Member Functions inherited from PtrList< T >
constexpr PtrList () noexcept
PtrList (const label len)
PtrList (const PtrList< T > &list)
PtrList (PtrList< T > &&list)
PtrList (UList< T * > &list)
template<class CloneArg >
PtrList (const PtrList< T > &list, const CloneArg &cloneArgs)
PtrList (PtrList< T > &list, bool reuse)
PtrList (const SLPtrList< T > &list)
template<class INew >
PtrList (Istream &is, const INew &inew)
PtrList (Istream &is)
~PtrList ()
template<class... Args>
PtrList< T > clone (Args &&... args) const
const T * set (const label i) const
void clear ()
void free ()
void resize (const label newLen)
template<class... Args>
T & emplace_back (Args &&... args)
void push_back (T *ptr)
void push_back (std::unique_ptr< T > &&ptr)
void push_back (autoPtr< T > &&ptr)
void push_back (const refPtr< T > &ptr)
void push_back (const tmp< T > &ptr)
void push_back (PtrList< T > &&other)
template<class... Args>
T & emplace_set (const label i, Args &&... args)
template<class... Args>
T & emplace (const label i, Args &&... args)
autoPtr< T > set (const label i, T *ptr)
autoPtr< T > set (const label i, std::unique_ptr< T > &&ptr)
autoPtr< T > set (const label i, autoPtr< T > &&ptr)
autoPtr< T > set (const label i, const refPtr< T > &ptr)
autoPtr< T > set (const label i, const tmp< T > &ptr)
autoPtr< T > release (const label i)
void transfer (PtrList< T > &list)
void operator= (const PtrList< T > &list)
void operator= (PtrList< T > &&list)
void push_back (autoPtr< T > &ptr)=delete
autoPtr< T > set (const label i, autoPtr< T > &ptr)
void setSize (const label newLen)
void append (autoPtr< T > &ptr)
void append (T *ptr)
void append (std::unique_ptr< T > &&ptr)
void append (autoPtr< T > &&ptr)
void append (const refPtr< T > &ptr)
void append (const tmp< T > &ptr)
void append (PtrList< T > &&other)
template<class... Args>
Foam::PtrList< T > clone (Args &&... args) const
Public Member Functions inherited from UPtrList< T >
constexpr UPtrList () noexcept
UPtrList (const label len)
UPtrList (const UPtrList< T > &list)
UPtrList (UPtrList< T > &&list)
UPtrList (UPtrList< T > &list, bool reuse)
UPtrList (PtrList< T > &list)
UPtrList (const UList< T * > &list)
UPtrList (UList< T > &list)
bool empty () const noexcept
label size () const noexcept
label count () const noexcept
T & front ()
const T & front () const
T & back ()
const T & back () const
const T * test (const label i) const
const T * get (const label i) const
T * get (const label i)
const T * set (const label i) const
void clear ()
void free ()
void resize (const label newLen)
label squeezeNull ()
void trimTrailingNull ()
void push_back (T *ptr)
void push_back (UPtrList< T > &&other)
void swap (UPtrList< T > &list)
void transfer (UPtrList< T > &list)
T * set (const label i, T *ptr)
void reorder (const labelUList &oldToNew, const bool check=false)
void sortOrder (const labelUList &order, const bool check=false)
void checkNonNull () const
const T & at (const label i) const
T & at (const label i)
const T & operator[] (const label i) const
T & operator[] (const label i)
FOAM_DEPRECATED_FOR (2022-09, "get(), set() or test() methods") const T *operator()(const label i) const
void operator= (const UPtrList< T > &list)
void operator= (UPtrList< T > &&list)
T ** begin_ptr () noexcept
T ** end_ptr () noexcept
iterator begin ()
iterator end () noexcept
const_iterator cbegin () const
const_iterator cend () const noexcept
const_iterator begin () const
const_iterator end () const noexcept
void setSize (const label n)
T & first ()
const T & first () const
T & last ()
const T & last () const
void append (T *ptr)
void append (UPtrList< T > &&other)
Protected Member Functions
void readUpdate (const polyBoundaryMesh &)
Protected Member Functions inherited from PtrList< T >
template<class INew >
void readIstream (Istream &is, const INew &inew)
Protected Member Functions inherited from UPtrList< T >
void setAddressableSize (const label n) noexcept
label find_next (label pos) const
UPtrList (Detail::PtrListDetail< T > &&ptrs)
Friends
class fvMesh
Additional Inherited Members
Public Types inherited from UPtrList< T >
typedef T value_type
typedef T & reference
typedef const T & const_reference
Protected Attributes inherited from UPtrList< T >
Detail::PtrListDetail< T > ptrs_
Detailed Description
Foam::fvBoundaryMesh.
Source files
fvBoundaryMesh.H
fvBoundaryMesh.C
Definition at line 53 of file fvBoundaryMesh.H.
Constructor & Destructor Documentation
fvBoundaryMesh() [1/2]
fvBoundaryMesh (const fvMesh & m) explicit
Definition at line 44 of file fvBoundaryMesh.C.
fvBoundaryMesh() [2/2]
fvBoundaryMesh (const fvMesh & m, const polyBoundaryMesh & basicBdry)
Definition at line 54 of file fvBoundaryMesh.C.
Member Function Documentation
readUpdate()
void readUpdate (const polyBoundaryMesh & basicBdry) protected
Definition at line 167 of file fvBoundaryMesh.C.
References clear().
mesh()
const fvMesh & mesh () const inline noexcept
Definition at line 99 of file fvBoundaryMesh.H.
faceCells()
Foam::UPtrList< const Foam::labelUList > faceCells () const
Definition at line 130 of file fvBoundaryMesh.C.
References forAll, patches, PtrList< T >::set(), and UPtrList< T >::size().
Referenced by cellCellStencil::setUpFrontOnOversetPatch().
interfaces()
Foam::lduInterfacePtrsList interfaces () const
Definition at line 145 of file fvBoundaryMesh.C.
References forAll, patches, UPtrList< T >::set(), and UPtrList< T >::size().
indices() [1/2]
Foam::labelList indices (const wordRe & matcher, const bool useGroups) const
Definition at line 69 of file fvBoundaryMesh.C.
References polyMesh::boundaryMesh(), and mesh.
Referenced by fvBoundaryMesh::findIndices().
indices() [2/2]
Foam::labelList indices (const wordRes & matcher, const bool useGroups) const
Definition at line 79 of file fvBoundaryMesh.C.
References polyMesh::boundaryMesh(), and mesh.
findPatchID()
Foam::label findPatchID (const word & patchName) const
Definition at line 89 of file fvBoundaryMesh.C.
References forAll, Foam::name(), and patches.
movePoints()
void movePoints ()
Definition at line 113 of file fvBoundaryMesh.C.
References p, and patches.
operator[]() [1/2]
const Foam::fvPatch & operator[] (const word & patchName) const
Definition at line 176 of file fvBoundaryMesh.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and Foam::nl.
operator[]() [2/2]
Foam::fvPatch & operator[] (const word & patchName)
Definition at line 194 of file fvBoundaryMesh.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and Foam::nl.
findIndices()
labelList findIndices (const wordRe & key, bool useGroups) const inline
Definition at line 143 of file fvBoundaryMesh.H.
References fvBoundaryMesh::indices().
Friends And Related Symbol Documentation
fvMesh
friend class fvMesh friend
Definition at line 84 of file fvBoundaryMesh.H.
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/fvBoundaryMesh/fvBoundaryMesh.H
src/finiteVolume/fvMesh/fvBoundaryMesh/fvBoundaryMesh.C