OpenFOAM: extendedEdgeMesh Class Reference
extendedEdgeMesh Class Reference
Description of feature edges and points.
#include <extendedEdgeMesh.H>
Public Types
enum pointStatus { CONVEX , CONCAVE , MIXED , NONFEATURE }
enum edgeStatus {
EXTERNAL , INTERNAL , FLAT , OPEN ,
MULTIPLE , NONE
}
enum sideVolumeType { INSIDE = 0 , OUTSIDE = 1 , BOTH = 2 , NEITHER = 3 }
Public Types inherited from GeoMesh< faMesh >
typedef faMesh Mesh
typedef MESH::BoundaryMesh BoundaryMesh
Public Member Functions
TypeName ("extendedEdgeMesh")
extendedEdgeMesh ()
extendedEdgeMesh (const extendedEdgeMesh &fem)
extendedEdgeMesh (const fileName &name)
extendedEdgeMesh (const fileName &name, const word &fileType)
extendedEdgeMesh (Istream &is)
extendedEdgeMesh (const pointField &points, const edgeList &edges)
extendedEdgeMesh (pointField &&points, edgeList &&edges)
extendedEdgeMesh (const surfaceFeatures &sFeat, const boolList &surfBaffleRegions)
extendedEdgeMesh (const PrimitivePatch< faceList, pointField > &surf, const labelUList &featureEdges, const labelUList &regionFeatureEdges, const labelUList &featurePoints)
extendedEdgeMesh (const pointField &pts, const edgeList &eds, label concaveStart, label mixedStart, label nonFeatureStart, label internalStart, label flatStart, label openStart, label multipleStart, const vectorField &normals, const List< sideVolumeType > &normalVolumeTypes, const vectorField &edgeDirections, const labelListList &normalDirections, const labelListList &edgeNormals, const labelListList &featurePointNormals, const labelListList &featurePointEdges, const labelList &regionEdges)
declareRunTimeSelectionTable (autoPtr, extendedEdgeMesh, fileExtension,(const fileName &name),(name))
~extendedEdgeMesh ()=default
void nearestFeaturePoint (const point &sample, scalar searchDistSqr, pointIndexHit &info) const
void nearestFeatureEdge (const point &sample, scalar searchDistSqr, pointIndexHit &info) const
void nearestFeatureEdge (const pointField &samples, const scalarField &searchDistSqr, List< pointIndexHit > &info) const
void nearestFeatureEdgeByType (const point &sample, const scalarField &searchDistSqr, List< pointIndexHit > &info) const
void allNearestFeaturePoints (const point &sample, scalar searchRadiusSqr, List< pointIndexHit > &info) const
void allNearestFeatureEdges (const point &sample, const scalar searchRadiusSqr, List< pointIndexHit > &info) const
label convexStart () const
label concaveStart () const
label mixedStart () const
label nonFeatureStart () const
label externalStart () const
label internalStart () const
label flatStart () const
label openStart () const
label multipleStart () const
bool featurePoint (label ptI) const
const vectorField & normals () const
const List< sideVolumeType > & normalVolumeTypes () const
const vectorField & edgeDirections () const
const labelListList & normalDirections () const
vector edgeDirection (label edgeI, label ptI) const
const labelListList & edgeNormals () const
vectorField edgeNormals (const labelList &edgeNormIs) const
vectorField edgeNormals (label edgeI) const
const labelListList & featurePointNormals () const
vectorField featurePointNormals (label ptI) const
const labelListList & featurePointEdges () const
const labelList & regionEdges () const
pointStatus getPointStatus (label ptI) const
edgeStatus getEdgeStatus (label edgeI) const
PackedList< 2 > edgeBaffles (label edgeI) const
const indexedOctree< treeDataPoint > & pointTree () const
const indexedOctree< treeDataEdge > & edgeTree () const
const PtrList< indexedOctree< treeDataEdge > > & edgeTreesByType () const
void transfer (extendedEdgeMesh &mesh)
virtual void clear ()
void add (const extendedEdgeMesh &fem)
void flipNormals ()
void autoMap (const pointField &subPoints, const edgeList &subEdges, const labelList &pointMap, const labelList &edgeMap)
void trim (const searchableSurface &surf, const volumeType volType, labelList &pointMap, labelList &edgeMap)
void setFromStatus (const List< extendedEdgeMesh::pointStatus > &pointStat, const List< extendedEdgeMesh::edgeStatus > &edgeStat, labelList &sortedToOriginalPoint, labelList &sortedToOriginalEdge)
bool mergePointsAndSort (const scalar mergeDist, labelList &pointMap, labelList &edgeMap)
bool read (const fileName &name, const word &ext)
virtual bool read (const fileName &name)
void writeObj (const fileName &prefix) const
virtual void writeStats (Ostream &os) const
Public Member Functions inherited from edgeMesh
edgeMesh (const faMesh &mesh)
label size () const
const edgeVectorField & C () const
TypeName ("edgeMesh")
edgeMesh ()
edgeMesh (const edgeMesh &em)
edgeMesh (edgeMesh &&em)
edgeMesh (const pointField &points, const edgeList &edges)
edgeMesh (pointField &&pointLst, edgeList &&edgeLst)
edgeMesh (const fileName &name)
edgeMesh (const fileName &name, const word &fileType)
declareRunTimeSelectionTable (autoPtr, edgeMesh, fileExtension,(const fileName &name),(name))
virtual ~edgeMesh ()=default
declareMemberFunctionSelectionTable (void, edgeMesh, write, fileExtension,(const fileName &name, const edgeMesh &mesh, IOstreamOption streamOpt, const dictionary &options),(name, mesh, streamOpt, options))
void transfer (edgeMesh &mesh)
bool read (const fileName &name, const word &fileType)
const pointField & points () const noexcept
const edgeList & edges () const noexcept
const labelListList & pointEdges () const
label regions (labelList &edgeRegion) const
virtual void scalePoints (const scalar scaleFactor)
virtual void mergePoints (const scalar mergeDist)
virtual void mergeEdges ()
virtual void write (const fileName &name, IOstreamOption streamOpt=IOstreamOption(), const dictionary &options=dictionary::null) const
virtual void write (const fileName &name, const word &fileType, IOstreamOption streamOpt=IOstreamOption(), const dictionary &options=dictionary::null) const
void operator= (const edgeMesh &rhs)
void operator= (edgeMesh &&rhs)
Public Member Functions inherited from GeoMesh< faMesh >
GeoMesh (const faMesh &mesh)
bool hasDb () const
const objectRegistry & thisDb () const
const faMesh & operator() () const
Public Member Functions inherited from edgeMeshFormatsCore
edgeMeshFormatsCore ()=default
virtual ~edgeMeshFormatsCore ()=default
Static Public Member Functions
static wordHashSet readTypes ()
static wordHashSet writeTypes ()
static bool canReadType (const word &fileType, bool verbose=false)
static bool canWriteType (const word &fileType, bool verbose=false)
static bool canRead (const fileName &name, bool verbose=false)
static autoPtr< extendedEdgeMesh > New (const fileName &name, const word &fileType)
static autoPtr< extendedEdgeMesh > New (const fileName &name)
static edgeStatus classifyEdge (const List< vector > &norms, const labelList &edNorms, const vector &fC0tofC1)
static void sortedOrder (const List< extendedEdgeMesh::pointStatus > &pointStat, const List< extendedEdgeMesh::edgeStatus > &edgeStat, labelList &sortedToOriginalPoint, labelList &sortedToOriginalEdge, label &pointConcaveStart, label &pointMixedStart, label &pointNonFeatStart, label &edgeInternalStart, label &edgeFlatStart, label &edgeOpenStart, label &edgeMultipleStart)
Static Public Member Functions inherited from edgeMesh
static label size (const Mesh &mesh)
static wordHashSet readTypes ()
static wordHashSet writeTypes ()
static bool canReadType (const word &fileType, bool verbose=false)
static bool canWriteType (const word &fileType, bool verbose=false)
static bool canRead (const fileName &name, bool verbose=false)
static autoPtr< edgeMesh > New (const fileName &name, const word &fileType)
static autoPtr< edgeMesh > New (const fileName &name)
static void write (const fileName &name, const edgeMesh &mesh, IOstreamOption streamOpt=IOstreamOption(), const dictionary &options=dictionary::null)
static void write (const fileName &name, const word &fileType, const edgeMesh &mesh, IOstreamOption streamOpt=IOstreamOption(), const dictionary &options=dictionary::null)
Static Public Member Functions inherited from edgeMeshFormatsCore
static bool checkSupport (const wordHashSet &available, const word &fileType, const bool verbose=false, const char *functionName=nullptr)
Static Public Attributes
static const Enum< pointStatus > pointStatusNames_
static const Enum< edgeStatus > edgeStatusNames_
static const Enum< sideVolumeType > sideVolumeTypeNames_
static scalar cosNormalAngleTol_
static constexpr label nPointTypes = 4
static constexpr label nEdgeTypes = 5
Static Public Attributes inherited from edgeMeshFormatsCore
static word nativeExt
Protected Member Functions
extendedEdgeMesh (std::nullptr_t)
pointStatus classifyFeaturePoint (label ptI) const
void cut (const searchableSurface &, labelList &pMap, labelList &eMap, labelList &pointsFromEdge, labelList &oldEdge, labelList &surfTri)
void select (const searchableSurface &surf, const volumeType volType, labelList &pMap, labelList &eMap)
template<class Patch >
void sortPointsAndEdges (const Patch &, const labelUList &featureEdges, const labelUList &regionFeatureEdges, const labelUList &feaurePoints)
Protected Member Functions inherited from edgeMesh
pointField & storedPoints () noexcept
edgeList & storedEdges () noexcept
Protected Attributes
label concaveStart_
label mixedStart_
label nonFeatureStart_
label internalStart_
label flatStart_
label openStart_
label multipleStart_
vectorField normals_
List< sideVolumeType > normalVolumeTypes_
vectorField edgeDirections_
labelListList normalDirections_
labelListList edgeNormals_
labelListList featurePointNormals_
labelListList featurePointEdges_
labelList regionEdges_
std::unique_ptr< indexedOctree< treeDataPoint > > pointTree_
std::unique_ptr< indexedOctree< treeDataEdge > > edgeTree_
PtrList< indexedOctree< treeDataEdge > > edgeTreesByType_
Protected Attributes inherited from GeoMesh< faMesh >
const faMesh & mesh_
Static Protected Attributes
static label convexStart_ = 0
static label externalStart_ = 0
Friends
Istream & operator>> (Istream &is, sideVolumeType &vt)
Ostream & operator<< (Ostream &os, const sideVolumeType &vt)
Ostream & operator<< (Ostream &, const extendedEdgeMesh &)
Istream & operator>> (Istream &, extendedEdgeMesh &)
Additional Inherited Members
Static Protected Member Functions inherited from edgeMeshFormatsCore
static string getLineNoComment (ISstream &is, const char comment='#')
Detailed Description
Description of feature edges and points.
Feature points are a sorted subset at the start of the overall points list: 0 .. concaveStart_-1 : convex points (w.r.t normals) concaveStart_ .. mixedStart_-1 : concave points mixedStart_ .. nonFeatureStart_-1 : mixed internal/external points nonFeatureStart_ .. size-1 : non-feature points
Feature edges are the edgeList of the edgeMesh and are sorted: 0 .. internalStart_-1 : external edges (convex w.r.t normals) internalStart_ .. flatStart_-1 : internal edges (concave) flatStart_ .. openStart_-1 : flat edges (neither concave or convex) can arise from region interfaces on flat surfaces openStart_ .. multipleStart_-1 : open edges (e.g. from baffle surfaces) multipleStart_ .. size-1 : multiply connected edges
The edge direction and feature edge and feature point adjacent normals are stored.
Source files
extendedEdgeMesh.H
extendedEdgeMeshI.H
extendedEdgeMesh.C
extendedEdgeMeshNew.C
Definition at line 81 of file extendedEdgeMesh.H.
Member Enumeration Documentation
pointStatus
enum pointStatus
Enumerator
CONVEX
Fully convex point (w.r.t normals)
CONCAVE
Fully concave point.
MIXED
A point surrounded by both convex and concave edges.
NONFEATURE
Not a feature point.
Definition at line 90 of file extendedEdgeMesh.H.
edgeStatus
enum edgeStatus
Enumerator
EXTERNAL
"Convex" edge
INTERNAL
"Concave" edge
FLAT
Neither concave or convex, on a flat surface.
OPEN
Only connected to a single face.
MULTIPLE
Multiply connected (connected to more than two faces)
NONE
Unclassified (consistency with surfaceFeatures)
Definition at line 100 of file extendedEdgeMesh.H.
sideVolumeType
enum sideVolumeType
Enumerator
INSIDE
mesh inside
OUTSIDE
mesh outside
BOTH
e.g. a baffle
NEITHER
not sure when this may be used
Definition at line 113 of file extendedEdgeMesh.H.
Constructor & Destructor Documentation
extendedEdgeMesh() [1/11]
extendedEdgeMesh (std::nullptr_t) explicit protected
Definition at line 396 of file extendedEdgeMesh.C.
extendedEdgeMesh() [2/11]
extendedEdgeMesh ()
Definition at line 372 of file extendedEdgeMesh.C.
extendedEdgeMesh() [3/11]
extendedEdgeMesh (const extendedEdgeMesh & fem) explicit
Definition at line 420 of file extendedEdgeMesh.C.
extendedEdgeMesh() [4/11]
extendedEdgeMesh (const fileName & name) explicit
Definition at line 612 of file extendedEdgeMesh.C.
References Foam::name(), and extendedEdgeMesh::read().
extendedEdgeMesh() [5/11]
extendedEdgeMesh (const fileName & name, const word & fileType)
Definition at line 600 of file extendedEdgeMesh.C.
References Foam::name(), and extendedEdgeMesh::read().
extendedEdgeMesh() [6/11]
extendedEdgeMesh (Istream & is) explicit
Definition at line 444 of file extendedEdgeMesh.C.
extendedEdgeMesh() [7/11]
extendedEdgeMesh (const pointField & points, const edgeList & edges)
Definition at line 450 of file extendedEdgeMesh.C.
References edgeMesh::edges(), edgeMesh::points(), edgeMesh::storedEdges(), and edgeMesh::storedPoints().
extendedEdgeMesh() [8/11]
extendedEdgeMesh (pointField && points, edgeList && edges)
Definition at line 463 of file extendedEdgeMesh.C.
References edgeMesh::edges(), edgeMesh::points(), edgeMesh::storedEdges(), edgeMesh::storedPoints(), and List< T >::transfer().
extendedEdgeMesh() [9/11]
extendedEdgeMesh (const surfaceFeatures & sFeat, const boolList & surfBaffleRegions)
Definition at line 476 of file extendedEdgeMesh.C.
References extendedEdgeMesh::BOTH, PrimitivePatch< FaceList, PointField >::edgeFaces(), Foam::faceMap(), forAll, Foam::identity(), extendedEdgeMesh::INSIDE, extendedEdgeMesh::normals_, extendedEdgeMesh::normalVolumeTypes_, List< T >::setSize(), UList< T >::size(), and extendedEdgeMesh::sortPointsAndEdges().
extendedEdgeMesh() [10/11]
extendedEdgeMesh (const PrimitivePatch< faceList, pointField > & surf, const labelUList & featureEdges, const labelUList & regionFeatureEdges, const labelUList & featurePoints)
Definition at line 537 of file extendedEdgeMesh.C.
References extendedEdgeMesh::sortPointsAndEdges().
extendedEdgeMesh() [11/11]
extendedEdgeMesh (const pointField & pts, const edgeList & eds, label concaveStart, label mixedStart, label nonFeatureStart, label internalStart, label flatStart, label openStart, label multipleStart, const vectorField & normals, const List< sideVolumeType > & normalVolumeTypes, const vectorField & edgeDirections, const labelListList & normalDirections, const labelListList & edgeNormals, const labelListList & featurePointNormals, const labelListList & featurePointEdges, const labelList & regionEdges)
Definition at line 557 of file extendedEdgeMesh.C.
~extendedEdgeMesh()
~extendedEdgeMesh () default
Member Function Documentation
TypeName()
TypeName ("extendedEdgeMesh")
classifyFeaturePoint()
Foam::extendedEdgeMesh::pointStatus classifyFeaturePoint (label ptI) const protected
Definition at line 146 of file extendedEdgeMesh.C.
References forAll, and UPtrList< T >::size().
Referenced by extendedEdgeMesh::sortPointsAndEdges().
cut()
void cut (const searchableSurface & surf, labelList & pMap, labelList & eMap, labelList & pointsFromEdge, labelList & oldEdge, labelList & surfTri) protected
Definition at line 190 of file extendedEdgeMesh.C.
References PtrList< T >::append(), e, searchableSurface::findLineAll(), forAll, Foam::identity(), points, UPtrList< T >::size(), UList< T >::size(), List< T >::transfer(), and PtrList< T >::transfer().
select()
void select (const searchableSurface & surf, const volumeType volType, labelList & pMap, labelList & eMap) protected
Definition at line 292 of file extendedEdgeMesh.C.
References e, edgeCentres(), forAll, searchableSurface::getVolumeType(), Foam::identity(), volumeType::INSIDE, Foam::labelMax, volumeType::OUTSIDE, points, List< T >::setSize(), UPtrList< T >::size(), and UList< T >::size().
sortPointsAndEdges()
template<class Patch > void sortPointsAndEdges (const Patch & surf, const labelUList & featureEdges, const labelUList & regionFeatureEdges, const labelUList & feaurePoints) protected
Definition at line 32 of file extendedEdgeMeshTemplates.C.
References Foam::abort(), PtrList< T >::append(), extendedEdgeMesh::classifyEdge(), extendedEdgeMesh::classifyFeaturePoint(), extendedEdgeMesh::CONCAVE, extendedEdgeMesh::concaveStart_, extendedEdgeMesh::CONVEX, extendedEdgeMesh::cosNormalAngleTol_, Foam::cross(), extendedEdgeMesh::edgeDirections(), extendedEdgeMesh::edgeDirections_, edgeMesh::edgeMesh(), extendedEdgeMesh::edgeNormals(), extendedEdgeMesh::edgeNormals_, UPtrList< T >::end(), extendedEdgeMesh::EXTERNAL, Foam::faceMap(), Foam::FatalError, FatalErrorInFunction, extendedEdgeMesh::featurePointEdges_, extendedEdgeMesh::featurePointNormals(), extendedEdgeMesh::featurePointNormals_, extendedEdgeMesh::FLAT, extendedEdgeMesh::flatStart_, forAll, Foam::identity(), Foam::inplaceRenumber(), Foam::inplaceReorder(), extendedEdgeMesh::INTERNAL, extendedEdgeMesh::internalStart_, Foam::invert(), k, Foam::mag(), extendedEdgeMesh::MIXED, extendedEdgeMesh::mixedStart_, extendedEdgeMesh::MULTIPLE, extendedEdgeMesh::multipleStart_, extendedEdgeMesh::nEdgeTypes, Foam::nl, extendedEdgeMesh::NONE, extendedEdgeMesh::NONFEATURE, extendedEdgeMesh::nonFeatureStart_, extendedEdgeMesh::normalDirections(), extendedEdgeMesh::normalDirections_, extendedEdgeMesh::normals_, extendedEdgeMesh::OPEN, extendedEdgeMesh::openStart_, edgeMesh::operator=(), edgeMesh::pointEdges(), edgeMesh::points(), pts, extendedEdgeMesh::regionEdges(), extendedEdgeMesh::regionEdges_, PtrList< T >::setSize(), UPtrList< T >::size(), UList< T >::size(), PatchTools::sortedEdgeFaces(), PatchTools::sortedPointEdges(), UPtrList< T >::test(), edgeMesh::transfer(), PtrList< T >::transfer(), and Foam::Zero.
Referenced by extendedEdgeMesh::extendedEdgeMesh(), and extendedEdgeMesh::extendedEdgeMesh().
readTypes()
Foam::wordHashSet readTypes () static
Definition at line 94 of file extendedEdgeMesh.C.
writeTypes()
Foam::wordHashSet writeTypes () static
Definition at line 100 of file extendedEdgeMesh.C.
canReadType()
bool canReadType (const word & fileType, bool verbose = false) static
Definition at line 106 of file extendedEdgeMesh.C.
canWriteType()
bool canWriteType (const word & fileType, bool verbose = false) static
Definition at line 118 of file extendedEdgeMesh.C.
canRead()
bool canRead (const fileName & name, bool verbose = false) static
Definition at line 130 of file extendedEdgeMesh.C.
References word::ext(), word::has_ext(), and Foam::name().
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , extendedEdgeMesh , fileExtension , (const fileName &name) , (name))
New() [1/2]
Foam::autoPtr< Foam::extendedEdgeMesh > New (const fileName & name, const word & fileType) static
Definition at line 34 of file extendedEdgeMeshNew.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::flatOutput(), Foam::name(), and Foam::nl.
New() [2/2]
Foam::autoPtr< Foam::extendedEdgeMesh > New (const fileName & name) static
Definition at line 56 of file extendedEdgeMeshNew.C.
References word::ext(), word::has_ext(), Foam::name(), and Foam::New().
nearestFeaturePoint()
void nearestFeaturePoint (const point & sample, scalar searchDistSqr, pointIndexHit & info) const
Definition at line 645 of file extendedEdgeMesh.C.
nearestFeatureEdge() [1/2]
void nearestFeatureEdge (const point & sample, scalar searchDistSqr, pointIndexHit & info) const
Definition at line 660 of file extendedEdgeMesh.C.
nearestFeatureEdge() [2/2]
void nearestFeatureEdge (const pointField & samples, const scalarField & searchDistSqr, List< pointIndexHit > & info) const
Definition at line 675 of file extendedEdgeMesh.C.
References forAll, samples(), PtrList< T >::setSize(), and UList< T >::size().
nearestFeatureEdgeByType()
void nearestFeatureEdgeByType (const point & sample, const scalarField & searchDistSqr, List< pointIndexHit > & info) const
Definition at line 696 of file extendedEdgeMesh.C.
References forAll, PtrList< T >::resize(), UPtrList< T >::size(), and tree().
allNearestFeaturePoints()
void allNearestFeaturePoints (const point & sample, scalar searchRadiusSqr, List< pointIndexHit > & info) const
Definition at line 723 of file extendedEdgeMesh.C.
References PtrList< T >::append(), UPtrList< T >::size(), and PtrList< T >::transfer().
allNearestFeatureEdges()
void allNearestFeatureEdges (const point & sample, const scalar searchRadiusSqr, List< pointIndexHit > & info) const
Definition at line 754 of file extendedEdgeMesh.C.
References PtrList< T >::append(), forAll, UPtrList< T >::size(), PtrList< T >::transfer(), and tree().
convexStart()
Foam::label convexStart () const inline
Definition at line 23 of file extendedEdgeMeshI.H.
References extendedEdgeMesh::convexStart_.
concaveStart()
Foam::label concaveStart () const inline
Definition at line 29 of file extendedEdgeMeshI.H.
mixedStart()
Foam::label mixedStart () const inline
Definition at line 35 of file extendedEdgeMeshI.H.
nonFeatureStart()
Foam::label nonFeatureStart () const inline
Definition at line 41 of file extendedEdgeMeshI.H.
externalStart()
Foam::label externalStart () const inline
Definition at line 47 of file extendedEdgeMeshI.H.
internalStart()
Foam::label internalStart () const inline
Definition at line 53 of file extendedEdgeMeshI.H.
flatStart()
Foam::label flatStart () const inline
Definition at line 59 of file extendedEdgeMeshI.H.
openStart()
Foam::label openStart () const inline
Definition at line 65 of file extendedEdgeMeshI.H.
multipleStart()
Foam::label multipleStart () const inline
Definition at line 71 of file extendedEdgeMeshI.H.
featurePoint()
bool featurePoint (label ptI) const inline
Definition at line 77 of file extendedEdgeMeshI.H.
normals()
const Foam::vectorField & normals () const inline
Definition at line 83 of file extendedEdgeMeshI.H.
normalVolumeTypes()
const Foam::List< Foam::extendedEdgeMesh::sideVolumeType > & normalVolumeTypes () const inline
Definition at line 90 of file extendedEdgeMeshI.H.
edgeDirections()
const Foam::vectorField & edgeDirections () const inline
Definition at line 96 of file extendedEdgeMeshI.H.
Referenced by extendedEdgeMesh::sortPointsAndEdges().
normalDirections()
const Foam::labelListList & normalDirections () const inline
Definition at line 104 of file extendedEdgeMeshI.H.
Referenced by extendedEdgeMesh::sortPointsAndEdges().
edgeDirection()
Foam::vector edgeDirection (label edgeI, label ptI) const inline
Definition at line 110 of file extendedEdgeMeshI.H.
References e, UList< T >::end(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, and Foam::Zero.
edgeNormals() [1/3]
const Foam::labelListList & edgeNormals () const inline
Definition at line 139 of file extendedEdgeMeshI.H.
Referenced by extendedEdgeMesh::sortPointsAndEdges().
edgeNormals() [2/3]
Foam::vectorField edgeNormals (const labelList & edgeNormIs) const inline
Definition at line 146 of file extendedEdgeMeshI.H.
References forAll, and UPtrList< T >::size().
edgeNormals() [3/3]
Foam::vectorField edgeNormals (label edgeI) const inline
Definition at line 162 of file extendedEdgeMeshI.H.
featurePointNormals() [1/2]
const Foam::labelListList & featurePointNormals () const inline
Definition at line 170 of file extendedEdgeMeshI.H.
Referenced by extendedEdgeMesh::sortPointsAndEdges().
featurePointNormals() [2/2]
Foam::vectorField featurePointNormals (label ptI) const inline
Definition at line 176 of file extendedEdgeMeshI.H.
References Foam::endl(), forAll, UPtrList< T >::size(), and WarningInFunction.
featurePointEdges()
const Foam::labelListList & featurePointEdges () const inline
Definition at line 205 of file extendedEdgeMeshI.H.
regionEdges()
const Foam::labelList & regionEdges () const inline
Definition at line 211 of file extendedEdgeMeshI.H.
Referenced by extendedEdgeMesh::sortPointsAndEdges().
getPointStatus()
Foam::extendedEdgeMesh::pointStatus getPointStatus (label ptI) const inline
Definition at line 218 of file extendedEdgeMeshI.H.
getEdgeStatus()
Foam::extendedEdgeMesh::edgeStatus getEdgeStatus (label edgeI) const inline
Definition at line 238 of file extendedEdgeMeshI.H.
edgeBaffles()
Foam::PackedList< 2 > edgeBaffles (label edgeI) const inline
Definition at line 261 of file extendedEdgeMeshI.H.
References PtrList< T >::append(), and UPtrList< T >::size().
pointTree()
const Foam::indexedOctree< Foam::treeDataPoint > & pointTree () const
Definition at line 792 of file extendedEdgeMesh.C.
References e, Foam::identity(), points, and rndGen.
edgeTree()
const Foam::indexedOctree< Foam::treeDataEdge > & edgeTree () const
Definition at line 826 of file extendedEdgeMesh.C.
References e, points, and rndGen.
edgeTreesByType()
const Foam::PtrList< Foam::indexedOctree< Foam::treeDataEdge > > & edgeTreesByType () const
Definition at line 858 of file extendedEdgeMesh.C.
References e, forAll, points, PtrList< T >::resize(), rndGen, and PtrList< T >::set().
transfer()
void transfer (extendedEdgeMesh & mesh)
Definition at line 914 of file extendedEdgeMesh.C.
References objectRegistry::clear(), mesh, edgeMesh::transfer(), HashTable< T, Key, Hash >::transfer(), and PtrList< T >::transfer().
clear()
void clear () virtual
Reimplemented from edgeMesh.
Definition at line 946 of file extendedEdgeMesh.C.
References edgeMesh::clear().
add()
void add (const extendedEdgeMesh & fem)
Definition at line 970 of file extendedEdgeMesh.C.
References PtrList< T >::append(), PtrList< T >::clear(), e, forAll, newPointi, points, Field< Type >::rmap(), UPtrList< T >::size(), edgeMesh::transfer(), and PtrList< T >::transfer().
flipNormals()
void flipNormals ()
Definition at line 1240 of file extendedEdgeMesh.C.
References PtrList< T >::clear(), e, forAll, Foam::identity(), newPointi, points, Field< Type >::rmap(), edgeMesh::transfer(), and PtrList< T >::transfer().
autoMap()
void autoMap (const pointField & subPoints, const edgeList & subEdges, const labelList & pointMap, const labelList & edgeMap)
Definition at line 1351 of file extendedEdgeMesh.C.
References PtrList< T >::append(), forAll, PtrList< T >::set(), PtrList< T >::setSize(), UPtrList< T >::size(), UList< T >::size(), UPtrList< T >::test(), and PtrList< T >::transfer().
trim()
void trim (const searchableSurface & surf, const volumeType volType, labelList & pointMap, labelList & edgeMap)
Definition at line 1591 of file extendedEdgeMesh.C.
References forAll, points, and UPtrList< T >::size().
setFromStatus()
void setFromStatus (const List< extendedEdgeMesh::pointStatus > & pointStat, const List< extendedEdgeMesh::edgeStatus > & edgeStat, labelList & sortedToOriginalPoint, labelList & sortedToOriginalEdge)
Definition at line 1674 of file extendedEdgeMesh.C.
References forAll, Foam::inplaceRenumber(), points, and Foam::sortedOrder().
mergePointsAndSort()
bool mergePointsAndSort (const scalar mergeDist, labelList & pointMap, labelList & edgeMap)
Definition at line 1742 of file extendedEdgeMesh.C.
References forAll, Foam::identity(), Foam::mergePoints(), nPoints, points, List< T >::setSize(), UPtrList< T >::size(), and Foam::Zero.
read() [1/2]
bool read (const fileName & name, const word & ext)
Definition at line 633 of file extendedEdgeMesh.C.
References Foam::name(), and Foam::New().
Referenced by extendedEdgeMesh::extendedEdgeMesh(), and extendedEdgeMesh::extendedEdgeMesh().
read() [2/2]
bool read (const fileName & name) virtual
Reimplemented from edgeMesh.
Reimplemented in extendedEdgeMeshFormat.
Definition at line 622 of file extendedEdgeMesh.C.
References word::ext(), word::has_ext(), word::lessExt(), Foam::name(), and Foam::read().
writeObj()
void writeObj (const fileName & prefix) const
Definition at line 1831 of file extendedEdgeMesh.C.
References e, Foam::endl(), forAll, Foam::Info, Foam::nl, points, UPtrList< T >::size(), and edgeMesh::write().
writeStats()
void writeStats (Ostream & os) const virtual
Reimplemented from edgeMesh.
Definition at line 1983 of file extendedEdgeMesh.C.
References Foam::decrIndent(), Foam::incrIndent(), Foam::indent(), Foam::nl, os(), points, Foam::setw(), UPtrList< T >::size(), and edgeMesh::writeStats().
classifyEdge()
Foam::extendedEdgeMesh::edgeStatus classifyEdge (const List< vector > & norms, const labelList & edNorms, const vector & fC0tofC1) static
Definition at line 2034 of file extendedEdgeMesh.C.
References UPtrList< T >::size().
Referenced by extendedEdgeMesh::sortPointsAndEdges().
sortedOrder()
void sortedOrder (const List< extendedEdgeMesh::pointStatus > & pointStat, const List< extendedEdgeMesh::edgeStatus > & edgeStat, labelList & sortedToOriginalPoint, labelList & sortedToOriginalEdge, label & pointConcaveStart, label & pointMixedStart, label & pointNonFeatStart, label & edgeInternalStart, label & edgeFlatStart, label & edgeOpenStart, label & edgeMultipleStart) static
Definition at line 2075 of file extendedEdgeMesh.C.
References extendedEdgeMesh::CONCAVE, extendedEdgeMesh::CONVEX, Foam::exit(), extendedEdgeMesh::EXTERNAL, Foam::FatalError, FatalErrorInFunction, extendedEdgeMesh::FLAT, forAll, extendedEdgeMesh::INTERNAL, extendedEdgeMesh::MIXED, extendedEdgeMesh::MULTIPLE, extendedEdgeMesh::NONE, extendedEdgeMesh::NONFEATURE, extendedEdgeMesh::OPEN, PtrList< T >::setSize(), and UPtrList< T >::size().
Friends And Related Symbol Documentation
operator>> [1/2]
Istream & operator>> (Istream & is, sideVolumeType & vt) friend
operator<< [1/2]
Ostream & operator<< (Ostream & os, const sideVolumeType & vt) friend
operator<< [2/2]
Ostream & operator<< (Ostream & , const extendedEdgeMesh &) friend
operator>> [2/2]
Istream & operator>> (Istream & , extendedEdgeMesh &) friend
Member Data Documentation
pointStatusNames_
const Foam::Enum< Foam::extendedEdgeMesh::pointStatus > pointStatusNames_ static
Definition at line 98 of file extendedEdgeMesh.H.
edgeStatusNames_
const Foam::Enum< Foam::extendedEdgeMesh::edgeStatus > edgeStatusNames_ static
Definition at line 110 of file extendedEdgeMesh.H.
sideVolumeTypeNames_
const Foam::Enum< Foam::extendedEdgeMesh::sideVolumeType > sideVolumeTypeNames_ static
Definition at line 121 of file extendedEdgeMesh.H.
cosNormalAngleTol_
Foam::scalar cosNormalAngleTol_ static
Initial value:
=
    Foam::cos(degToRad(0.1))
Definition at line 124 of file extendedEdgeMesh.H.
Referenced by extendedEdgeMesh::sortPointsAndEdges().
convexStart_
Foam::label convexStart_ = 0 static protected
Definition at line 132 of file extendedEdgeMesh.H.
Referenced by extendedEdgeMesh::convexStart().
externalStart_
Foam::label externalStart_ = 0 static protected
Definition at line 135 of file extendedEdgeMesh.H.
concaveStart_
label concaveStart_ protected
Definition at line 141 of file extendedEdgeMesh.H.
Referenced by extendedEdgeMesh::sortPointsAndEdges().
mixedStart_
label mixedStart_ protected
Definition at line 144 of file extendedEdgeMesh.H.
Referenced by extendedEdgeMesh::sortPointsAndEdges().
nonFeatureStart_
label nonFeatureStart_ protected
Definition at line 147 of file extendedEdgeMesh.H.
Referenced by extendedEdgeMesh::sortPointsAndEdges().
internalStart_
label internalStart_ protected
Definition at line 150 of file extendedEdgeMesh.H.
Referenced by extendedEdgeMesh::sortPointsAndEdges().
flatStart_
label flatStart_ protected
Definition at line 153 of file extendedEdgeMesh.H.
Referenced by extendedEdgeMesh::sortPointsAndEdges().
openStart_
label openStart_ protected
Definition at line 156 of file extendedEdgeMesh.H.
Referenced by extendedEdgeMesh::sortPointsAndEdges().
multipleStart_
label multipleStart_ protected
Definition at line 159 of file extendedEdgeMesh.H.
Referenced by extendedEdgeMesh::sortPointsAndEdges().
normals_
vectorField normals_ protected
Definition at line 163 of file extendedEdgeMesh.H.
Referenced by extendedEdgeMesh::extendedEdgeMesh(), and extendedEdgeMesh::sortPointsAndEdges().
normalVolumeTypes_
List<sideVolumeType> normalVolumeTypes_ protected
Definition at line 166 of file extendedEdgeMesh.H.
Referenced by extendedEdgeMesh::extendedEdgeMesh().
edgeDirections_
vectorField edgeDirections_ protected
Definition at line 169 of file extendedEdgeMesh.H.
Referenced by extendedFeatureEdgeMesh::extendedFeatureEdgeMesh(), and extendedEdgeMesh::sortPointsAndEdges().
normalDirections_
labelListList normalDirections_ protected
Definition at line 174 of file extendedEdgeMesh.H.
Referenced by extendedEdgeMesh::sortPointsAndEdges().
edgeNormals_
labelListList edgeNormals_ protected
Definition at line 177 of file extendedEdgeMesh.H.
Referenced by extendedEdgeMesh::sortPointsAndEdges().
featurePointNormals_
labelListList featurePointNormals_ protected
Definition at line 181 of file extendedEdgeMesh.H.
Referenced by extendedEdgeMesh::sortPointsAndEdges().
featurePointEdges_
labelListList featurePointEdges_ protected
Definition at line 185 of file extendedEdgeMesh.H.
Referenced by extendedEdgeMesh::sortPointsAndEdges().
regionEdges_
labelList regionEdges_ protected
Definition at line 188 of file extendedEdgeMesh.H.
Referenced by extendedEdgeMesh::sortPointsAndEdges().
pointTree_
std::unique_ptr<indexedOctree<treeDataPoint> > pointTree_ mutable protected
Definition at line 191 of file extendedEdgeMesh.H.
edgeTree_
std::unique_ptr<indexedOctree<treeDataEdge> > edgeTree_ mutable protected
Definition at line 194 of file extendedEdgeMesh.H.
edgeTreesByType_
PtrList<indexedOctree<treeDataEdge> > edgeTreesByType_ mutable protected
Definition at line 197 of file extendedEdgeMesh.H.
nPointTypes
constexpr label nPointTypes = 4 static constexpr
Definition at line 247 of file extendedEdgeMesh.H.
nEdgeTypes
constexpr label nEdgeTypes = 5 static constexpr
Definition at line 250 of file extendedEdgeMesh.H.
Referenced by extendedEdgeMesh::sortPointsAndEdges().
The documentation for this class was generated from the following files:
src/meshTools/edgeMesh/extendedEdgeMesh/extendedEdgeMesh.H
src/meshTools/edgeMesh/extendedEdgeMesh/extendedEdgeMesh.C
src/meshTools/edgeMesh/extendedEdgeMesh/extendedEdgeMeshI.H
src/meshTools/edgeMesh/extendedEdgeMesh/extendedEdgeMeshNew.C
src/meshTools/edgeMesh/extendedEdgeMesh/extendedEdgeMeshTemplates.C