OpenFOAM: genericPolyPatch Class Reference
genericPolyPatch Class Reference
Substitute for unknown patches. Used for postprocessing when only basic polyPatch info is needed or if the real patch type is unavailable.
#include <genericPolyPatch.H>
Public Member Functions
TypeName ("genericPatch")
genericPolyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType)
genericPolyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType)
genericPolyPatch (const genericPolyPatch &, const polyBoundaryMesh &)
genericPolyPatch (const genericPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart)
genericPolyPatch (const genericPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm) const
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart) const
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart) const
~genericPolyPatch ()
const word & actualType () const
virtual void write (Ostream &) const
Public Member Functions inherited from polyPatch
TypeName ("patch")
declareRunTimeSelectionTable (autoPtr, polyPatch, word,(const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType),(name, size, start, index, bm, patchType))
declareRunTimeSelectionTable (autoPtr, polyPatch, dictionary,(const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType),(name, dict, index, bm, patchType))
polyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType)
polyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &physicalType, const wordList &inGroups)
polyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType)
polyPatch (const polyPatch &, const polyBoundaryMesh &)
polyPatch (const polyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart)
polyPatch (const polyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
polyPatch (const polyPatch &p)
polyPatch (const polyPatch &p, const labelList &faceCells)
virtual autoPtr< polyPatch > clone (const labelList &faceCells) const
virtual ~polyPatch ()
virtual void newInternalProcFaces (label &, label &) const
virtual const labelUList & nbrCells () const
virtual label neighbPolyPatchID () const
virtual refPtr< labelListList > mapCollocatedFaces () const
virtual bool masterImplicit () const
virtual word neighbRegionID () const
label offset () const noexcept
label start () const noexcept
labelRange range () const
const polyBoundaryMesh & boundaryMesh () const noexcept
virtual bool coupled () const
template<class T >
const UIndirectList< T > patchInternalList (const UList< T > &internalValues) const
template<class T >
const List< T >::subList patchSlice (const UList< T > &values) const
template<class T >
const List< T >::subList boundarySlice (const List< T > &values) const
template<class T >
const Field< T >::subField patchSlice (const Field< T > &values) const
const vectorField::subField faceCentres () const
const vectorField::subField faceAreas () const
tmp< vectorField > faceCellCentres () const
tmp< scalarField > areaFraction () const
const labelUList & faceCells () const
const labelList & meshEdges () const
virtual void clearAddressing ()
label whichFace (const label facei) const noexcept
virtual void initOrder (PstreamBuffers &, const primitivePatch &) const
virtual bool order (PstreamBuffers &, const primitivePatch &, labelList &faceMap, labelList &rotation) const
virtual bool changeTopology () const
virtual bool setTopology (polyTopoChange &)
void operator= (const polyPatch &)
Public Member Functions inherited from patchIdentifier
patchIdentifier (const patchIdentifier &)=default
patchIdentifier & operator= (const patchIdentifier &)=default
virtual ~patchIdentifier ()=default
patchIdentifier ()
patchIdentifier (const word &name, const label index)
patchIdentifier (const word &name, const label index, const word &physicalType, const wordList &inGroups=wordList())
patchIdentifier (const word &name, const dictionary &dict, const label index)
patchIdentifier (const patchIdentifier &ident, const label index)
const word & name () const noexcept
word & name () noexcept
label index () const noexcept
label & index () noexcept
const word & physicalType () const noexcept
word & physicalType () noexcept
const wordList & inGroups () const noexcept
wordList & inGroups () noexcept
bool inGroup (const word &name) const
void write (Ostream &os) const
Public Member Functions inherited from PrimitivePatch< FaceList, PointField >
PrimitivePatch (const FaceList &faces, const PointField &points)
PrimitivePatch (FaceList &&faces, const PointField &points)
PrimitivePatch (FaceList &faces, PointField &points, const bool reuse)
PrimitivePatch (const PrimitivePatch< FaceList, PointField > &pp)
virtual ~PrimitivePatch ()
void clearOut ()
void clearGeom ()
void clearTopology ()
void clearPatchMeshAddr ()
void swap (PrimitivePatch &)=delete
const Field< point_type > & points () const noexcept
label nFaces () const noexcept
label nPoints () const
label nEdges () const
const edgeList & edges () const
const edgeList::subList internalEdges () const
const edgeList::subList boundaryEdges () const
label nInternalEdges () const
label nBoundaryEdges () const
bool isInternalEdge (const label edgei) const
const labelList & boundaryPoints () const
const labelListList & faceFaces () const
const labelListList & edgeFaces () const
const labelListList & faceEdges () const
const labelListList & pointEdges () const
const labelListList & pointFaces () const
const List< face_type > & localFaces () const
labelList boundaryFaces () const
labelList uniqBoundaryFaces () const
const labelList & meshPoints () const
const Map< label > & meshPointMap () const
const Field< point_type > & localPoints () const
const labelList & localPointOrder () const
label whichPoint (const label gp) const
edge meshEdge (const label edgei) const
edge meshEdge (const edge &e) const
label findEdge (const edge &e) const
labelList meshEdges (const edgeList &allEdges, const labelListList &cellEdges, const labelList &faceCells) const
labelList meshEdges (const edgeList &allEdges, const labelListList &pointEdges) const
label meshEdge (const label edgei, const edgeList &allEdges, const labelListList &pointEdges) const
labelList meshEdges (const labelUList &edgeLabels, const edgeList &allEdges, const labelListList &pointEdges) const
const Field< point_type > & faceCentres () const
const Field< point_type > & faceAreas () const
const Field< scalar > & magFaceAreas () const
const Field< point_type > & faceNormals () const
const Field< point_type > & pointNormals () const
Pair< point_type > box () const
scalar sphere (const label facei) const
bool hasFaceAreas () const
bool hasFaceCentres () const
bool hasFaceNormals () const
bool hasPointNormals () const
bool hasBoundaryPoints () const
bool hasEdges () const
bool hasFaceFaces () const
bool hasEdgeFaces () const
bool hasFaceEdges () const
bool hasPointEdges () const
bool hasPointFaces () const
bool hasMeshPoints () const
bool hasMeshPointMap () const
template<class ToPatch >
List< objectHit > projectPoints (const ToPatch &targetPatch, const Field< point_type > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
template<class ToPatch >
List< objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< point_type > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
const labelListList & edgeLoops () const
surfaceTopo surfaceType (labelHashSet *badEdgesPtr=nullptr) const
bool checkTopology (const bool report=false, labelHashSet *pointSetPtr=nullptr) const
bool checkPointManifold (const bool report=false, labelHashSet *pointSetPtr=nullptr) const
void operator= (const PrimitivePatch< FaceList, PointField > &rhs)
void operator= (PrimitivePatch< FaceList, PointField > &&rhs)
label whichEdge (const edge &e) const
template<class ToPatch >
Foam::List< Foam::objectHit > projectPoints (const ToPatch &targetPatch, const Field< typename Foam::PrimitivePatch< FaceList, PointField >::point_type > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
template<class ToPatch >
Foam::List< Foam::objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< typename Foam::PrimitivePatch< FaceList, PointField >::point_type > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
Public Member Functions inherited from PrimitivePatchBase
ClassName ("PrimitivePatch")
PrimitivePatchBase ()=default
Additional Inherited Members
Public Types inherited from PrimitivePatch< FaceList, PointField >
enum surfaceTopo { MANIFOLD , OPEN , ILLEGAL }
typedef std::remove_reference< FaceList >::type::value_type face_type
typedef std::remove_reference< PointField >::type::value_type point_type
typedef FaceList FaceListType
typedef PointField PointFieldType
typedef face_type FaceType
Static Public Member Functions inherited from polyPatch
static autoPtr< polyPatch > New (const word &patchType, const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm)
static autoPtr< polyPatch > New (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm)
static autoPtr< polyPatch > New (const word &patchType, const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm)
static bool constraintType (const word &patchType)
static wordList constraintTypes ()
Static Public Member Functions inherited from patchIdentifier
static word defaultName (const label n=-1)
Static Public Attributes inherited from polyPatch
static int disallowGenericPolyPatch
Protected Member Functions inherited from polyPatch
virtual void initGeometry (PstreamBuffers &)
virtual void calcGeometry (PstreamBuffers &)
virtual void initMovePoints (PstreamBuffers &, const pointField &)
virtual void movePoints (PstreamBuffers &, const pointField &p)
virtual void initUpdateMesh (PstreamBuffers &)
virtual void updateMesh (PstreamBuffers &)
virtual void clearGeom ()
virtual void movePoints (const Field< point_type > &)
Detailed Description
Substitute for unknown patches. Used for postprocessing when only basic polyPatch info is needed or if the real patch type is unavailable.
Note
Storage is not optimal. It stores all face centres and cells on all processors to keep the addressing calculation simple.
Source files
genericPolyPatch.H
genericPolyPatch.C
Definition at line 53 of file genericPolyPatch.H.
Constructor & Destructor Documentation
genericPolyPatch() [1/5]
genericPolyPatch (const word & name, const label size, const label start, const label index, const polyBoundaryMesh & bm, const word & patchType)
Definition at line 38 of file genericPolyPatch.C.
References Foam::name().
genericPolyPatch() [2/5]
genericPolyPatch (const word & name, const dictionary & dict, const label index, const polyBoundaryMesh & bm, const word & patchType)
Definition at line 52 of file genericPolyPatch.C.
genericPolyPatch() [3/5]
genericPolyPatch (const genericPolyPatch & pp, const polyBoundaryMesh & bm)
Definition at line 67 of file genericPolyPatch.C.
genericPolyPatch() [4/5]
genericPolyPatch (const genericPolyPatch & pp, const polyBoundaryMesh & bm, const label index, const label newSize, const label newStart)
Definition at line 79 of file genericPolyPatch.C.
genericPolyPatch() [5/5]
genericPolyPatch (const genericPolyPatch & pp, const polyBoundaryMesh & bm, const label index, const labelUList & mapAddressing, const label newStart)
Definition at line 94 of file genericPolyPatch.C.
~genericPolyPatch()
~genericPolyPatch ()
Definition at line 111 of file genericPolyPatch.C.
Member Function Documentation
TypeName()
TypeName ("genericPatch")
clone() [1/3]
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh & bm) const inline virtual
Reimplemented from polyPatch.
Definition at line 120 of file genericPolyPatch.H.
clone() [2/3]
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh & bm, const label index, const label newSize, const label newStart) const inline virtual
Reimplemented from polyPatch.
Definition at line 127 of file genericPolyPatch.H.
References patchIdentifier::index().
clone() [3/3]
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh & bm, const label index, const labelUList & mapAddressing, const label newStart) const inline virtual
Reimplemented from polyPatch.
Definition at line 143 of file genericPolyPatch.H.
References patchIdentifier::index().
actualType()
const Foam::word & actualType () const
Definition at line 117 of file genericPolyPatch.C.
write()
void write (Ostream & os) const virtual
Reimplemented from polyPatch.
Definition at line 123 of file genericPolyPatch.C.
References e, os(), regIOobject::write(), patchIdentifier::write(), and Ostream::writeEntry().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/polyPatches/basic/generic/genericPolyPatch.H
src/OpenFOAM/meshes/polyMesh/polyPatches/basic/generic/genericPolyPatch.C