OpenFOAM: thermophysicalPropertiesSelector< ThermophysicalProperties > Class Template Reference
thermophysicalPropertiesSelector< ThermophysicalProperties > Class Template Reference
Wrapper class providing run-time selection of thermophysicalProperties for the templated thermodynamics packages.
#include <thermophysicalPropertiesSelector.H>
Public Member Functions
thermophysicalPropertiesSelector (const word &name)
thermophysicalPropertiesSelector (const dictionary &dict)
const ThermophysicalProperties & properties () const
scalar W () const
scalar limit (const scalar T) const
scalar rho (scalar p, scalar T) const
scalar psi (scalar p, scalar T) const
scalar CpMCv (scalar p, scalar T) const
scalar Cp (const scalar p, const scalar T) const
scalar Ha (const scalar p, const scalar T) const
scalar Hs (const scalar p, const scalar T) const
scalar Hc () const
scalar Cv (const scalar p, const scalar T) const
scalar Es (const scalar p, const scalar T) const
scalar Ea (const scalar p, const scalar T) const
scalar S (const scalar p, const scalar T) const
scalar mu (scalar p, scalar T) const
scalar kappa (scalar p, scalar T) const
scalar alphah (const scalar p, const scalar T) const
Static Public Member Functions
static word typeName ()
Static Public Attributes
static const bool incompressible
static const bool isochoric
Detailed Description
template<class ThermophysicalProperties>
class Foam::thermophysicalPropertiesSelector< ThermophysicalProperties >
Wrapper class providing run-time selection of thermophysicalProperties for the templated thermodynamics packages.
Source files
thermophysicalPropertiesSelector.H
thermophysicalPropertiesSelectorI.H
thermophysicalPropertiesSelector.C
Definition at line 49 of file thermophysicalPropertiesSelector.H.
Constructor & Destructor Documentation
thermophysicalPropertiesSelector() [1/2]
template<class ThermophysicalProperties > thermophysicalPropertiesSelector (const word & name)
Definition at line 26 of file thermophysicalPropertiesSelector.C.
References Foam::name(), and Foam::New().
thermophysicalPropertiesSelector() [2/2]
template<class ThermophysicalProperties > thermophysicalPropertiesSelector (const dictionary & dict)
Definition at line 37 of file thermophysicalPropertiesSelector.C.
References dict, dictionary::findDict(), UILList< LListBase, T >::first(), and Foam::name().
Member Function Documentation
typeName()
template<class ThermophysicalProperties > static word typeName () inline static
Definition at line 81 of file thermophysicalPropertiesSelector.H.
properties()
template<class ThermophysicalProperties > const ThermophysicalProperties & properties () const inline
Definition at line 26 of file thermophysicalPropertiesSelectorI.H.
W()
template<class ThermophysicalProperties > Foam::scalar W () const inline
Definition at line 34 of file thermophysicalPropertiesSelectorI.H.
limit()
template<class ThermophysicalProperties > Foam::scalar limit (const scalar T) const inline
Definition at line 42 of file thermophysicalPropertiesSelectorI.H.
References T.
rho()
template<class ThermophysicalProperties > Foam::scalar rho (scalar p, scalar T) const inline
Definition at line 53 of file thermophysicalPropertiesSelectorI.H.
References p, and T.
psi()
template<class ThermophysicalProperties > Foam::scalar psi (scalar p, scalar T) const inline
Definition at line 65 of file thermophysicalPropertiesSelectorI.H.
References p, and T.
CpMCv()
template<class ThermophysicalProperties > Foam::scalar CpMCv (scalar p, scalar T) const inline
Definition at line 77 of file thermophysicalPropertiesSelectorI.H.
References p, and T.
Cp()
template<class ThermophysicalProperties > Foam::scalar Cp (const scalar p, const scalar T) const inline
Definition at line 89 of file thermophysicalPropertiesSelectorI.H.
References p, and T.
Ha()
template<class ThermophysicalProperties > Foam::scalar Ha (const scalar p, const scalar T) const inline
Definition at line 101 of file thermophysicalPropertiesSelectorI.H.
References p, and T.
Hs()
template<class ThermophysicalProperties > Foam::scalar Hs (const scalar p, const scalar T) const inline
Definition at line 113 of file thermophysicalPropertiesSelectorI.H.
References p, and T.
Hc()
template<class ThermophysicalProperties > Foam::scalar Hc () const inline
Definition at line 125 of file thermophysicalPropertiesSelectorI.H.
Cv()
template<class ThermophysicalProperties > Foam::scalar Cv (const scalar p, const scalar T) const inline
Definition at line 133 of file thermophysicalPropertiesSelectorI.H.
References p, and T.
Es()
template<class ThermophysicalProperties > Foam::scalar Es (const scalar p, const scalar T) const inline
Definition at line 145 of file thermophysicalPropertiesSelectorI.H.
References p, and T.
Ea()
template<class ThermophysicalProperties > Foam::scalar Ea (const scalar p, const scalar T) const inline
Definition at line 157 of file thermophysicalPropertiesSelectorI.H.
References p, and T.
S()
template<class ThermophysicalProperties > Foam::scalar S (const scalar p, const scalar T) const inline
Definition at line 169 of file thermophysicalPropertiesSelectorI.H.
References p, and T.
mu()
template<class ThermophysicalProperties > Foam::scalar mu (scalar p, scalar T) const inline
Definition at line 181 of file thermophysicalPropertiesSelectorI.H.
References p, and T.
kappa()
template<class ThermophysicalProperties > Foam::scalar kappa (scalar p, scalar T) const inline
Definition at line 193 of file thermophysicalPropertiesSelectorI.H.
References p, and T.
alphah()
template<class ThermophysicalProperties > Foam::scalar alphah (const scalar p, const scalar T) const inline
Definition at line 205 of file thermophysicalPropertiesSelectorI.H.
References p, and T.
Member Data Documentation
incompressible
template<class ThermophysicalProperties > const bool incompressible static
Initial value:
=
            ThermophysicalProperties::incompressible
Definition at line 70 of file thermophysicalPropertiesSelector.H.
isochoric
template<class ThermophysicalProperties > const bool isochoric static
Initial value:
=
            ThermophysicalProperties::isochoric
Definition at line 74 of file thermophysicalPropertiesSelector.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/thermophysicalProperties/thermophysicalPropertiesSelector/thermophysicalPropertiesSelector.H
src/thermophysicalModels/thermophysicalProperties/thermophysicalPropertiesSelector/thermophysicalPropertiesSelector.C
src/thermophysicalModels/thermophysicalProperties/thermophysicalPropertiesSelector/thermophysicalPropertiesSelectorI.H