OpenFOAM: sampledPatchInternalField Class Reference
sampledPatchInternalField Class Reference
Variation of sampledPatch that samples the internalField (at a given normal distance from the patch) instead of the patchField. Note:
#include <sampledPatchInternalField.H>
Public Member Functions
TypeName ("sampledPatchInternalField")
sampledPatchInternalField (const word &name, const polyMesh &mesh, const dictionary &dict)
virtual ~sampledPatchInternalField ()=default
virtual tmp< scalarField > sample (const interpolation< scalar > &sampler) const
virtual tmp< vectorField > sample (const interpolation< vector > &sampler) const
virtual tmp< sphericalTensorField > sample (const interpolation< sphericalTensor > &sampler) const
virtual tmp< symmTensorField > sample (const interpolation< symmTensor > &sampler) const
virtual tmp< tensorField > sample (const interpolation< tensor > &sampler) const
virtual tmp< scalarField > interpolate (const interpolation< scalar > &interpolator) const
virtual tmp< vectorField > interpolate (const interpolation< vector > &interpolator) const
virtual tmp< sphericalTensorField > interpolate (const interpolation< sphericalTensor > &interpolator) const
virtual tmp< symmTensorField > interpolate (const interpolation< symmTensor > &interpolator) const
virtual tmp< tensorField > interpolate (const interpolation< tensor > &interpolator) const
virtual void print (Ostream &os, int level=0) const
template<class Type >
Foam::tmp< Foam::Field< Type > > sampleOnFaces (const interpolation< Type > &sampler) const
template<class Type >
Foam::tmp< Foam::Field< Type > > sampleOnPoints (const interpolation< Type > &interpolator) const
Public Member Functions inherited from sampledPatch
TypeName ("sampledPatch")
sampledPatch (const word &name, const polyMesh &mesh, const UList< wordRe > &patchNames, const bool triangulate=false)
sampledPatch (const word &name, const polyMesh &mesh, const dictionary &dict)
virtual ~sampledPatch ()=default
virtual bool needsUpdate () const
virtual bool expire ()
virtual bool update ()
virtual const pointField & points () const
virtual const faceList & faces () const
virtual const labelList & zoneIds () const
virtual const vectorField & Sf () const
virtual const scalarField & magSf () const
virtual const vectorField & Cf () const
virtual bool withSurfaceFields () const
virtual tmp< scalarField > sample (const surfaceScalarField &) const
virtual tmp< vectorField > sample (const surfaceVectorField &) const
virtual tmp< sphericalTensorField > sample (const surfaceSphericalTensorField &) const
virtual tmp< symmTensorField > sample (const surfaceSymmTensorField &) const
virtual tmp< tensorField > sample (const surfaceTensorField &) const
template<class Type >
Foam::tmp< Foam::Field< Type > > sampleOnFaces (const interpolation< Type > &sampler) const
template<class Type >
Foam::tmp< Foam::Field< Type > > sampleOnFaces (const SurfaceField< Type > &sField) const
template<class Type >
Foam::tmp< Foam::Field< Type > > sampleOnPoints (const interpolation< Type > &interpolator) const
Public Member Functions inherited from MeshedSurface< face >
MeshedSurface ()
MeshedSurface (const MeshedSurface &surf)
MeshedSurface (const UnsortedMeshedSurface< face > &surf)
MeshedSurface (MeshedSurface &&surf)
MeshedSurface (UnsortedMeshedSurface< face > &&surf)
MeshedSurface (const pointField &pointLst, const UList< face > &faceLst, const UList< surfZone > &zoneLst)
MeshedSurface (pointField &&pointLst, List< face > &&faceLst, const UList< surfZone > &zoneLst)
MeshedSurface (const pointField &pointLst, const UList< face > &faceLst, const labelUList &zoneSizes=labelUList(), const UList< word > &zoneNames=UList< word >())
MeshedSurface (pointField &&pointLst, List< face > &&faceLst, const labelUList &zoneSizes=labelUList(), const UList< word > &zoneNames=UList< word >())
MeshedSurface (const polyBoundaryMesh &bMesh, const bool globalPoints=false)
MeshedSurface (const surfMesh &mesh)
MeshedSurface (const fileName &name)
MeshedSurface (const fileName &name, const word &fileType)
MeshedSurface (Istream &is)
MeshedSurface (const Time &runTime)
MeshedSurface (const Time &runTime, const word &surfName)
MeshedSurface (const IOobject &io, const dictionary &dict, const bool isGlobal=true)
MeshedSurface (const MeshedSurface< face > &surf)
MeshedSurface (MeshedSurface< face > &&surf)
bool read (const fileName &name, const word &fileType)
virtual bool read (const fileName &name)
virtual void write (const fileName &name, IOstreamOption streamOpt=IOstreamOption(), const dictionary &options=dictionary::null) const
virtual void write (const fileName &name, const word &fileType, IOstreamOption streamOpt=IOstreamOption(), const dictionary &options=dictionary::null) const
void write (const Time &runTime, const word &surfName=word::null) const
ClassName ("MeshedSurface")
declareRunTimeSelectionTable (autoPtr, MeshedSurface, fileExtension,(const fileName &name),(name))
virtual ~MeshedSurface ()
declareMemberFunctionSelectionTable (void, UnsortedMeshedSurface, write, fileExtension,(const fileName &name, const MeshedSurface< face > &surf, IOstreamOption streamOpt, const dictionary &options),(name, surf, streamOpt, options))
label size () const
const List< face > & surfFaces () const
const labelList & faceIds () const
const surfZoneList & surfZones () const
const vectorField & Sf () const
const scalarField & magSf () const
const vectorField & Cf () const
virtual void clear ()
virtual void addZones (const UList< surfZone > &, const bool cullEmpty=false)
virtual void addZones (const labelUList &sizes, const UList< word > &names, const bool cullEmpty=false)
virtual void addZones (const labelUList &sizes, const bool cullEmpty=false)
bool addZonesToFaces ()
bool addZonesToFaces ()
bool addZonesToFaces ()
virtual void removeZones ()
virtual void movePoints (const pointField &newPoints)
virtual void scalePoints (const scalar scaleFactor)
virtual void cleanup (const bool verbose)
virtual void compactPoints (labelList &pointMap=const_cast< labelList & >(labelList::null()))
virtual bool stitchFaces (const scalar tol=SMALL, const bool verbose=false)
virtual bool checkFaces (const bool verbose=false)
virtual label nTriangles () const
virtual label nTriangles (labelList &faceMap) const
virtual label triangulate ()
virtual label triangulate (labelList &faceMap)
void subsetMeshMap (const BoolListType &include, labelList &pointMap, labelList &faceMap) const
MeshedSurface subsetMesh (const UList< bool > &include, labelList &pointMap, labelList &faceMap) const
MeshedSurface subsetMesh (const bitSet &include, labelList &pointMap, labelList &faceMap) const
MeshedSurface subsetMesh (const UList< bool > &include) const
MeshedSurface subsetMesh (const bitSet &include) const
MeshedSurface subsetMesh (const wordRes &includeNames, const wordRes &excludeNames=wordRes()) const
void swap (MeshedSurface< face > &surf)
void transfer (pointField &pointLst, List< face > &faceLst)
void transfer (MeshedSurface< face > &surf)
void transfer (UnsortedMeshedSurface< face > &surf)
autoPtr< MeshedSurface< face > > releaseGeom ()
void swapFaces (List< face > &faces)
void swapPoints (pointField &points)
void writeStats (Ostream &os) const
void operator= (const MeshedSurface< face > &surf)
void operator= (MeshedSurface< face > &&surf)
operator MeshedSurfaceProxy< face > () const
Public Member Functions inherited from PrimitivePatch< FaceList, PointField >
PrimitivePatch (const FaceList &faces, const PointField &points)
PrimitivePatch (FaceList &&faces, const PointField &points)
PrimitivePatch (FaceList &faces, PointField &points, const bool reuse)
PrimitivePatch (const PrimitivePatch< FaceList, PointField > &pp)
virtual ~PrimitivePatch ()
void clearOut ()
void clearGeom ()
void clearTopology ()
void clearPatchMeshAddr ()
void swap (PrimitivePatch &)=delete
const Field< point_type > & points () const noexcept
label nFaces () const noexcept
label nPoints () const
label nEdges () const
const edgeList & edges () const
const edgeList::subList internalEdges () const
const edgeList::subList boundaryEdges () const
label nInternalEdges () const
label nBoundaryEdges () const
bool isInternalEdge (const label edgei) const
const labelList & boundaryPoints () const
const labelListList & faceFaces () const
const labelListList & edgeFaces () const
const labelListList & faceEdges () const
const labelListList & pointEdges () const
const labelListList & pointFaces () const
const List< face_type > & localFaces () const
labelList boundaryFaces () const
labelList uniqBoundaryFaces () const
const labelList & meshPoints () const
const Map< label > & meshPointMap () const
const Field< point_type > & localPoints () const
const labelList & localPointOrder () const
label whichPoint (const label gp) const
edge meshEdge (const label edgei) const
edge meshEdge (const edge &e) const
label findEdge (const edge &e) const
labelList meshEdges (const edgeList &allEdges, const labelListList &cellEdges, const labelList &faceCells) const
labelList meshEdges (const edgeList &allEdges, const labelListList &pointEdges) const
label meshEdge (const label edgei, const edgeList &allEdges, const labelListList &pointEdges) const
labelList meshEdges (const labelUList &edgeLabels, const edgeList &allEdges, const labelListList &pointEdges) const
const Field< point_type > & faceCentres () const
const Field< point_type > & faceAreas () const
const Field< scalar > & magFaceAreas () const
const Field< point_type > & faceNormals () const
const Field< point_type > & pointNormals () const
Pair< point_type > box () const
scalar sphere (const label facei) const
bool hasFaceAreas () const
bool hasFaceCentres () const
bool hasFaceNormals () const
bool hasPointNormals () const
bool hasBoundaryPoints () const
bool hasEdges () const
bool hasFaceFaces () const
bool hasEdgeFaces () const
bool hasFaceEdges () const
bool hasPointEdges () const
bool hasPointFaces () const
bool hasMeshPoints () const
bool hasMeshPointMap () const
template<class ToPatch >
List< objectHit > projectPoints (const ToPatch &targetPatch, const Field< point_type > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
template<class ToPatch >
List< objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< point_type > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
const labelListList & edgeLoops () const
surfaceTopo surfaceType (labelHashSet *badEdgesPtr=nullptr) const
bool checkTopology (const bool report=false, labelHashSet *pointSetPtr=nullptr) const
bool checkPointManifold (const bool report=false, labelHashSet *pointSetPtr=nullptr) const
virtual void movePoints (const Field< point_type > &)
void operator= (const PrimitivePatch< FaceList, PointField > &rhs)
void operator= (PrimitivePatch< FaceList, PointField > &&rhs)
label whichEdge (const edge &e) const
template<class ToPatch >
Foam::List< Foam::objectHit > projectPoints (const ToPatch &targetPatch, const Field< typename Foam::PrimitivePatch< FaceList, PointField >::point_type > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
template<class ToPatch >
Foam::List< Foam::objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< typename Foam::PrimitivePatch< FaceList, PointField >::point_type > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
Public Member Functions inherited from PrimitivePatchBase
ClassName ("PrimitivePatch")
PrimitivePatchBase ()=default
Public Member Functions inherited from surfaceFormatsCore
surfaceFormatsCore ()=default
virtual ~surfaceFormatsCore ()=default
Public Member Functions inherited from sampledSurface
TypeName ("sampledSurface")
declareRunTimeSelectionTable (autoPtr, sampledSurface, word,(const word &name, const polyMesh &mesh, const dictionary &dict),(name, mesh, dict))
sampledSurface (const word &name, const polyMesh &mesh, const bool interpolateToPoints=false)
sampledSurface (const word &name, const polyMesh &mesh, const dictionary &dict)
autoPtr< sampledSurface > clone () const
virtual ~sampledSurface ()
const polyMesh & mesh () const noexcept
const word & name () const noexcept
bool enabled () const noexcept
bool invariant () const noexcept
bool isPointData () const noexcept
virtual bool isPointData (const bool on)
scalar area () const
virtual bool hasFaceIds () const
polySurface * getRegistrySurface (const objectRegistry &obr, word lookupName="") const
polySurface * storeRegistrySurface (objectRegistry &obr, word lookupName="") const
bool removeRegistrySurface (objectRegistry &obr, word lookupName="") const
template<class Type , class GeoMeshType >
bool storeRegistryField (const objectRegistry &obr, const word &fieldName, const dimensionSet &dims, const Field< Type > &values, word lookupName="") const
template<class Type , class GeoMeshType >
bool storeRegistryField (const objectRegistry &obr, const word &fieldName, const dimensionSet &dims, Field< Type > &&values, word lookupName="") const
virtual void rename (const word &newName)
bool interpolate () const noexcept
template<class Type >
Foam::tmp< Foam::Field< Type > > sampleOnFaces (const interpolation< Type > &sampler, const labelUList &elements, const faceList &fcs, const pointField &pts, const Type &defaultValue)
template<class Type >
Foam::tmp< Foam::Field< Type > > sampleOnPoints (const interpolation< Type > &interpolator, const labelUList &elements, const faceList &fcs, const pointField &pts)
template<class Type >
Foam::tmp< Foam::VolumeField< Type > > pointAverage (const PointField< Type > &pfld)
Public Member Functions inherited from meshedSurf
constexpr meshedSurf () noexcept=default
virtual ~meshedSurf ()=default
virtual const labelList & faceIds () const
Additional Inherited Members
Public Types inherited from MeshedSurface< face >
typedef face face_type
typedef point point_type
Public Types inherited from PrimitivePatch< FaceList, PointField >
enum surfaceTopo { MANIFOLD , OPEN , ILLEGAL }
typedef std::remove_reference< FaceList >::type::value_type face_type
typedef std::remove_reference< PointField >::type::value_type point_type
typedef FaceList FaceListType
typedef PointField PointFieldType
typedef face_type FaceType
Static Public Member Functions inherited from MeshedSurface< face >
static void write (const fileName &name, const MeshedSurface< face > &surf, IOstreamOption streamOpt=IOstreamOption(), const dictionary &options=dictionary::null)
static void write (const fileName &name, const word &fileType, const MeshedSurface< face > &surf, IOstreamOption streamOpt=IOstreamOption(), const dictionary &options=dictionary::null)
static wordHashSet readTypes ()
static wordHashSet writeTypes ()
static bool canReadType (const word &fileType, bool verbose=false)
static bool canWriteType (const word &fileType, bool verbose=false)
static bool canRead (const fileName &name, bool verbose=false)
static autoPtr< MeshedSurface > New (const fileName &name, const word &fileType, bool mandatory=true)
static autoPtr< MeshedSurface > New (const fileName &name)
Static Public Member Functions inherited from surfaceFormatsCore
static bool checkSupport (const wordHashSet &available, const word &fileType, const bool verbose=false, const char *functionName=nullptr)
static fileName findFile (const IOobject &io, const bool isGlobal=true)
static fileName findFile (const IOobject &io, const dictionary &dict, const bool isGlobal=true)
Static Public Member Functions inherited from sampledSurface
static autoPtr< sampledSurface > New (const word &name, const polyMesh &mesh, const dictionary &dict)
Static Public Attributes inherited from surfaceFormatsCore
static word nativeExt
Protected Member Functions inherited from sampledPatch
const wordRes & patchNames () const
const labelList & patchIDs () const
const labelList & patchStart () const
const labelList & patchIndex () const
const labelList & patchFaceLabels () const
Protected Member Functions inherited from MeshedSurface< face >
void transcribe (MeshedSurface< face > &surf)
void transcribe (MeshedSurface< face > &surf)
void transcribe (MeshedSurface< face > &surf)
void transcribe (MeshedSurface< face > &surf)
void checkZones (const bool verbose=true)
pointField & storedPoints ()
List< face > & storedFaces ()
labelList & storedFaceIds ()
surfZoneList & storedZones ()
void sortFacesAndStore (DynamicList< face > &unsortedFaces, DynamicList< label > &zoneIds, DynamicList< label > &elemIds, bool sorted)
Protected Member Functions inherited from sampledSurface
virtual void clearGeom () const
sampledSurface (const word &name, std::nullptr_t)
Static Protected Member Functions inherited from surfaceFormatsCore
static string getLineNoComment (ISstream &is, const char comment='#')
template<class Container >
static List< surfZone > oneZone (const Container &container, const word &name="zone0")
static labelList getSelectedPatches (const surfZoneList &patches, const wordRes &allow, const wordRes &deny=wordRes())
static fileName relativeFilePath (const IOobject &io, const fileName &f, const bool isGlobal=true)
static fileName checkFile (const IOobject &io, const bool isGlobal=true)
static fileName checkFile (const IOobject &io, const dictionary &dict, const bool isGlobal=true)
Static Protected Member Functions inherited from sampledSurface
template<class Type >
static tmp< Field< Type > > sampleOnFaces (const interpolation< Type > &sampler, const labelUList &elements, const faceList &fcs, const pointField &pts, const Type &defaultValue=Type(Zero))
template<class Type >
static tmp< Field< Type > > sampleOnPoints (const interpolation< Type > &interpolator, const labelUList &elements, const faceList &fcs, const pointField &pts)
template<class Type >
static tmp< VolumeField< Type > > pointAverage (const PointField< Type > &pfld)
Detailed Description
Variation of sampledPatch that samples the internalField (at a given normal distance from the patch) instead of the patchField. Note:
interpolate=false : get cell value on faces
interpolate=true : interpolate inside cell and interpolate to points There is no option to get interpolated value inside the cell on the faces.
This is often embedded as part of a sampled surfaces function object.
Usage
Example of function object partial specification:
surfaces
{
    surface1
    {
        type    patchInternalField;
        patches (inlet "outlet.*");
        offsetMode  normal;
        distance    0.05;
    }
}
Where the sub-entries comprise:
Property Description Required Default
type patchInternalField yes
patches patch selection as word/regex list yes
offsetMode normal/uniform/nonuniform no normal
distance distance for normal offset partly
offset point offset for uniform offset partly
offsets point offsets for nonuniform offset partly
Source files
sampledPatchInternalField.H
sampledPatchInternalField.C
Definition at line 116 of file sampledPatchInternalField.H.
Constructor & Destructor Documentation
sampledPatchInternalField()
sampledPatchInternalField (const word & name, const polyMesh & mesh, const dictionary & dict)
Definition at line 47 of file sampledPatchInternalField.C.
References dict, Foam::distance(), forAll, sampledSurface::mesh(), Foam::mode(), Foam::name(), mappedPatchBase::NEARESTCELL, mappedPatchBase::NONUNIFORM, mappedPatchBase::NORMAL, word::null, mappedPatchBase::offsetModeNames_, sampledPatch::patchIDs(), PtrList< T >::set(), and mappedPatchBase::UNIFORM.
~sampledPatchInternalField()
virtual ~sampledPatchInternalField () virtual default
Member Function Documentation
TypeName()
TypeName ("sampledPatchInternalField")
sample() [1/5]
Foam::tmp< Foam::scalarField > sample (const interpolation< scalar > & sampler) const virtual
Reimplemented from sampledPatch.
Definition at line 133 of file sampledPatchInternalField.C.
sample() [2/5]
Foam::tmp< Foam::vectorField > sample (const interpolation< vector > & sampler) const virtual
Reimplemented from sampledPatch.
Definition at line 142 of file sampledPatchInternalField.C.
sample() [3/5]
Foam::tmp< Foam::sphericalTensorField > sample (const interpolation< sphericalTensor > & sampler) const virtual
Reimplemented from sampledPatch.
Definition at line 151 of file sampledPatchInternalField.C.
sample() [4/5]
Foam::tmp< Foam::symmTensorField > sample (const interpolation< symmTensor > & sampler) const virtual
Reimplemented from sampledPatch.
Definition at line 160 of file sampledPatchInternalField.C.
sample() [5/5]
Foam::tmp< Foam::tensorField > sample (const interpolation< tensor > & sampler) const virtual
Reimplemented from sampledPatch.
Definition at line 169 of file sampledPatchInternalField.C.
interpolate() [1/5]
Foam::tmp< Foam::scalarField > interpolate (const interpolation< scalar > & interpolator) const virtual
Reimplemented from sampledPatch.
Definition at line 178 of file sampledPatchInternalField.C.
interpolate() [2/5]
Foam::tmp< Foam::vectorField > interpolate (const interpolation< vector > & interpolator) const virtual
Reimplemented from sampledPatch.
Definition at line 187 of file sampledPatchInternalField.C.
interpolate() [3/5]
Foam::tmp< Foam::sphericalTensorField > interpolate (const interpolation< sphericalTensor > & interpolator) const virtual
Reimplemented from sampledPatch.
Definition at line 197 of file sampledPatchInternalField.C.
interpolate() [4/5]
Foam::tmp< Foam::symmTensorField > interpolate (const interpolation< symmTensor > & interpolator) const virtual
Reimplemented from sampledPatch.
Definition at line 206 of file sampledPatchInternalField.C.
interpolate() [5/5]
Foam::tmp< Foam::tensorField > interpolate (const interpolation< tensor > & interpolator) const virtual
Reimplemented from sampledPatch.
Definition at line 215 of file sampledPatchInternalField.C.
print()
void print (Ostream & os, int level = 0) const virtual
Reimplemented from sampledPatch.
Definition at line 224 of file sampledPatchInternalField.C.
References Foam::name(), os(), patchNames(), points, and UPtrList< T >::size().
sampleOnFaces()
template<class Type > Foam::tmp< Foam::Field< Type > > sampleOnFaces (const interpolation< Type > & sampler) const
Definition at line 30 of file sampledPatchInternalFieldTemplates.C.
References forAll, Foam::New(), sampledPatch::patchFaceLabels(), sampledPatch::patchStart(), MeshedSurface< face >::size(), and UPtrList< T >::size().
sampleOnPoints()
template<class Type > Foam::tmp< Foam::Field< Type > > sampleOnPoints (const interpolation< Type > & interpolator) const
Definition at line 67 of file sampledPatchInternalFieldTemplates.C.
References polyMesh::boundaryMesh(), forAll, VectorSpace< Form, Cmpt, Ncmpts >::max, mesh, patchId(), patchIDs(), points, pp(), samples(), and UPtrList< T >::size().
The documentation for this class was generated from the following files:
src/sampling/sampledSurface/sampledPatchInternalField/sampledPatchInternalField.H
src/sampling/sampledSurface/sampledPatchInternalField/sampledPatchInternalField.C
src/sampling/sampledSurface/sampledPatchInternalField/sampledPatchInternalFieldTemplates.C