OpenFOAM: nucleateFluxModel Class Reference
nucleateFluxModel Class Reference abstract
Base class for nucleation flux models.
#include <nucleateFluxModel.H>
Public Member Functions
TypeName ("nucleateFluxModel")
declareRunTimeSelectionTable (autoPtr, nucleateFluxModel, dictionary,(const dictionary &dict),(dict))
nucleateFluxModel ()=default
virtual ~nucleateFluxModel ()=default
virtual tmp< scalarField > qNucleate (const phaseModel &liquid, const phaseModel &vapor, const label patchi, const scalarField &Tl, const scalarField &Tsatw, const scalarField &L) const =0
virtual void write (Ostream &os) const
Static Public Member Functions
static autoPtr< nucleateFluxModel > New (const dictionary &dict)
Detailed Description
Base class for nucleation flux models.
Source files
nucleateFluxModel.H
nucleateFluxModel.C
Definition at line 50 of file nucleateFluxModel.H.
Constructor & Destructor Documentation
nucleateFluxModel()
nucleateFluxModel () default
~nucleateFluxModel()
virtual ~nucleateFluxModel () virtual default
Member Function Documentation
TypeName()
TypeName ("nucleateFluxModel")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , nucleateFluxModel , dictionary , (const dictionary &dict) , (dict))
New()
Foam::autoPtr< Foam::wallBoilingModels::nucleateFluxModel > New (const dictionary & dict) static
Definition at line 37 of file nucleateFluxModel.C.
References Foam::abort(), dict, Foam::endl(), Foam::FatalIOError, FatalIOErrorInLookup, and Foam::Info.
Referenced by alphatWallBoilingWallFunctionFvPatchScalarField::alphatWallBoilingWallFunctionFvPatchScalarField().
qNucleate()
virtual tmp< scalarField > qNucleate (const phaseModel & liquid, const phaseModel & vapor, const label patchi, const scalarField & Tl, const scalarField & Tsatw, const scalarField & L) const pure virtual
Implemented in exponential, and Kutadeladze.
write()
void write (Ostream & os) const virtual
Reimplemented in exponential, and Kutadeladze.
Definition at line 65 of file nucleateFluxModel.C.
References os(), and Foam::type().
Referenced by exponential::write(), and Kutadeladze::write().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/wallBoilingSubModels/nucleateFluxModels/nucleateFluxModel/nucleateFluxModel.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/wallBoilingSubModels/nucleateFluxModels/nucleateFluxModel/nucleateFluxModel.C