OpenFOAM: extendedCellToCellStencil Class Reference
extendedCellToCellStencil Class Reference
Baseclass for cell-to-cell stencils.
#include <extendedCellToCellStencil.H>
Public Member Functions
extendedCellToCellStencil (const polyMesh &)
template<class Type , class WeightType >
Foam::tmp< Foam::GeometricField< typename Foam::outerProduct< WeightType, Type >::type, Foam::fvPatchField, Foam::volMesh > > weightedSum (const mapDistribute &map, const labelListList &stencil, const GeometricField< Type, fvPatchField, volMesh > &fld, const List< List< WeightType > > &stencilWeights)
Static Public Member Functions
template<class Type , class WeightType >
static tmp< GeometricField< typename outerProduct< WeightType, Type >::type, fvPatchField, volMesh > > weightedSum (const mapDistribute &map, const labelListList &stencil, const GeometricField< Type, fvPatchField, volMesh > &fld, const List< List< WeightType > > &stencilWeights)
Protected Attributes
const polyMesh & mesh_
Detailed Description
Baseclass for cell-to-cell stencils.
Source files
extendedCellToCellStencil.H
extendedCellToCellStencil.C
extendedCellToCellStencilTemplates.C
Definition at line 50 of file extendedCellToCellStencil.H.
Constructor & Destructor Documentation
extendedCellToCellStencil()
extendedCellToCellStencil (const polyMesh & mesh) explicit
Definition at line 25 of file extendedCellToCellStencil.C.
References coupled(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, mesh, and patches.
Member Function Documentation
weightedSum() [1/2]
template<class Type , class WeightType > static tmp< GeometricField< typename outerProduct< WeightType, Type >::type, fvPatchField, volMesh > > weightedSum (const mapDistribute & map, const labelListList & stencil, const GeometricField< Type, fvPatchField, volMesh > & fld, const List< List< WeightType > > & stencilWeights) static
Referenced by extendedCentredCellToCellStencil::weightedSum().
weightedSum() [2/2]
template<class Type , class WeightType > Foam::tmp< Foam::GeometricField< typename Foam::outerProduct< WeightType, Type >::type, Foam::fvPatchField, Foam::volMesh > > weightedSum (const mapDistribute & map, const labelListList & stencil, const GeometricField< Type, fvPatchField, volMesh > & fld, const List< List< WeightType > > & stencilWeights)
Definition at line 35 of file extendedCellToCellStencilTemplates.C.
References extendedCellToFaceStencil::collectData(), fld(), forAll, mesh, and Foam::Zero.
Member Data Documentation
mesh_
const polyMesh& mesh_ protected
Definition at line 56 of file extendedCellToCellStencil.H.
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/extendedStencil/cellToCell/extendedCellToCellStencil.H
src/finiteVolume/fvMesh/extendedStencil/cellToCell/extendedCellToCellStencil.C
src/finiteVolume/fvMesh/extendedStencil/cellToCell/extendedCellToCellStencilTemplates.C