OpenFOAM: mapNearestMethod Class Reference
mapNearestMethod Class Reference
Map nearest mesh-to-mesh interpolation class.
#include <mapNearestMethod.H>
Public Member Functions
TypeName ("mapNearest")
mapNearestMethod (const polyMesh &src, const polyMesh &tgt)
virtual ~mapNearestMethod ()
virtual void calculate (labelListList &srcToTgtAddr, scalarListList &srcToTgtWght, pointListList &srcToTgtVec, labelListList &tgtToSrcAddr, scalarListList &tgtToSrcWght, pointListList &tgtToSrcVec)
Public Member Functions inherited from meshToMeshMethod
TypeName ("meshToMeshMethod")
declareRunTimeSelectionTable (autoPtr, meshToMeshMethod, components,(const polyMesh &src, const polyMesh &tgt),(src, tgt))
meshToMeshMethod (const polyMesh &src, const polyMesh &tgt)
virtual ~meshToMeshMethod ()
const polyMesh & src () const
const polyMesh & tgt () const
scalar V () const
void writeConnectivity (const polyMesh &mesh1, const polyMesh &mesh2, const labelListList &mesh1ToMesh2Addr) const
Protected Member Functions
virtual bool findInitialSeeds (const labelList &srcCellIDs, const boolList &mapFlag, const label startSeedI, label &srcSeedI, label &tgtSeedI) const
virtual void calculateAddressing (labelListList &srcToTgtCellAddr, scalarListList &srcToTgtCellWght, labelListList &tgtToSrcCellAddr, scalarListList &tgtToSrcCellWght, const label srcSeedI, const label tgtSeedI, const labelList &srcCellIDs, boolList &mapFlag, label &startSeedI)
virtual void findNearestCell (const polyMesh &mesh1, const polyMesh &mesh2, const label cell1, label &cell2) const
virtual void setNextNearestCells (label &startSeedI, label &srcCelli, label &tgtCelli, boolList &mapFlag, const labelList &srcCellIDs) const
virtual label findMappedSrcCell (const label tgtCelli, const List< DynamicList< label > > &tgtToSrc) const
mapNearestMethod (const mapNearestMethod &)=delete
void operator= (const mapNearestMethod &)=delete
Protected Member Functions inherited from meshToMeshMethod
labelList maskCells () const
virtual bool intersect (const label srcCelli, const label tgtCelli) const
virtual scalar interVol (const label srcCelli, const label tgtCelli) const
virtual Tuple2< scalar, point > interVolAndCentroid (const label srcCellI, const label tgtCellI)
virtual void appendNbrCells (const label tgtCelli, const polyMesh &mesh, const DynamicList< label > &visitedTgtCells, DynamicList< label > &nbrTgtCellIDs) const
virtual bool initialise (labelListList &srcToTgtAddr, scalarListList &srcToTgtWght, labelListList &tgtToTgtAddr, scalarListList &tgtToTgtWght) const
Additional Inherited Members
Static Public Member Functions inherited from meshToMeshMethod
static autoPtr< meshToMeshMethod > New (const word &methodName, const polyMesh &src, const polyMesh &tgt)
Protected Attributes inherited from meshToMeshMethod
const polyMesh & src_
const polyMesh & tgt_
scalar V_
Static Protected Attributes inherited from meshToMeshMethod
static scalar tolerance_ = 1e-6
Detailed Description
Map nearest mesh-to-mesh interpolation class.
Not volume conservative.
cells outside other meshes bounding box do not get mapped (initial filtering)
all remaining cells will be mapped (with weight 1!)
so take care when mapping meshes with different bounding boxes!
Source files
mapNearestMethod.H
mapNearestMethod.C
Definition at line 52 of file mapNearestMethod.H.
Constructor & Destructor Documentation
mapNearestMethod() [1/2]
mapNearestMethod (const mapNearestMethod &) protected delete
mapNearestMethod() [2/2]
mapNearestMethod (const polyMesh & src, const polyMesh & tgt)
Definition at line 331 of file mapNearestMethod.C.
~mapNearestMethod()
~mapNearestMethod () virtual
Definition at line 343 of file mapNearestMethod.C.
Member Function Documentation
findInitialSeeds()
bool findInitialSeeds (const labelList & srcCellIDs, const boolList & mapFlag, const label startSeedI, label & srcSeedI, label & tgtSeedI) const protected virtual
Definition at line 38 of file mapNearestMethod.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, PointIndexHit< PointType >::hit(), PointIndexHit< PointType >::index(), Foam::Pout, UPtrList< T >::size(), meshToMeshMethod::src_, and meshToMeshMethod::tgt_.
calculateAddressing()
void calculateAddressing (labelListList & srcToTgtCellAddr, scalarListList & srcToTgtCellWght, labelListList & tgtToSrcCellAddr, scalarListList & tgtToSrcCellWght, const label srcSeedI, const label tgtSeedI, const labelList & srcCellIDs, boolList & mapFlag, label & startSeedI) protected virtual
Definition at line 88 of file mapNearestMethod.C.
References PtrList< T >::append(), PtrList< T >::clear(), forAll, Foam::magSqr(), UPtrList< T >::size(), and List< T >::transfer().
findNearestCell()
void findNearestCell (const polyMesh & mesh1, const polyMesh & mesh2, const label cell1, label & cell2) const protected virtual
Definition at line 200 of file mapNearestMethod.C.
References UPtrList< T >::back(), Vector< Cmpt >::distSqr(), UPtrList< T >::empty(), and PtrList< T >::push_back().
setNextNearestCells()
void setNextNearestCells (label & startSeedI, label & srcCelli, label & tgtCelli, boolList & mapFlag, const labelList & srcCellIDs) const protected virtual
Definition at line 239 of file mapNearestMethod.C.
References forAll, and UPtrList< T >::size().
findMappedSrcCell()
Foam::label findMappedSrcCell (const label tgtCelli, const List< DynamicList< label > > & tgtToSrc) const protected virtual
Definition at line 282 of file mapNearestMethod.C.
References UPtrList< T >::back(), UPtrList< T >::empty(), and PtrList< T >::push_back().
operator=()
void operator= (const mapNearestMethod &) protected delete
TypeName()
TypeName ("mapNearest")
calculate()
void calculate (labelListList & srcToTgtAddr, scalarListList & srcToTgtWght, pointListList & srcToTgtVec, labelListList & tgtToSrcAddr, scalarListList & tgtToSrcWght, pointListList & tgtToSrcVec) virtual
Implements meshToMeshMethod.
Definition at line 349 of file mapNearestMethod.C.
The documentation for this class was generated from the following files:
src/sampling/meshToMesh/calcMethod/mapNearest/mapNearestMethod.H
src/sampling/meshToMesh/calcMethod/mapNearest/mapNearestMethod.C