OpenFOAM: mapDistribute::transform Class Reference
mapDistribute::transform Class Reference
#include <mapDistribute.H>
Public Member Functions
template<class Type >
void operator() (const vectorTensorTransform &vt, const bool forward, List< Type > &fld) const
template<class Type >
void operator() (const vectorTensorTransform &vt, const bool forward, List< List< Type > > &flds) const
template<class Type >
void operator() (const coupledPolyPatch &cpp, UList< Type > &fld) const
template<class Type , template< class > class Container>
void operator() (const coupledPolyPatch &cpp, Container< Type > &map) const
template<>
void operator() (const vectorTensorTransform &, const bool, List< label > &) const
template<>
void operator() (const coupledPolyPatch &, UList< label > &) const
template<>
void operator() (const coupledPolyPatch &, Map< label > &) const
template<>
void operator() (const coupledPolyPatch &, EdgeMap< label > &) const
template<>
void operator() (const vectorTensorTransform &, const bool, List< scalar > &) const
template<>
void operator() (const coupledPolyPatch &, UList< scalar > &) const
template<>
void operator() (const coupledPolyPatch &, Map< scalar > &) const
template<>
void operator() (const coupledPolyPatch &, EdgeMap< scalar > &) const
template<>
void operator() (const vectorTensorTransform &, const bool, List< bool > &) const
template<>
void operator() (const coupledPolyPatch &, UList< bool > &) const
template<>
void operator() (const coupledPolyPatch &, Map< bool > &) const
template<>
void operator() (const coupledPolyPatch &, EdgeMap< bool > &) const
Detailed Description
Definition at line 202 of file mapDistribute.H.
Member Function Documentation
operator()() [1/16]
template<class Type > void operator() (const vectorTensorTransform & vt, const bool forward, List< Type > & fld) const inline
Definition at line 207 of file mapDistribute.H.
References fld(), T, and Foam::transformList().
Referenced by mapDistribute::transform::operator()().
operator()() [2/16]
template<class Type > void operator() (const vectorTensorTransform & vt, const bool forward, List< List< Type > > & flds) const inline
Definition at line 219 of file mapDistribute.H.
References fld(), and mapDistribute::transform::operator()().
operator()() [3/16]
template<class Type > void operator() (const coupledPolyPatch & cpp, UList< Type > & fld) const inline
Definition at line 234 of file mapDistribute.H.
References fld(), and Foam::transformList().
operator()() [4/16]
template<class Type , template< class > class Container> void operator() (const coupledPolyPatch & cpp, Container< Type > & map) const inline
Definition at line 244 of file mapDistribute.H.
References Foam::transformList().
operator()() [5/16]
void operator() (const vectorTensorTransform & , const bool , List< label > &) const
Definition at line 37 of file mapDistribute.C.
operator()() [6/16]
void operator() (const coupledPolyPatch & , UList< label > &) const
Definition at line 45 of file mapDistribute.C.
operator()() [7/16]
void operator() (const coupledPolyPatch & , Map< label > &) const
Definition at line 52 of file mapDistribute.C.
operator()() [8/16]
void operator() (const coupledPolyPatch & , EdgeMap< label > &) const
Definition at line 59 of file mapDistribute.C.
operator()() [9/16]
void operator() (const vectorTensorTransform & , const bool , List< scalar > &) const
Definition at line 67 of file mapDistribute.C.
operator()() [10/16]
void operator() (const coupledPolyPatch & , UList< scalar > &) const
Definition at line 75 of file mapDistribute.C.
operator()() [11/16]
void operator() (const coupledPolyPatch & , Map< scalar > &) const
Definition at line 82 of file mapDistribute.C.
operator()() [12/16]
void operator() (const coupledPolyPatch & , EdgeMap< scalar > &) const
Definition at line 89 of file mapDistribute.C.
operator()() [13/16]
void operator() (const vectorTensorTransform & , const bool , List< bool > &) const
Definition at line 97 of file mapDistribute.C.
operator()() [14/16]
void operator() (const coupledPolyPatch & , UList< bool > &) const
Definition at line 105 of file mapDistribute.C.
operator()() [15/16]
void operator() (const coupledPolyPatch & , Map< bool > &) const
Definition at line 112 of file mapDistribute.C.
operator()() [16/16]
void operator() (const coupledPolyPatch & , EdgeMap< bool > &) const
Definition at line 119 of file mapDistribute.C.
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/mapDistribute/mapDistribute.H
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/mapDistribute/mapDistribute.C