OpenFOAM: LaunderSharmaKE< BasicTurbulenceModel > Class Template Reference
LaunderSharmaKE< BasicTurbulenceModel > Class Template Reference
Turbulence models » RAS turbulence
Launder and Sharma low-Reynolds k-epsilon turbulence model for incompressible and compressible and combusting flows including rapid distortion theory (RDT) based compression term.
#include <LaunderSharmaKE.H>
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from linearViscousStress< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("LaunderSharmaKE")
LaunderSharmaKE (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
virtual ~LaunderSharmaKE ()=default
virtual bool read ()
tmp< volScalarField > DkEff () const
tmp< volScalarField > DepsilonEff () const
virtual tmp< volScalarField > k () const
virtual tmp< volScalarField > epsilon () const
virtual void correct ()
Public Member Functions inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
eddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~eddyViscosity ()=default
virtual tmp< volScalarField > nut () const
virtual tmp< scalarField > nut (const label patchi) const
virtual tmp< volSymmTensorField > R () const
virtual void validate ()
Public Member Functions inherited from linearViscousStress< BasicTurbulenceModel >
linearViscousStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~linearViscousStress ()=default
virtual tmp< volSymmTensorField > devRhoReff () const
virtual tmp< volSymmTensorField > devRhoReff (const volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Protected Member Functions
tmp< volScalarField > fMu () const
tmp< volScalarField > f2 () const
virtual void correctNut ()
virtual tmp< fvScalarMatrix > kSource () const
virtual tmp< fvScalarMatrix > epsilonSource () const
Protected Attributes
dimensionedScalar Cmu_
dimensionedScalar C1_
dimensionedScalar C2_
dimensionedScalar C3_
dimensionedScalar sigmak_
dimensionedScalar sigmaEps_
volScalarField k_
volScalarField epsilon_
Protected Attributes inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
volScalarField nut_
Detailed Description
template<class BasicTurbulenceModel>
class Foam::RASModels::LaunderSharmaKE< BasicTurbulenceModel >
Launder and Sharma low-Reynolds k-epsilon turbulence model for incompressible and compressible and combusting flows including rapid distortion theory (RDT) based compression term.
References:
    Launder, B. E., & Sharma, B. I. (1974).
    Application of the energy-dissipation model of turbulence to the
    calculation of flow near a spinning disc.
    Letters in heat and mass transfer, 1(2), 131-137.
    For the RDT-based compression term:
    El Tahry, S. H. (1983).
    k-epsilon equation for compressible reciprocating engine flows.
    Journal of Energy, 7(4), 345-353.
The default model coefficients are
    LaunderSharmaKECoeffs
    {
        Cmu         0.09;
        C1          1.44;
        C2          1.92;
        C3          -0.33;
        alphah      1.0;    // only for compressible
        alphahk     1.0;    // only for compressible
        alphaEps    0.76923;
    }
Source files
LaunderSharmaKE.H
LaunderSharmaKE.C
Definition at line 83 of file LaunderSharmaKE.H.
Member Typedef Documentation
alphaField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 128 of file LaunderSharmaKE.H.
rhoField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 129 of file LaunderSharmaKE.H.
transportModel
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 130 of file LaunderSharmaKE.H.
Constructor & Destructor Documentation
LaunderSharmaKE()
template<class BasicTurbulenceModel > LaunderSharmaKE (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Definition at line 95 of file LaunderSharmaKE.C.
References Foam::bound(), LaunderSharmaKE< BasicTurbulenceModel >::epsilon_, LaunderSharmaKE< BasicTurbulenceModel >::k_, and Foam::type().
~LaunderSharmaKE()
template<class BasicTurbulenceModel > virtual ~LaunderSharmaKE () virtual default
Member Function Documentation
fMu()
template<class BasicTurbulenceModel > tmp< volScalarField > fMu () const protected
Definition at line 36 of file LaunderSharmaKE.C.
References Foam::exp(), nu, and Foam::sqr().
f2()
template<class BasicTurbulenceModel > tmp< volScalarField > f2 () const protected
Definition at line 43 of file LaunderSharmaKE.C.
References Foam::exp(), Foam::min(), nu, and Foam::sqr().
correctNut()
template<class BasicTurbulenceModel > void correctNut () protected virtual
Implements eddyViscosity< RASModel< BasicTurbulenceModel > >.
Definition at line 52 of file LaunderSharmaKE.C.
References options::New(), and Foam::sqr().
kSource()
template<class BasicTurbulenceModel > tmp< fvScalarMatrix > kSource () const protected virtual
Definition at line 63 of file LaunderSharmaKE.C.
References Foam::dimTime, and Foam::dimVolume.
epsilonSource()
template<class BasicTurbulenceModel > tmp< fvScalarMatrix > epsilonSource () const protected virtual
Definition at line 78 of file LaunderSharmaKE.C.
References Foam::dimTime, and Foam::dimVolume.
TypeName()
template<class BasicTurbulenceModel > TypeName ("LaunderSharmaKE< BasicTurbulenceModel >")
read()
template<class BasicTurbulenceModel > bool read () virtual
Implements eddyViscosity< RASModel< BasicTurbulenceModel > >.
Definition at line 213 of file LaunderSharmaKE.C.
References Foam::read().
DkEff()
template<class BasicTurbulenceModel > tmp< volScalarField > DkEff () const inline
Definition at line 163 of file LaunderSharmaKE.H.
References nu, and eddyViscosity< RASModel< BasicTurbulenceModel > >::nut_.
DepsilonEff()
template<class BasicTurbulenceModel > tmp< volScalarField > DepsilonEff () const inline
Definition at line 176 of file LaunderSharmaKE.H.
References nu, and eddyViscosity< RASModel< BasicTurbulenceModel > >::nut_.
k()
template<class BasicTurbulenceModel > virtual tmp< volScalarField > k () const inline virtual
Implements eddyViscosity< RASModel< BasicTurbulenceModel > >.
Definition at line 189 of file LaunderSharmaKE.H.
References LaunderSharmaKE< BasicTurbulenceModel >::k_.
epsilon()
template<class BasicTurbulenceModel > virtual tmp< volScalarField > epsilon () const inline virtual
Definition at line 195 of file LaunderSharmaKE.H.
References LaunderSharmaKE< BasicTurbulenceModel >::epsilon_.
correct()
template<class BasicTurbulenceModel > void correct () virtual
Implements eddyViscosity< RASModel< BasicTurbulenceModel > >.
Definition at line 232 of file LaunderSharmaKE.C.
References Foam::fvc::absolute(), alpha, Foam::bound(), PtrList< T >::clear(), correct(), D, Foam::fvm::ddt(), Foam::devTwoSymm(), Foam::fvc::div(), Foam::fvm::div(), divU, fvOptions, Foam::fvc::grad(), Foam::fvm::laplacian(), Foam::magSqr(), Foam::fvc::magSqrGradGrad(), options::New(), nu, nut, phi, rho, solve(), Foam::fvm::Sp(), Foam::sqrt(), Foam::fvm::SuSp(), and U.
Member Data Documentation
Cmu_
template<class BasicTurbulenceModel > dimensionedScalar Cmu_ protected
Definition at line 102 of file LaunderSharmaKE.H.
C1_
template<class BasicTurbulenceModel > dimensionedScalar C1_ protected
Definition at line 103 of file LaunderSharmaKE.H.
C2_
template<class BasicTurbulenceModel > dimensionedScalar C2_ protected
Definition at line 104 of file LaunderSharmaKE.H.
C3_
template<class BasicTurbulenceModel > dimensionedScalar C3_ protected
Definition at line 105 of file LaunderSharmaKE.H.
sigmak_
template<class BasicTurbulenceModel > dimensionedScalar sigmak_ protected
Definition at line 106 of file LaunderSharmaKE.H.
sigmaEps_
template<class BasicTurbulenceModel > dimensionedScalar sigmaEps_ protected
Definition at line 107 of file LaunderSharmaKE.H.
k_
template<class BasicTurbulenceModel > volScalarField k_ protected
Definition at line 112 of file LaunderSharmaKE.H.
Referenced by LaunderSharmaKE< BasicTurbulenceModel >::k(), and LaunderSharmaKE< BasicTurbulenceModel >::LaunderSharmaKE().
epsilon_
template<class BasicTurbulenceModel > volScalarField epsilon_ protected
Definition at line 113 of file LaunderSharmaKE.H.
Referenced by LaunderSharmaKE< BasicTurbulenceModel >::epsilon(), and LaunderSharmaKE< BasicTurbulenceModel >::LaunderSharmaKE().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/RAS/LaunderSharmaKE/LaunderSharmaKE.H
src/TurbulenceModels/turbulenceModels/RAS/LaunderSharmaKE/LaunderSharmaKE.C