OpenFOAM: GidaspowErgunWenYu Class Reference
GidaspowErgunWenYu Class Reference
D. Gidaspow, Multiphase flow and fluidization, Academic Press, New York, 1994.
#include <GidaspowErgunWenYu.H>
Public Member Functions
TypeName ("GidaspowErgunWenYu")
GidaspowErgunWenYu (const dictionary &interfaceDict, const phaseModel &phase1, const phaseModel &phase2)
virtual ~GidaspowErgunWenYu ()
tmp< volScalarField > K (const volScalarField &Ur) const
Public Member Functions inherited from dragModel
TypeName ("dragModel")
declareRunTimeSelectionTable (autoPtr, dragModel, dictionary,(const dictionary &interfaceDict, const phaseModel &phase1, const phaseModel &phase2),(interfaceDict, phase1, phase2))
dragModel (const dictionary &dict, const phaseModel &phase1, const phaseModel &phase2)
virtual ~dragModel ()=default
const phaseModel & phase1 () const
const phaseModel & phase2 () const
const dimensionedScalar & residualPhaseFraction () const
const dimensionedScalar & residualSlip () const
Additional Inherited Members
Static Public Member Functions inherited from dragModel
static autoPtr< dragModel > New (const dictionary &dict, const phaseModel &phase1, const phaseModel &phase2)
Protected Attributes inherited from dragModel
const dictionary & interfaceDict_
const phaseModel & phase1_
const phaseModel & phase2_
dimensionedScalar residualPhaseFraction_
dimensionedScalar residualSlip_
Detailed Description
D. Gidaspow, Multiphase flow and fluidization, Academic Press, New York, 1994.
Source files
GidaspowErgunWenYu.H
GidaspowErgunWenYu.C
Definition at line 52 of file GidaspowErgunWenYu.H.
Constructor & Destructor Documentation
GidaspowErgunWenYu()
GidaspowErgunWenYu (const dictionary & interfaceDict, const phaseModel & phase1, const phaseModel & phase2)
Definition at line 48 of file GidaspowErgunWenYu.C.
~GidaspowErgunWenYu()
~GidaspowErgunWenYu () virtual
Definition at line 61 of file GidaspowErgunWenYu.C.
Member Function Documentation
TypeName()
TypeName ("GidaspowErgunWenYu")
K()
Foam::tmp< Foam::volScalarField > K (const volScalarField & Ur) const virtual
Implements dragModel.
Definition at line 68 of file GidaspowErgunWenYu.C.
References alpha2, Foam::max(), Foam::neg(), Foam::pos0(), Foam::pow(), Foam::Re(), and Foam::sqr().
The documentation for this class was generated from the following files:
src/phaseSystemModels/multiphaseEuler/multiphaseSystem/interfacialModels/dragModels/GidaspowErgunWenYu/GidaspowErgunWenYu.H
src/phaseSystemModels/multiphaseEuler/multiphaseSystem/interfacialModels/dragModels/GidaspowErgunWenYu/GidaspowErgunWenYu.C