OpenFOAM: GenericPatchWriter< PatchType > Class Template Reference
GenericPatchWriter< PatchType > Class Template Reference
Write concrete PrimitivePatch faces/points (optionally with fields) as a vtp file or a legacy vtk file. The patch type is limited to representations of polygon faces and 3D points and must support the following methods:
#include <foamVtkGenericPatchWriter.H>
Public Member Functions
GenericPatchWriter (const PatchType &pp, const vtk::outputOptions opts=vtk::formatType::INLINE_BASE64)
GenericPatchWriter (const PatchType &pp, const fileName &file, bool parallel=Pstream::parRun())
GenericPatchWriter (const PatchType &pp, const vtk::outputOptions opts, const fileName &file, bool parallel=Pstream::parRun())
virtual ~GenericPatchWriter ()=default
const PatchType & patch () const noexcept
virtual bool beginFile (std::string title="surface")
virtual bool writeGeometry ()
bool writeProcIDs ()
Public Member Functions inherited from polyWriter
polyWriter (const vtk::outputOptions opts=vtk::formatType::INLINE_BASE64)
polyWriter (const fileName &file, bool parallel=Pstream::parRun())
polyWriter (const vtk::outputOptions opts, const fileName &file, bool parallel=Pstream::parRun())
virtual ~polyWriter ()=default
bool writeLineGeometry (const pointField &points, const edgeList &edges)
bool writePolyGeometry (const pointField &points, const faceList &faces)
virtual bool beginCellData (label nFields=0)
virtual bool beginPointData (label nFields=0)
template<class Type >
void write (const word &fieldName, const UList< Type > &field)
template<class Type >
void writeCellData (const word &fieldName, const UList< Type > &field)
template<class Type >
void writePointData (const word &fieldName, const UList< Type > &field)
Public Member Functions inherited from fileWriter
fileWriter (const vtk::fileTag contentType, const vtk::outputOptions opts)
virtual ~fileWriter ()
vtk::fileTag contentType () const noexcept
vtk::outputOptions opts () const noexcept
word ext () const
bool legacy () const noexcept
bool parallel () const noexcept
const word & state () const
const fileName & output () const noexcept
virtual bool open (const fileName &file, bool parallel=UPstream::parRun())
void close ()
bool beginFieldData (label nFields=0)
bool isCellData () const noexcept
bool isPointData () const noexcept
label nCellData () const noexcept
label nPointData () const noexcept
bool endFieldData ()
bool endCellData ()
bool endPointData ()
void writeTimeValue (scalar timeValue)
Additional Inherited Members
Static Public Member Functions inherited from polyWriter
static word ext (vtk::outputOptions opts)
Protected Types inherited from fileWriter
enum outputState : uint8_t {
CLOSED = 0 , OPENED , DECLARED , FIELD_DATA ,
PIECE , CELL_DATA , POINT_DATA
}
Protected Member Functions inherited from polyWriter
template<class Type >
void writeUniformValue (const label nCellValues, const word &fieldName, const Type &val)
Protected Member Functions inherited from fileWriter
void checkFormatterValidity () const
Ostream & reportBadState (Ostream &, outputState expected) const
Ostream & reportBadState (Ostream &, outputState, outputState) const
std::ofstream & os () noexcept
vtk::formatter & format ()
bool isState (outputState test) const noexcept
bool notState (outputState test) const noexcept
template<class Type >
void beginDataArray (const word &fieldName, const label nValues)
void endDataArray ()
void beginPoints (const label nPoints)
void endPoints ()
bool enter_Piece ()
bool endPiece ()
bool enter_CellData (label nEntries, label nFields)
bool enter_PointData (label nEntries, label nFields)
bool exit_File ()
template<class Type >
void writeUniform (const word &fieldName, const Type &val, const label nValues)
template<class Type >
void writeBasicField (const word &fieldName, const UList< Type > &field)
bool writeProcIDs (const label nValues)
fileWriter (const fileWriter &)=delete
void operator= (const fileWriter &)=delete
Protected Attributes inherited from polyWriter
label numberOfPoints_
label numberOfCells_
label nLocalPoints_
label nLocalVerts_
label nLocalLines_
label nLocalPolys_
Protected Attributes inherited from fileWriter
outputState state_
vtk::fileTag contentType_
bool parallel_
vtk::outputOptions opts_
label nCellData_
label nPointData_
fileName outputFile_
autoPtr< vtk::formatter > format_
std::ofstream os_
Static Protected Attributes inherited from fileWriter
static const Enum< outputState > stateNames
Detailed Description
template<class PatchType>
class Foam::vtk::GenericPatchWriter< PatchType >
Write concrete PrimitivePatch faces/points (optionally with fields) as a vtp file or a legacy vtk file. The patch type is limited to representations of polygon faces and 3D points and must support the following methods:
localPoints()
localFaces()
The file output states are managed by the Foam::vtk::fileWriter class. FieldData (eg, TimeValue) must appear before any geometry pieces.
Note
Parallel output is combined into a single Piece without point merging, which is similar to using multi-piece data sets, but allows more convenient creation as a streaming process.
Definition at line 59 of file foamVtkGenericPatchWriter.H.
Constructor & Destructor Documentation
GenericPatchWriter() [1/3]
template<class PatchType > GenericPatchWriter (const PatchType & pp, const vtk::outputOptions opts = vtk::formatType::INLINE_BASE64) inline explicit
Definition at line 83 of file foamVtkGenericPatchWriter.H.
GenericPatchWriter() [2/3]
template<class PatchType > GenericPatchWriter (const PatchType & pp, const fileName & file, bool parallel = Pstream::parRun()) inline
Definition at line 96 of file foamVtkGenericPatchWriter.H.
GenericPatchWriter() [3/3]
template<class PatchType > GenericPatchWriter (const PatchType & pp, const vtk::outputOptions opts, const fileName & file, bool parallel = Pstream::parRun()) inline
Definition at line 109 of file foamVtkGenericPatchWriter.H.
~GenericPatchWriter()
template<class PatchType > virtual ~GenericPatchWriter () virtual default
Member Function Documentation
patch()
template<class PatchType > const PatchType & patch () const inline noexcept
Definition at line 129 of file foamVtkGenericPatchWriter.H.
beginFile()
template<class PatchType > virtual bool beginFile (std::string title = "surface") inline virtual
Reimplemented from fileWriter.
Definition at line 136 of file foamVtkGenericPatchWriter.H.
References fileWriter::beginFile().
writeGeometry()
template<class PatchType > virtual bool writeGeometry () inline virtual
Reimplemented from polyWriter.
Definition at line 144 of file foamVtkGenericPatchWriter.H.
References polyWriter::writePolyGeometry().
writeProcIDs()
template<class PatchType > bool writeProcIDs () inline
Definition at line 153 of file foamVtkGenericPatchWriter.H.
References fileWriter::isPointData(), polyWriter::nLocalPoints_, polyWriter::nLocalPolys_, and fileWriter::writeProcIDs().
The documentation for this class was generated from the following file:
src/meshTools/output/vtk/patch/foamVtkGenericPatchWriter.H