OpenFOAM: cyclicACMILduInterfaceField Class Reference
cyclicACMILduInterfaceField Class Reference
Abstract base class for cyclic ACMI coupled interfaces.
#include <cyclicACMILduInterfaceField.H>
Public Member Functions
TypeName ("cyclicACMILduInterfaceField")
cyclicACMILduInterfaceField ()
virtual ~cyclicACMILduInterfaceField ()
template<class Type >
void transformCoupleField (Field< Type > &f) const
void transformCoupleField (solveScalarField &psiInternal, const direction cmpt) const
Public Member Functions inherited from cyclicAMILduInterfaceField
TypeName ("cyclicAMILduInterfaceField")
cyclicAMILduInterfaceField ()
virtual ~cyclicAMILduInterfaceField ()
virtual bool doTransform () const =0
virtual const tensorField & forwardT () const =0
virtual const tensorField & reverseT () const =0
virtual int rank () const =0
template<class Type >
void transformCoupleField (Field< Type > &f) const
void transformCoupleField (solveScalarField &psiInternal, const direction cmpt) const
Detailed Description
Abstract base class for cyclic ACMI coupled interfaces.
Source files
cyclicACMILduInterfaceField.H
cyclicACMILduInterfaceField.C
Definition at line 47 of file cyclicACMILduInterfaceField.H.
Constructor & Destructor Documentation
cyclicACMILduInterfaceField()
cyclicACMILduInterfaceField () inline
Definition at line 61 of file cyclicACMILduInterfaceField.H.
~cyclicACMILduInterfaceField()
~cyclicACMILduInterfaceField () virtual
Definition at line 35 of file cyclicACMILduInterfaceField.C.
Member Function Documentation
TypeName()
TypeName ("cyclicACMILduInterfaceField")
transformCoupleField() [1/2]
template<class Type > void transformCoupleField (Field< Type > & f) const
Definition at line 93 of file cyclicACMILduInterfaceField.H.
References f(), and cyclicAMILduInterfaceField::transformCoupleField().
transformCoupleField() [2/2]
void transformCoupleField (solveScalarField & psiInternal, const direction cmpt) const
Definition at line 41 of file cyclicACMILduInterfaceField.C.
References f(), and cyclicAMILduInterfaceField::transformCoupleField().
The documentation for this class was generated from the following files:
src/meshTools/AMIInterpolation/patches/cyclicACMI/cyclicACMILduInterfaceField/cyclicACMILduInterfaceField.H
src/meshTools/AMIInterpolation/patches/cyclicACMI/cyclicACMILduInterfaceField/cyclicACMILduInterfaceField.C