OpenFOAM: blockMesh Class Reference
blockMesh Class Reference
A multi-block mesh generator.
#include <blockMesh.H>
Public Types
enum mergeStrategy { DEFAULT_MERGE , MERGE_TOPOLOGY , MERGE_POINTS }
typedef PtrList< block > blockList
Public Types inherited from UPtrList< T >
typedef T value_type
typedef T & reference
typedef const T & const_reference
Public Member Functions
ClassName ("blockMesh")
blockMesh (const IOdictionary &dict, const word &regionName=polyMesh::defaultRegion, mergeStrategy strategy=mergeStrategy::DEFAULT_MERGE, int verbosity=0)
~blockMesh ()=default
const dictionary & meshDict () const noexcept
const searchableSurfaces & geometry () const noexcept
const blockEdgeList & edges () const noexcept
const blockFaceList & faces () const noexcept
bool valid () const noexcept
wordList patchNames () const
label numZonedBlocks () const
bool hasPointTransforms () const noexcept
bool inplacePointTransforms (pointField &pts) const
tmp< pointField > globalPosition (const pointField &localPoints) const
const pointField & vertices () const noexcept
tmp< pointField > vertices (bool applyTransform) const
const polyMesh & topology () const
refPtr< polyMesh > topology (bool applyTransform) const
const pointField & points () const
const cellShapeList & cells () const
const faceListList & patches () const
PtrList< dictionary > patchDicts () const
int verbose () const noexcept
int verbose (const int level) noexcept
autoPtr< polyMesh > mesh (const IOobject &io) const
scalar scaleFactor () const
Public Member Functions inherited from PtrList< block >
constexpr PtrList () noexcept
PtrList (const label len)
PtrList (const PtrList< block > &list)
PtrList (PtrList< block > &&list)
PtrList (UList< block * > &list)
PtrList (const PtrList< block > &list, const CloneArg &cloneArgs)
PtrList (PtrList< block > &list, bool reuse)
PtrList (const SLPtrList< block > &list)
PtrList (Istream &is, const INew &inew)
PtrList (Istream &is)
~PtrList ()
PtrList< block > clone (Args &&... args) const
Foam::PtrList< block > clone (Args &&... args) const
const block * set (const label i) const
autoPtr< block > set (const label i, block *ptr)
autoPtr< block > set (const label i, std::unique_ptr< block > &&ptr)
autoPtr< block > set (const label i, autoPtr< block > &&ptr)
autoPtr< block > set (const label i, const refPtr< block > &ptr)
autoPtr< block > set (const label i, const tmp< block > &ptr)
autoPtr< block > set (const label i, autoPtr< block > &ptr)
void clear ()
void free ()
void resize (const label newLen)
block & emplace_back (Args &&... args)
void push_back (block *ptr)
void push_back (std::unique_ptr< block > &&ptr)
void push_back (autoPtr< block > &&ptr)
void push_back (const refPtr< block > &ptr)
void push_back (const tmp< block > &ptr)
void push_back (PtrList< block > &&other)
void push_back (autoPtr< block > &ptr)=delete
block & emplace_set (const label i, Args &&... args)
block & emplace (const label i, Args &&... args)
autoPtr< block > release (const label i)
void transfer (PtrList< block > &list)
void operator= (const PtrList< block > &list)
void operator= (PtrList< block > &&list)
void setSize (const label newLen)
void append (autoPtr< block > &ptr)
void append (block *ptr)
void append (std::unique_ptr< block > &&ptr)
void append (autoPtr< block > &&ptr)
void append (const refPtr< block > &ptr)
void append (const tmp< block > &ptr)
void append (PtrList< block > &&other)
Public Member Functions inherited from UPtrList< T >
constexpr UPtrList () noexcept
UPtrList (const label len)
UPtrList (const UPtrList< T > &list)
UPtrList (UPtrList< T > &&list)
UPtrList (UPtrList< T > &list, bool reuse)
UPtrList (PtrList< T > &list)
UPtrList (const UList< T * > &list)
UPtrList (UList< T > &list)
bool empty () const noexcept
label size () const noexcept
label count () const noexcept
T & front ()
const T & front () const
T & back ()
const T & back () const
const T * test (const label i) const
const T * get (const label i) const
T * get (const label i)
const T * set (const label i) const
void clear ()
void free ()
void resize (const label newLen)
label squeezeNull ()
void trimTrailingNull ()
void push_back (T *ptr)
void push_back (UPtrList< T > &&other)
void swap (UPtrList< T > &list)
void transfer (UPtrList< T > &list)
T * set (const label i, T *ptr)
void reorder (const labelUList &oldToNew, const bool check=false)
void sortOrder (const labelUList &order, const bool check=false)
void checkNonNull () const
const T & at (const label i) const
T & at (const label i)
const T & operator[] (const label i) const
T & operator[] (const label i)
FOAM_DEPRECATED_FOR (2022-09, "get(), set() or test() methods") const T *operator()(const label i) const
void operator= (const UPtrList< T > &list)
void operator= (UPtrList< T > &&list)
T ** begin_ptr () noexcept
T ** end_ptr () noexcept
iterator begin ()
iterator end () noexcept
const_iterator cbegin () const
const_iterator cend () const noexcept
const_iterator begin () const
const_iterator end () const noexcept
void setSize (const label n)
T & first ()
const T & first () const
T & last ()
const T & last () const
void append (T *ptr)
void append (UPtrList< T > &&other)
Static Public Attributes
static bool verboseOutput = true
Additional Inherited Members
Protected Member Functions inherited from PtrList< block >
void readIstream (Istream &is, const INew &inew)
Protected Member Functions inherited from UPtrList< T >
void setAddressableSize (const label n) noexcept
label find_next (label pos) const
UPtrList (Detail::PtrListDetail< T > &&ptrs)
Protected Attributes inherited from UPtrList< T >
Detail::PtrListDetail< T > ptrs_
Detailed Description
A multi-block mesh generator.
Dictionary controls
Property Description Required Default
prescale Point scaling before transform no 1.0
scale Point scaling after transform no 1.0
transform Point transform (origin, rotation) no
vertices yes
blocks yes
edges no
faces no
boundary Boundary definition no
patches Alternate version for "boundary" no
namedBlocks no
namedVertices no
mergeType Merging "points" or "topology" no topology
checkFaceCorrespondence no true
verbose no true
Note
The prescale and scale can be a single scalar or a vector of values.
The vertices, cells and patches for filling the blocks are demand-driven.
Source files
blockMesh.H
blockMesh.C
blockMeshCheck.C
blockMeshCreate.C
blockMeshMerge.C
blockMeshTopology.C
Definition at line 161 of file blockMesh.H.
Member Typedef Documentation
blockList
typedef PtrList<block> blockList
Definition at line 170 of file blockMesh.H.
Member Enumeration Documentation
mergeStrategy
enum mergeStrategy
Enumerator
DEFAULT_MERGE
Default (TOPOLOGY), not selectable.
MERGE_TOPOLOGY
"topology" merge by block topology (default)
MERGE_POINTS
"points" merge by point geometry
Definition at line 176 of file blockMesh.H.
Constructor & Destructor Documentation
blockMesh()
blockMesh (const IOdictionary & dict, const word & regionName = polyMesh::defaultRegion, mergeStrategy strategy = mergeStrategy::DEFAULT_MERGE, int verbosity = 0) explicit
Definition at line 221 of file blockMesh.C.
References blockMesh::DEFAULT_MERGE, Foam::endl(), Foam::Info, blockMesh::MERGE_POINTS, and Foam::nl.
~blockMesh()
~blockMesh () default
Member Function Documentation
ClassName()
ClassName ("blockMesh")
meshDict()
const dictionary & meshDict () const inline noexcept
Definition at line 364 of file blockMesh.H.
geometry()
const searchableSurfaces & geometry () const inline noexcept
Definition at line 370 of file blockMesh.H.
edges()
const blockEdgeList & edges () const inline noexcept
Definition at line 376 of file blockMesh.H.
faces()
const blockFaceList & faces () const inline noexcept
Definition at line 382 of file blockMesh.H.
valid()
bool valid () const noexcept
Definition at line 300 of file blockMesh.C.
patchNames()
Foam::wordList patchNames () const
Definition at line 392 of file blockMesh.C.
numZonedBlocks()
Foam::label numZonedBlocks () const
Definition at line 410 of file blockMesh.C.
References UPtrList< T >::size().
hasPointTransforms()
bool hasPointTransforms () const noexcept
Definition at line 428 of file blockMesh.C.
inplacePointTransforms()
bool inplacePointTransforms (pointField & pts) const
Definition at line 434 of file blockMesh.C.
References Foam::cmptMultiply(), p, pts, and Foam::transform().
globalPosition()
Foam::tmp< Foam::pointField > globalPosition (const pointField & localPoints) const
Definition at line 507 of file blockMesh.C.
References tmp< T >::New().
vertices() [1/2]
const Foam::pointField & vertices () const noexcept
Definition at line 320 of file blockMesh.C.
vertices() [2/2]
Foam::tmp< Foam::pointField > vertices (bool applyTransform) const
Definition at line 327 of file blockMesh.C.
References tmp< T >::New().
topology() [1/2]
const Foam::polyMesh & topology () const
Definition at line 287 of file blockMeshCreate.C.
References Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
topology() [2/2]
Foam::refPtr< Foam::polyMesh > topology (bool applyTransform) const
Definition at line 301 of file blockMeshCreate.C.
References forAll, refPtr< T >::New(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, PtrList< T >::set(), UPtrList< T >::size(), and topoMesh.
points()
const Foam::pointField & points () const
Definition at line 359 of file blockMesh.C.
cells()
const Foam::cellShapeList & cells () const
Definition at line 370 of file blockMesh.C.
patches()
const Foam::faceListList & patches () const
Definition at line 381 of file blockMesh.C.
patchDicts()
Foam::PtrList< Foam::dictionary > patchDicts () const
Definition at line 342 of file blockMesh.C.
References forAll, os(), patchDicts, PtrList< T >::set(), and UPtrList< T >::size().
verbose() [1/2]
int verbose () const noexcept
Definition at line 306 of file blockMesh.C.
verbose() [2/2]
int verbose (const int level) noexcept
Definition at line 312 of file blockMesh.C.
mesh()
Foam::autoPtr< Foam::polyMesh > mesh (const IOobject & io) const
Definition at line 348 of file blockMeshCreate.C.
References PtrList< T >::append(), b, PtrList< T >::clear(), Foam::endl(), forAllConstIters, Foam::Info, io(), meshPtr, autoPtr< T >::New(), Foam::nl, UPtrList< T >::size(), and UList< T >::size().
scaleFactor()
scalar scaleFactor () const inline
Definition at line 464 of file blockMesh.H.
Member Data Documentation
verboseOutput
bool verboseOutput = true static
Definition at line 335 of file blockMesh.H.
Referenced by Foam::getVerbosity().
The documentation for this class was generated from the following files:
src/mesh/blockMesh/blockMesh/blockMesh.H
src/mesh/blockMesh/blockMesh/blockMesh.C
src/mesh/blockMesh/blockMesh/blockMeshCheck.C
src/mesh/blockMesh/blockMesh/blockMeshCreate.C
src/mesh/blockMesh/blockMesh/blockMeshMergeGeometrical.C
src/mesh/blockMesh/blockMesh/blockMeshMergeTopological.C
src/mesh/blockMesh/blockMesh/blockMeshTopology.C