OpenFOAM: solidBodyFvGeometryScheme Class Reference
solidBodyFvGeometryScheme Class Reference
Geometry calculation scheme that performs geometry updates only in regions where the mesh has changed.
#include <solidBodyFvGeometryScheme.H>
Public Member Functions
TypeName ("solidBody")
solidBodyFvGeometryScheme (const fvMesh &mesh, const dictionary &dict)
virtual ~solidBodyFvGeometryScheme ()=default
virtual void movePoints ()
virtual void updateMesh (const mapPolyMesh &mpm)
Public Member Functions inherited from basicFvGeometryScheme
TypeName ("basic")
basicFvGeometryScheme (const fvMesh &mesh, const dictionary &dict)
virtual ~basicFvGeometryScheme ()=default
virtual tmp< surfaceScalarField > weights () const
virtual tmp< surfaceScalarField > deltaCoeffs () const
virtual tmp< surfaceScalarField > nonOrthDeltaCoeffs () const
virtual tmp< surfaceVectorField > nonOrthCorrectionVectors () const
Public Member Functions inherited from fvGeometryScheme
TypeName ("fvGeometryScheme")
declareRunTimeSelectionTable (tmp, fvGeometryScheme, dict,(const fvMesh &mesh, const dictionary &dict),(mesh, dict))
fvGeometryScheme (const fvMesh &mesh, const dictionary &dict)
virtual ~fvGeometryScheme ()=default
const fvMesh & mesh () const
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Additional Inherited Members
Static Public Member Functions inherited from fvGeometryScheme
static tmp< fvGeometryScheme > New (const fvMesh &mesh, const dictionary &dict, const word &defaultScheme)
Protected Member Functions inherited from fvGeometryScheme
bool setMeshPhi () const
Protected Attributes inherited from fvGeometryScheme
const fvMesh & mesh_
Detailed Description
Geometry calculation scheme that performs geometry updates only in regions where the mesh has changed.
Example usage in fvSchemes:
    geometry
    {
        type            solidBody;
        // Optional entries
        // If set to false, update the entire mesh
        partialUpdate   yes;
        // Cache the motion addressing (changed points, faces, cells etc)
        cacheMotion     yes;
    }
Source files
solidBodyFvGeometryScheme.H
solidBodyFvGeometryScheme.C
Definition at line 65 of file solidBodyFvGeometryScheme.H.
Constructor & Destructor Documentation
solidBodyFvGeometryScheme()
solidBodyFvGeometryScheme (const fvMesh & mesh, const dictionary & dict)
Definition at line 152 of file solidBodyFvGeometryScheme.C.
References DebugInFunction, and Foam::endl().
~solidBodyFvGeometryScheme()
virtual ~solidBodyFvGeometryScheme () virtual default
Member Function Documentation
TypeName()
TypeName ("solidBody")
movePoints()
void movePoints () virtual
Reimplemented from basicFvGeometryScheme.
Definition at line 175 of file solidBodyFvGeometryScheme.C.
References Foam::abort(), primitiveMesh::clearGeom(), DebugInFunction, Foam::endl(), f(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::mag(), IOobject::name(), p, pbm, Foam::Pout, pp(), primitiveMesh::resetGeometry(), UPtrList< T >::size(), UList< T >::size(), Foam::sum(), primitiveMeshTools::updateCellCentresAndVols(), primitiveMeshTools::updateFaceCentresAndAreas(), primitiveMesh::updateGeom(), and Foam::Zero.
updateMesh()
void updateMesh (const mapPolyMesh & mpm) virtual
Reimplemented from fvGeometryScheme.
Definition at line 333 of file solidBodyFvGeometryScheme.C.
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/fvGeometryScheme/solidBody/solidBodyFvGeometryScheme.H
src/finiteVolume/fvMesh/fvGeometryScheme/solidBody/solidBodyFvGeometryScheme.C