OpenFOAM: AMIWeights Class Reference
AMIWeights Class Reference
FunctionObjects » Field function objects
Computes the min/max/average weights of arbitrary mesh interface (AMI) patches, and optionally reports to a text file or writes VTK surfaces of the sum of the weights and mask fields for arbitrarily coupled mesh interface (ACMI) patches.
#include <AMIWeights.H>
Public Member Functions
TypeName ("AMIWeights")
AMIWeights (const word &name, const Time &runTime, const dictionary &dict)
AMIWeights (const AMIWeights &)=delete
void operator= (const AMIWeights &)=delete
virtual ~AMIWeights ()=default
virtual bool read (const dictionary &)
virtual bool execute ()
virtual bool write ()
Public Member Functions inherited from fvMeshFunctionObject
TypeName ("fvMeshFunctionObject")
fvMeshFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
fvMeshFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
virtual ~fvMeshFunctionObject ()=default
Public Member Functions inherited from regionFunctionObject
TypeName ("regionFunctionObject")
regionFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
regionFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
virtual ~regionFunctionObject ()=default
template<class ObjectType >
const ObjectType * lookupObjectPtr (const word &fieldName) const
template<class ObjectType >
ObjectType * lookupObjectRefPtr (const word &fieldName) const
Public Member Functions inherited from stateFunctionObject
stateFunctionObject (const word &name, const Time &runTime)
virtual ~stateFunctionObject ()=default
dictionary & propertyDict ()
bool foundProperty (const word &entryName) const
void clearTrigger ()
label getTrigger () const
bool setTrigger (const label triggeri)
bool getDict (const word &entryName, dictionary &dict) const
bool getObjectDict (const word &objectName, const word &entryName, dictionary &dict) const
template<class Type >
Type getProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getProperty (const word &entryName, Type &value) const
template<class Type >
void setProperty (const word &entryName, const Type &value)
template<class Type >
Type getObjectProperty (const word &objectName, const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getObjectProperty (const word &objectName, const word &entryName, Type &value) const
template<class Type >
void setObjectProperty (const word &objectName, const word &entryName, const Type &value)
template<class Type >
void setResult (const word &entryName, const Type &value)
template<class Type >
void setObjectResult (const word &objectName, const word &entryName, const Type &value)
template<class Type >
Type getResult (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
Type getObjectResult (const word &objectName, const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getObjectResult (const word &objectName, const word &entryName, Type &value) const
word resultType (const word &entryName) const
word objectResultType (const word &objectName, const word &entryName) const
wordList objectResultEntries () const
wordList objectResultEntries (const word &objectName) const
void writeResultEntries (Ostream &os) const
void writeResultEntries (const word &objectName, Ostream &os) const
void writeAllResultEntries (Ostream &os) const
Public Member Functions inherited from timeFunctionObject
timeFunctionObject (const word &name, const Time &runTime)
virtual ~timeFunctionObject ()=default
const Time & time () const
objectRegistry & storedObjects ()
const objectRegistry & storedObjects () const
Public Member Functions inherited from functionObject
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name, const bool withNamePrefix=defaultUseNamePrefix)
autoPtr< functionObject > clone () const
virtual ~functionObject ()=default
virtual const word & type () const =0
const word & name () const noexcept
bool useNamePrefix () const noexcept
bool useNamePrefix (bool on) noexcept
virtual bool execute (const label subIndex)
virtual bool end ()
virtual bool adjustTimeStep ()
virtual bool filesModified () const
virtual void updateMesh (const mapPolyMesh &mpm)
virtual void movePoints (const polyMesh &mesh)
Public Member Functions inherited from writeFile
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name="undefined", const bool writeToFile=true)
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name, const dictionary &dict, const bool writeToFile=true)
writeFile (const writeFile &wf)
virtual ~writeFile ()=default
virtual OFstream & file ()
virtual bool writeToFile () const
virtual bool canWriteToFile () const
virtual bool canResetFile () const
virtual bool canWriteHeader () const
virtual label charWidth () const
virtual void writeCommented (Ostream &os, const string &str) const
virtual void writeTabbed (Ostream &os, const string &str) const
virtual void writeHeader (Ostream &os, const string &str) const
virtual void writeCurrentTime (Ostream &os) const
virtual void writeBreak (Ostream &os) const
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
template<class Type >
void writeValue (Ostream &os, const Type &val) const
Protected Member Functions
virtual void writeFileHeader (Ostream &os)
virtual void reportPatch (const cyclicAMIPolyPatch &pp)
void writeWeightField (const cyclicAMIPolyPatch &cpp, const scalarField &weightSum, const word &side) const
void writeWeightFields (const cyclicAMIPolyPatch &cpp) const
Protected Member Functions inherited from fvMeshFunctionObject
fvMeshFunctionObject (const fvMeshFunctionObject &)=delete
void operator= (const fvMeshFunctionObject &)=delete
Protected Member Functions inherited from regionFunctionObject
virtual const objectRegistry & obr () const
template<class ObjectType >
bool foundObject (const word &fieldName) const
template<class ObjectType >
const ObjectType * cfindObject (const word &fieldName) const
template<class ObjectType >
const ObjectType * findObject (const word &fieldName) const
template<class ObjectType >
ObjectType * findObject (const word &fieldName)
template<class ObjectType >
ObjectType * getObjectPtr (const word &fieldName) const
template<class ObjectType >
const ObjectType & lookupObject (const word &fieldName) const
template<class ObjectType >
ObjectType & lookupObjectRef (const word &fieldName) const
template<class ObjectType >
bool store (word &fieldName, const tmp< ObjectType > &tfield, bool cacheable=false)
template<class ObjectType >
bool storeInDb (const word &fieldName, const tmp< ObjectType > &tfield, const objectRegistry &obr)
bool writeObject (const word &fieldName)
bool clearObject (const word &fieldName)
void clearObjects (const wordList &objNames)
regionFunctionObject (const regionFunctionObject &)=delete
void operator= (const regionFunctionObject &)=delete
Protected Member Functions inherited from stateFunctionObject
const functionObjects::properties & stateDict () const
functionObjects::properties & stateDict ()
stateFunctionObject (const stateFunctionObject &)=delete
void operator= (const stateFunctionObject &)=delete
Protected Member Functions inherited from timeFunctionObject
void clearOutputObjects (const wordList &objNames)
timeFunctionObject (const timeFunctionObject &)=delete
void operator= (const timeFunctionObject &)=delete
Protected Member Functions inherited from functionObject
word scopedName (const word &name) const
Protected Member Functions inherited from writeFile
void initStream (Ostream &os) const
fileName baseFileDir () const
fileName baseTimeDir () const
fileName filePath (const fileName &fName) const
virtual autoPtr< OFstream > newFile (const fileName &fName) const
virtual autoPtr< OFstream > newFileAtTime (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > newFileAtStartTime (const word &name) const
virtual void resetFile (const word &name)
Omanip< int > valueWidth (const label offset=0) const
void operator= (const writeFile &)=delete
virtual autoPtr< OFstream > createFile (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > createFile (const word &name) const
Protected Attributes
bool writeFields_
labelList patchIDs_
Protected Attributes inherited from fvMeshFunctionObject
const fvMesh & mesh_
Protected Attributes inherited from regionFunctionObject
word subRegistryName_
const objectRegistry & obr_
const objectRegistry * obrPtr_
Protected Attributes inherited from timeFunctionObject
const Time & time_
Protected Attributes inherited from writeFile
const objectRegistry & fileObr_
const fileName prefix_
word fileName_
autoPtr< OFstream > filePtr_
label writePrecision_
bool writeToFile_
bool updateHeader_
bool writtenHeader_
bool useUserTime_
scalar startTime_
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &runTime, const dictionary &dict)
Public Attributes inherited from functionObject
bool log
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
static bool defaultUseNamePrefix
static word outputPrefix
Static Public Attributes inherited from writeFile
static label addChars = 8
Detailed Description
Computes the min/max/average weights of arbitrary mesh interface (AMI) patches, and optionally reports to a text file or writes VTK surfaces of the sum of the weights and mask fields for arbitrarily coupled mesh interface (ACMI) patches.
Operands:
Operand Type Location
input - -
output file dat $POST/<file>
output field vtp $POST/<AMINames>_{src,tgt}.vtp
where $POST=$FOAM_CASE/postProcessing/<FO>/<time>.
Usage
Minimal example by using system/controlDict.functions:
AMIWeights1
{
    // Mandatory entries (unmodifiable)
    type        AMIWeights;
    libs        (fieldFunctionObjects);
    // Mandatory entries (runtime modifiable)
    writeFields false;
    // Optional (inherited) entries
    ...
}
where the entries mean:
Property Description Type Req'd Dflt
type Type name: AMIWeights word yes -
libs Library name: fieldFunctionObjects word yes -
writeFields Write weights as VTK fields bool yes -
The inherited entries are elaborated in:
functionObject.H
writeFile.H
Minimal example by using the postProcess utility:
        postProcess -func AMIWeights
See also
Foam::functionObject
Foam::functionObjects::fvMeshFunctionObject
Foam::functionObjects::writeFile
ExtendedCodeGuide::functionObjects::field::AMIWeights
Source files
AMIWeights.H
AMIWeights.C
AMIWeightsTemplates.C
Definition at line 147 of file AMIWeights.H.
Constructor & Destructor Documentation
AMIWeights() [1/2]
AMIWeights (const word & name, const Time & runTime, const dictionary & dict)
Definition at line 289 of file AMIWeights.C.
References dict, and AMIWeights::read().
AMIWeights() [2/2]
AMIWeights (const AMIWeights &) delete
~AMIWeights()
virtual ~AMIWeights () virtual default
Member Function Documentation
writeFileHeader()
void writeFileHeader (Ostream & os) protected virtual
Definition at line 41 of file AMIWeights.C.
References Foam::endl(), forAll, os(), UPstream::parRun(), AMIWeights::patchIDs_, writeFile::writeCommented(), writeFile::writeHeader(), and writeFile::writeTabbed().
reportPatch()
void reportPatch (const cyclicAMIPolyPatch & pp) protected virtual
Definition at line 74 of file AMIWeights.C.
References IOstream::defaultPrecision(), Foam::endl(), Foam::gAverage(), Foam::gMax(), Foam::gMin(), Foam::labelMax, Foam::labelMin, Log, Foam::max(), Foam::min(), n, Foam::nl, UPstream::parRun(), pp(), Foam::reduce(), Foam::returnReduce(), Foam::setw(), UPtrList< T >::size(), UList< T >::size(), and Foam::tab.
writeWeightField()
void writeWeightField (const cyclicAMIPolyPatch & cpp, const scalarField & weightSum, const word & side) const protected
Definition at line 203 of file AMIWeights.C.
References PatchTools::gatherAndMerge(), UPstream::master(), pp(), and writer().
writeWeightFields()
void writeWeightFields (const cyclicAMIPolyPatch & cpp) const protected
Definition at line 274 of file AMIWeights.C.
TypeName()
TypeName ("AMIWeights")
operator=()
void operator= (const AMIWeights &) delete
read()
bool read (const dictionary & dict) virtual
Reimplemented from regionFunctionObject.
Definition at line 307 of file AMIWeights.C.
References PtrList< T >::clear(), dict, pp(), functionObject::read(), and writeFile::read().
Referenced by AMIWeights::AMIWeights().
execute()
bool execute () virtual
Implements functionObject.
Definition at line 337 of file AMIWeights.C.
write()
bool write () virtual
Implements functionObject.
Definition at line 343 of file AMIWeights.C.
References Log, Foam::name(), Foam::nl, pbm, pp(), and Foam::type().
Member Data Documentation
writeFields_
bool writeFields_ protected
Definition at line 157 of file AMIWeights.H.
patchIDs_
labelList patchIDs_ protected
Definition at line 160 of file AMIWeights.H.
Referenced by AMIWeights::writeFileHeader().
The documentation for this class was generated from the following files:
src/functionObjects/field/AMIWeights/AMIWeights.H
src/functionObjects/field/AMIWeights/AMIWeights.C