OpenFOAM: TDILUPreconditioner< Type, DType, LUType > Class Template Reference
TDILUPreconditioner< Type, DType, LUType > Class Template Reference
Simplified diagonal-based incomplete LU preconditioner for asymmetric matrices.
#include <TDILUPreconditioner.H>
Public Member Functions
TypeName ("DILU")
TDILUPreconditioner (const typename LduMatrix< Type, DType, LUType >::solver &sol, const dictionary &preconditionerDict)
virtual ~TDILUPreconditioner ()=default
virtual void precondition (Field< Type > &wA, const Field< Type > &rA) const
virtual void preconditionT (Field< Type > &wT, const Field< Type > &rT) const
Public Member Functions inherited from LduMatrix< Type, DType, LUType >::preconditioner
virtual const word & type () const =0
declareRunTimeSelectionTable (autoPtr, preconditioner, symMatrix,(const solver &sol, const dictionary &preconditionerDict),(sol, preconditionerDict))
declareRunTimeSelectionTable (autoPtr, preconditioner, asymMatrix,(const solver &sol, const dictionary &preconditionerDict),(sol, preconditionerDict))
preconditioner (const solver &sol)
virtual ~preconditioner ()=default
virtual void read (const dictionary &)
Static Public Member Functions
static void calcInvD (Field< DType > &rD, const LduMatrix< Type, DType, LUType > &matrix)
Static Public Member Functions inherited from LduMatrix< Type, DType, LUType >::preconditioner
static autoPtr< preconditioner > New (const solver &sol, const dictionary &preconditionerDict)
Additional Inherited Members
Protected Attributes inherited from LduMatrix< Type, DType, LUType >::preconditioner
const solver & solver_
Detailed Description
template<class Type, class DType, class LUType>
class Foam::TDILUPreconditioner< Type, DType, LUType >
Simplified diagonal-based incomplete LU preconditioner for asymmetric matrices.
The inverse (reciprocal for scalar) of the preconditioned diagonal is calculated and stored.
Source files
TDILUPreconditioner.H
TDILUPreconditioner.C
Definition at line 52 of file TDILUPreconditioner.H.
Constructor & Destructor Documentation
TDILUPreconditioner()
template<class Type , class DType , class LUType > TDILUPreconditioner (const typename LduMatrix< Type, DType, LUType >::solver & sol, const dictionary & preconditionerDict)
Definition at line 26 of file TDILUPreconditioner.C.
References TDILUPreconditioner< Type, DType, LUType >::calcInvD(), and Foam::diag().
~TDILUPreconditioner()
template<class Type , class DType , class LUType > virtual ~TDILUPreconditioner () virtual default
Member Function Documentation
TypeName()
template<class Type , class DType , class LUType > TypeName ("DILU")
calcInvD()
template<class Type , class DType , class LUType > void calcInvD (Field< DType > & rD, const LduMatrix< Type, DType, LUType > & matrix) static
Definition at line 42 of file TDILUPreconditioner.C.
References UPtrList< T >::begin(), Foam::dot(), Foam::inv(), and UPtrList< T >::size().
Referenced by TDILUPreconditioner< Type, DType, LUType >::TDILUPreconditioner().
precondition()
template<class Type , class DType , class LUType > void precondition (Field< Type > & wA, const Field< Type > & rA) const virtual
Implements LduMatrix< Type, DType, LUType >::preconditioner.
Definition at line 75 of file TDILUPreconditioner.C.
References UPtrList< T >::begin(), Foam::dot(), and UPtrList< T >::size().
preconditionT()
template<class Type , class DType , class LUType > void preconditionT (Field< Type > & wT, const Field< Type > & rT) const virtual
Reimplemented from LduMatrix< Type, DType, LUType >::preconditioner.
Definition at line 125 of file TDILUPreconditioner.C.
References UPtrList< T >::begin(), Foam::dot(), and UPtrList< T >::size().
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/LduMatrix/Preconditioners/DILUPreconditioner/TDILUPreconditioner.H
src/OpenFOAM/matrices/LduMatrix/Preconditioners/DILUPreconditioner/TDILUPreconditioner.C