OpenFOAM: ensightMesh::options Class Reference
ensightMesh::options Class Reference
#include <ensightMesh.H>
Public Member Functions
options ()
bool lazy () const noexcept
bool useInternalMesh () const noexcept
bool useBoundaryMesh () const noexcept
bool useFaceZones () const noexcept
bool useCellZones () const noexcept
const wordRes & patchSelection () const noexcept
const wordRes & patchExclude () const noexcept
const wordRes & faceZoneSelection () const noexcept
const wordRes & cellZoneSelection () const noexcept
void reset ()
bool lazy (bool on) noexcept
bool useInternalMesh (bool on) noexcept
bool useBoundaryMesh (bool on)
bool useCellZones (bool on)
void patchSelection (const UList< wordRe > &patterns)
void patchSelection (List< wordRe > &&patterns)
void patchExclude (const UList< wordRe > &patterns)
void patchExclude (List< wordRe > &&patterns)
void faceZoneSelection (const UList< wordRe > &patterns)
void faceZoneSelection (List< wordRe > &&patterns)
void cellZoneSelection (const UList< wordRe > &patterns)
void cellZoneSelection (List< wordRe > &&patterns)
void print (Ostream &os) const
Detailed Description
Definition at line 237 of file ensightMesh.H.
Constructor & Destructor Documentation
options()
options ()
Definition at line 53 of file ensightMeshOptions.C.
Member Function Documentation
lazy() [1/2]
bool lazy () const noexcept
Definition at line 68 of file ensightMeshOptions.C.
useInternalMesh() [1/2]
bool useInternalMesh () const noexcept
Definition at line 74 of file ensightMeshOptions.C.
useBoundaryMesh() [1/2]
bool useBoundaryMesh () const noexcept
Definition at line 80 of file ensightMeshOptions.C.
useFaceZones()
bool useFaceZones () const noexcept
Definition at line 92 of file ensightMeshOptions.C.
References UPtrList< T >::size().
useCellZones() [1/2]
bool useCellZones () const noexcept
Definition at line 86 of file ensightMeshOptions.C.
patchSelection() [1/3]
const wordRes & patchSelection () const inline noexcept
Definition at line 294 of file ensightMesh.H.
patchExclude() [1/3]
const wordRes & patchExclude () const inline noexcept
Definition at line 300 of file ensightMesh.H.
faceZoneSelection() [1/3]
const wordRes & faceZoneSelection () const inline noexcept
Definition at line 306 of file ensightMesh.H.
cellZoneSelection() [1/3]
const wordRes & cellZoneSelection () const inline noexcept
Definition at line 312 of file ensightMesh.H.
reset()
void reset ()
Definition at line 98 of file ensightMeshOptions.C.
References PtrList< T >::clear().
lazy() [2/2]
bool lazy (bool on) noexcept
Definition at line 110 of file ensightMeshOptions.C.
useInternalMesh() [2/2]
bool useInternalMesh (bool on) noexcept
Definition at line 118 of file ensightMeshOptions.C.
useBoundaryMesh() [2/2]
bool useBoundaryMesh (bool on)
Definition at line 126 of file ensightMeshOptions.C.
References PtrList< T >::clear(), Foam::endl(), and WarningInFunction.
useCellZones() [2/2]
bool useCellZones (bool on)
Definition at line 147 of file ensightMeshOptions.C.
References PtrList< T >::clear(), Foam::endl(), and WarningInFunction.
patchSelection() [2/3]
void patchSelection (const UList< wordRe > & patterns)
Definition at line 165 of file ensightMeshOptions.C.
References Foam::endl(), and WarningInFunction.
patchSelection() [3/3]
void patchSelection (List< wordRe > && patterns)
Definition at line 183 of file ensightMeshOptions.C.
References Foam::endl(), and WarningInFunction.
patchExclude() [2/3]
void patchExclude (const UList< wordRe > & patterns)
Definition at line 201 of file ensightMeshOptions.C.
patchExclude() [3/3]
void patchExclude (List< wordRe > && patterns)
Definition at line 210 of file ensightMeshOptions.C.
faceZoneSelection() [2/3]
void faceZoneSelection (const UList< wordRe > & patterns)
Definition at line 219 of file ensightMeshOptions.C.
faceZoneSelection() [3/3]
void faceZoneSelection (List< wordRe > && patterns)
Definition at line 228 of file ensightMeshOptions.C.
cellZoneSelection() [2/3]
void cellZoneSelection (const UList< wordRe > & patterns)
Definition at line 237 of file ensightMeshOptions.C.
References Foam::endl(), and WarningInFunction.
cellZoneSelection() [3/3]
void cellZoneSelection (List< wordRe > && patterns)
Definition at line 255 of file ensightMeshOptions.C.
References Foam::endl(), and WarningInFunction.
print()
void print (Ostream & os) const
Definition at line 273 of file ensightMeshOptions.C.
References Switch::name(), Foam::nl, os(), and Foam::printPatterns().
The documentation for this class was generated from the following files:
src/fileFormats/ensight/mesh/ensightMesh.H
src/fileFormats/ensight/mesh/ensightMeshOptions.C