OpenFOAM: particleTracksSampler Class Reference
particleTracksSampler Class Reference
Helper class when generating particle tracks. The interface is fairly rudimentary.
#include <particleTracksSampler.H>
Public Member Functions
const globalIndex & parcelAddr () const noexcept
label nParticle () const
label nTracks () const noexcept
void reset (const labelUList &origParcelCounts)
label setSampleRate (const label sampleFreq, const label maxPositions, const label maxTracks=-1)
void resetCloud (const label localCloudSize)
template<class Type >
void gatherInplace (List< Type > &fld) const
template<class Type >
void createTrackField (const UList< Type > &values, List< DynamicList< Type > > &trackValues) const
template<class Type >
label setTrackFields (const objectRegistry &obr, HashTable< List< DynamicList< Type > > > &fieldTable) const
Public Attributes
labelField origParcelIds_
labelField origProcIds_
Detailed Description
Helper class when generating particle tracks. The interface is fairly rudimentary.
Source files
particleTracksSampler.H
particleTracksSamplerTemplates.C
Definition at line 54 of file particleTracksSampler.H.
Member Function Documentation
parcelAddr()
const globalIndex & parcelAddr () const inline noexcept
Definition at line 91 of file particleTracksSampler.H.
nParticle()
label nParticle () const inline
Definition at line 97 of file particleTracksSampler.H.
References globalIndex::totalSize().
nTracks()
label nTracks () const inline noexcept
Definition at line 103 of file particleTracksSampler.H.
reset()
void reset (const labelUList & origParcelCounts) inline
Definition at line 109 of file particleTracksSampler.H.
References List< T >::clear(), particleTracksSampler::origParcelIds_, particleTracksSampler::origProcIds_, and globalIndex::reset().
setSampleRate()
label setSampleRate (const label sampleFreq, const label maxPositions, const label maxTracks = -1) inline
Definition at line 119 of file particleTracksSampler.H.
References Foam::max(), maxPositions(), maxTracks(), Foam::min(), and globalIndex::totalSize().
resetCloud()
void resetCloud (const label localCloudSize) inline
Definition at line 140 of file particleTracksSampler.H.
References particleTracksSampler::origParcelIds_, particleTracksSampler::origProcIds_, globalIndex::reset(), and List< T >::resize_nocopy().
gatherInplace()
template<class Type > void gatherInplace (List< Type > & fld) const inline
Definition at line 148 of file particleTracksSampler.H.
References fld(), and globalIndex::gatherInplace().
createTrackField()
template<class Type > void createTrackField (const UList< Type > & values, List< DynamicList< Type > > & trackValues) const
setTrackFields()
template<class Type > label setTrackFields (const objectRegistry & obr, HashTable< List< DynamicList< Type > > > & fieldTable) const
Member Data Documentation
origParcelIds_
labelField origParcelIds_
Definition at line 82 of file particleTracksSampler.H.
Referenced by particleTracksSampler::reset(), and particleTracksSampler::resetCloud().
origProcIds_
labelField origProcIds_
Definition at line 85 of file particleTracksSampler.H.
Referenced by particleTracksSampler::reset(), and particleTracksSampler::resetCloud().
The documentation for this class was generated from the following file:
applications/utilities/postProcessing/lagrangian/particleTracks/particleTracksSampler.H