OpenFOAM: ash Class Reference
ash Class Reference
Coal ash solid properties.
#include <ash.H>
Public Member Functions
TypeName ("ash")
ash ()
ash (const dictionary &dict)
virtual autoPtr< solidProperties > clone () const
void writeData (Ostream &os) const
Public Member Functions inherited from solidProperties
TypeName ("solid")
declareRunTimeSelectionTable (autoPtr, solidProperties,,(),())
declareRunTimeSelectionTable (autoPtr, solidProperties, dictionary,(const dictionary &dict),(dict))
solidProperties (scalar rho, scalar Cp, scalar kappa, scalar Hf, scalar emissivity, scalar W, scalar nu, scalar E)
solidProperties (const dictionary &dict)
virtual ~solidProperties ()=default
scalar rho () const
scalar Cp () const
scalar kappa () const
scalar Hf () const
scalar Hs (const scalar T) const
scalar emissivity () const
scalar W () const
scalar nu () const
scalar E () const
void readIfPresent (const dictionary &dict)
Friends
Ostream & operator<< (Ostream &os, const ash &s)
Additional Inherited Members
Static Public Member Functions inherited from solidProperties
static autoPtr< solidProperties > New (const word &name)
static autoPtr< solidProperties > New (const dictionary &dict)
Detailed Description
Coal ash solid properties.
Source files
ash.H
ash.C
Definition at line 46 of file ash.H.
Constructor & Destructor Documentation
ash() [1/2]
ash ()
Definition at line 36 of file ash.C.
References Foam::endl(), and WarningInFunction.
ash() [2/2]
ash (const dictionary & dict)
Definition at line 49 of file ash.C.
References dict, and solidProperties::readIfPresent().
Member Function Documentation
TypeName()
TypeName ("ash")
clone()
virtual autoPtr< solidProperties > clone () const inline virtual
Reimplemented from solidProperties.
Definition at line 66 of file ash.H.
writeData()
void writeData (Ostream & os) const virtual
Reimplemented from solidProperties.
Definition at line 59 of file ash.C.
References os(), and solidProperties::writeData().
Friends And Related Symbol Documentation
operator<<
Ostream & operator<< (Ostream & os, const ash & s) friend
The documentation for this class was generated from the following files:
src/thermophysicalModels/thermophysicalProperties/solidProperties/ash/ash.H
src/thermophysicalModels/thermophysicalProperties/solidProperties/ash/ash.C