OpenFOAM: SloanRenumber Class Reference
SloanRenumber Class Reference
Sloan renumbering algorithm.
#include <SloanRenumber.H>
Public Member Functions
TypeName ("Sloan")
SloanRenumber (const dictionary &dict)
virtual ~SloanRenumber ()=default
virtual labelList renumber (const pointField &) const
virtual labelList renumber (const polyMesh &mesh, const pointField &cc) const
virtual labelList renumber (const CompactListList< label > &cellCells, const pointField &cellCentres) const
virtual labelList renumber (const labelListList &cellCells, const pointField &cc) const
Public Member Functions inherited from renumberMethod
TypeName ("renumberMethod")
declareRunTimeSelectionTable (autoPtr, renumberMethod, dictionary,(const dictionary &renumberDict),(renumberDict))
renumberMethod (const dictionary &dict)
virtual ~renumberMethod ()=default
virtual labelList renumber (const labelList &cellCells, const labelList &offsets, const pointField &) const
virtual labelList renumber (const polyMesh &mesh, const labelList &fineToCoarse, const pointField &coarsePoints) const
Additional Inherited Members
Static Public Member Functions inherited from renumberMethod
static autoPtr< renumberMethod > New (const dictionary &renumberDict)
Protected Member Functions inherited from renumberMethod
renumberMethod (const renumberMethod &)=delete
void operator= (const renumberMethod &)=delete
Protected Attributes inherited from renumberMethod
const dictionary & renumberDict_
Detailed Description
Sloan renumbering algorithm.
E.g. http://www.apav.it/sito_ratio/file_pdf/ratio_4/capitolo_1.pdf
Source files
SloanRenumber.H
SloanRenumber.C
Definition at line 47 of file SloanRenumber.H.
Constructor & Destructor Documentation
SloanRenumber()
SloanRenumber (const dictionary & dict) explicit
Definition at line 85 of file SloanRenumber.C.
~SloanRenumber()
virtual ~SloanRenumber () virtual default
Member Function Documentation
TypeName()
TypeName ("Sloan")
renumber() [1/4]
virtual labelList renumber (const pointField &) const inline virtual
Reimplemented from renumberMethod.
Definition at line 86 of file SloanRenumber.H.
References NotImplemented.
renumber() [2/4]
Foam::labelList renumber (const polyMesh & mesh, const pointField & cc) const virtual
Reimplemented from renumberMethod.
Definition at line 149 of file SloanRenumber.C.
References polyMesh::boundaryMesh(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), forAll, mesh, primitiveMesh::nBoundaryFaces(), primitiveMesh::nCells(), pp(), and syncTools::swapBoundaryFaceList().
renumber() [3/4]
Foam::labelList renumber (const CompactListList< label > & cellCells, const pointField & cellCentres) const virtual
Reimplemented from renumberMethod.
Definition at line 210 of file SloanRenumber.C.
References forAll, and UPtrList< T >::size().
renumber() [4/4]
Foam::labelList renumber (const labelListList & cellCells, const pointField & cc) const virtual
Implements renumberMethod.
Definition at line 235 of file SloanRenumber.C.
References forAll, and UList< T >::size().
The documentation for this class was generated from the following files:
src/renumber/SloanRenumber/SloanRenumber.H
src/renumber/SloanRenumber/SloanRenumber.C