OpenFOAM: greyMeanSolidAbsorptionEmission Class Reference
greyMeanSolidAbsorptionEmission Class Reference
Thermophysical models » Radiation models » Sub-models » Absorption and emission sub-models
greyMeanSolidAbsorptionEmission radiation absorption and emission coefficients for solid mixture
#include <greyMeanSolidAbsorptionEmission.H>
Public Member Functions
TypeName ("greyMeanSolidAbsorptionEmission")
greyMeanSolidAbsorptionEmission (const dictionary &dict, const fvMesh &mesh)
virtual ~greyMeanSolidAbsorptionEmission ()=default
tmp< volScalarField > aCont (const label bandI=0) const
tmp< volScalarField > eCont (const label bandI=0) const
bool isGrey () const
Public Member Functions inherited from absorptionEmissionModel
TypeName ("absorptionEmissionModel")
declareRunTimeSelectionTable (autoPtr, absorptionEmissionModel, dictionary,(const dictionary &dict, const fvMesh &mesh),(dict, mesh))
absorptionEmissionModel (const dictionary &dict, const fvMesh &mesh)
virtual ~absorptionEmissionModel ()
const fvMesh & mesh () const
const dictionary & dict () const
virtual tmp< volScalarField > a (const label bandI=0) const
virtual tmp< volScalarField > aDisp (const label bandI=0) const
virtual tmp< volScalarField > e (const label bandI=0) const
virtual tmp< volScalarField > eDisp (const label bandI=0) const
virtual tmp< volScalarField > E (const label bandI=0) const
virtual tmp< volScalarField > ECont (const label bandI=0) const
virtual tmp< volScalarField > EDisp (const label bandI=0) const
virtual label nBands () const
virtual const Vector2D< scalar > & bands (const label n) const
virtual void correct (volScalarField &a, PtrList< volScalarField > &aj) const
Additional Inherited Members
Static Public Member Functions inherited from absorptionEmissionModel
static autoPtr< absorptionEmissionModel > New (const dictionary &dict, const fvMesh &mesh)
Protected Attributes inherited from absorptionEmissionModel
const dictionary dict_
const fvMesh & mesh_
Detailed Description
greyMeanSolidAbsorptionEmission radiation absorption and emission coefficients for solid mixture
Source files
greyMeanSolidAbsorptionEmission.H
greyMeanSolidAbsorptionEmission.C
Definition at line 56 of file greyMeanSolidAbsorptionEmission.H.
Constructor & Destructor Documentation
greyMeanSolidAbsorptionEmission()
greyMeanSolidAbsorptionEmission (const dictionary & dict, const fvMesh & mesh)
Definition at line 80 of file greyMeanSolidAbsorptionEmission.C.
References Foam::abort(), absorptionEmissionModel::dict(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, HashTable< T, Key, Hash >::insert(), Foam::nl, and WarningInFunction.
~greyMeanSolidAbsorptionEmission()
virtual ~greyMeanSolidAbsorptionEmission () virtual default
Member Function Documentation
TypeName()
TypeName ("greyMeanSolidAbsorptionEmission")
aCont()
Foam::tmp< Foam::volScalarField > aCont (const label bandI = 0) const virtual
Reimplemented from absorptionEmissionModel.
Definition at line 182 of file greyMeanSolidAbsorptionEmission.C.
eCont()
Foam::tmp< Foam::volScalarField > eCont (const label bandI = 0) const virtual
Reimplemented from absorptionEmissionModel.
Definition at line 172 of file greyMeanSolidAbsorptionEmission.C.
isGrey()
bool isGrey () const inline virtual
Reimplemented from absorptionEmissionModel.
Definition at line 127 of file greyMeanSolidAbsorptionEmission.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/radiation/submodels/absorptionEmissionModel/greyMeanSolidAbsorptionEmission/greyMeanSolidAbsorptionEmission.H
src/thermophysicalModels/radiation/submodels/absorptionEmissionModel/greyMeanSolidAbsorptionEmission/greyMeanSolidAbsorptionEmission.C