OpenFOAM: manualRenumber Class Reference
manualRenumber Class Reference
Renumber given a ordered-to-original cell association in a file.
#include <manualRenumber.H>
Public Member Functions
TypeName ("manual")
manualRenumber (const dictionary &dict)
virtual ~manualRenumber ()=default
virtual labelList renumber (const pointField &) const
virtual labelList renumber (const polyMesh &mesh, const pointField &cc) const
virtual labelList renumber (const CompactListList< label > &cellCells, const pointField &cellCentres) const
virtual labelList renumber (const labelListList &cellCells, const pointField &cellCentres) const
Public Member Functions inherited from renumberMethod
TypeName ("renumberMethod")
declareRunTimeSelectionTable (autoPtr, renumberMethod, dictionary,(const dictionary &renumberDict),(renumberDict))
renumberMethod (const dictionary &dict)
virtual ~renumberMethod ()=default
virtual labelList renumber (const labelList &cellCells, const labelList &offsets, const pointField &) const
virtual labelList renumber (const polyMesh &mesh, const labelList &fineToCoarse, const pointField &coarsePoints) const
Additional Inherited Members
Static Public Member Functions inherited from renumberMethod
static autoPtr< renumberMethod > New (const dictionary &renumberDict)
Protected Member Functions inherited from renumberMethod
renumberMethod (const renumberMethod &)=delete
void operator= (const renumberMethod &)=delete
Protected Attributes inherited from renumberMethod
const dictionary & renumberDict_
Detailed Description
Renumber given a ordered-to-original cell association in a file.
Source files
manualRenumber.H
manualRenumber.C
Definition at line 45 of file manualRenumber.H.
Constructor & Destructor Documentation
manualRenumber()
manualRenumber (const dictionary & dict) explicit
Definition at line 44 of file manualRenumber.C.
~manualRenumber()
virtual ~manualRenumber () virtual default
Member Function Documentation
TypeName()
TypeName ("manual")
renumber() [1/4]
virtual labelList renumber (const pointField &) const inline virtual
Reimplemented from renumberMethod.
Definition at line 82 of file manualRenumber.H.
References NotImplemented.
renumber() [2/4]
Foam::labelList renumber (const polyMesh & mesh, const pointField & cc) const virtual
Reimplemented from renumberMethod.
Definition at line 56 of file manualRenumber.C.
References Foam::endl(), Foam::exit(), polyMesh::facesInstance(), Foam::FatalError, FatalErrorInFunction, forAll, mesh, IOobjectOption::MUST_READ, Foam::nl, points, UPtrList< T >::size(), and fvMesh::thisDb().
renumber() [3/4]
virtual labelList renumber (const CompactListList< label > & cellCells, const pointField & cellCentres) const inline virtual
Reimplemented from renumberMethod.
Definition at line 99 of file manualRenumber.H.
References NotImplemented.
renumber() [4/4]
virtual labelList renumber (const labelListList & cellCells, const pointField & cellCentres) const inline virtual
Implements renumberMethod.
Definition at line 111 of file manualRenumber.H.
References NotImplemented.
The documentation for this class was generated from the following files:
src/renumber/renumberMethods/manualRenumber/manualRenumber.H
src/renumber/renumberMethods/manualRenumber/manualRenumber.C