OpenFOAM: PurePhaseModel< BasePhaseModel, phaseThermo > Class Template Reference
PurePhaseModel< BasePhaseModel, phaseThermo > Class Template Reference
Class which represents pure phases, i.e. without any species. Returns an empty list of mass fractions.
#include <PurePhaseModel.H>
Public Member Functions
PurePhaseModel (const multiphaseInterSystem &fluid, const word &phaseName)
virtual ~PurePhaseModel ()=default
virtual const PtrList< volScalarField > & Y () const
virtual PtrList< volScalarField > & Y ()
virtual void solveYi (PtrList< volScalarField::Internal > &, PtrList< volScalarField::Internal > &)
virtual const phaseThermo & thermo () const
virtual phaseThermo & thermo ()
PurePhaseModel (const phaseSystem &fluid, const word &phaseName, const label index)
virtual ~PurePhaseModel ()
virtual bool pure () const
virtual tmp< fvScalarMatrix > YiEqn (volScalarField &Yi)
virtual const PtrList< volScalarField > & Y () const
virtual const volScalarField & Y (const word &name) const
virtual PtrList< volScalarField > & YRef ()
virtual const UPtrList< volScalarField > & YActive () const
virtual UPtrList< volScalarField > & YActiveRef ()
Protected Attributes
PtrList< volScalarField > Y_
autoPtr< phaseThermo > thermoPtr_
Detailed Description
template<class BasePhaseModel, class phaseThermo>
class Foam::PurePhaseModel< BasePhaseModel, phaseThermo >
Class which represents pure phases, i.e. without any species. Returns an empty list of mass fractions.
Source files
PurePhaseModel.H
PurePhaseModel.C
Source files
PurePhaseModel.H
PurePhaseModel.C
Definition at line 52 of file PurePhaseModel.H.
Constructor & Destructor Documentation
PurePhaseModel() [1/2]
template<class BasePhaseModel , class phaseThermo > PurePhaseModel (const multiphaseInterSystem & fluid, const word & phaseName)
Definition at line 28 of file PurePhaseModel.C.
References basicThermo::dictName, fluid, basicThermo::phasePropertyName(), autoPtr< T >::reset(), and PurePhaseModel< BasePhaseModel, phaseThermo >::thermoPtr_.
~PurePhaseModel() [1/2]
template<class BasePhaseModel > ~PurePhaseModel () virtual default
Definition at line 41 of file PurePhaseModel.C.
PurePhaseModel() [2/2]
template<class BasePhaseModel > PurePhaseModel (const phaseSystem & fluid, const word & phaseName, const label index)
Definition at line 27 of file PurePhaseModel.C.
~PurePhaseModel() [2/2]
template<class BasePhaseModel , class phaseThermo > virtual ~PurePhaseModel () virtual
Member Function Documentation
Y() [1/4]
template<class BasePhaseModel > const Foam::PtrList< Foam::volScalarField > & Y () const virtual
Definition at line 64 of file PurePhaseModel.C.
Y() [2/4]
template<class BasePhaseModel , class phaseThermo > Foam::PtrList< Foam::volScalarField > & Y () virtual
Definition at line 72 of file PurePhaseModel.C.
solveYi()
template<class BasePhaseModel , class phaseThermo > void solveYi (PtrList< volScalarField::Internal > & , PtrList< volScalarField::Internal > &) virtual
Definition at line 52 of file PurePhaseModel.C.
References NotImplemented.
thermo() [1/2]
template<class BasePhaseModel , class phaseThermo > const phaseThermo & thermo () const virtual
Definition at line 79 of file PurePhaseModel.C.
thermo() [2/2]
template<class BasePhaseModel , class phaseThermo > phaseThermo & thermo () virtual
Definition at line 87 of file PurePhaseModel.C.
pure()
template<class BasePhaseModel > bool pure () const virtual
Definition at line 48 of file PurePhaseModel.C.
YiEqn()
template<class BasePhaseModel > Foam::tmp< Foam::fvScalarMatrix > YiEqn (volScalarField & Yi) virtual
Definition at line 56 of file PurePhaseModel.C.
References Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
Y() [3/4]
template<class BasePhaseModel , class phaseThermo > virtual const PtrList< volScalarField > & Y () const virtual
Y() [4/4]
template<class BasePhaseModel > const Foam::volScalarField & Y (const word & name) const virtual
Definition at line 78 of file PurePhaseModel.C.
References Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
YRef()
template<class BasePhaseModel > Foam::PtrList< Foam::volScalarField > & YRef () virtual
Definition at line 90 of file PurePhaseModel.C.
References Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
YActive()
template<class BasePhaseModel > const Foam::UPtrList< Foam::volScalarField > & YActive () const virtual
Definition at line 102 of file PurePhaseModel.C.
YActiveRef()
template<class BasePhaseModel > Foam::UPtrList< Foam::volScalarField > & YActiveRef () virtual
Definition at line 112 of file PurePhaseModel.C.
References Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
Member Data Documentation
Y_
template<class BasePhaseModel , class phaseThermo > PtrList< volScalarField > Y_ protected
Definition at line 61 of file PurePhaseModel.H.
thermoPtr_
template<class BasePhaseModel , class phaseThermo > autoPtr<phaseThermo> thermoPtr_ protected
Definition at line 64 of file PurePhaseModel.H.
Referenced by PurePhaseModel< BasePhaseModel, phaseThermo >::PurePhaseModel().
The documentation for this class was generated from the following files:
src/phaseSystemModels/multiphaseInter/phasesSystem/phaseModel/PurePhaseModel/PurePhaseModel.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/phaseModel/PurePhaseModel/PurePhaseModel.H
src/phaseSystemModels/multiphaseInter/phasesSystem/phaseModel/PurePhaseModel/PurePhaseModel.C
src/phaseSystemModels/reactingEuler/multiphaseSystem/phaseModel/PurePhaseModel/PurePhaseModel.C