OpenFOAM: SpalartAllmarasBase< BasicEddyViscosityModel > Class Template Reference
SpalartAllmarasBase< BasicEddyViscosityModel > Class Template Reference abstract
#include <SpalartAllmarasBase.H>
Public Types
typedef BasicEddyViscosityModel::alphaField alphaField
typedef BasicEddyViscosityModel::rhoField rhoField
typedef BasicEddyViscosityModel::transportModel transportModel
Public Member Functions
SpalartAllmarasBase (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
virtual ~SpalartAllmarasBase ()=default
virtual bool read ()
tmp< volScalarField > DnuTildaEff () const
virtual tmp< volScalarField > k () const
virtual tmp< volScalarField > epsilon () const
virtual tmp< volScalarField > omega () const
tmp< volScalarField > nuTilda () const
virtual void correct ()
Protected Member Functions
tmp< volScalarField > chi () const
tmp< volScalarField > fv1 (const volScalarField &chi) const
tmp< volScalarField > fv2 (const volScalarField &chi, const volScalarField &fv1) const
tmp< volScalarField > ft2 (const volScalarField &chi) const
tmp< volScalarField > Omega (const volTensorField &gradU) const
tmp< volScalarField > r (const volScalarField &nur, const volScalarField &Stilda, const volScalarField &dTilda) const
tmp< volScalarField::Internal > fw (const volScalarField &Stilda, const volScalarField &dTilda) const
virtual tmp< volScalarField > Stilda (const volScalarField &chi, const volScalarField &fv1, const volTensorField &gradU, const volScalarField &dTilda) const
virtual tmp< volScalarField > dTilda (const volScalarField &chi, const volScalarField &fv1, const volTensorField &gradU) const =0
void correctNut (const volScalarField &fv1)
virtual void correctNut ()
Protected Attributes
dimensionedScalar sigmaNut_
dimensionedScalar kappa_
dimensionedScalar Cb1_
dimensionedScalar Cb2_
dimensionedScalar Cw1_
dimensionedScalar Cw2_
dimensionedScalar Cw3_
dimensionedScalar Cv1_
dimensionedScalar Cs_
dimensionedScalar ck_
Switch ft2_
dimensionedScalar Ct3_
dimensionedScalar Ct4_
volScalarField nuTilda_
const volScalarField & y_
Detailed Description
template<class BasicEddyViscosityModel>
class Foam::SpalartAllmarasBase< BasicEddyViscosityModel >
Definition at line 76 of file SpalartAllmarasBase.H.
Member Typedef Documentation
alphaField
template<class BasicEddyViscosityModel > typedef BasicEddyViscosityModel::alphaField alphaField
Definition at line 174 of file SpalartAllmarasBase.H.
rhoField
template<class BasicEddyViscosityModel > typedef BasicEddyViscosityModel::rhoField rhoField
Definition at line 175 of file SpalartAllmarasBase.H.
transportModel
template<class BasicEddyViscosityModel > typedef BasicEddyViscosityModel::transportModel transportModel
Definition at line 176 of file SpalartAllmarasBase.H.
Constructor & Destructor Documentation
SpalartAllmarasBase()
template<class BasicEddyViscosityModel > SpalartAllmarasBase (const word & type, const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName)
Definition at line 175 of file SpalartAllmarasBase.C.
~SpalartAllmarasBase()
template<class BasicEddyViscosityModel > virtual ~SpalartAllmarasBase () virtual default
Member Function Documentation
chi()
template<class BasicEddyViscosityModel > tmp< volScalarField > chi () const protected
Definition at line 35 of file SpalartAllmarasBase.C.
References nu.
fv1()
template<class BasicEddyViscosityModel > tmp< volScalarField > fv1 (const volScalarField & chi) const protected
Definition at line 42 of file SpalartAllmarasBase.C.
References Foam::pow3(), and PtrList< T >::PtrList().
fv2()
template<class BasicEddyViscosityModel > tmp< volScalarField > fv2 (const volScalarField & chi, const volScalarField & fv1) const protected
Definition at line 53 of file SpalartAllmarasBase.C.
References PtrList< T >::PtrList().
ft2()
template<class BasicEddyViscosityModel > tmp< volScalarField > ft2 (const volScalarField & chi) const protected
Definition at line 64 of file SpalartAllmarasBase.C.
References Foam::dimless, Foam::exp(), tmp< T >::New(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, Foam::sqr(), and Foam::Zero.
Omega()
template<class BasicEddyViscosityModel > tmp< volScalarField > Omega (const volTensorField & gradU) const protected
Definition at line 91 of file SpalartAllmarasBase.C.
References Foam::mag(), Foam::skew(), and Foam::sqrt().
r()
template<class BasicEddyViscosityModel > tmp< volScalarField > r (const volScalarField & nur, const volScalarField & Stilda, const volScalarField & dTilda) const protected
Definition at line 101 of file SpalartAllmarasBase.C.
References DimensionedField< Type, GeoMesh >::dimensions(), Foam::max(), Foam::min(), PtrList< T >::PtrList(), Foam::sqr(), and Foam::tr().
fw()
template<class BasicEddyViscosityModel > tmp< volScalarField::Internal > fw (const volScalarField & Stilda, const volScalarField & dTilda) const protected
Definition at line 120 of file SpalartAllmarasBase.C.
Stilda()
template<class BasicEddyViscosityModel > tmp< volScalarField > Stilda (const volScalarField & chi, const volScalarField & fv1, const volTensorField & gradU, const volScalarField & dTilda) const protected virtual
Definition at line 134 of file SpalartAllmarasBase.C.
dTilda()
template<class BasicEddyViscosityModel > virtual tmp< volScalarField > dTilda (const volScalarField & chi, const volScalarField & fv1, const volTensorField & gradU) const protected pure virtual
Implemented in SpalartAllmaras< BasicTurbulenceModel >.
correctNut() [1/2]
template<class BasicEddyViscosityModel > void correctNut (const volScalarField & fv1) protected
Definition at line 154 of file SpalartAllmarasBase.C.
References GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), and options::New().
correctNut() [2/2]
template<class BasicEddyViscosityModel > void correctNut () protected virtual
Reimplemented in SpalartAllmaras< BasicTurbulenceModel >.
Definition at line 166 of file SpalartAllmarasBase.C.
Referenced by SpalartAllmaras< BasicTurbulenceModel >::correctNut().
read()
template<class BasicEddyViscosityModel > bool read () virtual
Definition at line 338 of file SpalartAllmarasBase.C.
References Foam::Info, Foam::nl, dimensioned< Type >::readIfPresent(), and Foam::sqr().
DnuTildaEff()
template<class BasicEddyViscosityModel > tmp< volScalarField > DnuTildaEff () const
Definition at line 376 of file SpalartAllmarasBase.C.
References IOobject::groupName(), and tmp< T >::New().
k()
template<class BasicEddyViscosityModel > tmp< volScalarField > k () const virtual
Definition at line 387 of file SpalartAllmarasBase.C.
References Foam::cbrt(), Foam::fvc::grad(), IOobject::groupName(), Foam::mag(), tmp< T >::New(), PtrList< T >::PtrList(), Foam::sqrt(), and Foam::symm().
epsilon()
template<class BasicEddyViscosityModel > tmp< volScalarField > epsilon () const virtual
Definition at line 402 of file SpalartAllmarasBase.C.
References IOobject::groupName(), k, tmp< T >::New(), PtrList< T >::PtrList(), Foam::sqr(), and Foam::sqrt().
omega()
template<class BasicEddyViscosityModel > tmp< volScalarField > omega () const virtual
Definition at line 418 of file SpalartAllmarasBase.C.
References Foam::dimLength, Foam::dimTime, IOobject::groupName(), tmp< T >::New(), and Foam::sqr().
nuTilda()
template<class BasicEddyViscosityModel > tmp< volScalarField > nuTilda () const inline
Definition at line 217 of file SpalartAllmarasBase.H.
References SpalartAllmarasBase< BasicEddyViscosityModel >::nuTilda_.
correct()
template<class BasicEddyViscosityModel > void correct () virtual
Definition at line 433 of file SpalartAllmarasBase.C.
References alpha, Foam::bound(), PtrList< T >::clear(), Foam::fvm::ddt(), Foam::fvm::div(), fvOptions, Foam::fvc::grad(), Foam::fvm::laplacian(), Foam::magSqr(), options::New(), PtrList< T >::PtrList(), rho, solve(), Foam::fvm::Sp(), Foam::sqr(), U, and Foam::Zero.
Member Data Documentation
sigmaNut_
template<class BasicEddyViscosityModel > dimensionedScalar sigmaNut_ protected
Definition at line 95 of file SpalartAllmarasBase.H.
kappa_
template<class BasicEddyViscosityModel > dimensionedScalar kappa_ protected
Definition at line 96 of file SpalartAllmarasBase.H.
Cb1_
template<class BasicEddyViscosityModel > dimensionedScalar Cb1_ protected
Definition at line 98 of file SpalartAllmarasBase.H.
Cb2_
template<class BasicEddyViscosityModel > dimensionedScalar Cb2_ protected
Definition at line 99 of file SpalartAllmarasBase.H.
Cw1_
template<class BasicEddyViscosityModel > dimensionedScalar Cw1_ protected
Definition at line 100 of file SpalartAllmarasBase.H.
Cw2_
template<class BasicEddyViscosityModel > dimensionedScalar Cw2_ protected
Definition at line 101 of file SpalartAllmarasBase.H.
Cw3_
template<class BasicEddyViscosityModel > dimensionedScalar Cw3_ protected
Definition at line 102 of file SpalartAllmarasBase.H.
Cv1_
template<class BasicEddyViscosityModel > dimensionedScalar Cv1_ protected
Definition at line 103 of file SpalartAllmarasBase.H.
Cs_
template<class BasicEddyViscosityModel > dimensionedScalar Cs_ protected
Definition at line 104 of file SpalartAllmarasBase.H.
ck_
template<class BasicEddyViscosityModel > dimensionedScalar ck_ protected
Definition at line 105 of file SpalartAllmarasBase.H.
ft2_
template<class BasicEddyViscosityModel > Switch ft2_ protected
Definition at line 107 of file SpalartAllmarasBase.H.
Ct3_
template<class BasicEddyViscosityModel > dimensionedScalar Ct3_ protected
Definition at line 108 of file SpalartAllmarasBase.H.
Ct4_
template<class BasicEddyViscosityModel > dimensionedScalar Ct4_ protected
Definition at line 109 of file SpalartAllmarasBase.H.
nuTilda_
template<class BasicEddyViscosityModel > volScalarField nuTilda_ protected
Definition at line 115 of file SpalartAllmarasBase.H.
Referenced by SpalartAllmarasBase< BasicEddyViscosityModel >::nuTilda().
y_
template<class BasicEddyViscosityModel > const volScalarField& y_ protected
Definition at line 120 of file SpalartAllmarasBase.H.
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/Base/SpalartAllmaras/SpalartAllmarasBase.H
src/TurbulenceModels/turbulenceModels/Base/SpalartAllmaras/SpalartAllmarasBase.C