OpenFOAM: cellModel Class Reference
cellModel Class Reference
Maps a geometry to a set of cell primitives.
#include <cellModel.H>
Public Types
enum modelType {
UNKNOWN = 0 , HEX = 3 , WEDGE = 4 , PRISM = 5 ,
PYR = 6 , TET = 7 , SPLITHEX = 8 , TETWEDGE = 9
}
Public Member Functions
cellModel (Istream &is)
autoPtr< cellModel > clone () const
const word & name () const noexcept
label index () const noexcept
label nPoints () const noexcept
label nEdges () const noexcept
label nFaces () const noexcept
const edgeList & modelEdges () const noexcept
const faceList & modelFaces () const noexcept
edgeList edges (const labelUList &pointLabels) const
faceList faces (const labelUList &pointLabels) const
Foam::edge edge (const label modelEdgei, const labelUList &pointLabels) const
Foam::face face (const label modelFacei, const labelUList &pointLabels) const
vector centre (const labelList &pointLabels, const UList< point > &points) const
scalar mag (const labelList &pointLabels, const UList< point > &points) const
InfoProxy< cellModel > info () const noexcept
bool writeData (Ostream &os) const
Static Public Member Functions
static const cellModel * ptr (const modelType model)
static const cellModel * ptr (const word &modelName)
static const cellModel * ptr (const label modelIndex)
static const cellModel & ref (const modelType model)
static const cellModel & ref (const word &modelName)
static const cellModel & ref (const label modelIndex)
static autoPtr< cellModel > New (Istream &is)
Static Public Attributes
static const Enum< modelType > modelNames
Friends
Ostream & operator<< (Ostream &os, const cellModel &cm)
Detailed Description
Maps a geometry to a set of cell primitives.
This enables geometric cell data to be calculated without access to the primitive geometric level. This means mapping a 3D geometry to a set of pyramids which are each described by a cell face and the cell centre point.
Also includes a static collection of cell models (normally loaded from etc/cellModels), and a means of looking them up.
Source files
cellModel.H
cellModelI.H
cellModel.C
cellModels.C
cellModelIO.C
Definition at line 72 of file cellModel.H.
Member Enumeration Documentation
modelType
enum modelType
Enumerator
UNKNOWN
unknown
HEX
hex
WEDGE
wedge
PRISM
prism
PYR
pyr
TET
tet
SPLITHEX
splitHex
TETWEDGE
tetWedge
Definition at line 78 of file cellModel.H.
Constructor & Destructor Documentation
cellModel()
cellModel (Istream & is) explicit
Definition at line 27 of file cellModelIO.C.
References dict, and dictionary::null.
Member Function Documentation
ptr() [1/3]
const Foam::cellModel * ptr (const modelType model) static
Definition at line 113 of file cellModels.C.
Referenced by cellModeller::lookup(), cellModeller::lookup(), cellMatcher::model(), STARCDMeshReader::readCells(), tetCell::shape(), hexCell::shape(), shapeToCell::shapeToCell(), and shapeToCell::shapeToCell().
ptr() [2/3]
const Foam::cellModel * ptr (const word & modelName) static
Definition at line 119 of file cellModels.C.
References n, Foam::name(), and UPtrList< T >::size().
ptr() [3/3]
const Foam::cellModel * ptr (const label modelIndex) static
Definition at line 139 of file cellModels.C.
References UPtrList< T >::size().
ref() [1/3]
const Foam::cellModel & ref (const modelType model) static
Definition at line 150 of file cellModels.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and p.
Referenced by PDRblock::blockMeshDict(), STARCDMeshReader::readBoundary(), STARCDMeshReader::readCells(), ABAQUSCore::readHelper::readSurfaceElements(), vtuSizing::reset(), vtuSizing::resetShapes(), and writer::writer().
ref() [2/3]
const Foam::cellModel & ref (const word & modelName) static
Definition at line 165 of file cellModels.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and p.
ref() [3/3]
const Foam::cellModel & ref (const label modelIndex) static
Definition at line 180 of file cellModels.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and p.
New()
static autoPtr< cellModel > New (Istream & is) inline static
Definition at line 160 of file cellModel.H.
References autoPtr< T >::New().
clone()
autoPtr< cellModel > clone () const inline
Definition at line 166 of file cellModel.H.
References autoPtr< T >::New().
name()
const Foam::word & name () const inline noexcept
Definition at line 24 of file cellModelI.H.
index()
Foam::label index () const inline noexcept
Definition at line 30 of file cellModelI.H.
nPoints()
Foam::label nPoints () const inline noexcept
Definition at line 36 of file cellModelI.H.
nEdges()
Foam::label nEdges () const inline noexcept
Definition at line 42 of file cellModelI.H.
References UPtrList< T >::size().
nFaces()
Foam::label nFaces () const inline noexcept
Definition at line 48 of file cellModelI.H.
References UPtrList< T >::size().
modelEdges()
const Foam::edgeList & modelEdges () const inline noexcept
Definition at line 54 of file cellModelI.H.
modelFaces()
const Foam::faceList & modelFaces () const inline noexcept
Definition at line 60 of file cellModelI.H.
Referenced by ABAQUSCore::readHelper::readSurfaceElements().
edges()
Foam::edgeList edges (const labelUList & pointLabels) const inline
Definition at line 66 of file cellModelI.H.
References forAll, and pointLabels().
faces()
Foam::faceList faces (const labelUList & pointLabels) const inline
Definition at line 94 of file cellModelI.H.
References forAll, and pointLabels().
edge()
Foam::edge edge (const label modelEdgei, const labelUList & pointLabels) const inline
Definition at line 83 of file cellModelI.H.
References pointLabels().
face()
Foam::face face (const label modelFacei, const labelUList & pointLabels) const inline
Definition at line 111 of file cellModelI.H.
References pointLabels().
centre()
Foam::vector centre (const labelList & pointLabels, const UList< point > & points) const
Definition at line 27 of file cellModel.C.
References Foam::endl(), f(), forAll, pointLabels(), points, WarningInFunction, and Foam::Zero.
mag()
Foam::scalar mag (const labelList & pointLabels, const UList< point > & points) const
Definition at line 70 of file cellModel.C.
References Foam::endl(), f(), forAll, pointLabels(), points, UList< T >::size(), WarningInFunction, and Foam::Zero.
info()
InfoProxy< cellModel > info () const inline noexcept
Definition at line 233 of file cellModel.H.
writeData()
bool writeData (Ostream & os) const inline
Definition at line 236 of file cellModel.H.
References os().
Friends And Related Symbol Documentation
operator<<
Ostream & operator<< (Ostream & os, const cellModel & cm) friend
Member Data Documentation
modelNames
const Foam::Enum< Foam::cellModel::modelType > modelNames static
Definition at line 92 of file cellModel.H.
Referenced by Foam::serializeHex().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/meshShapes/cellModel/cellModel.H
src/OpenFOAM/meshes/meshShapes/cellModel/cellModel.C
src/OpenFOAM/meshes/meshShapes/cellModel/cellModelI.H
src/OpenFOAM/meshes/meshShapes/cellModel/cellModelIO.C
src/OpenFOAM/meshes/meshShapes/cellModel/cellModels.C