OpenFOAM: faMeshBoundaryHalo Class Reference
faMeshBoundaryHalo Class Reference
Class for obtaining halo face data for the boundary edges. The ordering follows that natural edge ordering of the underlying primitive patch.
#include <faMeshBoundaryHalo.H>
Public Member Functions
ClassName ("faMeshBoundaryHalo")
faMeshBoundaryHalo (const label comm=UPstream::worldComm)
faMeshBoundaryHalo (const faMesh &mesh)
void clear ()
void reset (const faMesh &mesh)
label haloSize () const
const labelList & inputMeshFaces () const noexcept
template<class Type >
void distributeSparse (List< Type > &fld, const labelUList &sparseInputLocations, const labelUList &compactOutputMapping) const
template<class Type >
void distributeSparse (List< Type > &fld, const labelUList &sparseInputLocations) const
template<class Type >
void distributeSparse (List< Type > &fld) const
Public Member Functions inherited from mapDistributeBase
ClassName ("mapDistributeBase")
mapDistributeBase ()
mapDistributeBase (const label comm)
mapDistributeBase (const mapDistributeBase &map)
mapDistributeBase (mapDistributeBase &&map)
mapDistributeBase (const dictionary &dict, const label comm=UPstream::worldComm)
mapDistributeBase (const label constructSize, labelListList &&subMap, labelListList &&constructMap, const bool subHasFlip=false, const bool constructHasFlip=false, const label comm=UPstream::worldComm)
mapDistributeBase (const labelUList &sendProcs, const labelUList &recvProcs, const label comm=UPstream::worldComm)
mapDistributeBase (const globalIndex &, labelList &elements, List< Map< label > > &compactMap, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm)
mapDistributeBase (const globalIndex &, labelListList &cellCells, List< Map< label > > &compactMap, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm)
mapDistributeBase (labelListList &&subMap, const bool subHasFlip=false, const bool constructHasFlip=false, const label comm=UPstream::worldComm)
mapDistributeBase (Istream &is)
label constructSize () const noexcept
label & constructSize () noexcept
const labelListList & subMap () const noexcept
labelListList & subMap () noexcept
const labelListList & constructMap () const noexcept
labelListList & constructMap () noexcept
bool subHasFlip () const noexcept
bool & subHasFlip () noexcept
bool constructHasFlip () const noexcept
bool & constructHasFlip () noexcept
label comm () const noexcept
label nMaps () const noexcept
labelList subMapSizes () const
labelList constructMapSizes () const
const List< labelPair > & schedule () const
const List< labelPair > & whichSchedule (const UPstream::commsTypes commsType) const
void clear ()
void transfer (mapDistributeBase &rhs)
void compactLocalData (const bitSet &allowedLocalElems, const int tag=UPstream::msgType(), const bool doRenumber=false)
void compactRemoteData (const bitSet &allowedRemoteElems, const int tag=UPstream::msgType(), const bool doRenumber=false)
void compactLocalData (const bitSet &allowedLocalElems, labelList &oldToNewSub, labelList &oldToNewConstruct, const label localSize=-1, const int tag=UPstream::msgType())
void compactRemoteData (const bitSet &allowedRemoteElems, labelList &oldToNewSub, labelList &oldToNewConstruct, const label localSize=-1, const int tag=UPstream::msgType())
void compactData (const labelUList &localElements, const labelUList &remoteElements, labelList &oldToNewSub, labelList &oldToNewConstruct, const label localSize=-1, const int tag=UPstream::msgType())
void compactLocalData (const labelUList &localElements, labelList &oldToNewSub, labelList &oldToNewConstruct, const label localSize=-1, const int tag=UPstream::msgType())
void compactRemoteData (const labelUList &remoteElements, labelList &oldToNewSub, labelList &oldToNewConstruct, const label localSize=-1, const int tag=UPstream::msgType())
template<class T >
void distribute (List< T > &values, const int tag=UPstream::msgType()) const
template<class T >
void distribute (DynamicList< T > &values, const int tag=UPstream::msgType()) const
template<class T , class NegateOp >
void distribute (List< T > &values, const NegateOp &negOp, const int tag=UPstream::msgType()) const
template<class T , class NegateOp >
void distribute (const Pstream::commsTypes commsType, List< T > &values, const NegateOp &negOp, const int tag=UPstream::msgType()) const
template<class T , class NegateOp >
void distribute (const Pstream::commsTypes commsType, const T &nullValue, List< T > &values, const NegateOp &negOp, const int tag=UPstream::msgType()) const
template<class T >
void reverseDistribute (const label constructSize, List< T > &values, const int tag=UPstream::msgType()) const
template<class T >
void reverseDistribute (const label constructSize, const T &nullValue, List< T > &values, const int tag=UPstream::msgType()) const
template<class T >
void reverseDistribute (const Pstream::commsTypes commsType, const label constructSize, List< T > &values, const int tag=UPstream::msgType()) const
template<class T , class NegateOp >
void reverseDistribute (const Pstream::commsTypes commsType, const label constructSize, List< T > &values, const NegateOp &negOp, const int tag=UPstream::msgType()) const
template<class T >
void reverseDistribute (const Pstream::commsTypes commsType, const label constructSize, const T &nullValue, List< T > &values, const int tag=UPstream::msgType()) const
template<class T >
void send (PstreamBuffers &pBufs, const List< T > &field) const
template<class T >
void receive (PstreamBuffers &pBufs, List< T > &field) const
template<class T >
void send (const UList< T > &field, labelRange &requests, PtrList< List< T > > &sendFields, PtrList< List< T > > &recvFields, const int tag=UPstream::msgType()) const
template<class T >
void receive (const labelRange &requests, const UPtrList< List< T > > &sendFields, const UPtrList< List< T > > &recvFields, List< T > &field, const int tag=UPstream::msgType()) const
void printLayout (Ostream &os) const
void operator= (const mapDistributeBase &rhs)
void operator= (mapDistributeBase &&rhs)
InfoProxy< mapDistributeBase > info () const noexcept
void readDict (const dictionary &dict)
void writeEntries (Ostream &os) const
void updateMesh (const mapPolyMesh &)
void compact (const boolList &remoteElemUsed, const int tag=UPstream::msgType())
void compact (const boolList &remoteElemUsed, const label localSize, labelList &oldToNewSub, labelList &oldToNewConstruct, const int tag=UPstream::msgType())
template<class T , class NegateOp >
Foam::List< T > accessAndFlip (const UList< T > &values, const labelUList &indices, const bool hasFlip, const NegateOp &negOp)
Additional Inherited Members
Static Public Member Functions inherited from mapDistributeBase
static bool hasFlipAddressing (const labelUList &map)
static bool hasFlipAddressing (const labelListList &maps)
static label countUnmapped (const labelUList &elements, const labelListList &maps, const bool hasFlip)
static List< labelPair > schedule (const labelListList &subMap, const labelListList &constructMap, const int tag, const label comm=UPstream::worldComm)
static label renumber (const globalIndex &, const List< Map< label > > &compactMap, const label globalElement)
static label renumberMap (labelListList &mapElements, const labelUList &oldToNew, const bool hasFlip)
template<class T , class NegateOp >
static void distribute (const Pstream::commsTypes commsType, const List< labelPair > &schedule, const label constructSize, const labelListList &subMap, const bool subHasFlip, const labelListList &constructMap, const bool constructHasFlip, List< T > &field, const NegateOp &negOp, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm)
template<class T , class CombineOp , class NegateOp >
static void distribute (const Pstream::commsTypes commsType, const List< labelPair > &schedule, const label constructSize, const labelListList &subMap, const bool subHasFlip, const labelListList &constructMap, const bool constructHasFlip, List< T > &field, const T &nullValue, const CombineOp &cop, const NegateOp &negOp, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm)
template<class T , class negateOp >
static void send (const labelListList &subMap, const bool subHasFlip, const labelListList &constructMap, const bool constructHasFlip, const UList< T > &field, labelRange &requests, PtrList< List< T > > &sendFields, PtrList< List< T > > &recvFields, const negateOp &negOp, const int tag, const label comm)
template<class T , class CombineOp , class negateOp >
static void receive (const label constructSize, const labelListList &constructMap, const bool constructHasFlip, const UPtrList< List< T > > &sendFields, const UPtrList< List< T > > &recvFields, const labelRange &requests, List< T > &field, const CombineOp &cop, const negateOp &negOp, const int tag, const label comm)
Protected Member Functions inherited from mapDistributeBase
void calcCompactAddressing (const globalIndex &globalNumbering, const labelUList &elements, List< Map< label > > &compactMap) const
void calcCompactAddressing (const globalIndex &globalNumbering, const labelListList &elements, List< Map< label > > &compactMap) const
void exchangeAddressing (const int tag, const globalIndex &globalNumbering, labelList &elements, List< Map< label > > &compactMap, labelList &compactStart)
void exchangeAddressing (const int tag, const globalIndex &globalNumbering, labelListList &elements, List< Map< label > > &compactMap, labelList &compactStart)
Static Protected Member Functions inherited from mapDistributeBase
static void checkReceivedSize (const label proci, const label expectedSize, const label receivedSize)
static label getMappedSize (const labelListList &maps, const bool hasFlip)
static void exchangeMasks (const UList< bitSet > &sendMasks, UList< bitSet > &recvMasks, const int tag, const label comm)
static void unionCombineMasks (UList< bitSet > &sendMasks, UList< bitSet > &recvMasks, const int tag, const label comm)
template<class T , class CombineOp , class NegateOp >
static void flipAndCombine (const labelUList &map, const bool hasFlip, const UList< T > &rhs, const CombineOp &cop, const NegateOp &negOp, List< T > &lhs)
template<class T , class NegateOp >
static T accessAndFlip (const UList< T > &values, const label index, const bool hasFlip, const NegateOp &negOp)
template<class T , class NegateOp >
static List< T > accessAndFlip (const UList< T > &values, const labelUList &indices, const bool hasFlip, const NegateOp &negOp)
Detailed Description
Class for obtaining halo face data for the boundary edges. The ordering follows that natural edge ordering of the underlying primitive patch.
Note
The halo faces can be located on-processor or off-processor.
Source files
faMeshBoundaryHalo.H
faMeshBoundaryHalo.C
faMeshBoundaryHaloTemplates.C
Definition at line 55 of file faMeshBoundaryHalo.H.
Constructor & Destructor Documentation
faMeshBoundaryHalo() [1/2]
faMeshBoundaryHalo (const label comm = UPstream::worldComm) explicit
Definition at line 36 of file faMeshBoundaryHalo.C.
faMeshBoundaryHalo() [2/2]
faMeshBoundaryHalo (const faMesh & mesh) explicit
Definition at line 44 of file faMeshBoundaryHalo.C.
References faMeshBoundaryHalo::reset().
Member Function Documentation
ClassName()
ClassName ("faMeshBoundaryHalo")
clear()
void clear ()
Definition at line 56 of file faMeshBoundaryHalo.C.
reset()
void reset (const faMesh & mesh)
Definition at line 78 of file faMeshBoundaryHalo.C.
References PtrList< T >::clear(), UPtrList< T >::first(), forAll, UPstream::msgType(), UPstream::myProcNo(), UPstream::nProcs(), UPstream::parRun(), List< T >::resize(), PtrList< T >::resize(), and UPtrList< T >::size().
Referenced by faMeshBoundaryHalo::faMeshBoundaryHalo().
haloSize()
Foam::label haloSize () const
Definition at line 65 of file faMeshBoundaryHalo.C.
References UPstream::parRun(), and UPtrList< T >::size().
inputMeshFaces()
const labelList & inputMeshFaces () const inline noexcept
Definition at line 99 of file faMeshBoundaryHalo.H.
distributeSparse() [1/3]
template<class Type > void distributeSparse (List< Type > & fld, const labelUList & sparseInputLocations, const labelUList & compactOutputMapping) const
Definition at line 28 of file faMeshBoundaryHaloTemplates.C.
References mapDistributeBase::constructSize(), UPtrList< T >::empty(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, fld(), forAll, UPstream::parRun(), UPtrList< T >::size(), and Foam::Zero.
distributeSparse() [2/3]
template<class Type > void distributeSparse (List< Type > & fld, const labelUList & sparseInputLocations) const
Definition at line 83 of file faMeshBoundaryHaloTemplates.C.
References fld().
distributeSparse() [3/3]
template<class Type > void distributeSparse (List< Type > & fld) const
Definition at line 94 of file faMeshBoundaryHaloTemplates.C.
References fld().
The documentation for this class was generated from the following files:
src/finiteArea/faMesh/faMeshBoundaryHalo.H
src/finiteArea/faMesh/faMeshBoundaryHalo.C
src/finiteArea/faMesh/faMeshBoundaryHaloTemplates.C