OpenFOAM: ogzstream Class Reference
ogzstream Class Reference
#include <gzstream.h>
Public Member Functions
ogzstream ()
ogzstream (const char *_name, int _open_mode=std::ios::out)
ogzstream (const std::string &_name, int _open_mode=std::ios::out)
gzstreambuf * rdbuf ()
void open (const char *_name, int _open_mode=std::ios::out)
void open (const std::string &_name, int _open_mode=std::ios::out)
Public Member Functions inherited from gzstreambase
gzstreambase ()
gzstreambase (const char *_name, int _open_mode)
~gzstreambase ()
void open (const char *_name, int _open_mode)
void close ()
gzstreambuf * rdbuf ()
Additional Inherited Members
Protected Attributes inherited from gzstreambase
gzstreambuf buf
Detailed Description
Definition at line 196 of file gzstream.h.
Constructor & Destructor Documentation
ogzstream() [1/3]
ogzstream () inline
Definition at line 204 of file gzstream.h.
ogzstream() [2/3]
ogzstream (const char * _name, int _open_mode = std::ios::out) inline explicit
Definition at line 208 of file gzstream.h.
ogzstream() [3/3]
ogzstream (const std::string & _name, int _open_mode = std::ios::out) inline explicit
Definition at line 214 of file gzstream.h.
Member Function Documentation
rdbuf()
gzstreambuf * rdbuf () inline
Definition at line 220 of file gzstream.h.
References gzstreambase::rdbuf().
open() [1/2]
void open (const char * _name, int _open_mode = std::ios::out) inline
Definition at line 224 of file gzstream.h.
References gzstreambase::open().
open() [2/2]
void open (const std::string & _name, int _open_mode = std::ios::out) inline
Definition at line 229 of file gzstream.h.
References gzstreambase::open().
The documentation for this class was generated from the following file:
src/OpenFOAM/db/IOstreams/gzstream/gzstream.h