OpenFOAM: boundaryPatch Class Reference
boundaryPatch Class Reference
Like polyPatch but without reference to mesh. Used in boundaryMesh to hold data on patches. The patchIdentifier::index is set, but not used.
#include <boundaryPatch.H>
Public Member Functions
boundaryPatch (const word &name, const label index, const label size, const label start, const word &physicalType=word::null)
boundaryPatch (const word &name, const dictionary &dict, const label index)
boundaryPatch (const boundaryPatch &p, const label index)
autoPtr< boundaryPatch > clone () const
label size () const
label & size ()
label start () const
label & start ()
virtual void write (Ostream &os) const
Public Member Functions inherited from patchIdentifier
patchIdentifier (const patchIdentifier &)=default
patchIdentifier & operator= (const patchIdentifier &)=default
virtual ~patchIdentifier ()=default
patchIdentifier ()
patchIdentifier (const word &name, const label index)
patchIdentifier (const word &name, const label index, const word &physicalType, const wordList &inGroups=wordList())
patchIdentifier (const word &name, const dictionary &dict, const label index)
patchIdentifier (const patchIdentifier &ident, const label index)
const word & name () const noexcept
word & name () noexcept
label index () const noexcept
label & index () noexcept
const word & physicalType () const noexcept
word & physicalType () noexcept
const wordList & inGroups () const noexcept
wordList & inGroups () noexcept
bool inGroup (const word &name) const
void write (Ostream &os) const
Additional Inherited Members
Static Public Member Functions inherited from patchIdentifier
static word defaultName (const label n=-1)
Detailed Description
Like polyPatch but without reference to mesh. Used in boundaryMesh to hold data on patches. The patchIdentifier::index is set, but not used.
Source files
boundaryPatch.H
boundaryPatch.C
Definition at line 50 of file boundaryPatch.H.
Constructor & Destructor Documentation
boundaryPatch() [1/3]
boundaryPatch (const word & name, const label index, const label size, const label start, const word & physicalType = word::null)
Definition at line 28 of file boundaryPatch.C.
References Foam::name().
boundaryPatch() [2/3]
boundaryPatch (const word & name, const dictionary & dict, const label index)
Definition at line 43 of file boundaryPatch.C.
boundaryPatch() [3/3]
boundaryPatch (const boundaryPatch & p, const label index)
Definition at line 56 of file boundaryPatch.C.
References patchIdentifier::index().
Member Function Documentation
clone()
autoPtr< boundaryPatch > clone () const inline
Definition at line 90 of file boundaryPatch.H.
References autoPtr< T >::New().
size() [1/2]
label size () const inline
Definition at line 98 of file boundaryPatch.H.
size() [2/2]
label & size () inline
Definition at line 103 of file boundaryPatch.H.
start() [1/2]
label start () const inline
Definition at line 108 of file boundaryPatch.H.
start() [2/2]
label & start () inline
Definition at line 113 of file boundaryPatch.H.
write()
void write (Ostream & os) const virtual
Definition at line 66 of file boundaryPatch.C.
References os(), patchIdentifier::write(), and Ostream::writeEntry().
The documentation for this class was generated from the following files:
src/dynamicMesh/boundaryPatch/boundaryPatch.H
src/dynamicMesh/boundaryPatch/boundaryPatch.C