OpenFOAM: directionalPressureGradientExplicitSource Class Reference
directionalPressureGradientExplicitSource Class Reference
Numerics » Finite volume Options » Sources
Applies an explicit pressure gradient source in such a way to deflect the flow towards an specific direction (flowDir). Alternatively add an extra pressure drop in the flowDir direction using a model.
#include <directionalPressureGradientExplicitSource.H>
Public Types
enum pressureDropModel { pVolumetricFlowRateTable , pConstant , pDarcyForchheimer }
Public Types inherited from cellSetOption
enum selectionModeType {
smAll , smCellSet , smCellZone , smPoints ,
smGeometric , smCellType
}
Public Member Functions
TypeName ("directionalPressureGradientExplicitSource")
directionalPressureGradientExplicitSource (const word &sourceName, const word &modelType, const dictionary &dict, const fvMesh &mesh)
directionalPressureGradientExplicitSource (const directionalPressureGradientExplicitSource &)=delete
void operator= (const directionalPressureGradientExplicitSource &)=delete
virtual ~directionalPressureGradientExplicitSource ()=default
virtual void correct (volVectorField &U)
virtual void addSup (fvMatrix< vector > &eqn, const label fieldI)
virtual void addSup (const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldI)
virtual void constrain (fvMatrix< vector > &eqn, const label fieldI)
virtual void writeData (Ostream &os) const
virtual bool read (const dictionary &dict)
Public Member Functions inherited from cellSetOption
TypeName ("cellSetOption")
cellSetOption (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
virtual ~cellSetOption ()=default
scalar timeStart () const noexcept
scalar duration () const noexcept
bool inTimeLimits (const scalar timeValue) const
bool useSubMesh () const noexcept
selectionModeType selectionMode () const noexcept
const wordRes & selectionNames () const noexcept
const wordRe & zoneName () const
scalar V () const noexcept
const labelList & cells () const noexcept
scalar timeStart (scalar val) noexcept
scalar duration (scalar val) noexcept
virtual bool isActive ()
const word & cellSetName () const
Public Member Functions inherited from option
TypeName ("option")
declareRunTimeSelectionTable (autoPtr, option, dictionary,(const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh),(name, modelType, dict, mesh))
option (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
autoPtr< option > clone () const
virtual ~option ()=default
const word & name () const noexcept
const fvMesh & mesh () const noexcept
const dictionary & coeffs () const noexcept
bool active () const noexcept
void setApplied (const label fieldi)
bool active (const bool on) noexcept
virtual label applyToField (const word &fieldName) const
virtual void checkApplied () const
virtual void addSup (fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (fvMatrix< tensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< scalar > &eqn, const label fieldi)
virtual void constrain (fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< tensor > &eqn, const label fieldi)
virtual void correct (volScalarField &field)
virtual void correct (volSphericalTensorField &field)
virtual void correct (volSymmTensorField &field)
virtual void correct (volTensorField &field)
virtual void postProcessSens (scalarField &sensField, const word &fieldName=word::null, const word &designVariablesName=word::null)
virtual void postProcessSens (vectorField &sensField, const word &fieldName=word::null, const word &designVariablesName=word::null)
virtual void postProcessSens (tensorField &sensField, const word &fieldName=word::null, const word &designVariablesName=word::null)
virtual void writeHeader (Ostream &) const
virtual void writeFooter (Ostream &) const
Additional Inherited Members
Static Public Member Functions inherited from option
static autoPtr< option > New (const word &name, const dictionary &dict, const fvMesh &mesh)
Public Attributes inherited from option
bool log
Static Public Attributes inherited from cellSetOption
static const Enum< selectionModeType > selectionModeTypeNames_
Protected Member Functions inherited from cellSetOption
void setSelection (const dictionary &dict)
void setCellSelection ()
void setVol ()
Protected Member Functions inherited from option
void resetApplied ()
Protected Attributes inherited from cellSetOption
scalar timeStart_
scalar duration_
selectionModeType selectionMode_
wordRes selectionNames_
List< point > points_
dictionary geometricSelection_
labelList cells_
scalar V_
Protected Attributes inherited from option
const word name_
const word modelType_
const fvMesh & mesh_
dictionary dict_
dictionary coeffs_
wordList fieldNames_
List< bool > applied_
bool active_
Detailed Description
Applies an explicit pressure gradient source in such a way to deflect the flow towards an specific direction (flowDir). Alternatively add an extra pressure drop in the flowDir direction using a model.
Usage
Minimal example by using constant/fvOptions:
directionalPressureGradientExplicitSource1
{
    // Mandatory entries (unmodifiable)
    type            directionalPressureGradientExplicitSource;
    // Mandatory entries (unmodifiable)
    model       <modelName>;
    fields      (<fieldName>);
    // Mandatory entries (runtime modifiable)
    flowDir     (1 1 0);
    faceZone    <faceZoneName>;
    // Conditional mandatory entries (unmodifiable)
        // when <timePath>/uniform/<name>Properties file exists
        gradient    <vectorField>; // reading from the aforementioned file
        // when model=DarcyForchheimer
        // deltaP = (D*mu + 0.5*rho*magUn)*magUn*length
        D           5e7;
        I           0;
        length      1e-3;
        // when model=constant
        pressureDrop    40;
        // when model=volumetricFlowRateTable
        outOfBounds     clamp;
        fileName        "volFlowRateTable";
    // Optional entries (runtime modifiable)
    relaxationFactor    0.3;
    // Mandatory/Optional (inherited) entries
    ...
}
where the entries mean:
Property Description Type Reqd Dflt
type
Type name: directionalPressureGradientExplicitSource
word yes -
model Pressure drop model [Pa] word yes -
fields Name of operand field word yes -
gradient Initial pressure gradient field vectorField cndtnl -
flowDir Deflection flow direction vector yes -
faceZone Name of upstream faceZone word yes -
relaxationFactor Relaxation factor for flow deflection scalar no 0.3
D Darcy pressure loss coefficient scalar cndtnl -
I Inertia pressure lost coefficient scalar cndtnl -
length Porous media length scalar cndtnl -
presssureDrop Constant pressure drop scalar cndtnl -
fileName
Interpolation table for volumetric flow rate
interpolationTable cndtnl -
Options for the model entry:
      volumetricFlowRateTable | Pressure-gradient file
      constant                | Constant pressure drop
      DarcyForchheimer        | Darcy-Forchheimer model
The inherited entries are elaborated in:
fvOption.H
cellSetOption.H
Note
In order to obtain the upwind velocities this function loops over the slaves cells of the faceZone specified in the dictionary, on the other hand, the cellZone to which this source term is applied should be composed of the master cells and they should be 'downwind' the faceZone.
Source files
directionalPressureGradientExplicitSource.H
directionalPressureGradientExplicitSource.C
Definition at line 218 of file directionalPressureGradientExplicitSource.H.
Member Enumeration Documentation
pressureDropModel
enum pressureDropModel
Enumerator
pVolumetricFlowRateTable
pConstant
pDarcyForchheimer
Definition at line 227 of file directionalPressureGradientExplicitSource.H.
Constructor & Destructor Documentation
directionalPressureGradientExplicitSource() [1/2]
directionalPressureGradientExplicitSource (const word & sourceName, const word & modelType, const dictionary & dict, const fvMesh & mesh)
Definition at line 155 of file directionalPressureGradientExplicitSource.C.
References option::coeffs_, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, option::fieldNames_, fv(), Foam::Info, option::mesh_, option::name(), option::name_, Foam::nl, Vector< Cmpt >::normalise(), directionalPressureGradientExplicitSource::pConstant, directionalPressureGradientExplicitSource::pDarcyForchheimer, propsDict(), directionalPressureGradientExplicitSource::pVolumetricFlowRateTable, dictionary::readEntry(), option::resetApplied(), UList< T >::size(), and Foam::type().
directionalPressureGradientExplicitSource() [2/2]
directionalPressureGradientExplicitSource (const directionalPressureGradientExplicitSource &) delete
~directionalPressureGradientExplicitSource()
virtual ~directionalPressureGradientExplicitSource () virtual default
Member Function Documentation
TypeName()
TypeName ("directionalPressureGradientExplicitSource")
operator=()
void operator= (const directionalPressureGradientExplicitSource &) delete
correct()
void correct (volVectorField & U) virtual
Reimplemented from option.
Definition at line 249 of file directionalPressureGradientExplicitSource.C.
References cellId, D, Foam::dimTime, Foam::dimVolume, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::gSum(), Foam::gSumProd(), Foam::Info, Foam::mag(), mesh, mu, nu, pbm, phi, turbulenceModel::propertiesName, rAU, Foam::reduce(), rho, Foam::rotationTensor(), PtrList< T >::set(), UPtrList< T >::size(), U, and Foam::Zero.
addSup() [1/2]
void addSup (fvMatrix< vector > & eqn, const label fieldI) virtual
Reimplemented from option.
Definition at line 453 of file directionalPressureGradientExplicitSource.C.
References Foam::dimVolume, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, Su, and Foam::Zero.
addSup() [2/2]
void addSup (const volScalarField & rho, fvMatrix< vector > & eqn, const label fieldI) virtual
Reimplemented from option.
Definition at line 479 of file directionalPressureGradientExplicitSource.C.
constrain()
void constrain (fvMatrix< vector > & eqn, const label fieldI) virtual
Reimplemented from option.
Definition at line 490 of file directionalPressureGradientExplicitSource.C.
References IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, and Foam::Zero.
writeData()
void writeData (Ostream & os) const virtual
Reimplemented from option.
Definition at line 524 of file directionalPressureGradientExplicitSource.C.
References NotImplemented.
read()
bool read (const dictionary & dict) virtual
Reimplemented from cellSetOption.
Definition at line 533 of file directionalPressureGradientExplicitSource.C.
References dict, dictionary::getOrDefault(), and dictionary::readEntry().
The documentation for this class was generated from the following files:
src/fvOptions/sources/derived/directionalPressureGradientExplicitSource/directionalPressureGradientExplicitSource.H
src/fvOptions/sources/derived/directionalPressureGradientExplicitSource/directionalPressureGradientExplicitSource.C