OpenFOAM: nonEquilibrium Class Reference
nonEquilibrium Class Reference
Lagrangian particle models » Submodels » MP-PIC » Time scale
Non-Equlibrium model for the time scale over which properties of a dispersed phase tend towards the mean value.
#include <nonEquilibrium.H>
Public Member Functions
TypeName ("nonEquilibrium")
nonEquilibrium (const dictionary &dict)
nonEquilibrium (const nonEquilibrium &hc)
virtual autoPtr< TimeScaleModel > clone () const
virtual ~nonEquilibrium ()
tmp< FieldField< Field, scalar > > oneByTau (const FieldField< Field, scalar > &alpha, const FieldField< Field, scalar > &r32, const FieldField< Field, scalar > &uSqr, const FieldField< Field, scalar > &f) const
Public Member Functions inherited from TimeScaleModel
TypeName ("timeScaleModel")
declareRunTimeSelectionTable (autoPtr, TimeScaleModel, dictionary,(const dictionary &dict),(dict))
TimeScaleModel (const dictionary &dict)
TimeScaleModel (const TimeScaleModel &sm)
virtual ~TimeScaleModel ()
Additional Inherited Members
Static Public Member Functions inherited from TimeScaleModel
static autoPtr< TimeScaleModel > New (const dictionary &dict)
Protected Attributes inherited from TimeScaleModel
scalar alphaPacked_
scalar e_
Detailed Description
Non-Equlibrium model for the time scale over which properties of a dispersed phase tend towards the mean value.
Reference:
    "An improved collision damping time for MP-PIC calculations of dense
    particle flows with applications to polydisperse sedimenting beds and
    colliding particle jets"
    P O'Rourke and D Snider
    Chemical Engineering Science
    Volume 65, Issue 22, Pages 6014-6028, November 2010
Source files
nonEquilibrium.H
nonEquilibrium.C
Definition at line 62 of file nonEquilibrium.H.
Constructor & Destructor Documentation
nonEquilibrium() [1/2]
nonEquilibrium (const dictionary & dict)
Definition at line 44 of file nonEquilibrium.C.
nonEquilibrium() [2/2]
nonEquilibrium (const nonEquilibrium & hc)
Definition at line 53 of file nonEquilibrium.C.
~nonEquilibrium()
~nonEquilibrium () virtual
Definition at line 64 of file nonEquilibrium.C.
Member Function Documentation
TypeName()
TypeName ("nonEquilibrium")
clone()
virtual autoPtr< TimeScaleModel > clone () const inline virtual
Implements TimeScaleModel.
Definition at line 81 of file nonEquilibrium.H.
oneByTau()
Foam::tmp< Foam::FieldField< Foam::Field, Foam::scalar > > oneByTau (const FieldField< Field, scalar > & alpha, const FieldField< Field, scalar > & r32, const FieldField< Field, scalar > & uSqr, const FieldField< Field, scalar > & f) const virtual
Implements TimeScaleModel.
Definition at line 71 of file nonEquilibrium.C.
References alpha, f(), Foam::max(), Foam::constant::mathematical::pi(), and Foam::sqrt().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/MPPIC/TimeScaleModels/nonEquilibrium/nonEquilibrium.H
src/lagrangian/intermediate/submodels/MPPIC/TimeScaleModels/nonEquilibrium/nonEquilibrium.C