OpenFOAM: constantFilmThermo Class Reference
constantFilmThermo Class Reference
Constant thermo model.
#include <constantFilmThermo.H>
Classes
struct thermoData
Public Member Functions
TypeName ("constant")
constantFilmThermo (surfaceFilmRegionModel &film, const dictionary &dict)
virtual ~constantFilmThermo ()
virtual const word & name () const
virtual scalar rho (const scalar p, const scalar T) const
virtual scalar mu (const scalar p, const scalar T) const
virtual scalar sigma (const scalar p, const scalar T) const
virtual scalar Cp (const scalar p, const scalar T) const
virtual scalar kappa (const scalar p, const scalar T) const
virtual scalar D (const scalar p, const scalar T) const
virtual scalar hl (const scalar p, const scalar T) const
virtual scalar pv (const scalar p, const scalar T) const
virtual scalar W () const
virtual scalar Tb (const scalar p) const
virtual tmp< volScalarField > rho () const
virtual tmp< volScalarField > mu () const
virtual tmp< volScalarField > sigma () const
virtual tmp< volScalarField > Cp () const
virtual tmp< volScalarField > kappa () const
Public Member Functions inherited from filmThermoModel
TypeName ("filmThermoModel")
declareRunTimeSelectionTable (autoPtr, filmThermoModel, dictionary,(surfaceFilmRegionModel &film, const dictionary &dict),(film, dict))
filmThermoModel (surfaceFilmRegionModel &film)
filmThermoModel (const word &modelType, surfaceFilmRegionModel &film, const dictionary &dict)
virtual ~filmThermoModel ()
Public Member Functions inherited from filmSubModelBase
filmSubModelBase (surfaceFilmRegionModel &film)
filmSubModelBase (surfaceFilmRegionModel &film, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
filmSubModelBase (const word &modelName, surfaceFilmRegionModel &film, const dictionary &dict, const word &baseName, const word &modelType)
virtual ~filmSubModelBase ()
virtual bool writeTime () const
const surfaceFilmRegionModel & film () const
surfaceFilmRegionModel & film ()
template<class FilmType >
const FilmType & filmType () const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
subModelBase (const subModelBase &smb)
virtual ~subModelBase ()=default
const word & modelName () const
const dictionary & dict () const
const word & baseName () const
const word & modelType () const
const dictionary & coeffDict () const
const dictionary & properties () const
virtual bool defaultCoeffs (const bool printMsg) const
virtual bool active () const
virtual void cacheFields (const bool store)
virtual fileName localPath () const
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
bool getModelDict (const word &entryName, dictionary &dict) const
template<class Type >
bool getModelProperty (const word &entryName, Type &value) const
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
virtual void write (Ostream &os) const
Additional Inherited Members
Static Public Member Functions inherited from filmThermoModel
static autoPtr< filmThermoModel > New (surfaceFilmRegionModel &film, const dictionary &dict)
Public Attributes inherited from subModelBase
bool log
Protected Member Functions inherited from subModelBase
bool inLine () const
Protected Attributes inherited from filmSubModelBase
surfaceFilmRegionModel & filmModel_
Protected Attributes inherited from subModelBase
const word modelName_
dictionary & properties_
const dictionary dict_
const word baseName_
const word modelType_
const dictionary coeffDict_
Detailed Description
Constant thermo model.
Source files
constantFilmThermo.H
constantFilmThermo.C
Definition at line 51 of file constantFilmThermo.H.
Constructor & Destructor Documentation
constantFilmThermo()
constantFilmThermo (surfaceFilmRegionModel & film, const dictionary & dict)
Definition at line 57 of file constantFilmThermo.C.
~constantFilmThermo()
~constantFilmThermo () virtual
Definition at line 91 of file constantFilmThermo.C.
Member Function Documentation
TypeName()
TypeName ("constant")
name()
const word & name () const virtual
Implements filmThermoModel.
Definition at line 97 of file constantFilmThermo.C.
rho() [1/2]
scalar rho (const scalar p, const scalar T) const virtual
Implements filmThermoModel.
Definition at line 103 of file constantFilmThermo.C.
References subModelBase::coeffDict_, constantFilmThermo::thermoData::name_, constantFilmThermo::thermoData::set_, and constantFilmThermo::thermoData::value_.
mu() [1/2]
scalar mu (const scalar p, const scalar T) const virtual
Implements filmThermoModel.
Definition at line 119 of file constantFilmThermo.C.
References subModelBase::coeffDict_, constantFilmThermo::thermoData::name_, constantFilmThermo::thermoData::set_, and constantFilmThermo::thermoData::value_.
sigma() [1/2]
scalar sigma (const scalar p, const scalar T) const virtual
Implements filmThermoModel.
Definition at line 135 of file constantFilmThermo.C.
References subModelBase::coeffDict_, constantFilmThermo::thermoData::name_, constantFilmThermo::thermoData::set_, and constantFilmThermo::thermoData::value_.
Cp() [1/2]
scalar Cp (const scalar p, const scalar T) const virtual
Implements filmThermoModel.
Definition at line 151 of file constantFilmThermo.C.
References subModelBase::coeffDict_, constantFilmThermo::thermoData::name_, constantFilmThermo::thermoData::set_, and constantFilmThermo::thermoData::value_.
kappa() [1/2]
scalar kappa (const scalar p, const scalar T) const virtual
Implements filmThermoModel.
Definition at line 167 of file constantFilmThermo.C.
References subModelBase::coeffDict_, constantFilmThermo::thermoData::name_, constantFilmThermo::thermoData::set_, and constantFilmThermo::thermoData::value_.
D()
scalar D (const scalar p, const scalar T) const virtual
Implements filmThermoModel.
Definition at line 183 of file constantFilmThermo.C.
References subModelBase::coeffDict_, constantFilmThermo::thermoData::name_, constantFilmThermo::thermoData::set_, and constantFilmThermo::thermoData::value_.
hl()
scalar hl (const scalar p, const scalar T) const virtual
Implements filmThermoModel.
Definition at line 199 of file constantFilmThermo.C.
References subModelBase::coeffDict_, constantFilmThermo::thermoData::name_, constantFilmThermo::thermoData::set_, and constantFilmThermo::thermoData::value_.
pv()
scalar pv (const scalar p, const scalar T) const virtual
Implements filmThermoModel.
Definition at line 215 of file constantFilmThermo.C.
References subModelBase::coeffDict_, constantFilmThermo::thermoData::name_, constantFilmThermo::thermoData::set_, and constantFilmThermo::thermoData::value_.
W()
scalar W () const virtual
Implements filmThermoModel.
Definition at line 231 of file constantFilmThermo.C.
References subModelBase::coeffDict_, constantFilmThermo::thermoData::name_, constantFilmThermo::thermoData::set_, and constantFilmThermo::thermoData::value_.
Tb()
scalar Tb (const scalar p) const virtual
Implements filmThermoModel.
Definition at line 243 of file constantFilmThermo.C.
References subModelBase::coeffDict_, constantFilmThermo::thermoData::name_, constantFilmThermo::thermoData::set_, and constantFilmThermo::thermoData::value_.
rho() [2/2]
tmp< volScalarField > rho () const virtual
Implements filmThermoModel.
Definition at line 255 of file constantFilmThermo.C.
References Foam::dimDensity, fvPatchFieldBase::extrapolatedCalculatedType(), filmSubModelBase::film(), constantFilmThermo::thermoData::name_, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, constantFilmThermo::rho(), timeName, trho, Foam::type(), and Foam::Zero.
Referenced by constantFilmThermo::rho().
mu() [2/2]
tmp< volScalarField > mu () const virtual
Implements filmThermoModel.
Definition at line 282 of file constantFilmThermo.C.
References Foam::dimPressure, Foam::dimTime, filmSubModelBase::film(), constantFilmThermo::mu(), constantFilmThermo::thermoData::name_, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, timeName, Foam::type(), and Foam::Zero.
Referenced by constantFilmThermo::mu().
sigma() [2/2]
tmp< volScalarField > sigma () const virtual
Implements filmThermoModel.
Definition at line 309 of file constantFilmThermo.C.
References Foam::dimMass, Foam::dimTime, filmSubModelBase::film(), constantFilmThermo::thermoData::name_, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, constantFilmThermo::sigma(), Foam::sqr(), timeName, Foam::type(), and Foam::Zero.
Referenced by constantFilmThermo::sigma().
Cp() [2/2]
tmp< volScalarField > Cp () const virtual
Implements filmThermoModel.
Definition at line 336 of file constantFilmThermo.C.
References constantFilmThermo::Cp(), Foam::dimEnergy, Foam::dimMass, Foam::dimTemperature, filmSubModelBase::film(), constantFilmThermo::thermoData::name_, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, tCp, timeName, Foam::type(), and Foam::Zero.
Referenced by constantFilmThermo::Cp().
kappa() [2/2]
tmp< volScalarField > kappa () const virtual
Implements filmThermoModel.
Definition at line 363 of file constantFilmThermo.C.
References Foam::dimLength, Foam::dimPower, Foam::dimTemperature, filmSubModelBase::film(), constantFilmThermo::kappa(), constantFilmThermo::thermoData::name_, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, timeName, Foam::type(), and Foam::Zero.
Referenced by constantFilmThermo::kappa().
The documentation for this class was generated from the following files:
src/regionModels/surfaceFilmModels/submodels/kinematic/filmThermoModel/constantFilmThermo/constantFilmThermo.H
src/regionModels/surfaceFilmModels/submodels/kinematic/filmThermoModel/constantFilmThermo/constantFilmThermo.C