OpenFOAM: specie Class Reference
specie Class Reference
Base class of the thermophysical property types.
#include <specie.H>
Public Member Functions
ClassName ("specie")
specie (const specie &)=default
specie (const scalar Y, const scalar molWeight)
specie (const word &name, const scalar Y, const scalar molWeight)
specie (const word &name, const specie &)
specie (const dictionary &dict)
const word & name () const
scalar W () const
scalar Y () const
scalar R () const
void write (Ostream &os) const
void operator= (const specie &)
void operator+= (const specie &)
void operator*= (const scalar)
Friends
specie operator+ (const specie &, const specie &)
specie operator* (const scalar, const specie &)
specie operator== (const specie &, const specie &)
Ostream & operator<< (Ostream &, const specie &)
Detailed Description
Base class of the thermophysical property types.
Source files
specie.H
specieI.H
specie.C
Definition at line 63 of file specie.H.
Constructor & Destructor Documentation
specie() [1/5]
specie (const specie &) default
specie() [2/5]
specie (const scalar Y, const scalar molWeight) inline
Definition at line 39 of file specieI.H.
specie() [3/5]
specie (const word & name, const scalar Y, const scalar molWeight) inline
Definition at line 26 of file specieI.H.
References Foam::name().
specie() [4/5]
specie (const word & name, const specie & st) inline
Definition at line 52 of file specieI.H.
specie() [5/5]
specie (const dictionary & dict) explicit
Definition at line 35 of file specie.C.
Member Function Documentation
ClassName()
ClassName ("specie")
name()
const Foam::word & name () const inline
Definition at line 62 of file specieI.H.
Referenced by sutherlandTransport< Thermo >::write(), and WLFTransport< Thermo >::write().
W()
Foam::scalar W () const inline
Definition at line 68 of file specieI.H.
Y()
Foam::scalar Y () const inline
Definition at line 74 of file specieI.H.
R()
Foam::scalar R () const inline
Definition at line 80 of file specieI.H.
References Foam::constant::thermodynamic::RR.
write()
void write (Ostream & os) const
Definition at line 45 of file specie.C.
References Ostream::beginBlock(), Ostream::endBlock(), os(), Ostream::writeEntry(), and Ostream::writeEntryIfDifferent().
operator=()
void operator= (const specie & st) inline
Definition at line 88 of file specieI.H.
operator+=()
void operator+= (const specie & st) inline
Definition at line 96 of file specieI.H.
References Foam::mag().
operator*=()
void operator*= (const scalar s) inline
Definition at line 108 of file specieI.H.
References s().
Friends And Related Symbol Documentation
operator+
specie operator+ (const specie & , const specie &) friend
operator*
specie operator* (const scalar , const specie &) friend
operator==
specie operator== (const specie & , const specie &) friend
operator<<
Ostream & operator<< (Ostream & , const specie &) friend
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/specie/specie.H
src/thermophysicalModels/specie/specie/specie.C
src/thermophysicalModels/specie/specie/specieI.H