OpenFOAM: Random Class Reference
Random Class Reference
Random number generator.
#include <Random.H>
Classes
class gaussianGeneratorOp
class uniformGeneratorOp
Public Member Functions
Random (const label seedValue=defaultSeed)
Random (const Random &rnd, const bool reset)
label seed () const
void reset (const label seedValue)
int bit ()
template<class Type >
Type sample01 ()
template<class Type >
Type GaussNormal ()
template<class Type >
Type position (const Type &start, const Type &end)
template<class Type >
void randomise01 (Type &value)
template<class Type >
void shuffle (UList< Type > &values)
template<class Type >
Type globalSample01 ()
template<class Type >
Type globalGaussNormal ()
template<class Type >
Type globalPosition (const Type &start, const Type &end)
template<class Type >
void globalRandomise01 (Type &value)
template<>
Foam::scalar sample01 ()
template<>
Foam::label sample01 ()
template<>
Foam::scalar GaussNormal ()
template<>
Foam::label GaussNormal ()
template<>
Foam::scalar position (const scalar &start, const scalar &end)
template<>
Foam::label position (const label &start, const label &end)
template<>
Foam::scalar globalSample01 ()
template<>
Foam::label globalSample01 ()
template<>
Foam::scalar globalGaussNormal ()
template<>
Foam::label globalGaussNormal ()
template<>
Foam::scalar globalPosition (const scalar &start, const scalar &end)
template<>
Foam::label globalPosition (const label &start, const label &end)
template<>
scalar sample01 ()
template<>
label sample01 ()
template<>
scalar GaussNormal ()
template<>
label GaussNormal ()
template<>
scalar position (const scalar &start, const scalar &end)
template<>
label position (const label &start, const label &end)
template<>
scalar globalSample01 ()
template<>
label globalSample01 ()
template<>
scalar globalGaussNormal ()
template<>
label globalGaussNormal ()
template<>
scalar globalPosition (const scalar &start, const scalar &end)
template<>
label globalPosition (const label &start, const label &end)
Static Public Attributes
static constexpr label defaultSeed = 123456
Detailed Description
Random number generator.
Source files
Random.H
RandomI.H
Random.C
RandomTemplates.C
Definition at line 55 of file Random.H.
Constructor & Destructor Documentation
Random() [1/2]
Random (const label seedValue = defaultSeed) explicit
Definition at line 26 of file Random.C.
Random() [2/2]
Random (const Random & rnd, const bool reset)
Definition at line 36 of file Random.C.
References Random::reset(), and Rand48::seed().
Member Function Documentation
seed()
Foam::label seed () const inline
Definition at line 37 of file RandomI.H.
reset()
void reset (const label seedValue) inline
Definition at line 43 of file RandomI.H.
Referenced by Random::Random().
bit()
int bit () inline
Definition at line 31 of file RandomI.H.
sample01() [1/5]
template<class Type > Type sample01 ()
Definition at line 28 of file RandomTemplates.C.
Referenced by LarsenBorgnakkeVariableHardSphere< CloudType >::collide(), VariableHardSphere< CloudType >::collide(), MaxwellianThermal< CloudType >::correct(), MixedDiffuseSpecular< CloudType >::correct(), DSMCCloud< ParcelType >::DSMCCloud(), boundBox::inflate(), FreeStream< CloudType >::inflow(), ConeNozzleInjection< CloudType >::setProperties(), and SHF< CloudType >::update().
GaussNormal() [1/5]
template<class Type > Type GaussNormal ()
Definition at line 41 of file RandomTemplates.C.
Referenced by MaxwellianThermal< CloudType >::correct(), MixedDiffuseSpecular< CloudType >::correct(), and FreeStream< CloudType >::inflow().
position() [1/5]
template<class Type > Type position (const Type & start, const Type & end)
Definition at line 54 of file RandomTemplates.C.
Referenced by randomRenumber::renumber().
randomise01()
template<class Type > void randomise01 (Type & value)
Definition at line 68 of file RandomTemplates.C.
shuffle()
template<class Type > void shuffle (UList< Type > & values)
Definition at line 75 of file RandomTemplates.C.
References Foam::Swap().
globalSample01() [1/5]
template<class Type > Type globalSample01 ()
Definition at line 86 of file RandomTemplates.C.
References Pstream::broadcast(), UPstream::master(), and Foam::Zero.
Referenced by ConeNozzleInjection< CloudType >::setPositionAndCell().
globalGaussNormal() [1/5]
template<class Type > Type globalGaussNormal ()
Definition at line 102 of file RandomTemplates.C.
References Pstream::broadcast(), UPstream::master(), and Foam::Zero.
globalPosition() [1/5]
template<class Type > Type globalPosition (const Type & start, const Type & end)
Definition at line 118 of file RandomTemplates.C.
References Pstream::broadcast(), UPstream::master(), and Foam::Zero.
globalRandomise01()
template<class Type > void globalRandomise01 (Type & value)
Definition at line 134 of file RandomTemplates.C.
References Pstream::broadcast(), and UPstream::master().
sample01() [2/5]
template<> Foam::scalar sample01 ()
Definition at line 52 of file Random.C.
sample01() [3/5]
template<> Foam::label sample01 ()
Definition at line 59 of file Random.C.
GaussNormal() [2/5]
template<> Foam::scalar GaussNormal ()
Definition at line 66 of file Random.C.
References Foam::log(), Foam::sqr(), and Foam::sqrt().
GaussNormal() [3/5]
template<> Foam::label GaussNormal ()
Definition at line 95 of file Random.C.
position() [2/5]
template<> Foam::scalar position (const scalar & start, const scalar & end)
Definition at line 102 of file Random.C.
position() [3/5]
template<> Foam::label position (const label & start, const label & end)
Definition at line 113 of file Random.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, Foam::min(), and Foam::nl.
globalSample01() [2/5]
template<> Foam::scalar globalSample01 ()
Definition at line 137 of file Random.C.
References Pstream::broadcast(), and UPstream::master().
globalSample01() [3/5]
template<> Foam::label globalSample01 ()
Definition at line 153 of file Random.C.
References Pstream::broadcast(), and UPstream::master().
globalGaussNormal() [2/5]
template<> Foam::scalar globalGaussNormal ()
Definition at line 169 of file Random.C.
References Pstream::broadcast(), and UPstream::master().
globalGaussNormal() [3/5]
template<> Foam::label globalGaussNormal ()
Definition at line 185 of file Random.C.
References Pstream::broadcast(), and UPstream::master().
globalPosition() [2/5]
template<> Foam::scalar globalPosition (const scalar & start, const scalar & end)
Definition at line 201 of file Random.C.
References Pstream::broadcast(), and UPstream::master().
globalPosition() [3/5]
template<> Foam::label globalPosition (const label & start, const label & end)
Definition at line 221 of file Random.C.
References Pstream::broadcast(), and UPstream::master().
sample01() [4/5]
template<> scalar sample01 ()
sample01() [5/5]
template<> label sample01 ()
GaussNormal() [4/5]
template<> scalar GaussNormal ()
GaussNormal() [5/5]
template<> label GaussNormal ()
position() [4/5]
template<> scalar position (const scalar & start, const scalar & end)
position() [5/5]
template<> label position (const label & start, const label & end)
globalSample01() [4/5]
template<> scalar globalSample01 ()
globalSample01() [5/5]
template<> label globalSample01 ()
globalGaussNormal() [4/5]
template<> scalar globalGaussNormal ()
globalGaussNormal() [5/5]
template<> label globalGaussNormal ()
globalPosition() [4/5]
template<> scalar globalPosition (const scalar & start, const scalar & end)
globalPosition() [5/5]
template<> label globalPosition (const label & start, const label & end)
Member Data Documentation
defaultSeed
constexpr label defaultSeed = 123456 static constexpr
Definition at line 91 of file Random.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/random/Random/Random.H
src/OpenFOAM/primitives/random/Random/Random.C
src/OpenFOAM/primitives/random/Random/RandomI.H
src/OpenFOAM/primitives/random/Random/RandomTemplates.C