OpenFOAM: IOmapDistribute Class Reference
IOmapDistribute Class Reference
IOmapDistribute is derived from mapDistribute and IOobject to give the mapDistribute automatic IO functionality via the objectRegistry.
#include <IOmapDistribute.H>
Public Member Functions
TypeName ("mapDistribute")
IOmapDistribute (const IOobject &io)
IOmapDistribute (const IOobject &io, const mapDistribute &map)
IOmapDistribute (const IOobject &io, mapDistribute &&map)
virtual ~IOmapDistribute ()=default
virtual bool readData (Istream &)
virtual bool writeData (Ostream &) const
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
regIOobject (const IOobject &io, const bool isTimeObject=false)
regIOobject (const regIOobject &rio)
regIOobject (const regIOobject &rio, bool registerCopy)
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
regIOobject (const IOobject &io, const regIOobject &rio)
virtual ~regIOobject ()
bool checkIn ()
bool checkOut ()
virtual void addWatch ()
bool registered () const noexcept
bool ownedByRegistry () const noexcept
bool store ()
void release (const bool unregister=false) noexcept
label eventNo () const noexcept
label & eventNo () noexcept
bool upToDate (const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
void setUpToDate ()
virtual void rename (const word &newName)
const dictionary * findMetaData () const noexcept
dictionary & getMetaData () noexcept
void removeMetaData ()
virtual void updateMetaData ()
virtual fileName filePath () const
bool headerOk ()
Istream & readStream (const word &, const bool readOnProc=true)
void close ()
virtual bool read ()
virtual label addWatch (const fileName &)
const labelList & watchIndices () const noexcept
labelList & watchIndices () noexcept
virtual bool modified () const
virtual bool readIfModified ()
virtual bool writeObject (IOstreamOption streamOpt, const bool writeOnProc) const
virtual bool write (const bool writeOnProc=true) const
virtual bool global () const
void operator= (const IOobject &io)
virtual bool writeObject (IOstreamOption::streamFormat fmt, IOstreamOption::versionNumber ver, IOstreamOption::compressionType cmp, const bool writeOnProc) const
Public Member Functions inherited from IOobject
TypeName ("IOobject")
IOobject (const IOobject &)=default
virtual ~IOobject ()=default
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const fileName &path, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const fileName &path, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const IOobject &io, const objectRegistry &registry)
IOobject (const IOobject &io, const word &name)
IOobject (const IOobject &io, const word &name, const fileName &local)
IOobject (const IOobject &io, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt)
IOobject (const IOobject &io, IOobjectOption::registerOption regOpt)
autoPtr< IOobject > clone () const
autoPtr< IOobject > clone (const objectRegistry &registry) const
const objectRegistry & db () const noexcept
const Time & time () const noexcept
const word & name () const noexcept
const word & headerClassName () const noexcept
word & headerClassName () noexcept
const string & note () const noexcept
string & note () noexcept
unsigned labelByteSize () const noexcept
unsigned scalarByteSize () const noexcept
void resetHeader (const word &newName=word::null)
bool hasHeaderClass () const noexcept
template<class Type >
bool isHeaderClass () const
template<class Type >
bool isHeaderClassName () const
word group () const
word member () const
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const noexcept
fileName & instance () noexcept
const fileName & local () const noexcept
fileName path () const
fileName path (const word &instance, const fileName &local=fileName::null) const
fileName objectPath () const
fileName objectRelPath () const
fileName localFilePath (const word &typeName, const bool search=true) const
fileName globalFilePath (const word &typeName, const bool search=true) const
IOstreamOption parseHeader (const dictionary &headerDict)
bool readHeader (Istream &is)
bool readHeader (dictionary &headerDict, Istream &is)
template<class Type >
bool typeHeaderOk (const bool checkType=true, const bool search=true, const bool verbose=true)
template<class Type >
void warnNoRereading () const
bool writeHeader (Ostream &os) const
bool writeHeader (Ostream &os, const word &objectType) const
void writeHeader (dictionary &dict, IOstreamOption streamOpt) const
void writeHeader (dictionary &dict, const word &objectType, IOstreamOption streamOpt) const
bool good () const noexcept
bool bad () const noexcept
InfoProxy< IOobject > info () const noexcept
void operator= (const IOobject &io)
template<>
bool isHeaderClass () const
template<class StringType >
Foam::word groupName (StringType base, const word &group)
Public Member Functions inherited from IOobjectOption
constexpr IOobjectOption (readOption rOpt=readOption::NO_READ, writeOption wOpt=writeOption::NO_WRITE, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (readOption rOpt, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (writeOption wOpt, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (registerOption registerObject, bool globalObject=false) noexcept
constexpr IOobjectOption (readOption rOpt, writeOption wOpt, bool registerObject, bool globalObject=false) noexcept
constexpr IOobjectOption (bool registerObject, bool globalObject=false) noexcept
readOption readOpt () const noexcept
readOption readOpt (readOption opt) noexcept
writeOption writeOpt () const noexcept
writeOption writeOpt (writeOption opt) noexcept
bool registerObject () const noexcept
bool registerObject (bool on) noexcept
bool globalObject () const noexcept
bool globalObject (bool on) noexcept
bool isAnyRead () const noexcept
bool isReadRequired () const noexcept
bool isReadOptional () const noexcept
readOption & readOpt () noexcept
writeOption & writeOpt () noexcept
bool & registerObject () noexcept
bool & globalObject () noexcept
Public Member Functions inherited from mapDistribute
ClassName ("mapDistribute")
mapDistribute ()
mapDistribute (const label comm)
mapDistribute (mapDistributeBase &&map)
mapDistribute (const mapDistribute &map)
mapDistribute (mapDistribute &&map)
mapDistribute (const dictionary &dict, const label comm=UPstream::worldComm)
mapDistribute (const label constructSize, labelListList &&subMap, labelListList &&constructMap, labelListList &&transformElements, labelList &&transformStart, const bool subHasFlip=false, const bool constructHasFlip=false, const label comm=UPstream::worldComm)
mapDistribute (const globalIndex &, labelList &untransformedElements, const globalIndexAndTransform &, const labelPairList &transformedElements, labelList &transformedIndices, List< Map< label > > &compactMap, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm)
mapDistribute (const globalIndex &, labelListList &cellCells, const globalIndexAndTransform &, const List< labelPairList > &transformedElements, labelListList &transformedIndices, List< Map< label > > &compactMap, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm)
mapDistribute (Istream &is)
autoPtr< mapDistribute > clone () const
virtual ~mapDistribute ()=default
const labelListList & transformElements () const noexcept
const labelList & transformStart () const noexcept
label whichTransform (const label index) const
void clear ()
void transfer (mapDistribute &map)
template<class T >
void distribute (List< T > &fld, const bool dummyTransform=true, const int tag=UPstream::msgType()) const
template<class T , class NegateOp >
void distribute (List< T > &fld, const NegateOp &negOp, const bool dummyTransform=true, const int tag=UPstream::msgType()) const
template<class T >
void distribute (DynamicList< T > &fld, const bool dummyTransform=true, const int tag=UPstream::msgType()) const
template<class T >
void reverseDistribute (const label constructSize, List< T > &fld, const bool dummyTransform=true, const int tag=UPstream::msgType()) const
template<class T >
void reverseDistribute (const label constructSize, const T &nullValue, List< T > &fld, const bool dummyTransform=true, const int tag=UPstream::msgType()) const
template<class T , class TransformOp >
void distribute (const globalIndexAndTransform &, List< T > &fld, const TransformOp &top, const int tag=UPstream::msgType()) const
template<class T , class TransformOp >
void reverseDistribute (const globalIndexAndTransform &, const label constructSize, List< T > &fld, const TransformOp &top, const int tag=UPstream::msgType()) const
template<class T , class TransformOp >
void reverseDistribute (const globalIndexAndTransform &, const label constructSize, const T &nullValue, List< T > &fld, const TransformOp &top, const int tag=UPstream::msgType()) const
void printLayout (Ostream &os) const
void operator= (const mapDistribute &rhs)
void operator= (mapDistribute &&rhs)
void readDict (const dictionary &dict)
void writeEntries (Ostream &os) const
void updateMesh (const mapPolyMesh &)
mapDistributeBase ()
mapDistributeBase (const label comm)
mapDistributeBase (const mapDistributeBase &map)
mapDistributeBase (mapDistributeBase &&map)
mapDistributeBase (const dictionary &dict, const label comm=UPstream::worldComm)
mapDistributeBase (const label constructSize, labelListList &&subMap, labelListList &&constructMap, const bool subHasFlip=false, const bool constructHasFlip=false, const label comm=UPstream::worldComm)
mapDistributeBase (const labelUList &sendProcs, const labelUList &recvProcs, const label comm=UPstream::worldComm)
mapDistributeBase (const globalIndex &, labelList &elements, List< Map< label > > &compactMap, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm)
mapDistributeBase (const globalIndex &, labelListList &cellCells, List< Map< label > > &compactMap, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm)
mapDistributeBase (labelListList &&subMap, const bool subHasFlip=false, const bool constructHasFlip=false, const label comm=UPstream::worldComm)
mapDistributeBase (Istream &is)
Public Member Functions inherited from mapDistributeBase
ClassName ("mapDistributeBase")
mapDistributeBase ()
mapDistributeBase (const label comm)
mapDistributeBase (const mapDistributeBase &map)
mapDistributeBase (mapDistributeBase &&map)
mapDistributeBase (const dictionary &dict, const label comm=UPstream::worldComm)
mapDistributeBase (const label constructSize, labelListList &&subMap, labelListList &&constructMap, const bool subHasFlip=false, const bool constructHasFlip=false, const label comm=UPstream::worldComm)
mapDistributeBase (const labelUList &sendProcs, const labelUList &recvProcs, const label comm=UPstream::worldComm)
mapDistributeBase (const globalIndex &, labelList &elements, List< Map< label > > &compactMap, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm)
mapDistributeBase (const globalIndex &, labelListList &cellCells, List< Map< label > > &compactMap, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm)
mapDistributeBase (labelListList &&subMap, const bool subHasFlip=false, const bool constructHasFlip=false, const label comm=UPstream::worldComm)
mapDistributeBase (Istream &is)
label constructSize () const noexcept
label & constructSize () noexcept
const labelListList & subMap () const noexcept
labelListList & subMap () noexcept
const labelListList & constructMap () const noexcept
labelListList & constructMap () noexcept
bool subHasFlip () const noexcept
bool & subHasFlip () noexcept
bool constructHasFlip () const noexcept
bool & constructHasFlip () noexcept
label comm () const noexcept
label nMaps () const noexcept
labelList subMapSizes () const
labelList constructMapSizes () const
const List< labelPair > & schedule () const
const List< labelPair > & whichSchedule (const UPstream::commsTypes commsType) const
void clear ()
void transfer (mapDistributeBase &rhs)
void compactLocalData (const bitSet &allowedLocalElems, const int tag=UPstream::msgType(), const bool doRenumber=false)
void compactRemoteData (const bitSet &allowedRemoteElems, const int tag=UPstream::msgType(), const bool doRenumber=false)
void compactLocalData (const bitSet &allowedLocalElems, labelList &oldToNewSub, labelList &oldToNewConstruct, const label localSize=-1, const int tag=UPstream::msgType())
void compactRemoteData (const bitSet &allowedRemoteElems, labelList &oldToNewSub, labelList &oldToNewConstruct, const label localSize=-1, const int tag=UPstream::msgType())
void compactData (const labelUList &localElements, const labelUList &remoteElements, labelList &oldToNewSub, labelList &oldToNewConstruct, const label localSize=-1, const int tag=UPstream::msgType())
void compactLocalData (const labelUList &localElements, labelList &oldToNewSub, labelList &oldToNewConstruct, const label localSize=-1, const int tag=UPstream::msgType())
void compactRemoteData (const labelUList &remoteElements, labelList &oldToNewSub, labelList &oldToNewConstruct, const label localSize=-1, const int tag=UPstream::msgType())
template<class T >
void distribute (List< T > &values, const int tag=UPstream::msgType()) const
template<class T >
void distribute (DynamicList< T > &values, const int tag=UPstream::msgType()) const
template<class T , class NegateOp >
void distribute (List< T > &values, const NegateOp &negOp, const int tag=UPstream::msgType()) const
template<class T , class NegateOp >
void distribute (const Pstream::commsTypes commsType, List< T > &values, const NegateOp &negOp, const int tag=UPstream::msgType()) const
template<class T , class NegateOp >
void distribute (const Pstream::commsTypes commsType, const T &nullValue, List< T > &values, const NegateOp &negOp, const int tag=UPstream::msgType()) const
template<class T >
void reverseDistribute (const label constructSize, List< T > &values, const int tag=UPstream::msgType()) const
template<class T >
void reverseDistribute (const label constructSize, const T &nullValue, List< T > &values, const int tag=UPstream::msgType()) const
template<class T >
void reverseDistribute (const Pstream::commsTypes commsType, const label constructSize, List< T > &values, const int tag=UPstream::msgType()) const
template<class T , class NegateOp >
void reverseDistribute (const Pstream::commsTypes commsType, const label constructSize, List< T > &values, const NegateOp &negOp, const int tag=UPstream::msgType()) const
template<class T >
void reverseDistribute (const Pstream::commsTypes commsType, const label constructSize, const T &nullValue, List< T > &values, const int tag=UPstream::msgType()) const
template<class T >
void send (PstreamBuffers &pBufs, const List< T > &field) const
template<class T >
void receive (PstreamBuffers &pBufs, List< T > &field) const
template<class T >
void send (const UList< T > &field, labelRange &requests, PtrList< List< T > > &sendFields, PtrList< List< T > > &recvFields, const int tag=UPstream::msgType()) const
template<class T >
void receive (const labelRange &requests, const UPtrList< List< T > > &sendFields, const UPtrList< List< T > > &recvFields, List< T > &field, const int tag=UPstream::msgType()) const
void printLayout (Ostream &os) const
void operator= (const mapDistributeBase &rhs)
void operator= (mapDistributeBase &&rhs)
InfoProxy< mapDistributeBase > info () const noexcept
void readDict (const dictionary &dict)
void writeEntries (Ostream &os) const
void updateMesh (const mapPolyMesh &)
void compact (const boolList &remoteElemUsed, const int tag=UPstream::msgType())
void compact (const boolList &remoteElemUsed, const label localSize, labelList &oldToNewSub, labelList &oldToNewConstruct, const int tag=UPstream::msgType())
template<class T , class NegateOp >
Foam::List< T > accessAndFlip (const UList< T > &values, const labelUList &indices, const bool hasFlip, const NegateOp &negOp)
Additional Inherited Members
Public Types inherited from IOobject
enum objectState : char { GOOD , BAD }
enum fileCheckTypes : char { timeStamp , timeStampMaster , inotify , inotifyMaster }
Public Types inherited from IOobjectOption
enum readOption : unsigned char {
NO_READ = 0 , MUST_READ = 0x1 , READ_MODIFIED = 0x3 , MUST_READ_IF_MODIFIED = 0x3 ,
LAZY_READ = 0x4 , READ_IF_PRESENT = 0x4
}
enum writeOption : unsigned char { NO_WRITE = 0 , AUTO_WRITE = 0x10 }
enum registerOption : unsigned char { NO_REGISTER = 0 , REGISTER = 1 }
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *p)
template<class Type >
static Type & store (autoPtr< Type > &ptr)
template<class Type >
static Type & store (autoPtr< Type > &&ptr)
template<class Type >
static Type & store (refPtr< Type > &ptr)
template<class Type >
static Type & store (refPtr< Type > &&ptr)
template<class Type >
static Type & store (tmp< Type > &ptr)
template<class Type >
static Type & store (tmp< Type > &&ptr)
Static Public Member Functions inherited from IOobject
static bool bannerEnabled () noexcept
static bool bannerEnabled (bool on) noexcept
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
template<class StringType >
static word groupName (StringType base, const word &group)
static word group (const word &name)
static word member (const word &name)
static word scopedName (const std::string &scope, const word &name)
static IOobject selectIO (const IOobject &io, const fileName &altFile, const word &ioName="")
static Ostream & writeBanner (Ostream &os, const bool noSyntaxHint=false)
static Ostream & writeDivider (Ostream &os)
static Ostream & writeEndDivider (Ostream &os)
Static Public Member Functions inherited from IOobjectOption
static bool isAnyRead (readOption opt) noexcept
static bool isReadRequired (readOption opt) noexcept
static bool isReadOptional (readOption opt) noexcept
static readOption lazierRead (readOption opt) noexcept
Static Public Member Functions inherited from mapDistributeBase
static bool hasFlipAddressing (const labelUList &map)
static bool hasFlipAddressing (const labelListList &maps)
static label countUnmapped (const labelUList &elements, const labelListList &maps, const bool hasFlip)
static List< labelPair > schedule (const labelListList &subMap, const labelListList &constructMap, const int tag, const label comm=UPstream::worldComm)
static label renumber (const globalIndex &, const List< Map< label > > &compactMap, const label globalElement)
static label renumberMap (labelListList &mapElements, const labelUList &oldToNew, const bool hasFlip)
template<class T , class NegateOp >
static void distribute (const Pstream::commsTypes commsType, const List< labelPair > &schedule, const label constructSize, const labelListList &subMap, const bool subHasFlip, const labelListList &constructMap, const bool constructHasFlip, List< T > &field, const NegateOp &negOp, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm)
template<class T , class CombineOp , class NegateOp >
static void distribute (const Pstream::commsTypes commsType, const List< labelPair > &schedule, const label constructSize, const labelListList &subMap, const bool subHasFlip, const labelListList &constructMap, const bool constructHasFlip, List< T > &field, const T &nullValue, const CombineOp &cop, const NegateOp &negOp, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm)
template<class T , class negateOp >
static void send (const labelListList &subMap, const bool subHasFlip, const labelListList &constructMap, const bool constructHasFlip, const UList< T > &field, labelRange &requests, PtrList< List< T > > &sendFields, PtrList< List< T > > &recvFields, const negateOp &negOp, const int tag, const label comm)
template<class T , class CombineOp , class negateOp >
static void receive (const label constructSize, const labelListList &constructMap, const bool constructHasFlip, const UPtrList< List< T > > &sendFields, const UPtrList< List< T > > &recvFields, const labelRange &requests, List< T > &field, const CombineOp &cop, const negateOp &negOp, const int tag, const label comm)
Static Public Attributes inherited from IOobject
static const Enum< fileCheckTypes > fileCheckTypesNames
static char scopeSeparator
static fileCheckTypes fileModificationChecking
static float fileModificationSkew
static int maxFileModificationPolls
Protected Member Functions inherited from regIOobject
bool readHeaderOk (const IOstreamOption::streamFormat fmt, const word &typeName)
Protected Member Functions inherited from IOobject
void setBad (const string &s)
Protected Member Functions inherited from mapDistributeBase
void calcCompactAddressing (const globalIndex &globalNumbering, const labelUList &elements, List< Map< label > > &compactMap) const
void calcCompactAddressing (const globalIndex &globalNumbering, const labelListList &elements, List< Map< label > > &compactMap) const
void exchangeAddressing (const int tag, const globalIndex &globalNumbering, labelList &elements, List< Map< label > > &compactMap, labelList &compactStart)
void exchangeAddressing (const int tag, const globalIndex &globalNumbering, labelListList &elements, List< Map< label > > &compactMap, labelList &compactStart)
Static Protected Member Functions inherited from IOobject
static void writeHeaderContent (Ostream &os, const IOobject &io, const word &objectType, const dictionary *metaDataDict=nullptr)
static void writeHeaderContent (dictionary &dict, const IOobject &io, const word &objectType, IOstreamOption streamOpt, const dictionary *metaDataDict=nullptr)
Static Protected Member Functions inherited from mapDistributeBase
static void checkReceivedSize (const label proci, const label expectedSize, const label receivedSize)
static label getMappedSize (const labelListList &maps, const bool hasFlip)
static void exchangeMasks (const UList< bitSet > &sendMasks, UList< bitSet > &recvMasks, const int tag, const label comm)
static void unionCombineMasks (UList< bitSet > &sendMasks, UList< bitSet > &recvMasks, const int tag, const label comm)
template<class T , class CombineOp , class NegateOp >
static void flipAndCombine (const labelUList &map, const bool hasFlip, const UList< T > &rhs, const CombineOp &cop, const NegateOp &negOp, List< T > &lhs)
template<class T , class NegateOp >
static T accessAndFlip (const UList< T > &values, const label index, const bool hasFlip, const NegateOp &negOp)
template<class T , class NegateOp >
static List< T > accessAndFlip (const UList< T > &values, const labelUList &indices, const bool hasFlip, const NegateOp &negOp)
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
Detailed Description
IOmapDistribute is derived from mapDistribute and IOobject to give the mapDistribute automatic IO functionality via the objectRegistry.
Source files
IOmapDistribute.H
IOmapDistribute.C
Definition at line 50 of file IOmapDistribute.H.
Constructor & Destructor Documentation
IOmapDistribute() [1/3]
IOmapDistribute (const IOobject & io)
Definition at line 49 of file IOmapDistribute.C.
IOmapDistribute() [2/3]
IOmapDistribute (const IOobject & io, const mapDistribute & map)
Definition at line 60 of file IOmapDistribute.C.
References mapDistribute::operator=().
IOmapDistribute() [3/3]
IOmapDistribute (const IOobject & io, mapDistribute && map)
Definition at line 78 of file IOmapDistribute.C.
References mapDistribute::transfer().
~IOmapDistribute()
virtual ~IOmapDistribute () virtual default
Member Function Documentation
TypeName()
TypeName ("mapDistribute")
readData()
bool readData (Istream & is) virtual
Reimplemented from regIOobject.
Definition at line 97 of file IOmapDistribute.C.
writeData()
bool writeData (Ostream & os) const virtual
Implements regIOobject.
Definition at line 103 of file IOmapDistribute.C.
References os().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/mapDistribute/IOmapDistribute.H
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/mapDistribute/IOmapDistribute.C