OpenFOAM: simplifiedDynamicFvMeshBase Class Reference
simplifiedDynamicFvMeshBase Class Reference
#include <simplifiedDynamicFvMesh.H>
Public Member Functions
TypeName ("simplifiedDynamicFvMeshBase")
declareRunTimeSelectionTable (autoPtr, dynamicFvMesh, time,(const Time &runTime, const word &regionName),(runTime, regionName))
simplifiedDynamicFvMeshBase ()
virtual ~simplifiedDynamicFvMeshBase ()=default
Static Public Member Functions
static autoPtr< dynamicFvMesh > New (const IOobject &io)
Detailed Description
Definition at line 52 of file simplifiedDynamicFvMesh.H.
Constructor & Destructor Documentation
simplifiedDynamicFvMeshBase()
simplifiedDynamicFvMeshBase () inline
Definition at line 81 of file simplifiedDynamicFvMesh.H.
~simplifiedDynamicFvMeshBase()
virtual ~simplifiedDynamicFvMeshBase () virtual default
Member Function Documentation
TypeName()
TypeName ("simplifiedDynamicFvMeshBase")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , dynamicFvMesh , time , (const Time &runTime, const word &regionName) , (runTime, regionName))
New()
Foam::autoPtr< Foam::dynamicFvMesh > New (const IOobject & io) static
Definition at line 38 of file simplifiedDynamicFvMesh.C.
References dict, Foam::endl(), Foam::Info, io(), IOobjectOption::MUST_READ_IF_MODIFIED, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, and polyMesh::regionName().
Referenced by dynamicFvMesh::New().
The documentation for this class was generated from the following files:
src/dynamicFvMesh/simplifiedDynamicFvMesh/simplifiedDynamicFvMesh.H
src/dynamicFvMesh/simplifiedDynamicFvMesh/simplifiedDynamicFvMesh.C