OpenFOAM: analytical Class Reference
analytical Class Reference
Analytical integration scheme.
#include <analytical.H>
Public Member Functions
TypeName ("analytical")
analytical ()
virtual autoPtr< integrationScheme > clone () const
virtual ~analytical ()
virtual scalar dtEff (const scalar dt, const scalar Beta) const
virtual scalar sumDtEff (const scalar dt, const scalar Beta) const
Public Member Functions inherited from integrationScheme
TypeName ("integrationScheme")
declareRunTimeSelectionTable (autoPtr, integrationScheme, word,(),())
integrationScheme ()
virtual ~integrationScheme ()
template<class Type >
Type delta (const Type &phi, const scalar dt, const Type &Alpha, const scalar Beta) const
template<class Type >
Type partialDelta (const Type &phi, const scalar dt, const Type &Alpha, const scalar Beta, const Type &alphai, const scalar betai) const
Additional Inherited Members
Static Public Member Functions inherited from integrationScheme
static autoPtr< integrationScheme > New (const word &phiName, const dictionary &dict)
template<class Type >
static Type explicitDelta (const Type &phi, const scalar dtEff, const Type &Alpha, const scalar Beta)
Detailed Description
Analytical integration scheme.
Definition at line 47 of file analytical.H.
Constructor & Destructor Documentation
analytical()
analytical ()
Definition at line 37 of file analytical.C.
Referenced by analytical::clone().
~analytical()
~analytical () virtual
Definition at line 43 of file analytical.C.
Member Function Documentation
TypeName()
TypeName ("analytical")
clone()
virtual autoPtr< integrationScheme > clone () const inline virtual
Implements integrationScheme.
Definition at line 63 of file analytical.H.
References analytical::analytical().
dtEff()
Foam::scalar dtEff (const scalar dt, const scalar Beta) const virtual
Implements integrationScheme.
Definition at line 49 of file analytical.C.
References Foam::exp(), and Foam::mag().
sumDtEff()
Foam::scalar sumDtEff (const scalar dt, const scalar Beta) const virtual
Implements integrationScheme.
Definition at line 62 of file analytical.C.
References Foam::exp(), Foam::mag(), and Foam::sqr().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/integrationScheme/analytical/analytical.H
src/lagrangian/intermediate/integrationScheme/analytical/analytical.C