OpenFOAM: trimModel Class Reference
trimModel Class Reference abstract
Base class for trim models for handling blade characteristics and thrust-torque relations.
#include <trimModel.H>
Public Member Functions
TypeName ("trimModel")
declareRunTimeSelectionTable (autoPtr, trimModel, dictionary,(const fv::rotorDiskSource &rotor, const dictionary &dict),(rotor, dict))
trimModel (const fv::rotorDiskSource &rotor, const dictionary &dict, const word &name)
virtual ~trimModel ()=default
virtual void read (const dictionary &dict)
virtual tmp< scalarField > thetag () const =0
virtual void correct (const vectorField &U, vectorField &force)=0
virtual void correct (const volScalarField rho, const vectorField &U, vectorField &force)=0
Static Public Member Functions
static autoPtr< trimModel > New (const fv::rotorDiskSource &rotor, const dictionary &dict)
Protected Attributes
const fv::rotorDiskSource & rotor_
const word name_
dictionary coeffs_
Detailed Description
Base class for trim models for handling blade characteristics and thrust-torque relations.
Usage
Minimal example by using constant/fvOptions: rotorDiskSource1 { Mandatory/Optional (inherited) entries ...
Mandatory entries (runtime modifiable) trimModel <trimModel>;
<trimModel>Coeffs { Conditional mandatory entries (runtime modifiable)
when trimModel=fixedTrim theta0 5.0; theta1c 1.0; theta1s 4.0; } }
where the entries mean:
Property Description Type Reqd Dflt
trimModel Trim model specification word yes -
file Name of file containing profile characteristics word no -
Options for the trimModel entry:
      fixed       | Fixed blade/angle characteristics
      targetForce | Target thrust/torque by using time-variant blade characs.
See also
Foam::fv::rotorDiskSource
Foam::fixedTrim
Foam::targetCoeffTrim
Source files
trimModel.H
trimModel.C
Definition at line 107 of file trimModel.H.
Constructor & Destructor Documentation
trimModel()
trimModel (const fv::rotorDiskSource & rotor, const dictionary & dict, const word & name)
Definition at line 35 of file trimModel.C.
References dict, Foam::name(), and trimModel::read().
~trimModel()
virtual ~trimModel () virtual default
Member Function Documentation
TypeName()
TypeName ("trimModel")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , trimModel , dictionary , (const fv::rotorDiskSource &rotor, const dictionary &dict) , (rotor, dict))
New()
Foam::autoPtr< Foam::trimModel > New (const fv::rotorDiskSource & rotor, const dictionary & dict) static
Definition at line 26 of file trimModelNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, and Foam::Info.
read()
void read (const dictionary & dict) virtual
Reimplemented in fixedTrim, and targetCoeffTrim.
Definition at line 52 of file trimModel.C.
References dict, and dictionary::optionalSubDict().
Referenced by fixedTrim::read(), targetCoeffTrim::read(), and trimModel::trimModel().
thetag()
virtual tmp< scalarField > thetag () const pure virtual
Implemented in fixedTrim, and targetCoeffTrim.
correct() [1/2]
virtual void correct (const vectorField & U, vectorField & force) pure virtual
Implemented in fixedTrim, and targetCoeffTrim.
correct() [2/2]
virtual void correct (const volScalarField rho, const vectorField & U, vectorField & force) pure virtual
Implemented in fixedTrim, and targetCoeffTrim.
Member Data Documentation
rotor_
const fv::rotorDiskSource& rotor_ protected
Definition at line 114 of file trimModel.H.
Referenced by targetCoeffTrim::calcCoeffs().
name_
const word name_ protected
Definition at line 117 of file trimModel.H.
coeffs_
dictionary coeffs_ protected
Definition at line 120 of file trimModel.H.
The documentation for this class was generated from the following files:
src/fvOptions/sources/derived/rotorDiskSource/trimModel/trimModel/trimModel.H
src/fvOptions/sources/derived/rotorDiskSource/trimModel/trimModel/trimModel.C
src/fvOptions/sources/derived/rotorDiskSource/trimModel/trimModel/trimModelNew.C