OpenFOAM: Function1< Type > Class Template Reference
Function1< Type > Class Template Reference abstract
Top level data entry class for use in dictionaries. Provides a mechanism to specify a variable as a certain type, e.g. constant or table, and provide functions to return the (interpolated) value, and integral between limits.
#include <Function1.H>
Public Types
typedef Type returnType
Public Member Functions
TypeName ("Function1") declareRunTimeSelectionTable(autoPtr
Function1 (const word &entryName, const objectRegistry *obrPtr=nullptr)
Function1 (const word &entryName, const dictionary &dict, const objectRegistry *obrPtr=nullptr)
Function1 (const Function1< Type > &rhs)
virtual tmp< Function1< Type > > clone () const =0
virtual ~Function1 ()=default
virtual bool constant () const
virtual bool good () const
virtual Type value (const scalar x) const
virtual tmp< Field< Type > > value (const scalarField &x) const
virtual Type integrate (const scalar x1, const scalar x2) const
virtual tmp< Field< Type > > integrate (const scalarField &x1, const scalarField &x2) const
virtual void writeData (Ostream &os) const
virtual void writeEntries (Ostream &os) const
Public Member Functions inherited from function1Base
function1Base (const word &entryName, const objectRegistry *obrPtr=nullptr)
function1Base (const word &entryName, const dictionary &dict, const objectRegistry *obrPtr=nullptr)
function1Base (const function1Base &rhs)
virtual ~function1Base ()
const word & name () const noexcept
const objectRegistry * whichDb () const noexcept
void resetDb (const objectRegistry *obrPtr=nullptr) noexcept
void resetDb (const objectRegistry &db) noexcept
const objectRegistry & obr () const
bool isTime () const noexcept
const Time & time () const
template<class MeshType >
const MeshType & mesh (const word &regionName=word::null) const
virtual void userTimeToTime (const Time &t)
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Static Public Member Functions
static autoPtr< Function1< Type > > New (const word &entryName, const dictionary &dict, const word &redirectType, const objectRegistry *obrPtr=nullptr, const bool mandatory=true)
static autoPtr< Function1< Type > > NewCompat (const word &entryName, std::initializer_list< std::pair< const char *, int > > compat, const dictionary &dict, const word &redirectType=word::null, const objectRegistry *obrPtr=nullptr, const bool mandatory=true)
static autoPtr< Function1< Type > > New (const word &entryName, const dictionary &dict, const objectRegistry *obrPtr=nullptr, const bool mandatory=true)
static autoPtr< Function1< Type > > NewIfPresent (const word &entryName, const dictionary &dict, const word &redirectType, const objectRegistry *obrPtr=nullptr)
static autoPtr< Function1< Type > > NewIfPresent (const word &entryName, const dictionary &dict, const objectRegistry *obrPtr=nullptr)
static refPtr< Function1< Type > > New (HashPtrTable< Function1< Type > > &cache, const word &entryName, const dictionary &dict, enum keyType::option matchOpt=keyType::LITERAL, const objectRegistry *obrPtr=nullptr, const bool mandatory=true)
Public Attributes
Function1
dictionary
const word & entryName
const word const dictionary & dict
const word const dictionary const objectRegistry * obrPtr
const word const dictionary const objectRegistry entryName
const word const dictionary const objectRegistry dict
const word const dictionary const objectRegistry obrPtr
Protected Member Functions
void operator= (const Function1< Type > &)=delete
Protected Member Functions inherited from function1Base
void operator= (const function1Base &)=delete
Friends
Ostream & operator<< (Ostream &os, const Function1< Type > &func)
Additional Inherited Members
Protected Attributes inherited from function1Base
const word name_
const objectRegistry * obrPtr_
Detailed Description
template<class Type>
class Foam::Function1< Type >
Top level data entry class for use in dictionaries. Provides a mechanism to specify a variable as a certain type, e.g. constant or table, and provide functions to return the (interpolated) value, and integral between limits.
The New factory method attempts to deal with varying types of input. It accepts primitive or dictionary entries for dispatching to different function types, but wraps unspecified types as "constant".
In the dictionary form, the coefficients are the dictionary itself. This is arguably the more readable form. For example,
    <entryName>
    {
        type      linearRamp;
        start     10;
        duration  20;
    }
In the primitive form, the coefficients are provided separately. For example,
    <entryName>   linearRamp;
    <entryName>Coeffs
    {
        start     10;
        duration  20;
    }
The coeffs dictionary is optional, since it is not required by all types. For example,
    <entryName>   zero;
Source files
Function1.H
Function1.C
Function1New.C
Definition at line 89 of file Function1.H.
Member Typedef Documentation
returnType
template<class Type > typedef Type returnType
Definition at line 120 of file Function1.H.
Constructor & Destructor Documentation
Function1() [1/3]
template<class Type > Function1 (const word & entryName, const objectRegistry * obrPtr = nullptr) explicit
Function1() [2/3]
template<class Type > Function1 (const word & entryName, const dictionary & dict, const objectRegistry * obrPtr = nullptr)
Function1() [3/3]
template<class Type > Function1 (const Function1< Type > & rhs) explicit
~Function1()
template<class Type > virtual ~Function1 () virtual default
//- Selector with external storage of Function1. //- This also allows wildcard matches in a dictionary. // If the default value is used, stores an entry as "default" static refPtr<Function1<Type>> NewOrDefault (HashPtrTable<Function1<Type>>& cache, const word& entryName, const dictionary& dict, const Type& deflt, enum keyType::option matchOpt = keyType::LITERAL, const objectRegistry* obrPtr = nullptr);
Member Function Documentation
operator=()
template<class Type > void operator= (const Function1< Type > &) protected delete
TypeName()
template<class Type > TypeName ("Function1< Type >")
clone()
template<class Type > virtual tmp< Function1< Type > > clone () const pure virtual
Implemented in Function1Expression< Type >, CodedFunction1< Type >, Constant< Type >, Cosine< Type >, CSV< Type >, FunctionObjectTrigger< Type >, FunctionObjectValue< Type >, InputValueMapper< Type >, None< Type >, OneConstant< Type >, Polynomial< Type >, Scale< Type >, Sine< Type >, Square< Type >, Table< Type >, TableFile< Type >, Uniform< Type >, ZeroConstant< Type >, and Sample< Type >.
New() [1/3]
template<class Type > Foam::autoPtr< Foam::Function1< Type > > New (const word & entryName, const dictionary & dict, const word & redirectType, const objectRegistry * obrPtr = nullptr, const bool mandatory = true) static
Definition at line 147 of file Function1New.C.
References dict, dictionary::findEntry(), and keyType::LITERAL.
NewCompat()
template<class Type > Foam::autoPtr< Foam::Function1< Type > > NewCompat (const word & entryName, std::initializer_list< std::pair< const char *, int > > compat, const dictionary & dict, const word & redirectType = word::null, const objectRegistry * obrPtr = nullptr, const bool mandatory = true) static
Definition at line 170 of file Function1New.C.
New() [2/3]
template<class Type > Foam::autoPtr< Foam::Function1< Type > > New (const word & entryName, const dictionary & dict, const objectRegistry * obrPtr = nullptr, const bool mandatory = true) static
Definition at line 194 of file Function1New.C.
NewIfPresent() [1/2]
template<class Type > Foam::autoPtr< Foam::Function1< Type > > NewIfPresent (const word & entryName, const dictionary & dict, const word & redirectType, const objectRegistry * obrPtr = nullptr) static
Definition at line 208 of file Function1New.C.
References dict.
Referenced by coordinateScaling< Type >::coordinateScaling(), flowRateInletVelocityFvPatchVectorField::flowRateInletVelocityFvPatchVectorField(), flowRateOutletVelocityFvPatchVectorField::flowRateOutletVelocityFvPatchVectorField(), and rigidBodyMotion::read().
NewIfPresent() [2/2]
template<class Type > Foam::autoPtr< Foam::Function1< Type > > NewIfPresent (const word & entryName, const dictionary & dict, const objectRegistry * obrPtr = nullptr) static
Definition at line 223 of file Function1New.C.
References dict, and word::null.
New() [3/3]
template<class Type > Foam::refPtr< Foam::Function1< Type > > New (HashPtrTable< Function1< Type > > & cache, const word & entryName, const dictionary & dict, enum keyType::option matchOpt = keyType::LITERAL, const objectRegistry * obrPtr = nullptr, const bool mandatory = true) static
Definition at line 237 of file Function1New.C.
References dict, Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, dictionary::findEntry(), UPtrList< T >::get(), Foam::nl, word::null, and PtrList< T >::set().
constant()
template<class Type > virtual bool constant () const inline virtual
Reimplemented in Constant< Type >, None< Type >, OneConstant< Type >, and ZeroConstant< Type >.
Definition at line 251 of file Function1.H.
good()
template<class Type > virtual bool good () const inline virtual
Reimplemented in None< Type >.
Definition at line 254 of file Function1.H.
value() [1/2]
template<class Type > Type value (const scalar x) const virtual
Reimplemented in Cosine< Type >, halfCosineRamp, InputValueMapper< Type >, linearRamp, quadraticRamp, quarterCosineRamp, quarterSineRamp, Scale< Type >, Sine< Type >, Square< Type >, ramp, Function1Expression< Type >, CodedFunction1< Type >, None< Type >, Polynomial< Type >, stepFunction, TableBase< Type >, Sample< Type >, Constant< Type >, FunctionObjectTrigger< Type >, FunctionObjectValue< Type >, OneConstant< Type >, and ZeroConstant< Type >.
Definition at line 62 of file Function1.C.
References NotImplemented.
Referenced by solution::equationRelaxationFactor(), and solution::fieldRelaxationFactor().
value() [2/2]
template<class Type > Foam::tmp< Foam::Field< Type > > value (const scalarField & x) const virtual
Reimplemented in Constant< Type >, None< Type >, and OneConstant< Type >.
Definition at line 70 of file Function1.C.
References NotImplemented.
integrate() [1/2]
template<class Type > Type integrate (const scalar x1, const scalar x2) const virtual
Reimplemented in Function1Expression< Type >, Constant< Type >, FunctionObjectValue< Type >, InputValueMapper< Type >, OneConstant< Type >, Polynomial< Type >, TableBase< Type >, ZeroConstant< Type >, Sample< Type >, and FunctionObjectTrigger< Type >.
Definition at line 81 of file Function1.C.
References NotImplemented.
integrate() [2/2]
template<class Type > Foam::tmp< Foam::Field< Type > > integrate (const scalarField & x1, const scalarField & x2) const virtual
Reimplemented in OneConstant< Type >.
Definition at line 89 of file Function1.C.
References NotImplemented.
writeData()
template<class Type > void writeData (Ostream & os) const virtual
Reimplemented in Function1Expression< Type >, CodedFunction1< Type >, Constant< Type >, CSV< Type >, FunctionObjectTrigger< Type >, FunctionObjectValue< Type >, InputValueMapper< Type >, None< Type >, OneConstant< Type >, Polynomial< Type >, ramp, Scale< Type >, Sine< Type >, Square< Type >, Table< Type >, TableBase< Type >, TableFile< Type >, ZeroConstant< Type >, and Sample< Type >.
Definition at line 167 of file Function1.C.
References os(), Foam::type(), and Ostream::writeKeyword().
Referenced by Constant< Type >::writeData(), CSV< Type >::writeData(), FunctionObjectTrigger< Type >::writeData(), FunctionObjectValue< Type >::writeData(), InputValueMapper< Type >::writeData(), None< Type >::writeData(), OneConstant< Type >::writeData(), Polynomial< Type >::writeData(), ramp::writeData(), Scale< Type >::writeData(), Sine< Type >::writeData(), Square< Type >::writeData(), Table< Type >::writeData(), TableBase< Type >::writeData(), TableFile< Type >::writeData(), ZeroConstant< Type >::writeData(), and Sample< Type >::writeData().
writeEntries()
template<class Type > void writeEntries (Ostream & os) const virtual
Reimplemented in CSV< Type >, FunctionObjectTrigger< Type >, FunctionObjectValue< Type >, InputValueMapper< Type >, ramp, Scale< Type >, Sine< Type >, Square< Type >, TableBase< Type >, and Sample< Type >.
Definition at line 162 of file Function1.C.
Friends And Related Symbol Documentation
operator<<
template<class Type > Ostream & operator<< (Ostream & os, const Function1< Type > & func) friend
Member Data Documentation
Function1
template<class Type > Function1
Definition at line 130 of file Function1.H.
dictionary
template<class Type > dictionary
Definition at line 131 of file Function1.H.
entryName [1/2]
template<class Type > const word& entryName
Definition at line 133 of file Function1.H.
Referenced by Constant< Type >::Constant(), Polynomial< Type >::Polynomial(), and Table< Type >::Table().
dict [1/2]
template<class Type > const word const dictionary& dict
Definition at line 134 of file Function1.H.
Referenced by Constant< Type >::Constant(), Function1Expression< Type >::Function1Expression(), FunctionObjectTrigger< Type >::FunctionObjectTrigger(), FunctionObjectValue< Type >::FunctionObjectValue(), InputValueMapper< Type >::InputValueMapper(), Polynomial< Type >::Polynomial(), Scale< Type >::Scale(), Sine< Type >::Sine(), Table< Type >::Table(), and TableFile< Type >::TableFile().
obrPtr [1/2]
template<class Type > const word const dictionary const objectRegistry* obrPtr
Definition at line 135 of file Function1.H.
Referenced by Sine< Type >::Sine().
entryName [2/2]
template<class Type > const word const dictionary const objectRegistry entryName
Definition at line 137 of file Function1.H.
dict [2/2]
template<class Type > const word const dictionary const objectRegistry dict
Definition at line 137 of file Function1.H.
obrPtr [2/2]
template<class Type > const word const dictionary const objectRegistry obrPtr
Definition at line 137 of file Function1.H.
The documentation for this class was generated from the following files:
src/functionObjects/forces/propellerInfo/propellerInfo.H
src/OpenFOAM/primitives/functions/Function1/Function1/Function1.H
src/OpenFOAM/primitives/functions/Function1/Function1/Function1.C
src/OpenFOAM/primitives/functions/Function1/Function1/Function1New.C