OpenFOAM: inversePointDistanceDiffusivity Class Reference
inversePointDistanceDiffusivity Class Reference
Inverse distance to the given patches motion diffusivity.
#include <inversePointDistanceDiffusivity.H>
Public Member Functions
TypeName ("inversePointDistance")
inversePointDistanceDiffusivity (const fvMesh &mesh, Istream &mdData)
virtual ~inversePointDistanceDiffusivity ()=default
virtual void correct ()
Public Member Functions inherited from uniformDiffusivity
TypeName ("uniform")
uniformDiffusivity (const fvMesh &mesh, Istream &mdData)
virtual ~uniformDiffusivity ()
virtual tmp< surfaceScalarField > operator() () const
Public Member Functions inherited from motionDiffusivity
TypeName ("motionDiffusivity")
declareRunTimeSelectionTable (autoPtr, motionDiffusivity, Istream,(const fvMesh &mesh, Istream &mdData),(mesh, mdData))
motionDiffusivity (const fvMesh &mesh)
virtual ~motionDiffusivity ()
const fvMesh & mesh () const
Additional Inherited Members
Static Public Member Functions inherited from motionDiffusivity
static autoPtr< motionDiffusivity > New (const fvMesh &mesh, Istream &mdData)
Protected Attributes inherited from uniformDiffusivity
surfaceScalarField faceDiffusivity_
Detailed Description
Inverse distance to the given patches motion diffusivity.
Source files
inversePointDistanceDiffusivity.H
inversePointDistanceDiffusivity.C
Definition at line 47 of file inversePointDistanceDiffusivity.H.
Constructor & Destructor Documentation
inversePointDistanceDiffusivity()
inversePointDistanceDiffusivity (const fvMesh & mesh, Istream & mdData)
Definition at line 45 of file inversePointDistanceDiffusivity.C.
References inversePointDistanceDiffusivity::correct().
~inversePointDistanceDiffusivity()
virtual ~inversePointDistanceDiffusivity () virtual default
Member Function Documentation
TypeName()
TypeName ("inversePointDistance")
correct()
void correct () virtual
Reimplemented from uniformDiffusivity.
Definition at line 60 of file inversePointDistanceDiffusivity.C.
References polyMesh::boundaryMesh(), primitiveMesh::cells(), f(), polyMesh::faces(), forAll, HashTable< T, Key, Hash >::found(), mesh, primitiveMesh::nInternalFaces(), nPoints, points, PtrList< T >::setSize(), UPtrList< T >::size(), UList< T >::size(), and Foam::sqrt().
Referenced by inversePointDistanceDiffusivity::inversePointDistanceDiffusivity().
The documentation for this class was generated from the following files:
src/fvMotionSolver/motionDiffusivity/inversePointDistance/inversePointDistanceDiffusivity.H
src/fvMotionSolver/motionDiffusivity/inversePointDistance/inversePointDistanceDiffusivity.C