OpenFOAM: wallDependentModel Class Reference
wallDependentModel Class Reference
A class which provides on-demand creation and caching of wall distance and wall normal fields for use by multiple models.
#include <wallDependentModel.H>
Public Member Functions
wallDependentModel (const fvMesh &mesh)
virtual ~wallDependentModel ()
const volScalarField & yWall () const
const volVectorField & nWall () const
wallDependentModel (const fvMesh &mesh)
virtual ~wallDependentModel ()
const volScalarField & yWall () const
const volVectorField & nWall () const
Detailed Description
A class which provides on-demand creation and caching of wall distance and wall normal fields for use by multiple models.
Source files
wallDependentModel.H
wallDependentModel.C
Source files
wallDependentModel.H
wallDependentModel.C
Definition at line 48 of file wallDependentModel.H.
Constructor & Destructor Documentation
wallDependentModel() [1/2]
wallDependentModel (const fvMesh & mesh)
Definition at line 26 of file wallDependentModel.C.
~wallDependentModel() [1/2]
~wallDependentModel () virtual
Definition at line 34 of file wallDependentModel.C.
wallDependentModel() [2/2]
wallDependentModel (const fvMesh & mesh)
~wallDependentModel() [2/2]
virtual ~wallDependentModel () virtual
Member Function Documentation
yWall() [1/2]
const Foam::volScalarField & yWall () const
Definition at line 40 of file wallDependentModel.C.
References MeshObject< fvMesh, UpdateableMeshObject, wallDist >::New().
Referenced by cosine::limiter(), linear::limiter(), and sine::limiter().
nWall() [1/2]
const Foam::volVectorField & nWall () const
Definition at line 46 of file wallDependentModel.C.
References MeshObject< fvMesh, UpdateableMeshObject, wallDist >::New().
yWall() [2/2]
const volScalarField & yWall () const
nWall() [2/2]
const volVectorField & nWall () const
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/interfacialModels/wallDependentModel/wallDependentModel.H
src/phaseSystemModels/twoPhaseEuler/twoPhaseSystem/interfacialModels/wallDependentModel/wallDependentModel.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/interfacialModels/wallDependentModel/wallDependentModel.C
src/phaseSystemModels/twoPhaseEuler/twoPhaseSystem/interfacialModels/wallDependentModel/wallDependentModel.C