OpenFOAM: exponentialRepulsion Class Reference
exponentialRepulsion Class Reference
#include <exponentialRepulsion.H>
Public Member Functions
TypeName ("exponentialRepulsion")
exponentialRepulsion (const word &name, const dictionary &pairPotentialProperties)
~exponentialRepulsion ()
scalar unscaledEnergy (const scalar r) const
bool read (const dictionary &pairPotentialProperties)
Public Member Functions inherited from pairPotential
TypeName ("pairPotential")
declareRunTimeSelectionTable (autoPtr, pairPotential, dictionary,(const word &name, const dictionary &pairPotentialProperties),(name, pairPotentialProperties))
pairPotential (const word &name, const dictionary &pairPotentialProperties)
virtual ~pairPotential ()=default
void setLookupTables ()
scalar rMin () const
scalar dr () const
scalar rCut () const
scalar rCutSqr () const
scalar energy (const scalar r) const
scalar force (const scalar r) const
List< Pair< scalar > > energyTable () const
List< Pair< scalar > > forceTable () const
bool writeTables () const
scalar scaledEnergy (const scalar r) const
scalar energyDerivative (const scalar r, const bool scaledEnergyDerivative=true) const
const dictionary & pairPotentialProperties () const
bool writeEnergyAndForceTables (Ostream &os) const
Additional Inherited Members
Static Public Member Functions inherited from pairPotential
static autoPtr< pairPotential > New (const word &name, const dictionary &pairPotentialProperties)
Protected Member Functions inherited from pairPotential
void scaleEnergy (scalar &e, const scalar r) const
pairPotential (const pairPotential &)=delete
void operator= (const pairPotential &)=delete
Protected Attributes inherited from pairPotential
word name_
dictionary pairPotentialProperties_
scalar rCut_
scalar rCutSqr_
scalar rMin_
scalar dr_
List< scalar > forceLookup_
List< scalar > energyLookup_
energyScalingFunction * esfPtr_
bool writeTables_
Detailed Description
Source files
exponentialRepulsion.H
exponentialRepulsion.C
Definition at line 48 of file exponentialRepulsion.H.
Constructor & Destructor Documentation
exponentialRepulsion()
exponentialRepulsion (const word & name, const dictionary & pairPotentialProperties)
Definition at line 45 of file exponentialRepulsion.C.
References pairPotential::setLookupTables().
~exponentialRepulsion()
~exponentialRepulsion () inline
Definition at line 77 of file exponentialRepulsion.H.
Member Function Documentation
TypeName()
TypeName ("exponentialRepulsion")
unscaledEnergy()
scalar unscaledEnergy (const scalar r) const virtual
Implements pairPotential.
Definition at line 65 of file exponentialRepulsion.C.
References Foam::exp().
read()
bool read (const dictionary & pairPotentialProperties) virtual
Implements pairPotential.
Definition at line 71 of file exponentialRepulsion.C.
References pairPotential::read(), and dictionary::readEntry().
The documentation for this class was generated from the following files:
src/lagrangian/molecularDynamics/potential/pairPotential/derived/exponentialRepulsion/exponentialRepulsion.H
src/lagrangian/molecularDynamics/potential/pairPotential/derived/exponentialRepulsion/exponentialRepulsion.C