OpenFOAM: CollidingParcel< ParcelType > Class Template Reference
CollidingParcel< ParcelType > Class Template Reference
Lagrangian particle models » Parcels
Wrapper around kinematic parcel types to add collision modelling.
#include <CollidingParcel.H>
Classes
class constantProperties
class iNew
Public Types
typedef ParcelType::trackingData trackingData
Public Member Functions
TypeName ("CollidingParcel")
AddToPropertyList (ParcelType, " (fx fy fz)"+" (angularMomentumx angularMomentumy angularMomentumz)"+" (torquex torquey torquez)"+" collisionRecordsPairAccessed"+" collisionRecordsPairOrigProcOfOther"+" collisionRecordsPairOrigIdOfOther"+" (collisionRecordsPairData)"+" collisionRecordsWallAccessed"+" collisionRecordsWallPRel"+" (collisionRecordsWallData)")
CollidingParcel (const polyMesh &mesh, const barycentric &coordinates, const label celli, const label tetFacei, const label tetPti)
CollidingParcel (const polyMesh &mesh, const vector &position, const label celli)
CollidingParcel (const polyMesh &mesh, const barycentric &coordinates, const label celli, const label tetFacei, const label tetPti, const label typeId, const scalar nParticle0, const scalar d0, const scalar dTarget0, const vector &U0, const vector &f0, const vector &angularMomentum0, const vector &torque0, const typename ParcelType::constantProperties &constProps)
CollidingParcel (const polyMesh &mesh, Istream &is, bool readFields=true, bool newFormat=true)
CollidingParcel (const CollidingParcel &p)
CollidingParcel (const CollidingParcel &p, const polyMesh &mesh)
virtual autoPtr< particle > clone () const
virtual autoPtr< particle > clone (const polyMesh &mesh) const
const vector & f () const
const vector & angularMomentum () const
const vector & torque () const
const collisionRecordList & collisionRecords () const
vector & f ()
vector & angularMomentum ()
vector & torque ()
collisionRecordList & collisionRecords ()
vector omega () const
template<class TrackCloudType >
bool move (TrackCloudType &cloud, trackingData &td, const scalar trackTime)
virtual void transformProperties (const tensor &T)
virtual void transformProperties (const vector &separation)
void writeProperties (Ostream &os, const wordRes &filters, const word &delim, const bool namesOnly) const
Static Public Member Functions
template<class CloudType >
static void readFields (CloudType &c)
template<class CloudType >
static void writeFields (const CloudType &c)
template<class CloudType >
static void readObjects (CloudType &c, const objectRegistry &obr)
template<class CloudType >
static void writeObjects (const CloudType &c, objectRegistry &obr)
Static Public Attributes
static const std::size_t sizeofFields
Protected Attributes
vector f_
vector angularMomentum_
vector torque_
collisionRecordList collisionRecords_
Friends
Ostream & operator<< (Ostream &, const CollidingParcel< ParcelType > &)
Detailed Description
template<class ParcelType>
class Foam::CollidingParcel< ParcelType >
Wrapper around kinematic parcel types to add collision modelling.
Source files
CollidingParcel.H
CollidingParcelI.H
CollidingParcel.C
CollidingParcelIO.C
Definition at line 73 of file CollidingParcel.H.
Member Typedef Documentation
trackingData
template<class ParcelType > typedef ParcelType::trackingData trackingData
Definition at line 123 of file CollidingParcel.H.
Constructor & Destructor Documentation
CollidingParcel() [1/6]
template<class ParcelType > CollidingParcel (const polyMesh & mesh, const barycentric & coordinates, const label celli, const label tetFacei, const label tetPti) inline
Definition at line 58 of file CollidingParcelI.H.
CollidingParcel() [2/6]
template<class ParcelType > CollidingParcel (const polyMesh & mesh, const vector & position, const label celli) inline
Definition at line 76 of file CollidingParcelI.H.
CollidingParcel() [3/6]
template<class ParcelType > CollidingParcel (const polyMesh & mesh, const barycentric & coordinates, const label celli, const label tetFacei, const label tetPti, const label typeId, const scalar nParticle0, const scalar d0, const scalar dTarget0, const vector & U0, const vector & f0, const vector & angularMomentum0, const vector & torque0, const typename ParcelType::constantProperties & constProps) inline
Definition at line 92 of file CollidingParcelI.H.
CollidingParcel() [4/6]
template<class ParcelType > CollidingParcel (const polyMesh & mesh, Istream & is, bool readFields = true, bool newFormat = true)
Definition at line 43 of file CollidingParcelIO.C.
References CollidingParcel< ParcelType >::angularMomentum_, IOstreamOption::ASCII, CollidingParcel< ParcelType >::collisionRecords_, VectorSpace< Form, Cmpt, Ncmpts >::data(), CollidingParcel< ParcelType >::f_, FUNCTION_NAME, VectorSpace< Form, Cmpt, Ncmpts >::nComponents, CollidingParcel< ParcelType >::readFields(), Foam::readFields(), CollidingParcel< ParcelType >::sizeofFields, and CollidingParcel< ParcelType >::torque_.
CollidingParcel() [5/6]
template<class ParcelType > CollidingParcel (const CollidingParcel< ParcelType > & p)
CollidingParcel() [6/6]
template<class ParcelType > CollidingParcel (const CollidingParcel< ParcelType > & p, const polyMesh & mesh)
Member Function Documentation
TypeName()
template<class ParcelType > TypeName ("CollidingParcel< ParcelType >")
AddToPropertyList()
template<class ParcelType > AddToPropertyList (ParcelType , " (fx fy fz)"+" (angularMomentumx angularMomentumy angularMomentumz)"+" (torquex torquey torquez)"+" collisionRecordsPairAccessed"+" collisionRecordsPairOrigProcOfOther"+" collisionRecordsPairOrigIdOfOther"+" (collisionRecordsPairData)"+" collisionRecordsWallAccessed"+" collisionRecordsWallPRel"+" (collisionRecordsWallData)")
clone() [1/2]
template<class ParcelType > virtual autoPtr< particle > clone () const inline virtual
Definition at line 225 of file CollidingParcel.H.
clone() [2/2]
template<class ParcelType > virtual autoPtr< particle > clone (const polyMesh & mesh) const inline virtual
Definition at line 231 of file CollidingParcel.H.
References mesh.
f() [1/2]
template<class ParcelType > const Foam::vector & f () const inline
Definition at line 152 of file CollidingParcelI.H.
angularMomentum() [1/2]
template<class ParcelType > const Foam::vector & angularMomentum () const inline
Definition at line 160 of file CollidingParcelI.H.
torque() [1/2]
template<class ParcelType > const Foam::vector & torque () const inline
Definition at line 167 of file CollidingParcelI.H.
collisionRecords() [1/2]
template<class ParcelType > const Foam::collisionRecordList & collisionRecords () const inline
Definition at line 175 of file CollidingParcelI.H.
f() [2/2]
template<class ParcelType > Foam::vector & f () inline
Definition at line 182 of file CollidingParcelI.H.
angularMomentum() [2/2]
template<class ParcelType > Foam::vector & angularMomentum () inline
Definition at line 189 of file CollidingParcelI.H.
torque() [2/2]
template<class ParcelType > Foam::vector & torque () inline
Definition at line 196 of file CollidingParcelI.H.
collisionRecords() [2/2]
template<class ParcelType > Foam::collisionRecordList & collisionRecords () inline
Definition at line 204 of file CollidingParcelI.H.
omega()
template<class ParcelType > Foam::vector omega () const inline
Definition at line 211 of file CollidingParcelI.H.
move()
template<class ParcelType > template<class TrackCloudType > bool move (TrackCloudType & cloud, trackingData & td, const scalar trackTime)
Definition at line 58 of file CollidingParcel.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, NotImplemented, and p.
transformProperties() [1/2]
template<class ParcelType > void transformProperties (const tensor & T) virtual
Definition at line 115 of file CollidingParcel.C.
References T, and Foam::transform().
transformProperties() [2/2]
template<class ParcelType > void transformProperties (const vector & separation) virtual
Definition at line 128 of file CollidingParcel.C.
readFields()
template<class ParcelType > template<class CloudType > void readFields (CloudType & c) static
Definition at line 91 of file CollidingParcelIO.C.
References f(), IOobjectOption::MUST_READ, p, and UPtrList< T >::size().
Referenced by CollidingParcel< ParcelType >::CollidingParcel().
writeFields()
template<class ParcelType > template<class CloudType > void writeFields (const CloudType & c) static
Definition at line 197 of file CollidingParcelIO.C.
References f(), IOobjectOption::NO_READ, p, and UPtrList< T >::size().
writeProperties()
template<class ParcelType > void writeProperties (Ostream & os, const wordRes & filters, const word & delim, const bool namesOnly) const
Definition at line 288 of file CollidingParcelIO.C.
References os(), and writeProp.
readObjects()
template<class ParcelType > template<class CloudType > void readObjects (CloudType & c, const objectRegistry & obr) static
Definition at line 313 of file CollidingParcelIO.C.
References f(), p, and UPtrList< T >::size().
writeObjects()
template<class ParcelType > template<class CloudType > void writeObjects (const CloudType & c, objectRegistry & obr) static
Definition at line 341 of file CollidingParcelIO.C.
References f(), p, and UPtrList< T >::size().
Friends And Related Symbol Documentation
operator<<
template<class ParcelType > Ostream & operator<< (Ostream & , const CollidingParcel< ParcelType > &) friend
Member Data Documentation
sizeofFields
template<class ParcelType > const std::size_t sizeofFields static
Definition at line 80 of file CollidingParcel.H.
Referenced by CollidingParcel< ParcelType >::CollidingParcel().
f_
template<class ParcelType > vector f_ protected
Definition at line 131 of file CollidingParcel.H.
Referenced by CollidingParcel< ParcelType >::CollidingParcel().
angularMomentum_
template<class ParcelType > vector angularMomentum_ protected
Definition at line 134 of file CollidingParcel.H.
Referenced by CollidingParcel< ParcelType >::CollidingParcel().
torque_
template<class ParcelType > vector torque_ protected
Definition at line 138 of file CollidingParcel.H.
Referenced by CollidingParcel< ParcelType >::CollidingParcel().
collisionRecords_
template<class ParcelType > collisionRecordList collisionRecords_ protected
Definition at line 141 of file CollidingParcel.H.
Referenced by CollidingParcel< ParcelType >::CollidingParcel().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/parcels/Templates/CollidingParcel/CollidingParcel.H
src/lagrangian/intermediate/parcels/Templates/CollidingParcel/CollidingParcel.C
src/lagrangian/intermediate/parcels/Templates/CollidingParcel/CollidingParcelI.H
src/lagrangian/intermediate/parcels/Templates/CollidingParcel/CollidingParcelIO.C