OpenFOAM: vtuAdaptor Class Reference
vtuAdaptor Class Reference
A low-level backend adaptor for converting OpenFOAM volume meshes/fields to VTK internal representation. The output is a single piece vtkUnstructuredGrid dataset. Multiblock composition is done by the caller.
#include <foamVtkVtuAdaptor.H>
Public Member Functions
vtkSmartPointer< vtkPoints > points (const fvMesh &mesh) const
vtkSmartPointer< vtkPoints > points (const fvMesh &mesh, const labelUList &pointMap) const
vtkSmartPointer< vtkUnstructuredGrid > internal (const fvMesh &mesh, const bool decompPoly=false)
template<class Type >
vtkSmartPointer< vtkFloatArray > convertField (const DimensionedField< Type, volMesh > &fld) const
template<class Type >
vtkSmartPointer< vtkFloatArray > convertField (const GeometricField< Type, fvPatchField, volMesh > &fld) const
Public Member Functions inherited from Caching< vtkUnstructuredGrid >
uint64_t nPoints () const
void clearGeom ()
vtkSmartPointer< dataType > getCopy () const
void reuse ()
void set (vtkSmartPointer< dataType > geom)
void PrintSelf (std::ostream &os) const
Public Member Functions inherited from foamVtkMeshMaps
foamVtkMeshMaps ()=default
const labelList & cellMap () const noexcept
DynamicList< label > & cellMap () noexcept
const labelList & pointMap () const noexcept
DynamicList< label > & pointMap () noexcept
const labelList & additionalIds () const noexcept
DynamicList< label > & additionalIds () noexcept
void clear ()
void renumberCells (const labelUList &mapping)
void renumberPoints (const labelUList &mapping)
Static Public Member Functions
template<class Type >
static vtkSmartPointer< vtkFloatArray > convertField (const DimensionedField< Type, volMesh > &fld, const vtuAdaptor &vtuData)
template<class Type >
static vtkSmartPointer< vtkFloatArray > convertField (const GeometricField< Type, fvPatchField, volMesh > &fld, const vtuAdaptor &vtuData)
Additional Inherited Members
Public Types inherited from Caching< vtkUnstructuredGrid >
typedef vtkUnstructuredGrid dataType
Public Attributes inherited from Caching< vtkUnstructuredGrid >
vtkSmartPointer< dataType > vtkgeom
vtkSmartPointer< dataType > dataset
Detailed Description
A low-level backend adaptor for converting OpenFOAM volume meshes/fields to VTK internal representation. The output is a single piece vtkUnstructuredGrid dataset. Multiblock composition is done by the caller.
Note
This was originally part of the catalystFvMesh function object backend, which was prototyped in the ParaView reader module. This adaptor unifies many common elements of both.
Source files
foamVtkVtuAdaptor.H
foamVtkVtuAdaptorI.H
foamVtkVtuAdaptorTemplates.C
Definition at line 71 of file foamVtkVtuAdaptor.H.
Member Function Documentation
points() [1/2]
vtkSmartPointer< vtkPoints > points (const fvMesh & mesh) const inline
Definition at line 24 of file foamVtkVtuAdaptorI.H.
References foamVtkMeshMaps::additionalIds(), mesh, p, pts, and UPtrList< T >::size().
points() [2/2]
vtkSmartPointer< vtkPoints > points (const fvMesh & mesh, const labelUList & pointMap) const inline
Definition at line 58 of file foamVtkVtuAdaptorI.H.
References mesh, pts, UPtrList< T >::size(), and UList< T >::size().
internal()
vtkSmartPointer< vtkUnstructuredGrid > internal (const fvMesh & mesh, const bool decompPoly = false) inline
Definition at line 93 of file foamVtkVtuAdaptorI.H.
References Foam::vtk::Tools::asUList(), cells, vtuSizing::CELLS, vtuSizing::CELLS_OFFSETS, cellTypes, vtuSizing::FACES, vtuSizing::FACES_OFFSETS, vtuSizing::INTERNAL1, vtuSizing::INTERNAL2, mesh, vtuSizing::nFieldCells(), Foam::output(), points, vtuSizing::populateInternal(), UPtrList< T >::size(), and vtuSizing::sizeOf().
convertField() [1/4]
template<class Type > vtkSmartPointer< vtkFloatArray > convertField (const DimensionedField< Type, volMesh > & fld, const vtuAdaptor & vtuData) static
Definition at line 31 of file foamVtkVtuAdaptorTemplates.C.
References foamVtkMeshMaps::cellMap(), fld(), Foam::vtk::Tools::foamToVtkTuple(), and UPtrList< T >::size().
convertField() [2/4]
template<class Type > vtkSmartPointer< vtkFloatArray > convertField (const GeometricField< Type, fvPatchField, volMesh > & fld, const vtuAdaptor & vtuData) static
Definition at line 68 of file foamVtkVtuAdaptorTemplates.C.
References fld().
convertField() [3/4]
template<class Type > vtkSmartPointer< vtkFloatArray > convertField (const DimensionedField< Type, volMesh > & fld) const
Definition at line 80 of file foamVtkVtuAdaptorTemplates.C.
References fld().
convertField() [4/4]
template<class Type > vtkSmartPointer< vtkFloatArray > convertField (const GeometricField< Type, fvPatchField, volMesh > & fld) const
Definition at line 91 of file foamVtkVtuAdaptorTemplates.C.
References fld().
The documentation for this class was generated from the following files:
src/conversion/vtk/adaptor/foamVtkVtuAdaptor.H
src/conversion/vtk/adaptor/foamVtkVtuAdaptorI.H
src/conversion/vtk/adaptor/foamVtkVtuAdaptorTemplates.C