OpenFOAM: equalBinWidth Class Reference
equalBinWidth Class Reference
Histogram model which groups data into bins of equal width.
#include <equalBinWidth.H>
Public Member Functions
TypeName ("equalBinWidth")
equalBinWidth (const word &name, const fvMesh &mesh, const dictionary &dict)
equalBinWidth (const equalBinWidth &)=delete
void operator= (const equalBinWidth &)=delete
virtual ~equalBinWidth ()=default
virtual bool read (const dictionary &dict)
virtual bool write (const bool log)
Public Member Functions inherited from histogramModel
TypeName ("histogramModel")
declareRunTimeSelectionTable (autoPtr, histogramModel, dictionary,(const word &name, const fvMesh &mesh, const dictionary &dict),(name, mesh, dict))
histogramModel (const word &name, const fvMesh &mesh, const dictionary &dict)
histogramModel (const histogramModel &)=delete
void operator= (const histogramModel &)=delete
virtual ~histogramModel ()=default
const fvMesh & mesh () const noexcept
const word & fieldName () const noexcept
Public Member Functions inherited from writeFile
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name="undefined", const bool writeToFile=true)
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name, const dictionary &dict, const bool writeToFile=true)
writeFile (const writeFile &wf)
virtual ~writeFile ()=default
virtual OFstream & file ()
virtual bool writeToFile () const
virtual bool canWriteToFile () const
virtual bool canResetFile () const
virtual bool canWriteHeader () const
virtual label charWidth () const
virtual void writeCommented (Ostream &os, const string &str) const
virtual void writeTabbed (Ostream &os, const string &str) const
virtual void writeHeader (Ostream &os, const string &str) const
virtual void writeCurrentTime (Ostream &os) const
virtual void writeBreak (Ostream &os) const
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
template<class Type >
void writeValue (Ostream &os, const Type &val) const
Additional Inherited Members
Static Public Member Functions inherited from histogramModel
static autoPtr< histogramModel > New (const word &name, const fvMesh &mesh, const dictionary &dict)
Static Public Attributes inherited from writeFile
static label addChars = 8
Protected Member Functions inherited from histogramModel
virtual void writeFileHeader (Ostream &os)
volScalarField & getOrReadField (const word &fieldName) const
void write (scalarField &dataNormalised, const labelField &dataCount, const scalarField &magMidBin)
Protected Member Functions inherited from writeFile
void initStream (Ostream &os) const
fileName baseFileDir () const
fileName baseTimeDir () const
fileName filePath (const fileName &fName) const
virtual autoPtr< OFstream > newFile (const fileName &fName) const
virtual autoPtr< OFstream > newFileAtTime (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > newFileAtStartTime (const word &name) const
virtual void resetFile (const word &name)
Omanip< int > valueWidth (const label offset=0) const
void operator= (const writeFile &)=delete
virtual autoPtr< OFstream > createFile (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > createFile (const word &name) const
Protected Attributes inherited from writeFile
const objectRegistry & fileObr_
const fileName prefix_
word fileName_
autoPtr< OFstream > filePtr_
label writePrecision_
bool writeToFile_
bool updateHeader_
bool writtenHeader_
bool useUserTime_
scalar startTime_
Detailed Description
Histogram model which groups data into bins of equal width.
Usage
Minimal example by using system/controlDict.functions:
histogram1
{
    // Inherited entries
    ...
    // Mandatory entries
    nBins       <label>;
    // Optional entries
    min         <scalar>;
    max         <scalar>;
}
where the entries mean:
Property Description Type Reqd Deflt
nBins Number of histogram bins label yes -
min Minimum value of histogram data scalar no -
max Maximum value of histogram data scalar no -
Note
If max is not provided, histogram will use operand field's min and max as the bin extremes.
If max is provided without min, histogram will use 0 for the min.
Source files
equalBinWidth.H
equalBinWidth.C
Definition at line 104 of file equalBinWidth.H.
Constructor & Destructor Documentation
equalBinWidth() [1/2]
equalBinWidth (const word & name, const fvMesh & mesh, const dictionary & dict)
Definition at line 40 of file equalBinWidth.C.
References dict, Foam::name(), and equalBinWidth::read().
equalBinWidth() [2/2]
equalBinWidth (const equalBinWidth &) delete
~equalBinWidth()
virtual ~equalBinWidth () virtual default
Member Function Documentation
TypeName()
TypeName ("equalBinWidth")
operator=()
void operator= (const equalBinWidth &) delete
read()
bool read (const dictionary & dict) virtual
Reimplemented from histogramModel.
Definition at line 57 of file equalBinWidth.C.
References Foam::abort(), dict, Foam::FatalIOError, FatalIOErrorInFunction, UPtrList< T >::get(), and histogramModel::read().
Referenced by equalBinWidth::equalBinWidth().
write()
bool write (const bool log) virtual
Implements histogramModel.
Definition at line 84 of file equalBinWidth.C.
References delta, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, field(), forAll, histogramModel::getOrReadField(), Foam::Info, Pstream::listCombineGather(), Foam::log(), Foam::mag(), Foam::max(), mesh, Foam::min(), p, histogramModel::write(), x, and Foam::Zero.
The documentation for this class was generated from the following files:
src/functionObjects/field/histogram/histogramModels/equalBinWidth/equalBinWidth.H
src/functionObjects/field/histogram/histogramModels/equalBinWidth/equalBinWidth.C