OpenFOAM: filmPyrolysisRadiativeCoupledMixedFvPatchScalarField Class Reference
filmPyrolysisRadiativeCoupledMixedFvPatchScalarField Class Reference
Mixed boundary condition for temperature, to be used in the flow and pyrolysis regions when a film region model is used.
#include <filmPyrolysisRadiativeCoupledMixedFvPatchScalarField.H>
Public Types
typedef Foam::regionModels::surfaceFilmModels::thermoSingleLayer filmModelType
typedef Foam::regionModels::pyrolysisModels::pyrolysisModel pyrolysisModelType
Public Types inherited from temperatureCoupledBase
enum KMethodType {
mtFluidThermo , mtSolidThermo , mtDirectionalSolidThermo , mtLookup ,
mtFunction
}
Public Member Functions
TypeName ("filmPyrolysisRadiativeCoupledMixed")
filmPyrolysisRadiativeCoupledMixedFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
filmPyrolysisRadiativeCoupledMixedFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
filmPyrolysisRadiativeCoupledMixedFvPatchScalarField (const filmPyrolysisRadiativeCoupledMixedFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
virtual tmp< fvPatchScalarField > clone () const
filmPyrolysisRadiativeCoupledMixedFvPatchScalarField (const filmPyrolysisRadiativeCoupledMixedFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual void autoMap (const fvPatchFieldMapper &)
virtual void rmap (const fvPatchField< scalar > &, const labelList &)
tmp< scalarField > K () const
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Public Member Functions inherited from temperatureCoupledBase
temperatureCoupledBase (const fvPatch &patch, const KMethodType method=KMethodType::mtFluidThermo)
temperatureCoupledBase (const fvPatch &patch, const KMethodType method, const word &kappaName, const word &alphaName, const word &alphaAniName)
temperatureCoupledBase (const fvPatch &patch, const dictionary &dict)
temperatureCoupledBase (const fvPatch &patch, const temperatureCoupledBase &base)
temperatureCoupledBase (const temperatureCoupledBase &base)
virtual ~temperatureCoupledBase ()=default
word KMethod () const
const word & kappaName () const noexcept
const word & alphaName () const noexcept
virtual tmp< scalarField > kappa (const scalarField &Tp) const
virtual tmp< scalarField > alpha (const scalarField &Tp) const
void write (Ostream &os) const
Additional Inherited Members
Protected Attributes inherited from temperatureCoupledBase
const fvPatch & patch_
const KMethodType method_
const word kappaName_
const word alphaName_
const word alphaAniName_
autoPtr< PatchFunction1< scalar > > kappaFunction1_
autoPtr< PatchFunction1< scalar > > alphaFunction1_
Static Protected Attributes inherited from temperatureCoupledBase
static const Enum< KMethodType > KMethodTypeNames_
Detailed Description
Mixed boundary condition for temperature, to be used in the flow and pyrolysis regions when a film region model is used.
Example usage:
myInterfacePatchName
{
    type            filmPyrolysisRadiativeCoupledMixed;
    Tnbr            T;
    kappaMethod     fluidThermo;
    kappa           none;
    qr              qr;
    filmDeltaDry    0.0;
    filmDeltaWet    3e-4;
    value           $internalField;
}
Needs to be on underlying mapped(Wall)FvPatch. It calculates local field as:
    ratio = (filmDelta - filmDeltaDry)/(filmDeltaWet - filmDeltaDry)
when ratio = 1 is considered wet and the film temperature is fixed at the wall. If ratio = 0 (dry) it emulates the normal radiative solid BC.
In between ratio 0 and 1 the gradient and value contributions are weighted using the ratio field in the following way:
    qConv = ratio*htcwfilm*(Tfilm - *this);
    qRad = (1.0 - ratio)*qr;
Then the solid can gain or loose energy through radiation or conduction towards the film.
Notes:
kappaMethod and kappa are inherited from temperatureCoupledBase.
qr is the radiative flux defined in the radiation model.
See also
Foam::temperatureCoupledBase
Source files
filmPyrolysisRadiativeCoupledMixedFvPatchScalarField.H
filmPyrolysisRadiativeCoupledMixedFvPatchScalarField.C
Definition at line 95 of file filmPyrolysisRadiativeCoupledMixedFvPatchScalarField.H.
Member Typedef Documentation
filmModelType
typedef Foam::regionModels::surfaceFilmModels::thermoSingleLayer filmModelType
Definition at line 103 of file filmPyrolysisRadiativeCoupledMixedFvPatchScalarField.H.
pyrolysisModelType
typedef Foam::regionModels::pyrolysisModels::pyrolysisModel pyrolysisModelType
Definition at line 106 of file filmPyrolysisRadiativeCoupledMixedFvPatchScalarField.H.
Constructor & Destructor Documentation
filmPyrolysisRadiativeCoupledMixedFvPatchScalarField() [1/4]
filmPyrolysisRadiativeCoupledMixedFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 96 of file filmPyrolysisRadiativeCoupledMixedFvPatchScalarField.C.
filmPyrolysisRadiativeCoupledMixedFvPatchScalarField() [2/4]
filmPyrolysisRadiativeCoupledMixedFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 140 of file filmPyrolysisRadiativeCoupledMixedFvPatchScalarField.C.
References dict, Foam::exit(), Foam::FatalError, FatalErrorInFunction, IOobjectOption::MUST_READ, and p.
filmPyrolysisRadiativeCoupledMixedFvPatchScalarField() [3/4]
filmPyrolysisRadiativeCoupledMixedFvPatchScalarField (const filmPyrolysisRadiativeCoupledMixedFvPatchScalarField & psf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 119 of file filmPyrolysisRadiativeCoupledMixedFvPatchScalarField.C.
filmPyrolysisRadiativeCoupledMixedFvPatchScalarField() [4/4]
filmPyrolysisRadiativeCoupledMixedFvPatchScalarField (const filmPyrolysisRadiativeCoupledMixedFvPatchScalarField & psf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 190 of file filmPyrolysisRadiativeCoupledMixedFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("filmPyrolysisRadiativeCoupledMixed")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 177 of file filmPyrolysisRadiativeCoupledMixedFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 196 of file filmPyrolysisRadiativeCoupledMixedFvPatchScalarField.H.
autoMap()
void autoMap (const fvPatchFieldMapper & mapper) virtual
Implements temperatureCoupledBase.
Definition at line 211 of file filmPyrolysisRadiativeCoupledMixedFvPatchScalarField.C.
References temperatureCoupledBase::autoMap().
rmap()
void rmap (const fvPatchField< scalar > & ptf, const labelList & addr) virtual
Implements temperatureCoupledBase.
Definition at line 221 of file filmPyrolysisRadiativeCoupledMixedFvPatchScalarField.C.
References Foam::refCast(), and temperatureCoupledBase::rmap().
K()
tmp< scalarField > K () const
Referenced by filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::updateCoeffs().
updateCoeffs()
void updateCoeffs () virtual
Definition at line 239 of file filmPyrolysisRadiativeCoupledMixedFvPatchScalarField.C.
References alpha, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::gAverage(), Foam::gMax(), Foam::gMin(), Foam::gSum(), thermoSingleLayer::htcw(), Foam::Info, filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::K(), temperatureCoupledBase::kappa(), Foam::max(), mesh, Foam::min(), Foam::nl, Foam::refCast(), regionModel::toPrimary(), thermoSingleLayer::Ts(), Foam::type(), and Foam::Zero.
write()
void write (Ostream & os) const virtual
Definition at line 400 of file filmPyrolysisRadiativeCoupledMixedFvPatchScalarField.C.
References os(), mixedFvPatchField< Type >::write(), and temperatureCoupledBase::write().
The documentation for this class was generated from the following files:
src/regionModels/regionCoupling/derivedFvPatchFields/filmPyrolysisRadiativeCoupledMixed/filmPyrolysisRadiativeCoupledMixedFvPatchScalarField.H
src/regionModels/regionCoupling/derivedFvPatchFields/filmPyrolysisRadiativeCoupledMixed/filmPyrolysisRadiativeCoupledMixedFvPatchScalarField.C