OpenFOAM: OneResistanceHeatTransferPhaseSystem< BasePhaseSystem > Class Template Reference
OneResistanceHeatTransferPhaseSystem< BasePhaseSystem > Class Template Reference
Class which models interfacial heat transfer between a number of phases. A single heat transfer model is used for each interface.
#include <OneResistanceHeatTransferPhaseSystem.H>
Public Member Functions
OneResistanceHeatTransferPhaseSystem (const fvMesh &)
virtual ~OneResistanceHeatTransferPhaseSystem ()
virtual autoPtr< phaseSystem::heatTransferTable > heatTransfer () const
virtual bool read ()
Protected Types
typedef HashTable< autoPtr< BlendedInterfacialModel< heatTransferModel > >, phasePairKey, phasePairKey::hash > heatTransferModelTable
Protected Attributes
heatTransferModelTable heatTransferModels_
Detailed Description
template<class BasePhaseSystem>
class Foam::OneResistanceHeatTransferPhaseSystem< BasePhaseSystem >
Class which models interfacial heat transfer between a number of phases. A single heat transfer model is used for each interface.
See also
TwoResistanceHeatTransferPhaseSystem
Source files
OneResistanceHeatTransferPhaseSystem.H
OneResistanceHeatTransferPhaseSystem.C
Definition at line 55 of file OneResistanceHeatTransferPhaseSystem.H.
Member Typedef Documentation
heatTransferModelTable
template<class BasePhaseSystem > typedef HashTable< autoPtr<BlendedInterfacialModel<heatTransferModel> >, phasePairKey, phasePairKey::hash > heatTransferModelTable protected
Definition at line 68 of file OneResistanceHeatTransferPhaseSystem.H.
Constructor & Destructor Documentation
OneResistanceHeatTransferPhaseSystem()
template<class BasePhaseSystem > OneResistanceHeatTransferPhaseSystem (const fvMesh & mesh)
Definition at line 27 of file OneResistanceHeatTransferPhaseSystem.C.
References OneResistanceHeatTransferPhaseSystem< BasePhaseSystem >::heatTransferModels_.
~OneResistanceHeatTransferPhaseSystem()
template<class BasePhaseSystem > ~OneResistanceHeatTransferPhaseSystem () virtual
Definition at line 47 of file OneResistanceHeatTransferPhaseSystem.C.
Member Function Documentation
heatTransfer()
template<class BasePhaseSystem > Foam::autoPtr< Foam::phaseSystem::heatTransferTable > heatTransfer () const virtual
Definition at line 56 of file OneResistanceHeatTransferPhaseSystem.C.
References Foam::dimEnergy, Foam::dimTime, forAll, forAllConstIter, he, he2, phaseModel::K(), K1, K2, phase::name(), phaseModel::name(), Foam::negPart(), phasePairKey::ordered(), phaseModel::otherPhase(), phase1, phasePair::phase1(), phase2, phasePair::phase2(), phasei, Foam::posPart(), PtrList< T >::set(), Foam::fvm::Sp(), GeometricField< Type, PatchField, GeoMesh >::T(), and phaseModel::thermo().
read()
template<class BasePhaseSystem > bool read () virtual
Definition at line 147 of file OneResistanceHeatTransferPhaseSystem.C.
Member Data Documentation
heatTransferModels_
template<class BasePhaseSystem > heatTransferModelTable heatTransferModels_ protected
Definition at line 76 of file OneResistanceHeatTransferPhaseSystem.H.
Referenced by OneResistanceHeatTransferPhaseSystem< BasePhaseSystem >::OneResistanceHeatTransferPhaseSystem().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/PhaseSystems/OneResistanceHeatTransferPhaseSystem/OneResistanceHeatTransferPhaseSystem.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/PhaseSystems/OneResistanceHeatTransferPhaseSystem/OneResistanceHeatTransferPhaseSystem.C