OpenFOAM: Cole Class Reference
Cole Class Reference
A correlation for bubble departure frequency modelling based on Cole (1960) for boiling flows.
#include <Cole.H>
Public Member Functions
TypeName ("Cole")
Cole (const dictionary &dict)
virtual ~Cole ()=default
virtual tmp< scalarField > fDeparture (const phaseModel &liquid, const phaseModel &vapor, const label patchi, const scalarField &dDep) const
Public Member Functions inherited from departureFrequencyModel
TypeName ("departureFrequencyModel")
declareRunTimeSelectionTable (autoPtr, departureFrequencyModel, dictionary,(const dictionary &dict),(dict))
departureFrequencyModel ()=default
virtual ~departureFrequencyModel ()=default
virtual void write (Ostream &os) const
Additional Inherited Members
Static Public Member Functions inherited from departureFrequencyModel
static autoPtr< departureFrequencyModel > New (const dictionary &dict)
Detailed Description
A correlation for bubble departure frequency modelling based on Cole (1960) for boiling flows.
Reference:
    Cole, R. (1960).
    A photographic study of pool boiling
    in the region of the critical heat flux.
    AIChE Journal, 6(4), 533-538.
    DOI:10.1002/aic.690060405
Usage
Example of the model specification:
departureFrequencyModel
{
    // Mandatory entries
    type            Cole;
}
where the entries mean:
Property Description Type Reqd Deflt
type Type name: Cole word yes -
Source files
Cole.H
Cole.C
Definition at line 89 of file Cole.H.
Constructor & Destructor Documentation
Cole()
Cole (const dictionary & dict)
Definition at line 51 of file Cole.C.
~Cole()
virtual ~Cole () virtual default
Member Function Documentation
TypeName()
TypeName ("Cole")
fDeparture()
Foam::tmp< Foam::scalarField > fDeparture (const phaseModel & liquid, const phaseModel & vapor, const label patchi, const scalarField & dDep) const virtual
Implements departureFrequencyModel.
Definition at line 61 of file Cole.C.
References g, Foam::mag(), Foam::max(), liquid::rho(), and Foam::sqrt().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/wallBoilingSubModels/departureFrequencyModels/Cole/Cole.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/wallBoilingSubModels/departureFrequencyModels/Cole/Cole.C