OpenFOAM: SingleMixtureFraction< CloudType > Class Template Reference
SingleMixtureFraction< CloudType > Class Template Reference
Lagrangian particle models » Submodels » Reacting » Composition
Templated parcel multi-phase, multi-component class.
#include <SingleMixtureFraction.H>
Public Member Functions
TypeName ("singleMixtureFraction")
SingleMixtureFraction (const dictionary &dict, CloudType &owner)
SingleMixtureFraction (const SingleMixtureFraction< CloudType > &cm)
virtual autoPtr< CompositionModel< CloudType > > clone () const
virtual ~SingleMixtureFraction ()
virtual const scalarField & YMixture0 () const
virtual label idGas () const
virtual label idLiquid () const
virtual label idSolid () const
Public Member Functions inherited from CompositionModel< CloudType >
TypeName ("compositionModel")
declareRunTimeSelectionTable (autoPtr, CompositionModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
CompositionModel (CloudType &owner)
CompositionModel (const dictionary &dict, CloudType &owner, const word &type)
CompositionModel (const CompositionModel< CloudType > &cm)
virtual ~CompositionModel ()
const SLGThermo & thermo () const
const basicSpecieMixture & carrier () const
const liquidMixtureProperties & liquids () const
const solidMixtureProperties & solids () const
const phasePropertiesList & phaseProps () const
label nPhase () const
const wordList & phaseTypes () const
const wordList & stateLabels () const
const wordList & componentNames (const label phaseI) const
label carrierId (const word &cmptName, const bool allowNotFound=false) const
label localId (const label phaseI, const word &cmptName, const bool allowNotFound=false) const
label localToCarrierId (const label phaseI, const label id, const bool allowNotFound=false) const
const scalarField & Y0 (const label phaseI) const
tmp< scalarField > X (const label phaseI, const scalarField &Y) const
virtual scalar H (const label phaseI, const scalarField &Y, const scalar p, const scalar T) const
virtual scalar Hs (const label phaseI, const scalarField &Y, const scalar p, const scalar T) const
virtual scalar Hc (const label phaseI, const scalarField &Y, const scalar p, const scalar T) const
virtual scalar Cp (const label phaseI, const scalarField &Y, const scalar p, const scalar T) const
virtual scalar L (const label phaseI, const scalarField &Y, const scalar p, const scalar T) const
virtual scalar rho (const scalarField &Ygas, const scalarField &Yliq, const scalarField &Ysol, const scalar T, const scalar p) const
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
virtual ~CloudSubModelBase ()=default
const CloudType & owner () const
virtual bool writeTime () const
virtual fileName localPath () const
CloudType & owner ()
virtual void info ()
virtual void write (Ostream &os) const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
subModelBase (const subModelBase &smb)
virtual ~subModelBase ()=default
const word & modelName () const
const dictionary & dict () const
const word & baseName () const
const word & modelType () const
const dictionary & coeffDict () const
const dictionary & properties () const
virtual bool defaultCoeffs (const bool printMsg) const
virtual bool active () const
virtual void cacheFields (const bool store)
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
bool getModelDict (const word &entryName, dictionary &dict) const
template<class Type >
bool getModelProperty (const word &entryName, Type &value) const
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Additional Inherited Members
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Static Public Member Functions inherited from CompositionModel< CloudType >
static autoPtr< CompositionModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Public Attributes inherited from subModelBase
bool log
Protected Member Functions inherited from subModelBase
bool inLine () const
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Protected Attributes inherited from subModelBase
const word modelName_
dictionary & properties_
const dictionary dict_
const word baseName_
const word modelType_
const dictionary coeffDict_
Detailed Description
template<class CloudType>
class Foam::SingleMixtureFraction< CloudType >
Templated parcel multi-phase, multi-component class.
Source files
SingleMixtureFraction.H
SingleMixtureFraction.C
Definition at line 50 of file SingleMixtureFraction.H.
Constructor & Destructor Documentation
SingleMixtureFraction() [1/2]
template<class CloudType > SingleMixtureFraction (const dictionary & dict, CloudType & owner)
Definition at line 79 of file SingleMixtureFraction.C.
References subModelBase::coeffDict(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::mag(), Foam::nl, CompositionModel< CloudType >::phaseProps(), and Foam::sum().
SingleMixtureFraction() [2/2]
template<class CloudType > SingleMixtureFraction (const SingleMixtureFraction< CloudType > & cm)
Definition at line 117 of file SingleMixtureFraction.C.
~SingleMixtureFraction()
template<class CloudType > ~SingleMixtureFraction () virtual
Definition at line 133 of file SingleMixtureFraction.C.
Member Function Documentation
TypeName()
template<class CloudType > TypeName ("singleMixtureFraction")
clone()
template<class CloudType > virtual autoPtr< CompositionModel< CloudType > > clone () const inline virtual
Implements CompositionModel< CloudType >.
Definition at line 96 of file SingleMixtureFraction.H.
YMixture0()
template<class CloudType > const Foam::scalarField & YMixture0 () const virtual
Implements CompositionModel< CloudType >.
Definition at line 141 of file SingleMixtureFraction.C.
idGas()
template<class CloudType > Foam::label idGas () const virtual
Implements CompositionModel< CloudType >.
Definition at line 148 of file SingleMixtureFraction.C.
idLiquid()
template<class CloudType > Foam::label idLiquid () const virtual
Implements CompositionModel< CloudType >.
Definition at line 155 of file SingleMixtureFraction.C.
idSolid()
template<class CloudType > Foam::label idSolid () const virtual
Implements CompositionModel< CloudType >.
Definition at line 162 of file SingleMixtureFraction.C.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/Reacting/CompositionModel/SingleMixtureFraction/SingleMixtureFraction.H
src/lagrangian/intermediate/submodels/Reacting/CompositionModel/SingleMixtureFraction/SingleMixtureFraction.C