OpenFOAM: indexedFace< Gt, Fb > Class Template Reference
indexedFace< Gt, Fb > Class Template Reference
An indexed form of CGAL::Triangulation_face_base_2<K> used to keep track of the vertices in the triangulation.
#include <indexedFace.H>
Classes
struct Rebind_TDS
Public Types
enum faceTypes { UNCHANGED = 0 , CHANGED = -1 , SAVE_CHANGED = -2 }
typedef Fb::Vertex_handle Vertex_handle
typedef Fb::Face_handle Face_handle
Public Member Functions
indexedFace ()
indexedFace (Vertex_handle v0, Vertex_handle v1, Vertex_handle v2)
indexedFace (Vertex_handle v0, Vertex_handle v1, Vertex_handle v2, Face_handle n0, Face_handle n1, Face_handle n2)
void set_vertex (int i, Vertex_handle v)
void set_vertices ()
void set_vertices (Vertex_handle v0, Vertex_handle v1, Vertex_handle v2)
int & faceIndex ()
int faceIndex () const
Detailed Description
template<class Gt, class Fb = CGAL::Triangulation_face_base_2<Gt>>
class CGAL::indexedFace< Gt, Fb >
An indexed form of CGAL::Triangulation_face_base_2<K> used to keep track of the vertices in the triangulation.
Definition at line 43 of file indexedFace.H.
Member Typedef Documentation
Vertex_handle
template<class Gt , class Fb = CGAL::Triangulation_face_base_2<Gt>> typedef Fb::Vertex_handle Vertex_handle
Definition at line 64 of file indexedFace.H.
Face_handle
template<class Gt , class Fb = CGAL::Triangulation_face_base_2<Gt>> typedef Fb::Face_handle Face_handle
Definition at line 65 of file indexedFace.H.
Member Enumeration Documentation
faceTypes
template<class Gt , class Fb = CGAL::Triangulation_face_base_2<Gt>> enum faceTypes
Enumerator
UNCHANGED
CHANGED
SAVE_CHANGED
Definition at line 57 of file indexedFace.H.
Constructor & Destructor Documentation
indexedFace() [1/3]
template<class Gt , class Fb > indexedFace () inline
Definition at line 24 of file indexedFaceI.H.
indexedFace() [2/3]
template<class Gt , class Fb > indexedFace (Vertex_handle v0, Vertex_handle v1, Vertex_handle v2) inline
Definition at line 32 of file indexedFaceI.H.
indexedFace() [3/3]
template<class Gt , class Fb > indexedFace (Vertex_handle v0, Vertex_handle v1, Vertex_handle v2, Face_handle n0, Face_handle n1, Face_handle n2) inline
Definition at line 45 of file indexedFaceI.H.
Member Function Documentation
set_vertex()
template<class Gt , class Fb > void set_vertex (int i, Vertex_handle v) inline
Definition at line 63 of file indexedFaceI.H.
References indexedFace< Gt, Fb >::set_vertex().
Referenced by indexedFace< Gt, Fb >::set_vertex().
set_vertices() [1/2]
template<class Gt , class Fb > void set_vertices () inline
Definition at line 71 of file indexedFaceI.H.
References indexedFace< Gt, Fb >::set_vertices().
Referenced by indexedFace< Gt, Fb >::set_vertices(), and indexedFace< Gt, Fb >::set_vertices().
set_vertices() [2/2]
template<class Gt , class Fb > void set_vertices (Vertex_handle v0, Vertex_handle v1, Vertex_handle v2) inline
Definition at line 79 of file indexedFaceI.H.
References indexedFace< Gt, Fb >::set_vertices().
faceIndex() [1/2]
template<class Gt , class Fb > int & faceIndex () inline
Definition at line 92 of file indexedFaceI.H.
faceIndex() [2/2]
template<class Gt , class Fb > int faceIndex () const inline
Definition at line 99 of file indexedFaceI.H.
The documentation for this class was generated from the following files:
applications/utilities/mesh/generation/foamyMesh/foamyQuadMesh/indexedFace.H
applications/utilities/mesh/generation/foamyMesh/foamyQuadMesh/indexedFaceI.H