OpenFOAM: generalizedNewtonian< BasicMomentumTransportModel > Class Template Reference
generalizedNewtonian< BasicMomentumTransportModel > Class Template Reference
Turbulence model for shear-dependent Non-Newtonian flow.
#include <generalizedNewtonian.H>
Public Types
typedef BasicMomentumTransportModel::alphaField alphaField
typedef BasicMomentumTransportModel::rhoField rhoField
typedef BasicMomentumTransportModel::transportModel transportModel
Public Types inherited from linearViscousStress< laminarModel< BasicMomentumTransportModel > >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from laminarModel< BasicMomentumTransportModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("generalizedNewtonian")
generalizedNewtonian (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~generalizedNewtonian ()=default
virtual bool read ()
virtual tmp< volScalarField > nut () const
virtual tmp< scalarField > nut (const label patchi) const
virtual tmp< volScalarField > nuEff () const
virtual tmp< scalarField > nuEff (const label patchi) const
virtual void correct ()
Public Member Functions inherited from linearViscousStress< laminarModel< BasicMomentumTransportModel > >
linearViscousStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~linearViscousStress ()=default
virtual tmp< volSymmTensorField > devRhoReff () const
virtual tmp< volSymmTensorField > devRhoReff (const volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Public Member Functions inherited from laminarModel< BasicMomentumTransportModel >
laminarModel (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
TypeName ("laminar")
declareRunTimeSelectionTable (autoPtr, laminarModel, dictionary,(const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName),(alpha, rho, U, alphaRhoPhi, phi, transport, propertiesName))
virtual ~laminarModel ()=default
virtual const dictionary & coeffDict () const
virtual tmp< volScalarField > k () const
virtual tmp< volScalarField > epsilon () const
virtual tmp< volScalarField > omega () const
virtual tmp< volSymmTensorField > R () const
Static Public Member Functions
static autoPtr< generalizedNewtonian > New (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Static Public Member Functions inherited from laminarModel< BasicMomentumTransportModel >
static autoPtr< laminarModel > New (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Protected Member Functions
virtual tmp< volScalarField > strainRate () const
Protected Member Functions inherited from laminarModel< BasicMomentumTransportModel >
virtual void printCoeffs (const word &type)
laminarModel (const laminarModel &)=delete
void operator= (const laminarModel &)=delete
Protected Attributes
autoPtr< generalizedNewtonianViscosityModel > viscosityModel_
volScalarField nu_
Protected Attributes inherited from laminarModel< BasicMomentumTransportModel >
dictionary laminarDict_
Switch printCoeffs_
dictionary coeffDict_
Detailed Description
template<class BasicMomentumTransportModel>
class Foam::laminarModels::generalizedNewtonian< BasicMomentumTransportModel >
Turbulence model for shear-dependent Non-Newtonian flow.
Source files
generalizedNewtonian.H
generalizedNewtonian.C
Definition at line 52 of file generalizedNewtonian.H.
Member Typedef Documentation
alphaField
template<class BasicMomentumTransportModel > typedef BasicMomentumTransportModel::alphaField alphaField
Definition at line 74 of file generalizedNewtonian.H.
rhoField
template<class BasicMomentumTransportModel > typedef BasicMomentumTransportModel::rhoField rhoField
Definition at line 75 of file generalizedNewtonian.H.
transportModel
template<class BasicMomentumTransportModel > typedef BasicMomentumTransportModel::transportModel transportModel
Definition at line 76 of file generalizedNewtonian.H.
Constructor & Destructor Documentation
generalizedNewtonian()
template<class BasicMomentumTransportModel > generalizedNewtonian (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName)
Definition at line 39 of file generalizedNewtonian.C.
~generalizedNewtonian()
template<class BasicMomentumTransportModel > virtual ~generalizedNewtonian () virtual default
Member Function Documentation
strainRate()
template<class BasicMomentumTransportModel > Foam::tmp< Foam::volScalarField > strainRate () const protected virtual
Definition at line 89 of file generalizedNewtonian.C.
References Foam::fvc::grad(), Foam::mag(), Foam::sqrt(), Foam::symm(), and U.
TypeName()
template<class BasicMomentumTransportModel > TypeName ("generalizedNewtonian< BasicMomentumTransportModel >")
New()
template<class BasicMomentumTransportModel > static autoPtr< generalizedNewtonian > New (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName) static
read()
template<class BasicMomentumTransportModel > bool read () virtual
Implements linearViscousStress< laminarModel< BasicMomentumTransportModel > >.
Definition at line 98 of file generalizedNewtonian.C.
nut() [1/2]
template<class BasicMomentumTransportModel > tmp< volScalarField > nut () const virtual
Reimplemented from laminarModel< BasicMomentumTransportModel >.
Definition at line 108 of file generalizedNewtonian.C.
References Foam::dimViscosity, IOobject::groupName(), GeometricField< scalar, fvPatchField, volMesh >::New(), and Foam::Zero.
nut() [2/2]
template<class BasicMomentumTransportModel > tmp< scalarField > nut (const label patchi) const virtual
Reimplemented from laminarModel< BasicMomentumTransportModel >.
Definition at line 121 of file generalizedNewtonian.C.
References tmp< T >::New(), and Foam::Zero.
nuEff() [1/2]
template<class BasicMomentumTransportModel > tmp< volScalarField > nuEff () const virtual
Reimplemented from laminarModel< BasicMomentumTransportModel >.
Definition at line 132 of file generalizedNewtonian.C.
References IOobject::groupName(), and GeometricField< scalar, fvPatchField, volMesh >::New().
nuEff() [2/2]
template<class BasicMomentumTransportModel > tmp< scalarField > nuEff (const label patchi) const virtual
Reimplemented from laminarModel< BasicMomentumTransportModel >.
Definition at line 144 of file generalizedNewtonian.C.
correct()
template<class BasicMomentumTransportModel > void correct () virtual
Implements linearViscousStress< laminarModel< BasicMomentumTransportModel > >.
Definition at line 154 of file generalizedNewtonian.C.
References laminarModel< BasicTurbulenceModel >::correct(), and nu.
Member Data Documentation
viscosityModel_
template<class BasicMomentumTransportModel > autoPtr<generalizedNewtonianViscosityModel> viscosityModel_ protected
Definition at line 61 of file generalizedNewtonian.H.
nu_
template<class BasicMomentumTransportModel > volScalarField nu_ protected
Definition at line 64 of file generalizedNewtonian.H.
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/laminar/generalizedNewtonian/generalizedNewtonian.H
src/TurbulenceModels/turbulenceModels/laminar/generalizedNewtonian/generalizedNewtonian.C