OpenFOAM: kOmegaSST< BasicTurbulenceModel > Class Template Reference
kOmegaSST< BasicTurbulenceModel > Class Template Reference
Turbulence models » RAS turbulence
Implementation of the k-omega-SST turbulence model for incompressible and compressible flows.
#include <kOmegaSST.H>
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from kOmegaSSTBase< eddyViscosity< RASModel< BasicTurbulenceModel > > >
typedef BasicEddyViscosityModel::alphaField alphaField
typedef BasicEddyViscosityModel::rhoField rhoField
typedef BasicEddyViscosityModel::transportModel transportModel
Public Types inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from linearViscousStress< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("kOmegaSST")
kOmegaSST (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
virtual ~kOmegaSST ()=default
Public Member Functions inherited from kOmegaSSTBase< eddyViscosity< RASModel< BasicTurbulenceModel > > >
kOmegaSSTBase (const kOmegaSSTBase &)=delete
kOmegaSSTBase (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
void operator= (const kOmegaSSTBase &)=delete
virtual ~kOmegaSSTBase ()=default
virtual bool read ()
tmp< volScalarField > DkEff (const volScalarField &F1) const
tmp< volScalarField > DomegaEff (const volScalarField &F1) const
virtual tmp< volScalarField > k () const
virtual tmp< volScalarField > omega () const
virtual void correct ()
Public Member Functions inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
eddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~eddyViscosity ()=default
virtual tmp< volScalarField > nut () const
virtual tmp< scalarField > nut (const label patchi) const
virtual tmp< volSymmTensorField > R () const
virtual void validate ()
Public Member Functions inherited from linearViscousStress< BasicTurbulenceModel >
linearViscousStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~linearViscousStress ()=default
virtual tmp< volSymmTensorField > devRhoReff () const
virtual tmp< volSymmTensorField > devRhoReff (const volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Protected Member Functions
virtual void correctNut (const volScalarField &S2)
virtual void correctNut ()
Protected Member Functions inherited from kOmegaSSTBase< eddyViscosity< RASModel< BasicTurbulenceModel > > >
void setDecayControl (const dictionary &dict)
virtual tmp< volScalarField > F1 (const volScalarField &CDkOmega) const
virtual tmp< volScalarField > F2 () const
virtual tmp< volScalarField > F3 () const
virtual tmp< volScalarField > F23 () const
tmp< volScalarField > blend (const volScalarField &F1, const dimensionedScalar &psi1, const dimensionedScalar &psi2) const
tmp< volScalarField::Internal > blend (const volScalarField::Internal &F1, const dimensionedScalar &psi1, const dimensionedScalar &psi2) const
tmp< volScalarField > alphaK (const volScalarField &F1) const
tmp< volScalarField > alphaOmega (const volScalarField &F1) const
tmp< volScalarField::Internal > beta (const volScalarField::Internal &F1) const
tmp< volScalarField::Internal > gamma (const volScalarField::Internal &F1) const
virtual tmp< volScalarField > S2 (const volTensorField &gradU) const
virtual tmp< volScalarField::Internal > Pk (const volScalarField::Internal &G) const
virtual tmp< volScalarField::Internal > epsilonByk (const volScalarField &F1, const volTensorField &gradU) const
virtual tmp< volScalarField::Internal > GbyNu0 (const volTensorField &gradU, const volScalarField &S2) const
virtual tmp< volScalarField::Internal > GbyNu (const volScalarField::Internal &GbyNu0, const volScalarField::Internal &F2, const volScalarField::Internal &S2) const
virtual tmp< fvScalarMatrix > kSource () const
virtual tmp< fvScalarMatrix > omegaSource () const
virtual tmp< fvScalarMatrix > Qsas (const volScalarField::Internal &S2, const volScalarField::Internal &gamma, const volScalarField::Internal &beta) const
Additional Inherited Members
Protected Attributes inherited from kOmegaSSTBase< eddyViscosity< RASModel< BasicTurbulenceModel > > >
dimensionedScalar alphaK1_
dimensionedScalar alphaK2_
dimensionedScalar alphaOmega1_
dimensionedScalar alphaOmega2_
dimensionedScalar gamma1_
dimensionedScalar gamma2_
dimensionedScalar beta1_
dimensionedScalar beta2_
dimensionedScalar betaStar_
dimensionedScalar a1_
dimensionedScalar b1_
dimensionedScalar c1_
Switch F3_
const volScalarField & y_
volScalarField k_
volScalarField omega_
Switch decayControl_
dimensionedScalar kInf_
dimensionedScalar omegaInf_
Protected Attributes inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
volScalarField nut_
Detailed Description
template<class BasicTurbulenceModel>
class Foam::RASModels::kOmegaSST< BasicTurbulenceModel >
Implementation of the k-omega-SST turbulence model for incompressible and compressible flows.
Light wrapper around base class.
Turbulence model described in:
    Menter, F. R. & Esch, T. (2001).
    Elements of Industrial Heat Transfer Prediction.
    16th Brazilian Congress of Mechanical Engineering (COBEM).
with updated coefficients from
    Menter, F. R., Kuntz, M., and Langtry, R. (2003).
    Ten Years of Industrial Experience with the SST Turbulence Model.
    Turbulence, Heat and Mass Transfer 4, ed: K. Hanjalic, Y. Nagano,
    & M. Tummers, Begell House, Inc., 625 - 632.
but with the consistent production terms from the 2001 paper as form in the 2003 paper is a typo, see
    http://turbmodels.larc.nasa.gov/sst.html
and the addition of the optional F3 term for rough walls from
    Hellsten, A. (1998).
    "Some Improvements in Menters k-omega-SST turbulence model"
    29th AIAA Fluid Dynamics Conference, AIAA-98-2554.
Note that this implementation is written in terms of alpha diffusion coefficients rather than the more traditional sigma (alpha = 1/sigma) so that the blending can be applied to all coefficuients in a consistent manner. The paper suggests that sigma is blended but this would not be consistent with the blending of the k-epsilon and k-omega models.
Also note that the error in the last term of equation (2) relating to sigma has been corrected.
Wall-functions are applied in this implementation by using equations (14) to specify the near-wall omega as appropriate.
The blending functions (15) and (16) are not currently used because of the uncertainty in their origin, range of applicability and that if y+ becomes sufficiently small blending u_tau in this manner clearly becomes nonsense.
The default model coefficients are
    kOmegaSSTCoeffs
    {
        alphaK1     0.85;
        alphaK2     1.0;
        alphaOmega1 0.5;
        alphaOmega2 0.856;
        beta1       0.075;
        beta2       0.0828;
        betaStar    0.09;
        gamma1      5/9;
        gamma2      0.44;
        a1          0.31;
        b1          1.0;
        c1          10.0;
        F3          no;
    }
Source files
kOmegaSST.H
kOmegaSST.C
See also
kOmegaSSTBase.H
Definition at line 125 of file kOmegaSST.H.
Member Typedef Documentation
alphaField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 148 of file kOmegaSST.H.
rhoField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 149 of file kOmegaSST.H.
transportModel
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 150 of file kOmegaSST.H.
Constructor & Destructor Documentation
kOmegaSST()
template<class BasicTurbulenceModel > kOmegaSST (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Definition at line 56 of file kOmegaSST.C.
References Foam::type().
~kOmegaSST()
template<class BasicTurbulenceModel > virtual ~kOmegaSST () virtual default
Member Function Documentation
correctNut() [1/2]
template<class BasicTurbulenceModel > void correctNut (const volScalarField & S2) protected virtual
Reimplemented from kOmegaSSTBase< eddyViscosity< RASModel< BasicTurbulenceModel > > >.
Reimplemented in kOmegaSSTSato< BasicTurbulenceModel >.
Definition at line 33 of file kOmegaSST.C.
correctNut() [2/2]
template<class BasicTurbulenceModel > void correctNut () protected virtual
Reimplemented from kOmegaSSTBase< eddyViscosity< RASModel< BasicTurbulenceModel > > >.
Definition at line 47 of file kOmegaSST.C.
References Foam::fvc::grad(), Foam::magSqr(), and Foam::symm().
Referenced by kOmegaSSTSAS< BasicTurbulenceModel >::kOmegaSSTSAS().
TypeName()
template<class BasicTurbulenceModel > TypeName ("kOmegaSST< BasicTurbulenceModel >")
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/RAS/kOmegaSST/kOmegaSST.H
src/TurbulenceModels/turbulenceModels/RAS/kOmegaSST/kOmegaSST.C