OpenFOAM: fvMeshSubset Class Reference
fvMeshSubset Class Reference
Holds a reference to the original mesh (the baseMesh) and optionally to a subset of that mesh (the subMesh) with mapping lists for points, faces, and cells.
#include <fvMeshSubset.H>
Public Member Functions
fvMeshSubset (const fvMesh &baseMesh)
fvMeshSubset (const fvMesh &baseMesh, const Foam::zero)
fvMeshSubset (const fvMesh &baseMesh, const bitSet &selectedCells, const label patchID=-1, const bool syncPar=true)
fvMeshSubset (const fvMesh &baseMesh, const labelUList &selectedCells, const label patchID=-1, const bool syncPar=true)
fvMeshSubset (const fvMesh &baseMesh, const labelHashSet &selectedCells, const label patchID=-1, const bool syncPar=true)
fvMeshSubset (const fvMesh &baseMesh, const label regioni, const labelUList &regions, const label patchID=-1, const bool syncPar=true)
const fvMesh & baseMesh () const noexcept
const fvMesh & mesh () const noexcept
bool hasSubMesh () const noexcept
const fvMesh & subMesh () const
fvMesh & subMesh ()
const labelList & pointMap () const
const labelList & faceMap () const
const labelList & faceFlipMap () const
const labelList & cellMap () const
const labelList & patchMap () const
void clear ()
void reset ()
void reset (const Foam::zero)
void reset (autoPtr< fvMesh > &&subMeshPtr, labelList &&pointMap, labelList &&faceMap, labelList &&cellMap, labelList &&patchMap)
void reset (const bitSet &selectedCells, const label patchID=-1, const bool syncPar=true)
void reset (const labelUList &selectedCells, const label patchID=-1, const bool syncPar=true)
void reset (const labelHashSet &selectedCells, const label patchID=-1, const bool syncPar=true)
void reset (const label regioni, const labelUList &regions, const label patchID=-1, const bool syncCouples=true)
void setCellSubset (const bitSet &selectedCells, const label patchID=-1, const bool syncPar=true)
void setCellSubset (const labelUList &selectedCells, const label patchID=-1, const bool syncPar=true)
void setCellSubset (const labelHashSet &selectedCells, const label patchID=-1, const bool syncPar=true)
void setCellSubset (const label regioni, const labelUList &regions, const label patchID=-1, const bool syncPar=true)
template<class Type >
tmp< DimensionedField< Type, volMesh > > interpolate (const DimensionedField< Type, volMesh > &, const bool allowUnmapped=false) const
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const bool allowUnmapped=false) const
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvsPatchField, surfaceMesh > &, const bool allowUnmapped=false) const
template<class Type >
tmp< GeometricField< Type, pointPatchField, pointMesh > > interpolate (const GeometricField< Type, pointPatchField, pointMesh > &, const bool allowUnmapped=false) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &vf, const fvMesh &sMesh, const labelUList &patchMap, const labelUList &cellMap, const labelUList &faceMap, const bool allowUnmapped)
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &vf, const bool allowUnmapped) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > interpolate (const GeometricField< Type, fvsPatchField, surfaceMesh > &vf, const fvMesh &sMesh, const labelUList &patchMap, const labelUList &cellMap, const labelUList &faceMap)
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > interpolate (const GeometricField< Type, fvsPatchField, surfaceMesh > &sf, const bool allowUnmapped) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::pointPatchField, Foam::pointMesh > > interpolate (const GeometricField< Type, pointPatchField, pointMesh > &vf, const pointMesh &sMesh, const labelUList &patchMap, const labelUList &pointMap)
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::pointPatchField, Foam::pointMesh > > interpolate (const GeometricField< Type, pointPatchField, pointMesh > &sf, const bool allowUnmapped) const
template<class Type >
Foam::tmp< Foam::DimensionedField< Type, Foam::volMesh > > interpolate (const DimensionedField< Type, volMesh > &df, const fvMesh &sMesh, const labelUList &cellMap)
template<class Type >
Foam::tmp< Foam::DimensionedField< Type, Foam::volMesh > > interpolate (const DimensionedField< Type, volMesh > &df, const bool allowUnmapped) const
Static Public Member Functions
template<class Type >
static tmp< DimensionedField< Type, volMesh > > interpolate (const DimensionedField< Type, volMesh > &, const fvMesh &sMesh, const labelUList &cellMap)
template<class Type >
static tmp< GeometricField< Type, fvPatchField, volMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const fvMesh &sMesh, const labelUList &patchMap, const labelUList &cellMap, const labelUList &faceMap, const bool allowUnmapped=false)
template<class Type >
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvsPatchField, surfaceMesh > &, const fvMesh &sMesh, const labelUList &patchMap, const labelUList &cellMap, const labelUList &faceMap)
template<class Type >
static tmp< GeometricField< Type, pointPatchField, pointMesh > > interpolate (const GeometricField< Type, pointPatchField, pointMesh > &, const pointMesh &sMesh, const labelUList &patchMap, const labelUList &pointMap)
Static Public Attributes
static word exposedPatchName
Protected Member Functions
bool checkHasSubMesh () const
fvMeshSubset (const fvMeshSubset &)=delete
void operator= (const fvMeshSubset &)=delete
Detailed Description
Holds a reference to the original mesh (the baseMesh) and optionally to a subset of that mesh (the subMesh) with mapping lists for points, faces, and cells.
Can be constructed or reset to subset on the list of selected cells, which it creates as subMesh consisting only of the desired cells, with the mapping list for points, faces, and cells.
Places all exposed internal faces into either
a user supplied patch
a newly created patch "oldInternalFaces"
reset() does coupled patch subsetting as well. If it detects a face on a coupled patch 'losing' its neighbour it will move the face into the oldInternalFaces patch.
if a user supplied patch is used, it is up to the destination patchField to handle exposed internal faces (mapping from face -1). If not provided the default is to assign the internalField. All the basic patch field types (e.g. fixedValue) will give a warning and preferably derived patch field types should be used that know how to handle exposed faces (e.g. use uniformFixedValue instead of fixedValue)
Source files
fvMeshSubset.H
fvMeshSubset.C
fvMeshSubsetI.H
fvMeshSubsetTemplates.C
Definition at line 75 of file fvMeshSubset.H.
Constructor & Destructor Documentation
fvMeshSubset() [1/7]
fvMeshSubset (const fvMeshSubset &) protected delete
fvMeshSubset() [2/7]
fvMeshSubset (const fvMesh & baseMesh) explicit
Definition at line 394 of file fvMeshSubset.C.
fvMeshSubset() [3/7]
fvMeshSubset (const fvMesh & baseMesh, const Foam::zero)
Definition at line 406 of file fvMeshSubset.C.
References fvMeshSubset::reset().
fvMeshSubset() [4/7]
fvMeshSubset (const fvMesh & baseMesh, const bitSet & selectedCells, const label patchID = -1, const bool syncPar = true)
Definition at line 414 of file fvMeshSubset.C.
References patchID, and fvMeshSubset::reset().
fvMeshSubset() [5/7]
fvMeshSubset (const fvMesh & baseMesh, const labelUList & selectedCells, const label patchID = -1, const bool syncPar = true)
Definition at line 428 of file fvMeshSubset.C.
References patchID, and fvMeshSubset::reset().
fvMeshSubset() [6/7]
fvMeshSubset (const fvMesh & baseMesh, const labelHashSet & selectedCells, const label patchID = -1, const bool syncPar = true)
Definition at line 442 of file fvMeshSubset.C.
References patchID, and fvMeshSubset::reset().
fvMeshSubset() [7/7]
fvMeshSubset (const fvMesh & baseMesh, const label regioni, const labelUList & regions, const label patchID = -1, const bool syncPar = true)
Definition at line 456 of file fvMeshSubset.C.
References patchID, and fvMeshSubset::reset().
Member Function Documentation
checkHasSubMesh()
bool checkHasSubMesh () const protected
Definition at line 106 of file fvMeshSubset.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and Foam::nl.
operator=()
void operator= (const fvMeshSubset &) protected delete
baseMesh()
const Foam::fvMesh & baseMesh () const inline noexcept
Definition at line 23 of file fvMeshSubsetI.H.
Referenced by zoneSubSet::baseMesh(), and zoneSubSet::mapToZone().
mesh()
const Foam::fvMesh & mesh () const inline noexcept
Definition at line 29 of file fvMeshSubsetI.H.
hasSubMesh()
bool hasSubMesh () const inline noexcept
Definition at line 35 of file fvMeshSubsetI.H.
Referenced by fvMeshSubsetProxy::interpolate(), fvMeshSubsetProxy::interpolate(), fvMeshSubsetProxy::interpolateInternal(), and fvMeshSubsetProxy::interpolateInternal().
subMesh() [1/2]
const Foam::fvMesh & subMesh () const inline
Definition at line 41 of file fvMeshSubsetI.H.
Referenced by structuredDecomp::decompose(), fvMeshDistribute::distribute(), fvMeshSubsetProxy::mesh(), structuredRenumber::renumber(), and momentumError::write().
subMesh() [2/2]
Foam::fvMesh & subMesh () inline
Definition at line 49 of file fvMeshSubsetI.H.
pointMap()
const Foam::labelList & pointMap () const inline
Definition at line 57 of file fvMeshSubsetI.H.
Referenced by fvMeshDistribute::distribute().
faceMap()
const Foam::labelList & faceMap () const inline
Definition at line 65 of file fvMeshSubsetI.H.
Referenced by fvMeshDistribute::distribute(), and fvMeshSubset::interpolate().
faceFlipMap()
const Foam::labelList & faceFlipMap () const inline
Definition at line 73 of file fvMeshSubsetI.H.
Referenced by fvMeshDistribute::distribute().
cellMap()
const Foam::labelList & cellMap () const inline
Definition at line 84 of file fvMeshSubsetI.H.
Referenced by structuredDecomp::decompose(), fvMeshDistribute::distribute(), fvMeshSubset::interpolate(), zoneSubSet::mapToZone(), and structuredRenumber::renumber().
patchMap()
const Foam::labelList & patchMap () const inline
Definition at line 92 of file fvMeshSubsetI.H.
Referenced by fvMeshDistribute::distribute(), and fvMeshSubset::interpolate().
clear()
void clear ()
Definition at line 473 of file fvMeshSubset.C.
References PtrList< T >::clear().
reset() [1/7]
void reset ()
Definition at line 485 of file fvMeshSubset.C.
References clear().
Referenced by fvMeshSubset::fvMeshSubset(), fvMeshSubset::fvMeshSubset(), fvMeshSubset::fvMeshSubset(), fvMeshSubset::fvMeshSubset(), fvMeshSubset::fvMeshSubset(), fvMeshSubset::setCellSubset(), fvMeshSubset::setCellSubset(), fvMeshSubset::setCellSubset(), and fvMeshSubset::setCellSubset().
reset() [2/7]
void reset (const Foam::zero)
Definition at line 516 of file fvMeshSubset.C.
References clear(), forAll, Foam::identity(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, PtrList< T >::set(), and UPtrList< T >::size().
reset() [3/7]
void reset (autoPtr< fvMesh > && subMeshPtr, labelList && pointMap, labelList && faceMap, labelList && cellMap, labelList && patchMap)
Parameters
subMeshPtr Mesh subset
pointMap Point mapping
faceMap Face mapping
cellMap Cell mapping
patchMap Patch mapping
Definition at line 491 of file fvMeshSubset.C.
References clear(), and Foam::faceMap().
reset() [4/7]
void reset (const bitSet & selectedCells, const label patchID = -1, const bool syncPar = true)
Definition at line 574 of file fvMeshSubset.C.
References Foam::abort(), Pstream::allGatherList(), UPtrList< T >::begin(), clear(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::identity(), Foam::labelMax, Pstream::listCombineReduce(), UPstream::myProcNo(), autoPtr< T >::New(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, UPstream::nProcs(), UPstream::parRun(), patchID, patchNames(), Foam::reduce(), PtrList< T >::resize(), PtrList< T >::set(), List< T >::setSize(), PtrList< T >::setSize(), UPtrList< T >::size(), UList< T >::size(), bitSet::sortedToc(), bitSet::test(), and Foam::Zero.
reset() [5/7]
void reset (const labelUList & selectedCells, const label patchID = -1, const bool syncPar = true)
Definition at line 1231 of file fvMeshSubset.C.
References Foam::BitSetOps::create(), and patchID.
reset() [6/7]
void reset (const labelHashSet & selectedCells, const label patchID = -1, const bool syncPar = true)
Definition at line 1247 of file fvMeshSubset.C.
References Foam::BitSetOps::create(), and patchID.
reset() [7/7]
void reset (const label regioni, const labelUList & regions, const label patchID = -1, const bool syncCouples = true)
Definition at line 1263 of file fvMeshSubset.C.
References Foam::BitSetOps::create(), and patchID.
setCellSubset() [1/4]
void setCellSubset (const bitSet & selectedCells, const label patchID = -1, const bool syncPar = true) inline
Definition at line 290 of file fvMeshSubset.H.
References patchID, and fvMeshSubset::reset().
setCellSubset() [2/4]
void setCellSubset (const labelUList & selectedCells, const label patchID = -1, const bool syncPar = true) inline
Definition at line 301 of file fvMeshSubset.H.
References patchID, and fvMeshSubset::reset().
setCellSubset() [3/4]
void setCellSubset (const labelHashSet & selectedCells, const label patchID = -1, const bool syncPar = true) inline
Definition at line 312 of file fvMeshSubset.H.
References patchID, and fvMeshSubset::reset().
setCellSubset() [4/4]
void setCellSubset (const label regioni, const labelUList & regions, const label patchID = -1, const bool syncPar = true) inline
Definition at line 323 of file fvMeshSubset.H.
References patchID, and fvMeshSubset::reset().
interpolate() [1/16]
template<class Type > static tmp< DimensionedField< Type, volMesh > > interpolate (const DimensionedField< Type, volMesh > & , const fvMesh & sMesh, const labelUList & cellMap) static
Referenced by momentumError::calcMomentError(), momentumError::divDevRhoReff(), and fvMeshSubsetProxy::interpolate().
interpolate() [2/16]
template<class Type > static tmp< GeometricField< Type, fvPatchField, volMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > & , const fvMesh & sMesh, const labelUList & patchMap, const labelUList & cellMap, const labelUList & faceMap, const bool allowUnmapped = false) static
interpolate() [3/16]
template<class Type > static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvsPatchField, surfaceMesh > & , const fvMesh & sMesh, const labelUList & patchMap, const labelUList & cellMap, const labelUList & faceMap) static
interpolate() [4/16]
template<class Type > static tmp< GeometricField< Type, pointPatchField, pointMesh > > interpolate (const GeometricField< Type, pointPatchField, pointMesh > & , const pointMesh & sMesh, const labelUList & patchMap, const labelUList & pointMap) static
interpolate() [5/16]
template<class Type > tmp< DimensionedField< Type, volMesh > > interpolate (const DimensionedField< Type, volMesh > & , const bool allowUnmapped = false) const
interpolate() [6/16]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > & , const bool allowUnmapped = false) const
interpolate() [7/16]
template<class Type > tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvsPatchField, surfaceMesh > & , const bool allowUnmapped = false) const
interpolate() [8/16]
template<class Type > tmp< GeometricField< Type, pointPatchField, pointMesh > > interpolate (const GeometricField< Type, pointPatchField, pointMesh > & , const bool allowUnmapped = false) const
interpolate() [9/16]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > & vf, const fvMesh & sMesh, const labelUList & patchMap, const labelUList & cellMap, const labelUList & faceMap, const bool allowUnmapped)
Definition at line 37 of file fvMeshSubsetTemplates.C.
References fvPatchFieldBase::calculatedType(), fvMeshSubset::cellMap(), fvMeshSubset::faceMap(), fld(), forAll, Foam::New(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, fvMeshSubset::patchMap(), PtrList< T >::set(), and UPtrList< T >::size().
interpolate() [10/16]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > & vf, const bool allowUnmapped) const
Definition at line 194 of file fvMeshSubsetTemplates.C.
References Foam::faceMap(), and Foam::interpolate().
interpolate() [11/16]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > interpolate (const GeometricField< Type, fvsPatchField, surfaceMesh > & vf, const fvMesh & sMesh, const labelUList & patchMap, const labelUList & cellMap, const labelUList & faceMap)
Definition at line 219 of file fvMeshSubsetTemplates.C.
References fvsPatchFieldBase::calculatedType(), Foam::faceMap(), forAll, Foam::New(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, PtrList< T >::set(), UPtrList< T >::size(), and UList< T >::size().
interpolate() [12/16]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > interpolate (const GeometricField< Type, fvsPatchField, surfaceMesh > & sf, const bool allowUnmapped) const
Definition at line 383 of file fvMeshSubsetTemplates.C.
References Foam::faceMap(), and Foam::interpolate().
interpolate() [13/16]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::pointPatchField, Foam::pointMesh > > interpolate (const GeometricField< Type, pointPatchField, pointMesh > & vf, const pointMesh & sMesh, const labelUList & patchMap, const labelUList & pointMap)
Definition at line 407 of file fvMeshSubsetTemplates.C.
References pointPatchFieldBase::calculatedType(), forAll, Foam::New(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, PtrList< T >::set(), UPtrList< T >::size(), and UList< T >::size().
interpolate() [14/16]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::pointPatchField, Foam::pointMesh > > interpolate (const GeometricField< Type, pointPatchField, pointMesh > & sf, const bool allowUnmapped) const
Definition at line 540 of file fvMeshSubsetTemplates.C.
References Foam::interpolate(), and MeshObject< polyMesh, UpdateableMeshObject, pointMesh >::New().
interpolate() [15/16]
template<class Type > Foam::tmp< Foam::DimensionedField< Type, Foam::volMesh > > interpolate (const DimensionedField< Type, volMesh > & df, const fvMesh & sMesh, const labelUList & cellMap)
Definition at line 563 of file fvMeshSubsetTemplates.C.
References Foam::New(), IOobjectOption::NO_READ, and IOobjectOption::NO_WRITE.
interpolate() [16/16]
template<class Type > Foam::tmp< Foam::DimensionedField< Type, Foam::volMesh > > interpolate (const DimensionedField< Type, volMesh > & df, const bool allowUnmapped) const
Definition at line 597 of file fvMeshSubsetTemplates.C.
References Foam::interpolate().
Member Data Documentation
exposedPatchName
Foam::word exposedPatchName static
Definition at line 136 of file fvMeshSubset.H.
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/fvMeshSubset/fvMeshSubset.H
src/finiteVolume/fvMesh/fvMeshSubset/fvMeshSubset.C
src/finiteVolume/fvMesh/fvMeshSubset/fvMeshSubsetI.H
src/finiteVolume/fvMesh/fvMeshSubset/fvMeshSubsetTemplates.C