OpenFOAM: eagerGAMGProcAgglomeration Class Reference
eagerGAMGProcAgglomeration Class Reference
'Eager' processor agglomeration of GAMGAgglomerations: at every level agglomerates 'mergeLevels' number of processors onto the minimum processor number.
#include <eagerGAMGProcAgglomeration.H>
Public Member Functions
TypeName ("eager")
eagerGAMGProcAgglomeration (const eagerGAMGProcAgglomeration &)=delete
void operator= (const eagerGAMGProcAgglomeration &)=delete
eagerGAMGProcAgglomeration (GAMGAgglomeration &agglom, const dictionary &controlDict)
virtual ~eagerGAMGProcAgglomeration ()
virtual bool agglomerate ()
Public Member Functions inherited from GAMGProcAgglomeration
TypeName ("GAMGProcAgglomeration")
declareRunTimeSelectionTable (autoPtr, GAMGProcAgglomeration, GAMGAgglomeration,(GAMGAgglomeration &agglom, const dictionary &controlDict),(agglom, controlDict))
GAMGProcAgglomeration (const GAMGProcAgglomeration &)=delete
void operator= (const GAMGProcAgglomeration &)=delete
GAMGProcAgglomeration (GAMGAgglomeration &agglom, const dictionary &controlDict)
virtual ~GAMGProcAgglomeration ()
Additional Inherited Members
Static Public Member Functions inherited from GAMGProcAgglomeration
static autoPtr< GAMGProcAgglomeration > New (const word &type, GAMGAgglomeration &agglom, const dictionary &controlDict)
Protected Member Functions inherited from GAMGProcAgglomeration
void printStats (Ostream &os, GAMGAgglomeration &agglom) const
bool agglomerate (const label fineLevelIndex, const labelList &procAgglomMap, const labelList &masterProcs, const List< label > &agglomProcIDs, const label procAgglomComm)
void clearCommunicators ()
Static Protected Member Functions inherited from GAMGProcAgglomeration
static labelListList globalCellCells (const lduMesh &)
Protected Attributes inherited from GAMGProcAgglomeration
GAMGAgglomeration & agglom_
DynamicList< label > comms_
Detailed Description
'Eager' processor agglomeration of GAMGAgglomerations: at every level agglomerates 'mergeLevels' number of processors onto the minimum processor number.
Source files
eagerGAMGProcAgglomeration.H
eagerGAMGProcAgglomeration.C
Definition at line 49 of file eagerGAMGProcAgglomeration.H.
Constructor & Destructor Documentation
eagerGAMGProcAgglomeration() [1/2]
eagerGAMGProcAgglomeration (const eagerGAMGProcAgglomeration &) delete
eagerGAMGProcAgglomeration() [2/2]
eagerGAMGProcAgglomeration (GAMGAgglomeration & agglom, const dictionary & controlDict)
Definition at line 43 of file eagerGAMGProcAgglomeration.C.
~eagerGAMGProcAgglomeration()
~eagerGAMGProcAgglomeration () virtual
Definition at line 56 of file eagerGAMGProcAgglomeration.C.
Member Function Documentation
TypeName()
TypeName ("eager")
operator=()
void operator= (const eagerGAMGProcAgglomeration &) delete
agglomerate()
bool agglomerate () virtual
Implements GAMGProcAgglomeration.
Definition at line 62 of file eagerGAMGProcAgglomeration.C.
References GAMGProcAgglomeration::agglomerate(), UPstream::allocateCommunicator(), UPtrList< T >::back(), GAMGAgglomeration::calculateRegionMaster(), Foam::endl(), forAll, UPstream::myProcNo(), Foam::nl, UPstream::nProcs(), Foam::Pout, and UPtrList< T >::size().
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/GAMGProcAgglomerations/eagerGAMGProcAgglomeration/eagerGAMGProcAgglomeration.H
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/GAMGProcAgglomerations/eagerGAMGProcAgglomeration/eagerGAMGProcAgglomeration.C