OpenFOAM: molecule Class Reference
molecule Class Reference
Foam::molecule.
#include <molecule.H>
Classes
class constantProperties
class iNew
class trackingData
Public Types
enum specialTypes { SPECIAL_TETHERED = -1 , SPECIAL_FROZEN = -2 , NOT_SPECIAL = 0 , SPECIAL_USER = 1 }
Public Member Functions
molecule (const polyMesh &mesh, const barycentric &coordinates, const label celli, const label tetFacei, const label tetPti, const tensor &Q, const vector &v, const vector &a, const vector &pi, const vector &tau, const vector &specialPosition, const constantProperties &constProps, const label special, const label id)
molecule (const polyMesh &mesh, const vector &position, const label celli, const tensor &Q, const vector &v, const vector &a, const vector &pi, const vector &tau, const vector &specialPosition, const constantProperties &constProps, const label special, const label id)
molecule (const polyMesh &mesh, Istream &is, bool readFields=true, bool newFormat=true)
autoPtr< particle > clone () const
bool move (moleculeCloud &, trackingData &, const scalar trackTime)
virtual void transformProperties (const tensor &T)
virtual void transformProperties (const vector &separation)
void setSitePositions (const constantProperties &constProps)
void setSiteSizes (label size)
const tensor & Q () const
tensor & Q ()
const vector & v () const
vector & v ()
const vector & a () const
vector & a ()
const vector & pi () const
vector & pi ()
const vector & tau () const
vector & tau ()
const List< vector > & siteForces () const
List< vector > & siteForces ()
const List< vector > & sitePositions () const
List< vector > & sitePositions ()
const vector & specialPosition () const
vector & specialPosition ()
scalar potentialEnergy () const
scalar & potentialEnergy ()
const tensor & rf () const
tensor & rf ()
label special () const
bool tethered () const
label id () const
bool hitPatch (moleculeCloud &cloud, trackingData &td)
void hitProcessorPatch (moleculeCloud &cloud, trackingData &td)
void hitWallPatch (moleculeCloud &cloud, trackingData &td)
Public Member Functions inherited from particle< Type >
TypeName ("particle")
particle (const polyMesh &mesh, const barycentric &coordinates, const label celli, const label tetFacei, const label tetPti)
particle (const polyMesh &mesh, const vector &position, const label celli=-1)
particle (const polyMesh &mesh, const vector &position, const label celli, const label tetFacei, const label tetPti, const bool doLocate=true)
particle (const polyMesh &mesh, Istream &, const bool readFields=true, const bool newFormat=true, const bool doLocate=true)
particle (const particle &p)
particle (const particle &p, const polyMesh &mesh)
virtual ~particle ()=default
label getNewParticleID () const
const polyMesh & mesh () const noexcept
const barycentric & coordinates () const noexcept
label cell () const noexcept
label & cell () noexcept
label tetFace () const noexcept
label & tetFace () noexcept
label tetPt () const noexcept
label & tetPt () noexcept
label face () const noexcept
label & face () noexcept
scalar stepFraction () const noexcept
scalar & stepFraction () noexcept
label origProc () const noexcept
label & origProc () noexcept
label origId () const noexcept
label & origId () noexcept
Pair< scalar > stepFractionSpan () const
scalar currentTimeFraction () const
tetIndices currentTetIndices () const noexcept
barycentricTensor currentTetTransform () const
vector normal () const
bool onFace () const noexcept
bool onInternalFace () const noexcept
bool onBoundaryFace () const noexcept
label patch () const
vector position () const
void reset ()
scalar track (const vector &displacement, const scalar fraction)
scalar trackToFace (const vector &displacement, const scalar fraction)
scalar trackToTri (const vector &displacement, const scalar fraction, label &tetTriI)
scalar trackToStationaryTri (const vector &displacement, const scalar fraction, label &tetTriI)
scalar trackToMovingTri (const vector &displacement, const scalar fraction, label &tetTriI)
template<class TrackCloudType >
void hitFace (const vector &direction, TrackCloudType &cloud, trackingData &td)
template<class TrackCloudType >
void trackToAndHitFace (const vector &direction, const scalar fraction, TrackCloudType &cloud, trackingData &td)
vector deviationFromMeshCentre () const
void patchData (vector &n, vector &U) const
void prepareForParallelTransfer ()
void correctAfterParallelTransfer (const label patchi, trackingData &td)
void prepareForInteractionListReferral (const vectorTensorTransform &transform)
void correctAfterInteractionListReferral (const label celli)
label procTetPt (const polyMesh &procMesh, const label procCell, const label procTetFace) const
void autoMap (const vector &position, const mapPolyMesh &mapper)
void relocate (const point &position, const label celli=-1)
void writeProperties (Ostream &os, const wordRes &filters, const word &delim, const bool namesOnly) const
void writeCoordinates (Ostream &os) const
virtual void writePosition (Ostream &os) const
Static Public Member Functions
static void readFields (Cloud< molecule > &mC)
static void writeFields (const Cloud< molecule > &mC)
Static Public Member Functions inherited from particle< Type >
static string propertyList ()
template<class Type >
static void writePropertyName (Ostream &os, const word &name, const word &delim)
template<class Type >
static void writeProperty (Ostream &os, const word &name, const Type &value, const bool nameOnly, const word &delim, const wordRes &filters=wordRes::null())
template<class Type >
static void writeProperty (Ostream &os, const word &name, const Field< Type > &values, const bool nameOnly, const word &delim, const wordRes &filters=wordRes::null())
template<class TrackCloudType >
static void readFields (TrackCloudType &c)
template<class TrackCloudType >
static void writeFields (const TrackCloudType &c)
template<class CloudType >
static void readObjects (CloudType &c, const objectRegistry &obr)
template<class CloudType >
static void writeObjects (const CloudType &c, objectRegistry &obr)
Static Public Attributes
static const std::size_t sizeofFields
Static Public Attributes inherited from particle< Type >
static string propertyList_ = Foam::particle::propertyList()
static label particleCount_ = 0
static bool writeLagrangianCoordinates = true
static bool writeLagrangianPositions
Friends
class Cloud< molecule >
Ostream & operator<< (Ostream &, const molecule &)
Additional Inherited Members
Protected Member Functions inherited from particle< Type >
void readData (Istream &is, point &position, const bool readFields, const bool newFormat, const bool doLocate)
template<class TrackCloudType >
bool hitPatch (TrackCloudType &, trackingData &)
template<class TrackCloudType >
void hitWedgePatch (TrackCloudType &, trackingData &)
template<class TrackCloudType >
void hitSymmetryPlanePatch (TrackCloudType &, trackingData &)
template<class TrackCloudType >
void hitSymmetryPatch (TrackCloudType &, trackingData &)
template<class TrackCloudType >
void hitCyclicPatch (TrackCloudType &, trackingData &)
template<class TrackCloudType >
void hitCyclicAMIPatch (TrackCloudType &, trackingData &, const vector &)
template<class TrackCloudType >
void hitCyclicACMIPatch (TrackCloudType &, trackingData &, const vector &)
template<class TrackCloudType >
void hitProcessorPatch (TrackCloudType &, trackingData &)
template<class TrackCloudType >
void hitWallPatch (TrackCloudType &, trackingData &)
template<class TrackCloudType >
void hitBoundaryFace (const vector &direction, TrackCloudType &cloud, trackingData &td)
Detailed Description
Foam::molecule.
Source files
molecule.H
moleculeI.H
molecule.C
moleculeIO.C
Definition at line 63 of file molecule.H.
Member Enumeration Documentation
specialTypes
enum specialTypes
Enumerator
SPECIAL_TETHERED
SPECIAL_FROZEN
NOT_SPECIAL
SPECIAL_USER
Definition at line 77 of file molecule.H.
Constructor & Destructor Documentation
molecule() [1/3]
molecule (const polyMesh & mesh, const barycentric & coordinates, const label celli, const label tetFacei, const label tetPti, const tensor & Q, const vector & v, const vector & a, const vector & pi, const vector & tau, const vector & specialPosition, const constantProperties & constProps, const label special, const label id) inline
Definition at line 218 of file moleculeI.H.
References molecule::setSitePositions().
molecule() [2/3]
molecule (const polyMesh & mesh, const vector & position, const label celli, const tensor & Q, const vector & v, const vector & a, const vector & pi, const vector & tau, const vector & specialPosition, const constantProperties & constProps, const label special, const label id) inline
Definition at line 255 of file moleculeI.H.
References molecule::setSitePositions().
molecule() [3/3]
molecule (const polyMesh & mesh, Istream & is, bool readFields = true, bool newFormat = true)
Definition at line 36 of file moleculeIO.C.
References IOstreamOption::ASCII, VectorSpace< Form, Cmpt, Ncmpts >::data(), FUNCTION_NAME, VectorSpace< Form, Cmpt, Ncmpts >::nComponents, VectorSpace< Form, Cmpt, Mrows *Ncols >::nComponents, molecule::readFields(), Foam::readFields(), Foam::readRawLabel(), and molecule::sizeofFields.
Member Function Documentation
clone()
autoPtr< particle > clone () const inline virtual
Reimplemented from particle< Type >.
Definition at line 282 of file molecule.H.
move()
bool move (moleculeCloud & cloud, trackingData & td, const scalar trackTime)
Definition at line 63 of file molecule.C.
References Foam::abort(), f(), Foam::FatalError, FatalErrorInFunction, forAll, molecule::constantProperties::linearMolecule(), molecule::constantProperties::mass(), molecule::constantProperties::momentOfInertia(), molecule::constantProperties::pointMolecule(), R, s(), molecule::constantProperties::siteReferencePositions(), and Foam::Zero.
transformProperties() [1/2]
void transformProperties (const tensor & T) virtual
Reimplemented from particle< Type >.
Definition at line 184 of file molecule.C.
References T, Foam::transform(), and particle< Type >::transformProperties().
transformProperties() [2/2]
void transformProperties (const vector & separation) virtual
Reimplemented from particle< Type >.
Definition at line 206 of file molecule.C.
References particle< Type >::transformProperties().
setSitePositions()
void setSitePositions (const constantProperties & constProps)
Definition at line 219 of file molecule.C.
References molecule::constantProperties::siteReferencePositions().
Referenced by molecule::molecule(), and molecule::molecule().
setSiteSizes()
void setSiteSizes (label size)
Definition at line 225 of file molecule.C.
References PtrList< T >::setSize().
Q() [1/2]
const Foam::tensor & Q () const inline
Definition at line 502 of file moleculeI.H.
Referenced by molecule::constantProperties::constantProperties().
Q() [2/2]
Foam::tensor & Q () inline
Definition at line 508 of file moleculeI.H.
v() [1/2]
const Foam::vector & v () const inline
Definition at line 514 of file moleculeI.H.
v() [2/2]
Foam::vector & v () inline
Definition at line 520 of file moleculeI.H.
a() [1/2]
const Foam::vector & a () const inline
Definition at line 526 of file moleculeI.H.
a() [2/2]
Foam::vector & a () inline
Definition at line 532 of file moleculeI.H.
pi() [1/2]
const Foam::vector & pi () const inline
Definition at line 538 of file moleculeI.H.
pi() [2/2]
Foam::vector & pi () inline
Definition at line 544 of file moleculeI.H.
tau() [1/2]
const Foam::vector & tau () const inline
Definition at line 550 of file moleculeI.H.
tau() [2/2]
Foam::vector & tau () inline
Definition at line 556 of file moleculeI.H.
siteForces() [1/2]
const Foam::List< Foam::vector > & siteForces () const inline
Definition at line 562 of file moleculeI.H.
siteForces() [2/2]
Foam::List< Foam::vector > & siteForces () inline
Definition at line 568 of file moleculeI.H.
sitePositions() [1/2]
const Foam::List< Foam::vector > & sitePositions () const inline
Definition at line 574 of file moleculeI.H.
sitePositions() [2/2]
Foam::List< Foam::vector > & sitePositions () inline
Definition at line 580 of file moleculeI.H.
specialPosition() [1/2]
const Foam::vector & specialPosition () const inline
Definition at line 586 of file moleculeI.H.
specialPosition() [2/2]
Foam::vector & specialPosition () inline
Definition at line 592 of file moleculeI.H.
potentialEnergy() [1/2]
Foam::scalar potentialEnergy () const inline
Definition at line 598 of file moleculeI.H.
potentialEnergy() [2/2]
Foam::scalar & potentialEnergy () inline
Definition at line 604 of file moleculeI.H.
rf() [1/2]
const Foam::tensor & rf () const inline
Definition at line 610 of file moleculeI.H.
rf() [2/2]
Foam::tensor & rf () inline
Definition at line 616 of file moleculeI.H.
special()
Foam::label special () const inline
Definition at line 622 of file moleculeI.H.
tethered()
bool tethered () const inline
Definition at line 628 of file moleculeI.H.
id()
Foam::label id () const inline
Definition at line 634 of file moleculeI.H.
hitPatch()
bool hitPatch (moleculeCloud & cloud, trackingData & td)
Definition at line 233 of file molecule.C.
hitProcessorPatch()
void hitProcessorPatch (moleculeCloud & cloud, trackingData & td)
Definition at line 239 of file molecule.C.
hitWallPatch()
void hitWallPatch (moleculeCloud & cloud, trackingData & td)
Definition at line 245 of file molecule.C.
readFields()
void readFields (Cloud< molecule > & mC) static
Definition at line 104 of file moleculeIO.C.
References IOobjectOption::MUST_READ, particle< Type >::readFields(), and UPtrList< T >::size().
Referenced by molecule::molecule(), moleculeCloud::moleculeCloud(), and moleculeCloud::moleculeCloud().
writeFields()
void writeFields (const Cloud< molecule > & mC) static
Definition at line 163 of file moleculeIO.C.
References Foam::endl(), Foam::Info, moleculeCloud::mesh(), IOobjectOption::NO_READ, cloud::prefix, UPtrList< T >::size(), particle< Type >::writeFields(), and moleculeCloud::writeXYZ().
Friends And Related Symbol Documentation
Cloud< molecule >
friend class Cloud< molecule > friend
Definition at line 226 of file molecule.H.
operator<<
Ostream & operator<< (Ostream & , const molecule &) friend
Member Data Documentation
sizeofFields
const std::size_t sizeofFields static
Definition at line 70 of file molecule.H.
Referenced by molecule::molecule(), and Foam::operator<<().
The documentation for this class was generated from the following files:
src/lagrangian/molecularDynamics/molecule/molecule/molecule.H
src/lagrangian/molecularDynamics/molecule/molecule/molecule.C
src/lagrangian/molecularDynamics/molecule/molecule/moleculeI.H
src/lagrangian/molecularDynamics/molecule/molecule/moleculeIO.C