OpenFOAM: thermophysicalFunction Class Reference
thermophysicalFunction Class Reference abstract
Abstract base class for thermo-physical functions.
#include <thermophysicalFunction.H>
Public Member Functions
TypeName ("thermophysicalFunction")
declareRunTimeSelectionTable (autoPtr, thermophysicalFunction, Istream,(Istream &is),(is))
declareRunTimeSelectionTable (autoPtr, thermophysicalFunction, dictionary,(const dictionary &dict),(dict))
thermophysicalFunction ()
virtual ~thermophysicalFunction ()=default
virtual scalar f (scalar p, scalar T) const =0
virtual void writeData (Ostream &os) const =0
Static Public Member Functions
static autoPtr< thermophysicalFunction > New (Istream &is)
static autoPtr< thermophysicalFunction > New (const dictionary &dict)
Friends
Ostream & operator<< (Ostream &os, const thermophysicalFunction &f)
Detailed Description
Abstract base class for thermo-physical functions.
Definition at line 47 of file thermophysicalFunction.H.
Constructor & Destructor Documentation
thermophysicalFunction()
thermophysicalFunction () inline
Definition at line 80 of file thermophysicalFunction.H.
~thermophysicalFunction()
virtual ~thermophysicalFunction () virtual default
Member Function Documentation
TypeName()
TypeName ("thermophysicalFunction")
declareRunTimeSelectionTable() [1/2]
declareRunTimeSelectionTable (autoPtr , thermophysicalFunction , Istream , (Istream &is) , (is))
declareRunTimeSelectionTable() [2/2]
declareRunTimeSelectionTable (autoPtr , thermophysicalFunction , dictionary , (const dictionary &dict) , (dict))
New() [1/2]
Foam::autoPtr< Foam::thermophysicalFunction > New (Istream & is) static
Definition at line 37 of file thermophysicalFunction.C.
References Foam::abort(), DebugInFunction, Foam::endl(), Foam::FatalError, and FatalErrorInLookup.
New() [2/2]
Foam::autoPtr< Foam::thermophysicalFunction > New (const dictionary & dict) static
Definition at line 62 of file thermophysicalFunction.C.
References Foam::abort(), DebugInFunction, dict, Foam::endl(), Foam::FatalIOError, FatalIOErrorInLookup, and dictionary::get().
f()
virtual scalar f (scalar p, scalar T) const pure virtual
Implemented in APIdiffCoefFunc, NSRDSfunc0, NSRDSfunc1, NSRDSfunc14, NSRDSfunc2, NSRDSfunc3, NSRDSfunc4, NSRDSfunc5, NSRDSfunc6, and NSRDSfunc7.
writeData()
virtual void writeData (Ostream & os) const pure virtual
Implemented in APIdiffCoefFunc, NSRDSfunc0, NSRDSfunc1, NSRDSfunc14, NSRDSfunc2, NSRDSfunc3, NSRDSfunc4, NSRDSfunc5, NSRDSfunc6, and NSRDSfunc7.
Friends And Related Symbol Documentation
operator<<
Ostream & operator<< (Ostream & os, const thermophysicalFunction & f) friend
Definition at line 105 of file thermophysicalFunction.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/thermophysicalProperties/thermophysicalFunctions/thermophysicalFunction/thermophysicalFunction.H
src/thermophysicalModels/thermophysicalProperties/thermophysicalFunctions/thermophysicalFunction/thermophysicalFunction.C