OpenFOAM: TroeFallOffFunction Class Reference
TroeFallOffFunction Class Reference
The Troe fall-off function.
#include <TroeFallOffFunction.H>
Public Member Functions
TroeFallOffFunction (const scalar alpha, const scalar Tsss, const scalar Ts, const scalar Tss)
TroeFallOffFunction (const dictionary &dict)
scalar operator() (const scalar T, const scalar Pr) const
void write (Ostream &os) const
Static Public Member Functions
static word type ()
Friends
Ostream & operator<< (Ostream &, const TroeFallOffFunction &)
Detailed Description
The Troe fall-off function.
Source files
TroeFallOffFunction.H
TroeFallOffFunctionI.H
Definition at line 52 of file TroeFallOffFunction.H.
Constructor & Destructor Documentation
TroeFallOffFunction() [1/2]
TroeFallOffFunction (const scalar alpha, const scalar Tsss, const scalar Ts, const scalar Tss) inline
Definition at line 23 of file TroeFallOffFunctionI.H.
TroeFallOffFunction() [2/2]
TroeFallOffFunction (const dictionary & dict) inline
Definition at line 38 of file TroeFallOffFunctionI.H.
Member Function Documentation
type()
static word type () inline static
Definition at line 80 of file TroeFallOffFunction.H.
operator()()
Foam::scalar operator() (const scalar T, const scalar Pr) const inline
Definition at line 49 of file TroeFallOffFunctionI.H.
References Foam::exp(), Foam::log10(), Foam::max(), n, Foam::pow(), Pr(), Foam::sqr(), and T.
write()
void write (Ostream & os) const inline
Definition at line 73 of file TroeFallOffFunctionI.H.
References os(), and Ostream::writeEntry().
Friends And Related Symbol Documentation
operator<<
Ostream & operator<< (Ostream & , const TroeFallOffFunction &) friend
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/reaction/reactionRate/fallOffFunctions/TroeFallOffFunction/TroeFallOffFunction.H
src/thermophysicalModels/specie/reaction/reactionRate/fallOffFunctions/TroeFallOffFunction/TroeFallOffFunctionI.H