OpenFOAM: FIREMeshWriter Class Reference
FIREMeshWriter Class Reference
Writes polyMesh in AVL/FIRE polyhedra format (fpma, fpmb)
#include <FIREMeshWriter.H>
Public Member Functions
FIREMeshWriter (const polyMesh &, const scalar scaleFactor=1.0)
virtual ~FIREMeshWriter ()=default
virtual bool write (const fileName &meshName=fileName::null) const
Public Member Functions inherited from meshWriter
meshWriter (const polyMesh &, const scalar scaling=1.0)
virtual ~meshWriter ()
Static Public Attributes
static bool binary = false
static bool compress = false
static bool prefixBoundary = true
Static Public Attributes inherited from meshWriter
static string defaultMeshName = "meshExport"
Additional Inherited Members
Public Types inherited from FIRECore
enum selectionType { cellSelection = 2 , faceSelection = 3 }
enum shapeType {
fireLine = 1 , fireTri = 2 , fireQuad = 3 , fireTet = 4 ,
fireHex = 5 , firePyr = 6 , firePrism = 8
}
enum fileExt3d { POLY_ASCII , POLY_BINARY , POLY_ASCII_Z , POLY_BINARY_Z }
typedef int32_t fireInt_t
typedef double fireReal_t
Static Public Member Functions inherited from FIRECore
static fileName fireFileName (const fileName &baseName, const enum fileExt3d)
static label getFireLabel (ISstream &)
static point getFirePoint (ISstream &)
static std::string getFireString (ISstream &)
static void putFireLabel (OSstream &, const label)
static void putFireLabels (OSstream &, const labelUList &)
static void putFireLabels (OSstream &, const label count, const label start)
static void putFirePoint (OSstream &, const point &)
static void putFireString (OSstream &, const std::string &)
Protected Member Functions inherited from FIRECore
FIRECore ()=default
Static Protected Member Functions inherited from FIRECore
static label readPoints (ISstream &, pointField &)
Protected Attributes inherited from meshWriter
const polyMesh & mesh_
scalar scaleFactor_
boundaryRegion boundaryRegion_
cellTable cellTable_
labelList cellTableId_
Static Protected Attributes inherited from FIRECore
static const Enum< fileExt3d > file3dExtensions
Detailed Description
Writes polyMesh in AVL/FIRE polyhedra format (fpma, fpmb)
It is also possible to write compressed formats (fpmaz, fpmbz)
Note
The fpma, fpmb formats are relatively poorly documented, but are manageable to read and write. It is, however, not recommended to import them directly into AVL/FIRE (the GUI) since it is generally not robust enough. Instead use their file-convertor to reconvert them into their native format.
In the AVL/FIRE polyhedra format, the faces normals point inwards, whereas the OpenFOAM face normals always point outwards.
Source files
FIREMeshWriter.H
FIREMeshWriter.C
Definition at line 62 of file FIREMeshWriter.H.
Constructor & Destructor Documentation
FIREMeshWriter()
FIREMeshWriter (const polyMesh & mesh, const scalar scaleFactor = 1.0)
Definition at line 237 of file FIREMeshWriter.C.
~FIREMeshWriter()
virtual ~FIREMeshWriter () virtual default
Member Function Documentation
write()
bool write (const fileName & meshName = fileName::null) const virtual
Implements meshWriter.
Definition at line 249 of file FIREMeshWriter.C.
References IOstreamOption::ASCII, IOstreamOption::BINARY, PtrList< T >::clear(), IOstreamOption::COMPRESSED, TimePaths::constant(), meshWriter::defaultMeshName, Foam::endl(), fileName::ext(), FIRECore::file3dExtensions, FIRECore::fireFileName(), found, Foam::Info, Foam::mv(), FIRECore::POLY_ASCII, FIRECore::POLY_ASCII_Z, FIRECore::POLY_BINARY, FIRECore::POLY_BINARY_Z, fileName::remove_ext(), objectRegistry::time(), Time::timeName(), IOstreamOption::UNCOMPRESSED, and writeGeometry().
Member Data Documentation
binary
bool binary = false static
Definition at line 86 of file FIREMeshWriter.H.
compress
bool compress = false static
Definition at line 89 of file FIREMeshWriter.H.
prefixBoundary
bool prefixBoundary = true static
Definition at line 92 of file FIREMeshWriter.H.
The documentation for this class was generated from the following files:
src/conversion/fire/FIREMeshWriter.H
src/conversion/fire/FIREMeshWriter.C