OpenFOAM: UPtrList< T >::const_iterator Class Reference
UPtrList< T >::const_iterator Class Reference
#include <UPtrList.H>
Public Types
using pointer = const T *
using reference = const T &
Public Types inherited from UPtrList< T >::Iterator< Const >
using list_type = typename std::conditional< Const, const UPtrList< T >, UPtrList< T > >::type
Public Member Functions
const_iterator ()=default
const_iterator (const const_iterator &)=default
const_iterator & operator= (const const_iterator &)=default
template<bool Any>
const_iterator (const Iterator< Any > &iter)
const_iterator (const iterator &iter)
pointer get () const
reference val () const
pointer operator-> () const
reference operator* () const
reference operator() () const
const_iterator & operator++ ()
const_iterator operator++ (int)
Public Member Functions inherited from UPtrList< T >::Iterator< Const >
bool good () const noexcept
label key () const noexcept
template<bool Any>
bool operator== (const Iterator< Any > &iter) const noexcept
template<bool Any>
bool operator!= (const Iterator< Any > &iter) const noexcept
Additional Inherited Members
Protected Member Functions inherited from UPtrList< T >::Iterator< Const >
constexpr Iterator () noexcept
Iterator (list_type *list)
void increment ()
template<bool Any>
operator const Iterator< Any > & () const
Protected Attributes inherited from UPtrList< T >::Iterator< Const >
list_type * list_
label pos_
Detailed Description
template<class T>
class Foam::UPtrList< T >::const_iterator
Definition at line 525 of file UPtrList.H.
Member Typedef Documentation
pointer
template<class T > using pointer = const T*
Definition at line 530 of file UPtrList.H.
reference
template<class T > using reference = const T&
Definition at line 531 of file UPtrList.H.
Constructor & Destructor Documentation
const_iterator() [1/4]
template<class T > const_iterator () default
const_iterator() [2/4]
template<class T > const_iterator (const const_iterator &) default
const_iterator() [3/4]
template<class T > template<bool Any> const_iterator (const Iterator< Any > & iter) inline
Definition at line 550 of file UPtrList.H.
const_iterator() [4/4]
template<class T > const_iterator (const iterator & iter) inline
Definition at line 556 of file UPtrList.H.
Member Function Documentation
operator=()
template<class T > const_iterator & operator= (const const_iterator &) default
get()
template<class T > const T * get () const inline
Definition at line 373 of file UPtrListI.H.
References UPtrList< T >::get().
Referenced by genericRagelLemonDriver::cend(), and UPtrList< T >::const_iterator::operator->().
val()
template<class T > const T & val () const inline
Definition at line 380 of file UPtrListI.H.
References UPtrList< T >::at().
Referenced by UPtrList< T >::const_iterator::operator()(), and UPtrList< T >::const_iterator::operator*().
operator->()
template<class T > pointer operator-> () const inline
Definition at line 571 of file UPtrList.H.
References UPtrList< T >::const_iterator::get().
operator*()
template<class T > reference operator* () const inline
Definition at line 574 of file UPtrList.H.
References UPtrList< T >::const_iterator::val().
operator()()
template<class T > reference operator() () const inline
Definition at line 577 of file UPtrList.H.
References UPtrList< T >::const_iterator::val().
operator++() [1/2]
template<class T > Foam::UPtrList< T >::const_iterator & operator++ () inline
Definition at line 388 of file UPtrListI.H.
operator++() [2/2]
template<class T > Foam::UPtrList< T >::const_iterator operator++ (int) inline
Definition at line 397 of file UPtrListI.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/PtrLists/UPtrList/UPtrList.H
src/OpenFOAM/containers/PtrLists/UPtrList/UPtrListI.H