OpenFOAM: geometricSurfacePatch Class Reference
geometricSurfacePatch Class Reference
Identifies a surface patch/zone by name and index, with geometric type.
#include <geometricSurfacePatch.H>
Classes
struct fromIdentifier
Public Member Functions
geometricSurfacePatch (const geometricSurfacePatch &)=default
geometricSurfacePatch & operator= (const geometricSurfacePatch &)=default
geometricSurfacePatch ()
geometricSurfacePatch (const label index)
geometricSurfacePatch (const word &name, const label index)
geometricSurfacePatch (const word &name, const label index, const word &geometricType)
geometricSurfacePatch (const word &name, const dictionary &dict, const label index)
geometricSurfacePatch (const surfZoneIdentifier &ident)
const word & name () const noexcept
word & name () noexcept
label index () const noexcept
label & index () noexcept
const word & geometricType () const noexcept
word & geometricType () noexcept
void write (Ostream &os) const
geometricSurfacePatch (Istream &is, const label index)=delete
geometricSurfacePatch (const word &geometricType, const word &name, const label index)
void writeDict (Ostream &os) const
Static Public Member Functions
static word defaultName (const label n=-1)
Static Public Attributes
static constexpr const char *const emptyType = "empty"
Detailed Description
Identifies a surface patch/zone by name and index, with geometric type.
Source files
geometricSurfacePatch.H
geometricSurfacePatch.C
Definition at line 49 of file geometricSurfacePatch.H.
Constructor & Destructor Documentation
geometricSurfacePatch() [1/9]
geometricSurfacePatch (const geometricSurfacePatch &) default
geometricSurfacePatch() [2/9]
geometricSurfacePatch ()
Definition at line 27 of file geometricSurfacePatch.C.
Referenced by geometricSurfacePatch::fromIdentifier::operator()().
geometricSurfacePatch() [3/9]
geometricSurfacePatch (const label index) explicit
Definition at line 33 of file geometricSurfacePatch.C.
geometricSurfacePatch() [4/9]
geometricSurfacePatch (const word & name, const label index)
Definition at line 41 of file geometricSurfacePatch.C.
geometricSurfacePatch() [5/9]
geometricSurfacePatch (const word & name, const label index, const word & geometricType)
Definition at line 53 of file geometricSurfacePatch.C.
geometricSurfacePatch() [6/9]
geometricSurfacePatch (const word & name, const dictionary & dict, const label index)
Definition at line 66 of file geometricSurfacePatch.C.
References dict.
geometricSurfacePatch() [7/9]
geometricSurfacePatch (const surfZoneIdentifier & ident)
Definition at line 79 of file geometricSurfacePatch.C.
geometricSurfacePatch() [8/9]
geometricSurfacePatch (Istream & is, const label index) delete
geometricSurfacePatch() [9/9]
geometricSurfacePatch (const word & geometricType, const word & name, const label index) inline
Definition at line 195 of file geometricSurfacePatch.H.
Member Function Documentation
defaultName()
static word defaultName (const label n = -1) inline static
Definition at line 73 of file geometricSurfacePatch.H.
References n.
Referenced by boundaryMesh::readTriSurface().
operator=()
geometricSurfacePatch & operator= (const geometricSurfacePatch &) default
name() [1/2]
const word & name () const inline noexcept
Definition at line 145 of file geometricSurfacePatch.H.
Referenced by Foam::operator==().
name() [2/2]
word & name () inline noexcept
Definition at line 151 of file geometricSurfacePatch.H.
index() [1/2]
label index () const inline noexcept
Definition at line 157 of file geometricSurfacePatch.H.
index() [2/2]
label & index () inline noexcept
Definition at line 163 of file geometricSurfacePatch.H.
geometricType() [1/2]
const word & geometricType () const inline noexcept
Definition at line 169 of file geometricSurfacePatch.H.
Referenced by Foam::operator==(), and Foam::operator==().
geometricType() [2/2]
word & geometricType () inline noexcept
Definition at line 175 of file geometricSurfacePatch.H.
write()
void write (Ostream & os) const
Definition at line 90 of file geometricSurfacePatch.C.
References os(), and Ostream::writeEntry().
Referenced by surfacePatch::write().
writeDict()
void writeDict (Ostream & os) const inline
Definition at line 208 of file geometricSurfacePatch.H.
References os(), and write().
Member Data Documentation
emptyType
constexpr const char* const emptyType = "empty" static constexpr
Definition at line 67 of file geometricSurfacePatch.H.
Referenced by boundaryMesh::readTriSurface().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/Identifiers/surface/geometricSurfacePatch.H
src/OpenFOAM/meshes/Identifiers/surface/geometricSurfacePatch.C