OpenFOAM: SRFVelocityFvPatchVectorField Class Reference
SRFVelocityFvPatchVectorField Class Reference
Boundary conditions » Inlet | Boundary conditions » Wall
Velocity condition to be used in conjunction with the single rotating frame (SRF) model (see: SRFModel class)
#include <SRFVelocityFvPatchVectorField.H>
Public Member Functions
TypeName ("SRFVelocity")
SRFVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
SRFVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
SRFVelocityFvPatchVectorField (const SRFVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
SRFVelocityFvPatchVectorField (const SRFVelocityFvPatchVectorField &)
virtual tmp< fvPatchVectorField > clone () const
SRFVelocityFvPatchVectorField (const SRFVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
bool relative () const
virtual void autoMap (const fvPatchFieldMapper &)
virtual void rmap (const fvPatchVectorField &, const labelList &)
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
Velocity condition to be used in conjunction with the single rotating frame (SRF) model (see: SRFModel class)
Given the free stream velocity in the absolute frame, the condition applies the appropriate rotation transformation in time and space to determine the local velocity.
The optional relative flag switches the behaviour of the patch such that:
relative = yes: inlet velocity applied 'as is':
relative = no : SRF velocity is subtracted from the inlet velocity:
where
= patch velocity [m/s]
= user-specified inlet velocity
= SRF velocity
Usage
Property Description Required Default value
inletValue inlet velocity yes
relative inletValue relative motion to the SRF? yes
Example of the boundary condition specification:
    <patchName>
    {
        type            SRFVelocity;
        inletValue      uniform (0 0 0);
        relative        yes;
        value           uniform (0 0 0);    // initial value
    }
See also
Foam::fixedValueFvPatchField
Source files
SRFVelocityFvPatchVectorField.H
SRFVelocityFvPatchVectorField.C
Definition at line 127 of file SRFVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
SRFVelocityFvPatchVectorField() [1/5]
SRFVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Definition at line 29 of file SRFVelocityFvPatchVectorField.C.
SRFVelocityFvPatchVectorField() [2/5]
SRFVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Definition at line 55 of file SRFVelocityFvPatchVectorField.C.
SRFVelocityFvPatchVectorField() [3/5]
SRFVelocityFvPatchVectorField (const SRFVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 41 of file SRFVelocityFvPatchVectorField.C.
SRFVelocityFvPatchVectorField() [4/5]
SRFVelocityFvPatchVectorField (const SRFVelocityFvPatchVectorField & srfvpvf)
Definition at line 68 of file SRFVelocityFvPatchVectorField.C.
SRFVelocityFvPatchVectorField() [5/5]
SRFVelocityFvPatchVectorField (const SRFVelocityFvPatchVectorField & srfvpvf, const DimensionedField< vector, volMesh > & iF)
Definition at line 79 of file SRFVelocityFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("SRFVelocity")
clone() [1/2]
virtual tmp< fvPatchVectorField > clone () const inline virtual
Definition at line 180 of file SRFVelocityFvPatchVectorField.H.
clone() [2/2]
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Definition at line 196 of file SRFVelocityFvPatchVectorField.H.
relative()
bool relative () const inline
Definition at line 213 of file SRFVelocityFvPatchVectorField.H.
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Definition at line 93 of file SRFVelocityFvPatchVectorField.C.
References Field< vector >::autoMap().
rmap()
void rmap (const fvPatchVectorField & ptf, const labelList & addr) virtual
Definition at line 103 of file SRFVelocityFvPatchVectorField.C.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 118 of file SRFVelocityFvPatchVectorField.C.
References Foam::operator==().
write()
void write (Ostream & os) const virtual
Definition at line 148 of file SRFVelocityFvPatchVectorField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntry(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/finiteVolume/cfdTools/general/SRF/derivedFvPatchFields/SRFVelocityFvPatchVectorField/SRFVelocityFvPatchVectorField.H
src/finiteVolume/cfdTools/general/SRF/derivedFvPatchFields/SRFVelocityFvPatchVectorField/SRFVelocityFvPatchVectorField.C