OpenFOAM: fieldsDistributor Class Reference
fieldsDistributor Class Reference
#include <fieldsDistributor.H>
Static Public Member Functions
template<class GeoField >
static void readField (const IOobject &io, const typename GeoField::Mesh &mesh, const label i, PtrList< GeoField > &fields)
template<class Type , template< class > class PatchField, class GeoMesh >
static void readField (const IOobject &io, const typename GeoMesh::Mesh &mesh, const label i, PtrList< GeometricField< Type, PatchField, GeoMesh > > &fields)
template<class Type , template< class > class PatchField, class GeoMesh >
static void readFields (const typename GeoMesh::Mesh &mesh, const IOobjectList &objects, PtrList< GeometricField< Type, PatchField, GeoMesh > > &fields, const bool readOldTime)
template<class Mesh , class GeoField >
static void readFields (const Mesh &mesh, const IOobjectList &objects, PtrList< GeoField > &fields)
template<class GeoField , class MeshSubsetter >
static void readFields (const bitSet &haveMeshOnProc, const MeshSubsetter *subsetter, const typename GeoField::Mesh &mesh, IOobjectList &allObjects, PtrList< GeoField > &fields, const bool deregister=false)
template<class GeoField , class MeshSubsetter >
static void readFields (const boolUList &haveMeshOnProc, const MeshSubsetter *subsetter, const typename GeoField::Mesh &mesh, IOobjectList &allObjects, PtrList< GeoField > &fields, const bool deregister=false)
template<class GeoField , class MeshSubsetter >
static void readFields (const boolUList &haveMeshOnProc, const typename GeoField::Mesh &mesh, const autoPtr< MeshSubsetter > &subsetter, IOobjectList &allObjects, PtrList< GeoField > &fields, const bool deregister=false)
template<class GeoField , class MeshSubsetter >
static void readFields (const boolUList &haveMeshOnProc, refPtr< fileOperation > &readHandler, const typename GeoField::Mesh &mesh, const autoPtr< MeshSubsetter > &subsetter, IOobjectList &allObjects, PtrList< GeoField > &fields, const bool deregister=false)
Detailed Description
Definition at line 50 of file fieldsDistributor.H.
Member Function Documentation
readField() [1/2]
template<class GeoField > void readField (const IOobject & io, const typename GeoField::Mesh & mesh, const label i, PtrList< GeoField > & fields) static
Definition at line 24 of file fieldsDistributorTemplates.C.
References fields, io(), and mesh.
readField() [2/2]
template<class Type , template< class > class PatchField, class GeoMesh > void readField (const IOobject & io, const typename GeoMesh::Mesh & mesh, const label i, PtrList< GeometricField< Type, PatchField, GeoMesh > > & fields) static
Definition at line 37 of file fieldsDistributorTemplates.C.
References fields, io(), and mesh.
readFields() [1/6]
template<class Type , template< class > class PatchField, class GeoMesh > void readFields (const typename GeoMesh::Mesh & mesh, const IOobjectList & objects, PtrList< GeometricField< Type, PatchField, GeoMesh > > & fields, const bool readOldTime) static
Definition at line 50 of file fieldsDistributorTemplates.C.
References fields, forAll, mesh, and UPtrList< T >::size().
readFields() [2/6]
template<class Mesh , class GeoField > void readFields (const Mesh & mesh, const IOobjectList & objects, PtrList< GeoField > & fields) static
Definition at line 74 of file fieldsDistributorTemplates.C.
References fields, forAll, mesh, and UPtrList< T >::size().
readFields() [3/6]
template<class GeoField , class MeshSubsetter > void readFields (const bitSet & haveMeshOnProc, const MeshSubsetter * subsetter, const typename GeoField::Mesh & mesh, IOobjectList & allObjects, PtrList< GeoField > & fields, const bool deregister = false) static
Definition at line 366 of file fieldsDistributorTemplates.C.
References fields, and mesh.
readFields() [4/6]
template<class GeoField , class MeshSubsetter > void readFields (const boolUList & haveMeshOnProc, const MeshSubsetter * subsetter, const typename GeoField::Mesh & mesh, IOobjectList & allObjects, PtrList< GeoField > & fields, const bool deregister = false) static
Definition at line 391 of file fieldsDistributorTemplates.C.
References fields, and mesh.
readFields() [5/6]
template<class GeoField , class MeshSubsetter > void readFields (const boolUList & haveMeshOnProc, const typename GeoField::Mesh & mesh, const autoPtr< MeshSubsetter > & subsetter, IOobjectList & allObjects, PtrList< GeoField > & fields, const bool deregister = false) static
Definition at line 416 of file fieldsDistributorTemplates.C.
References fields, UPtrList< T >::get(), and mesh.
readFields() [6/6]
template<class GeoField , class MeshSubsetter > void readFields (const boolUList & haveMeshOnProc, refPtr< fileOperation > & readHandler, const typename GeoField::Mesh & mesh, const autoPtr< MeshSubsetter > & subsetter, IOobjectList & allObjects, PtrList< GeoField > & fields, const bool deregister = false) static
Definition at line 441 of file fieldsDistributorTemplates.C.
References fields, UPtrList< T >::get(), and mesh.
The documentation for this class was generated from the following files:
src/OpenFOAM/parallel/fieldsDistributor/fieldsDistributor.H
src/OpenFOAM/parallel/fieldsDistributor/fieldsDistributorTemplates.C