OpenFOAM: fvExpressionField Class Reference
fvExpressionField Class Reference
FunctionObjects » Field function objects
Function object that generates or modifies a field based on expressions.
#include <fvExpressionField.H>
Public Types
enum actionType : unsigned char { opNone = 0 , opNew , opModify }
Public Member Functions
TypeName ("exprField")
fvExpressionField (const word &name, const Time &runTime, const dictionary &dict, const bool loadFromFiles=false)
fvExpressionField (const fvExpressionField &)=delete
void operator= (const fvExpressionField &)=delete
virtual ~fvExpressionField ()
virtual word fieldName () const
virtual bool read (const dictionary &dict)
virtual bool execute ()
virtual bool write ()
Public Member Functions inherited from fvMeshFunctionObject
TypeName ("fvMeshFunctionObject")
fvMeshFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
fvMeshFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
virtual ~fvMeshFunctionObject ()=default
Public Member Functions inherited from regionFunctionObject
TypeName ("regionFunctionObject")
regionFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
regionFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
virtual ~regionFunctionObject ()=default
template<class ObjectType >
const ObjectType * lookupObjectPtr (const word &fieldName) const
template<class ObjectType >
ObjectType * lookupObjectRefPtr (const word &fieldName) const
Public Member Functions inherited from stateFunctionObject
stateFunctionObject (const word &name, const Time &runTime)
virtual ~stateFunctionObject ()=default
dictionary & propertyDict ()
bool foundProperty (const word &entryName) const
void clearTrigger ()
label getTrigger () const
bool setTrigger (const label triggeri)
bool getDict (const word &entryName, dictionary &dict) const
bool getObjectDict (const word &objectName, const word &entryName, dictionary &dict) const
template<class Type >
Type getProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getProperty (const word &entryName, Type &value) const
template<class Type >
void setProperty (const word &entryName, const Type &value)
template<class Type >
Type getObjectProperty (const word &objectName, const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getObjectProperty (const word &objectName, const word &entryName, Type &value) const
template<class Type >
void setObjectProperty (const word &objectName, const word &entryName, const Type &value)
template<class Type >
void setResult (const word &entryName, const Type &value)
template<class Type >
void setObjectResult (const word &objectName, const word &entryName, const Type &value)
template<class Type >
Type getResult (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
Type getObjectResult (const word &objectName, const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getObjectResult (const word &objectName, const word &entryName, Type &value) const
word resultType (const word &entryName) const
word objectResultType (const word &objectName, const word &entryName) const
wordList objectResultEntries () const
wordList objectResultEntries (const word &objectName) const
void writeResultEntries (Ostream &os) const
void writeResultEntries (const word &objectName, Ostream &os) const
void writeAllResultEntries (Ostream &os) const
Public Member Functions inherited from timeFunctionObject
timeFunctionObject (const word &name, const Time &runTime)
virtual ~timeFunctionObject ()=default
const Time & time () const
objectRegistry & storedObjects ()
const objectRegistry & storedObjects () const
Public Member Functions inherited from functionObject
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name, const bool withNamePrefix=defaultUseNamePrefix)
autoPtr< functionObject > clone () const
virtual ~functionObject ()=default
virtual const word & type () const =0
const word & name () const noexcept
bool useNamePrefix () const noexcept
bool useNamePrefix (bool on) noexcept
virtual bool execute (const label subIndex)
virtual bool end ()
virtual bool adjustTimeStep ()
virtual bool filesModified () const
virtual void updateMesh (const mapPolyMesh &mpm)
virtual void movePoints (const polyMesh &mesh)
Static Public Attributes
static const Enum< actionType > actionNames_
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
static bool defaultUseNamePrefix
static word outputPrefix
Protected Member Functions
template<class FieldType >
bool loadAndStore (const IOobject &io)
template<class Type >
bool loadField (const IOobject &io)
label loadFields (const UList< word > &fieldSet_)
template<class GeoField >
bool setField (GeoField &output, const GeoField &evaluated, const boolField &cond)
bool performAction (bool doWrite)
Protected Member Functions inherited from fvMeshFunctionObject
fvMeshFunctionObject (const fvMeshFunctionObject &)=delete
void operator= (const fvMeshFunctionObject &)=delete
Protected Member Functions inherited from regionFunctionObject
virtual const objectRegistry & obr () const
template<class ObjectType >
bool foundObject (const word &fieldName) const
template<class ObjectType >
const ObjectType * cfindObject (const word &fieldName) const
template<class ObjectType >
const ObjectType * findObject (const word &fieldName) const
template<class ObjectType >
ObjectType * findObject (const word &fieldName)
template<class ObjectType >
ObjectType * getObjectPtr (const word &fieldName) const
template<class ObjectType >
const ObjectType & lookupObject (const word &fieldName) const
template<class ObjectType >
ObjectType & lookupObjectRef (const word &fieldName) const
template<class ObjectType >
bool store (word &fieldName, const tmp< ObjectType > &tfield, bool cacheable=false)
template<class ObjectType >
bool storeInDb (const word &fieldName, const tmp< ObjectType > &tfield, const objectRegistry &obr)
bool writeObject (const word &fieldName)
bool clearObject (const word &fieldName)
void clearObjects (const wordList &objNames)
regionFunctionObject (const regionFunctionObject &)=delete
void operator= (const regionFunctionObject &)=delete
Protected Member Functions inherited from stateFunctionObject
const functionObjects::properties & stateDict () const
functionObjects::properties & stateDict ()
stateFunctionObject (const stateFunctionObject &)=delete
void operator= (const stateFunctionObject &)=delete
Protected Member Functions inherited from timeFunctionObject
void clearOutputObjects (const wordList &objNames)
timeFunctionObject (const timeFunctionObject &)=delete
void operator= (const timeFunctionObject &)=delete
Protected Member Functions inherited from functionObject
word scopedName (const word &name) const
Protected Attributes
dictionary dict_
word fieldName_
wordList preloadFields_
expressions::exprString maskExpr_
expressions::exprString valueExpr_
dimensionSet dimensions_
actionType action_
bool autowrite_
bool store_
bool hasDimensions_
bool loadFromFiles_
autoPtr< expressions::volumeExprDriver > driver_
Protected Attributes inherited from fvMeshFunctionObject
const fvMesh & mesh_
Protected Attributes inherited from regionFunctionObject
word subRegistryName_
const objectRegistry & obr_
const objectRegistry * obrPtr_
Protected Attributes inherited from timeFunctionObject
const Time & time_
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &runTime, const dictionary &dict)
Public Attributes inherited from functionObject
bool log
Detailed Description
Function object that generates or modifies a field based on expressions.
Usage
A minimal example:
<name1>
{
    type    exprField;
    libs    (fieldFunctionObjects);
    field   pTotal;
    expression  "p + 0.5*(rho*magSqr(U))";
    dimensions  [ Pa ];
}
// Modify an existing field
<name2>
{
    type    exprField;
    libs    (fieldFunctionObjects);
    field   pTotal;
    action  modify;
    // Static pressure only in these regions
    fieldMask   "(mag(pos()) < 0.05) && (pos().y() > 0)";
    expression  "p";
}
where the entries mean:
Property Description Type Reqd Dflt
type Type name: exprField word yes
libs Libraries: fieldFunctionObjects wordList yes
field Name of input or output field word yes
expression Field evaluation expression string yes
action Type of operation: see below word no new
autowrite Add AUTO_WRITE to created field bool no false
store Store calculated field bool no true
fieldMask Masking as logical expression string no ""
dimensions Apply specified dimensions to created field dim-spec no
readFields Preload named fields (post-process mode) wordList no
useNamePrefix Add prefix scoping to output name bool no false
Options for the action entry:
none : No operation
new : Define field based on expression (default)
modify : Adjust field according to expression and fieldMask
Note
The useNamePrefix entry is always ignored for the modify action.
Source files
fvExpressionField.H
fvExpressionField.C
Definition at line 191 of file fvExpressionField.H.
Member Enumeration Documentation
actionType
enum actionType : unsigned char
Enumerator
opNone
No operation.
opNew
Create/overwrite field (default)
opModify
Modify existing field.
Definition at line 200 of file fvExpressionField.H.
Constructor & Destructor Documentation
fvExpressionField() [1/2]
fvExpressionField (const word & name, const Time & runTime, const dictionary & dict, const bool loadFromFiles = false)
Definition at line 288 of file fvExpressionField.C.
References dict, and fvExpressionField::read().
fvExpressionField() [2/2]
fvExpressionField (const fvExpressionField &) delete
~fvExpressionField()
~fvExpressionField () virtual
Definition at line 315 of file fvExpressionField.C.
Member Function Documentation
loadAndStore()
template<class FieldType > bool loadAndStore (const IOobject & io) protected
Definition at line 125 of file fvExpressionField.C.
References Foam::endl(), io(), Log, and fvMeshFunctionObject::mesh_.
loadField()
template<class Type > bool loadField (const IOobject & io) protected
|| loadAndStore<VolumeInternalField<Type>>(io)
Definition at line 142 of file fvExpressionField.C.
References io().
loadFields()
Foam::label loadFields (const UList< word > & fieldSet_) protected
Definition at line 153 of file fvExpressionField.C.
References DebugInfo, Foam::endl(), io(), IOobjectOption::MUST_READ, and IOobjectOption::NO_WRITE.
setField()
template<class GeoField > bool setField (GeoField & output, const GeoField & evaluated, const boolField & cond) protected
Definition at line 214 of file fvExpressionField.C.
References Foam::doCorrectBoundaryConditions(), UPtrList< T >::empty(), Foam::endl(), forAll, Foam::Info, Foam::name(), Foam::nl, Foam::output(), Foam::reduce(), Foam::returnReduce(), and UPtrList< T >::size().
performAction()
bool performAction (bool doWrite) protected
Definition at line 436 of file fvExpressionField.C.
References IOobjectOption::AUTO_WRITE, doLocalCode, Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::fieldGeoType(), UPtrList< T >::get(), Foam::name(), Foam::nl, PtrList< T >::release(), Foam::type(), and WarningInFunction.
TypeName()
TypeName ("exprField")
operator=()
void operator= (const fvExpressionField &) delete
fieldName()
Foam::word fieldName () const virtual
Definition at line 321 of file fvExpressionField.C.
References word::null.
read()
bool read (const dictionary & dict) virtual
Reimplemented from regionFunctionObject.
Definition at line 343 of file fvExpressionField.C.
References PtrList< T >::clear(), dict, Foam::endl(), Log, Foam::name(), Foam::nl, functionObject::read(), exprDriver::SEARCH_FILES, exprDriver::SEARCH_REGISTRY, and Foam::type().
Referenced by fvExpressionField::fvExpressionField().
execute()
bool execute () virtual
Implements functionObject.
Definition at line 672 of file fvExpressionField.C.
write()
bool write () virtual
Implements functionObject.
Definition at line 678 of file fvExpressionField.C.
Member Data Documentation
actionNames_
const Foam::Enum< Foam::functionObjects::fvExpressionField::actionType > actionNames_ static
Definition at line 208 of file fvExpressionField.H.
dict_
dictionary dict_ protected
Definition at line 216 of file fvExpressionField.H.
fieldName_
word fieldName_ protected
Definition at line 219 of file fvExpressionField.H.
preloadFields_
wordList preloadFields_ protected
Definition at line 222 of file fvExpressionField.H.
maskExpr_
expressions::exprString maskExpr_ protected
Definition at line 225 of file fvExpressionField.H.
valueExpr_
expressions::exprString valueExpr_ protected
Definition at line 228 of file fvExpressionField.H.
dimensions_
dimensionSet dimensions_ protected
Definition at line 231 of file fvExpressionField.H.
action_
actionType action_ protected
Definition at line 234 of file fvExpressionField.H.
autowrite_
bool autowrite_ protected
Definition at line 237 of file fvExpressionField.H.
store_
bool store_ protected
Definition at line 240 of file fvExpressionField.H.
hasDimensions_
bool hasDimensions_ protected
Definition at line 243 of file fvExpressionField.H.
loadFromFiles_
bool loadFromFiles_ protected
Definition at line 246 of file fvExpressionField.H.
driver_
autoPtr<expressions::volumeExprDriver> driver_ protected
Definition at line 248 of file fvExpressionField.H.
The documentation for this class was generated from the following files:
src/functionObjects/field/expressions/fvExpressionField.H
src/functionObjects/field/expressions/fvExpressionField.C