OpenFOAM: wedgeFaPatch Class Reference
wedgeFaPatch Class Reference
Wedge front and back plane patch.
#include <wedgeFaPatch.H>
Public Member Functions
TypeName ("wedge")
wedgeFaPatch (const word &name, const dictionary &dict, const label index, const faBoundaryMesh &bm, const word &patchType)
virtual ~wedgeFaPatch ()=default
const vector & axis () const
const vector & centreNormal () const
const tensor & edgeT () const
const tensor & faceT () const
label axisPoint () const
Public Member Functions inherited from faPatch
TypeName ("patch")
declareRunTimeSelectionTable (autoPtr, faPatch, dictionary,(const word &name, const dictionary &dict, const label index, const faBoundaryMesh &bm, const word &patchType),(name, dict, index, bm, patchType))
faPatch (const word &name, const labelUList &edgeLabels, const label index, const faBoundaryMesh &bm, const label nbrPolyPatchi, const word &patchType)
faPatch (const word &name, const dictionary &dict, const label index, const faBoundaryMesh &bm, const word &patchType)
faPatch (const faPatch &p, const faBoundaryMesh &bm)
faPatch (const faPatch &p, const faBoundaryMesh &bm, const label index, const labelUList &edgeLabels, const label nbrPolyPatchi)
virtual autoPtr< faPatch > clone (const faBoundaryMesh &bm) const
virtual autoPtr< faPatch > clone (const faBoundaryMesh &bm, const labelUList &edgeLabels, const label index, const label nbrPolyPatchi) const
virtual ~faPatch ()
const labelList & edgeLabels () const noexcept
label nPoints () const
label nEdges () const noexcept
label ngbPolyPatchIndex () const noexcept
const faBoundaryMesh & boundaryMesh () const noexcept
virtual bool coupled () const
label offset () const
label start () const
virtual label size () const
label whichEdge (const label edgei) const
template<class T >
const List< T >::subList patchSlice (const List< T > &values) const
template<class T >
const List< T >::subList boundarySlice (const List< T > &values) const
virtual void write (Ostream &) const
List< labelPair > boundaryConnections () const
labelList boundaryProcs () const
List< labelPair > boundaryProcSizes () const
const labelList & pointLabels () const
const labelListList & pointEdges () const
tmp< vectorField > ngbPolyPatchFaceNormals () const
tmp< vectorField > ngbPolyPatchPointNormals () const
const labelUList & edgeFaces () const
const vectorField & edgeCentres () const
const vectorField & edgeLengths () const
const scalarField & magEdgeLengths () const
tmp< vectorField > edgeNormals () const
tmp< vectorField > edgeFaceCentres () const
virtual tmp< vectorField > delta () const
virtual void makeWeights (scalarField &) const
const scalarField & weights () const
virtual void makeDeltaCoeffs (scalarField &) const
void makeCorrectionVectors (vectorField &) const
const scalarField & deltaCoeffs () const
void resetEdges (const labelUList &newEdges)
void resetEdges (labelList &&newEdges)
template<class Type >
void patchInternalField (const UList< Type > &internalData, const labelUList &addressing, Field< Type > &pfld) const
template<class Type >
void patchInternalField (const UList< Type > &internalData, Field< Type > &pfld) const
template<class Type >
tmp< Field< Type > > patchInternalField (const UList< Type > &internalData) const
template<class GeometricField , class AnyType = bool>
const GeometricField::Patch & patchField (const GeometricField &gf) const
template<class GeometricField , class AnyType = bool>
const GeometricField::Patch & lookupPatchField (const word &name, const GeometricField *=nullptr, const AnyType *=nullptr) const
template<class Type >
Foam::tmp< Foam::Field< Type > > patchInternalField (const UList< Type > &internalData) const
Public Member Functions inherited from patchIdentifier
patchIdentifier (const patchIdentifier &)=default
patchIdentifier & operator= (const patchIdentifier &)=default
virtual ~patchIdentifier ()=default
patchIdentifier ()
patchIdentifier (const word &name, const label index)
patchIdentifier (const word &name, const label index, const word &physicalType, const wordList &inGroups=wordList())
patchIdentifier (const word &name, const dictionary &dict, const label index)
patchIdentifier (const patchIdentifier &ident, const label index)
const word & name () const noexcept
word & name () noexcept
label index () const noexcept
label & index () noexcept
const word & physicalType () const noexcept
word & physicalType () noexcept
const wordList & inGroups () const noexcept
wordList & inGroups () noexcept
bool inGroup (const word &name) const
void write (Ostream &os) const
Public Member Functions inherited from List< label >
constexpr List () noexcept
List (const label len)
List (const label len, const label &val)
List (const label len, const Foam::zero)
List (const Foam::one, const label &val)
List (const Foam::one, label &&val)
List (const Foam::one, const Foam::zero)
List (const List< label > &a)
List (const UList< label > &a)
List (List< label > &a, bool reuse)
List (const UList< label > &list, const labelUList &indices)
List (const UList< label > &list, const FixedList< label, N > &indices)
List (const FixedList< label, N > &list)
List (const PtrList< label > &list)
List (const SLList< label > &list)
List (const IndirectListBase< label, Addr > &list)
List (std::initializer_list< label > list)
List (List< label > &&list)
List (DynamicList< label, SizeMin > &&list)
List (SLList< label > &&list)
List (Istream &is)
autoPtr< List< label > > clone () const
~List ()
void clear ()
void resize (const label len)
void resize (const label len, const label &val)
void resize (const label newLen)
void resize_nocopy (const label len)
void setSize (const label n)
void setSize (const label n, const label &val)
void transfer (List< label > &list)
void transfer (DynamicList< label, SizeMin > &list)
label & newElmt (const label i)
label & emplace_back (Args &&... args)
void push_back (const label &val)
void push_back (label &&val)
void push_back (const UList< label > &list)
void push_back (const IndirectListBase< label, Addr > &list)
label push_uniq (const label &val)
void pop_back (label n=1)
void operator= (const UList< label > &a)
void operator= (const List< label > &list)
void operator= (const SLList< label > &list)
void operator= (const IndirectListBase< label, Addr > &list)
void operator= (const FixedList< label, N > &list)
void operator= (std::initializer_list< label > list)
void operator= (const label &val)
void operator= (const Foam::zero)
void operator= (List< label > &&list)
void operator= (DynamicList< label, SizeMin > &&list)
void operator= (SLList< label > &&list)
Istream & readList (Istream &is)
Istream & readList (Istream &is)
Istream & readList (Istream &is)
void shallowCopy (const UList< label > &)=delete
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type set (const label i, bool val=true)
void append (const label &val)
void append (label &&val)
void append (const UList< label > &list)
void append (const IndirectListBase< label, Addr > &list)
label appendUniq (const label &val)
Public Member Functions inherited from UList< T >
UList (const UList< T > &)=default
constexpr UList () noexcept
UList (T *__restrict__ v, const label len) noexcept
label fcIndex (const label i) const noexcept
label rcIndex (const label i) const noexcept
const T & fcValue (const label i) const
T & fcValue (const label i)
const T & rcValue (const label i) const
T & rcValue (const label i)
const T * cdata () const noexcept
T * data () noexcept
const char * cdata_bytes () const noexcept
char * data_bytes () noexcept
T & front ()
const T & front () const
T & back ()
const T & back () const
std::streamsize size_bytes () const noexcept
std::streamsize byteSize () const
void checkStart (const label start) const
void checkSize (const label size) const
void checkRange (const label start, const label len) const
void checkIndex (const label i) const
bool uniform () const
label find (const T &val, label pos=0) const
label rfind (const T &val, label pos=-1) const
bool contains (const T &val, label pos=0) const
void moveFirst (const label i)
void moveLast (const label i)
void swapFirst (const label i)
void swapLast (const label i)
void shallowCopy (const UList< T > &list)
void deepCopy (const UList< T > &list)
template<class Addr >
void deepCopy (const IndirectListBase< T, Addr > &list)
SubList< T > slice (const label pos, label len=-1)
const SubList< T > slice (const label pos, label len=-1) const
SubList< T > slice (const labelRange &range)
const SubList< T > slice (const labelRange &range) const
T & operator[] (const label i)
const T & operator[] (const label i) const
operator const Foam::List< T > & () const
void operator= (const T &val)
void operator= (const Foam::zero)
iterator begin () noexcept
iterator end () noexcept
iterator begin (const label i) noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
const_iterator begin () const noexcept
const_iterator end () const noexcept
const_iterator cbegin (const label i) const noexcept
const_iterator begin (const label i) const noexcept
reverse_iterator rbegin ()
reverse_iterator rend ()
const_reverse_iterator crbegin () const
const_reverse_iterator crend () const
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
bool empty () const noexcept
label size () const noexcept
void swap (UList< T > &list)
bool operator== (const UList< T > &a) const
bool operator!= (const UList< T > &a) const
bool operator< (const UList< T > &list) const
bool operator> (const UList< T > &a) const
bool operator<= (const UList< T > &a) const
bool operator>= (const UList< T > &a) const
Istream & readList (Istream &is)
void writeEntry (const word &keyword, Ostream &os) const
Ostream & writeList (Ostream &os, const label shortLen=0) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type test (const label i) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type get (const label i) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type unset (const label i)
T & first ()
const T & first () const
T & last ()
const T & last () const
bool found (const T &val, label pos=0) const
Istream & readList (Istream &is)
Ostream & writeList (Ostream &os, const label) const
const bool & operator[] (const label i) const
UPstream::commsStruct & operator[] (const label procID)
const UPstream::commsStruct & operator[] (const label procID) const
Foam::UPstream::commsStruct & operator[] (const label procID)
const Foam::UPstream::commsStruct & operator[] (const label procID) const
Ostream & writeList (Ostream &os, const label) const
Istream & readList (Istream &is)
Additional Inherited Members
Public Types inherited from faPatch
typedef faBoundaryMesh BoundaryMesh
Public Types inherited from List< label >
typedef SubList< label > subList
Public Types inherited from UList< T >
typedef T value_type
typedef T * pointer
typedef const T * const_pointer
typedef T & reference
typedef const T & const_reference
typedef T * iterator
typedef const T * const_iterator
typedef label size_type
typedef label difference_type
typedef std::reverse_iterator< iterator > reverse_iterator
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
Static Public Member Functions inherited from faPatch
static autoPtr< faPatch > New (const word &name, const dictionary &dict, const label index, const faBoundaryMesh &bm)
static autoPtr< faPatch > New (const word &patchType, const word &name, const dictionary &dict, const label index, const faBoundaryMesh &bm)
static bool constraintType (const word &patchType)
static wordList constraintTypes ()
Static Public Member Functions inherited from patchIdentifier
static word defaultName (const label n=-1)
Static Public Member Functions inherited from List< label >
static const List< label > & null ()
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
static constexpr label max_size () noexcept
Protected Member Functions inherited from faPatch
void calcPointLabels () const
void calcPointEdges () const
virtual void initGeometry (PstreamBuffers &)
virtual void calcGeometry (PstreamBuffers &)
virtual void initMovePoints (PstreamBuffers &, const pointField &)
virtual void movePoints (PstreamBuffers &, const pointField &)
virtual void initUpdateMesh (PstreamBuffers &)
virtual void updateMesh (PstreamBuffers &)
Protected Member Functions inherited from UList< T >
void setAddressableSize (const label n) noexcept
void size (const label n)
void writeEntry (Ostream &os) const
labelRange validateRange (const labelRange &requestedRange) const
UList< T > & operator= (const UList< T > &)=delete
void writeEntry (Ostream &os) const
void writeEntry (Ostream &os) const
Detailed Description
Wedge front and back plane patch.
Author Zeljko Tukovic, FMENA Hrvoje Jasak, Wikki Ltd.
Source files
wedgeFaPatch.H
wedgeFaPatch.C
Definition at line 52 of file wedgeFaPatch.H.
Constructor & Destructor Documentation
wedgeFaPatch()
wedgeFaPatch (const word & name, const dictionary & dict, const label index, const faBoundaryMesh & bm, const word & patchType)
Definition at line 71 of file wedgeFaPatch.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, patchIdentifier::name(), and faPatch::ngbPolyPatchIndex().
~wedgeFaPatch()
virtual ~wedgeFaPatch () virtual default
Member Function Documentation
TypeName()
TypeName ("wedge")
axis()
const vector & axis () const inline
Definition at line 95 of file wedgeFaPatch.H.
References wedgePolyPatch::axis().
centreNormal()
const vector & centreNormal () const inline
Definition at line 101 of file wedgeFaPatch.H.
References wedgePolyPatch::centreNormal().
edgeT()
const tensor & edgeT () const inline
Definition at line 107 of file wedgeFaPatch.H.
References wedgePolyPatch::faceT().
faceT()
const tensor & faceT () const inline
Definition at line 113 of file wedgeFaPatch.H.
References wedgePolyPatch::cellT().
axisPoint()
label axisPoint () const inline
Definition at line 119 of file wedgeFaPatch.H.
The documentation for this class was generated from the following files:
src/finiteArea/faMesh/faPatches/constraint/wedge/wedgeFaPatch.H
src/finiteArea/faMesh/faPatches/constraint/wedge/wedgeFaPatch.C