OpenFOAM: filmHeightInletVelocityFvPatchVectorField Class Reference
filmHeightInletVelocityFvPatchVectorField Class Reference
Boundary conditions » Region boundary conditions » Surface film boundary conditions
This boundary condition is designed to be used in conjunction with surface film modelling. It provides a velocity inlet boundary condition for patches where the film height is specified. The inflow velocity is obtained from the flux with a direction normal to the patch faces using:
#include <filmHeightInletVelocityFvPatchVectorField.H>
Public Member Functions
TypeName ("filmHeightInletVelocity")
filmHeightInletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
filmHeightInletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
filmHeightInletVelocityFvPatchVectorField (const filmHeightInletVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
filmHeightInletVelocityFvPatchVectorField (const filmHeightInletVelocityFvPatchVectorField &)
virtual tmp< fvPatchVectorField > clone () const
filmHeightInletVelocityFvPatchVectorField (const filmHeightInletVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
virtual bool assignable () const
const word & phiName () const
word & phiName ()
const word & rhoName () const
word & rhoName ()
const word & deltafName () const
word & deltafName ()
virtual void updateCoeffs ()
virtual void write (Ostream &) const
virtual void operator= (const fvPatchField< vector > &pvf)
Detailed Description
This boundary condition is designed to be used in conjunction with surface film modelling. It provides a velocity inlet boundary condition for patches where the film height is specified. The inflow velocity is obtained from the flux with a direction normal to the patch faces using:
where
= patch velocity [m/s]
= patch normal vector
= mass flux [kg/s]
= density [kg/m3]
= patch face area vectors [m2]
= film height [m]
Usage
Property Description Required Default value
phi Flux field name no phi
rho density field name no rho
deltaf height field name no deltaf
Example of the boundary condition specification:
    <patchName>
    {
        type            filmHeightInletVelocity;
        phi             phi;
        rho             rho;
        deltaf          deltaf;
        value           uniform (0 0 0); // initial velocity / [m/s]
    }
See also
Foam::fixedValueFvPatchField
Source files
filmHeightInletVelocityFvPatchVectorField.H
filmHeightInletVelocityFvPatchVectorField.C
Definition at line 134 of file filmHeightInletVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
filmHeightInletVelocityFvPatchVectorField() [1/5]
filmHeightInletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Definition at line 29 of file filmHeightInletVelocityFvPatchVectorField.C.
filmHeightInletVelocityFvPatchVectorField() [2/5]
filmHeightInletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Definition at line 59 of file filmHeightInletVelocityFvPatchVectorField.C.
filmHeightInletVelocityFvPatchVectorField() [3/5]
filmHeightInletVelocityFvPatchVectorField (const filmHeightInletVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 43 of file filmHeightInletVelocityFvPatchVectorField.C.
filmHeightInletVelocityFvPatchVectorField() [4/5]
filmHeightInletVelocityFvPatchVectorField (const filmHeightInletVelocityFvPatchVectorField & fhivpvf)
Definition at line 74 of file filmHeightInletVelocityFvPatchVectorField.C.
filmHeightInletVelocityFvPatchVectorField() [5/5]
filmHeightInletVelocityFvPatchVectorField (const filmHeightInletVelocityFvPatchVectorField & fhivpvf, const DimensionedField< vector, volMesh > & iF)
Definition at line 87 of file filmHeightInletVelocityFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("filmHeightInletVelocity")
clone() [1/2]
virtual tmp< fvPatchVectorField > clone () const inline virtual
Definition at line 190 of file filmHeightInletVelocityFvPatchVectorField.H.
clone() [2/2]
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Definition at line 206 of file filmHeightInletVelocityFvPatchVectorField.H.
assignable()
virtual bool assignable () const inline virtual
Definition at line 221 of file filmHeightInletVelocityFvPatchVectorField.H.
phiName() [1/2]
const word & phiName () const inline
Definition at line 227 of file filmHeightInletVelocityFvPatchVectorField.H.
phiName() [2/2]
word & phiName () inline
Definition at line 233 of file filmHeightInletVelocityFvPatchVectorField.H.
rhoName() [1/2]
const word & rhoName () const inline
Definition at line 239 of file filmHeightInletVelocityFvPatchVectorField.H.
rhoName() [2/2]
word & rhoName () inline
Definition at line 245 of file filmHeightInletVelocityFvPatchVectorField.H.
deltafName() [1/2]
const word & deltafName () const inline
Definition at line 251 of file filmHeightInletVelocityFvPatchVectorField.H.
deltafName() [2/2]
word & deltafName () inline
Definition at line 257 of file filmHeightInletVelocityFvPatchVectorField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 103 of file filmHeightInletVelocityFvPatchVectorField.C.
References n, and Foam::operator==().
write()
void write (Ostream & os) const virtual
Definition at line 123 of file filmHeightInletVelocityFvPatchVectorField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntryIfDifferent(), and fvPatchField< Type >::writeValueEntry().
operator=()
void operator= (const fvPatchField< vector > & pvf) virtual
Definition at line 135 of file filmHeightInletVelocityFvPatchVectorField.C.
References fvPatchField< Type >::operator=().
The documentation for this class was generated from the following files:
src/regionModels/surfaceFilmModels/derivedFvPatchFields/filmHeightInletVelocity/filmHeightInletVelocityFvPatchVectorField.H
src/regionModels/surfaceFilmModels/derivedFvPatchFields/filmHeightInletVelocity/filmHeightInletVelocityFvPatchVectorField.C