OpenFOAM: TimeFunction1< Type > Class Template Reference
TimeFunction1< Type > Class Template Reference
Light wrapper around Function1 to provide a mechanism to update time-based entries.
#include <TimeFunction1.H>
Public Member Functions
TimeFunction1 (const Time &runTime, const word &name, const dictionary &dict)
TimeFunction1 (const Time &runTime, const word &entryName)
TimeFunction1 (const TimeFunction1< Type > &rhs)
virtual ~TimeFunction1 ()=default
void reset (const dictionary &dict)
const word & name () const
virtual Type value (const scalar x) const
virtual Type integrate (const scalar x1, const scalar x2) const
virtual void writeData (Ostream &os) const
Protected Attributes
const Time & time_
const word name_
autoPtr< Function1< Type > > entry_
Friends
Ostream & operator<< (Ostream &os, const TimeFunction1< Type > &de)
Detailed Description
template<class Type>
class Foam::TimeFunction1< Type >
Light wrapper around Function1 to provide a mechanism to update time-based entries.
Source files
TimeFunction1.H
TimeFunction1.C
Definition at line 56 of file TimeFunction1.H.
Constructor & Destructor Documentation
TimeFunction1() [1/3]
template<class Type > TimeFunction1 (const Time & runTime, const word & name, const dictionary & dict)
Definition at line 27 of file TimeFunction1.C.
References Foam::New().
TimeFunction1() [2/3]
template<class Type > TimeFunction1 (const Time & runTime, const word & entryName)
Definition at line 44 of file TimeFunction1.C.
TimeFunction1() [3/3]
template<class Type > TimeFunction1 (const TimeFunction1< Type > & rhs)
Definition at line 57 of file TimeFunction1.C.
References PtrList< T >::clone(), and TimeFunction1< Type >::entry_.
~TimeFunction1()
template<class Type > virtual ~TimeFunction1 () virtual default
Member Function Documentation
reset()
template<class Type > void reset (const dictionary & dict)
Definition at line 76 of file TimeFunction1.C.
References dict.
name()
template<class Type > const Foam::word & name () const
Definition at line 84 of file TimeFunction1.C.
value()
template<class Type > Type value (const scalar x) const virtual
Definition at line 91 of file TimeFunction1.C.
References x.
integrate()
template<class Type > Type integrate (const scalar x1, const scalar x2) const virtual
Definition at line 98 of file TimeFunction1.C.
writeData()
template<class Type > void writeData (Ostream & os) const virtual
Definition at line 126 of file TimeFunction1.C.
References os().
Friends And Related Symbol Documentation
operator<<
template<class Type > Ostream & operator<< (Ostream & os, const TimeFunction1< Type > & de) friend
Member Data Documentation
time_
template<class Type > const Time& time_ protected
Definition at line 63 of file TimeFunction1.H.
name_
template<class Type > const word name_ protected
Definition at line 66 of file TimeFunction1.H.
entry_
template<class Type > autoPtr<Function1<Type> > entry_ protected
Definition at line 69 of file TimeFunction1.H.
Referenced by TimeFunction1< Type >::TimeFunction1().
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/functions/TimeFunction1/TimeFunction1.H
src/OpenFOAM/primitives/functions/TimeFunction1/TimeFunction1.C