OpenFOAM: qZeta Class Reference
qZeta Class Reference
Gibson and Dafa'Alla's q-zeta two-equation low-Re turbulence model for incompressible flows.
#include <qZeta.H>
Public Member Functions
TypeName ("qZeta")
qZeta (const geometricOneField &alpha, const geometricOneField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
virtual ~qZeta ()=default
virtual bool read ()
const dimensionedScalar & qMin () const
const dimensionedScalar & zetaMin () const
dimensionedScalar & qMin ()
dimensionedScalar & zetaMin ()
tmp< volScalarField > DqEff () const
tmp< volScalarField > DzetaEff () const
virtual tmp< volScalarField > k () const
virtual tmp< volScalarField > epsilon () const
virtual const volScalarField & q () const
virtual const volScalarField & zeta () const
virtual void correct ()
Public Member Functions inherited from eddyViscosity< incompressible::RASModel >
eddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~eddyViscosity ()=default
virtual tmp< volScalarField > nut () const
virtual tmp< scalarField > nut (const label patchi) const
virtual tmp< volSymmTensorField > R () const
virtual void validate ()
Public Member Functions inherited from linearViscousStress< BasicTurbulenceModel >
linearViscousStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~linearViscousStress ()=default
virtual tmp< volSymmTensorField > devRhoReff () const
virtual tmp< volSymmTensorField > devRhoReff (const volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Protected Member Functions
tmp< volScalarField > fMu () const
tmp< volScalarField > f2 () const
virtual void correctNut ()
Protected Attributes
dimensionedScalar Cmu_
dimensionedScalar C1_
dimensionedScalar C2_
dimensionedScalar sigmaZeta_
Switch anisotropic_
dimensionedScalar qMin_
dimensionedScalar zetaMin_
volScalarField k_
volScalarField epsilon_
volScalarField q_
volScalarField zeta_
Protected Attributes inherited from eddyViscosity< incompressible::RASModel >
volScalarField nut_
Additional Inherited Members
Public Types inherited from eddyViscosity< incompressible::RASModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from linearViscousStress< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Detailed Description
Gibson and Dafa'Alla's q-zeta two-equation low-Re turbulence model for incompressible flows.
This turbulence model is described in:
    Dafa'Alla, A.A., Juntasaro, E. & Gibson, M.M. (1996).
    Calculation of oscillating boundary layers with the
    q-zeta turbulence model.
    Engineering Turbulence Modelling and Experiments 3:
    Proceedings of the Third International Symposium,
    Crete, Greece, May 27-29, 141.
which is a development of the original q-zeta model described in:
    Gibson, M. M., & Dafa'Alla, A. A. (1995).
    Two-equation model for turbulent wall flow.
    AIAA journal, 33(8), 1514-1518.
Source files
qZeta.H
qZeta.C
Definition at line 72 of file qZeta.H.
Constructor & Destructor Documentation
qZeta()
qZeta (const geometricOneField & alpha, const geometricOneField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Definition at line 75 of file qZeta.C.
References Foam::bound(), Foam::type(), qZeta::zeta_, and qZeta::zetaMin_.
~qZeta()
virtual ~qZeta () virtual default
Member Function Documentation
fMu()
tmp< volScalarField > fMu () const protected
Definition at line 42 of file qZeta.C.
References qZeta::anisotropic_, Foam::exp(), qZeta::k_, nu, Foam::pow3(), qZeta::q_, Foam::sqr(), and qZeta::zeta_.
Referenced by qZeta::correctNut().
f2()
tmp< volScalarField > f2 () const protected
Definition at line 59 of file qZeta.C.
References Foam::exp(), qZeta::k_, nu, qZeta::q_, Foam::sqr(), and qZeta::zeta_.
Referenced by qZeta::correct().
correctNut()
void correctNut () protected virtual
Implements eddyViscosity< incompressible::RASModel >.
Definition at line 66 of file qZeta.C.
References qZeta::Cmu_, GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), qZeta::epsilon_, qZeta::fMu(), qZeta::k_, eddyViscosity< incompressible::RASModel >::nut_, and Foam::sqr().
Referenced by qZeta::correct().
TypeName()
TypeName ("qZeta")
read()
bool read () virtual
Implements eddyViscosity< incompressible::RASModel >.
Definition at line 213 of file qZeta.C.
References qZeta::anisotropic_, qZeta::C1_, qZeta::C2_, qZeta::Cmu_, qZeta::qMin_, dimensioned< Type >::readIfPresent(), Switch::readIfPresent(), qZeta::sigmaZeta_, and qZeta::zetaMin_.
qMin() [1/2]
const dimensionedScalar & qMin () const inline
Definition at line 142 of file qZeta.H.
References qZeta::qMin_.
zetaMin() [1/2]
const dimensionedScalar & zetaMin () const inline
Definition at line 148 of file qZeta.H.
References qZeta::zetaMin_.
qMin() [2/2]
dimensionedScalar & qMin () inline
Definition at line 154 of file qZeta.H.
References qZeta::qMin_.
zetaMin() [2/2]
dimensionedScalar & zetaMin () inline
Definition at line 160 of file qZeta.H.
References qZeta::zetaMin_.
DqEff()
tmp< volScalarField > DqEff () const inline
Definition at line 166 of file qZeta.H.
References nu, and eddyViscosity< incompressible::RASModel >::nut_.
Referenced by qZeta::correct().
DzetaEff()
tmp< volScalarField > DzetaEff () const inline
Definition at line 175 of file qZeta.H.
References nu, eddyViscosity< incompressible::RASModel >::nut_, and qZeta::sigmaZeta_.
Referenced by qZeta::correct().
k()
virtual tmp< volScalarField > k () const inline virtual
Implements eddyViscosity< incompressible::RASModel >.
Definition at line 184 of file qZeta.H.
References qZeta::k_.
epsilon()
virtual tmp< volScalarField > epsilon () const inline virtual
Definition at line 190 of file qZeta.H.
References qZeta::epsilon_.
q()
virtual const volScalarField & q () const inline virtual
Definition at line 195 of file qZeta.H.
References qZeta::q_.
zeta()
virtual const volScalarField & zeta () const inline virtual
Definition at line 200 of file qZeta.H.
References qZeta::zeta_.
correct()
void correct () virtual
Implements eddyViscosity< incompressible::RASModel >.
Definition at line 233 of file qZeta.C.
References Foam::bound(), qZeta::C1_, qZeta::C2_, eddyViscosity< BasicTurbulenceModel >::correct(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), qZeta::correctNut(), Foam::fvm::ddt(), Foam::fvm::div(), qZeta::DqEff(), qZeta::DzetaEff(), qZeta::epsilon_, qZeta::f2(), Foam::fvc::grad(), qZeta::k_, Foam::fvm::laplacian(), Foam::magSqr(), Foam::fvc::magSqrGradGrad(), nu, eddyViscosity< incompressible::RASModel >::nut_, qZeta::q_, qZeta::qMin_, solve(), Foam::fvm::Sp(), Foam::sqr(), Foam::fvm::SuSp(), Foam::symm(), qZeta::zeta_, and qZeta::zetaMin_.
Member Data Documentation
Cmu_
dimensionedScalar Cmu_ protected
Definition at line 83 of file qZeta.H.
Referenced by qZeta::correctNut(), and qZeta::read().
C1_
dimensionedScalar C1_ protected
Definition at line 84 of file qZeta.H.
Referenced by qZeta::correct(), and qZeta::read().
C2_
dimensionedScalar C2_ protected
Definition at line 85 of file qZeta.H.
Referenced by qZeta::correct(), and qZeta::read().
sigmaZeta_
dimensionedScalar sigmaZeta_ protected
Definition at line 86 of file qZeta.H.
Referenced by qZeta::DzetaEff(), and qZeta::read().
anisotropic_
Switch anisotropic_ protected
Definition at line 87 of file qZeta.H.
Referenced by qZeta::fMu(), and qZeta::read().
qMin_
dimensionedScalar qMin_ protected
Definition at line 90 of file qZeta.H.
Referenced by qZeta::correct(), qZeta::qMin(), qZeta::qMin(), and qZeta::read().
zetaMin_
dimensionedScalar zetaMin_ protected
Definition at line 93 of file qZeta.H.
Referenced by qZeta::correct(), qZeta::qZeta(), qZeta::read(), qZeta::zetaMin(), and qZeta::zetaMin().
k_
volScalarField k_ protected
Definition at line 97 of file qZeta.H.
Referenced by qZeta::correct(), qZeta::correctNut(), qZeta::f2(), qZeta::fMu(), and qZeta::k().
epsilon_
volScalarField epsilon_ protected
Definition at line 98 of file qZeta.H.
Referenced by qZeta::correct(), qZeta::correctNut(), and qZeta::epsilon().
q_
volScalarField q_ protected
Definition at line 100 of file qZeta.H.
Referenced by qZeta::correct(), qZeta::f2(), qZeta::fMu(), and qZeta::q().
zeta_
volScalarField zeta_ protected
Definition at line 101 of file qZeta.H.
Referenced by qZeta::correct(), qZeta::f2(), qZeta::fMu(), qZeta::qZeta(), and qZeta::zeta().
The documentation for this class was generated from the following files:
src/TurbulenceModels/incompressible/turbulentTransportModels/RAS/qZeta/qZeta.H
src/TurbulenceModels/incompressible/turbulentTransportModels/RAS/qZeta/qZeta.C