OpenFOAM: kOmegaSSTDES< BasicTurbulenceModel > Class Template Reference
kOmegaSSTDES< BasicTurbulenceModel > Class Template Reference
Turbulence models » DES turbulence
k-omega-SST DES turbulence model for incompressible and compressible flows.
#include <kOmegaSSTDES.H>
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from kOmegaSSTBase< DESModel< BasicTurbulenceModel > >
typedef BasicEddyViscosityModel::alphaField alphaField
typedef BasicEddyViscosityModel::rhoField rhoField
typedef BasicEddyViscosityModel::transportModel transportModel
Public Member Functions
TypeName ("kOmegaSSTDES")
kOmegaSSTDES (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
virtual ~kOmegaSSTDES ()=default
virtual bool read ()
virtual tmp< volScalarField > lengthScaleRAS () const
virtual tmp< volScalarField > lengthScaleLES (const volScalarField &CDES) const
virtual tmp< volScalarField > LESRegion () const
Public Member Functions inherited from kOmegaSSTBase< DESModel< BasicTurbulenceModel > >
kOmegaSSTBase (const kOmegaSSTBase &)=delete
kOmegaSSTBase (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
void operator= (const kOmegaSSTBase &)=delete
virtual ~kOmegaSSTBase ()=default
tmp< volScalarField > DkEff (const volScalarField &F1) const
tmp< volScalarField > DomegaEff (const volScalarField &F1) const
virtual tmp< volScalarField > k () const
virtual tmp< volScalarField > omega () const
virtual void correct ()
Protected Member Functions
virtual tmp< volScalarField > CDES (const volScalarField &F1) const
virtual void correctNut (const volScalarField &S2)
virtual void correctNut ()
tmp< volScalarField > r (const volScalarField &nur, const volScalarField &magGradU) const
virtual tmp< volScalarField > S2 (const volTensorField &gradU) const
virtual tmp< volScalarField > dTilda (const volScalarField &magGradU, const volScalarField &CDES) const
virtual tmp< volScalarField::Internal > epsilonByk (const volScalarField &F1, const volTensorField &gradU) const
virtual tmp< volScalarField::Internal > GbyNu0 (const volTensorField &gradU, const volScalarField &S2) const
virtual tmp< volScalarField::Internal > GbyNu (const volScalarField::Internal &GbyNu0, const volScalarField::Internal &F2, const volScalarField::Internal &S2) const
Protected Member Functions inherited from kOmegaSSTBase< DESModel< BasicTurbulenceModel > >
void setDecayControl (const dictionary &dict)
virtual tmp< volScalarField > F1 (const volScalarField &CDkOmega) const
virtual tmp< volScalarField > F2 () const
virtual tmp< volScalarField > F3 () const
virtual tmp< volScalarField > F23 () const
tmp< volScalarField > blend (const volScalarField &F1, const dimensionedScalar &psi1, const dimensionedScalar &psi2) const
tmp< volScalarField::Internal > blend (const volScalarField::Internal &F1, const dimensionedScalar &psi1, const dimensionedScalar &psi2) const
tmp< volScalarField > alphaK (const volScalarField &F1) const
tmp< volScalarField > alphaOmega (const volScalarField &F1) const
tmp< volScalarField::Internal > beta (const volScalarField::Internal &F1) const
tmp< volScalarField::Internal > gamma (const volScalarField::Internal &F1) const
virtual tmp< volScalarField::Internal > Pk (const volScalarField::Internal &G) const
virtual tmp< fvScalarMatrix > kSource () const
virtual tmp< fvScalarMatrix > omegaSource () const
virtual tmp< fvScalarMatrix > Qsas (const volScalarField::Internal &S2, const volScalarField::Internal &gamma, const volScalarField::Internal &beta) const
Protected Attributes
Switch useSigma_
dimensionedScalar kappa_
dimensionedScalar CDESkom_
dimensionedScalar CDESkeps_
Protected Attributes inherited from kOmegaSSTBase< DESModel< BasicTurbulenceModel > >
dimensionedScalar alphaK1_
dimensionedScalar alphaK2_
dimensionedScalar alphaOmega1_
dimensionedScalar alphaOmega2_
dimensionedScalar gamma1_
dimensionedScalar gamma2_
dimensionedScalar beta1_
dimensionedScalar beta2_
dimensionedScalar betaStar_
dimensionedScalar a1_
dimensionedScalar b1_
dimensionedScalar c1_
Switch F3_
const volScalarField & y_
volScalarField k_
volScalarField omega_
Switch decayControl_
dimensionedScalar kInf_
dimensionedScalar omegaInf_
Detailed Description
template<class BasicTurbulenceModel>
class Foam::LESModels::kOmegaSSTDES< BasicTurbulenceModel >
k-omega-SST DES turbulence model for incompressible and compressible flows.
Reference:
    Strelets, M. (2001).
    Detached Eddy Simulation of Massively Separated Flows.
    39th AIAA Aerospace Sciences Meeting and Exhibit, Reno, NV.
Note
The default values of the DES constants implemented are code-specific values calibrated for OpenFOAM using decaying isotropic turbulence, and hence deviate slightly from the values suggested in the reference publication.
Source files
kOmegaSSTDES.H
kOmegaSSTDES.C
Definition at line 67 of file kOmegaSSTDES.H.
Member Typedef Documentation
alphaField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 151 of file kOmegaSSTDES.H.
rhoField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 152 of file kOmegaSSTDES.H.
transportModel
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 153 of file kOmegaSSTDES.H.
Constructor & Destructor Documentation
kOmegaSSTDES()
template<class BasicTurbulenceModel > kOmegaSSTDES (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Definition at line 162 of file kOmegaSSTDES.C.
References Foam::endl(), dimensioned< Type >::getOrAddToDict(), Foam::type(), and WarningInFunction.
~kOmegaSSTDES()
template<class BasicTurbulenceModel > virtual ~kOmegaSSTDES () virtual default
Member Function Documentation
CDES()
template<class BasicTurbulenceModel > virtual tmp< volScalarField > CDES (const volScalarField & F1) const inline protected virtual
Definition at line 99 of file kOmegaSSTDES.H.
References kOmegaSSTBase< DESModel< BasicTurbulenceModel > >::blend(), kOmegaSSTDES< BasicTurbulenceModel >::CDESkeps_, and kOmegaSSTDES< BasicTurbulenceModel >::CDESkom_.
correctNut() [1/2]
template<class BasicTurbulenceModel > void correctNut (const volScalarField & S2) protected virtual
Reimplemented from kOmegaSSTBase< DESModel< BasicTurbulenceModel > >.
Definition at line 35 of file kOmegaSSTDES.C.
correctNut() [2/2]
template<class BasicTurbulenceModel > void correctNut () protected virtual
Reimplemented from kOmegaSSTBase< DESModel< BasicTurbulenceModel > >.
Definition at line 46 of file kOmegaSSTDES.C.
References Foam::fvc::grad(), Foam::magSqr(), and Foam::symm().
r()
template<class BasicTurbulenceModel > tmp< volScalarField > r (const volScalarField & nur, const volScalarField & magGradU) const protected
Definition at line 53 of file kOmegaSSTDES.C.
References Foam::max(), Foam::min(), Foam::sqr(), and Foam::tr().
S2()
template<class BasicTurbulenceModel > tmp< volScalarField > S2 (const volTensorField & gradU) const protected virtual
Reimplemented from kOmegaSSTBase< DESModel< BasicTurbulenceModel > >.
Reimplemented in kOmegaSSTDDES< BasicTurbulenceModel >.
Definition at line 71 of file kOmegaSSTDES.C.
References F1, Foam::fvc::grad(), k, Foam::mag(), Foam::pos(), and Foam::sqr().
dTilda()
template<class BasicTurbulenceModel > tmp< volScalarField > dTilda (const volScalarField & magGradU, const volScalarField & CDES) const protected virtual
Reimplemented in kOmegaSSTDDES< BasicTurbulenceModel >, and kOmegaSSTIDDES< BasicTurbulenceModel >.
Definition at line 108 of file kOmegaSSTDES.C.
References Foam::min().
epsilonByk()
template<class BasicTurbulenceModel > tmp< volScalarField::Internal > epsilonByk (const volScalarField & F1, const volTensorField & gradU) const protected virtual
Reimplemented from kOmegaSSTBase< DESModel< BasicTurbulenceModel > >.
Definition at line 119 of file kOmegaSSTDES.C.
References F1, Foam::mag(), and Foam::sqrt().
GbyNu0()
template<class BasicTurbulenceModel > tmp< volScalarField::Internal > GbyNu0 (const volTensorField & gradU, const volScalarField & S2) const protected virtual
Reimplemented from kOmegaSSTBase< DESModel< BasicTurbulenceModel > >.
Reimplemented in kOmegaSSTDDES< BasicTurbulenceModel >.
Definition at line 131 of file kOmegaSSTDES.C.
GbyNu()
template<class BasicTurbulenceModel > tmp< volScalarField::Internal > GbyNu (const volScalarField::Internal & GbyNu0, const volScalarField::Internal & F2, const volScalarField::Internal & S2) const protected virtual
Reimplemented from kOmegaSSTBase< DESModel< BasicTurbulenceModel > >.
Reimplemented in kOmegaSSTDDES< BasicTurbulenceModel >.
Definition at line 148 of file kOmegaSSTDES.C.
TypeName()
template<class BasicTurbulenceModel > TypeName ("kOmegaSSTDES< BasicTurbulenceModel >")
read()
template<class BasicTurbulenceModel > bool read () virtual
Reimplemented from kOmegaSSTBase< DESModel< BasicTurbulenceModel > >.
Reimplemented in kOmegaSSTDDES< BasicTurbulenceModel >, and kOmegaSSTIDDES< BasicTurbulenceModel >.
Definition at line 242 of file kOmegaSSTDES.C.
References Foam::read().
lengthScaleRAS()
template<class BasicTurbulenceModel > Foam::tmp< Foam::volScalarField > lengthScaleRAS () const virtual
Definition at line 260 of file kOmegaSSTDES.C.
References k, and Foam::sqrt().
lengthScaleLES()
template<class BasicTurbulenceModel > Foam::tmp< Foam::volScalarField > lengthScaleLES (const volScalarField & CDES) const virtual
Definition at line 271 of file kOmegaSSTDES.C.
References delta.
LESRegion()
template<class BasicTurbulenceModel > tmp< volScalarField > LESRegion () const virtual
Definition at line 281 of file kOmegaSSTDES.C.
References F1, Foam::fvc::grad(), k, Foam::mag(), Foam::neg(), tmp< T >::New(), IOobject::scopedName(), and U.
Member Data Documentation
useSigma_
template<class BasicTurbulenceModel > Switch useSigma_ protected
Definition at line 85 of file kOmegaSSTDES.H.
kappa_
template<class BasicTurbulenceModel > dimensionedScalar kappa_ protected
Definition at line 89 of file kOmegaSSTDES.H.
CDESkom_
template<class BasicTurbulenceModel > dimensionedScalar CDESkom_ protected
Definition at line 92 of file kOmegaSSTDES.H.
Referenced by kOmegaSSTDES< BasicTurbulenceModel >::CDES().
CDESkeps_
template<class BasicTurbulenceModel > dimensionedScalar CDESkeps_ protected
Definition at line 93 of file kOmegaSSTDES.H.
Referenced by kOmegaSSTDES< BasicTurbulenceModel >::CDES().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/DES/kOmegaSSTDES/kOmegaSSTDES.H
src/TurbulenceModels/turbulenceModels/DES/kOmegaSSTDES/kOmegaSSTDES.C