OpenFOAM: dynamicIndexedOctree< Type > Class Template Reference
dynamicIndexedOctree< Type > Class Template Reference
Non-pointer based hierarchical recursive searching. Storage is dynamic, so elements can be deleted.
#include <dynamicIndexedOctree.H>
Public Member Functions
dynamicIndexedOctree (const Type &shapes, const treeBoundBox &bb, const label maxLevels, const scalar maxLeafRatio, const scalar maxDuplicity)
autoPtr< dynamicIndexedOctree< Type > > clone () const
const Type & shapes () const noexcept
const List< node > & nodes () const noexcept
const DynamicList< DynamicList< label > > & contents () const noexcept
PackedList< 2 > & nodeTypes () const noexcept
const treeBoundBox & bb () const
pointIndexHit findNearest (const point &sample, const scalar nearestDistSqr) const
void findNearest (const label nodeI, const point &, scalar &nearestDistSqr, label &nearestShapeI, point &nearestPoint) const
pointIndexHit findNearest (const linePointRef &ln, treeBoundBox &tightest, point &linePoint) const
pointIndexHit findLine (const point &start, const point &end) const
pointIndexHit findLineAny (const point &start, const point &end) const
bool overlaps (const treeBoundBox &bb) const
labelList findBox (const treeBoundBox &bb) const
label findBox (const treeBoundBox &bb, labelHashSet &elements) const
bool overlaps (const point &centre, const scalar radiusSqr) const
labelList findSphere (const point &centre, const scalar radiusSqr) const
label findSphere (const point &centre, const scalar radiusSqr, labelHashSet &elements) const
labelBits findNode (const label nodeI, const point &) const
label findInside (const point &) const
const labelList & findIndices (const point &) const
volumeType getVolumeType (const point &) const
template<class CompareOp >
void findNear (const scalar nearDist, const dynamicIndexedOctree< Type > &tree2, CompareOp &cop) const
bool insert (label startIndex, label endIndex)
bool insertIndex (const label nodIndex, const label index, label &nLevels)
bool remove (const label index)
label removeIndex (const label nodIndex, const label index)
void writeOBJ (Ostream &os) const
void print (prefixOSstream &, const bool printContents, const label) const
bool write (Ostream &os) const
void writeTreeInfo () const
Public Member Functions inherited from dynamicIndexedOctreeBase
ClassName ("dynamicIndexedOctree")
dynamicIndexedOctreeBase ()=default
Public Member Functions inherited from indexedOctreeBase
ClassName ("indexedOctree")
indexedOctreeBase ()=default
Static Public Member Functions
static volumeType getSide (const vector &outsideNormal, const vector &vec)
Static Public Member Functions inherited from indexedOctreeBase
static bool isEmpty (labelBits i) noexcept
static bool isContent (labelBits i) noexcept
static bool isNode (labelBits i) noexcept
static label getContent (labelBits i)
static label getNode (const labelBits i)
static direction getOctant (labelBits i) noexcept
static scalar & perturbTol () noexcept
static scalar perturbTol (scalar tol) noexcept
static void writeOBJ (Ostream &os, const treeBoundBox &bb, label &vertIndex, const bool writeLinesOnly=false)
Friends
Ostream & operator<< (Ostream &, const dynamicIndexedOctree< Type > &)
Additional Inherited Members
Public Types inherited from dynamicIndexedOctreeBase
using node = indexedOctreeBase::node
Static Protected Member Functions inherited from indexedOctreeBase
static labelBits emptyPlusOctant (direction octant)
static labelBits contentPlusOctant (label i, direction octant)
static labelBits nodePlusOctant (label i, direction octant)
Static Protected Attributes inherited from indexedOctreeBase
static scalar perturbTol_ = 10*SMALL
Detailed Description
template<class Type>
class Foam::dynamicIndexedOctree< Type >
Non-pointer based hierarchical recursive searching. Storage is dynamic, so elements can be deleted.
Source files
dynamicIndexedOctree.H
dynamicIndexedOctree.C
Definition at line 85 of file dynamicIndexedOctree.H.
Constructor & Destructor Documentation
dynamicIndexedOctree()
template<class Type > dynamicIndexedOctree (const Type & shapes, const treeBoundBox & bb, const label maxLevels, const scalar maxLeafRatio, const scalar maxDuplicity)
Definition at line 2023 of file dynamicIndexedOctree.C.
References insert(), UPtrList< T >::size(), and dynamicIndexedOctree< Type >::writeTreeInfo().
Member Function Documentation
clone()
template<class Type > autoPtr< dynamicIndexedOctree< Type > > clone () const inline
Definition at line 339 of file dynamicIndexedOctree.H.
References Foam::New().
shapes()
template<class Type > const Type & shapes () const inline noexcept
Definition at line 350 of file dynamicIndexedOctree.H.
nodes()
template<class Type > const List< node > & nodes () const inline noexcept
Definition at line 353 of file dynamicIndexedOctree.H.
contents()
template<class Type > const DynamicList< DynamicList< label > > & contents () const inline noexcept
Definition at line 357 of file dynamicIndexedOctree.H.
nodeTypes()
template<class Type > PackedList< 2 > & nodeTypes () const inline noexcept
Definition at line 363 of file dynamicIndexedOctree.H.
bb()
template<class Type > const treeBoundBox & bb () const inline
Definition at line 369 of file dynamicIndexedOctree.H.
References UPtrList< T >::empty(), and treeBoundBox::null().
findNearest() [1/3]
template<class Type > Foam::pointIndexHit findNearest (const point & sample, const scalar nearestDistSqr) const
Definition at line 2060 of file dynamicIndexedOctree.C.
References Foam::Zero.
findNearest() [2/3]
template<class Type > void findNearest (const label nodeI, const point & sample, scalar & nearestDistSqr, label & nearestShapeI, point & nearestPoint) const
Definition at line 341 of file dynamicIndexedOctree.C.
findNearest() [3/3]
template<class Type > Foam::pointIndexHit findNearest (const linePointRef & ln, treeBoundBox & tightest, point & linePoint) const
Definition at line 2088 of file dynamicIndexedOctree.C.
References Foam::ln(), and Foam::Zero.
findLine()
template<class Type > Foam::pointIndexHit findLine (const point & start, const point & end) const
Definition at line 2117 of file dynamicIndexedOctree.C.
findLineAny()
template<class Type > Foam::pointIndexHit findLineAny (const point & start, const point & end) const
Definition at line 2128 of file dynamicIndexedOctree.C.
overlaps() [1/2]
template<class Type > bool overlaps (const treeBoundBox & bb) const
Definition at line 2139 of file dynamicIndexedOctree.C.
References UPtrList< T >::empty().
findBox() [1/2]
template<class Type > Foam::labelList findBox (const treeBoundBox & bb) const
Parameters
bb bound box limits
Definition at line 2176 of file dynamicIndexedOctree.C.
References HashTable< T, Key, Hash >::toc().
findBox() [2/2]
template<class Type > Foam::label findBox (const treeBoundBox & bb, labelHashSet & elements) const
Parameters
bb bound box limits
[out] elements elements found
Definition at line 2150 of file dynamicIndexedOctree.C.
References HashTable< T, Key, Hash >::capacity(), HashTable< T, Key, Hash >::clear(), Foam::max(), HashTable< T, Key, Hash >::resize(), and HashTable< T, Key, Hash >::size().
overlaps() [2/2]
template<class Type > bool overlaps (const point & centre, const scalar radiusSqr) const
Parameters
centre centre of bound sphere
radiusSqr radius^2 of sphere
Definition at line 2196 of file dynamicIndexedOctree.C.
References UPtrList< T >::empty().
findSphere() [1/2]
template<class Type > Foam::labelList findSphere (const point & centre, const scalar radiusSqr) const
Parameters
centre centre of bound sphere
radiusSqr radius^2 of sphere
Definition at line 2235 of file dynamicIndexedOctree.C.
References HashTable< T, Key, Hash >::toc().
findSphere() [2/2]
template<class Type > Foam::label findSphere (const point & centre, const scalar radiusSqr, labelHashSet & elements) const
Parameters
centre centre of bound sphere
radiusSqr radius^2 of sphere
[out] elements elements found
Definition at line 2208 of file dynamicIndexedOctree.C.
References HashTable< T, Key, Hash >::capacity(), HashTable< T, Key, Hash >::clear(), Foam::max(), HashTable< T, Key, Hash >::resize(), and HashTable< T, Key, Hash >::size().
findNode()
template<class Type > Foam::labelBits findNode (const label nodeI, const point & sample) const
Definition at line 2256 of file dynamicIndexedOctree.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
findInside()
template<class Type > Foam::label findInside (const point & sample) const
Definition at line 2303 of file dynamicIndexedOctree.C.
References forAll, and Foam::getOctant().
findIndices()
template<class Type > const Foam::labelList & findIndices (const point & sample) const
Definition at line 2335 of file dynamicIndexedOctree.C.
References Foam::getOctant(), and List< label >::null().
getVolumeType()
template<class Type > Foam::volumeType getVolumeType (const point & sample) const
Definition at line 2357 of file dynamicIndexedOctree.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, volumeType::INSIDE, volumeType::MIXED, volumeType::OUTSIDE, Foam::Pout, Foam::type(), and volumeType::UNKNOWN.
getSide()
template<class Type > Foam::volumeType getSide (const vector & outsideNormal, const vector & vec) static
Definition at line 323 of file dynamicIndexedOctree.C.
findNear()
template<class Type > template<class CompareOp > void findNear (const scalar nearDist, const dynamicIndexedOctree< Type > & tree2, CompareOp & cop) const
Definition at line 2427 of file dynamicIndexedOctree.C.
insert()
template<class Type > bool insert (label startIndex, label endIndex)
Definition at line 2450 of file dynamicIndexedOctree.C.
References Foam::divide(), PtrList< T >::emplace_back(), Foam::max(), and success.
insertIndex()
template<class Type > bool insertIndex (const label nodIndex, const label index, label & nLevels)
Definition at line 2488 of file dynamicIndexedOctree.C.
References PtrList< T >::emplace_back(), and UPtrList< T >::size().
remove()
template<class Type > bool remove (const label index)
Definition at line 2560 of file dynamicIndexedOctree.C.
removeIndex()
template<class Type > Foam::label removeIndex (const label nodIndex, const label index)
Definition at line 2574 of file dynamicIndexedOctree.C.
References UPtrList< T >::empty(), forAll, PtrList< T >::push_back(), UPtrList< T >::size(), and PtrList< T >::transfer().
writeOBJ()
template<class Type > void writeOBJ (Ostream & os) const
Definition at line 2009 of file dynamicIndexedOctree.C.
References os().
print()
template<class Type > void print (prefixOSstream & os, const bool printContents, const label nodeI) const
Definition at line 2657 of file dynamicIndexedOctree.C.
References Foam::endl(), forAll, Foam::nl, os(), UList< T >::size(), and treeBoundBox::subBbox().
write()
template<class Type > bool write (Ostream & os) const
Definition at line 2756 of file dynamicIndexedOctree.C.
References IOstream::good(), and os().
writeTreeInfo()
template<class Type > void writeTreeInfo () const
Definition at line 2730 of file dynamicIndexedOctree.C.
References Foam::endl(), Foam::nl, Foam::Pout, and UPtrList< T >::size().
Referenced by dynamicIndexedOctree< Type >::dynamicIndexedOctree().
Friends And Related Symbol Documentation
operator<<
template<class Type > Ostream & operator<< (Ostream & , const dynamicIndexedOctree< Type > &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/algorithms/dynamicIndexedOctree/dynamicIndexedOctree.H
src/OpenFOAM/algorithms/dynamicIndexedOctree/dynamicIndexedOctree.C