OpenFOAM: hPolynomialThermo< EquationOfState, PolySize > Class Template Reference
hPolynomialThermo< EquationOfState, PolySize > Class Template Reference
Thermophysical models » Specie » Thermodynamics
Thermodynamics package templated on the equation of state, using polynomial functions for cp, h and s.
#include <hPolynomialThermo.H>
Public Member Functions
hPolynomialThermo (const dictionary &dict)
hPolynomialThermo (const word &, const hPolynomialThermo &)
scalar limit (const scalar) const
scalar Cp (const scalar p, const scalar T) const
scalar Ha (const scalar p, const scalar T) const
scalar Hs (const scalar p, const scalar T) const
scalar Hc () const
scalar S (const scalar p, const scalar T) const
scalar Gstd (const scalar T) const
scalar dCpdT (const scalar p, const scalar T) const
void write (Ostream &os) const
void operator+= (const hPolynomialThermo &)
void operator*= (const scalar)
Static Public Member Functions
static word typeName ()
Friends
hPolynomialThermo operator+ (const hPolynomialThermo &, const hPolynomialThermo &)
hPolynomialThermo operator* (const scalar, const hPolynomialThermo &)
hPolynomialThermo operator== (const hPolynomialThermo &, const hPolynomialThermo &)
Ostream & operator (Ostream &, const hPolynomialThermo &)
Detailed Description
template<class EquationOfState, int PolySize = 8>
class Foam::hPolynomialThermo< EquationOfState, PolySize >
Thermodynamics package templated on the equation of state, using polynomial functions for cp, h and s.
Polynomials for h and s derived from cp.
Usage
Property Description
Hf Heat of formation
Sf Standard entropy
CpCoeffs<8> Specific heat at constant pressure polynomial coeffs
Example of the specification of the thermodynamic properties:
    thermodynamics
    {
        Hf              0;
        Sf              0;
        CpCoeffs<8>     ( 1000 -0.05 0.003 0 0 0 0 0 );
    }
The polynomial expression is evaluated as so:
Note
Heat of formation is inputted in [J/kg], but internally uses [J/kmol]
Standard entropy is inputted in [J/kg/K], but internally uses [J/kmol/K]
Specific heat at constant pressure polynomial coefficients evaluate to an expression in [J/(kg.K)].
Source files
hPolynomialThermo.H
hPolynomialThermoI.H
hPolynomialThermo.C
See also
Foam::Polynomial
Definition at line 136 of file hPolynomialThermo.H.
Constructor & Destructor Documentation
hPolynomialThermo() [1/2]
template<class EquationOfState , int PolySize> hPolynomialThermo (const dictionary & dict)
Definition at line 28 of file hPolynomialThermo.C.
hPolynomialThermo() [2/2]
template<class EquationOfState , int PolySize> hPolynomialThermo (const word & name, const hPolynomialThermo< EquationOfState, PolySize > & pt) inline
Definition at line 49 of file hPolynomialThermoI.H.
References Foam::name().
Member Function Documentation
typeName()
template<class EquationOfState , int PolySize = 8> static word typeName () inline static
Definition at line 208 of file hPolynomialThermo.H.
limit()
template<class EquationOfState , int PolySize> Foam::scalar limit (const scalar T) const inline
Definition at line 67 of file hPolynomialThermoI.H.
References T.
Cp()
template<class EquationOfState , int PolySize> Foam::scalar Cp (const scalar p, const scalar T) const inline
Definition at line 77 of file hPolynomialThermoI.H.
References p, and T.
Ha()
template<class EquationOfState , int PolySize> Foam::scalar Ha (const scalar p, const scalar T) const inline
Definition at line 87 of file hPolynomialThermoI.H.
References p, and T.
Hs()
template<class EquationOfState , int PolySize> Foam::scalar Hs (const scalar p, const scalar T) const inline
Definition at line 97 of file hPolynomialThermoI.H.
References Ha(), p, and T.
Hc()
template<class EquationOfState , int PolySize> Foam::scalar Hc () const inline
Definition at line 107 of file hPolynomialThermoI.H.
S()
template<class EquationOfState , int PolySize> Foam::scalar S (const scalar p, const scalar T) const inline
Definition at line 115 of file hPolynomialThermoI.H.
References p, and T.
Gstd()
template<class EquationOfState , int PolySize> Foam::scalar Gstd (const scalar T) const inline
Definition at line 126 of file hPolynomialThermoI.H.
References T.
dCpdT()
template<class EquationOfState , int PolySize> Foam::scalar dCpdT (const scalar p, const scalar T) const inline
Definition at line 136 of file hPolynomialThermoI.H.
References T.
write()
template<class EquationOfState , int PolySize> void write (Ostream & os) const
Definition at line 59 of file hPolynomialThermo.C.
References Ostream::beginBlock(), Ostream::endBlock(), os(), and Ostream::writeEntry().
operator+=()
template<class EquationOfState , int PolySize = 8> void operator+= (const hPolynomialThermo< EquationOfState, PolySize > &) inline
Definition at line 151 of file hPolynomialThermoI.H.
References Foam::mag(), and Y.
operator*=()
template<class EquationOfState , int PolySize> void operator*= (const scalar s) inline
Definition at line 175 of file hPolynomialThermoI.H.
References s().
Friends And Related Symbol Documentation
operator+
template<class EquationOfState , int PolySize = 8> hPolynomialThermo operator+ (const hPolynomialThermo< EquationOfState, PolySize > & , const hPolynomialThermo< EquationOfState, PolySize > &) friend
operator*
template<class EquationOfState , int PolySize = 8> hPolynomialThermo operator* (const scalar , const hPolynomialThermo< EquationOfState, PolySize > &) friend
operator==
template<class EquationOfState , int PolySize = 8> hPolynomialThermo operator== (const hPolynomialThermo< EquationOfState, PolySize > & , const hPolynomialThermo< EquationOfState, PolySize > &) friend
operator
template<class EquationOfState , int PolySize = 8> Ostream & operator (Ostream & , const hPolynomialThermo< EquationOfState, PolySize > &) friend
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/thermo/hPolynomial/hPolynomialThermo.H
src/thermophysicalModels/specie/thermo/hPolynomial/hPolynomialThermo.C
src/thermophysicalModels/specie/thermo/hPolynomial/hPolynomialThermoI.H