OpenFOAM: OppositeFaceCellWave< Type, TrackingData > Class Template Reference
OppositeFaceCellWave< Type, TrackingData > Class Template Reference
Version of FaceCellWave that walks through prismatic cells only.
#include <OppositeFaceCellWave.H>
Public Member Functions
OppositeFaceCellWave (const polyMesh &, const labelList &initialChangedFaces, const List< Type > &changedFacesInfo, UList< Type > &allFaceInfo, UList< Type > &allCellInfo, const label maxIter, TrackingData &td=FaceCellWaveBase::dummyTrackData_)
virtual ~OppositeFaceCellWave ()=default
virtual label faceToCell ()
virtual label cellToFace ()
Public Member Functions inherited from FaceCellWave< Type, TrackingData >
FaceCellWave (const polyMesh &mesh, UList< Type > &allFaceInfo, UList< Type > &allCellInfo, TrackingData &td=FaceCellWaveBase::dummyTrackData_)
FaceCellWave (const polyMesh &mesh, const labelUList &initialChangedFaces, const List< Type > &changedFacesInfo, UList< Type > &allFaceInfo, UList< Type > &allCellInfo, const label maxIter, TrackingData &td=FaceCellWaveBase::dummyTrackData_)
FaceCellWave (const polyMesh &mesh, const labelPairList &explicitConnections, const bool handleCyclicAMI, const labelUList &initialChangedFaces, const List< Type > &changedFacesInfo, UList< Type > &allFaceInfo, UList< Type > &allCellInfo, const label maxIter, TrackingData &td=FaceCellWaveBase::dummyTrackData_)
virtual ~FaceCellWave ()=default
UList< Type > & allFaceInfo () noexcept
UList< Type > & allCellInfo () noexcept
const TrackingData & data () const noexcept
void setFaceInfo (const label facei, const Type &faceInfo)
void setFaceInfo (const labelUList &changedFaces, const List< Type > &changedFacesInfo)
virtual label iterate (const label maxIter)
Public Member Functions inherited from FaceCellWaveBase
ClassName ("FaceCellWave")
FaceCellWaveBase (const polyMesh &mesh)
const polyMesh & mesh () const noexcept
label nChangedCells () const noexcept
label nChangedFaces () const noexcept
label nUnvisitedCells () const noexcept
label nUnvisitedFaces () const noexcept
Public Member Functions inherited from OppositeFaceCellWaveBase
ClassName ("OppositeFaceCellWave")
OppositeFaceCellWaveBase (const polyMesh &mesh)
Protected Member Functions
void opposingFaceLabels (const label celli, const label facei, DynamicList< label > &) const
Protected Member Functions inherited from FaceCellWave< Type, TrackingData >
bool updateCell (const label celli, const label neighbourFacei, const Type &neighbourInfo, const scalar tol, Type &cellInfo)
bool updateFace (const label facei, const label neighbourCelli, const Type &neighbourInfo, const scalar tol, Type &faceInfo)
bool updateFace (const label facei, const Type &neighbourInfo, const scalar tol, Type &faceInfo)
void checkCyclic (const polyPatch &pPatch) const
template<class PatchType >
bool hasPatch () const
void mergeFaceInfo (const polyPatch &patch, const label nFaces, const labelUList &changedFaces, const List< Type > &changedFacesInfo)
label getChangedPatchFaces (const polyPatch &patch, const label startFacei, const label nFaces, labelList &changedPatchFaces, List< Type > &changedPatchFacesInfo) const
void leaveDomain (const polyPatch &patch, const label nFaces, const labelUList &faceLabels, List< Type > &faceInfo) const
void enterDomain (const polyPatch &patch, const label nFaces, const labelUList &faceLabels, List< Type > &faceInfo) const
void transform (const tensorField &rotTensor, const label nFaces, List< Type > &faceInfo)
void handleProcPatches ()
void handleCyclicPatches ()
void handleAMICyclicPatches ()
void handleExplicitConnections ()
FaceCellWave (const FaceCellWave &)=delete
void operator= (const FaceCellWave &)=delete
Additional Inherited Members
Static Public Member Functions inherited from FaceCellWaveBase
static scalar propagationTol () noexcept
static scalar setPropagationTol (const scalar tol) noexcept
Static Public Attributes inherited from FaceCellWaveBase
static int dummyTrackData_ = 12345
Protected Types inherited from FaceCellWave< Type, TrackingData >
typedef std::pair< label, Type > taggedInfoType
Static Protected Member Functions inherited from FaceCellWave< Type, TrackingData >
static void offset (const polyPatch &patch, const label off, const label nFaces, labelList &faces)
Protected Attributes inherited from FaceCellWave< Type, TrackingData >
const labelPairList explicitConnections_
UList< Type > & allFaceInfo_
UList< Type > & allCellInfo_
TrackingData & td_
DynamicList< taggedInfoType > changedBaffles_
const bool hasCyclicPatches_
const bool hasCyclicAMIPatches_
label nEvals_
Protected Attributes inherited from FaceCellWaveBase
const polyMesh & mesh_
PstreamBuffers pBufs_
bitSet changedFace_
bitSet changedCell_
DynamicList< label > changedFaces_
DynamicList< label > changedCells_
label nUnvisitedFaces_
label nUnvisitedCells_
Protected Attributes inherited from OppositeFaceCellWaveBase
DynamicList< label > changedOppositeFaces_
Static Protected Attributes inherited from FaceCellWaveBase
static const scalar geomTol_ = 1e-6
static scalar propagationTol_ = 0.01
Detailed Description
template<class Type, class TrackingData = int>
class Foam::OppositeFaceCellWave< Type, TrackingData >
Version of FaceCellWave that walks through prismatic cells only.
Used to determine mesh structure. In the front walking routines (faceToCell and faceToCell) it
walks across prismatic cells only
and only to a single opposite face
Notes: A cell with a split faces will be marked but not walked through (since there is no single opposite face.
Source files
OppositeFaceCellWave.H
OppositeFaceCellWave.C
Definition at line 85 of file OppositeFaceCellWave.H.
Constructor & Destructor Documentation
OppositeFaceCellWave()
template<class Type , class TrackingData > OppositeFaceCellWave (const polyMesh & mesh, const labelList & initialChangedFaces, const List< Type > & changedFacesInfo, UList< Type > & allFaceInfo, UList< Type > & allCellInfo, const label maxIter, TrackingData & td = FaceCellWaveBase::dummyTrackData_)
Definition at line 71 of file OppositeFaceCellWave.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, FaceCellWave< Type, TrackingData >::iterate(), FaceCellWaveBase::nChangedCells(), and FaceCellWaveBase::nChangedFaces().
~OppositeFaceCellWave()
template<class Type , class TrackingData = int> virtual ~OppositeFaceCellWave () virtual default
Member Function Documentation
opposingFaceLabels()
template<class Type , class TrackingData > void opposingFaceLabels (const label celli, const label facei, DynamicList< label > & oppositeFaceLabels) const protected
Definition at line 28 of file OppositeFaceCellWave.C.
References PtrList< T >::clear(), f(), PtrList< T >::PtrList(), and PtrList< T >::push_back().
faceToCell()
template<class Type , class TrackingData > Foam::label faceToCell () virtual
Reimplemented from FaceCellWave< Type, TrackingData >.
Definition at line 113 of file OppositeFaceCellWave.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, UPtrList< T >::front(), Foam::Pout, Foam::returnReduce(), and UPtrList< T >::size().
cellToFace()
template<class Type , class TrackingData > Foam::label cellToFace () virtual
Reimplemented from FaceCellWave< Type, TrackingData >.
Definition at line 223 of file OppositeFaceCellWave.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, UPstream::parRun(), Foam::Pout, and Foam::returnReduce().
The documentation for this class was generated from the following files:
src/renumber/renumberMethods/structuredRenumber/OppositeFaceCellWave.H
src/renumber/renumberMethods/structuredRenumber/OppositeFaceCellWave.C