OpenFOAM: SVD Class Reference
SVD Class Reference
Singular value decomposition of a rectangular matrix.
#include <SVD.H>
Public Member Functions
SVD (const scalarRectangularMatrix &A, const scalar minCondition=0)
const scalarRectangularMatrix & U () const
const scalarRectangularMatrix & V () const
const scalarDiagonalMatrix & S () const
bool converged () const
label nZeros () const
scalar minNonZeroS () const
scalarRectangularMatrix VSinvUt () const
Detailed Description
Singular value decomposition of a rectangular matrix.
Source files
SVD.H
SVDI.H
SVD.C
Definition at line 49 of file SVD.H.
Constructor & Destructor Documentation
SVD()
SVD (const scalarRectangularMatrix & A, const scalar minCondition = 0)
Definition at line 28 of file SVD.C.
References A, f(), Foam::findMax(), forAll, g, h, k, Matrix< Form, Type >::m(), Foam::mag(), Foam::max(), Foam::min(), Matrix< Form, Type >::n(), s(), Foam::sqrt(), Foam::sqrtSumSqr(), x, and y.
Member Function Documentation
U()
const Foam::scalarRectangularMatrix & U () const inline
Definition at line 33 of file SVDI.H.
V()
const Foam::scalarRectangularMatrix & V () const inline
Definition at line 39 of file SVDI.H.
S()
const Foam::scalarDiagonalMatrix & S () const inline
Definition at line 45 of file SVDI.H.
converged()
bool converged () const inline
Definition at line 51 of file SVDI.H.
nZeros()
Foam::label nZeros () const inline
Definition at line 57 of file SVDI.H.
minNonZeroS()
Foam::scalar minNonZeroS () const inline
Definition at line 63 of file SVDI.H.
References s(), and UPtrList< T >::size().
VSinvUt()
Foam::scalarRectangularMatrix VSinvUt () const
Definition at line 380 of file SVD.C.
References Foam::inv(), Foam::multiply(), and dimensioned< Type >::T().
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/scalarMatrices/SVD/SVD.H
src/OpenFOAM/matrices/scalarMatrices/SVD/SVD.C
src/OpenFOAM/matrices/scalarMatrices/SVD/SVDI.H