OpenFOAM: PrinceBlanch Class Reference
PrinceBlanch Class Reference
Model of Prince and Blanch (1990). The coalescence rate is calculated by.
#include <PrinceBlanch.H>
Public Member Functions
TypeName ("PrinceBlanch")
PrinceBlanch (const populationBalanceModel &popBal, const dictionary &dict)
virtual ~PrinceBlanch ()=default
virtual void addToCoalescenceRate (volScalarField &coalescenceRate, const label i, const label j)
Public Member Functions inherited from coalescenceModel
TypeName ("coalescenceModel")
declareRunTimeSelectionTable (autoPtr, coalescenceModel, dictionary,(const populationBalanceModel &popBal, const dictionary &dict),(popBal, dict))
coalescenceModel (const populationBalanceModel &popBal, const dictionary &dict)
autoPtr< coalescenceModel > clone () const
virtual ~coalescenceModel ()=default
virtual void correct ()
Additional Inherited Members
Static Public Member Functions inherited from coalescenceModel
static autoPtr< coalescenceModel > New (const word &type, const populationBalanceModel &popBal, const dictionary &dict)
Protected Attributes inherited from coalescenceModel
const populationBalanceModel & popBal_
Detailed Description
Model of Prince and Blanch (1990). The coalescence rate is calculated by.
with the coalescence efficiency
the turbulent collision rate
and the buoyancy-driven collision rate
where the rise velocity of bubble i is calculated by
the equivalent radius by
and the collision cross sectional area by
Note that in equation 2, the bubble radius has been substituted by the bubble diameter. Also the expression for the equivalent radius r_ij (equation 19 in the paper of Prince and Blanch (1990)) was corrected. The collision rate contribution due to laminar shear in the continuous phase is currently neglected.
= Turbulent collision rate [m3/s]
= Buoyancy-driven collision rate [m3/s]
= Laminar shear collision rate [m3/s]
= Coalescence efficiency [-]
= Equivalent radius [m]
= Density of continuous phase [kg/m3]
= Surface tension [N/m]
= Initial film thickness [m]
= Critical film thickness [m]
= Continuous phase turbulent dissipation rate [m2/s3]
= Diameter of bubble i [m]
= Diameter of bubble j [m]
= Rise velocity of bubble i [m/s]
= Collision cross sectional area [m2]
= Gravitational constant [m/s2]
Reference:
        Prince, M. J., & Blanch, H. W. (1990).
        Bubble coalescence and break‐up in air‐sparged bubble columns.
        AIChE journal, 36(10), 1485-1499.
Usage
Property Description Required Default value
C1 coefficient C1 no 0.089
h0 initial film thickness no 1e-4m
hf critical film thickness no 1e-8m
turbulence Switch for collisions due to turbulence yes none
buoyancy Switch for collisions due to buoyancy yes none
laminarShear Switch for collisions due to laminar shear yes none
Source files
PrinceBlanch.H
PrinceBlanch.C
Definition at line 236 of file PrinceBlanch.H.
Constructor & Destructor Documentation
PrinceBlanch()
PrinceBlanch (const populationBalanceModel & popBal, const dictionary & dict)
Definition at line 50 of file PrinceBlanch.C.
References Foam::dimLength, and Foam::dimless.
~PrinceBlanch()
virtual ~PrinceBlanch () virtual default
Member Function Documentation
TypeName()
TypeName ("PrinceBlanch")
addToCoalescenceRate()
void addToCoalescenceRate (volScalarField & coalescenceRate, const label i, const label j) virtual
Implements coalescenceModel.
Definition at line 87 of file PrinceBlanch.C.
References Foam::cbrt(), Foam::exit(), Foam::exp(), Foam::FatalError, FatalErrorInFunction, g, Foam::log(), Foam::mag(), Foam::pow(), Foam::pow3(), phaseModel::rho(), Foam::sqr(), Foam::sqrt(), IOobject::time(), and Foam::type().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/populationBalanceModel/coalescenceModels/PrinceBlanch/PrinceBlanch.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/populationBalanceModel/coalescenceModels/PrinceBlanch/PrinceBlanch.C