OpenFOAM: ifstreamPointer Class Reference
ifstreamPointer Class Reference
A wrapped std::ifstream with possible compression handling (igzstream) that behaves much like a std::unique_ptr.
#include <fstreamPointer.H>
Public Member Functions
ifstreamPointer () noexcept=default
ifstreamPointer (const ifstreamPointer &)=delete
ifstreamPointer (ifstreamPointer &&)=default
void operator= (const ifstreamPointer &)=delete
ifstreamPointer & operator= (ifstreamPointer &&)=default
~ifstreamPointer ()=default
ifstreamPointer (const fileName &pathname)
std::istream * get () noexcept
const std::istream * get () const noexcept
IOstreamOption::compressionType whichCompression () const
std::istream * release () noexcept
void reset (std::istream *ptr) noexcept
std::istream & operator* ()
const std::istream & operator* () const
std::istream * operator-> () noexcept
const std::istream * operator-> () const noexcept
Static Public Member Functions
static bool supports_gz ()
Protected Member Functions
void reopen_gz (const std::string &pathname)
Detailed Description
A wrapped std::ifstream with possible compression handling (igzstream) that behaves much like a std::unique_ptr.
Note
No operator bool to avoid inheritance ambiguity with std::ios::operator bool.
Source files
fstreamPointer.H
fstreamPointers.C
Definition at line 70 of file fstreamPointer.H.
Constructor & Destructor Documentation
ifstreamPointer() [1/4]
ifstreamPointer () default noexcept
ifstreamPointer() [2/4]
ifstreamPointer (const ifstreamPointer &) delete
ifstreamPointer() [3/4]
ifstreamPointer (ifstreamPointer &&) default
~ifstreamPointer()
~ifstreamPointer () default
ifstreamPointer() [4/4]
ifstreamPointer (const fileName & pathname) explicit
Definition at line 58 of file fstreamPointers.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, Foam::isFile(), Foam::mode(), and Foam::nl.
Member Function Documentation
reopen_gz()
void reopen_gz (const std::string & pathname) protected
Definition at line 231 of file fstreamPointers.C.
References PtrList< T >::clear().
Referenced by IFstream::rewind().
operator=() [1/2]
void operator= (const ifstreamPointer &) delete
operator=() [2/2]
ifstreamPointer & operator= (ifstreamPointer &&) default
supports_gz()
bool supports_gz () static
Definition at line 36 of file fstreamPointers.C.
get() [1/2]
std::istream * get () inline noexcept
Definition at line 126 of file fstreamPointer.H.
References UPtrList< T >::get().
Referenced by IFstream::IFstream(), IFstream::rewind(), IFstream::stdStream(), and IFstream::stdStream().
get() [2/2]
const std::istream * get () const inline noexcept
Definition at line 129 of file fstreamPointer.H.
References UPtrList< T >::get().
whichCompression()
Foam::IOstreamOption::compressionType whichCompression () const
Definition at line 361 of file fstreamPointers.C.
References IOstreamOption::COMPRESSED, and IOstreamOption::UNCOMPRESSED.
Referenced by IFstream::IFstream(), and IFstream::rewind().
release()
std::istream * release () inline noexcept
Definition at line 138 of file fstreamPointer.H.
References PtrList< T >::release().
reset()
void reset (std::istream * ptr) inline noexcept
Definition at line 141 of file fstreamPointer.H.
operator*() [1/2]
std::istream & operator* () inline
Definition at line 147 of file fstreamPointer.H.
operator*() [2/2]
const std::istream & operator* () const inline
Definition at line 150 of file fstreamPointer.H.
operator->() [1/2]
std::istream * operator-> () inline noexcept
Definition at line 153 of file fstreamPointer.H.
References UPtrList< T >::get().
operator->() [2/2]
const std::istream * operator-> () const inline noexcept
Definition at line 156 of file fstreamPointer.H.
References UPtrList< T >::get().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOstreams/Fstreams/fstreamPointer.H
src/OpenFOAM/db/IOstreams/Fstreams/fstreamPointers.C