OpenFOAM: perfectFluid< Specie > Class Template Reference
perfectFluid< Specie > Class Template Reference
Thermophysical models » Specie » Equation of state
Perfect gas equation of state.
#include <perfectFluid.H>
Public Member Functions
perfectFluid (const Specie &sp, const scalar R, const scalar rho0)
perfectFluid (const dictionary &dict)
perfectFluid (const word &name, const perfectFluid &)
autoPtr< perfectFluid > clone () const
scalar R () const
scalar rho (scalar p, scalar T) const
scalar H (const scalar p, const scalar T) const
scalar Cp (scalar p, scalar T) const
scalar E (const scalar p, const scalar T) const
scalar Cv (scalar p, scalar T) const
scalar S (const scalar p, const scalar T) const
scalar psi (scalar p, scalar T) const
scalar Z (scalar p, scalar T) const
scalar CpMCv (scalar p, scalar T) const
void write (Ostream &os) const
void operator+= (const perfectFluid &)
void operator*= (const scalar)
Static Public Member Functions
static autoPtr< perfectFluid > New (const dictionary &dict)
static word typeName ()
Static Public Attributes
static const bool incompressible = false
static const bool isochoric = false
Friends
perfectFluid operator+ (const perfectFluid &, const perfectFluid &)
perfectFluid operator* (const scalar s, const perfectFluid &)
perfectFluid operator== (const perfectFluid &, const perfectFluid &)
Ostream & operator<< (Ostream &, const perfectFluid &)
Detailed Description
template<class Specie>
class Foam::perfectFluid< Specie >
Perfect gas equation of state.
Source files
perfectFluid.H
perfectFluidI.H
perfectFluid.C
Definition at line 84 of file perfectFluid.H.
Constructor & Destructor Documentation
perfectFluid() [1/3]
template<class Specie > perfectFluid (const Specie & sp, const scalar R, const scalar rho0) inline
Definition at line 27 of file perfectFluidI.H.
References R.
perfectFluid() [2/3]
template<class Specie > perfectFluid (const dictionary & dict)
Definition at line 27 of file perfectFluid.C.
perfectFluid() [3/3]
template<class Specie > perfectFluid (const word & name, const perfectFluid< Specie > &) inline
Member Function Documentation
clone()
template<class Specie > Foam::autoPtr< Foam::perfectFluid< Specie > > clone () const inline
Definition at line 57 of file perfectFluidI.H.
References Foam::New().
New()
template<class Specie > Foam::autoPtr< Foam::perfectFluid< Specie > > New (const dictionary & dict) inline static
Definition at line 65 of file perfectFluidI.H.
References dict, and Foam::New().
typeName()
template<class Specie > static word typeName () inline static
Definition at line 125 of file perfectFluid.H.
R()
template<class Specie > Foam::scalar R () const inline
Definition at line 77 of file perfectFluidI.H.
rho()
template<class Specie > Foam::scalar rho (scalar p, scalar T) const inline
Definition at line 84 of file perfectFluidI.H.
References p, R, and T.
H()
template<class Specie > Foam::scalar H (const scalar p, const scalar T) const inline
Definition at line 91 of file perfectFluidI.H.
Cp()
template<class Specie > Foam::scalar Cp (scalar p, scalar T) const inline
Definition at line 98 of file perfectFluidI.H.
E()
template<class Specie > Foam::scalar E (const scalar p, const scalar T) const inline
Definition at line 105 of file perfectFluidI.H.
Cv()
template<class Specie > Foam::scalar Cv (scalar p, scalar T) const inline
Definition at line 112 of file perfectFluidI.H.
S()
template<class Specie > Foam::scalar S (const scalar p, const scalar T) const inline
Definition at line 119 of file perfectFluidI.H.
References Foam::log(), p, Foam::constant::thermodynamic::Pstd, and R.
psi()
template<class Specie > Foam::scalar psi (scalar p, scalar T) const inline
Definition at line 126 of file perfectFluidI.H.
References R, and T.
Z()
template<class Specie > Foam::scalar Z (scalar p, scalar T) const inline
Definition at line 133 of file perfectFluidI.H.
CpMCv()
template<class Specie > Foam::scalar CpMCv (scalar p, scalar T) const inline
Definition at line 140 of file perfectFluidI.H.
References p, R, rho, Foam::sqr(), and T.
write()
template<class Specie > void write (Ostream & os) const
Definition at line 38 of file perfectFluid.C.
References Ostream::beginBlock(), Ostream::endBlock(), os(), and Ostream::writeEntry().
operator+=()
template<class Specie > void operator+= (const perfectFluid< Specie > &) inline
Definition at line 152 of file perfectFluidI.H.
References Foam::mag(), and Y.
operator*=()
template<class Specie > void operator*= (const scalar s) inline
Definition at line 172 of file perfectFluidI.H.
References s().
Friends And Related Symbol Documentation
operator+
template<class Specie > perfectFluid operator+ (const perfectFluid< Specie > & , const perfectFluid< Specie > &) friend
operator*
template<class Specie > perfectFluid operator* (const scalar s, const perfectFluid< Specie > &) friend
operator==
template<class Specie > perfectFluid operator== (const perfectFluid< Specie > & , const perfectFluid< Specie > &) friend
operator<<
template<class Specie > Ostream & operator<< (Ostream & , const perfectFluid< Specie > &) friend
Member Data Documentation
incompressible
template<class Specie > const bool incompressible = false static
Definition at line 134 of file perfectFluid.H.
isochoric
template<class Specie > const bool isochoric = false static
Definition at line 137 of file perfectFluid.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/equationOfState/perfectFluid/perfectFluid.H
src/thermophysicalModels/specie/equationOfState/perfectFluid/perfectFluid.C
src/thermophysicalModels/specie/equationOfState/perfectFluid/perfectFluidI.H