OpenFOAM: kinematicSingleLayer Class Reference
kinematicSingleLayer Class Reference
Kinematic form of single-cell layer surface film model.
#include <kinematicSingleLayer.H>
Public Member Functions
TypeName ("kinematicSingleLayer")
kinematicSingleLayer (const word &modelType, const fvMesh &mesh, const dimensionedVector &g, const word &regionType, const bool readFields=true)
virtual ~kinematicSingleLayer ()
virtual scalar CourantNumber () const
Switch momentumPredictor () const
label nOuterCorr () const
label nCorr () const
label nNonOrthCorr () const
const dimensionedScalar & deltaSmall () const
const volScalarField & mu () const
const volScalarField & sigma () const
const volScalarField & delta () const
const volScalarField & alpha () const
virtual const volVectorField & U () const
virtual const volVectorField & Us () const
virtual const volVectorField & Uw () const
virtual const volScalarField & deltaRho () const
virtual const surfaceScalarField & phi () const
virtual const volScalarField & rho () const
virtual const volScalarField & T () const
virtual const volScalarField & Ts () const
virtual const volScalarField & Tw () const
virtual const volScalarField & hs () const
virtual const volScalarField & Cp () const
virtual const volScalarField & kappa () const
virtual tmp< volScalarField > primaryMassTrans () const
virtual const volScalarField & cloudMassTrans () const
virtual const volScalarField & cloudDiameterTrans () const
virtual void addSources (const label patchi, const label facei, const scalar massSource, const vector &momentumSource, const scalar pressureSource, const scalar energySource=0)
volVectorField & USpPrimary ()
volScalarField & pSpPrimary ()
volScalarField & rhoSpPrimary ()
volVectorField & USp ()
volScalarField & pSp ()
volScalarField & rhoSp ()
const volVectorField & USp () const
const volScalarField & pSp () const
const volScalarField & rhoSp () const
const volVectorField & UPrimary () const
const volScalarField & pPrimary () const
const volScalarField & rhoPrimary () const
const volScalarField & muPrimary () const
const filmThermoModel & filmThermo () const
injectionModelList & injection ()
transferModelList & transfer ()
const filmTurbulenceModel & turbulence () const
tmp< volScalarField > mass () const
tmp< volScalarField > deltaMass () const
tmp< volScalarField > gNorm () const
tmp< volScalarField > gNormClipped () const
tmp< volVectorField > gTan () const
tmp< vectorField > gTan (const label patchI) const
virtual void preEvolveRegion ()
virtual void evolveRegion ()
virtual void postEvolveRegion ()
virtual tmp< volScalarField::Internal > Srho () const
virtual tmp< volScalarField::Internal > Srho (const label i) const
virtual tmp< volScalarField::Internal > Sh () const
virtual void info ()
Public Member Functions inherited from surfaceFilmRegionModel
TypeName ("surfaceFilmRegionModel")
surfaceFilmRegionModel (const word &modelType, const fvMesh &mesh, const dimensionedVector &g, const word &regionType)
virtual ~surfaceFilmRegionModel ()
const dimensionedVector & g () const
virtual void evolve ()
Public Member Functions inherited from surfaceFilmModel
TypeName ("surfaceFilmModel")
declareRunTimeSelectionTable (autoPtr, surfaceFilmModel, mesh,(const word &modelType, const fvMesh &mesh, const dimensionedVector &g, const word &regionType),(modelType, mesh, g, regionType))
surfaceFilmModel ()
virtual ~surfaceFilmModel ()
Public Member Functions inherited from singleLayerRegion
TypeName ("regionModel")
singleLayerRegion (const fvMesh &mesh, const word &regionType)
singleLayerRegion (const fvMesh &mesh, const word &regionType, const word &modelName, bool readFields=true)
virtual ~singleLayerRegion ()
virtual const volVectorField & nHat () const
virtual const volScalarField & magSf () const
virtual const labelList & passivePatchIDs () const
template<class Type >
wordList mappedFieldAndInternalPatchTypes () const
template<class Type >
wordList mappedPushedFieldPatchTypes () const
template<class Type >
Foam::wordList mappedFieldAndInternalPatchTypes () const
template<class Type >
Foam::wordList mappedPushedFieldPatchTypes () const
Public Member Functions inherited from regionModel
TypeName ("regionModel")
regionModel (const fvMesh &mesh, const word &regionType)
regionModel (const fvMesh &mesh, const word &regionType, const word &modelName, bool readFields=true)
regionModel (const fvMesh &mesh, const word &regionType, const word &modelName, const dictionary &dict, bool readFields=true)
virtual ~regionModel ()=default
const fvMesh & primaryMesh () const noexcept
const Time & time () const noexcept
Switch active () const noexcept
Switch infoOutput () const noexcept
const word & modelName () const noexcept
const fvMesh & regionMesh () const
fvMesh & regionMesh ()
const dictionary & coeffs () const noexcept
const dictionary & solution () const
const IOdictionary & outputProperties () const
IOdictionary & outputProperties ()
const labelList & primaryPatchIDs () const noexcept
const labelList & intCoupledPatchIDs () const noexcept
bool isCoupledPatch (const label regionPatchi) const
bool isRegionPatch (const label primaryPatchi) const
label regionPatchID (const label primaryPatchi) const
label nbrCoupledPatchID (const regionModel &nbrRegion, const label regionPatchi) const
template<class Type >
tmp< Foam::Field< Type > > mapRegionPatchField (const regionModel &nbrRegion, const label regionPatchi, const label nbrPatchi, const Field< Type > &nbrField, const bool flip=false) const
template<class Type >
tmp< Field< Type > > mapRegionPatchField (const regionModel &nbrRegion, const word &fieldName, const label regionPatchi, const bool flip=false) const
template<class Type >
tmp< Field< Type > > mapRegionPatchInternalField (const regionModel &nbrRegion, const word &fieldName, const label regionPatchi, const bool flip=false) const
template<class Type >
void toPrimary (const label regionPatchi, List< Type > &regionField) const
template<class Type >
void toRegion (const label regionPatchi, List< Type > &primaryFieldField) const
template<class Type , class CombineOp >
void toPrimary (const label regionPatchi, List< Type > &regionField, const CombineOp &cop) const
template<class Type , class CombineOp >
void toRegion (const label regionPatchi, List< Type > &primaryFieldField, const CombineOp &cop) const
template<class Type >
Foam::tmp< Foam::Field< Type > > mapRegionPatchField (const regionModel &nbrRegion, const label regionPatchi, const label nbrPatchi, const Field< Type > &nbrField, const bool flip) const
template<class Type >
Foam::tmp< Foam::Field< Type > > mapRegionPatchField (const regionModel &nbrRegion, const word &fieldName, const label regionPatchi, const bool flip) const
template<class Type >
Foam::tmp< Foam::Field< Type > > mapRegionPatchInternalField (const regionModel &nbrRegion, const word &fieldName, const label regionPatchi, const bool flip) const
Public Member Functions inherited from IOdictionary
IOdictionary (const IOobject &io, const dictionary *fallback=nullptr)
IOdictionary (const IOobject &io, const dictionary &dict)
IOdictionary (const IOobject &io, const word &wantedType, const dictionary *fallback=nullptr)
IOdictionary (const IOobject &io, Istream &is)
virtual ~IOdictionary ()=default
virtual bool global () const
virtual fileName filePath () const
Public Member Functions inherited from baseIOdictionary
TypeName ("dictionary")
baseIOdictionary (const baseIOdictionary &)=default
baseIOdictionary (baseIOdictionary &&)=default
virtual ~baseIOdictionary ()=default
baseIOdictionary (const IOobject &io, const dictionary *fallback=nullptr)
baseIOdictionary (const IOobject &io, const dictionary &dict)
baseIOdictionary (const IOobject &io, Istream &is)
const word & name () const
virtual bool readData (Istream &)
virtual bool writeData (Ostream &) const
void operator= (const baseIOdictionary &rhs)
void operator= (const dictionary &rhs)
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
regIOobject (const IOobject &io, const bool isTimeObject=false)
regIOobject (const regIOobject &rio)
regIOobject (const regIOobject &rio, bool registerCopy)
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
regIOobject (const IOobject &io, const regIOobject &rio)
virtual ~regIOobject ()
bool checkIn ()
bool checkOut ()
virtual void addWatch ()
bool registered () const noexcept
bool ownedByRegistry () const noexcept
bool store ()
void release (const bool unregister=false) noexcept
label eventNo () const noexcept
label & eventNo () noexcept
bool upToDate (const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
void setUpToDate ()
virtual void rename (const word &newName)
const dictionary * findMetaData () const noexcept
dictionary & getMetaData () noexcept
void removeMetaData ()
virtual void updateMetaData ()
bool headerOk ()
Istream & readStream (const word &, const bool readOnProc=true)
void close ()
virtual label addWatch (const fileName &)
const labelList & watchIndices () const noexcept
labelList & watchIndices () noexcept
virtual bool modified () const
virtual bool readIfModified ()
virtual bool writeObject (IOstreamOption streamOpt, const bool writeOnProc) const
virtual bool write (const bool writeOnProc=true) const
void operator= (const IOobject &io)
virtual bool writeObject (IOstreamOption::streamFormat fmt, IOstreamOption::versionNumber ver, IOstreamOption::compressionType cmp, const bool writeOnProc) const
Public Member Functions inherited from IOobject
TypeName ("IOobject")
IOobject (const IOobject &)=default
virtual ~IOobject ()=default
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const fileName &path, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const fileName &path, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const IOobject &io, const objectRegistry &registry)
IOobject (const IOobject &io, const word &name)
IOobject (const IOobject &io, const word &name, const fileName &local)
IOobject (const IOobject &io, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt)
IOobject (const IOobject &io, IOobjectOption::registerOption regOpt)
autoPtr< IOobject > clone () const
autoPtr< IOobject > clone (const objectRegistry &registry) const
const objectRegistry & db () const noexcept
const Time & time () const noexcept
const word & name () const noexcept
const word & headerClassName () const noexcept
word & headerClassName () noexcept
const string & note () const noexcept
string & note () noexcept
unsigned labelByteSize () const noexcept
unsigned scalarByteSize () const noexcept
void resetHeader (const word &newName=word::null)
bool hasHeaderClass () const noexcept
template<class Type >
bool isHeaderClass () const
template<class Type >
bool isHeaderClassName () const
word group () const
word member () const
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const noexcept
fileName & instance () noexcept
const fileName & local () const noexcept
fileName path () const
fileName path (const word &instance, const fileName &local=fileName::null) const
fileName objectPath () const
fileName objectRelPath () const
fileName localFilePath (const word &typeName, const bool search=true) const
fileName globalFilePath (const word &typeName, const bool search=true) const
IOstreamOption parseHeader (const dictionary &headerDict)
bool readHeader (Istream &is)
bool readHeader (dictionary &headerDict, Istream &is)
template<class Type >
bool typeHeaderOk (const bool checkType=true, const bool search=true, const bool verbose=true)
template<class Type >
void warnNoRereading () const
bool writeHeader (Ostream &os) const
bool writeHeader (Ostream &os, const word &objectType) const
void writeHeader (dictionary &dict, IOstreamOption streamOpt) const
void writeHeader (dictionary &dict, const word &objectType, IOstreamOption streamOpt) const
bool good () const noexcept
bool bad () const noexcept
InfoProxy< IOobject > info () const noexcept
void operator= (const IOobject &io)
template<>
bool isHeaderClass () const
template<class StringType >
Foam::word groupName (StringType base, const word &group)
Public Member Functions inherited from IOobjectOption
constexpr IOobjectOption (readOption rOpt=readOption::NO_READ, writeOption wOpt=writeOption::NO_WRITE, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (readOption rOpt, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (writeOption wOpt, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (registerOption registerObject, bool globalObject=false) noexcept
constexpr IOobjectOption (readOption rOpt, writeOption wOpt, bool registerObject, bool globalObject=false) noexcept
constexpr IOobjectOption (bool registerObject, bool globalObject=false) noexcept
readOption readOpt () const noexcept
readOption readOpt (readOption opt) noexcept
writeOption writeOpt () const noexcept
writeOption writeOpt (writeOption opt) noexcept
bool registerObject () const noexcept
bool registerObject (bool on) noexcept
bool globalObject () const noexcept
bool globalObject (bool on) noexcept
bool isAnyRead () const noexcept
bool isReadRequired () const noexcept
bool isReadOptional () const noexcept
readOption & readOpt () noexcept
writeOption & writeOpt () noexcept
bool & registerObject () noexcept
bool & globalObject () noexcept
Public Member Functions inherited from dictionary
ClassName ("dictionary")
dictionary ()
dictionary (const fileName &name)
dictionary (const fileName &name, const dictionary &parentDict, Istream &is, bool keepHeader=false)
dictionary (Istream &is)
dictionary (Istream &is, bool keepHeader)
dictionary (const dictionary &parentDict, const dictionary &dict)
dictionary (const dictionary &dict)
dictionary (const dictionary *dict)
dictionary (const dictionary &parentDict, dictionary &&dict)
dictionary (dictionary &&dict)
autoPtr< dictionary > clone () const
virtual ~dictionary ()
const fileName & name () const noexcept
fileName & name () noexcept
word dictName () const
fileName relativeName (const bool caseTag=false) const
bool isNullDict () const noexcept
const dictionary & parent () const noexcept
const dictionary & topDict () const
label startLineNumber () const
label endLineNumber () const
SHA1Digest digest () const
tokenList tokens () const
const entry * findEntry (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
entry * findEntry (const word &keyword, enum keyType::option matchOpt=keyType::REGEX)
bool found (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
const entry * findScoped (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
const dictionary * findDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
dictionary * findDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX)
bool isDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
const entry & lookupEntry (const word &keyword, enum keyType::option matchOpt) const
ITstream & lookup (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
template<class T >
T get (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
template<class T >
T getOrDefault (const word &keyword, const T &deflt, enum keyType::option matchOpt=keyType::REGEX) const
template<class T >
T getOrAdd (const word &keyword, const T &deflt, enum keyType::option matchOpt=keyType::REGEX)
template<class T >
bool readEntry (const word &keyword, T &val, enum keyType::option matchOpt=keyType::REGEX, IOobjectOption::readOption readOpt=IOobjectOption::MUST_READ) const
template<class T >
bool readIfPresent (const word &keyword, T &val, enum keyType::option matchOpt=keyType::REGEX) const
template<class T , class Predicate >
T getCheck (const word &keyword, const Predicate &pred, enum keyType::option matchOpt=keyType::REGEX) const
template<class T , class Predicate >
T getCheckOrDefault (const word &keyword, const T &deflt, const Predicate &pred, enum keyType::option matchOpt=keyType::REGEX) const
template<class T , class Predicate >
T getCheckOrAdd (const word &keyword, const T &deflt, const Predicate &pred, enum keyType::option matchOpt=keyType::REGEX)
template<class T , class Predicate >
bool readCheck (const word &keyword, T &val, const Predicate &pred, enum keyType::option matchOpt=keyType::REGEX, IOobjectOption::readOption readOpt=IOobjectOption::MUST_READ) const
template<class T , class Predicate >
bool readCheckIfPresent (const word &keyword, T &val, const Predicate &pred, enum keyType::option matchOpt=keyType::REGEX) const
const dictionary & subDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
dictionary & subDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX)
dictionary & subDictOrAdd (const word &keyword, enum keyType::option matchOpt=keyType::REGEX)
dictionary subOrEmptyDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX, const bool mandatory=false) const
const dictionary & optionalSubDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
wordList toc () const
wordList sortedToc () const
template<class Compare >
wordList sortedToc (const Compare &comp) const
List< keyType > keys (bool patterns=false) const
bool substituteKeyword (const word &keyword, bool mergeEntry=false)
bool substituteScopedKeyword (const word &keyword, bool mergeEntry=false)
entry * add (entry *entryPtr, bool mergeEntry=false)
entry * add (const entry &e, bool mergeEntry=false)
entry * add (const keyType &k, const word &v, bool overwrite=false)
entry * add (const keyType &k, const string &v, bool overwrite=false)
entry * add (const keyType &k, const label v, bool overwrite=false)
entry * add (const keyType &k, const scalar v, bool overwrite=false)
entry * add (const keyType &k, const dictionary &d, bool mergeEntry=false)
template<class T >
entry * add (const keyType &k, const T &v, bool overwrite=false)
entry * set (entry *entryPtr)
entry * set (const entry &e)
entry * set (const keyType &k, const dictionary &v)
template<class T >
entry * set (const keyType &k, const T &v)
bool remove (const word &keyword)
bool changeKeyword (const keyType &oldKeyword, const keyType &newKeyword, bool overwrite=false)
bool merge (const dictionary &dict)
void clear ()
void transfer (dictionary &dict)
void checkITstream (const ITstream &is, const word &keyword) const
bool read (Istream &is)
bool read (Istream &is, bool keepHeader)
void writeEntry (Ostream &os) const
void writeEntry (const keyType &keyword, Ostream &os) const
void writeEntries (Ostream &os, const bool extraNewLine=false) const
void write (Ostream &os, const bool subDict=true) const
const_searcher csearch (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
const_searcher search (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
searcher search (const word &keyword, enum keyType::option matchOpt=keyType::REGEX)
const_searcher csearchScoped (const word &keyword, enum keyType::option matchOpt) const
const_searcher searchScoped (const word &keyword, enum keyType::option matchOpt) const
searcher searchScoped (const word &keyword, enum keyType::option matchOpt)
const dictionary * cfindScopedDict (const fileName &dictPath) const
const dictionary * findScopedDict (const fileName &dictPath) const
dictionary * findScopedDict (const fileName &dictPath)
dictionary * makeScopedDict (const fileName &dictPath)
const_searcher csearchCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, enum keyType::option matchOpt=keyType::REGEX) const
const entry * findCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, enum keyType::option matchOpt) const
bool foundCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, enum keyType::option matchOpt=keyType::REGEX) const
const entry & lookupEntryCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, enum keyType::option matchOpt) const
ITstream & lookupCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, enum keyType::option matchOpt=keyType::REGEX) const
template<class T >
T getCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, enum keyType::option matchOpt=keyType::REGEX) const
template<class T >
T getOrDefaultCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, const T &deflt, enum keyType::option matchOpt=keyType::REGEX) const
template<class T >
bool readCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, T &val, enum keyType::option matchOpt=keyType::REGEX, IOobjectOption::readOption readOpt=IOobjectOption::MUST_READ) const
template<class T >
bool readIfPresentCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, T &val, enum keyType::option matchOpt=keyType::REGEX) const
void operator= (const dictionary &rhs)
void operator+= (const dictionary &rhs)
void operator|= (const dictionary &rhs)
void operator<<= (const dictionary &rhs)
bool getBool (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Same as get< bool >(const word&, keyType::option)
label getLabel (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Same as get< label >(const word&, keyType::option)
scalar getScalar (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Same as get< scalar >(const word&, keyType::option)
string getString (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Same as get< string >(const word&, keyType::option)
word getWord (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Same as get< word >(const word&, keyType::option)
fileName getFileName (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Same as get< fileName >(const word&, keyType::option)
template<class T >
T lookupOrDefault (const word &keyword, const T &deflt, enum keyType::option matchOpt=keyType::REGEX) const
template<class T >
T lookupOrAddDefault (const word &keyword, const T &deflt, enum keyType::option matchOpt=keyType::REGEX)
ITstream & operator[] (const word &keyword) const
bool found (const word &keyword, bool recursive, bool patternMatch=true) const
entry * lookupEntryPtr (const word &keyword, bool recursive, bool patternMatch)
const entry * lookupEntryPtr (const word &keyword, bool recursive, bool patternMatch) const
const entry * lookupScopedEntryPtr (const word &keyword, bool recursive, bool patternMatch) const
const dictionary * subDictPtr (const word &keyword) const
dictionary * subDictPtr (const word &keyword)
const entry & lookupEntry (const word &keyword, bool recursive, bool patternMatch) const
ITstream & lookup (const word &keyword, bool recursive, bool patternMatch=true) const
template<class T >
T lookupOrDefault (const word &keyword, const T &deflt, bool recursive, bool patternMatch=true) const
template<class T >
T lookupOrAddDefault (const word &keyword, const T &deflt, bool recursive, bool patternMatch=true)
template<class T >
bool readIfPresent (const word &keyword, T &val, bool recursive, bool patternMatch=true) const
template<class T >
T lookupType (const word &keyword, bool recursive=false, bool patternMatch=true) const
template<class Compare >
Foam::wordList sortedToc (const Compare &comp) const
template<class T >
Foam::entry * add (const keyType &k, const T &v, bool overwrite)
template<class T >
Foam::entry * set (const keyType &k, const T &v)
Public Member Functions inherited from ILList< LListBase, T >
ILList ()=default
ILList (T *item)
ILList (Istream &is)
ILList (const ILList< LListBase, T > &lst)
ILList (ILList< LListBase, T > &&lst)
template<class CloneArg >
ILList (const ILList< LListBase, T > &lst, const CloneArg &cloneArg)
template<class INew >
ILList (Istream &is, const INew &inew)
~ILList ()
void clear ()
void pop_front (label n=1)
bool erase (T *item)
void transfer (ILList< LListBase, T > &lst)
void operator= (const ILList< LListBase, T > &lst)
void operator= (ILList< LListBase, T > &&lst)
Public Member Functions inherited from UILList< LListBase, T >
UILList ()=default
UILList (T *item)
UILList (const UILList< LListBase, T > &list)
T * front ()
const T * front () const
T * back ()
const T * back () const
T * removeHead ()
T * remove (T *item)
T * remove (iterator &iter)
void operator= (const UILList< LListBase, T > &lst)
bool operator== (const UILList< LListBase, T > &lst) const
bool operator!= (const UILList< LListBase, T > &lst) const
Ostream & writeList (Ostream &os, const label shortLen=0) const
iterator begin ()
const_iterator cbegin () const
reverse_iterator rbegin ()
const_reverse_iterator crbegin () const
const_iterator begin () const
const_reverse_iterator rbegin () const
const iterator & end ()
const const_iterator & cend () const
const reverse_iterator & rend ()
const const_reverse_iterator & crend () const
const const_iterator & end () const
const const_reverse_iterator & rend () const
T * first ()
const T * first () const
T * last ()
const T * last () const
Protected Member Functions
virtual bool read ()
virtual void correctThermoFields ()
virtual void resetPrimaryRegionSourceTerms ()
virtual void transferPrimaryRegionThermoFields ()
virtual void transferPrimaryRegionSourceFields ()
virtual tmp< volScalarField > pu ()
virtual tmp< volScalarField > pp ()
virtual void correctAlpha ()
virtual void updateSubmodels ()
virtual void continuityCheck ()
virtual void updateSurfaceVelocities ()
template<class Type >
void constrainFilmField (Type &field, const typename Type::cmptType &value)
virtual void solveContinuity ()
virtual tmp< fvVectorMatrix > solveMomentum (const volScalarField &pu, const volScalarField &pp)
virtual void solveThickness (const volScalarField &pu, const volScalarField &pp, fvVectorMatrix &UEqn)
Protected Member Functions inherited from regionModel
virtual bool read (const dictionary &dict)
virtual const AMIPatchToPatchInterpolation & interRegionAMI (const regionModel &nbrRegion, const label regionPatchi, const label nbrPatchi, const bool flip) const
Protected Member Functions inherited from regIOobject
bool readHeaderOk (const IOstreamOption::streamFormat fmt, const word &typeName)
Protected Member Functions inherited from IOobject
void setBad (const string &s)
Protected Attributes
Switch momentumPredictor_
label nOuterCorr_
label nCorr_
label nNonOrthCorr_
scalar cumulativeContErr_
const dimensionedScalar deltaSmall_
scalar deltaCoLimit_
volScalarField rho_
volScalarField mu_
volScalarField sigma_
volScalarField delta_
volScalarField alpha_
volVectorField U_
volVectorField Us_
volVectorField Uw_
volScalarField deltaRho_
surfaceScalarField phi_
volScalarField primaryMassTrans_
volScalarField cloudMassTrans_
volScalarField cloudDiameterTrans_
volVectorField USp_
volScalarField pSp_
volScalarField rhoSp_
volVectorField USpPrimary_
volScalarField pSpPrimary_
volScalarField rhoSpPrimary_
volVectorField UPrimary_
volScalarField pPrimary_
volScalarField rhoPrimary_
volScalarField muPrimary_
autoPtr< filmThermoModel > filmThermo_
scalarField availableMass_
injectionModelList injection_
transferModelList transfer_
autoPtr< filmTurbulenceModel > turbulence_
forceList forces_
scalar addedMassTotal_
Protected Attributes inherited from surfaceFilmRegionModel
const dimensionedVector & g_
Protected Attributes inherited from singleLayerRegion
autoPtr< volVectorField > nHatPtr_
autoPtr< volScalarField > magSfPtr_
labelList passivePatchIDs_
Protected Attributes inherited from regionModel
const fvMesh & primaryMesh_
const Time & time_
Switch active_
Switch infoOutput_
const word modelName_
dictionary coeffs_
autoPtr< IOdictionary > outputPropertiesPtr_
labelList primaryPatchIDs_
labelList intCoupledPatchIDs_
word regionName_
regionModelFunctionObjectList functions_
wordList interRegionAMINames_
PtrList< PtrList< AMIPatchToPatchInterpolation > > interRegionAMI_
Additional Inherited Members
Public Types inherited from IOobject
enum objectState : char { GOOD , BAD }
enum fileCheckTypes : char { timeStamp , timeStampMaster , inotify , inotifyMaster }
Public Types inherited from IOobjectOption
enum readOption : unsigned char {
NO_READ = 0 , MUST_READ = 0x1 , READ_MODIFIED = 0x3 , MUST_READ_IF_MODIFIED = 0x3 ,
LAZY_READ = 0x4 , READ_IF_PRESENT = 0x4
}
enum writeOption : unsigned char { NO_WRITE = 0 , AUTO_WRITE = 0x10 }
enum registerOption : unsigned char { NO_REGISTER = 0 , REGISTER = 1 }
Public Types inherited from dictionary
typedef Searcher< true > const_searcher
typedef Searcher< false > searcher
Public Types inherited from UILList< LListBase, T >
typedef T value_type
typedef T * pointer
typedef const T * const_pointer
typedef T & reference
typedef const T & const_reference
typedef label size_type
typedef label difference_type
using base_iterator = typename LListBase::iterator
using const_base_iterator = typename LListBase::const_iterator
Static Public Member Functions inherited from surfaceFilmModel
static autoPtr< surfaceFilmModel > New (const fvMesh &mesh, const dimensionedVector &g, const word &regionType="surfaceFilm")
Static Public Member Functions inherited from IOdictionary
static dictionary readContents (const IOobject &io)
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *p)
template<class Type >
static Type & store (autoPtr< Type > &ptr)
template<class Type >
static Type & store (autoPtr< Type > &&ptr)
template<class Type >
static Type & store (refPtr< Type > &ptr)
template<class Type >
static Type & store (refPtr< Type > &&ptr)
template<class Type >
static Type & store (tmp< Type > &ptr)
template<class Type >
static Type & store (tmp< Type > &&ptr)
Static Public Member Functions inherited from IOobject
static bool bannerEnabled () noexcept
static bool bannerEnabled (bool on) noexcept
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
template<class StringType >
static word groupName (StringType base, const word &group)
static word group (const word &name)
static word member (const word &name)
static word scopedName (const std::string &scope, const word &name)
static IOobject selectIO (const IOobject &io, const fileName &altFile, const word &ioName="")
static Ostream & writeBanner (Ostream &os, const bool noSyntaxHint=false)
static Ostream & writeDivider (Ostream &os)
static Ostream & writeEndDivider (Ostream &os)
Static Public Member Functions inherited from IOobjectOption
static bool isAnyRead (readOption opt) noexcept
static bool isReadRequired (readOption opt) noexcept
static bool isReadOptional (readOption opt) noexcept
static readOption lazierRead (readOption opt) noexcept
Static Public Member Functions inherited from dictionary
static int reportOptional () noexcept
static int reportOptional (const int level) noexcept
static autoPtr< dictionary > New (Istream &is)
Public Attributes inherited from dictionary
friend const_searcher
friend searcher
Static Public Attributes inherited from surfaceFilmModel
static const dimensionedScalar Tref
Static Public Attributes inherited from IOobject
static const Enum< fileCheckTypes > fileCheckTypesNames
static char scopeSeparator
static fileCheckTypes fileModificationChecking
static float fileModificationSkew
static int maxFileModificationPolls
Static Public Attributes inherited from dictionary
static int writeOptionalEntries
static const dictionary null
static refPtr< OSstream > reportingOutput
Static Protected Member Functions inherited from IOobject
static void writeHeaderContent (Ostream &os, const IOobject &io, const word &objectType, const dictionary *metaDataDict=nullptr)
static void writeHeaderContent (dictionary &dict, const IOobject &io, const word &objectType, IOstreamOption streamOpt, const dictionary *metaDataDict=nullptr)
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
Detailed Description
Kinematic form of single-cell layer surface film model.
Source files
kinematicSingleLayer.H
kinematicSingleLayer.C
Definition at line 63 of file kinematicSingleLayer.H.
Constructor & Destructor Documentation
kinematicSingleLayer()
kinematicSingleLayer (const word & modelType, const fvMesh & mesh, const dimensionedVector & g, const word & regionType, const bool readFields = true)
Definition at line 428 of file kinematicSingleLayer.C.
References kinematicSingleLayer::correctAlpha(), kinematicSingleLayer::correctThermoFields(), kinematicSingleLayer::delta_, kinematicSingleLayer::deltaRho_, Foam::fvc::flux(), IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, kinematicSingleLayer::phi_, IOobjectOption::READ_IF_PRESENT, Foam::readFields(), regionModel::regionMesh(), kinematicSingleLayer::rho_, regionModel::time(), timeName, kinematicSingleLayer::transferPrimaryRegionThermoFields(), and kinematicSingleLayer::U_.
~kinematicSingleLayer()
~kinematicSingleLayer () virtual
Definition at line 816 of file kinematicSingleLayer.C.
Member Function Documentation
read()
bool read () protected virtual
Reimplemented from surfaceFilmRegionModel.
Reimplemented in thermoSingleLayer.
Definition at line 52 of file kinematicSingleLayer.C.
References kinematicSingleLayer::momentumPredictor_, kinematicSingleLayer::nCorr_, kinematicSingleLayer::nNonOrthCorr_, kinematicSingleLayer::nOuterCorr_, surfaceFilmRegionModel::read(), dictionary::readEntry(), dictionary::readIfPresent(), and regionModel::solution().
Referenced by thermoSingleLayer::read().
correctThermoFields()
void correctThermoFields () protected virtual
Reimplemented in thermoSingleLayer.
Definition at line 69 of file kinematicSingleLayer.C.
References kinematicSingleLayer::filmThermo_, kinematicSingleLayer::mu_, kinematicSingleLayer::rho_, and kinematicSingleLayer::sigma_.
Referenced by kinematicSingleLayer::kinematicSingleLayer(), and kinematicSingleLayer::preEvolveRegion().
resetPrimaryRegionSourceTerms()
void resetPrimaryRegionSourceTerms () protected virtual
Reimplemented in thermoSingleLayer.
Definition at line 77 of file kinematicSingleLayer.C.
References DebugInFunction, DimensionedField< Type, GeoMesh >::dimensions(), Foam::endl(), kinematicSingleLayer::pSp_, kinematicSingleLayer::pSpPrimary_, kinematicSingleLayer::rhoSp_, kinematicSingleLayer::rhoSpPrimary_, kinematicSingleLayer::USp_, kinematicSingleLayer::USpPrimary_, and Foam::Zero.
Referenced by kinematicSingleLayer::postEvolveRegion(), and thermoSingleLayer::resetPrimaryRegionSourceTerms().
transferPrimaryRegionThermoFields()
void transferPrimaryRegionThermoFields () protected virtual
Reimplemented in thermoSingleLayer.
Definition at line 87 of file kinematicSingleLayer.C.
References GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), DebugInFunction, Foam::endl(), kinematicSingleLayer::muPrimary_, kinematicSingleLayer::pPrimary_, kinematicSingleLayer::rhoPrimary_, and kinematicSingleLayer::UPrimary_.
Referenced by kinematicSingleLayer::kinematicSingleLayer(), kinematicSingleLayer::preEvolveRegion(), and thermoSingleLayer::transferPrimaryRegionThermoFields().
transferPrimaryRegionSourceFields()
void transferPrimaryRegionSourceFields () protected virtual
Reimplemented in thermoSingleLayer.
Definition at line 100 of file kinematicSingleLayer.C.
References kinematicSingleLayer::addedMassTotal_, GeometricField< Type, PatchField, GeoMesh >::boundaryField(), GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), DebugInFunction, Foam::endl(), forAll, singleLayerRegion::magSf(), regionModel::outputProperties(), regionModel::primaryMesh(), kinematicSingleLayer::pSp_, kinematicSingleLayer::pSpPrimary_, Foam::returnReduce(), kinematicSingleLayer::rhoSp_, kinematicSingleLayer::rhoSpPrimary_, regionModel::time(), regionModel::time_, kinematicSingleLayer::USp_, kinematicSingleLayer::USpPrimary_, and regIOobject::write().
Referenced by kinematicSingleLayer::preEvolveRegion(), and thermoSingleLayer::transferPrimaryRegionSourceFields().
pu()
tmp< volScalarField > pu () protected virtual
Definition at line 155 of file kinematicSingleLayer.C.
References kinematicSingleLayer::delta_, Foam::fvc::laplacian(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, kinematicSingleLayer::pPrimary_, kinematicSingleLayer::pSp_, regionModel::regionMesh(), kinematicSingleLayer::sigma_, and regionModel::time_.
Referenced by kinematicSingleLayer::evolveRegion(), thermoSingleLayer::evolveRegion(), kinematicSingleLayer::solveMomentum(), and kinematicSingleLayer::solveThickness().
pp()
tmp< volScalarField > pp () protected virtual
Definition at line 177 of file kinematicSingleLayer.C.
References kinematicSingleLayer::gNormClipped(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, regionModel::regionMesh(), kinematicSingleLayer::rho_, and regionModel::time_.
Referenced by kinematicSingleLayer::evolveRegion(), thermoSingleLayer::evolveRegion(), kinematicSingleLayer::solveMomentum(), kinematicSingleLayer::solveThickness(), thermoSingleLayer::updateSurfaceTemperatures(), and kinematicSingleLayer::updateSurfaceVelocities().
correctAlpha()
void correctAlpha () protected virtual
Reimplemented in thermoSingleLayer.
Definition at line 197 of file kinematicSingleLayer.C.
References kinematicSingleLayer::alpha_, kinematicSingleLayer::delta_, kinematicSingleLayer::deltaSmall_, and Foam::pos().
Referenced by kinematicSingleLayer::kinematicSingleLayer(), and kinematicSingleLayer::preEvolveRegion().
updateSubmodels()
void updateSubmodels () protected virtual
Reimplemented in thermoSingleLayer.
Definition at line 203 of file kinematicSingleLayer.C.
References kinematicSingleLayer::availableMass_, kinematicSingleLayer::cloudDiameterTrans_, kinematicSingleLayer::cloudMassTrans_, injectionModelList::correct(), transferModelList::correct(), DebugInFunction, Foam::endl(), kinematicSingleLayer::injection_, singleLayerRegion::magSf(), kinematicSingleLayer::rhoSp_, regionModel::time(), kinematicSingleLayer::transfer_, and kinematicSingleLayer::turbulence_.
Referenced by kinematicSingleLayer::evolveRegion().
continuityCheck()
void continuityCheck () protected virtual
Definition at line 220 of file kinematicSingleLayer.C.
References kinematicSingleLayer::cumulativeContErr_, kinematicSingleLayer::deltaRho_, Foam::dimMass, Foam::dimVolume, Foam::fvc::domainIntegrate(), Foam::endl(), globalContErr, InfoInFunction, Foam::mag(), singleLayerRegion::magSf(), kinematicSingleLayer::mass(), Foam::nl, kinematicSingleLayer::solveContinuity(), sumLocalContErr, totalMass, and Foam::type().
Referenced by kinematicSingleLayer::solveThickness().
updateSurfaceVelocities()
void updateSurfaceVelocities () protected virtual
Definition at line 268 of file kinematicSingleLayer.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), regionModel::intCoupledPatchIDs_, singleLayerRegion::nHat(), kinematicSingleLayer::pp(), regionModel::regionMesh(), UList< T >::size(), kinematicSingleLayer::turbulence_, kinematicSingleLayer::U_, kinematicSingleLayer::Us_, and kinematicSingleLayer::Uw_.
Referenced by kinematicSingleLayer::preEvolveRegion(), and kinematicSingleLayer::solveThickness().
constrainFilmField()
template<class Type > void constrainFilmField (Type & field, const typename Type::cmptType & value) protected
Definition at line 35 of file kinematicSingleLayerTemplates.C.
References Foam::endl(), field(), forAll, Foam::Info, regionModel::intCoupledPatchIDs_, and singleLayerRegion::passivePatchIDs_.
Referenced by kinematicSingleLayer::solveThickness().
solveContinuity()
void solveContinuity () protected virtual
Definition at line 254 of file kinematicSingleLayer.C.
References Foam::fvm::ddt(), DebugInFunction, kinematicSingleLayer::deltaRho_, Foam::fvc::div(), Foam::endl(), kinematicSingleLayer::phi_, kinematicSingleLayer::rhoSp_, and solve().
Referenced by kinematicSingleLayer::continuityCheck(), kinematicSingleLayer::evolveRegion(), and thermoSingleLayer::evolveRegion().
solveMomentum()
tmp< Foam::fvVectorMatrix > solveMomentum (const volScalarField & pu, const volScalarField & pp) protected virtual
Definition at line 285 of file kinematicSingleLayer.C.
References forceList::correct(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), Foam::fvm::ddt(), DebugInFunction, kinematicSingleLayer::delta_, kinematicSingleLayer::deltaRho_, Foam::fvm::div(), Foam::endl(), Foam::fvc::flux(), kinematicSingleLayer::forces_, kinematicSingleLayer::gTan(), Foam::fvc::interpolate(), singleLayerRegion::magSf(), kinematicSingleLayer::momentumPredictor_, singleLayerRegion::nHat(), kinematicSingleLayer::phi_, kinematicSingleLayer::pp(), kinematicSingleLayer::pu(), Foam::fvc::reconstruct(), regionModel::regionMesh(), fvMatrix< Type >::relax(), kinematicSingleLayer::rho_, kinematicSingleLayer::rhoSp_, Foam::fvc::snGrad(), solve(), tUEqn(), kinematicSingleLayer::turbulence_, kinematicSingleLayer::U_, UEqn, and kinematicSingleLayer::USp_.
Referenced by kinematicSingleLayer::evolveRegion(), and thermoSingleLayer::evolveRegion().
solveThickness()
void solveThickness (const volScalarField & pu, const volScalarField & pp, fvVectorMatrix & UEqn) protected virtual
Definition at line 340 of file kinematicSingleLayer.C.
References GeometricField< Type, PatchField, GeoMesh >::clamp_min(), kinematicSingleLayer::constrainFilmField(), kinematicSingleLayer::continuityCheck(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), Foam::fvm::ddt(), DebugInFunction, kinematicSingleLayer::delta_, Foam::fvm::div(), Foam::endl(), Foam::fvc::flux(), kinematicSingleLayer::gTan(), Foam::fvc::interpolate(), Foam::fvm::laplacian(), singleLayerRegion::magSf(), IOobject::name(), singleLayerRegion::nHat(), kinematicSingleLayer::nNonOrthCorr_, kinematicSingleLayer::phi_, phid(), kinematicSingleLayer::pp(), kinematicSingleLayer::pu(), Foam::fvc::reconstruct(), regionModel::regionMesh(), kinematicSingleLayer::rho_, rhof(), kinematicSingleLayer::rhoSp_, Foam::fvc::snGrad(), kinematicSingleLayer::U_, UEqn, and kinematicSingleLayer::updateSurfaceVelocities().
Referenced by kinematicSingleLayer::evolveRegion(), and thermoSingleLayer::evolveRegion().
TypeName()
TypeName ("kinematicSingleLayer")
CourantNumber()
scalar CourantNumber () const virtual
Implements surfaceFilmModel.
Definition at line 914 of file kinematicSingleLayer.C.
References kinematicSingleLayer::alpha_, CoNum, kinematicSingleLayer::delta_, kinematicSingleLayer::deltaCoLimit_, kinematicSingleLayer::deltaRho_, Foam::endl(), forAll, Foam::Info, Foam::mag(), singleLayerRegion::magSf(), Foam::max(), kinematicSingleLayer::phi_, GeometricField< Type, PatchField, GeoMesh >::primitiveField(), Foam::reduce(), regionModel::regionMesh(), Foam::fvc::surfaceSum(), and regionModel::time_.
momentumPredictor()
Switch momentumPredictor () const inline
Definition at line 37 of file kinematicSingleLayerI.H.
References kinematicSingleLayer::momentumPredictor_.
nOuterCorr()
label nOuterCorr () const inline
Definition at line 43 of file kinematicSingleLayerI.H.
References kinematicSingleLayer::nOuterCorr_.
nCorr()
label nCorr () const inline
Definition at line 49 of file kinematicSingleLayerI.H.
References kinematicSingleLayer::nCorr_.
nNonOrthCorr()
label nNonOrthCorr () const inline
Definition at line 55 of file kinematicSingleLayerI.H.
References kinematicSingleLayer::nNonOrthCorr_.
deltaSmall()
const dimensionedScalar & deltaSmall () const inline
Definition at line 61 of file kinematicSingleLayerI.H.
References kinematicSingleLayer::deltaSmall_.
mu()
const volScalarField & mu () const inline
Definition at line 67 of file kinematicSingleLayerI.H.
References kinematicSingleLayer::mu_.
sigma()
const volScalarField & sigma () const inline virtual
Implements surfaceFilmRegionModel.
Definition at line 73 of file kinematicSingleLayerI.H.
References kinematicSingleLayer::sigma_.
delta()
const volScalarField & delta () const inline virtual
Implements surfaceFilmRegionModel.
Definition at line 79 of file kinematicSingleLayerI.H.
References kinematicSingleLayer::delta_.
alpha()
const volScalarField & alpha () const inline virtual
Implements surfaceFilmRegionModel.
Definition at line 85 of file kinematicSingleLayerI.H.
References kinematicSingleLayer::alpha_.
U()
const volVectorField & U () const virtual
Implements surfaceFilmRegionModel.
Definition at line 945 of file kinematicSingleLayer.C.
References kinematicSingleLayer::U_.
Us()
const volVectorField & Us () const virtual
Implements surfaceFilmRegionModel.
Definition at line 951 of file kinematicSingleLayer.C.
References kinematicSingleLayer::Us_.
Uw()
const volVectorField & Uw () const virtual
Implements surfaceFilmRegionModel.
Definition at line 957 of file kinematicSingleLayer.C.
References kinematicSingleLayer::Uw_.
deltaRho()
const volScalarField & deltaRho () const virtual
Definition at line 963 of file kinematicSingleLayer.C.
References kinematicSingleLayer::deltaRho_.
phi()
const surfaceScalarField & phi () const virtual
Definition at line 969 of file kinematicSingleLayer.C.
References kinematicSingleLayer::phi_.
rho()
const volScalarField & rho () const virtual
Implements surfaceFilmRegionModel.
Definition at line 975 of file kinematicSingleLayer.C.
References kinematicSingleLayer::rho_.
T()
const volScalarField & T () const virtual
Implements surfaceFilmRegionModel.
Reimplemented in thermoSingleLayer.
Definition at line 981 of file kinematicSingleLayer.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, GeometricField< scalar, fvPatchField, volMesh >::null(), and Foam::type().
Ts()
const volScalarField & Ts () const virtual
Implements surfaceFilmRegionModel.
Reimplemented in thermoSingleLayer.
Definition at line 990 of file kinematicSingleLayer.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, GeometricField< scalar, fvPatchField, volMesh >::null(), and Foam::type().
Tw()
const volScalarField & Tw () const virtual
Implements surfaceFilmRegionModel.
Reimplemented in thermoSingleLayer.
Definition at line 999 of file kinematicSingleLayer.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, GeometricField< scalar, fvPatchField, volMesh >::null(), and Foam::type().
hs()
const volScalarField & hs () const virtual
Implements surfaceFilmRegionModel.
Reimplemented in thermoSingleLayer.
Definition at line 1008 of file kinematicSingleLayer.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, GeometricField< scalar, fvPatchField, volMesh >::null(), and Foam::type().
Cp()
const volScalarField & Cp () const virtual
Implements surfaceFilmRegionModel.
Reimplemented in thermoSingleLayer.
Definition at line 1017 of file kinematicSingleLayer.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, GeometricField< scalar, fvPatchField, volMesh >::null(), and Foam::type().
kappa()
const volScalarField & kappa () const virtual
Implements surfaceFilmRegionModel.
Reimplemented in thermoSingleLayer.
Definition at line 1026 of file kinematicSingleLayer.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, GeometricField< scalar, fvPatchField, volMesh >::null(), and Foam::type().
primaryMassTrans()
tmp< volScalarField > primaryMassTrans () const virtual
Implements surfaceFilmRegionModel.
Definition at line 1035 of file kinematicSingleLayer.C.
References kinematicSingleLayer::primaryMassTrans_.
cloudMassTrans()
const volScalarField & cloudMassTrans () const virtual
Implements surfaceFilmRegionModel.
Definition at line 1041 of file kinematicSingleLayer.C.
References kinematicSingleLayer::cloudMassTrans_.
cloudDiameterTrans()
const volScalarField & cloudDiameterTrans () const virtual
Implements surfaceFilmRegionModel.
Definition at line 1047 of file kinematicSingleLayer.C.
References kinematicSingleLayer::cloudDiameterTrans_.
addSources()
void addSources (const label patchi, const label facei, const scalar massSource, const vector & momentumSource, const scalar pressureSource, const scalar energySource = 0) virtual
Implements surfaceFilmRegionModel.
Reimplemented in thermoSingleLayer.
Definition at line 822 of file kinematicSingleLayer.C.
References kinematicSingleLayer::addedMassTotal_, GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), DebugInFunction, Foam::endl(), Foam::nl, kinematicSingleLayer::pSpPrimary_, kinematicSingleLayer::rhoSpPrimary_, Foam::type(), and kinematicSingleLayer::USpPrimary_.
Referenced by thermoSingleLayer::addSources().
USpPrimary()
volVectorField & USpPrimary () inline
Definition at line 91 of file kinematicSingleLayerI.H.
References kinematicSingleLayer::USpPrimary_.
pSpPrimary()
volScalarField & pSpPrimary () inline
Definition at line 97 of file kinematicSingleLayerI.H.
References kinematicSingleLayer::pSpPrimary_.
rhoSpPrimary()
volScalarField & rhoSpPrimary () inline
Definition at line 103 of file kinematicSingleLayerI.H.
References kinematicSingleLayer::rhoSpPrimary_.
USp() [1/2]
volVectorField & USp () inline
Definition at line 109 of file kinematicSingleLayerI.H.
References kinematicSingleLayer::USp_.
pSp() [1/2]
volScalarField & pSp () inline
Definition at line 115 of file kinematicSingleLayerI.H.
References kinematicSingleLayer::pSp_.
rhoSp() [1/2]
volScalarField & rhoSp () inline
Definition at line 121 of file kinematicSingleLayerI.H.
References kinematicSingleLayer::rhoSp_.
USp() [2/2]
const volVectorField & USp () const inline
Definition at line 127 of file kinematicSingleLayerI.H.
References kinematicSingleLayer::USp_.
pSp() [2/2]
const volScalarField & pSp () const inline
Definition at line 133 of file kinematicSingleLayerI.H.
References kinematicSingleLayer::pSp_.
rhoSp() [2/2]
const volScalarField & rhoSp () const inline
Definition at line 139 of file kinematicSingleLayerI.H.
References kinematicSingleLayer::rhoSp_.
UPrimary()
const volVectorField & UPrimary () const inline
Definition at line 145 of file kinematicSingleLayerI.H.
References kinematicSingleLayer::UPrimary_.
pPrimary()
const volScalarField & pPrimary () const inline
Definition at line 151 of file kinematicSingleLayerI.H.
References kinematicSingleLayer::pPrimary_.
rhoPrimary()
const volScalarField & rhoPrimary () const inline
Definition at line 157 of file kinematicSingleLayerI.H.
References kinematicSingleLayer::rhoPrimary_.
muPrimary()
const volScalarField & muPrimary () const inline
Definition at line 163 of file kinematicSingleLayerI.H.
References kinematicSingleLayer::muPrimary_.
filmThermo()
const filmThermoModel & filmThermo () const inline
Definition at line 169 of file kinematicSingleLayerI.H.
References kinematicSingleLayer::filmThermo_.
injection()
injectionModelList & injection () inline
Definition at line 175 of file kinematicSingleLayerI.H.
References kinematicSingleLayer::injection_.
transfer()
transferModelList & transfer () inline
Definition at line 181 of file kinematicSingleLayerI.H.
References kinematicSingleLayer::transfer_.
turbulence()
const filmTurbulenceModel & turbulence () const inline
Definition at line 187 of file kinematicSingleLayerI.H.
References kinematicSingleLayer::turbulence_.
mass()
tmp< volScalarField > mass () const inline
Definition at line 193 of file kinematicSingleLayerI.H.
References kinematicSingleLayer::deltaRho_, and singleLayerRegion::magSf().
Referenced by kinematicSingleLayer::continuityCheck(), and kinematicSingleLayer::preEvolveRegion().
deltaMass()
tmp< volScalarField > deltaMass () const inline
Definition at line 199 of file kinematicSingleLayerI.H.
References singleLayerRegion::magSf(), kinematicSingleLayer::rhoSp_, and regionModel::time().
gNorm()
tmp< volScalarField > gNorm () const inline
Definition at line 205 of file kinematicSingleLayerI.H.
References surfaceFilmRegionModel::g_, singleLayerRegion::nHat(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, regionModel::regionMesh(), regionModel::time(), and timeName.
Referenced by kinematicSingleLayer::gTan().
gNormClipped()
tmp< volScalarField > gNormClipped () const inline
Definition at line 227 of file kinematicSingleLayerI.H.
References surfaceFilmRegionModel::g_, kinematicSingleLayer::gNormClipped(), singleLayerRegion::nHat(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, regionModel::regionMesh(), regionModel::time(), and timeName.
Referenced by kinematicSingleLayer::gNormClipped(), and kinematicSingleLayer::pp().
gTan() [1/2]
tmp< volVectorField > gTan () const inline
Definition at line 252 of file kinematicSingleLayerI.H.
References surfaceFilmRegionModel::g_, kinematicSingleLayer::gNorm(), singleLayerRegion::nHat(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, regionModel::regionMesh(), regionModel::time(), and timeName.
Referenced by kinematicSingleLayer::solveMomentum(), and kinematicSingleLayer::solveThickness().
gTan() [2/2]
tmp< vectorField > gTan (const label patchI) const inline
Definition at line 273 of file kinematicSingleLayerI.H.
References surfaceFilmRegionModel::g(), surfaceFilmRegionModel::g_, and singleLayerRegion::nHat().
preEvolveRegion()
void preEvolveRegion () virtual
Reimplemented from regionModel.
Reimplemented in thermoSingleLayer.
Definition at line 846 of file kinematicSingleLayer.C.
References kinematicSingleLayer::availableMass_, kinematicSingleLayer::cloudDiameterTrans_, kinematicSingleLayer::cloudMassTrans_, kinematicSingleLayer::correctAlpha(), kinematicSingleLayer::correctThermoFields(), DebugInFunction, Foam::dimLength, Foam::dimMass, Foam::endl(), kinematicSingleLayer::mass(), regionModel::preEvolveRegion(), kinematicSingleLayer::primaryMassTrans_, kinematicSingleLayer::transferPrimaryRegionSourceFields(), kinematicSingleLayer::transferPrimaryRegionThermoFields(), kinematicSingleLayer::updateSurfaceVelocities(), and Foam::Zero.
Referenced by thermoSingleLayer::preEvolveRegion().
evolveRegion()
void evolveRegion () virtual
Reimplemented from regionModel.
Reimplemented in thermoSingleLayer.
Definition at line 870 of file kinematicSingleLayer.C.
References DebugInFunction, kinematicSingleLayer::delta_, kinematicSingleLayer::deltaRho_, Foam::endl(), kinematicSingleLayer::nCorr_, kinematicSingleLayer::nOuterCorr_, kinematicSingleLayer::pp(), kinematicSingleLayer::pu(), kinematicSingleLayer::rho_, kinematicSingleLayer::solveContinuity(), kinematicSingleLayer::solveMomentum(), kinematicSingleLayer::solveThickness(), tUEqn(), UEqn, and kinematicSingleLayer::updateSubmodels().
postEvolveRegion()
void postEvolveRegion () virtual
Reimplemented from regionModel.
Definition at line 905 of file kinematicSingleLayer.C.
References DebugInFunction, Foam::endl(), and kinematicSingleLayer::resetPrimaryRegionSourceTerms().
Srho() [1/2]
tmp< volScalarField::Internal > Srho () const virtual
Implements surfaceFilmModel.
Reimplemented in thermoSingleLayer.
Definition at line 1078 of file kinematicSingleLayer.C.
References Foam::dimMass, Foam::dimTime, Foam::dimVolume, tmp< T >::New(), IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, regionModel::primaryMesh(), regionModel::time(), timeName, and Foam::Zero.
Srho() [2/2]
tmp< volScalarField::Internal > Srho (const label i) const virtual
Implements surfaceFilmModel.
Reimplemented in thermoSingleLayer.
Definition at line 1097 of file kinematicSingleLayer.C.
References Foam::dimMass, Foam::dimTime, Foam::dimVolume, Foam::name(), tmp< T >::New(), IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, regionModel::primaryMesh(), regionModel::time(), timeName, and Foam::Zero.
Sh()
tmp< volScalarField::Internal > Sh () const virtual
Implements surfaceFilmModel.
Reimplemented in thermoSingleLayer.
Definition at line 1119 of file kinematicSingleLayer.C.
References Foam::dimEnergy, Foam::dimTime, Foam::dimVolume, tmp< T >::New(), IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, regionModel::primaryMesh(), regionModel::time(), timeName, and Foam::Zero.
info()
void info () virtual
Reimplemented from regionModel.
Reimplemented in thermoSingleLayer.
Definition at line 1053 of file kinematicSingleLayer.C.
References kinematicSingleLayer::addedMassTotal_, kinematicSingleLayer::alpha_, kinematicSingleLayer::delta_, kinematicSingleLayer::deltaRho_, Foam::endl(), Foam::gMax(), Foam::gMin(), Foam::gSum(), Foam::indent(), Foam::Info, injectionModelList::info(), transferModelList::info(), kinematicSingleLayer::injection_, Foam::mag(), singleLayerRegion::magSf(), Foam::nl, regionModel::outputProperties(), GeometricField< Type, PatchField, GeoMesh >::primitiveField(), Foam::returnReduce(), kinematicSingleLayer::transfer_, Foam::type(), and kinematicSingleLayer::U_.
Referenced by thermoSingleLayer::info().
Member Data Documentation
momentumPredictor_
Switch momentumPredictor_ protected
Definition at line 85 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::momentumPredictor(), kinematicSingleLayer::read(), and kinematicSingleLayer::solveMomentum().
nOuterCorr_
label nOuterCorr_ protected
Definition at line 88 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::evolveRegion(), thermoSingleLayer::evolveRegion(), kinematicSingleLayer::nOuterCorr(), and kinematicSingleLayer::read().
nCorr_
label nCorr_ protected
Definition at line 91 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::evolveRegion(), thermoSingleLayer::evolveRegion(), kinematicSingleLayer::nCorr(), and kinematicSingleLayer::read().
nNonOrthCorr_
label nNonOrthCorr_ protected
Definition at line 94 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::nNonOrthCorr(), kinematicSingleLayer::read(), and kinematicSingleLayer::solveThickness().
cumulativeContErr_
scalar cumulativeContErr_ protected
Definition at line 97 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::continuityCheck().
deltaSmall_
const dimensionedScalar deltaSmall_ protected
Definition at line 100 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::correctAlpha(), and kinematicSingleLayer::deltaSmall().
deltaCoLimit_
scalar deltaCoLimit_ protected
Definition at line 103 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::CourantNumber().
rho_
volScalarField rho_ protected
Definition at line 111 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::correctThermoFields(), thermoSingleLayer::correctThermoFields(), kinematicSingleLayer::evolveRegion(), thermoSingleLayer::evolveRegion(), kinematicSingleLayer::kinematicSingleLayer(), kinematicSingleLayer::pp(), kinematicSingleLayer::rho(), kinematicSingleLayer::solveMomentum(), kinematicSingleLayer::solveThickness(), and thermoSingleLayer::thermoSingleLayer().
mu_
volScalarField mu_ protected
Definition at line 114 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::correctThermoFields(), and kinematicSingleLayer::mu().
sigma_
volScalarField sigma_ protected
Definition at line 117 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::correctThermoFields(), thermoSingleLayer::correctThermoFields(), kinematicSingleLayer::pu(), and kinematicSingleLayer::sigma().
delta_
volScalarField delta_ protected
Definition at line 123 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::correctAlpha(), thermoSingleLayer::correctAlpha(), kinematicSingleLayer::CourantNumber(), kinematicSingleLayer::delta(), kinematicSingleLayer::evolveRegion(), thermoSingleLayer::evolveRegion(), kinematicSingleLayer::info(), kinematicSingleLayer::kinematicSingleLayer(), kinematicSingleLayer::pu(), kinematicSingleLayer::solveMomentum(), kinematicSingleLayer::solveThickness(), and thermoSingleLayer::thermoSingleLayer().
alpha_
volScalarField alpha_ protected
Definition at line 126 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::alpha(), kinematicSingleLayer::correctAlpha(), thermoSingleLayer::correctAlpha(), kinematicSingleLayer::CourantNumber(), kinematicSingleLayer::info(), and thermoSingleLayer::q().
U_
volVectorField U_ protected
Definition at line 129 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::info(), kinematicSingleLayer::kinematicSingleLayer(), kinematicSingleLayer::solveMomentum(), kinematicSingleLayer::solveThickness(), thermoSingleLayer::thermoSingleLayer(), kinematicSingleLayer::U(), and kinematicSingleLayer::updateSurfaceVelocities().
Us_
volVectorField Us_ protected
Definition at line 132 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::updateSurfaceVelocities(), and kinematicSingleLayer::Us().
Uw_
volVectorField Uw_ protected
Definition at line 135 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::updateSurfaceVelocities(), and kinematicSingleLayer::Uw().
deltaRho_
volScalarField deltaRho_ protected
Definition at line 138 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::continuityCheck(), kinematicSingleLayer::CourantNumber(), kinematicSingleLayer::deltaRho(), kinematicSingleLayer::evolveRegion(), thermoSingleLayer::evolveRegion(), kinematicSingleLayer::info(), kinematicSingleLayer::kinematicSingleLayer(), kinematicSingleLayer::mass(), kinematicSingleLayer::solveContinuity(), thermoSingleLayer::solveEnergy(), kinematicSingleLayer::solveMomentum(), and thermoSingleLayer::thermoSingleLayer().
phi_
surfaceScalarField phi_ protected
Definition at line 141 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::CourantNumber(), kinematicSingleLayer::kinematicSingleLayer(), kinematicSingleLayer::phi(), kinematicSingleLayer::solveContinuity(), thermoSingleLayer::solveEnergy(), kinematicSingleLayer::solveMomentum(), kinematicSingleLayer::solveThickness(), and thermoSingleLayer::thermoSingleLayer().
primaryMassTrans_
volScalarField primaryMassTrans_ protected
Definition at line 147 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::preEvolveRegion(), kinematicSingleLayer::primaryMassTrans(), thermoSingleLayer::Srho(), thermoSingleLayer::Srho(), and thermoSingleLayer::updateSubmodels().
cloudMassTrans_
volScalarField cloudMassTrans_ protected
Definition at line 150 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::cloudMassTrans(), kinematicSingleLayer::preEvolveRegion(), kinematicSingleLayer::updateSubmodels(), and thermoSingleLayer::updateSubmodels().
cloudDiameterTrans_
volScalarField cloudDiameterTrans_ protected
Definition at line 153 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::cloudDiameterTrans(), kinematicSingleLayer::preEvolveRegion(), kinematicSingleLayer::updateSubmodels(), and thermoSingleLayer::updateSubmodels().
USp_
volVectorField USp_ protected
Definition at line 163 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::resetPrimaryRegionSourceTerms(), kinematicSingleLayer::solveMomentum(), kinematicSingleLayer::transferPrimaryRegionSourceFields(), kinematicSingleLayer::USp(), and kinematicSingleLayer::USp().
pSp_
volScalarField pSp_ protected
Definition at line 166 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::pSp(), kinematicSingleLayer::pSp(), kinematicSingleLayer::pu(), kinematicSingleLayer::resetPrimaryRegionSourceTerms(), thermoSingleLayer::thermoSingleLayer(), kinematicSingleLayer::transferPrimaryRegionSourceFields(), and thermoSingleLayer::updateSubmodels().
rhoSp_
volScalarField rhoSp_ protected
Definition at line 169 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::deltaMass(), kinematicSingleLayer::resetPrimaryRegionSourceTerms(), kinematicSingleLayer::rhoSp(), kinematicSingleLayer::rhoSp(), kinematicSingleLayer::solveContinuity(), kinematicSingleLayer::solveMomentum(), kinematicSingleLayer::solveThickness(), kinematicSingleLayer::transferPrimaryRegionSourceFields(), kinematicSingleLayer::updateSubmodels(), and thermoSingleLayer::updateSubmodels().
USpPrimary_
volVectorField USpPrimary_ protected
Definition at line 176 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::addSources(), kinematicSingleLayer::resetPrimaryRegionSourceTerms(), kinematicSingleLayer::transferPrimaryRegionSourceFields(), and kinematicSingleLayer::USpPrimary().
pSpPrimary_
volScalarField pSpPrimary_ protected
Definition at line 179 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::addSources(), kinematicSingleLayer::pSpPrimary(), kinematicSingleLayer::resetPrimaryRegionSourceTerms(), and kinematicSingleLayer::transferPrimaryRegionSourceFields().
rhoSpPrimary_
volScalarField rhoSpPrimary_ protected
Definition at line 182 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::addSources(), kinematicSingleLayer::resetPrimaryRegionSourceTerms(), kinematicSingleLayer::rhoSpPrimary(), and kinematicSingleLayer::transferPrimaryRegionSourceFields().
UPrimary_
volVectorField UPrimary_ protected
Definition at line 189 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::transferPrimaryRegionThermoFields(), and kinematicSingleLayer::UPrimary().
pPrimary_
volScalarField pPrimary_ protected
Definition at line 192 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::pPrimary(), kinematicSingleLayer::pu(), thermoSingleLayer::solveEnergy(), thermoSingleLayer::thermoSingleLayer(), and kinematicSingleLayer::transferPrimaryRegionThermoFields().
rhoPrimary_
volScalarField rhoPrimary_ protected
Definition at line 195 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::rhoPrimary(), kinematicSingleLayer::transferPrimaryRegionThermoFields(), and thermoSingleLayer::updateSubmodels().
muPrimary_
volScalarField muPrimary_ protected
Definition at line 198 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::muPrimary(), and kinematicSingleLayer::transferPrimaryRegionThermoFields().
filmThermo_
autoPtr<filmThermoModel> filmThermo_ protected
Definition at line 204 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::correctThermoFields(), thermoSingleLayer::correctThermoFields(), kinematicSingleLayer::filmThermo(), and thermoSingleLayer::Srho().
availableMass_
scalarField availableMass_ protected
Definition at line 207 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::preEvolveRegion(), kinematicSingleLayer::updateSubmodels(), and thermoSingleLayer::updateSubmodels().
injection_
injectionModelList injection_ protected
Definition at line 210 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::info(), kinematicSingleLayer::injection(), kinematicSingleLayer::updateSubmodels(), and thermoSingleLayer::updateSubmodels().
transfer_
transferModelList transfer_ protected
Definition at line 213 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::info(), kinematicSingleLayer::transfer(), kinematicSingleLayer::updateSubmodels(), and thermoSingleLayer::updateSubmodels().
turbulence_
autoPtr<filmTurbulenceModel> turbulence_ protected
Definition at line 216 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::solveMomentum(), kinematicSingleLayer::turbulence(), kinematicSingleLayer::updateSubmodels(), thermoSingleLayer::updateSubmodels(), and kinematicSingleLayer::updateSurfaceVelocities().
forces_
forceList forces_ protected
Definition at line 219 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::solveMomentum().
addedMassTotal_
scalar addedMassTotal_ protected
Definition at line 225 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::addSources(), kinematicSingleLayer::info(), and kinematicSingleLayer::transferPrimaryRegionSourceFields().
The documentation for this class was generated from the following files:
src/regionModels/surfaceFilmModels/kinematicSingleLayer/kinematicSingleLayer.H
src/regionModels/surfaceFilmModels/kinematicSingleLayer/kinematicSingleLayer.C
src/regionModels/surfaceFilmModels/kinematicSingleLayer/kinematicSingleLayerI.H
src/regionModels/surfaceFilmModels/kinematicSingleLayer/kinematicSingleLayerTemplates.C