OpenFOAM: optMeshMovementVolumetricBSplines Class Reference
optMeshMovementVolumetricBSplines Class Reference
Converts NURBS volume control points update to actual mesh movement. Internal points are also moved based on the movement of the control points.
#include <optMeshMovementVolumetricBSplines.H>
Public Member Functions
TypeName ("volumetricBSplines")
optMeshMovementVolumetricBSplines (fvMesh &mesh, const dictionary &dict, const labelList &patchIDs)
virtual ~optMeshMovementVolumetricBSplines ()=default
void moveMesh ()
virtual void storeDesignVariables ()
virtual void resetDesignVariables ()
virtual scalar computeEta (const scalarField &correction)
virtual labelList getActiveDesignVariables () const
Public Member Functions inherited from optMeshMovement
TypeName ("optMeshMovement")
declareRunTimeSelectionTable (autoPtr, optMeshMovement, dictionary,(fvMesh &mesh, const dictionary &dict, const labelList &patchIDs),(mesh, dict, patchIDs))
optMeshMovement (fvMesh &mesh, const dictionary &dict, const labelList &patchIDs)
virtual ~optMeshMovement ()=default
void setCorrection (const scalarField &correction)
autoPtr< displacementMethod > & returnDisplacementMethod ()
const labelList & getPatchIDs ()
void writeMeshQualityMetrics ()
bool maxAllowedDisplacementSet () const
Protected Member Functions
vectorField controlPointMovement (const scalarField &correction)
Protected Member Functions inherited from optMeshMovement
scalar getMaxAllowedDisplacement () const
Protected Attributes
volBSplinesBase & volBSplinesBase_
List< vectorField > cpsInit_
Protected Attributes inherited from optMeshMovement
fvMesh & mesh_
const dictionary & dict_
scalarField correction_
labelList patchIDs_
vectorField pointsInit_
autoPtr< displacementMethod > displMethodPtr_
bool writeMeshQualityMetrics_
Additional Inherited Members
Static Public Member Functions inherited from optMeshMovement
static autoPtr< optMeshMovement > New (fvMesh &mesh, const dictionary &dict, const labelList &patchIDs)
Detailed Description
Converts NURBS volume control points update to actual mesh movement. Internal points are also moved based on the movement of the control points.
Source files
optMeshMovementVolumetricBSplines.H
optMeshMovementVolumetricBSplines.C
Definition at line 50 of file optMeshMovementVolumetricBSplines.H.
Constructor & Destructor Documentation
optMeshMovementVolumetricBSplines()
optMeshMovementVolumetricBSplines (fvMesh & mesh, const dictionary & dict, const labelList & patchIDs)
Definition at line 65 of file optMeshMovementVolumetricBSplines.C.
References volBSplinesBase::boxesRef(), optMeshMovementVolumetricBSplines::cpsInit_, forAll, List< T >::setSize(), and optMeshMovementVolumetricBSplines::volBSplinesBase_.
~optMeshMovementVolumetricBSplines()
virtual ~optMeshMovementVolumetricBSplines () virtual default
Member Function Documentation
controlPointMovement()
Foam::vectorField controlPointMovement (const scalarField & correction) protected
Definition at line 43 of file optMeshMovementVolumetricBSplines.C.
References Foam::correction(), optMeshMovement::displMethodPtr_, UPtrList< T >::size(), and Foam::Zero.
TypeName()
TypeName ("volumetricBSplines")
moveMesh()
void moveMesh () virtual
Reimplemented from optMeshMovement.
Definition at line 94 of file optMeshMovementVolumetricBSplines.C.
References optMeshMovement::moveMesh().
storeDesignVariables()
void storeDesignVariables () virtual
Reimplemented from optMeshMovement.
Definition at line 107 of file optMeshMovementVolumetricBSplines.C.
References forAll, and optMeshMovement::storeDesignVariables().
resetDesignVariables()
void resetDesignVariables () virtual
Reimplemented from optMeshMovement.
Definition at line 118 of file optMeshMovementVolumetricBSplines.C.
References DebugInfo, Foam::endl(), forAll, and optMeshMovement::resetDesignVariables().
computeEta()
Foam::scalar computeEta (const scalarField & correction) virtual
Implements optMeshMovement.
Definition at line 135 of file optMeshMovementVolumetricBSplines.C.
References Foam::correction(), Foam::endl(), and Foam::Info.
getActiveDesignVariables()
Foam::labelList getActiveDesignVariables () const virtual
Reimplemented from optMeshMovement.
Definition at line 160 of file optMeshMovementVolumetricBSplines.C.
Member Data Documentation
volBSplinesBase_
volBSplinesBase& volBSplinesBase_ protected
Definition at line 59 of file optMeshMovementVolumetricBSplines.H.
Referenced by optMeshMovementVolumetricBSplines::optMeshMovementVolumetricBSplines().
cpsInit_
List<vectorField> cpsInit_ protected
Definition at line 62 of file optMeshMovementVolumetricBSplines.H.
Referenced by optMeshMovementVolumetricBSplines::optMeshMovementVolumetricBSplines().
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/optimisation/optMeshMovement/optMeshMovementVolumetricBSplines/optMeshMovementVolumetricBSplines.H
src/optimisation/adjointOptimisation/adjoint/optimisation/optMeshMovement/optMeshMovementVolumetricBSplines/optMeshMovementVolumetricBSplines.C