OpenFOAM: parProfiling Class Reference
parProfiling Class Reference
FunctionObjects » Utility function objects
Simple (simplistic) mpi-profiling.
#include <parProfiling.H>
Public Member Functions
parProfiling (const parProfiling &)=delete
void operator= (const parProfiling &)=delete
TypeName ("parProfiling")
parProfiling (const word &name, const Time &runTime, const dictionary &dict)
virtual ~parProfiling ()
void report ()
virtual bool execute ()
virtual bool write ()
virtual bool end ()
Public Member Functions inherited from functionObject
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name, const bool withNamePrefix=defaultUseNamePrefix)
autoPtr< functionObject > clone () const
virtual ~functionObject ()=default
virtual const word & type () const =0
const word & name () const noexcept
bool useNamePrefix () const noexcept
bool useNamePrefix (bool on) noexcept
virtual bool read (const dictionary &dict)
virtual bool execute (const label subIndex)
virtual bool adjustTimeStep ()
virtual bool filesModified () const
virtual void updateMesh (const mapPolyMesh &mpm)
virtual void movePoints (const polyMesh &mesh)
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &runTime, const dictionary &dict)
Public Attributes inherited from functionObject
bool log
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
static bool defaultUseNamePrefix
static word outputPrefix
Protected Member Functions inherited from functionObject
word scopedName (const word &name) const
Detailed Description
Simple (simplistic) mpi-profiling.
Usage
Example of function object specification:
profiling
{
    type  parProfiling;
    libs  (utilityFunctionObjects);
    // Report stats on exit only (instead of every time step)
    executeControl  onEnd;
    writeControl    none;
    detail          0;
}
Source files
parProfiling.H
parProfiling.C
Definition at line 66 of file parProfiling.H.
Constructor & Destructor Documentation
parProfiling() [1/2]
parProfiling (const parProfiling &) delete
parProfiling() [2/2]
parProfiling (const word & name, const Time & runTime, const dictionary & dict)
Definition at line 47 of file parProfiling.C.
References dict, profilingPstream::enable(), and Foam::name().
~parProfiling()
~parProfiling () virtual
Definition at line 64 of file parProfiling.C.
References profilingPstream::disable().
Member Function Documentation
operator=()
void operator= (const parProfiling &) delete
TypeName()
TypeName ("parProfiling")
report()
void report ()
Definition at line 72 of file parProfiling.C.
References Foam::Info, Foam::nl, UPstream::nProcs(), UPstream::parRun(), and profilingPstream::report().
execute()
bool execute () virtual
Implements functionObject.
Definition at line 82 of file parProfiling.C.
write()
bool write () virtual
Implements functionObject.
Definition at line 89 of file parProfiling.C.
end()
bool end () virtual
Reimplemented from functionObject.
Definition at line 95 of file parProfiling.C.
References profilingPstream::disable().
The documentation for this class was generated from the following files:
src/functionObjects/utilities/parProfiling/parProfiling.H
src/functionObjects/utilities/parProfiling/parProfiling.C