OpenFOAM: LandauTellerReactionRate Class Reference
LandauTellerReactionRate Class Reference
Landau-Teller reaction rate.
#include <LandauTellerReactionRate.H>
Public Member Functions
LandauTellerReactionRate (const scalar A, const scalar beta, const scalar Ta, const scalar B, const scalar C)
LandauTellerReactionRate (const speciesTable &species, const dictionary &dict)
scalar operator() (const scalar p, const scalar T, const scalarField &c) const
void write (Ostream &os) const
Static Public Member Functions
static word type ()
Friends
Ostream & operator<< (Ostream &, const LandauTellerReactionRate &)
Detailed Description
Landau-Teller reaction rate.
Source files
LandauTellerReactionRate.H
LandauTellerReactionRateI.H
Definition at line 54 of file LandauTellerReactionRate.H.
Constructor & Destructor Documentation
LandauTellerReactionRate() [1/2]
LandauTellerReactionRate (const scalar A, const scalar beta, const scalar Ta, const scalar B, const scalar C) inline
Definition at line 23 of file LandauTellerReactionRateI.H.
LandauTellerReactionRate() [2/2]
LandauTellerReactionRate (const speciesTable & species, const dictionary & dict) inline
Definition at line 40 of file LandauTellerReactionRateI.H.
Member Function Documentation
type()
static word type () inline static
Definition at line 90 of file LandauTellerReactionRate.H.
operator()()
Foam::scalar operator() (const scalar p, const scalar T, const scalarField & c) const inline
Definition at line 56 of file LandauTellerReactionRateI.H.
References Foam::cbrt(), Foam::exp(), Foam::mag(), Foam::pow(), and T.
write()
void write (Ostream & os) const inline
Definition at line 96 of file LandauTellerReactionRateI.H.
References os(), and Ostream::writeEntry().
Friends And Related Symbol Documentation
operator<<
Ostream & operator<< (Ostream & , const LandauTellerReactionRate &) friend
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/reaction/reactionRate/LandauTellerReactionRate/LandauTellerReactionRate.H
src/thermophysicalModels/specie/reaction/reactionRate/LandauTellerReactionRate/LandauTellerReactionRateI.H