OpenFOAM: SHA1Digest Class Reference
SHA1Digest Class Reference
The SHA1 message digest.
#include <SHA1Digest.H>
Public Member Functions
SHA1Digest ()
SHA1Digest (Istream &is)
SHA1Digest (const char *content, std::size_t len)
SHA1Digest (const unsigned char *content, std::size_t len)
void clear ()
bool empty () const
std::string str (const bool prefixed=false) const
Istream & read (Istream &is)
Ostream & write (Ostream &os, const bool prefixed=false) const
const unsigned char * cdata () const noexcept
const char * cdata_bytes () const noexcept
char * data_bytes () noexcept
bool operator== (const SHA1Digest &rhs) const
bool operator== (const std::string &hexdigits) const
bool operator== (const char *hexdigits) const
bool operator!= (const SHA1Digest &rhs) const
bool operator!= (const std::string &hexdigits) const
bool operator!= (const char *hexdigits) const
Static Public Member Functions
static constexpr unsigned size_bytes () noexcept
static constexpr unsigned max_size () noexcept
Static Public Attributes
static const SHA1Digest null
Friends
class SHA1
Detailed Description
The SHA1 message digest.
See also
Foam::SHA1
Source files
SHA1Digest.H
SHA1Digest.C
Definition at line 56 of file SHA1Digest.H.
Constructor & Destructor Documentation
SHA1Digest() [1/4]
SHA1Digest ()
Definition at line 163 of file SHA1Digest.C.
References SHA1Digest::clear().
SHA1Digest() [2/4]
SHA1Digest (Istream & is) explicit
Definition at line 183 of file SHA1Digest.C.
References clear(), and Foam::read().
SHA1Digest() [3/4]
SHA1Digest (const char * content, std::size_t len)
Definition at line 169 of file SHA1Digest.C.
References clear().
SHA1Digest() [4/4]
SHA1Digest (const unsigned char * content, std::size_t len)
Definition at line 176 of file SHA1Digest.C.
References clear().
Member Function Documentation
clear()
void clear ()
Definition at line 192 of file SHA1Digest.C.
Referenced by SHA1Digest::SHA1Digest().
empty()
bool empty () const
Definition at line 198 of file SHA1Digest.C.
str()
std::string str (const bool prefixed = false) const
Definition at line 227 of file SHA1Digest.C.
References hexChars, and PtrList< T >::resize().
read()
Foam::Istream & read (Istream & is)
Definition at line 212 of file SHA1Digest.C.
References FUNCTION_NAME, and Foam::readHexDigit().
write()
Foam::Ostream & write (Ostream & os, const bool prefixed = false) const
Definition at line 252 of file SHA1Digest.C.
References IOstream::check(), FUNCTION_NAME, hexChars, os(), and OBJstream::write().
Referenced by dynamicCode::writeDigest().
cdata()
const unsigned char * cdata () const inline noexcept
Definition at line 124 of file SHA1Digest.H.
cdata_bytes()
const char * cdata_bytes () const inline noexcept
Definition at line 128 of file SHA1Digest.H.
data_bytes()
char * data_bytes () inline noexcept
Definition at line 136 of file SHA1Digest.H.
size_bytes()
static constexpr unsigned size_bytes () inline static constexpr noexcept
Definition at line 142 of file SHA1Digest.H.
max_size()
static constexpr unsigned max_size () inline static constexpr noexcept
Definition at line 145 of file SHA1Digest.H.
Referenced by fileOperation::getGlobalHostIORanks(), and Foam::getHostGroupIds().
operator==() [1/3]
bool operator== (const SHA1Digest & rhs) const
Definition at line 272 of file SHA1Digest.C.
operator==() [2/3]
bool operator== (const std::string & hexdigits) const
Definition at line 278 of file SHA1Digest.C.
operator==() [3/3]
bool operator== (const char * hexdigits) const
Definition at line 287 of file SHA1Digest.C.
operator!=() [1/3]
bool operator!= (const SHA1Digest & rhs) const
Definition at line 296 of file SHA1Digest.C.
References Foam::operator==().
operator!=() [2/3]
bool operator!= (const std::string & hexdigits) const
Definition at line 302 of file SHA1Digest.C.
References Foam::operator==().
operator!=() [3/3]
bool operator!= (const char * hexdigits) const
Definition at line 308 of file SHA1Digest.C.
References Foam::operator==().
Friends And Related Symbol Documentation
SHA1
friend class SHA1 friend
Definition at line 67 of file SHA1Digest.H.
Member Data Documentation
null
const Foam::SHA1Digest null static
Definition at line 78 of file SHA1Digest.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/hashes/SHA1/SHA1Digest.H
src/OpenFOAM/primitives/hashes/SHA1/SHA1Digest.C