OpenFOAM: STLtriangle Class Reference
STLtriangle Class Reference
A triangle representation for STL files.
#include <STLtriangle.H>
Public Member Functions
STLtriangle ()=default
STLtriangle (const STLpoint &normal, const STLpoint &p0, const STLpoint &p1, const STLpoint &p2, uint16_t attrib)
STLtriangle (std::istream &is)
const STLpoint & normal () const noexcept
const STLpoint & a () const noexcept
const STLpoint & b () const noexcept
const STLpoint & c () const noexcept
uint16_t attrib () const noexcept
void read (std::istream &is)
void write (std::ostream &os) const
Ostream & print (Ostream &os) const
Static Public Member Functions
static void write (Ostream &os, const vector &norm, const point &p0, const point &p1, const point &p2)
static void write (Ostream &os, const point &p0, const point &p1, const point &p2)
Friends
Ostream & operator<< (Ostream &os, const STLtriangle &tri)
Detailed Description
A triangle representation for STL files.
Source files
STLtriangle.H
STLtriangleI.H
Definition at line 54 of file STLtriangle.H.
Constructor & Destructor Documentation
STLtriangle() [1/3]
STLtriangle () default
STLtriangle() [2/3]
STLtriangle (const STLpoint & normal, const STLpoint & p0, const STLpoint & p1, const STLpoint & p2, uint16_t attrib) inline
Definition at line 26 of file STLtriangleI.H.
STLtriangle() [3/3]
STLtriangle (std::istream & is) inline
Definition at line 43 of file STLtriangleI.H.
References Foam::read().
Member Function Documentation
normal()
const STLpoint & normal () const inline noexcept
Definition at line 98 of file STLtriangle.H.
Referenced by Foam::operator<<().
a()
const STLpoint & a () const inline noexcept
Definition at line 99 of file STLtriangle.H.
Referenced by Foam::operator<<().
b()
const STLpoint & b () const inline noexcept
Definition at line 100 of file STLtriangle.H.
Referenced by Foam::operator<<().
c()
const STLpoint & c () const inline noexcept
Definition at line 101 of file STLtriangle.H.
Referenced by Foam::operator<<().
attrib()
uint16_t attrib () const inline noexcept
Definition at line 102 of file STLtriangle.H.
Referenced by Foam::operator<<().
read()
void read (std::istream & is) inline
Definition at line 51 of file STLtriangleI.H.
write() [1/3]
void write (std::ostream & os) const inline
Definition at line 58 of file STLtriangleI.H.
References os(), and OBJstream::write().
print()
Foam::Ostream & print (Ostream & os) const inline
Definition at line 65 of file STLtriangleI.H.
References Foam::nl, and os().
write() [2/3]
void write (Ostream & os, const vector & norm, const point & p0, const point & p1, const point & p2) inline static
Definition at line 80 of file STLtriangleI.H.
References Foam::nl, os(), p0, Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
write() [3/3]
void write (Ostream & os, const point & p0, const point & p1, const point & p2) inline static
Definition at line 100 of file STLtriangleI.H.
References os(), p0, triangle< Point, PointRef >::unitNormal(), and write().
Friends And Related Symbol Documentation
operator<<
Ostream & operator<< (Ostream & os, const STLtriangle & tri) friend
The documentation for this class was generated from the following files:
src/fileFormats/stl/STLtriangle.H
src/fileFormats/stl/STLtriangleI.H