OpenFOAM: NASCore Class Reference
NASCore Class Reference
Core routines used when reading/writing NASTRAN files.
#include <NASCore.H>
Public Types
enum fieldFormat { SHORT , LONG , FREE }
enum loadFormat { PLOAD2 , PLOAD4 }
Public Member Functions
NASCore ()=default
Static Public Member Functions
static scalar readNasScalar (const std::string &str)
static std::string nextNasField (const std::string &str, std::string::size_type &pos, std::string::size_type len)
static void setPrecision (Ostream &os, const fieldFormat format)
static Ostream & writeKeyword (Ostream &os, const word &keyword, const fieldFormat format)
static void writeCoord (Ostream &os, const point &p, const label pointId, const fieldFormat format)
static label faceDecomposition (const UList< point > &points, const UList< face > &faces, labelList &decompOffsets, DynamicList< face > &decompFaces)
Static Public Attributes
static const Enum< fieldFormat > fieldFormatNames
static const Enum< loadFormat > loadFormatNames
Detailed Description
Core routines used when reading/writing NASTRAN files.
Source files
NASCore.H
NASCore.C
Definition at line 53 of file NASCore.H.
Member Enumeration Documentation
fieldFormat
enum fieldFormat
Enumerator
SHORT
Short format (field width = 8)
LONG
Long format (field width = 16)
FREE
Free format (comma-separated fields)
Definition at line 58 of file NASCore.H.
loadFormat
enum loadFormat
Enumerator
PLOAD2
PLOAD4
Definition at line 69 of file NASCore.H.
Constructor & Destructor Documentation
NASCore()
NASCore () default
Member Function Documentation
readNasScalar()
Foam::scalar readNasScalar (const std::string & str) static
Definition at line 68 of file NASCore.C.
References Foam::parsing::errorNames, Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, Foam::parsing::GENERAL, Foam::isspace(), Foam::pow(), and Foam::readInt().
nextNasField()
std::string nextNasField (const std::string & str, std::string::size_type & pos, std::string::size_type len) static
Definition at line 114 of file NASCore.C.
References Foam::pos().
setPrecision()
void setPrecision (Ostream & os, const fieldFormat format) static
Definition at line 138 of file NASCore.C.
References format(), and os().
Referenced by nastranWriter::write(), nastranWriter::writeTemplate(), nastranWriter::writeTemplate(), and nastranWriter::writeTemplate().
writeKeyword()
Foam::Ostream & writeKeyword (Ostream & os, const word & keyword, const fieldFormat format) static
Definition at line 172 of file NASCore.C.
References format(), os(), and Foam::setw().
writeCoord()
void writeCoord (Ostream & os, const point & p, const label pointId, const fieldFormat format) static
Parameters
pointId 0-based Point Id
Definition at line 206 of file NASCore.C.
References format(), Foam::nl, os(), p, and Foam::putValue().
faceDecomposition()
Foam::label faceDecomposition (const UList< point > & points, const UList< face > & faces, labelList & decompOffsets, DynamicList< face > & decompFaces) static
Definition at line 272 of file NASCore.C.
References UPtrList< T >::begin(), PtrList< T >::clear(), f(), n, points, PtrList< T >::resize(), and UPtrList< T >::size().
Referenced by nastranWriter::writeTemplate().
Member Data Documentation
fieldFormatNames
const Foam::Enum< Foam::fileFormats::NASCore::fieldFormat > fieldFormatNames static
Definition at line 66 of file NASCore.H.
loadFormatNames
const Foam::Enum< Foam::fileFormats::NASCore::loadFormat > loadFormatNames static
Definition at line 76 of file NASCore.H.
Referenced by nastranWriter::nastranWriter(), nastranWriter::writeFaceValue(), and nastranWriter::writeTemplate().
The documentation for this class was generated from the following files:
src/fileFormats/nastran/NASCore.H
src/fileFormats/nastran/NASCore.C