OpenFOAM: DeardorffDiffStress< BasicTurbulenceModel > Class Template Reference
DeardorffDiffStress< BasicTurbulenceModel > Class Template Reference
Turbulence models » LES turbulence
Differential SGS Stress Equation Model for incompressible and compressible flows.
#include <DeardorffDiffStress.H>
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from ReynoldsStress< LESModel< BasicTurbulenceModel > >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from LESModel< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("DeardorffDiffStress")
DeardorffDiffStress (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
virtual ~DeardorffDiffStress ()=default
virtual bool read ()
virtual void correct ()
Public Member Functions inherited from ReynoldsStress< LESModel< BasicTurbulenceModel > >
Foam::tmp< Foam::fvVectorMatrix > DivDevRhoReff (const RhoFieldType &rho, volVectorField &U) const
ReynoldsStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~ReynoldsStress ()=default
virtual tmp< volScalarField > nut () const
virtual tmp< scalarField > nut (const label patchi) const
virtual tmp< volScalarField > k () const
virtual tmp< volSymmTensorField > R () const
virtual tmp< volSymmTensorField > devRhoReff () const
virtual tmp< volSymmTensorField > devRhoReff (const volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
virtual void validate ()
Public Member Functions inherited from LESModel< BasicTurbulenceModel >
TypeName ("LES")
declareRunTimeSelectionTable (autoPtr, LESModel, dictionary,(const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName),(alpha, rho, U, alphaRhoPhi, phi, transport, propertiesName))
LESModel (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~LESModel ()=default
virtual const dictionary & coeffDict () const
const dimensionedScalar & Ce () const noexcept
const dimensionedScalar & kMin () const
dimensionedScalar & kMin ()
const volScalarField & delta () const
virtual tmp< volScalarField > nuEff () const
virtual tmp< scalarField > nuEff (const label patchi) const
virtual tmp< volScalarField > epsilon () const
virtual tmp< volScalarField > omega () const
Protected Member Functions
virtual void correctNut ()
Protected Member Functions inherited from ReynoldsStress< LESModel< BasicTurbulenceModel > >
void boundNormalStress (volSymmTensorField &R) const
void correctWallShearStress (volSymmTensorField &R) const
void checkRealizabilityConditions (const volSymmTensorField &R) const
tmp< fvVectorMatrix > DivDevRhoReff (const RhoFieldType &rho, volVectorField &U) const
Protected Member Functions inherited from LESModel< BasicTurbulenceModel >
virtual void printCoeffs (const word &type)
LESModel (const LESModel &)=delete
void operator= (const LESModel &)=delete
Protected Attributes
dimensionedScalar Ck_
dimensionedScalar Cm_
dimensionedScalar Ce_
dimensionedScalar Cs_
Protected Attributes inherited from ReynoldsStress< LESModel< BasicTurbulenceModel > >
dimensionedScalar couplingFactor_
volSymmTensorField R_
volScalarField nut_
Protected Attributes inherited from LESModel< BasicTurbulenceModel >
dictionary LESDict_
Switch turbulence_
Switch printCoeffs_
dictionary coeffDict_
dimensionedScalar Ce_
dimensionedScalar kMin_
dimensionedScalar epsilonMin_
dimensionedScalar omegaMin_
autoPtr< Foam::LESdelta > delta_
Additional Inherited Members
Static Public Member Functions inherited from LESModel< BasicTurbulenceModel >
static autoPtr< LESModel > New (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Detailed Description
template<class BasicTurbulenceModel>
class Foam::LESModels::DeardorffDiffStress< BasicTurbulenceModel >
Differential SGS Stress Equation Model for incompressible and compressible flows.
Reference:
    Deardorff, J. W. (1973).
    The use of subgrid transport equations in a three-dimensional model
    of atmospheric turbulence.
    Journal of Fluids Engineering, 95(3), 429-438.
This SGS model uses a full balance equation for the SGS stress tensor to simulate the behaviour of B.
This implementation is as described in the above paper except that the triple correlation model of Donaldson is replaced with the generalized gradient diffusion model of Daly and Harlow:
    Daly, B. J., & Harlow, F. H. (1970).
    Transport equations in turbulence.
    Physics of Fluids (1958-1988), 13(11), 2634-2649.
with the default value for the coefficient Cs of 0.25 from
    Launder, B. E., Reece, G. J., & Rodi, W. (1975).
    Progress in the development of a Reynolds-stress turbulence closure.
    Journal of fluid mechanics, 68(03), 537-566.
Source files
DeardorffDiffStress.H
DeardorffDiffStress.C
Definition at line 81 of file DeardorffDiffStress.H.
Member Typedef Documentation
alphaField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 114 of file DeardorffDiffStress.H.
rhoField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 115 of file DeardorffDiffStress.H.
transportModel
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 116 of file DeardorffDiffStress.H.
Constructor & Destructor Documentation
DeardorffDiffStress()
template<class BasicTurbulenceModel > DeardorffDiffStress (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Definition at line 49 of file DeardorffDiffStress.C.
References ReynoldsStress< LESModel< BasicTurbulenceModel > >::boundNormalStress(), LESModel< BasicTurbulenceModel >::printCoeffs(), ReynoldsStress< LESModel< BasicTurbulenceModel > >::R_, and Foam::type().
~DeardorffDiffStress()
template<class BasicTurbulenceModel > virtual ~DeardorffDiffStress () virtual default
Member Function Documentation
correctNut()
template<class BasicTurbulenceModel > void correctNut () protected virtual
Implements ReynoldsStress< LESModel< BasicTurbulenceModel > >.
Definition at line 36 of file DeardorffDiffStress.C.
References delta, k, options::New(), and Foam::sqrt().
TypeName()
template<class BasicTurbulenceModel > TypeName ("DeardorffDiffStress< BasicTurbulenceModel >")
read()
template<class BasicTurbulenceModel > bool read () virtual
Implements ReynoldsStress< LESModel< BasicTurbulenceModel > >.
Definition at line 121 of file DeardorffDiffStress.C.
References Foam::read().
correct()
template<class BasicTurbulenceModel > void correct () virtual
Implements ReynoldsStress< LESModel< BasicTurbulenceModel > >.
Definition at line 138 of file DeardorffDiffStress.C.
References alpha, correct(), D, Foam::fvm::ddt(), delta, Foam::fvm::div(), epsilon, fvOptions, Foam::fvc::grad(), Foam::I, k, Foam::fvm::laplacian(), options::New(), nu, R, rho, Foam::fvm::Sp(), Foam::sqrt(), Foam::symm(), Foam::twoSymm(), and U.
Member Data Documentation
Ck_
template<class BasicTurbulenceModel > dimensionedScalar Ck_ protected
Definition at line 100 of file DeardorffDiffStress.H.
Cm_
template<class BasicTurbulenceModel > dimensionedScalar Cm_ protected
Definition at line 101 of file DeardorffDiffStress.H.
Ce_
template<class BasicTurbulenceModel > dimensionedScalar Ce_ protected
Definition at line 102 of file DeardorffDiffStress.H.
Cs_
template<class BasicTurbulenceModel > dimensionedScalar Cs_ protected
Definition at line 103 of file DeardorffDiffStress.H.
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/LES/DeardorffDiffStress/DeardorffDiffStress.H
src/TurbulenceModels/turbulenceModels/LES/DeardorffDiffStress/DeardorffDiffStress.C