OpenFOAM: pointEdgeStructuredWalk Class Reference
pointEdgeStructuredWalk Class Reference
Determines length of string of edges walked to point.
#include <pointEdgeStructuredWalk.H>
Public Member Functions
pointEdgeStructuredWalk ()
pointEdgeStructuredWalk (const point &point0, const point &previousPoint, const scalar dist, const vector &data, const label index=-1)
scalar dist () const
const vector & data () const
label index () const
bool inZone () const
template<class TrackingData >
bool valid (TrackingData &td) const
template<class TrackingData >
bool sameGeometry (const pointEdgeStructuredWalk &, const scalar tol, TrackingData &td) const
template<class TrackingData >
void leaveDomain (const polyPatch &patch, const label patchPointi, const point &pos, TrackingData &td)
template<class TrackingData >
void enterDomain (const polyPatch &patch, const label patchPointi, const point &pos, TrackingData &td)
template<class TrackingData >
void transform (const tensor &rotTensor, TrackingData &td)
template<class TrackingData >
bool updatePoint (const polyMesh &mesh, const label pointi, const label edgeI, const pointEdgeStructuredWalk &edgeInfo, const scalar tol, TrackingData &td)
template<class TrackingData >
bool updatePoint (const polyMesh &mesh, const label pointi, const pointEdgeStructuredWalk &newPointInfo, const scalar tol, TrackingData &td)
template<class TrackingData >
bool updatePoint (const pointEdgeStructuredWalk &newPointInfo, const scalar tol, TrackingData &td)
template<class TrackingData >
bool updateEdge (const polyMesh &mesh, const label edgeI, const label pointi, const pointEdgeStructuredWalk &pointInfo, const scalar tol, TrackingData &td)
template<class TrackingData >
bool equal (const pointEdgeStructuredWalk &, TrackingData &) const
bool operator== (const pointEdgeStructuredWalk &) const
bool operator!= (const pointEdgeStructuredWalk &) const
Friends
Ostream & operator<< (Ostream &, const pointEdgeStructuredWalk &)
Istream & operator>> (Istream &, pointEdgeStructuredWalk &)
Detailed Description
Determines length of string of edges walked to point.
Source files
pointEdgeStructuredWalk.H
pointEdgeStructuredWalkI.H
pointEdgeStructuredWalk.C
Definition at line 57 of file pointEdgeStructuredWalk.H.
Constructor & Destructor Documentation
pointEdgeStructuredWalk() [1/2]
pointEdgeStructuredWalk () inline
Definition at line 52 of file pointEdgeStructuredWalkI.H.
pointEdgeStructuredWalk() [2/2]
pointEdgeStructuredWalk (const point & point0, const point & previousPoint, const scalar dist, const vector & data, const label index = -1) inline
Definition at line 62 of file pointEdgeStructuredWalkI.H.
Member Function Documentation
dist()
scalar dist () const inline
Definition at line 111 of file pointEdgeStructuredWalk.H.
data()
const vector & data () const inline
Definition at line 117 of file pointEdgeStructuredWalk.H.
index()
label index () const inline
Definition at line 123 of file pointEdgeStructuredWalk.H.
inZone()
bool inZone () const inline
Definition at line 81 of file pointEdgeStructuredWalkI.H.
References VectorSpace< Form, Cmpt, Ncmpts >::max.
valid()
template<class TrackingData > bool valid (TrackingData & td) const inline
Definition at line 88 of file pointEdgeStructuredWalkI.H.
References VectorSpace< Form, Cmpt, Ncmpts >::max.
sameGeometry()
template<class TrackingData > bool sameGeometry (const pointEdgeStructuredWalk & w2, const scalar tol, TrackingData & td) const inline
Definition at line 96 of file pointEdgeStructuredWalkI.H.
References Foam::diff(), Foam::mag(), and w2.
leaveDomain()
template<class TrackingData > void leaveDomain (const polyPatch & patch, const label patchPointi, const point & pos, TrackingData & td) inline
Definition at line 124 of file pointEdgeStructuredWalkI.H.
enterDomain()
template<class TrackingData > void enterDomain (const polyPatch & patch, const label patchPointi, const point & pos, TrackingData & td) inline
Definition at line 150 of file pointEdgeStructuredWalkI.H.
transform()
template<class TrackingData > void transform (const tensor & rotTensor, TrackingData & td) inline
Definition at line 137 of file pointEdgeStructuredWalkI.H.
References Foam::transform().
updatePoint() [1/3]
template<class TrackingData > bool updatePoint (const polyMesh & mesh, const label pointi, const label edgeI, const pointEdgeStructuredWalk & edgeInfo, const scalar tol, TrackingData & td) inline
Definition at line 165 of file pointEdgeStructuredWalkI.H.
References update().
updatePoint() [2/3]
template<class TrackingData > bool updatePoint (const polyMesh & mesh, const label pointi, const pointEdgeStructuredWalk & newPointInfo, const scalar tol, TrackingData & td) inline
Definition at line 186 of file pointEdgeStructuredWalkI.H.
References update().
updatePoint() [3/3]
template<class TrackingData > bool updatePoint (const pointEdgeStructuredWalk & newPointInfo, const scalar tol, TrackingData & td) inline
Definition at line 206 of file pointEdgeStructuredWalkI.H.
References update().
updateEdge()
template<class TrackingData > bool updateEdge (const polyMesh & mesh, const label edgeI, const label pointi, const pointEdgeStructuredWalk & pointInfo, const scalar tol, TrackingData & td) inline
Definition at line 219 of file pointEdgeStructuredWalkI.H.
References update().
equal()
template<class TrackingData > bool equal (const pointEdgeStructuredWalk & rhs, TrackingData & td) const inline
Definition at line 239 of file pointEdgeStructuredWalkI.H.
References Foam::operator==().
operator==()
bool operator== (const pointEdgeStructuredWalk & rhs) const inline
Definition at line 251 of file pointEdgeStructuredWalkI.H.
operator!=()
bool operator!= (const pointEdgeStructuredWalk & rhs) const inline
Definition at line 260 of file pointEdgeStructuredWalkI.H.
Friends And Related Symbol Documentation
operator<<
Ostream & operator<< (Ostream & , const pointEdgeStructuredWalk &) friend
operator>>
Istream & operator>> (Istream & , pointEdgeStructuredWalk &) friend
The documentation for this class was generated from the following files:
src/dynamicMesh/motionSolvers/displacement/layeredSolver/pointEdgeStructuredWalk.H
src/dynamicMesh/motionSolvers/displacement/layeredSolver/pointEdgeStructuredWalkI.H