OpenFOAM: projectFace Class Reference
projectFace Class Reference
Projects the given set of face points onto the selected surface of the geometry provided as a searchableSurfaces object.
#include <projectFace.H>
Public Member Functions
TypeName ("project")
projectFace (const dictionary &dict, const label index, const searchableSurfaces &geometry, Istream &is)
virtual ~projectFace ()=default
virtual void project (const blockDescriptor &, const label blockFacei, pointField &points) const
Public Member Functions inherited from blockFace
TypeName ("blockFace")
declareRunTimeSelectionTable (autoPtr, blockFace, Istream,(const dictionary &dict, const label index, const searchableSurfaces &geometry, Istream &is),(dict, index, geometry, is))
blockFace (const face &vertices)
blockFace (const dictionary &dict, const label index, Istream &is)
virtual autoPtr< blockFace > clone () const
virtual ~blockFace ()=default
const face & vertices () const
bool compare (const blockFace &) const
bool compare (const face &vertices) const
void write (Ostream &, const dictionary &) const
Additional Inherited Members
Static Public Member Functions inherited from blockFace
static autoPtr< blockFace > New (const dictionary &dict, const label index, const searchableSurfaces &geometry, Istream &)
Protected Attributes inherited from blockFace
const face vertices_
Detailed Description
Projects the given set of face points onto the selected surface of the geometry provided as a searchableSurfaces object.
Source files
projectFace.H
projectFace.C
Definition at line 50 of file projectFace.H.
Constructor & Destructor Documentation
projectFace()
projectFace (const dictionary & dict, const label index, const searchableSurfaces & geometry, Istream & is)
Definition at line 126 of file projectFace.C.
~projectFace()
virtual ~projectFace () virtual default
Member Function Documentation
TypeName()
TypeName ("project")
project()
void project (const blockDescriptor & desc, const label blockFacei, pointField & points) const virtual
Implements blockFace.
Definition at line 141 of file projectFace.C.
References Foam::endl(), UPtrList< T >::first(), forAll, Foam::Info, UPtrList< T >::last(), Foam::mag(), Foam::magSqr(), n, Foam::name(), points, Foam::Pout, Foam::sum(), linearInterpolationWeights::valueWeights(), Foam::Zero, and VectorSpace< Form, Cmpt, Ncmpts >::zero.
The documentation for this class was generated from the following files:
src/mesh/blockMesh/blockFaces/projectFace/projectFace.H
src/mesh/blockMesh/blockFaces/projectFace/projectFace.C