OpenFOAM: Reaction< ReactionThermo > Class Template Reference
Reaction< ReactionThermo > Class Template Reference
Simple extension of ReactionThermo to handle reaction kinetics in addition to the equilibrium thermodynamics already handled.
#include <Reaction.H>
Classes
struct specieCoeffs
Public Member Functions
TypeName ("Reaction")
declareRunTimeSelectionTable (autoPtr, Reaction, dictionary,(const speciesTable &species, const ReactionTable< ReactionThermo > &thermoDatabase, const dictionary &dict),(species, thermoDatabase, dict))
Reaction (const speciesTable &species, const List< specieCoeffs > &lhs, const List< specieCoeffs > &rhs, const ReactionTable< ReactionThermo > &thermoDatabase, bool initReactionThermo=true)
Reaction (const Reaction< ReactionThermo > &, const speciesTable &species)
Reaction (const speciesTable &species, const ReactionTable< ReactionThermo > &thermoDatabase, const dictionary &dict, bool initReactionThermo=true, bool failUnknownSpecie=true)
virtual autoPtr< Reaction< ReactionThermo > > clone () const
virtual autoPtr< Reaction< ReactionThermo > > clone (const speciesTable &species) const
virtual ~Reaction ()=default
const word & name () const noexcept
const speciesTable & species () const noexcept
const List< specieCoeffs > & lhs () const noexcept
const List< specieCoeffs > & rhs () const noexcept
virtual const speciesTable & gasSpecies () const
virtual const List< specieCoeffs > & grhs () const
virtual const List< specieCoeffs > & glhs () const
void setLRhs (Istream &, const speciesTable &, List< specieCoeffs > &lhs, List< specieCoeffs > &rhs, bool failUnknownSpecie=true)
virtual scalar kf (const scalar p, const scalar T, const scalarField &c) const
virtual scalar kr (const scalar kfwd, const scalar p, const scalar T, const scalarField &c) const
virtual scalar kr (const scalar p, const scalar T, const scalarField &c) const
virtual void write (Ostream &os) const
Static Public Member Functions
static autoPtr< Reaction< ReactionThermo > > New (const speciesTable &species, const ReactionTable< ReactionThermo > &thermoDatabase, const dictionary &dict)
Static Public Attributes
static label nUnNamedReactions = 0
Protected Member Functions
void reactionStrLeft (OStringStream &reaction) const
void reactionStrRight (OStringStream &reaction) const
Static Protected Member Functions
static void reactionStr (OStringStream &reaction, const speciesTable &species, const List< specieCoeffs > &reactCoeffs)
Friends
Ostream & operator<< (Ostream &, const Reaction< ReactionThermo > &)
Detailed Description
template<class ReactionThermo>
class Foam::Reaction< ReactionThermo >
Simple extension of ReactionThermo to handle reaction kinetics in addition to the equilibrium thermodynamics already handled.
Source files
Reaction.H
ReactionI.H
Reaction.C
Definition at line 66 of file Reaction.H.
Constructor & Destructor Documentation
Reaction() [1/3]
template<class ReactionThermo > Reaction (const speciesTable & species, const List< specieCoeffs > & lhs, const List< specieCoeffs > & rhs, const ReactionTable< ReactionThermo > & thermoDatabase, bool initReactionThermo = true)
Definition at line 149 of file Reaction.C.
Reaction() [2/3]
template<class ReactionThermo > Reaction (const Reaction< ReactionThermo > & r, const speciesTable & species)
Definition at line 172 of file Reaction.C.
Reaction() [3/3]
template<class ReactionThermo > Reaction (const speciesTable & species, const ReactionTable< ReactionThermo > & thermoDatabase, const dictionary & dict, bool initReactionThermo = true, bool failUnknownSpecie = true)
Definition at line 315 of file Reaction.C.
~Reaction()
template<class ReactionThermo > virtual ~Reaction () virtual default
Member Function Documentation
reactionStr()
template<class ReactionThermo > void reactionStr (OStringStream & reaction, const speciesTable & species, const List< specieCoeffs > & reactCoeffs) static protected
Definition at line 34 of file Reaction.C.
References Reaction< ReactionThermo >::specieCoeffs::exponent, Reaction< ReactionThermo >::specieCoeffs::index, Foam::mag(), reaction, UPtrList< T >::size(), and Reaction< ReactionThermo >::specieCoeffs::stoichCoeff.
reactionStrLeft()
template<class ReactionThermo > void reactionStrLeft (OStringStream & reaction) const protected
Definition at line 63 of file Reaction.C.
References reaction.
reactionStrRight()
template<class ReactionThermo > void reactionStrRight (OStringStream & reaction) const protected
Definition at line 73 of file Reaction.C.
References reaction.
TypeName()
template<class ReactionThermo > TypeName ("Reaction< ReactionThermo >")
declareRunTimeSelectionTable()
template<class ReactionThermo > declareRunTimeSelectionTable (autoPtr , Reaction< ReactionThermo > , dictionary , (const speciesTable &species, const ReactionTable< ReactionThermo > &thermoDatabase, const dictionary &dict) , (species, thermoDatabase, dict))
clone() [1/2]
template<class ReactionThermo > virtual autoPtr< Reaction< ReactionThermo > > clone () const inline virtual
Reimplemented in solidReaction< ReactionThermo >.
Definition at line 228 of file Reaction.H.
References Reaction< ReactionThermo >::New().
clone() [2/2]
template<class ReactionThermo > virtual autoPtr< Reaction< ReactionThermo > > clone (const speciesTable & species) const inline virtual
Reimplemented in solidReaction< ReactionThermo >.
Definition at line 234 of file Reaction.H.
References Reaction< ReactionThermo >::New(), and Reaction< ReactionThermo >::species().
New()
template<class ReactionThermo > Foam::autoPtr< Foam::Reaction< ReactionThermo > > New (const speciesTable & species, const ReactionTable< ReactionThermo > & thermoDatabase, const dictionary & dict) static
Definition at line 348 of file Reaction.C.
References dict, Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, and dictionary::get().
Referenced by Reaction< ReactionThermo >::clone(), and Reaction< ReactionThermo >::clone().
name()
template<class ReactionThermo > const word & name () const inline noexcept
Definition at line 263 of file Reaction.H.
species()
template<class ReactionThermo > const speciesTable & species () const inline noexcept
Definition at line 266 of file Reaction.H.
Referenced by solidReaction< ReactionThermo >::clone(), Reaction< ReactionThermo >::clone(), and solidReaction< ReactionThermo >::solidReaction().
lhs()
template<class ReactionThermo > const List< specieCoeffs > & lhs () const inline noexcept
Definition at line 269 of file Reaction.H.
rhs()
template<class ReactionThermo > const List< specieCoeffs > & rhs () const inline noexcept
Definition at line 272 of file Reaction.H.
gasSpecies()
template<class ReactionThermo > const Foam::speciesTable & gasSpecies () const virtual
Reimplemented in solidReaction< ReactionThermo >.
Definition at line 425 of file Reaction.C.
References NotImplemented.
grhs()
template<class ReactionThermo > const Foam::List< typename Foam::Reaction< ReactionThermo >::specieCoeffs > & grhs () const virtual
Reimplemented in solidReaction< ReactionThermo >.
Definition at line 443 of file Reaction.C.
References NotImplemented.
glhs()
template<class ReactionThermo > const Foam::List< typename Foam::Reaction< ReactionThermo >::specieCoeffs > & glhs () const virtual
Reimplemented in solidReaction< ReactionThermo >.
Definition at line 434 of file Reaction.C.
References NotImplemented.
setLRhs()
template<class ReactionThermo > void setLRhs (Istream & is, const speciesTable & species, List< specieCoeffs > & lhs, List< specieCoeffs > & rhs, bool failUnknownSpecie = true)
Definition at line 240 of file Reaction.C.
Referenced by solidReaction< ReactionThermo >::solidReaction().
kf()
template<class ReactionThermo > Foam::scalar kf (const scalar p, const scalar T, const scalarField & c) const virtual
Definition at line 388 of file Reaction.C.
kr() [1/2]
template<class ReactionThermo > Foam::scalar kr (const scalar kfwd, const scalar p, const scalar T, const scalarField & c) const virtual
Definition at line 400 of file Reaction.C.
kr() [2/2]
template<class ReactionThermo > Foam::scalar kr (const scalar p, const scalar T, const scalarField & c) const virtual
Definition at line 413 of file Reaction.C.
write()
template<class ReactionThermo > void write (Ostream & os) const virtual
Reimplemented in solidReaction< ReactionThermo >.
Definition at line 380 of file Reaction.C.
References os(), reaction, and Ostream::writeEntry().
Referenced by ReversibleReaction< ReactionType, ReactionThermo, ReactionRate >::write().
Friends And Related Symbol Documentation
operator<<
template<class ReactionThermo > Ostream & operator<< (Ostream & , const Reaction< ReactionThermo > &) friend
Member Data Documentation
nUnNamedReactions
template<class ReactionThermo > Foam::label nUnNamedReactions = 0 static
Definition at line 75 of file Reaction.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/reaction/Reactions/Reaction/Reaction.H
src/thermophysicalModels/specie/reaction/Reactions/Reaction/Reaction.C