OpenFOAM: timeVaryingUniformFixedValueFaPatchField< Type > Class Template Reference
timeVaryingUniformFixedValueFaPatchField< Type > Class Template Reference
A time-varying form of a uniform fixed value finite area boundary condition.
#include <timeVaryingUniformFixedValueFaPatchField.H>
Public Member Functions
TypeName ("timeVaryingUniformFixedValue")
timeVaryingUniformFixedValueFaPatchField (const faPatch &, const DimensionedField< Type, areaMesh > &)
timeVaryingUniformFixedValueFaPatchField (const faPatch &, const DimensionedField< Type, areaMesh > &, const dictionary &)
timeVaryingUniformFixedValueFaPatchField (const timeVaryingUniformFixedValueFaPatchField< Type > &, const faPatch &, const DimensionedField< Type, areaMesh > &, const faPatchFieldMapper &)
timeVaryingUniformFixedValueFaPatchField (const timeVaryingUniformFixedValueFaPatchField< Type > &)
virtual tmp< faPatchField< Type > > clone () const
timeVaryingUniformFixedValueFaPatchField (const timeVaryingUniformFixedValueFaPatchField< Type > &, const DimensionedField< Type, areaMesh > &)
virtual tmp< faPatchField< Type > > clone (const DimensionedField< Type, areaMesh > &iF) const
virtual ~timeVaryingUniformFixedValueFaPatchField ()=default
const interpolationTable< Type > & timeSeries () const
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Public Member Functions inherited from fixedValueFaPatchField< Type >
TypeName ("fixedValue")
fixedValueFaPatchField (const faPatch &, const DimensionedField< Type, areaMesh > &)
fixedValueFaPatchField (const faPatch &, const DimensionedField< Type, areaMesh > &, const Type &value)
fixedValueFaPatchField (const faPatch &, const DimensionedField< Type, areaMesh > &, const dictionary &, IOobjectOption::readOption requireValue=IOobjectOption::MUST_READ)
fixedValueFaPatchField (const fixedValueFaPatchField< Type > &, const faPatch &, const DimensionedField< Type, areaMesh > &, const faPatchFieldMapper &)
fixedValueFaPatchField (const fixedValueFaPatchField< Type > &)
fixedValueFaPatchField (const fixedValueFaPatchField< Type > &, const DimensionedField< Type, areaMesh > &)
virtual bool fixesValue () const
virtual tmp< Field< Type > > valueInternalCoeffs (const tmp< scalarField > &) const
virtual tmp< Field< Type > > valueBoundaryCoeffs (const tmp< scalarField > &) const
virtual tmp< Field< Type > > gradientInternalCoeffs () const
virtual tmp< Field< Type > > gradientBoundaryCoeffs () const
virtual void operator= (const UList< Type > &)
virtual void operator= (const faPatchField< Type > &)
virtual void operator+= (const faPatchField< Type > &)
virtual void operator-= (const faPatchField< Type > &)
virtual void operator*= (const faPatchField< scalar > &)
virtual void operator/= (const faPatchField< scalar > &)
virtual void operator+= (const Field< Type > &)
virtual void operator-= (const Field< Type > &)
virtual void operator*= (const Field< scalar > &)
virtual void operator/= (const Field< scalar > &)
virtual void operator= (const Type &)
virtual void operator+= (const Type &)
virtual void operator-= (const Type &)
virtual void operator*= (const scalar)
virtual void operator/= (const scalar)
Public Member Functions inherited from faPatchField< Type >
declareRunTimeSelectionTable (tmp, faPatchField, patch,(const faPatch &p, const DimensionedField< Type, areaMesh > &iF),(p, iF))
declareRunTimeSelectionTable (tmp, faPatchField, patchMapper,(const faPatchField< Type > &ptf, const faPatch &p, const DimensionedField< Type, areaMesh > &iF, const faPatchFieldMapper &m),(dynamic_cast< const faPatchFieldType & >(ptf), p, iF, m))
declareRunTimeSelectionTable (tmp, faPatchField, dictionary,(const faPatch &p, const DimensionedField< Type, areaMesh > &iF, const dictionary &dict),(p, iF, dict))
faPatchField (const faPatch &, const DimensionedField< Type, areaMesh > &)
faPatchField (const faPatch &, const DimensionedField< Type, areaMesh > &, const Type &value)
faPatchField (const faPatch &, const DimensionedField< Type, areaMesh > &, const Field< Type > &pfld)
faPatchField (const faPatch &, const DimensionedField< Type, areaMesh > &, Field< Type > &&pfld)
faPatchField (const faPatch &, const DimensionedField< Type, areaMesh > &, const dictionary &dict, IOobjectOption::readOption requireValue=IOobjectOption::LAZY_READ)
faPatchField (const faPatchField< Type > &, const faPatch &, const DimensionedField< Type, areaMesh > &, const faPatchFieldMapper &)
faPatchField (const faPatchField< Type > &)
faPatchField (const faPatchField< Type > &, const DimensionedField< Type, areaMesh > &)
virtual ~faPatchField ()=default
const DimensionedField< Type, areaMesh > & internalField () const noexcept
const Field< Type > & primitiveField () const noexcept
virtual void autoMap (const faPatchFieldMapper &)
virtual void rmap (const faPatchField< Type > &, const labelList &)
virtual tmp< Field< Type > > snGrad () const
virtual tmp< Field< Type > > patchInternalField () const
virtual void patchInternalField (Field< Type > &pfld) const
virtual tmp< Field< Type > > patchNeighbourField () const
virtual void initEvaluate (const Pstream::commsTypes commsType=Pstream::commsTypes::blocking)
virtual void evaluate (const Pstream::commsTypes commsType=Pstream::commsTypes::blocking)
void check (const faPatchField< Type > &) const
virtual void operator== (const faPatchField< Type > &)
virtual void operator== (const Field< Type > &)
virtual void operator== (const Type &)
template<class AnyType >
Foam::tmp< Foam::faPatchField< Type > > NewCalculatedType (const faPatchField< AnyType > &pf)
Public Member Functions inherited from faPatchFieldBase
TypeName ("faPatchField")
faPatchFieldBase (const faPatch &p)
faPatchFieldBase (const faPatch &p, const word &patchType)
faPatchFieldBase (const faPatch &p, const dictionary &dict)
faPatchFieldBase (const faPatchFieldBase &rhs, const faPatch &p)
faPatchFieldBase (const faPatchFieldBase &rhs)
virtual ~faPatchFieldBase ()=default
virtual bool coupled () const
const objectRegistry & db () const
const faPatch & patch () const noexcept
const word & patchType () const noexcept
word & patchType () noexcept
bool updated () const noexcept
bool manipulatedMatrix () const noexcept
void checkPatch (const faPatchFieldBase &rhs) const
Public Member Functions inherited from Field< Type >
constexpr Field () noexcept
Field (const label len)
Field (const label len, const Type &val)
Field (const label len, const Foam::zero)
Field (const Foam::one, const Type &val)
Field (const Foam::one, Type &&val)
Field (const Foam::one, const Foam::zero)
Field (const Field< Type > &fld)
Field (const UList< Type > &list)
template<class Addr >
Field (const IndirectListBase< Type, Addr > &list)
Field (Field< Type > &&fld)
Field (List< Type > &&list)
template<int SizeMin>
Field (DynamicList< Type, SizeMin > &&list)
Field (const UList< Type > &mapF, const labelUList &mapAddressing)
Field (const tmp< Field< Type > > &tmapF, const labelUList &mapAddressing)
Field (const UList< Type > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Field (const tmp< Field< Type > > &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Field (const UList< Type > &mapF, const FieldMapper &map, const bool applyFlip=true)
Field (const UList< Type > &mapF, const FieldMapper &map, const Type &defaultValue, const bool applyFlip=true)
Field (const UList< Type > &mapF, const FieldMapper &map, const UList< Type > &defaultValues, const bool applyFlip=true)
Field (const tmp< Field< Type > > &tmapF, const FieldMapper &map, const bool applyFlip=true)
Field (const tmp< Field< Type > > &tmapF, const FieldMapper &map, const Type &defaultValue, const bool applyFlip=true)
Field (const tmp< Field< Type > > &tmapF, const FieldMapper &map, const UList< Type > &defaultValues, const bool applyFlip=true)
Field (Field< Type > &fld, bool reuse)
Field (const tmp< Field< Type > > &tfld)
Field (Istream &is)
Field (const entry &e, const label len)
Field (const word &key, const dictionary &dict, const label len, IOobjectOption::readOption readOpt=IOobjectOption::MUST_READ)
tmp< Field< Type > > clone () const
void assign (const entry &e, const label len)
bool assign (const word &key, const dictionary &dict, const label len, IOobjectOption::readOption readOpt=IOobjectOption::MUST_READ)
void map (const UList< Type > &mapF, const labelUList &mapAddressing)
void map (const tmp< Field< Type > > &tmapF, const labelUList &mapAddressing)
void map (const UList< Type > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
void map (const tmp< Field< Type > > &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
void map (const UList< Type > &mapF, const FieldMapper &map, const bool applyFlip=true)
void map (const tmp< Field< Type > > &tmapF, const FieldMapper &map, const bool applyFlip=true)
void autoMap (const FieldMapper &map, const bool applyFlip=true)
void rmap (const UList< Type > &mapF, const labelUList &mapAddressing)
void rmap (const tmp< Field< Type > > &tmapF, const labelUList &mapAddressing)
void rmap (const UList< Type > &mapF, const labelUList &mapAddressing, const UList< scalar > &weights)
void rmap (const tmp< Field< Type > > &tmapF, const labelUList &mapAddressing, const UList< scalar > &weights)
void negate ()
void normalise ()
tmp< Field< cmptType > > component (const direction) const
void replace (const direction, const UList< cmptType > &)
void replace (const direction, const tmp< Field< cmptType > > &)
void replace (const direction, const cmptType &)
void clamp_min (const Type &lower)
void clamp_max (const Type &upper)
void clamp_range (const Type &lower, const Type &upper)
void clamp_range (const MinMax< Type > &range)
template<class VSForm >
VSForm block (const label start) const
tmp< Field< Type > > T () const
void writeEntry (const word &keyword, Ostream &os) const
SubField< Type > slice (const label pos, label len=-1)
const SubField< Type > slice (const label pos, label len=-1) const
SubField< Type > slice (const labelRange &range)
const SubField< Type > slice (const labelRange &range) const
void operator= (const Field< Type > &)
void operator= (const tmp< Field< Type > > &)
void operator= (const UList< Type > &rhs)
void operator= (const SubField< Type > &rhs)
template<class Addr >
void operator= (const IndirectListBase< Type, Addr > &rhs)
void operator= (Field< Type > &&rhs)
void operator= (List< Type > &&rhs)
template<int SizeMin>
void operator= (DynamicList< Type, SizeMin > &&rhs)
void operator= (const Type &val)
void operator= (const Foam::zero)
template<class Form , class Cmpt , direction nCmpt>
void operator= (const VectorSpace< Form, Cmpt, nCmpt > &)
void operator+= (const UList< Type > &)
void operator+= (const tmp< Field< Type > > &)
void operator-= (const UList< Type > &)
void operator-= (const tmp< Field< Type > > &)
void operator*= (const UList< scalar > &)
void operator*= (const tmp< Field< scalar > > &)
void operator/= (const UList< scalar > &)
void operator/= (const tmp< Field< scalar > > &)
void operator+= (const Type &)
void operator-= (const Type &)
void operator*= (const scalar &)
void operator/= (const scalar &)
template<class Type >
void operator= (const tmp< Field > &rhs)
void normalise ()
void normalise ()
void normalise ()
void normalise ()
Public Member Functions inherited from FieldBase
constexpr FieldBase () noexcept
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Public Member Functions inherited from List< Type >
constexpr List () noexcept
List (const label len)
List (const label len, const Type &val)
List (const label len, const Foam::zero)
List (const Foam::one, const Type &val)
List (const Foam::one, Type &&val)
List (const Foam::one, const Foam::zero)
List (const List< Type > &a)
List (const UList< Type > &a)
List (List< Type > &a, bool reuse)
List (const UList< Type > &list, const labelUList &indices)
List (const UList< Type > &list, const FixedList< label, N > &indices)
List (const FixedList< Type, N > &list)
List (const PtrList< Type > &list)
List (const SLList< Type > &list)
List (const IndirectListBase< Type, Addr > &list)
List (std::initializer_list< Type > list)
List (List< Type > &&list)
List (DynamicList< Type, SizeMin > &&list)
List (SLList< Type > &&list)
List (Istream &is)
autoPtr< List< Type > > clone () const
~List ()
void clear ()
void resize (const label len)
void resize (const label len, const Type &val)
void resize (const label newLen)
void resize_nocopy (const label len)
void setSize (const label n)
void setSize (const label n, const Type &val)
void transfer (List< Type > &list)
void transfer (DynamicList< Type, SizeMin > &list)
Type & newElmt (const label i)
Type & emplace_back (Args &&... args)
void push_back (const Type &val)
void push_back (Type &&val)
void push_back (const UList< Type > &list)
void push_back (const IndirectListBase< Type, Addr > &list)
label push_uniq (const Type &val)
void pop_back (label n=1)
void operator= (const UList< Type > &a)
void operator= (const List< Type > &list)
void operator= (const SLList< Type > &list)
void operator= (const IndirectListBase< Type, Addr > &list)
void operator= (const FixedList< Type, N > &list)
void operator= (std::initializer_list< Type > list)
void operator= (const Type &val)
void operator= (const Foam::zero)
void operator= (List< Type > &&list)
void operator= (DynamicList< Type, SizeMin > &&list)
void operator= (SLList< Type > &&list)
Istream & readList (Istream &is)
Istream & readList (Istream &is)
Istream & readList (Istream &is)
void shallowCopy (const UList< Type > &)=delete
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type set (const label i, bool val=true)
void append (const Type &val)
void append (Type &&val)
void append (const UList< Type > &list)
void append (const IndirectListBase< Type, Addr > &list)
label appendUniq (const Type &val)
Public Member Functions inherited from UList< T >
UList (const UList< T > &)=default
constexpr UList () noexcept
UList (T *__restrict__ v, const label len) noexcept
label fcIndex (const label i) const noexcept
label rcIndex (const label i) const noexcept
const T & fcValue (const label i) const
T & fcValue (const label i)
const T & rcValue (const label i) const
T & rcValue (const label i)
const T * cdata () const noexcept
T * data () noexcept
const char * cdata_bytes () const noexcept
char * data_bytes () noexcept
T & front ()
const T & front () const
T & back ()
const T & back () const
std::streamsize size_bytes () const noexcept
std::streamsize byteSize () const
void checkStart (const label start) const
void checkSize (const label size) const
void checkRange (const label start, const label len) const
void checkIndex (const label i) const
bool uniform () const
label find (const T &val, label pos=0) const
label rfind (const T &val, label pos=-1) const
bool contains (const T &val, label pos=0) const
void moveFirst (const label i)
void moveLast (const label i)
void swapFirst (const label i)
void swapLast (const label i)
void shallowCopy (const UList< T > &list)
void deepCopy (const UList< T > &list)
template<class Addr >
void deepCopy (const IndirectListBase< T, Addr > &list)
SubList< T > slice (const label pos, label len=-1)
const SubList< T > slice (const label pos, label len=-1) const
SubList< T > slice (const labelRange &range)
const SubList< T > slice (const labelRange &range) const
T & operator[] (const label i)
const T & operator[] (const label i) const
operator const Foam::List< T > & () const
void operator= (const T &val)
void operator= (const Foam::zero)
iterator begin () noexcept
iterator end () noexcept
iterator begin (const label i) noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
const_iterator begin () const noexcept
const_iterator end () const noexcept
const_iterator cbegin (const label i) const noexcept
const_iterator begin (const label i) const noexcept
reverse_iterator rbegin ()
reverse_iterator rend ()
const_reverse_iterator crbegin () const
const_reverse_iterator crend () const
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
bool empty () const noexcept
label size () const noexcept
void swap (UList< T > &list)
bool operator== (const UList< T > &a) const
bool operator!= (const UList< T > &a) const
bool operator< (const UList< T > &list) const
bool operator> (const UList< T > &a) const
bool operator<= (const UList< T > &a) const
bool operator>= (const UList< T > &a) const
Istream & readList (Istream &is)
void writeEntry (const word &keyword, Ostream &os) const
Ostream & writeList (Ostream &os, const label shortLen=0) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type test (const label i) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type get (const label i) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type unset (const label i)
T & first ()
const T & first () const
T & last ()
const T & last () const
bool found (const T &val, label pos=0) const
Istream & readList (Istream &is)
Ostream & writeList (Ostream &os, const label) const
const bool & operator[] (const label i) const
UPstream::commsStruct & operator[] (const label procID)
const UPstream::commsStruct & operator[] (const label procID) const
Foam::UPstream::commsStruct & operator[] (const label procID)
const Foam::UPstream::commsStruct & operator[] (const label procID) const
Ostream & writeList (Ostream &os, const label) const
Istream & readList (Istream &is)
Additional Inherited Members
Public Types inherited from faPatchField< Type >
typedef DimensionedField< Type, areaMesh > Internal
typedef faPatch Patch
typedef calculatedFaPatchField< Type > Calculated
Public Types inherited from Field< Type >
typedef pTraits< Type >::cmptType cmptType
typedef SubField< Type > subField
Public Types inherited from List< Type >
typedef SubList< Type > subList
Public Types inherited from UList< T >
typedef T value_type
typedef T * pointer
typedef const T * const_pointer
typedef T & reference
typedef const T & const_reference
typedef T * iterator
typedef const T * const_iterator
typedef label size_type
typedef label difference_type
typedef std::reverse_iterator< iterator > reverse_iterator
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
Static Public Member Functions inherited from faPatchField< Type >
static tmp< faPatchField< Type > > New (const word &patchFieldType, const word &actualPatchType, const faPatch &, const DimensionedField< Type, areaMesh > &)
static tmp< faPatchField< Type > > New (const word &patchFieldType, const faPatch &, const DimensionedField< Type, areaMesh > &)
static tmp< faPatchField< Type > > New (const faPatchField< Type > &, const faPatch &, const DimensionedField< Type, areaMesh > &, const faPatchFieldMapper &)
static tmp< faPatchField< Type > > New (const faPatch &, const DimensionedField< Type, areaMesh > &, const dictionary &)
template<class AnyType >
static tmp< faPatchField< Type > > NewCalculatedType (const faPatchField< AnyType > &pf)
Static Public Member Functions inherited from faPatchFieldBase
static const word & emptyType () noexcept
static const word & calculatedType () noexcept
static const word & extrapolatedCalculatedType () noexcept
static const word & zeroGradientType () noexcept
Static Public Member Functions inherited from Field< Type >
static const Field< Type > & null ()
static autoPtr< Field< Type > > New (Istream &is)
template<class Type2 >
static tmp< Field< Type > > NewCalculatedType (const Field< Type2 > &f)
Static Public Member Functions inherited from List< Type >
static const List< Type > & null ()
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
static constexpr label max_size () noexcept
Static Public Attributes inherited from faPatchFieldBase
static int disallowGenericPatchField
Static Public Attributes inherited from FieldBase
static const char *const typeName
static bool allowConstructFromLargerSize = false
Protected Member Functions inherited from faPatchField< Type >
bool readValueEntry (const dictionary &dict, IOobjectOption::readOption readOpt=IOobjectOption::LAZY_READ)
void writeValueEntry (Ostream &os) const
void extrapolateInternal ()
Protected Member Functions inherited from faPatchFieldBase
virtual void readDict (const dictionary &dict)
void setUpdated (bool state) noexcept
void setManipulated (bool state) noexcept
Protected Member Functions inherited from UList< T >
void setAddressableSize (const label n) noexcept
void size (const label n)
void writeEntry (Ostream &os) const
labelRange validateRange (const labelRange &requestedRange) const
UList< T > & operator= (const UList< T > &)=delete
void writeEntry (Ostream &os) const
void writeEntry (Ostream &os) const
Detailed Description
template<class Type>
class Foam::timeVaryingUniformFixedValueFaPatchField< Type >
A time-varying form of a uniform fixed value finite area boundary condition.
Usage
Example of the boundary condition specification:
<patchName>
{
    // Mandatory entries (unmodifiable)
    type                timeVaryingUniformFixedValue;
    fileName            "<case>/time-series";
    outOfBounds         clamp;           // (error|warn|clamp|repeat)
    // Mandatory/Optional (inherited) entries
    ...
}
where the entries mean:
Property Description Type Reqd Dflt
type Type name: timeVaryingUniformFixedValue word yes -
fileName Name of operand file word yes -
The inherited entries are elaborated in:
faPatchFields.H
Author Zeljko Tukovic, FMENA Hrvoje Jasak, Wikki Ltd.
Note
This class is derived directly from a fixedValue patch rather than from a uniformFixedValue patch.
See also
Foam::interpolationTable
Foam::fixedValueFaPatchField
Source files
timeVaryingUniformFixedValueFaPatchField.H
timeVaryingUniformFixedValueFaPatchField.C
Definition at line 105 of file timeVaryingUniformFixedValueFaPatchField.H.
Constructor & Destructor Documentation
timeVaryingUniformFixedValueFaPatchField() [1/5]
template<class Type > timeVaryingUniformFixedValueFaPatchField (const faPatch & p, const DimensionedField< Type, areaMesh > & iF)
Definition at line 28 of file timeVaryingUniformFixedValueFaPatchField.C.
timeVaryingUniformFixedValueFaPatchField() [2/5]
template<class Type > timeVaryingUniformFixedValueFaPatchField (const faPatch & p, const DimensionedField< Type, areaMesh > & iF, const dictionary & dict)
Definition at line 41 of file timeVaryingUniformFixedValueFaPatchField.C.
References DeprecatedInFunction, Foam::endl(), faPatchField< Type >::extrapolateInternal(), Foam::nl, faPatchField< Type >::readValueEntry(), and timeVaryingUniformFixedValueFaPatchField< Type >::updateCoeffs().
timeVaryingUniformFixedValueFaPatchField() [3/5]
template<class Type > timeVaryingUniformFixedValueFaPatchField (const timeVaryingUniformFixedValueFaPatchField< Type > & ptf, const faPatch & p, const DimensionedField< Type, areaMesh > & iF, const faPatchFieldMapper & mapper)
Definition at line 67 of file timeVaryingUniformFixedValueFaPatchField.C.
timeVaryingUniformFixedValueFaPatchField() [4/5]
template<class Type > timeVaryingUniformFixedValueFaPatchField (const timeVaryingUniformFixedValueFaPatchField< Type > & ptf)
Definition at line 82 of file timeVaryingUniformFixedValueFaPatchField.C.
timeVaryingUniformFixedValueFaPatchField() [5/5]
template<class Type > timeVaryingUniformFixedValueFaPatchField (const timeVaryingUniformFixedValueFaPatchField< Type > & ptf, const DimensionedField< Type, areaMesh > & iF)
Definition at line 94 of file timeVaryingUniformFixedValueFaPatchField.C.
~timeVaryingUniformFixedValueFaPatchField()
template<class Type > virtual ~timeVaryingUniformFixedValueFaPatchField () virtual default
Member Function Documentation
TypeName()
template<class Type > TypeName ("timeVaryingUniformFixedValue")
clone() [1/2]
template<class Type > virtual tmp< faPatchField< Type > > clone () const inline virtual
Reimplemented from fixedValueFaPatchField< Type >.
Definition at line 154 of file timeVaryingUniformFixedValueFaPatchField.H.
clone() [2/2]
template<class Type > virtual tmp< faPatchField< Type > > clone (const DimensionedField< Type, areaMesh > & iF) const inline virtual
Reimplemented from fixedValueFaPatchField< Type >.
Definition at line 170 of file timeVaryingUniformFixedValueFaPatchField.H.
timeSeries()
template<class Type > const interpolationTable< Type > & timeSeries () const inline
Definition at line 191 of file timeVaryingUniformFixedValueFaPatchField.H.
updateCoeffs()
template<class Type > void updateCoeffs () virtual
Reimplemented from faPatchField< Type >.
Definition at line 109 of file timeVaryingUniformFixedValueFaPatchField.C.
References faPatchField< Type >::updateCoeffs().
Referenced by timeVaryingUniformFixedValueFaPatchField< Type >::timeVaryingUniformFixedValueFaPatchField().
write()
template<class Type > void write (Ostream & os) const virtual
Reimplemented from fixedValueFaPatchField< Type >.
Definition at line 125 of file timeVaryingUniformFixedValueFaPatchField.C.
References os(), faPatchField< Type >::write(), and faPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/finiteArea/fields/faPatchFields/derived/timeVaryingUniformFixedValue/timeVaryingUniformFixedValueFaPatchField.H
src/finiteArea/fields/faPatchFields/derived/timeVaryingUniformFixedValue/timeVaryingUniformFixedValueFaPatchField.C