OpenFOAM: parcelSelection Class Reference
parcelSelection Class Reference
Selection of parcels based on their objectRegistry entries. Normally accessed via a dictionary entry.
#include <parcelSelectionDetail.H>
Public Types
enum actionType {
ALL , CLEAR , INVERT , ADD ,
SUBTRACT , SUBSET , USE , IGNORE
}
enum sourceType { FIELD , STRIDE }
enum logicType { AND , OR }
Public Member Functions
parcelSelection ()=default
virtual ~parcelSelection ()=default
Static Public Attributes
static const Enum< actionType > actionNames
static const Enum< sourceType > sourceNames
static const Enum< logicType > logicNames
Protected Member Functions
bool calculateFilter (const objectRegistry &obrTmp, const bool log=true)
Protected Attributes
dictionary parcelSelect_
bitSet parcelAddr_
Detailed Description
Selection of parcels based on their objectRegistry entries. Normally accessed via a dictionary entry.
Example sub-dictionary entry
selection
{
    stride
    {
        // every 10th parcelId
        action  use;
        source  stride;
        stride  10;
    }
    injector
    {
        // Only output from injectorID == 1
        action  subset;
        source  field;
        field   typeId;
        accept  (equal 1);
    }
    Umin
    {
        // Remove slow parcels
        action  subtract;
        source  field;
        field   U;
        accept  (less 1e-3);
    }
    diam
    {
        // Only particular diameter ranges
        action  subset;
        source  field;
        field   d;
        accept  (greater 1e-5) and (less 1e-3);
    }
}
Entry type
Property Description Required Default
action all/clear/invert/ignore add/subtract/subset/use yes
source field/stride mostly
Stride source
Property Description Required Default
stride The stride for the parcel id yes
Field source
Property Description Required Default
field The label/scalar/vector field name yes
accept Acceptance or test criterion yes
The accept criterion has two forms:
single expression
(expr)
composite expression
(expr) or (expr)
(expr) and (expr)
The expressions are a (op scalar) pair that form a unary scalar predicate. The op is one of the following:
lt, less
le, lessEqual, lessEq
gt, greater
ge, greaterEqual, greaterEq
eq, equal
neq, notEqual
For example,
    accept  (less 10);
    accept  (less 10) or (greater 100);
    accept  (ge 10) and (le 20);
See also
Foam::predicates::scalars Foam::functionObjects::vtkCloud
Source files
parcelSelectionDetail.H
parcelSelectionDetail.C
Definition at line 176 of file parcelSelectionDetail.H.
Member Enumeration Documentation
actionType
enum actionType
Enumerator
ALL
"all" - select all parcels
CLEAR
"clear" - clear the selection
INVERT
"invert" - invert the selection
ADD
"add" - parcel selection
SUBTRACT
"subtract" - remove parcel selection
SUBSET
"subset" - subset parcel selection
USE
"use" - same as clear + add
IGNORE
"ignore" - dummy no-op
Definition at line 181 of file parcelSelectionDetail.H.
sourceType
enum sourceType
Enumerator
FIELD
"field" - select based on field value
STRIDE
"stride" - select based on stride (parcel id)
Definition at line 198 of file parcelSelectionDetail.H.
logicType
enum logicType
Enumerator
AND
OR
Definition at line 209 of file parcelSelectionDetail.H.
Constructor & Destructor Documentation
parcelSelection()
parcelSelection () default
~parcelSelection()
virtual ~parcelSelection () virtual default
Member Function Documentation
calculateFilter()
bool calculateFilter (const objectRegistry & obrTmp, const bool log = true) protected
Definition at line 142 of file parcelSelectionDetail.C.
References parcelSelection::actionNames, parcelSelection::ADD, parcelSelection::ALL, parcelSelection::AND, scalars::andOp(), Foam::apply(), parcelSelection::CLEAR, PackedList< Width >::clear(), dict, e, Foam::endl(), parcelSelection::FIELD, cloud::findIOPosition(), UPtrList< T >::first(), bitSet::flip(), UPtrList< T >::get(), parcelSelection::IGNORE, parcelSelection::INVERT, keyType::LITERAL, Log, parcelSelection::logicNames, Foam::nl, scalars::operation(), parcelSelection::OR, scalars::orOp(), parcelSelection::parcelAddr_, parcelSelection::parcelSelect_, Foam::reduce(), PackedList< Width >::reset(), PackedList< Width >::resize(), UPtrList< T >::size(), parcelSelection::sourceNames, parcelSelection::STRIDE, parcelSelection::SUBTRACT, and WarningInFunction.
Member Data Documentation
actionNames
const Foam::Enum< Foam::Detail::parcelSelection::actionType > actionNames static
Definition at line 194 of file parcelSelectionDetail.H.
Referenced by parcelSelection::calculateFilter().
sourceNames
const Foam::Enum< Foam::Detail::parcelSelection::sourceType > sourceNames static
Definition at line 205 of file parcelSelectionDetail.H.
Referenced by parcelSelection::calculateFilter().
logicNames
const Foam::Enum< Foam::Detail::parcelSelection::logicType > logicNames static
Definition at line 212 of file parcelSelectionDetail.H.
Referenced by parcelSelection::calculateFilter().
parcelSelect_
dictionary parcelSelect_ protected
Definition at line 220 of file parcelSelectionDetail.H.
Referenced by parcelSelection::calculateFilter().
parcelAddr_
bitSet parcelAddr_ protected
Definition at line 223 of file parcelSelectionDetail.H.
Referenced by parcelSelection::calculateFilter(), and vtkCloud::writeFields().
The documentation for this class was generated from the following files:
src/functionObjects/lagrangian/common/parcelSelectionDetail.H
src/functionObjects/lagrangian/common/parcelSelectionDetail.C