OpenFOAM: smoothData Class Reference
smoothData Class Reference
Helper class used by the fvc::smooth and fvc::spread functions.
#include <smoothData.H>
Classes
class trackData
Public Member Functions
smoothData (const smoothData &)=default
smoothData & operator= (const smoothData &)=default
smoothData ()
smoothData (const scalar value)
scalar value () const
scalar & value ()
template<class TrackingData >
bool valid (TrackingData &td) const
template<class TrackingData >
bool sameGeometry (const polyMesh &, const smoothData &, const scalar, TrackingData &td) const
template<class TrackingData >
void leaveDomain (const polyMesh &, const polyPatch &, const label patchFacei, const point &faceCentre, TrackingData &td)
template<class TrackingData >
void enterDomain (const polyMesh &, const polyPatch &, const label patchFacei, const point &faceCentre, TrackingData &td)
template<class TrackingData >
void transform (const polyMesh &, const tensor &, TrackingData &td)
template<class TrackingData >
bool updateCell (const polyMesh &, const label thisCelli, const label neighbourFacei, const smoothData &svf, const scalar tol, TrackingData &td)
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFacei, const label neighbourCelli, const smoothData &svf, const scalar tol, TrackingData &td)
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFacei, const smoothData &svf, const scalar tol, TrackingData &td)
template<class TrackingData >
bool equal (const smoothData &, TrackingData &td) const
void operator= (const scalar value)
bool operator== (const smoothData &) const
bool operator!= (const smoothData &) const
Friends
Ostream & operator<< (Ostream &os, const smoothData &rhs)
Istream & operator>> (Istream &is, smoothData &rhs)
Detailed Description
Helper class used by the fvc::smooth and fvc::spread functions.
Source files
smoothData.H
smoothData.H
smoothDataI.H
Definition at line 52 of file smoothData.H.
Constructor & Destructor Documentation
smoothData() [1/3]
smoothData (const smoothData &) default
smoothData() [2/3]
smoothData () inline
Definition at line 60 of file smoothDataI.H.
smoothData() [3/3]
smoothData (const scalar value) inline
Definition at line 66 of file smoothDataI.H.
Member Function Documentation
operator=() [1/2]
smoothData & operator= (const smoothData &) default
value() [1/2]
scalar value () const inline
Definition at line 108 of file smoothData.H.
Referenced by smoothData::operator=().
value() [2/2]
scalar & value () inline
Definition at line 114 of file smoothData.H.
valid()
template<class TrackingData > bool valid (TrackingData & td) const inline
Definition at line 75 of file smoothDataI.H.
sameGeometry()
template<class TrackingData > bool sameGeometry (const polyMesh & , const smoothData & , const scalar , TrackingData & td) const inline
Definition at line 82 of file smoothDataI.H.
leaveDomain()
template<class TrackingData > void leaveDomain (const polyMesh & , const polyPatch & , const label patchFacei, const point & faceCentre, TrackingData & td) inline
Definition at line 95 of file smoothDataI.H.
enterDomain()
template<class TrackingData > void enterDomain (const polyMesh & , const polyPatch & , const label patchFacei, const point & faceCentre, TrackingData & td) inline
Definition at line 117 of file smoothDataI.H.
transform()
template<class TrackingData > void transform (const polyMesh & , const tensor & , TrackingData & td) inline
Definition at line 107 of file smoothDataI.H.
updateCell()
template<class TrackingData > bool updateCell (const polyMesh & , const label thisCelli, const label neighbourFacei, const smoothData & svf, const scalar tol, TrackingData & td) inline
Definition at line 129 of file smoothDataI.H.
References update().
updateFace() [1/2]
template<class TrackingData > bool updateFace (const polyMesh & , const label thisFacei, const label neighbourCelli, const smoothData & svf, const scalar tol, TrackingData & td) inline
Definition at line 145 of file smoothDataI.H.
References update().
updateFace() [2/2]
template<class TrackingData > bool updateFace (const polyMesh & , const label thisFacei, const smoothData & svf, const scalar tol, TrackingData & td) inline
Definition at line 162 of file smoothDataI.H.
References update().
equal()
template<class TrackingData > bool equal (const smoothData & rhs, TrackingData & td) const inline
Definition at line 177 of file smoothDataI.H.
References Foam::operator==().
operator=() [2/2]
void operator= (const scalar value) inline
Definition at line 211 of file smoothData.H.
References smoothData::value().
operator==()
bool operator== (const smoothData & rhs) const inline
Definition at line 189 of file smoothDataI.H.
operator!=()
bool operator!= (const smoothData & rhs) const inline
Definition at line 198 of file smoothDataI.H.
Friends And Related Symbol Documentation
operator<<
Ostream & operator<< (Ostream & os, const smoothData & rhs) friend
Definition at line 225 of file smoothData.H.
operator>>
Istream & operator>> (Istream & is, smoothData & rhs) friend
Definition at line 230 of file smoothData.H.
The documentation for this class was generated from the following files:
src/finiteVolume/finiteVolume/fvc/fvcSmooth/smoothData.H
src/finiteVolume/finiteVolume/fvc/fvcSmooth/smoothDataI.H