OpenFOAM: deposition Class Reference
deposition Class Reference
Phase transfer model representing change from a dispersed phase to a film as a result of deposition onto a third phase.
#include <deposition.H>
Public Member Functions
TypeName ("deposition")
deposition (const dictionary &dict, const phasePair &pair)
virtual ~deposition ()
virtual tmp< volScalarField > dmdt () const
Public Member Functions inherited from phaseTransferModel
TypeName ("phaseTransferModel")
declareRunTimeSelectionTable (autoPtr, phaseTransferModel, dictionary,(const dictionary &dict, const phasePair &pair),(dict, pair))
phaseTransferModel (const dictionary &dict, const phasePair &pair)
virtual ~phaseTransferModel ()=default
Additional Inherited Members
Static Public Member Functions inherited from phaseTransferModel
static autoPtr< phaseTransferModel > New (const dictionary &dict, const phasePair &pair)
Static Public Attributes inherited from phaseTransferModel
static const dimensionSet dimDmdt
Protected Attributes inherited from phaseTransferModel
const phasePair & pair_
Detailed Description
Phase transfer model representing change from a dispersed phase to a film as a result of deposition onto a third phase.
Source files
deposition.H
deposition.C
Definition at line 52 of file deposition.H.
Constructor & Destructor Documentation
deposition()
deposition (const dictionary & dict, const phasePair & pair)
Definition at line 41 of file deposition.C.
~deposition()
~deposition () virtual
Definition at line 56 of file deposition.C.
Member Function Documentation
TypeName()
TypeName ("deposition")
dmdt()
Foam::tmp< Foam::volScalarField > dmdt () const virtual
Implements phaseTransferModel.
Definition at line 63 of file deposition.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::mag(), and Foam::sign().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/interfacialModels/phaseTransferModels/deposition/deposition.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/interfacialModels/phaseTransferModels/deposition/deposition.C