OpenFOAM: MomentumTransferPhaseSystem< BasePhaseSystem > Class Template Reference
MomentumTransferPhaseSystem< BasePhaseSystem > Class Template Reference
Class which models interfacial momenum transfer between a number of phases. Drag, virtual mass, lift, wall lubrication and turbulent dispersion are all modelled. The explicit contribution from the drag is omitted from the transfer matrices, as this forms part of the solution of the pressure equation.
#include <MomentumTransferPhaseSystem.H>
Public Member Functions
MomentumTransferPhaseSystem (const fvMesh &)
virtual ~MomentumTransferPhaseSystem ()
virtual autoPtr< phaseSystem::momentumTransferTable > momentumTransfer ()
virtual autoPtr< phaseSystem::momentumTransferTable > momentumTransferf ()
virtual PtrList< surfaceScalarField > AFfs () const
virtual PtrList< surfaceScalarField > phiFs (const PtrList< volScalarField > &rAUs)
virtual PtrList< surfaceScalarField > phiFfs (const PtrList< surfaceScalarField > &rAUfs)
virtual PtrList< surfaceScalarField > phiKdPhis (const PtrList< volScalarField > &rAUs) const
virtual PtrList< surfaceScalarField > phiKdPhifs (const PtrList< surfaceScalarField > &rAUfs) const
virtual PtrList< volVectorField > KdUByAs (const PtrList< volScalarField > &rAUs) const
virtual void partialElimination (const PtrList< volScalarField > &rAUs)
virtual void partialEliminationf (const PtrList< surfaceScalarField > &rAUfs)
virtual PtrList< surfaceScalarField > ddtCorrByAs (const PtrList< volScalarField > &rAUs, const bool includeVirtualMass=false) const
virtual const HashPtrTable< surfaceScalarField > & DByAfs () const
virtual bool read ()
Protected Types
typedef HashPtrTable< volScalarField, phasePairKey, phasePairKey::hash > KdTable
typedef HashPtrTable< surfaceScalarField, phasePairKey, phasePairKey::hash > KdfTable
typedef HashPtrTable< volScalarField, phasePairKey, phasePairKey::hash > VmTable
typedef HashPtrTable< surfaceScalarField, phasePairKey, phasePairKey::hash > VmfTable
typedef HashTable< autoPtr< BlendedInterfacialModel< dragModel > >, phasePairKey, phasePairKey::hash > dragModelTable
typedef HashTable< autoPtr< BlendedInterfacialModel< virtualMassModel > >, phasePairKey, phasePairKey::hash > virtualMassModelTable
typedef HashTable< autoPtr< BlendedInterfacialModel< liftModel > >, phasePairKey, phasePairKey::hash > liftModelTable
typedef HashTable< autoPtr< BlendedInterfacialModel< wallLubricationModel > >, phasePairKey, phasePairKey::hash > wallLubricationModelTable
typedef HashTable< autoPtr< BlendedInterfacialModel< turbulentDispersionModel > >, phasePairKey, phasePairKey::hash > turbulentDispersionModelTable
Detailed Description
template<class BasePhaseSystem>
class Foam::MomentumTransferPhaseSystem< BasePhaseSystem >
Class which models interfacial momenum transfer between a number of phases. Drag, virtual mass, lift, wall lubrication and turbulent dispersion are all modelled. The explicit contribution from the drag is omitted from the transfer matrices, as this forms part of the solution of the pressure equation.
Source files
MomentumTransferPhaseSystem.H
MomentumTransferPhaseSystem.C
Definition at line 62 of file MomentumTransferPhaseSystem.H.
Member Typedef Documentation
KdTable
template<class BasePhaseSystem > typedef HashPtrTable< volScalarField, phasePairKey, phasePairKey::hash > KdTable protected
Definition at line 75 of file MomentumTransferPhaseSystem.H.
KdfTable
template<class BasePhaseSystem > typedef HashPtrTable< surfaceScalarField, phasePairKey, phasePairKey::hash > KdfTable protected
Definition at line 82 of file MomentumTransferPhaseSystem.H.
VmTable
template<class BasePhaseSystem > typedef HashPtrTable< volScalarField, phasePairKey, phasePairKey::hash > VmTable protected
Definition at line 89 of file MomentumTransferPhaseSystem.H.
VmfTable
template<class BasePhaseSystem > typedef HashPtrTable< surfaceScalarField, phasePairKey, phasePairKey::hash > VmfTable protected
Definition at line 96 of file MomentumTransferPhaseSystem.H.
dragModelTable
template<class BasePhaseSystem > typedef HashTable< autoPtr<BlendedInterfacialModel<dragModel> >, phasePairKey, phasePairKey::hash > dragModelTable protected
Definition at line 103 of file MomentumTransferPhaseSystem.H.
virtualMassModelTable
template<class BasePhaseSystem > typedef HashTable< autoPtr<BlendedInterfacialModel<virtualMassModel> >, phasePairKey, phasePairKey::hash > virtualMassModelTable protected
Definition at line 110 of file MomentumTransferPhaseSystem.H.
liftModelTable
template<class BasePhaseSystem > typedef HashTable< autoPtr<BlendedInterfacialModel<liftModel> >, phasePairKey, phasePairKey::hash > liftModelTable protected
Definition at line 117 of file MomentumTransferPhaseSystem.H.
wallLubricationModelTable
template<class BasePhaseSystem > typedef HashTable< autoPtr<BlendedInterfacialModel<wallLubricationModel> >, phasePairKey, phasePairKey::hash > wallLubricationModelTable protected
Definition at line 124 of file MomentumTransferPhaseSystem.H.
turbulentDispersionModelTable
template<class BasePhaseSystem > typedef HashTable< autoPtr<BlendedInterfacialModel<turbulentDispersionModel> >, phasePairKey, phasePairKey::hash > turbulentDispersionModelTable protected
Definition at line 131 of file MomentumTransferPhaseSystem.H.
Constructor & Destructor Documentation
MomentumTransferPhaseSystem()
template<class BasePhaseSystem > MomentumTransferPhaseSystem (const fvMesh & mesh)
Definition at line 161 of file MomentumTransferPhaseSystem.C.
References forAllConstIter, IOobject::groupName(), phasePair::name(), and HashPtrTable< T, Key, Hash >::set().
~MomentumTransferPhaseSystem()
template<class BasePhaseSystem > ~MomentumTransferPhaseSystem () virtual
Definition at line 264 of file MomentumTransferPhaseSystem.C.
Member Function Documentation
momentumTransfer()
template<class BasePhaseSystem > Foam::autoPtr< Foam::phaseSystem::momentumTransferTable > momentumTransfer () virtual
Definition at line 273 of file MomentumTransferPhaseSystem.C.
References Foam::fvm::ddt(), Foam::dimMass, Foam::dimTime, Foam::dimVelocity, Foam::fvc::div(), Foam::fvm::div(), phaseModel::DUDt(), forAll, forAllConstIter, phase::name(), phaseModel::otherPhase(), phi, PtrList< T >::set(), Foam::fvm::Sp(), U, and phaseModel::U().
momentumTransferf()
template<class BasePhaseSystem > Foam::autoPtr< Foam::phaseSystem::momentumTransferTable > momentumTransferf () virtual
Definition at line 375 of file MomentumTransferPhaseSystem.C.
References Foam::dimMass, Foam::dimTime, Foam::dimVelocity, Foam::fvc::div(), Foam::fvm::div(), forAll, forAllConstIter, phaseModel::index(), phase::name(), phaseModel::otherPhase(), phasei, PtrList< T >::set(), Foam::fvm::Sp(), U, and phaseModel::U().
AFfs()
template<class BasePhaseSystem > Foam::PtrList< Foam::surfaceScalarField > AFfs () const virtual
Definition at line 451 of file MomentumTransferPhaseSystem.C.
References AFfs(), Foam::byDt(), Foam::dimDensity, Foam::dimTime, fillFields(), forAllConstIter, and Vmf().
phiFs()
template<class BasePhaseSystem > Foam::PtrList< Foam::surfaceScalarField > phiFs (const PtrList< volScalarField > & rAUs) virtual
Definition at line 490 of file MomentumTransferPhaseSystem.C.
References D, Foam::dimDensity, Foam::dimForce, Foam::dimVelocity, F(), fillFields(), Foam::fvc::flux(), forAll, forAllConstIter, Foam::fvc::interpolate(), phasePair::phase1(), phasePair::phase2(), phasei, phiFs(), rAUs, Foam::fvc::snGrad(), and snGradAlpha1().
phiFfs()
template<class BasePhaseSystem > Foam::PtrList< Foam::surfaceScalarField > phiFfs (const PtrList< surfaceScalarField > & rAUfs) virtual
Definition at line 631 of file MomentumTransferPhaseSystem.C.
References Foam::byDt(), D, Foam::dimDensity, Foam::dimForce, Foam::dimVelocity, Ff(), fillFields(), forAll, forAllConstIter, Foam::fvc::interpolate(), MRF, oldTime(), phasePair::phase1(), phasePair::phase2(), phasei, phi, phiFfs(), rAUfs, Foam::fvc::snGrad(), snGradAlpha1(), and Vmf().
phiKdPhis()
template<class BasePhaseSystem > Foam::PtrList< Foam::surfaceScalarField > phiKdPhis (const PtrList< volScalarField > & rAUs) const virtual
Definition at line 794 of file MomentumTransferPhaseSystem.C.
References Foam::dimDensity, Foam::dimForce, Foam::dimVelocity, fillFields(), forAllConstIter, Foam::fvc::interpolate(), MRF, and rAUs.
phiKdPhifs()
template<class BasePhaseSystem > Foam::PtrList< Foam::surfaceScalarField > phiKdPhifs (const PtrList< surfaceScalarField > & rAUfs) const virtual
Definition at line 836 of file MomentumTransferPhaseSystem.C.
References Foam::dimDensity, Foam::dimForce, Foam::dimVelocity, fillFields(), forAllConstIter, MRF, and rAUfs.
KdUByAs()
template<class BasePhaseSystem > Foam::PtrList< Foam::volVectorField > KdUByAs (const PtrList< volScalarField > & rAUs) const virtual
Definition at line 878 of file MomentumTransferPhaseSystem.C.
References Foam::dimVelocity, fillFields(), forAllConstIter, and rAUs.
partialElimination()
template<class BasePhaseSystem > void partialElimination (const PtrList< volScalarField > & rAUs) virtual
Definition at line 1013 of file MomentumTransferPhaseSystem.C.
References Foam::dimless, Foam::endl(), fillFields(), forAll, forAllConstIter, Foam::gMin(), Foam::Info, Foam::fvc::interpolate(), k, phasePair::phase1(), phasePair::phase2(), phasei, phases, rAUs, and PtrList< T >::set().
partialEliminationf()
template<class BasePhaseSystem > void partialEliminationf (const PtrList< surfaceScalarField > & rAUfs) virtual
Definition at line 1144 of file MomentumTransferPhaseSystem.C.
References Foam::dimless, Foam::endl(), fillFields(), forAll, forAllConstIter, Foam::gMin(), Foam::Info, k, phasePair::phase1(), phasePair::phase2(), phasei, phases, rAUfs, and PtrList< T >::set().
ddtCorrByAs()
template<class BasePhaseSystem > Foam::PtrList< Foam::surfaceScalarField > ddtCorrByAs (const PtrList< volScalarField > & rAUs, const bool includeVirtualMass = false) const virtual
Definition at line 914 of file MomentumTransferPhaseSystem.C.
References alpha, Foam::fvc::average(), Foam::byDt(), Foam::fvc::flux(), forAll, forAllConstIter, phaseModel::index(), Foam::fvc::interpolate(), MRF, GeometricField< Type, PatchField, GeoMesh >::oldTime(), phaseModel::otherPhase(), phasei, phaseModel::phi(), Foam::pos0(), rAUs, phase::rho(), PtrList< T >::set(), and phaseModel::U().
DByAfs()
template<class BasePhaseSystem > const Foam::HashPtrTable< Foam::surfaceScalarField > & DByAfs () const virtual
Definition at line 1244 of file MomentumTransferPhaseSystem.C.
read()
template<class BasePhaseSystem > bool read () virtual
Definition at line 1251 of file MomentumTransferPhaseSystem.C.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/PhaseSystems/MomentumTransferPhaseSystem/MomentumTransferPhaseSystem.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/PhaseSystems/MomentumTransferPhaseSystem/MomentumTransferPhaseSystem.C