OpenFOAM: waveMethod Class Reference
waveMethod Class Reference
Direct (one-to-one cell correspondence) mesh-to-mesh interpolation class.
#include <waveMethod.H>
Public Member Functions
TypeName ("wave")
waveMethod (const polyMesh &src, const polyMesh &tgt)
virtual ~waveMethod ()
virtual void calculate (labelListList &srcToTgtAddr, scalarListList &srcToTgtWght, pointListList &srcToTgtVec, labelListList &tgtToSrcAddr, scalarListList &tgtToSrcWght, pointListList &tgtToSrcVec)
Public Member Functions inherited from meshToMeshMethod
TypeName ("meshToMeshMethod")
declareRunTimeSelectionTable (autoPtr, meshToMeshMethod, components,(const polyMesh &src, const polyMesh &tgt),(src, tgt))
meshToMeshMethod (const polyMesh &src, const polyMesh &tgt)
virtual ~meshToMeshMethod ()
const polyMesh & src () const
const polyMesh & tgt () const
scalar V () const
void writeConnectivity (const polyMesh &mesh1, const polyMesh &mesh2, const labelListList &mesh1ToMesh2Addr) const
Static Public Member Functions
static void calculate (const polyMesh &src, const polyMesh &tgt, labelList &srcToTgtAddr)
Static Public Member Functions inherited from meshToMeshMethod
static autoPtr< meshToMeshMethod > New (const word &methodName, const polyMesh &src, const polyMesh &tgt)
Additional Inherited Members
Protected Member Functions inherited from meshToMeshMethod
labelList maskCells () const
virtual bool intersect (const label srcCelli, const label tgtCelli) const
virtual scalar interVol (const label srcCelli, const label tgtCelli) const
virtual Tuple2< scalar, point > interVolAndCentroid (const label srcCellI, const label tgtCellI)
virtual void appendNbrCells (const label tgtCelli, const polyMesh &mesh, const DynamicList< label > &visitedTgtCells, DynamicList< label > &nbrTgtCellIDs) const
virtual bool initialise (labelListList &srcToTgtAddr, scalarListList &srcToTgtWght, labelListList &tgtToTgtAddr, scalarListList &tgtToTgtWght) const
Protected Attributes inherited from meshToMeshMethod
const polyMesh & src_
const polyMesh & tgt_
scalar V_
Static Protected Attributes inherited from meshToMeshMethod
static scalar tolerance_ = 1e-6
Detailed Description
Direct (one-to-one cell correspondence) mesh-to-mesh interpolation class.
Source files
waveMethod.H
waveMethod.C
Definition at line 46 of file waveMethod.H.
Constructor & Destructor Documentation
waveMethod()
waveMethod (const polyMesh & src, const polyMesh & tgt)
Definition at line 152 of file waveMethod.C.
~waveMethod()
~waveMethod () virtual
Definition at line 164 of file waveMethod.C.
Member Function Documentation
TypeName()
TypeName ("wave")
calculate() [1/2]
void calculate (const polyMesh & src, const polyMesh & tgt, labelList & srcToTgtAddr) static
Definition at line 37 of file waveMethod.C.
References PtrList< T >::append(), polyMesh::CELL_TETS, PtrList< T >::clear(), UPtrList< T >::empty(), Foam::endl(), forAll, UPstream::parRun(), Foam::Pout, Foam::returnReduce(), Foam::returnReduceAnd(), PtrList< T >::setSize(), UPtrList< T >::size(), meshToMeshMethod::src(), and meshToMeshMethod::tgt().
Referenced by inverseDistance::markDonors(), and trackingInverseDistance::markDonors().
calculate() [2/2]
void calculate (labelListList & srcToTgtAddr, scalarListList & srcToTgtWght, pointListList & srcToTgtVec, labelListList & tgtToSrcAddr, scalarListList & tgtToSrcWght, pointListList & tgtToSrcVec) virtual
Implements meshToMeshMethod.
Definition at line 170 of file waveMethod.C.
References forAll, PtrList< T >::setSize(), and UPtrList< T >::size().
The documentation for this class was generated from the following files:
src/overset/cellCellStencil/inverseDistance/waveMethod.H
src/overset/cellCellStencil/inverseDistance/waveMethod.C