OpenFOAM: externalPointEdgePoint Class Reference
externalPointEdgePoint Class Reference
Holds information regarding nearest wall point. Used in PointEdgeWave. (so not standard FaceCellWave) To be used in wall distance calculation.
#include <externalPointEdgePoint.H>
Classes
class trackingData
Public Member Functions
externalPointEdgePoint ()
externalPointEdgePoint (const point &, const scalar)
const point & origin () const
scalar distSqr () const
template<class TrackingData >
bool valid (TrackingData &td) const
template<class TrackingData >
bool sameGeometry (const externalPointEdgePoint &, const scalar tol, TrackingData &td) const
template<class TrackingData >
void leaveDomain (const polyPatch &patch, const label patchPointi, const point &pos, TrackingData &td)
template<class TrackingData >
void enterDomain (const polyPatch &patch, const label patchPointi, const point &pos, TrackingData &td)
template<class TrackingData >
void transform (const tensor &rotTensor, TrackingData &td)
template<class TrackingData >
bool updatePoint (const polyMesh &mesh, const label pointi, const label edgeI, const externalPointEdgePoint &edgeInfo, const scalar tol, TrackingData &td)
template<class TrackingData >
bool updatePoint (const polyMesh &mesh, const label pointi, const externalPointEdgePoint &newPointInfo, const scalar tol, TrackingData &td)
template<class TrackingData >
bool updatePoint (const externalPointEdgePoint &newPointInfo, const scalar tol, TrackingData &td)
template<class TrackingData >
bool updateEdge (const polyMesh &mesh, const label edgeI, const label pointi, const externalPointEdgePoint &pointInfo, const scalar tol, TrackingData &td)
template<class TrackingData >
bool equal (const externalPointEdgePoint &, TrackingData &td) const
bool operator== (const externalPointEdgePoint &) const
bool operator!= (const externalPointEdgePoint &) const
Friends
Ostream & operator<< (Ostream &, const externalPointEdgePoint &)
Istream & operator>> (Istream &, externalPointEdgePoint &)
Detailed Description
Holds information regarding nearest wall point. Used in PointEdgeWave. (so not standard FaceCellWave) To be used in wall distance calculation.
Source files
externalPointEdgePoint.H
externalPointEdgePointI.H
externalPointEdgePoint.C
Definition at line 58 of file externalPointEdgePoint.H.
Constructor & Destructor Documentation
externalPointEdgePoint() [1/2]
externalPointEdgePoint () inline
Definition at line 114 of file externalPointEdgePointI.H.
externalPointEdgePoint() [2/2]
externalPointEdgePoint (const point & origin, const scalar distSqr) inline
Definition at line 121 of file externalPointEdgePointI.H.
Member Function Documentation
origin()
const point & origin () const inline
Definition at line 123 of file externalPointEdgePoint.H.
distSqr()
scalar distSqr () const inline
Definition at line 128 of file externalPointEdgePoint.H.
valid()
template<class TrackingData > bool valid (TrackingData & td) const inline
Definition at line 135 of file externalPointEdgePointI.H.
References VectorSpace< Form, Cmpt, Ncmpts >::max.
sameGeometry()
template<class TrackingData > bool sameGeometry (const externalPointEdgePoint & w2, const scalar tol, TrackingData & td) const inline
Definition at line 143 of file externalPointEdgePointI.H.
References Foam::diff(), Foam::mag(), and w2.
leaveDomain()
template<class TrackingData > void leaveDomain (const polyPatch & patch, const label patchPointi, const point & pos, TrackingData & td) inline
Definition at line 171 of file externalPointEdgePointI.H.
enterDomain()
template<class TrackingData > void enterDomain (const polyPatch & patch, const label patchPointi, const point & pos, TrackingData & td) inline
Definition at line 195 of file externalPointEdgePointI.H.
transform()
template<class TrackingData > void transform (const tensor & rotTensor, TrackingData & td) inline
Definition at line 184 of file externalPointEdgePointI.H.
References Foam::transform().
updatePoint() [1/3]
template<class TrackingData > bool updatePoint (const polyMesh & mesh, const label pointi, const label edgeI, const externalPointEdgePoint & edgeInfo, const scalar tol, TrackingData & td) inline
Definition at line 209 of file externalPointEdgePointI.H.
References update().
updatePoint() [2/3]
template<class TrackingData > bool updatePoint (const polyMesh & mesh, const label pointi, const externalPointEdgePoint & newPointInfo, const scalar tol, TrackingData & td) inline
Definition at line 224 of file externalPointEdgePointI.H.
References update().
updatePoint() [3/3]
template<class TrackingData > bool updatePoint (const externalPointEdgePoint & newPointInfo, const scalar tol, TrackingData & td) inline
Definition at line 238 of file externalPointEdgePointI.H.
References update().
updateEdge()
template<class TrackingData > bool updateEdge (const polyMesh & mesh, const label edgeI, const label pointi, const externalPointEdgePoint & pointInfo, const scalar tol, TrackingData & td) inline
Definition at line 250 of file externalPointEdgePointI.H.
References e, primitiveMesh::edges(), mesh, and update().
equal()
template<class TrackingData > bool equal (const externalPointEdgePoint & rhs, TrackingData & td) const inline
Definition at line 266 of file externalPointEdgePointI.H.
References Foam::operator==().
operator==()
bool operator== (const externalPointEdgePoint & rhs) const inline
Definition at line 278 of file externalPointEdgePointI.H.
operator!=()
bool operator!= (const externalPointEdgePoint & rhs) const inline
Definition at line 287 of file externalPointEdgePointI.H.
Friends And Related Symbol Documentation
operator<<
Ostream & operator<< (Ostream & , const externalPointEdgePoint &) friend
operator>>
Istream & operator>> (Istream & , externalPointEdgePoint &) friend
The documentation for this class was generated from the following files:
src/dynamicMesh/pointPatchDist/externalPointEdgePoint.H
src/dynamicMesh/pointPatchDist/externalPointEdgePointI.H