OpenFOAM: NURBSbasis Class Reference
NURBSbasis Class Reference
NURBSbasis function. Used to construct NURBS curves, surfaces and volumes.
#include <NURBSbasis.H>
Public Member Functions
TypeName ("NURBbasis")
NURBSbasis (const label nCPs, const label degree, const scalarField &knots)
NURBSbasis (const label nCPs, const label degree)
NURBSbasis (const dictionary &dict)
NURBSbasis (const NURBSbasis &)
virtual ~NURBSbasis ()=default
scalar basisValue (const label iCP, const label degree, const scalar u) const
scalar basisDerivativeU (const label iCP, const label degree, const scalar u) const
scalar basisDerivativeUU (const label iCP, const label degree, const scalar u) const
bool checkRange (const scalar u, const label CPI, const label degree) const
label insertKnot (const scalar uBar)
const scalarField & knots () const
const label & degree () const
const label & nCPs () const
Detailed Description
NURBSbasis function. Used to construct NURBS curves, surfaces and volumes.
Source files
NURBSbasis.H
NURBSbasis.C
NURBSbasisTemplates.C
NURBSbasisI.H
Definition at line 51 of file NURBSbasis.H.
Constructor & Destructor Documentation
NURBSbasis() [1/4]
NURBSbasis (const label nCPs, const label degree, const scalarField & knots)
Definition at line 76 of file NURBSbasis.C.
NURBSbasis() [2/4]
NURBSbasis (const label nCPs, const label degree)
Definition at line 89 of file NURBSbasis.C.
NURBSbasis() [3/4]
NURBSbasis (const dictionary & dict)
Definition at line 103 of file NURBSbasis.C.
NURBSbasis() [4/4]
NURBSbasis (const NURBSbasis & basis)
Definition at line 116 of file NURBSbasis.C.
References DebugInfo, and Foam::endl().
~NURBSbasis()
virtual ~NURBSbasis () virtual default
Member Function Documentation
TypeName()
TypeName ("NURBbasis")
basisValue()
scalar basisValue (const label iCP, const label degree, const scalar u) const
Definition at line 132 of file NURBSbasis.C.
References NURBSbasis::basisValue(), NURBSbasis::checkRange(), and NURBSbasis::degree().
Referenced by NURBSbasis::basisDerivativeU(), NURBSbasis::basisValue(), NURBS3DSurface::buildSurface(), NURBS3DSurface::surfaceDerivativeCP(), NURBS3DSurface::surfaceDerivativeU(), NURBS3DSurface::surfaceDerivativeUU(), NURBS3DSurface::surfaceDerivativeUV(), NURBS3DSurface::surfaceDerivativeV(), NURBS3DSurface::surfaceDerivativeVV(), NURBS3DSurface::surfaceDerivativeW(), and NURBS3DSurface::surfacePoint().
basisDerivativeU()
scalar basisDerivativeU (const label iCP, const label degree, const scalar u) const
Definition at line 182 of file NURBSbasis.C.
References NURBSbasis::basisDerivativeU(), NURBSbasis::basisValue(), NURBSbasis::checkRange(), and NURBSbasis::degree().
Referenced by NURBSbasis::basisDerivativeU(), NURBSbasis::basisDerivativeUU(), NURBS3DSurface::surfaceDerivativeU(), NURBS3DSurface::surfaceDerivativeUU(), NURBS3DSurface::surfaceDerivativeUV(), NURBS3DSurface::surfaceDerivativeV(), and NURBS3DSurface::surfaceDerivativeVV().
basisDerivativeUU()
scalar basisDerivativeUU (const label iCP, const label degree, const scalar u) const
Definition at line 223 of file NURBSbasis.C.
References NURBSbasis::basisDerivativeU(), NURBSbasis::basisDerivativeUU(), NURBSbasis::checkRange(), and NURBSbasis::degree().
Referenced by NURBSbasis::basisDerivativeUU(), NURBS3DSurface::surfaceDerivativeUU(), and NURBS3DSurface::surfaceDerivativeVV().
checkRange()
bool checkRange (const scalar u, const label CPI, const label degree) const
Definition at line 265 of file NURBSbasis.C.
References NURBSbasis::degree().
Referenced by NURBSbasis::basisDerivativeU(), NURBSbasis::basisDerivativeUU(), NURBSbasis::basisValue(), NURBS3DSurface::checkRangeU(), and NURBS3DSurface::checkRangeV().
insertKnot()
label insertKnot (const scalar uBar)
Definition at line 290 of file NURBSbasis.C.
References UPtrList< T >::size(), UList< T >::size(), and Foam::Zero.
knots()
const Foam::scalarField & knots () const inline
Definition at line 27 of file NURBSbasisI.H.
degree()
const Foam::label & degree () const inline
Definition at line 33 of file NURBSbasisI.H.
Referenced by NURBSbasis::basisDerivativeU(), NURBSbasis::basisDerivativeUU(), NURBSbasis::basisValue(), NURBS3DSurface::buildSurface(), NURBSbasis::checkRange(), NURBS3DSurface::checkRangeU(), NURBS3DSurface::checkRangeUV(), NURBS3DSurface::checkRangeV(), NURBS3DSurface::surfaceDerivativeCP(), NURBS3DSurface::surfaceDerivativeU(), NURBS3DSurface::surfaceDerivativeUU(), NURBS3DSurface::surfaceDerivativeUV(), NURBS3DSurface::surfaceDerivativeV(), NURBS3DSurface::surfaceDerivativeVV(), NURBS3DSurface::surfaceDerivativeW(), and NURBS3DSurface::surfacePoint().
nCPs()
const Foam::label & nCPs () const inline
Definition at line 39 of file NURBSbasisI.H.
Referenced by NURBS3DSurface::buildSurface(), NURBS3DSurface::getBoundaryCPIDs(), NURBS3DSurface::invertU(), NURBS3DSurface::invertUV(), NURBS3DSurface::invertV(), NURBS3DSurface::surfaceDerivativeCP(), NURBS3DSurface::surfaceDerivativeU(), NURBS3DSurface::surfaceDerivativeUU(), NURBS3DSurface::surfaceDerivativeUV(), NURBS3DSurface::surfaceDerivativeV(), NURBS3DSurface::surfaceDerivativeVV(), NURBS3DSurface::surfaceDerivativeW(), NURBS3DSurface::surfacePoint(), and NURBS3DSurface::writeVTK().
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/parameterization/NURBS/NURBSbasis/NURBSbasis.H
src/optimisation/adjointOptimisation/adjoint/parameterization/NURBS/NURBSbasis/NURBSbasis.C
src/optimisation/adjointOptimisation/adjoint/parameterization/NURBS/NURBSbasis/NURBSbasisI.H