OpenFOAM: fvGeometryScheme Class Reference
fvGeometryScheme Class Reference abstract
Abstract base class for geometry calculation schemes.
#include <fvGeometryScheme.H>
Public Member Functions
TypeName ("fvGeometryScheme")
declareRunTimeSelectionTable (tmp, fvGeometryScheme, dict,(const fvMesh &mesh, const dictionary &dict),(mesh, dict))
fvGeometryScheme (const fvMesh &mesh, const dictionary &dict)
virtual ~fvGeometryScheme ()=default
const fvMesh & mesh () const
virtual void movePoints ()
virtual void updateMesh (const mapPolyMesh &mpm)
virtual tmp< surfaceScalarField > weights () const =0
virtual tmp< surfaceScalarField > deltaCoeffs () const =0
virtual tmp< surfaceScalarField > nonOrthDeltaCoeffs () const =0
virtual tmp< surfaceVectorField > nonOrthCorrectionVectors () const =0
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Static Public Member Functions
static tmp< fvGeometryScheme > New (const fvMesh &mesh, const dictionary &dict, const word &defaultScheme)
Protected Member Functions
bool setMeshPhi () const
Protected Attributes
const fvMesh & mesh_
Detailed Description
Abstract base class for geometry calculation schemes.
Source files
fvGeometryScheme.H
fvGeometryScheme.C
Definition at line 52 of file fvGeometryScheme.H.
Constructor & Destructor Documentation
fvGeometryScheme()
fvGeometryScheme (const fvMesh & mesh, const dictionary & dict) inline
Definition at line 103 of file fvGeometryScheme.H.
~fvGeometryScheme()
virtual ~fvGeometryScheme () virtual default
Member Function Documentation
setMeshPhi()
bool setMeshPhi () const protected
Definition at line 37 of file fvGeometryScheme.C.
References Foam::abort(), f(), Foam::FatalError, FatalErrorInFunction, forAll, fvGeometryScheme::mesh_, pp(), UPtrList< T >::size(), and UList< T >::size().
TypeName()
TypeName ("fvGeometryScheme")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (tmp , fvGeometryScheme , dict , (const fvMesh &mesh, const dictionary &dict) , (mesh, dict))
New()
Foam::tmp< Foam::fvGeometryScheme > New (const fvMesh & mesh, const dictionary & dict, const word & defaultScheme) static
Definition at line 95 of file fvGeometryScheme.C.
References DebugInFunction, dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::findEntry(), dictionary::getOrDefault(), keyType::LITERAL, and mesh.
Referenced by parallelFvGeometryScheme::geometry(), and surfaceInterpolation::geometry().
mesh()
const fvMesh & mesh () const inline
Definition at line 127 of file fvGeometryScheme.H.
References fvGeometryScheme::mesh_.
Referenced by stabilisedFvGeometryScheme::makeFaceCentresAndAreas().
movePoints()
void movePoints () virtual
Reimplemented in averageNeighbourFvGeometryScheme, basicFvGeometryScheme, highAspectRatioFvGeometryScheme, parallelFvGeometryScheme, solidBodyFvGeometryScheme, and stabilisedFvGeometryScheme.
Definition at line 131 of file fvGeometryScheme.C.
References primitiveMesh::clearGeom().
Referenced by basicFvGeometryScheme::movePoints(), highAspectRatioFvGeometryScheme::movePoints(), and stabilisedFvGeometryScheme::movePoints().
updateMesh()
void updateMesh (const mapPolyMesh & mpm) virtual
Reimplemented in parallelFvGeometryScheme, and solidBodyFvGeometryScheme.
Definition at line 145 of file fvGeometryScheme.C.
weights()
virtual tmp< surfaceScalarField > weights () const pure virtual
Implemented in basicFvGeometryScheme, and parallelFvGeometryScheme.
deltaCoeffs()
virtual tmp< surfaceScalarField > deltaCoeffs () const pure virtual
Implemented in basicFvGeometryScheme, and parallelFvGeometryScheme.
nonOrthDeltaCoeffs()
virtual tmp< surfaceScalarField > nonOrthDeltaCoeffs () const pure virtual
Implemented in basicFvGeometryScheme, and parallelFvGeometryScheme.
nonOrthCorrectionVectors()
virtual tmp< surfaceVectorField > nonOrthCorrectionVectors () const pure virtual
Implemented in basicFvGeometryScheme, and parallelFvGeometryScheme.
Member Data Documentation
mesh_
const fvMesh& mesh_ protected
Definition at line 70 of file fvGeometryScheme.H.
Referenced by highAspectRatioFvGeometryScheme::calcAspectRatioWeights(), averageNeighbourFvGeometryScheme::clipFaceTet(), fvGeometryScheme::mesh(), and fvGeometryScheme::setMeshPhi().
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/fvGeometryScheme/fvGeometryScheme/fvGeometryScheme.H
src/finiteVolume/fvMesh/fvGeometryScheme/fvGeometryScheme/fvGeometryScheme.C