OpenFOAM: activePressureForceBaffleVelocityFvPatchVectorField Class Reference
activePressureForceBaffleVelocityFvPatchVectorField Class Reference
Boundary conditions » Coupled
This boundary condition is applied to the flow velocity, to simulate the opening or closure of a baffle due to area averaged pressure or force delta, between both sides of the baffle. This is achieved by merging the behaviours of wall and cyclic baffles.
#include <activePressureForceBaffleVelocityFvPatchVectorField.H>
Public Member Functions
TypeName ("activePressureForceBaffleVelocity")
activePressureForceBaffleVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
activePressureForceBaffleVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
activePressureForceBaffleVelocityFvPatchVectorField (const activePressureForceBaffleVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
activePressureForceBaffleVelocityFvPatchVectorField (const activePressureForceBaffleVelocityFvPatchVectorField &)
virtual tmp< fvPatchVectorField > clone () const
activePressureForceBaffleVelocityFvPatchVectorField (const activePressureForceBaffleVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
virtual void autoMap (const fvPatchFieldMapper &)
virtual void rmap (const fvPatchVectorField &, const labelList &)
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
This boundary condition is applied to the flow velocity, to simulate the opening or closure of a baffle due to area averaged pressure or force delta, between both sides of the baffle. This is achieved by merging the behaviours of wall and cyclic baffles.
The baffle joins two mesh regions, where the open fraction determines the interpolation weights applied to each cyclic- and neighbour-patch contribution. This means that this is boundary condition is meant to be used in an extra wall beyond an existing cyclic patch pair.
The baffle is activated when the area weighted pressure difference between master and slave patches is larger then minThresholdValue.
Once the threshold is crossed, the baffle is activated and continues to open or close at a fixed rate using
where
= baffle open fraction [0-1]
= baffle open fraction on previous evaluation
= sign for orientation: 1 to open or -1 to close
= simulation time step
= time taken to open the baffle
The open fraction is then applied to scale the patch areas.
Usage
Property Description Required Default
p Pressure field name no p
cyclicPatch Cyclic patch name yes
openFraction Current open fraction [0-1] yes
openingTime Time taken to open or close the baffle yes
maxOpenFractionDelta max fraction change per timestep yes
minThresholdValue Min absolute pressure or force difference for activation yes
forceBased Force (true) or pressure-based (false) activation yes
opening Baffle is opening (true) or closing (false) yes
Example of the boundary condition specification:
    <patchName>
    {
        type            activePressureForceBaffleVelocity;
        p               p;
        cyclicPatch     cyclic1;
        openFraction    0.2;
        openingTime     5.0;
        maxOpenFractionDelta 0.1;
        minThresholdValue 0.01;
        forceBased      false;
        opening         true;
    }
Source files
activePressureForceBaffleVelocityFvPatchVectorField.H
activePressureForceBaffleVelocityFvPatchVectorField.C
Definition at line 175 of file activePressureForceBaffleVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
activePressureForceBaffleVelocityFvPatchVectorField() [1/5]
activePressureForceBaffleVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Definition at line 30 of file activePressureForceBaffleVelocityFvPatchVectorField.C.
activePressureForceBaffleVelocityFvPatchVectorField() [2/5]
activePressureForceBaffleVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Definition at line 82 of file activePressureForceBaffleVelocityFvPatchVectorField.C.
References dict, fvPatchField< vector >::operator=(), p, and Foam::Zero.
activePressureForceBaffleVelocityFvPatchVectorField() [3/5]
activePressureForceBaffleVelocityFvPatchVectorField (const activePressureForceBaffleVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 55 of file activePressureForceBaffleVelocityFvPatchVectorField.C.
activePressureForceBaffleVelocityFvPatchVectorField() [4/5]
activePressureForceBaffleVelocityFvPatchVectorField (const activePressureForceBaffleVelocityFvPatchVectorField & ptf)
Definition at line 123 of file activePressureForceBaffleVelocityFvPatchVectorField.C.
activePressureForceBaffleVelocityFvPatchVectorField() [5/5]
activePressureForceBaffleVelocityFvPatchVectorField (const activePressureForceBaffleVelocityFvPatchVectorField & ptf, const DimensionedField< vector, volMesh > & iF)
Definition at line 147 of file activePressureForceBaffleVelocityFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("activePressureForceBaffleVelocity")
clone() [1/2]
virtual tmp< fvPatchVectorField > clone () const inline virtual
Definition at line 264 of file activePressureForceBaffleVelocityFvPatchVectorField.H.
clone() [2/2]
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Definition at line 280 of file activePressureForceBaffleVelocityFvPatchVectorField.H.
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Definition at line 174 of file activePressureForceBaffleVelocityFvPatchVectorField.C.
References Foam::endl(), forAll, Foam::Info, Foam::mag(), and mesh.
rmap()
void rmap (const fvPatchVectorField & ptf, const labelList & addr) virtual
Definition at line 212 of file activePressureForceBaffleVelocityFvPatchVectorField.C.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 235 of file activePressureForceBaffleVelocityFvPatchVectorField.C.
References Foam::clamp(), e, Foam::endl(), forAll, Foam::Info, Foam::mag(), UPstream::master(), mesh, Foam::min(), p, Foam::reduce(), and timeIndex.
write()
void write (Ostream & os) const virtual
Definition at line 364 of file activePressureForceBaffleVelocityFvPatchVectorField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntry(), Ostream::writeEntryIfDifferent(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/activePressureForceBaffleVelocity/activePressureForceBaffleVelocityFvPatchVectorField.H
src/finiteVolume/fields/fvPatchFields/derived/activePressureForceBaffleVelocity/activePressureForceBaffleVelocityFvPatchVectorField.C