OpenFOAM: blockDescriptor Class Reference
blockDescriptor Class Reference
Takes the description of the block and the list of curved edges and creates a list of points on edges together with the weighting factors.
#include <blockDescriptor.H>
Public Member Functions
blockDescriptor (const blockDescriptor &)=default
void operator= (const blockDescriptor &)=delete
blockDescriptor (const cellShape &bshape, const pointField &vertices, const blockEdgeList &edges, const blockFaceList &faces, const labelVector &density, const UList< gradingDescriptors > &expand=UList< gradingDescriptors >::null(), const word &zoneName=word::null)
blockDescriptor (const dictionary &dict, const label blockIndex, const pointField &vertices, const blockEdgeList &edges, const blockFaceList &faces, Istream &is)
const pointField & vertices () const noexcept
const blockFaceList & blockFaces () const noexcept
const cellShape & blockShape () const noexcept
const labelVector & density () const noexcept
const List< gradingDescriptors > & grading () const noexcept
const word & zoneName () const noexcept
const FixedList< label, 6 > & curvedFaces () const noexcept
label nCurvedFaces () const noexcept
const point & blockPoint (const label i) const
label facePointLabel (const direction facei, const label i, const label j) const
bool vertex (const label i, const label j, const label k) const
bool edge (const label i, const label j, const label k) const
int edgesPointsWeights (pointField(&edgesPoints)[12], scalarList(&edgesWeights)[12]) const
bool edgePointsWeights (const label edgei, pointField &edgePoints, scalarList &edgeWeights, const label nDiv, const gradingDescriptors &gd=gradingDescriptors()) const
bool edgePointsWeights (const label edgei, pointField &edgePoints, scalarList &edgeWeights) const
bool flatFaceOrEdge (const label i, const label j, const label k) const
FixedList< pointField, 6 > facePoints (const pointField &points) const
void correctFacePoints (FixedList< pointField, 6 > &) const
InfoProxy< blockDescriptor > info () const noexcept
Public Member Functions inherited from ijkMesh
ijkMesh ()
ijkMesh (const labelVector &ijk)
ijkMesh (const label nx, const label ny, const label nz)
label nPoints () const
label nCells () const
label nFaces () const
label nInternalFaces () const
label nBoundaryFaces () const
label nBoundaryFaces (const direction shapeFacei) const
label cellLabel (const label i, const label j, const label k) const
label cellLabel (const labelVector &ijk) const
label pointLabel (const label i, const label j, const label k) const
label pointLabel (const labelVector &ijk) const
hexCell vertLabels (const label i, const label j, const label k) const
hexCell vertLabels (const labelVector &ijk) const
Public Member Functions inherited from ijkAddressing
ijkAddressing ()
ijkAddressing (const labelVector &ijk)
ijkAddressing (const label ni, const label nj, const label nk)
bool empty () const
const labelVector & sizes () const
labelVector & sizes ()
label size () const
const label & size (const vector::components cmpt) const
void clear ()
void reset (const label ni, const label nj, const label nk)
void reset (const labelVector &newSizes)
label index (const label i, const label j, const label k) const
label index (const labelVector &ijk) const
labelVector index (const label idx) const
void checkIndex (const label i, const label j, const label k, const bool allowExtra=false) const
void checkIndex (const labelVector &ijk, const bool allowExtra=false) const
void checkSizes () const
void checkSizes (const labelVector &other) const
void checkSizes (const label nTotal) const
Static Public Member Functions
static void write (Ostream &, const label blocki, const dictionary &)
Detailed Description
Takes the description of the block and the list of curved edges and creates a list of points on edges together with the weighting factors.
For a given block, the correspondence between the ordering of vertex labels and face labels is shown below. For vertex numbering in the sequence 0 to 7 (block, centre): faces 0 (f0) and 1 are left and right, respectively; faces 2 and 3 are front and back; and faces 4 and 5 are bottom and top:
                7 ---- 6
          f5    |\     :\    f3
           |    | 4 ---- 5    \
           |    3.|....2 |     \
           |     \|     \|     f2
          f4      0 ---- 1
  Y  Z
   \ |          f0 ------ f1
    \|
     o--- X
Source files
blockDescriptor.H
blockDescriptor.C
blockDescriptorEdges.C
Definition at line 82 of file blockDescriptor.H.
Constructor & Destructor Documentation
blockDescriptor() [1/3]
blockDescriptor (const blockDescriptor &) default
blockDescriptor() [2/3]
blockDescriptor (const cellShape & bshape, const pointField & vertices, const blockEdgeList & edges, const blockFaceList & faces, const labelVector & density, const UList< gradingDescriptors > & expand = UList<gradingDescriptors>::null(), const word & zoneName = word::null)
Definition at line 189 of file blockDescriptor.C.
References Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
blockDescriptor() [3/3]
blockDescriptor (const dictionary & dict, const label blockIndex, const pointField & vertices, const blockEdgeList & edges, const blockFaceList & faces, Istream & is)
Definition at line 222 of file blockDescriptor.C.
References token::BEGIN_LIST, dict, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::FatalIOError, FatalIOErrorInFunction, token::info(), IOWarningInFunction, token::isPunctuation(), token::isWord(), token::pToken(), ijkAddressing::sizes(), and token::wordToken().
Member Function Documentation
operator=()
void operator= (const blockDescriptor &) delete
vertices()
const Foam::pointField & vertices () const inline noexcept
Definition at line 25 of file blockDescriptorI.H.
blockFaces()
const Foam::blockFaceList & blockFaces () const inline noexcept
Definition at line 32 of file blockDescriptorI.H.
blockShape()
const Foam::cellShape & blockShape () const inline noexcept
Definition at line 39 of file blockDescriptorI.H.
density()
const Foam::labelVector & density () const inline noexcept
Definition at line 46 of file blockDescriptorI.H.
References ijkAddressing::sizes().
Referenced by Foam::faceNij(), Foam::facePoint(), Foam::facePointN(), and Foam::facePointN().
grading()
const Foam::List< Foam::gradingDescriptors > & grading () const inline noexcept
Definition at line 53 of file blockDescriptorI.H.
zoneName()
const Foam::word & zoneName () const inline noexcept
Definition at line 59 of file blockDescriptorI.H.
curvedFaces()
const Foam::FixedList< Foam::label, 6 > & curvedFaces () const inline noexcept
Definition at line 66 of file blockDescriptorI.H.
nCurvedFaces()
Foam::label nCurvedFaces () const inline noexcept
Definition at line 72 of file blockDescriptorI.H.
blockPoint()
const Foam::point & blockPoint (const label i) const inline
Definition at line 78 of file blockDescriptorI.H.
facePointLabel()
Foam::label facePointLabel (const direction facei, const label i, const label j) const inline
Definition at line 84 of file blockDescriptorI.H.
References x, and y.
vertex()
bool vertex (const label i, const label j, const label k) const inline
Definition at line 121 of file blockDescriptorI.H.
References k.
edge()
bool edge (const label i, const label j, const label k) const inline
Definition at line 134 of file blockDescriptorI.H.
References k.
edgesPointsWeights()
int edgesPointsWeights (pointField(&) edgesPoints[12], scalarList(&) edgesWeights[12]) const
Definition at line 121 of file blockDescriptorEdges.C.
References hexCell::modelEdges().
edgePointsWeights() [1/2]
bool edgePointsWeights (const label edgei, pointField & edgePoints, scalarList & edgeWeights, const label nDiv, const gradingDescriptors & gd = gradingDescriptors()) const
Definition at line 146 of file blockDescriptorEdges.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and hexCell::modelEdges().
edgePointsWeights() [2/2]
bool edgePointsWeights (const label edgei, pointField & edgePoints, scalarList & edgeWeights) const
Definition at line 177 of file blockDescriptorEdges.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and hexCell::modelEdges().
flatFaceOrEdge()
bool flatFaceOrEdge (const label i, const label j, const label k) const inline
Definition at line 147 of file blockDescriptorI.H.
References k, x, and y.
facePoints()
Foam::FixedList< Foam::pointField, 6 > facePoints (const pointField & points) const
Definition at line 319 of file blockDescriptor.C.
References k, points, and PtrList< T >::setSize().
correctFacePoints()
void correctFacePoints (FixedList< pointField, 6 > & facePoints) const
Definition at line 374 of file blockDescriptor.C.
References forAll.
write()
void write (Ostream & os, const label blocki, const dictionary & d) static
Definition at line 394 of file blockDescriptor.C.
References dictionary::findDict(), os(), and Foam::blockMeshTools::write().
info()
InfoProxy< blockDescriptor > info () const inline noexcept
Definition at line 269 of file blockDescriptor.H.
The documentation for this class was generated from the following files:
src/mesh/blockMesh/blockDescriptor/blockDescriptor.H
src/mesh/blockMesh/blockDescriptor/blockDescriptor.C
src/mesh/blockMesh/blockDescriptor/blockDescriptorEdges.C
src/mesh/blockMesh/blockDescriptor/blockDescriptorI.H