OpenFOAM: PDRobstacle Class Reference
PDRobstacle Class Reference
Obstacle definitions for PDR.
#include <PDRobstacle.H>
Public Types
enum legacyTypes {
NONE = 0 , CUBOID_1 = 1 , CYLINDER = 2 , LOUVER_BLOWOFF = 5 ,
LOUVRE_BLOWOFF = 5 , CUBOID = 6 , WALL_BEAM = 7 , GRATING = 8 ,
OLD_INLET = 9 , OLD_BLOWOFF = 10 , CIRC_PATCH = 12 , RECT_PATCH = 16 ,
DIAG_BEAM = 22 , IGNITION = 41 , MESH_PLANE = 46 , IGNORE = 200
}
Public Member Functions
scalar dia () const
scalar theta () const
scalar len () const
scalar & dia ()
scalar & theta ()
scalar & len ()
PDRobstacle ()
PDRobstacle (Istream &is)
declareMemberFunctionSelectionTable (void, PDRobstacle, read, dictionary,(PDRobstacle &obs, const dictionary &dict),(obs, dict))
bool read (Istream &is)
void readProperties (const dictionary &dict)
scalar x () const
scalar y () const
scalar z () const
scalar & x ()
scalar & y ()
scalar & z ()
bool isCylinder () const
void clear ()
void scale (const scalar factor)
scalar volume () const
bool tooSmall (const scalar minWidth) const
bool setFromLegacy (const int groupTypeId, const string &buffer, const label lineNo=-1, const word &inputFile=word::null)
volumeType trim (const boundBox &bb)
meshedSurface surface () const
InfoProxy< PDRobstacle > info () const noexcept
Static Public Member Functions
static scalar legacyReadFiles (const fileName &obsFileDir, const wordList &obsFileNames, const boundBox &meshBb, DynamicList< PDRobstacle > &blocks, DynamicList< PDRobstacle > &cylinders)
static scalar readFiles (const fileName &obsFileDir, const wordList &obsFileNames, const boundBox &meshBb, DynamicList< PDRobstacle > &blocks, DynamicList< PDRobstacle > &cylinders)
static bool isCylinder (const label id)
static label addPieces (vtk::surfaceWriter &surfWriter, const UList< PDRobstacle > &list, label pieceId=0)
static void generateVtk (const fileName &outputDir, const UList< PDRobstacle > &obslist, const UList< PDRobstacle > &cyllist)
Public Attributes
label groupId
int typeId
direction orient
scalar sortBias
point pt
vector span
union {
scalar wa
scalar slat_width
scalar blowoff_press
};
union {
scalar wb
scalar blowoff_time
};
scalar vbkge
scalar xbkge
scalar ybkge
scalar zbkge
union {
int blowoff_type
int inlet_dirn
};
string identifier
Static Public Attributes
static constexpr int maxBlowoffPressure = 10
Friends
Istream & operator>> (Istream &is, PDRobstacle &obs)
Detailed Description
Obstacle definitions for PDR.
Source files
PDRobstacle.H
PDRobstacle.C
PDRobstacleIO.C
PDRobstacleRead.C
Definition at line 70 of file PDRobstacle.H.
Member Enumeration Documentation
legacyTypes
enum legacyTypes
Enumerator
NONE
Placeholder.
CUBOID_1
CYLINDER
LOUVER_BLOWOFF
LOUVRE_BLOWOFF
CUBOID
WALL_BEAM
GRATING
OLD_INLET
ignored (old)
OLD_BLOWOFF
ignored (old)
CIRC_PATCH
RECT_PATCH
DIAG_BEAM
IGNITION
ignored (old)
MESH_PLANE
IGNORE
Definition at line 75 of file PDRobstacle.H.
Constructor & Destructor Documentation
PDRobstacle() [1/2]
PDRobstacle ()
PDRobstacle() [2/2]
PDRobstacle (Istream & is) explicit
Member Function Documentation
dia() [1/2]
scalar dia () const inline
Definition at line 126 of file PDRobstacle.H.
References PDRobstacle::span, and Vector< scalar >::X.
theta() [1/2]
scalar theta () const inline
Definition at line 127 of file PDRobstacle.H.
References PDRobstacle::span, and Vector< scalar >::Y.
len() [1/2]
scalar len () const inline
Definition at line 128 of file PDRobstacle.H.
References PDRobstacle::span, and Vector< scalar >::Z.
dia() [2/2]
scalar & dia () inline
Definition at line 130 of file PDRobstacle.H.
References PDRobstacle::span, and Vector< scalar >::X.
theta() [2/2]
scalar & theta () inline
Definition at line 131 of file PDRobstacle.H.
References PDRobstacle::span, and Vector< scalar >::Y.
len() [2/2]
scalar & len () inline
Definition at line 132 of file PDRobstacle.H.
References PDRobstacle::span, and Vector< scalar >::Z.
declareMemberFunctionSelectionTable()
declareMemberFunctionSelectionTable (void , PDRobstacle , read , dictionary , (PDRobstacle &obs, const dictionary &dict) , (obs, dict))
legacyReadFiles()
static scalar legacyReadFiles (const fileName & obsFileDir, const wordList & obsFileNames, const boundBox & meshBb, DynamicList< PDRobstacle > & blocks, DynamicList< PDRobstacle > & cylinders) static
readFiles()
static scalar readFiles (const fileName & obsFileDir, const wordList & obsFileNames, const boundBox & meshBb, DynamicList< PDRobstacle > & blocks, DynamicList< PDRobstacle > & cylinders) static
read()
bool read (Istream & is)
readProperties()
void readProperties (const dictionary & dict)
x() [1/2]
scalar x () const inline
Definition at line 221 of file PDRobstacle.H.
References PDRobstacle::pt, and Vector< Cmpt >::x().
y() [1/2]
scalar y () const inline
Definition at line 222 of file PDRobstacle.H.
References PDRobstacle::pt, and Vector< Cmpt >::y().
z() [1/2]
scalar z () const inline
Definition at line 223 of file PDRobstacle.H.
References PDRobstacle::pt, and Vector< Cmpt >::z().
x() [2/2]
scalar & x () inline
Definition at line 224 of file PDRobstacle.H.
References PDRobstacle::pt, and Vector< Cmpt >::x().
y() [2/2]
scalar & y () inline
Definition at line 225 of file PDRobstacle.H.
References PDRobstacle::pt, and Vector< Cmpt >::y().
z() [2/2]
scalar & z () inline
Definition at line 226 of file PDRobstacle.H.
References PDRobstacle::pt, and Vector< Cmpt >::z().
isCylinder() [1/2]
bool isCylinder (const label id) inline static
Definition at line 23 of file PDRobstacleI.H.
References PDRobstacle::CYLINDER, and PDRobstacle::DIAG_BEAM.
isCylinder() [2/2]
bool isCylinder () const inline
Definition at line 33 of file PDRobstacleI.H.
clear()
void clear ()
scale()
void scale (const scalar factor)
volume()
scalar volume () const
tooSmall()
bool tooSmall (const scalar minWidth) const
setFromLegacy()
bool setFromLegacy (const int groupTypeId, const string & buffer, const label lineNo = -1, const word & inputFile = word::null)
trim()
volumeType trim (const boundBox & bb)
surface()
meshedSurface surface () const
addPieces()
static label addPieces (vtk::surfaceWriter & surfWriter, const UList< PDRobstacle > & list, label pieceId = 0) static
generateVtk()
static void generateVtk (const fileName & outputDir, const UList< PDRobstacle > & obslist, const UList< PDRobstacle > & cyllist) static
info()
InfoProxy< PDRobstacle > info () const inline noexcept
Definition at line 290 of file PDRobstacle.H.
Friends And Related Symbol Documentation
operator>>
Istream & operator>> (Istream & is, PDRobstacle & obs) friend
Member Data Documentation
maxBlowoffPressure
constexpr int maxBlowoffPressure = 10 static constexpr
Definition at line 100 of file PDRobstacle.H.
groupId
label groupId
Definition at line 106 of file PDRobstacle.H.
typeId
int typeId
Definition at line 109 of file PDRobstacle.H.
orient
direction orient
Definition at line 112 of file PDRobstacle.H.
sortBias
scalar sortBias
Definition at line 115 of file PDRobstacle.H.
pt
point pt
Definition at line 119 of file PDRobstacle.H.
Referenced by PDRobstacle::x(), PDRobstacle::x(), PDRobstacle::y(), PDRobstacle::y(), PDRobstacle::z(), and PDRobstacle::z().
span
vector span
Definition at line 122 of file PDRobstacle.H.
Referenced by PDRobstacle::dia(), PDRobstacle::dia(), PDRobstacle::len(), PDRobstacle::len(), PDRobstacle::theta(), and PDRobstacle::theta().
wa
scalar wa
Definition at line 136 of file PDRobstacle.H.
slat_width
scalar slat_width
Definition at line 137 of file PDRobstacle.H.
blowoff_press
scalar blowoff_press
Definition at line 138 of file PDRobstacle.H.
[union]
union { ... }
wb
scalar wb
Definition at line 142 of file PDRobstacle.H.
blowoff_time
scalar blowoff_time
Definition at line 143 of file PDRobstacle.H.
[union]
union { ... }
vbkge
scalar vbkge
Definition at line 145 of file PDRobstacle.H.
xbkge
scalar xbkge
Definition at line 146 of file PDRobstacle.H.
ybkge
scalar ybkge
Definition at line 147 of file PDRobstacle.H.
zbkge
scalar zbkge
Definition at line 148 of file PDRobstacle.H.
blowoff_type
int blowoff_type
Definition at line 152 of file PDRobstacle.H.
inlet_dirn
int inlet_dirn
Definition at line 153 of file PDRobstacle.H.
[union]
union { ... }
identifier
string identifier
Definition at line 156 of file PDRobstacle.H.
The documentation for this class was generated from the following files:
applications/utilities/preProcessing/PDR/pdrFields/obstacles/PDRobstacle.H
applications/utilities/preProcessing/PDR/pdrFields/obstacles/PDRobstacleI.H