OpenFOAM: KinematicSurfaceFilm< CloudType > Class Template Reference
KinematicSurfaceFilm< CloudType > Class Template Reference
Lagrangian particle models » Submodels » Kinematic » Surface film
Kinematic parcel surface film model.
#include <KinematicSurfaceFilm.H>
Public Types
enum class interactionType { absorb , bounce , splashBai }
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Public Member Functions
TypeName ("kinematicSurfaceFilm")
KinematicSurfaceFilm (const dictionary &dict, CloudType &owner, const word &type=typeName, bool initThermo=true)
KinematicSurfaceFilm (const KinematicSurfaceFilm< CloudType > &sfm, bool initThermo=true)
virtual autoPtr< SurfaceFilmModel< CloudType > > clone () const
virtual ~KinematicSurfaceFilm ()=default
template<class filmType >
void absorbInteraction (filmType &, const parcelType &p, const polyPatch &pp, const label facei, const scalar mass, bool &keepParticle)
void bounceInteraction (parcelType &p, const polyPatch &pp, const label facei, bool &keepParticle) const
template<class filmType >
void drySplashInteraction (filmType &, const scalar sigma, const scalar mu, const parcelType &p, const polyPatch &pp, const label facei, bool &keepParticle)
template<class filmType >
void wetSplashInteraction (filmType &, const scalar sigma, const scalar mu, parcelType &p, const polyPatch &pp, const label facei, bool &keepParticle)
template<class filmType >
void splashInteraction (filmType &, const parcelType &p, const polyPatch &pp, const label facei, const scalar mRatio, const scalar We, const scalar Wec, const scalar sigma, bool &keepParticle)
virtual bool transferParcel (parcelType &p, const polyPatch &pp, bool &keepParticle)
virtual void info ()
Public Member Functions inherited from SurfaceFilmModel< CloudType >
TypeName ("surfaceFilmModel")
declareRunTimeSelectionTable (autoPtr, SurfaceFilmModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
SurfaceFilmModel (CloudType &owner)
SurfaceFilmModel (const dictionary &dict, CloudType &owner, const word &type)
SurfaceFilmModel (const SurfaceFilmModel< CloudType > &sfm)
virtual ~SurfaceFilmModel ()=default
const dimensionedVector & g () const noexcept
label nParcelsTransferred () const noexcept
label & nParcelsTransferred () noexcept
label nParcelsInjected () const noexcept
label & nParcelsInjected () noexcept
scalar totalMassTransferred () const noexcept
scalar & totalMassTransferred () noexcept
template<class TrackCloudType >
void inject (TrackCloudType &cloud)
template<class CloudTrackType >
void injectParticles (const label primaryPatchi, const labelUList &injectorCells, CloudTrackType &cloud)
template<class CloudTrackType >
void injectParticles (const UList< labelPair > &patchFaces, CloudTrackType &cloud)
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
virtual ~CloudSubModelBase ()=default
const CloudType & owner () const
virtual bool writeTime () const
virtual fileName localPath () const
CloudType & owner ()
virtual void write (Ostream &os) const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
subModelBase (const subModelBase &smb)
virtual ~subModelBase ()=default
const word & modelName () const
const dictionary & dict () const
const word & baseName () const
const word & modelType () const
const dictionary & coeffDict () const
const dictionary & properties () const
virtual bool defaultCoeffs (const bool printMsg) const
virtual bool active () const
virtual void cacheFields (const bool store)
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
bool getModelDict (const word &entryName, dictionary &dict) const
template<class Type >
bool getModelProperty (const word &entryName, Type &value) const
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Static Public Attributes
static const Enum< interactionType > interactionTypeNames
Protected Types
typedef CloudType::parcelType parcelType
typedef regionModels::areaSurfaceFilmModels::liquidFilmBase areaFilm
typedef regionModels::surfaceFilmModels::surfaceFilmRegionModel regionFilm
Protected Types inherited from SurfaceFilmModel< CloudType >
typedef CloudType::parcelType parcelType
typedef regionModels::areaSurfaceFilmModels::liquidFilmBase areaFilm
typedef regionModels::surfaceFilmModels::surfaceFilmRegionModel regionFilm
Protected Member Functions
vector tangentVector (const vector &v) const
vector splashDirection (const vector &tanVec1, const vector &tanVec2, const vector &nf) const
void init (bool binitThermo)
void initFilmModels ()
virtual void cacheFilmFields (const areaFilm &film)
virtual void cacheFilmFields (const label filmPatchi, const label primaryPatchi, const regionModels::surfaceFilmModels::surfaceFilmRegionModel &)
virtual void setParcelProperties (parcelType &p, const label filmFacei) const
Protected Member Functions inherited from SurfaceFilmModel< CloudType >
template<class TrackCloudType >
void injectParticles (const label primaryPatchi, const labelUList &injectorCells, TrackCloudType &cloud)
template<class TrackCloudType >
void injectParticles (const UList< labelPair > &patchFaces, TrackCloudType &cloud)
Protected Member Functions inherited from subModelBase
bool inLine () const
Protected Attributes
Random & rndGen_
liquidMixtureProperties * thermo_
scalar pRef_
scalar TRef_
regionFilm * filmModel_
UPtrList< areaFilm > areaFilms_
interactionType interactionType_
labelList parcelTypes_
scalar deltaWet_
label splashParcelType_
label parcelsPerSplash_
scalar dMaxSplash_
scalar dMinSplash_
scalar Adry_
scalar Awet_
scalar Cf_
label nParcelsSplashed_
Protected Attributes inherited from SurfaceFilmModel< CloudType >
const dimensionedVector & g_
label ejectedParcelType_
scalar injectionOffset_
scalar minDiameter_
scalarField massParcelPatch_
scalarField diameterParcelPatch_
Field< vector > UFilmPatch_
scalarField rhoFilmPatch_
Field< scalarField > deltaFilmPatch_
label nParcelsTransferred_
label nParcelsInjected_
scalar totalMassTransferred_
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Protected Attributes inherited from subModelBase
const word modelName_
dictionary & properties_
const dictionary dict_
const word baseName_
const word modelType_
const dictionary coeffDict_
Additional Inherited Members
Static Public Member Functions inherited from SurfaceFilmModel< CloudType >
static autoPtr< SurfaceFilmModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Public Attributes inherited from subModelBase
bool log
Detailed Description
template<class CloudType>
class Foam::KinematicSurfaceFilm< CloudType >
Kinematic parcel surface film model.
Responsible for:
injecting parcels from the film model into the cloud, e.g. for dripping
parcel interaction with the film, e.g absorb, bounce, splash
Source files
KinematicSurfaceFilm.H
KinematicSurfaceFilm.C
KinematicSurfaceFilmI.H
Definition at line 71 of file KinematicSurfaceFilm.H.
Member Typedef Documentation
parcelType
template<class CloudType > typedef CloudType::parcelType parcelType protected
Definition at line 96 of file KinematicSurfaceFilm.H.
areaFilm
template<class CloudType > typedef regionModels::areaSurfaceFilmModels::liquidFilmBase areaFilm protected
Definition at line 99 of file KinematicSurfaceFilm.H.
regionFilm
template<class CloudType > typedef regionModels::surfaceFilmModels::surfaceFilmRegionModel regionFilm protected
Definition at line 102 of file KinematicSurfaceFilm.H.
Member Enumeration Documentation
interactionType
template<class CloudType > enum class interactionType strong
Enumerator
absorb
absorb
bounce
bounce
splashBai
Bai splash model.
Definition at line 80 of file KinematicSurfaceFilm.H.
Constructor & Destructor Documentation
KinematicSurfaceFilm() [1/2]
template<class CloudType > KinematicSurfaceFilm (const dictionary & dict, CloudType & owner, const word & type = typeName, bool initThermo = true)
Definition at line 477 of file KinematicSurfaceFilm.C.
References KinematicSurfaceFilm< CloudType >::Adry_, KinematicSurfaceFilm< CloudType >::Awet_, KinematicSurfaceFilm< CloudType >::Cf_, subModelBase::coeffDict(), KinematicSurfaceFilm< CloudType >::deltaWet_, KinematicSurfaceFilm< CloudType >::dMaxSplash_, KinematicSurfaceFilm< CloudType >::dMinSplash_, Foam::endl(), Foam::Info, KinematicSurfaceFilm< CloudType >::init(), KinematicSurfaceFilm< CloudType >::interactionType_, KinematicSurfaceFilm< CloudType >::interactionTypeNames, KinematicSurfaceFilm< CloudType >::parcelsPerSplash_, KinematicSurfaceFilm< CloudType >::splashBai, and KinematicSurfaceFilm< CloudType >::splashParcelType_.
KinematicSurfaceFilm() [2/2]
template<class CloudType > KinematicSurfaceFilm (const KinematicSurfaceFilm< CloudType > & sfm, bool initThermo = true)
Definition at line 527 of file KinematicSurfaceFilm.C.
References KinematicSurfaceFilm< CloudType >::init(), KinematicSurfaceFilm< CloudType >::interactionType_, and KinematicSurfaceFilm< CloudType >::splashBai.
~KinematicSurfaceFilm()
template<class CloudType > virtual ~KinematicSurfaceFilm () virtual default
Member Function Documentation
tangentVector()
template<class CloudType > Foam::vector tangentVector (const vector & v) const protected
Definition at line 48 of file KinematicSurfaceFilm.C.
References Foam::mag(), PtrList< T >::PtrList(), and Foam::Zero.
splashDirection()
template<class CloudType > Foam::vector splashDirection (const vector & tanVec1, const vector & tanVec2, const vector & nf) const protected
Definition at line 68 of file KinematicSurfaceFilm.C.
References alpha, Foam::cos(), Foam::degToRad(), Foam::mag(), Foam::sin(), and Foam::constant::mathematical::twoPi().
init()
template<class CloudType > void init (bool binitThermo) protected
Definition at line 124 of file KinematicSurfaceFilm.C.
Referenced by KinematicSurfaceFilm< CloudType >::KinematicSurfaceFilm(), and KinematicSurfaceFilm< CloudType >::KinematicSurfaceFilm().
initFilmModels()
template<class CloudType > void initFilmModels () protected
Definition at line 93 of file KinematicSurfaceFilm.C.
References mesh, and fvMesh::time().
cacheFilmFields() [1/2]
template<class CloudType > void cacheFilmFields (const areaFilm & film) protected virtual
Reimplemented from SurfaceFilmModel< CloudType >.
Reimplemented in ThermoSurfaceFilm< CloudType >.
Definition at line 750 of file KinematicSurfaceFilm.C.
References SurfaceFilmModel< CloudType >::cacheFilmFields().
Referenced by ThermoSurfaceFilm< CloudType >::cacheFilmFields(), and ThermoSurfaceFilm< CloudType >::cacheFilmFields().
cacheFilmFields() [2/2]
template<class CloudType > void cacheFilmFields (const label filmPatchi, const label primaryPatchi, const regionModels::surfaceFilmModels::surfaceFilmRegionModel & filmModel) protected virtual
Reimplemented from SurfaceFilmModel< CloudType >.
Reimplemented in ThermoSurfaceFilm< CloudType >.
Definition at line 733 of file KinematicSurfaceFilm.C.
References SurfaceFilmModel< CloudType >::cacheFilmFields().
setParcelProperties()
template<class CloudType > void setParcelProperties (parcelType & p, const label filmFacei) const protected virtual
Reimplemented from SurfaceFilmModel< CloudType >.
Reimplemented in ThermoSurfaceFilm< CloudType >.
Definition at line 760 of file KinematicSurfaceFilm.C.
References p, and SurfaceFilmModel< CloudType >::setParcelProperties().
Referenced by ThermoSurfaceFilm< CloudType >::setParcelProperties().
TypeName()
template<class CloudType > TypeName ("kinematicSurfaceFilm")
clone()
template<class CloudType > virtual autoPtr< SurfaceFilmModel< CloudType > > clone () const inline virtual
Implements SurfaceFilmModel< CloudType >.
Reimplemented in ThermoSurfaceFilm< CloudType >.
Definition at line 245 of file KinematicSurfaceFilm.H.
absorbInteraction()
template<class CloudType > template<class filmType > void absorbInteraction (filmType & film, const parcelType & p, const polyPatch & pp, const label facei, const scalar mass, bool & keepParticle)
Definition at line 137 of file KinematicSurfaceFilm.C.
References DebugInfo, Foam::endl(), PrimitivePatch< FaceList, PointField >::faceNormals(), Foam::mag(), p, pp(), and Urel.
bounceInteraction()
template<class CloudType > void bounceInteraction (parcelType & p, const polyPatch & pp, const label facei, bool & keepParticle) const
Definition at line 183 of file KinematicSurfaceFilm.C.
References DebugInfo, Foam::endl(), PrimitivePatch< FaceList, PointField >::faceNormals(), p, pp(), and Urel.
drySplashInteraction()
template<class CloudType > template<class filmType > void drySplashInteraction (filmType & filmModel, const scalar sigma, const scalar mu, const parcelType & p, const polyPatch & pp, const label facei, bool & keepParticle)
Definition at line 211 of file KinematicSurfaceFilm.C.
References DebugInfo, Foam::endl(), PrimitivePatch< FaceList, PointField >::faceNormals(), Foam::magSqr(), mu, p, Foam::pow(), pp(), rho, Foam::sqr(), and Urel.
wetSplashInteraction()
template<class CloudType > template<class filmType > void wetSplashInteraction (filmType & filmModel, const scalar sigma, const scalar mu, parcelType & p, const polyPatch & pp, const label facei, bool & keepParticle)
Definition at line 264 of file KinematicSurfaceFilm.C.
References Foam::acos(), DebugInfo, Foam::endl(), epsilon, PrimitivePatch< FaceList, PointField >::faceNormals(), Foam::mag(), Foam::magSqr(), mu, p, Foam::constant::mathematical::piByTwo(), Foam::pow(), pp(), rho, Foam::sqr(), U, and Urel.
splashInteraction()
template<class CloudType > template<class filmType > void splashInteraction (filmType & filmModel, const parcelType & p, const polyPatch & pp, const label facei, const scalar mRatio, const scalar We, const scalar Wec, const scalar sigma, bool & keepParticle)
Definition at line 336 of file KinematicSurfaceFilm.C.
References fvMesh::C(), Foam::cbrt(), fvMesh::Cf(), Foam::meshTools::constrainDirection(), Foam::exp(), PrimitivePatch< FaceList, PointField >::faceNormals(), forAll, Foam::log(), Foam::mag(), Foam::magSqr(), Foam::max(), mesh, UPstream::myProcNo(), p, Foam::constant::mathematical::pi(), Foam::pow3(), pp(), polyMesh::solutionD(), Foam::sqr(), Foam::sqrt(), Urel, and y.
transferParcel()
template<class CloudType > bool transferParcel (parcelType & p, const polyPatch & pp, bool & keepParticle) virtual
Implements SurfaceFilmModel< CloudType >.
Reimplemented in ThermoSurfaceFilm< CloudType >.
Definition at line 560 of file KinematicSurfaceFilm.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, mu, p, Foam::Pout, pp(), Foam::refCast(), UPtrList< T >::size(), and TRef().
info()
template<class CloudType > void info () virtual
Reimplemented from SurfaceFilmModel< CloudType >.
Reimplemented in ThermoSurfaceFilm< CloudType >.
Definition at line 771 of file KinematicSurfaceFilm.C.
References Foam::endl(), SurfaceFilmModel< CloudType >::info(), Log_, and Foam::returnReduce().
Referenced by ThermoSurfaceFilm< CloudType >::info().
Member Data Documentation
interactionTypeNames
template<class CloudType > const Foam::Enum< typename Foam::KinematicSurfaceFilm< CloudType >::interactionType > interactionTypeNames static
Definition at line 88 of file KinematicSurfaceFilm.H.
Referenced by KinematicSurfaceFilm< CloudType >::KinematicSurfaceFilm().
rndGen_
template<class CloudType > Random& rndGen_ protected
Definition at line 108 of file KinematicSurfaceFilm.H.
thermo_
template<class CloudType > liquidMixtureProperties* thermo_ protected
Definition at line 114 of file KinematicSurfaceFilm.H.
pRef_
template<class CloudType > scalar pRef_ protected
Definition at line 117 of file KinematicSurfaceFilm.H.
TRef_
template<class CloudType > scalar TRef_ protected
Definition at line 120 of file KinematicSurfaceFilm.H.
filmModel_
template<class CloudType > regionFilm* filmModel_ protected
Definition at line 123 of file KinematicSurfaceFilm.H.
areaFilms_
template<class CloudType > UPtrList<areaFilm> areaFilms_ protected
Definition at line 129 of file KinematicSurfaceFilm.H.
interactionType_
template<class CloudType > interactionType interactionType_ protected
Definition at line 135 of file KinematicSurfaceFilm.H.
Referenced by KinematicSurfaceFilm< CloudType >::KinematicSurfaceFilm(), and KinematicSurfaceFilm< CloudType >::KinematicSurfaceFilm().
parcelTypes_
template<class CloudType > labelList parcelTypes_ protected
Definition at line 139 of file KinematicSurfaceFilm.H.
deltaWet_
template<class CloudType > scalar deltaWet_ protected
Definition at line 142 of file KinematicSurfaceFilm.H.
Referenced by KinematicSurfaceFilm< CloudType >::KinematicSurfaceFilm().
splashParcelType_
template<class CloudType > label splashParcelType_ protected
Definition at line 147 of file KinematicSurfaceFilm.H.
Referenced by KinematicSurfaceFilm< CloudType >::KinematicSurfaceFilm().
parcelsPerSplash_
template<class CloudType > label parcelsPerSplash_ protected
Definition at line 150 of file KinematicSurfaceFilm.H.
Referenced by KinematicSurfaceFilm< CloudType >::KinematicSurfaceFilm().
dMaxSplash_
template<class CloudType > scalar dMaxSplash_ protected
Definition at line 154 of file KinematicSurfaceFilm.H.
Referenced by KinematicSurfaceFilm< CloudType >::KinematicSurfaceFilm().
dMinSplash_
template<class CloudType > scalar dMinSplash_ protected
Definition at line 158 of file KinematicSurfaceFilm.H.
Referenced by KinematicSurfaceFilm< CloudType >::KinematicSurfaceFilm().
Adry_
template<class CloudType > scalar Adry_ protected
Definition at line 165 of file KinematicSurfaceFilm.H.
Referenced by KinematicSurfaceFilm< CloudType >::KinematicSurfaceFilm().
Awet_
template<class CloudType > scalar Awet_ protected
Definition at line 169 of file KinematicSurfaceFilm.H.
Referenced by KinematicSurfaceFilm< CloudType >::KinematicSurfaceFilm().
Cf_
template<class CloudType > scalar Cf_ protected
Definition at line 173 of file KinematicSurfaceFilm.H.
Referenced by KinematicSurfaceFilm< CloudType >::KinematicSurfaceFilm().
nParcelsSplashed_
template<class CloudType > label nParcelsSplashed_ protected
Definition at line 176 of file KinematicSurfaceFilm.H.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/Kinematic/SurfaceFilmModel/KinematicSurfaceFilm/KinematicSurfaceFilm.H
src/lagrangian/intermediate/submodels/Kinematic/SurfaceFilmModel/KinematicSurfaceFilm/KinematicSurfaceFilm.C