OpenFOAM: SpalartAllmarasIDDES< BasicTurbulenceModel > Class Template Reference
SpalartAllmarasIDDES< BasicTurbulenceModel > Class Template Reference
Turbulence models » DES turbulence
SpalartAllmaras IDDES turbulence model for incompressible and compressible flows.
#include <SpalartAllmarasIDDES.H>
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from SpalartAllmarasDES< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("SpalartAllmarasIDDES")
SpalartAllmarasIDDES (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
virtual ~SpalartAllmarasIDDES ()=default
virtual bool read ()
virtual tmp< volScalarField > fd () const
Public Member Functions inherited from SpalartAllmarasDES< BasicTurbulenceModel >
TypeName ("SpalartAllmarasDES")
SpalartAllmarasDES (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
virtual ~SpalartAllmarasDES ()=default
virtual tmp< volScalarField > LESRegion () const
Protected Member Functions
virtual tmp< volScalarField > dTilda (const volScalarField &chi, const volScalarField &fv1, const volTensorField &gradU) const
Protected Member Functions inherited from SpalartAllmarasDES< BasicTurbulenceModel >
virtual tmp< volScalarField > psi (const volScalarField &chi, const volScalarField &fv1) const
virtual tmp< volScalarField > lengthScaleLES (const volScalarField &chi, const volScalarField &fv1) const
virtual tmp< volScalarField > Stilda (const volScalarField &chi, const volScalarField &fv1, const volTensorField &gradU, const volScalarField &dTilda) const
virtual void correctNut ()
Protected Attributes
dimensionedScalar Cdt1_
dimensionedScalar Cdt2_
dimensionedScalar Cl_
dimensionedScalar Ct_
Switch fe_
const IDDESDelta & IDDESDelta_
Protected Attributes inherited from SpalartAllmarasDES< BasicTurbulenceModel >
Switch useSigma_
dimensionedScalar CDES_
Switch lowReCorrection_
dimensionedScalar fwStar_
Detailed Description
template<class BasicTurbulenceModel>
class Foam::LESModels::SpalartAllmarasIDDES< BasicTurbulenceModel >
SpalartAllmaras IDDES turbulence model for incompressible and compressible flows.
Reference:
    Shur, M. L., Spalart, P. R., Strelets, M. K., & Travin, A. K. (2008).
    A hybrid RANS-LES approach with delayed-DES
    and wall-modelled LES capabilities.
    International journal of heat and fluid flow, 29(6), 1638-1649.
    DOI:10.1016/j.ijheatfluidflow.2008.07.001
Source files
SpalartAllmarasIDDES.H
SpalartAllmarasIDDES.C
Definition at line 64 of file SpalartAllmarasIDDES.H.
Member Typedef Documentation
alphaField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 119 of file SpalartAllmarasIDDES.H.
rhoField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 120 of file SpalartAllmarasIDDES.H.
transportModel
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 121 of file SpalartAllmarasIDDES.H.
Constructor & Destructor Documentation
SpalartAllmarasIDDES()
template<class BasicTurbulenceModel > SpalartAllmarasIDDES (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Definition at line 134 of file SpalartAllmarasIDDES.C.
References Foam::type().
~SpalartAllmarasIDDES()
template<class BasicTurbulenceModel > virtual ~SpalartAllmarasIDDES () virtual default
Member Function Documentation
dTilda()
template<class BasicTurbulenceModel > tmp< volScalarField > dTilda (const volScalarField & chi, const volScalarField & fv1, const volTensorField & gradU) const protected virtual
Reimplemented from SpalartAllmarasDES< BasicTurbulenceModel >.
Definition at line 87 of file SpalartAllmarasIDDES.C.
References alpha, delta, Foam::dimLength, Foam::exp(), Foam::lerp(), Foam::mag(), Foam::max(), Foam::min(), Foam::pos0(), Foam::pow(), psi, and Foam::sqr().
TypeName()
template<class BasicTurbulenceModel > TypeName ("SpalartAllmarasIDDES< BasicTurbulenceModel >")
read()
template<class BasicTurbulenceModel > bool read () virtual
Reimplemented from SpalartAllmarasDES< BasicTurbulenceModel >.
Definition at line 216 of file SpalartAllmarasIDDES.C.
fd()
template<class BasicTurbulenceModel > tmp< volScalarField > fd () const virtual
Definition at line 233 of file SpalartAllmarasIDDES.C.
References alpha, Foam::exp(), Foam::fvc::grad(), Foam::mag(), Foam::max(), Foam::min(), Foam::pow(), and Foam::sqr().
Member Data Documentation
Cdt1_
template<class BasicTurbulenceModel > dimensionedScalar Cdt1_ protected
Definition at line 95 of file SpalartAllmarasIDDES.H.
Cdt2_
template<class BasicTurbulenceModel > dimensionedScalar Cdt2_ protected
Definition at line 96 of file SpalartAllmarasIDDES.H.
Cl_
template<class BasicTurbulenceModel > dimensionedScalar Cl_ protected
Definition at line 97 of file SpalartAllmarasIDDES.H.
Ct_
template<class BasicTurbulenceModel > dimensionedScalar Ct_ protected
Definition at line 98 of file SpalartAllmarasIDDES.H.
fe_
template<class BasicTurbulenceModel > Switch fe_ protected
Definition at line 99 of file SpalartAllmarasIDDES.H.
IDDESDelta_
template<class BasicTurbulenceModel > const IDDESDelta& IDDESDelta_ protected
Definition at line 103 of file SpalartAllmarasIDDES.H.
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/DES/SpalartAllmarasIDDES/SpalartAllmarasIDDES.H
src/TurbulenceModels/turbulenceModels/DES/SpalartAllmarasIDDES/SpalartAllmarasIDDES.C