OpenFOAM: alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField Class Reference
alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField Class Reference
This boundary condition provides a thermal wall function for turbulent thermal diffusivity (usuallyalphat) based on the Jayatilleke model for the Eulerian multiphase solvers.
#include <alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField.H>
Public Member Functions
TypeName ("compressible::alphatPhaseChangeJayatillekeWallFunction")
alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField (const alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField (const alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField (const alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Public Member Functions inherited from alphatPhaseChangeWallFunctionFvPatchScalarField
TypeName ("compressible::alphatPhaseChangeWallFunction")
alphatPhaseChangeWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
alphatPhaseChangeWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
alphatPhaseChangeWallFunctionFvPatchScalarField (const alphatPhaseChangeWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
alphatPhaseChangeWallFunctionFvPatchScalarField (const alphatPhaseChangeWallFunctionFvPatchScalarField &)
alphatPhaseChangeWallFunctionFvPatchScalarField (const alphatPhaseChangeWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual const scalarField & dmdt () const
virtual const scalarField & mDotL () const
virtual bool activePhasePair (const phasePairKey &) const
virtual const scalarField & dmdt (const phasePairKey &) const
virtual const scalarField & mDotL (const phasePairKey &) const
virtual scalarField dmdt (const word &) const
virtual scalarField mDotL (const word &) const
Protected Member Functions
void checkType ()
tmp< scalarField > Psmooth (const scalarField &Prat) const
tmp< scalarField > yPlusTherm (const scalarField &P, const scalarField &Prat) const
tmp< scalarField > calcAlphat (const scalarField &prevAlphat) const
Protected Attributes
scalar Prt_
scalar Cmu_
scalar kappa_
scalar E_
Protected Attributes inherited from alphatPhaseChangeWallFunctionFvPatchScalarField
scalarField dmdt_
scalarField mDotL_
Static Protected Attributes
static scalar tolerance_ = 0.01
static label maxIters_ = 10
Detailed Description
This boundary condition provides a thermal wall function for turbulent thermal diffusivity (usuallyalphat) based on the Jayatilleke model for the Eulerian multiphase solvers.
Usage
Example of the boundary condition specification:
<patchName>
{
    // Mandatory entries
    type            alphatPhaseChangeJayatillekeWallFunction;
    // Optional entries
    Prt             <scalar>;
    Cmu             <scalar>;
    kappa           <scalar>;
    E               <scalar>;
    // Inherited entries
    ...
}
where the entries mean:
Property Description Type Reqd Deflt
type
Type name:
compressible::alphatPhaseChangeJayatillekeWallFunction
word yes -
Prt Turbulent Prandtl number scalar no 0.85
Cmu Empirical model coefficient scalar no 0.09
kappa Von Karman constant scalar no 0.41
E Wall roughness parameter scalar no 9.8
The inherited entries are elaborated in:
alphatPhaseChangeWallFunctionFvPatchScalarField.H
See also
Foam::compressible::alphatPhaseChangeWallFunctionFvPatchScalarField
Source files
alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField.H
alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField.C
Definition at line 128 of file alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField.H.
Constructor & Destructor Documentation
alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField() [1/5]
alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 214 of file alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField.C.
References alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField::checkType().
alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField() [2/5]
alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 231 of file alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField.C.
alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField() [3/5]
alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField (const alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 247 of file alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField.C.
alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField() [4/5]
alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField (const alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField & awfpsf)
Definition at line 264 of file alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField.C.
alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField() [5/5]
alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField (const alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField & awfpsf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 278 of file alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField.C.
Member Function Documentation
checkType()
void checkType () protected
Definition at line 48 of file alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and Foam::nl.
Referenced by alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField::alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField(), and alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField::alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField().
Psmooth()
tmp< scalarField > Psmooth (const scalarField & Prat) const protected
Definition at line 61 of file alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField.C.
References Foam::exp(), and Foam::pow().
Referenced by alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField::calcAlphat(), and alphatWallBoilingWallFunctionFvPatchScalarField::updateCoeffs().
yPlusTherm()
tmp< scalarField > yPlusTherm (const scalarField & P, const scalarField & Prat) const protected
Definition at line 71 of file alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField.C.
References alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField::E_, f(), forAll, alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField::kappa_, Foam::log(), Foam::mag(), alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField::maxIters_, tmp< T >::New(), and alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField::tolerance_.
Referenced by alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField::calcAlphat(), and alphatWallBoilingWallFunctionFvPatchScalarField::updateCoeffs().
calcAlphat()
tmp< scalarField > calcAlphat (const scalarField & prevAlphat) const protected
Definition at line 112 of file alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField.C.
References A, alphaEff(), B, GeometricField< Type, PatchField, GeoMesh >::boundaryField(), alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField::Cmu_, alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField::E_, fluid, forAll, IOobject::groupName(), k, alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField::kappa_, Foam::log(), Foam::mag(), magUp, Foam::max(), phase::name(), tmp< T >::New(), fvPatchField< Type >::patchInternalField(), Foam::pow025(), Pr(), turbulenceModel::propertiesName, alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField::Prt_, alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField::Psmooth(), fvPatchField< Type >::snGrad(), Foam::sqr(), Foam::sqrt(), uTau, y, yPlus, and alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField::yPlusTherm().
Referenced by alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField::updateCoeffs(), alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField::updateCoeffs(), and alphatWallBoilingWallFunctionFvPatchScalarField::updateCoeffs().
TypeName()
TypeName ("compressible::alphatPhaseChangeJayatillekeWallFunction")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Reimplemented in alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField, and alphatWallBoilingWallFunctionFvPatchScalarField.
Definition at line 220 of file alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Reimplemented in alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField, and alphatWallBoilingWallFunctionFvPatchScalarField.
Definition at line 239 of file alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField.H.
updateCoeffs()
void updateCoeffs () virtual
Implements alphatPhaseChangeWallFunctionFvPatchScalarField.
Reimplemented in alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField, and alphatWallBoilingWallFunctionFvPatchScalarField.
Definition at line 295 of file alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField.C.
References alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField::calcAlphat(), and Foam::operator==().
write()
void write (Ostream & os) const virtual
Reimplemented from alphatPhaseChangeWallFunctionFvPatchScalarField.
Reimplemented in alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField, and alphatWallBoilingWallFunctionFvPatchScalarField.
Definition at line 308 of file alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField.C.
References alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField::Cmu_, alphatPhaseChangeWallFunctionFvPatchScalarField::dmdt_, alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField::E_, alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField::kappa_, os(), alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField::Prt_, fvPatchField< Type >::write(), Field< Type >::writeEntry(), and fvPatchField< Type >::writeValueEntry().
Member Data Documentation
Prt_
scalar Prt_ protected
Definition at line 137 of file alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField.H.
Referenced by alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField::calcAlphat(), alphatWallBoilingWallFunctionFvPatchScalarField::updateCoeffs(), and alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField::write().
Cmu_
scalar Cmu_ protected
Definition at line 140 of file alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField.H.
Referenced by alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField::calcAlphat(), alphatWallBoilingWallFunctionFvPatchScalarField::updateCoeffs(), and alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField::write().
kappa_
scalar kappa_ protected
Definition at line 143 of file alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField.H.
Referenced by alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField::calcAlphat(), alphatWallBoilingWallFunctionFvPatchScalarField::updateCoeffs(), alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField::write(), and alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField::yPlusTherm().
E_
scalar E_ protected
Definition at line 146 of file alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField.H.
Referenced by alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField::calcAlphat(), alphatWallBoilingWallFunctionFvPatchScalarField::updateCoeffs(), alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField::write(), and alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField::yPlusTherm().
tolerance_
scalar tolerance_ = 0.01 static protected
Definition at line 151 of file alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField.H.
Referenced by alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField::yPlusTherm().
maxIters_
label maxIters_ = 10 static protected
Definition at line 154 of file alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField.H.
Referenced by alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField::yPlusTherm().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/alphatPhaseChangeJayatillekeWallFunction/alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/alphatPhaseChangeJayatillekeWallFunction/alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField.C