OpenFOAM: faPatchData Class Reference
faPatchData Class Reference
Helper class for holding data during faPatch construction. Most data members are exposed at the moment.
#include <faPatchData.H>
Public Member Functions
faPatchData ()
const word & name () const noexcept
dictionary dict (const bool withEdgeLabels=true) const
bool good () const
void clear ()
void assign (const faPatch &fap)
bool assign_coupled (int ownProci, int neiProci)
bool coupled () const noexcept
bool owner () const noexcept
bool neighbour () const noexcept
int matchPatchPair (const labelPair &patchPair) const noexcept
int comparePatchPair (const labelPair &patchPair) const noexcept
Public Attributes
word name_
word type_
label ownerPolyPatchId_
label neighPolyPatchId_
int ownerProcId_
int neighProcId_
labelList edgeLabels_
Detailed Description
Helper class for holding data during faPatch construction. Most data members are exposed at the moment.
Definition at line 48 of file faPatchData.H.
Constructor & Destructor Documentation
faPatchData()
faPatchData ()
Definition at line 28 of file faPatchData.C.
Member Function Documentation
name()
const Foam::word & name () const noexcept
Definition at line 39 of file faPatchData.C.
dict()
Foam::dictionary dict (const bool withEdgeLabels = true) const
Definition at line 45 of file faPatchData.C.
References coupled().
good()
bool good () const
Definition at line 70 of file faPatchData.C.
clear()
void clear ()
Definition at line 76 of file faPatchData.C.
References PtrList< T >::clear().
assign()
void assign (const faPatch & fap)
Definition at line 91 of file faPatchData.C.
References clear().
assign_coupled()
bool assign_coupled (int ownProci, int neiProci)
Definition at line 111 of file faPatchData.C.
References clear(), and processorPolyPatch::newName().
coupled()
bool coupled () const inline noexcept
Definition at line 101 of file faPatchData.H.
References faPatchData::neighProcId_, and faPatchData::ownerProcId_.
owner()
bool owner () const inline noexcept
Definition at line 107 of file faPatchData.H.
References faPatchData::neighProcId_, and faPatchData::ownerProcId_.
Referenced by faPatchData::neighbour().
neighbour()
bool neighbour () const inline noexcept
Definition at line 113 of file faPatchData.H.
References faPatchData::owner().
matchPatchPair()
int matchPatchPair (const labelPair & patchPair) const noexcept
Definition at line 129 of file faPatchData.C.
References UPtrList< T >::first().
comparePatchPair()
int comparePatchPair (const labelPair & patchPair) const noexcept
Definition at line 147 of file faPatchData.C.
References UPtrList< T >::first().
Member Data Documentation
name_
word name_
Definition at line 54 of file faPatchData.H.
type_
word type_
Definition at line 55 of file faPatchData.H.
ownerPolyPatchId_
label ownerPolyPatchId_
Definition at line 57 of file faPatchData.H.
neighPolyPatchId_
label neighPolyPatchId_
Definition at line 58 of file faPatchData.H.
ownerProcId_
int ownerProcId_
Definition at line 61 of file faPatchData.H.
Referenced by faPatchData::coupled(), and faPatchData::owner().
neighProcId_
int neighProcId_
Definition at line 62 of file faPatchData.H.
Referenced by faPatchData::coupled(), and faPatchData::owner().
edgeLabels_
labelList edgeLabels_
Definition at line 65 of file faPatchData.H.
The documentation for this class was generated from the following files:
src/finiteArea/faMesh/faPatches/faPatch/faPatchData.H
src/finiteArea/faMesh/faPatches/faPatch/faPatchData.C