OpenFOAM: ConeInjection< CloudType > Class Template Reference
ConeInjection< CloudType > Class Template Reference
Lagrangian particle models » Submodels » Kinematic » Injection
Multi-point cone injection model.
#include <ConeInjection.H>
Public Member Functions
TypeName ("coneInjection")
ConeInjection (const dictionary &dict, CloudType &owner, const word &modelName)
ConeInjection (const ConeInjection< CloudType > &im)
virtual autoPtr< InjectionModel< CloudType > > clone () const
virtual ~ConeInjection ()=default
virtual void updateMesh ()
scalar timeEnd () const
virtual label parcelsToInject (const scalar time0, const scalar time1)
virtual scalar volumeToInject (const scalar time0, const scalar time1)
virtual void setPositionAndCell (const label parcelI, const label nParcels, const scalar time, vector &position, label &cellOwner, label &tetFacei, label &tetPti)
virtual void setProperties (const label parcelI, const label nParcels, const scalar time, typename CloudType::parcelType &parcel)
virtual bool fullyDescribed () const
virtual bool validInjection (const label parcelI)
Public Member Functions inherited from InjectionModel< CloudType >
TypeName ("injectionModel")
declareRunTimeSelectionTable (autoPtr, InjectionModel, dictionary,(const dictionary &dict, CloudType &owner, const word &modelType),(dict, owner, modelType))
InjectionModel (CloudType &owner)
InjectionModel (const dictionary &dict, CloudType &owner, const word &modelName, const word &modelType)
InjectionModel (const InjectionModel< CloudType > &im)
virtual ~InjectionModel ()=default
scalar timeStart () const
scalar volumeTotal () const
scalar massTotal () const
scalar massInjected () const
label injectorID () const
virtual scalar averageParcelMass ()
label nInjections () const
label parcelsAddedTotal () const
template<class TrackCloudType >
void inject (TrackCloudType &cloud, typename CloudType::parcelType::trackingData &td)
template<class TrackCloudType >
void injectSteadyState (TrackCloudType &cloud, typename CloudType::parcelType::trackingData &td, const scalar trackTime)
virtual void info ()
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
virtual ~CloudSubModelBase ()=default
const CloudType & owner () const
virtual bool writeTime () const
virtual fileName localPath () const
CloudType & owner ()
virtual void write (Ostream &os) const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
subModelBase (const subModelBase &smb)
virtual ~subModelBase ()=default
const word & modelName () const
const dictionary & dict () const
const word & baseName () const
const word & modelType () const
const dictionary & coeffDict () const
const dictionary & properties () const
virtual bool defaultCoeffs (const bool printMsg) const
virtual bool active () const
virtual void cacheFields (const bool store)
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
bool getModelDict (const word &entryName, dictionary &dict) const
template<class Type >
bool getModelProperty (const word &entryName, Type &value) const
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Additional Inherited Members
Public Types inherited from InjectionModel< CloudType >
enum parcelBasis { pbNumber , pbMass , pbFixed }
typedef CloudType::parcelType parcelType
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Static Public Member Functions inherited from InjectionModel< CloudType >
static autoPtr< InjectionModel< CloudType > > New (const dictionary &dict, CloudType &owner)
static autoPtr< InjectionModel< CloudType > > New (const dictionary &dict, const word &modelName, const word &modelType, CloudType &owner)
Public Attributes inherited from subModelBase
bool log
Protected Member Functions inherited from InjectionModel< CloudType >
virtual bool prepareForNextTimeStep (const scalar time, label &newParcels, scalar &newVolumeFraction)
virtual bool findCellAtPosition (label &celli, label &tetFacei, label &tetPti, vector &position, bool errorOnNotFound=true)
virtual scalar setNumberOfParticles (const label parcels, const scalar volumeFraction, const scalar diameter, const scalar rho)
virtual void postInjectCheck (const label parcelsAdded, const scalar massAdded)
Protected Member Functions inherited from subModelBase
bool inLine () const
Protected Attributes inherited from InjectionModel< CloudType >
scalar SOI_
scalar volumeTotal_
scalar massTotal_
autoPtr< Function1< scalar > > massFlowRate_
scalar massInjected_
label nInjections_
label parcelsAddedTotal_
parcelBasis parcelBasis_
scalar nParticleFixed_
scalar time0_
scalar timeStep0_
scalar minParticlesPerParcel_
scalar delayedVolume_
label injectorID_
bool ignoreOutOfBounds_
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Protected Attributes inherited from subModelBase
const word modelName_
dictionary & properties_
const dictionary dict_
const word baseName_
const word modelType_
const dictionary coeffDict_
Detailed Description
template<class CloudType>
class Foam::ConeInjection< CloudType >
Multi-point cone injection model.
User specifies:
time of start of injection
list of injector positions and directions (along injection axes)
number of parcels to inject per injector
parcel velocities
inner and outer half-cone angles
Properties:
Parcel diameters obtained by distribution model
Source files
ConeInjection.H
ConeInjection.C
Definition at line 64 of file ConeInjection.H.
Constructor & Destructor Documentation
ConeInjection() [1/2]
template<class CloudType > ConeInjection (const dictionary & dict, CloudType & owner, const word & modelName)
Definition at line 32 of file ConeInjection.C.
References forAll, Foam::identity(), Foam::mag(), Foam::New(), Vector< Cmpt >::normalise(), CloudSubModelBase< CloudType >::owner(), List< T >::setSize(), UPtrList< T >::size(), ConeInjection< CloudType >::updateMesh(), TimeState::userTimeToTime(), InjectionModel< CloudType >::volumeTotal_, and Foam::Zero.
ConeInjection() [2/2]
template<class CloudType > ConeInjection (const ConeInjection< CloudType > & im)
Definition at line 139 of file ConeInjection.C.
~ConeInjection()
template<class CloudType > virtual ~ConeInjection () virtual default
Member Function Documentation
TypeName()
template<class CloudType > TypeName ("coneInjection")
clone()
template<class CloudType > virtual autoPtr< InjectionModel< CloudType > > clone () const inline virtual
Implements InjectionModel< CloudType >.
Definition at line 138 of file ConeInjection.H.
updateMesh()
template<class CloudType > void updateMesh () virtual
Reimplemented from InjectionModel< CloudType >.
Definition at line 166 of file ConeInjection.C.
References bitSet::count(), Foam::endl(), bitSet::flip(), forAll, Foam::Info, Foam::inplaceSubset(), and bitSet::set().
Referenced by ConeInjection< CloudType >::ConeInjection().
timeEnd()
template<class CloudType > Foam::scalar timeEnd () const virtual
Implements InjectionModel< CloudType >.
Definition at line 207 of file ConeInjection.C.
parcelsToInject()
template<class CloudType > Foam::label parcelsToInject (const scalar time0, const scalar time1) virtual
Implements InjectionModel< CloudType >.
Definition at line 214 of file ConeInjection.C.
volumeToInject()
template<class CloudType > Foam::scalar volumeToInject (const scalar time0, const scalar time1) virtual
Implements InjectionModel< CloudType >.
Definition at line 237 of file ConeInjection.C.
setPositionAndCell()
template<class CloudType > void setPositionAndCell (const label parcelI, const label nParcels, const scalar time, vector & position, label & cellOwner, label & tetFacei, label & tetPti) virtual
Implements InjectionModel< CloudType >.
Definition at line 253 of file ConeInjection.C.
References UPtrList< T >::size().
setProperties()
template<class CloudType > void setProperties (const label parcelI, const label nParcels, const scalar time, typename CloudType::parcelType & parcel) virtual
Implements InjectionModel< CloudType >.
Definition at line 276 of file ConeInjection.C.
References alpha, beta(), Foam::cos(), Foam::degToRad(), Foam::sin(), UPtrList< T >::size(), and Foam::constant::mathematical::twoPi().
fullyDescribed()
template<class CloudType > bool fullyDescribed () const virtual
Implements InjectionModel< CloudType >.
Definition at line 315 of file ConeInjection.C.
validInjection()
template<class CloudType > bool validInjection (const label parcelI) virtual
Implements InjectionModel< CloudType >.
Definition at line 322 of file ConeInjection.C.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/Kinematic/InjectionModel/ConeInjection/ConeInjection.H
src/lagrangian/intermediate/submodels/Kinematic/InjectionModel/ConeInjection/ConeInjection.C