OpenFOAM: tabulated6DoFAcceleration Class Reference
tabulated6DoFAcceleration Class Reference
Tabulated 6DoF acceleration.
#include <tabulated6DoFAcceleration.H>
Public Member Functions
TypeName ("tabulated6DoFAcceleration")
tabulated6DoFAcceleration (const dictionary &accelerationCoeffs, const Time &runTime)
tabulated6DoFAcceleration (const tabulated6DoFAcceleration &)=delete
void operator= (const tabulated6DoFAcceleration &)=delete
virtual ~tabulated6DoFAcceleration ()=default
virtual Vector< vector > acceleration () const
virtual bool read (const dictionary &accelerationCoeffs)
Detailed Description
Tabulated 6DoF acceleration.
Obtained by interpolating tabulated data for linear acceleration, angular velocity and angular acceleration.
Source files
tabulated6DoFAcceleration.H
tabulated6DoFAcceleration.C
Definition at line 52 of file tabulated6DoFAcceleration.H.
Constructor & Destructor Documentation
tabulated6DoFAcceleration() [1/2]
tabulated6DoFAcceleration (const dictionary & accelerationCoeffs, const Time & runTime)
Definition at line 37 of file tabulated6DoFAcceleration.C.
References tabulated6DoFAcceleration::read().
tabulated6DoFAcceleration() [2/2]
tabulated6DoFAcceleration (const tabulated6DoFAcceleration &) delete
~tabulated6DoFAcceleration()
virtual ~tabulated6DoFAcceleration () virtual default
Member Function Documentation
TypeName()
TypeName ("tabulated6DoFAcceleration")
operator=()
void operator= (const tabulated6DoFAcceleration &) delete
acceleration()
Foam::tabulated6DoFAcceleration::accelerationVectors acceleration () const virtual
Definition at line 53 of file tabulated6DoFAcceleration.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::Info, Foam::interpolateSplineXY(), and UPtrList< T >::last().
read()
bool read (const dictionary & accelerationCoeffs) virtual
Definition at line 88 of file tabulated6DoFAcceleration.C.
References Foam::exit(), string::expand(), Foam::FatalError, FatalErrorInFunction, UPtrList< T >::first(), forAll, and UPtrList< T >::size().
Referenced by tabulated6DoFAcceleration::tabulated6DoFAcceleration().
The documentation for this class was generated from the following files:
src/fvOptions/sources/derived/tabulatedAccelerationSource/tabulated6DoFAcceleration/tabulated6DoFAcceleration.H
src/fvOptions/sources/derived/tabulatedAccelerationSource/tabulated6DoFAcceleration/tabulated6DoFAcceleration.C