OpenFOAM: ITstream Class Reference
ITstream Class Reference
An input stream of tokens.
#include <ITstream.H>
Public Member Functions
ITstream (const ITstream &is)
ITstream (ITstream &&is)
ITstream (IOstreamOption streamOpt=IOstreamOption(), const string &name="input")
ITstream (const Foam::zero, const string &name="input", IOstreamOption streamOpt=IOstreamOption())
ITstream (const UList< token > &tokens, IOstreamOption streamOpt=IOstreamOption(), const string &name="input")
ITstream (List< token > &&tokens, IOstreamOption streamOpt=IOstreamOption(), const string &name="input")
ITstream (const UList< char > &input, IOstreamOption streamOpt=IOstreamOption(), const string &name="input")
ITstream (const std::string &input, IOstreamOption streamOpt=IOstreamOption(), const string &name="input")
ITstream (const char *input, IOstreamOption streamOpt=IOstreamOption(), const string &name="input")
ITstream (const string &name, const UList< token > &tokens, IOstreamOption streamOpt=IOstreamOption())
ITstream (const string &name, List< token > &&tokens, IOstreamOption streamOpt=IOstreamOption())
virtual ~ITstream ()=default
virtual const fileName & name () const
virtual fileName & name ()
bool hasPutback () const noexcept
const token & front () const
const token & back () const
const token & peek () const
label tokenIndex () const noexcept
label & tokenIndex () noexcept
label nRemainingTokens () const noexcept
void seek (label pos)
void skip (label n=1)
void push_back (const token &t, const bool lazy)
void push_back (token &&t, const bool lazy)
void push_back (const UList< token > &newTokens, const bool lazy)
void push_back (List< token > &&newTokens, const bool lazy)
virtual ios_base::fmtflags flags () const
ios_base::fmtflags flags (const ios_base::fmtflags)
virtual Istream & read (token &tok)
virtual Istream & read (char &)
virtual Istream & read (word &)
virtual Istream & read (string &)
virtual Istream & read (label &)
virtual Istream & read (float &)
virtual Istream & read (double &)
virtual Istream & read (char *data, std::streamsize)
virtual Istream & readRaw (char *data, std::streamsize count)
virtual bool beginRawRead ()
virtual bool endRawRead ()
virtual void rewind ()
void print (Ostream &os) const
std::string toString () const
void operator= (const ITstream &is)
void operator= (const UList< token > &toks)
void operator= (List< token > &&toks)
const token & peekFirst () const
void append (const token &t, const bool lazy)
void append (token &&t, const bool lazy)
void append (const UList< token > &newTokens, const bool lazy)
void append (List< token > &&newTokens, const bool lazy)
Public Member Functions inherited from Istream
Istream (const Istream &)=default
virtual ~Istream ()=default
Istream (IOstreamOption streamOpt=IOstreamOption())
Istream (IOstreamOption::streamFormat fmt, IOstreamOption::compressionType cmp=IOstreamOption::UNCOMPRESSED)
const token & peekBack () const noexcept
bool peekBack (token &tok)
void putBack (const token &tok)
bool getBack (token &tok)
bool readBegin (const char *funcName)
bool readEnd (const char *funcName)
char readBeginList (const char *funcName)
char readEndList (const char *funcName)
Istream & operator() () const
Public Member Functions inherited from IOstream
IOstream (const IOstream &)=default
virtual ~IOstream ()=default
IOstream (IOstreamOption streamOpt=IOstreamOption())
IOstream (IOstreamOption::streamFormat fmt, IOstreamOption::versionNumber ver, IOstreamOption::compressionType cmp=IOstreamOption::UNCOMPRESSED)
fileName relativeName () const
virtual bool check (const char *operation) const
bool fatalCheck (const char *operation) const
bool opened () const noexcept
bool closed () const noexcept
bool good () const noexcept
bool eof () const noexcept
bool fail () const noexcept
bool bad () const noexcept
operator bool () const noexcept
bool operator! () const noexcept
unsigned labelByteSize () const noexcept
unsigned scalarByteSize () const noexcept
void setLabelByteSize (unsigned nbytes) noexcept
void setScalarByteSize (unsigned nbytes) noexcept
template<class T = label>
std::enable_if< std::is_integral< T >::value, bool >::type checkLabelSize () const noexcept
template<class T = scalar>
std::enable_if< std::is_floating_point< T >::value, bool >::type checkScalarSize () const noexcept
label lineNumber () const noexcept
label & lineNumber () noexcept
label lineNumber (const label num) noexcept
void setEof () noexcept
void setFail () noexcept
void setBad ()
ios_base::fmtflags setf (const ios_base::fmtflags f)
ios_base::fmtflags setf (const ios_base::fmtflags f, const ios_base::fmtflags mask)
void unsetf (const ios_base::fmtflags f)
void print (Ostream &os, const int streamState) const
InfoProxy< IOstream > info () const noexcept
Public Member Functions inherited from IOstreamOption
constexpr IOstreamOption (streamFormat fmt=streamFormat::ASCII, compressionType comp=compressionType::UNCOMPRESSED) noexcept
constexpr IOstreamOption (streamFormat fmt, compressionType comp, versionNumber ver) noexcept
constexpr IOstreamOption (streamFormat fmt, versionNumber ver, compressionType comp=compressionType::UNCOMPRESSED) noexcept
IOstreamOption (const IOstreamOption &opt, streamFormat fmt) noexcept
streamFormat format () const noexcept
streamFormat format (const streamFormat fmt) noexcept
streamFormat format (const word &formatName)
compressionType compression () const noexcept
compressionType compression (const compressionType comp) noexcept
compressionType compression (const word &compName)
versionNumber version () const noexcept
versionNumber version (const versionNumber ver) noexcept
versionNumber version (const token &tok)
Public Member Functions inherited from List< token >
constexpr List () noexcept
List (const label len)
List (const label len, const token &val)
List (const label len, const Foam::zero)
List (const Foam::one, const token &val)
List (const Foam::one, token &&val)
List (const Foam::one, const Foam::zero)
List (const List< token > &a)
List (const UList< token > &a)
List (List< token > &a, bool reuse)
List (const UList< token > &list, const labelUList &indices)
List (const UList< token > &list, const FixedList< label, N > &indices)
List (const FixedList< token, N > &list)
List (const PtrList< token > &list)
List (const SLList< token > &list)
List (const IndirectListBase< token, Addr > &list)
List (std::initializer_list< token > list)
List (List< token > &&list)
List (DynamicList< token, SizeMin > &&list)
List (SLList< token > &&list)
List (Istream &is)
autoPtr< List< token > > clone () const
~List ()
void clear ()
void resize (const label len)
void resize (const label len, const token &val)
void resize (const label newLen)
void resize_nocopy (const label len)
void setSize (const label n)
void setSize (const label n, const token &val)
void transfer (List< token > &list)
void transfer (DynamicList< token, SizeMin > &list)
token & newElmt (const label i)
token & emplace_back (Args &&... args)
void push_back (const token &val)
void push_back (token &&val)
void push_back (const UList< token > &list)
void push_back (const IndirectListBase< token, Addr > &list)
label push_uniq (const token &val)
void pop_back (label n=1)
void operator= (const UList< token > &a)
void operator= (const List< token > &list)
void operator= (const SLList< token > &list)
void operator= (const IndirectListBase< token, Addr > &list)
void operator= (const FixedList< token, N > &list)
void operator= (std::initializer_list< token > list)
void operator= (const token &val)
void operator= (const Foam::zero)
void operator= (List< token > &&list)
void operator= (DynamicList< token, SizeMin > &&list)
void operator= (SLList< token > &&list)
Istream & readList (Istream &is)
Istream & readList (Istream &is)
Istream & readList (Istream &is)
void shallowCopy (const UList< token > &)=delete
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type set (const label i, bool val=true)
void append (const token &val)
void append (token &&val)
void append (const UList< token > &list)
void append (const IndirectListBase< token, Addr > &list)
label appendUniq (const token &val)
Public Member Functions inherited from UList< T >
UList (const UList< T > &)=default
constexpr UList () noexcept
UList (T *__restrict__ v, const label len) noexcept
label fcIndex (const label i) const noexcept
label rcIndex (const label i) const noexcept
const T & fcValue (const label i) const
T & fcValue (const label i)
const T & rcValue (const label i) const
T & rcValue (const label i)
const T * cdata () const noexcept
T * data () noexcept
const char * cdata_bytes () const noexcept
char * data_bytes () noexcept
T & front ()
const T & front () const
T & back ()
const T & back () const
std::streamsize size_bytes () const noexcept
std::streamsize byteSize () const
void checkStart (const label start) const
void checkSize (const label size) const
void checkRange (const label start, const label len) const
void checkIndex (const label i) const
bool uniform () const
label find (const T &val, label pos=0) const
label rfind (const T &val, label pos=-1) const
bool contains (const T &val, label pos=0) const
void moveFirst (const label i)
void moveLast (const label i)
void swapFirst (const label i)
void swapLast (const label i)
void shallowCopy (const UList< T > &list)
void deepCopy (const UList< T > &list)
template<class Addr >
void deepCopy (const IndirectListBase< T, Addr > &list)
SubList< T > slice (const label pos, label len=-1)
const SubList< T > slice (const label pos, label len=-1) const
SubList< T > slice (const labelRange &range)
const SubList< T > slice (const labelRange &range) const
T & operator[] (const label i)
const T & operator[] (const label i) const
operator const Foam::List< T > & () const
void operator= (const T &val)
void operator= (const Foam::zero)
iterator begin () noexcept
iterator end () noexcept
iterator begin (const label i) noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
const_iterator begin () const noexcept
const_iterator end () const noexcept
const_iterator cbegin (const label i) const noexcept
const_iterator begin (const label i) const noexcept
reverse_iterator rbegin ()
reverse_iterator rend ()
const_reverse_iterator crbegin () const
const_reverse_iterator crend () const
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
bool empty () const noexcept
label size () const noexcept
void swap (UList< T > &list)
bool operator== (const UList< T > &a) const
bool operator!= (const UList< T > &a) const
bool operator< (const UList< T > &list) const
bool operator> (const UList< T > &a) const
bool operator<= (const UList< T > &a) const
bool operator>= (const UList< T > &a) const
Istream & readList (Istream &is)
void writeEntry (const word &keyword, Ostream &os) const
Ostream & writeList (Ostream &os, const label shortLen=0) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type test (const label i) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type get (const label i) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type unset (const label i)
T & first ()
const T & first () const
T & last ()
const T & last () const
bool found (const T &val, label pos=0) const
Istream & readList (Istream &is)
Ostream & writeList (Ostream &os, const label) const
const bool & operator[] (const label i) const
UPstream::commsStruct & operator[] (const label procID)
const UPstream::commsStruct & operator[] (const label procID) const
Foam::UPstream::commsStruct & operator[] (const label procID)
const Foam::UPstream::commsStruct & operator[] (const label procID) const
Ostream & writeList (Ostream &os, const label) const
Istream & readList (Istream &is)
Static Public Member Functions
static tokenList parse (const UList< char > &input, IOstreamOption streamOpt=IOstreamOption())
static tokenList parse (const std::string &input, IOstreamOption streamOpt=IOstreamOption())
static tokenList parse (const char *input, IOstreamOption streamOpt=IOstreamOption())
Static Public Member Functions inherited from IOstream
static unsigned int defaultPrecision () noexcept
static unsigned int defaultPrecision (unsigned int prec) noexcept
Static Public Member Functions inherited from IOstreamOption
static streamFormat formatEnum (const word &formatName, const streamFormat deflt=streamFormat::ASCII)
static streamFormat formatEnum (const word &key, const dictionary &dict, const streamFormat deflt=streamFormat::ASCII)
static compressionType compressionEnum (const word &compName, const compressionType deflt=compressionType::UNCOMPRESSED)
static compressionType compressionEnum (const word &key, const dictionary &dict, const compressionType deflt=compressionType::UNCOMPRESSED)
Static Public Member Functions inherited from List< token >
static const List< token > & null ()
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
static constexpr label max_size () noexcept
Additional Inherited Members
Public Types inherited from IOstream
enum streamAccess : char { CLOSED = 0 , OPENED }
Public Types inherited from IOstreamOption
enum streamFormat : char { ASCII = 0 , BINARY }
enum compressionType : char { UNCOMPRESSED = 0 , COMPRESSED }
enum appendType : char { NON_APPEND = 0 , APPEND }
enum atomicType : char { NON_ATOMIC = 0 , ATOMIC }
Public Types inherited from List< token >
typedef SubList< token > subList
Public Types inherited from UList< T >
typedef T value_type
typedef T * pointer
typedef const T * const_pointer
typedef T & reference
typedef const T & const_reference
typedef T * iterator
typedef const T * const_iterator
typedef label size_type
typedef label difference_type
typedef std::reverse_iterator< iterator > reverse_iterator
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
Static Public Attributes inherited from IOstream
static unsigned int precision_
Static Public Attributes inherited from IOstreamOption
static const Enum< streamFormat > formatNames
static const versionNumber currentVersion
Protected Member Functions inherited from Istream
bool hasPutback () const noexcept
Protected Member Functions inherited from IOstream
void setOpened () noexcept
void setClosed () noexcept
void setState (std::ios_base::iostate state) noexcept
void setGood () noexcept
Protected Member Functions inherited from UList< T >
void setAddressableSize (const label n) noexcept
void size (const label n)
void writeEntry (Ostream &os) const
labelRange validateRange (const labelRange &requestedRange) const
UList< T > & operator= (const UList< T > &)=delete
void writeEntry (Ostream &os) const
void writeEntry (Ostream &os) const
Protected Attributes inherited from IOstream
std::ios_base::iostate ioState_
streamAccess openClosed_
unsigned char sizeofLabel_
unsigned char sizeofScalar_
label lineNumber_
Static Protected Attributes inherited from IOstream
static fileName staticName_
Detailed Description
An input stream of tokens.
Source files
ITstream.H
ITstream.C
Definition at line 48 of file ITstream.H.
Constructor & Destructor Documentation
ITstream() [1/11]
ITstream (const ITstream & is)
Definition at line 136 of file ITstream.C.
References IOstream::setGood(), and IOstream::setOpened().
ITstream() [2/11]
ITstream (ITstream && is)
Definition at line 148 of file ITstream.C.
References IOstream::setGood(), and IOstream::setOpened().
ITstream() [3/11]
ITstream (IOstreamOption streamOpt = IOstreamOption(), const string & name = "input") explicit
Definition at line 160 of file ITstream.C.
References IOstream::setGood(), and IOstream::setOpened().
ITstream() [4/11]
ITstream (const Foam::zero , const string & name = "input", IOstreamOption streamOpt = IOstreamOption()) explicit
Definition at line 176 of file ITstream.C.
ITstream() [5/11]
ITstream (const UList< token > & tokens, IOstreamOption streamOpt = IOstreamOption(), const string & name = "input") explicit
Definition at line 187 of file ITstream.C.
References IOstream::setGood(), and IOstream::setOpened().
ITstream() [6/11]
ITstream (List< token > && tokens, IOstreamOption streamOpt = IOstreamOption(), const string & name = "input") explicit
Definition at line 204 of file ITstream.C.
References IOstream::setGood(), and IOstream::setOpened().
ITstream() [7/11]
ITstream (const UList< char > & input, IOstreamOption streamOpt = IOstreamOption(), const string & name = "input") explicit
Definition at line 221 of file ITstream.C.
References Foam::input(), Foam::parseStream(), and ITstream::rewind().
ITstream() [8/11]
ITstream (const std::string & input, IOstreamOption streamOpt = IOstreamOption(), const string & name = "input") explicit
Definition at line 237 of file ITstream.C.
References Foam::input(), Foam::parseStream(), and ITstream::rewind().
ITstream() [9/11]
ITstream (const char * input, IOstreamOption streamOpt = IOstreamOption(), const string & name = "input") explicit
Definition at line 253 of file ITstream.C.
References Foam::input(), Foam::parseStream(), and ITstream::rewind().
ITstream() [10/11]
ITstream (const string & name, const UList< token > & tokens, IOstreamOption streamOpt = IOstreamOption()) inline
Definition at line 159 of file ITstream.H.
ITstream() [11/11]
ITstream (const string & name, List< token > && tokens, IOstreamOption streamOpt = IOstreamOption()) inline
Definition at line 170 of file ITstream.H.
~ITstream()
virtual ~ITstream () virtual default
Member Function Documentation
parse() [1/3]
Foam::tokenList parse (const UList< char > & input, IOstreamOption streamOpt = IOstreamOption()) static
Definition at line 57 of file ITstream.C.
References Foam::input(), and Foam::parseStream().
Referenced by dictionary::tokens().
parse() [2/3]
Foam::tokenList parse (const std::string & input, IOstreamOption streamOpt = IOstreamOption()) static
Definition at line 71 of file ITstream.C.
References Foam::input(), and Foam::parseStream().
parse() [3/3]
Foam::tokenList parse (const char * input, IOstreamOption streamOpt = IOstreamOption()) static
Definition at line 85 of file ITstream.C.
References Foam::input(), and Foam::parseStream().
name() [1/2]
virtual const fileName & name () const inline virtual
Reimplemented from IOstream.
Reimplemented in primitiveEntry.
Definition at line 217 of file ITstream.H.
Referenced by primitiveEntry::name(), primitiveEntry::name(), and primitiveEntry::primitiveEntry().
name() [2/2]
virtual fileName & name () inline virtual
Reimplemented in primitiveEntry.
Definition at line 220 of file ITstream.H.
hasPutback()
bool hasPutback () const inline noexcept
Definition at line 226 of file ITstream.H.
References Istream::hasPutback().
front()
const token & front () const inline
Definition at line 233 of file ITstream.H.
Referenced by ITstream::peekFirst().
back()
const token & back () const inline
Definition at line 237 of file ITstream.H.
References UList< T >::size().
peek()
const Foam::token & peek () const
Definition at line 321 of file ITstream.C.
tokenIndex() [1/2]
label tokenIndex () const inline noexcept
Definition at line 245 of file ITstream.H.
tokenIndex() [2/2]
label & tokenIndex () inline noexcept
Definition at line 248 of file ITstream.H.
nRemainingTokens()
label nRemainingTokens () const inline noexcept
Definition at line 251 of file ITstream.H.
References UList< T >::size().
seek()
void seek (label pos)
Definition at line 333 of file ITstream.C.
skip()
void skip (label n = 1)
Definition at line 380 of file ITstream.C.
References n, and UPtrList< T >::size().
push_back() [1/4]
void push_back (const token & t, const bool lazy)
Definition at line 536 of file ITstream.C.
Referenced by ITstream::append(), ITstream::append(), ITstream::append(), and ITstream::append().
push_back() [2/4]
void push_back (token && t, const bool lazy)
Definition at line 546 of file ITstream.C.
push_back() [3/4]
void push_back (const UList< token > & newTokens, const bool lazy)
Definition at line 556 of file ITstream.C.
References UPtrList< T >::size().
push_back() [4/4]
void push_back (List< token > && newTokens, const bool lazy)
Definition at line 569 of file ITstream.C.
References PtrList< T >::clear(), and UPtrList< T >::size().
flags() [1/2]
virtual ios_base::fmtflags flags () const inline virtual
Implements IOstream.
Definition at line 299 of file ITstream.H.
flags() [2/2]
ios_base::fmtflags flags (const ios_base::fmtflags) inline virtual
Implements IOstream.
Definition at line 305 of file ITstream.H.
read() [1/8]
Foam::Istream & read (token & tok) virtual
Implements Istream.
Reimplemented in primitiveEntry.
Definition at line 422 of file ITstream.C.
References UPtrList< T >::back(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, Istream::getBack(), and UPtrList< T >::size().
read() [2/8]
Foam::Istream & read (char &) virtual
Implements Istream.
Reimplemented in primitiveEntry.
Definition at line 474 of file ITstream.C.
References NotImplemented.
read() [3/8]
Foam::Istream & read (word &) virtual
Implements Istream.
Reimplemented in primitiveEntry.
Definition at line 481 of file ITstream.C.
References NotImplemented.
read() [4/8]
Foam::Istream & read (string &) virtual
Implements Istream.
Reimplemented in primitiveEntry.
Definition at line 488 of file ITstream.C.
References NotImplemented.
read() [5/8]
Foam::Istream & read (label &) virtual
Implements Istream.
Reimplemented in primitiveEntry.
Definition at line 495 of file ITstream.C.
References NotImplemented.
read() [6/8]
Foam::Istream & read (float &) virtual
Implements Istream.
Reimplemented in primitiveEntry.
Definition at line 502 of file ITstream.C.
References NotImplemented.
read() [7/8]
Foam::Istream & read (double &) virtual
Implements Istream.
Reimplemented in primitiveEntry.
Definition at line 509 of file ITstream.C.
References NotImplemented.
read() [8/8]
Foam::Istream & read (char * data, std::streamsize) virtual
Implements Istream.
Reimplemented in primitiveEntry.
Definition at line 523 of file ITstream.C.
References NotImplemented.
readRaw()
Foam::Istream & readRaw (char * data, std::streamsize count) virtual
Implements Istream.
Definition at line 516 of file ITstream.C.
References NotImplemented.
beginRawRead()
virtual bool beginRawRead () inline virtual
Implements Istream.
Definition at line 343 of file ITstream.H.
endRawRead()
virtual bool endRawRead () inline virtual
Implements Istream.
Definition at line 349 of file ITstream.H.
rewind()
void rewind () virtual
Implements Istream.
Definition at line 530 of file ITstream.C.
Referenced by ITstream::ITstream(), ITstream::ITstream(), and ITstream::ITstream().
print()
void print (Ostream & os) const virtual
Reimplemented from IOstream.
Definition at line 271 of file ITstream.C.
References UPtrList< T >::back(), UPtrList< T >::empty(), UPtrList< T >::front(), os(), and IOstream::print().
toString()
std::string toString () const
Definition at line 296 of file ITstream.C.
References UPtrList< T >::front(), OSstream::precision(), UPtrList< T >::size(), and token::SPACE.
operator=() [1/3]
void operator= (const ITstream & is)
Definition at line 586 of file ITstream.C.
References List< token >::operator=().
operator=() [2/3]
void operator= (const UList< token > & toks)
Definition at line 599 of file ITstream.C.
References List< token >::operator=().
operator=() [3/3]
void operator= (List< token > && toks)
Definition at line 606 of file ITstream.C.
References List< token >::operator=().
peekFirst()
const token & peekFirst () const inline
Definition at line 414 of file ITstream.H.
References ITstream::front().
append() [1/4]
void append (const token & t, const bool lazy) inline
Definition at line 418 of file ITstream.H.
References ITstream::push_back().
append() [2/4]
void append (token && t, const bool lazy) inline
Definition at line 425 of file ITstream.H.
References ITstream::push_back().
append() [3/4]
void append (const UList< token > & newTokens, const bool lazy) inline
Definition at line 436 of file ITstream.H.
References ITstream::push_back().
append() [4/4]
void append (List< token > && newTokens, const bool lazy) inline
Definition at line 447 of file ITstream.H.
References ITstream::push_back().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOstreams/Tstreams/ITstream.H
src/OpenFOAM/db/IOstreams/Tstreams/ITstream.C