OpenFOAM: patchEdgeFaceInfo Class Reference
patchEdgeFaceInfo Class Reference
#include <patchEdgeFaceInfo.H>
Public Member Functions
patchEdgeFaceInfo ()
patchEdgeFaceInfo (const point &origin, const scalar distSqr)
const point & origin () const
scalar distSqr () const
template<class TrackingData >
bool valid (TrackingData &td) const
template<class TrackingData >
void transform (const polyMesh &mesh, const primitivePatch &patch, const tensor &rotTensor, const scalar tol, TrackingData &td)
template<class TrackingData >
bool updateEdge (const polyMesh &mesh, const primitivePatch &patch, const label edgeI, const label facei, const patchEdgeFaceInfo &faceInfo, const scalar tol, TrackingData &td)
template<class TrackingData >
bool updateEdge (const polyMesh &mesh, const primitivePatch &patch, const patchEdgeFaceInfo &edgeInfo, const bool sameOrientation, const scalar tol, TrackingData &td)
template<class TrackingData >
bool updateFace (const polyMesh &mesh, const primitivePatch &patch, const label facei, const label edgeI, const patchEdgeFaceInfo &edgeInfo, const scalar tol, TrackingData &td)
template<class TrackingData >
bool equal (const patchEdgeFaceInfo &, TrackingData &td) const
bool operator== (const patchEdgeFaceInfo &) const
bool operator!= (const patchEdgeFaceInfo &) const
Friends
Ostream & operator<< (Ostream &, const patchEdgeFaceInfo &)
Istream & operator>> (Istream &, patchEdgeFaceInfo &)
Detailed Description
Source files
patchEdgeFaceInfo.H
patchEdgeFaceInfoI.H
patchEdgeFaceInfo.C
Definition at line 59 of file patchEdgeFaceInfo.H.
Constructor & Destructor Documentation
patchEdgeFaceInfo() [1/2]
patchEdgeFaceInfo () inline
Definition at line 116 of file patchEdgeFaceInfoI.H.
patchEdgeFaceInfo() [2/2]
patchEdgeFaceInfo (const point & origin, const scalar distSqr) inline
Definition at line 122 of file patchEdgeFaceInfoI.H.
Member Function Documentation
origin()
const point & origin () const inline
Definition at line 110 of file patchEdgeFaceInfo.H.
distSqr()
scalar distSqr () const inline
Definition at line 115 of file patchEdgeFaceInfo.H.
valid()
template<class TrackingData > bool valid (TrackingData & td) const inline
Definition at line 136 of file patchEdgeFaceInfoI.H.
References VectorSpace< Form, Cmpt, Ncmpts >::max.
transform()
template<class TrackingData > void transform (const polyMesh & mesh, const primitivePatch & patch, const tensor & rotTensor, const scalar tol, TrackingData & td) inline
Definition at line 143 of file patchEdgeFaceInfoI.H.
References Foam::transform().
updateEdge() [1/2]
template<class TrackingData > bool updateEdge (const polyMesh & mesh, const primitivePatch & patch, const label edgeI, const label facei, const patchEdgeFaceInfo & faceInfo, const scalar tol, TrackingData & td) inline
Definition at line 157 of file patchEdgeFaceInfoI.H.
References e, and update().
updateEdge() [2/2]
template<class TrackingData > bool updateEdge (const polyMesh & mesh, const primitivePatch & patch, const patchEdgeFaceInfo & edgeInfo, const bool sameOrientation, const scalar tol, TrackingData & td) inline
Definition at line 182 of file patchEdgeFaceInfoI.H.
References update().
updateFace()
template<class TrackingData > bool updateFace (const polyMesh & mesh, const primitivePatch & patch, const label facei, const label edgeI, const patchEdgeFaceInfo & edgeInfo, const scalar tol, TrackingData & td) inline
Definition at line 197 of file patchEdgeFaceInfoI.H.
References update().
equal()
template<class TrackingData > bool equal (const patchEdgeFaceInfo & rhs, TrackingData & td) const inline
Definition at line 213 of file patchEdgeFaceInfoI.H.
References Foam::operator==().
operator==()
bool operator== (const patchEdgeFaceInfo & rhs) const inline
Definition at line 225 of file patchEdgeFaceInfoI.H.
operator!=()
bool operator!= (const patchEdgeFaceInfo & rhs) const inline
Definition at line 234 of file patchEdgeFaceInfoI.H.
Friends And Related Symbol Documentation
operator<<
Ostream & operator<< (Ostream & , const patchEdgeFaceInfo &) friend
operator>>
Istream & operator>> (Istream & , patchEdgeFaceInfo &) friend
The documentation for this class was generated from the following files:
src/meshTools/algorithms/PatchEdgeFaceWave/patchEdgeFaceInfo.H
src/meshTools/algorithms/PatchEdgeFaceWave/patchEdgeFaceInfoI.H