OpenFOAM: fixedBlended< Type > Class Template Reference
fixedBlended< Type > Class Template Reference
Numerics » Finite volume numerical schemes » Surface interpolation schemes
Two-scheme fixed-blending differencing scheme.
#include <fixedBlended.H>
Public Member Functions
TypeName ("fixedBlended")
fixedBlended (const fvMesh &mesh, Istream &is)
fixedBlended (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &is)
tmp< surfaceScalarField > weights (const GeometricField< Type, fvPatchField, volMesh > &vf) const
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &vf) const
virtual bool corrected () const
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > &vf) const
Public Member Functions inherited from surfaceInterpolationScheme< Type >
TypeName ("surfaceInterpolationScheme")
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, Mesh,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, MeshFlux,(const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
surfaceInterpolationScheme (const fvMesh &mesh)
virtual ~surfaceInterpolationScheme ()=default
const fvMesh & mesh () const
virtual tmp< GeometricField< typename innerProduct< vector, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf) const
tmp< GeometricField< typename innerProduct< vector, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const tmp< GeometricField< Type, fvPatchField, volMesh > > &) const
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > &) const
template<class SFType >
Foam::tmp< Foam::GeometricField< typename Foam::innerProduct< typename SFType::value_type, Type >::type, Foam::fvsPatchField, Foam::surfaceMesh > > dotInterpolate (const SFType &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf, const tmp< surfaceScalarField > &tlambdas)
tmp< GeometricField< typename innerProduct< vector, scalar >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const GeometricField< scalar, fvPatchField, volMesh > &) const
Foam::tmp< Foam::GeometricField< typename Foam::innerProduct< Foam::vector, Foam::scalar >::type, Foam::fvsPatchField, Foam::surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const GeometricField< scalar, fvPatchField, volMesh > &) const
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Additional Inherited Members
Static Public Member Functions inherited from surfaceInterpolationScheme< Type >
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData)
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &, const tmp< surfaceScalarField > &)
template<class SFType >
static tmp< GeometricField< typename innerProduct< typename SFType::value_type, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const SFType &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf, const tmp< surfaceScalarField > &tlambdas)
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &)
Detailed Description
template<class Type>
class Foam::fixedBlended< Type >
Two-scheme fixed-blending differencing scheme.
Similar to localBlended but uses a single (global) constant blending factor. The factor applies to the first scheme and 1-factor to the second scheme.
Note
Although a blending factor of 0 and 1 is permitted, it is more efficient just to use the underlying scheme directly.
Source files
fixedBlended.H
fixedBlended.C
Definition at line 58 of file fixedBlended.H.
Constructor & Destructor Documentation
fixedBlended() [1/2]
template<class Type > fixedBlended (const fvMesh & mesh, Istream & is) inline
Definition at line 93 of file fixedBlended.H.
References Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, and Foam::Info.
fixedBlended() [2/2]
template<class Type > fixedBlended (const fvMesh & mesh, const surfaceScalarField & faceFlux, Istream & is) inline
Definition at line 129 of file fixedBlended.H.
References Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, and Foam::Info.
Member Function Documentation
TypeName()
template<class Type > TypeName ("fixedBlended< Type >")
weights()
template<class Type > tmp< surfaceScalarField > weights (const GeometricField< Type, fvPatchField, volMesh > & vf) const inline virtual
Implements surfaceInterpolationScheme< Type >.
Definition at line 169 of file fixedBlended.H.
interpolate()
template<class Type > tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > & vf) const inline virtual
Reimplemented from surfaceInterpolationScheme< Type >.
Definition at line 183 of file fixedBlended.H.
corrected()
template<class Type > virtual bool corrected () const inline virtual
Reimplemented from surfaceInterpolationScheme< Type >.
Definition at line 195 of file fixedBlended.H.
Referenced by fixedBlended< Type >::correction().
correction()
template<class Type > virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > & vf) const inline virtual
Reimplemented from surfaceInterpolationScheme< Type >.
Definition at line 204 of file fixedBlended.H.
References fixedBlended< Type >::corrected(), and fixedBlended< Type >::correction().
Referenced by fixedBlended< Type >::correction().
The documentation for this class was generated from the following file:
src/finiteVolume/interpolation/surfaceInterpolation/schemes/fixedBlended/fixedBlended.H