OpenFOAM: extendedFaceToCellStencil Class Reference
extendedFaceToCellStencil Class Reference
Note: transformations on coupled patches not supported. Problem is the positions of cells reachable through these patches.
#include <extendedFaceToCellStencil.H>
Public Member Functions
extendedFaceToCellStencil (const polyMesh &)
template<class Type >
void collectData (const mapDistribute &map, const labelListList &stencil, const GeometricField< Type, fvsPatchField, surfaceMesh > &fld, List< List< Type > > &stencilFld)
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > weightedSum (const mapDistribute &map, const labelListList &stencil, const GeometricField< Type, fvsPatchField, surfaceMesh > &fld, const List< List< scalar > > &stencilWeights)
Static Public Member Functions
template<class T >
static void collectData (const mapDistribute &map, const labelListList &stencil, const GeometricField< T, fvsPatchField, surfaceMesh > &fld, List< List< T > > &stencilFld)
template<class Type >
static tmp< GeometricField< Type, fvPatchField, volMesh > > weightedSum (const mapDistribute &map, const labelListList &stencil, const GeometricField< Type, fvsPatchField, surfaceMesh > &fld, const List< List< scalar > > &stencilWeights)
Protected Attributes
const polyMesh & mesh_
Detailed Description
Note: transformations on coupled patches not supported. Problem is the positions of cells reachable through these patches.
Source files
extendedFaceToCellStencil.H
extendedFaceToCellStencil.C
extendedFaceToCellStencilTemplates.C
Definition at line 52 of file extendedFaceToCellStencil.H.
Constructor & Destructor Documentation
extendedFaceToCellStencil()
extendedFaceToCellStencil (const polyMesh & mesh) explicit
Definition at line 27 of file extendedFaceToCellStencil.C.
References coupled(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, mesh, and patches.
Member Function Documentation
collectData() [1/2]
template<class T > static void collectData (const mapDistribute & map, const labelListList & stencil, const GeometricField< T, fvsPatchField, surfaceMesh > & fld, List< List< T > > & stencilFld) static
Referenced by extendedCentredFaceToCellStencil::collectData().
weightedSum() [1/2]
template<class Type > static tmp< GeometricField< Type, fvPatchField, volMesh > > weightedSum (const mapDistribute & map, const labelListList & stencil, const GeometricField< Type, fvsPatchField, surfaceMesh > & fld, const List< List< scalar > > & stencilWeights) static
Referenced by extendedCentredFaceToCellStencil::weightedSum().
collectData() [2/2]
template<class Type > void collectData (const mapDistribute & map, const labelListList & stencil, const GeometricField< Type, fvsPatchField, surfaceMesh > & fld, List< List< Type > > & stencilFld)
Definition at line 26 of file extendedFaceToCellStencilTemplates.C.
References mapDistributeBase::constructSize(), mapDistribute::distribute(), fld(), forAll, PtrList< T >::setSize(), UPtrList< T >::size(), UList< T >::size(), and Foam::Zero.
weightedSum() [2/2]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > weightedSum (const mapDistribute & map, const labelListList & stencil, const GeometricField< Type, fvsPatchField, surfaceMesh > & fld, const List< List< scalar > > & stencilWeights)
Definition at line 77 of file extendedFaceToCellStencilTemplates.C.
References fld(), forAll, mesh, fvMesh::time(), and Foam::Zero.
Member Data Documentation
mesh_
const polyMesh& mesh_ protected
Definition at line 58 of file extendedFaceToCellStencil.H.
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/extendedStencil/faceToCell/extendedFaceToCellStencil.H
src/finiteVolume/fvMesh/extendedStencil/faceToCell/extendedFaceToCellStencil.C
src/finiteVolume/fvMesh/extendedStencil/faceToCell/extendedFaceToCellStencilTemplates.C