OpenFOAM: cyclicPolyPatch Class Reference
cyclicPolyPatch Class Reference
Cyclic plane patch.
#include <cyclicPolyPatch.H>
Public Member Functions
TypeName ("cyclic")
cyclicPolyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType, const transformType transform=UNKNOWN)
cyclicPolyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &neighbPatchName, const transformType transform, const vector &rotationAxis, const point &rotationCentre, const vector &separationVector)
cyclicPolyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType)
cyclicPolyPatch (const cyclicPolyPatch &, const polyBoundaryMesh &)
cyclicPolyPatch (const cyclicPolyPatch &, label nbrPatchID, const labelList &faceCells)
cyclicPolyPatch (const cyclicPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart, const word &neighbPatchName)
cyclicPolyPatch (const cyclicPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm) const
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart) const
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart) const
virtual ~cyclicPolyPatch ()
virtual void newInternalProcFaces (label &newFaces, label &newProcFaces) const
virtual const labelUList & nbrCells () const
virtual label neighbPolyPatchID () const
virtual refPtr< labelListList > mapCollocatedFaces () const
virtual bool masterImplicit () const
const word & neighbPatchName () const
virtual label neighbPatchID () const
virtual bool owner () const
virtual bool neighbour () const
const cyclicPolyPatch & neighbPatch () const
const edgeList & coupledPoints () const
const edgeList & coupledEdges () const
virtual void transformPosition (pointField &l) const
virtual void transformPosition (point &, const label facei) const
label transformGlobalFace (const label facei) const
const vector & rotationAxis () const
const point & rotationCentre () const
const vector & separationVector () const
virtual void initOrder (PstreamBuffers &, const primitivePatch &) const
virtual bool order (PstreamBuffers &, const primitivePatch &, labelList &faceMap, labelList &rotation) const
virtual void write (Ostream &) const
Public Member Functions inherited from coupledPolyPatch
TypeName ("coupled")
coupledPolyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType, const transformType transform)
coupledPolyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType)
coupledPolyPatch (const coupledPolyPatch &, const polyBoundaryMesh &bm)
coupledPolyPatch (const coupledPolyPatch &, const labelList &faceCells)
coupledPolyPatch (const coupledPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart)
coupledPolyPatch (const coupledPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
virtual ~coupledPolyPatch ()
virtual bool coupled () const
virtual transformType transform () const
virtual transformType & transform ()
virtual bool separated () const
virtual const vectorField & separation () const
virtual bool parallel () const
virtual const tensorField & forwardT () const
virtual const tensorField & reverseT () const
virtual const boolList & collocated () const
scalar matchTolerance () const
Public Member Functions inherited from polyPatch
TypeName ("patch")
declareRunTimeSelectionTable (autoPtr, polyPatch, word,(const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType),(name, size, start, index, bm, patchType))
declareRunTimeSelectionTable (autoPtr, polyPatch, dictionary,(const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType),(name, dict, index, bm, patchType))
polyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType)
polyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &physicalType, const wordList &inGroups)
polyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType)
polyPatch (const polyPatch &, const polyBoundaryMesh &)
polyPatch (const polyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart)
polyPatch (const polyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
polyPatch (const polyPatch &p)
polyPatch (const polyPatch &p, const labelList &faceCells)
virtual autoPtr< polyPatch > clone (const labelList &faceCells) const
virtual ~polyPatch ()
virtual word neighbRegionID () const
label offset () const noexcept
label start () const noexcept
labelRange range () const
const polyBoundaryMesh & boundaryMesh () const noexcept
template<class T >
const UIndirectList< T > patchInternalList (const UList< T > &internalValues) const
template<class T >
const List< T >::subList patchSlice (const UList< T > &values) const
template<class T >
const List< T >::subList boundarySlice (const List< T > &values) const
template<class T >
const Field< T >::subField patchSlice (const Field< T > &values) const
const vectorField::subField faceCentres () const
const vectorField::subField faceAreas () const
tmp< vectorField > faceCellCentres () const
tmp< scalarField > areaFraction () const
const labelUList & faceCells () const
const labelList & meshEdges () const
virtual void clearAddressing ()
label whichFace (const label facei) const noexcept
virtual bool changeTopology () const
virtual bool setTopology (polyTopoChange &)
void operator= (const polyPatch &)
Public Member Functions inherited from patchIdentifier
patchIdentifier (const patchIdentifier &)=default
patchIdentifier & operator= (const patchIdentifier &)=default
virtual ~patchIdentifier ()=default
patchIdentifier ()
patchIdentifier (const word &name, const label index)
patchIdentifier (const word &name, const label index, const word &physicalType, const wordList &inGroups=wordList())
patchIdentifier (const word &name, const dictionary &dict, const label index)
patchIdentifier (const patchIdentifier &ident, const label index)
const word & name () const noexcept
word & name () noexcept
label index () const noexcept
label & index () noexcept
const word & physicalType () const noexcept
word & physicalType () noexcept
const wordList & inGroups () const noexcept
wordList & inGroups () noexcept
bool inGroup (const word &name) const
void write (Ostream &os) const
Public Member Functions inherited from PrimitivePatch< FaceList, PointField >
PrimitivePatch (const FaceList &faces, const PointField &points)
PrimitivePatch (FaceList &&faces, const PointField &points)
PrimitivePatch (FaceList &faces, PointField &points, const bool reuse)
PrimitivePatch (const PrimitivePatch< FaceList, PointField > &pp)
virtual ~PrimitivePatch ()
void clearOut ()
void clearGeom ()
void clearTopology ()
void clearPatchMeshAddr ()
void swap (PrimitivePatch &)=delete
const Field< point_type > & points () const noexcept
label nFaces () const noexcept
label nPoints () const
label nEdges () const
const edgeList & edges () const
const edgeList::subList internalEdges () const
const edgeList::subList boundaryEdges () const
label nInternalEdges () const
label nBoundaryEdges () const
bool isInternalEdge (const label edgei) const
const labelList & boundaryPoints () const
const labelListList & faceFaces () const
const labelListList & edgeFaces () const
const labelListList & faceEdges () const
const labelListList & pointEdges () const
const labelListList & pointFaces () const
const List< face_type > & localFaces () const
labelList boundaryFaces () const
labelList uniqBoundaryFaces () const
const labelList & meshPoints () const
const Map< label > & meshPointMap () const
const Field< point_type > & localPoints () const
const labelList & localPointOrder () const
label whichPoint (const label gp) const
edge meshEdge (const label edgei) const
edge meshEdge (const edge &e) const
label findEdge (const edge &e) const
labelList meshEdges (const edgeList &allEdges, const labelListList &cellEdges, const labelList &faceCells) const
labelList meshEdges (const edgeList &allEdges, const labelListList &pointEdges) const
label meshEdge (const label edgei, const edgeList &allEdges, const labelListList &pointEdges) const
labelList meshEdges (const labelUList &edgeLabels, const edgeList &allEdges, const labelListList &pointEdges) const
const Field< point_type > & faceCentres () const
const Field< point_type > & faceAreas () const
const Field< scalar > & magFaceAreas () const
const Field< point_type > & faceNormals () const
const Field< point_type > & pointNormals () const
Pair< point_type > box () const
scalar sphere (const label facei) const
bool hasFaceAreas () const
bool hasFaceCentres () const
bool hasFaceNormals () const
bool hasPointNormals () const
bool hasBoundaryPoints () const
bool hasEdges () const
bool hasFaceFaces () const
bool hasEdgeFaces () const
bool hasFaceEdges () const
bool hasPointEdges () const
bool hasPointFaces () const
bool hasMeshPoints () const
bool hasMeshPointMap () const
template<class ToPatch >
List< objectHit > projectPoints (const ToPatch &targetPatch, const Field< point_type > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
template<class ToPatch >
List< objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< point_type > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
const labelListList & edgeLoops () const
surfaceTopo surfaceType (labelHashSet *badEdgesPtr=nullptr) const
bool checkTopology (const bool report=false, labelHashSet *pointSetPtr=nullptr) const
bool checkPointManifold (const bool report=false, labelHashSet *pointSetPtr=nullptr) const
void operator= (const PrimitivePatch< FaceList, PointField > &rhs)
void operator= (PrimitivePatch< FaceList, PointField > &&rhs)
label whichEdge (const edge &e) const
template<class ToPatch >
Foam::List< Foam::objectHit > projectPoints (const ToPatch &targetPatch, const Field< typename Foam::PrimitivePatch< FaceList, PointField >::point_type > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
template<class ToPatch >
Foam::List< Foam::objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< typename Foam::PrimitivePatch< FaceList, PointField >::point_type > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
Public Member Functions inherited from PrimitivePatchBase
ClassName ("PrimitivePatch")
PrimitivePatchBase ()=default
Protected Member Functions
virtual void calcTransforms ()
virtual void initGeometry (PstreamBuffers &)
virtual void initGeometry (const primitivePatch &referPatch, pointField &nbrCtrs, vectorField &nbrAreas, pointField &nbrCc)
virtual void calcGeometry (PstreamBuffers &)
virtual void calcGeometry (const primitivePatch &referPatch, const pointField &thisCtrs, const vectorField &thisAreas, const pointField &thisCc, const pointField &nbrCtrs, const vectorField &nbrAreas, const pointField &nbrCc)
virtual void initMovePoints (PstreamBuffers &, const pointField &)
virtual void movePoints (PstreamBuffers &, const pointField &)
virtual void initUpdateMesh (PstreamBuffers &)
virtual void updateMesh (PstreamBuffers &)
Protected Member Functions inherited from coupledPolyPatch
void calcTransformTensors (const vectorField &Cf, const vectorField &Cr, const vectorField &nf, const vectorField &nr, const scalarField &smallDist, const scalar absTol, const transformType=UNKNOWN) const
Protected Member Functions inherited from polyPatch
virtual void clearGeom ()
virtual void movePoints (const Field< point_type > &)
Friends
class processorCyclicPolyPatch
Additional Inherited Members
Public Types inherited from coupledPolyPatch
enum transformType {
UNKNOWN , ROTATIONAL , TRANSLATIONAL , COINCIDENTFULLMATCH ,
NOORDERING
}
Public Types inherited from PrimitivePatch< FaceList, PointField >
enum surfaceTopo { MANIFOLD , OPEN , ILLEGAL }
typedef std::remove_reference< FaceList >::type::value_type face_type
typedef std::remove_reference< PointField >::type::value_type point_type
typedef FaceList FaceListType
typedef PointField PointFieldType
typedef face_type FaceType
Static Public Member Functions inherited from coupledPolyPatch
static scalarField calcFaceTol (const UList< face > &faces, const pointField &points, const pointField &faceCentres)
Static Public Member Functions inherited from polyPatch
static autoPtr< polyPatch > New (const word &patchType, const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm)
static autoPtr< polyPatch > New (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm)
static autoPtr< polyPatch > New (const word &patchType, const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm)
static bool constraintType (const word &patchType)
static wordList constraintTypes ()
Static Public Member Functions inherited from patchIdentifier
static word defaultName (const label n=-1)
Static Public Attributes inherited from coupledPolyPatch
static const Enum< transformType > transformTypeNames
Static Public Attributes inherited from polyPatch
static int disallowGenericPolyPatch
Static Protected Member Functions inherited from coupledPolyPatch
static void writeOBJ (Ostream &os, const point &pt)
static void writeOBJ (Ostream &, const pointField &, const labelList &)
static void writeOBJ (const fileName &, const UList< face > &, const pointField &)
static void writeOBJ (Ostream &os, const point &p0, const point &p1, label &vertI)
static pointField getAnchorPoints (const UList< face > &, const pointField &, const transformType)
static label getRotation (const pointField &points, const face &f, const point &anchor, const scalar tol)
Detailed Description
Cyclic plane patch.
Note: morph patch face ordering uses geometric matching so with the following restrictions: -coupled patches should be flat planes. -no rotation in patch plane
Uses coupledPolyPatch::calcFaceTol to calculate tolerance per face which might need tweaking.
Switch on 'cyclicPolyPatch' debug flag to write .obj files to show the matching.
Source files
cyclicPolyPatch.H
cyclicPolyPatch.C
Definition at line 62 of file cyclicPolyPatch.H.
Constructor & Destructor Documentation
cyclicPolyPatch() [1/7]
cyclicPolyPatch (const word & name, const label size, const label start, const label index, const polyBoundaryMesh & bm, const word & patchType, const transformType transform = UNKNOWN)
Definition at line 585 of file cyclicPolyPatch.C.
cyclicPolyPatch() [2/7]
cyclicPolyPatch (const word & name, const label size, const label start, const label index, const polyBoundaryMesh & bm, const word & neighbPatchName, const transformType transform, const vector & rotationAxis, const point & rotationCentre, const vector & separationVector)
Definition at line 610 of file cyclicPolyPatch.C.
cyclicPolyPatch() [3/7]
cyclicPolyPatch (const word & name, const dictionary & dict, const label index, const polyBoundaryMesh & bm, const word & patchType)
Definition at line 638 of file cyclicPolyPatch.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, Foam::mag(), patchIdentifier::name(), word::null, coupledPolyPatch::ROTATIONAL, coupledPolyPatch::transform(), and coupledPolyPatch::TRANSLATIONAL.
cyclicPolyPatch() [4/7]
cyclicPolyPatch (const cyclicPolyPatch & pp, const polyBoundaryMesh & bm)
Definition at line 709 of file cyclicPolyPatch.C.
cyclicPolyPatch() [5/7]
cyclicPolyPatch (const cyclicPolyPatch & pp, label nbrPatchID, const labelList & faceCells)
Definition at line 730 of file cyclicPolyPatch.C.
cyclicPolyPatch() [6/7]
cyclicPolyPatch (const cyclicPolyPatch & pp, const polyBoundaryMesh & bm, const label index, const label newSize, const label newStart, const word & neighbPatchName)
Definition at line 752 of file cyclicPolyPatch.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and patchIdentifier::name().
cyclicPolyPatch() [7/7]
cyclicPolyPatch (const cyclicPolyPatch & pp, const polyBoundaryMesh & bm, const label index, const labelUList & mapAddressing, const label newStart)
Definition at line 785 of file cyclicPolyPatch.C.
~cyclicPolyPatch()
~cyclicPolyPatch () virtual
Definition at line 808 of file cyclicPolyPatch.C.
References Foam::deleteDemandDrivenData().
Member Function Documentation
calcTransforms()
void calcTransforms () protected virtual
Definition at line 71 of file cyclicPolyPatch.C.
References forAll, and UPtrList< T >::size().
initGeometry() [1/2]
void initGeometry (PstreamBuffers & pBufs) protected virtual
Implements coupledPolyPatch.
Definition at line 935 of file cyclicPolyPatch.C.
References polyPatch::initGeometry().
initGeometry() [2/2]
void initGeometry (const primitivePatch & referPatch, pointField & nbrCtrs, vectorField & nbrAreas, pointField & nbrCc) protected virtual
Definition at line 941 of file cyclicPolyPatch.C.
calcGeometry() [1/2]
void calcGeometry (PstreamBuffers & pBufs) protected virtual
Implements coupledPolyPatch.
Definition at line 973 of file cyclicPolyPatch.C.
calcGeometry() [2/2]
void calcGeometry (const primitivePatch & referPatch, const pointField & thisCtrs, const vectorField & thisAreas, const pointField & thisCc, const pointField & nbrCtrs, const vectorField & nbrAreas, const pointField & nbrCc) protected virtual
Implements coupledPolyPatch.
Definition at line 951 of file cyclicPolyPatch.C.
initMovePoints()
void initMovePoints (PstreamBuffers & pBufs, const pointField & p) protected virtual
Implements coupledPolyPatch.
Definition at line 988 of file cyclicPolyPatch.C.
References polyPatch::initMovePoints(), and p.
movePoints()
void movePoints (PstreamBuffers & pBufs, const pointField & p) protected virtual
Implements coupledPolyPatch.
Definition at line 998 of file cyclicPolyPatch.C.
References polyPatch::movePoints(), and p.
initUpdateMesh()
void initUpdateMesh (PstreamBuffers & pBufs) protected virtual
Implements coupledPolyPatch.
Definition at line 1009 of file cyclicPolyPatch.C.
References polyPatch::initUpdateMesh().
updateMesh()
void updateMesh (PstreamBuffers & pBufs) protected virtual
Implements coupledPolyPatch.
Definition at line 1015 of file cyclicPolyPatch.C.
References Foam::deleteDemandDrivenData(), and polyPatch::updateMesh().
TypeName()
TypeName ("cyclic")
clone() [1/3]
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh & bm) const inline virtual
Reimplemented from polyPatch.
Reimplemented in cyclicSlipPolyPatch, and nonuniformTransformCyclicPolyPatch.
Definition at line 267 of file cyclicPolyPatch.H.
clone() [2/3]
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh & bm, const label index, const label newSize, const label newStart) const inline virtual
Reimplemented from polyPatch.
Reimplemented in cyclicSlipPolyPatch, and nonuniformTransformCyclicPolyPatch.
Definition at line 274 of file cyclicPolyPatch.H.
References patchIdentifier::index().
clone() [3/3]
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh & bm, const label index, const labelUList & mapAddressing, const label newStart) const inline virtual
Reimplemented from polyPatch.
Reimplemented in cyclicSlipPolyPatch, and nonuniformTransformCyclicPolyPatch.
Definition at line 298 of file cyclicPolyPatch.H.
References patchIdentifier::index().
newInternalProcFaces()
virtual void newInternalProcFaces (label & newFaces, label & newProcFaces) const inline virtual
Reimplemented from polyPatch.
Definition at line 322 of file cyclicPolyPatch.H.
References cyclicPolyPatch::neighbPatch(), and UPtrList< T >::size().
nbrCells()
virtual const labelUList & nbrCells () const inline virtual
Reimplemented from polyPatch.
Definition at line 333 of file cyclicPolyPatch.H.
References cyclicPolyPatch::neighbPatch().
neighbPolyPatchID()
virtual label neighbPolyPatchID () const inline virtual
Reimplemented from polyPatch.
Definition at line 338 of file cyclicPolyPatch.H.
References cyclicPolyPatch::neighbPatchID().
mapCollocatedFaces()
virtual refPtr< labelListList > mapCollocatedFaces () const inline virtual
Reimplemented from polyPatch.
Definition at line 343 of file cyclicPolyPatch.H.
References forAll, and List< T >::setSize().
masterImplicit()
virtual bool masterImplicit () const inline virtual
Reimplemented from polyPatch.
Definition at line 357 of file cyclicPolyPatch.H.
References cyclicPolyPatch::owner().
neighbPatchName()
const Foam::word & neighbPatchName () const
Definition at line 817 of file cyclicPolyPatch.C.
References patchID.
Referenced by cyclicSlipPolyPatch::clone(), and nonuniformTransformCyclicPolyPatch::clone().
neighbPatchID()
Foam::label neighbPatchID () const virtual
Definition at line 830 of file cyclicPolyPatch.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::name(), and WarningInFunction.
Referenced by cyclicFvPatch::neighbFvPatch(), cyclicFvPatch::neighbPatch(), cyclicPointPatch::neighbPatch(), cyclicPolyPatch::neighbPatch(), cyclicFvPatch::neighbPatchID(), cyclicPolyPatch::neighbPolyPatchID(), and cyclicPolyPatch::owner().
owner()
virtual bool owner () const inline virtual
Implements coupledPolyPatch.
Definition at line 368 of file cyclicPolyPatch.H.
References patchIdentifier::index(), and cyclicPolyPatch::neighbPatchID().
Referenced by cyclicPolyPatch::masterImplicit(), cyclicPolyPatch::neighbour(), and cyclicFvPatch::owner().
neighbour()
virtual bool neighbour () const inline virtual
Reimplemented from coupledPolyPatch.
Definition at line 373 of file cyclicPolyPatch.H.
References cyclicPolyPatch::owner().
neighbPatch()
const cyclicPolyPatch & neighbPatch () const inline
Definition at line 378 of file cyclicPolyPatch.H.
References cyclicPolyPatch::neighbPatchID(), and pp().
Referenced by cyclicPolyPatch::nbrCells(), cyclicPolyPatch::newInternalProcFaces(), and cyclicPolyPatch::transformGlobalFace().
coupledPoints()
const Foam::edgeList & coupledPoints () const
Definition at line 1023 of file cyclicPolyPatch.C.
References b, Foam::endl(), forAll, mesh, OFstream::name(), Foam::name(), Foam::nl, nPoints, path(), points, Foam::Pout, List< T >::setSize(), UPtrList< T >::size(), Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
coupledEdges()
const Foam::edgeList & coupledEdges () const
Definition at line 1104 of file cyclicPolyPatch.C.
References Foam::abort(), b, Vector< Cmpt >::centre(), e, PrimitivePatch< FaceList, PointField >::edges(), Foam::endl(), PrimitivePatch< FaceList, PointField >::faceEdges(), Foam::FatalError, FatalErrorInFunction, forAll, PrimitivePatch< FaceList, PointField >::localPoints(), mesh, PrimitivePatch< FaceList, PointField >::meshPoints(), OFstream::name(), Foam::name(), Foam::nl, path(), Foam::Pout, List< T >::setSize(), UPtrList< T >::size(), Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
transformPosition() [1/2]
void transformPosition (pointField & l) const virtual
Implements coupledPolyPatch.
Definition at line 865 of file cyclicPolyPatch.C.
References forAll, s(), UPtrList< T >::size(), and Foam::transform().
transformPosition() [2/2]
void transformPosition (point & l, const label facei) const virtual
Implements coupledPolyPatch.
Definition at line 901 of file cyclicPolyPatch.C.
References s(), T, and Foam::transform().
transformGlobalFace()
label transformGlobalFace (const label facei) const inline
Definition at line 403 of file cyclicPolyPatch.H.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, patchIdentifier::name(), cyclicPolyPatch::neighbPatch(), polyPatch::offset(), and polyPatch::start().
rotationAxis()
const vector & rotationAxis () const inline
Definition at line 422 of file cyclicPolyPatch.H.
rotationCentre()
const point & rotationCentre () const inline
Definition at line 428 of file cyclicPolyPatch.H.
separationVector()
const vector & separationVector () const inline
Definition at line 434 of file cyclicPolyPatch.H.
initOrder()
void initOrder (PstreamBuffers & , const primitivePatch & pp) const virtual
Implements coupledPolyPatch.
Definition at line 1234 of file cyclicPolyPatch.C.
References PrimitivePatch< FaceList, PointField >::points(), and pp().
order()
bool order (PstreamBuffers & pBufs, const primitivePatch & pp, labelList & faceMap, labelList & rotation) const virtual
Implements coupledPolyPatch.
Definition at line 1256 of file cyclicPolyPatch.C.
References Foam::endl(), Foam::faceMap(), forAll, Foam::gAverage(), Foam::matchPoints(), mesh, Foam::name(), Foam::nl, path(), PrimitivePatch< FaceList, PointField >::points(), Foam::Pout, pp(), SeriousErrorInFunction, List< T >::setSize(), PtrList< T >::setSize(), and Foam::transform().
write()
void write (Ostream & os) const virtual
Reimplemented from coupledPolyPatch.
Definition at line 1447 of file cyclicPolyPatch.C.
References os(), Foam::transform(), Ostream::write(), coupledPolyPatch::write(), and Ostream::writeEntry().
Friends And Related Symbol Documentation
processorCyclicPolyPatch
friend class processorCyclicPolyPatch friend
Definition at line 187 of file cyclicPolyPatch.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/polyPatches/constraint/cyclic/cyclicPolyPatch.H
src/OpenFOAM/meshes/polyMesh/polyPatches/constraint/cyclic/cyclicPolyPatch.C