OpenFOAM: HuaXu Class Reference
HuaXu Class Reference
A critical heat flux (CHF) sub-cooling correlation model based on Hua-Xu (2000) for boiling flows.
#include <HuaXu.H>
Public Member Functions
TypeName ("HuaXu")
HuaXu (const dictionary &dict)
virtual ~HuaXu ()=default
virtual tmp< scalarField > CHFSubCool (const phaseModel &liquid, const phaseModel &vapor, const label patchi, const scalarField &Tl, const scalarField &Tsatw, const scalarField &L) const
virtual void write (Ostream &os) const
Public Member Functions inherited from CHFSubCoolModel
TypeName ("CHFSubCoolModel")
declareRunTimeSelectionTable (autoPtr, CHFSubCoolModel, dictionary,(const dictionary &dict),(dict))
CHFSubCoolModel ()=default
virtual ~CHFSubCoolModel ()=default
Additional Inherited Members
Static Public Member Functions inherited from CHFSubCoolModel
static autoPtr< CHFSubCoolModel > New (const dictionary &dict)
Detailed Description
A critical heat flux (CHF) sub-cooling correlation model based on Hua-Xu (2000) for boiling flows.
Reference:
    Hua, T. C., & Xu, J. J. (2000).
    Quenching boiling in subcooled liquid nitrogen
    for solidification of aqueous materials.
    Materials Science and Engineering: A, 292(2), 169-172.
    DOI:10.1016/S0921-5093(00)01004-2
Usage
Example of the model specification:
CHFSubCoolModel
{
    // Mandatory entries
    type            HuaXu;
    // Optional entries
    Kburn           <scalar>;
}
where the entries mean:
Property Description Type Reqd Deflt
type Type name: HuaXu word yes -
Kburn Burn out factor scalar no 1.5
Source files
HuaXu.H
HuaXu.C
Definition at line 98 of file HuaXu.H.
Constructor & Destructor Documentation
HuaXu()
HuaXu (const dictionary & dict)
Definition at line 49 of file HuaXu.C.
~HuaXu()
virtual ~HuaXu () virtual default
Member Function Documentation
TypeName()
TypeName ("HuaXu")
CHFSubCool()
Foam::tmp< Foam::scalarField > CHFSubCool (const phaseModel & liquid, const phaseModel & vapor, const label patchi, const scalarField & Tl, const scalarField & Tsatw, const scalarField & L) const virtual
Implements CHFSubCoolModel.
Definition at line 62 of file HuaXu.C.
References cells, Cp, liquid::Cp(), g, L, Foam::mag(), Foam::max(), Foam::pow(), Foam::pow025(), liquid::sigma(), Foam::sqrt(), and tCp.
write()
void write (Ostream & os) const virtual
Reimplemented from CHFSubCoolModel.
Definition at line 118 of file HuaXu.C.
References os(), and CHFSubCoolModel::write().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/wallBoilingSubModels/CHFSubCoolModels/HuaXu/HuaXu.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/wallBoilingSubModels/CHFSubCoolModels/HuaXu/HuaXu.C