OpenFOAM: deltaBoundary Class Reference
deltaBoundary Class Reference
Differentiation of the mesh data structure.
#include <deltaBoundary.H>
Public Member Functions
deltaBoundary (const fvMesh &mesh)
~deltaBoundary ()=default
vectorField makeFaceCentresAndAreas_d (const pointField &p, const pointField &p_d)
tensorField makeFaceCentresAndAreas_d (const pointField &p, const tensorField &p_d)
template<class pT >
pT makeCellCentres_d (const vectorField &fAreas, const vectorField &fCtrs, const Field< pT > &fAreas_d, const Field< pT > &fCtrs_d)
tmp< tensorField > cellCenters_d (const label pointI)
Protected Attributes
const fvMesh & mesh_
Detailed Description
Differentiation of the mesh data structure.
Source files
deltaBoundary.H
deltaBoundary.C
Definition at line 54 of file deltaBoundary.H.
Constructor & Destructor Documentation
deltaBoundary()
deltaBoundary (const fvMesh & mesh)
Definition at line 56 of file deltaBoundary.C.
~deltaBoundary()
~deltaBoundary () default
Member Function Documentation
makeFaceCentresAndAreas_d() [1/2]
vectorField makeFaceCentresAndAreas_d (const pointField & p, const pointField & p_d)
Definition at line 64 of file deltaBoundary.C.
References Foam::endl(), Foam::mag(), n, nPoints, p, UPtrList< T >::size(), WarningInFunction, and Foam::Zero.
Referenced by deltaBoundary::cellCenters_d(), NURBS3DVolume::computeControlPointSensitivities(), NURBS3DVolume::computeControlPointSensitivities(), NURBS3DVolume::dndbBasedSensitivities(), Bezier::dndbBasedSensitivities(), Bezier::dndbBasedSensitivities(), Bezier::dxdbFace(), and Bezier::dxdbFace().
makeFaceCentresAndAreas_d() [2/2]
tensorField makeFaceCentresAndAreas_d (const pointField & p, const tensorField & p_d)
Definition at line 171 of file deltaBoundary.C.
References Foam::endl(), Foam::mag(), n, Foam::nl, nPoints, p, UPtrList< T >::size(), Foam::sqr(), WarningInFunction, and Foam::Zero.
makeCellCentres_d()
template<class pT > pT makeCellCentres_d (const vectorField & fAreas, const vectorField & fCtrs, const Field< pT > & fAreas_d, const Field< pT > & fCtrs_d)
Definition at line 33 of file deltaBoundaryTemplates.C.
References cellVols, forAll, Foam::mag(), UPtrList< T >::size(), and Foam::Zero.
Referenced by deltaBoundary::cellCenters_d().
cellCenters_d()
tmp< tensorField > cellCenters_d (const label pointI)
Definition at line 278 of file deltaBoundary.C.
References forAll, Tensor< scalar >::I, deltaBoundary::makeCellCentres_d(), deltaBoundary::makeFaceCentresAndAreas_d(), deltaBoundary::mesh_, tmp< T >::New(), points, UPtrList< T >::size(), UList< T >::size(), and Foam::Zero.
Member Data Documentation
mesh_
const fvMesh& mesh_ protected
Definition at line 61 of file deltaBoundary.H.
Referenced by deltaBoundary::cellCenters_d().
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/deltaBoundary/deltaBoundary.H
src/optimisation/adjointOptimisation/adjoint/deltaBoundary/deltaBoundary.C
src/optimisation/adjointOptimisation/adjoint/deltaBoundary/deltaBoundaryTemplates.C