OpenFOAM: polyLine Class Reference
polyLine Class Reference
A series of straight line segments, which can also be interpreted as a series of control points for splines, etc.
#include <polyLine.H>
Public Member Functions
polyLine (const pointField &points, const bool notImplementedClosed=false)
polyLine (const point &start, const pointField &intermediate, const point &end, const bool notImplementedClosed=false)
const pointField & points () const noexcept
label nSegments () const noexcept
point position (const scalar) const
point position (const label segment, const scalar) const
scalar length () const noexcept
Static Public Member Functions
static tmp< pointField > concat (const point &start, const pointField &intermediate, const point &end)
Protected Member Functions
void calcParam ()
label localParameter (scalar &lambda) const
Protected Attributes
pointField points_
scalar lineLength_
scalarList param_
Detailed Description
A series of straight line segments, which can also be interpreted as a series of control points for splines, etc.
A future implementation could also handle a closed polyLine.
Source files
polyLine.H
polyLine.C
Definition at line 51 of file polyLine.H.
Constructor & Destructor Documentation
polyLine() [1/2]
polyLine (const pointField & points, const bool notImplementedClosed = false) explicit
Parameters
points The poly-line points
Definition at line 77 of file polyLine.C.
References polyLine::calcParam().
polyLine() [2/2]
polyLine (const point & start, const pointField & intermediate, const point & end, const bool notImplementedClosed = false)
Parameters
start The start point
intermediate The intermediate points
end The end point
Definition at line 87 of file polyLine.C.
References polyLine::calcParam().
Member Function Documentation
calcParam()
void calcParam () protected
Definition at line 50 of file polyLine.C.
References Foam::mag(), PtrList< T >::resize(), and UPtrList< T >::size().
Referenced by polyLine::polyLine(), and polyLine::polyLine().
localParameter()
Foam::label localParameter (scalar & lambda) const protected
Definition at line 117 of file polyLine.C.
References lambda().
concat()
Foam::tmp< Foam::pointField > concat (const point & start, const pointField & intermediate, const point & end) static
Parameters
start The start point
intermediate The intermediate points
end The end point
Definition at line 27 of file polyLine.C.
References UPtrList< T >::first(), tmp< T >::New(), p0, and UPtrList< T >::size().
Referenced by blockEdge::appendEndPoints().
points()
const Foam::pointField & points () const noexcept
Definition at line 105 of file polyLine.C.
nSegments()
Foam::label nSegments () const noexcept
Definition at line 111 of file polyLine.C.
References UPtrList< T >::size().
position() [1/2]
Foam::point position (const scalar mu) const
Definition at line 151 of file polyLine.C.
References lambda(), and mu.
Referenced by polyLineEdge::position().
position() [2/2]
Foam::point position (const label segment, const scalar mu) const
Definition at line 169 of file polyLine.C.
References mu, and p0.
length()
Foam::scalar length () const noexcept
Definition at line 203 of file polyLine.C.
Member Data Documentation
points_
pointField points_ protected
Definition at line 58 of file polyLine.H.
lineLength_
scalar lineLength_ protected
Definition at line 61 of file polyLine.H.
Referenced by polyLineEdge::length().
param_
scalarList param_ protected
Definition at line 64 of file polyLine.H.
The documentation for this class was generated from the following files:
src/mesh/blockMesh/blockEdges/polyLineEdge/polyLine.H
src/mesh/blockMesh/blockEdges/polyLineEdge/polyLine.C