OpenFOAM: primitiveMeshTools Class Reference
primitiveMeshTools Class Reference
Collection of static functions operating on primitiveMesh (mainly checks).
#include <primitiveMeshTools.H>
Static Public Member Functions
static void updateFaceCentresAndAreas (const primitiveMesh &mesh, const UList< label > &faceIDs, const pointField &p, vectorField &fCtrs, vectorField &fAreas)
static void updateCellCentresAndVols (const primitiveMesh &mesh, const vectorField &fCtrs, const vectorField &fAreas, const List< label > &cellIDs, const List< cell > &cells, vectorField &cellCtrs_s, scalarField &cellVols_s)
static void makeFaceCentresAndAreas (const UList< face > &faces, const pointField &p, vectorField &fCtrs, vectorField &fAreas)
static void makeFaceCentresAndAreas (const primitiveMesh &mesh, const pointField &p, vectorField &fCtrs, vectorField &fAreas)
static void makeCellCentresAndVols (const primitiveMesh &mesh, const vectorField &fCtrs, const vectorField &fAreas, vectorField &cellCtrs, scalarField &cellVols)
static tmp< scalarField > faceOrthogonality (const primitiveMesh &mesh, const vectorField &fAreas, const vectorField &cellCtrs)
static void facePyramidVolume (const primitiveMesh &mesh, const pointField &points, const vectorField &cellCtrs, scalarField &ownPyrVol, scalarField &neiPyrVol)
static tmp< scalarField > faceSkewness (const primitiveMesh &mesh, const pointField &points, const vectorField &fCtrs, const vectorField &fAreas, const vectorField &cellCtrs)
static void cellClosedness (const primitiveMesh &mesh, const Vector< label > &meshD, const vectorField &areas, const scalarField &vols, scalarField &openness, scalarField &aratio)
static tmp< scalarField > faceConcavity (const scalar maxSin, const primitiveMesh &mesh, const pointField &p, const vectorField &faceAreas)
static tmp< scalarField > faceFlatness (const primitiveMesh &mesh, const pointField &p, const vectorField &fCtrs, const vectorField &faceAreas)
static tmp< scalarField > edgeAlignment (const primitiveMesh &mesh, const Vector< label > &directions, const pointField &p)
static tmp< scalarField > cellDeterminant (const primitiveMesh &mesh, const Vector< label > &directions, const vectorField &faceAreas, const bitSet &internalOrCoupledFace)
static scalar faceSkewness (const UList< face > &faces, const pointField &p, const vectorField &fCtrs, const vectorField &fAreas, const label facei, const point &ownCc, const point &neiCc)
static scalar boundaryFaceSkewness (const UList< face > &faces, const pointField &p, const vectorField &fCtrs, const vectorField &fAreas, const label facei, const point &ownCc)
static scalar faceSkewness (const primitiveMesh &mesh, const pointField &p, const vectorField &fCtrs, const vectorField &fAreas, const label facei, const point &ownCc, const point &neiCc)
static scalar boundaryFaceSkewness (const primitiveMesh &mesh, const pointField &p, const vectorField &fCtrs, const vectorField &fAreas, const label facei, const point &ownCc)
static scalar faceOrthogonality (const point &ownCc, const point &neiCc, const vector &s)
Detailed Description
Collection of static functions operating on primitiveMesh (mainly checks).
Source files
primitiveMeshTools.H
primitiveMeshTools.C
Definition at line 54 of file primitiveMeshTools.H.
Member Function Documentation
updateFaceCentresAndAreas()
void updateFaceCentresAndAreas (const primitiveMesh & mesh, const UList< label > & faceIDs, const pointField & p, vectorField & fCtrs, vectorField & fAreas) static
Definition at line 31 of file primitiveMeshTools.C.
References triangle< Point, PointRef >::areaNormal(), triangle< Point, PointRef >::centre(), f(), Foam::mag(), mesh, n, nPoints, p, UPtrList< T >::size(), and Foam::Zero.
Referenced by solidBodyFvGeometryScheme::movePoints().
updateCellCentresAndVols()
void updateCellCentresAndVols (const primitiveMesh & mesh, const vectorField & fCtrs, const vectorField & fAreas, const List< label > & cellIDs, const List< cell > & cells, vectorField & cellCtrs_s, scalarField & cellVols_s) static
Definition at line 101 of file primitiveMeshTools.C.
References cellIDs, cells, primitiveMesh::cells(), cellVols, polyMesh::faceOwner(), forAll, Foam::mag(), mesh, UList< T >::size(), and Foam::Zero.
Referenced by solidBodyFvGeometryScheme::movePoints(), and cyclicACMIPolyPatch::scalePatchFaceAreas().
makeFaceCentresAndAreas() [1/2]
void makeFaceCentresAndAreas (const UList< face > & faces, const pointField & p, vectorField & fCtrs, vectorField & fAreas) static
Parameters
faces The faces to consider
p Support points for faces
[out] fCtrs The face centres
[out] fAreas The face area normals
Definition at line 197 of file primitiveMeshTools.C.
References triangle< Point, PointRef >::areaNormal(), triangle< Point, PointRef >::centre(), f(), forAll, Foam::mag(), n, nPoints, p, UPtrList< T >::size(), UList< T >::size(), and Foam::Zero.
Referenced by primitiveMesh::calcFaceCentresAndAreas(), and polyMesh::checkMeshMotion().
makeFaceCentresAndAreas() [2/2]
void makeFaceCentresAndAreas (const primitiveMesh & mesh, const pointField & p, vectorField & fCtrs, vectorField & fAreas) static
Parameters
mesh The mesh faces
p Support points for faces
[out] fCtrs The face centres
[out] fAreas The face area normals
Definition at line 265 of file primitiveMeshTools.C.
References polyMesh::faces(), mesh, and p.
makeCellCentresAndVols()
void makeCellCentresAndVols (const primitiveMesh & mesh, const vectorField & fCtrs, const vectorField & fAreas, vectorField & cellCtrs, scalarField & cellVols) static
Definition at line 277 of file primitiveMeshTools.C.
References cellVols, polyMesh::faceNeighbour(), polyMesh::faceOwner(), forAll, Foam::mag(), mesh, primitiveMesh::nCells(), and Foam::Zero.
Referenced by primitiveMesh::calcCellCentresAndVols(), polyMesh::checkMeshMotion(), and stabilisedFvGeometryScheme::movePoints().
faceOrthogonality() [1/2]
Foam::tmp< Foam::scalarField > faceOrthogonality (const primitiveMesh & mesh, const vectorField & fAreas, const vectorField & cellCtrs) static
Definition at line 494 of file primitiveMeshTools.C.
References polyMesh::faceNeighbour(), polyMesh::faceOwner(), forAll, mesh, tmp< T >::New(), and primitiveMesh::nInternalFaces().
Referenced by primitiveMesh::checkFaceOrthogonality(), and polyMeshTools::faceOrthogonality().
facePyramidVolume()
void facePyramidVolume (const primitiveMesh & mesh, const pointField & points, const vectorField & cellCtrs, scalarField & ownPyrVol, scalarField & neiPyrVol) static
Definition at line 575 of file primitiveMeshTools.C.
References f(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), polyMesh::faces(), forAll, primitiveMesh::isInternalFace(), mesh, primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), points, and PtrList< T >::setSize().
Referenced by primitiveMesh::checkFacePyramids().
faceSkewness() [1/3]
Foam::tmp< Foam::scalarField > faceSkewness (const primitiveMesh & mesh, const pointField & points, const vectorField & fCtrs, const vectorField & fAreas, const vectorField & cellCtrs) static
Definition at line 522 of file primitiveMeshTools.C.
References polyMesh::faceNeighbour(), polyMesh::faceOwner(), polyMesh::faces(), mesh, tmp< T >::New(), primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), p, and Foam::skew().
Referenced by polyMeshGeometry::checkFaceSkewness(), primitiveMesh::checkFaceSkewness(), and polyMeshTools::faceSkewness().
cellClosedness()
void cellClosedness (const primitiveMesh & mesh, const Vector< label > & meshD, const vectorField & areas, const scalarField & vols, scalarField & openness, scalarField & aratio) static
Definition at line 614 of file primitiveMeshTools.C.
References Foam::cmptMag(), Foam::cmptSum(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), forAll, Foam::mag(), Foam::max(), mesh, Foam::min(), primitiveMesh::nCells(), VectorSpace< Form, Cmpt, Ncmpts >::nComponents, Foam::pow(), PtrList< T >::setSize(), and Foam::Zero.
Referenced by primitiveMesh::checkClosedCells().
faceConcavity()
Foam::tmp< Foam::scalarField > faceConcavity (const scalar maxSin, const primitiveMesh & mesh, const pointField & p, const vectorField & faceAreas) static
Definition at line 708 of file primitiveMeshTools.C.
References f(), polyMesh::faces(), UList< T >::first(), forAll, UList< T >::last(), Foam::mag(), Foam::max(), mesh, tmp< T >::New(), primitiveMesh::nFaces(), and p.
Referenced by primitiveMesh::checkFaceAngles().
faceFlatness()
Foam::tmp< Foam::scalarField > faceFlatness (const primitiveMesh & mesh, const pointField & p, const vectorField & fCtrs, const vectorField & faceAreas) static
Definition at line 774 of file primitiveMeshTools.C.
References f(), polyMesh::faces(), forAll, Foam::mag(), mesh, n, tmp< T >::New(), primitiveMesh::nFaces(), p, and UList< T >::size().
Referenced by primitiveMesh::checkFaceFlatness().
edgeAlignment()
static tmp< scalarField > edgeAlignment (const primitiveMesh & mesh, const Vector< label > & directions, const pointField & p) static
cellDeterminant()
Foam::tmp< Foam::scalarField > cellDeterminant (const primitiveMesh & mesh, const Vector< label > & directions, const vectorField & faceAreas, const bitSet & internalOrCoupledFace) static
Definition at line 822 of file primitiveMeshTools.C.
References primitiveMesh::cells(), Foam::det(), forAll, Foam::mag(), mesh, primitiveMesh::nCells(), VectorSpace< Form, Cmpt, Ncmpts >::nComponents, tmp< T >::New(), Foam::sqr(), UPtrList< T >::test(), and Foam::Zero.
faceSkewness() [2/3]
Foam::scalar faceSkewness (const UList< face > & faces, const pointField & p, const vectorField & fCtrs, const vectorField & fAreas, const label facei, const point & ownCc, const point & neiCc) static
Parameters
faces The faces to consider
p Support points for faces
Definition at line 373 of file primitiveMeshTools.C.
References f(), forAll, Foam::mag(), Foam::max(), and p.
boundaryFaceSkewness() [1/2]
Foam::scalar boundaryFaceSkewness (const UList< face > & faces, const pointField & p, const vectorField & fCtrs, const vectorField & fAreas, const label facei, const point & ownCc) static
Parameters
faces The faces to consider
p Support points for faces
Definition at line 410 of file primitiveMeshTools.C.
References f(), forAll, Foam::mag(), Foam::max(), Foam::normalised(), and p.
Referenced by polyMeshGeometry::checkFaceSkewness(), and polyMeshTools::faceSkewness().
faceSkewness() [3/3]
Foam::scalar faceSkewness (const primitiveMesh & mesh, const pointField & p, const vectorField & fCtrs, const vectorField & fAreas, const label facei, const point & ownCc, const point & neiCc) static
Parameters
mesh The mesh faces
p Support points for faces
Definition at line 448 of file primitiveMeshTools.C.
References polyMesh::faces(), mesh, and p.
boundaryFaceSkewness() [2/2]
Foam::scalar boundaryFaceSkewness (const primitiveMesh & mesh, const pointField & p, const vectorField & fCtrs, const vectorField & fAreas, const label facei, const point & ownCc) static
Parameters
mesh The mesh faces
p Support points for faces
Definition at line 464 of file primitiveMeshTools.C.
References polyMesh::faces(), mesh, and p.
faceOrthogonality() [2/2]
Foam::scalar faceOrthogonality (const point & ownCc, const point & neiCc, const vector & s) static
Definition at line 479 of file primitiveMeshTools.C.
References Foam::mag(), and s().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshCheck/primitiveMeshTools.H
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshCheck/primitiveMeshTools.C