OpenFOAM: FreeStream< CloudType > Class Template Reference
FreeStream< CloudType > Class Template Reference
Inserting new particles across the faces of a all patched of type "patch" for a free stream. Uniform values number density, temperature and velocity sourced face-by-face from the boundaryT and boundaryU fields of the cloud.
#include <FreeStream.H>
Public Member Functions
TypeName ("FreeStream")
FreeStream (const dictionary &dict, CloudType &cloud)
virtual ~FreeStream ()
virtual void autoMap (const mapPolyMesh &)
virtual void inflow ()
Public Member Functions inherited from InflowBoundaryModel< CloudType >
TypeName ("InflowBoundaryModel")
declareRunTimeSelectionTable (autoPtr, InflowBoundaryModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
InflowBoundaryModel (CloudType &owner)
InflowBoundaryModel (const dictionary &dict, CloudType &owner, const word &type)
virtual ~InflowBoundaryModel ()
const CloudType & owner () const
CloudType & owner ()
const dictionary & dict () const
const dictionary & coeffDict () const
Additional Inherited Members
Static Public Member Functions inherited from InflowBoundaryModel< CloudType >
static autoPtr< InflowBoundaryModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Detailed Description
template<class CloudType>
class Foam::FreeStream< CloudType >
Inserting new particles across the faces of a all patched of type "patch" for a free stream. Uniform values number density, temperature and velocity sourced face-by-face from the boundaryT and boundaryU fields of the cloud.
Definition at line 45 of file FreeStream.H.
Constructor & Destructor Documentation
FreeStream()
template<class CloudType > FreeStream (const dictionary & dict, CloudType & cloud)
Definition at line 31 of file FreeStream.C.
References Foam::abort(), InflowBoundaryModel< CloudType >::coeffDict(), Foam::FatalError, FatalErrorInFunction, HashTable< T, Key, Hash >::find(), forAll, UPtrList< T >::get(), Foam::nl, p, patches, List< T >::setSize(), PtrList< T >::setSize(), UPtrList< T >::size(), UList< T >::size(), List< T >::transfer(), and Foam::Zero.
~FreeStream()
template<class CloudType > ~FreeStream () virtual
Definition at line 106 of file FreeStream.C.
Member Function Documentation
TypeName()
template<class CloudType > TypeName ("FreeStream< CloudType >")
autoMap()
template<class CloudType > void autoMap (const mapPolyMesh & mapper) virtual
Reimplemented from InflowBoundaryModel< CloudType >.
Definition at line 113 of file FreeStream.C.
References polyMesh::boundaryMesh(), forAll, mesh, p, PtrList< T >::setSize(), and UPtrList< T >::size().
inflow()
template<class CloudType > void inflow () virtual
Implements InflowBoundaryModel< CloudType >.
Definition at line 134 of file FreeStream.C.
References Foam::abort(), polyMesh::boundaryMesh(), Foam::endl(), Foam::erf(), Foam::exp(), f(), polyMesh::faceOwner(), polyMeshTetDecomposition::faceTetIndices(), Foam::FatalError, FatalErrorInFunction, forAll, Random::GaussNormal(), Foam::Info, UPtrList< T >::last(), Foam::mag(), Foam::max(), mesh, Foam::min(), n, Foam::nl, Foam::normalised(), p, Foam::constant::mathematical::pi(), polyMesh::points(), Foam::returnReduce(), rndGen, Random::sample01(), UPtrList< T >::size(), Foam::sqr(), Foam::sqrt(), fvMesh::time(), U, and Foam::Zero.
The documentation for this class was generated from the following files:
src/lagrangian/DSMC/submodels/InflowBoundaryModel/FreeStream/FreeStream.H
src/lagrangian/DSMC/submodels/InflowBoundaryModel/FreeStream/FreeStream.C