OpenFOAM: layerAdditionRemoval Class Reference
layerAdditionRemoval Class Reference
Cell layer addition mesh modifier.
#include <layerAdditionRemoval.H>
Public Member Functions
TypeName ("layerAdditionRemoval")
layerAdditionRemoval (const word &name, const label index, const polyTopoChanger &ptc, const word &zoneName, const scalar minThickness, const scalar maxThickness, const bool thicknessFromVolume=true)
layerAdditionRemoval (const word &name, const dictionary &dict, const label index, const polyTopoChanger &ptc)
virtual ~layerAdditionRemoval ()=default
virtual bool changeTopology () const
virtual void setRefinement (polyTopoChange &) const
virtual void modifyMotionPoints (pointField &motionPoints) const
virtual void updateMesh (const mapPolyMesh &)
scalar minLayerThickness () const
void setMinLayerThickness (const scalar t) const
scalar maxLayerThickness () const
void setMaxLayerThickness (const scalar t) const
virtual void write (Ostream &) const
virtual void writeDict (Ostream &) const
Public Member Functions inherited from polyMeshModifier
TypeName ("meshModifier")
declareRunTimeSelectionTable (autoPtr, polyMeshModifier, dictionary,(const word &name, const dictionary &dict, const label index, const polyTopoChanger &mme),(name, dict, index, mme))
polyMeshModifier (const word &name, const label index, const polyTopoChanger &mme, const bool act)
virtual ~polyMeshModifier ()=default
const word & name () const
label index () const
const polyTopoChanger & topoChanger () const
Switch active () const
void enable () const
void disable () const
Additional Inherited Members
Static Public Member Functions inherited from polyMeshModifier
static autoPtr< polyMeshModifier > New (const word &name, const dictionary &dict, const label index, const polyTopoChanger &mme)
Detailed Description
Cell layer addition mesh modifier.
Source files
layerAdditionRemoval.H
layerAdditionRemoval.C
addCellLayer.C
removeCellLayer.C
Definition at line 51 of file layerAdditionRemoval.H.
Constructor & Destructor Documentation
layerAdditionRemoval() [1/2]
layerAdditionRemoval (const word & name, const label index, const polyTopoChanger & ptc, const word & zoneName, const scalar minThickness, const scalar maxThickness, const bool thicknessFromVolume = true)
Definition at line 102 of file layerAdditionRemoval.C.
layerAdditionRemoval() [2/2]
layerAdditionRemoval (const word & name, const dictionary & dict, const label index, const polyTopoChanger & ptc)
Definition at line 128 of file layerAdditionRemoval.C.
~layerAdditionRemoval()
virtual ~layerAdditionRemoval () virtual default
Member Function Documentation
TypeName()
TypeName ("layerAdditionRemoval")
changeTopology()
bool changeTopology () const virtual
Implements polyMeshModifier.
Definition at line 153 of file layerAdditionRemoval.C.
References Foam::abort(), primitiveMesh::cells(), primitiveMesh::cellVolumes(), e, Foam::endl(), primitiveMesh::faceAreas(), polyMesh::faces(), polyMesh::faceZones(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::mag(), Foam::max(), mesh, Foam::min(), Foam::name(), Foam::nl, polyMesh::points(), Foam::Pout, Foam::reduce(), UPtrList< T >::size(), and fvMesh::time().
setRefinement()
void setRefinement (polyTopoChange & ref) const virtual
Implements polyMeshModifier.
Definition at line 351 of file layerAdditionRemoval.C.
References Foam::endl(), mesh, Foam::name(), Foam::Pout, ref(), and timeIndex.
modifyMotionPoints()
void modifyMotionPoints (pointField & motionPoints) const virtual
Implements polyMeshModifier.
Definition at line 206 of file setLayerPairing.C.
References Foam::endl(), Foam::name(), and Foam::Pout.
updateMesh()
void updateMesh (const mapPolyMesh &) virtual
Implements polyMeshModifier.
Definition at line 390 of file layerAdditionRemoval.C.
References Foam::endl(), mesh, Foam::name(), and Foam::Pout.
minLayerThickness()
scalar minLayerThickness () const inline
Definition at line 189 of file layerAdditionRemoval.H.
setMinLayerThickness()
void setMinLayerThickness (const scalar t) const
Definition at line 415 of file layerAdditionRemoval.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
maxLayerThickness()
scalar maxLayerThickness () const inline
Definition at line 198 of file layerAdditionRemoval.H.
setMaxLayerThickness()
void setMaxLayerThickness (const scalar t) const
Definition at line 428 of file layerAdditionRemoval.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
write()
void write (Ostream & os) const virtual
Implements polyMeshModifier.
Definition at line 441 of file layerAdditionRemoval.C.
References Foam::endl(), Foam::name(), Foam::nl, os(), and Foam::type().
writeDict()
void writeDict (Ostream & os) const virtual
Implements polyMeshModifier.
Definition at line 453 of file layerAdditionRemoval.C.
References token::BEGIN_BLOCK, token::END_BLOCK, token::END_STATEMENT, Foam::endl(), Foam::name(), Foam::nl, os(), and Foam::type().
The documentation for this class was generated from the following files:
src/dynamicMesh/layerAdditionRemoval/layerAdditionRemoval.H
src/dynamicMesh/layerAdditionRemoval/addCellLayer.C
src/dynamicMesh/layerAdditionRemoval/layerAdditionRemoval.C
src/dynamicMesh/layerAdditionRemoval/removeCellLayer.C
src/dynamicMesh/layerAdditionRemoval/setLayerPairing.C