OpenFOAM: GAMGSolver Class Reference
GAMGSolver Class Reference
Numerics » Matrix manipulation and solvers » Solvers
Geometric agglomerated algebraic multigrid solver.
#include <GAMGSolver.H>
Public Member Functions
TypeName ("GAMG")
GAMGSolver (const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces, const dictionary &solverControls)
virtual ~GAMGSolver ()
virtual solverPerformance solve (scalarField &psi, const scalarField &source, const direction cmpt=0) const
Public Member Functions inherited from lduMatrix::solver
virtual const word & type () const =0
declareRunTimeSelectionTable (autoPtr, solver, symMatrix,(const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces, const dictionary &solverControls),(fieldName, matrix, interfaceBouCoeffs, interfaceIntCoeffs, interfaces, solverControls))
declareRunTimeSelectionTable (autoPtr, solver, asymMatrix,(const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces, const dictionary &solverControls),(fieldName, matrix, interfaceBouCoeffs, interfaceIntCoeffs, interfaces, solverControls))
solver (const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces, const dictionary &solverControls)
virtual ~solver ()=default
const word & fieldName () const noexcept
const lduMatrix & matrix () const noexcept
const FieldField< Field, scalar > & interfaceBouCoeffs () const noexcept
const FieldField< Field, scalar > & interfaceIntCoeffs () const noexcept
const lduInterfaceFieldPtrsList & interfaces () const noexcept
virtual void read (const dictionary &)
virtual solverPerformance scalarSolve (solveScalarField &psi, const solveScalarField &source, const direction cmpt=0) const
solveScalarField::cmptType normFactor (const solveScalarField &psi, const solveScalarField &source, const solveScalarField &Apsi, solveScalarField &tmpField, const lduMatrix::normTypes normType) const
solveScalarField::cmptType normFactor (const solveScalarField &psi, const solveScalarField &source, const solveScalarField &Apsi, solveScalarField &tmpField) const
Friends
class GAMGPreconditioner
Additional Inherited Members
Static Public Member Functions inherited from lduMatrix::solver
static autoPtr< solver > New (const word &solverName, const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces, const dictionary &solverControls)
static autoPtr< solver > New (const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces, const dictionary &solverControls)
Protected Attributes inherited from lduMatrix::solver
word fieldName_
const lduMatrix & matrix_
const FieldField< Field, scalar > & interfaceBouCoeffs_
const FieldField< Field, scalar > & interfaceIntCoeffs_
lduInterfaceFieldPtrsList interfaces_
dictionary controlDict_
int log_
label minIter_
label maxIter_
lduMatrix::normTypes normType_
scalar tolerance_
scalar relTol_
profilingTrigger profiling_
Detailed Description
Geometric agglomerated algebraic multigrid solver.
Characteristics:
Requires positive definite, diagonally dominant matrix.
Agglomeration algorithm: selectable and optionally cached.
Restriction operator: summation.
Prolongation operator: injection.
Smoother: Gauss-Seidel.
Coarse matrix creation: central coefficient: summation of fine grid central coefficients with the removal of intra-cluster face; off-diagonal coefficient: summation of off-diagonal faces.
Coarse matrix scaling: performed by correction scaling, using steepest descent optimisation.
Type of cycle: V-cycle with optional pre-smoothing.
Coarsest-level matrix solved using PCG or PBiCGStab.
Source files
GAMGSolver.H
GAMGSolver.C
GAMGSolverAgglomerateMatrix.C
GAMGSolverInterpolate.C
GAMGSolverScale.C
GAMGSolverSolve.C
Definition at line 71 of file GAMGSolver.H.
Constructor & Destructor Documentation
GAMGSolver()
GAMGSolver (const word & fieldName, const lduMatrix & matrix, const FieldField< Field, scalar > & interfaceBouCoeffs, const FieldField< Field, scalar > & interfaceIntCoeffs, const lduInterfaceFieldPtrsList & interfaces, const dictionary & solverControls)
Definition at line 43 of file GAMGSolver.C.
References lduMatrix::solver::controlDict_, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, dictionary::findEntry(), forAll, lduMatrix::solver::interfaces(), keyType::LITERAL_RECURSIVE, lduMatrix::solver::log_, lduMatrix::solver::matrix(), GAMGInterface::New(), Foam::New(), lduMatrix::solver::New(), Foam::nl, os(), Foam::Pout, lduMatrix::solver::relTol_, PtrList< T >::set(), UPtrList< T >::size(), lduMatrix::solver::tolerance_, and lduMatrix::solver::type().
~GAMGSolver()
~GAMGSolver () virtual
Definition at line 331 of file GAMGSolver.C.
Member Function Documentation
TypeName()
TypeName ("GAMG")
solve()
Foam::solverPerformance solve (scalarField & psi, const scalarField & source, const direction cmpt = 0) const virtual
Implements lduMatrix::solver.
Definition at line 29 of file GAMGSolverSolve.C.
References Foam::endl(), lduMatrix::solver::fieldName_, Foam::gSumMag(), Foam::Info, lduMatrix::solver::interfaceBouCoeffs_, lduMatrix::solver::interfaces_, lduMatrix::solver::log_, messageStream::masterStream(), lduMatrix::solver::matrix(), lduMatrix::solver::matrix_, lduMatrix::solver::maxIter_, mesh, lduMatrix::solver::minIter_, lduMatrix::solver::normFactor(), Foam::Pout, psi, lduMatrix::solver::relTol_, UPtrList< T >::size(), and lduMatrix::solver::tolerance_.
Friends And Related Symbol Documentation
GAMGPreconditioner
friend class GAMGPreconditioner friend
Definition at line 325 of file GAMGSolver.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/GAMGSolver.H
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/GAMGSolver.C
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/GAMGSolverAgglomerateMatrix.C
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/GAMGSolverInterpolate.C
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/GAMGSolverScale.C
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/GAMGSolverSolve.C