OpenFOAM: wallPointAddressing Class Reference
wallPointAddressing Class Reference
Holds information (coordinate and origin) regarding nearest wall point.
#include <wallPointAddressing.H>
Public Member Functions
wallPointAddressing ()
wallPointAddressing (const point &origin, const labelPair &data, const scalar distSqr)
const labelPair & data () const
labelPair & data ()
template<class TrackingData >
void leaveDomain (const polyMesh &, const polyPatch &, const label patchFacei, const point &faceCentre, TrackingData &td)
template<class TrackingData >
bool updateCell (const polyMesh &mesh, const label thisCelli, const label neighbourFacei, const wallPointAddressing &neighbourWallInfo, const scalar tol, TrackingData &td)
template<class TrackingData >
bool updateFace (const polyMesh &mesh, const label thisFacei, const label neighbourCelli, const wallPointAddressing &neighbourWallInfo, const scalar tol, TrackingData &td)
template<class TrackingData >
bool updateFace (const polyMesh &mesh, const label thisFacei, const wallPointAddressing &neighbourWallInfo, const scalar tol, TrackingData &td)
Public Member Functions inherited from wallPoint
wallPoint ()
wallPoint (const point &origin, const scalar distSqr)
const point & origin () const
point & origin ()
scalar distSqr () const
scalar & distSqr ()
template<class TrackingData >
bool valid (TrackingData &td) const
template<class TrackingData >
bool sameGeometry (const polyMesh &, const wallPoint &, const scalar, TrackingData &td) const
template<class TrackingData >
void leaveDomain (const polyMesh &, const polyPatch &, const label patchFacei, const point &faceCentre, TrackingData &td)
template<class TrackingData >
void enterDomain (const polyMesh &, const polyPatch &, const label patchFacei, const point &faceCentre, TrackingData &td)
template<class TrackingData >
void transform (const polyMesh &, const tensor &, TrackingData &td)
template<class TrackingData >
bool updateCell (const polyMesh &, const label thisCelli, const label neighbourFacei, const wallPoint &neighbourInfo, const scalar tol, TrackingData &td)
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFacei, const label neighbourCelli, const wallPoint &neighbourInfo, const scalar tol, TrackingData &td)
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFacei, const wallPoint &neighbourInfo, const scalar tol, TrackingData &td)
template<class TrackingData >
bool equal (const wallPoint &, TrackingData &td) const
bool operator== (const wallPoint &) const
bool operator!= (const wallPoint &) const
Friends
Ostream & operator<< (Ostream &, const wallPointAddressing &)
Istream & operator>> (Istream &, wallPointAddressing &)
Detailed Description
Holds information (coordinate and origin) regarding nearest wall point.
Is like wallPoint but transfer extra (passive) data. Used e.g. in wall distance calculation with wall reflection vectors.
Source files
wallPointAddressing.H
wallPointAddressingI.H
wallPointAddressing.C
Definition at line 58 of file wallPointAddressing.H.
Constructor & Destructor Documentation
wallPointAddressing() [1/2]
wallPointAddressing () inline
Definition at line 85 of file wallPointAddressingI.H.
wallPointAddressing() [2/2]
wallPointAddressing (const point & origin, const labelPair & data, const scalar distSqr) inline
Definition at line 92 of file wallPointAddressingI.H.
Member Function Documentation
data() [1/2]
const labelPair & data () const inline
Definition at line 106 of file wallPointAddressing.H.
data() [2/2]
labelPair & data () inline
Definition at line 110 of file wallPointAddressing.H.
leaveDomain()
template<class TrackingData > void leaveDomain (const polyMesh & mesh, const polyPatch & pp, const label patchFacei, const point & faceCentre, TrackingData & td) inline
Definition at line 107 of file wallPointAddressingI.H.
References polyMesh::globalData(), wallPoint::leaveDomain(), mesh, and pp().
updateCell()
template<class TrackingData > bool updateCell (const polyMesh & mesh, const label thisCelli, const label neighbourFacei, const wallPointAddressing & neighbourWallInfo, const scalar tol, TrackingData & td) inline
Definition at line 157 of file wallPointAddressingI.H.
References polyMesh::globalData(), mesh, and update().
updateFace() [1/2]
template<class TrackingData > bool updateFace (const polyMesh & mesh, const label thisFacei, const label neighbourCelli, const wallPointAddressing & neighbourWallInfo, const scalar tol, TrackingData & td) inline
Definition at line 183 of file wallPointAddressingI.H.
References primitiveMesh::faceCentres(), polyMesh::globalData(), mesh, and update().
updateFace() [2/2]
template<class TrackingData > bool updateFace (const polyMesh & mesh, const label thisFacei, const wallPointAddressing & neighbourWallInfo, const scalar tol, TrackingData & td) inline
Definition at line 209 of file wallPointAddressingI.H.
References primitiveMesh::faceCentres(), polyMesh::globalData(), mesh, and update().
Friends And Related Symbol Documentation
operator<<
Ostream & operator<< (Ostream & , const wallPointAddressing &) friend
operator>>
Istream & operator>> (Istream & , wallPointAddressing &) friend
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/wallDist/wallDistAddressing/wallPointAddressing.H
src/finiteVolume/fvMesh/wallDist/wallDistAddressing/wallPointAddressingI.H