OpenFOAM: noiseModel Class Reference
noiseModel Class Reference abstract
Base class for noise models.
#include <noiseModel.H>
Classes
struct octaveBandInfo
struct planInfo
Public Types
enum class weightingType {
none , dBA , dBB , dBC ,
dBD
}
Public Member Functions
TypeName ("noiseModel")
declareRunTimeSelectionTable (autoPtr, noiseModel, dictionary,(const dictionary &dict, const objectRegistry &obr),(dict, obr))
noiseModel (const noiseModel &)=delete
void operator= (const noiseModel &)=delete
noiseModel (const dictionary &dict, const objectRegistry &obr, const word &name, const bool readFields=true)
virtual ~noiseModel ()=default
virtual bool read (const dictionary &dict)
virtual void calculate ()=0
tmp< Foam::scalarField > PSD (const scalarField &PSDf) const
tmp< scalarField > SPL (const scalarField &Prms2, const scalar f) const
tmp< scalarField > SPL (const scalarField &Prms2, const scalarField &f) const
void cleanFFTW ()
void writeWeightings () const
Public Member Functions inherited from writeFile
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name="undefined", const bool writeToFile=true)
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name, const dictionary &dict, const bool writeToFile=true)
writeFile (const writeFile &wf)
virtual ~writeFile ()=default
virtual OFstream & file ()
virtual bool writeToFile () const
virtual bool canWriteToFile () const
virtual bool canResetFile () const
virtual bool canWriteHeader () const
virtual label charWidth () const
virtual void writeCommented (Ostream &os, const string &str) const
virtual void writeTabbed (Ostream &os, const string &str) const
virtual void writeHeader (Ostream &os, const string &str) const
virtual void writeCurrentTime (Ostream &os) const
virtual void writeBreak (Ostream &os) const
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
template<class Type >
void writeValue (Ostream &os, const Type &val) const
Static Public Member Functions
static autoPtr< noiseModel > New (const dictionary &dict, const objectRegistry &obr)
Static Public Attributes
static const Enum< weightingType > weightingTypeNames_
Static Public Attributes inherited from writeFile
static label addChars = 8
Protected Member Functions
scalar checkUniformTimeStep (const scalarList &times) const
bool validateBounds (const scalarList &p) const
fileName baseFileDir (const label dataseti) const
void writeFileHeader (Ostream &os, const string &x, const string &y, const UList< Tuple2< string, token > > &headerValues=UList< Tuple2< string, token > >::null()) const
void writeFreqDataToFile (Ostream &os, const scalarField &f, const scalarField &fx) const
tmp< scalarField > uniformFrequencies (const scalar deltaT, const bool check) const
tmp< scalarField > octaves (const scalarField &data, const scalarField &f, const labelUList &freqBandIDs) const
tmp< scalarField > Pf (const scalarField &p) const
tmp< scalarField > meanPf (const scalarField &p) const
tmp< scalarField > RMSmeanPf (const scalarField &p) const
tmp< scalarField > PSDf (const scalarField &p, const scalar deltaT) const
scalar RAf (const scalar f) const
scalar gainA (const scalar f) const
scalar RBf (const scalar f) const
scalar gainB (const scalar f) const
scalar RCf (const scalar f) const
scalar gainC (const scalar f) const
scalar RDf (const scalar f) const
scalar gainD (const scalar f) const
Protected Member Functions inherited from writeFile
void initStream (Ostream &os) const
fileName baseFileDir () const
fileName baseTimeDir () const
fileName filePath (const fileName &fName) const
virtual autoPtr< OFstream > newFile (const fileName &fName) const
virtual autoPtr< OFstream > newFileAtTime (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > newFileAtStartTime (const word &name) const
virtual void resetFile (const word &name)
Omanip< int > valueWidth (const label offset=0) const
void operator= (const writeFile &)=delete
virtual autoPtr< OFstream > createFile (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > createFile (const word &name) const
Static Protected Member Functions
static label findStartTimeIndex (const instantList &allTimes, const scalar startTime)
static void setOctaveBands (const scalarField &f, const scalar fLower, const scalar fUpper, const scalar octave, labelList &fBandIDs, scalarField &fCentre)
Protected Attributes
const dictionary dict_
scalar rhoRef_
label nSamples_
scalar fLower_
scalar fUpper_
scalar startTime_
autoPtr< windowModel > windowModelPtr_
weightingType SPLweighting_
scalar dBRef_
scalar minPressure_
scalar maxPressure_
fileName outputPrefix_
bool writePrmsf_
bool writeSPL_
bool writePSD_
bool writePSDf_
bool writeOctaves_
planInfo planInfo_
Protected Attributes inherited from writeFile
const objectRegistry & fileObr_
const fileName prefix_
word fileName_
autoPtr< OFstream > filePtr_
label writePrecision_
bool writeToFile_
bool updateHeader_
bool writtenHeader_
bool useUserTime_
scalar startTime_
Detailed Description
Base class for noise models.
Data is read from a dictionary, e.g.
rhoRef          1;
N               4096;
fl              25;
fu              10000;
startTime       0;
outputPrefix    "test1";
SPLweighting    dBA;
// Optional write options dictionary
writeOptions
{
    writePrmsf  no;
    writeSPL    yes;
    writePSD    yes;
    writePSDf   no;
    writeOctaves yes;
}
where
Property Description Required Default value
rhoRef Reference density no 1
N Number of samples in sampling window no 65536 (2^16)
fl Lower frequency bounds no 25
fu Upper frequency bounds no 10000
startTime Start time no 0
outputPrefix Prefix applied to output files no ''
SPLweighting Weighting: dBA, dBB, dBC, DBD no none
dBRef Reference for dB calculation no 2e-5
writePrmsf Write Prmsf data no yes
writeSPL Write SPL data no yes
writePSD Write PSD data no yes
writePSDf Write PSDf data no yes
writeOctaves Write octaves data no yes
Source files
noiseModel.H
noiseModel.C
Definition at line 166 of file noiseModel.H.
Member Enumeration Documentation
weightingType
enum class weightingType strong
Enumerator
none
dBA
dBB
dBC
dBD
Definition at line 172 of file noiseModel.H.
Constructor & Destructor Documentation
noiseModel() [1/2]
noiseModel (const noiseModel &) delete
noiseModel() [2/2]
noiseModel (const dictionary & dict, const objectRegistry & obr, const word & name, const bool readFields = true)
Definition at line 599 of file noiseModel.C.
References noiseModel::planInfo::active, dict, noiseModel::planInfo_, noiseModel::read(), Foam::readFields(), and noiseModel::writeWeightings().
~noiseModel()
virtual ~noiseModel () virtual default
Member Function Documentation
checkUniformTimeStep()
Foam::scalar checkUniformTimeStep (const scalarList & times) const protected
Definition at line 176 of file noiseModel.C.
References e, Foam::exit(), Foam::FatalError, FatalErrorInFunction, UList< T >::first(), UList< T >::last(), Foam::mag(), and UList< T >::size().
Referenced by surfaceNoise::initialise(), and pointNoise::processData().
validateBounds()
bool validateBounds (const scalarList & p) const protected
Definition at line 211 of file noiseModel.C.
References Foam::endl(), forAll, Foam::nl, p, and WarningInFunction.
Referenced by pointNoise::processData().
findStartTimeIndex()
static label findStartTimeIndex (const instantList & allTimes, const scalar startTime) inline static protected
Definition at line 288 of file noiseModel.H.
References instant::findStart(), and startTime.
baseFileDir()
Foam::fileName baseFileDir (const label dataseti) const protected
Definition at line 233 of file noiseModel.C.
References Foam::name(), and Foam::type().
writeFileHeader()
void writeFileHeader (Ostream & os, const string & x, const string & y, const UList< Tuple2< string, token > > & headerValues = UList<Tuple2<string, token>>::null()) const protected
Definition at line 244 of file noiseModel.C.
References UPtrList< T >::first(), Foam::nl, os(), Foam::writeHeader(), x, and y.
Referenced by surfaceNoise::calculate(), and pointNoise::processData().
writeFreqDataToFile()
void writeFreqDataToFile (Ostream & os, const scalarField & f, const scalarField & fx) const protected
Definition at line 272 of file noiseModel.C.
References f(), forAll, Foam::nl, os(), and Foam::tab.
Referenced by surfaceNoise::calculate(), and pointNoise::processData().
uniformFrequencies()
Foam::tmp< Foam::scalarField > uniformFrequencies (const scalar deltaT, const bool check) const protected
Definition at line 289 of file noiseModel.C.
References Foam::check(), Foam::endl(), f(), forAll, N(), tmp< T >::New(), WarningInFunction, and Foam::Zero.
Referenced by surfaceNoise::calculate(), and pointNoise::processData().
setOctaveBands()
void setOctaveBands (const scalarField & f, const scalar fLower, const scalar fUpper, const scalar octave, labelList & fBandIDs, scalarField & fCentre) static protected
Definition at line 47 of file noiseModel.C.
References PtrList< T >::append(), Foam::endl(), f(), Foam::flatOutput(), forAll, Foam::pow(), UPtrList< T >::size(), PtrList< T >::transfer(), and WarningInFunction.
Referenced by surfaceNoise::calculate(), and pointNoise::processData().
octaves()
Foam::tmp< Foam::scalarField > octaves (const scalarField & data, const scalarField & f, const labelUList & freqBandIDs) const protected
Definition at line 326 of file noiseModel.C.
References Foam::endl(), f(), tmp< T >::New(), PtrList< T >::set(), UPtrList< T >::size(), WarningInFunction, and Foam::Zero.
Referenced by surfaceNoise::calculate(), and pointNoise::processData().
Pf()
Foam::tmp< Foam::scalarField > Pf (const scalarField & p) const protected
Definition at line 378 of file noiseModel.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::mag(), n, tmp< T >::New(), p, fft::realTransform1D(), UList< T >::size(), and Foam::sqrt().
meanPf()
Foam::tmp< Foam::scalarField > meanPf (const scalarField & p) const protected
Definition at line 421 of file noiseModel.C.
References N(), tmp< T >::New(), p, and Foam::Zero.
RMSmeanPf()
Foam::tmp< Foam::scalarField > RMSmeanPf (const scalarField & p) const protected
Definition at line 441 of file noiseModel.C.
References N(), p, Foam::sqr(), Foam::sqrt(), and Foam::Zero.
Referenced by surfaceNoise::calculate(), and pointNoise::processData().
PSDf()
Foam::tmp< Foam::scalarField > PSDf (const scalarField & p, const scalar deltaT) const protected
Definition at line 460 of file noiseModel.C.
References Foam::average(), Foam::endl(), UPtrList< T >::first(), UPtrList< T >::last(), N(), tmp< T >::New(), p, Foam::Pout, Foam::sqr(), and Foam::Zero.
Referenced by surfaceNoise::calculate(), and pointNoise::processData().
RAf()
Foam::scalar RAf (const scalar f) const protected
Definition at line 496 of file noiseModel.C.
References f(), Foam::sqr(), and Foam::sqrt().
gainA()
Foam::scalar gainA (const scalar f) const protected
Definition at line 513 of file noiseModel.C.
References f(), and Foam::log10().
RBf()
Foam::scalar RBf (const scalar f) const protected
Definition at line 524 of file noiseModel.C.
References f(), Foam::sqr(), and Foam::sqrt().
gainB()
Foam::scalar gainB (const scalar f) const protected
Definition at line 540 of file noiseModel.C.
References f(), and Foam::log10().
RCf()
Foam::scalar RCf (const scalar f) const protected
Definition at line 551 of file noiseModel.C.
References f(), and Foam::sqr().
gainC()
Foam::scalar gainC (const scalar f) const protected
Definition at line 562 of file noiseModel.C.
References f(), and Foam::log10().
RDf()
Foam::scalar RDf (const scalar f) const protected
Definition at line 573 of file noiseModel.C.
References f(), Foam::sqr(), and Foam::sqrt().
gainD()
Foam::scalar gainD (const scalar f) const protected
Definition at line 586 of file noiseModel.C.
References f(), and Foam::log10().
TypeName()
TypeName ("noiseModel")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , noiseModel , dictionary , (const dictionary &dict, const objectRegistry &obr) , (dict, obr))
operator=()
void operator= (const noiseModel &) delete
New()
Foam::autoPtr< Foam::noiseModel > New (const dictionary & dict, const objectRegistry & obr) static
Definition at line 25 of file noiseModelNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, and Foam::Info.
read()
bool read (const dictionary & dict) virtual
Reimplemented from writeFile.
Reimplemented in pointNoise, and surfaceNoise.
Definition at line 643 of file noiseModel.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, Foam::Info, windowModel::New(), Foam::nl, writeFile::read(), dictionary::readIfPresent(), Foam::readWriteOption(), PtrList< T >::setSize(), and dictionary::subOrEmptyDict().
Referenced by noiseModel::noiseModel(), pointNoise::read(), and surfaceNoise::read().
calculate()
virtual void calculate () pure virtual
Implemented in pointNoise, and surfaceNoise.
PSD()
Foam::tmp< Foam::scalarField > PSD (const scalarField & PSDf) const
Definition at line 735 of file noiseModel.C.
References Foam::safeLog10(), and Foam::sqr().
Referenced by surfaceNoise::calculate(), and pointNoise::processData().
SPL() [1/2]
Foam::tmp< Foam::scalarField > SPL (const scalarField & Prms2, const scalar f) const
Definition at line 744 of file noiseModel.C.
References Foam::abort(), f(), Foam::FatalError, FatalErrorInFunction, Foam::safeLog10(), and Foam::sqr().
Referenced by surfaceNoise::calculate(), and pointNoise::processData().
SPL() [2/2]
Foam::tmp< Foam::scalarField > SPL (const scalarField & Prms2, const scalarField & f) const
Definition at line 791 of file noiseModel.C.
References Foam::abort(), f(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::safeLog10(), and Foam::sqr().
cleanFFTW()
void cleanFFTW ()
Definition at line 850 of file noiseModel.C.
writeWeightings()
void writeWeightings () const
Definition at line 861 of file noiseModel.C.
References f(), and Foam::nl.
Referenced by noiseModel::noiseModel().
Member Data Documentation
weightingTypeNames_
const Foam::Enum< Foam::noiseModel::weightingType > weightingTypeNames_ static
Definition at line 181 of file noiseModel.H.
Referenced by pointNoise::processData().
dict_
const dictionary dict_ protected
Definition at line 212 of file noiseModel.H.
Referenced by pointNoise::calculate().
rhoRef_
scalar rhoRef_ protected
Definition at line 215 of file noiseModel.H.
Referenced by pointNoise::processData(), and surfaceNoise::readSurfaceData().
nSamples_
label nSamples_ protected
Definition at line 218 of file noiseModel.H.
fLower_
scalar fLower_ protected
Definition at line 221 of file noiseModel.H.
Referenced by surfaceNoise::calculate(), and pointNoise::processData().
fUpper_
scalar fUpper_ protected
Definition at line 224 of file noiseModel.H.
Referenced by surfaceNoise::calculate(), and pointNoise::processData().
startTime_
scalar startTime_ protected
Definition at line 227 of file noiseModel.H.
Referenced by pointNoise::filterTimeData(), and surfaceNoise::initialise().
windowModelPtr_
autoPtr<windowModel> windowModelPtr_ protected
Definition at line 230 of file noiseModel.H.
Referenced by surfaceNoise::calculate(), surfaceNoise::initialise(), and pointNoise::processData().
SPLweighting_
weightingType SPLweighting_ protected
Definition at line 233 of file noiseModel.H.
Referenced by pointNoise::processData().
dBRef_
scalar dBRef_ protected
Definition at line 236 of file noiseModel.H.
minPressure_
scalar minPressure_ protected
Definition at line 242 of file noiseModel.H.
maxPressure_
scalar maxPressure_ protected
Definition at line 245 of file noiseModel.H.
outputPrefix_
fileName outputPrefix_ protected
Definition at line 251 of file noiseModel.H.
writePrmsf_
bool writePrmsf_ protected
Definition at line 254 of file noiseModel.H.
Referenced by surfaceNoise::calculate(), and pointNoise::processData().
writeSPL_
bool writeSPL_ protected
Definition at line 257 of file noiseModel.H.
Referenced by surfaceNoise::calculate(), and pointNoise::processData().
writePSD_
bool writePSD_ protected
Definition at line 260 of file noiseModel.H.
Referenced by surfaceNoise::calculate(), and pointNoise::processData().
writePSDf_
bool writePSDf_ protected
Definition at line 263 of file noiseModel.H.
Referenced by surfaceNoise::calculate(), and pointNoise::processData().
writeOctaves_
bool writeOctaves_ protected
Definition at line 266 of file noiseModel.H.
Referenced by surfaceNoise::calculate(), and pointNoise::processData().
planInfo_
planInfo planInfo_ mutable protected
Definition at line 272 of file noiseModel.H.
Referenced by noiseModel::noiseModel().
The documentation for this class was generated from the following files:
src/randomProcesses/noise/noiseModels/noiseModel/noiseModel.H
src/randomProcesses/noise/noiseModels/noiseModel/noiseModel.C
src/randomProcesses/noise/noiseModels/noiseModel/noiseModelNew.C