OpenFOAM: genericPatchFieldBase Class Reference
genericPatchFieldBase Class Reference
Generic infrastructure for reading/writing unknown patch types.
#include <genericPatchFieldBase.H>
Public Member Functions
genericPatchFieldBase ()=default
genericPatchFieldBase (const genericPatchFieldBase &)=default
genericPatchFieldBase (genericPatchFieldBase &&)=default
genericPatchFieldBase (const dictionary &dict)
const word & actualType () const noexcept
Protected Member Functions
void genericFatalSolveError (const word &patchName, const IOobject &io) const
void reportMissingEntry (const word &entryName, const word &patchName, const IOobject &io) const
void processGeneric (const label patchSize, const word &patchName, const IOobject &io, const bool separateValue)
bool processEntry (const entry &dEntry, const label patchSize, const word &patchName, const IOobject &io)
void putEntry (const entry &e, Ostream &os) const
void writeGeneric (Ostream &os, const bool separateValue) const
template<class MapperType >
void mapGeneric (const genericPatchFieldBase &rhs, const MapperType &mapper)
template<class MapperType >
void autoMapGeneric (const MapperType &mapper)
void rmapGeneric (const genericPatchFieldBase &rhs, const labelList &addr)
genericPatchFieldBase (const Foam::zero, const genericPatchFieldBase &)
Detailed Description
Generic infrastructure for reading/writing unknown patch types.
Source files
genericPatchFieldBase.H
genericPatchFieldBase.C
genericPatchFieldBaseTemplates.C
Definition at line 50 of file genericPatchFieldBase.H.
Constructor & Destructor Documentation
genericPatchFieldBase() [1/5]
genericPatchFieldBase (const Foam::zero , const genericPatchFieldBase & rhs) protected
Definition at line 64 of file genericPatchFieldBase.C.
genericPatchFieldBase() [2/5]
genericPatchFieldBase () default
genericPatchFieldBase() [3/5]
genericPatchFieldBase (const genericPatchFieldBase &) default
genericPatchFieldBase() [4/5]
genericPatchFieldBase (genericPatchFieldBase &&) default
genericPatchFieldBase() [5/5]
genericPatchFieldBase (const dictionary & dict) explicit
Definition at line 54 of file genericPatchFieldBase.C.
Member Function Documentation
genericFatalSolveError()
void genericFatalSolveError (const word & patchName, const IOobject & io) const protected
Definition at line 77 of file genericPatchFieldBase.C.
References Foam::FatalError, io(), IOobject::name(), Foam::nl, and IOobject::objectPath().
reportMissingEntry()
void reportMissingEntry (const word & entryName, const word & patchName, const IOobject & io) const protected
Definition at line 93 of file genericPatchFieldBase.C.
References Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, io(), IOobject::name(), Foam::nl, and IOobject::objectPath().
Referenced by genericFaePatchField< Type >::genericFaePatchField(), genericFaPatchField< Type >::genericFaPatchField(), genericFvPatchField< Type >::genericFvPatchField(), and genericFvsPatchField< Type >::genericFvsPatchField().
processGeneric()
void processGeneric (const label patchSize, const word & patchName, const IOobject & io, const bool separateValue) protected
Definition at line 112 of file genericPatchFieldBase.C.
References io().
Referenced by genericFaePatchField< Type >::genericFaePatchField(), genericFaPatchField< Type >::genericFaPatchField(), genericFvPatchField< Type >::genericFvPatchField(), genericFvsPatchField< Type >::genericFvsPatchField(), and genericPointPatchField< Type >::genericPointPatchField().
processEntry()
bool processEntry (const entry & dEntry, const label patchSize, const word & patchName, const IOobject & io) protected
Definition at line 136 of file genericPatchFieldBase.C.
References doLocalCode, UPtrList< T >::empty(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, Foam::flatOutput(), io(), IOobject::name(), VectorSpace< Form, Cmpt, Mrows *Ncols >::nComponents, VectorSpace< Form, Cmpt, Ncmpts >::nComponents, Foam::nl, IOobject::objectPath(), and UList< T >::size().
putEntry()
void putEntry (const entry & e, Ostream & os) const protected
Definition at line 333 of file genericPatchFieldBase.C.
References doLocalCode, e, os(), and regIOobject::write().
writeGeneric()
void writeGeneric (Ostream & os, const bool separateValue) const protected
Definition at line 373 of file genericPatchFieldBase.C.
References os(), and Ostream::writeEntry().
Referenced by genericFaePatchField< Type >::write(), genericFaPatchField< Type >::write(), genericFvPatchField< Type >::write(), genericFvsPatchField< Type >::write(), and genericPointPatchField< Type >::write().
mapGeneric()
template<class MapperType > void mapGeneric (const genericPatchFieldBase & rhs, const MapperType & mapper) protected
Definition at line 26 of file genericPatchFieldBaseTemplates.C.
References doLocalCode.
Referenced by genericFaePatchField< Type >::genericFaePatchField(), genericFaPatchField< Type >::genericFaPatchField(), genericFvPatchField< Type >::genericFvPatchField(), genericFvsPatchField< Type >::genericFvsPatchField(), and genericPointPatchField< Type >::genericPointPatchField().
autoMapGeneric()
template<class MapperType > void autoMapGeneric (const MapperType & mapper) protected
Definition at line 54 of file genericPatchFieldBaseTemplates.C.
References doLocalCode.
rmapGeneric()
void rmapGeneric (const genericPatchFieldBase & rhs, const labelList & addr) protected
Definition at line 397 of file genericPatchFieldBase.C.
References doLocalCode.
actualType()
const word & actualType () const inline noexcept
Definition at line 174 of file genericPatchFieldBase.H.
The documentation for this class was generated from the following files:
src/genericPatchFields/common/genericPatchFieldBase.H
src/genericPatchFields/common/genericPatchFieldBase.C
src/genericPatchFields/common/genericPatchFieldBaseTemplates.C