OpenFOAM: softWall Class Reference
softWall Class Reference
sixDoFRigidBodyMotionRestraints model. Soft wall.
#include <softWall.H>
Public Member Functions
TypeName ("softWall")
softWall (const word &name, const dictionary &sDoFRBMRDict)
virtual autoPtr< sixDoFRigidBodyMotionRestraint > clone () const
virtual ~softWall ()=default
virtual void restrain (const sixDoFRigidBodyMotion &motion, vector &restraintPosition, vector &restraintForce, vector &restraintMoment) const
virtual bool read (const dictionary &sDoFRBMRCoeff)
virtual void write (Ostream &) const
Public Member Functions inherited from sixDoFRigidBodyMotionRestraint
TypeName ("sixDoFRigidBodyMotionRestraint")
declareRunTimeSelectionTable (autoPtr, sixDoFRigidBodyMotionRestraint, dictionary,(const word &name, const dictionary &sDoFRBMRDict),(name, sDoFRBMRDict))
sixDoFRigidBodyMotionRestraint (const word &name, const dictionary &sDoFRBMRDict)
virtual ~sixDoFRigidBodyMotionRestraint ()
const word & name () const
const dictionary & coeffDict () const
Additional Inherited Members
Static Public Member Functions inherited from sixDoFRigidBodyMotionRestraint
static autoPtr< sixDoFRigidBodyMotionRestraint > New (const word &name, const dictionary &sDoFRBMRDict)
Protected Attributes inherited from sixDoFRigidBodyMotionRestraint
word name_
dictionary sDoFRBMRCoeffs_
Detailed Description
sixDoFRigidBodyMotionRestraints model. Soft wall.
Source files
softWall.H
softWall.C
Definition at line 50 of file softWall.H.
Constructor & Destructor Documentation
softWall()
softWall (const word & name, const dictionary & sDoFRBMRDict)
Definition at line 45 of file softWall.C.
References Foam::name(), and softWall::read().
~softWall()
virtual ~softWall () virtual default
Member Function Documentation
TypeName()
TypeName ("softWall")
clone()
virtual autoPtr< sixDoFRigidBodyMotionRestraint > clone () const inline virtual
Implements sixDoFRigidBodyMotionRestraint.
Definition at line 89 of file softWall.H.
restrain()
void restrain (const sixDoFRigidBodyMotion & motion, vector & restraintPosition, vector & restraintForce, vector & restraintMoment) const virtual
Implements sixDoFRigidBodyMotionRestraint.
Definition at line 64 of file softWall.C.
References Foam::endl(), Foam::Info, Foam::mag(), sixDoFRigidBodyMotion::mass(), sixDoFRigidBodyMotion::report(), Foam::sqr(), sixDoFRigidBodyMotion::transform(), sixDoFRigidBodyMotion::velocity(), and Foam::Zero.
read()
bool read (const dictionary & sDoFRBMRCoeff) virtual
Reimplemented from sixDoFRigidBodyMotionRestraint.
Definition at line 105 of file softWall.C.
References sixDoFRigidBodyMotionRestraint::read().
Referenced by softWall::softWall().
write()
void write (Ostream & os) const virtual
Implements sixDoFRigidBodyMotionRestraint.
Definition at line 125 of file softWall.C.
References os().
The documentation for this class was generated from the following files:
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/restraints/softWall/softWall.H
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/restraints/softWall/softWall.C