OpenFOAM: flowRateInletVelocityFvPatchVectorField Class Reference
flowRateInletVelocityFvPatchVectorField Class Reference
Boundary conditions » Inlet
Velocity inlet boundary condition either correcting the extrapolated velocity or creating a uniform velocity field normal to the patch adjusted to match the specified flow rate.
#include <flowRateInletVelocityFvPatchVectorField.H>
Public Member Functions
TypeName ("flowRateInletVelocity")
flowRateInletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
flowRateInletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
flowRateInletVelocityFvPatchVectorField (const flowRateInletVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
flowRateInletVelocityFvPatchVectorField (const flowRateInletVelocityFvPatchVectorField &)
virtual tmp< fvPatchVectorField > clone () const
flowRateInletVelocityFvPatchVectorField (const flowRateInletVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
Velocity inlet boundary condition either correcting the extrapolated velocity or creating a uniform velocity field normal to the patch adjusted to match the specified flow rate.
For a mass-based flux:
the flow rate should be provided in kg/s
if rho is "none" the flow rate is in m3/s
otherwise rho should correspond to the name of the density field
if the density field cannot be found in the database, the user must specify the inlet density using the rhoInlet entry
For a volumetric-based flux:
the flow rate is in m3/s
Usage
Property Description Required Default value
massFlowRate mass flow rate [kg/s] no
volumetricFlowRate volumetric flow rate [m3/s] no
rho density field name no rho
rhoInlet inlet density no
extrapolateProfile Extrapolate velocity profile no false
Example of the boundary condition specification for a volumetric flow rate:
    <patchName>
    {
        type                flowRateInletVelocity;
        volumetricFlowRate  0.2;
        extrapolateProfile  yes;
        value               uniform (0 0 0);
    }
Example of the boundary condition specification for a mass flow rate:
    <patchName>
    {
        type                flowRateInletVelocity;
        massFlowRate        0.2;
        extrapolateProfile  yes;
        rho                 rho;
        rhoInlet            1.0;
        value               uniform (0 0 0);
    }
The flowRate entry is a Function1 of time, see Foam::Function1Types.
Note
rhoInlet is required for the case of a mass flow rate, where the density field is not available at start-up
The value is positive into the domain (as an inlet)
May not work correctly for transonic inlets
Strange behaviour with potentialFoam since the U equation is not solved
See also
Foam::fixedValueFvPatchField Foam::Function1Types Foam::flowRateOutletVelocityFvPatchVectorField
Source files
flowRateInletVelocityFvPatchVectorField.H
flowRateInletVelocityFvPatchVectorField.C
Definition at line 141 of file flowRateInletVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
flowRateInletVelocityFvPatchVectorField() [1/5]
flowRateInletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Definition at line 30 of file flowRateInletVelocityFvPatchVectorField.C.
flowRateInletVelocityFvPatchVectorField() [2/5]
flowRateInletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Definition at line 46 of file flowRateInletVelocityFvPatchVectorField.C.
References UPstream::blocking, dict, Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, Function1< Type >::NewIfPresent(), and Foam::nl.
flowRateInletVelocityFvPatchVectorField() [3/5]
flowRateInletVelocityFvPatchVectorField (const flowRateInletVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 94 of file flowRateInletVelocityFvPatchVectorField.C.
flowRateInletVelocityFvPatchVectorField() [4/5]
flowRateInletVelocityFvPatchVectorField (const flowRateInletVelocityFvPatchVectorField & ptf)
Definition at line 112 of file flowRateInletVelocityFvPatchVectorField.C.
flowRateInletVelocityFvPatchVectorField() [5/5]
flowRateInletVelocityFvPatchVectorField (const flowRateInletVelocityFvPatchVectorField & ptf, const DimensionedField< vector, volMesh > & iF)
Definition at line 127 of file flowRateInletVelocityFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("flowRateInletVelocity")
clone() [1/2]
virtual tmp< fvPatchVectorField > clone () const inline virtual
Definition at line 211 of file flowRateInletVelocityFvPatchVectorField.H.
clone() [2/2]
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Definition at line 227 of file flowRateInletVelocityFvPatchVectorField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 194 of file flowRateInletVelocityFvPatchVectorField.C.
References Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
write()
void write (Ostream & os) const virtual
Definition at line 234 of file flowRateInletVelocityFvPatchVectorField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntry(), Ostream::writeEntryIfDifferent(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/flowRateInletVelocity/flowRateInletVelocityFvPatchVectorField.H
src/finiteVolume/fields/fvPatchFields/derived/flowRateInletVelocity/flowRateInletVelocityFvPatchVectorField.C