OpenFOAM: sixDoFRigidBodyMotionConstraint Class Reference
sixDoFRigidBodyMotionConstraint Class Reference abstract
Base class for defining constraints for sixDoF motions.
#include <sixDoFRigidBodyMotionConstraint.H>
Public Member Functions
TypeName ("sixDoFRigidBodyMotionConstraint")
declareRunTimeSelectionTable (autoPtr, sixDoFRigidBodyMotionConstraint, dictionary,(const word &name, const dictionary &sDoFRBMCDict, const sixDoFRigidBodyMotion &motion),(name, sDoFRBMCDict, motion))
sixDoFRigidBodyMotionConstraint (const word &name, const dictionary &sDoFRBMCDict, const sixDoFRigidBodyMotion &motion)
virtual autoPtr< sixDoFRigidBodyMotionConstraint > clone () const =0
virtual ~sixDoFRigidBodyMotionConstraint ()
const word & name () const
virtual void setCentreOfRotation (point &) const
virtual void constrainTranslation (pointConstraint &) const =0
virtual void constrainRotation (pointConstraint &) const =0
virtual bool read (const dictionary &sDoFRBMCDict)
const dictionary & coeffDict () const
const sixDoFRigidBodyMotion & motion () const noexcept
virtual void write (Ostream &) const
Static Public Member Functions
static autoPtr< sixDoFRigidBodyMotionConstraint > New (const word &name, const dictionary &sDoFRBMCDict, const sixDoFRigidBodyMotion &motion)
Protected Attributes
word name_
dictionary sDoFRBMCCoeffs_
const sixDoFRigidBodyMotion & motion_
Detailed Description
Base class for defining constraints for sixDoF motions.
Source files
sixDoFRigidBodyMotionConstraint.H
sixDoFRigidBodyMotionConstraint.C
sixDoFRigidBodyMotionConstraintNew.C
Definition at line 65 of file sixDoFRigidBodyMotionConstraint.H.
Constructor & Destructor Documentation
sixDoFRigidBodyMotionConstraint()
sixDoFRigidBodyMotionConstraint (const word & name, const dictionary & sDoFRBMCDict, const sixDoFRigidBodyMotion & motion)
Definition at line 34 of file sixDoFRigidBodyMotionConstraint.C.
References Foam::name().
~sixDoFRigidBodyMotionConstraint()
~sixDoFRigidBodyMotionConstraint () virtual
Definition at line 49 of file sixDoFRigidBodyMotionConstraint.C.
Member Function Documentation
TypeName()
TypeName ("sixDoFRigidBodyMotionConstraint")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , sixDoFRigidBodyMotionConstraint , dictionary , (const word &name, const dictionary &sDoFRBMCDict, const sixDoFRigidBodyMotion &motion) , (name, sDoFRBMCDict, motion))
clone()
virtual autoPtr< sixDoFRigidBodyMotionConstraint > clone () const pure virtual
Implemented in axis, line, orientation, plane, and point.
New()
Foam::autoPtr< Foam::sixDoFRigidBodyMotionConstraint > New (const word & name, const dictionary & sDoFRBMCDict, const sixDoFRigidBodyMotion & motion) static
Definition at line 27 of file sixDoFRigidBodyMotionConstraintNew.C.
References dict, Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, sixDoFRigidBodyMotionConstraint::motion(), and sixDoFRigidBodyMotionConstraint::name().
Referenced by sixDoFRigidBodyMotion::addConstraints().
name()
const word & name () const inline
Definition at line 136 of file sixDoFRigidBodyMotionConstraint.H.
References sixDoFRigidBodyMotionConstraint::name_.
Referenced by sixDoFRigidBodyMotionConstraint::New().
setCentreOfRotation()
virtual void setCentreOfRotation (point &) const inline virtual
Reimplemented in point.
Definition at line 142 of file sixDoFRigidBodyMotionConstraint.H.
constrainTranslation()
virtual void constrainTranslation (pointConstraint &) const pure virtual
Implemented in axis, line, orientation, plane, and point.
constrainRotation()
virtual void constrainRotation (pointConstraint &) const pure virtual
Implemented in axis, line, orientation, plane, and point.
read()
bool read (const dictionary & sDoFRBMCDict) virtual
Reimplemented in axis, line, orientation, plane, and point.
Definition at line 55 of file sixDoFRigidBodyMotionConstraint.C.
Referenced by axis::read(), line::read(), orientation::read(), plane::read(), and point::read().
coeffDict()
const dictionary & coeffDict () const inline
Definition at line 157 of file sixDoFRigidBodyMotionConstraint.H.
References sixDoFRigidBodyMotionConstraint::sDoFRBMCCoeffs_.
motion()
const sixDoFRigidBodyMotion & motion () const inline noexcept
Definition at line 163 of file sixDoFRigidBodyMotionConstraint.H.
References sixDoFRigidBodyMotionConstraint::motion_.
Referenced by sixDoFRigidBodyMotionConstraint::New().
write()
void write (Ostream & os) const virtual
Reimplemented in axis, line, orientation, plane, and point.
Definition at line 66 of file sixDoFRigidBodyMotionConstraint.C.
Member Data Documentation
name_
word name_ protected
Definition at line 73 of file sixDoFRigidBodyMotionConstraint.H.
Referenced by sixDoFRigidBodyMotionConstraint::name().
sDoFRBMCCoeffs_
dictionary sDoFRBMCCoeffs_ protected
Definition at line 76 of file sixDoFRigidBodyMotionConstraint.H.
Referenced by sixDoFRigidBodyMotionConstraint::coeffDict().
motion_
const sixDoFRigidBodyMotion& motion_ protected
Definition at line 79 of file sixDoFRigidBodyMotionConstraint.H.
Referenced by sixDoFRigidBodyMotionConstraint::motion().
The documentation for this class was generated from the following files:
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/constraints/sixDoFRigidBodyMotionConstraint/sixDoFRigidBodyMotionConstraint.H
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/constraints/sixDoFRigidBodyMotionConstraint/sixDoFRigidBodyMotionConstraint.C
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/constraints/sixDoFRigidBodyMotionConstraint/sixDoFRigidBodyMotionConstraintNew.C