OpenFOAM: exponentialSolidTransport< Thermo > Class Template Reference
exponentialSolidTransport< Thermo > Class Template Reference
Exponential properties for solid heat transport Templated into a given thermodynamics package.
#include <exponentialSolidTransport.H>
Public Member Functions
exponentialSolidTransport (const word &, const exponentialSolidTransport &)
exponentialSolidTransport (const dictionary &)
scalar kappa (const scalar p, const scalar T) const
vector Kappa (const scalar p, const scalar T) const
scalar mu (const scalar p, const scalar T) const
scalar alphah (const scalar p, const scalar T) const
void write (Ostream &os) const
void operator+= (const exponentialSolidTransport &)
Static Public Member Functions
static autoPtr< exponentialSolidTransport > New (const dictionary &dict)
static word typeName ()
Static Public Attributes
static const bool isotropic = true
Friends
exponentialSolidTransport operator* (const scalar, const exponentialSolidTransport &)
Ostream & operator<< (Ostream &, const exponentialSolidTransport &)
Detailed Description
template<class Thermo>
class Foam::exponentialSolidTransport< Thermo >
Exponential properties for solid heat transport Templated into a given thermodynamics package.
Source files
exponentialSolidTransport.H
exponentialSolidTransportI.H
exponentialSolidTransport.C
Definition at line 67 of file exponentialSolidTransport.H.
Constructor & Destructor Documentation
exponentialSolidTransport() [1/2]
template<class Thermo > exponentialSolidTransport (const word & name, const exponentialSolidTransport< Thermo > & ct) inline
Definition at line 40 of file exponentialSolidTransportI.H.
References Foam::name().
exponentialSolidTransport() [2/2]
template<class Thermo > exponentialSolidTransport (const dictionary & dict) explicit
Definition at line 27 of file exponentialSolidTransport.C.
Member Function Documentation
New()
template<class Thermo > Foam::autoPtr< Foam::exponentialSolidTransport< Thermo > > New (const dictionary & dict) inline static
Definition at line 55 of file exponentialSolidTransportI.H.
References dict, and Foam::New().
typeName()
template<class Thermo > static word typeName () inline static
Definition at line 122 of file exponentialSolidTransport.H.
kappa()
template<class Thermo > Foam::scalar kappa (const scalar p, const scalar T) const inline
Definition at line 66 of file exponentialSolidTransportI.H.
References Foam::pow(), and T.
Kappa()
template<class Thermo > Foam::vector Kappa (const scalar p, const scalar T) const inline
Definition at line 76 of file exponentialSolidTransportI.H.
References Foam::pow(), and T.
mu()
template<class Thermo > Foam::scalar mu (const scalar p, const scalar T) const inline
Definition at line 87 of file exponentialSolidTransportI.H.
References NotImplemented.
alphah()
template<class Thermo > Foam::scalar alphah (const scalar p, const scalar T) const inline
Definition at line 96 of file exponentialSolidTransportI.H.
References Cp, p, and T.
write()
template<class Thermo > void write (Ostream & os) const
operator+=()
template<class Thermo > void operator+= (const exponentialSolidTransport< Thermo > &) inline
Definition at line 105 of file exponentialSolidTransportI.H.
References Y.
Friends And Related Symbol Documentation
operator*
template<class Thermo > exponentialSolidTransport operator* (const scalar , const exponentialSolidTransport< Thermo > &) friend
operator<<
template<class Thermo > Ostream & operator<< (Ostream & , const exponentialSolidTransport< Thermo > &) friend
Member Data Documentation
isotropic
template<class Thermo > const bool isotropic = true static
Definition at line 128 of file exponentialSolidTransport.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/solidSpecie/transport/exponential/exponentialSolidTransport.H
src/thermophysicalModels/solidSpecie/transport/exponential/exponentialSolidTransport.C
src/thermophysicalModels/solidSpecie/transport/exponential/exponentialSolidTransportI.H