OpenFOAM: uniformDensityHydrostaticPressureFvPatchScalarField Class Reference
uniformDensityHydrostaticPressureFvPatchScalarField Class Reference
Boundary conditions » Generic
This boundary condition provides a hydrostatic pressure condition, calculated as:
#include <uniformDensityHydrostaticPressureFvPatchScalarField.H>
Public Member Functions
TypeName ("uniformDensityHydrostaticPressure")
uniformDensityHydrostaticPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
uniformDensityHydrostaticPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
uniformDensityHydrostaticPressureFvPatchScalarField (const uniformDensityHydrostaticPressureFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
uniformDensityHydrostaticPressureFvPatchScalarField (const uniformDensityHydrostaticPressureFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
uniformDensityHydrostaticPressureFvPatchScalarField (const uniformDensityHydrostaticPressureFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
scalar rho () const
scalar & rho ()
scalar pRefValue () const
scalar & pRefValue ()
const vector & pRefPoint () const
vector & pRefPoint ()
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
This boundary condition provides a hydrostatic pressure condition, calculated as:
where
= hyrostatic pressure [Pa]
= reference pressure [Pa]
= reference point in Cartesian coordinates
= density (assumed uniform)
= acceleration due to gravity [m/s2]
Usage
Property Description Required Default value
rho uniform density [kg/m3] yes
pRefValue reference pressure [Pa] yes
pRefPoint reference pressure location yes
Example of the boundary condition specification:
    <patchName>
    {
        type            uniformDensityHydrostaticPressure;
        rho             rho;
        pRefValue       1e5;
        pRefPoint       (0 0 0);
        value           uniform 0; // optional initial value
    }
Source files
uniformDensityHydrostaticPressureFvPatchScalarField.H
uniformDensityHydrostaticPressureFvPatchScalarField.C
Definition at line 123 of file uniformDensityHydrostaticPressureFvPatchScalarField.H.
Constructor & Destructor Documentation
uniformDensityHydrostaticPressureFvPatchScalarField() [1/5]
uniformDensityHydrostaticPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 30 of file uniformDensityHydrostaticPressureFvPatchScalarField.C.
uniformDensityHydrostaticPressureFvPatchScalarField() [2/5]
uniformDensityHydrostaticPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 44 of file uniformDensityHydrostaticPressureFvPatchScalarField.C.
References dict.
uniformDensityHydrostaticPressureFvPatchScalarField() [3/5]
uniformDensityHydrostaticPressureFvPatchScalarField (const uniformDensityHydrostaticPressureFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 64 of file uniformDensityHydrostaticPressureFvPatchScalarField.C.
uniformDensityHydrostaticPressureFvPatchScalarField() [4/5]
uniformDensityHydrostaticPressureFvPatchScalarField (const uniformDensityHydrostaticPressureFvPatchScalarField & ptf)
Definition at line 80 of file uniformDensityHydrostaticPressureFvPatchScalarField.C.
uniformDensityHydrostaticPressureFvPatchScalarField() [5/5]
uniformDensityHydrostaticPressureFvPatchScalarField (const uniformDensityHydrostaticPressureFvPatchScalarField & ptf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 93 of file uniformDensityHydrostaticPressureFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("uniformDensityHydrostaticPressure")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 179 of file uniformDensityHydrostaticPressureFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 195 of file uniformDensityHydrostaticPressureFvPatchScalarField.H.
rho() [1/2]
scalar rho () const inline
Definition at line 216 of file uniformDensityHydrostaticPressureFvPatchScalarField.H.
rho() [2/2]
scalar & rho () inline
Definition at line 223 of file uniformDensityHydrostaticPressureFvPatchScalarField.H.
pRefValue() [1/2]
scalar pRefValue () const inline
Definition at line 229 of file uniformDensityHydrostaticPressureFvPatchScalarField.H.
pRefValue() [2/2]
scalar & pRefValue () inline
Definition at line 235 of file uniformDensityHydrostaticPressureFvPatchScalarField.H.
pRefPoint() [1/2]
const vector & pRefPoint () const inline
Definition at line 241 of file uniformDensityHydrostaticPressureFvPatchScalarField.H.
pRefPoint() [2/2]
vector & pRefPoint () inline
Definition at line 248 of file uniformDensityHydrostaticPressureFvPatchScalarField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 109 of file uniformDensityHydrostaticPressureFvPatchScalarField.C.
References g, and gravity::New().
write()
void write (Ostream & os) const virtual
Definition at line 129 of file uniformDensityHydrostaticPressureFvPatchScalarField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntry(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/uniformDensityHydrostaticPressure/uniformDensityHydrostaticPressureFvPatchScalarField.H
src/finiteVolume/fields/fvPatchFields/derived/uniformDensityHydrostaticPressure/uniformDensityHydrostaticPressureFvPatchScalarField.C