OpenFOAM: subCycleField< GeometricField > Class Template Reference
subCycleField< GeometricField > Class Template Reference
#include <subCycle.H>
Public Member Functions
subCycleField (GeometricField &gf)
~subCycleField ()
void updateTimeIndex ()
Detailed Description
template<class GeometricField>
class Foam::subCycleField< GeometricField >
Definition at line 42 of file subCycle.H.
Constructor & Destructor Documentation
subCycleField()
template<class GeometricField > subCycleField (GeometricField & gf) inline
Definition at line 68 of file subCycle.H.
References IOobject::name(), and GeometricField< Type, PatchField, GeoMesh >::New().
~subCycleField()
template<class GeometricField > ~subCycleField () inline
Definition at line 82 of file subCycle.H.
References IOobject::time(), and GeometricField< Type, PatchField, GeoMesh >::timeIndex().
Member Function Documentation
updateTimeIndex()
template<class GeometricField > void updateTimeIndex () inline
Definition at line 103 of file subCycle.H.
References IOobject::time(), and GeometricField< Type, PatchField, GeoMesh >::timeIndex().
Referenced by subCycle< GeometricField >::subCycle().
The documentation for this class was generated from the following file:
src/OpenFOAM/algorithms/subCycle/subCycle.H