OpenFOAM: PDRblock Class Reference
PDRblock Class Reference
A single block x-y-z rectilinear mesh addressable as i,j,k with simplified creation. Some of the input is similar to blockMeshDict, but since this specialization is for a single-block that is aligned with the x-y-z directions, it provides a different means of specifying the mesh.
#include <PDRblock.H>
Classes
struct gridControl
class location
Public Types
enum expansionType : uint8_t { EXPAND_UNIFORM , EXPAND_RATIO , EXPAND_RELATIVE }
Public Member Functions
PDRblock ()
PDRblock (const UList< scalar > &xgrid, const UList< scalar > &ygrid, const UList< scalar > &zgrid)
PDRblock (const boundBox &box, const labelVector &nCells)
PDRblock (const dictionary &dict, bool verboseOutput=false)
bool read (const dictionary &dict)
void reset (const UList< scalar > &xgrid, const UList< scalar > &ygrid, const UList< scalar > &zgrid)
void reset (const boundBox &box, const labelVector &nCells)
const Vector< location > & grid () const noexcept
Vector< gradingDescriptors > grading () const
gradingDescriptors grading (const direction cmpt) const
const boundBox & bounds () const noexcept
const scalarMinMax & edgeLimits () const noexcept
scalar dx (const label i) const
scalar dx (const labelVector &ijk) const
scalar dy (const label j) const
scalar dy (const labelVector &ijk) const
scalar dz (const label k) const
scalar dz (const labelVector &ijk) const
vector span (const label i, const label j, const label k) const
vector span (const labelVector &ijk) const
point grid (const label i, const label j, const label k) const
point grid (const labelVector &ijk) const
point C (const label i, const label j, const label k) const
point C (const labelVector &ijk) const
scalar V (const label i, const label j, const label k) const
scalar V (const labelVector &ijk) const
scalar width (const label i, const label j, const label k) const
scalar width (const labelVector &ijk) const
labelVector findCell (const point &pt) const
labelVector gridIndex (const point &pt, const scalar relTol=0.01) const
Ostream & blockMeshDict (Ostream &os, const bool withHeader=false) const
dictionary blockMeshDict () const
void writeBlockMeshDict (const IOobject &io) const
autoPtr< polyMesh > mesh (const IOobject &io) const
autoPtr< polyMesh > innerMesh (const IOobject &io) const
Public Member Functions inherited from ijkMesh
ijkMesh ()
ijkMesh (const labelVector &ijk)
ijkMesh (const label nx, const label ny, const label nz)
label nPoints () const
label nCells () const
label nFaces () const
label nInternalFaces () const
label nBoundaryFaces () const
label nBoundaryFaces (const direction shapeFacei) const
label cellLabel (const label i, const label j, const label k) const
label cellLabel (const labelVector &ijk) const
label pointLabel (const label i, const label j, const label k) const
label pointLabel (const labelVector &ijk) const
hexCell vertLabels (const label i, const label j, const label k) const
hexCell vertLabels (const labelVector &ijk) const
Public Member Functions inherited from ijkAddressing
ijkAddressing ()
ijkAddressing (const labelVector &ijk)
ijkAddressing (const label ni, const label nj, const label nk)
bool empty () const
const labelVector & sizes () const
labelVector & sizes ()
label size () const
const label & size (const vector::components cmpt) const
void clear ()
void reset (const label ni, const label nj, const label nk)
void reset (const labelVector &newSizes)
label index (const label i, const label j, const label k) const
label index (const labelVector &ijk) const
labelVector index (const label idx) const
void checkIndex (const label i, const label j, const label k, const bool allowExtra=false) const
void checkIndex (const labelVector &ijk, const bool allowExtra=false) const
void checkSizes () const
void checkSizes (const labelVector &other) const
void checkSizes (const label nTotal) const
Static Public Member Functions
static const PDRblock & null ()
Static Public Attributes
static const Enum< expansionType > expansionNames_
Detailed Description
A single block x-y-z rectilinear mesh addressable as i,j,k with simplified creation. Some of the input is similar to blockMeshDict, but since this specialization is for a single-block that is aligned with the x-y-z directions, it provides a different means of specifying the mesh.
Dictionary controls
Property Description Required Default
x X-direction grid specification yes
y Y-direction grid specification yes
z Z-direction grid specification yes
scale Point scaling no 1.0
expansion Type of expansion (ratio/relative) no ratio
boundary Boundary patches yes
defaultPatch Default patch specification no
Grid coordinate controls
Property Description Required Default
points Locations defining the mesh segment yes
nCells Divisions per mesh segment yes
ratios Expansion values per segment no
A negative expansion value is trapped and treated as its reciprocal. by default, the expansion is as per blockMesh and represents the ratio of end-size / start-size for the section. Alternatively, the relative size can be given.
Source files
PDRblock.H
PDRblockI.H
PDRblock.C
PDRblockCreate.C
Definition at line 149 of file PDRblock.H.
Member Enumeration Documentation
expansionType
enum expansionType : uint8_t
Enumerator
EXPAND_UNIFORM
Uniform expansion (ie, no expansion)
EXPAND_RATIO
End/start ratio.
EXPAND_RELATIVE
Relative expansion ratio.
Definition at line 158 of file PDRblock.H.
Constructor & Destructor Documentation
PDRblock() [1/4]
PDRblock ()
Definition at line 520 of file PDRblock.C.
PDRblock() [2/4]
PDRblock (const UList< scalar > & xgrid, const UList< scalar > & ygrid, const UList< scalar > & zgrid)
Definition at line 526 of file PDRblock.C.
References PDRblock::reset().
PDRblock() [3/4]
PDRblock (const boundBox & box, const labelVector & nCells)
Definition at line 540 of file PDRblock.C.
References ijkMesh::nCells(), and PDRblock::reset().
PDRblock() [4/4]
PDRblock (const dictionary & dict, bool verboseOutput = false) explicit
Definition at line 549 of file PDRblock.C.
References dict, and PDRblock::read().
Member Function Documentation
null()
const Foam::PDRblock & null () static
Definition at line 106 of file PDRblock.C.
read()
bool read (const dictionary & dict)
Definition at line 569 of file PDRblock.C.
References dict, dictionary::findDict(), dictionary::getOrDefault(), Foam::Info, and dictionary::subDict().
Referenced by PDRblock::PDRblock().
reset() [1/2]
void reset (const UList< scalar > & xgrid, const UList< scalar > & ygrid, const UList< scalar > & zgrid)
Definition at line 605 of file PDRblock.C.
References VectorSpace< Form, Cmpt, Ncmpts >::nComponents.
Referenced by PDRblock::PDRblock(), and PDRblock::PDRblock().
reset() [2/2]
void reset (const boundBox & box, const labelVector & nCells)
Definition at line 639 of file PDRblock.C.
References boundBox::max(), boundBox::min(), Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
grid() [1/3]
const Vector< location > & grid () const inline noexcept
Definition at line 531 of file PDRblock.H.
grading() [1/2]
Foam::Vector< Foam::gradingDescriptors > grading () const
Definition at line 736 of file PDRblock.C.
Referenced by PDRblock::blockMeshDict().
grading() [2/2]
Foam::gradingDescriptors grading (const direction cmpt) const
Definition at line 742 of file PDRblock.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Vector< scalar >::X, Vector< scalar >::Y, and Vector< scalar >::Z.
bounds()
const boundBox & bounds () const inline noexcept
Definition at line 546 of file PDRblock.H.
Referenced by PDRblock::blockMeshDict().
edgeLimits()
const scalarMinMax & edgeLimits () const inline noexcept
Definition at line 549 of file PDRblock.H.
dx() [1/2]
Foam::scalar dx (const label i) const inline
Definition at line 140 of file PDRblockI.H.
Referenced by PDRblock::span(), PDRblock::span(), PDRblock::V(), and PDRblock::V().
dx() [2/2]
Foam::scalar dx (const labelVector & ijk) const inline
Definition at line 146 of file PDRblockI.H.
References Vector< Cmpt >::x().
dy() [1/2]
Foam::scalar dy (const label j) const inline
Definition at line 152 of file PDRblockI.H.
Referenced by PDRblock::span(), PDRblock::span(), PDRblock::V(), and PDRblock::V().
dy() [2/2]
Foam::scalar dy (const labelVector & ijk) const inline
Definition at line 158 of file PDRblockI.H.
References Vector< Cmpt >::y().
dz() [1/2]
Foam::scalar dz (const label k) const inline
Definition at line 164 of file PDRblockI.H.
References k.
Referenced by PDRblock::span(), PDRblock::span(), PDRblock::V(), and PDRblock::V().
dz() [2/2]
Foam::scalar dz (const labelVector & ijk) const inline
Definition at line 170 of file PDRblockI.H.
References Vector< Cmpt >::z().
span() [1/2]
Foam::vector span (const label i, const label j, const label k) const inline
Definition at line 176 of file PDRblockI.H.
References PDRblock::dx(), PDRblock::dy(), PDRblock::dz(), and k.
span() [2/2]
Foam::vector span (const labelVector & ijk) const inline
Definition at line 187 of file PDRblockI.H.
References PDRblock::dx(), PDRblock::dy(), and PDRblock::dz().
grid() [2/3]
Foam::point grid (const label i, const label j, const label k) const inline
Definition at line 193 of file PDRblockI.H.
References k.
grid() [3/3]
Foam::point grid (const labelVector & ijk) const inline
Definition at line 204 of file PDRblockI.H.
References Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
C() [1/2]
Foam::point C (const label i, const label j, const label k) const inline
Definition at line 216 of file PDRblockI.H.
References k.
C() [2/2]
Foam::point C (const labelVector & ijk) const inline
Definition at line 227 of file PDRblockI.H.
References Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
V() [1/2]
Foam::scalar V (const label i, const label j, const label k) const inline
Definition at line 239 of file PDRblockI.H.
References PDRblock::dx(), PDRblock::dy(), PDRblock::dz(), and k.
Referenced by PDRblock::width(), and PDRblock::width().
V() [2/2]
Foam::scalar V (const labelVector & ijk) const inline
Definition at line 250 of file PDRblockI.H.
References PDRblock::dx(), PDRblock::dy(), PDRblock::dz(), Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
width() [1/2]
Foam::scalar width (const label i, const label j, const label k) const inline
Definition at line 256 of file PDRblockI.H.
References Foam::cbrt(), k, and PDRblock::V().
width() [2/2]
Foam::scalar width (const labelVector & ijk) const inline
Definition at line 267 of file PDRblockI.H.
References Foam::cbrt(), and PDRblock::V().
findCell()
Foam::labelVector findCell (const point & pt) const
Definition at line 706 of file PDRblock.C.
References Foam::pos().
gridIndex()
Foam::labelVector gridIndex (const point & pt, const scalar relTol = 0.01) const
Definition at line 719 of file PDRblock.C.
References Foam::pos().
blockMeshDict() [1/2]
Foam::Ostream & blockMeshDict (Ostream & os, const bool withHeader = false) const
Definition at line 230 of file PDRblockBlockMesh.C.
References PtrList< T >::append(), Foam::begIndentList(), PDRblock::bounds(), PtrList< T >::clear(), e, token::END_STATEMENT, Foam::endIndentList(), PDRblock::EXPAND_RATIO, UPtrList< T >::first(), PDRblock::grading(), Foam::hex(), cellModel::HEX, Foam::indent(), io(), Foam::max(), Foam::min(), Time::New(), Foam::nl, IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, os(), Foam::outputIndent(), Foam::projGeomName, cellModel::ref(), Foam::relativeToGeometricRatio(), Foam::serializeFace(), Foam::serializeHex(), Foam::serializeProjectEdge(), Foam::serializeProjectFace(), Foam::serializeProjectPoints(), UPtrList< T >::size(), ijkAddressing::sizes(), and IOobject::writeEndDivider().
blockMeshDict() [2/2]
Foam::dictionary blockMeshDict () const
Definition at line 770 of file PDRblockBlockMesh.C.
References os(), and PtrList< T >::transfer().
writeBlockMeshDict()
void writeBlockMeshDict (const IOobject & io) const
Definition at line 782 of file PDRblockBlockMesh.C.
References IOobject::db(), IOstream::defaultPrecision(), Foam::endl(), Foam::Info, io(), IOobject::local(), Foam::max(), OFstream::name(), IOobject::name(), Foam::nl, IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, os(), OSstream::precision(), and IOobject::writeEndDivider().
mesh()
Foam::autoPtr< Foam::polyMesh > mesh (const IOobject & io) const
Definition at line 374 of file PDRblockCreate.C.
References Foam::Info, io(), and Foam::nl.
innerMesh()
Foam::autoPtr< Foam::polyMesh > innerMesh (const IOobject & io) const
Definition at line 297 of file PDRblockCreate.C.
References IOobjectOption::AUTO_WRITE, UPtrList< T >::begin(), UList< T >::begin(), io(), meshPtr, autoPtr< T >::New(), polyPatch::New(), nPoints, patches, pts, and PtrList< T >::set().
Member Data Documentation
expansionNames_
const Foam::Enum< Foam::PDRblock::expansionType > expansionNames_ static
Definition at line 166 of file PDRblock.H.
The documentation for this class was generated from the following files:
src/mesh/blockMesh/PDRblockMesh/PDRblock.H
src/mesh/blockMesh/PDRblockMesh/PDRblock.C
src/mesh/blockMesh/PDRblockMesh/PDRblockBlockMesh.C
src/mesh/blockMesh/PDRblockMesh/PDRblockCreate.C
src/mesh/blockMesh/PDRblockMesh/PDRblockI.H
src/mesh/blockMesh/PDRblockMesh/PDRblockLocation.C