OpenFOAM: polyPatch Class Reference
polyPatch Class Reference
A patch is a list of labels that address the faces in the global face list.
#include <polyPatch.H>
Public Member Functions
TypeName ("patch")
declareRunTimeSelectionTable (autoPtr, polyPatch, word,(const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType),(name, size, start, index, bm, patchType))
declareRunTimeSelectionTable (autoPtr, polyPatch, dictionary,(const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType),(name, dict, index, bm, patchType))
polyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType)
polyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &physicalType, const wordList &inGroups)
polyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType)
polyPatch (const polyPatch &, const polyBoundaryMesh &)
polyPatch (const polyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart)
polyPatch (const polyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
polyPatch (const polyPatch &p)
polyPatch (const polyPatch &p, const labelList &faceCells)
virtual autoPtr< polyPatch > clone (const labelList &faceCells) const
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm) const
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart) const
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart) const
virtual ~polyPatch ()
virtual void newInternalProcFaces (label &, label &) const
virtual const labelUList & nbrCells () const
virtual label neighbPolyPatchID () const
virtual refPtr< labelListList > mapCollocatedFaces () const
virtual bool masterImplicit () const
virtual word neighbRegionID () const
label offset () const noexcept
label start () const noexcept
labelRange range () const
const polyBoundaryMesh & boundaryMesh () const noexcept
virtual bool coupled () const
template<class T >
const UIndirectList< T > patchInternalList (const UList< T > &internalValues) const
template<class T >
const List< T >::subList patchSlice (const UList< T > &values) const
template<class T >
const List< T >::subList boundarySlice (const List< T > &values) const
template<class T >
const Field< T >::subField patchSlice (const Field< T > &values) const
virtual void write (Ostream &os) const
const vectorField::subField faceCentres () const
const vectorField::subField faceAreas () const
tmp< vectorField > faceCellCentres () const
tmp< scalarField > areaFraction () const
const labelUList & faceCells () const
const labelList & meshEdges () const
virtual void clearAddressing ()
label whichFace (const label facei) const noexcept
virtual void initOrder (PstreamBuffers &, const primitivePatch &) const
virtual bool order (PstreamBuffers &, const primitivePatch &, labelList &faceMap, labelList &rotation) const
virtual bool changeTopology () const
virtual bool setTopology (polyTopoChange &)
void operator= (const polyPatch &)
Public Member Functions inherited from patchIdentifier
patchIdentifier (const patchIdentifier &)=default
patchIdentifier & operator= (const patchIdentifier &)=default
virtual ~patchIdentifier ()=default
patchIdentifier ()
patchIdentifier (const word &name, const label index)
patchIdentifier (const word &name, const label index, const word &physicalType, const wordList &inGroups=wordList())
patchIdentifier (const word &name, const dictionary &dict, const label index)
patchIdentifier (const patchIdentifier &ident, const label index)
const word & name () const noexcept
word & name () noexcept
label index () const noexcept
label & index () noexcept
const word & physicalType () const noexcept
word & physicalType () noexcept
const wordList & inGroups () const noexcept
wordList & inGroups () noexcept
bool inGroup (const word &name) const
void write (Ostream &os) const
Public Member Functions inherited from PrimitivePatch< FaceList, PointField >
PrimitivePatch (const FaceList &faces, const PointField &points)
PrimitivePatch (FaceList &&faces, const PointField &points)
PrimitivePatch (FaceList &faces, PointField &points, const bool reuse)
PrimitivePatch (const PrimitivePatch< FaceList, PointField > &pp)
virtual ~PrimitivePatch ()
void clearOut ()
void clearGeom ()
void clearTopology ()
void clearPatchMeshAddr ()
void swap (PrimitivePatch &)=delete
const Field< point_type > & points () const noexcept
label nFaces () const noexcept
label nPoints () const
label nEdges () const
const edgeList & edges () const
const edgeList::subList internalEdges () const
const edgeList::subList boundaryEdges () const
label nInternalEdges () const
label nBoundaryEdges () const
bool isInternalEdge (const label edgei) const
const labelList & boundaryPoints () const
const labelListList & faceFaces () const
const labelListList & edgeFaces () const
const labelListList & faceEdges () const
const labelListList & pointEdges () const
const labelListList & pointFaces () const
const List< face_type > & localFaces () const
labelList boundaryFaces () const
labelList uniqBoundaryFaces () const
const labelList & meshPoints () const
const Map< label > & meshPointMap () const
const Field< point_type > & localPoints () const
const labelList & localPointOrder () const
label whichPoint (const label gp) const
edge meshEdge (const label edgei) const
edge meshEdge (const edge &e) const
label findEdge (const edge &e) const
labelList meshEdges (const edgeList &allEdges, const labelListList &cellEdges, const labelList &faceCells) const
labelList meshEdges (const edgeList &allEdges, const labelListList &pointEdges) const
label meshEdge (const label edgei, const edgeList &allEdges, const labelListList &pointEdges) const
labelList meshEdges (const labelUList &edgeLabels, const edgeList &allEdges, const labelListList &pointEdges) const
const Field< point_type > & faceCentres () const
const Field< point_type > & faceAreas () const
const Field< scalar > & magFaceAreas () const
const Field< point_type > & faceNormals () const
const Field< point_type > & pointNormals () const
Pair< point_type > box () const
scalar sphere (const label facei) const
bool hasFaceAreas () const
bool hasFaceCentres () const
bool hasFaceNormals () const
bool hasPointNormals () const
bool hasBoundaryPoints () const
bool hasEdges () const
bool hasFaceFaces () const
bool hasEdgeFaces () const
bool hasFaceEdges () const
bool hasPointEdges () const
bool hasPointFaces () const
bool hasMeshPoints () const
bool hasMeshPointMap () const
template<class ToPatch >
List< objectHit > projectPoints (const ToPatch &targetPatch, const Field< point_type > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
template<class ToPatch >
List< objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< point_type > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
const labelListList & edgeLoops () const
surfaceTopo surfaceType (labelHashSet *badEdgesPtr=nullptr) const
bool checkTopology (const bool report=false, labelHashSet *pointSetPtr=nullptr) const
bool checkPointManifold (const bool report=false, labelHashSet *pointSetPtr=nullptr) const
void operator= (const PrimitivePatch< FaceList, PointField > &rhs)
void operator= (PrimitivePatch< FaceList, PointField > &&rhs)
label whichEdge (const edge &e) const
template<class ToPatch >
Foam::List< Foam::objectHit > projectPoints (const ToPatch &targetPatch, const Field< typename Foam::PrimitivePatch< FaceList, PointField >::point_type > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
template<class ToPatch >
Foam::List< Foam::objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< typename Foam::PrimitivePatch< FaceList, PointField >::point_type > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
Public Member Functions inherited from PrimitivePatchBase
ClassName ("PrimitivePatch")
PrimitivePatchBase ()=default
Static Public Member Functions
static autoPtr< polyPatch > New (const word &patchType, const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm)
static autoPtr< polyPatch > New (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm)
static autoPtr< polyPatch > New (const word &patchType, const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm)
static bool constraintType (const word &patchType)
static wordList constraintTypes ()
Static Public Member Functions inherited from patchIdentifier
static word defaultName (const label n=-1)
Static Public Attributes
static int disallowGenericPolyPatch
Protected Member Functions
virtual void initGeometry (PstreamBuffers &)
virtual void calcGeometry (PstreamBuffers &)
virtual void initMovePoints (PstreamBuffers &, const pointField &)
virtual void movePoints (PstreamBuffers &, const pointField &p)
virtual void initUpdateMesh (PstreamBuffers &)
virtual void updateMesh (PstreamBuffers &)
virtual void clearGeom ()
virtual void movePoints (const Field< point_type > &)
Friends
class polyBoundaryMesh
Ostream & operator<< (Ostream &, const polyPatch &)
Additional Inherited Members
Public Types inherited from PrimitivePatch< FaceList, PointField >
enum surfaceTopo { MANIFOLD , OPEN , ILLEGAL }
typedef std::remove_reference< FaceList >::type::value_type face_type
typedef std::remove_reference< PointField >::type::value_type point_type
typedef FaceList FaceListType
typedef PointField PointFieldType
typedef face_type FaceType
Detailed Description
A patch is a list of labels that address the faces in the global face list.
The patch can calculate its own edges based on the global faces. Patch also contains all addressing between the faces.
Source files
polyPatch.H
polyPatch.C
polyPatchNew.C
Definition at line 69 of file polyPatch.H.
Constructor & Destructor Documentation
polyPatch() [1/8]
polyPatch (const word & name, const label size, const label start, const label index, const polyBoundaryMesh & bm, const word & patchType)
Definition at line 75 of file polyPatch.C.
References polyPatch::constraintType(), and patchIdentifier::inGroups().
polyPatch() [2/8]
polyPatch (const word & name, const label size, const label start, const label index, const polyBoundaryMesh & bm, const word & physicalType, const wordList & inGroups)
Definition at line 103 of file polyPatch.C.
polyPatch() [3/8]
polyPatch (const word & name, const dictionary & dict, const label index, const polyBoundaryMesh & bm, const word & patchType)
Definition at line 127 of file polyPatch.C.
References polyPatch::constraintType(), and patchIdentifier::inGroups().
polyPatch() [4/8]
polyPatch (const polyPatch & pp, const polyBoundaryMesh & bm)
Definition at line 159 of file polyPatch.C.
polyPatch() [5/8]
polyPatch (const polyPatch & pp, const polyBoundaryMesh & bm, const label index, const label newSize, const label newStart)
Definition at line 183 of file polyPatch.C.
polyPatch() [6/8]
polyPatch (const polyPatch & pp, const polyBoundaryMesh & bm, const label index, const labelUList & mapAddressing, const label newStart)
Definition at line 210 of file polyPatch.C.
polyPatch() [7/8]
polyPatch (const polyPatch & p)
Definition at line 237 of file polyPatch.C.
polyPatch() [8/8]
polyPatch (const polyPatch & p, const labelList & faceCells)
Definition at line 248 of file polyPatch.C.
~polyPatch()
~polyPatch () virtual
Definition at line 262 of file polyPatch.C.
Member Function Documentation
initGeometry()
virtual void initGeometry (PstreamBuffers &) inline protected virtual
Reimplemented in cyclicACMIPolyPatch, cyclicAMIPolyPatch, mappedPolyPatch, mappedWallPolyPatch, cyclicPolyPatch, oldCyclicPolyPatch, processorPolyPatch, processorCyclicPolyPatch, and coupledPolyPatch.
Definition at line 100 of file polyPatch.H.
Referenced by cyclicAMIPolyPatch::initGeometry(), mappedPolyPatch::initGeometry(), mappedWallPolyPatch::initGeometry(), cyclicPolyPatch::initGeometry(), and oldCyclicPolyPatch::initGeometry().
calcGeometry()
virtual void calcGeometry (PstreamBuffers &) inline protected virtual
Reimplemented in cyclicACMIPolyPatch, cyclicAMIPolyPatch, mappedPolyPatch, mappedWallPolyPatch, cyclicPolyPatch, oldCyclicPolyPatch, processorPolyPatch, processorCyclicPolyPatch, symmetryPlanePolyPatch, wedgePolyPatch, and coupledPolyPatch.
Definition at line 104 of file polyPatch.H.
Referenced by mappedPolyPatch::calcGeometry(), and mappedWallPolyPatch::calcGeometry().
initMovePoints()
virtual void initMovePoints (PstreamBuffers & , const pointField &) inline protected virtual
Reimplemented in mappedPolyPatch, mappedWallPolyPatch, cyclicPolyPatch, oldCyclicPolyPatch, processorPolyPatch, processorCyclicPolyPatch, coupledPolyPatch, cyclicACMIPolyPatch, and cyclicAMIPolyPatch.
Definition at line 108 of file polyPatch.H.
Referenced by mappedPolyPatch::initMovePoints(), mappedWallPolyPatch::initMovePoints(), cyclicPolyPatch::initMovePoints(), and oldCyclicPolyPatch::initMovePoints().
movePoints() [1/2]
void movePoints (PstreamBuffers & , const pointField & p) protected virtual
Reimplemented in mappedPolyPatch, mappedWallPolyPatch, cyclicPolyPatch, oldCyclicPolyPatch, processorPolyPatch, processorCyclicPolyPatch, coupledPolyPatch, cyclicACMIPolyPatch, and cyclicAMIPolyPatch.
Definition at line 54 of file polyPatch.C.
References PrimitivePatch< FaceList, PointField >::movePoints(), and p.
Referenced by processorPolyPatch::initMovePoints(), mappedPolyPatch::movePoints(), mappedWallPolyPatch::movePoints(), cyclicPolyPatch::movePoints(), and oldCyclicPolyPatch::movePoints().
initUpdateMesh()
virtual void initUpdateMesh (PstreamBuffers &) inline protected virtual
Reimplemented in cyclicACMIPolyPatch, cyclicAMIPolyPatch, mappedPolyPatch, mappedWallPolyPatch, cyclicPolyPatch, oldCyclicPolyPatch, processorPolyPatch, processorCyclicPolyPatch, and coupledPolyPatch.
Definition at line 115 of file polyPatch.H.
Referenced by cyclicAMIPolyPatch::initUpdateMesh(), mappedPolyPatch::initUpdateMesh(), mappedWallPolyPatch::initUpdateMesh(), cyclicPolyPatch::initUpdateMesh(), oldCyclicPolyPatch::initUpdateMesh(), and processorPolyPatch::initUpdateMesh().
updateMesh()
void updateMesh (PstreamBuffers &) protected virtual
Reimplemented in cyclicACMIPolyPatch, cyclicAMIPolyPatch, mappedPolyPatch, mappedWallPolyPatch, cyclicPolyPatch, oldCyclicPolyPatch, processorPolyPatch, processorCyclicPolyPatch, and coupledPolyPatch.
Definition at line 60 of file polyPatch.C.
References PrimitivePatch< FaceList, PointField >::clearGeom().
Referenced by cyclicAMIPolyPatch::updateMesh(), mappedPolyPatch::updateMesh(), mappedWallPolyPatch::updateMesh(), cyclicPolyPatch::updateMesh(), oldCyclicPolyPatch::updateMesh(), and processorPolyPatch::updateMesh().
clearGeom()
void clearGeom () protected virtual
Reimplemented in cyclicACMIPolyPatch, and cyclicAMIPolyPatch.
Definition at line 67 of file polyPatch.C.
References PrimitivePatch< FaceList, PointField >::clearGeom().
Referenced by cyclicAMIPolyPatch::clearGeom().
TypeName()
TypeName ("patch")
declareRunTimeSelectionTable() [1/2]
declareRunTimeSelectionTable (autoPtr , polyPatch , word , (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType) , (name, size, start, index, bm, patchType))
declareRunTimeSelectionTable() [2/2]
declareRunTimeSelectionTable (autoPtr , polyPatch , dictionary , (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType) , (name, dict, index, bm, patchType))
clone() [1/4]
virtual autoPtr< polyPatch > clone (const labelList & faceCells) const inline virtual
Definition at line 236 of file polyPatch.H.
References autoPtr< T >::New().
clone() [2/4]
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh & bm) const inline virtual
Reimplemented in cyclicACMIPolyPatch, cyclicAMIPolyPatch, cyclicPeriodicAMIPolyPatch, mappedPolyPatch, mappedVariableThicknessWallPolyPatch, mappedWallPolyPatch, genericPolyPatch, cyclicPolyPatch, cyclicSlipPolyPatch, emptyPolyPatch, nonuniformTransformCyclicPolyPatch, oldCyclicPolyPatch, processorPolyPatch, processorCyclicPolyPatch, symmetryPolyPatch, symmetryPlanePolyPatch, wedgePolyPatch, wallPolyPatch, and oversetPolyPatch.
Definition at line 242 of file polyPatch.H.
References autoPtr< T >::New().
clone() [3/4]
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh & bm, const label index, const label newSize, const label newStart) const inline virtual
Reimplemented in cyclicACMIPolyPatch, cyclicAMIPolyPatch, cyclicPeriodicAMIPolyPatch, mappedPolyPatch, mappedVariableThicknessWallPolyPatch, mappedWallPolyPatch, genericPolyPatch, cyclicPolyPatch, cyclicSlipPolyPatch, emptyPolyPatch, nonuniformTransformCyclicPolyPatch, oldCyclicPolyPatch, processorPolyPatch, processorCyclicPolyPatch, symmetryPolyPatch, symmetryPlanePolyPatch, wedgePolyPatch, wallPolyPatch, and oversetPolyPatch.
Definition at line 249 of file polyPatch.H.
References patchIdentifier::index(), and autoPtr< T >::New().
clone() [4/4]
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh & bm, const label index, const labelUList & mapAddressing, const label newStart) const inline virtual
Reimplemented in cyclicACMIPolyPatch, cyclicAMIPolyPatch, cyclicPeriodicAMIPolyPatch, mappedPolyPatch, mappedVariableThicknessWallPolyPatch, mappedWallPolyPatch, genericPolyPatch, cyclicPolyPatch, cyclicSlipPolyPatch, emptyPolyPatch, nonuniformTransformCyclicPolyPatch, processorPolyPatch, processorCyclicPolyPatch, symmetryPolyPatch, symmetryPlanePolyPatch, wedgePolyPatch, wallPolyPatch, and oversetPolyPatch.
Definition at line 262 of file polyPatch.H.
References patchIdentifier::index(), and autoPtr< T >::New().
New() [1/3]
Foam::autoPtr< Foam::polyPatch > New (const word & patchType, const word & name, const label size, const label start, const label index, const polyBoundaryMesh & bm) static
Definition at line 27 of file polyPatchNew.C.
References DebugInFunction, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInLookup, patchIdentifier::index(), patchIdentifier::name(), and polyPatch::start().
Referenced by columnFvMeshInfo::addLocalPatches(), meshRefinement::appendPatch(), extrudePatchMesh::extrudePatchMesh(), PDRblock::innerMesh(), polyPatch::New(), fvMeshTools::newMesh(), boundaryMesh::patchify(), polyMesh::polyMesh(), and polyMesh::polyMesh().
New() [2/3]
Foam::autoPtr< Foam::polyPatch > New (const word & name, const dictionary & dict, const label index, const polyBoundaryMesh & bm) static
Definition at line 66 of file polyPatchNew.C.
References DebugInFunction, dict, Foam::endl(), dictionary::get(), Foam::name(), polyPatch::New(), and dictionary::readIfPresent().
New() [3/3]
Foam::autoPtr< Foam::polyPatch > New (const word & patchType, const word & name, const dictionary & dict, const label index, const polyBoundaryMesh & bm) static
Definition at line 83 of file polyPatchNew.C.
References DebugInFunction, dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, and Foam::name().
newInternalProcFaces()
virtual void newInternalProcFaces (label & , label &) const inline virtual
Reimplemented in cyclicACMIPolyPatch, cyclicAMIPolyPatch, mappedPolyPatch, mappedWallPolyPatch, and cyclicPolyPatch.
Definition at line 317 of file polyPatch.H.
References NotImplemented.
nbrCells()
virtual const labelUList & nbrCells () const inline virtual
Reimplemented in cyclicAMIPolyPatch, mappedPolyPatch, mappedWallPolyPatch, and cyclicPolyPatch.
Definition at line 323 of file polyPatch.H.
References NotImplemented, and UList< label >::null().
neighbPolyPatchID()
virtual label neighbPolyPatchID () const inline virtual
Reimplemented in cyclicAMIPolyPatch, mappedPolyPatch, mappedWallPolyPatch, and cyclicPolyPatch.
Definition at line 330 of file polyPatch.H.
References NotImplemented.
mapCollocatedFaces()
virtual refPtr< labelListList > mapCollocatedFaces () const inline virtual
Reimplemented in cyclicACMIPolyPatch, cyclicAMIPolyPatch, mappedPolyPatch, mappedWallPolyPatch, and cyclicPolyPatch.
Definition at line 337 of file polyPatch.H.
References NotImplemented.
masterImplicit()
virtual bool masterImplicit () const inline virtual
Reimplemented in cyclicAMIPolyPatch, mappedPolyPatch, mappedWallPolyPatch, and cyclicPolyPatch.
Definition at line 344 of file polyPatch.H.
References NotImplemented.
neighbRegionID()
virtual word neighbRegionID () const inline virtual
Reimplemented in mappedPolyPatch, and mappedWallPolyPatch.
Definition at line 351 of file polyPatch.H.
offset()
Foam::label offset () const noexcept
Definition at line 303 of file polyPatch.C.
Referenced by fvPatch::boundarySlice(), polyPatch::boundarySlice(), and cyclicPolyPatch::transformGlobalFace().
start()
label start () const inline noexcept
Definition at line 362 of file polyPatch.H.
Referenced by polyPatch::New(), combine< Type, TrackingData >::operator()(), fvPatch::start(), and cyclicPolyPatch::transformGlobalFace().
range()
labelRange range () const inline
Definition at line 368 of file polyPatch.H.
boundaryMesh()
const Foam::polyBoundaryMesh & boundaryMesh () const noexcept
Definition at line 310 of file polyPatch.C.
Referenced by viewFactor::calculate(), directions::directions(), fluxSummary::initialiseFaceZone(), fluxSummary::initialiseFaceZoneAndDirection(), regionModel::interRegionAMI(), regionModel::mapRegionPatchField(), regionModel::mapRegionPatchInternalField(), regionModel::nbrCoupledPatchID(), singleDirectionUniformBin::processField(), uniformBin::processField(), externalFileSource::read(), uniformBin::setBinsAddressing(), extractEulerianParticles::setBlockedFaces(), externalCoupled::writeGeometry(), and Foam::ensightOutput::writePointField().
coupled()
virtual bool coupled () const inline virtual
Reimplemented in cyclicAMIPolyPatch, coupledPolyPatch, and processorPolyPatch.
Definition at line 378 of file polyPatch.H.
Referenced by fvPatch::coupled().
constraintType()
bool constraintType (const word & patchType) static
Definition at line 270 of file polyPatch.C.
Referenced by faPatch::constraintType(), Foam::evaluateConstraintTypes(), surfaceDistance::execute(), KinematicParcel< ParcelType >::hitPatch(), meshRefinement::meshedPatches(), polyPatch::polyPatch(), polyPatch::polyPatch(), and Foam::Detail::reusable().
constraintTypes()
Foam::wordList constraintTypes () static
Definition at line 281 of file polyPatch.C.
References forAllConstIters, PtrList< T >::resize(), and UPtrList< T >::size().
patchInternalList()
template<class T > const UIndirectList< T > patchInternalList (const UList< T > & internalValues) const inline
Definition at line 391 of file polyPatch.H.
References polyPatch::faceCells().
patchSlice() [1/2]
template<class T > const List< T >::subList patchSlice (const UList< T > & values) const inline
Definition at line 403 of file polyPatch.H.
boundarySlice()
template<class T > const List< T >::subList boundarySlice (const List< T > & values) const inline
Definition at line 412 of file polyPatch.H.
References polyPatch::offset().
patchSlice() [2/2]
template<class T > const Field< T >::subField patchSlice (const Field< T > & values) const inline
Definition at line 420 of file polyPatch.H.
write()
void write (Ostream & os) const virtual
Reimplemented in cyclicACMIPolyPatch, cyclicAMIPolyPatch, cyclicPeriodicAMIPolyPatch, mappedPolyPatch, mappedVariableThicknessWallPolyPatch, mappedWallPolyPatch, genericPolyPatch, cyclicPolyPatch, oldCyclicPolyPatch, processorPolyPatch, processorCyclicPolyPatch, and coupledPolyPatch.
Definition at line 408 of file polyPatch.C.
References os(), Foam::type(), patchIdentifier::write(), and Ostream::writeEntry().
Referenced by mappedPolyPatch::write(), and coupledPolyPatch::write().
faceCentres()
const Foam::vectorField::subField faceCentres () const
Definition at line 316 of file polyPatch.C.
References mesh.
Referenced by cyclicAMIPolyPatch::restoreScaledGeometry().
faceAreas()
const Foam::vectorField::subField faceAreas () const
Definition at line 322 of file polyPatch.C.
References mesh.
Referenced by cyclicAMIPolyPatch::restoreScaledGeometry(), cyclicACMIPolyPatch::scalePatchFaceAreas(), and cyclicACMIPolyPatch::scalePatchFaceAreas().
faceCellCentres()
Foam::tmp< Foam::vectorField > faceCellCentres () const
Definition at line 328 of file polyPatch.C.
References forAll.
areaFraction()
Foam::tmp< Foam::scalarField > areaFraction () const
Definition at line 347 of file polyPatch.C.
References forAll, Foam::mag(), and points.
faceCells()
const Foam::labelUList & faceCells () const
Definition at line 366 of file polyPatch.C.
References mesh.
Referenced by oversetFvPatch::faceCells(), polyPatch::patchInternalList(), and cyclicACMIPolyPatch::scalePatchFaceAreas().
meshEdges()
const Foam::labelList & meshEdges () const
Definition at line 380 of file polyPatch.C.
References mesh, and PrimitivePatch< FaceList, PointField >::meshEdges().
clearAddressing()
void clearAddressing () virtual
Definition at line 399 of file polyPatch.C.
References PrimitivePatch< FaceList, PointField >::clearPatchMeshAddr(), PrimitivePatch< FaceList, PointField >::clearTopology(), and Foam::deleteDemandDrivenData().
whichFace()
label whichFace (const label facei) const inline noexcept
Definition at line 461 of file polyPatch.H.
initOrder()
void initOrder (PstreamBuffers & , const primitivePatch &) const virtual
Reimplemented in cyclicACMIPolyPatch, cyclicAMIPolyPatch, cyclicPolyPatch, oldCyclicPolyPatch, processorPolyPatch, processorCyclicPolyPatch, and coupledPolyPatch.
Definition at line 417 of file polyPatch.C.
order()
bool order (PstreamBuffers & , const primitivePatch & , labelList & faceMap, labelList & rotation) const virtual
Reimplemented in cyclicACMIPolyPatch, cyclicAMIPolyPatch, cyclicPolyPatch, oldCyclicPolyPatch, processorPolyPatch, processorCyclicPolyPatch, and coupledPolyPatch.
Definition at line 421 of file polyPatch.C.
changeTopology()
virtual bool changeTopology () const inline virtual
Reimplemented in cyclicAMIPolyPatch.
Definition at line 486 of file polyPatch.H.
setTopology()
virtual bool setTopology (polyTopoChange &) inline virtual
Reimplemented in cyclicAMIPolyPatch.
Definition at line 492 of file polyPatch.H.
operator=()
void operator= (const polyPatch & p)
Definition at line 436 of file polyPatch.C.
References patchIdentifier::operator=(), PrimitivePatch< FaceList, PointField >::operator=(), and p.
movePoints() [2/2]
void movePoints (const Field< point_type > &) protected virtual
Reimplemented from PrimitivePatch< FaceList, PointField >.
Definition at line 558 of file PrimitivePatch.C.
Friends And Related Symbol Documentation
polyBoundaryMesh
friend class polyBoundaryMesh friend
Definition at line 97 of file polyPatch.H.
operator<<
Ostream & operator<< (Ostream & , const polyPatch &) friend
Member Data Documentation
disallowGenericPolyPatch
int disallowGenericPolyPatch static
Definition at line 131 of file polyPatch.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/polyPatches/polyPatch/polyPatch.H
src/OpenFOAM/meshes/polyMesh/polyPatches/polyPatch/polyPatch.C
src/OpenFOAM/meshes/polyMesh/polyPatches/polyPatch/polyPatchNew.C