OpenFOAM: LeidenfrostModel Class Reference
LeidenfrostModel Class Reference abstract
Base class for Leidenfrost-effect models.
#include <LeidenfrostModel.H>
Public Member Functions
TypeName ("LeidenfrostModel")
declareRunTimeSelectionTable (autoPtr, LeidenfrostModel, dictionary,(const dictionary &dict),(dict))
LeidenfrostModel ()=default
virtual ~LeidenfrostModel ()=default
virtual tmp< scalarField > TLeid (const phaseModel &liquid, const phaseModel &vapor, const label patchi, const scalarField &Tl, const scalarField &Tsatw, const scalarField &L) const =0
virtual void write (Ostream &os) const
Static Public Member Functions
static autoPtr< LeidenfrostModel > New (const dictionary &dict)
Detailed Description
Base class for Leidenfrost-effect models.
Source files
LeidenfrostModel.H
LeidenfrostModel.C
Definition at line 52 of file LeidenfrostModel.H.
Constructor & Destructor Documentation
LeidenfrostModel()
LeidenfrostModel () default
~LeidenfrostModel()
virtual ~LeidenfrostModel () virtual default
Member Function Documentation
TypeName()
TypeName ("LeidenfrostModel")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , LeidenfrostModel , dictionary , (const dictionary &dict) , (dict))
New()
Foam::autoPtr< Foam::wallBoilingModels::LeidenfrostModel > New (const dictionary & dict) static
Definition at line 38 of file LeidenfrostModel.C.
References Foam::abort(), dict, Foam::endl(), Foam::FatalIOError, FatalIOErrorInLookup, and Foam::Info.
Referenced by alphatWallBoilingWallFunctionFvPatchScalarField::alphatWallBoilingWallFunctionFvPatchScalarField().
TLeid()
virtual tmp< scalarField > TLeid (const phaseModel & liquid, const phaseModel & vapor, const label patchi, const scalarField & Tl, const scalarField & Tsatw, const scalarField & L) const pure virtual
Implemented in Spiegler.
write()
void write (Ostream & os) const virtual
Reimplemented in Spiegler.
Definition at line 66 of file LeidenfrostModel.C.
References os(), and Foam::type().
Referenced by Spiegler::write().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/wallBoilingSubModels/LeidenfrostModels/LeidenfrostModel/LeidenfrostModel.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/wallBoilingSubModels/LeidenfrostModels/LeidenfrostModel/LeidenfrostModel.C