OpenFOAM: ensightFile Class Reference
ensightFile Class Reference
Ensight output with specialized write() for strings, integers and floats. Correctly handles binary write as well.
#include <ensightFile.H>
Public Types
typedef float floatType
Public Types inherited from IOstream
enum streamAccess : char { CLOSED = 0 , OPENED }
Public Types inherited from IOstreamOption
enum streamFormat : char { ASCII = 0 , BINARY }
enum compressionType : char { UNCOMPRESSED = 0 , COMPRESSED }
enum appendType : char { NON_APPEND = 0 , APPEND }
enum atomicType : char { NON_ATOMIC = 0 , ATOMIC }
Public Member Functions
ensightFile (const fileName &pathname, IOstreamOption::streamFormat fmt=IOstreamOption::BINARY)
ensightFile (const fileName &path, const fileName &name, IOstreamOption::streamFormat fmt=IOstreamOption::BINARY)
~ensightFile ()=default
virtual Ostream & writeKeyword (const keyType &key)
Ostream & writeBinaryHeader ()
Ostream & writeString (const char *str)
Ostream & writeString (const std::string &str)
Ostream & writeUndef ()
virtual bool write (const token &)
virtual Ostream & write (const char)
virtual Ostream & write (const char *buf, std::streamsize count)
virtual Ostream & write (const char *str)
virtual Ostream & write (const word &str)
virtual Ostream & write (const string &str)
virtual Ostream & write (const int32_t val)
virtual Ostream & write (const int64_t val)
Ostream & write (const label value, const label fieldWidth)
virtual Ostream & write (const float val)
virtual Ostream & write (const double val)
void newline ()
void beginPart (const label index)
void beginParticleCoordinates (const label nparticles)
void writeLabels (const UList< label > &list)
template<class Addr >
void writeLabels (const IndirectListBase< label, Addr > &list)
void writeList (const UList< label > &field)
void writeList (const UList< float > &field)
void writeList (const UList< double > &field)
template<class Addr >
void writeList (const IndirectListBase< float, Addr > &field)
template<class Addr >
void writeList (const IndirectListBase< double, Addr > &field)
Public Member Functions inherited from OFstream
ClassName ("OFstream")
OFstream (std::nullptr_t)
OFstream (IOstreamOption::atomicType atomic, const fileName &pathname, IOstreamOption streamOpt=IOstreamOption(), IOstreamOption::appendType append=IOstreamOption::NON_APPEND)
OFstream (const fileName &pathname, IOstreamOption streamOpt=IOstreamOption(), IOstreamOption::appendType append=IOstreamOption::NON_APPEND)
OFstream (const fileName &pathname, IOstreamOption::streamFormat fmt, IOstreamOption::compressionType cmp=IOstreamOption::UNCOMPRESSED, IOstreamOption::appendType append=IOstreamOption::NON_APPEND)
OFstream (IOstreamOption::atomicType atomic, const fileName &pathname, IOstreamOption::streamFormat fmt, IOstreamOption::compressionType cmp=IOstreamOption::UNCOMPRESSED, IOstreamOption::appendType append=IOstreamOption::NON_APPEND)
~OFstream ()
virtual std::ostream & stdStream ()
virtual const std::ostream & stdStream () const
virtual void rewind ()
void print (Ostream &os) const
virtual const fileName & name () const
Public Member Functions inherited from OSstream
OSstream (const OSstream &)=default
void operator= (const OSstream &)=delete
OSstream (std::ostream &os, const string &streamName, IOstreamOption streamOpt=IOstreamOption())
OSstream (std::ostream &os, const string &streamName, IOstreamOption::streamFormat fmt, IOstreamOption::compressionType cmp=IOstreamOption::UNCOMPRESSED)
OSstream (std::ostream &os, const string &streamName, IOstreamOption::streamFormat fmt, IOstreamOption::versionNumber ver, IOstreamOption::compressionType cmp=IOstreamOption::UNCOMPRESSED)
virtual ios_base::fmtflags flags () const
virtual ios_base::fmtflags flags (const ios_base::fmtflags f)
void syncState ()
virtual Ostream & writeQuoted (const std::string &str, const bool quoted=true)
virtual Ostream & writeRaw (const char *data, std::streamsize count)
virtual bool beginRawWrite (std::streamsize count)
virtual bool endRawWrite ()
virtual void indent ()
virtual void flush ()
virtual void endl ()
virtual char fill () const
virtual char fill (const char fillch)
virtual int width () const
virtual int width (const int w)
virtual int precision () const
virtual int precision (const int p)
Public Member Functions inherited from Ostream
Ostream (const Ostream &)=default
virtual ~Ostream ()=default
Ostream (IOstreamOption streamOpt=IOstreamOption())
Ostream (IOstreamOption::streamFormat fmt, IOstreamOption::compressionType cmp=IOstreamOption::UNCOMPRESSED)
virtual Ostream & write (const keyType &kw)
unsigned short indentSize () const noexcept
unsigned short indentSize (unsigned short val) noexcept
unsigned short indentLevel () const noexcept
unsigned short indentLevel (unsigned short val) noexcept
void incrIndent () noexcept
void decrIndent ()
virtual Ostream & beginBlock (const keyType &kw)
virtual Ostream & beginBlock ()
virtual Ostream & endBlock ()
virtual Ostream & endEntry ()
template<class T >
Ostream & writeEntry (const keyType &key, const T &value)
template<class T >
Ostream & writeEntryIfDifferent (const word &key, const T &value1, const T &value2)
Ostream & operator() () const
unsigned short & indentLevel () noexcept
unsigned short & indentSize () noexcept
Public Member Functions inherited from IOstream
IOstream (const IOstream &)=default
virtual ~IOstream ()=default
IOstream (IOstreamOption streamOpt=IOstreamOption())
IOstream (IOstreamOption::streamFormat fmt, IOstreamOption::versionNumber ver, IOstreamOption::compressionType cmp=IOstreamOption::UNCOMPRESSED)
fileName relativeName () const
virtual bool check (const char *operation) const
bool fatalCheck (const char *operation) const
bool opened () const noexcept
bool closed () const noexcept
bool good () const noexcept
bool eof () const noexcept
bool fail () const noexcept
bool bad () const noexcept
operator bool () const noexcept
bool operator! () const noexcept
unsigned labelByteSize () const noexcept
unsigned scalarByteSize () const noexcept
void setLabelByteSize (unsigned nbytes) noexcept
void setScalarByteSize (unsigned nbytes) noexcept
template<class T = label>
std::enable_if< std::is_integral< T >::value, bool >::type checkLabelSize () const noexcept
template<class T = scalar>
std::enable_if< std::is_floating_point< T >::value, bool >::type checkScalarSize () const noexcept
label lineNumber () const noexcept
label & lineNumber () noexcept
label lineNumber (const label num) noexcept
void setEof () noexcept
void setFail () noexcept
void setBad ()
ios_base::fmtflags setf (const ios_base::fmtflags f)
ios_base::fmtflags setf (const ios_base::fmtflags f, const ios_base::fmtflags mask)
void unsetf (const ios_base::fmtflags f)
void print (Ostream &os, const int streamState) const
InfoProxy< IOstream > info () const noexcept
Public Member Functions inherited from IOstreamOption
constexpr IOstreamOption (streamFormat fmt=streamFormat::ASCII, compressionType comp=compressionType::UNCOMPRESSED) noexcept
constexpr IOstreamOption (streamFormat fmt, compressionType comp, versionNumber ver) noexcept
constexpr IOstreamOption (streamFormat fmt, versionNumber ver, compressionType comp=compressionType::UNCOMPRESSED) noexcept
IOstreamOption (const IOstreamOption &opt, streamFormat fmt) noexcept
streamFormat format () const noexcept
streamFormat format (const streamFormat fmt) noexcept
streamFormat format (const word &formatName)
compressionType compression () const noexcept
compressionType compression (const compressionType comp) noexcept
compressionType compression (const word &compName)
versionNumber version () const noexcept
versionNumber version (const versionNumber ver) noexcept
versionNumber version (const token &tok)
Static Public Member Functions
static const ensightFile & null ()
static bool allowUndef () noexcept
static bool allowUndef (bool on) noexcept
static float undefValue (float value) noexcept
static bool hasUndef (const UList< float > &field)
static bool hasUndef (const UList< double > &field)
template<class Addr >
static bool hasUndef (const IndirectListBase< float, Addr > &field)
template<class Addr >
static bool hasUndef (const IndirectListBase< double, Addr > &field)
Static Public Member Functions inherited from IOstream
static unsigned int defaultPrecision () noexcept
static unsigned int defaultPrecision (unsigned int prec) noexcept
Static Public Member Functions inherited from IOstreamOption
static streamFormat formatEnum (const word &formatName, const streamFormat deflt=streamFormat::ASCII)
static streamFormat formatEnum (const word &key, const dictionary &dict, const streamFormat deflt=streamFormat::ASCII)
static compressionType compressionEnum (const word &compName, const compressionType deflt=compressionType::UNCOMPRESSED)
static compressionType compressionEnum (const word &key, const dictionary &dict, const compressionType deflt=compressionType::UNCOMPRESSED)
Static Public Attributes
static const char *const coordinates = "coordinates"
Static Public Attributes inherited from IOstream
static unsigned int precision_
Static Public Attributes inherited from IOstreamOption
static const Enum< streamFormat > formatNames
static const versionNumber currentVersion
Additional Inherited Members
Protected Member Functions inherited from IOstream
void setOpened () noexcept
void setClosed () noexcept
void setState (std::ios_base::iostate state) noexcept
void setGood () noexcept
Protected Attributes inherited from Ostream
unsigned short indentSize_ = 4
unsigned short indentLevel_ = 0
Protected Attributes inherited from IOstream
std::ios_base::iostate ioState_
streamAccess openClosed_
unsigned char sizeofLabel_
unsigned char sizeofScalar_
label lineNumber_
Static Protected Attributes inherited from Ostream
static constexpr const unsigned short entryIndentation_ = 16
Static Protected Attributes inherited from IOstream
static fileName staticName_
Detailed Description
Ensight output with specialized write() for strings, integers and floats. Correctly handles binary write as well.
Definition at line 46 of file ensightFile.H.
Member Typedef Documentation
floatType
typedef float floatType
Definition at line 76 of file ensightFile.H.
Constructor & Destructor Documentation
ensightFile() [1/2]
ensightFile (const fileName & pathname, IOstreamOption::streamFormat fmt = IOstreamOption::BINARY) explicit
Definition at line 83 of file ensightFile.C.
ensightFile() [2/2]
ensightFile (const fileName & path, const fileName & name, IOstreamOption::streamFormat fmt = IOstreamOption::BINARY)
Definition at line 95 of file ensightFile.C.
~ensightFile()
~ensightFile () default
Member Function Documentation
null()
static const ensightFile & null () inline static
Definition at line 88 of file ensightFile.H.
allowUndef() [1/2]
bool allowUndef () static noexcept
Definition at line 110 of file ensightFile.C.
allowUndef() [2/2]
bool allowUndef (bool on) static noexcept
Definition at line 122 of file ensightFile.C.
undefValue()
float undefValue (float value) static noexcept
Definition at line 130 of file ensightFile.C.
writeKeyword()
Foam::Ostream & writeKeyword (const keyType & key) virtual
Reimplemented from Ostream.
Reimplemented in ensightGeoFile.
Definition at line 298 of file ensightFile.C.
References write().
writeBinaryHeader()
Foam::Ostream & writeBinaryHeader ()
Definition at line 317 of file ensightFile.C.
References IOstreamOption::BINARY, and format().
writeString() [1/2]
Foam::Ostream & writeString (const char * str)
Definition at line 143 of file ensightFile.C.
References IOstreamOption::BINARY, format(), and write().
writeString() [2/2]
Foam::Ostream & writeString (const std::string & str)
Definition at line 166 of file ensightFile.C.
writeUndef()
Foam::Ostream & writeUndef ()
Definition at line 291 of file ensightFile.C.
References write().
write() [1/11]
virtual bool write (const token &) inline virtual
Reimplemented from OSstream.
Definition at line 159 of file ensightFile.H.
References NotImplemented.
write() [2/11]
virtual Ostream & write (const char) inline virtual
Reimplemented from OSstream.
Definition at line 166 of file ensightFile.H.
References NotImplemented.
write() [3/11]
Foam::Ostream & write (const char * buf, std::streamsize count) virtual
Reimplemented from OSstream.
Definition at line 190 of file ensightFile.C.
write() [4/11]
Foam::Ostream & write (const char * str) virtual
Reimplemented from OSstream.
Definition at line 172 of file ensightFile.C.
write() [5/11]
Foam::Ostream & write (const word & str) virtual
Reimplemented from OSstream.
Definition at line 178 of file ensightFile.C.
write() [6/11]
Foam::Ostream & write (const string & str) virtual
Reimplemented from OSstream.
Definition at line 184 of file ensightFile.C.
write() [7/11]
Foam::Ostream & write (const int32_t val) virtual
Reimplemented from OSstream.
Definition at line 202 of file ensightFile.C.
References IOstreamOption::BINARY, and format().
write() [8/11]
Foam::Ostream & write (const int64_t val) virtual
Reimplemented from OSstream.
Definition at line 223 of file ensightFile.C.
References Foam::narrowInt32(), and write().
write() [9/11]
Foam::Ostream & write (const label value, const label fieldWidth)
Definition at line 260 of file ensightFile.C.
References IOstreamOption::BINARY, format(), and write().
write() [10/11]
Foam::Ostream & write (const float val) virtual
Reimplemented from OSstream.
Definition at line 231 of file ensightFile.C.
References IOstreamOption::BINARY, format(), and write().
write() [11/11]
Foam::Ostream & write (const double val) virtual
Reimplemented from OSstream.
Definition at line 252 of file ensightFile.C.
References Foam::narrowFloat(), and write().
newline()
void newline ()
Definition at line 281 of file ensightFile.C.
References IOstreamOption::ASCII, format(), and Foam::nl.
beginPart()
void beginPart (const label index)
Definition at line 332 of file ensightFile.C.
References write().
beginParticleCoordinates()
void beginParticleCoordinates (const label nparticles)
Definition at line 341 of file ensightFile.C.
References write().
writeLabels() [1/2]
void writeLabels (const UList< label > & list)
Definition at line 350 of file ensightFile.C.
References write().
writeLabels() [2/2]
template<class Addr > void writeLabels (const IndirectListBase< label, Addr > & list)
Definition at line 56 of file ensightFileTemplates.C.
References write().
writeList() [1/5]
void writeList (const UList< label > & field)
Definition at line 360 of file ensightFile.C.
References field(), and write().
writeList() [2/5]
void writeList (const UList< float > & field)
Definition at line 370 of file ensightFile.C.
References field(), and write().
writeList() [3/5]
void writeList (const UList< double > & field)
Definition at line 387 of file ensightFile.C.
References field(), and write().
writeList() [4/5]
template<class Addr > void writeList (const IndirectListBase< float, Addr > & field)
Definition at line 67 of file ensightFileTemplates.C.
References field(), and write().
writeList() [5/5]
template<class Addr > void writeList (const IndirectListBase< double, Addr > & field)
Definition at line 85 of file ensightFileTemplates.C.
References field(), and write().
hasUndef() [1/4]
bool hasUndef (const UList< float > & field) static
Definition at line 39 of file ensightFile.C.
References field().
hasUndef() [2/4]
bool hasUndef (const UList< double > & field) static
Definition at line 53 of file ensightFile.C.
References field().
hasUndef() [3/4]
template<class Addr > bool hasUndef (const IndirectListBase< float, Addr > & field) static
Definition at line 24 of file ensightFileTemplates.C.
References field().
hasUndef() [4/4]
template<class Addr > bool hasUndef (const IndirectListBase< double, Addr > & field) static
Definition at line 39 of file ensightFileTemplates.C.
References field().
Member Data Documentation
coordinates
const char *const coordinates = "coordinates" static
Definition at line 82 of file ensightFile.H.
Referenced by ensightGeoFile::beginCoordinates(), ensightOutputSurface::writePointData(), and Foam::writeTrackField().
The documentation for this class was generated from the following files:
src/fileFormats/ensight/file/ensightFile.H
src/fileFormats/ensight/file/ensightFile.C
src/fileFormats/ensight/file/ensightFileTemplates.C