OpenFOAM: FieldField< Field, Type > Class Template Reference
FieldField< Field, Type > Class Template Reference
A field of fields is a PtrList of fields with reference counting.
#include <FieldField.H>
Inherits refCount, and PtrList< Field< Type > >.
Inherited by AveragingMethod< Foam::Vector >, AveragingMethod< scalar >, GeometricBoundaryField< symmTensor, fvPatchField, volMesh >, GeometricBoundaryField< scalar, fvPatchField, volMesh >, GeometricBoundaryField< Type, pointPatchField, pointMesh >, GeometricBoundaryField< vector, fvPatchField, volMesh >, GeometricBoundaryField< tensor, fvPatchField, volMesh >, GeometricBoundaryField< scalar, Foam::fvPatchField, Foam::volMesh >, GeometricBoundaryField< Foam::Vector, Foam::fvPatchField, Foam::volMesh >, GeometricBoundaryField< Foam::Vector, Foam::pointPatchField, Foam::pointMesh >, GeometricBoundaryField< scalar, fvsPatchField, surfaceMesh >, GeometricBoundaryField< scalar, pointPatchField, pointMesh >, GeometricBoundaryField< vector, pointPatchField, pointMesh >, GeometricBoundaryField< scalar, faPatchField, areaMesh >, GeometricBoundaryField< scalar, Foam::faPatchField, Foam::areaMesh >, GeometricBoundaryField< scalar, Foam::faePatchField, Foam::edgeMesh >, GeometricBoundaryField< Foam::Vector, Foam::faPatchField, Foam::areaMesh >, GeometricBoundaryField< Foam::Vector, Foam::faePatchField, Foam::edgeMesh >, GeometricBoundaryField< Foam::SphericalTensor, Foam::faPatchField, Foam::areaMesh >, GeometricBoundaryField< Foam::SphericalTensor, Foam::faePatchField, Foam::edgeMesh >, GeometricBoundaryField< Foam::SymmTensor, Foam::faPatchField, Foam::areaMesh >, GeometricBoundaryField< Foam::SymmTensor, Foam::faePatchField, Foam::edgeMesh >, GeometricBoundaryField< Foam::Tensor, Foam::faPatchField, Foam::areaMesh >, GeometricBoundaryField< Foam::Tensor, Foam::faePatchField, Foam::edgeMesh >, GeometricBoundaryField< scalar, Foam::fvsPatchField, Foam::surfaceMesh >, GeometricBoundaryField< Foam::Vector, Foam::fvsPatchField, Foam::surfaceMesh >, GeometricBoundaryField< Foam::SphericalTensor, Foam::fvPatchField, Foam::volMesh >, GeometricBoundaryField< Foam::SphericalTensor, Foam::fvsPatchField, Foam::surfaceMesh >, GeometricBoundaryField< Foam::SymmTensor, Foam::fvPatchField, Foam::volMesh >, GeometricBoundaryField< Foam::SymmTensor, Foam::fvsPatchField, Foam::surfaceMesh >, GeometricBoundaryField< Foam::Tensor, Foam::fvPatchField, Foam::volMesh >, GeometricBoundaryField< Foam::Tensor, Foam::fvsPatchField, Foam::surfaceMesh >, GeometricBoundaryField< Type, Foam::fvPatchField, Foam::volMesh >, GeometricBoundaryField< Type, Foam::pointPatchField, Foam::pointMesh >, GeometricBoundaryField< Type, Foam::fvsPatchField, Foam::surfaceMesh >, GeometricBoundaryField< vector, fvsPatchField, surfaceMesh >, GeometricBoundaryField< scalar, Foam::pointPatchField, Foam::pointMesh >, GeometricBoundaryField< Foam::SphericalTensor, Foam::pointPatchField, Foam::pointMesh >, GeometricBoundaryField< Foam::SymmTensor, Foam::pointPatchField, Foam::pointMesh >, GeometricBoundaryField< Foam::Tensor, Foam::pointPatchField, Foam::pointMesh >, GeometricBoundaryField< tensor, faPatchField, areaMesh >, GeometricBoundaryField< vector, faPatchField, areaMesh >, GeometricBoundaryField< scalar, faePatchField, edgeMesh >, and AveragingMethod< Type >.
Public Types
typedef pTraits< Type >::cmptType cmptType
Public Types inherited from UPtrList< T >
typedef T value_type
typedef T & reference
typedef const T & const_reference
Public Member Functions
constexpr FieldField () noexcept
FieldField (const label size)
FieldField (const word &type, const FieldField< Field, Type > &ff)
FieldField (const FieldField< Field, Type > &ff)
FieldField (FieldField< Field, Type > &&ff)
FieldField (FieldField< Field, Type > &ff, bool reuse)
FieldField (const PtrList< Field< Type > > &list)
FieldField (PtrList< Field< Type > > &&list)
FieldField (const tmp< FieldField< Field, Type > > &tf)
FieldField (Istream &is)
tmp< FieldField< Field, Type > > clone () const
void negate ()
void normalise ()
tmp< FieldField< Field, cmptType > > component (const direction) const
void replace (const direction, const FieldField< Field, cmptType > &)
void replace (const direction, const cmptType &)
void clamp_min (const Type &lower)
void clamp_max (const Type &upper)
void clamp_range (const Type &lower, const Type &upper)
void clamp_range (const MinMax< Type > &range)
tmp< FieldField< Field, Type > > T () const
const Type & operator[] (const labelPair &index) const
Type & operator[] (const labelPair &index)
void operator= (const FieldField< Field, Type > &)
void operator= (FieldField< Field, Type > &&)
void operator= (const tmp< FieldField< Field, Type > > &)
void operator= (const Type &val)
void operator= (const Foam::zero)
void operator+= (const FieldField< Field, Type > &)
void operator+= (const tmp< FieldField< Field, Type > > &)
void operator-= (const FieldField< Field, Type > &)
void operator-= (const tmp< FieldField< Field, Type > > &)
void operator*= (const FieldField< Field, scalar > &)
void operator*= (const tmp< FieldField< Field, scalar > > &)
void operator/= (const FieldField< Field, scalar > &)
void operator/= (const tmp< FieldField< Field, scalar > > &)
void operator+= (const Type &)
void operator-= (const Type &)
void operator*= (const scalar &)
void operator/= (const scalar &)
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Public Member Functions inherited from PtrList< Field< Type > >
constexpr PtrList () noexcept
PtrList (const label len)
PtrList (const PtrList< Field< Type > > &list)
PtrList (PtrList< Field< Type > > &&list)
PtrList (UList< Field< Type > * > &list)
PtrList (const PtrList< Field< Type > > &list, const CloneArg &cloneArgs)
PtrList (PtrList< Field< Type > > &list, bool reuse)
PtrList (const SLPtrList< Field< Type > > &list)
PtrList (Istream &is, const INew &inew)
PtrList (Istream &is)
~PtrList ()
PtrList< Field< Type > > clone (Args &&... args) const
Foam::PtrList< Field< Type > > clone (Args &&... args) const
const Field< Type > * set (const label i) const
autoPtr< Field< Type > > set (const label i, Field< Type > *ptr)
autoPtr< Field< Type > > set (const label i, std::unique_ptr< Field< Type > > &&ptr)
autoPtr< Field< Type > > set (const label i, autoPtr< Field< Type > > &&ptr)
autoPtr< Field< Type > > set (const label i, const refPtr< Field< Type > > &ptr)
autoPtr< Field< Type > > set (const label i, const tmp< Field< Type > > &ptr)
autoPtr< Field< Type > > set (const label i, autoPtr< Field< Type > > &ptr)
void clear ()
void free ()
void resize (const label newLen)
Field< Type > & emplace_back (Args &&... args)
void push_back (Field< Type > *ptr)
void push_back (std::unique_ptr< Field< Type > > &&ptr)
void push_back (autoPtr< Field< Type > > &&ptr)
void push_back (const refPtr< Field< Type > > &ptr)
void push_back (const tmp< Field< Type > > &ptr)
void push_back (PtrList< Field< Type > > &&other)
void push_back (autoPtr< Field< Type > > &ptr)=delete
Field< Type > & emplace_set (const label i, Args &&... args)
Field< Type > & emplace (const label i, Args &&... args)
autoPtr< Field< Type > > release (const label i)
void transfer (PtrList< Field< Type > > &list)
void operator= (const PtrList< Field< Type > > &list)
void operator= (PtrList< Field< Type > > &&list)
void setSize (const label newLen)
void append (autoPtr< Field< Type > > &ptr)
void append (Field< Type > *ptr)
void append (std::unique_ptr< Field< Type > > &&ptr)
void append (autoPtr< Field< Type > > &&ptr)
void append (const refPtr< Field< Type > > &ptr)
void append (const tmp< Field< Type > > &ptr)
void append (PtrList< Field< Type > > &&other)
Public Member Functions inherited from UPtrList< T >
constexpr UPtrList () noexcept
UPtrList (const label len)
UPtrList (const UPtrList< T > &list)
UPtrList (UPtrList< T > &&list)
UPtrList (UPtrList< T > &list, bool reuse)
UPtrList (PtrList< T > &list)
UPtrList (const UList< T * > &list)
UPtrList (UList< T > &list)
bool empty () const noexcept
label size () const noexcept
label count () const noexcept
T & front ()
const T & front () const
T & back ()
const T & back () const
const T * test (const label i) const
const T * get (const label i) const
T * get (const label i)
const T * set (const label i) const
void clear ()
void free ()
void resize (const label newLen)
label squeezeNull ()
void trimTrailingNull ()
void push_back (T *ptr)
void push_back (UPtrList< T > &&other)
void swap (UPtrList< T > &list)
void transfer (UPtrList< T > &list)
T * set (const label i, T *ptr)
void reorder (const labelUList &oldToNew, const bool check=false)
void sortOrder (const labelUList &order, const bool check=false)
void checkNonNull () const
const T & at (const label i) const
T & at (const label i)
const T & operator[] (const label i) const
T & operator[] (const label i)
FOAM_DEPRECATED_FOR (2022-09, "get(), set() or test() methods") const T *operator()(const label i) const
void operator= (const UPtrList< T > &list)
void operator= (UPtrList< T > &&list)
T ** begin_ptr () noexcept
T ** end_ptr () noexcept
iterator begin ()
iterator end () noexcept
const_iterator cbegin () const
const_iterator cend () const noexcept
const_iterator begin () const
const_iterator end () const noexcept
void setSize (const label n)
T & first ()
const T & first () const
T & last ()
const T & last () const
void append (T *ptr)
void append (UPtrList< T > &&other)
Static Public Member Functions
template<class Type2 >
static tmp< FieldField< Field, Type > > NewCalculatedType (const FieldField< Field, Type2 > &ff)
Friends
Ostream & operator (Ostream &, const FieldField< Field, Type > &)
Ostream & operator (Ostream &, const tmp< FieldField< Field, Type > > &)
Additional Inherited Members
Protected Member Functions inherited from PtrList< Field< Type > >
void readIstream (Istream &is, const INew &inew)
Protected Member Functions inherited from UPtrList< T >
void setAddressableSize (const label n) noexcept
label find_next (label pos) const
UPtrList (Detail::PtrListDetail< T > &&ptrs)
Protected Attributes inherited from UPtrList< T >
Detail::PtrListDetail< T > ptrs_
Detailed Description
template<template< class > class Field, class Type>
class Foam::FieldField< Field, Type >
A field of fields is a PtrList of fields with reference counting.
Source files
FieldField.H
FieldField.C
Definition at line 73 of file FieldField.H.
Member Typedef Documentation
cmptType
template<template< class > class Field, class Type > typedef pTraits<Type>::cmptType cmptType
Definition at line 81 of file FieldField.H.
Constructor & Destructor Documentation
FieldField() [1/10]
template<template< class > class Field, class Type > constexpr FieldField () constexpr noexcept
Definition at line 101 of file FieldField.C.
FieldField() [2/10]
template<template< class > class Field, class Type > FieldField (const label size) explicit
Definition at line 108 of file FieldField.C.
FieldField() [3/10]
template<template< class > class Field, class Type > FieldField (const word & type, const FieldField< Field, Type > & ff)
Definition at line 115 of file FieldField.C.
FieldField() [4/10]
template<template< class > class Field, class Type > FieldField (const FieldField< Field, Type > & ff)
Definition at line 131 of file FieldField.C.
FieldField() [5/10]
template<template< class > class Field, class Type > FieldField (FieldField< Field, Type > && ff)
Definition at line 138 of file FieldField.C.
FieldField() [6/10]
template<template< class > class Field, class Type > FieldField (FieldField< Field, Type > & ff, bool reuse)
Definition at line 145 of file FieldField.C.
FieldField() [7/10]
template<template< class > class Field, class Type > FieldField (const PtrList< Field< Type > > & list)
Definition at line 152 of file FieldField.C.
FieldField() [8/10]
template<template< class > class Field, class Type > FieldField (PtrList< Field< Type > > && list)
Definition at line 159 of file FieldField.C.
FieldField() [9/10]
template<template< class > class Field, class Type > FieldField (const tmp< FieldField< Field, Type > > & tf)
Definition at line 166 of file FieldField.C.
References PtrList< T >::clear().
FieldField() [10/10]
template<template< class > class Field, class Type > FieldField (Istream & is)
Definition at line 175 of file FieldField.C.
Member Function Documentation
clone()
template<template< class > class Field, class Type > tmp< FieldField< Field, Type > > clone () const
Definition at line 182 of file FieldField.C.
References Foam::New().
NewCalculatedType()
template<template< class > class Field, class Type > template<class Type2 > tmp< FieldField< Field, Type > > NewCalculatedType (const FieldField< Field, Type2 > & ff) static
Definition at line 190 of file FieldField.C.
Referenced by Foam::cmptAv(), Foam::cmptMag(), Foam::cmptMax(), Foam::cmptMin(), Foam::mag(), Foam::magSqr(), reuseTmpFieldField< Field, TypeR, Type1 >::New(), reuseTmpFieldField< Field, TypeR, Type1 >::New(), reuseTmpTmpFieldField< Field, TypeR, Type1, Type12, Type2 >::New(), reuseTmpTmpFieldField< Field, TypeR, Type1, Type12, TypeR >::New(), reuseTmpFieldField< Field, TypeR, TypeR >::New(), reuseTmpTmpFieldField< Field, TypeR, TypeR, TypeR, Type2 >::New(), reuseTmpTmpFieldField< Field, TypeR, TypeR, TypeR, TypeR >::New(), Foam::pow(), and Foam::sqr().
negate()
template<template< class > class Field, class Type > void negate ()
Definition at line 212 of file FieldField.C.
References forAll, and UPtrList< T >::operator[]().
normalise()
template<template< class > class Field, class Type > void normalise ()
Definition at line 222 of file FieldField.C.
References forAll, and UPtrList< T >::operator[]().
component()
template<template< class > class Field, class Type > tmp< FieldField< Field, typename FieldField< Field, Type >::cmptType > > component (const direction d) const
Definition at line 233 of file FieldField.C.
References Foam::component(), and PtrList< T >::PtrList().
replace() [1/2]
template<template< class > class Field, class Type > void replace (const direction d, const FieldField< Field, cmptType > & sf)
Definition at line 251 of file FieldField.C.
References forAll, and UPtrList< T >::operator[]().
replace() [2/2]
template<template< class > class Field, class Type > void replace (const direction d, const cmptType & s)
Definition at line 265 of file FieldField.C.
References forAll, UPtrList< T >::operator[](), and s().
clamp_min()
template<template< class > class Field, class Type > void clamp_min (const Type & lower)
Definition at line 279 of file FieldField.C.
clamp_max()
template<template< class > class Field, class Type > void clamp_max (const Type & upper)
Definition at line 292 of file FieldField.C.
clamp_range() [1/2]
template<template< class > class Field, class Type > void clamp_range (const Type & lower, const Type & upper)
Definition at line 305 of file FieldField.C.
clamp_range() [2/2]
template<template< class > class Field, class Type > void clamp_range (const MinMax< Type > & range)
Definition at line 321 of file FieldField.C.
References range.
T()
template<template< class > class Field, class Type > tmp< FieldField< Field, Type > > T () const
Definition at line 336 of file FieldField.C.
References PtrList< T >::PtrList(), and Foam::T().
Referenced by Moment< Type >::Moment().
operator[]() [1/2]
template<template< class > class Field, class Type > const Type & operator[] (const labelPair & index) const inline
Definition at line 351 of file FieldField.C.
References Pair< T >::first(), UPtrList< T >::operator[](), and Pair< T >::second().
operator[]() [2/2]
template<template< class > class Field, class Type > Type & operator[] (const labelPair & index) inline
Definition at line 358 of file FieldField.C.
References Pair< T >::first(), UPtrList< T >::operator[](), and Pair< T >::second().
operator=() [1/5]
template<template< class > class Field, class Type > void operator= (const FieldField< Field, Type > & ff)
Definition at line 365 of file FieldField.C.
References forAll, and UPtrList< T >::operator[]().
Referenced by GeometricBoundaryField< Type, PatchField, GeoMesh >::operator=(), and GeometricBoundaryField< Type, PatchField, GeoMesh >::operator=().
operator=() [2/5]
template<template< class > class Field, class Type > void operator= (FieldField< Field, Type > && ff)
Definition at line 382 of file FieldField.C.
References PtrList< T >::transfer().
operator=() [3/5]
template<template< class > class Field, class Type > void operator= (const tmp< FieldField< Field, Type > > &)
operator=() [4/5]
template<template< class > class Field, class Type > void operator= (const Type & val)
Definition at line 414 of file FieldField.C.
References forAll, and UPtrList< T >::operator[]().
operator=() [5/5]
template<template< class > class Field, class Type > void operator= (const Foam::zero)
Definition at line 424 of file FieldField.C.
References forAll, and UPtrList< T >::operator[]().
operator+=() [1/3]
template<template< class > class Field, class Type > void operator+= (const FieldField< Field, Type > & f)
Definition at line 463 of file FieldField.C.
operator+=() [2/3]
template<template< class > class Field, class Type > void operator+= (const tmp< FieldField< Field, Type > > & tf)
Definition at line 463 of file FieldField.C.
operator-=() [1/3]
template<template< class > class Field, class Type > void operator-= (const FieldField< Field, Type > & f)
Definition at line 464 of file FieldField.C.
operator-=() [2/3]
template<template< class > class Field, class Type > void operator-= (const tmp< FieldField< Field, Type > > & tf)
Definition at line 464 of file FieldField.C.
operator*=() [1/3]
template<template< class > class Field, class Type > void operator*= (const FieldField< Field, scalar > & f)
Definition at line 465 of file FieldField.C.
operator*=() [2/3]
template<template< class > class Field, class Type > void operator*= (const tmp< FieldField< Field, scalar > > & tf)
Definition at line 465 of file FieldField.C.
operator/=() [1/3]
template<template< class > class Field, class Type > void operator/= (const FieldField< Field, scalar > & f)
Definition at line 466 of file FieldField.C.
operator/=() [2/3]
template<template< class > class Field, class Type > void operator/= (const tmp< FieldField< Field, scalar > > & tf)
Definition at line 466 of file FieldField.C.
operator+=() [3/3]
template<template< class > class Field, class Type > void operator+= (const Type & t)
Definition at line 463 of file FieldField.C.
operator-=() [3/3]
template<template< class > class Field, class Type > void operator-= (const Type & t)
Definition at line 464 of file FieldField.C.
operator*=() [3/3]
template<template< class > class Field, class Type > void operator*= (const scalar & t)
Definition at line 465 of file FieldField.C.
operator/=() [3/3]
template<template< class > class Field, class Type > void operator/= (const scalar & t)
Definition at line 466 of file FieldField.C.
Friends And Related Symbol Documentation
operator [1/2]
template<template< class > class Field, class Type > Ostream & operator (Ostream & , const FieldField< Field, Type > &) friend
operator [2/2]
template<template< class > class Field, class Type > Ostream & operator (Ostream & , const tmp< FieldField< Field, Type > > &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/fields/FieldFields/FieldField/FieldField.H
src/OpenFOAM/fields/FieldFields/FieldField/FieldField.C