OpenFOAM: eddyViscosity< BasicTurbulenceModel > Class Template Reference
eddyViscosity< BasicTurbulenceModel > Class Template Reference abstract
Turbulence models
Eddy viscosity turbulence model base class.
#include <eddyViscosity.H>
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from linearViscousStress< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
eddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~eddyViscosity ()=default
virtual bool read ()=0
virtual tmp< volScalarField > nut () const
virtual tmp< scalarField > nut (const label patchi) const
virtual tmp< volScalarField > k () const =0
virtual tmp< volSymmTensorField > R () const
virtual void validate ()
virtual void correct ()=0
Public Member Functions inherited from linearViscousStress< BasicTurbulenceModel >
linearViscousStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~linearViscousStress ()=default
virtual tmp< volSymmTensorField > devRhoReff () const
virtual tmp< volSymmTensorField > devRhoReff (const volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Protected Member Functions
virtual void correctNut ()=0
Protected Attributes
volScalarField nut_
Detailed Description
template<class BasicTurbulenceModel>
class Foam::eddyViscosity< BasicTurbulenceModel >
Eddy viscosity turbulence model base class.
Source files
eddyViscosity.H
eddyViscosity.C
Definition at line 51 of file eddyViscosity.H.
Member Typedef Documentation
alphaField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 72 of file eddyViscosity.H.
rhoField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 73 of file eddyViscosity.H.
transportModel
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 74 of file eddyViscosity.H.
Constructor & Destructor Documentation
eddyViscosity()
template<class BasicTurbulenceModel > eddyViscosity (const word & modelName, const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName)
Definition at line 29 of file eddyViscosity.C.
~eddyViscosity()
template<class BasicTurbulenceModel > virtual ~eddyViscosity () virtual default
Member Function Documentation
correctNut()
template<class BasicTurbulenceModel > virtual void correctNut () protected pure virtual
Implemented in kEpsilonLopesdaCosta< BasicTurbulenceModel >, kL< BasicTurbulenceModel >, kkLOmega, LamBremhorstKE, LienCubicKE, LienLeschziner, qZeta, ShihQuadraticKE, NicenoKEqn< BasicTurbulenceModel >, SmagorinskyZhang< BasicTurbulenceModel >, continuousGasKEpsilon< BasicTurbulenceModel >, LaheyKEpsilon< BasicTurbulenceModel >, mixtureKEpsilon< BasicTurbulenceModel >, kOmegaSSTBase< eddyViscosity< RASModel< BasicTurbulenceModel > > >, SpalartAllmarasBase< eddyViscosity< RASModel< BasicTurbulenceModel > > >, dynamicKEqn< BasicTurbulenceModel >, dynamicLagrangian< BasicTurbulenceModel >, kEqn< BasicTurbulenceModel >, sigma< BasicTurbulenceModel >, Smagorinsky< BasicTurbulenceModel >, WALE< BasicTurbulenceModel >, kEpsilon< BasicTurbulenceModel >, kEpsilon< EddyDiffusivity< compressible::turbulenceModel > >, kEpsilonPhitF< BasicTurbulenceModel >, kOmega< BasicTurbulenceModel >, kOmegaSST< BasicTurbulenceModel >, LaunderSharmaKE< BasicTurbulenceModel >, realizableKE< BasicTurbulenceModel >, RNGkEpsilon< BasicTurbulenceModel >, and SpalartAllmaras< BasicTurbulenceModel >.
read()
template<class BasicTurbulenceModel > bool read () pure virtual
Implements linearViscousStress< BasicTurbulenceModel >.
Implemented in PDRkEpsilon, kEpsilonLopesdaCosta< BasicTurbulenceModel >, kL< BasicTurbulenceModel >, kineticTheoryModel, phasePressureModel, kineticTheoryModel, phasePressureModel, buoyantKEpsilon< BasicTurbulenceModel >, kkLOmega, LamBremhorstKE, LienCubicKE, LienLeschziner, qZeta, ShihQuadraticKE, continuousGasKEqn< BasicTurbulenceModel >, NicenoKEqn< BasicTurbulenceModel >, SmagorinskyZhang< BasicTurbulenceModel >, continuousGasKEpsilon< BasicTurbulenceModel >, kOmegaSSTSato< BasicTurbulenceModel >, LaheyKEpsilon< BasicTurbulenceModel >, mixtureKEpsilon< BasicTurbulenceModel >, kOmegaSSTBase< eddyViscosity< RASModel< BasicTurbulenceModel > > >, SpalartAllmarasBase< eddyViscosity< RASModel< BasicTurbulenceModel > > >, DESModel< BasicTurbulenceModel >, dynamicKEqn< BasicTurbulenceModel >, dynamicLagrangian< BasicTurbulenceModel >, kEqn< BasicTurbulenceModel >, LESeddyViscosity< BasicTurbulenceModel >, sigma< BasicTurbulenceModel >, Smagorinsky< BasicTurbulenceModel >, WALE< BasicTurbulenceModel >, kEpsilon< BasicTurbulenceModel >, kEpsilon< EddyDiffusivity< compressible::turbulenceModel > >, kEpsilonPhitF< BasicTurbulenceModel >, kOmega< BasicTurbulenceModel >, kOmegaSSTLM< BasicTurbulenceModel >, kOmegaSSTSAS< BasicTurbulenceModel >, LaunderSharmaKE< BasicTurbulenceModel >, realizableKE< BasicTurbulenceModel >, and RNGkEpsilon< BasicTurbulenceModel >.
Definition at line 71 of file eddyViscosity.C.
nut() [1/2]
template<class BasicTurbulenceModel > virtual tmp< volScalarField > nut () const inline virtual
Definition at line 103 of file eddyViscosity.H.
References eddyViscosity< BasicTurbulenceModel >::nut_.
nut() [2/2]
template<class BasicTurbulenceModel > virtual tmp< scalarField > nut (const label patchi) const inline virtual
Definition at line 109 of file eddyViscosity.H.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), and eddyViscosity< BasicTurbulenceModel >::nut_.
k()
template<class BasicTurbulenceModel > virtual tmp< volScalarField > k () const pure virtual
Implemented in kEpsilonLopesdaCosta< BasicTurbulenceModel >, kL< BasicTurbulenceModel >, kineticTheoryModel, phasePressureModel, kineticTheoryModel, phasePressureModel, kkLOmega, LamBremhorstKE, LienCubicKE, LienLeschziner, qZeta, ShihQuadraticKE, mixtureKEpsilon< BasicTurbulenceModel >, kOmegaSSTBase< eddyViscosity< RASModel< BasicTurbulenceModel > > >, SpalartAllmarasBase< eddyViscosity< RASModel< BasicTurbulenceModel > > >, dynamicKEqn< BasicTurbulenceModel >, dynamicLagrangian< BasicTurbulenceModel >, kEqn< BasicTurbulenceModel >, sigma< BasicTurbulenceModel >, Smagorinsky< BasicTurbulenceModel >, WALE< BasicTurbulenceModel >, kEpsilon< BasicTurbulenceModel >, kEpsilon< EddyDiffusivity< compressible::turbulenceModel > >, kEpsilonPhitF< BasicTurbulenceModel >, kOmega< BasicTurbulenceModel >, LaunderSharmaKE< BasicTurbulenceModel >, realizableKE< BasicTurbulenceModel >, and RNGkEpsilon< BasicTurbulenceModel >.
R()
template<class BasicTurbulenceModel > Foam::tmp< Foam::volSymmTensorField > R () const virtual
Reimplemented in kineticTheoryModel, phasePressureModel, kineticTheoryModel, phasePressureModel, continuousGasKEpsilon< BasicTurbulenceModel >, nonlinearEddyViscosity< BasicTurbulenceModel >, and nonlinearEddyViscosity< incompressible::RASModel >.
Definition at line 79 of file eddyViscosity.C.
validate()
template<class BasicTurbulenceModel > void validate () virtual
Reimplemented in kkLOmega.
Definition at line 121 of file eddyViscosity.C.
correct()
template<class BasicTurbulenceModel > void correct () pure virtual
Implements linearViscousStress< BasicTurbulenceModel >.
Implemented in PDRkEpsilon, kEpsilonLopesdaCosta< BasicTurbulenceModel >, kL< BasicTurbulenceModel >, kineticTheoryModel, phasePressureModel, kineticTheoryModel, phasePressureModel, kkLOmega, LamBremhorstKE, LienCubicKE, LienLeschziner, qZeta, ShihQuadraticKE, kOmegaSSTSato< BasicTurbulenceModel >, LaheyKEpsilon< BasicTurbulenceModel >, mixtureKEpsilon< BasicTurbulenceModel >, kOmegaSSTBase< eddyViscosity< RASModel< BasicTurbulenceModel > > >, SpalartAllmarasBase< eddyViscosity< RASModel< BasicTurbulenceModel > > >, dynamicKEqn< BasicTurbulenceModel >, dynamicLagrangian< BasicTurbulenceModel >, kEqn< BasicTurbulenceModel >, sigma< BasicTurbulenceModel >, Smagorinsky< BasicTurbulenceModel >, WALE< BasicTurbulenceModel >, kEpsilon< BasicTurbulenceModel >, kEpsilon< EddyDiffusivity< compressible::turbulenceModel > >, kEpsilonPhitF< BasicTurbulenceModel >, kOmega< BasicTurbulenceModel >, kOmegaSSTLM< BasicTurbulenceModel >, LaunderSharmaKE< BasicTurbulenceModel >, realizableKE< BasicTurbulenceModel >, and RNGkEpsilon< BasicTurbulenceModel >.
Definition at line 128 of file eddyViscosity.C.
Referenced by kkLOmega::correct(), LamBremhorstKE::correct(), LienCubicKE::correct(), LienLeschziner::correct(), qZeta::correct(), and ShihQuadraticKE::correct().
Member Data Documentation
nut_
template<class BasicTurbulenceModel > volScalarField nut_ protected
Definition at line 62 of file eddyViscosity.H.
Referenced by LienCubicKE::correct(), ShihQuadraticKE::correct(), LienCubicKE::correctNonlinearStress(), ShihQuadraticKE::correctNonlinearStress(), LienCubicKE::DepsilonEff(), ShihQuadraticKE::DepsilonEff(), LienCubicKE::DkEff(), ShihQuadraticKE::DkEff(), eddyViscosity< BasicTurbulenceModel >::nut(), and eddyViscosity< BasicTurbulenceModel >::nut().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/eddyViscosity/eddyViscosity.H
src/TurbulenceModels/turbulenceModels/eddyViscosity/eddyViscosity.C