OpenFOAM: ReversibleReaction< ReactionType, ReactionThermo, ReactionRate > Class Template Reference
ReversibleReaction< ReactionType, ReactionThermo, ReactionRate > Class Template Reference
Thermophysical models » Specie » Reactions
Simple extension of Reaction to handle reversible reactions using equilibrium thermodynamics.
#include <ReversibleReaction.H>
Public Member Functions
TypeName ("reversible")
ReversibleReaction (const ReactionType< ReactionThermo > &reaction, const ReactionRate &k)
ReversibleReaction (const ReversibleReaction< ReactionType, ReactionThermo, ReactionRate > &, const speciesTable &species)
ReversibleReaction (const speciesTable &species, const ReactionTable< ReactionThermo > &thermoDatabase, const dictionary &dict)
virtual autoPtr< ReactionType< ReactionThermo > > clone () const
virtual autoPtr< ReactionType< ReactionThermo > > clone (const speciesTable &species) const
virtual ~ReversibleReaction ()=default
virtual scalar kf (const scalar p, const scalar T, const scalarField &c) const
virtual scalar kr (const scalar kfwd, const scalar p, const scalar T, const scalarField &c) const
virtual scalar kr (const scalar p, const scalar T, const scalarField &c) const
virtual void write (Ostream &) const
Detailed Description
template<template< class > class ReactionType, class ReactionThermo, class ReactionRate>
class Foam::ReversibleReaction< ReactionType, ReactionThermo, ReactionRate >
Simple extension of Reaction to handle reversible reactions using equilibrium thermodynamics.
Source files
ReversibleReaction.H
ReversibleReaction.C
Definition at line 57 of file ReversibleReaction.H.
Constructor & Destructor Documentation
ReversibleReaction() [1/3]
template<template< class > class ReactionType, class ReactionThermo , class ReactionRate > ReversibleReaction (const ReactionType< ReactionThermo > & reaction, const ReactionRate & k)
Definition at line 32 of file ReversibleReaction.C.
ReversibleReaction() [2/3]
template<template< class > class ReactionType, class ReactionThermo , class ReactionRate > ReversibleReaction (const ReversibleReaction< ReactionType, ReactionThermo, ReactionRate > & rr, const speciesTable & species)
Definition at line 69 of file ReversibleReaction.C.
ReversibleReaction() [3/3]
template<template< class > class ReactionType, class ReactionThermo , class ReactionRate > ReversibleReaction (const speciesTable & species, const ReactionTable< ReactionThermo > & thermoDatabase, const dictionary & dict)
Definition at line 50 of file ReversibleReaction.C.
~ReversibleReaction()
template<template< class > class ReactionType, class ReactionThermo , class ReactionRate > virtual ~ReversibleReaction () virtual default
Member Function Documentation
TypeName()
template<template< class > class ReactionType, class ReactionThermo , class ReactionRate > TypeName ("reversible")
clone() [1/2]
template<template< class > class ReactionType, class ReactionThermo , class ReactionRate > virtual autoPtr< ReactionType< ReactionThermo > > clone () const inline virtual
Definition at line 116 of file ReversibleReaction.H.
clone() [2/2]
template<template< class > class ReactionType, class ReactionThermo , class ReactionRate > virtual autoPtr< ReactionType< ReactionThermo > > clone (const speciesTable & species) const inline virtual
Definition at line 130 of file ReversibleReaction.H.
kf()
template<template< class > class ReactionType, class ReactionThermo , class ReactionRate > Foam::scalar kf (const scalar p, const scalar T, const scalarField & c) const virtual
Definition at line 94 of file ReversibleReaction.C.
References p, and T.
kr() [1/2]
template<template< class > class ReactionType, class ReactionThermo , class ReactionRate > Foam::scalar kr (const scalar kfwd, const scalar p, const scalar T, const scalarField & c) const virtual
Definition at line 116 of file ReversibleReaction.C.
References Foam::max(), p, and T.
kr() [2/2]
template<template< class > class ReactionType, class ReactionThermo , class ReactionRate > Foam::scalar kr (const scalar p, const scalar T, const scalarField & c) const virtual
Definition at line 139 of file ReversibleReaction.C.
References p, and T.
write()
template<template< class > class ReactionType, class ReactionThermo , class ReactionRate > void write (Ostream & os) const virtual
Definition at line 161 of file ReversibleReaction.C.
References os(), and Reaction< ReactionThermo >::write().
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/reaction/Reactions/ReversibleReaction/ReversibleReaction.H
src/thermophysicalModels/specie/reaction/Reactions/ReversibleReaction/ReversibleReaction.C