OpenFOAM: translatingWallVelocityFvPatchVectorField Class Reference
translatingWallVelocityFvPatchVectorField Class Reference
Boundary conditions » Wall | Boundary conditions » Generic
This boundary condition provides a velocity condition for translational motion on walls.
#include <translatingWallVelocityFvPatchVectorField.H>
Public Member Functions
TypeName ("translatingWallVelocity")
translatingWallVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
translatingWallVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
translatingWallVelocityFvPatchVectorField (const translatingWallVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
translatingWallVelocityFvPatchVectorField (const translatingWallVelocityFvPatchVectorField &)
virtual tmp< fvPatchVectorField > clone () const
translatingWallVelocityFvPatchVectorField (const translatingWallVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
This boundary condition provides a velocity condition for translational motion on walls.
Usage
Property Description Required Default value
U translational velocity yes
Example of the boundary condition specification:
    <patchName>
    {
        type            translatingWallVelocity;
        U               (100 0 0);
    }
The U entry is a Function1 of time, see Foam::Function1Types.
See also
Foam::fixedValueFvPatchField Foam::Function1Types
Source files
translatingWallVelocityFvPatchVectorField.H
translatingWallVelocityFvPatchVectorField.C
Definition at line 83 of file translatingWallVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
translatingWallVelocityFvPatchVectorField() [1/5]
translatingWallVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Definition at line 28 of file translatingWallVelocityFvPatchVectorField.C.
translatingWallVelocityFvPatchVectorField() [2/5]
translatingWallVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Definition at line 40 of file translatingWallVelocityFvPatchVectorField.C.
References translatingWallVelocityFvPatchVectorField::updateCoeffs().
translatingWallVelocityFvPatchVectorField() [3/5]
translatingWallVelocityFvPatchVectorField (const translatingWallVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 56 of file translatingWallVelocityFvPatchVectorField.C.
translatingWallVelocityFvPatchVectorField() [4/5]
translatingWallVelocityFvPatchVectorField (const translatingWallVelocityFvPatchVectorField & twvpvf)
Definition at line 70 of file translatingWallVelocityFvPatchVectorField.C.
translatingWallVelocityFvPatchVectorField() [5/5]
translatingWallVelocityFvPatchVectorField (const translatingWallVelocityFvPatchVectorField & twvpvf, const DimensionedField< vector, volMesh > & iF)
Definition at line 81 of file translatingWallVelocityFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("translatingWallVelocity")
clone() [1/2]
virtual tmp< fvPatchVectorField > clone () const inline virtual
Definition at line 133 of file translatingWallVelocityFvPatchVectorField.H.
clone() [2/2]
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Definition at line 149 of file translatingWallVelocityFvPatchVectorField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 95 of file translatingWallVelocityFvPatchVectorField.C.
References n, Field< vector >::operator=(), and U.
Referenced by translatingWallVelocityFvPatchVectorField::translatingWallVelocityFvPatchVectorField().
write()
void write (Ostream & os) const virtual
Definition at line 113 of file translatingWallVelocityFvPatchVectorField.C.
References os(), fvPatchField< Type >::write(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/translatingWallVelocity/translatingWallVelocityFvPatchVectorField.H
src/finiteVolume/fields/fvPatchFields/derived/translatingWallVelocity/translatingWallVelocityFvPatchVectorField.C