OpenFOAM: treeBoundBox Class Reference
treeBoundBox Class Reference
Standard boundBox with extra functionality for use in octree.
#include <treeBoundBox.H>
Public Types
enum octantBit : direction { RIGHTHALF = 1 , TOPHALF = 2 , FRONTHALF = 4 }
enum faceId : direction {
LEFT = 0 , RIGHT = 1 , BOTTOM = 2 , TOP = 3 ,
BACK = 4 , FRONT = 5
}
enum faceBit : direction {
NOFACE = 0 , LEFTBIT = (1 << LEFT) , RIGHTBIT = (1 << RIGHT) , BOTTOMBIT = (1 << BOTTOM) ,
TOPBIT = (1 << TOP) , BACKBIT = (1 << BACK) , FRONTBIT = (1 << FRONT)
}
enum edgeId {
E01 = 0 , E13 = 1 , E23 = 2 , E02 = 3 ,
E45 = 4 , E57 = 5 , E67 = 6 , E46 = 7 ,
E04 = 8 , E15 = 9 , E37 = 10 , E26 = 11
}
Public Types inherited from boundBox
enum directionBit : direction { XDIR = 1 , YDIR = 2 , ZDIR = 4 }
Public Member Functions
treeBoundBox ()=default
treeBoundBox (const treeBoundBox &)=default
treeBoundBox & operator= (const treeBoundBox &)=default
treeBoundBox (const boundBox &bb)
void operator= (const boundBox &bb)
treeBoundBox (const Foam::zero_one)
treeBoundBox (const point &p)
treeBoundBox (const point &min, const point &max)
treeBoundBox (const Pair< point > &bb)
treeBoundBox (const UList< point > &points)
treeBoundBox (const UList< point > &points, const labelUList &indices)
template<unsigned N>
treeBoundBox (const UList< point > &points, const FixedList< label, N > &indices)
treeBoundBox (Istream &is)
tmp< pointField > points () const
point corner (const direction octant) const
treeBoundBox subBbox (const direction octant) const
treeBoundBox subBbox (const point &mid, const direction) const
treeBoundBox subHalf (const direction whichFace) const
treeBoundBox subHalf (const scalar mid, const direction whichFace) const
direction subOctant (const point &pt) const
direction subOctant (const point &pt, bool &onEdge) const
void searchOrder (const point &pt, FixedList< direction, 8 > &octantOrder) const
FixedList< direction, 8 > searchOrder (const point &pt) const
bool subOverlaps (const direction octant, const boundBox &bb) const
bool subOverlaps (const direction octant, const point &centre, const scalar radiusSqr) const
bool intersects (const point &overallStart, const vector &overallVec, const point &start, const point &end, point &pt, direction &ptBits) const
bool intersects (const point &start, const point &end, point &pt) const
bool intersects (const linePointRef &ln, point &pt) const
bool contains (const vector &dir, const point &) const
direction faceBits (const point &pt) const
direction posBits (const point &pt) const
void calcExtremities (const point &pt, point &nearest, point &furthest) const
scalar maxDist (const point &pt) const
label distanceCmp (const point &pt, const treeBoundBox &other) const
treeBoundBox extend (Random &rndGen, const scalar s) const
treeBoundBox extend (Random &rndGen, const scalar s, const scalar delta) const
scalar typDim () const
bool overlaps (const boundBox &bb) const
bool overlaps (const point &centre, const scalar radiusSqr) const
bool intersects (const plane &pln) const
bool intersects (const triPointRef &tri) const
bool contains (const point &pt) const
bool contains (const boundBox &bb) const
bool contains (const UList< point > &points) const
template<unsigned N>
bool contains (const UList< point > &points, const FixedList< label, N > &indices) const
template<class IntContainer >
bool contains (const UList< point > &points, const IntContainer &indices) const
Public Member Functions inherited from boundBox
boundBox ()
boundBox (const boundBox &)=default
boundBox & operator= (const boundBox &)=default
boundBox (const boundBox &bb, bool doReduce)
boundBox (const point &p)
boundBox (const Foam::zero_one)
boundBox (const point &min, const point &max)
boundBox (const Pair< point > &bb)
boundBox (const UList< point > &points, bool doReduce=true)
boundBox (const tmp< pointField > &tpoints, bool doReduce=true)
boundBox (const UList< point > &points, const labelUList &indices, bool doReduce=true)
template<unsigned N>
boundBox (const UList< point > &points, const FixedList< label, N > &indices, bool doReduce=true)
boundBox (Istream &is)
bool empty () const
bool good () const
bool valid () const
const point & min () const noexcept
const point & max () const noexcept
point & min () noexcept
point & max () noexcept
point centre () const
vector span () const
scalar mag () const
scalar magSqr () const
scalar volume () const
scalar minDim () const
scalar maxDim () const
scalar avgDim () const
direction minDir () const
direction maxDir () const
int nDim () const
template<direction CornerNumber>
point hexCorner () const
tmp< pointField > hexCorners () const
tmp< pointField > points () const
tmp< pointField > faceCentres () const
point faceCentre (const direction facei) const
void reset ()
void reset (const Foam::zero_one)
void reset (const point &pt)
void reset (const point &min, const point &max)
void clear ()
void add (const boundBox &bb)
void add (const point &pt)
void add (const point &pt0, const point &pt1)
void add (const Pair< point > &points)
void add (const UList< point > &points)
void add (const tmp< pointField > &tpoints)
template<unsigned N>
void add (const FixedList< point, N > &points)
template<unsigned N>
void add (const UList< point > &points, const FixedList< label, N > &indices)
template<class IntContainer >
void add (const UList< point > &points, const IntContainer &indices)
void grow (const scalar delta)
void grow (const vector &delta)
void inflate (const scalar factor)
void inflate (Random &rndGen, const scalar factor)
void inflate (Random &r, const scalar factor, const scalar delta)
void reduce ()
bool intersects (const plane &pln) const
bool intersects (const triPointRef &tri) const
bool overlaps (const boundBox &bb) const
bool overlaps (const point &centre, const scalar radiusSqr) const
bool contains (const point &pt) const
bool contains (const boundBox &bb) const
bool containsInside (const point &pt) const
bool contains (const UList< point > &points) const
template<unsigned N>
bool contains (const UList< point > &points, const FixedList< label, N > &indices) const
template<class IntContainer >
bool contains (const UList< point > &points, const IntContainer &indices) const
bool containsAny (const UList< point > &points) const
template<unsigned N>
bool containsAny (const UList< point > &points, const FixedList< label, N > &indices) const
template<class IntContainer >
bool containsAny (const UList< point > &points, const IntContainer &indices) const
point nearest (const point &p) const
void operator&= (const boundBox &bb)
void operator+= (const boundBox &bb)
bool intersect (const boundBox &bb)
point midpoint () const
template<>
Foam::point hexCorner () const
template<>
Foam::point hexCorner () const
template<>
Foam::point hexCorner () const
template<>
Foam::point hexCorner () const
template<>
Foam::point hexCorner () const
template<>
Foam::point hexCorner () const
template<>
Foam::point hexCorner () const
template<>
Foam::point hexCorner () const
template<Foam::direction CornerNumber>
Foam::point hexCorner () const
Static Public Member Functions
static const treeBoundBox & null () noexcept
static direction subOctant (const point &mid, const point &pt)
static direction subOctant (const point &mid, const point &pt, bool &onEdge)
static direction subOctant (const point &mid, const vector &dir, const point &pt, bool &onEdge)
Static Public Member Functions inherited from boundBox
static const boundBox & null () noexcept
static const Foam::faceList & hexFaces ()
static constexpr label nPoints () noexcept
static constexpr label nEdges () noexcept
static constexpr label nFaces () noexcept
static boundBox returnReduce (const boundBox &bb)
Static Public Attributes
static const faceList faces
static const edgeList edges
Static Public Attributes inherited from boundBox
static const boundBox greatBox
static const boundBox invertedBox
static const FixedList< vector, 6 > faceNormals
Friends
Istream & operator>> (Istream &is, treeBoundBox &bb)
Ostream & operator<< (Ostream &os, const treeBoundBox &bb)
Additional Inherited Members
Static Protected Member Functions inherited from boundBox
static bool box_box_overlaps (const point &minA, const point &maxA, const point &minB, const point &maxB)
static bool box_sphere_overlaps (const point &corner0, const point &corner1, const point &centre, const scalar radiusSqr)
Detailed Description
Standard boundBox with extra functionality for use in octree.
Numbering of corner points is according to octant numbering as shown below. For vertex numbering in the sequence 0 to 7:
faces 0 and 1 are x-min and x-max, respectively;
faces 2 and 3 are y-min and y-max, respectively;
faces 4 and 5 are z-min and z-max, respectively.
Octant vertex ordering               | Hex cell ordering
(treeBoundBox)                       | (boundBox, blockMesh, hexCell)
                                     |
                6 ---- 7             |         7 ---- 6
          f5    |\     :\    f3      |   f5    |\     :\    f3
           |    | 4 ---- 5    \      |    |    | 4 ---- 5    \
           |    2.|....3 |     \     |    |    3.|....2 |     \
           |     \|     \|     f2    |    |     \|     \|     f2
          f4      0 ---- 1           |   f4      0 ---- 1
  Y  Z                               |
   \ |          f0 ------ f1         |         f0 ------ f1
    \|                               |
     o--- X                          |
Note
When a bounding box is created without any points, it creates an inverted bounding box. Points can be added later and the bounding box will grow to include them.
See also
Foam::boundBox
Source files
treeBoundBox.H
treeBoundBoxI.H
treeBoundBox.C
treeBoundBoxTemplates.C
Definition at line 90 of file treeBoundBox.H.
Member Enumeration Documentation
octantBit
enum octantBit : direction
Enumerator
RIGHTHALF
1: positive x-direction
TOPHALF
2: positive y-direction
FRONTHALF
4: positive z-direction
Definition at line 101 of file treeBoundBox.H.
faceId
enum faceId : direction
Enumerator
LEFT
0: x-min face
RIGHT
1: x-max face
BOTTOM
2: y-min face
TOP
3: y-max face
BACK
4: z-min face
FRONT
5: z-max face
Definition at line 111 of file treeBoundBox.H.
faceBit
enum faceBit : direction
Enumerator
NOFACE
0: none
LEFTBIT
1: x-min face
RIGHTBIT
2: x-max face
BOTTOMBIT
4: y-min face
TOPBIT
8: y-max face
BACKBIT
16: z-min face
FRONTBIT
32: z-max face
Definition at line 125 of file treeBoundBox.H.
edgeId
enum edgeId
Enumerator
E01
E13
E23
E02
E45
E57
E67
E46
E04
E15
E37
E26
Definition at line 138 of file treeBoundBox.H.
Constructor & Destructor Documentation
treeBoundBox() [1/11]
treeBoundBox () default
treeBoundBox() [2/11]
treeBoundBox (const treeBoundBox &) default
treeBoundBox() [3/11]
treeBoundBox (const boundBox & bb) inline explicit
Definition at line 188 of file treeBoundBox.H.
treeBoundBox() [4/11]
treeBoundBox (const Foam::zero_one) inline explicit
Definition at line 27 of file treeBoundBoxI.H.
treeBoundBox() [5/11]
treeBoundBox (const point & p) inline explicit
Definition at line 33 of file treeBoundBoxI.H.
treeBoundBox() [6/11]
treeBoundBox (const point & min, const point & max) inline
Definition at line 39 of file treeBoundBoxI.H.
treeBoundBox() [7/11]
treeBoundBox (const Pair< point > & bb) inline explicit
TBD: Construct from bound box min/max points inline explicit treeBoundBox(const MinMax<point>& bb);
Definition at line 45 of file treeBoundBoxI.H.
treeBoundBox() [8/11]
treeBoundBox (const UList< point > & points) explicit
Definition at line 57 of file treeBoundBox.C.
References UPtrList< T >::empty(), Foam::nl, treeBoundBox::points(), and WarningInFunction.
treeBoundBox() [9/11]
treeBoundBox (const UList< point > & points, const labelUList & indices)
Definition at line 69 of file treeBoundBox.C.
References UList< T >::empty(), UPtrList< T >::empty(), Foam::nl, treeBoundBox::points(), and WarningInFunction.
treeBoundBox() [10/11]
template<unsigned N> treeBoundBox (const UList< point > & points, const FixedList< label, N > & indices)
Definition at line 27 of file treeBoundBoxTemplates.C.
References UPtrList< T >::empty(), Foam::nl, treeBoundBox::points(), and WarningInFunction.
treeBoundBox() [11/11]
treeBoundBox (Istream & is) inline explicit
Definition at line 51 of file treeBoundBoxI.H.
Member Function Documentation
null()
static const treeBoundBox & null () inline static noexcept
Definition at line 169 of file treeBoundBox.H.
References boundBox::invertedBox.
Referenced by dynamicIndexedOctree< Type >::bb(), and indexedOctree< Type >::bb().
operator=() [1/2]
treeBoundBox & operator= (const treeBoundBox &) default
operator=() [2/2]
void operator= (const boundBox & bb) inline
Definition at line 191 of file treeBoundBox.H.
points()
Foam::tmp< Foam::pointField > points () const
Definition at line 87 of file treeBoundBox.C.
References forAll, tmp< T >::New(), and pts.
Referenced by searchableBox::boundingSpheres(), searchableBox::coordinates(), searchableBox::points(), treeBoundBox::treeBoundBox(), treeBoundBox::treeBoundBox(), treeBoundBox::treeBoundBox(), OBJstream::write(), box::writeBoxes(), Foam::meshTools::writeOBJ(), AABBTreeBase::writeOBJ(), and indexedOctreeBase::writeOBJ().
corner()
Foam::point corner (const direction octant) const inline
Definition at line 59 of file treeBoundBoxI.H.
References Foam::max(), Foam::min(), and x.
subBbox() [1/2]
Foam::treeBoundBox subBbox (const direction octant) const
Definition at line 204 of file treeBoundBox.C.
Referenced by dynamicIndexedOctree< Type >::print(), and indexedOctree< Type >::print().
subBbox() [2/2]
Foam::treeBoundBox subBbox (const point & mid, const direction octant) const
Definition at line 101 of file treeBoundBox.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, treeBoundBox::FRONTHALF, boundBox::max(), Foam::max(), boundBox::min(), Foam::min(), treeBoundBox::RIGHTHALF, and treeBoundBox::TOPHALF.
subHalf() [1/2]
Foam::treeBoundBox subHalf (const direction whichFace) const
Definition at line 184 of file treeBoundBox.C.
References Foam::max(), Foam::min(), Vector< scalar >::X, Vector< scalar >::Y, and Vector< scalar >::Z.
subHalf() [2/2]
Foam::treeBoundBox subHalf (const scalar mid, const direction whichFace) const
Definition at line 150 of file treeBoundBox.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, boundBox::max(), and boundBox::min().
subOctant() [1/5]
Foam::direction subOctant (const point & pt) const inline
Definition at line 71 of file treeBoundBoxI.H.
subOctant() [2/5]
Foam::direction subOctant (const point & mid, const point & pt) inline static
Definition at line 79 of file treeBoundBoxI.H.
References treeBoundBox::FRONTHALF, treeBoundBox::RIGHTHALF, treeBoundBox::TOPHALF, Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
subOctant() [3/5]
Foam::direction subOctant (const point & pt, bool & onEdge) const inline
Definition at line 108 of file treeBoundBoxI.H.
subOctant() [4/5]
Foam::direction subOctant (const point & mid, const point & pt, bool & onEdge) inline static
Definition at line 120 of file treeBoundBoxI.H.
References treeBoundBox::FRONTHALF, treeBoundBox::RIGHTHALF, treeBoundBox::TOPHALF, Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
subOctant() [5/5]
Foam::direction subOctant (const point & mid, const vector & dir, const point & pt, bool & onEdge) inline static
Definition at line 165 of file treeBoundBoxI.H.
References treeBoundBox::FRONTHALF, treeBoundBox::RIGHTHALF, treeBoundBox::TOPHALF, Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
searchOrder() [1/2]
void searchOrder (const point & pt, FixedList< direction, 8 > & octantOrder) const inline
Definition at line 219 of file treeBoundBoxI.H.
References treeBoundBox::FRONTHALF, Foam::max(), Foam::min(), treeBoundBox::RIGHTHALF, treeBoundBox::TOPHALF, Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
searchOrder() [2/2]
Foam::FixedList< Foam::direction, 8 > searchOrder (const point & pt) const inline
Definition at line 310 of file treeBoundBoxI.H.
subOverlaps() [1/2]
bool subOverlaps (const direction octant, const boundBox & bb) const
Definition at line 210 of file treeBoundBox.C.
References boundBox::max(), Foam::max(), boundBox::min(), and Foam::min().
subOverlaps() [2/2]
bool subOverlaps (const direction octant, const point & centre, const scalar radiusSqr) const inline
Definition at line 318 of file treeBoundBoxI.H.
intersects() [1/5]
bool intersects (const point & overallStart, const vector & overallVec, const point & start, const point & end, point & pt, direction & ptBits) const
Definition at line 254 of file treeBoundBox.C.
References Foam::mag(), Foam::max(), Foam::min(), s(), Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
Referenced by streamLineBase::trimToBox().
intersects() [2/5]
bool intersects (const point & start, const point & end, point & pt) const
Definition at line 401 of file treeBoundBox.C.
intersects() [3/5]
bool intersects (const linePointRef & ln, point & pt) const inline
Definition at line 339 of file treeBoundBoxI.H.
References UPtrList< T >::end(), and Foam::ln().
contains() [1/6]
bool contains (const vector & dir, const point & pt) const
Definition at line 413 of file treeBoundBox.C.
References Foam::max(), Foam::min(), and VectorSpace< Form, Cmpt, Ncmpts >::nComponents.
Referenced by surfaceFeatures::deleteBox(), searchableBox::getVolumeType(), streamLineBase::trimToBox(), propellerInfo::updateSampleDiskCells(), and dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::writeOBJ().
faceBits()
Foam::direction faceBits (const point & pt) const
Definition at line 451 of file treeBoundBox.C.
References Foam::max(), Foam::min(), x, Vector< Cmpt >::x(), y, Vector< Cmpt >::y(), and Vector< Cmpt >::z().
posBits()
Foam::direction posBits (const point & pt) const
Definition at line 486 of file treeBoundBox.C.
References Foam::max(), Foam::min(), x, Vector< Cmpt >::x(), y, Vector< Cmpt >::y(), and Vector< Cmpt >::z().
Referenced by treeDataCell::findIntersectOp::operator()().
calcExtremities()
void calcExtremities (const point & pt, point & nearest, point & furthest) const
Definition at line 521 of file treeBoundBox.C.
References Foam::mag(), Foam::max(), Foam::min(), and VectorSpace< Form, Cmpt, Ncmpts >::nComponents.
Referenced by treeBoundBox::distanceCmp().
maxDist()
Foam::scalar maxDist (const point & pt) const
Definition at line 548 of file treeBoundBox.C.
References Vector< Cmpt >::dist().
distanceCmp()
Foam::label distanceCmp (const point & pt, const treeBoundBox & other) const
Definition at line 557 of file treeBoundBox.C.
References treeBoundBox::calcExtremities(), and Vector< Cmpt >::distSqr().
extend() [1/2]
Foam::treeBoundBox extend (Random & rndGen, const scalar s) const inline
Definition at line 349 of file treeBoundBoxI.H.
References boundBox::inflate(), and rndGen.
Referenced by meshRefinement::distribute(), and mappedPatchBase::findLocalSamples().
extend() [2/2]
Foam::treeBoundBox extend (Random & rndGen, const scalar s, const scalar delta) const inline
Definition at line 363 of file treeBoundBoxI.H.
References delta, boundBox::inflate(), and rndGen.
typDim()
scalar typDim () const inline
Definition at line 432 of file treeBoundBox.H.
References boundBox::avgDim().
overlaps() [1/2]
bool overlaps (const boundBox & bb) const inline
Definition at line 388 of file boundBoxI.H.
Referenced by treeDataPrimitivePatch< PatchType >::overlaps().
overlaps() [2/2]
bool overlaps (const point & centre, const scalar radiusSqr) const inline
Definition at line 391 of file boundBoxI.H.
intersects() [4/5]
bool intersects (const plane & pln) const
Definition at line 379 of file boundBox.C.
intersects() [5/5]
bool intersects (const triPointRef & tri) const
Definition at line 385 of file boundBox.C.
contains() [2/6]
bool contains (const point & pt) const inline
Definition at line 398 of file boundBoxI.H.
contains() [3/6]
bool contains (const boundBox & bb) const inline
Definition at line 401 of file boundBoxI.H.
contains() [4/6]
bool contains (const UList< point > & points) const
Definition at line 407 of file boundBox.C.
contains() [5/6]
template<unsigned N> bool contains (const UList< point > & points, const FixedList< label, N > & indices) const inline
Definition at line 411 of file boundBoxTemplates.C.
contains() [6/6]
template<class IntContainer > bool contains (const UList< point > & points, const IntContainer & indices) const inline
Definition at line 423 of file boundBoxTemplates.C.
Friends And Related Symbol Documentation
operator>>
Istream & operator>> (Istream & is, treeBoundBox & bb) friend
operator<<
Ostream & operator<< (Ostream & os, const treeBoundBox & bb) friend
Member Data Documentation
faces
const Foam::faceList faces static
Definition at line 160 of file treeBoundBox.H.
Referenced by searchableBox::boundingSpheres(), searchableBox::coordinates(), searchableRotatedBox::overlaps(), OBJstream::write(), box::writeBoxes(), AABBTreeBase::writeOBJ(), and indexedOctreeBase::writeOBJ().
edges
const Foam::edgeList edges static
Definition at line 163 of file treeBoundBox.H.
Referenced by triangleFuncs::intersectBb(), searchableRotatedBox::overlaps(), OBJstream::write(), AABBTreeBase::writeOBJ(), and indexedOctreeBase::writeOBJ().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/treeBoundBox/treeBoundBox.H
src/OpenFOAM/meshes/treeBoundBox/treeBoundBox.C
src/OpenFOAM/meshes/treeBoundBox/treeBoundBoxI.H
src/OpenFOAM/meshes/treeBoundBox/treeBoundBoxTemplates.C