OpenFOAM: timeFunctionObject Class Reference
timeFunctionObject Class Reference
Virtual base class for function objects with a reference to Time.
#include <timeFunctionObject.H>
Public Member Functions
timeFunctionObject (const word &name, const Time &runTime)
virtual ~timeFunctionObject ()=default
const Time & time () const
objectRegistry & storedObjects ()
const objectRegistry & storedObjects () const
Public Member Functions inherited from functionObject
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name, const bool withNamePrefix=defaultUseNamePrefix)
autoPtr< functionObject > clone () const
virtual ~functionObject ()=default
virtual const word & type () const =0
const word & name () const noexcept
bool useNamePrefix () const noexcept
bool useNamePrefix (bool on) noexcept
virtual bool read (const dictionary &dict)
virtual bool execute ()=0
virtual bool execute (const label subIndex)
virtual bool write ()=0
virtual bool end ()
virtual bool adjustTimeStep ()
virtual bool filesModified () const
virtual void updateMesh (const mapPolyMesh &mpm)
virtual void movePoints (const polyMesh &mesh)
Protected Member Functions
void clearOutputObjects (const wordList &objNames)
timeFunctionObject (const timeFunctionObject &)=delete
void operator= (const timeFunctionObject &)=delete
Protected Member Functions inherited from functionObject
word scopedName (const word &name) const
Protected Attributes
const Time & time_
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &runTime, const dictionary &dict)
Public Attributes inherited from functionObject
bool log
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
static bool defaultUseNamePrefix
static word outputPrefix
Detailed Description
Virtual base class for function objects with a reference to Time.
See also
Foam::functionObject
Source files
timeFunctionObject.H
timeFunctionObject.C
Definition at line 52 of file timeFunctionObject.H.
Constructor & Destructor Documentation
timeFunctionObject() [1/2]
timeFunctionObject (const timeFunctionObject &) protected delete
timeFunctionObject() [2/2]
timeFunctionObject (const word & name, const Time & runTime)
Definition at line 26 of file timeFunctionObject.C.
References Foam::name().
~timeFunctionObject()
virtual ~timeFunctionObject () virtual default
Member Function Documentation
clearOutputObjects()
void clearOutputObjects (const wordList & objNames) protected
Definition at line 39 of file timeFunctionObject.C.
References objectRegistry::checkOut().
operator=()
void operator= (const timeFunctionObject &) protected delete
time()
const Time & time () const inline
Definition at line 92 of file timeFunctionObject.H.
References timeFunctionObject::time_.
Referenced by fieldAverage::addMeanFieldType(), and valueAverageBase::calc().
storedObjects() [1/2]
Foam::objectRegistry & storedObjects ()
Definition at line 56 of file timeFunctionObject.C.
Referenced by surfaceFieldValue::obr(), and regionFunctionObject::obr().
storedObjects() [2/2]
const Foam::objectRegistry & storedObjects () const
Definition at line 63 of file timeFunctionObject.C.
Member Data Documentation
time_
const Time& time_ protected
Definition at line 61 of file timeFunctionObject.H.
Referenced by blendingFactor::blendingFactor(), DESModelRegions::DESModelRegions(), codedFunctionObject::libs(), momentumError::momentumError(), stabilityBlendingFactor::stabilityBlendingFactor(), stateFunctionObject::stateDict(), and timeFunctionObject::time().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/functionObjects/timeFunctionObject/timeFunctionObject.H
src/OpenFOAM/db/functionObjects/timeFunctionObject/timeFunctionObject.C