OpenFOAM: LduMatrix< Type, DType, LUType >::preconditioner Class Reference
LduMatrix< Type, DType, LUType >::preconditioner Class Reference abstract
#include <LduMatrix.H>
Public Member Functions
virtual const word & type () const =0
declareRunTimeSelectionTable (autoPtr, preconditioner, symMatrix,(const solver &sol, const dictionary &preconditionerDict),(sol, preconditionerDict))
declareRunTimeSelectionTable (autoPtr, preconditioner, asymMatrix,(const solver &sol, const dictionary &preconditionerDict),(sol, preconditionerDict))
preconditioner (const solver &sol)
virtual ~preconditioner ()=default
virtual void read (const dictionary &)
virtual void precondition (Field< Type > &wA, const Field< Type > &rA) const =0
virtual void preconditionT (Field< Type > &wT, const Field< Type > &rT) const
Static Public Member Functions
static autoPtr< preconditioner > New (const solver &sol, const dictionary &preconditionerDict)
Protected Attributes
const solver & solver_
Detailed Description
template<class Type, class DType, class LUType>
class Foam::LduMatrix< Type, DType, LUType >::preconditioner
Definition at line 370 of file LduMatrix.H.
Constructor & Destructor Documentation
preconditioner()
template<class Type , class DType , class LUType > preconditioner (const solver & sol) inline
Definition at line 416 of file LduMatrix.H.
~preconditioner()
template<class Type , class DType , class LUType > virtual ~preconditioner () virtual default
Member Function Documentation
type()
template<class Type , class DType , class LUType > virtual const word & type () const pure virtual
declareRunTimeSelectionTable() [1/2]
template<class Type , class DType , class LUType > declareRunTimeSelectionTable (autoPtr , preconditioner , symMatrix , (const solver &sol, const dictionary &preconditionerDict) , (sol, preconditionerDict))
declareRunTimeSelectionTable() [2/2]
template<class Type , class DType , class LUType > declareRunTimeSelectionTable (autoPtr , preconditioner , asymMatrix , (const solver &sol, const dictionary &preconditionerDict) , (sol, preconditionerDict))
New()
template<class Type , class DType , class LUType > Foam::autoPtr< typename Foam::LduMatrix< Type, DType, LUType >::preconditioner > New (const solver & sol, const dictionary & preconditionerDict) static
Definition at line 28 of file LduMatrixPreconditioner.C.
References Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, FatalIOErrorInLookup, and UPtrList< T >::get().
Referenced by PBiCCCG< Type, DType, LUType >::solve(), PBiCICG< Type, DType, LUType >::solve(), and PCICG< Type, DType, LUType >::solve().
read()
template<class Type , class DType , class LUType > virtual void read (const dictionary &) inline virtual
Reimplemented in DiagonalPreconditioner< Type, DType, LUType >, and NoPreconditioner< Type, DType, LUType >.
Definition at line 440 of file LduMatrix.H.
precondition()
template<class Type , class DType , class LUType > virtual void precondition (Field< Type > & wA, const Field< Type > & rA) const pure virtual
Implemented in DiagonalPreconditioner< Type, DType, LUType >, TDILUPreconditioner< Type, DType, LUType >, and NoPreconditioner< Type, DType, LUType >.
preconditionT()
template<class Type , class DType , class LUType > virtual void preconditionT (Field< Type > & wT, const Field< Type > & rT) const inline virtual
Reimplemented in DiagonalPreconditioner< Type, DType, LUType >, TDILUPreconditioner< Type, DType, LUType >, and NoPreconditioner< Type, DType, LUType >.
Definition at line 453 of file LduMatrix.H.
References NotImplemented.
Member Data Documentation
solver_
template<class Type , class DType , class LUType > const solver& solver_ protected
Definition at line 377 of file LduMatrix.H.
Referenced by DiagonalPreconditioner< Type, DType, LUType >::DiagonalPreconditioner().
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/LduMatrix/LduMatrix/LduMatrix.H
src/OpenFOAM/matrices/LduMatrix/LduMatrix/LduMatrixPreconditioner.C