OpenFOAM: pointVolInterpolation Class Reference
pointVolInterpolation Class Reference
#include <pointVolInterpolation.H>
Public Member Functions
ClassName ("pointVolInterpolation")
pointVolInterpolation (const pointMesh &, const fvMesh &)
~pointVolInterpolation ()
const FieldField< Field, scalar > & volWeights () const
void updateTopology ()
bool movePoints ()
template<class Type >
void interpolate (const GeometricField< Type, pointPatchField, pointMesh > &, GeometricField< Type, fvPatchField, volMesh > &) const
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > interpolate (const GeometricField< Type, pointPatchField, pointMesh > &) const
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > interpolate (const tmp< GeometricField< Type, pointPatchField, pointMesh > > &) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > interpolate (const GeometricField< Type, pointPatchField, pointMesh > &pf) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > interpolate (const tmp< GeometricField< Type, pointPatchField, pointMesh > > &tpf) const
Protected Member Functions
const pointMesh & pMesh () const
const fvMesh & vMesh () const
Detailed Description
Source files
pointVolInterpolation.H
pointVolInterpolation.C
pointVolInterpolate.C
Definition at line 58 of file pointVolInterpolation.H.
Constructor & Destructor Documentation
pointVolInterpolation()
pointVolInterpolation (const pointMesh & pm, const fvMesh & vm)
Definition at line 163 of file pointVolInterpolation.C.
~pointVolInterpolation()
~pointVolInterpolation ()
Definition at line 178 of file pointVolInterpolation.C.
Member Function Documentation
pMesh()
const pointMesh & pMesh () const inline protected
Definition at line 89 of file pointVolInterpolation.H.
vMesh()
const fvMesh & vMesh () const inline protected
Definition at line 94 of file pointVolInterpolation.H.
Referenced by pointVolInterpolation::interpolate().
ClassName()
ClassName ("pointVolInterpolation")
volWeights()
const Foam::FieldField< Foam::Field, Foam::scalar > & volWeights () const
Definition at line 189 of file pointVolInterpolation.C.
Referenced by pointVolInterpolation::interpolate().
updateTopology()
void updateTopology ()
Definition at line 202 of file pointVolInterpolation.C.
movePoints()
bool movePoints ()
Definition at line 210 of file pointVolInterpolation.C.
interpolate() [1/5]
template<class Type > void interpolate (const GeometricField< Type, pointPatchField, pointMesh > & pf, GeometricField< Type, fvPatchField, volMesh > & vf) const
Definition at line 32 of file pointVolInterpolate.C.
References DebugInFunction, Foam::endl(), forAll, Foam::type(), pointVolInterpolation::vMesh(), and pointVolInterpolation::volWeights().
interpolate() [2/5]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > interpolate (const GeometricField< Type, pointPatchField, pointMesh > &) const
interpolate() [3/5]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > interpolate (const tmp< GeometricField< Type, pointPatchField, pointMesh > > &) const
interpolate() [4/5]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > interpolate (const GeometricField< Type, pointPatchField, pointMesh > & pf) const
Definition at line 88 of file pointVolInterpolate.C.
References Foam::interpolate().
interpolate() [5/5]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > interpolate (const tmp< GeometricField< Type, pointPatchField, pointMesh > > & tpf) const
Definition at line 118 of file pointVolInterpolate.C.
References PtrList< T >::clear(), and Foam::interpolate().
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/interpolation/pointVolInterpolation/pointVolInterpolation.H
src/optimisation/adjointOptimisation/adjoint/interpolation/pointVolInterpolation/pointVolInterpolate.C
src/optimisation/adjointOptimisation/adjoint/interpolation/pointVolInterpolation/pointVolInterpolation.C