OpenFOAM: KocamustafaogullariIshii Class Reference
KocamustafaogullariIshii Class Reference
A correlation for bubble departure diameter modelling based on Kocamustafaogullari-Ishii (1983) for boiling flows.
#include <KocamustafaogullariIshii.H>
Public Member Functions
TypeName ("KocamustafaogullariIshii")
KocamustafaogullariIshii (const dictionary &dict)
virtual ~KocamustafaogullariIshii ()=default
virtual tmp< scalarField > dDeparture (const phaseModel &liquid, const phaseModel &vapor, const label patchi, const scalarField &Tl, const scalarField &Tsatw, const scalarField &L) const
virtual void write (Ostream &os) const
Public Member Functions inherited from departureDiameterModel
TypeName ("departureDiameterModel")
declareRunTimeSelectionTable (autoPtr, departureDiameterModel, dictionary,(const dictionary &dict),(dict))
departureDiameterModel ()=default
virtual ~departureDiameterModel ()=default
Additional Inherited Members
Static Public Member Functions inherited from departureDiameterModel
static autoPtr< departureDiameterModel > New (const dictionary &dict)
Detailed Description
A correlation for bubble departure diameter modelling based on Kocamustafaogullari-Ishii (1983) for boiling flows.
Reference:
    Kocamustafaogullari, G., & Ishii, M. (1983).
    Interfacial area and nucleation site density in boiling systems.
    International Journal of Heat and Mass Transfer, 26(9), 1377-1387.
    DOI:10.1016/S0017-9310(83)80069-6
Usage
Example of the model specification:
departureDiameterModel
{
    // Mandatory entries
    type            KocamustafaogullariIshii;
    phi             <scalar>;
}
where the entries mean:
Property Description Type Reqd Deflt
type Type name: KocamustafaogullariIshii word yes -
phi Contact angle [deg] scalar yes -
Source files
KocamustafaogullariIshii.H
KocamustafaogullariIshii.C
Definition at line 96 of file KocamustafaogullariIshii.H.
Constructor & Destructor Documentation
KocamustafaogullariIshii()
KocamustafaogullariIshii (const dictionary & dict)
Definition at line 52 of file KocamustafaogullariIshii.C.
~KocamustafaogullariIshii()
virtual ~KocamustafaogullariIshii () virtual default
Member Function Documentation
TypeName()
TypeName ("KocamustafaogullariIshii")
dDeparture()
Foam::tmp< Foam::scalarField > dDeparture (const phaseModel & liquid, const phaseModel & vapor, const label patchi, const scalarField & Tl, const scalarField & Tsatw, const scalarField & L) const virtual
Implements departureDiameterModel.
Definition at line 66 of file KocamustafaogullariIshii.C.
References g, Foam::mag(), Foam::pow(), liquid::rho(), liquid::sigma(), and Foam::sqrt().
write()
void write (Ostream & os) const virtual
Reimplemented from departureDiameterModel.
Definition at line 98 of file KocamustafaogullariIshii.C.
References os(), and departureDiameterModel::write().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/wallBoilingSubModels/departureDiameterModels/KocamustafaogullariIshii/KocamustafaogullariIshii.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/wallBoilingSubModels/departureDiameterModels/KocamustafaogullariIshii/KocamustafaogullariIshii.C