OpenFOAM: surfaceIteratorIso Class Reference
surfaceIteratorIso Class Reference
Finds the isovalue that matches the volume fraction.
#include <surfaceIteratorIso.H>
Public Member Functions
surfaceIteratorIso (const fvMesh &mesh, scalarField &pointVal, const scalar tol)
bool isASurfaceCell (const scalar alpha1) const
label vofCutCell (const label celli, const scalar alpha1, const scalar tol, const label maxIter)
const point & subCellCentre () const
scalar subCellVolume () const
const point & surfaceCentre () const
const vector & surfaceArea () const
scalar VolumeOfFluid () const
scalar cutValue () const
label cellStatus ()
const DynamicList< point > & facePoints ()
Detailed Description
Finds the isovalue that matches the volume fraction.
Reference:
    Roenby, J., Bredmose, H. and Jasak, H. (2016).
    A computational method for sharp interface advection
    Royal Society Open Science, 3
    doi 10.1098/rsos.160405
Author Johan Roenby, DHI, all rights reserved.
Source files
surfaceIteratorIso.H
surfaceIteratorIso.C
Definition at line 60 of file surfaceIteratorIso.H.
Constructor & Destructor Documentation
surfaceIteratorIso()
surfaceIteratorIso (const fvMesh & mesh, scalarField & pointVal, const scalar tol)
Definition at line 26 of file surfaceIteratorIso.C.
Member Function Documentation
isASurfaceCell()
bool isASurfaceCell (const scalar alpha1) const inline
Definition at line 96 of file surfaceIteratorIso.H.
References alpha1.
vofCutCell()
Foam::label vofCutCell (const label celli, const scalar alpha1, const scalar tol, const label maxIter)
Definition at line 42 of file surfaceIteratorIso.C.
References alpha1, e, f(), UList< T >::first(), forAll, UList< T >::last(), Foam::LUsolve(), M, Foam::mag(), Foam::max(), Foam::min(), Foam::pow(), Foam::pow3(), UPtrList< T >::size(), Foam::sortedOrder(), and Foam::sqr().
subCellCentre()
const point & subCellCentre () const inline
Definition at line 116 of file surfaceIteratorIso.H.
References cutCellIso::subCellCentre().
subCellVolume()
scalar subCellVolume () const inline
Definition at line 122 of file surfaceIteratorIso.H.
References cutCellIso::subCellVolume().
surfaceCentre()
const point & surfaceCentre () const inline
Definition at line 128 of file surfaceIteratorIso.H.
References cutCellIso::faceCentre().
surfaceArea()
const vector & surfaceArea () const inline
Definition at line 134 of file surfaceIteratorIso.H.
References cutCellIso::faceArea().
VolumeOfFluid()
scalar VolumeOfFluid () const inline
Definition at line 140 of file surfaceIteratorIso.H.
References cutCellIso::VolumeOfFluid().
cutValue()
scalar cutValue () const inline
Definition at line 146 of file surfaceIteratorIso.H.
References cutCellIso::cutValue().
cellStatus()
label cellStatus () inline
Definition at line 152 of file surfaceIteratorIso.H.
References cutCellIso::cellStatus().
facePoints()
const DynamicList< point > & facePoints () inline
Definition at line 158 of file surfaceIteratorIso.H.
References cutCellIso::facePoints().
The documentation for this class was generated from the following files:
src/transportModels/geometricVoF/surfaceIterators/surfaceIteratorIso.H
src/transportModels/geometricVoF/surfaceIterators/surfaceIteratorIso.C