OpenFOAM: referenceTemperature Class Reference
referenceTemperature Class Reference
A heat exchanger model where heat exchange is calculated via a temperature table.
#include <referenceTemperature.H>
Public Member Functions
TypeName ("referenceTemperature")
referenceTemperature (const fvMesh &mesh, const word &name, const dictionary &coeffs)
referenceTemperature (const referenceTemperature &)=delete
void operator= (const referenceTemperature &)=delete
virtual ~referenceTemperature ()=default
virtual void initialise ()
virtual tmp< scalarField > energyDensity (const labelList &cells)
virtual bool read (const dictionary &dict)
virtual void write (const bool log)
Public Member Functions inherited from heatExchangerModel
TypeName ("heatExchangerModel")
declareRunTimeSelectionTable (autoPtr, heatExchangerModel, dictionary,(const fvMesh &mesh, const word &name, const dictionary &coeffs),(mesh, name, coeffs))
heatExchangerModel (const fvMesh &mesh, const word &name, const dictionary &coeffs)
heatExchangerModel (const heatExchangerModel &)=delete
void operator= (const heatExchangerModel &)=delete
virtual ~heatExchangerModel ()=default
virtual const word & U () const
Public Member Functions inherited from writeFile
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name="undefined", const bool writeToFile=true)
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name, const dictionary &dict, const bool writeToFile=true)
writeFile (const writeFile &wf)
virtual ~writeFile ()=default
virtual OFstream & file ()
virtual bool writeToFile () const
virtual bool canWriteToFile () const
virtual bool canResetFile () const
virtual bool canWriteHeader () const
virtual label charWidth () const
virtual void writeCommented (Ostream &os, const string &str) const
virtual void writeTabbed (Ostream &os, const string &str) const
virtual void writeHeader (Ostream &os, const string &str) const
virtual void writeCurrentTime (Ostream &os) const
virtual void writeBreak (Ostream &os) const
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
template<class Type >
void writeValue (Ostream &os, const Type &val) const
Additional Inherited Members
Static Public Member Functions inherited from heatExchangerModel
static autoPtr< heatExchangerModel > New (const fvMesh &mesh, const word &name, const dictionary &coeffs)
Static Public Attributes inherited from writeFile
static label addChars = 8
Protected Member Functions inherited from writeFile
void initStream (Ostream &os) const
fileName baseFileDir () const
fileName baseTimeDir () const
fileName filePath (const fileName &fName) const
virtual autoPtr< OFstream > newFile (const fileName &fName) const
virtual autoPtr< OFstream > newFileAtTime (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > newFileAtStartTime (const word &name) const
virtual void resetFile (const word &name)
Omanip< int > valueWidth (const label offset=0) const
void operator= (const writeFile &)=delete
virtual autoPtr< OFstream > createFile (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > createFile (const word &name) const
Protected Attributes inherited from heatExchangerModel
const fvMesh & mesh_
const dictionary & coeffs_
const word & name_
word UName_
word TName_
word phiName_
word faceZoneName_
labelList faceId_
labelList facePatchId_
labelList faceSign_
Protected Attributes inherited from writeFile
const objectRegistry & fileObr_
const fileName prefix_
word fileName_
autoPtr< OFstream > filePtr_
label writePrecision_
bool writeToFile_
bool updateHeader_
bool writtenHeader_
bool useUserTime_
scalar startTime_
Detailed Description
A heat exchanger model where heat exchange is calculated via a temperature table.
Usage
Minimal example by using constant/fvOptions:
<name>
{
    // Inherited entries
    ...
    // Mandatory entries
    model                    referenceTemperature;
    targetQdot               <Function1<scalar>>;
    // Conditional mandatory entries
        // Option-1
        Tref                     <scalar>;
        // Option-2
        file                     "<word>";
}
where the entries mean:
Property Description Type Reqd Deflt
model Model name:effectivenessTable word yes -
targetQdot
Target heat rejection [J/s]
Function1<scalar> yes -
Tref Reference temperature [K] scalar choice -
file
2D reference temperature table = function of primary
mass flow rate [kg/s] and primary flow temperature
file choice -
The inherited entries are elaborated in:
heatExchangerSource.H
interpolation2DTable.H
Source files
referenceTemperature.H
referenceTemperature.C
Definition at line 125 of file referenceTemperature.H.
Constructor & Destructor Documentation
referenceTemperature() [1/2]
referenceTemperature (const fvMesh & mesh, const word & name, const dictionary & coeffs)
Definition at line 183 of file referenceTemperature.C.
References writeFile::file().
referenceTemperature() [2/2]
referenceTemperature (const referenceTemperature &) delete
~referenceTemperature()
virtual ~referenceTemperature () virtual default
Member Function Documentation
TypeName()
TypeName ("referenceTemperature")
operator=()
void operator= (const referenceTemperature &) delete
initialise()
void initialise () virtual
Reimplemented from heatExchangerModel.
Definition at line 211 of file referenceTemperature.C.
References heatExchangerModel::initialise().
energyDensity()
Foam::tmp< Foam::scalarField > energyDensity (const labelList & cells) virtual
Implements heatExchangerModel.
Definition at line 218 of file referenceTemperature.C.
References cells, and Foam::mag().
read()
bool read (const dictionary & dict) virtual
Implements heatExchangerModel.
Definition at line 241 of file referenceTemperature.C.
References Foam::decrIndent(), dict, Foam::endl(), Foam::incrIndent(), Foam::indent(), Foam::Info, and Foam::type().
write()
void write (const bool log) virtual
Implements heatExchangerModel.
Definition at line 277 of file referenceTemperature.C.
References Foam::decrIndent(), Foam::endl(), Foam::incrIndent(), Foam::indent(), Foam::Info, Foam::log(), UPstream::master(), Foam::nl, os(), Foam::tab, and Foam::type().
The documentation for this class was generated from the following files:
src/fvOptions/sources/derived/heatExchangerSource/heatExchangerModels/referenceTemperature/referenceTemperature.H
src/fvOptions/sources/derived/heatExchangerSource/heatExchangerModels/referenceTemperature/referenceTemperature.C