OpenFOAM: cyclicLduInterfaceField Class Reference
cyclicLduInterfaceField Class Reference abstract
Abstract base class for cyclic coupled interfaces.
#include <cyclicLduInterfaceField.H>
Public Member Functions
TypeName ("cyclicLduInterfaceField")
cyclicLduInterfaceField ()=default
virtual ~cyclicLduInterfaceField ()=default
virtual bool doTransform () const =0
virtual const tensorField & forwardT () const =0
virtual const tensorField & reverseT () const =0
virtual int rank () const =0
template<class Type >
void transformCoupleField (Field< Type > &f) const
void transformCoupleField (solveScalarField &f, const direction cmpt) const
Detailed Description
Abstract base class for cyclic coupled interfaces.
Source files
cyclicLduInterfaceField.H
cyclicLduInterfaceField.C
Definition at line 48 of file cyclicLduInterfaceField.H.
Constructor & Destructor Documentation
cyclicLduInterfaceField()
cyclicLduInterfaceField () default
~cyclicLduInterfaceField()
virtual ~cyclicLduInterfaceField () virtual default
Member Function Documentation
TypeName()
TypeName ("cyclicLduInterfaceField")
doTransform()
virtual bool doTransform () const pure virtual
Implemented in cyclicFaPatchField< Type >, cyclicFvPatchField< Type >, cyclicFvPatchField< scalar >, cyclicFvPatchField< vector >, and cyclicGAMGInterfaceField.
Referenced by cyclicLduInterfaceField::transformCoupleField(), and cyclicLduInterfaceField::transformCoupleField().
forwardT()
virtual const tensorField & forwardT () const pure virtual
Implemented in cyclicFaPatchField< Type >, cyclicFvPatchField< Type >, cyclicFvPatchField< scalar >, cyclicFvPatchField< vector >, and cyclicGAMGInterfaceField.
Referenced by cyclicLduInterfaceField::transformCoupleField(), and cyclicLduInterfaceField::transformCoupleField().
reverseT()
virtual const tensorField & reverseT () const pure virtual
Implemented in cyclicFaPatchField< Type >, cyclicFvPatchField< Type >, cyclicFvPatchField< scalar >, cyclicFvPatchField< vector >, and cyclicGAMGInterfaceField.
rank()
virtual int rank () const pure virtual
Implemented in cyclicFaPatchField< Type >, cyclicFvPatchField< Type >, cyclicFvPatchField< scalar >, cyclicFvPatchField< vector >, and cyclicGAMGInterfaceField.
Referenced by cyclicLduInterfaceField::transformCoupleField().
transformCoupleField() [1/2]
template<class Type > void transformCoupleField (Field< Type > & f) const
Definition at line 106 of file cyclicLduInterfaceField.H.
References cyclicLduInterfaceField::doTransform(), f(), cyclicLduInterfaceField::forwardT(), and Foam::transform().
transformCoupleField() [2/2]
void transformCoupleField (solveScalarField & f, const direction cmpt) const
Definition at line 35 of file cyclicLduInterfaceField.C.
References Foam::component(), Foam::diag(), cyclicLduInterfaceField::doTransform(), f(), cyclicLduInterfaceField::forwardT(), Foam::pow(), and cyclicLduInterfaceField::rank().
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/lduMatrix/lduAddressing/lduInterfaceFields/cyclicLduInterfaceField/cyclicLduInterfaceField.H
src/OpenFOAM/matrices/lduMatrix/lduAddressing/lduInterfaceFields/cyclicLduInterfaceField/cyclicLduInterfaceField.C