OpenFOAM: heThermo< BasicThermo, MixtureType > Class Template Reference
heThermo< BasicThermo, MixtureType > Class Template Reference
Enthalpy/Internal energy for a mixture.
#include <heThermo.H>
Public Member Functions
heThermo (const fvMesh &, const word &phaseName)
heThermo (const fvMesh &, const dictionary &, const word &phaseName)
heThermo (const fvMesh &, const word &phaseName, const word &dictionaryName)
virtual ~heThermo ()
virtual MixtureType::basicMixtureType & composition ()
virtual const MixtureType::basicMixtureType & composition () const
virtual word thermoName () const
virtual bool incompressible () const
virtual bool isochoric () const
virtual volScalarField & he ()
virtual const volScalarField & he () const
virtual tmp< volScalarField > he (const volScalarField &p, const volScalarField &T) const
virtual tmp< scalarField > he (const scalarField &p, const scalarField &T, const labelList &cells) const
virtual tmp< scalarField > he (const scalarField &p, const scalarField &T, const label patchi) const
virtual tmp< volScalarField > hc () const
virtual tmp< scalarField > THE (const scalarField &he, const scalarField &p, const scalarField &T0, const labelList &cells) const
virtual tmp< scalarField > THE (const scalarField &he, const scalarField &p, const scalarField &T0, const label patchi) const
virtual tmp< scalarField > Cp (const scalarField &p, const scalarField &T, const label patchi) const
virtual tmp< scalarField > Cp (const scalarField &p, const scalarField &T, const labelList &cells) const
virtual tmp< volScalarField > Cp () const
virtual tmp< scalarField > Cv (const scalarField &p, const scalarField &T, const label patchi) const
virtual tmp< scalarField > rhoEoS (const scalarField &p, const scalarField &T, const labelList &cells) const
virtual tmp< volScalarField > Cv () const
virtual tmp< volScalarField > gamma () const
virtual tmp< scalarField > gamma (const scalarField &p, const scalarField &T, const label patchi) const
virtual tmp< scalarField > Cpv (const scalarField &p, const scalarField &T, const label patchi) const
virtual tmp< volScalarField > Cpv () const
virtual tmp< volScalarField > CpByCpv () const
virtual tmp< scalarField > CpByCpv (const scalarField &p, const scalarField &T, const label patchi) const
virtual tmp< volScalarField > W () const
virtual tmp< volScalarField > kappa () const
virtual tmp< scalarField > kappa (const label patchi) const
virtual tmp< volScalarField > alphahe () const
virtual tmp< scalarField > alphahe (const label patchi) const
virtual tmp< volScalarField > kappaEff (const volScalarField &) const
virtual tmp< scalarField > kappaEff (const scalarField &alphat, const label patchi) const
virtual tmp< volScalarField > alphaEff (const volScalarField &alphat) const
virtual tmp< scalarField > alphaEff (const scalarField &alphat, const label patchi) const
virtual bool read ()
Protected Member Functions
void heBoundaryCorrection (volScalarField &he)
Protected Attributes
volScalarField he_
Detailed Description
template<class BasicThermo, class MixtureType>
class Foam::heThermo< BasicThermo, MixtureType >
Enthalpy/Internal energy for a mixture.
Source files
heThermo.H
heThermo.C
Definition at line 48 of file heThermo.H.
Constructor & Destructor Documentation
heThermo() [1/3]
template<class BasicThermo , class MixtureType > heThermo (const fvMesh & mesh, const word & phaseName)
Definition at line 95 of file heThermo.C.
heThermo() [2/3]
template<class BasicThermo , class MixtureType > heThermo (const fvMesh & mesh, const dictionary & dict, const word & phaseName)
Definition at line 128 of file heThermo.C.
References Foam::dimEnergy, Foam::dimMass, and heThermo< BasicThermo, MixtureType >::he_.
heThermo() [3/3]
template<class BasicThermo , class MixtureType > heThermo (const fvMesh & mesh, const word & phaseName, const word & dictionaryName)
Definition at line 162 of file heThermo.C.
~heThermo()
template<class BasicThermo , class MixtureType > ~heThermo () virtual
Definition at line 199 of file heThermo.C.
Member Function Documentation
heBoundaryCorrection()
template<class BasicThermo , class MixtureType > void heBoundaryCorrection (volScalarField & he) protected
Definition at line 29 of file heThermo.C.
References forAll, h, and PtrList< T >::PtrList().
composition() [1/2]
template<class BasicThermo , class MixtureType > virtual MixtureType::basicMixtureType & composition () inline virtual
Definition at line 122 of file heThermo.H.
composition() [2/2]
template<class BasicThermo , class MixtureType > virtual const MixtureType::basicMixtureType & composition () const inline virtual
Definition at line 129 of file heThermo.H.
thermoName()
template<class BasicThermo , class MixtureType > virtual word thermoName () const inline virtual
Definition at line 135 of file heThermo.H.
incompressible()
template<class BasicThermo , class MixtureType > virtual bool incompressible () const inline virtual
Definition at line 142 of file heThermo.H.
isochoric()
template<class BasicThermo , class MixtureType > virtual bool isochoric () const inline virtual
Definition at line 149 of file heThermo.H.
he() [1/5]
template<class BasicThermo , class MixtureType > virtual volScalarField & he () inline virtual
Definition at line 159 of file heThermo.H.
References heThermo< BasicThermo, MixtureType >::he_.
he() [2/5]
template<class BasicThermo , class MixtureType > virtual const volScalarField & he () const inline virtual
Definition at line 165 of file heThermo.H.
References heThermo< BasicThermo, MixtureType >::he_.
he() [3/5]
template<class BasicThermo , class MixtureType > Foam::tmp< Foam::volScalarField > he (const volScalarField & p, const volScalarField & T) const virtual
Definition at line 206 of file heThermo.C.
he() [4/5]
template<class BasicThermo , class MixtureType > Foam::tmp< Foam::scalarField > he (const scalarField & p, const scalarField & T, const labelList & cells) const virtual
Definition at line 263 of file heThermo.C.
he() [5/5]
template<class BasicThermo , class MixtureType > Foam::tmp< Foam::scalarField > he (const scalarField & p, const scalarField & T, const label patchi) const virtual
Definition at line 283 of file heThermo.C.
hc()
template<class BasicThermo , class MixtureType > Foam::tmp< Foam::volScalarField > hc () const virtual
Definition at line 305 of file heThermo.C.
THE() [1/2]
template<class BasicThermo , class MixtureType > Foam::tmp< Foam::scalarField > THE (const scalarField & he, const scalarField & p, const scalarField & T0, const labelList & cells) const virtual
Definition at line 764 of file heThermo.C.
References cells, forAll, h, p, UList< T >::size(), T, and T0.
THE() [2/2]
template<class BasicThermo , class MixtureType > Foam::tmp< Foam::scalarField > THE (const scalarField & he, const scalarField & p, const scalarField & T0, const label patchi) const virtual
Definition at line 786 of file heThermo.C.
References forAll, h, p, UList< T >::size(), T, and T0.
Cp() [1/3]
template<class BasicThermo , class MixtureType > Foam::tmp< Foam::scalarField > Cp (const scalarField & p, const scalarField & T, const label patchi) const virtual
Definition at line 352 of file heThermo.C.
References cp, forAll, p, UPtrList< T >::size(), T, and tCp.
Cp() [2/3]
template<class BasicThermo , class MixtureType > Foam::tmp< Foam::scalarField > Cp (const scalarField & p, const scalarField & T, const labelList & cells) const virtual
Definition at line 374 of file heThermo.C.
References cells, Cp, forAll, tmp< T >::New(), p, UPtrList< T >::size(), T, and tCp.
Cp() [3/3]
template<class BasicThermo , class MixtureType > Foam::tmp< Foam::volScalarField > Cp () const virtual
Definition at line 396 of file heThermo.C.
References cp, Foam::dimEnergy, Foam::dimMass, Foam::dimTemperature, forAll, mesh, IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, pp(), tCp, and fvMesh::time().
Cv() [1/2]
template<class BasicThermo , class MixtureType > Foam::tmp< Foam::scalarField > Cv (const scalarField & p, const scalarField & T, const label patchi) const virtual
Definition at line 447 of file heThermo.C.
References forAll, p, UPtrList< T >::size(), T, and tCv.
rhoEoS()
template<class BasicThermo , class MixtureType > Foam::tmp< Foam::scalarField > rhoEoS (const scalarField & p, const scalarField & T, const labelList & cells) const virtual
Definition at line 469 of file heThermo.C.
References cells, forAll, tmp< T >::New(), p, rho, UPtrList< T >::size(), and T.
Cv() [2/2]
template<class BasicThermo , class MixtureType > Foam::tmp< Foam::volScalarField > Cv () const virtual
Definition at line 491 of file heThermo.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), Cv, Foam::dimEnergy, Foam::dimMass, Foam::dimTemperature, forAll, mesh, IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, tCv, and fvMesh::time().
gamma() [1/2]
template<class BasicThermo , class MixtureType > Foam::tmp< Foam::volScalarField > gamma () const virtual
Definition at line 560 of file heThermo.C.
References Foam::dimless, forAll, gamma, mesh, IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, pp(), and fvMesh::time().
gamma() [2/2]
template<class BasicThermo , class MixtureType > Foam::tmp< Foam::scalarField > gamma (const scalarField & p, const scalarField & T, const label patchi) const virtual
Definition at line 538 of file heThermo.C.
References forAll, gamma, p, UPtrList< T >::size(), and T.
Cpv() [1/2]
template<class BasicThermo , class MixtureType > Foam::tmp< Foam::scalarField > Cpv (const scalarField & p, const scalarField & T, const label patchi) const virtual
Definition at line 613 of file heThermo.C.
References forAll, p, UPtrList< T >::size(), and T.
Cpv() [2/2]
template<class BasicThermo , class MixtureType > Foam::tmp< Foam::volScalarField > Cpv () const virtual
Definition at line 635 of file heThermo.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), Foam::dimEnergy, Foam::dimMass, Foam::dimTemperature, forAll, mesh, IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, pp(), and fvMesh::time().
CpByCpv() [1/2]
template<class BasicThermo , class MixtureType > Foam::tmp< Foam::volScalarField > CpByCpv () const virtual
Definition at line 707 of file heThermo.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), Foam::dimless, forAll, mesh, IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, pp(), and fvMesh::time().
CpByCpv() [2/2]
template<class BasicThermo , class MixtureType > Foam::tmp< Foam::scalarField > CpByCpv (const scalarField & p, const scalarField & T, const label patchi) const virtual
Definition at line 685 of file heThermo.C.
References forAll, p, UPtrList< T >::size(), and T.
W()
template<class BasicThermo , class MixtureType > Foam::tmp< Foam::volScalarField > W () const virtual
Definition at line 811 of file heThermo.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), Foam::dimMass, Foam::dimMoles, forAll, mesh, IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef(), and fvMesh::time().
kappa() [1/2]
template<class BasicThermo , class MixtureType > Foam::tmp< Foam::volScalarField > kappa () const virtual
Definition at line 860 of file heThermo.C.
References Cp.
kappa() [2/2]
template<class BasicThermo , class MixtureType > Foam::tmp< Foam::scalarField > kappa (const label patchi) const virtual
Definition at line 869 of file heThermo.C.
References Cp.
alphahe() [1/2]
template<class BasicThermo , class MixtureType > Foam::tmp< Foam::volScalarField > alphahe () const virtual
Definition at line 886 of file heThermo.C.
References alphaEff(), GeometricField< Type, PatchField, GeoMesh >::ref(), and regIOobject::rename().
alphahe() [2/2]
template<class BasicThermo , class MixtureType > Foam::tmp< Foam::scalarField > alphahe (const label patchi) const virtual
Definition at line 896 of file heThermo.C.
kappaEff() [1/2]
template<class BasicThermo , class MixtureType > Foam::tmp< Foam::volScalarField > kappaEff (const volScalarField & alphat) const virtual
Definition at line 911 of file heThermo.C.
References Cp, and kappaEff.
kappaEff() [2/2]
template<class BasicThermo , class MixtureType > Foam::tmp< Foam::scalarField > kappaEff (const scalarField & alphat, const label patchi) const virtual
Definition at line 924 of file heThermo.C.
References Cp.
alphaEff() [1/2]
template<class BasicThermo , class MixtureType > Foam::tmp< Foam::volScalarField > alphaEff (const volScalarField & alphat) const virtual
Definition at line 946 of file heThermo.C.
References alphaEff(), GeometricField< Type, PatchField, GeoMesh >::ref(), and regIOobject::rename().
alphaEff() [2/2]
template<class BasicThermo , class MixtureType > Foam::tmp< Foam::scalarField > alphaEff (const scalarField & alphat, const label patchi) const virtual
Definition at line 959 of file heThermo.C.
read()
template<class BasicThermo , class MixtureType > bool read () virtual
Definition at line 980 of file heThermo.C.
Member Data Documentation
he_
template<class BasicThermo , class MixtureType > volScalarField he_ protected
Definition at line 58 of file heThermo.H.
Referenced by heThermo< BasicThermo, MixtureType >::he(), heThermo< BasicThermo, MixtureType >::he(), and heThermo< BasicThermo, MixtureType >::heThermo().
The documentation for this class was generated from the following files:
src/thermophysicalModels/basic/heThermo/heThermo.H
src/thermophysicalModels/basic/heThermo/heThermo.C