OpenFOAM: surfacePatch Class Reference
surfacePatch Class Reference
A 'patch' on surface as subset of triSurface.
#include <surfacePatch.H>
Public Member Functions
surfacePatch (const surfacePatch &)=default
surfacePatch & operator= (const surfacePatch &)=default
surfacePatch ()
surfacePatch (const label index)
surfacePatch (const word &name, const label size, const label start, const label index, const word &geometricType=word::null)
surfacePatch (const word &name, const dictionary &dict, const label index)
label start () const noexcept
label & start () noexcept
label size () const noexcept
label & size () noexcept
void write (Ostream &os) const
operator surfZone () const
surfacePatch (Istream &is, const label index)=delete
surfacePatch (const word &geometricType, const word &name, const label size, const label start, const label index)
void writeDict (Ostream &os) const
Public Member Functions inherited from geometricSurfacePatch
geometricSurfacePatch (const geometricSurfacePatch &)=default
geometricSurfacePatch & operator= (const geometricSurfacePatch &)=default
geometricSurfacePatch ()
geometricSurfacePatch (const label index)
geometricSurfacePatch (const word &name, const label index)
geometricSurfacePatch (const word &name, const label index, const word &geometricType)
geometricSurfacePatch (const word &name, const dictionary &dict, const label index)
geometricSurfacePatch (const surfZoneIdentifier &ident)
const word & name () const noexcept
word & name () noexcept
label index () const noexcept
label & index () noexcept
const word & geometricType () const noexcept
word & geometricType () noexcept
void write (Ostream &os) const
geometricSurfacePatch (Istream &is, const label index)=delete
geometricSurfacePatch (const word &geometricType, const word &name, const label index)
void writeDict (Ostream &os) const
Additional Inherited Members
Static Public Member Functions inherited from geometricSurfacePatch
static word defaultName (const label n=-1)
Static Public Attributes inherited from geometricSurfacePatch
static constexpr const char *const emptyType = "empty"
Detailed Description
A 'patch' on surface as subset of triSurface.
Source files
surfacePatch.H
surfacePatch.C
Definition at line 50 of file surfacePatch.H.
Constructor & Destructor Documentation
surfacePatch() [1/7]
surfacePatch (const surfacePatch &) default
surfacePatch() [2/7]
surfacePatch ()
Definition at line 28 of file surfacePatch.C.
surfacePatch() [3/7]
surfacePatch (const label index) explicit
Definition at line 34 of file surfacePatch.C.
surfacePatch() [4/7]
surfacePatch (const word & name, const label size, const label start, const label index, const word & geometricType = word::null)
Definition at line 42 of file surfacePatch.C.
surfacePatch() [5/7]
surfacePatch (const word & name, const dictionary & dict, const label index)
Definition at line 57 of file surfacePatch.C.
surfacePatch() [6/7]
surfacePatch (Istream & is, const label index) delete
surfacePatch() [7/7]
surfacePatch (const word & geometricType, const word & name, const label size, const label start, const label index) inline
Definition at line 147 of file surfacePatch.H.
Member Function Documentation
operator=()
surfacePatch & operator= (const surfacePatch &) default
start() [1/2]
label start () const inline noexcept
Definition at line 104 of file surfacePatch.H.
Referenced by Foam::operator==().
start() [2/2]
label & start () inline noexcept
Definition at line 110 of file surfacePatch.H.
size() [1/2]
label size () const inline noexcept
Definition at line 116 of file surfacePatch.H.
Referenced by Foam::operator==().
size() [2/2]
label & size () inline noexcept
Definition at line 122 of file surfacePatch.H.
write()
void write (Ostream & os) const
Definition at line 72 of file surfacePatch.C.
References Ostream::beginBlock(), Ostream::endBlock(), Foam::name(), os(), geometricSurfacePatch::write(), and Ostream::writeEntry().
operator surfZone()
operator surfZone () const explicit
writeDict()
void writeDict (Ostream & os) const inline
Definition at line 162 of file surfacePatch.H.
References os(), and write().
The documentation for this class was generated from the following files:
src/surfMesh/triSurface/patches/surfacePatch.H
src/surfMesh/triSurface/patches/surfacePatch.C