OpenFOAM: interfaceCompositionModel Class Reference
interfaceCompositionModel Class Reference abstract
#include <interfaceCompositionModel.H>
Public Types
enum modelVariable { T , P , Y , alpha }
Public Member Functions
TypeName ("interfaceCompositionModel")
declareRunTimeSelectionTable (autoPtr, interfaceCompositionModel, dictionary,(const dictionary &dict, const phasePair &pair),(dict, pair))
interfaceCompositionModel (const dictionary &dict, const phasePair &pair)
virtual ~interfaceCompositionModel ()=default
const word transferSpecie () const
const phasePair & pair () const
const multiphaseInterSystem & fluid () const
virtual tmp< volScalarField > Yf (const word &speciesName, const volScalarField &Tf) const =0
virtual tmp< volScalarField > dY (const word &speciesName, const volScalarField &Tf) const =0
virtual tmp< volScalarField > Dfrom (const word &speciesName) const =0
virtual tmp< volScalarField > Dto (const word &speciesName) const =0
virtual tmp< volScalarField > L (const word &speciesName, const volScalarField &Tf) const =0
virtual tmp< volScalarField > Kexp (const volScalarField &field)=0
virtual tmp< volScalarField > KSp (label modelVariable, const volScalarField &field)=0
virtual tmp< volScalarField > KSu (label modelVariable, const volScalarField &field)=0
virtual const dimensionedScalar & Tactivate () const noexcept=0
virtual bool includeDivU () const noexcept
bool includeVolChange ()
const word & variable () const
Static Public Member Functions
static autoPtr< interfaceCompositionModel > New (const dictionary &dict, const phasePair &pair)
Protected Attributes
modelVariable modelVariable_
bool includeVolChange_
const phasePair & pair_
word speciesName_
const fvMesh & mesh_
Static Protected Attributes
static const Enum< modelVariable > modelVariableNames_
Detailed Description
Definition at line 61 of file interfaceCompositionModel.H.
Member Enumeration Documentation
modelVariable
enum modelVariable
Enumerator
T
P
Y
alpha
Definition at line 68 of file interfaceCompositionModel.H.
Constructor & Destructor Documentation
interfaceCompositionModel()
interfaceCompositionModel (const dictionary & dict, const phasePair & pair)
Definition at line 51 of file interfaceCompositionModel.C.
~interfaceCompositionModel()
virtual ~interfaceCompositionModel () virtual default
Member Function Documentation
TypeName()
TypeName ("interfaceCompositionModel")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , interfaceCompositionModel , dictionary , (const dictionary &dict, const phasePair &pair) , (dict, pair))
New()
Foam::autoPtr< Foam::interfaceCompositionModel > New (const dictionary & dict, const phasePair & pair) static
Definition at line 76 of file interfaceCompositionModel.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, Foam::Info, phasePair::phase1(), and phasePair::phase2().
transferSpecie()
const Foam::word transferSpecie () const
Definition at line 114 of file interfaceCompositionModel.C.
Referenced by kineticGasEvaporation< Thermo, OtherThermo >::kineticGasEvaporation().
pair()
const Foam::phasePair & pair () const
Definition at line 121 of file interfaceCompositionModel.C.
Referenced by NonRandomTwoLiquid< Thermo, OtherThermo >::NonRandomTwoLiquid(), and Raoult< Thermo, OtherThermo >::Raoult().
fluid()
const Foam::multiphaseInterSystem & fluid () const
Definition at line 128 of file interfaceCompositionModel.C.
Yf()
virtual tmp< volScalarField > Yf (const word & speciesName, const volScalarField & Tf) const pure virtual
Implemented in InterfaceCompositionModel< Thermo, OtherThermo >, Henry< Thermo, OtherThermo >, NonRandomTwoLiquid< Thermo, OtherThermo >, Raoult< Thermo, OtherThermo >, and Saturated< Thermo, OtherThermo >.
dY()
virtual tmp< volScalarField > dY (const word & speciesName, const volScalarField & Tf) const pure virtual
Implemented in InterfaceCompositionModel< Thermo, OtherThermo >, and InterfaceCompositionModel< Thermo, OtherThermo >.
Dfrom()
virtual tmp< volScalarField > Dfrom (const word & speciesName) const pure virtual
Implemented in InterfaceCompositionModel< Thermo, OtherThermo >.
Dto()
virtual tmp< volScalarField > Dto (const word & speciesName) const pure virtual
Implemented in InterfaceCompositionModel< Thermo, OtherThermo >.
L()
virtual tmp< volScalarField > L (const word & speciesName, const volScalarField & Tf) const pure virtual
Implemented in InterfaceCompositionModel< Thermo, OtherThermo >, and InterfaceCompositionModel< Thermo, OtherThermo >.
Kexp()
virtual tmp< volScalarField > Kexp (const volScalarField & field) pure virtual
Implemented in diffusionGasEvaporation< Thermo, OtherThermo >, interfaceHeatResistance< Thermo, OtherThermo >, interfaceOxideRate< Thermo, OtherThermo >, kineticGasEvaporation< Thermo, OtherThermo >, and Lee< Thermo, OtherThermo >.
KSp()
virtual tmp< volScalarField > KSp (label modelVariable, const volScalarField & field) pure virtual
Implemented in diffusionGasEvaporation< Thermo, OtherThermo >, interfaceHeatResistance< Thermo, OtherThermo >, interfaceOxideRate< Thermo, OtherThermo >, kineticGasEvaporation< Thermo, OtherThermo >, and Lee< Thermo, OtherThermo >.
KSu()
virtual tmp< volScalarField > KSu (label modelVariable, const volScalarField & field) pure virtual
Implemented in diffusionGasEvaporation< Thermo, OtherThermo >, interfaceHeatResistance< Thermo, OtherThermo >, interfaceOxideRate< Thermo, OtherThermo >, kineticGasEvaporation< Thermo, OtherThermo >, and Lee< Thermo, OtherThermo >.
Tactivate()
virtual const dimensionedScalar & Tactivate () const pure virtual noexcept
Implemented in diffusionGasEvaporation< Thermo, OtherThermo >, interfaceHeatResistance< Thermo, OtherThermo >, interfaceOxideRate< Thermo, OtherThermo >, kineticGasEvaporation< Thermo, OtherThermo >, and Lee< Thermo, OtherThermo >.
includeDivU()
bool includeDivU () const virtual noexcept
Reimplemented in diffusionGasEvaporation< Thermo, OtherThermo >, interfaceHeatResistance< Thermo, OtherThermo >, interfaceOxideRate< Thermo, OtherThermo >, kineticGasEvaporation< Thermo, OtherThermo >, and Lee< Thermo, OtherThermo >.
Definition at line 142 of file interfaceCompositionModel.C.
includeVolChange()
bool includeVolChange ()
Definition at line 149 of file interfaceCompositionModel.C.
variable()
const Foam::word & variable () const
Definition at line 135 of file interfaceCompositionModel.C.
Member Data Documentation
modelVariableNames_
const Foam::Enum< Foam::multiphaseInter::interfaceCompositionModel::modelVariable > modelVariableNames_ static protected
Initial value:
{
    { modelVariable::T, "temperature" },
    { modelVariable::P, "pressure" },
    { modelVariable::Y, "massFraction" },
    { modelVariable::alpha, "alphaVolumeFraction" },
}
Definition at line 40 of file interfaceCompositionModel.H.
modelVariable_
modelVariable modelVariable_ protected
Definition at line 84 of file interfaceCompositionModel.H.
includeVolChange_
bool includeVolChange_ protected
Definition at line 87 of file interfaceCompositionModel.H.
pair_
const phasePair& pair_ protected
Definition at line 90 of file interfaceCompositionModel.H.
speciesName_
word speciesName_ protected
Definition at line 93 of file interfaceCompositionModel.H.
mesh_
const fvMesh& mesh_ protected
Definition at line 96 of file interfaceCompositionModel.H.
The documentation for this class was generated from the following files:
src/phaseSystemModels/multiphaseInter/phasesSystem/interfaceCompositionModel/interfaceCompositionModel.H
src/phaseSystemModels/multiphaseInter/phasesSystem/interfaceCompositionModel/interfaceCompositionModel.C
src/phaseSystemModels/reactingEuler/multiphaseSystem/interfacialCompositionModels/interfaceCompositionModels/interfaceCompositionModel/interfaceCompositionModel.C