OpenFOAM: prghTotalHydrostaticPressureFvPatchScalarField Class Reference
prghTotalHydrostaticPressureFvPatchScalarField Class Reference
Boundary conditions » Generic
This boundary condition provides static pressure condition for p_rgh, calculated as:
#include <prghTotalHydrostaticPressureFvPatchScalarField.H>
Public Member Functions
TypeName ("prghTotalHydrostaticPressure")
prghTotalHydrostaticPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
prghTotalHydrostaticPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
prghTotalHydrostaticPressureFvPatchScalarField (const prghTotalHydrostaticPressureFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
prghTotalHydrostaticPressureFvPatchScalarField (const prghTotalHydrostaticPressureFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
prghTotalHydrostaticPressureFvPatchScalarField (const prghTotalHydrostaticPressureFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Protected Attributes
word UName_
word phiName_
word rhoName_
word ph_rghName_
Detailed Description
This boundary condition provides static pressure condition for p_rgh, calculated as:
where
= Pressure: [Pa]
= Hydrostatic pressure: [Pa]
= Height in the opposite direction to gravity
= Reference height in the opposite direction to gravity
= Density
= Acceleration due to gravity [m/s^2]
Usage
Property Description Required Default value
U Velocity field name no U
phi Flux field name no phi
rho Density field name no rho
ph_rgh ph_rgh field name no ph_rgh
value Patch face values yes
Example of the boundary condition specification:
    <patchName>
    {
        type            prghTotalHydrostaticPressure;
        value           uniform 0;
    }
See also
Foam::fixedValueFvPatchScalarField Foam::prghTotalPressureFvPatchScalarField
Source files
prghTotalHydrostaticPressureFvPatchScalarField.H
prghTotalHydrostaticPressureFvPatchScalarField.C
Definition at line 141 of file prghTotalHydrostaticPressureFvPatchScalarField.H.
Constructor & Destructor Documentation
prghTotalHydrostaticPressureFvPatchScalarField() [1/5]
prghTotalHydrostaticPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 31 of file prghTotalHydrostaticPressureFvPatchScalarField.C.
prghTotalHydrostaticPressureFvPatchScalarField() [2/5]
prghTotalHydrostaticPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 46 of file prghTotalHydrostaticPressureFvPatchScalarField.C.
prghTotalHydrostaticPressureFvPatchScalarField() [3/5]
prghTotalHydrostaticPressureFvPatchScalarField (const prghTotalHydrostaticPressureFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 62 of file prghTotalHydrostaticPressureFvPatchScalarField.C.
prghTotalHydrostaticPressureFvPatchScalarField() [4/5]
prghTotalHydrostaticPressureFvPatchScalarField (const prghTotalHydrostaticPressureFvPatchScalarField & ptf)
Definition at line 79 of file prghTotalHydrostaticPressureFvPatchScalarField.C.
prghTotalHydrostaticPressureFvPatchScalarField() [5/5]
prghTotalHydrostaticPressureFvPatchScalarField (const prghTotalHydrostaticPressureFvPatchScalarField & ptf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 93 of file prghTotalHydrostaticPressureFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("prghTotalHydrostaticPressure")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 203 of file prghTotalHydrostaticPressureFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 219 of file prghTotalHydrostaticPressureFvPatchScalarField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 110 of file prghTotalHydrostaticPressureFvPatchScalarField.C.
References Foam::magSqr(), and Foam::neg().
write()
void write (Ostream & os) const virtual
Definition at line 139 of file prghTotalHydrostaticPressureFvPatchScalarField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntryIfDifferent(), and fvPatchField< Type >::writeValueEntry().
Member Data Documentation
UName_
word UName_ protected
Definition at line 151 of file prghTotalHydrostaticPressureFvPatchScalarField.H.
phiName_
word phiName_ protected
Definition at line 154 of file prghTotalHydrostaticPressureFvPatchScalarField.H.
rhoName_
word rhoName_ protected
Definition at line 157 of file prghTotalHydrostaticPressureFvPatchScalarField.H.
ph_rghName_
word ph_rghName_ protected
Definition at line 160 of file prghTotalHydrostaticPressureFvPatchScalarField.H.
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/prghTotalHydrostaticPressure/prghTotalHydrostaticPressureFvPatchScalarField.H
src/finiteVolume/fields/fvPatchFields/derived/prghTotalHydrostaticPressure/prghTotalHydrostaticPressureFvPatchScalarField.C