OpenFOAM: phaseModel Class Reference
phaseModel Class Reference abstract
Single incompressible phase derived from the phase-fraction. Used as part of the multiPhaseMixture for interface-capturing multi-phase simulations.
#include <phaseModel.H>
Classes
class iNew
Public Member Functions
phaseModel (const word &phaseName, const dictionary &phaseDict, const fvMesh &mesh)
autoPtr< phaseModel > clone () const
virtual ~phaseModel ()
const word & name () const
const word & keyword () const
tmp< volScalarField > d () const
const dimensionedScalar & nu () const
const dimensionedScalar & kappa () const
const dimensionedScalar & Cp () const
const dimensionedScalar & rho () const
const volVectorField & U () const
volVectorField & U ()
const volVectorField & DDtU () const
volVectorField & DDtU ()
const surfaceScalarField & phi () const
surfaceScalarField & phi ()
const surfaceScalarField & alphaPhi () const
surfaceScalarField & alphaPhi ()
void correctInflowOutflow (surfaceScalarField &alphaPhi) const
void correct ()
bool read (const dictionary &phaseDict)
ClassName ("phaseModel")
declareRunTimeSelectionTable (autoPtr, phaseModel, phaseSystem,(const phaseSystem &fluid, const word &phaseName, const label index),(fluid, phaseName, index))
phaseModel (const phaseSystem &fluid, const word &phaseName, const label index)
autoPtr< phaseModel > clone () const
virtual ~phaseModel ()
const word & name () const
const word & keyword () const
label index () const
const phaseSystem & fluid () const
const dimensionedScalar & residualAlpha () const
scalar alphaMax () const
tmp< volScalarField > d () const
const autoPtr< diameterModel > & dPtr () const
virtual void correct ()
virtual void correctKinematics ()
virtual void correctThermo ()
virtual void correctTurbulence ()
virtual void correctEnergyTransport ()
void correctInflowOutflow (surfaceScalarField &alphaPhi) const
virtual bool read ()
virtual bool compressible () const =0
virtual tmp< volScalarField > divU () const =0
virtual void divU (tmp< volScalarField > divU)=0
virtual bool isothermal () const =0
virtual tmp< fvScalarMatrix > heEqn ()=0
virtual const rhoThermo & thermo () const =0
virtual rhoThermo & thermoRef ()=0
virtual tmp< volScalarField > rho () const =0
virtual bool pure () const =0
virtual tmp< fvScalarMatrix > YiEqn (volScalarField &Yi)=0
virtual const PtrList< volScalarField > & Y () const =0
virtual const volScalarField & Y (const word &name) const =0
virtual PtrList< volScalarField > & YRef ()=0
virtual const UPtrList< volScalarField > & YActive () const =0
virtual UPtrList< volScalarField > & YActiveRef ()=0
virtual bool stationary () const =0
virtual tmp< fvVectorMatrix > UEqn ()=0
virtual tmp< fvVectorMatrix > UfEqn ()=0
virtual tmp< volVectorField > U () const =0
virtual volVectorField & URef ()=0
virtual tmp< surfaceScalarField > phi () const =0
virtual surfaceScalarField & phiRef ()=0
virtual tmp< surfaceScalarField > alphaPhi () const =0
virtual surfaceScalarField & alphaPhiRef ()=0
virtual tmp< surfaceScalarField > alphaRhoPhi () const =0
virtual surfaceScalarField & alphaRhoPhiRef ()=0
virtual tmp< volVectorField > DUDt () const =0
virtual tmp< surfaceScalarField > DUDtf () const =0
virtual tmp< volScalarField > continuityError () const =0
virtual tmp< volScalarField > continuityErrorFlow () const =0
virtual tmp< volScalarField > continuityErrorSources () const =0
virtual tmp< volScalarField > K () const =0
virtual tmp< volScalarField > mu () const =0
virtual tmp< scalarField > mu (const label patchi) const =0
virtual tmp< volScalarField > nu () const =0
virtual tmp< scalarField > nu (const label patchi) const =0
virtual tmp< volScalarField > alpha () const =0
virtual tmp< scalarField > alpha (const label patchi) const =0
virtual tmp< volScalarField > kappa () const =0
virtual tmp< scalarField > kappa (const label patchi) const =0
virtual tmp< volScalarField > alphahe () const =0
virtual tmp< scalarField > alphahe (const label patchi) const =0
virtual tmp< volScalarField > kappaEff (const volScalarField &alphat) const =0
virtual tmp< scalarField > kappaEff (const scalarField &alphat, const label patchi) const =0
virtual tmp< volScalarField > alphaEff (const volScalarField &alphat) const =0
virtual tmp< scalarField > alphaEff (const scalarField &alphat, const label patchi) const =0
virtual tmp< volScalarField > mut () const =0
virtual tmp< volScalarField > muEff () const =0
virtual tmp< volScalarField > nut () const =0
virtual tmp< volScalarField > nuEff () const =0
virtual tmp< volScalarField > kappaEff () const =0
virtual tmp< scalarField > kappaEff (const label patchi) const =0
virtual tmp< volScalarField > alphaEff () const =0
virtual tmp< scalarField > alphaEff (const label patchi) const =0
virtual tmp< volScalarField > k () const =0
virtual tmp< volScalarField > pPrime () const =0
phaseModel (const twoPhaseSystem &fluid, const dictionary &phaseProperties, const word &phaseName)
virtual ~phaseModel ()
const word & name () const
const twoPhaseSystem & fluid () const
const phaseModel & otherPhase () const
const dimensionedScalar & residualAlpha () const
scalar alphaMax () const
tmp< volScalarField > d () const
const PhaseCompressibleTurbulenceModel< phaseModel > & turbulence () const
PhaseCompressibleTurbulenceModel< phaseModel > & turbulence ()
const rhoThermo & thermo () const
rhoThermo & thermo ()
tmp< volScalarField > nu () const
tmp< scalarField > nu (const label patchi) const
tmp< volScalarField > mu () const
tmp< scalarField > mu (const label patchi) const
tmp< scalarField > kappa (const label patchi) const
tmp< volScalarField > kappa () const
tmp< volScalarField > alphahe () const
tmp< scalarField > alphahe (const label patchi) const
tmp< volScalarField > kappaEff (const volScalarField &alphat) const
tmp< scalarField > kappaEff (const scalarField &alphat, const label patchi) const
tmp< volScalarField > alpha () const
tmp< scalarField > alpha (const label patchi) const
tmp< volScalarField > alphaEff (const volScalarField &alphat) const
tmp< scalarField > alphaEff (const scalarField &alphat, const label patchi) const
tmp< volScalarField > Cp () const
const volScalarField & rho () const
const volVectorField & U () const
volVectorField & U ()
const surfaceScalarField & phi () const
surfaceScalarField & phi ()
const surfaceScalarField & alphaPhi () const
surfaceScalarField & alphaPhi ()
const surfaceScalarField & alphaRhoPhi () const
surfaceScalarField & alphaRhoPhi ()
void correctInflowOutflow (surfaceScalarField &alphaPhi) const
void correct ()
virtual bool read (const dictionary &phaseProperties)
virtual bool read ()
phaseModel (const word &phaseName, const volScalarField &p, const volScalarField &T)
autoPtr< phaseModel > clone () const
const word & name () const
const word & keyword () const
const rhoThermo & thermo () const
rhoThermo & thermo ()
const volScalarField & dgdt () const
volScalarField & dgdt ()
void correct ()
Public Member Functions inherited from GeometricField< scalar, fvPatchField, volMesh >
TypeName ("GeometricField")
GeometricField (const IOobject &io, const Mesh &mesh, const dimensionSet &dims, const word &patchFieldType=fvPatchField< scalar >::calculatedType())
GeometricField (const IOobject &io, const Mesh &mesh, const dimensionSet &dims, const wordList &wantedPatchTypes, const wordList &actualPatchTypes=wordList())
GeometricField (const IOobject &io, const Mesh &mesh, const scalar &value, const dimensionSet &dims, const word &patchFieldType=fvPatchField< scalar >::calculatedType())
GeometricField (const IOobject &io, const Mesh &mesh, const scalar &value, const dimensionSet &dims, const wordList &wantedPatchTypes, const wordList &actualPatchTypes=wordList())
GeometricField (const IOobject &io, const Mesh &mesh, const dimensioned< scalar > &dt, const word &patchFieldType=fvPatchField< scalar >::calculatedType())
GeometricField (const IOobject &io, const Mesh &mesh, const dimensioned< scalar > &dt, const wordList &wantedPatchTypes, const wordList &actualPatchTypes=wordList())
GeometricField (const IOobject &io, const Internal &diField, const PtrList< fvPatchField< scalar > > &ptfl)
GeometricField (const IOobject &io, Internal &&diField, const PtrList< fvPatchField< scalar > > &ptfl)
GeometricField (const IOobject &io, const tmp< Internal > &tfield, const PtrList< fvPatchField< scalar > > &ptfl)
GeometricField (const Internal &diField, const PtrList< fvPatchField< scalar > > &ptfl)
GeometricField (Internal &&diField, const PtrList< fvPatchField< scalar > > &ptfl)
GeometricField (const IOobject &io, const Mesh &mesh, const dimensionSet &dims, const Field< scalar > &iField, const word &patchFieldType=fvPatchField< scalar >::calculatedType())
GeometricField (const IOobject &io, const Mesh &mesh, const dimensionSet &dims, Field< scalar > &&iField, const word &patchFieldType=fvPatchField< scalar >::calculatedType())
GeometricField (const IOobject &io, const Mesh &mesh, const dimensionSet &dims, const Field< scalar > &iField, const PtrList< fvPatchField< scalar > > &ptfl)
GeometricField (const IOobject &io, const Mesh &mesh, const dimensionSet &dims, Field< scalar > &&iField, const PtrList< fvPatchField< scalar > > &ptfl)
GeometricField (const IOobject &io, const Mesh &mesh, const dimensionSet &dims, const tmp< Field< scalar > > &tiField, const PtrList< fvPatchField< scalar > > &ptfl)
GeometricField (const IOobject &io, const Mesh &mesh, const bool readOldTime=true)
GeometricField (const IOobject &io, const Mesh &mesh, const dictionary &dict)
GeometricField (const GeometricField< scalar, fvPatchField, volMesh > &gf)
GeometricField (const tmp< GeometricField< scalar, fvPatchField, volMesh > > &tgf)
GeometricField (const IOobject &io, const GeometricField< scalar, fvPatchField, volMesh > &gf)
GeometricField (const IOobject &io, const tmp< GeometricField< scalar, fvPatchField, volMesh > > &tgf)
GeometricField (const word &newName, const GeometricField< scalar, fvPatchField, volMesh > &gf)
GeometricField (const word &newName, const tmp< GeometricField< scalar, fvPatchField, volMesh > > &tgf)
GeometricField (const IOobject &io, const GeometricField< scalar, fvPatchField, volMesh > &gf, const word &patchFieldType)
GeometricField (const IOobject &io, const GeometricField< scalar, fvPatchField, volMesh > &gf, const labelList &patchIDs, const word &patchFieldType)
GeometricField (const IOobject &io, const GeometricField< scalar, fvPatchField, volMesh > &gf, const wordList &patchFieldTypes, const wordList &actualPatchTypes=wordList())
GeometricField (const IOobject &io, const tmp< GeometricField< scalar, fvPatchField, volMesh > > &tgf, const wordList &patchFieldTypes, const wordList &actualPatchTypes=wordList())
tmp< GeometricField< scalar, fvPatchField, volMesh > > clone () const
Foam::tmp< Foam::GeometricField< scalar, fvPatchField, volMesh > > New (const GeometricField< AnyType, fvPatchField, volMesh > &fld, const word &name, const dimensionSet &dims, const word &patchFieldType)
Foam::tmp< Foam::GeometricField< scalar, fvPatchField, volMesh > > New (const GeometricField< AnyType, fvPatchField, volMesh > &fld, const word &name, const dimensioned< scalar > &dt, const word &patchFieldType)
virtual ~GeometricField ()
const Internal & internalField () const noexcept
Internal & internalFieldRef (const bool updateAccessTime=true)
Internal & ref (const bool updateAccessTime=true)
const Internal & v () const
const Internal::FieldType & primitiveField () const noexcept
Internal::FieldType & primitiveFieldRef (const bool updateAccessTime=true)
const Boundary & boundaryField () const noexcept
Boundary & boundaryFieldRef (const bool updateAccessTime=true)
label timeIndex () const noexcept
label & timeIndex () noexcept
void storeOldTimes () const
void storeOldTime () const
label nOldTimes () const
const GeometricField< scalar, fvPatchField, volMesh > & oldTime () const
GeometricField< scalar, fvPatchField, volMesh > & oldTime ()
void storePrevIter () const
const GeometricField< scalar, fvPatchField, volMesh > & prevIter () const
void correctBoundaryConditions ()
bool needReference () const
tmp< GeometricField< cmptType, fvPatchField, volMesh > > component (const direction) const
tmp< GeometricField< scalar, faPatchField, areaMesh > > component (const direction) const
tmp< GeometricField< scalar, faPatchField, areaMesh > > component (const direction) const
tmp< GeometricField< scalar, fvPatchField, volMesh > > component (const direction) const
tmp< GeometricField< scalar, fvPatchField, volMesh > > component (const direction) const
bool writeData (Ostream &) const
tmp< GeometricField< scalar, fvPatchField, volMesh > > T () const
void relax (const scalar alpha)
void relax ()
word select (bool final) const
void writeMinMax (Ostream &os) const
void negate ()
void normalise ()
void replace (const direction d, const GeometricField< cmptType, fvPatchField, volMesh > &gcf)
void replace (const direction d, const dimensioned< cmptType > &ds)
void replace (const direction, const GeometricField< scalar, faPatchField, areaMesh > &gsf)
void replace (const direction, const GeometricField< scalar, faPatchField, areaMesh > &sf)
void replace (const direction, const GeometricField< scalar, fvPatchField, volMesh > &gsf)
void replace (const direction, const GeometricField< scalar, fvPatchField, volMesh > &sf)
void clamp_min (const scalar &lower)
void clamp_min (const dimensioned< scalar > &lower)
void clamp_max (const scalar &upper)
void clamp_max (const dimensioned< scalar > &upper)
void clamp_range (const dimensioned< MinMax< scalar > > &range)
void clamp_range (const scalar &lower, const scalar &upper)
void clamp_range (const MinMax< scalar > &range)
void clamp_range (const dimensioned< scalar > &lower, const dimensioned< scalar > &upper)
const Internal & operator() () const
void operator= (const GeometricField< scalar, fvPatchField, volMesh > &)
void operator= (const tmp< GeometricField< scalar, fvPatchField, volMesh > > &)
void operator= (const dimensioned< scalar > &)
void operator== (const tmp< GeometricField< scalar, fvPatchField, volMesh > > &)
void operator== (const dimensioned< scalar > &)
void operator+= (const GeometricField< scalar, fvPatchField, volMesh > &)
void operator+= (const tmp< GeometricField< scalar, fvPatchField, volMesh > > &)
void operator+= (const dimensioned< scalar > &)
void operator-= (const GeometricField< scalar, fvPatchField, volMesh > &)
void operator-= (const tmp< GeometricField< scalar, fvPatchField, volMesh > > &)
void operator-= (const dimensioned< scalar > &)
void operator*= (const GeometricField< scalar, fvPatchField, volMesh > &)
void operator*= (const tmp< GeometricField< scalar, fvPatchField, volMesh > > &)
void operator*= (const dimensioned< scalar > &)
void operator/= (const GeometricField< scalar, fvPatchField, volMesh > &)
void operator/= (const tmp< GeometricField< scalar, fvPatchField, volMesh > > &)
void operator/= (const dimensioned< scalar > &)
void clip (const dimensioned< MinMax< scalar > > &range)
void clip (const dimensioned< scalar > &lo, const dimensioned< scalar > &hi)
void min (const dimensioned< scalar > &upper)
void max (const dimensioned< scalar > &lower)
void maxMin (const dimensioned< scalar > &lo, const dimensioned< scalar > &hi)
Public Member Functions inherited from DimensionedField< Type, GeoMesh >
TypeName ("DimensionedField")
DimensionedField (const IOobject &io, const Mesh &mesh, const dimensionSet &dims, const Field< Type > &field)
DimensionedField (const IOobject &io, const Mesh &mesh, const dimensionSet &dims, Field< Type > &&field)
DimensionedField (const IOobject &io, const Mesh &mesh, const dimensionSet &dims, List< Type > &&field)
DimensionedField (const IOobject &io, const Mesh &mesh, const dimensionSet &dims, const tmp< Field< Type > > &tfield)
DimensionedField (const IOobject &io, const Mesh &mesh, const dimensionSet &dims, const bool checkIOFlags=true)
DimensionedField (const IOobject &io, const Mesh &mesh, const Type &value, const dimensionSet &dims, const bool checkIOFlags=true)
DimensionedField (const IOobject &io, const Mesh &mesh, const dimensioned< Type > &dt, const bool checkIOFlags=true)
DimensionedField (const IOobject &io, const Mesh &mesh, const word &fieldDictEntry="value")
DimensionedField (const IOobject &io, const Mesh &mesh, const dictionary &fieldDict, const word &fieldDictEntry="value")
DimensionedField (const DimensionedField< Type, GeoMesh > &df)
DimensionedField (DimensionedField< Type, GeoMesh > &&df)
DimensionedField (DimensionedField< Type, GeoMesh > &df, bool reuse)
DimensionedField (const tmp< DimensionedField< Type, GeoMesh > > &tdf)
DimensionedField (const IOobject &io, const DimensionedField< Type, GeoMesh > &df)
DimensionedField (const IOobject &io, DimensionedField< Type, GeoMesh > &&df)
DimensionedField (const IOobject &io, DimensionedField< Type, GeoMesh > &df, bool reuse)
DimensionedField (const IOobject &io, const tmp< DimensionedField< Type, GeoMesh > > &tdf)
DimensionedField (const word &newName, const DimensionedField< Type, GeoMesh > &df)
DimensionedField (const word &newName, DimensionedField< Type, GeoMesh > &&df)
DimensionedField (const word &newName, DimensionedField< Type, GeoMesh > &df, bool reuse)
DimensionedField (const word &newName, const tmp< DimensionedField< Type, GeoMesh > > &tdf)
tmp< DimensionedField< Type, GeoMesh > > clone () const
virtual ~DimensionedField ()=default
void readField (const dictionary &fieldDict, const word &fieldDictEntry="value")
const Mesh & mesh () const noexcept
const dimensionSet & dimensions () const noexcept
dimensionSet & dimensions () noexcept
orientedType oriented () const noexcept
orientedType & oriented () noexcept
bool is_oriented () const noexcept
void setOriented (bool on=true) noexcept
const Field< Type > & field () const noexcept
Field< Type > & field () noexcept
tmp< DimensionedField< cmptType, GeoMesh > > component (const direction d) const
void replace (const direction d, const DimensionedField< cmptType, GeoMesh > &df)
void replace (const direction d, const tmp< DimensionedField< cmptType, GeoMesh > > &tdf)
tmp< DimensionedField< Type, GeoMesh > > T () const
dimensioned< Type > average () const
dimensioned< Type > weightedAverage (const DimensionedField< scalar, GeoMesh > &weightField) const
dimensioned< Type > weightedAverage (const tmp< DimensionedField< scalar, GeoMesh > > &tweightField) const
bool writeData (Ostream &os, const word &fieldDictEntry) const
void operator= (const DimensionedField< Type, GeoMesh > &df)
void operator= (const tmp< DimensionedField< Type, GeoMesh > > &tdf)
void operator= (const dimensioned< Type > &dt)
void operator+= (const DimensionedField< Type, GeoMesh > &df)
void operator+= (const tmp< DimensionedField< Type, GeoMesh > > &tdf)
void operator-= (const DimensionedField< Type, GeoMesh > &df)
void operator-= (const tmp< DimensionedField< Type, GeoMesh > > &tdf)
void operator*= (const DimensionedField< scalar, GeoMesh > &df)
void operator*= (const tmp< DimensionedField< scalar, GeoMesh > > &tdf)
void operator/= (const DimensionedField< scalar, GeoMesh > &df)
void operator/= (const tmp< DimensionedField< scalar, GeoMesh > > &tdf)
void operator+= (const dimensioned< Type > &dt)
void operator-= (const dimensioned< Type > &dt)
void operator*= (const dimensioned< scalar > &dt)
void operator/= (const dimensioned< scalar > &dt)
const word typeName ("volScalarField::Internal")
const word typeName ("volVectorField::Internal")
const word typeName ("volSphericalTensorField::Internal")
const word typeName ("volSymmTensorField::Internal")
const word typeName ("volTensorField::Internal")
template<class AnyType >
Foam::tmp< Foam::DimensionedField< Type, GeoMesh > > New (const DimensionedField< AnyType, GeoMesh > &fld, const word &name, const dimensionSet &dims)
template<class AnyType >
Foam::tmp< Foam::DimensionedField< Type, GeoMesh > > New (const DimensionedField< AnyType, GeoMesh > &fld, const word &name, const dimensioned< Type > &dt)
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
regIOobject (const IOobject &io, const bool isTimeObject=false)
regIOobject (const regIOobject &rio)
regIOobject (const regIOobject &rio, bool registerCopy)
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
regIOobject (const IOobject &io, const regIOobject &rio)
virtual ~regIOobject ()
bool checkIn ()
bool checkOut ()
virtual void addWatch ()
bool registered () const noexcept
bool ownedByRegistry () const noexcept
bool store ()
void release (const bool unregister=false) noexcept
label eventNo () const noexcept
label & eventNo () noexcept
bool upToDate (const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
void setUpToDate ()
virtual void rename (const word &newName)
const dictionary * findMetaData () const noexcept
dictionary & getMetaData () noexcept
void removeMetaData ()
virtual void updateMetaData ()
virtual fileName filePath () const
bool headerOk ()
Istream & readStream (const word &, const bool readOnProc=true)
void close ()
virtual bool readData (Istream &)
virtual label addWatch (const fileName &)
const labelList & watchIndices () const noexcept
labelList & watchIndices () noexcept
virtual bool modified () const
virtual bool readIfModified ()
virtual bool writeObject (IOstreamOption streamOpt, const bool writeOnProc) const
virtual bool write (const bool writeOnProc=true) const
virtual bool global () const
void operator= (const IOobject &io)
virtual bool writeObject (IOstreamOption::streamFormat fmt, IOstreamOption::versionNumber ver, IOstreamOption::compressionType cmp, const bool writeOnProc) const
Public Member Functions inherited from IOobject
TypeName ("IOobject")
IOobject (const IOobject &)=default
virtual ~IOobject ()=default
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const fileName &path, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const fileName &path, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const IOobject &io, const objectRegistry &registry)
IOobject (const IOobject &io, const word &name)
IOobject (const IOobject &io, const word &name, const fileName &local)
IOobject (const IOobject &io, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt)
IOobject (const IOobject &io, IOobjectOption::registerOption regOpt)
autoPtr< IOobject > clone () const
autoPtr< IOobject > clone (const objectRegistry &registry) const
const objectRegistry & db () const noexcept
const Time & time () const noexcept
const word & name () const noexcept
const word & headerClassName () const noexcept
word & headerClassName () noexcept
const string & note () const noexcept
string & note () noexcept
unsigned labelByteSize () const noexcept
unsigned scalarByteSize () const noexcept
void resetHeader (const word &newName=word::null)
bool hasHeaderClass () const noexcept
template<class Type >
bool isHeaderClass () const
template<class Type >
bool isHeaderClassName () const
word group () const
word member () const
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const noexcept
fileName & instance () noexcept
const fileName & local () const noexcept
fileName path () const
fileName path (const word &instance, const fileName &local=fileName::null) const
fileName objectPath () const
fileName objectRelPath () const
fileName localFilePath (const word &typeName, const bool search=true) const
fileName globalFilePath (const word &typeName, const bool search=true) const
IOstreamOption parseHeader (const dictionary &headerDict)
bool readHeader (Istream &is)
bool readHeader (dictionary &headerDict, Istream &is)
template<class Type >
bool typeHeaderOk (const bool checkType=true, const bool search=true, const bool verbose=true)
template<class Type >
void warnNoRereading () const
bool writeHeader (Ostream &os) const
bool writeHeader (Ostream &os, const word &objectType) const
void writeHeader (dictionary &dict, IOstreamOption streamOpt) const
void writeHeader (dictionary &dict, const word &objectType, IOstreamOption streamOpt) const
bool good () const noexcept
bool bad () const noexcept
InfoProxy< IOobject > info () const noexcept
void operator= (const IOobject &io)
template<>
bool isHeaderClass () const
template<class StringType >
Foam::word groupName (StringType base, const word &group)
Public Member Functions inherited from IOobjectOption
constexpr IOobjectOption (readOption rOpt=readOption::NO_READ, writeOption wOpt=writeOption::NO_WRITE, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (readOption rOpt, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (writeOption wOpt, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (registerOption registerObject, bool globalObject=false) noexcept
constexpr IOobjectOption (readOption rOpt, writeOption wOpt, bool registerObject, bool globalObject=false) noexcept
constexpr IOobjectOption (bool registerObject, bool globalObject=false) noexcept
readOption readOpt () const noexcept
readOption readOpt (readOption opt) noexcept
writeOption writeOpt () const noexcept
writeOption writeOpt (writeOption opt) noexcept
bool registerObject () const noexcept
bool registerObject (bool on) noexcept
bool globalObject () const noexcept
bool globalObject (bool on) noexcept
bool isAnyRead () const noexcept
bool isReadRequired () const noexcept
bool isReadOptional () const noexcept
readOption & readOpt () noexcept
writeOption & writeOpt () noexcept
bool & registerObject () noexcept
bool & globalObject () noexcept
Public Member Functions inherited from Field< Type >
constexpr Field () noexcept
Field (const label len)
Field (const label len, const Type &val)
Field (const label len, const Foam::zero)
Field (const Foam::one, const Type &val)
Field (const Foam::one, Type &&val)
Field (const Foam::one, const Foam::zero)
Field (const Field< Type > &fld)
Field (const UList< Type > &list)
template<class Addr >
Field (const IndirectListBase< Type, Addr > &list)
Field (Field< Type > &&fld)
Field (List< Type > &&list)
template<int SizeMin>
Field (DynamicList< Type, SizeMin > &&list)
Field (const UList< Type > &mapF, const labelUList &mapAddressing)
Field (const tmp< Field< Type > > &tmapF, const labelUList &mapAddressing)
Field (const UList< Type > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Field (const tmp< Field< Type > > &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Field (const UList< Type > &mapF, const FieldMapper &map, const bool applyFlip=true)
Field (const UList< Type > &mapF, const FieldMapper &map, const Type &defaultValue, const bool applyFlip=true)
Field (const UList< Type > &mapF, const FieldMapper &map, const UList< Type > &defaultValues, const bool applyFlip=true)
Field (const tmp< Field< Type > > &tmapF, const FieldMapper &map, const bool applyFlip=true)
Field (const tmp< Field< Type > > &tmapF, const FieldMapper &map, const Type &defaultValue, const bool applyFlip=true)
Field (const tmp< Field< Type > > &tmapF, const FieldMapper &map, const UList< Type > &defaultValues, const bool applyFlip=true)
Field (Field< Type > &fld, bool reuse)
Field (const tmp< Field< Type > > &tfld)
Field (Istream &is)
Field (const entry &e, const label len)
Field (const word &key, const dictionary &dict, const label len, IOobjectOption::readOption readOpt=IOobjectOption::MUST_READ)
tmp< Field< Type > > clone () const
void assign (const entry &e, const label len)
bool assign (const word &key, const dictionary &dict, const label len, IOobjectOption::readOption readOpt=IOobjectOption::MUST_READ)
void map (const UList< Type > &mapF, const labelUList &mapAddressing)
void map (const tmp< Field< Type > > &tmapF, const labelUList &mapAddressing)
void map (const UList< Type > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
void map (const tmp< Field< Type > > &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
void map (const UList< Type > &mapF, const FieldMapper &map, const bool applyFlip=true)
void map (const tmp< Field< Type > > &tmapF, const FieldMapper &map, const bool applyFlip=true)
void autoMap (const FieldMapper &map, const bool applyFlip=true)
void rmap (const UList< Type > &mapF, const labelUList &mapAddressing)
void rmap (const tmp< Field< Type > > &tmapF, const labelUList &mapAddressing)
void rmap (const UList< Type > &mapF, const labelUList &mapAddressing, const UList< scalar > &weights)
void rmap (const tmp< Field< Type > > &tmapF, const labelUList &mapAddressing, const UList< scalar > &weights)
void negate ()
void normalise ()
tmp< Field< cmptType > > component (const direction) const
void replace (const direction, const UList< cmptType > &)
void replace (const direction, const tmp< Field< cmptType > > &)
void replace (const direction, const cmptType &)
void clamp_min (const Type &lower)
void clamp_max (const Type &upper)
void clamp_range (const Type &lower, const Type &upper)
void clamp_range (const MinMax< Type > &range)
template<class VSForm >
VSForm block (const label start) const
tmp< Field< Type > > T () const
void writeEntry (const word &keyword, Ostream &os) const
SubField< Type > slice (const label pos, label len=-1)
const SubField< Type > slice (const label pos, label len=-1) const
SubField< Type > slice (const labelRange &range)
const SubField< Type > slice (const labelRange &range) const
void operator= (const Field< Type > &)
void operator= (const tmp< Field< Type > > &)
void operator= (const UList< Type > &rhs)
void operator= (const SubField< Type > &rhs)
template<class Addr >
void operator= (const IndirectListBase< Type, Addr > &rhs)
void operator= (Field< Type > &&rhs)
void operator= (List< Type > &&rhs)
template<int SizeMin>
void operator= (DynamicList< Type, SizeMin > &&rhs)
void operator= (const Type &val)
void operator= (const Foam::zero)
template<class Form , class Cmpt , direction nCmpt>
void operator= (const VectorSpace< Form, Cmpt, nCmpt > &)
void operator+= (const UList< Type > &)
void operator+= (const tmp< Field< Type > > &)
void operator-= (const UList< Type > &)
void operator-= (const tmp< Field< Type > > &)
void operator*= (const UList< scalar > &)
void operator*= (const tmp< Field< scalar > > &)
void operator/= (const UList< scalar > &)
void operator/= (const tmp< Field< scalar > > &)
void operator+= (const Type &)
void operator-= (const Type &)
void operator*= (const scalar &)
void operator/= (const scalar &)
template<class Type >
void operator= (const tmp< Field > &rhs)
void normalise ()
void normalise ()
void normalise ()
void normalise ()
Public Member Functions inherited from FieldBase
constexpr FieldBase () noexcept
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Public Member Functions inherited from List< Type >
constexpr List () noexcept
List (const label len)
List (const label len, const Type &val)
List (const label len, const Foam::zero)
List (const Foam::one, const Type &val)
List (const Foam::one, Type &&val)
List (const Foam::one, const Foam::zero)
List (const List< Type > &a)
List (const UList< Type > &a)
List (List< Type > &a, bool reuse)
List (const UList< Type > &list, const labelUList &indices)
List (const UList< Type > &list, const FixedList< label, N > &indices)
List (const FixedList< Type, N > &list)
List (const PtrList< Type > &list)
List (const SLList< Type > &list)
List (const IndirectListBase< Type, Addr > &list)
List (std::initializer_list< Type > list)
List (List< Type > &&list)
List (DynamicList< Type, SizeMin > &&list)
List (SLList< Type > &&list)
List (Istream &is)
autoPtr< List< Type > > clone () const
~List ()
void clear ()
void resize (const label len)
void resize (const label len, const Type &val)
void resize (const label newLen)
void resize_nocopy (const label len)
void setSize (const label n)
void setSize (const label n, const Type &val)
void transfer (List< Type > &list)
void transfer (DynamicList< Type, SizeMin > &list)
Type & newElmt (const label i)
Type & emplace_back (Args &&... args)
void push_back (const Type &val)
void push_back (Type &&val)
void push_back (const UList< Type > &list)
void push_back (const IndirectListBase< Type, Addr > &list)
label push_uniq (const Type &val)
void pop_back (label n=1)
void operator= (const UList< Type > &a)
void operator= (const List< Type > &list)
void operator= (const SLList< Type > &list)
void operator= (const IndirectListBase< Type, Addr > &list)
void operator= (const FixedList< Type, N > &list)
void operator= (std::initializer_list< Type > list)
void operator= (const Type &val)
void operator= (const Foam::zero)
void operator= (List< Type > &&list)
void operator= (DynamicList< Type, SizeMin > &&list)
void operator= (SLList< Type > &&list)
Istream & readList (Istream &is)
Istream & readList (Istream &is)
Istream & readList (Istream &is)
void shallowCopy (const UList< Type > &)=delete
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type set (const label i, bool val=true)
void append (const Type &val)
void append (Type &&val)
void append (const UList< Type > &list)
void append (const IndirectListBase< Type, Addr > &list)
label appendUniq (const Type &val)
Public Member Functions inherited from UList< T >
UList (const UList< T > &)=default
constexpr UList () noexcept
UList (T *__restrict__ v, const label len) noexcept
label fcIndex (const label i) const noexcept
label rcIndex (const label i) const noexcept
const T & fcValue (const label i) const
T & fcValue (const label i)
const T & rcValue (const label i) const
T & rcValue (const label i)
const T * cdata () const noexcept
T * data () noexcept
const char * cdata_bytes () const noexcept
char * data_bytes () noexcept
T & front ()
const T & front () const
T & back ()
const T & back () const
std::streamsize size_bytes () const noexcept
std::streamsize byteSize () const
void checkStart (const label start) const
void checkSize (const label size) const
void checkRange (const label start, const label len) const
void checkIndex (const label i) const
bool uniform () const
label find (const T &val, label pos=0) const
label rfind (const T &val, label pos=-1) const
bool contains (const T &val, label pos=0) const
void moveFirst (const label i)
void moveLast (const label i)
void swapFirst (const label i)
void swapLast (const label i)
void shallowCopy (const UList< T > &list)
void deepCopy (const UList< T > &list)
template<class Addr >
void deepCopy (const IndirectListBase< T, Addr > &list)
SubList< T > slice (const label pos, label len=-1)
const SubList< T > slice (const label pos, label len=-1) const
SubList< T > slice (const labelRange &range)
const SubList< T > slice (const labelRange &range) const
T & operator[] (const label i)
const T & operator[] (const label i) const
operator const Foam::List< T > & () const
void operator= (const T &val)
void operator= (const Foam::zero)
iterator begin () noexcept
iterator end () noexcept
iterator begin (const label i) noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
const_iterator begin () const noexcept
const_iterator end () const noexcept
const_iterator cbegin (const label i) const noexcept
const_iterator begin (const label i) const noexcept
reverse_iterator rbegin ()
reverse_iterator rend ()
const_reverse_iterator crbegin () const
const_reverse_iterator crend () const
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
bool empty () const noexcept
label size () const noexcept
void swap (UList< T > &list)
bool operator== (const UList< T > &a) const
bool operator!= (const UList< T > &a) const
bool operator< (const UList< T > &list) const
bool operator> (const UList< T > &a) const
bool operator<= (const UList< T > &a) const
bool operator>= (const UList< T > &a) const
Istream & readList (Istream &is)
void writeEntry (const word &keyword, Ostream &os) const
Ostream & writeList (Ostream &os, const label shortLen=0) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type test (const label i) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type get (const label i) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type unset (const label i)
T & first ()
const T & first () const
T & last ()
const T & last () const
bool found (const T &val, label pos=0) const
Istream & readList (Istream &is)
Ostream & writeList (Ostream &os, const label) const
const bool & operator[] (const label i) const
UPstream::commsStruct & operator[] (const label procID)
const UPstream::commsStruct & operator[] (const label procID) const
Foam::UPstream::commsStruct & operator[] (const label procID)
const Foam::UPstream::commsStruct & operator[] (const label procID) const
Ostream & writeList (Ostream &os, const label) const
Istream & readList (Istream &is)
Public Member Functions inherited from transportModel
TypeName ("transportModel")
transportModel ()
virtual ~transportModel ()
Static Public Member Functions
static autoPtr< phaseModel > New (const phaseSystem &fluid, const word &phaseName, const label index)
Static Public Member Functions inherited from GeometricField< scalar, fvPatchField, volMesh >
static const GeometricField< scalar, fvPatchField, volMesh > & null ()
static tmp< GeometricField< scalar, fvPatchField, volMesh > > New (const word &name, const Mesh &mesh, const dimensionSet &dims, const word &patchFieldType=fvPatchField< scalar >::calculatedType())
static tmp< GeometricField< scalar, fvPatchField, volMesh > > New (const word &name, const Mesh &mesh, const dimensionSet &dims, const Field< scalar > &iField, const word &patchFieldType=fvPatchField< scalar >::calculatedType())
static tmp< GeometricField< scalar, fvPatchField, volMesh > > New (const word &name, const Mesh &mesh, const dimensionSet &dims, Field< scalar > &&iField, const word &patchFieldType=fvPatchField< scalar >::calculatedType())
static tmp< GeometricField< scalar, fvPatchField, volMesh > > New (const word &name, const Mesh &mesh, const scalar &value, const dimensionSet &dims, const word &patchFieldType=fvPatchField< scalar >::calculatedType())
static tmp< GeometricField< scalar, fvPatchField, volMesh > > New (const word &name, const Mesh &mesh, const scalar &value, const dimensionSet &dims, const wordList &patchFieldTypes, const wordList &actualPatchTypes=wordList())
static tmp< GeometricField< scalar, fvPatchField, volMesh > > New (const word &name, const Mesh &mesh, const dimensioned< scalar > &dt, const word &patchFieldType=fvPatchField< scalar >::calculatedType())
static tmp< GeometricField< scalar, fvPatchField, volMesh > > New (const word &name, const Mesh &mesh, const dimensioned< scalar > &dt, const wordList &patchFieldTypes, const wordList &actualPatchTypes=wordList())
static tmp< GeometricField< scalar, fvPatchField, volMesh > > New (const word &newName, const tmp< GeometricField< scalar, fvPatchField, volMesh > > &tgf)
static tmp< GeometricField< scalar, fvPatchField, volMesh > > New (const word &newName, const tmp< GeometricField< scalar, fvPatchField, volMesh > > &tgf, const word &patchFieldType)
static tmp< GeometricField< scalar, fvPatchField, volMesh > > New (const word &newName, const tmp< GeometricField< scalar, fvPatchField, volMesh > > &tgf, const wordList &patchFieldTypes, const wordList &actualPatchTypes=wordList())
static tmp< GeometricField< scalar, fvPatchField, volMesh > > New (const GeometricField< AnyType, fvPatchField, volMesh > &fld, const word &name, const dimensionSet &dims, const word &patchFieldType=fvPatchField< scalar >::calculatedType())
static tmp< GeometricField< scalar, fvPatchField, volMesh > > New (const GeometricField< AnyType, fvPatchField, volMesh > &fld, const word &name, const dimensioned< scalar > &dt, const word &patchFieldType=fvPatchField< scalar >::calculatedType())
Static Public Member Functions inherited from DimensionedField< Type, GeoMesh >
static const DimensionedField< Type, GeoMesh > & null ()
static tmp< DimensionedField< Type, GeoMesh > > New (const word &name, const Mesh &mesh, const dimensionSet &dims, const Field< Type > &iField)
static tmp< DimensionedField< Type, GeoMesh > > New (const word &name, const Mesh &mesh, const dimensionSet &dims, Field< Type > &&iField)
static tmp< DimensionedField< Type, GeoMesh > > New (const word &name, const Mesh &mesh, const dimensionSet &dims)
static tmp< DimensionedField< Type, GeoMesh > > New (const word &name, const Mesh &mesh, const Type &value, const dimensionSet &dims)
static tmp< DimensionedField< Type, GeoMesh > > New (const word &name, const Mesh &mesh, const dimensioned< Type > &dt)
static tmp< DimensionedField< Type, GeoMesh > > New (const word &newName, const tmp< DimensionedField< Type, GeoMesh > > &tfld)
template<class AnyType >
static tmp< DimensionedField< Type, GeoMesh > > New (const DimensionedField< AnyType, GeoMesh > &fld, const word &name, const dimensionSet &dims)
template<class AnyType >
static tmp< DimensionedField< Type, GeoMesh > > New (const DimensionedField< AnyType, GeoMesh > &fld, const word &name, const dimensioned< Type > &dt)
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *p)
template<class Type >
static Type & store (autoPtr< Type > &ptr)
template<class Type >
static Type & store (autoPtr< Type > &&ptr)
template<class Type >
static Type & store (refPtr< Type > &ptr)
template<class Type >
static Type & store (refPtr< Type > &&ptr)
template<class Type >
static Type & store (tmp< Type > &ptr)
template<class Type >
static Type & store (tmp< Type > &&ptr)
Static Public Member Functions inherited from IOobject
static bool bannerEnabled () noexcept
static bool bannerEnabled (bool on) noexcept
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
template<class StringType >
static word groupName (StringType base, const word &group)
static word group (const word &name)
static word member (const word &name)
static word scopedName (const std::string &scope, const word &name)
static IOobject selectIO (const IOobject &io, const fileName &altFile, const word &ioName="")
static Ostream & writeBanner (Ostream &os, const bool noSyntaxHint=false)
static Ostream & writeDivider (Ostream &os)
static Ostream & writeEndDivider (Ostream &os)
Static Public Member Functions inherited from IOobjectOption
static bool isAnyRead (readOption opt) noexcept
static bool isReadRequired (readOption opt) noexcept
static bool isReadOptional (readOption opt) noexcept
static readOption lazierRead (readOption opt) noexcept
Static Public Member Functions inherited from Field< Type >
static const Field< Type > & null ()
static autoPtr< Field< Type > > New (Istream &is)
template<class Type2 >
static tmp< Field< Type > > NewCalculatedType (const Field< Type2 > &f)
Static Public Member Functions inherited from List< Type >
static const List< Type > & null ()
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
static constexpr label max_size () noexcept
Additional Inherited Members
Public Types inherited from GeometricField< scalar, fvPatchField, volMesh >
typedef GeoMesh::Mesh Mesh
typedef GeoMesh::BoundaryMesh BoundaryMesh
typedef DimensionedField< scalar, volMesh > Internal
typedef GeometricBoundaryField< scalar, fvPatchField, volMesh > Boundary
typedef fvPatchField< scalar > Patch
typedef Field< scalar >::cmptType cmptType
Public Types inherited from DimensionedField< Type, GeoMesh >
typedef GeoMesh::Mesh Mesh
typedef Field< Type > FieldType
typedef Field< Type >::cmptType cmptType
Public Types inherited from IOobject
enum objectState : char { GOOD , BAD }
enum fileCheckTypes : char { timeStamp , timeStampMaster , inotify , inotifyMaster }
Public Types inherited from IOobjectOption
enum readOption : unsigned char {
NO_READ = 0 , MUST_READ = 0x1 , READ_MODIFIED = 0x3 , MUST_READ_IF_MODIFIED = 0x3 ,
LAZY_READ = 0x4 , READ_IF_PRESENT = 0x4
}
enum writeOption : unsigned char { NO_WRITE = 0 , AUTO_WRITE = 0x10 }
enum registerOption : unsigned char { NO_REGISTER = 0 , REGISTER = 1 }
Public Types inherited from Field< Type >
typedef pTraits< Type >::cmptType cmptType
typedef SubField< Type > subField
Public Types inherited from List< Type >
typedef SubList< Type > subList
Public Types inherited from UList< T >
typedef T value_type
typedef T * pointer
typedef const T * const_pointer
typedef T & reference
typedef const T & const_reference
typedef T * iterator
typedef const T * const_iterator
typedef label size_type
typedef label difference_type
typedef std::reverse_iterator< iterator > reverse_iterator
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
Static Public Attributes inherited from IOobject
static const Enum< fileCheckTypes > fileCheckTypesNames
static char scopeSeparator
static fileCheckTypes fileModificationChecking
static float fileModificationSkew
static int maxFileModificationPolls
Static Public Attributes inherited from FieldBase
static const char *const typeName
static bool allowConstructFromLargerSize = false
Protected Member Functions inherited from regIOobject
bool readHeaderOk (const IOstreamOption::streamFormat fmt, const word &typeName)
Protected Member Functions inherited from IOobject
void setBad (const string &s)
Protected Member Functions inherited from UList< T >
void setAddressableSize (const label n) noexcept
void size (const label n)
void writeEntry (Ostream &os) const
labelRange validateRange (const labelRange &requestedRange) const
UList< T > & operator= (const UList< T > &)=delete
void writeEntry (Ostream &os) const
void writeEntry (Ostream &os) const
Static Protected Member Functions inherited from IOobject
static void writeHeaderContent (Ostream &os, const IOobject &io, const word &objectType, const dictionary *metaDataDict=nullptr)
static void writeHeaderContent (dictionary &dict, const IOobject &io, const word &objectType, IOstreamOption streamOpt, const dictionary *metaDataDict=nullptr)
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
Detailed Description
Single incompressible phase derived from the phase-fraction. Used as part of the multiPhaseMixture for interface-capturing multi-phase simulations.
Source files
phaseModel.H
phaseModel.C
Source files
phaseModel.H
phaseModel.C
Source files
phaseModel.H
phaseModel.C
Source files
phaseModel.H
phaseModel.C
Source files
phaseModel.H
phaseModel.C
Definition at line 53 of file phaseModel.H.
Constructor & Destructor Documentation
phaseModel() [1/4]
phaseModel (const word & phaseName, const dictionary & phaseDict, const fvMesh & mesh)
Definition at line 32 of file phaseModel.C.
References IOobjectOption::AUTO_WRITE, GeometricField< Type, PatchField, GeoMesh >::boundaryField(), fvsPatchFieldBase::calculatedType(), Foam::dimDensity, Foam::dimSpecificHeatCapacity, Foam::dimTime, Foam::dimVelocity, Foam::dimViscosity, Foam::endl(), Foam::fvc::flux(), forAll, IOobject::groupName(), Foam::Info, DimensionedField< Type, GeoMesh >::mesh(), IOobjectOption::MUST_READ, diameterModel::New(), IOobjectOption::NO_READ, DimensionedField< Type, GeoMesh >::setOriented(), and UPtrList< T >::size().
~phaseModel() [1/3]
~phaseModel () virtual
Definition at line 195 of file phaseModel.C.
phaseModel() [2/4]
phaseModel (const phaseSystem & fluid, const word & phaseName, const label index)
Definition at line 37 of file phaseModel.C.
References Foam::dimless, phaseModel::fluid(), and diameterModel::New().
~phaseModel() [2/3]
virtual ~phaseModel () virtual
phaseModel() [3/4]
phaseModel (const twoPhaseSystem & fluid, const dictionary & phaseProperties, const word & phaseName)
Definition at line 39 of file phaseModel.C.
References IOobjectOption::AUTO_WRITE, GeometricField< Type, PatchField, GeoMesh >::boundaryField(), fvsPatchFieldBase::calculatedType(), Foam::dimless, Foam::endl(), Foam::fvc::flux(), forAll, IOobject::groupName(), Foam::Info, IOobjectOption::MUST_READ, PhaseCompressibleTurbulenceModel< TransportModel >::New(), diameterModel::New(), Foam::New(), IOobjectOption::NO_READ, phaseModel::phi(), DimensionedField< Type, GeoMesh >::setOriented(), and UPtrList< T >::size().
~phaseModel() [3/3]
virtual ~phaseModel () virtual
phaseModel() [4/4]
phaseModel (const word & phaseName, const volScalarField & p, const volScalarField & T)
Member Function Documentation
clone() [1/3]
Foam::autoPtr< Foam::phaseModel > clone () const
Definition at line 201 of file phaseModel.C.
References NotImplemented.
name() [1/4]
const Foam::word & name () const inline
Definition at line 139 of file phaseModel.H.
Referenced by MassTransferPhaseSystem< BasePhaseSystem >::alphaTransfer(), ThermalPhaseChangePhaseSystem< BasePhaseSystem >::correctInterfaceThermo(), OneResistanceHeatTransferPhaseSystem< BasePhaseSystem >::heatTransfer(), ThermalPhaseChangePhaseSystem< BasePhaseSystem >::heatTransfer(), TwoResistanceHeatTransferPhaseSystem< BasePhaseSystem >::heatTransfer(), InterfaceCompositionPhaseChangePhaseSystem< BasePhaseSystem >::InterfaceCompositionPhaseChangePhaseSystem(), phaseModel::keyword(), MassTransferPhaseSystem< BasePhaseSystem >::massSpeciesTransfer(), InterfaceCompositionPhaseChangePhaseSystem< BasePhaseSystem >::massTransfer(), PhaseTransferPhaseSystem< BasePhaseSystem >::massTransfer(), PopulationBalancePhaseSystem< BasePhaseSystem >::massTransfer(), ThermalPhaseChangePhaseSystem< BasePhaseSystem >::massTransfer(), and MassTransferPhaseSystem< BasePhaseSystem >::volTransfer().
keyword() [1/3]
const Foam::word & keyword () const inline
Definition at line 144 of file phaseModel.H.
References phaseModel::name().
d() [1/3]
Foam::tmp< Foam::volScalarField > d () const
Definition at line 251 of file phaseModel.C.
nu() [1/5]
const dimensionedScalar & nu () const inline virtual
Implements transportModel.
Definition at line 151 of file phaseModel.H.
kappa() [1/5]
const dimensionedScalar & kappa () const inline
Definition at line 156 of file phaseModel.H.
Cp() [1/2]
const dimensionedScalar & Cp () const inline
Definition at line 161 of file phaseModel.H.
rho() [1/3]
const dimensionedScalar & rho () const inline
Definition at line 166 of file phaseModel.H.
Referenced by LehrMilliesMewes::addToBinaryBreakupRate(), LuoSvendsen::addToBinaryBreakupRate(), CoulaloglouTavlaridesCoalescence::addToCoalescenceRate(), Luo::addToCoalescenceRate(), PrinceBlanch::addToCoalescenceRate(), ThermalPhaseChangePhaseSystem< BasePhaseSystem >::correctInterfaceThermo(), multiphaseSystem::Cvm(), phasePair::rho(), LaakkonenAlopaeusAittamaa::setBreakupRate(), and multiphaseSystem::Svm().
U() [1/5]
const volVectorField & U () const inline
Definition at line 171 of file phaseModel.H.
Referenced by MomentumTransferPhaseSystem< BasePhaseSystem >::ddtCorrByAs(), MomentumTransferPhaseSystem< BasePhaseSystem >::momentumTransfer(), and MomentumTransferPhaseSystem< BasePhaseSystem >::momentumTransferf().
U() [2/5]
volVectorField & U () inline
Definition at line 176 of file phaseModel.H.
DDtU() [1/2]
const volVectorField & DDtU () const inline
Definition at line 181 of file phaseModel.H.
Referenced by multiphaseSystem::Svm().
DDtU() [2/2]
volVectorField & DDtU () inline
Definition at line 186 of file phaseModel.H.
phi() [1/5]
const surfaceScalarField & phi () const inline
Definition at line 191 of file phaseModel.H.
Referenced by MomentumTransferPhaseSystem< BasePhaseSystem >::ddtCorrByAs(), and phaseModel::phaseModel().
phi() [2/5]
surfaceScalarField & phi () inline
Definition at line 196 of file phaseModel.H.
alphaPhi() [1/5]
const surfaceScalarField & alphaPhi () const inline
Definition at line 201 of file phaseModel.H.
alphaPhi() [2/5]
surfaceScalarField & alphaPhi () inline
Definition at line 206 of file phaseModel.H.
correctInflowOutflow() [1/3]
void correctInflowOutflow (surfaceScalarField & alphaPhi) const
Definition at line 233 of file phaseModel.C.
References alphaPhi(), GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), forAll, and phi.
correct() [1/4]
void correct () virtual
Implements transportModel.
Definition at line 209 of file phaseModel.C.
read() [1/4]
bool read (const dictionary & phaseDict)
Definition at line 215 of file phaseModel.C.
ClassName()
ClassName ("phaseModel")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , phaseModel , phaseSystem , (const phaseSystem &fluid, const word &phaseName, const label index) , (fluid, phaseName, index))
clone() [2/3]
autoPtr< phaseModel > clone () const
New()
Foam::autoPtr< Foam::phaseModel > New (const phaseSystem & fluid, const word & phaseName, const label index) static
Definition at line 84 of file phaseModel.C.
References Foam::abort(), dict, Foam::endl(), Foam::FatalIOError, FatalIOErrorInLookup, fluid, dictionary::get(), Foam::Info, and dictionary::subDict().
Referenced by phaseModel::iNew::operator()().
name() [2/4]
const word & name () const
keyword() [2/3]
const word & keyword () const
index()
Foam::label index () const
Definition at line 135 of file phaseModel.C.
Referenced by MomentumTransferPhaseSystem< BasePhaseSystem >::ddtCorrByAs(), and MomentumTransferPhaseSystem< BasePhaseSystem >::momentumTransferf().
fluid() [1/2]
const Foam::phaseSystem & fluid () const
Definition at line 141 of file phaseModel.C.
Referenced by orderedPhasePair::E(), phaseModel::phaseModel(), and phasePair::sigma().
residualAlpha() [1/2]
const Foam::dimensionedScalar & residualAlpha () const
Definition at line 147 of file phaseModel.C.
alphaMax() [1/2]
Foam::scalar alphaMax () const
Definition at line 153 of file phaseModel.C.
d() [2/3]
tmp< volScalarField > d () const
dPtr()
const Foam::autoPtr< Foam::diameterModel > & dPtr () const
Definition at line 165 of file phaseModel.C.
correct() [2/4]
virtual void correct () virtual
Implements transportModel.
correctKinematics()
void correctKinematics () virtual
Definition at line 177 of file phaseModel.C.
correctThermo()
void correctThermo () virtual
Definition at line 181 of file phaseModel.C.
correctTurbulence()
void correctTurbulence () virtual
Definition at line 185 of file phaseModel.C.
correctEnergyTransport()
void correctEnergyTransport () virtual
Definition at line 189 of file phaseModel.C.
correctInflowOutflow() [2/3]
void correctInflowOutflow (surfaceScalarField & alphaPhi) const
read() [2/4]
bool read () virtual
Reimplemented from regIOobject.
Definition at line 193 of file phaseModel.C.
compressible()
virtual bool compressible () const pure virtual
divU() [1/2]
virtual tmp< volScalarField > divU () const pure virtual
divU() [2/2]
virtual void divU (tmp< volScalarField > divU) pure virtual
isothermal()
virtual bool isothermal () const pure virtual
heEqn()
virtual tmp< fvScalarMatrix > heEqn () pure virtual
thermo() [1/5]
virtual const rhoThermo & thermo () const pure virtual
Referenced by ThermalPhaseChangePhaseSystem< BasePhaseSystem >::correctInterfaceThermo(), TwoResistanceHeatTransferPhaseSystem< BasePhaseSystem >::correctInterfaceThermo(), OneResistanceHeatTransferPhaseSystem< BasePhaseSystem >::heatTransfer(), ThermalPhaseChangePhaseSystem< BasePhaseSystem >::heatTransfer(), and TwoResistanceHeatTransferPhaseSystem< BasePhaseSystem >::heatTransfer().
thermoRef()
virtual rhoThermo & thermoRef () pure virtual
rho() [2/3]
virtual tmp< volScalarField > rho () const pure virtual
pure()
virtual bool pure () const pure virtual
YiEqn()
virtual tmp< fvScalarMatrix > YiEqn (volScalarField & Yi) pure virtual
Y() [1/2]
virtual const PtrList< volScalarField > & Y () const pure virtual
Y() [2/2]
virtual const volScalarField & Y (const word & name) const pure virtual
YRef()
virtual PtrList< volScalarField > & YRef () pure virtual
YActive()
virtual const UPtrList< volScalarField > & YActive () const pure virtual
YActiveRef()
virtual UPtrList< volScalarField > & YActiveRef () pure virtual
stationary()
virtual bool stationary () const pure virtual
UEqn()
virtual tmp< fvVectorMatrix > UEqn () pure virtual
UfEqn()
virtual tmp< fvVectorMatrix > UfEqn () pure virtual
U() [3/5]
virtual tmp< volVectorField > U () const pure virtual
URef()
virtual volVectorField & URef () pure virtual
phi() [3/5]
virtual tmp< surfaceScalarField > phi () const pure virtual
phiRef()
virtual surfaceScalarField & phiRef () pure virtual
alphaPhi() [3/5]
virtual tmp< surfaceScalarField > alphaPhi () const pure virtual
alphaPhiRef()
virtual surfaceScalarField & alphaPhiRef () pure virtual
alphaRhoPhi() [1/3]
virtual tmp< surfaceScalarField > alphaRhoPhi () const pure virtual
alphaRhoPhiRef()
virtual surfaceScalarField & alphaRhoPhiRef () pure virtual
DUDt()
virtual tmp< volVectorField > DUDt () const pure virtual
Referenced by MomentumTransferPhaseSystem< BasePhaseSystem >::momentumTransfer().
DUDtf()
virtual tmp< surfaceScalarField > DUDtf () const pure virtual
continuityError()
virtual tmp< volScalarField > continuityError () const pure virtual
continuityErrorFlow()
virtual tmp< volScalarField > continuityErrorFlow () const pure virtual
continuityErrorSources()
virtual tmp< volScalarField > continuityErrorSources () const pure virtual
K()
virtual tmp< volScalarField > K () const pure virtual
Referenced by OneResistanceHeatTransferPhaseSystem< BasePhaseSystem >::heatTransfer(), and TwoResistanceHeatTransferPhaseSystem< BasePhaseSystem >::heatTransfer().
mu() [1/4]
virtual tmp< volScalarField > mu () const pure virtual
Referenced by CoulaloglouTavlaridesCoalescence::addToCoalescenceRate(), and LaakkonenAlopaeusAittamaa::setBreakupRate().
mu() [2/4]
virtual tmp< scalarField > mu (const label patchi) const pure virtual
nu() [2/5]
virtual tmp< volScalarField > nu () const pure virtual
Implements transportModel.
nu() [3/5]
virtual tmp< scalarField > nu (const label patchi) const pure virtual
Implements transportModel.
alpha() [1/4]
virtual tmp< volScalarField > alpha () const pure virtual
alpha() [2/4]
virtual tmp< scalarField > alpha (const label patchi) const pure virtual
kappa() [2/5]
virtual tmp< volScalarField > kappa () const pure virtual
kappa() [3/5]
virtual tmp< scalarField > kappa (const label patchi) const pure virtual
alphahe() [1/4]
virtual tmp< volScalarField > alphahe () const pure virtual
alphahe() [2/4]
virtual tmp< scalarField > alphahe (const label patchi) const pure virtual
kappaEff() [1/6]
virtual tmp< volScalarField > kappaEff (const volScalarField & alphat) const pure virtual
kappaEff() [2/6]
virtual tmp< scalarField > kappaEff (const scalarField & alphat, const label patchi) const pure virtual
alphaEff() [1/6]
virtual tmp< volScalarField > alphaEff (const volScalarField & alphat) const pure virtual
alphaEff() [2/6]
virtual tmp< scalarField > alphaEff (const scalarField & alphat, const label patchi) const pure virtual
mut()
virtual tmp< volScalarField > mut () const pure virtual
muEff()
virtual tmp< volScalarField > muEff () const pure virtual
nut()
virtual tmp< volScalarField > nut () const pure virtual
nuEff()
virtual tmp< volScalarField > nuEff () const pure virtual
kappaEff() [3/6]
virtual tmp< volScalarField > kappaEff () const pure virtual
kappaEff() [4/6]
virtual tmp< scalarField > kappaEff (const label patchi) const pure virtual
alphaEff() [3/6]
virtual tmp< volScalarField > alphaEff () const pure virtual
alphaEff() [4/6]
virtual tmp< scalarField > alphaEff (const label patchi) const pure virtual
k()
virtual tmp< volScalarField > k () const pure virtual
pPrime()
virtual tmp< volScalarField > pPrime () const pure virtual
name() [3/4]
const word & name () const inline
Definition at line 118 of file phaseModel.H.
fluid() [2/2]
const twoPhaseSystem & fluid () const inline
Definition at line 124 of file phaseModel.H.
otherPhase()
const Foam::phaseModel & otherPhase () const
Definition at line 211 of file phaseModel.C.
Referenced by ThermalPhaseChangePhaseSystem< BasePhaseSystem >::correctInterfaceThermo(), MomentumTransferPhaseSystem< BasePhaseSystem >::ddtCorrByAs(), OneResistanceHeatTransferPhaseSystem< BasePhaseSystem >::heatTransfer(), InterfaceCompositionPhaseChangePhaseSystem< BasePhaseSystem >::iDmdt(), MomentumTransferPhaseSystem< BasePhaseSystem >::momentumTransfer(), and MomentumTransferPhaseSystem< BasePhaseSystem >::momentumTransferf().
residualAlpha() [2/2]
const dimensionedScalar & residualAlpha () const inline
Definition at line 134 of file phaseModel.H.
alphaMax() [2/2]
scalar alphaMax () const inline
Definition at line 141 of file phaseModel.H.
d() [3/3]
tmp< volScalarField > d () const
turbulence() [1/2]
const Foam::PhaseCompressibleTurbulenceModel< Foam::phaseModel > & turbulence () const
Definition at line 231 of file phaseModel.C.
turbulence() [2/2]
Foam::PhaseCompressibleTurbulenceModel< Foam::phaseModel > & turbulence ()
Definition at line 224 of file phaseModel.C.
thermo() [2/5]
const rhoThermo & thermo () const inline
Definition at line 159 of file phaseModel.H.
thermo() [3/5]
rhoThermo & thermo () inline
Definition at line 166 of file phaseModel.H.
nu() [4/5]
tmp< volScalarField > nu () const inline virtual
Implements transportModel.
Definition at line 172 of file phaseModel.H.
nu() [5/5]
tmp< scalarField > nu (const label patchi) const inline virtual
Implements transportModel.
Definition at line 178 of file phaseModel.H.
mu() [3/4]
tmp< volScalarField > mu () const inline
Definition at line 184 of file phaseModel.H.
mu() [4/4]
tmp< scalarField > mu (const label patchi) const inline
Definition at line 190 of file phaseModel.H.
kappa() [4/5]
tmp< scalarField > kappa (const label patchi) const inline
Definition at line 196 of file phaseModel.H.
kappa() [5/5]
tmp< volScalarField > kappa () const inline
Definition at line 202 of file phaseModel.H.
alphahe() [3/4]
tmp< volScalarField > alphahe () const inline
Definition at line 208 of file phaseModel.H.
alphahe() [4/4]
tmp< scalarField > alphahe (const label patchi) const inline
Definition at line 214 of file phaseModel.H.
kappaEff() [5/6]
tmp< volScalarField > kappaEff (const volScalarField & alphat) const inline
Definition at line 220 of file phaseModel.H.
kappaEff() [6/6]
tmp< scalarField > kappaEff (const scalarField & alphat, const label patchi) const inline
Definition at line 229 of file phaseModel.H.
alpha() [3/4]
tmp< volScalarField > alpha () const inline
Definition at line 239 of file phaseModel.H.
alpha() [4/4]
tmp< scalarField > alpha (const label patchi) const inline
Definition at line 245 of file phaseModel.H.
alphaEff() [5/6]
tmp< volScalarField > alphaEff (const volScalarField & alphat) const inline
Definition at line 251 of file phaseModel.H.
alphaEff() [6/6]
tmp< scalarField > alphaEff (const scalarField & alphat, const label patchi) const inline
Definition at line 260 of file phaseModel.H.
Cp() [2/2]
tmp< volScalarField > Cp () const inline
Definition at line 270 of file phaseModel.H.
rho() [3/3]
const volScalarField & rho () const inline
Definition at line 276 of file phaseModel.H.
U() [4/5]
const volVectorField & U () const inline
Definition at line 282 of file phaseModel.H.
U() [5/5]
volVectorField & U () inline
Definition at line 289 of file phaseModel.H.
phi() [4/5]
const surfaceScalarField & phi () const inline
Definition at line 295 of file phaseModel.H.
phi() [5/5]
surfaceScalarField & phi () inline
Definition at line 301 of file phaseModel.H.
alphaPhi() [4/5]
const surfaceScalarField & alphaPhi () const inline
Definition at line 307 of file phaseModel.H.
alphaPhi() [5/5]
surfaceScalarField & alphaPhi () inline
Definition at line 313 of file phaseModel.H.
alphaRhoPhi() [2/3]
const surfaceScalarField & alphaRhoPhi () const inline
Definition at line 319 of file phaseModel.H.
alphaRhoPhi() [3/3]
surfaceScalarField & alphaRhoPhi () inline
Definition at line 325 of file phaseModel.H.
correctInflowOutflow() [3/3]
void correctInflowOutflow (surfaceScalarField & alphaPhi) const
correct() [3/4]
void correct () virtual
Implements transportModel.
read() [3/4]
virtual bool read (const dictionary & phaseProperties) virtual
read() [4/4]
virtual bool read () inline virtual
Reimplemented from regIOobject.
Definition at line 342 of file phaseModel.H.
clone() [3/3]
autoPtr< phaseModel > clone () const
name() [4/4]
const word & name () const inline
Definition at line 105 of file phaseModel.H.
keyword() [3/3]
const word & keyword () const inline
Definition at line 110 of file phaseModel.H.
References phaseModel::name().
thermo() [4/5]
const rhoThermo & thermo () const inline
Definition at line 116 of file phaseModel.H.
thermo() [5/5]
rhoThermo & thermo () inline
Definition at line 122 of file phaseModel.H.
dgdt() [1/2]
const volScalarField & dgdt () const inline
Definition at line 128 of file phaseModel.H.
dgdt() [2/2]
volScalarField & dgdt () inline
Definition at line 134 of file phaseModel.H.
correct() [4/4]
void correct () virtual
Implements transportModel.
The documentation for this class was generated from the following files:
src/phaseSystemModels/multiphaseEuler/multiphaseSystem/phaseModel/phaseModel.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/phaseModel/phaseModel/phaseModel.H
src/phaseSystemModels/twoPhaseEuler/twoPhaseSystem/phaseModel/phaseModel.H
applications/solvers/multiphase/compressibleMultiphaseInterFoam/multiphaseMixtureThermo/phaseModel/phaseModel.H
src/phaseSystemModels/multiphaseEuler/multiphaseSystem/phaseModel/phaseModel.C
src/phaseSystemModels/reactingEuler/multiphaseSystem/phaseModel/phaseModel/phaseModel.C
src/phaseSystemModels/twoPhaseEuler/twoPhaseSystem/phaseModel/phaseModel.C