OpenFOAM: thermoCoupleProbes Class Reference
thermoCoupleProbes Class Reference
FunctionObjects » Utility function objects
Sample probe for temperature using a thermocouple.
#include <thermoCoupleProbes.H>
Public Member Functions
TypeName ("thermoCoupleProbes")
thermoCoupleProbes (const word &name, const Time &runTime, const dictionary &dict, const bool loadFromFiles=false, const bool readFields=true)
virtual ~thermoCoupleProbes ()=default
virtual label nEqns () const
virtual void derivatives (const scalar x, const scalarField &y, scalarField &dydx) const
virtual void jacobian (const scalar t, const scalarField &y, scalarField &dfdt, scalarSquareMatrix &dfdy) const
virtual bool read (const dictionary &)
virtual bool execute ()
virtual bool write ()
Public Member Functions inherited from probes
TypeName ("probes")
probes (const word &name, const Time &runTime, const dictionary &dict, const bool loadFromFiles=false, const bool readFields=true)
virtual ~probes ()=default
bool verbose (const bool on) noexcept
virtual const wordRes & fieldNames () const noexcept
virtual const pointField & probeLocations () const noexcept
virtual const point & probe (const label i) const
const labelList & elements () const noexcept
virtual void updateMesh (const mapPolyMesh &)
virtual void movePoints (const polyMesh &)
virtual void readUpdate (const polyMesh::readUpdateState state)
template<class Type >
tmp< Field< Type > > sample (const VolumeField< Type > &) const
template<class Type >
tmp< Field< Type > > sample (const SurfaceField< Type > &) const
template<class Type >
tmp< Field< Type > > sample (const word &fieldName) const
template<class Type >
tmp< Field< Type > > sampleSurfaceField (const word &fieldName) const
template<class GeoField >
Foam::tmp< GeoField > getOrLoadField (const word &fieldName) const
template<class Type >
Foam::tmp< Foam::Field< Type > > sample (const VolumeField< Type > &vField) const
template<class Type >
Foam::tmp< Foam::Field< Type > > sample (const SurfaceField< Type > &sField) const
template<class Type >
Foam::tmp< Foam::Field< Type > > sample (const word &fieldName) const
template<class Type >
Foam::tmp< Foam::Field< Type > > sampleSurfaceField (const word &fieldName) const
Public Member Functions inherited from fvMeshFunctionObject
TypeName ("fvMeshFunctionObject")
fvMeshFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
fvMeshFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
virtual ~fvMeshFunctionObject ()=default
Public Member Functions inherited from regionFunctionObject
TypeName ("regionFunctionObject")
regionFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
regionFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
virtual ~regionFunctionObject ()=default
template<class ObjectType >
const ObjectType * lookupObjectPtr (const word &fieldName) const
template<class ObjectType >
ObjectType * lookupObjectRefPtr (const word &fieldName) const
Public Member Functions inherited from stateFunctionObject
stateFunctionObject (const word &name, const Time &runTime)
virtual ~stateFunctionObject ()=default
dictionary & propertyDict ()
bool foundProperty (const word &entryName) const
void clearTrigger ()
label getTrigger () const
bool setTrigger (const label triggeri)
bool getDict (const word &entryName, dictionary &dict) const
bool getObjectDict (const word &objectName, const word &entryName, dictionary &dict) const
template<class Type >
Type getProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getProperty (const word &entryName, Type &value) const
template<class Type >
void setProperty (const word &entryName, const Type &value)
template<class Type >
Type getObjectProperty (const word &objectName, const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getObjectProperty (const word &objectName, const word &entryName, Type &value) const
template<class Type >
void setObjectProperty (const word &objectName, const word &entryName, const Type &value)
template<class Type >
void setResult (const word &entryName, const Type &value)
template<class Type >
void setObjectResult (const word &objectName, const word &entryName, const Type &value)
template<class Type >
Type getResult (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
Type getObjectResult (const word &objectName, const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getObjectResult (const word &objectName, const word &entryName, Type &value) const
word resultType (const word &entryName) const
word objectResultType (const word &objectName, const word &entryName) const
wordList objectResultEntries () const
wordList objectResultEntries (const word &objectName) const
void writeResultEntries (Ostream &os) const
void writeResultEntries (const word &objectName, Ostream &os) const
void writeAllResultEntries (Ostream &os) const
Public Member Functions inherited from timeFunctionObject
timeFunctionObject (const word &name, const Time &runTime)
virtual ~timeFunctionObject ()=default
const Time & time () const
objectRegistry & storedObjects ()
const objectRegistry & storedObjects () const
Public Member Functions inherited from functionObject
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name, const bool withNamePrefix=defaultUseNamePrefix)
autoPtr< functionObject > clone () const
virtual ~functionObject ()=default
virtual const word & type () const =0
const word & name () const noexcept
bool useNamePrefix () const noexcept
bool useNamePrefix (bool on) noexcept
virtual bool execute (const label subIndex)
virtual bool end ()
virtual bool adjustTimeStep ()
virtual bool filesModified () const
Public Member Functions inherited from Field< vector >
constexpr Field () noexcept
Field (const label len)
Field (const label len, const vector &val)
Field (const label len, const Foam::zero)
Field (const Foam::one, const vector &val)
Field (const Foam::one, vector &&val)
Field (const Foam::one, const Foam::zero)
Field (const Field< vector > &fld)
Field (const UList< vector > &list)
Field (const IndirectListBase< vector, Addr > &list)
Field (Field< vector > &&fld)
Field (List< vector > &&list)
Field (DynamicList< vector, SizeMin > &&list)
Field (const UList< vector > &mapF, const labelUList &mapAddressing)
Field (const tmp< Field< vector > > &tmapF, const labelUList &mapAddressing)
Field (const UList< vector > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Field (const tmp< Field< vector > > &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Field (const UList< vector > &mapF, const FieldMapper &map, const bool applyFlip=true)
Field (const UList< vector > &mapF, const FieldMapper &map, const vector &defaultValue, const bool applyFlip=true)
Field (const UList< vector > &mapF, const FieldMapper &map, const UList< vector > &defaultValues, const bool applyFlip=true)
Field (const tmp< Field< vector > > &tmapF, const FieldMapper &map, const bool applyFlip=true)
Field (const tmp< Field< vector > > &tmapF, const FieldMapper &map, const vector &defaultValue, const bool applyFlip=true)
Field (const tmp< Field< vector > > &tmapF, const FieldMapper &map, const UList< vector > &defaultValues, const bool applyFlip=true)
Field (Field< vector > &fld, bool reuse)
Field (const tmp< Field< vector > > &tfld)
Field (Istream &is)
Field (const entry &e, const label len)
Field (const word &key, const dictionary &dict, const label len, IOobjectOption::readOption readOpt=IOobjectOption::MUST_READ)
tmp< Field< vector > > clone () const
void assign (const entry &e, const label len)
bool assign (const word &key, const dictionary &dict, const label len, IOobjectOption::readOption readOpt=IOobjectOption::MUST_READ)
void map (const UList< vector > &mapF, const labelUList &mapAddressing)
void map (const tmp< Field< vector > > &tmapF, const labelUList &mapAddressing)
void map (const UList< vector > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
void map (const tmp< Field< vector > > &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
void map (const UList< vector > &mapF, const FieldMapper &map, const bool applyFlip=true)
void map (const tmp< Field< vector > > &tmapF, const FieldMapper &map, const bool applyFlip=true)
void autoMap (const FieldMapper &map, const bool applyFlip=true)
void rmap (const UList< vector > &mapF, const labelUList &mapAddressing)
void rmap (const tmp< Field< vector > > &tmapF, const labelUList &mapAddressing)
void rmap (const UList< vector > &mapF, const labelUList &mapAddressing, const UList< scalar > &weights)
void rmap (const tmp< Field< vector > > &tmapF, const labelUList &mapAddressing, const UList< scalar > &weights)
void negate ()
void normalise ()
void normalise ()
void normalise ()
void normalise ()
void normalise ()
tmp< Field< cmptType > > component (const direction) const
void replace (const direction, const UList< cmptType > &)
void replace (const direction, const tmp< Field< cmptType > > &)
void replace (const direction, const cmptType &)
void clamp_min (const vector &lower)
void clamp_max (const vector &upper)
void clamp_range (const vector &lower, const vector &upper)
void clamp_range (const MinMax< vector > &range)
VSForm block (const label start) const
tmp< Field< vector > > T () const
void writeEntry (const word &keyword, Ostream &os) const
SubField< vector > slice (const label pos, label len=-1)
const SubField< vector > slice (const label pos, label len=-1) const
SubField< vector > slice (const labelRange &range)
const SubField< vector > slice (const labelRange &range) const
void operator= (const Field< vector > &)
void operator= (const tmp< Field< vector > > &)
void operator= (const UList< vector > &rhs)
void operator= (const SubField< vector > &rhs)
void operator= (const IndirectListBase< vector, Addr > &rhs)
void operator= (Field< vector > &&rhs)
void operator= (List< vector > &&rhs)
void operator= (DynamicList< vector, SizeMin > &&rhs)
void operator= (const vector &val)
void operator= (const Foam::zero)
void operator= (const VectorSpace< Form, Cmpt, nCmpt > &)
void operator= (const tmp< Field > &rhs)
void operator+= (const UList< vector > &)
void operator+= (const tmp< Field< vector > > &)
void operator+= (const vector &)
void operator-= (const UList< vector > &)
void operator-= (const tmp< Field< vector > > &)
void operator-= (const vector &)
void operator*= (const UList< scalar > &)
void operator*= (const tmp< Field< scalar > > &)
void operator*= (const scalar &)
void operator/= (const UList< scalar > &)
void operator/= (const tmp< Field< scalar > > &)
void operator/= (const scalar &)
Public Member Functions inherited from FieldBase
constexpr FieldBase () noexcept
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Public Member Functions inherited from List< T >
constexpr List () noexcept
List (const label len)
List (const label len, const T &val)
List (const label len, const Foam::zero)
List (const Foam::one, const T &val)
List (const Foam::one, T &&val)
List (const Foam::one, const Foam::zero)
List (const List< T > &a)
List (const UList< T > &a)
List (List< T > &a, bool reuse)
List (const UList< T > &list, const labelUList &indices)
template<unsigned N>
List (const UList< T > &list, const FixedList< label, N > &indices)
template<unsigned N>
List (const FixedList< T, N > &list)
List (const PtrList< T > &list)
List (const SLList< T > &list)
template<class Addr >
List (const IndirectListBase< T, Addr > &list)
List (std::initializer_list< T > list)
List (List< T > &&list)
template<int SizeMin>
List (DynamicList< T, SizeMin > &&list)
List (SLList< T > &&list)
List (Istream &is)
autoPtr< List< T > > clone () const
~List ()
void clear ()
void resize (const label len)
void resize (const label len, const T &val)
void resize_nocopy (const label len)
void setSize (const label n)
void setSize (const label n, const T &val)
void transfer (List< T > &list)
template<int SizeMin>
void transfer (DynamicList< T, SizeMin > &list)
T & newElmt (const label i)
template<class... Args>
T & emplace_back (Args &&... args)
void push_back (const T &val)
void push_back (T &&val)
void push_back (const UList< T > &list)
template<class Addr >
void push_back (const IndirectListBase< T, Addr > &list)
label push_uniq (const T &val)
void pop_back (label n=1)
void operator= (const UList< T > &a)
void operator= (const List< T > &list)
void operator= (const SLList< T > &list)
template<class Addr >
void operator= (const IndirectListBase< T, Addr > &list)
template<unsigned N>
void operator= (const FixedList< T, N > &list)
void operator= (std::initializer_list< T > list)
void operator= (const T &val)
void operator= (const Foam::zero)
void operator= (List< T > &&list)
template<int SizeMin>
void operator= (DynamicList< T, SizeMin > &&list)
void operator= (SLList< T > &&list)
Istream & readList (Istream &is)
void shallowCopy (const UList< T > &)=delete
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type set (const label i, bool val=true)
void append (const T &val)
void append (T &&val)
void append (const UList< T > &list)
template<class Addr >
void append (const IndirectListBase< T, Addr > &list)
label appendUniq (const T &val)
Istream & readList (Istream &is)
void resize (const label newLen)
Istream & readList (Istream &is)
Public Member Functions inherited from UList< T >
UList (const UList< T > &)=default
constexpr UList () noexcept
UList (T *__restrict__ v, const label len) noexcept
label fcIndex (const label i) const noexcept
label rcIndex (const label i) const noexcept
const T & fcValue (const label i) const
T & fcValue (const label i)
const T & rcValue (const label i) const
T & rcValue (const label i)
const T * cdata () const noexcept
T * data () noexcept
const char * cdata_bytes () const noexcept
char * data_bytes () noexcept
T & front ()
const T & front () const
T & back ()
const T & back () const
std::streamsize size_bytes () const noexcept
std::streamsize byteSize () const
void checkStart (const label start) const
void checkSize (const label size) const
void checkRange (const label start, const label len) const
void checkIndex (const label i) const
bool uniform () const
label find (const T &val, label pos=0) const
label rfind (const T &val, label pos=-1) const
bool contains (const T &val, label pos=0) const
void moveFirst (const label i)
void moveLast (const label i)
void swapFirst (const label i)
void swapLast (const label i)
void shallowCopy (const UList< T > &list)
void deepCopy (const UList< T > &list)
template<class Addr >
void deepCopy (const IndirectListBase< T, Addr > &list)
SubList< T > slice (const label pos, label len=-1)
const SubList< T > slice (const label pos, label len=-1) const
SubList< T > slice (const labelRange &range)
const SubList< T > slice (const labelRange &range) const
T & operator[] (const label i)
const T & operator[] (const label i) const
operator const Foam::List< T > & () const
void operator= (const T &val)
void operator= (const Foam::zero)
iterator begin () noexcept
iterator end () noexcept
iterator begin (const label i) noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
const_iterator begin () const noexcept
const_iterator end () const noexcept
const_iterator cbegin (const label i) const noexcept
const_iterator begin (const label i) const noexcept
reverse_iterator rbegin ()
reverse_iterator rend ()
const_reverse_iterator crbegin () const
const_reverse_iterator crend () const
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
bool empty () const noexcept
label size () const noexcept
void swap (UList< T > &list)
bool operator== (const UList< T > &a) const
bool operator!= (const UList< T > &a) const
bool operator< (const UList< T > &list) const
bool operator> (const UList< T > &a) const
bool operator<= (const UList< T > &a) const
bool operator>= (const UList< T > &a) const
Istream & readList (Istream &is)
void writeEntry (const word &keyword, Ostream &os) const
Ostream & writeList (Ostream &os, const label shortLen=0) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type test (const label i) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type get (const label i) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type unset (const label i)
T & first ()
const T & first () const
T & last ()
const T & last () const
bool found (const T &val, label pos=0) const
Istream & readList (Istream &is)
Ostream & writeList (Ostream &os, const label) const
const bool & operator[] (const label i) const
UPstream::commsStruct & operator[] (const label procID)
const UPstream::commsStruct & operator[] (const label procID) const
Foam::UPstream::commsStruct & operator[] (const label procID)
const Foam::UPstream::commsStruct & operator[] (const label procID) const
Ostream & writeList (Ostream &os, const label) const
Istream & readList (Istream &is)
Public Member Functions inherited from ODESystem
ODESystem ()
virtual ~ODESystem ()=default
Protected Attributes
scalar rho_
scalar Cp_
scalar d_
scalar epsilon_
word UName_
word radiationFieldName_
const fluidThermo & thermo_
autoPtr< ODESolver > odeSolver_
scalarField Ttc_
Protected Attributes inherited from probes
bool loadFromFiles_
bool fixedLocations_
bool includeOutOfBounds_
bool verbose_
bool onExecute_
wordRes fieldSelection_
word samplePointScheme_
DynamicList< word > selectedFieldNames_
fieldGroup< volScalarField > scalarFields_
fieldGroup< volVectorField > vectorFields_
fieldGroup< volSphericalTensorField > sphericalTensorFields_
fieldGroup< volSymmTensorField > symmTensorFields_
fieldGroup< volTensorField > tensorFields_
fieldGroup< surfaceScalarField > surfaceScalarFields_
fieldGroup< surfaceVectorField > surfaceVectorFields_
fieldGroup< surfaceSphericalTensorField > surfaceSphericalTensorFields_
fieldGroup< surfaceSymmTensorField > surfaceSymmTensorFields_
fieldGroup< surfaceTensorField > surfaceTensorFields_
labelList elementList_
labelList faceList_
labelList processor_
HashPtrTable< OFstream > probeFilePtrs_
labelList patchIDList_
pointField oldPoints_
Protected Attributes inherited from fvMeshFunctionObject
const fvMesh & mesh_
Protected Attributes inherited from regionFunctionObject
word subRegistryName_
const objectRegistry & obr_
const objectRegistry * obrPtr_
Protected Attributes inherited from timeFunctionObject
const Time & time_
Additional Inherited Members
Public Types inherited from Field< vector >
typedef pTraits< vector >::cmptType cmptType
typedef SubField< vector > subField
Public Types inherited from List< T >
typedef SubList< T > subList
Public Types inherited from UList< T >
typedef T value_type
typedef T * pointer
typedef const T * const_pointer
typedef T & reference
typedef const T & const_reference
typedef T * iterator
typedef const T * const_iterator
typedef label size_type
typedef label difference_type
typedef std::reverse_iterator< iterator > reverse_iterator
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &runTime, const dictionary &dict)
Static Public Member Functions inherited from Field< vector >
static const Field< vector > & null ()
static autoPtr< Field< vector > > New (Istream &is)
static tmp< Field< vector > > NewCalculatedType (const Field< Type2 > &f)
Static Public Member Functions inherited from List< T >
static const List< T > & null ()
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
static constexpr label max_size () noexcept
Public Attributes inherited from functionObject
bool log
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
static bool defaultUseNamePrefix
static word outputPrefix
Static Public Attributes inherited from FieldBase
static const char *const typeName
static bool allowConstructFromLargerSize = false
Protected Types inherited from probes
enum sampleActionType : unsigned { ACTION_NONE = 0 , ACTION_WRITE = 0x1 , ACTION_STORE = 0x2 , ACTION_ALL = 0xF }
Protected Member Functions inherited from probes
virtual void findElements (const fvMesh &mesh)
label prepare (unsigned request)
template<class GeoField >
tmp< GeoField > getOrLoadField (const word &fieldName) const
template<class Type >
void storeResults (const word &fieldName, const Field< Type > &values)
Protected Member Functions inherited from fvMeshFunctionObject
fvMeshFunctionObject (const fvMeshFunctionObject &)=delete
void operator= (const fvMeshFunctionObject &)=delete
Protected Member Functions inherited from regionFunctionObject
virtual const objectRegistry & obr () const
template<class ObjectType >
bool foundObject (const word &fieldName) const
template<class ObjectType >
const ObjectType * cfindObject (const word &fieldName) const
template<class ObjectType >
const ObjectType * findObject (const word &fieldName) const
template<class ObjectType >
ObjectType * findObject (const word &fieldName)
template<class ObjectType >
ObjectType * getObjectPtr (const word &fieldName) const
template<class ObjectType >
const ObjectType & lookupObject (const word &fieldName) const
template<class ObjectType >
ObjectType & lookupObjectRef (const word &fieldName) const
template<class ObjectType >
bool store (word &fieldName, const tmp< ObjectType > &tfield, bool cacheable=false)
template<class ObjectType >
bool storeInDb (const word &fieldName, const tmp< ObjectType > &tfield, const objectRegistry &obr)
bool writeObject (const word &fieldName)
bool clearObject (const word &fieldName)
void clearObjects (const wordList &objNames)
regionFunctionObject (const regionFunctionObject &)=delete
void operator= (const regionFunctionObject &)=delete
Protected Member Functions inherited from stateFunctionObject
const functionObjects::properties & stateDict () const
functionObjects::properties & stateDict ()
stateFunctionObject (const stateFunctionObject &)=delete
void operator= (const stateFunctionObject &)=delete
Protected Member Functions inherited from timeFunctionObject
void clearOutputObjects (const wordList &objNames)
timeFunctionObject (const timeFunctionObject &)=delete
void operator= (const timeFunctionObject &)=delete
Protected Member Functions inherited from functionObject
word scopedName (const word &name) const
Protected Member Functions inherited from UList< T >
void setAddressableSize (const label n) noexcept
void size (const label n)
void writeEntry (Ostream &os) const
labelRange validateRange (const labelRange &requestedRange) const
UList< T > & operator= (const UList< T > &)=delete
void writeEntry (Ostream &os) const
void writeEntry (Ostream &os) const
Detailed Description
Sample probe for temperature using a thermocouple.
Uses the correlation:
Usage
Example of function object specification:
probes
{
    type            thermoCoupleProbes;
    libs            (utilityFunctionObjects);
    writeControl    timeStep;
    writeInterval   1;
    solver          rodas23;
    absTol          1e-12;
    relTol          1e-8;
    interpolationScheme cellPoint;
    // thermocouple properties
    rho             8908;
    Cp              440;
    d               1e-3;
    epsilon         0.85;
    radiationField  G;
    probeLocations
    (
        (0.5 0.5 0.5)
    );
    fields
    (
        T
    );
}
Source files
thermoCoupleProbes.H
thermoCoupleProbes.C
Definition at line 97 of file thermoCoupleProbes.H.
Constructor & Destructor Documentation
thermoCoupleProbes()
thermoCoupleProbes (const word & name, const Time & runTime, const dictionary & dict, const bool loadFromFiles = false, const bool readFields = true)
Definition at line 42 of file thermoCoupleProbes.C.
References dict, stateFunctionObject::getDict(), Foam::name(), ODESolver::New(), thermoCoupleProbes::odeSolver_, thermoCoupleProbes::read(), probes::sample(), thermoCoupleProbes::thermo_, thermoCoupleProbes::Ttc_, and FieldBase::typeName.
~thermoCoupleProbes()
virtual ~thermoCoupleProbes () virtual default
Member Function Documentation
TypeName()
TypeName ("thermoCoupleProbes")
nEqns()
Foam::label nEqns () const virtual
Implements ODESystem.
Definition at line 83 of file thermoCoupleProbes.C.
derivatives()
void derivatives (const scalar x, const scalarField & y, scalarField & dydx) const virtual
Implements ODESystem.
Definition at line 89 of file thermoCoupleProbes.C.
References Foam::max(), Foam::constant::mathematical::pi(), Foam::pow3(), Foam::pow4(), Pr(), Foam::Re(), probes::sample(), Foam::constant::physicoChemical::sigma, Foam::sqr(), Foam::sqrt(), y, and Foam::Zero.
jacobian()
void jacobian (const scalar t, const scalarField & y, scalarField & dfdt, scalarSquareMatrix & dfdy) const virtual
Implements ODESystem.
Definition at line 135 of file thermoCoupleProbes.C.
References n, x, and y.
read()
bool read (const dictionary & dict) virtual
Reimplemented from probes.
Definition at line 190 of file thermoCoupleProbes.C.
References dict, and probes::read().
Referenced by thermoCoupleProbes::thermoCoupleProbes().
execute()
bool execute () virtual
Reimplemented from probes.
Definition at line 176 of file thermoCoupleProbes.C.
References UList< T >::empty().
write()
bool write () virtual
Reimplemented from probes.
Definition at line 157 of file thermoCoupleProbes.C.
References UList< T >::empty().
Member Data Documentation
rho_
scalar rho_ protected
Definition at line 107 of file thermoCoupleProbes.H.
Cp_
scalar Cp_ protected
Definition at line 110 of file thermoCoupleProbes.H.
d_
scalar d_ protected
Definition at line 113 of file thermoCoupleProbes.H.
epsilon_
scalar epsilon_ protected
Definition at line 116 of file thermoCoupleProbes.H.
UName_
word UName_ protected
Definition at line 119 of file thermoCoupleProbes.H.
radiationFieldName_
word radiationFieldName_ protected
Definition at line 122 of file thermoCoupleProbes.H.
thermo_
const fluidThermo& thermo_ protected
Definition at line 125 of file thermoCoupleProbes.H.
Referenced by thermoCoupleProbes::thermoCoupleProbes().
odeSolver_
autoPtr<ODESolver> odeSolver_ protected
Definition at line 128 of file thermoCoupleProbes.H.
Referenced by thermoCoupleProbes::thermoCoupleProbes().
Ttc_
scalarField Ttc_ protected
Definition at line 131 of file thermoCoupleProbes.H.
Referenced by thermoCoupleProbes::thermoCoupleProbes().
The documentation for this class was generated from the following files:
src/functionObjects/utilities/thermoCoupleProbes/thermoCoupleProbes.H
src/functionObjects/utilities/thermoCoupleProbes/thermoCoupleProbes.C
src/functionObjects/utilities/thermoCoupleProbes/thermoCoupleProbesTemplates.C