OpenFOAM: transformBox Class Reference
transformBox Class Reference
Defines control points based on given lower and upper boundaries for the box and additional translation, rotation and scaling vectors. The latter can be copied over from the Paraview clip or transform filters, to facilitate the definition of a more general box.
#include <transformBox.H>
Public Member Functions
TypeName ("transformBox")
transformBox (NURBS3DVolume &box)
virtual ~transformBox ()=default
Public Member Functions inherited from controlPointsDefinition
TypeName ("controlPointsDefinition")
declareRunTimeSelectionTable (autoPtr, controlPointsDefinition, dictionary,(NURBS3DVolume &box),(box))
controlPointsDefinition (NURBS3DVolume &box)
virtual ~controlPointsDefinition ()=default
Protected Member Functions
virtual void computeControlPoints ()
Protected Member Functions inherited from controlPointsDefinition
void transformControlPoints (const vector &geometryMin, const vector &geometryMax)
Additional Inherited Members
Static Public Member Functions inherited from controlPointsDefinition
static autoPtr< controlPointsDefinition > New (NURBS3DVolume &box)
Protected Attributes inherited from controlPointsDefinition
NURBS3DVolume & box_
vectorField & cps_
Detailed Description
Defines control points based on given lower and upper boundaries for the box and additional translation, rotation and scaling vectors. The latter can be copied over from the Paraview clip or transform filters, to facilitate the definition of a more general box.
Source files
transformBox.H
transformBox.C
Definition at line 51 of file transformBox.H.
Constructor & Destructor Documentation
transformBox()
transformBox (NURBS3DVolume & box)
Definition at line 83 of file transformBox.C.
References transformBox::computeControlPoints().
~transformBox()
virtual ~transformBox () virtual default
Member Function Documentation
computeControlPoints()
void computeControlPoints () protected virtual
Implements controlPointsDefinition.
Definition at line 43 of file transformBox.C.
References NURBS3DVolume::basisU(), NURBS3DVolume::basisV(), NURBS3DVolume::basisW(), controlPointsDefinition::box_, controlPointsDefinition::cps_, dict, NURBS3DVolume::dict(), NURBS3DVolume::getCPID(), List< T >::setSize(), controlPointsDefinition::transformControlPoints(), and VectorSpace< Form, Cmpt, Ncmpts >::zero.
Referenced by transformBox::transformBox().
TypeName()
TypeName ("transformBox")
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/parameterization/NURBS/NURBS3DVolume/controlPointsDefinition/transformBox/transformBox.H
src/optimisation/adjointOptimisation/adjoint/parameterization/NURBS/NURBS3DVolume/controlPointsDefinition/transformBox/transformBox.C