OpenFOAM: DMDModel Class Reference
DMDModel Class Reference abstract
Abstract base class for DMD models to handle DMD characteristics for the DMD function object.
#include <DMDModel.H>
Public Member Functions
TypeName ("DMDModel")
declareRunTimeSelectionTable (autoPtr, DMDModel, dictionary,(const fvMesh &mesh, const word &name, const dictionary &dict),(mesh, name, dict))
DMDModel (const fvMesh &mesh, const word &name, const dictionary &dict)
DMDModel (const DMDModel &)=delete
void operator= (const DMDModel &)=delete
virtual ~DMDModel ()=default
virtual bool initialise (const RMatrix &snapshot)=0
virtual bool update (const RMatrix &snapshot)=0
virtual bool fit ()=0
virtual void reconstruct (const wordList modes)
virtual bool read (const dictionary &dict)=0
Public Member Functions inherited from writeFile
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name="undefined", const bool writeToFile=true)
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name, const dictionary &dict, const bool writeToFile=true)
writeFile (const writeFile &wf)
virtual ~writeFile ()=default
virtual OFstream & file ()
virtual bool writeToFile () const
virtual bool canWriteToFile () const
virtual bool canResetFile () const
virtual bool canWriteHeader () const
virtual label charWidth () const
virtual void writeCommented (Ostream &os, const string &str) const
virtual void writeTabbed (Ostream &os, const string &str) const
virtual void writeHeader (Ostream &os, const string &str) const
virtual void writeCurrentTime (Ostream &os) const
virtual void writeBreak (Ostream &os) const
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
template<class Type >
void writeValue (Ostream &os, const Type &val) const
Static Public Member Functions
static autoPtr< DMDModel > New (const fvMesh &mesh, const word &name, const dictionary &dict)
Protected Member Functions
virtual bool dynamics ()=0
virtual bool modes ()=0
Protected Member Functions inherited from writeFile
void initStream (Ostream &os) const
fileName baseFileDir () const
fileName baseTimeDir () const
fileName filePath (const fileName &fName) const
virtual autoPtr< OFstream > newFile (const fileName &fName) const
virtual autoPtr< OFstream > newFileAtTime (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > newFileAtStartTime (const word &name) const
virtual void resetFile (const word &name)
Omanip< int > valueWidth (const label offset=0) const
void operator= (const writeFile &)=delete
virtual autoPtr< OFstream > createFile (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > createFile (const word &name) const
Protected Attributes
const fvMesh & mesh_
const word name_
Protected Attributes inherited from writeFile
const objectRegistry & fileObr_
const fileName prefix_
word fileName_
autoPtr< OFstream > filePtr_
label writePrecision_
bool writeToFile_
bool updateHeader_
bool writtenHeader_
bool useUserTime_
scalar startTime_
Additional Inherited Members
Static Public Attributes inherited from writeFile
static label addChars = 8
Detailed Description
Abstract base class for DMD models to handle DMD characteristics for the DMD function object.
Source files
DMDModel.H
DMDModel.C
DMDModelNew.C
DMDModelTemplates.C
Definition at line 62 of file DMDModel.H.
Constructor & Destructor Documentation
DMDModel() [1/2]
DMDModel (const fvMesh & mesh, const word & name, const dictionary & dict)
Definition at line 34 of file DMDModel.C.
References Foam::name().
DMDModel() [2/2]
DMDModel (const DMDModel &) delete
~DMDModel()
virtual ~DMDModel () virtual default
Member Function Documentation
dynamics()
virtual bool dynamics () protected pure virtual
modes()
virtual bool modes () protected pure virtual
TypeName()
TypeName ("DMDModel")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , DMDModel , dictionary , (const fvMesh &mesh, const word &name, const dictionary &dict) , (mesh, name, dict))
New()
Foam::autoPtr< Foam::DMDModel > New (const fvMesh & mesh, const word & name, const dictionary & dict) static
Definition at line 25 of file DMDModelNew.C.
References dict, Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, mesh, and Foam::name().
operator=()
void operator= (const DMDModel &) delete
initialise()
virtual bool initialise (const RMatrix & snapshot) pure virtual
Implemented in STDMD.
update()
virtual bool update (const RMatrix & snapshot) pure virtual
Implemented in STDMD.
fit()
virtual bool fit () pure virtual
Implemented in STDMD.
reconstruct()
virtual void reconstruct (const wordList modes) inline virtual
Definition at line 162 of file DMDModel.H.
References NotImplemented.
read()
virtual bool read (const dictionary & dict) pure virtual
Reimplemented from writeFile.
Implemented in STDMD.
Member Data Documentation
mesh_
const fvMesh& mesh_ protected
Definition at line 75 of file DMDModel.H.
name_
const word name_ protected
Definition at line 78 of file DMDModel.H.
The documentation for this class was generated from the following files:
src/functionObjects/field/DMD/DMDModels/DMDModel/DMDModel.H
src/functionObjects/field/DMD/DMDModels/DMDModel/DMDModel.C
src/functionObjects/field/DMD/DMDModels/DMDModel/DMDModelNew.C