OpenFOAM: uniformBin Class Reference
uniformBin Class Reference
Calculates binned data in multiple segments according to a specified Cartesian or cylindrical coordinate system.
#include <uniformBin.H>
Public Member Functions
TypeName ("uniformBin")
uniformBin (const dictionary &dict, const fvMesh &mesh, const word &outputPrefix)
uniformBin (const uniformBin &)=delete
void operator= (const uniformBin &)=delete
virtual ~uniformBin ()=default
virtual bool read (const dictionary &dict)
virtual void apply ()
virtual void updateMesh (const mapPolyMesh &mpm)
virtual void movePoints (const polyMesh &mesh)
Public Member Functions inherited from binModel
TypeName ("binModel")
declareRunTimeSelectionTable (autoPtr, binModel, dictionary,(const dictionary &dict, const fvMesh &mesh, const word &outputPrefix),(dict, mesh, outputPrefix))
binModel (const dictionary &dict, const fvMesh &mesh, const word &outputPrefix)
binModel (const binModel &)=delete
void operator= (const binModel &)=delete
virtual ~binModel ()=default
label nBin () const noexcept
template<>
bool decomposePatchValues (List< List< vector > > &data, const label bini, const vector &v, const vector &n) const
template<>
bool decomposePatchValues (List< List< vector > > &data, const label bini, const vector &v, const vector &n) const
template<class Type >
Foam::string writeComponents (const word &stem) const
Public Member Functions inherited from writeFile
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name="undefined", const bool writeToFile=true)
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name, const dictionary &dict, const bool writeToFile=true)
writeFile (const writeFile &wf)
virtual ~writeFile ()=default
virtual OFstream & file ()
virtual bool writeToFile () const
virtual bool canWriteToFile () const
virtual bool canResetFile () const
virtual bool canWriteHeader () const
virtual label charWidth () const
virtual void writeCommented (Ostream &os, const string &str) const
virtual void writeTabbed (Ostream &os, const string &str) const
virtual void writeHeader (Ostream &os, const string &str) const
virtual void writeCurrentTime (Ostream &os) const
virtual void writeBreak (Ostream &os) const
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
template<class Type >
void writeValue (Ostream &os, const Type &val) const
Protected Member Functions
template<class Type >
void writeFileHeader (OFstream &os) const
virtual void initialise ()
virtual labelList binAddr (const vectorField &d) const
virtual void setBinsAddressing ()
template<class Type >
bool processField (const label fieldi)
Protected Member Functions inherited from binModel
void setCoordinateSystem (const dictionary &dict, const word &e3Name=word::null, const word &e1Name=word::null)
template<class Type >
bool decomposePatchValues (List< List< Type > > &data, const label bini, const Type &v, const vector &n) const
template<class Type >
string writeComponents (const word &stem) const
template<class Type >
void writeBinnedData (List< List< Type > > &data, Ostream &os) const
Protected Member Functions inherited from writeFile
void initStream (Ostream &os) const
fileName baseFileDir () const
fileName baseTimeDir () const
fileName filePath (const fileName &fName) const
virtual autoPtr< OFstream > newFile (const fileName &fName) const
virtual autoPtr< OFstream > newFileAtTime (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > newFileAtStartTime (const word &name) const
virtual void resetFile (const word &name)
Omanip< int > valueWidth (const label offset=0) const
void operator= (const writeFile &)=delete
virtual autoPtr< OFstream > createFile (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > createFile (const word &name) const
Protected Attributes
Vector< label > nBins_
vector binW_
Vector< vector2D > binMinMax_
labelList faceToBin_
labelList cellToBin_
Protected Attributes inherited from binModel
const fvMesh & mesh_
bool decomposePatchValues_
bool cumulative_
autoPtr< coordinateSystem > coordSysPtr_
label nBin_
labelHashSet patchSet_
wordList fieldNames_
labelList cellZoneIDs_
PtrList< OFstream > filePtrs_
Protected Attributes inherited from writeFile
const objectRegistry & fileObr_
const fileName prefix_
word fileName_
autoPtr< OFstream > filePtr_
label writePrecision_
bool writeToFile_
bool updateHeader_
bool writtenHeader_
bool useUserTime_
scalar startTime_
Additional Inherited Members
Static Public Member Functions inherited from binModel
static autoPtr< binModel > New (const dictionary &dict, const fvMesh &mesh, const word &outputPrefix)
Static Public Attributes inherited from writeFile
static label addChars = 8
Detailed Description
Calculates binned data in multiple segments according to a specified Cartesian or cylindrical coordinate system.
Usage
Minimal example by using system/controlDict.functions:
binField1
{
    // Other binField entries
    ...
    // Mandatory entries
    binModel          uniformBin;
    binData
    {
        // Mandatory entries
        nBin          <Vector<label>>;
        // Optional entries
        cumulative    <bool>;
        minMax
        {
            e1        (<scalar> <scalar>); // (min max);
            e2        (<scalar> <scalar>);
            e3        (<scalar> <scalar>);
        }
    }
}
where the entries mean:
Property Description Type Reqd Deflt
binModel Type name: uniformBin word yes -
binData Entries of the chosen bin model dict yes -
nBin Numbers of bins in specified directions
Vector<label>
yes -
cumulative
Flag to bin data accumulated with increasing distance
in binning direction
bool no false
minMax
Min-max bounds in binning directions with respect to
the coordinateSystem's origin
dict no -
Note
The order of bin numbering is (e1, e2, e3), where the first varies the fastest. For example, for a cylindrical bin with , the bin indices may look like as follows - note the counterclockwise increments:
                       |-------------------|
                       | 12 |         | 14 |
                            | 11 | 13 |
                            | 9  | 15 |
                       | 10 |         | 16 |
                       |-------------------|
                      /    /         /    /
                     /    /         /    /
                    |-------------------|
                    | 4  |         | 6  |
                         | 3  | 5  |
                         | 1  | 7  |
                    | 2  |         | 8  |
                    |-------------------|
Source files
uniformBin.H
uniformBin.C
uniformBinTemplates.C
Definition at line 157 of file uniformBin.H.
Constructor & Destructor Documentation
uniformBin() [1/2]
uniformBin (const dictionary & dict, const fvMesh & mesh, const word & outputPrefix)
Definition at line 189 of file uniformBin.C.
References dict, and uniformBin::read().
uniformBin() [2/2]
uniformBin (const uniformBin &) delete
~uniformBin()
virtual ~uniformBin () virtual default
Member Function Documentation
writeFileHeader()
template<class Type > void writeFileHeader (OFstream & os) const protected
Definition at line 24 of file uniformBinTemplates.C.
References uniformBin::binMinMax_, uniformBin::binW_, binModel::coordSysPtr_, binModel::decomposePatchValues_, Foam::endl(), Foam::name(), binModel::nBin_, uniformBin::nBins_, VectorSpace< Form, Cmpt, Ncmpts >::nComponents, Foam::nl, os(), R, Foam::tab, writeFile::writeCommented(), writeFile::writeHeader(), writeFile::writeHeaderValue(), and writeFile::writeTabbed().
initialise()
void initialise () protected virtual
Implements binModel.
Definition at line 37 of file uniformBin.C.
References uniformBin::binMinMax_, uniformBin::binW_, binModel::cellZoneIDs_, Field< Type >::component(), binModel::coordSysPtr_, Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::max(), binModel::mesh_, Foam::min(), uniformBin::nBins_, VectorSpace< Form, Cmpt, Ncmpts >::nComponents, Foam::nl, binModel::patchSet_, pbm, pp(), Foam::reduce(), and uniformBin::setBinsAddressing().
binAddr()
Foam::labelList binAddr (const vectorField & d) const protected virtual
Definition at line 113 of file uniformBin.C.
References forAll, Foam::max(), Foam::min(), n, VectorSpace< Form, Cmpt, Ncmpts >::nComponents, UList< T >::size(), and Foam::Zero.
setBinsAddressing()
void setBinsAddressing () protected virtual
Definition at line 153 of file uniformBin.C.
References polyPatch::boundaryMesh(), forAll, forAllIters, pp(), and PtrList< T >::setSize().
Referenced by uniformBin::initialise().
processField()
template<class Type > bool processField (const label fieldi) protected
Definition at line 81 of file uniformBinTemplates.C.
References polyPatch::boundaryMesh(), fld(), forAll, forAllIters, pp(), Foam::reduce(), PtrList< T >::setSize(), and Foam::Zero.
TypeName()
TypeName ("uniformBin")
operator=()
void operator= (const uniformBin &) delete
read()
bool read (const dictionary & dict) virtual
Reimplemented from binModel.
Definition at line 212 of file uniformBin.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, UPtrList< T >::get(), Foam::Info, n, Foam::name(), VectorSpace< Form, Cmpt, Ncmpts >::nComponents, Foam::nl, and binModel::read().
Referenced by uniformBin::uniformBin().
apply()
void apply () virtual
Implements binModel.
Definition at line 275 of file uniformBin.C.
References Foam::endl(), forAll, and WarningInFunction.
updateMesh()
void updateMesh (const mapPolyMesh & mpm) virtual
Reimplemented from binModel.
Definition at line 298 of file uniformBin.C.
movePoints()
void movePoints (const polyMesh & mesh) virtual
Reimplemented from binModel.
Definition at line 302 of file uniformBin.C.
Member Data Documentation
nBins_
Vector<label> nBins_ protected
Definition at line 166 of file uniformBin.H.
Referenced by uniformBin::initialise(), and uniformBin::writeFileHeader().
binW_
vector binW_ protected
Definition at line 169 of file uniformBin.H.
Referenced by uniformBin::initialise(), and uniformBin::writeFileHeader().
binMinMax_
Vector<vector2D> binMinMax_ protected
Definition at line 172 of file uniformBin.H.
Referenced by uniformBin::initialise(), and uniformBin::writeFileHeader().
faceToBin_
labelList faceToBin_ protected
Definition at line 175 of file uniformBin.H.
cellToBin_
labelList cellToBin_ protected
Definition at line 178 of file uniformBin.H.
The documentation for this class was generated from the following files:
src/functionObjects/field/binField/binModels/uniformBin/uniformBin.H
src/functionObjects/field/binField/binModels/uniformBin/uniformBin.C
src/functionObjects/field/binField/binModels/uniformBin/uniformBinTemplates.C