OpenFOAM: pressurePermeableAlphaInletOutletVelocityFvPatchVectorField Class Reference
pressurePermeableAlphaInletOutletVelocityFvPatchVectorField Class Reference
Boundary conditions » Inlet | Boundary conditions » Outlet
The pressurePermeableAlphaInletOutletVelocity is a velocity inlet-outlet boundary condition which can be applied to velocity boundaries for multiphase flows when the pressure boundary condition is specified.
#include <pressurePermeableAlphaInletOutletVelocityFvPatchVectorField.H>
Public Member Functions
TypeName ("permeableAlphaPressureInletOutletVelocity")
pressurePermeableAlphaInletOutletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
pressurePermeableAlphaInletOutletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
pressurePermeableAlphaInletOutletVelocityFvPatchVectorField (const pressurePermeableAlphaInletOutletVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
pressurePermeableAlphaInletOutletVelocityFvPatchVectorField (const pressurePermeableAlphaInletOutletVelocityFvPatchVectorField &)
virtual tmp< fvPatchVectorField > clone () const
pressurePermeableAlphaInletOutletVelocityFvPatchVectorField (const pressurePermeableAlphaInletOutletVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
virtual bool assignable () const
const word & rhoName () const noexcept
word & rhoName ()
const word & phiName () const noexcept
word & phiName ()
virtual void updateCoeffs ()
virtual void write (Ostream &) const
virtual void operator= (const fvPatchField< vector > &pvf)
Detailed Description
The pressurePermeableAlphaInletOutletVelocity is a velocity inlet-outlet boundary condition which can be applied to velocity boundaries for multiphase flows when the pressure boundary condition is specified.
In the pressurePermeableAlphaInletOutletVelocity, an open condition is applied when alpha is under a user-defined alphaMin value and a wall condition is applied when alpha is larger than the alphaMin.
This boundary condition can be used in conjunction with prghPermeableAlphaTotalPressure for the p_rgh variable.
Usage
Example of the boundary condition specification:
<patchName>
{
    // Mandatory entries
    type            pressurePermeableAlphaInletOutletVelocity;
    // Optional entries
    phi             phi;
    rho             rho;
    alpha           alpha.water;
    alphaMin        0.01;
    // Inherited entries
    value           uniform (0 0 0);
    ...
}
where the entries mean:
Property Description Type Reqd Deflt
phi Name of flux field word no phi
rho Name of density field word no rho
alpha Name of mixture field word no none
alphaMin Minimum alpha scalar no 1
The inherited entries are elaborated in:
mixedFvPatchFields.H
See also
Foam::prghPermeableAlphaTotalPressureFvPatchScalarField
Foam::mixedFvPatchVectorField
Source files
pressurePermeableAlphaInletOutletVelocityFvPatchVectorField.H
pressurePermeableAlphaInletOutletVelocityFvPatchVectorField.C
Definition at line 125 of file pressurePermeableAlphaInletOutletVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
pressurePermeableAlphaInletOutletVelocityFvPatchVectorField() [1/5]
pressurePermeableAlphaInletOutletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Definition at line 29 of file pressurePermeableAlphaInletOutletVelocityFvPatchVectorField.C.
References Foam::Zero.
pressurePermeableAlphaInletOutletVelocityFvPatchVectorField() [2/5]
pressurePermeableAlphaInletOutletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Definition at line 65 of file pressurePermeableAlphaInletOutletVelocityFvPatchVectorField.C.
References dict, IOobjectOption::MUST_READ, fvPatchFieldBase::readDict(), and Foam::Zero.
pressurePermeableAlphaInletOutletVelocityFvPatchVectorField() [3/5]
pressurePermeableAlphaInletOutletVelocityFvPatchVectorField (const pressurePermeableAlphaInletOutletVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 48 of file pressurePermeableAlphaInletOutletVelocityFvPatchVectorField.C.
pressurePermeableAlphaInletOutletVelocityFvPatchVectorField() [4/5]
pressurePermeableAlphaInletOutletVelocityFvPatchVectorField (const pressurePermeableAlphaInletOutletVelocityFvPatchVectorField & pivpvf)
Definition at line 87 of file pressurePermeableAlphaInletOutletVelocityFvPatchVectorField.C.
pressurePermeableAlphaInletOutletVelocityFvPatchVectorField() [5/5]
pressurePermeableAlphaInletOutletVelocityFvPatchVectorField (const pressurePermeableAlphaInletOutletVelocityFvPatchVectorField & pivpvf, const DimensionedField< vector, volMesh > & iF)
Definition at line 101 of file pressurePermeableAlphaInletOutletVelocityFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("permeableAlphaPressureInletOutletVelocity")
clone() [1/2]
virtual tmp< fvPatchVectorField > clone () const inline virtual
Definition at line 185 of file pressurePermeableAlphaInletOutletVelocityFvPatchVectorField.H.
clone() [2/2]
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Definition at line 204 of file pressurePermeableAlphaInletOutletVelocityFvPatchVectorField.H.
assignable()
virtual bool assignable () const inline virtual
Definition at line 223 of file pressurePermeableAlphaInletOutletVelocityFvPatchVectorField.H.
rhoName() [1/2]
const word & rhoName () const inline noexcept
Definition at line 229 of file pressurePermeableAlphaInletOutletVelocityFvPatchVectorField.H.
rhoName() [2/2]
word & rhoName () inline
Definition at line 235 of file pressurePermeableAlphaInletOutletVelocityFvPatchVectorField.H.
phiName() [1/2]
const word & phiName () const inline noexcept
Definition at line 241 of file pressurePermeableAlphaInletOutletVelocityFvPatchVectorField.H.
phiName() [2/2]
word & phiName () inline
Definition at line 247 of file pressurePermeableAlphaInletOutletVelocityFvPatchVectorField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 119 of file pressurePermeableAlphaInletOutletVelocityFvPatchVectorField.C.
References Foam::dimMass, Foam::dimTime, Foam::dimVolume, Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::max(), n, Foam::neg(), Foam::pos(), and Foam::Zero.
write()
void write (Ostream & os) const virtual
Definition at line 173 of file pressurePermeableAlphaInletOutletVelocityFvPatchVectorField.C.
References os(), mixedFvPatchField< Type >::write(), and Ostream::writeEntryIfDifferent().
operator=()
void operator= (const fvPatchField< vector > & pvf) virtual
Definition at line 188 of file pressurePermeableAlphaInletOutletVelocityFvPatchVectorField.C.
References Foam::lerp(), and n.
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/pressurePermeableAlphaInletOutletVelocity/pressurePermeableAlphaInletOutletVelocityFvPatchVectorField.H
src/finiteVolume/fields/fvPatchFields/derived/pressurePermeableAlphaInletOutletVelocity/pressurePermeableAlphaInletOutletVelocityFvPatchVectorField.C