OpenFOAM: cyclicAMIPointPatchField< Type > Class Template Reference
cyclicAMIPointPatchField< Type > Class Template Reference
Cyclic AMI front and back plane patch field.
#include <cyclicAMIPointPatchField.H>
Public Member Functions
TypeName (cyclicAMIPointPatch::typeName_())
cyclicAMIPointPatchField (const pointPatch &, const DimensionedField< Type, pointMesh > &)
cyclicAMIPointPatchField (const pointPatch &, const DimensionedField< Type, pointMesh > &, const dictionary &)
cyclicAMIPointPatchField (const cyclicAMIPointPatchField< Type > &, const pointPatch &, const DimensionedField< Type, pointMesh > &, const pointPatchFieldMapper &)
virtual autoPtr< pointPatchField< Type > > clone () const
cyclicAMIPointPatchField (const cyclicAMIPointPatchField< Type > &, const DimensionedField< Type, pointMesh > &)
virtual autoPtr< pointPatchField< Type > > clone (const DimensionedField< Type, pointMesh > &iF) const
virtual const word & constraintType () const
virtual bool doTransform () const
virtual const tensorField & forwardT () const
virtual const tensorField & reverseT () const
virtual bool coupled () const
virtual void evaluate (const Pstream::commsTypes commsType=Pstream::commsTypes::blocking)
virtual void swapAddSeparated (const Pstream::commsTypes commsType, Field< Type > &) const
Public Member Functions inherited from coupledPointPatchField< Type >
TypeName (coupledPointPatch::typeName_())
coupledPointPatchField (const pointPatch &, const DimensionedField< Type, pointMesh > &)
coupledPointPatchField (const pointPatch &, const DimensionedField< Type, pointMesh > &, const dictionary &dict)
coupledPointPatchField (const coupledPointPatchField< Type > &, const pointPatch &, const DimensionedField< Type, pointMesh > &, const pointPatchFieldMapper &)
coupledPointPatchField (const coupledPointPatchField< Type > &, const DimensionedField< Type, pointMesh > &)
virtual void initSwapAddSeparated (const Pstream::commsTypes, Field< Type > &) const
Public Member Functions inherited from pointPatchField< Type >
declareRunTimeSelectionTable (autoPtr, pointPatchField, patch,(const pointPatch &p, const DimensionedField< Type, pointMesh > &iF),(p, iF))
declareRunTimeSelectionTable (autoPtr, pointPatchField, patchMapper,(const pointPatchField< Type > &ptf, const pointPatch &p, const DimensionedField< Type, pointMesh > &iF, const pointPatchFieldMapper &m),(dynamic_cast< const pointPatchFieldType & >(ptf), p, iF, m))
declareRunTimeSelectionTable (autoPtr, pointPatchField, dictionary,(const pointPatch &p, const DimensionedField< Type, pointMesh > &iF, const dictionary &dict),(p, iF, dict))
pointPatchField (const pointPatch &, const DimensionedField< Type, pointMesh > &)
pointPatchField (const pointPatch &, const DimensionedField< Type, pointMesh > &, const dictionary &)
pointPatchField (const pointPatchField< Type > &, const pointPatch &, const DimensionedField< Type, pointMesh > &, const pointPatchFieldMapper &)
pointPatchField (const pointPatchField< Type > &)
pointPatchField (const pointPatchField< Type > &, const DimensionedField< Type, pointMesh > &)
virtual ~pointPatchField ()=default
label size () const
const DimensionedField< Type, pointMesh > & internalField () const noexcept
const Field< Type > & primitiveField () const noexcept
tmp< Field< Type > > patchInternalField () const
template<class Type1 >
tmp< Field< Type1 > > patchInternalField (const Field< Type1 > &iF) const
template<class Type1 >
tmp< Field< Type1 > > patchInternalField (const Field< Type1 > &iF, const labelUList &meshPoints) const
template<class Type1 >
void addToInternalField (Field< Type1 > &iF, const Field< Type1 > &pF) const
template<class Type1 >
void addToInternalField (Field< Type1 > &iF, const Field< Type1 > &pF, const labelUList &points) const
template<class Type1 >
void setInInternalField (Field< Type1 > &iF, const Field< Type1 > &pF, const labelUList &meshPoints) const
template<class Type1 >
void setInInternalField (Field< Type1 > &iF, const Field< Type1 > &pF) const
virtual void autoMap (const pointPatchFieldMapper &)
virtual void rmap (const pointPatchField< Type > &, const labelList &)
virtual void updateCoeffs ()
virtual void initEvaluate (const Pstream::commsTypes commsType=Pstream::commsTypes::blocking)
virtual void write (Ostream &os) const
virtual void operator= (const pointPatchField< Type > &)
virtual void operator+= (const pointPatchField< Type > &)
virtual void operator-= (const pointPatchField< Type > &)
virtual void operator*= (const pointPatchField< scalar > &)
virtual void operator/= (const pointPatchField< scalar > &)
virtual void operator= (const Field< Type > &)
virtual void operator+= (const Field< Type > &)
virtual void operator-= (const Field< Type > &)
virtual void operator*= (const Field< scalar > &)
virtual void operator/= (const Field< scalar > &)
virtual void operator= (const Type &)
virtual void operator+= (const Type &)
virtual void operator-= (const Type &)
virtual void operator*= (const scalar)
virtual void operator/= (const scalar)
virtual void operator== (const pointPatchField< Type > &)
virtual void operator== (const Field< Type > &)
virtual void operator== (const Type &)
void negate ()
void normalise ()
template<class Type2 >
Foam::autoPtr< Foam::pointPatchField< Type > > NewCalculatedType (const pointPatchField< Type2 > &pf)
template<class Type1 >
Foam::tmp< Foam::Field< Type1 > > patchInternalField (const Field< Type1 > &iF, const labelUList &meshPoints) const
template<class Type1 >
Foam::tmp< Foam::Field< Type1 > > patchInternalField (const Field< Type1 > &iF) const
Public Member Functions inherited from pointPatchFieldBase
TypeName ("pointPatchField")
pointPatchFieldBase (const pointPatch &p)
pointPatchFieldBase (const pointPatch &p, const word &patchType)
pointPatchFieldBase (const pointPatch &p, const dictionary &dict)
pointPatchFieldBase (const pointPatchFieldBase &, const pointPatch &p)
pointPatchFieldBase (const pointPatchFieldBase &)
virtual ~pointPatchFieldBase ()=default
virtual bool fixesValue () const
const objectRegistry & db () const
const pointPatch & patch () const noexcept
const word & patchType () const noexcept
word & patchType () noexcept
bool updated () const noexcept
bool manipulatedMatrix () const noexcept
void checkPatch (const pointPatchFieldBase &rhs) const
Additional Inherited Members
Public Types inherited from pointPatchField< Type >
typedef Type value_type
typedef DimensionedField< Type, pointMesh > Internal
typedef pointPatch Patch
typedef calculatedPointPatchField< Type > Calculated
Static Public Member Functions inherited from pointPatchField< Type >
static autoPtr< pointPatchField< Type > > New (const word &patchFieldType, const pointPatch &p, const DimensionedField< Type, pointMesh > &iF)
static autoPtr< pointPatchField< Type > > New (const word &patchFieldType, const word &actualPatchType, const pointPatch &p, const DimensionedField< Type, pointMesh > &iF)
static autoPtr< pointPatchField< Type > > New (const pointPatchField< Type > &, const pointPatch &, const DimensionedField< Type, pointMesh > &, const pointPatchFieldMapper &)
static autoPtr< pointPatchField< Type > > New (const pointPatch &, const DimensionedField< Type, pointMesh > &, const dictionary &)
template<class Type2 >
static autoPtr< pointPatchField< Type > > NewCalculatedType (const pointPatchField< Type2 > &)
Static Public Member Functions inherited from pointPatchFieldBase
static const word & emptyType () noexcept
static const word & calculatedType () noexcept
static const word & zeroGradientType () noexcept
Static Public Attributes inherited from pointPatchFieldBase
static int disallowGenericPatchField
Protected Member Functions inherited from pointPatchFieldBase
virtual void readDict (const dictionary &dict)
void setUpdated (bool state) noexcept
void setManipulated (bool state) noexcept
Detailed Description
template<class Type>
class Foam::cyclicAMIPointPatchField< Type >
Cyclic AMI front and back plane patch field.
Source files
cyclicAMIPointPatchField.H
cyclicAMIPointPatchField.C
Definition at line 50 of file cyclicAMIPointPatchField.H.
Constructor & Destructor Documentation
cyclicAMIPointPatchField() [1/4]
template<class Type > cyclicAMIPointPatchField (const pointPatch & p, const DimensionedField< Type, pointMesh > & iF)
Definition at line 28 of file cyclicAMIPointPatchField.C.
References Foam::refCast().
cyclicAMIPointPatchField() [2/4]
template<class Type > cyclicAMIPointPatchField (const pointPatch & p, const DimensionedField< Type, pointMesh > & iF, const dictionary & dict)
Definition at line 42 of file cyclicAMIPointPatchField.C.
References dict, Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, p, and pointPatchFieldBase::patch().
cyclicAMIPointPatchField() [3/4]
template<class Type > cyclicAMIPointPatchField (const cyclicAMIPointPatchField< Type > & ptf, const pointPatch & p, const DimensionedField< Type, pointMesh > & iF, const pointPatchFieldMapper & mapper)
Definition at line 65 of file cyclicAMIPointPatchField.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, and pointPatchFieldBase::patch().
cyclicAMIPointPatchField() [4/4]
template<class Type > cyclicAMIPointPatchField (const cyclicAMIPointPatchField< Type > & ptf, const DimensionedField< Type, pointMesh > & iF)
Definition at line 91 of file cyclicAMIPointPatchField.C.
Member Function Documentation
TypeName()
template<class Type > TypeName (cyclicAMIPointPatch::typeName_())
clone() [1/2]
template<class Type > virtual autoPtr< pointPatchField< Type > > clone () const inline virtual
Implements coupledPointPatchField< Type >.
Definition at line 137 of file cyclicAMIPointPatchField.H.
clone() [2/2]
template<class Type > virtual autoPtr< pointPatchField< Type > > clone (const DimensionedField< Type, pointMesh > & iF) const inline virtual
Implements coupledPointPatchField< Type >.
Definition at line 156 of file cyclicAMIPointPatchField.H.
constraintType()
template<class Type > virtual const word & constraintType () const inline virtual
Reimplemented from pointPatchFieldBase.
Definition at line 176 of file cyclicAMIPointPatchField.H.
doTransform()
template<class Type > virtual bool doTransform () const inline virtual
Definition at line 185 of file cyclicAMIPointPatchField.H.
References cyclicAMIPointPatch::parallel().
forwardT()
template<class Type > virtual const tensorField & forwardT () const inline virtual
Definition at line 191 of file cyclicAMIPointPatchField.H.
References cyclicAMIPointPatch::forwardT().
reverseT()
template<class Type > virtual const tensorField & reverseT () const inline virtual
Definition at line 197 of file cyclicAMIPointPatchField.H.
References cyclicAMIPointPatch::reverseT().
coupled()
template<class Type > bool coupled () const virtual
Reimplemented from coupledPointPatchField< Type >.
Definition at line 107 of file cyclicAMIPointPatchField.C.
evaluate()
template<class Type > virtual void evaluate (const Pstream::commsTypes commsType = Pstream::commsTypes::blocking) inline virtual
Implements coupledPointPatchField< Type >.
Definition at line 210 of file cyclicAMIPointPatchField.H.
swapAddSeparated()
template<class Type > void swapAddSeparated (const Pstream::commsTypes commsType, Field< Type > & pField) const virtual
Implements coupledPointPatchField< Type >.
Definition at line 114 of file cyclicAMIPointPatchField.C.
References fld(), and Foam::transform().
The documentation for this class was generated from the following files:
src/meshTools/AMIInterpolation/patches/cyclicAMI/cyclicAMIPointPatchField/cyclicAMIPointPatchField.H
src/meshTools/AMIInterpolation/patches/cyclicAMI/cyclicAMIPointPatchField/cyclicAMIPointPatchField.C