OpenFOAM: DistortedSphereDragForce< CloudType > Class Template Reference
DistortedSphereDragForce< CloudType > Class Template Reference
Lagrangian particle models » Submodels » Kinematic » Forces
Particle-drag model wherein drag forces (per unit carrier-fluid velocity) are dynamically computed by using sphereDrag model; however, are corrected for particle distortion by linearly varying the drag between of a sphere (i.e. sphereDrag) and a value of 1.54 corresponding to a disk.
#include <DistortedSphereDragForce.H>
Public Member Functions
TypeName ("distortedSphereDrag")
DistortedSphereDragForce (CloudType &owner, const fvMesh &mesh, const dictionary &dict)
DistortedSphereDragForce (const DistortedSphereDragForce< CloudType > &df)
virtual autoPtr< ParticleForce< CloudType > > clone () const
void operator= (const DistortedSphereDragForce< CloudType > &)=delete
virtual ~DistortedSphereDragForce ()=default
virtual forceSuSp calcCoupled (const typename CloudType::parcelType &p, const typename CloudType::parcelType::trackingData &td, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const
Public Member Functions inherited from ParticleForce< CloudType >
TypeName ("particleForce")
declareRunTimeSelectionTable (autoPtr, ParticleForce, dictionary,(CloudType &owner, const fvMesh &mesh, const dictionary &dict),(owner, mesh, dict))
ParticleForce (CloudType &owner, const fvMesh &mesh, const dictionary &dict, const word &forceType, const bool readCoeffs)
ParticleForce (const ParticleForce &pf)
virtual ~ParticleForce ()
const CloudType & owner () const
CloudType & owner ()
const fvMesh & mesh () const
const dictionary & coeffs () const
virtual void cacheFields (const bool store)
virtual forceSuSp calcNonCoupled (const typename CloudType::parcelType &p, const typename CloudType::parcelType::trackingData &td, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const
virtual scalar massAdd (const typename CloudType::parcelType &p, const typename CloudType::parcelType::trackingData &td, const scalar mass) const
Additional Inherited Members
Public Types inherited from ParticleForce< CloudType >
typedef VectorSpace< Vector< vector >, vector, 2 > returnType
Static Public Member Functions inherited from ParticleForce< CloudType >
static autoPtr< ParticleForce< CloudType > > New (CloudType &owner, const fvMesh &mesh, const dictionary &dict, const word &forceType)
Detailed Description
template<class CloudType>
class Foam::DistortedSphereDragForce< CloudType >
Particle-drag model wherein drag forces (per unit carrier-fluid velocity) are dynamically computed by using sphereDrag model; however, are corrected for particle distortion by linearly varying the drag between of a sphere (i.e. sphereDrag) and a value of 1.54 corresponding to a disk.
with
where
= Drag force per carrier-fluid velocity [kg/s]
= Particle drag coefficient
= Sphere drag coefficient
= Particle Reynolds number
= Particle mass density
= Particle diameter
= Level of distortion determined by other models internally
Constraints:
Applicable to particles with a spatially homogeneous distribution.
References:
        Standard model:
            Putnam, A. (1961).
            Integratable form of droplet drag coefficient.
            ARS Journal, 31(10), 1467-1468.
        Standard model (tag:AOB):
            Amsden, A. A., O'Rourke, P. J., & Butler, T. D. (1989).
            KIVA-II: A computer program for chemically
            reactive flows with sprays (No. LA-11560-MS).
            Los Alamos National Lab.(LANL), Los Alamos, NM (United States).
            DOI:10.2172/6228444
        Expression correcting drag for particle distortion (tag:LMR):
            Liu, A. B., Mather, D., & Reitz, R. D. (1993).
            Modeling the effects of drop drag
            and breakup on fuel sprays.
            SAE Transactions, 83-95.
            DOI:10.4271/930072
Usage
Minimal example by using constant/<CloudProperties>:
subModels
{
    particleForces
    {
        distortedSphereDrag;
    }
}
where the entries mean:
Property Description Type Reqd Deflt
type Type name: distortedSphereDrag word yes -
Note
is weighted with the particle mass at the stage of a function return, so that it can later be normalised with the effective mass, if necessary (e.g. when using virtual-mass forces).
See also
Foam::SphereDragForce
Source files
DistortedSphereDragForce.H
DistortedSphereDragForce.C
Definition at line 168 of file DistortedSphereDragForce.H.
Constructor & Destructor Documentation
DistortedSphereDragForce() [1/2]
template<class CloudType > DistortedSphereDragForce (CloudType & owner, const fvMesh & mesh, const dictionary & dict)
Definition at line 45 of file DistortedSphereDragForce.C.
DistortedSphereDragForce() [2/2]
template<class CloudType > DistortedSphereDragForce (const DistortedSphereDragForce< CloudType > & df)
Definition at line 57 of file DistortedSphereDragForce.C.
~DistortedSphereDragForce()
template<class CloudType > virtual ~DistortedSphereDragForce () virtual default
Member Function Documentation
TypeName()
template<class CloudType > TypeName ("distortedSphereDrag")
clone()
template<class CloudType > virtual autoPtr< ParticleForce< CloudType > > clone () const inline virtual
Reimplemented from ParticleForce< CloudType >.
Definition at line 198 of file DistortedSphereDragForce.H.
operator=()
template<class CloudType > void operator= (const DistortedSphereDragForce< CloudType > &) delete
calcCoupled()
template<class CloudType > Foam::forceSuSp calcCoupled (const typename CloudType::parcelType & p, const typename CloudType::parcelType::trackingData & td, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const virtual
Reimplemented from ParticleForce< CloudType >.
Definition at line 69 of file DistortedSphereDragForce.C.
References Foam::clamp(), p, Foam::Re(), Foam::sqr(), y, and Foam::Zero.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/Kinematic/ParticleForces/Drag/DistortedSphereDrag/DistortedSphereDragForce.H
src/lagrangian/intermediate/submodels/Kinematic/ParticleForces/Drag/DistortedSphereDrag/DistortedSphereDragForce.C