OpenFOAM: projectEdge Class Reference
projectEdge Class Reference
Defines the edge from the projection onto a surface (single surface) or intersection of two surfaces.
#include <projectEdge.H>
Public Member Functions
TypeName ("project")
projectEdge (const dictionary &dict, const label index, const searchableSurfaces &geometry, const pointField &points, Istream &is)
virtual ~projectEdge ()=default
virtual point position (const scalar) const
virtual tmp< pointField > position (const scalarList &) const
virtual scalar length () const
Public Member Functions inherited from blockEdge
TypeName ("blockEdge")
declareRunTimeSelectionTable (autoPtr, blockEdge, Istream,(const dictionary &dict, const label index, const searchableSurfaces &geometry, const pointField &points, Istream &is),(dict, index, geometry, points, is))
blockEdge (const pointField &points, const edge &fromTo)
blockEdge (const dictionary &dict, const label index, const pointField &points, Istream &is)
virtual autoPtr< blockEdge > clone () const
virtual ~blockEdge ()=default
bool valid () const noexcept
label start () const noexcept
label end () const noexcept
const point & firstPoint () const
const point & lastPoint () const
int compare (const blockEdge &e) const
int compare (const edge &e) const
int compare (const label start, const label end) const
point linearPosition (const scalar lambda) const
void write (Ostream &os, const dictionary &dict) const
Additional Inherited Members
Static Public Member Functions inherited from blockEdge
static autoPtr< blockEdge > New (const dictionary &dict, const label index, const searchableSurfaces &geometry, const pointField &points, Istream &is)
Protected Member Functions inherited from blockEdge
blockEdge (const pointField &points, const label from, const label to)
Static Protected Member Functions inherited from blockEdge
static pointField appendEndPoints (const pointField &p, const label from, const label to, const pointField &intermediate)
Protected Attributes inherited from blockEdge
const pointField & points_
const label start_
const label end_
Detailed Description
Defines the edge from the projection onto a surface (single surface) or intersection of two surfaces.
Source files
projectEdge.H
projectEdge.C
Definition at line 54 of file projectEdge.H.
Constructor & Destructor Documentation
projectEdge()
projectEdge (const dictionary & dict, const label index, const searchableSurfaces & geometry, const pointField & points, Istream & is)
Parameters
points Referenced point field
Definition at line 78 of file projectEdge.C.
References Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, forAll, List< T >::resize(), and UList< T >::size().
~projectEdge()
virtual ~projectEdge () virtual default
Member Function Documentation
TypeName()
TypeName ("project")
position() [1/2]
Foam::point position (const scalar lambda) const virtual
Implements blockEdge.
Definition at line 108 of file projectEdge.C.
References lambda(), and blockEdge::linearPosition().
position() [2/2]
Foam::tmp< Foam::pointField > position (const scalarList & lambdas) const virtual
Reimplemented from blockEdge.
Definition at line 126 of file projectEdge.C.
References e, Foam::endl(), searchableSurfacesQueries::findNearest(), forAll, Foam::Info, UPtrList< T >::last(), blockEdge::linearPosition(), Foam::mag(), Foam::magSqr(), Foam::name(), tmp< T >::New(), points, Foam::Pout, UPtrList< T >::size(), UList< T >::size(), Foam::sum(), linearInterpolationWeights::valueWeights(), and Foam::Zero.
length()
Foam::scalar length () const virtual
Implements blockEdge.
Definition at line 266 of file projectEdge.C.
References NotImplemented.
The documentation for this class was generated from the following files:
src/mesh/blockMesh/blockEdges/projectEdge/projectEdge.H
src/mesh/blockMesh/blockEdges/projectEdge/projectEdge.C