OpenFOAM: patchInjectionBase Class Reference
patchInjectionBase Class Reference
#include <patchInjectionBase.H>
Public Member Functions
patchInjectionBase (const polyMesh &mesh, const word &patchName)
patchInjectionBase (const patchInjectionBase &pib)
virtual ~patchInjectionBase ()=default
virtual void updateMesh (const polyMesh &mesh)
label setPositionAndCell (const fvMesh &mesh, const scalar fraction01, Random &rnd, vector &position, label &cellOwner, label &tetFacei, label &tetPti)
virtual label setPositionAndCell (const fvMesh &mesh, Random &rnd, vector &position, label &cellOwner, label &tetFacei, label &tetPti)
label whichProc (const scalar fraction01) const
Protected Attributes
const word patchName_
const label patchId_
scalar patchArea_
vectorList patchNormal_
labelList cellOwners_
faceList triFace_
labelList triToFace_
scalarList triCumulativeMagSf_
scalarList sumTriMagSf_
Detailed Description
Definition at line 60 of file patchInjectionBase.H.
Constructor & Destructor Documentation
patchInjectionBase() [1/2]
patchInjectionBase (const polyMesh & mesh, const word & patchName)
Definition at line 31 of file patchInjectionBase.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, mesh, Foam::nl, patchInjectionBase::patchId_, patchInjectionBase::patchName_, and patchInjectionBase::updateMesh().
patchInjectionBase() [2/2]
patchInjectionBase (const patchInjectionBase & pib)
Definition at line 59 of file patchInjectionBase.C.
~patchInjectionBase()
virtual ~patchInjectionBase () virtual default
Member Function Documentation
updateMesh()
void updateMesh (const polyMesh & mesh) virtual
Reimplemented in PatchFlowRateInjection< CloudType >, and PatchInjection< CloudType >.
Definition at line 75 of file patchInjectionBase.C.
References PtrList< T >::append(), polyMesh::boundaryMesh(), PtrList< T >::clear(), f(), forAll, Pstream::listCombineReduce(), Foam::mag(), mesh, UPstream::myProcNo(), points, UPtrList< T >::size(), Foam::sum(), and Foam::Zero.
Referenced by PatchFlowRateInjection< CloudType >::PatchFlowRateInjection(), PatchInjection< CloudType >::PatchInjection(), patchInjectionBase::patchInjectionBase(), PatchFlowRateInjection< CloudType >::updateMesh(), and PatchInjection< CloudType >::updateMesh().
setPositionAndCell() [1/2]
Foam::label setPositionAndCell (const fvMesh & mesh, const scalar fraction01, Random & rnd, vector & position, label & cellOwner, label & tetFacei, label & tetPti)
Definition at line 135 of file patchInjectionBase.C.
References polyMesh::boundaryMesh(), primitiveMesh::cellCentres(), polyMeshTetDecomposition::cellTetIndices(), polyMesh::findCellFacePt(), polyMesh::findTetFacePt(), forAll, forAllReverse, UPtrList< T >::last(), Foam::mag(), mesh, UPstream::myProcNo(), points, triangle< Point, PointRef >::randomPoint(), UPtrList< T >::size(), fvMesh::V(), and Foam::Zero.
Referenced by PatchFlowRateInjection< CloudType >::setPositionAndCell(), and PatchInjection< CloudType >::setPositionAndCell().
setPositionAndCell() [2/2]
Foam::label setPositionAndCell (const fvMesh & mesh, Random & rnd, vector & position, label & cellOwner, label & tetFacei, label & tetPti) virtual
Reimplemented in PatchFlowRateInjection< CloudType >, and PatchInjection< CloudType >.
Definition at line 259 of file patchInjectionBase.C.
References mesh.
whichProc()
Foam::label whichProc (const scalar fraction01) const
Definition at line 284 of file patchInjectionBase.C.
References forAllReverse.
Member Data Documentation
patchName_
const word patchName_ protected
Definition at line 67 of file patchInjectionBase.H.
Referenced by patchInjectionBase::patchInjectionBase().
patchId_
const label patchId_ protected
Definition at line 70 of file patchInjectionBase.H.
Referenced by patchInjectionBase::patchInjectionBase().
patchArea_
scalar patchArea_ protected
Definition at line 73 of file patchInjectionBase.H.
patchNormal_
vectorList patchNormal_ protected
Definition at line 76 of file patchInjectionBase.H.
cellOwners_
labelList cellOwners_ protected
Definition at line 79 of file patchInjectionBase.H.
triFace_
faceList triFace_ protected
Definition at line 82 of file patchInjectionBase.H.
triToFace_
labelList triToFace_ protected
Definition at line 85 of file patchInjectionBase.H.
triCumulativeMagSf_
scalarList triCumulativeMagSf_ protected
Definition at line 88 of file patchInjectionBase.H.
sumTriMagSf_
scalarList sumTriMagSf_ protected
Definition at line 91 of file patchInjectionBase.H.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/Kinematic/InjectionModel/PatchInjection/patchInjectionBase.H
src/lagrangian/intermediate/submodels/Kinematic/InjectionModel/PatchInjection/patchInjectionBase.C