OpenFOAM: randomRenumber Class Reference
randomRenumber Class Reference
Random renumber. Just to see effect of renumbering.
#include <randomRenumber.H>
Public Member Functions
TypeName ("random")
randomRenumber (const dictionary &dict)
virtual ~randomRenumber ()=default
virtual labelList renumber (const pointField &) const
virtual labelList renumber (const polyMesh &, const pointField &) const
virtual labelList renumber (const CompactListList< label > &cellCells, const pointField &cellCentres) const
virtual labelList renumber (const labelListList &cellCells, const pointField &cellCentres) const
Public Member Functions inherited from renumberMethod
TypeName ("renumberMethod")
declareRunTimeSelectionTable (autoPtr, renumberMethod, dictionary,(const dictionary &renumberDict),(renumberDict))
renumberMethod (const dictionary &dict)
virtual ~renumberMethod ()=default
virtual labelList renumber (const labelList &cellCells, const labelList &offsets, const pointField &) const
virtual labelList renumber (const polyMesh &mesh, const labelList &fineToCoarse, const pointField &coarsePoints) const
Additional Inherited Members
Static Public Member Functions inherited from renumberMethod
static autoPtr< renumberMethod > New (const dictionary &renumberDict)
Protected Member Functions inherited from renumberMethod
renumberMethod (const renumberMethod &)=delete
void operator= (const renumberMethod &)=delete
Protected Attributes inherited from renumberMethod
const dictionary & renumberDict_
Detailed Description
Random renumber. Just to see effect of renumbering.
Source files
randomRenumber.H
randomRenumber.C
Definition at line 45 of file randomRenumber.H.
Constructor & Destructor Documentation
randomRenumber()
randomRenumber (const dictionary & dict) explicit
Definition at line 43 of file randomRenumber.C.
~randomRenumber()
virtual ~randomRenumber () virtual default
Member Function Documentation
TypeName()
TypeName ("random")
renumber() [1/4]
Foam::labelList renumber (const pointField & points) const virtual
Reimplemented from renumberMethod.
Definition at line 51 of file randomRenumber.C.
References forAll, Foam::identity(), points, Random::position(), rndGen, and UPtrList< T >::size().
renumber() [2/4]
Foam::labelList renumber (const polyMesh & mesh, const pointField & points) const virtual
Reimplemented from renumberMethod.
Definition at line 72 of file randomRenumber.C.
References points, and Foam::renumber().
renumber() [3/4]
Foam::labelList renumber (const CompactListList< label > & cellCells, const pointField & cellCentres) const virtual
Reimplemented from renumberMethod.
Definition at line 82 of file randomRenumber.C.
References points, and Foam::renumber().
renumber() [4/4]
Foam::labelList renumber (const labelListList & cellCells, const pointField & cellCentres) const virtual
Implements renumberMethod.
Definition at line 92 of file randomRenumber.C.
References points, and Foam::renumber().
The documentation for this class was generated from the following files:
src/renumber/renumberMethods/randomRenumber/randomRenumber.H
src/renumber/renumberMethods/randomRenumber/randomRenumber.C