OpenFOAM: parseDriver Class Reference
parseDriver Class Reference
Driver for patch expressions.
#include <patchExprDriver.H>
Public Member Functions
ClassName ("patchExpr::driver")
parseDriver (const parseDriver &)=delete
void operator= (const parseDriver &)=delete
parseDriver (const fvPatch &p, const dictionary &dict=dictionary::null)
parseDriver (const fvPatch &p, const parseDriver &driver, const dictionary &dict)
parseDriver (const word &patchName, const fvMesh &mesh)
parseDriver (const dictionary &dict, const fvMesh &mesh)
virtual ~parseDriver ()=default
virtual const fvMesh & mesh () const
virtual label size () const
virtual label pointSize () const
label size (const FieldAssociation geoType) const
virtual unsigned parse (const std::string &expr, size_t pos=0, size_t len=std::string::npos)
template<class Type >
void setResult (Field< Type > *ptr, bool pointVal=false)
template<class Type >
tmp< Field< Type > > getVariableIfAvailable (const word &fldName) const
template<class Type >
tmp< Field< Type > > getField (const word &fldName)
template<class Type >
tmp< Field< Type > > getVolField (const word &fldName)
template<class Type >
tmp< Field< Type > > getSurfaceField (const word &fldName)
template<class Type >
tmp< Field< Type > > getPointField (const word &fldName)
template<class Type >
tmp< Field< Type > > patchInternalField (const word &fldName)
template<class Type >
tmp< Field< Type > > patchNeighbourField (const word &fldName)
template<class Type >
tmp< Field< Type > > patchNormalField (const word &fldName)
template<class Type >
tmp< Field< Type > > faceToPoint (const Field< Type > &field) const
template<class Type >
tmp< Field< Type > > pointToFace (const Field< Type > &field) const
template<class Type >
Type areaAverage (const Field< Type > &fld) const
template<class Type >
Type areaSum (const Field< Type > &fld) const
tmp< scalarField > field_faceArea () const
tmp< vectorField > field_faceCentre () const
tmp< vectorField > field_areaNormal () const
tmp< vectorField > field_unitNormal () const
tmp< vectorField > field_pointField () const
tmp< boolField > field_cellSet (const word &name) const
tmp< boolField > field_cellZone (const word &name) const
tmp< boolField > field_faceSet (const word &name) const
tmp< boolField > field_faceZone (const word &name) const
tmp< scalarField > field_rand (label seed=0, bool gaussian=false) const
tmp< scalarField > field_randGaussian (label seed=0) const
template<>
tmp< Field< bool > > getSurfaceField (const word &fldName)
template<>
tmp< Field< bool > > getPointField (const word &fldName)
template<>
Foam::tmp< Foam::Field< bool > > getSurfaceField (const word &name)
template<>
Foam::tmp< Foam::Field< bool > > getPointField (const word &name)
template<class Type >
Foam::tmp< Foam::Field< Type > > getVariableIfAvailable (const word &name) const
template<class Type >
Foam::tmp< Foam::Field< Type > > getVolField (const word &name)
template<class Type >
Foam::tmp< Foam::Field< Type > > getSurfaceField (const word &name)
template<class Type >
Foam::tmp< Foam::Field< Type > > getPointField (const word &name)
template<class Type >
Foam::tmp< Foam::Field< Type > > getField (const word &name)
template<class Type >
Foam::tmp< Foam::Field< Type > > patchInternalField (const word &name)
template<class Type >
Foam::tmp< Foam::Field< Type > > patchNeighbourField (const word &name)
template<class Type >
Foam::tmp< Foam::Field< Type > > patchNormalField (const word &name)
template<class Type >
Foam::tmp< Foam::Field< Type > > faceToPoint (const Field< Type > &field) const
template<class Type >
Foam::tmp< Foam::Field< Type > > pointToFace (const Field< Type > &field) const
template<class Type >
Foam::tmp< Foam::VolumeField< Type > > getVolField (const word &fldName, bool getOldTime)
template<class Type >
Foam::tmp< Foam::SurfaceField< Type > > getSurfaceField (const word &fldName, bool getOldTime)
template<class Type >
Foam::tmp< Foam::PointField< Type > > getPointField (const word &fldName, bool getOldTime)
template<class Type >
Foam::tmp< Foam::Field< Type > > getField (const word &name) const
Public Member Functions inherited from genericRagelLemonDriver
genericRagelLemonDriver ()
genericRagelLemonDriver (const genericRagelLemonDriver &rhs)=default
genericRagelLemonDriver (genericRagelLemonDriver &&rhs)=default
virtual ~genericRagelLemonDriver ()=default
void clear ()
const std::string & content () const
void content (const std::string &s, size_t pos=0, size_t len=std::string::npos)
std::string::const_iterator cbegin () const
std::string::const_iterator cend () const
size_t parsePosition () const
size_t & parsePosition ()
Ostream & printBuffer (Ostream &os) const
void reportFatal (const std::string &msg) const
void reportFatal (const std::string &msg, size_t pos) const
Public Member Functions inherited from fvExprDriver
TypeName ("fvExprDriver")
declareRunTimeSelectionTable (autoPtr, fvExprDriver, dictionary,(const dictionary &dict, const fvMesh &mesh),(dict, mesh))
declareRunTimeSelectionTable (autoPtr, fvExprDriver, idName,(const word &ident, const fvMesh &mesh),(ident, mesh))
fvExprDriver (enum exprDriver::searchControls search=exprDriver::searchControls::DEFAULT_SEARCH, const dictionary &dict=dictionary::null)
fvExprDriver (const fvExprDriver &rhs, const dictionary &dict)
fvExprDriver (const dictionary &dict)
virtual autoPtr< fvExprDriver > clone ()=delete
virtual ~fvExprDriver ()
bool cacheSets () const
virtual void clearVariables ()
virtual bool hasVariable (const word &name) const
virtual const exprResult & variable (const word &name) const
template<class Type >
bool isVariableOrField (const word &name, const bool wantPointData=false, const label expectSize=-1) const
template<class Type >
tmp< Field< Type > > getVariable (const word &name, const label expectSize, const bool mandatory=true) const
word getFieldClassName (const word &name) const
topoSetSource::sourceType topoSetType (const word &name) const
topoSetSource::sourceType topoZoneType (const word &name) const
topoSetSource::sourceType topoSourceType (const word &name) const
refPtr< labelList > getTopoSetLabels (const word &name, enum topoSetSource::sourceType setType) const
bool isCellZone (const word &name) const
bool isFaceZone (const word &name) const
bool isPointZone (const word &name) const
bool isCellSet (const word &name) const
bool isFaceSet (const word &name) const
bool isPointSet (const word &name) const
virtual void evaluateVariable (const word &varName, const expressions::exprString &expr)
virtual void evaluateVariableRemote (string remote, const word &varName, const expressions::exprString &expr)
template<class Type >
bool isVariable (const word &name, bool wantPointData=false, label expectSize=-1) const
template<class Type >
bool foundField (const word &name) const
word getTypeOfField (const word &fieldName) const
virtual bool readDict (const dictionary &dict)
Ostream & writeCommon (Ostream &os, bool debug=false) const
void createWriterAndRead (const word &name)
void tryWrite () const
template<class GeomField >
Foam::tmp< GeomField > getOrReadField (const word &name, const bool mandatory, const bool getOldTime)
template<class GeomField >
Foam::tmp< GeomField > getOrReadPointField (const word &name, const bool mandatory, const bool getOldTime)
template<class GeomField , class Mesh >
Foam::tmp< GeomField > readAndRegister (const word &name, const Mesh &meshRef)
template<class Type >
Foam::tmp< Foam::Field< Type > > getVariable (const word &name, const label expectedSize, const bool mandatory) const
template<class GeomField , class Mesh >
Foam::tmp< GeomField > getOrReadFieldImpl (const word &name, const Mesh &meshRef, bool mandatory, bool getOldTime)
template<class T >
Foam::autoPtr< T > getTopoSet (const fvMesh &mesh, const word &name, SetOrigin &origin) const
Public Member Functions inherited from exprDriver
TypeName ("exprDriver")
exprDriver (const exprDriver &)=delete
void operator= (const exprDriver &)=delete
exprDriver (enum searchControls search=searchControls::DEFAULT_SEARCH, const dictionary &dict=dictionary::null)
exprDriver (const exprDriver &rhs, const dictionary &dict)
exprDriver (const dictionary &dict)
virtual ~exprDriver ()=default
const TimeState * timeState () const noexcept
virtual scalar timeValue () const
virtual scalar deltaT () const
const dictionary & dict () const noexcept
const exprResult & result () const noexcept
exprResult & result () noexcept
void clearResult ()
template<class Type >
tmp< Field< Type > > getResult (bool wantPointData=false)
const word & getResultType () const noexcept
void resetDb (const objectRegistry *obrPtr=nullptr)
void resetDb (const objectRegistry &db)
scalar argValue () const noexcept
int stashedTokenId () const noexcept
int resetStashedTokenId (int tokenId=0) const noexcept
void setDebugging (bool scannerDebug, bool parserDebug)
void setDebugging (const exprDriver &rhs)
bool setCaching (bool on) noexcept
void setSearchBehaviour (enum searchControls search, const bool caching=false)
void setSearchBehaviour (const exprDriver &rhs)
bool debugScanner () const noexcept
bool debugParser () const noexcept
bool prevIterIsOldTime () const
void setArgument (const scalar val) noexcept
void addVariables (const expressions::exprString &expr, bool clear=true)
void addVariables (const UList< expressions::exprString > &list, bool clear=true)
template<class T >
void addUniformVariable (const word &name, const T &val)
bool hasContextObjects () const
const regIOobject * cfindContextIOobject (const word &name) const
template<class ObjType >
const ObjType * cfindContextObject (const word &name) const
void addContextObject (const word &name, const regIOobject *)
void addContextObject (const regIOobject *)
void removeContextObject (const word &name)
void removeContextObject (const regIOobject *)
const contextObjectTableType & contextObjects () const noexcept
contextObjectTableType & contextObjects () noexcept
template<class Type >
bool isFunction (const word &name) const
template<class Type >
Type getFunctionValue (const word &name, const scalar x) const
template<class Type >
void fillFunctionValues (Field< Type > &result, const word &name, const scalarField &input) const
template<class T >
bool isLocalVariable (const word &name, bool wantPointData=false, label expectedSize=-1) const
template<class Type >
tmp< Field< Type > > getLocalVariable (const word &name, label expectSize, const bool mandatory=true) const
template<class Type >
tmp< Field< Type > > evaluate (const expressions::exprString &expr, bool wantPointData=false)
template<class Type >
Type evaluateUniform (const expressions::exprString &expr, bool wantPointData=false)
void evaluateVariable (const word &varName, const expressions::exprString &expr)
template<class Type >
tmp< Field< Type > > newField (const Type &val=pTraits< Type >::zero) const
template<class Type >
tmp< Field< Type > > newPointField (const Type &val=pTraits< Type >::zero) const
expressions::exprString readExpression (const word &name)
label setVariableStrings (const dictionary &dict, bool mandatory=false)
Ostream & writeVariableStrings (Ostream &os, const word &keyword="") const
template<class Type >
void addUniformVariable (const word &name, const Type &val)
template<class Type >
Foam::tmp< Foam::Field< Type > > evaluate (const expressions::exprString &expr, bool wantPointData)
template<class Type >
Foam::tmp< Foam::Field< Type > > getResult (bool wantPointData)
template<class Type >
const Foam::Function1< Type > * getFunction1Ptr (const word &name, const HashTable< refPtr< Function1< Type > > > &tbl, wordList *listFailure)
template<class Type >
Foam::tmp< Foam::Field< Type > > newField (const Type &val) const
template<class Type >
Foam::tmp< Foam::Field< Type > > newPointField (const Type &val) const
Protected Member Functions
tmp< boolField > field_cellSelection (const word &name, enum topoSetSource::sourceType setType) const
tmp< boolField > field_faceSelection (const word &name, enum topoSetSource::sourceType setType) const
Protected Member Functions inherited from fvExprDriver
void setGlobalScopes (const wordUList &scopes)
virtual exprResult & variable (const word &name)
template<class T >
bool isGlobalVariable (const word &name, const bool wantPointData=false, const label expectedSize=-1) const
const exprResult & lookupGlobal (const word &name) const
template<class Type >
bool isField (const word &name, const bool wantPointData=false, const label expectSize=-1) const
template<class GeomField >
tmp< GeomField > getOrReadField (const word &name, const bool mandatory=true, const bool getOldTime=false)
template<class GeomField >
tmp< GeomField > getOrReadPointField (const word &name, const bool mandatory=true, const bool getOldTime=false)
template<class GeomField , class MeshRef >
tmp< GeomField > getOrReadFieldImpl (const word &name, const MeshRef &meshRef, const bool mandatory=true, const bool getOldTime=false)
template<class GeomField , class MeshRef >
tmp< GeomField > readAndRegister (const word &name, const MeshRef &meshRef)
template<class T >
autoPtr< T > getTopoSet (const fvMesh &mesh, const word &setName, SetOrigin &origin) const
template<class T >
bool updateSet (autoPtr< T > &setPtr, const word &setName, SetOrigin origin) const
virtual void updateSpecialVariables (bool force=false)
virtual bool hasDataToWrite () const
virtual void prepareData (dictionary &dict) const
virtual void getData (const dictionary &dict)
Protected Member Functions inherited from exprDriver
bool searchRegistry () const noexcept
bool searchFiles () const noexcept
bool cacheReadFields () const noexcept
void resetTimeReference (const TimeState *ts)
void resetTimeReference (const TimeState &ts)
void writeFunctions (Ostream &os) const
void fill_random (scalarField &field, label seed=0, const bool gaussian=false) const
virtual bool update ()
virtual exprResult getRemoteResult (const exprDriver &other) const
Protected Attributes
const fvPatch & patch_
Protected Attributes inherited from genericRagelLemonDriver
std::reference_wrapper< const std::string > content_
size_t start_
size_t length_
size_t position_
Protected Attributes inherited from exprDriver
const dictionary & dict_
exprResult result_
List< expressions::exprString > variableStrings_
HashTable< exprResult > variables_
HashTable< refPtr< Function1< scalar > > > scalarFuncs_
HashTable< refPtr< Function1< vector > > > vectorFuncs_
contextObjectTableType contextObjects_
scalar arg1Value_
const TimeState * timeStatePtr_
const objectRegistry * obrPtr_
int stashedTokenId_
bool debugScanner_
bool debugParser_
bool allowShadowing_
bool prevIterIsOldTime_
searchControls searchCtrl_
Additional Inherited Members
Public Types inherited from genericRagelLemonDriver
typedef size_t location_type
Public Types inherited from exprDriver
enum searchControls {
NO_SEARCH = 0 , SEARCH_REGISTRY = 1 , SEARCH_FILES = 2 , CACHE_READ_FIELDS = 4 ,
DEFAULT_SEARCH = (SEARCH_REGISTRY)
}
typedef HashTable< const regIOobject * > contextObjectTableType
Static Public Member Functions inherited from fvExprDriver
static const fvMesh & defaultMesh ()
static const fvMesh * resetDefaultMesh (const fvMesh &mesh, const bool force=false)
static autoPtr< fvExprDriver > New (const dictionary &dict, const fvMesh &mesh)
static autoPtr< fvExprDriver > New (const dictionary &dict)
static autoPtr< fvExprDriver > New (const word &type, const word &id, const fvMesh &mesh)
Static Public Member Functions inherited from exprDriver
static expressions::exprString readExpression (const word &name, const dictionary &dict)
static List< expressions::exprString > readVariableStrings (const dictionary &dict, const word &name="variables", bool mandatory=false)
Protected Types inherited from fvExprDriver
enum SetOrigin {
INVALID = 0 , NEW , FILE , MEMORY ,
CACHE
}
Static Protected Member Functions inherited from fvExprDriver
static const fvMesh & regionMesh (const dictionary &dict, const fvMesh &mesh, bool readIfNecessary)
template<class T >
static word defaultBoundaryType (const T &)
template<class Type >
static word defaultBoundaryType (const VolumeField< Type > &)
template<class T >
static void correctField (T &)
template<class Type >
static void correctField (VolumeField< Type > &fld)
Static Protected Member Functions inherited from exprDriver
template<class Type >
static Type weightedAverage (const scalarField &weights, const Field< Type > &fld)
template<class Type >
static Type weightedSum (const scalarField &weights, const Field< Type > &fld)
static point getPositionOfMinimum (const scalarField &vals, const pointField &locs)
static point getPositionOfMaximum (const scalarField &vals, const pointField &locs)
Detailed Description
Driver for patch expressions.
In addition to the standard mathematical functions, operations and logical and relational operations, the patch expressions support the following driver-specific functions:
Functions
Function Description Number of arguments
pos The face centres 0
pts The face points 0
area The face area magnitudes 0
weightAverage Area weighted average 1
weightSum Area weighted sum 1
face The face area normal vectors 0
normal The face unit normal vectors 0
point A point-field point value 1
faceToPoint Interpolate face values onto points 1
pointToFace Interpolate point values onto faces 1
rand Random field 0/1
snGrad Surface normal field 0
internalField Internal field next to patch 0
neighbourField patch field on opposite side of coupled patch 0
Note
Use namespace debug switch patchExpr for scanner (2), parser (4) or dictionary controls as per Foam::expressions::exprDriver.
Source files
patchExprDriver.H
patchExprDriver.C
patchExprDriverFields.C
patchExprDriverTemplates.C
Definition at line 161 of file patchExprDriver.H.
Constructor & Destructor Documentation
parseDriver() [1/5]
parseDriver (const parseDriver &) delete
parseDriver() [2/5]
parseDriver (const fvPatch & p, const dictionary & dict = dictionary::null) explicit
Definition at line 95 of file patchExprDriver.C.
References parseDriver::patch_, exprDriver::resetDb(), and exprDriver::resetTimeReference().
parseDriver() [3/5]
parseDriver (const fvPatch & p, const parseDriver & driver, const dictionary & dict)
Definition at line 110 of file patchExprDriver.C.
References parseDriver::patch_, exprDriver::resetDb(), and exprDriver::resetTimeReference().
parseDriver() [4/5]
parseDriver (const word & patchName, const fvMesh & mesh)
Definition at line 126 of file patchExprDriver.C.
parseDriver() [5/5]
parseDriver (const dictionary & dict, const fvMesh & mesh)
Definition at line 136 of file patchExprDriver.C.
~parseDriver()
virtual ~parseDriver () virtual default
Member Function Documentation
field_cellSelection()
Foam::tmp< Foam::boolField > field_cellSelection (const word & name, enum topoSetSource::sourceType setType) const protected
Definition at line 52 of file patchExprDriverFields.C.
References topoSetSource::CELLSET_SOURCE, topoSetSource::CELLZONE_SOURCE, Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::name(), tmp< T >::New(), and Foam::nl.
field_faceSelection()
Foam::tmp< Foam::boolField > field_faceSelection (const word & name, enum topoSetSource::sourceType setType) const protected
Definition at line 97 of file patchExprDriverFields.C.
References Foam::exit(), topoSetSource::FACESET_SOURCE, topoSetSource::FACEZONE_SOURCE, Foam::FatalError, FatalErrorInFunction, forAll, Foam::name(), tmp< T >::New(), and Foam::nl.
ClassName()
ClassName ("patchExpr::driver")
operator=()
void operator= (const parseDriver &) delete
mesh()
virtual const fvMesh & mesh () const inline virtual
Implements fvExprDriver.
Definition at line 248 of file patchExprDriver.H.
References parseDriver::patch_.
size() [1/2]
virtual label size () const inline virtual
Implements fvExprDriver.
Definition at line 254 of file patchExprDriver.H.
References parseDriver::patch_, and UPtrList< T >::size().
Referenced by parseDriver::getPointField(), and parseDriver::getVariableIfAvailable().
pointSize()
virtual label pointSize () const inline virtual
Implements fvExprDriver.
Definition at line 260 of file patchExprDriver.H.
References parseDriver::patch_.
Referenced by parseDriver::getVariableIfAvailable().
size() [2/2]
Foam::label size (const FieldAssociation geoType) const inline
Definition at line 23 of file patchExprDriverI.H.
References Foam::expressions::FACE_DATA, parseDriver::patch_, Foam::expressions::POINT_DATA, and UPtrList< T >::size().
parse()
unsigned parse (const std::string & expr, size_t pos = 0, size_t len = std::string::npos) virtual
Implements exprDriver.
Definition at line 148 of file patchExprDriver.C.
References Foam::pos(), and scanner::process().
setResult()
template<class Type > void setResult (Field< Type > * ptr, bool pointVal = false) inline
Definition at line 288 of file patchExprDriver.H.
References exprDriver::result().
getVariableIfAvailable() [1/2]
template<class Type > tmp< Field< Type > > getVariableIfAvailable (const word & fldName) const
getField() [1/3]
template<class Type > tmp< Field< Type > > getField (const word & fldName)
getVolField() [1/3]
template<class Type > tmp< Field< Type > > getVolField (const word & fldName)
getSurfaceField() [1/5]
template<class Type > tmp< Field< Type > > getSurfaceField (const word & fldName)
getPointField() [1/5]
template<class Type > tmp< Field< Type > > getPointField (const word & fldName)
patchInternalField() [1/2]
template<class Type > tmp< Field< Type > > patchInternalField (const word & fldName)
patchNeighbourField() [1/2]
template<class Type > tmp< Field< Type > > patchNeighbourField (const word & fldName)
patchNormalField() [1/2]
template<class Type > tmp< Field< Type > > patchNormalField (const word & fldName)
faceToPoint() [1/2]
template<class Type > tmp< Field< Type > > faceToPoint (const Field< Type > & field) const
pointToFace() [1/2]
template<class Type > tmp< Field< Type > > pointToFace (const Field< Type > & field) const
areaAverage()
template<class Type > Type areaAverage (const Field< Type > & fld) const inline
Definition at line 346 of file patchExprDriver.H.
References fld(), parseDriver::patch_, and exprDriver::weightedAverage().
areaSum()
template<class Type > Type areaSum (const Field< Type > & fld) const inline
Definition at line 353 of file patchExprDriver.H.
References fld(), parseDriver::patch_, and exprDriver::weightedSum().
field_faceArea()
Foam::tmp< Foam::scalarField > field_faceArea () const
Definition at line 143 of file patchExprDriverFields.C.
field_faceCentre()
Foam::tmp< Foam::vectorField > field_faceCentre () const
Definition at line 150 of file patchExprDriverFields.C.
field_areaNormal()
Foam::tmp< Foam::vectorField > field_areaNormal () const
Definition at line 157 of file patchExprDriverFields.C.
field_unitNormal()
Foam::tmp< Foam::vectorField > field_unitNormal () const
Definition at line 164 of file patchExprDriverFields.C.
field_pointField()
Foam::tmp< Foam::vectorField > field_pointField () const
Definition at line 171 of file patchExprDriverFields.C.
field_cellSet()
tmp< boolField > field_cellSet (const word & name) const inline
field_cellZone()
Foam::tmp< Foam::boolField > field_cellZone (const word & name) const inline
Definition at line 58 of file patchExprDriverI.H.
References topoSetSource::CELLZONE_SOURCE, and Foam::name().
field_faceSet()
Foam::tmp< Foam::boolField > field_faceSet (const word & name) const inline
Definition at line 72 of file patchExprDriverI.H.
References topoSetSource::FACESET_SOURCE, and Foam::name().
field_faceZone()
Foam::tmp< Foam::boolField > field_faceZone (const word & name) const inline
Definition at line 86 of file patchExprDriverI.H.
References topoSetSource::FACEZONE_SOURCE, and Foam::name().
field_rand()
Foam::tmp< Foam::scalarField > field_rand (label seed = 0, bool gaussian = false) const
Definition at line 178 of file patchExprDriverFields.C.
References exprDriver::fill_random(), and tmp< T >::New().
Referenced by parseDriver::field_randGaussian().
field_randGaussian()
tmp< scalarField > field_randGaussian (label seed = 0) const inline
Definition at line 391 of file patchExprDriver.H.
References parseDriver::field_rand().
getSurfaceField() [2/5]
template<> tmp< Field< bool > > getSurfaceField (const word & fldName)
getPointField() [2/5]
template<> tmp< Field< bool > > getPointField (const word & fldName)
getSurfaceField() [3/5]
template<> Foam::tmp< Foam::Field< bool > > getSurfaceField (const word & name)
Definition at line 1 of file patchExprDriverFields.C.
getPointField() [3/5]
template<> Foam::tmp< Foam::Field< bool > > getPointField (const word & name)
Definition at line 1 of file patchExprDriverFields.C.
References Foam::name(), and parseDriver::size().
getVariableIfAvailable() [2/2]
template<class Type > Foam::tmp< Foam::Field< Type > > getVariableIfAvailable (const word & name) const
Definition at line 27 of file patchExprDriverTemplates.C.
References Foam::endl(), Foam::gAverage(), fvExprDriver::hasVariable(), fvExprDriver::lookupGlobal(), Foam::name(), fvExprDriver::New(), parseDriver::pointSize(), Foam::returnReduceAnd(), parseDriver::size(), UPtrList< T >::size(), fvExprDriver::variable(), and WarningInFunction.
getVolField() [2/3]
template<class Type > Foam::tmp< Foam::Field< Type > > getVolField (const word & name)
Definition at line 77 of file patchExprDriverTemplates.C.
References Foam::name().
getSurfaceField() [4/5]
template<class Type > Foam::tmp< Foam::Field< Type > > getSurfaceField (const word & name)
Definition at line 85 of file patchExprDriverTemplates.C.
References Foam::name().
getPointField() [4/5]
template<class Type > Foam::tmp< Foam::Field< Type > > getPointField (const word & name)
Definition at line 93 of file patchExprDriverTemplates.C.
References Foam::name().
getField() [2/3]
template<class Type > Foam::tmp< Foam::Field< Type > > getField (const word & name)
Definition at line 101 of file patchExprDriverTemplates.C.
References exprDriver::cfindContextIOobject(), objectRegistry::cfindIOobject(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::flatOutput(), found, mesh, Foam::name(), MeshObject< polyMesh, UpdateableMeshObject, pointMesh >::New(), Foam::New(), Foam::nl, objectRegistry::sortedNames(), and objectRegistry::thisDb().
patchInternalField() [2/2]
template<class Type > Foam::tmp< Foam::Field< Type > > patchInternalField (const word & name)
Definition at line 219 of file patchExprDriverTemplates.C.
References exprDriver::cfindContextIOobject(), objectRegistry::cfindIOobject(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::flatOutput(), found, mesh, Foam::name(), MeshObject< polyMesh, UpdateableMeshObject, pointMesh >::New(), Foam::New(), Foam::nl, objectRegistry::sortedNames(), and objectRegistry::thisDb().
patchNeighbourField() [2/2]
template<class Type > Foam::tmp< Foam::Field< Type > > patchNeighbourField (const word & name)
Definition at line 316 of file patchExprDriverTemplates.C.
References exprDriver::cfindContextIOobject(), objectRegistry::cfindIOobject(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::flatOutput(), found, mesh, Foam::name(), Foam::New(), Foam::nl, objectRegistry::sortedNames(), and objectRegistry::thisDb().
patchNormalField() [2/2]
template<class Type > Foam::tmp< Foam::Field< Type > > patchNormalField (const word & name)
Definition at line 391 of file patchExprDriverTemplates.C.
References exprDriver::cfindContextIOobject(), objectRegistry::cfindIOobject(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::flatOutput(), found, mesh, Foam::name(), Foam::New(), Foam::nl, objectRegistry::sortedNames(), and objectRegistry::thisDb().
faceToPoint() [2/2]
template<class Type > Foam::tmp< Foam::Field< Type > > faceToPoint (const Field< Type > & field) const
Definition at line 466 of file patchExprDriverTemplates.C.
References field().
pointToFace() [2/2]
template<class Type > Foam::tmp< Foam::Field< Type > > pointToFace (const Field< Type > & field) const
Definition at line 479 of file patchExprDriverTemplates.C.
References field().
getVolField() [3/3]
template<class Type > Foam::tmp< Foam::VolumeField< Type > > getVolField (const word & fldName, bool getOldTime)
Definition at line 173 of file volumeExprDriverTemplates.C.
getSurfaceField() [5/5]
template<class Type > Foam::tmp< Foam::SurfaceField< Type > > getSurfaceField (const word & fldName, bool getOldTime)
Definition at line 190 of file volumeExprDriverTemplates.C.
getPointField() [5/5]
template<class Type > Foam::tmp< Foam::PointField< Type > > getPointField (const word & fldName, bool getOldTime)
Definition at line 207 of file volumeExprDriverTemplates.C.
getField() [3/3]
template<class Type > Foam::tmp< Foam::Field< Type > > getField (const word & name) const
Definition at line 25 of file fieldExprDriverTemplates.C.
References Foam::endl(), Foam::gAverage(), exprDriver::hasVariable(), Foam::name(), Foam::New(), parseDriver::pointSize(), Foam::returnReduceAnd(), parseDriver::size(), UPtrList< T >::size(), exprDriver::variable(), and WarningInFunction.
Member Data Documentation
patch_
const fvPatch& patch_ protected
Definition at line 180 of file patchExprDriver.H.
Referenced by parseDriver::areaAverage(), parseDriver::areaSum(), parseDriver::mesh(), parseDriver::parseDriver(), parseDriver::parseDriver(), parseDriver::pointSize(), parseDriver::size(), and parseDriver::size().
The documentation for this class was generated from the following files:
src/finiteVolume/expressions/patch/patchExprDriver.H
src/finiteVolume/expressions/patch/patchExprDriver.C
src/finiteVolume/expressions/patch/patchExprDriverFields.C
src/finiteVolume/expressions/patch/patchExprDriverI.H
src/finiteVolume/expressions/patch/patchExprDriverTemplates.C
src/finiteVolume/expressions/volume/volumeExprDriverTemplates.C
src/OpenFOAM/expressions/fields/fieldExprDriverTemplates.C