OpenFOAM: directMethod Class Reference
directMethod Class Reference
Direct (one-to-one cell correspondence) mesh-to-mesh interpolation class.
#include <directMethod.H>
Public Member Functions
TypeName ("direct")
directMethod (const polyMesh &src, const polyMesh &tgt)
virtual ~directMethod ()
virtual void calculate (labelListList &srcToTgtAddr, scalarListList &srcToTgtWght, pointListList &srcToTgtVec, labelListList &tgtToSrcAddr, scalarListList &tgtToSrcWght, pointListList &tgtToSrcVec)
Public Member Functions inherited from meshToMeshMethod
TypeName ("meshToMeshMethod")
declareRunTimeSelectionTable (autoPtr, meshToMeshMethod, components,(const polyMesh &src, const polyMesh &tgt),(src, tgt))
meshToMeshMethod (const polyMesh &src, const polyMesh &tgt)
virtual ~meshToMeshMethod ()
const polyMesh & src () const
const polyMesh & tgt () const
scalar V () const
void writeConnectivity (const polyMesh &mesh1, const polyMesh &mesh2, const labelListList &mesh1ToMesh2Addr) const
Protected Member Functions
virtual bool intersect (const label srcCelli, const label tgtCelli) const
virtual bool findInitialSeeds (const labelList &srcCellIDs, const boolList &mapFlag, const label startSeedI, label &srcSeedI, label &tgtSeedI) const
virtual void calculateAddressing (labelListList &srcToTgtCellAddr, scalarListList &srcToTgtCellWght, labelListList &tgtToSrcCellAddr, scalarListList &tgtToSrcCellWght, const label srcSeedI, const label tgtSeedI, const labelList &srcCellIDs, boolList &mapFlag, label &startSeedI)
virtual void appendToDirectSeeds (boolList &mapFlag, labelList &srcTgtSeed, DynamicList< label > &srcSeeds, label &srcSeedI, label &tgtSeedI) const
Protected Member Functions inherited from meshToMeshMethod
labelList maskCells () const
virtual scalar interVol (const label srcCelli, const label tgtCelli) const
virtual Tuple2< scalar, point > interVolAndCentroid (const label srcCellI, const label tgtCellI)
virtual void appendNbrCells (const label tgtCelli, const polyMesh &mesh, const DynamicList< label > &visitedTgtCells, DynamicList< label > &nbrTgtCellIDs) const
virtual bool initialise (labelListList &srcToTgtAddr, scalarListList &srcToTgtWght, labelListList &tgtToTgtAddr, scalarListList &tgtToTgtWght) const
Additional Inherited Members
Static Public Member Functions inherited from meshToMeshMethod
static autoPtr< meshToMeshMethod > New (const word &methodName, const polyMesh &src, const polyMesh &tgt)
Protected Attributes inherited from meshToMeshMethod
const polyMesh & src_
const polyMesh & tgt_
scalar V_
Static Protected Attributes inherited from meshToMeshMethod
static scalar tolerance_ = 1e-6
Detailed Description
Direct (one-to-one cell correspondence) mesh-to-mesh interpolation class.
Volume conservative.
Source files
directMethod.H
directMethod.C
Definition at line 48 of file directMethod.H.
Constructor & Destructor Documentation
directMethod()
directMethod (const polyMesh & src, const polyMesh & tgt)
Definition at line 215 of file directMethod.C.
~directMethod()
~directMethod () virtual
Definition at line 227 of file directMethod.C.
Member Function Documentation
intersect()
bool intersect (const label srcCelli, const label tgtCelli) const protected virtual
Reimplemented from meshToMeshMethod.
Definition at line 36 of file directMethod.C.
References polyMesh::FACE_PLANES, meshToMeshMethod::src_, and meshToMeshMethod::tgt_.
findInitialSeeds()
bool findInitialSeeds (const labelList & srcCellIDs, const boolList & mapFlag, const label startSeedI, label & srcSeedI, label & tgtSeedI) const protected virtual
Definition at line 51 of file directMethod.C.
References Foam::endl(), Foam::Pout, and UPtrList< T >::size().
calculateAddressing()
void calculateAddressing (labelListList & srcToTgtCellAddr, scalarListList & srcToTgtCellWght, labelListList & tgtToSrcCellAddr, scalarListList & tgtToSrcCellWght, const label srcSeedI, const label tgtSeedI, const labelList & srcCellIDs, boolList & mapFlag, label & startSeedI) protected virtual
Definition at line 92 of file directMethod.C.
References PtrList< T >::append(), forAll, and List< T >::transfer().
appendToDirectSeeds()
void appendToDirectSeeds (boolList & mapFlag, labelList & srcTgtSeed, DynamicList< label > & srcSeeds, label & srcSeedI, label & tgtSeedI) const protected virtual
Definition at line 158 of file directMethod.C.
References UPtrList< T >::back(), UPtrList< T >::empty(), found, and PtrList< T >::push_back().
TypeName()
TypeName ("direct")
calculate()
void calculate (labelListList & srcToTgtAddr, scalarListList & srcToTgtWght, pointListList & srcToTgtVec, labelListList & tgtToSrcAddr, scalarListList & tgtToSrcWght, pointListList & tgtToSrcVec) virtual
Implements meshToMeshMethod.
Definition at line 233 of file directMethod.C.
The documentation for this class was generated from the following files:
src/sampling/meshToMesh/calcMethod/direct/directMethod.H
src/sampling/meshToMesh/calcMethod/direct/directMethod.C