OpenFOAM: surfaceIntersection Class Reference
surfaceIntersection Class Reference
Basic surface-surface intersection description. Constructed from two surfaces it creates a description of the intersection.
#include <surfaceIntersection.H>
Public Types
enum intersectionType {
FIRST , SECOND , SELF , SELF_REGION ,
NONE
}
Public Member Functions
ClassName ("surfaceIntersection")
surfaceIntersection ()
surfaceIntersection (const triSurfaceSearch &querySurf1, const triSurfaceSearch &querySurf2, const dictionary &dict=dictionary::null)
surfaceIntersection (const triSurfaceSearch &querySurf1, const dictionary &dict=dictionary::null)
surfaceIntersection (const triSurface &surf1, const edgeIntersections &intersections1, const triSurface &surf2, const edgeIntersections &intersections2)
const pointField & cutPoints () const
const edgeList & cutEdges () const
const labelPairLookup & facePairToEdgeId () const
const labelListList & edgeCuts (const bool isFirstSurf) const
const labelListList & surf1EdgeCuts () const
const labelListList & surf2EdgeCuts () const
void mergePoints (const scalar mergeDist)
void mergeEdges ()
Static Public Attributes
static const Enum< intersectionType > selfIntersectionNames
Detailed Description
Basic surface-surface intersection description. Constructed from two surfaces it creates a description of the intersection.
The intersection information consists of the intersection line(s) with new points, new edges between points (note that these edges and points are on both surfaces) and various addressing from original surface faces/edges to intersection and vice versa.
Gets either precalculated intersection information or calculates it itself. Algorithm works by intersecting all edges of one surface with the other surface and storing a reference from both faces (one on surface1, one on surface 2) to the vertex. If the reference re-occurs we have the second hit of both faces and an edge is created between the retrieved vertex and the new one.
Note: when doing intersecting itself uses 'tolerance' as a fraction of current edge length to determine if intersection is a point-touching one instead of an edge-piercing action.
Some constructors allow a dictionary of intersection controls:
Property Description Type Default value
tolerance Edge-length tolerance scalar 1e-3
allowEdgeHits Edge-end cuts another edge bool true
snap Snap near end-points bool true
warnDegenerate Number of warnings about degenerate edges label 0
intersectionMethod Control for self intersection (self,region,none)
Source files
surfaceIntersection.H
surfaceIntersection.C
surfaceIntersectionFuncs.C
surfaceIntersectionTemplates.C
Definition at line 130 of file surfaceIntersection.H.
Member Enumeration Documentation
intersectionType
enum intersectionType
Enumerator
FIRST
First surface.
SECOND
Second surface.
SELF
Self-intersection.
SELF_REGION
Self-intersection, region-wise only.
NONE
None = invalid (for input only)
Definition at line 135 of file surfaceIntersection.H.
Constructor & Destructor Documentation
surfaceIntersection() [1/4]
surfaceIntersection ()
Definition at line 1048 of file surfaceIntersection.C.
surfaceIntersection() [2/4]
surfaceIntersection (const triSurfaceSearch & querySurf1, const triSurfaceSearch & querySurf2, const dictionary & dict = dictionary::null)
Definition at line 1063 of file surfaceIntersection.C.
References PtrList< T >::clear(), dict, Foam::endl(), surfaceIntersection::FIRST, Foam::Pout, surfaceIntersection::SECOND, UList< T >::size(), List< T >::transfer(), and OBJstream::write().
surfaceIntersection() [3/4]
surfaceIntersection (const triSurfaceSearch & querySurf1, const dictionary & dict = dictionary::null)
Definition at line 1176 of file surfaceIntersection.C.
References HashTable< T, Key, Hash >::clear(), PtrList< T >::clear(), dict, UList< T >::empty(), Foam::endl(), surfaceIntersection::NONE, Foam::Pout, surfaceIntersection::SELF, surfaceIntersection::selfIntersectionNames, UList< T >::size(), List< T >::transfer(), and OBJstream::write().
surfaceIntersection() [4/4]
surfaceIntersection (const triSurface & surf1, const edgeIntersections & intersections1, const triSurface & surf2, const edgeIntersections & intersections2)
Definition at line 1288 of file surfaceIntersection.C.
References PtrList< T >::append(), PtrList< T >::clear(), Foam::endl(), surfaceIntersection::FIRST, forAll, Foam::Pout, surfaceIntersection::SECOND, UPtrList< T >::size(), UList< T >::size(), List< T >::transfer(), and OBJstream::write().
Member Function Documentation
ClassName()
ClassName ("surfaceIntersection")
cutPoints()
const Foam::pointField & cutPoints () const
Definition at line 1434 of file surfaceIntersection.C.
cutEdges()
const Foam::edgeList & cutEdges () const
Definition at line 1440 of file surfaceIntersection.C.
facePairToEdgeId()
const Foam::labelPairLookup & facePairToEdgeId () const
Definition at line 1446 of file surfaceIntersection.C.
edgeCuts()
const Foam::labelListList & edgeCuts (const bool isFirstSurf) const
Definition at line 1452 of file surfaceIntersection.C.
surf1EdgeCuts()
const Foam::labelListList & surf1EdgeCuts () const
Definition at line 1468 of file surfaceIntersection.C.
surf2EdgeCuts()
const Foam::labelListList & surf2EdgeCuts () const
Definition at line 1474 of file surfaceIntersection.C.
mergePoints()
void mergePoints (const scalar mergeDist)
Definition at line 1480 of file surfaceIntersection.C.
References e, forAll, Foam::inplaceMergePoints(), Foam::inplaceRenumber(), and Foam::inplaceUniqueSort().
mergeEdges()
void mergeEdges ()
Definition at line 1518 of file surfaceIntersection.C.
References e, forAll, and PtrList< T >::setSize().
Member Data Documentation
selfIntersectionNames
const Foam::Enum< Foam::surfaceIntersection::intersectionType > selfIntersectionNames static
Definition at line 145 of file surfaceIntersection.H.
Referenced by surfaceIntersection::surfaceIntersection().
The documentation for this class was generated from the following files:
src/meshTools/triSurface/booleanOps/surfaceIntersection/surfaceIntersection.H
src/meshTools/triSurface/booleanOps/surfaceIntersection/surfaceIntersection.C
src/meshTools/triSurface/booleanOps/surfaceIntersection/surfaceIntersectionFuncs.C
src/meshTools/triSurface/booleanOps/surfaceIntersection/surfaceIntersectionTemplates.C