OpenFOAM: laminar Class Reference
laminar Class Reference
Film laminar turbulence model.
#include <laminar.H>
Public Member Functions
TypeName ("laminar")
laminar (liquidFilmBase &film, const dictionary &dict)
virtual ~laminar ()=default
tmp< faVectorMatrix > wallFriction (areaVectorField &U) const
virtual tmp< areaScalarField > mut () const
virtual tmp< faVectorMatrix > Su (areaVectorField &U) const
virtual void correct ()
Public Member Functions inherited from filmTurbulenceModel
TypeName ("filmTurbulenceModel")
declareRunTimeSelectionTable (autoPtr, filmTurbulenceModel, dictionary,(liquidFilmBase &film, const dictionary &dict),(film, dict))
filmTurbulenceModel (const word &modelType, liquidFilmBase &film, const dictionary &dict)
virtual ~filmTurbulenceModel ()=default
const liquidFilmBase & film () const
tmp< volSymmTensorField > devRhoReff () const
tmp< faVectorMatrix > primaryRegionFriction (areaVectorField &U) const
tmp< volScalarField > rho () const
virtual tmp< areaScalarField > Cw () const
Additional Inherited Members
Public Types inherited from filmTurbulenceModel
enum frictionMethodType { mquadraticProfile , mlinearProfile , mDarcyWeisbach , mManningStrickler }
enum shearMethodType { msimple , mwallFunction }
Static Public Member Functions inherited from filmTurbulenceModel
static autoPtr< filmTurbulenceModel > New (liquidFilmBase &film, const dictionary &dict)
Protected Attributes inherited from filmTurbulenceModel
const liquidFilmBase & film_
const dictionary dict_
const frictionMethodType method_
const shearMethodType shearMethod_
word rhoName_
scalar rhoRef_
Static Protected Attributes inherited from filmTurbulenceModel
static const Enum< frictionMethodType > frictionMethodTypeNames_
static const Enum< shearMethodType > shearMethodTypeNames_
Detailed Description
Film laminar turbulence model.
Source files
laminar.H
laminar.C
Definition at line 51 of file laminar.H.
Constructor & Destructor Documentation
laminar()
laminar (liquidFilmBase & film, const dictionary & dict)
Definition at line 41 of file laminar.C.
~laminar()
virtual ~laminar () virtual default
Member Function Documentation
TypeName()
TypeName ("laminar")
wallFriction()
tmp< faVectorMatrix > wallFriction (areaVectorField & U) const
Definition at line 83 of file laminar.C.
References filmTurbulenceModel::Cw(), filmTurbulenceModel::film_, Foam::fam::Sp(), and U.
Referenced by laminar::Su().
mut()
tmp< areaScalarField > mut () const virtual
Implements filmTurbulenceModel.
Definition at line 53 of file laminar.C.
References Foam::dimLength, Foam::dimMass, Foam::dimTime, filmTurbulenceModel::film(), tmp< T >::New(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, and timeName.
Su()
tmp< faVectorMatrix > Su (areaVectorField & U) const virtual
Implements filmTurbulenceModel.
Definition at line 77 of file laminar.C.
References filmTurbulenceModel::primaryRegionFriction(), U, and laminar::wallFriction().
correct()
void correct () virtual
Implements filmTurbulenceModel.
Definition at line 73 of file laminar.C.
The documentation for this class was generated from the following files:
src/regionFaModels/liquidFilm/subModels/kinematic/filmTurbulenceModel/laminar/laminar.H
src/regionFaModels/liquidFilm/subModels/kinematic/filmTurbulenceModel/laminar/laminar.C