OpenFOAM: memorybuf Class Reference
memorybuf Class Reference
A std::streambuf used for memory buffer streams such as UIListStream, UOListStream, etc.
#include <memoryStreamBuffer.H>
Classes
class in
class out
Protected Member Functions
virtual std::streampos seekoff (std::streamoff off, std::ios_base::seekdir way, std::ios_base::openmode which=std::ios_base::in|std::ios_base::out)
virtual std::streampos seekpos (std::streampos pos, std::ios_base::openmode which=std::ios_base::in|std::ios_base::out)
std::streamsize tellg () const
std::streamsize tellp () const
Detailed Description
A std::streambuf used for memory buffer streams such as UIListStream, UOListStream, etc.
Definition at line 47 of file memoryStreamBuffer.H.
Member Function Documentation
seekoff()
virtual std::streampos seekoff (std::streamoff off, std::ios_base::seekdir way, std::ios_base::openmode which = std::ios_base::in|std::ios_base::out) inline protected virtual
Definition at line 54 of file memoryStreamBuffer.H.
Referenced by memorybuf::seekpos().
seekpos()
virtual std::streampos seekpos (std::streampos pos, std::ios_base::openmode which = std::ios_base::in|std::ios_base::out) inline protected virtual
Definition at line 116 of file memoryStreamBuffer.H.
References Foam::pos(), and memorybuf::seekoff().
tellg()
std::streamsize tellg () const inline protected
Definition at line 127 of file memoryStreamBuffer.H.
tellp()
std::streamsize tellp () const inline protected
Definition at line 133 of file memoryStreamBuffer.H.
The documentation for this class was generated from the following file:
src/OpenFOAM/db/IOstreams/memory/memoryStreamBuffer.H