OpenFOAM: edgeInterpolationScheme< Type > Class Template Reference
edgeInterpolationScheme< Type > Class Template Reference abstract
Abstract base class for edge interpolation schemes.
#include <edgeInterpolationScheme.H>
Public Member Functions
declareRunTimeSelectionTable (tmp, edgeInterpolationScheme, Mesh,(const faMesh &mesh, Istream &schemeData),(mesh, schemeData))
declareRunTimeSelectionTable (tmp, edgeInterpolationScheme, MeshFlux,(const faMesh &mesh, const edgeScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
edgeInterpolationScheme (const faMesh &mesh)
virtual ~edgeInterpolationScheme ()
const faMesh & mesh () const
virtual tmp< edgeScalarField > weights (const GeometricField< Type, faPatchField, areaMesh > &) const =0
virtual bool corrected () const
virtual tmp< GeometricField< Type, faePatchField, edgeMesh > > correction (const GeometricField< Type, faPatchField, areaMesh > &) const
virtual tmp< GeometricField< Type, faePatchField, edgeMesh > > interpolate (const GeometricField< Type, faPatchField, areaMesh > &) const
virtual tmp< GeometricField< Type, faePatchField, edgeMesh > > euclidianInterpolate (const GeometricField< Type, faPatchField, areaMesh > &) const
tmp< GeometricField< Type, faePatchField, edgeMesh > > interpolate (const tmp< GeometricField< Type, faPatchField, areaMesh > > &) const
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Static Public Member Functions
static tmp< edgeInterpolationScheme< Type > > New (const faMesh &mesh, Istream &schemeData)
static tmp< edgeInterpolationScheme< Type > > New (const faMesh &mesh, const edgeScalarField &faceFlux, Istream &schemeData)
static tmp< GeometricField< Type, faePatchField, edgeMesh > > interpolate (const GeometricField< Type, faPatchField, areaMesh > &, const tmp< edgeScalarField > &, const tmp< edgeScalarField > &)
static tmp< GeometricField< Type, faePatchField, edgeMesh > > interpolate (const GeometricField< Type, faPatchField, areaMesh > &, const tmp< edgeScalarField > &)
static tmp< GeometricField< Type, faePatchField, edgeMesh > > euclidianInterpolate (const GeometricField< Type, faPatchField, areaMesh > &, const tmp< edgeScalarField > &)
Detailed Description
template<class Type>
class Foam::edgeInterpolationScheme< Type >
Abstract base class for edge interpolation schemes.
Source files
edgeInterpolationScheme.H
edgeInterpolationScheme.C
Definition at line 53 of file edgeInterpolationScheme.H.
Constructor & Destructor Documentation
edgeInterpolationScheme()
template<class Type > edgeInterpolationScheme (const faMesh & mesh) inline
Definition at line 102 of file edgeInterpolationScheme.H.
~edgeInterpolationScheme()
template<class Type > ~edgeInterpolationScheme () virtual
Definition at line 122 of file edgeInterpolationScheme.C.
Member Function Documentation
declareRunTimeSelectionTable() [1/2]
template<class Type > declareRunTimeSelectionTable (tmp , edgeInterpolationScheme< Type > , Mesh , (const faMesh &mesh, Istream &schemeData) , (mesh, schemeData))
declareRunTimeSelectionTable() [2/2]
template<class Type > declareRunTimeSelectionTable (tmp , edgeInterpolationScheme< Type > , MeshFlux , (const faMesh &mesh, const edgeScalarField &faceFlux, Istream &schemeData) , (mesh, faceFlux, schemeData))
New() [1/2]
template<class Type > Foam::tmp< Foam::edgeInterpolationScheme< Type > > New (const faMesh & mesh, Istream & schemeData) static
Definition at line 33 of file edgeInterpolationScheme.C.
References Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, FatalIOErrorInLookup, InfoInFunction, mesh, Foam::nl, and PtrList< T >::PtrList().
Referenced by gaussGrad< Type >::gaussGrad(), and laplacianScheme< Type >::laplacianScheme().
New() [2/2]
template<class Type > Foam::tmp< Foam::edgeInterpolationScheme< Type > > New (const faMesh & mesh, const edgeScalarField & faceFlux, Istream & schemeData) static
Definition at line 76 of file edgeInterpolationScheme.C.
References Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, FatalIOErrorInLookup, and InfoInFunction.
mesh()
template<class Type > const faMesh & mesh () const inline
Definition at line 134 of file edgeInterpolationScheme.H.
Referenced by skewCorrectedEdgeInterpolation< Type >::corrected(), skewCorrectedEdgeInterpolation< Type >::correction(), skewCorrectedEdgeInterpolation< Type >::skewCorrection(), leastSquaresEdgeInterpolation< Type >::weights(), and linearEdgeInterpolation< Type >::weights().
interpolate() [1/4]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::faePatchField, Foam::edgeMesh > > interpolate (const GeometricField< Type, faPatchField, areaMesh > & vf, const tmp< edgeScalarField > & tlambdas, const tmp< edgeScalarField > & tys) static
Definition at line 130 of file edgeInterpolationScheme.C.
References InfoInFunction.
Referenced by Foam::linearEdgeInterpolate(), and skewCorrectedEdgeInterpolation< Type >::skewCorrection().
interpolate() [2/4]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::faePatchField, Foam::edgeMesh > > interpolate (const GeometricField< Type, faPatchField, areaMesh > & vf, const tmp< edgeScalarField > & tlambdas) static
Definition at line 249 of file edgeInterpolationScheme.C.
References PtrList< T >::clear(), Foam::endl(), forAll, InfoInFunction, lambda(), mesh, N(), fvMesh::neighbour(), fvMesh::owner(), UPtrList< T >::size(), UList< T >::size(), and Foam::transform().
euclidianInterpolate() [1/2]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::faePatchField, Foam::edgeMesh > > euclidianInterpolate (const GeometricField< Type, faPatchField, areaMesh > & vf, const tmp< edgeScalarField > & tlambdas) static
Definition at line 365 of file edgeInterpolationScheme.C.
References PtrList< T >::clear(), Foam::endl(), forAll, InfoInFunction, lambda(), mesh, N(), fvMesh::neighbour(), fvMesh::owner(), and UList< T >::size().
weights()
template<class Type > virtual tmp< edgeScalarField > weights (const GeometricField< Type, faPatchField, areaMesh > &) const pure virtual
Implemented in leastSquaresEdgeInterpolation< Type >, linearEdgeInterpolation< Type >, faNVDscheme< Type, NVDweight >, upwindEdgeInterpolation< Type >, blendedEdgeInterpolation< Type >, and skewCorrectedEdgeInterpolation< Type >.
corrected()
template<class Type > virtual bool corrected () const inline virtual
Reimplemented in skewCorrectedEdgeInterpolation< Type >.
Definition at line 177 of file edgeInterpolationScheme.H.
correction()
template<class Type > virtual tmp< GeometricField< Type, faePatchField, edgeMesh > > correction (const GeometricField< Type, faPatchField, areaMesh > &) const inline virtual
Reimplemented in skewCorrectedEdgeInterpolation< Type >.
Definition at line 185 of file edgeInterpolationScheme.H.
interpolate() [3/4]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::faePatchField, Foam::edgeMesh > > interpolate (const GeometricField< Type, faPatchField, areaMesh > & vf) const virtual
Reimplemented in leastSquaresEdgeInterpolation< Type >.
Definition at line 441 of file edgeInterpolationScheme.C.
References Foam::correction(), Foam::endl(), InfoInFunction, and Foam::interpolate().
euclidianInterpolate() [2/2]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::faePatchField, Foam::edgeMesh > > euclidianInterpolate (const GeometricField< Type, faPatchField, areaMesh > & vf) const virtual
Definition at line 470 of file edgeInterpolationScheme.C.
References Foam::endl(), and InfoInFunction.
interpolate() [4/4]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::faePatchField, Foam::edgeMesh > > interpolate (const tmp< GeometricField< Type, faPatchField, areaMesh > > & tvf) const
Definition at line 494 of file edgeInterpolationScheme.C.
References PtrList< T >::clear(), and Foam::interpolate().
The documentation for this class was generated from the following files:
src/finiteArea/interpolation/edgeInterpolation/edgeInterpolationScheme/edgeInterpolationScheme.H
src/finiteArea/interpolation/edgeInterpolation/edgeInterpolationScheme/edgeInterpolationScheme.C