OpenFOAM: multiWorldConnections Class Reference
multiWorldConnections Class Reference
Centralized handling of multi-world MPI connections.
#include <multiWorldConnectionsObject.H>
Public Member Functions
TypeName ("multiWorld")
multiWorldConnections (const Time &runTime)
~multiWorldConnections ()
bool empty () const noexcept
label size () const noexcept
void createComms ()
bool addConnectionById (const label otherWorld)
bool addConnectionByName (const word &otherWorld)
label getCommById (const label otherWorld) const
label getCommByName (const word &otherWorld) const
labelList comms () const
Public Member Functions inherited from MeshObject< Time, TopologicalMeshObject, multiWorldConnections >
MeshObject (const Time &mesh)
MeshObject (const word &objName, const Time &mesh)
virtual ~MeshObject ()=default
const Time & mesh () const noexcept
virtual bool writeData (Ostream &os) const
Static Public Member Functions
static const multiWorldConnections & New (const Time &runTime)
Static Public Member Functions inherited from MeshObject< Time, TopologicalMeshObject, multiWorldConnections >
static const multiWorldConnections & New (const Time &mesh, Args &&... args)
static const multiWorldConnections & New (const word &objName, const Time &mesh, Args &&... args)
static bool Delete (const word &objName, const Time &mesh)
static bool Delete (const Time &mesh)
Additional Inherited Members
Protected Attributes inherited from MeshObject< Time, TopologicalMeshObject, multiWorldConnections >
const Time & mesh_
Detailed Description
Centralized handling of multi-world MPI connections.
Note
This class may move to static only or a singleton in the future.
Source files
multiWorldConnectionsObject.H
multiWorldConnectionsObject.C
Definition at line 51 of file multiWorldConnectionsObject.H.
Constructor & Destructor Documentation
multiWorldConnections()
multiWorldConnections (const Time & runTime) explicit
Definition at line 175 of file multiWorldConnectionsObject.C.
~multiWorldConnections()
~multiWorldConnections ()
Definition at line 192 of file multiWorldConnectionsObject.C.
Member Function Documentation
TypeName()
TypeName ("multiWorld")
New()
const Foam::multiWorldConnections & New (const Time & runTime) static
Definition at line 184 of file multiWorldConnectionsObject.C.
References runTime.
Referenced by mappedPatchBase::addWorldConnection(), and mappedPatchBase::getWorldCommunicator().
empty()
bool empty () const noexcept
Definition at line 198 of file multiWorldConnectionsObject.C.
References UPtrList< T >::empty().
size()
Foam::label size () const noexcept
Definition at line 204 of file multiWorldConnectionsObject.C.
References UPtrList< T >::size().
createComms()
void createComms ()
Definition at line 210 of file multiWorldConnectionsObject.C.
References Pstream::combineReduce(), UPstream::commGlobal(), UPstream::commWarn(), UPstream::commWorld(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, UPtrList< T >::first(), forAllConstIters, Foam::Info, UPstream::myWorldID(), UPstream::parRun(), and Foam::printDOT().
Referenced by multiWorldConnections::comms(), multiWorldConnections::getCommById(), and multiWorldConnections::getCommByName().
addConnectionById()
bool addConnectionById (const label otherWorld)
Definition at line 293 of file multiWorldConnectionsObject.C.
References UPstream::myWorld(), Foam::nl, and Foam::Pout.
addConnectionByName()
bool addConnectionByName (const word & otherWorld)
Definition at line 312 of file multiWorldConnectionsObject.C.
References UPstream::myWorld(), Foam::nl, and Foam::Pout.
getCommById()
Foam::label getCommById (const label otherWorld) const
Definition at line 331 of file multiWorldConnectionsObject.C.
References multiWorldConnections::createComms(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, and UPstream::worldComm.
getCommByName()
Foam::label getCommByName (const word & otherWorld) const
Definition at line 372 of file multiWorldConnectionsObject.C.
References multiWorldConnections::createComms(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, and UPstream::worldComm.
comms()
Foam::labelList comms () const
Definition at line 413 of file multiWorldConnectionsObject.C.
References multiWorldConnections::createComms(), UList< T >::empty(), forAllConstIters, List< T >::resize(), Foam::sort(), and UPstream::worldComm.
The documentation for this class was generated from the following files:
src/meshTools/multiWorld/multiWorldConnectionsObject.H
src/meshTools/multiWorld/multiWorldConnectionsObject.C