OpenFOAM: phaseModel Class Reference
phaseModel Class Reference abstract
#include <phaseModel.H>
Public Member Functions
ClassName ("phaseModel")
declareRunTimeSelectionTable (autoPtr, phaseModel, multiphaseInterSystem,(const multiphaseInterSystem &fluid, const word &phaseName),(fluid, phaseName))
phaseModel (const multiphaseInterSystem &fluid, const word &phaseName)
virtual ~phaseModel ()=default
const word & name () const
const multiphaseInterSystem & fluid () const
virtual void correct ()
virtual void correctTurbulence ()
virtual void solveYi (PtrList< volScalarField::Internal > &Su, PtrList< volScalarField::Internal > &Sp)=0
virtual bool read ()
virtual const rhoThermo & thermo () const =0
virtual rhoThermo & thermo ()=0
tmp< volScalarField > rho () const
tmp< scalarField > rho (const label patchi) const
tmp< volScalarField > hc () const
tmp< volScalarField > Cp () const
tmp< scalarField > Cp (const scalarField &p, const scalarField &T, const label patchi) const
tmp< volScalarField > Cv () const
tmp< scalarField > Cv (const scalarField &p, const scalarField &T, const label patchI) const
tmp< volScalarField > gamma () const
tmp< scalarField > gamma (const scalarField &p, const scalarField &T, const label patchi) const
tmp< volScalarField > Cpv () const
tmp< scalarField > Cpv (const scalarField &p, const scalarField &T, const label patchi) const
tmp< volScalarField > CpByCpv () const
tmp< scalarField > CpByCpv (const scalarField &p, const scalarField &T, const label patchi) const
bool dpdt () const
const volScalarField & alpha () const
const scalarField & alpha (const label patchi) const
tmp< volScalarField > kappa () const
tmp< scalarField > kappa (const label patchi) const
tmp< volScalarField > alphahe () const
tmp< scalarField > alphahe (const label patchi) const
tmp< volScalarField > kappaEff (const volScalarField &) const
tmp< scalarField > kappaEff (const scalarField &alphat, const label patchi) const
tmp< volScalarField > alphaEff (const volScalarField &alphat) const
tmp< scalarField > alphaEff (const scalarField &alphat, const label patchi) const
virtual tmp< volScalarField > nu () const
virtual tmp< scalarField > nu (const label patchi) const
virtual tmp< volScalarField > mu () const
virtual tmp< scalarField > mu (const label patchi) const
virtual tmp< surfaceScalarField > diffNo () const =0
virtual const PtrList< volScalarField > & Y () const =0
virtual PtrList< volScalarField > & Y ()=0
virtual tmp< surfaceScalarField > phi () const =0
virtual const surfaceScalarField & phi ()=0
virtual tmp< surfaceScalarField > alphaPhi () const =0
virtual surfaceScalarField & alphaPhi ()=0
virtual tmp< volVectorField > U () const =0
Public Member Functions inherited from GeometricField< scalar, fvPatchField, volMesh >
TypeName ("GeometricField")
GeometricField (const IOobject &io, const Mesh &mesh, const dimensionSet &dims, const word &patchFieldType=fvPatchField< scalar >::calculatedType())
GeometricField (const IOobject &io, const Mesh &mesh, const dimensionSet &dims, const wordList &wantedPatchTypes, const wordList &actualPatchTypes=wordList())
GeometricField (const IOobject &io, const Mesh &mesh, const scalar &value, const dimensionSet &dims, const word &patchFieldType=fvPatchField< scalar >::calculatedType())
GeometricField (const IOobject &io, const Mesh &mesh, const scalar &value, const dimensionSet &dims, const wordList &wantedPatchTypes, const wordList &actualPatchTypes=wordList())
GeometricField (const IOobject &io, const Mesh &mesh, const dimensioned< scalar > &dt, const word &patchFieldType=fvPatchField< scalar >::calculatedType())
GeometricField (const IOobject &io, const Mesh &mesh, const dimensioned< scalar > &dt, const wordList &wantedPatchTypes, const wordList &actualPatchTypes=wordList())
GeometricField (const IOobject &io, const Internal &diField, const PtrList< fvPatchField< scalar > > &ptfl)
GeometricField (const IOobject &io, Internal &&diField, const PtrList< fvPatchField< scalar > > &ptfl)
GeometricField (const IOobject &io, const tmp< Internal > &tfield, const PtrList< fvPatchField< scalar > > &ptfl)
GeometricField (const Internal &diField, const PtrList< fvPatchField< scalar > > &ptfl)
GeometricField (Internal &&diField, const PtrList< fvPatchField< scalar > > &ptfl)
GeometricField (const IOobject &io, const Mesh &mesh, const dimensionSet &dims, const Field< scalar > &iField, const word &patchFieldType=fvPatchField< scalar >::calculatedType())
GeometricField (const IOobject &io, const Mesh &mesh, const dimensionSet &dims, Field< scalar > &&iField, const word &patchFieldType=fvPatchField< scalar >::calculatedType())
GeometricField (const IOobject &io, const Mesh &mesh, const dimensionSet &dims, const Field< scalar > &iField, const PtrList< fvPatchField< scalar > > &ptfl)
GeometricField (const IOobject &io, const Mesh &mesh, const dimensionSet &dims, Field< scalar > &&iField, const PtrList< fvPatchField< scalar > > &ptfl)
GeometricField (const IOobject &io, const Mesh &mesh, const dimensionSet &dims, const tmp< Field< scalar > > &tiField, const PtrList< fvPatchField< scalar > > &ptfl)
GeometricField (const IOobject &io, const Mesh &mesh, const bool readOldTime=true)
GeometricField (const IOobject &io, const Mesh &mesh, const dictionary &dict)
GeometricField (const GeometricField< scalar, fvPatchField, volMesh > &gf)
GeometricField (const tmp< GeometricField< scalar, fvPatchField, volMesh > > &tgf)
GeometricField (const IOobject &io, const GeometricField< scalar, fvPatchField, volMesh > &gf)
GeometricField (const IOobject &io, const tmp< GeometricField< scalar, fvPatchField, volMesh > > &tgf)
GeometricField (const word &newName, const GeometricField< scalar, fvPatchField, volMesh > &gf)
GeometricField (const word &newName, const tmp< GeometricField< scalar, fvPatchField, volMesh > > &tgf)
GeometricField (const IOobject &io, const GeometricField< scalar, fvPatchField, volMesh > &gf, const word &patchFieldType)
GeometricField (const IOobject &io, const GeometricField< scalar, fvPatchField, volMesh > &gf, const labelList &patchIDs, const word &patchFieldType)
GeometricField (const IOobject &io, const GeometricField< scalar, fvPatchField, volMesh > &gf, const wordList &patchFieldTypes, const wordList &actualPatchTypes=wordList())
GeometricField (const IOobject &io, const tmp< GeometricField< scalar, fvPatchField, volMesh > > &tgf, const wordList &patchFieldTypes, const wordList &actualPatchTypes=wordList())
tmp< GeometricField< scalar, fvPatchField, volMesh > > clone () const
Foam::tmp< Foam::GeometricField< scalar, fvPatchField, volMesh > > New (const GeometricField< AnyType, fvPatchField, volMesh > &fld, const word &name, const dimensionSet &dims, const word &patchFieldType)
Foam::tmp< Foam::GeometricField< scalar, fvPatchField, volMesh > > New (const GeometricField< AnyType, fvPatchField, volMesh > &fld, const word &name, const dimensioned< scalar > &dt, const word &patchFieldType)
virtual ~GeometricField ()
const Internal & internalField () const noexcept
Internal & internalFieldRef (const bool updateAccessTime=true)
Internal & ref (const bool updateAccessTime=true)
const Internal & v () const
const Internal::FieldType & primitiveField () const noexcept
Internal::FieldType & primitiveFieldRef (const bool updateAccessTime=true)
const Boundary & boundaryField () const noexcept
Boundary & boundaryFieldRef (const bool updateAccessTime=true)
label timeIndex () const noexcept
label & timeIndex () noexcept
void storeOldTimes () const
void storeOldTime () const
label nOldTimes () const
const GeometricField< scalar, fvPatchField, volMesh > & oldTime () const
GeometricField< scalar, fvPatchField, volMesh > & oldTime ()
void storePrevIter () const
const GeometricField< scalar, fvPatchField, volMesh > & prevIter () const
void correctBoundaryConditions ()
bool needReference () const
tmp< GeometricField< cmptType, fvPatchField, volMesh > > component (const direction) const
tmp< GeometricField< scalar, faPatchField, areaMesh > > component (const direction) const
tmp< GeometricField< scalar, faPatchField, areaMesh > > component (const direction) const
tmp< GeometricField< scalar, fvPatchField, volMesh > > component (const direction) const
tmp< GeometricField< scalar, fvPatchField, volMesh > > component (const direction) const
bool writeData (Ostream &) const
tmp< GeometricField< scalar, fvPatchField, volMesh > > T () const
void relax (const scalar alpha)
void relax ()
word select (bool final) const
void writeMinMax (Ostream &os) const
void negate ()
void normalise ()
void replace (const direction d, const GeometricField< cmptType, fvPatchField, volMesh > &gcf)
void replace (const direction d, const dimensioned< cmptType > &ds)
void replace (const direction, const GeometricField< scalar, faPatchField, areaMesh > &gsf)
void replace (const direction, const GeometricField< scalar, faPatchField, areaMesh > &sf)
void replace (const direction, const GeometricField< scalar, fvPatchField, volMesh > &gsf)
void replace (const direction, const GeometricField< scalar, fvPatchField, volMesh > &sf)
void clamp_min (const scalar &lower)
void clamp_min (const dimensioned< scalar > &lower)
void clamp_max (const scalar &upper)
void clamp_max (const dimensioned< scalar > &upper)
void clamp_range (const dimensioned< MinMax< scalar > > &range)
void clamp_range (const scalar &lower, const scalar &upper)
void clamp_range (const MinMax< scalar > &range)
void clamp_range (const dimensioned< scalar > &lower, const dimensioned< scalar > &upper)
const Internal & operator() () const
void operator= (const GeometricField< scalar, fvPatchField, volMesh > &)
void operator= (const tmp< GeometricField< scalar, fvPatchField, volMesh > > &)
void operator= (const dimensioned< scalar > &)
void operator== (const tmp< GeometricField< scalar, fvPatchField, volMesh > > &)
void operator== (const dimensioned< scalar > &)
void operator+= (const GeometricField< scalar, fvPatchField, volMesh > &)
void operator+= (const tmp< GeometricField< scalar, fvPatchField, volMesh > > &)
void operator+= (const dimensioned< scalar > &)
void operator-= (const GeometricField< scalar, fvPatchField, volMesh > &)
void operator-= (const tmp< GeometricField< scalar, fvPatchField, volMesh > > &)
void operator-= (const dimensioned< scalar > &)
void operator*= (const GeometricField< scalar, fvPatchField, volMesh > &)
void operator*= (const tmp< GeometricField< scalar, fvPatchField, volMesh > > &)
void operator*= (const dimensioned< scalar > &)
void operator/= (const GeometricField< scalar, fvPatchField, volMesh > &)
void operator/= (const tmp< GeometricField< scalar, fvPatchField, volMesh > > &)
void operator/= (const dimensioned< scalar > &)
void clip (const dimensioned< MinMax< scalar > > &range)
void clip (const dimensioned< scalar > &lo, const dimensioned< scalar > &hi)
void min (const dimensioned< scalar > &upper)
void max (const dimensioned< scalar > &lower)
void maxMin (const dimensioned< scalar > &lo, const dimensioned< scalar > &hi)
Public Member Functions inherited from DimensionedField< Type, GeoMesh >
TypeName ("DimensionedField")
DimensionedField (const IOobject &io, const Mesh &mesh, const dimensionSet &dims, const Field< Type > &field)
DimensionedField (const IOobject &io, const Mesh &mesh, const dimensionSet &dims, Field< Type > &&field)
DimensionedField (const IOobject &io, const Mesh &mesh, const dimensionSet &dims, List< Type > &&field)
DimensionedField (const IOobject &io, const Mesh &mesh, const dimensionSet &dims, const tmp< Field< Type > > &tfield)
DimensionedField (const IOobject &io, const Mesh &mesh, const dimensionSet &dims, const bool checkIOFlags=true)
DimensionedField (const IOobject &io, const Mesh &mesh, const Type &value, const dimensionSet &dims, const bool checkIOFlags=true)
DimensionedField (const IOobject &io, const Mesh &mesh, const dimensioned< Type > &dt, const bool checkIOFlags=true)
DimensionedField (const IOobject &io, const Mesh &mesh, const word &fieldDictEntry="value")
DimensionedField (const IOobject &io, const Mesh &mesh, const dictionary &fieldDict, const word &fieldDictEntry="value")
DimensionedField (const DimensionedField< Type, GeoMesh > &df)
DimensionedField (DimensionedField< Type, GeoMesh > &&df)
DimensionedField (DimensionedField< Type, GeoMesh > &df, bool reuse)
DimensionedField (const tmp< DimensionedField< Type, GeoMesh > > &tdf)
DimensionedField (const IOobject &io, const DimensionedField< Type, GeoMesh > &df)
DimensionedField (const IOobject &io, DimensionedField< Type, GeoMesh > &&df)
DimensionedField (const IOobject &io, DimensionedField< Type, GeoMesh > &df, bool reuse)
DimensionedField (const IOobject &io, const tmp< DimensionedField< Type, GeoMesh > > &tdf)
DimensionedField (const word &newName, const DimensionedField< Type, GeoMesh > &df)
DimensionedField (const word &newName, DimensionedField< Type, GeoMesh > &&df)
DimensionedField (const word &newName, DimensionedField< Type, GeoMesh > &df, bool reuse)
DimensionedField (const word &newName, const tmp< DimensionedField< Type, GeoMesh > > &tdf)
tmp< DimensionedField< Type, GeoMesh > > clone () const
virtual ~DimensionedField ()=default
void readField (const dictionary &fieldDict, const word &fieldDictEntry="value")
const Mesh & mesh () const noexcept
const dimensionSet & dimensions () const noexcept
dimensionSet & dimensions () noexcept
orientedType oriented () const noexcept
orientedType & oriented () noexcept
bool is_oriented () const noexcept
void setOriented (bool on=true) noexcept
const Field< Type > & field () const noexcept
Field< Type > & field () noexcept
tmp< DimensionedField< cmptType, GeoMesh > > component (const direction d) const
void replace (const direction d, const DimensionedField< cmptType, GeoMesh > &df)
void replace (const direction d, const tmp< DimensionedField< cmptType, GeoMesh > > &tdf)
tmp< DimensionedField< Type, GeoMesh > > T () const
dimensioned< Type > average () const
dimensioned< Type > weightedAverage (const DimensionedField< scalar, GeoMesh > &weightField) const
dimensioned< Type > weightedAverage (const tmp< DimensionedField< scalar, GeoMesh > > &tweightField) const
bool writeData (Ostream &os, const word &fieldDictEntry) const
void operator= (const DimensionedField< Type, GeoMesh > &df)
void operator= (const tmp< DimensionedField< Type, GeoMesh > > &tdf)
void operator= (const dimensioned< Type > &dt)
void operator+= (const DimensionedField< Type, GeoMesh > &df)
void operator+= (const tmp< DimensionedField< Type, GeoMesh > > &tdf)
void operator-= (const DimensionedField< Type, GeoMesh > &df)
void operator-= (const tmp< DimensionedField< Type, GeoMesh > > &tdf)
void operator*= (const DimensionedField< scalar, GeoMesh > &df)
void operator*= (const tmp< DimensionedField< scalar, GeoMesh > > &tdf)
void operator/= (const DimensionedField< scalar, GeoMesh > &df)
void operator/= (const tmp< DimensionedField< scalar, GeoMesh > > &tdf)
void operator+= (const dimensioned< Type > &dt)
void operator-= (const dimensioned< Type > &dt)
void operator*= (const dimensioned< scalar > &dt)
void operator/= (const dimensioned< scalar > &dt)
const word typeName ("volScalarField::Internal")
const word typeName ("volVectorField::Internal")
const word typeName ("volSphericalTensorField::Internal")
const word typeName ("volSymmTensorField::Internal")
const word typeName ("volTensorField::Internal")
template<class AnyType >
Foam::tmp< Foam::DimensionedField< Type, GeoMesh > > New (const DimensionedField< AnyType, GeoMesh > &fld, const word &name, const dimensionSet &dims)
template<class AnyType >
Foam::tmp< Foam::DimensionedField< Type, GeoMesh > > New (const DimensionedField< AnyType, GeoMesh > &fld, const word &name, const dimensioned< Type > &dt)
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
regIOobject (const IOobject &io, const bool isTimeObject=false)
regIOobject (const regIOobject &rio)
regIOobject (const regIOobject &rio, bool registerCopy)
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
regIOobject (const IOobject &io, const regIOobject &rio)
virtual ~regIOobject ()
bool checkIn ()
bool checkOut ()
virtual void addWatch ()
bool registered () const noexcept
bool ownedByRegistry () const noexcept
bool store ()
void release (const bool unregister=false) noexcept
label eventNo () const noexcept
label & eventNo () noexcept
bool upToDate (const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
void setUpToDate ()
virtual void rename (const word &newName)
const dictionary * findMetaData () const noexcept
dictionary & getMetaData () noexcept
void removeMetaData ()
virtual void updateMetaData ()
virtual fileName filePath () const
bool headerOk ()
Istream & readStream (const word &, const bool readOnProc=true)
void close ()
virtual bool readData (Istream &)
virtual label addWatch (const fileName &)
const labelList & watchIndices () const noexcept
labelList & watchIndices () noexcept
virtual bool modified () const
virtual bool readIfModified ()
virtual bool writeObject (IOstreamOption streamOpt, const bool writeOnProc) const
virtual bool write (const bool writeOnProc=true) const
virtual bool global () const
void operator= (const IOobject &io)
virtual bool writeObject (IOstreamOption::streamFormat fmt, IOstreamOption::versionNumber ver, IOstreamOption::compressionType cmp, const bool writeOnProc) const
Public Member Functions inherited from IOobject
TypeName ("IOobject")
IOobject (const IOobject &)=default
virtual ~IOobject ()=default
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const fileName &path, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const fileName &path, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const IOobject &io, const objectRegistry &registry)
IOobject (const IOobject &io, const word &name)
IOobject (const IOobject &io, const word &name, const fileName &local)
IOobject (const IOobject &io, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt)
IOobject (const IOobject &io, IOobjectOption::registerOption regOpt)
autoPtr< IOobject > clone () const
autoPtr< IOobject > clone (const objectRegistry &registry) const
const objectRegistry & db () const noexcept
const Time & time () const noexcept
const word & name () const noexcept
const word & headerClassName () const noexcept
word & headerClassName () noexcept
const string & note () const noexcept
string & note () noexcept
unsigned labelByteSize () const noexcept
unsigned scalarByteSize () const noexcept
void resetHeader (const word &newName=word::null)
bool hasHeaderClass () const noexcept
template<class Type >
bool isHeaderClass () const
template<class Type >
bool isHeaderClassName () const
word group () const
word member () const
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const noexcept
fileName & instance () noexcept
const fileName & local () const noexcept
fileName path () const
fileName path (const word &instance, const fileName &local=fileName::null) const
fileName objectPath () const
fileName objectRelPath () const
fileName localFilePath (const word &typeName, const bool search=true) const
fileName globalFilePath (const word &typeName, const bool search=true) const
IOstreamOption parseHeader (const dictionary &headerDict)
bool readHeader (Istream &is)
bool readHeader (dictionary &headerDict, Istream &is)
template<class Type >
bool typeHeaderOk (const bool checkType=true, const bool search=true, const bool verbose=true)
template<class Type >
void warnNoRereading () const
bool writeHeader (Ostream &os) const
bool writeHeader (Ostream &os, const word &objectType) const
void writeHeader (dictionary &dict, IOstreamOption streamOpt) const
void writeHeader (dictionary &dict, const word &objectType, IOstreamOption streamOpt) const
bool good () const noexcept
bool bad () const noexcept
InfoProxy< IOobject > info () const noexcept
void operator= (const IOobject &io)
template<>
bool isHeaderClass () const
template<class StringType >
Foam::word groupName (StringType base, const word &group)
Public Member Functions inherited from IOobjectOption
constexpr IOobjectOption (readOption rOpt=readOption::NO_READ, writeOption wOpt=writeOption::NO_WRITE, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (readOption rOpt, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (writeOption wOpt, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (registerOption registerObject, bool globalObject=false) noexcept
constexpr IOobjectOption (readOption rOpt, writeOption wOpt, bool registerObject, bool globalObject=false) noexcept
constexpr IOobjectOption (bool registerObject, bool globalObject=false) noexcept
readOption readOpt () const noexcept
readOption readOpt (readOption opt) noexcept
writeOption writeOpt () const noexcept
writeOption writeOpt (writeOption opt) noexcept
bool registerObject () const noexcept
bool registerObject (bool on) noexcept
bool globalObject () const noexcept
bool globalObject (bool on) noexcept
bool isAnyRead () const noexcept
bool isReadRequired () const noexcept
bool isReadOptional () const noexcept
readOption & readOpt () noexcept
writeOption & writeOpt () noexcept
bool & registerObject () noexcept
bool & globalObject () noexcept
Public Member Functions inherited from Field< Type >
constexpr Field () noexcept
Field (const label len)
Field (const label len, const Type &val)
Field (const label len, const Foam::zero)
Field (const Foam::one, const Type &val)
Field (const Foam::one, Type &&val)
Field (const Foam::one, const Foam::zero)
Field (const Field< Type > &fld)
Field (const UList< Type > &list)
template<class Addr >
Field (const IndirectListBase< Type, Addr > &list)
Field (Field< Type > &&fld)
Field (List< Type > &&list)
template<int SizeMin>
Field (DynamicList< Type, SizeMin > &&list)
Field (const UList< Type > &mapF, const labelUList &mapAddressing)
Field (const tmp< Field< Type > > &tmapF, const labelUList &mapAddressing)
Field (const UList< Type > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Field (const tmp< Field< Type > > &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Field (const UList< Type > &mapF, const FieldMapper &map, const bool applyFlip=true)
Field (const UList< Type > &mapF, const FieldMapper &map, const Type &defaultValue, const bool applyFlip=true)
Field (const UList< Type > &mapF, const FieldMapper &map, const UList< Type > &defaultValues, const bool applyFlip=true)
Field (const tmp< Field< Type > > &tmapF, const FieldMapper &map, const bool applyFlip=true)
Field (const tmp< Field< Type > > &tmapF, const FieldMapper &map, const Type &defaultValue, const bool applyFlip=true)
Field (const tmp< Field< Type > > &tmapF, const FieldMapper &map, const UList< Type > &defaultValues, const bool applyFlip=true)
Field (Field< Type > &fld, bool reuse)
Field (const tmp< Field< Type > > &tfld)
Field (Istream &is)
Field (const entry &e, const label len)
Field (const word &key, const dictionary &dict, const label len, IOobjectOption::readOption readOpt=IOobjectOption::MUST_READ)
tmp< Field< Type > > clone () const
void assign (const entry &e, const label len)
bool assign (const word &key, const dictionary &dict, const label len, IOobjectOption::readOption readOpt=IOobjectOption::MUST_READ)
void map (const UList< Type > &mapF, const labelUList &mapAddressing)
void map (const tmp< Field< Type > > &tmapF, const labelUList &mapAddressing)
void map (const UList< Type > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
void map (const tmp< Field< Type > > &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
void map (const UList< Type > &mapF, const FieldMapper &map, const bool applyFlip=true)
void map (const tmp< Field< Type > > &tmapF, const FieldMapper &map, const bool applyFlip=true)
void autoMap (const FieldMapper &map, const bool applyFlip=true)
void rmap (const UList< Type > &mapF, const labelUList &mapAddressing)
void rmap (const tmp< Field< Type > > &tmapF, const labelUList &mapAddressing)
void rmap (const UList< Type > &mapF, const labelUList &mapAddressing, const UList< scalar > &weights)
void rmap (const tmp< Field< Type > > &tmapF, const labelUList &mapAddressing, const UList< scalar > &weights)
void negate ()
void normalise ()
tmp< Field< cmptType > > component (const direction) const
void replace (const direction, const UList< cmptType > &)
void replace (const direction, const tmp< Field< cmptType > > &)
void replace (const direction, const cmptType &)
void clamp_min (const Type &lower)
void clamp_max (const Type &upper)
void clamp_range (const Type &lower, const Type &upper)
void clamp_range (const MinMax< Type > &range)
template<class VSForm >
VSForm block (const label start) const
tmp< Field< Type > > T () const
void writeEntry (const word &keyword, Ostream &os) const
SubField< Type > slice (const label pos, label len=-1)
const SubField< Type > slice (const label pos, label len=-1) const
SubField< Type > slice (const labelRange &range)
const SubField< Type > slice (const labelRange &range) const
void operator= (const Field< Type > &)
void operator= (const tmp< Field< Type > > &)
void operator= (const UList< Type > &rhs)
void operator= (const SubField< Type > &rhs)
template<class Addr >
void operator= (const IndirectListBase< Type, Addr > &rhs)
void operator= (Field< Type > &&rhs)
void operator= (List< Type > &&rhs)
template<int SizeMin>
void operator= (DynamicList< Type, SizeMin > &&rhs)
void operator= (const Type &val)
void operator= (const Foam::zero)
template<class Form , class Cmpt , direction nCmpt>
void operator= (const VectorSpace< Form, Cmpt, nCmpt > &)
void operator+= (const UList< Type > &)
void operator+= (const tmp< Field< Type > > &)
void operator-= (const UList< Type > &)
void operator-= (const tmp< Field< Type > > &)
void operator*= (const UList< scalar > &)
void operator*= (const tmp< Field< scalar > > &)
void operator/= (const UList< scalar > &)
void operator/= (const tmp< Field< scalar > > &)
void operator+= (const Type &)
void operator-= (const Type &)
void operator*= (const scalar &)
void operator/= (const scalar &)
template<class Type >
void operator= (const tmp< Field > &rhs)
void normalise ()
void normalise ()
void normalise ()
void normalise ()
Public Member Functions inherited from FieldBase
constexpr FieldBase () noexcept
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Public Member Functions inherited from List< Type >
constexpr List () noexcept
List (const label len)
List (const label len, const Type &val)
List (const label len, const Foam::zero)
List (const Foam::one, const Type &val)
List (const Foam::one, Type &&val)
List (const Foam::one, const Foam::zero)
List (const List< Type > &a)
List (const UList< Type > &a)
List (List< Type > &a, bool reuse)
List (const UList< Type > &list, const labelUList &indices)
List (const UList< Type > &list, const FixedList< label, N > &indices)
List (const FixedList< Type, N > &list)
List (const PtrList< Type > &list)
List (const SLList< Type > &list)
List (const IndirectListBase< Type, Addr > &list)
List (std::initializer_list< Type > list)
List (List< Type > &&list)
List (DynamicList< Type, SizeMin > &&list)
List (SLList< Type > &&list)
List (Istream &is)
autoPtr< List< Type > > clone () const
~List ()
void clear ()
void resize (const label len)
void resize (const label len, const Type &val)
void resize (const label newLen)
void resize_nocopy (const label len)
void setSize (const label n)
void setSize (const label n, const Type &val)
void transfer (List< Type > &list)
void transfer (DynamicList< Type, SizeMin > &list)
Type & newElmt (const label i)
Type & emplace_back (Args &&... args)
void push_back (const Type &val)
void push_back (Type &&val)
void push_back (const UList< Type > &list)
void push_back (const IndirectListBase< Type, Addr > &list)
label push_uniq (const Type &val)
void pop_back (label n=1)
void operator= (const UList< Type > &a)
void operator= (const List< Type > &list)
void operator= (const SLList< Type > &list)
void operator= (const IndirectListBase< Type, Addr > &list)
void operator= (const FixedList< Type, N > &list)
void operator= (std::initializer_list< Type > list)
void operator= (const Type &val)
void operator= (const Foam::zero)
void operator= (List< Type > &&list)
void operator= (DynamicList< Type, SizeMin > &&list)
void operator= (SLList< Type > &&list)
Istream & readList (Istream &is)
Istream & readList (Istream &is)
Istream & readList (Istream &is)
void shallowCopy (const UList< Type > &)=delete
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type set (const label i, bool val=true)
void append (const Type &val)
void append (Type &&val)
void append (const UList< Type > &list)
void append (const IndirectListBase< Type, Addr > &list)
label appendUniq (const Type &val)
Public Member Functions inherited from UList< T >
UList (const UList< T > &)=default
constexpr UList () noexcept
UList (T *__restrict__ v, const label len) noexcept
label fcIndex (const label i) const noexcept
label rcIndex (const label i) const noexcept
const T & fcValue (const label i) const
T & fcValue (const label i)
const T & rcValue (const label i) const
T & rcValue (const label i)
const T * cdata () const noexcept
T * data () noexcept
const char * cdata_bytes () const noexcept
char * data_bytes () noexcept
T & front ()
const T & front () const
T & back ()
const T & back () const
std::streamsize size_bytes () const noexcept
std::streamsize byteSize () const
void checkStart (const label start) const
void checkSize (const label size) const
void checkRange (const label start, const label len) const
void checkIndex (const label i) const
bool uniform () const
label find (const T &val, label pos=0) const
label rfind (const T &val, label pos=-1) const
bool contains (const T &val, label pos=0) const
void moveFirst (const label i)
void moveLast (const label i)
void swapFirst (const label i)
void swapLast (const label i)
void shallowCopy (const UList< T > &list)
void deepCopy (const UList< T > &list)
template<class Addr >
void deepCopy (const IndirectListBase< T, Addr > &list)
SubList< T > slice (const label pos, label len=-1)
const SubList< T > slice (const label pos, label len=-1) const
SubList< T > slice (const labelRange &range)
const SubList< T > slice (const labelRange &range) const
T & operator[] (const label i)
const T & operator[] (const label i) const
operator const Foam::List< T > & () const
void operator= (const T &val)
void operator= (const Foam::zero)
iterator begin () noexcept
iterator end () noexcept
iterator begin (const label i) noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
const_iterator begin () const noexcept
const_iterator end () const noexcept
const_iterator cbegin (const label i) const noexcept
const_iterator begin (const label i) const noexcept
reverse_iterator rbegin ()
reverse_iterator rend ()
const_reverse_iterator crbegin () const
const_reverse_iterator crend () const
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
bool empty () const noexcept
label size () const noexcept
void swap (UList< T > &list)
bool operator== (const UList< T > &a) const
bool operator!= (const UList< T > &a) const
bool operator< (const UList< T > &list) const
bool operator> (const UList< T > &a) const
bool operator<= (const UList< T > &a) const
bool operator>= (const UList< T > &a) const
Istream & readList (Istream &is)
void writeEntry (const word &keyword, Ostream &os) const
Ostream & writeList (Ostream &os, const label shortLen=0) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type test (const label i) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type get (const label i) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type unset (const label i)
T & first ()
const T & first () const
T & last ()
const T & last () const
bool found (const T &val, label pos=0) const
Istream & readList (Istream &is)
Ostream & writeList (Ostream &os, const label) const
const bool & operator[] (const label i) const
UPstream::commsStruct & operator[] (const label procID)
const UPstream::commsStruct & operator[] (const label procID) const
Foam::UPstream::commsStruct & operator[] (const label procID)
const Foam::UPstream::commsStruct & operator[] (const label procID) const
Ostream & writeList (Ostream &os, const label) const
Istream & readList (Istream &is)
Static Public Member Functions
static autoPtr< phaseModel > New (const multiphaseInterSystem &fluid, const word &phaseName)
Static Public Member Functions inherited from GeometricField< scalar, fvPatchField, volMesh >
static const GeometricField< scalar, fvPatchField, volMesh > & null ()
static tmp< GeometricField< scalar, fvPatchField, volMesh > > New (const word &name, const Mesh &mesh, const dimensionSet &dims, const word &patchFieldType=fvPatchField< scalar >::calculatedType())
static tmp< GeometricField< scalar, fvPatchField, volMesh > > New (const word &name, const Mesh &mesh, const dimensionSet &dims, const Field< scalar > &iField, const word &patchFieldType=fvPatchField< scalar >::calculatedType())
static tmp< GeometricField< scalar, fvPatchField, volMesh > > New (const word &name, const Mesh &mesh, const dimensionSet &dims, Field< scalar > &&iField, const word &patchFieldType=fvPatchField< scalar >::calculatedType())
static tmp< GeometricField< scalar, fvPatchField, volMesh > > New (const word &name, const Mesh &mesh, const scalar &value, const dimensionSet &dims, const word &patchFieldType=fvPatchField< scalar >::calculatedType())
static tmp< GeometricField< scalar, fvPatchField, volMesh > > New (const word &name, const Mesh &mesh, const scalar &value, const dimensionSet &dims, const wordList &patchFieldTypes, const wordList &actualPatchTypes=wordList())
static tmp< GeometricField< scalar, fvPatchField, volMesh > > New (const word &name, const Mesh &mesh, const dimensioned< scalar > &dt, const word &patchFieldType=fvPatchField< scalar >::calculatedType())
static tmp< GeometricField< scalar, fvPatchField, volMesh > > New (const word &name, const Mesh &mesh, const dimensioned< scalar > &dt, const wordList &patchFieldTypes, const wordList &actualPatchTypes=wordList())
static tmp< GeometricField< scalar, fvPatchField, volMesh > > New (const word &newName, const tmp< GeometricField< scalar, fvPatchField, volMesh > > &tgf)
static tmp< GeometricField< scalar, fvPatchField, volMesh > > New (const word &newName, const tmp< GeometricField< scalar, fvPatchField, volMesh > > &tgf, const word &patchFieldType)
static tmp< GeometricField< scalar, fvPatchField, volMesh > > New (const word &newName, const tmp< GeometricField< scalar, fvPatchField, volMesh > > &tgf, const wordList &patchFieldTypes, const wordList &actualPatchTypes=wordList())
static tmp< GeometricField< scalar, fvPatchField, volMesh > > New (const GeometricField< AnyType, fvPatchField, volMesh > &fld, const word &name, const dimensionSet &dims, const word &patchFieldType=fvPatchField< scalar >::calculatedType())
static tmp< GeometricField< scalar, fvPatchField, volMesh > > New (const GeometricField< AnyType, fvPatchField, volMesh > &fld, const word &name, const dimensioned< scalar > &dt, const word &patchFieldType=fvPatchField< scalar >::calculatedType())
Static Public Member Functions inherited from DimensionedField< Type, GeoMesh >
static const DimensionedField< Type, GeoMesh > & null ()
static tmp< DimensionedField< Type, GeoMesh > > New (const word &name, const Mesh &mesh, const dimensionSet &dims, const Field< Type > &iField)
static tmp< DimensionedField< Type, GeoMesh > > New (const word &name, const Mesh &mesh, const dimensionSet &dims, Field< Type > &&iField)
static tmp< DimensionedField< Type, GeoMesh > > New (const word &name, const Mesh &mesh, const dimensionSet &dims)
static tmp< DimensionedField< Type, GeoMesh > > New (const word &name, const Mesh &mesh, const Type &value, const dimensionSet &dims)
static tmp< DimensionedField< Type, GeoMesh > > New (const word &name, const Mesh &mesh, const dimensioned< Type > &dt)
static tmp< DimensionedField< Type, GeoMesh > > New (const word &newName, const tmp< DimensionedField< Type, GeoMesh > > &tfld)
template<class AnyType >
static tmp< DimensionedField< Type, GeoMesh > > New (const DimensionedField< AnyType, GeoMesh > &fld, const word &name, const dimensionSet &dims)
template<class AnyType >
static tmp< DimensionedField< Type, GeoMesh > > New (const DimensionedField< AnyType, GeoMesh > &fld, const word &name, const dimensioned< Type > &dt)
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *p)
template<class Type >
static Type & store (autoPtr< Type > &ptr)
template<class Type >
static Type & store (autoPtr< Type > &&ptr)
template<class Type >
static Type & store (refPtr< Type > &ptr)
template<class Type >
static Type & store (refPtr< Type > &&ptr)
template<class Type >
static Type & store (tmp< Type > &ptr)
template<class Type >
static Type & store (tmp< Type > &&ptr)
Static Public Member Functions inherited from IOobject
static bool bannerEnabled () noexcept
static bool bannerEnabled (bool on) noexcept
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
template<class StringType >
static word groupName (StringType base, const word &group)
static word group (const word &name)
static word member (const word &name)
static word scopedName (const std::string &scope, const word &name)
static IOobject selectIO (const IOobject &io, const fileName &altFile, const word &ioName="")
static Ostream & writeBanner (Ostream &os, const bool noSyntaxHint=false)
static Ostream & writeDivider (Ostream &os)
static Ostream & writeEndDivider (Ostream &os)
Static Public Member Functions inherited from IOobjectOption
static bool isAnyRead (readOption opt) noexcept
static bool isReadRequired (readOption opt) noexcept
static bool isReadOptional (readOption opt) noexcept
static readOption lazierRead (readOption opt) noexcept
Static Public Member Functions inherited from Field< Type >
static const Field< Type > & null ()
static autoPtr< Field< Type > > New (Istream &is)
template<class Type2 >
static tmp< Field< Type > > NewCalculatedType (const Field< Type2 > &f)
Static Public Member Functions inherited from List< Type >
static const List< Type > & null ()
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
static constexpr label max_size () noexcept
Additional Inherited Members
Public Types inherited from GeometricField< scalar, fvPatchField, volMesh >
typedef GeoMesh::Mesh Mesh
typedef GeoMesh::BoundaryMesh BoundaryMesh
typedef DimensionedField< scalar, volMesh > Internal
typedef GeometricBoundaryField< scalar, fvPatchField, volMesh > Boundary
typedef fvPatchField< scalar > Patch
typedef Field< scalar >::cmptType cmptType
Public Types inherited from DimensionedField< Type, GeoMesh >
typedef GeoMesh::Mesh Mesh
typedef Field< Type > FieldType
typedef Field< Type >::cmptType cmptType
Public Types inherited from IOobject
enum objectState : char { GOOD , BAD }
enum fileCheckTypes : char { timeStamp , timeStampMaster , inotify , inotifyMaster }
Public Types inherited from IOobjectOption
enum readOption : unsigned char {
NO_READ = 0 , MUST_READ = 0x1 , READ_MODIFIED = 0x3 , MUST_READ_IF_MODIFIED = 0x3 ,
LAZY_READ = 0x4 , READ_IF_PRESENT = 0x4
}
enum writeOption : unsigned char { NO_WRITE = 0 , AUTO_WRITE = 0x10 }
enum registerOption : unsigned char { NO_REGISTER = 0 , REGISTER = 1 }
Public Types inherited from Field< Type >
typedef pTraits< Type >::cmptType cmptType
typedef SubField< Type > subField
Public Types inherited from List< Type >
typedef SubList< Type > subList
Public Types inherited from UList< T >
typedef T value_type
typedef T * pointer
typedef const T * const_pointer
typedef T & reference
typedef const T & const_reference
typedef T * iterator
typedef const T * const_iterator
typedef label size_type
typedef label difference_type
typedef std::reverse_iterator< iterator > reverse_iterator
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
Static Public Attributes inherited from IOobject
static const Enum< fileCheckTypes > fileCheckTypesNames
static char scopeSeparator
static fileCheckTypes fileModificationChecking
static float fileModificationSkew
static int maxFileModificationPolls
Static Public Attributes inherited from FieldBase
static const char *const typeName
static bool allowConstructFromLargerSize = false
Protected Member Functions inherited from regIOobject
bool readHeaderOk (const IOstreamOption::streamFormat fmt, const word &typeName)
Protected Member Functions inherited from IOobject
void setBad (const string &s)
Protected Member Functions inherited from UList< T >
void setAddressableSize (const label n) noexcept
void size (const label n)
void writeEntry (Ostream &os) const
labelRange validateRange (const labelRange &requestedRange) const
UList< T > & operator= (const UList< T > &)=delete
void writeEntry (Ostream &os) const
void writeEntry (Ostream &os) const
Static Protected Member Functions inherited from IOobject
static void writeHeaderContent (Ostream &os, const IOobject &io, const word &objectType, const dictionary *metaDataDict=nullptr)
static void writeHeaderContent (dictionary &dict, const IOobject &io, const word &objectType, IOstreamOption streamOpt, const dictionary *metaDataDict=nullptr)
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
Detailed Description
Definition at line 56 of file phaseModel.H.
Constructor & Destructor Documentation
phaseModel()
phaseModel (const multiphaseInterSystem & fluid, const word & phaseName)
Definition at line 37 of file phaseModel.C.
References Foam::dimless.
~phaseModel()
virtual ~phaseModel () virtual default
Member Function Documentation
ClassName()
ClassName ("phaseModel")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , phaseModel , multiphaseInterSystem , (const multiphaseInterSystem &fluid, const word &phaseName) , (fluid, phaseName))
New()
Foam::autoPtr< Foam::multiphaseInter::phaseModel > New (const multiphaseInterSystem & fluid, const word & phaseName) static
Definition at line 64 of file phaseModel.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, fluid, Foam::Info, and dictionary::subDict().
Referenced by multiphaseInterSystem::generatePhaseModels().
name()
const word & name () const inline
Definition at line 110 of file phaseModel.H.
Referenced by StaticPhaseModel< BasePhaseModel >::alphaPhi(), MovingPhaseModel< BasePhaseModel >::diffNo(), StaticPhaseModel< BasePhaseModel >::phi(), multiphaseSystem::solveAlphas(), and StaticPhaseModel< BasePhaseModel >::U().
fluid()
const Foam::multiphaseInterSystem & fluid () const
Definition at line 97 of file phaseModel.C.
correct()
void correct () virtual
Definition at line 103 of file phaseModel.C.
correctTurbulence()
void correctTurbulence () virtual
Definition at line 109 of file phaseModel.C.
solveYi()
virtual void solveYi (PtrList< volScalarField::Internal > & Su, PtrList< volScalarField::Internal > & Sp) pure virtual
read()
bool read () virtual
Reimplemented from regIOobject.
Definition at line 325 of file phaseModel.C.
thermo() [1/2]
virtual const rhoThermo & thermo () const pure virtual
Referenced by phaseModel::dpdt().
thermo() [2/2]
virtual rhoThermo & thermo () pure virtual
rho() [1/2]
Foam::tmp< Foam::volScalarField > rho () const
Definition at line 115 of file phaseModel.C.
rho() [2/2]
Foam::tmp< Foam::scalarField > rho (const label patchi) const
Definition at line 122 of file phaseModel.C.
hc()
Foam::tmp< Foam::volScalarField > hc () const
Definition at line 128 of file phaseModel.C.
Cp() [1/2]
Foam::tmp< Foam::volScalarField > Cp () const
Definition at line 134 of file phaseModel.C.
Cp() [2/2]
Foam::tmp< Foam::scalarField > Cp (const scalarField & p, const scalarField & T, const label patchi) const
Definition at line 140 of file phaseModel.C.
References Cp, p, and T.
Cv() [1/2]
Foam::tmp< Foam::volScalarField > Cv () const
Definition at line 151 of file phaseModel.C.
Cv() [2/2]
Foam::tmp< Foam::scalarField > Cv (const scalarField & p, const scalarField & T, const label patchI) const
Definition at line 157 of file phaseModel.C.
References p, and T.
gamma() [1/2]
Foam::tmp< Foam::volScalarField > gamma () const
Definition at line 168 of file phaseModel.C.
gamma() [2/2]
Foam::tmp< Foam::scalarField > gamma (const scalarField & p, const scalarField & T, const label patchi) const
Definition at line 174 of file phaseModel.C.
References p, and T.
Cpv() [1/2]
Foam::tmp< Foam::volScalarField > Cpv () const
Definition at line 185 of file phaseModel.C.
Cpv() [2/2]
Foam::tmp< Foam::scalarField > Cpv (const scalarField & p, const scalarField & T, const label patchi) const
Definition at line 191 of file phaseModel.C.
References p, and T.
CpByCpv() [1/2]
Foam::tmp< Foam::volScalarField > CpByCpv () const
Definition at line 202 of file phaseModel.C.
CpByCpv() [2/2]
Foam::tmp< Foam::scalarField > CpByCpv (const scalarField & p, const scalarField & T, const label patchi) const
Definition at line 208 of file phaseModel.C.
References p, and T.
dpdt()
bool dpdt () const inline
Definition at line 210 of file phaseModel.H.
References phaseModel::thermo().
alpha() [1/2]
const Foam::volScalarField & alpha () const
Definition at line 219 of file phaseModel.C.
alpha() [2/2]
const Foam::scalarField & alpha (const label patchi) const
Definition at line 226 of file phaseModel.C.
kappa() [1/2]
Foam::tmp< Foam::volScalarField > kappa () const
Definition at line 232 of file phaseModel.C.
kappa() [2/2]
Foam::tmp< Foam::scalarField > kappa (const label patchi) const
Definition at line 239 of file phaseModel.C.
alphahe() [1/2]
Foam::tmp< Foam::volScalarField > alphahe () const
Definition at line 246 of file phaseModel.C.
alphahe() [2/2]
Foam::tmp< Foam::scalarField > alphahe (const label patchi) const
Definition at line 253 of file phaseModel.C.
kappaEff() [1/2]
Foam::tmp< Foam::volScalarField > kappaEff (const volScalarField & kappat) const
Definition at line 259 of file phaseModel.C.
References kappaEff.
kappaEff() [2/2]
Foam::tmp< Foam::scalarField > kappaEff (const scalarField & alphat, const label patchi) const
Definition at line 270 of file phaseModel.C.
alphaEff() [1/2]
Foam::tmp< Foam::volScalarField > alphaEff (const volScalarField & alphat) const
Definition at line 280 of file phaseModel.C.
References alpha.
alphaEff() [2/2]
Foam::tmp< Foam::scalarField > alphaEff (const scalarField & alphat, const label patchi) const
Definition at line 289 of file phaseModel.C.
References alpha.
nu() [1/2]
Foam::tmp< Foam::volScalarField > nu () const virtual
Definition at line 312 of file phaseModel.C.
nu() [2/2]
Foam::tmp< Foam::scalarField > nu (const label patchi) const virtual
Definition at line 319 of file phaseModel.C.
mu() [1/2]
Foam::tmp< Foam::volScalarField > mu () const virtual
Definition at line 299 of file phaseModel.C.
mu() [2/2]
Foam::tmp< Foam::scalarField > mu (const label patchi) const virtual
Definition at line 306 of file phaseModel.C.
diffNo()
virtual tmp< surfaceScalarField > diffNo () const pure virtual
Y() [1/2]
virtual const PtrList< volScalarField > & Y () const pure virtual
Y() [2/2]
virtual PtrList< volScalarField > & Y () pure virtual
phi() [1/2]
virtual tmp< surfaceScalarField > phi () const pure virtual
phi() [2/2]
virtual const surfaceScalarField & phi () pure virtual
alphaPhi() [1/2]
virtual tmp< surfaceScalarField > alphaPhi () const pure virtual
alphaPhi() [2/2]
virtual surfaceScalarField & alphaPhi () pure virtual
U()
virtual tmp< volVectorField > U () const pure virtual
The documentation for this class was generated from the following files:
src/phaseSystemModels/multiphaseInter/phasesSystem/phaseModel/phaseModel/phaseModel.H
src/phaseSystemModels/multiphaseInter/phasesSystem/phaseModel/phaseModel/phaseModel.C