OpenFOAM: globalIndex Class Reference
globalIndex Class Reference
Calculates a unique integer (label so might not have enough room - 2G max) for processor + local index. E.g.
#include <globalIndex.H>
Classes
class const_iterator
struct gatherNone
struct gatherNonLocal
struct gatherOnly
Public Types
enum accessType : char { OFFSETS , SIZES }
Public Member Functions
globalIndex () noexcept=default
globalIndex (const labelUList &listOffsets)
globalIndex (labelList &&listOffsets)
globalIndex (const labelUList &offsetsOrSizes, enum accessType accType)
globalIndex (const label localSize, const label comm=UPstream::worldComm, const bool parallel=UPstream::parRun())
globalIndex (const globalIndex::gatherNone, const label localSize, const label comm=-1)
globalIndex (const globalIndex::gatherOnly, const label localSize, const label comm=UPstream::worldComm)
globalIndex (const globalIndex::gatherNonLocal, const label localSize, const label comm=UPstream::worldComm)
globalIndex (Istream &is)
bool empty () const
label size () const
label totalSize () const
labelList sizes () const
const labelUList localStarts () const
labelList localSizes () const
label maxSize () const
const labelList & offsets () const noexcept
labelList & offsets () noexcept
label nProcs () const noexcept
labelRange allProcs () const noexcept
labelRange subProcs () const noexcept
void clear ()
void reset (const label localSize, const label comm=UPstream::worldComm, const bool parallel=UPstream::parRun())
void reset (const labelUList &localLens, const bool checkOverflow=false)
void reset (const globalIndex::gatherNone, const label localSize, const label comm=-1)
void reset (const globalIndex::gatherOnly, const label localSize, const label comm=UPstream::worldComm)
void reset (const globalIndex::gatherNonLocal, const label localSize, const label comm=UPstream::worldComm)
void setLocalSize (const label proci, const label len)
label localStart () const
label localSize () const
label maxNonLocalSize () const
labelRange range () const
List< labelRange > ranges () const
bool isLocal (const label i) const
label toGlobal (const label i) const
labelList toGlobal (const labelUList &labels) const
void inplaceToGlobal (labelUList &labels) const
label toLocal (const label i) const
label localStart (const label proci) const
label localSize (const label proci) const
label maxNonLocalSize (const label proci) const
labelRange range (const label proci) const
bool isLocal (const label proci, const label i) const
label toGlobal (const label proci, const label i) const
labelList toGlobal (const label proci, const labelUList &labels) const
void inplaceToGlobal (const label proci, labelUList &labels) const
label toLocal (const label proci, const label i) const
label whichProcID (const label i) const
const_iterator cbegin () const noexcept
const const_iterator cend () const noexcept
const_iterator begin () const noexcept
const const_iterator end () const noexcept
template<class ProcIDsContainer , class Type >
void gather (const label comm, const ProcIDsContainer &procIDs, const UList< Type > &fld, List< Type > &allFld, const int tag=UPstream::msgType(), const UPstream::commsTypes ct=UPstream::commsTypes::nonBlocking) const
template<class ProcIDsContainer , class Type >
void gather (const label comm, const ProcIDsContainer &procIDs, List< Type > &fld, const int tag=UPstream::msgType(), const UPstream::commsTypes ct=UPstream::commsTypes::nonBlocking) const
template<class Type >
void gather (const UList< Type > &sendData, List< Type > &allData, const int tag=UPstream::msgType(), const UPstream::commsTypes=UPstream::commsTypes::nonBlocking, const label comm=UPstream::worldComm) const
template<class Type , class Addr >
void gather (const IndirectListBase< Type, Addr > &sendData, List< Type > &allData, const int tag=UPstream::msgType(), const UPstream::commsTypes=UPstream::commsTypes::nonBlocking, const label comm=UPstream::worldComm) const
template<class Type , class OutputContainer = List<Type>>
OutputContainer gather (const UList< Type > &sendData, const int tag=UPstream::msgType(), const UPstream::commsTypes=UPstream::commsTypes::nonBlocking, const label comm=UPstream::worldComm) const
template<class Type , class Addr , class OutputContainer = List<Type>>
OutputContainer gather (const IndirectListBase< Type, Addr > &sendData, const int tag=UPstream::msgType(), const UPstream::commsTypes=UPstream::commsTypes::nonBlocking, const label comm=UPstream::worldComm) const
template<class Type >
void gatherInplace (List< Type > &fld, const int tag=UPstream::msgType(), const UPstream::commsTypes=UPstream::commsTypes::nonBlocking, const label comm=UPstream::worldComm) const
template<class Type , class OutputContainer = List<Type>>
void mpiGather (const UList< Type > &sendData, OutputContainer &allData, const label comm=UPstream::worldComm, const UPstream::commsTypes=UPstream::commsTypes::nonBlocking, const int tag=UPstream::msgType()) const
template<class Type , class OutputContainer = List<Type>>
OutputContainer mpiGather (const UList< Type > &sendData, const label comm=UPstream::worldComm, const UPstream::commsTypes=UPstream::commsTypes::nonBlocking, const int tag=UPstream::msgType()) const
template<class Type >
void mpiGatherInplace (List< Type > &fld, const label comm=UPstream::worldComm, const UPstream::commsTypes=UPstream::commsTypes::nonBlocking, const int tag=UPstream::msgType()) const
template<class ProcIDsContainer , class Type >
void scatter (const label comm, const ProcIDsContainer &procIDs, const UList< Type > &allFld, UList< Type > &fld, const int tag=UPstream::msgType(), const UPstream::commsTypes ct=UPstream::commsTypes::nonBlocking) const
template<class Type >
void scatter (const UList< Type > &allData, UList< Type > &localData, const int tag=UPstream::msgType(), const UPstream::commsTypes=UPstream::commsTypes::nonBlocking, const label comm=UPstream::worldComm) const
template<class Type , class OutputContainer = List<Type>>
OutputContainer scatter (const UList< Type > &allData, const int tag=UPstream::msgType(), const UPstream::commsTypes=UPstream::commsTypes::nonBlocking, const label comm=UPstream::worldComm) const
template<class Type , class CombineOp >
void get (List< Type > &allFld, const labelUList &globalIds, const CombineOp &cop, const label comm=UPstream::worldComm, const int tag=UPstream::msgType()) const
globalIndex (const label localSize, const globalIndex::gatherNone, const label comm=-1)
globalIndex (const label localSize, const globalIndex::gatherOnly, const label comm=UPstream::worldComm)
globalIndex (const label localSize, const int tag, const label comm, const bool parallel)
void reset (const label localSize, const int tag, const label comm, const bool parallel)
label offset (const label proci) const
void reset (const label localSize, const globalIndex::gatherOnly, const label comm=UPstream::worldComm)
template<class SubListType >
Foam::labelList calcListOffsets (const List< SubListType > &lists, const bool checkOverflow)
Static Public Member Functions
static labelList calcOffsets (const labelUList &localLens, const bool checkOverflow=false)
template<class SubListType >
static labelList calcListOffsets (const List< SubListType > &lists, const bool checkOverflow=false)
static List< labelRange > calcRanges (const labelUList &localLens, const bool checkOverflow=false)
template<class ProcIDsContainer , class Type >
static void gatherValues (const label comm, const ProcIDsContainer &procIDs, const Type &localValue, List< Type > &allValues, const int tag=UPstream::msgType(), const UPstream::commsTypes=UPstream::commsTypes::nonBlocking)
template<class ProcIDsContainer , class Type >
static void gather (const labelUList &offsets, const label comm, const ProcIDsContainer &procIDs, const UList< Type > &fld, List< Type > &allFld, const int tag=UPstream::msgType(), const UPstream::commsTypes=UPstream::commsTypes::nonBlocking)
template<class ProcIDsContainer , class Type , class Addr >
static void gather (const labelUList &offsets, const label comm, const ProcIDsContainer &procIDs, const IndirectListBase< Type, Addr > &fld, List< Type > &allFld, const int tag=UPstream::msgType(), const UPstream::commsTypes=UPstream::commsTypes::nonBlocking)
template<class ProcIDsContainer , class Type >
static void gather (const labelUList &offsets, const label comm, const ProcIDsContainer &procIDs, List< Type > &fld, const int tag=UPstream::msgType(), const UPstream::commsTypes ct=UPstream::commsTypes::nonBlocking)
template<class Type , class OutputContainer = List<Type>>
static void mpiGatherOp (const UList< Type > &sendData, OutputContainer &allData, const label comm=UPstream::worldComm, const UPstream::commsTypes=UPstream::commsTypes::nonBlocking, const int tag=UPstream::msgType())
template<class Type , class OutputContainer = List<Type>>
static OutputContainer mpiGatherOp (const UList< Type > &sendData, const label comm=UPstream::worldComm, const UPstream::commsTypes=UPstream::commsTypes::nonBlocking, const int tag=UPstream::msgType())
template<class Type >
static void mpiGatherInplaceOp (List< Type > &fld, const label comm=UPstream::worldComm, const UPstream::commsTypes=UPstream::commsTypes::nonBlocking, const int tag=UPstream::msgType())
template<class Type >
static void gatherOp (const UList< Type > &sendData, List< Type > &allData, const int tag=UPstream::msgType(), const UPstream::commsTypes=UPstream::commsTypes::nonBlocking, const label comm=UPstream::worldComm)
template<class Type , class Addr >
static void gatherOp (const IndirectListBase< Type, Addr > &sendData, List< Type > &allData, const int tag=UPstream::msgType(), const UPstream::commsTypes=UPstream::commsTypes::nonBlocking, const label comm=UPstream::worldComm)
template<class Type , class OutputContainer = List<Type>>
static OutputContainer gatherOp (const UList< Type > &sendData, const int tag=UPstream::msgType(), const UPstream::commsTypes=UPstream::commsTypes::nonBlocking, const label comm=UPstream::worldComm)
template<class Type , class Addr , class OutputContainer = List<Type>>
static OutputContainer gatherOp (const IndirectListBase< Type, Addr > &sendData, const int tag=UPstream::msgType(), const UPstream::commsTypes=UPstream::commsTypes::nonBlocking, const label comm=UPstream::worldComm)
template<class Type >
static void gatherInplaceOp (List< Type > &fld, const int tag=UPstream::msgType(), const UPstream::commsTypes=UPstream::commsTypes::nonBlocking, const label comm=UPstream::worldComm)
template<class ProcIDsContainer , class Type >
static void scatter (const labelUList &offsets, const label comm, const ProcIDsContainer &procIDs, const UList< Type > &allFld, UList< Type > &fld, const int tag=UPstream::msgType(), const UPstream::commsTypes=UPstream::commsTypes::nonBlocking)
Friends
Istream & operator>> (Istream &is, globalIndex &gi)
Ostream & operator<< (Ostream &os, const globalIndex &gi)
Detailed Description
Calculates a unique integer (label so might not have enough room - 2G max) for processor + local index. E.g.
globalIndex globalFaces(mesh.nFaces()); label globalFacei = globalFaces.toGlobal(facei);
Source files
globalIndex.H
globalIndex.C
globalIndexI.H
globalIndexTemplates.C
Definition at line 62 of file globalIndex.H.
Member Enumeration Documentation
accessType
enum accessType : char
Enumerator
OFFSETS
SIZES
Definition at line 94 of file globalIndex.H.
Constructor & Destructor Documentation
globalIndex() [1/12]
globalIndex () default noexcept
globalIndex() [2/12]
globalIndex (const labelUList & listOffsets) inline explicit
Definition at line 26 of file globalIndexI.H.
References UPtrList< T >::size().
globalIndex() [3/12]
globalIndex (labelList && listOffsets) inline explicit
Definition at line 38 of file globalIndexI.H.
References PtrList< T >::clear(), UPtrList< T >::size(), and PtrList< T >::transfer().
globalIndex() [4/12]
globalIndex (const labelUList & offsetsOrSizes, enum accessType accType) inline
Definition at line 54 of file globalIndexI.H.
References UPtrList< T >::size().
globalIndex() [5/12]
globalIndex (const label localSize, const label comm = UPstream::worldComm, const bool parallel = UPstream::parRun()) inline explicit
Parameters
comm communicator
parallel use parallel comms
Definition at line 72 of file globalIndexI.H.
globalIndex() [6/12]
globalIndex (const globalIndex::gatherNone , const label localSize, const label comm = -1) inline
Parameters
comm no communicator needed
Definition at line 83 of file globalIndexI.H.
References globalIndex::localSize().
globalIndex() [7/12]
globalIndex (const globalIndex::gatherOnly , const label localSize, const label comm = UPstream::worldComm) inline
Parameters
comm communicator
Definition at line 97 of file globalIndexI.H.
References UPstream::listGatherValues().
globalIndex() [8/12]
globalIndex (const globalIndex::gatherNonLocal , const label localSize, const label comm = UPstream::worldComm) inline
Parameters
comm communicator
Definition at line 109 of file globalIndexI.H.
References UPstream::listGatherValues(), and UPstream::master().
globalIndex() [9/12]
globalIndex (Istream & is) explicit
Definition at line 115 of file globalIndex.C.
globalIndex() [10/12]
globalIndex (const label localSize, const globalIndex::gatherNone , const label comm = -1) inline
Parameters
comm no communicator needed
Definition at line 896 of file globalIndex.H.
globalIndex() [11/12]
globalIndex (const label localSize, const globalIndex::gatherOnly , const label comm = UPstream::worldComm) inline
Definition at line 907 of file globalIndex.H.
globalIndex() [12/12]
globalIndex (const label localSize, const int tag, const label comm, const bool parallel) inline
Definition at line 920 of file globalIndex.H.
References globalIndex::localSize(), and globalIndex::reset().
Member Function Documentation
empty()
bool empty () const inline
Definition at line 130 of file globalIndexI.H.
References UPtrList< T >::back(), and UPtrList< T >::empty().
size()
Foam::label size () const inline
Definition at line 143 of file globalIndexI.H.
totalSize()
Foam::label totalSize () const inline
Definition at line 136 of file globalIndexI.H.
Referenced by particleTracksSampler::nParticle(), and particleTracksSampler::setSampleRate().
sizes()
Foam::labelList sizes () const inline
Definition at line 149 of file globalIndexI.H.
localStarts()
const Foam::labelUList localStarts () const inline
Definition at line 196 of file globalIndexI.H.
References UList< label >::null().
localSizes()
Foam::labelList localSizes () const
Definition at line 271 of file globalIndex.C.
maxSize()
Foam::label maxSize () const inline
Definition at line 230 of file globalIndexI.H.
offsets() [1/2]
const Foam::labelList & offsets () const inline noexcept
Definition at line 178 of file globalIndexI.H.
Referenced by globalIndex::gather().
offsets() [2/2]
Foam::labelList & offsets () inline noexcept
Definition at line 184 of file globalIndexI.H.
nProcs()
Foam::label nProcs () const inline noexcept
Definition at line 155 of file globalIndexI.H.
allProcs()
Foam::labelRange allProcs () const inline noexcept
Definition at line 162 of file globalIndexI.H.
subProcs()
Foam::labelRange subProcs () const inline noexcept
Definition at line 170 of file globalIndexI.H.
Referenced by faBoundaryMesh::checkParallelSync(), polyBoundaryMesh::checkParallelSync(), ZoneMesh< ZoneType, MeshType >::checkParallelSync(), and PatchTools::gatherAndMerge().
clear()
void clear () inline
Definition at line 190 of file globalIndexI.H.
References PtrList< T >::clear().
reset() [1/7]
void reset (const label localSize, const label comm = UPstream::worldComm, const bool parallel = UPstream::parRun())
Parameters
comm communicator
parallel use parallel comms
Definition at line 186 of file globalIndex.C.
References UPstream::allGatherValues(), UPstream::myProcNo(), UPstream::nProcs(), UPstream::parRun(), PtrList< T >::resize(), and Foam::Zero.
Referenced by PatchTools::gatherAndMerge(), globalIndex::globalIndex(), globalIndex::reset(), globalIndex::reset(), particleTracksSampler::reset(), and particleTracksSampler::resetCloud().
reset() [2/7]
void reset (const labelUList & localLens, const bool checkOverflow = false)
Definition at line 221 of file globalIndex.C.
References PtrList< T >::clear(), and UPtrList< T >::size().
reset() [3/7]
void reset (const globalIndex::gatherNone , const label localSize, const label comm = -1) inline
Parameters
comm no communicator needed
Definition at line 364 of file globalIndexI.H.
reset() [4/7]
void reset (const globalIndex::gatherOnly , const label localSize, const label comm = UPstream::worldComm) inline
Parameters
comm communicator
Definition at line 377 of file globalIndexI.H.
References UPstream::listGatherValues().
reset() [5/7]
void reset (const globalIndex::gatherNonLocal , const label localSize, const label comm = UPstream::worldComm) inline
Parameters
comm communicator
Definition at line 389 of file globalIndexI.H.
References UPstream::listGatherValues(), and UPstream::master().
setLocalSize()
void setLocalSize (const label proci, const label len)
Definition at line 253 of file globalIndex.C.
References delta, and UPtrList< T >::size().
localStart() [1/2]
Foam::label localStart () const inline
Definition at line 212 of file globalIndexI.H.
References UPstream::myProcNo().
Referenced by viewFactor::calculate(), GAMGProcAgglomeration::globalCellCells(), lduPrimitiveMesh::globalCellCells(), globalIndex::offset(), Foam::vtk::writeCellSetFaces(), Foam::vtk::writeFaceSet(), internalMeshWriter::writeGeometry(), patchMeshWriter::writeGeometry(), polyWriter::writeLineGeometry(), internalMeshWriter::writePointIDs(), polyWriter::writePolyGeometry(), and patchMeshWriter::writePolys().
localSize() [1/2]
Foam::label localSize () const inline
Definition at line 224 of file globalIndexI.H.
References UPstream::myProcNo().
Referenced by viewFactor::calculate(), mapDistributeBase::exchangeAddressing(), mapDistributeBase::exchangeAddressing(), GAMGProcAgglomeration::globalCellCells(), globalIndex::globalIndex(), globalIndex::globalIndex(), globalIndex::reset(), and globalIndex::reset().
maxNonLocalSize() [1/2]
Foam::label maxNonLocalSize () const inline
Definition at line 237 of file globalIndexI.H.
References UPstream::myProcNo().
range() [1/2]
Foam::labelRange range () const inline
Definition at line 249 of file globalIndexI.H.
References UPstream::myProcNo(), and range.
Referenced by faBoundaryMesh::checkParallelSync(), polyBoundaryMesh::checkParallelSync(), ZoneMesh< ZoneType, MeshType >::checkParallelSync(), and PatchTools::gatherAndMerge().
ranges()
Foam::List< Foam::labelRange > ranges () const
Definition at line 294 of file globalIndex.C.
isLocal() [1/2]
bool isLocal (const label i) const inline
Definition at line 261 of file globalIndexI.H.
References UPstream::myProcNo().
Referenced by mapDistribute::mapDistributeBase(), mapDistribute::mapDistributeBase(), and mapDistributeBase::renumber().
toGlobal() [1/4]
Foam::label toGlobal (const label i) const inline
Definition at line 277 of file globalIndexI.H.
References UPstream::myProcNo().
Referenced by MGridGenGAMGAgglomeration::agglomerate(), viewFactor::calculate(), viewFactor::initialise(), viewFactor::insertMatrixElements(), and oversetFvMeshBase::updateAddressing().
toGlobal() [2/4]
Foam::labelList toGlobal (const labelUList & labels) const inline
Definition at line 296 of file globalIndexI.H.
References UPstream::myProcNo().
inplaceToGlobal() [1/2]
void inplaceToGlobal (labelUList & labels) const inline
Definition at line 320 of file globalIndexI.H.
References UPstream::myProcNo().
Referenced by PatchTools::gatherAndMerge().
toLocal() [1/2]
Foam::label toLocal (const label i) const inline
Definition at line 342 of file globalIndexI.H.
References UPstream::myProcNo().
Referenced by fvMeshPrimitiveLduAddressing::addAddressing(), viewFactor::calculate(), viewFactor::initialise(), mapDistribute::mapDistributeBase(), mapDistributeBase::renumber(), and oversetFvMeshBase::updateAddressing().
localStart() [2/2]
Foam::label localStart (const label proci) const inline
Definition at line 206 of file globalIndexI.H.
localSize() [2/2]
Foam::label localSize (const label proci) const inline
Definition at line 218 of file globalIndexI.H.
maxNonLocalSize() [2/2]
Foam::label maxNonLocalSize (const label proci) const
Definition at line 320 of file globalIndex.C.
References Foam::max().
range() [2/2]
Foam::labelRange range (const label proci) const inline
Definition at line 243 of file globalIndexI.H.
isLocal() [2/2]
bool isLocal (const label proci, const label i) const inline
Definition at line 255 of file globalIndexI.H.
toGlobal() [3/4]
Foam::label toGlobal (const label proci, const label i) const inline
Definition at line 267 of file globalIndexI.H.
toGlobal() [4/4]
Foam::labelList toGlobal (const label proci, const labelUList & labels) const inline
Definition at line 283 of file globalIndexI.H.
inplaceToGlobal() [2/2]
void inplaceToGlobal (const label proci, labelUList & labels) const inline
Definition at line 305 of file globalIndexI.H.
toLocal() [2/2]
Foam::label toLocal (const label proci, const label i) const inline
Definition at line 327 of file globalIndexI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and Foam::nl.
whichProcID()
Foam::label whichProcID (const label i) const inline
Definition at line 348 of file globalIndexI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, Foam::findLower(), and UPstream::myProcNo().
Referenced by fvMeshPrimitiveLduAddressing::addAddressing(), viewFactor::calculate(), viewFactor::initialise(), mapDistribute::mapDistributeBase(), mapDistribute::mapDistributeBase(), mapDistributeBase::renumber(), and oversetFvMeshBase::updateAddressing().
cbegin()
Foam::globalIndex::const_iterator cbegin () const inline noexcept
Definition at line 520 of file globalIndexI.H.
cend()
const Foam::globalIndex::const_iterator cend () const inline noexcept
Definition at line 527 of file globalIndexI.H.
begin()
Foam::globalIndex::const_iterator begin () const inline noexcept
Definition at line 534 of file globalIndexI.H.
end()
const Foam::globalIndex::const_iterator end () const inline noexcept
Definition at line 541 of file globalIndexI.H.
calcOffsets()
Foam::labelList calcOffsets (const labelUList & localLens, const bool checkOverflow = false) static
Definition at line 49 of file globalIndex.C.
References UPtrList< T >::size().
Referenced by GAMGAgglomeration::procAgglomerateRestrictAddressing().
calcListOffsets() [1/2]
template<class SubListType > static labelList calcListOffsets (const List< SubListType > & lists, const bool checkOverflow = false) static
calcRanges()
Foam::List< Foam::labelRange > calcRanges (const labelUList & localLens, const bool checkOverflow = false) static
Definition at line 82 of file globalIndex.C.
References UPtrList< T >::size().
gatherValues()
template<class ProcIDsContainer , class Type > void gatherValues (const label comm, const ProcIDsContainer & procIDs, const Type & localValue, List< Type > & allValues, const int tag = UPstream::msgType(), const UPstream::commsTypes preferredCommsType = UPstream::commsTypes::nonBlocking) static
Parameters
comm communicator
tag output field (master only)
Definition at line 61 of file globalIndexTemplates.C.
References PtrList< T >::clear(), UPstream::myProcNo(), UPstream::nonBlocking, UPstream::nRequests(), UIPstream::read(), UPstream::scheduled, UPtrList< T >::size(), UPstream::waitRequests(), and UOPstream::write().
Referenced by GAMGAgglomeration::procAgglomerateRestrictAddressing().
gather() [1/9]
template<class ProcIDsContainer , class Type > void gather (const labelUList & offsets, const label comm, const ProcIDsContainer & procIDs, const UList< Type > & fld, List< Type > & allFld, const int tag = UPstream::msgType(), const UPstream::commsTypes preferredCommsType = UPstream::commsTypes::nonBlocking) static
Parameters
offsets offsets (master only)
comm communicator
tag output field (master only)
Definition at line 147 of file globalIndexTemplates.C.
References UList< T >::back(), UPtrList< T >::empty(), fld(), UPstream::myProcNo(), UPstream::nonBlocking, UPstream::nRequests(), UIPstream::read(), UPstream::scheduled, UPtrList< T >::size(), UPstream::waitRequests(), and UOPstream::write().
Referenced by faBoundaryMesh::checkParallelSync(), polyBoundaryMesh::checkParallelSync(), ZoneMesh< ZoneType, MeshType >::checkParallelSync(), globalIndex::gather(), globalIndex::gather(), globalIndex::gather(), globalIndex::gather(), globalIndex::gather(), PatchTools::gatherAndMerge(), globalIndex::gatherInplaceOp(), globalIndex::gatherOp(), globalIndex::gatherOp(), debugWriter::mergeField(), globalIndex::mpiGather(), GAMGAgglomeration::procAgglomerateRestrictAddressing(), and GAMGAgglomeration::restrictField().
gather() [2/9]
template<class ProcIDsContainer , class Type , class Addr > void gather (const labelUList & offsets, const label comm, const ProcIDsContainer & procIDs, const IndirectListBase< Type, Addr > & fld, List< Type > & allFld, const int tag = UPstream::msgType(), const UPstream::commsTypes preferredCommsType = UPstream::commsTypes::nonBlocking) static
Parameters
offsets offsets (master only)
comm communicator
tag output field (master only)
Definition at line 249 of file globalIndexTemplates.C.
References UList< T >::back(), UPtrList< T >::empty(), fld(), UPstream::myProcNo(), UPstream::nonBlocking, UPstream::nRequests(), UPstream::scheduled, UPtrList< T >::size(), and UPstream::waitRequests().
gather() [3/9]
template<class ProcIDsContainer , class Type > static void gather (const labelUList & offsets, const label comm, const ProcIDsContainer & procIDs, List< Type > & fld, const int tag = UPstream::msgType(), const UPstream::commsTypes ct = UPstream::commsTypes::nonBlocking) inline static
Parameters
offsets offsets (master only)
comm communicator
fld in/out field
Definition at line 504 of file globalIndex.H.
References fld(), globalIndex::gather(), UPstream::myProcNo(), globalIndex::offsets(), UPtrList< T >::size(), and PtrList< T >::transfer().
gather() [4/9]
template<class ProcIDsContainer , class Type > void gather (const label comm, const ProcIDsContainer & procIDs, const UList< Type > & fld, List< Type > & allFld, const int tag = UPstream::msgType(), const UPstream::commsTypes ct = UPstream::commsTypes::nonBlocking) const inline
Parameters
comm communicator
fld input field
tag output field (master only)
Definition at line 527 of file globalIndex.H.
References fld(), and globalIndex::gather().
gather() [5/9]
template<class ProcIDsContainer , class Type > void gather (const label comm, const ProcIDsContainer & procIDs, List< Type > & fld, const int tag = UPstream::msgType(), const UPstream::commsTypes ct = UPstream::commsTypes::nonBlocking) const inline
Parameters
comm communicator
fld in/out field
Definition at line 544 of file globalIndex.H.
References fld(), and globalIndex::gather().
gather() [6/9]
template<class Type > void gather (const UList< Type > & sendData, List< Type > & allData, const int tag = UPstream::msgType(), const UPstream::commsTypes commsType = UPstream::commsTypes::nonBlocking, const label comm = UPstream::worldComm) const
Parameters
comm communicator
Definition at line 349 of file globalIndexTemplates.C.
References UPstream::allProcs(), PtrList< T >::clear(), globalIndex::gather(), UPstream::master(), and UPstream::parRun().
gather() [7/9]
template<class Type , class Addr > void gather (const IndirectListBase< Type, Addr > & sendData, List< Type > & allData, const int tag = UPstream::msgType(), const UPstream::commsTypes commsType = UPstream::commsTypes::nonBlocking, const label comm = UPstream::worldComm) const
Parameters
comm communicator
Definition at line 385 of file globalIndexTemplates.C.
References UPstream::allProcs(), PtrList< T >::clear(), globalIndex::gather(), UPstream::master(), and UPstream::parRun().
gather() [8/9]
template<class Type , class OutputContainer > OutputContainer gather (const UList< Type > & sendData, const int tag = UPstream::msgType(), const UPstream::commsTypes commsType = UPstream::commsTypes::nonBlocking, const label comm = UPstream::worldComm) const
Parameters
comm communicator
Definition at line 421 of file globalIndexTemplates.C.
gather() [9/9]
template<class Type , class Addr , class OutputContainer > OutputContainer gather (const IndirectListBase< Type, Addr > & sendData, const int tag = UPstream::msgType(), const UPstream::commsTypes commsType = UPstream::commsTypes::nonBlocking, const label comm = UPstream::worldComm) const
Parameters
comm communicator
Definition at line 436 of file globalIndexTemplates.C.
gatherInplace()
template<class Type > void gatherInplace (List< Type > & fld, const int tag = UPstream::msgType(), const UPstream::commsTypes commsType = UPstream::commsTypes::nonBlocking, const label comm = UPstream::worldComm) const
Parameters
comm communicator
Definition at line 451 of file globalIndexTemplates.C.
References PtrList< T >::clear(), fld(), UPstream::master(), UPstream::parRun(), and PtrList< T >::transfer().
Referenced by particleTracksSampler::gatherInplace().
mpiGather() [1/2]
template<class Type , class OutputContainer > void mpiGather (const UList< Type > & sendData, OutputContainer & allData, const label comm = UPstream::worldComm, const UPstream::commsTypes commsType = UPstream::commsTypes::nonBlocking, const int tag = UPstream::msgType()) const
Parameters
comm communicator
Definition at line 478 of file globalIndexTemplates.C.
References UPstream::allProcs(), UPstream::broadcast(), PtrList< T >::clear(), UPstream::gather(), globalIndex::gather(), UPstream::master(), UPstream::parRun(), PtrList< T >::resize(), and UPtrList< T >::size().
Referenced by globalIndex::mpiGatherOp().
mpiGather() [2/2]
template<class Type , class OutputContainer > OutputContainer mpiGather (const UList< Type > & sendData, const label comm = UPstream::worldComm, const UPstream::commsTypes commsType = UPstream::commsTypes::nonBlocking, const int tag = UPstream::msgType()) const
Parameters
comm communicator
Definition at line 642 of file globalIndexTemplates.C.
References globalIndex::mpiGather().
Referenced by globalIndex::mpiGather().
mpiGatherInplace()
template<class Type > void mpiGatherInplace (List< Type > & fld, const label comm = UPstream::worldComm, const UPstream::commsTypes commsType = UPstream::commsTypes::nonBlocking, const int tag = UPstream::msgType()) const
Parameters
comm communicator
Definition at line 658 of file globalIndexTemplates.C.
References PtrList< T >::clear(), fld(), UPstream::master(), UPstream::parRun(), and PtrList< T >::transfer().
mpiGatherOp() [1/2]
template<class Type , class OutputContainer > void mpiGatherOp (const UList< Type > & sendData, OutputContainer & allData, const label comm = UPstream::worldComm, const UPstream::commsTypes commsType = UPstream::commsTypes::nonBlocking, const int tag = UPstream::msgType()) static
Parameters
comm communicator
Definition at line 686 of file globalIndexTemplates.C.
References globalIndex::mpiGather(), UPstream::parRun(), and UPtrList< T >::size().
Referenced by debugWriter::mergeField().
mpiGatherOp() [2/2]
template<class Type , class OutputContainer > OutputContainer mpiGatherOp (const UList< Type > & sendData, const label comm = UPstream::worldComm, const UPstream::commsTypes commsType = UPstream::commsTypes::nonBlocking, const int tag = UPstream::msgType()) static
Parameters
comm communicator
Definition at line 711 of file globalIndexTemplates.C.
mpiGatherInplaceOp()
template<class Type > void mpiGatherInplaceOp (List< Type > & fld, const label comm = UPstream::worldComm, const UPstream::commsTypes commsType = UPstream::commsTypes::nonBlocking, const int tag = UPstream::msgType()) static
Parameters
comm communicator
Definition at line 727 of file globalIndexTemplates.C.
References PtrList< T >::clear(), fld(), UPstream::master(), UPstream::parRun(), and PtrList< T >::transfer().
gatherOp() [1/4]
template<class Type > void gatherOp (const UList< Type > & sendData, List< Type > & allData, const int tag = UPstream::msgType(), const UPstream::commsTypes commsType = UPstream::commsTypes::nonBlocking, const label comm = UPstream::worldComm) static
Parameters
comm communicator
Definition at line 755 of file globalIndexTemplates.C.
References globalIndex::gather(), UPstream::parRun(), and UPtrList< T >::size().
Referenced by coordSet::gatherSort(), and mergedSurf::merge().
gatherOp() [2/4]
template<class Type , class Addr > void gatherOp (const IndirectListBase< Type, Addr > & sendData, List< Type > & allData, const int tag = UPstream::msgType(), const UPstream::commsTypes commsType = UPstream::commsTypes::nonBlocking, const label comm = UPstream::worldComm) static
Parameters
comm communicator
Definition at line 779 of file globalIndexTemplates.C.
References globalIndex::gather(), UPstream::parRun(), and UPtrList< T >::size().
gatherOp() [3/4]
template<class Type , class OutputContainer > OutputContainer gatherOp (const UList< Type > & sendData, const int tag = UPstream::msgType(), const UPstream::commsTypes commsType = UPstream::commsTypes::nonBlocking, const label comm = UPstream::worldComm) static
Parameters
comm communicator
Definition at line 803 of file globalIndexTemplates.C.
gatherOp() [4/4]
template<class Type , class Addr , class OutputContainer > OutputContainer gatherOp (const IndirectListBase< Type, Addr > & sendData, const int tag = UPstream::msgType(), const UPstream::commsTypes commsType = UPstream::commsTypes::nonBlocking, const label comm = UPstream::worldComm) static
Parameters
comm communicator
Definition at line 818 of file globalIndexTemplates.C.
gatherInplaceOp()
template<class Type > void gatherInplaceOp (List< Type > & fld, const int tag = UPstream::msgType(), const UPstream::commsTypes commsType = UPstream::commsTypes::nonBlocking, const label comm = UPstream::worldComm) static
Parameters
comm communicator
Definition at line 833 of file globalIndexTemplates.C.
References fld(), globalIndex::gather(), UPstream::parRun(), and UPtrList< T >::size().
scatter() [1/4]
template<class ProcIDsContainer , class Type > void scatter (const labelUList & offsets, const label comm, const ProcIDsContainer & procIDs, const UList< Type > & allFld, UList< Type > & fld, const int tag = UPstream::msgType(), const UPstream::commsTypes preferredCommsType = UPstream::commsTypes::nonBlocking) static
Parameters
offsets offsets (master only)
comm communicator
Definition at line 852 of file globalIndexTemplates.C.
References UPtrList< T >::empty(), fld(), UPstream::myProcNo(), UPstream::nonBlocking, UPstream::nRequests(), UIPstream::read(), UPstream::scheduled, UPtrList< T >::size(), UPstream::waitRequests(), and UOPstream::write().
Referenced by GAMGAgglomeration::prolongField(), and globalIndex::scatter().
scatter() [2/4]
template<class ProcIDsContainer , class Type > void scatter (const label comm, const ProcIDsContainer & procIDs, const UList< Type > & allFld, UList< Type > & fld, const int tag = UPstream::msgType(), const UPstream::commsTypes ct = UPstream::commsTypes::nonBlocking) const inline
Parameters
comm communicator
Definition at line 829 of file globalIndex.H.
References fld(), and globalIndex::scatter().
scatter() [3/4]
template<class Type > void scatter (const UList< Type > & allData, UList< Type > & localData, const int tag = UPstream::msgType(), const UPstream::commsTypes commsType = UPstream::commsTypes::nonBlocking, const label comm = UPstream::worldComm) const
Parameters
comm communicator
Definition at line 956 of file globalIndexTemplates.C.
References UPstream::allProcs(), and UPstream::parRun().
scatter() [4/4]
template<class Type , class OutputContainer > OutputContainer scatter (const UList< Type > & allData, const int tag = UPstream::msgType(), const UPstream::commsTypes commsType = UPstream::commsTypes::nonBlocking, const label comm = UPstream::worldComm) const
Parameters
comm communicator
Definition at line 988 of file globalIndexTemplates.C.
References UPstream::parRun().
get()
template<class Type , class CombineOp > void get (List< Type > & allFld, const labelUList & globalIds, const CombineOp & cop, const label comm = UPstream::worldComm, const int tag = UPstream::msgType()) const
Parameters
comm communicator
Definition at line 1020 of file globalIndexTemplates.C.
References fld(), UPstream::nonBlocking, UPstream::nProcs(), os(), and UPtrList< T >::size().
reset() [6/7]
void reset (const label localSize, const int tag, const label comm, const bool parallel) inline
Definition at line 934 of file globalIndex.H.
References globalIndex::localSize(), and globalIndex::reset().
offset()
label offset (const label proci) const inline
Definition at line 947 of file globalIndex.H.
References globalIndex::localStart().
reset() [7/7]
void reset (const label localSize, const globalIndex::gatherOnly , const label comm = UPstream::worldComm) inline
Parameters
comm communicator
Definition at line 953 of file globalIndex.H.
References globalIndex::localSize(), and globalIndex::reset().
calcListOffsets() [2/2]
template<class SubListType > Foam::labelList calcListOffsets (const List< SubListType > & lists, const bool checkOverflow)
Definition at line 28 of file globalIndexTemplates.C.
References UPtrList< T >::size().
Friends And Related Symbol Documentation
operator>>
Istream & operator>> (Istream & is, globalIndex & gi) friend
operator<<
Ostream & operator<< (Ostream & os, const globalIndex & gi) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/parallel/globalIndex/globalIndex.H
src/OpenFOAM/parallel/globalIndex/globalIndex.C
src/OpenFOAM/parallel/globalIndex/globalIndexI.H
src/OpenFOAM/parallel/globalIndex/globalIndexTemplates.C