OpenFOAM: lumpedPointMovement Class Reference
lumpedPointMovement Class Reference
The movement driver that describes initial point locations, the current state of the points/rotations, and forwarding to the externalFileCoupler communication coordinator.
#include <lumpedPointMovement.H>
Public Types
enum class outputFormatType { PLAIN , DICTIONARY }
enum scalingType { LENGTH = 0 , FORCE , MOMENT }
Public Member Functions
lumpedPointMovement ()
lumpedPointMovement (const dictionary &dict, label ownerId=-1)
virtual ~lumpedPointMovement ()=default
void readDict (const dictionary &dict)
bool empty () const
label size () const
label ownerId () const
void ownerId (label id)
const externalFileCoupler & coupler () const
externalFileCoupler & coupler ()
bool couplingPending (const label timeIndex) const
void couplingCompleted (const label timeIndex) const
const lumpedPointState & state0 () const
const lumpedPointState & state () const
const point & origin () const
void scalePoints (lumpedPointState &state) const
scalar relax () const
scalar & relax ()
const word & inputName () const
const word & outputName () const
const word & logName () const
lumpedPointState::inputFormatType inputFormat () const
lumpedPointMovement::outputFormatType outputFormat () const
quaternion::eulerOrder rotationOrder () const
bool degrees () const
bool hasPatchControl (const label patchIndex) const
bool hasPatchControl (const polyPatch &pp) const
bool hasInterpolator (const pointPatch &fpatch) const
void checkPatchControl (const polyPatch &pp) const
void setPatchControl (const polyPatch &pp, const wordList &ctrlNames, const pointField &points0)
void setMapping (const polyMesh &mesh, const labelUList &patchIds, const pointField &points0)
void setInterpolator (const pointPatch &fpatch, const pointField &points0)
bool hasMapping () const
bool hasInterpolator (const label patchIndex) const
List< scalar > areas (const polyMesh &pmesh) const
bool forcesAndMoments (const polyMesh &pmesh, List< vector > &forces, List< vector > &moments) const
tmp< pointField > pointsDisplacement (const pointPatch &fpatch, const pointField &points0) const
tmp< pointField > pointsDisplacement (const lumpedPointState &state, const pointPatch &fpatch, const pointField &points0) const
tmp< pointField > pointsPosition (const lumpedPointState &state, const pointPatch &fpatch, const pointField &points0) const
void writeDict (Ostream &os) const
bool writeData (Ostream &os, const UList< vector > &forces, const UList< vector > &moments, const outputFormatType fmt=outputFormatType::PLAIN, const Tuple2< scalar, scalar > *timesWritten=nullptr) const
bool writeData (const UList< vector > &forces, const UList< vector > &moments=List< vector >(), const Tuple2< scalar, scalar > *timesWritten=nullptr) const
bool readState ()
void writeStateVTP (const lumpedPointState &state, const fileName &file) const
void writeStateVTP (const fileName &file) const
void writeForcesAndMomentsVTP (const fileName &file, const UList< vector > &forces, const UList< vector > &moments) const
void writeZonesVTP (const fileName &file, const polyMesh &mesh, const pointField &points0) const
void writeVTP (const fileName &file, const polyMesh &mesh, const pointField &points0) const
void writeVTP (const fileName &file, const lumpedPointState &state, const polyMesh &mesh, const pointField &points0) const
Static Public Attributes
static const Enum< outputFormatType > formatNames
static const Enum< scalingType > scalingNames
static int debug
static const word canonicalName
Detailed Description
The movement driver that describes initial point locations, the current state of the points/rotations, and forwarding to the externalFileCoupler communication coordinator.
The lumpedPointIOMovement class is simply a registered version of the same.
See externalFileCoupler for more information about some of the communication parameters and setup.
Dictionary parameters
Property Description Required Default
points Initial locations of lumped points yes
pointLabels The FEA ids for the points no
origin Shift offset when reading points no (0 0 0)
rotationOrder The Euler rotation order no zxz
degrees Input rotations in degrees no false
relax Relaxation/scaling for updating positions no 1
controllers Motion controllers (dictionary) yes
forces Force settings (dictionary) no
communication Communication settings (dictionary) yes
Parameters for communication dictionary
Property Description Required Default
inputName Name of positions input file yes
outputName Name of forces output file yes
logName Name of log file no movement.log
inputFormat Input format: dictionary/plain yes
outputFormat Output format: dictionary/plain yes
scaleInput Input scaling parameter dictionary no
scaleOutput Output scaling parameter dictionary no
calcFrequency Calculation/coupling frequency no 1
Parameters for optional communication/scaleInput dictionary
Property Description Required Default
length Scaling for input positions no 1
Parameters for optional communication/scaleOutput dictionary
Property Description Required Default
length Scaling for output positions no 1
force Scaling for force no 1
moment Scaling for moment no 1
Parameters for optional forces dictionary
Property Description Required Default
p Name of the pressure field no p
pRef Reference pressure in Pa no 0
rhoRef Reference density for incompressible no 1
Source files
lumpedPointMovement.H
lumpedPointMovement.C
Definition at line 265 of file lumpedPointMovement.H.
Member Enumeration Documentation
outputFormatType
enum class outputFormatType strong
Enumerator
PLAIN
"plain" is a simple ASCII format
DICTIONARY
"dictionary" is the OpenFOAM dictionary format
Definition at line 272 of file lumpedPointMovement.H.
scalingType
enum scalingType
Enumerator
LENGTH
The "length" scaling.
FORCE
The "force" scaling.
MOMENT
The "moment" scaling.
Definition at line 279 of file lumpedPointMovement.H.
Constructor & Destructor Documentation
lumpedPointMovement() [1/2]
lumpedPointMovement ()
lumpedPointMovement() [2/2]
lumpedPointMovement (const dictionary & dict, label ownerId = -1) explicit
~lumpedPointMovement()
virtual ~lumpedPointMovement () virtual default
Member Function Documentation
readDict()
void readDict (const dictionary & dict)
empty()
bool empty () const inline
Definition at line 21 of file lumpedPointMovementI.H.
References lumpedPointState::empty().
size()
Foam::label size () const inline
Definition at line 27 of file lumpedPointMovementI.H.
References UPtrList< T >::size().
ownerId() [1/2]
Foam::label ownerId () const inline
Definition at line 33 of file lumpedPointMovementI.H.
Referenced by lumpedPointIOMovement::lumpedPointIOMovement(), and lumpedPointDisplacementPointPatchVectorField::~lumpedPointDisplacementPointPatchVectorField().
ownerId() [2/2]
void ownerId (label id) inline
Definition at line 39 of file lumpedPointMovementI.H.
coupler() [1/2]
const Foam::externalFileCoupler & coupler () const inline
Definition at line 62 of file lumpedPointMovementI.H.
coupler() [2/2]
Foam::externalFileCoupler & coupler () inline
Definition at line 68 of file lumpedPointMovementI.H.
couplingPending()
bool couplingPending (const label timeIndex) const
couplingCompleted()
void couplingCompleted (const label timeIndex) const
Referenced by lumpedPointDisplacementPointPatchVectorField::updateCoeffs().
state0()
const Foam::lumpedPointState & state0 () const inline
Definition at line 74 of file lumpedPointMovementI.H.
state()
const Foam::lumpedPointState & state () const inline
Definition at line 80 of file lumpedPointMovementI.H.
Referenced by lumpedPointMovement::writeStateVTP().
origin()
const Foam::point & origin () const inline
Definition at line 86 of file lumpedPointMovementI.H.
scalePoints()
void scalePoints (lumpedPointState & state) const inline
Definition at line 92 of file lumpedPointMovementI.H.
References lumpedPointState::scalePoints().
relax() [1/2]
Foam::scalar relax () const inline
Definition at line 101 of file lumpedPointMovementI.H.
relax() [2/2]
Foam::scalar & relax () inline
Definition at line 107 of file lumpedPointMovementI.H.
inputName()
const Foam::word & inputName () const inline
Definition at line 113 of file lumpedPointMovementI.H.
outputName()
const Foam::word & outputName () const inline
Definition at line 119 of file lumpedPointMovementI.H.
logName()
const Foam::word & logName () const inline
Definition at line 125 of file lumpedPointMovementI.H.
inputFormat()
Foam::lumpedPointState::inputFormatType inputFormat () const inline
Definition at line 132 of file lumpedPointMovementI.H.
outputFormat()
Foam::lumpedPointMovement::outputFormatType outputFormat () const inline
Definition at line 139 of file lumpedPointMovementI.H.
rotationOrder()
Foam::quaternion::eulerOrder rotationOrder () const inline
Definition at line 146 of file lumpedPointMovementI.H.
degrees()
bool degrees () const inline
Definition at line 152 of file lumpedPointMovementI.H.
hasPatchControl() [1/2]
bool hasPatchControl (const label patchIndex) const inline
Definition at line 46 of file lumpedPointMovementI.H.
hasPatchControl() [2/2]
bool hasPatchControl (const polyPatch & pp) const
hasInterpolator() [1/2]
bool hasInterpolator (const pointPatch & fpatch) const
checkPatchControl()
void checkPatchControl (const polyPatch & pp) const
setPatchControl()
void setPatchControl (const polyPatch & pp, const wordList & ctrlNames, const pointField & points0)
setMapping()
void setMapping (const polyMesh & mesh, const labelUList & patchIds, const pointField & points0)
setInterpolator()
void setInterpolator (const pointPatch & fpatch, const pointField & points0)
hasMapping()
bool hasMapping () const inline
Definition at line 158 of file lumpedPointMovementI.H.
References UPtrList< T >::empty().
hasInterpolator() [2/2]
bool hasInterpolator (const label patchIndex) const inline
Definition at line 53 of file lumpedPointMovementI.H.
areas()
List< scalar > areas (const polyMesh & pmesh) const
forcesAndMoments()
bool forcesAndMoments (const polyMesh & pmesh, List< vector > & forces, List< vector > & moments) const
pointsDisplacement() [1/2]
tmp< pointField > pointsDisplacement (const pointPatch & fpatch, const pointField & points0) const
pointsDisplacement() [2/2]
tmp< pointField > pointsDisplacement (const lumpedPointState & state, const pointPatch & fpatch, const pointField & points0) const
pointsPosition()
tmp< pointField > pointsPosition (const lumpedPointState & state, const pointPatch & fpatch, const pointField & points0) const
writeDict()
void writeDict (Ostream & os) const
writeData() [1/2]
bool writeData (Ostream & os, const UList< vector > & forces, const UList< vector > & moments, const outputFormatType fmt = outputFormatType::PLAIN, const Tuple2< scalar, scalar > * timesWritten = nullptr) const
writeData() [2/2]
bool writeData (const UList< vector > & forces, const UList< vector > & moments = List< vector >(), const Tuple2< scalar, scalar > * timesWritten = nullptr) const
readState()
bool readState ()
writeStateVTP() [1/2]
void writeStateVTP (const lumpedPointState & state, const fileName & file) const
Definition at line 30 of file lumpedPointMovementWriter.C.
References UList< T >::first(), Foam::identity(), UPstream::master(), List< T >::resize(), UPtrList< T >::size(), and lumpedPointMovement::state().
writeStateVTP() [2/2]
void writeStateVTP (const fileName & file) const
Definition at line 68 of file lumpedPointMovementWriter.C.
writeForcesAndMomentsVTP()
void writeForcesAndMomentsVTP (const fileName & file, const UList< vector > & forces, const UList< vector > & moments) const
Definition at line 74 of file lumpedPointMovementWriter.C.
References Foam::vtk::CONNECTIVITY, format(), Foam::vtk::INLINE_ASCII, UPstream::master(), Foam::vtk::newFormatter(), nPoints, Foam::vtk::NUMBER_OF_POINTS, Foam::vtk::NUMBER_OF_VERTS, Foam::vtk::OFFSETS, os(), Foam::vtk::PIECE, points, Foam::vtk::POINTS, Foam::vtk::POLY_DATA, UPtrList< T >::size(), Foam::vtk::VERTS, Foam::vtk::writeIdentity(), and Foam::vtk::writeList().
writeZonesVTP()
void writeZonesVTP (const fileName & file, const polyMesh & mesh, const pointField & points0) const
Definition at line 209 of file lumpedPointMovementWriter.C.
References polyWriter::beginCellData(), polyMesh::boundaryMesh(), fileWriter::endCellData(), polyMesh::faces(), Foam::vtk::INLINE_ASCII, PrimitivePatch< FaceList, PointField >::localFaces(), PrimitivePatch< FaceList, PointField >::localPoints(), mesh, List< face >::null(), Field< vector >::null(), patches, patchIds, lineWriter::piece(), points0(), pp(), polyWriter::write(), lineWriter::writeGeometry(), writer(), and lineWriter::writeUniform().
writeVTP() [1/2]
void writeVTP (const fileName & file, const polyMesh & mesh, const pointField & points0) const
Definition at line 251 of file lumpedPointMovementWriter.C.
References mesh, and points0().
writeVTP() [2/2]
void writeVTP (const fileName & file, const lumpedPointState & state, const polyMesh & mesh, const pointField & points0) const
Definition at line 262 of file lumpedPointMovementWriter.C.
References polyWriter::beginCellData(), polyWriter::beginPointData(), polyMesh::boundaryMesh(), fileWriter::endCellData(), fileWriter::endPointData(), forAll, Foam::vtk::INLINE_ASCII, PrimitivePatch< FaceList, PointField >::localFaces(), mesh, List< face >::null(), Field< vector >::null(), patches, patchIds, lineWriter::piece(), points0(), pp(), UPtrList< T >::size(), polyWriter::write(), lineWriter::writeGeometry(), writer(), and lineWriter::writeUniform().
Member Data Documentation
formatNames
const Foam::Enum< Foam::lumpedPointMovement::outputFormatType > formatNames static
Definition at line 290 of file lumpedPointMovement.H.
scalingNames
const Foam::Enum< Foam::lumpedPointMovement::scalingType > scalingNames static
Definition at line 293 of file lumpedPointMovement.H.
debug
int debug static
Definition at line 378 of file lumpedPointMovement.H.
Referenced by lumpedPointDisplacementPointPatchVectorField::updateCoeffs().
canonicalName
const Foam::word canonicalName static
Definition at line 381 of file lumpedPointMovement.H.
Referenced by lumpedPointIOMovement::getMovementObject(), and lumpedPointIOMovement::New().
The documentation for this class was generated from the following files:
src/lumpedPointMotion/movement/lumpedPointMovement.H
src/lumpedPointMotion/movement/lumpedPointMovement.C
src/lumpedPointMotion/movement/lumpedPointMovementI.H
src/lumpedPointMotion/movement/lumpedPointMovementWriter.C