OpenFOAM: zoneSubSet Class Reference
zoneSubSet Class Reference
#include <zoneSubSet.H>
Public Member Functions
TypeName ("zoneSubSet")
zoneSubSet (const fvMesh &mesh, const wordRes &zoneSelector, const label nZoneLayers=0)
zoneSubSet (const fvMesh &mesh, const dictionary &dict)
virtual ~zoneSubSet ()=default
const fvMesh & baseMesh () const noexcept
const fvMeshSubset & subsetter () const
fvMeshSubset & subsetter ()
bool useSubMesh () const noexcept
const wordRes & zones () const noexcept
label nLayers () const noexcept
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > mapToZone (const GeometricField< Type, fvPatchField, volMesh > &subVolField) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > mapToZone (const GeometricField< Type, fvPatchField, volMesh > &subVolField) const
Detailed Description
Definition at line 94 of file zoneSubSet.H.
Constructor & Destructor Documentation
zoneSubSet() [1/2]
zoneSubSet (const fvMesh & mesh, const wordRes & zoneSelector, const label nZoneLayers = 0)
Definition at line 99 of file zoneSubSet.C.
zoneSubSet() [2/2]
zoneSubSet (const fvMesh & mesh, const dictionary & dict)
Definition at line 115 of file zoneSubSet.C.
References dict.
~zoneSubSet()
virtual ~zoneSubSet () virtual default
Member Function Documentation
TypeName()
TypeName ("zoneSubSet")
baseMesh()
const fvMesh & baseMesh () const inline noexcept
Definition at line 156 of file zoneSubSet.H.
References fvMeshSubset::baseMesh().
subsetter() [1/2]
const fvMeshSubset & subsetter () const inline
Definition at line 162 of file zoneSubSet.H.
subsetter() [2/2]
fvMeshSubset & subsetter () inline
Definition at line 168 of file zoneSubSet.H.
useSubMesh()
bool useSubMesh () const inline noexcept
Definition at line 174 of file zoneSubSet.H.
References UList< T >::empty().
zones()
const wordRes & zones () const inline noexcept
Definition at line 180 of file zoneSubSet.H.
nLayers()
label nLayers () const inline noexcept
Definition at line 186 of file zoneSubSet.H.
mapToZone() [1/2]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > mapToZone (const GeometricField< Type, fvPatchField, volMesh > & subVolField) const
mapToZone() [2/2]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > mapToZone (const GeometricField< Type, fvPatchField, volMesh > & subVolField) const
Definition at line 27 of file zoneSubSetTemplates.C.
References fvMeshSubset::baseMesh(), fvMeshSubset::cellMap(), forAll, and bitSet::test().
The documentation for this class was generated from the following files:
src/dynamicMesh/zoneSubSet/zoneSubSet.H
src/dynamicMesh/zoneSubSet/zoneSubSet.C
src/dynamicMesh/zoneSubSet/zoneSubSetTemplates.C