OpenFOAM: restrainedHarmonicSpring Class Reference
restrainedHarmonicSpring Class Reference
#include <restrainedHarmonicSpring.H>
Public Member Functions
TypeName ("restrainedHarmonicSpring")
restrainedHarmonicSpring (const word &name, const dictionary &tetherPotentialProperties)
~restrainedHarmonicSpring ()
scalar energy (const vector r) const
vector force (const vector r) const
bool read (const dictionary &tetherPotentialProperties)
Public Member Functions inherited from tetherPotential
TypeName ("tetherPotential")
declareRunTimeSelectionTable (autoPtr, tetherPotential, dictionary,(const word &name, const dictionary &tetherPotentialProperties),(name, tetherPotentialProperties))
tetherPotential (const word &name, const dictionary &tetherPotentialProperties)
virtual ~tetherPotential ()=default
const dictionary & tetherPotentialProperties () const
Additional Inherited Members
Static Public Member Functions inherited from tetherPotential
static autoPtr< tetherPotential > New (const word &name, const dictionary &tetherPotentialProperties)
Protected Member Functions inherited from tetherPotential
tetherPotential (const tetherPotential &)=delete
void operator= (const tetherPotential &)=delete
Protected Attributes inherited from tetherPotential
word name_
dictionary tetherPotentialProperties_
Detailed Description
Source files
restrainedHarmonicSpring.H
restrainedHarmonicSpring.C
Definition at line 48 of file restrainedHarmonicSpring.H.
Constructor & Destructor Documentation
restrainedHarmonicSpring()
restrainedHarmonicSpring (const word & name, const dictionary & tetherPotentialProperties)
Definition at line 45 of file restrainedHarmonicSpring.C.
~restrainedHarmonicSpring()
~restrainedHarmonicSpring () inline
Definition at line 78 of file restrainedHarmonicSpring.H.
Member Function Documentation
TypeName()
TypeName ("restrainedHarmonicSpring")
energy()
scalar energy (const vector r) const virtual
Implements tetherPotential.
Definition at line 68 of file restrainedHarmonicSpring.C.
References Foam::mag(), and Foam::magSqr().
force()
vector force (const vector r) const virtual
Implements tetherPotential.
Definition at line 84 of file restrainedHarmonicSpring.C.
References Foam::mag().
read()
bool read (const dictionary & tetherPotentialProperties) virtual
Implements tetherPotential.
Definition at line 99 of file restrainedHarmonicSpring.C.
References tetherPotential::read(), dictionary::readEntry(), and tetherPotential::tetherPotentialProperties().
The documentation for this class was generated from the following files:
src/lagrangian/molecularDynamics/potential/tetherPotential/derived/restrainedHarmonicSpring/restrainedHarmonicSpring.H
src/lagrangian/molecularDynamics/potential/tetherPotential/derived/restrainedHarmonicSpring/restrainedHarmonicSpring.C