OpenFOAM: LaheyKEpsilon< BasicTurbulenceModel > Class Template Reference
LaheyKEpsilon< BasicTurbulenceModel > Class Template Reference
Turbulence models » RAS turbulence
Continuous-phase k-epsilon model including bubble-generated turbulence.
#include <LaheyKEpsilon.H>
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from kEpsilon< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from linearViscousStress< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("LaheyKEpsilon")
LaheyKEpsilon (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
virtual ~LaheyKEpsilon ()=default
virtual bool read ()
virtual void correct ()
Public Member Functions inherited from kEpsilon< BasicTurbulenceModel >
TypeName ("kEpsilon")
kEpsilon (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
virtual ~kEpsilon ()=default
tmp< volScalarField > DkEff () const
tmp< volScalarField > DepsilonEff () const
virtual tmp< volScalarField > k () const
virtual tmp< volScalarField > epsilon () const
Public Member Functions inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
eddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~eddyViscosity ()=default
virtual tmp< volScalarField > nut () const
virtual tmp< scalarField > nut (const label patchi) const
virtual tmp< volSymmTensorField > R () const
virtual void validate ()
Public Member Functions inherited from linearViscousStress< BasicTurbulenceModel >
linearViscousStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~linearViscousStress ()=default
virtual tmp< volSymmTensorField > devRhoReff () const
virtual tmp< volSymmTensorField > devRhoReff (const volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Protected Member Functions
virtual void correctNut ()
tmp< volScalarField > bubbleG () const
tmp< volScalarField > phaseTransferCoeff () const
virtual tmp< fvScalarMatrix > kSource () const
virtual tmp< fvScalarMatrix > epsilonSource () const
Protected Attributes
dimensionedScalar alphaInversion_
dimensionedScalar Cp_
dimensionedScalar C3_
dimensionedScalar Cmub_
Protected Attributes inherited from kEpsilon< BasicTurbulenceModel >
dimensionedScalar Cmu_
dimensionedScalar C1_
dimensionedScalar C2_
dimensionedScalar C3_
dimensionedScalar sigmak_
dimensionedScalar sigmaEps_
volScalarField k_
volScalarField epsilon_
Protected Attributes inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
volScalarField nut_
Detailed Description
template<class BasicTurbulenceModel>
class Foam::RASModels::LaheyKEpsilon< BasicTurbulenceModel >
Continuous-phase k-epsilon model including bubble-generated turbulence.
Reference:
    Lahey Jr, R. T. (2005).
    The simulation of multidimensional multiphase flows.
    Nuclear Engineering and Design, 235(10), 1043-1060.
The default model coefficients are
    LaheyKEpsilonCoeffs
    {
        Cmu             0.09;
        C1              1.44;
        C2              1.92;
        C3              -0.33;
        sigmak          1.0;
        sigmaEps        1.3;
        Cp              0.25;
        Cmub            0.6;
        alphaInversion  0.3;
    }
Source files
LaheyKEpsilon.H
LaheyKEpsilon.C
Definition at line 76 of file LaheyKEpsilon.H.
Member Typedef Documentation
alphaField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 127 of file LaheyKEpsilon.H.
rhoField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 128 of file LaheyKEpsilon.H.
transportModel
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 129 of file LaheyKEpsilon.H.
Constructor & Destructor Documentation
LaheyKEpsilon()
template<class BasicTurbulenceModel > LaheyKEpsilon (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Definition at line 37 of file LaheyKEpsilon.C.
References Foam::type().
~LaheyKEpsilon()
template<class BasicTurbulenceModel > virtual ~LaheyKEpsilon () virtual default
Member Function Documentation
correctNut()
template<class BasicTurbulenceModel > void correctNut () protected virtual
Reimplemented from kEpsilon< BasicTurbulenceModel >.
Definition at line 162 of file LaheyKEpsilon.C.
References Foam::mag(), options::New(), and Foam::sqr().
bubbleG()
template<class BasicTurbulenceModel > tmp< volScalarField > bubbleG () const protected
Definition at line 180 of file LaheyKEpsilon.C.
References drag, fluid, Foam::mag(), Foam::pow(), and Foam::pow3().
phaseTransferCoeff()
template<class BasicTurbulenceModel > tmp< volScalarField > phaseTransferCoeff () const protected
Definition at line 211 of file LaheyKEpsilon.C.
References alpha, turbulenceModel::epsilon(), turbulenceModel::k(), Foam::max(), Foam::min(), rho, and U.
kSource()
template<class BasicTurbulenceModel > tmp< fvScalarMatrix > kSource () const protected virtual
Reimplemented from kEpsilon< BasicTurbulenceModel >.
Definition at line 229 of file LaheyKEpsilon.C.
References alpha, rho, and Foam::fvm::Sp().
epsilonSource()
template<class BasicTurbulenceModel > tmp< fvScalarMatrix > epsilonSource () const protected virtual
Reimplemented from kEpsilon< BasicTurbulenceModel >.
Definition at line 247 of file LaheyKEpsilon.C.
References alpha, rho, and Foam::fvm::Sp().
TypeName()
template<class BasicTurbulenceModel > TypeName ("LaheyKEpsilon< BasicTurbulenceModel >")
read()
template<class BasicTurbulenceModel > bool read () virtual
Reimplemented from kEpsilon< BasicTurbulenceModel >.
Definition at line 113 of file LaheyKEpsilon.C.
correct()
template<class BasicTurbulenceModel > void correct () virtual
Reimplemented from kEpsilon< BasicTurbulenceModel >.
Definition at line 265 of file LaheyKEpsilon.C.
References kEpsilon< BasicTurbulenceModel >::correct().
Member Data Documentation
alphaInversion_
template<class BasicTurbulenceModel > dimensionedScalar alphaInversion_ protected
Definition at line 110 of file LaheyKEpsilon.H.
Cp_
template<class BasicTurbulenceModel > dimensionedScalar Cp_ protected
Definition at line 111 of file LaheyKEpsilon.H.
C3_
template<class BasicTurbulenceModel > dimensionedScalar C3_ protected
Definition at line 112 of file LaheyKEpsilon.H.
Cmub_
template<class BasicTurbulenceModel > dimensionedScalar Cmub_ protected
Definition at line 113 of file LaheyKEpsilon.H.
The documentation for this class was generated from the following files:
src/TurbulenceModels/phaseCompressible/RAS/LaheyKEpsilon/LaheyKEpsilon.H
src/TurbulenceModels/phaseCompressible/RAS/LaheyKEpsilon/LaheyKEpsilon.C