OpenFOAM: labelBits Class Reference
labelBits Class Reference
A 29bits (or 61bits) integer label with 3bits direction (eg, octant) packed into single label.
#include <labelBits.H>
Public Member Functions
constexpr labelBits () noexcept
labelBits (const label val, const direction bits)
labelBits (Istream &is)
label data () const noexcept
label val () const noexcept
direction bits () const noexcept
void setVal (const label val)
void setBits (const direction bits)
Static Public Member Functions
static constexpr label pack (const label val, const direction bits) noexcept
Friends
bool operator== (const labelBits &a, const labelBits &b)
bool operator!= (const labelBits &a, const labelBits &b)
Istream & operator>> (Istream &is, labelBits &rhs)
Ostream & operator<< (Ostream &os, const labelBits &rhs)
Detailed Description
A 29bits (or 61bits) integer label with 3bits direction (eg, octant) packed into single label.
Definition at line 48 of file labelBits.H.
Constructor & Destructor Documentation
labelBits() [1/3]
constexpr labelBits () inline constexpr noexcept
Definition at line 97 of file labelBits.H.
labelBits() [2/3]
labelBits (const label val, const direction bits) inline
Definition at line 103 of file labelBits.H.
labelBits() [3/3]
labelBits (Istream & is) inline explicit
Definition at line 109 of file labelBits.H.
Member Function Documentation
pack()
static constexpr label pack (const label val, const direction bits) inline static constexpr noexcept
Definition at line 82 of file labelBits.H.
References labelBits::bits(), and labelBits::val().
Referenced by labelBits::setBits(), and labelBits::setVal().
data()
label data () const inline noexcept
Definition at line 118 of file labelBits.H.
val()
label val () const inline noexcept
Definition at line 121 of file labelBits.H.
Referenced by indexedOctreeBase::getContent(), indexedOctreeBase::getNode(), labelBits::pack(), labelBits::setBits(), and labelBits::setVal().
bits()
direction bits () const inline noexcept
Definition at line 124 of file labelBits.H.
Referenced by labelBits::pack(), labelBits::setBits(), and labelBits::setVal().
setVal()
void setVal (const label val) inline
Definition at line 127 of file labelBits.H.
References labelBits::bits(), labelBits::pack(), and labelBits::val().
setBits()
void setBits (const direction bits) inline
Definition at line 133 of file labelBits.H.
References labelBits::bits(), labelBits::pack(), and labelBits::val().
Friends And Related Symbol Documentation
operator==
bool operator== (const labelBits & a, const labelBits & b) friend
Definition at line 142 of file labelBits.H.
operator!=
bool operator!= (const labelBits & a, const labelBits & b) friend
Definition at line 148 of file labelBits.H.
operator>>
Istream & operator>> (Istream & is, labelBits & rhs) friend
Definition at line 157 of file labelBits.H.
operator<<
Ostream & operator<< (Ostream & os, const labelBits & rhs) friend
Definition at line 163 of file labelBits.H.
The documentation for this class was generated from the following file:
src/OpenFOAM/algorithms/indexedOctree/labelBits.H