OpenFOAM: WallLocalSpringSliderDashpot< CloudType > Class Template Reference
WallLocalSpringSliderDashpot< CloudType > Class Template Reference
Forces between particles and walls, interacting with a spring, slider, damper model.
#include <WallLocalSpringSliderDashpot.H>
Public Member Functions
TypeName ("wallLocalSpringSliderDashpot")
WallLocalSpringSliderDashpot (const dictionary &dict, CloudType &cloud)
virtual ~WallLocalSpringSliderDashpot ()=default
scalar volumeFactor () const
virtual scalar pREff (const typename CloudType::parcelType &p) const
virtual bool controlsTimestep () const
virtual label nSubCycles () const
virtual void evaluateWall (typename CloudType::parcelType &p, const List< point > &flatSitePoints, const List< WallSiteData< vector > > &flatSiteData, const List< point > &sharpSitePoints, const List< WallSiteData< vector > > &sharpSiteData) const
Public Member Functions inherited from WallModel< CloudType >
TypeName ("wallModel")
declareRunTimeSelectionTable (autoPtr, WallModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
WallModel (const dictionary &dict, CloudType &owner, const word &type)
virtual ~WallModel ()
const CloudType & owner () const
CloudType & owner ()
const dictionary & dict () const
const dictionary & coeffDict () const
Additional Inherited Members
Static Public Member Functions inherited from WallModel< CloudType >
static autoPtr< WallModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Detailed Description
template<class CloudType>
class Foam::WallLocalSpringSliderDashpot< CloudType >
Forces between particles and walls, interacting with a spring, slider, damper model.
Reference:
    "Lagrangian numerical simulation of plug flow of cohesionless
     particles in a horizontal pipe"
    Tsuji, Y., Tanaka, T., Ishida, T.,
    Powder Technology
    Volume 73, Issue 3, September 1992, pp. 239-250
Definition at line 52 of file WallLocalSpringSliderDashpot.H.
Constructor & Destructor Documentation
WallLocalSpringSliderDashpot()
template<class CloudType > WallLocalSpringSliderDashpot (const dictionary & dict, CloudType & cloud)
Definition at line 168 of file WallLocalSpringSliderDashpot.C.
References PtrList< T >::append(), WallModel< CloudType >::coeffDict(), forAll, UPtrList< T >::get(), Foam::mag(), mesh, Foam::name(), nu, WallModel< CloudType >::owner(), pp(), List< T >::setSize(), PtrList< T >::setSize(), UPtrList< T >::size(), and Foam::sqr().
~WallLocalSpringSliderDashpot()
template<class CloudType > virtual ~WallLocalSpringSliderDashpot () virtual default
Member Function Documentation
TypeName()
template<class CloudType > TypeName ("wallLocalSpringSliderDashpot")
volumeFactor()
template<class CloudType > scalar volumeFactor () const inline
Definition at line 153 of file WallLocalSpringSliderDashpot.H.
pREff()
template<class CloudType > Foam::scalar pREff (const typename CloudType::parcelType & p) const virtual
Implements WallModel< CloudType >.
Definition at line 269 of file WallLocalSpringSliderDashpot.C.
References Foam::cbrt(), and p.
controlsTimestep()
template<class CloudType > bool controlsTimestep () const virtual
Implements WallModel< CloudType >.
Definition at line 284 of file WallLocalSpringSliderDashpot.C.
nSubCycles()
template<class CloudType > Foam::label nSubCycles () const virtual
Implements WallModel< CloudType >.
Definition at line 291 of file WallLocalSpringSliderDashpot.C.
References Foam::pow(), rhoMax, and Foam::sqrt().
evaluateWall()
template<class CloudType > void evaluateWall (typename CloudType::parcelType & p, const List< point > & flatSitePoints, const List< WallSiteData< vector > > & flatSiteData, const List< point > & sharpSitePoints, const List< WallSiteData< vector > > & sharpSiteData) const virtual
Implements WallModel< CloudType >.
Definition at line 316 of file WallLocalSpringSliderDashpot.C.
References forAll, and p.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/Kinematic/CollisionModel/PairCollision/WallModel/WallLocalSpringSliderDashpot/WallLocalSpringSliderDashpot.H
src/lagrangian/intermediate/submodels/Kinematic/CollisionModel/PairCollision/WallModel/WallLocalSpringSliderDashpot/WallLocalSpringSliderDashpot.C