OpenFOAM: cloudSolution Class Reference
cloudSolution Class Reference
Stores all relevant solution info for cloud.
#include <cloudSolution.H>
Public Member Functions
cloudSolution (const fvMesh &mesh)
cloudSolution (const fvMesh &mesh, const dictionary &dict)
cloudSolution (const cloudSolution &cs)
virtual ~cloudSolution ()
void read ()
scalar relaxCoeff (const word &fieldName) const
bool semiImplicit (const word &fieldName) const
const fvMesh & mesh () const
const dictionary & dict () const
const Switch active () const
const Switch transient () const
const Switch steadyState () const
label calcFrequency () const
scalar maxCo () const
label iter () const
label nextIter ()
scalar trackTime () const
scalar deltaTMax () const
const Switch coupled () const
Switch & coupled ()
const Switch cellValueSourceCorrection () const
scalar maxTrackTime () const
const Switch resetSourcesOnStartup () const
const dictionary & sourceTermDict () const
const dictionary & interpolationSchemes () const
const dictionary & integrationSchemes () const
bool solveThisStep () const
bool canEvolve ()
bool log () const
bool output () const
scalar deltaTMax (const scalar trackTime) const
scalar deltaLMax (const scalar lRef) const
Detailed Description
Stores all relevant solution info for cloud.
Source files
cloudSolution.H
cloudSolutionI.H
cloudSolution.C
Definition at line 49 of file cloudSolution.H.
Constructor & Destructor Documentation
cloudSolution() [1/3]
cloudSolution (const fvMesh & mesh)
Definition at line 92 of file cloudSolution.C.
cloudSolution() [2/3]
cloudSolution (const fvMesh & mesh, const dictionary & dict)
Definition at line 28 of file cloudSolution.C.
References Foam::endl(), Foam::Info, cloudSolution::read(), and dictionary::subOrEmptyDict().
cloudSolution() [3/3]
cloudSolution (const cloudSolution & cs)
Definition at line 72 of file cloudSolution.C.
~cloudSolution()
~cloudSolution () virtual
Definition at line 114 of file cloudSolution.C.
Member Function Documentation
read()
void read ()
Definition at line 120 of file cloudSolution.C.
References localEulerDdt::enabled(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, UPtrList< T >::first(), forAll, IOWarningInFunction, dictionary::lookup(), UPtrList< T >::size(), and dictionary::toc().
Referenced by cloudSolution::cloudSolution().
relaxCoeff()
Foam::scalar relaxCoeff (const word & fieldName) const
Definition at line 203 of file cloudSolution.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and forAll.
semiImplicit()
bool semiImplicit (const word & fieldName) const
Definition at line 221 of file cloudSolution.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, UPtrList< T >::first(), and forAll.
mesh()
const Foam::fvMesh & mesh () const inline
Definition at line 21 of file cloudSolutionI.H.
dict()
const Foam::dictionary & dict () const inline
Definition at line 27 of file cloudSolutionI.H.
active()
const Foam::Switch active () const inline
Definition at line 33 of file cloudSolutionI.H.
Referenced by KinematicCloud< CloudType >::KinematicCloud().
transient()
const Foam::Switch transient () const inline
Definition at line 57 of file cloudSolutionI.H.
steadyState()
const Foam::Switch steadyState () const inline
Definition at line 63 of file cloudSolutionI.H.
calcFrequency()
Foam::label calcFrequency () const inline
Definition at line 69 of file cloudSolutionI.H.
maxCo()
Foam::scalar maxCo () const inline
Definition at line 75 of file cloudSolutionI.H.
iter()
Foam::label iter () const inline
Definition at line 81 of file cloudSolutionI.H.
nextIter()
Foam::label nextIter () inline
Definition at line 87 of file cloudSolutionI.H.
trackTime()
Foam::scalar trackTime () const inline
Definition at line 93 of file cloudSolutionI.H.
deltaTMax() [1/2]
Foam::scalar deltaTMax () const inline
Definition at line 99 of file cloudSolutionI.H.
coupled() [1/2]
const Foam::Switch coupled () const inline
Definition at line 111 of file cloudSolutionI.H.
coupled() [2/2]
Foam::Switch & coupled () inline
Definition at line 105 of file cloudSolutionI.H.
cellValueSourceCorrection()
const Foam::Switch cellValueSourceCorrection () const inline
Definition at line 117 of file cloudSolutionI.H.
maxTrackTime()
Foam::scalar maxTrackTime () const inline
Definition at line 123 of file cloudSolutionI.H.
resetSourcesOnStartup()
const Foam::Switch resetSourcesOnStartup () const inline
Definition at line 129 of file cloudSolutionI.H.
Referenced by KinematicCloud< CloudType >::KinematicCloud().
sourceTermDict()
const Foam::dictionary & sourceTermDict () const inline
Definition at line 39 of file cloudSolutionI.H.
interpolationSchemes()
const Foam::dictionary & interpolationSchemes () const inline
Definition at line 45 of file cloudSolutionI.H.
integrationSchemes()
const Foam::dictionary & integrationSchemes () const inline
Definition at line 51 of file cloudSolutionI.H.
solveThisStep()
bool solveThisStep () const
Definition at line 239 of file cloudSolution.C.
canEvolve()
bool canEvolve ()
Definition at line 250 of file cloudSolution.C.
log()
bool log () const
Definition at line 265 of file cloudSolution.C.
output()
bool output () const
Definition at line 274 of file cloudSolution.C.
deltaTMax() [2/2]
Foam::scalar deltaTMax (const scalar trackTime) const
Definition at line 280 of file cloudSolution.C.
References Foam::min().
deltaLMax()
Foam::scalar deltaLMax (const scalar lRef) const
Definition at line 293 of file cloudSolution.C.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/clouds/Templates/KinematicCloud/cloudSolution/cloudSolution.H
src/lagrangian/intermediate/clouds/Templates/KinematicCloud/cloudSolution/cloudSolution.C
src/lagrangian/intermediate/clouds/Templates/KinematicCloud/cloudSolution/cloudSolutionI.H