OpenFOAM: objectiveFlowRatePartition Class Reference
objectiveFlowRatePartition Class Reference
Split inlet flow rate to given percentages at the prescribed outlet patches.
#include <objectiveFlowRatePartition.H>
Public Member Functions
TypeName ("flowRatePartition")
objectiveFlowRatePartition (const fvMesh &mesh, const dictionary &dict, const word &adjointSolverName, const word &primalSolverName)
virtual ~objectiveFlowRatePartition ()=default
scalar J ()
void update_boundarydJdv ()
void update_boundarydJdvn ()
virtual void addHeaderInfo () const
virtual void addHeaderColumns () const
virtual void addColumnValues () const
Public Member Functions inherited from objectiveIncompressible
TypeName ("incompressible")
declareRunTimeSelectionTable (autoPtr, objectiveIncompressible, dictionary,(const fvMesh &mesh, const dictionary &dict, const word &adjointSolverName, const word &primalSolverName),(mesh, dict, adjointSolverName, primalSolverName))
objectiveIncompressible (const fvMesh &mesh, const dictionary &dict, const word &adjointSolverName, const word &primalSolverName)
virtual ~objectiveIncompressible ()=default
virtual void doNormalization ()
const volVectorField & dJdv ()
const volScalarField & dJdp ()
const volScalarField & dJdT ()
const volScalarField & dJdTMvar1 ()
const volScalarField & dJdTMvar2 ()
const fvPatchVectorField & boundarydJdv (const label)
const fvPatchScalarField & boundarydJdvn (const label)
const fvPatchVectorField & boundarydJdvt (const label)
const fvPatchVectorField & boundarydJdp (const label)
const fvPatchScalarField & boundarydJdT (const label)
const fvPatchScalarField & boundarydJdTMvar1 (const label)
const fvPatchScalarField & boundarydJdTMvar2 (const label)
const fvPatchScalarField & boundarydJdnut (const label)
const fvPatchTensorField & boundarydJdGradU (const label)
const boundaryVectorField & boundarydJdv ()
const boundaryScalarField & boundarydJdvn ()
const boundaryVectorField & boundarydJdvt ()
const boundaryVectorField & boundarydJdp ()
const boundaryScalarField & boundarydJdT ()
const boundaryScalarField & boundarydJdTMvar1 ()
const boundaryScalarField & boundarydJdTMvar2 ()
const boundaryScalarField & boundarydJdnut ()
const boundaryTensorField & boundarydJdGradU ()
virtual void update ()
virtual void nullify ()
void allocatedJdTurbulence ()
void checkCellZonesSize (const labelList &zoneIDs) const
void update_dJdTMvar (autoPtr< volScalarField > &dJdTMvarPtr, tmp< volScalarField >(incompressibleAdjoint::adjointRASModel::*JacobianFunc)() const, const volScalarField &JacobianMultiplier, const labelList &zones)
virtual void update_dJdv ()
virtual void update_dJdp ()
virtual void update_dJdT ()
virtual void update_dJdTMvar1 ()
virtual void update_dJdTMvar2 ()
virtual void update_dJdb ()
virtual void update_divDxDbMultiplier ()
virtual void update_gradDxDbMultiplier ()
virtual void update_boundarydJdvt ()
virtual void update_boundarydJdp ()
virtual void update_boundarydJdT ()
virtual void update_boundarydJdTMvar1 ()
virtual void update_boundarydJdTMvar2 ()
virtual void update_boundarydJdnut ()
virtual void update_boundarydJdGradU ()
virtual void update_boundarydJdb ()
virtual void update_dSdbMultiplier ()
virtual void update_dndbMultiplier ()
virtual void update_dxdbMultiplier ()
virtual void update_dxdbDirectMultiplier ()
virtual void update_meanValues ()
virtual bool write (const bool valid=true) const
bool hasdJdv () const
bool hasdJdp () const
bool hasdJdT () const
bool hasdJdTMVar1 () const
bool hasdJdTMVar2 () const
bool hasBoundarydJdv () const
bool hasBoundarydJdvn () const
bool hasBoundarydJdvt () const
bool hasBoundarydJdp () const
bool hasBoundarydJdT () const
bool hasBoundarydJdTMVar1 () const
bool hasBoundarydJdTMVar2 () const
bool hasBoundarydJdnut () const
bool hasBoundarydJdGradU () const
Public Member Functions inherited from objective
TypeName ("objective")
declareRunTimeNewSelectionTable (autoPtr, objective, objective,(const fvMesh &mesh, const dictionary &dict, const word &adjointSolverName, const word &primalSolverName),(mesh, dict, adjointSolverName, primalSolverName))
objective (const fvMesh &mesh, const dictionary &dict, const word &adjointSolverName, const word &primalSolverName)
virtual ~objective ()=default
virtual bool readDict (const dictionary &dict)
scalar JCycle () const
void accumulateJMean (solverControl &solverControl)
void accumulateJMean ()
scalar weight () const
bool normalize () const
bool isWithinIntegrationTime () const
void incrementIntegrationTimes (const scalar timeSpan)
const volScalarField & dJdb ()
const fvPatchVectorField & boundarydJdb (const label)
const fvPatchVectorField & dSdbMultiplier (const label)
const fvPatchVectorField & dndbMultiplier (const label)
const fvPatchVectorField & dxdbMultiplier (const label)
const fvPatchVectorField & dxdbDirectMultiplier (const label)
const vectorField & boundaryEdgeMultiplier (const label patchI, const label edgeI)
const boundaryVectorField & boundarydJdb ()
const boundaryVectorField & dSdbMultiplier ()
const boundaryVectorField & dndbMultiplier ()
const boundaryVectorField & dxdbMultiplier ()
const boundaryVectorField & dxdbDirectMultiplier ()
const vectorField3 & boundaryEdgeMultiplier ()
const volScalarField & divDxDbMultiplier ()
const volTensorField & gradDxDbMultiplier ()
virtual void updateNormalizationFactor ()
virtual void update_boundaryEdgeContribution ()
virtual void writeInstantaneousValue () const
virtual void writeInstantaneousSeparator () const
virtual void writeMeanValue () const
virtual bool writeData (Ostream &os) const
const word & objectiveName () const
bool hasdJdb () const
bool hasBoundarydJdb () const
bool hasdSdbMult () const
bool hasdndbMult () const
bool hasdxdbMult () const
bool hasdxdbDirectMult () const
bool hasBoundaryEdgeContribution () const
bool hasDivDxDbMult () const
bool hasGradDxDbMult () const
bool hasIntegrationStartTime () const
bool hasIntegrationEndTime () const
Public Member Functions inherited from localIOdictionary
localIOdictionary (const IOobject &io, const dictionary *fallback=nullptr)
localIOdictionary (const IOobject &io, const dictionary &dict)
localIOdictionary (const IOobject &io, const word &wantedType, const dictionary *fallback=nullptr)
localIOdictionary (const IOobject &io, Istream &is)
virtual ~localIOdictionary ()=default
virtual bool global () const
virtual fileName filePath () const
Public Member Functions inherited from baseIOdictionary
TypeName ("dictionary")
baseIOdictionary (const baseIOdictionary &)=default
baseIOdictionary (baseIOdictionary &&)=default
virtual ~baseIOdictionary ()=default
baseIOdictionary (const IOobject &io, const dictionary *fallback=nullptr)
baseIOdictionary (const IOobject &io, const dictionary &dict)
baseIOdictionary (const IOobject &io, Istream &is)
const word & name () const
virtual bool readData (Istream &)
void operator= (const baseIOdictionary &rhs)
void operator= (const dictionary &rhs)
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
regIOobject (const IOobject &io, const bool isTimeObject=false)
regIOobject (const regIOobject &rio)
regIOobject (const regIOobject &rio, bool registerCopy)
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
regIOobject (const IOobject &io, const regIOobject &rio)
virtual ~regIOobject ()
bool checkIn ()
bool checkOut ()
virtual void addWatch ()
bool registered () const noexcept
bool ownedByRegistry () const noexcept
bool store ()
void release (const bool unregister=false) noexcept
label eventNo () const noexcept
label & eventNo () noexcept
bool upToDate (const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
void setUpToDate ()
virtual void rename (const word &newName)
const dictionary * findMetaData () const noexcept
dictionary & getMetaData () noexcept
void removeMetaData ()
virtual void updateMetaData ()
bool headerOk ()
Istream & readStream (const word &, const bool readOnProc=true)
void close ()
virtual bool read ()
virtual label addWatch (const fileName &)
const labelList & watchIndices () const noexcept
labelList & watchIndices () noexcept
virtual bool modified () const
virtual bool readIfModified ()
virtual bool writeObject (IOstreamOption streamOpt, const bool writeOnProc) const
void operator= (const IOobject &io)
virtual bool writeObject (IOstreamOption::streamFormat fmt, IOstreamOption::versionNumber ver, IOstreamOption::compressionType cmp, const bool writeOnProc) const
Public Member Functions inherited from IOobject
TypeName ("IOobject")
IOobject (const IOobject &)=default
virtual ~IOobject ()=default
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const fileName &path, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const fileName &path, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const IOobject &io, const objectRegistry &registry)
IOobject (const IOobject &io, const word &name)
IOobject (const IOobject &io, const word &name, const fileName &local)
IOobject (const IOobject &io, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt)
IOobject (const IOobject &io, IOobjectOption::registerOption regOpt)
autoPtr< IOobject > clone () const
autoPtr< IOobject > clone (const objectRegistry &registry) const
const objectRegistry & db () const noexcept
const Time & time () const noexcept
const word & name () const noexcept
const word & headerClassName () const noexcept
word & headerClassName () noexcept
const string & note () const noexcept
string & note () noexcept
unsigned labelByteSize () const noexcept
unsigned scalarByteSize () const noexcept
void resetHeader (const word &newName=word::null)
bool hasHeaderClass () const noexcept
template<class Type >
bool isHeaderClass () const
template<class Type >
bool isHeaderClassName () const
word group () const
word member () const
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const noexcept
fileName & instance () noexcept
const fileName & local () const noexcept
fileName path () const
fileName path (const word &instance, const fileName &local=fileName::null) const
fileName objectPath () const
fileName objectRelPath () const
fileName localFilePath (const word &typeName, const bool search=true) const
fileName globalFilePath (const word &typeName, const bool search=true) const
IOstreamOption parseHeader (const dictionary &headerDict)
bool readHeader (Istream &is)
bool readHeader (dictionary &headerDict, Istream &is)
template<class Type >
bool typeHeaderOk (const bool checkType=true, const bool search=true, const bool verbose=true)
template<class Type >
void warnNoRereading () const
bool writeHeader (Ostream &os) const
bool writeHeader (Ostream &os, const word &objectType) const
void writeHeader (dictionary &dict, IOstreamOption streamOpt) const
void writeHeader (dictionary &dict, const word &objectType, IOstreamOption streamOpt) const
bool good () const noexcept
bool bad () const noexcept
InfoProxy< IOobject > info () const noexcept
void operator= (const IOobject &io)
template<>
bool isHeaderClass () const
template<class StringType >
Foam::word groupName (StringType base, const word &group)
Public Member Functions inherited from IOobjectOption
constexpr IOobjectOption (readOption rOpt=readOption::NO_READ, writeOption wOpt=writeOption::NO_WRITE, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (readOption rOpt, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (writeOption wOpt, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (registerOption registerObject, bool globalObject=false) noexcept
constexpr IOobjectOption (readOption rOpt, writeOption wOpt, bool registerObject, bool globalObject=false) noexcept
constexpr IOobjectOption (bool registerObject, bool globalObject=false) noexcept
readOption readOpt () const noexcept
readOption readOpt (readOption opt) noexcept
writeOption writeOpt () const noexcept
writeOption writeOpt (writeOption opt) noexcept
bool registerObject () const noexcept
bool registerObject (bool on) noexcept
bool globalObject () const noexcept
bool globalObject (bool on) noexcept
bool isAnyRead () const noexcept
bool isReadRequired () const noexcept
bool isReadOptional () const noexcept
readOption & readOpt () noexcept
writeOption & writeOpt () noexcept
bool & registerObject () noexcept
bool & globalObject () noexcept
Public Member Functions inherited from dictionary
ClassName ("dictionary")
dictionary ()
dictionary (const fileName &name)
dictionary (const fileName &name, const dictionary &parentDict, Istream &is, bool keepHeader=false)
dictionary (Istream &is)
dictionary (Istream &is, bool keepHeader)
dictionary (const dictionary &parentDict, const dictionary &dict)
dictionary (const dictionary &dict)
dictionary (const dictionary *dict)
dictionary (const dictionary &parentDict, dictionary &&dict)
dictionary (dictionary &&dict)
autoPtr< dictionary > clone () const
virtual ~dictionary ()
const fileName & name () const noexcept
fileName & name () noexcept
word dictName () const
fileName relativeName (const bool caseTag=false) const
bool isNullDict () const noexcept
const dictionary & parent () const noexcept
const dictionary & topDict () const
label startLineNumber () const
label endLineNumber () const
SHA1Digest digest () const
tokenList tokens () const
const entry * findEntry (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
entry * findEntry (const word &keyword, enum keyType::option matchOpt=keyType::REGEX)
bool found (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
const entry * findScoped (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
const dictionary * findDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
dictionary * findDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX)
bool isDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
const entry & lookupEntry (const word &keyword, enum keyType::option matchOpt) const
ITstream & lookup (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
template<class T >
T get (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
template<class T >
T getOrDefault (const word &keyword, const T &deflt, enum keyType::option matchOpt=keyType::REGEX) const
template<class T >
T getOrAdd (const word &keyword, const T &deflt, enum keyType::option matchOpt=keyType::REGEX)
template<class T >
bool readEntry (const word &keyword, T &val, enum keyType::option matchOpt=keyType::REGEX, IOobjectOption::readOption readOpt=IOobjectOption::MUST_READ) const
template<class T >
bool readIfPresent (const word &keyword, T &val, enum keyType::option matchOpt=keyType::REGEX) const
template<class T , class Predicate >
T getCheck (const word &keyword, const Predicate &pred, enum keyType::option matchOpt=keyType::REGEX) const
template<class T , class Predicate >
T getCheckOrDefault (const word &keyword, const T &deflt, const Predicate &pred, enum keyType::option matchOpt=keyType::REGEX) const
template<class T , class Predicate >
T getCheckOrAdd (const word &keyword, const T &deflt, const Predicate &pred, enum keyType::option matchOpt=keyType::REGEX)
template<class T , class Predicate >
bool readCheck (const word &keyword, T &val, const Predicate &pred, enum keyType::option matchOpt=keyType::REGEX, IOobjectOption::readOption readOpt=IOobjectOption::MUST_READ) const
template<class T , class Predicate >
bool readCheckIfPresent (const word &keyword, T &val, const Predicate &pred, enum keyType::option matchOpt=keyType::REGEX) const
const dictionary & subDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
dictionary & subDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX)
dictionary & subDictOrAdd (const word &keyword, enum keyType::option matchOpt=keyType::REGEX)
dictionary subOrEmptyDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX, const bool mandatory=false) const
const dictionary & optionalSubDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
wordList toc () const
wordList sortedToc () const
template<class Compare >
wordList sortedToc (const Compare &comp) const
List< keyType > keys (bool patterns=false) const
bool substituteKeyword (const word &keyword, bool mergeEntry=false)
bool substituteScopedKeyword (const word &keyword, bool mergeEntry=false)
entry * add (entry *entryPtr, bool mergeEntry=false)
entry * add (const entry &e, bool mergeEntry=false)
entry * add (const keyType &k, const word &v, bool overwrite=false)
entry * add (const keyType &k, const string &v, bool overwrite=false)
entry * add (const keyType &k, const label v, bool overwrite=false)
entry * add (const keyType &k, const scalar v, bool overwrite=false)
entry * add (const keyType &k, const dictionary &d, bool mergeEntry=false)
template<class T >
entry * add (const keyType &k, const T &v, bool overwrite=false)
entry * set (entry *entryPtr)
entry * set (const entry &e)
entry * set (const keyType &k, const dictionary &v)
template<class T >
entry * set (const keyType &k, const T &v)
bool remove (const word &keyword)
bool changeKeyword (const keyType &oldKeyword, const keyType &newKeyword, bool overwrite=false)
bool merge (const dictionary &dict)
void clear ()
void transfer (dictionary &dict)
void checkITstream (const ITstream &is, const word &keyword) const
bool read (Istream &is)
bool read (Istream &is, bool keepHeader)
void writeEntry (Ostream &os) const
void writeEntry (const keyType &keyword, Ostream &os) const
void writeEntries (Ostream &os, const bool extraNewLine=false) const
void write (Ostream &os, const bool subDict=true) const
const_searcher csearch (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
const_searcher search (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
searcher search (const word &keyword, enum keyType::option matchOpt=keyType::REGEX)
const_searcher csearchScoped (const word &keyword, enum keyType::option matchOpt) const
const_searcher searchScoped (const word &keyword, enum keyType::option matchOpt) const
searcher searchScoped (const word &keyword, enum keyType::option matchOpt)
const dictionary * cfindScopedDict (const fileName &dictPath) const
const dictionary * findScopedDict (const fileName &dictPath) const
dictionary * findScopedDict (const fileName &dictPath)
dictionary * makeScopedDict (const fileName &dictPath)
const_searcher csearchCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, enum keyType::option matchOpt=keyType::REGEX) const
const entry * findCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, enum keyType::option matchOpt) const
bool foundCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, enum keyType::option matchOpt=keyType::REGEX) const
const entry & lookupEntryCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, enum keyType::option matchOpt) const
ITstream & lookupCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, enum keyType::option matchOpt=keyType::REGEX) const
template<class T >
T getCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, enum keyType::option matchOpt=keyType::REGEX) const
template<class T >
T getOrDefaultCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, const T &deflt, enum keyType::option matchOpt=keyType::REGEX) const
template<class T >
bool readCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, T &val, enum keyType::option matchOpt=keyType::REGEX, IOobjectOption::readOption readOpt=IOobjectOption::MUST_READ) const
template<class T >
bool readIfPresentCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, T &val, enum keyType::option matchOpt=keyType::REGEX) const
void operator= (const dictionary &rhs)
void operator+= (const dictionary &rhs)
void operator|= (const dictionary &rhs)
void operator<<= (const dictionary &rhs)
bool getBool (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Same as get< bool >(const word&, keyType::option)
label getLabel (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Same as get< label >(const word&, keyType::option)
scalar getScalar (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Same as get< scalar >(const word&, keyType::option)
string getString (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Same as get< string >(const word&, keyType::option)
word getWord (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Same as get< word >(const word&, keyType::option)
fileName getFileName (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Same as get< fileName >(const word&, keyType::option)
template<class T >
T lookupOrDefault (const word &keyword, const T &deflt, enum keyType::option matchOpt=keyType::REGEX) const
template<class T >
T lookupOrAddDefault (const word &keyword, const T &deflt, enum keyType::option matchOpt=keyType::REGEX)
ITstream & operator[] (const word &keyword) const
bool found (const word &keyword, bool recursive, bool patternMatch=true) const
entry * lookupEntryPtr (const word &keyword, bool recursive, bool patternMatch)
const entry * lookupEntryPtr (const word &keyword, bool recursive, bool patternMatch) const
const entry * lookupScopedEntryPtr (const word &keyword, bool recursive, bool patternMatch) const
const dictionary * subDictPtr (const word &keyword) const
dictionary * subDictPtr (const word &keyword)
const entry & lookupEntry (const word &keyword, bool recursive, bool patternMatch) const
ITstream & lookup (const word &keyword, bool recursive, bool patternMatch=true) const
template<class T >
T lookupOrDefault (const word &keyword, const T &deflt, bool recursive, bool patternMatch=true) const
template<class T >
T lookupOrAddDefault (const word &keyword, const T &deflt, bool recursive, bool patternMatch=true)
template<class T >
bool readIfPresent (const word &keyword, T &val, bool recursive, bool patternMatch=true) const
template<class T >
T lookupType (const word &keyword, bool recursive=false, bool patternMatch=true) const
template<class Compare >
Foam::wordList sortedToc (const Compare &comp) const
template<class T >
Foam::entry * add (const keyType &k, const T &v, bool overwrite)
template<class T >
Foam::entry * set (const keyType &k, const T &v)
Public Member Functions inherited from ILList< LListBase, T >
ILList ()=default
ILList (T *item)
ILList (Istream &is)
ILList (const ILList< LListBase, T > &lst)
ILList (ILList< LListBase, T > &&lst)
template<class CloneArg >
ILList (const ILList< LListBase, T > &lst, const CloneArg &cloneArg)
template<class INew >
ILList (Istream &is, const INew &inew)
~ILList ()
void clear ()
void pop_front (label n=1)
bool erase (T *item)
void transfer (ILList< LListBase, T > &lst)
void operator= (const ILList< LListBase, T > &lst)
void operator= (ILList< LListBase, T > &&lst)
Public Member Functions inherited from UILList< LListBase, T >
UILList ()=default
UILList (T *item)
UILList (const UILList< LListBase, T > &list)
T * front ()
const T * front () const
T * back ()
const T * back () const
T * removeHead ()
T * remove (T *item)
T * remove (iterator &iter)
void operator= (const UILList< LListBase, T > &lst)
bool operator== (const UILList< LListBase, T > &lst) const
bool operator!= (const UILList< LListBase, T > &lst) const
Ostream & writeList (Ostream &os, const label shortLen=0) const
iterator begin ()
const_iterator cbegin () const
reverse_iterator rbegin ()
const_reverse_iterator crbegin () const
const_iterator begin () const
const_reverse_iterator rbegin () const
const iterator & end ()
const const_iterator & cend () const
const reverse_iterator & rend ()
const const_reverse_iterator & crend () const
const const_iterator & end () const
const const_reverse_iterator & rend () const
T * first ()
const T * first () const
T * last ()
const T * last () const
Additional Inherited Members
Public Types inherited from IOobject
enum objectState : char { GOOD , BAD }
enum fileCheckTypes : char { timeStamp , timeStampMaster , inotify , inotifyMaster }
Public Types inherited from IOobjectOption
enum readOption : unsigned char {
NO_READ = 0 , MUST_READ = 0x1 , READ_MODIFIED = 0x3 , MUST_READ_IF_MODIFIED = 0x3 ,
LAZY_READ = 0x4 , READ_IF_PRESENT = 0x4
}
enum writeOption : unsigned char { NO_WRITE = 0 , AUTO_WRITE = 0x10 }
enum registerOption : unsigned char { NO_REGISTER = 0 , REGISTER = 1 }
Public Types inherited from dictionary
typedef Searcher< true > const_searcher
typedef Searcher< false > searcher
Public Types inherited from UILList< LListBase, T >
typedef T value_type
typedef T * pointer
typedef const T * const_pointer
typedef T & reference
typedef const T & const_reference
typedef label size_type
typedef label difference_type
using base_iterator = typename LListBase::iterator
using const_base_iterator = typename LListBase::const_iterator
Static Public Member Functions inherited from objectiveIncompressible
static autoPtr< objectiveIncompressible > New (const fvMesh &mesh, const dictionary &dict, const word &adjointSolverName, const word &primalSolverName)
Static Public Member Functions inherited from objective
static autoPtr< objective > New (const fvMesh &mesh, const dictionary &dict, const word &objectiveType, const word &adjointSolverName, const word &primalSolverName)
Static Public Member Functions inherited from localIOdictionary
static dictionary readContents (const IOobject &io)
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *p)
template<class Type >
static Type & store (autoPtr< Type > &ptr)
template<class Type >
static Type & store (autoPtr< Type > &&ptr)
template<class Type >
static Type & store (refPtr< Type > &ptr)
template<class Type >
static Type & store (refPtr< Type > &&ptr)
template<class Type >
static Type & store (tmp< Type > &ptr)
template<class Type >
static Type & store (tmp< Type > &&ptr)
Static Public Member Functions inherited from IOobject
static bool bannerEnabled () noexcept
static bool bannerEnabled (bool on) noexcept
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
template<class StringType >
static word groupName (StringType base, const word &group)
static word group (const word &name)
static word member (const word &name)
static word scopedName (const std::string &scope, const word &name)
static IOobject selectIO (const IOobject &io, const fileName &altFile, const word &ioName="")
static Ostream & writeBanner (Ostream &os, const bool noSyntaxHint=false)
static Ostream & writeDivider (Ostream &os)
static Ostream & writeEndDivider (Ostream &os)
Static Public Member Functions inherited from IOobjectOption
static bool isAnyRead (readOption opt) noexcept
static bool isReadRequired (readOption opt) noexcept
static bool isReadOptional (readOption opt) noexcept
static readOption lazierRead (readOption opt) noexcept
Static Public Member Functions inherited from dictionary
static int reportOptional () noexcept
static int reportOptional (const int level) noexcept
static autoPtr< dictionary > New (Istream &is)
Public Attributes inherited from dictionary
friend const_searcher
friend searcher
Static Public Attributes inherited from IOobject
static const Enum< fileCheckTypes > fileCheckTypesNames
static char scopeSeparator
static fileCheckTypes fileModificationChecking
static float fileModificationSkew
static int maxFileModificationPolls
Static Public Attributes inherited from dictionary
static int writeOptionalEntries
static const dictionary null
static refPtr< OSstream > reportingOutput
Protected Member Functions inherited from objective
const dictionary & dict () const
void setObjectiveFilePtr () const
void setInstantValueFilePtr () const
void setMeanValueFilePtr () const
Protected Member Functions inherited from regIOobject
bool readHeaderOk (const IOstreamOption::streamFormat fmt, const word &typeName)
Protected Member Functions inherited from IOobject
void setBad (const string &s)
Static Protected Member Functions inherited from IOobject
static void writeHeaderContent (Ostream &os, const IOobject &io, const word &objectType, const dictionary *metaDataDict=nullptr)
static void writeHeaderContent (dictionary &dict, const IOobject &io, const word &objectType, IOstreamOption streamOpt, const dictionary *metaDataDict=nullptr)
Protected Attributes inherited from objectiveIncompressible
const incompressibleVars & vars_
autoPtr< volVectorField > dJdvPtr_
autoPtr< volScalarField > dJdpPtr_
autoPtr< volScalarField > dJdTPtr_
autoPtr< volScalarField > dJdTMvar1Ptr_
autoPtr< volScalarField > dJdTMvar2Ptr_
autoPtr< boundaryVectorField > bdJdvPtr_
autoPtr< boundaryScalarField > bdJdvnPtr_
autoPtr< boundaryVectorField > bdJdvtPtr_
autoPtr< boundaryVectorField > bdJdpPtr_
autoPtr< boundaryScalarField > bdJdTPtr_
autoPtr< boundaryScalarField > bdJdTMvar1Ptr_
autoPtr< boundaryScalarField > bdJdTMvar2Ptr_
autoPtr< boundaryScalarField > bdJdnutPtr_
autoPtr< boundaryTensorField > bdJdGradUPtr_
Protected Attributes inherited from objective
const fvMesh & mesh_
dictionary dict_
const word adjointSolverName_
const word primalSolverName_
const word objectiveName_
bool computeMeanFields_
bool nullified_
bool normalize_
scalar J_
scalar JMean_
scalar weight_
autoPtr< scalar > normFactor_
autoPtr< scalar > target_
autoPtr< scalar > integrationStartTimePtr_
autoPtr< scalar > integrationEndTimePtr_
autoPtr< volScalarField > dJdbPtr_
autoPtr< boundaryVectorField > bdJdbPtr_
autoPtr< boundaryVectorField > bdSdbMultPtr_
autoPtr< boundaryVectorField > bdndbMultPtr_
autoPtr< boundaryVectorField > bdxdbMultPtr_
autoPtr< boundaryVectorField > bdxdbDirectMultPtr_
autoPtr< vectorField3 > bEdgeContribution_
autoPtr< volScalarField > divDxDbMultPtr_
autoPtr< volTensorField > gradDxDbMultPtr_
fileName objFunctionFolder_
autoPtr< OFstream > objFunctionFilePtr_
autoPtr< OFstream > instantValueFilePtr_
autoPtr< OFstream > meanValueFilePtr_
unsigned int width_
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
Detailed Description
Split inlet flow rate to given percentages at the prescribed outlet patches.
Source files
objectiveFlowRatePartition.H
objectiveFlowRatePartition.C
Definition at line 51 of file objectiveFlowRatePartition.H.
Constructor & Destructor Documentation
objectiveFlowRatePartition()
objectiveFlowRatePartition (const fvMesh & mesh, const dictionary & dict, const word & adjointSolverName, const word & primalSolverName)
Definition at line 48 of file objectiveFlowRatePartition.C.
References objectiveIncompressible::bdJdvnPtr_, objectiveIncompressible::bdJdvPtr_, objective::dict(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::max(), objective::mesh_, List< T >::setSize(), UList< T >::size(), and objective::width_.
~objectiveFlowRatePartition()
virtual ~objectiveFlowRatePartition () virtual default
Member Function Documentation
TypeName()
TypeName ("flowRatePartition")
J()
scalar J () virtual
Implements objectiveIncompressible.
Definition at line 108 of file objectiveFlowRatePartition.C.
References forAll, Foam::gSum(), objective::J_, objective::mesh_, U, and objectiveIncompressible::vars_.
update_boundarydJdv()
void update_boundarydJdv () virtual
Reimplemented from objectiveIncompressible.
Definition at line 138 of file objectiveFlowRatePartition.C.
References objectiveIncompressible::bdJdvPtr_, forAll, and objective::mesh_.
update_boundarydJdvn()
void update_boundarydJdvn () virtual
Reimplemented from objectiveIncompressible.
Definition at line 149 of file objectiveFlowRatePartition.C.
References objectiveIncompressible::bdJdvnPtr_, and forAll.
addHeaderInfo()
void addHeaderInfo () const virtual
Reimplemented from objective.
Definition at line 159 of file objectiveFlowRatePartition.C.
References Foam::endl(), forAll, objective::mesh_, objective::objFunctionFilePtr_, Foam::setw(), and objective::width_.
addHeaderColumns()
void addHeaderColumns () const virtual
Reimplemented from objective.
Definition at line 175 of file objectiveFlowRatePartition.C.
References objective::mesh_, objective::objFunctionFilePtr_, Foam::setw(), and objective::width_.
addColumnValues()
void addColumnValues () const virtual
Reimplemented from objective.
Definition at line 186 of file objectiveFlowRatePartition.C.
References objective::objFunctionFilePtr_, Foam::setw(), and objective::width_.
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/objectives/incompressible/objectiveFlowRatePartition/objectiveFlowRatePartition.H
src/optimisation/adjointOptimisation/adjoint/objectives/incompressible/objectiveFlowRatePartition/objectiveFlowRatePartition.C