OpenFOAM: triad Class Reference
triad Class Reference
Representation of a 3D Cartesian coordinate system as a Vector of row vectors.
#include <triad.H>
Public Member Functions
triad ()
triad (const Vector< vector > &vv)
triad (const vector &x, const vector &y, const vector &z)
triad (const tensor &t)
triad (const vector &pa)
triad (const quaternion &q)
triad (Istream &)
bool set (const direction d) const
bool set () const
void orthogonalise ()
void normalise ()
void align (const vector &v)
triad sortxyz () const
operator quaternion () const
triad T () const
vector cx () const
vector cy () const
vector cz () const
void operator= (const Vector< vector > &vv)
void operator= (const tensor &t)
void operator+= (const triad &t2)
void orthogonalize ()
void normalize ()
Public Member Functions inherited from Vector< vector >
Vector ()=default
Vector (const Vector &)=default
Vector (const Foam::zero)
Vector (const VectorSpace< Vector< Cmpt2 >, Cmpt2, 3 > &vs)
Vector (const vector &vx, const vector &vy, const vector &vz)
Vector (Istream &is)
Vector & operator= (const Vector &)=default
const vector & x () const noexcept
vector & x () noexcept
const vector & y () const noexcept
vector & y () noexcept
const vector & z () const noexcept
vector & z () noexcept
const Vector< vector > & centre (const Foam::UList< Vector< vector > > &) const noexcept
scalar mag () const
scalar magSqr () const
scalar dist (const Vector< vector > &v2) const
scalar distSqr (const Vector< vector > &v2) const
Vector< vector > & normalise (const scalar tol=ROOTVSMALL)
Vector< vector > & removeCollinear (const Vector< vector > &unitVec)
vector inner (const Vector< vector > &v2) const
Vector< vector > cross (const Vector< vector > &v2) const
Public Member Functions inherited from VectorSpace< Form, Cmpt, Ncmpts >
VectorSpace ()=default
VectorSpace (const Foam::zero)
VectorSpace (const VectorSpace< Form, Cmpt, Ncmpts > &vs)
template<class Form2 , class Cmpt2 >
VectorSpace (const VectorSpace< Form2, Cmpt2, Ncmpts > &)
VectorSpace (Istream &is)
const Cmpt & component (const direction) const
Cmpt & component (const direction)
void component (Cmpt &, const direction) const
void replace (const direction, const Cmpt &)
const Cmpt * cdata () const noexcept
Cmpt * data () noexcept
template<class SubVector , direction BStart>
const ConstBlock< SubVector, BStart > block () const
const Cmpt & operator[] (const direction) const
Cmpt & operator[] (const direction)
void operator= (const VectorSpace< Form, Cmpt, Ncmpts > &)
void operator+= (const VectorSpace< Form, Cmpt, Ncmpts > &)
void operator-= (const VectorSpace< Form, Cmpt, Ncmpts > &)
void operator= (const Foam::zero)
void operator*= (const scalar)
void operator/= (const scalar)
iterator begin () noexcept
iterator end () noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
const_iterator begin () const noexcept
const_iterator end () const noexcept
template<class SubVector , Foam::direction BStart>
const Foam::VectorSpace< Form, Cmpt, Ncmpts >::template ConstBlock< SubVector, BStart > block () const
Static Public Member Functions
static direction primaryDirection (const vector &v)
static vector orthogonal (const vector &v1, const vector &v2)
Static Public Member Functions inherited from Vector< vector >
static bool less_xyz (const Vector< vector > &a, const Vector< vector > &b)
static bool less_yzx (const Vector< vector > &a, const Vector< vector > &b)
static bool less_zxy (const Vector< vector > &a, const Vector< vector > &b)
Static Public Member Functions inherited from VectorSpace< Form, Cmpt, Ncmpts >
static constexpr direction size () noexcept
static Form uniform (const Cmpt &s)
Static Public Attributes
static const triad I
static const triad unset
Static Public Attributes inherited from Vector< vector >
static constexpr direction rank
Static Public Attributes inherited from VectorSpace< Form, Cmpt, Ncmpts >
static constexpr direction dim = 3
static constexpr direction nComponents = Ncmpts
static constexpr direction mRows = Ncmpts
static constexpr direction nCols = 1
static const char *const typeName = "diagTensor"
static const char *const componentNames []
static const Form zero
static const Form one
static const Form max
static const Form min
static const Form rootMax
static const Form rootMin
Friends
Istream & operator>> (Istream &, triad &)
Ostream & operator<< (Ostream &, const triad &)
Additional Inherited Members
Public Types inherited from Vector< vector >
enum components
typedef Vector< label > labelType
Public Types inherited from VectorSpace< Form, Cmpt, Ncmpts >
typedef VectorSpace< Form, Cmpt, Ncmpts > vsType
typedef Cmpt cmptType
typedef Cmpt magType
typedef Cmpt * iterator
typedef const Cmpt * const_iterator
Public Attributes inherited from VectorSpace< Form, Cmpt, Ncmpts >
Cmpt v_ [Ncmpts]
Detailed Description
Representation of a 3D Cartesian coordinate system as a Vector of row vectors.
See also
Foam::quaternion
Source files
triad.H
triadI.H
triad.C
Definition at line 60 of file triad.H.
Constructor & Destructor Documentation
triad() [1/7]
triad () inline
Definition at line 24 of file triadI.H.
triad() [2/7]
triad (const Vector< vector > & vv) inline
Definition at line 30 of file triadI.H.
triad() [3/7]
triad (const vector & x, const vector & y, const vector & z) inline
Definition at line 36 of file triadI.H.
triad() [4/7]
triad (const tensor & t) inline
Definition at line 42 of file triadI.H.
triad() [5/7]
triad (const vector & pa) inline
Definition at line 48 of file triadI.H.
References triad::unset.
triad() [6/7]
triad (const quaternion & q)
Definition at line 84 of file triad.C.
References quaternion::R(), Tensor< Cmpt >::T(), Tensor< Cmpt >::x(), Vector< vector >::x(), Tensor< Cmpt >::y(), Vector< vector >::y(), Tensor< Cmpt >::z(), and Vector< vector >::z().
triad() [7/7]
triad (Istream & is) inline
Definition at line 55 of file triadI.H.
Member Function Documentation
set() [1/2]
bool set (const direction d) const inline
Definition at line 63 of file triadI.H.
set() [2/2]
bool set () const inline
Definition at line 69 of file triadI.H.
primaryDirection()
Foam::direction primaryDirection (const vector & v) inline static
Definition at line 75 of file triadI.H.
References Foam::mag(), Vector< vector >::X, Vector< Cmpt >::x(), Vector< vector >::Y, Vector< Cmpt >::y(), Vector< vector >::Z, and Vector< Cmpt >::z().
orthogonal()
Foam::vector orthogonal (const vector & v1, const vector & v2) inline static
Definition at line 96 of file triadI.H.
References Foam::mag(), and triad::unset.
orthogonalise()
void orthogonalise ()
Definition at line 95 of file triad.C.
References Foam::mag().
Referenced by triad::orthogonalize().
normalise()
void normalise () inline
Definition at line 117 of file triadI.H.
Referenced by triad::normalize().
align()
void align (const vector & v)
Definition at line 235 of file triad.C.
References Foam::mag(), R, Foam::rotationTensor(), and Foam::transform().
sortxyz()
Foam::triad sortxyz () const
Definition at line 280 of file triad.C.
References Foam::mag(), x, and y.
operator quaternion()
operator quaternion () const
T()
Foam::triad T () const inline
Definition at line 143 of file triadI.H.
cx()
Foam::vector cx () const inline
Definition at line 125 of file triadI.H.
References x, and y.
cy()
Foam::vector cy () const inline
Definition at line 131 of file triadI.H.
References x, and y.
cz()
Foam::vector cz () const inline
Definition at line 137 of file triadI.H.
References x, and y.
operator=() [1/2]
void operator= (const Vector< vector > & vv) inline
Definition at line 151 of file triadI.H.
References Vector< Cmpt >::operator=().
operator=() [2/2]
void operator= (const tensor & t) inline
Definition at line 157 of file triadI.H.
References x, Tensor< Cmpt >::x(), y, Tensor< Cmpt >::y(), and Tensor< Cmpt >::z().
operator+=()
void operator+= (const triad & t2)
Definition at line 172 of file triad.C.
References k, Foam::mag(), PtrList< T >::set(), and Foam::sign().
orthogonalize()
void orthogonalize () inline
Definition at line 163 of file triad.H.
References triad::orthogonalise().
normalize()
void normalize () inline
Definition at line 166 of file triad.H.
References triad::normalise().
Friends And Related Symbol Documentation
operator>>
Istream & operator>> (Istream & , triad &) friend
operator<<
Ostream & operator<< (Ostream & , const triad &) friend
Member Data Documentation
I
const Foam::triad I static
Definition at line 92 of file triad.H.
unset
const Foam::triad unset static
Definition at line 93 of file triad.H.
Referenced by triad::orthogonal(), triad::triad(), and triSurfaceTools::vertexTriads().
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/triad/triad.H
src/OpenFOAM/primitives/triad/triad.C
src/OpenFOAM/primitives/triad/triadI.H