OpenFOAM: PressureGradientForce< CloudType > Class Template Reference
PressureGradientForce< CloudType > Class Template Reference
Lagrangian particle models » Submodels » Kinematic » Forces
Calculates particle pressure gradient force.
#include <PressureGradientForce.H>
Public Member Functions
TypeName ("pressureGradient")
PressureGradientForce (CloudType &owner, const fvMesh &mesh, const dictionary &dict, const word &forceType=typeName)
PressureGradientForce (const PressureGradientForce &pgf)
virtual autoPtr< ParticleForce< CloudType > > clone () const
virtual ~PressureGradientForce ()
const interpolation< vector > & DUcDtInterp () const
virtual void cacheFields (const bool store)
virtual forceSuSp calcCoupled (const typename CloudType::parcelType &p, const typename CloudType::parcelType::trackingData &td, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const
virtual scalar massAdd (const typename CloudType::parcelType &p, const typename CloudType::parcelType::trackingData &td, const scalar mass) const
Public Member Functions inherited from ParticleForce< CloudType >
TypeName ("particleForce")
declareRunTimeSelectionTable (autoPtr, ParticleForce, dictionary,(CloudType &owner, const fvMesh &mesh, const dictionary &dict),(owner, mesh, dict))
ParticleForce (CloudType &owner, const fvMesh &mesh, const dictionary &dict, const word &forceType, const bool readCoeffs)
ParticleForce (const ParticleForce &pf)
virtual ~ParticleForce ()
const CloudType & owner () const
CloudType & owner ()
const fvMesh & mesh () const
const dictionary & coeffs () const
virtual forceSuSp calcNonCoupled (const typename CloudType::parcelType &p, const typename CloudType::parcelType::trackingData &td, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const
Protected Attributes
const word UName_
autoPtr< interpolation< vector > > DUcDtInterpPtr_
Additional Inherited Members
Public Types inherited from ParticleForce< CloudType >
typedef VectorSpace< Vector< vector >, vector, 2 > returnType
Static Public Member Functions inherited from ParticleForce< CloudType >
static autoPtr< ParticleForce< CloudType > > New (CloudType &owner, const fvMesh &mesh, const dictionary &dict, const word &forceType)
Detailed Description
template<class CloudType>
class Foam::PressureGradientForce< CloudType >
Calculates particle pressure gradient force.
Source files
PressureGradientForce.H
PressureGradientForceI.H
PressureGradientForce.C
Definition at line 53 of file PressureGradientForce.H.
Constructor & Destructor Documentation
PressureGradientForce() [1/2]
template<class CloudType > PressureGradientForce (CloudType & owner, const fvMesh & mesh, const dictionary & dict, const word & forceType = typeName)
Definition at line 29 of file PressureGradientForce.C.
PressureGradientForce() [2/2]
template<class CloudType > PressureGradientForce (const PressureGradientForce< CloudType > & pgf)
Definition at line 44 of file PressureGradientForce.C.
~PressureGradientForce()
template<class CloudType > ~PressureGradientForce () virtual
Definition at line 58 of file PressureGradientForce.C.
Member Function Documentation
TypeName()
template<class CloudType > TypeName ("pressureGradient")
clone()
template<class CloudType > virtual autoPtr< ParticleForce< CloudType > > clone () const inline virtual
Reimplemented from ParticleForce< CloudType >.
Reimplemented in VirtualMassForce< CloudType >.
Definition at line 89 of file PressureGradientForce.H.
DUcDtInterp()
template<class CloudType > const Foam::interpolation< Foam::vector > & DUcDtInterp () const inline
Definition at line 26 of file PressureGradientForceI.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
cacheFields()
template<class CloudType > void cacheFields (const bool store) virtual
Reimplemented from ParticleForce< CloudType >.
Reimplemented in VirtualMassForce< CloudType >.
Definition at line 65 of file PressureGradientForce.C.
References PtrList< T >::clear(), Foam::fvc::ddt(), Foam::fvc::grad(), and mesh.
Referenced by VirtualMassForce< CloudType >::cacheFields().
calcCoupled()
template<class CloudType > Foam::forceSuSp calcCoupled (const typename CloudType::parcelType & p, const typename CloudType::parcelType::trackingData & td, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const virtual
Reimplemented from ParticleForce< CloudType >.
Reimplemented in VirtualMassForce< CloudType >.
Definition at line 111 of file PressureGradientForce.C.
References p, forceSuSp::Su(), and Foam::Zero.
Referenced by VirtualMassForce< CloudType >::calcCoupled().
massAdd()
template<class CloudType > Foam::scalar massAdd (const typename CloudType::parcelType & p, const typename CloudType::parcelType::trackingData & td, const scalar mass) const virtual
Reimplemented from ParticleForce< CloudType >.
Reimplemented in VirtualMassForce< CloudType >.
Definition at line 133 of file PressureGradientForce.C.
Member Data Documentation
UName_
template<class CloudType > const word UName_ protected
Definition at line 62 of file PressureGradientForce.H.
DUcDtInterpPtr_
template<class CloudType > autoPtr<interpolation<vector> > DUcDtInterpPtr_ protected
Definition at line 65 of file PressureGradientForce.H.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/Kinematic/ParticleForces/PressureGradient/PressureGradientForce.H
src/lagrangian/intermediate/submodels/Kinematic/ParticleForces/PressureGradient/PressureGradientForce.C
src/lagrangian/intermediate/submodels/Kinematic/ParticleForces/PressureGradient/PressureGradientForceI.H