OpenFOAM: MaxwellianThermal< CloudType > Class Template Reference
MaxwellianThermal< CloudType > Class Template Reference
Wall interaction setting microscopic velocity to a random one drawn from a Maxwellian distribution corresponding to a specified temperature.
#include <MaxwellianThermal.H>
Public Member Functions
TypeName ("MaxwellianThermal")
MaxwellianThermal (const dictionary &dict, CloudType &cloud)
virtual ~MaxwellianThermal ()
virtual void correct (typename CloudType::parcelType &p)
Public Member Functions inherited from WallInteractionModel< CloudType >
TypeName ("WallInteractionModel")
declareRunTimeSelectionTable (autoPtr, WallInteractionModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
WallInteractionModel (CloudType &owner)
WallInteractionModel (const dictionary &dict, CloudType &owner, const word &type)
virtual ~WallInteractionModel ()
const CloudType & owner () const
CloudType & owner ()
const dictionary & dict () const
const dictionary & coeffDict () const
Additional Inherited Members
Static Public Member Functions inherited from WallInteractionModel< CloudType >
static autoPtr< WallInteractionModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Detailed Description
template<class CloudType>
class Foam::MaxwellianThermal< CloudType >
Wall interaction setting microscopic velocity to a random one drawn from a Maxwellian distribution corresponding to a specified temperature.
Definition at line 43 of file MaxwellianThermal.H.
Constructor & Destructor Documentation
MaxwellianThermal()
template<class CloudType > MaxwellianThermal (const dictionary & dict, CloudType & cloud)
Definition at line 29 of file MaxwellianThermal.C.
~MaxwellianThermal()
template<class CloudType > ~MaxwellianThermal () virtual
Definition at line 42 of file MaxwellianThermal.C.
Member Function Documentation
TypeName()
template<class CloudType > TypeName ("MaxwellianThermal< CloudType >")
correct()
template<class CloudType > void correct (typename CloudType::parcelType & p) virtual
Implements WallInteractionModel< CloudType >.
Definition at line 49 of file MaxwellianThermal.C.
References Random::GaussNormal(), Foam::constant::physicoChemical::k, Foam::log(), Foam::mag(), Foam::max(), DimensionedField< Type, GeoMesh >::mesh(), p, rndGen, Random::sample01(), Foam::sqrt(), T, and U.
The documentation for this class was generated from the following files:
src/lagrangian/DSMC/submodels/WallInteractionModel/MaxwellianThermal/MaxwellianThermal.H
src/lagrangian/DSMC/submodels/WallInteractionModel/MaxwellianThermal/MaxwellianThermal.C