OpenFOAM: UOListStreamAllocator Class Reference
UOListStreamAllocator Class Reference
#include <UOListStream.H>
Public Member Functions
const UList< char > list () const
UList< char > list ()
label capacity () const
label size () const
void rewind ()
Protected Types
typedef std::ostream stream_type
Protected Member Functions
UOListStreamAllocator (char *buffer, size_t nbytes)
void printBufInfo (Ostream &os) const
Protected Attributes
memorybuf::out buf_
stream_type stream_
Detailed Description
Definition at line 98 of file UOListStream.H.
Member Typedef Documentation
stream_type
typedef std::ostream stream_type protected
Definition at line 104 of file UOListStream.H.
Constructor & Destructor Documentation
UOListStreamAllocator()
UOListStreamAllocator (char * buffer, size_t nbytes) inline protected
Definition at line 116 of file UOListStream.H.
Member Function Documentation
printBufInfo()
void printBufInfo (Ostream & os) const inline protected
Definition at line 122 of file UOListStream.H.
References UOListStreamAllocator::buf_, os(), and memorybuf::out::printBufInfo().
list() [1/2]
const UList< char > list () const inline
Definition at line 132 of file UOListStream.H.
References UOListStreamAllocator::buf_, and memorybuf::out::list().
list() [2/2]
UList< char > list () inline
Definition at line 138 of file UOListStream.H.
References UOListStreamAllocator::buf_, and memorybuf::out::list().
capacity()
label capacity () const inline
Definition at line 144 of file UOListStream.H.
References UOListStreamAllocator::buf_, and memorybuf::out::capacity().
size()
label size () const inline
Definition at line 151 of file UOListStream.H.
References UOListStreamAllocator::buf_, and memorybuf::out::tellp().
rewind()
void rewind () inline
Definition at line 157 of file UOListStream.H.
References UOListStreamAllocator::buf_, and UOListStreamAllocator::stream_.
Referenced by UOListStream::rewind().
Member Data Documentation
buf_
memorybuf::out buf_ protected
Definition at line 107 of file UOListStream.H.
Referenced by UOListStreamAllocator::capacity(), UOListStreamAllocator::list(), UOListStreamAllocator::list(), UOListStreamAllocator::printBufInfo(), UOListStreamAllocator::rewind(), and UOListStreamAllocator::size().
stream_
stream_type stream_ protected
Definition at line 110 of file UOListStream.H.
Referenced by UOListStreamAllocator::rewind().
The documentation for this class was generated from the following file:
src/OpenFOAM/db/IOstreams/memory/UOListStream.H