OpenFOAM: tetOverlapVolume Class Reference
tetOverlapVolume Class Reference
Calculates the overlap volume of two cells using tetrahedral decomposition.
#include <tetOverlapVolume.H>
Public Member Functions
ClassName ("tetOverlapVolume")
tetOverlapVolume ()=default
labelList overlappingCells (const polyMesh &meshA, const polyMesh &meshB, const label cellBI) const
bool cellCellOverlapMinDecomp (const primitiveMesh &meshA, const label cellAI, const primitiveMesh &meshB, const label cellBI, const treeBoundBox &cellBbB, const scalar threshold=0.0) const
scalar cellCellOverlapVolumeMinDecomp (const primitiveMesh &meshA, const label cellAI, const primitiveMesh &meshB, const label cellBI, const treeBoundBox &cellBbB) const
Tuple2< scalar, point > cellCellOverlapMomentMinDecomp (const primitiveMesh &meshA, const label cellAI, const primitiveMesh &meshB, const label cellBI, const treeBoundBox &cellBbB) const
Detailed Description
Calculates the overlap volume of two cells using tetrahedral decomposition.
Source files
tetOverlapVolume.H
tetOverlapVolume.C
tetOverlapVolumeTemplates.C
Definition at line 53 of file tetOverlapVolume.H.
Constructor & Destructor Documentation
tetOverlapVolume()
tetOverlapVolume () default
Member Function Documentation
ClassName()
ClassName ("tetOverlapVolume")
overlappingCells()
Foam::labelList overlappingCells (const polyMesh & meshA, const polyMesh & meshB, const label cellBI) const
Definition at line 132 of file tetOverlapVolume.C.
References primitiveMesh::cellPoints(), polyMesh::cellTree(), and polyMesh::points().
cellCellOverlapMinDecomp()
bool cellCellOverlapMinDecomp (const primitiveMesh & meshA, const label cellAI, const primitiveMesh & meshB, const label cellBI, const treeBoundBox & cellBbB, const scalar threshold = 0.0) const
Definition at line 56 of file tetOverlapVolume.C.
cellCellOverlapVolumeMinDecomp()
Foam::scalar cellCellOverlapVolumeMinDecomp (const primitiveMesh & meshA, const label cellAI, const primitiveMesh & meshB, const label cellBI, const treeBoundBox & cellBbB) const
Definition at line 81 of file tetOverlapVolume.C.
cellCellOverlapMomentMinDecomp()
Foam::Tuple2< Foam::scalar, Foam::point > cellCellOverlapMomentMinDecomp (const primitiveMesh & meshA, const label cellAI, const primitiveMesh & meshB, const label cellBI, const treeBoundBox & cellBbB) const
Definition at line 107 of file tetOverlapVolume.C.
The documentation for this class was generated from the following files:
src/meshTools/tetOverlapVolume/tetOverlapVolume.H
src/meshTools/tetOverlapVolume/tetOverlapVolume.C
src/meshTools/tetOverlapVolume/tetOverlapVolumeTemplates.C