OpenFOAM: SquareMatrix< Type > Class Template Reference
SquareMatrix< Type > Class Template Reference
A templated (N x N) square matrix of objects of <Type>, containing N*N elements, derived from Matrix.
#include <SquareMatrix.H>
Public Member Functions
SquareMatrix ()=default
SquareMatrix (const SquareMatrix &)=default
SquareMatrix & operator= (const SquareMatrix &)=default
SquareMatrix (const label n)
SquareMatrix (const label n, const Foam::zero)
SquareMatrix (const label n, const Type &val)
template<class AnyType >
SquareMatrix (const label n, const Identity< AnyType >)
template<class AnyType >
SquareMatrix (const labelPair &dims, const Identity< AnyType >)
SquareMatrix (const labelPair &dims)
SquareMatrix (const labelPair &dims, const Foam::zero)
SquareMatrix (const labelPair &dims, const Type &val)
SquareMatrix (const label m, const label n, const Foam::zero)
template<class MatrixType >
SquareMatrix (const ConstMatrixBlock< MatrixType > &mat)
template<class MatrixType >
SquareMatrix (const MatrixBlock< MatrixType > &mat)
SquareMatrix (const RectangularMatrix< Type > &mat)
SquareMatrix (Istream &is)
autoPtr< SquareMatrix< Type > > clone () const
void resize (const label m)
void resize (const label m, const label n)
void setSize (const label m)
void shallowResize (const label m)
bool symmetric () const
bool tridiagonal () const
template<class CompOp >
List< label > sortPermutation (CompOp &compare) const
void applyPermutation (const List< label > &p)
void operator= (SquareMatrix< Type > &&mat)
void operator= (const Foam::zero)
void operator= (const Type &val)
template<class AnyType >
void operator= (const Identity< AnyType >)
template<class CompOp >
Foam::List< Foam::label > sortPermutation (CompOp &compare) const
Public Member Functions inherited from Matrix< SquareMatrix< Type >, Type >
Foam::tmp< Foam::Field< Type > > AmulImpl (const ListType &x) const
Foam::tmp< Foam::Field< Type > > TmulImpl (const ListType &x) const
Matrix () noexcept
Matrix (const label m, const label n)
Matrix (const label m, const label n, const Foam::zero)
Matrix (const label m, const label n, const Type &val)
Matrix (const labelPair &dims)
Matrix (const labelPair &dims, const Foam::zero)
Matrix (const labelPair &dims, const Type &val)
Matrix (const Matrix< SquareMatrix< Type >, Type > &mat)
Matrix (Matrix< SquareMatrix< Type >, Type > &&mat)
Matrix (const Matrix< Form2, Type > &mat)
Matrix (const ConstMatrixBlock< MatrixType > &Mb)
Matrix (const MatrixBlock< MatrixType > &Mb)
Matrix (Istream &is)
autoPtr< mType > clone () const
~Matrix ()
label m () const noexcept
label n () const noexcept
label size () const
labelPair sizes () const
bool empty () const noexcept
const Type * cdata () const noexcept
Type * data () noexcept
const char * cdata_bytes () const noexcept
char * data_bytes () noexcept
std::streamsize size_bytes () const noexcept
std::streamsize byteSize () const
const Type * rowData (const label irow) const
Type * rowData (const label irow)
const Type & at (const label idx) const
Type & at (const label idx)
ConstMatrixBlock< mType > subColumn (const label colIndex, const label rowIndex=0, label len=-1) const
MatrixBlock< mType > subColumn (const label colIndex, const label rowIndex=0, label len=-1)
ConstMatrixBlock< mType > subRow (const label rowIndex, const label colIndex=0, label len=-1) const
MatrixBlock< mType > subRow (const label rowIndex, const label colIndex=0, label len=-1)
ConstMatrixBlock< mType > subMatrix (const label rowIndex, const label colIndex, label szRows=-1, label szCols=-1) const
MatrixBlock< mType > subMatrix (const label rowIndex, const label colIndex, label szRows=-1, label szCols=-1)
ConstMatrixBlock< mType > block (const label rowIndex, const label colIndex) const
MatrixBlock< mType > block (const label rowIndex, const label colIndex)
ConstMatrixBlock< mType > block (const label m, const label n, const label mStart, const label nStart) const
MatrixBlock< mType > block (const label m, const label n, const label mStart, const label nStart)
Foam::ConstMatrixBlock< Foam::Matrix< SquareMatrix< Type >, Type > > block (const label rowIndex, const label colIndex) const
Foam::MatrixBlock< Foam::Matrix< SquareMatrix< Type >, Type > > block (const label rowIndex, const label colIndex)
void checki (const label irow) const
void checkj (const label jcol) const
void checkSize () const
bool uniform () const
void clear ()
List< Type > release ()
void swap (Matrix< SquareMatrix< Type >, Type > &mat)
void transfer (Matrix< SquareMatrix< Type >, Type > &mat)
void resize (const label m, const label n)
void resize_nocopy (const label mrow, const label ncol)
void setSize (const label m, const label n)
void shallowResize (const label m, const label n)
void round (const scalar tol=SMALL)
SquareMatrix< Type > T () const
SquareMatrix< Type > transpose () const
tmp< Field< Type > > Amul (const UList< Type > &x) const
tmp< Field< Type > > Amul (const IndirectListBase< Type, Addr > &x) const
Foam::tmp< Foam::Field< Type > > Amul (const IndirectListBase< Type, Addr > &x) const
tmp< Field< Type > > Tmul (const UList< Type > &x) const
tmp< Field< Type > > Tmul (const IndirectListBase< Type, Addr > &x) const
Foam::tmp< Foam::Field< Type > > Tmul (const IndirectListBase< Type, Addr > &x) const
List< Type > diag () const
void diag (const UList< Type > &list)
Type trace () const
scalar columnNorm (const label colIndex, const bool noSqrt=false) const
scalar norm (const bool noSqrt=false) const
const Type * operator[] (const label irow) const
Type * operator[] (const label irow)
const Type & operator() (const label irow, const label jcol) const
Type & operator() (const label irow, const label jcol)
void operator= (const Matrix< SquareMatrix< Type >, Type > &mat)
void operator= (Matrix< SquareMatrix< Type >, Type > &&mat)
void operator= (const ConstMatrixBlock< MatrixType > &Mb)
void operator= (const MatrixBlock< MatrixType > &Mb)
void operator= (const Foam::zero)
void operator= (const Type &val)
void operator+= (const Matrix< SquareMatrix< Type >, Type > &other)
void operator+= (const Type &s)
void operator-= (const Matrix< SquareMatrix< Type >, Type > &other)
void operator-= (const Type &s)
void operator*= (const Type &s)
void operator/= (const Type &s)
iterator begin () noexcept
const_iterator begin () const noexcept
iterator end () noexcept
const_iterator end () const noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
bool readMatrix (Istream &is)
Ostream & writeMatrix (Ostream &os, const label shortLen=0) const
label mRows () const noexcept
label nRows () const noexcept
label nCols () const noexcept
const Type * v () const
Type * v ()
ConstMatrixBlock< mType > col (const label m, const label mStart, const label nStart) const
MatrixBlock< mType > col (const label m, const label mStart, const label nStart)
void col (const label m, const label rowStart) const=delete
void col (const label m, const label rowStart)=delete
Additional Inherited Members
Public Types inherited from Matrix< SquareMatrix< Type >, Type >
typedef Matrix< SquareMatrix< Type >, Type > mType
typedef Type cmptType
typedef Type * iterator
typedef const Type * const_iterator
Static Public Member Functions inherited from Matrix< SquareMatrix< Type >, Type >
static const Matrix< SquareMatrix< Type >, Type > & null ()
Detailed Description
template<class Type>
class Foam::SquareMatrix< Type >
A templated (N x N) square matrix of objects of <Type>, containing N*N elements, derived from Matrix.
See also
Test-SquareMatrix.C
Source files
SquareMatrix.H
SquareMatrixI.H
SquareMatrix.C
Definition at line 59 of file SquareMatrix.H.
Constructor & Destructor Documentation
SquareMatrix() [1/15]
template<class Type > SquareMatrix () default
SquareMatrix() [2/15]
template<class Type > SquareMatrix (const SquareMatrix< Type > &) default
SquareMatrix() [3/15]
template<class Type > SquareMatrix (const label n) inline explicit
Definition at line 34 of file SquareMatrixI.H.
SquareMatrix() [4/15]
template<class Type > SquareMatrix (const label n, const Foam::zero) inline
Definition at line 41 of file SquareMatrixI.H.
SquareMatrix() [5/15]
template<class Type > SquareMatrix (const label n, const Type & val) inline
Definition at line 52 of file SquareMatrixI.H.
SquareMatrix() [6/15]
template<class Type > template<class AnyType > SquareMatrix (const label n, const Identity< AnyType >) inline
Definition at line 64 of file SquareMatrixI.H.
References Matrix< SquareMatrix< Type >, Type >::n(), and Matrix< SquareMatrix< Type >, Type >::operator()().
SquareMatrix() [7/15]
template<class Type > template<class AnyType > SquareMatrix (const labelPair & dims, const Identity< AnyType >) inline
Definition at line 81 of file SquareMatrixI.H.
SquareMatrix() [8/15]
template<class Type > SquareMatrix (const labelPair & dims) inline explicit
Definition at line 99 of file SquareMatrixI.H.
SquareMatrix() [9/15]
template<class Type > SquareMatrix (const labelPair & dims, const Foam::zero) inline
Definition at line 111 of file SquareMatrixI.H.
SquareMatrix() [10/15]
template<class Type > SquareMatrix (const labelPair & dims, const Type & val) inline
Definition at line 124 of file SquareMatrixI.H.
SquareMatrix() [11/15]
template<class Type > SquareMatrix (const label m, const label n, const Foam::zero) inline
Definition at line 137 of file SquareMatrixI.H.
SquareMatrix() [12/15]
template<class Type > template<class MatrixType > SquareMatrix (const ConstMatrixBlock< MatrixType > & mat) inline
Definition at line 152 of file SquareMatrixI.H.
SquareMatrix() [13/15]
template<class Type > template<class MatrixType > SquareMatrix (const MatrixBlock< MatrixType > & mat) inline
Definition at line 165 of file SquareMatrixI.H.
SquareMatrix() [14/15]
template<class Type > SquareMatrix (const RectangularMatrix< Type > & mat) inline explicit
Definition at line 177 of file SquareMatrixI.H.
SquareMatrix() [15/15]
template<class Type > SquareMatrix (Istream & is) inline explicit
Definition at line 189 of file SquareMatrixI.H.
References CHECK_MATRIX_IS_SQUARE, Matrix< SquareMatrix< Type >, Type >::m(), and Matrix< SquareMatrix< Type >, Type >::n().
Member Function Documentation
operator=() [1/5]
template<class Type > SquareMatrix & operator= (const SquareMatrix< Type > &) default
clone()
template<class Type > Foam::autoPtr< Foam::SquareMatrix< Type > > clone () const inline
Definition at line 199 of file SquareMatrixI.H.
References Foam::New().
resize() [1/2]
template<class Type > void resize (const label m) inline
Definition at line 208 of file SquareMatrixI.H.
References resize().
resize() [2/2]
template<class Type > void resize (const label m, const label n) inline
Definition at line 215 of file SquareMatrixI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, n, and resize().
setSize()
template<class Type > void setSize (const label m) inline
Definition at line 228 of file SquareMatrixI.H.
References resize().
shallowResize()
template<class Type > void shallowResize (const label m) inline
Definition at line 235 of file SquareMatrixI.H.
Referenced by ODESolver::resizeMatrix().
symmetric()
template<class Type > bool symmetric () const inline
Definition at line 242 of file SquareMatrixI.H.
References Foam::mag(), and n.
tridiagonal()
template<class Type > bool tridiagonal () const inline
Definition at line 259 of file SquareMatrixI.H.
References Foam::mag(), and n.
sortPermutation() [1/2]
template<class Type > template<class CompOp > List< label > sortPermutation (CompOp & compare) const
applyPermutation()
template<class Type > void applyPermutation (const List< label > & p)
Definition at line 49 of file SquareMatrix.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, Foam::nl, p, and UList< T >::size().
operator=() [2/5]
template<class Type > void operator= (SquareMatrix< Type > && mat) inline
Definition at line 287 of file SquareMatrixI.H.
operator=() [3/5]
template<class Type > void operator= (const Foam::zero) inline
Definition at line 294 of file SquareMatrixI.H.
References Foam::Zero.
operator=() [4/5]
template<class Type > void operator= (const Type & val) inline
Definition at line 301 of file SquareMatrixI.H.
operator=() [5/5]
template<class Type > template<class AnyType > void operator= (const Identity< AnyType >)
Definition at line 79 of file SquareMatrix.C.
References n, and Foam::Zero.
sortPermutation() [2/2]
template<class Type > template<class CompOp > Foam::List< Foam::label > sortPermutation (CompOp & compare) const
Definition at line 30 of file SquareMatrix.C.
References p.
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/SquareMatrix/SquareMatrix.H
src/OpenFOAM/matrices/SquareMatrix/SquareMatrix.C
src/OpenFOAM/matrices/SquareMatrix/SquareMatrixI.H