OpenFOAM: DelaunayMesh< Triangulation > Class Template Reference
DelaunayMesh< Triangulation > Class Template Reference
The vertex and cell classes must have an index defined.
#include <DelaunayMesh.H>
Public Types
typedef Triangulation::Cell_handle Cell_handle
typedef Triangulation::Vertex_handle Vertex_handle
typedef Triangulation::Edge Edge
typedef Triangulation::Point Point
typedef Triangulation::Facet Facet
typedef Triangulation::Finite_vertices_iterator Finite_vertices_iterator
typedef Triangulation::Finite_cells_iterator Finite_cells_iterator
typedef Triangulation::Finite_facets_iterator Finite_facets_iterator
Public Member Functions
DelaunayMesh (const Time &runTime)
DelaunayMesh (const Time &runTime, const word &meshName)
~DelaunayMesh ()
const Time & time () const
void timeCheck (const string &description, const bool check=true) const
label getNewCellIndex () const
label getNewVertexIndex () const
label cellCount () const
label vertexCount () const
void resetCellCount ()
void resetVertexCount ()
void reset ()
Map< label > insertPoints (const List< Vb > &vertices, const bool reIndex)
template<class PointIterator >
Map< label > rangeInsertWithInfo (PointIterator begin, PointIterator end, bool printErrors=false, bool reIndex=true)
void printInfo (Ostream &os) const
void printVertexInfo (Ostream &os) const
autoPtr< polyMesh > createMesh (const fileName &name, labelPairLookup &vertexMap, labelList &cellMap, const bool writeDelaunayData=true) const
Detailed Description
template<class Triangulation>
class Foam::DelaunayMesh< Triangulation >
The vertex and cell classes must have an index defined.
Source files
DelaunayMesh.H
DelaunayMeshI.H
DelaunayMesh.C
DelaunayMeshIO.C
Definition at line 56 of file DelaunayMesh.H.
Member Typedef Documentation
Cell_handle
template<class Triangulation > typedef Triangulation::Cell_handle Cell_handle
Definition at line 62 of file DelaunayMesh.H.
Vertex_handle
template<class Triangulation > typedef Triangulation::Vertex_handle Vertex_handle
Definition at line 63 of file DelaunayMesh.H.
Edge
template<class Triangulation > typedef Triangulation::Edge Edge
Definition at line 64 of file DelaunayMesh.H.
Point
template<class Triangulation > typedef Triangulation::Point Point
Definition at line 65 of file DelaunayMesh.H.
Facet
template<class Triangulation > typedef Triangulation::Facet Facet
Definition at line 66 of file DelaunayMesh.H.
Finite_vertices_iterator
template<class Triangulation > typedef Triangulation::Finite_vertices_iterator Finite_vertices_iterator
Definition at line 69 of file DelaunayMesh.H.
Finite_cells_iterator
template<class Triangulation > typedef Triangulation::Finite_cells_iterator Finite_cells_iterator
Definition at line 71 of file DelaunayMesh.H.
Finite_facets_iterator
template<class Triangulation > typedef Triangulation::Finite_facets_iterator Finite_facets_iterator
Definition at line 73 of file DelaunayMesh.H.
Constructor & Destructor Documentation
DelaunayMesh() [1/2]
template<class Triangulation > DelaunayMesh (const Time & runTime) explicit
DelaunayMesh() [2/2]
template<class Triangulation > DelaunayMesh (const Time & runTime, const word & meshName)
~DelaunayMesh()
template<class Triangulation > ~DelaunayMesh ()
Member Function Documentation
time()
template<class Triangulation > const Foam::Time & time () const inline
Definition at line 24 of file DelaunayMeshI.H.
timeCheck()
template<class Triangulation > void timeCheck (const string & description, const bool check = true) const inline
Definition at line 31 of file DelaunayMeshI.H.
References Foam::check(), Foam::endl(), Foam::Info, Foam::nl, and word::null.
getNewCellIndex()
template<class Triangulation > Foam::label getNewCellIndex () const inline
Definition at line 58 of file DelaunayMeshI.H.
References Foam::endl(), Foam::labelMax, and WarningInFunction.
getNewVertexIndex()
template<class Triangulation > Foam::label getNewVertexIndex () const inline
Definition at line 73 of file DelaunayMeshI.H.
References Foam::endl(), Foam::labelMax, and WarningInFunction.
Referenced by cellShapeControlMesh::insert().
cellCount()
template<class Triangulation > Foam::label cellCount () const inline
Definition at line 88 of file DelaunayMeshI.H.
vertexCount()
template<class Triangulation > Foam::label vertexCount () const inline
Definition at line 95 of file DelaunayMeshI.H.
resetCellCount()
template<class Triangulation > void resetCellCount () inline
Definition at line 102 of file DelaunayMeshI.H.
resetVertexCount()
template<class Triangulation > void resetVertexCount () inline
Definition at line 109 of file DelaunayMeshI.H.
reset()
template<class Triangulation > void reset ()
insertPoints()
template<class Triangulation > Map< label > insertPoints (const List< Vb > & vertices, const bool reIndex)
rangeInsertWithInfo()
template<class Triangulation > template<class PointIterator > Map< label > rangeInsertWithInfo (PointIterator begin, PointIterator end, bool printErrors = false, bool reIndex = true)
printInfo()
template<class Triangulation > void printInfo (Ostream & os) const
printVertexInfo()
template<class Triangulation > void printVertexInfo (Ostream & os) const
createMesh()
template<class Triangulation > autoPtr< polyMesh > createMesh (const fileName & name, labelPairLookup & vertexMap, labelList & cellMap, const bool writeDelaunayData = true) const
The documentation for this class was generated from the following files:
applications/utilities/mesh/generation/foamyMesh/conformalVoronoiMesh/DelaunayMesh/DelaunayMesh.H
applications/utilities/mesh/generation/foamyMesh/conformalVoronoiMesh/DelaunayMesh/DelaunayMeshI.H