OpenFOAM: SLListBase Class Reference
SLListBase Class Reference
Base for singly-linked lists.
#include <SLListBase.H>
Classes
class const_iterator
class iterator
struct link
Public Member Functions
SLListBase ()=default
SLListBase (const SLListBase &)=delete
void operator= (const SLListBase &)=delete
~SLListBase ()=default
bool empty () const noexcept
label size () const noexcept
link * front ()
const link * front () const
link * back ()
const link * back () const
void push_front (link *item)
void push_back (link *item)
link * removeHead ()
link * remove (link *item)
link * remove (iterator &iter)
void clear ()
void swap (SLListBase &lst)
void transfer (SLListBase &lst)
iterator begin ()
const_iterator cbegin () const
const_iterator crbegin () const =delete
const iterator & end ()
const const_iterator & cend () const
const const_iterator & crend () const =delete
link * first ()
const link * first () const
link * last ()
const link * last () const
void prepend (link *item)
void append (link *item)
Protected Member Functions
template<class IteratorType >
IteratorType iterator_first () const
template<class IteratorType >
IteratorType iterator_last () const
Static Protected Member Functions
template<class IteratorType >
static const IteratorType & iterator_end ()
template<class IteratorType >
static const IteratorType & iterator_rend ()=delete
Friends
class iterator
class const_iterator
Detailed Description
Base for singly-linked lists.
The iterators associated with the list only have a core functionality for navigation, with additional functionality to be added by inheriting classes. The node iterators always have a node-pointer as the first member data, which allows reinterpret_cast from anything else with a nullptr as its first data member. The nullObject is such an item (with a nullptr data member).
Source files
SLListBase.H
SLListBaseI.H
SLListBase.C
Definition at line 57 of file SLListBase.H.
Constructor & Destructor Documentation
SLListBase() [1/2]
SLListBase () default
SLListBase() [2/2]
SLListBase (const SLListBase &) delete
~SLListBase()
~SLListBase () default
Member Function Documentation
iterator_end()
template<class IteratorType > const IteratorType & iterator_end () inline static protected
Definition at line 28 of file SLListBaseI.H.
References Foam::nullObjectPtr.
iterator_rend()
template<class IteratorType > static const IteratorType & iterator_rend () static protected delete
iterator_first()
template<class IteratorType > IteratorType iterator_first () const inline protected
Definition at line 35 of file SLListBaseI.H.
iterator_last()
template<class IteratorType > IteratorType iterator_last () const inline protected
Definition at line 50 of file SLListBaseI.H.
operator=()
void operator= (const SLListBase &) delete
empty()
bool empty () const inline noexcept
Definition at line 140 of file SLListBase.H.
size()
label size () const inline noexcept
Definition at line 143 of file SLListBase.H.
Referenced by SLListBase::begin(), and SLListBase::cbegin().
front() [1/2]
Foam::SLListBase::link * front () inline
Definition at line 67 of file SLListBaseI.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Referenced by SLListBase::first(), and SLListBase::first().
front() [2/2]
const Foam::SLListBase::link * front () const inline
Definition at line 80 of file SLListBaseI.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
back() [1/2]
Foam::SLListBase::link * back () inline
Definition at line 93 of file SLListBaseI.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Referenced by SLListBase::last(), and SLListBase::last().
back() [2/2]
const Foam::SLListBase::link * back () const inline
Definition at line 106 of file SLListBaseI.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
push_front()
void push_front (SLListBase::link * item)
Definition at line 27 of file SLListBase.C.
References SLListBase::link::next_.
Referenced by SLListBase::prepend().
push_back()
void push_back (SLListBase::link * item)
Definition at line 49 of file SLListBase.C.
Referenced by SLListBase::append().
removeHead()
Foam::SLListBase::link * removeHead ()
Definition at line 70 of file SLListBase.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
remove() [1/2]
Foam::SLListBase::link * remove (SLListBase::link * item)
Definition at line 99 of file SLListBase.C.
References SLListBase::iterator::get_node(), SLListBase::iterator::next(), SLListBase::link::next_, and p.
remove() [2/2]
Foam::SLListBase::link * remove (SLListBase::iterator & iter) inline
Definition at line 151 of file SLListBaseI.H.
clear()
void clear () inline
Definition at line 118 of file SLListBaseI.H.
swap()
void swap (SLListBase & lst) inline
Definition at line 125 of file SLListBaseI.H.
transfer()
void transfer (SLListBase & lst) inline
Definition at line 137 of file SLListBaseI.H.
References PtrList< T >::clear().
begin()
Foam::SLListBase::iterator begin () inline
Definition at line 230 of file SLListBaseI.H.
References SLListBase::end(), and SLListBase::size().
cbegin()
Foam::SLListBase::const_iterator cbegin () const inline
Definition at line 326 of file SLListBaseI.H.
References SLListBase::cend(), and SLListBase::size().
crbegin()
const_iterator crbegin () const delete
end()
const Foam::SLListBase::iterator & end () inline
Definition at line 242 of file SLListBaseI.H.
Referenced by SLListBase::begin().
cend()
const Foam::SLListBase::const_iterator & cend () const inline
Definition at line 249 of file SLListBaseI.H.
Referenced by SLListBase::cbegin().
crend()
const const_iterator & crend () const delete
first() [1/2]
link * first () inline
Definition at line 300 of file SLListBase.H.
References SLListBase::front().
first() [2/2]
const link * first () const inline
Definition at line 304 of file SLListBase.H.
References SLListBase::front().
last() [1/2]
link * last () inline
Definition at line 308 of file SLListBase.H.
References SLListBase::back().
last() [2/2]
const link * last () const inline
Definition at line 312 of file SLListBase.H.
References SLListBase::back().
prepend()
void prepend (link * item) inline
Definition at line 316 of file SLListBase.H.
References SLListBase::push_front().
append()
void append (link * item) inline
Definition at line 320 of file SLListBase.H.
References SLListBase::push_back().
Friends And Related Symbol Documentation
iterator
friend class iterator friend
Definition at line 116 of file SLListBase.H.
const_iterator
friend class const_iterator friend
Definition at line 119 of file SLListBase.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/LinkedLists/linkTypes/SLListBase/SLListBase.H
src/OpenFOAM/containers/LinkedLists/linkTypes/SLListBase/SLListBase.C
src/OpenFOAM/containers/LinkedLists/linkTypes/SLListBase/SLListBaseI.H