OpenFOAM: searchableSurface Class Reference
searchableSurface Class Reference abstract
Base class of (analytical or triangulated) surface. Encapsulates all the search routines. WIP.
#include <searchableSurface.H>
Classes
class iNew
Public Member Functions
TypeName ("searchableSurface")
declareRunTimeSelectionTable (autoPtr, searchableSurface, dict,(const IOobject &io, const dictionary &dict),(io, dict))
searchableSurface (const IOobject &io)
virtual autoPtr< searchableSurface > clone () const
virtual ~searchableSurface ()=default
virtual bool global () const
virtual fileName filePath () const
virtual const boundBox & bounds () const
virtual boundBox & bounds ()
virtual const wordList & regions () const =0
virtual bool hasVolumeType () const
virtual volumeType outsideVolumeType () const =0
virtual label size () const =0
virtual label globalSize () const
virtual tmp< pointField > coordinates () const =0
virtual void boundingSpheres (pointField &centres, scalarField &radiusSqr) const =0
virtual tmp< pointField > points () const =0
virtual bool overlaps (const boundBox &bb) const =0
virtual void findNearest (const pointField &sample, const scalarField &nearestDistSqr, List< pointIndexHit > &) const =0
virtual void findNearest (const pointField &samples, const scalarField &nearestDistSqr, const labelList &regionIndices, List< pointIndexHit > &info) const
virtual void findLine (const pointField &start, const pointField &end, List< pointIndexHit > &) const =0
virtual void findLineAny (const pointField &start, const pointField &end, List< pointIndexHit > &) const =0
virtual void findLineAll (const pointField &start, const pointField &end, List< List< pointIndexHit > > &) const =0
virtual void getRegion (const List< pointIndexHit > &, labelList &region) const =0
virtual void getNormal (const List< pointIndexHit > &, vectorField &normal) const =0
virtual void getVolumeType (const pointField &, List< volumeType > &) const =0
virtual void findNearest (const pointField &sample, const scalarField &nearestDistSqr, List< pointIndexHit > &, vectorField &normal, labelList &region) const
virtual void distribute (const List< treeBoundBox > &, const bool keepNonLocal, autoPtr< mapDistribute > &faceMap, autoPtr< mapDistribute > &pointMap)
virtual void setField (const labelList &values)
virtual void getField (const List< pointIndexHit > &, labelList &values) const
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
regIOobject (const IOobject &io, const bool isTimeObject=false)
regIOobject (const regIOobject &rio)
regIOobject (const regIOobject &rio, bool registerCopy)
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
regIOobject (const IOobject &io, const regIOobject &rio)
virtual ~regIOobject ()
bool checkIn ()
bool checkOut ()
virtual void addWatch ()
bool registered () const noexcept
bool ownedByRegistry () const noexcept
bool store ()
void release (const bool unregister=false) noexcept
label eventNo () const noexcept
label & eventNo () noexcept
bool upToDate (const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
void setUpToDate ()
virtual void rename (const word &newName)
const dictionary * findMetaData () const noexcept
dictionary & getMetaData () noexcept
void removeMetaData ()
virtual void updateMetaData ()
bool headerOk ()
Istream & readStream (const word &, const bool readOnProc=true)
void close ()
virtual bool readData (Istream &)
virtual bool read ()
virtual label addWatch (const fileName &)
const labelList & watchIndices () const noexcept
labelList & watchIndices () noexcept
virtual bool modified () const
virtual bool readIfModified ()
virtual bool writeData (Ostream &) const =0
virtual bool writeObject (IOstreamOption streamOpt, const bool writeOnProc) const
virtual bool write (const bool writeOnProc=true) const
void operator= (const IOobject &io)
virtual bool writeObject (IOstreamOption::streamFormat fmt, IOstreamOption::versionNumber ver, IOstreamOption::compressionType cmp, const bool writeOnProc) const
Public Member Functions inherited from IOobject
TypeName ("IOobject")
IOobject (const IOobject &)=default
virtual ~IOobject ()=default
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const fileName &path, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const fileName &path, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const IOobject &io, const objectRegistry &registry)
IOobject (const IOobject &io, const word &name)
IOobject (const IOobject &io, const word &name, const fileName &local)
IOobject (const IOobject &io, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt)
IOobject (const IOobject &io, IOobjectOption::registerOption regOpt)
autoPtr< IOobject > clone () const
autoPtr< IOobject > clone (const objectRegistry &registry) const
const objectRegistry & db () const noexcept
const Time & time () const noexcept
const word & name () const noexcept
const word & headerClassName () const noexcept
word & headerClassName () noexcept
const string & note () const noexcept
string & note () noexcept
unsigned labelByteSize () const noexcept
unsigned scalarByteSize () const noexcept
void resetHeader (const word &newName=word::null)
bool hasHeaderClass () const noexcept
template<class Type >
bool isHeaderClass () const
template<class Type >
bool isHeaderClassName () const
word group () const
word member () const
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const noexcept
fileName & instance () noexcept
const fileName & local () const noexcept
fileName path () const
fileName path (const word &instance, const fileName &local=fileName::null) const
fileName objectPath () const
fileName objectRelPath () const
fileName localFilePath (const word &typeName, const bool search=true) const
fileName globalFilePath (const word &typeName, const bool search=true) const
IOstreamOption parseHeader (const dictionary &headerDict)
bool readHeader (Istream &is)
bool readHeader (dictionary &headerDict, Istream &is)
template<class Type >
bool typeHeaderOk (const bool checkType=true, const bool search=true, const bool verbose=true)
template<class Type >
void warnNoRereading () const
bool writeHeader (Ostream &os) const
bool writeHeader (Ostream &os, const word &objectType) const
void writeHeader (dictionary &dict, IOstreamOption streamOpt) const
void writeHeader (dictionary &dict, const word &objectType, IOstreamOption streamOpt) const
bool good () const noexcept
bool bad () const noexcept
InfoProxy< IOobject > info () const noexcept
void operator= (const IOobject &io)
template<>
bool isHeaderClass () const
template<class StringType >
Foam::word groupName (StringType base, const word &group)
Public Member Functions inherited from IOobjectOption
constexpr IOobjectOption (readOption rOpt=readOption::NO_READ, writeOption wOpt=writeOption::NO_WRITE, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (readOption rOpt, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (writeOption wOpt, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (registerOption registerObject, bool globalObject=false) noexcept
constexpr IOobjectOption (readOption rOpt, writeOption wOpt, bool registerObject, bool globalObject=false) noexcept
constexpr IOobjectOption (bool registerObject, bool globalObject=false) noexcept
readOption readOpt () const noexcept
readOption readOpt (readOption opt) noexcept
writeOption writeOpt () const noexcept
writeOption writeOpt (writeOption opt) noexcept
bool registerObject () const noexcept
bool registerObject (bool on) noexcept
bool globalObject () const noexcept
bool globalObject (bool on) noexcept
bool isAnyRead () const noexcept
bool isReadRequired () const noexcept
bool isReadOptional () const noexcept
readOption & readOpt () noexcept
writeOption & writeOpt () noexcept
bool & registerObject () noexcept
bool & globalObject () noexcept
Static Public Member Functions
static autoPtr< searchableSurface > New (const word &surfaceType, const IOobject &io, const dictionary &dict)
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *p)
template<class Type >
static Type & store (autoPtr< Type > &ptr)
template<class Type >
static Type & store (autoPtr< Type > &&ptr)
template<class Type >
static Type & store (refPtr< Type > &ptr)
template<class Type >
static Type & store (refPtr< Type > &&ptr)
template<class Type >
static Type & store (tmp< Type > &ptr)
template<class Type >
static Type & store (tmp< Type > &&ptr)
Static Public Member Functions inherited from IOobject
static bool bannerEnabled () noexcept
static bool bannerEnabled (bool on) noexcept
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
template<class StringType >
static word groupName (StringType base, const word &group)
static word group (const word &name)
static word member (const word &name)
static word scopedName (const std::string &scope, const word &name)
static IOobject selectIO (const IOobject &io, const fileName &altFile, const word &ioName="")
static Ostream & writeBanner (Ostream &os, const bool noSyntaxHint=false)
static Ostream & writeDivider (Ostream &os)
static Ostream & writeEndDivider (Ostream &os)
Static Public Member Functions inherited from IOobjectOption
static bool isAnyRead (readOption opt) noexcept
static bool isReadRequired (readOption opt) noexcept
static bool isReadOptional (readOption opt) noexcept
static readOption lazierRead (readOption opt) noexcept
Additional Inherited Members
Public Types inherited from IOobject
enum objectState : char { GOOD , BAD }
enum fileCheckTypes : char { timeStamp , timeStampMaster , inotify , inotifyMaster }
Public Types inherited from IOobjectOption
enum readOption : unsigned char {
NO_READ = 0 , MUST_READ = 0x1 , READ_MODIFIED = 0x3 , MUST_READ_IF_MODIFIED = 0x3 ,
LAZY_READ = 0x4 , READ_IF_PRESENT = 0x4
}
enum writeOption : unsigned char { NO_WRITE = 0 , AUTO_WRITE = 0x10 }
enum registerOption : unsigned char { NO_REGISTER = 0 , REGISTER = 1 }
Static Public Attributes inherited from IOobject
static const Enum< fileCheckTypes > fileCheckTypesNames
static char scopeSeparator
static fileCheckTypes fileModificationChecking
static float fileModificationSkew
static int maxFileModificationPolls
Protected Member Functions inherited from regIOobject
bool readHeaderOk (const IOstreamOption::streamFormat fmt, const word &typeName)
Protected Member Functions inherited from IOobject
void setBad (const string &s)
Static Protected Member Functions inherited from IOobject
static void writeHeaderContent (Ostream &os, const IOobject &io, const word &objectType, const dictionary *metaDataDict=nullptr)
static void writeHeaderContent (dictionary &dict, const IOobject &io, const word &objectType, IOstreamOption streamOpt, const dictionary *metaDataDict=nullptr)
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
Detailed Description
Base class of (analytical or triangulated) surface. Encapsulates all the search routines. WIP.
Information returned is usually a pointIndexHit:
bool : was intersection/nearest found?
point : intersection point or nearest point
index : unique index on surface (e.g. triangle for triSurfaceMesh)
Source files
searchableSurface.H
searchableSurface.C
Definition at line 65 of file searchableSurface.H.
Constructor & Destructor Documentation
searchableSurface()
searchableSurface (const IOobject & io)
Definition at line 61 of file searchableSurface.C.
~searchableSurface()
virtual ~searchableSurface () virtual default
Member Function Documentation
TypeName()
TypeName ("searchableSurface")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , searchableSurface , dict , (const IOobject &io, const dictionary &dict) , (io, dict))
clone()
virtual autoPtr< searchableSurface > clone () const inline virtual
Definition at line 137 of file searchableSurface.H.
References NotImplemented.
New()
Foam::autoPtr< Foam::searchableSurface > New (const word & surfaceType, const IOobject & io, const dictionary & dict) static
Definition at line 35 of file searchableSurface.C.
References dict, Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, and io().
Referenced by searchableSurface::iNew::operator()(), searchableSurfaces::searchableSurfaces(), cyclicAMIPolyPatch::surfPtr(), and mappedPatchBase::surfPtr().
global()
virtual bool global () const inline virtual
Reimplemented from regIOobject.
Reimplemented in triSurfaceMesh, and distributedTriSurfaceMesh.
Definition at line 162 of file searchableSurface.H.
filePath()
virtual fileName filePath () const inline virtual
Reimplemented from regIOobject.
Reimplemented in triSurfaceMesh, and distributedTriSurfaceMesh.
Definition at line 169 of file searchableSurface.H.
References IOobject::globalFilePath(), and Foam::type().
bounds() [1/2]
virtual const boundBox & bounds () const inline virtual
Definition at line 175 of file searchableSurface.H.
Referenced by distributedTriSurfaceMesh::distributedTriSurfaceMesh(), distributedTriSurfaceMesh::distributedTriSurfaceMesh(), distributedTriSurfaceMesh::distributedTriSurfaceMesh(), searchableBox::searchableBox(), searchableBox::searchableBox(), searchableCone::searchableCone(), searchableCone::searchableCone(), searchableCylinder::searchableCylinder(), searchableCylinder::searchableCylinder(), searchableDisk::searchableDisk(), searchableExtrudedCircle::searchableExtrudedCircle(), searchablePlane::searchablePlane(), searchablePlane::searchablePlane(), searchablePlate::searchablePlate(), searchableSphere::searchableSphere(), searchableSurfaceCollection::searchableSurfaceCollection(), searchableSurfaceWithGaps::searchableSurfaceWithGaps(), triSurfaceMesh::triSurfaceMesh(), triSurfaceMesh::triSurfaceMesh(), triSurfaceMesh::triSurfaceMesh(), triSurfaceMesh::triSurfaceMesh(), and triSurfaceMesh::triSurfaceMesh().
bounds() [2/2]
virtual boundBox & bounds () inline virtual
Definition at line 181 of file searchableSurface.H.
regions()
virtual const wordList & regions () const pure virtual
Implemented in searchableBox, searchableCone, searchableCylinder, searchableDisk, searchableExtrudedCircle, searchablePlane, searchablePlate, searchableRotatedBox, searchableSphere, searchableSurfaceCollection, searchableSurfaceWithGaps, and triSurfaceMesh.
hasVolumeType()
bool hasVolumeType () const virtual
Reimplemented in closedTriSurfaceMesh, searchableBox, searchableCone, searchableCylinder, searchableDisk, searchableExtrudedCircle, searchablePlane, searchablePlate, searchableRotatedBox, searchableSphere, searchableSurfaceCollection, searchableSurfaceWithGaps, and triSurfaceMesh.
Definition at line 69 of file searchableSurface.C.
outsideVolumeType()
virtual volumeType outsideVolumeType () const pure virtual
Implemented in searchableBox, searchableCone, searchableCylinder, searchableDisk, searchableExtrudedCircle, searchablePlane, searchablePlate, searchableRotatedBox, searchableSphere, searchableSurfaceCollection, searchableSurfaceWithGaps, and triSurfaceMesh.
size()
virtual label size () const pure virtual
Implemented in searchableBox, searchableCone, searchableCylinder, searchableDisk, searchableExtrudedCircle, searchablePlane, searchablePlate, searchableRotatedBox, searchableSphere, searchableSurfaceCollection, searchableSurfaceWithGaps, and triSurfaceMesh.
Referenced by searchableSurface::globalSize().
globalSize()
virtual label globalSize () const inline virtual
Reimplemented in distributedTriSurfaceMesh.
Definition at line 201 of file searchableSurface.H.
References searchableSurface::size().
coordinates()
virtual tmp< pointField > coordinates () const pure virtual
Implemented in searchableBox, searchableCone, searchableCylinder, searchableDisk, searchableExtrudedCircle, searchablePlane, searchablePlate, searchableRotatedBox, searchableSphere, searchableSurfaceCollection, searchableSurfaceWithGaps, and triSurfaceMesh.
boundingSpheres()
virtual void boundingSpheres (pointField & centres, scalarField & radiusSqr) const pure virtual
Implemented in searchableBox, searchableCone, searchableCylinder, searchableDisk, searchableExtrudedCircle, searchablePlane, searchablePlate, searchableRotatedBox, searchableSphere, searchableSurfaceCollection, searchableSurfaceWithGaps, and triSurfaceMesh.
points()
virtual tmp< pointField > points () const pure virtual
Implemented in searchableBox, searchableCone, searchableCylinder, searchableDisk, searchableExtrudedCircle, searchablePlane, searchablePlate, searchableRotatedBox, searchableSphere, searchableSurfaceCollection, searchableSurfaceWithGaps, and triSurfaceMesh.
overlaps()
virtual bool overlaps (const boundBox & bb) const pure virtual
Implemented in searchableBox, searchableCone, searchableCylinder, searchableDisk, searchableExtrudedCircle, searchablePlane, searchablePlate, searchableRotatedBox, searchableSphere, searchableSurfaceCollection, searchableSurfaceWithGaps, and triSurfaceMesh.
findNearest() [1/3]
virtual void findNearest (const pointField & sample, const scalarField & nearestDistSqr, List< pointIndexHit > &) const pure virtual
Implemented in searchableBox, searchableCone, searchableCylinder, searchableDisk, searchableExtrudedCircle, searchablePlane, searchablePlate, searchableRotatedBox, searchableSphere, searchableSurfaceCollection, triSurfaceMesh, distributedTriSurfaceMesh, searchableRotatedBox, and searchableSurfaceWithGaps.
Referenced by searchableSurface::findNearest(), and AMIInterpolation::projectPointsToSurface().
findNearest() [2/3]
virtual void findNearest (const pointField & samples, const scalarField & nearestDistSqr, const labelList & regionIndices, List< pointIndexHit > & info) const inline virtual
Reimplemented in triSurfaceMesh, searchableRotatedBox, and distributedTriSurfaceMesh.
Definition at line 290 of file searchableSurface.H.
References searchableSurface::findNearest(), IOobject::info(), and samples().
findLine()
virtual void findLine (const pointField & start, const pointField & end, List< pointIndexHit > &) const pure virtual
Implemented in searchableBox, searchableCone, searchableCylinder, searchableDisk, searchableExtrudedCircle, searchablePlane, searchablePlate, searchableRotatedBox, searchableSphere, searchableSurfaceCollection, searchableSurfaceWithGaps, triSurfaceMesh, and distributedTriSurfaceMesh.
findLineAny()
virtual void findLineAny (const pointField & start, const pointField & end, List< pointIndexHit > &) const pure virtual
Implemented in searchableBox, searchableCone, searchableCylinder, searchableDisk, searchableExtrudedCircle, searchablePlane, searchablePlate, searchableRotatedBox, searchableSphere, searchableSurfaceCollection, searchableSurfaceWithGaps, triSurfaceMesh, and distributedTriSurfaceMesh.
findLineAll()
virtual void findLineAll (const pointField & start, const pointField & end, List< List< pointIndexHit > > &) const pure virtual
Implemented in searchableBox, searchableCone, searchableCylinder, searchableDisk, searchableExtrudedCircle, searchablePlane, searchablePlate, searchableRotatedBox, searchableSphere, searchableSurfaceCollection, searchableSurfaceWithGaps, triSurfaceMesh, and distributedTriSurfaceMesh.
Referenced by extendedEdgeMesh::cut().
getRegion()
virtual void getRegion (const List< pointIndexHit > & , labelList & region) const pure virtual
Implemented in searchableBox, searchableCone, searchableCylinder, searchableDisk, searchableExtrudedCircle, searchablePlane, searchablePlate, searchableRotatedBox, searchableSphere, searchableSurfaceCollection, triSurfaceMesh, distributedTriSurfaceMesh, and searchableSurfaceWithGaps.
getNormal()
virtual void getNormal (const List< pointIndexHit > & , vectorField & normal) const pure virtual
Implemented in searchableBox, searchableCone, searchableCylinder, searchableExtrudedCircle, searchablePlane, searchablePlate, searchableRotatedBox, searchableSphere, searchableSurfaceCollection, triSurfaceMesh, distributedTriSurfaceMesh, searchableDisk, and searchableSurfaceWithGaps.
getVolumeType()
virtual void getVolumeType (const pointField & , List< volumeType > &) const pure virtual
Implemented in searchableExtrudedCircle, searchablePlane, searchablePlate, distributedTriSurfaceMesh, searchableBox, searchableCone, searchableCylinder, searchableDisk, searchableRotatedBox, searchableSphere, searchableSurfaceCollection, triSurfaceMesh, and searchableSurfaceWithGaps.
Referenced by extendedEdgeMesh::select().
findNearest() [3/3]
void findNearest (const pointField & sample, const scalarField & nearestDistSqr, List< pointIndexHit > & info, vectorField & normal, labelList & region) const virtual
Reimplemented in searchableRotatedBox.
Definition at line 75 of file searchableSurface.C.
distribute()
virtual void distribute (const List< treeBoundBox > & , const bool keepNonLocal, autoPtr< mapDistribute > & faceMap, autoPtr< mapDistribute > & pointMap) inline virtual
Reimplemented in searchableSurfaceCollection, and distributedTriSurfaceMesh.
Definition at line 367 of file searchableSurface.H.
setField()
virtual void setField (const labelList & values) inline virtual
Reimplemented in searchableSurfaceCollection, searchableSurfaceWithGaps, and triSurfaceMesh.
Definition at line 377 of file searchableSurface.H.
getField()
virtual void getField (const List< pointIndexHit > & , labelList & values) const inline virtual
Reimplemented in searchableSurfaceCollection, triSurfaceMesh, distributedTriSurfaceMesh, and searchableSurfaceWithGaps.
Definition at line 383 of file searchableSurface.H.
The documentation for this class was generated from the following files:
src/meshTools/searchableSurfaces/searchableSurface/searchableSurface.H
src/meshTools/searchableSurfaces/searchableSurface/searchableSurface.C