OpenFOAM: outletMappedUniformInletHeatAdditionFvPatchField Class Reference
outletMappedUniformInletHeatAdditionFvPatchField Class Reference
Boundary conditions » Inlet
This temperature boundary condition averages the temperature over the "outlet" patch specified by name "outletPatchName" and applies an extra heat source. This is set as a uniform temperature value on this patch. Additionally TMin/TMax limits can be applied.
#include <outletMappedUniformInletHeatAdditionFvPatchField.H>
Public Member Functions
TypeName ("outletMappedUniformInletHeatAddition")
outletMappedUniformInletHeatAdditionFvPatchField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
outletMappedUniformInletHeatAdditionFvPatchField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
outletMappedUniformInletHeatAdditionFvPatchField (const outletMappedUniformInletHeatAdditionFvPatchField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
outletMappedUniformInletHeatAdditionFvPatchField (const outletMappedUniformInletHeatAdditionFvPatchField &)
virtual tmp< fvPatchField< scalar > > clone () const
outletMappedUniformInletHeatAdditionFvPatchField (const outletMappedUniformInletHeatAdditionFvPatchField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchField< scalar > > clone (const DimensionedField< scalar, volMesh > &iF) const
const word & outletPatchName () const
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
This temperature boundary condition averages the temperature over the "outlet" patch specified by name "outletPatchName" and applies an extra heat source. This is set as a uniform temperature value on this patch. Additionally TMin/TMax limits can be applied.
Patch usage
Property Description Required Default value
outletPatch name of outlet patch yes
Q Heat addition yes
phi flux field name no phi
TMin min temperature limit no 0.0
TMax max temperature limit no 5000.0
Example of the boundary condition specification:
    myPatch
    {
        type            outletMappedUniformInletHeatAddition;
        outletPatch     aPatch;
        Q               10;     // Heat addition in W
        phi             phi;
        value           uniform 0;
    }
See also
Foam::fixedValueFvPatchField
Source files
outletMappedUniformInletHeatAdditionFvPatchField.H
outletMappedUniformInletHeatAdditionFvPatchField.C
Definition at line 109 of file outletMappedUniformInletHeatAdditionFvPatchField.H.
Constructor & Destructor Documentation
outletMappedUniformInletHeatAdditionFvPatchField() [1/5]
outletMappedUniformInletHeatAdditionFvPatchField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 29 of file outletMappedUniformInletHeatAdditionFvPatchField.C.
outletMappedUniformInletHeatAdditionFvPatchField() [2/5]
outletMappedUniformInletHeatAdditionFvPatchField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 63 of file outletMappedUniformInletHeatAdditionFvPatchField.C.
outletMappedUniformInletHeatAdditionFvPatchField() [3/5]
outletMappedUniformInletHeatAdditionFvPatchField (const outletMappedUniformInletHeatAdditionFvPatchField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 45 of file outletMappedUniformInletHeatAdditionFvPatchField.C.
outletMappedUniformInletHeatAdditionFvPatchField() [4/5]
outletMappedUniformInletHeatAdditionFvPatchField (const outletMappedUniformInletHeatAdditionFvPatchField & ptf)
Definition at line 81 of file outletMappedUniformInletHeatAdditionFvPatchField.C.
outletMappedUniformInletHeatAdditionFvPatchField() [5/5]
outletMappedUniformInletHeatAdditionFvPatchField (const outletMappedUniformInletHeatAdditionFvPatchField & ptf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 97 of file outletMappedUniformInletHeatAdditionFvPatchField.C.
Member Function Documentation
TypeName()
TypeName ("outletMappedUniformInletHeatAddition")
clone() [1/2]
virtual tmp< fvPatchField< scalar > > clone () const inline virtual
Definition at line 170 of file outletMappedUniformInletHeatAdditionFvPatchField.H.
clone() [2/2]
virtual tmp< fvPatchField< scalar > > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 186 of file outletMappedUniformInletHeatAdditionFvPatchField.H.
outletPatchName()
const word & outletPatchName () const inline
Definition at line 203 of file outletMappedUniformInletHeatAdditionFvPatchField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 116 of file outletMappedUniformInletHeatAdditionFvPatchField.C.
References Foam::abort(), Foam::clamp(), basicThermo::dictName, Foam::FatalError, FatalErrorInFunction, Foam::gAverage(), Foam::gSum(), Foam::operator==(), phi, and pp().
write()
void write (Ostream & os) const virtual
Definition at line 181 of file outletMappedUniformInletHeatAdditionFvPatchField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntry(), Ostream::writeEntryIfDifferent(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/thermoTools/derivedFvPatchFields/outletMappedUniformInletHeatAddition/outletMappedUniformInletHeatAdditionFvPatchField.H
src/thermoTools/derivedFvPatchFields/outletMappedUniformInletHeatAddition/outletMappedUniformInletHeatAdditionFvPatchField.C