OpenFOAM: meshWaveAddressing Class Reference
meshWaveAddressing Class Reference
Variant of patchDistMethods::meshWave that stores nearest-wall addressing instead of directly transporting wall information.
#include <meshWaveAddressingPatchDistMethod.H>
Public Member Functions
TypeName ("meshWaveAddressing")
meshWaveAddressing (const dictionary &dict, const fvMesh &mesh, const labelHashSet &patchIDs)
meshWaveAddressing (const fvMesh &mesh, const labelHashSet &patchIDs, const bool correctWalls=true)
virtual bool correct (volScalarField &y)
virtual bool correct (volScalarField &y, volVectorField &n)
Public Member Functions inherited from patchDistMethod
TypeName ("patchDistMethod")
declareRunTimeSelectionTable (autoPtr, patchDistMethod, dictionary,(const dictionary &dict, const fvMesh &mesh, const labelHashSet &patchIDs),(dict, mesh, patchIDs))
patchDistMethod (const fvMesh &mesh, const labelHashSet &patchIDs)
virtual ~patchDistMethod ()
const labelHashSet & patchIDs () const
virtual bool movePoints ()
virtual void updateMesh (const mapPolyMesh &)
template<class Type >
Foam::wordList patchTypes (const fvMesh &mesh, const labelHashSet &patchIDs)
Protected Member Functions
meshWaveAddressing (const meshWaveAddressing &)=delete
void operator= (const meshWaveAddressing &)=delete
Protected Member Functions inherited from patchDistMethod
patchDistMethod (const patchDistMethod &)=delete
void operator= (const patchDistMethod &)=delete
Protected Attributes
const bool correctWalls_
Protected Attributes inherited from patchDistMethod
const fvMesh & mesh_
const labelHashSet patchIDs_
Additional Inherited Members
Static Public Member Functions inherited from patchDistMethod
static autoPtr< patchDistMethod > New (const dictionary &dict, const fvMesh &mesh, const labelHashSet &patchIDs, const word &defaultPatchDistMethod=word::null)
template<class Type >
static wordList patchTypes (const fvMesh &mesh, const labelHashSet &patchIDs)
Detailed Description
Variant of patchDistMethods::meshWave that stores nearest-wall addressing instead of directly transporting wall information.
Example of the wallDist specification in fvSchemes:
    wallDist
    {
        method meshWaveAddressing;
        // Optional entry enabling the calculation
        // of the normal-to-wall field
        nRequired true;
    }
See also
Foam::patchDistMethod::meshWave Foam::wallDist
Source files
meshWaveAddressingPatchDistMethod.H
meshWaveAddressingPatchDistMethod.C
Definition at line 65 of file meshWaveAddressingPatchDistMethod.H.
Constructor & Destructor Documentation
meshWaveAddressing() [1/3]
meshWaveAddressing (const meshWaveAddressing &) protected delete
meshWaveAddressing() [2/3]
meshWaveAddressing (const dictionary & dict, const fvMesh & mesh, const labelHashSet & patchIDs)
Definition at line 41 of file meshWaveAddressingPatchDistMethod.C.
meshWaveAddressing() [3/3]
meshWaveAddressing (const fvMesh & mesh, const labelHashSet & patchIDs, const bool correctWalls = true)
Definition at line 53 of file meshWaveAddressingPatchDistMethod.C.
Member Function Documentation
operator=()
void operator= (const meshWaveAddressing &) protected delete
TypeName()
TypeName ("meshWaveAddressing")
correct() [1/2]
bool correct (volScalarField & y) virtual
Implements patchDistMethod.
Definition at line 67 of file meshWaveAddressingPatchDistMethod.C.
References correct(), GeometricField< vector, fvPatchField, volMesh >::null(), and y.
correct() [2/2]
bool correct (volScalarField & y, volVectorField & n) virtual
Implements patchDistMethod.
Definition at line 73 of file meshWaveAddressingPatchDistMethod.C.
References n, MeshObject< fvMesh, UpdateableMeshObject, wallDistAddressing >::New(), UPstream::nonBlocking, Foam::notNull(), UPstream::nRequests(), UPstream::waitRequests(), and y.
Member Data Documentation
correctWalls_
const bool correctWalls_ protected
Definition at line 74 of file meshWaveAddressingPatchDistMethod.H.
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/wallDist/patchDistMethods/meshWaveAddressing/meshWaveAddressingPatchDistMethod.H
src/finiteVolume/fvMesh/wallDist/patchDistMethods/meshWaveAddressing/meshWaveAddressingPatchDistMethod.C