OpenFOAM: LESModel< BasicTurbulenceModel > Class Template Reference
LESModel< BasicTurbulenceModel > Class Template Reference
Templated abstract base class for LES SGS models.
#include <LESModel.H>
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("LES")
declareRunTimeSelectionTable (autoPtr, LESModel, dictionary,(const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName),(alpha, rho, U, alphaRhoPhi, phi, transport, propertiesName))
LESModel (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~LESModel ()=default
virtual bool read ()
virtual const dictionary & coeffDict () const
const dimensionedScalar & Ce () const noexcept
const dimensionedScalar & kMin () const
dimensionedScalar & kMin ()
const volScalarField & delta () const
virtual tmp< volScalarField > nuEff () const
virtual tmp< scalarField > nuEff (const label patchi) const
virtual tmp< volScalarField > epsilon () const
virtual tmp< volScalarField > omega () const
virtual void correct ()
Static Public Member Functions
static autoPtr< LESModel > New (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Protected Member Functions
virtual void printCoeffs (const word &type)
LESModel (const LESModel &)=delete
void operator= (const LESModel &)=delete
Protected Attributes
dictionary LESDict_
Switch turbulence_
Switch printCoeffs_
dictionary coeffDict_
dimensionedScalar Ce_
dimensionedScalar kMin_
dimensionedScalar epsilonMin_
dimensionedScalar omegaMin_
autoPtr< Foam::LESdelta > delta_
Detailed Description
template<class BasicTurbulenceModel>
class Foam::LESModel< BasicTurbulenceModel >
Templated abstract base class for LES SGS models.
Source files
LESModel.H
LESModel.C
Definition at line 56 of file LESModel.H.
Member Typedef Documentation
alphaField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 106 of file LESModel.H.
rhoField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 107 of file LESModel.H.
transportModel
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 108 of file LESModel.H.
Constructor & Destructor Documentation
LESModel() [1/2]
template<class BasicTurbulenceModel > LESModel (const LESModel< BasicTurbulenceModel > &) protected delete
LESModel() [2/2]
template<class BasicTurbulenceModel > LESModel (const word & type, const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName)
Definition at line 39 of file LESModel.C.
~LESModel()
template<class BasicTurbulenceModel > virtual ~LESModel () virtual default
Member Function Documentation
printCoeffs()
template<class BasicTurbulenceModel > void printCoeffs (const word & type) protected virtual
Definition at line 27 of file LESModel.C.
References Foam::endl(), and Foam::Info.
Referenced by DeardorffDiffStress< BasicTurbulenceModel >::DeardorffDiffStress().
operator=()
template<class BasicTurbulenceModel > void operator= (const LESModel< BasicTurbulenceModel > &) protected delete
TypeName()
template<class BasicTurbulenceModel > TypeName ("LES")
declareRunTimeSelectionTable()
template<class BasicTurbulenceModel > declareRunTimeSelectionTable (autoPtr , LESModel< BasicTurbulenceModel > , dictionary , (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName) , (alpha, rho, U, alphaRhoPhi, phi, transport, propertiesName))
New()
template<class BasicTurbulenceModel > Foam::autoPtr< Foam::LESModel< BasicTurbulenceModel > > New (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName) static
Definition at line 125 of file LESModel.C.
References dict, dictionary::getCompat(), IOobject::group(), IOobject::groupName(), IOobjectOption::MUST_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, dictionary::subDict(), and U.
read()
template<class BasicTurbulenceModel > bool read () virtual
Reimplemented in DeardorffDiffStress< BasicTurbulenceModel >, linearViscousStress< LESModel< BasicTurbulenceModel > >, and ReynoldsStress< LESModel< BasicTurbulenceModel > >.
Definition at line 182 of file LESModel.C.
References Foam::type().
coeffDict()
template<class BasicTurbulenceModel > virtual const dictionary & coeffDict () const inline virtual
Definition at line 179 of file LESModel.H.
References LESModel< BasicTurbulenceModel >::coeffDict_.
Ce()
template<class BasicTurbulenceModel > const dimensionedScalar & Ce () const inline noexcept
Definition at line 185 of file LESModel.H.
References LESModel< BasicTurbulenceModel >::Ce_.
kMin() [1/2]
template<class BasicTurbulenceModel > const dimensionedScalar & kMin () const inline
Definition at line 191 of file LESModel.H.
References LESModel< BasicTurbulenceModel >::kMin_.
kMin() [2/2]
template<class BasicTurbulenceModel > dimensionedScalar & kMin () inline
Definition at line 197 of file LESModel.H.
References LESModel< BasicTurbulenceModel >::kMin_.
delta()
template<class BasicTurbulenceModel > const volScalarField & delta () const inline
Definition at line 203 of file LESModel.H.
References LESModel< BasicTurbulenceModel >::delta_.
nuEff() [1/2]
template<class BasicTurbulenceModel > virtual tmp< volScalarField > nuEff () const inline virtual
Definition at line 210 of file LESModel.H.
References IOobject::groupName().
nuEff() [2/2]
template<class BasicTurbulenceModel > virtual tmp< scalarField > nuEff (const label patchi) const inline virtual
Definition at line 223 of file LESModel.H.
References nu, and nut.
epsilon()
template<class BasicTurbulenceModel > Foam::tmp< Foam::volScalarField > epsilon () const virtual
Definition at line 206 of file LESModel.C.
References delta, IOobject::groupName(), k, tmp< T >::New(), and Foam::pow().
omega()
template<class BasicTurbulenceModel > Foam::tmp< Foam::volScalarField > omega () const virtual
Definition at line 223 of file LESModel.C.
References Foam::dimLength, Foam::dimTime, IOobject::groupName(), tmp< T >::New(), and Foam::sqr().
correct()
template<class BasicTurbulenceModel > void correct () virtual
Reimplemented in DeardorffDiffStress< BasicTurbulenceModel >, linearViscousStress< LESModel< BasicTurbulenceModel > >, and ReynoldsStress< LESModel< BasicTurbulenceModel > >.
Definition at line 242 of file LESModel.C.
Member Data Documentation
LESDict_
template<class BasicTurbulenceModel > dictionary LESDict_ protected
Definition at line 65 of file LESModel.H.
turbulence_
template<class BasicTurbulenceModel > Switch turbulence_ protected
Definition at line 68 of file LESModel.H.
printCoeffs_
template<class BasicTurbulenceModel > Switch printCoeffs_ protected
Definition at line 71 of file LESModel.H.
coeffDict_
template<class BasicTurbulenceModel > dictionary coeffDict_ protected
Definition at line 74 of file LESModel.H.
Referenced by LESModel< BasicTurbulenceModel >::coeffDict().
Ce_
template<class BasicTurbulenceModel > dimensionedScalar Ce_ protected
Definition at line 77 of file LESModel.H.
Referenced by LESModel< BasicTurbulenceModel >::Ce().
kMin_
template<class BasicTurbulenceModel > dimensionedScalar kMin_ protected
Definition at line 80 of file LESModel.H.
Referenced by LESModel< BasicTurbulenceModel >::kMin(), and LESModel< BasicTurbulenceModel >::kMin().
epsilonMin_
template<class BasicTurbulenceModel > dimensionedScalar epsilonMin_ protected
Definition at line 83 of file LESModel.H.
omegaMin_
template<class BasicTurbulenceModel > dimensionedScalar omegaMin_ protected
Definition at line 86 of file LESModel.H.
delta_
template<class BasicTurbulenceModel > autoPtr<Foam::LESdelta> delta_ protected
Definition at line 89 of file LESModel.H.
Referenced by LESModel< BasicTurbulenceModel >::delta().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/LES/LESModel/LESModel.H
src/TurbulenceModels/turbulenceModels/LES/LESModel/LESModel.C