OpenFOAM: memorybuf::out Class Reference
memorybuf::out Class Reference
#include <memoryStreamBuffer.H>
Public Member Functions
out (char *s, std::streamsize n)
void resetp (char *s, std::streamsize n)
std::streamsize capacity () const
const UList< char > list () const
UList< char > list ()
void printBufInfo (Ostream &os) const
std::streamsize tellp () const
Protected Member Functions
out ()=default
virtual std::streamsize xsputn (const char *s, std::streamsize n)
Protected Member Functions inherited from memorybuf
virtual std::streampos seekoff (std::streamoff off, std::ios_base::seekdir way, std::ios_base::openmode which=std::ios_base::in|std::ios_base::out)
virtual std::streampos seekpos (std::streampos pos, std::ios_base::openmode which=std::ios_base::in|std::ios_base::out)
std::streamsize tellg () const
std::streamsize tellp () const
Detailed Description
Definition at line 237 of file memoryStreamBuffer.H.
Constructor & Destructor Documentation
out() [1/2]
out () protected default
out() [2/2]
out (char * s, std::streamsize n) inline
Definition at line 263 of file memoryStreamBuffer.H.
References n, memorybuf::out::resetp(), and s().
Member Function Documentation
xsputn()
virtual std::streamsize xsputn (const char * s, std::streamsize n) inline protected virtual
Definition at line 247 of file memoryStreamBuffer.H.
References n, and s().
resetp()
void resetp (char * s, std::streamsize n) inline
Definition at line 270 of file memoryStreamBuffer.H.
References n, and s().
Referenced by memorybuf::out::out().
capacity()
std::streamsize capacity () const inline
Definition at line 286 of file memoryStreamBuffer.H.
Referenced by UOListStreamAllocator::capacity().
list() [1/2]
const UList< char > list () const inline
Definition at line 292 of file memoryStreamBuffer.H.
Referenced by UOListStreamAllocator::list(), and UOListStreamAllocator::list().
list() [2/2]
UList< char > list () inline
Definition at line 298 of file memoryStreamBuffer.H.
printBufInfo()
void printBufInfo (Ostream & os) const inline
Definition at line 304 of file memoryStreamBuffer.H.
References os().
Referenced by UOListStreamAllocator::printBufInfo().
tellp()
std::streamsize tellp () const inline
Definition at line 133 of file memoryStreamBuffer.H.
Referenced by UOListStreamAllocator::size().
The documentation for this class was generated from the following file:
src/OpenFOAM/db/IOstreams/memory/memoryStreamBuffer.H