OpenFOAM: BiIndirectList< T > Class Template Reference
BiIndirectList< T > Class Template Reference
Indexes into negList (negative index) or posList (zero or positive index).
#include <BiIndirectList.H>
Public Member Functions
BiIndirectList (const UList< T > &posList, const UList< T > &negList, const labelUList &addr)
BiIndirectList (const UList< T > &posList, const UList< T > &negList, labelList &&addr)
bool empty () const noexcept
label size () const noexcept
const UList< T > & posList () const noexcept
const UList< T > & negList () const noexcept
const labelList & addressing () const noexcept
void resetAddressing (const labelUList &addr)
void resetAddressing (labelList &&addr)
List< T > list () const
List< T > operator() () const
T & operator[] (const label i)
const T & operator[] (const label i) const
void operator= (const UList< T > &ae)
void operator= (const T &val)
Static Public Member Functions
static label posIndex (const label i) noexcept
static label negIndex (const label i) noexcept
Detailed Description
template<class T>
class Foam::BiIndirectList< T >
Indexes into negList (negative index) or posList (zero or positive index).
Source files
BiIndirectList.H
BiIndirectListI.H
Definition at line 48 of file BiIndirectList.H.
Constructor & Destructor Documentation
BiIndirectList() [1/2]
template<class T > BiIndirectList (const UList< T > & posList, const UList< T > & negList, const labelUList & addr) inline
Definition at line 25 of file BiIndirectListI.H.
BiIndirectList() [2/2]
template<class T > BiIndirectList (const UList< T > & posList, const UList< T > & negList, labelList && addr) inline
Definition at line 39 of file BiIndirectListI.H.
Member Function Documentation
empty()
template<class T > bool empty () const inline noexcept
Definition at line 83 of file BiIndirectList.H.
References UList< T >::empty().
size()
template<class T > label size () const inline noexcept
Definition at line 86 of file BiIndirectList.H.
References UList< T >::size().
posList()
template<class T > const UList< T > & posList () const inline noexcept
Definition at line 89 of file BiIndirectList.H.
negList()
template<class T > const UList< T > & negList () const inline noexcept
Definition at line 92 of file BiIndirectList.H.
addressing()
template<class T > const labelList & addressing () const inline noexcept
Definition at line 95 of file BiIndirectList.H.
posIndex()
template<class T > static label posIndex (const label i) inline static noexcept
Definition at line 98 of file BiIndirectList.H.
negIndex()
template<class T > static label negIndex (const label i) inline static noexcept
Definition at line 99 of file BiIndirectList.H.
resetAddressing() [1/2]
template<class T > void resetAddressing (const labelUList & addr) inline
Definition at line 55 of file BiIndirectListI.H.
resetAddressing() [2/2]
template<class T > void resetAddressing (labelList && addr) inline
Definition at line 62 of file BiIndirectListI.H.
References PtrList< T >::transfer().
list()
template<class T > Foam::List< T > list () const inline
Definition at line 69 of file BiIndirectListI.H.
References forAll.
Referenced by BiIndirectList< T >::operator()().
operator()()
template<class T > List< T > operator() () const inline
Definition at line 117 of file BiIndirectList.H.
References BiIndirectList< T >::list().
operator[]() [1/2]
template<class T > T & operator[] (const label i) inline
Definition at line 85 of file BiIndirectListI.H.
operator[]() [2/2]
template<class T > const T & operator[] (const label i) const inline
Definition at line 94 of file BiIndirectListI.H.
operator=() [1/2]
template<class T > void operator= (const UList< T > & ae) inline
Definition at line 103 of file BiIndirectListI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, and UPtrList< T >::size().
operator=() [2/2]
template<class T > void operator= (const T & val) inline
Definition at line 122 of file BiIndirectListI.H.
References forAll.
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/IndirectLists/BiIndirectList/BiIndirectList.H
src/OpenFOAM/containers/IndirectLists/BiIndirectList/BiIndirectListI.H