OpenFOAM: noFilm Class Reference
noFilm Class Reference
Dummy surfaceFilmModel to allow solvers supporting film simulations to be run without a film region.
#include <noFilm.H>
Public Member Functions
TypeName ("none")
noFilm (const word &modelType, const fvMesh &mesh, const dimensionedVector &g, const word &regionType)
virtual ~noFilm ()
virtual scalar CourantNumber () const
virtual tmp< volScalarField::Internal > Srho () const
virtual tmp< volScalarField::Internal > Srho (const label i) const
virtual tmp< volScalarField::Internal > Sh () const
virtual void evolve ()
Public Member Functions inherited from surfaceFilmModel
TypeName ("surfaceFilmModel")
declareRunTimeSelectionTable (autoPtr, surfaceFilmModel, mesh,(const word &modelType, const fvMesh &mesh, const dimensionedVector &g, const word &regionType),(modelType, mesh, g, regionType))
surfaceFilmModel ()
virtual ~surfaceFilmModel ()
Additional Inherited Members
Static Public Member Functions inherited from surfaceFilmModel
static autoPtr< surfaceFilmModel > New (const fvMesh &mesh, const dimensionedVector &g, const word &regionType="surfaceFilm")
Static Public Attributes inherited from surfaceFilmModel
static const dimensionedScalar Tref
Detailed Description
Dummy surfaceFilmModel to allow solvers supporting film simulations to be run without a film region.
Source files
noFilm.H
noFilm.C
Definition at line 51 of file noFilm.H.
Constructor & Destructor Documentation
noFilm()
noFilm (const word & modelType, const fvMesh & mesh, const dimensionedVector & g, const word & regionType)
Definition at line 41 of file noFilm.C.
~noFilm()
~noFilm () virtual
Definition at line 56 of file noFilm.C.
Member Function Documentation
TypeName()
TypeName ("none")
CourantNumber()
Foam::scalar CourantNumber () const virtual
Implements surfaceFilmModel.
Definition at line 62 of file noFilm.C.
Srho() [1/2]
tmp< volScalarField::Internal > Srho () const virtual
Implements surfaceFilmModel.
Definition at line 68 of file noFilm.C.
References Foam::dimMass, Foam::dimTime, Foam::dimVolume, tmp< T >::New(), IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, and Foam::Zero.
Srho() [2/2]
tmp< volScalarField::Internal > Srho (const label i) const virtual
Implements surfaceFilmModel.
Definition at line 87 of file noFilm.C.
References Foam::dimMass, Foam::dimTime, Foam::dimVolume, Foam::name(), tmp< T >::New(), IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, and Foam::Zero.
Sh()
tmp< volScalarField::Internal > Sh () const virtual
Implements surfaceFilmModel.
Definition at line 106 of file noFilm.C.
References Foam::dimEnergy, Foam::dimTime, Foam::dimVolume, tmp< T >::New(), IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, and Foam::Zero.
evolve()
void evolve () virtual
Implements surfaceFilmModel.
Definition at line 125 of file noFilm.C.
The documentation for this class was generated from the following files:
src/regionModels/surfaceFilmModels/noFilm/noFilm.H
src/regionModels/surfaceFilmModels/noFilm/noFilm.C