OpenFOAM: IOField< Type > Class Template Reference
IOField< Type > Class Template Reference
A primitive field of type <T> with automated input and output.
#include <IOField.H>
Public Types
typedef Field< Type > content_type
Public Types inherited from IOobject
enum objectState : char { GOOD , BAD }
enum fileCheckTypes : char { timeStamp , timeStampMaster , inotify , inotifyMaster }
Public Types inherited from IOobjectOption
enum readOption : unsigned char {
NO_READ = 0 , MUST_READ = 0x1 , READ_MODIFIED = 0x3 , MUST_READ_IF_MODIFIED = 0x3 ,
LAZY_READ = 0x4 , READ_IF_PRESENT = 0x4
}
enum writeOption : unsigned char { NO_WRITE = 0 , AUTO_WRITE = 0x10 }
enum registerOption : unsigned char { NO_REGISTER = 0 , REGISTER = 1 }
Public Types inherited from Field< Type >
typedef pTraits< Type >::cmptType cmptType
typedef SubField< Type > subField
Public Types inherited from List< Type >
typedef SubList< Type > subList
Public Types inherited from UList< T >
typedef T value_type
typedef T * pointer
typedef const T * const_pointer
typedef T & reference
typedef const T & const_reference
typedef T * iterator
typedef const T * const_iterator
typedef label size_type
typedef label difference_type
typedef std::reverse_iterator< iterator > reverse_iterator
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
Public Member Functions
TypeName ("Field")
IOField (const IOField &)=default
IOField (const IOobject &io)
IOField (const IOobject &io, const bool readOnProc)
IOField (const IOobject &io, Foam::zero)
IOField (const IOobject &io, const label len)
IOField (const IOobject &io, const UList< Type > &content)
IOField (const IOobject &io, Field< Type > &&content)
IOField (const IOobject &io, const tmp< Field< Type > > &tfld)
virtual ~IOField ()=default
virtual bool writeData (Ostream &os) const
void operator= (const IOField< Type > &rhs)
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
regIOobject (const IOobject &io, const bool isTimeObject=false)
regIOobject (const regIOobject &rio)
regIOobject (const regIOobject &rio, bool registerCopy)
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
regIOobject (const IOobject &io, const regIOobject &rio)
virtual ~regIOobject ()
bool checkIn ()
bool checkOut ()
virtual void addWatch ()
bool registered () const noexcept
bool ownedByRegistry () const noexcept
bool store ()
void release (const bool unregister=false) noexcept
label eventNo () const noexcept
label & eventNo () noexcept
bool upToDate (const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
void setUpToDate ()
virtual void rename (const word &newName)
const dictionary * findMetaData () const noexcept
dictionary & getMetaData () noexcept
void removeMetaData ()
virtual void updateMetaData ()
virtual fileName filePath () const
bool headerOk ()
Istream & readStream (const word &, const bool readOnProc=true)
void close ()
virtual bool readData (Istream &)
virtual bool read ()
virtual label addWatch (const fileName &)
const labelList & watchIndices () const noexcept
labelList & watchIndices () noexcept
virtual bool modified () const
virtual bool readIfModified ()
virtual bool writeObject (IOstreamOption streamOpt, const bool writeOnProc) const
virtual bool write (const bool writeOnProc=true) const
virtual bool global () const
void operator= (const IOobject &io)
virtual bool writeObject (IOstreamOption::streamFormat fmt, IOstreamOption::versionNumber ver, IOstreamOption::compressionType cmp, const bool writeOnProc) const
Public Member Functions inherited from IOobject
TypeName ("IOobject")
IOobject (const IOobject &)=default
virtual ~IOobject ()=default
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const fileName &path, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const fileName &path, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const IOobject &io, const objectRegistry &registry)
IOobject (const IOobject &io, const word &name)
IOobject (const IOobject &io, const word &name, const fileName &local)
IOobject (const IOobject &io, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt)
IOobject (const IOobject &io, IOobjectOption::registerOption regOpt)
autoPtr< IOobject > clone () const
autoPtr< IOobject > clone (const objectRegistry &registry) const
const objectRegistry & db () const noexcept
const Time & time () const noexcept
const word & name () const noexcept
const word & headerClassName () const noexcept
word & headerClassName () noexcept
const string & note () const noexcept
string & note () noexcept
unsigned labelByteSize () const noexcept
unsigned scalarByteSize () const noexcept
void resetHeader (const word &newName=word::null)
bool hasHeaderClass () const noexcept
template<class Type >
bool isHeaderClass () const
template<class Type >
bool isHeaderClassName () const
word group () const
word member () const
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const noexcept
fileName & instance () noexcept
const fileName & local () const noexcept
fileName path () const
fileName path (const word &instance, const fileName &local=fileName::null) const
fileName objectPath () const
fileName objectRelPath () const
fileName localFilePath (const word &typeName, const bool search=true) const
fileName globalFilePath (const word &typeName, const bool search=true) const
IOstreamOption parseHeader (const dictionary &headerDict)
bool readHeader (Istream &is)
bool readHeader (dictionary &headerDict, Istream &is)
template<class Type >
bool typeHeaderOk (const bool checkType=true, const bool search=true, const bool verbose=true)
template<class Type >
void warnNoRereading () const
bool writeHeader (Ostream &os) const
bool writeHeader (Ostream &os, const word &objectType) const
void writeHeader (dictionary &dict, IOstreamOption streamOpt) const
void writeHeader (dictionary &dict, const word &objectType, IOstreamOption streamOpt) const
bool good () const noexcept
bool bad () const noexcept
InfoProxy< IOobject > info () const noexcept
void operator= (const IOobject &io)
template<>
bool isHeaderClass () const
template<class StringType >
Foam::word groupName (StringType base, const word &group)
Public Member Functions inherited from IOobjectOption
constexpr IOobjectOption (readOption rOpt=readOption::NO_READ, writeOption wOpt=writeOption::NO_WRITE, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (readOption rOpt, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (writeOption wOpt, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (registerOption registerObject, bool globalObject=false) noexcept
constexpr IOobjectOption (readOption rOpt, writeOption wOpt, bool registerObject, bool globalObject=false) noexcept
constexpr IOobjectOption (bool registerObject, bool globalObject=false) noexcept
readOption readOpt () const noexcept
readOption readOpt (readOption opt) noexcept
writeOption writeOpt () const noexcept
writeOption writeOpt (writeOption opt) noexcept
bool registerObject () const noexcept
bool registerObject (bool on) noexcept
bool globalObject () const noexcept
bool globalObject (bool on) noexcept
bool isAnyRead () const noexcept
bool isReadRequired () const noexcept
bool isReadOptional () const noexcept
readOption & readOpt () noexcept
writeOption & writeOpt () noexcept
bool & registerObject () noexcept
bool & globalObject () noexcept
Public Member Functions inherited from Field< Type >
constexpr Field () noexcept
Field (const label len)
Field (const label len, const Type &val)
Field (const label len, const Foam::zero)
Field (const Foam::one, const Type &val)
Field (const Foam::one, Type &&val)
Field (const Foam::one, const Foam::zero)
Field (const Field< Type > &fld)
Field (const UList< Type > &list)
template<class Addr >
Field (const IndirectListBase< Type, Addr > &list)
Field (Field< Type > &&fld)
Field (List< Type > &&list)
template<int SizeMin>
Field (DynamicList< Type, SizeMin > &&list)
Field (const UList< Type > &mapF, const labelUList &mapAddressing)
Field (const tmp< Field< Type > > &tmapF, const labelUList &mapAddressing)
Field (const UList< Type > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Field (const tmp< Field< Type > > &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Field (const UList< Type > &mapF, const FieldMapper &map, const bool applyFlip=true)
Field (const UList< Type > &mapF, const FieldMapper &map, const Type &defaultValue, const bool applyFlip=true)
Field (const UList< Type > &mapF, const FieldMapper &map, const UList< Type > &defaultValues, const bool applyFlip=true)
Field (const tmp< Field< Type > > &tmapF, const FieldMapper &map, const bool applyFlip=true)
Field (const tmp< Field< Type > > &tmapF, const FieldMapper &map, const Type &defaultValue, const bool applyFlip=true)
Field (const tmp< Field< Type > > &tmapF, const FieldMapper &map, const UList< Type > &defaultValues, const bool applyFlip=true)
Field (Field< Type > &fld, bool reuse)
Field (const tmp< Field< Type > > &tfld)
Field (Istream &is)
Field (const entry &e, const label len)
Field (const word &key, const dictionary &dict, const label len, IOobjectOption::readOption readOpt=IOobjectOption::MUST_READ)
tmp< Field< Type > > clone () const
void assign (const entry &e, const label len)
bool assign (const word &key, const dictionary &dict, const label len, IOobjectOption::readOption readOpt=IOobjectOption::MUST_READ)
void map (const UList< Type > &mapF, const labelUList &mapAddressing)
void map (const tmp< Field< Type > > &tmapF, const labelUList &mapAddressing)
void map (const UList< Type > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
void map (const tmp< Field< Type > > &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
void map (const UList< Type > &mapF, const FieldMapper &map, const bool applyFlip=true)
void map (const tmp< Field< Type > > &tmapF, const FieldMapper &map, const bool applyFlip=true)
void autoMap (const FieldMapper &map, const bool applyFlip=true)
void rmap (const UList< Type > &mapF, const labelUList &mapAddressing)
void rmap (const tmp< Field< Type > > &tmapF, const labelUList &mapAddressing)
void rmap (const UList< Type > &mapF, const labelUList &mapAddressing, const UList< scalar > &weights)
void rmap (const tmp< Field< Type > > &tmapF, const labelUList &mapAddressing, const UList< scalar > &weights)
void negate ()
void normalise ()
tmp< Field< cmptType > > component (const direction) const
void replace (const direction, const UList< cmptType > &)
void replace (const direction, const tmp< Field< cmptType > > &)
void replace (const direction, const cmptType &)
void clamp_min (const Type &lower)
void clamp_max (const Type &upper)
void clamp_range (const Type &lower, const Type &upper)
void clamp_range (const MinMax< Type > &range)
template<class VSForm >
VSForm block (const label start) const
tmp< Field< Type > > T () const
void writeEntry (const word &keyword, Ostream &os) const
SubField< Type > slice (const label pos, label len=-1)
const SubField< Type > slice (const label pos, label len=-1) const
SubField< Type > slice (const labelRange &range)
const SubField< Type > slice (const labelRange &range) const
void operator= (const Field< Type > &)
void operator= (const tmp< Field< Type > > &)
void operator= (const UList< Type > &rhs)
void operator= (const SubField< Type > &rhs)
template<class Addr >
void operator= (const IndirectListBase< Type, Addr > &rhs)
void operator= (Field< Type > &&rhs)
void operator= (List< Type > &&rhs)
template<int SizeMin>
void operator= (DynamicList< Type, SizeMin > &&rhs)
void operator= (const Type &val)
void operator= (const Foam::zero)
template<class Form , class Cmpt , direction nCmpt>
void operator= (const VectorSpace< Form, Cmpt, nCmpt > &)
void operator+= (const UList< Type > &)
void operator+= (const tmp< Field< Type > > &)
void operator-= (const UList< Type > &)
void operator-= (const tmp< Field< Type > > &)
void operator*= (const UList< scalar > &)
void operator*= (const tmp< Field< scalar > > &)
void operator/= (const UList< scalar > &)
void operator/= (const tmp< Field< scalar > > &)
void operator+= (const Type &)
void operator-= (const Type &)
void operator*= (const scalar &)
void operator/= (const scalar &)
template<class Type >
void operator= (const tmp< Field > &rhs)
void normalise ()
void normalise ()
void normalise ()
void normalise ()
Public Member Functions inherited from FieldBase
constexpr FieldBase () noexcept
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Public Member Functions inherited from List< Type >
constexpr List () noexcept
List (const label len)
List (const label len, const Type &val)
List (const label len, const Foam::zero)
List (const Foam::one, const Type &val)
List (const Foam::one, Type &&val)
List (const Foam::one, const Foam::zero)
List (const List< Type > &a)
List (const UList< Type > &a)
List (List< Type > &a, bool reuse)
List (const UList< Type > &list, const labelUList &indices)
List (const UList< Type > &list, const FixedList< label, N > &indices)
List (const FixedList< Type, N > &list)
List (const PtrList< Type > &list)
List (const SLList< Type > &list)
List (const IndirectListBase< Type, Addr > &list)
List (std::initializer_list< Type > list)
List (List< Type > &&list)
List (DynamicList< Type, SizeMin > &&list)
List (SLList< Type > &&list)
List (Istream &is)
autoPtr< List< Type > > clone () const
~List ()
void clear ()
void resize (const label len)
void resize (const label len, const Type &val)
void resize (const label newLen)
void resize_nocopy (const label len)
void setSize (const label n)
void setSize (const label n, const Type &val)
void transfer (List< Type > &list)
void transfer (DynamicList< Type, SizeMin > &list)
Type & newElmt (const label i)
Type & emplace_back (Args &&... args)
void push_back (const Type &val)
void push_back (Type &&val)
void push_back (const UList< Type > &list)
void push_back (const IndirectListBase< Type, Addr > &list)
label push_uniq (const Type &val)
void pop_back (label n=1)
void operator= (const UList< Type > &a)
void operator= (const List< Type > &list)
void operator= (const SLList< Type > &list)
void operator= (const IndirectListBase< Type, Addr > &list)
void operator= (const FixedList< Type, N > &list)
void operator= (std::initializer_list< Type > list)
void operator= (const Type &val)
void operator= (const Foam::zero)
void operator= (List< Type > &&list)
void operator= (DynamicList< Type, SizeMin > &&list)
void operator= (SLList< Type > &&list)
Istream & readList (Istream &is)
Istream & readList (Istream &is)
Istream & readList (Istream &is)
void shallowCopy (const UList< Type > &)=delete
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type set (const label i, bool val=true)
void append (const Type &val)
void append (Type &&val)
void append (const UList< Type > &list)
void append (const IndirectListBase< Type, Addr > &list)
label appendUniq (const Type &val)
Public Member Functions inherited from UList< T >
UList (const UList< T > &)=default
constexpr UList () noexcept
UList (T *__restrict__ v, const label len) noexcept
label fcIndex (const label i) const noexcept
label rcIndex (const label i) const noexcept
const T & fcValue (const label i) const
T & fcValue (const label i)
const T & rcValue (const label i) const
T & rcValue (const label i)
const T * cdata () const noexcept
T * data () noexcept
const char * cdata_bytes () const noexcept
char * data_bytes () noexcept
T & front ()
const T & front () const
T & back ()
const T & back () const
std::streamsize size_bytes () const noexcept
std::streamsize byteSize () const
void checkStart (const label start) const
void checkSize (const label size) const
void checkRange (const label start, const label len) const
void checkIndex (const label i) const
bool uniform () const
label find (const T &val, label pos=0) const
label rfind (const T &val, label pos=-1) const
bool contains (const T &val, label pos=0) const
void moveFirst (const label i)
void moveLast (const label i)
void swapFirst (const label i)
void swapLast (const label i)
void shallowCopy (const UList< T > &list)
void deepCopy (const UList< T > &list)
template<class Addr >
void deepCopy (const IndirectListBase< T, Addr > &list)
SubList< T > slice (const label pos, label len=-1)
const SubList< T > slice (const label pos, label len=-1) const
SubList< T > slice (const labelRange &range)
const SubList< T > slice (const labelRange &range) const
T & operator[] (const label i)
const T & operator[] (const label i) const
operator const Foam::List< T > & () const
void operator= (const T &val)
void operator= (const Foam::zero)
iterator begin () noexcept
iterator end () noexcept
iterator begin (const label i) noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
const_iterator begin () const noexcept
const_iterator end () const noexcept
const_iterator cbegin (const label i) const noexcept
const_iterator begin (const label i) const noexcept
reverse_iterator rbegin ()
reverse_iterator rend ()
const_reverse_iterator crbegin () const
const_reverse_iterator crend () const
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
bool empty () const noexcept
label size () const noexcept
void swap (UList< T > &list)
bool operator== (const UList< T > &a) const
bool operator!= (const UList< T > &a) const
bool operator< (const UList< T > &list) const
bool operator> (const UList< T > &a) const
bool operator<= (const UList< T > &a) const
bool operator>= (const UList< T > &a) const
Istream & readList (Istream &is)
void writeEntry (const word &keyword, Ostream &os) const
Ostream & writeList (Ostream &os, const label shortLen=0) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type test (const label i) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type get (const label i) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type unset (const label i)
T & first ()
const T & first () const
T & last ()
const T & last () const
bool found (const T &val, label pos=0) const
Istream & readList (Istream &is)
Ostream & writeList (Ostream &os, const label) const
const bool & operator[] (const label i) const
UPstream::commsStruct & operator[] (const label procID)
const UPstream::commsStruct & operator[] (const label procID) const
Foam::UPstream::commsStruct & operator[] (const label procID)
const Foam::UPstream::commsStruct & operator[] (const label procID) const
Ostream & writeList (Ostream &os, const label) const
Istream & readList (Istream &is)
Static Public Member Functions
static Field< Type > readContents (const IOobject &io)
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *p)
template<class Type >
static Type & store (autoPtr< Type > &ptr)
template<class Type >
static Type & store (autoPtr< Type > &&ptr)
template<class Type >
static Type & store (refPtr< Type > &ptr)
template<class Type >
static Type & store (refPtr< Type > &&ptr)
template<class Type >
static Type & store (tmp< Type > &ptr)
template<class Type >
static Type & store (tmp< Type > &&ptr)
Static Public Member Functions inherited from IOobject
static bool bannerEnabled () noexcept
static bool bannerEnabled (bool on) noexcept
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
template<class StringType >
static word groupName (StringType base, const word &group)
static word group (const word &name)
static word member (const word &name)
static word scopedName (const std::string &scope, const word &name)
static IOobject selectIO (const IOobject &io, const fileName &altFile, const word &ioName="")
static Ostream & writeBanner (Ostream &os, const bool noSyntaxHint=false)
static Ostream & writeDivider (Ostream &os)
static Ostream & writeEndDivider (Ostream &os)
Static Public Member Functions inherited from IOobjectOption
static bool isAnyRead (readOption opt) noexcept
static bool isReadRequired (readOption opt) noexcept
static bool isReadOptional (readOption opt) noexcept
static readOption lazierRead (readOption opt) noexcept
Static Public Member Functions inherited from Field< Type >
static const Field< Type > & null ()
static autoPtr< Field< Type > > New (Istream &is)
template<class Type2 >
static tmp< Field< Type > > NewCalculatedType (const Field< Type2 > &f)
Static Public Member Functions inherited from List< Type >
static const List< Type > & null ()
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
static constexpr label max_size () noexcept
Additional Inherited Members
Static Public Attributes inherited from IOobject
static const Enum< fileCheckTypes > fileCheckTypesNames
static char scopeSeparator
static fileCheckTypes fileModificationChecking
static float fileModificationSkew
static int maxFileModificationPolls
Static Public Attributes inherited from FieldBase
static const char *const typeName
static bool allowConstructFromLargerSize = false
Protected Member Functions inherited from regIOobject
bool readHeaderOk (const IOstreamOption::streamFormat fmt, const word &typeName)
Protected Member Functions inherited from IOobject
void setBad (const string &s)
Protected Member Functions inherited from UList< T >
void setAddressableSize (const label n) noexcept
void size (const label n)
void writeEntry (Ostream &os) const
labelRange validateRange (const labelRange &requestedRange) const
UList< T > & operator= (const UList< T > &)=delete
void writeEntry (Ostream &os) const
void writeEntry (Ostream &os) const
Static Protected Member Functions inherited from IOobject
static void writeHeaderContent (Ostream &os, const IOobject &io, const word &objectType, const dictionary *metaDataDict=nullptr)
static void writeHeaderContent (dictionary &dict, const IOobject &io, const word &objectType, IOstreamOption streamOpt, const dictionary *metaDataDict=nullptr)
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
Detailed Description
template<class Type>
class Foam::IOField< Type >
A primitive field of type <T> with automated input and output.
Source files
IOField.H
IOField.C
Definition at line 49 of file IOField.H.
Member Typedef Documentation
content_type
template<class Type > typedef Field<Type> content_type
Definition at line 65 of file IOField.H.
Constructor & Destructor Documentation
IOField() [1/8]
template<class Type > IOField (const IOField< Type > &) default
IOField() [2/8]
template<class Type > IOField (const IOobject & io) explicit
Definition at line 55 of file IOField.C.
IOField() [3/8]
template<class Type > IOField (const IOobject & io, const bool readOnProc)
Definition at line 67 of file IOField.C.
References IOobjectOption::isReadRequired().
IOField() [4/8]
template<class Type > IOField (const IOobject & io, Foam::zero)
Definition at line 87 of file IOField.C.
IOField() [5/8]
template<class Type > IOField (const IOobject & io, const label len)
Definition at line 99 of file IOField.C.
IOField() [6/8]
template<class Type > IOField (const IOobject & io, const UList< Type > & content)
Definition at line 114 of file IOField.C.
IOField() [7/8]
template<class Type > IOField (const IOobject & io, Field< Type > && content)
Definition at line 129 of file IOField.C.
References List< Type >::transfer().
IOField() [8/8]
template<class Type > IOField (const IOobject & io, const tmp< Field< Type > > & tfld)
Definition at line 143 of file IOField.C.
References PtrList< T >::clear(), Field< Type >::operator=(), and List< Type >::transfer().
~IOField()
template<class Type > virtual ~IOField () virtual default
Member Function Documentation
TypeName()
template<class Type > TypeName ("Field")
readContents()
template<class Type > Foam::Field< Type > readContents (const IOobject & io) static
Definition at line 178 of file IOField.C.
References io(), IOobjectOption::MUST_READ, IOobjectOption::MUST_READ_IF_MODIFIED, and IOobjectOption::NO_REGISTER.
writeData()
template<class Type > bool writeData (Ostream & os) const virtual
Implements regIOobject.
Definition at line 195 of file IOField.C.
References IOstream::good(), and os().
operator=()
template<class Type > void operator= (const IOField< Type > & rhs)
Definition at line 213 of file IOField.C.
References Field< Type >::operator=().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/conversion/vtk/foamVtkLagrangianWriter.H
src/OpenFOAM/db/IOobjects/IOField/IOField.H
src/OpenFOAM/db/IOobjects/IOField/IOField.C