OpenFOAM: IOstream Class Reference
IOstream Class Reference abstract
An IOstream is an abstract base class for all input/output systems; be they streams, files, token lists etc.
#include <IOstream.H>
Public Types
enum streamAccess : char { CLOSED = 0 , OPENED }
Public Types inherited from IOstreamOption
enum streamFormat : char { ASCII = 0 , BINARY }
enum compressionType : char { UNCOMPRESSED = 0 , COMPRESSED }
enum appendType : char { NON_APPEND = 0 , APPEND }
enum atomicType : char { NON_ATOMIC = 0 , ATOMIC }
Public Member Functions
IOstream (const IOstream &)=default
virtual ~IOstream ()=default
IOstream (IOstreamOption streamOpt=IOstreamOption())
IOstream (IOstreamOption::streamFormat fmt, IOstreamOption::versionNumber ver, IOstreamOption::compressionType cmp=IOstreamOption::UNCOMPRESSED)
virtual const fileName & name () const
fileName relativeName () const
virtual bool check (const char *operation) const
bool fatalCheck (const char *operation) const
bool opened () const noexcept
bool closed () const noexcept
bool good () const noexcept
bool eof () const noexcept
bool fail () const noexcept
bool bad () const noexcept
operator bool () const noexcept
bool operator! () const noexcept
unsigned labelByteSize () const noexcept
unsigned scalarByteSize () const noexcept
void setLabelByteSize (unsigned nbytes) noexcept
void setScalarByteSize (unsigned nbytes) noexcept
template<class T = label>
std::enable_if< std::is_integral< T >::value, bool >::type checkLabelSize () const noexcept
template<class T = scalar>
std::enable_if< std::is_floating_point< T >::value, bool >::type checkScalarSize () const noexcept
label lineNumber () const noexcept
label & lineNumber () noexcept
label lineNumber (const label num) noexcept
virtual ios_base::fmtflags flags () const =0
void setEof () noexcept
void setFail () noexcept
void setBad ()
virtual ios_base::fmtflags flags (const ios_base::fmtflags f)=0
ios_base::fmtflags setf (const ios_base::fmtflags f)
ios_base::fmtflags setf (const ios_base::fmtflags f, const ios_base::fmtflags mask)
void unsetf (const ios_base::fmtflags f)
virtual void print (Ostream &os) const
void print (Ostream &os, const int streamState) const
InfoProxy< IOstream > info () const noexcept
Public Member Functions inherited from IOstreamOption
constexpr IOstreamOption (streamFormat fmt=streamFormat::ASCII, compressionType comp=compressionType::UNCOMPRESSED) noexcept
constexpr IOstreamOption (streamFormat fmt, compressionType comp, versionNumber ver) noexcept
constexpr IOstreamOption (streamFormat fmt, versionNumber ver, compressionType comp=compressionType::UNCOMPRESSED) noexcept
IOstreamOption (const IOstreamOption &opt, streamFormat fmt) noexcept
streamFormat format () const noexcept
streamFormat format (const streamFormat fmt) noexcept
streamFormat format (const word &formatName)
compressionType compression () const noexcept
compressionType compression (const compressionType comp) noexcept
compressionType compression (const word &compName)
versionNumber version () const noexcept
versionNumber version (const versionNumber ver) noexcept
versionNumber version (const token &tok)
Static Public Member Functions
static unsigned int defaultPrecision () noexcept
static unsigned int defaultPrecision (unsigned int prec) noexcept
Static Public Member Functions inherited from IOstreamOption
static streamFormat formatEnum (const word &formatName, const streamFormat deflt=streamFormat::ASCII)
static streamFormat formatEnum (const word &key, const dictionary &dict, const streamFormat deflt=streamFormat::ASCII)
static compressionType compressionEnum (const word &compName, const compressionType deflt=compressionType::UNCOMPRESSED)
static compressionType compressionEnum (const word &key, const dictionary &dict, const compressionType deflt=compressionType::UNCOMPRESSED)
Static Public Attributes
static unsigned int precision_
Static Public Attributes inherited from IOstreamOption
static const Enum< streamFormat > formatNames
static const versionNumber currentVersion
Protected Member Functions
void setOpened () noexcept
void setClosed () noexcept
void setState (std::ios_base::iostate state) noexcept
void setGood () noexcept
Protected Attributes
std::ios_base::iostate ioState_
streamAccess openClosed_
unsigned char sizeofLabel_
unsigned char sizeofScalar_
label lineNumber_
Static Protected Attributes
static fileName staticName_
Detailed Description
An IOstream is an abstract base class for all input/output systems; be they streams, files, token lists etc.
The basic operations are construct, close, read token, read primitive and read binary block. In addition version control and line number counting is incorporated. Usually one would use the read primitive member functions, but if one were reading a stream on unknown data sequence one can read token by token, and then analyse.
Source files
IOstream.H
IOstream.C
Definition at line 82 of file IOstream.H.
Member Enumeration Documentation
streamAccess
enum streamAccess : char
Enumerator
CLOSED
The stream is not open.
OPENED
The stream is open.
Definition at line 91 of file IOstream.H.
Constructor & Destructor Documentation
IOstream() [1/3]
IOstream (const IOstream &) default
~IOstream()
virtual ~IOstream () virtual default
IOstream() [2/3]
IOstream (IOstreamOption streamOpt = IOstreamOption()) inline explicit
Definition at line 171 of file IOstream.H.
References IOstream::setBad().
IOstream() [3/3]
IOstream (IOstreamOption::streamFormat fmt, IOstreamOption::versionNumber ver, IOstreamOption::compressionType cmp = IOstreamOption::UNCOMPRESSED) inline
Definition at line 184 of file IOstream.H.
Member Function Documentation
setOpened()
void setOpened () inline protected noexcept
Definition at line 132 of file IOstream.H.
References IOstream::openClosed_, and IOstream::OPENED.
Referenced by IFstream::IFstream(), ISstream::ISstream(), ITstream::ITstream(), ITstream::ITstream(), ITstream::ITstream(), ITstream::ITstream(), ITstream::ITstream(), OFstream::OFstream(), OFstream::OFstream(), OSstream::OSstream(), OTstream::OTstream(), OTstream::OTstream(), OTstream::OTstream(), OTstream::rewind(), UIPstreamBase::UIPstreamBase(), and UOPstreamBase::UOPstreamBase().
setClosed()
void setClosed () inline protected noexcept
Definition at line 138 of file IOstream.H.
References IOstream::CLOSED, and IOstream::openClosed_.
Referenced by IFstream::IFstream(), and OFstream::OFstream().
setState()
void setState (std::ios_base::iostate state) inline protected noexcept
Definition at line 144 of file IOstream.H.
References IOstream::ioState_.
Referenced by IFstream::IFstream(), OFstream::OFstream(), OFstream::OFstream(), ISstream::syncState(), and OSstream::syncState().
setGood()
void setGood () inline protected noexcept
Definition at line 150 of file IOstream.H.
References IOstream::ioState_.
Referenced by ISstream::ISstream(), ITstream::ITstream(), ITstream::ITstream(), ITstream::ITstream(), ITstream::ITstream(), ITstream::ITstream(), OSstream::OSstream(), OTstream::OTstream(), OTstream::OTstream(), OTstream::OTstream(), IListStream::rewind(), OCountStream::rewind(), OListStream::rewind(), UIListStream::rewind(), UOListStream::rewind(), OTstream::rewind(), UIPstreamBase::UIPstreamBase(), and UOPstreamBase::UOPstreamBase().
name()
const Foam::fileName & name () const virtual
Reimplemented in primitiveEntry, IFstream, OFstream, ISstream, OSstream, and ITstream.
Definition at line 33 of file IOstream.C.
References IOstream::staticName_.
Referenced by interRegionHeatTransferModel::addSup(), globalIndexAndTransform::addToTransformIndex(), mappedPatchBase::calcMapping(), wallBoiling::correct(), distributedTriSurfaceMesh::distributedTriSurfaceMesh(), distributedTriSurfaceMesh::distributedTriSurfaceMesh(), readFields::execute(), wallHeatFlux::execute(), if(), injectionModelList::info(), transferModelList::info(), surfaceInterpolate::interpolateFields(), wallShearStress::read(), wallHeatFlux::read(), fvExprDriver::updateSpecialVariables(), wallShearStress::write(), internalWriter::write(), patchWriter::write(), and lagrangianWriter::write().
relativeName()
Foam::fileName relativeName () const
Definition at line 39 of file IOstream.C.
References argList::envRelativePath(), and Foam::name().
Referenced by primitiveEntry::relativeName().
check()
bool check (const char * operation) const virtual
Definition at line 45 of file IOstream.C.
Referenced by HashTable< T * >::HashTable(), GeometricField< Type, PatchField, GeoMesh >::operator/=(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::functionObjects::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::RBD::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::output(), fvPatchField< symmTensor >::updateCoeffs(), dictionaryListEntry::write(), SHA1Digest::write(), dimensionSet::write(), Foam::writeChars(), particle< Type >::writeCoordinates(), faBoundaryMesh::writeData(), polyBoundaryMesh::writeData(), DimensionedField< Type, GeoMesh >::writeData(), dimensioned< Type >::writeEntry(), GeometricBoundaryField< Type, PatchField, GeoMesh >::writeEntry(), HashTable< T, Key, Hash >::writeKeys(), CircularBuffer< T >::writeList(), LList< LListBase, T >::writeList(), injectedParticle::writePosition(), and particle< Type >::writePosition().
fatalCheck()
bool fatalCheck (const char * operation) const
Definition at line 51 of file IOstream.C.
References Foam::exit(), Foam::FatalIOError, and FatalIOErrorInFunction.
opened()
bool opened () const inline noexcept
Definition at line 220 of file IOstream.H.
References IOstream::openClosed_, and IOstream::OPENED.
Referenced by IFstream::IFstream(), and OFstream::OFstream().
closed()
bool closed () const inline noexcept
Definition at line 226 of file IOstream.H.
References IOstream::CLOSED, and IOstream::openClosed_.
good()
bool good () const inline noexcept
Definition at line 232 of file IOstream.H.
References IOstream::ioState_.
Referenced by dynamicCode::copyAndFilter(), dynamicCode::copyOrCreateFiles(), dynamicCode::createMakeFiles(), dynamicCode::createMakeOptions(), IFstream::IFstream(), OFstream::OFstream(), dynamicIndexedOctree< Type >::write(), indexedOctree< Type >::write(), decomposedBlockData::writeBlocks(), refinementHistory::writeData(), polyTopoChanger::writeData(), AveragingMethod< Type >::writeData(), extendedFeatureEdgeMesh::writeData(), featureEdgeMesh::writeData(), baseIOdictionary::writeData(), GeometricField< Type, PatchField, GeoMesh >::writeData(), faBoundaryMesh::writeData(), MRFZoneList::writeData(), porosityModelList::writeData(), IOPosition< CloudType >::writeData(), lumpedPointIOMovement::writeData(), decomposedBlockData::writeData(), IOField< Type >::writeData(), IOFieldRef< Type >::writeData(), IOList< T >::writeData(), IOListRef< T >::writeData(), IOMap< T >::writeData(), rawIOField< Type >::writeData(), profiling::writeData(), IOmapDistributePolyMesh::writeData(), IOmapDistributePolyMeshRef::writeData(), polyBoundaryMesh::writeData(), ZoneMesh< ZoneType, MeshType >::writeData(), coordinateSystems::writeData(), porousModel::writeData(), BlendedInterfacialModel< ModelType >::writeData(), dragModel::writeData(), virtualMassModel::writeData(), surfZoneIOList::writeData(), DimensionedField< Type, GeoMesh >::writeData(), dynamicCode::writeDigest(), dynamicCode::writeDigest(), dictionary::writeEntries(), IOobject::writeHeader(), Foam::writeJobDict(), and fileOperation::writeObject().
eof()
bool eof () const inline noexcept
Definition at line 238 of file IOstream.H.
References IOstream::ioState_.
fail()
bool fail () const inline noexcept
Definition at line 244 of file IOstream.H.
References IOstream::ioState_.
Referenced by IOstream::operator bool(), and IOstream::operator!().
bad()
bool bad () const inline noexcept
Definition at line 250 of file IOstream.H.
References IOstream::ioState_.
Referenced by error::write(), and IOerror::write().
operator bool()
operator bool () const inline explicit noexcept
Definition at line 256 of file IOstream.H.
References IOstream::fail().
operator!()
bool operator! () const inline noexcept
Definition at line 262 of file IOstream.H.
References IOstream::fail().
labelByteSize()
unsigned labelByteSize () const inline noexcept
Definition at line 271 of file IOstream.H.
References IOstream::sizeofLabel_.
scalarByteSize()
unsigned scalarByteSize () const inline noexcept
Definition at line 277 of file IOstream.H.
References IOstream::sizeofScalar_.
setLabelByteSize()
void setLabelByteSize (unsigned nbytes) inline noexcept
Definition at line 283 of file IOstream.H.
References IOstream::sizeofLabel_.
setScalarByteSize()
void setScalarByteSize (unsigned nbytes) inline noexcept
Definition at line 289 of file IOstream.H.
References IOstream::sizeofScalar_.
checkLabelSize()
template<class T = label> std::enable_if< std::is_integral< T >::value, bool >::type checkLabelSize () const inline noexcept
Definition at line 299 of file IOstream.H.
References IOstream::sizeofLabel_, and T.
checkScalarSize()
template<class T = scalar> std::enable_if< std::is_floating_point< T >::value, bool >::type checkScalarSize () const inline noexcept
Definition at line 308 of file IOstream.H.
References IOstream::sizeofScalar_, and T.
lineNumber() [1/3]
label lineNumber () const inline noexcept
Definition at line 317 of file IOstream.H.
References IOstream::lineNumber_.
lineNumber() [2/3]
label & lineNumber () inline noexcept
Definition at line 323 of file IOstream.H.
References IOstream::lineNumber_.
lineNumber() [3/3]
label lineNumber (const label num) inline noexcept
Definition at line 330 of file IOstream.H.
References IOstream::lineNumber_.
flags() [1/2]
virtual ios_base::fmtflags flags () const pure virtual
Implemented in dummyISstream, UIPstreamBase, UOPstreamBase, ISstream, OSstream, ITstream, and OTstream.
Referenced by IOstream::setf(), IOstream::setf(), and IOstream::unsetf().
defaultPrecision() [1/2]
static unsigned int defaultPrecision () inline static noexcept
Definition at line 341 of file IOstream.H.
References IOstream::precision_.
Referenced by VTPsurfaceFormatCore::formatOptions(), VTKsurfaceFormatCore::formatOptions(), objectiveManager::objectiveManager(), dataCloud::read(), vtkCloud::read(), vtkWrite::read(), writeFile::read(), Time::readDict(), AMIWeights::reportPatch(), faceSetOption::setArea(), cellSetOption::setVol(), SQP::write(), VTKedgeFormat::write(), sensitivityBezier::write(), sensitivityBezierFI::write(), sensitivityVolBSplines::write(), sensitivityVolBSplinesFI::write(), PDRblock::writeBlockMeshDict(), faMeshDecomposition::writeDecomposition(), and objectiveManager::writeObjectives().
defaultPrecision() [2/2]
static unsigned int defaultPrecision (unsigned int prec) inline static noexcept
Definition at line 348 of file IOstream.H.
References IOstream::precision_.
setEof()
void setEof () inline noexcept
Definition at line 356 of file IOstream.H.
References IOstream::ioState_.
setFail()
void setFail () inline noexcept
Definition at line 362 of file IOstream.H.
References IOstream::ioState_.
setBad()
void setBad () inline
Definition at line 368 of file IOstream.H.
References IOstream::ioState_.
Referenced by IFstream::IFstream(), IOstream::IOstream(), and OFstream::OFstream().
flags() [2/2]
virtual ios_base::fmtflags flags (const ios_base::fmtflags f) pure virtual
Implemented in ISstream, OSstream, dummyISstream, UIPstreamBase, UOPstreamBase, ITstream, and OTstream.
setf() [1/2]
ios_base::fmtflags setf (const ios_base::fmtflags f) inline
Definition at line 377 of file IOstream.H.
References f(), and IOstream::flags().
Referenced by Foam::setf().
setf() [2/2]
ios_base::fmtflags setf (const ios_base::fmtflags f, const ios_base::fmtflags mask) inline
Definition at line 383 of file IOstream.H.
References f(), and IOstream::flags().
unsetf()
void unsetf (const ios_base::fmtflags f) inline
Definition at line 393 of file IOstream.H.
References f(), and IOstream::flags().
print() [1/2]
void print (Ostream & os) const virtual
Reimplemented in IFstream, OFstream, IListStream, OCountStream, OListStream, UIListStream, UOListStream, UIPstreamBase, UOPstreamBase, ISstream, OSstream, prefixOSstream, IStringStream, OStringStream, ITstream, and OTstream.
Definition at line 67 of file IOstream.C.
References Foam::endl(), format(), and os().
Referenced by Foam::operator<<(), Foam::operator<<(), ISstream::print(), OSstream::print(), ITstream::print(), and OTstream::print().
print() [2/2]
void print (Ostream & os, const int streamState) const
Definition at line 106 of file IOstream.C.
References Foam::endl(), and os().
info()
InfoProxy< IOstream > info () const inline noexcept
Definition at line 412 of file IOstream.H.
Referenced by IFstream::IFstream(), MultiInteraction< CloudType >::info(), OFstream::OFstream(), Foam::operator<<(), and IOobject::writeHeader().
Member Data Documentation
precision_
unsigned int precision_ static
Definition at line 101 of file IOstream.H.
Referenced by IOstream::defaultPrecision(), IOstream::defaultPrecision(), functionObjectList::execute(), and OSstream::OSstream().
staticName_
Foam::fileName staticName_ static protected
Definition at line 109 of file IOstream.H.
Referenced by IOstream::name().
ioState_
std::ios_base::iostate ioState_ protected
Definition at line 112 of file IOstream.H.
Referenced by IOstream::bad(), IOstream::eof(), IOstream::fail(), IOstream::good(), IOstream::setBad(), IOstream::setEof(), IOstream::setFail(), IOstream::setGood(), and IOstream::setState().
openClosed_
streamAccess openClosed_ protected
Definition at line 115 of file IOstream.H.
Referenced by IOstream::closed(), IOstream::opened(), IOstream::setClosed(), and IOstream::setOpened().
sizeofLabel_
unsigned char sizeofLabel_ protected
Definition at line 118 of file IOstream.H.
Referenced by IOstream::checkLabelSize(), IOstream::labelByteSize(), and IOstream::setLabelByteSize().
sizeofScalar_
unsigned char sizeofScalar_ protected
Definition at line 121 of file IOstream.H.
Referenced by IOstream::checkScalarSize(), IOstream::scalarByteSize(), and IOstream::setScalarByteSize().
lineNumber_
label lineNumber_ protected
Definition at line 124 of file IOstream.H.
Referenced by IFstream::IFstream(), IOstream::lineNumber(), IOstream::lineNumber(), IOstream::lineNumber(), OFstream::OFstream(), and OFstream::OFstream().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOstreams/IOstreams/IOstream.H
src/OpenFOAM/db/IOstreams/IOstreams.C
src/OpenFOAM/db/IOstreams/IOstreams/IOstream.C