OpenFOAM: X3DsurfaceFormatCore Class Reference
X3DsurfaceFormatCore Class Reference
Internal class used by the X3DsurfaceFormat.
#include <X3DsurfaceFormatCore.H>
Static Protected Member Functions
static void writeHeader (Ostream &os)
static void writeFooter (Ostream &os)
static void beginGroup (Ostream &os)
static void endGroup (Ostream &os)
static void writeAppearance (Ostream &os)
static void writePoints (Ostream &os, const UList< point > &pts)
Detailed Description
Internal class used by the X3DsurfaceFormat.
Source files
X3DsurfaceFormatCore.H
X3DsurfaceFormatCore.C
Definition at line 48 of file X3DsurfaceFormatCore.H.
Member Function Documentation
writeHeader()
void writeHeader (Ostream & os) static protected
Definition at line 27 of file X3DsurfaceFormatCore.C.
References os().
writeFooter()
void writeFooter (Ostream & os) static protected
Definition at line 46 of file X3DsurfaceFormatCore.C.
References os().
beginGroup()
void beginGroup (Ostream & os) static protected
Definition at line 56 of file X3DsurfaceFormatCore.C.
References os().
endGroup()
void endGroup (Ostream & os) static protected
Definition at line 67 of file X3DsurfaceFormatCore.C.
References os().
writeAppearance()
void writeAppearance (Ostream & os) static protected
Definition at line 78 of file X3DsurfaceFormatCore.C.
References os().
writePoints()
void writePoints (Ostream & os, const UList< point > & pts) static protected
Definition at line 97 of file X3DsurfaceFormatCore.C.
References Foam::nl, os(), p, and pts.
The documentation for this class was generated from the following files:
src/surfMesh/surfaceFormats/x3d/X3DsurfaceFormatCore.H
src/surfMesh/surfaceFormats/x3d/X3DsurfaceFormatCore.C