OpenFOAM: Frossling Class Reference
Frossling Class Reference
Frossling correlation for turbulent mass transfer from the surface of a sphere to the surrounding fluid.
#include <Frossling.H>
Public Member Functions
TypeName ("Frossling")
Frossling (const dictionary &dict, const phasePair &pair)
virtual ~Frossling ()
virtual tmp< volScalarField > K () const
Public Member Functions inherited from massTransferModel
TypeName ("massTransferModel")
declareRunTimeSelectionTable (autoPtr, massTransferModel, dictionary,(const dictionary &dict, const phasePair &pair),(dict, pair))
massTransferModel (const dictionary &dict, const phasePair &pair)
virtual ~massTransferModel ()=default
Additional Inherited Members
Static Public Member Functions inherited from massTransferModel
static autoPtr< massTransferModel > New (const dictionary &dict, const phasePair &pair)
Static Public Attributes inherited from massTransferModel
static const dimensionSet dimK
Protected Attributes inherited from massTransferModel
const phasePair & pair_
Detailed Description
Frossling correlation for turbulent mass transfer from the surface of a sphere to the surrounding fluid.
Source files
Frossling.H
Frossling.C
Definition at line 52 of file Frossling.H.
Constructor & Destructor Documentation
Frossling()
Frossling (const dictionary & dict, const phasePair & pair)
Definition at line 39 of file Frossling.C.
References Foam::dimless.
~Frossling()
~Frossling () virtual
Definition at line 52 of file Frossling.C.
Member Function Documentation
TypeName()
TypeName ("Frossling")
K()
Foam::tmp< Foam::volScalarField > K () const virtual
Implements massTransferModel.
Definition at line 59 of file Frossling.C.
References Foam::cbrt(), Foam::sqr(), and Foam::sqrt().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/interfacialCompositionModels/massTransferModels/Frossling/Frossling.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/interfacialCompositionModels/massTransferModels/Frossling/Frossling.C