OpenFOAM: box Class Reference
box Class Reference abstract
Creates the parallel distribution map by describing the source and target objects using box shapes.
#include <box.H>
Public Member Functions
TypeName ("box")
box (const UList< point > &srcPoints, const UList< point > &tgtPoints, const label maxObjectsPerLeaf, const label nObjectsOfType, const label nRefineIterMax=100)
virtual ~box ()=default
Public Member Functions inherited from processorLOD
TypeName ("processorLOD")
processorLOD (const label maxObjectsPerLeaf, const label nObjectsOfType)
virtual ~processorLOD ()=default
virtual autoPtr< mapDistribute > map ()=0
Protected Member Functions
void writeBoxes (const List< DynamicList< treeBoundBox > > &fixedBoxes, const label iter) const
virtual boundBox calcSrcBox (const label srcObji) const =0
virtual boundBox calcTgtBox (const label tgtObji) const =0
void setRefineFlags (const label refineIter, const label nTgtObjects, List< labelHashSet > &fixedSendElems, List< List< labelList > > &localTgtElems, List< labelList > &refineFlags, labelList &nElems) const
void refineBox (const label boxi, const label refineIter, const label nSrcElem, const treeBoundBox &origBox, DynamicList< treeBoundBox > &procBoxes, DynamicList< labelList > &procBoxElems, DynamicList< label > &procNewToOld) const
void refineBox (const label boxi, const labelList &srcAddr, const treeBoundBox &origBox, DynamicList< treeBoundBox > &procBoxes, DynamicList< labelList > &procBoxElems, DynamicList< label > &procNewToOld) const
bool doRefineBoxes (const label refineIter, const label nSrcFaces, const List< labelList > &refineFlags, List< DynamicList< treeBoundBox > > &fixedBoxes)
autoPtr< mapDistribute > createMap (const label nSrcElems, const label nTgtElems)
Protected Attributes
const UList< point > & srcPoints_
const UList< point > & tgtPoints_
List< List< treeBoundBox > > boxes_
label nRefineIterMax_
List< labelList > newToOld_
List< List< labelList > > boxSrcElems_
Protected Attributes inherited from processorLOD
label maxObjectsPerLeaf_
label nObjectsOfType_
Static Protected Attributes
static const label DROP = 0
static const label REFINE = 1
static const label FIXED = 2
static const label nStartUpIter = 2
Detailed Description
Creates the parallel distribution map by describing the source and target objects using box shapes.
A single box is created for the source object, which is then split using 2x2x2 refinement based on the number of remote target objects that overlap. The refinement is local between communicating processor pairs, where the refinement continues until a threshold number of remote target objects per source box is achieved.
Definition at line 52 of file box.H.
Constructor & Destructor Documentation
box()
box (const UList< point > & srcPoints, const UList< point > & tgtPoints, const label maxObjectsPerLeaf, const label nObjectsOfType, const label nRefineIterMax = 100)
Definition at line 530 of file box.C.
References box::boxes_, forAll, UPtrList< T >::front(), PtrList< T >::resize(), UPtrList< T >::size(), and box::srcPoints_.
~box()
virtual ~box () virtual default
Member Function Documentation
writeBoxes()
void writeBoxes (const List< DynamicList< treeBoundBox > > & fixedBoxes, const label iter) const protected
Definition at line 41 of file box.C.
References UPstream::allProcs(), f(), treeBoundBox::faces, forAll, UPstream::myProcNo(), Foam::name(), Foam::nl, os(), treeBoundBox::points(), pts, UPtrList< T >::size(), and Foam::meshTools::writeOBJ().
calcSrcBox()
virtual boundBox calcSrcBox (const label srcObji) const protected pure virtual
Implemented in faceBox.
calcTgtBox()
virtual boundBox calcTgtBox (const label tgtObji) const protected pure virtual
Implemented in faceBox.
setRefineFlags()
void setRefineFlags (const label refineIter, const label nTgtObjects, List< labelHashSet > & fixedSendElems, List< List< labelList > > & localTgtElems, List< labelList > & refineFlags, labelList & nElems) const protected
Definition at line 91 of file box.C.
References UPstream::allProcs(), PtrList< T >::append(), UPtrList< T >::empty(), forAll, Foam::identity(), UPstream::myProcNo(), UPstream::nonBlocking, Foam::readLabel(), PtrList< T >::setSize(), UPtrList< T >::size(), and PtrList< T >::transfer().
refineBox() [1/2]
void refineBox (const label boxi, const label refineIter, const label nSrcElem, const treeBoundBox & origBox, DynamicList< treeBoundBox > & procBoxes, DynamicList< labelList > & procBoxElems, DynamicList< label > & procNewToOld) const protected
Definition at line 211 of file box.C.
References PtrList< T >::append(), and UPtrList< T >::size().
refineBox() [2/2]
void refineBox (const label boxi, const labelList & srcAddr, const treeBoundBox & origBox, DynamicList< treeBoundBox > & procBoxes, DynamicList< labelList > & procBoxElems, DynamicList< label > & procNewToOld) const protected
Definition at line 269 of file box.C.
References PtrList< T >::append(), and UPtrList< T >::size().
doRefineBoxes()
bool doRefineBoxes (const label refineIter, const label nSrcFaces, const List< labelList > & refineFlags, List< DynamicList< treeBoundBox > > & fixedBoxes) protected
Definition at line 306 of file box.C.
References Foam::abort(), UPstream::allProcs(), PtrList< T >::append(), Foam::FatalError, FatalErrorInFunction, forAll, UPstream::myProcNo(), UPstream::nonBlocking, UPstream::nProcs(), Foam::returnReduceOr(), and UPtrList< T >::size().
createMap()
Foam::autoPtr< Foam::mapDistribute > createMap (const label nSrcElems, const label nTgtElems) protected
Definition at line 411 of file box.C.
References PtrList< T >::append(), PtrList< T >::clear(), Foam::endl(), forAll, Foam::identity(), UPstream::myProcNo(), autoPtr< T >::New(), Foam::nl, UPstream::nProcs(), Foam::Pout, UPtrList< T >::size(), Foam::tab, and Foam::Zero.
TypeName()
TypeName ("box")
Member Data Documentation
DROP
const Foam::label DROP = 0 static protected
Definition at line 63 of file box.H.
REFINE
const Foam::label REFINE = 1 static protected
Definition at line 66 of file box.H.
FIXED
const Foam::label FIXED = 2 static protected
Definition at line 69 of file box.H.
srcPoints_
const UList<point>& srcPoints_ protected
Definition at line 73 of file box.H.
Referenced by box::box(), and faceBox::calcSrcBox().
tgtPoints_
const UList<point>& tgtPoints_ protected
Definition at line 76 of file box.H.
boxes_
List<List<treeBoundBox> > boxes_ protected
Definition at line 80 of file box.H.
Referenced by box::box().
nRefineIterMax_
label nRefineIterMax_ protected
Definition at line 83 of file box.H.
nStartUpIter
const Foam::label nStartUpIter = 2 static protected
Definition at line 89 of file box.H.
newToOld_
List<labelList> newToOld_ protected
Definition at line 92 of file box.H.
boxSrcElems_
List<List<labelList> > boxSrcElems_ protected
Definition at line 95 of file box.H.
The documentation for this class was generated from the following files:
src/meshTools/processorLOD/box/box.H
src/meshTools/processorLOD/box/box.C