OpenFOAM: alphaContactAngleTwoPhaseFvPatchScalarField Class Reference
alphaContactAngleTwoPhaseFvPatchScalarField Class Reference abstract
Boundary conditions » Wall | Boundary conditions » Generic
Abstract base class for two-phase alphaContactAngle boundary conditions.
#include <alphaContactAngleTwoPhaseFvPatchScalarField.H>
Public Types
enum limitControls { lcNone , lcGradient , lcZeroGradient , lcAlpha }
Public Member Functions
alphaContactAngleTwoPhaseFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
alphaContactAngleTwoPhaseFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
alphaContactAngleTwoPhaseFvPatchScalarField (const alphaContactAngleTwoPhaseFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
alphaContactAngleTwoPhaseFvPatchScalarField (const alphaContactAngleTwoPhaseFvPatchScalarField &)
alphaContactAngleTwoPhaseFvPatchScalarField (const alphaContactAngleTwoPhaseFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< scalarField > theta (const fvPatchVectorField &Up, const fvsPatchVectorField &nHat) const =0
virtual void evaluate (const Pstream::commsTypes commsType=Pstream::commsTypes::blocking)
virtual void write (Ostream &os) const
Public Attributes
limitControls limit_
Static Public Attributes
static const Enum< limitControls > limitControlNames_
Detailed Description
Abstract base class for two-phase alphaContactAngle boundary conditions.
Derived classes must implement the theta() function which returns the wall contact angle field.
The essential entry "limit" controls the gradient of alpha1 on the wall:
none - Calculate the gradient from the contact-angle without limiter
gradient - Limit the wall-gradient such that alpha1 remains bounded on the wall
alpha - Bound the calculated alpha1 on the wall
zeroGradient - Set the gradient of alpha1 to 0 on the wall, i.e. reproduce previous behaviour, the pressure BCs can be left as before.
Note that if any of the first three options are used the boundary condition on p_rgh must set to guarantee that the flux is corrected to be zero at the wall e.g.:
<patchName>
{
    type            alphaContactAngle;
    limit           none;
}
Source files
alphaContactAngleTwoPhaseFvPatchScalarField.H
alphaContactAngleTwoPhaseFvPatchScalarField.C
Definition at line 74 of file alphaContactAngleTwoPhaseFvPatchScalarField.H.
Member Enumeration Documentation
limitControls
enum limitControls
Enumerator
lcNone
lcGradient
lcZeroGradient
lcAlpha
Definition at line 83 of file alphaContactAngleTwoPhaseFvPatchScalarField.H.
Constructor & Destructor Documentation
alphaContactAngleTwoPhaseFvPatchScalarField() [1/5]
alphaContactAngleTwoPhaseFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 43 of file alphaContactAngleTwoPhaseFvPatchScalarField.C.
alphaContactAngleTwoPhaseFvPatchScalarField() [2/5]
alphaContactAngleTwoPhaseFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 55 of file alphaContactAngleTwoPhaseFvPatchScalarField.C.
References dict, and Foam::Zero.
alphaContactAngleTwoPhaseFvPatchScalarField() [3/5]
alphaContactAngleTwoPhaseFvPatchScalarField (const alphaContactAngleTwoPhaseFvPatchScalarField & acpsf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 80 of file alphaContactAngleTwoPhaseFvPatchScalarField.C.
alphaContactAngleTwoPhaseFvPatchScalarField() [4/5]
alphaContactAngleTwoPhaseFvPatchScalarField (const alphaContactAngleTwoPhaseFvPatchScalarField & acpsf)
Definition at line 94 of file alphaContactAngleTwoPhaseFvPatchScalarField.C.
alphaContactAngleTwoPhaseFvPatchScalarField() [5/5]
alphaContactAngleTwoPhaseFvPatchScalarField (const alphaContactAngleTwoPhaseFvPatchScalarField & acpsf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 105 of file alphaContactAngleTwoPhaseFvPatchScalarField.C.
Member Function Documentation
theta()
virtual tmp< scalarField > theta (const fvPatchVectorField & Up, const fvsPatchVectorField & nHat) const pure virtual
Implemented in constantAlphaContactAngleFvPatchScalarField, dynamicAlphaContactAngleFvPatchScalarField, temperatureDependentAlphaContactAngleFvPatchScalarField, and timeVaryingAlphaContactAngleFvPatchScalarField.
evaluate()
void evaluate (const Pstream::commsTypes commsType = Pstream::commsTypes::blocking) virtual
Definition at line 119 of file alphaContactAngleTwoPhaseFvPatchScalarField.C.
References Foam::clamp(), Field< scalar >::operator=(), and Foam::Zero.
Referenced by constantAlphaContactAngleFvPatchScalarField::constantAlphaContactAngleFvPatchScalarField(), dynamicAlphaContactAngleFvPatchScalarField::dynamicAlphaContactAngleFvPatchScalarField(), temperatureDependentAlphaContactAngleFvPatchScalarField::temperatureDependentAlphaContactAngleFvPatchScalarField(), and timeVaryingAlphaContactAngleFvPatchScalarField::timeVaryingAlphaContactAngleFvPatchScalarField().
write()
void write (Ostream & os) const virtual
Reimplemented in constantAlphaContactAngleFvPatchScalarField, dynamicAlphaContactAngleFvPatchScalarField, temperatureDependentAlphaContactAngleFvPatchScalarField, and timeVaryingAlphaContactAngleFvPatchScalarField.
Definition at line 147 of file alphaContactAngleTwoPhaseFvPatchScalarField.C.
References os(), fixedGradientFvPatchField< Type >::write(), and Ostream::writeEntry().
Referenced by constantAlphaContactAngleFvPatchScalarField::write(), dynamicAlphaContactAngleFvPatchScalarField::write(), temperatureDependentAlphaContactAngleFvPatchScalarField::write(), and timeVaryingAlphaContactAngleFvPatchScalarField::write().
Member Data Documentation
limitControlNames_
const Foam::Enum< Foam::alphaContactAngleTwoPhaseFvPatchScalarField::limitControls > limitControlNames_ static
Definition at line 91 of file alphaContactAngleTwoPhaseFvPatchScalarField.H.
limit_
limitControls limit_
Definition at line 92 of file alphaContactAngleTwoPhaseFvPatchScalarField.H.
The documentation for this class was generated from the following files:
src/transportModels/interfaceProperties/alphaContactAngle/alphaContactAngleTwoPhaseFvPatchScalarField.H
src/transportModels/interfaceProperties/alphaContactAngle/alphaContactAngleTwoPhaseFvPatchScalarField.C