OpenFOAM: dynamicTreeDataPoint Class Reference
dynamicTreeDataPoint Class Reference
Holds (reference to) pointField. Encapsulation of data needed for octree searches. Used for searching for nearest point. No bounding boxes around points. Only overlaps and calcNearest are implemented, rest makes little sense.
#include <dynamicTreeDataPoint.H>
Public Member Functions
ClassNameNoDebug ("dynamicTreeDataPoint")
dynamicTreeDataPoint (const DynamicList< point > &points)
int nDim () const noexcept
treeBoundBox bounds (const labelUList &indices) const
const DynamicList< point > & points () const noexcept
bool useSubset () const noexcept
const labelList& pointLabels() const noexcept { labelList::null(); }
bool empty () const noexcept
label size () const noexcept
label objectIndex (label index) const noexcept
const point & operator[] (label index) const
const point & centre (label index) const
const DynamicList< point > & centres () const noexcept
volumeType getVolumeType (const dynamicIndexedOctree< dynamicTreeDataPoint > &, const point &) const
bool overlaps (const label index, const treeBoundBox &searchBox) const
bool overlaps (const label index, const point &centre, const scalar radiusSqr) const
void findNearest (const labelUList &indices, const point &sample, scalar &nearestDistSqr, label &nearestIndex, point &nearestPoint) const
void findNearest (const labelUList &indices, const linePointRef &ln, treeBoundBox &tightest, label &minIndex, point &linePoint, point &nearestPoint) const
bool intersects (const label index, const point &start, const point &end, point &result) const
Detailed Description
Holds (reference to) pointField. Encapsulation of data needed for octree searches. Used for searching for nearest point. No bounding boxes around points. Only overlaps and calcNearest are implemented, rest makes little sense.
Optionally works on subset of points.
Source files
dynamicTreeDataPoint.H
dynamicTreeDataPoint.C
Definition at line 58 of file dynamicTreeDataPoint.H.
Constructor & Destructor Documentation
dynamicTreeDataPoint()
dynamicTreeDataPoint (const DynamicList< point > & points) explicit
Definition at line 35 of file dynamicTreeDataPoint.C.
Member Function Documentation
ClassNameNoDebug()
ClassNameNoDebug ("dynamicTreeDataPoint")
nDim()
int nDim () const inline noexcept
Definition at line 81 of file dynamicTreeDataPoint.H.
bounds()
Foam::treeBoundBox bounds (const labelUList & indices) const
Definition at line 47 of file dynamicTreeDataPoint.C.
points()
const DynamicList< point > & points () const inline noexcept
Definition at line 90 of file dynamicTreeDataPoint.H.
useSubset()
bool useSubset () const inline noexcept
const labelList& pointLabels() const noexcept { labelList::null(); }
Definition at line 96 of file dynamicTreeDataPoint.H.
empty()
bool empty () const inline noexcept
Definition at line 99 of file dynamicTreeDataPoint.H.
References UPtrList< T >::empty().
size()
label size () const inline noexcept
Definition at line 102 of file dynamicTreeDataPoint.H.
References UPtrList< T >::size().
objectIndex()
label objectIndex (label index) const inline noexcept
Definition at line 105 of file dynamicTreeDataPoint.H.
operator[]()
const point & operator[] (label index) const inline
Definition at line 108 of file dynamicTreeDataPoint.H.
centre()
const point & centre (label index) const inline
Definition at line 111 of file dynamicTreeDataPoint.H.
centres()
const DynamicList< point > & centres () const inline noexcept
Definition at line 114 of file dynamicTreeDataPoint.H.
getVolumeType()
Foam::volumeType getVolumeType (const dynamicIndexedOctree< dynamicTreeDataPoint > & oc, const point & sample) const
Definition at line 53 of file dynamicTreeDataPoint.C.
References volumeType::UNKNOWN.
overlaps() [1/2]
bool overlaps (const label index, const treeBoundBox & searchBox) const
Definition at line 63 of file dynamicTreeDataPoint.C.
overlaps() [2/2]
bool overlaps (const label index, const point & centre, const scalar radiusSqr) const
Definition at line 73 of file dynamicTreeDataPoint.C.
References Vector< Cmpt >::distSqr().
findNearest() [1/2]
void findNearest (const labelUList & indices, const point & sample, scalar & nearestDistSqr, label & nearestIndex, point & nearestPoint) const
Definition at line 84 of file dynamicTreeDataPoint.C.
findNearest() [2/2]
void findNearest (const labelUList & indices, const linePointRef & ln, treeBoundBox & tightest, label & minIndex, point & linePoint, point & nearestPoint) const
Definition at line 110 of file dynamicTreeDataPoint.C.
References Foam::ln(), and Foam::sqr().
intersects()
bool intersects (const label index, const point & start, const point & end, point & result) const inline
Definition at line 169 of file dynamicTreeDataPoint.H.
References NotImplemented.
The documentation for this class was generated from the following files:
src/OpenFOAM/algorithms/dynamicIndexedOctree/dynamicTreeDataPoint.H
src/OpenFOAM/algorithms/dynamicIndexedOctree/dynamicTreeDataPoint.C