OpenFOAM: UList< T > Class Template Reference
UList< T > Class Template Reference
A 1D vector of objects of type <T>, where the size of the vector is known and can be used for subscript bounds checking, etc.
#include <UList.H>
Inherited by List< CloudFunctionObject< CloudType > * >, List< label >, List< char >, List< T * >, List< Type >, List< List< scalar > >, List< scalar >, List< Field< Type > * >, List< PatchField< Type > * >, List< InjectionModel< CloudType > * >, List< fvPatchField< symmTensor > * >, List< symmTensor >, List< fvPatchField< scalar > * >, List< MRFZone * >, List< pointPatchField< Type > * >, List< Face >, List< token >, List< taggedInfoType >, List< point >, List< ParticleForce< CloudType > * >, List< joint * >, List< ZoneType * >, List< vector >, List< block_type >, List< block * >, List< Field< Type > >, List< Foam::boundBox >, List< coalCloud * >, List< coordinateSystem * >, List< Field< scalar > >, List< FixedList< point, N > >, List< vectorField >, List< List< pointIndexHit > >, List< pointIndexHit >, List< fa::option * >, List< entry * >, List< faPatchMapper * >, List< functionObject * >, List< fieldInfo >, List< fv::option * >, List< fvPatchMapper * >, List< gradingDescriptor >, List< Tuple2< scalar, List< Tuple2< scalar, Type > > > >, List< Tuple2< scalar, Type > >, List< scalarField >, List< Foam::labelRange >, List< substance >, List< pairPotential * >, List< patchInteractionData >, List< pointPatchMapper * >, List< face >, List< polyMeshModifier * >, List< porosityModel * >, List< std::function< bool(Foam::scalar)> >, List< word >, List< profileModel * >, List< Reaction< ThermoType > * >, List< Foam::Reaction::specieCoeffs >, List< extendedFeatureEdgeMesh * >, List< force * >, List< injectionModel * >, List< pyrolysisModel * >, List< regionModelFunctionObject * >, List< transferModel * >, List< sampledSet * >, List< sampledSurface * >, List< scalarRange >, List< searchableSurface * >, List< simpleRegIOobject * >, List< tetherPotential * >, List< labelledTri >, List< refineCell >, List< wordRe >, List< Foam::treeBoundBox >, List< Foam::List >, List< labelList >, List< scalarList >, List< pointList >, List< fvPatchField< vector > * >, List< fvPatchField< tensor > * >, List< tensor >, List< TypeGrad >, List< Foam::SymmTensor >, List< Foam::GeometricField * >, List< bool >, List< List< bool > >, List< Foam::Vector >, List< Foam::PairCollisionRecord< vector > >, List< Foam::WallCollisionRecord< vector > >, List< Foam::PairCollisionRecord< PairType > >, List< Foam::WallCollisionRecord< WallType > >, List< Foam::Tuple2< Foam::Vector, Foam::Vector > >, List< Foam::word >, List< int >, List< Foam::Tuple2< Foam::word, scalar > >, List< solveScalar >, List< Foam::complex >, List< Foam::DynamicList< ParcelType * > >, List< ParcelType * >, List< typename ParcelType::constantProperties >, List< Foam::fvPatchField< scalar > * >, List< Foam::fvPatchField< Foam::Vector > * >, List< Foam::pointPatchField< Foam::Vector > * >, List< Foam::radiation::reflectionModel * >, List< Field< Foam::Vector > * >, List< Field< scalar > * >, List< Foam::STLpoint >, List< tokenType >, List< DType >, List< cmptType >, List< interactionType >, List< Foam::OFstream * >, List< Foam::Field >, List< Foam::List< Foam::Field< scalar > > >, List< Foam::Field< scalar > >, List< Foam::Tuple2< Type, Type > >, List< Foam::Tuple2< scalar, Type > >, List< Foam::Field * >, List< Foam::List * >, List< Foam::lduPrimitiveMesh * >, List< Foam::lduMatrix * >, List< Foam::PtrList< Foam::lduInterfaceField > * >, List< Foam::lduInterfaceField * >, List< Foam::UPtrList * >, List< Foam::FieldField< Foam::Field, scalar > * >, List< Foam::Field< scalar > * >, List< Foam::Tuple2 >, List< List< vector > >, List< Foam::distributionModels::general * >, List< Foam::Pair >, List< Foam::referredWallFace >, List< Foam::ILList< ParticleType > >, List< Foam::DynamicList< parcelType * > >, List< parcelType * >, List< ParticleForce< KinematicCloud< Foam::DSMCCloud > > * >, List< CloudFunctionObject< KinematicCloud< Foam::DSMCCloud > > * >, List< InjectionModel< Foam::KinematicCloud< Foam::DSMCCloud > > * >, List< ParticleForce< KinematicCloud< CloudType > > * >, List< CloudFunctionObject< KinematicCloud< CloudType > > * >, List< kinematicParcelInjectionData >, List< Foam::regionModels::areaSurfaceFilmModels::liquidFilmBase * >, List< LUType >, List< Type * >, List< Foam::Field< LUType > * >, List< Foam::List< label > >, List< Foam::List< scalar > >, List< surfZone >, List< fvsPatchField< scalar > * >, List< Foam::PatchInteractionModel< Foam::DSMCCloud > * >, List< boolVector >, List< Foam::List< char > * >, List< Foam::Vector< bool > >, List< boundaryEntry * >, List< direction >, List< Foam::ILList< typename CloudType::parcelType > >, List< Foam::face >, List< Foam::List< Foam::face > >, List< Foam::DynamicList< scalar > >, List< Foam::DynamicList< Foam::string > >, List< Foam::string >, List< Foam::particleInfo >, List< instant >, List< Foam::diameterModels::populationBalanceModel * >, List< InputType >, List< Foam::DynamicList< char > >, List< Foam::SpatialVector >, List< Foam::RBD::rigidBody * >, List< Foam::RBD::subBody * >, List< Foam::RBD::joint * >, List< Foam::spatialTransform >, List< Foam::RBD::restraint * >, List< Foam::SpatialTensor >, List< Foam::CompactSpatialTensor >, List< Foam::Tensor >, List< Foam::DimensionedField * >, List< reactingParcelInjectionData >, List< reactingMultiphaseParcelInjectionData >, List< Foam::Pair< Foam::word > >, List< Foam::Pair< label > >, List< Foam::ILList< parcelType > >, List< Foam::patchInjectionBase * >, List< volatileData >, List< Foam::Reaction< ThermoType > * >, List< ThermoType * >, List< Foam::List< Foam::specieElement > >, List< Foam::specieElement >, List< complexVector >, List< Foam::List< int > >, List< Foam::List< Foam::UPstream::commsStruct > >, List< Foam::UPstream::commsStruct >, List< Foam::surfZoneIdentifier >, List< Foam::adjointSolver * >, List< Foam::DynamicList< Foam::face > >, List< node >, List< string >, List< Foam::Function1< scalar > * >, List< treeBoundBox >, List< Foam::hexCell >, List< Foam::FixedList< label, 4 > >, List< Foam::gradingDescriptors >, List< blockVertex * >, List< blockEdge * >, List< blockFace * >, List< cellShape >, List< faceList >, List< Foam::entry * >, List< Foam::boundaryPatch * >, List< edge >, List< Foam::wordRes >, List< Foam::fvMeshSubset * >, List< Foam::DynamicList< label > >, List< Foam::cellModel * >, List< const Foam::cellModel * >, List< Foam::cellSizeAndAlignmentControl * >, List< Foam::Tuple2< Foam::word, Foam::Tuple2< bool, scalar > > >, List< pointPatchField< scalar > * >, List< CGAL::indexedVertex >, List< Foam::extendedFeatureEdgeMesh * >, List< sideVolumeType >, List< Foam::surfaceZonesInfo * >, List< Foam::dictionary * >, List< Foam::volumeType >, List< const Foam::coordSet * >, List< Foam::Field< label > * >, List< Foam::Field< Foam::Vector > * >, List< Foam::Field< Foam::SphericalTensor > * >, List< Foam::SphericalTensor >, List< Foam::Field< Foam::SymmTensor > * >, List< Foam::Field< Foam::Tensor > * >, List< Foam::Function1< Type > * >, List< Foam::Field< Type > >, List< Foam::DynamicList< Foam::Vector > >, List< Foam::topoSetFaceSource * >, List< Foam::Tuple2< Foam::word, label > >, List< Foam::decompositionConstraint * >, List< Foam::diameterModels::IATEsource * >, List< Tuple2< scalar, scalar > >, List< Foam::PtrList< Foam::dimensioned > * >, List< Foam::dimensioned * >, List< Foam::phasePairKey >, List< Foam::diameterModels::velocityGroup * >, List< Foam::diameterModels::sizeGroup * >, List< Foam::diameterModels::coalescenceModel * >, List< Foam::diameterModels::breakupModel * >, List< Foam::diameterModels::binaryBreakupModel * >, List< Foam::diameterModels::driftModel * >, List< Foam::diameterModels::nucleationModel * >, List< Foam::token >, List< pointPatchField< vector > * >, List< Foam::Field< solveScalar > * >, List< Foam::UPstream::Request >, List< Foam::FieldField< Foam::Field, solveScalar > * >, List< Foam::List< Foam::treeBoundBox > >, List< Foam::VectorSpace >, List< void * >, List< Foam::fileName >, List< Foam::Tuple2< Foam::fileName, std::string > >, List< Foam::motionSolver * >, List< Foam::objectHit >, List< Foam::expressions::exprString >, List< Foam::expressions::exprResultStored >, List< Foam::indexedOctree< Foam::treeDataEdge > * >, List< temperatureCoupling * >, List< Foam::PatchFunction1Types::MappedFile< scalar > * >, List< faPatchField< scalar > * >, List< Foam::faFieldDecomposer::patchFieldDecomposer * >, List< Foam::faFieldDecomposer::processorAreaPatchFieldDecomposer * >, List< Foam::faFieldDecomposer::processorEdgePatchFieldDecomposer * >, List< Foam::GeometricField< scalar, Foam::faPatchField, Foam::areaMesh > * >, List< Foam::faPatchField< scalar > * >, List< Foam::GeometricField< scalar, Foam::faePatchField, Foam::edgeMesh > * >, List< Foam::faePatchField< scalar > * >, List< Foam::GeometricField< Foam::Vector, Foam::faPatchField, Foam::areaMesh > * >, List< Foam::faPatchField< Foam::Vector > * >, List< Foam::GeometricField< Foam::Vector, Foam::faePatchField, Foam::edgeMesh > * >, List< Foam::faePatchField< Foam::Vector > * >, List< Foam::GeometricField< Foam::SphericalTensor, Foam::faPatchField, Foam::areaMesh > * >, List< Foam::faPatchField< Foam::SphericalTensor > * >, List< Foam::GeometricField< Foam::SphericalTensor, Foam::faePatchField, Foam::edgeMesh > * >, List< Foam::faePatchField< Foam::SphericalTensor > * >, List< Foam::GeometricField< Foam::SymmTensor, Foam::faPatchField, Foam::areaMesh > * >, List< Foam::faPatchField< Foam::SymmTensor > * >, List< Foam::GeometricField< Foam::SymmTensor, Foam::faePatchField, Foam::edgeMesh > * >, List< Foam::faePatchField< Foam::SymmTensor > * >, List< Foam::GeometricField< Foam::Tensor, Foam::faPatchField, Foam::areaMesh > * >, List< Foam::faPatchField< Foam::Tensor > * >, List< Foam::GeometricField< Foam::Tensor, Foam::faePatchField, Foam::edgeMesh > * >, List< Foam::faePatchField< Foam::Tensor > * >, List< Foam::faMesh * >, List< Foam::IOList * >, List< Foam::Field< Type > * >, List< Foam::Map< label > >, List< Foam::mapDistributeBase * >, List< const Foam::UList * >, List< Foam::triPoints >, List< ABAQUSCore::shapeType >, List< fileState >, List< double >, List< Foam::List< Foam::Vector > >, List< Foam::PointIndexHit >, List< errorHandlingType >, List< Foam::SHA1Digest >, List< derivedType >, List< Foam::wordRe >, List< Foam::functionObjects::eulerianParticle >, List< Foam::functionObjects::fieldAverageItem >, List< Foam::functionObjects::fieldInfo >, List< Foam::functionObject * >, List< ParticleForce< KinematicCloud< Cloud< basicKinematicCollidingParcel > > > * >, List< CloudFunctionObject< KinematicCloud< Cloud< basicKinematicCollidingParcel > > > * >, List< Foam::Tuple2< Foam::word, Foam::word > >, List< Foam::functionObjects::runTimeControls::runTimeCondition * >, List< Foam::DynamicList< Foam::List > >, List< Foam::DynamicList< List< vector > > >, List< Foam::Tuple2< scalar, Foam::fileName > >, List< Foam::vtk::vtuCells * >, List< Tuple2< scalar, List< Tuple2< scalar, scalar > > > >, List< Foam::fvFieldDecomposer::patchFieldDecomposer * >, List< Foam::fvFieldDecomposer::processorVolPatchFieldDecomposer * >, List< Foam::fvFieldDecomposer::processorSurfacePatchFieldDecomposer * >, List< Foam::DimensionedField< scalar, Foam::volMesh > * >, List< Foam::GeometricField< scalar, Foam::fvPatchField, Foam::volMesh > * >, List< Foam::GeometricField< scalar, Foam::fvsPatchField, Foam::surfaceMesh > * >, List< Foam::fvsPatchField< scalar > * >, List< Foam::DimensionedField< Foam::Vector, Foam::volMesh > * >, List< Foam::GeometricField< Foam::Vector, Foam::fvPatchField, Foam::volMesh > * >, List< Foam::GeometricField< Foam::Vector, Foam::fvsPatchField, Foam::surfaceMesh > * >, List< Foam::fvsPatchField< Foam::Vector > * >, List< Foam::DimensionedField< Foam::SphericalTensor, Foam::volMesh > * >, List< Foam::GeometricField< Foam::SphericalTensor, Foam::fvPatchField, Foam::volMesh > * >, List< Foam::fvPatchField< Foam::SphericalTensor > * >, List< Foam::GeometricField< Foam::SphericalTensor, Foam::fvsPatchField, Foam::surfaceMesh > * >, List< Foam::fvsPatchField< Foam::SphericalTensor > * >, List< Foam::DimensionedField< Foam::SymmTensor, Foam::volMesh > * >, List< Foam::GeometricField< Foam::SymmTensor, Foam::fvPatchField, Foam::volMesh > * >, List< Foam::fvPatchField< Foam::SymmTensor > * >, List< Foam::GeometricField< Foam::SymmTensor, Foam::fvsPatchField, Foam::surfaceMesh > * >, List< Foam::fvsPatchField< Foam::SymmTensor > * >, List< Foam::DimensionedField< Foam::Tensor, Foam::volMesh > * >, List< Foam::GeometricField< Foam::Tensor, Foam::fvPatchField, Foam::volMesh > * >, List< Foam::fvPatchField< Foam::Tensor > * >, List< Foam::GeometricField< Foam::Tensor, Foam::fvsPatchField, Foam::surfaceMesh > * >, List< Foam::fvsPatchField< Foam::Tensor > * >, List< Foam::fvMesh * >, List< Foam::fvMatrix< Type > * >, List< Foam::glTF::animation::glTFSampler >, List< Foam::glTF::animation::glTFChannel >, List< Foam::Tuple2< Foam::string, label > >, List< float >, List< Foam::vectorTensorTransform >, List< Foam::MinMax >, List< Foam::ignitionSite * >, List< Foam::implicitFunction * >, List< Foam::adjointSolverManager * >, List< Foam::incompressible::adjointSensitivity * >, List< Foam::fvPatchField< Type > * >, List< Foam::pointPatchField< Type > * >, List< Foam::fvsPatchField< Type > * >, List< Foam::dictionary >, List< DynamicList< label > >, List< cutType >, List< Foam::FixedList< label, 3 > >, List< Foam::FixedList< scalar, 3 > >, List< Foam::edge >, List< Foam::cellShape >, List< Foam::PtrList< Foam::IOField< label > > * >, List< Foam::IOField< label > * >, List< Foam::PtrList< Foam::CompactIOField< Foam::Field< label >, label > > * >, List< Foam::CompactIOField< Foam::Field< label >, label > * >, List< Foam::Field< label > >, List< Foam::PtrList< Foam::IOField< scalar > > * >, List< Foam::IOField< scalar > * >, List< Foam::PtrList< Foam::CompactIOField< Foam::Field< scalar >, scalar > > * >, List< Foam::CompactIOField< Foam::Field< scalar >, scalar > * >, List< Foam::PtrList< Foam::IOField< Foam::Vector > > * >, List< Foam::IOField< Foam::Vector > * >, List< Foam::PtrList< Foam::CompactIOField< Foam::Field< Foam::Vector >, Foam::Vector > > * >, List< Foam::CompactIOField< Foam::Field< Foam::Vector >, Foam::Vector > * >, List< Foam::Field< Foam::Vector > >, List< Foam::PtrList< Foam::IOField< Foam::SphericalTensor > > * >, List< Foam::IOField< Foam::SphericalTensor > * >, List< Foam::PtrList< Foam::CompactIOField< Foam::Field< Foam::SphericalTensor >, Foam::SphericalTensor > > * >, List< Foam::CompactIOField< Foam::Field< Foam::SphericalTensor >, Foam::SphericalTensor > * >, List< Foam::Field< Foam::SphericalTensor > >, List< Foam::PtrList< Foam::IOField< Foam::SymmTensor > > * >, List< Foam::IOField< Foam::SymmTensor > * >, List< Foam::PtrList< Foam::CompactIOField< Foam::Field< Foam::SymmTensor >, Foam::SymmTensor > > * >, List< Foam::CompactIOField< Foam::Field< Foam::SymmTensor >, Foam::SymmTensor > * >, List< Foam::Field< Foam::SymmTensor > >, List< Foam::PtrList< Foam::IOField< Foam::Tensor > > * >, List< Foam::IOField< Foam::Tensor > * >, List< Foam::PtrList< Foam::CompactIOField< Foam::Field< Foam::Tensor >, Foam::Tensor > > * >, List< Foam::CompactIOField< Foam::Field< Foam::Tensor >, Foam::Tensor > * >, List< Foam::Field< Foam::Tensor > >, List< Foam::List< Foam::List< scalar > > >, List< thicknessModelType >, List< const lduInterfaceField * >, List< const lduInterface * >, List< const Foam::lduInterface * >, List< lduScheduleEntry >, List< Foam::lduMesh * >, List< labelListList >, List< fvsPatchField< vector > * >, List< Foam::liquidProperties * >, List< Foam::lumpedPointInterpolator >, List< Foam::Tuple2< label, Foam::List< Foam::List > > >, List< Foam::objectMap >, List< Foam::List< Foam::meshReader::cellFaceIdentifier > >, List< Foam::meshReader::cellFaceIdentifier >, List< cell >, List< Foam::Tuple2< mapType, Foam::List > >, List< Foam::AMIInterpolation * >, List< Foam::DynamicList< Foam::molecule * > >, List< Foam::molecule * >, List< Foam::ILList< Foam::molecule > >, List< Foam::molecule::constantProperties >, List< Foam::decompositionMethod * >, List< Foam::solidBodyMotionFunction * >, List< Foam::multiphaseInter::phaseModel * >, List< Foam::objective * >, List< Foam::primalSolver * >, List< Foam::DynamicList< Type > >, List< const Foam::lduPrimitiveProcessorInterface * >, List< Foam::PrimitivePatch * >, List< Foam::phaseProperties >, List< phaseModel * >, List< Foam::pointConstraint >, List< Foam::pointFieldDecomposer::patchFieldDecomposer * >, List< Foam::GeometricField< scalar, Foam::pointPatchField, Foam::pointMesh > * >, List< Foam::pointPatchField< scalar > * >, List< Foam::GeometricField< Foam::Vector, Foam::pointPatchField, Foam::pointMesh > * >, List< Foam::GeometricField< Foam::SphericalTensor, Foam::pointPatchField, Foam::pointMesh > * >, List< Foam::pointPatchField< Foam::SphericalTensor > * >, List< Foam::GeometricField< Foam::SymmTensor, Foam::pointPatchField, Foam::pointMesh > * >, List< Foam::pointPatchField< Foam::SymmTensor > * >, List< Foam::GeometricField< Foam::Tensor, Foam::pointPatchField, Foam::pointMesh > * >, List< Foam::pointPatchField< Foam::Tensor > * >, List< Foam::pointMesh * >, List< Foam::PrimitivePatchInterpolation * >, List< pointZone * >, List< faceZone * >, List< cellZone * >, List< Foam::procLduInterface * >, List< Foam::List< Foam::List > >, List< Foam::Time * >, List< Foam::profilingInformation * >, List< Foam::DynamicList< Foam::profilingInformation *, 16 > >, List< Foam::clockValue >, List< GasThermo * >, List< Foam::Tuple2< scalar, scalar > >, List< Foam::radiation::boundaryRadiationPropertiesPatch * >, List< Foam::radiation::radiativeIntensityRay * >, List< Foam::FixedList< scalar, 2 > >, List< Foam::List< Foam::tmp< Foam::Field > > >, List< Foam::tmp< Foam::Field > >, List< Foam::indexedOctree< Foam::treeDataPoint > * >, List< Foam::refinementHistory::splitCell8 >, List< faPatchField< tensor > * >, List< faPatchField< vector > * >, List< faePatchField< scalar > * >, List< Foam::PtrList< Foam::AMIInterpolation > * >, List< Foam::Tuple2< label, scalar > >, List< bodyMesh * >, List< Foam::mappedPatchBase * >, List< Foam::coordSetWriter * >, List< Foam::coordSet * >, List< Foam::globalIndex >, List< Foam::surfaceWriter * >, List< unsigned >, List< Foam::coordSystem::cartesian * >, List< Foam::searchableSurface * >, List< Foam::cellSizeFunction * >, List< refineMode >, List< Foam::Tuple2< Foam::Pair, Foam::Vector > >, List< Foam::List< Foam::FixedList< label, 3 > > >, List< Foam::List< Foam::volumeType > >, List< Foam::sixDoFRigidBodyMotionRestraint * >, List< Foam::sixDoFRigidBodyMotionConstraint * >, List< Foam::Vector2D >, List< Foam::Reaction< SolidThermo > * >, List< SolidThermo * >, List< Foam::solidProperties * >, List< Foam::solutionControl::fieldData >, List< Foam::PtrList< Foam::dimensionSet > >, List< Foam::dimensionSet * >, List< Foam::interpolation< scalar > * >, List< Foam::interpolation< Foam::Vector > * >, List< Foam::topoDistanceData< label > >, List< Foam::triSurfaceMesh * >, List< Foam::bitSet >, List< geometricSurfacePatch >, List< Foam::indexedOctree * >, List< Foam::Function1< Foam::Vector > * >, List< Foam::Function1< Foam::SymmTensor > * >, List< Foam::eddy >, List< Foam::Function1< TypeR > * >, List< fileName >, List< Foam::NURBS3DVolume * >, List< Foam::autoPtr< Foam::NURBS3DVolume > >, List< const Foam::Field * >, List< Foam::Instant >, List< vtmEntry >, List< uint8_t >, SubList< Type >, List< T >, SubList< T >, and pTraits< UList< T > >.
Classes
struct greater
struct Hash
struct hasher
struct less
Public Types
typedef T value_type
typedef T * pointer
typedef const T * const_pointer
typedef T & reference
typedef const T & const_reference
typedef T * iterator
typedef const T * const_iterator
typedef label size_type
typedef label difference_type
typedef std::reverse_iterator< iterator > reverse_iterator
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
Public Member Functions
UList (const UList< T > &)=default
constexpr UList () noexcept
UList (T *__restrict__ v, const label len) noexcept
label fcIndex (const label i) const noexcept
label rcIndex (const label i) const noexcept
const T & fcValue (const label i) const
T & fcValue (const label i)
const T & rcValue (const label i) const
T & rcValue (const label i)
const T * cdata () const noexcept
T * data () noexcept
const char * cdata_bytes () const noexcept
char * data_bytes () noexcept
T & front ()
const T & front () const
T & back ()
const T & back () const
std::streamsize size_bytes () const noexcept
std::streamsize byteSize () const
void checkStart (const label start) const
void checkSize (const label size) const
void checkRange (const label start, const label len) const
void checkIndex (const label i) const
bool uniform () const
label find (const T &val, label pos=0) const
label rfind (const T &val, label pos=-1) const
bool contains (const T &val, label pos=0) const
void moveFirst (const label i)
void moveLast (const label i)
void swapFirst (const label i)
void swapLast (const label i)
void shallowCopy (const UList< T > &list)
void deepCopy (const UList< T > &list)
template<class Addr >
void deepCopy (const IndirectListBase< T, Addr > &list)
SubList< T > slice (const label pos, label len=-1)
const SubList< T > slice (const label pos, label len=-1) const
SubList< T > slice (const labelRange &range)
const SubList< T > slice (const labelRange &range) const
T & operator[] (const label i)
const T & operator[] (const label i) const
operator const Foam::List< T > & () const
void operator= (const T &val)
void operator= (const Foam::zero)
iterator begin () noexcept
iterator end () noexcept
iterator begin (const label i) noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
const_iterator begin () const noexcept
const_iterator end () const noexcept
const_iterator cbegin (const label i) const noexcept
const_iterator begin (const label i) const noexcept
reverse_iterator rbegin ()
reverse_iterator rend ()
const_reverse_iterator crbegin () const
const_reverse_iterator crend () const
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
bool empty () const noexcept
label size () const noexcept
void swap (UList< T > &list)
bool operator== (const UList< T > &a) const
bool operator!= (const UList< T > &a) const
bool operator< (const UList< T > &list) const
bool operator> (const UList< T > &a) const
bool operator<= (const UList< T > &a) const
bool operator>= (const UList< T > &a) const
Istream & readList (Istream &is)
void writeEntry (const word &keyword, Ostream &os) const
Ostream & writeList (Ostream &os, const label shortLen=0) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type test (const label i) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type get (const label i) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type unset (const label i)
T & first ()
const T & first () const
T & last ()
const T & last () const
bool found (const T &val, label pos=0) const
Istream & readList (Istream &is)
Ostream & writeList (Ostream &os, const label) const
const bool & operator[] (const label i) const
UPstream::commsStruct & operator[] (const label procID)
const UPstream::commsStruct & operator[] (const label procID) const
Foam::UPstream::commsStruct & operator[] (const label procID)
const Foam::UPstream::commsStruct & operator[] (const label procID) const
Ostream & writeList (Ostream &os, const label) const
Istream & readList (Istream &is)
Static Public Member Functions
static const UList< T > & null ()
static constexpr label max_size () noexcept
Protected Member Functions
void setAddressableSize (const label n) noexcept
void size (const label n)
void writeEntry (Ostream &os) const
labelRange validateRange (const labelRange &requestedRange) const
UList< T > & operator= (const UList< T > &)=delete
void writeEntry (Ostream &os) const
void writeEntry (Ostream &os) const
Friends
class List< T >
class SubList< T >
Istream & operator>> (Istream &os, UList< T > &list)
Detailed Description
template<class T>
class Foam::UList< T >
A 1D vector of objects of type <T>, where the size of the vector is known and can be used for subscript bounds checking, etc.
Storage is not allocated during construction or use but is supplied to the constructor as an argument. This type of list is particularly useful for lists that refer to parts of existing lists such as SubList.
Source files
UList.H
UList.C
UListI.H
UListIO.C
Definition at line 86 of file UList.H.
Member Typedef Documentation
value_type
template<class T > typedef T value_type
Definition at line 129 of file UList.H.
pointer
template<class T > typedef T* pointer
Definition at line 132 of file UList.H.
const_pointer
template<class T > typedef const T* const_pointer
Definition at line 135 of file UList.H.
reference
template<class T > typedef T& reference
Definition at line 138 of file UList.H.
const_reference
template<class T > typedef const T& const_reference
Definition at line 141 of file UList.H.
iterator
template<class T > typedef T* iterator
Definition at line 144 of file UList.H.
const_iterator
template<class T > typedef const T* const_iterator
Definition at line 147 of file UList.H.
size_type
template<class T > typedef label size_type
Definition at line 150 of file UList.H.
difference_type
template<class T > typedef label difference_type
Definition at line 153 of file UList.H.
reverse_iterator
template<class T > typedef std::reverse_iterator<iterator> reverse_iterator
Definition at line 156 of file UList.H.
const_reverse_iterator
template<class T > typedef std::reverse_iterator<const_iterator> const_reverse_iterator
Definition at line 159 of file UList.H.
Constructor & Destructor Documentation
UList() [1/3]
template<class T > UList (const UList< T > &) default
UList() [2/3]
template<class T > constexpr UList () inline constexpr noexcept
Definition at line 27 of file UListI.H.
UList() [3/3]
template<class T > UList (T *__restrict__ v, const label len) inline noexcept
Definition at line 35 of file UListI.H.
Member Function Documentation
setAddressableSize()
template<class T > void setAddressableSize (const label n) inline protected noexcept
Definition at line 428 of file UListI.H.
References n.
Referenced by PtrListDetail< CloudFunctionObject< CloudType > >::checkNonNull(), DynamicList< T, SizeMin >::clear(), DynamicField< T, SizeMin >::clear(), DynamicList< label >::DynamicList(), DynamicList< T, SizeMin >::expandStorage(), DynamicField< T, SizeMin >::expandStorage(), DynamicList< T, SizeMin >::remove(), DynamicList< T, SizeMin >::shrinkStorage(), DynamicField< T, SizeMin >::shrinkStorage(), and UList< T >::size().
size() [1/2]
template<class T > void size (const label n) inline protected
Definition at line 107 of file UList.H.
References UList< T >::setAddressableSize().
Referenced by mapDistributeBase::accessAndFlip(), polyMeshAdder::add(), fvMeshPrimitiveLduAddressing::addAddressing(), velocityDampingConstraint::addDamping(), object::addData(), addPatchCellLayer::addedCells(), mapPatchChange::addedPatches(), surfaceZonesInfo::addFaceZonesToMesh(), oversetFvMeshBase::addInterpolation(), fieldSelection::addRegistered(), regIOobject::addWatch(), fileMonitorWatcher::addWatch(), MeshedSurface< Face >::addZones(), MeshedSurface< Face >::addZones(), adjointSolverManager::adjointSolverManager(), oversetFvPatchField< Type >::adjustPsi(), masterCoarsestGAMGProcAgglomeration::agglomerate(), singleCellFvMesh::agglomerate(), pairGAMGAgglomeration::agglomerate(), pairGAMGAgglomeration::agglomerate(), GAMGAgglomeration::agglomerateLduAddressing(), UPstream::allocateCommunicator(), conjugateGradient::allocateFields(), BFGS::allocateMatrices(), DBFGS::allocateMatrices(), LBFGS::allocateMatrices(), SR1::allocateMatrices(), lduMatrix::Amul(), PDRblock::gridControl::append(), Foam::applyPermutation(), DiagonalMatrix< cmptType >::applyPermutation(), SquareMatrix< Type >::applyPermutation(), Foam::applyPermutation(), face::areaInContact(), argList::argList(), assemblyFaceAreaPairGAMGAgglomeration::assemblyFaceAreaPairGAMGAgglomeration(), bitSet::assign(), fvPatchField< Type >::autoMap(), extendedEdgeMesh::autoMap(), Foam::average(), snappySnapDriver::avgCellCentres(), Foam::meshTools::bandCompression(), STLAsciiParse::beginSolid(), Bezier::Bezier(), uniformBin::binAddr(), meshRefinement::blockLeakFaces(), searchableExtrudedCircle::boundingSpheres(), searchableSurfaceCollection::boundingSpheres(), buoyancyEnergy::buoyancyEnergy(), buoyancyForce::buoyancyForce(), Foam::calcElementMasks(), polyDualMesh::calcFeatures(), add::calcFieldType(), subtract::calcFieldType(), triSurfaceSearch::calcInside(), cutCell::calcIsoFacePointsFromEdges(), cellMatcher::calcLocalFaces(), snappySnapDriver::calcNearestSurface(), primitiveMesh::calcPointOrder(), createShellMesh::calcPointRegions(), DICPreconditioner::calcReciprocalD(), DILUPreconditioner::calcReciprocalD(), distributedDILUPreconditioner::calcReciprocalD(), snappySnapDriver::calcSnapDistance(), cutFaceAdvect::calcSubFace(), cutFace::calcSubFace(), cutFaceAdvect::calcSubFace(), cutFaceIso::calcSubFace(), cutFace::calcSubFace(), cutFaceAdvect::calcSubFace(), cutFacePLIC::calcSubFace(), coupledFaPatch::calcTransformTensors(), coupledPolyPatch::calcTransformTensors(), meshRefinement::calculateEdgeWeights(), GAMGAgglomeration::calculateRegionMaster(), deltaBoundary::cellCenters_d(), repatchPolyTopoChanger::changeAnchorPoint(), polyTopoChange::changeMesh(), topoSetSource::check(), primitiveMesh::checkCellsZipUp(), primitiveMesh::checkClosedBoundary(), meshRefinement::checkData(), sampledSet::checkDimensions(), polyMeshGeometry::checkFaceFlatness(), Foam::checkFaceSizeMatch(), Foam::checkFaceSizeMatch(), polyMeshGeometry::checkFaceTwist(), primitiveMeshGeometry::checkFaceTwist(), hexRef8::checkMesh(), PatchTools::checkOrientation(), polyMeshGeometry::checkTriangleTwist(), noiseModel::checkUniformTimeStep(), lduPrimitiveMesh::checkUpperTriangular(), ensightFaces::classify(), cellShape::collapsedFaces(), triSurfaceTools::collapseEdges(), triSurfaceTools::collapseEdges(), extendedCellToFaceStencil::collectData(), extendedFaceToCellStencil::collectData(), collector::collector(), mappedPatchBase::collectSamples(), CollisionRecordList< PairType, WallType >::CollisionRecordList(), UPstream::commsStruct::commsStruct(), face::compare(), componentDisplacementMotionSolver::componentDisplacementMotionSolver(), processorLduInterface::compressedReceive(), processorLduInterface::compressedSend(), fromFile::computeControlPoints(), NURBS3DVolume::computeControlPointSensitivities(), NURBS3DVolume::computeControlPointSensitivities(), NURBS3DVolume::computeParametricCoordinates(), MappedFile< Type >::constant(), molecule::constantProperties::constantProperties(), mapDistributeBase::constructMapSizes(), reconstructedDistanceFunction::constructRDF(), polySurface::copySurface(), surfMesh::copySurface(), inversePointDistanceDiffusivity::correct(), patchInjection::correct(), Foam::countConnectivity(), Foam::countConnectivity(), meshRefinement::countEdgeFaces(), removePoints::countPointUsage(), createShellMesh::createShellMesh(), displacementInterpolationMotionSolver::curPoints(), triSurfaceTools::curvatures(), cuttingSurfaceBase::cut(), geomCellLooper::cut(), extendedEdgeMesh::cut(), hexCellLooper::cut(), cutFaceAdvect::cutPoints(), DAC< CompType, ThermoType >::DAC(), noDecomp::decompose(), randomDecomp::decompose(), metisLikeDecomp::decompose(), simpleGeomDecomp::decompose(), faMeshDecomposition::decomposeMesh(), diagonalPreconditioner::diagonalPreconditioner(), DiagonalPreconditioner< Type, DType, LUType >::DiagonalPreconditioner(), directionalPressureGradientExplicitSource::directionalPressureGradientExplicitSource(), refinementHistory::distribute(), pointSet::distribute(), cellSet::distribute(), faceSet::distribute(), mapDistributeBase::distribute(), mapDistributeBase::distribute(), NURBS3DVolume::dndbBasedSensitivities(), Bezier::dndbBasedSensitivities(), Bezier::dndbBasedSensitivities(), snappyLayerDriver::doLayers(), meshRefinement::doSplitFaces(), DRG< CompType, ThermoType >::DRG(), DRGEP< CompType, ThermoType >::DRGEP(), Foam::duplicateOrder(), Bezier::dxdbFace(), Bezier::dxdbFace(), PatchTools::edgeOwner(), edgeSurface::edgeSurface(), directionInfo::edgeToFaceIndex(), primitiveEntry::endLineNumber(), energyTransport::energyTransport(), directionInfo::enterDomain(), equationInitialResidualCondition::equationInitialResidualCondition(), edgeInterpolationScheme< Type >::euclidianInterpolate(), FilterField::evaluate(), STLAsciiParseManual::execute(), extendedEdgeMesh::extendedEdgeMesh(), extendedUpwindCellToFaceStencil::extendedUpwindCellToFaceStencil(), extendedUpwindCellToFaceStencil::extendedUpwindCellToFaceStencil(), externalWallHeatFluxTemperatureFvPatchScalarField::externalWallHeatFluxTemperatureFvPatchScalarField(), Foam::extractData(), faceCells::faceCells(), FaceCellWave< Type, TrackingData >::FaceCellWave(), FaceCellWave< Type, TrackingData >::FaceCellWave(), FaceCellWave< Type, TrackingData >::FaceCellWave(), primitiveMesh::faceEdges(), primitiveMesh::faceEdges(), primitiveMeshTools::faceFlatness(), LduMatrix< Type, DType, LUType >::faceH(), lduMatrix::faceH(), hexRef8::faceLevel(), mappedPatchBase::facePoint(), FacePostProcessing< CloudType >::FacePostProcessing(), prismMatcher::faceSizeMatch(), tetWedgeMatcher::faceSizeMatch(), wedgeMatcher::faceSizeMatch(), polyMeshTetDecomposition::faceTetIndices(), PrimitivePatchInterpolation< Patch >::faceToEdgeInterpolate(), tetIndices::faceTriIs(), faMesh::faMesh(), faMesh::faMesh(), faMeshMapper::faMeshMapper(), FDICPreconditioner::FDICPreconditioner(), Foam::edgeMeshTools::featureProximity(), FieldActivatedInjection< CloudType >::FieldActivatedInjection(), fieldsExpression::fieldsExpression(), refinementSurfaces::findAllIntersections(), refinementSurfaces::findAllIntersections(), searchableSurfacesQueries::findAllIntersections(), searchableSurfacesQueries::findAnyIntersection(), shellSurfaces::findDirectionalLevel(), Foam::findEtcEntry(), shellSurfaces::findHigherGapLevel(), refinementSurfaces::findHigherIntersection(), inverseDistance::findHoles(), refinementSurfaces::findInside(), shellSurfaces::findLevel(), searchableBox::findLine(), searchableCone::findLine(), searchableCylinder::findLine(), searchableDisk::findLine(), searchablePlane::findLine(), searchablePlate::findLine(), searchableRotatedBox::findLine(), searchableSphere::findLine(), searchableSurfaceCollection::findLine(), triSurfaceMesh::findLine(), triSurfaceSearch::findLine(), searchableBox::findLineAll(), searchableCone::findLineAll(), searchableCylinder::findLineAll(), searchableDisk::findLineAll(), searchablePlane::findLineAll(), searchablePlate::findLineAll(), searchableRotatedBox::findLineAll(), searchableSphere::findLineAll(), searchableSurfaceCollection::findLineAll(), searchableSurfaceWithGaps::findLineAll(), triSurfaceMesh::findLineAll(), distributedTriSurfaceMesh::findLineAll(), triSurfaceSearch::findLineAll(), searchableBox::findLineAny(), searchableCone::findLineAny(), searchableCylinder::findLineAny(), searchableRotatedBox::findLineAny(), searchableSphere::findLineAny(), triSurfaceMesh::findLineAny(), triSurfaceSearch::findLineAny(), mappedPatchBase::findLocalSamples(), triSurfaceMesh::findNearest(), searchableBox::findNearest(), searchableCone::findNearest(), searchableCylinder::findNearest(), searchableDisk::findNearest(), searchableExtrudedCircle::findNearest(), searchablePlane::findNearest(), searchablePlate::findNearest(), searchableRotatedBox::findNearest(), searchableSphere::findNearest(), triSurfaceMesh::findNearest(), distributedTriSurfaceMesh::findNearest(), triSurfaceRegionSearch::findNearest(), distributedTriSurfaceMesh::findNearest(), triSurfaceSearch::findNearest(), searchableSurfacesQueries::findNearest(), searchableSurfacesQueries::findNearest(), searchableSurfacesQueries::findNearest(), primitiveMesh::findNearestCell(), refinementFeatures::findNearestEdge(), refinementSurfaces::findNearestIntersection(), refinementSurfaces::findNearestIntersection(), refinementSurfaces::findNearestIntersection(), refinementSurfaces::findNearestIntersection(), searchableSurfacesQueries::findNearestIntersection(), refinementFeatures::findNearestPoint(), refinementFeatures::findNearestRegionEdge(), searchableExtrudedCircle::findParametricNearest(), NURBS3DVolume::findPointsInBox(), meshRefinement::findRegions(), mappedPatchBase::findSamples(), polyMeshAdder::findSharedPoints(), polyMeshTetDecomposition::findTet(), faMeshTools::flattenEdgeField(), mapDistributeBase::flipAndCombine(), forceList::forceList(), forceList::forceList(), coupledFaPatch::forwardT(), FreeStream< CloudType >::FreeStream(), PatchTools::gatherAndMerge(), Foam::gAverage(), GeometricBoundaryField< Type, PatchField, GeoMesh >::GeometricBoundaryField(), coupledPolyPatch::getAnchorPoints(), zoneDistribute::getDatafromOtherProc(), GenericPatchGeoFieldsWriter< PatchType >::getFaceField(), zoneDistribute::getFields(), meshRefinement::getMasterEdges(), meshRefinement::getMasterPoints(), cellDistFuncs::getPointNeighbours(), Foam::ensightOutput::Detail::getPolysFacePoints(), Foam::ensightOutput::Detail::getPolysNFaces(), Foam::ensightOutput::Detail::getPolysNPointsPerFace(), coupledPolyPatch::getRotation(), distributedTriSurfaceMesh::getVolumeType(), cellCellStencil::globalCellCells(), cylindrical::globalToLocal(), triSurfaceTools::greenRefine(), lduMatrix::H(), faMesh::haloFaceCentres(), faMesh::haloFaceNormals(), mapPolyMesh::hasMotionPoints(), heheuPsiThermo< BasicPsiThermo, MixtureType >::heu(), heheuPsiThermo< BasicPsiThermo, MixtureType >::heu(), hexRef8::hexRef8(), hexRef8::hexRef8(), hexRef8::hexRef8(), wallBoundedParticle::hitProcessorPatch(), if(), if(), if(), if(), indexedOctree< Type >::indexedOctree(), faBoundaryMesh::indices(), polyBoundaryMesh::indices(), ZoneMesh< ZoneType, MeshType >::indices(), injectionModelList::info(), transferModelList::info(), waveModel::initialiseGeometry(), objectivePtLosses::initialize(), objectiveUniformityPatch::initialize(), LduMatrix< Type, DType, LUType >::initMatrixInterfaces(), processorPolyPatch::initOrder(), InjectedParticleDistributionInjection< CloudType >::InjectedParticleDistributionInjection(), InjectedParticleInjection< CloudType >::InjectedParticleInjection(), Foam::inplaceSubset(), Foam::inplaceUniqueSort(), NURBSbasis::insertKnot(), polynomialFunction::integrate(), linearInterpolationWeights::integrationWeights(), edgeInterpolationScheme< Type >::interpolate(), fvMeshSubset::interpolate(), fvMeshSubset::interpolate(), interpolationCellPointFace< Type >::interpolate(), cellCellStencil::interpolate(), meshToMesh0::interpolateField(), cellVolumeWeight::interpolatePatchTypes(), isoSurfaceTopo::interpolateTemplate(), AMIInterpolation::interpolateToTarget(), intersectedSurface::intersectedSurface(), NURBS3DCurve::invert(), NURBS3DSurface::invertU(), NURBS3DSurface::invertUV(), NURBS3DSurface::invertV(), coordinateSystem::invTransformPointImpl(), prismMatcher::isA(), tetWedgeMatcher::isA(), wedgeMatcher::isA(), isoSurfaceTopo::isoSurfaceTopo(), liquidMixtureProperties::kappa(), turbulentTemperatureCoupledBaffleMixedFvPatchScalarField::kappa(), cell::labels(), lagrangianFieldDecomposer::lagrangianFieldDecomposer(), lduPrimitiveMesh::lduPrimitiveMesh(), lduPrimitiveMesh::lduPrimitiveMesh(), lduPrimitiveMesh::lduPrimitiveMesh(), NURBS3DCurve::length(), LiquidEvapFuchsKnudsen< CloudType >::LiquidEvapFuchsKnudsen(), LiquidEvaporation< CloudType >::LiquidEvaporation(), LiquidEvaporationBoil< CloudType >::LiquidEvaporationBoil(), liquidMixtureProperties::liquidMixtureProperties(), cellCuts::loopPoints(), lumpedPointState::lumpedPointState(), cellModel::mag(), highAspectRatioFvGeometryScheme::makeAverageCentres(), primitiveMeshTools::makeFaceCentresAndAreas(), polyTopoChange::makeMesh(), voxelMeshSearch::makeMesh(), Field< Type >::map(), fvMeshAdder::MapDimField(), mappedPatchFieldBase< Type >::mappedField(), mappedPatchFieldBase< scalar >::mappedPatchFieldBase(), meshToMesh::mapSrcToTgt(), meshToMesh::mapSrcToTgt(), meshToMesh::mapTgtToSrc(), meshToMesh::mapTgtToSrc(), PatchTools::markZones(), momentOfInertia::massPropertiesPatch(), momentOfInertia::massPropertiesShell(), momentOfInertia::massPropertiesSolid(), degenerateMatcher::match(), processorPolyPatch::matchFace(), noiseFFT::meanPf(), meanVelocityForce::meanVelocityForce(), cellToCellStencil::merge(), cellToFaceStencil::merge(), globalMeshData::mergePoints(), triSurfaceTools::mergePoints(), fileOperation::mergeTimes(), blockMesh::mesh(), PrimitivePatch< FaceList, PointField >::meshEdges(), cellShape::meshFaces(), edgeIntersections::minEdgeLength(), fieldSmoother::minSmoothField(), slidingInterface::modifyMotionPoints(), wallBoundedStreamLineParticle::move(), regionModel1D::moveMesh(), solidBodyFvGeometryScheme::movePoints(), polyMesh::movePoints(), polyTopoChange::movePoints(), multiBandAbsorption::multiBandAbsorption(), multiBandAbsorptionEmission::multiBandAbsorptionEmission(), multiBandTransmissivity::multiBandTransmissivity(), multiBandZoneAbsorptionEmission::multiBandZoneAbsorptionEmission(), multiDirRefinement::multiDirRefinement(), multiDirRefinement::multiDirRefinement(), FaceCellWaveBase::nChangedCells(), PatchEdgeFaceWaveBase::nChangedEdges(), PointEdgeWaveBase::nChangedEdges(), FaceCellWaveBase::nChangedFaces(), PatchEdgeFaceWaveBase::nChangedFaces(), PointEdgeWaveBase::nChangedPoints(), extendedEdgeMesh::nearestFeatureEdge(), face::nearestPointClassify(), surfaceFeatures::nearestSamples(), surfaceFeatures::nearestSurfEdge(), LduMatrix< Type, DType, LUType >::negSumDiag(), lduMatrix::negSumDiag(), polyBoundaryMesh::neighbourEdges(), fvMeshTools::newMesh(), potential::nIds(), mapDistributeBase::nMaps(), cellCuts::nonAnchorPoints(), AMIInterpolation::normaliseWeights(), refinementSurfaces::nRegions(), NURBS3DSurface::NURBS3DSurface(), NURBS3DSurface::NURBS3DSurface(), NURBS3DSurface::NURBS3DSurface(), NURBS3DSurface::NURBS3DSurface(), objectiveFlowRatePartition::objectiveFlowRatePartition(), noiseFFT::octaveBandInfo(), coordinateSystem::oneToManyImpl(), coordinateSystem::oneToOneImpl(), projectVertex::operator point(), Foam::operator&(), polynomialFunction::operator+=(), polynomialFunction::operator-=(), Foam::operator<<(), MatrixBlock< MatrixType >::operator=(), List< CloudFunctionObject< CloudType > * >::operator=(), Foam::operator==(), Foam::operator==(), Foam::operator==(), Foam::operator>>(), cell::opposingFace(), cell::opposingFaceLabel(), processorPolyPatch::order(), updateMethod::outerProd(), treeDataFace::overlaps(), PackedList< Width >::PackedList(), pairPatchAgglomeration::pairPatchAgglomeration(), pairPatchAgglomeration::pairPatchAgglomeration(), coupledFaPatch::parallel(), argList::parse(), ParticleCollector< CloudType >::ParticleCollector(), NURBS3DVolume::patchDxDbFace(), PatchEdgeFaceWave< PrimitivePatchType, Type, TrackingData >::PatchEdgeFaceWave(), pointFieldDecomposer::patchFieldDecomposer::patchFieldDecomposer(), sampledPatch::patchIDs(), patchInjection::patchInjectedMassTotals(), patchInjection::patchInjection(), polyBoundaryMesh::patchSizes(), SprayCloud< CloudType >::penetration(), noiseModel::Pf(), PFA< CompType, ThermoType >::PFA(), pointCells::pointCells(), PointEdgeWave< Type, TrackingData >::PointEdgeWave(), polyMesh::pointInCell(), pointMVCWeight::pointMVCWeight(), cell::points(), vtuAdaptor::points(), points0MotionSolver::points0MotionSolver(), points0MotionSolver::points0MotionSolver(), PrimitivePatchInterpolation< Patch >::pointToFaceInterpolate(), polyAddFace::polyAddFace(), polyMesh::polyMesh(), polyMesh::polyMesh(), polyMesh::polyMesh(), polyMesh::polyMesh(), Foam::polyMeshZipUpCells(), polyModifyFace::polyModifyFace(), projectCurveEdge::position(), projectEdge::position(), PDRblock::gridControl::prepend(), filmTurbulenceModel::primaryRegionFriction(), foamToVtkReportFields::print(), dynamicIndexedOctree< Type >::print(), indexedOctree< Type >::print(), vtkUnstructuredReader::printFieldStats(), mapDistribute::printLayout(), fvMeshDistribute::printMeshInfo(), pointNoise::processData(), genericPatchFieldBase::processEntry(), profileModelList::profileModelList(), projectCurveEdge::projectCurveEdge(), projectEdge::projectEdge(), projectVertex::projectVertex(), pyrolysisModelCollection::pyrolysisModelCollection(), reactionsSensitivityAnalysis< chemistryType >::reactionsSensitivityAnalysis(), areaWrite::read(), STLsurfaceFormat< Face >::read(), VTKsurfaceFormat< Face >::read(), boundaryMesh::read(), waveModel::readDict(), triSurfaceLoader::readDir(), ReactingParcel< ParcelType >::readFields(), ensightSurfaceReader::readGeometry(), ReactingParcel< ParcelType >::readObjects(), faMeshTools::readProcAddressing(), fvMeshTools::readProcAddressing(), surfaceNoise::readSurfaceData(), boundaryMesh::readTriSurface(), valuePointPatchField< vector >::readValueEntry(), mapDistributeBase::receive(), mapDistributeBase::receive(), InteractionLists< ParticleType >::receiveReferredData(), processorMeshes::reconstructPoints(), triSurfaceTools::redGreenRefine(), referredWallFace::referredWallFace(), refinementHistory::refinementHistory(), refinementHistory::refinementHistory(), refinementHistory::refinementHistory(), refinementHistory::refinementHistory(), refinementHistory::refinementHistory(), refinementHistory::refinementHistory(), refinementParameters::refinementParameters(), regionModelFunctionObjectList::regionModelFunctionObjectList(), hashedWordList::rehash(), RemoveParcels< CloudType >::RemoveParcels(), SloanRenumber::renumber(), springRenumber::renumberImpl(), AMIWeights::reportPatch(), fvMeshSubset::reset(), vtuSizing::reset(), option::resetApplied(), fieldSelection::resetFieldFilters(), vtuSizing::resetShapes(), mappedPatchFieldBase< Type >::retrieveField(), coupledFaPatch::reverseT(), Foam::rewritePatchLabels(), rigidBodyModelState::rigidBodyModelState(), coordinateSystem::rotationsImpl(), face::sameVertices(), sampledCuttingPlane::sampledCuttingPlane(), sampledIsoSurface::sampledIsoSurface(), sampledFaceZone::sampleOnFaces(), sampledMeshedSurface::sampleOnFaces(), sampledPatch::sampleOnFaces(), sampledSurface::sampleOnFaces(), sampledMeshedSurface::sampleOnPoints(), sampledSurface::sampleOnPoints(), cyclicACMIPolyPatch::scalePatchFaceAreas(), timeSelector::select(), extendedEdgeMesh::select(), timeSelector::selected(), mapDistributeBase::send(), mapDistributeBase::send(), InteractionLists< ParticleType >::sendReferredData(), coupledFaPatch::separated(), coupledPolyPatch::separated(), coupledFaPatch::separation(), Foam::BitOps::set(), Foam::BitOps::set(), pointPatchField< Type >::setInInternalField(), fvGeometryScheme::setMeshPhi(), removePoints::setRefinement(), meshCutter::setRefinement(), tetDecomposer::setRefinement(), addPatchCellLayer::setRefinement(), perfectInterface::setRefinement(), meshCutAndRemove::setRefinement(), hexRef8::setRefinement(), faceCollapser::setRefinement(), removeFaces::setRefinement(), combineFaces::setRefinement(), edgeCollapser::setRefinement(), duplicatePoints::setRefinement(), boundaryCutter::setRefinement(), createShellMesh::setRefinement(), fieldsExpression::setResultName(), combineFaces::setUnrefinement(), UnsortedMeshedSurface< Face >::setZones(), UnsortedMeshedSurface< Face >::setZones(), liquidMixtureProperties::sigma(), searchableSurfacesQueries::signedDistance(), singleCellFvMesh::agglomPatchFieldMapper::size(), lumpedPointController::size(), DirectFieldMapper< FieldMapperType >::size(), GAMGInterface::size(), procLduMatrix::size(), fvFieldDecomposer::patchFieldDecomposer::size(), fvFieldDecomposer::processorVolPatchFieldDecomposer::size(), fvFieldDecomposer::processorSurfacePatchFieldDecomposer::size(), pointFieldDecomposer::patchFieldDecomposer::size(), faFieldDecomposer::patchFieldDecomposer::size(), faFieldDecomposer::processorAreaPatchFieldDecomposer::size(), faFieldDecomposer::processorEdgePatchFieldDecomposer::size(), meshToMesh0::patchFieldInterpolator::size(), ensightPart::size(), collector::size(), treeDataFace::size(), treeDataCell::size(), treeDataEdge::size(), treeDataPoint::size(), BiIndirectList< T >::size(), mergedSurf::size(), fieldSmoother::smoothLambdaMuDisplacement(), fieldSmoother::smoothNormals(), fieldSmoother::smoothPatchNormals(), solidMixtureProperties::solidMixtureProperties(), rigidBodyMeshMotion::solve(), sixDoFRigidBodyMotionSolver::solve(), PatchTools::sortedEdgeFaces(), UPtrList< T >::sortOrder(), extendedEdgeMesh::sortPointsAndEdges(), primitiveEntry::startLineNumber(), mappedPatchFieldBase< Type >::storeField(), fvMesh::storeOldVol(), mapDistributeBase::subMapSizes(), mappedPatchBase::subRegistry(), hexRef8::subset(), refinementHistory::subset(), LduMatrix< Type, DType, LUType >::sumDiag(), lduMatrix::sumDiag(), LduMatrix< Type, DType, LUType >::sumMagOffDiag(), lduMatrix::sumMagOffDiag(), surfaceFeatures::surfaceFeatures(), surfaceIntersection::surfaceIntersection(), surfaceIntersection::surfaceIntersection(), surfaceIntersection::surfaceIntersection(), surfaceZonesInfo::surfaceZonesInfo(), surfZoneIOList::surfZoneIOList(), face::symmhash_code(), syncTools::syncEdgeList(), syncTools::syncEdgeList(), syncTools::syncEdgeMap(), syncTools::syncPointList(), weightedPosition::syncPoints(), ParticleStressModel::tau(), heThermo< BasicThermo, MixtureType >::THE(), heThermo< BasicThermo, MixtureType >::THE(), cutFaceAdvect::timeIntegratedFaceFlux(), cutFaceAdvect::timeIntegratedFaceFlux(), pointToPointPlanarInterpolation::timeNames(), Foam::BitOps::toc(), CV2D::toPoint2D(), wallBoundedParticle::trackToEdge(), rigidBodyMotion::transformPoints(), MeshedSurface< Face >::triangulate(), triSurfaceTools::triangulateFaceCentre(), tetIndices::triIs(), UIPstream::UIPstream(), fileOperation::uniformFile(), hashedWordList::uniq(), Foam::uniqueOrder(), oversetFvMeshBase::updateAddressing(), directionInfo::updateCell(), primitiveMeshTools::updateCellCentresAndVols(), uniformInterpolatedDisplacementPointPatchVectorField::updateCoeffs(), externalWallHeatFluxTemperatureFvPatchScalarField::updateCoeffs(), humidityTemperatureCoupledMixedFvPatchScalarField::updateCoeffs(), thermalBaffle1DFvPatchScalarField< solidType >::updateCoeffs(), turbulentTemperatureRadCoupledMixedFvPatchScalarField::updateCoeffs(), patchEdgeFaceRegions::updateFace(), processorGAMGInterfaceField::updateInterfaceMatrix(), meshRefinement::updateIntersections(), topoBitSet::updateLabels(), topoBoolSet::updateLabels(), topoSet::updateLabels(), LduMatrix< Type, DType, LUType >::updateMatrixInterfaces(), lduMatrix::updateMatrixInterfaces(), boundaryCutter::updateMesh(), hexRef8Data::updateMesh(), addPatchCellLayer::updateMesh(), hexRef8::updateMesh(), polyMesh::updateMesh(), processorPolyPatch::updateMesh(), cellZoneSet::updateSet(), faceZoneSet::updateSet(), pointZoneSet::updateSet(), thermoSingleLayer::updateSurfaceTemperatures(), kinematicSingleLayer::updateSurfaceVelocities(), dynamicRefineFvMesh::updateTopology(), Foam::HashSetOps::used(), lumpedPointState::valid(), triSurfaceTools::validTri(), polynomialFunction::value(), linearInterpolationWeights::valueWeights(), splineInterpolationWeights::valueWeights(), viscousDissipation::viscousDissipation(), meshReader::warnDuplicates(), meshRefinement::weightedSum(), SQP::write(), foamWriter::write(), rawWriter::write(), GTSsurfaceFormat< Face >::write(), ABAQUSsurfaceFormat< Face >::write(), AC3DsurfaceFormat< Face >::write(), NASsurfaceFormat< Face >::write(), OBJsurfaceFormat< Face >::write(), OFFsurfaceFormat< Face >::write(), SMESHsurfaceFormat< Face >::write(), STARCDsurfaceFormat< Face >::write(), TRIsurfaceFormat< Face >::write(), X3DsurfaceFormat< Face >::write(), VTKsurfaceFormat< Face >::write(), VTPsurfaceFormat< Face >::write(), TRIsurfaceFormat< Face >::write(), NURBS3DCurve::write(), internalWriter::write(), patchWriter::write(), sensitivityBezier::write(), sensitivityBezierFI::write(), sensitivityVolBSplines::write(), sensitivityVolBSplinesFI::write(), NURBS3DCurve::write(), FLMAsurfaceFormat< Face >::write(), turbulentTemperatureCoupledBaffleMixedFvPatchScalarField::write(), turbulentTemperatureRadCoupledMixedFvPatchScalarField::write(), STLsurfaceFormat< Face >::writeAscii(), STLsurfaceFormat< Face >::writeBinary(), VTKsurfaceFormatCore::writeCellData(), VTPsurfaceFormatCore::writeCellData(), triSurfaceTools::writeCloseness(), externalCoupledTemperatureMixedFvPatchScalarField::writeData(), surfZoneIOList::writeData(), ReactingHeterogeneousParcel< ParcelType >::writeFields(), ReactingParcel< ParcelType >::writeFields(), surfaceFieldWriter::writeGeometry(), Foam::ensightOutput::Detail::writeLabelListList(), patchMeshWriter::writeNeighIDs(), Foam::meshTools::writeOBJ(), regIOobject::writeObject(), oversetFvMeshBase::writeObject(), ReactingParcel< ParcelType >::writeObjects(), patchMeshWriter::writePatchIDs(), patchMeshWriter::writePolys(), Foam::ensightOutput::writePolysPoints(), Foam::ensightOutput::writePolysPoints(), searchableSurfaces::writeStats(), MeshedSurface< Face >::writeStats(), abaqusWriter::writeTemplate(), nastranWriter::writeTemplate(), lumpedPointState::writeVTP(), NURBS3DCurve::writeWParses(), NURBS3DCurve::writeWParses(), Foam::writeZone(), liquidMixtureProperties::Y(), Foam::zip(), Foam::zip(), Foam::zip(), Foam::zip(), Foam::zip(), Foam::zip(), refinementParameters::zonedLocations(), refinementParameters::zonePoints(), and meshRefinement::zonify().
writeEntry() [1/4]
template<class T > void writeEntry (Ostream & os) const protected
Definition at line 31 of file UListIO.C.
References IOstreamOption::ASCII, token::BEGIN_LIST, token::END_LIST, token::compound::isCompound(), os(), UPtrList< T >::size(), and token::SPACE.
Referenced by faPatch::write(), turbulentTemperatureCoupledBaffleMixedFvPatchScalarField::write(), turbulentTemperatureRadCoupledMixedFvPatchScalarField::write(), and Field< Type >::writeEntry().
validateRange()
template<class T > Foam::labelRange validateRange (const labelRange & requestedRange) const protected
Definition at line 33 of file UList.C.
References range, and UPtrList< T >::size().
operator=() [1/3]
template<class T > UList< T > & operator= (const UList< T > &) protected delete
Referenced by DynamicList< T, SizeMin >::operator=(), List< T >::operator=(), SubList< T >::operator=(), DynamicField< T, SizeMin >::operator=(), DynamicList< T, SizeMin >::operator=(), List< T >::operator=(), SubList< T >::operator=(), SortableList< T >::operator=(), and DynamicField< T, SizeMin >::operator=().
null()
template<class T > const Foam::UList< T > & null () inline static
Definition at line 45 of file UListI.H.
fcIndex()
template<class T > Foam::label fcIndex (const label i) const inline noexcept
Definition at line 52 of file UListI.H.
Referenced by holeToFace::calcClosure(), triSurfaceTools::calcInterpolationWeights(), pointMVCWeight::calcWeights(), polyMeshGeometry::checkEdgeLength(), polyMeshGeometry::checkTriangleTwist(), wallBoundedParticle::crossDiagonalEdge(), meshRefinement::doSplitFaces(), primitiveMesh::edgeFaces(), primitiveMesh::faceEdges(), mappedPatchBase::facePoint(), tetIndices::faceTriIs(), isoSurfacePoint::generateFaceTriPoints(), edgeFaceCirculator::getMinIndex(), treeDataFace::getVolumeType(), face::ray(), tetDecomposer::setRefinement(), addPatchCellLayer::setRefinement(), faceCollapser::setRefinement(), createShellMesh::setRefinement(), face::symmhash_code(), syncTools::syncEdgeMap(), wallBoundedParticle::trackToEdge(), MeshedSurface< Face >::triangulate(), triSurfaceTools::triangulateFaceCentre(), tetIndices::triIs(), patchEdgeFaceRegions::updateEdge(), and patchEdgeFaceRegions::updateFace().
rcIndex()
template<class T > Foam::label rcIndex (const label i) const inline noexcept
Definition at line 59 of file UListI.H.
Referenced by pointMVCWeight::calcWeights(), wallBoundedParticle::crossDiagonalEdge(), wallBoundedParticle::crossEdgeConnectedFace(), primitiveMesh::edgeFaces(), edgeFaceCirculator::getMinIndex(), treeDataFace::getVolumeType(), tetDecomposer::setRefinement(), faceCollapser::setRefinement(), createShellMesh::setRefinement(), face::symmhash_code(), and wallBoundedParticle::trackToEdge().
fcValue() [1/2]
template<class T > const T & fcValue (const label i) const inline
Definition at line 66 of file UListI.H.
Referenced by polyMeshTetDecomposition::adjustTetBasePtIs(), face::nextLabel(), and face::symmhash_code().
fcValue() [2/2]
template<class T > T & fcValue (const label i) inline
Definition at line 73 of file UListI.H.
rcValue() [1/2]
template<class T > const T & rcValue (const label i) const inline
Definition at line 80 of file UListI.H.
Referenced by polyMeshTetDecomposition::adjustTetBasePtIs(), face::prevLabel(), and face::symmhash_code().
rcValue() [2/2]
template<class T > T & rcValue (const label i) inline
Definition at line 87 of file UListI.H.
cdata()
template<class T > const T * cdata () const inline noexcept
Definition at line 222 of file UListI.H.
Referenced by processorLduInterface::compressedSend(), face::hash_code(), and processorLduInterface::send().
data()
template<class T > T * data () inline noexcept
Definition at line 229 of file UListI.H.
Referenced by argList::argList(), processorLduInterface::compressedReceive(), particle< Type >::readData(), processorLduInterface::receive(), and processorLduInterface::send().
cdata_bytes()
template<class T > const char * cdata_bytes () const inline noexcept
Definition at line 236 of file UListI.H.
data_bytes()
template<class T > char * data_bytes () inline noexcept
Definition at line 243 of file UListI.H.
Referenced by processorLduInterface::receive().
front() [1/2]
template<class T > T & front () inline
Definition at line 194 of file UListI.H.
Referenced by boxToCell::boxToCell(), boxToFace::boxToFace(), boxToPoint::boxToPoint(), cellToCell::cellToCell(), cellToFace::cellToFace(), cellToFaceZone::cellToFaceZone(), cellToPoint::cellToPoint(), processorColour::colour(), faceToCell::faceToCell(), faceToFace::faceToFace(), faceToPoint::faceToPoint(), faceZoneToCell::faceZoneToCell(), UList< T >::first(), UList< T >::first(), holeToFace::holeToFace(), patchToCell::patchToCell(), patchToFace::patchToFace(), pointToCell::pointToCell(), pointToFace::pointToFace(), pointToPoint::pointToPoint(), PDRblock::location::reset(), zoneToCell::zoneToCell(), zoneToFace::zoneToFace(), and zoneToPoint::zoneToPoint().
front() [2/2]
template<class T > const T & front () const inline
Definition at line 201 of file UListI.H.
back() [1/2]
template<class T > T & back () inline
Definition at line 208 of file UListI.H.
Referenced by manualGAMGProcAgglomeration::agglomerate(), globalIndex::gather(), globalIndex::gather(), UList< T >::last(), UList< T >::last(), and PDRblock::location::reset().
back() [2/2]
template<class T > const T & back () const inline
Definition at line 215 of file UListI.H.
size_bytes()
template<class T > std::streamsize size_bytes () const inline noexcept
Definition at line 250 of file UListI.H.
Referenced by face::hash_code().
byteSize()
template<class T > std::streamsize byteSize () const
Definition at line 191 of file UList.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Referenced by processorLduInterface::receive().
checkStart()
template<class T > void checkStart (const label start) const inline
Definition at line 94 of file UListI.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
checkSize()
template<class T > void checkSize (const label size) const inline
Definition at line 108 of file UListI.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
checkRange()
template<class T > void checkRange (const label start, const label len) const inline
Definition at line 121 of file UListI.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
checkIndex()
template<class T > void checkIndex (const label i) const inline
Definition at line 151 of file UListI.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
uniform()
template<class T > bool uniform () const inline
Definition at line 170 of file UListI.H.
find()
template<class T > Foam::label find (const T & val, label pos = 0) const
Definition at line 204 of file UList.C.
References List_CONST_ACCESS, Foam::pos(), and T.
Referenced by multiBandZoneAbsorptionEmission::aCont(), greyMeanAbsorptionEmission::aCont(), wideBandAbsorptionEmission::aCont(), manualGAMGProcAgglomeration::agglomerate(), createShellMesh::calcPointRegions(), wallBoundedParticle::crossEdgeConnectedFace(), primitiveMesh::edgeFaces(), directionInfo::edgeToFaceIndex(), Foam::filteredName(), for(), edgeFaceCirculator::getMinIndex(), surfaceNoise::initialise(), processorFaPatch::initUpdateMesh(), processorPolyPatch::initUpdateMesh(), pureZoneMixture< ThermoType >::pureZoneMixture(), fileName::relative(), duplicatePoints::setRefinement(), boundaryCutter::setRefinement(), createShellMesh::setRefinement(), processorFaPatch::updateMesh(), and face::which().
rfind()
template<class T > Foam::label rfind (const T & val, label pos = -1) const
Definition at line 228 of file UList.C.
References List_CONST_ACCESS, Foam::pos(), and T.
Referenced by topoBoolSet::check().
contains()
template<class T > bool contains (const T & val, label pos = 0) const inline
Definition at line 257 of file UListI.H.
References Foam::pos().
Referenced by refinementFeatures::checkSizes(), face::connected(), UList< T >::found(), and HashSet< labelPairPair >::operator-=().
moveFirst()
template<class T > void moveFirst (const label i)
Definition at line 49 of file UList.C.
References Foam::Swap().
moveLast()
template<class T > void moveLast (const label i)
Definition at line 61 of file UList.C.
References Foam::Swap().
swapFirst()
template<class T > void swapFirst (const label i)
Definition at line 73 of file UList.C.
References Foam::Swap().
swapLast()
template<class T > void swapLast (const label i)
Definition at line 85 of file UList.C.
References Foam::Swap().
shallowCopy()
template<class T > void shallowCopy (const UList< T > & list) inline
Definition at line 264 of file UListI.H.
Referenced by SlicedDimensionedField< Type, GeoMesh >::SlicedDimensionedField(), slicedFaePatchField< Type >::slicedFaePatchField(), slicedFaePatchField< Type >::slicedFaePatchField(), slicedFaePatchField< Type >::slicedFaePatchField(), slicedFaPatchField< Type >::slicedFaPatchField(), slicedFaPatchField< Type >::slicedFaPatchField(), slicedFaPatchField< Type >::slicedFaPatchField(), slicedFvPatchField< Type >::slicedFvPatchField(), slicedFvPatchField< Type >::slicedFvPatchField(), slicedFvPatchField< Type >::slicedFvPatchField(), slicedFvsPatchField< Type >::slicedFvsPatchField(), slicedFvsPatchField< Type >::slicedFvsPatchField(), slicedFvsPatchField< Type >::slicedFvsPatchField(), SlicedGeometricField< Type, PatchField, SlicedPatchField, GeoMesh >::SlicedGeometricField(), SlicedGeometricField< Type, PatchField, SlicedPatchField, GeoMesh >::SlicedGeometricField(), SlicedGeometricField< Type, PatchField, SlicedPatchField, GeoMesh >::SlicedGeometricField(), SlicedGeometricField< Type, PatchField, SlicedPatchField, GeoMesh >::SlicedGeometricField(), surfMesh::updateRefs(), SlicedDimensionedField< Type, GeoMesh >::~SlicedDimensionedField(), slicedFaePatchField< Type >::~slicedFaePatchField(), slicedFaPatchField< Type >::~slicedFaPatchField(), slicedFvPatchField< Type >::~slicedFvPatchField(), slicedFvsPatchField< Type >::~slicedFvsPatchField(), and SlicedGeometricField< Type, PatchField, SlicedPatchField, GeoMesh >::~SlicedGeometricField().
deepCopy() [1/2]
template<class T > void deepCopy (const UList< T > & list)
Definition at line 99 of file UList.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, Foam::nl, and UPtrList< T >::size().
Referenced by SubList< T >::operator=(), and SubList< T >::operator=().
deepCopy() [2/2]
template<class T > template<class Addr > void deepCopy (const IndirectListBase< T, Addr > & list)
Definition at line 136 of file UList.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, List_ACCESS, Foam::nl, UPtrList< T >::size(), and T.
slice() [1/4]
template<class Type > Foam::SubList< Type > slice (const label pos, label len = -1)
Definition at line 161 of file SubList.H.
References Foam::pos(), and UList< T >::size().
Referenced by ZoneMesh< ZoneType, MeshType >::checkParallelSync().
slice() [2/4]
template<class Type > const Foam::SubList< Type > slice (const label pos, label len = -1) const
Definition at line 173 of file SubList.H.
References Foam::pos(), and UList< T >::size().
slice() [3/4]
template<class Type > Foam::SubList< Type > slice (const labelRange & range)
Definition at line 185 of file SubList.H.
References range.
slice() [4/4]
template<class Type > const Foam::SubList< Type > slice (const labelRange & range) const
Definition at line 193 of file SubList.H.
References range.
operator[]() [1/7]
template<class T > T & operator[] (const label i) inline
Definition at line 291 of file UListI.H.
Referenced by triSurfaceMesh::boundingSpheres(), NURBS3DCurve::buildCurve(), NURBS3DSurface::buildSurface(), directions::directions(), patchProbes::findElements(), triSurfaceMesh::getRegion(), distributedTriSurfaceMesh::getRegion(), mixture::mixture(), processorColour::myColour(), List< T >::newElmt(), IjkField< Type >::operator()(), IjkField< Type >::operator()(), IjkField< Type >::operator()(), IjkField< Type >::operator()(), hashedWordList::operator[](), interpolationLookUpTable< Type >::operator[](), interpolationLookUpTable< Type >::operator[](), patchZones::patchZones(), probes::probe(), regionSplit2D::regionSplit2D(), DynamicList< T, SizeMin >::remove(), thirdBodyEfficiencies::thirdBodyEfficiencies(), and face::thisLabel().
operator[]() [2/7]
template<class T > const T & operator[] (const label i) const inline
Definition at line 301 of file UListI.H.
operator const Foam::List< T > &()
template<class T > operator const Foam::List< T > & () const inline
Definition at line 311 of file UListI.H.
operator=() [2/3]
template<class T > void operator= (const T & val)
Definition at line 161 of file UList.C.
References List_ACCESS, and T.
operator=() [3/3]
template<class T > void operator= (const Foam::zero)
Definition at line 175 of file UList.C.
References List_ACCESS, T, and Foam::Zero.
begin() [1/4]
template<class T > Foam::UList< T >::iterator begin () inline noexcept
Definition at line 321 of file UListI.H.
Referenced by Foam::BitOps::all(), lduMatrix::Amul(), Foam::BitOps::any(), DICPreconditioner::calcReciprocalD(), DILUPreconditioner::calcReciprocalD(), distributedDILUPreconditioner::calcReciprocalD(), Foam::ListListOps::combineOffset(), Foam::BitOps::count(), diagonalPreconditioner::diagonalPreconditioner(), DiagonalPreconditioner< Type, DType, LUType >::DiagonalPreconditioner(), DICPreconditioner::DICPreconditioner(), DICSmoother::DICSmoother(), DILUPreconditioner::DILUPreconditioner(), DILUSmoother::DILUSmoother(), edge::erase(), FDICPreconditioner::FDICPreconditioner(), FDICSmoother::FDICSmoother(), Foam::ensightOutput::Detail::getFaceSizes(), Foam::ensightOutput::Detail::getFaceSizes(), Foam::ensightOutput::Detail::getPolysNFaces(), Foam::ensightOutput::Detail::getPolysNPointsPerFace(), lduMatrix::H(), Foam::identity(), Foam::ListOps::identity(), Foam::Im(), Foam::Im(), PDRblock::innerMesh(), edge::insert(), Foam::BitOps::none(), face::points(), Foam::Re(), Foam::Re(), Foam::ReImSum(), Foam::ReImSum(), vtuSizing::renumberVertLabelsLegacy(), lduMatrix::residual(), ODESolver::resizeField(), nonBlockingGaussSeidelSmoother::smooth(), GaussSeidelSmoother::smooth(), symGaussSeidelSmoother::smooth(), Foam::sortedOrder(), DiagonalMatrix< Type >::sortPermutation(), fileOperation::sortTimes(), lduMatrix::sumA(), TGaussSeidelSmoother< Type, DType, LUType >::TGaussSeidelSmoother(), patchMeshWriter::writePolys(), and patchMeshWriter::writePolysLegacy().
end() [1/2]
template<class T > Foam::UList< T >::iterator end () inline noexcept
Definition at line 365 of file UListI.H.
Referenced by edgeSurface::addIntersectionEdges(), Foam::BitOps::all(), Foam::BitOps::any(), triSurfaceTools::collapseEdges(), blockEdge::compare(), blockEdge::compare(), edgeVertex::coord(), twoDPointCorrector::correctDisplacement(), Foam::BitOps::count(), wallBoundedParticle::crossEdgeConnectedFace(), geomCellLooper::cut(), extendedEdgeMesh::edgeDirection(), directionInfo::edgeToFaceIndex(), edge::erase(), cellLooper::getFirstVertEdge(), triSurfaceTools::getVertexTriangles(), triSurfaceTools::getVertexVertices(), Foam::identity(), Foam::ListOps::identity(), edge::insert(), edgeCollapser::markSmallEdges(), fileOperation::mergeTimes(), motionSmootherAlgo::modifyMotionPoints(), Foam::BitOps::none(), vtuSizing::renumberVertLabelsLegacy(), boundaryMesh::setFeatureEdges(), meshCutter::setRefinement(), meshCutAndRemove::setRefinement(), Foam::sortedOrder(), DiagonalMatrix< Type >::sortPermutation(), fileOperation::sortTimes(), surfaceFeatures::subsetPlane(), boundaryCutter::updateMesh(), meshCutAndRemove::updateMesh(), meshCutter::updateMesh(), wallLayerCells::wallLayerCells(), and Foam::writeObjEdges().
begin() [2/4]
template<class T > Foam::UList< T >::iterator begin (const label i) inline noexcept
Definition at line 343 of file UListI.H.
cbegin() [1/2]
template<class T > Foam::UList< T >::const_iterator cbegin () const inline noexcept
Definition at line 335 of file UListI.H.
Referenced by Foam::isFaceCut().
cend()
template<class T > Foam::UList< T >::const_iterator cend () const inline noexcept
Definition at line 379 of file UListI.H.
Referenced by Foam::isFaceCut().
begin() [3/4]
template<class T > Foam::UList< T >::const_iterator begin () const inline noexcept
Definition at line 328 of file UListI.H.
end() [2/2]
template<class T > Foam::UList< T >::const_iterator end () const inline noexcept
Definition at line 372 of file UListI.H.
cbegin() [2/2]
template<class T > Foam::UList< T >::const_iterator cbegin (const label i) const inline noexcept
Definition at line 357 of file UListI.H.
begin() [4/4]
template<class T > Foam::UList< T >::const_iterator begin (const label i) const inline noexcept
Definition at line 350 of file UListI.H.
rbegin() [1/2]
template<class T > Foam::UList< T >::reverse_iterator rbegin () inline
Definition at line 386 of file UListI.H.
rend() [1/2]
template<class T > Foam::UList< T >::reverse_iterator rend () inline
Definition at line 407 of file UListI.H.
crbegin()
template<class T > Foam::UList< T >::const_reverse_iterator crbegin () const inline
Definition at line 400 of file UListI.H.
crend()
template<class T > Foam::UList< T >::const_reverse_iterator crend () const inline
Definition at line 421 of file UListI.H.
rbegin() [2/2]
template<class T > Foam::UList< T >::const_reverse_iterator rbegin () const inline
Definition at line 393 of file UListI.H.
rend() [2/2]
template<class T > Foam::UList< T >::const_reverse_iterator rend () const inline
Definition at line 414 of file UListI.H.
empty()
template<class T > bool empty () const inline noexcept
Definition at line 457 of file UList.H.
Referenced by DynamicID< ObjectType >::active(), unwatchedIOdictionary::addWatch(), conjugateGradient::allocateFields(), BFGS::allocateMatrices(), DBFGS::allocateMatrices(), LBFGS::allocateMatrices(), SR1::allocateMatrices(), PDRblock::location::centre(), primitiveMesh::checkPoints(), collector::collector(), multiWorldConnections::comms(), optimisationType::computeMeritFunction(), mapDistributeBase::countUnmapped(), hexCellLooper::cut(), systemCall::dispatch(), lumpedPointController::empty(), ensightPart::empty(), treeDataFace::empty(), treeDataCell::empty(), treeDataEdge::empty(), treeDataPoint::empty(), BiIndirectList< T >::empty(), thermoCoupleProbes::execute(), STLAsciiParseManual::execute(), PDRblock::location::findCell(), Foam::findEtcFiles(), PDRblock::location::findIndex(), ZoneMesh< ZoneType, MeshType >::findIndex(), coordinateSystems::findIndex(), DynamicID< ObjectType >::index(), coordinateSystems::indices(), faBoundaryMesh::indices(), polyBoundaryMesh::indices(), ZoneMesh< ZoneType, MeshType >::indices(), objectivePtLosses::initialize(), objectiveUniformityPatch::initialize(), wallBoundedStreamLineParticle::interpolateFields(), PDRblock::location::length(), lumpedPointDisplacementPointPatchVectorField::lumpedPointDisplacementPointPatchVectorField(), oversetFvPatchField< Type >::manipulateMatrix(), PDRblock::location::max(), PDRblock::location::min(), coordinateSystems::names(), triSurfaceMesh::overlaps(), coupledPolyPatch::parallel(), globalMeshData::parallel(), argList::parse(), meshedSurfRef::points(), porosityModel::porosityModel(), boundaryMesh::readTriSurface(), sampledCuttingPlane::sampledCuttingPlane(), sampledIsoSurface::sampledIsoSurface(), sampledPlane::sampledPlane(), sampledPlane::sampledPlane(), meshedSurfRef::scalePoints(), timeSelector::select0(), seriesProfile::seriesProfile(), fieldsExpression::setResultName(), faceSetOption::setSelection(), cellSetOption::setSelection(), combineFaces::setUnrefinement(), SingleKineticRateDevolatilisation< CloudType >::SingleKineticRateDevolatilisation(), mappedPatchBase::subRegistry(), Foam::subsetSubset(), surfaceIntersection::surfaceIntersection(), treeBoundBox::treeBoundBox(), fileOperation::uniformFile(), zoneSubSet::useSubMesh(), viscousDissipation::viscousDissipation(), thermoCoupleProbes::write(), particle< Type >::writeProperty(), particle< Type >::writeProperty(), and zoneMotion::zoneMotion().
size() [2/2]
template<class T > label size () const inline noexcept
Definition at line 460 of file UList.H.
Referenced by face::areaInContact(), ITstream::back(), PDRblock::location::C(), cellClassification::cellClassification(), coordSet::checkDimensions(), sampledSet::checkDimensions(), PDRblock::location::clip(), PDRblock::location::contains(), triSurfaceMesh::coordinates(), distributedTriSurfaceMesh::distribute(), distributedTriSurfaceMesh::distributedTriSurfaceMesh(), distributedTriSurfaceMesh::distributedTriSurfaceMesh(), distributedTriSurfaceMesh::distributedTriSurfaceMesh(), DynamicList< T, SizeMin >::emplace_back(), DynamicField< T, SizeMin >::emplace_back(), DynamicList< T, SizeMin >::expandStorage(), DynamicField< T, SizeMin >::expandStorage(), faceZone::faceZone(), faceZone::faceZone(), NURBS3DCurve::findClosestCurvePoint(), patchProbes::findElements(), probes::findElements(), PDRblock::location::findIndex(), genericFaePatchField< Type >::genericFaePatchField(), genericFaPatchField< Type >::genericFaPatchField(), genericFvPatchField< Type >::genericFvPatchField(), genericFvsPatchField< Type >::genericFvsPatchField(), distributedTriSurfaceMesh::globalTris(), waWallFunctionFvPatchScalarField::gradientBoundaryCoeffs(), oversetFvPatchField< Type >::gradientBoundaryCoeffs(), waWallFunctionFvPatchScalarField::gradientInternalCoeffs(), oversetFvPatchField< Type >::gradientInternalCoeffs(), intersectedSurface::intersectedSurface(), triSurfaceMesh::isSurfaceClosed(), hashedWordList::lookup(), waWallFunctionFvPatchScalarField::manipulateMatrix(), mixture::mixture(), PDRblock::location::nCells(), faPatch::nEdges(), polySurface::nFaces(), PDRblock::location::nPoints(), coordSet::nPoints(), cellShape::nPoints(), ITstream::nRemainingTokens(), obstacleGrouping::nTotal(), obstacleGrouping::nTotalCylinder(), obstacleGrouping::nTotalObstacle(), DynamicList< T, SizeMin >::push_back(), DynamicList< T, SizeMin >::push_back(), DynamicList< T, SizeMin >::push_back(), DynamicField< T, SizeMin >::push_back(), DynamicList< T, SizeMin >::push_back(), DynamicField< T, SizeMin >::push_back(), DynamicList< T, SizeMin >::push_back(), DynamicList< T, SizeMin >::push_back(), DynamicList< T, SizeMin >::push_back(), DynamicField< T, SizeMin >::push_back(), face::ray(), referredWallFace::referredWallFace(), DynamicList< T, SizeMin >::remove(), DynamicList< T, SizeMin >::resize(), DynamicField< T, SizeMin >::resize(), List< T >::set(), DynamicList< T, SizeMin >::shrinkStorage(), DynamicField< T, SizeMin >::shrinkStorage(), faPatch::size(), triSurfaceMesh::size(), valuePointPatchField< Type >::size(), MeshedSurface< Face >::size(), polySurface::size(), UList< T >::slice(), Field< Type >::slice(), UList< T >::slice(), Field< Type >::slice(), zeroGradientFaPatchField< Type >::snGrad(), clampedPlateFaPatchField< Type >::snGrad(), zeroGradientFvPatchField< Type >::snGrad(), thirdBodyEfficiencies::thirdBodyEfficiencies(), triSurfaceMesh::triSurfaceMesh(), triSurfaceMesh::triSurfaceMesh(), waWallFunctionFvPatchScalarField::updateCoeffs(), PDRblock::location::valid(), waWallFunctionFvPatchScalarField::valueBoundaryCoeffs(), oversetFvPatchField< Type >::valueBoundaryCoeffs(), waWallFunctionFvPatchScalarField::valueInternalCoeffs(), oversetFvPatchField< Type >::valueInternalCoeffs(), and distributedTriSurfaceMesh::writeStats().
max_size()
template<class T > static constexpr label max_size () inline static constexpr noexcept
Definition at line 463 of file UList.H.
References Foam::labelMax.
swap()
template<class T > void swap (UList< T > & list) inline
Definition at line 435 of file UListI.H.
Referenced by DynamicField< T, SizeMin >::swap(), DynamicList< T, SizeMin >::swap(), DynamicField< T, SizeMin >::swap(), hashedWordList::swap(), IListStreamAllocator::swap(), and SortableList< T >::swap().
operator==()
template<class T > bool operator== (const UList< T > & a) const
OR: return ((this->size_ == list.size_)
);
Definition at line 255 of file UList.C.
References List_CONST_ACCESS, and T.
operator!=()
template<class T > bool operator!= (const UList< T > & a) const
Definition at line 283 of file UList.C.
operator<()
template<class T > bool operator< (const UList< T > & list) const
OR: return std::lexicographical_compare (cbegin(), cend(), list.cbegin(), list.cend());
Definition at line 290 of file UList.C.
References UPtrList< T >::cbegin(), and UPtrList< T >::cend().
operator>()
template<class T > bool operator> (const UList< T > & a) const
Definition at line 325 of file UList.C.
operator<=()
template<class T > bool operator<= (const UList< T > & a) const
Definition at line 332 of file UList.C.
operator>=()
template<class T > bool operator>= (const UList< T > & a) const
Definition at line 339 of file UList.C.
References Foam::operator<().
readList() [1/3]
template<class T > Foam::Istream & readList (Istream & is)
Definition at line 150 of file UListIO.C.
References token::BEGIN_LIST, IOstreamOption::BINARY, Foam::dynamicCast(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, FUNCTION_NAME, Foam::nl, UPtrList< T >::size(), T, and PtrList< T >::transfer().
writeEntry() [2/4]
template<class T > void writeEntry (const word & keyword, Ostream & os) const
Definition at line 59 of file UListIO.C.
References token::END_STATEMENT, Foam::endl(), os(), and Ostream::writeKeyword().
writeList() [1/3]
template<class T > Foam::Ostream & writeList (Ostream & os, const label shortLen = 0) const
Definition at line 71 of file UListIO.C.
References token::BEGIN_BLOCK, IOstreamOption::BINARY, token::END_BLOCK, IOstreamOption::format(), Foam::nl, os(), UPtrList< T >::size(), and OBJstream::write().
Referenced by Foam::printStatus().
test()
template<class T > template<class TypeT = T> std::enable_if< std::is_same< bool, TypeT >::value, bool >::type test (const label i) const inline
Definition at line 523 of file UList.H.
Referenced by ensightFaces::classify(), pointSet::distribute(), cellSet::distribute(), faceSet::distribute(), faceSet::sync(), pointSet::sync(), and topoBoolSet::updateLabels().
get()
template<class T > template<class TypeT = T> std::enable_if< std::is_same< bool, TypeT >::value, bool >::type get (const label i) const inline
Definition at line 533 of file UList.H.
Referenced by interfaceTrackingFvMesh::init(), fvMeshTools::newMesh(), and faMeshTools::newMesh().
unset()
template<class T > template<class TypeT = T> std::enable_if< std::is_same< bool, TypeT >::value, bool >::type unset (const label i) inline
Definition at line 544 of file UList.H.
Referenced by Foam::BitOps::unset(), and Foam::BitOps::unset().
first() [1/2]
template<class T > T & first () inline
Definition at line 593 of file UList.H.
References UList< T >::front().
Referenced by treeDataEdge::bounds(), treeDataEdge::bounds(), Foam::boundsImpl(), faPatch::calcPointEdges(), faPatch::calcPointLabels(), polyMeshGeometry::checkFaceAngles(), primitiveMeshGeometry::checkFaceAngles(), PrimitivePatch< FaceList, PointField >::checkTopology(), noiseModel::checkUniformTimeStep(), shellSurfaces::directionalSelectLevel(), face::edgeDirection(), triFace::edgeDirection(), primitiveMeshTools::faceConcavity(), PrimitivePatch< FaceList, PointField >::findEdge(), Foam::findEtcEntry(), fvMeshSubsetProxy::fvMeshSubsetProxy(), DynamicID< ObjectType >::index(), faBoundaryMesh::indices(), polyBoundaryMesh::indices(), ZoneMesh< ZoneType, MeshType >::indices(), Foam::markupBoundaryPoints(), Foam::operator<(), Foam::operator<(), Foam::operator==(), Foam::operator==(), cuttingPlane::performCut(), cuttingSurface::performCut(), PDRblock::gridControl::prepend(), Foam::printPatchEdges(), areaWrite::read(), pointNoise::read(), surfaceNoise::read(), waveModel::readDict(), Foam::reverse(), Foam::reverse(), sampledCuttingPlane::sampledCuttingPlane(), sampledCuttingSurface::sampledCuttingSurface(), sampledInterface::sampledInterface(), sampledIsoSurface::sampledIsoSurface(), sampledPlane::sampledPlane(), timeSelector::select0(), Foam::serializeProjectEdge(), faceSetOption::setSelection(), cellSetOption::setSelection(), multiphaseSystem::solve(), primitiveEntry::startLineNumber(), cutFaceAdvect::timeIntegratedArea(), cutFaceAdvect::timeIntegratedArea(), surfaceIteratorIso::vofCutCell(), surfaceIteratorPLIC::vofCutCell(), OBJstream::write(), OBJstream::write(), OBJstream::write(), OBJstream::write(), and lumpedPointMovement::writeStateVTP().
first() [2/2]
template<class T > const T & first () const inline
Definition at line 597 of file UList.H.
References UList< T >::front().
last() [1/2]
template<class T > T & last () inline
Definition at line 601 of file UList.H.
References UList< T >::back().
Referenced by PDRblock::gridControl::append(), polyMeshGeometry::checkFaceAngles(), primitiveMeshGeometry::checkFaceAngles(), noiseModel::checkUniformTimeStep(), processorLduInterface::compressedReceive(), processorLduInterface::compressedSend(), primitiveEntry::endLineNumber(), primitiveMeshTools::faceConcavity(), wallBoundedStreamLineParticle::interpolateFields(), lduPrimitiveMesh::lduPrimitiveMesh(), SprayCloud< CloudType >::penetration(), cuttingPlane::performCut(), cuttingSurface::performCut(), refinementHistory::refinementHistory(), cutFaceAdvect::timeIntegratedArea(), cutFaceAdvect::timeIntegratedArea(), lduPrimitiveMesh::upperTriOrder(), surfaceIteratorIso::vofCutCell(), surfaceIteratorPLIC::vofCutCell(), and regIOobject::writeObject().
last() [2/2]
template<class T > const T & last () const inline
Definition at line 605 of file UList.H.
References UList< T >::back().
found()
template<class T > bool found (const T & val, label pos = 0) const inline
Definition at line 608 of file UList.H.
References UList< T >::contains(), and Foam::pos().
Referenced by manualGAMGProcAgglomeration::agglomerate(), fvPatch::constraintType(), simplifiedFvMesh::fvPatchFieldExists(), triSurfaceTools::getEdge(), patchIdentifier::inGroup(), zoneIdentifier::inGroup(), processorFaPatch::makeNonGlobalPatchPoints(), cellCuts::nonAnchorPoints(), findNearestMaskedOp< PatchType >::operator()(), triSurfaceTools::oppositeEdge(), triSurfaceTools::oppositeVertex(), faBoundaryMesh::setGroup(), polyBoundaryMesh::setGroup(), and ZoneMesh< ZoneType, MeshType >::setGroup().
readList() [2/3]
Istream & readList (Istream & is)
writeEntry() [3/4]
void writeEntry (Ostream & os) const protected
writeList() [2/3]
Ostream & writeList (Ostream & os, const label) const
operator[]() [3/7]
const bool & operator[] (const label i) const inline
Definition at line 277 of file UListI.H.
operator[]() [4/7]
UPstream::commsStruct & operator[] (const label procID)
operator[]() [5/7]
const UPstream::commsStruct & operator[] (const label procID) const
operator[]() [6/7]
Foam::UPstream::commsStruct & operator[] (const label procID)
Definition at line 268 of file UPstreamCommsStruct.C.
References UPstream::procID(), and UPstream::commsStruct::reset().
operator[]() [7/7]
const Foam::UPstream::commsStruct & operator[] (const label procID) const
Definition at line 284 of file UPstreamCommsStruct.C.
References UPstream::procID().
writeEntry() [4/4]
void writeEntry (Ostream & os) const protected
Definition at line 64 of file charUList.C.
References UPtrList< T >::count(), os(), PtrList< T >::PtrList(), UPtrList< T >::size(), token::SPACE, and Foam::writeChars().
writeList() [3/3]
Ostream & writeList (Ostream & os, const label) const
Definition at line 90 of file charUList.C.
References os(), UPtrList< T >::size(), and Foam::writeChars().
readList() [3/3]
Istream & readList (Istream & is)
Definition at line 101 of file charUList.C.
References IOstreamOption::BINARY, Foam::dynamicCast(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, FUNCTION_NAME, Foam::nl, PtrList< T >::PtrList(), UPtrList< T >::size(), and PtrList< T >::transfer().
Friends And Related Symbol Documentation
List< T >
template<class T > friend class List< T > friend
Definition at line 159 of file UList.H.
SubList< T >
template<class T > friend class SubList< T > friend
Definition at line 159 of file UList.H.
operator>>
template<class T > Istream & operator>> (Istream & os, UList< T > & list) friend
Definition at line 645 of file UList.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/HashTables/HashTable/HashTable.H
src/OpenFOAM/containers/Lists/List/UList.H
src/OpenFOAM/containers/Lists/List/SubList.H
src/OpenFOAM/containers/Lists/List/UList.C
src/OpenFOAM/containers/Lists/List/UListI.H
src/OpenFOAM/containers/Lists/List/UListIO.C