OpenFOAM: distanceSurface Class Reference
distanceSurface Class Reference
A surface defined by a distance from an input searchable surface. Uses an iso-surface algorithm (cell, topo, point) for constructing the distance surface.
#include <distanceSurface.H>
Public Member Functions
TypeName ("distanceSurface")
distanceSurface (const word &defaultSurfaceName, const polyMesh &mesh, const dictionary &dict)
distanceSurface (const polyMesh &mesh, const word &surfaceType, const word &surfaceName, const isoSurfaceParams &params=isoSurfaceParams(), const bool interpolate=false)
distanceSurface (const polyMesh &mesh, const bool interpolate, const word &surfaceType, const word &surfaceName, const scalar distance, const bool useSignedDistance, const isoSurfaceParams &params=isoSurfaceParams())
distanceSurface (const polyMesh &mesh, const bool interpolate, autoPtr< searchableSurface > &&surface, const scalar distance, const bool useSignedDistance, const isoSurfaceParams &params=isoSurfaceParams())
virtual ~distanceSurface ()=default
void createGeometry ()
const word & surfaceName () const
scalar distance () const noexcept
const meshedSurface & surface () const
meshedSurface & surface ()
const labelList & meshCells () const
labelList & meshCells ()
void print (Ostream &os, int level=0) const
Protected Member Functions
bool hasIsoSurface () const
template<class Type >
tmp< Field< Type > > isoSurfaceInterpolate (const VolumeField< Type > &cellValues, const Field< Type > &pointValues) const
bool refineBlockedCells (bitSet &ignoreCells, const isoSurfaceBase &isoContext) const
bitSet filterPrepareRegionSplit (const bitSet &ignoreCells) const
void filterKeepLargestRegion (bitSet &ignoreCells) const
void filterKeepNearestRegions (bitSet &ignoreCells) const
void filterRegionProximity (bitSet &ignoreCells) const
void filterFaceProximity ()
Detailed Description
A surface defined by a distance from an input searchable surface. Uses an iso-surface algorithm (cell, topo, point) for constructing the distance surface.
For a zero-distance surface, it performs additional checks and supports filtering to handle the surface boundaries.
Usage
Example of function object partial specification:
surfaces
{
    surface1
    {
        type        distanceSurface;
        surfaceType triSurfaceMesh;
        surfaceName something.obj;
        topology    proximityFaces;
    }
    surface2
    {
        type        distanceSurface;
        surfaceType triSurfaceMesh;
        surfaceName other.obj;
        topology    nearestPoints;
        nearestPoints
        (
            (0 0 0)
            (10 10 0)
        );
        // Max search distance for nearestPoints
        maxDistance 0.005;
    }
}
Dictionary controls:
Property Description Required Default
distance distance from surface no 0
signed Use sign when distance is positive no true
isoMethod Iso-algorithm (cell/topo/point) no default
regularise Face simplification (enum or bool) no true
bounds Limit with bounding box no
surfaceType Type of surface yes
surfaceName Name of surface in triSurface/ no dict name
topology Topology filter name no none
nearestPoints Points for point-based segmentation no
maxDistance Max search distance for nearestPoints no GREAT
absProximity Max proximity of face centres no 1e-5
Topology/Filtering (for zero-distance only). These represent different ways to tackle the "ragged edge" problem.
none : No filtering
proximityFaces or proximity (post-filter): Checks the resulting faces against the original search surface and rejects faces with a distance greater than absProximity.
proximityRegions (post-filter): Checks the distance of the resulting faces against the original search surface. Filters based on the area-weighted distance of each topologically connected region. If the area-weighted distance of a region is greater than absProximity, the entire region is rejected.
largestRegion (pre-filter): The cut cells are checked for topological connectivity and the region with the most number of cut cells is retained.
nearestPoints (pre-filter): The cut cells split into regions, the regions closest to the user-defined points are retained. Uses maxDistance for additional control.
Note
For distance = 0, some special adjustments.
Always signed (ignoring the input value).
Use normal distance from surface (for better treatment of open edges).
Additional checks for open surfaces edges are used to limit the extend of resulting distance surface. The resulting surface elements will, however, contain partial cell coverage. NB: Not applicable if the point isoMethod is used.
The keyword cell (bool value) which was use in 1906 and earlier to switch between point/cell algorithms is now ignored (2020-12).
Changed default algorithm from cell to topo (2020-12).
Source files
distanceSurface.H
distanceSurface.C
distanceSurfaceFilter.C
Definition at line 205 of file distanceSurface.H.
Constructor & Destructor Documentation
distanceSurface() [1/4]
distanceSurface (const word & defaultSurfaceName, const polyMesh & mesh, const dictionary & dict)
Definition at line 234 of file distanceSurface.C.
References dict, Foam::New(), and Foam::sqr().
distanceSurface() [2/4]
distanceSurface (const polyMesh & mesh, const word & surfaceType, const word & surfaceName, const isoSurfaceParams & params = isoSurfaceParams(), const bool interpolate = false)
Definition at line 304 of file distanceSurface.C.
distanceSurface() [3/4]
distanceSurface (const polyMesh & mesh, const bool interpolate, const word & surfaceType, const word & surfaceName, const scalar distance, const bool useSignedDistance, const isoSurfaceParams & params = isoSurfaceParams())
Definition at line 326 of file distanceSurface.C.
distanceSurface() [4/4]
distanceSurface (const polyMesh & mesh, const bool interpolate, autoPtr< searchableSurface > && surface, const scalar distance, const bool useSignedDistance, const isoSurfaceParams & params = isoSurfaceParams())
Definition at line 362 of file distanceSurface.C.
~distanceSurface()
virtual ~distanceSurface () virtual default
Member Function Documentation
hasIsoSurface()
bool hasIsoSurface () const inline protected
Definition at line 298 of file distanceSurface.H.
isoSurfaceInterpolate()
template<class Type > tmp< Field< Type > > isoSurfaceInterpolate (const VolumeField< Type > & cellValues, const Field< Type > & pointValues) const inline protected
Definition at line 305 of file distanceSurface.H.
refineBlockedCells()
bool refineBlockedCells (bitSet & ignoreCells, const isoSurfaceBase & isoContext) const protected
Definition at line 29 of file distanceSurfaceFilter.C.
References isoSurfaceBase::ANYCUT, PtrList< T >::set(), and UPtrList< T >::test().
filterPrepareRegionSplit()
Foam::bitSet filterPrepareRegionSplit (const bitSet & ignoreCells) const protected
Definition at line 61 of file distanceSurfaceFilter.C.
References forAll, PtrList< T >::set(), syncTools::syncFaceList(), and UPtrList< T >::test().
filterKeepLargestRegion()
void filterKeepLargestRegion (bitSet & ignoreCells) const protected
Definition at line 112 of file distanceSurfaceFilter.C.
References Pstream::broadcast(), Foam::findMax(), Foam::flatOutput(), forAll, Foam::Info, Pstream::listCombineGather(), UPstream::master(), Foam::nl, PtrList< T >::set(), UPtrList< T >::size(), Foam::sum(), UPtrList< T >::test(), and Foam::Zero.
filterKeepNearestRegions()
void filterKeepNearestRegions (bitSet & ignoreCells) const protected
Definition at line 179 of file distanceSurfaceFilter.C.
References Pstream::broadcast(), Foam::endl(), Foam::findMax(), UPtrList< T >::first(), Foam::flatOutput(), forAll, Foam::Info, Pstream::listCombineGather(), Foam::magSqr(), UPstream::master(), Foam::nl, PtrList< T >::set(), UPtrList< T >::size(), Foam::sqrt(), Foam::sum(), UPtrList< T >::test(), WarningInFunction, and Foam::Zero.
filterRegionProximity()
void filterRegionProximity (bitSet & ignoreCells) const protected
Definition at line 303 of file distanceSurfaceFilter.C.
References Pstream::broadcast(), Foam::faceMap(), forAll, Foam::Info, Pstream::listCombineGather(), UPstream::master(), Foam::nl, outputName(), Foam::returnReduceAnd(), PtrList< T >::set(), UPtrList< T >::size(), polyWriter::write(), writer(), and Foam::Zero.
filterFaceProximity()
void filterFaceProximity () protected
Definition at line 460 of file distanceSurfaceFilter.C.
References Foam::diff(), Foam::faceMap(), forAll, Foam::Info, Foam::mag(), Foam::nl, outputName(), Foam::Pout, PtrList< T >::resize(), PtrList< T >::set(), UPtrList< T >::size(), polyWriter::write(), and writer().
TypeName()
TypeName ("distanceSurface")
createGeometry()
void createGeometry ()
Definition at line 398 of file distanceSurface.C.
References isoSurfaceParams::ALGO_POINT, Foam::calcNormalDistance_filtered(), Foam::calcNormalDistance_nonzero(), Foam::calcNormalDistance_zero(), Foam::checkAllHits(), Foam::dimLength, Foam::endl(), fld(), forAll, isoSurfaceBase::New(), MeshObject< polyMesh, UpdateableMeshObject, pointMesh >::New(), IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, Foam::Pout, pts, primitiveMesh::reset(), UPtrList< T >::size(), and Foam::Zero.
Referenced by sampledDistanceSurface::update().
surfaceName()
const word & surfaceName () const inline
Definition at line 405 of file distanceSurface.H.
distance()
scalar distance () const inline noexcept
Definition at line 411 of file distanceSurface.H.
surface() [1/2]
const meshedSurface & surface () const inline
Definition at line 417 of file distanceSurface.H.
Referenced by sampledDistanceSurface::Cf(), sampledDistanceSurface::faces(), sampledDistanceSurface::magSf(), sampledDistanceSurface::points(), and sampledDistanceSurface::Sf().
surface() [2/2]
meshedSurface & surface () inline
Definition at line 427 of file distanceSurface.H.
meshCells() [1/2]
const labelList & meshCells () const inline
Definition at line 437 of file distanceSurface.H.
Referenced by sampledDistanceSurface::sampleOnFaces().
meshCells() [2/2]
labelList & meshCells () inline
Definition at line 447 of file distanceSurface.H.
print()
void print (Ostream & os, int level = 0) const
Definition at line 747 of file distanceSurface.C.
References Foam::distance(), os(), and UPtrList< T >::size().
Referenced by sampledDistanceSurface::print().
The documentation for this class was generated from the following files:
src/sampling/surface/distanceSurface/distanceSurface.H
src/sampling/surface/distanceSurface/distanceSurface.C
src/sampling/surface/distanceSurface/distanceSurfaceFilter.C