OpenFOAM: wallAbsorptionEmissionModel Class Reference
wallAbsorptionEmissionModel Class Reference abstract
Based class for wall absorption emission models.
#include <wallAbsorptionEmissionModel.H>
Public Member Functions
TypeName ("wallAbsorptionEmissionModel")
declareRunTimeSelectionTable (autoPtr, wallAbsorptionEmissionModel, dictionary,(const dictionary &dict, const polyPatch &pp),(dict, pp))
wallAbsorptionEmissionModel (const dictionary &dict, const polyPatch &pp)
virtual ~wallAbsorptionEmissionModel ()
virtual tmp< scalarField > e (const label bandI=0, vectorField *incomingDirection=nullptr, scalarField *T=nullptr) const =0
virtual scalar e (const label faceI, const label bandI=0, const vector dir=Zero, const scalar T=0) const =0
virtual tmp< scalarField > a (const label bandI=0, vectorField *incomingDirection=nullptr, scalarField *T=nullptr) const =0
virtual scalar a (const label faceI, const label bandI=0, const vector dir=Zero, const scalar T=0) const =0
virtual bool isGrey () const =0
virtual label nBands () const =0
Static Public Member Functions
static autoPtr< wallAbsorptionEmissionModel > New (const dictionary &dict, const polyPatch &pp)
Protected Attributes
const polyPatch & pp_
Detailed Description
Based class for wall absorption emission models.
Definition at line 46 of file wallAbsorptionEmissionModel.H.
Constructor & Destructor Documentation
wallAbsorptionEmissionModel()
wallAbsorptionEmissionModel (const dictionary & dict, const polyPatch & pp)
Definition at line 38 of file wallAbsorptionEmissionModel.C.
~wallAbsorptionEmissionModel()
~wallAbsorptionEmissionModel () virtual
Definition at line 50 of file wallAbsorptionEmissionModel.C.
Member Function Documentation
TypeName()
TypeName ("wallAbsorptionEmissionModel")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , wallAbsorptionEmissionModel , dictionary , (const dictionary &dict, const polyPatch &pp) , (dict, pp))
New()
Foam::autoPtr< Foam::radiation::wallAbsorptionEmissionModel > New (const dictionary & dict, const polyPatch & pp) static
Definition at line 26 of file wallAbsorptionEmissionModelNew.C.
References dict, Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, and pp().
Referenced by opaqueDiffusive::opaqueDiffusive(), opaqueReflective::opaqueReflective(), and transparent::transparent().
e() [1/2]
virtual tmp< scalarField > e (const label bandI = 0, vectorField * incomingDirection = nullptr, scalarField * T = nullptr) const pure virtual
Implemented in constantAbsorption, multiBandAbsorption, and solidAbsorption.
e() [2/2]
virtual scalar e (const label faceI, const label bandI = 0, const vector dir = Zero, const scalar T = 0) const pure virtual
Implemented in constantAbsorption, multiBandAbsorption, and solidAbsorption.
a() [1/2]
virtual tmp< scalarField > a (const label bandI = 0, vectorField * incomingDirection = nullptr, scalarField * T = nullptr) const pure virtual
Implemented in constantAbsorption, multiBandAbsorption, and solidAbsorption.
a() [2/2]
virtual scalar a (const label faceI, const label bandI = 0, const vector dir = Zero, const scalar T = 0) const pure virtual
Implemented in constantAbsorption, multiBandAbsorption, and solidAbsorption.
isGrey()
virtual bool isGrey () const pure virtual
Implemented in constantAbsorption, multiBandAbsorption, and solidAbsorption.
nBands()
virtual label nBands () const pure virtual
Implemented in constantAbsorption, multiBandAbsorption, and solidAbsorption.
Member Data Documentation
pp_
const polyPatch& pp_ protected
Definition at line 54 of file wallAbsorptionEmissionModel.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/radiation/submodels/wallAbsorptionEmissionModel/wallAbsorptionEmissionModel/wallAbsorptionEmissionModel.H
src/thermophysicalModels/radiation/submodels/wallAbsorptionEmissionModel/wallAbsorptionEmissionModel/wallAbsorptionEmissionModel.C
src/thermophysicalModels/radiation/submodels/wallAbsorptionEmissionModel/wallAbsorptionEmissionModel/wallAbsorptionEmissionModelNew.C