OpenFOAM: targetCoeffTrim Class Reference
targetCoeffTrim Class Reference
Trim model where the operating characteristics of rotor (e.g. blade pitch angle) can vary to reach a specified target thrust and torque.
#include <targetCoeffTrim.H>
Public Member Functions
TypeName ("targetCoeffTrim")
targetCoeffTrim (const fv::rotorDiskSource &rotor, const dictionary &dict)
targetCoeffTrim (const targetCoeffTrim &)=delete
void operator= (const targetCoeffTrim &)=delete
virtual ~targetCoeffTrim ()=default
void read (const dictionary &dict)
virtual tmp< scalarField > thetag () const
virtual void correct (const vectorField &U, vectorField &force)
virtual void correct (const volScalarField rho, const vectorField &U, vectorField &force)
template<class RhoFieldType >
Foam::vector calcCoeffs (const RhoFieldType &rho, const vectorField &U, const scalarField &thetag, vectorField &force) const
Public Member Functions inherited from trimModel
TypeName ("trimModel")
declareRunTimeSelectionTable (autoPtr, trimModel, dictionary,(const fv::rotorDiskSource &rotor, const dictionary &dict),(rotor, dict))
trimModel (const fv::rotorDiskSource &rotor, const dictionary &dict, const word &name)
virtual ~trimModel ()=default
Protected Member Functions
template<class RhoFieldType >
vector calcCoeffs (const RhoFieldType &rho, const vectorField &U, const scalarField &alphag, vectorField &force) const
template<class RhoFieldType >
void correctTrim (const RhoFieldType &rho, const vectorField &U, vectorField &force)
Protected Attributes
label calcFrequency_
bool useCoeffs_
vector target_
vector theta_
label nIter_
scalar tol_
scalar relax_
scalar dTheta_
scalar alpha_
Protected Attributes inherited from trimModel
const fv::rotorDiskSource & rotor_
const word name_
dictionary coeffs_
Additional Inherited Members
Static Public Member Functions inherited from trimModel
static autoPtr< trimModel > New (const fv::rotorDiskSource &rotor, const dictionary &dict)
Detailed Description
Trim model where the operating characteristics of rotor (e.g. blade pitch angle) can vary to reach a specified target thrust and torque.
Solves:
where
= Time level
= Coefficient vector (thrust force, roll moment, pitch moment)
= Pitch angle vector (collective, roll, pitch)
= Jacobian [3x3] matrix
The trimmed pitch angles are found via solving the above with a Newton-Raphson iterative method. The solver tolerance can be user-input, using the 'tol' entry.
If coefficients are requested (useCoeffs = true), the force and moments are normalised using:
and
where
= Force
= Moment
= User-input conversion coefficient (default = 1)
= Fluid desity
= Rotor angular velocity
= Mathematical pi
= Rotor radius
Usage
Minimal example by using constant/fvOptions: rotorDiskSource1 { Mandatory/Optional (inherited) entries ...
Mandatory entries (runtime modifiable) trimModel targetForce;
targetForceCoeffs { Conditional mandatory entries (runtime modifiable)
when trimModel=targetForce target { Mandatory entries (runtime modifiable) thrust 0.5; pitch 0.5; roll 0.5;
Optional entries (runtime modifiable) useCoeffs true; }
pitchAngles { theta0Ini 0.1; theta1cIni 0.1; theta1sIni 0.1; }
calcFrequency 1;
Optional entries (runtime modifiable) nIter 50; tol 1e-8; relax 1; dTheta 0.1; alpha 1.0; } }
where the entries mean:
Property Description Type Reqd Dflt
calcFrequency
Number of iterations between calls to 'correct'
label yes -
useCoeffs
Flag to indicate whether to solve coeffs
(true) or forces (false)
bool no true
thrust Target thrust (coefficient) scalar yes -
pitch Target pitch (coefficient) scalar yes -
roll Target roll moment (coefficient) scalar yes -
theta0Ini Initial pitch angle [deg] scalar yes -
theta1cIni
Initial lateral pitch angle (cos coeff) [deg]
scalar yes -
theta1sIni
Initial longitudinal pitch angle (sin coeff) [deg]
scalar yes -
nIter
Maximum number of iterations in trim routine
label no 50
tol Convergence tolerance in trim routine scalar no 1e-8
relax Relaxation factor in trim routine scalar no 1
dTheta
Perturbation angle used to determine Jacobian [deg]
scalar no 0.1
alpha
Coefficient to allow for conversion between US
and EU definitions
scalar no 1
See also
Foam::fv::rotorDiskSource
Foam::trimModel
Foam::fixedTrim
Source files
targetCoeffTrim.H
targetCoeffTrim.C
Definition at line 309 of file targetCoeffTrim.H.
Constructor & Destructor Documentation
targetCoeffTrim() [1/2]
targetCoeffTrim (const fv::rotorDiskSource & rotor, const dictionary & dict)
Definition at line 188 of file targetCoeffTrim.C.
References dict, and targetCoeffTrim::read().
targetCoeffTrim() [2/2]
targetCoeffTrim (const targetCoeffTrim &) delete
~targetCoeffTrim()
virtual ~targetCoeffTrim () virtual default
Member Function Documentation
calcCoeffs() [1/2]
template<class RhoFieldType > vector calcCoeffs (const RhoFieldType & rho, const vectorField & U, const scalarField & alphag, vectorField & force) const protected
correctTrim()
template<class RhoFieldType > void correctTrim (const RhoFieldType & rho, const vectorField & U, vectorField & force) protected
Definition at line 94 of file targetCoeffTrim.C.
References Foam::endl(), Foam::Info, Foam::inv(), Foam::mag(), Foam::nl, Foam::radToDeg(), rho, Foam::type(), U, and Foam::Zero.
TypeName()
TypeName ("targetCoeffTrim")
operator=()
void operator= (const targetCoeffTrim &) delete
read()
void read (const dictionary & dict) virtual
Reimplemented from trimModel.
Definition at line 211 of file targetCoeffTrim.C.
References Foam::degToRad(), dict, UPtrList< T >::get(), and trimModel::read().
Referenced by targetCoeffTrim::targetCoeffTrim().
thetag()
Foam::tmp< Foam::scalarField > thetag () const virtual
Implements trimModel.
Definition at line 247 of file targetCoeffTrim.C.
References Foam::cos(), forAll, tmp< T >::New(), psi, Foam::sin(), and x.
Referenced by targetCoeffTrim::calcCoeffs().
correct() [1/2]
void correct (const vectorField & U, vectorField & force) virtual
Implements trimModel.
Definition at line 264 of file targetCoeffTrim.C.
References U.
correct() [2/2]
void correct (const volScalarField rho, const vectorField & U, vectorField & force) virtual
Implements trimModel.
Definition at line 274 of file targetCoeffTrim.C.
References rho, and U.
calcCoeffs() [2/2]
template<class RhoFieldType > Foam::vector calcCoeffs (const RhoFieldType & rho, const vectorField & U, const scalarField & thetag, vectorField & force) const
Definition at line 40 of file targetCoeffTrim.C.
References targetCoeffTrim::alpha_, cells, forAll, Foam::constant::mathematical::pi(), Foam::pow4(), Foam::reduce(), rho, trimModel::rotor_, Foam::sqr(), targetCoeffTrim::thetag(), U, targetCoeffTrim::useCoeffs_, x, and Foam::Zero.
Member Data Documentation
calcFrequency_
label calcFrequency_ protected
Definition at line 318 of file targetCoeffTrim.H.
useCoeffs_
bool useCoeffs_ protected
Definition at line 321 of file targetCoeffTrim.H.
Referenced by targetCoeffTrim::calcCoeffs().
target_
vector target_ protected
Definition at line 324 of file targetCoeffTrim.H.
theta_
vector theta_ protected
Definition at line 327 of file targetCoeffTrim.H.
nIter_
label nIter_ protected
Definition at line 330 of file targetCoeffTrim.H.
tol_
scalar tol_ protected
Definition at line 333 of file targetCoeffTrim.H.
relax_
scalar relax_ protected
Definition at line 336 of file targetCoeffTrim.H.
dTheta_
scalar dTheta_ protected
Definition at line 339 of file targetCoeffTrim.H.
alpha_
scalar alpha_ protected
Definition at line 342 of file targetCoeffTrim.H.
Referenced by targetCoeffTrim::calcCoeffs().
The documentation for this class was generated from the following files:
src/fvOptions/sources/derived/rotorDiskSource/trimModel/targetCoeff/targetCoeffTrim.H
src/fvOptions/sources/derived/rotorDiskSource/trimModel/targetCoeff/targetCoeffTrim.C