OpenFOAM: polySurface Class Reference
polySurface Class Reference
A surface mesh consisting of general polygon faces and capable of holding fields.
#include <polySurface.H>
Public Types
enum FieldAssociation { NO_DATA = 0 , FACE_DATA = 1 , POINT_DATA = 2 , FACE_OR_POINT_DATA = 3 }
typedef polySurface Mesh
typedef bool BoundaryMesh
Public Types inherited from IOobject
enum objectState : char { GOOD , BAD }
enum fileCheckTypes : char { timeStamp , timeStampMaster , inotify , inotifyMaster }
Public Types inherited from IOobjectOption
enum readOption : unsigned char {
NO_READ = 0 , MUST_READ = 0x1 , READ_MODIFIED = 0x3 , MUST_READ_IF_MODIFIED = 0x3 ,
LAZY_READ = 0x4 , READ_IF_PRESENT = 0x4
}
enum writeOption : unsigned char { NO_WRITE = 0 , AUTO_WRITE = 0x10 }
enum registerOption : unsigned char { NO_REGISTER = 0 , REGISTER = 1 }
Public Types inherited from HashTable< regIOobject * >
typedef HashTable< regIOobject *, word, Foam::Hash< word > > this_type
typedef std::conditional< std::is_same< Foam::zero, typenamestd::remove_cv< regIOobject * >::type >::value, Detail::HashTableSingle< word >, Detail::HashTablePair< word, regIOobject * > >::type node_type
typedef word key_type
typedef regIOobject * mapped_type
typedef regIOobject * value_type
typedef Foam::Hash< word > hasher
typedef regIOobject * * pointer
typedef regIOobject * & reference
typedef const regIOobject * * const_pointer
typedef const regIOobject * & const_reference
typedef label difference_type
typedef label size_type
using key_iterator = key_iterator_base< iterator >
using const_key_iterator = key_iterator_base< const_iterator >
Public Types inherited from PrimitivePatch<::Foam::List< face >, pointField >
enum surfaceTopo
typedef std::remove_reference< ::Foam::List< face > >::type::value_type face_type
typedef std::remove_reference< pointField >::type::value_type point_type
typedef ::Foam::List< face > FaceListType
typedef pointField PointFieldType
typedef face_type FaceType
Public Types inherited from List< face >
typedef SubList< face > subList
Public Types inherited from UList< T >
typedef T value_type
typedef T * pointer
typedef const T * const_pointer
typedef T & reference
typedef const T & const_reference
typedef T * iterator
typedef const T * const_iterator
typedef label size_type
typedef label difference_type
typedef std::reverse_iterator< iterator > reverse_iterator
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
Public Member Functions
TypeName ("polySurface")
polySurface (const IOobject &io, bool doCheckIn=false)
polySurface (const word &surfName, const objectRegistry &obr, bool doCheckIn=false)
polySurface (const IOobject &io, const MeshedSurface< face > &surf, bool doCheckIn=false)
polySurface (const IOobject &io, MeshedSurface< face > &&surf, bool doCheckIn=false)
virtual ~polySurface ()
virtual label nPoints () const
virtual label nFaces () const
virtual label size () const
virtual const pointField & points () const
virtual const faceList & faces () const
virtual const labelList & zoneIds () const
const vectorField & Sf () const
const scalarField & magSf () const
const vectorField & Cf () const
void copySurface (const pointField &points, const faceList &faces, bool unused=false)
void copySurface (const meshedSurf &surf, bool unused=false)
void copySurface (const MeshedSurface< face > &surf, bool unused=false)
void transfer (pointField &&points, faceList &&faces, labelList &&zoneIds=labelList())
void transfer (MeshedSurface< face > &surf, bool validate=false)
label nFaceData () const
label nPointData () const
FieldAssociation queryFieldAssociation (const word &fieldName) const
const regIOobject * findFieldObject (const word &fieldName, const FieldAssociation association) const
template<class GeoMeshType = void>
const regIOobject * findFieldObject (const word &fieldName) const
template<class GeoMeshType = void>
const objectRegistry * whichRegistry (const word &fieldName) const
template<class DataType >
const objectRegistry & fieldData () const
const objectRegistry & faceData () const
const objectRegistry & pointData () const
template<class Type , class GeoMeshType = polySurfaceGeoMesh>
void storeField (const word &fieldName, const dimensionSet &dims, const Field< Type > &values)
template<class Type , class GeoMeshType = polySurfaceGeoMesh>
void storeField (const word &fieldName, const dimensionSet &dims, Field< Type > &&values)
virtual bool writeObject (IOstreamOption streamOpt, const bool writeOnProc) const
void clearGeom ()
void clearAddressing ()
void clearOut ()
void clearPrimitives ()
void clearFields ()
template<>
const regIOobject * findFieldObject (const word &fieldName) const
template<>
const regIOobject * findFieldObject (const word &fieldName) const
template<>
const objectRegistry * whichRegistry (const word &fieldName) const
template<>
const objectRegistry * whichRegistry (const word &fieldName) const
template<>
const regIOobject * findFieldObject (const word &fieldName) const
template<>
const regIOobject * findFieldObject (const word &fieldName) const
template<>
const objectRegistry * whichRegistry (const word &fieldName) const
template<>
const objectRegistry * whichRegistry (const word &fieldName) const
template<>
const objectRegistry & fieldData () const
template<class GeoMeshType >
const Foam::regIOobject * findFieldObject (const word &fieldName) const
template<class GeoMeshType >
const Foam::objectRegistry * whichRegistry (const word &fieldName) const
Public Member Functions inherited from objectRegistry
TypeName ("objectRegistry")
objectRegistry (const Time &db, const label nObjects=128)
objectRegistry (const IOobject &io, const label nObjects=128)
virtual ~objectRegistry ()
const objectRegistry & thisDb () const noexcept
const objectRegistry & parent () const noexcept
const Time & time () const noexcept
bool isTimeDb () const noexcept
virtual const fileName & dbDir () const
HashTable< wordHashSet > classes () const
template<class MatchPredicate >
HashTable< wordHashSet > classes (const MatchPredicate &matchName) const
UPtrList< const regIOobject > csorted () const
UPtrList< const regIOobject > sorted () const
UPtrList< regIOobject > sorted ()
template<class Type >
UPtrList< const Type > csorted () const
template<class Type >
UPtrList< const Type > sorted () const
template<class Type >
UPtrList< Type > sorted ()
template<class Type , class MatchPredicate >
UPtrList< const Type > csorted (const MatchPredicate &matchName) const
template<class Type , class MatchPredicate >
UPtrList< const Type > sorted (const MatchPredicate &matchName) const
template<class Type , class MatchPredicate >
UPtrList< Type > sorted (const MatchPredicate &matchName)
label count (const char *clsName) const
template<class MatchPredicate >
label count (const MatchPredicate &matchClass) const
template<class MatchPredicate1 , class MatchPredicate2 >
label count (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName) const
template<class Type >
label count (const bool strict=false) const
template<class Type , class MatchPredicate >
label count (const MatchPredicate &matchName) const
wordList names () const
wordList names (const char *clsName) const
template<class MatchPredicate >
wordList names (const MatchPredicate &matchClass) const
template<class MatchPredicate1 , class MatchPredicate2 >
wordList names (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName) const
template<class Type >
wordList names () const
template<class Type , class MatchPredicate >
wordList names (const MatchPredicate &matchName) const
wordList sortedNames () const
wordList sortedNames (const char *clsName) const
template<class MatchPredicate >
wordList sortedNames (const MatchPredicate &matchClass) const
template<class MatchPredicate1 , class MatchPredicate2 >
wordList sortedNames (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName) const
template<class Type >
wordList sortedNames () const
template<class Type , class MatchPredicate >
wordList sortedNames (const MatchPredicate &matchName) const
const objectRegistry & subRegistry (const word &name, const bool forceCreate=false, const bool recursive=false) const
template<class Type >
HashTable< const Type * > lookupClass (const bool strict=false) const
template<class Type >
HashTable< Type * > lookupClass (const bool strict=false)
const regIOobject * cfindIOobject (const word &name, const bool recursive=false) const
bool contains (const word &name, const bool recursive=false) const
template<class Type >
bool foundObject (const word &name, const bool recursive=false) const
template<class Type >
const Type * cfindObject (const word &name, const bool recursive=false) const
template<class Type >
const Type * findObject (const word &name, const bool recursive=false) const
template<class Type >
Type * findObject (const word &name, const bool recursive=false)
template<class Type >
Type * getObjectPtr (const word &name, const bool recursive=false) const
template<class Type >
const Type & lookupObject (const word &name, const bool recursive=false) const
template<class Type >
Type & lookupObjectRef (const word &name, const bool recursive=false) const
label getEvent () const
bool checkIn (regIOobject *io) const
bool checkIn (regIOobject &io) const
bool checkOut (regIOobject *io) const
bool checkOut (regIOobject &io) const
bool checkOut (const word &key) const
void clear ()
void clearStorage ()
bool erase (const iterator &iter)
bool erase (const word &key)
label erase (std::initializer_list< word > keys)
label erase (const UList< word > &keys)
virtual void rename (const word &newName)
bool cacheTemporaryObject (const word &name) const
template<class Type >
bool cacheTemporaryObject (Type &obj) const
void resetCacheTemporaryObject (const regIOobject *io) const
void resetCacheTemporaryObject (const regIOobject &io) const
bool checkCacheTemporaryObjects () const
virtual bool modified () const
void readModifiedObjects ()
virtual bool readIfModified ()
virtual bool writeData (Ostream &) const
bool found (const word &name, bool recursive=false) const
template<class Type >
const Type * lookupObjectPtr (const word &name, bool recursive=false) const
template<class Type >
Type * lookupObjectRefPtr (const word &name, bool recursive=false) const
template<class MatchPredicate >
Foam::HashTable< Foam::wordHashSet > classesImpl (const objectRegistry &list, const MatchPredicate &matchName)
template<class MatchPredicate1 , class MatchPredicate2 >
Foam::label countImpl (const objectRegistry &list, const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName)
template<class Type , class MatchPredicate >
Foam::label countTypeImpl (const objectRegistry &list, const MatchPredicate &matchName)
template<class MatchPredicate1 , class MatchPredicate2 >
Foam::wordList namesImpl (const objectRegistry &list, const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName, const bool doSort)
template<class Type , class MatchPredicate >
Foam::wordList namesTypeImpl (const objectRegistry &list, const MatchPredicate &matchName, const bool doSort)
template<class Type , class MatchPredicate >
Foam::UPtrList< Type > objectsTypeImpl (const objectRegistry &list, const MatchPredicate &matchName)
template<class MatchPredicate >
Foam::HashTable< Foam::wordHashSet > classes (const MatchPredicate &matchName) const
template<class MatchPredicate >
Foam::label count (const MatchPredicate &matchClass) const
template<class MatchPredicate1 , class MatchPredicate2 >
Foam::label count (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName) const
template<class Type , class MatchPredicate >
Foam::label count (const MatchPredicate &matchName) const
template<class Type >
Foam::label count (const bool strict) const
template<class Type >
Foam::UPtrList< const Type > csorted () const
template<class Type >
Foam::UPtrList< const Type > sorted () const
template<class Type >
Foam::UPtrList< Type > sorted ()
template<class Type , class MatchPredicate >
Foam::UPtrList< const Type > csorted (const MatchPredicate &matchName) const
template<class Type , class MatchPredicate >
Foam::UPtrList< const Type > sorted (const MatchPredicate &matchName) const
template<class Type , class MatchPredicate >
Foam::UPtrList< Type > sorted (const MatchPredicate &matchName)
template<class MatchPredicate >
Foam::wordList names (const MatchPredicate &matchClass) const
template<class MatchPredicate1 , class MatchPredicate2 >
Foam::wordList names (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName) const
template<class Type >
Foam::wordList names () const
template<class Type , class MatchPredicate >
Foam::wordList names (const MatchPredicate &matchName) const
template<class MatchPredicate >
Foam::wordList sortedNames (const MatchPredicate &matchClass) const
template<class MatchPredicate1 , class MatchPredicate2 >
Foam::wordList sortedNames (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName) const
template<class Type >
Foam::wordList sortedNames () const
template<class Type , class MatchPredicate >
Foam::wordList sortedNames (const MatchPredicate &matchName) const
template<class Type >
Foam::HashTable< const Type * > lookupClass (const bool strict) const
template<class Type >
Foam::HashTable< Type * > lookupClass (const bool strict)
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
regIOobject (const IOobject &io, const bool isTimeObject=false)
regIOobject (const regIOobject &rio)
regIOobject (const regIOobject &rio, bool registerCopy)
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
regIOobject (const IOobject &io, const regIOobject &rio)
virtual ~regIOobject ()
bool checkIn ()
bool checkOut ()
virtual void addWatch ()
bool registered () const noexcept
bool ownedByRegistry () const noexcept
bool store ()
void release (const bool unregister=false) noexcept
label eventNo () const noexcept
label & eventNo () noexcept
bool upToDate (const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
void setUpToDate ()
const dictionary * findMetaData () const noexcept
dictionary & getMetaData () noexcept
void removeMetaData ()
virtual void updateMetaData ()
virtual fileName filePath () const
bool headerOk ()
Istream & readStream (const word &, const bool readOnProc=true)
void close ()
virtual bool readData (Istream &)
virtual bool read ()
virtual label addWatch (const fileName &)
const labelList & watchIndices () const noexcept
labelList & watchIndices () noexcept
virtual bool write (const bool writeOnProc=true) const
virtual bool global () const
void operator= (const IOobject &io)
virtual bool writeObject (IOstreamOption::streamFormat fmt, IOstreamOption::versionNumber ver, IOstreamOption::compressionType cmp, const bool writeOnProc) const
Public Member Functions inherited from IOobject
TypeName ("IOobject")
IOobject (const IOobject &)=default
virtual ~IOobject ()=default
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const fileName &path, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const fileName &path, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const IOobject &io, const objectRegistry &registry)
IOobject (const IOobject &io, const word &name)
IOobject (const IOobject &io, const word &name, const fileName &local)
IOobject (const IOobject &io, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt)
IOobject (const IOobject &io, IOobjectOption::registerOption regOpt)
autoPtr< IOobject > clone () const
autoPtr< IOobject > clone (const objectRegistry &registry) const
const objectRegistry & db () const noexcept
const Time & time () const noexcept
const word & name () const noexcept
const word & headerClassName () const noexcept
word & headerClassName () noexcept
const string & note () const noexcept
string & note () noexcept
unsigned labelByteSize () const noexcept
unsigned scalarByteSize () const noexcept
void resetHeader (const word &newName=word::null)
bool hasHeaderClass () const noexcept
template<class Type >
bool isHeaderClass () const
template<class Type >
bool isHeaderClassName () const
word group () const
word member () const
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const noexcept
fileName & instance () noexcept
const fileName & local () const noexcept
fileName path () const
fileName path (const word &instance, const fileName &local=fileName::null) const
fileName objectPath () const
fileName objectRelPath () const
fileName localFilePath (const word &typeName, const bool search=true) const
fileName globalFilePath (const word &typeName, const bool search=true) const
IOstreamOption parseHeader (const dictionary &headerDict)
bool readHeader (Istream &is)
bool readHeader (dictionary &headerDict, Istream &is)
template<class Type >
bool typeHeaderOk (const bool checkType=true, const bool search=true, const bool verbose=true)
template<class Type >
void warnNoRereading () const
bool writeHeader (Ostream &os) const
bool writeHeader (Ostream &os, const word &objectType) const
void writeHeader (dictionary &dict, IOstreamOption streamOpt) const
void writeHeader (dictionary &dict, const word &objectType, IOstreamOption streamOpt) const
bool good () const noexcept
bool bad () const noexcept
InfoProxy< IOobject > info () const noexcept
void operator= (const IOobject &io)
template<>
bool isHeaderClass () const
template<class StringType >
Foam::word groupName (StringType base, const word &group)
Public Member Functions inherited from IOobjectOption
constexpr IOobjectOption (readOption rOpt=readOption::NO_READ, writeOption wOpt=writeOption::NO_WRITE, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (readOption rOpt, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (writeOption wOpt, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (registerOption registerObject, bool globalObject=false) noexcept
constexpr IOobjectOption (readOption rOpt, writeOption wOpt, bool registerObject, bool globalObject=false) noexcept
constexpr IOobjectOption (bool registerObject, bool globalObject=false) noexcept
readOption readOpt () const noexcept
readOption readOpt (readOption opt) noexcept
writeOption writeOpt () const noexcept
writeOption writeOpt (writeOption opt) noexcept
bool registerObject () const noexcept
bool registerObject (bool on) noexcept
bool globalObject () const noexcept
bool globalObject (bool on) noexcept
bool isAnyRead () const noexcept
bool isReadRequired () const noexcept
bool isReadOptional () const noexcept
readOption & readOpt () noexcept
writeOption & writeOpt () noexcept
bool & registerObject () noexcept
bool & globalObject () noexcept
Public Member Functions inherited from HashTable< regIOobject * >
HashTable ()
HashTable (const label size)
HashTable (Istream &is, const label size=128)
HashTable (const this_type &ht)
HashTable (this_type &&rhs)
HashTable (std::initializer_list< std::pair< word, regIOobject * > > list)
~HashTable ()
bool empty () const noexcept
label size () const noexcept
label capacity () const noexcept
regIOobject * & at (const word &key)
const regIOobject * & at (const word &key) const
bool contains (const word &key) const
iterator find (const word &key)
const_iterator find (const word &key) const
const_iterator cfind (const word &key) const
const regIOobject * & lookup (const word &key, const regIOobject * &deflt) const
List< word > toc () const
List< word > sortedToc () const
List< word > sortedToc (const Compare &comp) const
Foam::List< word > sortedToc (const Compare &comp) const
List< word > tocKeys (const UnaryPredicate &pred, const bool invert=false) const
Foam::List< word > tocKeys (const UnaryPredicate &pred, const bool invert) const
List< word > tocValues (const UnaryPredicate &pred, const bool invert=false) const
Foam::List< word > tocValues (const UnaryPredicate &pred, const bool invert) const
List< word > tocEntries (const BinaryPredicate &pred, const bool invert=false) const
Foam::List< word > tocEntries (const BinaryPredicate &pred, const bool invert) const
UPtrList< const node_type > csorted () const
UPtrList< const node_type > sorted () const
UPtrList< node_type > sorted ()
label countKeys (const UnaryPredicate &pred, const bool invert=false) const
Foam::label countKeys (const UnaryPredicate &pred, const bool invert) const
label countValues (const UnaryPredicate &pred, const bool invert=false) const
Foam::label countValues (const UnaryPredicate &pred, const bool invert) const
label countEntries (const BinaryPredicate &pred, const bool invert=false) const
Foam::label countEntries (const BinaryPredicate &pred, const bool invert) const
bool emplace (const word &key, Args &&... args)
bool emplace_set (const word &key, Args &&... args)
bool insert (const word &key, const regIOobject * &obj)
bool insert (const word &key, regIOobject * &&obj)
bool set (const word &key, const regIOobject * &obj)
bool set (const word &key, regIOobject * &&obj)
bool erase (const iterator &iter)
bool erase (const word &key)
label erase (const HashTable< AnyType, word, AnyHash > &other)
label erase (std::initializer_list< word > keys)
label erase (InputIter first, InputIter last)
label erase (const FixedList< word, N > &keys)
label erase (const UList< word > &keys)
Foam::label erase (InputIter first, InputIter last)
Foam::label erase (const FixedList< word, N > &keys)
Foam::label erase (const HashTable< AnyType, word, AnyHash > &other)
label retain (const HashTable< AnyType, word, AnyHash > &other)
Foam::label retain (const HashTable< AnyType, word, AnyHash > &other)
label filterKeys (const UnaryPredicate &pred, const bool pruning=false)
Foam::label filterKeys (const UnaryPredicate &pred, const bool pruning)
label filterValues (const UnaryPredicate &pred, const bool pruning=false)
Foam::label filterValues (const UnaryPredicate &pred, const bool pruning)
label filterEntries (const BinaryPredicate &pred, const bool pruning=false)
Foam::label filterEntries (const BinaryPredicate &pred, const bool pruning)
void resize (const label sz)
void clear ()
void clearStorage ()
void swap (HashTable< regIOobject *, word, Foam::Hash< word > > &rhs)
void transfer (HashTable< regIOobject *, word, Foam::Hash< word > > &rhs)
void merge (HashTable< regIOobject *, word, Foam::Hash< word > > &source)
void merge (HashTable< regIOobject *, word, Foam::Hash< word > > &&source)
regIOobject * & operator[] (const word &key)
const regIOobject * & operator[] (const word &key) const
regIOobject * & operator() (const word &key)
regIOobject * & operator() (const word &key, const regIOobject * &deflt)
void operator= (const this_type &rhs)
void operator= (std::initializer_list< std::pair< word, regIOobject * > > rhs)
void operator= (this_type &&rhs)
bool operator== (const this_type &rhs) const
bool operator!= (const this_type &rhs) const
this_type & operator+= (const this_type &rhs)
const_iterator_pair< const_key_iterator, this_type > keys () const
iterator begin ()
const_iterator begin () const
const_iterator cbegin () const
iterator end () noexcept
const_iterator end () const noexcept
constexpr const_iterator cend () const noexcept
Ostream & printInfo (Ostream &os) const
Ostream & writeKeys (Ostream &os, const label shortLen=0) const
bool found (const word &key) const
Public Member Functions inherited from HashTableCore
ClassName ("HashTable")
HashTableCore () noexcept=default
Public Member Functions inherited from PrimitivePatch<::Foam::List< face >, pointField >
PrimitivePatch (const ::Foam::List< face > &faces, const pointField &points)
PrimitivePatch (::Foam::List< face > &&faces, const pointField &points)
PrimitivePatch (::Foam::List< face > &faces, pointField &points, const bool reuse)
PrimitivePatch (const PrimitivePatch< ::Foam::List< face >, pointField > &pp)
virtual ~PrimitivePatch ()
void clearOut ()
void clearGeom ()
void clearTopology ()
void clearPatchMeshAddr ()
void swap (PrimitivePatch &)=delete
const Field< point_type > & points () const noexcept
label nFaces () const noexcept
label nPoints () const
label nEdges () const
const edgeList & edges () const
const edgeList::subList internalEdges () const
const edgeList::subList boundaryEdges () const
label nInternalEdges () const
label nBoundaryEdges () const
bool isInternalEdge (const label edgei) const
const labelList & boundaryPoints () const
const labelListList & faceFaces () const
const labelListList & edgeFaces () const
const labelListList & faceEdges () const
const labelListList & pointEdges () const
const labelListList & pointFaces () const
const List< face_type > & localFaces () const
labelList boundaryFaces () const
labelList uniqBoundaryFaces () const
const labelList & meshPoints () const
const Map< label > & meshPointMap () const
const Field< point_type > & localPoints () const
const labelList & localPointOrder () const
label whichPoint (const label gp) const
edge meshEdge (const label edgei) const
edge meshEdge (const edge &e) const
label meshEdge (const label edgei, const edgeList &allEdges, const labelListList &pointEdges) const
label findEdge (const edge &e) const
labelList meshEdges (const edgeList &allEdges, const labelListList &cellEdges, const labelList &faceCells) const
labelList meshEdges (const edgeList &allEdges, const labelListList &pointEdges) const
labelList meshEdges (const labelUList &edgeLabels, const edgeList &allEdges, const labelListList &pointEdges) const
const Field< point_type > & faceCentres () const
const Field< point_type > & faceAreas () const
const Field< scalar > & magFaceAreas () const
const Field< point_type > & faceNormals () const
const Field< point_type > & pointNormals () const
Pair< point_type > box () const
scalar sphere (const label facei) const
bool hasFaceAreas () const
bool hasFaceCentres () const
bool hasFaceNormals () const
bool hasPointNormals () const
bool hasBoundaryPoints () const
bool hasEdges () const
bool hasFaceFaces () const
bool hasEdgeFaces () const
bool hasFaceEdges () const
bool hasPointEdges () const
bool hasPointFaces () const
bool hasMeshPoints () const
bool hasMeshPointMap () const
List< objectHit > projectPoints (const ToPatch &targetPatch, const Field< point_type > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Foam::List< Foam::objectHit > projectPoints (const ToPatch &targetPatch, const Field< typename Foam::PrimitivePatch< ::Foam::List< face >, pointField >::point_type > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
List< objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< point_type > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Foam::List< Foam::objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< typename Foam::PrimitivePatch< ::Foam::List< face >, pointField >::point_type > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
const labelListList & edgeLoops () const
surfaceTopo surfaceType (labelHashSet *badEdgesPtr=nullptr) const
bool checkTopology (const bool report=false, labelHashSet *pointSetPtr=nullptr) const
bool checkPointManifold (const bool report=false, labelHashSet *pointSetPtr=nullptr) const
virtual void movePoints (const Field< point_type > &)
void operator= (const PrimitivePatch< ::Foam::List< face >, pointField > &rhs)
void operator= (PrimitivePatch< ::Foam::List< face >, pointField > &&rhs)
label whichEdge (const edge &e) const
Public Member Functions inherited from PrimitivePatchBase
ClassName ("PrimitivePatch")
PrimitivePatchBase ()=default
Public Member Functions inherited from List< face >
constexpr List () noexcept
List (const label len)
List (const label len, const face &val)
List (const label len, const Foam::zero)
List (const Foam::one, const face &val)
List (const Foam::one, face &&val)
List (const Foam::one, const Foam::zero)
List (const List< face > &a)
List (const UList< face > &a)
List (List< face > &a, bool reuse)
List (const UList< face > &list, const labelUList &indices)
List (const UList< face > &list, const FixedList< label, N > &indices)
List (const FixedList< face, N > &list)
List (const PtrList< face > &list)
List (const SLList< face > &list)
List (const IndirectListBase< face, Addr > &list)
List (std::initializer_list< face > list)
List (List< face > &&list)
List (DynamicList< face, SizeMin > &&list)
List (SLList< face > &&list)
List (Istream &is)
autoPtr< List< face > > clone () const
~List ()
void clear ()
void resize (const label len)
void resize (const label len, const face &val)
void resize (const label newLen)
void resize_nocopy (const label len)
void setSize (const label n)
void setSize (const label n, const face &val)
void transfer (List< face > &list)
void transfer (DynamicList< face, SizeMin > &list)
face & newElmt (const label i)
face & emplace_back (Args &&... args)
void push_back (const face &val)
void push_back (face &&val)
void push_back (const UList< face > &list)
void push_back (const IndirectListBase< face, Addr > &list)
label push_uniq (const face &val)
void pop_back (label n=1)
void operator= (const UList< face > &a)
void operator= (const List< face > &list)
void operator= (const SLList< face > &list)
void operator= (const IndirectListBase< face, Addr > &list)
void operator= (const FixedList< face, N > &list)
void operator= (std::initializer_list< face > list)
void operator= (const face &val)
void operator= (const Foam::zero)
void operator= (List< face > &&list)
void operator= (DynamicList< face, SizeMin > &&list)
void operator= (SLList< face > &&list)
Istream & readList (Istream &is)
Istream & readList (Istream &is)
Istream & readList (Istream &is)
void shallowCopy (const UList< face > &)=delete
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type set (const label i, bool val=true)
void append (const face &val)
void append (face &&val)
void append (const UList< face > &list)
void append (const IndirectListBase< face, Addr > &list)
label appendUniq (const face &val)
Public Member Functions inherited from UList< T >
UList (const UList< T > &)=default
constexpr UList () noexcept
UList (T *__restrict__ v, const label len) noexcept
label fcIndex (const label i) const noexcept
label rcIndex (const label i) const noexcept
const T & fcValue (const label i) const
T & fcValue (const label i)
const T & rcValue (const label i) const
T & rcValue (const label i)
const T * cdata () const noexcept
T * data () noexcept
const char * cdata_bytes () const noexcept
char * data_bytes () noexcept
T & front ()
const T & front () const
T & back ()
const T & back () const
std::streamsize size_bytes () const noexcept
std::streamsize byteSize () const
void checkStart (const label start) const
void checkSize (const label size) const
void checkRange (const label start, const label len) const
void checkIndex (const label i) const
bool uniform () const
label find (const T &val, label pos=0) const
label rfind (const T &val, label pos=-1) const
bool contains (const T &val, label pos=0) const
void moveFirst (const label i)
void moveLast (const label i)
void swapFirst (const label i)
void swapLast (const label i)
void shallowCopy (const UList< T > &list)
void deepCopy (const UList< T > &list)
template<class Addr >
void deepCopy (const IndirectListBase< T, Addr > &list)
SubList< T > slice (const label pos, label len=-1)
const SubList< T > slice (const label pos, label len=-1) const
SubList< T > slice (const labelRange &range)
const SubList< T > slice (const labelRange &range) const
T & operator[] (const label i)
const T & operator[] (const label i) const
operator const Foam::List< T > & () const
void operator= (const T &val)
void operator= (const Foam::zero)
iterator begin () noexcept
iterator end () noexcept
iterator begin (const label i) noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
const_iterator begin () const noexcept
const_iterator end () const noexcept
const_iterator cbegin (const label i) const noexcept
const_iterator begin (const label i) const noexcept
reverse_iterator rbegin ()
reverse_iterator rend ()
const_reverse_iterator crbegin () const
const_reverse_iterator crend () const
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
bool empty () const noexcept
label size () const noexcept
void swap (UList< T > &list)
bool operator== (const UList< T > &a) const
bool operator!= (const UList< T > &a) const
bool operator< (const UList< T > &list) const
bool operator> (const UList< T > &a) const
bool operator<= (const UList< T > &a) const
bool operator>= (const UList< T > &a) const
Istream & readList (Istream &is)
void writeEntry (const word &keyword, Ostream &os) const
Ostream & writeList (Ostream &os, const label shortLen=0) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type test (const label i) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type get (const label i) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type unset (const label i)
T & first ()
const T & first () const
T & last ()
const T & last () const
bool found (const T &val, label pos=0) const
Istream & readList (Istream &is)
Ostream & writeList (Ostream &os, const label) const
const bool & operator[] (const label i) const
UPstream::commsStruct & operator[] (const label procID)
const UPstream::commsStruct & operator[] (const label procID) const
Foam::UPstream::commsStruct & operator[] (const label procID)
const Foam::UPstream::commsStruct & operator[] (const label procID) const
Ostream & writeList (Ostream &os, const label) const
Istream & readList (Istream &is)
Public Member Functions inherited from meshedSurf
constexpr meshedSurf () noexcept=default
virtual ~meshedSurf ()=default
virtual const labelList & faceIds () const
Static Public Attributes
static const word pointDataName
Static Public Attributes inherited from IOobject
static const Enum< fileCheckTypes > fileCheckTypesNames
static char scopeSeparator
static fileCheckTypes fileModificationChecking
static float fileModificationSkew
static int maxFileModificationPolls
Static Public Attributes inherited from HashTableCore
static const label maxTableSize
Protected Member Functions
pointField & storedPoints ()
faceList & storedFaces ()
const faceList & storedFaces () const
Protected Member Functions inherited from regIOobject
bool readHeaderOk (const IOstreamOption::streamFormat fmt, const word &typeName)
Protected Member Functions inherited from IOobject
void setBad (const string &s)
Protected Member Functions inherited from UList< T >
void setAddressableSize (const label n) noexcept
void size (const label n)
void writeEntry (Ostream &os) const
labelRange validateRange (const labelRange &requestedRange) const
UList< T > & operator= (const UList< T > &)=delete
void writeEntry (Ostream &os) const
void writeEntry (Ostream &os) const
Additional Inherited Members
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *p)
template<class Type >
static Type & store (autoPtr< Type > &ptr)
template<class Type >
static Type & store (autoPtr< Type > &&ptr)
template<class Type >
static Type & store (refPtr< Type > &ptr)
template<class Type >
static Type & store (refPtr< Type > &&ptr)
template<class Type >
static Type & store (tmp< Type > &ptr)
template<class Type >
static Type & store (tmp< Type > &&ptr)
Static Public Member Functions inherited from IOobject
static bool bannerEnabled () noexcept
static bool bannerEnabled (bool on) noexcept
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
template<class StringType >
static word groupName (StringType base, const word &group)
static word group (const word &name)
static word member (const word &name)
static word scopedName (const std::string &scope, const word &name)
static IOobject selectIO (const IOobject &io, const fileName &altFile, const word &ioName="")
static Ostream & writeBanner (Ostream &os, const bool noSyntaxHint=false)
static Ostream & writeDivider (Ostream &os)
static Ostream & writeEndDivider (Ostream &os)
Static Public Member Functions inherited from IOobjectOption
static bool isAnyRead (readOption opt) noexcept
static bool isReadRequired (readOption opt) noexcept
static bool isReadOptional (readOption opt) noexcept
static readOption lazierRead (readOption opt) noexcept
Static Public Member Functions inherited from HashTableCore
static label canonicalSize (const label requested_size)
Static Public Member Functions inherited from List< face >
static const List< face > & null ()
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
static constexpr label max_size () noexcept
Static Protected Member Functions inherited from IOobject
static void writeHeaderContent (Ostream &os, const IOobject &io, const word &objectType, const dictionary *metaDataDict=nullptr)
static void writeHeaderContent (dictionary &dict, const IOobject &io, const word &objectType, IOstreamOption streamOpt, const dictionary *metaDataDict=nullptr)
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
Detailed Description
A surface mesh consisting of general polygon faces and capable of holding fields.
Source files
polySurface.H
polySurface.C
polySurfaceClear.C
polySurfaceIO.C
polySurfaceTemplates.C
Definition at line 62 of file polySurface.H.
Member Typedef Documentation
Mesh
typedef polySurface Mesh
Definition at line 139 of file polySurface.H.
BoundaryMesh
typedef bool BoundaryMesh
Definition at line 142 of file polySurface.H.
Member Enumeration Documentation
FieldAssociation
enum FieldAssociation
Enumerator
NO_DATA
No associated data.
FACE_DATA
Data associated with faces.
POINT_DATA
Data associated with points.
FACE_OR_POINT_DATA
Data associated with faces or points.
Definition at line 71 of file polySurface.H.
Constructor & Destructor Documentation
polySurface() [1/4]
polySurface (const IOobject & io, bool doCheckIn = false) explicit
Definition at line 78 of file polySurface.C.
References regIOobject::store().
polySurface() [2/4]
polySurface (const word & surfName, const objectRegistry & obr, bool doCheckIn = false)
Definition at line 104 of file polySurface.C.
polySurface() [3/4]
polySurface (const IOobject & io, const MeshedSurface< face > & surf, bool doCheckIn = false)
Definition at line 127 of file polySurface.C.
References polySurface::copySurface().
polySurface() [4/4]
polySurface (const IOobject & io, MeshedSurface< face > && surf, bool doCheckIn = false)
Definition at line 140 of file polySurface.C.
References polySurface::transfer().
~polySurface()
~polySurface () virtual
clearOut(); // Clear addressing
Definition at line 155 of file polySurface.C.
Member Function Documentation
storedPoints()
pointField & storedPoints () inline protected
Definition at line 112 of file polySurface.H.
References PrimitivePatch<::Foam::List< face >, pointField >::points().
storedFaces() [1/2]
faceList & storedFaces () inline protected
Definition at line 118 of file polySurface.H.
Referenced by polySurface::faces().
storedFaces() [2/2]
const faceList & storedFaces () const inline protected
Definition at line 124 of file polySurface.H.
TypeName()
TypeName ("polySurface")
nPoints()
virtual label nPoints () const inline virtual
Definition at line 209 of file polySurface.H.
References PrimitivePatch<::Foam::List< face >, pointField >::points(), and UPtrList< T >::size().
nFaces()
virtual label nFaces () const inline virtual
Definition at line 215 of file polySurface.H.
References UList< T >::size().
size()
virtual label size () const inline virtual
Definition at line 221 of file polySurface.H.
References UList< T >::size().
points()
virtual const pointField & points () const inline virtual
Implements meshedSurf.
Definition at line 228 of file polySurface.H.
References PrimitivePatch<::Foam::List< face >, pointField >::points().
faces()
virtual const faceList & faces () const inline virtual
Implements meshedSurf.
Definition at line 234 of file polySurface.H.
References polySurface::storedFaces().
zoneIds()
virtual const labelList & zoneIds () const inline virtual
Reimplemented from meshedSurf.
Definition at line 240 of file polySurface.H.
Sf()
const vectorField & Sf () const inline
Definition at line 246 of file polySurface.H.
References PrimitivePatch<::Foam::List< face >, pointField >::faceAreas().
magSf()
const scalarField & magSf () const inline
Definition at line 252 of file polySurface.H.
References PrimitivePatch<::Foam::List< face >, pointField >::magFaceAreas().
Cf()
const vectorField & Cf () const inline
Definition at line 258 of file polySurface.H.
References PrimitivePatch<::Foam::List< face >, pointField >::faceCentres().
copySurface() [1/3]
void copySurface (const pointField & points, const faceList & faces, bool unused = false)
Definition at line 272 of file polySurface.C.
References List< T >::clear(), nPoints, points, and UList< T >::size().
Referenced by polySurface::polySurface().
copySurface() [2/3]
void copySurface (const meshedSurf & surf, bool unused = false)
Definition at line 303 of file polySurface.C.
References meshedSurf::faces(), nPoints, meshedSurf::points(), UPtrList< T >::size(), and meshedSurf::zoneIds().
copySurface() [3/3]
void copySurface (const MeshedSurface< face > & surf, bool unused = false)
Definition at line 333 of file polySurface.C.
References nPoints, and UPtrList< T >::size().
transfer() [1/2]
void transfer (pointField && points, faceList && faces, labelList && zoneIds = labelList())
Definition at line 363 of file polySurface.C.
References points.
Referenced by polySurface::polySurface().
transfer() [2/2]
void transfer (MeshedSurface< face > & surf, bool validate = false)
Definition at line 379 of file polySurface.C.
nFaceData()
Foam::label nFaceData () const
Definition at line 163 of file polySurface.C.
References HashTable< regIOobject * >::size().
nPointData()
Foam::label nPointData () const
Definition at line 177 of file polySurface.C.
References UPtrList< T >::size().
queryFieldAssociation()
Foam::polySurface::FieldAssociation queryFieldAssociation (const word & fieldName) const
Definition at line 205 of file polySurface.C.
findFieldObject() [1/7]
const Foam::regIOobject * findFieldObject (const word & fieldName, const FieldAssociation association) const
Definition at line 234 of file polySurface.C.
findFieldObject() [2/7]
template<class GeoMeshType = void> const regIOobject * findFieldObject (const word & fieldName) const
whichRegistry() [1/6]
template<class GeoMeshType = void> const objectRegistry * whichRegistry (const word & fieldName) const
fieldData() [1/2]
template<class DataType > const objectRegistry & fieldData () const inline
Definition at line 342 of file polySurface.H.
faceData()
const Foam::objectRegistry & faceData () const
Definition at line 191 of file polySurface.C.
pointData()
const Foam::objectRegistry & pointData () const
Definition at line 197 of file polySurface.C.
References objectRegistry::subRegistry().
Referenced by polySurface::fieldData().
storeField() [1/2]
template<class Type , class GeoMeshType > void storeField (const word & fieldName, const dimensionSet & dims, const Field< Type > & values)
Definition at line 87 of file polySurfaceTemplates.C.
References IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, and IOobjectOption::REGISTER.
storeField() [2/2]
template<class Type , class GeoMeshType > void storeField (const word & fieldName, const dimensionSet & dims, Field< Type > && values)
Definition at line 128 of file polySurfaceTemplates.C.
References IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, and IOobjectOption::REGISTER.
writeObject()
bool writeObject (IOstreamOption streamOpt, const bool writeOnProc) const virtual
Reimplemented from objectRegistry.
Definition at line 25 of file polySurfaceIO.C.
clearGeom()
void clearGeom ()
Definition at line 26 of file polySurfaceClear.C.
References PrimitivePatch<::Foam::List< face >, pointField >::clearGeom(), DebugInFunction, and Foam::endl().
clearAddressing()
void clearAddressing ()
Definition at line 34 of file polySurfaceClear.C.
References DebugInFunction, and Foam::endl().
clearOut()
void clearOut ()
Definition at line 42 of file polySurfaceClear.C.
clearPrimitives()
void clearPrimitives ()
clearFields()
void clearFields ()
Definition at line 51 of file polySurfaceClear.C.
References objectRegistry::clear().
findFieldObject() [3/7]
template<> const regIOobject * findFieldObject (const word & fieldName) const
Definition at line 444 of file polySurface.C.
findFieldObject() [4/7]
template<> const regIOobject * findFieldObject (const word & fieldName) const
Definition at line 455 of file polySurface.C.
References polySurface::pointDataName.
whichRegistry() [2/6]
template<> const objectRegistry * whichRegistry (const word & fieldName) const
Definition at line 476 of file polySurface.C.
whichRegistry() [3/6]
template<> const objectRegistry * whichRegistry (const word & fieldName) const
Definition at line 494 of file polySurface.C.
References polySurface::pointDataName.
findFieldObject() [5/7]
template<> const regIOobject * findFieldObject (const word & fieldName) const
findFieldObject() [6/7]
template<> const regIOobject * findFieldObject (const word & fieldName) const
whichRegistry() [4/6]
template<> const objectRegistry * whichRegistry (const word & fieldName) const
whichRegistry() [5/6]
template<> const objectRegistry * whichRegistry (const word & fieldName) const
fieldData() [2/2]
template<> const objectRegistry & fieldData () const inline
Definition at line 457 of file polySurface.H.
References polySurface::pointData().
findFieldObject() [7/7]
template<class GeoMeshType > const Foam::regIOobject * findFieldObject (const word & fieldName) const
Definition at line 27 of file polySurfaceTemplates.C.
References objectRegistry::cfindObject(), and forAllConstIters.
whichRegistry() [6/6]
template<class GeoMeshType > const Foam::objectRegistry * whichRegistry (const word & fieldName) const
Definition at line 58 of file polySurfaceTemplates.C.
References forAllConstIters, and objectRegistry::found().
Member Data Documentation
pointDataName
const Foam::word pointDataName static
Definition at line 145 of file polySurface.H.
Referenced by polySurface::findFieldObject(), and polySurface::whichRegistry().
The documentation for this class was generated from the following files:
src/surfMesh/polySurface/polySurface.H
src/surfMesh/polySurface/polySurface.C
src/surfMesh/polySurface/polySurfaceClear.C
src/surfMesh/polySurface/polySurfaceIO.C
src/surfMesh/polySurface/polySurfaceTemplates.C