OpenFOAM: DeltaOmegaTildeDelta Class Reference
DeltaOmegaTildeDelta Class Reference
Delta formulation that accounts for the orientation of the vorticity vector. In "2D-regions" (i.e. xy-plane), delta is of the order max(delta_x,delta_y), so that the influence of delta_z is discarded. This can help to accelerate the transition from RANS to LES in hybrid RANS/LES simulations.
#include <DeltaOmegaTildeDelta.H>
Public Member Functions
TypeName ("DeltaOmegaTilde")
DeltaOmegaTildeDelta (const word &name, const turbulenceModel &turbulence, const dictionary &)
virtual ~DeltaOmegaTildeDelta ()=default
virtual void read (const dictionary &)
const volScalarField & hmax () const
void correct ()
Public Member Functions inherited from LESdelta
TypeName ("LESdelta")
declareRunTimeSelectionTable (autoPtr, LESdelta, dictionary,(const word &name, const turbulenceModel &turbulence, const dictionary &dict),(name, turbulence, dict))
LESdelta (const word &name, const turbulenceModel &turbulence)
virtual ~LESdelta ()=default
const turbulenceModel & turbulence () const
virtual operator const volScalarField & () const
Additional Inherited Members
Static Public Member Functions inherited from LESdelta
static autoPtr< LESdelta > New (const word &name, const turbulenceModel &turbulence, const dictionary &dict, const word &lookupName="delta")
static autoPtr< LESdelta > New (const word &name, const turbulenceModel &turbulence, const dictionary &dict, const dictionaryConstructorTableType &additionalConstructors, const word &lookupName="delta")
Protected Member Functions inherited from LESdelta
LESdelta (const LESdelta &)=delete
void operator= (const LESdelta &)=delete
Protected Attributes inherited from LESdelta
const turbulenceModel & turbulenceModel_
volScalarField delta_
Detailed Description
Delta formulation that accounts for the orientation of the vorticity vector. In "2D-regions" (i.e. xy-plane), delta is of the order max(delta_x,delta_y), so that the influence of delta_z is discarded. This can help to accelerate the transition from RANS to LES in hybrid RANS/LES simulations.
Reference:
    Shur, M. L., Spalart, P. R., Strelets, M. K., & Travin, A. K. (2015).
    An enhanced version of DES with rapid transition
    from RANS to LES in separated flows.
    Flow, turbulence and combustion, 95(4), 709-737.
    DOI:10.1007/s10494-015-9618-0
Source files
DeltaOmegaTildeDelta.H
DeltaOmegaTildeDelta.C
Definition at line 62 of file DeltaOmegaTildeDelta.H.
Constructor & Destructor Documentation
DeltaOmegaTildeDelta()
DeltaOmegaTildeDelta (const word & name, const turbulenceModel & turbulence, const dictionary & dict)
Definition at line 108 of file DeltaOmegaTildeDelta.C.
References dict, Foam::endl(), found, IOobject::groupName(), Foam::Info, LESdelta::New(), turbulence, LESdelta::turbulence(), and Foam::type().
~DeltaOmegaTildeDelta()
virtual ~DeltaOmegaTildeDelta () virtual default
Member Function Documentation
TypeName()
TypeName ("DeltaOmegaTilde")
read()
void read (const dictionary & dict) virtual
Implements LESdelta.
Definition at line 167 of file DeltaOmegaTildeDelta.C.
References dict, dictionary::optionalSubDict(), dictionary::readIfPresent(), and Foam::type().
hmax()
const volScalarField & hmax () const inline
Definition at line 118 of file DeltaOmegaTildeDelta.H.
correct()
void correct () virtual
Implements LESdelta.
Definition at line 178 of file DeltaOmegaTildeDelta.C.
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/LES/LESdeltas/DeltaOmegaTildeDelta/DeltaOmegaTildeDelta.H
src/TurbulenceModels/turbulenceModels/LES/LESdeltas/DeltaOmegaTildeDelta/DeltaOmegaTildeDelta.C