OpenFOAM: filmPyrolysisTemperatureCoupledFvPatchScalarField Class Reference
filmPyrolysisTemperatureCoupledFvPatchScalarField Class Reference
This boundary condition is designed to be used in conjunction with surface film and pyrolysis modelling. It provides a temperature boundary condition for patches on the primary region based on whether the patch is seen to be 'wet', retrieved from the film alpha field.
#include <filmPyrolysisTemperatureCoupledFvPatchScalarField.H>
Public Member Functions
TypeName ("filmPyrolysisTemperatureCoupled")
filmPyrolysisTemperatureCoupledFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
filmPyrolysisTemperatureCoupledFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
filmPyrolysisTemperatureCoupledFvPatchScalarField (const filmPyrolysisTemperatureCoupledFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
filmPyrolysisTemperatureCoupledFvPatchScalarField (const filmPyrolysisTemperatureCoupledFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
filmPyrolysisTemperatureCoupledFvPatchScalarField (const filmPyrolysisTemperatureCoupledFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
const word & phiName () const
word & phiName ()
const word & rhoName () const
word & rhoName ()
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
This boundary condition is designed to be used in conjunction with surface film and pyrolysis modelling. It provides a temperature boundary condition for patches on the primary region based on whether the patch is seen to be 'wet', retrieved from the film alpha field.
if the patch is wet, the temperature is set using the film temperature
otherwise, it is set using pyrolysis temperature
Example of the boundary condition specification:
<patchName>
{
    type            filmPyrolysisTemperatureCoupled;
    phi             phi;      // name of flux field (default = phi)
    rho             rho;      // name of density field (default = rho)
    deltaWet        1e-4;     // threshold height for 'wet' film
    value           uniform   300; // initial temperature / [K]
}
Source files
filmPyrolysisTemperatureCoupledFvPatchScalarField.H
filmPyrolysisTemperatureCoupledFvPatchScalarField.C
Definition at line 64 of file filmPyrolysisTemperatureCoupledFvPatchScalarField.H.
Constructor & Destructor Documentation
filmPyrolysisTemperatureCoupledFvPatchScalarField() [1/5]
filmPyrolysisTemperatureCoupledFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 30 of file filmPyrolysisTemperatureCoupledFvPatchScalarField.C.
filmPyrolysisTemperatureCoupledFvPatchScalarField() [2/5]
filmPyrolysisTemperatureCoupledFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 62 of file filmPyrolysisTemperatureCoupledFvPatchScalarField.C.
filmPyrolysisTemperatureCoupledFvPatchScalarField() [3/5]
filmPyrolysisTemperatureCoupledFvPatchScalarField (const filmPyrolysisTemperatureCoupledFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 45 of file filmPyrolysisTemperatureCoupledFvPatchScalarField.C.
filmPyrolysisTemperatureCoupledFvPatchScalarField() [4/5]
filmPyrolysisTemperatureCoupledFvPatchScalarField (const filmPyrolysisTemperatureCoupledFvPatchScalarField & fptpsf)
Definition at line 84 of file filmPyrolysisTemperatureCoupledFvPatchScalarField.C.
filmPyrolysisTemperatureCoupledFvPatchScalarField() [5/5]
filmPyrolysisTemperatureCoupledFvPatchScalarField (const filmPyrolysisTemperatureCoupledFvPatchScalarField & fptpsf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 98 of file filmPyrolysisTemperatureCoupledFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("filmPyrolysisTemperatureCoupled")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 123 of file filmPyrolysisTemperatureCoupledFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 139 of file filmPyrolysisTemperatureCoupledFvPatchScalarField.H.
phiName() [1/2]
const word & phiName () const inline
Definition at line 156 of file filmPyrolysisTemperatureCoupledFvPatchScalarField.H.
phiName() [2/2]
word & phiName () inline
Definition at line 162 of file filmPyrolysisTemperatureCoupledFvPatchScalarField.H.
rhoName() [1/2]
const word & rhoName () const inline
Definition at line 168 of file filmPyrolysisTemperatureCoupledFvPatchScalarField.H.
rhoName() [2/2]
word & rhoName () inline
Definition at line 174 of file filmPyrolysisTemperatureCoupledFvPatchScalarField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 115 of file filmPyrolysisTemperatureCoupledFvPatchScalarField.C.
References UPstream::msgType().
write()
void write (Ostream & os) const virtual
Definition at line 178 of file filmPyrolysisTemperatureCoupledFvPatchScalarField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntryIfDifferent(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/regionModels/regionCoupling/derivedFvPatchFields/filmPyrolysisTemperatureCoupled/filmPyrolysisTemperatureCoupledFvPatchScalarField.H
src/regionModels/regionCoupling/derivedFvPatchFields/filmPyrolysisTemperatureCoupled/filmPyrolysisTemperatureCoupledFvPatchScalarField.C