OpenFOAM: AtomizationModel< CloudType > Class Template Reference
AtomizationModel< CloudType > Class Template Reference abstract
Lagrangian particle models » Submodels » Reacting » Atomization
Templated atomization model class.
#include <AtomizationModel.H>
Public Member Functions
TypeName ("atomizationModel")
declareRunTimeSelectionTable (autoPtr, AtomizationModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
AtomizationModel (CloudType &owner)
AtomizationModel (const dictionary &dict, CloudType &owner, const word &type)
AtomizationModel (const AtomizationModel< CloudType > &am)
virtual autoPtr< AtomizationModel< CloudType > > clone () const =0
virtual ~AtomizationModel ()
scalar Taverage (const scalar &Tliq, const scalar &Tc) const
virtual scalar initLiquidCore () const =0
virtual bool calcChi () const =0
virtual void update (const scalar dt, scalar &d, scalar &liquidCore, scalar &tc, const scalar rho, const scalar mu, const scalar sigma, const scalar volFlowRate, const scalar rhoAv, const scalar Urel, const vector &pos, const vector &injectionPos, const scalar pAmbient, const scalar chi, Random &rndGen) const =0
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
virtual ~CloudSubModelBase ()=default
const CloudType & owner () const
virtual bool writeTime () const
virtual fileName localPath () const
CloudType & owner ()
virtual void info ()
virtual void write (Ostream &os) const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
subModelBase (const subModelBase &smb)
virtual ~subModelBase ()=default
const word & modelName () const
const dictionary & dict () const
const word & baseName () const
const word & modelType () const
const dictionary & coeffDict () const
const dictionary & properties () const
virtual bool defaultCoeffs (const bool printMsg) const
virtual bool active () const
virtual void cacheFields (const bool store)
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
bool getModelDict (const word &entryName, dictionary &dict) const
template<class Type >
bool getModelProperty (const word &entryName, Type &value) const
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Static Public Member Functions
static autoPtr< AtomizationModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Additional Inherited Members
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Public Attributes inherited from subModelBase
bool log
Protected Member Functions inherited from subModelBase
bool inLine () const
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Protected Attributes inherited from subModelBase
const word modelName_
dictionary & properties_
const dictionary dict_
const word baseName_
const word modelType_
const dictionary coeffDict_
Detailed Description
template<class CloudType>
class Foam::AtomizationModel< CloudType >
Templated atomization model class.
Source files
AtomizationModel.H
AtomizationModel.C
AtomizationModelNew.C
Definition at line 54 of file AtomizationModel.H.
Constructor & Destructor Documentation
AtomizationModel() [1/3]
template<class CloudType > AtomizationModel (CloudType & owner)
Definition at line 26 of file AtomizationModel.C.
AtomizationModel() [2/3]
template<class CloudType > AtomizationModel (const dictionary & dict, CloudType & owner, const word & type)
Definition at line 46 of file AtomizationModel.C.
AtomizationModel() [3/3]
template<class CloudType > AtomizationModel (const AtomizationModel< CloudType > & am)
Definition at line 36 of file AtomizationModel.C.
~AtomizationModel()
template<class CloudType > ~AtomizationModel () virtual
Definition at line 60 of file AtomizationModel.C.
Member Function Documentation
TypeName()
template<class CloudType > TypeName ("atomizationModel")
declareRunTimeSelectionTable()
template<class CloudType > declareRunTimeSelectionTable (autoPtr , AtomizationModel< CloudType > , dictionary , (const dictionary &dict, CloudType &owner) , (dict, owner))
clone()
template<class CloudType > virtual autoPtr< AtomizationModel< CloudType > > clone () const pure virtual
Implemented in BlobsSheetAtomization< CloudType >, LISAAtomization< CloudType >, and NoAtomization< CloudType >.
New()
template<class CloudType > Foam::autoPtr< Foam::AtomizationModel< CloudType > > New (const dictionary & dict, CloudType & owner) static
Definition at line 28 of file AtomizationModelNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, Foam::Info, and PtrList< T >::PtrList().
Taverage()
template<class CloudType > Foam::scalar Taverage (const scalar & Tliq, const scalar & Tc) const
Definition at line 67 of file AtomizationModel.C.
initLiquidCore()
template<class CloudType > virtual scalar initLiquidCore () const pure virtual
Implemented in BlobsSheetAtomization< CloudType >, LISAAtomization< CloudType >, and NoAtomization< CloudType >.
calcChi()
template<class CloudType > virtual bool calcChi () const pure virtual
Implemented in BlobsSheetAtomization< CloudType >, LISAAtomization< CloudType >, and NoAtomization< CloudType >.
update()
template<class CloudType > virtual void update (const scalar dt, scalar & d, scalar & liquidCore, scalar & tc, const scalar rho, const scalar mu, const scalar sigma, const scalar volFlowRate, const scalar rhoAv, const scalar Urel, const vector & pos, const vector & injectionPos, const scalar pAmbient, const scalar chi, Random & rndGen) const pure virtual
Implemented in BlobsSheetAtomization< CloudType >, LISAAtomization< CloudType >, and NoAtomization< CloudType >.
The documentation for this class was generated from the following files:
src/lagrangian/spray/clouds/Templates/SprayCloud/SprayCloud.H
src/lagrangian/spray/submodels/AtomizationModel/AtomizationModel/AtomizationModel.H
src/lagrangian/spray/submodels/AtomizationModel/AtomizationModel/AtomizationModel.C
src/lagrangian/spray/submodels/AtomizationModel/AtomizationModel/AtomizationModelNew.C