OpenFOAM: DSMCParcel< ParcelType > Class Template Reference
DSMCParcel< ParcelType > Class Template Reference
DSMC parcel class.
#include <DSMCParcel.H>
Classes
class constantProperties
class iNew
Public Types
typedef ParcelType::trackingData trackingData
Public Member Functions
TypeName ("DSMCParcel")
DSMCParcel (const polyMesh &mesh, const barycentric &coordinates, const label celli, const label tetFacei, const label tetPti, const vector &U, const scalar Ei, const label typeId)
DSMCParcel (const polyMesh &mesh, const vector &position, const label celli, const vector &U, const scalar Ei, const label typeId)
DSMCParcel (const polyMesh &mesh, Istream &is, bool readFields=true, bool newFormat=true)
virtual autoPtr< particle > clone () const
label typeId () const
const vector & U () const
scalar Ei () const
vector & U ()
scalar & Ei ()
template<class TrackCloudType >
bool move (TrackCloudType &cloud, trackingData &td, const scalar trackTime)
template<class TrackCloudType >
bool hitPatch (TrackCloudType &, trackingData &)
template<class TrackCloudType >
void hitProcessorPatch (TrackCloudType &, trackingData &)
template<class TrackCloudType >
void hitWallPatch (TrackCloudType &, trackingData &)
virtual void transformProperties (const tensor &T)
virtual void transformProperties (const vector &separation)
Static Public Member Functions
static void readFields (Cloud< DSMCParcel< ParcelType > > &c)
static void writeFields (const Cloud< DSMCParcel< ParcelType > > &c)
Static Public Attributes
static const std::size_t sizeofFields
Protected Attributes
vector U_
scalar Ei_
label typeId_
Friends
class Cloud< ParcelType >
Ostream & operator<< (Ostream &, const DSMCParcel< ParcelType > &)
Detailed Description
template<class ParcelType>
class Foam::DSMCParcel< ParcelType >
DSMC parcel class.
Source files
DSMCParcel.H
DSMCParcelI.H
DSMCParcel.C
DSMCParcelIO.C
Definition at line 66 of file DSMCParcel.H.
Member Typedef Documentation
trackingData
template<class ParcelType > typedef ParcelType::trackingData trackingData
Definition at line 127 of file DSMCParcel.H.
Constructor & Destructor Documentation
DSMCParcel() [1/3]
template<class ParcelType > DSMCParcel (const polyMesh & mesh, const barycentric & coordinates, const label celli, const label tetFacei, const label tetPti, const vector & U, const scalar Ei, const label typeId) inline
Definition at line 47 of file DSMCParcelI.H.
DSMCParcel() [2/3]
template<class ParcelType > DSMCParcel (const polyMesh & mesh, const vector & position, const label celli, const vector & U, const scalar Ei, const label typeId) inline
Definition at line 67 of file DSMCParcelI.H.
DSMCParcel() [3/3]
template<class ParcelType > DSMCParcel (const polyMesh & mesh, Istream & is, bool readFields = true, bool newFormat = true)
Definition at line 39 of file DSMCParcelIO.C.
References IOstreamOption::ASCII, VectorSpace< Form, Cmpt, Ncmpts >::data(), DSMCParcel< ParcelType >::Ei_, FUNCTION_NAME, VectorSpace< Form, Cmpt, Ncmpts >::nComponents, DSMCParcel< ParcelType >::readFields(), Foam::readFields(), Foam::readRawLabel(), DSMCParcel< ParcelType >::sizeofFields, DSMCParcel< ParcelType >::typeId_, and DSMCParcel< ParcelType >::U_.
Member Function Documentation
TypeName()
template<class ParcelType > TypeName ("DSMCParcel< ParcelType >")
clone()
template<class ParcelType > virtual autoPtr< particle > clone () const inline virtual
Definition at line 192 of file DSMCParcel.H.
typeId()
template<class ParcelType > Foam::label typeId () const inline
Definition at line 129 of file DSMCParcelI.H.
U() [1/2]
template<class ParcelType > const Foam::vector & U () const inline
Definition at line 136 of file DSMCParcelI.H.
Ei() [1/2]
template<class ParcelType > Foam::scalar Ei () const inline
Definition at line 143 of file DSMCParcelI.H.
U() [2/2]
template<class ParcelType > Foam::vector & U () inline
Definition at line 150 of file DSMCParcelI.H.
Ei() [2/2]
template<class ParcelType > Foam::scalar & Ei () inline
Definition at line 157 of file DSMCParcelI.H.
move()
template<class ParcelType > template<class TrackCloudType > bool move (TrackCloudType & cloud, trackingData & td, const scalar trackTime)
Definition at line 28 of file DSMCParcel.C.
References Foam::meshTools::constrainDirection(), f(), mesh, and p.
hitPatch()
template<class ParcelType > template<class TrackCloudType > bool hitPatch (TrackCloudType & , trackingData &)
Definition at line 70 of file DSMCParcel.C.
hitProcessorPatch()
template<class ParcelType > template<class TrackCloudType > void hitProcessorPatch (TrackCloudType & , trackingData & td)
Definition at line 78 of file DSMCParcel.C.
hitWallPatch()
template<class ParcelType > template<class TrackCloudType > void hitWallPatch (TrackCloudType & cloud, trackingData &)
Definition at line 90 of file DSMCParcel.C.
References polyMesh::boundaryMesh(), DSMCParcel< ParcelType >::constantProperties::internalDegreesOfFreedom(), Foam::mag(), DSMCParcel< ParcelType >::constantProperties::mass(), Foam::max(), mesh, Foam::normalised(), and objectRegistry::time().
transformProperties() [1/2]
template<class ParcelType > void transformProperties (const tensor & T) virtual
Definition at line 181 of file DSMCParcel.C.
References T, and Foam::transform().
transformProperties() [2/2]
template<class ParcelType > void transformProperties (const vector & separation) virtual
Definition at line 189 of file DSMCParcel.C.
readFields()
template<class ParcelType > void readFields (Cloud< DSMCParcel< ParcelType > > & c) static
Definition at line 81 of file DSMCParcelIO.C.
References IOobjectOption::MUST_READ, p, UPtrList< T >::size(), and U.
Referenced by DSMCParcel< ParcelType >::DSMCParcel().
writeFields()
template<class ParcelType > void writeFields (const Cloud< DSMCParcel< ParcelType > > & c) static
Definition at line 112 of file DSMCParcelIO.C.
References IOobjectOption::NO_READ, p, UPtrList< T >::size(), and U.
Friends And Related Symbol Documentation
Cloud< ParcelType >
template<class ParcelType > friend class Cloud< ParcelType > friend
Definition at line 150 of file DSMCParcel.H.
operator<<
template<class ParcelType > Ostream & operator<< (Ostream & , const DSMCParcel< ParcelType > &) friend
Member Data Documentation
sizeofFields
template<class ParcelType > const std::size_t sizeofFields static
Definition at line 73 of file DSMCParcel.H.
Referenced by DSMCParcel< ParcelType >::DSMCParcel().
U_
template<class ParcelType > vector U_ protected
Definition at line 137 of file DSMCParcel.H.
Referenced by DSMCParcel< ParcelType >::DSMCParcel().
Ei_
template<class ParcelType > scalar Ei_ protected
Definition at line 141 of file DSMCParcel.H.
Referenced by DSMCParcel< ParcelType >::DSMCParcel().
typeId_
template<class ParcelType > label typeId_ protected
Definition at line 144 of file DSMCParcel.H.
Referenced by DSMCParcel< ParcelType >::DSMCParcel().
The documentation for this class was generated from the following files:
src/lagrangian/DSMC/parcels/Templates/DSMCParcel/DSMCParcel.H
src/lagrangian/DSMC/parcels/Templates/DSMCParcel/DSMCParcel.C
src/lagrangian/DSMC/parcels/Templates/DSMCParcel/DSMCParcelI.H
src/lagrangian/DSMC/parcels/Templates/DSMCParcel/DSMCParcelIO.C