OpenFOAM: BrunDrippingInjection Class Reference
BrunDrippingInjection Class Reference
Film-dripping mass-transfer model.
#include <BrunDrippingInjection.H>
Public Member Functions
TypeName ("BrunDrippingInjection")
BrunDrippingInjection (liquidFilmBase &film, const dictionary &dict)
virtual ~BrunDrippingInjection ()=default
virtual void correct (scalarField &availableMass, scalarField &massToInject, scalarField &diameterToInject)
Public Member Functions inherited from injectionModel
TypeName ("injectionModel")
declareRunTimeSelectionTable (autoPtr, injectionModel, dictionary,(liquidFilmBase &film, const dictionary &dict),(film, dict))
injectionModel (liquidFilmBase &film)
injectionModel (const word &modelType, liquidFilmBase &film, const dictionary &dict)
virtual ~injectionModel ()
virtual scalar injectedMassTotal () const
virtual void patchInjectedMassTotals (scalar &patchMasses) const
Public Member Functions inherited from filmSubModelBase
filmSubModelBase (liquidFilmBase &film)
filmSubModelBase (liquidFilmBase &film, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
filmSubModelBase (const word &modelName, liquidFilmBase &film, const dictionary &dict, const word &baseName, const word &modelType)
virtual ~filmSubModelBase ()
virtual bool writeTime () const
const liquidFilmBase & film () const
liquidFilmBase & film ()
template<class FilmType >
const FilmType & filmType () const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
subModelBase (const subModelBase &smb)
virtual ~subModelBase ()=default
const word & modelName () const
const dictionary & dict () const
const word & baseName () const
const word & modelType () const
const dictionary & coeffDict () const
const dictionary & properties () const
virtual bool defaultCoeffs (const bool printMsg) const
virtual bool active () const
virtual void cacheFields (const bool store)
virtual fileName localPath () const
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
bool getModelDict (const word &entryName, dictionary &dict) const
template<class Type >
bool getModelProperty (const word &entryName, Type &value) const
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
virtual void write (Ostream &os) const
Protected Attributes
scalar ubarStar_
scalar dCoeff_
scalar deltaStable_
scalarList diameter_
Protected Attributes inherited from filmSubModelBase
liquidFilmBase & filmModel_
Protected Attributes inherited from subModelBase
const word modelName_
dictionary & properties_
const dictionary dict_
const word baseName_
const word modelType_
const dictionary coeffDict_
Additional Inherited Members
Static Public Member Functions inherited from injectionModel
static autoPtr< injectionModel > New (liquidFilmBase &film, const dictionary &dict, const word &mdoelType)
Public Attributes inherited from subModelBase
bool log
Protected Member Functions inherited from injectionModel
void addToInjectedMass (const scalar dMass)
void correct ()
Protected Member Functions inherited from subModelBase
bool inLine () const
Detailed Description
Film-dripping mass-transfer model.
If the film thickness exceeds the critical value needed to generate one or more drops, the equivalent mass is removed from the film. The critical film thickness is calculated from the Rayleigh-Taylor stability analysis of film flow on an inclined plane, proposed by (Brun et. al., 2015).
Reference:
    Brun, P. T., Damiano, A., Rieu, P., Balestra, G., & Gallaire, F. (2015).
    Rayleigh-Taylor instability under an inclined plane.
    Physics of Fluids, 27(8), 084107.
    DOI:10.1063/1.4927857
The diameter of the drops formed are obtained from the local capillary length multiplied by the dCoeff coefficient.
Reference:
    Lefebvre, A. (1988).
    Atomization and sprays
    (Vol. 1040, No. 2756). CRC press.
Usage
Minimal example:
injectionModels
(
    BrunDrippingInjection
);
BrunDrippingInjectionCoeffs
{
    // Optional entries
    ubarStar        <scalar>;
    dCoeff          <scalar>;
    deltaStable     <scalar>;
}
where the entries mean:
Property Description Type Reqd Deflt
type Type name: BrunDrippingInjection word yes -
ubarStar
Critical non-dimensional interface velocity
scalar yes 1.62208
dCoeff
Coefficient relating the diameter of the drops
formed to the capillary length
scalar yes 3.3
deltaStable Stable film thickness scalar yes 0
The inherited entries are elaborated in:
injectionModel.H
Source files
BrunDrippingInjection.H
BrunDrippingInjection.C
Definition at line 139 of file BrunDrippingInjection.H.
Constructor & Destructor Documentation
BrunDrippingInjection()
BrunDrippingInjection (liquidFilmBase & film, const dictionary & dict)
Definition at line 47 of file BrunDrippingInjection.C.
~BrunDrippingInjection()
virtual ~BrunDrippingInjection () virtual default
Member Function Documentation
TypeName()
TypeName ("BrunDrippingInjection")
correct()
void correct (scalarField & availableMass, scalarField & massToInject, scalarField & diameterToInject) virtual
Implements injectionModel.
Definition at line 71 of file BrunDrippingInjection.C.
References injectionModel::addToInjectedMass(), injectionModel::correct(), BrunDrippingInjection::dCoeff_, delta, BrunDrippingInjection::deltaStable_, BrunDrippingInjection::diameter_, filmSubModelBase::film(), forAll, g, Foam::mag(), Foam::max(), rho, Foam::sqr(), Foam::sqrt(), and BrunDrippingInjection::ubarStar_.
Member Data Documentation
ubarStar_
scalar ubarStar_ protected
Definition at line 158 of file BrunDrippingInjection.H.
Referenced by BrunDrippingInjection::correct().
dCoeff_
scalar dCoeff_ protected
Definition at line 162 of file BrunDrippingInjection.H.
Referenced by BrunDrippingInjection::correct().
deltaStable_
scalar deltaStable_ protected
Definition at line 166 of file BrunDrippingInjection.H.
Referenced by BrunDrippingInjection::correct().
diameter_
scalarList diameter_ protected
Definition at line 169 of file BrunDrippingInjection.H.
Referenced by BrunDrippingInjection::correct().
The documentation for this class was generated from the following files:
src/regionFaModels/liquidFilm/subModels/kinematic/injectionModel/BrunDrippingInjection/BrunDrippingInjection.H
src/regionFaModels/liquidFilm/subModels/kinematic/injectionModel/BrunDrippingInjection/BrunDrippingInjection.C