OpenFOAM: turbulentIntensityKineticEnergyInletFvPatchScalarField Class Reference
turbulentIntensityKineticEnergyInletFvPatchScalarField Class Reference
Boundary conditions » Inlet
This boundary condition provides a turbulent kinetic energy condition, based on user-supplied turbulence intensity, defined as a fraction of the mean velocity:
#include <turbulentIntensityKineticEnergyInletFvPatchScalarField.H>
Public Member Functions
TypeName ("turbulentIntensityKineticEnergyInlet")
turbulentIntensityKineticEnergyInletFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
turbulentIntensityKineticEnergyInletFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
turbulentIntensityKineticEnergyInletFvPatchScalarField (const turbulentIntensityKineticEnergyInletFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
turbulentIntensityKineticEnergyInletFvPatchScalarField (const turbulentIntensityKineticEnergyInletFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
turbulentIntensityKineticEnergyInletFvPatchScalarField (const turbulentIntensityKineticEnergyInletFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
This boundary condition provides a turbulent kinetic energy condition, based on user-supplied turbulence intensity, defined as a fraction of the mean velocity:
where
= kinetic energy at the patch
= turbulence intensity
= velocity field
In the event of reverse flow, a zero-gradient condition is applied.
Usage
Property Description Required Default value
intensity fraction of mean field [0-1] yes
U velocity field name no U
phi flux field name no phi
Example of the boundary condition specification:
    <patchName>
    {
        type        turbulentIntensityKineticEnergyInlet;
        intensity   0.05;           // 5% turbulence
        value       uniform 1;      // placeholder
    }
See also
Foam::inletOutletFvPatchField
Source files
turbulentIntensityKineticEnergyInletFvPatchScalarField.H
turbulentIntensityKineticEnergyInletFvPatchScalarField.C
Definition at line 118 of file turbulentIntensityKineticEnergyInletFvPatchScalarField.H.
Constructor & Destructor Documentation
turbulentIntensityKineticEnergyInletFvPatchScalarField() [1/5]
turbulentIntensityKineticEnergyInletFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 30 of file turbulentIntensityKineticEnergyInletFvPatchScalarField.C.
References Foam::Zero.
turbulentIntensityKineticEnergyInletFvPatchScalarField() [2/5]
turbulentIntensityKineticEnergyInletFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 60 of file turbulentIntensityKineticEnergyInletFvPatchScalarField.C.
References dict, Foam::exit(), Foam::FatalError, FatalErrorInFunction, IOobjectOption::MUST_READ, Foam::nl, fvPatchFieldBase::readDict(), and Foam::Zero.
turbulentIntensityKineticEnergyInletFvPatchScalarField() [3/5]
turbulentIntensityKineticEnergyInletFvPatchScalarField (const turbulentIntensityKineticEnergyInletFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 46 of file turbulentIntensityKineticEnergyInletFvPatchScalarField.C.
turbulentIntensityKineticEnergyInletFvPatchScalarField() [4/5]
turbulentIntensityKineticEnergyInletFvPatchScalarField (const turbulentIntensityKineticEnergyInletFvPatchScalarField & ptf)
Definition at line 94 of file turbulentIntensityKineticEnergyInletFvPatchScalarField.C.
turbulentIntensityKineticEnergyInletFvPatchScalarField() [5/5]
turbulentIntensityKineticEnergyInletFvPatchScalarField (const turbulentIntensityKineticEnergyInletFvPatchScalarField & ptf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 106 of file turbulentIntensityKineticEnergyInletFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("turbulentIntensityKineticEnergyInlet")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 172 of file turbulentIntensityKineticEnergyInletFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 191 of file turbulentIntensityKineticEnergyInletFvPatchScalarField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 121 of file turbulentIntensityKineticEnergyInletFvPatchScalarField.C.
References Foam::magSqr(), Foam::neg(), and Foam::sqr().
write()
void write (Ostream & os) const virtual
Definition at line 142 of file turbulentIntensityKineticEnergyInletFvPatchScalarField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntry(), Ostream::writeEntryIfDifferent(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/turbulentIntensityKineticEnergyInlet/turbulentIntensityKineticEnergyInletFvPatchScalarField.H
src/finiteVolume/fields/fvPatchFields/derived/turbulentIntensityKineticEnergyInlet/turbulentIntensityKineticEnergyInletFvPatchScalarField.C