OpenFOAM: pointEdgePoint Class Reference
pointEdgePoint Class Reference
Holds information regarding nearest wall point. Used in PointEdgeWave. (so not standard FaceCellWave) To be used in wall distance calculation.
#include <pointEdgePoint.H>
Public Member Functions
pointEdgePoint ()
pointEdgePoint (const point &origin, const scalar distSqr)
const point & origin () const noexcept
point & origin () noexcept
scalar distSqr () const noexcept
scalar & distSqr () noexcept
bool operator== (const pointEdgePoint &) const
bool operator!= (const pointEdgePoint &) const
template<class TrackingData >
bool valid (TrackingData &td) const
template<class TrackingData >
bool sameGeometry (const pointEdgePoint &, const scalar tol, TrackingData &td) const
template<class TrackingData >
void leaveDomain (const polyPatch &patch, const label patchPointi, const point &pos, TrackingData &td)
template<class TrackingData >
void enterDomain (const polyPatch &patch, const label patchPointi, const point &pos, TrackingData &td)
template<class TrackingData >
void transform (const tensor &rotTensor, TrackingData &td)
template<class TrackingData >
bool updatePoint (const polyMesh &mesh, const label pointi, const label edgeI, const pointEdgePoint &edgeInfo, const scalar tol, TrackingData &td)
template<class TrackingData >
bool updatePoint (const polyMesh &mesh, const label pointi, const pointEdgePoint &newPointInfo, const scalar tol, TrackingData &td)
template<class TrackingData >
bool updatePoint (const pointEdgePoint &newPointInfo, const scalar tol, TrackingData &td)
template<class TrackingData >
bool updateEdge (const polyMesh &mesh, const label edgeI, const label pointi, const pointEdgePoint &pointInfo, const scalar tol, TrackingData &td)
template<class TrackingData >
bool equal (const pointEdgePoint &, TrackingData &td) const
Friends
Ostream & operator<< (Ostream &, const pointEdgePoint &)
Istream & operator>> (Istream &, pointEdgePoint &)
Detailed Description
Holds information regarding nearest wall point. Used in PointEdgeWave. (so not standard FaceCellWave) To be used in wall distance calculation.
Source files
pointEdgePoint.H
pointEdgePointI.H
pointEdgePoint.C
Definition at line 61 of file pointEdgePoint.H.
Constructor & Destructor Documentation
pointEdgePoint() [1/2]
pointEdgePoint () inline
Definition at line 116 of file pointEdgePointI.H.
pointEdgePoint() [2/2]
pointEdgePoint (const point & origin, const scalar distSqr) inline
Definition at line 123 of file pointEdgePointI.H.
Member Function Documentation
origin() [1/2]
const point & origin () const inline noexcept
Definition at line 112 of file pointEdgePoint.H.
origin() [2/2]
point & origin () inline noexcept
Definition at line 114 of file pointEdgePoint.H.
distSqr() [1/2]
scalar distSqr () const inline noexcept
Definition at line 116 of file pointEdgePoint.H.
distSqr() [2/2]
scalar & distSqr () inline noexcept
Definition at line 118 of file pointEdgePoint.H.
operator==()
bool operator== (const pointEdgePoint & rhs) const inline
Definition at line 286 of file pointEdgePointI.H.
Referenced by PointData< DataType >::operator==().
operator!=()
bool operator!= (const pointEdgePoint & rhs) const inline
Definition at line 295 of file pointEdgePointI.H.
valid()
template<class TrackingData > bool valid (TrackingData & td) const inline
Definition at line 137 of file pointEdgePointI.H.
References VectorSpace< Form, Cmpt, Ncmpts >::max.
sameGeometry()
template<class TrackingData > bool sameGeometry (const pointEdgePoint & w2, const scalar tol, TrackingData & td) const inline
Definition at line 145 of file pointEdgePointI.H.
References Foam::diff(), Foam::mag(), and w2.
leaveDomain()
template<class TrackingData > void leaveDomain (const polyPatch & patch, const label patchPointi, const point & pos, TrackingData & td) inline
Definition at line 173 of file pointEdgePointI.H.
enterDomain()
template<class TrackingData > void enterDomain (const polyPatch & patch, const label patchPointi, const point & pos, TrackingData & td) inline
Definition at line 199 of file pointEdgePointI.H.
transform()
template<class TrackingData > void transform (const tensor & rotTensor, TrackingData & td) inline
Definition at line 186 of file pointEdgePointI.H.
References Foam::transform().
Referenced by PointData< DataType >::transform().
updatePoint() [1/3]
template<class TrackingData > bool updatePoint (const polyMesh & mesh, const label pointi, const label edgeI, const pointEdgePoint & edgeInfo, const scalar tol, TrackingData & td) inline
Definition at line 214 of file pointEdgePointI.H.
References mesh, polyMesh::points(), and update().
Referenced by PointData< DataType >::updatePoint(), PointData< DataType >::updatePoint(), and PointData< DataType >::updatePoint().
updatePoint() [2/3]
template<class TrackingData > bool updatePoint (const polyMesh & mesh, const label pointi, const pointEdgePoint & newPointInfo, const scalar tol, TrackingData & td) inline
Definition at line 230 of file pointEdgePointI.H.
References mesh, polyMesh::points(), and update().
updatePoint() [3/3]
template<class TrackingData > bool updatePoint (const pointEdgePoint & newPointInfo, const scalar tol, TrackingData & td) inline
Definition at line 245 of file pointEdgePointI.H.
References update().
updateEdge()
template<class TrackingData > bool updateEdge (const polyMesh & mesh, const label edgeI, const label pointi, const pointEdgePoint & pointInfo, const scalar tol, TrackingData & td) inline
Definition at line 258 of file pointEdgePointI.H.
References e, primitiveMesh::edges(), mesh, polyMesh::points(), and update().
Referenced by PointData< DataType >::updateEdge().
equal()
template<class TrackingData > bool equal (const pointEdgePoint & rhs, TrackingData & td) const inline
Definition at line 274 of file pointEdgePointI.H.
References Foam::operator==().
Friends And Related Symbol Documentation
operator<<
Ostream & operator<< (Ostream & , const pointEdgePoint &) friend
operator>>
Istream & operator>> (Istream & , pointEdgePoint &) friend
The documentation for this class was generated from the following files:
src/meshTools/algorithms/PointEdgeWave/pointEdgePoint.H
src/meshTools/algorithms/PointEdgeWave/pointEdgePointI.H