OpenFOAM: molecule::constantProperties Class Reference
molecule::constantProperties Class Reference
#include <molecule.H>
Public Member Functions
constantProperties ()
constantProperties (const dictionary &dict)
const Field< vector > & siteReferencePositions () const
const List< scalar > & siteMasses () const
const List< scalar > & siteCharges () const
const List< label > & siteIds () const
List< label > & siteIds ()
const List< bool > & pairPotentialSites () const
bool pairPotentialSite (label sId) const
const List< bool > & electrostaticSites () const
bool electrostaticSite (label sId) const
const diagTensor & momentOfInertia () const
bool linearMolecule () const
bool pointMolecule () const
label degreesOfFreedom () const
scalar mass () const
label nSites () const
Detailed Description
Definition at line 87 of file molecule.H.
Constructor & Destructor Documentation
constantProperties() [1/2]
constantProperties () inline
Definition at line 24 of file moleculeI.H.
constantProperties() [2/2]
constantProperties (const dictionary & dict) inline
Definition at line 37 of file moleculeI.H.
References Foam::abort(), dict, e, Foam::eigenValues(), Foam::eigenVectors(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::Info, Foam::nl, Foam::normalised(), p, molecule::Q(), Foam::rotationTensor(), UList< T >::size(), Foam::sum(), x, Vector< Cmpt >::x(), Vector< Cmpt >::y(), Vector< Cmpt >::z(), and Foam::Zero.
Member Function Documentation
siteReferencePositions()
const Foam::Field< Foam::vector > & siteReferencePositions () const inline
Definition at line 367 of file moleculeI.H.
Referenced by molecule::move(), and molecule::setSitePositions().
siteMasses()
const Foam::List< Foam::scalar > & siteMasses () const inline
Definition at line 374 of file moleculeI.H.
siteCharges()
const Foam::List< Foam::scalar > & siteCharges () const inline
Definition at line 381 of file moleculeI.H.
siteIds() [1/2]
const Foam::List< Foam::label > & siteIds () const inline
Definition at line 388 of file moleculeI.H.
siteIds() [2/2]
Foam::List< Foam::label > & siteIds () inline
Definition at line 395 of file moleculeI.H.
pairPotentialSites()
const Foam::List< bool > & pairPotentialSites () const inline
Definition at line 402 of file moleculeI.H.
pairPotentialSite()
bool pairPotentialSite (label sId) const inline
Definition at line 408 of file moleculeI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, Foam::nl, and s().
electrostaticSites()
const Foam::List< bool > & electrostaticSites () const inline
Definition at line 427 of file moleculeI.H.
electrostaticSite()
bool electrostaticSite (label sId) const inline
Definition at line 433 of file moleculeI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, Foam::nl, and s().
momentOfInertia()
const Foam::diagTensor & momentOfInertia () const inline
Definition at line 452 of file moleculeI.H.
Referenced by molecule::move().
linearMolecule()
bool linearMolecule () const inline
Definition at line 458 of file moleculeI.H.
Referenced by molecule::move().
pointMolecule()
bool pointMolecule () const inline
Definition at line 464 of file moleculeI.H.
Referenced by molecule::move().
degreesOfFreedom()
Foam::label degreesOfFreedom () const inline
Definition at line 470 of file moleculeI.H.
mass()
Foam::scalar mass () const inline
Definition at line 487 of file moleculeI.H.
Referenced by molecule::move().
nSites()
Foam::label nSites () const inline
Definition at line 493 of file moleculeI.H.
References UPtrList< T >::size().
The documentation for this class was generated from the following files:
src/lagrangian/molecularDynamics/molecule/molecule/molecule.H
src/lagrangian/molecularDynamics/molecule/molecule/moleculeI.H