OpenFOAM: turbulentDispersionModel Class Reference
turbulentDispersionModel Class Reference abstract
#include <turbulentDispersionModel.H>
Public Member Functions
TypeName ("turbulentDispersionModel")
declareRunTimeSelectionTable (autoPtr, turbulentDispersionModel, dictionary,(const dictionary &dict, const phasePair &pair),(dict, pair))
turbulentDispersionModel (const dictionary &dict, const phasePair &pair)
virtual ~turbulentDispersionModel ()=default
const phaseCompressibleTurbulenceModel & continuousTurbulence () const
virtual tmp< volScalarField > D () const =0
virtual tmp< volVectorField > F () const
virtual tmp< surfaceScalarField > Ff () const
TypeName ("turbulentDispersionModel")
declareRunTimeSelectionTable (autoPtr, turbulentDispersionModel, dictionary,(const dictionary &dict, const phasePair &pair),(dict, pair))
turbulentDispersionModel (const dictionary &dict, const phasePair &pair)
virtual ~turbulentDispersionModel ()=default
virtual tmp< volScalarField > D () const =0
virtual tmp< volVectorField > F () const
Static Public Member Functions
static autoPtr< turbulentDispersionModel > New (const dictionary &dict, const phasePair &pair)
static autoPtr< turbulentDispersionModel > New (const dictionary &dict, const phasePair &pair)
Static Public Attributes
static const dimensionSet dimD
static const dimensionSet dimF
Protected Attributes
const phasePair & pair_
Detailed Description
Source files
turbulentDispersionModel.H
turbulentDispersionModel.C
Source files
turbulentDispersionModel.H
turbulentDispersionModel.C
Definition at line 52 of file turbulentDispersionModel.H.
Constructor & Destructor Documentation
turbulentDispersionModel() [1/2]
turbulentDispersionModel (const dictionary & dict, const phasePair & pair)
Definition at line 45 of file turbulentDispersionModel.C.
~turbulentDispersionModel() [1/2]
virtual ~turbulentDispersionModel () virtual default
turbulentDispersionModel() [2/2]
turbulentDispersionModel (const dictionary & dict, const phasePair & pair)
~turbulentDispersionModel() [2/2]
virtual ~turbulentDispersionModel () virtual default
Member Function Documentation
TypeName() [1/2]
TypeName ("turbulentDispersionModel")
declareRunTimeSelectionTable() [1/2]
declareRunTimeSelectionTable (autoPtr , turbulentDispersionModel , dictionary , (const dictionary &dict, const phasePair &pair) , (dict, pair))
New() [1/2]
Foam::autoPtr< Foam::turbulentDispersionModel > New (const dictionary & dict, const phasePair & pair) static
Definition at line 58 of file turbulentDispersionModel.C.
References Foam::abort(), dict, Foam::endl(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), and Foam::Info.
continuousTurbulence()
const Foam::phaseCompressibleTurbulenceModel & continuousTurbulence () const
Definition at line 89 of file turbulentDispersionModel.C.
References IOobject::groupName(), and turbulenceModel::propertiesName.
D() [1/2]
virtual tmp< volScalarField > D () const pure virtual
Implemented in Burns, constantTurbulentDispersionCoefficient, Gosman, LopezDeBertodano, noTurbulentDispersion, Burns, constantTurbulentDispersionCoefficient, Gosman, LopezDeBertodano, and noTurbulentDispersion.
F() [1/2]
Foam::tmp< Foam::volVectorField > F () const virtual
Reimplemented in noTurbulentDispersion, and noTurbulentDispersion.
Definition at line 104 of file turbulentDispersionModel.C.
References D, and Foam::fvc::grad().
Ff()
Foam::tmp< Foam::surfaceScalarField > Ff () const virtual
Definition at line 111 of file turbulentDispersionModel.C.
References D, Foam::fvc::interpolate(), and Foam::fvc::snGrad().
TypeName() [2/2]
TypeName ("turbulentDispersionModel")
declareRunTimeSelectionTable() [2/2]
declareRunTimeSelectionTable (autoPtr , turbulentDispersionModel , dictionary , (const dictionary &dict, const phasePair &pair) , (dict, pair))
New() [2/2]
static autoPtr< turbulentDispersionModel > New (const dictionary & dict, const phasePair & pair) static
D() [2/2]
virtual tmp< volScalarField > D () const pure virtual
Implemented in Burns, constantTurbulentDispersionCoefficient, Gosman, LopezDeBertodano, noTurbulentDispersion, Burns, constantTurbulentDispersionCoefficient, Gosman, LopezDeBertodano, and noTurbulentDispersion.
F() [2/2]
virtual tmp< volVectorField > F () const virtual
Reimplemented in noTurbulentDispersion, and noTurbulentDispersion.
Member Data Documentation
pair_
const phasePair & pair_ protected
Definition at line 59 of file turbulentDispersionModel.H.
dimD
static const dimensionSet dimD static
Definition at line 85 of file turbulentDispersionModel.H.
dimF
static const dimensionSet dimF static
Definition at line 88 of file turbulentDispersionModel.H.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/interfacialModels/turbulentDispersionModels/turbulentDispersionModel/turbulentDispersionModel.H
src/phaseSystemModels/twoPhaseEuler/twoPhaseSystem/interfacialModels/turbulentDispersionModels/turbulentDispersionModel/turbulentDispersionModel.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/interfacialModels/turbulentDispersionModels/turbulentDispersionModel/turbulentDispersionModel.C
src/phaseSystemModels/twoPhaseEuler/twoPhaseSystem/interfacialModels/turbulentDispersionModels/turbulentDispersionModel/turbulentDispersionModel.C