OpenFOAM: StaticPhaseModel< BasePhaseModel > Class Template Reference
StaticPhaseModel< BasePhaseModel > Class Template Reference
Class which represents a static fluid phase.
#include <StaticPhaseModel.H>
Public Member Functions
StaticPhaseModel (const multiphaseInterSystem &fluid, const word &phaseName)
virtual ~StaticPhaseModel ()=default
virtual void correct ()
virtual tmp< surfaceScalarField > phi () const
virtual const surfaceScalarField & phi ()
virtual tmp< surfaceScalarField > alphaPhi () const
virtual surfaceScalarField & alphaPhi ()
virtual tmp< volVectorField > U () const
virtual tmp< surfaceScalarField > diffNo () const
Detailed Description
template<class BasePhaseModel>
class Foam::StaticPhaseModel< BasePhaseModel >
Class which represents a static fluid phase.
Source files
StaticPhaseModel.H
StaticPhaseModel.C
Definition at line 47 of file StaticPhaseModel.H.
Constructor & Destructor Documentation
StaticPhaseModel()
template<class BasePhaseModel > StaticPhaseModel (const multiphaseInterSystem & fluid, const word & phaseName)
Definition at line 33 of file StaticPhaseModel.C.
References Foam::name().
~StaticPhaseModel()
template<class BasePhaseModel > virtual ~StaticPhaseModel () virtual default
Member Function Documentation
correct()
template<class BasePhaseModel > void correct () virtual
Definition at line 73 of file StaticPhaseModel.C.
phi() [1/2]
template<class BasePhaseModel > Foam::tmp< Foam::surfaceScalarField > phi () const virtual
Definition at line 81 of file StaticPhaseModel.C.
References IOobject::groupName(), phaseModel::name(), tmp< T >::New(), and Foam::Zero.
phi() [2/2]
template<class BasePhaseModel > const Foam::surfaceScalarField & phi () virtual
Definition at line 99 of file StaticPhaseModel.C.
References Foam::Zero.
alphaPhi() [1/2]
template<class BasePhaseModel > Foam::tmp< Foam::surfaceScalarField > alphaPhi () const virtual
Definition at line 108 of file StaticPhaseModel.C.
References IOobject::groupName(), phaseModel::name(), tmp< T >::New(), and Foam::Zero.
alphaPhi() [2/2]
template<class BasePhaseModel > Foam::surfaceScalarField & alphaPhi () virtual
Definition at line 130 of file StaticPhaseModel.C.
References Foam::Zero.
U()
template<class BasePhaseModel > Foam::tmp< Foam::volVectorField > U () const virtual
Definition at line 139 of file StaticPhaseModel.C.
References Foam::dimVelocity, IOobject::groupName(), phaseModel::name(), tmp< T >::New(), and Foam::Zero.
diffNo()
template<class BasePhaseModel > Foam::tmp< Foam::surfaceScalarField > diffNo () const virtual
Definition at line 157 of file StaticPhaseModel.C.
References Foam::fvc::interpolate(), and Foam::sqr().
The documentation for this class was generated from the following files:
src/phaseSystemModels/multiphaseInter/phasesSystem/phaseModel/StaticPhaseModel/StaticPhaseModel.H
src/phaseSystemModels/multiphaseInter/phasesSystem/phaseModel/StaticPhaseModel/StaticPhaseModel.C