OpenFOAM: nucleationModel Class Reference
nucleationModel Class Reference abstract
Base class for nucleation models.
#include <nucleationModel.H>
Classes
class iNew
Public Member Functions
TypeName ("nucleationModel")
declareRunTimeSelectionTable (autoPtr, nucleationModel, dictionary,(const populationBalanceModel &popBal, const dictionary &dict),(popBal, dict))
nucleationModel (const populationBalanceModel &popBal, const dictionary &dict)
autoPtr< nucleationModel > clone () const
virtual ~nucleationModel ()=default
const populationBalanceModel & popBal () const
virtual void correct ()
virtual void addToNucleationRate (volScalarField &nucleationRate, const label i)=0
Static Public Member Functions
static autoPtr< nucleationModel > New (const word &type, const populationBalanceModel &popBal, const dictionary &dict)
Protected Attributes
const populationBalanceModel & popBal_
Detailed Description
Base class for nucleation models.
Source files
nucleationModel.H
nucleationModel.C
Definition at line 48 of file nucleationModel.H.
Constructor & Destructor Documentation
nucleationModel()
nucleationModel (const populationBalanceModel & popBal, const dictionary & dict)
Definition at line 66 of file nucleationModel.C.
~nucleationModel()
virtual ~nucleationModel () virtual default
Member Function Documentation
TypeName()
TypeName ("nucleationModel")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , nucleationModel , dictionary , (const populationBalanceModel &popBal, const dictionary &dict) , (popBal, dict))
clone()
autoPtr< nucleationModel > clone () const inline
Definition at line 109 of file nucleationModel.H.
References NotImplemented.
New()
Foam::autoPtr< Foam::diameterModels::nucleationModel > New (const word & type, const populationBalanceModel & popBal, const dictionary & dict) static
Definition at line 40 of file nucleationModel.C.
References dict, Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, nucleationModel::popBal(), and Foam::type().
Referenced by nucleationModel::iNew::operator()().
popBal()
const populationBalanceModel & popBal () const inline
Definition at line 133 of file nucleationModel.H.
References nucleationModel::popBal_.
Referenced by nucleationModel::New().
correct()
void correct () virtual
Reimplemented in constantNucleation, and wallBoiling.
Definition at line 78 of file nucleationModel.C.
addToNucleationRate()
virtual void addToNucleationRate (volScalarField & nucleationRate, const label i) pure virtual
Implemented in constantNucleation, and wallBoiling.
Member Data Documentation
popBal_
const populationBalanceModel& popBal_ protected
Definition at line 55 of file nucleationModel.H.
Referenced by nucleationModel::popBal().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/populationBalanceModel/nucleationModels/nucleationModel/nucleationModel.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/populationBalanceModel/nucleationModels/nucleationModel/nucleationModel.C