OpenFOAM: projectVertex Class Reference
projectVertex Class Reference
Projects the vertex onto the selected surfacees of the geometry provided as a searchableSurfaces object.
#include <projectVertex.H>
Public Member Functions
TypeName ("project")
projectVertex (const dictionary &dict, const label index, const searchableSurfaces &geometry, Istream &is)
virtual ~projectVertex ()=default
virtual operator point () const
Public Member Functions inherited from pointVertex
TypeName ("point")
pointVertex (const dictionary &dict, const label index, const searchableSurfaces &geometry, Istream &is)
virtual ~pointVertex ()=default
Public Member Functions inherited from blockVertex
TypeName ("blockVertex")
declareRunTimeSelectionTable (autoPtr, blockVertex, Istream,(const dictionary &dict, const label index, const searchableSurfaces &geometry, Istream &is),(dict, index, geometry, is))
blockVertex () noexcept=default
virtual autoPtr< blockVertex > clone () const
virtual ~blockVertex ()=default
Additional Inherited Members
Static Public Member Functions inherited from blockVertex
static autoPtr< blockVertex > New (const dictionary &dict, const label index, const searchableSurfaces &geometry, Istream &)
static label read (Istream &, const dictionary &)
static void write (Ostream &, const label, const dictionary &)
Protected Attributes inherited from pointVertex
point vertex_
Detailed Description
Projects the vertex onto the selected surfacees of the geometry provided as a searchableSurfaces object.
Source files
projectVertex.H
projectVertex.C
Definition at line 50 of file projectVertex.H.
Constructor & Destructor Documentation
projectVertex()
projectVertex (const dictionary & dict, const label index, const searchableSurfaces & geometry, Istream & is)
Definition at line 41 of file projectVertex.C.
References Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, forAll, List< T >::setSize(), and UList< T >::size().
~projectVertex()
virtual ~projectVertex () virtual default
Member Function Documentation
TypeName()
TypeName ("project")
operator point()
operator point () const virtual
Reimplemented from pointVertex.
Definition at line 70 of file projectVertex.C.
References searchableSurfacesQueries::bounds(), searchableSurfacesQueries::findNearest(), boundBox::magSqr(), boundBox::max(), Foam::max(), boundBox::min(), Foam::min(), and UList< T >::size().
The documentation for this class was generated from the following files:
src/mesh/blockMesh/blockVertices/projectVertex/projectVertex.H
src/mesh/blockMesh/blockVertices/projectVertex/projectVertex.C