OpenFOAM: STLAsciiParseManual Class Reference
STLAsciiParseManual Class Reference
Public Member Functions
STLAsciiParseManual (const label approxNpoints)
void execute (std::istream &is)
Public Member Functions inherited from STLAsciiParse
STLAsciiParse (const label approxNpoints)
void clear ()
bool sorted () const
DynamicList< STLpoint > & points ()
DynamicList< label > & facets ()
DynamicList< word > & names ()
DynamicList< label > & sizes ()
Additional Inherited Members
Protected Member Functions inherited from STLAsciiParse
void beginSolid (word solidName)
void beginFacet ()
void resetVertex ()
bool addVertexComponent (float val)
bool addVertexComponent (const char *text)
void endFacet ()
STLAsciiParse (const STLAsciiParse &)=delete
void operator= (const STLAsciiParse &)=delete
Protected Attributes inherited from STLAsciiParse
bool sorted_
label groupId_
label lineNum_
int nFacetPoints_
int nVertexCmpt_
STLpoint currVertex_
DynamicList< STLpoint > points_
DynamicList< label > facets_
DynamicList< word > names_
DynamicList< label > sizes_
HashTable< label > nameLookup_
Detailed Description
Definition at line 57 of file STLAsciiParseManual.C.
Constructor & Destructor Documentation
STLAsciiParseManual()
STLAsciiParseManual (const label approxNpoints) inline
Definition at line 128 of file STLAsciiParseManual.C.
Member Function Documentation
execute()
void execute (std::istream & is)
Definition at line 146 of file STLAsciiParseManual.C.
References STLAsciiParse::addVertexComponent(), STLAsciiParse::beginFacet(), STLAsciiParse::beginSolid(), UList< T >::empty(), STLAsciiParse::endFacet(), FatalErrorInFunction, INBUFLEN, STLAsciiParse::lineNum_, Foam::stringOps::lower(), Foam::nl, word::null, p, perrorEOF(), perrorParse(), UList< T >::size(), and word::validate().
The documentation for this class was generated from the following file:
src/fileFormats/stl/STLAsciiParseManual.C