OpenFOAM: blockEdge Class Reference
blockEdge Class Reference abstract
Define a curved edge that is parameterized for 0<lambda<1 between the start/end points.
#include <blockEdge.H>
Classes
class iNew
Public Member Functions
TypeName ("blockEdge")
declareRunTimeSelectionTable (autoPtr, blockEdge, Istream,(const dictionary &dict, const label index, const searchableSurfaces &geometry, const pointField &points, Istream &is),(dict, index, geometry, points, is))
blockEdge (const pointField &points, const edge &fromTo)
blockEdge (const dictionary &dict, const label index, const pointField &points, Istream &is)
virtual autoPtr< blockEdge > clone () const
virtual ~blockEdge ()=default
bool valid () const noexcept
label start () const noexcept
label end () const noexcept
const point & firstPoint () const
const point & lastPoint () const
int compare (const blockEdge &e) const
int compare (const edge &e) const
int compare (const label start, const label end) const
point linearPosition (const scalar lambda) const
virtual point position (const scalar lambda) const =0
virtual tmp< pointField > position (const scalarList &lambdas) const
virtual scalar length () const =0
void write (Ostream &os, const dictionary &dict) const
Static Public Member Functions
static autoPtr< blockEdge > New (const dictionary &dict, const label index, const searchableSurfaces &geometry, const pointField &points, Istream &is)
Protected Member Functions
blockEdge (const pointField &points, const label from, const label to)
Static Protected Member Functions
static pointField appendEndPoints (const pointField &p, const label from, const label to, const pointField &intermediate)
Protected Attributes
const pointField & points_
const label start_
const label end_
Friends
Ostream & operator<< (Ostream &os, const blockEdge &e)
Detailed Description
Define a curved edge that is parameterized for 0<lambda<1 between the start/end points.
Source files
blockEdge.H
blockEdge.C
Definition at line 60 of file blockEdge.H.
Constructor & Destructor Documentation
blockEdge() [1/3]
blockEdge (const pointField & points, const label from, const label to) inline protected
Parameters
points Referenced point field
from Start point in point field
to End point in point field
Definition at line 93 of file blockEdge.H.
blockEdge() [2/3]
blockEdge (const pointField & points, const edge & fromTo)
Parameters
points Referenced point field
fromTo Start/end in point field
Definition at line 37 of file blockEdge.C.
blockEdge() [3/3]
blockEdge (const dictionary & dict, const label index, const pointField & points, Istream & is)
Parameters
points Referenced point field
Definition at line 49 of file blockEdge.C.
~blockEdge()
virtual ~blockEdge () virtual default
Member Function Documentation
appendEndPoints()
Foam::pointField appendEndPoints (const pointField & p, const label from, const label to, const pointField & intermediate) static protected
Parameters
p Referenced point field
from Start point in point field
to End point in point field
intermediate Intermediate points (knots)
Definition at line 102 of file blockEdge.C.
References polyLine::concat(), and p.
TypeName()
TypeName ("blockEdge")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , blockEdge , Istream , (const dictionary &dict, const label index, const searchableSurfaces &geometry, const pointField &points, Istream &is) , (dict, index, geometry, points, is))
clone()
Foam::autoPtr< Foam::blockEdge > clone () const virtual
Definition at line 63 of file blockEdge.C.
References NotImplemented.
New()
Foam::autoPtr< Foam::blockEdge > New (const dictionary & dict, const label index, const searchableSurfaces & geometry, const pointField & points, Istream & is) static
Definition at line 70 of file blockEdge.C.
References Foam::abort(), DebugInFunction, dict, Foam::endl(), Foam::FatalIOError, FatalIOErrorInLookup, and points.
Referenced by blockEdge::iNew::operator()().
valid()
bool valid () const inline noexcept
Definition at line 24 of file blockEdgeI.H.
References blockEdge::end_, and blockEdge::start_.
start()
Foam::label start () const inline noexcept
Definition at line 30 of file blockEdgeI.H.
end()
Foam::label end () const inline noexcept
Definition at line 36 of file blockEdgeI.H.
firstPoint()
const Foam::point & firstPoint () const inline
Definition at line 42 of file blockEdgeI.H.
Referenced by arcEdge::arcEdge(), arcEdge::arcEdge(), and arcEdge::arcEdge().
lastPoint()
const Foam::point & lastPoint () const inline
Definition at line 48 of file blockEdgeI.H.
Referenced by arcEdge::arcEdge(), arcEdge::arcEdge(), and arcEdge::arcEdge().
compare() [1/3]
int compare (const blockEdge & e) const inline
Definition at line 69 of file blockEdgeI.H.
References blockEdge::compare(), e, and UList< T >::end().
Referenced by blockEdge::compare(), and blockEdge::compare().
compare() [2/3]
int compare (const edge & e) const inline
Definition at line 75 of file blockEdgeI.H.
References blockEdge::compare(), e, and UList< T >::end().
compare() [3/3]
int compare (const label start, const label end) const inline
Definition at line 54 of file blockEdgeI.H.
linearPosition()
Foam::point linearPosition (const scalar lambda) const inline
Definition at line 81 of file blockEdgeI.H.
References InfoInFunction, lambda(), and Foam::nl.
Referenced by lineEdge::position(), projectEdge::position(), projectCurveEdge::position(), and projectEdge::position().
position() [1/2]
virtual point position (const scalar lambda) const pure virtual
Implemented in arcEdge, bezier, polyLineEdge, BSplineEdge, lineEdge, projectCurveEdge, projectEdge, and splineEdge.
position() [2/2]
Foam::tmp< Foam::pointField > position (const scalarList & lambdas) const virtual
Reimplemented in projectCurveEdge, and projectEdge.
Definition at line 117 of file blockEdge.C.
References forAll, tmp< T >::New(), points, and UPtrList< T >::size().
length()
virtual scalar length () const pure virtual
Implemented in bezier, BSplineEdge, lineEdge, polyLineEdge, projectCurveEdge, projectEdge, splineEdge, and arcEdge.
write()
void write (Ostream & os, const dictionary & dict) const
Definition at line 130 of file blockEdge.C.
References dict, Foam::endl(), os(), Foam::tab, and blockVertex::write().
Friends And Related Symbol Documentation
operator<<
Ostream & operator<< (Ostream & os, const blockEdge & e) friend
Member Data Documentation
points_
const pointField& points_ protected
Definition at line 67 of file blockEdge.H.
start_
const label start_ protected
Definition at line 70 of file blockEdge.H.
Referenced by arcEdge::arcEdge(), and blockEdge::valid().
end_
const label end_ protected
Definition at line 73 of file blockEdge.H.
Referenced by arcEdge::arcEdge(), and blockEdge::valid().
The documentation for this class was generated from the following files:
src/mesh/blockMesh/blockEdges/blockEdge/blockEdge.H
src/mesh/blockMesh/blockEdges/blockEdge/blockEdge.C
src/mesh/blockMesh/blockEdges/blockEdge/blockEdgeI.H