OpenFOAM: setUpdater Class Reference
setUpdater Class Reference
Keeps cell/face/vertex sets uptodate. Both the ones loaded and the ones on disk.
#include <setUpdater.H>
Public Member Functions
TypeName ("setUpdater")
setUpdater (const word &name, const dictionary &dict, const label index, const polyTopoChanger &mme)
virtual ~setUpdater ()=default
virtual bool changeTopology () const
virtual void setRefinement (polyTopoChange &) const
virtual void modifyMotionPoints (pointField &motionPoints) const
virtual void updateMesh (const mapPolyMesh &)
virtual void write (Ostream &) const
virtual void writeDict (Ostream &) const
Public Member Functions inherited from polyMeshModifier
TypeName ("meshModifier")
declareRunTimeSelectionTable (autoPtr, polyMeshModifier, dictionary,(const word &name, const dictionary &dict, const label index, const polyTopoChanger &mme),(name, dict, index, mme))
polyMeshModifier (const word &name, const label index, const polyTopoChanger &mme, const bool act)
virtual ~polyMeshModifier ()=default
const word & name () const
label index () const
const polyTopoChanger & topoChanger () const
Switch active () const
void enable () const
void disable () const
Additional Inherited Members
Static Public Member Functions inherited from polyMeshModifier
static autoPtr< polyMeshModifier > New (const word &name, const dictionary &dict, const label index, const polyTopoChanger &mme)
Detailed Description
Keeps cell/face/vertex sets uptodate. Both the ones loaded and the ones on disk.
Source files
setUpdater.H
setUpdater.C
setUpdaterTemplates.C
Definition at line 49 of file setUpdater.H.
Constructor & Destructor Documentation
setUpdater()
setUpdater (const word & name, const dictionary & dict, const label index, const polyTopoChanger & mme)
Definition at line 46 of file setUpdater.C.
References Foam::name().
~setUpdater()
virtual ~setUpdater () virtual default
Member Function Documentation
TypeName()
TypeName ("setUpdater")
changeTopology()
bool changeTopology () const virtual
Implements polyMeshModifier.
Definition at line 60 of file setUpdater.C.
setRefinement()
void setRefinement (polyTopoChange &) const virtual
Implements polyMeshModifier.
Definition at line 67 of file setUpdater.C.
modifyMotionPoints()
void modifyMotionPoints (pointField & motionPoints) const virtual
Implements polyMeshModifier.
Definition at line 71 of file setUpdater.C.
updateMesh()
void updateMesh (const mapPolyMesh & morphMap) virtual
Implements polyMeshModifier.
Definition at line 75 of file setUpdater.C.
References Foam::endl(), and Foam::Pout.
write()
void write (Ostream & os) const virtual
Implements polyMeshModifier.
Definition at line 90 of file setUpdater.C.
References Foam::nl, os(), and Foam::type().
writeDict()
void writeDict (Ostream & os) const virtual
Implements polyMeshModifier.
Definition at line 96 of file setUpdater.C.
References Ostream::beginBlock(), Ostream::endBlock(), Foam::name(), Foam::nl, os(), Foam::type(), and Ostream::writeEntry().
The documentation for this class was generated from the following files:
src/dynamicMesh/setUpdater/setUpdater.H
src/dynamicMesh/setUpdater/setUpdater.C
src/dynamicMesh/setUpdater/setUpdaterTemplates.C