OpenFOAM: treeDataPoint Class Reference
treeDataPoint Class Reference
Holds (reference to) pointField. Encapsulation of data needed for octree searches. Used for searching for nearest point. No bounding boxes around points. Only overlaps and calcNearest are implemented, rest makes little sense.
#include <treeDataPoint.H>
Classes
class findIntersectOp
class findNearestOp
Public Member Functions
ClassNameNoDebug ("treeDataPoint")
treeDataPoint (const pointField &points)
treeDataPoint (const pointField &points, const labelUList &pointLabels, const bool useSubsetPoints=true)
treeDataPoint (const pointField &points, labelList &&pointLabels, const bool useSubsetPoints=true)
int nDim () const noexcept
treeBoundBox bounds (const labelUList &indices) const
const pointField & points () const noexcept
const labelList & pointLabels () const noexcept
bool useSubset () const noexcept
bool empty () const noexcept
label size () const noexcept
label objectIndex (const label index) const
const point & operator[] (const label index) const
const point & centre (const label index) const
tmp< pointField > centres () const
volumeType getVolumeType (const indexedOctree< treeDataPoint > &os, const point &sample) const
bool overlaps (const label index, const treeBoundBox &searchBox) const
bool overlaps (const label index, const point &centre, const scalar radiusSqr) const
void findNearest (const labelUList &indices, const point &sample, scalar &nearestDistSqr, label &nearestIndex, point &nearestPoint) const
label pointLabel (label index) const
FOAM_DEPRECATED_FOR(2022-10, "objectIndex()")
Detailed Description
Holds (reference to) pointField. Encapsulation of data needed for octree searches. Used for searching for nearest point. No bounding boxes around points. Only overlaps and calcNearest are implemented, rest makes little sense.
Optionally works on subset of points.
Source files
treeDataPoint.H
treeDataPoint.C
Definition at line 58 of file treeDataPoint.H.
Constructor & Destructor Documentation
treeDataPoint() [1/3]
treeDataPoint (const pointField & points) explicit
Definition at line 35 of file treeDataPoint.C.
treeDataPoint() [2/3]
treeDataPoint (const pointField & points, const labelUList & pointLabels, const bool useSubsetPoints = true)
Definition at line 42 of file treeDataPoint.C.
treeDataPoint() [3/3]
treeDataPoint (const pointField & points, labelList && pointLabels, const bool useSubsetPoints = true)
Definition at line 55 of file treeDataPoint.C.
Member Function Documentation
ClassNameNoDebug()
ClassNameNoDebug ("treeDataPoint")
nDim()
int nDim () const inline noexcept
Definition at line 157 of file treeDataPoint.H.
bounds()
Foam::treeBoundBox bounds (const labelUList & indices) const
Definition at line 70 of file treeDataPoint.C.
References boundBox::add().
points()
const pointField & points () const inline noexcept
Definition at line 166 of file treeDataPoint.H.
pointLabels()
const labelList & pointLabels () const inline noexcept
Definition at line 169 of file treeDataPoint.H.
useSubset()
bool useSubset () const inline noexcept
Definition at line 172 of file treeDataPoint.H.
empty()
bool empty () const inline noexcept
Definition at line 175 of file treeDataPoint.H.
References UList< T >::empty().
size()
label size () const inline noexcept
Definition at line 181 of file treeDataPoint.H.
References UList< T >::size().
objectIndex()
label objectIndex (const label index) const inline
Definition at line 187 of file treeDataPoint.H.
Referenced by treeDataPoint::centre(), treeDataPoint::operator[](), and treeDataPoint::pointLabel().
operator[]()
const point & operator[] (const label index) const inline
Definition at line 193 of file treeDataPoint.H.
References treeDataPoint::objectIndex().
centre()
const point & centre (const label index) const inline
Definition at line 199 of file treeDataPoint.H.
References treeDataPoint::objectIndex().
Referenced by treeDataPoint::findNearest(), and treeDataPoint::findNearestOp::operator()().
centres()
Foam::tmp< Foam::pointField > centres () const
Definition at line 86 of file treeDataPoint.C.
References tmp< T >::New().
getVolumeType()
Foam::volumeType getVolumeType (const indexedOctree< treeDataPoint > & os, const point & sample) const
Definition at line 97 of file treeDataPoint.C.
References volumeType::UNKNOWN.
overlaps() [1/2]
bool overlaps (const label index, const treeBoundBox & searchBox) const
Definition at line 107 of file treeDataPoint.C.
overlaps() [2/2]
bool overlaps (const label index, const point & centre, const scalar radiusSqr) const
Definition at line 117 of file treeDataPoint.C.
References Vector< Cmpt >::distSqr().
findNearest()
void findNearest (const labelUList & indices, const point & sample, scalar & nearestDistSqr, label & nearestIndex, point & nearestPoint) const
Definition at line 146 of file treeDataPoint.C.
References treeDataPoint::centre().
pointLabel()
label pointLabel (label index) const inline
FOAM_DEPRECATED_FOR(2022-10, "objectIndex()")
Definition at line 250 of file treeDataPoint.H.
References treeDataPoint::objectIndex().
The documentation for this class was generated from the following files:
src/OpenFOAM/algorithms/indexedOctree/treeDataPoint.H
src/OpenFOAM/algorithms/indexedOctree/treeDataPoint.C