OpenFOAM: seulex Class Reference
seulex Class Reference
Numerics » Ordinary Differential Equation (ODE) solvers
An extrapolation-algorithm, based on the linearly implicit Euler method with step size control and order selection.
#include <seulex.H>
Public Member Functions
TypeName ("seulex")
seulex (const ODESystem &ode, const dictionary &dict)
virtual ~seulex ()=default
virtual bool resize ()
virtual void solve (scalar &x, scalarField &y, stepState &step) const
Public Member Functions inherited from ODESolver
TypeName ("ODESolver")
declareRunTimeSelectionTable (autoPtr, ODESolver, dictionary,(const ODESystem &ode, const dictionary &dict),(ode, dict))
ODESolver (const ODESystem &ode, const dictionary &dict)
ODESolver (const ODESystem &ode, const scalarField &absTol, const scalarField &relTol)
virtual ~ODESolver ()=default
label nEqns () const
scalarField & absTol ()
scalarField & relTol ()
template<class Type >
void resizeField (UList< Type > &f) const
void resizeMatrix (scalarSquareMatrix &m) const
virtual void solve (scalar &x, scalarField &y, scalar &dxTry) const
virtual void solve (const scalar xStart, const scalar xEnd, scalarField &y, scalar &dxEst) const
Additional Inherited Members
Static Public Member Functions inherited from ODESolver
static autoPtr< ODESolver > New (const ODESystem &ode, const dictionary &dict)
template<class Type >
static void resizeField (UList< Type > &f, const label n)
Protected Member Functions inherited from ODESolver
scalar normalizeError (const scalarField &y0, const scalarField &y, const scalarField &err) const
ODESolver (const ODESolver &)=delete
void operator= (const ODESolver &)=delete
Protected Attributes inherited from ODESolver
const ODESystem & odes_
const label maxN_
label n_
scalarField absTol_
scalarField relTol_
label maxSteps_
Detailed Description
An extrapolation-algorithm, based on the linearly implicit Euler method with step size control and order selection.
Reference:
    Hairer, E., Nørsett, S. P., & Wanner, G. (1996).
    Solving Ordinary Differential Equations II:
    Stiff and Differential-Algebraic Problems, second edition",
    Springer-Verlag, Berlin.
Source files
seulex.H
seulex.C
Definition at line 61 of file seulex.H.
Constructor & Destructor Documentation
seulex()
seulex (const ODESystem & ode, const dictionary & dict)
Definition at line 46 of file seulex.C.
References k, and Foam::min().
~seulex()
virtual ~seulex () virtual default
Member Function Documentation
TypeName()
TypeName ("seulex")
resize()
bool resize () virtual
Implements ODESolver.
Definition at line 210 of file seulex.C.
References ODESolver::resize().
solve()
void solve (scalar & x, scalarField & y, stepState & step) const virtual
Reimplemented from ODESolver.
Definition at line 233 of file seulex.C.
References ODESolver::stepState::dxDid, ODESolver::stepState::dxTry, Foam::endl(), ODESolver::stepState::first, forAll, ODESolver::stepState::forward, k, ODESolver::stepState::last, Foam::log10(), Foam::mag(), Foam::max(), Foam::min(), Foam::pow(), ODESolver::stepState::prevReject, ODESolver::stepState::reject, Foam::sqr(), Foam::sqrt(), success, WarningInFunction, x, and y.
The documentation for this class was generated from the following files:
src/ODE/ODESolvers/seulex/seulex.H
src/ODE/ODESolvers/seulex/seulex.C