OpenFOAM: parseDriver Class Reference
parseDriver Class Reference
Driver for volume, surface, point field expressions.
#include <volumeExprDriver.H>
Public Member Functions
ClassName ("volumeExpr::driver")
parseDriver (const parseDriver &)=delete
void operator= (const parseDriver &)=delete
parseDriver (const fvMesh &mesh, const dictionary &dict=dictionary::null)
parseDriver (const fvMesh &mesh, const parseDriver &driver, const dictionary &dict)
parseDriver (const word &meshName, const fvMesh &mesh)
parseDriver (const dictionary &dict, const fvMesh &mesh)
virtual ~parseDriver ()=default
virtual const fvMesh & mesh () const
virtual label size () const
virtual label pointSize () const
label size (const FieldAssociation geoType) const
bool hasDimensions () const noexcept
const dimensionSet & dimensions () const noexcept
void clearField ()
virtual bool readDict (const dictionary &dict)
virtual unsigned parse (const std::string &expr, size_t pos=0, size_t len=std::string::npos)
const word & resultType () const noexcept
FieldAssociation fieldAssociation () const noexcept
bool isLogical () const noexcept
bool isVolumeData () const noexcept
bool isFaceData () const noexcept
bool isPointData () const noexcept
template<class GeoField >
const GeoField * isResultType () const
template<class GeoField >
const GeoField * isResultType (bool logical, bool dieOnNull=false) const
autoPtr< regIOobject > dupZeroField () const
template<class Type >
void setResult (VolumeField< Type > *ptr, bool logical=false)
template<class Type >
void setResult (SurfaceField< Type > *ptr, bool logical=false)
template<class Type >
void setResult (PointField< Type > *ptr, bool logical=false)
template<class Type >
tmp< VolumeField< Type > > newVolField (const Type &val=pTraits< Type >::zero) const
template<class Type >
tmp< SurfaceField< Type > > newSurfaceField (const Type &val=pTraits< Type >::zero) const
template<class Type >
tmp< PointField< Type > > newPointField (const Type &val=pTraits< Type >::zero) const
template<class Type >
tmp< VolumeField< Type > > getVolField (const word &fldName, bool getOldTime=false)
template<class Type >
tmp< SurfaceField< Type > > getSurfaceField (const word &fldName, bool getOldTime=false)
template<class Type >
tmp< PointField< Type > > getPointField (const word &fldName, bool getOldTime=false)
template<class Type >
tmp< SurfaceField< Type > > cellToFace (const VolumeField< Type > &field) const
template<class Type >
tmp< PointField< Type > > cellToPoint (const VolumeField< Type > &field) const
template<class Type >
tmp< VolumeField< Type > > pointToCell (const PointField< Type > &field) const
template<class Type >
Type volAverage (VolumeField< Type > &fld) const
template<class Type >
Type volSum (VolumeField< Type > &fld) const
template<class Type >
Type areaAverage (SurfaceField< Type > &fld) const
template<class Type >
Type areaSum (SurfaceField< Type > &fld) const
tmp< volScalarField > field_cellVolume () const
tmp< volVectorField > field_cellCentre () const
tmp< surfaceScalarField > field_faceArea () const
tmp< surfaceVectorField > field_faceCentre () const
tmp< surfaceVectorField > field_areaNormal () const
tmp< pointVectorField > field_pointField () const
tmp< volScalarField > field_cellSet (const word &name) const
tmp< volScalarField > field_cellZone (const word &name) const
tmp< surfaceScalarField > field_faceSet (const word &name) const
tmp< surfaceScalarField > field_faceZone (const word &name) const
tmp< pointScalarField > field_pointSet (const word &name) const
tmp< pointScalarField > field_pointZone (const word &name) const
tmp< volScalarField > field_rand (label seed=0, bool gaussian=false) const
tmp< volScalarField > field_randGaussian (label seed=0) const
template<class GeomField >
const GeomField * isResultType () const
template<class GeomField >
const GeomField * isResultType (bool logical, bool dieOnNull) const
template<class Type >
Foam::tmp< Foam::VolumeField< Type > > newVolField (const Type &val) const
template<class Type >
Foam::tmp< Foam::SurfaceField< Type > > newSurfaceField (const Type &val) const
template<class Type >
Foam::tmp< Foam::PointField< Type > > newPointField (const Type &val) const
template<class Type >
Foam::tmp< Foam::SurfaceField< Type > > cellToFace (const VolumeField< Type > &field) const
template<class Type >
Foam::tmp< Foam::PointField< Type > > cellToPoint (const VolumeField< Type > &field) const
template<class Type >
Foam::tmp< Foam::VolumeField< Type > > pointToCell (const PointField< Type > &field) const
Public Member Functions inherited from genericRagelLemonDriver
genericRagelLemonDriver ()
genericRagelLemonDriver (const genericRagelLemonDriver &rhs)=default
genericRagelLemonDriver (genericRagelLemonDriver &&rhs)=default
virtual ~genericRagelLemonDriver ()=default
void clear ()
const std::string & content () const
void content (const std::string &s, size_t pos=0, size_t len=std::string::npos)
std::string::const_iterator cbegin () const
std::string::const_iterator cend () const
size_t parsePosition () const
size_t & parsePosition ()
Ostream & printBuffer (Ostream &os) const
void reportFatal (const std::string &msg) const
void reportFatal (const std::string &msg, size_t pos) const
Public Member Functions inherited from fvExprDriver
TypeName ("fvExprDriver")
declareRunTimeSelectionTable (autoPtr, fvExprDriver, dictionary,(const dictionary &dict, const fvMesh &mesh),(dict, mesh))
declareRunTimeSelectionTable (autoPtr, fvExprDriver, idName,(const word &ident, const fvMesh &mesh),(ident, mesh))
fvExprDriver (enum exprDriver::searchControls search=exprDriver::searchControls::DEFAULT_SEARCH, const dictionary &dict=dictionary::null)
fvExprDriver (const fvExprDriver &rhs, const dictionary &dict)
fvExprDriver (const dictionary &dict)
virtual autoPtr< fvExprDriver > clone ()=delete
virtual ~fvExprDriver ()
bool cacheSets () const
virtual void clearVariables ()
virtual bool hasVariable (const word &name) const
virtual const exprResult & variable (const word &name) const
template<class Type >
bool isVariableOrField (const word &name, const bool wantPointData=false, const label expectSize=-1) const
template<class Type >
tmp< Field< Type > > getVariable (const word &name, const label expectSize, const bool mandatory=true) const
word getFieldClassName (const word &name) const
topoSetSource::sourceType topoSetType (const word &name) const
topoSetSource::sourceType topoZoneType (const word &name) const
topoSetSource::sourceType topoSourceType (const word &name) const
refPtr< labelList > getTopoSetLabels (const word &name, enum topoSetSource::sourceType setType) const
bool isCellZone (const word &name) const
bool isFaceZone (const word &name) const
bool isPointZone (const word &name) const
bool isCellSet (const word &name) const
bool isFaceSet (const word &name) const
bool isPointSet (const word &name) const
virtual void evaluateVariable (const word &varName, const expressions::exprString &expr)
virtual void evaluateVariableRemote (string remote, const word &varName, const expressions::exprString &expr)
template<class Type >
bool isVariable (const word &name, bool wantPointData=false, label expectSize=-1) const
template<class Type >
bool foundField (const word &name) const
word getTypeOfField (const word &fieldName) const
Ostream & writeCommon (Ostream &os, bool debug=false) const
void createWriterAndRead (const word &name)
void tryWrite () const
template<class GeomField >
Foam::tmp< GeomField > getOrReadField (const word &name, const bool mandatory, const bool getOldTime)
template<class GeomField >
Foam::tmp< GeomField > getOrReadPointField (const word &name, const bool mandatory, const bool getOldTime)
template<class GeomField , class Mesh >
Foam::tmp< GeomField > readAndRegister (const word &name, const Mesh &meshRef)
template<class Type >
Foam::tmp< Foam::Field< Type > > getVariable (const word &name, const label expectedSize, const bool mandatory) const
template<class GeomField , class Mesh >
Foam::tmp< GeomField > getOrReadFieldImpl (const word &name, const Mesh &meshRef, bool mandatory, bool getOldTime)
template<class T >
Foam::autoPtr< T > getTopoSet (const fvMesh &mesh, const word &name, SetOrigin &origin) const
Public Member Functions inherited from exprDriver
TypeName ("exprDriver")
exprDriver (const exprDriver &)=delete
void operator= (const exprDriver &)=delete
exprDriver (enum searchControls search=searchControls::DEFAULT_SEARCH, const dictionary &dict=dictionary::null)
exprDriver (const exprDriver &rhs, const dictionary &dict)
exprDriver (const dictionary &dict)
virtual ~exprDriver ()=default
const TimeState * timeState () const noexcept
virtual scalar timeValue () const
virtual scalar deltaT () const
const dictionary & dict () const noexcept
const exprResult & result () const noexcept
exprResult & result () noexcept
void clearResult ()
template<class Type >
tmp< Field< Type > > getResult (bool wantPointData=false)
const word & getResultType () const noexcept
void resetDb (const objectRegistry *obrPtr=nullptr)
void resetDb (const objectRegistry &db)
scalar argValue () const noexcept
int stashedTokenId () const noexcept
int resetStashedTokenId (int tokenId=0) const noexcept
void setDebugging (bool scannerDebug, bool parserDebug)
void setDebugging (const exprDriver &rhs)
bool setCaching (bool on) noexcept
void setSearchBehaviour (enum searchControls search, const bool caching=false)
void setSearchBehaviour (const exprDriver &rhs)
bool debugScanner () const noexcept
bool debugParser () const noexcept
bool prevIterIsOldTime () const
void setArgument (const scalar val) noexcept
void addVariables (const expressions::exprString &expr, bool clear=true)
void addVariables (const UList< expressions::exprString > &list, bool clear=true)
template<class T >
void addUniformVariable (const word &name, const T &val)
bool hasContextObjects () const
const regIOobject * cfindContextIOobject (const word &name) const
template<class ObjType >
const ObjType * cfindContextObject (const word &name) const
void addContextObject (const word &name, const regIOobject *)
void addContextObject (const regIOobject *)
void removeContextObject (const word &name)
void removeContextObject (const regIOobject *)
const contextObjectTableType & contextObjects () const noexcept
contextObjectTableType & contextObjects () noexcept
template<class Type >
bool isFunction (const word &name) const
template<class Type >
Type getFunctionValue (const word &name, const scalar x) const
template<class Type >
void fillFunctionValues (Field< Type > &result, const word &name, const scalarField &input) const
template<class T >
bool isLocalVariable (const word &name, bool wantPointData=false, label expectedSize=-1) const
template<class Type >
tmp< Field< Type > > getLocalVariable (const word &name, label expectSize, const bool mandatory=true) const
template<class Type >
tmp< Field< Type > > evaluate (const expressions::exprString &expr, bool wantPointData=false)
template<class Type >
Type evaluateUniform (const expressions::exprString &expr, bool wantPointData=false)
void evaluateVariable (const word &varName, const expressions::exprString &expr)
template<class Type >
tmp< Field< Type > > newField (const Type &val=pTraits< Type >::zero) const
template<class Type >
tmp< Field< Type > > newPointField (const Type &val=pTraits< Type >::zero) const
expressions::exprString readExpression (const word &name)
label setVariableStrings (const dictionary &dict, bool mandatory=false)
Ostream & writeVariableStrings (Ostream &os, const word &keyword="") const
template<class Type >
void addUniformVariable (const word &name, const Type &val)
template<class Type >
Foam::tmp< Foam::Field< Type > > evaluate (const expressions::exprString &expr, bool wantPointData)
template<class Type >
Foam::tmp< Foam::Field< Type > > getResult (bool wantPointData)
template<class Type >
const Foam::Function1< Type > * getFunction1Ptr (const word &name, const HashTable< refPtr< Function1< Type > > > &tbl, wordList *listFailure)
template<class Type >
Foam::tmp< Foam::Field< Type > > newField (const Type &val) const
template<class Type >
Foam::tmp< Foam::Field< Type > > newPointField (const Type &val) const
Protected Member Functions
template<class Type >
void setInternalFieldResult (const Field< Type > &fld)
tmp< volScalarField > field_cellSelection (const word &name, enum topoSetSource::sourceType setType) const
tmp< surfaceScalarField > field_faceSelection (const word &name, enum topoSetSource::sourceType setType) const
tmp< pointScalarField > field_pointSelection (const word &name, enum topoSetSource::sourceType setType) const
Protected Member Functions inherited from fvExprDriver
void setGlobalScopes (const wordUList &scopes)
virtual exprResult & variable (const word &name)
template<class T >
bool isGlobalVariable (const word &name, const bool wantPointData=false, const label expectedSize=-1) const
const exprResult & lookupGlobal (const word &name) const
template<class Type >
bool isField (const word &name, const bool wantPointData=false, const label expectSize=-1) const
template<class GeomField >
tmp< GeomField > getOrReadField (const word &name, const bool mandatory=true, const bool getOldTime=false)
template<class GeomField >
tmp< GeomField > getOrReadPointField (const word &name, const bool mandatory=true, const bool getOldTime=false)
template<class GeomField , class MeshRef >
tmp< GeomField > getOrReadFieldImpl (const word &name, const MeshRef &meshRef, const bool mandatory=true, const bool getOldTime=false)
template<class GeomField , class MeshRef >
tmp< GeomField > readAndRegister (const word &name, const MeshRef &meshRef)
template<class T >
autoPtr< T > getTopoSet (const fvMesh &mesh, const word &setName, SetOrigin &origin) const
template<class T >
bool updateSet (autoPtr< T > &setPtr, const word &setName, SetOrigin origin) const
virtual void updateSpecialVariables (bool force=false)
virtual bool hasDataToWrite () const
virtual void prepareData (dictionary &dict) const
virtual void getData (const dictionary &dict)
Protected Member Functions inherited from exprDriver
bool searchRegistry () const noexcept
bool searchFiles () const noexcept
bool cacheReadFields () const noexcept
void resetTimeReference (const TimeState *ts)
void resetTimeReference (const TimeState &ts)
void writeFunctions (Ostream &os) const
void fill_random (scalarField &field, label seed=0, const bool gaussian=false) const
virtual bool update ()
virtual exprResult getRemoteResult (const exprDriver &other) const
Protected Attributes
const fvMesh & mesh_
autoPtr< regIOobject > resultField_
word resultType_
bool isLogical_
bool hasDimensions_
expressions::FieldAssociation fieldGeoType_
dimensionSet resultDimensions_
Protected Attributes inherited from genericRagelLemonDriver
std::reference_wrapper< const std::string > content_
size_t start_
size_t length_
size_t position_
Protected Attributes inherited from exprDriver
const dictionary & dict_
exprResult result_
List< expressions::exprString > variableStrings_
HashTable< exprResult > variables_
HashTable< refPtr< Function1< scalar > > > scalarFuncs_
HashTable< refPtr< Function1< vector > > > vectorFuncs_
contextObjectTableType contextObjects_
scalar arg1Value_
const TimeState * timeStatePtr_
const objectRegistry * obrPtr_
int stashedTokenId_
bool debugScanner_
bool debugParser_
bool allowShadowing_
bool prevIterIsOldTime_
searchControls searchCtrl_
Additional Inherited Members
Public Types inherited from genericRagelLemonDriver
typedef size_t location_type
Public Types inherited from exprDriver
enum searchControls {
NO_SEARCH = 0 , SEARCH_REGISTRY = 1 , SEARCH_FILES = 2 , CACHE_READ_FIELDS = 4 ,
DEFAULT_SEARCH = (SEARCH_REGISTRY)
}
typedef HashTable< const regIOobject * > contextObjectTableType
Static Public Member Functions inherited from fvExprDriver
static const fvMesh & defaultMesh ()
static const fvMesh * resetDefaultMesh (const fvMesh &mesh, const bool force=false)
static autoPtr< fvExprDriver > New (const dictionary &dict, const fvMesh &mesh)
static autoPtr< fvExprDriver > New (const dictionary &dict)
static autoPtr< fvExprDriver > New (const word &type, const word &id, const fvMesh &mesh)
Static Public Member Functions inherited from exprDriver
static expressions::exprString readExpression (const word &name, const dictionary &dict)
static List< expressions::exprString > readVariableStrings (const dictionary &dict, const word &name="variables", bool mandatory=false)
Protected Types inherited from fvExprDriver
enum SetOrigin {
INVALID = 0 , NEW , FILE , MEMORY ,
CACHE
}
Static Protected Member Functions inherited from fvExprDriver
static const fvMesh & regionMesh (const dictionary &dict, const fvMesh &mesh, bool readIfNecessary)
template<class T >
static word defaultBoundaryType (const T &)
template<class Type >
static word defaultBoundaryType (const VolumeField< Type > &)
template<class T >
static void correctField (T &)
template<class Type >
static void correctField (VolumeField< Type > &fld)
Static Protected Member Functions inherited from exprDriver
template<class Type >
static Type weightedAverage (const scalarField &weights, const Field< Type > &fld)
template<class Type >
static Type weightedSum (const scalarField &weights, const Field< Type > &fld)
static point getPositionOfMinimum (const scalarField &vals, const pointField &locs)
static point getPositionOfMaximum (const scalarField &vals, const pointField &locs)
Detailed Description
Driver for volume, surface, point field expressions.
Additional Properties
Property Description Required Default
dimensions Dimensions for the expression result no
In addition to the standard mathematical functions, operations and logical and relational operations, the volume expressions support the following driver-specific functions:
Functions
Function Description Number of arguments
vol The cell volumes 0
pos The cell centres 0
pts The cell points 0
area The face area magnitudes 0
fpos The face centres 0
weightAverage Volume or area weighted average 1
weightSum Volume or area weighted sum 1
face The face areaNormal vectors 0
face A surface-field face value 1
point A point-field point value 1
cellToFace Interpolate cell values onto faces 1
cellToPoint Interpolate cell values onto points 1
pointToCell Interpolate point values onto cells 1
reconstruct Reconstruct cell vector from surface scalar 1
rand Random field 0/1
Selections
Function Description Number of arguments
cset Logical vol field corresponding to cellSet 1
fset Logical surf field corresponding to faceSet 1
pset Logical point field corresponding to pointSet 1
czone Logical vol field corresponding to cellZone 1
fzone Logical surf field corresponding to faceZone 1
pzone Logical point field corresponding to pointZone 1
Note
Use namespace debug switch volumeExpr for scanner (2), parser (4) or dictionary controls as per Foam::expressions::exprDriver.
Source files
volumeExprDriver.H
volumeExprDriver.C
Definition at line 226 of file volumeExprDriver.H.
Constructor & Destructor Documentation
parseDriver() [1/5]
parseDriver (const parseDriver &) delete
parseDriver() [2/5]
parseDriver (const fvMesh & mesh, const dictionary & dict = dictionary::null) explicit
Definition at line 79 of file volumeExprDriver.C.
References parseDriver::mesh_, Foam::expressions::NO_DATA, exprDriver::resetDb(), and exprDriver::resetTimeReference().
parseDriver() [3/5]
parseDriver (const fvMesh & mesh, const parseDriver & driver, const dictionary & dict)
Definition at line 99 of file volumeExprDriver.C.
References parseDriver::mesh_, exprDriver::resetDb(), and exprDriver::resetTimeReference().
parseDriver() [4/5]
parseDriver (const word & meshName, const fvMesh & mesh)
Definition at line 120 of file volumeExprDriver.C.
parseDriver() [5/5]
parseDriver (const dictionary & dict, const fvMesh & mesh)
Definition at line 132 of file volumeExprDriver.C.
References parseDriver::mesh_, exprDriver::resetDb(), and exprDriver::resetTimeReference().
~parseDriver()
virtual ~parseDriver () virtual default
Member Function Documentation
setInternalFieldResult()
template<class Type > void setInternalFieldResult (const Field< Type > & fld) protected
Definition at line 30 of file volumeExprDriverTemplates.C.
References Foam::FieldOps::assign(), fld(), parseDriver::isLogical_, parseDriver::isPointData(), string::replace(), exprDriver::result(), and parseDriver::resultType_.
field_cellSelection()
Foam::tmp< Foam::volScalarField > field_cellSelection (const word & name, enum topoSetSource::sourceType setType) const protected
Definition at line 28 of file volumeExprDriverFields.C.
References topoSetSource::CELLSET_SOURCE, topoSetSource::CELLZONE_SOURCE, Foam::exit(), Foam::FatalError, FatalErrorInFunction, fld(), fvExprDriver::getTopoSetLabels(), parseDriver::mesh(), Foam::name(), GeometricField< scalar, fvPatchField, volMesh >::New(), Foam::nl, and Foam::Zero.
field_faceSelection()
Foam::tmp< Foam::surfaceScalarField > field_faceSelection (const word & name, enum topoSetSource::sourceType setType) const protected
Definition at line 69 of file volumeExprDriverFields.C.
References Foam::exit(), topoSetSource::FACESET_SOURCE, topoSetSource::FACEZONE_SOURCE, Foam::FatalError, FatalErrorInFunction, fld(), mesh, Foam::name(), GeometricField< scalar, fvsPatchField, surfaceMesh >::New(), Foam::nl, WarningInFunction, and Foam::Zero.
field_pointSelection()
Foam::tmp< Foam::pointScalarField > field_pointSelection (const word & name, enum topoSetSource::sourceType setType) const protected
Definition at line 145 of file volumeExprDriverFields.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, fld(), mesh, Foam::name(), MeshObject< polyMesh, UpdateableMeshObject, pointMesh >::New(), GeometricField< scalar, pointPatchField, pointMesh >::New(), Foam::nl, topoSetSource::POINTSET_SOURCE, topoSetSource::POINTZONE_SOURCE, and Foam::Zero.
ClassName()
ClassName ("volumeExpr::driver")
operator=()
void operator= (const parseDriver &) delete
mesh()
virtual const fvMesh & mesh () const inline virtual
Implements fvExprDriver.
Definition at line 338 of file volumeExprDriver.H.
References parseDriver::mesh_.
Referenced by parseDriver::field_cellSelection().
size() [1/2]
virtual label size () const inline virtual
Implements fvExprDriver.
Definition at line 344 of file volumeExprDriver.H.
References parseDriver::mesh_.
pointSize()
virtual label pointSize () const inline virtual
Implements fvExprDriver.
Definition at line 350 of file volumeExprDriver.H.
References parseDriver::mesh_.
size() [2/2]
Foam::label size (const FieldAssociation geoType) const inline
Definition at line 23 of file volumeExprDriverI.H.
References Foam::expressions::FACE_DATA, parseDriver::mesh_, Foam::expressions::POINT_DATA, and Foam::expressions::VOLUME_DATA.
hasDimensions()
bool hasDimensions () const inline noexcept
Definition at line 46 of file volumeExprDriverI.H.
dimensions()
const Foam::dimensionSet & dimensions () const inline noexcept
Definition at line 54 of file volumeExprDriverI.H.
clearField()
void clearField ()
Definition at line 185 of file volumeExprDriver.C.
References PtrList< T >::clear(), and Foam::expressions::NO_DATA.
readDict()
bool readDict (const dictionary & dict) virtual
Reimplemented from fvExprDriver.
Definition at line 153 of file volumeExprDriver.C.
References dict, and fvExprDriver::readDict().
parse()
unsigned parse (const std::string & expr, size_t pos = 0, size_t len = std::string::npos) virtual
Implements exprDriver.
Definition at line 170 of file volumeExprDriver.C.
References Foam::pos(), and scanner::process().
resultType()
const word & resultType () const inline noexcept
Definition at line 396 of file volumeExprDriver.H.
References parseDriver::resultType_.
fieldAssociation()
FieldAssociation fieldAssociation () const inline noexcept
Definition at line 402 of file volumeExprDriver.H.
References parseDriver::fieldGeoType_.
isLogical()
bool isLogical () const inline noexcept
Definition at line 408 of file volumeExprDriver.H.
References parseDriver::isLogical_.
isVolumeData()
bool isVolumeData () const inline noexcept
Definition at line 414 of file volumeExprDriver.H.
References parseDriver::fieldGeoType_, and Foam::expressions::VOLUME_DATA.
isFaceData()
bool isFaceData () const inline noexcept
Definition at line 420 of file volumeExprDriver.H.
References Foam::expressions::FACE_DATA, and parseDriver::fieldGeoType_.
isPointData()
bool isPointData () const inline noexcept
Definition at line 426 of file volumeExprDriver.H.
References parseDriver::fieldGeoType_, and Foam::expressions::POINT_DATA.
Referenced by parseDriver::setInternalFieldResult().
isResultType() [1/4]
template<class GeoField > const GeoField * isResultType () const
isResultType() [2/4]
template<class GeoField > const GeoField * isResultType (bool logical, bool dieOnNull = false) const
dupZeroField()
Foam::autoPtr< Foam::regIOobject > dupZeroField () const
Definition at line 197 of file volumeExprDriver.C.
References doLocalCode, Foam::expressions::FACE_DATA, UPtrList< T >::get(), Foam::expressions::POINT_DATA, and Foam::expressions::VOLUME_DATA.
setResult() [1/3]
template<class Type > void setResult (VolumeField< Type > * ptr, bool logical = false)
Definition at line 56 of file volumeExprDriverTemplates.C.
References Foam::expressions::VOLUME_DATA.
setResult() [2/3]
template<class Type > void setResult (SurfaceField< Type > * ptr, bool logical = false)
Definition at line 83 of file volumeExprDriverTemplates.C.
References Foam::expressions::FACE_DATA.
setResult() [3/3]
template<class Type > void setResult (PointField< Type > * ptr, bool logical = false)
Definition at line 110 of file volumeExprDriverTemplates.C.
References Foam::expressions::POINT_DATA.
newVolField() [1/2]
template<class Type > tmp< VolumeField< Type > > newVolField (const Type & val = pTraits< Type >::zero) const
newSurfaceField() [1/2]
template<class Type > tmp< SurfaceField< Type > > newSurfaceField (const Type & val = pTraits< Type >::zero) const
newPointField() [1/2]
template<class Type > tmp< PointField< Type > > newPointField (const Type & val = pTraits< Type >::zero) const
getVolField()
template<class Type > tmp< VolumeField< Type > > getVolField (const word & fldName, bool getOldTime = false)
getSurfaceField()
template<class Type > tmp< SurfaceField< Type > > getSurfaceField (const word & fldName, bool getOldTime = false)
getPointField()
template<class Type > tmp< PointField< Type > > getPointField (const word & fldName, bool getOldTime = false)
cellToFace() [1/2]
template<class Type > tmp< SurfaceField< Type > > cellToFace (const VolumeField< Type > & field) const
cellToPoint() [1/2]
template<class Type > tmp< PointField< Type > > cellToPoint (const VolumeField< Type > & field) const
pointToCell() [1/2]
template<class Type > tmp< VolumeField< Type > > pointToCell (const PointField< Type > & field) const
volAverage()
template<class Type > Type volAverage (VolumeField< Type > & fld) const inline
Definition at line 515 of file volumeExprDriver.H.
References fld(), and exprDriver::weightedAverage().
volSum()
template<class Type > Type volSum (VolumeField< Type > & fld) const inline
Definition at line 522 of file volumeExprDriver.H.
References fld(), and exprDriver::weightedSum().
areaAverage()
template<class Type > Type areaAverage (SurfaceField< Type > & fld) const inline
Definition at line 529 of file volumeExprDriver.H.
References fld(), and exprDriver::weightedAverage().
areaSum()
template<class Type > Type areaSum (SurfaceField< Type > & fld) const inline
Definition at line 540 of file volumeExprDriver.H.
References fld(), and exprDriver::weightedSum().
field_cellVolume()
Foam::tmp< Foam::volScalarField > field_cellVolume () const
Definition at line 187 of file volumeExprDriverFields.C.
References Foam::dimVol, mesh, and GeometricField< scalar, fvPatchField, volMesh >::New().
field_cellCentre()
Foam::tmp< Foam::volVectorField > field_cellCentre () const
Definition at line 200 of file volumeExprDriverFields.C.
References mesh, and tmp< T >::New().
field_faceArea()
Foam::tmp< Foam::surfaceScalarField > field_faceArea () const
Definition at line 207 of file volumeExprDriverFields.C.
References Foam::dimless, mesh, and GeometricField< scalar, fvsPatchField, surfaceMesh >::New().
field_faceCentre()
Foam::tmp< Foam::surfaceVectorField > field_faceCentre () const
Definition at line 220 of file volumeExprDriverFields.C.
References Foam::dimless, mesh, and GeometricField< vector, fvsPatchField, surfaceMesh >::New().
field_areaNormal()
Foam::tmp< Foam::surfaceVectorField > field_areaNormal () const
Definition at line 233 of file volumeExprDriverFields.C.
References Foam::dimless, mesh, and GeometricField< vector, fvsPatchField, surfaceMesh >::New().
field_pointField()
Foam::tmp< Foam::pointVectorField > field_pointField () const
Definition at line 246 of file volumeExprDriverFields.C.
References Foam::dimless, mesh, MeshObject< polyMesh, UpdateableMeshObject, pointMesh >::New(), GeometricField< vector, pointPatchField, pointMesh >::New(), and points.
field_cellSet()
tmp< volScalarField > field_cellSet (const word & name) const inline
field_cellZone()
Foam::tmp< Foam::volScalarField > field_cellZone (const word & name) const inline
Definition at line 75 of file volumeExprDriverI.H.
References topoSetSource::CELLZONE_SOURCE, and Foam::name().
field_faceSet()
Foam::tmp< Foam::surfaceScalarField > field_faceSet (const word & name) const inline
Definition at line 89 of file volumeExprDriverI.H.
References topoSetSource::FACESET_SOURCE, and Foam::name().
field_faceZone()
Foam::tmp< Foam::surfaceScalarField > field_faceZone (const word & name) const inline
Definition at line 103 of file volumeExprDriverI.H.
References topoSetSource::FACEZONE_SOURCE, and Foam::name().
field_pointSet()
Foam::tmp< Foam::pointScalarField > field_pointSet (const word & name) const inline
Definition at line 117 of file volumeExprDriverI.H.
References Foam::name(), and topoSetSource::POINTSET_SOURCE.
field_pointZone()
Foam::tmp< Foam::pointScalarField > field_pointZone (const word & name) const inline
Definition at line 131 of file volumeExprDriverI.H.
References Foam::name(), and topoSetSource::POINTZONE_SOURCE.
field_rand()
Foam::tmp< Foam::volScalarField > field_rand (label seed = 0, bool gaussian = false) const
Definition at line 259 of file volumeExprDriverFields.C.
References Foam::dimless, exprDriver::fill_random(), mesh, and GeometricField< scalar, fvPatchField, volMesh >::New().
Referenced by parseDriver::field_randGaussian().
field_randGaussian()
tmp< volScalarField > field_randGaussian (label seed = 0) const inline
Definition at line 591 of file volumeExprDriver.H.
References parseDriver::field_rand().
isResultType() [3/4]
template<class GeomField > const GeomField * isResultType () const
Definition at line 138 of file volumeExprDriverTemplates.C.
isResultType() [4/4]
template<class GeomField > const GeomField * isResultType (bool logical, bool dieOnNull) const
Definition at line 146 of file volumeExprDriverTemplates.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and Foam::nl.
newVolField() [2/2]
template<class Type > Foam::tmp< Foam::VolumeField< Type > > newVolField (const Type & val) const
Definition at line 224 of file volumeExprDriverTemplates.C.
References Foam::dimless, mesh, and GeometricField< Type, PatchField, GeoMesh >::New().
newSurfaceField() [2/2]
template<class Type > Foam::tmp< Foam::SurfaceField< Type > > newSurfaceField (const Type & val) const
Definition at line 240 of file volumeExprDriverTemplates.C.
References Foam::dimless, mesh, and GeometricField< Type, PatchField, GeoMesh >::New().
newPointField() [2/2]
template<class Type > Foam::tmp< Foam::PointField< Type > > newPointField (const Type & val) const
Definition at line 256 of file volumeExprDriverTemplates.C.
References Foam::dimless, mesh, MeshObject< polyMesh, UpdateableMeshObject, pointMesh >::New(), and GeometricField< Type, pointPatchField, pointMesh >::New().
cellToFace() [2/2]
template<class Type > Foam::tmp< Foam::SurfaceField< Type > > cellToFace (const VolumeField< Type > & field) const
Definition at line 272 of file volumeExprDriverTemplates.C.
References field(), and Foam::fvc::interpolate().
cellToPoint() [2/2]
template<class Type > Foam::tmp< Foam::PointField< Type > > cellToPoint (const VolumeField< Type > & field) const
Definition at line 283 of file volumeExprDriverTemplates.C.
References field(), volPointInterpolation::interpolate(), and mesh.
pointToCell() [2/2]
template<class Type > Foam::tmp< Foam::VolumeField< Type > > pointToCell (const PointField< Type > & field) const
Definition at line 295 of file volumeExprDriverTemplates.C.
References field(), forAll, and Foam::interpolatePointToCell().
Member Data Documentation
mesh_
const fvMesh& mesh_ protected
Definition at line 236 of file volumeExprDriver.H.
Referenced by parseDriver::mesh(), parseDriver::parseDriver(), parseDriver::parseDriver(), parseDriver::parseDriver(), parseDriver::pointSize(), parseDriver::size(), and parseDriver::size().
resultField_
autoPtr<regIOobject> resultField_ protected
Definition at line 239 of file volumeExprDriver.H.
resultType_
word resultType_ protected
Definition at line 244 of file volumeExprDriver.H.
Referenced by parseDriver::resultType(), and parseDriver::setInternalFieldResult().
isLogical_
bool isLogical_ protected
Definition at line 247 of file volumeExprDriver.H.
Referenced by parseDriver::isLogical(), and parseDriver::setInternalFieldResult().
hasDimensions_
bool hasDimensions_ protected
Definition at line 250 of file volumeExprDriver.H.
fieldGeoType_
expressions::FieldAssociation fieldGeoType_ protected
Definition at line 253 of file volumeExprDriver.H.
Referenced by parseDriver::fieldAssociation(), parseDriver::isFaceData(), parseDriver::isPointData(), and parseDriver::isVolumeData().
resultDimensions_
dimensionSet resultDimensions_ protected
Definition at line 256 of file volumeExprDriver.H.
The documentation for this class was generated from the following files:
src/finiteVolume/expressions/volume/volumeExprDriver.H
src/finiteVolume/expressions/volume/volumeExprDriver.C
src/finiteVolume/expressions/volume/volumeExprDriverFields.C
src/finiteVolume/expressions/volume/volumeExprDriverI.H
src/finiteVolume/expressions/volume/volumeExprDriverTemplates.C