OpenFOAM: PointHit< PointType > Class Template Reference
PointHit< PointType > Class Template Reference
Describes the interaction of a object and a (templated) point. It carries the info of a successful hit and (if successful) the interaction point.
#include <pointHit.H>
Public Types
typedef PointType point_type
Public Member Functions
PointHit ()
PointHit (const point_type &p)
PointHit (bool hit, const point_type &p, scalar dist, bool eligibleMiss=false)
bool hit () const noexcept
bool eligibleMiss () const noexcept
const point_type & point () const noexcept
scalar distance () const noexcept
const point_type & hitPoint () const
const point_type & missPoint () const
const point_type & rawPoint () const noexcept
void setHit () noexcept
void setMiss (const bool eligible) noexcept
void setPoint (const point_type &p)
void setDistance (const scalar d) noexcept
void hitPoint (const point_type &p)
template<class AnyPointType >
bool operator< (const PointHit< AnyPointType > &rhs) const noexcept
Detailed Description
template<class PointType>
class Foam::PointHit< PointType >
Describes the interaction of a object and a (templated) point. It carries the info of a successful hit and (if successful) the interaction point.
Definition at line 59 of file pointHit.H.
Member Typedef Documentation
point_type
template<class PointType > typedef PointType point_type
Definition at line 81 of file pointHit.H.
Constructor & Destructor Documentation
PointHit() [1/3]
template<class PointType > PointHit () inline
Definition at line 88 of file pointHit.H.
PointHit() [2/3]
template<class PointType > PointHit (const point_type & p) inline explicit
Definition at line 98 of file pointHit.H.
PointHit() [3/3]
template<class PointType > PointHit (bool hit, const point_type & p, scalar dist, bool eligibleMiss = false) inline
Definition at line 107 of file pointHit.H.
Member Function Documentation
hit()
template<class PointType > bool hit () const inline noexcept
Definition at line 127 of file pointHit.H.
Referenced by triSurfaceTools::calcInterpolationWeights(), face::intersection(), face::ray(), AMIInterpolation::srcPointFace(), and AMIInterpolation::tgtPointFace().
eligibleMiss()
template<class PointType > bool eligibleMiss () const inline noexcept
Definition at line 133 of file pointHit.H.
Referenced by AMIInterpolation::srcPointFace(), and AMIInterpolation::tgtPointFace().
point()
template<class PointType > const point_type & point () const inline noexcept
Definition at line 139 of file pointHit.H.
Referenced by triSurfaceTools::calcInterpolationWeights(), wallBoundedStreamLine::findNearestTet(), tetrahedron< Point, PointRef >::nearestPoint(), AMIInterpolation::srcPointFace(), and AMIInterpolation::tgtPointFace().
distance()
template<class PointType > scalar distance () const inline noexcept
Definition at line 145 of file pointHit.H.
Referenced by triSurfaceTools::calcInterpolationWeights(), wallBoundedStreamLine::findNearestTet(), tetrahedron< Point, PointRef >::nearestPoint(), face::nearestPointClassify(), AMIInterpolation::srcPointFace(), and AMIInterpolation::tgtPointFace().
hitPoint() [1/2]
template<class PointType > const point_type & hitPoint () const inline
Definition at line 151 of file pointHit.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Referenced by face::intersection(), face::nearestPointClassify(), and face::ray().
missPoint()
template<class PointType > const point_type & missPoint () const inline
Definition at line 164 of file pointHit.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
rawPoint()
template<class PointType > const point_type & rawPoint () const inline noexcept
Definition at line 178 of file pointHit.H.
setHit()
template<class PointType > void setHit () inline noexcept
Definition at line 184 of file pointHit.H.
setMiss()
template<class PointType > void setMiss (const bool eligible) inline noexcept
Definition at line 191 of file pointHit.H.
Referenced by face::nearestPointClassify(), and face::ray().
setPoint()
template<class PointType > void setPoint (const point_type & p) inline
Definition at line 198 of file pointHit.H.
References p.
Referenced by face::nearestPointClassify(), and face::ray().
setDistance()
template<class PointType > void setDistance (const scalar d) inline noexcept
Definition at line 204 of file pointHit.H.
Referenced by face::intersection(), face::nearestPointClassify(), face::ray(), AMIInterpolation::srcPointFace(), and AMIInterpolation::tgtPointFace().
hitPoint() [2/2]
template<class PointType > void hitPoint (const point_type & p) inline
Definition at line 210 of file pointHit.H.
References p.
operator<()
template<class PointType > template<class AnyPointType > bool operator< (const PointHit< AnyPointType > & rhs) const inline noexcept
Definition at line 222 of file pointHit.H.
The documentation for this class was generated from the following file:
src/OpenFOAM/meshes/primitiveShapes/objectHit/pointHit.H