OpenFOAM: DispersionModel< CloudType > Class Template Reference
DispersionModel< CloudType > Class Template Reference abstract
Lagrangian particle models » Submodels » Kinematic » Dispersion
Base class for dispersion modelling.
#include <DispersionModel.H>
Public Member Functions
TypeName ("dispersionModel")
declareRunTimeSelectionTable (autoPtr, DispersionModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
DispersionModel (CloudType &owner)
DispersionModel (const dictionary &dict, CloudType &owner, const word &type)
DispersionModel (const DispersionModel< CloudType > &dm)
virtual autoPtr< DispersionModel< CloudType > > clone () const =0
virtual ~DispersionModel ()
virtual vector update (const scalar dt, const label celli, const vector &U, const vector &Uc, vector &UTurb, scalar &tTurb)=0
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
virtual ~CloudSubModelBase ()=default
const CloudType & owner () const
virtual bool writeTime () const
virtual fileName localPath () const
CloudType & owner ()
virtual void info ()
virtual void write (Ostream &os) const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
subModelBase (const subModelBase &smb)
virtual ~subModelBase ()=default
const word & modelName () const
const dictionary & dict () const
const word & baseName () const
const word & modelType () const
const dictionary & coeffDict () const
const dictionary & properties () const
virtual bool defaultCoeffs (const bool printMsg) const
virtual bool active () const
virtual void cacheFields (const bool store)
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
bool getModelDict (const word &entryName, dictionary &dict) const
template<class Type >
bool getModelProperty (const word &entryName, Type &value) const
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Static Public Member Functions
static autoPtr< DispersionModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Additional Inherited Members
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Public Attributes inherited from subModelBase
bool log
Protected Member Functions inherited from subModelBase
bool inLine () const
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Protected Attributes inherited from subModelBase
const word modelName_
dictionary & properties_
const dictionary dict_
const word baseName_
const word modelType_
const dictionary coeffDict_
Detailed Description
template<class CloudType>
class Foam::DispersionModel< CloudType >
Base class for dispersion modelling.
Definition at line 48 of file DispersionModel.H.
Constructor & Destructor Documentation
DispersionModel() [1/3]
template<class CloudType > DispersionModel (CloudType & owner)
Definition at line 26 of file DispersionModel.C.
DispersionModel() [2/3]
template<class CloudType > DispersionModel (const dictionary & dict, CloudType & owner, const word & type)
Definition at line 33 of file DispersionModel.C.
DispersionModel() [3/3]
template<class CloudType > DispersionModel (const DispersionModel< CloudType > & dm)
Definition at line 45 of file DispersionModel.C.
~DispersionModel()
template<class CloudType > ~DispersionModel () virtual
Definition at line 57 of file DispersionModel.C.
Member Function Documentation
TypeName()
template<class CloudType > TypeName ("dispersionModel")
declareRunTimeSelectionTable()
template<class CloudType > declareRunTimeSelectionTable (autoPtr , DispersionModel< CloudType > , dictionary , (const dictionary &dict, CloudType &owner) , (dict, owner))
clone()
template<class CloudType > virtual autoPtr< DispersionModel< CloudType > > clone () const pure virtual
Implemented in NoDispersion< CloudType >, GradientDispersionRAS< CloudType >, StochasticDispersionRAS< CloudType >, and DispersionRASModel< CloudType >.
New()
template<class CloudType > Foam::autoPtr< Foam::DispersionModel< CloudType > > New (const dictionary & dict, CloudType & owner) static
Definition at line 28 of file DispersionModelNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, Foam::Info, and PtrList< T >::PtrList().
update()
template<class CloudType > virtual vector update (const scalar dt, const label celli, const vector & U, const vector & Uc, vector & UTurb, scalar & tTurb) pure virtual
Implemented in NoDispersion< CloudType >, GradientDispersionRAS< CloudType >, StochasticDispersionRAS< CloudType >, and DispersionRASModel< CloudType >.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/clouds/Templates/KinematicCloud/KinematicCloud.H
src/lagrangian/intermediate/submodels/Kinematic/DispersionModel/DispersionModel/DispersionModel.H
src/lagrangian/intermediate/submodels/Kinematic/DispersionModel/DispersionModel/DispersionModel.C
src/lagrangian/intermediate/submodels/Kinematic/DispersionModel/DispersionModel/DispersionModelNew.C