OpenFOAM: masterUncollatedFileOperation::fileOrNullOp Class Reference
masterUncollatedFileOperation::fileOrNullOp Class Reference
#include <masterUncollatedFileOperation.H>
Public Member Functions
fileOrNullOp (const bool isFile)
const fileName & operator() (const fileName &f) const
Detailed Description
Definition at line 339 of file masterUncollatedFileOperation.H.
Constructor & Destructor Documentation
fileOrNullOp()
fileOrNullOp (const bool isFile) inline
Definition at line 343 of file masterUncollatedFileOperation.H.
Member Function Documentation
operator()()
const fileName & operator() (const fileName & f) const inline
Definition at line 348 of file masterUncollatedFileOperation.H.
References f(), Foam::isDir(), Foam::isFile(), and fileName::null.
The documentation for this class was generated from the following file:
src/OpenFOAM/global/fileOperations/masterUncollatedFileOperation/masterUncollatedFileOperation.H