OpenFOAM: filmBoilingModel Class Reference
filmBoilingModel Class Reference abstract
#include <filmBoilingModel.H>
Public Member Functions
TypeName ("filmBoilingModel")
declareRunTimeSelectionTable (autoPtr, filmBoilingModel, dictionary,(const dictionary &dict),(dict))
filmBoilingModel ()=default
virtual ~filmBoilingModel ()=default
virtual tmp< scalarField > htcFilmBoil (const phaseModel &liquid, const phaseModel &vapor, const label patchi, const scalarField &Tl, const scalarField &Tsatw, const scalarField &L) const =0
virtual void write (Ostream &os) const
Static Public Member Functions
static autoPtr< filmBoilingModel > New (const dictionary &dict)
Detailed Description
Definition at line 52 of file filmBoilingModel.H.
Constructor & Destructor Documentation
filmBoilingModel()
filmBoilingModel () default
~filmBoilingModel()
virtual ~filmBoilingModel () virtual default
Member Function Documentation
TypeName()
TypeName ("filmBoilingModel")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , filmBoilingModel , dictionary , (const dictionary &dict) , (dict))
New()
Foam::autoPtr< Foam::wallBoilingModels::filmBoilingModel > New (const dictionary & dict) static
Definition at line 38 of file filmBoilingModel.C.
References Foam::abort(), dict, Foam::endl(), Foam::FatalIOError, FatalIOErrorInLookup, and Foam::Info.
Referenced by alphatWallBoilingWallFunctionFvPatchScalarField::alphatWallBoilingWallFunctionFvPatchScalarField().
htcFilmBoil()
virtual tmp< scalarField > htcFilmBoil (const phaseModel & liquid, const phaseModel & vapor, const label patchi, const scalarField & Tl, const scalarField & Tsatw, const scalarField & L) const pure virtual
Implemented in BreenWestwater, and Bromley.
write()
void write (Ostream & os) const virtual
Reimplemented in BreenWestwater, and Bromley.
Definition at line 66 of file filmBoilingModel.C.
References os(), and Foam::type().
Referenced by BreenWestwater::write(), and Bromley::write().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/wallBoilingSubModels/filmBoilingModels/filmBoilingModel/filmBoilingModel.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/wallBoilingSubModels/filmBoilingModels/filmBoilingModel/filmBoilingModel.C