OpenFOAM: patchFunction1Base Class Reference
patchFunction1Base Class Reference
Top level data entry class for use in dictionaries. Provides a mechanism to specify a variable as a certain type, e.g. constant or time varying, and provide functions to return the (interpolated) value, and integral between limits.
#include <patchFunction1Base.H>
Public Member Functions
patchFunction1Base (const polyPatch &pp, const word &entryName, const bool faceValues=true)
patchFunction1Base (const polyPatch &pp, const word &entryName, const dictionary &dict, const bool faceValues=true)
patchFunction1Base (const patchFunction1Base &rhs)
patchFunction1Base (const patchFunction1Base &rhs, const polyPatch &pp)
virtual ~patchFunction1Base ()=default
const word & name () const noexcept
const polyPatch & patch () const noexcept
bool faceValues () const noexcept
label size () const
const objectRegistry * whichDb () const
const objectRegistry & obr () const
const Time & time () const
virtual void userTimeToTime (const Time &t)
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Protected Member Functions
void operator= (const patchFunction1Base &)=delete
Protected Attributes
const word name_
const polyPatch & patch_
const bool faceValues_
Detailed Description
Top level data entry class for use in dictionaries. Provides a mechanism to specify a variable as a certain type, e.g. constant or time varying, and provide functions to return the (interpolated) value, and integral between limits.
Extends the Function1 class by adding autoMap and rMap functions
Source files
patchFunction1Base.H
patchFunction1Base.C
Definition at line 56 of file patchFunction1Base.H.
Constructor & Destructor Documentation
patchFunction1Base() [1/4]
patchFunction1Base (const polyPatch & pp, const word & entryName, const bool faceValues = true)
Definition at line 30 of file patchFunction1Base.C.
patchFunction1Base() [2/4]
patchFunction1Base (const polyPatch & pp, const word & entryName, const dictionary & dict, const bool faceValues = true)
Definition at line 44 of file patchFunction1Base.C.
patchFunction1Base() [3/4]
patchFunction1Base (const patchFunction1Base & rhs) explicit
Definition at line 59 of file patchFunction1Base.C.
patchFunction1Base() [4/4]
patchFunction1Base (const patchFunction1Base & rhs, const polyPatch & pp) explicit
Definition at line 65 of file patchFunction1Base.C.
~patchFunction1Base()
virtual ~patchFunction1Base () virtual default
Member Function Documentation
operator=()
void operator= (const patchFunction1Base &) protected delete
name()
const word & name () const inline noexcept
Definition at line 121 of file patchFunction1Base.H.
References patchFunction1Base::name_.
patch()
const polyPatch & patch () const inline noexcept
Definition at line 127 of file patchFunction1Base.H.
References patchFunction1Base::patch_.
faceValues()
bool faceValues () const inline noexcept
Definition at line 133 of file patchFunction1Base.H.
References patchFunction1Base::faceValues_.
size()
label size () const inline
Definition at line 139 of file patchFunction1Base.H.
References patchFunction1Base::faceValues_, patchFunction1Base::patch_, and UPtrList< T >::size().
Referenced by ConstantField< Type >::ConstantField(), and ConstantField< Type >::ConstantField().
whichDb()
const Foam::objectRegistry * whichDb () const
Definition at line 80 of file patchFunction1Base.C.
Referenced by UniformValueField< Type >::UniformValueField().
obr()
const Foam::objectRegistry & obr () const
Definition at line 86 of file patchFunction1Base.C.
time()
const Foam::Time & time () const
bool isTime() const noexcept { return false; }
Definition at line 92 of file patchFunction1Base.C.
userTimeToTime()
void userTimeToTime (const Time & t) virtual
Definition at line 98 of file patchFunction1Base.C.
Member Data Documentation
name_
const word name_ protected
Definition at line 65 of file patchFunction1Base.H.
Referenced by patchFunction1Base::name().
patch_
const polyPatch& patch_ protected
Definition at line 68 of file patchFunction1Base.H.
Referenced by patchFunction1Base::patch(), and patchFunction1Base::size().
faceValues_
const bool faceValues_ protected
Definition at line 71 of file patchFunction1Base.H.
Referenced by patchFunction1Base::faceValues(), and patchFunction1Base::size().
The documentation for this class was generated from the following files:
src/meshTools/PatchFunction1/PatchFunction1/patchFunction1Base.H
src/meshTools/PatchFunction1/PatchFunction1/patchFunction1Base.C