OpenFOAM: cutCellIso Class Reference
cutCellIso Class Reference
Class for cutting a cell, celli, of an fvMesh, mesh_, at its intersection with an isosurface defined by the mesh point values f_ and the cutValue, isoValue_.
#include <cutCellIso.H>
Public Member Functions
cutCellIso (const fvMesh &mesh, scalarField &f)
label calcSubCell (const label cellI, const scalar cutValue)
const point & subCellCentre () const noexcept
scalar subCellVolume () const noexcept
const DynamicList< point > & facePoints ()
const point & faceCentre () const noexcept
const vector & faceArea () const noexcept
label cellStatus () const noexcept
scalar VolumeOfFluid () const noexcept
scalar cutValue () const noexcept
void clearStorage ()
Public Member Functions inherited from cutCell
cutCell (const fvMesh &mesh)
Additional Inherited Members
Static Public Attributes inherited from cutCell
static int debug = 0
Static Protected Member Functions inherited from cutCell
static void calcCellData (const DynamicList< point > &cutFaceCentres, const DynamicList< vector > &cutFaceAreas, vector &subCellCentre, scalar &subCellVolume)
static void calcGeomDataCutFace (const DynamicList< DynamicList< point > > &faceEdges, const vector &subCellCentre, vector &faceArea, vector &faceCentre)
static void calcIsoFacePointsFromEdges (const vector &faceArea, const vector &faceCentre, const DynamicList< DynamicList< point > > &faceEdges, DynamicList< point > &facePoints)
Detailed Description
Class for cutting a cell, celli, of an fvMesh, mesh_, at its intersection with an isosurface defined by the mesh point values f_ and the cutValue, isoValue_.
Reference:
    Roenby, J., Bredmose, H. and Jasak, H. (2016).
    A computational method for sharp interface advection
    Royal Society Open Science, 3
    doi 10.1098/rsos.160405
    Henning Scheufler, Johan Roenby,
    Accurate and efficient surface reconstruction from volume
    fraction data on general meshes,
    Journal of Computational Physics, 2019,
    doi 10.1016/j.jcp.2019.01.009
Original code supplied by Johan Roenby, DHI (2016)
Source files
cutCellIso.H
cutCellIso.C
Definition at line 72 of file cutCellIso.H.
Constructor & Destructor Documentation
cutCellIso()
cutCellIso (const fvMesh & mesh, scalarField & f)
Definition at line 27 of file cutCellIso.C.
References cutCellIso::clearStorage().
Member Function Documentation
calcSubCell()
Foam::label calcSubCell (const label cellI, const scalar cutValue)
Definition at line 52 of file cutCellIso.C.
References PtrList< T >::append(), Foam::average(), Foam::mag(), and Foam::Zero.
subCellCentre()
const point & subCellCentre () const inline noexcept
Definition at line 146 of file cutCellIso.H.
Referenced by surfaceIteratorIso::subCellCentre().
subCellVolume()
scalar subCellVolume () const inline noexcept
Definition at line 152 of file cutCellIso.H.
Referenced by surfaceIteratorIso::subCellVolume().
facePoints()
const Foam::DynamicList< Foam::point > & facePoints ()
Definition at line 166 of file cutCellIso.C.
Referenced by surfaceIteratorIso::facePoints().
faceCentre()
const point & faceCentre () const inline noexcept
Definition at line 161 of file cutCellIso.H.
Referenced by surfaceIteratorIso::surfaceCentre().
faceArea()
const vector & faceArea () const inline noexcept
Definition at line 167 of file cutCellIso.H.
Referenced by surfaceIteratorIso::surfaceArea().
cellStatus()
label cellStatus () const inline noexcept
Definition at line 173 of file cutCellIso.H.
Referenced by surfaceIteratorIso::cellStatus().
VolumeOfFluid()
scalar VolumeOfFluid () const inline noexcept
Definition at line 179 of file cutCellIso.H.
Referenced by surfaceIteratorIso::VolumeOfFluid().
cutValue()
scalar cutValue () const inline noexcept
Definition at line 185 of file cutCellIso.H.
Referenced by surfaceIteratorIso::cutValue().
clearStorage()
void clearStorage ()
Definition at line 184 of file cutCellIso.C.
References PtrList< T >::clear(), and Foam::Zero.
Referenced by cutCellIso::cutCellIso().
The documentation for this class was generated from the following files:
src/transportModels/geometricVoF/cellCuts/cutCell/cutCellIso.H
src/transportModels/geometricVoF/cellCuts/cutCell/cutCellIso.C