OpenFOAM: lduPrimitiveMesh Class Reference
lduPrimitiveMesh Class Reference
Simplest concrete lduMesh that stores the addressing needed by lduMatrix.
#include <lduPrimitiveMesh.H>
Public Member Functions
ClassName ("lduPrimitiveMesh")
lduPrimitiveMesh (const label nCells)
lduPrimitiveMesh (const label nCells, labelList &l, labelList &u, const label comm, bool reuse)
void addInterfaces (lduInterfacePtrsList &interfaces, const lduSchedule &ps)
lduPrimitiveMesh (const label nCells, labelList &l, labelList &u, PtrList< const lduInterface > &primitiveInterfaces, const lduSchedule &ps, const label comm)
lduPrimitiveMesh (const label comm, const labelList &procAgglomMap, const labelList &procIDs, const lduMesh &myMesh, const PtrList< lduPrimitiveMesh > &otherMeshes, labelList &cellOffsets, labelList &faceOffsets, labelListList &faceMap, labelListList &boundaryMap, labelListListList &boundaryFaceMap)
virtual ~lduPrimitiveMesh ()=default
virtual bool hasDb () const
virtual const lduAddressing & lduAddr () const
virtual lduAddressing & lduAddr ()
virtual lduInterfacePtrsList interfaces () const
virtual lduInterfacePtrsList & interfaces ()
PtrList< const lduInterface > & primitiveInterfaces ()
const lduInterfacePtrsList & rawInterfaces () const
virtual label comm () const
virtual const labelUList & lowerAddr () const
virtual const labelUList & upperAddr () const
virtual labelList & lowerAddr ()
virtual labelList & upperAddr ()
virtual const labelUList & patchAddr (const label i) const
virtual const lduSchedule & patchSchedule () const
template<class ProcPatch >
Foam::lduSchedule nonBlockingSchedule (const lduInterfacePtrsList &interfaces)
Public Member Functions inherited from lduMesh
TypeName ("lduMesh")
virtual ~lduMesh ()=default
virtual const objectRegistry & thisDb () const
template<class T , class BinaryOp >
void reduce (T &Value, const BinaryOp &bop) const
InfoProxy< lduMesh > info () const noexcept
Public Member Functions inherited from lduAddressing
lduAddressing (const label nEqns)
virtual ~lduAddressing ()
label size () const
void clearOut ()
const labelUList & losortAddr () const
const labelUList & ownerStartAddr () const
const labelUList & losortStartAddr () const
label triIndex (const label a, const label b) const
Tuple2< label, scalar > band () const
Static Public Member Functions
static const lduMesh & mesh (const lduMesh &mesh0, const PtrList< lduPrimitiveMesh > &otherMeshes, const label meshI)
static void gather (const label comm, const lduMesh &mesh, const labelList &procIDs, PtrList< lduPrimitiveMesh > &otherMeshes)
template<class ProcPatch >
static lduSchedule nonBlockingSchedule (const lduInterfacePtrsList &)
static labelList upperTriOrder (const label nCells, const labelUList &lower, const labelUList &upper)
static void checkUpperTriangular (const label size, const labelUList &l, const labelUList &u)
static labelListList globalCellCells (const lduMesh &mesh, const globalIndex &globalNumbering)
Detailed Description
Simplest concrete lduMesh that stores the addressing needed by lduMatrix.
Source files
lduPrimitiveMesh.H
lduPrimitiveMesh.C
Definition at line 48 of file lduPrimitiveMesh.H.
Constructor & Destructor Documentation
lduPrimitiveMesh() [1/4]
lduPrimitiveMesh (const label nCells) explicit
Definition at line 366 of file lduPrimitiveMesh.C.
lduPrimitiveMesh() [2/4]
lduPrimitiveMesh (const label nCells, labelList & l, labelList & u, const label comm, bool reuse)
Definition at line 306 of file lduPrimitiveMesh.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::max(), Foam::min(), and UList< T >::size().
lduPrimitiveMesh() [3/4]
lduPrimitiveMesh (const label nCells, labelList & l, labelList & u, PtrList< const lduInterface > & primitiveInterfaces, const lduSchedule & ps, const label comm)
Definition at line 376 of file lduPrimitiveMesh.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::max(), Foam::min(), lduPrimitiveMesh::primitiveInterfaces(), PtrList< T >::set(), UPtrList< T >::set(), UPtrList< T >::setSize(), UPtrList< T >::size(), UList< T >::size(), and PtrList< T >::transfer().
lduPrimitiveMesh() [4/4]
lduPrimitiveMesh (const label comm, const labelList & procAgglomMap, const labelList & procIDs, const lduMesh & myMesh, const PtrList< lduPrimitiveMesh > & otherMeshes, labelList & cellOffsets, labelList & faceOffsets, labelListList & faceMap, labelListList & boundaryMap, labelListListList & boundaryFaceMap)
Definition at line 431 of file lduPrimitiveMesh.C.
References Foam::abort(), PtrList< T >::append(), lduPrimitiveMesh::checkUpperTriangular(), lduPrimitiveMesh::comm(), Foam::endl(), Foam::exit(), Foam::faceMap(), Foam::FatalError, FatalErrorInFunction, Foam::findIndices(), forAll, forAllConstIters, Foam::inplaceReorder(), lduPrimitiveMesh::interfaces(), UList< T >::last(), Foam::max(), mesh, Foam::min(), UPstream::msgType(), UPstream::myProcNo(), n, Foam::Pout, PtrList< T >::set(), UPtrList< T >::set(), List< T >::setSize(), UPtrList< T >::setSize(), PtrList< T >::setSize(), UPtrList< T >::size(), UList< T >::size(), Foam::sortedOrder(), lduPrimitiveMesh::upperTriOrder(), WarningInFunction, and Foam::Zero.
~lduPrimitiveMesh()
virtual ~lduPrimitiveMesh () virtual default
Member Function Documentation
ClassName()
ClassName ("lduPrimitiveMesh")
addInterfaces()
void addInterfaces (lduInterfacePtrsList & interfaces, const lduSchedule & ps)
Definition at line 345 of file lduPrimitiveMesh.C.
References forAll, PtrList< T >::set(), and PtrList< T >::setSize().
hasDb()
virtual bool hasDb () const inline virtual
Implements lduMesh.
Reimplemented in lduPrimitiveMeshAssembly.
Definition at line 177 of file lduPrimitiveMesh.H.
lduAddr() [1/2]
virtual const lduAddressing & lduAddr () const inline virtual
Implements lduMesh.
Definition at line 183 of file lduPrimitiveMesh.H.
Referenced by fvMatrix< Type >::createOrUpdateLduPrimitiveAssembly(), and lduPrimitiveMeshAssembly::update().
lduAddr() [2/2]
virtual lduAddressing & lduAddr () inline virtual
Definition at line 189 of file lduPrimitiveMesh.H.
interfaces() [1/2]
virtual lduInterfacePtrsList interfaces () const inline virtual
Implements lduMesh.
Definition at line 196 of file lduPrimitiveMesh.H.
Referenced by lduPrimitiveMesh::lduPrimitiveMesh(), lduPrimitiveMesh::nonBlockingSchedule(), and lduPrimitiveMeshAssembly::update().
interfaces() [2/2]
virtual lduInterfacePtrsList & interfaces () inline virtual
Definition at line 203 of file lduPrimitiveMesh.H.
primitiveInterfaces()
PtrList< const lduInterface > & primitiveInterfaces () inline
Definition at line 209 of file lduPrimitiveMesh.H.
Referenced by lduPrimitiveMesh::lduPrimitiveMesh(), and lduPrimitiveMeshAssembly::update().
rawInterfaces()
const lduInterfacePtrsList & rawInterfaces () const inline
Definition at line 217 of file lduPrimitiveMesh.H.
comm()
virtual label comm () const inline virtual
Implements lduMesh.
Definition at line 223 of file lduPrimitiveMesh.H.
Referenced by lduPrimitiveMesh::lduPrimitiveMesh(), and lduPrimitiveMeshAssembly::lduPrimitiveMeshAssembly().
lowerAddr() [1/2]
virtual const labelUList & lowerAddr () const inline virtual
Implements lduAddressing.
Definition at line 229 of file lduPrimitiveMesh.H.
Referenced by lduPrimitiveMeshAssembly::update().
upperAddr() [1/2]
virtual const labelUList & upperAddr () const inline virtual
Implements lduAddressing.
Definition at line 235 of file lduPrimitiveMesh.H.
Referenced by lduPrimitiveMeshAssembly::update().
lowerAddr() [2/2]
virtual labelList & lowerAddr () inline virtual
Definition at line 241 of file lduPrimitiveMesh.H.
upperAddr() [2/2]
virtual labelList & upperAddr () inline virtual
Definition at line 247 of file lduPrimitiveMesh.H.
patchAddr()
virtual const labelUList & patchAddr (const label i) const inline virtual
Implements lduAddressing.
Reimplemented in lduPrimitiveMeshAssembly.
Definition at line 253 of file lduPrimitiveMesh.H.
patchSchedule()
virtual const lduSchedule & patchSchedule () const inline virtual
Implements lduAddressing.
Definition at line 259 of file lduPrimitiveMesh.H.
mesh()
const Foam::lduMesh & mesh (const lduMesh & mesh0, const PtrList< lduPrimitiveMesh > & otherMeshes, const label meshI) static
Definition at line 1092 of file lduPrimitiveMesh.C.
gather()
void gather (const label comm, const lduMesh & mesh, const labelList & procIDs, PtrList< lduPrimitiveMesh > & otherMeshes) static
Definition at line 1103 of file lduPrimitiveMesh.C.
References forAll, interface(), fvMesh::interfaces(), fvMesh::lduAddr(), lduAddressing::lowerAddr(), mesh, UPstream::msgType(), UPstream::myProcNo(), GAMGInterface::New(), Foam::readLabel(), Foam::refCast(), UPstream::scheduled, PtrList< T >::set(), UPtrList< T >::set(), PtrList< T >::setSize(), lduAddressing::size(), UPtrList< T >::size(), and lduAddressing::upperAddr().
Referenced by GAMGAgglomeration::procAgglomerateLduAddressing().
nonBlockingSchedule() [1/2]
template<class ProcPatch > static lduSchedule nonBlockingSchedule (const lduInterfacePtrsList &) static
Referenced by viewFactor::initialise().
upperTriOrder()
Foam::labelList upperTriOrder (const label nCells, const labelUList & lower, const labelUList & upper) static
Definition at line 231 of file lduPrimitiveMesh.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, UList< T >::last(), PtrList< T >::resize(), Foam::sortedOrder(), and Foam::Zero.
Referenced by fvMeshPrimitiveLduAddressing::addAddressing(), lduPrimitiveMesh::lduPrimitiveMesh(), and lduPrimitiveMeshAssembly::update().
checkUpperTriangular()
void checkUpperTriangular (const label size, const labelUList & l, const labelUList & u) static
Definition at line 38 of file lduPrimitiveMesh.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, lduAddressing::size(), and UList< T >::size().
Referenced by lduPrimitiveMesh::lduPrimitiveMesh(), and lduPrimitiveMeshAssembly::update().
globalCellCells()
Foam::labelListList globalCellCells (const lduMesh & mesh, const globalIndex & globalNumbering) static
Definition at line 91 of file lduPrimitiveMesh.C.
References fvMesh::comm(), forAll, Foam::identity(), fvMesh::interfaces(), fvMesh::lduAddr(), globalIndex::localStart(), mesh, UPstream::myProcNo(), UPstream::nonBlocking, UPstream::nRequests(), PtrList< T >::set(), UPtrList< T >::set(), List< T >::setSize(), UPtrList< T >::size(), UPstream::waitRequests(), and Foam::Zero.
nonBlockingSchedule() [2/2]
template<class ProcPatch > Foam::lduSchedule nonBlockingSchedule (const lduInterfacePtrsList & interfaces)
Definition at line 27 of file lduPrimitiveMeshTemplates.C.
References forAll, lduPrimitiveMesh::interfaces(), PtrList< T >::set(), and UPtrList< T >::size().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/lduMesh/lduPrimitiveMesh.H
src/OpenFOAM/meshes/lduMesh/lduPrimitiveMesh.C
src/OpenFOAM/meshes/lduMesh/lduPrimitiveMeshTemplates.C