OpenFOAM: polynomialTransport< Thermo, PolySize > Class Template Reference
polynomialTransport< Thermo, PolySize > Class Template Reference
Thermophysical models » Specie » Transport
Transport package using polynomial functions for mu and kappa.
#include <polynomialTransport.H>
Public Member Functions
polynomialTransport (const word &, const polynomialTransport &)
polynomialTransport (const dictionary &dict)
autoPtr< polynomialTransport > clone () const
scalar mu (const scalar p, const scalar T) const
scalar kappa (const scalar p, const scalar T) const
scalar alphah (const scalar p, const scalar T) const
void write (Ostream &os) const
void operator+= (const polynomialTransport &)
void operator*= (const scalar)
Static Public Member Functions
static autoPtr< polynomialTransport > New (const dictionary &dict)
static word typeName ()
Friends
polynomialTransport operator+ (const polynomialTransport &, const polynomialTransport &)
polynomialTransport operator* (const scalar, const polynomialTransport &)
Ostream & operator (Ostream &, const polynomialTransport &)
Detailed Description
template<class Thermo, int PolySize = 8>
class Foam::polynomialTransport< Thermo, PolySize >
Transport package using polynomial functions for mu and kappa.
Usage
Property Description
muCoeffs<8> Dynamic viscosity polynomial coefficients
kappaCoeffs<8> Thermal conductivity polynomial coefficients
Example of the specification of the transport properties:
    transport
    {
        muCoeffs<8>     ( 1000 -0.05 0.003 0 0 0 0 0 );
        kappaCoeffs<8>  ( 2000 -0.15 0.023 0 0 0 0 0 );
    }
The polynomial expressions are evaluated as so:
Note
Dynamic viscosity polynomial coefficients evaluate to an expression in [Pa.s], but internally uses [Pa.s/kmol].
Thermal conductivity polynomial coefficients evaluate to an expression in [W/m/K], but internally uses [W/m/K/kmol].
Source files
polynomialTransport.H
polynomialTransportI.H
polynomialTransport.C
See also
Foam::Polynomial
Definition at line 123 of file polynomialTransport.H.
Constructor & Destructor Documentation
polynomialTransport() [1/2]
template<class Thermo , int PolySize> polynomialTransport (const word & name, const polynomialTransport< Thermo, PolySize > & pt) inline
Definition at line 40 of file polynomialTransportI.H.
References Foam::name().
polynomialTransport() [2/2]
template<class Thermo , int PolySize> polynomialTransport (const dictionary & dict) explicit
Definition at line 27 of file polynomialTransport.C.
Member Function Documentation
clone()
template<class Thermo , int PolySize> Foam::autoPtr< Foam::polynomialTransport< Thermo, PolySize > > clone () const inline
Definition at line 54 of file polynomialTransportI.H.
References Foam::New().
New()
template<class Thermo , int PolySize> Foam::autoPtr< Foam::polynomialTransport< Thermo, PolySize > > New (const dictionary & dict) inline static
Definition at line 62 of file polynomialTransportI.H.
References dict, and Foam::New().
typeName()
template<class Thermo , int PolySize = 8> static word typeName () inline static
Definition at line 176 of file polynomialTransport.H.
mu()
template<class Thermo , int PolySize> Foam::scalar mu (const scalar p, const scalar T) const inline
Definition at line 71 of file polynomialTransportI.H.
References T.
kappa()
template<class Thermo , int PolySize> Foam::scalar kappa (const scalar p, const scalar T) const inline
Definition at line 82 of file polynomialTransportI.H.
References T.
alphah()
template<class Thermo , int PolySize> Foam::scalar alphah (const scalar p, const scalar T) const inline
Definition at line 93 of file polynomialTransportI.H.
References Cp, p, and T.
write()
template<class Thermo , int PolySize> void write (Ostream & os) const
Definition at line 41 of file polynomialTransport.C.
References Ostream::beginBlock(), Ostream::endBlock(), Foam::name(), os(), and Ostream::writeEntry().
operator+=()
template<class Thermo , int PolySize = 8> void operator+= (const polynomialTransport< Thermo, PolySize > &) inline
Definition at line 105 of file polynomialTransportI.H.
References Foam::mag(), and Y.
operator*=()
template<class Thermo , int PolySize> void operator*= (const scalar s) inline
Definition at line 126 of file polynomialTransportI.H.
References s().
Friends And Related Symbol Documentation
operator+
template<class Thermo , int PolySize = 8> polynomialTransport operator+ (const polynomialTransport< Thermo, PolySize > & , const polynomialTransport< Thermo, PolySize > &) friend
operator*
template<class Thermo , int PolySize = 8> polynomialTransport operator* (const scalar , const polynomialTransport< Thermo, PolySize > &) friend
operator
template<class Thermo , int PolySize = 8> Ostream & operator (Ostream & , const polynomialTransport< Thermo, PolySize > &) friend
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/transport/polynomial/polynomialTransport.H
src/thermophysicalModels/specie/transport/polynomial/polynomialTransport.C
src/thermophysicalModels/specie/transport/polynomial/polynomialTransportI.H