OpenFOAM: tabulatedTransport< Thermo > Class Template Reference
tabulatedTransport< Thermo > Class Template Reference
Transport properties package using non-uniform tabulated data for viscosity and thermal conductivity vs temperature.
#include <tabulatedTransport.H>
Public Member Functions
tabulatedTransport (const word &, const tabulatedTransport &)
tabulatedTransport (const dictionary &dict)
autoPtr< tabulatedTransport > clone () const
scalar mu (const scalar p, const scalar T) const
scalar kappa (const scalar p, const scalar T) const
scalar alphah (const scalar p, const scalar T) const
void write (Ostream &os) const
Static Public Member Functions
static autoPtr< tabulatedTransport > New (const dictionary &dict)
static word typeName ()
Friends
Ostream & operator<< (Ostream &, const tabulatedTransport &)
Detailed Description
template<class Thermo>
class Foam::tabulatedTransport< Thermo >
Transport properties package using non-uniform tabulated data for viscosity and thermal conductivity vs temperature.
Usage
Property Description
mu Dynamic viscosity vs temperature table
kappa Thermal conductivity vs temperature table
Example of the specification of the transport properties:
    transport
    {
        mu
        (
            (200 1.82e-05)
            (350 2.61e-05)
            (400 3.93e-05)
        );
        kappa
        (
            (200 2.56e-5)
            (350 3.33e-5)
            (400 4.72e-5)
        );
    }
Source files
tabulatedTransport.H
tabulatedTransportI.H
tabulatedTransport.C
See also
Foam::thermophysicalFunctions::nonUniformTable
Definition at line 96 of file tabulatedTransport.H.
Constructor & Destructor Documentation
tabulatedTransport() [1/2]
template<class Thermo > tabulatedTransport (const word & name, const tabulatedTransport< Thermo > & pt) inline
Definition at line 41 of file tabulatedTransportI.H.
References Foam::name().
tabulatedTransport() [2/2]
template<class Thermo > tabulatedTransport (const dictionary & dict) explicit
Definition at line 28 of file tabulatedTransport.C.
Member Function Documentation
clone()
template<class Thermo > Foam::autoPtr< Foam::tabulatedTransport< Thermo > > clone () const inline
Definition at line 55 of file tabulatedTransportI.H.
References Foam::New().
New()
template<class Thermo > Foam::autoPtr< Foam::tabulatedTransport< Thermo > > New (const dictionary & dict) inline static
Definition at line 63 of file tabulatedTransportI.H.
References dict, and Foam::New().
typeName()
template<class Thermo > static word typeName () inline static
Definition at line 140 of file tabulatedTransport.H.
mu()
template<class Thermo > Foam::scalar mu (const scalar p, const scalar T) const inline
Definition at line 72 of file tabulatedTransportI.H.
References p, and T.
kappa()
template<class Thermo > Foam::scalar kappa (const scalar p, const scalar T) const inline
Definition at line 83 of file tabulatedTransportI.H.
References p, and T.
alphah()
template<class Thermo > Foam::scalar alphah (const scalar p, const scalar T) const inline
Definition at line 94 of file tabulatedTransportI.H.
References Cp, p, and T.
write()
template<class Thermo > void write (Ostream & os) const
Definition at line 42 of file tabulatedTransport.C.
References Ostream::beginBlock(), Ostream::endBlock(), Foam::name(), os(), and Ostream::writeEntry().
Friends And Related Symbol Documentation
operator<<
template<class Thermo > Ostream & operator<< (Ostream & , const tabulatedTransport< Thermo > &) friend
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/transport/tabulated/tabulatedTransport.H
src/thermophysicalModels/specie/transport/tabulated/tabulatedTransport.C
src/thermophysicalModels/specie/transport/tabulated/tabulatedTransportI.H