OpenFOAM: cutCell Class Reference
cutCell Class Reference
Service routines for cutting a cell, celli, of an fvMesh, mesh_, at its intersection with a surface.
#include <cutCell.H>
Public Member Functions
cutCell (const fvMesh &mesh)
Static Public Attributes
static int debug = 0
Static Protected Member Functions
static void calcCellData (const DynamicList< point > &cutFaceCentres, const DynamicList< vector > &cutFaceAreas, vector &subCellCentre, scalar &subCellVolume)
static void calcGeomDataCutFace (const DynamicList< DynamicList< point > > &faceEdges, const vector &subCellCentre, vector &faceArea, vector &faceCentre)
static void calcIsoFacePointsFromEdges (const vector &faceArea, const vector &faceCentre, const DynamicList< DynamicList< point > > &faceEdges, DynamicList< point > &facePoints)
Detailed Description
Service routines for cutting a cell, celli, of an fvMesh, mesh_, at its intersection with a surface.
Original code supplied by Johan Roenby, DHI (2016) Henning Scheufler, DLR (2019)
Source files
cutCell.H
cutCell.C
Definition at line 55 of file cutCell.H.
Constructor & Destructor Documentation
cutCell()
cutCell (const fvMesh & mesh) explicit
Definition at line 33 of file cutCell.C.
References mesh.
Member Function Documentation
calcCellData()
void calcCellData (const DynamicList< point > & cutFaceCentres, const DynamicList< vector > & cutFaceAreas, vector & subCellCentre, scalar & subCellVolume) static protected
Definition at line 48 of file cutCell.C.
References Foam::average(), forAll, Foam::mag(), Foam::max(), and Foam::Zero.
calcGeomDataCutFace()
void calcGeomDataCutFace (const DynamicList< DynamicList< point > > & faceEdges, const vector & subCellCentre, vector & faceArea, vector & faceCentre) static protected
Definition at line 87 of file cutCell.C.
References forAll, Foam::mag(), n, nPoints, p, Foam::sign(), UPtrList< T >::size(), and Foam::Zero.
calcIsoFacePointsFromEdges()
void calcIsoFacePointsFromEdges (const vector & faceArea, const vector & faceCentre, const DynamicList< DynamicList< point > > & faceEdges, DynamicList< point > & facePoints) static protected
Definition at line 157 of file cutCell.C.
References PtrList< T >::append(), Foam::atan2(), PtrList< T >::clear(), e, Foam::mag(), Foam::normalised(), p, UList< T >::size(), and Foam::sortedOrder().
Member Data Documentation
debug
int debug = 0 static
Definition at line 91 of file cutCell.H.
The documentation for this class was generated from the following files:
src/transportModels/geometricVoF/cellCuts/cutCell/cutCell.H
src/transportModels/geometricVoF/cellCuts/cutCell/cutCell.C