OpenFOAM: stateFunctionObject Class Reference
stateFunctionObject Class Reference
Base class for function objects, adding functionality to read/write state information (data required for smooth restart behaviour) and results to/from the state dictionary.
#include <stateFunctionObject.H>
Public Member Functions
stateFunctionObject (const word &name, const Time &runTime)
virtual ~stateFunctionObject ()=default
dictionary & propertyDict ()
bool foundProperty (const word &entryName) const
void clearTrigger ()
label getTrigger () const
bool setTrigger (const label triggeri)
bool getDict (const word &entryName, dictionary &dict) const
bool getObjectDict (const word &objectName, const word &entryName, dictionary &dict) const
template<class Type >
Type getProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getProperty (const word &entryName, Type &value) const
template<class Type >
void setProperty (const word &entryName, const Type &value)
template<class Type >
Type getObjectProperty (const word &objectName, const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getObjectProperty (const word &objectName, const word &entryName, Type &value) const
template<class Type >
void setObjectProperty (const word &objectName, const word &entryName, const Type &value)
template<class Type >
void setResult (const word &entryName, const Type &value)
template<class Type >
void setObjectResult (const word &objectName, const word &entryName, const Type &value)
template<class Type >
Type getResult (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
Type getObjectResult (const word &objectName, const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getObjectResult (const word &objectName, const word &entryName, Type &value) const
word resultType (const word &entryName) const
word objectResultType (const word &objectName, const word &entryName) const
wordList objectResultEntries () const
wordList objectResultEntries (const word &objectName) const
void writeResultEntries (Ostream &os) const
void writeResultEntries (const word &objectName, Ostream &os) const
void writeAllResultEntries (Ostream &os) const
Public Member Functions inherited from timeFunctionObject
timeFunctionObject (const word &name, const Time &runTime)
virtual ~timeFunctionObject ()=default
const Time & time () const
objectRegistry & storedObjects ()
const objectRegistry & storedObjects () const
Public Member Functions inherited from functionObject
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name, const bool withNamePrefix=defaultUseNamePrefix)
autoPtr< functionObject > clone () const
virtual ~functionObject ()=default
virtual const word & type () const =0
const word & name () const noexcept
bool useNamePrefix () const noexcept
bool useNamePrefix (bool on) noexcept
virtual bool read (const dictionary &dict)
virtual bool execute ()=0
virtual bool execute (const label subIndex)
virtual bool write ()=0
virtual bool end ()
virtual bool adjustTimeStep ()
virtual bool filesModified () const
virtual void updateMesh (const mapPolyMesh &mpm)
virtual void movePoints (const polyMesh &mesh)
Protected Member Functions
const functionObjects::properties & stateDict () const
functionObjects::properties & stateDict ()
stateFunctionObject (const stateFunctionObject &)=delete
void operator= (const stateFunctionObject &)=delete
Protected Member Functions inherited from timeFunctionObject
void clearOutputObjects (const wordList &objNames)
timeFunctionObject (const timeFunctionObject &)=delete
void operator= (const timeFunctionObject &)=delete
Protected Member Functions inherited from functionObject
word scopedName (const word &name) const
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &runTime, const dictionary &dict)
Public Attributes inherited from functionObject
bool log
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
static bool defaultUseNamePrefix
static word outputPrefix
Protected Attributes inherited from timeFunctionObject
const Time & time_
Detailed Description
Base class for function objects, adding functionality to read/write state information (data required for smooth restart behaviour) and results to/from the state dictionary.
Note: cannot access the state dictionary until after construction of the function objects, since the owner container functionObjectList is owned by time, and time owns the state dictionary i.e. need to wait for time to be fully constructed.
See also
Foam::functionObject
Source files
stateFunctionObject.H
stateFunctionObject.C
stateFunctionObjectTemplates.C
Definition at line 65 of file stateFunctionObject.H.
Constructor & Destructor Documentation
stateFunctionObject() [1/2]
stateFunctionObject (const stateFunctionObject &) protected delete
stateFunctionObject() [2/2]
stateFunctionObject (const word & name, const Time & runTime)
Definition at line 52 of file stateFunctionObject.C.
~stateFunctionObject()
virtual ~stateFunctionObject () virtual default
Member Function Documentation
stateDict() [1/2]
const Foam::functionObjects::properties & stateDict () const protected
Definition at line 34 of file stateFunctionObject.C.
References timeFunctionObject::time_.
stateDict() [2/2]
Foam::functionObjects::properties & stateDict () protected
Definition at line 41 of file stateFunctionObject.C.
operator=()
void operator= (const stateFunctionObject &) protected delete
propertyDict()
Foam::dictionary & propertyDict ()
Definition at line 64 of file stateFunctionObject.C.
References Foam::name().
Referenced by runTimeCondition::setConditionDict(), and valueAverage::valueAverage().
foundProperty()
bool foundProperty (const word & entryName) const
Definition at line 91 of file stateFunctionObject.C.
References Foam::name().
clearTrigger()
void clearTrigger ()
Definition at line 70 of file stateFunctionObject.C.
getTrigger()
Foam::label getTrigger () const
Definition at line 76 of file stateFunctionObject.C.
setTrigger()
bool setTrigger (const label triggeri)
Definition at line 82 of file stateFunctionObject.C.
getDict()
bool getDict (const word & entryName, dictionary & dict) const
Definition at line 100 of file stateFunctionObject.C.
References dict, and Foam::name().
Referenced by thermoCoupleProbes::thermoCoupleProbes().
getObjectDict()
bool getObjectDict (const word & objectName, const word & entryName, dictionary & dict) const
Definition at line 110 of file stateFunctionObject.C.
References dict.
getProperty() [1/2]
template<class Type > Type getProperty (const word & entryName, const Type & defaultValue = Type(Zero)) const
Definition at line 27 of file stateFunctionObjectTemplates.C.
References stateFunctionObject::getProperty().
Referenced by stateFunctionObject::getProperty().
getProperty() [2/2]
template<class Type > bool getProperty (const word & entryName, Type & value) const
Definition at line 40 of file stateFunctionObjectTemplates.C.
References Foam::name().
setProperty()
template<class Type > void setProperty (const word & entryName, const Type & value)
Definition at line 51 of file stateFunctionObjectTemplates.C.
References Foam::name().
getObjectProperty() [1/2]
template<class Type > Type getObjectProperty (const word & objectName, const word & entryName, const Type & defaultValue = Type(Zero)) const
Definition at line 62 of file stateFunctionObjectTemplates.C.
getObjectProperty() [2/2]
template<class Type > bool getObjectProperty (const word & objectName, const word & entryName, Type & value) const
Definition at line 76 of file stateFunctionObjectTemplates.C.
setObjectProperty()
template<class Type > void setObjectProperty (const word & objectName, const word & entryName, const Type & value)
Definition at line 88 of file stateFunctionObjectTemplates.C.
setResult()
template<class Type > void setResult (const word & entryName, const Type & value)
Definition at line 100 of file stateFunctionObjectTemplates.C.
References Foam::name().
Referenced by valueAverageBase::calc(), and fieldMinMax::output().
setObjectResult()
template<class Type > void setObjectResult (const word & objectName, const word & entryName, const Type & value)
Definition at line 111 of file stateFunctionObjectTemplates.C.
getResult()
template<class Type > Type getResult (const word & entryName, const Type & defaultValue = Type(Zero)) const
Definition at line 123 of file stateFunctionObjectTemplates.C.
References Foam::name().
Referenced by valueAverageBase::calc().
getObjectResult() [1/2]
template<class Type > Type getObjectResult (const word & objectName, const word & entryName, const Type & defaultValue = Type(Zero)) const
Definition at line 134 of file stateFunctionObjectTemplates.C.
Referenced by valueAverageBase::calc(), and minMaxCondition::setValue().
getObjectResult() [2/2]
template<class Type > bool getObjectResult (const word & objectName, const word & entryName, Type & value) const
Definition at line 148 of file stateFunctionObjectTemplates.C.
resultType()
Foam::word resultType (const word & entryName) const
Definition at line 121 of file stateFunctionObject.C.
References Foam::name().
objectResultType()
Foam::word objectResultType (const word & objectName, const word & entryName) const
Definition at line 130 of file stateFunctionObject.C.
Referenced by valueAverageBase::calc().
objectResultEntries() [1/2]
Foam::wordList objectResultEntries () const
Definition at line 141 of file stateFunctionObject.C.
References Foam::name().
objectResultEntries() [2/2]
Foam::wordList objectResultEntries (const word & objectName) const
Definition at line 148 of file stateFunctionObject.C.
writeResultEntries() [1/2]
void writeResultEntries (Ostream & os) const
Definition at line 157 of file stateFunctionObject.C.
References Foam::name(), and os().
writeResultEntries() [2/2]
void writeResultEntries (const word & objectName, Ostream & os) const
Definition at line 166 of file stateFunctionObject.C.
References os().
writeAllResultEntries()
void writeAllResultEntries (Ostream & os) const
Definition at line 176 of file stateFunctionObject.C.
References os().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/functionObjects/stateFunctionObject/stateFunctionObject.H
src/OpenFOAM/db/functionObjects/stateFunctionObject/stateFunctionObject.C
src/OpenFOAM/db/functionObjects/stateFunctionObject/stateFunctionObjectTemplates.C