OpenFOAM: processorLduInterfaceField Class Reference
processorLduInterfaceField Class Reference abstract
Abstract base class for processor coupled interfaces.
#include <processorLduInterfaceField.H>
Public Member Functions
TypeName ("processorLduInterfaceField")
processorLduInterfaceField ()=default
virtual ~processorLduInterfaceField ()=default
virtual label comm () const =0
virtual int myProcNo () const =0
virtual int neighbProcNo () const =0
virtual bool doTransform () const =0
virtual const tensorField & forwardT () const =0
virtual int rank () const =0
template<class Type >
void transformCoupleField (Field< Type > &f) const
void transformCoupleField (solveScalarField &f, const direction cmpt) const
Detailed Description
Abstract base class for processor coupled interfaces.
Source files
processorLduInterfaceField.H
processorLduInterfaceField.C
Definition at line 48 of file processorLduInterfaceField.H.
Constructor & Destructor Documentation
processorLduInterfaceField()
processorLduInterfaceField () default
~processorLduInterfaceField()
virtual ~processorLduInterfaceField () virtual default
Member Function Documentation
TypeName()
TypeName ("processorLduInterfaceField")
comm()
virtual label comm () const pure virtual
Implemented in processorFaPatchField< Type >, calculatedProcessorFvPatchField< Type >, processorFvPatchField< Type >, lduCalculatedProcessorField< Type >, processorGAMGInterfaceField, and calculatedProcessorGAMGInterfaceField.
myProcNo()
virtual int myProcNo () const pure virtual
Implemented in processorFaPatchField< Type >, calculatedProcessorFvPatchField< Type >, processorFvPatchField< Type >, lduCalculatedProcessorField< Type >, processorGAMGInterfaceField, and calculatedProcessorGAMGInterfaceField.
neighbProcNo()
virtual int neighbProcNo () const pure virtual
Implemented in processorFaPatchField< Type >, calculatedProcessorFvPatchField< Type >, processorFvPatchField< Type >, lduCalculatedProcessorField< Type >, processorGAMGInterfaceField, and calculatedProcessorGAMGInterfaceField.
doTransform()
virtual bool doTransform () const pure virtual
Implemented in processorFaPatchField< Type >, calculatedProcessorFvPatchField< Type >, processorFvPatchField< Type >, processorCyclicFvPatchField< Type >, lduCalculatedProcessorField< Type >, processorGAMGInterfaceField, and calculatedProcessorGAMGInterfaceField.
Referenced by processorLduInterfaceField::transformCoupleField(), and processorLduInterfaceField::transformCoupleField().
forwardT()
virtual const tensorField & forwardT () const pure virtual
Implemented in processorFaPatchField< Type >, calculatedProcessorFvPatchField< Type >, processorFvPatchField< Type >, processorCyclicFvPatchField< Type >, lduCalculatedProcessorField< Type >, processorGAMGInterfaceField, and calculatedProcessorGAMGInterfaceField.
Referenced by processorLduInterfaceField::transformCoupleField(), and processorLduInterfaceField::transformCoupleField().
rank()
virtual int rank () const pure virtual
Implemented in processorFaPatchField< Type >, calculatedProcessorFvPatchField< Type >, processorFvPatchField< Type >, lduCalculatedProcessorField< Type >, processorGAMGInterfaceField, and calculatedProcessorGAMGInterfaceField.
Referenced by processorLduInterfaceField::transformCoupleField().
transformCoupleField() [1/2]
template<class Type > void transformCoupleField (Field< Type > & f) const
Definition at line 111 of file processorLduInterfaceField.H.
References processorLduInterfaceField::doTransform(), f(), processorLduInterfaceField::forwardT(), and Foam::transform().
transformCoupleField() [2/2]
void transformCoupleField (solveScalarField & f, const direction cmpt) const
Definition at line 35 of file processorLduInterfaceField.C.
References Foam::component(), Foam::diag(), processorLduInterfaceField::doTransform(), f(), processorLduInterfaceField::forwardT(), Foam::pow(), and processorLduInterfaceField::rank().
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/lduMatrix/lduAddressing/lduInterfaceFields/processorLduInterfaceField/processorLduInterfaceField.H
src/OpenFOAM/matrices/lduMatrix/lduAddressing/lduInterfaceFields/processorLduInterfaceField/processorLduInterfaceField.C