OpenFOAM: freeSurfaceVelocityFvPatchVectorField Class Reference
freeSurfaceVelocityFvPatchVectorField Class Reference
Boundary conditions » Outlet
This boundary condition provides a velocity outlet boundary condition for free surface patches.
#include <freeSurfaceVelocityFvPatchVectorField.H>
Public Member Functions
TypeName ("freeSurfaceVelocity")
freeSurfaceVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
freeSurfaceVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
freeSurfaceVelocityFvPatchVectorField (const freeSurfaceVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
virtual tmp< fvPatchVectorField > clone () const
freeSurfaceVelocityFvPatchVectorField (const freeSurfaceVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
This boundary condition provides a velocity outlet boundary condition for free surface patches.
Source files
freeSurfaceVelocityFvPatchVectorField.H
freeSurfaceVelocityFvPatchVectorField.C
Definition at line 51 of file freeSurfaceVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
freeSurfaceVelocityFvPatchVectorField() [1/4]
freeSurfaceVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Definition at line 31 of file freeSurfaceVelocityFvPatchVectorField.C.
freeSurfaceVelocityFvPatchVectorField() [2/4]
freeSurfaceVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Definition at line 55 of file freeSurfaceVelocityFvPatchVectorField.C.
References dict, and fvPatchFieldBase::readDict().
freeSurfaceVelocityFvPatchVectorField() [3/4]
freeSurfaceVelocityFvPatchVectorField (const freeSurfaceVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 42 of file freeSurfaceVelocityFvPatchVectorField.C.
freeSurfaceVelocityFvPatchVectorField() [4/4]
freeSurfaceVelocityFvPatchVectorField (const freeSurfaceVelocityFvPatchVectorField & fcvpvf, const DimensionedField< vector, volMesh > & iF)
Definition at line 71 of file freeSurfaceVelocityFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("freeSurfaceVelocity")
clone() [1/2]
virtual tmp< fvPatchVectorField > clone () const inline virtual
Definition at line 89 of file freeSurfaceVelocityFvPatchVectorField.H.
clone() [2/2]
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Definition at line 105 of file freeSurfaceVelocityFvPatchVectorField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 84 of file freeSurfaceVelocityFvPatchVectorField.C.
References objectRegistry::lookupObject(), and mesh.
write()
void write (Ostream & os) const virtual
Definition at line 108 of file freeSurfaceVelocityFvPatchVectorField.C.
References os(), fixedGradientFvPatchField< Type >::write(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/dynamicFaMesh/interfaceTrackingFvMesh/fvPatchFields/freeSurfaceVelocity/freeSurfaceVelocityFvPatchVectorField.H
src/dynamicFaMesh/interfaceTrackingFvMesh/fvPatchFields/freeSurfaceVelocity/freeSurfaceVelocityFvPatchVectorField.C