OpenFOAM: multiComponentMixture< ThermoType > Class Template Reference
multiComponentMixture< ThermoType > Class Template Reference
Thermophysical models » Reaction thermophysical models » Mixtures
Foam::multiComponentMixture.
#include <multiComponentMixture.H>
Public Types
typedef ThermoType thermoType
Public Types inherited from basicSpecieMixture
typedef basicSpecieMixture basicMixtureType
Public Types inherited from basicMultiComponentMixture
typedef basicMultiComponentMixture basicMixtureType
Public Types inherited from basicMixture
typedef basicMixture basicMixtureType
Public Member Functions
multiComponentMixture (const dictionary &, const wordList &specieNames, const ReactionTable< ThermoType > &thermoData, const fvMesh &mesh, const word &phaseName)
multiComponentMixture (const dictionary &thermoDict, const fvMesh &mesh, const word &phaseName)
virtual ~multiComponentMixture ()=default
const ThermoType & cellMixture (const label celli) const
const ThermoType & patchFaceMixture (const label patchi, const label facei) const
const ThermoType & cellVolMixture (const scalar p, const scalar T, const label celli) const
const ThermoType & patchFaceVolMixture (const scalar p, const scalar T, const label patchi, const label facei) const
const PtrList< ThermoType > & speciesData () const
void read (const dictionary &)
const ThermoType & getLocalThermo (const label speciei) const
Public Member Functions inherited from basicSpecieMixture
TypeName ("basicSpecieMixture")
basicSpecieMixture (const dictionary &thermoDict, const wordList &specieNames, const fvMesh &mesh, const word &phaseName)
virtual ~basicSpecieMixture ()=default
virtual scalar W (const label speciei) const =0
virtual scalar Hc (const label speciei) const =0
virtual scalar Cp (const label speciei, const scalar p, const scalar T) const =0
virtual scalar Cv (const label speciei, const scalar p, const scalar T) const =0
virtual scalar HE (const label speciei, const scalar p, const scalar T) const =0
virtual scalar Ha (const label speciei, const scalar p, const scalar T) const =0
virtual scalar Hs (const label speciei, const scalar p, const scalar T) const =0
virtual scalar S (const label speciei, const scalar p, const scalar T) const =0
virtual scalar Es (const label speciei, const scalar p, const scalar T) const =0
virtual scalar G (const label speciei, const scalar p, const scalar T) const =0
virtual scalar A (const label speciei, const scalar p, const scalar T) const =0
virtual scalar mu (const label speciei, const scalar p, const scalar T) const =0
virtual scalar kappa (const label speciei, const scalar p, const scalar T) const =0
virtual scalar alphah (const label speciei, const scalar p, const scalar T) const =0
virtual scalar rho (const label speciei, const scalar p, const scalar T) const =0
virtual autoPtr< speciesCompositionTable > specieComposition () const
Public Member Functions inherited from basicMultiComponentMixture
TypeName ("basicMultiComponentMixture")
basicMultiComponentMixture (const dictionary &thermoDict, const wordList &specieNames, const fvMesh &mesh, const word &phaseName)
virtual ~basicMultiComponentMixture ()=default
const speciesTable & species () const
bool contains (const word &specieName) const
bool active (label speciei) const
const List< bool > & active () const
void setActive (label speciei)
void setInactive (label speciei)
PtrList< volScalarField > & Y ()
const PtrList< volScalarField > & Y () const
volScalarField & Y (const label i)
const volScalarField & Y (const label i) const
volScalarField & Y (const word &specieName)
const volScalarField & Y (const word &specieName) const
Public Member Functions inherited from basicMixture
basicMixture (const dictionary &, const fvMesh &, const word &)
Static Public Member Functions
static word typeName ()
Additional Inherited Members
Protected Attributes inherited from basicMultiComponentMixture
speciesTable species_
List< bool > active_
PtrList< volScalarField > Y_
Detailed Description
template<class ThermoType>
class Foam::multiComponentMixture< ThermoType >
Foam::multiComponentMixture.
Source files
multiComponentMixture.H
multiComponentMixture.C
Definition at line 52 of file multiComponentMixture.H.
Member Typedef Documentation
thermoType
template<class ThermoType > typedef ThermoType thermoType
Definition at line 85 of file multiComponentMixture.H.
Constructor & Destructor Documentation
multiComponentMixture() [1/2]
template<class ThermoType > multiComponentMixture (const dictionary & thermoDict, const wordList & specieNames, const ReactionTable< ThermoType > & thermoData, const fvMesh & mesh, const word & phaseName)
Definition at line 89 of file multiComponentMixture.C.
References forAll, PtrList< T >::set(), and basicMultiComponentMixture::species_.
multiComponentMixture() [2/2]
template<class ThermoType > multiComponentMixture (const dictionary & thermoDict, const fvMesh & mesh, const word & phaseName)
Definition at line 117 of file multiComponentMixture.C.
~multiComponentMixture()
template<class ThermoType > virtual ~multiComponentMixture () virtual default
Member Function Documentation
typeName()
template<class ThermoType > static word typeName () inline static
Definition at line 117 of file multiComponentMixture.H.
cellMixture()
template<class ThermoType > const ThermoType & cellMixture (const label celli) const
Definition at line 142 of file multiComponentMixture.C.
References n, and UPtrList< T >::size().
patchFaceMixture()
template<class ThermoType > const ThermoType & patchFaceMixture (const label patchi, const label facei) const
Definition at line 159 of file multiComponentMixture.C.
References n, and UPtrList< T >::size().
cellVolMixture()
template<class ThermoType > const ThermoType & cellVolMixture (const scalar p, const scalar T, const label celli) const
Definition at line 177 of file multiComponentMixture.C.
References forAll, n, p, UPtrList< T >::size(), and T.
patchFaceVolMixture()
template<class ThermoType > const ThermoType & patchFaceVolMixture (const scalar p, const scalar T, const label patchi, const label facei) const
Definition at line 204 of file multiComponentMixture.C.
References forAll, n, p, UPtrList< T >::size(), and T.
speciesData()
template<class ThermoType > const PtrList< ThermoType > & speciesData () const inline
Definition at line 146 of file multiComponentMixture.H.
read()
template<class ThermoType > void read (const dictionary & thermoDict)
Definition at line 236 of file multiComponentMixture.C.
References forAll, and thermoDict.
getLocalThermo()
template<class ThermoType > const ThermoType & getLocalThermo (const label speciei) const inline
Definition at line 155 of file multiComponentMixture.H.
The documentation for this class was generated from the following files:
src/phaseSystemModels/multiphaseInter/phasesSystem/InterfaceCompositionModel/InterfaceCompositionModel.H
src/thermophysicalModels/reactionThermo/mixtures/multiComponentMixture/multiComponentMixture.H
src/thermophysicalModels/reactionThermo/mixtures/multiComponentMixture/multiComponentMixture.C