OpenFOAM: IOobjectList Class Reference
IOobjectList Class Reference
List of IOobjects with searching and retrieving facilities. Implemented as a HashTable, so the various sorted methods should be used if traversing in parallel.
#include <IOobjectList.H>
Public Member Functions
IOobjectList ()
IOobjectList (const label nObjects)
IOobjectList (const IOobjectList &list)
IOobjectList (IOobjectList &&list)
IOobjectList (const objectRegistry &db, const fileName &instance, IOobjectOption ioOpt)
IOobjectList (const objectRegistry &db, const fileName &instance, const fileName &local, IOobjectOption ioOpt)
IOobjectList (const objectRegistry &db, const fileName &instance, IOobjectOption::registerOption=IOobjectOption::REGISTER)
IOobjectList (const objectRegistry &db, const fileName &instance, const fileName &local, IOobjectOption::registerOption=IOobjectOption::REGISTER)
~IOobjectList ()=default
bool add (autoPtr< IOobject > &objectPtr)
bool add (autoPtr< IOobject > &&objectPtr)
autoPtr< IOobject > remove (const IOobject &io)
const IOobject * cfindObject (const word &objName) const
template<class Type >
const IOobject * cfindObject (const word &objName) const
const IOobject * findObject (const word &objName) const
template<class Type >
const IOobject * findObject (const word &objName) const
IOobject * findObject (const word &objName)
template<class Type >
IOobject * findObject (const word &objName)
IOobject * getObject (const word &objName) const
template<class Type >
IOobject * getObject (const word &objName) const
template<class MatchPredicate >
IOobjectList lookup (const MatchPredicate &matchName) const
IOobjectList lookupClass (const char *clsName) const
template<class MatchPredicate >
IOobjectList lookupClass (const MatchPredicate &matchClass) const
template<class MatchPredicate1 , class MatchPredicate2 >
IOobjectList lookupClass (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName) const
template<class Type >
IOobjectList lookupClass () const
template<class Type , class MatchPredicate >
IOobjectList lookupClass (const MatchPredicate &matchName) const
HashTable< wordHashSet > classes () const
template<class MatchPredicate >
HashTable< wordHashSet > classes (const MatchPredicate &matchName) const
UPtrList< const IOobject > sorted () const
UPtrList< const IOobject > sorted (const bool syncPar) const
template<class Type >
UPtrList< const IOobject > sorted () const
template<class Type >
UPtrList< const IOobject > sorted (const bool syncPar) const
template<class Type , class MatchPredicate >
UPtrList< const IOobject > sorted (const MatchPredicate &matchName) const
template<class Type , class MatchPredicate >
UPtrList< const IOobject > sorted (const MatchPredicate &matchName, const bool syncPar) const
label count (const char *clsName) const
template<class MatchPredicate >
label count (const MatchPredicate &matchClass) const
template<class MatchPredicate1 , class MatchPredicate2 >
label count (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName) const
template<class Type >
label count () const
template<class Type , class MatchPredicate >
label count (const MatchPredicate &matchName) const
wordList names () const
wordList names (const bool syncPar) const
wordList names (const char *clsName) const
wordList names (const char *clsName, const bool syncPar) const
template<class MatchPredicate >
wordList names (const MatchPredicate &matchClass) const
template<class MatchPredicate >
wordList names (const MatchPredicate &matchClass, const bool syncPar) const
template<class MatchPredicate1 , class MatchPredicate2 >
wordList names (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName) const
template<class MatchPredicate1 , class MatchPredicate2 >
wordList names (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName, const bool syncPar) const
template<class Type >
wordList names () const
template<class Type >
wordList names (bool syncPar) const
template<class Type , class MatchPredicate >
wordList names (const MatchPredicate &matchName) const
template<class Type , class MatchPredicate >
wordList names (const MatchPredicate &matchName, const bool syncPar) const
wordList sortedNames () const
wordList sortedNames (const bool syncPar) const
wordList sortedNames (const char *clsName) const
wordList sortedNames (const char *clsName, const bool syncPar) const
template<class MatchPredicate >
wordList sortedNames (const MatchPredicate &matchClass) const
template<class MatchPredicate >
wordList sortedNames (const MatchPredicate &matchClass, const bool syncPar) const
template<class MatchPredicate1 , class MatchPredicate2 >
wordList sortedNames (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName) const
template<class MatchPredicate1 , class MatchPredicate2 >
wordList sortedNames (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName, const bool syncPar) const
template<class Type >
wordList sortedNames () const
template<class Type >
wordList sortedNames (bool syncPar) const
template<class Type , class MatchPredicate >
wordList sortedNames (const MatchPredicate &matchName) const
template<class Type , class MatchPredicate >
wordList sortedNames (const MatchPredicate &matchName, const bool syncPar) const
template<class UnaryPredicate >
label filterClasses (const UnaryPredicate &pred, const bool pruning=false)
template<class UnaryPredicate >
label filterObjects (const UnaryPredicate &pred, const bool pruning=false)
label prune_0 ()
wordList allNames () const
template<class Type >
wordList allNames () const
void checkNames (const bool syncPar=true) const
void operator= (const IOobjectList &)=delete
void operator= (IOobjectList &&list)
IOobjectList (const objectRegistry &db, const fileName &instance, const fileName &local, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true)
IOobject * lookup (const char *objName) const
IOobject * lookup (const word &objName) const
template<class MatchPredicate >
Foam::HashTable< Foam::wordHashSet > classesImpl (const IOobjectList &list, const MatchPredicate &matchName)
template<class MatchPredicate1 , class MatchPredicate2 >
Foam::label countImpl (const IOobjectList &list, const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName)
template<class Type , class MatchPredicate >
Foam::label countTypeImpl (const IOobjectList &list, const MatchPredicate &matchName)
template<class MatchPredicate1 , class MatchPredicate2 >
Foam::wordList namesImpl (const IOobjectList &list, const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName, const bool doSort)
template<class Type , class MatchPredicate >
Foam::wordList namesTypeImpl (const IOobjectList &list, const MatchPredicate &matchName, const bool doSort)
template<class Type , class MatchPredicate >
Foam::UPtrList< const Foam::IOobject > objectsTypeImpl (const IOobjectList &list, const MatchPredicate &matchName)
template<class MatchPredicate >
Foam::IOobjectList lookupImpl (const IOobjectList &list, const MatchPredicate &matchName)
template<class MatchPredicate1 , class MatchPredicate2 >
Foam::IOobjectList lookupClassImpl (const IOobjectList &list, const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName)
template<class Type , class MatchPredicate >
Foam::IOobjectList lookupClassTypeImpl (const IOobjectList &list, const MatchPredicate &matchName)
template<class Type >
const Foam::IOobject * cfindObject (const word &objName) const
template<class Type >
const Foam::IOobject * findObject (const word &objName) const
template<class Type >
Foam::IOobject * findObject (const word &objName)
template<class Type >
Foam::IOobject * getObject (const word &objName) const
template<class MatchPredicate >
Foam::IOobjectList lookup (const MatchPredicate &matchName) const
template<class MatchPredicate >
Foam::IOobjectList lookupClass (const MatchPredicate &matchClass) const
template<class MatchPredicate1 , class MatchPredicate2 >
Foam::IOobjectList lookupClass (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName) const
template<class Type >
Foam::IOobjectList lookupClass () const
template<class Type , class MatchPredicate >
Foam::IOobjectList lookupClass (const MatchPredicate &matchName) const
template<class MatchPredicate >
Foam::HashTable< Foam::wordHashSet > classes (const MatchPredicate &matchName) const
template<class MatchPredicate >
Foam::label count (const MatchPredicate &matchClass) const
template<class MatchPredicate1 , class MatchPredicate2 >
Foam::label count (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName) const
template<class Type >
Foam::label count () const
template<class Type , class MatchPredicate >
Foam::label count (const MatchPredicate &matchName) const
template<class Type >
Foam::UPtrList< const Foam::IOobject > sorted () const
template<class Type >
Foam::UPtrList< const Foam::IOobject > sorted (const bool syncPar) const
template<class Type , class MatchPredicate >
Foam::UPtrList< const Foam::IOobject > sorted (const MatchPredicate &matchName) const
template<class Type , class MatchPredicate >
Foam::UPtrList< const Foam::IOobject > sorted (const MatchPredicate &matchName, const bool syncPar) const
template<class MatchPredicate >
Foam::wordList names (const MatchPredicate &matchClass) const
template<class MatchPredicate >
Foam::wordList names (const MatchPredicate &matchClass, const bool syncPar) const
template<class MatchPredicate1 , class MatchPredicate2 >
Foam::wordList names (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName) const
template<class MatchPredicate1 , class MatchPredicate2 >
Foam::wordList names (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName, const bool syncPar) const
template<class Type >
Foam::wordList names () const
template<class Type >
Foam::wordList names (const bool syncPar) const
template<class Type , class MatchPredicate >
Foam::wordList names (const MatchPredicate &matchName) const
template<class Type , class MatchPredicate >
Foam::wordList names (const MatchPredicate &matchName, const bool syncPar) const
template<class MatchPredicate >
Foam::wordList sortedNames (const MatchPredicate &matchClass) const
template<class MatchPredicate >
Foam::wordList sortedNames (const MatchPredicate &matchClass, const bool syncPar) const
template<class MatchPredicate1 , class MatchPredicate2 >
Foam::wordList sortedNames (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName) const
template<class MatchPredicate1 , class MatchPredicate2 >
Foam::wordList sortedNames (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName, const bool syncPar) const
template<class Type >
Foam::wordList sortedNames () const
template<class Type >
Foam::wordList sortedNames (const bool syncPar) const
template<class Type , class MatchPredicate >
Foam::wordList sortedNames (const MatchPredicate &matchName) const
template<class Type , class MatchPredicate >
Foam::wordList sortedNames (const MatchPredicate &matchName, const bool syncPar) const
template<class UnaryPredicate >
Foam::label filterClasses (const UnaryPredicate &pred, const bool pruning)
template<class UnaryPredicate >
Foam::label filterObjects (const UnaryPredicate &pred, const bool pruning)
template<class Type >
Foam::wordList allNames () const
Public Member Functions inherited from HashPtrTable< IOobject >
HashPtrTable ()=default
HashPtrTable (const label size)
HashPtrTable (const this_type &rhs)
HashPtrTable (this_type &&rhs)
HashPtrTable (Istream &is, const INew &inew)
HashPtrTable (Istream &is)
HashPtrTable (const dictionary &dict)
~HashPtrTable ()
const IOobject * test (const word &key) const
const IOobject * get (const word &key) const
autoPtr< IOobject > release (iterator &iter)
autoPtr< IOobject > release (const word &key)
autoPtr< IOobject > remove (iterator &iter)
autoPtr< IOobject > remove (const word &key)
bool erase (iterator &iter)
bool erase (const word &key)
void clear ()
void merge (HashPtrTable< IOobject, word, Foam::Hash< word > > &source)
void merge (HashPtrTable< IOobject, word, Foam::Hash< word > > &&source)
void write (Ostream &os) const
void operator= (const this_type &rhs)
void operator= (this_type &&rhs)
bool emplace (const word &key, Args &&... args)
IOobject & emplace_set (const word &key, Args &&... args)
bool insert (const word &, IOobject *)=delete
bool insert (const word &key, std::unique_ptr< IOobject > &&ptr)
bool insert (const word &key, autoPtr< IOobject > &&ptr)
bool insert (const word &key, autoPtr< IOobject > &ptr)
bool set (const word &key, IOobject *ptr)
bool set (const word &key, std::unique_ptr< IOobject > &&ptr)
bool set (const word &key, autoPtr< IOobject > &&ptr)
bool set (const word &key, const refPtr< IOobject > &ptr)
bool set (const word &key, const tmp< IOobject > &ptr)
bool set (const word &key, autoPtr< IOobject > &ptr)
Public Member Functions inherited from HashTable< T, Key, Hash >
HashTable ()
HashTable (const label size)
HashTable (Istream &is, const label size=128)
HashTable (const this_type &ht)
HashTable (this_type &&rhs)
HashTable (std::initializer_list< std::pair< Key, T > > list)
~HashTable ()
bool empty () const noexcept
label size () const noexcept
label capacity () const noexcept
T & at (const Key &key)
const T & at (const Key &key) const
bool contains (const Key &key) const
iterator find (const Key &key)
const_iterator find (const Key &key) const
const_iterator cfind (const Key &key) const
const T & lookup (const Key &key, const T &deflt) const
List< Key > toc () const
List< Key > sortedToc () const
template<class Compare >
List< Key > sortedToc (const Compare &comp) const
template<class UnaryPredicate >
List< Key > tocKeys (const UnaryPredicate &pred, const bool invert=false) const
template<class UnaryPredicate >
List< Key > tocValues (const UnaryPredicate &pred, const bool invert=false) const
template<class BinaryPredicate >
List< Key > tocEntries (const BinaryPredicate &pred, const bool invert=false) const
UPtrList< const node_type > csorted () const
UPtrList< const node_type > sorted () const
UPtrList< node_type > sorted ()
template<class UnaryPredicate >
label countKeys (const UnaryPredicate &pred, const bool invert=false) const
template<class UnaryPredicate >
label countValues (const UnaryPredicate &pred, const bool invert=false) const
template<class BinaryPredicate >
label countEntries (const BinaryPredicate &pred, const bool invert=false) const
template<class... Args>
bool emplace (const Key &key, Args &&... args)
template<class... Args>
bool emplace_set (const Key &key, Args &&... args)
bool insert (const Key &key, const T &obj)
bool insert (const Key &key, T &&obj)
bool set (const Key &key, const T &obj)
bool set (const Key &key, T &&obj)
bool erase (const iterator &iter)
bool erase (const Key &key)
template<class AnyType , class AnyHash >
label erase (const HashTable< AnyType, Key, AnyHash > &other)
label erase (std::initializer_list< Key > keys)
template<class InputIter >
label erase (InputIter first, InputIter last)
template<unsigned N>
label erase (const FixedList< Key, N > &keys)
label erase (const UList< Key > &keys)
template<class AnyType , class AnyHash >
label retain (const HashTable< AnyType, Key, AnyHash > &other)
template<class UnaryPredicate >
label filterKeys (const UnaryPredicate &pred, const bool pruning=false)
template<class UnaryPredicate >
label filterValues (const UnaryPredicate &pred, const bool pruning=false)
template<class BinaryPredicate >
label filterEntries (const BinaryPredicate &pred, const bool pruning=false)
void resize (const label sz)
void clear ()
void clearStorage ()
void swap (HashTable< T, Key, Hash > &rhs)
void transfer (HashTable< T, Key, Hash > &rhs)
void merge (HashTable< T, Key, Hash > &source)
void merge (HashTable< T, Key, Hash > &&source)
T & operator[] (const Key &key)
const T & operator[] (const Key &key) const
T & operator() (const Key &key)
T & operator() (const Key &key, const T &deflt)
void operator= (const this_type &rhs)
void operator= (std::initializer_list< std::pair< Key, T > > rhs)
void operator= (this_type &&rhs)
bool operator== (const this_type &rhs) const
bool operator!= (const this_type &rhs) const
this_type & operator+= (const this_type &rhs)
const_iterator_pair< const_key_iterator, this_type > keys () const
iterator begin ()
const_iterator begin () const
const_iterator cbegin () const
iterator end () noexcept
const_iterator end () const noexcept
constexpr const_iterator cend () const noexcept
Ostream & printInfo (Ostream &os) const
Ostream & writeKeys (Ostream &os, const label shortLen=0) const
bool found (const Key &key) const
template<class Compare >
Foam::List< Key > sortedToc (const Compare &comp) const
template<class UnaryPredicate >
Foam::List< Key > tocKeys (const UnaryPredicate &pred, const bool invert) const
template<class UnaryPredicate >
Foam::List< Key > tocValues (const UnaryPredicate &pred, const bool invert) const
template<class BinaryPredicate >
Foam::List< Key > tocEntries (const BinaryPredicate &pred, const bool invert) const
template<class UnaryPredicate >
Foam::label countKeys (const UnaryPredicate &pred, const bool invert) const
template<class UnaryPredicate >
Foam::label countValues (const UnaryPredicate &pred, const bool invert) const
template<class BinaryPredicate >
Foam::label countEntries (const BinaryPredicate &pred, const bool invert) const
template<class InputIter >
Foam::label erase (InputIter first, InputIter last)
template<unsigned N>
Foam::label erase (const FixedList< Key, N > &keys)
template<class AnyType , class AnyHash >
Foam::label erase (const HashTable< AnyType, Key, AnyHash > &other)
template<class AnyType , class AnyHash >
Foam::label retain (const HashTable< AnyType, Key, AnyHash > &other)
template<class UnaryPredicate >
Foam::label filterKeys (const UnaryPredicate &pred, const bool pruning)
template<class UnaryPredicate >
Foam::label filterValues (const UnaryPredicate &pred, const bool pruning)
template<class BinaryPredicate >
Foam::label filterEntries (const BinaryPredicate &pred, const bool pruning)
Public Member Functions inherited from HashTableCore
ClassName ("HashTable")
HashTableCore () noexcept=default
Additional Inherited Members
Public Types inherited from HashPtrTable< IOobject >
typedef HashPtrTable< IOobject, word, Foam::Hash< word > > this_type
typedef HashTable< IOobject *, word, Foam::Hash< word > > parent_type
using iterator = typename parent_type::iterator
using const_iterator = typename parent_type::const_iterator
Public Types inherited from HashTable< T, Key, Hash >
typedef HashTable< T, Key, Hash > this_type
typedef std::conditional< std::is_same< Foam::zero, typenamestd::remove_cv< T >::type >::value, Detail::HashTableSingle< Key >, Detail::HashTablePair< Key, T > >::type node_type
typedef Key key_type
typedef T mapped_type
typedef T value_type
typedef Hash hasher
typedef T * pointer
typedef T & reference
typedef const T * const_pointer
typedef const T & const_reference
typedef label difference_type
typedef label size_type
using key_iterator = key_iterator_base< iterator >
using const_key_iterator = key_iterator_base< const_iterator >
Static Public Member Functions inherited from HashTableCore
static label canonicalSize (const label requested_size)
Static Public Attributes inherited from HashTableCore
static const label maxTableSize
Detailed Description
List of IOobjects with searching and retrieving facilities. Implemented as a HashTable, so the various sorted methods should be used if traversing in parallel.
Source files
IOobjectList.H
IOobjectList.C
IOobjectListI.H
IOobjectListTemplates.C
Definition at line 55 of file IOobjectList.H.
Constructor & Destructor Documentation
IOobjectList() [1/9]
IOobjectList () inline
Definition at line 23 of file IOobjectListI.H.
IOobjectList() [2/9]
IOobjectList (const label nObjects) inline explicit
Definition at line 29 of file IOobjectListI.H.
IOobjectList() [3/9]
IOobjectList (const IOobjectList & list) inline
Definition at line 35 of file IOobjectListI.H.
IOobjectList() [4/9]
IOobjectList (IOobjectList && list) inline
Definition at line 41 of file IOobjectListI.H.
IOobjectList() [5/9]
IOobjectList (const objectRegistry & db, const fileName & instance, IOobjectOption ioOpt) inline
Definition at line 47 of file IOobjectListI.H.
IOobjectList() [6/9]
IOobjectList (const objectRegistry & db, const fileName & instance, const fileName & local, IOobjectOption ioOpt)
Definition at line 94 of file IOobjectList.C.
References Foam::endl(), Foam::FatalIOError, Foam::fileHandler, insert(), local, autoPtr< T >::New(), Foam::nl, error::throwing(), and Foam::Warning.
IOobjectList() [7/9]
IOobjectList (const objectRegistry & db, const fileName & instance, IOobjectOption::registerOption registerObject = IOobjectOption::REGISTER) inline
Definition at line 58 of file IOobjectListI.H.
IOobjectList() [8/9]
IOobjectList (const objectRegistry & db, const fileName & instance, const fileName & local, IOobjectOption::registerOption registerObject = IOobjectOption::REGISTER) inline
Definition at line 80 of file IOobjectListI.H.
~IOobjectList()
~IOobjectList () default
IOobjectList() [9/9]
IOobjectList (const objectRegistry & db, const fileName & instance, const fileName & local, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt = IOobjectOption::NO_WRITE, bool registerObject = true) inline
Definition at line 730 of file IOobjectList.H.
Member Function Documentation
add() [1/2]
bool add (autoPtr< IOobject > & objectPtr) inline
Definition at line 105 of file IOobjectListI.H.
References insert().
add() [2/2]
bool add (autoPtr< IOobject > && objectPtr) inline
Definition at line 116 of file IOobjectListI.H.
References insert().
remove()
autoPtr< IOobject > remove (const IOobject & io) inline
Definition at line 236 of file IOobjectList.H.
References io(), and IOobjectList::remove().
Referenced by IOobjectList::remove().
cfindObject() [1/3]
const Foam::IOobject * cfindObject (const word & objName) const
Definition at line 149 of file IOobjectList.C.
References Foam::endl(), HashTable< T, Key, Hash >::Iterator< Const >::good(), InfoInFunction, io(), and HashTable< T, Key, Hash >::const_iterator::val().
cfindObject() [2/3]
template<class Type > const IOobject * cfindObject (const word & objName) const
findObject() [1/6]
const Foam::IOobject * findObject (const word & objName) const
Definition at line 179 of file IOobjectList.C.
findObject() [2/6]
template<class Type > const IOobject * findObject (const word & objName) const
findObject() [3/6]
Foam::IOobject * findObject (const word & objName)
Definition at line 188 of file IOobjectList.C.
findObject() [4/6]
template<class Type > IOobject * findObject (const word & objName)
getObject() [1/3]
Foam::IOobject * getObject (const word & objName) const
Definition at line 194 of file IOobjectList.C.
Referenced by IOobjectList::lookup(), and IOobjectList::lookup().
getObject() [2/3]
template<class Type > IOobject * getObject (const word & objName) const
lookup() [1/4]
template<class MatchPredicate > IOobjectList lookup (const MatchPredicate & matchName) const
lookupClass() [1/9]
Foam::IOobjectList lookupClass (const char * clsName) const
Definition at line 200 of file IOobjectList.C.
lookupClass() [2/9]
template<class MatchPredicate > IOobjectList lookupClass (const MatchPredicate & matchClass) const
lookupClass() [3/9]
template<class MatchPredicate1 , class MatchPredicate2 > IOobjectList lookupClass (const MatchPredicate1 & matchClass, const MatchPredicate2 & matchName) const
lookupClass() [4/9]
template<class Type > IOobjectList lookupClass () const
lookupClass() [5/9]
template<class Type , class MatchPredicate > IOobjectList lookupClass (const MatchPredicate & matchName) const
classes() [1/3]
Foam::HashTable< Foam::wordHashSet > classes () const
Definition at line 207 of file IOobjectList.C.
Referenced by probes::prepare().
classes() [2/3]
template<class MatchPredicate > HashTable< wordHashSet > classes (const MatchPredicate & matchName) const
sorted() [1/10]
Foam::UPtrList< const Foam::IOobject > sorted () const
Definition at line 223 of file IOobjectList.C.
sorted() [2/10]
Foam::UPtrList< const Foam::IOobject > sorted (const bool syncPar) const
Definition at line 230 of file IOobjectList.C.
sorted() [3/10]
template<class Type > UPtrList< const IOobject > sorted () const
sorted() [4/10]
template<class Type > UPtrList< const IOobject > sorted (const bool syncPar) const
sorted() [5/10]
template<class Type , class MatchPredicate > UPtrList< const IOobject > sorted (const MatchPredicate & matchName) const
sorted() [6/10]
template<class Type , class MatchPredicate > UPtrList< const IOobject > sorted (const MatchPredicate & matchName, const bool syncPar) const
count() [1/9]
Foam::label count (const char * clsName) const
Definition at line 213 of file IOobjectList.C.
count() [2/9]
template<class MatchPredicate > label count (const MatchPredicate & matchClass) const
count() [3/9]
template<class MatchPredicate1 , class MatchPredicate2 > label count (const MatchPredicate1 & matchClass, const MatchPredicate2 & matchName) const
count() [4/9]
template<class Type > label count () const
count() [5/9]
template<class Type , class MatchPredicate > label count (const MatchPredicate & matchName) const
names() [1/20]
Foam::wordList names () const
Definition at line 238 of file IOobjectList.C.
References HashTable< T, Key, Hash >::toc().
names() [2/20]
Foam::wordList names (const bool syncPar) const
Definition at line 244 of file IOobjectList.C.
names() [3/20]
Foam::wordList names (const char * clsName) const
Definition at line 250 of file IOobjectList.C.
names() [4/20]
Foam::wordList names (const char * clsName, const bool syncPar) const
Definition at line 257 of file IOobjectList.C.
names() [5/20]
template<class MatchPredicate > wordList names (const MatchPredicate & matchClass) const
names() [6/20]
template<class MatchPredicate > wordList names (const MatchPredicate & matchClass, const bool syncPar) const
names() [7/20]
template<class MatchPredicate1 , class MatchPredicate2 > wordList names (const MatchPredicate1 & matchClass, const MatchPredicate2 & matchName) const
names() [8/20]
template<class MatchPredicate1 , class MatchPredicate2 > wordList names (const MatchPredicate1 & matchClass, const MatchPredicate2 & matchName, const bool syncPar) const
names() [9/20]
template<class Type > wordList names () const
names() [10/20]
template<class Type > wordList names (bool syncPar) const
names() [11/20]
template<class Type , class MatchPredicate > wordList names (const MatchPredicate & matchName) const
names() [12/20]
template<class Type , class MatchPredicate > wordList names (const MatchPredicate & matchName, const bool syncPar) const
sortedNames() [1/20]
Foam::wordList sortedNames () const
Definition at line 270 of file IOobjectList.C.
References HashTable< T, Key, Hash >::sortedToc().
sortedNames() [2/20]
Foam::wordList sortedNames (const bool syncPar) const
Definition at line 276 of file IOobjectList.C.
sortedNames() [3/20]
Foam::wordList sortedNames (const char * clsName) const
Definition at line 285 of file IOobjectList.C.
sortedNames() [4/20]
Foam::wordList sortedNames (const char * clsName, const bool syncPar) const
Definition at line 292 of file IOobjectList.C.
sortedNames() [5/20]
template<class MatchPredicate > wordList sortedNames (const MatchPredicate & matchClass) const
sortedNames() [6/20]
template<class MatchPredicate > wordList sortedNames (const MatchPredicate & matchClass, const bool syncPar) const
sortedNames() [7/20]
template<class MatchPredicate1 , class MatchPredicate2 > wordList sortedNames (const MatchPredicate1 & matchClass, const MatchPredicate2 & matchName) const
sortedNames() [8/20]
template<class MatchPredicate1 , class MatchPredicate2 > wordList sortedNames (const MatchPredicate1 & matchClass, const MatchPredicate2 & matchName, const bool syncPar) const
sortedNames() [9/20]
template<class Type > wordList sortedNames () const
sortedNames() [10/20]
template<class Type > wordList sortedNames (bool syncPar) const
sortedNames() [11/20]
template<class Type , class MatchPredicate > wordList sortedNames (const MatchPredicate & matchName) const
sortedNames() [12/20]
template<class Type , class MatchPredicate > wordList sortedNames (const MatchPredicate & matchName, const bool syncPar) const
filterClasses() [1/2]
template<class UnaryPredicate > label filterClasses (const UnaryPredicate & pred, const bool pruning = false)
filterObjects() [1/2]
template<class UnaryPredicate > label filterObjects (const UnaryPredicate & pred, const bool pruning = false)
prune_0()
Foam::label prune_0 ()
Definition at line 305 of file IOobjectList.C.
References HashTable< T, Key, Hash >::filterKeys(), and k.
allNames() [1/3]
Foam::wordList allNames () const
Definition at line 316 of file IOobjectList.C.
allNames() [2/3]
template<class Type > wordList allNames () const
checkNames()
void checkNames (const bool syncPar = true) const
Definition at line 325 of file IOobjectList.C.
References UPstream::parRun().
operator=() [1/2]
void operator= (const IOobjectList &) delete
operator=() [2/2]
void operator= (IOobjectList && list) inline
Definition at line 129 of file IOobjectListI.H.
lookup() [2/4]
IOobject * lookup (const char * objName) const inline
Definition at line 752 of file IOobjectList.H.
References IOobjectList::getObject().
lookup() [3/4]
IOobject * lookup (const word & objName) const inline
Definition at line 760 of file IOobjectList.H.
References IOobjectList::getObject().
classesImpl()
template<class MatchPredicate > Foam::HashTable< Foam::wordHashSet > classesImpl (const IOobjectList & list, const MatchPredicate & matchName)
Definition at line 28 of file IOobjectListTemplates.C.
References forAllConstIters, io(), and HashTable< T, Key, Hash >::size().
countImpl()
template<class MatchPredicate1 , class MatchPredicate2 > Foam::label countImpl (const IOobjectList & list, const MatchPredicate1 & matchClass, const MatchPredicate2 & matchName)
Definition at line 55 of file IOobjectListTemplates.C.
References forAllConstIters, IOobject::headerClassName(), io(), and IOobject::name().
countTypeImpl()
template<class Type , class MatchPredicate > Foam::label countTypeImpl (const IOobjectList & list, const MatchPredicate & matchName)
Definition at line 80 of file IOobjectListTemplates.C.
References forAllConstIters, io(), IOobject::isHeaderClass(), and IOobject::name().
namesImpl()
template<class MatchPredicate1 , class MatchPredicate2 > Foam::wordList namesImpl (const IOobjectList & list, const MatchPredicate1 & matchClass, const MatchPredicate2 & matchName, const bool doSort)
Definition at line 104 of file IOobjectListTemplates.C.
References forAllConstIters, IOobject::headerClassName(), io(), PtrList< T >::resize(), HashTable< T, Key, Hash >::size(), and Foam::sort().
namesTypeImpl()
template<class Type , class MatchPredicate > Foam::wordList namesTypeImpl (const IOobjectList & list, const MatchPredicate & matchName, const bool doSort)
Definition at line 140 of file IOobjectListTemplates.C.
References forAllConstIters, io(), IOobject::isHeaderClass(), PtrList< T >::resize(), HashTable< T, Key, Hash >::size(), and Foam::sort().
objectsTypeImpl()
template<class Type , class MatchPredicate > Foam::UPtrList< const Foam::IOobject > objectsTypeImpl (const IOobjectList & list, const MatchPredicate & matchName)
Definition at line 176 of file IOobjectListTemplates.C.
References forAllConstIters, io(), IOobject::isHeaderClass(), PtrList< T >::resize(), PtrList< T >::set(), HashTable< T, Key, Hash >::size(), and Foam::sort().
lookupImpl()
template<class MatchPredicate > Foam::IOobjectList lookupImpl (const IOobjectList & list, const MatchPredicate & matchName)
Definition at line 207 of file IOobjectListTemplates.C.
References Foam::endl(), forAllConstIters, InfoInFunction, io(), PtrList< T >::set(), and HashTable< T, Key, Hash >::size().
lookupClassImpl()
template<class MatchPredicate1 , class MatchPredicate2 > Foam::IOobjectList lookupClassImpl (const IOobjectList & list, const MatchPredicate1 & matchClass, const MatchPredicate2 & matchName)
Definition at line 237 of file IOobjectListTemplates.C.
References Foam::endl(), forAllConstIters, IOobject::headerClassName(), InfoInFunction, io(), PtrList< T >::set(), and HashTable< T, Key, Hash >::size().
lookupClassTypeImpl()
template<class Type , class MatchPredicate > Foam::IOobjectList lookupClassTypeImpl (const IOobjectList & list, const MatchPredicate & matchName)
Definition at line 268 of file IOobjectListTemplates.C.
References Foam::endl(), forAllConstIters, InfoInFunction, io(), IOobject::isHeaderClass(), PtrList< T >::set(), and HashTable< T, Key, Hash >::size().
cfindObject() [3/3]
template<class Type > const Foam::IOobject * cfindObject (const word & objName) const
Definition at line 299 of file IOobjectListTemplates.C.
References Foam::endl(), HashTable< T, Key, Hash >::Iterator< Const >::good(), InfoInFunction, io(), IOobject::isHeaderClass(), and HashTable< T, Key, Hash >::const_iterator::val().
findObject() [5/6]
template<class Type > const Foam::IOobject * findObject (const word & objName) const
Definition at line 343 of file IOobjectListTemplates.C.
findObject() [6/6]
template<class Type > Foam::IOobject * findObject (const word & objName)
Definition at line 353 of file IOobjectListTemplates.C.
getObject() [3/3]
template<class Type > Foam::IOobject * getObject (const word & objName) const
Definition at line 360 of file IOobjectListTemplates.C.
lookup() [4/4]
template<class MatchPredicate > Foam::IOobjectList lookup (const MatchPredicate & matchName) const
Definition at line 367 of file IOobjectListTemplates.C.
lookupClass() [6/9]
template<class MatchPredicate > Foam::IOobjectList lookupClass (const MatchPredicate & matchClass) const
Definition at line 377 of file IOobjectListTemplates.C.
lookupClass() [7/9]
template<class MatchPredicate1 , class MatchPredicate2 > Foam::IOobjectList lookupClass (const MatchPredicate1 & matchClass, const MatchPredicate2 & matchName) const
Definition at line 387 of file IOobjectListTemplates.C.
lookupClass() [8/9]
template<class Type > Foam::IOobjectList lookupClass () const
Definition at line 398 of file IOobjectListTemplates.C.
lookupClass() [9/9]
template<class Type , class MatchPredicate > Foam::IOobjectList lookupClass (const MatchPredicate & matchName) const
Definition at line 405 of file IOobjectListTemplates.C.
classes() [3/3]
template<class MatchPredicate > Foam::HashTable< Foam::wordHashSet > classes (const MatchPredicate & matchName) const
Definition at line 416 of file IOobjectListTemplates.C.
count() [6/9]
template<class MatchPredicate > Foam::label count (const MatchPredicate & matchClass) const
Definition at line 426 of file IOobjectListTemplates.C.
count() [7/9]
template<class MatchPredicate1 , class MatchPredicate2 > Foam::label count (const MatchPredicate1 & matchClass, const MatchPredicate2 & matchName) const
Definition at line 436 of file IOobjectListTemplates.C.
count() [8/9]
template<class Type > Foam::label count () const
Definition at line 447 of file IOobjectListTemplates.C.
count() [9/9]
template<class Type , class MatchPredicate > Foam::label count (const MatchPredicate & matchName) const
Definition at line 454 of file IOobjectListTemplates.C.
sorted() [7/10]
template<class Type > Foam::UPtrList< const Foam::IOobject > sorted () const
Definition at line 468 of file IOobjectListTemplates.C.
sorted() [8/10]
template<class Type > Foam::UPtrList< const Foam::IOobject > sorted (const bool syncPar) const
Definition at line 476 of file IOobjectListTemplates.C.
sorted() [9/10]
template<class Type , class MatchPredicate > Foam::UPtrList< const Foam::IOobject > sorted (const MatchPredicate & matchName) const
Definition at line 491 of file IOobjectListTemplates.C.
sorted() [10/10]
template<class Type , class MatchPredicate > Foam::UPtrList< const Foam::IOobject > sorted (const MatchPredicate & matchName, const bool syncPar) const
Definition at line 502 of file IOobjectListTemplates.C.
names() [13/20]
template<class MatchPredicate > Foam::wordList names (const MatchPredicate & matchClass) const
Definition at line 522 of file IOobjectListTemplates.C.
names() [14/20]
template<class MatchPredicate > Foam::wordList names (const MatchPredicate & matchClass, const bool syncPar) const
Definition at line 532 of file IOobjectListTemplates.C.
names() [15/20]
template<class MatchPredicate1 , class MatchPredicate2 > Foam::wordList names (const MatchPredicate1 & matchClass, const MatchPredicate2 & matchName) const
Definition at line 543 of file IOobjectListTemplates.C.
names() [16/20]
template<class MatchPredicate1 , class MatchPredicate2 > Foam::wordList names (const MatchPredicate1 & matchClass, const MatchPredicate2 & matchName, const bool syncPar) const
Definition at line 554 of file IOobjectListTemplates.C.
names() [17/20]
template<class Type > Foam::wordList names () const
Definition at line 566 of file IOobjectListTemplates.C.
names() [18/20]
template<class Type > Foam::wordList names (const bool syncPar) const
Definition at line 573 of file IOobjectListTemplates.C.
names() [19/20]
template<class Type , class MatchPredicate > Foam::wordList names (const MatchPredicate & matchName) const
Definition at line 580 of file IOobjectListTemplates.C.
names() [20/20]
template<class Type , class MatchPredicate > Foam::wordList names (const MatchPredicate & matchName, const bool syncPar) const
Definition at line 590 of file IOobjectListTemplates.C.
sortedNames() [13/20]
template<class MatchPredicate > Foam::wordList sortedNames (const MatchPredicate & matchClass) const
Definition at line 603 of file IOobjectListTemplates.C.
sortedNames() [14/20]
template<class MatchPredicate > Foam::wordList sortedNames (const MatchPredicate & matchClass, const bool syncPar) const
Definition at line 613 of file IOobjectListTemplates.C.
sortedNames() [15/20]
template<class MatchPredicate1 , class MatchPredicate2 > Foam::wordList sortedNames (const MatchPredicate1 & matchClass, const MatchPredicate2 & matchName) const
Definition at line 630 of file IOobjectListTemplates.C.
sortedNames() [16/20]
template<class MatchPredicate1 , class MatchPredicate2 > Foam::wordList sortedNames (const MatchPredicate1 & matchClass, const MatchPredicate2 & matchName, const bool syncPar) const
Definition at line 641 of file IOobjectListTemplates.C.
sortedNames() [17/20]
template<class Type > Foam::wordList sortedNames () const
Definition at line 656 of file IOobjectListTemplates.C.
sortedNames() [18/20]
template<class Type > Foam::wordList sortedNames (const bool syncPar) const
Definition at line 663 of file IOobjectListTemplates.C.
sortedNames() [19/20]
template<class Type , class MatchPredicate > Foam::wordList sortedNames (const MatchPredicate & matchName) const
Definition at line 673 of file IOobjectListTemplates.C.
sortedNames() [20/20]
template<class Type , class MatchPredicate > Foam::wordList sortedNames (const MatchPredicate & matchName, const bool syncPar) const
Definition at line 683 of file IOobjectListTemplates.C.
filterClasses() [2/2]
template<class UnaryPredicate > Foam::label filterClasses (const UnaryPredicate & pred, const bool pruning)
Definition at line 699 of file IOobjectListTemplates.C.
References erase().
filterObjects() [2/2]
template<class UnaryPredicate > Foam::label filterObjects (const UnaryPredicate & pred, const bool pruning)
Definition at line 736 of file IOobjectListTemplates.C.
References erase().
allNames() [3/3]
template<class Type > Foam::wordList allNames () const
Definition at line 769 of file IOobjectListTemplates.C.
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOobjectList/IOobjectList.H
src/OpenFOAM/db/IOobjectList/IOobjectList.C
src/OpenFOAM/db/IOobjectList/IOobjectListI.H
src/OpenFOAM/db/IOobjectList/IOobjectListTemplates.C