OpenFOAM: labelRange Class Reference
labelRange Class Reference
A range or interval of labels defined by a start and a size.
#include <labelRange.H>
Public Member Functions
constexpr labelRange () noexcept
constexpr labelRange (const label len) noexcept
labelRange (const label beg, const label len) noexcept
labelRange (const label beg, const label len, const bool adjustStart) noexcept
labelRange (const MinMax< label > &range) noexcept
labelRange (Istream &is)
void adjust () noexcept
void reset (const label beg, const label end, const bool adjustStart) noexcept
List< label > labels () const
bool overlaps (const labelRange &range, bool touches=false) const
labelRange join (const labelRange &range) const
labelRange subset (const labelRange &range) const
labelRange subset (const label start, const label size) const
labelRange subset0 (const label size) const
bool valid () const noexcept
Public Member Functions inherited from IntRange< label >
constexpr IntRange () noexcept
constexpr IntRange (const label len) noexcept
constexpr IntRange (const label beg, const label len) noexcept
bool empty () const noexcept
label size () const noexcept
label & size () noexcept
label start () const noexcept
label & start () noexcept
label min () const noexcept
label max () const noexcept
void clear () noexcept
void reset (const label beg, const label len) noexcept
void setStart (const label i) noexcept
void setSize (const label n) noexcept
void resize (const label n) noexcept
void clampSize () noexcept
bool contains (const label value) const noexcept
bool found (const label val) const noexcept
const_iterator at (const label i) const
constexpr label operator[] (const label i) const noexcept
bool operator() (const label i) const noexcept
label operator++ () noexcept
label operator++ (int) noexcept
label operator+= (const label n) noexcept
label operator-- () noexcept
label operator-- (int) noexcept
label operator-= (const label n) noexcept
operator bool () const noexcept
label begin_value () const noexcept
label end_value () const noexcept
label rbegin_value () const noexcept
label rend_value () const noexcept
const_iterator begin () const noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
const_iterator end () const noexcept
const_reverse_iterator rbegin () const noexcept
const_reverse_iterator crbegin () const noexcept
const_reverse_iterator rend () const noexcept
const_reverse_iterator crend () const noexcept
Static Public Attributes
static int debug
Additional Inherited Members
Public Types inherited from IntRange< label >
typedef label value_type
typedef label size_type
Detailed Description
A range or interval of labels defined by a start and a size.
Source files
labelRange.H
labelRange.C
labelRangeI.H
Definition at line 51 of file labelRange.H.
Constructor & Destructor Documentation
labelRange() [1/6]
constexpr labelRange () inline constexpr noexcept
Definition at line 24 of file labelRangeI.H.
labelRange() [2/6]
constexpr labelRange (const label len) inline explicit constexpr noexcept
Definition at line 30 of file labelRangeI.H.
labelRange() [3/6]
labelRange (const label beg, const label len) inline noexcept
Definition at line 36 of file labelRangeI.H.
labelRange() [4/6]
labelRange (const label beg, const label len, const bool adjustStart) inline noexcept
Definition at line 48 of file labelRangeI.H.
labelRange() [5/6]
labelRange (const MinMax< label > & range) explicit noexcept
Definition at line 37 of file labelRange.C.
References IntRange< IntType >::min(), Foam::noexcept, and range.
labelRange() [6/6]
labelRange (Istream & is) explicit
Definition at line 49 of file labelRange.C.
Member Function Documentation
adjust()
void adjust () noexcept
Definition at line 74 of file labelRange.C.
Referenced by bitSet::set(), Foam::BitOps::set(), and Foam::BitOps::set().
reset()
void reset (const label beg, const label end, const bool adjustStart) inline noexcept
Definition at line 70 of file labelRangeI.H.
labels()
Foam::List< Foam::label > labels () const
Definition at line 59 of file labelRange.C.
References UPtrList< T >::begin(), and UPtrList< T >::end().
overlaps()
bool overlaps (const labelRange & range, bool touches = false) const
Definition at line 89 of file labelRange.C.
References range, and UPtrList< T >::size().
join()
Foam::labelRange join (const labelRange & range) const
Definition at line 112 of file labelRange.C.
References IntRange< IntType >::max(), Foam::max(), IntRange< IntType >::min(), Foam::min(), range, and UPtrList< T >::size().
subset() [1/2]
Foam::labelRange subset (const labelRange & range) const
Definition at line 137 of file labelRange.C.
References IntRange< IntType >::max(), Foam::max(), IntRange< IntType >::min(), and Foam::min().
subset() [2/2]
Foam::labelRange subset (const label start, const label size) const
Definition at line 154 of file labelRange.C.
References Foam::max(), and Foam::min().
subset0()
Foam::labelRange subset0 (const label size) const
Definition at line 175 of file labelRange.C.
References Foam::max(), and Foam::min().
valid()
bool valid () const inline noexcept
Definition at line 163 of file labelRange.H.
References IntRange< label >::empty().
Member Data Documentation
debug
int debug static
Definition at line 69 of file labelRange.H.
Referenced by labelRanges::remove().
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/ranges/labelRange/labelRange.H
src/OpenFOAM/primitives/ranges/labelRange/labelRange.C
src/OpenFOAM/primitives/ranges/labelRange/labelRangeI.H