OpenFOAM: MeshedSurfaceProxy< Face > Class Template Reference
MeshedSurfaceProxy< Face > Class Template Reference
A proxy for writing MeshedSurface, UnsortedMeshedSurface and surfMesh to various file formats.
#include <MeshedSurfaceProxy.H>
Public Types
typedef Face face_type
typedef point point_type
Public Member Functions
ClassName ("MeshedSurfaceProxy")
MeshedSurfaceProxy (const pointField &pointLst, const UList< Face > &faceLst, const UList< surfZone > &zoneLst=UList< surfZone >::null(), const labelUList &faceMap=labelUList::null(), const labelUList &faceIdLst=labelUList::null())
virtual ~MeshedSurfaceProxy ()=default
declareMemberFunctionSelectionTable (void, MeshedSurfaceProxy, write, fileExtension,(const fileName &name, const MeshedSurfaceProxy< Face > &surf, IOstreamOption streamOpt, const dictionary &options),(name, surf, streamOpt, options))
label size () const
const pointField & points () const
const UList< Face > & surfFaces () const
const UList< surfZone > & surfZones () const
const labelUList & faceMap () const
const labelUList & faceIds () const
bool useFaceMap () const
bool useFaceIds () const
label nTriangles () const
virtual void write (const fileName &name, IOstreamOption streamOpt=IOstreamOption(), const dictionary &options=dictionary::null) const
virtual void write (const fileName &name, const word &fileType, IOstreamOption streamOpt=IOstreamOption(), const dictionary &options=dictionary::null) const
virtual void write (const Time &t, const word &surfName=word::null) const
Public Member Functions inherited from surfaceFormatsCore
surfaceFormatsCore ()=default
virtual ~surfaceFormatsCore ()=default
Static Public Member Functions
static wordHashSet writeTypes ()
static bool canWriteType (const word &fileType, bool verbose=false)
static void write (const fileName &name, const MeshedSurfaceProxy &surf, IOstreamOption streamOpt=IOstreamOption(), const dictionary &options=dictionary::null)
static void write (const fileName &name, const word &fileType, const MeshedSurfaceProxy &surf, IOstreamOption streamOpt=IOstreamOption(), const dictionary &options=dictionary::null)
Static Public Member Functions inherited from surfaceFormatsCore
static bool checkSupport (const wordHashSet &available, const word &fileType, const bool verbose=false, const char *functionName=nullptr)
static fileName findFile (const IOobject &io, const bool isGlobal=true)
static fileName findFile (const IOobject &io, const dictionary &dict, const bool isGlobal=true)
Additional Inherited Members
Static Public Attributes inherited from surfaceFormatsCore
static word nativeExt
Static Protected Member Functions inherited from surfaceFormatsCore
static string getLineNoComment (ISstream &is, const char comment='#')
template<class Container >
static List< surfZone > oneZone (const Container &container, const word &name="zone0")
static labelList getSelectedPatches (const surfZoneList &patches, const wordRes &allow, const wordRes &deny=wordRes())
static fileName relativeFilePath (const IOobject &io, const fileName &f, const bool isGlobal=true)
static fileName checkFile (const IOobject &io, const bool isGlobal=true)
static fileName checkFile (const IOobject &io, const dictionary &dict, const bool isGlobal=true)
Detailed Description
template<class Face>
class Foam::MeshedSurfaceProxy< Face >
A proxy for writing MeshedSurface, UnsortedMeshedSurface and surfMesh to various file formats.
The constructor interface is fat and ugly, but is largely encapsulated by conversion operators in other classes.
Source files
MeshedSurfaceProxy.H
MeshedSurfaceProxy.C
MeshedSurfaceProxys.C
Definition at line 60 of file MeshedSurfaceProxy.H.
Member Typedef Documentation
face_type
template<class Face > typedef Face face_type
Definition at line 82 of file MeshedSurfaceProxy.H.
point_type
template<class Face > typedef point point_type
Definition at line 85 of file MeshedSurfaceProxy.H.
Constructor & Destructor Documentation
MeshedSurfaceProxy()
template<class Face > MeshedSurfaceProxy (const pointField & pointLst, const UList< Face > & faceLst, const UList< surfZone > & zoneLst = UList<surfZone>::null(), const labelUList & faceMap = labelUList::null(), const labelUList & faceIdLst = labelUList::null())
Definition at line 229 of file MeshedSurfaceProxy.C.
~MeshedSurfaceProxy()
template<class Face > virtual ~MeshedSurfaceProxy () virtual default
Member Function Documentation
ClassName()
template<class Face > ClassName ("MeshedSurfaceProxy< Face >")
writeTypes()
template<class Face > Foam::wordHashSet writeTypes () static
Definition at line 32 of file MeshedSurfaceProxy.C.
Referenced by surfaceWriter::New(), and surfaceWriter::New().
canWriteType()
template<class Face > bool canWriteType (const word & fileType, bool verbose = false) static
Definition at line 39 of file MeshedSurfaceProxy.C.
References surfaceFormatsCore::checkSupport().
declareMemberFunctionSelectionTable()
template<class Face > declareMemberFunctionSelectionTable (void , MeshedSurfaceProxy< Face > , write , fileExtension , (const fileName &name, const MeshedSurfaceProxy< Face > &surf, IOstreamOption streamOpt, const dictionary &options) , (name, surf, streamOpt, options))
write() [1/5]
template<class Face > void write (const fileName & name, const MeshedSurfaceProxy< Face > & surf, IOstreamOption streamOpt = IOstreamOption(), const dictionary & options = dictionary::null) static
Definition at line 56 of file MeshedSurfaceProxy.C.
References word::ext(), Foam::name(), and write().
write() [2/5]
template<class Face > void write (const fileName & name, const word & fileType, const MeshedSurfaceProxy< Face > & surf, IOstreamOption streamOpt = IOstreamOption(), const dictionary & options = dictionary::null) static
Definition at line 69 of file MeshedSurfaceProxy.C.
References DebugInFunction, UPtrList< T >::empty(), Foam::exit(), word::ext(), Foam::FatalError, FatalErrorInFunction, Foam::flatOutput(), Foam::name(), Foam::nl, and write().
size()
template<class Face > label size () const inline
Definition at line 161 of file MeshedSurfaceProxy.H.
References UPtrList< T >::size().
points()
template<class Face > const pointField & points () const inline
Definition at line 167 of file MeshedSurfaceProxy.H.
surfFaces()
template<class Face > const UList< Face > & surfFaces () const inline
Definition at line 173 of file MeshedSurfaceProxy.H.
surfZones()
template<class Face > const UList< surfZone > & surfZones () const inline
Definition at line 181 of file MeshedSurfaceProxy.H.
faceMap()
template<class Face > const labelUList & faceMap () const inline
Definition at line 187 of file MeshedSurfaceProxy.H.
faceIds()
template<class Face > const labelUList & faceIds () const inline
Definition at line 193 of file MeshedSurfaceProxy.H.
useFaceMap()
template<class Face > bool useFaceMap () const inline
Definition at line 199 of file MeshedSurfaceProxy.H.
References UPtrList< T >::size().
useFaceIds()
template<class Face > bool useFaceIds () const inline
Definition at line 205 of file MeshedSurfaceProxy.H.
References UPtrList< T >::size().
nTriangles()
template<class Face > Foam::label nTriangles () const inline
Definition at line 249 of file MeshedSurfaceProxy.C.
References f().
write() [3/5]
template<class Face > virtual void write (const fileName & name, IOstreamOption streamOpt = IOstreamOption(), const dictionary & options = dictionary::null) const inline virtual
Definition at line 217 of file MeshedSurfaceProxy.H.
References Foam::name(), and write().
write() [4/5]
template<class Face > virtual void write (const fileName & name, const word & fileType, IOstreamOption streamOpt = IOstreamOption(), const dictionary & options = dictionary::null) const inline virtual
Definition at line 229 of file MeshedSurfaceProxy.H.
References Foam::name(), and write().
write() [5/5]
template<class Face > void write (const Time & t, const word & surfName = word::null) const virtual
Definition at line 115 of file MeshedSurfaceProxy.C.
References DebugInFunction, surfaceRegistry::defaultName, Foam::endl(), Foam::faceMap(), io(), Foam::isDir(), surfMesh::meshSubDir, Foam::mkDir(), IOobject::name(), Foam::name(), IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, os(), points, surfaceRegistry::prefix, UPtrList< T >::size(), Time::timeName(), Time::timePath(), IOobject::writeEndDivider(), IOobject::writeHeader(), and Time::writeStreamOption().
The documentation for this class was generated from the following files:
src/surfMesh/MeshedSurface/MeshedSurface.H
src/surfMesh/MeshedSurfaceProxy/MeshedSurfaceProxy.H
src/surfMesh/MeshedSurfaceProxy/MeshedSurfaceProxy.C