OpenFOAM: lineEdge Class Reference
lineEdge Class Reference
A straight edge between the start point and the end point.
#include <lineEdge.H>
Public Member Functions
TypeName ("line")
lineEdge (const pointField &points, const edge &fromTo)
lineEdge (const pointField &points, const label from, const label to)
lineEdge (const dictionary &dict, const label index, const searchableSurfaces &, const pointField &points, Istream &is)
virtual ~lineEdge ()=default
point position (const scalar) const
scalar length () const
Public Member Functions inherited from blockEdge
TypeName ("blockEdge")
declareRunTimeSelectionTable (autoPtr, blockEdge, Istream,(const dictionary &dict, const label index, const searchableSurfaces &geometry, const pointField &points, Istream &is),(dict, index, geometry, points, is))
blockEdge (const pointField &points, const edge &fromTo)
blockEdge (const dictionary &dict, const label index, const pointField &points, Istream &is)
virtual autoPtr< blockEdge > clone () const
virtual ~blockEdge ()=default
bool valid () const noexcept
label start () const noexcept
label end () const noexcept
const point & firstPoint () const
const point & lastPoint () const
int compare (const blockEdge &e) const
int compare (const edge &e) const
int compare (const label start, const label end) const
point linearPosition (const scalar lambda) const
virtual tmp< pointField > position (const scalarList &lambdas) const
void write (Ostream &os, const dictionary &dict) const
Additional Inherited Members
Static Public Member Functions inherited from blockEdge
static autoPtr< blockEdge > New (const dictionary &dict, const label index, const searchableSurfaces &geometry, const pointField &points, Istream &is)
Protected Member Functions inherited from blockEdge
blockEdge (const pointField &points, const label from, const label to)
Static Protected Member Functions inherited from blockEdge
static pointField appendEndPoints (const pointField &p, const label from, const label to, const pointField &intermediate)
Protected Attributes inherited from blockEdge
const pointField & points_
const label start_
const label end_
Detailed Description
A straight edge between the start point and the end point.
Source files
lineEdge.H
lineEdge.C
Definition at line 49 of file lineEdge.H.
Constructor & Destructor Documentation
lineEdge() [1/3]
lineEdge (const pointField & points, const edge & fromTo)
Parameters
points Referenced point field
fromTo Start/end in point field
Definition at line 39 of file lineEdge.C.
lineEdge() [2/3]
lineEdge (const pointField & points, const label from, const label to)
Parameters
points Referenced point field
from Start point in point field
to End point in point field
Definition at line 49 of file lineEdge.C.
lineEdge() [3/3]
lineEdge (const dictionary & dict, const label index, const searchableSurfaces & , const pointField & points, Istream & is)
Parameters
points Referenced point field
Definition at line 60 of file lineEdge.C.
~lineEdge()
virtual ~lineEdge () virtual default
Member Function Documentation
TypeName()
TypeName ("line")
position()
Foam::point position (const scalar lambda) const virtual
Implements blockEdge.
Definition at line 75 of file lineEdge.C.
References lambda(), and blockEdge::linearPosition().
length()
Foam::scalar length () const virtual
Implements blockEdge.
Definition at line 81 of file lineEdge.C.
References Foam::mag().
The documentation for this class was generated from the following files:
src/mesh/blockMesh/blockEdges/lineEdge/lineEdge.H
src/mesh/blockMesh/blockEdges/lineEdge/lineEdge.C