OpenFOAM: meshToMesh Class Reference
meshToMesh Class Reference
Class to calculate the cell-addressing between two overlapping meshes.
#include <meshToMesh.H>
Public Types
enum class interpolationMethod { imDirect , imMapNearest , imCellVolumeWeight , imCorrectedCellVolumeWeight }
enum class procMapMethod { pmAABB , pmLOD }
Public Member Functions
TypeName ("meshToMesh")
meshToMesh (const polyMesh &src, const polyMesh &tgt, const interpolationMethod &method, const procMapMethod &mapMethod=procMapMethod::pmAABB, const bool interpAllPatches=true)
meshToMesh (const polyMesh &src, const polyMesh &tgt, const word &methodName, const word &AMIMethodName, const procMapMethod &mapMethod=procMapMethod::pmAABB, const bool interpAllPatches=true)
meshToMesh (const polyMesh &src, const polyMesh &tgt, const interpolationMethod &method, const HashTable< word > &patchMap, const wordList &cuttingPatches, const procMapMethod &mapMethod=procMapMethod::pmAABB, const bool normalise=true)
meshToMesh (const polyMesh &src, const polyMesh &tgt, const word &methodName, const word &AMIMethodName, const HashTable< word > &patchMap, const wordList &cuttingPatches, const procMapMethod &mapMethod=procMapMethod::pmAABB, const bool normalise=true)
virtual ~meshToMesh ()
const polyMesh & srcRegion () const
const polyMesh & tgtRegion () const
const labelListList & srcToTgtCellAddr () const
const labelListList & tgtToSrcCellAddr () const
const scalarListList & srcToTgtCellWght () const
const scalarListList & tgtToSrcCellWght () const
const pointListList & srcToTgtCellVec () const
const pointListList & tgtToSrcCellVec () const
scalar V () const
const PtrList< AMIPatchToPatchInterpolation > & patchAMIs () const
const autoPtr< mapDistribute > & srcMap () const
const autoPtr< mapDistribute > & tgtMap () const
template<class Type , class CombineOp >
void mapSrcToTgt (const UList< Type > &srcFld, const CombineOp &cop, List< Type > &result) const
template<class Type , class CombineOp >
void mapSrcToTgt (const UList< Type > &srcField, const UList< typename outerProduct< vector, Type >::type > &, const CombineOp &cop, List< Type > &result) const
template<class Type , class CombineOp >
tmp< Field< Type > > mapSrcToTgt (const Field< Type > &srcFld, const CombineOp &cop) const
template<class Type , class CombineOp >
tmp< Field< Type > > mapSrcToTgt (const tmp< Field< Type > > &tsrcFld, const CombineOp &cop) const
template<class Type >
tmp< Field< Type > > mapSrcToTgt (const Field< Type > &srcFld) const
template<class Type >
tmp< Field< Type > > mapSrcToTgt (const tmp< Field< Type > > &tsrcFld) const
template<class Type , class CombineOp >
void mapTgtToSrc (const UList< Type > &tgtFld, const CombineOp &cop, List< Type > &result) const
template<class Type , class CombineOp >
void mapTgtToSrc (const UList< Type > &srcField, const UList< typename outerProduct< vector, Type >::type > &, const CombineOp &cop, List< Type > &result) const
template<class Type , class CombineOp >
tmp< Field< Type > > mapTgtToSrc (const Field< Type > &tgtFld, const CombineOp &cop) const
template<class Type , class CombineOp >
tmp< Field< Type > > mapTgtToSrc (const tmp< Field< Type > > &ttgtFld, const CombineOp &cop) const
template<class Type >
tmp< Field< Type > > mapTgtToSrc (const Field< Type > &tgtFld) const
template<class Type >
tmp< Field< Type > > mapTgtToSrc (const tmp< Field< Type > > &ttgtFld) const
template<class Type , class CombineOp >
void mapSrcToTgt (const VolumeField< Type > &field, const CombineOp &cop, VolumeField< Type > &result, const bool secondOrder=true) const
template<class Type , class CombineOp >
tmp< VolumeField< Type > > mapSrcToTgt (const VolumeField< Type > &field, const CombineOp &cop, const bool secondOrder=true) const
template<class Type , class CombineOp >
tmp< VolumeField< Type > > mapSrcToTgt (const tmp< VolumeField< Type > > &tfield, const CombineOp &cop, const bool secondOrder=true) const
template<class Type >
tmp< VolumeField< Type > > mapSrcToTgt (const VolumeField< Type > &field, const bool secondOrder=true) const
template<class Type >
tmp< VolumeField< Type > > mapSrcToTgt (const tmp< VolumeField< Type > > &tfield, const bool secondOrder=true) const
template<class Type , class CombineOp >
void mapTgtToSrc (const VolumeField< Type > &field, const CombineOp &cop, VolumeField< Type > &result, const bool secondOrder=true) const
template<class Type , class CombineOp >
tmp< VolumeField< Type > > mapTgtToSrc (const VolumeField< Type > &field, const CombineOp &cop, const bool secondOrder=true) const
template<class Type , class CombineOp >
tmp< VolumeField< Type > > mapTgtToSrc (const tmp< VolumeField< Type > > &tfield, const CombineOp &cop, const bool secondOrder=true) const
template<class Type >
tmp< VolumeField< Type > > mapTgtToSrc (const VolumeField< Type > &field, const bool secondOrder=true) const
template<class Type >
tmp< VolumeField< Type > > mapTgtToSrc (const tmp< VolumeField< Type > > &tfield, const bool secondOrder=true) const
template<>
void mapInternalSrcToTgt (const VolumeField< sphericalTensor > &field, const plusEqOp< sphericalTensor > &cop, VolumeField< sphericalTensor > &result, const bool secondOrder) const
template<>
void mapInternalSrcToTgt (const VolumeField< sphericalTensor > &field, const minusEqOp< sphericalTensor > &cop, VolumeField< sphericalTensor > &result, const bool secondOrder) const
template<>
void mapInternalSrcToTgt (const VolumeField< symmTensor > &field, const plusEqOp< symmTensor > &cop, VolumeField< symmTensor > &result, const bool secondOrder) const
template<>
void mapInternalSrcToTgt (const VolumeField< symmTensor > &field, const minusEqOp< symmTensor > &cop, VolumeField< symmTensor > &result, const bool secondOrder) const
template<>
void mapInternalSrcToTgt (const VolumeField< tensor > &field, const plusEqOp< tensor > &cop, VolumeField< tensor > &result, const bool secondOrder) const
template<>
void mapInternalSrcToTgt (const VolumeField< tensor > &field, const minusEqOp< tensor > &cop, VolumeField< tensor > &result, const bool secondOrder) const
template<>
void mapInternalTgtToSrc (const VolumeField< sphericalTensor > &field, const plusEqOp< sphericalTensor > &cop, VolumeField< sphericalTensor > &result, const bool secondOrder) const
template<>
void mapInternalTgtToSrc (const VolumeField< sphericalTensor > &field, const minusEqOp< sphericalTensor > &cop, VolumeField< sphericalTensor > &result, const bool secondOrder) const
template<>
void mapInternalTgtToSrc (const VolumeField< symmTensor > &field, const plusEqOp< symmTensor > &cop, VolumeField< symmTensor > &result, const bool secondOrder) const
template<>
void mapInternalTgtToSrc (const VolumeField< symmTensor > &field, const minusEqOp< symmTensor > &cop, VolumeField< symmTensor > &result, const bool secondOrder) const
template<>
void mapInternalTgtToSrc (const VolumeField< tensor > &field, const plusEqOp< tensor > &cop, VolumeField< tensor > &result, const bool secondOrder) const
template<>
void mapInternalTgtToSrc (const VolumeField< tensor > &field, const minusEqOp< tensor > &cop, VolumeField< tensor > &result, const bool secondOrder) const
template<>
void mapAndOpSrcToTgt (const AMIPatchToPatchInterpolation &AMI, const Field< scalar > &srcField, Field< scalar > &tgtField, const plusEqOp< scalar > &cop) const
template<>
void mapAndOpSrcToTgt (const AMIPatchToPatchInterpolation &AMI, const Field< vector > &srcField, Field< vector > &tgtField, const plusEqOp< vector > &cop) const
template<>
void mapAndOpSrcToTgt (const AMIPatchToPatchInterpolation &AMI, const Field< sphericalTensor > &srcField, Field< sphericalTensor > &tgtField, const plusEqOp< sphericalTensor > &cop) const
template<>
void mapAndOpSrcToTgt (const AMIPatchToPatchInterpolation &AMI, const Field< symmTensor > &srcField, Field< symmTensor > &tgtField, const plusEqOp< symmTensor > &cop) const
template<>
void mapAndOpSrcToTgt (const AMIPatchToPatchInterpolation &AMI, const Field< tensor > &srcField, Field< tensor > &tgtField, const plusEqOp< tensor > &cop) const
template<>
void mapAndOpTgtToSrc (const AMIPatchToPatchInterpolation &AMI, Field< scalar > &srcField, const Field< scalar > &tgtField, const plusEqOp< scalar > &cop) const
template<>
void mapAndOpTgtToSrc (const AMIPatchToPatchInterpolation &AMI, Field< vector > &srcField, const Field< vector > &tgtField, const plusEqOp< vector > &cop) const
template<>
void mapAndOpTgtToSrc (const AMIPatchToPatchInterpolation &AMI, Field< sphericalTensor > &srcField, const Field< sphericalTensor > &tgtField, const plusEqOp< sphericalTensor > &cop) const
template<>
void mapAndOpTgtToSrc (const AMIPatchToPatchInterpolation &AMI, Field< symmTensor > &srcField, const Field< symmTensor > &tgtField, const plusEqOp< symmTensor > &cop) const
template<>
void mapAndOpTgtToSrc (const AMIPatchToPatchInterpolation &AMI, Field< tensor > &srcField, const Field< tensor > &tgtField, const plusEqOp< tensor > &cop) const
template<>
void mapInternalSrcToTgt (const VolumeField< sphericalTensor > &, const plusEqOp< sphericalTensor > &, VolumeField< sphericalTensor > &, const bool) const
template<>
void mapInternalSrcToTgt (const VolumeField< sphericalTensor > &, const minusEqOp< sphericalTensor > &, VolumeField< sphericalTensor > &, const bool) const
template<>
void mapInternalSrcToTgt (const VolumeField< symmTensor > &, const plusEqOp< symmTensor > &, VolumeField< symmTensor > &, const bool) const
template<>
void mapInternalSrcToTgt (const VolumeField< symmTensor > &, const minusEqOp< symmTensor > &, VolumeField< symmTensor > &, const bool) const
template<>
void mapInternalSrcToTgt (const VolumeField< tensor > &, const plusEqOp< tensor > &, VolumeField< tensor > &, const bool) const
template<>
void mapInternalSrcToTgt (const VolumeField< tensor > &, const minusEqOp< tensor > &, VolumeField< tensor > &, const bool) const
template<>
void mapInternalTgtToSrc (const VolumeField< sphericalTensor > &, const plusEqOp< sphericalTensor > &, VolumeField< sphericalTensor > &, const bool) const
template<>
void mapInternalTgtToSrc (const VolumeField< sphericalTensor > &, const minusEqOp< sphericalTensor > &, VolumeField< sphericalTensor > &, const bool) const
template<>
void mapInternalTgtToSrc (const VolumeField< symmTensor > &, const plusEqOp< symmTensor > &, VolumeField< symmTensor > &, const bool) const
template<>
void mapInternalTgtToSrc (const VolumeField< symmTensor > &, const minusEqOp< symmTensor > &, VolumeField< symmTensor > &, const bool) const
template<>
void mapInternalTgtToSrc (const VolumeField< tensor > &, const plusEqOp< tensor > &, VolumeField< tensor > &, const bool) const
template<>
void mapInternalTgtToSrc (const VolumeField< tensor > &, const minusEqOp< tensor > &, VolumeField< tensor > &, const bool) const
template<>
void mapAndOpSrcToTgt (const AMIPatchToPatchInterpolation &AMI, const Field< scalar > &srcField, Field< scalar > &tgtField, const plusEqOp< scalar > &cop) const
template<>
void mapAndOpSrcToTgt (const AMIPatchToPatchInterpolation &AMI, const Field< vector > &srcField, Field< vector > &tgtField, const plusEqOp< vector > &cop) const
template<>
void mapAndOpSrcToTgt (const AMIPatchToPatchInterpolation &AMI, const Field< sphericalTensor > &srcField, Field< sphericalTensor > &tgtField, const plusEqOp< sphericalTensor > &cop) const
template<>
void mapAndOpSrcToTgt (const AMIPatchToPatchInterpolation &AMI, const Field< symmTensor > &srcField, Field< symmTensor > &tgtField, const plusEqOp< symmTensor > &cop) const
template<>
void mapAndOpSrcToTgt (const AMIPatchToPatchInterpolation &AMI, const Field< tensor > &srcField, Field< tensor > &tgtField, const plusEqOp< tensor > &cop) const
template<>
void mapAndOpTgtToSrc (const AMIPatchToPatchInterpolation &AMI, Field< scalar > &srcField, const Field< scalar > &tgtField, const plusEqOp< scalar > &cop) const
template<>
void mapAndOpTgtToSrc (const AMIPatchToPatchInterpolation &AMI, Field< vector > &srcField, const Field< vector > &tgtField, const plusEqOp< vector > &cop) const
template<>
void mapAndOpTgtToSrc (const AMIPatchToPatchInterpolation &AMI, Field< sphericalTensor > &srcField, const Field< sphericalTensor > &tgtField, const plusEqOp< sphericalTensor > &cop) const
template<>
void mapAndOpTgtToSrc (const AMIPatchToPatchInterpolation &AMI, Field< symmTensor > &srcField, const Field< symmTensor > &tgtField, const plusEqOp< symmTensor > &cop) const
template<>
void mapAndOpTgtToSrc (const AMIPatchToPatchInterpolation &AMI, Field< tensor > &srcField, const Field< tensor > &tgtField, const plusEqOp< tensor > &cop) const
template<class Type , class CombineOp >
Foam::tmp< Foam::Field< Type > > mapSrcToTgt (const Field< Type > &srcField, const CombineOp &cop) const
template<class Type , class CombineOp >
Foam::tmp< Foam::Field< Type > > mapSrcToTgt (const tmp< Field< Type > > &tsrcField, const CombineOp &cop) const
template<class Type >
Foam::tmp< Foam::Field< Type > > mapSrcToTgt (const Field< Type > &srcField) const
template<class Type >
Foam::tmp< Foam::Field< Type > > mapSrcToTgt (const tmp< Field< Type > > &tsrcField) const
template<class Type , class CombineOp >
Foam::tmp< Foam::Field< Type > > mapTgtToSrc (const Field< Type > &tgtField, const CombineOp &cop) const
template<class Type , class CombineOp >
Foam::tmp< Foam::Field< Type > > mapTgtToSrc (const tmp< Field< Type > > &ttgtField, const CombineOp &cop) const
template<class Type >
Foam::tmp< Foam::Field< Type > > mapTgtToSrc (const Field< Type > &tgtField) const
template<class Type >
Foam::tmp< Foam::Field< Type > > mapTgtToSrc (const tmp< Field< Type > > &ttgtField) const
template<class Type , class CombineOp >
Foam::tmp< Foam::VolumeField< Type > > mapSrcToTgt (const VolumeField< Type > &field, const CombineOp &cop, const bool secondOrder) const
template<class Type , class CombineOp >
Foam::tmp< Foam::VolumeField< Type > > mapSrcToTgt (const tmp< VolumeField< Type > > &tfield, const CombineOp &cop, const bool secondOrder) const
template<class Type >
Foam::tmp< Foam::VolumeField< Type > > mapSrcToTgt (const VolumeField< Type > &field, const bool secondOrder) const
template<class Type >
Foam::tmp< Foam::VolumeField< Type > > mapSrcToTgt (const tmp< VolumeField< Type > > &tfield, const bool secondOrder) const
template<class Type , class CombineOp >
Foam::tmp< Foam::VolumeField< Type > > mapTgtToSrc (const VolumeField< Type > &field, const CombineOp &cop, const bool secondOrder) const
template<class Type , class CombineOp >
Foam::tmp< Foam::VolumeField< Type > > mapTgtToSrc (const tmp< VolumeField< Type > > &tfield, const CombineOp &cop, const bool secondOrder) const
template<class Type >
Foam::tmp< Foam::VolumeField< Type > > mapTgtToSrc (const VolumeField< Type > &field, const bool secondOrder) const
template<class Type >
Foam::tmp< Foam::VolumeField< Type > > mapTgtToSrc (const tmp< VolumeField< Type > > &tfield, const bool secondOrder) const
Static Public Member Functions
static word interpolationMethodAMI (const interpolationMethod method)
Static Public Attributes
static const Enum< interpolationMethod > interpolationMethodNames_
static const Enum< procMapMethod > procMapMethodNames_
Detailed Description
Class to calculate the cell-addressing between two overlapping meshes.
Mapping is performed using a run-time selectable interpolation mothod
See also
meshToMeshMethod
Source files
meshToMesh.H
meshToMesh.C
meshToMeshParallelOps.C
meshToMeshTemplates.C
Definition at line 60 of file meshToMesh.H.
Member Enumeration Documentation
interpolationMethod
enum class interpolationMethod strong
Enumerator
imDirect
imMapNearest
imCellVolumeWeight
imCorrectedCellVolumeWeight
Definition at line 67 of file meshToMesh.H.
procMapMethod
enum class procMapMethod strong
Enumerator
pmAABB
pmLOD
Definition at line 78 of file meshToMesh.H.
Constructor & Destructor Documentation
meshToMesh() [1/4]
meshToMesh (const polyMesh & src, const polyMesh & tgt, const interpolationMethod & method, const procMapMethod & mapMethod = procMapMethod::pmAABB, const bool interpAllPatches = true)
Definition at line 838 of file meshToMesh.C.
References meshToMesh::interpolationMethodAMI(), and meshToMesh::interpolationMethodNames_.
meshToMesh() [2/4]
meshToMesh (const polyMesh & src, const polyMesh & tgt, const word & methodName, const word & AMIMethodName, const procMapMethod & mapMethod = procMapMethod::pmAABB, const bool interpAllPatches = true)
Definition at line 874 of file meshToMesh.C.
meshToMesh() [3/4]
meshToMesh (const polyMesh & src, const polyMesh & tgt, const interpolationMethod & method, const HashTable< word > & patchMap, const wordList & cuttingPatches, const procMapMethod & mapMethod = procMapMethod::pmAABB, const bool normalise = true)
Definition at line 906 of file meshToMesh.C.
References meshToMesh::interpolationMethodAMI(), and meshToMesh::interpolationMethodNames_.
meshToMesh() [4/4]
meshToMesh (const polyMesh & src, const polyMesh & tgt, const word & methodName, const word & AMIMethodName, const HashTable< word > & patchMap, const wordList & cuttingPatches, const procMapMethod & mapMethod = procMapMethod::pmAABB, const bool normalise = true)
Definition at line 944 of file meshToMesh.C.
~meshToMesh()
~meshToMesh () virtual
Definition at line 985 of file meshToMesh.C.
Member Function Documentation
TypeName()
TypeName ("meshToMesh")
srcRegion()
const Foam::polyMesh & srcRegion () const inline
Definition at line 26 of file meshToMeshI.H.
tgtRegion()
const Foam::polyMesh & tgtRegion () const inline
Definition at line 32 of file meshToMeshI.H.
srcToTgtCellAddr()
const Foam::labelListList & srcToTgtCellAddr () const inline
Definition at line 38 of file meshToMeshI.H.
Referenced by cellVolumeWeight::update().
tgtToSrcCellAddr()
const Foam::labelListList & tgtToSrcCellAddr () const inline
Definition at line 44 of file meshToMeshI.H.
Referenced by cellVolumeWeight::update().
srcToTgtCellWght()
const Foam::scalarListList & srcToTgtCellWght () const inline
Definition at line 50 of file meshToMeshI.H.
Referenced by cellVolumeWeight::update().
tgtToSrcCellWght()
const Foam::scalarListList & tgtToSrcCellWght () const inline
Definition at line 56 of file meshToMeshI.H.
Referenced by cellVolumeWeight::update().
srcToTgtCellVec()
const Foam::pointListList & srcToTgtCellVec () const inline
Definition at line 62 of file meshToMeshI.H.
tgtToSrcCellVec()
const Foam::pointListList & tgtToSrcCellVec () const inline
Definition at line 68 of file meshToMeshI.H.
V()
Foam::scalar V () const inline
Definition at line 74 of file meshToMeshI.H.
interpolationMethodAMI()
Foam::word interpolationMethodAMI (const interpolationMethod method) static
Definition at line 638 of file meshToMesh.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Referenced by meshToMesh::meshToMesh(), and meshToMesh::meshToMesh().
patchAMIs()
const Foam::PtrList< Foam::AMIPatchToPatchInterpolation > & patchAMIs () const inline
Definition at line 95 of file meshToMeshI.H.
srcMap()
const Foam::autoPtr< Foam::mapDistribute > & srcMap () const inline
Definition at line 81 of file meshToMeshI.H.
Referenced by cellVolumeWeight::update().
tgtMap()
const Foam::autoPtr< Foam::mapDistribute > & tgtMap () const inline
Definition at line 88 of file meshToMeshI.H.
Referenced by cellVolumeWeight::update().
mapSrcToTgt() [1/19]
template<class Type , class CombineOp > void mapSrcToTgt (const UList< Type > & srcFld, const CombineOp & cop, List< Type > & result) const
Definition at line 46 of file meshToMeshTemplates.C.
References Foam::abort(), mapDistribute::distribute(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::nl, UPtrList< T >::size(), UList< T >::size(), and Foam::sum().
Referenced by meshToMesh::mapInternalSrcToTgt().
mapSrcToTgt() [2/19]
template<class Type , class CombineOp > void mapSrcToTgt (const UList< Type > & srcField, const UList< typename outerProduct< vector, Type >::type > & srcGradField, const CombineOp & cop, List< Type > & result) const
Definition at line 114 of file meshToMeshTemplates.C.
References Foam::abort(), mapDistribute::distribute(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::nl, Foam::returnReduceAnd(), UPtrList< T >::size(), UList< T >::size(), and Foam::sum().
mapSrcToTgt() [3/19]
template<class Type , class CombineOp > tmp< Field< Type > > mapSrcToTgt (const Field< Type > & srcFld, const CombineOp & cop) const
mapSrcToTgt() [4/19]
template<class Type , class CombineOp > tmp< Field< Type > > mapSrcToTgt (const tmp< Field< Type > > & tsrcFld, const CombineOp & cop) const
mapSrcToTgt() [5/19]
template<class Type > tmp< Field< Type > > mapSrcToTgt (const Field< Type > & srcFld) const
mapSrcToTgt() [6/19]
template<class Type > tmp< Field< Type > > mapSrcToTgt (const tmp< Field< Type > > & tsrcFld) const
mapTgtToSrc() [1/19]
template<class Type , class CombineOp > void mapTgtToSrc (const UList< Type > & tgtFld, const CombineOp & cop, List< Type > & result) const
Definition at line 261 of file meshToMeshTemplates.C.
References Foam::abort(), mapDistribute::distribute(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::nl, UPtrList< T >::size(), UList< T >::size(), and Foam::sum().
mapTgtToSrc() [2/19]
template<class Type , class CombineOp > void mapTgtToSrc (const UList< Type > & srcField, const UList< typename outerProduct< vector, Type >::type > & tgtGradField, const CombineOp & cop, List< Type > & result) const
Definition at line 327 of file meshToMeshTemplates.C.
References Foam::abort(), mapDistribute::distribute(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::nl, Foam::returnReduceAnd(), UPtrList< T >::size(), UList< T >::size(), and Foam::sum().
mapTgtToSrc() [3/19]
template<class Type , class CombineOp > tmp< Field< Type > > mapTgtToSrc (const Field< Type > & tgtFld, const CombineOp & cop) const
mapTgtToSrc() [4/19]
template<class Type , class CombineOp > tmp< Field< Type > > mapTgtToSrc (const tmp< Field< Type > > & ttgtFld, const CombineOp & cop) const
mapTgtToSrc() [5/19]
template<class Type > tmp< Field< Type > > mapTgtToSrc (const Field< Type > & tgtFld) const
mapTgtToSrc() [6/19]
template<class Type > tmp< Field< Type > > mapTgtToSrc (const tmp< Field< Type > > & ttgtFld) const
mapSrcToTgt() [7/19]
template<class Type , class CombineOp > void mapSrcToTgt (const VolumeField< Type > & field, const CombineOp & cop, VolumeField< Type > & result, const bool secondOrder = true) const
Definition at line 513 of file meshToMeshTemplates.C.
References field(), forAll, Foam::identity(), and UPtrList< T >::size().
mapSrcToTgt() [8/19]
template<class Type , class CombineOp > tmp< VolumeField< Type > > mapSrcToTgt (const VolumeField< Type > & field, const CombineOp & cop, const bool secondOrder = true) const
mapSrcToTgt() [9/19]
template<class Type , class CombineOp > tmp< VolumeField< Type > > mapSrcToTgt (const tmp< VolumeField< Type > > & tfield, const CombineOp & cop, const bool secondOrder = true) const
mapSrcToTgt() [10/19]
template<class Type > tmp< VolumeField< Type > > mapSrcToTgt (const VolumeField< Type > & field, const bool secondOrder = true) const
mapSrcToTgt() [11/19]
template<class Type > tmp< VolumeField< Type > > mapSrcToTgt (const tmp< VolumeField< Type > > & tfield, const bool secondOrder = true) const
mapTgtToSrc() [7/19]
template<class Type , class CombineOp > void mapTgtToSrc (const VolumeField< Type > & field, const CombineOp & cop, VolumeField< Type > & result, const bool secondOrder = true) const
Definition at line 746 of file meshToMeshTemplates.C.
References field(), forAll, Foam::identity(), and UPtrList< T >::size().
mapTgtToSrc() [8/19]
template<class Type , class CombineOp > tmp< VolumeField< Type > > mapTgtToSrc (const VolumeField< Type > & field, const CombineOp & cop, const bool secondOrder = true) const
mapTgtToSrc() [9/19]
template<class Type , class CombineOp > tmp< VolumeField< Type > > mapTgtToSrc (const tmp< VolumeField< Type > > & tfield, const CombineOp & cop, const bool secondOrder = true) const
mapTgtToSrc() [10/19]
template<class Type > tmp< VolumeField< Type > > mapTgtToSrc (const VolumeField< Type > & field, const bool secondOrder = true) const
mapTgtToSrc() [11/19]
template<class Type > tmp< VolumeField< Type > > mapTgtToSrc (const tmp< VolumeField< Type > > & tfield, const bool secondOrder = true) const
mapInternalSrcToTgt() [1/12]
template<> void mapInternalSrcToTgt (const VolumeField< sphericalTensor > & field, const plusEqOp< sphericalTensor > & cop, VolumeField< sphericalTensor > & result, const bool secondOrder) const
Definition at line 68 of file meshToMesh.C.
References field(), and meshToMesh::mapSrcToTgt().
mapInternalSrcToTgt() [2/12]
template<> void mapInternalSrcToTgt (const VolumeField< sphericalTensor > & field, const minusEqOp< sphericalTensor > & cop, VolumeField< sphericalTensor > & result, const bool secondOrder) const
Definition at line 81 of file meshToMesh.C.
References field().
mapInternalSrcToTgt() [3/12]
template<> void mapInternalSrcToTgt (const VolumeField< symmTensor > & field, const plusEqOp< symmTensor > & cop, VolumeField< symmTensor > & result, const bool secondOrder) const
Definition at line 94 of file meshToMesh.C.
References field().
mapInternalSrcToTgt() [4/12]
template<> void mapInternalSrcToTgt (const VolumeField< symmTensor > & field, const minusEqOp< symmTensor > & cop, VolumeField< symmTensor > & result, const bool secondOrder) const
Definition at line 107 of file meshToMesh.C.
References field().
mapInternalSrcToTgt() [5/12]
template<> void mapInternalSrcToTgt (const VolumeField< tensor > & field, const plusEqOp< tensor > & cop, VolumeField< tensor > & result, const bool secondOrder) const
Definition at line 120 of file meshToMesh.C.
References field().
mapInternalSrcToTgt() [6/12]
template<> void mapInternalSrcToTgt (const VolumeField< tensor > & field, const minusEqOp< tensor > & cop, VolumeField< tensor > & result, const bool secondOrder) const
Definition at line 133 of file meshToMesh.C.
References field().
mapInternalTgtToSrc() [1/12]
template<> void mapInternalTgtToSrc (const VolumeField< sphericalTensor > & field, const plusEqOp< sphericalTensor > & cop, VolumeField< sphericalTensor > & result, const bool secondOrder) const
Definition at line 146 of file meshToMesh.C.
References field().
mapInternalTgtToSrc() [2/12]
template<> void mapInternalTgtToSrc (const VolumeField< sphericalTensor > & field, const minusEqOp< sphericalTensor > & cop, VolumeField< sphericalTensor > & result, const bool secondOrder) const
Definition at line 159 of file meshToMesh.C.
References field().
mapInternalTgtToSrc() [3/12]
template<> void mapInternalTgtToSrc (const VolumeField< symmTensor > & field, const plusEqOp< symmTensor > & cop, VolumeField< symmTensor > & result, const bool secondOrder) const
Definition at line 172 of file meshToMesh.C.
References field().
mapInternalTgtToSrc() [4/12]
template<> void mapInternalTgtToSrc (const VolumeField< symmTensor > & field, const minusEqOp< symmTensor > & cop, VolumeField< symmTensor > & result, const bool secondOrder) const
Definition at line 185 of file meshToMesh.C.
References field().
mapInternalTgtToSrc() [5/12]
template<> void mapInternalTgtToSrc (const VolumeField< tensor > & field, const plusEqOp< tensor > & cop, VolumeField< tensor > & result, const bool secondOrder) const
Definition at line 198 of file meshToMesh.C.
References field().
mapInternalTgtToSrc() [6/12]
template<> void mapInternalTgtToSrc (const VolumeField< tensor > & field, const minusEqOp< tensor > & cop, VolumeField< tensor > & result, const bool secondOrder) const
Definition at line 211 of file meshToMesh.C.
References field().
mapAndOpSrcToTgt() [1/10]
template<> void mapAndOpSrcToTgt (const AMIPatchToPatchInterpolation & AMI, const Field< scalar > & srcField, Field< scalar > & tgtField, const plusEqOp< scalar > & cop) const
Definition at line 224 of file meshToMesh.C.
mapAndOpSrcToTgt() [2/10]
template<> void mapAndOpSrcToTgt (const AMIPatchToPatchInterpolation & AMI, const Field< vector > & srcField, Field< vector > & tgtField, const plusEqOp< vector > & cop) const
Definition at line 235 of file meshToMesh.C.
mapAndOpSrcToTgt() [3/10]
template<> void mapAndOpSrcToTgt (const AMIPatchToPatchInterpolation & AMI, const Field< sphericalTensor > & srcField, Field< sphericalTensor > & tgtField, const plusEqOp< sphericalTensor > & cop) const
Definition at line 246 of file meshToMesh.C.
mapAndOpSrcToTgt() [4/10]
template<> void mapAndOpSrcToTgt (const AMIPatchToPatchInterpolation & AMI, const Field< symmTensor > & srcField, Field< symmTensor > & tgtField, const plusEqOp< symmTensor > & cop) const
Definition at line 257 of file meshToMesh.C.
mapAndOpSrcToTgt() [5/10]
template<> void mapAndOpSrcToTgt (const AMIPatchToPatchInterpolation & AMI, const Field< tensor > & srcField, Field< tensor > & tgtField, const plusEqOp< tensor > & cop) const
Definition at line 268 of file meshToMesh.C.
mapAndOpTgtToSrc() [1/10]
template<> void mapAndOpTgtToSrc (const AMIPatchToPatchInterpolation & AMI, Field< scalar > & srcField, const Field< scalar > & tgtField, const plusEqOp< scalar > & cop) const
Definition at line 279 of file meshToMesh.C.
mapAndOpTgtToSrc() [2/10]
template<> void mapAndOpTgtToSrc (const AMIPatchToPatchInterpolation & AMI, Field< vector > & srcField, const Field< vector > & tgtField, const plusEqOp< vector > & cop) const
Definition at line 290 of file meshToMesh.C.
mapAndOpTgtToSrc() [3/10]
template<> void mapAndOpTgtToSrc (const AMIPatchToPatchInterpolation & AMI, Field< sphericalTensor > & srcField, const Field< sphericalTensor > & tgtField, const plusEqOp< sphericalTensor > & cop) const
Definition at line 301 of file meshToMesh.C.
mapAndOpTgtToSrc() [4/10]
template<> void mapAndOpTgtToSrc (const AMIPatchToPatchInterpolation & AMI, Field< symmTensor > & srcField, const Field< symmTensor > & tgtField, const plusEqOp< symmTensor > & cop) const
Definition at line 312 of file meshToMesh.C.
mapAndOpTgtToSrc() [5/10]
template<> void mapAndOpTgtToSrc (const AMIPatchToPatchInterpolation & AMI, Field< tensor > & srcField, const Field< tensor > & tgtField, const plusEqOp< tensor > & cop) const
Definition at line 323 of file meshToMesh.C.
mapInternalSrcToTgt() [7/12]
template<> void mapInternalSrcToTgt (const VolumeField< sphericalTensor > & , const plusEqOp< sphericalTensor > & , VolumeField< sphericalTensor > & , const bool) const
mapInternalSrcToTgt() [8/12]
template<> void mapInternalSrcToTgt (const VolumeField< sphericalTensor > & , const minusEqOp< sphericalTensor > & , VolumeField< sphericalTensor > & , const bool) const
mapInternalSrcToTgt() [9/12]
template<> void mapInternalSrcToTgt (const VolumeField< symmTensor > & , const plusEqOp< symmTensor > & , VolumeField< symmTensor > & , const bool) const
mapInternalSrcToTgt() [10/12]
template<> void mapInternalSrcToTgt (const VolumeField< symmTensor > & , const minusEqOp< symmTensor > & , VolumeField< symmTensor > & , const bool) const
mapInternalSrcToTgt() [11/12]
template<> void mapInternalSrcToTgt (const VolumeField< tensor > & , const plusEqOp< tensor > & , VolumeField< tensor > & , const bool) const
mapInternalSrcToTgt() [12/12]
template<> void mapInternalSrcToTgt (const VolumeField< tensor > & , const minusEqOp< tensor > & , VolumeField< tensor > & , const bool) const
mapInternalTgtToSrc() [7/12]
template<> void mapInternalTgtToSrc (const VolumeField< sphericalTensor > & , const plusEqOp< sphericalTensor > & , VolumeField< sphericalTensor > & , const bool) const
mapInternalTgtToSrc() [8/12]
template<> void mapInternalTgtToSrc (const VolumeField< sphericalTensor > & , const minusEqOp< sphericalTensor > & , VolumeField< sphericalTensor > & , const bool) const
mapInternalTgtToSrc() [9/12]
template<> void mapInternalTgtToSrc (const VolumeField< symmTensor > & , const plusEqOp< symmTensor > & , VolumeField< symmTensor > & , const bool) const
mapInternalTgtToSrc() [10/12]
template<> void mapInternalTgtToSrc (const VolumeField< symmTensor > & , const minusEqOp< symmTensor > & , VolumeField< symmTensor > & , const bool) const
mapInternalTgtToSrc() [11/12]
template<> void mapInternalTgtToSrc (const VolumeField< tensor > & , const plusEqOp< tensor > & , VolumeField< tensor > & , const bool) const
mapInternalTgtToSrc() [12/12]
template<> void mapInternalTgtToSrc (const VolumeField< tensor > & , const minusEqOp< tensor > & , VolumeField< tensor > & , const bool) const
mapAndOpSrcToTgt() [6/10]
template<> void mapAndOpSrcToTgt (const AMIPatchToPatchInterpolation & AMI, const Field< scalar > & srcField, Field< scalar > & tgtField, const plusEqOp< scalar > & cop) const
mapAndOpSrcToTgt() [7/10]
template<> void mapAndOpSrcToTgt (const AMIPatchToPatchInterpolation & AMI, const Field< vector > & srcField, Field< vector > & tgtField, const plusEqOp< vector > & cop) const
mapAndOpSrcToTgt() [8/10]
template<> void mapAndOpSrcToTgt (const AMIPatchToPatchInterpolation & AMI, const Field< sphericalTensor > & srcField, Field< sphericalTensor > & tgtField, const plusEqOp< sphericalTensor > & cop) const
mapAndOpSrcToTgt() [9/10]
template<> void mapAndOpSrcToTgt (const AMIPatchToPatchInterpolation & AMI, const Field< symmTensor > & srcField, Field< symmTensor > & tgtField, const plusEqOp< symmTensor > & cop) const
mapAndOpSrcToTgt() [10/10]
template<> void mapAndOpSrcToTgt (const AMIPatchToPatchInterpolation & AMI, const Field< tensor > & srcField, Field< tensor > & tgtField, const plusEqOp< tensor > & cop) const
mapAndOpTgtToSrc() [6/10]
template<> void mapAndOpTgtToSrc (const AMIPatchToPatchInterpolation & AMI, Field< scalar > & srcField, const Field< scalar > & tgtField, const plusEqOp< scalar > & cop) const
mapAndOpTgtToSrc() [7/10]
template<> void mapAndOpTgtToSrc (const AMIPatchToPatchInterpolation & AMI, Field< vector > & srcField, const Field< vector > & tgtField, const plusEqOp< vector > & cop) const
mapAndOpTgtToSrc() [8/10]
template<> void mapAndOpTgtToSrc (const AMIPatchToPatchInterpolation & AMI, Field< sphericalTensor > & srcField, const Field< sphericalTensor > & tgtField, const plusEqOp< sphericalTensor > & cop) const
mapAndOpTgtToSrc() [9/10]
template<> void mapAndOpTgtToSrc (const AMIPatchToPatchInterpolation & AMI, Field< symmTensor > & srcField, const Field< symmTensor > & tgtField, const plusEqOp< symmTensor > & cop) const
mapAndOpTgtToSrc() [10/10]
template<> void mapAndOpTgtToSrc (const AMIPatchToPatchInterpolation & AMI, Field< tensor > & srcField, const Field< tensor > & tgtField, const plusEqOp< tensor > & cop) const
mapSrcToTgt() [12/19]
template<class Type , class CombineOp > Foam::tmp< Foam::Field< Type > > mapSrcToTgt (const Field< Type > & srcField, const CombineOp & cop) const
Definition at line 208 of file meshToMeshTemplates.C.
References Foam::Zero.
mapSrcToTgt() [13/19]
template<class Type , class CombineOp > Foam::tmp< Foam::Field< Type > > mapSrcToTgt (const tmp< Field< Type > > & tsrcField, const CombineOp & cop) const
Definition at line 230 of file meshToMeshTemplates.C.
mapSrcToTgt() [14/19]
template<class Type > Foam::tmp< Foam::Field< Type > > mapSrcToTgt (const Field< Type > & srcField) const
Definition at line 241 of file meshToMeshTemplates.C.
mapSrcToTgt() [15/19]
template<class Type > Foam::tmp< Foam::Field< Type > > mapSrcToTgt (const tmp< Field< Type > > & tsrcField) const
Definition at line 251 of file meshToMeshTemplates.C.
mapTgtToSrc() [12/19]
template<class Type , class CombineOp > Foam::tmp< Foam::Field< Type > > mapTgtToSrc (const Field< Type > & tgtField, const CombineOp & cop) const
Definition at line 413 of file meshToMeshTemplates.C.
References Foam::Zero.
mapTgtToSrc() [13/19]
template<class Type , class CombineOp > Foam::tmp< Foam::Field< Type > > mapTgtToSrc (const tmp< Field< Type > > & ttgtField, const CombineOp & cop) const
Definition at line 435 of file meshToMeshTemplates.C.
mapTgtToSrc() [14/19]
template<class Type > Foam::tmp< Foam::Field< Type > > mapTgtToSrc (const Field< Type > & tgtField) const
Definition at line 446 of file meshToMeshTemplates.C.
mapTgtToSrc() [15/19]
template<class Type > Foam::tmp< Foam::Field< Type > > mapTgtToSrc (const tmp< Field< Type > > & ttgtField) const
Definition at line 456 of file meshToMeshTemplates.C.
mapSrcToTgt() [16/19]
template<class Type , class CombineOp > Foam::tmp< Foam::VolumeField< Type > > mapSrcToTgt (const VolumeField< Type > & field, const CombineOp & cop, const bool secondOrder) const
Definition at line 577 of file meshToMeshTemplates.C.
References fvPatchFieldBase::calculatedType(), field(), forAll, Foam::New(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, PtrList< T >::set(), UPtrList< T >::size(), Foam::type(), and Foam::Zero.
mapSrcToTgt() [17/19]
template<class Type , class CombineOp > Foam::tmp< Foam::VolumeField< Type > > mapSrcToTgt (const tmp< VolumeField< Type > > & tfield, const CombineOp & cop, const bool secondOrder) const
Definition at line 663 of file meshToMeshTemplates.C.
mapSrcToTgt() [18/19]
template<class Type > Foam::tmp< Foam::VolumeField< Type > > mapSrcToTgt (const VolumeField< Type > & field, const bool secondOrder) const
Definition at line 676 of file meshToMeshTemplates.C.
References field().
mapSrcToTgt() [19/19]
template<class Type > Foam::tmp< Foam::VolumeField< Type > > mapSrcToTgt (const tmp< VolumeField< Type > > & tfield, const bool secondOrder) const
Definition at line 688 of file meshToMeshTemplates.C.
mapTgtToSrc() [16/19]
template<class Type , class CombineOp > Foam::tmp< Foam::VolumeField< Type > > mapTgtToSrc (const VolumeField< Type > & field, const CombineOp & cop, const bool secondOrder) const
Definition at line 808 of file meshToMeshTemplates.C.
References fvPatchFieldBase::calculatedType(), field(), forAll, Foam::New(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, PtrList< T >::set(), UPtrList< T >::size(), Foam::type(), and Foam::Zero.
mapTgtToSrc() [17/19]
template<class Type , class CombineOp > Foam::tmp< Foam::VolumeField< Type > > mapTgtToSrc (const tmp< VolumeField< Type > > & tfield, const CombineOp & cop, const bool secondOrder) const
Definition at line 894 of file meshToMeshTemplates.C.
mapTgtToSrc() [18/19]
template<class Type > Foam::tmp< Foam::VolumeField< Type > > mapTgtToSrc (const VolumeField< Type > & field, const bool secondOrder) const
Definition at line 907 of file meshToMeshTemplates.C.
References field().
mapTgtToSrc() [19/19]
template<class Type > Foam::tmp< Foam::VolumeField< Type > > mapTgtToSrc (const tmp< VolumeField< Type > > & tfield, const bool secondOrder) const
Definition at line 919 of file meshToMeshTemplates.C.
Member Data Documentation
interpolationMethodNames_
const Foam::Enum< Foam::meshToMesh::interpolationMethod > interpolationMethodNames_ static
Definition at line 75 of file meshToMesh.H.
Referenced by meshToMesh::meshToMesh(), meshToMesh::meshToMesh(), and interRegionOption::setMapper().
procMapMethodNames_
const Foam::Enum< Foam::meshToMesh::procMapMethod > procMapMethodNames_ static
Initial value:
{
    { procMapMethod::pmAABB, "AABB" },
    { procMapMethod::pmLOD, "LOD" },
}
Definition at line 58 of file meshToMesh.H.
Referenced by interRegionOption::setMapper().
The documentation for this class was generated from the following files:
src/sampling/meshToMesh/meshToMesh.H
src/sampling/meshToMesh/meshToMesh.C
src/sampling/meshToMesh/meshToMeshI.H
src/sampling/meshToMesh/meshToMeshParallelOps.C
src/sampling/meshToMesh/meshToMeshTemplates.C