OpenFOAM: faePatchFieldBase Class Reference
faePatchFieldBase Class Reference
#include <faePatchField.H>
Public Member Functions
TypeName ("faePatchField")
faePatchFieldBase (const faPatch &p)
faePatchFieldBase (const faPatch &p, const word &patchType)
faePatchFieldBase (const faPatch &p, const dictionary &dict)
faePatchFieldBase (const faePatchFieldBase &rhs, const faPatch &p)
faePatchFieldBase (const faePatchFieldBase &rhs)
virtual ~faePatchFieldBase ()=default
virtual bool fixesValue () const
virtual bool coupled () const
const objectRegistry & db () const
const faPatch & patch () const noexcept
bool updated () const noexcept
bool manipulatedMatrix () const noexcept
void checkPatch (const faePatchFieldBase &rhs) const
Static Public Member Functions
static const word & emptyType () noexcept
static const word & calculatedType () noexcept
Static Public Attributes
static int disallowGenericPatchField
Protected Member Functions
virtual void readDict (const dictionary &dict)
void setUpdated (bool state) noexcept
void setManipulated (bool state) noexcept
Detailed Description
Definition at line 76 of file faePatchField.H.
Constructor & Destructor Documentation
faePatchFieldBase() [1/5]
faePatchFieldBase (const faPatch & p) explicit
Definition at line 41 of file faePatchFieldBase.C.
faePatchFieldBase() [2/5]
faePatchFieldBase (const faPatch & p, const word & patchType) explicit
Definition at line 47 of file faePatchFieldBase.C.
faePatchFieldBase() [3/5]
faePatchFieldBase (const faPatch & p, const dictionary & dict)
Definition at line 57 of file faePatchFieldBase.C.
References dict, and faePatchFieldBase::readDict().
faePatchFieldBase() [4/5]
faePatchFieldBase (const faePatchFieldBase & rhs, const faPatch & p)
Definition at line 69 of file faePatchFieldBase.C.
faePatchFieldBase() [5/5]
faePatchFieldBase (const faePatchFieldBase & rhs)
Definition at line 79 of file faePatchFieldBase.C.
~faePatchFieldBase()
virtual ~faePatchFieldBase () virtual default
Member Function Documentation
readDict()
void readDict (const dictionary & dict) protected virtual
Definition at line 87 of file faePatchFieldBase.C.
Referenced by faePatchFieldBase::faePatchFieldBase(), and slicedFaePatchField< Type >::slicedFaePatchField().
setUpdated()
void setUpdated (bool state) inline protected noexcept
Definition at line 92 of file faePatchField.H.
setManipulated()
void setManipulated (bool state) inline protected noexcept
Definition at line 96 of file faePatchField.H.
TypeName()
TypeName ("faePatchField")
emptyType()
static const word & emptyType () inline static noexcept
Definition at line 134 of file faePatchField.H.
References Foam::fieldTypes::emptyType.
calculatedType()
static const word & calculatedType () inline static noexcept
Definition at line 140 of file faePatchField.H.
References Foam::fieldTypes::calculatedType.
Referenced by faMeshSubset::interpolate().
fixesValue()
virtual bool fixesValue () const inline virtual
Reimplemented in calculatedFaePatchField< Type >, fixedValueFaePatchField< Type >, and slicedFaePatchField< Type >.
Definition at line 153 of file faePatchField.H.
coupled()
virtual bool coupled () const inline virtual
Reimplemented in coupledFaePatchField< Type >, and processorFaePatchField< Type >.
Definition at line 159 of file faePatchField.H.
db()
const Foam::objectRegistry & db () const
Definition at line 91 of file faePatchFieldBase.C.
patch()
const faPatch & patch () const inline noexcept
Definition at line 171 of file faePatchField.H.
Referenced by cyclicFaePatchField< Type >::cyclicFaePatchField(), cyclicFaePatchField< Type >::cyclicFaePatchField(), emptyFaePatchField< Type >::emptyFaePatchField(), emptyFaePatchField< Type >::emptyFaePatchField(), genericFaePatchField< Type >::genericFaePatchField(), genericFaePatchField< Type >::genericFaePatchField(), processorFaePatchField< Type >::processorFaePatchField(), processorFaePatchField< Type >::processorFaePatchField(), faePatchField< Type >::readValueEntry(), symmetryFaePatchField< Type >::symmetryFaePatchField(), symmetryFaePatchField< Type >::symmetryFaePatchField(), wedgeFaePatchField< Type >::wedgeFaePatchField(), and wedgeFaePatchField< Type >::wedgeFaePatchField().
updated()
bool updated () const inline noexcept
Definition at line 181 of file faePatchField.H.
manipulatedMatrix()
bool manipulatedMatrix () const inline noexcept
Definition at line 188 of file faePatchField.H.
checkPatch()
void checkPatch (const faePatchFieldBase & rhs) const
Definition at line 97 of file faePatchFieldBase.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Referenced by faePatchField< Type >::check(), faePatchField< Type >::operator*=(), faePatchField< Type >::operator+=(), faePatchField< Type >::operator-=(), faePatchField< Type >::operator/=(), and faePatchField< Type >::operator=().
Member Data Documentation
disallowGenericPatchField
int disallowGenericPatchField static
Definition at line 103 of file faePatchField.H.
Referenced by faePatchField< Type >::New().
The documentation for this class was generated from the following files:
src/finiteArea/fields/faePatchFields/faePatchField/faePatchField.H
src/finiteArea/fields/faePatchFields/faePatchField/faePatchFieldBase.C