OpenFOAM: kL< BasicTurbulenceModel > Class Template Reference
kL< BasicTurbulenceModel > Class Template Reference
Turbulence models » RAS turbulence
A one-equation (turbulent kinetic energy k) turbulence closure model for incompressible and compressible geophysical applications.
#include <kL.H>
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from linearViscousStress< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("kL")
kL (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
virtual ~kL ()=default
virtual bool read ()
tmp< volScalarField > DkEff () const
virtual tmp< volScalarField > k () const
virtual void correct ()
Public Member Functions inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
eddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~eddyViscosity ()=default
virtual tmp< volScalarField > nut () const
virtual tmp< scalarField > nut (const label patchi) const
virtual tmp< volSymmTensorField > R () const
virtual void validate ()
Public Member Functions inherited from linearViscousStress< BasicTurbulenceModel >
linearViscousStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~linearViscousStress ()=default
virtual tmp< volSymmTensorField > devRhoReff () const
virtual tmp< volSymmTensorField > devRhoReff (const volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Protected Member Functions
virtual void correctNut ()
virtual tmp< fvScalarMatrix > kSource () const
Protected Attributes
dimensionedScalar kappa_
dimensionedScalar sigmak_
dimensionedScalar beta_
dimensionedScalar Cmu0_
dimensionedScalar Lmax_
dimensionedScalar CbStable_
dimensionedScalar CbUnstable_
volScalarField k_
volScalarField L_
volScalarField Rt_
const uniformDimensionedVectorField & g_
const volScalarField & y_
Protected Attributes inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
volScalarField nut_
Detailed Description
template<class BasicTurbulenceModel>
class Foam::RASModels::kL< BasicTurbulenceModel >
A one-equation (turbulent kinetic energy k) turbulence closure model for incompressible and compressible geophysical applications.
Turbulent kinetic energy (k) is computed with a transport equation and the turbulent length scale (L) is computed with an algebraic expression which depends on the local stratification.
References:
    Standard model (tag:A):
        Axell, L. B., & Liungman, O. (2001).
        A one-equation turbulence model for geophysical applications:
        comparison with data and the k−ε model.
        Environmental Fluid Mechanics, 1(1), 71-106.
        DOI:10.1023/A:1011560202388
    Canopy-related models (tag:W):
        Wilson, J. D., & Flesch, T. K. (1999).
        Wind and remnant tree sway in forest cutblocks.
        III. A windflow model to diagnose spatial variation.
        Agricultural and Forest Meteorology, 93(4), 259-282.
        DOI:10.1016/S0168-1923(98)00121-X
Usage
Example by using constant/turbulenceProperties:
RAS
{
    // Mandatory entries
    RASModel        kL;
    // Optional entries
    kLCoeffs
    {
        kappa       <scalar>;
        sigmak      <scalar>;
        beta        <scalar>;
        Cmu0        <scalar>;
        Lmax        <scalar>;
        CbStable    <scalar>;
        CbUnstable  <scalar>;
    }
    // Inherited entries
    ...
}
where the entries mean:
Property Description Type Reqd Deflt
RASModel Type name: kL word yes -
kappa von Karman constant scalar no 0.41
sigmak Empirical model coefficient scalar no 1.0
beta Thermal expansion coefficient [1/K] scalar no 3.3e-3
Cmu0 Empirical model coefficient scalar no 0.556
Lmax Maximum mixing-length scale [m] scalar no GREAT
CbStable Stable stratification constant scalar no 0.25
CbUnstable Unstable stratification constant scalar no 0.35
The inherited entries are elaborated in:
eddyViscosity.H
Input fields (mandatory)
k : Turbulent kinetic energy [m2/s2]
T : Potential temperature [K]
Input fields (optional)
canopyHeight : Canopy height [m]
Cd : Plant canopy drag coefficient [-]
LAD : Leaf area density [1/m]
Rt : Turbulent Richardson number [-]
L : Characteristic length scale [m]
Note
Optional input fields can/should be input by using readFields function object.
Source files
kL.H
kL.C
Definition at line 218 of file kL.H.
Member Typedef Documentation
alphaField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 320 of file kL.H.
rhoField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 321 of file kL.H.
transportModel
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 322 of file kL.H.
Constructor & Destructor Documentation
kL()
template<class BasicTurbulenceModel > kL (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Definition at line 240 of file kL.C.
References Foam::bound(), kL< BasicTurbulenceModel >::k_, and Foam::type().
~kL()
template<class BasicTurbulenceModel > virtual ~kL () virtual default
Member Function Documentation
correctNut()
template<class BasicTurbulenceModel > void correctNut () protected virtual
Implements eddyViscosity< RASModel< BasicTurbulenceModel > >.
Definition at line 216 of file kL.C.
References options::New(), and Foam::sqrt().
kSource()
template<class BasicTurbulenceModel > tmp< fvScalarMatrix > kSource () const protected virtual
Definition at line 227 of file kL.C.
References Foam::dimTime, Foam::dimVolume, and tmp< T >::New().
TypeName()
template<class BasicTurbulenceModel > TypeName ("kL< BasicTurbulenceModel >")
read()
template<class BasicTurbulenceModel > bool read () virtual
Implements eddyViscosity< RASModel< BasicTurbulenceModel > >.
Definition at line 383 of file kL.C.
References Foam::read().
DkEff()
template<class BasicTurbulenceModel > tmp< volScalarField > DkEff () const inline
Definition at line 355 of file kL.H.
References tmp< T >::New(), nu, and eddyViscosity< RASModel< BasicTurbulenceModel > >::nut_.
k()
template<class BasicTurbulenceModel > virtual tmp< volScalarField > k () const inline virtual
Implements eddyViscosity< RASModel< BasicTurbulenceModel > >.
Definition at line 365 of file kL.H.
References kL< BasicTurbulenceModel >::k_.
correct()
template<class BasicTurbulenceModel > void correct () virtual
Implements eddyViscosity< RASModel< BasicTurbulenceModel > >.
Definition at line 403 of file kL.C.
References Foam::fvc::absolute(), alpha, Foam::bound(), PtrList< T >::clear(), correct(), Foam::fvm::ddt(), Foam::devSymm(), Foam::fvc::div(), Foam::fvm::div(), divU, epsilon, fvOptions, Foam::fvc::grad(), Foam::fvm::laplacian(), Foam::magSqr(), options::New(), nut, phi, rho, solve(), Foam::sqr(), Foam::fvm::SuSp(), T, and U.
Member Data Documentation
kappa_
template<class BasicTurbulenceModel > dimensionedScalar kappa_ protected
Definition at line 268 of file kL.H.
sigmak_
template<class BasicTurbulenceModel > dimensionedScalar sigmak_ protected
Definition at line 271 of file kL.H.
beta_
template<class BasicTurbulenceModel > dimensionedScalar beta_ protected
Definition at line 274 of file kL.H.
Cmu0_
template<class BasicTurbulenceModel > dimensionedScalar Cmu0_ protected
Definition at line 277 of file kL.H.
Lmax_
template<class BasicTurbulenceModel > dimensionedScalar Lmax_ protected
Definition at line 280 of file kL.H.
CbStable_
template<class BasicTurbulenceModel > dimensionedScalar CbStable_ protected
Definition at line 283 of file kL.H.
CbUnstable_
template<class BasicTurbulenceModel > dimensionedScalar CbUnstable_ protected
Definition at line 286 of file kL.H.
k_
template<class BasicTurbulenceModel > volScalarField k_ protected
Definition at line 292 of file kL.H.
Referenced by kL< BasicTurbulenceModel >::k(), and kL< BasicTurbulenceModel >::kL().
L_
template<class BasicTurbulenceModel > volScalarField L_ protected
Definition at line 295 of file kL.H.
Rt_
template<class BasicTurbulenceModel > volScalarField Rt_ protected
Definition at line 298 of file kL.H.
g_
template<class BasicTurbulenceModel > const uniformDimensionedVectorField& g_ protected
Definition at line 301 of file kL.H.
y_
template<class BasicTurbulenceModel > const volScalarField& y_ protected
Definition at line 306 of file kL.H.
The documentation for this class was generated from the following files:
src/atmosphericModels/turbulenceModels/RAS/kL/kL.H
src/atmosphericModels/turbulenceModels/RAS/kL/kL.C