OpenFOAM: fieldExpression Class Reference
fieldExpression Class Reference abstract
FunctionObjects » Field function objects
Intermediate class for handling field expression function objects (e.g. blendingFactor etc.) whereinto a single field is input.
#include <fieldExpression.H>
Public Member Functions
TypeName ("fieldExpression")
fieldExpression (const word &name, const Time &runTime, const dictionary &dict, const word &fieldName=word::null, const word &resultName=word::null)
fieldExpression (const fieldExpression &)=delete
void operator= (const fieldExpression &)=delete
virtual ~fieldExpression ()=default
virtual bool read (const dictionary &dict)
virtual bool execute ()
virtual bool write ()
virtual bool clear ()
Public Member Functions inherited from fvMeshFunctionObject
TypeName ("fvMeshFunctionObject")
fvMeshFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
fvMeshFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
virtual ~fvMeshFunctionObject ()=default
Public Member Functions inherited from regionFunctionObject
TypeName ("regionFunctionObject")
regionFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
regionFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
virtual ~regionFunctionObject ()=default
template<class ObjectType >
const ObjectType * lookupObjectPtr (const word &fieldName) const
template<class ObjectType >
ObjectType * lookupObjectRefPtr (const word &fieldName) const
Public Member Functions inherited from stateFunctionObject
stateFunctionObject (const word &name, const Time &runTime)
virtual ~stateFunctionObject ()=default
dictionary & propertyDict ()
bool foundProperty (const word &entryName) const
void clearTrigger ()
label getTrigger () const
bool setTrigger (const label triggeri)
bool getDict (const word &entryName, dictionary &dict) const
bool getObjectDict (const word &objectName, const word &entryName, dictionary &dict) const
template<class Type >
Type getProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getProperty (const word &entryName, Type &value) const
template<class Type >
void setProperty (const word &entryName, const Type &value)
template<class Type >
Type getObjectProperty (const word &objectName, const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getObjectProperty (const word &objectName, const word &entryName, Type &value) const
template<class Type >
void setObjectProperty (const word &objectName, const word &entryName, const Type &value)
template<class Type >
void setResult (const word &entryName, const Type &value)
template<class Type >
void setObjectResult (const word &objectName, const word &entryName, const Type &value)
template<class Type >
Type getResult (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
Type getObjectResult (const word &objectName, const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getObjectResult (const word &objectName, const word &entryName, Type &value) const
word resultType (const word &entryName) const
word objectResultType (const word &objectName, const word &entryName) const
wordList objectResultEntries () const
wordList objectResultEntries (const word &objectName) const
void writeResultEntries (Ostream &os) const
void writeResultEntries (const word &objectName, Ostream &os) const
void writeAllResultEntries (Ostream &os) const
Public Member Functions inherited from timeFunctionObject
timeFunctionObject (const word &name, const Time &runTime)
virtual ~timeFunctionObject ()=default
const Time & time () const
objectRegistry & storedObjects ()
const objectRegistry & storedObjects () const
Public Member Functions inherited from functionObject
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name, const bool withNamePrefix=defaultUseNamePrefix)
autoPtr< functionObject > clone () const
virtual ~functionObject ()=default
virtual const word & type () const =0
const word & name () const noexcept
bool useNamePrefix () const noexcept
bool useNamePrefix (bool on) noexcept
virtual bool execute (const label subIndex)
virtual bool end ()
virtual bool adjustTimeStep ()
virtual bool filesModified () const
virtual void updateMesh (const mapPolyMesh &mpm)
virtual void movePoints (const polyMesh &mesh)
Protected Member Functions
virtual bool calc ()=0
void setResultName (const word &typeName, const word &defaultArg)
template<class Type >
bool foundObject (const word &name, const bool verbose=true) const
Protected Member Functions inherited from fvMeshFunctionObject
fvMeshFunctionObject (const fvMeshFunctionObject &)=delete
void operator= (const fvMeshFunctionObject &)=delete
Protected Member Functions inherited from regionFunctionObject
virtual const objectRegistry & obr () const
template<class ObjectType >
bool foundObject (const word &fieldName) const
template<class ObjectType >
const ObjectType * cfindObject (const word &fieldName) const
template<class ObjectType >
const ObjectType * findObject (const word &fieldName) const
template<class ObjectType >
ObjectType * findObject (const word &fieldName)
template<class ObjectType >
ObjectType * getObjectPtr (const word &fieldName) const
template<class ObjectType >
const ObjectType & lookupObject (const word &fieldName) const
template<class ObjectType >
ObjectType & lookupObjectRef (const word &fieldName) const
template<class ObjectType >
bool store (word &fieldName, const tmp< ObjectType > &tfield, bool cacheable=false)
template<class ObjectType >
bool storeInDb (const word &fieldName, const tmp< ObjectType > &tfield, const objectRegistry &obr)
bool writeObject (const word &fieldName)
bool clearObject (const word &fieldName)
void clearObjects (const wordList &objNames)
regionFunctionObject (const regionFunctionObject &)=delete
void operator= (const regionFunctionObject &)=delete
Protected Member Functions inherited from stateFunctionObject
const functionObjects::properties & stateDict () const
functionObjects::properties & stateDict ()
stateFunctionObject (const stateFunctionObject &)=delete
void operator= (const stateFunctionObject &)=delete
Protected Member Functions inherited from timeFunctionObject
void clearOutputObjects (const wordList &objNames)
timeFunctionObject (const timeFunctionObject &)=delete
void operator= (const timeFunctionObject &)=delete
Protected Member Functions inherited from functionObject
word scopedName (const word &name) const
Protected Attributes
word fieldName_
word resultName_
autoPtr< Detail::zoneSubSet > zoneSubSetPtr_
Protected Attributes inherited from fvMeshFunctionObject
const fvMesh & mesh_
Protected Attributes inherited from regionFunctionObject
word subRegistryName_
const objectRegistry & obr_
const objectRegistry * obrPtr_
Protected Attributes inherited from timeFunctionObject
const Time & time_
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &runTime, const dictionary &dict)
Public Attributes inherited from functionObject
bool log
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
static bool defaultUseNamePrefix
static word outputPrefix
Detailed Description
Intermediate class for handling field expression function objects (e.g. blendingFactor etc.) whereinto a single field is input.
Usage
Minimal example by using system/controlDict.functions:
<functionObject>
{
    // Mandatory and optional entries
    ...
    // Inherited entries
    field             <field>;
    result            <fieldResult>;
    cellZones         ( <cellZone1> <cellZone2> ... <cellZoneN> );
    nLayers           <label>;
}
where the entries mean:
Property Description Type Reqd Deflt
field Name of the operand field word yes -
result Name of the output field word no <FO>(<field>)
cellZones Names of cellZones wordRes no -
nLayers Number of cell layers around cellZones label no 0
See also
Foam::functionObject
Foam::functionObjects::fvMeshFunctionObject
ExtendedCodeGuide::functionObjects::field::fieldExpression
Source files
fieldExpression.H
fieldExpression.C
fieldExpressionTemplates.C
Definition at line 116 of file fieldExpression.H.
Constructor & Destructor Documentation
fieldExpression() [1/2]
fieldExpression (const word & name, const Time & runTime, const dictionary & dict, const word & fieldName = word::null, const word & resultName = word::null)
Definition at line 67 of file fieldExpression.C.
References dict, and fieldExpression::read().
fieldExpression() [2/2]
fieldExpression (const fieldExpression &) delete
~fieldExpression()
virtual ~fieldExpression () virtual default
Member Function Documentation
calc()
virtual bool calc () protected pure virtual
Implemented in heatTransferCoeff, multiphaseInterHtcModel, reactingEulerHtcModel, and randomise.
setResultName()
void setResultName (const word & typeName, const word & defaultArg) protected
Definition at line 38 of file fieldExpression.C.
References fieldExpression::fieldName_, fieldExpression::resultName_, and functionObject::scopedName().
Referenced by blendingFactor::blendingFactor(), CourantNo::CourantNo(), enstrophy::enstrophy(), flowType::flowType(), heatTransferCoeff::heatTransferCoeff(), Lambda2::Lambda2(), LambVector::LambVector(), MachNo::MachNo(), multiphaseInterHtcModel::multiphaseInterHtcModel(), PecletNo::PecletNo(), Q::Q(), reactingEulerHtcModel::reactingEulerHtcModel(), reference::reference(), stabilityBlendingFactor::stabilityBlendingFactor(), streamFunction::streamFunction(), and vorticity::vorticity().
foundObject()
template<class Type > bool foundObject (const word & name, const bool verbose = true) const protected
Definition at line 26 of file fieldExpressionTemplates.C.
References functionObject::debug, Foam::endl(), functionObject::name(), functionObject::type(), and Foam::Warning.
TypeName()
TypeName ("fieldExpression")
operator=()
void operator= (const fieldExpression &) delete
read()
bool read (const dictionary & dict) virtual
Reimplemented from regionFunctionObject.
Reimplemented in blendingFactor, CourantNo, log, norm, PecletNo, pow, pressure, stabilityBlendingFactor, heatTransferCoeff, multiphaseInterHtcModel, reactingEulerHtcModel, randomise, and reference.
Definition at line 86 of file fieldExpression.C.
References dict, and functionObject::read().
Referenced by ddt::ddt(), fieldExpression::fieldExpression(), blendingFactor::read(), CourantNo::read(), log::read(), norm::read(), pow::read(), pressure::read(), stabilityBlendingFactor::read(), heatTransferCoeff::read(), multiphaseInterHtcModel::read(), reactingEulerHtcModel::read(), randomise::read(), and reference::read().
execute()
bool execute () virtual
Implements functionObject.
Definition at line 113 of file fieldExpression.C.
References clear(), Foam::endl(), Foam::name(), Foam::type(), and Foam::Warning.
write()
bool write () virtual
Implements functionObject.
Reimplemented in blendingFactor, components, div, and stabilityBlendingFactor.
Definition at line 131 of file fieldExpression.C.
Referenced by blendingFactor::write().
clear()
bool clear () virtual
Reimplemented in components.
Definition at line 137 of file fieldExpression.C.
Member Data Documentation
fieldName_
word fieldName_ protected
Definition at line 125 of file fieldExpression.H.
Referenced by fieldExpression::setResultName(), and vorticity::vorticity().
resultName_
word resultName_ protected
Definition at line 128 of file fieldExpression.H.
Referenced by blendingFactor::blendingFactor(), heatTransferCoeff::calc(), multiphaseInterHtcModel::calc(), reactingEulerHtcModel::calc(), heatTransferCoeff::heatTransferCoeff(), multiphaseInterHtcModel::multiphaseInterHtcModel(), reactingEulerHtcModel::reactingEulerHtcModel(), fieldExpression::setResultName(), and stabilityBlendingFactor::stabilityBlendingFactor().
zoneSubSetPtr_
autoPtr<Detail::zoneSubSet> zoneSubSetPtr_ protected
Definition at line 131 of file fieldExpression.H.
The documentation for this class was generated from the following files:
src/functionObjects/field/fieldExpression/fieldExpression.H
src/functionObjects/field/fieldExpression/fieldExpression.C
src/functionObjects/field/fieldExpression/fieldExpressionTemplates.C