OpenFOAM: UILList< LListBase, T > Class Template Reference
UILList< LListBase, T > Class Template Reference
Template class for intrusive linked lists.
#include <UILList.H>
Classes
class const_iterator
class const_reverse_iterator
class iterator
class reverse_iterator
Public Types
typedef T value_type
typedef T * pointer
typedef const T * const_pointer
typedef T & reference
typedef const T & const_reference
typedef label size_type
typedef label difference_type
using base_iterator = typename LListBase::iterator
using const_base_iterator = typename LListBase::const_iterator
Public Member Functions
UILList ()=default
UILList (T *item)
UILList (const UILList< LListBase, T > &list)
T * front ()
const T * front () const
T * back ()
const T * back () const
T * removeHead ()
T * remove (T *item)
T * remove (iterator &iter)
void operator= (const UILList< LListBase, T > &lst)
bool operator== (const UILList< LListBase, T > &lst) const
bool operator!= (const UILList< LListBase, T > &lst) const
Ostream & writeList (Ostream &os, const label shortLen=0) const
iterator begin ()
const_iterator cbegin () const
reverse_iterator rbegin ()
const_reverse_iterator crbegin () const
const_iterator begin () const
const_reverse_iterator rbegin () const
const iterator & end ()
const const_iterator & cend () const
const reverse_iterator & rend ()
const const_reverse_iterator & crend () const
const const_iterator & end () const
const const_reverse_iterator & rend () const
T * first ()
const T * first () const
T * last ()
const T * last () const
Friends
Ostream & operator (Ostream &os, const UILList< LListBase, T > &lst)
Detailed Description
template<class LListBase, class T>
class Foam::UILList< LListBase, T >
Template class for intrusive linked lists.
Source files
UILList.H
UILList.C
UILListIO.C
Definition at line 62 of file UILList.H.
Member Typedef Documentation
value_type
template<class LListBase , class T > typedef T value_type
Definition at line 71 of file UILList.H.
pointer
template<class LListBase , class T > typedef T* pointer
Definition at line 74 of file UILList.H.
const_pointer
template<class LListBase , class T > typedef const T* const_pointer
Definition at line 77 of file UILList.H.
reference
template<class LListBase , class T > typedef T& reference
Definition at line 80 of file UILList.H.
const_reference
template<class LListBase , class T > typedef const T& const_reference
Definition at line 83 of file UILList.H.
size_type
template<class LListBase , class T > typedef label size_type
Definition at line 86 of file UILList.H.
difference_type
template<class LListBase , class T > typedef label difference_type
Definition at line 89 of file UILList.H.
base_iterator
template<class LListBase , class T > using base_iterator = typename LListBase::iterator
Definition at line 97 of file UILList.H.
const_base_iterator
template<class LListBase , class T > using const_base_iterator = typename LListBase::const_iterator
Definition at line 98 of file UILList.H.
Constructor & Destructor Documentation
UILList() [1/3]
template<class LListBase , class T > UILList () default
UILList() [2/3]
template<class LListBase , class T > UILList (T * item) inline explicit
Definition at line 107 of file UILList.H.
UILList() [3/3]
template<class LListBase , class T > UILList (const UILList< LListBase, T > & list)
Definition at line 27 of file UILList.C.
References UPtrList< T >::cbegin(), UPtrList< T >::cend(), and PtrList< T >::push_back().
Member Function Documentation
front() [1/2]
template<class LListBase , class T > T * front () inline
Definition at line 119 of file UILList.H.
References T.
Referenced by UILList< LListBase, T >::first(), and UILList< LListBase, T >::first().
front() [2/2]
template<class LListBase , class T > const T * front () const inline
Definition at line 125 of file UILList.H.
References T.
back() [1/2]
template<class LListBase , class T > T * back () inline
Definition at line 131 of file UILList.H.
References T.
Referenced by UILList< LListBase, T >::last(), and UILList< LListBase, T >::last().
back() [2/2]
template<class LListBase , class T > const T * back () const inline
Definition at line 137 of file UILList.H.
References T.
removeHead()
template<class LListBase , class T > T * removeHead () inline
Definition at line 144 of file UILList.H.
References T.
remove() [1/2]
template<class LListBase , class T > T * remove (T * item) inline
Definition at line 150 of file UILList.H.
References T.
remove() [2/2]
template<class LListBase , class T > T * remove (iterator & iter) inline
Definition at line 156 of file UILList.H.
References T.
operator=()
template<class LListBase , class T > void operator= (const UILList< LListBase, T > & lst)
Definition at line 39 of file UILList.C.
References UPtrList< T >::cbegin(), and UPtrList< T >::cend().
operator==()
template<class LListBase , class T > bool operator== (const UILList< LListBase, T > & lst) const
Definition at line 51 of file UILList.C.
References UPtrList< T >::cbegin().
operator!=()
template<class LListBase , class T > bool operator!= (const UILList< LListBase, T > & lst) const
Definition at line 76 of file UILList.C.
References Foam::operator==().
writeList()
template<class LListBase , class T > Foam::Ostream & writeList (Ostream & os, const label shortLen = 0) const
Definition at line 29 of file UILListIO.C.
References token::BEGIN_LIST, token::END_LIST, FUNCTION_NAME, Foam::nl, os(), UPtrList< T >::size(), token::SPACE, and T.
begin() [1/2]
template<class LListBase , class T > iterator begin () inline
Definition at line 372 of file UILList.H.
cbegin()
template<class LListBase , class T > const_iterator cbegin () const inline
Definition at line 378 of file UILList.H.
rbegin() [1/2]
template<class LListBase , class T > reverse_iterator rbegin () inline
Definition at line 384 of file UILList.H.
crbegin()
template<class LListBase , class T > const_reverse_iterator crbegin () const inline
Definition at line 390 of file UILList.H.
Referenced by UILList< LListBase, T >::rbegin().
begin() [2/2]
template<class LListBase , class T > const_iterator begin () const inline
Definition at line 396 of file UILList.H.
rbegin() [2/2]
template<class LListBase , class T > const_reverse_iterator rbegin () const inline
Definition at line 402 of file UILList.H.
References UILList< LListBase, T >::crbegin().
end() [1/2]
template<class LListBase , class T > const iterator & end () inline
Definition at line 409 of file UILList.H.
Referenced by KirchhoffShell::solveDisplacement().
cend()
template<class LListBase , class T > const const_iterator & cend () const inline
Definition at line 415 of file UILList.H.
Referenced by UILList< LListBase, T >::end().
rend() [1/2]
template<class LListBase , class T > const reverse_iterator & rend () inline
Definition at line 421 of file UILList.H.
crend()
template<class LListBase , class T > const const_reverse_iterator & crend () const inline
Definition at line 427 of file UILList.H.
Referenced by UILList< LListBase, T >::rend().
end() [2/2]
template<class LListBase , class T > const const_iterator & end () const inline
Definition at line 433 of file UILList.H.
References UILList< LListBase, T >::cend().
rend() [2/2]
template<class LListBase , class T > const const_reverse_iterator & rend () const inline
Definition at line 439 of file UILList.H.
References UILList< LListBase, T >::crend().
first() [1/2]
template<class LListBase , class T > T * first () inline
Definition at line 449 of file UILList.H.
References UILList< LListBase, T >::front().
Referenced by bladeModel::bladeModel(), meshRefinement::lookup(), and thermophysicalPropertiesSelector< ThermophysicalProperties >::thermophysicalPropertiesSelector().
first() [2/2]
template<class LListBase , class T > const T * first () const inline
Definition at line 453 of file UILList.H.
References UILList< LListBase, T >::front().
last() [1/2]
template<class LListBase , class T > T * last () inline
Definition at line 457 of file UILList.H.
References UILList< LListBase, T >::back().
last() [2/2]
template<class LListBase , class T > const T * last () const inline
Definition at line 461 of file UILList.H.
References UILList< LListBase, T >::back().
Friends And Related Symbol Documentation
operator
template<class LListBase , class T > Ostream & operator (Ostream & os, const UILList< LListBase, T > & lst) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/LinkedLists/accessTypes/UILList/UILList.H
src/OpenFOAM/containers/LinkedLists/accessTypes/UILList/UILList.C
src/OpenFOAM/containers/LinkedLists/accessTypes/UILList/UILListIO.C