OpenFOAM: surfaceLocation Class Reference
surfaceLocation Class Reference
Contains information about location on a triSurface.
#include <surfaceLocation.H>
Public Member Functions
surfaceLocation ()
surfaceLocation (const pointIndexHit &pHit, const triPointRef::proxType elementType, const label triangle)
surfaceLocation (Istream &is)
triPointRef::proxType & elementType () noexcept
triPointRef::proxType elementType () const noexcept
label & triangle () noexcept
label triangle () const noexcept
vector normal (const triSurface &s) const
InfoProxy< surfaceLocation > info () const noexcept
void write (Ostream &os, const triSurface &s) const
Public Member Functions inherited from PointIndexHit< PointType >
PointIndexHit ()
PointIndexHit (const point_type &p)
PointIndexHit (const PointHit< point_type > &p, label index=-1)
PointIndexHit (const PointIndexHit< point_type > &p, label index)
PointIndexHit (bool success, const point_type &p, label index)
PointIndexHit (Istream &is)
bool hit () const noexcept
label index () const noexcept
const point_type & point () const noexcept
point_type & point () noexcept
const point_type & hitPoint () const
const point_type & missPoint () const
const point_type & rawPoint () const noexcept
point_type & rawPoint () noexcept
void setHit () noexcept
void setMiss () noexcept
void setPoint (const point_type &p)
void setIndex (const label index) noexcept
void hitPoint (const point_type &p)
void hitPoint (const point_type &p, const label index)
void write (Ostream &os)
bool operator== (const PointIndexHit &rhs) const
bool operator!= (const PointIndexHit &rhs) const
Friends
Istream & operator>> (Istream &is, surfaceLocation &sl)
Ostream & operator<< (Ostream &os, const surfaceLocation &sl)
Additional Inherited Members
Public Types inherited from PointIndexHit< PointType >
typedef PointType point_type
Detailed Description
Contains information about location on a triSurface.
Access to data:
pointIndexHit provides
location
bool: hit/miss
index (of triangle/point/edge)
elementType() provides
what index above relates to. In triangle::proxType
triangle() provides
last known triangle
Source files
surfaceLocation.H
surfaceLocation.C
Definition at line 69 of file surfaceLocation.H.
Constructor & Destructor Documentation
surfaceLocation() [1/3]
surfaceLocation () inline
Definition at line 85 of file surfaceLocation.H.
surfaceLocation() [2/3]
surfaceLocation (const pointIndexHit & pHit, const triPointRef::proxType elementType, const label triangle) inline
Definition at line 93 of file surfaceLocation.H.
surfaceLocation() [3/3]
surfaceLocation (Istream & is) inline explicit
Definition at line 106 of file surfaceLocation.H.
Member Function Documentation
elementType() [1/2]
triPointRef::proxType & elementType () inline noexcept
Definition at line 116 of file surfaceLocation.H.
Referenced by triSurfaceTools::classify(), and triSurfaceTools::trackToEdge().
elementType() [2/2]
triPointRef::proxType elementType () const inline noexcept
Definition at line 121 of file surfaceLocation.H.
triangle() [1/2]
label & triangle () inline noexcept
Definition at line 126 of file surfaceLocation.H.
Referenced by triSurfaceTools::trackToEdge().
triangle() [2/2]
label triangle () const inline noexcept
Definition at line 131 of file surfaceLocation.H.
normal()
Foam::vector normal (const triSurface & s) const
Definition at line 27 of file surfaceLocation.C.
References triangle< Point, PointRef >::EDGE, PointIndexHit< PointType >::index(), Foam::mag(), n, triangle< Point, PointRef >::NONE, s(), UPtrList< T >::size(), and Foam::Zero.
info()
InfoProxy< surfaceLocation > info () const inline noexcept
Definition at line 141 of file surfaceLocation.H.
write()
void write (Ostream & os, const triSurface & s) const
Definition at line 65 of file surfaceLocation.C.
References e, triangle< Point, PointRef >::EDGE, triangle< Point, PointRef >::NONE, os(), and s().
Friends And Related Symbol Documentation
operator>>
Istream & operator>> (Istream & is, surfaceLocation & sl) friend
operator<<
Ostream & operator<< (Ostream & os, const surfaceLocation & sl) friend
The documentation for this class was generated from the following files:
src/meshTools/triSurface/surfaceLocation/surfaceLocation.H
src/meshTools/triSurface/surfaceLocation/surfaceLocation.C