OpenFOAM: WallModel< CloudType > Class Template Reference
WallModel< CloudType > Class Template Reference abstract
Templated wall interaction class.
#include <WallModel.H>
Public Member Functions
TypeName ("wallModel")
declareRunTimeSelectionTable (autoPtr, WallModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
WallModel (const dictionary &dict, CloudType &owner, const word &type)
virtual ~WallModel ()
const CloudType & owner () const
CloudType & owner ()
const dictionary & dict () const
const dictionary & coeffDict () const
virtual scalar pREff (const typename CloudType::parcelType &p) const =0
virtual bool controlsTimestep () const =0
virtual label nSubCycles () const =0
virtual void evaluateWall (typename CloudType::parcelType &p, const List< point > &flatSitePoints, const List< WallSiteData< vector > > &flatSiteData, const List< point > &sharpSitePoints, const List< WallSiteData< vector > > &sharpSiteData) const =0
Static Public Member Functions
static autoPtr< WallModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Detailed Description
template<class CloudType>
class Foam::WallModel< CloudType >
Templated wall interaction class.
Source files
WallModel.H
WallModel.C
WallModelNew.C
Definition at line 51 of file WallModel.H.
Constructor & Destructor Documentation
WallModel()
template<class CloudType > WallModel (const dictionary & dict, CloudType & owner, const word & type)
Definition at line 26 of file WallModel.C.
~WallModel()
template<class CloudType > ~WallModel () virtual
Definition at line 42 of file WallModel.C.
Member Function Documentation
TypeName()
template<class CloudType > TypeName ("wallModel")
declareRunTimeSelectionTable()
template<class CloudType > declareRunTimeSelectionTable (autoPtr , WallModel< CloudType > , dictionary , (const dictionary &dict, CloudType &owner) , (dict, owner))
New()
template<class CloudType > Foam::autoPtr< Foam::WallModel< CloudType > > New (const dictionary & dict, CloudType & owner) static
Definition at line 28 of file WallModelNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, Foam::Info, and PtrList< T >::PtrList().
owner() [1/2]
template<class CloudType > const CloudType & owner () const
Definition at line 50 of file WallModel.C.
Referenced by WallLocalSpringSliderDashpot< CloudType >::WallLocalSpringSliderDashpot(), and WallSpringSliderDashpot< CloudType >::WallSpringSliderDashpot().
owner() [2/2]
template<class CloudType > CloudType & owner ()
Definition at line 58 of file WallModel.C.
dict()
template<class CloudType > const Foam::dictionary & dict () const
Definition at line 65 of file WallModel.C.
coeffDict()
template<class CloudType > const Foam::dictionary & coeffDict () const
Definition at line 73 of file WallModel.C.
Referenced by WallLocalSpringSliderDashpot< CloudType >::WallLocalSpringSliderDashpot(), and WallSpringSliderDashpot< CloudType >::WallSpringSliderDashpot().
pREff()
template<class CloudType > virtual scalar pREff (const typename CloudType::parcelType & p) const pure virtual
Implemented in WallLocalSpringSliderDashpot< CloudType >, and WallSpringSliderDashpot< CloudType >.
controlsTimestep()
template<class CloudType > virtual bool controlsTimestep () const pure virtual
Implemented in WallLocalSpringSliderDashpot< CloudType >, and WallSpringSliderDashpot< CloudType >.
nSubCycles()
template<class CloudType > virtual label nSubCycles () const pure virtual
Implemented in WallLocalSpringSliderDashpot< CloudType >, and WallSpringSliderDashpot< CloudType >.
evaluateWall()
template<class CloudType > virtual void evaluateWall (typename CloudType::parcelType & p, const List< point > & flatSitePoints, const List< WallSiteData< vector > > & flatSiteData, const List< point > & sharpSitePoints, const List< WallSiteData< vector > > & sharpSiteData) const pure virtual
Implemented in WallLocalSpringSliderDashpot< CloudType >, and WallSpringSliderDashpot< CloudType >.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/Kinematic/CollisionModel/PairCollision/PairCollision.H
src/lagrangian/intermediate/submodels/Kinematic/CollisionModel/PairCollision/WallModel/WallModel/WallModel.H
src/lagrangian/intermediate/submodels/Kinematic/CollisionModel/PairCollision/WallModel/WallModel/WallModel.C
src/lagrangian/intermediate/submodels/Kinematic/CollisionModel/PairCollision/WallModel/WallModel/WallModelNew.C