OpenFOAM: preserveBaffles Class Reference
preserveBaffles Class Reference
Detects baffles and keeps owner and neighbour on same processor.
#include <preserveBafflesConstraint.H>
Public Member Functions
TypeName ("preserveBaffles")
preserveBaffles (const dictionary &dict)
preserveBaffles ()
virtual ~preserveBaffles ()=default
virtual void add (const polyMesh &mesh, boolList &blockedFace, PtrList< labelList > &specifiedProcessorFaces, labelList &specifiedProcessor, List< labelPair > &explicitConnections) const
virtual void apply (const polyMesh &mesh, const boolList &blockedFace, const PtrList< labelList > &specifiedProcessorFaces, const labelList &specifiedProcessor, const List< labelPair > &explicitConnections, labelList &decomposition) const
Public Member Functions inherited from decompositionConstraint
TypeName ("decompositionConstraint")
declareRunTimeSelectionTable (autoPtr, decompositionConstraint, dictionary,(const dictionary &dict),(dict))
decompositionConstraint (const dictionary &constraintDict)
decompositionConstraint (const dictionary &constraintDict, const word &modelType)
virtual ~decompositionConstraint ()=default
Additional Inherited Members
Static Public Member Functions inherited from decompositionConstraint
static autoPtr< decompositionConstraint > New (const dictionary &constraintDict)
static autoPtr< decompositionConstraint > New (const dictionary &constraintDict, const word &modelType)
Protected Member Functions inherited from decompositionConstraint
void getMinBoundaryValue (const polyMesh &mesh, const labelList &decomposition, labelList &destProc) const
decompositionConstraint (const decompositionConstraint &)=delete
void operator= (const decompositionConstraint &)=delete
Protected Attributes inherited from decompositionConstraint
dictionary coeffDict_
Detailed Description
Detects baffles and keeps owner and neighbour on same processor.
Dictionary parameters
Property Description Required Default
type preserveBaffles yes
Source files
preserveBafflesConstraint.H
preserveBafflesConstraint.C
Definition at line 65 of file preserveBafflesConstraint.H.
Constructor & Destructor Documentation
preserveBaffles() [1/2]
preserveBaffles (const dictionary & dict) explicit
Definition at line 47 of file preserveBafflesConstraint.C.
References Foam::endl(), Foam::Info, and Foam::type().
preserveBaffles() [2/2]
preserveBaffles ()
Definition at line 64 of file preserveBafflesConstraint.C.
References Foam::endl(), Foam::Info, and Foam::type().
~preserveBaffles()
virtual ~preserveBaffles () virtual default
Member Function Documentation
TypeName()
TypeName ("preserveBaffles")
add()
void add (const polyMesh & mesh, boolList & blockedFace, PtrList< labelList > & specifiedProcessorFaces, labelList & specifiedProcessor, List< labelPair > & explicitConnections) const virtual
Implements decompositionConstraint.
Definition at line 80 of file preserveBafflesConstraint.C.
References Pair< label >::compare(), Foam::endl(), localPointRegion::findDuplicateFacePairs(), forAll, Foam::Info, IOWarningInFunction, mesh, n, p, Foam::returnReduce(), PtrList< T >::setSize(), UPtrList< T >::size(), syncTools::syncFaceList(), and Foam::type().
apply()
void apply (const polyMesh & mesh, const boolList & blockedFace, const PtrList< labelList > & specifiedProcessorFaces, const labelList & specifiedProcessor, const List< labelPair > & explicitConnections, labelList & decomposition) const virtual
Reimplemented from decompositionConstraint.
Definition at line 175 of file preserveBafflesConstraint.C.
References Foam::endl(), localPointRegion::findDuplicateFacePairs(), UPtrList< T >::first(), Foam::Info, mesh, Foam::returnReduce(), and Foam::type().
The documentation for this class was generated from the following files:
src/parallel/decompose/decompositionMethods/decompositionConstraints/preserveBaffles/preserveBafflesConstraint.H
src/parallel/decompose/decompositionMethods/decompositionConstraints/preserveBaffles/preserveBafflesConstraint.C