OpenFOAM: kEpsilonPhitF< BasicTurbulenceModel > Class Template Reference
kEpsilonPhitF< BasicTurbulenceModel > Class Template Reference
Turbulence models » RAS turbulence
The k-epsilon-phit-f turbulence closure model for incompressible and compressible flows.
#include <kEpsilonPhitF.H>
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from linearViscousStress< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("kEpsilonPhitF")
kEpsilonPhitF (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
virtual ~kEpsilonPhitF ()=default
virtual bool read ()
tmp< volScalarField > DkEff () const
tmp< volScalarField > DepsilonEff () const
tmp< volScalarField > DphitEff () const
virtual tmp< volScalarField > k () const
virtual tmp< volScalarField > epsilon () const
virtual tmp< volScalarField > phit () const
virtual tmp< volScalarField > f () const
virtual void correct ()
Public Member Functions inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
eddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~eddyViscosity ()=default
virtual tmp< volScalarField > nut () const
virtual tmp< scalarField > nut (const label patchi) const
virtual tmp< volSymmTensorField > R () const
virtual void validate ()
Public Member Functions inherited from linearViscousStress< BasicTurbulenceModel >
linearViscousStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~linearViscousStress ()=default
virtual tmp< volSymmTensorField > devRhoReff () const
virtual tmp< volSymmTensorField > devRhoReff (const volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Protected Member Functions
virtual void correctNut ()
tmp< volScalarField > Ts () const
tmp< volScalarField > Ls () const
Protected Attributes
Switch includeNu_
dimensionedScalar Cmu_
dimensionedScalar Ceps1a_
dimensionedScalar Ceps1b_
dimensionedScalar Ceps1c_
dimensionedScalar Ceps2_
dimensionedScalar Cf1_
dimensionedScalar Cf2_
dimensionedScalar CL_
dimensionedScalar Ceta_
dimensionedScalar CT_
dimensionedScalar sigmaK_
dimensionedScalar sigmaEps_
dimensionedScalar sigmaPhit_
volScalarField k_
volScalarField epsilon_
volScalarField phit_
volScalarField f_
volScalarField T_
dimensionedScalar phitMin_
dimensionedScalar fMin_
dimensionedScalar TMin_
dimensionedScalar L2Min_
Protected Attributes inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
volScalarField nut_
Detailed Description
template<class BasicTurbulenceModel>
class Foam::RASModels::kEpsilonPhitF< BasicTurbulenceModel >
The k-epsilon-phit-f turbulence closure model for incompressible and compressible flows.
The model is a three-transport-equation linear-eddy-viscosity turbulence closure model alongside an elliptic relaxation equation.
Input fields
k : Turbulent kinetic energy [m2/s2]
epsilon : Turbulent kinetic energy dissipation rate [m2/s3]
phit : Normalised wall-normal fluctuating velocity scale [-]
f : Elliptic relaxation factor [1/s]
Reference:
        Standard model (Tag:LUU):
            Laurence, D. R., Uribe, J. C., & Utyuzhnikov, S. V. (2005).
            A robust formulation of the v2-f model.
            Flow, Turbulence and Combustion, 73(3-4), 169185.
            DOI:10.1007/s10494-005-1974-8
The default model coefficients are (LUU:Eqs. 19-20):
        kEpsilonPhitFCoeffs
        {
            includeNu   true;    // include nu in (LUU: Eq. 17), see Notes
            Cmu         0.22;    // Turbulent viscosity constant
            Ceps1a      1.4;     // Model constant for epsilon
            Ceps1b      1.0;     // Model constant for epsilon
            Ceps1c      0.05;    // Model constant for epsilon
            Ceps2       1.9;     // Model constant for epsilon
            Cf1         1.4;     // Model constant for f
            Cf2         0.3;     // Model constant for f
            CL          0.25;    // Model constant for L
            Ceta        110.0;   // Model constant for L
            CT          6.0;     // Model constant for T
            sigmaK      1.0;     // Turbulent Prandtl number for k
            sigmaEps    1.3;     // Turbulent Prandtl number for epsilon
            sigmaPhit   1.0;     // Turbulent Prandtl number for phit = sigmaK
        }
Note
The name of the original variable replacing 'v2' is 'phi' (LUU:Eq. 14). However, the name 'phi' preexisted in OpenFOAM; therefore, this name was replaced by 'phit' herein.
Including nu in DphitEff even though it is not present in (LUU:Eq. 17) provided higher level of resemblance to benchmarks for the tests considered, particularly for the peak skin friction (yet, pressure-related predictions were unaffected). Users can switch off nu in DphitEff by using includeNu entry in kEpsilonPhitFCoeffs as shown above in order to follow the reference paper thereat. includeNu is left true by default. See GitLab issue #1560.
Source files
kEpsilonPhitF.H
kEpsilonPhitF.C
See also
kEpsilon.C
Definition at line 127 of file kEpsilonPhitF.H.
Member Typedef Documentation
alphaField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 203 of file kEpsilonPhitF.H.
rhoField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 204 of file kEpsilonPhitF.H.
transportModel
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 205 of file kEpsilonPhitF.H.
Constructor & Destructor Documentation
kEpsilonPhitF()
template<class BasicTurbulenceModel > kEpsilonPhitF (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Definition at line 92 of file kEpsilonPhitF.C.
References Foam::bound(), kEpsilonPhitF< BasicTurbulenceModel >::epsilon_, Foam::exit(), kEpsilonPhitF< BasicTurbulenceModel >::f_, Foam::FatalError, FatalErrorInFunction, kEpsilonPhitF< BasicTurbulenceModel >::fMin_, kEpsilonPhitF< BasicTurbulenceModel >::k_, Foam::mag(), Foam::nl, kEpsilonPhitF< BasicTurbulenceModel >::phit_, kEpsilonPhitF< BasicTurbulenceModel >::phitMin_, kEpsilonPhitF< BasicTurbulenceModel >::sigmaEps_, kEpsilonPhitF< BasicTurbulenceModel >::sigmaK_, kEpsilonPhitF< BasicTurbulenceModel >::sigmaPhit_, Foam::type(), and dimensioned< Type >::value().
~kEpsilonPhitF()
template<class BasicTurbulenceModel > virtual ~kEpsilonPhitF () virtual default
Member Function Documentation
correctNut()
template<class BasicTurbulenceModel > void correctNut () protected virtual
Implements eddyViscosity< RASModel< BasicTurbulenceModel > >.
Definition at line 35 of file kEpsilonPhitF.C.
References options::New().
Ts()
template<class BasicTurbulenceModel > tmp< volScalarField > Ts () const protected
Definition at line 47 of file kEpsilonPhitF.C.
References Foam::max(), nu, Foam::sqrt(), and Foam::Zero.
Ls()
template<class BasicTurbulenceModel > tmp< volScalarField > Ls () const protected
Definition at line 67 of file kEpsilonPhitF.C.
References Foam::max(), nu, Foam::pow(), Foam::pow025(), Foam::pow3(), and Foam::Zero.
TypeName()
template<class BasicTurbulenceModel > TypeName ("kEpsilonPhitF< BasicTurbulenceModel >")
read()
template<class BasicTurbulenceModel > bool read () virtual
Implements eddyViscosity< RASModel< BasicTurbulenceModel > >.
Definition at line 341 of file kEpsilonPhitF.C.
References Foam::read().
DkEff()
template<class BasicTurbulenceModel > tmp< volScalarField > DkEff () const inline
Definition at line 238 of file kEpsilonPhitF.H.
References nu, and eddyViscosity< RASModel< BasicTurbulenceModel > >::nut_.
DepsilonEff()
template<class BasicTurbulenceModel > tmp< volScalarField > DepsilonEff () const inline
Definition at line 251 of file kEpsilonPhitF.H.
References nu, and eddyViscosity< RASModel< BasicTurbulenceModel > >::nut_.
DphitEff()
template<class BasicTurbulenceModel > tmp< volScalarField > DphitEff () const inline
Definition at line 264 of file kEpsilonPhitF.H.
References kEpsilonPhitF< BasicTurbulenceModel >::includeNu_, tmp< T >::New(), nu, and eddyViscosity< RASModel< BasicTurbulenceModel > >::nut_.
k()
template<class BasicTurbulenceModel > virtual tmp< volScalarField > k () const inline virtual
Implements eddyViscosity< RASModel< BasicTurbulenceModel > >.
Definition at line 278 of file kEpsilonPhitF.H.
References kEpsilonPhitF< BasicTurbulenceModel >::k_.
epsilon()
template<class BasicTurbulenceModel > virtual tmp< volScalarField > epsilon () const inline virtual
Definition at line 284 of file kEpsilonPhitF.H.
References kEpsilonPhitF< BasicTurbulenceModel >::epsilon_.
phit()
template<class BasicTurbulenceModel > virtual tmp< volScalarField > phit () const inline virtual
Definition at line 290 of file kEpsilonPhitF.H.
References kEpsilonPhitF< BasicTurbulenceModel >::phit_.
f()
template<class BasicTurbulenceModel > virtual tmp< volScalarField > f () const inline virtual
Definition at line 296 of file kEpsilonPhitF.H.
References kEpsilonPhitF< BasicTurbulenceModel >::f_.
correct()
template<class BasicTurbulenceModel > void correct () virtual
Implements eddyViscosity< RASModel< BasicTurbulenceModel > >.
Definition at line 368 of file kEpsilonPhitF.C.
References Foam::fvc::absolute(), alpha, Foam::bound(), PtrList< T >::clear(), correct(), Foam::fvm::ddt(), Foam::dev(), Foam::fvc::div(), Foam::fvm::div(), divU, fvOptions, Foam::fvc::grad(), Foam::fvc::laplacian(), Foam::fvm::laplacian(), options::New(), nu, nut, phi, rho, solve(), Foam::fvm::Sp(), Foam::sqr(), Foam::sqrt(), Foam::fvm::SuSp(), Foam::symm(), Foam::type(), and U.
Member Data Documentation
includeNu_
template<class BasicTurbulenceModel > Switch includeNu_ protected
Definition at line 144 of file kEpsilonPhitF.H.
Referenced by kEpsilonPhitF< BasicTurbulenceModel >::DphitEff().
Cmu_
template<class BasicTurbulenceModel > dimensionedScalar Cmu_ protected
Definition at line 148 of file kEpsilonPhitF.H.
Ceps1a_
template<class BasicTurbulenceModel > dimensionedScalar Ceps1a_ protected
Definition at line 149 of file kEpsilonPhitF.H.
Ceps1b_
template<class BasicTurbulenceModel > dimensionedScalar Ceps1b_ protected
Definition at line 150 of file kEpsilonPhitF.H.
Ceps1c_
template<class BasicTurbulenceModel > dimensionedScalar Ceps1c_ protected
Definition at line 151 of file kEpsilonPhitF.H.
Ceps2_
template<class BasicTurbulenceModel > dimensionedScalar Ceps2_ protected
Definition at line 152 of file kEpsilonPhitF.H.
Cf1_
template<class BasicTurbulenceModel > dimensionedScalar Cf1_ protected
Definition at line 153 of file kEpsilonPhitF.H.
Cf2_
template<class BasicTurbulenceModel > dimensionedScalar Cf2_ protected
Definition at line 154 of file kEpsilonPhitF.H.
CL_
template<class BasicTurbulenceModel > dimensionedScalar CL_ protected
Definition at line 155 of file kEpsilonPhitF.H.
Ceta_
template<class BasicTurbulenceModel > dimensionedScalar Ceta_ protected
Definition at line 156 of file kEpsilonPhitF.H.
CT_
template<class BasicTurbulenceModel > dimensionedScalar CT_ protected
Definition at line 157 of file kEpsilonPhitF.H.
sigmaK_
template<class BasicTurbulenceModel > dimensionedScalar sigmaK_ protected
Definition at line 158 of file kEpsilonPhitF.H.
Referenced by kEpsilonPhitF< BasicTurbulenceModel >::kEpsilonPhitF().
sigmaEps_
template<class BasicTurbulenceModel > dimensionedScalar sigmaEps_ protected
Definition at line 159 of file kEpsilonPhitF.H.
Referenced by kEpsilonPhitF< BasicTurbulenceModel >::kEpsilonPhitF().
sigmaPhit_
template<class BasicTurbulenceModel > dimensionedScalar sigmaPhit_ protected
Definition at line 160 of file kEpsilonPhitF.H.
Referenced by kEpsilonPhitF< BasicTurbulenceModel >::kEpsilonPhitF().
k_
template<class BasicTurbulenceModel > volScalarField k_ protected
Definition at line 166 of file kEpsilonPhitF.H.
Referenced by kEpsilonPhitF< BasicTurbulenceModel >::k(), and kEpsilonPhitF< BasicTurbulenceModel >::kEpsilonPhitF().
epsilon_
template<class BasicTurbulenceModel > volScalarField epsilon_ protected
Definition at line 169 of file kEpsilonPhitF.H.
Referenced by kEpsilonPhitF< BasicTurbulenceModel >::epsilon(), and kEpsilonPhitF< BasicTurbulenceModel >::kEpsilonPhitF().
phit_
template<class BasicTurbulenceModel > volScalarField phit_ protected
Definition at line 172 of file kEpsilonPhitF.H.
Referenced by kEpsilonPhitF< BasicTurbulenceModel >::kEpsilonPhitF(), and kEpsilonPhitF< BasicTurbulenceModel >::phit().
f_
template<class BasicTurbulenceModel > volScalarField f_ protected
Definition at line 175 of file kEpsilonPhitF.H.
Referenced by kEpsilonPhitF< BasicTurbulenceModel >::f(), and kEpsilonPhitF< BasicTurbulenceModel >::kEpsilonPhitF().
T_
template<class BasicTurbulenceModel > volScalarField T_ protected
Definition at line 178 of file kEpsilonPhitF.H.
phitMin_
template<class BasicTurbulenceModel > dimensionedScalar phitMin_ protected
Definition at line 183 of file kEpsilonPhitF.H.
Referenced by kEpsilonPhitF< BasicTurbulenceModel >::kEpsilonPhitF().
fMin_
template<class BasicTurbulenceModel > dimensionedScalar fMin_ protected
Definition at line 184 of file kEpsilonPhitF.H.
Referenced by kEpsilonPhitF< BasicTurbulenceModel >::kEpsilonPhitF().
TMin_
template<class BasicTurbulenceModel > dimensionedScalar TMin_ protected
Definition at line 185 of file kEpsilonPhitF.H.
L2Min_
template<class BasicTurbulenceModel > dimensionedScalar L2Min_ protected
Definition at line 186 of file kEpsilonPhitF.H.
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/RAS/kEpsilonPhitF/kEpsilonPhitF.H
src/TurbulenceModels/turbulenceModels/RAS/kEpsilonPhitF/kEpsilonPhitF.C