OpenFOAM: incompressiblePerfectGas< Specie > Class Template Reference
incompressiblePerfectGas< Specie > Class Template Reference
Thermophysical models » Specie » Equation of state
Incompressible gas equation of state using a constant reference pressure in the perfect gas equation of state rather than the local pressure so that the density only varies with temperature and composition.
#include <incompressiblePerfectGas.H>
Public Member Functions
incompressiblePerfectGas (const Specie &sp, const scalar pRef)
incompressiblePerfectGas (const dictionary &dict)
incompressiblePerfectGas (const word &name, const incompressiblePerfectGas &)
autoPtr< incompressiblePerfectGas > clone () const
scalar rho (scalar p, scalar T) const
scalar H (const scalar p, const scalar T) const
scalar Cp (scalar p, scalar T) const
scalar E (const scalar p, const scalar T) const
scalar Cv (scalar p, scalar T) const
scalar S (const scalar p, const scalar T) const
scalar psi (scalar p, scalar T) const
scalar Z (scalar p, scalar T) const
scalar CpMCv (scalar p, scalar T) const
void write (Ostream &os) const
void operator+= (const incompressiblePerfectGas &)
void operator*= (const scalar)
Static Public Member Functions
static autoPtr< incompressiblePerfectGas > New (const dictionary &dict)
static word typeName ()
Static Public Attributes
static const bool incompressible = true
static const bool isochoric = false
Friends
incompressiblePerfectGas operator+ (const incompressiblePerfectGas &, const incompressiblePerfectGas &)
incompressiblePerfectGas operator* (const scalar s, const incompressiblePerfectGas &)
incompressiblePerfectGas operator== (const incompressiblePerfectGas &, const incompressiblePerfectGas &)
Ostream & operator<< (Ostream &, const incompressiblePerfectGas &)
Detailed Description
template<class Specie>
class Foam::incompressiblePerfectGas< Specie >
Incompressible gas equation of state using a constant reference pressure in the perfect gas equation of state rather than the local pressure so that the density only varies with temperature and composition.
Source files
incompressiblePerfectGas.H
incompressiblePerfectGasI.H
incompressiblePerfectGas.C
Definition at line 87 of file incompressiblePerfectGas.H.
Constructor & Destructor Documentation
incompressiblePerfectGas() [1/3]
template<class Specie > incompressiblePerfectGas (const Specie & sp, const scalar pRef) inline
Definition at line 26 of file incompressiblePerfectGasI.H.
incompressiblePerfectGas() [2/3]
template<class Specie > incompressiblePerfectGas (const dictionary & dict) explicit
Definition at line 27 of file incompressiblePerfectGas.C.
incompressiblePerfectGas() [3/3]
template<class Specie > incompressiblePerfectGas (const word & name, const incompressiblePerfectGas< Specie > &) inline
Member Function Documentation
clone()
template<class Specie > Foam::autoPtr< Foam::incompressiblePerfectGas< Specie > > clone () const inline
Definition at line 51 of file incompressiblePerfectGasI.H.
References Foam::New().
New()
template<class Specie > Foam::autoPtr< Foam::incompressiblePerfectGas< Specie > > New (const dictionary & dict) inline static
Definition at line 59 of file incompressiblePerfectGasI.H.
References dict, and Foam::New().
typeName()
template<class Specie > static word typeName () inline static
Definition at line 130 of file incompressiblePerfectGas.H.
rho()
template<class Specie > Foam::scalar rho (scalar p, scalar T) const inline
Definition at line 71 of file incompressiblePerfectGasI.H.
References R, and T.
H()
template<class Specie > Foam::scalar H (const scalar p, const scalar T) const inline
Definition at line 82 of file incompressiblePerfectGasI.H.
Cp()
template<class Specie > Foam::scalar Cp (scalar p, scalar T) const inline
Definition at line 93 of file incompressiblePerfectGasI.H.
E()
template<class Specie > Foam::scalar E (const scalar p, const scalar T) const inline
Definition at line 104 of file incompressiblePerfectGasI.H.
Cv()
template<class Specie > Foam::scalar Cv (scalar p, scalar T) const inline
Definition at line 115 of file incompressiblePerfectGasI.H.
S()
template<class Specie > Foam::scalar S (const scalar p, const scalar T) const inline
Definition at line 126 of file incompressiblePerfectGasI.H.
psi()
template<class Specie > Foam::scalar psi (scalar p, scalar T) const inline
Definition at line 137 of file incompressiblePerfectGasI.H.
Z()
template<class Specie > Foam::scalar Z (scalar p, scalar T) const inline
Definition at line 148 of file incompressiblePerfectGasI.H.
CpMCv()
template<class Specie > Foam::scalar CpMCv (scalar p, scalar T) const inline
Definition at line 159 of file incompressiblePerfectGasI.H.
write()
template<class Specie > void write (Ostream & os) const
Definition at line 40 of file incompressiblePerfectGas.C.
References Ostream::beginBlock(), Ostream::endBlock(), os(), and Ostream::writeEntry().
operator+=()
template<class Specie > void operator+= (const incompressiblePerfectGas< Specie > &) inline
Definition at line 172 of file incompressiblePerfectGasI.H.
References Foam::mag(), and Y.
operator*=()
template<class Specie > void operator*= (const scalar s) inline
Definition at line 191 of file incompressiblePerfectGasI.H.
References s().
Friends And Related Symbol Documentation
operator+
template<class Specie > incompressiblePerfectGas operator+ (const incompressiblePerfectGas< Specie > & , const incompressiblePerfectGas< Specie > &) friend
operator*
template<class Specie > incompressiblePerfectGas operator* (const scalar s, const incompressiblePerfectGas< Specie > &) friend
operator==
template<class Specie > incompressiblePerfectGas operator== (const incompressiblePerfectGas< Specie > & , const incompressiblePerfectGas< Specie > &) friend
operator<<
template<class Specie > Ostream & operator<< (Ostream & , const incompressiblePerfectGas< Specie > &) friend
Member Data Documentation
incompressible
template<class Specie > const bool incompressible = true static
Definition at line 141 of file incompressiblePerfectGas.H.
isochoric
template<class Specie > const bool isochoric = false static
Definition at line 144 of file incompressiblePerfectGas.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/equationOfState/incompressiblePerfectGas/incompressiblePerfectGas.H
src/thermophysicalModels/specie/equationOfState/incompressiblePerfectGas/incompressiblePerfectGas.C
src/thermophysicalModels/specie/equationOfState/incompressiblePerfectGas/incompressiblePerfectGasI.H