OpenFOAM: polyMeshTetDecomposition Class Reference
polyMeshTetDecomposition Class Reference
Tools for performing the minimum decomposition of faces of the mesh into triangles so that the cells may be tet decomposed. Includes functions for finding variable face starting (base) points on each face to avoid the decomposition of cells into tets that have negative or zero volume.
#include <polyMeshTetDecomposition.H>
Static Public Member Functions
static scalar minQuality (const polyMesh &mesh, const point &cC, const label fI, const bool isOwner, const label faceBasePtI)
static scalar minQuality (const polyMesh &mesh, const label facei, const label faceBasePtI)
static label findSharedBasePoint (const polyMesh &mesh, label fI, const point &nCc, scalar tol, bool report=false)
static label findSharedBasePoint (const polyMesh &mesh, label fI, scalar tol, bool report=false)
static label findBasePoint (const polyMesh &mesh, label fI, scalar tol, bool report=false)
static labelList findFaceBasePts (const polyMesh &mesh, scalar tol=minTetQuality, bool report=false)
static bool checkFaceTets (const polyMesh &mesh, scalar tol=minTetQuality, const bool report=false, labelHashSet *setPtr=nullptr)
static List< tetIndices > faceTetIndices (const polyMesh &mesh, label fI, label cI)
static List< tetIndices > cellTetIndices (const polyMesh &mesh, label cI)
static tetIndices findTet (const polyMesh &mesh, label cI, const point &pt)
static labelList adjustTetBasePtIs (const polyMesh &mesh, const bool report=false)
Static Public Attributes
static const scalar minTetQuality = sqr(SMALL)
Detailed Description
Tools for performing the minimum decomposition of faces of the mesh into triangles so that the cells may be tet decomposed. Includes functions for finding variable face starting (base) points on each face to avoid the decomposition of cells into tets that have negative or zero volume.
Source files
polyMeshTetDecomposition.H
polyMeshTetDecomposition.C
Definition at line 54 of file polyMeshTetDecomposition.H.
Member Function Documentation
minQuality() [1/2]
Foam::scalar minQuality (const polyMesh & mesh, const point & cC, const label fI, const bool isOwner, const label faceBasePtI) static
Definition at line 34 of file polyMeshTetDecomposition.C.
References f(), mesh, tetrahedron< Point, PointRef >::quality(), and UPtrList< T >::size().
minQuality() [2/2]
Foam::scalar minQuality (const polyMesh & mesh, const label facei, const label faceBasePtI) static
Definition at line 87 of file polyMeshTetDecomposition.C.
References primitiveMesh::cellCentres(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), primitiveMesh::isInternalFace(), and mesh.
findSharedBasePoint() [1/2]
Foam::label findSharedBasePoint (const polyMesh & mesh, label fI, const point & nCc, scalar tol, bool report = false) static
Definition at line 126 of file polyMeshTetDecomposition.C.
References primitiveMesh::cellCentres(), f(), polyMesh::faceOwner(), polyMesh::faces(), forAll, mesh, Foam::min(), and pFaces.
Referenced by polyMeshGeometry::checkFaceTets().
findSharedBasePoint() [2/2]
Foam::label findSharedBasePoint (const polyMesh & mesh, label fI, scalar tol, bool report = false) static
Definition at line 162 of file polyMeshTetDecomposition.C.
References primitiveMesh::cellCentres(), polyMesh::faceNeighbour(), and mesh.
findBasePoint()
Foam::label findBasePoint (const polyMesh & mesh, label fI, scalar tol, bool report = false) static
Definition at line 181 of file polyMeshTetDecomposition.C.
References primitiveMesh::cellCentres(), f(), polyMesh::faceOwner(), polyMesh::faces(), forAll, mesh, and pFaces.
Referenced by polyMeshGeometry::checkFaceTets().
findFaceBasePts()
Foam::labelList findFaceBasePts (const polyMesh & mesh, scalar tol = minTetQuality, bool report = false) static
Definition at line 217 of file polyMeshTetDecomposition.C.
References Foam::abort(), polyMesh::boundaryMesh(), primitiveMesh::cellCentres(), coupled(), primitiveMesh::faceCentres(), polyMesh::faceOwner(), polyMesh::faces(), Foam::FatalError, FatalErrorInFunction, mesh, primitiveMesh::nBoundaryFaces(), primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), patches, UPtrList< T >::size(), syncTools::swapBoundaryFacePositions(), and syncTools::syncBoundaryFaceList().
Referenced by polyMesh::tetBasePtIs().
checkFaceTets()
bool checkFaceTets (const polyMesh & mesh, scalar tol = minTetQuality, const bool report = false, labelHashSet * setPtr = nullptr) static
Definition at line 376 of file polyMeshTetDecomposition.C.
References polyMesh::boundaryMesh(), primitiveMesh::cellCentres(), coupled(), Foam::endl(), f(), primitiveMesh::faceCentres(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), polyMesh::faces(), forAll, Foam::Info, primitiveMesh::isInternalFace(), mesh, primitiveMesh::nBoundaryFaces(), primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), p, patches, polyMesh::points(), Foam::reduce(), and syncTools::swapBoundaryFacePositions().
Referenced by wallBoundedStreamLine::read().
faceTetIndices()
Foam::List< Foam::tetIndices > faceTetIndices (const polyMesh & mesh, label fI, label cI) static
Definition at line 534 of file polyMeshTetDecomposition.C.
References f(), polyMesh::faces(), mesh, pFaces, and UList< T >::size().
Referenced by cellPointWeight::findTriangle(), and FreeStream< CloudType >::inflow().
cellTetIndices()
Foam::List< Foam::tetIndices > cellTetIndices (const polyMesh & mesh, label cI) static
Definition at line 558 of file polyMeshTetDecomposition.C.
References PtrList< T >::append(), primitiveMesh::cells(), polyMesh::faces(), mesh, pFaces, and UPtrList< T >::size().
Referenced by Dual< Type >::Dual(), cellPointWeight::findTetrahedron(), momentOfInertia::meshInertia(), Moment< Type >::Moment(), and patchInjectionBase::setPositionAndCell().
findTet()
Foam::tetIndices findTet (const polyMesh & mesh, label cI, const point & pt) static
Definition at line 587 of file polyMeshTetDecomposition.C.
References primitiveMesh::cells(), f(), polyMesh::faces(), mesh, pFaces, and UList< T >::size().
Referenced by polyMesh::findTetFacePt().
adjustTetBasePtIs()
Foam::labelList adjustTetBasePtIs (const polyMesh & mesh, const bool report = false) static
Definition at line 629 of file polyMeshTetDecomposition.C.
References cells, primitiveMesh::cells(), PtrList< T >::clear(), Foam::endl(), Foam::exit(), f(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), polyMesh::faces(), Foam::FatalError, FatalErrorInFunction, UList< T >::fcValue(), forAll, forAllConstIters, primitiveMesh::isInternalFace(), mesh, Foam::nl, polyMesh::points(), Foam::Pout, UList< T >::rcValue(), Foam::returnReduceOr(), PtrList< T >::set(), UPtrList< T >::size(), syncTools::syncFaceList(), UPtrList< T >::test(), and polyMesh::tetBasePtIs().
Referenced by isoSurfaceTopo::isoSurfaceTopo().
Member Data Documentation
minTetQuality
const Foam::scalar minTetQuality = sqr(SMALL) static
Definition at line 61 of file polyMeshTetDecomposition.H.
Referenced by wallBoundedStreamLine::read().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/polyMeshTetDecomposition/polyMeshTetDecomposition.H
src/OpenFOAM/meshes/polyMesh/polyMeshTetDecomposition/polyMeshTetDecomposition.C