OpenFOAM: atmAlphatkWallFunctionFvPatchScalarField Class Reference
atmAlphatkWallFunctionFvPatchScalarField Class Reference
This boundary condition provides a wall constraint on the kinematic turbulent thermal conductivity (i.e. alphat) for atmospheric boundary layer modelling. It assumes a logarithmic distribution of the potential temperature within the first cell.
#include <atmAlphatkWallFunctionFvPatchScalarField.H>
Public Member Functions
TypeName ("atmAlphatkWallFunction")
atmAlphatkWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
atmAlphatkWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
atmAlphatkWallFunctionFvPatchScalarField (const atmAlphatkWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
atmAlphatkWallFunctionFvPatchScalarField (const atmAlphatkWallFunctionFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
atmAlphatkWallFunctionFvPatchScalarField (const atmAlphatkWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual void updateCoeffs ()
virtual void autoMap (const fvPatchFieldMapper &)
virtual void rmap (const fvPatchScalarField &, const labelList &)
virtual void write (Ostream &) const
Protected Member Functions
virtual void checkType ()
void writeLocalEntries (Ostream &) const
Protected Attributes
const scalar Cmu_
const scalar kappa_
autoPtr< Function1< scalar > > Pr_
autoPtr< PatchFunction1< scalar > > Prt_
autoPtr< PatchFunction1< scalar > > z0_
Static Protected Attributes
static scalar tolerance_ = 0.01
static label maxIters_ = 10
Detailed Description
This boundary condition provides a wall constraint on the kinematic turbulent thermal conductivity (i.e. alphat) for atmospheric boundary layer modelling. It assumes a logarithmic distribution of the potential temperature within the first cell.
Required fields:
  alphat    | Kinematic turbulent thermal conductivity    [m2/s]
Usage
Example of the boundary condition specification:
<patchName>
{
    // Mandatory entries
    type            atmAlphatkWallFunction;
    Pr              <Function1<scalar>>;
    Prt             <PatchFunction1<scalar>>;
    z0              <PatchFunction1<scalar>>;
    // Optional entries
    Cmu             <scalar>;
    kappa           <scalar>;
    // Inherited entries
    ...
}
where the entries mean:
Property Description Type Reqd Deflt
type Type name: atmAlphatkWallFunction word yes -
Pr Molecular Prandtl number Function1<scalar> yes -
Prt Turbulent Prandtl number PatchFunction1<scalar> yes -
z0 Surface roughness length [m] PatchFunction1<scalar> yes -
Cmu Empirical model constant scalar no 0.09
kappa von Kármán constant scalar no 0.41
The inherited entries are elaborated in:
fixedValueFvPatchField.H
Function1.H
PatchFunction1.H
Source files
atmAlphatkWallFunctionFvPatchScalarField.H
atmAlphatkWallFunctionFvPatchScalarField.C
Definition at line 140 of file atmAlphatkWallFunctionFvPatchScalarField.H.
Constructor & Destructor Documentation
atmAlphatkWallFunctionFvPatchScalarField() [1/5]
atmAlphatkWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 80 of file atmAlphatkWallFunctionFvPatchScalarField.C.
References atmAlphatkWallFunctionFvPatchScalarField::checkType().
atmAlphatkWallFunctionFvPatchScalarField() [2/5]
atmAlphatkWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 118 of file atmAlphatkWallFunctionFvPatchScalarField.C.
References atmAlphatkWallFunctionFvPatchScalarField::checkType().
atmAlphatkWallFunctionFvPatchScalarField() [3/5]
atmAlphatkWallFunctionFvPatchScalarField (const atmAlphatkWallFunctionFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 98 of file atmAlphatkWallFunctionFvPatchScalarField.C.
References atmAlphatkWallFunctionFvPatchScalarField::checkType().
atmAlphatkWallFunctionFvPatchScalarField() [4/5]
atmAlphatkWallFunctionFvPatchScalarField (const atmAlphatkWallFunctionFvPatchScalarField & wfpsf)
Definition at line 153 of file atmAlphatkWallFunctionFvPatchScalarField.C.
References atmAlphatkWallFunctionFvPatchScalarField::checkType().
atmAlphatkWallFunctionFvPatchScalarField() [5/5]
atmAlphatkWallFunctionFvPatchScalarField (const atmAlphatkWallFunctionFvPatchScalarField & wfpsf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 170 of file atmAlphatkWallFunctionFvPatchScalarField.C.
References atmAlphatkWallFunctionFvPatchScalarField::checkType().
Member Function Documentation
checkType()
void checkType () protected virtual
Definition at line 41 of file atmAlphatkWallFunctionFvPatchScalarField.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, and Foam::nl.
Referenced by atmAlphatkWallFunctionFvPatchScalarField::atmAlphatkWallFunctionFvPatchScalarField(), atmAlphatkWallFunctionFvPatchScalarField::atmAlphatkWallFunctionFvPatchScalarField(), atmAlphatkWallFunctionFvPatchScalarField::atmAlphatkWallFunctionFvPatchScalarField(), atmAlphatkWallFunctionFvPatchScalarField::atmAlphatkWallFunctionFvPatchScalarField(), and atmAlphatkWallFunctionFvPatchScalarField::atmAlphatkWallFunctionFvPatchScalarField().
writeLocalEntries()
void writeLocalEntries (Ostream & os) const protected
Definition at line 55 of file atmAlphatkWallFunctionFvPatchScalarField.C.
References atmAlphatkWallFunctionFvPatchScalarField::Cmu_, atmAlphatkWallFunctionFvPatchScalarField::kappa_, os(), atmAlphatkWallFunctionFvPatchScalarField::Pr_, atmAlphatkWallFunctionFvPatchScalarField::Prt_, and atmAlphatkWallFunctionFvPatchScalarField::z0_.
Referenced by atmAlphatkWallFunctionFvPatchScalarField::write().
TypeName()
TypeName ("atmAlphatkWallFunction")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 220 of file atmAlphatkWallFunctionFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 236 of file atmAlphatkWallFunctionFvPatchScalarField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 190 of file atmAlphatkWallFunctionFvPatchScalarField.C.
References atmAlphatkWallFunctionFvPatchScalarField::Cmu_, e, Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, IOobject::groupName(), k, atmAlphatkWallFunctionFvPatchScalarField::kappa_, Foam::log(), Foam::max(), Foam::pow025(), Pr(), atmAlphatkWallFunctionFvPatchScalarField::Pr_, turbulenceModel::propertiesName, Prt(), atmAlphatkWallFunctionFvPatchScalarField::Prt_, Foam::sqrt(), fvPatchField< Type >::updateCoeffs(), y, and atmAlphatkWallFunctionFvPatchScalarField::z0_.
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Definition at line 273 of file atmAlphatkWallFunctionFvPatchScalarField.C.
References atmAlphatkWallFunctionFvPatchScalarField::Prt_, and atmAlphatkWallFunctionFvPatchScalarField::z0_.
rmap()
void rmap (const fvPatchScalarField & ptf, const labelList & addr) virtual
Definition at line 291 of file atmAlphatkWallFunctionFvPatchScalarField.C.
References atmAlphatkWallFunctionFvPatchScalarField::Prt_, and atmAlphatkWallFunctionFvPatchScalarField::z0_.
write()
void write (Ostream & os) const virtual
Definition at line 313 of file atmAlphatkWallFunctionFvPatchScalarField.C.
References os(), fvPatchField< Type >::write(), atmAlphatkWallFunctionFvPatchScalarField::writeLocalEntries(), and fvPatchField< Type >::writeValueEntry().
Member Data Documentation
Cmu_
const scalar Cmu_ protected
Definition at line 149 of file atmAlphatkWallFunctionFvPatchScalarField.H.
Referenced by atmAlphatkWallFunctionFvPatchScalarField::updateCoeffs(), and atmAlphatkWallFunctionFvPatchScalarField::writeLocalEntries().
kappa_
const scalar kappa_ protected
Definition at line 152 of file atmAlphatkWallFunctionFvPatchScalarField.H.
Referenced by atmAlphatkWallFunctionFvPatchScalarField::updateCoeffs(), and atmAlphatkWallFunctionFvPatchScalarField::writeLocalEntries().
Pr_
autoPtr<Function1<scalar> > Pr_ protected
Definition at line 155 of file atmAlphatkWallFunctionFvPatchScalarField.H.
Referenced by atmAlphatkWallFunctionFvPatchScalarField::updateCoeffs(), and atmAlphatkWallFunctionFvPatchScalarField::writeLocalEntries().
Prt_
autoPtr<PatchFunction1<scalar> > Prt_ protected
Definition at line 158 of file atmAlphatkWallFunctionFvPatchScalarField.H.
Referenced by atmAlphatkWallFunctionFvPatchScalarField::autoMap(), atmAlphatkWallFunctionFvPatchScalarField::rmap(), atmAlphatkWallFunctionFvPatchScalarField::updateCoeffs(), and atmAlphatkWallFunctionFvPatchScalarField::writeLocalEntries().
z0_
autoPtr<PatchFunction1<scalar> > z0_ protected
Definition at line 161 of file atmAlphatkWallFunctionFvPatchScalarField.H.
Referenced by atmAlphatkWallFunctionFvPatchScalarField::autoMap(), atmAlphatkWallFunctionFvPatchScalarField::rmap(), atmAlphatkWallFunctionFvPatchScalarField::updateCoeffs(), and atmAlphatkWallFunctionFvPatchScalarField::writeLocalEntries().
tolerance_
scalar tolerance_ = 0.01 static protected
Definition at line 166 of file atmAlphatkWallFunctionFvPatchScalarField.H.
maxIters_
label maxIters_ = 10 static protected
Definition at line 167 of file atmAlphatkWallFunctionFvPatchScalarField.H.
The documentation for this class was generated from the following files:
src/atmosphericModels/derivedFvPatchFields/wallFunctions/atmAlphatkWallFunction/atmAlphatkWallFunctionFvPatchScalarField.H
src/atmosphericModels/derivedFvPatchFields/wallFunctions/atmAlphatkWallFunction/atmAlphatkWallFunctionFvPatchScalarField.C