OpenFOAM: Lee< Thermo, OtherThermo > Class Template Reference
Lee< Thermo, OtherThermo > Class Template Reference
Mass transfer Lee model. Simple model driven by field value difference as:
#include <Lee.H>
Public Member Functions
TypeName ("Lee")
Lee (const dictionary &dict, const phasePair &pair)
virtual ~Lee ()=default
virtual tmp< volScalarField > Kexp (const volScalarField &field)
virtual tmp< volScalarField > KSp (label modelVariable, const volScalarField &field)
virtual tmp< volScalarField > KSu (label modelVariable, const volScalarField &field)
virtual const dimensionedScalar & Tactivate () const noexcept
virtual bool includeDivU () const noexcept
Public Member Functions inherited from InterfaceCompositionModel< Thermo, OtherThermo >
InterfaceCompositionModel (const dictionary &dict, const phasePair &pair)
virtual ~InterfaceCompositionModel ()=default
virtual tmp< volScalarField > dY (const word &speciesName, const volScalarField &Tf) const
virtual tmp< volScalarField > Yf (const word &speciesName, const volScalarField &Tf) const
virtual tmp< volScalarField > Dfrom (const word &speciesName) const
virtual tmp< volScalarField > Dto (const word &speciesName) const
virtual tmp< volScalarField > L (const word &speciesName, const volScalarField &Tf) const
InterfaceCompositionModel (const dictionary &dict, const phasePair &pair)
~InterfaceCompositionModel ()=default
virtual tmp< volScalarField > dY (const word &speciesName, const volScalarField &Tf) const
virtual tmp< volScalarField > D (const word &speciesName) const
virtual tmp< volScalarField > L (const word &speciesName, const volScalarField &Tf) const
virtual void addMDotL (const volScalarField &K, const volScalarField &Tf, volScalarField &mDotL, volScalarField &mDotLPrime) const
template<class ThermoType >
const Foam::multiComponentMixture< ThermoType >::thermoType & getLocalThermo (const word &speciesName, const multiComponentMixture< ThermoType > &globalThermo) const
template<class ThermoType >
const Foam::pureMixture< ThermoType >::thermoType & getLocalThermo (const word &speciesName, const pureMixture< ThermoType > &globalThermo) const
template<class ThermoType >
Foam::tmp< Foam::volScalarField > getSpecieMassFraction (const word &speciesName, const multiComponentMixture< ThermoType > &mixture) const
template<class ThermoType >
Foam::tmp< Foam::volScalarField > getSpecieMassFraction (const word &speciesName, const pureMixture< ThermoType > &mixture) const
template<class ThermoType >
Foam::tmp< Foam::volScalarField > MwMixture (const pureMixture< ThermoType > &mixture) const
template<class ThermoType >
Foam::tmp< Foam::volScalarField > MwMixture (const multiComponentMixture< ThermoType > &mixture) const
Public Member Functions inherited from interfaceCompositionModel
TypeName ("interfaceCompositionModel")
declareRunTimeSelectionTable (autoPtr, interfaceCompositionModel, dictionary,(const dictionary &dict, const phasePair &pair),(dict, pair))
interfaceCompositionModel (const dictionary &dict, const phasePair &pair)
virtual ~interfaceCompositionModel ()=default
const word transferSpecie () const
const phasePair & pair () const
const multiphaseInterSystem & fluid () const
bool includeVolChange ()
const word & variable () const
Additional Inherited Members
Public Types inherited from interfaceCompositionModel
enum modelVariable { T , P , Y , alpha }
Static Public Member Functions inherited from interfaceCompositionModel
static autoPtr< interfaceCompositionModel > New (const dictionary &dict, const phasePair &pair)
Protected Member Functions inherited from InterfaceCompositionModel< Thermo, OtherThermo >
template<class ThermoType >
const pureMixture< ThermoType >::thermoType & getLocalThermo (const word &speciesName, const pureMixture< ThermoType > &globalThermo) const
template<class ThermoType >
const multiComponentMixture< ThermoType >::thermoType & getLocalThermo (const word &speciesName, const multiComponentMixture< ThermoType > &globalThermo) const
template<class ThermoType >
tmp< volScalarField > getSpecieMassFraction (const word &speciesName, const pureMixture< ThermoType > &thermo) const
template<class ThermoType >
tmp< volScalarField > getSpecieMassFraction (const word &speciesName, const multiComponentMixture< ThermoType > &thermo) const
template<class ThermoType >
tmp< volScalarField > MwMixture (const pureMixture< ThermoType > &thermo) const
template<class ThermoType >
tmp< volScalarField > MwMixture (const multiComponentMixture< ThermoType > &) const
template<class ThermoType >
const pureMixture< ThermoType >::thermoType & getLocalThermo (const word &speciesName, const pureMixture< ThermoType > &globalThermo) const
template<class ThermoType >
const multiComponentMixture< ThermoType >::thermoType & getLocalThermo (const word &speciesName, const multiComponentMixture< ThermoType > &globalThermo) const
Protected Attributes inherited from InterfaceCompositionModel< Thermo, OtherThermo >
const Thermo & fromThermo_
const OtherThermo & toThermo_
const dimensionedScalar Le_
const Thermo & thermo_
const OtherThermo & otherThermo_
Protected Attributes inherited from interfaceCompositionModel
modelVariable modelVariable_
bool includeVolChange_
const phasePair & pair_
word speciesName_
const fvMesh & mesh_
Static Protected Attributes inherited from interfaceCompositionModel
static const Enum< modelVariable > modelVariableNames_
Detailed Description
template<class Thermo, class OtherThermo>
class Foam::meltingEvaporationModels::Lee< Thermo, OtherThermo >
Mass transfer Lee model. Simple model driven by field value difference as:
where C is a model constant.
if C > 0:
for
and
for
if C < 0:
for
and
for
Based on the reference:
W. H. Lee. "A Pressure Iteration Scheme for Two-Phase Modeling". Technical Report LA-UR 79-975. Los Alamos Scientific Laboratory, Los Alamos, New Mexico. 1979.
Usage
Example usage:
    massTransferModel
    (
        (solid to liquid)
        {
            type            Lee;
            C               40;
            Tactivate       302.78;
        }
    );
Where:
Property Description Required Default value
Tactivate Activation temperature yes
C Model constant yes
includeVolChange Volumen change no yes
species Specie name on the other phase no none
Source files
Lee.H
Lee.C
Definition at line 127 of file Lee.H.
Constructor & Destructor Documentation
Lee()
template<class Thermo , class OtherThermo > Lee (const dictionary & dict, const phasePair & pair)
Definition at line 28 of file Lee.C.
References Foam::dimTemperature, Foam::dimTime, and Foam::inv().
~Lee()
template<class Thermo , class OtherThermo > virtual ~Lee () virtual default
Member Function Documentation
TypeName()
template<class Thermo , class OtherThermo > TypeName ("Lee< Thermo, OtherThermo >")
Kexp()
template<class Thermo , class OtherThermo > Foam::tmp< Foam::volScalarField > Kexp (const volScalarField & field) virtual
Implements interfaceCompositionModel.
Definition at line 45 of file Lee.C.
References Foam::clamp(), Foam::pos(), rho, and Foam::sign().
KSp()
template<class Thermo , class OtherThermo > Foam::tmp< Foam::volScalarField > KSp (label modelVariable, const volScalarField & field) virtual
Implements interfaceCompositionModel.
Definition at line 83 of file Lee.C.
References Foam::clamp(), Foam::pos(), rho, and Foam::sign().
KSu()
template<class Thermo , class OtherThermo > Foam::tmp< Foam::volScalarField > KSu (label modelVariable, const volScalarField & field) virtual
Implements interfaceCompositionModel.
Definition at line 126 of file Lee.C.
References Foam::clamp(), Foam::pos(), rho, and Foam::sign().
Tactivate()
template<class Thermo , class OtherThermo > virtual const dimensionedScalar & Tactivate () const inline virtual noexcept
Implements interfaceCompositionModel.
Definition at line 186 of file Lee.H.
includeDivU()
template<class Thermo , class OtherThermo > virtual bool includeDivU () const inline virtual noexcept
Reimplemented from interfaceCompositionModel.
Definition at line 193 of file Lee.H.
The documentation for this class was generated from the following files:
src/phaseSystemModels/multiphaseInter/phasesSystem/massTransferModels/Lee/Lee.H
src/phaseSystemModels/multiphaseInter/phasesSystem/massTransferModels/Lee/Lee.C