OpenFOAM: VakhrushevEfremov Class Reference
VakhrushevEfremov Class Reference
Aspect ratio model of Vakhrushev and Efremov.
#include <VakhrushevEfremov.H>
Public Member Functions
TypeName ("VakhrushevEfremov")
VakhrushevEfremov (const dictionary &dict, const phasePair &pair)
virtual ~VakhrushevEfremov ()
virtual tmp< volScalarField > E () const
TypeName ("VakhrushevEfremov")
VakhrushevEfremov (const dictionary &dict, const phasePair &pair)
virtual ~VakhrushevEfremov ()
virtual tmp< volScalarField > E () const
Public Member Functions inherited from aspectRatioModel
TypeName ("aspectRatioModel")
declareRunTimeSelectionTable (autoPtr, aspectRatioModel, dictionary,(const dictionary &dict, const phasePair &pair),(dict, pair))
aspectRatioModel (const dictionary &dict, const phasePair &pair)
virtual ~aspectRatioModel ()=default
TypeName ("aspectRatioModel")
declareRunTimeSelectionTable (autoPtr, aspectRatioModel, dictionary,(const dictionary &dict, const phasePair &pair),(dict, pair))
aspectRatioModel (const dictionary &dict, const phasePair &pair)
virtual ~aspectRatioModel ()=default
Additional Inherited Members
Static Public Member Functions inherited from aspectRatioModel
static autoPtr< aspectRatioModel > New (const dictionary &dict, const phasePair &pair)
static autoPtr< aspectRatioModel > New (const dictionary &dict, const phasePair &pair)
Protected Attributes inherited from aspectRatioModel
const phasePair & pair_
Detailed Description
Aspect ratio model of Vakhrushev and Efremov.
Reference:
    Vakhrushev, I. A., & Efremov, G. I. (1970).
    Interpolation formula for computing the velocities of single gas bubbles
    in liquids.
    Chemistry and Technology of Fuels and Oils, 6(5), 376-379.
Source files
VakhrushevEfremov.H
VakhrushevEfremov.C
Definition at line 56 of file VakhrushevEfremov.H.
Constructor & Destructor Documentation
VakhrushevEfremov() [1/2]
VakhrushevEfremov (const dictionary & dict, const phasePair & pair)
Definition at line 44 of file VakhrushevEfremov.C.
~VakhrushevEfremov() [1/2]
~VakhrushevEfremov () virtual
Definition at line 56 of file VakhrushevEfremov.C.
VakhrushevEfremov() [2/2]
VakhrushevEfremov (const dictionary & dict, const phasePair & pair)
~VakhrushevEfremov() [2/2]
virtual ~VakhrushevEfremov () virtual
Member Function Documentation
TypeName() [1/2]
TypeName ("VakhrushevEfremov")
E() [1/2]
Foam::tmp< Foam::volScalarField > E () const virtual
Implements aspectRatioModel.
Reimplemented in TomiyamaAspectRatio, and TomiyamaAspectRatio.
Definition at line 63 of file VakhrushevEfremov.C.
References Foam::log10(), Foam::max(), Foam::neg(), Foam::pos0(), Foam::pow3(), and Foam::tanh().
Referenced by TomiyamaAspectRatio::E().
TypeName() [2/2]
TypeName ("VakhrushevEfremov")
E() [2/2]
virtual tmp< volScalarField > E () const virtual
Implements aspectRatioModel.
Reimplemented in TomiyamaAspectRatio, and TomiyamaAspectRatio.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/interfacialModels/aspectRatioModels/VakhrushevEfremov/VakhrushevEfremov.H
src/phaseSystemModels/twoPhaseEuler/twoPhaseSystem/interfacialModels/aspectRatioModels/VakhrushevEfremov/VakhrushevEfremov.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/interfacialModels/aspectRatioModels/VakhrushevEfremov/VakhrushevEfremov.C
src/phaseSystemModels/twoPhaseEuler/twoPhaseSystem/interfacialModels/aspectRatioModels/VakhrushevEfremov/VakhrushevEfremov.C