OpenFOAM: colourTable Class Reference
colourTable Class Reference
Base class for generating a colour table from node points.
#include <colourTable.H>
Public Types
enum interpolationType { RGB , HSV , DIVERGING }
enum predefinedType {
COOL_WARM , COLD_HOT , FIRE , RAINBOW ,
GREYSCALE , XRAY
}
typedef Tuple2< scalar, vector > pair_type
Public Member Functions
colourTable (const List< Tuple2< scalar, vector > > &values, const interpolationType interp=interpolationType::RGB)
colourTable (List< Tuple2< scalar, vector > > &&values, const interpolationType interp=interpolationType::RGB)
colourTable (const dictionary &dict, const interpolationType interp=interpolationType::RGB)
virtual ~colourTable ()=default
vector value (const scalar x) const
List< Tuple2< scalar, vector > > table (const label nColours) const
Ostream & writeDict (Ostream &os) const
Static Public Member Functions
static const colourTable * ptr (const word &tableName)
static const colourTable * ptr (const predefinedType tbl)
static const colourTable & ref (const word &tableName)
static const colourTable & ref (const predefinedType tbl)
static autoPtr< colourTable > New (Istream &is)
static const HashPtrTable< colourTable > & tables ()
Static Public Attributes
static const Enum< interpolationType > interpolationTypeNames
static const Enum< predefinedType > predefinedNames
Detailed Description
Base class for generating a colour table from node points.
Dictionary definition
Property Description Required Default
interpolate rgb/hsv/diverging no rgb
table Node points for the colour table yes
Predefined colour tables (in "etc/colourTables") include "coolToWarm", "coldAndHot", "fire", "rainbow", "greyscale", "xray".
Source files
colourTable.H
colourTable.C
Definition at line 75 of file colourTable.H.
Member Typedef Documentation
pair_type
typedef Tuple2<scalar, vector> pair_type
Definition at line 107 of file colourTable.H.
Member Enumeration Documentation
interpolationType
enum interpolationType
Enumerator
RGB
HSV
DIVERGING
Definition at line 80 of file colourTable.H.
predefinedType
enum predefinedType
Enumerator
COOL_WARM
"coolToWarm"
COLD_HOT
"coldAndHot"
FIRE
"fire" - ParaView "Black-Body Radiation"
RAINBOW
"rainbow"
GREYSCALE
greyscale - ParaView "Grayscale"
XRAY
"xray" - ParaView "X Ray"
Definition at line 89 of file colourTable.H.
Constructor & Destructor Documentation
colourTable() [1/3]
colourTable (const List< Tuple2< scalar, vector > > & values, const interpolationType interp = interpolationType::RGB) explicit
Definition at line 41 of file colourTable.C.
colourTable() [2/3]
colourTable (List< Tuple2< scalar, vector > > && values, const interpolationType interp = interpolationType::RGB) explicit
Definition at line 52 of file colourTable.C.
colourTable() [3/3]
colourTable (const dictionary & dict, const interpolationType interp = interpolationType::RGB) explicit
Definition at line 63 of file colourTable.C.
References dict, and colourTable::interpolationTypeNames.
~colourTable()
virtual ~colourTable () virtual default
Member Function Documentation
ptr() [1/2]
const Foam::colourTable * ptr (const word & tableName) static
Definition at line 81 of file colourTables.C.
References p.
Referenced by x3dWriter::x3dWriter().
ptr() [2/2]
const Foam::colourTable * ptr (const predefinedType tbl) static
Definition at line 100 of file colourTables.C.
ref() [1/2]
const Foam::colourTable & ref (const word & tableName) static
Definition at line 106 of file colourTables.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and p.
ref() [2/2]
const Foam::colourTable & ref (const predefinedType tbl) static
Definition at line 121 of file colourTables.C.
References ref().
New()
Foam::autoPtr< Foam::colourTable > New (Istream & is) static
Definition at line 79 of file colourTable.C.
References autoPtr< T >::New().
tables()
const Foam::HashPtrTable< Foam::colourTable > & tables () static
Definition at line 70 of file colourTables.C.
value()
Foam::vector value (const scalar x) const
Definition at line 87 of file colourTable.C.
References Foam::findLower(), UPtrList< T >::first(), Foam::colourTools::interpolateDiverging(), Foam::colourTools::interpolateHSV(), Foam::colourTools::interpolateRGB(), s(), UPtrList< T >::size(), and x.
table()
Foam::List< Foam::Tuple2< Foam::scalar, Foam::vector > > table (const label nColours) const
Definition at line 143 of file colourTable.C.
References x.
writeDict()
Foam::Ostream & writeDict (Ostream & os) const
Definition at line 158 of file colourTable.C.
References Ostream::beginBlock(), Ostream::endBlock(), os(), and Ostream::writeEntry().
Member Data Documentation
interpolationTypeNames
const Foam::Enum< Foam::colourTable::interpolationType > interpolationTypeNames static
Definition at line 101 of file colourTable.H.
Referenced by colourTable::colourTable().
predefinedNames
const Foam::Enum< Foam::colourTable::predefinedType > predefinedNames static
Definition at line 104 of file colourTable.H.
Referenced by x3dWriter::x3dWriter().
The documentation for this class was generated from the following files:
src/fileFormats/colours/colourTable.H
src/fileFormats/colours/colourTable.C
src/fileFormats/colours/colourTables.C