OpenFOAM: EulerD2dt2Scheme< Type > Class Template Reference
EulerD2dt2Scheme< Type > Class Template Reference
First-order Euler implicit d2dt2 using the current and two previous time-step values.
#include <EulerD2dt2Scheme.H>
Public Member Functions
TypeName ("Euler")
EulerD2dt2Scheme (const fvMesh &mesh)
EulerD2dt2Scheme (const fvMesh &mesh, Istream &is)
const fvMesh & mesh () const
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcD2dt2 (const GeometricField< Type, fvPatchField, volMesh > &)
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcD2dt2 (const volScalarField &, const GeometricField< Type, fvPatchField, volMesh > &)
tmp< fvMatrix< Type > > fvmD2dt2 (const GeometricField< Type, fvPatchField, volMesh > &)
tmp< fvMatrix< Type > > fvmD2dt2 (const dimensionedScalar &, const GeometricField< Type, fvPatchField, volMesh > &)
tmp< fvMatrix< Type > > fvmD2dt2 (const volScalarField &, const GeometricField< Type, fvPatchField, volMesh > &)
Public Member Functions inherited from d2dt2Scheme< Type >
virtual const word & type () const =0
declareRunTimeSelectionTable (tmp, d2dt2Scheme, Istream,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
d2dt2Scheme (const fvMesh &mesh)
d2dt2Scheme (const fvMesh &mesh, Istream &)
virtual ~d2dt2Scheme ()=default
const fvMesh & mesh () const
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Additional Inherited Members
Static Public Member Functions inherited from d2dt2Scheme< Type >
static tmp< d2dt2Scheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Protected Member Functions inherited from d2dt2Scheme< Type >
d2dt2Scheme (const d2dt2Scheme &)=delete
void operator= (const d2dt2Scheme &)=delete
Protected Attributes inherited from d2dt2Scheme< Type >
const fvMesh & mesh_
Detailed Description
template<class Type>
class Foam::fv::EulerD2dt2Scheme< Type >
First-order Euler implicit d2dt2 using the current and two previous time-step values.
Source files
EulerD2dt2Scheme.H
EulerD2dt2Scheme.C
Definition at line 53 of file EulerD2dt2Scheme.H.
Constructor & Destructor Documentation
EulerD2dt2Scheme() [1/2]
template<class Type > EulerD2dt2Scheme (const fvMesh & mesh) inline
Definition at line 75 of file EulerD2dt2Scheme.H.
EulerD2dt2Scheme() [2/2]
template<class Type > EulerD2dt2Scheme (const fvMesh & mesh, Istream & is) inline
Definition at line 81 of file EulerD2dt2Scheme.H.
Member Function Documentation
TypeName()
template<class Type > TypeName ("Euler")
mesh()
template<class Type > const fvMesh & mesh () const inline
Definition at line 90 of file EulerD2dt2Scheme.H.
References d2dt2Scheme< Type >::mesh().
fvcD2dt2() [1/2]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > fvcD2dt2 (const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements d2dt2Scheme< Type >.
Definition at line 39 of file EulerD2dt2Scheme.C.
References mesh, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, Foam::sqr(), and timeName.
fvcD2dt2() [2/2]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > fvcD2dt2 (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements d2dt2Scheme< Type >.
Definition at line 116 of file EulerD2dt2Scheme.C.
References mesh, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, rho, Foam::sqr(), and timeName.
fvmD2dt2() [1/3]
template<class Type > tmp< fvMatrix< Type > > fvmD2dt2 (const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements d2dt2Scheme< Type >.
Definition at line 231 of file EulerD2dt2Scheme.C.
References Foam::dimTime, Foam::dimVol, mesh, and Foam::sqr().
fvmD2dt2() [2/3]
template<class Type > tmp< fvMatrix< Type > > fvmD2dt2 (const dimensionedScalar & rho, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements d2dt2Scheme< Type >.
Definition at line 290 of file EulerD2dt2Scheme.C.
References Foam::dimTime, Foam::dimVol, mesh, rho, and Foam::sqr().
fvmD2dt2() [3/3]
template<class Type > tmp< fvMatrix< Type > > fvmD2dt2 (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements d2dt2Scheme< Type >.
Definition at line 350 of file EulerD2dt2Scheme.C.
References Foam::dimTime, Foam::dimVol, mesh, rho, and Foam::sqr().
The documentation for this class was generated from the following files:
src/finiteVolume/finiteVolume/d2dt2Schemes/EulerD2dt2Scheme/EulerD2dt2Scheme.H
src/finiteVolume/finiteVolume/d2dt2Schemes/EulerD2dt2Scheme/EulerD2dt2Scheme.C