OpenFOAM: motionDiffusivity Class Reference
motionDiffusivity Class Reference abstract
Abstract base class for cell-centre mesh motion diffusivity.
#include <motionDiffusivity.H>
Public Member Functions
TypeName ("motionDiffusivity")
declareRunTimeSelectionTable (autoPtr, motionDiffusivity, Istream,(const fvMesh &mesh, Istream &mdData),(mesh, mdData))
motionDiffusivity (const fvMesh &mesh)
virtual ~motionDiffusivity ()
const fvMesh & mesh () const
virtual tmp< surfaceScalarField > operator() () const =0
virtual void correct ()=0
Static Public Member Functions
static autoPtr< motionDiffusivity > New (const fvMesh &mesh, Istream &mdData)
Detailed Description
Abstract base class for cell-centre mesh motion diffusivity.
Source files
motionDiffusivity.H
motionDiffusivity.C
Definition at line 47 of file motionDiffusivity.H.
Constructor & Destructor Documentation
motionDiffusivity()
motionDiffusivity (const fvMesh & mesh)
Definition at line 35 of file motionDiffusivity.C.
~motionDiffusivity()
~motionDiffusivity () virtual
Definition at line 72 of file motionDiffusivity.C.
Member Function Documentation
TypeName()
TypeName ("motionDiffusivity")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , motionDiffusivity , Istream , (const fvMesh &mesh, Istream &mdData) , (mesh, mdData))
New()
Foam::autoPtr< Foam::motionDiffusivity > New (const fvMesh & mesh, Istream & mdData) static
Definition at line 43 of file motionDiffusivity.C.
References Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, Foam::Info, and mesh.
Referenced by displacementLaplacianFvMotionSolver::diffusivity(), solidBodyDisplacementLaplacianFvMotionSolver::diffusivity(), displacementComponentLaplacianFvMotionSolver::updateMesh(), velocityComponentLaplacianFvMotionSolver::updateMesh(), displacementSBRStressFvMotionSolver::updateMesh(), and velocityLaplacianFvMotionSolver::updateMesh().
mesh()
const fvMesh & mesh () const inline
Definition at line 98 of file motionDiffusivity.H.
operator()()
virtual tmp< surfaceScalarField > operator() () const pure virtual
Implemented in fileDiffusivity, exponentialDiffusivity, quadraticDiffusivity, and uniformDiffusivity.
correct()
virtual void correct () pure virtual
Implemented in directionalDiffusivity, fileDiffusivity, inverseDistanceDiffusivity, inverseFaceDistanceDiffusivity, inversePointDistanceDiffusivity, inverseVolumeDiffusivity, exponentialDiffusivity, quadraticDiffusivity, motionDirectionalDiffusivity, and uniformDiffusivity.
The documentation for this class was generated from the following files:
src/fvMotionSolver/motionDiffusivity/motionDiffusivity/motionDiffusivity.H
src/fvMotionSolver/motionDiffusivity/motionDiffusivity/motionDiffusivity.C