OpenFOAM: solarCalculator Class Reference
solarCalculator Class Reference
A solar calculator model providing models for the solar direction and solar loads.
#include <solarCalculator.H>
Public Types
enum sunDirModel { mSunDirConstant , mSunDirTracking }
enum sunLModel { mSunLoadConstant , mSunLoadTimeDependent , mSunLoadFairWeatherConditions , mSunLoadTheoreticalMaximum }
Public Member Functions
ClassName ("solarCalculator")
solarCalculator (const dictionary &, const fvMesh &)
~solarCalculator ()=default
void correctSunDirection ()
void correctDirectSolarRad ()
void correctDiffuseSolarRad ()
tmp< scalarField > diffuseSolarRad (const vectorField &n) const
const sunDirModel & sunDirectionModel () const noexcept
const sunLModel & sunLoadModel () const noexcept
vector & direction ()
const vector & direction () const noexcept
scalar & directSolarRad ()
const scalar & directSolarRad () const noexcept
scalar & diffuseSolarRad ()
const scalar & diffuseSolarRad () const noexcept
scalar C () const noexcept
scalar beta () const noexcept
scalar theta () const noexcept
scalar groundReflectivity () const noexcept
const coordinateSystem & coord () const noexcept
scalar sunTrackingUpdateInterval () const noexcept
scalar startTime () const noexcept
Static Public Attributes
static const Enum< sunDirModel > sunDirectionModelTypeNames_
static const Enum< sunLModel > sunLModelTypeNames_
Detailed Description
A solar calculator model providing models for the solar direction and solar loads.
Available models for the solar direction:
constant: Constant sunbeam direction.
tracking: Transient model calculating sunbeam direction based on a given set of parameters.
Available models for the solar load:
constant: Constant solar load.
timeDependent: Time-dependent solar load.
fairWeather: Solar fluxes are calculated following the "Fair Weather Conditions Method from the ASHRAE Handbook".
theoreticalMaximum: Theoretically maximum solar load.
Usage
Minimal examples by using constant/radiationProperties:
sunDirectionModel - Option-1:
solarLoadCoeffs
{
    sunDirectionModel           constant;
    sunDirection                (1 0 -1);
}
where the entries mean:
Property Description Type Reqd Deflt
sunDirection Sunbeam direction vector no calculated
sunDirectionModel - Option-2:
    solarLoadCoeffs
    {
        sunDirectionModel           tracking;
        sunTrackingUpdateInterval   800;
        localStandardMeridian       9;
        startDay                    204;
        startTime                   15;
        longitude                   139.74;
        latitude                    35.658;
        gridUp                      (0 0 1);
        gridEast                    (1 0 0);
    }
where the entries mean:
Property Description Type Reqd Deflt
sunTrackingUpdateInterval
Interval to update the Sun direction
[decimal hours]
scalar yes -
localStandardMeridian
GMT (Local Zone Meridian) [decimal hours]
scalar yes -
startDay Day from 1 to 365 scalar yes -
startTime
Start time for the Sun position [decimal hours]
scalar yes -
longitude
Geographic coordinate specifying the east–west
position of a point on the surface of a planetary
body [degree]
scalar yes -
latitude
Geographic coordinate specifying the north–south
position of a point on the surface of a planetary
body [degree]
scalar yes -
gridUp Grid orientation upwards vector yes -
gridEast Grid orientation eastwards vector yes -
sunLoadModel - Option-1:
    solarLoadCoeffs
    {
        sunLoadModel                constant;
        directSolarRad              100;
        diffuseSolarRad             0;
    }
where the entries mean:
Property Description Type Reqd Deflt
directSolarRad Direct solar irradiation [W/m2] scalar yes -
diffuseSolarRad
Diffuse solar irradiation on vertical surfaces
[W/m2]
scalar yes -
sunLoadModel - Option-2:
    solarLoadCoeffs
    {
        sunLoadModel                timeDependent;
        directSolarRad              <Function1<scalar>>;
        diffuseSolarRad             <Function1<scalar>>;
    }
where the entries mean:
Property Description Type Reqd Deflt
directSolarRad
Time-series of direct solar irradiation
[W/m2]
Function1<scalar> yes -
diffuseSolarRad
Time-series of diffuse solar irradiation on
vertical surfaces [W/m2]
Function1<scalar> yes -
sunLoadModel - Option-3:
    solarLoadCoeffs
    {
        sunLoadModel                fairWeather;
        skyCloudCoverFraction       0.25;
        groundReflectivity          1.0;
        A                           0.1;
        B                           0.2;
        C                           0.058;
        beta                        0.15;
    }
where the entries mean:
Property Description Type Reqd Deflt
A
Apparent solar irradiation at air mass m = 0
scalar yes -
B
Atmospheric extinction coefficient
scalar yes -
C Solar diffusivity constant scalar yes -
groundReflectivity Ground reflectivity scalar yes -
skyCloudCoverFraction
Fraction of sky covered by clouds [0,1]
scalar no 0
beta
Solar altitude (in degrees) above the horizontal
scalar no calculated
In this model the flux is calculated as:
    directSolarRad = (1 - 0.75*skyCloudCoverFraction^3)*A/exp(B/sin(beta));
sunLoadModel - Option-4:
    solarLoadCoeffs
    {
        sunLoadModel                theoreticalMaximum;
        Setrn                       1.0;
        SunPrime                    4.0;
        groundReflectivity          1.0;
        C                           0.058;
    }
where the entries mean:
Property Description Type Reqd Deflt
Setrn
Parameter in maximum theoretical direct solar
model
scalar yes -
SunPrime
Parameter in maximum theoretical direct solar
model
scalar yes -
groundReflectivity Ground reflectivity scalar yes -
C Solar diffusivity constant scalar yes -
In this model the flux is calculated as:
    directSolarRad = Setrn*SunPrime;
Note
The sunDirectionModel:tracking can only be used in transient calculations.
The keyword sunTrackingUpdateInterval (in hours) specifies on which interval is the Sun direction updated.
The diffuse on vertical/horizontal walls and ground-reflected radiation are calculated following the ASHRAE Handbook.
The range of skyCloudCoverFraction is [0,1].
Source files
solarCalculator.H
solarCalculator.C
Definition at line 440 of file solarCalculator.H.
Member Enumeration Documentation
sunDirModel
enum sunDirModel
Enumerator
mSunDirConstant
mSunDirTracking
Definition at line 447 of file solarCalculator.H.
sunLModel
enum sunLModel
Enumerator
mSunLoadConstant
mSunLoadTimeDependent
mSunLoadFairWeatherConditions
mSunLoadTheoreticalMaximum
Definition at line 457 of file solarCalculator.H.
Constructor & Destructor Documentation
solarCalculator()
solarCalculator (const dictionary & dict, const fvMesh & mesh)
Definition at line 261 of file solarCalculator.C.
~solarCalculator()
~solarCalculator () default
Member Function Documentation
ClassName()
ClassName ("solarCalculator")
correctSunDirection()
void correctSunDirection ()
Definition at line 300 of file solarCalculator.C.
References Foam::exp(), Foam::max(), and Foam::sin().
correctDirectSolarRad()
void correctDirectSolarRad ()
Definition at line 311 of file solarCalculator.C.
correctDiffuseSolarRad()
void correctDiffuseSolarRad ()
Definition at line 320 of file solarCalculator.C.
diffuseSolarRad() [1/3]
Foam::tmp< Foam::scalarField > diffuseSolarRad (const vectorField & n) const
Definition at line 329 of file solarCalculator.C.
References forAll, n, tmp< T >::New(), Foam::sin(), UPtrList< T >::size(), Foam::sqr(), and Y.
sunDirectionModel()
const sunDirModel & sunDirectionModel () const inline noexcept
Definition at line 610 of file solarCalculator.H.
sunLoadModel()
const sunLModel & sunLoadModel () const inline noexcept
Definition at line 616 of file solarCalculator.H.
direction() [1/2]
vector & direction () inline
Definition at line 622 of file solarCalculator.H.
direction() [2/2]
const vector & direction () const inline noexcept
Definition at line 628 of file solarCalculator.H.
directSolarRad() [1/2]
scalar & directSolarRad () inline
Definition at line 634 of file solarCalculator.H.
directSolarRad() [2/2]
const scalar & directSolarRad () const inline noexcept
Definition at line 640 of file solarCalculator.H.
diffuseSolarRad() [2/3]
scalar & diffuseSolarRad () inline
Definition at line 646 of file solarCalculator.H.
diffuseSolarRad() [3/3]
const scalar & diffuseSolarRad () const inline noexcept
Definition at line 652 of file solarCalculator.H.
C()
scalar C () const inline noexcept
Definition at line 658 of file solarCalculator.H.
beta()
scalar beta () const inline noexcept
Definition at line 664 of file solarCalculator.H.
theta()
scalar theta () const inline noexcept
Definition at line 670 of file solarCalculator.H.
groundReflectivity()
scalar groundReflectivity () const inline noexcept
Definition at line 676 of file solarCalculator.H.
coord()
const coordinateSystem & coord () const inline noexcept
Definition at line 682 of file solarCalculator.H.
sunTrackingUpdateInterval()
scalar sunTrackingUpdateInterval () const inline noexcept
Definition at line 688 of file solarCalculator.H.
startTime()
scalar startTime () const inline noexcept
Definition at line 694 of file solarCalculator.H.
Member Data Documentation
sunDirectionModelTypeNames_
const Foam::Enum< Foam::solarCalculator::sunDirModel > sunDirectionModelTypeNames_ static
Definition at line 454 of file solarCalculator.H.
sunLModelTypeNames_
const Foam::Enum< Foam::solarCalculator::sunLModel > sunLModelTypeNames_ static
Definition at line 466 of file solarCalculator.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/radiation/submodels/solarCalculator/solarCalculator.H
src/thermophysicalModels/radiation/submodels/solarCalculator/solarCalculator.C