OpenFOAM: sensitivityVolBSplinesFI Class Reference
sensitivityVolBSplinesFI Class Reference
Calculation of adjoint based sensitivities at vol B-Splines control points using the FI approach.
#include <sensitivityVolBSplinesFIIncompressible.H>
Public Member Functions
TypeName ("volumetricBSplinesFI")
sensitivityVolBSplinesFI (const fvMesh &mesh, const dictionary &dict, incompressibleAdjointSolver &adjointSolver)
virtual ~sensitivityVolBSplinesFI ()=default
virtual void assembleSensitivities ()
virtual void clearSensitivities ()
virtual void write (const word &baseName=word::null)
Public Member Functions inherited from FIBase
TypeName ("volumetricBSplinesFI")
FIBase (const fvMesh &mesh, const dictionary &dict, incompressibleAdjointSolver &adjointSolver)
virtual ~FIBase ()=default
virtual bool readDict (const dictionary &dict)
virtual void accumulateIntegrand (const scalar dt)
Public Member Functions inherited from shapeSensitivities
TypeName ("shapeSensitivities")
shapeSensitivities (const fvMesh &mesh, const dictionary &dict, incompressibleAdjointSolver &adjointSolver)
virtual ~shapeSensitivities ()=default
Public Member Functions inherited from adjointSensitivity
TypeName ("adjointSensitivity")
declareRunTimeSelectionTable (autoPtr, adjointSensitivity, dictionary,(const fvMesh &mesh, const dictionary &dict, incompressibleAdjointSolver &adjointSolver),(mesh, dict, adjointSolver))
adjointSensitivity (const fvMesh &mesh, const dictionary &dict, incompressibleAdjointSolver &adjointSolver)
virtual ~adjointSensitivity ()=default
const incompressibleVars & primalVars () const
const incompressibleAdjointVars & adjointVars () const
const incompressibleAdjointSolver & adjointSolver () const
virtual const scalarField & calculateSensitivities ()
const scalarField & getSensitivities () const
tmp< volTensorField > computeGradDxDbMultiplier ()
tmp< volVectorField > adjointMeshMovementSource ()
Public Member Functions inherited from sensitivity
TypeName ("sensitivity")
sensitivity (const fvMesh &mesh, const dictionary &dict)
virtual ~sensitivity ()=default
const dictionary & dict () const
virtual void computeDerivativesSize ()
Protected Attributes
volBSplinesBase & volBSplinesBase_
vectorField flowSens_
vectorField dSdbSens_
vectorField dndbSens_
vectorField dxdbDirectSens_
vectorField dVdbSens_
vectorField distanceSens_
vectorField optionsSens_
vectorField bcSens_
fileName derivativesFolder_
Protected Attributes inherited from FIBase
volTensorField gradDxDbMult_
scalarField divDxDbMult_
vectorField optionsDxDbMult_
bool includeDistance_
autoPtr< adjointEikonalSolver > eikonalSolver_
Protected Attributes inherited from shapeSensitivities
autoPtr< boundaryVectorField > dSfdbMult_
autoPtr< boundaryVectorField > dnfdbMult_
autoPtr< boundaryVectorField > dxdbDirectMult_
autoPtr< boundaryVectorField > bcDxDbMult_
Protected Attributes inherited from adjointSensitivity
scalarField derivatives_
incompressibleAdjointSolver & adjointSolver_
const incompressibleVars & primalVars_
incompressibleAdjointVars & adjointVars_
objectiveManager & objectiveManager_
Protected Attributes inherited from sensitivity
const fvMesh & mesh_
dictionary dict_
autoPtr< volScalarField > fieldSensPtr_
Additional Inherited Members
Static Public Member Functions inherited from adjointSensitivity
static autoPtr< adjointSensitivity > New (const fvMesh &mesh, const dictionary &dict, incompressibleAdjointSolver &adjointSolver)
Protected Member Functions inherited from FIBase
void read ()
Protected Member Functions inherited from shapeSensitivities
virtual void accumulateDirectSensitivityIntegrand (const scalar dt)
virtual void accumulateBCSensitivityIntegrand (const scalar dt)
tmp< boundaryVectorField > dvdbMult () const
Detailed Description
Calculation of adjoint based sensitivities at vol B-Splines control points using the FI approach.
Source files
sensitivityVolBSplinesFIIncompressible.H
sensitivityVolBSplinesFI.C
Definition at line 53 of file sensitivityVolBSplinesFIIncompressible.H.
Constructor & Destructor Documentation
sensitivityVolBSplinesFI()
sensitivityVolBSplinesFI (const fvMesh & mesh, const dictionary & dict, incompressibleAdjointSolver & adjointSolver)
Definition at line 48 of file sensitivityVolBSplinesFIIncompressible.C.
References sensitivityVolBSplinesFI::bcSens_, adjointSensitivity::derivatives_, sensitivityVolBSplinesFI::derivativesFolder_, sensitivityVolBSplinesFI::distanceSens_, sensitivityVolBSplinesFI::dndbSens_, sensitivityVolBSplinesFI::dSdbSens_, sensitivityVolBSplinesFI::dVdbSens_, sensitivityVolBSplinesFI::dxdbDirectSens_, sensitivityVolBSplinesFI::flowSens_, volBSplinesBase::getTotalControlPointsNumber(), Foam::mkDir(), sensitivityVolBSplinesFI::optionsSens_, sensitivityVolBSplinesFI::volBSplinesBase_, and Foam::Zero.
~sensitivityVolBSplinesFI()
virtual ~sensitivityVolBSplinesFI () virtual default
Member Function Documentation
TypeName()
TypeName ("volumetricBSplinesFI")
assembleSensitivities()
void assembleSensitivities () virtual
Implements FIBase.
Definition at line 91 of file sensitivityVolBSplinesFIIncompressible.C.
References shapeSensitivities::bcDxDbMult_, sensitivityVolBSplinesFI::bcSens_, volBSplinesBase::boundControlPointMovement(), volBSplinesBase::boxesRef(), Field< Type >::component(), adjointSensitivity::derivatives_, Foam::dimless, sensitivityVolBSplinesFI::distanceSens_, Foam::fvc::div(), FIBase::divDxDbMult_, sensitivityVolBSplinesFI::dndbSens_, shapeSensitivities::dnfdbMult_, sensitivityVolBSplinesFI::dSdbSens_, shapeSensitivities::dSfdbMult_, sensitivityVolBSplinesFI::dVdbSens_, shapeSensitivities::dxdbDirectMult_, sensitivityVolBSplinesFI::dxdbDirectSens_, FIBase::eikonalSolver_, sensitivityVolBSplinesFI::flowSens_, forAll, Foam::fvc::grad(), FIBase::gradDxDbMult_, Foam::gSum(), FIBase::includeDistance_, sensitivity::mesh_, tmp< T >::New(), MeshObject< polyMesh, UpdateableMeshObject, pointMesh >::New(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, FIBase::optionsDxDbMult_, sensitivityVolBSplinesFI::optionsSens_, GeometricField< Type, PatchField, GeoMesh >::primitiveField(), FIBase::read(), T, Foam::unzipCol(), sensitivityVolBSplinesFI::volBSplinesBase_, and Foam::Zero.
clearSensitivities()
void clearSensitivities () virtual
Reimplemented from FIBase.
Definition at line 285 of file sensitivityVolBSplinesFIIncompressible.C.
References sensitivityVolBSplinesFI::bcSens_, FIBase::clearSensitivities(), sensitivityVolBSplinesFI::distanceSens_, sensitivityVolBSplinesFI::dndbSens_, sensitivityVolBSplinesFI::dSdbSens_, sensitivityVolBSplinesFI::dVdbSens_, sensitivityVolBSplinesFI::dxdbDirectSens_, sensitivityVolBSplinesFI::flowSens_, sensitivityVolBSplinesFI::optionsSens_, and VectorSpace< Form, Cmpt, Ncmpts >::zero.
write()
void write (const word & baseName = word::null) virtual
Reimplemented from shapeSensitivities.
Definition at line 300 of file sensitivityVolBSplinesFIIncompressible.C.
References adjointSensitivity::adjointVars_, sensitivityVolBSplinesFI::bcSens_, volBSplinesBase::boxesRef(), IOstream::defaultPrecision(), adjointSensitivity::derivatives_, sensitivityVolBSplinesFI::derivativesFolder_, sensitivityVolBSplinesFI::distanceSens_, sensitivityVolBSplinesFI::dndbSens_, sensitivityVolBSplinesFI::dSdbSens_, sensitivityVolBSplinesFI::dVdbSens_, sensitivityVolBSplinesFI::dxdbDirectSens_, Foam::endl(), sensitivityVolBSplinesFI::flowSens_, forAll, Foam::Info, UPstream::master(), Foam::max(), sensitivity::mesh_, Foam::name(), sensitivityVolBSplinesFI::optionsSens_, Foam::setw(), UPtrList< T >::size(), UList< T >::size(), variablesSet::solverName(), and sensitivityVolBSplinesFI::volBSplinesBase_.
Member Data Documentation
volBSplinesBase_
volBSplinesBase& volBSplinesBase_ protected
Definition at line 62 of file sensitivityVolBSplinesFIIncompressible.H.
Referenced by sensitivityVolBSplinesFI::assembleSensitivities(), sensitivityVolBSplinesFI::sensitivityVolBSplinesFI(), and sensitivityVolBSplinesFI::write().
flowSens_
vectorField flowSens_ protected
Definition at line 65 of file sensitivityVolBSplinesFIIncompressible.H.
Referenced by sensitivityVolBSplinesFI::assembleSensitivities(), sensitivityVolBSplinesFI::clearSensitivities(), sensitivityVolBSplinesFI::sensitivityVolBSplinesFI(), and sensitivityVolBSplinesFI::write().
dSdbSens_
vectorField dSdbSens_ protected
Definition at line 68 of file sensitivityVolBSplinesFIIncompressible.H.
Referenced by sensitivityVolBSplinesFI::assembleSensitivities(), sensitivityVolBSplinesFI::clearSensitivities(), sensitivityVolBSplinesFI::sensitivityVolBSplinesFI(), and sensitivityVolBSplinesFI::write().
dndbSens_
vectorField dndbSens_ protected
Definition at line 71 of file sensitivityVolBSplinesFIIncompressible.H.
Referenced by sensitivityVolBSplinesFI::assembleSensitivities(), sensitivityVolBSplinesFI::clearSensitivities(), sensitivityVolBSplinesFI::sensitivityVolBSplinesFI(), and sensitivityVolBSplinesFI::write().
dxdbDirectSens_
vectorField dxdbDirectSens_ protected
Definition at line 75 of file sensitivityVolBSplinesFIIncompressible.H.
Referenced by sensitivityVolBSplinesFI::assembleSensitivities(), sensitivityVolBSplinesFI::clearSensitivities(), sensitivityVolBSplinesFI::sensitivityVolBSplinesFI(), and sensitivityVolBSplinesFI::write().
dVdbSens_
vectorField dVdbSens_ protected
Definition at line 78 of file sensitivityVolBSplinesFIIncompressible.H.
Referenced by sensitivityVolBSplinesFI::assembleSensitivities(), sensitivityVolBSplinesFI::clearSensitivities(), sensitivityVolBSplinesFI::sensitivityVolBSplinesFI(), and sensitivityVolBSplinesFI::write().
distanceSens_
vectorField distanceSens_ protected
Definition at line 81 of file sensitivityVolBSplinesFIIncompressible.H.
Referenced by sensitivityVolBSplinesFI::assembleSensitivities(), sensitivityVolBSplinesFI::clearSensitivities(), sensitivityVolBSplinesFI::sensitivityVolBSplinesFI(), and sensitivityVolBSplinesFI::write().
optionsSens_
vectorField optionsSens_ protected
Definition at line 84 of file sensitivityVolBSplinesFIIncompressible.H.
Referenced by sensitivityVolBSplinesFI::assembleSensitivities(), sensitivityVolBSplinesFI::clearSensitivities(), sensitivityVolBSplinesFI::sensitivityVolBSplinesFI(), and sensitivityVolBSplinesFI::write().
bcSens_
vectorField bcSens_ protected
Definition at line 87 of file sensitivityVolBSplinesFIIncompressible.H.
Referenced by sensitivityVolBSplinesFI::assembleSensitivities(), sensitivityVolBSplinesFI::clearSensitivities(), sensitivityVolBSplinesFI::sensitivityVolBSplinesFI(), and sensitivityVolBSplinesFI::write().
derivativesFolder_
fileName derivativesFolder_ protected
Definition at line 89 of file sensitivityVolBSplinesFIIncompressible.H.
Referenced by sensitivityVolBSplinesFI::sensitivityVolBSplinesFI(), and sensitivityVolBSplinesFI::write().
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/optimisation/adjointSensitivity/incompressible/sensitivityVolBSplinesFI/sensitivityVolBSplinesFIIncompressible.H
src/optimisation/adjointOptimisation/adjoint/optimisation/adjointSensitivity/incompressible/sensitivityVolBSplinesFI/sensitivityVolBSplinesFIIncompressible.C