OpenFOAM: ISAT< CompType, ThermoType > Class Template Reference
ISAT< CompType, ThermoType > Class Template Reference
Implementation of the ISAT (In-situ adaptive tabulation), for chemistry calculation.
#include <ISAT.H>
Public Member Functions
TypeName ("ISAT")
ISAT (const dictionary &chemistryProperties, TDACChemistryModel< CompType, ThermoType > &chemistry)
virtual ~ISAT ()
binaryTree< CompType, ThermoType > & chemisTree ()
const scalarField & scaleFactor () const
virtual label size ()
virtual void writePerformance ()
virtual bool retrieve (const Foam::scalarField &phiq, scalarField &Rphiq)
virtual label add (const scalarField &phiq, const scalarField &Rphiq, const scalar rho, const scalar deltaT)
virtual bool update ()
Public Member Functions inherited from chemistryTabulationMethod< CompType, ThermoType >
TypeName ("chemistryTabulationMethod")
declareRunTimeSelectionTable (autoPtr, chemistryTabulationMethod, dictionary,(const dictionary &dict, TDACChemistryModel< CompType, ThermoType > &chemistry),(dict, chemistry))
chemistryTabulationMethod (const dictionary &dict, TDACChemistryModel< CompType, ThermoType > &chemistry)
virtual ~chemistryTabulationMethod ()
bool active ()
bool log ()
bool variableTimeStep ()
scalar tolerance () const
Additional Inherited Members
Static Public Member Functions inherited from chemistryTabulationMethod< CompType, ThermoType >
static autoPtr< chemistryTabulationMethod > New (const IOdictionary &dict, TDACChemistryModel< CompType, ThermoType > &chemistry)
Protected Attributes inherited from chemistryTabulationMethod< CompType, ThermoType >
const dictionary & dict_
const dictionary coeffsDict_
Switch active_
Switch log_
TDACChemistryModel< CompType, ThermoType > & chemistry_
scalar tolerance_
Detailed Description
template<class CompType, class ThermoType>
class Foam::chemistryTabulationMethods::ISAT< CompType, ThermoType >
Implementation of the ISAT (In-situ adaptive tabulation), for chemistry calculation.
Reference:
    Pope, S. B. (1997).
    Computationally efficient implementation of combustion chemistry using
    in situ adaptive tabulation.
    Combustion Theory and Modelling, 1, 41-63.
Definition at line 53 of file ISAT.H.
Constructor & Destructor Documentation
ISAT()
template<class CompType , class ThermoType > ISAT (const dictionary & chemistryProperties, TDACChemistryModel< CompType, ThermoType > & chemistry)
Definition at line 29 of file ISAT.C.
References chemistryTabulationMethod< CompType, ThermoType >::active_, chemistry, chemistryTabulationMethod< CompType, ThermoType >::chemistry_, chemistryTabulationMethod< CompType, ThermoType >::coeffsDict_, UPtrList< T >::get(), chemistryTabulationMethod< CompType, ThermoType >::log(), Foam::log(), dictionary::readEntry(), UPtrList< T >::size(), chemistryTabulationMethod< CompType, ThermoType >::variableTimeStep(), and TDACChemistryModel< ReactionThermo, ThermoType >::Y().
~ISAT()
template<class CompType , class ThermoType > ~ISAT () virtual
Definition at line 126 of file ISAT.C.
Member Function Documentation
TypeName()
template<class CompType , class ThermoType > TypeName ("ISAT< CompType, ThermoType >")
chemisTree()
template<class CompType , class ThermoType > binaryTree< CompType, ThermoType > & chemisTree () inline
Definition at line 196 of file ISAT.H.
scaleFactor()
template<class CompType , class ThermoType > const scalarField & scaleFactor () const inline
Definition at line 201 of file ISAT.H.
size()
template<class CompType , class ThermoType > virtual label size () inline virtual
Implements chemistryTabulationMethod< CompType, ThermoType >.
Definition at line 207 of file ISAT.H.
References UPtrList< T >::size().
writePerformance()
template<class CompType , class ThermoType > void writePerformance () virtual
Implements chemistryTabulationMethod< CompType, ThermoType >.
Definition at line 602 of file ISAT.C.
References Foam::endl(), and Foam::log().
retrieve()
template<class CompType , class ThermoType > bool retrieve (const Foam::scalarField & phiq, scalarField & Rphiq) virtual
Implements chemistryTabulationMethod< CompType, ThermoType >.
Definition at line 427 of file ISAT.C.
References forAllConstIters.
add()
template<class CompType , class ThermoType > Foam::label add (const scalarField & phiq, const scalarField & Rphiq, const scalar rho, const scalar deltaT) virtual
Implements chemistryTabulationMethod< CompType, ThermoType >.
Definition at line 502 of file ISAT.C.
References A, PtrList< T >::append(), PtrList< T >::clear(), Foam::deleteDemandDrivenData(), forAllConstIters, rho, and Foam::Zero.
update()
template<class CompType , class ThermoType > virtual bool update () inline virtual
Implements chemistryTabulationMethod< CompType, ThermoType >.
Definition at line 234 of file ISAT.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/chemistryModel/chemistryModel/TDACChemistryModel/tabulation/ISAT/ISAT.H
src/thermophysicalModels/chemistryModel/chemistryModel/TDACChemistryModel/tabulation/ISAT/ISAT.C