OpenFOAM: geometric Class Reference
geometric Class Reference
Keep faces together based on geometric considerations from a list of topoSetFaceSource. The faces selected (inside) of each source are to be kept together during the decomposition.
#include <geometricConstraint.H>
Public Member Functions
TypeName ("geometric")
geometric (const dictionary &dict)
geometric (PtrList< topoSetFaceSource > &&selections)
virtual ~geometric ()=default
virtual void add (const polyMesh &mesh, boolList &blockedFace, PtrList< labelList > &specifiedProcessorFaces, labelList &specifiedProcessor, List< labelPair > &explicitConnections) const
Public Member Functions inherited from decompositionConstraint
TypeName ("decompositionConstraint")
declareRunTimeSelectionTable (autoPtr, decompositionConstraint, dictionary,(const dictionary &dict),(dict))
decompositionConstraint (const dictionary &constraintDict)
decompositionConstraint (const dictionary &constraintDict, const word &modelType)
virtual ~decompositionConstraint ()=default
virtual void apply (const polyMesh &mesh, const boolList &blockedFace, const PtrList< labelList > &specifiedProcessorFaces, const labelList &specifiedProcessor, const List< labelPair > &explicitConnections, labelList &decomposition) const
Additional Inherited Members
Static Public Member Functions inherited from decompositionConstraint
static autoPtr< decompositionConstraint > New (const dictionary &constraintDict)
static autoPtr< decompositionConstraint > New (const dictionary &constraintDict, const word &modelType)
Protected Member Functions inherited from decompositionConstraint
void getMinBoundaryValue (const polyMesh &mesh, const labelList &decomposition, labelList &destProc) const
decompositionConstraint (const decompositionConstraint &)=delete
void operator= (const decompositionConstraint &)=delete
Protected Attributes inherited from decompositionConstraint
dictionary coeffDict_
Detailed Description
Keep faces together based on geometric considerations from a list of topoSetFaceSource. The faces selected (inside) of each source are to be kept together during the decomposition.
constraints
{
    geom1
    {
        type    geometric;
        grow    false;
        selection
        {
            box1
            {
                source  box;
                min     (-0.1 -0.01 -0.1);
                max     (0.1 0.30 0.1);
            }
            ball
            {
                source  sphere;
                origin  (-0.1 -0.01 -0.1);
                radius  0.25;
            }
            blob
            {
                source      surface;
                surfaceType triSurfaceMesh;
                surfaceName blob.obj;
            }
        }
    }
}
Dictionary parameters
Property Description Required Default
type geometric yes
grow Grow cells with partial connectivity no false
selection Dictionary of geometric selections yes
Note
Any searchableSurface selections must describe a closed volume. Ie, its hasVolumeType() method must be true.
The combined face selections are treated as an OR operation.
The "grow" mode includes an additional check to include cell faces for any cell that already has two or more of its faces "unblocked". This could indicate a connection over a corner, but does not distinguish between connectivity introduced by the constraint and the connectivity defined by other constraints.
Source files
geometricConstraint.H
geometricConstraint.C
Definition at line 127 of file geometricConstraint.H.
Constructor & Destructor Documentation
geometric() [1/2]
geometric (const dictionary & dict) explicit
Definition at line 48 of file geometricConstraint.C.
References Foam::endl(), Foam::Info, and Foam::type().
geometric() [2/2]
geometric (PtrList< topoSetFaceSource > && selections) explicit
Definition at line 69 of file geometricConstraint.C.
References Foam::endl(), Foam::Info, UPtrList< T >::size(), and Foam::type().
~geometric()
virtual ~geometric () virtual default
Member Function Documentation
TypeName()
TypeName ("geometric")
add()
void add (const polyMesh & mesh, boolList & blockedFace, PtrList< labelList > & specifiedProcessorFaces, labelList & specifiedProcessor, List< labelPair > & explicitConnections) const virtual
Implements decompositionConstraint.
Definition at line 90 of file geometricConstraint.C.
References Foam::BitOps::count(), Foam::endl(), UPtrList< T >::get(), Foam::Info, mesh, topoSetFaceSource::New(), PtrList< T >::resize(), Foam::returnReduce(), PtrList< T >::set(), topoSetSource::SUBTRACT, syncTools::syncFaceList(), PtrList< T >::transfer(), Foam::type(), and WarningInFunction.
The documentation for this class was generated from the following files:
src/parallel/decompose/decompositionMethods/decompositionConstraints/geometric/geometricConstraint.H
src/parallel/decompose/decompositionMethods/decompositionConstraints/geometric/geometricConstraint.C