OpenFOAM: SolverPerformance< Type > Class Template Reference
SolverPerformance< Type > Class Template Reference
SolverPerformance is the class returned by the LduMatrix solver containing performance statistics.
#include <SolverPerformance.H>
Public Member Functions
ClassName ("SolverPerformance")
SolverPerformance ()
SolverPerformance (const word &solverName, const word &fieldName, const Type &iRes=pTraits< Type >::zero, const Type &fRes=pTraits< Type >::zero, const labelType &nIter=pTraits< labelType >::zero, const bool converged=false, const bool singular=false)
const word & solverName () const noexcept
word & solverName () noexcept
const word & fieldName () const noexcept
const Type & initialResidual () const noexcept
Type & initialResidual () noexcept
const Type & finalResidual () const noexcept
Type & finalResidual () noexcept
const labelType & nIterations () const noexcept
labelType & nIterations () noexcept
bool converged () const noexcept
bool singular () const
bool checkConvergence (const Type &tolerance, const Type &relTolerance, const int logLevel=0)
bool checkSingularity (const Type &residual)
void print (Ostream &os) const
void replace (const label cmpt, const SolverPerformance< typename pTraits< Type >::cmptType > &sp)
SolverPerformance< typename pTraits< Type >::cmptType > max ()
bool operator!= (const SolverPerformance< Type > &) const
Foam::SolverPerformance< Foam::scalar > max ()
SolverPerformance< scalar > max ()
Static Public Attributes
static const scalar great_
static const scalar small_
static const scalar vsmall_
Friends
SolverPerformance< Type > Foam::max (const SolverPerformance< Type > &, const SolverPerformance< Type > &)
Istream & operator>> (Istream &, SolverPerformance< Type > &)
Ostream & operator<< (Ostream &, const SolverPerformance< Type > &)
Detailed Description
template<class Type>
class Foam::SolverPerformance< Type >
SolverPerformance is the class returned by the LduMatrix solver containing performance statistics.
Source files
SolverPerformance.H
SolverPerformance.C
Definition at line 77 of file SolverPerformance.H.
Constructor & Destructor Documentation
SolverPerformance() [1/2]
template<class Type > SolverPerformance () inline
Definition at line 112 of file SolverPerformance.H.
SolverPerformance() [2/2]
template<class Type > SolverPerformance (const word & solverName, const word & fieldName, const Type & iRes = pTraits<Type>::zero, const Type & fRes = pTraits<Type>::zero, const labelType & nIter = pTraits<labelType>::zero, const bool converged = false, const bool singular = false) inline
Definition at line 122 of file SolverPerformance.H.
Member Function Documentation
ClassName()
template<class Type > ClassName ("SolverPerformance< Type >")
solverName() [1/2]
template<class Type > const word & solverName () const inline noexcept
Definition at line 146 of file SolverPerformance.H.
solverName() [2/2]
template<class Type > word & solverName () inline noexcept
Definition at line 152 of file SolverPerformance.H.
fieldName()
template<class Type > const word & fieldName () const inline noexcept
Definition at line 159 of file SolverPerformance.H.
initialResidual() [1/2]
template<class Type > const Type & initialResidual () const inline noexcept
Definition at line 166 of file SolverPerformance.H.
initialResidual() [2/2]
template<class Type > Type & initialResidual () inline noexcept
Definition at line 172 of file SolverPerformance.H.
finalResidual() [1/2]
template<class Type > const Type & finalResidual () const inline noexcept
Definition at line 179 of file SolverPerformance.H.
finalResidual() [2/2]
template<class Type > Type & finalResidual () inline noexcept
Definition at line 185 of file SolverPerformance.H.
nIterations() [1/2]
template<class Type > const labelType & nIterations () const inline noexcept
Definition at line 192 of file SolverPerformance.H.
nIterations() [2/2]
template<class Type > labelType & nIterations () inline noexcept
Definition at line 198 of file SolverPerformance.H.
converged()
template<class Type > bool converged () const inline noexcept
Definition at line 205 of file SolverPerformance.H.
singular()
template<class Type > bool singular () const
Definition at line 44 of file SolverPerformance.C.
checkConvergence()
template<class Type > bool checkConvergence (const Type & tolerance, const Type & relTolerance, const int logLevel = 0)
Definition at line 56 of file SolverPerformance.C.
References Foam::cmptMultiply(), Foam::endl(), and Foam::Info.
checkSingularity()
template<class Type > bool checkSingularity (const Type & residual)
Definition at line 28 of file SolverPerformance.C.
References Foam::component().
print()
template<class Type > void print (Ostream & os) const
Definition at line 85 of file SolverPerformance.C.
References Foam::component(), Foam::endl(), and os().
replace()
template<class Type > void replace (const label cmpt, const SolverPerformance< typename pTraits< Type >::cmptType > & sp)
Definition at line 118 of file SolverPerformance.C.
max() [1/3]
template<class Type > Foam::SolverPerformance< typename Foam::pTraits< Type >::cmptType > max ()
Definition at line 133 of file SolverPerformance.C.
References Foam::cmptMax().
operator!=()
template<class Type > bool operator!= (const SolverPerformance< Type > & sp) const
Definition at line 149 of file SolverPerformance.C.
max() [2/3]
Foam::SolverPerformance< Foam::scalar > max ()
Definition at line 36 of file solverPerformance.C.
max() [3/3]
SolverPerformance< scalar > max ()
Friends And Related Symbol Documentation
Foam::max
template<class Type > SolverPerformance< Type > Foam::max (const SolverPerformance< Type > & , const SolverPerformance< Type > &) friend
operator>>
template<class Type > Istream & operator>> (Istream & , SolverPerformance< Type > &) friend
operator<<
template<class Type > Ostream & operator<< (Ostream & , const SolverPerformance< Type > &) friend
Member Data Documentation
great_
const scalar great_ static
Definition at line 101 of file SolverPerformance.H.
small_
const scalar small_ static
Definition at line 104 of file SolverPerformance.H.
Referenced by lduMatrix::solver::normFactor().
vsmall_
const scalar vsmall_ static
Definition at line 107 of file SolverPerformance.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/LduMatrix/LduMatrix/SolverPerformance.H
src/OpenFOAM/matrices/LduMatrix/LduMatrix/SolverPerformance.C
src/OpenFOAM/matrices/LduMatrix/LduMatrix/solverPerformance.C