OpenFOAM: tetrahedron< Point, PointRef > Class Template Reference
tetrahedron< Point, PointRef > Class Template Reference
A tetrahedron primitive.
#include <tetrahedron.H>
Classes
class dummyOp
class storeOp
class sumVolOp
Public Types
enum { nVertices = 4 , nEdges = 6 }
typedef Point point_type
typedef FixedList< tetPoints, 200 > tetIntersectionList
Public Member Functions
tetrahedron (const Point &p0, const Point &p1, const Point &p2, const Point &p3)
tetrahedron (const FixedList< Point, 4 > &pts)
tetrahedron (const UList< Point > &points, const FixedList< label, 4 > &indices)
tetrahedron (Istream &)
const Point & a () const noexcept
const Point & b () const noexcept
const Point & c () const noexcept
const Point & d () const noexcept
triPointRef tri (const label facei) const
vector Sa () const
vector Sb () const
vector Sc () const
vector Sd () const
Point centre () const
scalar mag () const
Pair< Point > box () const
treeBoundBox bounds () const
Point circumCentre () const
scalar circumRadius () const
scalar quality () const
Point randomPoint (Random &rndGen) const
Point barycentricToPoint (const barycentric &bary) const
barycentric pointToBarycentric (const point &pt) const
scalar pointToBarycentric (const point &pt, barycentric &bary) const
pointHit nearestPoint (const point &p) const
bool inside (const point &pt) const
template<class AboveTetOp , class BelowTetOp >
void sliceWithPlane (const plane &pl, AboveTetOp &aboveOp, BelowTetOp &belowOp) const
void tetOverlap (const tetrahedron< Point, PointRef > &tetB, tetIntersectionList &insideTets, label &nInside, tetIntersectionList &outsideTets, label &nOutside) const
pointHit containmentSphere (const scalar tol) const
void gradNiSquared (scalarField &buffer) const
void gradNiDotGradNj (scalarField &buffer) const
void gradNiGradNi (tensorField &buffer) const
void gradNiGradNj (tensorField &buffer) const
Static Public Member Functions
static Pair< Point > box (const Point &p0, const Point &p1, const Point &p2, const Point &p3)
Friends
Istream & operator>> (Istream &, tetrahedron &)
Ostream & operator (Ostream &, const tetrahedron &)
Detailed Description
template<class Point, class PointRef>
class Foam::tetrahedron< Point, PointRef >
A tetrahedron primitive.
Ordering of edges needs to be the same for a tetrahedron class, a tetrahedron cell shape model and a tetCell.
Source files
tetrahedron.H
tetrahedronI.H
tetrahedron.C
Definition at line 170 of file tetrahedron.H.
Member Typedef Documentation
point_type
template<class Point , class PointRef > typedef Point point_type
Definition at line 177 of file tetrahedron.H.
tetIntersectionList
template<class Point , class PointRef > typedef FixedList<tetPoints, 200> tetIntersectionList
Definition at line 181 of file tetrahedron.H.
Member Enumeration Documentation
anonymous enum
template<class Point , class PointRef > anonymous enum
Enumerator
nVertices
nEdges
Definition at line 255 of file tetrahedron.H.
Constructor & Destructor Documentation
tetrahedron() [1/4]
template<class Point , class PointRef > tetrahedron (const Point & p0, const Point & p1, const Point & p2, const Point & p3) inline
Definition at line 69 of file tetrahedronI.H.
tetrahedron() [2/4]
template<class Point , class PointRef > tetrahedron (const FixedList< Point, 4 > & pts) inline
Definition at line 85 of file tetrahedronI.H.
tetrahedron() [3/4]
template<class Point , class PointRef > tetrahedron (const UList< Point > & points, const FixedList< label, 4 > & indices) inline
Definition at line 98 of file tetrahedronI.H.
tetrahedron() [4/4]
template<class Point , class PointRef > tetrahedron (Istream & is) inline explicit
Definition at line 112 of file tetrahedronI.H.
Member Function Documentation
a()
template<class Point , class PointRef > const Point & a () const inline noexcept
Definition at line 292 of file tetrahedron.H.
b()
template<class Point , class PointRef > const Point & b () const inline noexcept
Definition at line 295 of file tetrahedron.H.
c()
template<class Point , class PointRef > const Point & c () const inline noexcept
Definition at line 298 of file tetrahedron.H.
d()
template<class Point , class PointRef > const Point & d () const inline noexcept
Definition at line 301 of file tetrahedron.H.
tri()
template<class Point , class PointRef > Foam::triPointRef tri (const label facei) const inline
Definition at line 184 of file tetrahedronI.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
box() [1/2]
template<class Point , class PointRef > Foam::Pair< Point > box (const Point & p0, const Point & p1, const Point & p2, const Point & p3) inline static
Definition at line 138 of file tetrahedronI.H.
References Foam::max(), Foam::min(), and p0.
Sa()
template<class Point , class PointRef > Foam::vector Sa () const inline
Definition at line 217 of file tetrahedronI.H.
References triangle< Point, PointRef >::areaNormal().
Sb()
template<class Point , class PointRef > Foam::vector Sb () const inline
Definition at line 224 of file tetrahedronI.H.
References triangle< Point, PointRef >::areaNormal().
Sc()
template<class Point , class PointRef > Foam::vector Sc () const inline
Definition at line 231 of file tetrahedronI.H.
References triangle< Point, PointRef >::areaNormal().
Sd()
template<class Point , class PointRef > Foam::vector Sd () const inline
Definition at line 238 of file tetrahedronI.H.
References triangle< Point, PointRef >::areaNormal().
centre()
template<class Point , class PointRef > Point centre () const inline
Definition at line 245 of file tetrahedronI.H.
Referenced by nearWallFields::calcAddressing().
mag()
template<class Point , class PointRef > Foam::scalar mag () const inline
Definition at line 252 of file tetrahedronI.H.
Referenced by tetrahedron< Point, PointRef >::sumVolOp::operator()().
box() [2/2]
template<class Point , class PointRef > Foam::Pair< Point > box () const inline
Definition at line 155 of file tetrahedronI.H.
References tetrahedron< Point, PointRef >::box().
Referenced by tetPoints::box(), and tetrahedron< Point, PointRef >::box().
bounds()
template<class Point , class PointRef > Foam::treeBoundBox bounds () const inline
Definition at line 168 of file tetrahedronI.H.
circumCentre()
template<class Point , class PointRef > Point circumCentre () const inline
Definition at line 259 of file tetrahedronI.H.
References b, lambda(), Foam::mag(), Foam::magSqr(), and mu.
circumRadius()
template<class Point , class PointRef > Foam::scalar circumRadius () const inline
Definition at line 286 of file tetrahedronI.H.
References b, lambda(), Foam::mag(), Foam::magSqr(), and mu.
quality()
template<class Point , class PointRef > Foam::scalar quality () const inline
Definition at line 312 of file tetrahedronI.H.
References Foam::mag(), Foam::min(), Foam::pow3(), and Foam::sqrt().
Referenced by polyMeshTetDecomposition::minQuality().
randomPoint()
template<class Point , class PointRef > Point randomPoint (Random & rndGen) const inline
Definition at line 325 of file tetrahedronI.H.
References Foam::barycentric01(), and rndGen.
barycentricToPoint()
template<class Point , class PointRef > Point barycentricToPoint (const barycentric & bary) const inline
Definition at line 335 of file tetrahedronI.H.
pointToBarycentric() [1/2]
template<class Point , class PointRef > Foam::barycentric pointToBarycentric (const point & pt) const inline
Definition at line 345 of file tetrahedronI.H.
pointToBarycentric() [2/2]
template<class Point , class PointRef > Foam::scalar pointToBarycentric (const point & pt, barycentric & bary) const inline
Definition at line 357 of file tetrahedronI.H.
References Foam::det(), Foam::inv(), Foam::mag(), Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
nearestPoint()
template<class Point , class PointRef > Foam::pointHit nearestPoint (const point & p) const inline
Definition at line 400 of file tetrahedronI.H.
References PointHit< PointType >::distance(), p, and PointHit< PointType >::point().
inside()
template<class Point , class PointRef > bool inside (const point & pt) const inline
Definition at line 515 of file tetrahedronI.H.
References p.
sliceWithPlane()
template<class Point , class PointRef > template<class AboveTetOp , class BelowTetOp > void sliceWithPlane (const plane & pl, AboveTetOp & aboveOp, BelowTetOp & belowOp) const inline
Definition at line 1107 of file tetrahedronI.H.
tetOverlap()
template<class Point , class PointRef > void tetOverlap (const tetrahedron< Point, PointRef > & tetB, tetIntersectionList & insideTets, label & nInside, tetIntersectionList & outsideTets, label & nOutside) const inline
containmentSphere()
template<class Point , class PointRef > Foam::pointHit containmentSphere (const scalar tol) const
Definition at line 27 of file tetrahedron.C.
References Foam::magSqr(), PtrList< T >::PtrList(), and Foam::sqrt().
gradNiSquared()
template<class Point , class PointRef > void gradNiSquared (scalarField & buffer) const
Definition at line 239 of file tetrahedron.C.
References Foam::mag(), and Foam::magSqr().
gradNiDotGradNj()
template<class Point , class PointRef > void gradNiDotGradNj (scalarField & buffer) const
Definition at line 260 of file tetrahedron.C.
References Foam::mag().
gradNiGradNi()
template<class Point , class PointRef > void gradNiGradNi (tensorField & buffer) const
Definition at line 290 of file tetrahedron.C.
References Foam::mag(), and Foam::sqr().
gradNiGradNj()
template<class Point , class PointRef > void gradNiGradNj (tensorField & buffer) const
Definition at line 308 of file tetrahedron.C.
References Foam::mag().
Friends And Related Symbol Documentation
operator>>
template<class Point , class PointRef > Istream & operator>> (Istream & , tetrahedron< Point, PointRef > &) friend
operator
template<class Point , class PointRef > Ostream & operator (Ostream & , const tetrahedron< Point, PointRef > &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/primitiveShapes/tetrahedron/tetrahedron.H
src/OpenFOAM/meshes/primitiveShapes/tetrahedron/tetrahedron.C
src/OpenFOAM/meshes/primitiveShapes/tetrahedron/tetrahedronI.H