OpenFOAM: polynomialFunction Class Reference
polynomialFunction Class Reference
Polynomial function representation.
#include <polynomialFunction.H>
Public Member Functions
TypeName ("polynomialFunction")
polynomialFunction ()
polynomialFunction (const label order)
polynomialFunction (std::initializer_list< scalar > coeffs)
polynomialFunction (const UList< scalar > &coeffs)
polynomialFunction (Istream &is)
virtual ~polynomialFunction ()=default
bool logActive () const
scalar logCoeff () const
scalar value (const scalar x) const
scalar integrate (const scalar x1, const scalar x2) const
polynomialFunction integral (const scalar intConstant=0) const
polynomialFunction integralMinus1 (const scalar intConstant=0) const
bool operator== (const polynomialFunction &rhs) const
bool operator!= (const polynomialFunction &rhs) const
polynomialFunction & operator+= (const polynomialFunction &)
polynomialFunction & operator-= (const polynomialFunction &)
polynomialFunction & operator*= (const scalar)
polynomialFunction & operator/= (const scalar)
Friends
Istream & operator>> (Istream &, polynomialFunction &poly)
Ostream & operator<< (Ostream &, const polynomialFunction &poly)
Detailed Description
Polynomial function representation.
    poly = logCoeff*log(x) + sum(coeffs[i]*x^i)
where 0 <= i <= N
integer powers, starting at zero
value(x) to evaluate the poly for a given value
integrate(x1, x2) between two scalar values
integral() to return a new, integral coeff polynomial
increases the size (order)
integralMinus1() to return a new, integral coeff polynomial where the base poly starts at order -1
See also
Foam::Polynomial for a templated implementation
Source files
polynomialFunction.H
polynomialFunction.C
Definition at line 72 of file polynomialFunction.H.
Constructor & Destructor Documentation
polynomialFunction() [1/5]
polynomialFunction ()
Definition at line 92 of file polynomialFunction.C.
polynomialFunction() [2/5]
polynomialFunction (const label order) explicit
Definition at line 100 of file polynomialFunction.C.
polynomialFunction() [3/5]
polynomialFunction (std::initializer_list< scalar > coeffs) explicit
Definition at line 110 of file polynomialFunction.C.
polynomialFunction() [4/5]
polynomialFunction (const UList< scalar > & coeffs) explicit
Definition at line 123 of file polynomialFunction.C.
polynomialFunction() [5/5]
polynomialFunction (Istream & is) explicit
Definition at line 133 of file polynomialFunction.C.
~polynomialFunction()
virtual ~polynomialFunction () virtual default
Member Function Documentation
TypeName()
TypeName ("polynomialFunction")
logActive()
bool logActive () const
Definition at line 145 of file polynomialFunction.C.
logCoeff()
Foam::scalar logCoeff () const
Definition at line 151 of file polynomialFunction.C.
value()
Foam::scalar value (const scalar x) const
Definition at line 157 of file polynomialFunction.C.
References Foam::log(), UList< T >::size(), and x.
integrate()
Foam::scalar integrate (const scalar x1, const scalar x2) const
Definition at line 179 of file polynomialFunction.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, Foam::nl, and UList< T >::size().
integral()
Foam::polynomialFunction integral (const scalar intConstant = 0) const
Definition at line 211 of file polynomialFunction.C.
integralMinus1()
Foam::polynomialFunction integralMinus1 (const scalar intConstant = 0) const
Definition at line 218 of file polynomialFunction.C.
operator==()
bool operator== (const polynomialFunction & rhs) const
Definition at line 226 of file polynomialFunction.C.
Referenced by polynomialFunction::operator!=().
operator!=()
bool operator!= (const polynomialFunction & rhs) const inline
Definition at line 188 of file polynomialFunction.H.
References polynomialFunction::operator==().
operator+=()
Foam::polynomialFunction & operator+= (const polynomialFunction & poly)
Definition at line 238 of file polynomialFunction.C.
References forAll, List< T >::resize(), UPtrList< T >::size(), UList< T >::size(), and Foam::Zero.
operator-=()
Foam::polynomialFunction & operator-= (const polynomialFunction & poly)
Definition at line 257 of file polynomialFunction.C.
References forAll, List< T >::resize(), UPtrList< T >::size(), UList< T >::size(), and Foam::Zero.
operator*=()
Foam::polynomialFunction & operator*= (const scalar s)
Definition at line 276 of file polynomialFunction.C.
References forAll, and s().
operator/=()
Foam::polynomialFunction & operator/= (const scalar s)
Definition at line 289 of file polynomialFunction.C.
References forAll, and s().
Friends And Related Symbol Documentation
operator>>
Istream & operator>> (Istream & , polynomialFunction & poly) friend
operator<<
Ostream & operator<< (Ostream & , const polynomialFunction & poly) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/functions/Polynomial/polynomialFunction.H
src/OpenFOAM/primitives/functions/Polynomial/polynomialFunction.C