OpenFOAM: gravity Class Reference
gravity Class Reference
Gravitational acceleration vector Although termed a MeshObject it is registered on Time only and thus identical for all regions.
#include <gravityMeshObject.H>
Public Member Functions
TypeNameNoDebug ("g")
gravity (const word &name, const Time &runTime)
gravity (const Time &runTime)
virtual ~gravity ()=default
Public Member Functions inherited from MeshObject< Time, TopologicalMeshObject, gravity >
MeshObject (const Time &mesh)
MeshObject (const word &objName, const Time &mesh)
virtual ~MeshObject ()=default
const Time & mesh () const noexcept
virtual bool writeData (Ostream &os) const
Public Member Functions inherited from UniformDimensionedField< vector >
TypeName ("UniformDimensionedField")
UniformDimensionedField (const IOobject &io, const dimensioned< vector > &dt)
UniformDimensionedField (const IOobject &io, const dimensionSet &dims, const vector &val)
UniformDimensionedField (const IOobject &io, const vector &val, const dimensionSet &dims)
UniformDimensionedField (const UniformDimensionedField< vector > &)
UniformDimensionedField (const IOobject &io)
virtual ~UniformDimensionedField ()=default
virtual const word & name () const
virtual bool readData (Istream &)
bool writeData (Ostream &) const
virtual bool global () const
virtual fileName filePath () const
void operator= (const UniformDimensionedField< vector > &rhs)
void operator= (const dimensioned< vector > &rhs)
const vector & operator[] (const label) const noexcept
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
regIOobject (const IOobject &io, const bool isTimeObject=false)
regIOobject (const regIOobject &rio)
regIOobject (const regIOobject &rio, bool registerCopy)
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
regIOobject (const IOobject &io, const regIOobject &rio)
virtual ~regIOobject ()
bool checkIn ()
bool checkOut ()
virtual void addWatch ()
bool registered () const noexcept
bool ownedByRegistry () const noexcept
bool store ()
void release (const bool unregister=false) noexcept
label eventNo () const noexcept
label & eventNo () noexcept
bool upToDate (const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
void setUpToDate ()
virtual void rename (const word &newName)
const dictionary * findMetaData () const noexcept
dictionary & getMetaData () noexcept
void removeMetaData ()
virtual void updateMetaData ()
bool headerOk ()
Istream & readStream (const word &, const bool readOnProc=true)
void close ()
virtual bool read ()
virtual label addWatch (const fileName &)
const labelList & watchIndices () const noexcept
labelList & watchIndices () noexcept
virtual bool modified () const
virtual bool readIfModified ()
virtual bool writeObject (IOstreamOption streamOpt, const bool writeOnProc) const
virtual bool write (const bool writeOnProc=true) const
void operator= (const IOobject &io)
virtual bool writeObject (IOstreamOption::streamFormat fmt, IOstreamOption::versionNumber ver, IOstreamOption::compressionType cmp, const bool writeOnProc) const
Public Member Functions inherited from IOobject
TypeName ("IOobject")
IOobject (const IOobject &)=default
virtual ~IOobject ()=default
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const fileName &path, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const fileName &path, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const IOobject &io, const objectRegistry &registry)
IOobject (const IOobject &io, const word &name)
IOobject (const IOobject &io, const word &name, const fileName &local)
IOobject (const IOobject &io, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt)
IOobject (const IOobject &io, IOobjectOption::registerOption regOpt)
autoPtr< IOobject > clone () const
autoPtr< IOobject > clone (const objectRegistry &registry) const
const objectRegistry & db () const noexcept
const Time & time () const noexcept
const word & name () const noexcept
const word & headerClassName () const noexcept
word & headerClassName () noexcept
const string & note () const noexcept
string & note () noexcept
unsigned labelByteSize () const noexcept
unsigned scalarByteSize () const noexcept
void resetHeader (const word &newName=word::null)
bool hasHeaderClass () const noexcept
template<class Type >
bool isHeaderClass () const
template<class Type >
bool isHeaderClassName () const
word group () const
word member () const
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const noexcept
fileName & instance () noexcept
const fileName & local () const noexcept
fileName path () const
fileName path (const word &instance, const fileName &local=fileName::null) const
fileName objectPath () const
fileName objectRelPath () const
fileName localFilePath (const word &typeName, const bool search=true) const
fileName globalFilePath (const word &typeName, const bool search=true) const
IOstreamOption parseHeader (const dictionary &headerDict)
bool readHeader (Istream &is)
bool readHeader (dictionary &headerDict, Istream &is)
template<class Type >
bool typeHeaderOk (const bool checkType=true, const bool search=true, const bool verbose=true)
template<class Type >
void warnNoRereading () const
bool writeHeader (Ostream &os) const
bool writeHeader (Ostream &os, const word &objectType) const
void writeHeader (dictionary &dict, IOstreamOption streamOpt) const
void writeHeader (dictionary &dict, const word &objectType, IOstreamOption streamOpt) const
bool good () const noexcept
bool bad () const noexcept
InfoProxy< IOobject > info () const noexcept
void operator= (const IOobject &io)
template<>
bool isHeaderClass () const
template<class StringType >
Foam::word groupName (StringType base, const word &group)
Public Member Functions inherited from IOobjectOption
constexpr IOobjectOption (readOption rOpt=readOption::NO_READ, writeOption wOpt=writeOption::NO_WRITE, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (readOption rOpt, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (writeOption wOpt, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (registerOption registerObject, bool globalObject=false) noexcept
constexpr IOobjectOption (readOption rOpt, writeOption wOpt, bool registerObject, bool globalObject=false) noexcept
constexpr IOobjectOption (bool registerObject, bool globalObject=false) noexcept
readOption readOpt () const noexcept
readOption readOpt (readOption opt) noexcept
writeOption writeOpt () const noexcept
writeOption writeOpt (writeOption opt) noexcept
bool registerObject () const noexcept
bool registerObject (bool on) noexcept
bool globalObject () const noexcept
bool globalObject (bool on) noexcept
bool isAnyRead () const noexcept
bool isReadRequired () const noexcept
bool isReadOptional () const noexcept
readOption & readOpt () noexcept
writeOption & writeOpt () noexcept
bool & registerObject () noexcept
bool & globalObject () noexcept
Public Member Functions inherited from dimensioned< Type >
dimensioned ()
dimensioned (const dimensionSet &dims)
dimensioned (const dimensionSet &dims, const Foam::zero)
dimensioned (const dimensionSet &dims, const Foam::one)
dimensioned (const Type &val)
dimensioned (const dimensionSet &dims, const Type &val)
dimensioned (const word &name, const dimensionSet &dims, const Type &val)
dimensioned (const word &name, const dimensioned< Type > &dt)
dimensioned (const primitiveEntry &e)
dimensioned (const primitiveEntry &e, const dimensionSet &dims)
dimensioned (const word &name, const dictionary &dict)
dimensioned (const word &name, const dimensionSet &dims, const dictionary &dict)
dimensioned (const word &name, const dimensionSet &dims, const dictionary &dict, const word &entryName)
dimensioned (const word &name, const dimensionSet &dims, const Type &val, const dictionary &dict)
const word & name () const noexcept
word & name () noexcept
const dimensionSet & dimensions () const noexcept
dimensionSet & dimensions () noexcept
const Type & value () const noexcept
Type & value () noexcept
dimensioned< cmptType > component (const direction d) const
void replace (const direction d, const dimensioned< cmptType > &dc)
dimensioned< Type > T () const
bool read (const dictionary &dict)
bool readIfPresent (const dictionary &dict)
bool read (const word &entryName, const dictionary &dict)
bool readIfPresent (const word &entryName, const dictionary &dict)
Istream & read (Istream &is, const bool readName=true)
Istream & read (Istream &is, const dictionary &readSet)
Istream & read (Istream &is, const HashTable< dimensionedScalar > &readSet)
void writeEntry (const word &keyword, Ostream &os) const
dimensioned< cmptType > operator[] (const direction d) const
void operator+= (const dimensioned< Type > &dt)
void operator-= (const dimensioned< Type > &dt)
void operator*= (const scalar s)
void operator/= (const scalar s)
dimensioned (Istream &is)
dimensioned (const word &name, Istream &is)
dimensioned (const word &name, const dimensionSet &dims, Istream &is)
Static Public Member Functions
static const gravity & New (const word &name, const Time &runTime)
static const gravity & New (const Time &runTime)
static const uniformDimensionedVectorField * findObject (const Time &runTime)
static uniformDimensionedVectorField * getObjectPtr (const Time &runTime)
static const uniformDimensionedVectorField & lookupObject (const Time &runTime)
Static Public Member Functions inherited from MeshObject< Time, TopologicalMeshObject, gravity >
static const gravity & New (const Time &mesh, Args &&... args)
static const gravity & New (const word &objName, const Time &mesh, Args &&... args)
static bool Delete (const word &objName, const Time &mesh)
static bool Delete (const Time &mesh)
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *p)
template<class Type >
static Type & store (autoPtr< Type > &ptr)
template<class Type >
static Type & store (autoPtr< Type > &&ptr)
template<class Type >
static Type & store (refPtr< Type > &ptr)
template<class Type >
static Type & store (refPtr< Type > &&ptr)
template<class Type >
static Type & store (tmp< Type > &ptr)
template<class Type >
static Type & store (tmp< Type > &&ptr)
Static Public Member Functions inherited from IOobject
static bool bannerEnabled () noexcept
static bool bannerEnabled (bool on) noexcept
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
template<class StringType >
static word groupName (StringType base, const word &group)
static word group (const word &name)
static word member (const word &name)
static word scopedName (const std::string &scope, const word &name)
static IOobject selectIO (const IOobject &io, const fileName &altFile, const word &ioName="")
static Ostream & writeBanner (Ostream &os, const bool noSyntaxHint=false)
static Ostream & writeDivider (Ostream &os)
static Ostream & writeEndDivider (Ostream &os)
Static Public Member Functions inherited from IOobjectOption
static bool isAnyRead (readOption opt) noexcept
static bool isReadRequired (readOption opt) noexcept
static bool isReadOptional (readOption opt) noexcept
static readOption lazierRead (readOption opt) noexcept
Static Public Member Functions inherited from dimensioned< Type >
static dimensioned< Type > getOrDefault (const word &name, const dictionary &dict, const dimensionSet &dims=dimless, const Type &deflt=Type(Zero))
static dimensioned< Type > getOrDefault (const word &name, const dictionary &dict, const Type &deflt=Type(Zero))
static dimensioned< Type > getOrAddToDict (const word &name, dictionary &dict, const dimensionSet &dims=dimless, const Type &deflt=Type(Zero))
static dimensioned< Type > getOrAddToDict (const word &name, dictionary &dict, const Type &deflt=Type(Zero))
static dimensioned< Type > lookupOrDefault (const word &name, const dictionary &dict, const dimensionSet &dims=dimless, const Type &deflt=Type(Zero))
static dimensioned< Type > lookupOrDefault (const word &name, const dictionary &dict, const Type &deflt=Type(Zero))
static dimensioned< Type > lookupOrAddToDict (const word &name, dictionary &dict, const dimensionSet &dims=dimless, const Type &deflt=Type(Zero))
static dimensioned< Type > lookupOrAddToDict (const word &name, dictionary &dict, const Type &deflt=Type(Zero))
Additional Inherited Members
Public Types inherited from IOobject
enum objectState : char { GOOD , BAD }
enum fileCheckTypes : char { timeStamp , timeStampMaster , inotify , inotifyMaster }
Public Types inherited from IOobjectOption
enum readOption : unsigned char {
NO_READ = 0 , MUST_READ = 0x1 , READ_MODIFIED = 0x3 , MUST_READ_IF_MODIFIED = 0x3 ,
LAZY_READ = 0x4 , READ_IF_PRESENT = 0x4
}
enum writeOption : unsigned char { NO_WRITE = 0 , AUTO_WRITE = 0x10 }
enum registerOption : unsigned char { NO_REGISTER = 0 , REGISTER = 1 }
Public Types inherited from dimensioned< Type >
typedef Type value_type
typedef pTraits< Type >::cmptType cmptType
Static Public Attributes inherited from IOobject
static const Enum< fileCheckTypes > fileCheckTypesNames
static char scopeSeparator
static fileCheckTypes fileModificationChecking
static float fileModificationSkew
static int maxFileModificationPolls
Protected Member Functions inherited from regIOobject
bool readHeaderOk (const IOstreamOption::streamFormat fmt, const word &typeName)
Protected Member Functions inherited from IOobject
void setBad (const string &s)
Static Protected Member Functions inherited from IOobject
static void writeHeaderContent (Ostream &os, const IOobject &io, const word &objectType, const dictionary *metaDataDict=nullptr)
static void writeHeaderContent (dictionary &dict, const IOobject &io, const word &objectType, IOstreamOption streamOpt, const dictionary *metaDataDict=nullptr)
Protected Attributes inherited from MeshObject< Time, TopologicalMeshObject, gravity >
const Time & mesh_
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
Detailed Description
Gravitational acceleration vector Although termed a MeshObject it is registered on Time only and thus identical for all regions.
Source files
gravityMeshObject.H
gravityMeshObject.C
Definition at line 52 of file gravityMeshObject.H.
Constructor & Destructor Documentation
gravity() [1/2]
gravity (const word & name, const Time & runTime)
Definition at line 36 of file gravityMeshObject.C.
References Foam::name().
gravity() [2/2]
gravity (const Time & runTime) inline explicit
Definition at line 76 of file gravityMeshObject.H.
~gravity()
virtual ~gravity () virtual default
Member Function Documentation
TypeNameNoDebug()
TypeNameNoDebug ("g")
New() [1/2]
static const gravity & New (const word & name, const Time & runTime) inline static
Definition at line 82 of file gravityMeshObject.H.
References UniformDimensionedField< vector >::name(), MeshObject< Mesh, MeshObjectType, Type >::New(), and runTime.
Referenced by buoyancyEnergy::addSup(), multiphaseStabilizedTurbulence::addSup(), solidificationMeltingSource::addSup(), filmTurbulenceModel::Cw(), buoyantKEpsilon< BasicTurbulenceModel >::epsilonSource(), interfaceTrackingFvMesh::freeSurfacePressureJump(), waveMakerPointPatchVectorField::g(), buoyantKEpsilon< BasicTurbulenceModel >::Gcoef(), buoyantKEpsilon< BasicTurbulenceModel >::kSource(), phaseHydrostaticPressureFvPatchScalarField::updateCoeffs(), prghPressureFvPatchScalarField::updateCoeffs(), prghTotalPressureFvPatchScalarField::updateCoeffs(), uniformDensityHydrostaticPressureFvPatchScalarField::updateCoeffs(), waveSurfacePressureFvPatchScalarField::updateCoeffs(), alphaFixedPressureFvPatchScalarField::updateCoeffs(), and prghPermeableAlphaTotalPressureFvPatchScalarField::updateSnGrad().
New() [2/2]
static const gravity & New (const Time & runTime) inline static
Definition at line 92 of file gravityMeshObject.H.
References MeshObject< Mesh, MeshObjectType, Type >::New(), and runTime.
findObject()
static const uniformDimensionedVectorField * findObject (const Time & runTime) inline static
Definition at line 109 of file gravityMeshObject.H.
References runTime.
getObjectPtr()
static uniformDimensionedVectorField * getObjectPtr (const Time & runTime) inline static
Definition at line 117 of file gravityMeshObject.H.
References runTime.
lookupObject()
static const uniformDimensionedVectorField & lookupObject (const Time & runTime) inline static
Definition at line 124 of file gravityMeshObject.H.
References runTime.
The documentation for this class was generated from the following files:
src/finiteVolume/cfdTools/general/meshObjects/gravity/gravityMeshObject.H
src/finiteVolume/cfdTools/general/meshObjects/gravity/gravityMeshObject.C