OpenFOAM: eulerianParticle Class Reference
eulerianParticle Class Reference
#include <eulerianParticle.H>
Public Member Functions
eulerianParticle ()
void write (Ostream &os) const
Foam::dictionary writeDict () const
Public Attributes
label faceIHit
vector VC
vector VU
scalar V
scalar time
Friends
bool operator== (const eulerianParticle &a, const eulerianParticle &b)
bool operator!= (const eulerianParticle &a, const eulerianParticle &b)
Detailed Description
Definition at line 64 of file eulerianParticle.H.
Constructor & Destructor Documentation
eulerianParticle()
eulerianParticle ()
Definition at line 28 of file eulerianParticle.C.
Member Function Documentation
write()
void write (Ostream & os) const
Definition at line 72 of file eulerianParticle.C.
References Foam::cbrt(), Foam::endl(), os(), Foam::constant::mathematical::pi(), token::SPACE, and U.
writeDict()
Foam::dictionary writeDict () const
Definition at line 87 of file eulerianParticle.C.
References dictionary::add(), Foam::cbrt(), dict, Foam::constant::mathematical::pi(), and U.
Friends And Related Symbol Documentation
operator==
bool operator== (const eulerianParticle & a, const eulerianParticle & b) friend
Definition at line 104 of file eulerianParticle.H.
operator!=
bool operator!= (const eulerianParticle & a, const eulerianParticle & b) friend
Definition at line 118 of file eulerianParticle.H.
Member Data Documentation
faceIHit
label faceIHit
Definition at line 74 of file eulerianParticle.H.
Referenced by extractEulerianParticles::accumulateParticleInfo().
VC
vector VC
Definition at line 77 of file eulerianParticle.H.
VU
vector VU
Definition at line 80 of file eulerianParticle.H.
V
scalar V
Definition at line 83 of file eulerianParticle.H.
Referenced by sumParticleOp< VOFParticle >::operator()().
time
scalar time
Definition at line 86 of file eulerianParticle.H.
The documentation for this class was generated from the following files:
src/functionObjects/field/extractEulerianParticles/eulerianParticle/eulerianParticle.H
src/functionObjects/field/extractEulerianParticles/eulerianParticle/eulerianParticle.C