OpenFOAM: faceZoneReferenceTemperature Class Reference
faceZoneReferenceTemperature Class Reference
Heat transfer coefficient calculation that employs the area-average temperature of a specified face zone as the reference temperature.
#include <faceZoneReferenceTemperature.H>
Public Member Functions
TypeName ("faceZoneReferenceTemperature")
faceZoneReferenceTemperature (const dictionary &dict, const fvMesh &mesh, const word &TName)
faceZoneReferenceTemperature (const faceZoneReferenceTemperature &)=delete
void operator= (const faceZoneReferenceTemperature &)=delete
virtual ~faceZoneReferenceTemperature ()=default
virtual bool read (const dictionary &dict)
Public Member Functions inherited from heatTransferCoeffModel
TypeName ("heatTransferCoeffModel")
declareRunTimeSelectionTable (autoPtr, heatTransferCoeffModel, dictionary,(const dictionary &dict, const fvMesh &mesh, const word &TName),(dict, mesh, TName))
heatTransferCoeffModel (const dictionary &dict, const fvMesh &mesh, const word &TName)
heatTransferCoeffModel (const heatTransferCoeffModel &)=delete
void operator= (const heatTransferCoeffModel &)=delete
virtual ~heatTransferCoeffModel ()=default
const fvMesh & mesh () const noexcept
const labelHashSet & patchSet () const noexcept
const word & TName () const noexcept
const word & qrName () const noexcept
tmp< FieldField< Field, scalar > > q () const
virtual bool calc (volScalarField &result, const FieldField< Field, scalar > &q)
Additional Inherited Members
Static Public Member Functions inherited from heatTransferCoeffModel
static autoPtr< heatTransferCoeffModel > New (const dictionary &dict, const fvMesh &mesh, const word &TName)
Protected Attributes inherited from heatTransferCoeffModel
const fvMesh & mesh_
labelHashSet patchSet_
const word TName_
word qrName_
Detailed Description
Heat transfer coefficient calculation that employs the area-average temperature of a specified face zone as the reference temperature.
The heat transfer coefficient is calculated by:
where
= Heat transfer coefficient [W/m^2/K]
= Heat flux [W/m^2]
= Area average of reference face zone temperature [K]
= Temperature field of current patch [K]
Usage
Minimal example by using system/controlDict.functions:
heatTransferCoeff1
{
    // Inherited entries
    ...
    // Mandatory entries
    htcModel            faceZoneReferenceTemperature;
    referenceFaceZone   <word>;
    // Optional entries
    referenceRegion     <word>;
}
where the entries mean:
Property Description Type Reqd Deflt
htcModel Model name: faceZoneReferenceTemperature word yes -
referenceFaceZone Name of reference face zone word yes -
referenceRegion
Name of region that reference face zone resides
word no region0
Source files
faceZoneReferenceTemperature.H
faceZoneReferenceTemperature.C
Definition at line 131 of file faceZoneReferenceTemperature.H.
Constructor & Destructor Documentation
faceZoneReferenceTemperature() [1/2]
faceZoneReferenceTemperature (const dictionary & dict, const fvMesh & mesh, const word & TName)
Definition at line 195 of file faceZoneReferenceTemperature.C.
References dict, and faceZoneReferenceTemperature::read().
faceZoneReferenceTemperature() [2/2]
faceZoneReferenceTemperature (const faceZoneReferenceTemperature &) delete
~faceZoneReferenceTemperature()
virtual ~faceZoneReferenceTemperature () virtual default
Member Function Documentation
TypeName()
TypeName ("faceZoneReferenceTemperature")
operator=()
void operator= (const faceZoneReferenceTemperature &) delete
read()
bool read (const dictionary & dict) virtual
Reimplemented from heatTransferCoeffModel.
Definition at line 215 of file faceZoneReferenceTemperature.C.
References dict, and heatTransferCoeffModel::read().
Referenced by faceZoneReferenceTemperature::faceZoneReferenceTemperature().
The documentation for this class was generated from the following files:
src/functionObjects/field/heatTransferCoeff/heatTransferCoeffModels/faceZoneReferenceTemperature/faceZoneReferenceTemperature.H
src/functionObjects/field/heatTransferCoeff/heatTransferCoeffModels/faceZoneReferenceTemperature/faceZoneReferenceTemperature.C