OpenFOAM: adjointRotatingWallVelocityFvPatchVectorField Class Reference
adjointRotatingWallVelocityFvPatchVectorField Class Reference
The same as adjointWallVelocity but additionally computes the sensitivity contribution emerging from the change in the positions of the face centres, in case rotatingWallVelocity is used for the flow simulation.
#include <adjointRotatingWallVelocityFvPatchVectorField.H>
Public Member Functions
TypeName ("adjointRotatingWallVelocity")
adjointRotatingWallVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
adjointRotatingWallVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
adjointRotatingWallVelocityFvPatchVectorField (const adjointRotatingWallVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
virtual tmp< fvPatchVectorField > clone () const
adjointRotatingWallVelocityFvPatchVectorField (const adjointRotatingWallVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
virtual tmp< tensorField > dxdbMult () const
virtual void write (Ostream &) const
Public Member Functions inherited from adjointWallVelocityFvPatchVectorField
TypeName ("adjointWallVelocity")
adjointWallVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
adjointWallVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
adjointWallVelocityFvPatchVectorField (const adjointWallVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
adjointWallVelocityFvPatchVectorField (const adjointWallVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
virtual void manipulateMatrix (fvMatrix< vector > &matrix)
virtual void updateCoeffs ()
Public Member Functions inherited from adjointBoundaryCondition< Type >
TypeName ("adjointBoundaryCondition")
adjointBoundaryCondition (const fvPatch &p, const DimensionedField< Type, volMesh > &iF, const word &solverName)
adjointBoundaryCondition (const adjointBoundaryCondition< Type > &)
virtual ~adjointBoundaryCondition ()=default
const word & objectiveManagerName () const
const word & adjointSolverName () const
const word & simulationType () const
void setBoundaryContributionPtr ()
boundaryAdjointContribution & getBoundaryAdjContribution ()
const ATCModel & getATC () const
virtual void updatePrimalBasedQuantities ()
Additional Inherited Members
Protected Member Functions inherited from adjointBoundaryCondition< Type >
template<class Type2 >
tmp< Field< typename Foam::outerProduct< Foam::vector, Type2 >::type > > computePatchGrad (word name)
bool addATCUaGradUTerm ()
Protected Attributes inherited from adjointBoundaryCondition< Type >
const fvPatch & patch_
word managerName_
word adjointSolverName_
word simulationType_
autoPtr< boundaryAdjointContribution > boundaryContrPtr_
Switch addATCUaGradUTerm_
Detailed Description
The same as adjointWallVelocity but additionally computes the sensitivity contribution emerging from the change in the positions of the face centres, in case rotatingWallVelocity is used for the flow simulation.
Source files
adjointRotatingWallVelocityFvPatchVectorField.H
adjointRotatingWallVelocityFvPatchVectorField.C
Definition at line 51 of file adjointRotatingWallVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
adjointRotatingWallVelocityFvPatchVectorField() [1/4]
adjointRotatingWallVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Definition at line 27 of file adjointRotatingWallVelocityFvPatchVectorField.C.
adjointRotatingWallVelocityFvPatchVectorField() [2/4]
adjointRotatingWallVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Definition at line 57 of file adjointRotatingWallVelocityFvPatchVectorField.C.
adjointRotatingWallVelocityFvPatchVectorField() [3/4]
adjointRotatingWallVelocityFvPatchVectorField (const adjointRotatingWallVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 41 of file adjointRotatingWallVelocityFvPatchVectorField.C.
adjointRotatingWallVelocityFvPatchVectorField() [4/4]
adjointRotatingWallVelocityFvPatchVectorField (const adjointRotatingWallVelocityFvPatchVectorField & pivpvf, const DimensionedField< vector, volMesh > & iF)
Definition at line 72 of file adjointRotatingWallVelocityFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("adjointRotatingWallVelocity")
clone() [1/2]
virtual tmp< fvPatchVectorField > clone () const inline virtual
Reimplemented from adjointWallVelocityFvPatchVectorField.
Definition at line 103 of file adjointRotatingWallVelocityFvPatchVectorField.H.
clone() [2/2]
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Reimplemented from adjointWallVelocityFvPatchVectorField.
Definition at line 119 of file adjointRotatingWallVelocityFvPatchVectorField.H.
dxdbMult()
Foam::tmp< Foam::tensorField > dxdbMult () const virtual
Reimplemented from adjointBoundaryCondition< Type >.
Definition at line 89 of file adjointRotatingWallVelocityFvPatchVectorField.C.
References Foam::mag(), tmp< T >::New(), om, Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
write()
void write (Ostream & os) const virtual
Reimplemented from adjointWallVelocityFvPatchVectorField.
Definition at line 105 of file adjointRotatingWallVelocityFvPatchVectorField.C.
References os(), adjointWallVelocityFvPatchVectorField::write(), and Ostream::writeEntry().
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/adjointBoundaryConditions/adjointRotatingWallVelocity/adjointRotatingWallVelocityFvPatchVectorField.H
src/optimisation/adjointOptimisation/adjoint/adjointBoundaryConditions/adjointRotatingWallVelocity/adjointRotatingWallVelocityFvPatchVectorField.C