OpenFOAM: effectivenessTable Class Reference
effectivenessTable Class Reference
A heat exchanger model where heat exchange is calculated via an effectiveness table.
#include <effectivenessTable.H>
Public Member Functions
TypeName ("effectivenessTable")
effectivenessTable (const fvMesh &mesh, const word &name, const dictionary &coeffs)
effectivenessTable (const effectivenessTable &)=delete
void operator= (const effectivenessTable &)=delete
virtual ~effectivenessTable ()=default
virtual void initialise ()
virtual tmp< scalarField > energyDensity (const labelList &cells)
virtual bool read (const dictionary &dict)
virtual void write (const bool log)
Public Member Functions inherited from heatExchangerModel
TypeName ("heatExchangerModel")
declareRunTimeSelectionTable (autoPtr, heatExchangerModel, dictionary,(const fvMesh &mesh, const word &name, const dictionary &coeffs),(mesh, name, coeffs))
heatExchangerModel (const fvMesh &mesh, const word &name, const dictionary &coeffs)
heatExchangerModel (const heatExchangerModel &)=delete
void operator= (const heatExchangerModel &)=delete
virtual ~heatExchangerModel ()=default
virtual const word & U () const
Public Member Functions inherited from writeFile
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name="undefined", const bool writeToFile=true)
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name, const dictionary &dict, const bool writeToFile=true)
writeFile (const writeFile &wf)
virtual ~writeFile ()=default
virtual OFstream & file ()
virtual bool writeToFile () const
virtual bool canWriteToFile () const
virtual bool canResetFile () const
virtual bool canWriteHeader () const
virtual label charWidth () const
virtual void writeCommented (Ostream &os, const string &str) const
virtual void writeTabbed (Ostream &os, const string &str) const
virtual void writeHeader (Ostream &os, const string &str) const
virtual void writeCurrentTime (Ostream &os) const
virtual void writeBreak (Ostream &os) const
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
template<class Type >
void writeValue (Ostream &os, const Type &val) const
Additional Inherited Members
Static Public Member Functions inherited from heatExchangerModel
static autoPtr< heatExchangerModel > New (const fvMesh &mesh, const word &name, const dictionary &coeffs)
Static Public Attributes inherited from writeFile
static label addChars = 8
Protected Member Functions inherited from writeFile
void initStream (Ostream &os) const
fileName baseFileDir () const
fileName baseTimeDir () const
fileName filePath (const fileName &fName) const
virtual autoPtr< OFstream > newFile (const fileName &fName) const
virtual autoPtr< OFstream > newFileAtTime (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > newFileAtStartTime (const word &name) const
virtual void resetFile (const word &name)
Omanip< int > valueWidth (const label offset=0) const
void operator= (const writeFile &)=delete
virtual autoPtr< OFstream > createFile (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > createFile (const word &name) const
Protected Attributes inherited from heatExchangerModel
const fvMesh & mesh_
const dictionary & coeffs_
const word & name_
word UName_
word TName_
word phiName_
word faceZoneName_
labelList faceId_
labelList facePatchId_
labelList faceSign_
Protected Attributes inherited from writeFile
const objectRegistry & fileObr_
const fileName prefix_
word fileName_
autoPtr< OFstream > filePtr_
label writePrecision_
bool writeToFile_
bool updateHeader_
bool writtenHeader_
bool useUserTime_
scalar startTime_
Detailed Description
A heat exchanger model where heat exchange is calculated via an effectiveness table.
The total heat exchange source is given by:
where:
= Total heat exchange source [J/s]
= Effectivenes table [-]
= Net mass flux entering heat exchanger [kg/s]
= Secondary flow mass flow rate [kg/s]
= Primary flow inlet temperature [K]
= Secondary flow inlet temperature [K]
= Primary flow specific heat capacity [J/kg/K]
The distribution inside the heat exchanger is given by:
where:
= Source for cell
= Volume of the cell [m^3]
= Local cell velocity [m/s]
= Local cell temperature [K]
= Min or max(T) in cell zone depending on the sign of Qt [K]
Usage
Minimal example by using constant/fvOptions:
<name>
{
    // Inherited entries
    ...
    // Mandatory entries
    model                    effectivenessTable;
    secondaryMassFlowRate    <scalar>;
    secondaryInletT          <scalar>;
    file                     "<word>";
    outOfBounds              <word>;
    // Conditional optional entries
        // when the total heat exchange is calculated with primary inlet T
        primaryInletT           <scalar>;
        // when the total heat exchange is calculated with a given target
        targetQdot              <scalar>;
        targetQdotCalcInterval  <label>;
        targetQdotRelax         <scalar>;
        // when secondary outlet temperature is requested
        secondaryCp             <Function1<scalar>>;
}
where the entries mean:
Property Description Type Reqd Deflt
model Model name:effectivenessTable word yes -
secondaryMassFlowRate
Secondary flow mass rate [kg/s]
scalar yes -
secondaryInletT
Secondary flow inlet temperature [K]
scalar yes -
file
2D effectiveness table = function of primary
and secondary mass flow rates [kg/s]
file yes -
primaryInletT
Primary flow temperature at the heat exchanger inlet
scalar no -
targetQdot Target heat rejection scalar no -
targetQdotCalcInterval
Target heat rejection calculation interval
label no -
targetQdotRelax
Target heat rejection temperature
under-relaxation coefficient
scalar no -
secondaryCp
Secondary flow specific heat capacity
Function1<scalar> no -
The inherited entries are elaborated in:
heatExchangerSource.H
interpolation2DTable.H
The effectiveness table is described in terms of the primary and secondary mass flow rates. For example, the table:
                           secondary MFR
                       |  0.1   0.2   0.3
                  -----+-----------------
                  0.02 |   A     B     C
     primary MFR  0.04 |   D     E     F
                  0.06 |   G     H     I
is specified by the following:
        (
            (
                0.02
                (
                    (0.1    A)
                    (0.2    B)
                    (0.3    C)
                )
            )
            (
                0.04
                (
                    (0.1    D)
                    (0.2    E)
                    (0.3    F)
                )
            )
            (
                0.06
                (
                    (0.1    G)
                    (0.2    H)
                    (0.3    I)
                )
            )
        );
Note
Primary flow indicates the CFD flow region and secondary flow the non-CFD-model region.
The table with name file should have the same units as the secondary mass flow rate and kg/s for phi.
faceZone is the faces at the inlet of the cellZone, it needs to be created with flip map flags. It is used to integrate the net mass flow rate into the heat exchanger.
primaryInletT sets the primary inlet temperature. If not set, the flux-averaged temperature is used.
Source files
effectivenessTable.H
effectivenessTable.C
Definition at line 312 of file effectivenessTable.H.
Constructor & Destructor Documentation
effectivenessTable() [1/2]
effectivenessTable (const fvMesh & mesh, const word & name, const dictionary & coeffs)
Definition at line 69 of file effectivenessTable.C.
References writeFile::file().
effectivenessTable() [2/2]
effectivenessTable (const effectivenessTable &) delete
~effectivenessTable()
virtual ~effectivenessTable () virtual default
Member Function Documentation
TypeName()
TypeName ("effectivenessTable")
operator=()
void operator= (const effectivenessTable &) delete
initialise()
void initialise () virtual
Reimplemented from heatExchangerModel.
Definition at line 107 of file effectivenessTable.C.
References heatExchangerModel::initialise().
energyDensity()
Foam::tmp< Foam::scalarField > energyDensity (const labelList & cells) virtual
Implements heatExchangerModel.
Definition at line 116 of file effectivenessTable.C.
References alpha, GeometricField< Type, PatchField, GeoMesh >::boundaryField(), cells, basicThermo::dictName, forAll, Foam::gMax(), Foam::gMin(), Foam::fvc::interpolate(), Foam::mag(), Foam::max(), phi, Foam::reduce(), T, U, and Foam::Zero.
read()
bool read (const dictionary & dict) virtual
Implements heatExchangerModel.
Definition at line 225 of file effectivenessTable.C.
References Foam::decrIndent(), dict, Foam::endl(), Foam::incrIndent(), Foam::indent(), Foam::Info, Foam::nl, and Foam::type().
write()
void write (const bool log) virtual
Implements heatExchangerModel.
Definition at line 284 of file effectivenessTable.C.
References Foam::decrIndent(), Foam::endl(), Foam::incrIndent(), Foam::indent(), Foam::Info, Foam::log(), UPstream::master(), Foam::nl, os(), Foam::tab, and Foam::type().
The documentation for this class was generated from the following files:
src/fvOptions/sources/derived/heatExchangerSource/heatExchangerModels/effectivenessTable/effectivenessTable.H
src/fvOptions/sources/derived/heatExchangerSource/heatExchangerModels/effectivenessTable/effectivenessTable.C