OpenFOAM: GAMGAgglomeration Class Reference
GAMGAgglomeration Class Reference abstract
Geometric agglomerated algebraic multigrid agglomeration class.
#include <GAMGAgglomeration.H>
Public Member Functions
TypeName ("GAMGAgglomeration")
declareRunTimeSelectionTable (autoPtr, GAMGAgglomeration, lduMesh,(const lduMesh &mesh, const dictionary &controlDict),(mesh, controlDict))
declareRunTimeSelectionTable (autoPtr, GAMGAgglomeration, lduMatrix,(const lduMatrix &matrix, const dictionary &controlDict),(matrix, controlDict))
declareRunTimeSelectionTable (autoPtr, GAMGAgglomeration, geometry,(const lduMesh &mesh, const scalarField &cellVolumes, const vectorField &faceAreas, const dictionary &controlDict),(mesh, cellVolumes, faceAreas, controlDict))
GAMGAgglomeration (const lduMesh &mesh, const dictionary &controlDict)
~GAMGAgglomeration ()
label size () const
const lduMesh & meshLevel (const label leveli) const
bool hasMeshLevel (const label leveli) const
const lduInterfacePtrsList & interfaceLevel (const label leveli) const
const labelField & restrictAddressing (const label leveli) const
const labelList & faceRestrictAddressing (const label leveli) const
const labelListList & patchFaceRestrictAddressing (const label leveli) const
const boolList & faceFlipMap (const label leveli) const
label nCells (const label leveli) const
label nFaces (const label leveli) const
const labelList & nPatchFaces (const label leveli) const
template<class Type >
void restrictField (Field< Type > &cf, const Field< Type > &ff, const label fineLevelIndex, const bool procAgglom) const
template<class Type >
void restrictFaceField (Field< Type > &cf, const Field< Type > &ff, const label fineLevelIndex) const
template<class Type >
void restrictField (Field< Type > &cf, const Field< Type > &ff, const labelList &fineToCoarse) const
template<class Type >
void prolongField (Field< Type > &ff, const Field< Type > &cf, const label coarseLevelIndex, const bool procAgglom) const
bool processorAgglomerate () const
const labelList & procAgglomMap (const label fineLeveli) const
const labelList & agglomProcIDs (const label fineLeveli) const
bool hasProcMesh (const label fineLeveli) const
label procCommunicator (const label fineLeveli) const
const labelList & cellOffsets (const label fineLeveli) const
const labelListList & faceMap (const label fineLeveli) const
const labelListList & boundaryMap (const label fineLeveli) const
const labelListListList & boundaryFaceMap (const label fineLeveli) const
virtual void agglomerate (const label nCellsInCoarsestLevel, const label startLevel, const scalarField &startFaceWeights, const bool doProcessorAgglomerate=true)=0
Public Member Functions inherited from MeshObject< lduMesh, GeometricMeshObject, GAMGAgglomeration >
MeshObject (const lduMesh &mesh)
MeshObject (const word &objName, const lduMesh &mesh)
virtual ~MeshObject ()=default
const lduMesh & mesh () const noexcept
virtual bool writeData (Ostream &os) const
Static Public Member Functions
static const GAMGAgglomeration & New (const lduMesh &mesh, const dictionary &controlDict)
static const GAMGAgglomeration & New (const lduMatrix &matrix, const dictionary &controlDict)
static const GAMGAgglomeration & New (const lduMesh &mesh, const scalarField &cellVolumes, const vectorField &faceAreas, const dictionary &controlDict)
static void calculateRegionMaster (const label comm, const labelList &procAgglomMap, labelList &masterProcs, List< label > &agglomProcIDs)
static bool checkRestriction (labelList &newRestrict, label &nNewCoarse, const lduAddressing &fineAddressing, const labelUList &restriction, const label nCoarse)
Static Public Member Functions inherited from MeshObject< lduMesh, GeometricMeshObject, GAMGAgglomeration >
static const GAMGAgglomeration & New (const lduMesh &mesh, Args &&... args)
static const GAMGAgglomeration & New (const word &objName, const lduMesh &mesh, Args &&... args)
static bool Delete (const word &objName, const lduMesh &mesh)
static bool Delete (const lduMesh &mesh)
Protected Member Functions
void agglomerateLduAddressing (const label fineLevelIndex)
void combineLevels (const label curLevel)
void compactLevels (const label nCreatedLevels, const bool doProcessorAgglomerate)
bool continueAgglomerating (const label nCellsInCoarsestLevel, const label nCells, const label nCoarseCells, const label comm) const
void clearLevel (const label leveli)
void printLevels () const
void procAgglomerateLduAddressing (const label comm, const labelList &procAgglomMap, const labelList &procIDs, const label allMeshComm, const label levelIndex)
void procAgglomerateRestrictAddressing (const label comm, const labelList &procIDs, const label levelIndex)
GAMGAgglomeration (const GAMGAgglomeration &)=delete
void operator= (const GAMGAgglomeration &)=delete
Protected Attributes
const label maxLevels_
label nCellsInCoarsestLevel_
const lduInterfacePtrsList meshInterfaces_
autoPtr< GAMGProcAgglomeration > procAgglomeratorPtr_
labelList nCells_
PtrList< labelField > restrictAddressing_
labelList nFaces_
PtrList< labelList > faceRestrictAddressing_
PtrList< boolList > faceFlipMap_
PtrList< labelList > nPatchFaces_
PtrList< labelListList > patchFaceRestrictAddressing_
PtrList< lduPrimitiveMesh > meshLevels_
PtrList< labelList > procAgglomMap_
PtrList< labelList > agglomProcIDs_
labelList procCommunicator_
PtrList< labelList > procCellOffsets_
PtrList< labelListList > procFaceMap_
PtrList< labelListList > procBoundaryMap_
PtrList< labelListListList > procBoundaryFaceMap_
Protected Attributes inherited from MeshObject< lduMesh, GeometricMeshObject, GAMGAgglomeration >
const lduMesh & mesh_
Friends
class GAMGProcAgglomeration
Detailed Description
Geometric agglomerated algebraic multigrid agglomeration class.
Source files
GAMGAgglomeration.H
GAMGAgglomeration.C
GAMGAgglomerationTemplates.C
GAMGAgglomerateLduAddressing.C
Definition at line 61 of file GAMGAgglomeration.H.
Constructor & Destructor Documentation
GAMGAgglomeration() [1/2]
GAMGAgglomeration (const GAMGAgglomeration &) protected delete
GAMGAgglomeration() [2/2]
GAMGAgglomeration (const lduMesh & mesh, const dictionary & controlDict)
Definition at line 232 of file GAMGAgglomeration.C.
References GAMGAgglomeration::agglomProcIDs_, Foam::max(), GAMGAgglomeration::maxLevels_, MeshObject< lduMesh, GeometricMeshObject, GAMGAgglomeration >::mesh(), Foam::min(), GAMGAgglomeration::nCellsInCoarsestLevel_, GAMGAgglomeration::procAgglomMap_, GAMGAgglomeration::procBoundaryFaceMap_, GAMGAgglomeration::procBoundaryMap_, GAMGAgglomeration::procCellOffsets_, GAMGAgglomeration::procCommunicator_, GAMGAgglomeration::processorAgglomerate(), GAMGAgglomeration::procFaceMap_, Foam::reduce(), List< T >::setSize(), PtrList< T >::setSize(), and UPtrList< T >::size().
~GAMGAgglomeration()
~GAMGAgglomeration ()
Definition at line 464 of file GAMGAgglomeration.C.
Member Function Documentation
agglomerateLduAddressing()
void agglomerateLduAddressing (const label fineLevelIndex) protected
Definition at line 29 of file GAMGAgglomerateLduAddressing.C.
References Foam::abort(), Foam::endl(), Foam::exit(), GAMGAgglomeration::faceFlipMap(), GAMGAgglomeration::faceFlipMap_, GAMGAgglomeration::faceRestrictAddressing_, Foam::FatalError, FatalErrorInFunction, forAll, forAllReverse, GAMGAgglomeration::interfaceLevel(), GAMGAgglomeration::meshLevel(), GAMGAgglomeration::meshLevels_, Foam::min(), GAMGAgglomeration::nCells_, GAMGInterface::New(), GAMGAgglomeration::nFaces_, UPstream::nonBlocking, GAMGAgglomeration::nPatchFaces(), GAMGAgglomeration::nPatchFaces_, UPstream::nRequests(), GAMGAgglomeration::patchFaceRestrictAddressing_, Foam::Pout, GAMGAgglomeration::restrictAddressing(), PtrList< T >::set(), UPtrList< T >::set(), PtrList< T >::setSize(), UPtrList< T >::size(), UList< T >::size(), UPstream::waitRequests(), and Foam::Zero.
Referenced by pairGAMGAgglomeration::agglomerate(), and dummyAgglomeration::dummyAgglomeration().
combineLevels()
void combineLevels (const label curLevel) protected
Definition at line 565 of file GAMGAgglomerateLduAddressing.C.
References forAll, and PtrList< T >::set().
Referenced by pairGAMGAgglomeration::agglomerate().
compactLevels()
void compactLevels (const label nCreatedLevels, const bool doProcessorAgglomerate) protected
Definition at line 44 of file GAMGAgglomeration.C.
References GAMGAgglomeration::agglomProcIDs_, GAMGAgglomeration::faceFlipMap_, GAMGAgglomeration::faceRestrictAddressing_, GAMGAgglomeration::meshLevels_, GAMGAgglomeration::nCells_, GAMGAgglomeration::nFaces_, GAMGAgglomeration::nPatchFaces_, GAMGAgglomeration::patchFaceRestrictAddressing_, GAMGAgglomeration::procAgglomeratorPtr_, GAMGAgglomeration::procAgglomMap_, GAMGAgglomeration::procBoundaryFaceMap_, GAMGAgglomeration::procBoundaryMap_, GAMGAgglomeration::procCellOffsets_, GAMGAgglomeration::procCommunicator_, GAMGAgglomeration::processorAgglomerate(), GAMGAgglomeration::procFaceMap_, GAMGAgglomeration::restrictAddressing_, List< T >::setSize(), and PtrList< T >::setSize().
Referenced by pairGAMGAgglomeration::agglomerate(), and dummyAgglomeration::dummyAgglomeration().
continueAgglomerating()
bool continueAgglomerating (const label nCellsInCoarsestLevel, const label nCells, const label nCoarseCells, const label comm) const protected
Definition at line 207 of file GAMGAgglomeration.C.
References UPstream::msgType(), UPstream::nProcs(), and Foam::returnReduce().
Referenced by pairGAMGAgglomeration::agglomerate().
clearLevel()
void clearLevel (const label leveli) protected
Definition at line 515 of file GAMGAgglomeration.C.
References PtrList< T >::set(), and UPtrList< T >::size().
printLevels()
void printLevels () const protected
Definition at line 75 of file GAMGAgglomeration.C.
References Foam::endl(), forAll, Foam::Info, Foam::nl, OSstream::precision(), Foam::returnReduce(), UPtrList< T >::set(), Foam::setw(), UPtrList< T >::size(), messageStream::stream(), and Foam::type().
procAgglomerateLduAddressing()
void procAgglomerateLduAddressing (const label comm, const labelList & procAgglomMap, const labelList & procIDs, const label allMeshComm, const label levelIndex) protected
Definition at line 416 of file GAMGAgglomerateLduAddressing.C.
References lduPrimitiveMesh::gather(), UPstream::myProcNo(), and PtrList< T >::set().
procAgglomerateRestrictAddressing()
void procAgglomerateRestrictAddressing (const label comm, const labelList & procIDs, const label levelIndex) protected
Definition at line 489 of file GAMGAgglomerateLduAddressing.C.
References globalIndex::calcOffsets(), forAll, globalIndex::gather(), globalIndex::gatherValues(), UPtrList< T >::last(), UPstream::msgType(), UPstream::myProcNo(), UPstream::nonBlocking, UPstream::scheduled, UPtrList< T >::size(), and PtrList< T >::transfer().
operator=()
void operator= (const GAMGAgglomeration &) protected delete
TypeName()
TypeName ("GAMGAgglomeration")
declareRunTimeSelectionTable() [1/3]
declareRunTimeSelectionTable (autoPtr , GAMGAgglomeration , lduMesh , (const lduMesh &mesh, const dictionary &controlDict) , (mesh, controlDict))
declareRunTimeSelectionTable() [2/3]
declareRunTimeSelectionTable (autoPtr , GAMGAgglomeration , lduMatrix , (const lduMatrix &matrix, const dictionary &controlDict) , (matrix, controlDict))
declareRunTimeSelectionTable() [3/3]
declareRunTimeSelectionTable (autoPtr , GAMGAgglomeration , geometry , (const lduMesh &mesh, const scalarField &cellVolumes, const vectorField &faceAreas, const dictionary &controlDict) , (mesh, cellVolumes, faceAreas, controlDict))
New() [1/3]
const Foam::GAMGAgglomeration & New (const lduMesh & mesh, const dictionary & controlDict) static
Definition at line 293 of file GAMGAgglomeration.C.
References controlDict(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, mesh, and fvMesh::thisDb().
New() [2/3]
const Foam::GAMGAgglomeration & New (const lduMatrix & matrix, const dictionary & controlDict) static
Definition at line 347 of file GAMGAgglomeration.C.
References controlDict(), mesh, lduMatrix::mesh(), Foam::New(), and fvMesh::thisDb().
New() [3/3]
const Foam::GAMGAgglomeration & New (const lduMesh & mesh, const scalarField & cellVolumes, const vectorField & faceAreas, const dictionary & controlDict) static
Definition at line 398 of file GAMGAgglomeration.C.
References controlDict(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, mesh, and fvMesh::thisDb().
size()
label size () const inline
Definition at line 320 of file GAMGAgglomeration.H.
References GAMGAgglomeration::meshLevels_, and UPtrList< T >::size().
Referenced by pairGAMGAgglomeration::agglomerate(), and assemblyFaceAreaPairGAMGAgglomeration::assemblyFaceAreaPairGAMGAgglomeration().
meshLevel()
const Foam::lduMesh & meshLevel (const label leveli) const
Definition at line 470 of file GAMGAgglomeration.C.
Referenced by pairGAMGAgglomeration::agglomerate(), and GAMGAgglomeration::agglomerateLduAddressing().
hasMeshLevel()
bool hasMeshLevel (const label leveli) const
Definition at line 486 of file GAMGAgglomeration.C.
References PtrList< T >::set().
Referenced by pairGAMGAgglomeration::agglomerate().
interfaceLevel()
const Foam::lduInterfacePtrsList & interfaceLevel (const label leveli) const
Definition at line 499 of file GAMGAgglomeration.C.
Referenced by GAMGAgglomeration::agglomerateLduAddressing().
restrictAddressing()
const labelField & restrictAddressing (const label leveli) const inline
Definition at line 338 of file GAMGAgglomeration.H.
References GAMGAgglomeration::restrictAddressing_.
Referenced by GAMGAgglomeration::agglomerateLduAddressing().
faceRestrictAddressing()
const labelList & faceRestrictAddressing (const label leveli) const inline
Definition at line 344 of file GAMGAgglomeration.H.
References GAMGAgglomeration::faceRestrictAddressing_.
patchFaceRestrictAddressing()
const labelListList & patchFaceRestrictAddressing (const label leveli) const inline
Definition at line 349 of file GAMGAgglomeration.H.
References GAMGAgglomeration::patchFaceRestrictAddressing_.
faceFlipMap()
const boolList & faceFlipMap (const label leveli) const inline
Definition at line 356 of file GAMGAgglomeration.H.
References GAMGAgglomeration::faceFlipMap_.
Referenced by GAMGAgglomeration::agglomerateLduAddressing().
nCells()
label nCells (const label leveli) const inline
Definition at line 362 of file GAMGAgglomeration.H.
References GAMGAgglomeration::nCells_.
nFaces()
label nFaces (const label leveli) const inline
Definition at line 368 of file GAMGAgglomeration.H.
References GAMGAgglomeration::nFaces_.
nPatchFaces()
const labelList & nPatchFaces (const label leveli) const inline
Definition at line 375 of file GAMGAgglomeration.H.
References GAMGAgglomeration::nPatchFaces_.
Referenced by GAMGAgglomeration::agglomerateLduAddressing().
restrictField() [1/2]
template<class Type > void restrictField (Field< Type > & cf, const Field< Type > & ff, const label fineLevelIndex, const bool procAgglom) const
Definition at line 45 of file GAMGAgglomerationTemplates.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, globalIndex::gather(), UPstream::msgType(), UPstream::nonBlocking, UPstream::parent(), and UPtrList< T >::size().
restrictFaceField()
template<class Type > void restrictFaceField (Field< Type > & cf, const Field< Type > & ff, const label fineLevelIndex) const
Definition at line 90 of file GAMGAgglomerationTemplates.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, UPtrList< T >::size(), and Foam::Zero.
Referenced by pairGAMGAgglomeration::agglomerate().
restrictField() [2/2]
template<class Type > void restrictField (Field< Type > & cf, const Field< Type > & ff, const labelList & fineToCoarse) const
Definition at line 28 of file GAMGAgglomerationTemplates.C.
References forAll, and Foam::Zero.
prolongField()
template<class Type > void prolongField (Field< Type > & ff, const Field< Type > & cf, const label coarseLevelIndex, const bool procAgglom) const
Definition at line 123 of file GAMGAgglomerationTemplates.C.
References forAll, UPstream::msgType(), UPstream::nonBlocking, UPstream::parent(), and globalIndex::scatter().
calculateRegionMaster()
void calculateRegionMaster (const label comm, const labelList & procAgglomMap, labelList & masterProcs, List< label > & agglomProcIDs) static
Definition at line 664 of file GAMGAgglomerateLduAddressing.C.
References Foam::findIndices(), forAll, forAllConstIters, Foam::min(), UPstream::myProcNo(), PtrList< T >::setSize(), UPtrList< T >::size(), and UList< T >::size().
Referenced by eagerGAMGProcAgglomeration::agglomerate(), masterCoarsestGAMGProcAgglomeration::agglomerate(), and procFacesGAMGProcAgglomeration::agglomerate().
processorAgglomerate()
bool processorAgglomerate () const inline
Definition at line 442 of file GAMGAgglomeration.H.
References GAMGAgglomeration::procAgglomeratorPtr_.
Referenced by pairGAMGAgglomeration::agglomerate(), GAMGAgglomeration::compactLevels(), and GAMGAgglomeration::GAMGAgglomeration().
procAgglomMap()
const Foam::labelList & procAgglomMap (const label fineLeveli) const
Definition at line 535 of file GAMGAgglomeration.C.
agglomProcIDs()
const Foam::labelList & agglomProcIDs (const label fineLeveli) const
Definition at line 544 of file GAMGAgglomeration.C.
hasProcMesh()
bool hasProcMesh (const label fineLeveli) const
Definition at line 553 of file GAMGAgglomeration.C.
procCommunicator()
Foam::label procCommunicator (const label fineLeveli) const
Definition at line 559 of file GAMGAgglomeration.C.
cellOffsets()
const Foam::labelList & cellOffsets (const label fineLeveli) const
Definition at line 565 of file GAMGAgglomeration.C.
faceMap()
const Foam::labelListList & faceMap (const label fineLeveli) const
Definition at line 574 of file GAMGAgglomeration.C.
boundaryMap()
const Foam::labelListList & boundaryMap (const label fineLeveli) const
Definition at line 583 of file GAMGAgglomeration.C.
boundaryFaceMap()
const Foam::labelListListList & boundaryFaceMap (const label fineLeveli) const
Definition at line 592 of file GAMGAgglomeration.C.
agglomerate()
virtual void agglomerate (const label nCellsInCoarsestLevel, const label startLevel, const scalarField & startFaceWeights, const bool doProcessorAgglomerate = true) pure virtual
Implemented in MGridGenGAMGAgglomeration, dummyAgglomeration, and pairGAMGAgglomeration.
checkRestriction()
bool checkRestriction (labelList & newRestrict, label & nNewCoarse, const lduAddressing & fineAddressing, const labelUList & restriction, const label nCoarse) static
Definition at line 601 of file GAMGAgglomeration.C.
References Foam::abort(), PtrList< T >::append(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::identity(), Foam::reduce(), PtrList< T >::setSize(), and UPtrList< T >::size().
Friends And Related Symbol Documentation
GAMGProcAgglomeration
friend class GAMGProcAgglomeration friend
Definition at line 213 of file GAMGAgglomeration.H.
Member Data Documentation
maxLevels_
const label maxLevels_ protected
Definition at line 70 of file GAMGAgglomeration.H.
Referenced by pairGAMGAgglomeration::agglomerate(), and GAMGAgglomeration::GAMGAgglomeration().
nCellsInCoarsestLevel_
label nCellsInCoarsestLevel_ protected
Definition at line 73 of file GAMGAgglomeration.H.
Referenced by algebraicPairGAMGAgglomeration::algebraicPairGAMGAgglomeration(), assemblyFaceAreaPairGAMGAgglomeration::assemblyFaceAreaPairGAMGAgglomeration(), assemblyFaceAreaPairGAMGAgglomeration::assemblyFaceAreaPairGAMGAgglomeration(), faceAreaPairGAMGAgglomeration::faceAreaPairGAMGAgglomeration(), faceAreaPairGAMGAgglomeration::faceAreaPairGAMGAgglomeration(), and GAMGAgglomeration::GAMGAgglomeration().
meshInterfaces_
const lduInterfacePtrsList meshInterfaces_ protected
Definition at line 76 of file GAMGAgglomeration.H.
procAgglomeratorPtr_
autoPtr<GAMGProcAgglomeration> procAgglomeratorPtr_ protected
Definition at line 78 of file GAMGAgglomeration.H.
Referenced by GAMGAgglomeration::compactLevels(), and GAMGAgglomeration::processorAgglomerate().
nCells_
labelList nCells_ protected
Definition at line 81 of file GAMGAgglomeration.H.
Referenced by pairGAMGAgglomeration::agglomerate(), GAMGAgglomeration::agglomerateLduAddressing(), GAMGAgglomeration::compactLevels(), dummyAgglomeration::dummyAgglomeration(), and GAMGAgglomeration::nCells().
restrictAddressing_
PtrList<labelField> restrictAddressing_ protected
Definition at line 85 of file GAMGAgglomeration.H.
Referenced by pairGAMGAgglomeration::agglomerate(), GAMGAgglomeration::compactLevels(), dummyAgglomeration::dummyAgglomeration(), and GAMGAgglomeration::restrictAddressing().
nFaces_
labelList nFaces_ protected
Definition at line 89 of file GAMGAgglomeration.H.
Referenced by pairGAMGAgglomeration::agglomerate(), GAMGAgglomeration::agglomerateLduAddressing(), GAMGAgglomeration::compactLevels(), and GAMGAgglomeration::nFaces().
faceRestrictAddressing_
PtrList<labelList> faceRestrictAddressing_ protected
Definition at line 97 of file GAMGAgglomeration.H.
Referenced by pairGAMGAgglomeration::agglomerate(), GAMGAgglomeration::agglomerateLduAddressing(), GAMGAgglomeration::compactLevels(), and GAMGAgglomeration::faceRestrictAddressing().
faceFlipMap_
PtrList<boolList> faceFlipMap_ protected
Definition at line 102 of file GAMGAgglomeration.H.
Referenced by pairGAMGAgglomeration::agglomerate(), GAMGAgglomeration::agglomerateLduAddressing(), GAMGAgglomeration::compactLevels(), and GAMGAgglomeration::faceFlipMap().
nPatchFaces_
PtrList<labelList> nPatchFaces_ protected
Definition at line 106 of file GAMGAgglomeration.H.
Referenced by pairGAMGAgglomeration::agglomerate(), GAMGAgglomeration::agglomerateLduAddressing(), GAMGAgglomeration::compactLevels(), and GAMGAgglomeration::nPatchFaces().
patchFaceRestrictAddressing_
PtrList<labelListList> patchFaceRestrictAddressing_ protected
Definition at line 111 of file GAMGAgglomeration.H.
Referenced by pairGAMGAgglomeration::agglomerate(), GAMGAgglomeration::agglomerateLduAddressing(), GAMGAgglomeration::compactLevels(), and GAMGAgglomeration::patchFaceRestrictAddressing().
meshLevels_
PtrList<lduPrimitiveMesh> meshLevels_ protected
Definition at line 114 of file GAMGAgglomeration.H.
Referenced by pairGAMGAgglomeration::agglomerate(), GAMGAgglomeration::agglomerateLduAddressing(), GAMGAgglomeration::compactLevels(), and GAMGAgglomeration::size().
procAgglomMap_
PtrList<labelList> procAgglomMap_ mutable protected
Definition at line 120 of file GAMGAgglomeration.H.
Referenced by pairGAMGAgglomeration::agglomerate(), GAMGAgglomeration::compactLevels(), and GAMGAgglomeration::GAMGAgglomeration().
agglomProcIDs_
PtrList<labelList> agglomProcIDs_ mutable protected
Definition at line 124 of file GAMGAgglomeration.H.
Referenced by pairGAMGAgglomeration::agglomerate(), GAMGAgglomeration::compactLevels(), and GAMGAgglomeration::GAMGAgglomeration().
procCommunicator_
labelList procCommunicator_ mutable protected
Definition at line 127 of file GAMGAgglomeration.H.
Referenced by pairGAMGAgglomeration::agglomerate(), GAMGAgglomeration::compactLevels(), and GAMGAgglomeration::GAMGAgglomeration().
procCellOffsets_
PtrList<labelList> procCellOffsets_ mutable protected
Definition at line 130 of file GAMGAgglomeration.H.
Referenced by pairGAMGAgglomeration::agglomerate(), GAMGAgglomeration::compactLevels(), and GAMGAgglomeration::GAMGAgglomeration().
procFaceMap_
PtrList<labelListList> procFaceMap_ mutable protected
Definition at line 133 of file GAMGAgglomeration.H.
Referenced by pairGAMGAgglomeration::agglomerate(), GAMGAgglomeration::compactLevels(), and GAMGAgglomeration::GAMGAgglomeration().
procBoundaryMap_
PtrList<labelListList> procBoundaryMap_ mutable protected
Definition at line 136 of file GAMGAgglomeration.H.
Referenced by pairGAMGAgglomeration::agglomerate(), GAMGAgglomeration::compactLevels(), and GAMGAgglomeration::GAMGAgglomeration().
procBoundaryFaceMap_
PtrList<labelListListList> procBoundaryFaceMap_ mutable protected
Definition at line 139 of file GAMGAgglomeration.H.
Referenced by pairGAMGAgglomeration::agglomerate(), GAMGAgglomeration::compactLevels(), and GAMGAgglomeration::GAMGAgglomeration().
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/GAMGAgglomerations/GAMGAgglomeration/GAMGAgglomeration.H
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/GAMGAgglomerations/GAMGAgglomeration/GAMGAgglomerateLduAddressing.C
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/GAMGAgglomerations/GAMGAgglomeration/GAMGAgglomeration.C
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/GAMGAgglomerations/GAMGAgglomeration/GAMGAgglomerationTemplates.C