OpenFOAM: constantNucleation Class Reference
constantNucleation Class Reference
Constant nucleation rate within all classes. Used for verification and validation of the nucleation formulation implemented in the populationBalanceModel class. Rate is calculated from fvOptions mass source.
#include <constantNucleation.H>
Public Member Functions
TypeName ("constant")
constantNucleation (const populationBalanceModel &popBal, const dictionary &dict)
virtual ~constantNucleation ()=default
virtual void correct ()
virtual void addToNucleationRate (volScalarField &nucleationRate, const label i)
Public Member Functions inherited from nucleationModel
TypeName ("nucleationModel")
declareRunTimeSelectionTable (autoPtr, nucleationModel, dictionary,(const populationBalanceModel &popBal, const dictionary &dict),(popBal, dict))
nucleationModel (const populationBalanceModel &popBal, const dictionary &dict)
autoPtr< nucleationModel > clone () const
virtual ~nucleationModel ()=default
const populationBalanceModel & popBal () const
Additional Inherited Members
Static Public Member Functions inherited from nucleationModel
static autoPtr< nucleationModel > New (const word &type, const populationBalanceModel &popBal, const dictionary &dict)
Protected Attributes inherited from nucleationModel
const populationBalanceModel & popBal_
Detailed Description
Constant nucleation rate within all classes. Used for verification and validation of the nucleation formulation implemented in the populationBalanceModel class. Rate is calculated from fvOptions mass source.
Source files
constantNucleation.H
constant.C
Definition at line 52 of file constantNucleation.H.
Constructor & Destructor Documentation
constantNucleation()
constantNucleation (const populationBalanceModel & popBal, const dictionary & dict)
Definition at line 47 of file constantNucleation.C.
References Foam::dimLength, and Foam::refCast().
~constantNucleation()
virtual ~constantNucleation () virtual default
Member Function Documentation
TypeName()
TypeName ("constant")
correct()
void correct () virtual
Reimplemented from nucleationModel.
Definition at line 75 of file constantNucleation.C.
References Foam::endl(), UPtrList< T >::first(), and WarningInFunction.
addToNucleationRate()
void addToNucleationRate (volScalarField & nucleationRate, const label i) virtual
Implements nucleationModel.
Definition at line 96 of file constantNucleation.C.
References Foam::pow3(), rho, and phase::rho().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/populationBalanceModel/nucleationModels/constantNucleation/constantNucleation.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/populationBalanceModel/nucleationModels/constantNucleation/constantNucleation.C