OpenFOAM: dlLibraryTable Class Reference
dlLibraryTable Class Reference
A table of dynamically loaded libraries.
#include <dlLibraryTable.H>
Public Types
typedef void(* loaderType) (bool)
Public Member Functions
ClassName ("dlLibraryTable")
dlLibraryTable ()=default
dlLibraryTable (const dlLibraryTable &)=delete
dlLibraryTable (dlLibraryTable &&)=default
void operator= (const dlLibraryTable &)=delete
dlLibraryTable & operator= (dlLibraryTable &&)=default
dlLibraryTable (const UList< fileName > &libNames, bool verbose=true)
dlLibraryTable (std::initializer_list< fileName > libNames, bool verbose=true)
dlLibraryTable (const word &libsEntry, const dictionary &dict, bool verbose=true)
dlLibraryTable (const dictionary &dict, const word &libsEntry, bool verbose=true)
~dlLibraryTable ()
bool empty () const noexcept
label size () const noexcept
List< fileName > loaded () const
const UList< fileName > & names () const
const UList< void * > & pointers () const
void clear ()
bool append (const fileName &libName)
label append (const UList< fileName > &libNames)
bool open (bool verbose=true)
void * open (const fileName &libName, bool verbose=true)
bool open (const UList< fileName > &libNames, bool verbose=true)
bool open (std::initializer_list< fileName > libNames, bool verbose=true)
void close (bool verbose=true)
bool close (const fileName &libName, bool verbose=true)
void * findLibrary (const fileName &libName)
bool open (const word &libsEntry, const dictionary &dict, bool verbose=true)
bool open (const dictionary &dict, const word &libsEntry)
template<class TablePtr >
bool open (const dictionary &dict, const word &libsEntry, const TablePtr &tablePtr, bool verbose=true)
InfoProxy< dlLibraryTable > info () const noexcept
Static Public Member Functions
static word basename (const fileName &libPath)
static word fullname (word libName)
static dlLibraryTable & libs ()
static bool loadHook (void *handle, const std::string &funcName, const bool verbose=false, const std::string &context="")
static bool unloadHook (void *handle, const std::string &funcName, const bool verbose=false, const std::string &context="")
Static Public Attributes
static int dlcloseOnTerminate
Detailed Description
A table of dynamically loaded libraries.
See also
Foam::dlOpen Foam::dlClose
Source files
dlLibraryTable.H
dlLibraryTable.C
dlLibraryTableTemplates.C
Definition at line 60 of file dlLibraryTable.H.
Member Typedef Documentation
loaderType
typedef void(* loaderType) (bool)
Definition at line 110 of file dlLibraryTable.H.
Constructor & Destructor Documentation
dlLibraryTable() [1/7]
dlLibraryTable () default
dlLibraryTable() [2/7]
dlLibraryTable (const dlLibraryTable &) delete
dlLibraryTable() [3/7]
dlLibraryTable (dlLibraryTable &&) default
dlLibraryTable() [4/7]
dlLibraryTable (const UList< fileName > & libNames, bool verbose = true) explicit
Definition at line 191 of file dlLibraryTable.C.
References dlLibraryTable::open().
dlLibraryTable() [5/7]
dlLibraryTable (std::initializer_list< fileName > libNames, bool verbose = true) explicit
Definition at line 201 of file dlLibraryTable.C.
References dlLibraryTable::open().
dlLibraryTable() [6/7]
dlLibraryTable (const word & libsEntry, const dictionary & dict, bool verbose = true)
Definition at line 211 of file dlLibraryTable.C.
References dict, keyType::LITERAL, dlLibraryTable::open(), and dictionary::readIfPresent().
dlLibraryTable() [7/7]
dlLibraryTable (const dictionary & dict, const word & libsEntry, bool verbose = true)
Definition at line 224 of file dlLibraryTable.C.
~dlLibraryTable()
~dlLibraryTable ()
Definition at line 238 of file dlLibraryTable.C.
References dlLibraryTable::dlcloseOnTerminate.
Member Function Documentation
ClassName()
ClassName ("dlLibraryTable")
operator=() [1/2]
void operator= (const dlLibraryTable &) delete
operator=() [2/2]
dlLibraryTable & operator= (dlLibraryTable &&) default
basename()
Foam::word basename (const fileName & libPath) static
Definition at line 53 of file dlLibraryTable.C.
References fileName::stem().
Referenced by codedBase::updateLibrary().
fullname()
Foam::word fullname (word libName) static
Definition at line 61 of file dlLibraryTable.C.
References UPtrList< T >::empty(), and EXT_SO.
Referenced by dynamicCode::libPath(), and dynamicCode::libRelPath().
libs()
Foam::dlLibraryTable & libs () static
Definition at line 73 of file dlLibraryTable.C.
loadHook()
bool loadHook (void * handle, const std::string & funcName, const bool verbose = false, const std::string & context = "") static
Parameters
context Calling context for warnings
Definition at line 134 of file dlLibraryTable.C.
unloadHook()
bool unloadHook (void * handle, const std::string & funcName, const bool verbose = false, const std::string & context = "") static
Parameters
context Calling context for warnings
Definition at line 146 of file dlLibraryTable.C.
empty()
bool empty () const noexcept
Definition at line 249 of file dlLibraryTable.C.
size()
Foam::label size () const noexcept
Definition at line 263 of file dlLibraryTable.C.
loaded()
Foam::List< Foam::fileName > loaded () const
Definition at line 286 of file dlLibraryTable.C.
References UPtrList< T >::empty(), forAll, and PtrList< T >::resize().
names()
const UList< fileName > & names () const inline
Definition at line 225 of file dlLibraryTable.H.
pointers()
const UList< void * > & pointers () const inline
Definition at line 231 of file dlLibraryTable.H.
clear()
void clear ()
Definition at line 279 of file dlLibraryTable.C.
References PtrList< T >::clear().
append() [1/2]
bool append (const fileName & libName)
Definition at line 372 of file dlLibraryTable.C.
References UPtrList< T >::empty(), and PtrList< T >::push_back().
Referenced by argList::argList().
append() [2/2]
Foam::label append (const UList< fileName > & libNames)
Definition at line 386 of file dlLibraryTable.C.
References append().
open() [1/7]
bool open (bool verbose = true)
Definition at line 402 of file dlLibraryTable.C.
References PtrList< T >::clear(), UPtrList< T >::empty(), and forAll.
Referenced by dlLibraryTable::dlLibraryTable(), dlLibraryTable::dlLibraryTable(), dlLibraryTable::dlLibraryTable(), functionObject::New(), dlLibraryTable::open(), dlLibraryTable::open(), dlLibraryTable::open(), dlLibraryTable::open(), dlLibraryTable::open(), Time::Time(), Time::Time(), Time::Time(), and Time::Time().
open() [2/7]
void * open (const fileName & libName, bool verbose = true)
Definition at line 434 of file dlLibraryTable.C.
open() [3/7]
bool open (const UList< fileName > & libNames, bool verbose = true)
Definition at line 453 of file dlLibraryTable.C.
References dlLibraryTable::open(), and UPtrList< T >::size().
open() [4/7]
bool open (std::initializer_list< fileName > libNames, bool verbose = true)
Definition at line 480 of file dlLibraryTable.C.
References dlLibraryTable::open(), and UPtrList< T >::size().
close() [1/2]
void close (bool verbose = true)
Definition at line 310 of file dlLibraryTable.C.
References PtrList< T >::clear(), DebugInFunction, Foam::dlClose(), Foam::endl(), forAll, forAllReverse, Foam::name(), Foam::nl, PtrList< T >::resize(), UPtrList< T >::size(), and WarningInFunction.
close() [2/2]
bool close (const fileName & libName, bool verbose = true)
Definition at line 507 of file dlLibraryTable.C.
References PtrList< T >::clear(), DebugInFunction, Foam::dlClose(), UPtrList< T >::empty(), Foam::endl(), Foam::name(), Foam::nl, and WarningInFunction.
findLibrary()
void * findLibrary (const fileName & libName)
Definition at line 563 of file dlLibraryTable.C.
References UPtrList< T >::empty().
open() [5/7]
bool open (const word & libsEntry, const dictionary & dict, bool verbose = true)
Definition at line 576 of file dlLibraryTable.C.
References dict, keyType::LITERAL, dlLibraryTable::open(), and dictionary::readIfPresent().
open() [6/7]
bool open (const dictionary & dict, const word & libsEntry)
Definition at line 592 of file dlLibraryTable.C.
References dict, and dlLibraryTable::open().
open() [7/7]
template<class TablePtr > bool open (const dictionary & dict, const word & libsEntry, const TablePtr & tablePtr, bool verbose = true)
Definition at line 28 of file dlLibraryTableTemplates.C.
References dict, Foam::endl(), keyType::LITERAL, Foam::nl, dlLibraryTable::open(), UPtrList< T >::size(), and WarningInFunction.
info()
InfoProxy< dlLibraryTable > info () const inline noexcept
Definition at line 309 of file dlLibraryTable.H.
Member Data Documentation
dlcloseOnTerminate
int dlcloseOnTerminate static
Definition at line 103 of file dlLibraryTable.H.
Referenced by dlLibraryTable::~dlLibraryTable().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/dynamicLibrary/dlLibraryTable/dlLibraryTable.H
src/OpenFOAM/db/dynamicLibrary/dlLibraryTable/dlLibraryTable.C
src/OpenFOAM/db/dynamicLibrary/dlLibraryTable/dlLibraryTableTemplates.C