OpenFOAM: PatchTools Class Reference
PatchTools Class Reference
A collection of tools for searching, sorting PrimitivePatch information.
#include <PatchTools.H>
Public Member Functions
template<class FaceList , class PointField >
Foam::labelList edgeOwner (const PrimitivePatch< FaceList, PointField > &p)
template<class FaceList , class PointField >
Foam::tmp< Foam::pointField > pointNormals (const polyMesh &mesh, const PrimitivePatch< FaceList, PointField > &p, const bitSet &pFlip)
template<class FaceList , class PointField >
Foam::tmp< Foam::pointField > edgeNormals (const polyMesh &mesh, const PrimitivePatch< FaceList, PointField > &p, const labelList &patchEdges, const labelList &coupledEdges, const bitSet &pFlip)
template<class BoolListType , class FaceList , class PointField >
Foam::label markZones (const PrimitivePatch< FaceList, PointField > &p, const BoolListType &borderEdge, labelList &faceZone)
template<class FaceList , class PointField >
Foam::labelListList sortedEdgeFaces (const PrimitivePatch< FaceList, PointField > &p)
template<class FaceList , class PointField >
Foam::labelListList sortedPointEdges (const PrimitivePatch< FaceList, PointField > &p)
Static Public Member Functions
template<class FaceList , class PointField >
static bool checkOrientation (const PrimitivePatch< FaceList, PointField > &, const bool report=false, labelHashSet *marked=0)
template<class BoolListType , class FaceList , class PointField >
static void markZone (const PrimitivePatch< FaceList, PointField > &, const BoolListType &borderEdge, const label facei, const label currentZone, labelList &faceZone)
template<class BoolListType , class FaceList , class PointField >
static label markZones (const PrimitivePatch< FaceList, PointField > &, const BoolListType &borderEdge, labelList &faceZone)
template<class BoolListType , class FaceList , class PointField >
static void subsetMap (const PrimitivePatch< FaceList, PointField > &p, const BoolListType &includeFaces, labelList &pointMap, labelList &faceMap)
template<class FaceList , class PointField >
static void calcBounds (const PrimitivePatch< FaceList, PointField > &p, boundBox &bb, label &nPoints)
template<class FaceList , class PointField >
static labelListList sortedEdgeFaces (const PrimitivePatch< FaceList, PointField > &)
template<class FaceList , class PointField >
static labelListList sortedPointEdges (const PrimitivePatch< FaceList, PointField > &)
template<class FaceList , class PointField >
static labelList edgeOwner (const PrimitivePatch< FaceList, PointField > &)
template<class FaceList1 , class PointField1 , class FaceList2 , class PointField2 >
static void matchPoints (const PrimitivePatch< FaceList1, PointField1 > &p1, const PrimitivePatch< FaceList2, PointField2 > &p2, labelList &p1PointLabels, labelList &p2PointLabels)
template<class FaceList1 , class PointField1 , class FaceList2 , class PointField2 >
static void matchEdges (const PrimitivePatch< FaceList1, PointField1 > &p1, const PrimitivePatch< FaceList2, PointField2 > &p2, labelList &p1EdgeLabels, labelList &p2EdgeLabels, bitSet &sameOrientation)
template<class FaceList , class PointField >
static tmp< pointField > pointNormals (const polyMesh &, const PrimitivePatch< FaceList, PointField > &, const bitSet &flipMap=bitSet::null())
template<class FaceList , class PointField >
static tmp< pointField > edgeNormals (const polyMesh &, const PrimitivePatch< FaceList, PointField > &, const labelList &patchEdges, const labelList &coupledEdges, const bitSet &flipMap=bitSet::null())
template<class FaceList , class PointField >
static void gatherAndMerge (const scalar mergeDist, const PrimitivePatch< FaceList, PointField > &pp, Field< typename PrimitivePatch< FaceList, PointField >::point_type > &mergedPoints, List< typename PrimitivePatch< FaceList, PointField >::face_type > &mergedFaces, globalIndex &pointAddr, globalIndex &faceAddr, labelList &pointMergeMap=const_cast< labelList & >(labelList::null()), const bool useLocal=false)
template<class FaceList , class PointField >
static void gatherAndMerge (const scalar mergeDist, const PrimitivePatch< FaceList, PointField > &pp, Field< typename PrimitivePatch< FaceList, PointField >::point_type > &mergedPoints, List< typename PrimitivePatch< FaceList, PointField >::face_type > &mergedFaces, labelList &pointMergeMap=const_cast< labelList & >(labelList::null()), const bool useLocal=false)
template<class FaceList >
static void gatherAndMerge (const polyMesh &mesh, const FaceList &faces, const labelList &meshPoints, const Map< label > &meshPointMap, labelList &pointToGlobal, labelList &uniqueMeshPointLabels, autoPtr< globalIndex > &globalPoints, autoPtr< globalIndex > &globalFaces, List< typename FaceList::value_type > &mergedFaces, pointField &mergedPoints)
Detailed Description
A collection of tools for searching, sorting PrimitivePatch information.
The class could also be extended to include more that just static methods.
Source files
PatchTools.H
PatchTools.C
PatchToolsCheck.C
PatchToolsEdgeOwner.C
PatchToolsGatherAndMerge.C
PatchToolsMatch.C
PatchToolsNormals.C
PatchToolsSearch.C
PatchToolsSortEdges.C
PatchToolsSortPoints.C
Definition at line 64 of file PatchTools.H.
Member Function Documentation
checkOrientation()
template<class FaceList , class PointField > bool checkOrientation (const PrimitivePatch< FaceList, PointField > & p, const bool report = false, labelHashSet * marked = 0) static
Definition at line 28 of file PatchToolsCheck.C.
References e, Foam::endl(), f(), forAll, foundError, Foam::Info, Foam::nl, p, p0, UPtrList< T >::size(), and UList< T >::size().
Referenced by searchableSurfaces::checkNormalOrientation().
markZone()
template<class BoolListType , class FaceList , class PointField > void markZone (const PrimitivePatch< FaceList, PointField > & p, const BoolListType & borderEdge, const label facei, const label currentZone, labelList & faceZone) static
Definition at line 33 of file PatchToolsSearch.C.
References Foam::abort(), PtrList< T >::append(), UPtrList< T >::empty(), Foam::FatalError, FatalErrorInFunction, forAll, p, UPtrList< T >::size(), and PtrList< T >::transfer().
markZones() [1/2]
template<class BoolListType , class FaceList , class PointField > static label markZones (const PrimitivePatch< FaceList, PointField > & , const BoolListType & borderEdge, labelList & faceZone) static
Referenced by searchableSurfaces::checkNormalOrientation().
subsetMap()
template<class BoolListType , class FaceList , class PointField > void subsetMap (const PrimitivePatch< FaceList, PointField > & p, const BoolListType & includeFaces, labelList & pointMap, labelList & faceMap) static
Definition at line 135 of file PatchToolsSearch.C.
References List< T >::clear(), Foam::faceMap(), forAll, p, PtrList< T >::resize(), and PtrList< T >::set().
Referenced by MeshedSurface< Face >::subsetMeshMap(), triSurface::subsetMeshMap(), and UnsortedMeshedSurface< Face >::subsetMeshMap().
calcBounds()
template<class FaceList , class PointField > void calcBounds (const PrimitivePatch< FaceList, PointField > & p, boundBox & bb, label & nPoints) static
Definition at line 171 of file PatchToolsSearch.C.
References boundBox::add(), f(), nPoints, p, points, boundBox::reset(), PtrList< T >::set(), and UPtrList< T >::size().
Referenced by triSurfaceMesh::edgeTree(), triSurfaceSearch::tree(), triSurfaceRegionSearch::treeByRegion(), and distributedTriSurfaceMesh::writeStats().
sortedEdgeFaces() [1/2]
template<class FaceList , class PointField > static labelListList sortedEdgeFaces (const PrimitivePatch< FaceList, PointField > &) static
Referenced by PatchTools::sortedEdgeFaces(), and extendedEdgeMesh::sortPointsAndEdges().
sortedPointEdges() [1/2]
template<class FaceList , class PointField > static labelListList sortedPointEdges (const PrimitivePatch< FaceList, PointField > &) static
Referenced by PatchTools::sortedPointEdges(), and extendedEdgeMesh::sortPointsAndEdges().
edgeOwner() [1/2]
template<class FaceList , class PointField > static labelList edgeOwner (const PrimitivePatch< FaceList, PointField > &) static
Referenced by PatchTools::edgeOwner().
matchPoints()
template<class FaceList1 , class PointField1 , class FaceList2 , class PointField2 > void matchPoints (const PrimitivePatch< FaceList1, PointField1 > & p1, const PrimitivePatch< FaceList2, PointField2 > & p2, labelList & p1PointLabels, labelList & p2PointLabels) static
Definition at line 31 of file PatchToolsMatch.C.
References forAll, and PtrList< T >::resize().
matchEdges()
template<class FaceList1 , class PointField1 , class FaceList2 , class PointField2 > void matchEdges (const PrimitivePatch< FaceList1, PointField1 > & p1, const PrimitivePatch< FaceList2, PointField2 > & p2, labelList & p1EdgeLabels, labelList & p2EdgeLabels, bitSet & sameOrientation) static
Definition at line 69 of file PatchToolsMatch.C.
References forAll, PtrList< T >::resize(), and PtrList< T >::set().
Referenced by addPatchCellLayer::calcExtrudeInfo(), createShellMesh::calcPointRegions(), meshRefinement::countEdgeFaces(), PatchEdgeFaceWave< PrimitivePatchType, Type, TrackingData >::PatchEdgeFaceWave(), and PatchEdgeFaceWave< PrimitivePatchType, Type, TrackingData >::PatchEdgeFaceWave().
pointNormals() [1/2]
template<class FaceList , class PointField > static tmp< pointField > pointNormals (const polyMesh & , const PrimitivePatch< FaceList, PointField > & , const bitSet & flipMap = bitSet::null()) static
edgeNormals() [1/2]
template<class FaceList , class PointField > static tmp< pointField > edgeNormals (const polyMesh & , const PrimitivePatch< FaceList, PointField > & , const labelList & patchEdges, const labelList & coupledEdges, const bitSet & flipMap = bitSet::null()) static
gatherAndMerge() [1/3]
template<class FaceList , class PointField > void gatherAndMerge (const scalar mergeDist, const PrimitivePatch< FaceList, PointField > & pp, Field< typename PrimitivePatch< FaceList, PointField >::point_type > & mergedPoints, List< typename PrimitivePatch< FaceList, PointField >::face_type > & mergedFaces, globalIndex & pointAddr, globalIndex & faceAddr, labelList & pointMergeMap = const_cast<labelList&>(labelList::null()), const bool useLocal = false) static
Definition at line 30 of file PatchToolsGatherAndMerge.C.
References f(), globalIndex::gather(), Foam::identity(), Foam::inplaceMergePoints(), Foam::inplaceRenumber(), globalIndex::inplaceToGlobal(), UPstream::master(), Foam::notNull(), UPstream::parRun(), pp(), globalIndex::range(), globalIndex::reset(), UPtrList< T >::size(), globalIndex::subProcs(), and List< T >::transfer().
Referenced by mergedSurf::merge(), shortestPathSet::shortestPathSet(), and AMIWeights::writeWeightField().
gatherAndMerge() [2/3]
template<class FaceList , class PointField > void gatherAndMerge (const scalar mergeDist, const PrimitivePatch< FaceList, PointField > & pp, Field< typename PrimitivePatch< FaceList, PointField >::point_type > & mergedPoints, List< typename PrimitivePatch< FaceList, PointField >::face_type > & mergedFaces, labelList & pointMergeMap = const_cast<labelList&>(labelList::null()), const bool useLocal = false) static
Definition at line 151 of file PatchToolsGatherAndMerge.C.
References pp().
gatherAndMerge() [3/3]
template<class FaceList > void gatherAndMerge (const polyMesh & mesh, const FaceList & faces, const labelList & meshPoints, const Map< label > & meshPointMap, labelList & pointToGlobal, labelList & uniqueMeshPointLabels, autoPtr< globalIndex > & globalPoints, autoPtr< globalIndex > & globalFaces, List< typename FaceList::value_type > & mergedFaces, pointField & mergedPoints) static
Definition at line 185 of file PatchToolsGatherAndMerge.C.
References f(), polyMesh::globalData(), Foam::identity(), Foam::inplaceRenumber(), mesh, UPstream::parRun(), polyMesh::points(), and UList< T >::size().
edgeOwner() [2/2]
template<class FaceList , class PointField > Foam::labelList edgeOwner (const PrimitivePatch< FaceList, PointField > & p)
Definition at line 28 of file PatchToolsEdgeOwner.C.
References Foam::abort(), PatchTools::edgeOwner(), f(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::nl, p, UPtrList< T >::size(), and UList< T >::size().
pointNormals() [2/2]
template<class FaceList , class PointField > Foam::tmp< Foam::pointField > pointNormals (const polyMesh & mesh, const PrimitivePatch< FaceList, PointField > & p, const bitSet & pFlip)
Definition at line 31 of file PatchToolsNormals.C.
References mapDistributeBase::constructSize(), globalMeshData::coupledPatch(), mapDistribute::distribute(), UPtrList< T >::empty(), f(), forAll, globalMeshData::globalPointSlaves(), globalMeshData::globalPointSlavesMap(), globalMeshData::globalPointTransformedSlaves(), globalMeshData::globalTransforms(), local, Foam::mag(), mesh, PrimitivePatch< FaceList, PointField >::meshPointMap(), n, tmp< T >::New(), p, pFaces, mapDistribute::reverseDistribute(), PtrList< T >::setSize(), UPtrList< T >::size(), Foam::sum(), and Foam::Zero.
edgeNormals() [2/2]
template<class FaceList , class PointField > Foam::tmp< Foam::pointField > edgeNormals (const polyMesh & mesh, const PrimitivePatch< FaceList, PointField > & p, const labelList & patchEdges, const labelList & coupledEdges, const bitSet & pFlip)
Definition at line 190 of file PatchToolsNormals.C.
References mapDistributeBase::constructSize(), UPtrList< T >::empty(), forAll, polyMesh::globalData(), globalMeshData::globalEdgeSlaves(), globalMeshData::globalEdgeSlavesMap(), globalMeshData::globalEdgeTransformedSlaves(), globalMeshData::globalTransforms(), Foam::mag(), mesh, n, tmp< T >::New(), p, globalMeshData::syncData(), and Foam::Zero.
markZones() [2/2]
template<class BoolListType , class FaceList , class PointField > Foam::label markZones (const PrimitivePatch< FaceList, PointField > & p, const BoolListType & borderEdge, labelList & faceZone)
Definition at line 103 of file PatchToolsSearch.C.
References p, List< T >::setSize(), and UList< T >::size().
sortedEdgeFaces() [2/2]
template<class FaceList , class PointField > Foam::labelListList sortedEdgeFaces (const PrimitivePatch< FaceList, PointField > & p)
Definition at line 30 of file PatchToolsSortEdges.C.
References e, f(), forAll, Foam::mag(), VectorSpace< Form, Cmpt, Ncmpts >::max, Foam::normalised(), p, Foam::pseudoAngle(), UPtrList< T >::size(), UList< T >::size(), and PatchTools::sortedEdgeFaces().
sortedPointEdges() [2/2]
template<class FaceList , class PointField > Foam::labelListList sortedPointEdges (const PrimitivePatch< FaceList, PointField > & p)
Definition at line 28 of file PatchToolsSortPoints.C.
References PtrList< T >::append(), PtrList< T >::clear(), edge::end(), Foam::endl(), forAll, Foam::nl, p, UPtrList< T >::size(), PatchTools::sortedPointEdges(), edge::start(), and WarningInFunction.
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/primitiveMesh/PatchTools/PatchTools.H
src/OpenFOAM/meshes/primitiveMesh/PatchTools/PatchToolsCheck.C
src/OpenFOAM/meshes/primitiveMesh/PatchTools/PatchToolsEdgeOwner.C
src/OpenFOAM/meshes/primitiveMesh/PatchTools/PatchToolsGatherAndMerge.C
src/OpenFOAM/meshes/primitiveMesh/PatchTools/PatchToolsMatch.C
src/OpenFOAM/meshes/primitiveMesh/PatchTools/PatchToolsNormals.C
src/OpenFOAM/meshes/primitiveMesh/PatchTools/PatchToolsSearch.C
src/OpenFOAM/meshes/primitiveMesh/PatchTools/PatchToolsSortEdges.C
src/OpenFOAM/meshes/primitiveMesh/PatchTools/PatchToolsSortPoints.C