OpenFOAM: solidification Class Reference
solidification Class Reference
Solidification phase change model where all film mass is converted when the local temperature > activation temperature. The latent heat is assumed to be removed by heat-transfer to the wall.
#include <solidification.H>
Public Member Functions
TypeName ("solidification")
solidification (surfaceFilmRegionModel &film, const dictionary &dict)
virtual ~solidification ()
virtual void correctModel (const scalar dt, scalarField &availableMass, scalarField &dMass, scalarField &dEnergy)
Public Member Functions inherited from phaseChangeModel
TypeName ("phaseChangeModel")
declareRunTimeSelectionTable (autoPtr, phaseChangeModel, dictionary,(surfaceFilmRegionModel &film, const dictionary &dict),(film, dict))
phaseChangeModel (surfaceFilmRegionModel &film)
phaseChangeModel (const word &modelType, surfaceFilmRegionModel &film, const dictionary &dict)
virtual ~phaseChangeModel ()
virtual void correct (const scalar dt, scalarField &availableMass, volScalarField &dMass, volScalarField &dEnergy)
virtual void info (Ostream &os) const
Public Member Functions inherited from filmSubModelBase
filmSubModelBase (surfaceFilmRegionModel &film)
filmSubModelBase (surfaceFilmRegionModel &film, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
filmSubModelBase (const word &modelName, surfaceFilmRegionModel &film, const dictionary &dict, const word &baseName, const word &modelType)
virtual ~filmSubModelBase ()
virtual bool writeTime () const
const surfaceFilmRegionModel & film () const
surfaceFilmRegionModel & film ()
template<class FilmType >
const FilmType & filmType () const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
subModelBase (const subModelBase &smb)
virtual ~subModelBase ()=default
const word & modelName () const
const dictionary & dict () const
const word & baseName () const
const word & modelType () const
const dictionary & coeffDict () const
const dictionary & properties () const
virtual bool defaultCoeffs (const bool printMsg) const
virtual bool active () const
virtual void cacheFields (const bool store)
virtual fileName localPath () const
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
bool getModelDict (const word &entryName, dictionary &dict) const
template<class Type >
bool getModelProperty (const word &entryName, Type &value) const
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
virtual void write (Ostream &os) const
Protected Attributes
scalar T0_
scalar maxSolidificationFrac_
dimensionedScalar maxSolidificationRate_
volScalarField mass_
volScalarField thickness_
Protected Attributes inherited from phaseChangeModel
scalar latestMassPC_
scalar totalMassPC_
Protected Attributes inherited from filmSubModelBase
surfaceFilmRegionModel & filmModel_
Protected Attributes inherited from subModelBase
const word modelName_
dictionary & properties_
const dictionary dict_
const word baseName_
const word modelType_
const dictionary coeffDict_
Additional Inherited Members
Static Public Member Functions inherited from phaseChangeModel
static autoPtr< phaseChangeModel > New (surfaceFilmRegionModel &film, const dictionary &dict)
Public Attributes inherited from subModelBase
bool log
Protected Member Functions inherited from subModelBase
bool inLine () const
Detailed Description
Solidification phase change model where all film mass is converted when the local temperature > activation temperature. The latent heat is assumed to be removed by heat-transfer to the wall.
Source files
solidification.H
solidification.C
Definition at line 52 of file solidification.H.
Constructor & Destructor Documentation
solidification()
solidification (surfaceFilmRegionModel & film, const dictionary & dict)
Definition at line 48 of file solidification.C.
~solidification()
~solidification () virtual
Definition at line 100 of file solidification.C.
Member Function Documentation
TypeName()
TypeName ("solidification")
correctModel()
void correctModel (const scalar dt, scalarField & availableMass, scalarField & dMass, scalarField & dEnergy) virtual
Implements phaseChangeModel.
Definition at line 106 of file solidification.C.
References alpha, filmSubModelBase::film(), filmSubModelBase::filmModel_, forAll, solidification::mass_, solidification::maxSolidificationFrac_, solidification::maxSolidificationRate_, Foam::min(), regionModel::regionMesh(), T, solidification::T0_, and solidification::thickness_.
Member Data Documentation
T0_
scalar T0_ protected
Definition at line 70 of file solidification.H.
Referenced by solidification::correctModel().
maxSolidificationFrac_
scalar maxSolidificationFrac_ protected
Definition at line 74 of file solidification.H.
Referenced by solidification::correctModel().
maxSolidificationRate_
dimensionedScalar maxSolidificationRate_ protected
Definition at line 78 of file solidification.H.
Referenced by solidification::correctModel().
mass_
volScalarField mass_ protected
Definition at line 81 of file solidification.H.
Referenced by solidification::correctModel().
thickness_
volScalarField thickness_ protected
Definition at line 84 of file solidification.H.
Referenced by solidification::correctModel().
The documentation for this class was generated from the following files:
src/regionModels/surfaceFilmModels/submodels/thermo/phaseChangeModel/solidification/solidification.H
src/regionModels/surfaceFilmModels/submodels/thermo/phaseChangeModel/solidification/solidification.C