OpenFOAM: rotatingPressureInletOutletVelocityFvPatchVectorField Class Reference
rotatingPressureInletOutletVelocityFvPatchVectorField Class Reference
Boundary conditions » Inlet | Boundary conditions » Outlet
This velocity inlet/outlet boundary condition is applied to patches in a rotating frame where the pressure is specified. A zero-gradient is applied for outflow (as defined by the flux); for inflow, the velocity is obtained from the flux with a direction normal to the patch faces.
#include <rotatingPressureInletOutletVelocityFvPatchVectorField.H>
Public Member Functions
TypeName ("rotatingPressureInletOutletVelocity")
rotatingPressureInletOutletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
rotatingPressureInletOutletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
rotatingPressureInletOutletVelocityFvPatchVectorField (const rotatingPressureInletOutletVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
rotatingPressureInletOutletVelocityFvPatchVectorField (const rotatingPressureInletOutletVelocityFvPatchVectorField &)
virtual tmp< fvPatchVectorField > clone () const
rotatingPressureInletOutletVelocityFvPatchVectorField (const rotatingPressureInletOutletVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
virtual void write (Ostream &) const
Public Member Functions inherited from pressureInletOutletVelocityFvPatchVectorField
TypeName ("pressureInletOutletVelocity")
pressureInletOutletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
pressureInletOutletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
pressureInletOutletVelocityFvPatchVectorField (const pressureInletOutletVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
pressureInletOutletVelocityFvPatchVectorField (const pressureInletOutletVelocityFvPatchVectorField &)
pressureInletOutletVelocityFvPatchVectorField (const pressureInletOutletVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
virtual bool assignable () const
const word & phiName () const
word & phiName ()
const vectorField & tangentialVelocity () const
void setTangentialVelocity (const vectorField &tangentialVelocity)
virtual void autoMap (const fvPatchFieldMapper &)
virtual void rmap (const fvPatchVectorField &, const labelList &)
virtual void updateCoeffs ()
virtual void operator= (const fvPatchField< vector > &pvf)
Detailed Description
This velocity inlet/outlet boundary condition is applied to patches in a rotating frame where the pressure is specified. A zero-gradient is applied for outflow (as defined by the flux); for inflow, the velocity is obtained from the flux with a direction normal to the patch faces.
Usage
Property Description Required Default value
phi flux field name no phi
tangentialVelocity tangential velocity field no
omega angular velocity of the frame [rad/s] yes
Example of the boundary condition specification:
    <patchName>
    {
        type            rotatingPressureInletOutletVelocity;
        phi             phi;
        tangentialVelocity uniform (0 0 0);
        omega           100;
    }
The omega entry is a Function1 type, able to describe time varying functions.
Note
Sign conventions:
positive flux (out of domain): apply zero-gradient condition
negative flux (into of domain): derive from the flux in the patch-normal direction
See also
Foam::pressureInletOutletVelocityFvPatchVectorField Foam::Function1Types
Source files
rotatingPressureInletOutletVelocityFvPatchVectorField.H
rotatingPressureInletOutletVelocityFvPatchVectorField.C
Definition at line 106 of file rotatingPressureInletOutletVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
rotatingPressureInletOutletVelocityFvPatchVectorField() [1/5]
rotatingPressureInletOutletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Definition at line 48 of file rotatingPressureInletOutletVelocityFvPatchVectorField.C.
rotatingPressureInletOutletVelocityFvPatchVectorField() [2/5]
rotatingPressureInletOutletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Definition at line 76 of file rotatingPressureInletOutletVelocityFvPatchVectorField.C.
rotatingPressureInletOutletVelocityFvPatchVectorField() [3/5]
rotatingPressureInletOutletVelocityFvPatchVectorField (const rotatingPressureInletOutletVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 60 of file rotatingPressureInletOutletVelocityFvPatchVectorField.C.
rotatingPressureInletOutletVelocityFvPatchVectorField() [4/5]
rotatingPressureInletOutletVelocityFvPatchVectorField (const rotatingPressureInletOutletVelocityFvPatchVectorField & rppvf)
Definition at line 91 of file rotatingPressureInletOutletVelocityFvPatchVectorField.C.
rotatingPressureInletOutletVelocityFvPatchVectorField() [5/5]
rotatingPressureInletOutletVelocityFvPatchVectorField (const rotatingPressureInletOutletVelocityFvPatchVectorField & rppvf, const DimensionedField< vector, volMesh > & iF)
Definition at line 104 of file rotatingPressureInletOutletVelocityFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("rotatingPressureInletOutletVelocity")
clone() [1/2]
virtual tmp< fvPatchVectorField > clone () const inline virtual
Reimplemented from pressureInletOutletVelocityFvPatchVectorField.
Definition at line 163 of file rotatingPressureInletOutletVelocityFvPatchVectorField.H.
clone() [2/2]
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Reimplemented from pressureInletOutletVelocityFvPatchVectorField.
Definition at line 179 of file rotatingPressureInletOutletVelocityFvPatchVectorField.H.
write()
void write (Ostream & os) const virtual
Reimplemented from pressureInletOutletVelocityFvPatchVectorField.
Definition at line 120 of file rotatingPressureInletOutletVelocityFvPatchVectorField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntry(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/rotatingPressureInletOutletVelocity/rotatingPressureInletOutletVelocityFvPatchVectorField.H
src/finiteVolume/fields/fvPatchFields/derived/rotatingPressureInletOutletVelocity/rotatingPressureInletOutletVelocityFvPatchVectorField.C