OpenFOAM: searchableSurfacesQueries Class Reference
searchableSurfacesQueries Class Reference
A collection of tools for searchableSurfaces.
#include <searchableSurfacesQueries.H>
Public Member Functions
ClassName ("searchableSurfacesQueries")
Static Public Member Functions
static void findAnyIntersection (const PtrList< searchableSurface > &, const labelList &surfacesToTest, const pointField &start, const pointField &end, labelList &surfaces, List< pointIndexHit > &)
static void findAllIntersections (const PtrList< searchableSurface > &, const labelList &surfacesToTest, const pointField &start, const pointField &end, labelListList &surfaces, List< List< pointIndexHit > > &surfaceHits)
static void findNearestIntersection (const PtrList< searchableSurface > &allSurfaces, const labelList &surfacesToTest, const pointField &start, const pointField &end, labelList &surface1, List< pointIndexHit > &hit1, labelList &surface2, List< pointIndexHit > &hit2)
static void findNearest (const PtrList< searchableSurface > &, const labelList &surfacesToTest, const pointField &, const scalarField &nearestDistSqr, labelList &surfaces, List< pointIndexHit > &)
static void findNearest (const PtrList< searchableSurface > &allSurfaces, const labelList &surfacesToTest, const labelListList &regionIndices, const pointField &samples, const scalarField &nearestDistSqr, labelList &nearestSurfaces, List< pointIndexHit > &nearestInfo)
static void findNearest (const PtrList< searchableSurface > &allSurfaces, const labelList &surfacesToTest, const pointField &start, const scalarField &distSqr, pointField &near, List< pointConstraint > &constraint, const label nIter=20)
static void signedDistance (const PtrList< searchableSurface > &allSurfaces, const labelList &surfacesToTest, const pointField &samples, const scalarField &nearestDistSqr, const volumeType illegalHandling, labelList &nearestSurfaces, scalarField &distance)
static boundBox bounds (const PtrList< searchableSurface > &allSurfaces, const labelUList &surfacesToTest)
Detailed Description
A collection of tools for searchableSurfaces.
Source files
searchableSurfacesQueries.H
searchableSurfacesQueries.C
Definition at line 50 of file searchableSurfacesQueries.H.
Member Function Documentation
ClassName()
ClassName ("searchableSurfacesQueries")
References searchableSurfacesQueries::bounds().
findAnyIntersection()
void findAnyIntersection (const PtrList< searchableSurface > & allSurfaces, const labelList & surfacesToTest, const pointField & start, const pointField & end, labelList & surfaces, List< pointIndexHit > & hitInfo) static
Definition at line 114 of file searchableSurfacesQueries.C.
References forAll, Foam::identity(), p0, List< T >::setSize(), PtrList< T >::setSize(), and UList< T >::size().
Referenced by refinementSurfaces::findAnyIntersection(), and searchableSurfaces::findAnyIntersection().
findAllIntersections()
void findAllIntersections (const PtrList< searchableSurface > & allSurfaces, const labelList & surfacesToTest, const pointField & start, const pointField & end, labelListList & surfaces, List< List< pointIndexHit > > & surfaceHits) static
Definition at line 175 of file searchableSurfacesQueries.C.
References UPtrList< T >::empty(), forAll, PtrList< T >::setSize(), UPtrList< T >::size(), and UList< T >::size().
Referenced by searchableSurfaces::findAllIntersections().
findNearestIntersection()
void findNearestIntersection (const PtrList< searchableSurface > & allSurfaces, const labelList & surfacesToTest, const pointField & start, const pointField & end, labelList & surface1, List< pointIndexHit > & hit1, labelList & surface2, List< pointIndexHit > & hit2) static
Definition at line 254 of file searchableSurfacesQueries.C.
References forAll, PtrList< T >::setSize(), and UList< T >::size().
Referenced by searchableSurfaces::findNearestIntersection().
findNearest() [1/3]
void findNearest (const PtrList< searchableSurface > & allSurfaces, const labelList & surfacesToTest, const pointField & samples, const scalarField & nearestDistSqr, labelList & surfaces, List< pointIndexHit > & nearestInfo) static
Definition at line 341 of file searchableSurfacesQueries.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, samples(), PtrList< T >::setSize(), UPtrList< T >::size(), and UList< T >::size().
Referenced by refinementSurfaces::findNearest(), refinementSurfaces::findNearest(), searchableSurfaces::findNearest(), searchableSurfaces::findNearest(), refinementSurfaces::findNearestRegion(), refinementSurfaces::findNearestRegion(), refinementSurfaces::findNearestRegion(), projectVertex::operator point(), projectCurveEdge::position(), and projectEdge::position().
findNearest() [2/3]
void findNearest (const PtrList< searchableSurface > & allSurfaces, const labelList & surfacesToTest, const labelListList & regionIndices, const pointField & samples, const scalarField & nearestDistSqr, labelList & nearestSurfaces, List< pointIndexHit > & nearestInfo) static
Definition at line 394 of file searchableSurfacesQueries.C.
References UPtrList< T >::empty(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, samples(), PtrList< T >::setSize(), UPtrList< T >::size(), and UList< T >::size().
findNearest() [3/3]
void findNearest (const PtrList< searchableSurface > & allSurfaces, const labelList & surfacesToTest, const pointField & start, const scalarField & distSqr, pointField & near, List< pointConstraint > & constraint, const label nIter = 20) static
Definition at line 465 of file searchableSurfacesQueries.C.
References plane::ray::dir(), e, Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::mag(), n, plane::ray::refPoint(), Vector< Cmpt >::removeCollinear(), s(), PtrList< T >::setSize(), UPtrList< T >::size(), UList< T >::size(), Foam::sqrt(), and VectorSpace< Form, Cmpt, Ncmpts >::zero.
signedDistance()
void signedDistance (const PtrList< searchableSurface > & allSurfaces, const labelList & surfacesToTest, const pointField & samples, const scalarField & nearestDistSqr, const volumeType illegalHandling, labelList & nearestSurfaces, scalarField & distance) static
Definition at line 587 of file searchableSurfacesQueries.C.
References PtrList< T >::append(), PtrList< T >::clear(), Foam::distance(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, volumeType::INSIDE, volumeType::OUTSIDE, samples(), PtrList< T >::setSize(), and UList< T >::size().
bounds()
Foam::boundBox bounds (const PtrList< searchableSurface > & allSurfaces, const labelUList & surfacesToTest) static
Definition at line 685 of file searchableSurfacesQueries.C.
References boundBox::add().
Referenced by searchableSurfaces::bounds(), searchableSurfacesQueries::ClassName(), and projectVertex::operator point().
The documentation for this class was generated from the following files:
src/meshTools/searchableSurfaces/searchableSurfacesQueries/searchableSurfacesQueries.H
src/meshTools/searchableSurfaces/searchableSurfacesQueries/searchableSurfacesQueries.C