OpenFOAM: threePhaseInterfaceProperties Class Reference
threePhaseInterfaceProperties Class Reference
Properties to aid interFoam : 1. Correct the alpha boundary condition for dynamic contact angle. 2. Calculate interface curvature.
#include <threePhaseInterfaceProperties.H>
Public Member Functions
threePhaseInterfaceProperties (const incompressibleThreePhaseMixture &mixture)
scalar cAlpha () const
const dimensionedScalar & deltaN () const
const surfaceScalarField & nHatf () const
const volScalarField & K () const
tmp< volScalarField > sigma () const
tmp< volScalarField > sigmaK () const
tmp< surfaceScalarField > surfaceTensionForce () const
tmp< volScalarField > nearInterface () const
void correct ()
Detailed Description
Properties to aid interFoam : 1. Correct the alpha boundary condition for dynamic contact angle. 2. Calculate interface curvature.
Source files
threePhaseInterfaceProperties.H
threePhaseInterfaceProperties.C
Definition at line 49 of file threePhaseInterfaceProperties.H.
Constructor & Destructor Documentation
threePhaseInterfaceProperties()
threePhaseInterfaceProperties (const incompressibleThreePhaseMixture & mixture)
Member Function Documentation
cAlpha()
scalar cAlpha () const inline
Definition at line 108 of file threePhaseInterfaceProperties.H.
deltaN()
const dimensionedScalar & deltaN () const inline
Definition at line 113 of file threePhaseInterfaceProperties.H.
nHatf()
const surfaceScalarField & nHatf () const inline
Definition at line 118 of file threePhaseInterfaceProperties.H.
K()
const volScalarField & K () const inline
Definition at line 123 of file threePhaseInterfaceProperties.H.
sigma()
tmp< volScalarField > sigma () const inline
Definition at line 128 of file threePhaseInterfaceProperties.H.
References incompressibleThreePhaseMixture::alpha2(), incompressibleThreePhaseMixture::alpha3(), and Foam::max().
Referenced by threePhaseInterfaceProperties::sigmaK().
sigmaK()
tmp< volScalarField > sigmaK () const inline
Definition at line 138 of file threePhaseInterfaceProperties.H.
References threePhaseInterfaceProperties::sigma().
surfaceTensionForce()
tmp< surfaceScalarField > surfaceTensionForce () const
nearInterface()
tmp< volScalarField > nearInterface () const
correct()
void correct () inline
Definition at line 149 of file threePhaseInterfaceProperties.H.
Referenced by immiscibleIncompressibleThreePhaseMixture::correct().
The documentation for this class was generated from the following file:
applications/solvers/multiphase/interFoam/interMixingFoam/threePhaseInterfaceProperties/threePhaseInterfaceProperties.H