OpenFOAM: lagrangianReconstructor Class Reference
lagrangianReconstructor Class Reference
Reconstructor for lagrangian positions and fields.
#include <lagrangianReconstructor.H>
Public Member Functions
lagrangianReconstructor (const fvMesh &mesh, const PtrList< fvMesh > &procMeshes, const PtrList< labelIOList > &faceProcAddressing, const PtrList< labelIOList > &cellProcAddressing)
label reconstructPositions (const word &cloudName) const
template<class Type >
tmp< IOField< Type > > reconstructField (const word &cloudName, const word &fieldName)
template<class Type >
tmp< CompactIOField< Field< Type >, Type > > reconstructFieldField (const word &cloudName, const word &fieldName)
template<class Type >
label reconstructFields (const word &cloudName, const UPtrList< const IOobject > &fieldObjects)
template<class Type >
label reconstructFields (const word &cloudName, const IOobjectList &objects, const wordRes &selectedFields=wordRes())
template<class Type >
label reconstructFieldFields (const word &cloudName, const IOobjectList &objects, const wordRes &selectedFields=wordRes())
void reconstructAllFields (const word &cloudName, const IOobjectList &cloudObjs, const wordRes &selectedFields=wordRes())
template<class Type >
Foam::tmp< Foam::IOField< Type > > reconstructField (const word &cloudName, const word &fieldName)
template<class Type >
Foam::tmp< Foam::CompactIOField< Foam::Field< Type >, Type > > reconstructFieldField (const word &cloudName, const word &fieldName)
template<class Type >
Foam::label reconstructFields (const word &cloudName, const UPtrList< const IOobject > &fieldObjects)
template<class Type >
Foam::label reconstructFields (const word &cloudName, const IOobjectList &objects, const wordRes &selectedFields)
template<class Type >
Foam::label reconstructFieldFields (const word &cloudName, const IOobjectList &objects, const wordRes &selectedFields)
Static Public Attributes
static int verbose_ = 1
Detailed Description
Reconstructor for lagrangian positions and fields.
Source files
lagrangianReconstructor.H
lagrangianReconstructor.C
lagrangianReconstructorTemplates.C
Definition at line 52 of file lagrangianReconstructor.H.
Constructor & Destructor Documentation
lagrangianReconstructor()
lagrangianReconstructor (const fvMesh & mesh, const PtrList< fvMesh > & procMeshes, const PtrList< labelIOList > & faceProcAddressing, const PtrList< labelIOList > & cellProcAddressing)
Definition at line 32 of file lagrangianReconstructor.C.
Member Function Documentation
reconstructPositions()
Foam::label reconstructPositions (const word & cloudName) const
Definition at line 49 of file lagrangianReconstructor.C.
References PtrList< T >::append(), particle< Type >::cell(), cloudName(), particle< Type >::coordinates(), Foam::faceMap(), forAll, forAllConstIters, passivePositionParticle::location(), Foam::mag(), cloud::POSITIONS, particle< Type >::procTetPt(), UPtrList< T >::size(), particle< Type >::tetFace(), particle< Type >::writeLagrangianPositions, and Foam::Zero.
reconstructField() [1/2]
template<class Type > tmp< IOField< Type > > reconstructField (const word & cloudName, const word & fieldName)
reconstructFieldField() [1/2]
template<class Type > tmp< CompactIOField< Field< Type >, Type > > reconstructFieldField (const word & cloudName, const word & fieldName)
reconstructFields() [1/4]
template<class Type > label reconstructFields (const word & cloudName, const UPtrList< const IOobject > & fieldObjects)
reconstructFields() [2/4]
template<class Type > label reconstructFields (const word & cloudName, const IOobjectList & objects, const wordRes & selectedFields = wordRes())
reconstructFieldFields() [1/2]
template<class Type > label reconstructFieldFields (const word & cloudName, const IOobjectList & objects, const wordRes & selectedFields = wordRes())
reconstructAllFields()
void reconstructAllFields (const word & cloudName, const IOobjectList & cloudObjs, const wordRes & selectedFields = wordRes())
Definition at line 159 of file lagrangianReconstructor.C.
References doLocalCode.
reconstructField() [2/2]
template<class Type > Foam::tmp< Foam::IOField< Type > > reconstructField (const word & cloudName, const word & fieldName)
Definition at line 30 of file lagrangianReconstructorTemplates.C.
References cloudName(), field(), forAll, IOobjectOption::MUST_READ, Foam::New(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, cloud::prefix, PtrList< T >::setSize(), and UPtrList< T >::size().
reconstructFieldField() [2/2]
template<class Type > Foam::tmp< Foam::CompactIOField< Foam::Field< Type >, Type > > reconstructFieldField (const word & cloudName, const word & fieldName)
Definition at line 85 of file lagrangianReconstructorTemplates.C.
References cloudName(), field(), forAll, IOobjectOption::MUST_READ, Foam::New(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, cloud::prefix, PtrList< T >::setSize(), and UPtrList< T >::size().
reconstructFields() [3/4]
template<class Type > Foam::label reconstructFields (const word & cloudName, const UPtrList< const IOobject > & fieldObjects)
Definition at line 146 of file lagrangianReconstructorTemplates.C.
References cloudName(), Foam::endl(), Foam::Info, io(), IOobject::isHeaderClass(), IOobject::name(), Foam::nl, and write().
reconstructFields() [4/4]
template<class Type > Foam::label reconstructFields (const word & cloudName, const IOobjectList & objects, const wordRes & selectedFields)
Definition at line 181 of file lagrangianReconstructorTemplates.C.
References cloudName(), and UPtrList< T >::empty().
reconstructFieldFields() [2/2]
template<class Type > Foam::label reconstructFieldFields (const word & cloudName, const IOobjectList & objects, const wordRes & selectedFields)
Definition at line 203 of file lagrangianReconstructorTemplates.C.
References PtrList< T >::append(), cloudName(), UPtrList< T >::empty(), Foam::endl(), Foam::Info, io(), IOobject::name(), Foam::nl, Foam::sort(), and write().
Member Data Documentation
verbose_
int verbose_ = 1 static
Definition at line 83 of file lagrangianReconstructor.H.
The documentation for this class was generated from the following files:
src/parallel/reconstruct/reconstruct/lagrangianReconstructor.H
src/parallel/reconstruct/reconstruct/lagrangianReconstructor.C
src/parallel/reconstruct/reconstruct/lagrangianReconstructorTemplates.C