OpenFOAM: inverseVolumeDiffusivity Class Reference
inverseVolumeDiffusivity Class Reference
Inverse cell-volume motion diffusivity.
#include <inverseVolumeDiffusivity.H>
Public Member Functions
TypeName ("inverseVolume")
inverseVolumeDiffusivity (const fvMesh &mesh, Istream &mdData)
virtual ~inverseVolumeDiffusivity ()
virtual void correct ()
Public Member Functions inherited from uniformDiffusivity
TypeName ("uniform")
uniformDiffusivity (const fvMesh &mesh, Istream &mdData)
virtual ~uniformDiffusivity ()
virtual tmp< surfaceScalarField > operator() () const
Public Member Functions inherited from motionDiffusivity
TypeName ("motionDiffusivity")
declareRunTimeSelectionTable (autoPtr, motionDiffusivity, Istream,(const fvMesh &mesh, Istream &mdData),(mesh, mdData))
motionDiffusivity (const fvMesh &mesh)
virtual ~motionDiffusivity ()
const fvMesh & mesh () const
Additional Inherited Members
Static Public Member Functions inherited from motionDiffusivity
static autoPtr< motionDiffusivity > New (const fvMesh &mesh, Istream &mdData)
Protected Attributes inherited from uniformDiffusivity
surfaceScalarField faceDiffusivity_
Detailed Description
Inverse cell-volume motion diffusivity.
Source files
inverseVolumeDiffusivity.H
inverseVolumeDiffusivity.C
Definition at line 46 of file inverseVolumeDiffusivity.H.
Constructor & Destructor Documentation
inverseVolumeDiffusivity()
inverseVolumeDiffusivity (const fvMesh & mesh, Istream & mdData)
Definition at line 45 of file inverseVolumeDiffusivity.C.
References inverseVolumeDiffusivity::correct().
~inverseVolumeDiffusivity()
~inverseVolumeDiffusivity () virtual
Definition at line 59 of file inverseVolumeDiffusivity.C.
Member Function Documentation
TypeName()
TypeName ("inverseVolume")
correct()
void correct () virtual
Reimplemented from uniformDiffusivity.
Definition at line 65 of file inverseVolumeDiffusivity.C.
References GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), Foam::dimless, Foam::fvc::interpolate(), mesh, IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef(), timeName, fvMesh::V(), and fvPatchFieldBase::zeroGradientType().
Referenced by inverseVolumeDiffusivity::inverseVolumeDiffusivity().
The documentation for this class was generated from the following files:
src/fvMotionSolver/motionDiffusivity/inverseVolume/inverseVolumeDiffusivity.H
src/fvMotionSolver/motionDiffusivity/inverseVolume/inverseVolumeDiffusivity.C