OpenFOAM: EulerFaDdtScheme< Type > Class Template Reference
EulerFaDdtScheme< Type > Class Template Reference
#include <EulerFaDdtScheme.H>
Public Member Functions
TypeName ("Euler")
EulerFaDdtScheme (const faMesh &mesh)
EulerFaDdtScheme (const faMesh &mesh, Istream &is)
const faMesh & mesh () const
tmp< GeometricField< Type, faPatchField, areaMesh > > facDdt (const dimensioned< Type >)
tmp< GeometricField< Type, faPatchField, areaMesh > > facDdt0 (const dimensioned< Type >)
tmp< GeometricField< Type, faPatchField, areaMesh > > facDdt (const GeometricField< Type, faPatchField, areaMesh > &)
tmp< GeometricField< Type, faPatchField, areaMesh > > facDdt0 (const GeometricField< Type, faPatchField, areaMesh > &)
tmp< GeometricField< Type, faPatchField, areaMesh > > facDdt (const dimensionedScalar &, const GeometricField< Type, faPatchField, areaMesh > &)
tmp< GeometricField< Type, faPatchField, areaMesh > > facDdt0 (const dimensionedScalar &, const GeometricField< Type, faPatchField, areaMesh > &)
tmp< GeometricField< Type, faPatchField, areaMesh > > facDdt (const areaScalarField &, const GeometricField< Type, faPatchField, areaMesh > &)
tmp< GeometricField< Type, faPatchField, areaMesh > > facDdt0 (const areaScalarField &, const GeometricField< Type, faPatchField, areaMesh > &)
tmp< faMatrix< Type > > famDdt (const GeometricField< Type, faPatchField, areaMesh > &)
tmp< faMatrix< Type > > famDdt (const dimensionedScalar &, const GeometricField< Type, faPatchField, areaMesh > &)
tmp< faMatrix< Type > > famDdt (const areaScalarField &, const GeometricField< Type, faPatchField, areaMesh > &)
Public Member Functions inherited from faDdtScheme< Type >
virtual const word & type () const =0
declareRunTimeSelectionTable (tmp, faDdtScheme, Istream,(const faMesh &mesh, Istream &schemeData),(mesh, schemeData))
faDdtScheme (const faMesh &mesh)
faDdtScheme (const faMesh &mesh, Istream &)
virtual ~faDdtScheme ()
const faMesh & mesh () const
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Additional Inherited Members
Static Public Member Functions inherited from faDdtScheme< Type >
static tmp< faDdtScheme< Type > > New (const faMesh &mesh, Istream &schemeData)
Protected Member Functions inherited from faDdtScheme< Type >
faDdtScheme (const faDdtScheme &)=delete
void operator= (const faDdtScheme &)=delete
Protected Attributes inherited from faDdtScheme< Type >
const faMesh & mesh_
Detailed Description
template<class Type>
class Foam::fa::EulerFaDdtScheme< Type >
Definition at line 53 of file EulerFaDdtScheme.H.
Constructor & Destructor Documentation
EulerFaDdtScheme() [1/2]
template<class Type > EulerFaDdtScheme (const faMesh & mesh) inline
Definition at line 75 of file EulerFaDdtScheme.H.
EulerFaDdtScheme() [2/2]
template<class Type > EulerFaDdtScheme (const faMesh & mesh, Istream & is) inline
Definition at line 81 of file EulerFaDdtScheme.H.
Member Function Documentation
TypeName()
template<class Type > TypeName ("Euler")
mesh()
template<class Type > const faMesh & mesh () const inline
Definition at line 90 of file EulerFaDdtScheme.H.
References faDdtScheme< Type >::mesh().
facDdt() [1/4]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > facDdt (const dimensioned< Type > dt) virtual
Implements faDdtScheme< Type >.
Definition at line 39 of file EulerFaDdtScheme.C.
References faPatchFieldBase::calculatedType(), Foam::dimTime, mesh, Foam::New(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, timeName, and Foam::Zero.
facDdt0() [1/4]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > facDdt0 (const dimensioned< Type > dt) virtual
Implements faDdtScheme< Type >.
Definition at line 86 of file EulerFaDdtScheme.C.
References mesh, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, and timeName.
facDdt() [2/4]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > facDdt (const GeometricField< Type, faPatchField, areaMesh > & vf) virtual
Implements faDdtScheme< Type >.
Definition at line 124 of file EulerFaDdtScheme.C.
References mesh, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, and timeName.
facDdt0() [2/4]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > facDdt0 (const GeometricField< Type, faPatchField, areaMesh > & vf) virtual
Implements faDdtScheme< Type >.
Definition at line 177 of file EulerFaDdtScheme.C.
References mesh, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, and timeName.
facDdt() [3/4]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > facDdt (const dimensionedScalar & rho, const GeometricField< Type, faPatchField, areaMesh > & vf) virtual
Implements faDdtScheme< Type >.
Definition at line 223 of file EulerFaDdtScheme.C.
References mesh, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, rho, and timeName.
facDdt0() [3/4]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > facDdt0 (const dimensionedScalar & rho, const GeometricField< Type, faPatchField, areaMesh > & vf) virtual
Implements faDdtScheme< Type >.
Definition at line 276 of file EulerFaDdtScheme.C.
References mesh, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, rho, and timeName.
facDdt() [4/4]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > facDdt (const areaScalarField & rho, const GeometricField< Type, faPatchField, areaMesh > & vf) virtual
Implements faDdtScheme< Type >.
Definition at line 325 of file EulerFaDdtScheme.C.
References mesh, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, rho, and timeName.
facDdt0() [4/4]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > facDdt0 (const areaScalarField & rho, const GeometricField< Type, faPatchField, areaMesh > & vf) virtual
Implements faDdtScheme< Type >.
Definition at line 382 of file EulerFaDdtScheme.C.
References mesh, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, rho, and timeName.
famDdt() [1/3]
template<class Type > tmp< faMatrix< Type > > famDdt (const GeometricField< Type, faPatchField, areaMesh > & vf) virtual
Implements faDdtScheme< Type >.
Definition at line 436 of file EulerFaDdtScheme.C.
References Foam::dimArea, Foam::dimTime, and mesh.
famDdt() [2/3]
template<class Type > tmp< faMatrix< Type > > famDdt (const dimensionedScalar & rho, const GeometricField< Type, faPatchField, areaMesh > & vf) virtual
Implements faDdtScheme< Type >.
Definition at line 471 of file EulerFaDdtScheme.C.
References Foam::dimArea, Foam::dimTime, mesh, and rho.
famDdt() [3/3]
template<class Type > tmp< faMatrix< Type > > famDdt (const areaScalarField & rho, const GeometricField< Type, faPatchField, areaMesh > & vf) virtual
Implements faDdtScheme< Type >.
Definition at line 508 of file EulerFaDdtScheme.C.
References Foam::dimArea, Foam::dimTime, mesh, and rho.
The documentation for this class was generated from the following files:
src/finiteArea/finiteArea/ddtSchemes/EulerFaDdtScheme/EulerFaDdtScheme.H
src/finiteArea/finiteArea/ddtSchemes/EulerFaDdtScheme/EulerFaDdtScheme.C