OpenFOAM: interfaceProperties Class Reference
interfaceProperties Class Reference
Contains the interface properties.
#include <interfaceProperties.H>
Public Member Functions
interfaceProperties (const volScalarField &alpha1, const volVectorField &U, const IOdictionary &)
scalar cAlpha () const
const dimensionedScalar & deltaN () const
const surfaceScalarField & nHatf () const
tmp< volScalarField > sigmaK () const
tmp< surfaceScalarField > surfaceTensionForce () const
tmp< volScalarField > nearInterface () const
void correct ()
bool read ()
Detailed Description
Contains the interface properties.
Properties to aid interFoam:
Correct the alpha boundary condition for dynamic contact angle.
Calculate interface curvature.
References:
    Smoother algorithm for interface curvatures (tag:YK):
        Yamamoto, T. & Komarov, S. V. (2022).
        Evaluation on different volume of fluid methods in
        unstructured solver under the optimized condition. Preprint.
        DOI:10.13140/RG.2.2.17223.37281
Source files
interfaceProperties.H
interfaceProperties.C
Definition at line 63 of file interfaceProperties.H.
Constructor & Destructor Documentation
interfaceProperties()
interfaceProperties (const volScalarField & alpha1, const volVectorField & U, const IOdictionary & dict)
Definition at line 164 of file interfaceProperties.C.
Member Function Documentation
cAlpha()
scalar cAlpha () const inline
Definition at line 124 of file interfaceProperties.H.
deltaN()
const dimensionedScalar & deltaN () const inline
Definition at line 129 of file interfaceProperties.H.
nHatf()
const surfaceScalarField & nHatf () const inline
Definition at line 134 of file interfaceProperties.H.
sigmaK()
Foam::tmp< Foam::volScalarField > sigmaK () const
Definition at line 224 of file interfaceProperties.C.
surfaceTensionForce()
Foam::tmp< Foam::surfaceScalarField > surfaceTensionForce () const
Definition at line 231 of file interfaceProperties.C.
References Foam::fvc::interpolate(), and Foam::fvc::snGrad().
nearInterface()
Foam::tmp< Foam::volScalarField > nearInterface () const
Definition at line 238 of file interfaceProperties.C.
References Foam::pos0().
correct()
void correct ()
Definition at line 244 of file interfaceProperties.C.
Referenced by immiscibleIncompressibleTwoPhaseMixture::correct().
read()
bool read ()
Definition at line 250 of file interfaceProperties.C.
Referenced by immiscibleIncompressibleTwoPhaseMixture::read().
The documentation for this class was generated from the following files:
src/transportModels/interfaceProperties/interfaceProperties.H
src/transportModels/interfaceProperties/interfaceProperties.C