OpenFOAM: voxelMeshSearch Class Reference
voxelMeshSearch Class Reference
Fast, non-parallel searching in mesh without use of octree.
#include <voxelMeshSearch.H>
Public Member Functions
ClassName ("voxelMeshSearch")
voxelMeshSearch (const polyMesh &, const bool doUpdate=true)
voxelMeshSearch (const polyMesh &, const boundBox &bb, const labelVector &nDivs, const bool doUpdate=true)
const labelVector & nDivs () const
bool update ()
label findCell (const point &) const
autoPtr< fvMesh > makeMesh (const IOobject &) const
Static Public Member Functions
static label index (const labelVector &nDivs, const labelVector &voxel)
static labelVector offset (const labelVector &nDivs)
static labelVector index3 (const labelVector &nDivs, const label voxeli)
static labelVector index3 (const boundBox &bb, const labelVector &nDivs, const point &p)
static point centre (const boundBox &bb, const labelVector &nDivs, const labelVector &voxel)
static label index (const boundBox &bb, const labelVector &nDivs, const point &p, const bool clip)
template<class Container , class Type >
static void fill (Container &elems, const boundBox &bb, const labelVector &nDivs, const boundBox &subBb, const Type val)
template<class Container , class Type , class CombineOp >
static void fill (Container &elems, const boundBox &bb, const labelVector &nDivs, const boundBox &subBb, const Type val, const CombineOp &cop=eqOp< Type >())
template<class Container , class Type >
static bool overlaps (const boundBox &bb, const labelVector &nDivs, const boundBox &subBb, const Container &elems, const Type val, const bool isNot=false)
template<class Container , class Type >
static void write (OBJstream &, const boundBox &bb, const labelVector &nDivs, const Container &elems, const Type val, const bool isNot=false)
static void writeGrid (OBJstream &, const boundBox &, const labelVector &)
Detailed Description
Fast, non-parallel searching in mesh without use of octree.
Source files
voxelMeshSearch.H
voxelMeshSearch.C
Definition at line 53 of file voxelMeshSearch.H.
Constructor & Destructor Documentation
voxelMeshSearch() [1/2]
voxelMeshSearch (const polyMesh & mesh, const bool doUpdate = true)
Definition at line 279 of file voxelMeshSearch.C.
References Foam::cbrt(), e, Foam::endl(), forAll, boundBox::max(), Foam::max(), boundBox::min(), voxelMeshSearch::nDivs(), Foam::Pout, Foam::sqrt(), and voxelMeshSearch::update().
voxelMeshSearch() [2/2]
voxelMeshSearch (const polyMesh & mesh, const boundBox & bb, const labelVector & nDivs, const bool doUpdate = true)
Definition at line 337 of file voxelMeshSearch.C.
References voxelMeshSearch::update().
Member Function Documentation
ClassName()
ClassName ("voxelMeshSearch")
nDivs()
const labelVector & nDivs () const inline
Definition at line 105 of file voxelMeshSearch.H.
Referenced by voxelMeshSearch::fill(), voxelMeshSearch::offset(), and voxelMeshSearch::voxelMeshSearch().
update()
bool update ()
Definition at line 358 of file voxelMeshSearch.C.
References Foam::cmptProduct(), Foam::endl(), forAll, OSstream::name(), points, Foam::Pout, and PtrList< T >::setSize().
Referenced by voxelMeshSearch::voxelMeshSearch(), and voxelMeshSearch::voxelMeshSearch().
findCell()
Foam::label findCell (const point & p) const
Definition at line 402 of file voxelMeshSearch.C.
References PtrList< T >::append(), PtrList< T >::clear(), Foam::max(), and p.
index() [1/2]
Foam::label index (const labelVector & nDivs, const labelVector & voxel) static
Definition at line 49 of file voxelMeshSearch.C.
References Vector< Cmpt >::x(), and Vector< Cmpt >::y().
Referenced by voxelMeshSearch::fill().
offset()
Foam::labelVector offset (const labelVector & nDivs) static
Definition at line 40 of file voxelMeshSearch.C.
References voxelMeshSearch::nDivs().
Referenced by voxelMeshSearch::fill().
index3() [1/2]
Foam::labelVector index3 (const labelVector & nDivs, const label voxeli) static
Definition at line 59 of file voxelMeshSearch.C.
References Vector< Cmpt >::x(), and Vector< Cmpt >::y().
Referenced by voxelMeshSearch::fill().
index3() [2/2]
Foam::labelVector index3 (const boundBox & bb, const labelVector & nDivs, const point & p) static
Definition at line 77 of file voxelMeshSearch.C.
References Foam::cmptDivide(), g, boundBox::min(), s(), boundBox::span(), Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
centre()
Foam::point centre (const boundBox & bb, const labelVector & nDivs, const labelVector & voxel) static
Definition at line 137 of file voxelMeshSearch.C.
References Foam::cmptDivide(), g, boundBox::min(), s(), and boundBox::span().
index() [2/2]
Foam::label index (const boundBox & bb, const labelVector & nDivs, const point & p, const bool clip) static
Definition at line 97 of file voxelMeshSearch.C.
References Foam::clip(), Foam::cmptDivide(), g, Foam::max(), boundBox::min(), Foam::min(), s(), boundBox::span(), Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
fill() [1/2]
template<class Container , class Type > void fill (Container & elems, const boundBox & bb, const labelVector & nDivs, const boundBox & subBb, const Type val) static
Definition at line 27 of file voxelMeshSearchTemplates.C.
References voxelMeshSearch::index(), voxelMeshSearch::index3(), k, Foam::max(), Foam::min(), voxelMeshSearch::nDivs(), and voxelMeshSearch::offset().
Referenced by trackingInverseDistance::markBoundaries().
fill() [2/2]
template<class Container , class Type , class CombineOp > void fill (Container & elems, const boundBox & bb, const labelVector & nDivs, const boundBox & subBb, const Type val, const CombineOp & cop = eqOp<Type>()) static
Definition at line 71 of file voxelMeshSearchTemplates.C.
References k, Foam::max(), and Foam::min().
overlaps()
template<class Container , class Type > bool overlaps (const boundBox & bb, const labelVector & nDivs, const boundBox & subBb, const Container & elems, const Type val, const bool isNot = false) static
Definition at line 116 of file voxelMeshSearchTemplates.C.
References Foam::cmptProduct(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, k, Foam::max(), Foam::min(), and UPtrList< T >::size().
Referenced by trackingInverseDistance::markBoundaries(), and trackingInverseDistance::markPatchesAsHoles().
write()
template<class Container , class Type > void write (OBJstream & os, const boundBox & bb, const labelVector & nDivs, const Container & elems, const Type val, const bool isNot = false) static
Definition at line 176 of file voxelMeshSearchTemplates.C.
References Foam::cmptProduct(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, k, os(), UPtrList< T >::size(), and OBJstream::write().
writeGrid()
void writeGrid (OBJstream & os, const boundBox & bb, const labelVector & g) static
Definition at line 150 of file voxelMeshSearch.C.
References Foam::cmptDivide(), g, k, boundBox::min(), os(), s(), boundBox::span(), and OBJstream::writeLine().
makeMesh()
Foam::autoPtr< Foam::fvMesh > makeMesh (const IOobject & io) const
Definition at line 487 of file voxelMeshSearch.C.
References b, boundary, boundaryDicts(), cellShapes, fvMeshTools::createDummyFvMeshFiles(), IOobject::db(), patchIdentifier::defaultName(), forAll, cellModel::HEX, Foam::identity(), io(), mesh, IOobjectOption::MUST_READ, IOobject::name(), autoPtr< T >::New(), IOobjectOption::NO_READ, patchNames(), points, cellShape::points(), PtrList< T >::set(), List< T >::setSize(), UList< T >::size(), List< T >::transfer(), PtrList< T >::transfer(), and fvMesh::write().
The documentation for this class was generated from the following files:
src/overset/cellCellStencil/trackingInverseDistance/voxelMeshSearch.H
src/overset/cellCellStencil/trackingInverseDistance/voxelMeshSearch.C
src/overset/cellCellStencil/trackingInverseDistance/voxelMeshSearchTemplates.C