OpenFOAM: CSV< Type > Class Template Reference
CSV< Type > Class Template Reference
Templated CSV function.
#include <CSV.H>
Public Member Functions
void operator= (const CSV< Type > &)=delete
TypeName ("csvFile")
CSV (const word &entryName, const dictionary &dict, const objectRegistry *obrPtr=nullptr, const fileName &fName=fileName::null)
CSV (const CSV< Type > &csv)
virtual tmp< Function1< Type > > clone () const
virtual ~CSV ()=default
virtual const fileName & fName () const
virtual void writeData (Ostream &os) const
virtual void writeEntries (Ostream &os) const
Public Member Functions inherited from TableBase< Type >
TableBase (const word &name, const dictionary &dict, const objectRegistry *obrPtr=nullptr)
TableBase (const TableBase< Type > &tbl)
virtual ~TableBase ()=default
void initialise ()
bool checkMinBounds (const scalar x, scalar &xDash) const
bool checkMaxBounds (const scalar x, scalar &xDash) const
virtual void userTimeToTime (const Time &t)
virtual Type value (const scalar x) const
virtual Type integrate (const scalar x1, const scalar x2) const
virtual tmp< scalarField > x () const
virtual tmp< Field< Type > > y () const
Public Member Functions inherited from Function1< Type >
TypeName ("Function1") declareRunTimeSelectionTable(autoPtr
Function1 (const word &entryName, const objectRegistry *obrPtr=nullptr)
Function1 (const word &entryName, const dictionary &dict, const objectRegistry *obrPtr=nullptr)
Function1 (const Function1< Type > &rhs)
virtual ~Function1 ()=default
virtual bool constant () const
virtual bool good () const
virtual tmp< Field< Type > > value (const scalarField &x) const
virtual tmp< Field< Type > > integrate (const scalarField &x1, const scalarField &x2) const
Public Member Functions inherited from function1Base
function1Base (const word &entryName, const objectRegistry *obrPtr=nullptr)
function1Base (const word &entryName, const dictionary &dict, const objectRegistry *obrPtr=nullptr)
function1Base (const function1Base &rhs)
virtual ~function1Base ()
const word & name () const noexcept
const objectRegistry * whichDb () const noexcept
void resetDb (const objectRegistry *obrPtr=nullptr) noexcept
void resetDb (const objectRegistry &db) noexcept
const objectRegistry & obr () const
bool isTime () const noexcept
const Time & time () const
template<class MeshType >
const MeshType & mesh (const word &regionName=word::null) const
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Additional Inherited Members
Public Types inherited from Function1< Type >
typedef Type returnType
Static Public Member Functions inherited from Function1< Type >
static autoPtr< Function1< Type > > New (const word &entryName, const dictionary &dict, const word &redirectType, const objectRegistry *obrPtr=nullptr, const bool mandatory=true)
static autoPtr< Function1< Type > > NewCompat (const word &entryName, std::initializer_list< std::pair< const char *, int > > compat, const dictionary &dict, const word &redirectType=word::null, const objectRegistry *obrPtr=nullptr, const bool mandatory=true)
static autoPtr< Function1< Type > > New (const word &entryName, const dictionary &dict, const objectRegistry *obrPtr=nullptr, const bool mandatory=true)
static autoPtr< Function1< Type > > NewIfPresent (const word &entryName, const dictionary &dict, const word &redirectType, const objectRegistry *obrPtr=nullptr)
static autoPtr< Function1< Type > > NewIfPresent (const word &entryName, const dictionary &dict, const objectRegistry *obrPtr=nullptr)
static refPtr< Function1< Type > > New (HashPtrTable< Function1< Type > > &cache, const word &entryName, const dictionary &dict, enum keyType::option matchOpt=keyType::LITERAL, const objectRegistry *obrPtr=nullptr, const bool mandatory=true)
Public Attributes inherited from Function1< Type >
Function1
dictionary
const word & entryName
const word const dictionary & dict
const word const dictionary const objectRegistry * obrPtr
const word const dictionary const objectRegistry entryName
const word const dictionary const objectRegistry dict
const word const dictionary const objectRegistry obrPtr
Protected Member Functions inherited from TableBase< Type >
const interpolationWeights & interpolator () const
void operator= (const TableBase< Type > &)=delete
Protected Member Functions inherited from Function1< Type >
void operator= (const Function1< Type > &)=delete
Protected Member Functions inherited from function1Base
void operator= (const function1Base &)=delete
Protected Attributes inherited from TableBase< Type >
const bounds::repeatableBounding bounding_
const word interpolationScheme_
List< Tuple2< scalar, Type > > table_
autoPtr< scalarField > tableSamplesPtr_
autoPtr< interpolationWeights > interpolatorPtr_
labelList currentIndices_
scalarField currentWeights_
Protected Attributes inherited from function1Base
const word name_
const objectRegistry * obrPtr_
Detailed Description
template<class Type>
class Foam::Function1Types::CSV< Type >
Templated CSV function.
Reference column is always a scalar, e.g. time.
Usage:
    <entryName> csvFile;
    <entryName>Coeffs
    {
        nHeaderLine         4;          // number of header lines
        refColumn           0;          // reference column index
        componentColumns    (1 2 3);    // component column indices
        separator           ",";        // optional (defaults to ",")
        mergeSeparators     no;         // merge multiple separators
        file                "fileXYZ";  // name of csv data file
        outOfBounds         clamp;      // optional out-of-bounds handling
        interpolationScheme linear;     // optional interpolation scheme
    }
Source files
CSV.H
CSV.C
Definition at line 71 of file CSV.H.
Constructor & Destructor Documentation
CSV() [1/2]
template<class Type > CSV (const word & entryName, const dictionary & dict, const objectRegistry * obrPtr = nullptr, const fileName & fName = fileName::null)
Definition at line 191 of file CSV.C.
References TableBase< Type >::initialise().
CSV() [2/2]
template<class Type > CSV (const CSV< Type > & csv) explicit
Definition at line 214 of file CSV.C.
~CSV()
template<class Type > virtual ~CSV () virtual default
Member Function Documentation
operator=()
template<class Type > void operator= (const CSV< Type > &) delete
TypeName()
template<class Type > TypeName ("csvFile")
clone()
template<class Type > virtual tmp< Function1< Type > > clone () const inline virtual
Implements Function1< Type >.
Definition at line 139 of file CSV.H.
fName()
template<class Type > const Foam::fileName & fName () const virtual
Definition at line 229 of file CSV.C.
writeData()
template<class Type > void writeData (Ostream & os) const virtual
Reimplemented from TableBase< Type >.
Definition at line 257 of file CSV.C.
References Foam::name(), os(), and Function1< Type >::writeData().
writeEntries()
template<class Type > void writeEntries (Ostream & os) const virtual
Reimplemented from TableBase< Type >.
Definition at line 236 of file CSV.C.
References IOstreamOption::ASCII, os(), and TableBase< Type >::writeEntries().
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/functions/Function1/CSV/CSV.H
src/OpenFOAM/primitives/functions/Function1/CSV/CSV.C