OpenFOAM: distributedDILUPreconditioner Class Reference
distributedDILUPreconditioner Class Reference
Numerics » Matrix manipulation and solvers » Preconditioners
Version of DILUpreconditioner that uses preconditioning across processor (and coupled) boundaries. Based on 'Parallel Preconditioners' chapter from 'Iterative Methods for Sparse Linear Systems' by Yousef Saad.
#include <distributedDILUPreconditioner.H>
Public Member Functions
TypeName ("distributedDILU")
distributedDILUPreconditioner (const lduMatrix::solver &, const dictionary &solverControlsUnused)
virtual ~distributedDILUPreconditioner ()
virtual void precondition (solveScalarField &wA, const solveScalarField &rA, const direction cmpt=0) const
virtual void setFinished (const solverPerformance &perf) const
Public Member Functions inherited from lduMatrix::preconditioner
virtual const word & type () const =0
declareRunTimeSelectionTable (autoPtr, preconditioner, symMatrix,(const solver &sol, const dictionary &solverControls),(sol, solverControls))
declareRunTimeSelectionTable (autoPtr, preconditioner, asymMatrix,(const solver &sol, const dictionary &solverControls),(sol, solverControls))
preconditioner (const solver &sol)
virtual ~preconditioner ()=default
virtual void read (const dictionary &)
virtual void preconditionT (solveScalarField &wT, const solveScalarField &rT, const direction cmpt=0) const
Protected Member Functions
void updateMatrixInterfaces (const bool add, const FieldField< Field, scalar > &coupleCoeffs, const labelList &selectedInterfaces, const solveScalarField &psiif, solveScalarField &result, const direction cmpt) const
void sendGlobal (const labelList &selectedInterfaces, solveScalarField &psi, const label colouri) const
void receive (const labelList &selectedInterfaces, DynamicList< UPstream::Request > &requests) const
void send (const labelList &selectedInterfaces, const solveScalarField &psiInternal, DynamicList< UPstream::Request > &requests) const
void wait (DynamicList< UPstream::Request > &requests, const bool cancel=false) const
virtual void addInterfaceDiag (solveScalarField &rD, const label inti, const Field< solveScalar > &recvBuf) const
virtual void forwardInternalDiag (solveScalarField &rD, const label colouri) const
virtual void addInterface (solveScalarField &wA, const label inti, const Field< solveScalar > &recvBuf) const
virtual void forwardInternal (solveScalarField &wA, const label colouri) const
virtual void backwardInternal (solveScalarField &wA, const label colouri) const
virtual void calcReciprocalD (solveScalarField &rD) const
Protected Attributes
const bool coupled_
FieldField< Field, solveScalar > sendBufs_
FieldField< Field, solveScalar > recvBufs_
DynamicList< UPstream::Request > recvRequests_
DynamicList< label > lowerNbrs_
DynamicList< UPstream::Request > lowerSendRequests_
DynamicList< UPstream::Request > lowerRecvRequests_
DynamicList< label > higherNbrs_
DynamicList< UPstream::Request > higherSendRequests_
DynamicList< UPstream::Request > higherRecvRequests_
autoPtr< labelList > cellColourPtr_
label nColours_
PtrList< FieldField< Field, solveScalar > > colourBufs_
List< DynamicList< label > > lowerGlobalRecv_
List< DynamicList< label > > lowerGlobalSend_
List< label > lowerColour_
List< DynamicList< label > > higherGlobalRecv_
List< DynamicList< label > > higherGlobalSend_
List< label > higherColour_
solveScalarField rD_
Protected Attributes inherited from lduMatrix::preconditioner
const solver & solver_
Static Protected Attributes
static const lduMesh * meshPtr_ = nullptr
static autoPtr< labelList > procColoursPtr_
Additional Inherited Members
Static Public Member Functions inherited from lduMatrix::preconditioner
static word getName (const dictionary &)
static autoPtr< preconditioner > New (const solver &sol, const dictionary &solverControls)
Detailed Description
Version of DILUpreconditioner that uses preconditioning across processor (and coupled) boundaries. Based on 'Parallel Preconditioners' chapter from 'Iterative Methods for Sparse Linear Systems' by Yousef Saad.
Leaves out the handling of boundary nodes after internal nodes since probably not beneficial (so no overlap of comms and internal calculation)
By default preconditions across coupled boundaries (currently only tested for cyclicAMI). This can be disabled with the 'coupled' setting
solver PCG; preconditioner { preconditioner distributedDILU; coupled false; }
The cyclicAMI boundary behaviour will only work if
running non-parallel or
different sides of cyclicAMI run on different processors i.e. there is no processor which has cells on both owner and neighbour of the patch pair.
See also
Foam::DILUPreconditioner Foam::distributedDICPreconditioner
Source files
distributedDILUPreconditioner.H
distributedDILUPreconditioner.C
Definition at line 74 of file distributedDILUPreconditioner.H.
Constructor & Destructor Documentation
distributedDILUPreconditioner()
distributedDILUPreconditioner (const lduMatrix::solver & sol, const dictionary & solverControlsUnused)
Definition at line 517 of file distributedDILUPreconditioner.C.
References DynamicList< T, SizeMin >::append(), List< T >::append(), distributedDILUPreconditioner::calcReciprocalD(), processorColour::cellColour(), distributedDILUPreconditioner::cellColourPtr_, PtrList< T >::clear(), processorColour::colour(), distributedDILUPreconditioner::colourBufs_, distributedDILUPreconditioner::coupled_, Foam::endl(), Foam::flatOutput(), forAll, distributedDILUPreconditioner::higherColour_, distributedDILUPreconditioner::higherGlobalRecv_, distributedDILUPreconditioner::higherGlobalSend_, distributedDILUPreconditioner::higherNbrs_, Foam::incrIndent(), Foam::indent(), Foam::Info, distributedDILUPreconditioner::lowerColour_, distributedDILUPreconditioner::lowerGlobalRecv_, distributedDILUPreconditioner::lowerGlobalSend_, distributedDILUPreconditioner::lowerNbrs_, mesh, distributedDILUPreconditioner::meshPtr_, UPstream::myProcNo(), distributedDILUPreconditioner::nColours_, UPstream::nProcs(), distributedDILUPreconditioner::procColoursPtr_, distributedDILUPreconditioner::rD_, distributedDILUPreconditioner::recvBufs_, List< T >::resize_nocopy(), distributedDILUPreconditioner::sendBufs_, PtrList< T >::set(), List< T >::setSize(), PtrList< T >::setSize(), UPtrList< T >::size(), WarningInFunction, and Foam::Zero.
~distributedDILUPreconditioner()
~distributedDILUPreconditioner () virtual
Definition at line 759 of file distributedDILUPreconditioner.C.
References DebugPout, and Foam::endl().
Member Function Documentation
updateMatrixInterfaces()
void updateMatrixInterfaces (const bool add, const FieldField< Field, scalar > & coupleCoeffs, const labelList & selectedInterfaces, const solveScalarField & psiif, solveScalarField & result, const direction cmpt) const protected
Definition at line 45 of file distributedDILUPreconditioner.C.
References Foam::add(), UPstream::msgType(), UPstream::nonBlocking, UPstream::nRequests(), lduMatrix::preconditioner::solver_, and UPstream::waitRequests().
sendGlobal()
void sendGlobal (const labelList & selectedInterfaces, solveScalarField & psi, const label colouri) const protected
Definition at line 103 of file distributedDILUPreconditioner.C.
References forAll, psi, PtrList< T >::set(), PtrList< T >::setSize(), and UPtrList< T >::size().
receive()
void receive (const labelList & selectedInterfaces, DynamicList< UPstream::Request > & requests) const protected
Definition at line 172 of file distributedDILUPreconditioner.C.
References UPtrList< T >::back(), PtrList< T >::push_back(), and UIPstream::read().
send()
void send (const labelList & selectedInterfaces, const solveScalarField & psiInternal, DynamicList< UPstream::Request > & requests) const protected
Definition at line 204 of file distributedDILUPreconditioner.C.
References UPtrList< T >::back(), forAll, PtrList< T >::push_back(), and UOPstream::write().
wait()
void wait (DynamicList< UPstream::Request > & requests, const bool cancel = false) const protected
Definition at line 242 of file distributedDILUPreconditioner.C.
References UPstream::cancelRequests(), PtrList< T >::clear(), and UPstream::waitRequests().
addInterfaceDiag()
void addInterfaceDiag (solveScalarField & rD, const label inti, const Field< solveScalar > & recvBuf) const protected virtual
Definition at line 263 of file distributedDILUPreconditioner.C.
References forAll.
forwardInternalDiag()
void forwardInternalDiag (solveScalarField & rD, const label colouri) const protected virtual
Reimplemented in distributedDICPreconditioner.
Definition at line 289 of file distributedDILUPreconditioner.C.
References UPtrList< T >::begin(), and UPtrList< T >::size().
addInterface()
void addInterface (solveScalarField & wA, const label inti, const Field< solveScalar > & recvBuf) const protected virtual
Definition at line 328 of file distributedDILUPreconditioner.C.
References UPtrList< T >::begin(), and forAll.
forwardInternal()
void forwardInternal (solveScalarField & wA, const label colouri) const protected virtual
Reimplemented in distributedDICPreconditioner.
Definition at line 353 of file distributedDILUPreconditioner.C.
References UPtrList< T >::begin(), and UPtrList< T >::size().
backwardInternal()
void backwardInternal (solveScalarField & wA, const label colouri) const protected virtual
Definition at line 397 of file distributedDILUPreconditioner.C.
References UPtrList< T >::begin(), and UPtrList< T >::size().
calcReciprocalD()
void calcReciprocalD (solveScalarField & rD) const protected virtual
Definition at line 440 of file distributedDILUPreconditioner.C.
References UPtrList< T >::begin(), UList< T >::begin(), Foam::diag(), UPtrList< T >::end(), List< T >::resize_nocopy(), UPtrList< T >::size(), and UList< T >::size().
Referenced by distributedDILUPreconditioner::distributedDILUPreconditioner().
TypeName()
TypeName ("distributedDILU")
precondition()
void precondition (solveScalarField & wA, const solveScalarField & rA, const direction cmpt = 0) const virtual
Implements lduMatrix::preconditioner.
Definition at line 780 of file distributedDILUPreconditioner.C.
References UPtrList< T >::begin(), and UPtrList< T >::size().
setFinished()
void setFinished (const solverPerformance & perf) const virtual
Reimplemented from lduMatrix::preconditioner.
Definition at line 906 of file distributedDILUPreconditioner.C.
References DebugPout, Foam::endl(), and s().
Member Data Documentation
coupled_
const bool coupled_ protected
Definition at line 83 of file distributedDILUPreconditioner.H.
Referenced by distributedDILUPreconditioner::distributedDILUPreconditioner().
meshPtr_
const lduMesh * meshPtr_ = nullptr static protected
Definition at line 89 of file distributedDILUPreconditioner.H.
Referenced by distributedDILUPreconditioner::distributedDILUPreconditioner().
procColoursPtr_
autoPtr< labelList > procColoursPtr_ static protected
Definition at line 92 of file distributedDILUPreconditioner.H.
Referenced by distributedDILUPreconditioner::distributedDILUPreconditioner().
sendBufs_
FieldField<Field, solveScalar> sendBufs_ mutable protected
Definition at line 95 of file distributedDILUPreconditioner.H.
Referenced by distributedDILUPreconditioner::distributedDILUPreconditioner().
recvBufs_
FieldField<Field, solveScalar> recvBufs_ mutable protected
Definition at line 96 of file distributedDILUPreconditioner.H.
Referenced by distributedDILUPreconditioner::distributedDILUPreconditioner().
recvRequests_
DynamicList<UPstream::Request> recvRequests_ mutable protected
Definition at line 97 of file distributedDILUPreconditioner.H.
lowerNbrs_
DynamicList<label> lowerNbrs_ protected
Definition at line 100 of file distributedDILUPreconditioner.H.
Referenced by distributedDILUPreconditioner::distributedDILUPreconditioner().
lowerSendRequests_
DynamicList<UPstream::Request> lowerSendRequests_ mutable protected
Definition at line 101 of file distributedDILUPreconditioner.H.
lowerRecvRequests_
DynamicList<UPstream::Request> lowerRecvRequests_ mutable protected
Definition at line 102 of file distributedDILUPreconditioner.H.
higherNbrs_
DynamicList<label> higherNbrs_ protected
Definition at line 105 of file distributedDILUPreconditioner.H.
Referenced by distributedDILUPreconditioner::distributedDILUPreconditioner().
higherSendRequests_
DynamicList<UPstream::Request> higherSendRequests_ mutable protected
Definition at line 106 of file distributedDILUPreconditioner.H.
higherRecvRequests_
DynamicList<UPstream::Request> higherRecvRequests_ mutable protected
Definition at line 107 of file distributedDILUPreconditioner.H.
cellColourPtr_
autoPtr<labelList> cellColourPtr_ protected
Definition at line 113 of file distributedDILUPreconditioner.H.
Referenced by distributedDILUPreconditioner::distributedDILUPreconditioner(), and distributedDICPreconditioner::forwardInternalDiag().
nColours_
label nColours_ protected
Definition at line 117 of file distributedDILUPreconditioner.H.
Referenced by distributedDILUPreconditioner::distributedDILUPreconditioner().
colourBufs_
PtrList<FieldField<Field, solveScalar> > colourBufs_ mutable protected
Definition at line 123 of file distributedDILUPreconditioner.H.
Referenced by distributedDILUPreconditioner::distributedDILUPreconditioner().
lowerGlobalRecv_
List<DynamicList<label> > lowerGlobalRecv_ protected
Definition at line 126 of file distributedDILUPreconditioner.H.
Referenced by distributedDILUPreconditioner::distributedDILUPreconditioner().
lowerGlobalSend_
List<DynamicList<label> > lowerGlobalSend_ protected
Definition at line 129 of file distributedDILUPreconditioner.H.
Referenced by distributedDILUPreconditioner::distributedDILUPreconditioner().
lowerColour_
List<label> lowerColour_ protected
Definition at line 132 of file distributedDILUPreconditioner.H.
Referenced by distributedDILUPreconditioner::distributedDILUPreconditioner().
higherGlobalRecv_
List<DynamicList<label> > higherGlobalRecv_ protected
Definition at line 135 of file distributedDILUPreconditioner.H.
Referenced by distributedDILUPreconditioner::distributedDILUPreconditioner().
higherGlobalSend_
List<DynamicList<label> > higherGlobalSend_ protected
Definition at line 138 of file distributedDILUPreconditioner.H.
Referenced by distributedDILUPreconditioner::distributedDILUPreconditioner().
higherColour_
List<label> higherColour_ protected
Definition at line 141 of file distributedDILUPreconditioner.H.
Referenced by distributedDILUPreconditioner::distributedDILUPreconditioner().
rD_
solveScalarField rD_ protected
Definition at line 145 of file distributedDILUPreconditioner.H.
Referenced by distributedDILUPreconditioner::distributedDILUPreconditioner().
The documentation for this class was generated from the following files:
src/meshTools/matrices/lduMatrix/preconditioners/distributedDILUPreconditioner/distributedDILUPreconditioner.H
src/meshTools/matrices/lduMatrix/preconditioners/distributedDILUPreconditioner/distributedDILUPreconditioner.C