OpenFOAM: SubStrings< StringType > Class Template Reference
SubStrings< StringType > Class Template Reference
Sub-ranges of a string with a structure similar to std::match_results, but without the underlying regular expression matching.
#include <SubStrings.H>
Public Types
using value_type = typename std::sub_match< typename StringType::const_iterator >
using string_iterator = typename StringType::const_iterator
Public Member Functions
SubStrings ()=default
std::string::size_type length () const
StringType str (size_t pos) const
void append (const typename StringType::const_iterator &b, const typename StringType::const_iterator &e)
auto first () const -> decltype(this->front())
auto last () const -> decltype(this->back())
Detailed Description
template<class StringType>
class Foam::SubStrings< StringType >
Sub-ranges of a string with a structure similar to std::match_results, but without the underlying regular expression matching.
Definition at line 45 of file SubStrings.H.
Member Typedef Documentation
value_type
template<class StringType > using value_type = typename std::sub_match<typename StringType::const_iterator>
Definition at line 54 of file SubStrings.H.
string_iterator
template<class StringType > using string_iterator = typename StringType::const_iterator
Definition at line 58 of file SubStrings.H.
Constructor & Destructor Documentation
SubStrings()
template<class StringType > SubStrings () default
Member Function Documentation
length()
template<class StringType > std::string::size_type length () const inline
Definition at line 72 of file SubStrings.H.
str()
template<class StringType > StringType str (size_t pos) const inline
Definition at line 85 of file SubStrings.H.
References Foam::pos().
Referenced by STARCDsurfaceFormatCore::readInpCellTable().
append()
template<class StringType > void append (const typename StringType::const_iterator & b, const typename StringType::const_iterator & e) inline
Definition at line 91 of file SubStrings.H.
References b, e, UPtrList< T >::first(), and range.
first()
template<class StringType > auto first () const -> decltype(this->front()) inline
Definition at line 107 of file SubStrings.H.
last()
template<class StringType > auto last () const -> decltype(this->back()) inline
Definition at line 114 of file SubStrings.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/strings/lists/CStringList.H
src/OpenFOAM/primitives/strings/lists/SubStrings.H