OpenFOAM: csvTableReader< Type > Class Template Reference
csvTableReader< Type > Class Template Reference
Reads an interpolation table from a file - CSV-format.
#include <csvTableReader.H>
Public Member Functions
TypeName ("csv")
csvTableReader (const dictionary &dict)
virtual autoPtr< tableReader< Type > > clone () const
virtual ~csvTableReader ()=default
virtual void operator() (const fileName &fName, List< Tuple2< scalar, Type > > &data)
virtual void operator() (const fileName &fName, List< Tuple2< scalar, List< Tuple2< scalar, Type > > > > &data)
virtual void write (Ostream &os) const
Public Member Functions inherited from tableReader< Type >
TypeName ("tableReader")
declareRunTimeSelectionTable (autoPtr, tableReader, dictionary,(const dictionary &dict),(dict))
tableReader ()=default
tableReader (const dictionary &dict)
virtual ~tableReader ()=default
Additional Inherited Members
Static Public Member Functions inherited from tableReader< Type >
static autoPtr< tableReader > New (const dictionary &spec)
Detailed Description
template<class Type>
class Foam::csvTableReader< Type >
Reads an interpolation table from a file - CSV-format.
Source files
csvTableReader.H
tableReader.C
Definition at line 49 of file csvTableReader.H.
Constructor & Destructor Documentation
csvTableReader()
template<class Type > csvTableReader (const dictionary & dict)
Definition at line 91 of file csvTableReader.C.
~csvTableReader()
template<class Type > virtual ~csvTableReader () virtual default
Member Function Documentation
TypeName()
template<class Type > TypeName ("csv")
clone()
template<class Type > virtual autoPtr< tableReader< Type > > clone () const inline virtual
Implements tableReader< Type >.
Definition at line 94 of file csvTableReader.H.
operator()() [1/2]
template<class Type > void operator() (const fileName & fName, List< Tuple2< scalar, Type > > & data) virtual
Implements tableReader< Type >.
Definition at line 107 of file csvTableReader.C.
References PtrList< T >::clear(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::fileHandler, Foam::findMax(), Foam::max(), n, Foam::nl, Foam::pos(), PtrList< T >::push_back(), UPtrList< T >::size(), dictionary::transfer(), and x.
operator()() [2/2]
template<class Type > void operator() (const fileName & fName, List< Tuple2< scalar, List< Tuple2< scalar, Type > > > > & data) virtual
Implements tableReader< Type >.
Definition at line 187 of file csvTableReader.C.
References NotImplemented.
write()
template<class Type > void write (Ostream & os) const virtual
Reimplemented from tableReader< Type >.
Definition at line 198 of file csvTableReader.C.
References IOstreamOption::ASCII, IOstreamOption::format(), os(), tableReader< Type >::write(), and Ostream::writeEntry().
The documentation for this class was generated from the following files:
src/OpenFOAM/interpolations/interpolationTable/tableReaders/csv/csvTableReader.H
src/OpenFOAM/interpolations/interpolationTable/tableReaders/csv/csvTableReader.C