OpenFOAM: wallBoundedStreamLine Class Reference
wallBoundedStreamLine Class Reference
FunctionObjects » Field function objects
Generates streamline data by sampling a set of user-specified fields along a particle track, transported by a user-specified velocity field, constrained to a patch.
#include <wallBoundedStreamLine.H>
Public Member Functions
TypeName ("wallBoundedStreamLine")
wallBoundedStreamLine (const word &name, const Time &runTime, const dictionary &dict)
wallBoundedStreamLine (const word &name, const Time &runTime, const dictionary &dict, const wordList &fieldNames)
wallBoundedStreamLine (const wallBoundedStreamLine &)=delete
void operator= (const wallBoundedStreamLine &)=delete
virtual ~wallBoundedStreamLine ()=default
virtual bool read (const dictionary &)
virtual void track ()
Public Member Functions inherited from streamLineBase
TypeName ("streamLineBase")
streamLineBase (const word &name, const Time &runTime, const dictionary &dict)
streamLineBase (const word &name, const Time &runTime, const dictionary &dict, const wordList &fieldNames)
virtual ~streamLineBase ()
virtual bool execute ()
virtual bool write ()
virtual void updateMesh (const mapPolyMesh &)
virtual void movePoints (const polyMesh &)
Public Member Functions inherited from fvMeshFunctionObject
TypeName ("fvMeshFunctionObject")
fvMeshFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
fvMeshFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
virtual ~fvMeshFunctionObject ()=default
Public Member Functions inherited from regionFunctionObject
TypeName ("regionFunctionObject")
regionFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
regionFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
virtual ~regionFunctionObject ()=default
template<class ObjectType >
const ObjectType * lookupObjectPtr (const word &fieldName) const
template<class ObjectType >
ObjectType * lookupObjectRefPtr (const word &fieldName) const
Public Member Functions inherited from stateFunctionObject
stateFunctionObject (const word &name, const Time &runTime)
virtual ~stateFunctionObject ()=default
dictionary & propertyDict ()
bool foundProperty (const word &entryName) const
void clearTrigger ()
label getTrigger () const
bool setTrigger (const label triggeri)
bool getDict (const word &entryName, dictionary &dict) const
bool getObjectDict (const word &objectName, const word &entryName, dictionary &dict) const
template<class Type >
Type getProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getProperty (const word &entryName, Type &value) const
template<class Type >
void setProperty (const word &entryName, const Type &value)
template<class Type >
Type getObjectProperty (const word &objectName, const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getObjectProperty (const word &objectName, const word &entryName, Type &value) const
template<class Type >
void setObjectProperty (const word &objectName, const word &entryName, const Type &value)
template<class Type >
void setResult (const word &entryName, const Type &value)
template<class Type >
void setObjectResult (const word &objectName, const word &entryName, const Type &value)
template<class Type >
Type getResult (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
Type getObjectResult (const word &objectName, const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getObjectResult (const word &objectName, const word &entryName, Type &value) const
word resultType (const word &entryName) const
word objectResultType (const word &objectName, const word &entryName) const
wordList objectResultEntries () const
wordList objectResultEntries (const word &objectName) const
void writeResultEntries (Ostream &os) const
void writeResultEntries (const word &objectName, Ostream &os) const
void writeAllResultEntries (Ostream &os) const
Public Member Functions inherited from timeFunctionObject
timeFunctionObject (const word &name, const Time &runTime)
virtual ~timeFunctionObject ()=default
const Time & time () const
objectRegistry & storedObjects ()
const objectRegistry & storedObjects () const
Public Member Functions inherited from functionObject
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name, const bool withNamePrefix=defaultUseNamePrefix)
autoPtr< functionObject > clone () const
virtual ~functionObject ()=default
virtual const word & type () const =0
const word & name () const noexcept
bool useNamePrefix () const noexcept
bool useNamePrefix (bool on) noexcept
virtual bool execute (const label subIndex)
virtual bool end ()
virtual bool adjustTimeStep ()
virtual bool filesModified () const
Protected Member Functions
Tuple2< tetIndices, point > findNearestTet (const bitSet &isWallPatch, const point &seedPt, const label celli) const
point pushIn (const triPointRef &tri, const point &pt) const
Protected Member Functions inherited from streamLineBase
const word & sampledSetAxis () const
const sampledSet & sampledSetPoints () const
autoPtr< indirectPrimitivePatch > wallPatch () const
refPtr< interpolation< vector > > initInterpolations (const label nSeeds, PtrList< interpolation< scalar > > &vsInterp, PtrList< interpolation< vector > > &vvInterp)
void storePoint (const label tracki, const scalar w, const label lefti, const label righti, DynamicList< point > &newTrack, DynamicList< List< scalar > > &newScalars, DynamicList< List< vector > > &newVectors) const
void trimToBox (const treeBoundBox &bb, const label tracki, PtrList< DynamicList< point > > &newTracks, PtrList< DynamicList< scalarList > > &newScalars, PtrList< DynamicList< vectorList > > &newVectors) const
void trimToBox (const treeBoundBox &bb)
virtual bool writeToFile ()
virtual void resetFieldNames (const word &newUName, const wordList &newFieldNames)
Protected Member Functions inherited from fvMeshFunctionObject
fvMeshFunctionObject (const fvMeshFunctionObject &)=delete
void operator= (const fvMeshFunctionObject &)=delete
Protected Member Functions inherited from regionFunctionObject
virtual const objectRegistry & obr () const
template<class ObjectType >
bool foundObject (const word &fieldName) const
template<class ObjectType >
const ObjectType * cfindObject (const word &fieldName) const
template<class ObjectType >
const ObjectType * findObject (const word &fieldName) const
template<class ObjectType >
ObjectType * findObject (const word &fieldName)
template<class ObjectType >
ObjectType * getObjectPtr (const word &fieldName) const
template<class ObjectType >
const ObjectType & lookupObject (const word &fieldName) const
template<class ObjectType >
ObjectType & lookupObjectRef (const word &fieldName) const
template<class ObjectType >
bool store (word &fieldName, const tmp< ObjectType > &tfield, bool cacheable=false)
template<class ObjectType >
bool storeInDb (const word &fieldName, const tmp< ObjectType > &tfield, const objectRegistry &obr)
bool writeObject (const word &fieldName)
bool clearObject (const word &fieldName)
void clearObjects (const wordList &objNames)
regionFunctionObject (const regionFunctionObject &)=delete
void operator= (const regionFunctionObject &)=delete
Protected Member Functions inherited from stateFunctionObject
const functionObjects::properties & stateDict () const
functionObjects::properties & stateDict ()
stateFunctionObject (const stateFunctionObject &)=delete
void operator= (const stateFunctionObject &)=delete
Protected Member Functions inherited from timeFunctionObject
void clearOutputObjects (const wordList &objNames)
timeFunctionObject (const timeFunctionObject &)=delete
void operator= (const timeFunctionObject &)=delete
Protected Member Functions inherited from functionObject
word scopedName (const word &name) const
Additional Inherited Members
Public Types inherited from streamLineBase
enum trackDirType : char { FORWARD , BACKWARD , BIDIRECTIONAL }
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &runTime, const dictionary &dict)
Public Attributes inherited from functionObject
bool log
Static Public Attributes inherited from streamLineBase
static const Enum< trackDirType > trackDirTypeNames
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
static bool defaultUseNamePrefix
static word outputPrefix
Protected Attributes inherited from streamLineBase
autoPtr< sampledSet > sampledSetPtr_
word sampledSetAxis_
dictionary dict_
wordList fields_
word UName_
word interpolationScheme_
trackDirType trackDir_
label lifeTime_
scalar trackLength_
boundBox bounds_
word cloudName_
word seedSet_
wordList scalarNames_
wordList vectorNames_
autoPtr< coordSetWriter > trackWriterPtr_
DynamicList< List< point > > allTracks_
List< DynamicList< scalarList > > allScalars_
List< DynamicList< vectorList > > allVectors_
Protected Attributes inherited from fvMeshFunctionObject
const fvMesh & mesh_
Protected Attributes inherited from regionFunctionObject
word subRegistryName_
const objectRegistry & obr_
const objectRegistry * obrPtr_
Protected Attributes inherited from timeFunctionObject
const Time & time_
Detailed Description
Generates streamline data by sampling a set of user-specified fields along a particle track, transported by a user-specified velocity field, constrained to a patch.
Operands:
Operand Type Location
input - -
output file - $FOAM_CASE/postProcessing/<FO>/<time>/<file>
output field - -
Usage
Minimal example by using system/controlDict.functions:
wallBoundedStreamLine1
{
    // Mandatory entries (unmodifiable)
    type            wallBoundedStreamLine;
    libs            (fieldFunctionObjects);
    // Optional entries
    U               <velocity-name>;
    direction       forward;
    cloud           particleTracks;
    // Mandatory entries (runtime modifiable)
    fields          (<field1> ... <fieldN>);
    setFormat       vtk;
    lifeTime        10000;
    seedSampleSet
    {
        type        patchSeed;
        patches     (wall);
        axis        x;
        maxPoints   20000;
    }
    // Optional entries (runtime modifiable)
    bounds          (0.2 -10 -10)(0.22 10 10);
    trackLength     1e-3;
    nSubCycle       1;
    interpolationScheme cellPoint;
    // Deprecated
    // trackForward true;
    // Optional (inherited) entries
    ...
}
where the entries mean:
Property Description Type Req'd Dflt
type Type name: wallBoundedStreamLine word yes -
libs Library name: fieldFunctionObjects word yes -
U Name of tracking velocity field word yes -
fields Names of operand fields to sample wordList yes -
setFormat Type of output data word yes -
direction Direction (enum) to track word no forward
lifetime Maximum number of particle tracking steps label yes -
cloud Cloud name to use for streamlines word no typeName
seedSampleSet Seeding description (see below) dict yes -
bounds Bounding box to trim tracks vector pair no -
trackLength Tracking segment length scalar no VGREAT
nSubCycle Number of tracking steps per cell label no 1
interpolationScheme Interp. scheme for sample word no cellPoint
Example types for the seedSampleSet sub-dict:
      uniform   | uniform particle seeding
      cloud     | cloud of points
      patchSeed | seeding via patch faces
      triSurfaceMeshPointSet | points according to a tri-surface mesh
Options for the setFormat entry:
        csv
        ensight
        gnuplot
        nastran
        raw
        vtk
        xmgr
Options for the direction entry:
        forward
        backward
        bidirectional
The inherited entries are elaborated in:
functionObject.H
Usage by the postProcess utility is not available.
Note
When specifying the track resolution, the trackLength OR nSubCycle option should be used.
See also
Foam::functionObject
Foam::functionObjects::streamLineBase
ExtendedCodeGuide::functionObjects::field::wallBoundedStreamLine
Source files
wallBoundedStreamLine.H
wallBoundedStreamLine.C
Definition at line 260 of file wallBoundedStreamLine.H.
Constructor & Destructor Documentation
wallBoundedStreamLine() [1/3]
wallBoundedStreamLine (const word & name, const Time & runTime, const dictionary & dict)
Definition at line 263 of file wallBoundedStreamLine.C.
References streamLineBase::dict_, and wallBoundedStreamLine::read().
wallBoundedStreamLine() [2/3]
wallBoundedStreamLine (const word & name, const Time & runTime, const dictionary & dict, const wordList & fieldNames)
Definition at line 276 of file wallBoundedStreamLine.C.
References streamLineBase::dict_, and wallBoundedStreamLine::read().
wallBoundedStreamLine() [3/3]
wallBoundedStreamLine (const wallBoundedStreamLine &) delete
~wallBoundedStreamLine()
virtual ~wallBoundedStreamLine () virtual default
Member Function Documentation
findNearestTet()
Foam::Tuple2< Foam::tetIndices, Foam::point > findNearestTet (const bitSet & isWallPatch, const point & seedPt, const label celli) const protected
Definition at line 48 of file wallBoundedStreamLine.C.
References PointHit< PointType >::distance(), f(), fvMeshFunctionObject::mesh_, triangle< Point, PointRef >::nearestPoint(), PointHit< PointType >::point(), UPtrList< T >::size(), and Foam::sqr().
pushIn()
Foam::point pushIn (const triPointRef & tri, const point & pt) const protected
Definition at line 108 of file wallBoundedStreamLine.C.
References triangle< Point, PointRef >::centre().
TypeName()
TypeName ("wallBoundedStreamLine")
operator=()
void operator= (const wallBoundedStreamLine &) delete
read()
bool read (const dictionary & dict) virtual
Reimplemented from streamLineBase.
Definition at line 292 of file wallBoundedStreamLine.C.
References polyMeshTetDecomposition::checkFaceTets(), PtrList< T >::clear(), dict, e, Foam::endl(), f(), Foam::FatalError, FatalErrorInFunction, forAll, forAllConstIters, polyMeshTetDecomposition::minTetQuality, IOobject::name(), streamLineBase::read(), Foam::returnReduce(), HashTable< T, Key, Hash >::size(), and WarningInFunction.
Referenced by wallBoundedStreamLine::wallBoundedStreamLine(), and wallBoundedStreamLine::wallBoundedStreamLine().
track()
void track () virtual
Implements streamLineBase.
Definition at line 125 of file wallBoundedStreamLine.C.
References Foam::endl(), UPtrList< T >::first(), forAll, Log, Foam::Pout, Foam::returnReduce(), UPtrList< T >::size(), Foam::sqrt(), and Foam::type().
The documentation for this class was generated from the following files:
src/functionObjects/field/wallBoundedStreamLine/wallBoundedStreamLine.H
src/functionObjects/field/wallBoundedStreamLine/wallBoundedStreamLine.C