OpenFOAM: word Class Reference
word Class Reference
A class for handling words, derived from Foam::string.
#include <word.H>
Public Member Functions
word ()=default
word (const word &)=default
word (word &&w)=default
word (const string &s, bool doStrip=true)
word (string &&s, bool doStrip=true)
word (const std::string &s, bool doStrip=true)
word (std::string &&s, bool doStrip=true)
word (const char *s, bool doStrip=true)
word (const char *s, size_type len, bool doStrip)
word (Istream &is)
void stripInvalid ()
word ext () const
word & ext (const word &ending)
word & replace_ext (const word &ending)
word lessExt () const
word & operator= (const word &s)
word & operator= (word &&s)
word & operator= (const string &s)
word & operator= (string &&s)
word & operator= (const std::string &s)
word & operator= (std::string &&s)
word & operator= (const char *s)
bool hasExt () const
bool hasExt (const std::string &s) const
bool removeExt ()
template<class PrimitiveType >
Foam::word printf (const char *fmt, const PrimitiveType &val)
template<class PrimitiveType >
Foam::word printf (const std::string &fmt, const PrimitiveType &val)
bool remove_ext ()
bool has_ext () const
bool has_ext (const char *ending) const
bool has_ext (const std::string &ending) const
bool has_ext (const wordRe &ending) const
Public Member Functions inherited from string
string ()=default
string (const std::string &str)
string (std::string &&str)
string (const char *str)
string (const char *str, const size_type len)
string (const char c)
string (const size_type len, const char c)
string (Istream &is)
bool match (const std::string &text) const
string & replace (const std::string &s1, const std::string &s2, size_type pos=0)
string & replaceAll (const std::string &s1, const std::string &s2, size_type pos=0)
string & replaceAny (const std::string &s1, const char c2, size_type pos=0)
string & expand (const bool allowEmpty=false)
bool removeRepeated (const char character)
bool removeStart (const std::string &text)
bool removeStart (const char c)
bool removeEnd (const std::string &text)
bool removeEnd (const char c)
void swap (std::string &str)
bool operator() (const std::string &text) const
bool contains (char c) const noexcept
bool contains (const std::string &s) const noexcept
bool contains (const char *s) const
bool starts_with (char c) const
bool starts_with (const std::string &s) const
bool starts_with (const char *s) const
bool ends_with (char c) const
bool ends_with (const std::string &s) const
bool ends_with (const char *s) const
size_type count (const char c) const
bool startsWith (const std::string &s) const
bool endsWith (const std::string &s) const
bool removeTrailing (const char c)
Static Public Member Functions
template<class PrimitiveType >
static word printf (const char *fmt, const PrimitiveType &val)
template<class PrimitiveType >
static word printf (const std::string &fmt, const PrimitiveType &val)
static bool valid (char c)
static word validate (const std::string &s, const bool prefix=false)
static word validate (const char *first, const char *last, const bool prefix=false)
Static Public Member Functions inherited from string
template<class StringType >
static bool valid (const std::string &str)
template<class StringType >
static bool stripInvalid (std::string &str)
template<class StringType >
static StringType validate (const std::string &str)
Static Public Attributes
static const char *const typeName = "word"
static int debug
static const word null
Static Public Attributes inherited from string
static const char *const typeName = "string"
static int debug
static const string null
Additional Inherited Members
Protected Member Functions inherited from string
std::string::size_type find_ext () const
word ext () const
bool ext (const word &ending)
bool has_ext () const
bool has_ext (const char *ending) const
bool has_ext (const std::string &ending) const
bool has_ext (const wordRe &ending) const
bool remove_path ()
bool remove_ext ()
Static Protected Member Functions inherited from string
static std::string::size_type find_ext (const std::string &str)
template<class PrimitiveType >
static std::string::size_type string_printf (std::string &output, const char *fmt, const PrimitiveType &val)
template<class PrimitiveType >
static std::string::size_type string_printf (std::string &output, const std::string &fmt, const PrimitiveType &val)
Detailed Description
A class for handling words, derived from Foam::string.
A word is a string of characters without whitespace, quotes, slashes, semicolons or brace brackets. Words are delimited by whitespace.
Source files
word.H
wordI.H
word.C
wordIO.C
Definition at line 63 of file word.H.
Constructor & Destructor Documentation
word() [1/10]
word () default
word() [2/10]
word (const word &) default
word() [3/10]
word (word && w) default
word() [4/10]
word (const string & s, bool doStrip = true) inline
Definition at line 69 of file wordI.H.
References word::stripInvalid().
word() [5/10]
word (string && s, bool doStrip = true) inline
Definition at line 80 of file wordI.H.
References word::stripInvalid().
word() [6/10]
word (const std::string & s, bool doStrip = true) inline
Definition at line 102 of file wordI.H.
References word::stripInvalid().
word() [7/10]
word (std::string && s, bool doStrip = true) inline
Definition at line 91 of file wordI.H.
References word::stripInvalid().
word() [8/10]
word (const char * s, bool doStrip = true) inline
Definition at line 113 of file wordI.H.
References word::stripInvalid().
word() [9/10]
word (const char * s, size_type len, bool doStrip) inline
Definition at line 124 of file wordI.H.
References word::stripInvalid().
word() [10/10]
word (Istream & is) explicit
Definition at line 28 of file wordIO.C.
Member Function Documentation
printf() [1/4]
template<class PrimitiveType > static word printf (const char * fmt, const PrimitiveType & val) inline static
Referenced by isoSurfaceTopo::isoSurfaceTopo(), dataCloud::write(), vtkCloud::write(), vtkWrite::write(), ensightCase::write(), and isoAdvection::writeIsoFaces().
printf() [2/4]
template<class PrimitiveType > static word printf (const std::string & fmt, const PrimitiveType & val) inline static
valid()
bool valid (char c) inline static
Definition at line 52 of file wordI.H.
References Foam::isspace().
Referenced by ISstream::read(), ISstream::read(), VarName::valid(), keyType::valid(), wordRe::valid(), word::validate(), and word::validate().
validate() [1/2]
Foam::word validate (const std::string & s, const bool prefix = false) static
Definition at line 39 of file word.C.
References s(), and word::valid().
Referenced by exprDriver::addVariables(), dictionary::csearchCompat(), fvExprDriver::evaluateVariableRemote(), STLAsciiParseManual::execute(), IOobject::fileNameComponents(), Foam::getStopAction(), entry::New(), Foam::operator>>(), Foam::operator>>(), Foam::operator>>(), NASedgeFormat::read(), OBJedgeFormat::read(), functionObjectList::readFunctionObject(), STARCDsurfaceFormatCore::readInpCellTable(), FIREMeshReader::readSelections(), and ABAQUSCore::readHelper::readSurfaceElements().
validate() [2/2]
Foam::word validate (const char * first, const char * last, const bool prefix = false) static
Definition at line 71 of file word.C.
References word::valid().
stripInvalid()
void stripInvalid () inline
Definition at line 137 of file wordI.H.
Referenced by word::word(), word::word(), word::word(), word::word(), word::word(), and word::word().
ext() [1/2]
Foam::word ext () const inline
Definition at line 171 of file wordI.H.
References string::ext().
Referenced by edgeMesh::canRead(), extendedEdgeMesh::canRead(), MeshedSurface< Face >::canRead(), triSurface::canRead(), UnsortedMeshedSurface< Face >::canRead(), fileWriter::ext(), IOobject::group(), edgeMesh::New(), extendedEdgeMesh::New(), MeshedSurface< Face >::New(), triSurface::New(), UnsortedMeshedSurface< Face >::New(), triSurface::New(), MeshedSurface< Face >::New(), UnsortedMeshedSurface< Face >::New(), edgeMesh::read(), extendedEdgeMesh::read(), coordSetWriter::suffix(), coordSetWriter::suffix(), triSurface::write(), triSurface::write(), edgeMesh::write(), MeshedSurface< Face >::write(), MeshedSurfaceProxy< Face >::write(), UnsortedMeshedSurface< Face >::write(), MeshedSurface< Face >::write(), MeshedSurfaceProxy< Face >::write(), UnsortedMeshedSurface< Face >::write(), and surfMesh::write().
ext() [2/2]
Foam::word & ext (const word & ending) inline
Definition at line 177 of file wordI.H.
References string::ext().
replace_ext()
Foam::word & replace_ext (const word & ending) inline
Definition at line 184 of file wordI.H.
References string::ext(), and string::remove_ext().
lessExt()
Foam::word lessExt () const inline
Definition at line 192 of file wordI.H.
Referenced by IOobject::member(), MeshedSurface< Face >::New(), triSurface::New(), UnsortedMeshedSurface< Face >::New(), triSurface::New(), MeshedSurface< Face >::New(), UnsortedMeshedSurface< Face >::New(), edgeMesh::read(), and extendedEdgeMesh::read().
operator=() [1/7]
Foam::word & operator= (const word & s) inline
Definition at line 207 of file wordI.H.
References s().
operator=() [2/7]
Foam::word & operator= (word && s) inline
Definition at line 218 of file wordI.H.
References s().
operator=() [3/7]
Foam::word & operator= (const string & s) inline
Definition at line 229 of file wordI.H.
References s().
operator=() [4/7]
Foam::word & operator= (string && s) inline
Definition at line 237 of file wordI.H.
References s().
operator=() [5/7]
Foam::word & operator= (const std::string & s) inline
Definition at line 245 of file wordI.H.
References s().
operator=() [6/7]
Foam::word & operator= (std::string && s) inline
Definition at line 253 of file wordI.H.
References s().
operator=() [7/7]
Foam::word & operator= (const char * s) inline
Definition at line 261 of file wordI.H.
References s().
hasExt() [1/2]
bool hasExt () const inline
Definition at line 213 of file word.H.
References word::has_ext().
hasExt() [2/2]
bool hasExt (const std::string & s) const inline
Definition at line 216 of file word.H.
References word::has_ext(), and s().
removeExt()
bool removeExt () inline
Definition at line 219 of file word.H.
References word::remove_ext().
printf() [3/4]
template<class PrimitiveType > Foam::word printf (const char * fmt, const PrimitiveType & val) inline
Definition at line 27 of file wordI.H.
References Foam::output(), and string::string_printf().
printf() [4/4]
template<class PrimitiveType > Foam::word printf (const std::string & fmt, const PrimitiveType & val) inline
Definition at line 40 of file wordI.H.
References Foam::output().
remove_ext()
bool remove_ext () inline
Definition at line 133 of file stringI.H.
Referenced by Foam::readDir(), and word::removeExt().
has_ext() [1/4]
bool has_ext () const inline
Definition at line 117 of file stringI.H.
Referenced by edgeMesh::canRead(), extendedEdgeMesh::canRead(), MeshedSurface< Face >::canRead(), triSurface::canRead(), UnsortedMeshedSurface< Face >::canRead(), word::hasExt(), word::hasExt(), edgeMesh::New(), extendedEdgeMesh::New(), MeshedSurface< Face >::New(), triSurface::New(), UnsortedMeshedSurface< Face >::New(), edgeMesh::read(), extendedEdgeMesh::read(), and Foam::readDir().
has_ext() [2/4]
bool has_ext (const char * ending) const inline
Definition at line 121 of file stringI.H.
has_ext() [3/4]
bool has_ext (const std::string & ending) const inline
Definition at line 124 of file stringI.H.
has_ext() [4/4]
bool has_ext (const wordRe & ending) const
Definition at line 127 of file string.C.
Member Data Documentation
typeName
const char *const typeName = "word" static
Definition at line 72 of file word.H.
debug
int debug static
Definition at line 75 of file word.H.
Referenced by keyType::setType(), keyType::uncompile(), and wordRe::uncompile().
null
const Foam::word null static
Definition at line 78 of file word.H.
Referenced by surfaceZonesInfo::addCellZonesToMesh(), refinementParameters::addCellZonesToMesh(), FIREMeshReader::addPatches(), vtmWriter::append(), vtmWriter::append(), minMaxCondition::apply(), interfaceEntry::canonicalName(), surfaceFormatsCore::checkFile(), surfaceFormatsCore::checkFile(), fluxSummary::checkFlowType(), externalCoupled::compositeName(), pointPatchFieldBase::constraintType(), pointPatch::constraintType(), Foam::createZeroBoundaryPtr(), cyclicAMIPolyPatch::cyclicAMIPolyPatch(), cyclicPolyPatch::cyclicPolyPatch(), STLAsciiParseManual::execute(), masterUncollatedFileOperation::exists(), fileOperation::exists(), faMesh::faMesh(), fvExpressionField::fieldName(), Foam::filteredName(), surfaceFormatsCore::findFile(), surfaceFormatsCore::findFile(), boundaryRegion::findIndex(), cellTable::findIndex(), Time::findInstancePath(), topoSet::findIOobject(), topoSet::findIOobject(), fvExprDriver::getFieldClassName(), sizeDistribution::initialise(), Foam::interpolate(), CloudSubModelBase< CloudType >::localPath(), subModelBase::localPath(), polyTopoChange::makeMesh(), moleFractions< ThermoType >::moleFractions(), displacementMotionSolverMeshMover::move(), faPatchField< Type >::New(), faePatchField< Type >::New(), fvsPatchField< Type >::New(), fvPatchField< Type >::New(), pointPatchField< Type >::New(), Function1< Type >::New(), basicSolidChemistryModel::New(), combustionModel::New(), Function1< Type >::NewIfPresent(), Function1< scalar >::NewIfPresent(), collatedFileOperation::objectPath(), properties::objectResultType(), orderedPhasePair::otherName(), outletMappedUniformInletFvPatchField< Type >::outletMappedUniformInletFvPatchField(), cyclicAMIPolyPatch::periodicPatchID(), decomposedBlockData::read(), norm::read(), BilgerMixtureFraction::read(), MRFZone::read(), regionFunctionObject::read(), rigidBodyMotion::read(), sampledSurfaces::read(), moleFractions< ThermoType >::read(), reference::reference(), refinementParameters::refinementParameters(), polyMesh::regionName(), surfaceFormatsCore::relativeFilePath(), sampledPatchInternalField::sampledPatchInternalField(), sizeDistribution::setCellZoneCells(), sensitivitySurface::setSuffixName(), sensitivitySurfacePoints::setSuffixName(), StandardChemistryModel< ReactionThermo, ThermoType >::tc(), DelaunayMesh< Triangulation >::timeCheck(), triSurface::triSurface(), triSurfaceMesh::triSurfaceMesh(), nutWallFunctionFvPatchScalarField::U(), UnsortedMeshedSurface< Face >::UnsortedMeshedSurface(), refinementParameters::unzonedLocations(), token::wordToken(), multiFieldValue::write(), mappedMixedFieldFvPatchField< Type >::write(), mappedMixedFvPatchField< Type >::write(), surfaceDisplacementPointPatchVectorField::write(), surfaceSlipDisplacementPointPatchVectorField::write(), cyclicAMIPolyPatch::write(), mappedPatchBase::write(), nutWallFunctionFvPatchScalarField::writeLocalEntries(), Foam::writeMeshObject(), NURBS3DSurface::writeVTK(), and refinementParameters::zonedLocations().
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/strings/word/word.H
src/OpenFOAM/primitives/strings/word/word.C
src/OpenFOAM/primitives/strings/word/wordI.H
src/OpenFOAM/primitives/strings/word/wordIO.C