OpenFOAM: outletPhaseMeanVelocityFvPatchVectorField Class Reference
outletPhaseMeanVelocityFvPatchVectorField Class Reference
Boundary conditions » Outlet
This boundary condition adjusts the velocity for the given phase to achieve the specified mean thus causing the phase-fraction to adjust according to the mass flow rate.
#include <outletPhaseMeanVelocityFvPatchVectorField.H>
Public Member Functions
TypeName ("outletPhaseMeanVelocity")
outletPhaseMeanVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
outletPhaseMeanVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
outletPhaseMeanVelocityFvPatchVectorField (const outletPhaseMeanVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
outletPhaseMeanVelocityFvPatchVectorField (const outletPhaseMeanVelocityFvPatchVectorField &)
virtual tmp< fvPatchVectorField > clone () const
outletPhaseMeanVelocityFvPatchVectorField (const outletPhaseMeanVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
scalar Umean () const
scalar & Umean ()
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
This boundary condition adjusts the velocity for the given phase to achieve the specified mean thus causing the phase-fraction to adjust according to the mass flow rate.
Typical usage is as the outlet condition for a towing-tank ship simulation to maintain the outlet water level at the level as the inlet.
Usage
Property Description Required Default value
Umean mean velocity normal to the boundary [m/s] yes
alpha phase-fraction field yes
Example of the boundary condition specification:
    <patchName>
    {
        type            outletPhaseMeanVelocity;
        Umean           1.2;
        alpha           alpha.water;
        value           uniform (1.2 0 0);
    }
See also
Foam::mixedFvPatchField Foam::variableHeightFlowRateInletVelocityFvPatchVectorField
Source files
outletPhaseMeanVelocityFvPatchVectorField.H
outletPhaseMeanVelocityFvPatchVectorField.C
Definition at line 90 of file outletPhaseMeanVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
outletPhaseMeanVelocityFvPatchVectorField() [1/5]
outletPhaseMeanVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Definition at line 30 of file outletPhaseMeanVelocityFvPatchVectorField.C.
References Foam::Zero.
outletPhaseMeanVelocityFvPatchVectorField() [2/5]
outletPhaseMeanVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Definition at line 62 of file outletPhaseMeanVelocityFvPatchVectorField.C.
References dict, fvPatchFieldBase::readDict(), and Foam::Zero.
outletPhaseMeanVelocityFvPatchVectorField() [3/5]
outletPhaseMeanVelocityFvPatchVectorField (const outletPhaseMeanVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 47 of file outletPhaseMeanVelocityFvPatchVectorField.C.
outletPhaseMeanVelocityFvPatchVectorField() [4/5]
outletPhaseMeanVelocityFvPatchVectorField (const outletPhaseMeanVelocityFvPatchVectorField & ptf)
Definition at line 87 of file outletPhaseMeanVelocityFvPatchVectorField.C.
outletPhaseMeanVelocityFvPatchVectorField() [5/5]
outletPhaseMeanVelocityFvPatchVectorField (const outletPhaseMeanVelocityFvPatchVectorField & ptf, const DimensionedField< vector, volMesh > & iF)
Definition at line 99 of file outletPhaseMeanVelocityFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("outletPhaseMeanVelocity")
clone() [1/2]
virtual tmp< fvPatchVectorField > clone () const inline virtual
Definition at line 144 of file outletPhaseMeanVelocityFvPatchVectorField.H.
clone() [2/2]
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Definition at line 160 of file outletPhaseMeanVelocityFvPatchVectorField.H.
Umean() [1/2]
scalar Umean () const inline
Definition at line 181 of file outletPhaseMeanVelocityFvPatchVectorField.H.
Umean() [2/2]
scalar & Umean () inline
Definition at line 187 of file outletPhaseMeanVelocityFvPatchVectorField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 114 of file outletPhaseMeanVelocityFvPatchVectorField.C.
References Foam::gSum(), Foam::max(), Foam::min(), fvPatchField< Type >::updateCoeffs(), and Foam::Zero.
write()
void write (Ostream & os) const virtual
Definition at line 154 of file outletPhaseMeanVelocityFvPatchVectorField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntry(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/outletPhaseMeanVelocity/outletPhaseMeanVelocityFvPatchVectorField.H
src/finiteVolume/fields/fvPatchFields/derived/outletPhaseMeanVelocity/outletPhaseMeanVelocityFvPatchVectorField.C