OpenFOAM: wideBandDiffusiveRadiationMixedFvPatchScalarField Class Reference
wideBandDiffusiveRadiationMixedFvPatchScalarField Class Reference
Boundary conditions » Thermophysical
This boundary condition provides a wide-band, diffusive radiation condition, where the patch temperature is specified.
#include <wideBandDiffusiveRadiationMixedFvPatchScalarField.H>
Public Member Functions
TypeName ("wideBandDiffusiveRadiation")
wideBandDiffusiveRadiationMixedFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
wideBandDiffusiveRadiationMixedFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
wideBandDiffusiveRadiationMixedFvPatchScalarField (const wideBandDiffusiveRadiationMixedFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
wideBandDiffusiveRadiationMixedFvPatchScalarField (const wideBandDiffusiveRadiationMixedFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
wideBandDiffusiveRadiationMixedFvPatchScalarField (const wideBandDiffusiveRadiationMixedFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
This boundary condition provides a wide-band, diffusive radiation condition, where the patch temperature is specified.
Usage
Property Description Required Default value
T temperature field name no T
Example of the boundary condition specification:
    <patchName>
    {
        type            wideBandDiffusiveRadiation;
        value           uniform 0;
    }
See also
Foam::mixedFvPatchScalarField Foam::radiationCoupledBase
Source files
wideBandDiffusiveRadiationMixedFvPatchScalarField.H
wideBandDiffusiveRadiationMixedFvPatchScalarField.C
Definition at line 81 of file wideBandDiffusiveRadiationMixedFvPatchScalarField.H.
Constructor & Destructor Documentation
wideBandDiffusiveRadiationMixedFvPatchScalarField() [1/5]
wideBandDiffusiveRadiationMixedFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 37 of file wideBandDiffusiveRadiationMixedFvPatchScalarField.C.
References Foam::Zero.
wideBandDiffusiveRadiationMixedFvPatchScalarField() [2/5]
wideBandDiffusiveRadiationMixedFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 65 of file wideBandDiffusiveRadiationMixedFvPatchScalarField.C.
References dict, IOobjectOption::MUST_READ, fvPatchField< scalar >::operator=(), and Foam::Zero.
wideBandDiffusiveRadiationMixedFvPatchScalarField() [3/5]
wideBandDiffusiveRadiationMixedFvPatchScalarField (const wideBandDiffusiveRadiationMixedFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 52 of file wideBandDiffusiveRadiationMixedFvPatchScalarField.C.
wideBandDiffusiveRadiationMixedFvPatchScalarField() [4/5]
wideBandDiffusiveRadiationMixedFvPatchScalarField (const wideBandDiffusiveRadiationMixedFvPatchScalarField & ptf)
Definition at line 91 of file wideBandDiffusiveRadiationMixedFvPatchScalarField.C.
wideBandDiffusiveRadiationMixedFvPatchScalarField() [5/5]
wideBandDiffusiveRadiationMixedFvPatchScalarField (const wideBandDiffusiveRadiationMixedFvPatchScalarField & ptf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 101 of file wideBandDiffusiveRadiationMixedFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("wideBandDiffusiveRadiation")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 125 of file wideBandDiffusiveRadiationMixedFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 141 of file wideBandDiffusiveRadiationMixedFvPatchScalarField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 114 of file wideBandDiffusiveRadiationMixedFvPatchScalarField.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), radiativeIntensityRay::dAve(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::mag(), mesh, UPstream::msgType(), n, Foam::name(), MeshObject< fvMesh, Foam::GeometricMeshObject, boundaryRadiationProperties >::New(), Foam::nl, Foam::constant::mathematical::pi(), radiativeIntensityRay::qem(), radiativeIntensityRay::qin(), radiativeIntensityRay::qr(), radiation(), and Foam::Zero.
write()
void write (Ostream & os) const virtual
Definition at line 291 of file wideBandDiffusiveRadiationMixedFvPatchScalarField.C.
References os(), and mixedFvPatchField< Type >::write().
The documentation for this class was generated from the following files:
src/thermophysicalModels/radiation/derivedFvPatchFields/wideBandDiffusiveRadiation/wideBandDiffusiveRadiationMixedFvPatchScalarField.H
src/thermophysicalModels/radiation/derivedFvPatchFields/wideBandDiffusiveRadiation/wideBandDiffusiveRadiationMixedFvPatchScalarField.C