OpenFOAM: abort Class Reference
abort Class Reference
FunctionObjects » Utility function objects
Watches for presence of the named trigger file in the case directory and signals a simulation stop (or other) event if found.
#include <abort.H>
Public Member Functions
TypeName ("abort")
abort (const word &name, const Time &runTime, const dictionary &dict)
virtual ~abort ()=default
virtual bool read (const dictionary &dict)
virtual bool execute ()
virtual bool write ()
virtual bool end ()
Public Member Functions inherited from timeFunctionObject
timeFunctionObject (const word &name, const Time &runTime)
virtual ~timeFunctionObject ()=default
const Time & time () const
objectRegistry & storedObjects ()
const objectRegistry & storedObjects () const
Public Member Functions inherited from functionObject
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name, const bool withNamePrefix=defaultUseNamePrefix)
autoPtr< functionObject > clone () const
virtual ~functionObject ()=default
virtual const word & type () const =0
const word & name () const noexcept
bool useNamePrefix () const noexcept
bool useNamePrefix (bool on) noexcept
virtual bool execute (const label subIndex)
virtual bool adjustTimeStep ()
virtual bool filesModified () const
virtual void updateMesh (const mapPolyMesh &mpm)
virtual void movePoints (const polyMesh &mesh)
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &runTime, const dictionary &dict)
Public Attributes inherited from functionObject
bool log
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
static bool defaultUseNamePrefix
static word outputPrefix
Protected Member Functions inherited from timeFunctionObject
void clearOutputObjects (const wordList &objNames)
timeFunctionObject (const timeFunctionObject &)=delete
void operator= (const timeFunctionObject &)=delete
Protected Member Functions inherited from functionObject
word scopedName (const word &name) const
Protected Attributes inherited from timeFunctionObject
const Time & time_
Detailed Description
Watches for presence of the named trigger file in the case directory and signals a simulation stop (or other) event if found.
The presence of the trigger file is only checked on the master process.
Currently the following action types are supported:
noWriteNow
writeNow
nextWrite
Example of function object specification:
abort
{
    type    abort;
    libs    (utilityFunctionObjects);
    file    "<case>/GOODBYE";
    action  writeNow
}
Function object usage
Property Description Required Default
type Type name: abort yes
file The trigger filename no <case>/name
action The default action to trigger no nextWrite
When the trigger file is found, it is checked for the following content which corresponds to actions.
action=noWriteNow : triggers Foam::Time::saNoWriteNow (stop without writing data)
action=writeNow : triggers Foam::Time::saWriteNow (stop and write data)
action=nextWrite : triggers Foam::Time::saNextWrite (stop after next normal data write)
action=endTime : triggers Foam::Time::saEndTime (continue simulation to the end)
Anything else (empty file, no action=, ...) : use the default action
Note
The trigger file is considered "sticky". This means that once detected and processed, the trigger is duly noted and the file will not be rechecked. It is not possible or desirable to 'untrigger' an action.
Source files
abort.H
abort.C
Definition at line 121 of file abort.H.
Constructor & Destructor Documentation
abort()
abort (const word & name, const Time & runTime, const dictionary & dict)
Definition at line 130 of file abort.C.
References dict, UPstream::master(), Foam::name(), abort::read(), and Foam::rm().
~abort()
virtual ~abort () virtual default
Member Function Documentation
TypeName()
TypeName ("abort")
read()
bool read (const dictionary & dict) virtual
Reimplemented from functionObject.
Definition at line 154 of file abort.C.
References dict, Foam::endl(), Foam::Info, Foam::longDescription(), Foam::name(), Foam::nl, functionObject::read(), Time::saNextWrite, Time::stopAtControlNames, and Foam::type().
Referenced by abort::abort().
execute()
bool execute () virtual
Implements functionObject.
Definition at line 194 of file abort.C.
References Pstream::broadcast(), Foam::endl(), Foam::getStopAction(), Foam::Info, Foam::isFile(), Foam::longDescription(), UPstream::master(), and Time::saUnknown.
write()
bool write () virtual
Implements functionObject.
Definition at line 235 of file abort.C.
end()
bool end () virtual
Reimplemented from functionObject.
Definition at line 241 of file abort.C.
References UPstream::master(), and Foam::rm().
The documentation for this class was generated from the following files:
src/functionObjects/utilities/abort/abort.H
src/functionObjects/utilities/abort/abort.C