OpenFOAM: conjugateGradient Class Reference
conjugateGradient Class Reference
The Conjugate Gradient formula.
#include <conjugateGradient.H>
Public Member Functions
TypeName ("conjugateGradient")
conjugateGradient (const fvMesh &mesh, const dictionary &dict)
virtual ~conjugateGradient ()=default
void computeCorrection ()
virtual void updateOldCorrection (const scalarField &oldCorrection)
virtual void write ()
Public Member Functions inherited from updateMethod
TypeName ("updateMethod")
declareRunTimeSelectionTable (autoPtr, updateMethod, dictionary,(const fvMesh &mesh, const dictionary &dict),(mesh, dict))
updateMethod (const fvMesh &mesh, const dictionary &dict)
virtual ~updateMethod ()=default
void setObjectiveDeriv (const scalarField &derivs)
void setConstraintDeriv (const PtrList< scalarField > &derivs)
void setObjectiveValue (const scalar value)
void setConstraintValues (const scalarField &values)
void setStep (const scalar eta)
void setGlobalSum (const bool useGlobalSum)
scalarField & returnCorrection ()
void writeCorrection ()
virtual scalar computeMeritFunction ()
virtual scalar meritFunctionDirectionalDerivative ()
bool & initialEtaSet ()
Protected Member Functions
void allocateFields ()
void readFromDict ()
Protected Member Functions inherited from updateMethod
const scalarField leftMult (const scalarField &, const SquareMatrix< scalar > &)
const scalarField rightMult (const SquareMatrix< scalar > &, const scalarField &)
SquareMatrix< scalar > outerProd (const scalarField &, const scalarField &)
SquareMatrix< scalar > inv (SquareMatrix< scalar > A)
scalar globalSum (const scalarField &field)
scalar globalSum (tmp< scalarField > &tfield)
dictionary coeffsDict ()
Protected Attributes
labelList activeDesignVars_
scalarField dxOld_
scalarField sOld_
label counter_
word betaType_
Protected Attributes inherited from updateMethod
const fvMesh & mesh_
const dictionary dict_
IOdictionary optMethodIODict_
scalarField objectiveDerivatives_
PtrList< scalarField > constraintDerivatives_
scalar objectiveValue_
scalarField cValues_
scalarField correction_
scalarField cumulativeCorrection_
scalar eta_
bool initialEtaSet_
word correctionFolder_
bool globalSum_
Additional Inherited Members
Static Public Member Functions inherited from updateMethod
static autoPtr< updateMethod > New (const fvMesh &mesh, const dictionary &dict)
Detailed Description
The Conjugate Gradient formula.
Beta computed from Fletcher-Reeves or Polak-Ribiere approaches. Polak-Ribiere seems to misbehave. Not tested with line search.
Source files
conjugateGradient.H
conjugateGradient.C
Definition at line 53 of file conjugateGradient.H.
Constructor & Destructor Documentation
conjugateGradient()
conjugateGradient (const fvMesh & mesh, const dictionary & dict)
Definition at line 78 of file conjugateGradient.C.
References conjugateGradient::activeDesignVars_, conjugateGradient::betaType_, updateMethod::coeffsDict(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::Info, Foam::nl, conjugateGradient::readFromDict(), and readIfPresent().
~conjugateGradient()
virtual ~conjugateGradient () virtual default
Member Function Documentation
allocateFields()
void allocateFields () protected
Definition at line 42 of file conjugateGradient.C.
References conjugateGradient::activeDesignVars_, conjugateGradient::dxOld_, UList< T >::empty(), Foam::identity(), updateMethod::objectiveDerivatives_, UList< T >::size(), conjugateGradient::sOld_, and Foam::Zero.
readFromDict()
void readFromDict () protected
Definition at line 56 of file conjugateGradient.C.
References UPtrList< T >::get(), Foam::identity(), and Foam::Zero.
Referenced by conjugateGradient::conjugateGradient().
TypeName()
TypeName ("conjugateGradient")
computeCorrection()
void computeCorrection () virtual
Implements updateMethod.
Definition at line 128 of file conjugateGradient.C.
References beta(), Foam::endl(), forAll, Foam::Info, Field< Type >::map(), Foam::max(), s(), and Foam::Zero.
updateOldCorrection()
void updateOldCorrection (const scalarField & oldCorrection) virtual
Reimplemented from updateMethod.
Definition at line 185 of file conjugateGradient.C.
write()
void write () virtual
Reimplemented from updateMethod.
Definition at line 196 of file conjugateGradient.C.
References updateMethod::write().
Member Data Documentation
activeDesignVars_
labelList activeDesignVars_ protected
Definition at line 61 of file conjugateGradient.H.
Referenced by conjugateGradient::allocateFields(), and conjugateGradient::conjugateGradient().
dxOld_
scalarField dxOld_ protected
Definition at line 62 of file conjugateGradient.H.
Referenced by conjugateGradient::allocateFields().
sOld_
scalarField sOld_ protected
Definition at line 63 of file conjugateGradient.H.
Referenced by conjugateGradient::allocateFields().
counter_
label counter_ protected
Definition at line 64 of file conjugateGradient.H.
betaType_
word betaType_ protected
Definition at line 65 of file conjugateGradient.H.
Referenced by conjugateGradient::conjugateGradient().
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/optimisation/updateMethod/conjugateGradient/conjugateGradient.H
src/optimisation/adjointOptimisation/adjoint/optimisation/updateMethod/conjugateGradient/conjugateGradient.C