OpenFOAM: weightedFlux< Type > Class Template Reference
weightedFlux< Type > Class Template Reference
Weighted flux interpolation scheme class.
#include <weightedFlux.H>
Public Member Functions
TypeName ("weightedFlux")
weightedFlux (const fvMesh &mesh, Istream &is)
weightedFlux (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &is)
virtual ~weightedFlux ()
tmp< surfaceScalarField > weights (const GeometricField< Type, fvPatchField, volMesh > &) const
const surfaceScalarField & oDelta () const
const surfaceScalarField & nDelta () const
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &vf) const
Public Member Functions inherited from surfaceInterpolationScheme< Type >
TypeName ("surfaceInterpolationScheme")
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, Mesh,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, MeshFlux,(const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
surfaceInterpolationScheme (const fvMesh &mesh)
virtual ~surfaceInterpolationScheme ()=default
const fvMesh & mesh () const
virtual bool corrected () const
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > &) const
virtual tmp< GeometricField< typename innerProduct< vector, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf) const
tmp< GeometricField< typename innerProduct< vector, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const tmp< GeometricField< Type, fvPatchField, volMesh > > &) const
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > &) const
template<class SFType >
Foam::tmp< Foam::GeometricField< typename Foam::innerProduct< typename SFType::value_type, Type >::type, Foam::fvsPatchField, Foam::surfaceMesh > > dotInterpolate (const SFType &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf, const tmp< surfaceScalarField > &tlambdas)
tmp< GeometricField< typename innerProduct< vector, scalar >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const GeometricField< scalar, fvPatchField, volMesh > &) const
Foam::tmp< Foam::GeometricField< typename Foam::innerProduct< Foam::vector, Foam::scalar >::type, Foam::fvsPatchField, Foam::surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const GeometricField< scalar, fvPatchField, volMesh > &) const
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Protected Member Functions
void clearOut ()
Additional Inherited Members
Static Public Member Functions inherited from surfaceInterpolationScheme< Type >
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData)
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &, const tmp< surfaceScalarField > &)
template<class SFType >
static tmp< GeometricField< typename innerProduct< typename SFType::value_type, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const SFType &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf, const tmp< surfaceScalarField > &tlambdas)
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &)
Detailed Description
template<class Type>
class Foam::weightedFlux< Type >
Weighted flux interpolation scheme class.
This scheme is used to compute fluxes with variable diffusivity or conductivity, as e.g.
a thermal flux: lambda*grad(T)
a mass flux: D*grad(u)
an electric current: -sigma*grad(potential)
When using the Gauss theorem to compute a gradient, cell centred values need to be interpolated to the faces. Using this scheme, temperature (T) is weighted by thermal conductivity when being interpolated. Similarly, velocity is weighted by diffusivity (D) and the electric potential by the electric conductivity (sigma). Lambda, D or sigma are read from the object registry - the names need to be specified in fvSchemes as e.g.
    gradSchemes
    {
        grad(T)             Gauss weightedFlux lambda;
        grad(u)             Gauss weightedFlux D;
        grad(potential)     Gauss weightedFlux sigma;
    }
For more details, see equation 16 and 17 in
    Weber, N., Beckstein, P., Galindo, V., Starace, M. & Weier, T. (2018).
    Electro-vortex flow simulation using coupled meshes.
    Computers and Fluids 168, 101-109.
    doi:10.1016/j.compfluid.2018.03.047
    https://arxiv.org/pdf/1707.06546.pdf
Note
For support, contact Norbe.nosp@m.rt.W.nosp@m.eber@.nosp@m.hzdr.nosp@m..de
Source files
weightedFlux.H
weightedFlux.C
Definition at line 82 of file weightedFlux.H.
Constructor & Destructor Documentation
weightedFlux() [1/2]
template<class Type > weightedFlux (const fvMesh & mesh, Istream & is) inline
Definition at line 130 of file weightedFlux.H.
weightedFlux() [2/2]
template<class Type > weightedFlux (const fvMesh & mesh, const surfaceScalarField & faceFlux, Istream & is) inline
Definition at line 144 of file weightedFlux.H.
~weightedFlux()
template<class Type > ~weightedFlux () virtual
Definition at line 37 of file weightedFlux.C.
Member Function Documentation
clearOut()
template<class Type > void clearOut () protected
Definition at line 27 of file weightedFlux.C.
References Foam::deleteDemandDrivenData().
TypeName()
template<class Type > TypeName ("weightedFlux< Type >")
weights()
template<class Type > tmp< surfaceScalarField > weights (const GeometricField< Type, fvPatchField, volMesh > &) const inline virtual
Implements surfaceInterpolationScheme< Type >.
Definition at line 166 of file weightedFlux.H.
References surfaceInterpolationScheme< Type >::mesh().
oDelta()
template<class Type > const surfaceScalarField & oDelta () const inline
Definition at line 175 of file weightedFlux.H.
Referenced by weightedFlux< Type >::interpolate().
nDelta()
template<class Type > const surfaceScalarField & nDelta () const inline
Definition at line 186 of file weightedFlux.H.
Referenced by weightedFlux< Type >::interpolate().
interpolate()
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > & vf) const virtual
Reimplemented from surfaceInterpolationScheme< Type >.
Definition at line 146 of file weightedFlux.C.
References fvMesh::boundary(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), forAll, mesh, weightedFlux< Type >::nDelta(), fvMesh::neighbour(), Foam::New(), weightedFlux< Type >::oDelta(), fvMesh::owner(), and fvMesh::time().
The documentation for this class was generated from the following files:
src/finiteVolume/interpolation/surfaceInterpolation/schemes/weightedFlux/weightedFlux.H
src/finiteVolume/interpolation/surfaceInterpolation/schemes/weightedFlux/weightedFlux.C