OpenFOAM: displacementMotionSolverMeshMover Class Reference
displacementMotionSolverMeshMover Class Reference
Quality-based under-relaxation wrapped around generic displacementMotionSolver.
#include <displacementMotionSolverMeshMover.H>
Public Member Functions
TypeName ("displacementMotionSolver")
displacementMotionSolverMeshMover (const dictionary &dict, const List< labelPair > &baffles, pointVectorField &pointDisplacement, const bool dryRun)
virtual ~displacementMotionSolverMeshMover ()
virtual bool move (const dictionary &, const label nAllowableErrors, labelList &checkFaces)
virtual void movePoints (const pointField &)
virtual void updateMesh (const mapPolyMesh &)
Public Member Functions inherited from externalDisplacementMeshMover
TypeName ("externalDisplacementMeshMover")
declareRunTimeSelectionTable (autoPtr, externalDisplacementMeshMover, dictionary,(const dictionary &dict, const List< labelPair > &baffles, pointVectorField &pointDisplacement, const bool dryRun),(dict, baffles, pointDisplacement, dryRun))
externalDisplacementMeshMover (const dictionary &dict, const List< labelPair > &baffles, pointVectorField &pointDisplacement, const bool dryRun)
virtual ~externalDisplacementMeshMover ()
pointVectorField & pointDisplacement ()
const pointVectorField & pointDisplacement () const
const pointMesh & pMesh () const
const polyMesh & mesh () const
Additional Inherited Members
Static Public Member Functions inherited from externalDisplacementMeshMover
static autoPtr< externalDisplacementMeshMover > New (const word &type, const dictionary &dict, const List< labelPair > &baffles, pointVectorField &pointDisplacement, const bool dryRun=false)
Static Protected Member Functions inherited from externalDisplacementMeshMover
static labelList getFixedValueBCs (const pointVectorField &)
static autoPtr< indirectPrimitivePatch > getPatch (const polyMesh &, const labelList &)
Protected Attributes inherited from externalDisplacementMeshMover
List< labelPair > baffles_
pointVectorField & pointDisplacement_
const bool dryRun_
Detailed Description
Quality-based under-relaxation wrapped around generic displacementMotionSolver.
Example of use in layer settings in snappyHexMeshDict:
meshShrinker displacementMotionSolver;
solver displacementLaplacian;
displacementLaplacianCoeffs
{
    diffusivity quadratic inverseDistance 1(wall);
}
Source files
displacementMotionSolverMeshMover.H
displacementMotionSolverMeshMover.C
Definition at line 61 of file displacementMotionSolverMeshMover.H.
Constructor & Destructor Documentation
displacementMotionSolverMeshMover()
displacementMotionSolverMeshMover (const dictionary & dict, const List< labelPair > & baffles, pointVectorField & pointDisplacement, const bool dryRun)
Definition at line 104 of file displacementMotionSolverMeshMover.C.
~displacementMotionSolverMeshMover()
~displacementMotionSolverMeshMover () virtual
Definition at line 188 of file displacementMotionSolverMeshMover.C.
Member Function Documentation
TypeName()
TypeName ("displacementMotionSolver")
move()
bool move (const dictionary & moveDict, const label nAllowableErrors, labelList & checkFaces) virtual
Implements externalDisplacementMeshMover.
Definition at line 194 of file displacementMotionSolverMeshMover.C.
References forAll, meshRefinement::getMasterEdges(), meshRefinement::getMasterPoints(), objectRegistry::lookupObject(), mesh, nPoints, word::null, keyType::REGEX, and Foam::Zero.
movePoints()
void movePoints (const pointField & p) virtual
Reimplemented from externalDisplacementMeshMover.
Definition at line 299 of file displacementMotionSolverMeshMover.C.
References externalDisplacementMeshMover::movePoints(), and p.
updateMesh()
virtual void updateMesh (const mapPolyMesh &) inline virtual
Reimplemented from externalDisplacementMeshMover.
Definition at line 138 of file displacementMotionSolverMeshMover.H.
References NotImplemented.
The documentation for this class was generated from the following files:
src/mesh/snappyHexMesh/externalDisplacementMeshMover/displacementMotionSolverMeshMover.H
src/mesh/snappyHexMesh/externalDisplacementMeshMover/displacementMotionSolverMeshMover.C