OpenFOAM: lduAddressing Class Reference
lduAddressing Class Reference abstract
The class contains the addressing required by the lduMatrix: upper, lower and losort.
#include <lduAddressing.H>
Public Member Functions
lduAddressing (const label nEqns)
virtual ~lduAddressing ()
label size () const
virtual const labelUList & lowerAddr () const =0
virtual const labelUList & upperAddr () const =0
virtual const labelUList & patchAddr (const label patchNo) const =0
virtual const lduSchedule & patchSchedule () const =0
void clearOut ()
const labelUList & losortAddr () const
const labelUList & ownerStartAddr () const
const labelUList & losortStartAddr () const
label triIndex (const label a, const label b) const
Tuple2< label, scalar > band () const
Detailed Description
The class contains the addressing required by the lduMatrix: upper, lower and losort.
The addressing can be created in two ways: either with references to upper and lower in which case it stores references or from labelLists, in which case it stores the addressing itself. Additionally, the losort addressing belongs to the class is as on lazy evaluation.
The ordering of owner addresses is such that the labels are in increasing order, with groups of identical labels for edges "owned" by the same point. The neighbour labels are also ordered in ascending order but only for groups of edges belonging to each point. An example is given below:
    owner     neighbour
    0         1
    0         20
    1         2
    1         21
    2         3
    2         22
    3         4
    3         23
    4         5
    4         24
    5         6
    5         25
    6         7
    6         26
    7         8
    7         27
    8         9
    8         28
    9         10
    9         29
There exists an alternative way of addressing the owner list: instead of repeating the same label in the owner list, it is possible to address the start of each point neighbours in the neighbour list. This reduces the size of owner addressing from a list over all edges to a list over all points + 1:
    Owner start list: 0 2 4 6 8 10 12 14 16 18
We shall use the second form of the addressing for fast lookup of edge label from the known owner and neighbour, using the following algorithm:
take the owner label and position the start of lookup using the owner start list
loop through all neighbours of this owner (ending at the start of lookup of owner + 1) until the match with current neighbour is found. The index used on the neighbour list for the match is the edge index.
While owner start addressing allows us to find the edge owned by the points, it is also necessary to find the edges for which the point is a neighbour. Losort addressing lists the edges neighboured by the point and we shall use the same trick as above to address into this list. Thus, for every point the losort start gives the address of the first face to neighbour this point.
Source files
lduAddressing.H
lduAddressing.C
Definition at line 110 of file lduAddressing.H.
Constructor & Destructor Documentation
lduAddressing()
lduAddressing (const label nEqns) inline explicit
Definition at line 151 of file lduAddressing.H.
~lduAddressing()
~lduAddressing () virtual
Definition at line 171 of file lduAddressing.C.
References Foam::deleteDemandDrivenData().
Member Function Documentation
size()
label size () const inline
Definition at line 167 of file lduAddressing.H.
Referenced by lduPrimitiveMesh::checkUpperTriangular(), lduPrimitiveMesh::gather(), and lduPrimitiveMeshAssembly::update().
lowerAddr()
virtual const labelUList & lowerAddr () const pure virtual
Implemented in lduPrimitiveMesh, faMeshLduAddressing, fvMeshLduAddressing, and fvMeshPrimitiveLduAddressing.
Referenced by lduPrimitiveMesh::gather().
upperAddr()
virtual const labelUList & upperAddr () const pure virtual
Implemented in lduPrimitiveMesh, faMeshLduAddressing, fvMeshLduAddressing, and fvMeshPrimitiveLduAddressing.
Referenced by lduPrimitiveMesh::gather().
patchAddr()
virtual const labelUList & patchAddr (const label patchNo) const pure virtual
Implemented in lduPrimitiveMesh, faMeshLduAddressing, fvMeshLduAddressing, fvMeshPrimitiveLduAddressing, and lduPrimitiveMeshAssembly.
Referenced by processorFvPatchField< Type >::initInterfaceMatrixUpdate(), calculatedProcessorFvPatchField< Type >::initInterfaceMatrixUpdate(), processorFvPatchField< Type >::initInterfaceMatrixUpdate(), lduCalculatedProcessorField< Type >::initInterfaceMatrixUpdate(), cyclicACMIFvPatchField< Type >::updateInterfaceMatrix(), cyclicAMIFvPatchField< Type >::updateInterfaceMatrix(), jumpCyclicFvPatchField< Type >::updateInterfaceMatrix(), jumpCyclicAMIFvPatchField< Type >::updateInterfaceMatrix(), cyclicFvPatchField< Type >::updateInterfaceMatrix(), processorFvPatchField< Type >::updateInterfaceMatrix(), cyclicFvPatchField< scalar >::updateInterfaceMatrix(), cyclicACMIFvPatchField< Type >::updateInterfaceMatrix(), cyclicAMIFvPatchField< scalar >::updateInterfaceMatrix(), processorFvPatchField< Type >::updateInterfaceMatrix(), cyclicACMIGAMGInterfaceField::updateInterfaceMatrix(), cyclicAMIGAMGInterfaceField::updateInterfaceMatrix(), cyclicGAMGInterfaceField::updateInterfaceMatrix(), processorGAMGInterfaceField::updateInterfaceMatrix(), calculatedProcessorGAMGInterfaceField::updateInterfaceMatrix(), jumpCyclicFvPatchField< Type >::updateInterfaceMatrix(), and jumpCyclicAMIFvPatchField< Type >::updateInterfaceMatrix().
patchSchedule()
virtual const lduSchedule & patchSchedule () const pure virtual
Implemented in lduPrimitiveMesh, faMeshLduAddressing, fvMeshLduAddressing, and fvMeshPrimitiveLduAddressing.
clearOut()
void clearOut ()
Definition at line 214 of file lduAddressing.C.
References Foam::deleteDemandDrivenData().
losortAddr()
const Foam::labelUList & losortAddr () const
Definition at line 181 of file lduAddressing.C.
ownerStartAddr()
const Foam::labelUList & ownerStartAddr () const
Definition at line 192 of file lduAddressing.C.
losortStartAddr()
const Foam::labelUList & losortStartAddr () const
Definition at line 203 of file lduAddressing.C.
triIndex()
Foam::label triIndex (const label a, const label b) const
Definition at line 222 of file lduAddressing.C.
References Foam::abort(), b, Foam::FatalError, FatalErrorInFunction, Foam::max(), and Foam::min().
band()
Foam::Tuple2< Foam::label, Foam::scalar > band () const
Definition at line 253 of file lduAddressing.C.
References Foam::diff(), forAll, Foam::max(), and Foam::Zero.
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/lduMatrix/lduAddressing/lduAddressing.H
src/OpenFOAM/matrices/lduMatrix/lduAddressing/lduAddressing.C