OpenFOAM: alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField Class Reference
alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField Class Reference
A simple alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField with a fixed volumetric phase-change mass flux.
#include <alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField.H>
Public Member Functions
TypeName ("compressible::alphatFixedDmdtWallBoilingWallFunction")
alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField (const alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField (const alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField (const alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual bool activePhasePair (const phasePairKey &) const
virtual const scalarField & dmdt (const phasePairKey &) const
virtual const scalarField & mDotL (const phasePairKey &) const
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Public Member Functions inherited from alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField
TypeName ("compressible::alphatPhaseChangeJayatillekeWallFunction")
alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField (const alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField (const alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField &)
alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField (const alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Public Member Functions inherited from alphatPhaseChangeWallFunctionFvPatchScalarField
TypeName ("compressible::alphatPhaseChangeWallFunction")
alphatPhaseChangeWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
alphatPhaseChangeWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
alphatPhaseChangeWallFunctionFvPatchScalarField (const alphatPhaseChangeWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
alphatPhaseChangeWallFunctionFvPatchScalarField (const alphatPhaseChangeWallFunctionFvPatchScalarField &)
alphatPhaseChangeWallFunctionFvPatchScalarField (const alphatPhaseChangeWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual const scalarField & dmdt () const
virtual const scalarField & mDotL () const
virtual scalarField dmdt (const word &) const
virtual scalarField mDotL (const word &) const
Additional Inherited Members
Protected Member Functions inherited from alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField
void checkType ()
tmp< scalarField > Psmooth (const scalarField &Prat) const
tmp< scalarField > yPlusTherm (const scalarField &P, const scalarField &Prat) const
tmp< scalarField > calcAlphat (const scalarField &prevAlphat) const
Protected Attributes inherited from alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField
scalar Prt_
scalar Cmu_
scalar kappa_
scalar E_
Protected Attributes inherited from alphatPhaseChangeWallFunctionFvPatchScalarField
scalarField dmdt_
scalarField mDotL_
Static Protected Attributes inherited from alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField
static scalar tolerance_ = 0.01
static label maxIters_ = 10
Detailed Description
A simple alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField with a fixed volumetric phase-change mass flux.
Usage
Example of the boundary condition specification:
<patch>
{
    // Mandatory entries
    type         compressible::alphatFixedDmdtWallBoilingWallFunction;
    vaporPhase   <word>;
    // Optional entries
    relax        <scalar>;
    fixedDmdt    <scalar>;
    L            <scalar>;
    // Inherited entries
    ...
}
where the entries mean:
Property Description Type Reqd Deflt
type
Type name:
compressible::alphatFixedDmdtWallBoilingWallFunction
word yes -
vaporPhase Name of the vapor phase word yes -
relax Relaxation factor for dmdt scalar no 1.0
fixedDmdt
Volumetric phase-change mass flux in near wall cells
scalar no 0.0
L Latent heat scalar no 0.0
The inherited entries are elaborated in: -Foam::compressible:: alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField Source files alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField.H alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField.C
Definition at line 131 of file alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField.H.
Constructor & Destructor Documentation
alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField() [1/5]
alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 35 of file alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField.C.
References alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField::checkType().
alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField() [2/5]
alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 52 of file alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField.C.
alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField() [3/5]
alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField (const alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField & psf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 68 of file alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField.C.
alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField() [4/5]
alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField (const alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField & psf)
Definition at line 91 of file alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField.C.
alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField() [5/5]
alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField (const alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField & psf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 105 of file alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("compressible::alphatFixedDmdtWallBoilingWallFunction")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Reimplemented from alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField.
Definition at line 191 of file alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Reimplemented from alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField.
Definition at line 210 of file alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField.H.
activePhasePair()
bool activePhasePair (const phasePairKey & phasePair) const virtual
Reimplemented from alphatPhaseChangeWallFunctionFvPatchScalarField.
Definition at line 122 of file alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField.C.
Referenced by alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField::dmdt(), and alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField::mDotL().
dmdt()
const scalarField & dmdt (const phasePairKey & phasePair) const virtual
Reimplemented from alphatPhaseChangeWallFunctionFvPatchScalarField.
Definition at line 134 of file alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField.C.
References Foam::abort(), alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField::activePhasePair(), alphatPhaseChangeWallFunctionFvPatchScalarField::dmdt_, Foam::FatalError, FatalErrorInFunction, and alphatPhaseChangeWallFunctionFvPatchScalarField::mDotL_.
mDotL()
const scalarField & mDotL (const phasePairKey & phasePair) const virtual
Reimplemented from alphatPhaseChangeWallFunctionFvPatchScalarField.
Definition at line 150 of file alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField.C.
References Foam::abort(), alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField::activePhasePair(), Foam::FatalError, FatalErrorInFunction, and alphatPhaseChangeWallFunctionFvPatchScalarField::mDotL_.
updateCoeffs()
void updateCoeffs () virtual
Reimplemented from alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField.
Definition at line 166 of file alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField.C.
References alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField::calcAlphat(), alphatPhaseChangeWallFunctionFvPatchScalarField::dmdt_, alphatPhaseChangeWallFunctionFvPatchScalarField::mDotL_, and Foam::operator==().
write()
void write (Ostream & os) const virtual
Reimplemented from alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField.
Definition at line 184 of file alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField.C.
References alphatPhaseChangeWallFunctionFvPatchScalarField::dmdt_, os(), fvPatchField< Type >::write(), Field< Type >::writeEntry(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/alphatFixedDmdtWallBoilingWallFunction/alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/alphatFixedDmdtWallBoilingWallFunction/alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField.C