OpenFOAM: hConstThermo< EquationOfState > Class Template Reference
hConstThermo< EquationOfState > Class Template Reference
Thermophysical models » Specie » Thermodynamics
Constant properties thermodynamics package templated into the EquationOfState.
#include <hConstThermo.H>
Public Member Functions
hConstThermo (const dictionary &dict)
hConstThermo (const word &, const hConstThermo &)
autoPtr< hConstThermo > clone () const
scalar limit (const scalar T) const
scalar Cp (const scalar p, const scalar T) const
scalar Ha (const scalar p, const scalar T) const
scalar Hs (const scalar p, const scalar T) const
scalar Hc () const
scalar S (const scalar p, const scalar T) const
scalar Gstd (const scalar T) const
scalar dCpdT (const scalar p, const scalar T) const
void write (Ostream &os) const
void operator+= (const hConstThermo &)
Static Public Member Functions
static autoPtr< hConstThermo > New (const dictionary &dict)
static word typeName ()
Friends
hConstThermo operator+ (const hConstThermo &, const hConstThermo &)
hConstThermo operator* (const scalar, const hConstThermo &)
hConstThermo operator== (const hConstThermo &, const hConstThermo &)
Ostream & operator<< (Ostream &, const hConstThermo &)
Detailed Description
template<class EquationOfState>
class Foam::hConstThermo< EquationOfState >
Constant properties thermodynamics package templated into the EquationOfState.
Source files
hConstThermo.H
hConstThermoI.H
hConstThermo.C
Definition at line 84 of file hConstThermo.H.
Constructor & Destructor Documentation
hConstThermo() [1/2]
template<class EquationOfState > hConstThermo (const dictionary & dict)
Definition at line 28 of file hConstThermo.C.
hConstThermo() [2/2]
template<class EquationOfState > hConstThermo (const word & name, const hConstThermo< EquationOfState > & ct) inline
Definition at line 44 of file hConstThermoI.H.
References Foam::name().
Member Function Documentation
clone()
template<class EquationOfState > Foam::autoPtr< Foam::hConstThermo< EquationOfState > > clone () const inline
Definition at line 60 of file hConstThermoI.H.
References Foam::New().
New()
template<class EquationOfState > Foam::autoPtr< Foam::hConstThermo< EquationOfState > > New (const dictionary & dict) inline static
Definition at line 68 of file hConstThermoI.H.
References dict, and Foam::New().
typeName()
template<class EquationOfState > static word typeName () inline static
Definition at line 133 of file hConstThermo.H.
limit()
template<class EquationOfState > Foam::scalar limit (const scalar T) const inline
Definition at line 77 of file hConstThermoI.H.
References T.
Cp()
template<class EquationOfState > Foam::scalar Cp (const scalar p, const scalar T) const inline
Definition at line 87 of file hConstThermoI.H.
References p, and T.
Ha()
template<class EquationOfState > Foam::scalar Ha (const scalar p, const scalar T) const inline
Definition at line 98 of file hConstThermoI.H.
References Hs(), p, and T.
Hs()
template<class EquationOfState > Foam::scalar Hs (const scalar p, const scalar T) const inline
Definition at line 108 of file hConstThermoI.H.
References p, and T.
Hc()
template<class EquationOfState > Foam::scalar Hc () const inline
Definition at line 118 of file hConstThermoI.H.
S()
template<class EquationOfState > Foam::scalar S (const scalar p, const scalar T) const inline
Definition at line 125 of file hConstThermoI.H.
References Foam::log(), p, and T.
Gstd()
template<class EquationOfState > Foam::scalar Gstd (const scalar T) const inline
Definition at line 135 of file hConstThermoI.H.
References Foam::log(), and T.
dCpdT()
template<class EquationOfState > Foam::scalar dCpdT (const scalar p, const scalar T) const inline
Definition at line 145 of file hConstThermoI.H.
write()
template<class EquationOfState > void write (Ostream & os) const
Definition at line 41 of file hConstThermo.C.
References Ostream::beginBlock(), Ostream::endBlock(), os(), Ostream::writeEntry(), and Ostream::writeEntryIfDifferent().
operator+=()
template<class EquationOfState > void operator+= (const hConstThermo< EquationOfState > &) inline
Definition at line 156 of file hConstThermoI.H.
References Foam::mag(), and Y.
Friends And Related Symbol Documentation
operator+
template<class EquationOfState > hConstThermo operator+ (const hConstThermo< EquationOfState > & , const hConstThermo< EquationOfState > &) friend
operator*
template<class EquationOfState > hConstThermo operator* (const scalar , const hConstThermo< EquationOfState > &) friend
operator==
template<class EquationOfState > hConstThermo operator== (const hConstThermo< EquationOfState > & , const hConstThermo< EquationOfState > &) friend
operator<<
template<class EquationOfState > Ostream & operator<< (Ostream & , const hConstThermo< EquationOfState > &) friend
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/thermo/hConst/hConstThermo.H
src/thermophysicalModels/specie/thermo/hConst/hConstThermo.C
src/thermophysicalModels/specie/thermo/hConst/hConstThermoI.H