OpenFOAM: zoneMotion Class Reference
zoneMotion Class Reference
Intermediate class for handling "zonified" motion. Can select motion for the entire mesh, or restrict to a subset of points based on a specified cellSet or cellZone(s).
#include <zoneMotion.H>
Public Member Functions
zoneMotion (const dictionary &dict, const polyMesh &mesh)
virtual ~zoneMotion ()=default
const labelList & pointIDs () const noexcept
bool moveAllCells () const noexcept
Detailed Description
Intermediate class for handling "zonified" motion. Can select motion for the entire mesh, or restrict to a subset of points based on a specified cellSet or cellZone(s).
Usage
{
    cellSet     <name>;
    // and/or
    cellZone    <name or regex>;
}
Note
The cellZone can be specified as a wordRe and will select by name or group. The special name "none" is treated as ignored.
Source files
zoneMotion.H
zoneMotion.C
Definition at line 66 of file zoneMotion.H.
Constructor & Destructor Documentation
zoneMotion()
zoneMotion (const dictionary & dict, const polyMesh & mesh)
Definition at line 31 of file zoneMotion.C.
References cellIDs, wordRe::clear(), dict, UList< T >::empty(), Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, Foam::flatOutput(), Foam::Info, mesh, Foam::nl, Foam::returnReduceAnd(), PtrList< T >::set(), syncTools::syncPointList(), HashTable< T, Key, Hash >::toc(), and zoneIDs.
~zoneMotion()
virtual ~zoneMotion () virtual default
Member Function Documentation
pointIDs()
const labelList & pointIDs () const inline noexcept
Definition at line 92 of file zoneMotion.H.
moveAllCells()
bool moveAllCells () const inline noexcept
Definition at line 98 of file zoneMotion.H.
The documentation for this class was generated from the following files:
src/dynamicMesh/motionSolvers/displacement/displacement/zoneMotion.H
src/dynamicMesh/motionSolvers/displacement/displacement/zoneMotion.C