OpenFOAM: EFA< CompType, ThermoType > Class Template Reference
EFA< CompType, ThermoType > Class Template Reference
#include <EFA.H>
Public Member Functions
TypeName ("EFA")
EFA (const IOdictionary &dict, TDACChemistryModel< CompType, ThermoType > &chemistry)
virtual ~EFA ()
virtual void reduceMechanism (const scalarField &c, const scalar T, const scalar p)
Public Member Functions inherited from chemistryReductionMethod< CompType, ThermoType >
TypeName ("chemistryReductionMethod")
declareRunTimeSelectionTable (autoPtr, chemistryReductionMethod, dictionary,(const IOdictionary &dict, TDACChemistryModel< CompType, ThermoType > &chemistry),(dict, chemistry))
chemistryReductionMethod (const IOdictionary &dict, TDACChemistryModel< CompType, ThermoType > &chemistry)
virtual ~chemistryReductionMethod ()
bool active () const
bool log () const
const List< bool > & activeSpecies () const
label NsSimp ()
label nSpecie ()
scalar tolerance () const
Additional Inherited Members
Static Public Member Functions inherited from chemistryReductionMethod< CompType, ThermoType >
static autoPtr< chemistryReductionMethod< CompType, ThermoType > > New (const IOdictionary &dict, TDACChemistryModel< CompType, ThermoType > &chemistry)
Protected Attributes inherited from chemistryReductionMethod< CompType, ThermoType >
const IOdictionary & dict_
const dictionary coeffsDict_
Switch active_
Switch log_
TDACChemistryModel< CompType, ThermoType > & chemistry_
List< bool > activeSpecies_
label NsSimp_
const label nSpecie_
scalar tolerance_
Detailed Description
template<class CompType, class ThermoType>
class Foam::chemistryReductionMethods::EFA< CompType, ThermoType >
Source files
EFA.H
EFA.C
Definition at line 46 of file EFA.H.
Constructor & Destructor Documentation
EFA()
template<class CompType , class ThermoType > EFA (const IOdictionary & dict, TDACChemistryModel< CompType, ThermoType > & chemistry)
Definition at line 27 of file EFA.C.
References chemistryReductionMethod< CompType, ThermoType >::chemistry_, chemistryReductionMethod< CompType, ThermoType >::coeffsDict_, Foam::endl(), forAll, Foam::Info, chemistryReductionMethod< CompType, ThermoType >::nSpecie_, and TDACChemistryModel< ReactionThermo, ThermoType >::specieComp().
~EFA()
template<class CompType , class ThermoType > ~EFA () virtual
Definition at line 81 of file EFA.C.
Member Function Documentation
TypeName()
template<class CompType , class ThermoType > TypeName ("EFA< CompType, ThermoType >")
reduceMechanism()
template<class CompType , class ThermoType > void reduceMechanism (const scalarField & c, const scalar T, const scalar p) virtual
Implements chemistryReductionMethod< CompType, ThermoType >.
Definition at line 88 of file EFA.C.
References A, B, Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::mag(), Foam::max(), Foam::min(), p, R, s(), List< T >::setSize(), PtrList< T >::setSize(), T, and Foam::Zero.
The documentation for this class was generated from the following files:
src/thermophysicalModels/chemistryModel/chemistryModel/TDACChemistryModel/reduction/EFA/EFA.H
src/thermophysicalModels/chemistryModel/chemistryModel/TDACChemistryModel/reduction/EFA/EFA.C