OpenFOAM: MatrixBlock< MatrixType > Class Template Reference
MatrixBlock< MatrixType > Class Template Reference
A templated block of an (m x n) matrix of type <MatrixType>.
#include <MatrixBlock.H>
Public Types
typedef MatrixType::cmptType cmptType
Public Member Functions
MatrixBlock (const MatrixBlock &)=default
MatrixBlock (MatrixType &matrix, const label m, const label n, const label mStart, const label nStart)
label m () const
label n () const
labelPair sizes () const
const cmptType & operator() (const label i, const label j) const
cmptType & operator() (const label i, const label j)
operator Field< cmptType > () const
void checkIndex (const label i, const label j) const
template<class Form >
void operator= (const Matrix< Form, cmptType > &)
void operator= (const ConstMatrixBlock< MatrixType > &)
void operator= (const MatrixBlock< MatrixType > &)
template<class MatrixType2 >
void operator= (const ConstMatrixBlock< MatrixType2 > &)
template<class MatrixType2 >
void operator= (const MatrixBlock< MatrixType2 > &)
template<class MSForm , direction Nrows, direction Ncols>
void operator= (const MatrixSpace< MSForm, cmptType, Nrows, Ncols > &)
template<template< class, direction, direction > class Block, class SubTensor , direction BRowStart, direction BColStart>
void operator= (const Block< SubTensor, BRowStart, BColStart > &)
template<class VSForm , direction Ncmpts>
void operator= (const VectorSpace< VSForm, cmptType, Ncmpts > &)
template<template< class, direction > class Block, class SubVector , direction BStart>
void operator= (const Block< SubVector, BStart > &)
void operator= (const Field< cmptType > &)
template<template< class, Foam::direction, Foam::direction > class MSBlock, class SubTensor , Foam::direction BRowStart, Foam::direction BColStart>
void operator= (const MSBlock< SubTensor, BRowStart, BColStart > &Mb)
template<template< class, Foam::direction > class VSBlock, class SubVector , Foam::direction BStart>
void operator= (const VSBlock< SubVector, BStart > &Mb)
Detailed Description
template<class MatrixType>
class Foam::MatrixBlock< MatrixType >
A templated block of an (m x n) matrix of type <MatrixType>.
Foam::ConstMatrixBlock: block of a const matrix Foam::MatrixBlock: block of a non-const matrix
The block may be assigned to a block of another matrix or to a VectorSpace or MatrixSpace e.g. tensor. Conversion of a column block to a Field<T> is also provide.
Source files
MatrixBlock.H
MatrixBlock.C
MatrixBlockI.H
Definition at line 127 of file MatrixBlock.H.
Member Typedef Documentation
cmptType
template<class MatrixType > typedef MatrixType::cmptType cmptType
Definition at line 151 of file MatrixBlock.H.
Constructor & Destructor Documentation
MatrixBlock() [1/2]
template<class MatrixType > MatrixBlock (const MatrixBlock< MatrixType > &) default
MatrixBlock() [2/2]
template<class MatrixType > MatrixBlock (MatrixType & matrix, const label m, const label n, const label mStart, const label nStart) inline
Definition at line 53 of file MatrixBlockI.H.
Member Function Documentation
m()
template<class MatrixType > Foam::label m () const inline
Definition at line 97 of file MatrixBlockI.H.
n()
template<class MatrixType > Foam::label n () const inline
Definition at line 104 of file MatrixBlockI.H.
sizes()
template<class MatrixType > Foam::labelPair sizes () const inline
Definition at line 118 of file MatrixBlockI.H.
operator()() [1/2]
template<class MatrixType > const MatrixType::cmptType & operator() (const label i, const label j) const inline
Definition at line 144 of file MatrixBlockI.H.
operator()() [2/2]
template<class MatrixType > MatrixType::cmptType & operator() (const label i, const label j) inline
Definition at line 160 of file MatrixBlockI.H.
operator Field< cmptType >()
template<class MatrixType > operator Field< cmptType > () const
Definition at line 48 of file MatrixBlock.C.
References Foam::abort(), f(), Foam::FatalError, FatalErrorInFunction, and forAll.
checkIndex()
template<class MatrixType > void checkIndex (const label i, const label j) const
Definition at line 117 of file MatrixBlock.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
operator=() [1/12]
template<class MatrixType > template<class Form > void operator= (const Matrix< Form, cmptType > & Mb)
Definition at line 142 of file MatrixBlock.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
operator=() [2/12]
template<class MatrixType > void operator= (const ConstMatrixBlock< MatrixType > & Mb)
Definition at line 167 of file MatrixBlock.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
operator=() [3/12]
template<class MatrixType > void operator= (const MatrixBlock< MatrixType > & Mb)
Definition at line 195 of file MatrixBlock.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
operator=() [4/12]
template<class MatrixType > template<class MatrixType2 > void operator= (const ConstMatrixBlock< MatrixType2 > & Mb)
Definition at line 224 of file MatrixBlock.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
operator=() [5/12]
template<class MatrixType > template<class MatrixType2 > void operator= (const MatrixBlock< MatrixType2 > & Mb)
Definition at line 253 of file MatrixBlock.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
operator=() [6/12]
template<class MatrixType > template<class MSForm , Foam::direction Nrows, Foam::direction Ncols> void operator= (const MatrixSpace< MSForm, cmptType, Nrows, Ncols > & ms)
Definition at line 342 of file MatrixBlock.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
operator=() [7/12]
template<class MatrixType > template<template< class, direction, direction > class Block, class SubTensor , direction BRowStart, direction BColStart> void operator= (const Block< SubTensor, BRowStart, BColStart > &)
operator=() [8/12]
template<class MatrixType > template<class VSForm , Foam::direction Ncmpts> void operator= (const VectorSpace< VSForm, cmptType, Ncmpts > & ms)
Definition at line 368 of file MatrixBlock.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
operator=() [9/12]
template<class MatrixType > template<template< class, direction > class Block, class SubVector , direction BStart> void operator= (const Block< SubVector, BStart > &)
operator=() [10/12]
template<class MatrixType > void operator= (const Field< cmptType > & f)
Definition at line 390 of file MatrixBlock.C.
References Foam::abort(), f(), Foam::FatalError, FatalErrorInFunction, forAll, and UList< T >::size().
operator=() [11/12]
template<class MatrixType > template<template< class, Foam::direction, Foam::direction > class MSBlock, class SubTensor , Foam::direction BRowStart, Foam::direction BColStart> void operator= (const MSBlock< SubTensor, BRowStart, BColStart > & Mb)
Definition at line 288 of file MatrixBlock.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
operator=() [12/12]
template<class MatrixType > template<template< class, Foam::direction > class VSBlock, class SubVector , Foam::direction BStart> void operator= (const VSBlock< SubVector, BStart > & Mb)
Definition at line 319 of file MatrixBlock.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/Matrix/Matrix.H
src/OpenFOAM/matrices/MatrixBlock/MatrixBlock.H
src/OpenFOAM/matrices/MatrixBlock/MatrixBlock.C
src/OpenFOAM/matrices/MatrixBlock/MatrixBlockI.H