OpenFOAM: quadraticEqn Class Reference
quadraticEqn Class Reference
Container to encapsulate various operations for quadratic equation of the forms with real coefficients:
#include <quadraticEqn.H>
Public Types
enum components { A , B , C }
Public Types inherited from VectorSpace< quadraticEqn, scalar, 3 >
typedef VectorSpace< quadraticEqn, scalar, Ncmpts > vsType
typedef scalar cmptType
typedef scalar magType
typedef scalar * iterator
typedef const scalar * const_iterator
Public Member Functions
quadraticEqn ()=default
quadraticEqn (const Foam::zero)
quadraticEqn (const scalar a, const scalar b, const scalar c)
scalar a () const noexcept
scalar b () const noexcept
scalar c () const noexcept
scalar & a () noexcept
scalar & b () noexcept
scalar & c () noexcept
scalar value (const scalar x) const
scalar derivative (const scalar x) const
scalar error (const scalar x) const
Roots< 2 > roots () const
Public Member Functions inherited from VectorSpace< quadraticEqn, scalar, 3 >
VectorSpace ()=default
VectorSpace (const Foam::zero)
VectorSpace (const VectorSpace< quadraticEqn, scalar, Ncmpts > &vs)
VectorSpace (const VectorSpace< Form2, Cmpt2, Ncmpts > &)
VectorSpace (Istream &is)
const scalar & component (const direction) const
scalar & component (const direction)
void component (scalar &, const direction) const
void replace (const direction, const scalar &)
const scalar * cdata () const noexcept
scalar * data () noexcept
const ConstBlock< SubVector, BStart > block () const
const Foam::VectorSpace< quadraticEqn, scalar, Ncmpts >::template ConstBlock< SubVector, BStart > block () const
const scalar & operator[] (const direction) const
scalar & operator[] (const direction)
void operator= (const VectorSpace< quadraticEqn, scalar, Ncmpts > &)
void operator= (const Foam::zero)
void operator+= (const VectorSpace< quadraticEqn, scalar, Ncmpts > &)
void operator-= (const VectorSpace< quadraticEqn, scalar, Ncmpts > &)
void operator*= (const scalar)
void operator/= (const scalar)
iterator begin () noexcept
const_iterator begin () const noexcept
iterator end () noexcept
const_iterator end () const noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
Additional Inherited Members
Static Public Member Functions inherited from VectorSpace< quadraticEqn, scalar, 3 >
static constexpr direction size () noexcept
static quadraticEqn uniform (const scalar &s)
Public Attributes inherited from VectorSpace< quadraticEqn, scalar, 3 >
scalar v_ [Ncmpts]
Static Public Attributes inherited from VectorSpace< quadraticEqn, scalar, 3 >
static constexpr direction dim
static constexpr direction nComponents
static constexpr direction mRows
static constexpr direction nCols
static const char *const typeName
static const char *const componentNames []
static const quadraticEqn zero
static const quadraticEqn one
static const quadraticEqn max
static const quadraticEqn min
static const quadraticEqn rootMax
static const quadraticEqn rootMin
Detailed Description
Container to encapsulate various operations for quadratic equation of the forms with real coefficients:
The expressions for the roots of quadraticEqn are as follows:
where (b^2 - 4ac) is evaluated by fused multiply-adds to avoid detrimental cancellation.
Reference:
    Cancellation-avoiding quadratic formula (tag:F):
        Ford, W. (2014).
        Numerical linear algebra with applications: Using MATLAB.
        London: Elsevier/Academic Press.
        DOI:10.1016/C2011-0-07533-6
    Kahan's algo. to compute 'b^2-a*c' using fused multiply-adds (tag:JML):
        Jeannerod, C. P., Louvet, N., & Muller, J. M. (2013).
        Further analysis of Kahan's algorithm for the accurate
        computation of 2 2 determinants.
        Mathematics of Computation, 82(284), 2245-2264.
        DOI:10.1090/S0025-5718-2013-02679-8
See also
Test-quadraticEqn.C
Source files
quadraticEqn.H
quadraticEqnI.H
quadraticEqn.C
Definition at line 84 of file quadraticEqn.H.
Member Enumeration Documentation
components
enum components
Enumerator
A
B
C
Definition at line 91 of file quadraticEqn.H.
Constructor & Destructor Documentation
quadraticEqn() [1/3]
quadraticEqn () default
quadraticEqn() [2/3]
quadraticEqn (const Foam::zero) inline
Definition at line 23 of file quadraticEqnI.H.
quadraticEqn() [3/3]
quadraticEqn (const scalar a, const scalar b, const scalar c) inline
Definition at line 29 of file quadraticEqnI.H.
References A, b, and B.
Member Function Documentation
a() [1/2]
scalar a () const inline noexcept
Definition at line 110 of file quadraticEqn.H.
References quadraticEqn::A, and VectorSpace< quadraticEqn, scalar, 3 >::v_.
Referenced by quadraticEqn::roots().
b() [1/2]
scalar b () const inline noexcept
Definition at line 111 of file quadraticEqn.H.
References quadraticEqn::B, and VectorSpace< quadraticEqn, scalar, 3 >::v_.
Referenced by quadraticEqn::roots().
c() [1/2]
scalar c () const inline noexcept
Definition at line 112 of file quadraticEqn.H.
References quadraticEqn::C, and VectorSpace< quadraticEqn, scalar, 3 >::v_.
Referenced by quadraticEqn::roots().
a() [2/2]
scalar & a () inline noexcept
Definition at line 114 of file quadraticEqn.H.
References quadraticEqn::A, and VectorSpace< quadraticEqn, scalar, 3 >::v_.
b() [2/2]
scalar & b () inline noexcept
Definition at line 115 of file quadraticEqn.H.
References quadraticEqn::B, and VectorSpace< quadraticEqn, scalar, 3 >::v_.
c() [2/2]
scalar & c () inline noexcept
Definition at line 116 of file quadraticEqn.H.
References quadraticEqn::C, and VectorSpace< quadraticEqn, scalar, 3 >::v_.
value()
Foam::scalar value (const scalar x) const inline
Definition at line 44 of file quadraticEqnI.H.
References b, and x.
derivative()
Foam::scalar derivative (const scalar x) const inline
Definition at line 50 of file quadraticEqnI.H.
References b, and x.
error()
Foam::scalar error (const scalar x) const inline
Definition at line 56 of file quadraticEqnI.H.
References b, Foam::mag(), and x.
roots()
Foam::Roots< 2 > roots () const
Definition at line 27 of file quadraticEqn.C.
References quadraticEqn::a(), quadraticEqn::b(), quadraticEqn::c(), Foam::roots::complex, Foam::mag(), Foam::roots::nan, quadraticEqn::roots(), Foam::sign(), Foam::sqrt(), and x.
Referenced by quadraticEqn::roots().
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/polynomialEqns/quadraticEqn/quadraticEqn.H
src/OpenFOAM/primitives/polynomialEqns/quadraticEqn/quadraticEqn.C
src/OpenFOAM/primitives/polynomialEqns/quadraticEqn/quadraticEqnI.H