OpenFOAM: multivariateSelectionScheme< Type > Class Template Reference
multivariateSelectionScheme< Type > Class Template Reference
Generic multi-variate discretisation scheme class for which any of the NVD, CNVD or NVDV schemes may be selected for each variable.
#include <multivariateSelectionScheme.H>
Classes
class fieldScheme
Public Member Functions
TypeName ("multivariateSelection")
multivariateSelectionScheme (const fvMesh &mesh, const typename multivariateSurfaceInterpolationScheme< Type >::fieldTable &fields, const surfaceScalarField &faceFlux, Istream &schemeData)
tmp< surfaceInterpolationScheme< Type > > operator() (const GeometricField< Type, fvPatchField, volMesh > &field) const
Public Member Functions inherited from multivariateSurfaceInterpolationScheme< Type >
virtual const word & type () const =0
declareRunTimeSelectionTable (tmp, multivariateSurfaceInterpolationScheme, Istream,(const fvMesh &mesh, const fieldTable &fields, const surfaceScalarField &faceFlux, Istream &is),(mesh, fields, faceFlux, is))
multivariateSurfaceInterpolationScheme (const fvMesh &mesh, const fieldTable &fields, const surfaceScalarField &faceFlux, Istream &schemeData)
virtual ~multivariateSurfaceInterpolationScheme ()=default
const fvMesh & mesh () const
const fieldTable & fields () const
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Additional Inherited Members
Static Public Member Functions inherited from multivariateSurfaceInterpolationScheme< Type >
static tmp< multivariateSurfaceInterpolationScheme< Type > > New (const fvMesh &mesh, const fieldTable &fields, const surfaceScalarField &faceFlux, Istream &schemeData)
Detailed Description
template<class Type>
class Foam::multivariateSelectionScheme< Type >
Generic multi-variate discretisation scheme class for which any of the NVD, CNVD or NVDV schemes may be selected for each variable.
Source files
multivariateSelectionScheme.H
multivariateSelectionScheme.C
Definition at line 49 of file multivariateSelectionScheme.H.
Constructor & Destructor Documentation
multivariateSelectionScheme()
template<class Type > multivariateSelectionScheme (const fvMesh & mesh, const typename multivariateSurfaceInterpolationScheme< Type >::fieldTable & fields, const surfaceScalarField & faceFlux, Istream & schemeData)
Definition at line 32 of file multivariateSelectionScheme.C.
References UPtrList< T >::cbegin(), Foam::dimless, multivariateSurfaceInterpolationScheme< Type >::fields(), Foam::limiter(), dictionary::lookup(), multivariateSurfaceInterpolationScheme< Type >::mesh(), Foam::min(), and Foam::name().
Member Function Documentation
TypeName()
template<class Type > TypeName ("multivariateSelection")
operator()()
template<class Type > tmp< surfaceInterpolationScheme< Type > > operator() (const GeometricField< Type, fvPatchField, volMesh > & field) const inline virtual
Implements multivariateSurfaceInterpolationScheme< Type >.
Definition at line 131 of file multivariateSelectionScheme.H.
References field().
The documentation for this class was generated from the following files:
src/finiteVolume/interpolation/surfaceInterpolation/multivariateSchemes/multivariateSelectionScheme/multivariateSelectionScheme.H
src/finiteVolume/interpolation/surfaceInterpolation/multivariateSchemes/multivariateSelectionScheme/multivariateSelectionScheme.C