OpenFOAM: pressure Class Reference
pressure Class Reference
FunctionObjects » Field function objects
Provides several methods to convert an input pressure field into derived forms, including:
#include <pressure.H>
Public Types
enum mode : unsigned {
STATIC = (1 << 0) , TOTAL = (1 << 1) , ISENTROPIC = (1 << 2) , COEFF = (1 << 3) ,
STATIC_COEFF = (STATIC | COEFF) , TOTAL_COEFF = (TOTAL | COEFF)
}
enum hydrostaticMode : unsigned { NONE = 0 , ADD , SUBTRACT }
Public Member Functions
TypeName ("pressure")
pressure (const word &name, const Time &runTime, const dictionary &)
pressure (const pressure &)=delete
void operator= (const pressure &)=delete
virtual ~pressure ()=default
virtual bool read (const dictionary &)
Public Member Functions inherited from fieldExpression
TypeName ("fieldExpression")
fieldExpression (const word &name, const Time &runTime, const dictionary &dict, const word &fieldName=word::null, const word &resultName=word::null)
fieldExpression (const fieldExpression &)=delete
void operator= (const fieldExpression &)=delete
virtual ~fieldExpression ()=default
virtual bool execute ()
virtual bool write ()
virtual bool clear ()
Public Member Functions inherited from fvMeshFunctionObject
TypeName ("fvMeshFunctionObject")
fvMeshFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
fvMeshFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
virtual ~fvMeshFunctionObject ()=default
Public Member Functions inherited from regionFunctionObject
TypeName ("regionFunctionObject")
regionFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
regionFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
virtual ~regionFunctionObject ()=default
template<class ObjectType >
const ObjectType * lookupObjectPtr (const word &fieldName) const
template<class ObjectType >
ObjectType * lookupObjectRefPtr (const word &fieldName) const
Public Member Functions inherited from stateFunctionObject
stateFunctionObject (const word &name, const Time &runTime)
virtual ~stateFunctionObject ()=default
dictionary & propertyDict ()
bool foundProperty (const word &entryName) const
void clearTrigger ()
label getTrigger () const
bool setTrigger (const label triggeri)
bool getDict (const word &entryName, dictionary &dict) const
bool getObjectDict (const word &objectName, const word &entryName, dictionary &dict) const
template<class Type >
Type getProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getProperty (const word &entryName, Type &value) const
template<class Type >
void setProperty (const word &entryName, const Type &value)
template<class Type >
Type getObjectProperty (const word &objectName, const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getObjectProperty (const word &objectName, const word &entryName, Type &value) const
template<class Type >
void setObjectProperty (const word &objectName, const word &entryName, const Type &value)
template<class Type >
void setResult (const word &entryName, const Type &value)
template<class Type >
void setObjectResult (const word &objectName, const word &entryName, const Type &value)
template<class Type >
Type getResult (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
Type getObjectResult (const word &objectName, const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getObjectResult (const word &objectName, const word &entryName, Type &value) const
word resultType (const word &entryName) const
word objectResultType (const word &objectName, const word &entryName) const
wordList objectResultEntries () const
wordList objectResultEntries (const word &objectName) const
void writeResultEntries (Ostream &os) const
void writeResultEntries (const word &objectName, Ostream &os) const
void writeAllResultEntries (Ostream &os) const
Public Member Functions inherited from timeFunctionObject
timeFunctionObject (const word &name, const Time &runTime)
virtual ~timeFunctionObject ()=default
const Time & time () const
objectRegistry & storedObjects ()
const objectRegistry & storedObjects () const
Public Member Functions inherited from functionObject
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name, const bool withNamePrefix=defaultUseNamePrefix)
autoPtr< functionObject > clone () const
virtual ~functionObject ()=default
virtual const word & type () const =0
const word & name () const noexcept
bool useNamePrefix () const noexcept
bool useNamePrefix (bool on) noexcept
virtual bool execute (const label subIndex)
virtual bool end ()
virtual bool adjustTimeStep ()
virtual bool filesModified () const
virtual void updateMesh (const mapPolyMesh &mpm)
virtual void movePoints (const polyMesh &mesh)
Static Public Attributes
static const Enum< mode > modeNames
static const Enum< hydrostaticMode > hydrostaticModeNames
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
static bool defaultUseNamePrefix
static word outputPrefix
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &runTime, const dictionary &dict)
Public Attributes inherited from functionObject
bool log
Protected Member Functions inherited from fieldExpression
void setResultName (const word &typeName, const word &defaultArg)
template<class Type >
bool foundObject (const word &name, const bool verbose=true) const
Protected Member Functions inherited from fvMeshFunctionObject
fvMeshFunctionObject (const fvMeshFunctionObject &)=delete
void operator= (const fvMeshFunctionObject &)=delete
Protected Member Functions inherited from regionFunctionObject
virtual const objectRegistry & obr () const
template<class ObjectType >
bool foundObject (const word &fieldName) const
template<class ObjectType >
const ObjectType * cfindObject (const word &fieldName) const
template<class ObjectType >
const ObjectType * findObject (const word &fieldName) const
template<class ObjectType >
ObjectType * findObject (const word &fieldName)
template<class ObjectType >
ObjectType * getObjectPtr (const word &fieldName) const
template<class ObjectType >
const ObjectType & lookupObject (const word &fieldName) const
template<class ObjectType >
ObjectType & lookupObjectRef (const word &fieldName) const
template<class ObjectType >
bool store (word &fieldName, const tmp< ObjectType > &tfield, bool cacheable=false)
template<class ObjectType >
bool storeInDb (const word &fieldName, const tmp< ObjectType > &tfield, const objectRegistry &obr)
bool writeObject (const word &fieldName)
bool clearObject (const word &fieldName)
void clearObjects (const wordList &objNames)
regionFunctionObject (const regionFunctionObject &)=delete
void operator= (const regionFunctionObject &)=delete
Protected Member Functions inherited from stateFunctionObject
const functionObjects::properties & stateDict () const
functionObjects::properties & stateDict ()
stateFunctionObject (const stateFunctionObject &)=delete
void operator= (const stateFunctionObject &)=delete
Protected Member Functions inherited from timeFunctionObject
void clearOutputObjects (const wordList &objNames)
timeFunctionObject (const timeFunctionObject &)=delete
void operator= (const timeFunctionObject &)=delete
Protected Member Functions inherited from functionObject
word scopedName (const word &name) const
Protected Attributes inherited from fieldExpression
word fieldName_
word resultName_
autoPtr< Detail::zoneSubSet > zoneSubSetPtr_
Protected Attributes inherited from fvMeshFunctionObject
const fvMesh & mesh_
Protected Attributes inherited from regionFunctionObject
word subRegistryName_
const objectRegistry & obr_
const objectRegistry * obrPtr_
Protected Attributes inherited from timeFunctionObject
const Time & time_
Detailed Description
Provides several methods to convert an input pressure field into derived forms, including:
static pressure
total pressure
isentropic pressure
static pressure coefficient
total pressure coefficient
where
= Density [kg/m3]
= Velocity [m/s]
= Freestream density [kg/m3]
= Freestream pressure [Pa]
= Freestream velocity [m/s]
= Kinematic pressure (p/rho)[m2/s2]
= Static pressure [Pa]
= Total pressure [Pa]
= Reference pressure level [Pa]
= Total isentropic pressure
= Pressure coefficient
= Total pressure coefficient
= Specific heat ratio
The function object will operate on both kinematic () and static pressure () fields.
Operands:
Operand Type Location
input volScalarField $FOAM_CASE/<time>/<inpField>
output file - -
output field volScalarField $FOAM_CASE/<time>/<outField>
Usage
Minimal example by using system/controlDict.functions:
pressure1
{
    // Mandatory entries (unmodifiable)
    type            pressure;
    libs            (fieldFunctionObjects);
    // Mandatory entries (runtime modifiable)
    mode            \<option\>;
    // Optional entries (runtime modifiable)
    field           \<pName\>;
    U               \<UName\>;
    rho             <rhoName>;
    rhoInf          1.0; // enabled if rho=rhoInf
    pRef            0.0;
    hydroStaticMode none;
    g               (0 -9.81 0); // enabled if hydroStaticMode != none
    hRef            0.0;         // enabled if hydroStaticMode != none
    pInf            0.0;
    UInf            (1 0 0);
    // Optional (inherited) entries
    ...
}
where the entries mean:
Property Description Type Req'd Dflt
type Type name: pressure word yes -
libs Library name: fieldFunctionObjects word yes -
mode Calculation mode (see below) word yes -
field Name of the pressure field word no p
U Name of the velocity field word no U
rho Name of the density field word no rho
rhoInf Freestream density for coefficient calculation
scalar
conditional -
pRef Reference pressure for total pressure scalar no 0
hydrostaticMode Hydrostatic contributions (see below) word no none
g Gravity vector (see below) vector no -
hRef Reference height (see below) scalar no -
pInf Freestream pressure for coefficient calculation scalar no -
UInf Freestream velocity for coefficient calculation vector no -
Options for the mode entry:
        static      | static pressure
        total       | total pressure
        isentropic  | isentropic pressure
        staticCoeff | static pressure coefficient
        totalCoeff  | total pressure coefficient
The optional hydrostaticMode entry provides handling for the term where options include
        none     | not included
        add      | add the term, e.g. to convert from p_rgh to p
        subtract | subtract the term, e.g. to convert from p to p_rgh
If the hydrostaticMode is active, values are also required for gravity, g, and reference height, hRef. By default these will be retrieved from the database. When these values are not available the user must provide them, e.g.
        g           (0 -9.81 0);
        hRef        0;
The inherited entries are elaborated in:
functionObject.H
fieldExpression.H
Usage by the postProcess utility is not available.
See also
Foam::functionObject
Foam::functionObjects::fieldExpression
Foam::functionObjects::fvMeshFunctionObject
ExtendedCodeGuide::functionObjects::field::pressure
Source files
pressure.H
pressure.C
Definition at line 345 of file pressure.H.
Member Enumeration Documentation
mode
enum mode : unsigned
Enumerator
STATIC
Static pressure.
TOTAL
Total pressure.
ISENTROPIC
Isentropic pressure.
COEFF
Coefficient manipulator.
STATIC_COEFF
TOTAL_COEFF
Definition at line 354 of file pressure.H.
hydrostaticMode
enum hydrostaticMode : unsigned
Enumerator
NONE
ADD
SUBTRACT
Definition at line 367 of file pressure.H.
Constructor & Destructor Documentation
pressure() [1/2]
pressure (const word & name, const Time & runTime, const dictionary & dict)
Definition at line 343 of file pressure.C.
References dict, and pressure::read().
pressure() [2/2]
pressure (const pressure &) delete
~pressure()
virtual ~pressure () virtual default
Member Function Documentation
TypeName()
TypeName ("pressure")
operator=()
void operator= (const pressure &) delete
read()
bool read (const dictionary & dict) virtual
Reimplemented from fieldExpression.
Definition at line 371 of file pressure.C.
References dict, Foam::endl(), Foam::Info, Foam::name(), Foam::nl, fieldExpression::read(), Foam::type(), and WarningInFunction.
Referenced by pressure::pressure().
Member Data Documentation
modeNames
const Foam::Enum< Foam::functionObjects::pressure::mode > modeNames static
Definition at line 364 of file pressure.H.
hydrostaticModeNames
const Foam::Enum< Foam::functionObjects::pressure::hydrostaticMode > hydrostaticModeNames static
Definition at line 374 of file pressure.H.
The documentation for this class was generated from the following files:
src/functionObjects/field/pressure/pressure.H
src/functionObjects/field/pressure/pressure.C