OpenFOAM: ReactingParcel< ParcelType > Class Template Reference
ReactingParcel< ParcelType > Class Template Reference
Lagrangian particle models » Parcels
Reacting parcel class with one/two-way coupling with the continuous phase.
#include <ReactingParcel.H>
Classes
class constantProperties
class iNew
class trackingData
Public Member Functions
TypeName ("ReactingParcel")
AddToPropertyList (ParcelType, " mass0"+" nPhases(Y1..YN)")
ReactingParcel (const polyMesh &mesh, const barycentric &coordinates, const label celli, const label tetFacei, const label tetPti)
ReactingParcel (const polyMesh &mesh, const vector &position, const label celli)
ReactingParcel (const polyMesh &mesh, const barycentric &coordinates, const label celli, const label tetFacei, const label tetPti, const label typeId, const scalar nParticle0, const scalar d0, const scalar dTarget0, const vector &U0, const vector &f0, const vector &angularMomentum0, const vector &torque0, const scalarField &Y0, const constantProperties &constProps)
ReactingParcel (const polyMesh &mesh, Istream &is, bool readFields=true, bool newFormat=true)
ReactingParcel (const ReactingParcel &p, const polyMesh &mesh)
ReactingParcel (const ReactingParcel &p)
virtual autoPtr< particle > clone () const
virtual autoPtr< particle > clone (const polyMesh &mesh) const
scalar mass0 () const
const scalarField & Y () const
const scalarField & YGas () const
const scalarField & YLiquid () const
const scalarField & YSolid () const
scalar & mass0 ()
scalarField & Y ()
template<class TrackCloudType >
void setCellValues (TrackCloudType &cloud, trackingData &td)
template<class TrackCloudType >
void cellValueSourceCorrection (TrackCloudType &cloud, trackingData &td, const scalar dt)
template<class TrackCloudType >
void correctSurfaceValues (TrackCloudType &cloud, trackingData &td, const scalar T, const scalarField &Cs, scalar &rhos, scalar &mus, scalar &Prs, scalar &kappas)
template<class TrackCloudType >
void calc (TrackCloudType &cloud, trackingData &td, const scalar dt)
void writeProperties (Ostream &os, const wordRes &filters, const word &delim, const bool namesOnly=false) const
template<class TrackCloudType >
Foam::scalar updatedDeltaVolume (TrackCloudType &cloud, const scalarField &dMass, const scalar p, const scalar T)
Static Public Member Functions
template<class CloudType , class CompositionType >
static void readFields (CloudType &c, const CompositionType &compModel)
template<class CloudType >
static void readFields (CloudType &c)
template<class CloudType , class CompositionType >
static void writeFields (const CloudType &c, const CompositionType &compModel)
template<class CloudType >
static void writeFields (const CloudType &c)
template<class CloudType >
static void readObjects (CloudType &c, const objectRegistry &obr)
template<class CloudType , class CompositionType >
static void readObjects (CloudType &c, const CompositionType &compModel, const objectRegistry &obr)
template<class CloudType >
static void writeObjects (const CloudType &c, objectRegistry &obr)
template<class CloudType , class CompositionType >
static void writeObjects (const CloudType &c, const CompositionType &compModel, objectRegistry &obr)
Static Public Attributes
static const std::size_t sizeofFields
Protected Member Functions
template<class TrackCloudType >
scalar updatedDeltaVolume (TrackCloudType &cloud, const scalarField &dMass, const scalar p, const scalar T)
template<class TrackCloudType >
void calcPhaseChange (TrackCloudType &cloud, trackingData &td, const scalar dt, const scalar Re, const scalar Pr, const scalar Ts, const scalar nus, const scalar d, const scalar T, const scalar mass, const scalar rho, const label idPhase, const scalar YPhase, const scalarField &YLiq, const scalarField &YSol, scalarField &dMassPC, scalar &Sh, scalar &N, scalar &NCpW, scalarField &Cs)
scalar updateMassFraction (const scalar mass0, const scalarField &dMass, scalarField &Y) const
Protected Attributes
scalar mass0_
scalarField Y_
Friends
Ostream & operator<< (Ostream &, const ReactingParcel< ParcelType > &)
Detailed Description
template<class ParcelType>
class Foam::ReactingParcel< ParcelType >
Reacting parcel class with one/two-way coupling with the continuous phase.
Source files
ReactingParcel.H
ReactingParcelI.H
ReactingParcel.C
ReactingParcelIO.C
Definition at line 67 of file ReactingParcel.H.
Constructor & Destructor Documentation
ReactingParcel() [1/6]
template<class ParcelType > ReactingParcel (const polyMesh & mesh, const barycentric & coordinates, const label celli, const label tetFacei, const label tetPti) inline
Definition at line 100 of file ReactingParcelI.H.
ReactingParcel() [2/6]
template<class ParcelType > ReactingParcel (const polyMesh & mesh, const vector & position, const label celli) inline
Definition at line 116 of file ReactingParcelI.H.
ReactingParcel() [3/6]
template<class ParcelType > ReactingParcel (const polyMesh & mesh, const barycentric & coordinates, const label celli, const label tetFacei, const label tetPti, const label typeId, const scalar nParticle0, const scalar d0, const scalar dTarget0, const vector & U0, const vector & f0, const vector & angularMomentum0, const vector & torque0, const scalarField & Y0, const constantProperties & constProps) inline
Definition at line 130 of file ReactingParcelI.H.
References ReactingParcel< ParcelType >::mass0_.
ReactingParcel() [4/6]
template<class ParcelType > ReactingParcel (const polyMesh & mesh, Istream & is, bool readFields = true, bool newFormat = true)
Definition at line 42 of file ReactingParcelIO.C.
References IOstreamOption::ASCII, FUNCTION_NAME, ReactingParcel< ParcelType >::mass0_, ReactingParcel< ParcelType >::readFields(), Foam::readFields(), ReactingParcel< ParcelType >::sizeofFields, List< T >::transfer(), and ReactingParcel< ParcelType >::Y_.
ReactingParcel() [5/6]
template<class ParcelType > ReactingParcel (const ReactingParcel< ParcelType > & p, const polyMesh & mesh)
ReactingParcel() [6/6]
template<class ParcelType > ReactingParcel (const ReactingParcel< ParcelType > & p)
Member Function Documentation
updatedDeltaVolume() [1/2]
template<class ParcelType > template<class TrackCloudType > scalar updatedDeltaVolume (TrackCloudType & cloud, const scalarField & dMass, const scalar p, const scalar T) protected
calcPhaseChange()
template<class ParcelType > template<class TrackCloudType > void calcPhaseChange (TrackCloudType & cloud, trackingData & td, const scalar dt, const scalar Re, const scalar Pr, const scalar Ts, const scalar nus, const scalar d, const scalar T, const scalar mass, const scalar rho, const label idPhase, const scalar YPhase, const scalarField & YLiq, const scalarField & YSol, scalarField & dMassPC, scalar & Sh, scalar & N, scalar & NCpW, scalarField & Cs) protected
Definition at line 57 of file ReactingParcel.C.
References composition, Cp, basicSpecieMixture::Cp(), Cs, forAll, Foam::min(), N(), Pr(), Foam::Re(), rho, Foam::constant::thermodynamic::RR, Foam::sum(), T, basicSpecieMixture::W(), and Y.
updateMassFraction()
template<class ParcelType > Foam::scalar updateMassFraction (const scalar mass0, const scalarField & dMass, scalarField & Y) const protected
Definition at line 178 of file ReactingParcel.C.
References forAll, Foam::sum(), and Y.
TypeName()
template<class ParcelType > TypeName ("ReactingParcel< ParcelType >")
AddToPropertyList()
template<class ParcelType > AddToPropertyList (ParcelType , " mass0"+" nPhases(Y1..YN)")
clone() [1/2]
template<class ParcelType > virtual autoPtr< particle > clone () const inline virtual
Definition at line 326 of file ReactingParcel.H.
clone() [2/2]
template<class ParcelType > virtual autoPtr< particle > clone (const polyMesh & mesh) const inline virtual
Definition at line 332 of file ReactingParcel.H.
References mesh.
mass0() [1/2]
template<class ParcelType > Foam::scalar mass0 () const inline
Definition at line 203 of file ReactingParcelI.H.
Y() [1/2]
template<class ParcelType > const Foam::scalarField & Y () const inline
Definition at line 210 of file ReactingParcelI.H.
YGas()
template<class ParcelType > const Foam::scalarField & YGas () const inline
Definition at line 217 of file ReactingParcelI.H.
YLiquid()
template<class ParcelType > const Foam::scalarField & YLiquid () const inline
Definition at line 225 of file ReactingParcelI.H.
YSolid()
template<class ParcelType > const Foam::scalarField & YSolid () const inline
Definition at line 233 of file ReactingParcelI.H.
mass0() [2/2]
template<class ParcelType > Foam::scalar & mass0 () inline
Definition at line 240 of file ReactingParcelI.H.
Y() [2/2]
template<class ParcelType > Foam::scalarField & Y () inline
Definition at line 247 of file ReactingParcelI.H.
setCellValues()
template<class ParcelType > template<class TrackCloudType > void setCellValues (TrackCloudType & cloud, trackingData & td)
Definition at line 231 of file ReactingParcel.C.
References coordinates(), Foam::endl(), Foam::nl, and WarningInFunction.
cellValueSourceCorrection()
template<class ParcelType > template<class TrackCloudType > void cellValueSourceCorrection (TrackCloudType & cloud, trackingData & td, const scalar dt)
Definition at line 261 of file ReactingParcel.C.
References Foam::endl(), forAll, Foam::mag(), Foam::max(), Foam::nl, WarningInFunction, and Y.
correctSurfaceValues()
template<class ParcelType > template<class TrackCloudType > void correctSurfaceValues (TrackCloudType & cloud, trackingData & td, const scalar T, const scalarField & Cs, scalar & rhos, scalar & mus, scalar & Prs, scalar & kappas)
Definition at line 317 of file ReactingParcel.C.
References Foam::cbrt(), Cs, forAll, Foam::max(), Foam::min(), Foam::constant::thermodynamic::RR, UPtrList< T >::size(), Foam::sqrt(), Foam::sum(), and T.
calc()
template<class ParcelType > template<class TrackCloudType > void calc (TrackCloudType & cloud, trackingData & td, const scalar dt)
Definition at line 409 of file ReactingParcel.C.
References Foam::cbrt(), composition, basicSpecieMixture::Cp(), Cs, forAll, basicSpecieMixture::Hs(), Foam::constant::mathematical::pi(), Foam::pow4(), Foam::Re(), rho0, UPtrList< T >::size(), basicMultiComponentMixture::species(), Su, T0, and Foam::Zero.
readFields() [1/2]
template<class ParcelType > template<class CloudType , class CompositionType > void readFields (CloudType & c, const CompositionType & compModel) static
Definition at line 96 of file ReactingParcelIO.C.
References forAll, IOobjectOption::MUST_READ, p, List< T >::setSize(), UPtrList< T >::size(), UList< T >::size(), and Y.
Referenced by ReactingParcel< ParcelType >::ReactingParcel().
readFields() [2/2]
template<class ParcelType > template<class CloudType > void readFields (CloudType & c) static
Definition at line 88 of file ReactingParcelIO.C.
writeFields() [1/2]
template<class ParcelType > template<class CloudType , class CompositionType > void writeFields (const CloudType & c, const CompositionType & compModel) static
Definition at line 171 of file ReactingParcelIO.C.
References forAll, IOobjectOption::NO_READ, p, UPtrList< T >::size(), UList< T >::size(), and Y.
writeFields() [2/2]
template<class ParcelType > template<class CloudType > void writeFields (const CloudType & c) static
Definition at line 163 of file ReactingParcelIO.C.
writeProperties()
template<class ParcelType > void writeProperties (Ostream & os, const wordRes & filters, const word & delim, const bool namesOnly = false) const
Definition at line 229 of file ReactingParcelIO.C.
References os(), and writeProp.
readObjects() [1/2]
template<class ParcelType > template<class CloudType > void readObjects (CloudType & c, const objectRegistry & obr) static
Definition at line 252 of file ReactingParcelIO.C.
readObjects() [2/2]
template<class ParcelType > template<class CloudType , class CompositionType > void readObjects (CloudType & c, const CompositionType & compModel, const objectRegistry & obr) static
Definition at line 276 of file ReactingParcelIO.C.
References forAll, p, UPtrList< T >::size(), UList< T >::size(), and Y.
writeObjects() [1/2]
template<class ParcelType > template<class CloudType > void writeObjects (const CloudType & c, objectRegistry & obr) static
Definition at line 264 of file ReactingParcelIO.C.
writeObjects() [2/2]
template<class ParcelType > template<class CloudType , class CompositionType > void writeObjects (const CloudType & c, const CompositionType & compModel, objectRegistry & obr) static
Definition at line 324 of file ReactingParcelIO.C.
References forAll, p, UPtrList< T >::size(), UList< T >::size(), and Y.
updatedDeltaVolume() [2/2]
template<class ParcelType > template<class TrackCloudType > Foam::scalar updatedDeltaVolume (TrackCloudType & cloud, const scalarField & dMass, const scalar p, const scalar T)
Definition at line 34 of file ReactingParcel.C.
References composition, forAll, p, PtrList< T >::PtrList(), UPtrList< T >::size(), Foam::sum(), T, and Foam::Zero.
Friends And Related Symbol Documentation
operator<<
template<class ParcelType > Ostream & operator<< (Ostream & , const ReactingParcel< ParcelType > &) friend
Member Data Documentation
sizeofFields
template<class ParcelType > const std::size_t sizeofFields static
Definition at line 74 of file ReactingParcel.H.
Referenced by ReactingParcel< ParcelType >::ReactingParcel().
mass0_
template<class ParcelType > scalar mass0_ protected
Definition at line 194 of file ReactingParcel.H.
Referenced by ReactingParcel< ParcelType >::ReactingParcel(), and ReactingParcel< ParcelType >::ReactingParcel().
Y_
template<class ParcelType > scalarField Y_ protected
Definition at line 197 of file ReactingParcel.H.
Referenced by ReactingParcel< ParcelType >::ReactingParcel().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/parcels/Templates/ReactingParcel/ReactingParcel.H
src/lagrangian/intermediate/parcels/Templates/ReactingParcel/ReactingParcel.C
src/lagrangian/intermediate/parcels/Templates/ReactingParcel/ReactingParcelI.H
src/lagrangian/intermediate/parcels/Templates/ReactingParcel/ReactingParcelIO.C