OpenFOAM: faDdtScheme< Type > Class Template Reference
faDdtScheme< Type > Class Template Reference abstract
#include <faDdtScheme.H>
Public Member Functions
virtual const word & type () const =0
declareRunTimeSelectionTable (tmp, faDdtScheme, Istream,(const faMesh &mesh, Istream &schemeData),(mesh, schemeData))
faDdtScheme (const faMesh &mesh)
faDdtScheme (const faMesh &mesh, Istream &)
virtual ~faDdtScheme ()
const faMesh & mesh () const
virtual tmp< GeometricField< Type, faPatchField, areaMesh > > facDdt (const dimensioned< Type >)=0
virtual tmp< GeometricField< Type, faPatchField, areaMesh > > facDdt0 (const dimensioned< Type >)=0
virtual tmp< GeometricField< Type, faPatchField, areaMesh > > facDdt (const GeometricField< Type, faPatchField, areaMesh > &)=0
virtual tmp< GeometricField< Type, faPatchField, areaMesh > > facDdt0 (const GeometricField< Type, faPatchField, areaMesh > &)=0
virtual tmp< GeometricField< Type, faPatchField, areaMesh > > facDdt (const dimensionedScalar &, const GeometricField< Type, faPatchField, areaMesh > &)=0
virtual tmp< GeometricField< Type, faPatchField, areaMesh > > facDdt0 (const dimensionedScalar &, const GeometricField< Type, faPatchField, areaMesh > &)=0
virtual tmp< GeometricField< Type, faPatchField, areaMesh > > facDdt (const areaScalarField &, const GeometricField< Type, faPatchField, areaMesh > &)=0
virtual tmp< GeometricField< Type, faPatchField, areaMesh > > facDdt0 (const areaScalarField &, const GeometricField< Type, faPatchField, areaMesh > &)=0
virtual tmp< faMatrix< Type > > famDdt (const GeometricField< Type, faPatchField, areaMesh > &)=0
virtual tmp< faMatrix< Type > > famDdt (const dimensionedScalar &, const GeometricField< Type, faPatchField, areaMesh > &)=0
virtual tmp< faMatrix< Type > > famDdt (const areaScalarField &, const GeometricField< Type, faPatchField, areaMesh > &)=0
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Static Public Member Functions
static tmp< faDdtScheme< Type > > New (const faMesh &mesh, Istream &schemeData)
Protected Member Functions
faDdtScheme (const faDdtScheme &)=delete
void operator= (const faDdtScheme &)=delete
Protected Attributes
const faMesh & mesh_
Detailed Description
template<class Type>
class Foam::fa::faDdtScheme< Type >
Definition at line 62 of file faDdtScheme.H.
Constructor & Destructor Documentation
faDdtScheme() [1/3]
template<class Type > faDdtScheme (const faDdtScheme< Type > &) protected delete
faDdtScheme() [2/3]
template<class Type > faDdtScheme (const faMesh & mesh) inline
Definition at line 104 of file faDdtScheme.H.
faDdtScheme() [3/3]
template<class Type > faDdtScheme (const faMesh & mesh, Istream &) inline
Definition at line 110 of file faDdtScheme.H.
~faDdtScheme()
template<class Type > ~faDdtScheme () virtual
Definition at line 82 of file faDdtScheme.C.
Member Function Documentation
operator=()
template<class Type > void operator= (const faDdtScheme< Type > &) protected delete
type()
template<class Type > virtual const word & type () const pure virtual
declareRunTimeSelectionTable()
template<class Type > declareRunTimeSelectionTable (tmp , faDdtScheme< Type > , Istream , (const faMesh &mesh, Istream &schemeData) , (mesh, schemeData))
New()
template<class Type > tmp< faDdtScheme< Type > > New (const faMesh & mesh, Istream & schemeData) static
Definition at line 38 of file faDdtScheme.C.
References Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, FatalIOErrorInLookup, InfoInFunction, mesh, and Foam::nl.
Referenced by Foam::fac::ddt(), Foam::fam::ddt(), Foam::fac::ddt(), Foam::fac::ddt(), Foam::fam::ddt(), Foam::fac::ddt(), and Foam::fam::ddt().
mesh()
template<class Type > const faMesh & mesh () const inline
Definition at line 133 of file faDdtScheme.H.
References faDdtScheme< Type >::mesh_.
Referenced by backwardFaDdtScheme< Type >::mesh(), boundedBackwardFaDdtScheme::mesh(), EulerFaDdtScheme< Type >::mesh(), and steadyStateFaDdtScheme< Type >::mesh().
facDdt() [1/4]
template<class Type > virtual tmp< GeometricField< Type, faPatchField, areaMesh > > facDdt (const dimensioned< Type >) pure virtual
Implemented in backwardFaDdtScheme< Type >, EulerFaDdtScheme< Type >, steadyStateFaDdtScheme< Type >, and boundedBackwardFaDdtScheme.
facDdt0() [1/4]
template<class Type > virtual tmp< GeometricField< Type, faPatchField, areaMesh > > facDdt0 (const dimensioned< Type >) pure virtual
Implemented in backwardFaDdtScheme< Type >, EulerFaDdtScheme< Type >, steadyStateFaDdtScheme< Type >, and boundedBackwardFaDdtScheme.
facDdt() [2/4]
template<class Type > virtual tmp< GeometricField< Type, faPatchField, areaMesh > > facDdt (const GeometricField< Type, faPatchField, areaMesh > &) pure virtual
Implemented in backwardFaDdtScheme< Type >, EulerFaDdtScheme< Type >, and steadyStateFaDdtScheme< Type >.
facDdt0() [2/4]
template<class Type > virtual tmp< GeometricField< Type, faPatchField, areaMesh > > facDdt0 (const GeometricField< Type, faPatchField, areaMesh > &) pure virtual
Implemented in backwardFaDdtScheme< Type >, EulerFaDdtScheme< Type >, and steadyStateFaDdtScheme< Type >.
facDdt() [3/4]
template<class Type > virtual tmp< GeometricField< Type, faPatchField, areaMesh > > facDdt (const dimensionedScalar & , const GeometricField< Type, faPatchField, areaMesh > &) pure virtual
Implemented in backwardFaDdtScheme< Type >, EulerFaDdtScheme< Type >, and steadyStateFaDdtScheme< Type >.
facDdt0() [3/4]
template<class Type > virtual tmp< GeometricField< Type, faPatchField, areaMesh > > facDdt0 (const dimensionedScalar & , const GeometricField< Type, faPatchField, areaMesh > &) pure virtual
Implemented in backwardFaDdtScheme< Type >, EulerFaDdtScheme< Type >, and steadyStateFaDdtScheme< Type >.
facDdt() [4/4]
template<class Type > virtual tmp< GeometricField< Type, faPatchField, areaMesh > > facDdt (const areaScalarField & , const GeometricField< Type, faPatchField, areaMesh > &) pure virtual
Implemented in backwardFaDdtScheme< Type >, EulerFaDdtScheme< Type >, and steadyStateFaDdtScheme< Type >.
facDdt0() [4/4]
template<class Type > virtual tmp< GeometricField< Type, faPatchField, areaMesh > > facDdt0 (const areaScalarField & , const GeometricField< Type, faPatchField, areaMesh > &) pure virtual
Implemented in backwardFaDdtScheme< Type >, EulerFaDdtScheme< Type >, and steadyStateFaDdtScheme< Type >.
famDdt() [1/3]
template<class Type > virtual tmp< faMatrix< Type > > famDdt (const GeometricField< Type, faPatchField, areaMesh > &) pure virtual
Implemented in backwardFaDdtScheme< Type >, EulerFaDdtScheme< Type >, and steadyStateFaDdtScheme< Type >.
famDdt() [2/3]
template<class Type > virtual tmp< faMatrix< Type > > famDdt (const dimensionedScalar & , const GeometricField< Type, faPatchField, areaMesh > &) pure virtual
Implemented in backwardFaDdtScheme< Type >, EulerFaDdtScheme< Type >, and steadyStateFaDdtScheme< Type >.
famDdt() [3/3]
template<class Type > virtual tmp< faMatrix< Type > > famDdt (const areaScalarField & , const GeometricField< Type, faPatchField, areaMesh > &) pure virtual
Implemented in backwardFaDdtScheme< Type >, EulerFaDdtScheme< Type >, and steadyStateFaDdtScheme< Type >.
Member Data Documentation
mesh_
template<class Type > const faMesh& mesh_ protected
Definition at line 71 of file faDdtScheme.H.
Referenced by faDdtScheme< Type >::mesh().
The documentation for this class was generated from the following files:
src/finiteArea/finiteArea/ddtSchemes/faDdtScheme/faDdtScheme.H
src/finiteArea/finiteArea/ddtSchemes/faDdtScheme/faDdtScheme.C