OpenFOAM: gaussGrad< Type > Class Template Reference
gaussGrad< Type > Class Template Reference
Numerics » Finite volume numerical schemes » Gradient schemes
Basic second-order gradient scheme using face-interpolation and Gauss' theorem.
#include <gaussGrad.H>
Public Member Functions
TypeName ("Gauss")
gaussGrad (const fvMesh &mesh)
gaussGrad (const fvMesh &mesh, Istream &is)
virtual tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > calcGrad (const GeometricField< Type, fvPatchField, volMesh > &vsf, const word &name) const
Public Member Functions inherited from gradScheme< Type >
virtual const word & type () const =0
declareRunTimeSelectionTable (tmp, gradScheme, Istream,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
gradScheme (const fvMesh &mesh)
virtual ~gradScheme ()=default
const fvMesh & mesh () const
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > grad (const GeometricField< Type, fvPatchField, volMesh > &, const word &name) const
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > grad (const GeometricField< Type, fvPatchField, volMesh > &) const
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > grad (const tmp< GeometricField< Type, fvPatchField, volMesh > > &) const
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Static Public Member Functions
static tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > gradf (const GeometricField< Type, fvsPatchField, surfaceMesh > &, const word &name)
static void correctBoundaryConditions (const GeometricField< Type, fvPatchField, volMesh > &, GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > &)
Static Public Member Functions inherited from gradScheme< Type >
static tmp< gradScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Detailed Description
template<class Type>
class Foam::fv::gaussGrad< Type >
Basic second-order gradient scheme using face-interpolation and Gauss' theorem.
Source files
gaussGrad.H
gaussGrad.C
Definition at line 59 of file gaussGrad.H.
Constructor & Destructor Documentation
gaussGrad() [1/2]
template<class Type > gaussGrad (const fvMesh & mesh) inline
Definition at line 87 of file gaussGrad.H.
gaussGrad() [2/2]
template<class Type > gaussGrad (const fvMesh & mesh, Istream & is) inline
Definition at line 94 of file gaussGrad.H.
References gradScheme< Type >::mesh(), and surfaceInterpolationScheme< Type >::New().
Member Function Documentation
TypeName()
template<class Type > TypeName ("Gauss")
gradf()
template<class Type > Foam::tmp< Foam::GeometricField< typename Foam::outerProduct< Foam::vector, Type >::type, Foam::fvPatchField, Foam::volMesh > > gradf (const GeometricField< Type, fvsPatchField, surfaceMesh > & ssf, const word & name) static
Definition at line 37 of file gaussGrad.C.
References Foam::dimLength, forAll, mesh, and Foam::name().
Referenced by Foam::fvc::grad().
calcGrad()
template<class Type > Foam::tmp< Foam::GeometricField< typename Foam::outerProduct< Foam::vector, Type >::type, Foam::fvPatchField, Foam::volMesh > > calcGrad (const GeometricField< Type, fvPatchField, volMesh > & vsf, const word & name) const virtual
Implements gradScheme< Type >.
Reimplemented in iterativeGaussGrad< Type >.
Definition at line 115 of file gaussGrad.C.
References correctBoundaryConditions(), interpolate(), and Foam::name().
correctBoundaryConditions()
template<class Type > void correctBoundaryConditions (const GeometricField< Type, fvPatchField, volMesh > & vsf, GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > & gGrad) static
Definition at line 137 of file gaussGrad.C.
References forAll, and n.
The documentation for this class was generated from the following files:
src/finiteVolume/finiteVolume/gradSchemes/gaussGrad/gaussGrad.H
src/finiteVolume/finiteVolume/gradSchemes/gaussGrad/gaussGrad.C