OpenFOAM: KinematicParcel< ParcelType > Class Template Reference
KinematicParcel< ParcelType > Class Template Reference
Lagrangian particle models » Parcels
Kinematic parcel class with rotational motion (as spherical particles only) and one/two-way coupling with the continuous phase.
#include <KinematicParcel.H>
Classes
class constantProperties
class iNew
class trackingData
Public Member Functions
TypeName ("KinematicParcel")
AddToPropertyList (ParcelType, " active"+" typeId"+" nParticle"+" d"+" dTarget"+" (Ux Uy Uz)"+" rho"+" age"+" tTurb"+" (UTurbx UTurby UTurbz)"+" (UCorrectx UCorrecty UCorrectz)")
KinematicParcel (const polyMesh &mesh, const barycentric &coordinates, const label celli, const label tetFacei, const label tetPti)
KinematicParcel (const polyMesh &mesh, const vector &position, const label celli)
KinematicParcel (const polyMesh &mesh, const barycentric &coordinates, const label celli, const label tetFacei, const label tetPti, const label typeId, const scalar nParticle0, const scalar d0, const scalar dTarget0, const vector &U0, const constantProperties &constProps)
KinematicParcel (const polyMesh &mesh, Istream &is, bool readFields=true, bool newFormat=true)
KinematicParcel (const KinematicParcel &p)
KinematicParcel (const KinematicParcel &p, const polyMesh &mesh)
virtual autoPtr< particle > clone () const
virtual autoPtr< particle > clone (const polyMesh &mesh) const
bool active () const
label typeId () const
scalar nParticle () const
scalar d () const
scalar dTarget () const
const vector & U () const
scalar rho () const
scalar age () const
scalar tTurb () const
const vector & UTurb () const
const vector & UCorrect () const
void active (const bool state)
label & typeId ()
scalar & nParticle ()
scalar & d ()
scalar & dTarget ()
vector & U ()
scalar & rho ()
scalar & age ()
scalar & tTurb ()
vector & UTurb ()
vector & UCorrect ()
scalar massCell (const trackingData &td) const
scalar mass () const
scalar momentOfInertia () const
scalar volume () const
scalar areaP () const
scalar areaS () const
scalar Re (const trackingData &td) const
scalar We (const trackingData &td, const scalar sigma) const
scalar Eo (const trackingData &td, const scalar sigma) const
template<class TrackCloudType >
void setCellValues (TrackCloudType &cloud, trackingData &td)
template<class TrackCloudType >
void calcDispersion (TrackCloudType &cloud, trackingData &td, const scalar dt)
template<class TrackCloudType >
void cellValueSourceCorrection (TrackCloudType &cloud, trackingData &td, const scalar dt)
template<class TrackCloudType >
void calc (TrackCloudType &cloud, trackingData &td, const scalar dt)
template<class TrackCloudType >
void calcUCorrection (TrackCloudType &cloud, trackingData &td, const scalar dt)
template<class TrackCloudType >
bool move (TrackCloudType &cloud, trackingData &td, const scalar trackTime)
template<class TrackCloudType >
bool hitPatch (TrackCloudType &cloud, trackingData &td)
template<class TrackCloudType >
void hitProcessorPatch (TrackCloudType &cloud, trackingData &td)
template<class TrackCloudType >
void hitWallPatch (TrackCloudType &cloud, trackingData &td)
virtual void transformProperties (const tensor &T)
virtual void transformProperties (const vector &separation)
void writeProperties (Ostream &os, const wordRes &filters, const word &delim, const bool namesOnly=false) const
template<class TrackCloudType >
const Foam::vector calcVelocity (TrackCloudType &cloud, trackingData &td, const scalar dt, const scalar Re, const scalar mu, const scalar mass, const vector &Su, vector &dUTrans, scalar &Spu) const
template<class CloudType >
void readFields (CloudType &c)
template<class CloudType >
void writeFields (const CloudType &c)
Static Public Member Functions
static scalar volume (const scalar d)
static scalar areaP (const scalar d)
static scalar areaS (const scalar d)
static scalar Re (const scalar rhoc, const vector &U, const vector &Uc, const scalar d, const scalar muc)
static scalar We (const scalar rhoc, const vector &U, const vector &Uc, const scalar d, const scalar sigma)
static scalar Eo (const vector &g, const scalar rho, const scalar rhoc, const vector &U, const scalar d, const scalar sigma)
template<class TrackCloudType >
static void readFields (TrackCloudType &c)
template<class TrackCloudType >
static void writeFields (const TrackCloudType &c)
template<class CloudType >
static void readObjects (CloudType &c, const objectRegistry &obr)
template<class CloudType >
static void writeObjects (const CloudType &c, objectRegistry &obr)
Static Public Attributes
static const std::size_t sizeofFields
Protected Member Functions
template<class TrackCloudType >
const vector calcVelocity (TrackCloudType &cloud, trackingData &td, const scalar dt, const scalar Re, const scalar mu, const scalar mass, const vector &Su, vector &dUTrans, scalar &Spu) const
Protected Attributes
label active_
label typeId_
scalar nParticle_
scalar d_
scalar dTarget_
vector U_
scalar rho_
scalar age_
scalar tTurb_
vector UTurb_
vector UCorrect_
Friends
Ostream & operator<< (Ostream &, const KinematicParcel< ParcelType > &)
Detailed Description
template<class ParcelType>
class Foam::KinematicParcel< ParcelType >
Kinematic parcel class with rotational motion (as spherical particles only) and one/two-way coupling with the continuous phase.
Sub-models include:
drag
turbulent dispersion
wall interactions
Source files
KinematicParcel.H
KinematicParcelI.H
KinematicParcel.C
KinematicParcelIO.C
Definition at line 81 of file KinematicParcel.H.
Constructor & Destructor Documentation
KinematicParcel() [1/6]
template<class ParcelType > KinematicParcel (const polyMesh & mesh, const barycentric & coordinates, const label celli, const label tetFacei, const label tetPti) inline
Definition at line 69 of file KinematicParcelI.H.
KinematicParcel() [2/6]
template<class ParcelType > KinematicParcel (const polyMesh & mesh, const vector & position, const label celli) inline
Definition at line 93 of file KinematicParcelI.H.
KinematicParcel() [3/6]
template<class ParcelType > KinematicParcel (const polyMesh & mesh, const barycentric & coordinates, const label celli, const label tetFacei, const label tetPti, const label typeId, const scalar nParticle0, const scalar d0, const scalar dTarget0, const vector & U0, const constantProperties & constProps) inline
Definition at line 115 of file KinematicParcelI.H.
KinematicParcel() [4/6]
template<class ParcelType > KinematicParcel (const polyMesh & mesh, Istream & is, bool readFields = true, bool newFormat = true)
Definition at line 45 of file KinematicParcelIO.C.
References KinematicParcel< ParcelType >::active_, KinematicParcel< ParcelType >::age_, IOstreamOption::ASCII, KinematicParcel< ParcelType >::d_, VectorSpace< Form, Cmpt, Ncmpts >::data(), KinematicParcel< ParcelType >::dTarget_, FUNCTION_NAME, VectorSpace< Form, Cmpt, Ncmpts >::nComponents, KinematicParcel< ParcelType >::nParticle_, Foam::readFields(), KinematicParcel< ParcelType >::readFields(), Foam::readRawLabel(), KinematicParcel< ParcelType >::rho_, KinematicParcel< ParcelType >::sizeofFields, KinematicParcel< ParcelType >::tTurb_, KinematicParcel< ParcelType >::typeId_, KinematicParcel< ParcelType >::U_, KinematicParcel< ParcelType >::UCorrect_, and KinematicParcel< ParcelType >::UTurb_.
KinematicParcel() [5/6]
template<class ParcelType > KinematicParcel (const KinematicParcel< ParcelType > & p)
KinematicParcel() [6/6]
template<class ParcelType > KinematicParcel (const KinematicParcel< ParcelType > & p, const polyMesh & mesh)
Member Function Documentation
calcVelocity() [1/2]
template<class ParcelType > template<class TrackCloudType > const vector calcVelocity (TrackCloudType & cloud, trackingData & td, const scalar dt, const scalar Re, const scalar mu, const scalar mass, const vector & Su, vector & dUTrans, scalar & Spu) const protected
TypeName()
template<class ParcelType > TypeName ("KinematicParcel< ParcelType >")
AddToPropertyList()
template<class ParcelType > AddToPropertyList (ParcelType , " active"+" typeId"+" nParticle"+" d"+" dTarget"+" (Ux Uy Uz)"+" rho"+" age"+" tTurb"+" (UTurbx UTurby UTurbz)"+" (UCorrectx UCorrecty UCorrectz)")
clone() [1/2]
template<class ParcelType > virtual autoPtr< particle > clone () const inline virtual
Definition at line 432 of file KinematicParcel.H.
clone() [2/2]
template<class ParcelType > virtual autoPtr< particle > clone (const polyMesh & mesh) const inline virtual
Definition at line 438 of file KinematicParcel.H.
References mesh.
active() [1/2]
template<class ParcelType > bool active () const inline
Definition at line 189 of file KinematicParcelI.H.
typeId() [1/2]
template<class ParcelType > Foam::label typeId () const inline
Definition at line 196 of file KinematicParcelI.H.
nParticle() [1/2]
template<class ParcelType > Foam::scalar nParticle () const inline
Definition at line 203 of file KinematicParcelI.H.
d() [1/2]
template<class ParcelType > Foam::scalar d () const inline
Definition at line 210 of file KinematicParcelI.H.
dTarget() [1/2]
template<class ParcelType > Foam::scalar dTarget () const inline
Definition at line 217 of file KinematicParcelI.H.
U() [1/2]
template<class ParcelType > const Foam::vector & U () const inline
Definition at line 224 of file KinematicParcelI.H.
rho() [1/2]
template<class ParcelType > Foam::scalar rho () const inline
Definition at line 231 of file KinematicParcelI.H.
age() [1/2]
template<class ParcelType > Foam::scalar age () const inline
Definition at line 238 of file KinematicParcelI.H.
tTurb() [1/2]
template<class ParcelType > Foam::scalar tTurb () const inline
Definition at line 245 of file KinematicParcelI.H.
UTurb() [1/2]
template<class ParcelType > const Foam::vector & UTurb () const inline
Definition at line 252 of file KinematicParcelI.H.
UCorrect() [1/2]
template<class ParcelType > const Foam::vector & UCorrect () const inline
Definition at line 301 of file KinematicParcelI.H.
active() [2/2]
template<class ParcelType > void active (const bool state) inline
Definition at line 259 of file KinematicParcelI.H.
typeId() [2/2]
template<class ParcelType > Foam::label & typeId () inline
Definition at line 266 of file KinematicParcelI.H.
nParticle() [2/2]
template<class ParcelType > Foam::scalar & nParticle () inline
Definition at line 273 of file KinematicParcelI.H.
d() [2/2]
template<class ParcelType > Foam::scalar & d () inline
Definition at line 280 of file KinematicParcelI.H.
dTarget() [2/2]
template<class ParcelType > Foam::scalar & dTarget () inline
Definition at line 287 of file KinematicParcelI.H.
U() [2/2]
template<class ParcelType > Foam::vector & U () inline
Definition at line 294 of file KinematicParcelI.H.
rho() [2/2]
template<class ParcelType > Foam::scalar & rho () inline
Definition at line 315 of file KinematicParcelI.H.
age() [2/2]
template<class ParcelType > Foam::scalar & age () inline
Definition at line 322 of file KinematicParcelI.H.
tTurb() [2/2]
template<class ParcelType > Foam::scalar & tTurb () inline
Definition at line 329 of file KinematicParcelI.H.
UTurb() [2/2]
template<class ParcelType > Foam::vector & UTurb () inline
Definition at line 336 of file KinematicParcelI.H.
UCorrect() [2/2]
template<class ParcelType > Foam::vector & UCorrect () inline
Definition at line 308 of file KinematicParcelI.H.
massCell()
template<class ParcelType > Foam::scalar massCell (const trackingData & td) const inline
Definition at line 343 of file KinematicParcelI.H.
References primitiveMesh::cellVolumes(), and mesh.
mass()
template<class ParcelType > Foam::scalar mass () const inline
Definition at line 353 of file KinematicParcelI.H.
momentOfInertia()
template<class ParcelType > Foam::scalar momentOfInertia () const inline
Definition at line 360 of file KinematicParcelI.H.
References Foam::sqr().
volume() [1/2]
template<class ParcelType > Foam::scalar volume () const inline
Definition at line 367 of file KinematicParcelI.H.
volume() [2/2]
template<class ParcelType > Foam::scalar volume (const scalar d) inline static
Definition at line 374 of file KinematicParcelI.H.
References Foam::constant::mathematical::pi(), and Foam::pow3().
areaP() [1/2]
template<class ParcelType > Foam::scalar areaP () const inline
Definition at line 381 of file KinematicParcelI.H.
areaP() [2/2]
template<class ParcelType > Foam::scalar areaP (const scalar d) inline static
Definition at line 388 of file KinematicParcelI.H.
areaS() [1/2]
template<class ParcelType > Foam::scalar areaS () const inline
Definition at line 395 of file KinematicParcelI.H.
areaS() [2/2]
template<class ParcelType > Foam::scalar areaS (const scalar d) inline static
Definition at line 402 of file KinematicParcelI.H.
References Foam::constant::mathematical::pi().
Re() [1/2]
template<class ParcelType > Foam::scalar Re (const trackingData & td) const inline
Definition at line 409 of file KinematicParcelI.H.
References Foam::Re().
Re() [2/2]
template<class ParcelType > Foam::scalar Re (const scalar rhoc, const vector & U, const vector & Uc, const scalar d, const scalar muc) inline static
Definition at line 419 of file KinematicParcelI.H.
References Foam::mag(), Foam::max(), and U.
We() [1/2]
template<class ParcelType > Foam::scalar We (const trackingData & td, const scalar sigma) const inline
Definition at line 433 of file KinematicParcelI.H.
We() [2/2]
template<class ParcelType > Foam::scalar We (const scalar rhoc, const vector & U, const vector & Uc, const scalar d, const scalar sigma) inline static
Definition at line 444 of file KinematicParcelI.H.
References Foam::magSqr(), Foam::max(), and U.
Eo() [1/2]
template<class ParcelType > Foam::scalar Eo (const trackingData & td, const scalar sigma) const inline
Definition at line 458 of file KinematicParcelI.H.
Eo() [2/2]
template<class ParcelType > Foam::scalar Eo (const vector & g, const scalar rho, const scalar rhoc, const vector & U, const scalar d, const scalar sigma) inline static
Definition at line 469 of file KinematicParcelI.H.
References g, Foam::mag(), Foam::max(), rho, Foam::sqr(), and U.
setCellValues()
template<class ParcelType > template<class TrackCloudType > void setCellValues (TrackCloudType & cloud, trackingData & td)
Definition at line 38 of file KinematicParcel.C.
References coordinates(), Foam::endl(), Foam::nl, and WarningInFunction.
calcDispersion()
template<class ParcelType > template<class TrackCloudType > void calcDispersion (TrackCloudType & cloud, trackingData & td, const scalar dt)
Definition at line 68 of file KinematicParcel.C.
cellValueSourceCorrection()
template<class ParcelType > template<class TrackCloudType > void cellValueSourceCorrection (TrackCloudType & cloud, trackingData & td, const scalar dt)
Definition at line 111 of file KinematicParcel.C.
calc()
template<class ParcelType > template<class TrackCloudType > void calc (TrackCloudType & cloud, trackingData & td, const scalar dt)
Definition at line 124 of file KinematicParcel.C.
References Foam::Re(), Su, and Foam::Zero.
calcUCorrection()
template<class ParcelType > template<class TrackCloudType > void calcUCorrection (TrackCloudType & cloud, trackingData & td, const scalar dt)
Definition at line 89 of file KinematicParcel.C.
References p, and Foam::Zero.
move()
template<class ParcelType > template<class TrackCloudType > bool move (TrackCloudType & cloud, trackingData & td, const scalar trackTime)
Definition at line 300 of file KinematicParcel.C.
References f(), Foam::mag(), Foam::max(), maxCo, Foam::min(), p, and s().
hitPatch()
template<class ParcelType > template<class TrackCloudType > bool hitPatch (TrackCloudType & cloud, trackingData & td)
Definition at line 395 of file KinematicParcel.C.
References polyPatch::constraintType(), DimensionedField< Type, GeoMesh >::mesh(), p, and pp().
hitProcessorPatch()
template<class ParcelType > template<class TrackCloudType > void hitProcessorPatch (TrackCloudType & cloud, trackingData & td)
Definition at line 438 of file KinematicParcel.C.
hitWallPatch()
template<class ParcelType > template<class TrackCloudType > void hitWallPatch (TrackCloudType & cloud, trackingData & td)
Definition at line 450 of file KinematicParcel.C.
transformProperties() [1/2]
template<class ParcelType > void transformProperties (const tensor & T) virtual
Definition at line 461 of file KinematicParcel.C.
References T, and Foam::transform().
transformProperties() [2/2]
template<class ParcelType > void transformProperties (const vector & separation) virtual
Definition at line 470 of file KinematicParcel.C.
readFields() [1/2]
template<class ParcelType > template<class TrackCloudType > static void readFields (TrackCloudType & c) static
Referenced by KinematicParcel< ParcelType >::KinematicParcel().
writeFields() [1/2]
template<class ParcelType > template<class TrackCloudType > static void writeFields (const TrackCloudType & c) static
writeProperties()
template<class ParcelType > void writeProperties (Ostream & os, const wordRes & filters, const word & delim, const bool namesOnly = false) const
Definition at line 277 of file KinematicParcelIO.C.
References os(), and writeProp.
readObjects()
template<class ParcelType > template<class CloudType > void readObjects (CloudType & c, const objectRegistry & obr) static
Definition at line 309 of file KinematicParcelIO.C.
References p, rho, UPtrList< T >::size(), and U.
writeObjects()
template<class ParcelType > template<class CloudType > void writeObjects (const CloudType & c, objectRegistry & obr) static
Definition at line 354 of file KinematicParcelIO.C.
References p, rho, UPtrList< T >::size(), and U.
calcVelocity() [2/2]
template<class ParcelType > template<class TrackCloudType > const Foam::vector calcVelocity (TrackCloudType & cloud, trackingData & td, const scalar dt, const scalar Re, const scalar mu, const scalar mass, const vector & Su, vector & dUTrans, scalar & Spu) const
Definition at line 177 of file KinematicParcel.C.
References Foam::meshTools::constrainDirection(), mesh, mu, p, Foam::Re(), polyMesh::solutionD(), and Su.
readFields() [2/2]
template<class ParcelType > template<class CloudType > void readFields (CloudType & c)
Definition at line 114 of file KinematicParcelIO.C.
References IOobjectOption::MUST_READ, p, rho, UPtrList< T >::size(), and U.
writeFields() [2/2]
template<class ParcelType > template<class CloudType > void writeFields (const CloudType & c)
Definition at line 220 of file KinematicParcelIO.C.
References IOobjectOption::NO_READ, p, rho, UPtrList< T >::size(), and U.
Friends And Related Symbol Documentation
operator<<
template<class ParcelType > Ostream & operator<< (Ostream & , const KinematicParcel< ParcelType > &) friend
Member Data Documentation
sizeofFields
template<class ParcelType > const std::size_t sizeofFields static
Definition at line 94 of file KinematicParcel.H.
Referenced by KinematicParcel< ParcelType >::KinematicParcel().
active_
template<class ParcelType > label active_ protected
Definition at line 302 of file KinematicParcel.H.
Referenced by KinematicParcel< ParcelType >::KinematicParcel().
typeId_
template<class ParcelType > label typeId_ protected
Definition at line 305 of file KinematicParcel.H.
Referenced by KinematicParcel< ParcelType >::KinematicParcel().
nParticle_
template<class ParcelType > scalar nParticle_ protected
Definition at line 308 of file KinematicParcel.H.
Referenced by KinematicParcel< ParcelType >::KinematicParcel().
d_
template<class ParcelType > scalar d_ protected
Definition at line 311 of file KinematicParcel.H.
Referenced by KinematicParcel< ParcelType >::KinematicParcel().
dTarget_
template<class ParcelType > scalar dTarget_ protected
Definition at line 314 of file KinematicParcel.H.
Referenced by KinematicParcel< ParcelType >::KinematicParcel().
U_
template<class ParcelType > vector U_ protected
Definition at line 317 of file KinematicParcel.H.
Referenced by KinematicParcel< ParcelType >::KinematicParcel().
rho_
template<class ParcelType > scalar rho_ protected
Definition at line 320 of file KinematicParcel.H.
Referenced by KinematicParcel< ParcelType >::KinematicParcel().
age_
template<class ParcelType > scalar age_ protected
Definition at line 323 of file KinematicParcel.H.
Referenced by KinematicParcel< ParcelType >::KinematicParcel().
tTurb_
template<class ParcelType > scalar tTurb_ protected
Definition at line 326 of file KinematicParcel.H.
Referenced by KinematicParcel< ParcelType >::KinematicParcel().
UTurb_
template<class ParcelType > vector UTurb_ protected
Definition at line 329 of file KinematicParcel.H.
Referenced by KinematicParcel< ParcelType >::KinematicParcel().
UCorrect_
template<class ParcelType > vector UCorrect_ protected
Definition at line 332 of file KinematicParcel.H.
Referenced by KinematicParcel< ParcelType >::KinematicParcel().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/parcels/Templates/KinematicParcel/KinematicParcel.H
src/lagrangian/intermediate/parcels/Templates/KinematicParcel/KinematicParcel.C
src/lagrangian/intermediate/parcels/Templates/KinematicParcel/KinematicParcelI.H
src/lagrangian/intermediate/parcels/Templates/KinematicParcel/KinematicParcelIO.C