OpenFOAM: DynamicID< ObjectType > Class Template Reference
DynamicID< ObjectType > Class Template Reference
A class that holds the data needed to identify things (zones, patches) in a dynamic mesh.
#include <DynamicID.H>
Public Member Functions
DynamicID (const wordRe &key, const ObjectType &obj)
DynamicID (wordRe &&key, const ObjectType &obj)
DynamicID (const word &key, const ObjectType &obj)
DynamicID (const keyType &key, const ObjectType &obj)
DynamicID (Istream &is, const ObjectType &obj)
~DynamicID ()=default
const wordRe & name () const noexcept
const labelList & indices () const noexcept
label index () const
bool active () const noexcept
void update (const ObjectType &obj)
Detailed Description
template<class ObjectType>
class Foam::DynamicID< ObjectType >
A class that holds the data needed to identify things (zones, patches) in a dynamic mesh.
The thing is identified by name. Its indices are updated if the mesh has changed.
Definition at line 48 of file DynamicID.H.
Constructor & Destructor Documentation
DynamicID() [1/5]
template<class ObjectType > DynamicID (const wordRe & key, const ObjectType & obj) inline
Definition at line 64 of file DynamicID.H.
DynamicID() [2/5]
template<class ObjectType > DynamicID (wordRe && key, const ObjectType & obj) inline
Definition at line 71 of file DynamicID.H.
DynamicID() [3/5]
template<class ObjectType > DynamicID (const word & key, const ObjectType & obj) inline
Definition at line 78 of file DynamicID.H.
DynamicID() [4/5]
template<class ObjectType > DynamicID (const keyType & key, const ObjectType & obj) inline
Definition at line 84 of file DynamicID.H.
DynamicID() [5/5]
template<class ObjectType > DynamicID (Istream & is, const ObjectType & obj) inline
Definition at line 90 of file DynamicID.H.
~DynamicID()
template<class ObjectType > ~DynamicID () default
Member Function Documentation
name()
template<class ObjectType > const wordRe & name () const inline noexcept
Definition at line 105 of file DynamicID.H.
indices()
template<class ObjectType > const labelList & indices () const inline noexcept
Definition at line 111 of file DynamicID.H.
index()
template<class ObjectType > label index () const inline
Definition at line 117 of file DynamicID.H.
References UList< T >::empty(), and UList< T >::first().
active()
template<class ObjectType > bool active () const inline noexcept
Definition at line 123 of file DynamicID.H.
References UList< T >::empty().
update()
template<class ObjectType > void update (const ObjectType & obj) inline
Definition at line 132 of file DynamicID.H.
The documentation for this class was generated from the following file:
src/OpenFOAM/meshes/Identifiers/DynamicID/DynamicID.H