OpenFOAM: indexedOctree< Type > Class Template Reference
indexedOctree< Type > Class Template Reference
Non-pointer based hierarchical recursive searching.
#include <indexedOctree.H>
Public Member Functions
indexedOctree (const Type &shapes)
indexedOctree (const Type &shapes, const List< node > &nodes, const List< labelList > &contents)
indexedOctree (const Type &shapes, const treeBoundBox &bb, const label maxLevels, const scalar maxLeafRatio, const scalar maxDuplicity)
indexedOctree (const Type &shapes, Istream &is)
autoPtr< indexedOctree< Type > > clone () const
const Type & shapes () const noexcept
const List< node > & nodes () const noexcept
const List< labelList > & contents () const noexcept
PackedList< 2 > & nodeTypes () const noexcept
const treeBoundBox & bb () const
label nLeafs () const
pointIndexHit findNearest (const point &sample, const scalar nearestDistSqr) const
template<class FindNearestOp >
pointIndexHit findNearest (const point &sample, const scalar nearestDistSqr, const FindNearestOp &fnOp) const
template<class FindNearestOp >
void findNearest (const label nodeI, const point &, scalar &nearestDistSqr, label &nearestShapeI, point &nearestPoint, const FindNearestOp &fnOp) const
pointIndexHit findNearest (const linePointRef &ln, treeBoundBox &tightest, point &linePoint) const
template<class FindNearestOp >
pointIndexHit findNearest (const linePointRef &ln, treeBoundBox &tightest, point &linePoint, const FindNearestOp &fnOp) const
pointIndexHit findLine (const point &start, const point &end) const
pointIndexHit findLineAny (const point &start, const point &end) const
template<class FindIntersectOp >
pointIndexHit findLine (const point &start, const point &end, const FindIntersectOp &fiOp) const
template<class FindIntersectOp >
pointIndexHit findLineAny (const point &start, const point &end, const FindIntersectOp &fiOp) const
bool overlaps (const treeBoundBox &bb) const
labelList findBox (const treeBoundBox &bb) const
label findBox (const treeBoundBox &bb, labelHashSet &elements) const
bool overlaps (const point &centre, const scalar radiusSqr) const
labelList findSphere (const point &centre, const scalar radiusSqr) const
label findSphere (const point &centre, const scalar radiusSqr, labelHashSet &elements) const
labelBits findNode (const label nodeI, const point &) const
label findInside (const point &) const
const labelList & findIndices (const point &) const
volumeType getVolumeType (const point &) const
template<class CompareOp >
void findNear (const scalar nearDist, const indexedOctree< Type > &tree2, CompareOp &cop) const
void writeOBJ (Ostream &os) const
void print (prefixOSstream &, const bool printContents, const label) const
bool write (Ostream &os) const
template<class FindIntersectOp >
Foam::pointIndexHit findLine (const bool findAny, const point &treeStart, const point &treeEnd, const label startNodeI, const direction startOctant, const FindIntersectOp &fiOp, const bool verbose) const
template<class FindIntersectOp >
Foam::pointIndexHit findLine (const bool findAny, const point &start, const point &end, const FindIntersectOp &fiOp) const
template<class FindNearestOp >
Foam::pointIndexHit findNearest (const point &sample, const scalar startDistSqr, const FindNearestOp &fnOp) const
template<class FindNearestOp >
Foam::pointIndexHit findNearest (const linePointRef &ln, treeBoundBox &tightest, point &linePoint, const FindNearestOp &fnOp) const
template<class FindIntersectOp >
Foam::pointIndexHit findLine (const point &start, const point &end, const FindIntersectOp &fiOp) const
template<class FindIntersectOp >
Foam::pointIndexHit findLineAny (const point &start, const point &end, const FindIntersectOp &fiOp) const
Public Member Functions inherited from indexedOctreeBase
ClassName ("indexedOctree")
indexedOctreeBase ()=default
Static Public Member Functions
static volumeType getSide (const vector &outsideNormal, const vector &vec)
Static Public Member Functions inherited from indexedOctreeBase
static bool isEmpty (labelBits i) noexcept
static bool isContent (labelBits i) noexcept
static bool isNode (labelBits i) noexcept
static label getContent (labelBits i)
static label getNode (const labelBits i)
static direction getOctant (labelBits i) noexcept
static scalar & perturbTol () noexcept
static scalar perturbTol (scalar tol) noexcept
static void writeOBJ (Ostream &os, const treeBoundBox &bb, label &vertIndex, const bool writeLinesOnly=false)
Friends
Ostream & operator<< (Ostream &, const indexedOctree< Type > &)
Additional Inherited Members
Static Protected Member Functions inherited from indexedOctreeBase
static labelBits emptyPlusOctant (direction octant)
static labelBits contentPlusOctant (label i, direction octant)
static labelBits nodePlusOctant (label i, direction octant)
Static Protected Attributes inherited from indexedOctreeBase
static scalar perturbTol_ = 10*SMALL
Detailed Description
template<class Type>
class Foam::indexedOctree< Type >
Non-pointer based hierarchical recursive searching.
Source files
indexedOctree.H
indexedOctree.C
Definition at line 254 of file indexedOctree.H.
Constructor & Destructor Documentation
indexedOctree() [1/4]
template<class Type > indexedOctree (const Type & shapes)
Definition at line 2111 of file indexedOctree.C.
indexedOctree() [2/4]
template<class Type > indexedOctree (const Type & shapes, const List< node > & nodes, const List< labelList > & contents)
Definition at line 2121 of file indexedOctree.C.
indexedOctree() [3/4]
template<class Type > indexedOctree (const Type & shapes, const treeBoundBox & bb, const label maxLevels, const scalar maxLeafRatio, const scalar maxDuplicity)
Definition at line 2136 of file indexedOctree.C.
References indexedOctree< Type >::bb(), PtrList< T >::clear(), indexedOctree< Type >::contents(), Foam::endl(), Foam::identity(), Foam::max(), Foam::min(), Foam::nl, indexedOctree< Type >::nodes(), Foam::Pout, PtrList< T >::push_back(), List< T >::setSize(), indexedOctree< Type >::shapes(), UPtrList< T >::size(), memInfo::size(), UList< T >::size(), and List< T >::transfer().
indexedOctree() [4/4]
template<class Type > indexedOctree (const Type & shapes, Istream & is)
Definition at line 2315 of file indexedOctree.C.
Member Function Documentation
clone()
template<class Type > autoPtr< indexedOctree< Type > > clone () const inline
Definition at line 534 of file indexedOctree.H.
References Foam::New().
shapes()
template<class Type > const Type & shapes () const inline noexcept
Definition at line 545 of file indexedOctree.H.
Referenced by indexedOctree< Type >::indexedOctree().
nodes()
template<class Type > const List< node > & nodes () const inline noexcept
Definition at line 548 of file indexedOctree.H.
Referenced by indexedOctree< Type >::indexedOctree().
contents()
template<class Type > const List< labelList > & contents () const inline noexcept
Definition at line 552 of file indexedOctree.H.
Referenced by indexedOctree< Type >::indexedOctree().
nodeTypes()
template<class Type > PackedList< 2 > & nodeTypes () const inline noexcept
Definition at line 558 of file indexedOctree.H.
bb()
template<class Type > const treeBoundBox & bb () const inline
Definition at line 564 of file indexedOctree.H.
References UPtrList< T >::empty(), and treeBoundBox::null().
Referenced by indexedOctree< Type >::indexedOctree().
nLeafs()
template<class Type > Foam::label nLeafs () const
Definition at line 2882 of file indexedOctree.C.
References UPtrList< T >::size().
findNearest() [1/7]
template<class Type > Foam::pointIndexHit findNearest (const point & sample, const scalar nearestDistSqr) const
Definition at line 2331 of file indexedOctree.C.
findNearest() [2/7]
template<class Type > template<class FindNearestOp > pointIndexHit findNearest (const point & sample, const scalar nearestDistSqr, const FindNearestOp & fnOp) const
findNearest() [3/7]
template<class Type > template<class FindNearestOp > void findNearest (const label nodeI, const point & sample, scalar & nearestDistSqr, label & nearestShapeI, point & nearestPoint, const FindNearestOp & fnOp) const
Definition at line 389 of file indexedOctree.C.
findNearest() [4/7]
template<class Type > Foam::pointIndexHit findNearest (const linePointRef & ln, treeBoundBox & tightest, point & linePoint) const
Definition at line 2380 of file indexedOctree.C.
References Foam::ln().
findNearest() [5/7]
template<class Type > template<class FindNearestOp > pointIndexHit findNearest (const linePointRef & ln, treeBoundBox & tightest, point & linePoint, const FindNearestOp & fnOp) const
findLine() [1/5]
template<class Type > Foam::pointIndexHit findLine (const point & start, const point & end) const
Definition at line 2432 of file indexedOctree.C.
findLineAny() [1/3]
template<class Type > Foam::pointIndexHit findLineAny (const point & start, const point & end) const
Definition at line 2449 of file indexedOctree.C.
findLine() [2/5]
template<class Type > template<class FindIntersectOp > pointIndexHit findLine (const point & start, const point & end, const FindIntersectOp & fiOp) const
findLineAny() [2/3]
template<class Type > template<class FindIntersectOp > pointIndexHit findLineAny (const point & start, const point & end, const FindIntersectOp & fiOp) const
overlaps() [1/2]
template<class Type > bool overlaps (const treeBoundBox & bb) const
Definition at line 2492 of file indexedOctree.C.
References UPtrList< T >::empty().
findBox() [1/2]
template<class Type > Foam::labelList findBox (const treeBoundBox & bb) const
Parameters
bb bound box limits
Definition at line 2529 of file indexedOctree.C.
References HashTable< T, Key, Hash >::toc().
findBox() [2/2]
template<class Type > Foam::label findBox (const treeBoundBox & bb, labelHashSet & elements) const
Parameters
bb bound box limits
[out] elements elements found
Definition at line 2503 of file indexedOctree.C.
References HashTable< T, Key, Hash >::capacity(), HashTable< T, Key, Hash >::clear(), Foam::max(), HashTable< T, Key, Hash >::resize(), and HashTable< T, Key, Hash >::size().
overlaps() [2/2]
template<class Type > bool overlaps (const point & centre, const scalar radiusSqr) const
Parameters
centre centre of bound sphere
radiusSqr radius^2 of sphere
Definition at line 2549 of file indexedOctree.C.
References UPtrList< T >::empty().
findSphere() [1/2]
template<class Type > Foam::labelList findSphere (const point & centre, const scalar radiusSqr) const
Parameters
centre centre of bound sphere
radiusSqr radius^2 of sphere
Definition at line 2589 of file indexedOctree.C.
References HashTable< T, Key, Hash >::toc().
findSphere() [2/2]
template<class Type > Foam::label findSphere (const point & centre, const scalar radiusSqr, labelHashSet & elements) const
Parameters
centre centre of bound sphere
radiusSqr radius^2 of sphere
[out] elements elements found
Definition at line 2561 of file indexedOctree.C.
References HashTable< T, Key, Hash >::capacity(), HashTable< T, Key, Hash >::clear(), Foam::max(), HashTable< T, Key, Hash >::resize(), and HashTable< T, Key, Hash >::size().
findNode()
template<class Type > Foam::labelBits findNode (const label nodeI, const point & sample) const
Definition at line 2610 of file indexedOctree.C.
findInside()
template<class Type > Foam::label findInside (const point & sample) const
Definition at line 2647 of file indexedOctree.C.
References forAll, and Foam::getOctant().
findIndices()
template<class Type > const Foam::labelList & findIndices (const point & sample) const
Definition at line 2681 of file indexedOctree.C.
References Foam::getOctant(), and List< label >::null().
getVolumeType()
template<class Type > Foam::volumeType getVolumeType (const point & sample) const
Definition at line 2708 of file indexedOctree.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, volumeType::INSIDE, volumeType::MIXED, volumeType::OUTSIDE, Foam::Pout, Foam::type(), and volumeType::UNKNOWN.
getSide()
template<class Type > Foam::volumeType getSide (const vector & outsideNormal, const vector & vec) static
Definition at line 370 of file indexedOctree.C.
References volumeType::INSIDE, and volumeType::OUTSIDE.
Referenced by treeDataFace::getVolumeType(), and treeDataPrimitivePatch< PatchType >::getVolumeType().
findNear()
template<class Type > template<class CompareOp > void findNear (const scalar nearDist, const indexedOctree< Type > & tree2, CompareOp & cop) const
Definition at line 2778 of file indexedOctree.C.
writeOBJ()
template<class Type > void writeOBJ (Ostream & os) const
Definition at line 2097 of file indexedOctree.C.
References os().
print()
template<class Type > void print (prefixOSstream & os, const bool printContents, const label nodeI) const
Definition at line 2804 of file indexedOctree.C.
References Foam::endl(), forAll, Foam::nl, os(), UList< T >::size(), and treeBoundBox::subBbox().
write()
template<class Type > bool write (Ostream & os) const
Definition at line 2895 of file indexedOctree.C.
References IOstream::good(), and os().
findLine() [3/5]
template<class Type > template<class FindIntersectOp > Foam::pointIndexHit findLine (const bool findAny, const point & treeStart, const point & treeEnd, const label startNodeI, const direction startOctant, const FindIntersectOp & fiOp, const bool verbose) const
Definition at line 1414 of file indexedOctree.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, Foam::nl, Foam::Pout, and WarningInFunction.
findLine() [4/5]
template<class Type > template<class FindIntersectOp > Foam::pointIndexHit findLine (const bool findAny, const point & start, const point & end, const FindIntersectOp & fiOp) const
Definition at line 1606 of file indexedOctree.C.
References Foam::getOctant(), and Foam::Zero.
findNearest() [6/7]
template<class Type > template<class FindNearestOp > Foam::pointIndexHit findNearest (const point & sample, const scalar startDistSqr, const FindNearestOp & fnOp) const
Definition at line 2348 of file indexedOctree.C.
References Foam::Zero.
findNearest() [7/7]
template<class Type > template<class FindNearestOp > Foam::pointIndexHit findNearest (const linePointRef & ln, treeBoundBox & tightest, point & linePoint, const FindNearestOp & fnOp) const
Definition at line 2399 of file indexedOctree.C.
References Foam::ln(), and Foam::Zero.
findLine() [5/5]
template<class Type > template<class FindIntersectOp > Foam::pointIndexHit findLine (const point & start, const point & end, const FindIntersectOp & fiOp) const
Definition at line 2467 of file indexedOctree.C.
findLineAny() [3/3]
template<class Type > template<class FindIntersectOp > Foam::pointIndexHit findLineAny (const point & start, const point & end, const FindIntersectOp & fiOp) const
Definition at line 2480 of file indexedOctree.C.
Friends And Related Symbol Documentation
operator<<
template<class Type > Ostream & operator<< (Ostream & , const indexedOctree< Type > &) friend
The documentation for this class was generated from the following files:
src/meshTools/indexedOctree/treeDataPrimitivePatch.H
src/OpenFOAM/algorithms/indexedOctree/indexedOctree.H
src/OpenFOAM/algorithms/indexedOctree/indexedOctree.C