OpenFOAM: deferredCorrection< Type > Class Template Reference
deferredCorrection< Type > Class Template Reference
Deferred correction interpolation scheme wrapper around a run-time selectable base scheme.
#include <deferredCorrection.H>
Public Member Functions
TypeName ("deferredCorrection")
deferredCorrection (const fvMesh &mesh, Istream &is)
deferredCorrection (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &is)
virtual bool corrected () const
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > &) const
Public Member Functions inherited from upwind< Type >
TypeName ("upwind")
upwind (const fvMesh &mesh, const surfaceScalarField &faceFlux)
upwind (const fvMesh &mesh, Istream &is)
upwind (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &)
virtual tmp< surfaceScalarField > limiter (const GeometricField< Type, fvPatchField, volMesh > &) const
tmp< surfaceScalarField > weights () const
virtual tmp< surfaceScalarField > weights (const GeometricField< Type, fvPatchField, volMesh > &) const
Public Member Functions inherited from limitedSurfaceInterpolationScheme< Type >
TypeName ("limitedSurfaceInterpolationScheme")
declareRunTimeSelectionTable (tmp, limitedSurfaceInterpolationScheme, Mesh,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
declareRunTimeSelectionTable (tmp, limitedSurfaceInterpolationScheme, MeshFlux,(const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
limitedSurfaceInterpolationScheme (const fvMesh &mesh, const surfaceScalarField &faceFlux)
limitedSurfaceInterpolationScheme (const fvMesh &mesh, Istream &is)
virtual ~limitedSurfaceInterpolationScheme ()
tmp< surfaceScalarField > weights (const GeometricField< Type, fvPatchField, volMesh > &, const surfaceScalarField &CDweights, tmp< surfaceScalarField > tLimiter) const
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const GeometricField< Type, fvPatchField, volMesh > &) const
Public Member Functions inherited from surfaceInterpolationScheme< Type >
TypeName ("surfaceInterpolationScheme")
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, Mesh,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, MeshFlux,(const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
surfaceInterpolationScheme (const fvMesh &mesh)
virtual ~surfaceInterpolationScheme ()=default
const fvMesh & mesh () const
virtual tmp< GeometricField< typename innerProduct< vector, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf) const
tmp< GeometricField< typename innerProduct< vector, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const tmp< GeometricField< Type, fvPatchField, volMesh > > &) const
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &) const
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > &) const
template<class SFType >
Foam::tmp< Foam::GeometricField< typename Foam::innerProduct< typename SFType::value_type, Type >::type, Foam::fvsPatchField, Foam::surfaceMesh > > dotInterpolate (const SFType &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf, const tmp< surfaceScalarField > &tlambdas)
tmp< GeometricField< typename innerProduct< vector, scalar >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const GeometricField< scalar, fvPatchField, volMesh > &) const
Foam::tmp< Foam::GeometricField< typename Foam::innerProduct< Foam::vector, Foam::scalar >::type, Foam::fvsPatchField, Foam::surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const GeometricField< scalar, fvPatchField, volMesh > &) const
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Additional Inherited Members
Static Public Member Functions inherited from limitedSurfaceInterpolationScheme< Type >
static tmp< limitedSurfaceInterpolationScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
static tmp< limitedSurfaceInterpolationScheme< Type > > New (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData)
Static Public Member Functions inherited from surfaceInterpolationScheme< Type >
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData)
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &, const tmp< surfaceScalarField > &)
template<class SFType >
static tmp< GeometricField< typename innerProduct< typename SFType::value_type, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const SFType &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf, const tmp< surfaceScalarField > &tlambdas)
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &)
Protected Attributes inherited from limitedSurfaceInterpolationScheme< Type >
const surfaceScalarField & faceFlux_
Detailed Description
template<class Type>
class Foam::deferredCorrection< Type >
Deferred correction interpolation scheme wrapper around a run-time selectable base scheme.
The characteristics of the base scheme are recovered by applying an explicit correction to the upwind scheme weights.
Usage
Example of the deferredCorrection scheme applied to the linear scheme:
divSchemes
{
    .
    .
    div(phi,U)      Gauss deferredCorrection linear;
    .
    .
}
Source files
deferredCorrection.H
deferredCorrection.C
See also
Foam::upwind
Definition at line 68 of file deferredCorrection.H.
Constructor & Destructor Documentation
deferredCorrection() [1/2]
template<class Type > deferredCorrection (const fvMesh & mesh, Istream & is) inline
Definition at line 98 of file deferredCorrection.H.
deferredCorrection() [2/2]
template<class Type > deferredCorrection (const fvMesh & mesh, const surfaceScalarField & faceFlux, Istream & is) inline
Definition at line 112 of file deferredCorrection.H.
Member Function Documentation
TypeName()
template<class Type > TypeName ("deferredCorrection< Type >")
corrected()
template<class Type > virtual bool corrected () const inline virtual
Reimplemented from surfaceInterpolationScheme< Type >.
Definition at line 132 of file deferredCorrection.H.
correction()
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > & vf) const virtual
Reimplemented from surfaceInterpolationScheme< Type >.
Definition at line 27 of file deferredCorrection.C.
References surfaceInterpolationScheme< Type >::interpolate(), Foam::interpolate(), and PtrList< T >::PtrList().
The documentation for this class was generated from the following files:
src/finiteVolume/interpolation/surfaceInterpolation/schemes/deferredCorrection/deferredCorrection.H
src/finiteVolume/interpolation/surfaceInterpolation/schemes/deferredCorrection/deferredCorrection.C