OpenFOAM: specularRadiationMixedFvPatchScalarField Class Reference
specularRadiationMixedFvPatchScalarField Class Reference
This boundary condition provides a specular radiation condition for axisymmetric and symmetry-plane fvDOM computations.
#include <specularRadiationMixedFvPatchScalarField.H>
Public Member Functions
TypeName ("specularRadiation")
specularRadiationMixedFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
specularRadiationMixedFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
specularRadiationMixedFvPatchScalarField (const specularRadiationMixedFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
specularRadiationMixedFvPatchScalarField (const specularRadiationMixedFvPatchScalarField &)
virtual tmp< fvPatchField< scalar > > clone () const
specularRadiationMixedFvPatchScalarField (const specularRadiationMixedFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchField< scalar > > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
This boundary condition provides a specular radiation condition for axisymmetric and symmetry-plane fvDOM computations.
References:
    Standard model (tag:KE):
        Kumar, P., & Eswaran, V. (2013).
        A methodology to solve 2D and axisymmetric radiative
        transfer problems using a general 3D solver.
        Journal of heat transfer, 135(12).
        DOI:10.1115/1.4024674
Usage
Example of the boundary condition specification:
<patchName>
{
    // Mandatory entries
    type                specularRadiation;
    // Optional entries
    interpolate         <bool>;
    // Inherited entries
    patchType           <word>;
    ...
}
where the entries mean:
Property Description Type Reqd Deflt
type Type name: turbulentDigitalFilterInlet word yes -
interpolate Flag to enable ray-intensity interp bool no false
The inherited entries are elaborated in:
mixedFvPatchFields.H
Note
The condition is limited to the underlying wedge and symmetryPlane conditions.
Source files
specularRadiationMixedFvPatchScalarField.H
specularRadiationMixedFvPatchScalarField.C
Definition at line 108 of file specularRadiationMixedFvPatchScalarField.H.
Constructor & Destructor Documentation
specularRadiationMixedFvPatchScalarField() [1/5]
specularRadiationMixedFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 279 of file specularRadiationMixedFvPatchScalarField.C.
References Foam::Zero.
specularRadiationMixedFvPatchScalarField() [2/5]
specularRadiationMixedFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 315 of file specularRadiationMixedFvPatchScalarField.C.
References dict, Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::nl, fvPatchField< scalar >::operator=(), p, and Foam::Zero.
specularRadiationMixedFvPatchScalarField() [3/5]
specularRadiationMixedFvPatchScalarField (const specularRadiationMixedFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 298 of file specularRadiationMixedFvPatchScalarField.C.
specularRadiationMixedFvPatchScalarField() [4/5]
specularRadiationMixedFvPatchScalarField (const specularRadiationMixedFvPatchScalarField & ptf)
Definition at line 374 of file specularRadiationMixedFvPatchScalarField.C.
specularRadiationMixedFvPatchScalarField() [5/5]
specularRadiationMixedFvPatchScalarField (const specularRadiationMixedFvPatchScalarField & ptf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 359 of file specularRadiationMixedFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("specularRadiation")
clone() [1/2]
virtual tmp< fvPatchField< scalar > > clone () const inline virtual
Definition at line 186 of file specularRadiationMixedFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchField< scalar > > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 202 of file specularRadiationMixedFvPatchScalarField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 390 of file specularRadiationMixedFvPatchScalarField.C.
write()
void write (Ostream & os) const virtual
Definition at line 441 of file specularRadiationMixedFvPatchScalarField.C.
References os().
The documentation for this class was generated from the following files:
src/thermophysicalModels/radiation/derivedFvPatchFields/specularRadiation/specularRadiationMixedFvPatchScalarField.H
src/thermophysicalModels/radiation/derivedFvPatchFields/specularRadiation/specularRadiationMixedFvPatchScalarField.C