OpenFOAM: InterfaceCompositionPhaseChangePhaseSystem< BasePhaseSystem > Class Template Reference
InterfaceCompositionPhaseChangePhaseSystem< BasePhaseSystem > Class Template Reference
Class to provide interfacial heat and mass transfer between a number of phases according to a interface composition model.
#include <InterfaceCompositionPhaseChangePhaseSystem.H>
Public Member Functions
InterfaceCompositionPhaseChangePhaseSystem (const fvMesh &)
virtual ~InterfaceCompositionPhaseChangePhaseSystem ()
virtual tmp< volScalarField > dmdt (const phasePairKey &key) const
virtual PtrList< volScalarField > dmdts () const
virtual autoPtr< phaseSystem::massTransferTable > massTransfer () const
virtual void correctInterfaceThermo ()
virtual bool read ()
Protected Types
typedef HashTable< autoPtr< interfaceCompositionModel >, phasePairKey, phasePairKey::hash > interfaceCompositionModelTable
typedef HashTable< Pair< autoPtr< BlendedInterfacialModel< massTransferModel > > >, phasePairKey, phasePairKey::hash > massTransferModelTable
typedef HashPtrTable< HashPtrTable< volScalarField >, phasePairKey, phasePairKey::hash > iDmdtSuSpTable
typedef HashPtrTable< volScalarField, phasePairKey, phasePairKey::hash > iDmdtTable
Protected Member Functions
virtual tmp< volScalarField > iDmdt (const phasePairKey &key) const
Protected Attributes
const label nInterfaceCorrectors_
massTransferModelTable massTransferModels_
interfaceCompositionModelTable interfaceCompositionModels_
iDmdtSuSpTable iDmdtSu_
iDmdtSuSpTable iDmdtSp_
Detailed Description
template<class BasePhaseSystem>
class Foam::InterfaceCompositionPhaseChangePhaseSystem< BasePhaseSystem >
Class to provide interfacial heat and mass transfer between a number of phases according to a interface composition model.
The interface temperature is calculated such that the net rate at which the heat is transferred to the interface is equal to the latent heat consumed by the mass transfer.
Source files
InterfaceCompositionPhaseChangePhaseSystem.H
InterfaceCompositionPhaseChangePhaseSystem.C
Definition at line 56 of file InterfaceCompositionPhaseChangePhaseSystem.H.
Member Typedef Documentation
interfaceCompositionModelTable
template<class BasePhaseSystem > typedef HashTable< autoPtr<interfaceCompositionModel>, phasePairKey, phasePairKey::hash > interfaceCompositionModelTable protected
Definition at line 69 of file InterfaceCompositionPhaseChangePhaseSystem.H.
massTransferModelTable
template<class BasePhaseSystem > typedef HashTable< Pair<autoPtr<BlendedInterfacialModel<massTransferModel> > >, phasePairKey, phasePairKey::hash > massTransferModelTable protected
Definition at line 76 of file InterfaceCompositionPhaseChangePhaseSystem.H.
iDmdtSuSpTable
template<class BasePhaseSystem > typedef HashPtrTable< HashPtrTable<volScalarField>, phasePairKey, phasePairKey::hash > iDmdtSuSpTable protected
Definition at line 83 of file InterfaceCompositionPhaseChangePhaseSystem.H.
iDmdtTable
template<class BasePhaseSystem > typedef HashPtrTable< volScalarField, phasePairKey, phasePairKey::hash > iDmdtTable protected
Definition at line 90 of file InterfaceCompositionPhaseChangePhaseSystem.H.
Constructor & Destructor Documentation
InterfaceCompositionPhaseChangePhaseSystem()
template<class BasePhaseSystem > InterfaceCompositionPhaseChangePhaseSystem (const fvMesh & mesh) explicit
Definition at line 76 of file InterfaceCompositionPhaseChangePhaseSystem.C.
References Foam::dimDensity, Foam::dimTime, Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAllConstIter, IOobject::groupName(), InterfaceCompositionPhaseChangePhaseSystem< BasePhaseSystem >::iDmdtSp_, InterfaceCompositionPhaseChangePhaseSystem< BasePhaseSystem >::iDmdtSu_, InterfaceCompositionPhaseChangePhaseSystem< BasePhaseSystem >::interfaceCompositionModels_, InterfaceCompositionPhaseChangePhaseSystem< BasePhaseSystem >::massTransferModels_, phase::name(), phaseModel::name(), phasePair::name(), phasePairKey::ordered(), phasePair::phase1(), phasePair::phase2(), and HashPtrTable< T, Key, Hash >::set().
~InterfaceCompositionPhaseChangePhaseSystem()
template<class BasePhaseSystem > ~InterfaceCompositionPhaseChangePhaseSystem () virtual
Definition at line 228 of file InterfaceCompositionPhaseChangePhaseSystem.C.
Member Function Documentation
iDmdt()
template<class BasePhaseSystem > Foam::tmp< Foam::volScalarField > iDmdt (const phasePairKey & key) const protected virtual
Definition at line 30 of file InterfaceCompositionPhaseChangePhaseSystem.C.
References Pair< T >::compare(), phaseSystem::dmdt(), Pair< T >::first(), forAllConstIter, phaseModel::otherPhase(), phases, and PtrList< T >::PtrList().
dmdt()
template<class BasePhaseSystem > Foam::tmp< Foam::volScalarField > dmdt (const phasePairKey & key) const virtual
Definition at line 237 of file InterfaceCompositionPhaseChangePhaseSystem.C.
dmdts()
template<class BasePhaseSystem > Foam::PtrList< Foam::volScalarField > dmdts () const virtual
Definition at line 248 of file InterfaceCompositionPhaseChangePhaseSystem.C.
References forAllConstIter, phasePair::phase1(), and phasePair::phase2().
massTransfer()
template<class BasePhaseSystem > Foam::autoPtr< Foam::phaseSystem::massTransferTable > massTransfer () const virtual
Definition at line 286 of file InterfaceCompositionPhaseChangePhaseSystem.C.
References forAllConstIter, IOobject::groupName(), phase::name(), phaseModel::name(), Foam::name(), phasePair::phase1(), phasePair::phase2(), phase::rho(), and Foam::fvm::Sp().
correctInterfaceThermo()
template<class BasePhaseSystem > void correctInterfaceThermo () virtual
Definition at line 366 of file InterfaceCompositionPhaseChangePhaseSystem.C.
References Foam::average(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), Foam::dimEnergy, DimensionedField< Type, GeoMesh >::dimensions(), heatTransferModel::dimK, Foam::dimTemperature, Foam::dimTime, Foam::dimVolume, Foam::endl(), Pair< T >::first(), forAllConstIter, Foam::Info, Foam::max(), mesh, Foam::min(), phasePair::name(), phasePair::phase1(), phasePair::phase2(), GeometricField< Type, PatchField, GeoMesh >::primitiveField(), Pair< T >::second(), and timeName.
read()
template<class BasePhaseSystem > bool read () virtual
Definition at line 482 of file InterfaceCompositionPhaseChangePhaseSystem.C.
Member Data Documentation
nInterfaceCorrectors_
template<class BasePhaseSystem > const label nInterfaceCorrectors_ protected
Definition at line 98 of file InterfaceCompositionPhaseChangePhaseSystem.H.
massTransferModels_
template<class BasePhaseSystem > massTransferModelTable massTransferModels_ protected
Definition at line 101 of file InterfaceCompositionPhaseChangePhaseSystem.H.
Referenced by InterfaceCompositionPhaseChangePhaseSystem< BasePhaseSystem >::InterfaceCompositionPhaseChangePhaseSystem().
interfaceCompositionModels_
template<class BasePhaseSystem > interfaceCompositionModelTable interfaceCompositionModels_ protected
Definition at line 104 of file InterfaceCompositionPhaseChangePhaseSystem.H.
Referenced by InterfaceCompositionPhaseChangePhaseSystem< BasePhaseSystem >::InterfaceCompositionPhaseChangePhaseSystem().
iDmdtSu_
template<class BasePhaseSystem > iDmdtSuSpTable iDmdtSu_ mutable protected
Definition at line 107 of file InterfaceCompositionPhaseChangePhaseSystem.H.
Referenced by InterfaceCompositionPhaseChangePhaseSystem< BasePhaseSystem >::InterfaceCompositionPhaseChangePhaseSystem().
iDmdtSp_
template<class BasePhaseSystem > iDmdtSuSpTable iDmdtSp_ mutable protected
Definition at line 110 of file InterfaceCompositionPhaseChangePhaseSystem.H.
Referenced by InterfaceCompositionPhaseChangePhaseSystem< BasePhaseSystem >::InterfaceCompositionPhaseChangePhaseSystem().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/PhaseSystems/InterfaceCompositionPhaseChangePhaseSystem/InterfaceCompositionPhaseChangePhaseSystem.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/PhaseSystems/InterfaceCompositionPhaseChangePhaseSystem/InterfaceCompositionPhaseChangePhaseSystem.C