OpenFOAM: surfaceZonesInfo Class Reference
surfaceZonesInfo Class Reference
#include <surfaceZonesInfo.H>
Public Types
enum areaSelectionAlgo { INSIDE , OUTSIDE , INSIDEPOINT , NONE }
enum faceZoneNaming { NOZONE , SINGLE , REGION }
enum faceZoneType { INTERNAL , BAFFLE , BOUNDARY }
Public Member Functions
surfaceZonesInfo (const searchableSurface &surface, const dictionary &surfacesDict, const wordList &regionNames)
surfaceZonesInfo (const wordList &faceZoneNames, const word &cellZoneNames, const areaSelectionAlgo &zoneInside, const point &zoneInsidePoints, const faceZoneType &faceType)
surfaceZonesInfo (const surfaceZonesInfo &)
autoPtr< surfaceZonesInfo > clone () const
const wordList & faceZoneNames () const
const word & cellZoneName () const
const areaSelectionAlgo & zoneInside () const
const point & zoneInsidePoint () const
const faceZoneType & faceType () const
Static Public Member Functions
static labelList getUnnamedSurfaces (const PtrList< surfaceZonesInfo > &surfList)
static labelList getNamedSurfaces (const PtrList< surfaceZonesInfo > &surfList)
static labelList getStandaloneNamedSurfaces (const PtrList< surfaceZonesInfo > &surfList)
static labelList getClosedNamedSurfaces (const PtrList< surfaceZonesInfo > &surfList, const searchableSurfaces &allGeometry, const labelList &surfaces)
static labelList getUnclosedNamedSurfaces (const PtrList< surfaceZonesInfo > &surfList, const searchableSurfaces &allGeometry, const labelList &surfaces)
static labelList getAllClosedNamedSurfaces (const PtrList< surfaceZonesInfo > &surfList, const searchableSurfaces &allGeometry, const labelList &surfaces)
static labelList getInsidePointNamedSurfaces (const PtrList< surfaceZonesInfo > &surfList)
static label addCellZone (const word &name, const labelList &addressing, polyMesh &mesh)
static labelList addCellZonesToMesh (const PtrList< surfaceZonesInfo > &surfList, const labelList &namedSurfaces, polyMesh &mesh)
static label addFaceZone (const word &name, const labelList &addressing, const boolList &flipMap, polyMesh &mesh)
static labelListList addFaceZonesToMesh (const PtrList< surfaceZonesInfo > &surfList, const labelList &namedSurfaces, polyMesh &mesh)
Static Public Attributes
static const Enum< areaSelectionAlgo > areaSelectionAlgoNames
static const Enum< faceZoneNaming > faceZoneNamingNames
static const Enum< faceZoneType > faceZoneTypeNames
Detailed Description
Source files
surfaceZonesInfo.H
surfaceZonesInfo.C
Definition at line 56 of file surfaceZonesInfo.H.
Member Enumeration Documentation
areaSelectionAlgo
enum areaSelectionAlgo
Enumerator
INSIDE
OUTSIDE
INSIDEPOINT
NONE
Definition at line 61 of file surfaceZonesInfo.H.
faceZoneNaming
enum faceZoneNaming
Enumerator
NOZONE
SINGLE
REGION
Definition at line 72 of file surfaceZonesInfo.H.
faceZoneType
enum faceZoneType
Enumerator
INTERNAL
BAFFLE
BOUNDARY
Definition at line 82 of file surfaceZonesInfo.H.
Constructor & Destructor Documentation
surfaceZonesInfo() [1/3]
surfaceZonesInfo (const searchableSurface & surface, const dictionary & surfacesDict, const wordList & regionNames)
Definition at line 69 of file surfaceZonesInfo.C.
References surfaceZonesInfo::areaSelectionAlgoNames, Foam::endl(), Foam::exit(), surfaceZonesInfo::faceZoneNamingNames, surfaceZonesInfo::faceZoneTypeNames, Foam::FatalIOError, FatalIOErrorInFunction, UPtrList< T >::get(), surfaceZonesInfo::INSIDE, surfaceZonesInfo::INSIDEPOINT, IOWarningInFunction, Foam::min(), surfaceZonesInfo::NOZONE, surfaceZonesInfo::OUTSIDE, surfaceZonesInfo::REGION, regionNames, List< T >::setSize(), surfaceZonesInfo::SINGLE, UPtrList< T >::size(), and UList< T >::size().
surfaceZonesInfo() [2/3]
surfaceZonesInfo (const wordList & faceZoneNames, const word & cellZoneNames, const areaSelectionAlgo & zoneInside, const point & zoneInsidePoints, const faceZoneType & faceType)
Definition at line 207 of file surfaceZonesInfo.C.
surfaceZonesInfo() [3/3]
surfaceZonesInfo (const surfaceZonesInfo & surfZone)
Definition at line 224 of file surfaceZonesInfo.C.
Member Function Documentation
clone()
autoPtr< surfaceZonesInfo > clone () const inline
Definition at line 148 of file surfaceZonesInfo.H.
References autoPtr< T >::New().
faceZoneNames()
const wordList & faceZoneNames () const inline
Definition at line 160 of file surfaceZonesInfo.H.
cellZoneName()
const word & cellZoneName () const inline
Definition at line 167 of file surfaceZonesInfo.H.
zoneInside()
const areaSelectionAlgo & zoneInside () const inline
Definition at line 172 of file surfaceZonesInfo.H.
zoneInsidePoint()
const point & zoneInsidePoint () const inline
Definition at line 178 of file surfaceZonesInfo.H.
faceType()
const faceZoneType & faceType () const inline
Definition at line 184 of file surfaceZonesInfo.H.
getUnnamedSurfaces()
Foam::labelList getUnnamedSurfaces (const PtrList< surfaceZonesInfo > & surfList) static
Definition at line 234 of file surfaceZonesInfo.C.
References forAll, PtrList< T >::setSize(), and UPtrList< T >::size().
Referenced by snappySnapDriver::calcNearestSurface(), snappySnapDriver::detectNearSurfaces(), snappyRefineDriver::doRefine(), meshRefinement::removeGapCells(), and snappySnapDriver::repatchToSurface().
getNamedSurfaces()
Foam::labelList getNamedSurfaces (const PtrList< surfaceZonesInfo > & surfList) static
Definition at line 255 of file surfaceZonesInfo.C.
References forAll, PtrList< T >::set(), PtrList< T >::setSize(), and UPtrList< T >::size().
Referenced by snappySnapDriver::calcNearestSurface(), snappySnapDriver::detectNearSurfaces(), snappySnapDriver::repatchToSurface(), and meshRefinement::zonify().
getStandaloneNamedSurfaces()
Foam::labelList getStandaloneNamedSurfaces (const PtrList< surfaceZonesInfo > & surfList) static
Definition at line 280 of file surfaceZonesInfo.C.
References forAll, PtrList< T >::set(), PtrList< T >::setSize(), and UPtrList< T >::size().
getClosedNamedSurfaces()
Foam::labelList getClosedNamedSurfaces (const PtrList< surfaceZonesInfo > & surfList, const searchableSurfaces & allGeometry, const labelList & surfaces) static
Definition at line 306 of file surfaceZonesInfo.C.
References forAll, surfaceZonesInfo::INSIDE, surfaceZonesInfo::OUTSIDE, PtrList< T >::set(), List< T >::setSize(), and UPtrList< T >::size().
getUnclosedNamedSurfaces()
Foam::labelList getUnclosedNamedSurfaces (const PtrList< surfaceZonesInfo > & surfList, const searchableSurfaces & allGeometry, const labelList & surfaces) static
Definition at line 338 of file surfaceZonesInfo.C.
References forAll, PtrList< T >::set(), PtrList< T >::setSize(), and UPtrList< T >::size().
getAllClosedNamedSurfaces()
Foam::labelList getAllClosedNamedSurfaces (const PtrList< surfaceZonesInfo > & surfList, const searchableSurfaces & allGeometry, const labelList & surfaces) static
Definition at line 365 of file surfaceZonesInfo.C.
References forAll, PtrList< T >::set(), List< T >::setSize(), and UPtrList< T >::size().
getInsidePointNamedSurfaces()
Foam::labelList getInsidePointNamedSurfaces (const PtrList< surfaceZonesInfo > & surfList) static
Definition at line 393 of file surfaceZonesInfo.C.
References forAll, surfaceZonesInfo::INSIDEPOINT, PtrList< T >::set(), List< T >::setSize(), and UPtrList< T >::size().
addCellZone()
Foam::label addCellZone (const word & name, const labelList & addressing, polyMesh & mesh) static
Definition at line 419 of file surfaceZonesInfo.C.
References polyMesh::cellZones(), ZoneMesh< ZoneType, MeshType >::findZoneID(), mesh, Foam::name(), PtrList< T >::set(), PtrList< T >::setSize(), and UPtrList< T >::size().
Referenced by refinementParameters::addCellZonesToMesh().
addCellZonesToMesh()
Foam::labelList addCellZonesToMesh (const PtrList< surfaceZonesInfo > & surfList, const labelList & namedSurfaces, polyMesh & mesh) static
Definition at line 450 of file surfaceZonesInfo.C.
References Pstream::allGatherList(), polyMesh::cellZones(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, mesh, UPstream::myProcNo(), Foam::nl, UPstream::nProcs(), word::null, and UPtrList< T >::size().
Referenced by meshRefinement::zonify().
addFaceZone()
Foam::label addFaceZone (const word & name, const labelList & addressing, const boolList & flipMap, polyMesh & mesh) static
Definition at line 501 of file surfaceZonesInfo.C.
References polyMesh::faceZones(), ZoneMesh< ZoneType, MeshType >::findZoneID(), mesh, Foam::name(), PtrList< T >::set(), PtrList< T >::setSize(), and UPtrList< T >::size().
Referenced by meshRefinement::addFaceZone(), meshRefinement::blockLeakFaces(), and meshRefinement::zonify().
addFaceZonesToMesh()
Foam::labelListList addFaceZonesToMesh (const PtrList< surfaceZonesInfo > & surfList, const labelList & namedSurfaces, polyMesh & mesh) static
Definition at line 604 of file surfaceZonesInfo.C.
References Pstream::allGatherList(), Foam::exit(), polyMesh::faceZones(), Foam::FatalError, FatalErrorInFunction, forAll, mesh, UPstream::myProcNo(), ZoneMesh< ZoneType, MeshType >::names(), Foam::nl, UPstream::nProcs(), PtrList< T >::setSize(), UPtrList< T >::size(), and UList< T >::size().
Referenced by meshRefinement::zonify().
Member Data Documentation
areaSelectionAlgoNames
const Foam::Enum< Foam::surfaceZonesInfo::areaSelectionAlgo > areaSelectionAlgoNames static
Definition at line 69 of file surfaceZonesInfo.H.
Referenced by refinementSurfaces::findInside(), and surfaceZonesInfo::surfaceZonesInfo().
faceZoneNamingNames
const Foam::Enum< Foam::surfaceZonesInfo::faceZoneNaming > faceZoneNamingNames static
Definition at line 79 of file surfaceZonesInfo.H.
Referenced by surfaceZonesInfo::surfaceZonesInfo().
faceZoneTypeNames
const Foam::Enum< Foam::surfaceZonesInfo::faceZoneType > faceZoneTypeNames static
Definition at line 89 of file surfaceZonesInfo.H.
Referenced by snappyRefineDriver::addFaceZones(), meshRefinement::createZoneBaffles(), meshRefinement::dupNonManifoldBoundaryPoints(), refinementParameters::getZoneInfo(), and surfaceZonesInfo::surfaceZonesInfo().
The documentation for this class was generated from the following files:
src/mesh/snappyHexMesh/refinementSurfaces/surfaceZonesInfo.H
src/mesh/snappyHexMesh/refinementSurfaces/surfaceZonesInfo.C