OpenFOAM: interfaceHeight Class Reference
interfaceHeight Class Reference
This function object reports the height of the interface above a set of locations.
#include <interfaceHeight.H>
Public Member Functions
TypeName ("interfaceHeight")
interfaceHeight (const word &name, const Time &runTime, const dictionary &dict)
interfaceHeight (const interfaceHeight &)=delete
void operator= (const interfaceHeight &)=delete
virtual ~interfaceHeight ()=default
OFstream & files (const fileID fid)
virtual bool read (const dictionary &)
virtual bool execute ()
virtual bool end ()
virtual bool write ()
PtrList< OFstream > & files ()
OFstream & files (const label i)
Public Member Functions inherited from fvMeshFunctionObject
TypeName ("fvMeshFunctionObject")
fvMeshFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
fvMeshFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
virtual ~fvMeshFunctionObject ()=default
Public Member Functions inherited from regionFunctionObject
TypeName ("regionFunctionObject")
regionFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
regionFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
virtual ~regionFunctionObject ()=default
template<class ObjectType >
const ObjectType * lookupObjectPtr (const word &fieldName) const
template<class ObjectType >
ObjectType * lookupObjectRefPtr (const word &fieldName) const
Public Member Functions inherited from stateFunctionObject
stateFunctionObject (const word &name, const Time &runTime)
virtual ~stateFunctionObject ()=default
dictionary & propertyDict ()
bool foundProperty (const word &entryName) const
void clearTrigger ()
label getTrigger () const
bool setTrigger (const label triggeri)
bool getDict (const word &entryName, dictionary &dict) const
bool getObjectDict (const word &objectName, const word &entryName, dictionary &dict) const
template<class Type >
Type getProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getProperty (const word &entryName, Type &value) const
template<class Type >
void setProperty (const word &entryName, const Type &value)
template<class Type >
Type getObjectProperty (const word &objectName, const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getObjectProperty (const word &objectName, const word &entryName, Type &value) const
template<class Type >
void setObjectProperty (const word &objectName, const word &entryName, const Type &value)
template<class Type >
void setResult (const word &entryName, const Type &value)
template<class Type >
void setObjectResult (const word &objectName, const word &entryName, const Type &value)
template<class Type >
Type getResult (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
Type getObjectResult (const word &objectName, const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getObjectResult (const word &objectName, const word &entryName, Type &value) const
word resultType (const word &entryName) const
word objectResultType (const word &objectName, const word &entryName) const
wordList objectResultEntries () const
wordList objectResultEntries (const word &objectName) const
void writeResultEntries (Ostream &os) const
void writeResultEntries (const word &objectName, Ostream &os) const
void writeAllResultEntries (Ostream &os) const
Public Member Functions inherited from timeFunctionObject
timeFunctionObject (const word &name, const Time &runTime)
virtual ~timeFunctionObject ()=default
const Time & time () const
objectRegistry & storedObjects ()
const objectRegistry & storedObjects () const
Public Member Functions inherited from functionObject
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name, const bool withNamePrefix=defaultUseNamePrefix)
autoPtr< functionObject > clone () const
virtual ~functionObject ()=default
virtual const word & type () const =0
const word & name () const noexcept
bool useNamePrefix () const noexcept
bool useNamePrefix (bool on) noexcept
virtual bool execute (const label subIndex)
virtual bool adjustTimeStep ()
virtual bool filesModified () const
virtual void updateMesh (const mapPolyMesh &mpm)
virtual void movePoints (const polyMesh &mesh)
Public Member Functions inherited from logFiles
logFiles (const objectRegistry &obr, const word &prefix)
logFiles (const objectRegistry &obr, const word &prefix, const dictionary &dict)
virtual ~logFiles ()=default
const wordList & names () const
PtrList< OFstream > & files ()
OFstream & files (const label i)
Public Member Functions inherited from writeFile
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name="undefined", const bool writeToFile=true)
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name, const dictionary &dict, const bool writeToFile=true)
writeFile (const writeFile &wf)
virtual ~writeFile ()=default
virtual OFstream & file ()
virtual bool writeToFile () const
virtual bool canWriteToFile () const
virtual bool canResetFile () const
virtual bool canWriteHeader () const
virtual label charWidth () const
virtual void writeCommented (Ostream &os, const string &str) const
virtual void writeTabbed (Ostream &os, const string &str) const
virtual void writeHeader (Ostream &os, const string &str) const
virtual void writeCurrentTime (Ostream &os) const
virtual void writeBreak (Ostream &os) const
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
template<class Type >
void writeValue (Ostream &os, const Type &val) const
Protected Member Functions
virtual void writeFileHeader (const fileID fid)
Protected Member Functions inherited from fvMeshFunctionObject
fvMeshFunctionObject (const fvMeshFunctionObject &)=delete
void operator= (const fvMeshFunctionObject &)=delete
Protected Member Functions inherited from regionFunctionObject
virtual const objectRegistry & obr () const
template<class ObjectType >
bool foundObject (const word &fieldName) const
template<class ObjectType >
const ObjectType * cfindObject (const word &fieldName) const
template<class ObjectType >
const ObjectType * findObject (const word &fieldName) const
template<class ObjectType >
ObjectType * findObject (const word &fieldName)
template<class ObjectType >
ObjectType * getObjectPtr (const word &fieldName) const
template<class ObjectType >
const ObjectType & lookupObject (const word &fieldName) const
template<class ObjectType >
ObjectType & lookupObjectRef (const word &fieldName) const
template<class ObjectType >
bool store (word &fieldName, const tmp< ObjectType > &tfield, bool cacheable=false)
template<class ObjectType >
bool storeInDb (const word &fieldName, const tmp< ObjectType > &tfield, const objectRegistry &obr)
bool writeObject (const word &fieldName)
bool clearObject (const word &fieldName)
void clearObjects (const wordList &objNames)
regionFunctionObject (const regionFunctionObject &)=delete
void operator= (const regionFunctionObject &)=delete
Protected Member Functions inherited from stateFunctionObject
const functionObjects::properties & stateDict () const
functionObjects::properties & stateDict ()
stateFunctionObject (const stateFunctionObject &)=delete
void operator= (const stateFunctionObject &)=delete
Protected Member Functions inherited from timeFunctionObject
void clearOutputObjects (const wordList &objNames)
timeFunctionObject (const timeFunctionObject &)=delete
void operator= (const timeFunctionObject &)=delete
Protected Member Functions inherited from functionObject
word scopedName (const word &name) const
Protected Member Functions inherited from logFiles
virtual void createFiles ()
virtual void resetNames (const wordList &names)
virtual void resetName (const word &name)
Protected Member Functions inherited from writeFile
void initStream (Ostream &os) const
fileName baseFileDir () const
fileName baseTimeDir () const
fileName filePath (const fileName &fName) const
virtual autoPtr< OFstream > newFile (const fileName &fName) const
virtual autoPtr< OFstream > newFileAtTime (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > newFileAtStartTime (const word &name) const
virtual void resetFile (const word &name)
Omanip< int > valueWidth (const label offset=0) const
void operator= (const writeFile &)=delete
virtual autoPtr< OFstream > createFile (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > createFile (const word &name) const
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &runTime, const dictionary &dict)
Public Attributes inherited from functionObject
bool log
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
static bool defaultUseNamePrefix
static word outputPrefix
Static Public Attributes inherited from writeFile
static label addChars = 8
Protected Attributes inherited from fvMeshFunctionObject
const fvMesh & mesh_
Protected Attributes inherited from regionFunctionObject
word subRegistryName_
const objectRegistry & obr_
const objectRegistry * obrPtr_
Protected Attributes inherited from timeFunctionObject
const Time & time_
Protected Attributes inherited from logFiles
wordList names_
PtrList< OFstream > filePtrs_
Protected Attributes inherited from writeFile
const objectRegistry & fileObr_
const fileName prefix_
word fileName_
autoPtr< OFstream > filePtr_
label writePrecision_
bool writeToFile_
bool updateHeader_
bool writtenHeader_
bool useUserTime_
scalar startTime_
Detailed Description
This function object reports the height of the interface above a set of locations.
For each location, it writes the vertical distance of the interface above both the location and the lowest boundary. It also writes the point on the interface from which these heights are computed. It uses an integral approach, so if there are multiple interfaces above or below a location then this method will generate average values.
Operands:
Operand Type Location
input - -
output file 1 dat $FOAM_CASE/postProcessing/<FO>/<time>/height
output file 2 dat $FOAM_CASE/postProcessing/<FO>/<time>/position
output field - -
Usage
Minimal example by using system/controlDict.functions:
interfaceHeight1
{
    // Mandatory entries (unmodifiable)
    type            interfaceHeight;
    libs            (fieldFunctionObjects);
    // Mandatory entries (runtime modifiable)
    locations       ((0 0 0) (10 0 0) (20 0 0));
    // Optional entries (runtime modifiable)
    alpha           alpha.water;
    liquid          true;
    direction       (1 0 0);
    interpolationScheme    cellPoint;
    // Optional (inherited) entries
    ...
}
where the entries mean:
Property Description Type Req'd Dflt
type Type name: interfaceHeight word yes -
libs Library name: fieldFunctionObjects word yes -
locations Locations to report the height at vectorList yes -
alpha Name of alpha field word no alpha
liquid Flag if the alpha field that of the liquid bool no true
direction Direction of interface vector no g
interpolationScheme Interpolation scheme word no cellPoint
The inherited entries are elaborated in:
functionObject.H
writeFile.H
Usage by the postProcess utility is not available.
See also
Foam::functionObject
Foam::functionObjects::fvMeshFunctionObject
Foam::functionObjects::writeFile
Foam::functionObjects::logFile
ExtendedCodeGuide::functionObjects::field::interfaceHeight
Source files
interfaceHeight.H
interfaceHeight.C
Definition at line 183 of file interfaceHeight.H.
Constructor & Destructor Documentation
interfaceHeight() [1/2]
interfaceHeight (const word & name, const Time & runTime, const dictionary & dict)
Definition at line 221 of file interfaceHeight.C.
References dict, interfaceHeight::read(), and logFiles::resetNames().
interfaceHeight() [2/2]
interfaceHeight (const interfaceHeight &) delete
~interfaceHeight()
virtual ~interfaceHeight () virtual default
Member Function Documentation
writeFileHeader()
void writeFileHeader (const fileID fid) protected virtual
Definition at line 148 of file interfaceHeight.C.
References forAll, and Foam::name().
TypeName()
TypeName ("interfaceHeight")
operator=()
void operator= (const interfaceHeight &) delete
files() [1/3]
OFstream & files (const fileID fid) inline
Definition at line 263 of file interfaceHeight.H.
References logFiles::files().
read()
bool read (const dictionary & dict) virtual
Reimplemented from regionFunctionObject.
Definition at line 243 of file interfaceHeight.C.
References dict.
Referenced by interfaceHeight::interfaceHeight().
execute()
bool execute () virtual
Implements functionObject.
Definition at line 255 of file interfaceHeight.C.
end()
bool end () virtual
Reimplemented from functionObject.
Definition at line 261 of file interfaceHeight.C.
write()
bool write () virtual
Implements functionObject.
Definition at line 267 of file interfaceHeight.C.
References logFiles::write().
files() [2/3]
Foam::PtrList< Foam::OFstream > & files ()
Definition at line 126 of file logFiles.C.
files() [3/3]
Foam::OFstream & files (const label i)
Definition at line 129 of file logFiles.C.
The documentation for this class was generated from the following files:
src/functionObjects/field/interfaceHeight/interfaceHeight.H
src/functionObjects/field/interfaceHeight/interfaceHeight.C