OpenFOAM: dictionary Class Reference
dictionary Class Reference
A list of keyword definitions, which are a keyword followed by a number of values (eg, words and numbers) or by a sub-dictionary. Since the dictionary format is used extensively throughout OpenFOAM for input/output files, there are many examples of its use.
#include <dictionary.H>
Classes
class Searcher
Public Types
typedef Searcher< true > const_searcher
typedef Searcher< false > searcher
Public Types inherited from UILList< LListBase, T >
typedef T value_type
typedef T * pointer
typedef const T * const_pointer
typedef T & reference
typedef const T & const_reference
typedef label size_type
typedef label difference_type
using base_iterator = typename LListBase::iterator
using const_base_iterator = typename LListBase::const_iterator
Public Member Functions
ClassName ("dictionary")
dictionary ()
dictionary (const fileName &name)
dictionary (const fileName &name, const dictionary &parentDict, Istream &is, bool keepHeader=false)
dictionary (Istream &is)
dictionary (Istream &is, bool keepHeader)
dictionary (const dictionary &parentDict, const dictionary &dict)
dictionary (const dictionary &dict)
dictionary (const dictionary *dict)
dictionary (const dictionary &parentDict, dictionary &&dict)
dictionary (dictionary &&dict)
autoPtr< dictionary > clone () const
virtual ~dictionary ()
const fileName & name () const noexcept
fileName & name () noexcept
word dictName () const
fileName relativeName (const bool caseTag=false) const
bool isNullDict () const noexcept
const dictionary & parent () const noexcept
const dictionary & topDict () const
label startLineNumber () const
label endLineNumber () const
SHA1Digest digest () const
tokenList tokens () const
const entry * findEntry (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
entry * findEntry (const word &keyword, enum keyType::option matchOpt=keyType::REGEX)
bool found (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
const entry * findScoped (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
const dictionary * findDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
dictionary * findDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX)
bool isDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
const entry & lookupEntry (const word &keyword, enum keyType::option matchOpt) const
ITstream & lookup (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
template<class T >
T get (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
template<class T >
T getOrDefault (const word &keyword, const T &deflt, enum keyType::option matchOpt=keyType::REGEX) const
template<class T >
T getOrAdd (const word &keyword, const T &deflt, enum keyType::option matchOpt=keyType::REGEX)
template<class T >
bool readEntry (const word &keyword, T &val, enum keyType::option matchOpt=keyType::REGEX, IOobjectOption::readOption readOpt=IOobjectOption::MUST_READ) const
template<class T >
bool readIfPresent (const word &keyword, T &val, enum keyType::option matchOpt=keyType::REGEX) const
template<class T , class Predicate >
T getCheck (const word &keyword, const Predicate &pred, enum keyType::option matchOpt=keyType::REGEX) const
template<class T , class Predicate >
T getCheckOrDefault (const word &keyword, const T &deflt, const Predicate &pred, enum keyType::option matchOpt=keyType::REGEX) const
template<class T , class Predicate >
T getCheckOrAdd (const word &keyword, const T &deflt, const Predicate &pred, enum keyType::option matchOpt=keyType::REGEX)
template<class T , class Predicate >
bool readCheck (const word &keyword, T &val, const Predicate &pred, enum keyType::option matchOpt=keyType::REGEX, IOobjectOption::readOption readOpt=IOobjectOption::MUST_READ) const
template<class T , class Predicate >
bool readCheckIfPresent (const word &keyword, T &val, const Predicate &pred, enum keyType::option matchOpt=keyType::REGEX) const
const dictionary & subDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
dictionary & subDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX)
dictionary & subDictOrAdd (const word &keyword, enum keyType::option matchOpt=keyType::REGEX)
dictionary subOrEmptyDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX, const bool mandatory=false) const
const dictionary & optionalSubDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
wordList toc () const
wordList sortedToc () const
template<class Compare >
wordList sortedToc (const Compare &comp) const
List< keyType > keys (bool patterns=false) const
bool substituteKeyword (const word &keyword, bool mergeEntry=false)
bool substituteScopedKeyword (const word &keyword, bool mergeEntry=false)
entry * add (entry *entryPtr, bool mergeEntry=false)
entry * add (const entry &e, bool mergeEntry=false)
entry * add (const keyType &k, const word &v, bool overwrite=false)
entry * add (const keyType &k, const string &v, bool overwrite=false)
entry * add (const keyType &k, const label v, bool overwrite=false)
entry * add (const keyType &k, const scalar v, bool overwrite=false)
entry * add (const keyType &k, const dictionary &d, bool mergeEntry=false)
template<class T >
entry * add (const keyType &k, const T &v, bool overwrite=false)
entry * set (entry *entryPtr)
entry * set (const entry &e)
entry * set (const keyType &k, const dictionary &v)
template<class T >
entry * set (const keyType &k, const T &v)
bool remove (const word &keyword)
bool changeKeyword (const keyType &oldKeyword, const keyType &newKeyword, bool overwrite=false)
bool merge (const dictionary &dict)
void clear ()
void transfer (dictionary &dict)
void checkITstream (const ITstream &is, const word &keyword) const
bool read (Istream &is)
bool read (Istream &is, bool keepHeader)
void writeEntry (Ostream &os) const
void writeEntry (const keyType &keyword, Ostream &os) const
void writeEntries (Ostream &os, const bool extraNewLine=false) const
void write (Ostream &os, const bool subDict=true) const
const_searcher csearch (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
const_searcher search (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
searcher search (const word &keyword, enum keyType::option matchOpt=keyType::REGEX)
const_searcher csearchScoped (const word &keyword, enum keyType::option matchOpt) const
const_searcher searchScoped (const word &keyword, enum keyType::option matchOpt) const
searcher searchScoped (const word &keyword, enum keyType::option matchOpt)
const dictionary * cfindScopedDict (const fileName &dictPath) const
const dictionary * findScopedDict (const fileName &dictPath) const
dictionary * findScopedDict (const fileName &dictPath)
dictionary * makeScopedDict (const fileName &dictPath)
const_searcher csearchCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, enum keyType::option matchOpt=keyType::REGEX) const
const entry * findCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, enum keyType::option matchOpt) const
bool foundCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, enum keyType::option matchOpt=keyType::REGEX) const
const entry & lookupEntryCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, enum keyType::option matchOpt) const
ITstream & lookupCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, enum keyType::option matchOpt=keyType::REGEX) const
template<class T >
T getCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, enum keyType::option matchOpt=keyType::REGEX) const
template<class T >
T getOrDefaultCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, const T &deflt, enum keyType::option matchOpt=keyType::REGEX) const
template<class T >
bool readCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, T &val, enum keyType::option matchOpt=keyType::REGEX, IOobjectOption::readOption readOpt=IOobjectOption::MUST_READ) const
template<class T >
bool readIfPresentCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, T &val, enum keyType::option matchOpt=keyType::REGEX) const
void operator= (const dictionary &rhs)
void operator+= (const dictionary &rhs)
void operator|= (const dictionary &rhs)
void operator<<= (const dictionary &rhs)
bool getBool (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Same as get< bool >(const word&, keyType::option)
label getLabel (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Same as get< label >(const word&, keyType::option)
scalar getScalar (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Same as get< scalar >(const word&, keyType::option)
string getString (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Same as get< string >(const word&, keyType::option)
word getWord (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Same as get< word >(const word&, keyType::option)
fileName getFileName (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Same as get< fileName >(const word&, keyType::option)
template<class T >
T lookupOrDefault (const word &keyword, const T &deflt, enum keyType::option matchOpt=keyType::REGEX) const
template<class T >
T lookupOrAddDefault (const word &keyword, const T &deflt, enum keyType::option matchOpt=keyType::REGEX)
ITstream & operator[] (const word &keyword) const
bool found (const word &keyword, bool recursive, bool patternMatch=true) const
entry * lookupEntryPtr (const word &keyword, bool recursive, bool patternMatch)
const entry * lookupEntryPtr (const word &keyword, bool recursive, bool patternMatch) const
const entry * lookupScopedEntryPtr (const word &keyword, bool recursive, bool patternMatch) const
const dictionary * subDictPtr (const word &keyword) const
dictionary * subDictPtr (const word &keyword)
const entry & lookupEntry (const word &keyword, bool recursive, bool patternMatch) const
ITstream & lookup (const word &keyword, bool recursive, bool patternMatch=true) const
template<class T >
T lookupOrDefault (const word &keyword, const T &deflt, bool recursive, bool patternMatch=true) const
template<class T >
T lookupOrAddDefault (const word &keyword, const T &deflt, bool recursive, bool patternMatch=true)
template<class T >
bool readIfPresent (const word &keyword, T &val, bool recursive, bool patternMatch=true) const
template<class T >
T lookupType (const word &keyword, bool recursive=false, bool patternMatch=true) const
template<class Compare >
Foam::wordList sortedToc (const Compare &comp) const
template<class T >
Foam::entry * add (const keyType &k, const T &v, bool overwrite)
template<class T >
Foam::entry * set (const keyType &k, const T &v)
Public Member Functions inherited from ILList< LListBase, T >
ILList ()=default
ILList (T *item)
ILList (Istream &is)
ILList (const ILList< LListBase, T > &lst)
ILList (ILList< LListBase, T > &&lst)
template<class CloneArg >
ILList (const ILList< LListBase, T > &lst, const CloneArg &cloneArg)
template<class INew >
ILList (Istream &is, const INew &inew)
~ILList ()
void clear ()
void pop_front (label n=1)
bool erase (T *item)
void transfer (ILList< LListBase, T > &lst)
void operator= (const ILList< LListBase, T > &lst)
void operator= (ILList< LListBase, T > &&lst)
Public Member Functions inherited from UILList< LListBase, T >
UILList ()=default
UILList (T *item)
UILList (const UILList< LListBase, T > &list)
T * front ()
const T * front () const
T * back ()
const T * back () const
T * removeHead ()
T * remove (T *item)
T * remove (iterator &iter)
void operator= (const UILList< LListBase, T > &lst)
bool operator== (const UILList< LListBase, T > &lst) const
bool operator!= (const UILList< LListBase, T > &lst) const
Ostream & writeList (Ostream &os, const label shortLen=0) const
iterator begin ()
const_iterator cbegin () const
reverse_iterator rbegin ()
const_reverse_iterator crbegin () const
const_iterator begin () const
const_reverse_iterator rbegin () const
const iterator & end ()
const const_iterator & cend () const
const reverse_iterator & rend ()
const const_reverse_iterator & crend () const
const const_iterator & end () const
const const_reverse_iterator & rend () const
T * first ()
const T * first () const
T * last ()
const T * last () const
Static Public Member Functions
static int reportOptional () noexcept
static int reportOptional (const int level) noexcept
static autoPtr< dictionary > New (Istream &is)
Public Attributes
friend const_searcher
friend searcher
Static Public Attributes
static int writeOptionalEntries
static const dictionary null
static refPtr< OSstream > reportingOutput
Friends
class entry
Istream & operator>> (Istream &is, dictionary &dict)
Ostream & operator<< (Ostream &os, const dictionary &dict)
Detailed Description
A list of keyword definitions, which are a keyword followed by a number of values (eg, words and numbers) or by a sub-dictionary. Since the dictionary format is used extensively throughout OpenFOAM for input/output files, there are many examples of its use.
Dictionary keywords are a plain word or a pattern (regular expression). The general order for searching is as follows:
exact match
pattern match (in reverse order)
optional recursion into the enclosing (parent) dictionaries
The dictionary class is the base class for IOdictionary and also serves as a bootstrap dictionary for the objectRegistry data dictionaries.
Note
Within dictionaries, entries can be referenced by using the '$' syntax familiar from shell programming. A '.' separator is used when referencing sub-dictionary entries. Leading '.' prefixes can be used to specify an entry from a parent dictionary. An initial '^' anchor (or ':' for backward compatibility) specifies starting from the top-level entry. For example,
key1        val1;
key2        $key1;   // use key1 value from current scope
key3        $.key1;  // use key1 value from current scope
subdict1
{
    key1        val1b;
    key2        $..key1; // use key1 value from parent
    subdict2
    {
        key2    val2;
        key3    $...key1; // use key1 value from grandparent
    }
}
key4        $^subdict1.subdict2.key3;  // lookup with absolute scoping
It is also possible to use the '${}' syntax for clarity.
Source files
dictionary.H
dictionary.C
dictionaryIO.C
dictionarySearch.C
See also
Foam::entry
Foam::dictionaryEntry
Foam::primitiveEntry
Definition at line 120 of file dictionary.H.
Member Typedef Documentation
const_searcher
typedef Searcher<true> const_searcher
Definition at line 252 of file dictionary.H.
searcher
typedef Searcher<false> searcher
Definition at line 255 of file dictionary.H.
Constructor & Destructor Documentation
dictionary() [1/10]
dictionary ()
Definition at line 68 of file dictionary.C.
dictionary() [2/10]
dictionary (const fileName & name) explicit
Definition at line 75 of file dictionary.C.
dictionary() [3/10]
dictionary (const fileName & name, const dictionary & parentDict, Istream & is, bool keepHeader = false)
Definition at line 27 of file dictionaryIO.C.
References Foam::name(), and dictionary::read().
dictionary() [4/10]
dictionary (Istream & is)
Definition at line 42 of file dictionaryIO.C.
dictionary() [5/10]
dictionary (Istream & is, bool keepHeader)
Definition at line 48 of file dictionaryIO.C.
References dictionary::read(), and entry::resetInputMode().
dictionary() [6/10]
dictionary (const dictionary & parentDict, const dictionary & dict)
Definition at line 82 of file dictionary.C.
References e.
dictionary() [7/10]
dictionary (const dictionary & dict)
Definition at line 105 of file dictionary.C.
References e.
dictionary() [8/10]
dictionary (const dictionary * dict) explicit
Definition at line 127 of file dictionary.C.
References dict, and dictionary::operator=().
dictionary() [9/10]
dictionary (const dictionary & parentDict, dictionary && dict)
Definition at line 139 of file dictionary.C.
References fileName::concat(), dict, dictionary::name(), and dictionary::transfer().
dictionary() [10/10]
dictionary (dictionary && dict)
Definition at line 153 of file dictionary.C.
References dict, and dictionary::transfer().
~dictionary()
~dictionary () virtual
Definition at line 173 of file dictionary.C.
Member Function Documentation
ClassName()
ClassName ("dictionary")
reportOptional() [1/2]
int reportOptional () inline static noexcept
Definition at line 25 of file dictionaryI.H.
References dictionary::writeOptionalEntries.
reportOptional() [2/2]
int reportOptional (const int level) inline static noexcept
Definition at line 31 of file dictionaryI.H.
clone()
Foam::autoPtr< Foam::dictionary > clone () const
Definition at line 165 of file dictionary.C.
References autoPtr< T >::New().
Referenced by hexRef8Data::hexRef8Data().
New()
Foam::autoPtr< Foam::dictionary > New (Istream & is) static
Definition at line 62 of file dictionaryIO.C.
References autoPtr< T >::New().
name() [1/2]
const Foam::fileName & name () const inline noexcept
Definition at line 41 of file dictionaryI.H.
Referenced by dynamicCodeContext::addLineDirective(), baseIOdictionary::baseIOdictionary(), baseIOdictionary::baseIOdictionary(), Foam::copyFilteredDict(), metisLikeDecomp::decompose(), dictionary::dictionary(), motionSmootherAlgo::get(), meshRefinement::get(), JobInfo::JobInfo(), dictionaryEntry::name(), dictionaryEntry::name(), dictionary::operator=(), Foam::operator>>(), dynamicCodeContext::readEntry(), dictionary::transfer(), and Foam::unitSet().
name() [2/2]
Foam::fileName & name () inline noexcept
Definition at line 47 of file dictionaryI.H.
dictName()
Foam::word dictName () const inline
Definition at line 53 of file dictionaryI.H.
Referenced by profileModel::New(), liquidProperties::New(), solidProperties::New(), thermophysicalProperties::New(), blendingMethod::New(), and twoPhaseSystem::twoPhaseSystem().
relativeName()
Foam::fileName relativeName (const bool caseTag = false) const
Definition at line 179 of file dictionary.C.
References argList::envRelativePath(), and Foam::name().
Referenced by dictionary::csearchCompat(), meshRefinement::lookup(), messageStream::operator()(), IOerror::operator()(), IOerror::operator()(), dimensionSet::readEntry(), dictionaryEntry::relativeName(), meshRefinement::subDict(), and Foam::warnCompatDegrees().
isNullDict()
bool isNullDict () const inline noexcept
Definition at line 67 of file dictionaryI.H.
References dictionary::null.
parent()
const Foam::dictionary & parent () const inline noexcept
Definition at line 73 of file dictionaryI.H.
topDict()
const Foam::dictionary & topDict () const
Definition at line 185 of file dictionary.C.
References UPtrList< T >::empty(), IOobject::name(), and p.
startLineNumber()
Foam::label startLineNumber () const
Definition at line 198 of file dictionary.C.
Referenced by messageStream::operator()(), IOerror::operator()(), and IOerror::operator()().
endLineNumber()
Foam::label endLineNumber () const
Definition at line 209 of file dictionary.C.
Referenced by messageStream::operator()(), IOerror::operator()(), and IOerror::operator()().
digest()
Foam::SHA1Digest digest () const
Definition at line 220 of file dictionary.C.
References e, and os().
Referenced by functionObjectList::read().
tokens()
Foam::tokenList tokens () const
Definition at line 234 of file dictionary.C.
References e, os(), and ITstream::parse().
findEntry() [1/2]
const Foam::entry * findEntry (const word & keyword, enum keyType::option matchOpt = keyType::REGEX) const inline
Definition at line 79 of file dictionaryI.H.
Referenced by dynamicCodeContext::findEntry(), GAMGSolver::GAMGSolver(), genericFaePatchField< Type >::genericFaePatchField(), genericFaPatchField< Type >::genericFaPatchField(), genericFvPatchField< Type >::genericFvPatchField(), genericFvsPatchField< Type >::genericFvsPatchField(), Foam::getOrAdd(), Enum< EnumType >::getOrDefault(), meshRefinement::lookup(), dictionary::lookupEntryPtr(), dictionary::lookupEntryPtr(), fvGeometryScheme::New(), PatchFunction1< scalar >::New(), Function1< Type >::New(), Function1< Type >::New(), PatchFunction1< Type >::New(), sampledSets::read(), sampledSurfaces::read(), Enum< injectionMethod >::read(), dimensionSet::readEntry(), dynamicCodeContext::readEntry(), and Foam::writeEntryIfPresent().
findEntry() [2/2]
Foam::entry * findEntry (const word & keyword, enum keyType::option matchOpt = keyType::REGEX) inline
Definition at line 89 of file dictionaryI.H.
found() [1/2]
bool found (const word & keyword, enum keyType::option matchOpt = keyType::REGEX) const inline
Definition at line 99 of file dictionaryI.H.
Referenced by sixDoFRigidBodyMotion::addConstraints(), sixDoFRigidBodyMotion::addRestraints(), adjointSimple::adjointSimple(), equationInitialResidualCondition::apply(), equationMaxIterCondition::apply(), dimensioned< scalar >::dimensioned(), timeControl::entriesPresent(), fanMomentumSource::fanMomentumSource(), subModelBase::getBaseProperty(), greyMeanAbsorptionEmission::greyMeanAbsorptionEmission(), oversetFvPatchField< Type >::initEvaluate(), solverInfo::initialiseResidualField(), liquidProperties::New(), solidProperties::New(), binModel::read(), timeControl::read(), Time::readDict(), liquidProperties::readIfPresent(), runTimeCondition::setConditionDict(), sixDoFRigidBodyMotion::sixDoFRigidBodyMotion(), Foam::unitSet(), inverseDistance::update(), solverInfo::updateSolverInfo(), Foam::warnCompatDegrees(), and wideBandAbsorptionEmission::wideBandAbsorptionEmission().
findScoped()
const Foam::entry * findScoped (const word & keyword, enum keyType::option matchOpt = keyType::REGEX) const inline
Definition at line 109 of file dictionaryI.H.
Referenced by Foam::getVariableOrDie(), and dictionary::lookupScopedEntryPtr().
findDict() [1/2]
const Foam::dictionary * findDict (const word & keyword, enum keyType::option matchOpt = keyType::REGEX) const inline
Definition at line 119 of file dictionaryI.H.
Referenced by alphatWallBoilingWallFunctionFvPatchScalarField::alphatWallBoilingWallFunctionFvPatchScalarField(), Foam::cfindCoeffsDict(), codedMixedFvPatchField< Type >::codeContext(), codedFunctionObject::codeContext(), Foam::combineFormatOptions(), data::data(), energyTransport::energyTransport(), dynamicMotionSolverListFvMesh::init(), oversetFvPatchField< Type >::initEvaluate(), liquidMixtureProperties::liquidMixtureProperties(), namedBlock::namedBlock(), namedVertex::namedVertex(), laminarModel< BasicTurbulenceModel >::New(), RASModelVariables::New(), adjointRASModel::read(), PDRblock::read(), blockVertex::read(), Time::readDict(), mapDistribute::readDict(), constant::readDict(), Foam::resetFuncsImpl(), Time::setMonitoring(), solidMixtureProperties::solidMixtureProperties(), dictionary::subDictPtr(), dictionary::subDictPtr(), surfaceWriter::surfaceWriter(), Foam::debug::switchSet(), thermophysicalPropertiesSelector< ThermophysicalProperties >::thermophysicalPropertiesSelector(), Foam::unitSet(), blockDescriptor::write(), blockVertex::write(), and Foam::writeFuncsImpl().
findDict() [2/2]
Foam::dictionary * findDict (const word & keyword, enum keyType::option matchOpt = keyType::REGEX) inline
Definition at line 129 of file dictionaryI.H.
isDict()
bool isDict (const word & keyword, enum keyType::option matchOpt = keyType::REGEX) const inline
Definition at line 139 of file dictionaryI.H.
lookupEntry() [1/2]
const Foam::entry & lookupEntry (const word & keyword, enum keyType::option matchOpt) const
Definition at line 358 of file dictionary.C.
References Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, and Foam::nl.
Referenced by dictionary::lookupEntry().
lookup() [1/2]
Foam::ITstream & lookup (const word & keyword, enum keyType::option matchOpt = keyType::REGEX) const
Definition at line 378 of file dictionary.C.
Referenced by equationMaxIterCondition::apply(), forceList::forceList(), Foam::getLazyPair(), Foam::getRadius(), multivariateSelectionScheme< Type >::multivariateSelectionScheme(), interpolation< Type >::New(), multivariateIndependentScheme< Type >::operator()(), cloudSolution::read(), and solverInfo::updateSolverInfo().
get()
template<class T > T get (const word & keyword, enum keyType::option matchOpt = keyType::REGEX) const
Definition at line 99 of file dictionaryTemplates.C.
References T.
Referenced by BreakupModel< CloudType >::BreakupModel(), rotorDiskSource::checkData(), CloudFunctionObjectList< CloudType >::CloudFunctionObjectList(), coalCloudList::coalCloudList(), Foam::dimensionedConstant(), Enum< injectionMethod >::get(), Foam::getLazyPair(), Foam::getRadius(), greyMeanAbsorptionEmission::greyMeanAbsorptionEmission(), viewFactor::initialise(), TurbulenceModel< Alpha, Rho, BasicTurbulenceModel, TransportModel >::New(), decompositionConstraint::New(), diameterModel::New(), profileModel::New(), CorrectionLimitingMethod::New(), ParticleStressModel::New(), TimeScaleModel::New(), coordinateRotation::New(), liquidProperties::New(), solidProperties::New(), thermophysicalFunction::New(), porousModel::New(), surfaceTensionModel::New(), NURBS3DVolume::New(), saturationModel::New(), massTransferModel::New(), aspectRatioModel::New(), dragModel::New(), heatTransferModel::New(), liftModel::New(), phaseTransferModel::New(), swarmCorrection::New(), turbulentDispersionModel::New(), virtualMassModel::New(), wallDampingModel::New(), wallLubricationModel::New(), blendingMethod::New(), faPatchField< Type >::New(), faePatchField< Type >::New(), cellCellStencil::New(), updateMethod::New(), liquidFilmBase::New(), heatExchangerModel::New(), fvsPatchField< Type >::New(), fvPatchField< Type >::New(), phaseModel::New(), pointPatchField< Type >::New(), Reaction< ReactionThermo >::New(), LduMatrix< Type, DType, LUType >::solver::New(), blendingMethod::New(), option::New(), polyPatch::New(), sampledSurface::New(), sampledSet::New(), functionObject::New(), LESdelta::New(), LESdelta::New(), optimisationManager::New(), optMeshMovement::New(), incompressiblePrimalSolver::New(), primalSolver::New(), adjointSolver::New(), incompressibleAdjointSolver::New(), adjointTurbulenceModel::New(), filmTurbulenceModel::New(), controlPointsDefinition::New(), dynamicCodeContext::operator const dictionary &(), Foam::operator>>(), plane::plane(), powerLawLopesdaCostaZone::powerLawLopesdaCostaZone(), solutionControl::read(), patchProbes::read(), binModel::read(), heatTransferCoeffModel::read(), histogramModel::read(), areaWrite::read(), timeControl::read(), sampledSurfaces::read(), multiphaseMangrovesSource::read(), multiphaseMangrovesTurbulenceModel::read(), Time::readDict(), mapDistributeBase::readDict(), SIMPLEControl::readIters(), SIMPLEControlSingleRun::readIters(), boundaryRegion::rename(), cellBitSet::select(), binModel::setCoordinateSystem(), Foam::unitSet(), wideBandAbsorptionEmission::wideBandAbsorptionEmission(), thermalBaffleFvPatchScalarField::write(), ensightWriter::writeCollated(), and ensightWriter::writeCollated().
getOrDefault()
template<class T > T getOrDefault (const word & keyword, const T & deflt, enum keyType::option matchOpt = keyType::REGEX) const
Definition at line 140 of file dictionaryTemplates.C.
References T.
Referenced by motionSmootherAlgo::checkMesh(), motionSmootherAlgo::checkMesh(), csvWriter::csvWriter(), displacementComponentLaplacianFvMotionSolver::displacementComponentLaplacianFvMotionSolver(), ensightSurfaceReader::ensightSurfaceReader(), exprResult::exprResult(), fixedMeanOutletInletFvPatchField< Type >::fixedMeanOutletInletFvPatchField(), fixedTemperatureConstraint::fixedTemperatureConstraint(), freestreamFvPatchField< Type >::freestreamFvPatchField(), Foam::getVerbosity(), gnuplotWriter::gnuplotWriter(), viewFactor::initialise(), dictionary::lookupOrDefault(), stepUpdate::New(), lineSearch::New(), fvGeometryScheme::New(), Foam::operator>>(), outletMappedUniformInletFvPatchField< Type >::outletMappedUniformInletFvPatchField(), rawWriter::rawWriter(), functionObjectList::read(), adjointEikonalSolver::read(), adjointMeshMovementSolver::read(), FIBase::read(), solutionControl::read(), probes::read(), sampledSets::read(), binModel::read(), resolutionIndexModel::read(), areaWrite::read(), directionalPressureGradientExplicitSource::read(), PDRblock::read(), functionObject::read(), timeControl::read(), sampledSurfaces::read(), moleFractions< ThermoType >::read(), externalFileCoupler::readDict(), adjointSolver::readDict(), temperatureDependent::readDict(), sampledMeshedSurface::sampleOnFaces(), cellTable::selectType(), slidingInterface::setTolerances(), UnsortedMeshedSurface< Face >::UnsortedMeshedSurface(), vtkWriter::vtkWriter(), VTKedgeFormat::write(), ensightWriter::writeCollated(), ensightWriter::writeCollated(), and xmgraceWriter::xmgraceWriter().
getOrAdd()
template<class T > T getOrAdd (const word & keyword, const T & deflt, enum keyType::option matchOpt = keyType::REGEX)
Definition at line 170 of file dictionaryTemplates.C.
References Foam::add(), and T.
Referenced by Switch::getOrAddToDict(), and dictionary::lookupOrAddDefault().
readEntry()
template<class T > bool readEntry (const word & keyword, T & val, enum keyType::option matchOpt = keyType::REGEX, IOobjectOption::readOption readOpt = IOobjectOption::MUST_READ) const
Definition at line 294 of file dictionaryTemplates.C.
References Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, IOobjectOption::isReadRequired(), Foam::name(), Foam::nl, and IOobjectOption::NO_READ.
Referenced by bladeModel::bladeModel(), BreakupModel< CloudType >::BreakupModel(), buoyancyEnergy::buoyancyEnergy(), buoyancyForce::buoyancyForce(), rotorDiskSource::checkData(), directionalPressureGradientExplicitSource::directionalPressureGradientExplicitSource(), motionSmootherAlgo::get(), meshRefinement::get(), dynamicMultiMotionSolverFvMesh::init(), viewFactor::initialise(), interRegionHeatTransferModel::interRegionHeatTransferModel(), ISAT< CompType, ThermoType >::ISAT(), lookupProfile::lookupProfile(), meanVelocityForce::meanVelocityForce(), multiBandAbsorption::multiBandAbsorption(), multiBandAbsorptionEmission::multiBandAbsorptionEmission(), multiBandTransmissivity::multiBandTransmissivity(), multiBandZoneAbsorptionEmission::multiBandZoneAbsorptionEmission(), nastranWriter::nastranWriter(), patchDistMethod::New(), combustionModel::New(), Foam::operator>>(), adjointRASModel::read(), kinematicSingleLayer::read(), probes::read(), sampledSets::read(), consumptionSpeed::read(), porosityModel::read(), areaWrite::read(), directionalPressureGradientExplicitSource::read(), sampledSurfaces::read(), smoothDelta::read(), multiphaseMangrovesSource::read(), multiphaseMangrovesTurbulenceModel::read(), reactionRateFlameArea::read(), doubleSigmoid::read(), sigmoid::read(), azizChen::read(), dampedCoulomb::read(), exponentialRepulsion::read(), lennardJones::read(), maitlandSmith::read(), harmonicSpring::read(), pitchForkRing::read(), restrainedHarmonicSpring::read(), Casson::read(), Foam::readBoxDim(), thermo::readControls(), Time::readDict(), externalFileCoupler::readDict(), constant::readDict(), rigidBodyMeshMotion::rigidBodyMeshMotion(), Sampled< Type >::Sampled(), multiphaseSystem::solveAlphas(), thermoSingleLayer::thermoSingleLayer(), variableHeatTransfer::variableHeatTransfer(), viscousDissipation::viscousDissipation(), and writer::writeSolution().
readIfPresent() [1/2]
template<class T > bool readIfPresent (const word & keyword, T & val, enum keyType::option matchOpt = keyType::REGEX) const
Definition at line 412 of file dictionaryTemplates.C.
References IOobjectOption::READ_IF_PRESENT.
Referenced by advectiveFvPatchField< Type >::advectiveFvPatchField(), basicThermo::basicThermo(), basicThermo::basicThermo(), basicThermo::basicThermo(), boundaryDataSurfaceReader::boundaryDataSurfaceReader(), valueAverageBase::calc(), motionSmootherAlgo::checkMesh(), coordSetWriter::coordSetWriter(), coupleGroupIdentifier::coupleGroupIdentifier(), distributedTriSurfaceMesh::distributedTriSurfaceMesh(), dlLibraryTable::dlLibraryTable(), Foam::getAnimationColour(), isoSurfaceParams::getFilterType(), Foam::getSurfaceName(), viewFactor::initialise(), objectivePtLosses::initialize(), objectiveUniformityPatch::initialize(), liquidFilmModel::liquidFilmModel(), liquidProperties::New(), faPatchField< Type >::New(), fvsPatchField< Type >::New(), fvPatchField< Type >::New(), pointPatchField< Type >::New(), polyPatch::New(), coordinateSystem::New(), objective::objective(), dlLibraryTable::open(), patchCellsSource::patchCellsSource(), pointHistory::pointHistory(), randomDecomp::randomDecomp(), kinematicSingleLayer::read(), patchProbes::read(), probes::read(), DeltaOmegaTildeDelta::read(), IDDESDelta::read(), maxDeltaxyz::read(), PrandtlDelta::read(), SLADelta::read(), vanDriestDelta::read(), pointHistory::read(), writeFreeSurface::read(), MRFZone::read(), porosityModel::read(), heatTransferCoeffModel::read(), areaWrite::read(), noiseModel::read(), surfaceNoise::read(), Foam::readBoxDim(), Time::readDict(), faPatchFieldBase::readDict(), fvPatchFieldBase::readDict(), pointPatchFieldBase::readDict(), liquidProperties::readIfPresent(), solidProperties::readIfPresent(), thermophysicalProperties::readIfPresent(), Switch::readIfPresent(), dictionary::readIfPresent(), Foam::readWriteOption(), binModel::setCoordinateSystem(), surfaceWriter::surfaceWriter(), thermalBaffleFvPatchScalarField::thermalBaffleFvPatchScalarField(), thermoSingleLayer::thermoSingleLayer(), updateMethod::updateMethod(), vanDriestDelta::vanDriestDelta(), topoSetSource::verbose(), writeFreeSurface::writeFreeSurface(), and x3dWriter::x3dWriter().
getCheck()
template<class T , class Predicate > T getCheck (const word & keyword, const Predicate & pred, enum keyType::option matchOpt = keyType::REGEX) const
Definition at line 112 of file dictionaryTemplates.C.
References T.
Referenced by electrostaticDepositionFvPatchScalarField::electrostaticDepositionFvPatchScalarField(), and electricPotential::read().
getCheckOrDefault()
template<class T , class Predicate > T getCheckOrDefault (const word & keyword, const T & deflt, const Predicate & pred, enum keyType::option matchOpt = keyType::REGEX) const
Definition at line 201 of file dictionaryTemplates.C.
References Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, Foam::name(), and T.
getCheckOrAdd()
template<class T , class Predicate > T getCheckOrAdd (const word & keyword, const T & deflt, const Predicate & pred, enum keyType::option matchOpt = keyType::REGEX)
Definition at line 247 of file dictionaryTemplates.C.
References Foam::add(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, Foam::name(), and T.
readCheck()
template<class T , class Predicate > bool readCheck (const word & keyword, T & val, const Predicate & pred, enum keyType::option matchOpt = keyType::REGEX, IOobjectOption::readOption readOpt = IOobjectOption::MUST_READ) const
Definition at line 331 of file dictionaryTemplates.C.
References Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, IOobjectOption::isReadRequired(), Foam::name(), Foam::nl, and IOobjectOption::NO_READ.
readCheckIfPresent()
template<class T , class Predicate > bool readCheckIfPresent (const word & keyword, T & val, const Predicate & pred, enum keyType::option matchOpt = keyType::REGEX) const
Definition at line 431 of file dictionaryTemplates.C.
References IOobjectOption::READ_IF_PRESENT.
subDict() [1/2]
const Foam::dictionary & subDict (const word & keyword, enum keyType::option matchOpt = keyType::REGEX) const
Definition at line 452 of file dictionary.C.
References Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, and Foam::nl.
Referenced by sixDoFRigidBodyMotion::addConstraints(), sixDoFRigidBodyMotion::addRestraints(), valueAverageBase::calc(), Foam::dimensionedConstant(), argList::displayDoc(), extrudePatchMesh::extrudePatchMesh(), subModelBase::getBaseProperty(), humidityTemperatureCoupledMixedFvPatchScalarField::humidityTemperatureCoupledMixedFvPatchScalarField(), oversetFvPatchField< Type >::initEvaluate(), viewFactor::initialise(), multiBandZoneAbsorptionEmission::multiBandZoneAbsorptionEmission(), multiSolidBodyMotionSolver::multiSolidBodyMotionSolver(), LESModel< BasicTurbulenceModel >::New(), RASModel< BasicTurbulenceModel >::New(), phaseModel::New(), phaseModel::New(), optimisationManager::optimisationManager(), phaseSystem::phaseSystem(), plane::plane(), MRFZoneList::read(), porosityModelList::read(), PDRblock::read(), mapDistributeBase::readDict(), mapDistributePolyMesh::readDict(), adjointSolverManager::readDict(), adjointSolver::readDict(), liquidProperties::readIfPresent(), searchableSurfaces::searchableSurfaces(), runTimeCondition::setConditionDict(), cellSetOption::setSelection(), steadyOptimisation::steadyOptimisation(), twoPhaseSystem::twoPhaseSystem(), inverseDistance::update(), volBSplinesBase::volBSplinesBase(), and thermalBaffleFvPatchScalarField::write().
subDict() [2/2]
Foam::dictionary & subDict (const word & keyword, enum keyType::option matchOpt = keyType::REGEX)
Definition at line 472 of file dictionary.C.
References Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, Foam::nl, and Foam::search().
subDictOrAdd()
Foam::dictionary & subDictOrAdd (const word & keyword, enum keyType::option matchOpt = keyType::REGEX)
Definition at line 492 of file dictionary.C.
References Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, Foam::nl, and Foam::search().
Referenced by mappedPatchBase::writeDict().
subOrEmptyDict()
Foam::dictionary subOrEmptyDict (const word & keyword, enum keyType::option matchOpt = keyType::REGEX, const bool mandatory = false) const
Definition at line 532 of file dictionary.C.
References Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, IOWarningInFunction, and Foam::nl.
Referenced by cloudSolution::cloudSolution(), updateMethod::coeffsDict(), subModelBase::getModelDict(), sensitivityBezierFI::read(), noiseModel::read(), adjointEikonalSolver::readDict(), adjointMeshMovementSolver::readDict(), surfaceWriter::surfaceWriter(), and gltfWriter::writeTemplate().
optionalSubDict()
const Foam::dictionary & optionalSubDict (const word & keyword, enum keyType::option matchOpt = keyType::REGEX) const
Definition at line 571 of file dictionary.C.
References Foam::endl(), and IOWarningInFunction.
Referenced by diameterModel::New(), liquidProperties::New(), solidProperties::New(), sampledSet::New(), plane::plane(), motionSolver::read(), DeltaOmegaTildeDelta::read(), vanDriestDelta::read(), porosityModel::read(), trimModel::read(), diameterModel::read(), solidBodyMotionFunction::read(), Arrhenius< ViscousModel >::read(), BirdCarreau::read(), Casson::read(), CrossPowerLaw::read(), HerschelBulkley::read(), powerLaw::read(), strainRateFunction::read(), cellBitSet::select(), and vanDriestDelta::vanDriestDelta().
toc()
Foam::wordList toc () const
Definition at line 599 of file dictionary.C.
References e, and n.
Referenced by oversetFvMeshBase::interpolateFields(), Foam::operator>>(), and cloudSolution::read().
sortedToc() [1/3]
Foam::wordList sortedToc () const
Definition at line 613 of file dictionary.C.
Referenced by equationInitialResidualCondition::apply(), and solverFieldSelection::updateSelection().
sortedToc() [2/3]
template<class Compare > wordList sortedToc (const Compare & comp) const
keys()
Foam::List< Foam::keyType > keys (bool patterns = false) const
Definition at line 619 of file dictionary.C.
References e, n, and PtrList< T >::resize().
substituteKeyword()
bool substituteKeyword (const word & keyword, bool mergeEntry = false)
Definition at line 388 of file dictionary.C.
References Foam::add(), e, and keyType::REGEX_RECURSIVE.
substituteScopedKeyword()
bool substituteScopedKeyword (const word & keyword, bool mergeEntry = false)
Definition at line 420 of file dictionary.C.
References Foam::add(), e, and keyType::REGEX_RECURSIVE.
add() [1/9]
Foam::entry * add (entry * entryPtr, bool mergeEntry = false)
Definition at line 637 of file dictionary.C.
References fileName::concat(), entry::dict(), Foam::endl(), IOWarningInFunction, and Foam::name().
Referenced by adjointSolverManager::adjointSolverManager(), Foam::copyFilteredDict(), fvMeshTools::createDummyFvMeshFiles(), dimensioned< scalar >::dimensioned(), Foam::getOrAdd(), refinementParameters::getZoneInfo(), dictionary::makeScopedDict(), namedBlock::namedBlock(), namedVertex::namedVertex(), entry::New(), cellTable::operator=(), optimisationManager::optimisationManager(), argList::parse(), runTimeCondition::setConditionDict(), uniformInterpolationTable< Type >::write(), eulerianParticle::writeDict(), mappedPatchBase::writeDict(), decomposedBlockData::writeExtraHeaderContent(), IOobject::writeHeaderContent(), streamLineBase::writeToFile(), and surfaceFieldValue::writeValues().
add() [2/9]
Foam::entry * add (const entry & e, bool mergeEntry = false)
Definition at line 716 of file dictionary.C.
References Foam::add(), GeometricField< Type, PatchField, GeoMesh >::clone(), and e.
add() [3/9]
Foam::entry * add (const keyType & k, const word & v, bool overwrite = false)
Definition at line 722 of file dictionary.C.
References Foam::add(), and k.
add() [4/9]
Foam::entry * add (const keyType & k, const string & v, bool overwrite = false)
Definition at line 733 of file dictionary.C.
References Foam::add(), and k.
add() [5/9]
Foam::entry * add (const keyType & k, const label v, bool overwrite = false)
Definition at line 744 of file dictionary.C.
References Foam::add(), and k.
add() [6/9]
Foam::entry * add (const keyType & k, const scalar v, bool overwrite = false)
Definition at line 755 of file dictionary.C.
References Foam::add(), and k.
add() [7/9]
Foam::entry * add (const keyType & k, const dictionary & d, bool mergeEntry = false)
Definition at line 766 of file dictionary.C.
References Foam::add(), and k.
add() [8/9]
template<class T > entry * add (const keyType & k, const T & v, bool overwrite = false)
set() [1/5]
Foam::entry * set (entry * entryPtr)
Definition at line 777 of file dictionary.C.
References Foam::add(), dictionary::clear(), keyType::REGEX, and Foam::search().
Referenced by valueAverageBase::calc(), data::data(), boundaryRegion::rename(), structuredDecomp::structuredDecomp(), ZoneMesh< ZoneType, MeshType >::updateMetaData(), solution::upgradeSolverDict(), averageCondition::write(), decomposedBlockData::writeExtraHeaderContent(), IOobject::writeHeaderContent(), and mappedPatchBase::writeIOField().
set() [2/5]
Foam::entry * set (const entry & e)
Definition at line 799 of file dictionary.C.
References GeometricField< Type, PatchField, GeoMesh >::clone(), and e.
set() [3/5]
Foam::entry * set (const keyType & k, const dictionary & v)
Definition at line 805 of file dictionary.C.
References k.
set() [4/5]
template<class T > entry * set (const keyType & k, const T & v)
remove()
bool remove (const word & keyword)
Definition at line 575 of file dictionarySearch.C.
References UPtrList< T >::begin().
changeKeyword()
bool changeKeyword (const keyType & oldKeyword, const keyType & newKeyword, bool overwrite = false)
Definition at line 603 of file dictionarySearch.C.
References UPtrList< T >::begin(), Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, IOWarningInFunction, Foam::name(), and Foam::nl.
merge()
bool merge (const dictionary & dict)
Definition at line 811 of file dictionary.C.
References Foam::abort(), Foam::add(), GeometricField< Type, PatchField, GeoMesh >::clone(), dict, e, Foam::FatalIOError, FatalIOErrorInFunction, and Foam::nl.
Referenced by Foam::combineFormatOptions(), and Time::readDict().
clear()
void clear ()
Definition at line 856 of file dictionary.C.
Referenced by Foam::operator>>(), dictionary::set(), and data::setSolverPerformance().
transfer()
void transfer (dictionary & dict)
Definition at line 865 of file dictionary.C.
References dict, dictionary::name(), and Foam::name().
Referenced by dictionary::dictionary(), dictionary::dictionary(), csvTableReader< Type >::operator()(), and meshRefinement::updateMesh().
checkITstream()
void checkITstream (const ITstream & is, const word & keyword) const
Definition at line 250 of file dictionary.C.
References JobInfo::constructed, Foam::exit(), Foam::FatalIOError, Foam::nl, and UPtrList< T >::size().
Referenced by Table< Type >::Table().
read() [1/2]
bool read (Istream & is)
Definition at line 134 of file dictionaryIO.C.
References Foam::read().
Referenced by dictionary::dictionary(), dictionary::dictionary(), and Foam::operator>>().
read() [2/2]
bool read (Istream & is, bool keepHeader)
Definition at line 70 of file dictionaryIO.C.
References token::BEGIN_BLOCK, token::END_BLOCK, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, entry::GLOBAL, InfoInFunction, Foam::name(), entry::New(), and Foam::nl.
writeEntry() [1/2]
void writeEntry (Ostream & os) const
Definition at line 157 of file dictionaryIO.C.
References Ostream::beginBlock(), dictName(), Ostream::endBlock(), and os().
Referenced by dictionaryEntry::write().
writeEntry() [2/2]
void writeEntry (const keyType & keyword, Ostream & os) const
Definition at line 165 of file dictionaryIO.C.
References Ostream::beginBlock(), Ostream::endBlock(), and os().
writeEntries()
void writeEntries (Ostream & os, const bool extraNewLine = false) const
Definition at line 173 of file dictionaryIO.C.
References e, Foam::endl(), IOstream::good(), Foam::name(), Foam::nl, dictionary::null, os(), and WarningInFunction.
Referenced by Foam::writeJobDict().
write()
void write (Ostream & os, const bool subDict = true) const
Definition at line 199 of file dictionaryIO.C.
References Ostream::beginBlock(), Ostream::endBlock(), Foam::nl, and os().
Referenced by Foam::operator<<(), velocityFilmShellFvPatchVectorField::write(), thermalShellFvPatchScalarField::write(), vibrationShellFvPatchScalarField::write(), dictionaryListEntry::write(), baseIOdictionary::writeData(), fvExprDriverWriter::writeData(), and fieldDictionary::writeData().
csearch()
Foam::dictionary::const_searcher csearch (const word & keyword, enum keyType::option matchOpt = keyType::REGEX) const
Definition at line 257 of file dictionarySearch.C.
References UPtrList< T >::cbegin(), dictionary::null, keyType::RECURSIVE, keyType::REGEX, and PtrList< T >::set().
Referenced by dictionary::csearchCompat(), and meshRefinement::subDict().
search() [1/2]
Foam::dictionary::const_searcher search (const word & keyword, enum keyType::option matchOpt = keyType::REGEX) const
Definition at line 295 of file dictionarySearch.C.
search() [2/2]
Foam::dictionary::searcher search (const word & keyword, enum keyType::option matchOpt = keyType::REGEX)
Definition at line 305 of file dictionarySearch.C.
csearchScoped()
Foam::dictionary::const_searcher csearchScoped (const word & keyword, enum keyType::option matchOpt) const
Definition at line 317 of file dictionarySearch.C.
References string::contains(), dictionary::null, and keyType::RECURSIVE.
searchScoped() [1/2]
Foam::dictionary::const_searcher searchScoped (const word & keyword, enum keyType::option matchOpt) const
Definition at line 347 of file dictionarySearch.C.
searchScoped() [2/2]
Foam::dictionary::searcher searchScoped (const word & keyword, enum keyType::option matchOpt)
Definition at line 357 of file dictionarySearch.C.
cfindScopedDict()
const Foam::dictionary * cfindScopedDict (const fileName & dictPath) const
Definition at line 369 of file dictionarySearch.C.
References fileName::clean(), fileName::components(), UPtrList< T >::empty(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, Foam::nl, dictionary::null, and path().
findScopedDict() [1/2]
const Foam::dictionary * findScopedDict (const fileName & dictPath) const
Definition at line 456 of file dictionarySearch.C.
findScopedDict() [2/2]
Foam::dictionary * findScopedDict (const fileName & dictPath)
Definition at line 465 of file dictionarySearch.C.
makeScopedDict()
Foam::dictionary * makeScopedDict (const fileName & dictPath)
Definition at line 475 of file dictionarySearch.C.
References dictionary::add(), fileName::clean(), UPtrList< T >::empty(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, Foam::nl, dictionary::null, path(), and Foam::stringOps::split().
csearchCompat()
Foam::dictionary::const_searcher csearchCompat (const word & keyword, std::initializer_list< std::pair< const char *, int > > compat, enum keyType::option matchOpt = keyType::REGEX) const
Definition at line 26 of file dictionaryCompat.C.
References dictionary::csearch(), UPtrList< T >::first(), error::master(), Foam::nl, dictionary::relativeName(), word::validate(), and error::warnAboutAge().
Referenced by functionObject::New().
findCompat()
const Foam::entry * findCompat (const word & keyword, std::initializer_list< std::pair< const char *, int > > compat, enum keyType::option matchOpt) const
Definition at line 67 of file dictionaryCompat.C.
Referenced by Function1< scalar >::NewCompat(), and PatchFunction1< scalar >::NewIfPresent().
foundCompat()
bool foundCompat (const word & keyword, std::initializer_list< std::pair< const char *, int > > compat, enum keyType::option matchOpt = keyType::REGEX) const
Definition at line 78 of file dictionaryCompat.C.
lookupEntryCompat()
const Foam::entry & lookupEntryCompat (const word & keyword, std::initializer_list< std::pair< const char *, int > > compat, enum keyType::option matchOpt) const
Definition at line 89 of file dictionaryCompat.C.
References Foam::exit(), Foam::FatalIOError, and FatalIOErrorInFunction.
lookupCompat()
Foam::ITstream & lookupCompat (const word & keyword, std::initializer_list< std::pair< const char *, int > > compat, enum keyType::option matchOpt = keyType::REGEX) const
Definition at line 110 of file dictionaryCompat.C.
getCompat()
template<class T > T getCompat (const word & keyword, std::initializer_list< std::pair< const char *, int > > compat, enum keyType::option matchOpt = keyType::REGEX) const
Definition at line 126 of file dictionaryTemplates.C.
References T.
Referenced by laminarModel< BasicTurbulenceModel >::New(), LESModel< BasicTurbulenceModel >::New(), RASModel< BasicTurbulenceModel >::New(), motionSolver::New(), and plane::plane().
getOrDefaultCompat()
template<class T > T getOrDefaultCompat (const word & keyword, std::initializer_list< std::pair< const char *, int > > compat, const T & deflt, enum keyType::option matchOpt = keyType::REGEX) const
Definition at line 452 of file dictionaryTemplates.C.
References T.
Referenced by Foam::getSurfaceName().
readCompat()
template<class T > bool readCompat (const word & keyword, std::initializer_list< std::pair< const char *, int > > compat, T & val, enum keyType::option matchOpt = keyType::REGEX, IOobjectOption::readOption readOpt = IOobjectOption::MUST_READ) const
Definition at line 374 of file dictionaryTemplates.C.
References Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, IOobjectOption::isReadRequired(), Foam::name(), Foam::nl, and IOobjectOption::NO_READ.
readIfPresentCompat()
template<class T > bool readIfPresentCompat (const word & keyword, std::initializer_list< std::pair< const char *, int > > compat, T & val, enum keyType::option matchOpt = keyType::REGEX) const
Definition at line 483 of file dictionaryTemplates.C.
References IOobjectOption::READ_IF_PRESENT.
Referenced by solidProperties::readIfPresent().
operator=()
void operator= (const dictionary & rhs)
Definition at line 880 of file dictionary.C.
References Foam::add(), clear(), GeometricField< Type, PatchField, GeoMesh >::clone(), e, dictionary::name(), and Foam::name().
Referenced by dictionary::dictionary(), IOdictionary::IOdictionary(), localIOdictionary::localIOdictionary(), baseIOdictionary::operator=(), and unwatchedIOdictionary::unwatchedIOdictionary().
operator+=()
void operator+= (const dictionary & rhs)
Definition at line 900 of file dictionary.C.
References Foam::abort(), Foam::add(), GeometricField< Type, PatchField, GeoMesh >::clone(), e, Foam::FatalIOError, FatalIOErrorInFunction, and Foam::nl.
operator|=()
void operator|= (const dictionary & rhs)
Definition at line 917 of file dictionary.C.
References Foam::abort(), Foam::add(), GeometricField< Type, PatchField, GeoMesh >::clone(), e, Foam::FatalIOError, FatalIOErrorInFunction, found, and Foam::nl.
operator<<=()
void operator<<= (const dictionary & rhs)
Definition at line 937 of file dictionary.C.
References Foam::abort(), GeometricField< Type, PatchField, GeoMesh >::clone(), e, Foam::FatalIOError, FatalIOErrorInFunction, and Foam::nl.
getBool()
bool getBool (const word & keyword, enum keyType::option matchOpt = keyType::REGEX) const inline
Same as get< bool >(const word&, keyType::option)
Definition at line 1279 of file dictionary.H.
getLabel()
label getLabel (const word & keyword, enum keyType::option matchOpt = keyType::REGEX) const inline
Same as get< label >(const word&, keyType::option)
Definition at line 1280 of file dictionary.H.
getScalar()
scalar getScalar (const word & keyword, enum keyType::option matchOpt = keyType::REGEX) const inline
Same as get< scalar >(const word&, keyType::option)
Definition at line 1281 of file dictionary.H.
getString()
string getString (const word & keyword, enum keyType::option matchOpt = keyType::REGEX) const inline
Same as get< string >(const word&, keyType::option)
Definition at line 1282 of file dictionary.H.
Referenced by Reaction< ThermoType >::write().
getWord()
word getWord (const word & keyword, enum keyType::option matchOpt = keyType::REGEX) const inline
Same as get< word >(const word&, keyType::option)
Definition at line 1283 of file dictionary.H.
Referenced by fanMomentumSource::fanMomentumSource().
getFileName()
fileName getFileName (const word & keyword, enum keyType::option matchOpt = keyType::REGEX) const inline
Same as get< fileName >(const word&, keyType::option)
Definition at line 1284 of file dictionary.H.
lookupOrDefault() [1/2]
template<class T > T lookupOrDefault (const word & keyword, const T & deflt, enum keyType::option matchOpt = keyType::REGEX) const inline
Definition at line 1298 of file dictionary.H.
lookupOrAddDefault() [1/2]
template<class T > T lookupOrAddDefault (const word & keyword, const T & deflt, enum keyType::option matchOpt = keyType::REGEX) inline
Definition at line 1317 of file dictionary.H.
operator[]()
ITstream & operator[] (const word & keyword) const inline
Definition at line 1330 of file dictionary.H.
found() [2/2]
bool found (const word & keyword, bool recursive, bool patternMatch = true) const inline
Definition at line 1338 of file dictionary.H.
References found.
lookupEntryPtr() [1/2]
entry * lookupEntryPtr (const word & keyword, bool recursive, bool patternMatch) inline
Definition at line 1351 of file dictionary.H.
References dictionary::findEntry().
lookupEntryPtr() [2/2]
const entry * lookupEntryPtr (const word & keyword, bool recursive, bool patternMatch) const inline
Definition at line 1364 of file dictionary.H.
References dictionary::findEntry().
lookupScopedEntryPtr()
const entry * lookupScopedEntryPtr (const word & keyword, bool recursive, bool patternMatch) const inline
Definition at line 1377 of file dictionary.H.
References dictionary::findScoped().
subDictPtr() [1/2]
const dictionary * subDictPtr (const word & keyword) const inline
Definition at line 1394 of file dictionary.H.
References dictionary::findDict(), and keyType::REGEX.
Referenced by basicChemistryModel::New().
subDictPtr() [2/2]
dictionary * subDictPtr (const word & keyword) inline
Definition at line 1406 of file dictionary.H.
References dictionary::findDict(), and keyType::REGEX.
lookupEntry() [2/2]
const entry & lookupEntry (const word & keyword, bool recursive, bool patternMatch) const inline
Definition at line 1414 of file dictionary.H.
References dictionary::lookupEntry().
lookup() [2/2]
ITstream & lookup (const word & keyword, bool recursive, bool patternMatch = true) const inline
Definition at line 1427 of file dictionary.H.
lookupOrDefault() [2/2]
template<class T > T lookupOrDefault (const word & keyword, const T & deflt, bool recursive, bool patternMatch = true) const inline
Definition at line 1441 of file dictionary.H.
References dictionary::getOrDefault().
lookupOrAddDefault() [2/2]
template<class T > T lookupOrAddDefault (const word & keyword, const T & deflt, bool recursive, bool patternMatch = true) inline
Definition at line 1456 of file dictionary.H.
References dictionary::getOrAdd().
readIfPresent() [2/2]
template<class T > bool readIfPresent (const word & keyword, T & val, bool recursive, bool patternMatch = true) const inline
Definition at line 1471 of file dictionary.H.
References dictionary::readIfPresent().
lookupType()
template<class T > T lookupType (const word & keyword, bool recursive = false, bool patternMatch = true) const inline
Definition at line 1491 of file dictionary.H.
sortedToc() [3/3]
template<class Compare > Foam::wordList sortedToc (const Compare & comp) const
Definition at line 78 of file dictionaryTemplates.C.
add() [9/9]
template<class T > Foam::entry * add (const keyType & k, const T & v, bool overwrite)
Definition at line 85 of file dictionaryTemplates.C.
References Foam::add(), and k.
set() [5/5]
template<class T > Foam::entry * set (const keyType & k, const T & v)
Definition at line 92 of file dictionaryTemplates.C.
References k.
Friends And Related Symbol Documentation
entry
friend class entry friend
Definition at line 261 of file dictionary.H.
operator>>
Istream & operator>> (Istream & is, dictionary & dict) friend
operator<<
Ostream & operator<< (Ostream & os, const dictionary & dict) friend
Member Data Documentation
const_searcher
friend const_searcher
Definition at line 264 of file dictionary.H.
searcher
friend searcher
Definition at line 265 of file dictionary.H.
writeOptionalEntries
int writeOptionalEntries static
Definition at line 373 of file dictionary.H.
Referenced by dictionary::reportOptional().
null
const Foam::dictionary null static
Definition at line 376 of file dictionary.H.
Referenced by cellModel::cellModel(), dictionary::cfindScopedDict(), entry::clone(), codedMixedFvPatchField< Type >::codeContext(), codedFunctionObject::codeContext(), Stokes< BasicTurbulenceModel >::coeffDict(), dictionary::csearch(), dictionary::csearchScoped(), primitiveEntry::dict(), primitiveEntry::dict(), Foam::dimensionedConstant(), writerCaching::fieldsDict(), dictionary::isNullDict(), dictionary::makeScopedDict(), functionObjectList::New(), RASModelVariables::New(), lduMatrix::preconditioner::New(), entry::New(), phase::iNew::operator()(), motionSolver::iNew::operator()(), phaseModel::iNew::operator()(), sizeGroup::iNew::operator()(), Foam::functionObjects::operator>>(), Foam::operator>>(), Foam::operator>>(), decompositionMethod::optionalRegionDict(), primitiveEntry::primitiveEntry(), meshRefinement::subDict(), triSurfaceMeshPointSet::triSurfaceMeshPointSet(), dynamicCodeContext::valid(), and dictionary::writeEntries().
reportingOutput
Foam::refPtr< Foam::OSstream > reportingOutput static
Definition at line 379 of file dictionary.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/db/dictionary/dictionary.H
src/OpenFOAM/db/dictionary/dictionary.C
src/OpenFOAM/db/dictionary/dictionaryCompat.C
src/OpenFOAM/db/dictionary/dictionaryI.H
src/OpenFOAM/db/dictionary/dictionaryIO.C
src/OpenFOAM/db/dictionary/dictionarySearch.C
src/OpenFOAM/db/dictionary/dictionaryTemplates.C