OpenFOAM: thermoSingleLayer Class Reference
thermoSingleLayer Class Reference
Thermodynamic form of single-cell layer surface film model.
#include <thermoSingleLayer.H>
Public Member Functions
TypeName ("thermoSingleLayer")
thermoSingleLayer (const word &modelType, const fvMesh &mesh, const dimensionedVector &g, const word &regionType, const bool readFields=true)
virtual ~thermoSingleLayer ()
const SLGThermo & thermo () const
virtual const volScalarField & Cp () const
virtual const volScalarField & kappa () const
virtual const volScalarField & T () const
virtual const volScalarField & Ts () const
virtual const volScalarField & Tw () const
virtual const volScalarField & hs () const
tmp< scalarField > hs (const scalarField &T, const label patchi) const
tmp< volScalarField > hs (const volScalarField &T) const
tmp< volScalarField > T (const volScalarField &hs) const
virtual void addSources (const label patchi, const label facei, const scalar massSource, const vector &momentumSource, const scalar pressureSource, const scalar energySource)
const volScalarField & hsSp () const
const volScalarField & hsSpPrimary () const
const volScalarField & TPrimary () const
const PtrList< volScalarField > & YPrimary () const
const heatTransferModel & htcs () const
const heatTransferModel & htcw () const
const phaseChangeModel & phaseChange () const
const filmRadiationModel & radiation () const
tmp< scalarField > qconvw (const label patchi) const
tmp< scalarField > qconvp (const label patchi) const
virtual void preEvolveRegion ()
virtual void evolveRegion ()
virtual tmp< volScalarField::Internal > Srho () const
virtual tmp< volScalarField::Internal > Srho (const label i) const
virtual tmp< volScalarField::Internal > Sh () const
virtual void info ()
Public Member Functions inherited from kinematicSingleLayer
TypeName ("kinematicSingleLayer")
kinematicSingleLayer (const word &modelType, const fvMesh &mesh, const dimensionedVector &g, const word &regionType, const bool readFields=true)
virtual ~kinematicSingleLayer ()
virtual scalar CourantNumber () const
Switch momentumPredictor () const
label nOuterCorr () const
label nCorr () const
label nNonOrthCorr () const
const dimensionedScalar & deltaSmall () const
const volScalarField & mu () const
const volScalarField & sigma () const
const volScalarField & delta () const
const volScalarField & alpha () const
virtual const volVectorField & U () const
virtual const volVectorField & Us () const
virtual const volVectorField & Uw () const
virtual const volScalarField & deltaRho () const
virtual const surfaceScalarField & phi () const
virtual const volScalarField & rho () const
virtual tmp< volScalarField > primaryMassTrans () const
virtual const volScalarField & cloudMassTrans () const
virtual const volScalarField & cloudDiameterTrans () const
volVectorField & USpPrimary ()
volScalarField & pSpPrimary ()
volScalarField & rhoSpPrimary ()
volVectorField & USp ()
volScalarField & pSp ()
volScalarField & rhoSp ()
const volVectorField & USp () const
const volScalarField & pSp () const
const volScalarField & rhoSp () const
const volVectorField & UPrimary () const
const volScalarField & pPrimary () const
const volScalarField & rhoPrimary () const
const volScalarField & muPrimary () const
const filmThermoModel & filmThermo () const
injectionModelList & injection ()
transferModelList & transfer ()
const filmTurbulenceModel & turbulence () const
tmp< volScalarField > mass () const
tmp< volScalarField > deltaMass () const
tmp< volScalarField > gNorm () const
tmp< volScalarField > gNormClipped () const
tmp< volVectorField > gTan () const
tmp< vectorField > gTan (const label patchI) const
virtual void postEvolveRegion ()
Public Member Functions inherited from surfaceFilmRegionModel
TypeName ("surfaceFilmRegionModel")
surfaceFilmRegionModel (const word &modelType, const fvMesh &mesh, const dimensionedVector &g, const word &regionType)
virtual ~surfaceFilmRegionModel ()
const dimensionedVector & g () const
virtual void evolve ()
Public Member Functions inherited from surfaceFilmModel
TypeName ("surfaceFilmModel")
declareRunTimeSelectionTable (autoPtr, surfaceFilmModel, mesh,(const word &modelType, const fvMesh &mesh, const dimensionedVector &g, const word &regionType),(modelType, mesh, g, regionType))
surfaceFilmModel ()
virtual ~surfaceFilmModel ()
Public Member Functions inherited from singleLayerRegion
TypeName ("regionModel")
singleLayerRegion (const fvMesh &mesh, const word &regionType)
singleLayerRegion (const fvMesh &mesh, const word &regionType, const word &modelName, bool readFields=true)
virtual ~singleLayerRegion ()
virtual const volVectorField & nHat () const
virtual const volScalarField & magSf () const
virtual const labelList & passivePatchIDs () const
template<class Type >
wordList mappedFieldAndInternalPatchTypes () const
template<class Type >
wordList mappedPushedFieldPatchTypes () const
template<class Type >
Foam::wordList mappedFieldAndInternalPatchTypes () const
template<class Type >
Foam::wordList mappedPushedFieldPatchTypes () const
Public Member Functions inherited from regionModel
TypeName ("regionModel")
regionModel (const fvMesh &mesh, const word &regionType)
regionModel (const fvMesh &mesh, const word &regionType, const word &modelName, bool readFields=true)
regionModel (const fvMesh &mesh, const word &regionType, const word &modelName, const dictionary &dict, bool readFields=true)
virtual ~regionModel ()=default
const fvMesh & primaryMesh () const noexcept
const Time & time () const noexcept
Switch active () const noexcept
Switch infoOutput () const noexcept
const word & modelName () const noexcept
const fvMesh & regionMesh () const
fvMesh & regionMesh ()
const dictionary & coeffs () const noexcept
const dictionary & solution () const
const IOdictionary & outputProperties () const
IOdictionary & outputProperties ()
const labelList & primaryPatchIDs () const noexcept
const labelList & intCoupledPatchIDs () const noexcept
bool isCoupledPatch (const label regionPatchi) const
bool isRegionPatch (const label primaryPatchi) const
label regionPatchID (const label primaryPatchi) const
label nbrCoupledPatchID (const regionModel &nbrRegion, const label regionPatchi) const
template<class Type >
tmp< Foam::Field< Type > > mapRegionPatchField (const regionModel &nbrRegion, const label regionPatchi, const label nbrPatchi, const Field< Type > &nbrField, const bool flip=false) const
template<class Type >
tmp< Field< Type > > mapRegionPatchField (const regionModel &nbrRegion, const word &fieldName, const label regionPatchi, const bool flip=false) const
template<class Type >
tmp< Field< Type > > mapRegionPatchInternalField (const regionModel &nbrRegion, const word &fieldName, const label regionPatchi, const bool flip=false) const
template<class Type >
void toPrimary (const label regionPatchi, List< Type > &regionField) const
template<class Type >
void toRegion (const label regionPatchi, List< Type > &primaryFieldField) const
template<class Type , class CombineOp >
void toPrimary (const label regionPatchi, List< Type > &regionField, const CombineOp &cop) const
template<class Type , class CombineOp >
void toRegion (const label regionPatchi, List< Type > &primaryFieldField, const CombineOp &cop) const
template<class Type >
Foam::tmp< Foam::Field< Type > > mapRegionPatchField (const regionModel &nbrRegion, const label regionPatchi, const label nbrPatchi, const Field< Type > &nbrField, const bool flip) const
template<class Type >
Foam::tmp< Foam::Field< Type > > mapRegionPatchField (const regionModel &nbrRegion, const word &fieldName, const label regionPatchi, const bool flip) const
template<class Type >
Foam::tmp< Foam::Field< Type > > mapRegionPatchInternalField (const regionModel &nbrRegion, const word &fieldName, const label regionPatchi, const bool flip) const
Public Member Functions inherited from IOdictionary
IOdictionary (const IOobject &io, const dictionary *fallback=nullptr)
IOdictionary (const IOobject &io, const dictionary &dict)
IOdictionary (const IOobject &io, const word &wantedType, const dictionary *fallback=nullptr)
IOdictionary (const IOobject &io, Istream &is)
virtual ~IOdictionary ()=default
virtual bool global () const
virtual fileName filePath () const
Public Member Functions inherited from baseIOdictionary
TypeName ("dictionary")
baseIOdictionary (const baseIOdictionary &)=default
baseIOdictionary (baseIOdictionary &&)=default
virtual ~baseIOdictionary ()=default
baseIOdictionary (const IOobject &io, const dictionary *fallback=nullptr)
baseIOdictionary (const IOobject &io, const dictionary &dict)
baseIOdictionary (const IOobject &io, Istream &is)
const word & name () const
virtual bool readData (Istream &)
virtual bool writeData (Ostream &) const
void operator= (const baseIOdictionary &rhs)
void operator= (const dictionary &rhs)
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
regIOobject (const IOobject &io, const bool isTimeObject=false)
regIOobject (const regIOobject &rio)
regIOobject (const regIOobject &rio, bool registerCopy)
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
regIOobject (const IOobject &io, const regIOobject &rio)
virtual ~regIOobject ()
bool checkIn ()
bool checkOut ()
virtual void addWatch ()
bool registered () const noexcept
bool ownedByRegistry () const noexcept
bool store ()
void release (const bool unregister=false) noexcept
label eventNo () const noexcept
label & eventNo () noexcept
bool upToDate (const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
void setUpToDate ()
virtual void rename (const word &newName)
const dictionary * findMetaData () const noexcept
dictionary & getMetaData () noexcept
void removeMetaData ()
virtual void updateMetaData ()
bool headerOk ()
Istream & readStream (const word &, const bool readOnProc=true)
void close ()
virtual label addWatch (const fileName &)
const labelList & watchIndices () const noexcept
labelList & watchIndices () noexcept
virtual bool modified () const
virtual bool readIfModified ()
virtual bool writeObject (IOstreamOption streamOpt, const bool writeOnProc) const
virtual bool write (const bool writeOnProc=true) const
void operator= (const IOobject &io)
virtual bool writeObject (IOstreamOption::streamFormat fmt, IOstreamOption::versionNumber ver, IOstreamOption::compressionType cmp, const bool writeOnProc) const
Public Member Functions inherited from IOobject
TypeName ("IOobject")
IOobject (const IOobject &)=default
virtual ~IOobject ()=default
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const fileName &path, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const fileName &path, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const IOobject &io, const objectRegistry &registry)
IOobject (const IOobject &io, const word &name)
IOobject (const IOobject &io, const word &name, const fileName &local)
IOobject (const IOobject &io, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt)
IOobject (const IOobject &io, IOobjectOption::registerOption regOpt)
autoPtr< IOobject > clone () const
autoPtr< IOobject > clone (const objectRegistry &registry) const
const objectRegistry & db () const noexcept
const Time & time () const noexcept
const word & name () const noexcept
const word & headerClassName () const noexcept
word & headerClassName () noexcept
const string & note () const noexcept
string & note () noexcept
unsigned labelByteSize () const noexcept
unsigned scalarByteSize () const noexcept
void resetHeader (const word &newName=word::null)
bool hasHeaderClass () const noexcept
template<class Type >
bool isHeaderClass () const
template<class Type >
bool isHeaderClassName () const
word group () const
word member () const
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const noexcept
fileName & instance () noexcept
const fileName & local () const noexcept
fileName path () const
fileName path (const word &instance, const fileName &local=fileName::null) const
fileName objectPath () const
fileName objectRelPath () const
fileName localFilePath (const word &typeName, const bool search=true) const
fileName globalFilePath (const word &typeName, const bool search=true) const
IOstreamOption parseHeader (const dictionary &headerDict)
bool readHeader (Istream &is)
bool readHeader (dictionary &headerDict, Istream &is)
template<class Type >
bool typeHeaderOk (const bool checkType=true, const bool search=true, const bool verbose=true)
template<class Type >
void warnNoRereading () const
bool writeHeader (Ostream &os) const
bool writeHeader (Ostream &os, const word &objectType) const
void writeHeader (dictionary &dict, IOstreamOption streamOpt) const
void writeHeader (dictionary &dict, const word &objectType, IOstreamOption streamOpt) const
bool good () const noexcept
bool bad () const noexcept
InfoProxy< IOobject > info () const noexcept
void operator= (const IOobject &io)
template<>
bool isHeaderClass () const
template<class StringType >
Foam::word groupName (StringType base, const word &group)
Public Member Functions inherited from IOobjectOption
constexpr IOobjectOption (readOption rOpt=readOption::NO_READ, writeOption wOpt=writeOption::NO_WRITE, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (readOption rOpt, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (writeOption wOpt, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (registerOption registerObject, bool globalObject=false) noexcept
constexpr IOobjectOption (readOption rOpt, writeOption wOpt, bool registerObject, bool globalObject=false) noexcept
constexpr IOobjectOption (bool registerObject, bool globalObject=false) noexcept
readOption readOpt () const noexcept
readOption readOpt (readOption opt) noexcept
writeOption writeOpt () const noexcept
writeOption writeOpt (writeOption opt) noexcept
bool registerObject () const noexcept
bool registerObject (bool on) noexcept
bool globalObject () const noexcept
bool globalObject (bool on) noexcept
bool isAnyRead () const noexcept
bool isReadRequired () const noexcept
bool isReadOptional () const noexcept
readOption & readOpt () noexcept
writeOption & writeOpt () noexcept
bool & registerObject () noexcept
bool & globalObject () noexcept
Public Member Functions inherited from dictionary
ClassName ("dictionary")
dictionary ()
dictionary (const fileName &name)
dictionary (const fileName &name, const dictionary &parentDict, Istream &is, bool keepHeader=false)
dictionary (Istream &is)
dictionary (Istream &is, bool keepHeader)
dictionary (const dictionary &parentDict, const dictionary &dict)
dictionary (const dictionary &dict)
dictionary (const dictionary *dict)
dictionary (const dictionary &parentDict, dictionary &&dict)
dictionary (dictionary &&dict)
autoPtr< dictionary > clone () const
virtual ~dictionary ()
const fileName & name () const noexcept
fileName & name () noexcept
word dictName () const
fileName relativeName (const bool caseTag=false) const
bool isNullDict () const noexcept
const dictionary & parent () const noexcept
const dictionary & topDict () const
label startLineNumber () const
label endLineNumber () const
SHA1Digest digest () const
tokenList tokens () const
const entry * findEntry (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
entry * findEntry (const word &keyword, enum keyType::option matchOpt=keyType::REGEX)
bool found (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
const entry * findScoped (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
const dictionary * findDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
dictionary * findDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX)
bool isDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
const entry & lookupEntry (const word &keyword, enum keyType::option matchOpt) const
ITstream & lookup (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
template<class T >
T get (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
template<class T >
T getOrDefault (const word &keyword, const T &deflt, enum keyType::option matchOpt=keyType::REGEX) const
template<class T >
T getOrAdd (const word &keyword, const T &deflt, enum keyType::option matchOpt=keyType::REGEX)
template<class T >
bool readEntry (const word &keyword, T &val, enum keyType::option matchOpt=keyType::REGEX, IOobjectOption::readOption readOpt=IOobjectOption::MUST_READ) const
template<class T >
bool readIfPresent (const word &keyword, T &val, enum keyType::option matchOpt=keyType::REGEX) const
template<class T , class Predicate >
T getCheck (const word &keyword, const Predicate &pred, enum keyType::option matchOpt=keyType::REGEX) const
template<class T , class Predicate >
T getCheckOrDefault (const word &keyword, const T &deflt, const Predicate &pred, enum keyType::option matchOpt=keyType::REGEX) const
template<class T , class Predicate >
T getCheckOrAdd (const word &keyword, const T &deflt, const Predicate &pred, enum keyType::option matchOpt=keyType::REGEX)
template<class T , class Predicate >
bool readCheck (const word &keyword, T &val, const Predicate &pred, enum keyType::option matchOpt=keyType::REGEX, IOobjectOption::readOption readOpt=IOobjectOption::MUST_READ) const
template<class T , class Predicate >
bool readCheckIfPresent (const word &keyword, T &val, const Predicate &pred, enum keyType::option matchOpt=keyType::REGEX) const
const dictionary & subDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
dictionary & subDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX)
dictionary & subDictOrAdd (const word &keyword, enum keyType::option matchOpt=keyType::REGEX)
dictionary subOrEmptyDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX, const bool mandatory=false) const
const dictionary & optionalSubDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
wordList toc () const
wordList sortedToc () const
template<class Compare >
wordList sortedToc (const Compare &comp) const
List< keyType > keys (bool patterns=false) const
bool substituteKeyword (const word &keyword, bool mergeEntry=false)
bool substituteScopedKeyword (const word &keyword, bool mergeEntry=false)
entry * add (entry *entryPtr, bool mergeEntry=false)
entry * add (const entry &e, bool mergeEntry=false)
entry * add (const keyType &k, const word &v, bool overwrite=false)
entry * add (const keyType &k, const string &v, bool overwrite=false)
entry * add (const keyType &k, const label v, bool overwrite=false)
entry * add (const keyType &k, const scalar v, bool overwrite=false)
entry * add (const keyType &k, const dictionary &d, bool mergeEntry=false)
template<class T >
entry * add (const keyType &k, const T &v, bool overwrite=false)
entry * set (entry *entryPtr)
entry * set (const entry &e)
entry * set (const keyType &k, const dictionary &v)
template<class T >
entry * set (const keyType &k, const T &v)
bool remove (const word &keyword)
bool changeKeyword (const keyType &oldKeyword, const keyType &newKeyword, bool overwrite=false)
bool merge (const dictionary &dict)
void clear ()
void transfer (dictionary &dict)
void checkITstream (const ITstream &is, const word &keyword) const
bool read (Istream &is)
bool read (Istream &is, bool keepHeader)
void writeEntry (Ostream &os) const
void writeEntry (const keyType &keyword, Ostream &os) const
void writeEntries (Ostream &os, const bool extraNewLine=false) const
void write (Ostream &os, const bool subDict=true) const
const_searcher csearch (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
const_searcher search (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
searcher search (const word &keyword, enum keyType::option matchOpt=keyType::REGEX)
const_searcher csearchScoped (const word &keyword, enum keyType::option matchOpt) const
const_searcher searchScoped (const word &keyword, enum keyType::option matchOpt) const
searcher searchScoped (const word &keyword, enum keyType::option matchOpt)
const dictionary * cfindScopedDict (const fileName &dictPath) const
const dictionary * findScopedDict (const fileName &dictPath) const
dictionary * findScopedDict (const fileName &dictPath)
dictionary * makeScopedDict (const fileName &dictPath)
const_searcher csearchCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, enum keyType::option matchOpt=keyType::REGEX) const
const entry * findCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, enum keyType::option matchOpt) const
bool foundCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, enum keyType::option matchOpt=keyType::REGEX) const
const entry & lookupEntryCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, enum keyType::option matchOpt) const
ITstream & lookupCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, enum keyType::option matchOpt=keyType::REGEX) const
template<class T >
T getCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, enum keyType::option matchOpt=keyType::REGEX) const
template<class T >
T getOrDefaultCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, const T &deflt, enum keyType::option matchOpt=keyType::REGEX) const
template<class T >
bool readCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, T &val, enum keyType::option matchOpt=keyType::REGEX, IOobjectOption::readOption readOpt=IOobjectOption::MUST_READ) const
template<class T >
bool readIfPresentCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, T &val, enum keyType::option matchOpt=keyType::REGEX) const
void operator= (const dictionary &rhs)
void operator+= (const dictionary &rhs)
void operator|= (const dictionary &rhs)
void operator<<= (const dictionary &rhs)
bool getBool (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Same as get< bool >(const word&, keyType::option)
label getLabel (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Same as get< label >(const word&, keyType::option)
scalar getScalar (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Same as get< scalar >(const word&, keyType::option)
string getString (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Same as get< string >(const word&, keyType::option)
word getWord (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Same as get< word >(const word&, keyType::option)
fileName getFileName (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Same as get< fileName >(const word&, keyType::option)
template<class T >
T lookupOrDefault (const word &keyword, const T &deflt, enum keyType::option matchOpt=keyType::REGEX) const
template<class T >
T lookupOrAddDefault (const word &keyword, const T &deflt, enum keyType::option matchOpt=keyType::REGEX)
ITstream & operator[] (const word &keyword) const
bool found (const word &keyword, bool recursive, bool patternMatch=true) const
entry * lookupEntryPtr (const word &keyword, bool recursive, bool patternMatch)
const entry * lookupEntryPtr (const word &keyword, bool recursive, bool patternMatch) const
const entry * lookupScopedEntryPtr (const word &keyword, bool recursive, bool patternMatch) const
const dictionary * subDictPtr (const word &keyword) const
dictionary * subDictPtr (const word &keyword)
const entry & lookupEntry (const word &keyword, bool recursive, bool patternMatch) const
ITstream & lookup (const word &keyword, bool recursive, bool patternMatch=true) const
template<class T >
T lookupOrDefault (const word &keyword, const T &deflt, bool recursive, bool patternMatch=true) const
template<class T >
T lookupOrAddDefault (const word &keyword, const T &deflt, bool recursive, bool patternMatch=true)
template<class T >
bool readIfPresent (const word &keyword, T &val, bool recursive, bool patternMatch=true) const
template<class T >
T lookupType (const word &keyword, bool recursive=false, bool patternMatch=true) const
template<class Compare >
Foam::wordList sortedToc (const Compare &comp) const
template<class T >
Foam::entry * add (const keyType &k, const T &v, bool overwrite)
template<class T >
Foam::entry * set (const keyType &k, const T &v)
Public Member Functions inherited from ILList< LListBase, T >
ILList ()=default
ILList (T *item)
ILList (Istream &is)
ILList (const ILList< LListBase, T > &lst)
ILList (ILList< LListBase, T > &&lst)
template<class CloneArg >
ILList (const ILList< LListBase, T > &lst, const CloneArg &cloneArg)
template<class INew >
ILList (Istream &is, const INew &inew)
~ILList ()
void clear ()
void pop_front (label n=1)
bool erase (T *item)
void transfer (ILList< LListBase, T > &lst)
void operator= (const ILList< LListBase, T > &lst)
void operator= (ILList< LListBase, T > &&lst)
Public Member Functions inherited from UILList< LListBase, T >
UILList ()=default
UILList (T *item)
UILList (const UILList< LListBase, T > &list)
T * front ()
const T * front () const
T * back ()
const T * back () const
T * removeHead ()
T * remove (T *item)
T * remove (iterator &iter)
void operator= (const UILList< LListBase, T > &lst)
bool operator== (const UILList< LListBase, T > &lst) const
bool operator!= (const UILList< LListBase, T > &lst) const
Ostream & writeList (Ostream &os, const label shortLen=0) const
iterator begin ()
const_iterator cbegin () const
reverse_iterator rbegin ()
const_reverse_iterator crbegin () const
const_iterator begin () const
const_reverse_iterator rbegin () const
const iterator & end ()
const const_iterator & cend () const
const reverse_iterator & rend ()
const const_reverse_iterator & crend () const
const const_iterator & end () const
const const_reverse_iterator & rend () const
T * first ()
const T * first () const
T * last ()
const T * last () const
Protected Types
enum limitType : unsigned { CLAMP_NONE = 0 , CLAMP_MIN = 0x1 , CLAMP_MAX = 0x2 , CLAMP_RANGE = (CLAMP_MIN | CLAMP_MAX) }
Protected Member Functions
virtual bool read ()
virtual void correctThermoFields ()
virtual void correctHsForMappedT ()
virtual void updateSurfaceTemperatures ()
virtual void resetPrimaryRegionSourceTerms ()
virtual void transferPrimaryRegionThermoFields ()
virtual void transferPrimaryRegionSourceFields ()
virtual void correctAlpha ()
virtual void updateSubmodels ()
virtual tmp< fvScalarMatrix > q (volScalarField &hs) const
virtual void solveEnergy ()
Protected Member Functions inherited from kinematicSingleLayer
virtual tmp< volScalarField > pu ()
virtual tmp< volScalarField > pp ()
virtual void continuityCheck ()
virtual void updateSurfaceVelocities ()
template<class Type >
void constrainFilmField (Type &field, const typename Type::cmptType &value)
virtual void solveContinuity ()
virtual tmp< fvVectorMatrix > solveMomentum (const volScalarField &pu, const volScalarField &pp)
virtual void solveThickness (const volScalarField &pu, const volScalarField &pp, fvVectorMatrix &UEqn)
Protected Member Functions inherited from regionModel
virtual bool read (const dictionary &dict)
virtual const AMIPatchToPatchInterpolation & interRegionAMI (const regionModel &nbrRegion, const label regionPatchi, const label nbrPatchi, const bool flip) const
Protected Member Functions inherited from regIOobject
bool readHeaderOk (const IOstreamOption::streamFormat fmt, const word &typeName)
Protected Member Functions inherited from IOobject
void setBad (const string &s)
Protected Attributes
const SLGThermo & thermo_
volScalarField Cp_
volScalarField kappa_
volScalarField T_
volScalarField Ts_
volScalarField Tw_
volScalarField hs_
volScalarField primaryEnergyTrans_
scalar deltaWet_
bool hydrophilic_
scalar hydrophilicDryScale_
scalar hydrophilicWetScale_
volScalarField hsSp_
volScalarField hsSpPrimary_
volScalarField TPrimary_
PtrList< volScalarField > YPrimary_
autoPtr< filmViscosityModel > viscosity_
autoPtr< heatTransferModel > htcs_
autoPtr< heatTransferModel > htcw_
autoPtr< phaseChangeModel > phaseChange_
autoPtr< filmRadiationModel > radiation_
limitType withTbounds_
scalarMinMax Tbounds_
Protected Attributes inherited from kinematicSingleLayer
Switch momentumPredictor_
label nOuterCorr_
label nCorr_
label nNonOrthCorr_
scalar cumulativeContErr_
const dimensionedScalar deltaSmall_
scalar deltaCoLimit_
volScalarField rho_
volScalarField mu_
volScalarField sigma_
volScalarField delta_
volScalarField alpha_
volVectorField U_
volVectorField Us_
volVectorField Uw_
volScalarField deltaRho_
surfaceScalarField phi_
volScalarField primaryMassTrans_
volScalarField cloudMassTrans_
volScalarField cloudDiameterTrans_
volVectorField USp_
volScalarField pSp_
volScalarField rhoSp_
volVectorField USpPrimary_
volScalarField pSpPrimary_
volScalarField rhoSpPrimary_
volVectorField UPrimary_
volScalarField pPrimary_
volScalarField rhoPrimary_
volScalarField muPrimary_
autoPtr< filmThermoModel > filmThermo_
scalarField availableMass_
injectionModelList injection_
transferModelList transfer_
autoPtr< filmTurbulenceModel > turbulence_
forceList forces_
scalar addedMassTotal_
Protected Attributes inherited from surfaceFilmRegionModel
const dimensionedVector & g_
Protected Attributes inherited from singleLayerRegion
autoPtr< volVectorField > nHatPtr_
autoPtr< volScalarField > magSfPtr_
labelList passivePatchIDs_
Protected Attributes inherited from regionModel
const fvMesh & primaryMesh_
const Time & time_
Switch active_
Switch infoOutput_
const word modelName_
dictionary coeffs_
autoPtr< IOdictionary > outputPropertiesPtr_
labelList primaryPatchIDs_
labelList intCoupledPatchIDs_
word regionName_
regionModelFunctionObjectList functions_
wordList interRegionAMINames_
PtrList< PtrList< AMIPatchToPatchInterpolation > > interRegionAMI_
Additional Inherited Members
Public Types inherited from IOobject
enum objectState : char { GOOD , BAD }
enum fileCheckTypes : char { timeStamp , timeStampMaster , inotify , inotifyMaster }
Public Types inherited from IOobjectOption
enum readOption : unsigned char {
NO_READ = 0 , MUST_READ = 0x1 , READ_MODIFIED = 0x3 , MUST_READ_IF_MODIFIED = 0x3 ,
LAZY_READ = 0x4 , READ_IF_PRESENT = 0x4
}
enum writeOption : unsigned char { NO_WRITE = 0 , AUTO_WRITE = 0x10 }
enum registerOption : unsigned char { NO_REGISTER = 0 , REGISTER = 1 }
Public Types inherited from dictionary
typedef Searcher< true > const_searcher
typedef Searcher< false > searcher
Public Types inherited from UILList< LListBase, T >
typedef T value_type
typedef T * pointer
typedef const T * const_pointer
typedef T & reference
typedef const T & const_reference
typedef label size_type
typedef label difference_type
using base_iterator = typename LListBase::iterator
using const_base_iterator = typename LListBase::const_iterator
Static Public Member Functions inherited from surfaceFilmModel
static autoPtr< surfaceFilmModel > New (const fvMesh &mesh, const dimensionedVector &g, const word &regionType="surfaceFilm")
Static Public Member Functions inherited from IOdictionary
static dictionary readContents (const IOobject &io)
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *p)
template<class Type >
static Type & store (autoPtr< Type > &ptr)
template<class Type >
static Type & store (autoPtr< Type > &&ptr)
template<class Type >
static Type & store (refPtr< Type > &ptr)
template<class Type >
static Type & store (refPtr< Type > &&ptr)
template<class Type >
static Type & store (tmp< Type > &ptr)
template<class Type >
static Type & store (tmp< Type > &&ptr)
Static Public Member Functions inherited from IOobject
static bool bannerEnabled () noexcept
static bool bannerEnabled (bool on) noexcept
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
template<class StringType >
static word groupName (StringType base, const word &group)
static word group (const word &name)
static word member (const word &name)
static word scopedName (const std::string &scope, const word &name)
static IOobject selectIO (const IOobject &io, const fileName &altFile, const word &ioName="")
static Ostream & writeBanner (Ostream &os, const bool noSyntaxHint=false)
static Ostream & writeDivider (Ostream &os)
static Ostream & writeEndDivider (Ostream &os)
Static Public Member Functions inherited from IOobjectOption
static bool isAnyRead (readOption opt) noexcept
static bool isReadRequired (readOption opt) noexcept
static bool isReadOptional (readOption opt) noexcept
static readOption lazierRead (readOption opt) noexcept
Static Public Member Functions inherited from dictionary
static int reportOptional () noexcept
static int reportOptional (const int level) noexcept
static autoPtr< dictionary > New (Istream &is)
Public Attributes inherited from dictionary
friend const_searcher
friend searcher
Static Public Attributes inherited from surfaceFilmModel
static const dimensionedScalar Tref
Static Public Attributes inherited from IOobject
static const Enum< fileCheckTypes > fileCheckTypesNames
static char scopeSeparator
static fileCheckTypes fileModificationChecking
static float fileModificationSkew
static int maxFileModificationPolls
Static Public Attributes inherited from dictionary
static int writeOptionalEntries
static const dictionary null
static refPtr< OSstream > reportingOutput
Static Protected Member Functions inherited from IOobject
static void writeHeaderContent (Ostream &os, const IOobject &io, const word &objectType, const dictionary *metaDataDict=nullptr)
static void writeHeaderContent (dictionary &dict, const IOobject &io, const word &objectType, IOstreamOption streamOpt, const dictionary *metaDataDict=nullptr)
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
Detailed Description
Thermodynamic form of single-cell layer surface film model.
Note: defining enthalpy as Cp(T - Tstd) - when using liquids from the thermophysical library, their enthalpies are calculated similarly, where Tstd = 298.15K. This is clearly non-conservative unless the heat-capacity is constant and should be rewritten to use the standard thermodynamics packages.
Source files
thermoSingleLayer.H
thermoSingleLayer.C
Definition at line 64 of file thermoSingleLayer.H.
Member Enumeration Documentation
limitType
enum limitType : unsigned protected
Enumerator
CLAMP_NONE
No limit.
CLAMP_MIN
Clamp minimum value.
CLAMP_MAX
Clamp maximum value.
CLAMP_RANGE
Clamp min/max.
Definition at line 85 of file thermoSingleLayer.H.
Constructor & Destructor Documentation
thermoSingleLayer()
thermoSingleLayer (const word & modelType, const fvMesh & mesh, const dimensionedVector & g, const word & regionType, const bool readFields = true)
Definition at line 304 of file thermoSingleLayer.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), thermoSingleLayer::CLAMP_MAX, thermoSingleLayer::CLAMP_MIN, thermoSingleLayer::CLAMP_NONE, regionModel::coeffs(), regionModel::coeffs_, thermoSingleLayer::correctAlpha(), thermoSingleLayer::correctThermoFields(), kinematicSingleLayer::delta_, kinematicSingleLayer::deltaRho_, Foam::dimless, Foam::fvc::flux(), forAll, thermoSingleLayer::hs(), thermoSingleLayer::hs_, thermoSingleLayer::hydrophilic_, thermoSingleLayer::hydrophilicDryScale_, thermoSingleLayer::hydrophilicWetScale_, Foam::Info, MinMax< T >::max(), MinMax< T >::min(), Foam::nl, IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, kinematicSingleLayer::phi_, kinematicSingleLayer::pPrimary_, kinematicSingleLayer::pSp_, IOobjectOption::READ_IF_PRESENT, dictionary::readEntry(), Foam::readFields(), dictionary::readIfPresent(), regionModel::regionMesh(), kinematicSingleLayer::rho_, PtrList< T >::set(), PtrList< T >::setSize(), UPtrList< T >::size(), thermoSingleLayer::T_, thermoSingleLayer::Tbounds_, thermoSingleLayer::thermo_, regionModel::time(), timeName, thermoSingleLayer::transferPrimaryRegionThermoFields(), kinematicSingleLayer::U_, thermoSingleLayer::viscosity_, thermoSingleLayer::withTbounds_, thermoSingleLayer::YPrimary_, and Foam::Zero.
~thermoSingleLayer()
~thermoSingleLayer () virtual
Definition at line 562 of file thermoSingleLayer.C.
Member Function Documentation
read()
bool read () protected virtual
Reimplemented from kinematicSingleLayer.
Definition at line 81 of file thermoSingleLayer.C.
References kinematicSingleLayer::read().
correctThermoFields()
void correctThermoFields () protected virtual
Reimplemented from kinematicSingleLayer.
Definition at line 98 of file thermoSingleLayer.C.
References thermoSingleLayer::Cp_, kinematicSingleLayer::filmThermo_, thermoSingleLayer::kappa_, kinematicSingleLayer::rho_, and kinematicSingleLayer::sigma_.
Referenced by thermoSingleLayer::solveEnergy(), and thermoSingleLayer::thermoSingleLayer().
correctHsForMappedT()
void correctHsForMappedT () protected virtual
Definition at line 107 of file thermoSingleLayer.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), forAll, thermoSingleLayer::hs(), thermoSingleLayer::hs_, Foam::isA(), and thermoSingleLayer::T_.
Referenced by thermoSingleLayer::updateSurfaceTemperatures().
updateSurfaceTemperatures()
void updateSurfaceTemperatures () protected virtual
Definition at line 124 of file thermoSingleLayer.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), thermoSingleLayer::correctHsForMappedT(), regionModel::intCoupledPatchIDs_, kinematicSingleLayer::pp(), regionModel::regionMesh(), UList< T >::size(), thermoSingleLayer::T_, thermoSingleLayer::Ts_, and thermoSingleLayer::Tw_.
Referenced by thermoSingleLayer::solveEnergy().
resetPrimaryRegionSourceTerms()
void resetPrimaryRegionSourceTerms () protected virtual
Reimplemented from kinematicSingleLayer.
Definition at line 88 of file thermoSingleLayer.C.
References DebugInFunction, DimensionedField< Type, GeoMesh >::dimensions(), Foam::endl(), thermoSingleLayer::hsSp_, thermoSingleLayer::hsSpPrimary_, kinematicSingleLayer::resetPrimaryRegionSourceTerms(), and Foam::Zero.
transferPrimaryRegionThermoFields()
void transferPrimaryRegionThermoFields () protected virtual
Reimplemented from kinematicSingleLayer.
Definition at line 144 of file thermoSingleLayer.C.
References GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), DebugInFunction, Foam::endl(), forAll, thermoSingleLayer::TPrimary_, kinematicSingleLayer::transferPrimaryRegionThermoFields(), and thermoSingleLayer::YPrimary_.
Referenced by thermoSingleLayer::thermoSingleLayer().
transferPrimaryRegionSourceFields()
void transferPrimaryRegionSourceFields () protected virtual
Reimplemented from kinematicSingleLayer.
Definition at line 160 of file thermoSingleLayer.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), DebugInFunction, Foam::endl(), forAll, thermoSingleLayer::hsSp_, thermoSingleLayer::hsSpPrimary_, singleLayerRegion::magSf(), regionModel::primaryMesh(), regionModel::time_, and kinematicSingleLayer::transferPrimaryRegionSourceFields().
correctAlpha()
void correctAlpha () protected virtual
Reimplemented from kinematicSingleLayer.
Definition at line 189 of file thermoSingleLayer.C.
References kinematicSingleLayer::alpha_, GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), kinematicSingleLayer::delta_, thermoSingleLayer::deltaWet_, Foam::dimLength, forAll, thermoSingleLayer::hydrophilic_, thermoSingleLayer::hydrophilicDryScale_, thermoSingleLayer::hydrophilicWetScale_, and Foam::pos0().
Referenced by thermoSingleLayer::thermoSingleLayer().
updateSubmodels()
void updateSubmodels () protected virtual
Reimplemented from kinematicSingleLayer.
Definition at line 218 of file thermoSingleLayer.C.
References kinematicSingleLayer::availableMass_, kinematicSingleLayer::cloudDiameterTrans_, kinematicSingleLayer::cloudMassTrans_, injectionModelList::correct(), transferModelList::correct(), DebugInFunction, Foam::endl(), thermoSingleLayer::hs_, thermoSingleLayer::hsSp_, thermoSingleLayer::htcs_, thermoSingleLayer::htcw_, kinematicSingleLayer::injection_, singleLayerRegion::magSf(), thermoSingleLayer::phaseChange_, thermoSingleLayer::primaryEnergyTrans_, kinematicSingleLayer::primaryMassTrans_, kinematicSingleLayer::pSp_, thermoSingleLayer::radiation_, kinematicSingleLayer::rhoPrimary_, kinematicSingleLayer::rhoSp_, Foam::sqr(), regionModel::time(), regionModel::time_, kinematicSingleLayer::transfer_, and kinematicSingleLayer::turbulence_.
Referenced by thermoSingleLayer::evolveRegion().
q()
tmp< fvScalarMatrix > q (volScalarField & hs) const protected virtual
Definition at line 256 of file thermoSingleLayer.C.
References kinematicSingleLayer::alpha_, thermoSingleLayer::Cp_, thermoSingleLayer::hs(), thermoSingleLayer::htcs_, thermoSingleLayer::htcw_, Foam::fvm::Sp(), thermoSingleLayer::T_, thermoSingleLayer::TPrimary_, and thermoSingleLayer::Tw_.
Referenced by thermoSingleLayer::solveEnergy().
solveEnergy()
void solveEnergy () protected virtual
Definition at line 271 of file thermoSingleLayer.C.
References thermoSingleLayer::correctThermoFields(), Foam::fvm::ddt(), DebugInFunction, kinematicSingleLayer::deltaRho_, DimensionedField< Type, GeoMesh >::dimensions(), Foam::fvm::div(), e, Foam::endl(), thermoSingleLayer::hs_, thermoSingleLayer::hsSp_, kinematicSingleLayer::phi_, kinematicSingleLayer::pPrimary_, thermoSingleLayer::q(), thermoSingleLayer::radiation_, solve(), thermoSingleLayer::T_, thermoSingleLayer::updateSurfaceTemperatures(), and thermoSingleLayer::viscosity_.
Referenced by thermoSingleLayer::evolveRegion().
TypeName()
TypeName ("thermoSingleLayer")
thermo()
const SLGThermo & thermo () const inline
Definition at line 38 of file thermoSingleLayerI.H.
References thermoSingleLayer::thermo_.
Cp()
const volScalarField & Cp () const virtual
Reimplemented from kinematicSingleLayer.
Definition at line 648 of file thermoSingleLayer.C.
References thermoSingleLayer::Cp_.
Referenced by thermoSingleLayer::hs().
kappa()
const volScalarField & kappa () const virtual
Reimplemented from kinematicSingleLayer.
Definition at line 654 of file thermoSingleLayer.C.
References thermoSingleLayer::kappa_.
T() [1/2]
const volScalarField & T () const virtual
Reimplemented from kinematicSingleLayer.
Definition at line 660 of file thermoSingleLayer.C.
References thermoSingleLayer::T_.
Referenced by thermoSingleLayer::evolveRegion(), thermoSingleLayer::hs(), and thermoSingleLayer::hs().
Ts()
const volScalarField & Ts () const virtual
Reimplemented from kinematicSingleLayer.
Definition at line 666 of file thermoSingleLayer.C.
References thermoSingleLayer::Ts_.
Referenced by filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::updateCoeffs().
Tw()
const volScalarField & Tw () const virtual
Reimplemented from kinematicSingleLayer.
Definition at line 672 of file thermoSingleLayer.C.
References thermoSingleLayer::Tw_.
hs() [1/3]
const volScalarField & hs () const virtual
Reimplemented from kinematicSingleLayer.
Definition at line 678 of file thermoSingleLayer.C.
References thermoSingleLayer::hs_.
Referenced by thermoSingleLayer::correctHsForMappedT(), thermoSingleLayer::q(), thermoSingleLayer::T(), and thermoSingleLayer::thermoSingleLayer().
hs() [2/3]
tmp< scalarField > hs (const scalarField & T, const label patchi) const inline
Definition at line 44 of file thermoSingleLayerI.H.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), thermoSingleLayer::Cp(), thermoSingleLayer::Cp_, thermoSingleLayer::T(), and surfaceFilmModel::Tref.
hs() [3/3]
tmp< volScalarField > hs (const volScalarField & T) const inline
Definition at line 55 of file thermoSingleLayerI.H.
References thermoSingleLayer::Cp_, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, regionModel::regionMesh(), thermoSingleLayer::T(), regionModel::time(), timeName, and surfaceFilmModel::Tref.
T() [2/2]
tmp< volScalarField > T (const volScalarField & hs) const inline
Definition at line 78 of file thermoSingleLayerI.H.
References thermoSingleLayer::CLAMP_MAX, thermoSingleLayer::CLAMP_MIN, thermoSingleLayer::CLAMP_RANGE, thermoSingleLayer::Cp_, thermoSingleLayer::hs(), MinMax< T >::max(), MinMax< T >::min(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, regionModel::regionMesh(), thermoSingleLayer::Tbounds_, regionModel::time(), timeName, surfaceFilmModel::Tref, and thermoSingleLayer::withTbounds_.
addSources()
void addSources (const label patchi, const label facei, const scalar massSource, const vector & momentumSource, const scalar pressureSource, const scalar energySource) virtual
Reimplemented from kinematicSingleLayer.
Definition at line 568 of file thermoSingleLayer.C.
References kinematicSingleLayer::addSources(), GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), DebugInfo, thermoSingleLayer::hsSpPrimary_, and Foam::nl.
hsSp()
const volScalarField & hsSp () const inline
Definition at line 116 of file thermoSingleLayerI.H.
References thermoSingleLayer::hsSp_.
hsSpPrimary()
const volScalarField & hsSpPrimary () const inline
Definition at line 122 of file thermoSingleLayerI.H.
References thermoSingleLayer::hsSpPrimary_.
TPrimary()
const volScalarField & TPrimary () const inline
Definition at line 128 of file thermoSingleLayerI.H.
References thermoSingleLayer::TPrimary_.
YPrimary()
const PtrList< volScalarField > & YPrimary () const inline
Definition at line 134 of file thermoSingleLayerI.H.
References thermoSingleLayer::YPrimary_.
htcs()
const heatTransferModel & htcs () const inline
Definition at line 140 of file thermoSingleLayerI.H.
References thermoSingleLayer::htcs_.
htcw()
const heatTransferModel & htcw () const inline
Definition at line 146 of file thermoSingleLayerI.H.
References thermoSingleLayer::htcw_.
Referenced by filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::updateCoeffs().
phaseChange()
const phaseChangeModel & phaseChange () const inline
Definition at line 152 of file thermoSingleLayerI.H.
References thermoSingleLayer::phaseChange_.
radiation()
const filmRadiationModel & radiation () const inline
Definition at line 158 of file thermoSingleLayerI.H.
References thermoSingleLayer::radiation_.
qconvw()
tmp< scalarField > qconvw (const label patchi) const inline
Definition at line 164 of file thermoSingleLayerI.H.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), thermoSingleLayer::htcw_, thermoSingleLayer::T_, and thermoSingleLayer::Tw_.
qconvp()
tmp< scalarField > qconvp (const label patchi) const inline
Definition at line 174 of file thermoSingleLayerI.H.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), thermoSingleLayer::htcs_, thermoSingleLayer::T_, and thermoSingleLayer::TPrimary_.
preEvolveRegion()
void preEvolveRegion () virtual
Reimplemented from kinematicSingleLayer.
Definition at line 595 of file thermoSingleLayer.C.
References DebugInFunction, Foam::dimEnergy, Foam::endl(), kinematicSingleLayer::preEvolveRegion(), thermoSingleLayer::primaryEnergyTrans_, and Foam::Zero.
evolveRegion()
void evolveRegion () virtual
Reimplemented from kinematicSingleLayer.
Definition at line 604 of file thermoSingleLayer.C.
References DebugInFunction, kinematicSingleLayer::delta_, kinematicSingleLayer::deltaRho_, Foam::endl(), thermoSingleLayer::hs_, kinematicSingleLayer::nCorr_, kinematicSingleLayer::nOuterCorr_, kinematicSingleLayer::pp(), kinematicSingleLayer::pu(), kinematicSingleLayer::rho_, kinematicSingleLayer::solveContinuity(), thermoSingleLayer::solveEnergy(), kinematicSingleLayer::solveMomentum(), kinematicSingleLayer::solveThickness(), thermoSingleLayer::T(), thermoSingleLayer::T_, tUEqn(), UEqn, and thermoSingleLayer::updateSubmodels().
Srho() [1/2]
tmp< volScalarField::Internal > Srho () const virtual
Reimplemented from kinematicSingleLayer.
Definition at line 699 of file thermoSingleLayer.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), cells, Foam::dimMass, Foam::dimTime, Foam::dimVolume, forAll, regionModel::intCoupledPatchIDs(), IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, kinematicSingleLayer::primaryMassTrans_, regionModel::primaryMesh(), regionModel::primaryPatchIDs(), thermoSingleLayer::Srho(), regionModel::time(), regionModel::time_, timeName, regionModel::toPrimary(), and Foam::Zero.
Referenced by thermoSingleLayer::Srho(), and thermoSingleLayer::Srho().
Srho() [2/2]
tmp< volScalarField::Internal > Srho (const label i) const virtual
Reimplemented from kinematicSingleLayer.
Definition at line 746 of file thermoSingleLayer.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), cells, Foam::dimMass, Foam::dimTime, Foam::dimVolume, kinematicSingleLayer::filmThermo_, forAll, regionModel::intCoupledPatchIDs_, Foam::name(), IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, kinematicSingleLayer::primaryMassTrans_, regionModel::primaryMesh(), regionModel::primaryPatchIDs(), thermoSingleLayer::Srho(), thermoSingleLayer::thermo_, regionModel::time(), regionModel::time_, regionModel::toPrimary(), and Foam::Zero.
Sh()
tmp< volScalarField::Internal > Sh () const virtual
Reimplemented from kinematicSingleLayer.
Definition at line 801 of file thermoSingleLayer.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), cells, Foam::dimEnergy, Foam::dimTime, Foam::dimVolume, forAll, regionModel::intCoupledPatchIDs_, IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, thermoSingleLayer::primaryEnergyTrans_, regionModel::primaryMesh(), regionModel::primaryPatchIDs(), thermoSingleLayer::Sh(), regionModel::time(), regionModel::time_, timeName, regionModel::toPrimary(), and Foam::Zero.
Referenced by thermoSingleLayer::Sh().
info()
void info () virtual
Reimplemented from kinematicSingleLayer.
Definition at line 684 of file thermoSingleLayer.C.
References Foam::gAverage(), Foam::gMax(), Foam::gMin(), Foam::indent(), Foam::Info, kinematicSingleLayer::info(), Foam::nl, thermoSingleLayer::phaseChange_, and thermoSingleLayer::T_.
Member Data Documentation
thermo_
const SLGThermo& thermo_ protected
Definition at line 97 of file thermoSingleLayer.H.
Referenced by thermoSingleLayer::Srho(), thermoSingleLayer::thermo(), and thermoSingleLayer::thermoSingleLayer().
Cp_
volScalarField Cp_ protected
Definition at line 103 of file thermoSingleLayer.H.
Referenced by thermoSingleLayer::correctThermoFields(), thermoSingleLayer::Cp(), thermoSingleLayer::hs(), thermoSingleLayer::hs(), thermoSingleLayer::q(), and thermoSingleLayer::T().
kappa_
volScalarField kappa_ protected
Definition at line 106 of file thermoSingleLayer.H.
Referenced by thermoSingleLayer::correctThermoFields(), and thermoSingleLayer::kappa().
T_
volScalarField T_ protected
Definition at line 109 of file thermoSingleLayer.H.
Referenced by thermoSingleLayer::correctHsForMappedT(), thermoSingleLayer::evolveRegion(), thermoSingleLayer::info(), thermoSingleLayer::q(), thermoSingleLayer::qconvp(), thermoSingleLayer::qconvw(), thermoSingleLayer::solveEnergy(), thermoSingleLayer::T(), thermoSingleLayer::thermoSingleLayer(), and thermoSingleLayer::updateSurfaceTemperatures().
Ts_
volScalarField Ts_ protected
Definition at line 112 of file thermoSingleLayer.H.
Referenced by thermoSingleLayer::Ts(), and thermoSingleLayer::updateSurfaceTemperatures().
Tw_
volScalarField Tw_ protected
Definition at line 115 of file thermoSingleLayer.H.
Referenced by thermoSingleLayer::q(), thermoSingleLayer::qconvw(), thermoSingleLayer::Tw(), and thermoSingleLayer::updateSurfaceTemperatures().
hs_
volScalarField hs_ protected
Definition at line 118 of file thermoSingleLayer.H.
Referenced by thermoSingleLayer::correctHsForMappedT(), thermoSingleLayer::evolveRegion(), thermoSingleLayer::hs(), thermoSingleLayer::solveEnergy(), thermoSingleLayer::thermoSingleLayer(), and thermoSingleLayer::updateSubmodels().
primaryEnergyTrans_
volScalarField primaryEnergyTrans_ protected
Definition at line 124 of file thermoSingleLayer.H.
Referenced by thermoSingleLayer::preEvolveRegion(), thermoSingleLayer::Sh(), and thermoSingleLayer::updateSubmodels().
deltaWet_
scalar deltaWet_ protected
Definition at line 128 of file thermoSingleLayer.H.
Referenced by thermoSingleLayer::correctAlpha().
hydrophilic_
bool hydrophilic_ protected
Definition at line 134 of file thermoSingleLayer.H.
Referenced by thermoSingleLayer::correctAlpha(), and thermoSingleLayer::thermoSingleLayer().
hydrophilicDryScale_
scalar hydrophilicDryScale_ protected
Definition at line 138 of file thermoSingleLayer.H.
Referenced by thermoSingleLayer::correctAlpha(), and thermoSingleLayer::thermoSingleLayer().
hydrophilicWetScale_
scalar hydrophilicWetScale_ protected
Definition at line 142 of file thermoSingleLayer.H.
Referenced by thermoSingleLayer::correctAlpha(), and thermoSingleLayer::thermoSingleLayer().
hsSp_
volScalarField hsSp_ protected
Definition at line 152 of file thermoSingleLayer.H.
Referenced by thermoSingleLayer::hsSp(), thermoSingleLayer::resetPrimaryRegionSourceTerms(), thermoSingleLayer::solveEnergy(), thermoSingleLayer::transferPrimaryRegionSourceFields(), and thermoSingleLayer::updateSubmodels().
hsSpPrimary_
volScalarField hsSpPrimary_ protected
Definition at line 159 of file thermoSingleLayer.H.
Referenced by thermoSingleLayer::addSources(), thermoSingleLayer::hsSpPrimary(), thermoSingleLayer::resetPrimaryRegionSourceTerms(), and thermoSingleLayer::transferPrimaryRegionSourceFields().
TPrimary_
volScalarField TPrimary_ protected
Definition at line 166 of file thermoSingleLayer.H.
Referenced by thermoSingleLayer::q(), thermoSingleLayer::qconvp(), thermoSingleLayer::TPrimary(), and thermoSingleLayer::transferPrimaryRegionThermoFields().
YPrimary_
PtrList<volScalarField> YPrimary_ protected
Definition at line 169 of file thermoSingleLayer.H.
Referenced by thermoSingleLayer::thermoSingleLayer(), thermoSingleLayer::transferPrimaryRegionThermoFields(), and thermoSingleLayer::YPrimary().
viscosity_
autoPtr<filmViscosityModel> viscosity_ protected
Definition at line 175 of file thermoSingleLayer.H.
Referenced by thermoSingleLayer::solveEnergy(), and thermoSingleLayer::thermoSingleLayer().
htcs_
autoPtr<heatTransferModel> htcs_ protected
Definition at line 179 of file thermoSingleLayer.H.
Referenced by thermoSingleLayer::htcs(), thermoSingleLayer::q(), thermoSingleLayer::qconvp(), and thermoSingleLayer::updateSubmodels().
htcw_
autoPtr<heatTransferModel> htcw_ protected
Definition at line 182 of file thermoSingleLayer.H.
Referenced by thermoSingleLayer::htcw(), thermoSingleLayer::q(), thermoSingleLayer::qconvw(), and thermoSingleLayer::updateSubmodels().
phaseChange_
autoPtr<phaseChangeModel> phaseChange_ protected
Definition at line 185 of file thermoSingleLayer.H.
Referenced by thermoSingleLayer::info(), thermoSingleLayer::phaseChange(), and thermoSingleLayer::updateSubmodels().
radiation_
autoPtr<filmRadiationModel> radiation_ protected
Definition at line 188 of file thermoSingleLayer.H.
Referenced by thermoSingleLayer::radiation(), thermoSingleLayer::solveEnergy(), and thermoSingleLayer::updateSubmodels().
withTbounds_
limitType withTbounds_ protected
Definition at line 194 of file thermoSingleLayer.H.
Referenced by thermoSingleLayer::T(), and thermoSingleLayer::thermoSingleLayer().
Tbounds_
scalarMinMax Tbounds_ protected
Definition at line 197 of file thermoSingleLayer.H.
Referenced by thermoSingleLayer::T(), and thermoSingleLayer::thermoSingleLayer().
The documentation for this class was generated from the following files:
src/regionModels/surfaceFilmModels/thermoSingleLayer/thermoSingleLayer.H
src/regionModels/surfaceFilmModels/thermoSingleLayer/thermoSingleLayer.C
src/regionModels/surfaceFilmModels/thermoSingleLayer/thermoSingleLayerI.H