OpenFOAM: hexRef8Data Class Reference
hexRef8Data Class Reference
Various for reading/decomposing/reconstructing/distributing refinement data.
#include <hexRef8Data.H>
Public Member Functions
hexRef8Data (const hexRef8Data &)=delete
void operator= (const hexRef8Data &)=delete
hexRef8Data (const IOobject &io)
hexRef8Data (const IOobject &io, const hexRef8Data &, const labelList &cellMap, const labelList &pointMap)
hexRef8Data (const IOobject &io, const UPtrList< const labelList > &cellMaps, const UPtrList< const labelList > &pointMaps, const UPtrList< const hexRef8Data > &)
~hexRef8Data ()
void sync (const IOobject &io)
void updateMesh (const mapPolyMesh &)
void distribute (const mapDistributePolyMesh &)
bool write () const
Detailed Description
Various for reading/decomposing/reconstructing/distributing refinement data.
Source files
hexRef8Data.H
hexRef8Data.C
Definition at line 56 of file hexRef8Data.H.
Constructor & Destructor Documentation
hexRef8Data() [1/4]
hexRef8Data (const hexRef8Data &) delete
hexRef8Data() [2/4]
hexRef8Data (const IOobject & io) explicit
Definition at line 34 of file hexRef8Data.C.
References Foam::endl(), Foam::Info, io(), IOobjectOption::LAZY_READ, IOobjectOption::MUST_READ, and Foam::returnReduceOr().
hexRef8Data() [3/4]
hexRef8Data (const IOobject & io, const hexRef8Data & data, const labelList & cellMap, const labelList & pointMap)
Definition at line 93 of file hexRef8Data.C.
References dictionary::clone(), io(), and baseIOdictionary::name().
hexRef8Data() [4/4]
hexRef8Data (const IOobject & io, const UPtrList< const labelList > & cellMaps, const UPtrList< const labelList > & pointMaps, const UPtrList< const hexRef8Data > & procDatas)
Definition at line 145 of file hexRef8Data.C.
References IOobject::db(), forAll, io(), mesh, Foam::name(), primitiveMesh::nCells(), primitiveMesh::nPoints(), PtrList< T >::set(), and UPtrList< T >::size().
~hexRef8Data()
~hexRef8Data ()
Definition at line 233 of file hexRef8Data.C.
Member Function Documentation
operator=()
void operator= (const hexRef8Data &) delete
sync()
void sync (const IOobject & io)
Definition at line 239 of file hexRef8Data.C.
References Pstream::broadcast(), IOobject::db(), Foam::dimLength, io(), UPstream::master(), mesh, primitiveMesh::nCells(), IOobjectOption::NO_READ, primitiveMesh::nPoints(), Foam::returnReduceOr(), and Foam::Zero.
updateMesh()
void updateMesh (const mapPolyMesh & map)
Definition at line 308 of file hexRef8Data.C.
References mapPolyMesh::cellMap(), PtrList< T >::clear(), forAll, mapPolyMesh::mesh(), newPointi, mapPolyMesh::nOldCells(), mapPolyMesh::nOldPoints(), mapPolyMesh::pointMap(), UList< T >::size(), and List< T >::transfer().
distribute()
void distribute (const mapDistributePolyMesh & map)
Definition at line 379 of file hexRef8Data.C.
References mapDistributePolyMesh::cellMap(), and mapDistributePolyMesh::pointMap().
write()
bool write () const
Definition at line 399 of file hexRef8Data.C.
The documentation for this class was generated from the following files:
src/dynamicMesh/polyTopoChange/polyTopoChange/hexRef8/hexRef8Data.H
src/dynamicMesh/polyTopoChange/polyTopoChange/hexRef8/hexRef8Data.C