OpenFOAM: localEulerDdt Class Reference
localEulerDdt Class Reference
#include <localEulerDdtScheme.H>
Public Member Functions
localEulerDdt ()
Static Public Member Functions
static bool enabled (const fvMesh &mesh)
static const volScalarField & localRDeltaT (const fvMesh &mesh)
static const surfaceScalarField & localRDeltaTf (const fvMesh &mesh)
static tmp< volScalarField > localRSubDeltaT (const fvMesh &mesh, const label nAlphaSubCycles)
Static Public Attributes
static word rDeltaTName
static word rDeltaTfName
static word rSubDeltaTName
Detailed Description
Definition at line 65 of file localEulerDdtScheme.H.
Constructor & Destructor Documentation
localEulerDdt()
localEulerDdt () inline
Definition at line 81 of file localEulerDdtScheme.H.
Member Function Documentation
enabled()
bool enabled (const fvMesh & mesh) static
Definition at line 32 of file localEulerDdt.C.
References mesh.
Referenced by Foam::byDt(), Foam::byDt(), laminar< ReactionThermo >::correct(), cloudSolution::read(), and twoPhaseSystem::solve().
localRDeltaT()
const Foam::volScalarField & localRDeltaT (const fvMesh & mesh) static
Definition at line 40 of file localEulerDdt.C.
References mesh.
Referenced by laminar< ReactionThermo >::correct(), multiphaseSystem::sigma(), and advectiveFvPatchField< Type >::updateCoeffs().
localRDeltaTf()
const Foam::surfaceScalarField & localRDeltaTf (const fvMesh & mesh) static
Definition at line 52 of file localEulerDdt.C.
References mesh.
Referenced by Foam::byDt().
localRSubDeltaT()
Foam::tmp< Foam::volScalarField > localRSubDeltaT (const fvMesh & mesh, const label nAlphaSubCycles) static
Definition at line 64 of file localEulerDdt.C.
References mesh, and nAlphaSubCycles().
Referenced by twoPhaseSystem::solve().
Member Data Documentation
rDeltaTName
Foam::word rDeltaTName static
Definition at line 70 of file localEulerDdtScheme.H.
rDeltaTfName
Foam::word rDeltaTfName static
Definition at line 73 of file localEulerDdtScheme.H.
rSubDeltaTName
Foam::word rSubDeltaTName static
Definition at line 76 of file localEulerDdtScheme.H.
The documentation for this class was generated from the following files:
src/finiteVolume/finiteVolume/ddtSchemes/localEulerDdtScheme/localEulerDdtScheme.H
src/finiteVolume/finiteVolume/ddtSchemes/localEulerDdtScheme/localEulerDdt.C