OpenFOAM: pointMesh Class Reference
pointMesh Class Reference
Mesh representing a set of points created from polyMesh.
#include <pointMesh.H>
Public Types
typedef pointMesh Mesh
typedef pointBoundaryMesh BoundaryMesh
Public Types inherited from GeoMesh< polyMesh >
typedef polyMesh Mesh
typedef MESH::BoundaryMesh BoundaryMesh
Public Member Functions
ClassName ("pointMesh")
pointMesh (const polyMesh &pMesh)
~pointMesh ()=default
label size () const
const pointBoundaryMesh & boundary () const noexcept
const globalMeshData & globalData () const
const objectRegistry & thisDb () const
const Time & time () const
const polyBoundaryMesh & boundaryMesh () const
bool movePoints ()
void updateMesh (const mapPolyMesh &mpm)
bool operator!= (const pointMesh &pm) const
bool operator== (const pointMesh &pm) const
Public Member Functions inherited from MeshObject< polyMesh, UpdateableMeshObject, pointMesh >
MeshObject (const polyMesh &mesh)
MeshObject (const word &objName, const polyMesh &mesh)
virtual ~MeshObject ()=default
const polyMesh & mesh () const noexcept
virtual bool writeData (Ostream &os) const
Public Member Functions inherited from GeoMesh< polyMesh >
GeoMesh (const polyMesh &mesh)
bool hasDb () const
const objectRegistry & thisDb () const
const polyMesh & operator() () const
Static Public Member Functions
static label size (const Mesh &mesh)
Static Public Member Functions inherited from MeshObject< polyMesh, UpdateableMeshObject, pointMesh >
static const pointMesh & New (const polyMesh &mesh, Args &&... args)
static const pointMesh & New (const word &objName, const polyMesh &mesh, Args &&... args)
static bool Delete (const word &objName, const polyMesh &mesh)
static bool Delete (const polyMesh &mesh)
Additional Inherited Members
Protected Attributes inherited from MeshObject< polyMesh, UpdateableMeshObject, pointMesh >
const polyMesh & mesh_
Protected Attributes inherited from GeoMesh< polyMesh >
const polyMesh & mesh_
Detailed Description
Mesh representing a set of points created from polyMesh.
Definition at line 45 of file pointMesh.H.
Member Typedef Documentation
Mesh
typedef pointMesh Mesh
Definition at line 73 of file pointMesh.H.
BoundaryMesh
typedef pointBoundaryMesh BoundaryMesh
Definition at line 76 of file pointMesh.H.
Constructor & Destructor Documentation
pointMesh()
pointMesh (const polyMesh & pMesh) explicit
Definition at line 66 of file pointMesh.C.
References Foam::endl(), IOobject::name(), and Foam::Pout.
~pointMesh()
~pointMesh () default
Member Function Documentation
ClassName()
ClassName ("pointMesh")
size() [1/2]
static label size (const Mesh & mesh) inline static
Definition at line 96 of file pointMesh.H.
References MeshObject< polyMesh, UpdateableMeshObject, pointMesh >::mesh(), and GeoMesh< polyMesh >::mesh_.
size() [2/2]
label size () const inline
Definition at line 102 of file pointMesh.H.
References pointMesh::size().
Referenced by pointMesh::size().
boundary()
const pointBoundaryMesh & boundary () const inline noexcept
Definition at line 108 of file pointMesh.H.
Referenced by meshRefinement::makeDisplacementField().
globalData()
const globalMeshData & globalData () const inline
Definition at line 114 of file pointMesh.H.
thisDb()
const objectRegistry & thisDb () const inline
Definition at line 120 of file pointMesh.H.
References GeoMesh< MESH >::thisDb().
Referenced by uniformInterpolatedDisplacementPointPatchVectorField::updateCoeffs().
time()
const Time & time () const inline
Definition at line 126 of file pointMesh.H.
Referenced by uniformInterpolatedDisplacementPointPatchVectorField::updateCoeffs().
boundaryMesh()
const polyBoundaryMesh & boundaryMesh () const inline
Definition at line 135 of file pointMesh.H.
movePoints()
bool movePoints ()
Definition at line 86 of file pointMesh.C.
References Foam::endl(), points, and Foam::Pout.
updateMesh()
void updateMesh (const mapPolyMesh & mpm)
Definition at line 100 of file pointMesh.C.
References Foam::endl(), Foam::nl, and Foam::Pout.
operator!=()
bool operator!= (const pointMesh & pm) const inline
Definition at line 152 of file pointMesh.H.
operator==()
bool operator== (const pointMesh & pm) const inline
Definition at line 157 of file pointMesh.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/pointMesh/pointMesh.H
src/OpenFOAM/meshes/pointMesh/pointMesh.C