OpenFOAM: inverseDistance Class Reference
inverseDistance Class Reference
Inverse-distance-weighted interpolation stencil.
#include <inverseDistanceCellCellStencil.H>
Classes
struct interpolatedDonorSet
Public Member Functions
TypeName ("inverseDistance")
inverseDistance (const fvMesh &, const dictionary &, const bool)
virtual ~inverseDistance ()
virtual bool update ()
virtual const labelUList & cellTypes () const
virtual const labelUList & interpolationCells () const
virtual const mapDistribute & cellInterpolationMap () const
virtual const labelListList & cellStencil () const
virtual const scalarListList & cellInterpolationWeights () const
virtual const scalarList & cellInterpolationWeight () const
virtual void stencilWeights (const point &sample, const pointList &donorCcs, scalarList &weights) const
Public Member Functions inherited from cellCellStencil
TypeName ("cellCellStencil")
declareRunTimeSelectionTable (autoPtr, cellCellStencil, mesh,(const fvMesh &mesh, const dictionary &dict, const bool update),(mesh, dict, update))
cellCellStencil (const fvMesh &)
virtual ~cellCellStencil ()
virtual const wordHashSet & nonInterpolatedFields () const
virtual wordHashSet & nonInterpolatedFields ()
bool localStencil (const labelUList &) const
const labelIOList & zoneID () const
template<class T >
void interpolate (const fvMesh &mesh, Field< T > &psi) const
template<class GeoField >
void interpolate (GeoField &psi) const
template<class GeoField >
void interpolate (const fvMesh &mesh, const wordHashSet &suppressed) const
void walkFront (const globalIndex &globalCells, const scalar layerRelax, const labelListList &allStencil, labelList &allCellTypes, scalarField &allWeight, const scalarList &compactCellVol, const labelListList &compactStencil, const labelList &zoneID, const label holeLayers, const label useLayer) const
void setUpFront (const labelList &allCellTypes, bitSet &isFront) const
void setUpFrontOnOversetPatch (const labelList &allCellTypes, bitSet &isFront) const
void seedCell (const label cellI, const scalar wantedFraction, bitSet &isFront, scalarField &fraction) const
InfoProxy< cellCellStencil > info () const noexcept
template<class Type >
Foam::tmp< Foam::volScalarField > createField (const fvMesh &mesh, const word &name, const UList< Type > &psi)
Protected Member Functions
void markPatchesAsHoles (PstreamBuffers &pBufs, const PtrList< fvMeshSubset > &meshParts, const List< treeBoundBoxList > &patchBb, const List< labelVector > &patchDivisions, const PtrList< PackedList< 2 > > &patchParts, const label srcI, const label tgtI, labelList &allCellTypes) const
bool betterDonor (const label destMesh, const label currentDonorMesh, const label newDonorMesh) const
void markDonors (const globalIndex &globalCells, PstreamBuffers &pBufs, const PtrList< fvMeshSubset > &meshParts, const List< treeBoundBoxList > &meshBb, const labelList &allCellTypes, const label srcI, const label tgtI, labelListList &allStencil, labelList &allDonor) const
void uncompactedRegionSplit (const fvMesh &mesh, const globalIndex &globalFaces, const label nZones, const labelList &zoneID, const labelList &cellTypes, const boolList &isBlockedFace, labelList &cellRegion) const
autoPtr< globalIndex > compactedRegionSplit (const fvMesh &mesh, const globalIndex &globalFaces, labelList &cellRegion) const
void findHoles (const globalIndex &globalCells, const fvMesh &mesh, const labelList &zoneID, const labelListList &stencil, labelList &cellTypes) const
void seedCell (const label cellI, const scalar wantedFraction, bitSet &isFront, scalarField &fraction) const
virtual void createStencil (const globalIndex &, const bool allowHoleDonors)
void holeExtrapolationStencil (const globalIndex &globalCells)
Static Protected Member Functions
static label index (const labelVector &nDivs, const labelVector &)
static labelVector index3 (const labelVector &nDivs, const label)
static labelVector index3 (const boundBox &bb, const labelVector &nDivs, const point &pt)
static point position (const boundBox &bb, const labelVector &nDivs, const label boxI)
static void fill (PackedList< 2 > &elems, const boundBox &bb, const labelVector &nDivs, const boundBox &subBb, const unsigned int val)
static bool overlaps (const boundBox &bb, const labelVector &nDivs, const PackedList< 2 > &voxels, const treeBoundBox &subBb, const unsigned int val)
static void markBoundaries (const fvMesh &mesh, const vector &smallVec, const boundBox &bb, const labelVector &nDivs, PackedList< 2 > &patchTypes, const labelList &cellMap, labelList &patchCellTypes)
Static Protected Member Functions inherited from cellCellStencil
template<class Type >
static tmp< volScalarField > createField (const fvMesh &mesh, const word &name, const UList< Type > &)
static word baseName (const word &name)
Protected Attributes
const dictionary dict_
const bool allowHoleDonors_
const bool allowInterpolatedDonors_
vector smallVec_
labelList cellTypes_
labelList interpolationCells_
autoPtr< mapDistribute > cellInterpolationMap_
labelListList cellStencil_
scalarListList cellInterpolationWeights_
volScalarField cellInterpolationWeight_
Protected Attributes inherited from cellCellStencil
const fvMesh & mesh_
wordHashSet nonInterpolatedFields_
const dictionary dict_
Additional Inherited Members
Public Types inherited from cellCellStencil
enum patchCellType { OTHER = 0 , PATCH = 1 , OVERSET = 2 }
enum cellType {
CALCULATED = 0 , INTERPOLATED = 1 , HOLE = 2 , SPECIAL = 3 ,
POROUS = 4
}
Static Public Member Functions inherited from cellCellStencil
static autoPtr< cellCellStencil > New (const fvMesh &, const dictionary &dict, const bool update=true)
static const labelIOList & zoneID (const fvMesh &)
static labelList count (const label size, const labelUList &lst)
static void globalCellCells (const globalIndex &gi, const polyMesh &mesh, const boolList &isValidDonor, const labelList &selectedCells, labelListList &cellCells, pointListList &cellCellCentres)
template<class T >
static void interpolate (Field< T > &psi, const fvMesh &mesh, const cellCellStencil &overlap, const List< scalarList > &wghts)
template<class GeoField , class SuppressBC >
static void correctBoundaryConditions (GeoField &psi)
Static Protected Attributes inherited from cellCellStencil
static const Enum< cellType > cellTypeNames_
Detailed Description
Inverse-distance-weighted interpolation stencil.
hole finding:
mark boundary faces on helper (voxel) mesh
mark any cell overlaying these voxels
use flood filling to find any unreachable cell Alternative is to use an octree of the boundary faces and determine directly for all cells whether we are outside. Might be slow though.
Source files
inverseDistanceCellCellStencil.H
inverseDistanceCellCellStencil.C
Definition at line 63 of file inverseDistanceCellCellStencil.H.
Constructor & Destructor Documentation
inverseDistance()
inverseDistance (const fvMesh & mesh, const dictionary & dict, const bool doUpdate)
Definition at line 1699 of file inverseDistanceCellCellStencil.C.
References inverseDistance::cellTypes_, Foam::endl(), forAll, HashSet< Key, Hash >::insert(), io(), cellCellStencil::mesh_, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, cellCellStencil::nonInterpolatedFields_, Foam::Pout, IOobjectOption::READ_IF_PRESENT, inverseDistance::update(), and cellCellStencil::zoneID().
~inverseDistance()
~inverseDistance () virtual
Definition at line 1785 of file inverseDistanceCellCellStencil.C.
Member Function Documentation
index()
Foam::label index (const labelVector & nDivs, const labelVector & ijk) static protected
Definition at line 55 of file inverseDistanceCellCellStencil.C.
index3() [1/2]
Foam::labelVector index3 (const labelVector & nDivs, const label boxI) static protected
Definition at line 65 of file inverseDistanceCellCellStencil.C.
References k.
index3() [2/2]
Foam::labelVector index3 (const boundBox & bb, const labelVector & nDivs, const point & pt) static protected
Definition at line 80 of file inverseDistanceCellCellStencil.C.
References boundBox::min(), and boundBox::span().
position()
Foam::point position (const boundBox & bb, const labelVector & nDivs, const label boxI) static protected
Definition at line 99 of file inverseDistanceCellCellStencil.C.
References boundBox::min(), and boundBox::span().
fill()
void fill (PackedList< 2 > & elems, const boundBox & bb, const labelVector & nDivs, const boundBox & subBb, const unsigned int val) static protected
Definition at line 116 of file inverseDistanceCellCellStencil.C.
References k, Foam::max(), Foam::min(), and VectorSpace< Form, Cmpt, Ncmpts >::zero.
overlaps()
bool overlaps (const boundBox & bb, const labelVector & nDivs, const PackedList< 2 > & voxels, const treeBoundBox & subBb, const unsigned int val) static protected
Definition at line 230 of file inverseDistanceCellCellStencil.C.
References k, Foam::max(), Foam::min(), and VectorSpace< Form, Cmpt, Ncmpts >::zero.
markBoundaries()
void markBoundaries (const fvMesh & mesh, const vector & smallVec, const boundBox & bb, const labelVector & nDivs, PackedList< 2 > & patchTypes, const labelList & cellMap, labelList & patchCellTypes) static protected
Definition at line 154 of file inverseDistanceCellCellStencil.C.
References fvPatch::constraintType(), forAll, mesh, boundBox::overlaps(), patchTypes(), pbm, and pp().
markPatchesAsHoles()
void markPatchesAsHoles (PstreamBuffers & pBufs, const PtrList< fvMeshSubset > & meshParts, const List< treeBoundBoxList > & patchBb, const List< labelVector > & patchDivisions, const PtrList< PackedList< 2 > > & patchParts, const label srcI, const label tgtI, labelList & allCellTypes) const protected
Definition at line 274 of file inverseDistanceCellCellStencil.C.
References UPstream::allProcs(), PtrList< T >::clear(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, UPstream::myProcNo(), and os().
betterDonor()
bool betterDonor (const label destMesh, const label currentDonorMesh, const label newDonorMesh) const protected
Definition at line 398 of file inverseDistanceCellCellStencil.C.
References Foam::mag().
markDonors()
void markDonors (const globalIndex & globalCells, PstreamBuffers & pBufs, const PtrList< fvMeshSubset > & meshParts, const List< treeBoundBoxList > & meshBb, const labelList & allCellTypes, const label srcI, const label tgtI, labelListList & allStencil, labelList & allDonor) const protected
Definition at line 440 of file inverseDistanceCellCellStencil.C.
References Foam::abort(), UPstream::allProcs(), PtrList< T >::append(), waveMethod::calculate(), polyMesh::CELL_TETS, cellIDs, PtrList< T >::clear(), Foam::FatalError, FatalErrorInFunction, forAll, meshBb(), UPstream::myProcNo(), UPstream::nProcs(), os(), samples(), PtrList< T >::setSize(), and UPtrList< T >::size().
uncompactedRegionSplit()
void uncompactedRegionSplit (const fvMesh & mesh, const globalIndex & globalFaces, const label nZones, const labelList & zoneID, const labelList & cellTypes, const boolList & isBlockedFace, labelList & cellRegion) const protected
compactedRegionSplit()
autoPtr< globalIndex > compactedRegionSplit (const fvMesh & mesh, const globalIndex & globalFaces, labelList & cellRegion) const protected
findHoles()
void findHoles (const globalIndex & globalCells, const fvMesh & mesh, const labelList & zoneID, const labelListList & stencil, labelList & cellTypes) const protected
Definition at line 893 of file inverseDistanceCellCellStencil.C.
References cellTypes, fvPatch::constraintType(), DebugInfo, mapDistribute::distribute(), Foam::endl(), Foam::findIndices(), forAll, FUNCTION_NAME, Pstream::listCombineReduce(), mesh, pbm, Foam::reduce(), UList< T >::size(), syncTools::swapBoundaryCellList(), Foam::type(), and Foam::Zero.
seedCell()
void seedCell (const label cellI, const scalar wantedFraction, bitSet & isFront, scalarField & fraction) const protected
createStencil()
void createStencil (const globalIndex & globalCells, const bool allowHoleDonors) protected virtual
Definition at line 1502 of file inverseDistanceCellCellStencil.C.
References Foam::abort(), PtrList< T >::append(), Foam::FatalError, FatalErrorInFunction, forAll, UPstream::msgType(), UPstream::nonBlocking, nSamples(), List< T >::null(), Foam::returnReduceOr(), samples(), PtrList< T >::set(), UPtrList< T >::size(), and PtrList< T >::transfer().
holeExtrapolationStencil()
void holeExtrapolationStencil (const globalIndex & globalCells) protected
Definition at line 1210 of file inverseDistanceCellCellStencil.C.
References PtrList< T >::append(), cellCellStencil::CALCULATED, Foam::endl(), forAll, cellCellStencil::HOLE, Foam::identity(), cellCellStencil::INTERPOLATED, Foam::labelMin, UPstream::myProcNo(), Foam::nl, UPstream::nonBlocking, Foam::Pout, Foam::reduce(), PtrList< T >::setSize(), and syncTools::swapBoundaryCellList().
TypeName()
TypeName ("inverseDistance")
update()
bool update () virtual
Implements cellCellStencil.
Reimplemented in trackingInverseDistance.
Definition at line 1791 of file inverseDistanceCellCellStencil.C.
References Pstream::allGatherList(), PtrList< T >::append(), Foam::cbrt(), PtrList< T >::clear(), oversetFvMeshBase::correctBoundaryConditions(), DebugInfo, Foam::decrIndent(), mapDistribute::distribute(), e, Foam::endl(), forAll, dictionary::found(), FUNCTION_NAME, Foam::gMax(), Foam::incrIndent(), Foam::indent(), Foam::Info, Pstream::listCombineReduce(), Foam::mag(), meshBb(), Foam::mkDir(), UPstream::myProcNo(), OFstream::name(), Foam::name(), polyMesh::nGeometricD(), Foam::nl, UPstream::nonBlocking, primitiveMesh::nPoints(), UPstream::nProcs(), polyMesh::points(), Foam::Pout, Foam::reduce(), Foam::returnReduce(), schemesLookup::schemesDict(), PtrList< T >::set(), PtrList< T >::setSize(), UPtrList< T >::size(), Foam::sqrt(), dictionary::subDict(), PtrList< T >::transfer(), Foam::type(), OBJstream::writeLine(), and Foam::Zero.
Referenced by inverseDistance::cellInterpolationMap(), inverseDistance::inverseDistance(), and leastSquares::leastSquares().
cellTypes()
virtual const labelUList & cellTypes () const inline virtual
Implements cellCellStencil.
Definition at line 294 of file inverseDistanceCellCellStencil.H.
References inverseDistance::cellTypes_.
interpolationCells()
virtual const labelUList & interpolationCells () const inline virtual
Implements cellCellStencil.
Definition at line 300 of file inverseDistanceCellCellStencil.H.
References inverseDistance::interpolationCells_.
cellInterpolationMap()
virtual const mapDistribute & cellInterpolationMap () const inline virtual
Implements cellCellStencil.
Definition at line 306 of file inverseDistanceCellCellStencil.H.
References inverseDistance::cellInterpolationMap_, and inverseDistance::update().
cellStencil()
virtual const labelListList & cellStencil () const inline virtual
Implements cellCellStencil.
Definition at line 317 of file inverseDistanceCellCellStencil.H.
References inverseDistance::cellStencil_.
cellInterpolationWeights()
virtual const scalarListList & cellInterpolationWeights () const inline virtual
Implements cellCellStencil.
Definition at line 323 of file inverseDistanceCellCellStencil.H.
References inverseDistance::cellInterpolationWeights_.
cellInterpolationWeight()
virtual const scalarList & cellInterpolationWeight () const inline virtual
Implements cellCellStencil.
Definition at line 330 of file inverseDistanceCellCellStencil.H.
References inverseDistance::cellInterpolationWeight_.
stencilWeights()
void stencilWeights (const point & sample, const pointList & donorCcs, scalarList & weights) const virtual
Implements cellCellStencil.
Reimplemented in leastSquares.
Definition at line 1175 of file inverseDistanceCellCellStencil.C.
References forAll, Foam::mag(), List< T >::setSize(), UPtrList< T >::size(), and Foam::sum().
Member Data Documentation
dict_
const dictionary dict_ protected
Definition at line 81 of file inverseDistanceCellCellStencil.H.
allowHoleDonors_
const bool allowHoleDonors_ protected
Definition at line 84 of file inverseDistanceCellCellStencil.H.
allowInterpolatedDonors_
const bool allowInterpolatedDonors_ protected
Definition at line 87 of file inverseDistanceCellCellStencil.H.
smallVec_
vector smallVec_ protected
Definition at line 90 of file inverseDistanceCellCellStencil.H.
cellTypes_
labelList cellTypes_ protected
Definition at line 93 of file inverseDistanceCellCellStencil.H.
Referenced by inverseDistance::cellTypes(), and inverseDistance::inverseDistance().
interpolationCells_
labelList interpolationCells_ protected
Definition at line 96 of file inverseDistanceCellCellStencil.H.
Referenced by inverseDistance::interpolationCells().
cellInterpolationMap_
autoPtr<mapDistribute> cellInterpolationMap_ protected
Definition at line 99 of file inverseDistanceCellCellStencil.H.
Referenced by inverseDistance::cellInterpolationMap().
cellStencil_
labelListList cellStencil_ protected
Definition at line 102 of file inverseDistanceCellCellStencil.H.
Referenced by inverseDistance::cellStencil().
cellInterpolationWeights_
scalarListList cellInterpolationWeights_ protected
Definition at line 105 of file inverseDistanceCellCellStencil.H.
Referenced by inverseDistance::cellInterpolationWeights().
cellInterpolationWeight_
volScalarField cellInterpolationWeight_ protected
Definition at line 108 of file inverseDistanceCellCellStencil.H.
Referenced by inverseDistance::cellInterpolationWeight().
The documentation for this class was generated from the following files:
src/overset/cellCellStencil/inverseDistance/inverseDistanceCellCellStencil.H
src/overset/cellCellStencil/inverseDistance/inverseDistanceCellCellStencil.C