OpenFOAM: SymmTensor2D< Cmpt > Class Template Reference
SymmTensor2D< Cmpt > Class Template Reference
A templated (2 x 2) symmetric tensor of objects of <T>, effectively containing 3 elements, derived from VectorSpace.
#include <SymmTensor2D.H>
Public Types
enum components { XX , XY , YY }
typedef SymmTensor2D< label > labelType
Public Types inherited from VectorSpace< SymmTensor2D< Cmpt >, Cmpt, 3 >
typedef VectorSpace< SymmTensor2D< Cmpt >, Cmpt, Ncmpts > vsType
typedef Cmpt cmptType
typedef Cmpt magType
typedef Cmpt * iterator
typedef const Cmpt * const_iterator
Public Member Functions
SymmTensor2D ()=default
SymmTensor2D (const SymmTensor2D &)=default
SymmTensor2D & operator= (const SymmTensor2D &)=default
SymmTensor2D (const Foam::zero)
SymmTensor2D (const VectorSpace< SymmTensor2D< Cmpt >, Cmpt, 3 > &)
SymmTensor2D (const SphericalTensor2D< Cmpt > &)
SymmTensor2D (const Cmpt txx, const Cmpt txy, const Cmpt tyy)
SymmTensor2D (Istream &is)
const Cmpt & xx () const noexcept
const Cmpt & xy () const noexcept
const Cmpt & yx () const noexcept
const Cmpt & yy () const noexcept
Cmpt & xx () noexcept
Cmpt & xy () noexcept
Cmpt & yx () noexcept
Cmpt & yy () noexcept
Vector2D< Cmpt > diag () const
void diag (const Vector2D< Cmpt > &v)
scalar diagSqr () const
const SymmTensor2D< Cmpt > & T () const noexcept
Cmpt det () const
SymmTensor2D< Cmpt > adjunct () const
SymmTensor2D< Cmpt > cof () const
SymmTensor2D< Cmpt > inv () const
void operator= (const SphericalTensor2D< Cmpt > &)
Public Member Functions inherited from VectorSpace< SymmTensor2D< Cmpt >, Cmpt, 3 >
VectorSpace ()=default
VectorSpace (const Foam::zero)
VectorSpace (const VectorSpace< SymmTensor2D< Cmpt >, Cmpt, Ncmpts > &vs)
VectorSpace (const VectorSpace< Form2, Cmpt2, Ncmpts > &)
VectorSpace (Istream &is)
const Cmpt & component (const direction) const
Cmpt & component (const direction)
void component (Cmpt &, const direction) const
void replace (const direction, const Cmpt &)
const Cmpt * cdata () const noexcept
Cmpt * data () noexcept
const ConstBlock< SubVector, BStart > block () const
const Foam::VectorSpace< SymmTensor2D< Cmpt >, Cmpt, Ncmpts >::template ConstBlock< SubVector, BStart > block () const
const Cmpt & operator[] (const direction) const
Cmpt & operator[] (const direction)
void operator= (const VectorSpace< SymmTensor2D< Cmpt >, Cmpt, Ncmpts > &)
void operator= (const Foam::zero)
void operator+= (const VectorSpace< SymmTensor2D< Cmpt >, Cmpt, Ncmpts > &)
void operator-= (const VectorSpace< SymmTensor2D< Cmpt >, Cmpt, Ncmpts > &)
void operator*= (const scalar)
void operator/= (const scalar)
iterator begin () noexcept
const_iterator begin () const noexcept
iterator end () noexcept
const_iterator end () const noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
Static Public Attributes
static constexpr direction rank = 2
static const SymmTensor2D I
Static Public Attributes inherited from VectorSpace< SymmTensor2D< Cmpt >, Cmpt, 3 >
static constexpr direction dim
static constexpr direction nComponents
static constexpr direction mRows
static constexpr direction nCols
static const char *const typeName
static const char *const componentNames []
static const SymmTensor2D< Cmpt > zero
static const SymmTensor2D< Cmpt > one
static const SymmTensor2D< Cmpt > max
static const SymmTensor2D< Cmpt > min
static const SymmTensor2D< Cmpt > rootMax
static const SymmTensor2D< Cmpt > rootMin
Additional Inherited Members
Static Public Member Functions inherited from VectorSpace< SymmTensor2D< Cmpt >, Cmpt, 3 >
static constexpr direction size () noexcept
static SymmTensor2D< Cmpt > uniform (const Cmpt &s)
Public Attributes inherited from VectorSpace< SymmTensor2D< Cmpt >, Cmpt, 3 >
Cmpt v_ [Ncmpts]
Detailed Description
template<class Cmpt>
class Foam::SymmTensor2D< Cmpt >
A templated (2 x 2) symmetric tensor of objects of <T>, effectively containing 3 elements, derived from VectorSpace.
See also
Test-SymmTensor2D.C
Source files
SymmTensor2D.H
SymmTensor2DI.H
Definition at line 54 of file SymmTensor2D.H.
Member Typedef Documentation
labelType
template<class Cmpt > typedef SymmTensor2D<label> labelType
Definition at line 63 of file SymmTensor2D.H.
Member Enumeration Documentation
components
template<class Cmpt > enum components
Enumerator
XX
XY
YY
Definition at line 78 of file SymmTensor2D.H.
Constructor & Destructor Documentation
SymmTensor2D() [1/7]
template<class Cmpt > SymmTensor2D () default
SymmTensor2D() [2/7]
template<class Cmpt > SymmTensor2D (const SymmTensor2D< Cmpt > &) default
SymmTensor2D() [3/7]
template<class Cmpt > SymmTensor2D (const Foam::zero) inline
Definition at line 27 of file SymmTensor2DI.H.
SymmTensor2D() [4/7]
template<class Cmpt > SymmTensor2D (const VectorSpace< SymmTensor2D< Cmpt >, Cmpt, 3 > & vs) inline
Definition at line 34 of file SymmTensor2DI.H.
SymmTensor2D() [5/7]
template<class Cmpt > SymmTensor2D (const SphericalTensor2D< Cmpt > & st) inline
Definition at line 44 of file SymmTensor2DI.H.
References Foam::Zero.
SymmTensor2D() [6/7]
template<class Cmpt > SymmTensor2D (const Cmpt txx, const Cmpt txy, const Cmpt tyy) inline
Definition at line 52 of file SymmTensor2DI.H.
SymmTensor2D() [7/7]
template<class Cmpt > SymmTensor2D (Istream & is) inline explicit
Definition at line 64 of file SymmTensor2DI.H.
Member Function Documentation
operator=() [1/2]
template<class Cmpt > SymmTensor2D & operator= (const SymmTensor2D< Cmpt > &) default
xx() [1/2]
template<class Cmpt > const Cmpt & xx () const inline noexcept
Definition at line 119 of file SymmTensor2D.H.
References VectorSpace< SymmTensor2D< Cmpt >, Cmpt, 3 >::v_, and SymmTensor2D< Cmpt >::XX.
xy() [1/2]
template<class Cmpt > const Cmpt & xy () const inline noexcept
Definition at line 120 of file SymmTensor2D.H.
References VectorSpace< SymmTensor2D< Cmpt >, Cmpt, 3 >::v_, and SymmTensor2D< Cmpt >::XY.
yx() [1/2]
template<class Cmpt > const Cmpt & yx () const inline noexcept
Definition at line 121 of file SymmTensor2D.H.
References VectorSpace< SymmTensor2D< Cmpt >, Cmpt, 3 >::v_, and SymmTensor2D< Cmpt >::XY.
yy() [1/2]
template<class Cmpt > const Cmpt & yy () const inline noexcept
Definition at line 122 of file SymmTensor2D.H.
References VectorSpace< SymmTensor2D< Cmpt >, Cmpt, 3 >::v_, and SymmTensor2D< Cmpt >::YY.
xx() [2/2]
template<class Cmpt > Cmpt & xx () inline noexcept
Definition at line 124 of file SymmTensor2D.H.
References VectorSpace< SymmTensor2D< Cmpt >, Cmpt, 3 >::v_, and SymmTensor2D< Cmpt >::XX.
xy() [2/2]
template<class Cmpt > Cmpt & xy () inline noexcept
Definition at line 125 of file SymmTensor2D.H.
References VectorSpace< SymmTensor2D< Cmpt >, Cmpt, 3 >::v_, and SymmTensor2D< Cmpt >::XY.
yx() [2/2]
template<class Cmpt > Cmpt & yx () inline noexcept
Definition at line 126 of file SymmTensor2D.H.
References VectorSpace< SymmTensor2D< Cmpt >, Cmpt, 3 >::v_, and SymmTensor2D< Cmpt >::XY.
yy() [2/2]
template<class Cmpt > Cmpt & yy () inline noexcept
Definition at line 127 of file SymmTensor2D.H.
References VectorSpace< SymmTensor2D< Cmpt >, Cmpt, 3 >::v_, and SymmTensor2D< Cmpt >::YY.
diag() [1/2]
template<class Cmpt > Foam::Vector2D< Cmpt > diag () const inline
Definition at line 73 of file SymmTensor2DI.H.
diag() [2/2]
template<class Cmpt > void diag (const Vector2D< Cmpt > & v) inline
Definition at line 80 of file SymmTensor2DI.H.
diagSqr()
template<class Cmpt > Foam::scalar diagSqr () const inline
Definition at line 87 of file SymmTensor2DI.H.
References Foam::magSqr().
T()
template<class Cmpt > const SymmTensor2D< Cmpt > & T () const inline noexcept
Definition at line 145 of file SymmTensor2D.H.
det()
template<class Cmpt > Cmpt det () const inline
Definition at line 98 of file SymmTensor2DI.H.
adjunct()
template<class Cmpt > Foam::SymmTensor2D< Cmpt > adjunct () const inline
Definition at line 105 of file SymmTensor2DI.H.
cof()
template<class Cmpt > Foam::SymmTensor2D< Cmpt > cof () const inline
Definition at line 117 of file SymmTensor2DI.H.
inv()
template<class Cmpt > Foam::SymmTensor2D< Cmpt > inv () const inline
Definition at line 126 of file SymmTensor2DI.H.
References Foam::abort(), Foam::det(), Foam::FatalError, FatalErrorInFunction, Foam::mag(), and Foam::nl.
operator=() [2/2]
template<class Cmpt > void operator= (const SphericalTensor2D< Cmpt > & st) inline
Definition at line 147 of file SymmTensor2DI.H.
References Foam::Zero.
Member Data Documentation
rank
template<class Cmpt > constexpr direction rank = 2 static constexpr
Definition at line 69 of file SymmTensor2D.H.
I
const Foam::symmTensor2D I static
Definition at line 74 of file SymmTensor2D.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/SymmTensor2D/SymmTensor2D.H
src/OpenFOAM/primitives/SymmTensor2D/symmTensor2D/symmTensor2D.C
src/OpenFOAM/primitives/SymmTensor2D/SymmTensor2DI.H