OpenFOAM: cyclicAMILduInterfaceField Class Reference
cyclicAMILduInterfaceField Class Reference abstract
Abstract base class for cyclic AMI coupled interfaces.
#include <cyclicAMILduInterfaceField.H>
Public Member Functions
TypeName ("cyclicAMILduInterfaceField")
cyclicAMILduInterfaceField ()
virtual ~cyclicAMILduInterfaceField ()
virtual bool doTransform () const =0
virtual const tensorField & forwardT () const =0
virtual const tensorField & reverseT () const =0
virtual int rank () const =0
template<class Type >
void transformCoupleField (Field< Type > &f) const
void transformCoupleField (solveScalarField &psiInternal, const direction cmpt) const
Detailed Description
Abstract base class for cyclic AMI coupled interfaces.
Source files
cyclicAMILduInterfaceField.H
cyclicAMILduInterfaceField.C
Definition at line 47 of file cyclicAMILduInterfaceField.H.
Constructor & Destructor Documentation
cyclicAMILduInterfaceField()
cyclicAMILduInterfaceField () inline
Definition at line 59 of file cyclicAMILduInterfaceField.H.
~cyclicAMILduInterfaceField()
~cyclicAMILduInterfaceField () virtual
Definition at line 35 of file cyclicAMILduInterfaceField.C.
Member Function Documentation
TypeName()
TypeName ("cyclicAMILduInterfaceField")
doTransform()
virtual bool doTransform () const pure virtual
Implemented in cyclicACMIFvPatchField< Type >, cyclicAMIFvPatchField< Type >, cyclicAMIFvPatchField< scalar >, cyclicACMIGAMGInterfaceField, and cyclicAMIGAMGInterfaceField.
Referenced by cyclicAMILduInterfaceField::transformCoupleField().
forwardT()
virtual const tensorField & forwardT () const pure virtual
Implemented in cyclicACMIFvPatchField< Type >, cyclicAMIFvPatchField< Type >, cyclicAMIFvPatchField< scalar >, cyclicACMIGAMGInterfaceField, and cyclicAMIGAMGInterfaceField.
Referenced by cyclicAMILduInterfaceField::transformCoupleField().
reverseT()
virtual const tensorField & reverseT () const pure virtual
Implemented in cyclicACMIFvPatchField< Type >, cyclicAMIFvPatchField< Type >, cyclicAMIFvPatchField< scalar >, cyclicACMIGAMGInterfaceField, and cyclicAMIGAMGInterfaceField.
rank()
virtual int rank () const pure virtual
Implemented in cyclicACMIFvPatchField< Type >, cyclicAMIFvPatchField< Type >, cyclicAMIFvPatchField< scalar >, cyclicACMIGAMGInterfaceField, and cyclicAMIGAMGInterfaceField.
transformCoupleField() [1/2]
template<class Type > void transformCoupleField (Field< Type > & f) const
Definition at line 106 of file cyclicAMILduInterfaceField.H.
References cyclicAMILduInterfaceField::doTransform(), f(), cyclicAMILduInterfaceField::forwardT(), and Foam::transform().
Referenced by cyclicACMILduInterfaceField::transformCoupleField(), and cyclicACMILduInterfaceField::transformCoupleField().
transformCoupleField() [2/2]
void transformCoupleField (solveScalarField & psiInternal, const direction cmpt) const
Definition at line 41 of file cyclicAMILduInterfaceField.C.
References Foam::component(), Foam::diag(), f(), and Foam::pow().
The documentation for this class was generated from the following files:
src/meshTools/AMIInterpolation/patches/cyclicAMI/cyclicAMILduInterfaceField/cyclicAMILduInterfaceField.H
src/meshTools/AMIInterpolation/patches/cyclicAMI/cyclicAMILduInterfaceField/cyclicAMILduInterfaceField.C