OpenFOAM: CelikEtaIndex Class Reference
CelikEtaIndex Class Reference
Computes a single-mesh resolution index according to Celik et al.'s index using Kolmogorov length scale, which is used as a LES/DES quality/post verification metric that does not require any experimental or DNS data.
#include <CelikEtaIndex.H>
Public Member Functions
TypeName ("CelikEtaIndex")
CelikEtaIndex (const word &name, const fvMesh &mesh, const dictionary &dict)
CelikEtaIndex (const CelikEtaIndex &)=delete
void operator= (const CelikEtaIndex &)=delete
virtual ~CelikEtaIndex ()=default
virtual bool read (const dictionary &dict)
virtual bool execute ()
virtual bool write ()
Public Member Functions inherited from resolutionIndexModel
TypeName ("resolutionIndexModel")
declareRunTimeSelectionTable (autoPtr, resolutionIndexModel, dictionary,(const word &name, const fvMesh &mesh, const dictionary &dict),(name, mesh, dict))
resolutionIndexModel (const word &name, const fvMesh &mesh, const dictionary &dict)
resolutionIndexModel (const resolutionIndexModel &)=delete
void operator= (const resolutionIndexModel &)=delete
virtual ~resolutionIndexModel ()=default
const fvMesh & mesh () const noexcept
const word & resultName () const noexcept
Additional Inherited Members
Static Public Member Functions inherited from resolutionIndexModel
static autoPtr< resolutionIndexModel > New (const word &name, const fvMesh &mesh, const dictionary &dict)
Protected Member Functions inherited from resolutionIndexModel
template<class GeoFieldType >
GeoFieldType & getOrReadField (const word &fieldName) const
tmp< volScalarField > V () const
Detailed Description
Computes a single-mesh resolution index according to Celik et al.'s index using Kolmogorov length scale, which is used as a LES/DES quality/post verification metric that does not require any experimental or DNS data.
with
where
= Celik et al.'s index [-]
= Empirical constant [-]
= Characteristic length scale with [m]
= Cell volume [m^3]
= Kolmogorov length scale [m]
= Empirical exponent [-]
= Kinematic viscosity of fluid [m^2/s]
= Kinetic energy dissipation rate [m^2/s^3]
= Effective eddy viscosity [m^2/s]
= Numerical eddy viscosity [m^2/s]
= Subgrid-scale eddy viscosity [m^2/s]
= Numerical turbulent kinetic energy [m^2/s^2]
= Empirical constant [-]
= Filter length scale [m]
= Subgrid-scale turbulent kinetic energy [m^2/s^2]
= Empirical constant [-]
= Empirical constant [-]
References:
        Governing equations (tag:CCY):
            Celik, I. B., Cehreli Z. N., Yavuz I. (2005).
            Index of resolution quality for large eddy simulations.
            Journal of Fluids Engineering. 127:949–958.
            DOI:10.1115/1.1990201
        Governing equations (tag:CKJ):
            Celik, I., Klein, M., & Janicka, J. (2009).
            Assessment measures for engineering LES applications.
            Journal of fluids engineering, 131(3).
            DOI:10.1115/1.3059703
Usage
Minimal example by using system/controlDict.functions:
resolutionIndex1
{
    // Inherited entries
    ...
    model       CelikEtaIndex;
    // Optional entries
    alphaEta    <scalar>;
    m           <scalar>;
    Cnu         <scalar>;
    Cn          <scalar>;
    Ck          <scalar>;
    k           <word>;
    delta       <word>;
    nu          <word>;
    nut         <word>;
}
where the entries mean:
Property Description Type Reqd Deflt
model Model name: CelikEtaIndex word yes -
alphaEta Empirical constant scalar no 0.05
m Empirical exponent scalar no 0.5
Cnu Empirical constant scalar no 0.1
Cn Empirical constant scalar no 1.0
Ck Empirical constant scalar no 0.0376
k
Name of subgrid-scale turbulent kinetic energy field
word no k
delta Name of filter field word no delta
nu Name of kinematic viscosity field word no nu
nut Name of subgrid-scale eddy viscosity field word no nut
Source files
CelikEtaIndex.H
CelikEtaIndex.C
Definition at line 287 of file CelikEtaIndex.H.
Constructor & Destructor Documentation
CelikEtaIndex() [1/2]
CelikEtaIndex (const word & name, const fvMesh & mesh, const dictionary & dict)
Definition at line 103 of file CelikEtaIndex.C.
References dict, and CelikEtaIndex::read().
CelikEtaIndex() [2/2]
CelikEtaIndex (const CelikEtaIndex &) delete
~CelikEtaIndex()
virtual ~CelikEtaIndex () virtual default
Member Function Documentation
TypeName()
TypeName ("CelikEtaIndex")
operator=()
void operator= (const CelikEtaIndex &) delete
read()
bool read (const dictionary & dict) virtual
Reimplemented from resolutionIndexModel.
Definition at line 127 of file CelikEtaIndex.C.
References dict, and resolutionIndexModel::read().
Referenced by CelikEtaIndex::CelikEtaIndex().
execute()
bool execute () virtual
Implements resolutionIndexModel.
Definition at line 149 of file CelikEtaIndex.C.
References Foam::cbrt(), and Foam::pow().
write()
bool write () virtual
Implements resolutionIndexModel.
Definition at line 166 of file CelikEtaIndex.C.
References Foam::endl(), Foam::Info, Foam::tab, and Ostream::write().
The documentation for this class was generated from the following files:
src/functionObjects/field/resolutionIndex/resolutionIndexModels/CelikEtaIndex/CelikEtaIndex.H
src/functionObjects/field/resolutionIndex/resolutionIndexModels/CelikEtaIndex/CelikEtaIndex.C