OpenFOAM: turbulentMixingLengthDissipationRateInletFvPatchScalarField Class Reference
turbulentMixingLengthDissipationRateInletFvPatchScalarField Class Reference
Turbulence models » RAS turbulence » Boundary conditions | Boundary conditions » Inlet
This boundary condition provides an inlet condition for turbulent kinetic energy dissipation rate, i.e. epsilon, based on a specified mixing length. The patch values are calculated using:
#include <turbulentMixingLengthDissipationRateInletFvPatchScalarField.H>
Public Member Functions
TypeName ("turbulentMixingLengthDissipationRateInlet")
turbulentMixingLengthDissipationRateInletFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
turbulentMixingLengthDissipationRateInletFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
turbulentMixingLengthDissipationRateInletFvPatchScalarField (const turbulentMixingLengthDissipationRateInletFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
turbulentMixingLengthDissipationRateInletFvPatchScalarField (const turbulentMixingLengthDissipationRateInletFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
turbulentMixingLengthDissipationRateInletFvPatchScalarField (const turbulentMixingLengthDissipationRateInletFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
This boundary condition provides an inlet condition for turbulent kinetic energy dissipation rate, i.e. epsilon, based on a specified mixing length. The patch values are calculated using:
where
= Patch epsilon values [m2/s3]
= Empirical model constant retrived from turbulence model
= Turbulent kinetic energy [m2/s2]
= Mixing length scale [m]
Usage
Example of the boundary condition specification:
<patchName>
{
    // Mandatory entries (unmodifiable)
    type            turbulentMixingLengthDissipationRateInlet;
    // Mandatory entries (runtime modifiable)
    mixingLength    0.005;
    // Optional entries (runtime modifiable)
    Cmu             0.09;
    k               k;
    phi             phi;
    // Placeholder
    value           uniform 200;
}
where the entries mean:
Property Description Type Req'd Dflt
mixingLength Mixing length scale [m] scalar yes -
Cmu Empirical model constant scalar no 0.09
phi Name of flux field word no phi
k Name of turbulent kinetic energy field word no k
Note
The boundary condition is derived from inletOutlet condition. Therefore, in the event of reverse flow, a zero-gradient condition is applied.
The order of precedence to input the empirical model constant Cmu is: turbulence model, boundary condition dictionary, and default value=0.09.
The empirical model constant Cmu is not a spatiotemporal variant field. Therefore, the use of the boundary condition may not be fully consistent with the turbulence models where Cmu is a variant field, such as realizableKE closure model in this respect. Nevertheless, workflow observations suggest that the matter poses no importance.
See also
Foam::inletOutletFvPatchField
Source files
turbulentMixingLengthDissipationRateInletFvPatchScalarField.H
turbulentMixingLengthDissipationRateInletFvPatchScalarField.C
Definition at line 155 of file turbulentMixingLengthDissipationRateInletFvPatchScalarField.H.
Constructor & Destructor Documentation
turbulentMixingLengthDissipationRateInletFvPatchScalarField() [1/5]
turbulentMixingLengthDissipationRateInletFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 36 of file turbulentMixingLengthDissipationRateInletFvPatchScalarField.C.
References Foam::Zero.
turbulentMixingLengthDissipationRateInletFvPatchScalarField() [2/5]
turbulentMixingLengthDissipationRateInletFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 70 of file turbulentMixingLengthDissipationRateInletFvPatchScalarField.C.
References dict, IOobjectOption::MUST_READ, and Foam::Zero.
turbulentMixingLengthDissipationRateInletFvPatchScalarField() [3/5]
turbulentMixingLengthDissipationRateInletFvPatchScalarField (const turbulentMixingLengthDissipationRateInletFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 54 of file turbulentMixingLengthDissipationRateInletFvPatchScalarField.C.
turbulentMixingLengthDissipationRateInletFvPatchScalarField() [4/5]
turbulentMixingLengthDissipationRateInletFvPatchScalarField (const turbulentMixingLengthDissipationRateInletFvPatchScalarField & ptf)
Definition at line 96 of file turbulentMixingLengthDissipationRateInletFvPatchScalarField.C.
turbulentMixingLengthDissipationRateInletFvPatchScalarField() [5/5]
turbulentMixingLengthDissipationRateInletFvPatchScalarField (const turbulentMixingLengthDissipationRateInletFvPatchScalarField & ptf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 109 of file turbulentMixingLengthDissipationRateInletFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("turbulentMixingLengthDissipationRateInlet")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 212 of file turbulentMixingLengthDissipationRateInletFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 231 of file turbulentMixingLengthDissipationRateInletFvPatchScalarField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 125 of file turbulentMixingLengthDissipationRateInletFvPatchScalarField.C.
References IOobject::groupName(), Foam::neg(), Foam::pow(), and turbulenceModel::propertiesName.
write()
void write (Ostream & os) const virtual
Definition at line 159 of file turbulentMixingLengthDissipationRateInletFvPatchScalarField.C.
References os(), fvPatchField< Type >::write(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/RAS/derivedFvPatchFields/turbulentMixingLengthDissipationRateInlet/turbulentMixingLengthDissipationRateInletFvPatchScalarField.H
src/TurbulenceModels/turbulenceModels/RAS/derivedFvPatchFields/turbulentMixingLengthDissipationRateInlet/turbulentMixingLengthDissipationRateInletFvPatchScalarField.C