OpenFOAM: noLift Class Reference
noLift Class Reference
#include <noLift.H>
Public Member Functions
TypeName ("none")
noLift (const dictionary &dict, const phasePair &pair)
virtual ~noLift ()
virtual tmp< volScalarField > Cl () const
virtual tmp< volVectorField > F () const
virtual tmp< surfaceScalarField > Ff () const
TypeName ("none")
noLift (const dictionary &dict, const phasePair &pair)
virtual ~noLift ()
virtual tmp< volScalarField > Cl () const
virtual tmp< volVectorField > F () const
virtual tmp< surfaceScalarField > Ff () const
Public Member Functions inherited from liftModel
TypeName ("liftModel")
declareRunTimeSelectionTable (autoPtr, liftModel, dictionary,(const dictionary &dict, const phasePair &pair),(dict, pair))
liftModel (const dictionary &dict, const phasePair &pair)
virtual ~liftModel ()=default
virtual tmp< volVectorField > Fi () const
TypeName ("liftModel")
declareRunTimeSelectionTable (autoPtr, liftModel, dictionary,(const dictionary &dict, const phasePair &pair),(dict, pair))
liftModel (const dictionary &dict, const phasePair &pair)
virtual ~liftModel ()=default
virtual tmp< volVectorField > Fi () const
Additional Inherited Members
Static Public Member Functions inherited from liftModel
static autoPtr< liftModel > New (const dictionary &dict, const phasePair &pair)
static autoPtr< liftModel > New (const dictionary &dict, const phasePair &pair)
Static Public Attributes inherited from liftModel
static const dimensionSet dimF
Protected Attributes inherited from liftModel
const phasePair & pair_
Detailed Description
Source files
noLift.H
noLift.C
Source files
noLift.H
noLift.C
Definition at line 50 of file noLift.H.
Constructor & Destructor Documentation
noLift() [1/2]
noLift (const dictionary & dict, const phasePair & pair)
Definition at line 39 of file noLift.C.
~noLift() [1/2]
~noLift () virtual
Definition at line 51 of file noLift.C.
noLift() [2/2]
noLift (const dictionary & dict, const phasePair & pair)
~noLift() [2/2]
virtual ~noLift () virtual
Member Function Documentation
TypeName() [1/2]
TypeName ("none")
Cl() [1/2]
Foam::tmp< Foam::volScalarField > Cl () const virtual
Implements liftModel.
Definition at line 57 of file noLift.C.
References Foam::dimless, mesh, and GeometricField< scalar, fvPatchField, volMesh >::New().
F() [1/2]
Foam::tmp< Foam::volVectorField > F () const virtual
Reimplemented from liftModel.
Definition at line 70 of file noLift.C.
References mesh, and GeometricField< vector, fvPatchField, volMesh >::New().
Ff() [1/2]
Foam::tmp< Foam::surfaceScalarField > Ff () const virtual
Reimplemented from liftModel.
Definition at line 83 of file noLift.C.
References Foam::dimArea, mesh, and GeometricField< scalar, fvsPatchField, surfaceMesh >::New().
TypeName() [2/2]
TypeName ("none")
Cl() [2/2]
virtual tmp< volScalarField > Cl () const virtual
Implements liftModel.
F() [2/2]
virtual tmp< volVectorField > F () const virtual
Reimplemented from liftModel.
Ff() [2/2]
virtual tmp< surfaceScalarField > Ff () const virtual
Reimplemented from liftModel.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/interfacialModels/liftModels/noLift/noLift.H
src/phaseSystemModels/twoPhaseEuler/twoPhaseSystem/interfacialModels/liftModels/noLift/noLift.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/interfacialModels/liftModels/noLift/noLift.C
src/phaseSystemModels/twoPhaseEuler/twoPhaseSystem/interfacialModels/liftModels/noLift/noLift.C