OpenFOAM: SurfaceFilmModel< CloudType > Class Template Reference
SurfaceFilmModel< CloudType > Class Template Reference abstract
Lagrangian particle models » Submodels » Kinematic » Surface film
Templated wall surface film model class.
#include <SurfaceFilmModel.H>
Public Member Functions
TypeName ("surfaceFilmModel")
declareRunTimeSelectionTable (autoPtr, SurfaceFilmModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
SurfaceFilmModel (CloudType &owner)
SurfaceFilmModel (const dictionary &dict, CloudType &owner, const word &type)
SurfaceFilmModel (const SurfaceFilmModel< CloudType > &sfm)
virtual autoPtr< SurfaceFilmModel< CloudType > > clone () const =0
virtual ~SurfaceFilmModel ()=default
const dimensionedVector & g () const noexcept
label nParcelsTransferred () const noexcept
label & nParcelsTransferred () noexcept
label nParcelsInjected () const noexcept
label & nParcelsInjected () noexcept
scalar totalMassTransferred () const noexcept
scalar & totalMassTransferred () noexcept
virtual bool transferParcel (parcelType &p, const polyPatch &pp, bool &keepParticle)=0
template<class TrackCloudType >
void inject (TrackCloudType &cloud)
virtual void info ()
template<class CloudTrackType >
void injectParticles (const label primaryPatchi, const labelUList &injectorCells, CloudTrackType &cloud)
template<class CloudTrackType >
void injectParticles (const UList< labelPair > &patchFaces, CloudTrackType &cloud)
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
virtual ~CloudSubModelBase ()=default
const CloudType & owner () const
virtual bool writeTime () const
virtual fileName localPath () const
CloudType & owner ()
virtual void write (Ostream &os) const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
subModelBase (const subModelBase &smb)
virtual ~subModelBase ()=default
const word & modelName () const
const dictionary & dict () const
const word & baseName () const
const word & modelType () const
const dictionary & coeffDict () const
const dictionary & properties () const
virtual bool defaultCoeffs (const bool printMsg) const
virtual bool active () const
virtual void cacheFields (const bool store)
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
bool getModelDict (const word &entryName, dictionary &dict) const
template<class Type >
bool getModelProperty (const word &entryName, Type &value) const
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Static Public Member Functions
static autoPtr< SurfaceFilmModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Protected Types
typedef CloudType::parcelType parcelType
typedef regionModels::areaSurfaceFilmModels::liquidFilmBase areaFilm
typedef regionModels::surfaceFilmModels::surfaceFilmRegionModel regionFilm
Protected Member Functions
virtual void cacheFilmFields (const label filmPatchi, const label primaryPatchi, const regionFilm &)
virtual void cacheFilmFields (const areaFilm &film)
template<class TrackCloudType >
void injectParticles (const label primaryPatchi, const labelUList &injectorCells, TrackCloudType &cloud)
template<class TrackCloudType >
void injectParticles (const UList< labelPair > &patchFaces, TrackCloudType &cloud)
virtual void setParcelProperties (parcelType &p, const label filmFacei) const
Protected Member Functions inherited from subModelBase
bool inLine () const
Protected Attributes
const dimensionedVector & g_
label ejectedParcelType_
scalar injectionOffset_
scalar minDiameter_
scalarField massParcelPatch_
scalarField diameterParcelPatch_
Field< vector > UFilmPatch_
scalarField rhoFilmPatch_
Field< scalarField > deltaFilmPatch_
label nParcelsTransferred_
label nParcelsInjected_
scalar totalMassTransferred_
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Protected Attributes inherited from subModelBase
const word modelName_
dictionary & properties_
const dictionary dict_
const word baseName_
const word modelType_
const dictionary coeffDict_
Additional Inherited Members
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Public Attributes inherited from subModelBase
bool log
Detailed Description
template<class CloudType>
class Foam::SurfaceFilmModel< CloudType >
Templated wall surface film model class.
Source files
SurfaceFilmModel.H
SurfaceFilmModel.C
SurfaceFilmModelNew.C
Definition at line 70 of file SurfaceFilmModel.H.
Member Typedef Documentation
parcelType
template<class CloudType > typedef CloudType::parcelType parcelType protected
Definition at line 79 of file SurfaceFilmModel.H.
areaFilm
template<class CloudType > typedef regionModels::areaSurfaceFilmModels::liquidFilmBase areaFilm protected
Definition at line 83 of file SurfaceFilmModel.H.
regionFilm
template<class CloudType > typedef regionModels::surfaceFilmModels::surfaceFilmRegionModel regionFilm protected
Definition at line 87 of file SurfaceFilmModel.H.
Constructor & Destructor Documentation
SurfaceFilmModel() [1/3]
template<class CloudType > SurfaceFilmModel (CloudType & owner)
Definition at line 32 of file SurfaceFilmModel.C.
SurfaceFilmModel() [2/3]
template<class CloudType > SurfaceFilmModel (const dictionary & dict, CloudType & owner, const word & type)
Definition at line 51 of file SurfaceFilmModel.C.
SurfaceFilmModel() [3/3]
template<class CloudType > SurfaceFilmModel (const SurfaceFilmModel< CloudType > & sfm)
Definition at line 84 of file SurfaceFilmModel.C.
~SurfaceFilmModel()
template<class CloudType > virtual ~SurfaceFilmModel () virtual default
Member Function Documentation
cacheFilmFields() [1/2]
template<class CloudType > void cacheFilmFields (const label filmPatchi, const label primaryPatchi, const regionFilm & filmModel) protected virtual
Reimplemented in ThermoSurfaceFilm< CloudType >, and KinematicSurfaceFilm< CloudType >.
Definition at line 323 of file SurfaceFilmModel.C.
References surfaceFilmRegionModel::cloudDiameterTrans(), surfaceFilmRegionModel::cloudMassTrans(), surfaceFilmRegionModel::delta(), surfaceFilmRegionModel::rho(), regionModel::toPrimary(), and surfaceFilmRegionModel::Us().
Referenced by KinematicSurfaceFilm< CloudType >::cacheFilmFields(), and KinematicSurfaceFilm< CloudType >::cacheFilmFields().
cacheFilmFields() [2/2]
template<class CloudType > void cacheFilmFields (const areaFilm & film) protected virtual
Reimplemented in ThermoSurfaceFilm< CloudType >, and KinematicSurfaceFilm< CloudType >.
Definition at line 350 of file SurfaceFilmModel.C.
References liquidFilmBase::cloudDiameterTrans(), liquidFilmBase::cloudMassTrans(), UPtrList< T >::first(), forAll, liquidFilmBase::h(), volSurfaceMapping::mapToSurface(), pbm, liquidFilmBase::region(), regionFaModel::regionMesh(), PtrList< T >::resize(), liquidFilmBase::rho(), UPtrList< T >::size(), liquidFilmBase::Uf(), and Foam::Zero.
injectParticles() [1/4]
template<class CloudType > template<class TrackCloudType > void injectParticles (const label primaryPatchi, const labelUList & injectorCells, TrackCloudType & cloud) protected
injectParticles() [2/4]
template<class CloudType > template<class TrackCloudType > void injectParticles (const UList< labelPair > & patchFaces, TrackCloudType & cloud) protected
setParcelProperties()
template<class CloudType > void setParcelProperties (parcelType & p, const label filmFacei) const protected virtual
Reimplemented in NoSurfaceFilm< CloudType >, KinematicSurfaceFilm< CloudType >, and ThermoSurfaceFilm< CloudType >.
Definition at line 402 of file SurfaceFilmModel.C.
References p, Foam::constant::mathematical::pi(), and Foam::pow3().
Referenced by KinematicSurfaceFilm< CloudType >::setParcelProperties().
TypeName()
template<class CloudType > TypeName ("surfaceFilmModel")
declareRunTimeSelectionTable()
template<class CloudType > declareRunTimeSelectionTable (autoPtr , SurfaceFilmModel< CloudType > , dictionary , (const dictionary &dict, CloudType &owner) , (dict, owner))
clone()
template<class CloudType > virtual autoPtr< SurfaceFilmModel< CloudType > > clone () const pure virtual
Implemented in KinematicSurfaceFilm< CloudType >, NoSurfaceFilm< CloudType >, and ThermoSurfaceFilm< CloudType >.
New()
template<class CloudType > Foam::autoPtr< Foam::SurfaceFilmModel< CloudType > > New (const dictionary & dict, CloudType & owner) static
Definition at line 28 of file SurfaceFilmModelNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, Foam::Info, and PtrList< T >::PtrList().
g()
template<class CloudType > const Foam::dimensionedVector & g () const inline noexcept
Definition at line 26 of file SurfaceFilmModelI.H.
nParcelsTransferred() [1/2]
template<class CloudType > Foam::label nParcelsTransferred () const inline noexcept
Definition at line 34 of file SurfaceFilmModelI.H.
nParcelsTransferred() [2/2]
template<class CloudType > Foam::label & nParcelsTransferred () inline noexcept
Definition at line 41 of file SurfaceFilmModelI.H.
nParcelsInjected() [1/2]
template<class CloudType > Foam::label nParcelsInjected () const inline noexcept
Definition at line 49 of file SurfaceFilmModelI.H.
nParcelsInjected() [2/2]
template<class CloudType > Foam::label & nParcelsInjected () inline noexcept
Definition at line 57 of file SurfaceFilmModelI.H.
totalMassTransferred() [1/2]
template<class CloudType > Foam::scalar totalMassTransferred () const inline noexcept
Definition at line 65 of file SurfaceFilmModelI.H.
totalMassTransferred() [2/2]
template<class CloudType > Foam::scalar & totalMassTransferred () inline noexcept
Definition at line 73 of file SurfaceFilmModelI.H.
transferParcel()
template<class CloudType > virtual bool transferParcel (parcelType & p, const polyPatch & pp, bool & keepParticle) pure virtual
Implemented in KinematicSurfaceFilm< CloudType >, NoSurfaceFilm< CloudType >, and ThermoSurfaceFilm< CloudType >.
inject()
template<class CloudType > template<class TrackCloudType > void inject (TrackCloudType & cloud)
Definition at line 239 of file SurfaceFilmModel.C.
References polyMesh::boundaryMesh(), forAll, mesh, pbm, and fvMesh::time().
info()
template<class CloudType > void info () virtual
Reimplemented from CloudSubModelBase< CloudType >.
Reimplemented in KinematicSurfaceFilm< CloudType >, and ThermoSurfaceFilm< CloudType >.
Definition at line 432 of file SurfaceFilmModel.C.
References Foam::endl(), CloudSubModelBase< CloudType >::info(), Log_, Foam::nl, and Foam::returnReduce().
Referenced by KinematicSurfaceFilm< CloudType >::info().
injectParticles() [3/4]
template<class CloudType > template<class CloudTrackType > void injectParticles (const label primaryPatchi, const labelUList & injectorCells, CloudTrackType & cloud)
Definition at line 109 of file SurfaceFilmModel.C.
References fvMesh::C(), forAll, Foam::max(), mesh, Foam::normalised(), Foam::pos(), and fvMesh::Sf().
injectParticles() [4/4]
template<class CloudType > template<class CloudTrackType > void injectParticles (const UList< labelPair > & patchFaces, CloudTrackType & cloud)
Definition at line 171 of file SurfaceFilmModel.C.
References polyMesh::boundaryMesh(), fvMesh::C(), UPtrList< T >::first(), forAll, Foam::max(), mesh, pbm, and fvMesh::Sf().
Member Data Documentation
g_
template<class CloudType > const dimensionedVector& g_ protected
Definition at line 93 of file SurfaceFilmModel.H.
ejectedParcelType_
template<class CloudType > label ejectedParcelType_ protected
Definition at line 98 of file SurfaceFilmModel.H.
injectionOffset_
template<class CloudType > scalar injectionOffset_ protected
Definition at line 101 of file SurfaceFilmModel.H.
minDiameter_
template<class CloudType > scalar minDiameter_ protected
Definition at line 104 of file SurfaceFilmModel.H.
massParcelPatch_
template<class CloudType > scalarField massParcelPatch_ protected
Definition at line 110 of file SurfaceFilmModel.H.
diameterParcelPatch_
template<class CloudType > scalarField diameterParcelPatch_ protected
Definition at line 113 of file SurfaceFilmModel.H.
UFilmPatch_
template<class CloudType > Field<vector> UFilmPatch_ protected
Definition at line 116 of file SurfaceFilmModel.H.
rhoFilmPatch_
template<class CloudType > scalarField rhoFilmPatch_ protected
Definition at line 119 of file SurfaceFilmModel.H.
deltaFilmPatch_
template<class CloudType > Field<scalarField> deltaFilmPatch_ protected
Definition at line 122 of file SurfaceFilmModel.H.
nParcelsTransferred_
template<class CloudType > label nParcelsTransferred_ protected
Definition at line 128 of file SurfaceFilmModel.H.
nParcelsInjected_
template<class CloudType > label nParcelsInjected_ protected
Definition at line 131 of file SurfaceFilmModel.H.
totalMassTransferred_
template<class CloudType > scalar totalMassTransferred_ protected
Definition at line 137 of file SurfaceFilmModel.H.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/clouds/Templates/KinematicCloud/KinematicCloud.H
src/lagrangian/intermediate/submodels/Kinematic/SurfaceFilmModel/SurfaceFilmModel/SurfaceFilmModel.H
src/lagrangian/intermediate/submodels/Kinematic/SurfaceFilmModel/SurfaceFilmModel/SurfaceFilmModel.C
src/lagrangian/intermediate/submodels/Kinematic/SurfaceFilmModel/SurfaceFilmModel/SurfaceFilmModelI.H
src/lagrangian/intermediate/submodels/Kinematic/SurfaceFilmModel/SurfaceFilmModel/SurfaceFilmModelNew.C