OpenFOAM: slidingInterface Class Reference
slidingInterface Class Reference
Sliding interface mesh modifier. Given two face zones, couple the master and slave side using a cutting procedure.
#include <slidingInterface.H>
Public Types
enum typeOfMatch { INTEGRAL , PARTIAL }
Public Member Functions
TypeName ("slidingInterface")
slidingInterface (const word &name, const label index, const polyTopoChanger &mme, const word &masterFaceZoneName, const word &slaveFaceZoneName, const word &cutPointZoneName, const word &cutFaceZoneName, const word &masterPatchName, const word &slavePatchName, const typeOfMatch tom, const bool coupleDecouple=false, const intersection::algorithm algo=intersection::VISIBLE)
slidingInterface (const word &name, const dictionary &dict, const label index, const polyTopoChanger &mme)
virtual ~slidingInterface ()=default
const faceZoneID & masterFaceZoneID () const
const faceZoneID & slaveFaceZoneID () const
bool attached () const
virtual bool changeTopology () const
virtual void setRefinement (polyTopoChange &) const
virtual void modifyMotionPoints (pointField &motionPoints) const
virtual void updateMesh (const mapPolyMesh &)
const pointField & pointProjection () const
void setTolerances (const dictionary &, bool report=false)
virtual void write (Ostream &) const
virtual void writeDict (Ostream &) const
Public Member Functions inherited from polyMeshModifier
TypeName ("meshModifier")
declareRunTimeSelectionTable (autoPtr, polyMeshModifier, dictionary,(const word &name, const dictionary &dict, const label index, const polyTopoChanger &mme),(name, dict, index, mme))
polyMeshModifier (const word &name, const label index, const polyTopoChanger &mme, const bool act)
virtual ~polyMeshModifier ()=default
const word & name () const
label index () const
const polyTopoChanger & topoChanger () const
Switch active () const
void enable () const
void disable () const
Static Public Attributes
static const Enum< typeOfMatch > typeOfMatchNames
Additional Inherited Members
Static Public Member Functions inherited from polyMeshModifier
static autoPtr< polyMeshModifier > New (const word &name, const dictionary &dict, const label index, const polyTopoChanger &mme)
Detailed Description
Sliding interface mesh modifier. Given two face zones, couple the master and slave side using a cutting procedure.
The coupled faces are collected into the "coupled" zone and can become either internal or placed into a master and slave coupled zone. The remaining faces (uncovered master or slave) are placed into the master and slave patch.
The definition of the sliding interface can be either integral or partial. Integral interface implies that the slave side completely covers the master (i.e. no faces are uncovered); partial interface implies that the uncovered part of master/slave face zone should become boundary faces.
Source files
slidingInterface.H
slidingInterface.C
coupleSlidingInterface.C
decoupleSlidingInterface.C
slidingInterfaceProjectPoints.C
slidingInterfaceAttachedAddressing.C
slidingInterfaceClearCouple.C
Definition at line 70 of file slidingInterface.H.
Member Enumeration Documentation
typeOfMatch
enum typeOfMatch
Enumerator
INTEGRAL
PARTIAL
Definition at line 79 of file slidingInterface.H.
Constructor & Destructor Documentation
slidingInterface() [1/2]
slidingInterface (const word & name, const label index, const polyTopoChanger & mme, const word & masterFaceZoneName, const word & slaveFaceZoneName, const word & cutPointZoneName, const word & cutFaceZoneName, const word & masterPatchName, const word & slavePatchName, const typeOfMatch tom, const bool coupleDecouple = false, const intersection::algorithm algo = intersection::VISIBLE)
Definition at line 111 of file slidingInterface.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
slidingInterface() [2/2]
slidingInterface (const word & name, const dictionary & dict, const label index, const polyTopoChanger & mme)
Definition at line 201 of file slidingInterface.C.
References dict, Foam::endl(), polyMeshModifier::name(), Foam::Pout, and slidingInterface::setTolerances().
~slidingInterface()
virtual ~slidingInterface () virtual default
Member Function Documentation
TypeName()
TypeName ("slidingInterface")
masterFaceZoneID()
const Foam::faceZoneID & masterFaceZoneID () const
Definition at line 310 of file slidingInterface.C.
slaveFaceZoneID()
const Foam::faceZoneID & slaveFaceZoneID () const
Definition at line 316 of file slidingInterface.C.
attached()
bool attached () const inline
Definition at line 352 of file slidingInterface.H.
changeTopology()
bool changeTopology () const virtual
Implements polyMeshModifier.
Definition at line 322 of file slidingInterface.C.
References Foam::endl(), mesh, Foam::name(), and Foam::Pout.
setRefinement()
void setRefinement (polyTopoChange & ref) const virtual
Implements polyMeshModifier.
Definition at line 363 of file slidingInterface.C.
References ref().
modifyMotionPoints()
void modifyMotionPoints (pointField & motionPoints) const virtual
Implements polyMeshModifier.
Definition at line 396 of file slidingInterface.C.
References Foam::abort(), b, PrimitivePatch< FaceList, PointField >::edges(), UPtrList< T >::end(), Foam::endl(), polyMesh::faceZones(), Foam::FatalError, FatalErrorInFunction, UPtrList< T >::first(), PrimitivePatch< FaceList, PointField >::localPoints(), Foam::mag(), mesh, Foam::name(), PrimitivePatch< FaceList, PointField >::pointNormals(), polyMesh::pointZones(), Foam::Pout, UList< T >::size(), Foam::sqr(), PrimitivePatch< FaceList, PointField >::whichEdge(), and PrimitivePatch< FaceList, PointField >::whichPoint().
updateMesh()
void updateMesh (const mapPolyMesh & m) virtual
Implements polyMeshModifier.
Definition at line 627 of file slidingInterface.C.
References polyMesh::boundaryMesh(), Foam::endl(), polyMesh::faceZones(), mesh, Foam::name(), polyMesh::pointZones(), Foam::Pout, and dynamicFvMesh::update().
pointProjection()
const Foam::pointField & pointProjection () const
Definition at line 659 of file slidingInterface.C.
setTolerances()
void setTolerances (const dictionary & dict, bool report = false)
Definition at line 670 of file slidingInterface.C.
References dict, Foam::endl(), dictionary::getOrDefault(), Foam::Info, and Foam::nl.
Referenced by slidingInterface::slidingInterface().
write()
void write (Ostream & os) const virtual
Implements polyMeshModifier.
Definition at line 728 of file slidingInterface.C.
References Foam::endl(), Foam::name(), Foam::nl, os(), and Foam::type().
writeDict()
void writeDict (Ostream & os) const virtual
Implements polyMeshModifier.
Definition at line 752 of file slidingInterface.C.
References intersection::algorithmNames_, Ostream::beginBlock(), Ostream::endBlock(), Foam::name(), Foam::nl, os(), Foam::type(), WRITE_NON_DEFAULT, and Ostream::writeEntry().
Member Data Documentation
typeOfMatchNames
const Foam::Enum< Foam::slidingInterface::typeOfMatch > typeOfMatchNames static
Definition at line 86 of file slidingInterface.H.
The documentation for this class was generated from the following files:
src/dynamicMesh/slidingInterface/slidingInterface.H
src/dynamicMesh/slidingInterface/coupleSlidingInterface.C
src/dynamicMesh/slidingInterface/decoupleSlidingInterface.C
src/dynamicMesh/slidingInterface/slidingInterface.C
src/dynamicMesh/slidingInterface/slidingInterfaceAttachedAddressing.C
src/dynamicMesh/slidingInterface/slidingInterfaceClearCouple.C
src/dynamicMesh/slidingInterface/slidingInterfaceProjectPoints.C