OpenFOAM: identity Class Reference
identity Class Reference
An identity coordinateRotation.
#include <identityRotation.H>
Public Member Functions
TypeNameNoDebug ("none")
identity ()=default
identity (const identity &)=default
identity & operator= (const identity &)=default
identity (const dictionary &unused)
autoPtr< coordinateRotation > clone () const
virtual ~identity ()=default
virtual void clear ()
virtual tensor R () const
virtual void write (Ostream &os) const
virtual void writeEntry (const word &keyword, Ostream &os) const
Public Member Functions inherited from coordinateRotation
TypeNameNoDebug ("coordinateRotation")
declareRunTimeSelectionTable (autoPtr, coordinateRotation, dictionary,(const dictionary &dict),(dict))
virtual ~coordinateRotation ()=default
Additional Inherited Members
Static Public Member Functions inherited from coordinateRotation
static autoPtr< coordinateRotation > New (const word &modelType, const dictionary &dict)
static autoPtr< coordinateRotation > New (const dictionary &dict)
Static Protected Member Functions inherited from coordinateRotation
static vector findOrthogonal (const vector &axis)
Detailed Description
An identity coordinateRotation.
rotation
{
    type    none;
}
Dictionary entries
Property Description Reqd Default
type Type name: none yes
Source files
identityRotation.H
identityRotation.C
Definition at line 71 of file identityRotation.H.
Constructor & Destructor Documentation
identity() [1/3]
identity () default
identity() [2/3]
identity (const identity &) default
identity() [3/3]
identity (const dictionary & unused) explicit
Definition at line 46 of file identityRotation.C.
~identity()
virtual ~identity () virtual default
Member Function Documentation
TypeNameNoDebug()
TypeNameNoDebug ("none")
operator=()
identity & operator= (const identity &) default
clone()
autoPtr< coordinateRotation > clone () const inline virtual
Implements coordinateRotation.
Definition at line 99 of file identityRotation.H.
clear()
void clear () virtual
Implements coordinateRotation.
Definition at line 52 of file identityRotation.C.
R()
Foam::tensor R () const virtual
Implements coordinateRotation.
Definition at line 56 of file identityRotation.C.
References SphericalTensor< scalar >::I.
write()
void write (Ostream & os) const virtual
Implements coordinateRotation.
Definition at line 62 of file identityRotation.C.
References os().
writeEntry()
void writeEntry (const word & keyword, Ostream & os) const virtual
Implements coordinateRotation.
Definition at line 68 of file identityRotation.C.
References os(), and Foam::type().
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/coordinate/rotation/identityRotation.H
src/OpenFOAM/primitives/coordinate/rotation/identityRotation.C