OpenFOAM: fromFile Class Reference
fromFile Class Reference
Reads control points from constant/controlPoints.
#include <fromFile.H>
Public Member Functions
TypeName ("fromFile")
fromFile (NURBS3DVolume &box)
virtual ~fromFile ()=default
Public Member Functions inherited from controlPointsDefinition
TypeName ("controlPointsDefinition")
declareRunTimeSelectionTable (autoPtr, controlPointsDefinition, dictionary,(NURBS3DVolume &box),(box))
controlPointsDefinition (NURBS3DVolume &box)
virtual ~controlPointsDefinition ()=default
Protected Member Functions
virtual void computeControlPoints ()
Protected Member Functions inherited from controlPointsDefinition
void transformControlPoints (const vector &geometryMin, const vector &geometryMax)
Additional Inherited Members
Static Public Member Functions inherited from controlPointsDefinition
static autoPtr< controlPointsDefinition > New (NURBS3DVolume &box)
Protected Attributes inherited from controlPointsDefinition
NURBS3DVolume & box_
vectorField & cps_
Detailed Description
Reads control points from constant/controlPoints.
Source files
fromFile.H
fromFile.C
Definition at line 48 of file fromFile.H.
Constructor & Destructor Documentation
fromFile()
fromFile (NURBS3DVolume & box)
Definition at line 79 of file fromFile.C.
References fromFile::computeControlPoints().
~fromFile()
virtual ~fromFile () virtual default
Member Function Documentation
computeControlPoints()
void computeControlPoints () protected virtual
Implements controlPointsDefinition.
Definition at line 44 of file fromFile.C.
References NURBS3DVolume::basisU(), NURBS3DVolume::basisV(), NURBS3DVolume::basisW(), controlPointsDefinition::box_, controlPointsDefinition::cps_, dict, NURBS3DVolume::dict(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::Info, mesh, NURBS3DVolume::mesh(), IOobjectOption::MUST_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, and UList< T >::size().
Referenced by fromFile::fromFile().
TypeName()
TypeName ("fromFile")
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/parameterization/NURBS/NURBS3DVolume/controlPointsDefinition/fromFile/fromFile.H
src/optimisation/adjointOptimisation/adjoint/parameterization/NURBS/NURBS3DVolume/controlPointsDefinition/fromFile/fromFile.C