OpenFOAM: fileOperation Class Reference
fileOperation Class Reference abstract
An encapsulation of filesystem-related operations.
#include <fileOperation.H>
Public Types
enum pathType : int {
NOTFOUND = 0 , ABSOLUTE , OBJECT , WRITEOBJECT ,
PROCUNCOLLATED , PROCBASEOBJECT = PROCUNCOLLATED + 1 , PROCOBJECT = PROCBASEOBJECT + 1 , PARENTOBJECT ,
FINDINSTANCE , PROCUNCOLLATEDINSTANCE , PROCBASEINSTANCE , PROCINSTANCE
}
typedef Tuple2< fileName, Tuple2< pathType, int > > dirIndex
typedef List< dirIndex > dirIndexList
typedef IntRange< int > procRangeType
Public Member Functions
TypeName ("fileOperation")
fileOperation (const label comm, const labelUList &ioRanks=labelUList::null(), const bool distributedRoots=false)
fileOperation (const Tuple2< label, labelList > &commAndIORanks, const bool distributedRoots=false)
declareRunTimeSelectionTable (autoPtr, fileOperation, word,(bool verbose),(verbose))
declareRunTimeSelectionTable (autoPtr, fileOperation, comm,(const Tuple2< label, labelList > &commAndIORanks, const bool distributedRoots, bool verbose),(commAndIORanks, distributedRoots, verbose))
virtual ~fileOperation ()=default
label comm () const noexcept
label comm (label communicator) const noexcept
bool distributed () const noexcept
bool distributed (bool on) const noexcept
const labelList & ioRanks () const noexcept
InfoProxy< fileOperation > info () const noexcept
virtual bool good () const
virtual void storeComm () const =0
virtual bool mkDir (const fileName &, mode_t=0777) const =0
virtual bool chMod (const fileName &, const mode_t) const =0
virtual mode_t mode (const fileName &, const bool followLink=true) const =0
virtual fileName::Type type (const fileName &, const bool followLink=true) const =0
virtual bool exists (const fileName &, const bool checkGzip=true, const bool followLink=true) const =0
virtual bool isDir (const fileName &, const bool followLink=true) const =0
virtual bool isFile (const fileName &, const bool checkGzip=true, const bool followLink=true) const =0
virtual off_t fileSize (const fileName &, const bool followLink=true) const =0
virtual time_t lastModified (const fileName &, const bool followLink=true) const =0
virtual double highResLastModified (const fileName &, const bool followLink=true) const =0
virtual fileNameList readDir (const fileName &, const fileName::Type=fileName::FILE, const bool filtergz=true, const bool followLink=true) const =0
virtual bool cp (const fileName &src, const fileName &dst, const bool followLink=true) const =0
virtual bool ln (const fileName &src, const fileName &dst) const =0
virtual bool mv (const fileName &src, const fileName &dst, const bool followLink=false) const =0
virtual bool mvBak (const fileName &, const std::string &ext="bak") const =0
virtual bool rm (const fileName &) const =0
virtual bool rmDir (const fileName &dir, const bool silent=false, const bool emptyOnly=false) const =0
virtual bool broadcastCopy (const label comm, const bool writeOnProc, const fileName &src, const fileName &dst) const
virtual fileName objectPath (const IOobject &io, const word &typeName) const
virtual fileName filePath (const bool checkGlobal, const IOobject &, const word &typeName, const bool search=true) const =0
virtual fileName dirPath (const bool checkGlobal, const IOobject &io, const bool search=true) const =0
virtual fileNameList readObjects (const objectRegistry &db, const fileName &instance, const fileName &local, word &newInstance) const
virtual bool readHeader (IOobject &, const fileName &, const word &typeName) const =0
virtual autoPtr< ISstream > readStream (regIOobject &, const fileName &, const word &typeName, const bool readOnProc=true) const =0
virtual bool read (regIOobject &, const bool masterOnly, const IOstreamOption::streamFormat format, const word &typeName) const =0
virtual bool writeObject (const regIOobject &io, IOstreamOption streamOpt=IOstreamOption(), const bool writeOnProc=true) const
virtual fileName filePath (const fileName &, const bool checkGzip=true, const bool followLink=true) const
virtual autoPtr< ISstream > NewIFstream (const fileName &) const =0
virtual autoPtr< OSstream > NewOFstream (const fileName &pathname, IOstreamOption streamOpt=IOstreamOption(), const bool writeOnProc=true) const =0
virtual autoPtr< OSstream > NewOFstream (IOstreamOption::atomicType atomic, const fileName &pathname, IOstreamOption streamOpt=IOstreamOption(), const bool writeOnProc=true) const =0
virtual label addWatch (const fileName &) const
virtual bool removeWatch (const label) const
virtual label findWatch (const labelList &watchIndices, const fileName &) const
virtual void addWatches (regIOobject &, const fileNameList &) const
virtual fileName getFile (const label) const
virtual void updateStates (const bool masterOnly, const bool syncPar) const
virtual fileMonitor::fileState getState (const label) const
virtual void setUnmodified (const label) const
virtual word processorsDir (const IOobject &io) const
virtual word processorsDir (const fileName &) const
label nProcs () const noexcept
label nProcs (const label numProcs) noexcept
virtual label nProcs (const fileName &dir, const fileName &local="") const
virtual instantList findTimes (const fileName &, const word &) const
virtual IOobject findInstance (const IOobject &io, const scalar startValue, const word &stopInstance) const
virtual void setTime (const Time &) const
virtual void flush () const
virtual void sync ()
fileName processorsCasePath (const IOobject &io, const word &procDir) const
fileName processorsPath (const IOobject &io, const word &instance, const word &procDir) const
fileName processorsPath (const fileName &, const word &procDir) const
label setNProcs (label numProcs)
Static Public Member Functions
static refPtr< fileOperation > null ()
static autoPtr< fileOperation > New (const word &handlerType, bool verbose=false)
static autoPtr< fileOperation > New (const word &handlerType, const Tuple2< label, labelList > &commAndIORanks, const bool distributedRoots, bool verbose=false)
static autoPtr< fileOperation > New (const fileOperation &origHandler, const boolUList &useProc, bool verbose=false)
static autoPtr< fileOperation > New (const fileOperation &origHandler, const bitSet &useProc, bool verbose=false)
static autoPtr< fileOperation > NewUncollated ()
static const fileOperation & fileHandler ()
static refPtr< fileOperation > fileHandler (std::nullptr_t)
static refPtr< fileOperation > fileHandler (refPtr< fileOperation > &newHandler)
static refPtr< fileOperation > fileHandler (refPtr< fileOperation > &&newHandler)
static refPtr< fileOperation > fileHandler (autoPtr< fileOperation > &&newHandler)
static int cacheLevel () noexcept
static int cacheLevel (int level) noexcept
static instantList sortTimes (const fileNameList &dirEntries, const word &constantName="constant")
static bool uniformFile (const fileNameList &names)
static bool uniformFile (const label comm, const fileName &name)
static label splitProcessorPath (const fileName &objectPath, fileName &path, fileName &procDir, fileName &local, procRangeType &group, label &nProcs)
static label detectProcessorPath (const fileName &objPath)
static labelRange subRanks (const labelUList &mainIOranks)
static labelList getGlobalHostIORanks ()
static labelList getGlobalIORanks ()
Static Public Attributes
static const Enum< pathType > pathTypeNames_
static word processorsBaseDir = "processors"
static word defaultFileHandler
static refPtr< fileOperation > fileHandlerPtr_
Protected Member Functions
fileMonitor & monitor () const
refPtr< dirIndexList > lookupAndCacheProcessorsPath (const fileName &objectPath, const bool syncPar) const
virtual refPtr< dirIndexList > lookupProcessorsPath (const fileName &objectPath) const
bool exists (IOobject &io) const
bool isIOrank (const label proci) const
void printRanks () const
Static Protected Member Functions
static void mergeTimes (const instantList &extraTimes, const word &constantName, instantList &times)
static bool isFileOrDir (const bool isFile, const fileName &)
static label getManagedComm (const label communicator)
Protected Attributes
label comm_
label nProcs_
bool distributed_
const labelList ioRanks_
HashTable< dirIndexList > procsDirs_
std::unique_ptr< fileMonitor > monitorPtr_
Static Protected Attributes
static int cacheLevel_
Detailed Description
An encapsulation of filesystem-related operations.
Several of the file handlers can be configured to use specific ranks for IO operations. These can either be defined from the command-line -ioRanks option, or via the FOAM_ENV environment variable. In either case, the list of IO ranks shall always include the value 0 (master rank). The ranks may be specified as a plain list, or as an OpenFOAM list. The special value host can be used to specify selection based on hostname.
For example,
    FOAM_IORANKS='0 4 8'   decomposePar -fileHandler hostCollated
    FOAM_IORANKS='0,4,8'   decomposePar -fileHandler hostCollated
    FOAM_IORANKS='(0 4 8)' decomposePar -fileHandler hostCollated
will generate
    processors12_0-3/   : containing data for processors 0 to 3
    processors12_4-7/   : containing data for processors 4 to 7
    processors12_8-11/  : containing data for processors 8 to 11
The value host can be used to specify a single IO rank for each host. For example,
    decomposePar -fileHandler collated -ioRanks host
    decomposePar -fileHandler hostCollated
Environment
FOAM_ENV : list of io-ranks as plain space or comma separated list or as an OpenFOAM formatted list. Eg, '(0 4 8)'
Definition at line 100 of file fileOperation.H.
Member Typedef Documentation
dirIndex
typedef Tuple2<fileName, Tuple2<pathType, int> > dirIndex
Definition at line 132 of file fileOperation.H.
dirIndexList
typedef List<dirIndex> dirIndexList
Definition at line 133 of file fileOperation.H.
procRangeType
typedef IntRange<int> procRangeType
Definition at line 137 of file fileOperation.H.
Member Enumeration Documentation
pathType
enum pathType : int
Enumerator
NOTFOUND
Not found.
ABSOLUTE
instance is absolute directory
OBJECT
io.objectPath() exists
WRITEOBJECT
write path exists
PROCUNCOLLATED
objectPath exists in 'processorN'
PROCBASEOBJECT
objectPath exists in 'processorsNN'
PROCOBJECT
objectPath exists in 'processorsNN_first-last'
PARENTOBJECT
parent of object path
FINDINSTANCE
file found in time directory
PROCUNCOLLATEDINSTANCE
as PROCUNCOLLATED but with instance
PROCBASEINSTANCE
as PROCBASEOBJECT but with instance
PROCINSTANCE
as PROCOBJECT but with instance
Definition at line 107 of file fileOperation.H.
Constructor & Destructor Documentation
fileOperation() [1/2]
fileOperation (const label comm, const labelUList & ioRanks = labelUList::null(), const bool distributedRoots = false) explicit
Definition at line 747 of file fileOperation.C.
fileOperation() [2/2]
fileOperation (const Tuple2< label, labelList > & commAndIORanks, const bool distributedRoots = false) explicit
Definition at line 734 of file fileOperation.C.
~fileOperation()
virtual ~fileOperation () virtual default
Member Function Documentation
monitor()
Foam::fileMonitor & monitor () const protected
Definition at line 315 of file fileOperation.C.
References IOobject::fileModificationChecking, IOobject::inotify, and IOobject::inotifyMaster.
mergeTimes()
void mergeTimes (const instantList & extraTimes, const word & constantName, instantList & times) static protected
Definition at line 332 of file fileOperation.C.
References UList< T >::end(), forAll, Foam::name(), List< T >::setSize(), PtrList< T >::setSize(), UPtrList< T >::size(), UList< T >::size(), and List< T >::transfer().
isFileOrDir()
bool isFileOrDir (const bool isFile, const fileName & f) static protected
Definition at line 406 of file fileOperation.C.
References f(), Foam::isDir(), and Foam::isFile().
Referenced by uncollatedFileOperation::filePathInfo().
lookupAndCacheProcessorsPath()
Foam::refPtr< Foam::fileOperation::dirIndexList > lookupAndCacheProcessorsPath (const fileName & objectPath, const bool syncPar) const protected
sortProcessorDirs(procDirs);
Definition at line 413 of file fileOperation.C.
References PtrList< T >::append(), Pstream::broadcast(), DebugInfo, fileName::DIRECTORY, UPtrList< T >::empty(), Foam::endl(), IOobject::fileModificationChecking, UPtrList< T >::first(), IOobject::inotifyMaster, local, UPstream::master(), Foam::max(), Foam::name(), refPtr< T >::New(), fileOperation::nProcs(), UPstream::parRun(), path(), Foam::Pout, Foam::readDir(), Foam::reduce(), rp(), UPtrList< T >::size(), IOobject::timeStampMaster, and UPstream::worldComm.
Referenced by uncollatedFileOperation::filePathInfo(), and uncollatedFileOperation::lookupProcessorsPath().
lookupProcessorsPath()
Foam::refPtr< Foam::fileOperation::dirIndexList > lookupProcessorsPath (const fileName & objectPath) const protected virtual
Reimplemented in uncollatedFileOperation.
Definition at line 676 of file fileOperation.C.
exists() [1/2]
bool exists (IOobject & io) const protected
Definition at line 683 of file fileOperation.C.
References UPtrList< T >::empty(), io(), Foam::isDir(), Foam::isFile(), IOobject::name(), word::null, IOobject::objectPath(), and IOobject::typeHeaderOk().
isIOrank()
bool isIOrank (const label proci) const protected
Definition at line 239 of file fileOperationRanks.C.
References UPstream::master(), and UPstream::parRun().
Referenced by collatedFileOperation::appendObject().
printRanks()
void printRanks () const protected
Definition at line 252 of file fileOperationRanks.C.
References DetailInfo, forAll, Pstream::gatherList(), Foam::hostName(), UPstream::master(), UPstream::msgType(), UPstream::myProcNo(), Foam::nl, UPstream::nProcs(), PtrList< T >::push_back(), UPtrList< T >::size(), and UPstream::worldComm.
getManagedComm()
static label getManagedComm (const label communicator) inline static protected
Definition at line 227 of file fileOperation.H.
References UPstream::commGlobal(), UPstream::commSelf(), and UPstream::commWorld().
TypeName()
TypeName ("fileOperation")
null()
Foam::refPtr< Foam::fileOperation > null () static
Definition at line 34 of file fileOperationNew.C.
declareRunTimeSelectionTable() [1/2]
declareRunTimeSelectionTable (autoPtr , fileOperation , word , (bool verbose) , (verbose))
declareRunTimeSelectionTable() [2/2]
declareRunTimeSelectionTable (autoPtr , fileOperation , comm , (const Tuple2< label, labelList > &commAndIORanks, const bool distributedRoots, bool verbose) , (commAndIORanks, distributedRoots, verbose))
New() [1/4]
Foam::autoPtr< Foam::fileOperation > New (const word & handlerType, bool verbose = false) static
Definition at line 144 of file fileOperationNew.C.
References Foam::abort(), DebugInFunction, fileOperation::defaultFileHandler, UPtrList< T >::empty(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, FatalErrorInLookup, fileOperation::New(), and Foam::nl.
Referenced by fileOperation::fileHandler(), fileOperation::New(), fileOperation::New(), argList::parse(), and Time::readDict().
New() [2/4]
Foam::autoPtr< Foam::fileOperation > New (const word & handlerType, const Tuple2< label, labelList > & commAndIORanks, const bool distributedRoots, bool verbose = false) static
Definition at line 183 of file fileOperationNew.C.
References Foam::abort(), DebugInFunction, fileOperation::defaultFileHandler, UPtrList< T >::empty(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, FatalErrorInLookup, fileOperation::New(), and Foam::nl.
New() [3/4]
Foam::autoPtr< Foam::fileOperation > New (const fileOperation & origHandler, const boolUList & useProc, bool verbose = false) static
Parameters
origHandler The original file handler
useProc The selected sub-ranks (in comm-world)
Definition at line 389 of file fileOperationNew.C.
References Foam::getSelectedProcs().
New() [4/4]
Foam::autoPtr< Foam::fileOperation > New (const fileOperation & origHandler, const bitSet & useProc, bool verbose = false) static
Parameters
origHandler The original file handler
useProc The selected sub-ranks (in comm-world). Monotonic order!
Definition at line 403 of file fileOperationNew.C.
References Foam::getSelectedProcs().
NewUncollated()
Foam::autoPtr< Foam::fileOperation > NewUncollated () static
Definition at line 132 of file fileOperationNew.C.
Referenced by faMeshReconstructor::writeMesh().
fileHandler() [1/5]
const Foam::fileOperation & fileHandler () static
Definition at line 46 of file fileOperationNew.C.
References UPtrList< T >::empty(), fileOperation::fileHandlerPtr_, Foam::getEnv(), and fileOperation::New().
Referenced by faMeshDistributor::distributeAreaFields(), faMeshDistributor::distributeEdgeFields(), Foam::fileHandler(), fileOperation::fileHandler(), argList::parse(), Time::readDict(), faMeshReconstructor::writeMesh(), faMeshTools::writeProcAddressing(), fvMeshTools::writeProcAddressing(), and argList::~argList().
fileHandler() [2/5]
Foam::refPtr< Foam::fileOperation > fileHandler (std::nullptr_t) static
Definition at line 65 of file fileOperationNew.C.
fileHandler() [3/5]
Foam::refPtr< Foam::fileOperation > fileHandler (refPtr< fileOperation > & newHandler) static
Definition at line 72 of file fileOperationNew.C.
References fileOperation::fileHandlerPtr_, UPtrList< T >::get(), and UPtrList< T >::swap().
fileHandler() [4/5]
Foam::refPtr< Foam::fileOperation > fileHandler (refPtr< fileOperation > && newHandler) static
Definition at line 126 of file fileOperationNew.C.
References fileOperation::fileHandler().
fileHandler() [5/5]
Foam::refPtr< Foam::fileOperation > fileHandler (autoPtr< fileOperation > && newHandler) static
Definition at line 105 of file fileOperationNew.C.
References fileOperation::fileHandlerPtr_, UPtrList< T >::get(), PtrList< T >::release(), and UPtrList< T >::swap().
cacheLevel() [1/2]
static int cacheLevel () inline static noexcept
Definition at line 436 of file fileOperation.H.
References fileOperation::cacheLevel_.
Referenced by masterUncollatedFileOperation::dirPath(), masterUncollatedFileOperation::filePath(), masterUncollatedFileOperation::findInstance(), masterUncollatedFileOperation::findTimes(), masterUncollatedFileOperation::read(), and masterUncollatedFileOperation::readObjects().
cacheLevel() [2/2]
static int cacheLevel (int level) inline static noexcept
Definition at line 442 of file fileOperation.H.
References fileOperation::cacheLevel_.
sortTimes()
Foam::instantList sortTimes (const fileNameList & dirEntries, const word & constantName = "constant") static
Definition at line 218 of file fileOperation.C.
References UList< T >::begin(), UPtrList< T >::empty(), UList< T >::end(), List< T >::resize(), and UPtrList< T >::size().
uniformFile() [1/2]
bool uniformFile (const fileNameList & names) static
Definition at line 277 of file fileOperation.C.
References UList< T >::empty(), and UList< T >::size().
Referenced by masterUncollatedFileOperation::NewIFstream(), masterUncollatedFileOperation::readHeader(), and masterUncollatedFileOperation::readStream().
uniformFile() [2/2]
bool uniformFile (const label comm, const fileName & name) static
Definition at line 298 of file fileOperation.C.
References Pstream::broadcast(), Foam::name(), UPstream::parRun(), and Foam::returnReduceAnd().
comm() [1/2]
label comm () const inline noexcept
Definition at line 469 of file fileOperation.H.
References fileOperation::comm_.
Referenced by fileOperation::broadcastCopy(), and masterUncollatedFileOperation::scatterList().
comm() [2/2]
label comm (label communicator) const inline noexcept
Definition at line 476 of file fileOperation.H.
References fileOperation::comm_.
distributed() [1/2]
bool distributed () const inline noexcept
Definition at line 484 of file fileOperation.H.
References fileOperation::distributed_.
distributed() [2/2]
bool distributed (bool on) const inline noexcept
Definition at line 491 of file fileOperation.H.
References fileOperation::distributed_.
ioRanks()
const labelList & ioRanks () const inline noexcept
Definition at line 500 of file fileOperation.H.
References fileOperation::ioRanks_.
info()
InfoProxy< fileOperation > info () const inline noexcept
Definition at line 504 of file fileOperation.H.
good()
virtual bool good () const inline virtual
Reimplemented in dummyFileOperation.
Definition at line 511 of file fileOperation.H.
storeComm()
virtual void storeComm () const pure virtual
Implemented in collatedFileOperation, hostCollatedFileOperation, dummyFileOperation, masterUncollatedFileOperation, hostUncollatedFileOperation, and uncollatedFileOperation.
mkDir()
virtual bool mkDir (const fileName & , mode_t = 0777) const pure virtual
Implemented in dummyFileOperation, masterUncollatedFileOperation, and uncollatedFileOperation.
chMod()
virtual bool chMod (const fileName & , const mode_t) const pure virtual
Implemented in dummyFileOperation, masterUncollatedFileOperation, and uncollatedFileOperation.
mode()
virtual mode_t mode (const fileName & , const bool followLink = true) const pure virtual
Implemented in dummyFileOperation, masterUncollatedFileOperation, and uncollatedFileOperation.
type()
virtual fileName::Type type (const fileName & , const bool followLink = true) const pure virtual
Implemented in dummyFileOperation, masterUncollatedFileOperation, and uncollatedFileOperation.
exists() [2/2]
virtual bool exists (const fileName & , const bool checkGzip = true, const bool followLink = true) const pure virtual
Implemented in dummyFileOperation, masterUncollatedFileOperation, and uncollatedFileOperation.
isDir()
virtual bool isDir (const fileName & , const bool followLink = true) const pure virtual
Implemented in dummyFileOperation, masterUncollatedFileOperation, and uncollatedFileOperation.
isFile()
virtual bool isFile (const fileName & , const bool checkGzip = true, const bool followLink = true) const pure virtual
Implemented in dummyFileOperation, masterUncollatedFileOperation, and uncollatedFileOperation.
fileSize()
virtual off_t fileSize (const fileName & , const bool followLink = true) const pure virtual
Implemented in dummyFileOperation, masterUncollatedFileOperation, and uncollatedFileOperation.
lastModified()
virtual time_t lastModified (const fileName & , const bool followLink = true) const pure virtual
Implemented in dummyFileOperation, masterUncollatedFileOperation, and uncollatedFileOperation.
highResLastModified()
virtual double highResLastModified (const fileName & , const bool followLink = true) const pure virtual
Implemented in dummyFileOperation, masterUncollatedFileOperation, and uncollatedFileOperation.
readDir()
virtual fileNameList readDir (const fileName & , const fileName::Type = fileName::FILE, const bool filtergz = true, const bool followLink = true) const pure virtual
Implemented in dummyFileOperation, masterUncollatedFileOperation, and uncollatedFileOperation.
cp()
virtual bool cp (const fileName & src, const fileName & dst, const bool followLink = true) const pure virtual
Implemented in dummyFileOperation, masterUncollatedFileOperation, and uncollatedFileOperation.
ln()
virtual bool ln (const fileName & src, const fileName & dst) const pure virtual
Implemented in dummyFileOperation, masterUncollatedFileOperation, and uncollatedFileOperation.
mv()
virtual bool mv (const fileName & src, const fileName & dst, const bool followLink = false) const pure virtual
Implemented in dummyFileOperation, masterUncollatedFileOperation, and uncollatedFileOperation.
mvBak()
virtual bool mvBak (const fileName & , const std::string & ext = "bak") const pure virtual
Implemented in dummyFileOperation, masterUncollatedFileOperation, and uncollatedFileOperation.
rm()
virtual bool rm (const fileName &) const pure virtual
Implemented in dummyFileOperation, masterUncollatedFileOperation, and uncollatedFileOperation.
rmDir()
virtual bool rmDir (const fileName & dir, const bool silent = false, const bool emptyOnly = false) const pure virtual
Implemented in dummyFileOperation, masterUncollatedFileOperation, and uncollatedFileOperation.
broadcastCopy()
bool broadcastCopy (const label comm, const bool writeOnProc, const fileName & src, const fileName & dst) const virtual
Definition at line 347 of file fileOperationBroadcast.C.
References Foam::broadcastFile_recursive(), fileOperation::comm(), fileName::DIRECTORY, UPtrList< T >::empty(), and fileName::FILE.
objectPath()
Foam::fileName objectPath (const IOobject & io, const word & typeName) const virtual
Reimplemented in collatedFileOperation.
Definition at line 763 of file fileOperation.C.
References io(), and IOobject::objectPath().
Referenced by uncollatedFileOperation::filePathInfo().
filePath() [1/2]
virtual fileName filePath (const bool checkGlobal, const IOobject & , const word & typeName, const bool search = true) const pure virtual
Implemented in dummyFileOperation, masterUncollatedFileOperation, and uncollatedFileOperation.
dirPath()
virtual fileName dirPath (const bool checkGlobal, const IOobject & io, const bool search = true) const pure virtual
Implemented in dummyFileOperation, masterUncollatedFileOperation, and uncollatedFileOperation.
readObjects()
Foam::fileNameList readObjects (const objectRegistry & db, const fileName & instance, const fileName & local, word & newInstance) const virtual
Reimplemented in dummyFileOperation, masterUncollatedFileOperation, and uncollatedFileOperation.
Definition at line 1193 of file fileOperation.C.
References PtrList< T >::clear(), objectRegistry::dbDir(), UPtrList< T >::empty(), Foam::endl(), fileName::FILE, Foam::isDir(), local, IOobject::objectPath(), IOobject::path(), path(), Foam::Pout, and Foam::readDir().
Referenced by masterUncollatedFileOperation::readObjects(), and uncollatedFileOperation::readObjects().
readHeader()
virtual bool readHeader (IOobject & , const fileName & , const word & typeName) const pure virtual
Implemented in dummyFileOperation, masterUncollatedFileOperation, and uncollatedFileOperation.
readStream()
virtual autoPtr< ISstream > readStream (regIOobject & , const fileName & , const word & typeName, const bool readOnProc = true) const pure virtual
Implemented in dummyFileOperation, masterUncollatedFileOperation, and uncollatedFileOperation.
read()
virtual bool read (regIOobject & , const bool masterOnly, const IOstreamOption::streamFormat format, const word & typeName) const pure virtual
Implemented in dummyFileOperation, masterUncollatedFileOperation, and uncollatedFileOperation.
writeObject()
bool writeObject (const regIOobject & io, IOstreamOption streamOpt = IOstreamOption(), const bool writeOnProc = true) const virtual
Reimplemented in collatedFileOperation, and masterUncollatedFileOperation.
Definition at line 773 of file fileOperation.C.
References IOstream::good(), io(), Foam::mkDir(), IOobject::objectPath(), os(), IOobject::writeEndDivider(), and IOobject::writeHeader().
filePath() [2/2]
Foam::fileName filePath (const fileName & fName, const bool checkGzip = true, const bool followLink = true) const virtual
Definition at line 818 of file fileOperation.C.
References Foam::endl(), Foam::exists(), UPtrList< T >::first(), local, path(), Foam::Pout, and WarningInFunction.
NewIFstream()
virtual autoPtr< ISstream > NewIFstream (const fileName &) const pure virtual
Implemented in dummyFileOperation, masterUncollatedFileOperation, and uncollatedFileOperation.
NewOFstream() [1/2]
virtual autoPtr< OSstream > NewOFstream (const fileName & pathname, IOstreamOption streamOpt = IOstreamOption(), const bool writeOnProc = true) const pure virtual
Implemented in dummyFileOperation, masterUncollatedFileOperation, and uncollatedFileOperation.
NewOFstream() [2/2]
virtual autoPtr< OSstream > NewOFstream (IOstreamOption::atomicType atomic, const fileName & pathname, IOstreamOption streamOpt = IOstreamOption(), const bool writeOnProc = true) const pure virtual
Implemented in masterUncollatedFileOperation, dummyFileOperation, and uncollatedFileOperation.
addWatch()
Foam::label addWatch (const fileName & fName) const virtual
Reimplemented in masterUncollatedFileOperation.
Definition at line 880 of file fileOperation.C.
removeWatch()
bool removeWatch (const label watchIndex) const virtual
Reimplemented in masterUncollatedFileOperation.
Definition at line 886 of file fileOperation.C.
findWatch()
Foam::label findWatch (const labelList & watchIndices, const fileName & fName) const virtual
Reimplemented in masterUncollatedFileOperation.
Definition at line 892 of file fileOperation.C.
References forAll.
addWatches()
void addWatches (regIOobject & rio, const fileNameList & files) const virtual
Reimplemented in masterUncollatedFileOperation.
Definition at line 909 of file fileOperation.C.
References PtrList< T >::append(), and f().
getFile()
Foam::fileName getFile (const label watchIndex) const virtual
Reimplemented in masterUncollatedFileOperation.
Definition at line 946 of file fileOperation.C.
updateStates()
void updateStates (const bool masterOnly, const bool syncPar) const virtual
Reimplemented in masterUncollatedFileOperation.
Definition at line 952 of file fileOperation.C.
References UPstream::parRun().
getState()
Foam::fileMonitor::fileState getState (const label watchFd) const virtual
Reimplemented in masterUncollatedFileOperation.
Definition at line 962 of file fileOperation.C.
setUnmodified()
void setUnmodified (const label watchFd) const virtual
Reimplemented in masterUncollatedFileOperation.
Definition at line 971 of file fileOperation.C.
processorsDir() [1/2]
virtual word processorsDir (const IOobject & io) const inline virtual
Reimplemented in collatedFileOperation.
Definition at line 805 of file fileOperation.H.
References fileOperation::processorsBaseDir.
processorsDir() [2/2]
virtual word processorsDir (const fileName &) const inline virtual
Reimplemented in collatedFileOperation.
Definition at line 812 of file fileOperation.H.
References fileOperation::processorsBaseDir.
nProcs() [1/3]
label nProcs () const inline noexcept
Definition at line 819 of file fileOperation.H.
References fileOperation::nProcs_.
Referenced by fileOperation::lookupAndCacheProcessorsPath(), and fileOperation::setNProcs().
nProcs() [2/3]
label nProcs (const label numProcs) inline noexcept
Definition at line 825 of file fileOperation.H.
References fileOperation::nProcs_.
nProcs() [3/3]
Foam::label nProcs (const fileName & dir, const fileName & local = "") const virtual
Definition at line 1233 of file fileOperation.C.
References Pstream::broadcast(), fileName::DIRECTORY, Foam::endl(), Foam::isDir(), UPstream::master(), Foam::max(), Foam::nl, Foam::readDir(), rp(), and WarningInFunction.
findTimes()
Foam::instantList findTimes (const fileName & directory, const word & constantName) const virtual
Reimplemented in masterUncollatedFileOperation.
Definition at line 977 of file fileOperation.C.
References fileName::DIRECTORY, UPtrList< T >::empty(), Foam::endl(), UPtrList< T >::first(), Foam::flatOutput(), Foam::Pout, and Foam::readDir().
Referenced by masterUncollatedFileOperation::findTimes(), and masterUncollatedFileOperation::readObjects().
findInstance()
Foam::IOobject findInstance (const IOobject & io, const scalar startValue, const word & stopInstance) const virtual
Reimplemented in masterUncollatedFileOperation.
Definition at line 1031 of file fileOperation.C.
References TimePaths::constant(), DebugInFunction, UPtrList< T >::empty(), Foam::endl(), Foam::exists(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, IOobject::instance(), io(), IOobject::local(), IOobject::name(), UPtrList< T >::size(), and TimePaths::times().
setTime()
virtual void setTime (const Time &) const inline virtual
Reimplemented in masterUncollatedFileOperation.
Definition at line 855 of file fileOperation.H.
Referenced by masterUncollatedFileOperation::setTime().
flush()
void flush () const virtual
Reimplemented in collatedFileOperation, and masterUncollatedFileOperation.
Definition at line 1282 of file fileOperation.C.
References Foam::endl(), and Foam::Pout.
Referenced by masterUncollatedFileOperation::flush().
sync()
void sync () virtual
Reimplemented in masterUncollatedFileOperation.
Definition at line 1293 of file fileOperation.C.
References Pstream::broadcasts(), Foam::endl(), Foam::Pout, and UPstream::worldComm.
Referenced by masterUncollatedFileOperation::sync().
processorsCasePath()
Foam::fileName processorsCasePath (const IOobject & io, const word & procDir) const
Definition at line 1310 of file fileOperation.C.
References io(), IOobject::rootPath(), and IOobject::time().
processorsPath() [1/2]
Foam::fileName processorsPath (const IOobject & io, const word & instance, const word & procDir) const
Definition at line 1320 of file fileOperation.C.
References IOobject::db(), io(), and IOobject::local().
Referenced by uncollatedFileOperation::filePathInfo().
processorsPath() [2/2]
Foam::fileName processorsPath (const fileName & dir, const word & procDir) const
Definition at line 1335 of file fileOperation.C.
References Foam::endl(), fileName::name(), fileName::path(), string::starts_with(), and WarningInFunction.
splitProcessorPath()
Foam::label splitProcessorPath (const fileName & objectPath, fileName & path, fileName & procDir, fileName & local, procRangeType & group, label & nProcs) static
Definition at line 1361 of file fileOperation.C.
References PtrList< T >::clear(), local, path(), Foam::pos(), and Foam::read().
detectProcessorPath()
Foam::label detectProcessorPath (const fileName & objPath) static
Definition at line 1522 of file fileOperation.C.
References local, and path().
subRanks()
Foam::labelRange subRanks (const labelUList & mainIOranks) static
Definition at line 66 of file fileOperationRanks.C.
References UPtrList< T >::empty(), Foam::endl(), forAllReverse, UPstream::myProcNo(), UPstream::nProcs(), Foam::Pout, UPtrList< T >::size(), and UPstream::worldComm.
Referenced by Foam::getCommPattern().
getGlobalHostIORanks()
Foam::labelList getGlobalHostIORanks () static
Definition at line 102 of file fileOperationRanks.C.
References Pstream::broadcast(), Foam::hostName(), UPstream::master(), SHA1Digest::max_size(), UPstream::mpiGather(), UPstream::nProcs(), PtrList< T >::push_back(), PtrList< T >::resize(), UPtrList< T >::size(), PtrList< T >::transfer(), and UPstream::worldComm.
Referenced by Foam::getCommPattern(), and fileOperation::getGlobalIORanks().
getGlobalIORanks()
Foam::labelList getGlobalIORanks () static
Definition at line 155 of file fileOperationRanks.C.
References UPtrList< T >::begin(), string::contains(), UPtrList< T >::empty(), UPtrList< T >::end(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::flatOutput(), UPtrList< T >::front(), Foam::getEnv(), fileOperation::getGlobalHostIORanks(), Foam::nl, and UPtrList< T >::size().
Referenced by Foam::getCommPattern().
setNProcs()
label setNProcs (label numProcs) inline
Definition at line 923 of file fileOperation.H.
References fileOperation::nProcs().
Member Data Documentation
pathTypeNames_
const Foam::Enum< Foam::fileOperation::pathType > pathTypeNames_ static
Definition at line 129 of file fileOperation.H.
Referenced by masterUncollatedFileOperation::dirPath(), and masterUncollatedFileOperation::filePath().
cacheLevel_
int cacheLevel_ static protected
Definition at line 153 of file fileOperation.H.
Referenced by fileOperation::cacheLevel(), and fileOperation::cacheLevel().
comm_
label comm_ mutable protected
Definition at line 159 of file fileOperation.H.
Referenced by fileOperation::comm(), fileOperation::comm(), and collatedFileOperation::printBanner().
nProcs_
label nProcs_ protected
Definition at line 165 of file fileOperation.H.
Referenced by fileOperation::nProcs(), and fileOperation::nProcs().
distributed_
bool distributed_ mutable protected
Definition at line 168 of file fileOperation.H.
Referenced by fileOperation::distributed(), and fileOperation::distributed().
ioRanks_
const labelList ioRanks_ protected
Definition at line 172 of file fileOperation.H.
Referenced by fileOperation::ioRanks().
procsDirs_
HashTable<dirIndexList> procsDirs_ mutable protected
Definition at line 175 of file fileOperation.H.
monitorPtr_
std::unique_ptr<fileMonitor> monitorPtr_ mutable protected
Definition at line 178 of file fileOperation.H.
processorsBaseDir
Foam::word processorsBaseDir = "processors" static
Definition at line 262 of file fileOperation.H.
Referenced by fileOperation::processorsDir(), and fileOperation::processorsDir().
defaultFileHandler
word defaultFileHandler static
Definition at line 265 of file fileOperation.H.
Referenced by argList::argList(), fileOperation::New(), fileOperation::New(), and argList::parse().
fileHandlerPtr_
Foam::refPtr< Foam::fileOperation > fileHandlerPtr_ static
Definition at line 275 of file fileOperation.H.
Referenced by fileOperation::fileHandler(), fileOperation::fileHandler(), fileOperation::fileHandler(), and argList::parse().
The documentation for this class was generated from the following files:
src/OpenFOAM/global/fileOperations/fileOperation/fileOperation.H
src/OpenFOAM/global/fileOperations/fileOperation/fileOperation.C
src/OpenFOAM/global/fileOperations/fileOperation/fileOperationBroadcast.C
src/OpenFOAM/global/fileOperations/fileOperation/fileOperationNew.C
src/OpenFOAM/global/fileOperations/fileOperation/fileOperationRanks.C