OpenFOAM: AC3DsurfaceFormatCore Class Reference
AC3DsurfaceFormatCore Class Reference
Internal class used by the AC3DsurfaceFormat.
#include <AC3DsurfaceFormatCore.H>
Static Protected Member Functions
template<class Type >
static Type parse (const string &str)
static bool readCmd (IFstream &is, string &cmd, string &args)
static bool cueTo (IFstream &, const string &cmd, string &args)
static string cueToOrDie (IFstream &, const string &cmd, const string &errorMsg=string::null)
static void writeHeader (Ostream &os, const UList< surfZone > &zones)
Detailed Description
Internal class used by the AC3DsurfaceFormat.
Source files
AC3DsurfaceFormatCore.H
AC3DsurfaceFormatCore.C
Definition at line 51 of file AC3DsurfaceFormatCore.H.
Member Function Documentation
parse()
template<class Type > static Type parse (const string & str) inline static protected
Definition at line 59 of file AC3DsurfaceFormatCore.H.
readCmd()
bool readCmd (IFstream & is, string & cmd, string & args) static protected
Definition at line 44 of file AC3DsurfaceFormatCore.C.
References args.
cueTo()
bool cueTo (IFstream & is, const string & cmd, string & args) static protected
Definition at line 71 of file AC3DsurfaceFormatCore.C.
References args.
cueToOrDie()
Foam::string cueToOrDie (IFstream & is, const string & cmd, const string & errorMsg = string::null) static protected
Definition at line 97 of file AC3DsurfaceFormatCore.C.
References args, Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
writeHeader()
void writeHeader (Ostream & os, const UList< surfZone > & zones) static protected
Definition at line 117 of file AC3DsurfaceFormatCore.C.
References colourMap, Foam::endl(), forAll, Foam::nl, os(), and UPtrList< T >::size().
The documentation for this class was generated from the following files:
src/surfMesh/surfaceFormats/ac3d/AC3DsurfaceFormatCore.H
src/surfMesh/surfaceFormats/ac3d/AC3DsurfaceFormatCore.C