OpenFOAM: exprDriver Class Reference
exprDriver Class Reference abstract
Base driver for parsing (field) values.
#include <exprDriver.H>
Public Types
enum searchControls {
NO_SEARCH = 0 , SEARCH_REGISTRY = 1 , SEARCH_FILES = 2 , CACHE_READ_FIELDS = 4 ,
DEFAULT_SEARCH = (SEARCH_REGISTRY)
}
typedef HashTable< const regIOobject * > contextObjectTableType
Public Member Functions
TypeName ("exprDriver")
exprDriver (const exprDriver &)=delete
void operator= (const exprDriver &)=delete
exprDriver (enum searchControls search=searchControls::DEFAULT_SEARCH, const dictionary &dict=dictionary::null)
exprDriver (const exprDriver &rhs, const dictionary &dict)
exprDriver (const dictionary &dict)
virtual ~exprDriver ()=default
virtual label size () const
virtual label pointSize () const
const TimeState * timeState () const noexcept
virtual scalar timeValue () const
virtual scalar deltaT () const
const dictionary & dict () const noexcept
const exprResult & result () const noexcept
exprResult & result () noexcept
void clearResult ()
template<class Type >
tmp< Field< Type > > getResult (bool wantPointData=false)
const word & getResultType () const noexcept
void resetDb (const objectRegistry *obrPtr=nullptr)
void resetDb (const objectRegistry &db)
scalar argValue () const noexcept
int stashedTokenId () const noexcept
int resetStashedTokenId (int tokenId=0) const noexcept
void setDebugging (bool scannerDebug, bool parserDebug)
void setDebugging (const exprDriver &rhs)
bool setCaching (bool on) noexcept
void setSearchBehaviour (enum searchControls search, const bool caching=false)
void setSearchBehaviour (const exprDriver &rhs)
bool debugScanner () const noexcept
bool debugParser () const noexcept
bool prevIterIsOldTime () const
virtual void clearVariables ()
void setArgument (const scalar val) noexcept
virtual bool hasVariable (const word &name) const
virtual const exprResult & variable (const word &name) const
void addVariables (const expressions::exprString &expr, bool clear=true)
void addVariables (const UList< expressions::exprString > &list, bool clear=true)
template<class T >
void addUniformVariable (const word &name, const T &val)
bool hasContextObjects () const
const regIOobject * cfindContextIOobject (const word &name) const
template<class ObjType >
const ObjType * cfindContextObject (const word &name) const
void addContextObject (const word &name, const regIOobject *)
void addContextObject (const regIOobject *)
void removeContextObject (const word &name)
void removeContextObject (const regIOobject *)
const contextObjectTableType & contextObjects () const noexcept
contextObjectTableType & contextObjects () noexcept
template<class Type >
bool isFunction (const word &name) const
template<class Type >
Type getFunctionValue (const word &name, const scalar x) const
template<class Type >
void fillFunctionValues (Field< Type > &result, const word &name, const scalarField &input) const
template<class T >
bool isLocalVariable (const word &name, bool wantPointData=false, label expectedSize=-1) const
template<class Type >
tmp< Field< Type > > getLocalVariable (const word &name, label expectSize, const bool mandatory=true) const
virtual unsigned parse (const std::string &expr, size_t pos=0, size_t len=std::string::npos)=0
template<class Type >
tmp< Field< Type > > evaluate (const expressions::exprString &expr, bool wantPointData=false)
template<class Type >
Type evaluateUniform (const expressions::exprString &expr, bool wantPointData=false)
void evaluateVariable (const word &varName, const expressions::exprString &expr)
virtual void evaluateVariableRemote (string remote, const word &varName, const expressions::exprString &expr)
template<class Type >
tmp< Field< Type > > newField (const Type &val=pTraits< Type >::zero) const
template<class Type >
tmp< Field< Type > > newPointField (const Type &val=pTraits< Type >::zero) const
expressions::exprString readExpression (const word &name)
virtual bool readDict (const dictionary &dict)
label setVariableStrings (const dictionary &dict, bool mandatory=false)
Ostream & writeVariableStrings (Ostream &os, const word &keyword="") const
template<class Type >
void addUniformVariable (const word &name, const Type &val)
template<class Type >
Foam::tmp< Foam::Field< Type > > evaluate (const expressions::exprString &expr, bool wantPointData)
template<class Type >
Foam::tmp< Foam::Field< Type > > getResult (bool wantPointData)
template<class Type >
const Foam::Function1< Type > * getFunction1Ptr (const word &name, const HashTable< refPtr< Function1< Type > > > &tbl, wordList *listFailure)
template<class Type >
Foam::tmp< Foam::Field< Type > > newField (const Type &val) const
template<class Type >
Foam::tmp< Foam::Field< Type > > newPointField (const Type &val) const
Static Public Member Functions
static expressions::exprString readExpression (const word &name, const dictionary &dict)
static List< expressions::exprString > readVariableStrings (const dictionary &dict, const word &name="variables", bool mandatory=false)
Protected Member Functions
bool searchRegistry () const noexcept
bool searchFiles () const noexcept
bool cacheReadFields () const noexcept
void resetTimeReference (const TimeState *ts)
void resetTimeReference (const TimeState &ts)
void writeFunctions (Ostream &os) const
virtual exprResult & variable (const word &name)
void fill_random (scalarField &field, label seed=0, const bool gaussian=false) const
virtual bool update ()
virtual void updateSpecialVariables (bool force=false)
virtual exprResult getRemoteResult (const exprDriver &other) const
Static Protected Member Functions
template<class Type >
static Type weightedAverage (const scalarField &weights, const Field< Type > &fld)
template<class Type >
static Type weightedSum (const scalarField &weights, const Field< Type > &fld)
static point getPositionOfMinimum (const scalarField &vals, const pointField &locs)
static point getPositionOfMaximum (const scalarField &vals, const pointField &locs)
Protected Attributes
const dictionary & dict_
exprResult result_
List< expressions::exprString > variableStrings_
HashTable< exprResult > variables_
HashTable< refPtr< Function1< scalar > > > scalarFuncs_
HashTable< refPtr< Function1< vector > > > vectorFuncs_
contextObjectTableType contextObjects_
scalar arg1Value_
const TimeState * timeStatePtr_
const objectRegistry * obrPtr_
int stashedTokenId_
bool debugScanner_
bool debugParser_
bool allowShadowing_
bool prevIterIsOldTime_
searchControls searchCtrl_
Detailed Description
Base driver for parsing (field) values.
Largely based on code and ideas from swak4foam
Properties
Property Description Required Default
variables List of variables for expressions no ()
functions<scalar> Dictionary of scalar Function1 no {}
functions<vector> Dictionary of vector Function1 no {}
allowShadowing Allow variables to shadow field names no false
Debug Properties
Property Description Required Default
debug.driver Debug level (int) for base driver no
debug.scanner Add debug for scanner no false
debug.parser Add debug for parser no false
The functions<scalar> and functions<vector> entries are dictionaries of Foam::Function1 definitions that can either be used to establish a time-varying quantity, to remap a field of scalar values, or both.
Source files
exprDriver.H
exprDriverI.H
exprDriverContextI.H
exprDriver.C
exprDriverFields.C
exprDriverFunctions.C
exprDriverIO.C
exprDriverTemplates.C
Definition at line 136 of file exprDriver.H.
Member Typedef Documentation
contextObjectTableType
typedef HashTable<const regIOobject*> contextObjectTableType
Definition at line 154 of file exprDriver.H.
Member Enumeration Documentation
searchControls
enum searchControls
Enumerator
NO_SEARCH
SEARCH_REGISTRY
Search registry before disk.
SEARCH_FILES
Search disk (eg, standalone app)
CACHE_READ_FIELDS
Cache fields read from disk.
DEFAULT_SEARCH
Definition at line 143 of file exprDriver.H.
Constructor & Destructor Documentation
exprDriver() [1/4]
exprDriver (const exprDriver &) delete
exprDriver() [2/4]
exprDriver (enum searchControls search = searchControls::DEFAULT_SEARCH, const dictionary & dict = dictionary::null) explicit
Definition at line 166 of file exprDriver.C.
exprDriver() [3/4]
exprDriver (const exprDriver & rhs, const dictionary & dict)
Definition at line 193 of file exprDriver.C.
References exprDriver::dict_, exprDriver::scalarFuncs_, Foam::shallowCloneFunctions(), and exprDriver::vectorFuncs_.
exprDriver() [4/4]
exprDriver (const dictionary & dict) explicit
Definition at line 230 of file exprDriver.C.
References exprDriver::dict(), and exprDriver::readDict().
~exprDriver()
virtual ~exprDriver () virtual default
Member Function Documentation
searchRegistry()
bool searchRegistry () const inline protected noexcept
Definition at line 137 of file exprDriverI.H.
searchFiles()
bool searchFiles () const inline protected noexcept
Definition at line 143 of file exprDriverI.H.
cacheReadFields()
bool cacheReadFields () const inline protected noexcept
Definition at line 149 of file exprDriverI.H.
resetTimeReference() [1/2]
void resetTimeReference (const TimeState * ts) protected
Definition at line 123 of file exprDriver.C.
Referenced by parseDriver::parseDriver(), parseDriver::parseDriver(), parseDriver::parseDriver(), parseDriver::parseDriver(), and parseDriver::parseDriver().
resetTimeReference() [2/2]
void resetTimeReference (const TimeState & ts) protected
Definition at line 129 of file exprDriver.C.
writeFunctions()
void writeFunctions (Ostream & os) const protected
Definition at line 214 of file exprDriverFunctions.C.
References os().
variable() [1/2]
Foam::expressions::exprResult & variable (const word & name) inline protected virtual
Reimplemented in fvExprDriver.
Definition at line 56 of file exprDriverI.H.
References Foam::name().
Referenced by parseDriver::getField().
fill_random()
void fill_random (scalarField & field, label seed = 0, const bool gaussian = false) const protected
Definition at line 28 of file exprDriverFields.C.
References Foam::FieldOps::assign(), field(), and exprDriver::timeState().
Referenced by parseDriver::field_rand().
weightedAverage()
template<class Type > static Type weightedAverage (const scalarField & weights, const Field< Type > & fld) static protected
Referenced by parseDriver::areaAverage(), parseDriver::areaAverage(), and parseDriver::volAverage().
weightedSum()
template<class Type > static Type weightedSum (const scalarField & weights, const Field< Type > & fld) static protected
Referenced by parseDriver::areaSum(), parseDriver::areaSum(), and parseDriver::volSum().
getPositionOfMinimum()
Foam::point getPositionOfMinimum (const scalarField & vals, const pointField & locs) static protected
Definition at line 62 of file exprDriverFields.C.
References Foam::FieldOps::findMinData().
getPositionOfMaximum()
Foam::point getPositionOfMaximum (const scalarField & vals, const pointField & locs) static protected
Definition at line 72 of file exprDriverFields.C.
References Foam::FieldOps::findMaxData().
update()
bool update () protected virtual
Definition at line 314 of file exprDriver.C.
updateSpecialVariables()
void updateSpecialVariables (bool force = false) protected virtual
Reimplemented in fvExprDriver.
Definition at line 320 of file exprDriver.C.
getRemoteResult()
Foam::expressions::exprResult getRemoteResult (const exprDriver & other) const protected virtual
Definition at line 361 of file exprDriver.C.
References exprDriver::result().
TypeName()
TypeName ("exprDriver")
operator=()
void operator= (const exprDriver &) delete
size()
virtual label size () const inline virtual
Reimplemented in parseDriver, parseDriver, parseDriver, and fvExprDriver.
Definition at line 359 of file exprDriver.H.
pointSize()
virtual label pointSize () const inline virtual
Reimplemented in parseDriver, parseDriver, parseDriver, and fvExprDriver.
Definition at line 365 of file exprDriver.H.
timeState()
const Foam::TimeState * timeState () const noexcept
Definition at line 247 of file exprDriver.C.
Referenced by exprDriver::fill_random().
timeValue()
Foam::scalar timeValue () const virtual
Definition at line 261 of file exprDriver.C.
deltaT()
Foam::scalar deltaT () const virtual
Definition at line 275 of file exprDriver.C.
dict()
const dictionary & dict () const inline noexcept
Definition at line 381 of file exprDriver.H.
References exprDriver::dict_.
Referenced by exprDriver::exprDriver(), fvExprDriver::fvExprDriver(), fvExprDriver::New(), and exprDriver::readExpression().
result() [1/2]
const exprResult & result () const inline noexcept
Definition at line 387 of file exprDriver.H.
References exprDriver::result_.
Referenced by exprDriver::getRemoteResult(), fvExprDriver::isGlobalVariable(), parseDriver::setInternalFieldResult(), and parseDriver::setResult().
result() [2/2]
exprResult & result () inline noexcept
Definition at line 393 of file exprDriver.H.
References exprDriver::result_.
clearResult()
void clearResult ()
Definition at line 308 of file exprDriver.C.
References PtrList< T >::clear().
getResult() [1/2]
template<class Type > tmp< Field< Type > > getResult (bool wantPointData = false)
getResultType()
const word & getResultType () const inline noexcept
Definition at line 407 of file exprDriver.H.
References exprDriver::result_, and exprResult::valueType().
resetDb() [1/2]
void resetDb (const objectRegistry * obrPtr = nullptr)
Definition at line 135 of file exprDriver.C.
References forAllIters.
Referenced by parseDriver::parseDriver(), parseDriver::parseDriver(), parseDriver::parseDriver(), parseDriver::parseDriver(), and parseDriver::parseDriver().
resetDb() [2/2]
void resetDb (const objectRegistry & db)
Definition at line 158 of file exprDriver.C.
argValue()
Foam::scalar argValue () const inline noexcept
Definition at line 30 of file exprDriverI.H.
References exprDriver::arg1Value_.
stashedTokenId()
int stashedTokenId () const inline noexcept
Definition at line 108 of file exprDriverI.H.
resetStashedTokenId()
int resetStashedTokenId (int tokenId = 0) const inline noexcept
Definition at line 114 of file exprDriverI.H.
setDebugging() [1/2]
void setDebugging (bool scannerDebug, bool parserDebug)
Definition at line 485 of file exprDriver.C.
setDebugging() [2/2]
void setDebugging (const exprDriver & rhs)
Definition at line 496 of file exprDriver.C.
References exprDriver::debugParser_, and exprDriver::debugScanner_.
setCaching()
bool setCaching (bool on) noexcept
Definition at line 506 of file exprDriver.C.
setSearchBehaviour() [1/2]
void setSearchBehaviour (enum searchControls search, const bool caching = false)
Definition at line 534 of file exprDriver.C.
References Foam::Info, Foam::nl, and Foam::search().
setSearchBehaviour() [2/2]
void setSearchBehaviour (const exprDriver & rhs)
Definition at line 562 of file exprDriver.C.
References exprDriver::searchCtrl_.
debugScanner()
bool debugScanner () const inline noexcept
Definition at line 125 of file exprDriverI.H.
debugParser()
bool debugParser () const inline noexcept
Definition at line 131 of file exprDriverI.H.
prevIterIsOldTime()
bool prevIterIsOldTime () const inline
Definition at line 466 of file exprDriver.H.
References exprDriver::prevIterIsOldTime_.
clearVariables()
void clearVariables () virtual
Reimplemented in fvExprDriver.
Definition at line 324 of file exprDriver.C.
References PtrList< T >::clear().
setArgument()
void setArgument (const scalar val) inline noexcept
Definition at line 24 of file exprDriverI.H.
hasVariable()
bool hasVariable (const word & name) const inline virtual
Reimplemented in fvExprDriver.
Definition at line 36 of file exprDriverI.H.
References Foam::name().
Referenced by parseDriver::getField().
variable() [2/2]
const Foam::expressions::exprResult & variable (const word & name) const inline virtual
Reimplemented in fvExprDriver.
Definition at line 46 of file exprDriverI.H.
References Foam::name().
addVariables() [1/2]
void addVariables (const expressions::exprString & expr, bool clear = true)
Parameters
clear Remove previously defined variables
Definition at line 371 of file exprDriver.C.
References clear(), UPtrList< T >::empty(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::FatalIOError, FatalIOErrorInFunction, Foam::stringOps::inplaceTrim(), Foam::nl, PtrList< T >::resize(), Foam::stringOps::trim(), and word::validate().
addVariables() [2/2]
void addVariables (const UList< expressions::exprString > & list, bool clear = true)
Parameters
clear Remove previously defined variables
Definition at line 467 of file exprDriver.C.
References clear().
addUniformVariable() [1/2]
template<class T > void addUniformVariable (const word & name, const T & val) inline
hasContextObjects()
bool hasContextObjects () const inline
Definition at line 23 of file exprDriverContextI.H.
References exprDriver::contextObjects_, and HashTable< T, Key, Hash >::empty().
cfindContextIOobject()
const Foam::regIOobject * cfindContextIOobject (const word & name) const inline
Definition at line 30 of file exprDriverContextI.H.
References Foam::name().
Referenced by fvExprDriver::foundField(), parseDriver::getField(), parseDriver::patchInternalField(), parseDriver::patchNeighbourField(), and parseDriver::patchNormalField().
cfindContextObject()
template<class ObjType > const ObjType * cfindContextObject (const word & name) const
Definition at line 106 of file exprDriverContextI.H.
References Foam::name().
addContextObject() [1/2]
void addContextObject (const word & name, const regIOobject * objptr) inline
Definition at line 40 of file exprDriverContextI.H.
References Foam::name(), and PtrList< T >::set().
addContextObject() [2/2]
void addContextObject (const regIOobject * objptr) inline
Definition at line 57 of file exprDriverContextI.H.
removeContextObject() [1/2]
void removeContextObject (const word & name) inline
Definition at line 69 of file exprDriverContextI.H.
References Foam::name().
removeContextObject() [2/2]
void removeContextObject (const regIOobject * objptr) inline
Definition at line 78 of file exprDriverContextI.H.
contextObjects() [1/2]
const Foam::HashTable< const Foam::regIOobject * > & contextObjects () const inline noexcept
Definition at line 91 of file exprDriverContextI.H.
contextObjects() [2/2]
Foam::HashTable< const Foam::regIOobject * > & contextObjects () inline noexcept
Definition at line 98 of file exprDriverContextI.H.
isFunction()
template<class Type > bool isFunction (const word & name) const
Definition at line 128 of file exprDriverTemplates.C.
References doLocalCode.
getFunctionValue()
template<class Type > Type getFunctionValue (const word & name, const scalar x) const
Definition at line 153 of file exprDriverTemplates.C.
References doLocalCode, UPtrList< T >::empty(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::flatOutput(), Foam::name(), Foam::nl, and x.
fillFunctionValues()
template<class Type > void fillFunctionValues (Field< Type > & result, const word & name, const scalarField & input) const
Definition at line 206 of file exprDriverTemplates.C.
References doLocalCode, UPtrList< T >::empty(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::flatOutput(), Foam::input(), Foam::min(), Foam::name(), Foam::nl, UPtrList< T >::size(), and Foam::Zero.
isLocalVariable()
template<class Type > bool isLocalVariable (const word & name, bool wantPointData = false, label expectedSize = -1) const
Definition at line 277 of file exprDriverTemplates.C.
References DebugInfo, Foam::endl(), Foam::Info, Foam::name(), Foam::returnReduceAnd(), and UPtrList< T >::size().
getLocalVariable()
template<class Type > tmp< Field< Type > > getLocalVariable (const word & name, label expectSize, const bool mandatory = true) const
parse()
virtual unsigned parse (const std::string & expr, size_t pos = 0, size_t len = std::string::npos) pure virtual
Implemented in parseDriver, parseDriver, and parseDriver.
evaluate() [1/2]
template<class Type > tmp< Field< Type > > evaluate (const expressions::exprString & expr, bool wantPointData = false) inline
evaluateUniform()
template<class Type > Type evaluateUniform (const expressions::exprString & expr, bool wantPointData = false) inline
Definition at line 93 of file exprDriverI.H.
evaluateVariable()
void evaluateVariable (const word & varName, const expressions::exprString & expr)
Definition at line 331 of file exprDriver.C.
References DebugInfo, and Foam::endl().
evaluateVariableRemote()
void evaluateVariableRemote (string remote, const word & varName, const expressions::exprString & expr) virtual
Reimplemented in fvExprDriver.
Definition at line 349 of file exprDriver.C.
References NotImplemented.
newField() [1/2]
template<class Type > tmp< Field< Type > > newField (const Type & val = pTraits< Type >::zero) const
newPointField() [1/2]
template<class Type > tmp< Field< Type > > newPointField (const Type & val = pTraits< Type >::zero) const
readExpression() [1/2]
Foam::expressions::exprString readExpression (const word & name, const dictionary & dict) static
Definition at line 67 of file exprDriverIO.C.
References exprDriver::dict(), and Foam::name().
readVariableStrings()
Foam::List< Foam::expressions::exprString > readVariableStrings (const dictionary & dict, const word & name = "variables", bool mandatory = false) static
Definition at line 88 of file exprDriverIO.C.
References dict, and Foam::exprTools::getList().
readExpression() [2/2]
Foam::expressions::exprString readExpression (const word & name)
Definition at line 78 of file exprDriverIO.C.
References dict, and Foam::name().
readDict()
bool readDict (const dictionary & dict) virtual
Reimplemented in fvExprDriver, and parseDriver.
Definition at line 289 of file exprDriver.C.
References dict.
Referenced by exprDriver::exprDriver(), Function1Expression< Type >::Function1Expression(), and fvExprDriver::readDict().
setVariableStrings()
Foam::label setVariableStrings (const dictionary & dict, bool mandatory = false)
Definition at line 99 of file exprDriverIO.C.
References dict.
writeVariableStrings()
Foam::Ostream & writeVariableStrings (Ostream & os, const word & keyword = "") const
Definition at line 111 of file exprDriverIO.C.
References os(), and Ostream::writeKeyword().
addUniformVariable() [2/2]
template<class Type > void addUniformVariable (const word & name, const Type & val) inline
Definition at line 66 of file exprDriverI.H.
References Foam::name(), PtrList< T >::set(), and exprResult::setSingleValue().
evaluate() [2/2]
template<class Type > Foam::tmp< Foam::Field< Type > > evaluate (const expressions::exprString & expr, bool wantPointData)
Definition at line 79 of file exprDriverI.H.
getResult() [2/2]
template<class Type > Foam::tmp< Foam::Field< Type > > getResult (bool wantPointData)
Definition at line 84 of file exprDriverTemplates.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, exprResult::getResult(), exprResult::isPointData(), Foam::nl, and exprDriver::result_.
getFunction1Ptr()
template<class Type > const Foam::Function1< Type > * getFunction1Ptr (const word & name, const HashTable< refPtr< Function1< Type > > > & tbl, wordList * listFailure)
Definition at line 102 of file exprDriverTemplates.C.
References UPtrList< T >::get(), and Foam::name().
newField() [2/2]
template<class Type > Foam::tmp< Foam::Field< Type > > newField (const Type & val) const
Definition at line 322 of file exprDriverTemplates.C.
References Foam::New().
newPointField() [2/2]
template<class Type > Foam::tmp< Foam::Field< Type > > newPointField (const Type & val) const
Definition at line 333 of file exprDriverTemplates.C.
References Foam::New().
Member Data Documentation
dict_
const dictionary& dict_ protected
Definition at line 184 of file exprDriver.H.
Referenced by exprDriver::dict(), and exprDriver::exprDriver().
result_
exprResult result_ protected
Definition at line 187 of file exprDriver.H.
Referenced by exprDriver::getResult(), exprDriver::getResultType(), exprDriver::result(), and exprDriver::result().
variableStrings_
List<expressions::exprString> variableStrings_ protected
Definition at line 190 of file exprDriver.H.
variables_
HashTable<exprResult> variables_ protected
Definition at line 193 of file exprDriver.H.
Referenced by fvExprDriver::hasVariable().
scalarFuncs_
HashTable<refPtr<Function1<scalar> > > scalarFuncs_ protected
Definition at line 197 of file exprDriver.H.
Referenced by exprDriver::exprDriver().
vectorFuncs_
HashTable<refPtr<Function1<vector> > > vectorFuncs_ protected
Definition at line 201 of file exprDriver.H.
Referenced by exprDriver::exprDriver().
contextObjects_
contextObjectTableType contextObjects_ protected
Definition at line 204 of file exprDriver.H.
Referenced by exprDriver::hasContextObjects().
arg1Value_
scalar arg1Value_ protected
Definition at line 207 of file exprDriver.H.
Referenced by exprDriver::argValue().
timeStatePtr_
const TimeState* timeStatePtr_ mutable protected
Definition at line 210 of file exprDriver.H.
obrPtr_
const objectRegistry* obrPtr_ protected
Definition at line 213 of file exprDriver.H.
stashedTokenId_
int stashedTokenId_ mutable protected
Definition at line 219 of file exprDriver.H.
debugScanner_
bool debugScanner_ protected
Definition at line 222 of file exprDriver.H.
Referenced by exprDriver::setDebugging().
debugParser_
bool debugParser_ protected
Definition at line 225 of file exprDriver.H.
Referenced by exprDriver::setDebugging().
allowShadowing_
bool allowShadowing_ protected
Definition at line 228 of file exprDriver.H.
prevIterIsOldTime_
bool prevIterIsOldTime_ protected
Definition at line 231 of file exprDriver.H.
Referenced by exprDriver::prevIterIsOldTime().
searchCtrl_
searchControls searchCtrl_ protected
Definition at line 234 of file exprDriver.H.
Referenced by exprDriver::setSearchBehaviour().
The documentation for this class was generated from the following files:
src/OpenFOAM/expressions/exprDriver/exprDriver.H
src/OpenFOAM/expressions/exprDriver/exprDriver.C
src/OpenFOAM/expressions/exprDriver/exprDriverContextI.H
src/OpenFOAM/expressions/exprDriver/exprDriverFields.C
src/OpenFOAM/expressions/exprDriver/exprDriverFunctions.C
src/OpenFOAM/expressions/exprDriver/exprDriverI.H
src/OpenFOAM/expressions/exprDriver/exprDriverIO.C
src/OpenFOAM/expressions/exprDriver/exprDriverTemplates.C