OpenFOAM: pointToFace Class Reference
pointToFace Class Reference
A topoSetFaceSource to select faces with any point or any edge within a given pointSet(s).
#include <pointToFace.H>
Public Types
enum pointAction { ANY , ALL , EDGE }
Public Types inherited from topoSetSource
enum sourceType {
UNKNOWN_SOURCE = 0 , CELL_TYPE = 0x1 , FACE_TYPE = 0x2 , POINT_TYPE = 0x4 ,
SET_SOURCE = 0x10 , CELLSET_SOURCE = (CELL_TYPE | SET_SOURCE) , FACESET_SOURCE = (FACE_TYPE | SET_SOURCE) , POINTSET_SOURCE = (POINT_TYPE | SET_SOURCE) ,
ZONE_SOURCE = 0x20 , CELLZONE_SOURCE = (CELL_TYPE | ZONE_SOURCE) , FACEZONE_SOURCE = (FACE_TYPE | ZONE_SOURCE) , POINTZONE_SOURCE = (POINT_TYPE | ZONE_SOURCE) ,
CELLSETSOURCE = CELLSET_SOURCE , FACESETSOURCE = FACESET_SOURCE , POINTSETSOURCE = POINTSET_SOURCE , CELLZONESOURCE = CELLZONE_SOURCE ,
FACEZONESOURCE = FACEZONE_SOURCE , POINTZONESOURCE = POINTZONE_SOURCE
}
enum setAction {
ADD , SUBTRACT , NEW , SUBSET ,
INVERT , CLEAR , REMOVE , LIST ,
IGNORE , DELETE = SUBTRACT
}
Public Member Functions
TypeName ("pointToFace")
pointToFace (const polyMesh &mesh, const word &setName, const pointAction option)
pointToFace (const polyMesh &mesh, const dictionary &dict)
pointToFace (const polyMesh &mesh, Istream &is)
virtual ~pointToFace ()=default
virtual void applyToSet (const topoSetSource::setAction action, topoSet &set) const
Public Member Functions inherited from topoSetFaceSource
declareRunTimeSelectionTable (autoPtr, topoSetFaceSource, word,(const polyMesh &mesh, const dictionary &dict),(mesh, dict))
declareRunTimeSelectionTable (autoPtr, topoSetFaceSource, istream,(const polyMesh &mesh, Istream &is),(mesh, is))
topoSetFaceSource (const polyMesh &mesh)
topoSetFaceSource (const polyMesh &mesh, const dictionary &dict)
autoPtr< topoSetFaceSource > clone () const
virtual ~topoSetFaceSource ()=default
virtual topoSetSource::sourceType setType () const
Public Member Functions inherited from topoSetSource
TypeName ("topoSetSource")
declareRunTimeSelectionTable (autoPtr, topoSetSource, word,(const polyMesh &mesh, const dictionary &dict),(mesh, dict))
declareRunTimeSelectionTable (autoPtr, topoSetSource, istream,(const polyMesh &mesh, Istream &is),(mesh, is))
topoSetSource (const polyMesh &mesh, bool verbose=true)
topoSetSource (const polyMesh &mesh, const dictionary &dict)
autoPtr< topoSetSource > clone () const
virtual ~topoSetSource ()=default
const polyMesh & mesh () const noexcept
bool verbose () const noexcept
bool verbose (bool on) noexcept
void verbose (const dictionary &dict)
Additional Inherited Members
Static Public Member Functions inherited from topoSetFaceSource
static autoPtr< topoSetFaceSource > New (const word &sourceType, const polyMesh &mesh, const dictionary &dict)
static autoPtr< topoSetFaceSource > New (const word &sourceType, const polyMesh &mesh, Istream &is)
Static Public Member Functions inherited from topoSetSource
static Istream & checkIs (Istream &is)
static bool isSetSource (const sourceType t) noexcept
static bool isZoneSource (const sourceType t) noexcept
static bool isCell (const sourceType t) noexcept
static bool isFace (const sourceType t) noexcept
static bool isPoint (const sourceType t) noexcept
static const string & usage (const word &name)
static autoPtr< topoSetSource > New (const word &topoSetSourceType, const polyMesh &mesh, const dictionary &dict)
static autoPtr< topoSetSource > New (const word &topoSetSourceType, const polyMesh &mesh, Istream &is)
static setAction toAction (const word &actionName)
Static Public Attributes inherited from topoSetSource
static const Enum< setAction > actionNames
static const Enum< setAction > combineNames
Protected Member Functions inherited from topoSetSource
void addOrDelete (topoSet &set, const label id, const bool add) const
void addOrDelete (topoSet &set, const labelUList &labels, const bool add) const
void addOrDelete (topoSet &set, const bitSet &labels, const bool add) const
topoSetSource (const topoSetSource &)=delete
void operator= (const topoSetSource &)=delete
Static Protected Member Functions inherited from topoSetSource
static bool check (labelList &list, const label maxLabel)
Protected Attributes inherited from topoSetSource
const polyMesh & mesh_
bool verbose_
Static Protected Attributes inherited from topoSetSource
static const string illegalSource_
static HashTable< string > * usageTablePtr_ = nullptr
Detailed Description
A topoSetFaceSource to select faces with any point or any edge within a given pointSet(s).
Operands
Operand Type Location
input pointSet(s) $FOAM_CASE/constant/polyMesh/sets/<set>
output faceSet $FOAM_CASE/constant/polyMesh/sets/<set>
Usage
Minimal example by using system/topoSetDict.actions:
{
    // Mandatory (inherited) entries
    name        <name>;
    type        faceSet;
    action      <action>;
    // Mandatory entries
    source      pointToFace;
    option      <option>;
    // Conditional mandatory entries
    // Select either of the below
    // Option-1
    sets
    (
        <pointSetName1>
        <pointSetName2>
        ...
    );
    // Option-2
    set   <pointSetName>;
}
where the entries mean:
Property Description Type Req'd Dflt
name Name of faceSet word yes -
type Type name: faceSet word yes -
action Action applied on faces - see below word yes -
source Source name: pointToFace word yes -
option Selection type - see below word yes -
Options for the action entry:
      new      | Create a new faceSet from selected faces
      add      | Add selected faces into this faceSet
      subtract | Remove selected faces from this faceSet
Options for the option entry:
      any     | Any point in the pointSet
      edge    | Two consecutive points (an edge) in the pointSet
      all     | All points in the pointSet
Options for the conditional mandatory entries:
      Entry    | Description                | Type     | Req'd  | Dflt
      sets     | Names of input pointSets   | wordList | cond'l | -
      set      | Name of input pointSet     | word     | cond'l | -
Note
The order of precedence among the conditional mandatory entries from the highest to the lowest is sets, and set.
See also
Foam::topoSetSource
Foam::topoSetFaceSource
Source files
pointToFace.H
pointToFace.C
Definition at line 172 of file pointToFace.H.
Member Enumeration Documentation
pointAction
enum pointAction
Enumerator
ANY
ALL
EDGE
Definition at line 180 of file pointToFace.H.
Constructor & Destructor Documentation
pointToFace() [1/3]
pointToFace (const polyMesh & mesh, const word & setName, const pointAction option)
Definition at line 158 of file pointToFace.C.
pointToFace() [2/3]
pointToFace (const polyMesh & mesh, const dictionary & dict)
Definition at line 171 of file pointToFace.C.
References dict, UList< T >::front(), and List< T >::resize().
pointToFace() [3/3]
pointToFace (const polyMesh & mesh, Istream & is)
Definition at line 190 of file pointToFace.C.
~pointToFace()
virtual ~pointToFace () virtual default
Member Function Documentation
TypeName()
TypeName ("pointToFace")
applyToSet()
void applyToSet (const topoSetSource::setAction action, topoSet & set) const virtual
Implements topoSetSource.
Definition at line 204 of file pointToFace.C.
References topoSetSource::ADD, Foam::flatOutput(), Foam::Info, topoSetSource::NEW, Foam::nl, and topoSetSource::SUBTRACT.
The documentation for this class was generated from the following files:
src/meshTools/topoSet/faceSources/pointToFace/pointToFace.H
src/meshTools/topoSet/faceSources/pointToFace/pointToFace.C