OpenFOAM: fanPressureFvPatchScalarField Class Reference
fanPressureFvPatchScalarField Class Reference
Boundary conditions » Inlet | Boundary conditions » Outlet
This boundary condition can be applied to assign either a pressure inlet or outlet total pressure condition for a fan.
#include <fanPressureFvPatchScalarField.H>
Public Types
enum fanFlowDirection : uint8_t { ffdIn , ffdOut }
Public Member Functions
TypeName ("fanPressure")
fanPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
fanPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
fanPressureFvPatchScalarField (const fanPressureFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
fanPressureFvPatchScalarField (const fanPressureFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
fanPressureFvPatchScalarField (const fanPressureFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual void updateCoeffs ()
virtual void write (Ostream &os) const
Public Member Functions inherited from totalPressureFvPatchScalarField
TypeName ("totalPressure")
totalPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
totalPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
totalPressureFvPatchScalarField (const totalPressureFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
totalPressureFvPatchScalarField (const totalPressureFvPatchScalarField &)
totalPressureFvPatchScalarField (const totalPressureFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
const word & UName () const
word & UName ()
const word & phiName () const
word & phiName ()
const word & rhoName () const
word & rhoName ()
const word & psiName () const
word & psiName ()
scalar gamma () const
scalar & gamma ()
const scalarField & p0 () const
scalarField & p0 ()
virtual void autoMap (const fvPatchFieldMapper &)
virtual void rmap (const fvPatchScalarField &, const labelList &)
virtual void updateCoeffs (const scalarField &p0p, const vectorField &Up)
Static Public Attributes
static const Enum< fanFlowDirection > fanFlowDirectionNames_
Detailed Description
This boundary condition can be applied to assign either a pressure inlet or outlet total pressure condition for a fan.
The switch nonDimensional can be used for a non-dimensional fan curve. It needs inputs rpm and dm of the fan.
The nonDimensional flux is calculate as :
phi = 4.0*mDot/(rho*sqr(PI)*dm^3*omega) where: dm is the mean diameter. omega is rad/sec.
The nonDimensinal pressure :
Psi = 2 deltaP/(rho*(sqr(PI*omega*dm))) where: deltaP is the pressure drop
The non-dimensional table should be given as Psi = F(phi).
Usage
Property Description Required Default
fanCurve Pressure vs flow-rate yes
direction direction of flow through fan [in/out] yes
p0 environmental total pressure yes
nonDimensional uses non-dimensional table no false
rpm fan rpm for non-dimensional table no
dm mean diameter for non-dimensional table no
file fan curve file name legacy
outOfBounds out of bounds handling legacy
Example of the boundary condition specification:
    inlet
    {
        type            fanPressure;
        direction       in;
        fanCurve
        {
            type table;
            file "<constant>/fanCurve";
            outOfBounds clamp;  // Optional out-of-bounds handling
        }
        p0              uniform 0;
        value           uniform 0;
    }
    // Legacy specification
    outlet
    {
        type            fanPressure;
        direction       out;
        file            "<constant>/fanCurve";
        outOfBounds     clamp;
        p0              uniform 0;
        value           uniform 0;
    }
Note
For compatibility with older versions (OpenFOAM-v2006 and earlier), a missing fanCurve keyword is treated as a tableFile and makes the file keyword mandatory.
See also
Foam::fanFvPatchField Foam::totalPressureFvPatchScalarField Foam::Function1
Source files
fanPressureFvPatchScalarField.H
fanPressureFvPatchScalarField.C
Definition at line 166 of file fanPressureFvPatchScalarField.H.
Member Enumeration Documentation
fanFlowDirection
enum fanFlowDirection : uint8_t
Enumerator
ffdIn
ffdOut
Definition at line 173 of file fanPressureFvPatchScalarField.H.
Constructor & Destructor Documentation
fanPressureFvPatchScalarField() [1/5]
fanPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 43 of file fanPressureFvPatchScalarField.C.
fanPressureFvPatchScalarField() [2/5]
fanPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 75 of file fanPressureFvPatchScalarField.C.
References dict.
fanPressureFvPatchScalarField() [3/5]
fanPressureFvPatchScalarField (const fanPressureFvPatchScalarField & rhs, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 58 of file fanPressureFvPatchScalarField.C.
fanPressureFvPatchScalarField() [4/5]
fanPressureFvPatchScalarField (const fanPressureFvPatchScalarField & rhs)
Definition at line 110 of file fanPressureFvPatchScalarField.C.
fanPressureFvPatchScalarField() [5/5]
fanPressureFvPatchScalarField (const fanPressureFvPatchScalarField & rhs, const DimensionedField< scalar, volMesh > & iF)
Definition at line 124 of file fanPressureFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("fanPressure")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Reimplemented from totalPressureFvPatchScalarField.
Definition at line 244 of file fanPressureFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Reimplemented from totalPressureFvPatchScalarField.
Definition at line 260 of file fanPressureFvPatchScalarField.H.
updateCoeffs()
void updateCoeffs () virtual
Reimplemented from totalPressureFvPatchScalarField.
Definition at line 141 of file fanPressureFvPatchScalarField.C.
References Foam::dimMass, Foam::dimTime, Foam::dimVolume, Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::gSum(), Foam::max(), Foam::nl, p0, Foam::constant::mathematical::pi(), Foam::pow3(), Foam::pow4(), Foam::sqr(), Foam::stabilise(), UName(), and totalPressureFvPatchScalarField::updateCoeffs().
write()
void write (Ostream & os) const virtual
Reimplemented from totalPressureFvPatchScalarField.
Definition at line 216 of file fanPressureFvPatchScalarField.C.
References os(), totalPressureFvPatchScalarField::write(), and Ostream::writeEntry().
Member Data Documentation
fanFlowDirectionNames_
const Foam::Enum< Foam::fanPressureFvPatchScalarField::fanFlowDirection > fanFlowDirectionNames_ static
Definition at line 180 of file fanPressureFvPatchScalarField.H.
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/fanPressure/fanPressureFvPatchScalarField.H
src/finiteVolume/fields/fvPatchFields/derived/fanPressure/fanPressureFvPatchScalarField.C