OpenFOAM: meshedSurfRef Class Reference
meshedSurfRef Class Reference
Implements a meshed surface by referencing another meshed surface or faces/points components.
#include <meshedSurfRef.H>
Public Member Functions
meshedSurfRef ()
meshedSurfRef (const meshedSurf &s)
meshedSurfRef (const pointField &points, const faceList &faces, const labelList &zoneIds=labelList::null(), const labelList &faceIds=labelList::null())
virtual ~meshedSurfRef ()=default
bool good () const
bool valid () const
const pointField & points0 () const
virtual const pointField & points () const
virtual const faceList & faces () const
virtual const labelList & zoneIds () const
virtual const labelList & faceIds () const
void clear ()
void reset (const meshedSurf &s)
void reset (const pointField &points, const faceList &faces, const labelList &zoneIds=labelList::null(), const labelList &faceIds=labelList::null())
void resetPoints ()
void movePoints (pointField &&pts)
void movePoints (const tmp< pointField > &tpts)
void scalePoints (const scalar scaleFactor)
Public Member Functions inherited from meshedSurf
constexpr meshedSurf () noexcept=default
virtual ~meshedSurf ()=default
Detailed Description
Implements a meshed surface by referencing another meshed surface or faces/points components.
In addition to the referencing, supports simple moving/scaling of points (uses a deep-copy).
Definition at line 47 of file meshedSurfRef.H.
Constructor & Destructor Documentation
meshedSurfRef() [1/3]
meshedSurfRef () inline
Definition at line 71 of file meshedSurfRef.H.
meshedSurfRef() [2/3]
meshedSurfRef (const meshedSurf & s) inline explicit
Definition at line 80 of file meshedSurfRef.H.
References s().
meshedSurfRef() [3/3]
meshedSurfRef (const pointField & points, const faceList & faces, const labelList & zoneIds = labelList::null(), const labelList & faceIds = labelList::null()) inline
Definition at line 88 of file meshedSurfRef.H.
~meshedSurfRef()
virtual ~meshedSurfRef () virtual default
Member Function Documentation
good()
bool good () const inline
Definition at line 110 of file meshedSurfRef.H.
References Foam::notNull().
Referenced by meshedSurfRef::valid().
valid()
bool valid () const inline
Definition at line 116 of file meshedSurfRef.H.
References meshedSurfRef::good().
points0()
const pointField & points0 () const inline
Definition at line 119 of file meshedSurfRef.H.
Referenced by meshedSurfRef::points(), and meshedSurfRef::scalePoints().
points()
virtual const pointField & points () const inline virtual
Implements meshedSurf.
Definition at line 125 of file meshedSurfRef.H.
References UList< T >::empty(), and meshedSurfRef::points0().
Referenced by meshedSurfRef::reset(), foamWriter::write(), proxyWriter::write(), rawWriter::write(), starcdWriter::write(), vtkWriter::write(), x3dWriter::write(), ensightWriter::writeCollated(), abaqusWriter::writeTemplate(), nastranWriter::writeTemplate(), rawWriter::writeTemplate(), x3dWriter::writeTemplate(), and ensightWriter::writeUncollated().
faces()
virtual const faceList & faces () const inline virtual
Implements meshedSurf.
Definition at line 131 of file meshedSurfRef.H.
Referenced by meshedSurfRef::reset(), foamWriter::write(), proxyWriter::write(), rawWriter::write(), starcdWriter::write(), vtkWriter::write(), x3dWriter::write(), ensightWriter::writeCollated(), abaqusWriter::writeTemplate(), nastranWriter::writeTemplate(), rawWriter::writeTemplate(), x3dWriter::writeTemplate(), and ensightWriter::writeUncollated().
zoneIds()
virtual const labelList & zoneIds () const inline virtual
Reimplemented from meshedSurf.
Definition at line 137 of file meshedSurfRef.H.
Referenced by meshedSurfRef::reset().
faceIds()
virtual const labelList & faceIds () const inline virtual
Reimplemented from meshedSurf.
Definition at line 143 of file meshedSurfRef.H.
Referenced by meshedSurfRef::reset(), starcdWriter::write(), abaqusWriter::writeTemplate(), nastranWriter::writeTemplate(), and starcdWriter::writeTemplate().
clear()
void clear () inline
Definition at line 149 of file meshedSurfRef.H.
References List< T >::clear(), List< label >::null(), List< face >::null(), and Field< vector >::null().
Referenced by meshedSurfRef::reset().
reset() [1/2]
void reset (const meshedSurf & s) inline
Definition at line 160 of file meshedSurfRef.H.
References meshedSurfRef::clear(), and s().
reset() [2/2]
void reset (const pointField & points, const faceList & faces, const labelList & zoneIds = labelList::null(), const labelList & faceIds = labelList::null()) inline
Definition at line 167 of file meshedSurfRef.H.
References List< T >::clear(), meshedSurfRef::faceIds(), meshedSurfRef::faces(), meshedSurfRef::points(), and meshedSurfRef::zoneIds().
resetPoints()
void resetPoints () inline
Definition at line 185 of file meshedSurfRef.H.
References List< T >::clear().
movePoints() [1/2]
void movePoints (pointField && pts) inline
Definition at line 191 of file meshedSurfRef.H.
References pts, and List< T >::transfer().
movePoints() [2/2]
void movePoints (const tmp< pointField > & tpts) inline
Definition at line 197 of file meshedSurfRef.H.
References List< T >::clear(), and PtrList< T >::clear().
scalePoints()
void scalePoints (const scalar scaleFactor) inline
Definition at line 208 of file meshedSurfRef.H.
References UList< T >::empty(), Foam::equal(), and meshedSurfRef::points0().
The documentation for this class was generated from the following file:
src/surfMesh/meshedSurf/meshedSurfRef.H