OpenFOAM: multiRegion Class Reference
multiRegion Class Reference
FunctionObjects » Utility function objects
Wrapper that clones the supplied function object for each region.
#include <multiRegion.H>
Public Member Functions
TypeName ("multiRegion")
multiRegion (const word &name, const Time &runTime, const dictionary &dict)
virtual ~multiRegion ()=default
virtual bool read (const dictionary &dict)
virtual bool execute ()
virtual bool write ()
Public Member Functions inherited from timeFunctionObject
timeFunctionObject (const word &name, const Time &runTime)
virtual ~timeFunctionObject ()=default
const Time & time () const
objectRegistry & storedObjects ()
const objectRegistry & storedObjects () const
Public Member Functions inherited from functionObject
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name, const bool withNamePrefix=defaultUseNamePrefix)
autoPtr< functionObject > clone () const
virtual ~functionObject ()=default
virtual const word & type () const =0
const word & name () const noexcept
bool useNamePrefix () const noexcept
bool useNamePrefix (bool on) noexcept
virtual bool execute (const label subIndex)
virtual bool end ()
virtual bool adjustTimeStep ()
virtual bool filesModified () const
virtual void updateMesh (const mapPolyMesh &mpm)
virtual void movePoints (const polyMesh &mesh)
Protected Member Functions
multiRegion (const multiRegion &)=delete
void operator= (const multiRegion &)=delete
Protected Member Functions inherited from timeFunctionObject
void clearOutputObjects (const wordList &objNames)
timeFunctionObject (const timeFunctionObject &)=delete
void operator= (const timeFunctionObject &)=delete
Protected Member Functions inherited from functionObject
word scopedName (const word &name) const
Protected Attributes
PtrList< functionObject > functions_
Protected Attributes inherited from timeFunctionObject
const Time & time_
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &runTime, const dictionary &dict)
Public Attributes inherited from functionObject
bool log
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
static bool defaultUseNamePrefix
static word outputPrefix
Detailed Description
Wrapper that clones the supplied function object for each region.
Simplifies the setup of identical post-processing requirements for multi-region cases. Applies the supplied function to all regions by default.
Usage
Minimal example by using system/controlDict.functions:
multiRegion
{
    // Mandatory entries
    type    multiRegion;
    libs    (utilityFunctionObjects);
    function
    {
        // Actual object specification
        type    fieldMinMax;
        libs    (fieldFunctionObjects);
        fields  (<field1> ... <fieldN>);
    }
    // Optional entries
    regions     (region1 region2);
}
where the entries mean:
Property Description Type Reqd Deflt
type Type name: multiRegion word yes -
libs Library name: utilityFunctionObjects word yes -
function Function object sub-dictionary dict yes -
regions List of region names wordList no all
See also
Foam::functionObject
Source files
multiRegion.H
multiRegion.C
Definition at line 119 of file multiRegion.H.
Constructor & Destructor Documentation
multiRegion() [1/2]
multiRegion (const multiRegion &) protected delete
multiRegion() [2/2]
multiRegion (const word & name, const Time & runTime, const dictionary & dict)
Definition at line 46 of file multiRegion.C.
References dict, Foam::name(), and multiRegion::read().
~multiRegion()
virtual ~multiRegion () virtual default
Member Function Documentation
operator=()
void operator= (const multiRegion &) protected delete
TypeName()
TypeName ("multiRegion")
read()
bool read (const dictionary & dict) virtual
Reimplemented from functionObject.
Definition at line 61 of file multiRegion.C.
References dict, Foam::endl(), timeControl::entriesPresent(), f(), Foam::Info, Foam::name(), functionObject::New(), Foam::nl, functionObject::read(), regionName, PtrList< T >::resize(), IOobject::scopedName(), PtrList< T >::set(), UPtrList< T >::size(), Foam::type(), and WarningInFunction.
Referenced by multiRegion::multiRegion().
execute()
bool execute () virtual
Implements functionObject.
Definition at line 136 of file multiRegion.C.
References f().
write()
bool write () virtual
Implements functionObject.
Definition at line 149 of file multiRegion.C.
References f().
Member Data Documentation
functions_
PtrList<functionObject> functions_ protected
Definition at line 128 of file multiRegion.H.
The documentation for this class was generated from the following files:
src/functionObjects/utilities/multiRegion/multiRegion.H
src/functionObjects/utilities/multiRegion/multiRegion.C