OpenFOAM: syringePressureFvPatchScalarField Class Reference
syringePressureFvPatchScalarField Class Reference
Boundary conditions » Inlet
This boundary condition provides a pressure condition, obtained from a zero-D model of the cylinder of a syringe.
#include <syringePressureFvPatchScalarField.H>
Public Member Functions
TypeName ("syringePressure")
syringePressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
syringePressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
syringePressureFvPatchScalarField (const syringePressureFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
virtual tmp< fvPatchScalarField > clone () const
syringePressureFvPatchScalarField (const syringePressureFvPatchScalarField &)
syringePressureFvPatchScalarField (const syringePressureFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
This boundary condition provides a pressure condition, obtained from a zero-D model of the cylinder of a syringe.
The syringe cylinder is defined by its initial volume, piston area and velocity profile specified by regions of constant acceleration, speed and deceleration. The gas in the cylinder is described by its initial pressure and compressibility which is assumed constant, i.e. isothermal expansion/compression.
Usage
Property Description Required Default value
Ap syringe piston area [m2] yes
Sp syringe piston speed [m/s] yes
VsI initial syringe volume [m3] yes
tas start of piston acceleration [s] yes
tae end of piston acceleration [s] yes
tds start of piston deceleration [s] yes
tde end of piston deceleration [s] yes
psI initial syringe pressure [Pa] yes
psi gas compressibility [m2/s2] yes
ams added (or removed) gas mass [kg] yes
Example of the BC specification:
    <patchName>
    {
        type            syringePressure;
        Ap              1.388e-6;
        Sp              0.01;
        VsI             1.388e-8;
        tas             0.001;
        tae             0.002;
        tds             0.005;
        tde             0.006;
        psI             1e5;
        psi             1e-5;
        ams             0;
        value           uniform 0;
    }
See also
Foam::fixedValueFvPatchField
Source files
syringePressureFvPatchScalarField.H
syringePressureFvPatchScalarField.C
Definition at line 148 of file syringePressureFvPatchScalarField.H.
Constructor & Destructor Documentation
syringePressureFvPatchScalarField() [1/5]
syringePressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 30 of file syringePressureFvPatchScalarField.C.
syringePressureFvPatchScalarField() [2/5]
syringePressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 42 of file syringePressureFvPatchScalarField.C.
References fvPatchField< Type >::operator=().
syringePressureFvPatchScalarField() [3/5]
syringePressureFvPatchScalarField (const syringePressureFvPatchScalarField & sppsf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 69 of file syringePressureFvPatchScalarField.C.
syringePressureFvPatchScalarField() [4/5]
syringePressureFvPatchScalarField (const syringePressureFvPatchScalarField & sppsf)
Definition at line 117 of file syringePressureFvPatchScalarField.C.
syringePressureFvPatchScalarField() [5/5]
syringePressureFvPatchScalarField (const syringePressureFvPatchScalarField & sppsf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 94 of file syringePressureFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("syringePressure")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 234 of file syringePressureFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 256 of file syringePressureFvPatchScalarField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 180 of file syringePressureFvPatchScalarField.C.
References Foam::dimMass, Foam::dimTime, Foam::dimVolume, Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::operator==(), Foam::sum(), and timeIndex.
write()
void write (Ostream & os) const virtual
Definition at line 224 of file syringePressureFvPatchScalarField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntry(), Ostream::writeEntryIfDifferent(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/syringePressure/syringePressureFvPatchScalarField.H
src/finiteVolume/fields/fvPatchFields/derived/syringePressure/syringePressureFvPatchScalarField.C