OpenFOAM: indexedVertex< Gt, Vb > Class Template Reference
indexedVertex< Gt, Vb > Class Template Reference
An indexed form of CGAL::Triangulation_vertex_base_3<K> used to keep track of the Delaunay vertices in the tessellation.
#include <indexedVertex.H>
Classes
struct Rebind_TDS
Public Types
enum pointTypes { NEAR_BOUNDARY_POINT = -4 , INTERNAL_POINT = -3 , MIRROR_POINT = -2 , FAR_POINT = -1 }
typedef Vb::Triangulation_data_structure Tds
typedef Vb::Point Point
typedef Tds::Vertex_handle Vertex_handle
typedef Tds::Cell_handle Cell_handle
typedef Vb::Vertex_handle Vertex_handle
typedef Vb::Face_handle Face_handle
typedef Vb::Point Point
Public Types inherited from indexedVertexEnum
enum vertexType {
vtUnassigned = 0 , vtInternal = 1 , vtInternalNearBoundary = 2 , vtInternalSurface = 3 ,
vtInternalSurfaceBaffle = 4 , vtExternalSurfaceBaffle = 5 , vtInternalFeatureEdge = 6 , vtInternalFeatureEdgeBaffle = 7 ,
vtExternalFeatureEdgeBaffle = 8 , vtInternalFeaturePoint = 9 , vtExternalSurface = 10 , vtExternalFeatureEdge = 11 ,
vtExternalFeaturePoint = 12 , vtFar = 13 , vtConstrained = 14
}
enum vertexMotion { fixed = 0 , movable = 1 }
Public Member Functions
indexedVertex (const indexedVertex &)=default
indexedVertex ()
indexedVertex (const Point &p)
indexedVertex (const Point &p, vertexType type)
indexedVertex (const Foam::point &p, vertexType type)
indexedVertex (const Point &p, Foam::label index, vertexType type, int processor)
indexedVertex (const Foam::point &p, Foam::label index, vertexType type, int processor)
indexedVertex (const Point &p, Cell_handle f)
indexedVertex (Cell_handle f)
Foam::label & index ()
Foam::label index () const
vertexType & type ()
vertexType type () const
Foam::tensor & alignment ()
const Foam::tensor & alignment () const
Foam::scalar & targetCellSize ()
Foam::scalar targetCellSize () const
bool farPoint () const
bool internalPoint () const
bool referred () const
bool real () const
int procIndex () const
int & procIndex ()
void setInternal ()
bool nearBoundary () const
void setNearBoundary ()
bool nearProcBoundary () const
void setNearProcBoundary ()
bool boundaryPoint () const
bool internalOrBoundaryPoint () const
bool nearOrOnBoundary () const
bool featurePoint () const
bool featureEdgePoint () const
bool surfacePoint () const
bool internalBoundaryPoint () const
bool internalBaffleSurfacePoint () const
bool internalBaffleEdgePoint () const
bool externalBoundaryPoint () const
bool externalBaffleSurfacePoint () const
bool externalBaffleEdgePoint () const
bool constrained () const
bool fixed () const
bool & fixed ()
void operator= (const indexedVertex &rhs)
bool operator== (const indexedVertex &rhs) const
bool operator!= (const indexedVertex &rhs) const
Foam::InfoProxy< indexedVertex< Gt, Vb > > info () const noexcept
indexedVertex ()
indexedVertex (const Point &p)
indexedVertex (const Point &p, const int index, const int &type)
indexedVertex (const Point &p, Face_handle f)
indexedVertex (Face_handle f)
int & index ()
int index () const
int & type ()
int type () const
bool farPoint () const
bool internalPoint () const
bool nearBoundary () const
void setNearBoundary ()
bool mirrorPoint () const
bool pairPoint () const
bool ppMaster () const
bool ppSlave () const
bool internalOrBoundaryPoint () const
bool nearOrOnBoundary () const
Friends
Foam::Ostream & Foam::operator (Foam::Ostream &, const Foam::InfoProxy< indexedVertex< Gt, Vb > > &)
Foam::Ostream & Foam::operator (Foam::Ostream &, const indexedVertex< Gt, Vb > &)
Foam::Istream & Foam::operator>> (Foam::Istream &, indexedVertex< Gt, Vb > &)
bool pointPair (const indexedVertex< Gt, Vb > &v0, const indexedVertex< Gt, Vb > &v1)
bool boundaryTriangle (const indexedVertex< Gt, Vb > &v0, const indexedVertex< Gt, Vb > &v1, const indexedVertex< Gt, Vb > &v2)
bool outsideTriangle (const indexedVertex< Gt, Vb > &v0, const indexedVertex< Gt, Vb > &v1, const indexedVertex< Gt, Vb > &v2)
Additional Inherited Members
Static Public Attributes inherited from indexedVertexEnum
static const Enum< vertexType > vertexTypeNames_
static const Enum< vertexMotion > vertexMotionNames_
Detailed Description
template<class Gt, class Vb = CGAL::Triangulation_vertex_base_2<Gt>>
class CGAL::indexedVertex< Gt, Vb >
An indexed form of CGAL::Triangulation_vertex_base_3<K> used to keep track of the Delaunay vertices in the tessellation.
An indexed form of CGAL::Triangulation_vertex_base_2<K> used to keep track of the vertices in the triangulation.
Source files
indexedVertex.H
indexedVertexI.H
indexedVertex.C
Definition at line 80 of file indexedVertex.H.
Member Typedef Documentation
Tds
template<class Gt , class Vb = CGAL::Triangulation_vertex_base_2<Gt>> typedef Vb::Triangulation_data_structure Tds
Definition at line 139 of file indexedVertex.H.
Point [1/2]
template<class Gt , class Vb = CGAL::Triangulation_vertex_base_2<Gt>> typedef Vb::Point Point
Definition at line 140 of file indexedVertex.H.
Vertex_handle [1/2]
template<class Gt , class Vb = CGAL::Triangulation_vertex_base_2<Gt>> typedef Tds::Vertex_handle Vertex_handle
Definition at line 141 of file indexedVertex.H.
Cell_handle
template<class Gt , class Vb = CGAL::Triangulation_vertex_base_2<Gt>> typedef Tds::Cell_handle Cell_handle
Definition at line 142 of file indexedVertex.H.
Vertex_handle [2/2]
template<class Gt , class Vb = CGAL::Triangulation_vertex_base_2<Gt>> typedef Vb::Vertex_handle Vertex_handle
Definition at line 108 of file indexedVertex.H.
Face_handle
template<class Gt , class Vb = CGAL::Triangulation_vertex_base_2<Gt>> typedef Vb::Face_handle Face_handle
Definition at line 109 of file indexedVertex.H.
Point [2/2]
template<class Gt , class Vb = CGAL::Triangulation_vertex_base_2<Gt>> typedef Vb::Point Point
Definition at line 110 of file indexedVertex.H.
Member Enumeration Documentation
pointTypes
template<class Gt , class Vb = CGAL::Triangulation_vertex_base_2<Gt>> enum pointTypes
Enumerator
NEAR_BOUNDARY_POINT
INTERNAL_POINT
MIRROR_POINT
FAR_POINT
Definition at line 100 of file indexedVertex.H.
Constructor & Destructor Documentation
indexedVertex() [1/14]
template<class Gt , class Vb = CGAL::Triangulation_vertex_base_2<Gt>> indexedVertex (const indexedVertex< Gt, Vb > &) default
indexedVertex() [2/14]
template<class Gt , class Vb > indexedVertex () inline
Definition at line 26 of file indexedVertexI.H.
indexedVertex() [3/14]
template<class Gt , class Vb > indexedVertex (const Point & p) inline
Definition at line 39 of file indexedVertexI.H.
indexedVertex() [4/14]
template<class Gt , class Vb > indexedVertex (const Point & p, vertexType type) inline
Definition at line 52 of file indexedVertexI.H.
indexedVertex() [5/14]
template<class Gt , class Vb > indexedVertex (const Foam::point & p, vertexType type) inline
Definition at line 69 of file indexedVertexI.H.
indexedVertex() [6/14]
template<class Gt , class Vb > indexedVertex (const Point & p, Foam::label index, vertexType type, int processor) inline
Definition at line 86 of file indexedVertexI.H.
indexedVertex() [7/14]
template<class Gt , class Vb > indexedVertex (const Foam::point & p, Foam::label index, vertexType type, int processor) inline
Definition at line 105 of file indexedVertexI.H.
indexedVertex() [8/14]
template<class Gt , class Vb > indexedVertex (const Point & p, Cell_handle f) inline
Definition at line 124 of file indexedVertexI.H.
indexedVertex() [9/14]
template<class Gt , class Vb > indexedVertex (Cell_handle f) inline
Definition at line 137 of file indexedVertexI.H.
indexedVertex() [10/14]
template<class Gt , class Vb = CGAL::Triangulation_vertex_base_2<Gt>> indexedVertex () inline
indexedVertex() [11/14]
template<class Gt , class Vb = CGAL::Triangulation_vertex_base_2<Gt>> indexedVertex (const Point & p) inline
indexedVertex() [12/14]
template<class Gt , class Vb > indexedVertex (const Point & p, const int index, const int & type) inline
Definition at line 43 of file indexedVertexI.H.
indexedVertex() [13/14]
template<class Gt , class Vb > indexedVertex (const Point & p, Face_handle f) inline
Definition at line 57 of file indexedVertexI.H.
indexedVertex() [14/14]
template<class Gt , class Vb > indexedVertex (Face_handle f) inline
Definition at line 66 of file indexedVertexI.H.
Member Function Documentation
index() [1/4]
template<class Gt , class Vb > int & index () inline
Definition at line 152 of file indexedVertexI.H.
index() [2/4]
template<class Gt , class Vb > int index () const inline
Definition at line 159 of file indexedVertexI.H.
type() [1/4]
template<class Gt , class Vb > int & type () inline
Definition at line 167 of file indexedVertexI.H.
type() [2/4]
template<class Gt , class Vb > int type () const inline
Definition at line 175 of file indexedVertexI.H.
alignment() [1/2]
template<class Gt , class Vb > Foam::tensor & alignment () inline
Definition at line 182 of file indexedVertexI.H.
alignment() [2/2]
template<class Gt , class Vb > const Foam::tensor & alignment () const inline
Definition at line 189 of file indexedVertexI.H.
targetCellSize() [1/2]
template<class Gt , class Vb > Foam::scalar & targetCellSize () inline
Definition at line 196 of file indexedVertexI.H.
targetCellSize() [2/2]
template<class Gt , class Vb > Foam::scalar targetCellSize () const inline
Definition at line 203 of file indexedVertexI.H.
farPoint() [1/2]
template<class Gt , class Vb > bool farPoint () const inline
Definition at line 210 of file indexedVertexI.H.
Referenced by CGAL::outsideTriangle().
internalPoint() [1/2]
template<class Gt , class Vb > bool internalPoint () const inline
Definition at line 217 of file indexedVertexI.H.
referred()
template<class Gt , class Vb > bool referred () const inline
Definition at line 224 of file indexedVertexI.H.
References UPstream::myProcNo().
real()
template<class Gt , class Vb > bool real () const inline
Definition at line 237 of file indexedVertexI.H.
procIndex() [1/2]
template<class Gt , class Vb > int procIndex () const inline
Definition at line 244 of file indexedVertexI.H.
procIndex() [2/2]
template<class Gt , class Vb > int & procIndex () inline
Definition at line 251 of file indexedVertexI.H.
setInternal()
template<class Gt , class Vb > void setInternal () inline
Definition at line 258 of file indexedVertexI.H.
nearBoundary() [1/2]
template<class Gt , class Vb > bool nearBoundary () const inline
Definition at line 265 of file indexedVertexI.H.
setNearBoundary() [1/2]
template<class Gt , class Vb > void setNearBoundary () inline
Definition at line 272 of file indexedVertexI.H.
nearProcBoundary()
template<class Gt , class Vb = CGAL::Triangulation_vertex_base_2<Gt>> bool nearProcBoundary () const inline
setNearProcBoundary()
template<class Gt , class Vb = CGAL::Triangulation_vertex_base_2<Gt>> void setNearProcBoundary () inline
boundaryPoint()
template<class Gt , class Vb > bool boundaryPoint () const inline
Definition at line 279 of file indexedVertexI.H.
internalOrBoundaryPoint() [1/2]
template<class Gt , class Vb > bool internalOrBoundaryPoint () const inline
Definition at line 286 of file indexedVertexI.H.
nearOrOnBoundary() [1/2]
template<class Gt , class Vb > bool nearOrOnBoundary () const inline
Definition at line 293 of file indexedVertexI.H.
featurePoint()
template<class Gt , class Vb > bool featurePoint () const inline
Definition at line 344 of file indexedVertexI.H.
featureEdgePoint()
template<class Gt , class Vb > bool featureEdgePoint () const inline
Definition at line 351 of file indexedVertexI.H.
surfacePoint()
template<class Gt , class Vb > bool surfacePoint () const inline
Definition at line 358 of file indexedVertexI.H.
internalBoundaryPoint()
template<class Gt , class Vb > bool internalBoundaryPoint () const inline
Definition at line 300 of file indexedVertexI.H.
internalBaffleSurfacePoint()
template<class Gt , class Vb > bool internalBaffleSurfacePoint () const inline
Definition at line 306 of file indexedVertexI.H.
internalBaffleEdgePoint()
template<class Gt , class Vb > bool internalBaffleEdgePoint () const inline
Definition at line 312 of file indexedVertexI.H.
externalBoundaryPoint()
template<class Gt , class Vb > bool externalBoundaryPoint () const inline
Definition at line 318 of file indexedVertexI.H.
externalBaffleSurfacePoint()
template<class Gt , class Vb > bool externalBaffleSurfacePoint () const inline
Definition at line 324 of file indexedVertexI.H.
externalBaffleEdgePoint()
template<class Gt , class Vb > bool externalBaffleEdgePoint () const inline
Definition at line 330 of file indexedVertexI.H.
constrained()
template<class Gt , class Vb > bool constrained () const inline
Definition at line 337 of file indexedVertexI.H.
fixed() [1/2]
template<class Gt , class Vb > bool fixed () const inline
Definition at line 365 of file indexedVertexI.H.
fixed() [2/2]
template<class Gt , class Vb > bool & fixed () inline
Definition at line 372 of file indexedVertexI.H.
operator=()
template<class Gt , class Vb = CGAL::Triangulation_vertex_base_2<Gt>> void operator= (const indexedVertex< Gt, Vb > & rhs) inline
Definition at line 279 of file indexedVertex.H.
References indexedVertex< Gt, Vb >::operator=().
Referenced by indexedVertex< Gt, Vb >::operator=().
operator==()
template<class Gt , class Vb = CGAL::Triangulation_vertex_base_2<Gt>> bool operator== (const indexedVertex< Gt, Vb > & rhs) const inline
Definition at line 291 of file indexedVertex.H.
operator!=()
template<class Gt , class Vb = CGAL::Triangulation_vertex_base_2<Gt>> bool operator!= (const indexedVertex< Gt, Vb > & rhs) const inline
Definition at line 303 of file indexedVertex.H.
info()
template<class Gt , class Vb = CGAL::Triangulation_vertex_base_2<Gt>> Foam::InfoProxy< indexedVertex< Gt, Vb > > info () const inline noexcept
Definition at line 313 of file indexedVertex.H.
index() [3/4]
template<class Gt , class Vb = CGAL::Triangulation_vertex_base_2<Gt>> int & index () inline
index() [4/4]
template<class Gt , class Vb = CGAL::Triangulation_vertex_base_2<Gt>> int index () const inline
type() [3/4]
template<class Gt , class Vb = CGAL::Triangulation_vertex_base_2<Gt>> int & type () inline
type() [4/4]
template<class Gt , class Vb = CGAL::Triangulation_vertex_base_2<Gt>> int type () const inline
farPoint() [2/2]
template<class Gt , class Vb = CGAL::Triangulation_vertex_base_2<Gt>> bool farPoint () const inline
internalPoint() [2/2]
template<class Gt , class Vb = CGAL::Triangulation_vertex_base_2<Gt>> bool internalPoint () const inline
nearBoundary() [2/2]
template<class Gt , class Vb = CGAL::Triangulation_vertex_base_2<Gt>> bool nearBoundary () const inline
setNearBoundary() [2/2]
template<class Gt , class Vb = CGAL::Triangulation_vertex_base_2<Gt>> void setNearBoundary () inline
mirrorPoint()
template<class Gt , class Vb > bool mirrorPoint () const inline
Definition at line 133 of file indexedVertexI.H.
pairPoint()
template<class Gt , class Vb > bool pairPoint () const inline
Definition at line 140 of file indexedVertexI.H.
Referenced by CGAL::boundaryTriangle().
ppMaster()
template<class Gt , class Vb > bool ppMaster () const inline
Definition at line 147 of file indexedVertexI.H.
ppSlave()
template<class Gt , class Vb > bool ppSlave () const inline
Definition at line 154 of file indexedVertexI.H.
Referenced by CGAL::outsideTriangle().
internalOrBoundaryPoint() [2/2]
template<class Gt , class Vb = CGAL::Triangulation_vertex_base_2<Gt>> bool internalOrBoundaryPoint () const inline
nearOrOnBoundary() [2/2]
template<class Gt , class Vb = CGAL::Triangulation_vertex_base_2<Gt>> bool nearOrOnBoundary () const inline
Friends And Related Symbol Documentation
Foam::operator [1/2]
template<class Gt , class Vb = CGAL::Triangulation_vertex_base_2<Gt>> Foam::Ostream & Foam::operator (Foam::Ostream & , const Foam::InfoProxy< indexedVertex< Gt, Vb > > &) friend
Foam::operator [2/2]
template<class Gt , class Vb = CGAL::Triangulation_vertex_base_2<Gt>> Foam::Ostream & Foam::operator (Foam::Ostream & , const indexedVertex< Gt, Vb > &) friend
Foam::operator>>
template<class Gt , class Vb = CGAL::Triangulation_vertex_base_2<Gt>> Foam::Istream & Foam::operator>> (Foam::Istream & , indexedVertex< Gt, Vb > &) friend
pointPair
template<class Gt , class Vb = CGAL::Triangulation_vertex_base_2<Gt>> bool pointPair (const indexedVertex< Gt, Vb > & v0, const indexedVertex< Gt, Vb > & v1) friend
boundaryTriangle
template<class Gt , class Vb = CGAL::Triangulation_vertex_base_2<Gt>> bool boundaryTriangle (const indexedVertex< Gt, Vb > & v0, const indexedVertex< Gt, Vb > & v1, const indexedVertex< Gt, Vb > & v2) friend
outsideTriangle
template<class Gt , class Vb = CGAL::Triangulation_vertex_base_2<Gt>> bool outsideTriangle (const indexedVertex< Gt, Vb > & v0, const indexedVertex< Gt, Vb > & v1, const indexedVertex< Gt, Vb > & v2) friend
The documentation for this class was generated from the following files:
applications/utilities/mesh/generation/foamyMesh/conformalVoronoiMesh/conformalVoronoiMesh/indexedVertex/indexedVertex.H
applications/utilities/mesh/generation/foamyMesh/foamyQuadMesh/indexedVertex.H
applications/utilities/mesh/generation/foamyMesh/conformalVoronoiMesh/conformalVoronoiMesh/indexedVertex/indexedVertexI.H
applications/utilities/mesh/generation/foamyMesh/foamyQuadMesh/indexedVertexI.H