OpenFOAM: InjectionModel< CloudType > Class Template Reference
InjectionModel< CloudType > Class Template Reference abstract
Lagrangian particle models » Submodels » Kinematic » Injection
Templated injection model class.
#include <InjectionModel.H>
Public Types
enum parcelBasis { pbNumber , pbMass , pbFixed }
typedef CloudType::parcelType parcelType
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Public Member Functions
TypeName ("injectionModel")
declareRunTimeSelectionTable (autoPtr, InjectionModel, dictionary,(const dictionary &dict, CloudType &owner, const word &modelType),(dict, owner, modelType))
InjectionModel (CloudType &owner)
InjectionModel (const dictionary &dict, CloudType &owner, const word &modelName, const word &modelType)
InjectionModel (const InjectionModel< CloudType > &im)
virtual autoPtr< InjectionModel< CloudType > > clone () const =0
virtual ~InjectionModel ()=default
virtual void updateMesh ()
scalar timeStart () const
scalar volumeTotal () const
scalar massTotal () const
scalar massInjected () const
label injectorID () const
virtual scalar timeEnd () const =0
virtual label parcelsToInject (const scalar time0, const scalar time1)=0
virtual scalar volumeToInject (const scalar time0, const scalar time1)=0
virtual scalar averageParcelMass ()
label nInjections () const
label parcelsAddedTotal () const
template<class TrackCloudType >
void inject (TrackCloudType &cloud, typename CloudType::parcelType::trackingData &td)
template<class TrackCloudType >
void injectSteadyState (TrackCloudType &cloud, typename CloudType::parcelType::trackingData &td, const scalar trackTime)
virtual void setPositionAndCell (const label parcelI, const label nParcels, const scalar time, vector &position, label &cellOwner, label &tetFacei, label &tetPti)=0
virtual void setProperties (const label parcelI, const label nParcels, const scalar time, parcelType &parcel)=0
virtual bool fullyDescribed () const =0
virtual void info ()
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
virtual ~CloudSubModelBase ()=default
const CloudType & owner () const
virtual bool writeTime () const
virtual fileName localPath () const
CloudType & owner ()
virtual void write (Ostream &os) const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
subModelBase (const subModelBase &smb)
virtual ~subModelBase ()=default
const word & modelName () const
const dictionary & dict () const
const word & baseName () const
const word & modelType () const
const dictionary & coeffDict () const
const dictionary & properties () const
virtual bool defaultCoeffs (const bool printMsg) const
virtual bool active () const
virtual void cacheFields (const bool store)
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
bool getModelDict (const word &entryName, dictionary &dict) const
template<class Type >
bool getModelProperty (const word &entryName, Type &value) const
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Static Public Member Functions
static autoPtr< InjectionModel< CloudType > > New (const dictionary &dict, CloudType &owner)
static autoPtr< InjectionModel< CloudType > > New (const dictionary &dict, const word &modelName, const word &modelType, CloudType &owner)
Protected Member Functions
virtual bool validInjection (const label parcelI)=0
virtual bool prepareForNextTimeStep (const scalar time, label &newParcels, scalar &newVolumeFraction)
virtual bool findCellAtPosition (label &celli, label &tetFacei, label &tetPti, vector &position, bool errorOnNotFound=true)
virtual scalar setNumberOfParticles (const label parcels, const scalar volumeFraction, const scalar diameter, const scalar rho)
virtual void postInjectCheck (const label parcelsAdded, const scalar massAdded)
Protected Member Functions inherited from subModelBase
bool inLine () const
Protected Attributes
scalar SOI_
scalar volumeTotal_
scalar massTotal_
autoPtr< Function1< scalar > > massFlowRate_
scalar massInjected_
label nInjections_
label parcelsAddedTotal_
parcelBasis parcelBasis_
scalar nParticleFixed_
scalar time0_
scalar timeStep0_
scalar minParticlesPerParcel_
scalar delayedVolume_
label injectorID_
bool ignoreOutOfBounds_
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Protected Attributes inherited from subModelBase
const word modelName_
dictionary & properties_
const dictionary dict_
const word baseName_
const word modelType_
const dictionary coeffDict_
Additional Inherited Members
Public Attributes inherited from subModelBase
bool log
Detailed Description
template<class CloudType>
class Foam::InjectionModel< CloudType >
Templated injection model class.
The injection model nominally describes the parcel:
position
diameter
velocity In this case, the fullyDescribed() flag should be set to 0 (false). When the parcel is then added to the cloud, the remaining properties are populated using values supplied in the constant properties.
If, however, all of a parcel's properties are described in the model, the fullDescribed() flag should be set to 1 (true).
Source files
InjectionModel.H
InjectionModel.C
InjectionModelNew.C
Definition at line 69 of file InjectionModel.H.
Member Typedef Documentation
parcelType
template<class CloudType > typedef CloudType::parcelType parcelType
Definition at line 76 of file InjectionModel.H.
Member Enumeration Documentation
parcelBasis
template<class CloudType > enum parcelBasis
Enumerator
pbNumber
pbMass
pbFixed
Definition at line 83 of file InjectionModel.H.
Constructor & Destructor Documentation
InjectionModel() [1/3]
template<class CloudType > InjectionModel (CloudType & owner)
Definition at line 256 of file InjectionModel.C.
InjectionModel() [2/3]
template<class CloudType > InjectionModel (const dictionary & dict, CloudType & owner, const word & modelName, const word & modelType)
Definition at line 281 of file InjectionModel.C.
InjectionModel() [3/3]
template<class CloudType > InjectionModel (const InjectionModel< CloudType > & im)
Definition at line 381 of file InjectionModel.C.
~InjectionModel()
template<class CloudType > virtual ~InjectionModel () virtual default
Member Function Documentation
validInjection()
template<class CloudType > virtual bool validInjection (const label parcelI) protected pure virtual
Implemented in CellZoneInjection< CloudType >, ConeInjection< CloudType >, ConeNozzleInjection< CloudType >, FieldActivatedInjection< CloudType >, InflationInjection< CloudType >, InjectedParticleDistributionInjection< CloudType >, InjectedParticleInjection< CloudType >, KinematicLookupTableInjection< CloudType >, ManualInjection< CloudType >, NoInjection< CloudType >, PatchFlowRateInjection< CloudType >, PatchInjection< CloudType >, ReactingLookupTableInjection< CloudType >, ReactingMultiphaseLookupTableInjection< CloudType >, and ThermoLookupTableInjection< CloudType >.
prepareForNextTimeStep()
template<class CloudType > bool prepareForNextTimeStep (const scalar time, label & newParcels, scalar & newVolumeFraction) protected virtual
Definition at line 31 of file InjectionModel.C.
References PtrList< T >::PtrList().
findCellAtPosition()
template<class CloudType > bool findCellAtPosition (label & celli, label & tetFacei, label & tetPti, vector & position, bool errorOnNotFound = true) protected virtual
Definition at line 87 of file InjectionModel.C.
References DimensionedField< Type, GeoMesh >::mesh(), UPstream::myProcNo(), p0, and Foam::reduce().
setNumberOfParticles()
template<class CloudType > Foam::scalar setNumberOfParticles (const label parcels, const scalar volumeFraction, const scalar diameter, const scalar rho) protected virtual
Definition at line 180 of file InjectionModel.C.
postInjectCheck()
template<class CloudType > void postInjectCheck (const label parcelsAdded, const scalar massAdded) protected virtual
Definition at line 223 of file InjectionModel.C.
TypeName()
template<class CloudType > TypeName ("injectionModel")
declareRunTimeSelectionTable()
template<class CloudType > declareRunTimeSelectionTable (autoPtr , InjectionModel< CloudType > , dictionary , (const dictionary &dict, CloudType &owner, const word &modelType) , (dict, owner, modelType))
clone()
template<class CloudType > virtual autoPtr< InjectionModel< CloudType > > clone () const pure virtual
Implemented in CellZoneInjection< CloudType >, ConeInjection< CloudType >, ConeNozzleInjection< CloudType >, FieldActivatedInjection< CloudType >, InflationInjection< CloudType >, InjectedParticleDistributionInjection< CloudType >, InjectedParticleInjection< CloudType >, KinematicLookupTableInjection< CloudType >, ManualInjection< CloudType >, NoInjection< CloudType >, PatchFlowRateInjection< CloudType >, PatchInjection< CloudType >, ReactingLookupTableInjection< CloudType >, ReactingMultiphaseLookupTableInjection< CloudType >, and ThermoLookupTableInjection< CloudType >.
New() [1/2]
template<class CloudType > Foam::autoPtr< Foam::InjectionModel< CloudType > > New (const dictionary & dict, CloudType & owner) static
Definition at line 28 of file InjectionModelNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, Foam::Info, and PtrList< T >::PtrList().
New() [2/2]
template<class CloudType > Foam::autoPtr< Foam::InjectionModel< CloudType > > New (const dictionary & dict, const word & modelName, const word & modelType, CloudType & owner) static
Definition at line 57 of file InjectionModelNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, and Foam::Info.
updateMesh()
template<class CloudType > void updateMesh () virtual
Reimplemented in CellZoneInjection< CloudType >, ConeInjection< CloudType >, ConeNozzleInjection< CloudType >, FieldActivatedInjection< CloudType >, InflationInjection< CloudType >, InjectedParticleDistributionInjection< CloudType >, InjectedParticleInjection< CloudType >, KinematicLookupTableInjection< CloudType >, ManualInjection< CloudType >, PatchFlowRateInjection< CloudType >, PatchInjection< CloudType >, ReactingLookupTableInjection< CloudType >, ReactingMultiphaseLookupTableInjection< CloudType >, and ThermoLookupTableInjection< CloudType >.
Definition at line 408 of file InjectionModel.C.
timeStart()
template<class CloudType > Foam::scalar timeStart () const inline
Definition at line 27 of file InjectionModelI.H.
volumeTotal()
template<class CloudType > Foam::scalar volumeTotal () const inline
Definition at line 34 of file InjectionModelI.H.
massTotal()
template<class CloudType > Foam::scalar massTotal () const inline
Definition at line 41 of file InjectionModelI.H.
massInjected()
template<class CloudType > Foam::scalar massInjected () const inline
Definition at line 48 of file InjectionModelI.H.
injectorID()
template<class CloudType > Foam::label injectorID () const inline
Definition at line 55 of file InjectionModelI.H.
timeEnd()
template<class CloudType > virtual scalar timeEnd () const pure virtual
Implemented in CellZoneInjection< CloudType >, ConeInjection< CloudType >, ConeNozzleInjection< CloudType >, FieldActivatedInjection< CloudType >, InflationInjection< CloudType >, InjectedParticleDistributionInjection< CloudType >, InjectedParticleInjection< CloudType >, KinematicLookupTableInjection< CloudType >, ManualInjection< CloudType >, NoInjection< CloudType >, PatchFlowRateInjection< CloudType >, PatchInjection< CloudType >, ReactingLookupTableInjection< CloudType >, ReactingMultiphaseLookupTableInjection< CloudType >, and ThermoLookupTableInjection< CloudType >.
parcelsToInject()
template<class CloudType > virtual label parcelsToInject (const scalar time0, const scalar time1) pure virtual
Implemented in CellZoneInjection< CloudType >, ConeInjection< CloudType >, ConeNozzleInjection< CloudType >, FieldActivatedInjection< CloudType >, InflationInjection< CloudType >, InjectedParticleDistributionInjection< CloudType >, InjectedParticleInjection< CloudType >, KinematicLookupTableInjection< CloudType >, ManualInjection< CloudType >, NoInjection< CloudType >, PatchFlowRateInjection< CloudType >, PatchInjection< CloudType >, ReactingLookupTableInjection< CloudType >, ReactingMultiphaseLookupTableInjection< CloudType >, and ThermoLookupTableInjection< CloudType >.
volumeToInject()
template<class CloudType > virtual scalar volumeToInject (const scalar time0, const scalar time1) pure virtual
Implemented in CellZoneInjection< CloudType >, ConeInjection< CloudType >, ConeNozzleInjection< CloudType >, FieldActivatedInjection< CloudType >, InflationInjection< CloudType >, InjectedParticleDistributionInjection< CloudType >, InjectedParticleInjection< CloudType >, KinematicLookupTableInjection< CloudType >, ManualInjection< CloudType >, NoInjection< CloudType >, PatchFlowRateInjection< CloudType >, PatchInjection< CloudType >, ReactingLookupTableInjection< CloudType >, ReactingMultiphaseLookupTableInjection< CloudType >, and ThermoLookupTableInjection< CloudType >.
averageParcelMass()
template<class CloudType > Foam::scalar averageParcelMass () virtual
Definition at line 413 of file InjectionModel.C.
nInjections()
template<class CloudType > Foam::label nInjections () const inline
Definition at line 62 of file InjectionModelI.H.
parcelsAddedTotal()
template<class CloudType > Foam::label parcelsAddedTotal () const inline
Definition at line 69 of file InjectionModelI.H.
inject()
template<class CloudType > template<class TrackCloudType > void inject (TrackCloudType & cloud, typename CloudType::parcelType::trackingData & td)
Definition at line 431 of file InjectionModel.C.
References Foam::meshTools::constrainDirection(), Foam::meshTools::constrainToMeshCentre(), IOobject::db(), Foam::max(), mesh, DSMCCloud< ParcelType >::mesh(), Foam::min(), Foam::pos(), Foam::returnReduce(), polyMesh::solutionD(), and Foam::Zero.
injectSteadyState()
template<class CloudType > template<class TrackCloudType > void injectSteadyState (TrackCloudType & cloud, typename CloudType::parcelType::trackingData & td, const scalar trackTime)
Definition at line 561 of file InjectionModel.C.
References Foam::meshTools::constrainDirection(), Foam::meshTools::constrainToMeshCentre(), IOobject::db(), mesh, DSMCCloud< ParcelType >::mesh(), Foam::pos(), polyMesh::solutionD(), fvMesh::time(), and Foam::Zero.
setPositionAndCell()
template<class CloudType > virtual void setPositionAndCell (const label parcelI, const label nParcels, const scalar time, vector & position, label & cellOwner, label & tetFacei, label & tetPti) pure virtual
Implemented in CellZoneInjection< CloudType >, ConeInjection< CloudType >, ConeNozzleInjection< CloudType >, FieldActivatedInjection< CloudType >, InflationInjection< CloudType >, InjectedParticleDistributionInjection< CloudType >, InjectedParticleInjection< CloudType >, KinematicLookupTableInjection< CloudType >, ManualInjection< CloudType >, NoInjection< CloudType >, PatchFlowRateInjection< CloudType >, PatchInjection< CloudType >, ReactingLookupTableInjection< CloudType >, ReactingMultiphaseLookupTableInjection< CloudType >, and ThermoLookupTableInjection< CloudType >.
setProperties()
template<class CloudType > virtual void setProperties (const label parcelI, const label nParcels, const scalar time, parcelType & parcel) pure virtual
Implemented in CellZoneInjection< CloudType >, ConeInjection< CloudType >, ConeNozzleInjection< CloudType >, FieldActivatedInjection< CloudType >, InflationInjection< CloudType >, InjectedParticleDistributionInjection< CloudType >, InjectedParticleInjection< CloudType >, KinematicLookupTableInjection< CloudType >, ManualInjection< CloudType >, NoInjection< CloudType >, PatchFlowRateInjection< CloudType >, PatchInjection< CloudType >, ReactingLookupTableInjection< CloudType >, ReactingMultiphaseLookupTableInjection< CloudType >, and ThermoLookupTableInjection< CloudType >.
fullyDescribed()
template<class CloudType > virtual bool fullyDescribed () const pure virtual
Implemented in CellZoneInjection< CloudType >, ConeInjection< CloudType >, ConeNozzleInjection< CloudType >, FieldActivatedInjection< CloudType >, InflationInjection< CloudType >, InjectedParticleDistributionInjection< CloudType >, InjectedParticleInjection< CloudType >, KinematicLookupTableInjection< CloudType >, ManualInjection< CloudType >, NoInjection< CloudType >, PatchFlowRateInjection< CloudType >, PatchInjection< CloudType >, ReactingLookupTableInjection< CloudType >, ReactingMultiphaseLookupTableInjection< CloudType >, and ThermoLookupTableInjection< CloudType >.
info()
template<class CloudType > void info () virtual
Reimplemented from CloudSubModelBase< CloudType >.
Reimplemented in InjectedParticleDistributionInjection< CloudType >, and InjectedParticleInjection< CloudType >.
Definition at line 662 of file InjectionModel.C.
References CloudSubModelBase< CloudType >::info(), Log_, and Foam::nl.
Referenced by InjectedParticleDistributionInjection< CloudType >::info(), and InjectedParticleInjection< CloudType >::info().
Member Data Documentation
SOI_
template<class CloudType > scalar SOI_ protected
Definition at line 98 of file InjectionModel.H.
volumeTotal_
template<class CloudType > scalar volumeTotal_ protected
Definition at line 102 of file InjectionModel.H.
Referenced by ConeInjection< CloudType >::ConeInjection(), ConeNozzleInjection< CloudType >::ConeNozzleInjection(), FieldActivatedInjection< CloudType >::FieldActivatedInjection(), InflationInjection< CloudType >::InflationInjection(), InjectedParticleDistributionInjection< CloudType >::InjectedParticleDistributionInjection(), InjectedParticleInjection< CloudType >::InjectedParticleInjection(), KinematicLookupTableInjection< CloudType >::KinematicLookupTableInjection(), ManualInjection< CloudType >::ManualInjection(), PatchFlowRateInjection< CloudType >::PatchFlowRateInjection(), PatchInjection< CloudType >::PatchInjection(), ReactingLookupTableInjection< CloudType >::ReactingLookupTableInjection(), ReactingMultiphaseLookupTableInjection< CloudType >::ReactingMultiphaseLookupTableInjection(), and ThermoLookupTableInjection< CloudType >::ThermoLookupTableInjection().
massTotal_
template<class CloudType > scalar massTotal_ protected
Definition at line 105 of file InjectionModel.H.
Referenced by InflationInjection< CloudType >::InflationInjection(), InjectedParticleDistributionInjection< CloudType >::InjectedParticleDistributionInjection(), InjectedParticleInjection< CloudType >::InjectedParticleInjection(), and PatchFlowRateInjection< CloudType >::PatchFlowRateInjection().
massFlowRate_
template<class CloudType > autoPtr<Function1<scalar> > massFlowRate_ protected
Definition at line 108 of file InjectionModel.H.
massInjected_
template<class CloudType > scalar massInjected_ protected
Definition at line 111 of file InjectionModel.H.
nInjections_
template<class CloudType > label nInjections_ protected
Definition at line 117 of file InjectionModel.H.
parcelsAddedTotal_
template<class CloudType > label parcelsAddedTotal_ protected
Definition at line 120 of file InjectionModel.H.
parcelBasis_
template<class CloudType > parcelBasis parcelBasis_ protected
Definition at line 126 of file InjectionModel.H.
Referenced by InjectedParticleInjection< CloudType >::InjectedParticleInjection().
nParticleFixed_
template<class CloudType > scalar nParticleFixed_ protected
Definition at line 130 of file InjectionModel.H.
time0_
template<class CloudType > scalar time0_ protected
Definition at line 133 of file InjectionModel.H.
timeStep0_
template<class CloudType > scalar timeStep0_ protected
Definition at line 136 of file InjectionModel.H.
minParticlesPerParcel_
template<class CloudType > scalar minParticlesPerParcel_ protected
Definition at line 140 of file InjectionModel.H.
delayedVolume_
template<class CloudType > scalar delayedVolume_ protected
Definition at line 144 of file InjectionModel.H.
injectorID_
template<class CloudType > label injectorID_ protected
Definition at line 147 of file InjectionModel.H.
ignoreOutOfBounds_
template<class CloudType > bool ignoreOutOfBounds_ protected
Definition at line 151 of file InjectionModel.H.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/Kinematic/InjectionModel/InjectionModel/InjectionModel.H
src/lagrangian/intermediate/submodels/Kinematic/InjectionModel/InjectionModel/InjectionModel.C
src/lagrangian/intermediate/submodels/Kinematic/InjectionModel/InjectionModel/InjectionModelI.H
src/lagrangian/intermediate/submodels/Kinematic/InjectionModel/InjectionModel/InjectionModelNew.C