OpenFOAM: wallBoundedParticle Class Reference
wallBoundedParticle Class Reference
Particle class that tracks on triangles of boundary faces. Use trackToEdge similar to trackToFace on particle.
#include <wallBoundedParticle.H>
Classes
class iNew
class trackingData
Public Member Functions
wallBoundedParticle (const polyMesh &c, const point &position, const label celli, const label tetFacei, const label tetPti, const label meshEdgeStart, const label diagEdge)
wallBoundedParticle (const polyMesh &c, Istream &is, bool readFields=true, bool newFormat=true)
wallBoundedParticle (const wallBoundedParticle &p)
autoPtr< particle > clone () const
label meshEdgeStart () const noexcept
label diagEdge () const noexcept
template<class TrackCloudType >
scalar trackToEdge (TrackCloudType &cloud, trackingData &td, const vector &endPosition)
template<class TrackCloudType >
void patchInteraction (TrackCloudType &cloud, trackingData &td, const scalar trackFraction)
template<class TrackCloudType >
void hitProcessorPatch (TrackCloudType &cloud, trackingData &td)
template<class TrackCloudType >
void hitWallPatch (TrackCloudType &cloud, trackingData &td)
InfoProxy< wallBoundedParticle > info () const noexcept
template<class TrackCloudType >
Foam::scalar trackToEdge (TrackCloudType &cloud, trackingData &td, const vector &endPosition)
template<class TrackCloudType >
void readFields (TrackCloudType &c)
template<class TrackCloudType >
void writeFields (const TrackCloudType &c)
Public Member Functions inherited from particle< Type >
TypeName ("particle")
particle (const polyMesh &mesh, const barycentric &coordinates, const label celli, const label tetFacei, const label tetPti)
particle (const polyMesh &mesh, const vector &position, const label celli=-1)
particle (const polyMesh &mesh, const vector &position, const label celli, const label tetFacei, const label tetPti, const bool doLocate=true)
particle (const polyMesh &mesh, Istream &, const bool readFields=true, const bool newFormat=true, const bool doLocate=true)
particle (const particle &p)
particle (const particle &p, const polyMesh &mesh)
virtual ~particle ()=default
label getNewParticleID () const
const polyMesh & mesh () const noexcept
const barycentric & coordinates () const noexcept
label cell () const noexcept
label & cell () noexcept
label tetFace () const noexcept
label & tetFace () noexcept
label tetPt () const noexcept
label & tetPt () noexcept
label face () const noexcept
label & face () noexcept
scalar stepFraction () const noexcept
scalar & stepFraction () noexcept
label origProc () const noexcept
label & origProc () noexcept
label origId () const noexcept
label & origId () noexcept
Pair< scalar > stepFractionSpan () const
scalar currentTimeFraction () const
tetIndices currentTetIndices () const noexcept
barycentricTensor currentTetTransform () const
vector normal () const
bool onFace () const noexcept
bool onInternalFace () const noexcept
bool onBoundaryFace () const noexcept
label patch () const
vector position () const
void reset ()
scalar track (const vector &displacement, const scalar fraction)
scalar trackToFace (const vector &displacement, const scalar fraction)
scalar trackToTri (const vector &displacement, const scalar fraction, label &tetTriI)
scalar trackToStationaryTri (const vector &displacement, const scalar fraction, label &tetTriI)
scalar trackToMovingTri (const vector &displacement, const scalar fraction, label &tetTriI)
template<class TrackCloudType >
void hitFace (const vector &direction, TrackCloudType &cloud, trackingData &td)
template<class TrackCloudType >
void trackToAndHitFace (const vector &direction, const scalar fraction, TrackCloudType &cloud, trackingData &td)
vector deviationFromMeshCentre () const
void patchData (vector &n, vector &U) const
virtual void transformProperties (const tensor &T)
virtual void transformProperties (const vector &separation)
void prepareForParallelTransfer ()
void correctAfterParallelTransfer (const label patchi, trackingData &td)
void prepareForInteractionListReferral (const vectorTensorTransform &transform)
void correctAfterInteractionListReferral (const label celli)
label procTetPt (const polyMesh &procMesh, const label procCell, const label procTetFace) const
void autoMap (const vector &position, const mapPolyMesh &mapper)
void relocate (const point &position, const label celli=-1)
void writeProperties (Ostream &os, const wordRes &filters, const word &delim, const bool namesOnly) const
void writeCoordinates (Ostream &os) const
virtual void writePosition (Ostream &os) const
Static Public Member Functions
template<class CloudType >
static void readFields (CloudType &)
template<class CloudType >
static void writeFields (const CloudType &)
Static Public Member Functions inherited from particle< Type >
static string propertyList ()
template<class Type >
static void writePropertyName (Ostream &os, const word &name, const word &delim)
template<class Type >
static void writeProperty (Ostream &os, const word &name, const Type &value, const bool nameOnly, const word &delim, const wordRes &filters=wordRes::null())
template<class Type >
static void writeProperty (Ostream &os, const word &name, const Field< Type > &values, const bool nameOnly, const word &delim, const wordRes &filters=wordRes::null())
template<class TrackCloudType >
static void readFields (TrackCloudType &c)
template<class TrackCloudType >
static void writeFields (const TrackCloudType &c)
template<class CloudType >
static void readObjects (CloudType &c, const objectRegistry &obr)
template<class CloudType >
static void writeObjects (const CloudType &c, objectRegistry &obr)
Static Public Attributes
static const std::size_t sizeofFields_
Static Public Attributes inherited from particle< Type >
static string propertyList_ = Foam::particle::propertyList()
static label particleCount_ = 0
static bool writeLagrangianCoordinates = true
static bool writeLagrangianPositions
Protected Member Functions
edge currentEdge () const
void crossEdgeConnectedFace (const label &celli, label &tetFacei, label &tetPti, const edge &e)
void crossEdgeConnectedFace (const edge &meshEdge)
void crossDiagonalEdge ()
scalar trackFaceTri (const vector &n, const vector &endPosition, label &)
bool isTriAlongTrack (const vector &n, const point &endPosition) const
Protected Member Functions inherited from particle< Type >
void readData (Istream &is, point &position, const bool readFields, const bool newFormat, const bool doLocate)
template<class TrackCloudType >
bool hitPatch (TrackCloudType &, trackingData &)
template<class TrackCloudType >
void hitWedgePatch (TrackCloudType &, trackingData &)
template<class TrackCloudType >
void hitSymmetryPlanePatch (TrackCloudType &, trackingData &)
template<class TrackCloudType >
void hitSymmetryPatch (TrackCloudType &, trackingData &)
template<class TrackCloudType >
void hitCyclicPatch (TrackCloudType &, trackingData &)
template<class TrackCloudType >
void hitCyclicAMIPatch (TrackCloudType &, trackingData &, const vector &)
template<class TrackCloudType >
void hitCyclicACMIPatch (TrackCloudType &, trackingData &, const vector &)
template<class TrackCloudType >
void hitProcessorPatch (TrackCloudType &, trackingData &)
template<class TrackCloudType >
void hitWallPatch (TrackCloudType &, trackingData &)
template<class TrackCloudType >
void hitBoundaryFace (const vector &direction, TrackCloudType &cloud, trackingData &td)
Protected Attributes
point localPosition_
label meshEdgeStart_
label diagEdge_
Friends
Ostream & operator<< (Ostream &, const wallBoundedParticle &)
Ostream & operator<< (Ostream &, const InfoProxy< wallBoundedParticle > &)
Detailed Description
Particle class that tracks on triangles of boundary faces. Use trackToEdge similar to trackToFace on particle.
Source files
wallBoundedParticle.H
wallBoundedParticle.C
wallBoundedParticleTemplates.C
Definition at line 58 of file wallBoundedParticle.H.
Constructor & Destructor Documentation
wallBoundedParticle() [1/3]
wallBoundedParticle (const polyMesh & c, const point & position, const label celli, const label tetFacei, const label tetPti, const label meshEdgeStart, const label diagEdge)
Definition at line 404 of file wallBoundedParticle.C.
wallBoundedParticle() [2/3]
wallBoundedParticle (const polyMesh & c, Istream & is, bool readFields = true, bool newFormat = true)
Definition at line 422 of file wallBoundedParticle.C.
References IOstreamOption::ASCII, VectorSpace< Form, Cmpt, Ncmpts >::data(), wallBoundedParticle::diagEdge_, FUNCTION_NAME, wallBoundedParticle::localPosition_, wallBoundedParticle::meshEdgeStart_, VectorSpace< Form, Cmpt, Ncmpts >::nComponents, wallBoundedParticle::readFields(), Foam::readRawLabel(), and wallBoundedParticle::sizeofFields_.
wallBoundedParticle() [3/3]
wallBoundedParticle (const wallBoundedParticle & p)
Definition at line 460 of file wallBoundedParticle.C.
Member Function Documentation
currentEdge()
Foam::edge currentEdge () const protected
Definition at line 34 of file wallBoundedParticle.C.
References Foam::abort(), wallBoundedParticle::diagEdge_, f(), Foam::FatalError, FatalErrorInFunction, wallBoundedParticle::info(), particle< Type >::mesh(), wallBoundedParticle::meshEdgeStart_, UPtrList< T >::size(), and particle< Type >::tetFace().
crossEdgeConnectedFace() [1/2]
void crossEdgeConnectedFace (const label & celli, label & tetFacei, label & tetPti, const edge & e) protected
Definition at line 75 of file wallBoundedParticle.C.
References primitiveMesh::cells(), e, UList< T >::end(), f(), polyMesh::faces(), mesh, Foam::neg(), pFaces, UPtrList< T >::size(), and polyMesh::tetBasePtIs().
crossEdgeConnectedFace() [2/2]
void crossEdgeConnectedFace (const edge & meshEdge) protected
Definition at line 183 of file wallBoundedParticle.C.
References Foam::abort(), f(), polyMesh::faces(), Foam::FatalError, FatalErrorInFunction, UList< T >::find(), mesh, and UList< T >::rcIndex().
crossDiagonalEdge()
void crossDiagonalEdge () protected
Definition at line 232 of file wallBoundedParticle.C.
References Foam::abort(), f(), polyMesh::faces(), Foam::FatalError, FatalErrorInFunction, UList< T >::fcIndex(), mesh, and UList< T >::rcIndex().
trackFaceTri()
Foam::scalar trackFaceTri (const vector & n, const vector & endPosition, label & minEdgei) protected
Definition at line 278 of file wallBoundedParticle.C.
References FixedList< T, N >::fcIndex(), forAll, Foam::mag(), mesh, n, polyMesh::points(), and s().
isTriAlongTrack()
bool isTriAlongTrack (const vector & n, const point & endPosition) const protected
Definition at line 357 of file wallBoundedParticle.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, mesh, n, and polyMesh::points().
clone()
autoPtr< particle > clone () const inline virtual
Reimplemented from particle< Type >.
Reimplemented in wallBoundedStreamLineParticle.
Definition at line 175 of file wallBoundedParticle.H.
meshEdgeStart()
label meshEdgeStart () const inline noexcept
Definition at line 211 of file wallBoundedParticle.H.
References wallBoundedParticle::meshEdgeStart_.
diagEdge()
label diagEdge () const inline noexcept
Definition at line 214 of file wallBoundedParticle.H.
References wallBoundedParticle::diagEdge_.
trackToEdge() [1/2]
template<class TrackCloudType > scalar trackToEdge (TrackCloudType & cloud, trackingData & td, const vector & endPosition)
Referenced by wallBoundedStreamLineParticle::move().
patchInteraction()
template<class TrackCloudType > void patchInteraction (TrackCloudType & cloud, trackingData & td, const scalar trackFraction)
Definition at line 27 of file wallBoundedParticleTemplates.C.
References particle< Type >::face(), particle< Type >::mesh(), p, and particle< Type >::patch().
hitProcessorPatch()
template<class TrackCloudType > void hitProcessorPatch (TrackCloudType & cloud, trackingData & td)
Definition at line 374 of file wallBoundedParticleTemplates.C.
References f(), polyMesh::faces(), mesh, and UList< T >::size().
hitWallPatch()
template<class TrackCloudType > void hitWallPatch (TrackCloudType & cloud, trackingData & td)
Definition at line 403 of file wallBoundedParticleTemplates.C.
info()
InfoProxy< wallBoundedParticle > info () const inline noexcept
Definition at line 262 of file wallBoundedParticle.H.
Referenced by wallBoundedParticle::currentEdge().
readFields() [1/2]
template<class CloudType > static void readFields (CloudType &) static
Referenced by wallBoundedStreamLineParticle::readFields(), and wallBoundedParticle::wallBoundedParticle().
writeFields() [1/2]
template<class CloudType > static void writeFields (const CloudType &) static
Referenced by wallBoundedStreamLineParticle::writeFields().
trackToEdge() [2/2]
template<class TrackCloudType > Foam::scalar trackToEdge (TrackCloudType & cloud, trackingData & td, const vector & endPosition)
Definition at line 72 of file wallBoundedParticleTemplates.C.
References Foam::abort(), f(), primitiveMesh::faceCentres(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), polyMesh::faces(), Foam::FatalError, FatalErrorInFunction, UList< T >::fcIndex(), Foam::mag(), mesh, meshBb(), n, path(), points, polyMesh::points(), UList< T >::rcIndex(), UList< T >::size(), and triFace::unitNormal().
readFields() [2/2]
template<class TrackCloudType > void readFields (TrackCloudType & c)
Definition at line 412 of file wallBoundedParticleTemplates.C.
References IOobjectOption::MUST_READ, p, particle< Type >::readFields(), and UPtrList< T >::size().
writeFields() [2/2]
template<class TrackCloudType > void writeFields (const TrackCloudType & c)
Definition at line 452 of file wallBoundedParticleTemplates.C.
References IOobjectOption::NO_READ, p, UPtrList< T >::size(), and particle< Type >::writeFields().
Friends And Related Symbol Documentation
operator<< [1/2]
Ostream & operator<< (Ostream & , const wallBoundedParticle &) friend
operator<< [2/2]
Ostream & operator<< (Ostream & , const InfoProxy< wallBoundedParticle > &) friend
Member Data Documentation
localPosition_
point localPosition_ protected
Definition at line 94 of file wallBoundedParticle.H.
Referenced by wallBoundedStreamLineParticle::move(), and wallBoundedParticle::wallBoundedParticle().
meshEdgeStart_
label meshEdgeStart_ protected
Definition at line 102 of file wallBoundedParticle.H.
Referenced by wallBoundedParticle::currentEdge(), wallBoundedParticle::meshEdgeStart(), and wallBoundedParticle::wallBoundedParticle().
diagEdge_
label diagEdge_ protected
Definition at line 109 of file wallBoundedParticle.H.
Referenced by wallBoundedParticle::currentEdge(), wallBoundedParticle::diagEdge(), and wallBoundedParticle::wallBoundedParticle().
sizeofFields_
const std::size_t sizeofFields_ static
Definition at line 145 of file wallBoundedParticle.H.
Referenced by Foam::operator<<(), and wallBoundedParticle::wallBoundedParticle().
The documentation for this class was generated from the following files:
src/functionObjects/field/wallBoundedStreamLine/wallBoundedParticle.H
src/functionObjects/field/wallBoundedStreamLine/wallBoundedParticle.C
src/functionObjects/field/wallBoundedStreamLine/wallBoundedParticleTemplates.C