OpenFOAM: waveSurfacePressureFvPatchScalarField Class Reference
waveSurfacePressureFvPatchScalarField Class Reference
Boundary conditions » Inlet
This is a pressure boundary condition, whose value is calculated as the hydrostatic pressure based on a given displacement:
#include <waveSurfacePressureFvPatchScalarField.H>
Public Types
enum ddtSchemeType { tsEuler , tsCrankNicolson , tsBackward }
Public Member Functions
TypeName ("waveSurfacePressure")
waveSurfacePressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
waveSurfacePressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
waveSurfacePressureFvPatchScalarField (const waveSurfacePressureFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
waveSurfacePressureFvPatchScalarField (const waveSurfacePressureFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
waveSurfacePressureFvPatchScalarField (const waveSurfacePressureFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
This is a pressure boundary condition, whose value is calculated as the hydrostatic pressure based on a given displacement:
= density [kg/m3]
= acceleration due to gravity [m/s2]
= wave amplitude [m]
The wave amplitude is updated as part of the calculation, derived from the local volumetric flux.
Usage
Property Description Required Default value
phi flux field name no phi
rho density field name no rho
zeta wave amplitude field name no zeta
Example of the boundary condition specification:
    <patchName>
    {
        type            waveSurfacePressure;
        phi             phi;
        rho             rho;
        zeta            zeta;
        value           uniform 0;  // place holder
    }
The density field is only required if the flux is mass-based as opposed to volumetric-based.
See also
Foam::fixedValueFvPatchField
Source files
waveSurfacePressureFvPatchScalarField.H
waveSurfacePressureFvPatchScalarField.C
Definition at line 122 of file waveSurfacePressureFvPatchScalarField.H.
Member Enumeration Documentation
ddtSchemeType
enum ddtSchemeType
Enumerator
tsEuler
tsCrankNicolson
tsBackward
Definition at line 131 of file waveSurfacePressureFvPatchScalarField.H.
Constructor & Destructor Documentation
waveSurfacePressureFvPatchScalarField() [1/5]
waveSurfacePressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 57 of file waveSurfacePressureFvPatchScalarField.C.
waveSurfacePressureFvPatchScalarField() [2/5]
waveSurfacePressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 71 of file waveSurfacePressureFvPatchScalarField.C.
waveSurfacePressureFvPatchScalarField() [3/5]
waveSurfacePressureFvPatchScalarField (const waveSurfacePressureFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 86 of file waveSurfacePressureFvPatchScalarField.C.
waveSurfacePressureFvPatchScalarField() [4/5]
waveSurfacePressureFvPatchScalarField (const waveSurfacePressureFvPatchScalarField & wspsf)
Definition at line 102 of file waveSurfacePressureFvPatchScalarField.C.
waveSurfacePressureFvPatchScalarField() [5/5]
waveSurfacePressureFvPatchScalarField (const waveSurfacePressureFvPatchScalarField & wspsf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 115 of file waveSurfacePressureFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("waveSurfacePressure")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 196 of file waveSurfacePressureFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 212 of file waveSurfacePressureFvPatchScalarField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 131 of file waveSurfacePressureFvPatchScalarField.C.
References Foam::abort(), GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), Foam::dimMass, Foam::dimTime, Foam::endl(), Foam::FatalError, FatalErrorInFunction, g, Foam::gMax(), Foam::gMin(), Foam::Info, DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), gravity::New(), Foam::nl, GeometricField< Type, PatchField, GeoMesh >::oldTime(), Foam::operator==(), and phi.
write()
void write (Ostream & os) const virtual
Definition at line 219 of file waveSurfacePressureFvPatchScalarField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntryIfDifferent(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/waveSurfacePressure/waveSurfacePressureFvPatchScalarField.H
src/finiteVolume/fields/fvPatchFields/derived/waveSurfacePressure/waveSurfacePressureFvPatchScalarField.C