OpenFOAM: SimplifiedDynamicFvMesh< DynamicMeshType > Class Template Reference
SimplifiedDynamicFvMesh< DynamicMeshType > Class Template Reference
#include <simplifiedDynamicFvMesh.H>
Public Member Functions
ClassNameNoDebug (DynamicMeshType::typeName_.c_str())
SimplifiedDynamicFvMesh (const Time &runTime, const word &regionName)
virtual bool update ()
Public Member Functions inherited from simplifiedDynamicFvMeshBase
TypeName ("simplifiedDynamicFvMeshBase")
declareRunTimeSelectionTable (autoPtr, dynamicFvMesh, time,(const Time &runTime, const word &regionName),(runTime, regionName))
simplifiedDynamicFvMeshBase ()
virtual ~simplifiedDynamicFvMeshBase ()=default
Public Member Functions inherited from columnFvMeshInfo
ClassName ("columnFvMeshInfo")
columnFvMeshInfo (const Time &runTime, const word &regionName)
Additional Inherited Members
Static Public Member Functions inherited from simplifiedDynamicFvMeshBase
static autoPtr< dynamicFvMesh > New (const IOobject &io)
Protected Member Functions inherited from columnFvMeshInfo
void addLocalPatches (fvMesh &mesh) const
void initialiseZones (fvMesh &mesh)
Protected Attributes inherited from columnFvMeshInfo
const word regionName_
const word localInstance_
bool createFromMesh_
pointField points1D_
faceList faces1D_
labelList owner1D_
labelList neighbour1D_
dictionary patchEntries_
label nPatchWithFace_
Detailed Description
template<class DynamicMeshType>
class Foam::simplifiedMeshes::SimplifiedDynamicFvMesh< DynamicMeshType >
Definition at line 90 of file simplifiedDynamicFvMesh.H.
Constructor & Destructor Documentation
SimplifiedDynamicFvMesh()
template<class DynamicMeshType > SimplifiedDynamicFvMesh (const Time & runTime, const word & regionName)
Definition at line 24 of file simplifiedDynamicFvMeshTemplates.C.
References columnFvMeshInfo::addLocalPatches(), columnFvMeshInfo::initialiseZones(), IOobjectOption::MUST_READ, regIOobject::read(), and IOobjectOption::readOpt().
Member Function Documentation
ClassNameNoDebug()
template<class DynamicMeshType > ClassNameNoDebug (DynamicMeshType::typeName_. c_str())
update()
template<class DynamicMeshType > virtual bool update () inline virtual
Definition at line 105 of file simplifiedDynamicFvMesh.H.
The documentation for this class was generated from the following files:
src/dynamicFvMesh/simplifiedDynamicFvMesh/simplifiedDynamicFvMesh.H
src/dynamicFvMesh/simplifiedDynamicFvMesh/simplifiedDynamicFvMeshTemplates.C