OpenFOAM: refinementDistanceData Class Reference
refinementDistanceData Class Reference
Transfers refinement levels such that slow transition between levels is maintained. Used in FaceCellWave.
#include <refinementDistanceData.H>
Public Member Functions
refinementDistanceData ()
refinementDistanceData (const scalar level0Size, const point &origin, const label level)
scalar level0Size () const
scalar & level0Size ()
const point & origin () const
point & origin ()
label originLevel () const
label & originLevel ()
label wantedLevel (const point &pt) const
template<class TrackingData >
bool valid (TrackingData &) const
template<class TrackingData >
bool sameGeometry (const polyMesh &, const refinementDistanceData &, const scalar, TrackingData &) const
template<class TrackingData >
void leaveDomain (const polyMesh &, const polyPatch &, const label patchFacei, const point &faceCentre, TrackingData &)
template<class TrackingData >
void enterDomain (const polyMesh &, const polyPatch &, const label patchFacei, const point &faceCentre, TrackingData &)
template<class TrackingData >
void transform (const polyMesh &, const tensor &, TrackingData &)
template<class TrackingData >
bool updateCell (const polyMesh &, const label thisCelli, const label neighbourFacei, const refinementDistanceData &neighbourInfo, const scalar tol, TrackingData &)
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFacei, const label neighbourCelli, const refinementDistanceData &neighbourInfo, const scalar tol, TrackingData &)
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFacei, const refinementDistanceData &neighbourInfo, const scalar tol, TrackingData &)
template<class TrackingData >
bool equal (const refinementDistanceData &, TrackingData &) const
bool operator== (const refinementDistanceData &) const
bool operator!= (const refinementDistanceData &) const
Friends
Ostream & operator<< (Ostream &, const refinementDistanceData &)
Istream & operator>> (Istream &, refinementDistanceData &)
Detailed Description
Transfers refinement levels such that slow transition between levels is maintained. Used in FaceCellWave.
Source files
refinementDistanceData.H
refinementDistanceDataI.H
refinementDistanceData.C
Definition at line 59 of file refinementDistanceData.H.
Constructor & Destructor Documentation
refinementDistanceData() [1/2]
refinementDistanceData () inline
Definition at line 119 of file refinementDistanceDataI.H.
refinementDistanceData() [2/2]
refinementDistanceData (const scalar level0Size, const point & origin, const label level) inline
Definition at line 125 of file refinementDistanceDataI.H.
Member Function Documentation
level0Size() [1/2]
scalar level0Size () const inline
Definition at line 104 of file refinementDistanceData.H.
level0Size() [2/2]
scalar & level0Size () inline
Definition at line 108 of file refinementDistanceData.H.
origin() [1/2]
const point & origin () const inline
Definition at line 113 of file refinementDistanceData.H.
origin() [2/2]
point & origin () inline
Definition at line 117 of file refinementDistanceData.H.
originLevel() [1/2]
label originLevel () const inline
Definition at line 122 of file refinementDistanceData.H.
originLevel() [2/2]
label & originLevel () inline
Definition at line 126 of file refinementDistanceData.H.
wantedLevel()
Foam::label wantedLevel (const point & pt) const inline
Definition at line 27 of file refinementDistanceDataI.H.
References Foam::magSqr(), and Foam::sqr().
valid()
template<class TrackingData > bool valid (TrackingData & td) const inline
Definition at line 141 of file refinementDistanceDataI.H.
Referenced by refinementDistanceData::equal().
sameGeometry()
template<class TrackingData > bool sameGeometry (const polyMesh & , const refinementDistanceData & , const scalar , TrackingData & td) const inline
Definition at line 149 of file refinementDistanceDataI.H.
leaveDomain()
template<class TrackingData > void leaveDomain (const polyMesh & , const polyPatch & patch, const label patchFacei, const point & faceCentre, TrackingData & td) inline
Definition at line 162 of file refinementDistanceDataI.H.
enterDomain()
template<class TrackingData > void enterDomain (const polyMesh & , const polyPatch & patch, const label patchFacei, const point & faceCentre, TrackingData & td) inline
Definition at line 189 of file refinementDistanceDataI.H.
transform()
template<class TrackingData > void transform (const polyMesh & , const tensor & rotTensor, TrackingData & td) inline
Definition at line 176 of file refinementDistanceDataI.H.
References Foam::transform().
updateCell()
template<class TrackingData > bool updateCell (const polyMesh & mesh, const label thisCelli, const label neighbourFacei, const refinementDistanceData & neighbourInfo, const scalar tol, TrackingData & td) inline
Definition at line 205 of file refinementDistanceDataI.H.
References primitiveMesh::cellCentres(), mesh, Foam::pos(), and update().
updateFace() [1/2]
template<class TrackingData > bool updateFace (const polyMesh & mesh, const label thisFacei, const label neighbourCelli, const refinementDistanceData & neighbourInfo, const scalar tol, TrackingData & td) inline
Definition at line 223 of file refinementDistanceDataI.H.
References primitiveMesh::faceCentres(), mesh, Foam::pos(), and update().
updateFace() [2/2]
template<class TrackingData > bool updateFace (const polyMesh & mesh, const label thisFacei, const refinementDistanceData & neighbourInfo, const scalar tol, TrackingData & td) inline
Definition at line 241 of file refinementDistanceDataI.H.
References primitiveMesh::faceCentres(), mesh, Foam::pos(), and update().
equal()
template<class TrackingData > bool equal (const refinementDistanceData & rhs, TrackingData & td) const inline
Definition at line 257 of file refinementDistanceDataI.H.
References Foam::operator==(), and refinementDistanceData::valid().
operator==()
bool operator== (const refinementDistanceData & rhs) const inline
Definition at line 276 of file refinementDistanceDataI.H.
operator!=()
bool operator!= (const refinementDistanceData & rhs) const inline
Definition at line 288 of file refinementDistanceDataI.H.
Friends And Related Symbol Documentation
operator<<
Ostream & operator<< (Ostream & , const refinementDistanceData &) friend
operator>>
Istream & operator>> (Istream & , refinementDistanceData &) friend
The documentation for this class was generated from the following files:
src/dynamicMesh/polyTopoChange/polyTopoChange/refinementDistanceData.H
src/dynamicMesh/polyTopoChange/polyTopoChange/refinementDistanceDataI.H