OpenFOAM: cellPointWeightWallModified Class Reference
cellPointWeightWallModified Class Reference
Foam::cellPointWeightWallModified.
#include <cellPointWeightWallModified.H>
Public Member Functions
cellPointWeightWallModified (const polyMesh &mesh, const vector &position, const label celli, const label facei=-1)
Public Member Functions inherited from cellPointWeight
cellPointWeight (const polyMesh &mesh, const vector &position, const label celli, const label facei=-1)
label cell () const noexcept
const barycentric & weights () const noexcept
const triFace & faceVertices () const noexcept
Static Public Member Functions
static bool onWall (const polyMesh &mesh, const label facei)
Additional Inherited Members
Static Public Attributes inherited from cellPointWeight
static int debug
static scalar tol
Protected Member Functions inherited from cellPointWeight
void findTetrahedron (const polyMesh &mesh, const vector &position, const label celli)
void findTriangle (const polyMesh &mesh, const vector &position, const label facei)
Protected Attributes inherited from cellPointWeight
const label celli_
barycentric weights_
triFace faceVertices_
Detailed Description
Foam::cellPointWeightWallModified.
Source files
cellPointWeightWallModified.H
cellPointWeightWallModified.C
Definition at line 47 of file cellPointWeightWallModified.H.
Constructor & Destructor Documentation
cellPointWeightWallModified()
cellPointWeightWallModified (const polyMesh & mesh, const vector & position, const label celli, const label facei = -1)
Definition at line 52 of file cellPointWeightWallModified.C.
References mesh, cellPointWeightWallModified::onWall(), and cellPointWeight::weights_.
Member Function Documentation
onWall()
bool onWall (const polyMesh & mesh, const label facei) static
Definition at line 29 of file cellPointWeightWallModified.C.
References mesh.
Referenced by cellPointWeightWallModified::cellPointWeightWallModified(), and interpolationCellPointWallModified< Type >::interpolate().
The documentation for this class was generated from the following files:
src/finiteVolume/interpolation/interpolation/interpolationCellPointWallModified/cellPointWeightWallModified.H
src/finiteVolume/interpolation/interpolation/interpolationCellPointWallModified/cellPointWeightWallModified.C