OpenFOAM: primitiveMeshGeometry Class Reference
primitiveMeshGeometry Class Reference
Updateable mesh geometry + checking routines.
#include <primitiveMeshGeometry.H>
Public Member Functions
ClassName ("primitiveMeshGeometry")
primitiveMeshGeometry (const primitiveMesh &)
const primitiveMesh & mesh () const
const vectorField & faceAreas () const
const vectorField & faceCentres () const
const vectorField & cellCentres () const
const scalarField & cellVolumes () const
void correct ()
void correct (const pointField &p, const labelList &changedFaces)
labelList affectedCells (const labelList &changedFaces) const
bool checkFaceDotProduct (const bool report, const scalar orthWarn, const labelList &checkFaces, labelHashSet *setPtr) const
bool checkFacePyramids (const bool report, const scalar minPyrVol, const pointField &p, const labelList &checkFaces, labelHashSet *setPtr) const
bool checkFaceSkewness (const bool report, const scalar internalSkew, const scalar boundarySkew, const labelList &checkFaces, labelHashSet *setPtr) const
bool checkFaceWeights (const bool report, const scalar warnWeight, const labelList &checkFaces, labelHashSet *setPtr) const
bool checkFaceAngles (const bool report, const scalar maxDeg, const pointField &p, const labelList &checkFaces, labelHashSet *setPtr) const
bool checkFaceTwist (const bool report, const scalar minTwist, const pointField &p, const labelList &checkFaces, labelHashSet *setPtr) const
bool checkFaceArea (const bool report, const scalar minArea, const labelList &checkFaces, labelHashSet *setPtr) const
bool checkCellDeterminant (const bool report, const scalar warnDet, const labelList &checkFaces, const labelList &affectedCells, labelHashSet *setPtr) const
Static Public Member Functions
static bool checkFaceDotProduct (const bool report, const scalar orthWarn, const primitiveMesh &, const vectorField &cellCentres, const vectorField &faceAreas, const labelList &checkFaces, labelHashSet *setPtr)
static bool checkFacePyramids (const bool report, const scalar minPyrVol, const primitiveMesh &, const vectorField &cellCentres, const pointField &p, const labelList &checkFaces, labelHashSet *)
static bool checkFaceSkewness (const bool report, const scalar internalSkew, const scalar boundarySkew, const primitiveMesh &mesh, const vectorField &cellCentres, const vectorField &faceCentres, const vectorField &faceAreas, const labelList &checkFaces, labelHashSet *setPtr)
static bool checkFaceWeights (const bool report, const scalar warnWeight, const primitiveMesh &mesh, const vectorField &cellCentres, const vectorField &faceCentres, const vectorField &faceAreas, const labelList &checkFaces, labelHashSet *setPtr)
static bool checkFaceAngles (const bool report, const scalar maxDeg, const primitiveMesh &mesh, const vectorField &faceAreas, const pointField &p, const labelList &checkFaces, labelHashSet *setPtr)
static bool checkFaceTwist (const bool report, const scalar minTwist, const primitiveMesh &, const vectorField &faceAreas, const vectorField &faceCentres, const pointField &p, const labelList &checkFaces, labelHashSet *setPtr)
static bool checkFaceArea (const bool report, const scalar minArea, const primitiveMesh &, const vectorField &faceAreas, const labelList &checkFaces, labelHashSet *setPtr)
static bool checkCellDeterminant (const bool report, const scalar minDet, const primitiveMesh &, const vectorField &faceAreas, const labelList &checkFaces, const labelList &affectedCells, labelHashSet *setPtr)
Detailed Description
Updateable mesh geometry + checking routines.
Source files
primitiveMeshGeometry.H
primitiveMeshGeometry.C
Definition at line 47 of file primitiveMeshGeometry.H.
Constructor & Destructor Documentation
primitiveMeshGeometry()
primitiveMeshGeometry (const primitiveMesh & mesh)
Definition at line 206 of file primitiveMeshGeometry.C.
References primitiveMeshGeometry::correct().
Member Function Documentation
ClassName()
ClassName ("primitiveMeshGeometry")
mesh()
const primitiveMesh & mesh () const inline
Definition at line 96 of file primitiveMeshGeometry.H.
faceAreas()
const vectorField & faceAreas () const inline
Definition at line 101 of file primitiveMeshGeometry.H.
faceCentres()
const vectorField & faceCentres () const inline
Definition at line 105 of file primitiveMeshGeometry.H.
cellCentres()
const vectorField & cellCentres () const inline
Definition at line 109 of file primitiveMeshGeometry.H.
cellVolumes()
const scalarField & cellVolumes () const inline
Definition at line 113 of file primitiveMeshGeometry.H.
correct() [1/2]
void correct ()
Definition at line 219 of file primitiveMeshGeometry.C.
Referenced by primitiveMeshGeometry::primitiveMeshGeometry().
correct() [2/2]
void correct (const pointField & p, const labelList & changedFaces)
Definition at line 228 of file primitiveMeshGeometry.C.
References p.
affectedCells()
Foam::labelList affectedCells (const labelList & changedFaces) const
Definition at line 181 of file primitiveMeshGeometry.C.
References HashSet< Key, Hash >::insert(), UPtrList< T >::size(), and HashTable< T, Key, Hash >::toc().
checkFaceDotProduct() [1/2]
bool checkFaceDotProduct (const bool report, const scalar orthWarn, const primitiveMesh & mesh, const vectorField & cellCentres, const vectorField & faceAreas, const labelList & checkFaces, labelHashSet * setPtr) static
Definition at line 241 of file primitiveMeshGeometry.C.
References Foam::acos(), Foam::cos(), Foam::degToRad(), Foam::endl(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), forAll, Foam::Info, primitiveMesh::isInternalFace(), Foam::mag(), mesh, Foam::Pout, Foam::radToDeg(), Foam::reduce(), Foam::returnReduce(), s(), SeriousErrorInFunction, UPtrList< T >::size(), and WarningInFunction.
checkFacePyramids() [1/2]
bool checkFacePyramids (const bool report, const scalar minPyrVol, const primitiveMesh & mesh, const vectorField & cellCentres, const pointField & p, const labelList & checkFaces, labelHashSet * setPtr) static
Definition at line 381 of file primitiveMeshGeometry.C.
References primitiveMesh::cells(), Foam::endl(), f(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), polyMesh::faces(), Foam::Info, primitiveMesh::isInternalFace(), mesh, p, Foam::Pout, Foam::reduce(), and SeriousErrorInFunction.
checkFaceSkewness() [1/2]
bool checkFaceSkewness (const bool report, const scalar internalSkew, const scalar boundarySkew, const primitiveMesh & mesh, const vectorField & cellCentres, const vectorField & faceCentres, const vectorField & faceAreas, const labelList & checkFaces, labelHashSet * setPtr) static
Definition at line 489 of file primitiveMeshGeometry.C.
References Foam::endl(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), Foam::Info, primitiveMesh::isInternalFace(), Foam::mag(), mesh, Foam::nl, Foam::normalised(), Foam::Pout, Foam::reduce(), and WarningInFunction.
checkFaceWeights() [1/2]
bool checkFaceWeights (const bool report, const scalar warnWeight, const primitiveMesh & mesh, const vectorField & cellCentres, const vectorField & faceCentres, const vectorField & faceAreas, const labelList & checkFaces, labelHashSet * setPtr) static
Definition at line 624 of file primitiveMeshGeometry.C.
References Foam::endl(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), Foam::Info, primitiveMesh::isInternalFace(), Foam::mag(), mesh, Foam::min(), Foam::nl, Foam::Pout, Foam::reduce(), and WarningInFunction.
checkFaceAngles() [1/2]
bool checkFaceAngles (const bool report, const scalar maxDeg, const primitiveMesh & mesh, const vectorField & faceAreas, const pointField & p, const labelList & checkFaces, labelHashSet * setPtr) static
Definition at line 706 of file primitiveMeshGeometry.C.
References Foam::abort(), Foam::asin(), Foam::degToRad(), Foam::endl(), f(), polyMesh::faces(), Foam::FatalError, FatalErrorInFunction, UList< T >::first(), forAll, Foam::Info, UList< T >::last(), Foam::mag(), Foam::max(), mesh, Foam::min(), Foam::normalised(), p, Foam::radToDeg(), Foam::reduce(), Foam::sin(), and WarningInFunction.
checkFaceTwist() [1/2]
bool checkFaceTwist (const bool report, const scalar minTwist, const primitiveMesh & mesh, const vectorField & faceAreas, const vectorField & faceCentres, const pointField & p, const labelList & checkFaces, labelHashSet * setPtr) static
Definition at line 959 of file primitiveMeshGeometry.C.
References Foam::abort(), triangle< Point, PointRef >::areaNormal(), Foam::endl(), f(), polyMesh::faces(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::Info, Foam::mag(), mesh, Foam::nl, p, Foam::reduce(), UList< T >::size(), and WarningInFunction.
checkFaceArea() [1/2]
bool checkFaceArea (const bool report, const scalar minArea, const primitiveMesh & mesh, const vectorField & faceAreas, const labelList & checkFaces, labelHashSet * setPtr) static
Definition at line 1063 of file primitiveMeshGeometry.C.
References Foam::endl(), Foam::Info, Foam::mag(), Foam::nl, Foam::reduce(), and WarningInFunction.
checkCellDeterminant() [1/2]
bool checkCellDeterminant (const bool report, const scalar minDet, const primitiveMesh & mesh, const vectorField & faceAreas, const labelList & checkFaces, const labelList & affectedCells, labelHashSet * setPtr) static
Definition at line 1120 of file primitiveMeshGeometry.C.
References cells, primitiveMesh::cells(), Foam::det(), Foam::endl(), forAll, Foam::Info, Foam::mag(), mesh, Foam::min(), Foam::nl, Foam::reduce(), WarningInFunction, and Foam::Zero.
checkFaceDotProduct() [2/2]
bool checkFaceDotProduct (const bool report, const scalar orthWarn, const labelList & checkFaces, labelHashSet * setPtr) const
Definition at line 1219 of file primitiveMeshGeometry.C.
checkFacePyramids() [2/2]
bool checkFacePyramids (const bool report, const scalar minPyrVol, const pointField & p, const labelList & checkFaces, labelHashSet * setPtr) const
Definition at line 1240 of file primitiveMeshGeometry.C.
References p.
checkFaceSkewness() [2/2]
bool checkFaceSkewness (const bool report, const scalar internalSkew, const scalar boundarySkew, const labelList & checkFaces, labelHashSet * setPtr) const
Definition at line 1262 of file primitiveMeshGeometry.C.
checkFaceWeights() [2/2]
bool checkFaceWeights (const bool report, const scalar warnWeight, const labelList & checkFaces, labelHashSet * setPtr) const
Definition at line 1286 of file primitiveMeshGeometry.C.
checkFaceAngles() [2/2]
bool checkFaceAngles (const bool report, const scalar maxDeg, const pointField & p, const labelList & checkFaces, labelHashSet * setPtr) const
Definition at line 1308 of file primitiveMeshGeometry.C.
References p.
checkFaceTwist() [2/2]
bool checkFaceTwist (const bool report, const scalar minTwist, const pointField & p, const labelList & checkFaces, labelHashSet * setPtr) const
Definition at line 1353 of file primitiveMeshGeometry.C.
References p.
checkFaceArea() [2/2]
bool checkFaceArea (const bool report, const scalar minArea, const labelList & checkFaces, labelHashSet * setPtr) const
Definition at line 1376 of file primitiveMeshGeometry.C.
checkCellDeterminant() [2/2]
bool checkCellDeterminant (const bool report, const scalar warnDet, const labelList & checkFaces, const labelList & affectedCells, labelHashSet * setPtr) const
Definition at line 1396 of file primitiveMeshGeometry.C.
The documentation for this class was generated from the following files:
src/meshTools/primitiveMeshGeometry/primitiveMeshGeometry.H
src/meshTools/primitiveMeshGeometry/primitiveMeshGeometry.C