OpenFOAM: AnisothermalPhaseModel< BasePhaseModel > Class Template Reference
AnisothermalPhaseModel< BasePhaseModel > Class Template Reference
Class which represents a phase for which the temperature (strictly energy) varies. Returns the energy equation and corrects the thermodynamic model.
#include <AnisothermalPhaseModel.H>
Public Member Functions
AnisothermalPhaseModel (const phaseSystem &fluid, const word &phaseName, const label index)
virtual ~AnisothermalPhaseModel ()=default
virtual void correctThermo ()
virtual bool isothermal () const
virtual tmp< fvScalarMatrix > heEqn ()
Detailed Description
template<class BasePhaseModel>
class Foam::AnisothermalPhaseModel< BasePhaseModel >
Class which represents a phase for which the temperature (strictly energy) varies. Returns the energy equation and corrects the thermodynamic model.
Source files
AnisothermalPhaseModel.H
AnisothermalPhaseModel.C
Definition at line 49 of file AnisothermalPhaseModel.H.
Constructor & Destructor Documentation
AnisothermalPhaseModel()
template<class BasePhaseModel > AnisothermalPhaseModel (const phaseSystem & fluid, const word & phaseName, const label index)
Definition at line 55 of file AnisothermalPhaseModel.C.
~AnisothermalPhaseModel()
template<class BasePhaseModel > virtual ~AnisothermalPhaseModel () virtual default
Member Function Documentation
correctThermo()
template<class BasePhaseModel > void correctThermo () virtual
Definition at line 69 of file AnisothermalPhaseModel.C.
isothermal()
template<class BasePhaseModel > bool isothermal () const virtual
Definition at line 78 of file AnisothermalPhaseModel.C.
heEqn()
template<class BasePhaseModel > Foam::tmp< Foam::fvScalarMatrix > heEqn () virtual
Definition at line 86 of file AnisothermalPhaseModel.C.
References Foam::fvc::absolute(), alpha, alphaEff(), alphaPhi(), contErr(), Foam::fvc::ddt(), Foam::fvm::ddt(), Foam::fvc::div(), Foam::fvm::div(), dpdt, fluid, he, Foam::fvc::interpolate(), Foam::fvm::laplacian(), IOobject::name(), p, Qdot, rho, Foam::fvm::Sp(), talphaPhi, and U.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/phaseModel/AnisothermalPhaseModel/AnisothermalPhaseModel.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/phaseModel/AnisothermalPhaseModel/AnisothermalPhaseModel.C