OpenFOAM: ReactingMultiphaseParcel< ParcelType > Class Template Reference
ReactingMultiphaseParcel< ParcelType > Class Template Reference
Lagrangian particle models » Parcels
Multiphase variant of the reacting parcel class with one/two-way coupling with the continuous phase.
#include <ReactingMultiphaseParcel.H>
Classes
class constantProperties
class iNew
Public Types
typedef ParcelType::trackingData trackingData
Public Member Functions
TypeName ("ReactingMultiphaseParcel")
AddToPropertyList (ParcelType, " nGas(Y1..YN)"+" nLiquid(Y1..YN)"+" nSolid(Y1..YN)")
ReactingMultiphaseParcel (const polyMesh &mesh, const barycentric &coordinates, const label celli, const label tetFacei, const label tetPti)
ReactingMultiphaseParcel (const polyMesh &mesh, const vector &position, const label celli)
ReactingMultiphaseParcel (const polyMesh &mesh, const barycentric &coordinates, const label celli, const label tetFacei, const label tetPti, const label typeId, const scalar nParticle0, const scalar d0, const scalar dTarget0, const vector &U0, const vector &f0, const vector &angularMomentum0, const vector &torque0, const scalarField &Y0, const scalarField &YGas0, const scalarField &YLiquid0, const scalarField &YSolid0, const constantProperties &constProps)
ReactingMultiphaseParcel (const polyMesh &mesh, Istream &is, bool readFields=true, bool newFormat=true)
ReactingMultiphaseParcel (const ReactingMultiphaseParcel &p)
ReactingMultiphaseParcel (const ReactingMultiphaseParcel &p, const polyMesh &mesh)
virtual autoPtr< particle > clone () const
virtual autoPtr< particle > clone (const polyMesh &mesh) const
const scalarField & YGas () const
const scalarField & YLiquid () const
const scalarField & YSolid () const
label canCombust () const
scalarField & YGas ()
scalarField & YLiquid ()
scalarField & YSolid ()
label & canCombust ()
template<class TrackCloudType >
void setCellValues (TrackCloudType &cloud, trackingData &td)
template<class TrackCloudType >
void cellValueSourceCorrection (TrackCloudType &cloud, trackingData &td, const scalar dt)
template<class TrackCloudType >
void calc (TrackCloudType &cloud, trackingData &td, const scalar dt)
void writeProperties (Ostream &os, const wordRes &filters, const word &delim, const bool namesOnly=false) const
template<class TrackCloudType >
Foam::scalar CpEff (TrackCloudType &cloud, trackingData &td, const scalar p, const scalar T, const label idG, const label idL, const label idS) const
template<class TrackCloudType >
Foam::scalar HsEff (TrackCloudType &cloud, trackingData &td, const scalar p, const scalar T, const label idG, const label idL, const label idS) const
template<class TrackCloudType >
Foam::scalar LEff (TrackCloudType &cloud, trackingData &td, const scalar p, const scalar T, const label idG, const label idL, const label idS) const
template<class TrackCloudType >
Foam::scalar updatedDeltaVolume (TrackCloudType &cloud, const scalarField &dMassGas, const scalarField &dMassLiquid, const scalarField &dMassSolid, const label idG, const label idL, const label idS, const scalar p, const scalar T)
Static Public Member Functions
template<class CloudType , class CompositionType >
static void readFields (CloudType &c, const CompositionType &compModel)
template<class CloudType >
static void readFields (CloudType &c)
template<class CloudType , class CompositionType >
static void writeFields (const CloudType &c, const CompositionType &compModel)
template<class CloudType >
static void writeFields (const CloudType &c)
template<class CloudType >
static void readObjects (CloudType &c, const objectRegistry &obr)
template<class CloudType , class CompositionType >
static void readObjects (CloudType &c, const CompositionType &compModel, const objectRegistry &obr)
template<class CloudType >
static void writeObjects (const CloudType &c, objectRegistry &obr)
template<class CloudType , class CompositionType >
static void writeObjects (const CloudType &c, const CompositionType &compModel, objectRegistry &obr)
Static Public Attributes
static const std::size_t sizeofFields
static const label GAS
static const label LIQ
static const label SLD
Protected Member Functions
template<class TrackCloudType >
scalar updatedDeltaVolume (TrackCloudType &cloud, const scalarField &dMassGas, const scalarField &dMassLiquid, const scalarField &dMassSolid, const label idG, const label idL, const label idS, const scalar p, const scalar T)
template<class TrackCloudType >
void calcDevolatilisation (TrackCloudType &cloud, trackingData &td, const scalar dt, const scalar age, const scalar Ts, const scalar d, const scalar T, const scalar mass, const scalar mass0, const scalarField &YGasEff, const scalarField &YLiquidEff, const scalarField &YSolidEff, label &canCombust, scalarField &dMassDV, scalar &Sh, scalar &N, scalar &NCpW, scalarField &Cs) const
template<class TrackCloudType >
void calcSurfaceReactions (TrackCloudType &cloud, trackingData &td, const scalar dt, const scalar d, const scalar Re, const scalar nu, const scalar T, const scalar mass, const label canCombust, const scalar N, const scalarField &YMix, const scalarField &YGas, const scalarField &YLiquid, const scalarField &YSolid, scalarField &dMassSRGas, scalarField &dMassSRLiquid, scalarField &dMassSRSolid, scalarField &dMassSRCarrier, scalar &Sh, scalar &dhsTrans) const
Protected Attributes
scalarField YGas_
scalarField YLiquid_
scalarField YSolid_
label canCombust_
Friends
Ostream & operator<< (Ostream &, const ReactingMultiphaseParcel< ParcelType > &)
Detailed Description
template<class ParcelType>
class Foam::ReactingMultiphaseParcel< ParcelType >
Multiphase variant of the reacting parcel class with one/two-way coupling with the continuous phase.
Source files
ReactingMultiphaseParcel.H
ReactingMultiphaseParcelI.H
ReactingMultiphaseParcel.C
ReactingMultiphaseParcelIO.C
Definition at line 61 of file ReactingMultiphaseParcel.H.
Member Typedef Documentation
trackingData
template<class ParcelType > typedef ParcelType::trackingData trackingData
Definition at line 125 of file ReactingMultiphaseParcel.H.
Constructor & Destructor Documentation
ReactingMultiphaseParcel() [1/6]
template<class ParcelType > ReactingMultiphaseParcel (const polyMesh & mesh, const barycentric & coordinates, const label celli, const label tetFacei, const label tetPti) inline
Definition at line 63 of file ReactingMultiphaseParcelI.H.
ReactingMultiphaseParcel() [2/6]
template<class ParcelType > ReactingMultiphaseParcel (const polyMesh & mesh, const vector & position, const label celli) inline
Definition at line 81 of file ReactingMultiphaseParcelI.H.
ReactingMultiphaseParcel() [3/6]
template<class ParcelType > ReactingMultiphaseParcel (const polyMesh & mesh, const barycentric & coordinates, const label celli, const label tetFacei, const label tetPti, const label typeId, const scalar nParticle0, const scalar d0, const scalar dTarget0, const vector & U0, const vector & f0, const vector & angularMomentum0, const vector & torque0, const scalarField & Y0, const scalarField & YGas0, const scalarField & YLiquid0, const scalarField & YSolid0, const constantProperties & constProps) inline
Definition at line 97 of file ReactingMultiphaseParcelI.H.
ReactingMultiphaseParcel() [4/6]
template<class ParcelType > ReactingMultiphaseParcel (const polyMesh & mesh, Istream & is, bool readFields = true, bool newFormat = true)
Definition at line 42 of file ReactingMultiphaseParcelIO.C.
References FUNCTION_NAME, ReactingMultiphaseParcel< ParcelType >::readFields(), Foam::readFields(), List< T >::transfer(), ReactingMultiphaseParcel< ParcelType >::YGas_, ReactingMultiphaseParcel< ParcelType >::YLiquid_, and ReactingMultiphaseParcel< ParcelType >::YSolid_.
ReactingMultiphaseParcel() [5/6]
template<class ParcelType > ReactingMultiphaseParcel (const ReactingMultiphaseParcel< ParcelType > & p)
ReactingMultiphaseParcel() [6/6]
template<class ParcelType > ReactingMultiphaseParcel (const ReactingMultiphaseParcel< ParcelType > & p, const polyMesh & mesh)
Member Function Documentation
updatedDeltaVolume() [1/2]
template<class ParcelType > template<class TrackCloudType > scalar updatedDeltaVolume (TrackCloudType & cloud, const scalarField & dMassGas, const scalarField & dMassLiquid, const scalarField & dMassSolid, const label idG, const label idL, const label idS, const scalar p, const scalar T) protected
calcDevolatilisation()
template<class ParcelType > template<class TrackCloudType > void calcDevolatilisation (TrackCloudType & cloud, trackingData & td, const scalar dt, const scalar age, const scalar Ts, const scalar d, const scalar T, const scalar mass, const scalar mass0, const scalarField & YGasEff, const scalarField & YLiquidEff, const scalarField & YSolidEff, label & canCombust, scalarField & dMassDV, scalar & Sh, scalar & N, scalar & NCpW, scalarField & Cs) const protected
Definition at line 586 of file ReactingMultiphaseParcel.C.
References beta(), Foam::cbrt(), composition, Cp, basicSpecieMixture::Cp(), Cs, forAll, Foam::max(), N(), Foam::pow(), Foam::constant::thermodynamic::RR, Foam::sqr(), Foam::sqrt(), Foam::sum(), T, and basicSpecieMixture::W().
calcSurfaceReactions()
template<class ParcelType > template<class TrackCloudType > void calcSurfaceReactions (TrackCloudType & cloud, trackingData & td, const scalar dt, const scalar d, const scalar Re, const scalar nu, const scalar T, const scalar mass, const label canCombust, const scalar N, const scalarField & YMix, const scalarField & YGas, const scalarField & YLiquid, const scalarField & YSolid, scalarField & dMassSRGas, scalarField & dMassSRLiquid, scalarField & dMassSRSolid, scalarField & dMassSRCarrier, scalar & Sh, scalar & dhsTrans) const protected
Definition at line 687 of file ReactingMultiphaseParcel.C.
References Foam::min(), N(), nu, Foam::Re(), Foam::sum(), and T.
TypeName()
template<class ParcelType > TypeName ("ReactingMultiphaseParcel< ParcelType >")
AddToPropertyList()
template<class ParcelType > AddToPropertyList (ParcelType , " nGas(Y1..YN)"+" nLiquid(Y1..YN)"+" nSolid(Y1..YN)")
clone() [1/2]
template<class ParcelType > virtual autoPtr< particle > clone () const inline virtual
Definition at line 356 of file ReactingMultiphaseParcel.H.
clone() [2/2]
template<class ParcelType > virtual autoPtr< particle > clone (const polyMesh & mesh) const inline virtual
Definition at line 362 of file ReactingMultiphaseParcel.H.
References mesh.
YGas() [1/2]
template<class ParcelType > const Foam::scalarField & YGas () const inline
Definition at line 183 of file ReactingMultiphaseParcelI.H.
YLiquid() [1/2]
template<class ParcelType > const Foam::scalarField & YLiquid () const inline
Definition at line 191 of file ReactingMultiphaseParcelI.H.
YSolid() [1/2]
template<class ParcelType > const Foam::scalarField & YSolid () const inline
Definition at line 199 of file ReactingMultiphaseParcelI.H.
canCombust() [1/2]
template<class ParcelType > Foam::label canCombust () const inline
Definition at line 208 of file ReactingMultiphaseParcelI.H.
YGas() [2/2]
template<class ParcelType > Foam::scalarField & YGas () inline
Definition at line 215 of file ReactingMultiphaseParcelI.H.
YLiquid() [2/2]
template<class ParcelType > Foam::scalarField & YLiquid () inline
Definition at line 222 of file ReactingMultiphaseParcelI.H.
YSolid() [2/2]
template<class ParcelType > Foam::scalarField & YSolid () inline
Definition at line 229 of file ReactingMultiphaseParcelI.H.
canCombust() [2/2]
template<class ParcelType > Foam::label & canCombust () inline
Definition at line 236 of file ReactingMultiphaseParcelI.H.
setCellValues()
template<class ParcelType > template<class TrackCloudType > void setCellValues (TrackCloudType & cloud, trackingData & td)
Definition at line 181 of file ReactingMultiphaseParcel.C.
cellValueSourceCorrection()
template<class ParcelType > template<class TrackCloudType > void cellValueSourceCorrection (TrackCloudType & cloud, trackingData & td, const scalar dt)
Definition at line 193 of file ReactingMultiphaseParcel.C.
calc()
template<class ParcelType > template<class TrackCloudType > void calc (TrackCloudType & cloud, trackingData & td, const scalar dt)
Definition at line 207 of file ReactingMultiphaseParcel.C.
References Foam::cbrt(), composition, Cs, forAll, basicSpecieMixture::Hs(), Foam::constant::mathematical::pi(), Foam::pow4(), Foam::Re(), rho0, UPtrList< T >::size(), basicMultiComponentMixture::species(), Su, Foam::sum(), T0, and Foam::Zero.
readFields() [1/2]
template<class ParcelType > template<class CloudType , class CompositionType > void readFields (CloudType & c, const CompositionType & compModel) static
Definition at line 83 of file ReactingMultiphaseParcelIO.C.
References forAll, Foam::max(), IOobjectOption::MUST_READ, p, List< T >::setSize(), UPtrList< T >::size(), and solidNames().
Referenced by ReactingMultiphaseParcel< ParcelType >::ReactingMultiphaseParcel().
readFields() [2/2]
template<class ParcelType > template<class CloudType > void readFields (CloudType & c) static
Definition at line 75 of file ReactingMultiphaseParcelIO.C.
writeFields() [1/2]
template<class ParcelType > template<class CloudType , class CompositionType > void writeFields (const CloudType & c, const CompositionType & compModel) static
Definition at line 183 of file ReactingMultiphaseParcelIO.C.
References forAll, Foam::max(), IOobjectOption::NO_READ, p0, UPtrList< T >::size(), and solidNames().
writeFields() [2/2]
template<class ParcelType > template<class CloudType > void writeFields (const CloudType & c) static
Definition at line 175 of file ReactingMultiphaseParcelIO.C.
writeProperties()
template<class ParcelType > void writeProperties (Ostream & os, const wordRes & filters, const word & delim, const bool namesOnly = false) const
Definition at line 274 of file ReactingMultiphaseParcelIO.C.
References os(), and writeProp.
readObjects() [1/2]
template<class ParcelType > template<class CloudType > void readObjects (CloudType & c, const objectRegistry & obr) static
Definition at line 299 of file ReactingMultiphaseParcelIO.C.
readObjects() [2/2]
template<class ParcelType > template<class CloudType , class CompositionType > void readObjects (CloudType & c, const CompositionType & compModel, const objectRegistry & obr) static
Definition at line 323 of file ReactingMultiphaseParcelIO.C.
References forAll, Foam::max(), p0, UPtrList< T >::size(), and solidNames().
writeObjects() [1/2]
template<class ParcelType > template<class CloudType > void writeObjects (const CloudType & c, objectRegistry & obr) static
Definition at line 311 of file ReactingMultiphaseParcelIO.C.
writeObjects() [2/2]
template<class ParcelType > template<class CloudType , class CompositionType > void writeObjects (const CloudType & c, const CompositionType & compModel, objectRegistry & obr) static
Definition at line 390 of file ReactingMultiphaseParcelIO.C.
References forAll, Foam::max(), p0, UPtrList< T >::size(), and solidNames().
CpEff()
template<class ParcelType > template<class TrackCloudType > Foam::scalar CpEff (TrackCloudType & cloud, trackingData & td, const scalar p, const scalar T, const label idG, const label idL, const label idS) const
Definition at line 43 of file ReactingMultiphaseParcel.C.
References p, and T.
HsEff()
template<class ParcelType > template<class TrackCloudType > Foam::scalar HsEff (TrackCloudType & cloud, trackingData & td, const scalar p, const scalar T, const label idG, const label idL, const label idS) const
Definition at line 63 of file ReactingMultiphaseParcel.C.
References p, and T.
LEff()
template<class ParcelType > template<class TrackCloudType > Foam::scalar LEff (TrackCloudType & cloud, trackingData & td, const scalar p, const scalar T, const label idG, const label idL, const label idS) const
Definition at line 83 of file ReactingMultiphaseParcel.C.
References p, and T.
updatedDeltaVolume() [2/2]
template<class ParcelType > template<class TrackCloudType > Foam::scalar updatedDeltaVolume (TrackCloudType & cloud, const scalarField & dMassGas, const scalarField & dMassLiquid, const scalarField & dMassSolid, const label idG, const label idL, const label idS, const scalar p, const scalar T)
Definition at line 137 of file ReactingMultiphaseParcel.C.
References forAll, p, UPtrList< T >::size(), Foam::sum(), T, and Foam::Zero.
Friends And Related Symbol Documentation
operator<<
template<class ParcelType > Ostream & operator<< (Ostream & , const ReactingMultiphaseParcel< ParcelType > &) friend
Member Data Documentation
sizeofFields
template<class ParcelType > const std::size_t sizeofFields static
Definition at line 68 of file ReactingMultiphaseParcel.H.
GAS
template<class ParcelType > const Foam::label GAS static
Definition at line 73 of file ReactingMultiphaseParcel.H.
LIQ
template<class ParcelType > const Foam::label LIQ static
Definition at line 74 of file ReactingMultiphaseParcel.H.
SLD
template<class ParcelType > const Foam::label SLD static
Definition at line 75 of file ReactingMultiphaseParcel.H.
YGas_
template<class ParcelType > scalarField YGas_ protected
Definition at line 188 of file ReactingMultiphaseParcel.H.
Referenced by ReactingMultiphaseParcel< ParcelType >::ReactingMultiphaseParcel().
YLiquid_
template<class ParcelType > scalarField YLiquid_ protected
Definition at line 191 of file ReactingMultiphaseParcel.H.
Referenced by ReactingMultiphaseParcel< ParcelType >::ReactingMultiphaseParcel().
YSolid_
template<class ParcelType > scalarField YSolid_ protected
Definition at line 194 of file ReactingMultiphaseParcel.H.
Referenced by ReactingMultiphaseParcel< ParcelType >::ReactingMultiphaseParcel().
canCombust_
template<class ParcelType > label canCombust_ protected
Definition at line 202 of file ReactingMultiphaseParcel.H.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/parcels/Templates/ReactingMultiphaseParcel/ReactingMultiphaseParcel.H
src/lagrangian/intermediate/parcels/Templates/ReactingMultiphaseParcel/ReactingMultiphaseParcel.C
src/lagrangian/intermediate/parcels/Templates/ReactingMultiphaseParcel/ReactingMultiphaseParcelI.H
src/lagrangian/intermediate/parcels/Templates/ReactingMultiphaseParcel/ReactingMultiphaseParcelIO.C