OpenFOAM: edgeCollapser Class Reference
edgeCollapser Class Reference
Does polyTopoChanges to remove edges. Can remove faces due to edge collapse but can not remove cells due to face removal! Also removes unused points.
#include <edgeCollapser.H>
Public Types
enum collapseType { noCollapse = 0 , toPoint = 1 , toEdge = 2 }
Public Member Functions
ClassName ("edgeCollapser")
edgeCollapser (const polyMesh &mesh)
edgeCollapser (const polyMesh &mesh, const dictionary &dict)
void consistentCollapse (const globalIndex &globalPoints, const labelList &pointPriority, const Map< point > &collapsePointToLocation, bitSet &collapseEdge, List< pointEdgeCollapse > &allPointInfo, const bool allowCellCollapse=false) const
bool setRefinement (const List< pointEdgeCollapse > &allPointInfo, polyTopoChange &meshMod) const
label markSmallEdges (const scalarField &minEdgeLen, const labelList &pointPriority, bitSet &collapseEdge, Map< point > &collapsePointToLocation) const
label markMergeEdges (const scalar maxCos, const labelList &pointPriority, bitSet &collapseEdge, Map< point > &collapsePointToLocation) const
labelPair markSmallSliverFaces (const scalarField &faceFilterFactor, const labelList &pointPriority, bitSet &collapseEdge, Map< point > &collapsePointToLocation) const
labelPair markFaceZoneEdges (const faceZone &fZone, const scalarField &faceFilterFactor, const labelList &pointPriority, bitSet &collapseEdge, Map< point > &collapsePointToLocation) const
Static Public Member Functions
static labelHashSet checkBadFaces (const polyMesh &mesh, const dictionary &meshQualityDict)
static label checkMeshQuality (const polyMesh &mesh, const dictionary &meshQualityDict, bitSet &isErrorPoint)
Detailed Description
Does polyTopoChanges to remove edges. Can remove faces due to edge collapse but can not remove cells due to face removal! Also removes unused points.
Source files
edgeCollapser.H
edgeCollapser.C
Definition at line 64 of file edgeCollapser.H.
Member Enumeration Documentation
collapseType
enum collapseType
Enumerator
noCollapse
toPoint
toEdge
Definition at line 69 of file edgeCollapser.H.
Constructor & Destructor Documentation
edgeCollapser() [1/2]
edgeCollapser (const polyMesh & mesh) explicit
Definition at line 1191 of file edgeCollapser.C.
edgeCollapser() [2/2]
edgeCollapser (const polyMesh & mesh, const dictionary & dict)
Definition at line 1201 of file edgeCollapser.C.
References Foam::endl(), Foam::Info, and Foam::nl.
Member Function Documentation
ClassName()
ClassName ("edgeCollapser")
checkBadFaces()
Foam::labelHashSet checkBadFaces (const polyMesh & mesh, const dictionary & meshQualityDict) static
Definition at line 43 of file edgeCollapser.C.
References PtrList< T >::append(), motionSmootherAlgo::checkMesh(), Foam::endl(), forAll, Foam::Info, Foam::mag(), and mesh.
Referenced by edgeCollapser::checkMeshQuality().
checkMeshQuality()
Foam::label checkMeshQuality (const polyMesh & mesh, const dictionary & meshQualityDict, bitSet & isErrorPoint) static
Definition at line 79 of file edgeCollapser.C.
References edgeCollapser::checkBadFaces(), f(), polyMesh::faces(), mesh, Foam::returnReduce(), PtrList< T >::set(), UPtrList< T >::size(), and syncTools::syncPointList().
Referenced by polyMeshFilter::filterEdges().
consistentCollapse()
void consistentCollapse (const globalIndex & globalPoints, const labelList & pointPriority, const Map< point > & collapsePointToLocation, bitSet & collapseEdge, List< pointEdgeCollapse > & allPointInfo, const bool allowCellCollapse = false) const
Definition at line 1602 of file edgeCollapser.C.
References Foam::abort(), cells, collapseEdge(), Foam::endl(), f(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::Info, Foam::nl, Foam::reduce(), Foam::returnReduce(), PtrList< T >::set(), UPtrList< T >::size(), syncTools::syncEdgeList(), syncTools::syncPointList(), UPtrList< T >::test(), bitSet::test(), and bitSet::unset().
setRefinement()
bool setRefinement (const List< pointEdgeCollapse > & allPointInfo, polyTopoChange & meshMod) const
Definition at line 1241 of file edgeCollapser.C.
References PtrList< T >::append(), cells, Foam::decrIndent(), Foam::endl(), f(), forAll, forAllConstIters, Foam::incrIndent(), Foam::indent(), Foam::Info, polyTopoChange::modifyFace(), polyTopoChange::modifyPoint(), Foam::nl, nPoints, patchID, Foam::Pout, Foam::reduce(), polyTopoChange::removeCell(), polyTopoChange::removeFace(), polyTopoChange::removePoint(), PtrList< T >::resize(), bitSet::set(), PtrList< T >::set(), UPtrList< T >::size(), UList< T >::size(), UPtrList< T >::test(), bitSet::test(), and ZoneMesh< ZoneType, MeshType >::whichZone().
markSmallEdges()
Foam::label markSmallEdges (const scalarField & minEdgeLen, const labelList & pointPriority, bitSet & collapseEdge, Map< point > & collapsePointToLocation) const
Definition at line 1792 of file edgeCollapser.C.
References Foam::average(), collapseEdge(), e, UList< T >::end(), forAll, points, PtrList< T >::set(), and UPtrList< T >::test().
markMergeEdges()
Foam::label markMergeEdges (const scalar maxCos, const labelList & pointPriority, bitSet & collapseEdge, Map< point > & collapsePointToLocation) const
Definition at line 1843 of file edgeCollapser.C.
References collapseEdge(), forAll, Foam::mag(), points, PtrList< T >::set(), and UPtrList< T >::size().
markSmallSliverFaces()
Foam::labelPair markSmallSliverFaces (const scalarField & faceFilterFactor, const labelList & pointPriority, bitSet & collapseEdge, Map< point > & collapsePointToLocation) const
Definition at line 1930 of file edgeCollapser.C.
References Foam::abort(), collapseEdge(), f(), Foam::FatalError, FatalErrorInFunction, forAll, and Foam::toPoint().
markFaceZoneEdges()
Foam::labelPair markFaceZoneEdges (const faceZone & fZone, const scalarField & faceFilterFactor, const labelList & pointPriority, bitSet & collapseEdge, Map< point > & collapsePointToLocation) const
Definition at line 1991 of file edgeCollapser.C.
References Foam::abort(), collapseEdge(), f(), Foam::FatalError, FatalErrorInFunction, forAll, and Foam::toPoint().
The documentation for this class was generated from the following files:
src/dynamicMesh/polyTopoChange/polyTopoChange/edgeCollapser.H
src/dynamicMesh/polyTopoChange/polyTopoChange/edgeCollapser.C