OpenFOAM: processorLduInterface Class Reference
processorLduInterface Class Reference abstract
An abstract base class for processor coupled interfaces.
#include <processorLduInterface.H>
Public Member Functions
TypeNameNoDebug ("processorLduInterface")
processorLduInterface () noexcept=default
virtual ~processorLduInterface ()=default
virtual label comm () const =0
virtual int myProcNo () const =0
virtual int neighbProcNo () const =0
virtual const tensorField & forwardT () const =0
virtual int tag () const =0
template<class Type >
void send (const UPstream::commsTypes commsType, const UList< Type > &f) const
template<class Type >
void receive (const UPstream::commsTypes commsType, UList< Type > &f) const
template<class Type >
tmp< Field< Type > > receive (const UPstream::commsTypes commsType, const label size) const
template<class Type >
void compressedSend (const UPstream::commsTypes commsType, const UList< Type > &f) const
template<class Type >
void compressedReceive (const UPstream::commsTypes commsType, UList< Type > &f) const
template<class Type >
tmp< Field< Type > > compressedReceive (const UPstream::commsTypes commsType, const label size) const
template<class Type >
Foam::tmp< Foam::Field< Type > > receive (const UPstream::commsTypes commsType, const label size) const
template<class Type >
Foam::tmp< Foam::Field< Type > > compressedReceive (const UPstream::commsTypes commsType, const label size) const
Detailed Description
An abstract base class for processor coupled interfaces.
Source files
processorLduInterface.H
processorLduInterface.C
processorLduInterfaceTemplates.C
Definition at line 49 of file processorLduInterface.H.
Constructor & Destructor Documentation
processorLduInterface()
processorLduInterface () default noexcept
~processorLduInterface()
virtual ~processorLduInterface () virtual default
Member Function Documentation
TypeNameNoDebug()
TypeNameNoDebug ("processorLduInterface")
comm()
virtual label comm () const pure virtual
Implemented in processorFaPatch, processorFvPatch, lduPrimitiveProcessorInterface, processorGAMGInterface, and calculatedProcessorGAMGInterface.
Referenced by processorLduInterface::send().
myProcNo()
virtual int myProcNo () const pure virtual
Implemented in processorFvPatch, lduPrimitiveProcessorInterface, processorGAMGInterface, calculatedProcessorGAMGInterface, and processorFaPatch.
neighbProcNo()
virtual int neighbProcNo () const pure virtual
Implemented in processorFvPatch, lduPrimitiveProcessorInterface, processorGAMGInterface, calculatedProcessorGAMGInterface, and processorFaPatch.
Referenced by processorLduInterface::send().
forwardT()
virtual const tensorField & forwardT () const pure virtual
Implemented in processorFaPatch, processorFvPatch, processorCyclicFvPatch, lduPrimitiveProcessorInterface, processorGAMGInterface, and calculatedProcessorGAMGInterface.
tag()
virtual int tag () const pure virtual
Implemented in processorFaPatch, processorFvPatch, processorCyclicFvPatch, lduPrimitiveProcessorInterface, processorGAMGInterface, and calculatedProcessorGAMGInterface.
Referenced by processorLduInterface::send().
send()
template<class Type > void send (const UPstream::commsTypes commsType, const UList< Type > & f) const
Definition at line 29 of file processorLduInterfaceTemplates.C.
References UPstream::blocking, UList< T >::cdata(), processorLduInterface::comm(), UList< T >::data(), Foam::exit(), f(), Foam::FatalError, FatalErrorInFunction, processorLduInterface::neighbProcNo(), UPstream::nonBlocking, UIPstream::read(), UPstream::scheduled, processorLduInterface::tag(), and UOPstream::write().
Referenced by lduPrimitiveProcessorInterface::initInternalFieldTransfer(), and lduPrimitiveProcessorInterface::initInternalFieldTransfer().
receive() [1/3]
template<class Type > void receive (const UPstream::commsTypes commsType, UList< Type > & f) const
Definition at line 99 of file processorLduInterfaceTemplates.C.
References UPstream::blocking, UList< T >::byteSize(), UList< T >::data(), UList< T >::data_bytes(), Foam::exit(), f(), Foam::FatalError, FatalErrorInFunction, UPstream::nonBlocking, UIPstream::read(), and UPstream::scheduled.
receive() [2/3]
template<class Type > tmp< Field< Type > > receive (const UPstream::commsTypes commsType, const label size) const
compressedSend()
template<class Type > void compressedSend (const UPstream::commsTypes commsType, const UList< Type > & f) const
Definition at line 153 of file processorLduInterfaceTemplates.C.
References UPstream::blocking, UList< T >::cdata(), Foam::exit(), f(), Foam::FatalError, FatalErrorInFunction, UPstream::floatTransfer, UList< T >::last(), UPstream::nonBlocking, UIPstream::read(), UPstream::scheduled, UList< T >::size(), and UOPstream::write().
compressedReceive() [1/3]
template<class Type > void compressedReceive (const UPstream::commsTypes commsType, UList< Type > & f) const
Definition at line 243 of file processorLduInterfaceTemplates.C.
References UPstream::blocking, UList< T >::data(), Foam::exit(), f(), Foam::FatalError, FatalErrorInFunction, UPstream::floatTransfer, UList< T >::last(), UPstream::nonBlocking, UIPstream::read(), UPstream::scheduled, and UList< T >::size().
compressedReceive() [2/3]
template<class Type > tmp< Field< Type > > compressedReceive (const UPstream::commsTypes commsType, const label size) const
receive() [3/3]
template<class Type > Foam::tmp< Foam::Field< Type > > receive (const UPstream::commsTypes commsType, const label size) const
Definition at line 140 of file processorLduInterfaceTemplates.C.
References Foam::New().
compressedReceive() [3/3]
template<class Type > Foam::tmp< Foam::Field< Type > > compressedReceive (const UPstream::commsTypes commsType, const label size) const
Definition at line 310 of file processorLduInterfaceTemplates.C.
References Foam::New().
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/lduMatrix/lduAddressing/lduInterface/processorLduInterface.H
src/OpenFOAM/matrices/lduMatrix/lduAddressing/lduInterface/processorLduInterfaceTemplates.C