OpenFOAM: substance Class Reference
substance Class Reference
#include <substance.H>
Public Member Functions
substance ()
const word & name () const
scalar volFrac () const
bool operator== (const substance &s) const
bool operator!= (const substance &s) const
Friends
Istream & operator>> (Istream &is, substance &s)
Ostream & operator<< (Ostream &os, const substance &s)
Detailed Description
Source files
substance.H
substanceI.H
substance.C
substanceIO.C
Definition at line 49 of file substance.H.
Constructor & Destructor Documentation
substance()
substance () inline
Definition at line 62 of file substance.H.
Member Function Documentation
name()
const word & name () const inline
Definition at line 70 of file substance.H.
volFrac()
scalar volFrac () const inline
Definition at line 75 of file substance.H.
operator==()
bool operator== (const substance & s) const inline
Definition at line 80 of file substance.H.
References s().
Referenced by substance::operator!=().
operator!=()
bool operator!= (const substance & s) const inline
Definition at line 85 of file substance.H.
References substance::operator==(), and s().
Friends And Related Symbol Documentation
operator>>
Istream & operator>> (Istream & is, substance & s) friend
Definition at line 93 of file substance.H.
operator<<
Ostream & operator<< (Ostream & os, const substance & s) friend
Definition at line 99 of file substance.H.
The documentation for this class was generated from the following file:
applications/utilities/thermophysical/mixtureAdiabaticFlameT/substance.H