OpenFOAM: removePoints Class Reference
removePoints Class Reference
Removes selected points from mesh and updates faces using these points.
#include <removePoints.H>
Public Member Functions
ClassName ("removePoints")
removePoints (const polyMesh &mesh, const bool undoable=false)
const labelList & savedFaceLabels () const
label countPointUsage (const scalar minCos, boolList &pointCanBeDeleted) const
void setRefinement (const boolList &, polyTopoChange &)
void updateMesh (const mapPolyMesh &)
void getUnrefimentSet (const labelList &undoFaces, labelList &localFaces, labelList &localPoints) const
void setUnrefinement (const labelList &localFaces, const labelList &localPoints, polyTopoChange &)
Detailed Description
Removes selected points from mesh and updates faces using these points.
Source files
removePoints.H
removePoints.C
Definition at line 56 of file removePoints.H.
Constructor & Destructor Documentation
removePoints()
removePoints (const polyMesh & mesh, const bool undoable = false) explicit
Definition at line 127 of file removePoints.C.
Member Function Documentation
ClassName()
ClassName ("removePoints")
savedFaceLabels()
const labelList & savedFaceLabels () const inline
Definition at line 111 of file removePoints.H.
countPointUsage()
Foam::label countPointUsage (const scalar minCos, boolList & pointCanBeDeleted) const
Definition at line 140 of file removePoints.C.
References PtrList< T >::clear(), e, f(), forAll, Foam::normalised(), edge::otherVertex(), points, Foam::returnReduce(), PtrList< T >::setSize(), UList< T >::size(), and syncTools::syncPointList().
setRefinement()
void setRefinement (const boolList & pointCanBeDeleted, polyTopoChange & meshMod)
Definition at line 288 of file removePoints.C.
References Foam::abort(), f(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::nl, pFaces, PtrList< T >::resize(), polyTopoChange::setAction(), List< T >::setSize(), PtrList< T >::setSize(), UPtrList< T >::size(), and UList< T >::size().
updateMesh()
void updateMesh (const mapPolyMesh & map)
Definition at line 444 of file removePoints.C.
References Foam::abort(), f(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::nl, mapPolyMesh::reverseFaceMap(), mapPolyMesh::reversePointMap(), PtrList< T >::setSize(), and UPtrList< T >::size().
getUnrefimentSet()
void getUnrefimentSet (const labelList & undoFaces, labelList & localFaces, labelList & localPoints) const
Definition at line 545 of file removePoints.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, VectorSpace< Form, Cmpt, Ncmpts >::max, PtrList< T >::setSize(), UPtrList< T >::size(), and syncTools::syncBoundaryFaceList().
setUnrefinement()
void setUnrefinement (const labelList & localFaces, const labelList & localPoints, polyTopoChange & meshMod)
Definition at line 757 of file removePoints.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, VectorSpace< Form, Cmpt, Ncmpts >::max, polyTopoChange::setAction(), List< T >::setSize(), PtrList< T >::setSize(), UPtrList< T >::size(), and PtrList< T >::transfer().
The documentation for this class was generated from the following files:
src/dynamicMesh/polyTopoChange/polyTopoChange/removePoints.H
src/dynamicMesh/polyTopoChange/polyTopoChange/removePoints.C