OpenFOAM: constantHeatTransfer Class Reference
constantHeatTransfer Class Reference
Constant heat transfer model.
#include <constantHeatTransfer.H>
Public Member Functions
TypeName ("constant")
constantHeatTransfer (surfaceFilmRegionModel &film, const dictionary &dict)
virtual ~constantHeatTransfer ()
virtual void correct ()
virtual tmp< volScalarField > h () const
Public Member Functions inherited from heatTransferModel
TypeName ("heatTransferModel")
declareRunTimeSelectionTable (autoPtr, heatTransferModel, dictionary,(surfaceFilmRegionModel &film, const dictionary &dict),(film, dict))
heatTransferModel (surfaceFilmRegionModel &film)
heatTransferModel (const word &modelType, surfaceFilmRegionModel &film, const dictionary &dict)
virtual ~heatTransferModel ()
Public Member Functions inherited from filmSubModelBase
filmSubModelBase (surfaceFilmRegionModel &film)
filmSubModelBase (surfaceFilmRegionModel &film, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
filmSubModelBase (const word &modelName, surfaceFilmRegionModel &film, const dictionary &dict, const word &baseName, const word &modelType)
virtual ~filmSubModelBase ()
virtual bool writeTime () const
const surfaceFilmRegionModel & film () const
surfaceFilmRegionModel & film ()
template<class FilmType >
const FilmType & filmType () const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
subModelBase (const subModelBase &smb)
virtual ~subModelBase ()=default
const word & modelName () const
const dictionary & dict () const
const word & baseName () const
const word & modelType () const
const dictionary & coeffDict () const
const dictionary & properties () const
virtual bool defaultCoeffs (const bool printMsg) const
virtual bool active () const
virtual void cacheFields (const bool store)
virtual fileName localPath () const
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
bool getModelDict (const word &entryName, dictionary &dict) const
template<class Type >
bool getModelProperty (const word &entryName, Type &value) const
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
virtual void write (Ostream &os) const
Additional Inherited Members
Static Public Member Functions inherited from heatTransferModel
static autoPtr< heatTransferModel > New (surfaceFilmRegionModel &film, const dictionary &dict)
Public Attributes inherited from subModelBase
bool log
Protected Member Functions inherited from subModelBase
bool inLine () const
Protected Attributes inherited from filmSubModelBase
surfaceFilmRegionModel & filmModel_
Protected Attributes inherited from subModelBase
const word modelName_
dictionary & properties_
const dictionary dict_
const word baseName_
const word modelType_
const dictionary coeffDict_
Detailed Description
Constant heat transfer model.
Source files
constantHeatTransfer.H
constantHeatTransfer.C
Definition at line 51 of file constantHeatTransfer.H.
Constructor & Destructor Documentation
constantHeatTransfer()
constantHeatTransfer (surfaceFilmRegionModel & film, const dictionary & dict)
Definition at line 47 of file constantHeatTransfer.C.
~constantHeatTransfer()
~constantHeatTransfer () virtual
Definition at line 60 of file constantHeatTransfer.C.
Member Function Documentation
TypeName()
TypeName ("constant")
correct()
void correct () virtual
Implements heatTransferModel.
Definition at line 66 of file constantHeatTransfer.C.
h()
tmp< volScalarField > h () const virtual
Implements heatTransferModel.
Definition at line 70 of file constantHeatTransfer.C.
References Foam::dimEnergy, Foam::dimLength, Foam::dimTemperature, Foam::dimTime, filmSubModelBase::filmModel_, IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, regionModel::regionMesh(), Foam::sqr(), and regionModel::time().
The documentation for this class was generated from the following files:
src/regionModels/surfaceFilmModels/submodels/thermo/heatTransferModel/constantHeatTransfer/constantHeatTransfer.H
src/regionModels/surfaceFilmModels/submodels/thermo/heatTransferModel/constantHeatTransfer/constantHeatTransfer.C