OpenFOAM: boundedBackwardFaDdtScheme Class Reference
boundedBackwardFaDdtScheme Class Reference
#include <boundedBackwardFaDdtScheme.H>
Public Member Functions
TypeName ("boundedBackward")
boundedBackwardFaDdtScheme (const faMesh &mesh)
boundedBackwardFaDdtScheme (const faMesh &mesh, Istream &is)
const faMesh & mesh () const
tmp< areaScalarField > facDdt (const dimensionedScalar)
tmp< areaScalarField > facDdt0 (const dimensionedScalar)
tmp< areaScalarField > facDdt (const areaScalarField &)
tmp< areaScalarField > facDdt0 (const areaScalarField &)
tmp< areaScalarField > facDdt (const dimensionedScalar &, const areaScalarField &)
tmp< areaScalarField > facDdt0 (const dimensionedScalar &, const areaScalarField &)
tmp< areaScalarField > facDdt (const areaScalarField &, const areaScalarField &)
tmp< areaScalarField > facDdt0 (const areaScalarField &, const areaScalarField &)
tmp< faScalarMatrix > famDdt (const areaScalarField &)
tmp< faScalarMatrix > famDdt (const dimensionedScalar &, const areaScalarField &)
tmp< faScalarMatrix > famDdt (const areaScalarField &, const areaScalarField &)
Public Member Functions inherited from faDdtScheme< scalar >
faDdtScheme (const faMesh &mesh)
faDdtScheme (const faMesh &mesh, Istream &)
virtual const word & type () const=0
declareRunTimeSelectionTable (tmp, faDdtScheme, Istream,(const faMesh &mesh, Istream &schemeData),(mesh, schemeData))
virtual ~faDdtScheme ()
const faMesh & mesh () const
virtual tmp< GeometricField< scalar, faPatchField, areaMesh > > facDdt (const GeometricField< scalar, faPatchField, areaMesh > &)=0
virtual tmp< GeometricField< scalar, faPatchField, areaMesh > > facDdt (const dimensionedScalar &, const GeometricField< scalar, faPatchField, areaMesh > &)=0
virtual tmp< GeometricField< scalar, faPatchField, areaMesh > > facDdt (const areaScalarField &, const GeometricField< scalar, faPatchField, areaMesh > &)=0
virtual tmp< GeometricField< scalar, faPatchField, areaMesh > > facDdt0 (const GeometricField< scalar, faPatchField, areaMesh > &)=0
virtual tmp< GeometricField< scalar, faPatchField, areaMesh > > facDdt0 (const dimensionedScalar &, const GeometricField< scalar, faPatchField, areaMesh > &)=0
virtual tmp< GeometricField< scalar, faPatchField, areaMesh > > facDdt0 (const areaScalarField &, const GeometricField< scalar, faPatchField, areaMesh > &)=0
virtual tmp< faMatrix< scalar > > famDdt (const GeometricField< scalar, faPatchField, areaMesh > &)=0
virtual tmp< faMatrix< scalar > > famDdt (const dimensionedScalar &, const GeometricField< scalar, faPatchField, areaMesh > &)=0
virtual tmp< faMatrix< scalar > > famDdt (const areaScalarField &, const GeometricField< scalar, faPatchField, areaMesh > &)=0
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Additional Inherited Members
Static Public Member Functions inherited from faDdtScheme< scalar >
static tmp< faDdtScheme< scalar > > New (const faMesh &mesh, Istream &schemeData)
Protected Member Functions inherited from faDdtScheme< scalar >
faDdtScheme (const faDdtScheme &)=delete
void operator= (const faDdtScheme &)=delete
Protected Attributes inherited from faDdtScheme< scalar >
const faMesh & mesh_
Detailed Description
Definition at line 53 of file boundedBackwardFaDdtScheme.H.
Constructor & Destructor Documentation
boundedBackwardFaDdtScheme() [1/2]
boundedBackwardFaDdtScheme (const faMesh & mesh) inline
Definition at line 97 of file boundedBackwardFaDdtScheme.H.
boundedBackwardFaDdtScheme() [2/2]
boundedBackwardFaDdtScheme (const faMesh & mesh, Istream & is) inline
Definition at line 103 of file boundedBackwardFaDdtScheme.H.
Member Function Documentation
TypeName()
TypeName ("boundedBackward")
mesh()
const faMesh & mesh () const inline
Definition at line 112 of file boundedBackwardFaDdtScheme.H.
References faDdtScheme< Type >::mesh().
Referenced by boundedBackwardFaDdtScheme::facDdt(), boundedBackwardFaDdtScheme::facDdt(), boundedBackwardFaDdtScheme::facDdt(), boundedBackwardFaDdtScheme::facDdt(), boundedBackwardFaDdtScheme::facDdt0(), boundedBackwardFaDdtScheme::facDdt0(), boundedBackwardFaDdtScheme::facDdt0(), boundedBackwardFaDdtScheme::facDdt0(), boundedBackwardFaDdtScheme::famDdt(), boundedBackwardFaDdtScheme::famDdt(), and boundedBackwardFaDdtScheme::famDdt().
facDdt() [1/4]
tmp< areaScalarField > facDdt (const dimensionedScalar dt) virtual
Implements faDdtScheme< scalar >.
Definition at line 51 of file boundedBackwardFaDdtScheme.C.
References faPatchFieldBase::calculatedType(), dimensioned< Type >::dimensions(), Foam::dimTime, boundedBackwardFaDdtScheme::mesh(), dimensioned< Type >::name(), tmp< T >::New(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, timeName, dimensioned< Type >::value(), and Foam::Zero.
facDdt0() [1/4]
tmp< areaScalarField > facDdt0 (const dimensionedScalar dt) virtual
Implements faDdtScheme< scalar >.
Definition at line 106 of file boundedBackwardFaDdtScheme.C.
References boundedBackwardFaDdtScheme::mesh(), dimensioned< Type >::name(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, timeName, and dimensioned< Type >::value().
facDdt() [2/4]
tmp< areaScalarField > facDdt (const areaScalarField & vf)
Definition at line 153 of file boundedBackwardFaDdtScheme.C.
References Foam::limiter(), Foam::mag(), boundedBackwardFaDdtScheme::mesh(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, Foam::pos(), Foam::sqr(), and timeName.
facDdt0() [2/4]
tmp< areaScalarField > facDdt0 (const areaScalarField & vf)
Definition at line 250 of file boundedBackwardFaDdtScheme.C.
References Foam::limiter(), Foam::mag(), boundedBackwardFaDdtScheme::mesh(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, Foam::pos(), Foam::sqr(), and timeName.
facDdt() [3/4]
tmp< areaScalarField > facDdt (const dimensionedScalar & rho, const areaScalarField & vf)
Definition at line 344 of file boundedBackwardFaDdtScheme.C.
References Foam::limiter(), Foam::mag(), boundedBackwardFaDdtScheme::mesh(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, Foam::pos(), rho, Foam::sqr(), and timeName.
facDdt0() [3/4]
tmp< areaScalarField > facDdt0 (const dimensionedScalar & rho, const areaScalarField & vf)
Definition at line 441 of file boundedBackwardFaDdtScheme.C.
References Foam::limiter(), Foam::mag(), boundedBackwardFaDdtScheme::mesh(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, Foam::pos(), rho, Foam::sqr(), and timeName.
facDdt() [4/4]
tmp< areaScalarField > facDdt (const areaScalarField & rho, const areaScalarField & vf)
Definition at line 536 of file boundedBackwardFaDdtScheme.C.
References Foam::limiter(), Foam::mag(), boundedBackwardFaDdtScheme::mesh(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, Foam::pos(), rho, Foam::sqr(), and timeName.
facDdt0() [4/4]
tmp< areaScalarField > facDdt0 (const areaScalarField & rho, const areaScalarField & vf)
Definition at line 637 of file boundedBackwardFaDdtScheme.C.
References Foam::limiter(), Foam::mag(), boundedBackwardFaDdtScheme::mesh(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, Foam::pos(), rho, Foam::sqr(), and timeName.
famDdt() [1/3]
tmp< faScalarMatrix > famDdt (const areaScalarField & vf)
Definition at line 735 of file boundedBackwardFaDdtScheme.C.
References Foam::dimArea, Foam::dimTime, Foam::limiter(), Foam::mag(), boundedBackwardFaDdtScheme::mesh(), and Foam::pos().
famDdt() [2/3]
tmp< faScalarMatrix > famDdt (const dimensionedScalar & rho, const areaScalarField & vf)
Definition at line 806 of file boundedBackwardFaDdtScheme.C.
References Foam::dimArea, Foam::dimTime, Foam::limiter(), Foam::mag(), boundedBackwardFaDdtScheme::mesh(), Foam::pos(), and rho.
famDdt() [3/3]
tmp< faScalarMatrix > famDdt (const areaScalarField & rho, const areaScalarField & vf)
Definition at line 877 of file boundedBackwardFaDdtScheme.C.
References Foam::dimArea, Foam::dimTime, Foam::limiter(), Foam::mag(), boundedBackwardFaDdtScheme::mesh(), Foam::pos(), and rho.
The documentation for this class was generated from the following files:
src/finiteArea/finiteArea/ddtSchemes/boundedBackwardFaDdtScheme/boundedBackwardFaDdtScheme.H
src/finiteArea/finiteArea/ddtSchemes/boundedBackwardFaDdtScheme/boundedBackwardFaDdtScheme.C