OpenFOAM: cellPointWeight Class Reference
cellPointWeight Class Reference
Foam::cellPointWeight.
#include <cellPointWeight.H>
Public Member Functions
cellPointWeight (const polyMesh &mesh, const vector &position, const label celli, const label facei=-1)
label cell () const noexcept
const barycentric & weights () const noexcept
const triFace & faceVertices () const noexcept
Static Public Attributes
static int debug
static scalar tol
Protected Member Functions
void findTetrahedron (const polyMesh &mesh, const vector &position, const label celli)
void findTriangle (const polyMesh &mesh, const vector &position, const label facei)
Protected Attributes
const label celli_
barycentric weights_
triFace faceVertices_
Detailed Description
Foam::cellPointWeight.
Source files
cellPointWeight.H
cellPointWeight.C
Definition at line 51 of file cellPointWeight.H.
Constructor & Destructor Documentation
cellPointWeight()
cellPointWeight (const polyMesh & mesh, const vector & position, const label celli, const label facei = -1)
Definition at line 235 of file cellPointWeight.C.
References cellPointWeight::findTetrahedron(), cellPointWeight::findTriangle(), and mesh.
Member Function Documentation
findTetrahedron()
void findTetrahedron (const polyMesh & mesh, const vector & position, const label celli) protected
Definition at line 33 of file cellPointWeight.C.
References polyMeshTetDecomposition::cellTetIndices(), cellPointWeight::debug, Foam::det(), Foam::endl(), cellPointWeight::faceVertices_, forAll, Foam::mag(), mesh, Foam::nl, Foam::Pout, cellPointWeight::tol, and cellPointWeight::weights_.
Referenced by cellPointWeight::cellPointWeight().
findTriangle()
void findTriangle (const polyMesh & mesh, const vector & position, const label facei) protected
Definition at line 127 of file cellPointWeight.C.
References Foam::det(), Foam::endl(), primitiveMesh::faceAreas(), polyMesh::faceOwner(), polyMeshTetDecomposition::faceTetIndices(), forAll, Foam::mag(), Foam::magSqr(), mesh, Foam::nl, and Foam::Pout.
Referenced by cellPointWeight::cellPointWeight().
cell()
label cell () const inline noexcept
Definition at line 110 of file cellPointWeight.H.
References cellPointWeight::celli_.
weights()
const barycentric & weights () const inline noexcept
Definition at line 116 of file cellPointWeight.H.
References cellPointWeight::weights_.
faceVertices()
const triFace & faceVertices () const inline noexcept
Definition at line 122 of file cellPointWeight.H.
References cellPointWeight::faceVertices_.
Member Data Documentation
celli_
const label celli_ protected
Definition at line 58 of file cellPointWeight.H.
Referenced by cellPointWeight::cell().
weights_
barycentric weights_ protected
Definition at line 62 of file cellPointWeight.H.
Referenced by cellPointWeightWallModified::cellPointWeightWallModified(), cellPointWeight::findTetrahedron(), and cellPointWeight::weights().
faceVertices_
triFace faceVertices_ protected
Definition at line 65 of file cellPointWeight.H.
Referenced by cellPointWeight::faceVertices(), and cellPointWeight::findTetrahedron().
debug
int debug static
Definition at line 88 of file cellPointWeight.H.
Referenced by cellPointWeight::findTetrahedron().
tol
Foam::scalar tol static
Definition at line 92 of file cellPointWeight.H.
Referenced by cellPointWeight::findTetrahedron().
The documentation for this class was generated from the following files:
src/finiteVolume/interpolation/interpolation/interpolationCellPoint/cellPointWeight.H
src/finiteVolume/interpolation/interpolation/interpolationCellPoint/cellPointWeight.C