OpenFOAM: pressureNormalInletOutletVelocityFvPatchVectorField Class Reference
pressureNormalInletOutletVelocityFvPatchVectorField Class Reference
Boundary conditions » Inlet | Boundary conditions » Outlet
This velocity inlet/outlet boundary condition is applied to patches where the pressure is specified. A zero-gradient condition is applied for outflow (as defined by the flux); for inflow, the velocity is obtained from the flux with a direction normal to the patch faces.
#include <pressureNormalInletOutletVelocityFvPatchVectorField.H>
Public Member Functions
TypeName ("pressureNormalInletOutletVelocity")
pressureNormalInletOutletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
pressureNormalInletOutletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
pressureNormalInletOutletVelocityFvPatchVectorField (const pressureNormalInletOutletVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
pressureNormalInletOutletVelocityFvPatchVectorField (const pressureNormalInletOutletVelocityFvPatchVectorField &)
virtual tmp< fvPatchVectorField > clone () const
pressureNormalInletOutletVelocityFvPatchVectorField (const pressureNormalInletOutletVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
virtual bool assignable () const
const word & rhoName () const
word & rhoName ()
const word & phiName () const
word & phiName ()
virtual void updateCoeffs ()
virtual void write (Ostream &) const
virtual void operator= (const fvPatchField< vector > &pvf)
Detailed Description
This velocity inlet/outlet boundary condition is applied to patches where the pressure is specified. A zero-gradient condition is applied for outflow (as defined by the flux); for inflow, the velocity is obtained from the flux with a direction normal to the patch faces.
Usage
Property Description Required Default value
phi flux field name no phi
rho density field name no rho
Example of the boundary condition specification:
    <patchName>
    {
        type            pressureNormalInletOutletVelocity;
        phi             phi;
        rho             rho;
        value           uniform 0;
    }
Note
Sign conventions:
positive flux (out of domain): apply zero-gradient condition
negative flux (into of domain): derive from the flux and patch-normal direction
See also
Foam::mixedFvPatchVectorField
Source files
pressureNormalInletOutletVelocityFvPatchVectorField.H
pressureNormalInletOutletVelocityFvPatchVectorField.C
Definition at line 95 of file pressureNormalInletOutletVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
pressureNormalInletOutletVelocityFvPatchVectorField() [1/5]
pressureNormalInletOutletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Definition at line 31 of file pressureNormalInletOutletVelocityFvPatchVectorField.C.
References Foam::Zero.
pressureNormalInletOutletVelocityFvPatchVectorField() [2/5]
pressureNormalInletOutletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Definition at line 63 of file pressureNormalInletOutletVelocityFvPatchVectorField.C.
References dict, IOobjectOption::MUST_READ, fvPatchFieldBase::readDict(), and Foam::Zero.
pressureNormalInletOutletVelocityFvPatchVectorField() [3/5]
pressureNormalInletOutletVelocityFvPatchVectorField (const pressureNormalInletOutletVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 48 of file pressureNormalInletOutletVelocityFvPatchVectorField.C.
pressureNormalInletOutletVelocityFvPatchVectorField() [4/5]
pressureNormalInletOutletVelocityFvPatchVectorField (const pressureNormalInletOutletVelocityFvPatchVectorField & pivpvf)
Definition at line 83 of file pressureNormalInletOutletVelocityFvPatchVectorField.C.
pressureNormalInletOutletVelocityFvPatchVectorField() [5/5]
pressureNormalInletOutletVelocityFvPatchVectorField (const pressureNormalInletOutletVelocityFvPatchVectorField & pivpvf, const DimensionedField< vector, volMesh > & iF)
Definition at line 95 of file pressureNormalInletOutletVelocityFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("pressureNormalInletOutletVelocity")
clone() [1/2]
virtual tmp< fvPatchVectorField > clone () const inline virtual
Definition at line 149 of file pressureNormalInletOutletVelocityFvPatchVectorField.H.
clone() [2/2]
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Definition at line 168 of file pressureNormalInletOutletVelocityFvPatchVectorField.H.
assignable()
virtual bool assignable () const inline virtual
Definition at line 187 of file pressureNormalInletOutletVelocityFvPatchVectorField.H.
rhoName() [1/2]
const word & rhoName () const inline
Definition at line 193 of file pressureNormalInletOutletVelocityFvPatchVectorField.H.
rhoName() [2/2]
word & rhoName () inline
Definition at line 199 of file pressureNormalInletOutletVelocityFvPatchVectorField.H.
phiName() [1/2]
const word & phiName () const inline
Definition at line 205 of file pressureNormalInletOutletVelocityFvPatchVectorField.H.
phiName() [2/2]
word & phiName () inline
Definition at line 212 of file pressureNormalInletOutletVelocityFvPatchVectorField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 110 of file pressureNormalInletOutletVelocityFvPatchVectorField.C.
References Foam::dimMass, Foam::dimTime, Foam::dimVolume, Foam::exit(), Foam::FatalError, FatalErrorInFunction, n, and Foam::neg().
write()
void write (Ostream & os) const virtual
Definition at line 148 of file pressureNormalInletOutletVelocityFvPatchVectorField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntry(), and fvPatchField< Type >::writeValueEntry().
operator=()
void operator= (const fvPatchField< vector > & pvf) virtual
Definition at line 162 of file pressureNormalInletOutletVelocityFvPatchVectorField.C.
References Foam::lerp(), and n.
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/pressureNormalInletOutletVelocity/pressureNormalInletOutletVelocityFvPatchVectorField.H
src/finiteVolume/fields/fvPatchFields/derived/pressureNormalInletOutletVelocity/pressureNormalInletOutletVelocityFvPatchVectorField.C