OpenFOAM: cellQuality Class Reference
cellQuality Class Reference
Class calculates cell quality measures.
#include <cellQuality.H>
Public Member Functions
cellQuality (const polyMesh &mesh)
tmp< scalarField > nonOrthogonality () const
tmp< scalarField > skewness () const
tmp< scalarField > faceNonOrthogonality () const
tmp< scalarField > faceSkewness () const
Detailed Description
Class calculates cell quality measures.
Source files
cellQuality.H
cellQuality.C
Definition at line 47 of file cellQuality.H.
Constructor & Destructor Documentation
cellQuality()
cellQuality (const polyMesh & mesh)
Definition at line 27 of file cellQuality.C.
Member Function Documentation
nonOrthogonality()
Foam::tmp< Foam::scalarField > nonOrthogonality () const
Definition at line 35 of file cellQuality.C.
References Foam::acos(), forAll, Foam::mag(), Foam::max(), Foam::min(), Foam::radToDeg(), s(), and Foam::Zero.
skewness()
Foam::tmp< Foam::scalarField > skewness () const
Definition at line 97 of file cellQuality.C.
References forAll, Foam::mag(), Foam::max(), n, and Foam::Zero.
faceNonOrthogonality()
Foam::tmp< Foam::scalarField > faceNonOrthogonality () const
Definition at line 176 of file cellQuality.C.
References Foam::acos(), forAll, Foam::mag(), Foam::min(), Foam::radToDeg(), and s().
faceSkewness()
Foam::tmp< Foam::scalarField > faceSkewness () const
Definition at line 236 of file cellQuality.C.
References forAll, Foam::mag(), and n.
The documentation for this class was generated from the following files:
src/meshTools/cellQuality/cellQuality.H
src/meshTools/cellQuality/cellQuality.C