OpenFOAM: PtrDynList< T, SizeMin > Class Template Reference
PtrDynList< T, SizeMin > Class Template Reference
A dynamically resizable PtrList with allocation management.
#include <PtrDynList.H>
Public Member Functions
constexpr PtrDynList () noexcept
PtrDynList (const label len)
PtrDynList (const PtrDynList< T, SizeMin > &list)
PtrDynList (PtrDynList< T, SizeMin > &&list)
PtrDynList (PtrList< T > &&list)
PtrDynList (UList< T * > &list)
~PtrDynList ()=default
label capacity () const noexcept
void reserve (const label len)
void resize (const label newLen)
void clear ()
void clearStorage ()
label expandStorage () noexcept
void shrink ()
label squeezeNull ()
template<int AnySizeMin>
void swap (PtrDynList< T, AnySizeMin > &other)
void transfer (PtrList< T > &list)
template<int AnySizeMin>
void transfer (PtrDynList< T, AnySizeMin > &list)
template<class... Args>
T & emplace_back (Args &&... args)
void push_back (T *ptr)
void push_back (std::unique_ptr< T > &&ptr)
void push_back (autoPtr< T > &&ptr)
void push_back (const refPtr< T > &ptr)
void push_back (const tmp< T > &ptr)
void push_back (PtrList< T > &&other)
template<int AnySizeMin>
void push_back (PtrDynList< T, AnySizeMin > &&other)
void pop_back (label n=1)
template<class... Args>
T & emplace (const label i, Args &&... args)
autoPtr< T > set (const label i, T *ptr)
autoPtr< T > set (const label i, std::unique_ptr< T > &&ptr)
autoPtr< T > set (const label i, autoPtr< T > &&ptr)
autoPtr< T > set (const label i, const refPtr< T > &ptr)
autoPtr< T > set (const label i, const tmp< T > &ptr)
void reorder (const labelUList &oldToNew)
void operator= (const PtrList< T > &list)
void operator= (const PtrDynList< T, SizeMin > &list)
template<int AnySizeMin>
void operator= (const PtrDynList< T, AnySizeMin > &list)
void operator= (PtrList< T > &&list)
void operator= (PtrDynList< T, SizeMin > &&list)
template<int AnySizeMin>
void operator= (PtrDynList< T, AnySizeMin > &&list)
void push_back (autoPtr< T > &ptr)=delete
autoPtr< T > set (const label i, autoPtr< T > &ptr)
void setSize (const label n)
void append (autoPtr< T > &ptr)
void append (T *ptr)
void append (std::unique_ptr< T > &&ptr)
void append (autoPtr< T > &&ptr)
void append (const refPtr< T > &ptr)
void append (const tmp< T > &ptr)
void append (PtrList< T > &&other)
template<int AnySizeMin>
void append (PtrDynList< T, AnySizeMin > &&other)
Public Member Functions inherited from PtrList< T >
constexpr PtrList () noexcept
PtrList (const label len)
PtrList (const PtrList< T > &list)
PtrList (PtrList< T > &&list)
PtrList (UList< T * > &list)
template<class CloneArg >
PtrList (const PtrList< T > &list, const CloneArg &cloneArgs)
PtrList (PtrList< T > &list, bool reuse)
PtrList (const SLPtrList< T > &list)
template<class INew >
PtrList (Istream &is, const INew &inew)
PtrList (Istream &is)
~PtrList ()
template<class... Args>
PtrList< T > clone (Args &&... args) const
const T * set (const label i) const
void clear ()
void free ()
void resize (const label newLen)
template<class... Args>
T & emplace_back (Args &&... args)
void push_back (T *ptr)
void push_back (std::unique_ptr< T > &&ptr)
void push_back (autoPtr< T > &&ptr)
void push_back (const refPtr< T > &ptr)
void push_back (const tmp< T > &ptr)
void push_back (PtrList< T > &&other)
template<class... Args>
T & emplace_set (const label i, Args &&... args)
template<class... Args>
T & emplace (const label i, Args &&... args)
autoPtr< T > set (const label i, T *ptr)
autoPtr< T > set (const label i, std::unique_ptr< T > &&ptr)
autoPtr< T > set (const label i, autoPtr< T > &&ptr)
autoPtr< T > set (const label i, const refPtr< T > &ptr)
autoPtr< T > set (const label i, const tmp< T > &ptr)
autoPtr< T > release (const label i)
void transfer (PtrList< T > &list)
void operator= (const PtrList< T > &list)
void operator= (PtrList< T > &&list)
void push_back (autoPtr< T > &ptr)=delete
autoPtr< T > set (const label i, autoPtr< T > &ptr)
void setSize (const label newLen)
void append (autoPtr< T > &ptr)
void append (T *ptr)
void append (std::unique_ptr< T > &&ptr)
void append (autoPtr< T > &&ptr)
void append (const refPtr< T > &ptr)
void append (const tmp< T > &ptr)
void append (PtrList< T > &&other)
template<class... Args>
Foam::PtrList< T > clone (Args &&... args) const
Public Member Functions inherited from UPtrList< T >
constexpr UPtrList () noexcept
UPtrList (const label len)
UPtrList (const UPtrList< T > &list)
UPtrList (UPtrList< T > &&list)
UPtrList (UPtrList< T > &list, bool reuse)
UPtrList (PtrList< T > &list)
UPtrList (const UList< T * > &list)
UPtrList (UList< T > &list)
bool empty () const noexcept
label size () const noexcept
label count () const noexcept
T & front ()
const T & front () const
T & back ()
const T & back () const
const T * test (const label i) const
const T * get (const label i) const
T * get (const label i)
const T * set (const label i) const
void clear ()
void free ()
void resize (const label newLen)
label squeezeNull ()
void trimTrailingNull ()
void push_back (T *ptr)
void push_back (UPtrList< T > &&other)
void swap (UPtrList< T > &list)
void transfer (UPtrList< T > &list)
T * set (const label i, T *ptr)
void reorder (const labelUList &oldToNew, const bool check=false)
void sortOrder (const labelUList &order, const bool check=false)
void checkNonNull () const
const T & at (const label i) const
T & at (const label i)
const T & operator[] (const label i) const
T & operator[] (const label i)
FOAM_DEPRECATED_FOR (2022-09, "get(), set() or test() methods") const T *operator()(const label i) const
void operator= (const UPtrList< T > &list)
void operator= (UPtrList< T > &&list)
T ** begin_ptr () noexcept
T ** end_ptr () noexcept
iterator begin ()
iterator end () noexcept
const_iterator cbegin () const
const_iterator cend () const noexcept
const_iterator begin () const
const_iterator end () const noexcept
void setSize (const label n)
T & first ()
const T & first () const
T & last ()
const T & last () const
void append (T *ptr)
void append (UPtrList< T > &&other)
Additional Inherited Members
Public Types inherited from UPtrList< T >
typedef T value_type
typedef T & reference
typedef const T & const_reference
Protected Member Functions inherited from PtrList< T >
template<class INew >
void readIstream (Istream &is, const INew &inew)
Protected Member Functions inherited from UPtrList< T >
void setAddressableSize (const label n) noexcept
label find_next (label pos) const
UPtrList (Detail::PtrListDetail< T > &&ptrs)
Protected Attributes inherited from UPtrList< T >
Detail::PtrListDetail< T > ptrs_
Detailed Description
template<class T, int SizeMin = 64>
class Foam::PtrDynList< T, SizeMin >
A dynamically resizable PtrList with allocation management.
See also
Foam::UPtrList Foam::PtrList
Source files
PtrDynList.H
PtrDynListI.H
Definition at line 55 of file PtrDynList.H.
Constructor & Destructor Documentation
PtrDynList() [1/6]
template<class T , int SizeMin> constexpr PtrDynList () inline constexpr noexcept
Definition at line 28 of file PtrDynListI.H.
PtrDynList() [2/6]
template<class T , int SizeMin> PtrDynList (const label len) inline explicit
Definition at line 36 of file PtrDynListI.H.
References PtrDynList< T, SizeMin >::reserve().
PtrDynList() [3/6]
template<class T , int SizeMin> PtrDynList (const PtrDynList< T, SizeMin > & list) inline
Definition at line 46 of file PtrDynListI.H.
PtrDynList() [4/6]
template<class T , int SizeMin> PtrDynList (PtrDynList< T, SizeMin > && list) inline
Definition at line 57 of file PtrDynListI.H.
PtrDynList() [5/6]
template<class T , int SizeMin> PtrDynList (PtrList< T > && list) inline
Definition at line 70 of file PtrDynListI.H.
PtrDynList() [6/6]
template<class T , int SizeMin> PtrDynList (UList< T * > & list) inline explicit
Definition at line 81 of file PtrDynListI.H.
~PtrDynList()
template<class T , int SizeMin = 64> ~PtrDynList () default
Member Function Documentation
capacity()
template<class T , int SizeMin = 64> label capacity () const inline noexcept
Definition at line 99 of file PtrDynList.H.
reserve()
template<class T , int SizeMin> void reserve (const label len) inline
Definition at line 91 of file PtrDynListI.H.
References Foam::max(), PtrList< T >::resize(), and UPtrList< T >::size().
Referenced by PtrDynList< T, SizeMin >::PtrDynList().
resize()
template<class T , int SizeMin> void resize (const label newLen) inline
Definition at line 108 of file PtrDynListI.H.
Referenced by PtrDynList< T, SizeMin >::setSize().
clear()
template<class T , int SizeMin> void clear () inline
Definition at line 137 of file PtrDynListI.H.
clearStorage()
template<class T , int SizeMin> void clearStorage () inline
Definition at line 145 of file PtrDynListI.H.
expandStorage()
template<class T , int SizeMin> Foam::label expandStorage () inline noexcept
Definition at line 153 of file PtrDynListI.H.
shrink()
template<class T , int SizeMin> void shrink () inline
Definition at line 165 of file PtrDynListI.H.
squeezeNull()
template<class T , int SizeMin> Foam::label squeezeNull () inline
Definition at line 180 of file PtrDynListI.H.
swap()
template<class T , int SizeMin> template<int AnySizeMin> void swap (PtrDynList< T, AnySizeMin > & other) inline
Definition at line 190 of file PtrDynListI.H.
transfer() [1/2]
template<class T , int SizeMin> void transfer (PtrList< T > & list) inline
Definition at line 213 of file PtrDynListI.H.
transfer() [2/2]
template<class T , int SizeMin> template<int AnySizeMin> void transfer (PtrDynList< T, AnySizeMin > & list) inline
Definition at line 232 of file PtrDynListI.H.
References PtrList< T >::transfer().
emplace_back()
template<class T , int SizeMin> template<class... Args> T & emplace_back (Args &&... args) inline
Definition at line 255 of file PtrDynListI.H.
References args, and T.
push_back() [1/8]
template<class T , int SizeMin> void push_back (T * ptr) inline
Definition at line 264 of file PtrDynListI.H.
References resize().
Referenced by PtrDynList< T, SizeMin >::append(), PtrDynList< T, SizeMin >::append(), PtrDynList< T, SizeMin >::append(), PtrDynList< T, SizeMin >::append(), PtrDynList< T, SizeMin >::append(), PtrDynList< T, SizeMin >::append(), PtrDynList< T, SizeMin >::append(), and PtrDynList< T, SizeMin >::append().
push_back() [2/8]
template<class T , int SizeMin> void push_back (std::unique_ptr< T > && ptr) inline
Definition at line 273 of file PtrDynListI.H.
push_back() [3/8]
template<class T , int SizeMin> void push_back (autoPtr< T > && ptr) inline
Definition at line 280 of file PtrDynListI.H.
push_back() [4/8]
template<class T , int SizeMin> void push_back (const refPtr< T > & ptr) inline
Definition at line 287 of file PtrDynListI.H.
push_back() [5/8]
template<class T , int SizeMin> void push_back (const tmp< T > & ptr) inline
Definition at line 294 of file PtrDynListI.H.
push_back() [6/8]
template<class T , int SizeMin> void push_back (PtrList< T > && other) inline
Definition at line 301 of file PtrDynListI.H.
References PtrList< T >::clear(), PtrList< T >::release(), resize(), and UPtrList< T >::size().
push_back() [7/8]
template<class T , int SizeMin> template<int AnySizeMin> void push_back (PtrDynList< T, AnySizeMin > && other) inline
Definition at line 319 of file PtrDynListI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, PtrList< T >::release(), resize(), and UPtrList< T >::size().
pop_back()
template<class T , int SizeMin> void pop_back (label n = 1) inline
Definition at line 350 of file PtrDynListI.H.
References clear(), n, and resize().
emplace()
template<class T , int SizeMin> template<class... Args> T & emplace (const label i, Args &&... args) inline
Definition at line 365 of file PtrDynListI.H.
References args, and T.
set() [1/6]
template<class T , int SizeMin> Foam::autoPtr< T > set (const label i, T * ptr) inline
Definition at line 378 of file PtrDynListI.H.
References resize().
Referenced by PtrDynList< T, SizeMin >::set().
set() [2/6]
template<class T , int SizeMin> Foam::autoPtr< T > set (const label i, std::unique_ptr< T > && ptr) inline
Definition at line 394 of file PtrDynListI.H.
References PtrList< T >::release().
set() [3/6]
template<class T , int SizeMin> Foam::autoPtr< T > set (const label i, autoPtr< T > && ptr) inline
Definition at line 405 of file PtrDynListI.H.
References PtrList< T >::release().
set() [4/6]
template<class T , int SizeMin> Foam::autoPtr< T > set (const label i, const refPtr< T > & ptr) inline
Definition at line 416 of file PtrDynListI.H.
set() [5/6]
template<class T , int SizeMin> Foam::autoPtr< T > set (const label i, const tmp< T > & ptr) inline
Definition at line 428 of file PtrDynListI.H.
reorder()
template<class T , int SizeMin> void reorder (const labelUList & oldToNew) inline
Definition at line 439 of file PtrDynListI.H.
References UPtrList< T >::reorder().
operator=() [1/6]
template<class T , int SizeMin> void operator= (const PtrList< T > & list) inline
Definition at line 450 of file PtrDynListI.H.
References PtrList< T >::operator=(), and UPtrList< T >::size().
operator=() [2/6]
template<class T , int SizeMin> void operator= (const PtrDynList< T, SizeMin > & list) inline
Definition at line 466 of file PtrDynListI.H.
References PtrList< T >::operator=(), and UPtrList< T >::size().
operator=() [3/6]
template<class T , int SizeMin> template<int AnySizeMin> void operator= (const PtrDynList< T, AnySizeMin > & list) inline
Definition at line 483 of file PtrDynListI.H.
References PtrList< T >::operator=(), and UPtrList< T >::size().
operator=() [4/6]
template<class T , int SizeMin> void operator= (PtrList< T > && list) inline
Definition at line 503 of file PtrDynListI.H.
operator=() [5/6]
template<class T , int SizeMin> void operator= (PtrDynList< T, SizeMin > && list) inline
Definition at line 513 of file PtrDynListI.H.
operator=() [6/6]
template<class T , int SizeMin> template<int AnySizeMin> void operator= (PtrDynList< T, AnySizeMin > && list) inline
Definition at line 524 of file PtrDynListI.H.
push_back() [8/8]
template<class T , int SizeMin = 64> void push_back (autoPtr< T > & ptr) delete
set() [6/6]
template<class T , int SizeMin = 64> autoPtr< T > set (const label i, autoPtr< T > & ptr) inline
Definition at line 230 of file PtrDynList.H.
References PtrList< T >::release(), and PtrDynList< T, SizeMin >::set().
setSize()
template<class T , int SizeMin = 64> void setSize (const label n) inline
Definition at line 236 of file PtrDynList.H.
References PtrDynList< T, SizeMin >::resize().
append() [1/8]
template<class T , int SizeMin = 64> void append (autoPtr< T > & ptr) inline
Definition at line 239 of file PtrDynList.H.
References PtrDynList< T, SizeMin >::push_back().
append() [2/8]
template<class T , int SizeMin = 64> void append (T * ptr) inline
Definition at line 243 of file PtrDynList.H.
References PtrDynList< T, SizeMin >::push_back().
append() [3/8]
template<class T , int SizeMin = 64> void append (std::unique_ptr< T > && ptr) inline
Definition at line 247 of file PtrDynList.H.
References PtrDynList< T, SizeMin >::push_back().
append() [4/8]
template<class T , int SizeMin = 64> void append (autoPtr< T > && ptr) inline
Definition at line 254 of file PtrDynList.H.
References PtrDynList< T, SizeMin >::push_back().
append() [5/8]
template<class T , int SizeMin = 64> void append (const refPtr< T > & ptr) inline
Definition at line 258 of file PtrDynList.H.
References PtrDynList< T, SizeMin >::push_back().
append() [6/8]
template<class T , int SizeMin = 64> void append (const tmp< T > & ptr) inline
Definition at line 262 of file PtrDynList.H.
References PtrDynList< T, SizeMin >::push_back().
append() [7/8]
template<class T , int SizeMin = 64> void append (PtrList< T > && other) inline
Definition at line 266 of file PtrDynList.H.
References PtrDynList< T, SizeMin >::push_back().
append() [8/8]
template<class T , int SizeMin = 64> template<int AnySizeMin> void append (PtrDynList< T, AnySizeMin > && other) inline
Definition at line 270 of file PtrDynList.H.
References PtrDynList< T, SizeMin >::push_back().
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/PtrLists/PtrDynList/PtrDynList.H
src/OpenFOAM/containers/PtrLists/PtrDynList/PtrDynListI.H