OpenFOAM: function1Base Class Reference
function1Base Class Reference
Base class for template-invariant parts of Function1.
#include <function1Base.H>
Public Member Functions
function1Base (const word &entryName, const objectRegistry *obrPtr=nullptr)
function1Base (const word &entryName, const dictionary &dict, const objectRegistry *obrPtr=nullptr)
function1Base (const function1Base &rhs)
virtual ~function1Base ()
const word & name () const noexcept
const objectRegistry * whichDb () const noexcept
void resetDb (const objectRegistry *obrPtr=nullptr) noexcept
void resetDb (const objectRegistry &db) noexcept
const objectRegistry & obr () const
bool isTime () const noexcept
const Time & time () const
template<class MeshType >
const MeshType & mesh (const word &regionName=word::null) const
virtual void userTimeToTime (const Time &t)
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Protected Member Functions
void operator= (const function1Base &)=delete
Protected Attributes
const word name_
const objectRegistry * obrPtr_
Detailed Description
Base class for template-invariant parts of Function1.
Source files
function1Base.H
function1Base.C
Definition at line 50 of file function1Base.H.
Constructor & Destructor Documentation
function1Base() [1/3]
function1Base (const word & entryName, const objectRegistry * obrPtr = nullptr) explicit
Definition at line 43 of file function1Base.C.
function1Base() [2/3]
function1Base (const word & entryName, const dictionary & dict, const objectRegistry * obrPtr = nullptr)
Definition at line 55 of file function1Base.C.
function1Base() [3/3]
function1Base (const function1Base & rhs) explicit
Definition at line 68 of file function1Base.C.
~function1Base()
~function1Base () virtual
Definition at line 79 of file function1Base.C.
Member Function Documentation
operator=()
void operator= (const function1Base &) protected delete
name()
const word & name () const inline noexcept
Definition at line 109 of file function1Base.H.
References function1Base::name_.
whichDb()
const objectRegistry * whichDb () const inline noexcept
Definition at line 115 of file function1Base.H.
References function1Base::obrPtr_.
Referenced by function1Base::mesh().
resetDb() [1/2]
void resetDb (const objectRegistry * obrPtr = nullptr) noexcept
Definition at line 116 of file function1Base.C.
resetDb() [2/2]
void resetDb (const objectRegistry & db) noexcept
Definition at line 122 of file function1Base.C.
obr()
const Foam::objectRegistry & obr () const
Definition at line 85 of file function1Base.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
isTime()
bool isTime () const noexcept
Definition at line 110 of file function1Base.C.
time()
const Foam::Time & time () const
Definition at line 97 of file function1Base.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
mesh()
template<class MeshType > const MeshType & mesh (const word & regionName = word::null) const inline
Definition at line 140 of file function1Base.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, objectRegistry::lookupObject(), regionName, and function1Base::whichDb().
userTimeToTime()
void userTimeToTime (const Time & t) virtual
Reimplemented in Polynomial< Type >, ramp, Sine< Type >, and TableBase< Type >.
Definition at line 128 of file function1Base.C.
Member Data Documentation
name_
const word name_ protected
Definition at line 65 of file function1Base.H.
Referenced by function1Base::name().
obrPtr_
const objectRegistry* obrPtr_ protected
Definition at line 68 of file function1Base.H.
Referenced by function1Base::whichDb().
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/functions/Function1/Function1/function1Base.H
src/OpenFOAM/primitives/functions/Function1/Function1/function1Base.C