OpenFOAM: UPstream::Request Class Reference
UPstream::Request Class Reference
#include <UPstream.H>
Public Types
typedef std::intptr_t value_type
Public Member Functions
Request (const Request &) noexcept=default
Request (Request &&) noexcept=default
Request & operator= (const Request &) noexcept=default
Request & operator= (Request &&) noexcept=default
bool operator== (const Request &rhs) const noexcept
bool operator!= (const Request &rhs) const noexcept
Request () noexcept
Request (const void *p) noexcept
Request (value_type val) noexcept
value_type value () const noexcept
const void * pointer () const noexcept
bool good () const noexcept
void reset () noexcept
void cancel ()
void free ()
bool finished ()
void wait ()
Detailed Description
Definition at line 1213 of file UPstream.H.
Member Typedef Documentation
value_type
typedef std::intptr_t value_type
Definition at line 1220 of file UPstream.H.
Constructor & Destructor Documentation
Request() [1/5]
Request (const Request &) default noexcept
Request() [2/5]
Request (Request &&) default noexcept
Request() [3/5]
Request () noexcept
Definition at line 25 of file UPstreamRequest.C.
Request() [4/5]
Request (const void * p) inline explicit noexcept
Definition at line 1268 of file UPstream.H.
Request() [5/5]
Request (value_type val) inline explicit noexcept
Definition at line 1274 of file UPstream.H.
Member Function Documentation
operator=() [1/2]
Request & operator= (const Request &) default noexcept
operator=() [2/2]
Request & operator= (Request &&) default noexcept
operator==()
bool operator== (const Request & rhs) const inline noexcept
Definition at line 1250 of file UPstream.H.
operator!=()
bool operator!= (const Request & rhs) const inline noexcept
Definition at line 1256 of file UPstream.H.
value()
value_type value () const inline noexcept
Definition at line 1283 of file UPstream.H.
pointer()
const void * pointer () const inline noexcept
Definition at line 1286 of file UPstream.H.
good()
bool good () const noexcept
Definition at line 33 of file UPstreamRequest.C.
reset()
void reset () noexcept
Definition at line 39 of file UPstreamRequest.C.
cancel()
void cancel () inline
Definition at line 1298 of file UPstream.H.
References UPstream::cancelRequest().
free()
void free () inline
Definition at line 1301 of file UPstream.H.
References UPstream::freeRequest().
finished()
bool finished () inline
Definition at line 1304 of file UPstream.H.
References UPstream::finishedRequest().
wait()
void wait () inline
Definition at line 1307 of file UPstream.H.
References UPstream::waitRequest().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOstreams/Pstreams/UPstream.H
src/Pstream/dummy/UPstreamRequest.C
src/Pstream/mpi/UPstreamRequest.C