OpenFOAM: rPolynomial< Specie > Class Template Reference
rPolynomial< Specie > Class Template Reference
Reciprocal polynomial equation of state for liquids and solids.
#include <rPolynomial.H>
Public Member Functions
rPolynomial (const Specie &sp, const coeffList &coeffs)
rPolynomial (const dictionary &dict)
rPolynomial (const word &name, const rPolynomial &)
autoPtr< rPolynomial > clone () const
scalar rho (scalar p, scalar T) const
scalar H (const scalar p, const scalar T) const
scalar Cp (scalar p, scalar T) const
scalar E (const scalar p, const scalar T) const
scalar Cv (scalar p, scalar T) const
scalar S (const scalar p, const scalar T) const
scalar psi (scalar p, scalar T) const
scalar Z (scalar p, scalar T) const
scalar CpMCv (scalar p, scalar T) const
void write (Ostream &os) const
void operator+= (const rPolynomial &)
void operator*= (const scalar)
Static Public Member Functions
static autoPtr< rPolynomial > New (const dictionary &dict)
static word typeName ()
Static Public Attributes
static const bool incompressible = false
static const bool isochoric = false
Friends
rPolynomial operator+ (const rPolynomial &, const rPolynomial &)
rPolynomial operator* (const scalar s, const rPolynomial &)
rPolynomial operator== (const rPolynomial &, const rPolynomial &)
Ostream & operator<< (Ostream &, const rPolynomial &)
Detailed Description
template<class Specie>
class Foam::rPolynomial< Specie >
Reciprocal polynomial equation of state for liquids and solids.
This polynomial for the reciprocal of the density provides a much better fit than the equivalent polynomial for the density and has the advantage that it support coefficient mixing to support liquid and solid mixtures in an efficient manner.
Usage
Property Description
C Density polynomial coefficients
Example of the specification of the equation of state for pure water:
    equationOfState
    {
        C (0.001278 -2.1055e-06 3.9689e-09 4.3772e-13 -2.0225e-16);
    }
Note: This fit is based on the small amount of data which is freely available for the range 20-65degC and 1-100bar.
Source files
rPolynomial.H
rPolynomialI.H
rPolynomial.C
Definition at line 113 of file rPolynomial.H.
Constructor & Destructor Documentation
rPolynomial() [1/3]
template<class Specie > rPolynomial (const Specie & sp, const coeffList & coeffs) inline
Definition at line 26 of file rPolynomialI.H.
rPolynomial() [2/3]
template<class Specie > rPolynomial (const dictionary & dict)
Definition at line 28 of file rPolynomial.C.
rPolynomial() [3/3]
template<class Specie > rPolynomial (const word & name, const rPolynomial< Specie > &) inline
Member Function Documentation
clone()
template<class Specie > Foam::autoPtr< Foam::rPolynomial< Specie > > clone () const inline
Definition at line 53 of file rPolynomialI.H.
References Foam::New().
New()
template<class Specie > Foam::autoPtr< Foam::rPolynomial< Specie > > New (const dictionary & dict) inline static
Definition at line 61 of file rPolynomialI.H.
References dict, and Foam::New().
typeName()
template<class Specie > static word typeName () inline static
Definition at line 170 of file rPolynomial.H.
rho()
template<class Specie > Foam::scalar rho (scalar p, scalar T) const inline
Definition at line 73 of file rPolynomialI.H.
References p, and T.
H()
template<class Specie > Foam::scalar H (const scalar p, const scalar T) const inline
Definition at line 80 of file rPolynomialI.H.
Cp()
template<class Specie > Foam::scalar Cp (scalar p, scalar T) const inline
Definition at line 87 of file rPolynomialI.H.
E()
template<class Specie > Foam::scalar E (const scalar p, const scalar T) const inline
Definition at line 94 of file rPolynomialI.H.
Cv()
template<class Specie > Foam::scalar Cv (scalar p, scalar T) const inline
Definition at line 101 of file rPolynomialI.H.
S()
template<class Specie > Foam::scalar S (const scalar p, const scalar T) const inline
Definition at line 108 of file rPolynomialI.H.
psi()
template<class Specie > Foam::scalar psi (scalar p, scalar T) const inline
Definition at line 115 of file rPolynomialI.H.
References p, rho, Foam::sqr(), and T.
Z()
template<class Specie > Foam::scalar Z (scalar p, scalar T) const inline
Definition at line 122 of file rPolynomialI.H.
CpMCv()
template<class Specie > Foam::scalar CpMCv (scalar p, scalar T) const inline
Definition at line 129 of file rPolynomialI.H.
write()
template<class Specie > void write (Ostream & os) const
Definition at line 38 of file rPolynomial.C.
References Ostream::beginBlock(), Ostream::endBlock(), os(), and Ostream::writeEntry().
operator+=()
template<class Specie > void operator+= (const rPolynomial< Specie > &) inline
Definition at line 138 of file rPolynomialI.H.
References Foam::mag(), rp(), and Y.
operator*=()
template<class Specie > void operator*= (const scalar s) inline
Definition at line 154 of file rPolynomialI.H.
References s().
Friends And Related Symbol Documentation
operator+
template<class Specie > rPolynomial operator+ (const rPolynomial< Specie > & , const rPolynomial< Specie > &) friend
operator*
template<class Specie > rPolynomial operator* (const scalar s, const rPolynomial< Specie > &) friend
operator==
template<class Specie > rPolynomial operator== (const rPolynomial< Specie > & , const rPolynomial< Specie > &) friend
operator<<
template<class Specie > Ostream & operator<< (Ostream & , const rPolynomial< Specie > &) friend
Member Data Documentation
incompressible
template<class Specie > const bool incompressible = false static
Definition at line 179 of file rPolynomial.H.
isochoric
template<class Specie > const bool isochoric = false static
Definition at line 182 of file rPolynomial.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/equationOfState/rPolynomial/rPolynomial.H
src/thermophysicalModels/specie/equationOfState/rPolynomial/rPolynomial.C
src/thermophysicalModels/specie/equationOfState/rPolynomial/rPolynomialI.H