OpenFOAM: fileWriter Class Reference
fileWriter Class Reference abstract
Base class for VTK output writers that handle geometry and fields (eg, vtp, vtu data). These output formats are structured as DECLARED, FIELD_DATA, PIECE followed by any CELL_DATA or POINT_DATA.
#include <foamVtkFileWriter.H>
Public Member Functions
fileWriter (const vtk::fileTag contentType, const vtk::outputOptions opts)
virtual ~fileWriter ()
vtk::fileTag contentType () const noexcept
vtk::outputOptions opts () const noexcept
word ext () const
bool legacy () const noexcept
bool parallel () const noexcept
const word & state () const
const fileName & output () const noexcept
virtual bool open (const fileName &file, bool parallel=UPstream::parRun())
void close ()
virtual bool beginFile (std::string title="")
bool beginFieldData (label nFields=0)
virtual bool writeGeometry ()=0
virtual bool beginCellData (label nFields=0)=0
virtual bool beginPointData (label nFields=0)=0
bool isCellData () const noexcept
bool isPointData () const noexcept
label nCellData () const noexcept
label nPointData () const noexcept
bool endFieldData ()
bool endCellData ()
bool endPointData ()
void writeTimeValue (scalar timeValue)
Protected Types
enum outputState : uint8_t {
CLOSED = 0 , OPENED , DECLARED , FIELD_DATA ,
PIECE , CELL_DATA , POINT_DATA
}
Protected Member Functions
void checkFormatterValidity () const
Ostream & reportBadState (Ostream &, outputState expected) const
Ostream & reportBadState (Ostream &, outputState, outputState) const
std::ofstream & os () noexcept
vtk::formatter & format ()
bool isState (outputState test) const noexcept
bool notState (outputState test) const noexcept
template<class Type >
void beginDataArray (const word &fieldName, const label nValues)
void endDataArray ()
void beginPoints (const label nPoints)
void endPoints ()
bool enter_Piece ()
bool endPiece ()
bool enter_CellData (label nEntries, label nFields)
bool enter_PointData (label nEntries, label nFields)
bool exit_File ()
template<class Type >
void writeUniform (const word &fieldName, const Type &val, const label nValues)
template<class Type >
void writeBasicField (const word &fieldName, const UList< Type > &field)
bool writeProcIDs (const label nValues)
fileWriter (const fileWriter &)=delete
void operator= (const fileWriter &)=delete
Protected Attributes
outputState state_
vtk::fileTag contentType_
bool parallel_
vtk::outputOptions opts_
label nCellData_
label nPointData_
fileName outputFile_
autoPtr< vtk::formatter > format_
std::ofstream os_
Static Protected Attributes
static const Enum< outputState > stateNames
Detailed Description
Base class for VTK output writers that handle geometry and fields (eg, vtp, vtu data). These output formats are structured as DECLARED, FIELD_DATA, PIECE followed by any CELL_DATA or POINT_DATA.
This writer base tracks these expected output states internally to help avoid logic errors in the callers.
The FieldData element must be placed prior to writing any geometry Piece. This moves the information to the front of the output file for visibility and simplifies the logic when creating multi-piece geometries.
Source files
foamVtkFileWriter.H
foamVtkFileWriter.C
foamVtkFileWriterI.H
foamVtkFileWriterTemplates.C
Definition at line 64 of file foamVtkFileWriter.H.
Member Enumeration Documentation
outputState
enum outputState : uint8_t protected
Enumerator
CLOSED
File is closed.
OPENED
File is opened.
DECLARED
File contents declared (VTKFile header written)
FIELD_DATA
Inside FieldData.
PIECE
Inside Piece (after geometry write)
CELL_DATA
Inside CellData.
POINT_DATA
Inside PointData.
Definition at line 71 of file foamVtkFileWriter.H.
Constructor & Destructor Documentation
fileWriter() [1/2]
fileWriter (const fileWriter &) protected delete
fileWriter() [2/2]
fileWriter (const vtk::fileTag contentType, const vtk::outputOptions opts)
Definition at line 280 of file foamVtkFileWriter.C.
References outputOptions::append(), and fileWriter::opts_.
~fileWriter()
~fileWriter () virtual
Definition at line 303 of file foamVtkFileWriter.C.
Member Function Documentation
checkFormatterValidity()
void checkFormatterValidity () const protected
Definition at line 45 of file foamVtkFileWriter.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, fileWriter::format_, UPstream::master(), and fileWriter::parallel_.
reportBadState() [1/2]
Foam::Ostream & reportBadState (Ostream & os, outputState expected) const protected
Definition at line 57 of file foamVtkFileWriter.C.
References os().
Referenced by internalWriter::write(), patchWriter::write(), lagrangianWriter::write(), coordSetWriter::writePointData(), internalMeshWriter::writeUniform(), patchMeshWriter::writeUniform(), and polyWriter::writeUniformValue().
reportBadState() [2/2]
Foam::Ostream & reportBadState (Ostream & os, outputState expected1, outputState expected2) const protected
Definition at line 69 of file foamVtkFileWriter.C.
References os().
os()
std::ofstream & os () inline protected noexcept
Definition at line 23 of file foamVtkFileWriterI.H.
References fileWriter::os_.
format()
Foam::vtk::formatter & format () inline protected
Definition at line 29 of file foamVtkFileWriterI.H.
Referenced by fileWriter::beginDataArray(), patchMeshWriter::beginPiece(), internalWriter::write(), patchWriter::write(), and coordSetWriter::writePointData().
isState()
bool isState (outputState test) const inline protected noexcept
Definition at line 35 of file foamVtkFileWriterI.H.
Referenced by internalWriter::write(), patchWriter::write(), lagrangianWriter::write(), coordSetWriter::writePointData(), internalMeshWriter::writeUniform(), patchMeshWriter::writeUniform(), and polyWriter::writeUniformValue().
notState()
bool notState (outputState test) const inline protected noexcept
Definition at line 41 of file foamVtkFileWriterI.H.
beginDataArray()
template<class Type > void beginDataArray (const word & fieldName, const label nValues) protected
Definition at line 27 of file foamVtkFileWriterTemplates.C.
References formatter::beginDataArray(), fileWriter::format(), fileWriter::format_, fileWriter::legacy(), and formatter::writeSize().
endDataArray()
void endDataArray () protected
Definition at line 199 of file foamVtkFileWriter.C.
References format().
Referenced by internalWriter::write(), patchWriter::write(), and coordSetWriter::writePointData().
beginPoints()
void beginPoints (const label nPoints) protected
Definition at line 209 of file foamVtkFileWriter.C.
References Foam::vtk::legacy::beginPoints(), format(), nPoints, and Foam::vtk::POINTS.
endPoints()
void endPoints () protected
Definition at line 232 of file foamVtkFileWriter.C.
References format(), and Foam::vtk::POINTS.
enter_Piece()
bool enter_Piece () protected
Definition at line 82 of file foamVtkFileWriter.C.
References Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
endPiece()
bool endPiece () protected
Definition at line 103 of file foamVtkFileWriter.C.
References format().
enter_CellData()
bool enter_CellData (label nEntries, label nFields) protected
Definition at line 125 of file foamVtkFileWriter.C.
References Foam::vtk::legacy::beginCellData(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, and format().
enter_PointData()
bool enter_PointData (label nEntries, label nFields) protected
Definition at line 162 of file foamVtkFileWriter.C.
References Foam::vtk::legacy::beginPointData(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, and format().
exit_File()
bool exit_File () protected
Definition at line 248 of file foamVtkFileWriter.C.
References Foam::endl(), Foam::vtk::fileTagNames, format(), Foam::nl, and WarningInFunction.
writeUniform()
template<class Type > void writeUniform (const word & fieldName, const Type & val, const label nValues) protected
Definition at line 81 of file foamVtkFileWriterTemplates.C.
References format(), Foam::reduce(), Foam::vtk::write(), and Foam::vtk::writeValueParallel().
writeBasicField()
template<class Type > void writeBasicField (const word & fieldName, const UList< Type > & field) protected
Definition at line 111 of file foamVtkFileWriterTemplates.C.
References field(), format(), Foam::reduce(), UPtrList< T >::size(), Foam::vtk::writeList(), and Foam::vtk::writeListParallel().
writeProcIDs()
bool writeProcIDs (const label nValues) protected
Definition at line 537 of file foamVtkFileWriter.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, format(), UPstream::master(), UPstream::myProcNo(), Foam::nl, UPstream::parRun(), procAddr(), Foam::returnReduceOr(), and Foam::vtk::write().
Referenced by lineWriter::writeProcIDs(), surfaceWriter::writeProcIDs(), internalMeshWriter::writeProcIDs(), GenericPatchWriter< PatchType >::writeProcIDs(), and patchMeshWriter::writeProcIDs().
operator=()
void operator= (const fileWriter &) protected delete
contentType()
Foam::vtk::fileTag contentType () const inline noexcept
Definition at line 49 of file foamVtkFileWriterI.H.
opts()
Foam::vtk::outputOptions opts () const inline noexcept
Definition at line 55 of file foamVtkFileWriterI.H.
Referenced by polyWriter::ext(), internalMeshWriter::ext(), and patchMeshWriter::ext().
ext()
Foam::word ext () const inline
Definition at line 61 of file foamVtkFileWriterI.H.
References word::ext().
Referenced by vtkWriter::path(), and vtkWriter::write().
legacy()
bool legacy () const inline noexcept
Definition at line 67 of file foamVtkFileWriterI.H.
Referenced by fileWriter::beginDataArray(), and patchMeshWriter::beginPiece().
parallel()
bool parallel () const inline noexcept
Definition at line 73 of file foamVtkFileWriterI.H.
Referenced by coordSetWriter::coordSetWriter(), coordSetWriter::coordSetWriter(), internalMeshWriter::internalMeshWriter(), internalMeshWriter::internalMeshWriter(), lagrangianWriter::lagrangianWriter(), lagrangianWriter::lagrangianWriter(), lineWriter::lineWriter(), lineWriter::lineWriter(), patchMeshWriter::patchMeshWriter(), patchMeshWriter::patchMeshWriter(), polyWriter::polyWriter(), polyWriter::polyWriter(), surfaceFieldWriter::surfaceFieldWriter(), surfaceFieldWriter::surfaceFieldWriter(), surfaceWriter::surfaceWriter(), and surfaceWriter::surfaceWriter().
state()
const Foam::word & state () const inline
Definition at line 79 of file foamVtkFileWriterI.H.
output()
const Foam::fileName & output () const inline noexcept
Definition at line 85 of file foamVtkFileWriterI.H.
open()
bool open (const fileName & file, bool parallel = UPstream::parRun()) virtual
Reimplemented in coordSetWriter.
Definition at line 311 of file foamVtkFileWriter.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::vtk::fileExtension, Foam::vtk::legacy::fileExtension, UPstream::master(), Foam::mkDir(), UPstream::parRun(), and fileName::remove_ext().
Referenced by searchableSurfaces::checkIntersection(), internalMeshWriter::internalMeshWriter(), internalMeshWriter::internalMeshWriter(), lagrangianWriter::lagrangianWriter(), lagrangianWriter::lagrangianWriter(), lineWriter::lineWriter(), lineWriter::lineWriter(), coordSetWriter::open(), patchMeshWriter::patchMeshWriter(), patchMeshWriter::patchMeshWriter(), polyWriter::polyWriter(), polyWriter::polyWriter(), surfaceFieldWriter::surfaceFieldWriter(), surfaceFieldWriter::surfaceFieldWriter(), surfaceWriter::surfaceWriter(), surfaceWriter::surfaceWriter(), FacePostProcessing< CloudType >::write(), and ParticleCollector< CloudType >::write().
close()
void close ()
Definition at line 369 of file foamVtkFileWriter.C.
Referenced by searchableSurfaces::checkIntersection(), and Foam::vtkWritePatchEdges().
beginFile()
bool beginFile (std::string title = "") virtual
Reimplemented in surfaceFieldWriter, lineWriter, surfaceWriter, lagrangianWriter, coordSetWriter, internalMeshWriter, patchMeshWriter, and GenericPatchWriter< PatchType >.
Definition at line 385 of file foamVtkFileWriter.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::vtk::legacy::fileHeader(), and format().
Referenced by surfaceFieldWriter::beginFile(), lineWriter::beginFile(), surfaceWriter::beginFile(), lagrangianWriter::beginFile(), coordSetWriter::beginFile(), internalMeshWriter::beginFile(), patchMeshWriter::beginFile(), and GenericPatchWriter< PatchType >::beginFile().
beginFieldData()
bool beginFieldData (label nFields = 0)
Definition at line 424 of file foamVtkFileWriter.C.
References Foam::vtk::legacy::beginFieldData(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, and format().
writeGeometry()
virtual bool writeGeometry () pure virtual
Implemented in surfaceFieldWriter, lineWriter, polyWriter, surfaceWriter, lagrangianWriter, coordSetWriter, internalMeshWriter, GenericPatchWriter< PatchType >, and patchMeshWriter.
beginCellData()
virtual bool beginCellData (label nFields = 0) pure virtual
Implemented in surfaceFieldWriter, polyWriter, lagrangianWriter, internalMeshWriter, and patchMeshWriter.
beginPointData()
virtual bool beginPointData (label nFields = 0) pure virtual
Implemented in surfaceFieldWriter, polyWriter, lagrangianWriter, internalMeshWriter, and patchMeshWriter.
isCellData()
bool isCellData () const inline noexcept
Definition at line 103 of file foamVtkFileWriterI.H.
isPointData()
bool isPointData () const inline noexcept
Definition at line 109 of file foamVtkFileWriterI.H.
Referenced by GenericPatchWriter< PatchType >::writeProcIDs().
nCellData()
Foam::label nCellData () const inline noexcept
Definition at line 91 of file foamVtkFileWriterI.H.
nPointData()
Foam::label nPointData () const inline noexcept
Definition at line 97 of file foamVtkFileWriterI.H.
endFieldData()
bool endFieldData ()
Definition at line 456 of file foamVtkFileWriter.C.
References format().
endCellData()
bool endCellData ()
Definition at line 474 of file foamVtkFileWriter.C.
References format().
Referenced by lumpedPointMovement::writeVTP(), and lumpedPointMovement::writeZonesVTP().
endPointData()
bool endPointData ()
Definition at line 492 of file foamVtkFileWriter.C.
References format().
Referenced by lumpedPointMovement::writeVTP().
writeTimeValue()
void writeTimeValue (scalar timeValue)
Definition at line 510 of file foamVtkFileWriter.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, format(), and Foam::vtk::legacy::writeTimeValue().
Referenced by lineWriter::writeTimeValue(), surfaceWriter::writeTimeValue(), and coordSetWriter::writeTimeValue().
Member Data Documentation
stateNames
const Foam::Enum< Foam::vtk::fileWriter::outputState > stateNames static protected
Definition at line 83 of file foamVtkFileWriter.H.
state_
outputState state_ protected
Definition at line 87 of file foamVtkFileWriter.H.
contentType_
vtk::fileTag contentType_ protected
Definition at line 90 of file foamVtkFileWriter.H.
parallel_
bool parallel_ protected
Definition at line 93 of file foamVtkFileWriter.H.
Referenced by patchMeshWriter::beginPiece(), fileWriter::checkFormatterValidity(), internalWriter::write(), and patchWriter::write().
opts_
vtk::outputOptions opts_ protected
Definition at line 96 of file foamVtkFileWriter.H.
Referenced by fileWriter::fileWriter(), internalMeshWriter::internalMeshWriter(), lagrangianWriter::lagrangianWriter(), patchMeshWriter::patchMeshWriter(), polyWriter::polyWriter(), and surfaceFieldWriter::surfaceFieldWriter().
nCellData_
label nCellData_ protected
Definition at line 99 of file foamVtkFileWriter.H.
Referenced by lagrangianWriter::write(), internalMeshWriter::writeUniform(), patchMeshWriter::writeUniform(), and polyWriter::writeUniformValue().
nPointData_
label nPointData_ protected
Definition at line 102 of file foamVtkFileWriter.H.
Referenced by internalWriter::write(), patchWriter::write(), lagrangianWriter::write(), coordSetWriter::writePointData(), internalMeshWriter::writeUniform(), patchMeshWriter::writeUniform(), and polyWriter::writeUniformValue().
outputFile_
fileName outputFile_ protected
Definition at line 105 of file foamVtkFileWriter.H.
format_
autoPtr<vtk::formatter> format_ protected
Definition at line 108 of file foamVtkFileWriter.H.
Referenced by fileWriter::beginDataArray(), patchMeshWriter::beginPiece(), fileWriter::checkFormatterValidity(), and internalWriter::write().
os_
std::ofstream os_ protected
Definition at line 111 of file foamVtkFileWriter.H.
Referenced by fileWriter::os().
The documentation for this class was generated from the following files:
src/fileFormats/vtk/file/foamVtkFileWriter.H
src/fileFormats/vtk/file/foamVtkFileWriter.C
src/fileFormats/vtk/file/foamVtkFileWriterI.H
src/fileFormats/vtk/file/foamVtkFileWriterTemplates.C