OpenFOAM: TimeScaleModel Class Reference
TimeScaleModel Class Reference abstract
Lagrangian particle models » Submodels » MP-PIC » Time scale
Base class for time scale models.
#include <TimeScaleModel.H>
Public Member Functions
TypeName ("timeScaleModel")
declareRunTimeSelectionTable (autoPtr, TimeScaleModel, dictionary,(const dictionary &dict),(dict))
TimeScaleModel (const dictionary &dict)
TimeScaleModel (const TimeScaleModel &sm)
virtual autoPtr< TimeScaleModel > clone () const =0
virtual ~TimeScaleModel ()
virtual tmp< FieldField< Field, scalar > > oneByTau (const FieldField< Field, scalar > &alpha, const FieldField< Field, scalar > &r32, const FieldField< Field, scalar > &uSqr, const FieldField< Field, scalar > &f) const =0
Static Public Member Functions
static autoPtr< TimeScaleModel > New (const dictionary &dict)
Protected Attributes
scalar alphaPacked_
scalar e_
Detailed Description
Base class for time scale models.
Source files
TimeScaleModel.H
TimeScaleModel.C
Definition at line 53 of file TimeScaleModel.H.
Constructor & Destructor Documentation
TimeScaleModel() [1/2]
TimeScaleModel (const dictionary & dict)
Definition at line 35 of file TimeScaleModel.C.
TimeScaleModel() [2/2]
TimeScaleModel (const TimeScaleModel & sm)
Definition at line 46 of file TimeScaleModel.C.
~TimeScaleModel()
~TimeScaleModel () virtual
Definition at line 87 of file TimeScaleModel.C.
Member Function Documentation
TypeName()
TypeName ("timeScaleModel")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , TimeScaleModel , dictionary , (const dictionary &dict) , (dict))
clone()
virtual autoPtr< TimeScaleModel > clone () const pure virtual
Implemented in equilibrium, isotropic, and nonEquilibrium.
New()
Foam::autoPtr< Foam::TimeScaleModel > New (const dictionary & dict) static
Definition at line 59 of file TimeScaleModel.C.
References Foam::abort(), dict, Foam::endl(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), and Foam::Info.
oneByTau()
virtual tmp< FieldField< Field, scalar > > oneByTau (const FieldField< Field, scalar > & alpha, const FieldField< Field, scalar > & r32, const FieldField< Field, scalar > & uSqr, const FieldField< Field, scalar > & f) const pure virtual
Implemented in equilibrium, isotropic, and nonEquilibrium.
Member Data Documentation
alphaPacked_
scalar alphaPacked_ protected
Definition at line 68 of file TimeScaleModel.H.
e_
scalar e_ protected
Definition at line 71 of file TimeScaleModel.H.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/MPPIC/TimeScaleModels/TimeScaleModel/TimeScaleModel.H
src/lagrangian/intermediate/submodels/MPPIC/TimeScaleModels/TimeScaleModel/TimeScaleModel.C