OpenFOAM: tabulated6DoFMotion Class Reference
tabulated6DoFMotion Class Reference
Tabulated 6DoF motion function.
#include <tabulated6DoFMotion.H>
Public Member Functions
TypeName ("tabulated6DoFMotion")
tabulated6DoFMotion (const dictionary &SBMFCoeffs, const Time &runTime)
virtual autoPtr< solidBodyMotionFunction > clone () const
virtual ~tabulated6DoFMotion ()=default
virtual septernion transformation () const
virtual bool read (const dictionary &SBMFCoeffs)
Public Member Functions inherited from solidBodyMotionFunction
TypeName ("solidBodyMotionFunction")
declareRunTimeSelectionTable (autoPtr, solidBodyMotionFunction, dictionary,(const dictionary &SBMFCoeffs, const Time &runTime),(SBMFCoeffs, runTime))
solidBodyMotionFunction (const dictionary &SBMFCoeffs, const Time &runTime)
virtual ~solidBodyMotionFunction ()=default
virtual void writeData (Ostream &) const
Additional Inherited Members
Static Public Member Functions inherited from solidBodyMotionFunction
static autoPtr< solidBodyMotionFunction > New (const dictionary &SBMFCoeffs, const Time &runTime)
Protected Member Functions inherited from solidBodyMotionFunction
solidBodyMotionFunction (const solidBodyMotionFunction &)=delete
void operator= (const solidBodyMotionFunction &)=delete
Protected Attributes inherited from solidBodyMotionFunction
dictionary SBMFCoeffs_
const Time & time_
Detailed Description
Tabulated 6DoF motion function.
Obtained by interpolating tabulated data for surge (x-translation), sway (y-translation), heave (z-translation), roll (rotation about x), pitch (rotation about y) and yaw (rotation about z).
Source files
tabulated6DoFMotion.H
tabulated6DoFMotion.C
Definition at line 55 of file tabulated6DoFMotion.H.
Constructor & Destructor Documentation
tabulated6DoFMotion()
tabulated6DoFMotion (const dictionary & SBMFCoeffs, const Time & runTime)
Definition at line 49 of file tabulated6DoFMotion.C.
References tabulated6DoFMotion::read().
~tabulated6DoFMotion()
virtual ~tabulated6DoFMotion () virtual default
Member Function Documentation
TypeName()
TypeName ("tabulated6DoFMotion")
clone()
virtual autoPtr< solidBodyMotionFunction > clone () const inline virtual
Implements solidBodyMotionFunction.
Definition at line 102 of file tabulated6DoFMotion.H.
References solidBodyMotionFunction::SBMFCoeffs_, and solidBodyMotionFunction::time_.
transformation()
Foam::septernion transformation () const virtual
Implements solidBodyMotionFunction.
Definition at line 64 of file tabulated6DoFMotion.C.
References DebugInFunction, Foam::degToRad(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::interpolateSplineXY(), UPtrList< T >::last(), R, and quaternion::XYZ.
read()
bool read (const dictionary & SBMFCoeffs) virtual
Implements solidBodyMotionFunction.
Definition at line 105 of file tabulated6DoFMotion.C.
References Foam::exit(), string::expand(), Foam::FatalError, FatalErrorInFunction, UPtrList< T >::first(), forAll, solidBodyMotionFunction::read(), and UPtrList< T >::size().
Referenced by tabulated6DoFMotion::tabulated6DoFMotion().
The documentation for this class was generated from the following files:
src/dynamicMesh/motionSolvers/displacement/solidBody/solidBodyMotionFunctions/tabulated6DoFMotion/tabulated6DoFMotion.H
src/dynamicMesh/motionSolvers/displacement/solidBody/solidBodyMotionFunctions/tabulated6DoFMotion/tabulated6DoFMotion.C