OpenFOAM: multiphaseMixtureThermo Class Reference
multiphaseMixtureThermo Class Reference
#include <multiphaseMixtureThermo.H>
Classes
class interfacePair
Public Member Functions
TypeName ("multiphaseMixtureThermo")
multiphaseMixtureThermo (const volVectorField &U, const surfaceScalarField &phi)
virtual ~multiphaseMixtureThermo ()=default
const PtrDictionary< phaseModel > & phases () const
PtrDictionary< phaseModel > & phases ()
const volVectorField & U () const
const surfaceScalarField & phi () const
const surfaceScalarField & rhoPhi () const
virtual void correct ()
void correctRho (const volScalarField &dp)
virtual word thermoName () const
virtual bool incompressible () const
virtual bool isochoric () const
virtual volScalarField & he ()
virtual const volScalarField & he () const
virtual tmp< volScalarField > he (const volScalarField &p, const volScalarField &T) const
virtual tmp< scalarField > he (const scalarField &p, const scalarField &T, const labelList &cells) const
virtual tmp< scalarField > he (const scalarField &p, const scalarField &T, const label patchi) const
virtual tmp< volScalarField > hc () const
virtual tmp< scalarField > THE (const scalarField &h, const scalarField &p, const scalarField &T0, const labelList &cells) const
virtual tmp< scalarField > THE (const scalarField &h, const scalarField &p, const scalarField &T0, const label patchi) const
virtual tmp< volScalarField > rho () const
virtual tmp< scalarField > rho (const label patchi) const
virtual tmp< volScalarField > Cp () const
virtual tmp< scalarField > Cp (const scalarField &p, const scalarField &T, const label patchi) const
virtual tmp< scalarField > Cp (const scalarField &p, const scalarField &T, const labelList &cells) const
virtual tmp< volScalarField > Cv () const
virtual tmp< scalarField > Cv (const scalarField &p, const scalarField &T, const label patchi) const
virtual tmp< scalarField > rhoEoS (const scalarField &p, const scalarField &T, const labelList &cells) const
virtual tmp< volScalarField > gamma () const
virtual tmp< scalarField > gamma (const scalarField &p, const scalarField &T, const label patchi) const
virtual tmp< volScalarField > Cpv () const
virtual tmp< scalarField > Cpv (const scalarField &p, const scalarField &T, const label patchi) const
virtual tmp< volScalarField > CpByCpv () const
virtual tmp< scalarField > CpByCpv (const scalarField &p, const scalarField &T, const label patchi) const
virtual tmp< volScalarField > W () const
virtual tmp< volScalarField > nu () const
virtual tmp< scalarField > nu (const label patchi) const
virtual tmp< volScalarField > kappa () const
virtual tmp< scalarField > kappa (const label patchi) const
virtual tmp< volScalarField > alphahe () const
virtual tmp< scalarField > alphahe (const label patchi) const
virtual tmp< volScalarField > kappaEff (const volScalarField &alphat) const
virtual tmp< scalarField > kappaEff (const scalarField &alphat, const label patchi) const
virtual tmp< volScalarField > alphaEff (const volScalarField &alphat) const
virtual tmp< scalarField > alphaEff (const scalarField &alphat, const label patchi) const
tmp< volScalarField > rCv () const
tmp< surfaceScalarField > surfaceTensionForce () const
tmp< volScalarField > nearInterface () const
void solve ()
Public Member Functions inherited from psiThermo
TypeName ("psiThermo")
declareRunTimeSelectionTable (autoPtr, psiThermo, fvMesh,(const fvMesh &mesh, const word &phaseName),(mesh, phaseName))
declareRunTimeSelectionTable (autoPtr, psiThermo, fvMeshDictPhase,(const fvMesh &mesh, const word &phaseName, const word &dictName),(mesh, phaseName, dictName))
psiThermo (const fvMesh &, const word &phaseName)
psiThermo (const fvMesh &, const word &phaseName, const word &dictionaryName)
virtual ~psiThermo ()
virtual void correctRho (const volScalarField &deltaRho, const dimensionedScalar &rhoMin, const dimensionedScalar &rhoMax)
virtual const volScalarField & psi () const
virtual tmp< volScalarField > mu () const
virtual tmp< scalarField > mu (const label patchi) const
Public Member Functions inherited from fluidThermo
TypeName ("fluidThermo")
declareRunTimeSelectionTable (autoPtr, fluidThermo, fvMesh,(const fvMesh &mesh, const word &phaseName),(mesh, phaseName))
declareRunTimeSelectionTable (autoPtr, fluidThermo, fvMeshDictPhase,(const fvMesh &mesh, const word &phaseName, const word &dictName),(mesh, phaseName, dictName))
fluidThermo (const fvMesh &, const word &phaseName)
fluidThermo (const fvMesh &, const dictionary &, const word &phaseName)
fluidThermo (const fvMesh &, const word &phaseName, const word &dictionaryName)
virtual ~fluidThermo ()
Public Member Functions inherited from basicThermo
TypeName ("basicThermo")
declareRunTimeSelectionTable (autoPtr, basicThermo, fvMesh,(const fvMesh &mesh, const word &phaseName),(mesh, phaseName))
declareRunTimeSelectionTable (autoPtr, basicThermo, fvMeshDictPhase,(const fvMesh &mesh, const word &phaseName, const word &dictName),(mesh, phaseName, dictName))
basicThermo (const fvMesh &, const word &phaseName)
basicThermo (const fvMesh &, const dictionary &, const word &phaseName)
basicThermo (const fvMesh &, const word &phaseName, const word &dictionaryName)
virtual ~basicThermo ()
word phasePropertyName (const word &name) const
word phaseScopedName (const std::string &scope, const word &name) const
void validate (const string &app, const word &) const
void validate (const string &app, const word &, const word &) const
void validate (const string &app, const word &, const word &, const word &) const
void validate (const string &app, const word &, const word &, const word &, const word &) const
bool dpdt () const noexcept
bool updateT () const noexcept
virtual volScalarField & p ()
virtual const volScalarField & p () const
virtual const volScalarField & T () const
virtual volScalarField & T ()
virtual const volScalarField & alpha () const
virtual const scalarField & alpha (const label patchi) const
virtual bool read ()
template<class Thermo >
Foam::autoPtr< Thermo > New (const fvMesh &mesh, const word &phaseName)
template<class Thermo >
Foam::autoPtr< Thermo > New (const fvMesh &mesh, const dictionary &dict, const word &phaseName)
template<class Thermo >
Foam::autoPtr< Thermo > New (const fvMesh &mesh, const word &phaseName, const word &dictName)
Public Member Functions inherited from IOdictionary
IOdictionary (const IOobject &io, const dictionary *fallback=nullptr)
IOdictionary (const IOobject &io, const dictionary &dict)
IOdictionary (const IOobject &io, const word &wantedType, const dictionary *fallback=nullptr)
IOdictionary (const IOobject &io, Istream &is)
virtual ~IOdictionary ()=default
virtual bool global () const
virtual fileName filePath () const
Public Member Functions inherited from baseIOdictionary
TypeName ("dictionary")
baseIOdictionary (const baseIOdictionary &)=default
baseIOdictionary (baseIOdictionary &&)=default
virtual ~baseIOdictionary ()=default
baseIOdictionary (const IOobject &io, const dictionary *fallback=nullptr)
baseIOdictionary (const IOobject &io, const dictionary &dict)
baseIOdictionary (const IOobject &io, Istream &is)
const word & name () const
virtual bool readData (Istream &)
virtual bool writeData (Ostream &) const
void operator= (const baseIOdictionary &rhs)
void operator= (const dictionary &rhs)
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
regIOobject (const IOobject &io, const bool isTimeObject=false)
regIOobject (const regIOobject &rio)
regIOobject (const regIOobject &rio, bool registerCopy)
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
regIOobject (const IOobject &io, const regIOobject &rio)
virtual ~regIOobject ()
bool checkIn ()
bool checkOut ()
virtual void addWatch ()
bool registered () const noexcept
bool ownedByRegistry () const noexcept
bool store ()
void release (const bool unregister=false) noexcept
label eventNo () const noexcept
label & eventNo () noexcept
bool upToDate (const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
void setUpToDate ()
virtual void rename (const word &newName)
const dictionary * findMetaData () const noexcept
dictionary & getMetaData () noexcept
void removeMetaData ()
virtual void updateMetaData ()
bool headerOk ()
Istream & readStream (const word &, const bool readOnProc=true)
void close ()
virtual label addWatch (const fileName &)
const labelList & watchIndices () const noexcept
labelList & watchIndices () noexcept
virtual bool modified () const
virtual bool readIfModified ()
virtual bool writeObject (IOstreamOption streamOpt, const bool writeOnProc) const
virtual bool write (const bool writeOnProc=true) const
void operator= (const IOobject &io)
virtual bool writeObject (IOstreamOption::streamFormat fmt, IOstreamOption::versionNumber ver, IOstreamOption::compressionType cmp, const bool writeOnProc) const
Public Member Functions inherited from IOobject
TypeName ("IOobject")
IOobject (const IOobject &)=default
virtual ~IOobject ()=default
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const fileName &path, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const fileName &path, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const IOobject &io, const objectRegistry &registry)
IOobject (const IOobject &io, const word &name)
IOobject (const IOobject &io, const word &name, const fileName &local)
IOobject (const IOobject &io, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt)
IOobject (const IOobject &io, IOobjectOption::registerOption regOpt)
autoPtr< IOobject > clone () const
autoPtr< IOobject > clone (const objectRegistry &registry) const
const objectRegistry & db () const noexcept
const Time & time () const noexcept
const word & name () const noexcept
const word & headerClassName () const noexcept
word & headerClassName () noexcept
const string & note () const noexcept
string & note () noexcept
unsigned labelByteSize () const noexcept
unsigned scalarByteSize () const noexcept
void resetHeader (const word &newName=word::null)
bool hasHeaderClass () const noexcept
template<class Type >
bool isHeaderClass () const
template<class Type >
bool isHeaderClassName () const
word group () const
word member () const
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const noexcept
fileName & instance () noexcept
const fileName & local () const noexcept
fileName path () const
fileName path (const word &instance, const fileName &local=fileName::null) const
fileName objectPath () const
fileName objectRelPath () const
fileName localFilePath (const word &typeName, const bool search=true) const
fileName globalFilePath (const word &typeName, const bool search=true) const
IOstreamOption parseHeader (const dictionary &headerDict)
bool readHeader (Istream &is)
bool readHeader (dictionary &headerDict, Istream &is)
template<class Type >
bool typeHeaderOk (const bool checkType=true, const bool search=true, const bool verbose=true)
template<class Type >
void warnNoRereading () const
bool writeHeader (Ostream &os) const
bool writeHeader (Ostream &os, const word &objectType) const
void writeHeader (dictionary &dict, IOstreamOption streamOpt) const
void writeHeader (dictionary &dict, const word &objectType, IOstreamOption streamOpt) const
bool good () const noexcept
bool bad () const noexcept
InfoProxy< IOobject > info () const noexcept
void operator= (const IOobject &io)
template<>
bool isHeaderClass () const
template<class StringType >
Foam::word groupName (StringType base, const word &group)
Public Member Functions inherited from IOobjectOption
constexpr IOobjectOption (readOption rOpt=readOption::NO_READ, writeOption wOpt=writeOption::NO_WRITE, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (readOption rOpt, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (writeOption wOpt, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (registerOption registerObject, bool globalObject=false) noexcept
constexpr IOobjectOption (readOption rOpt, writeOption wOpt, bool registerObject, bool globalObject=false) noexcept
constexpr IOobjectOption (bool registerObject, bool globalObject=false) noexcept
readOption readOpt () const noexcept
readOption readOpt (readOption opt) noexcept
writeOption writeOpt () const noexcept
writeOption writeOpt (writeOption opt) noexcept
bool registerObject () const noexcept
bool registerObject (bool on) noexcept
bool globalObject () const noexcept
bool globalObject (bool on) noexcept
bool isAnyRead () const noexcept
bool isReadRequired () const noexcept
bool isReadOptional () const noexcept
readOption & readOpt () noexcept
writeOption & writeOpt () noexcept
bool & registerObject () noexcept
bool & globalObject () noexcept
Public Member Functions inherited from dictionary
ClassName ("dictionary")
dictionary ()
dictionary (const fileName &name)
dictionary (const fileName &name, const dictionary &parentDict, Istream &is, bool keepHeader=false)
dictionary (Istream &is)
dictionary (Istream &is, bool keepHeader)
dictionary (const dictionary &parentDict, const dictionary &dict)
dictionary (const dictionary &dict)
dictionary (const dictionary *dict)
dictionary (const dictionary &parentDict, dictionary &&dict)
dictionary (dictionary &&dict)
autoPtr< dictionary > clone () const
virtual ~dictionary ()
const fileName & name () const noexcept
fileName & name () noexcept
word dictName () const
fileName relativeName (const bool caseTag=false) const
bool isNullDict () const noexcept
const dictionary & parent () const noexcept
const dictionary & topDict () const
label startLineNumber () const
label endLineNumber () const
SHA1Digest digest () const
tokenList tokens () const
const entry * findEntry (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
entry * findEntry (const word &keyword, enum keyType::option matchOpt=keyType::REGEX)
bool found (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
const entry * findScoped (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
const dictionary * findDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
dictionary * findDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX)
bool isDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
const entry & lookupEntry (const word &keyword, enum keyType::option matchOpt) const
ITstream & lookup (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
template<class T >
T get (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
template<class T >
T getOrDefault (const word &keyword, const T &deflt, enum keyType::option matchOpt=keyType::REGEX) const
template<class T >
T getOrAdd (const word &keyword, const T &deflt, enum keyType::option matchOpt=keyType::REGEX)
template<class T >
bool readEntry (const word &keyword, T &val, enum keyType::option matchOpt=keyType::REGEX, IOobjectOption::readOption readOpt=IOobjectOption::MUST_READ) const
template<class T >
bool readIfPresent (const word &keyword, T &val, enum keyType::option matchOpt=keyType::REGEX) const
template<class T , class Predicate >
T getCheck (const word &keyword, const Predicate &pred, enum keyType::option matchOpt=keyType::REGEX) const
template<class T , class Predicate >
T getCheckOrDefault (const word &keyword, const T &deflt, const Predicate &pred, enum keyType::option matchOpt=keyType::REGEX) const
template<class T , class Predicate >
T getCheckOrAdd (const word &keyword, const T &deflt, const Predicate &pred, enum keyType::option matchOpt=keyType::REGEX)
template<class T , class Predicate >
bool readCheck (const word &keyword, T &val, const Predicate &pred, enum keyType::option matchOpt=keyType::REGEX, IOobjectOption::readOption readOpt=IOobjectOption::MUST_READ) const
template<class T , class Predicate >
bool readCheckIfPresent (const word &keyword, T &val, const Predicate &pred, enum keyType::option matchOpt=keyType::REGEX) const
const dictionary & subDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
dictionary & subDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX)
dictionary & subDictOrAdd (const word &keyword, enum keyType::option matchOpt=keyType::REGEX)
dictionary subOrEmptyDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX, const bool mandatory=false) const
const dictionary & optionalSubDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
wordList toc () const
wordList sortedToc () const
template<class Compare >
wordList sortedToc (const Compare &comp) const
List< keyType > keys (bool patterns=false) const
bool substituteKeyword (const word &keyword, bool mergeEntry=false)
bool substituteScopedKeyword (const word &keyword, bool mergeEntry=false)
entry * add (entry *entryPtr, bool mergeEntry=false)
entry * add (const entry &e, bool mergeEntry=false)
entry * add (const keyType &k, const word &v, bool overwrite=false)
entry * add (const keyType &k, const string &v, bool overwrite=false)
entry * add (const keyType &k, const label v, bool overwrite=false)
entry * add (const keyType &k, const scalar v, bool overwrite=false)
entry * add (const keyType &k, const dictionary &d, bool mergeEntry=false)
template<class T >
entry * add (const keyType &k, const T &v, bool overwrite=false)
entry * set (entry *entryPtr)
entry * set (const entry &e)
entry * set (const keyType &k, const dictionary &v)
template<class T >
entry * set (const keyType &k, const T &v)
bool remove (const word &keyword)
bool changeKeyword (const keyType &oldKeyword, const keyType &newKeyword, bool overwrite=false)
bool merge (const dictionary &dict)
void clear ()
void transfer (dictionary &dict)
void checkITstream (const ITstream &is, const word &keyword) const
bool read (Istream &is)
bool read (Istream &is, bool keepHeader)
void writeEntry (Ostream &os) const
void writeEntry (const keyType &keyword, Ostream &os) const
void writeEntries (Ostream &os, const bool extraNewLine=false) const
void write (Ostream &os, const bool subDict=true) const
const_searcher csearch (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
const_searcher search (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
searcher search (const word &keyword, enum keyType::option matchOpt=keyType::REGEX)
const_searcher csearchScoped (const word &keyword, enum keyType::option matchOpt) const
const_searcher searchScoped (const word &keyword, enum keyType::option matchOpt) const
searcher searchScoped (const word &keyword, enum keyType::option matchOpt)
const dictionary * cfindScopedDict (const fileName &dictPath) const
const dictionary * findScopedDict (const fileName &dictPath) const
dictionary * findScopedDict (const fileName &dictPath)
dictionary * makeScopedDict (const fileName &dictPath)
const_searcher csearchCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, enum keyType::option matchOpt=keyType::REGEX) const
const entry * findCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, enum keyType::option matchOpt) const
bool foundCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, enum keyType::option matchOpt=keyType::REGEX) const
const entry & lookupEntryCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, enum keyType::option matchOpt) const
ITstream & lookupCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, enum keyType::option matchOpt=keyType::REGEX) const
template<class T >
T getCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, enum keyType::option matchOpt=keyType::REGEX) const
template<class T >
T getOrDefaultCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, const T &deflt, enum keyType::option matchOpt=keyType::REGEX) const
template<class T >
bool readCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, T &val, enum keyType::option matchOpt=keyType::REGEX, IOobjectOption::readOption readOpt=IOobjectOption::MUST_READ) const
template<class T >
bool readIfPresentCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, T &val, enum keyType::option matchOpt=keyType::REGEX) const
void operator= (const dictionary &rhs)
void operator+= (const dictionary &rhs)
void operator|= (const dictionary &rhs)
void operator<<= (const dictionary &rhs)
bool getBool (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Same as get< bool >(const word&, keyType::option)
label getLabel (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Same as get< label >(const word&, keyType::option)
scalar getScalar (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Same as get< scalar >(const word&, keyType::option)
string getString (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Same as get< string >(const word&, keyType::option)
word getWord (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Same as get< word >(const word&, keyType::option)
fileName getFileName (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Same as get< fileName >(const word&, keyType::option)
template<class T >
T lookupOrDefault (const word &keyword, const T &deflt, enum keyType::option matchOpt=keyType::REGEX) const
template<class T >
T lookupOrAddDefault (const word &keyword, const T &deflt, enum keyType::option matchOpt=keyType::REGEX)
ITstream & operator[] (const word &keyword) const
bool found (const word &keyword, bool recursive, bool patternMatch=true) const
entry * lookupEntryPtr (const word &keyword, bool recursive, bool patternMatch)
const entry * lookupEntryPtr (const word &keyword, bool recursive, bool patternMatch) const
const entry * lookupScopedEntryPtr (const word &keyword, bool recursive, bool patternMatch) const
const dictionary * subDictPtr (const word &keyword) const
dictionary * subDictPtr (const word &keyword)
const entry & lookupEntry (const word &keyword, bool recursive, bool patternMatch) const
ITstream & lookup (const word &keyword, bool recursive, bool patternMatch=true) const
template<class T >
T lookupOrDefault (const word &keyword, const T &deflt, bool recursive, bool patternMatch=true) const
template<class T >
T lookupOrAddDefault (const word &keyword, const T &deflt, bool recursive, bool patternMatch=true)
template<class T >
bool readIfPresent (const word &keyword, T &val, bool recursive, bool patternMatch=true) const
template<class T >
T lookupType (const word &keyword, bool recursive=false, bool patternMatch=true) const
template<class Compare >
Foam::wordList sortedToc (const Compare &comp) const
template<class T >
Foam::entry * add (const keyType &k, const T &v, bool overwrite)
template<class T >
Foam::entry * set (const keyType &k, const T &v)
Public Member Functions inherited from ILList< LListBase, T >
ILList ()=default
ILList (T *item)
ILList (Istream &is)
ILList (const ILList< LListBase, T > &lst)
ILList (ILList< LListBase, T > &&lst)
template<class CloneArg >
ILList (const ILList< LListBase, T > &lst, const CloneArg &cloneArg)
template<class INew >
ILList (Istream &is, const INew &inew)
~ILList ()
void clear ()
void pop_front (label n=1)
bool erase (T *item)
void transfer (ILList< LListBase, T > &lst)
void operator= (const ILList< LListBase, T > &lst)
void operator= (ILList< LListBase, T > &&lst)
Public Member Functions inherited from UILList< LListBase, T >
UILList ()=default
UILList (T *item)
UILList (const UILList< LListBase, T > &list)
T * front ()
const T * front () const
T * back ()
const T * back () const
T * removeHead ()
T * remove (T *item)
T * remove (iterator &iter)
void operator= (const UILList< LListBase, T > &lst)
bool operator== (const UILList< LListBase, T > &lst) const
bool operator!= (const UILList< LListBase, T > &lst) const
Ostream & writeList (Ostream &os, const label shortLen=0) const
iterator begin ()
const_iterator cbegin () const
reverse_iterator rbegin ()
const_reverse_iterator crbegin () const
const_iterator begin () const
const_reverse_iterator rbegin () const
const iterator & end ()
const const_iterator & cend () const
const reverse_iterator & rend ()
const const_reverse_iterator & crend () const
const const_iterator & end () const
const const_reverse_iterator & rend () const
T * first ()
const T * first () const
T * last ()
const T * last () const
Public Member Functions inherited from compressibleTransportModel
TypeName ("compressibleTransportModel")
compressibleTransportModel ()
virtual ~compressibleTransportModel ()
Additional Inherited Members
Public Types inherited from IOobject
enum objectState : char { GOOD , BAD }
enum fileCheckTypes : char { timeStamp , timeStampMaster , inotify , inotifyMaster }
Public Types inherited from IOobjectOption
enum readOption : unsigned char {
NO_READ = 0 , MUST_READ = 0x1 , READ_MODIFIED = 0x3 , MUST_READ_IF_MODIFIED = 0x3 ,
LAZY_READ = 0x4 , READ_IF_PRESENT = 0x4
}
enum writeOption : unsigned char { NO_WRITE = 0 , AUTO_WRITE = 0x10 }
enum registerOption : unsigned char { NO_REGISTER = 0 , REGISTER = 1 }
Public Types inherited from dictionary
typedef Searcher< true > const_searcher
typedef Searcher< false > searcher
Public Types inherited from UILList< LListBase, T >
typedef T value_type
typedef T * pointer
typedef const T * const_pointer
typedef T & reference
typedef const T & const_reference
typedef label size_type
typedef label difference_type
using base_iterator = typename LListBase::iterator
using const_base_iterator = typename LListBase::const_iterator
Static Public Member Functions inherited from psiThermo
static autoPtr< psiThermo > New (const fvMesh &mesh, const word &phaseName=word::null)
static autoPtr< psiThermo > New (const fvMesh &, const word &dictName, const word &phaseName)
Static Public Member Functions inherited from fluidThermo
static autoPtr< fluidThermo > New (const fvMesh &, const word &phaseName=word::null)
static autoPtr< fluidThermo > New (const fvMesh &, const word &phaseName, const word &dictName)
Static Public Member Functions inherited from basicThermo
template<class Thermo >
static autoPtr< Thermo > New (const fvMesh &, const word &phaseName=word::null)
template<class Thermo >
static autoPtr< Thermo > New (const fvMesh &, const dictionary &, const word &phaseName=word::null)
template<class Thermo >
static autoPtr< Thermo > New (const fvMesh &, const word &phaseName, const word &dictName)
static autoPtr< basicThermo > New (const fvMesh &, const word &phaseName=word::null)
static word phasePropertyName (const word &name, const word &phaseName)
static const basicThermo & lookupThermo (const fvPatchScalarField &pf)
static Ostream & printThermoNames (Ostream &os, const wordList &cmptNames, const wordList &thermoNames)
static wordList splitThermoName (const std::string &thermoName, const int nExpectedCmpts)
Static Public Member Functions inherited from IOdictionary
static dictionary readContents (const IOobject &io)
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *p)
template<class Type >
static Type & store (autoPtr< Type > &ptr)
template<class Type >
static Type & store (autoPtr< Type > &&ptr)
template<class Type >
static Type & store (refPtr< Type > &ptr)
template<class Type >
static Type & store (refPtr< Type > &&ptr)
template<class Type >
static Type & store (tmp< Type > &ptr)
template<class Type >
static Type & store (tmp< Type > &&ptr)
Static Public Member Functions inherited from IOobject
static bool bannerEnabled () noexcept
static bool bannerEnabled (bool on) noexcept
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
template<class StringType >
static word groupName (StringType base, const word &group)
static word group (const word &name)
static word member (const word &name)
static word scopedName (const std::string &scope, const word &name)
static IOobject selectIO (const IOobject &io, const fileName &altFile, const word &ioName="")
static Ostream & writeBanner (Ostream &os, const bool noSyntaxHint=false)
static Ostream & writeDivider (Ostream &os)
static Ostream & writeEndDivider (Ostream &os)
Static Public Member Functions inherited from IOobjectOption
static bool isAnyRead (readOption opt) noexcept
static bool isReadRequired (readOption opt) noexcept
static bool isReadOptional (readOption opt) noexcept
static readOption lazierRead (readOption opt) noexcept
Static Public Member Functions inherited from dictionary
static int reportOptional () noexcept
static int reportOptional (const int level) noexcept
static autoPtr< dictionary > New (Istream &is)
Public Attributes inherited from dictionary
friend const_searcher
friend searcher
Static Public Attributes inherited from basicThermo
static const word dictName
Static Public Attributes inherited from IOobject
static const Enum< fileCheckTypes > fileCheckTypesNames
static char scopeSeparator
static fileCheckTypes fileModificationChecking
static float fileModificationSkew
static int maxFileModificationPolls
Static Public Attributes inherited from dictionary
static int writeOptionalEntries
static const dictionary null
static refPtr< OSstream > reportingOutput
Protected Member Functions inherited from psiThermo
psiThermo (const psiThermo &)
Protected Member Functions inherited from basicThermo
wordList heBoundaryTypes ()
wordList heBoundaryBaseTypes ()
basicThermo (const basicThermo &)=delete
Protected Member Functions inherited from regIOobject
bool readHeaderOk (const IOstreamOption::streamFormat fmt, const word &typeName)
Protected Member Functions inherited from IOobject
void setBad (const string &s)
Static Protected Member Functions inherited from IOobject
static void writeHeaderContent (Ostream &os, const IOobject &io, const word &objectType, const dictionary *metaDataDict=nullptr)
static void writeHeaderContent (dictionary &dict, const IOobject &io, const word &objectType, IOstreamOption streamOpt, const dictionary *metaDataDict=nullptr)
Protected Attributes inherited from psiThermo
volScalarField psi_
volScalarField mu_
Protected Attributes inherited from basicThermo
const word & phaseName_
bool pOwner_
bool TOwner_
bool dpdt_
volScalarField & p_
volScalarField & T_
volScalarField alpha_
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
Detailed Description
Source files
multiphaseMixtureThermo.H
multiphaseMixtureThermo.C
Definition at line 51 of file multiphaseMixtureThermo.H.
Constructor & Destructor Documentation
multiphaseMixtureThermo()
multiphaseMixtureThermo (const volVectorField & U, const surfaceScalarField & phi)
~multiphaseMixtureThermo()
virtual ~multiphaseMixtureThermo () virtual default
Member Function Documentation
TypeName()
TypeName ("multiphaseMixtureThermo")
phases() [1/2]
const PtrDictionary< phaseModel > & phases () const inline
Definition at line 188 of file multiphaseMixtureThermo.H.
phases() [2/2]
PtrDictionary< phaseModel > & phases () inline
Definition at line 194 of file multiphaseMixtureThermo.H.
U()
const volVectorField & U () const inline
Definition at line 200 of file multiphaseMixtureThermo.H.
phi()
const surfaceScalarField & phi () const inline
Definition at line 206 of file multiphaseMixtureThermo.H.
rhoPhi()
const surfaceScalarField & rhoPhi () const inline
Definition at line 211 of file multiphaseMixtureThermo.H.
correct()
virtual void correct () virtual
Implements basicThermo.
correctRho()
void correctRho (const volScalarField & dp) virtual
Reimplemented from psiThermo.
thermoName()
virtual word thermoName () const virtual
Implements basicThermo.
incompressible()
virtual bool incompressible () const virtual
Implements basicThermo.
isochoric()
virtual bool isochoric () const virtual
Implements basicThermo.
he() [1/5]
virtual volScalarField & he () inline virtual
Implements basicThermo.
Definition at line 238 of file multiphaseMixtureThermo.H.
References NotImplemented.
he() [2/5]
virtual const volScalarField & he () const inline virtual
Implements basicThermo.
Definition at line 245 of file multiphaseMixtureThermo.H.
References NotImplemented.
he() [3/5]
virtual tmp< volScalarField > he (const volScalarField & p, const volScalarField & T) const virtual
Implements basicThermo.
he() [4/5]
virtual tmp< scalarField > he (const scalarField & p, const scalarField & T, const labelList & cells) const virtual
Implements basicThermo.
he() [5/5]
virtual tmp< scalarField > he (const scalarField & p, const scalarField & T, const label patchi) const virtual
Implements basicThermo.
hc()
virtual tmp< volScalarField > hc () const virtual
Implements basicThermo.
THE() [1/2]
virtual tmp< scalarField > THE (const scalarField & h, const scalarField & p, const scalarField & T0, const labelList & cells) const virtual
Implements basicThermo.
THE() [2/2]
virtual tmp< scalarField > THE (const scalarField & h, const scalarField & p, const scalarField & T0, const label patchi) const virtual
Implements basicThermo.
rho() [1/2]
virtual tmp< volScalarField > rho () const virtual
Reimplemented from psiThermo.
rho() [2/2]
virtual tmp< scalarField > rho (const label patchi) const virtual
Reimplemented from psiThermo.
Cp() [1/3]
virtual tmp< volScalarField > Cp () const virtual
Implements basicThermo.
Cp() [2/3]
virtual tmp< scalarField > Cp (const scalarField & p, const scalarField & T, const label patchi) const virtual
Implements basicThermo.
Cp() [3/3]
virtual tmp< scalarField > Cp (const scalarField & p, const scalarField & T, const labelList & cells) const inline virtual
Implements basicThermo.
Definition at line 317 of file multiphaseMixtureThermo.H.
References tmp< T >::New(), NotImplemented, and basicThermo::p().
Cv() [1/2]
virtual tmp< volScalarField > Cv () const virtual
Implements basicThermo.
Cv() [2/2]
virtual tmp< scalarField > Cv (const scalarField & p, const scalarField & T, const label patchi) const virtual
Implements basicThermo.
rhoEoS()
virtual tmp< scalarField > rhoEoS (const scalarField & p, const scalarField & T, const labelList & cells) const inline virtual
Implements basicThermo.
Definition at line 340 of file multiphaseMixtureThermo.H.
References tmp< T >::New(), NotImplemented, and basicThermo::p().
gamma() [1/2]
virtual tmp< volScalarField > gamma () const virtual
Implements basicThermo.
gamma() [2/2]
virtual tmp< scalarField > gamma (const scalarField & p, const scalarField & T, const label patchi) const virtual
Implements basicThermo.
Cpv() [1/2]
virtual tmp< volScalarField > Cpv () const virtual
Implements basicThermo.
Cpv() [2/2]
virtual tmp< scalarField > Cpv (const scalarField & p, const scalarField & T, const label patchi) const virtual
Implements basicThermo.
CpByCpv() [1/2]
virtual tmp< volScalarField > CpByCpv () const virtual
Implements basicThermo.
CpByCpv() [2/2]
virtual tmp< scalarField > CpByCpv (const scalarField & p, const scalarField & T, const label patchi) const virtual
Implements basicThermo.
W()
virtual tmp< volScalarField > W () const virtual
Implements basicThermo.
nu() [1/2]
virtual tmp< volScalarField > nu () const virtual
Reimplemented from fluidThermo.
nu() [2/2]
virtual tmp< scalarField > nu (const label patchi) const virtual
Reimplemented from fluidThermo.
kappa() [1/2]
virtual tmp< volScalarField > kappa () const virtual
Implements basicThermo.
kappa() [2/2]
virtual tmp< scalarField > kappa (const label patchi) const virtual
Implements basicThermo.
alphahe() [1/2]
virtual tmp< volScalarField > alphahe () const virtual
Implements basicThermo.
alphahe() [2/2]
virtual tmp< scalarField > alphahe (const label patchi) const virtual
Implements basicThermo.
kappaEff() [1/2]
virtual tmp< volScalarField > kappaEff (const volScalarField & alphat) const virtual
Implements basicThermo.
kappaEff() [2/2]
virtual tmp< scalarField > kappaEff (const scalarField & alphat, const label patchi) const virtual
Implements basicThermo.
alphaEff() [1/2]
virtual tmp< volScalarField > alphaEff (const volScalarField & alphat) const virtual
Implements basicThermo.
alphaEff() [2/2]
virtual tmp< scalarField > alphaEff (const scalarField & alphat, const label patchi) const virtual
Implements basicThermo.
rCv()
tmp< volScalarField > rCv () const
surfaceTensionForce()
tmp< surfaceScalarField > surfaceTensionForce () const
nearInterface()
tmp< volScalarField > nearInterface () const
solve()
void solve ()
The documentation for this class was generated from the following file:
applications/solvers/multiphase/compressibleMultiphaseInterFoam/multiphaseMixtureThermo/multiphaseMixtureThermo.H