OpenFOAM: VTPsurfaceFormatCore Class Reference
VTPsurfaceFormatCore Class Reference
Internal class used by the VTPsurfaceFormat. The default format is INLINE_BASE64.
#include <VTPsurfaceFormatCore.H>
Static Protected Member Functions
static vtk::outputOptions formatOptions (const dictionary &dict, vtk::outputOptions opts=vtk::formatType::INLINE_BASE64)
static void writeHeader (vtk::formatter &format, const UList< point > &pts, const label nFaces)
static void writeFooter (vtk::formatter &format)
static void writeCellData (vtk::formatter &format, const UList< surfZone > &zones)
static void writeCellData (vtk::formatter &format, const labelUList &zoneIds)
Detailed Description
Internal class used by the VTPsurfaceFormat. The default format is INLINE_BASE64.
Output Options
Property Description Required Default
format ascii or binary format no binary
precision Write precision in ascii no same as IOstream
Source files
VTPsurfaceFormatCore.H
VTPsurfaceFormatCore.C
Definition at line 73 of file VTPsurfaceFormatCore.H.
Member Function Documentation
formatOptions()
Foam::vtk::outputOptions formatOptions (const dictionary & dict, vtk::outputOptions opts = vtk::formatType::INLINE_BASE64) static protected
Definition at line 27 of file VTPsurfaceFormatCore.C.
References outputOptions::append(), outputOptions::ascii(), IOstreamOption::ASCII, IOstreamOption::BINARY, IOstream::defaultPrecision(), dict, IOstreamOption::formatEnum(), outputOptions::legacy(), and outputOptions::precision().
writeHeader()
void writeHeader (vtk::formatter & format, const UList< point > & pts, const label nFaces) static protected
Definition at line 51 of file VTPsurfaceFormatCore.C.
References clock::dateTime(), format(), Foam::vtk::NUMBER_OF_POINTS, Foam::vtk::NUMBER_OF_POLYS, Foam::vtk::PIECE, Foam::vtk::POINTS, Foam::vtk::POLY_DATA, pts, and Foam::vtk::writeList().
writeFooter()
void writeFooter (vtk::formatter & format) static protected
Definition at line 93 of file VTPsurfaceFormatCore.C.
References format(), and Foam::vtk::POLY_DATA.
writeCellData() [1/2]
void writeCellData (vtk::formatter & format, const UList< surfZone > & zones) static protected
Definition at line 105 of file VTPsurfaceFormatCore.C.
References format(), UPtrList< T >::size(), and Foam::vtk::write().
writeCellData() [2/2]
void writeCellData (vtk::formatter & format, const labelUList & zoneIds) static protected
Definition at line 140 of file VTPsurfaceFormatCore.C.
References format(), UList< T >::size(), and Foam::vtk::writeList().
The documentation for this class was generated from the following files:
src/surfMesh/surfaceFormats/vtp/VTPsurfaceFormatCore.H
src/surfMesh/surfaceFormats/vtp/VTPsurfaceFormatCore.C