OpenFOAM: ThermoSurfaceFilm< CloudType > Class Template Reference
ThermoSurfaceFilm< CloudType > Class Template Reference
Lagrangian particle models » Submodels » Kinematic » Surface film
Thermo parcel surface film model.
#include <ThermoSurfaceFilm.H>
Public Member Functions
TypeName ("thermoSurfaceFilm")
ThermoSurfaceFilm (const dictionary &dict, CloudType &owner)
ThermoSurfaceFilm (const ThermoSurfaceFilm< CloudType > &sfm)
virtual autoPtr< SurfaceFilmModel< CloudType > > clone () const
virtual ~ThermoSurfaceFilm ()=default
virtual bool transferParcel (parcelType &p, const polyPatch &pp, bool &keepParticle)
virtual void info ()
Public Member Functions inherited from KinematicSurfaceFilm< CloudType >
TypeName ("kinematicSurfaceFilm")
KinematicSurfaceFilm (const dictionary &dict, CloudType &owner, const word &type=typeName, bool initThermo=true)
KinematicSurfaceFilm (const KinematicSurfaceFilm< CloudType > &sfm, bool initThermo=true)
virtual ~KinematicSurfaceFilm ()=default
template<class filmType >
void absorbInteraction (filmType &, const parcelType &p, const polyPatch &pp, const label facei, const scalar mass, bool &keepParticle)
void bounceInteraction (parcelType &p, const polyPatch &pp, const label facei, bool &keepParticle) const
template<class filmType >
void drySplashInteraction (filmType &, const scalar sigma, const scalar mu, const parcelType &p, const polyPatch &pp, const label facei, bool &keepParticle)
template<class filmType >
void wetSplashInteraction (filmType &, const scalar sigma, const scalar mu, parcelType &p, const polyPatch &pp, const label facei, bool &keepParticle)
template<class filmType >
void splashInteraction (filmType &, const parcelType &p, const polyPatch &pp, const label facei, const scalar mRatio, const scalar We, const scalar Wec, const scalar sigma, bool &keepParticle)
Public Member Functions inherited from SurfaceFilmModel< CloudType >
TypeName ("surfaceFilmModel")
declareRunTimeSelectionTable (autoPtr, SurfaceFilmModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
SurfaceFilmModel (CloudType &owner)
SurfaceFilmModel (const dictionary &dict, CloudType &owner, const word &type)
SurfaceFilmModel (const SurfaceFilmModel< CloudType > &sfm)
virtual ~SurfaceFilmModel ()=default
const dimensionedVector & g () const noexcept
label nParcelsTransferred () const noexcept
label & nParcelsTransferred () noexcept
label nParcelsInjected () const noexcept
label & nParcelsInjected () noexcept
scalar totalMassTransferred () const noexcept
scalar & totalMassTransferred () noexcept
template<class TrackCloudType >
void inject (TrackCloudType &cloud)
template<class CloudTrackType >
void injectParticles (const label primaryPatchi, const labelUList &injectorCells, CloudTrackType &cloud)
template<class CloudTrackType >
void injectParticles (const UList< labelPair > &patchFaces, CloudTrackType &cloud)
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
virtual ~CloudSubModelBase ()=default
const CloudType & owner () const
virtual bool writeTime () const
virtual fileName localPath () const
CloudType & owner ()
virtual void write (Ostream &os) const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
subModelBase (const subModelBase &smb)
virtual ~subModelBase ()=default
const word & modelName () const
const dictionary & dict () const
const word & baseName () const
const word & modelType () const
const dictionary & coeffDict () const
const dictionary & properties () const
virtual bool defaultCoeffs (const bool printMsg) const
virtual bool active () const
virtual void cacheFields (const bool store)
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
bool getModelDict (const word &entryName, dictionary &dict) const
template<class Type >
bool getModelProperty (const word &entryName, Type &value) const
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Protected Types
typedef CloudType::parcelType parcelType
typedef regionModels::areaSurfaceFilmModels::liquidFilmBase areaFilm
typedef regionModels::surfaceFilmModels::surfaceFilmRegionModel regionFilm
Protected Types inherited from KinematicSurfaceFilm< CloudType >
typedef CloudType::parcelType parcelType
typedef regionModels::areaSurfaceFilmModels::liquidFilmBase areaFilm
typedef regionModels::surfaceFilmModels::surfaceFilmRegionModel regionFilm
Protected Types inherited from SurfaceFilmModel< CloudType >
typedef CloudType::parcelType parcelType
typedef regionModels::areaSurfaceFilmModels::liquidFilmBase areaFilm
typedef regionModels::surfaceFilmModels::surfaceFilmRegionModel regionFilm
Protected Member Functions
virtual void cacheFilmFields (const label filmPatchi, const label primaryPatchi, const regionFilm &)
virtual void cacheFilmFields (const areaFilm &)
virtual void setParcelProperties (parcelType &p, const label filmFacei) const
Protected Member Functions inherited from KinematicSurfaceFilm< CloudType >
vector tangentVector (const vector &v) const
vector splashDirection (const vector &tanVec1, const vector &tanVec2, const vector &nf) const
void init (bool binitThermo)
void initFilmModels ()
Protected Member Functions inherited from SurfaceFilmModel< CloudType >
template<class TrackCloudType >
void injectParticles (const label primaryPatchi, const labelUList &injectorCells, TrackCloudType &cloud)
template<class TrackCloudType >
void injectParticles (const UList< labelPair > &patchFaces, TrackCloudType &cloud)
Protected Member Functions inherited from subModelBase
bool inLine () const
Protected Attributes
const SLGThermo & thermo_
scalarField TFilmPatch_
scalarField CpFilmPatch_
Protected Attributes inherited from KinematicSurfaceFilm< CloudType >
Random & rndGen_
liquidMixtureProperties * thermo_
scalar pRef_
scalar TRef_
regionFilm * filmModel_
UPtrList< areaFilm > areaFilms_
interactionType interactionType_
labelList parcelTypes_
scalar deltaWet_
label splashParcelType_
label parcelsPerSplash_
scalar dMaxSplash_
scalar dMinSplash_
scalar Adry_
scalar Awet_
scalar Cf_
label nParcelsSplashed_
Protected Attributes inherited from SurfaceFilmModel< CloudType >
const dimensionedVector & g_
label ejectedParcelType_
scalar injectionOffset_
scalar minDiameter_
scalarField massParcelPatch_
scalarField diameterParcelPatch_
Field< vector > UFilmPatch_
scalarField rhoFilmPatch_
Field< scalarField > deltaFilmPatch_
label nParcelsTransferred_
label nParcelsInjected_
scalar totalMassTransferred_
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Protected Attributes inherited from subModelBase
const word modelName_
dictionary & properties_
const dictionary dict_
const word baseName_
const word modelType_
const dictionary coeffDict_
Additional Inherited Members
Public Types inherited from KinematicSurfaceFilm< CloudType >
enum class interactionType { absorb , bounce , splashBai }
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Static Public Member Functions inherited from SurfaceFilmModel< CloudType >
static autoPtr< SurfaceFilmModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Public Attributes inherited from subModelBase
bool log
Static Public Attributes inherited from KinematicSurfaceFilm< CloudType >
static const Enum< interactionType > interactionTypeNames
Detailed Description
template<class CloudType>
class Foam::ThermoSurfaceFilm< CloudType >
Thermo parcel surface film model.
Source files
ThermoSurfaceFilm.H
ThermoSurfaceFilm.C
ThermoSurfaceFilmI.H
Definition at line 53 of file ThermoSurfaceFilm.H.
Member Typedef Documentation
parcelType
template<class CloudType > typedef CloudType::parcelType parcelType protected
Definition at line 62 of file ThermoSurfaceFilm.H.
areaFilm
template<class CloudType > typedef regionModels::areaSurfaceFilmModels::liquidFilmBase areaFilm protected
Definition at line 66 of file ThermoSurfaceFilm.H.
regionFilm
template<class CloudType > typedef regionModels::surfaceFilmModels::surfaceFilmRegionModel regionFilm protected
Definition at line 70 of file ThermoSurfaceFilm.H.
Constructor & Destructor Documentation
ThermoSurfaceFilm() [1/2]
template<class CloudType > ThermoSurfaceFilm (const dictionary & dict, CloudType & owner)
Definition at line 27 of file ThermoSurfaceFilm.C.
ThermoSurfaceFilm() [2/2]
template<class CloudType > ThermoSurfaceFilm (const ThermoSurfaceFilm< CloudType > & sfm)
Definition at line 44 of file ThermoSurfaceFilm.C.
~ThermoSurfaceFilm()
template<class CloudType > virtual ~ThermoSurfaceFilm () virtual default
Member Function Documentation
cacheFilmFields() [1/2]
template<class CloudType > void cacheFilmFields (const label filmPatchi, const label primaryPatchi, const regionFilm & filmModel) protected virtual
Reimplemented from KinematicSurfaceFilm< CloudType >.
Definition at line 217 of file ThermoSurfaceFilm.C.
References KinematicSurfaceFilm< CloudType >::cacheFilmFields(), surfaceFilmRegionModel::Cp(), regionModel::toPrimary(), and surfaceFilmRegionModel::Ts().
cacheFilmFields() [2/2]
template<class CloudType > void cacheFilmFields (const areaFilm & film) protected virtual
Reimplemented from KinematicSurfaceFilm< CloudType >.
Definition at line 240 of file ThermoSurfaceFilm.C.
References KinematicSurfaceFilm< CloudType >::cacheFilmFields(), liquidFilmBase::Cp(), and liquidFilmBase::Tf().
setParcelProperties()
template<class CloudType > void setParcelProperties (parcelType & p, const label filmFacei) const protected virtual
Reimplemented from KinematicSurfaceFilm< CloudType >.
Definition at line 256 of file ThermoSurfaceFilm.C.
References p, KinematicSurfaceFilm< CloudType >::setParcelProperties(), and GeometricField< Type, PatchField, GeoMesh >::T().
TypeName()
template<class CloudType > TypeName ("thermoSurfaceFilm")
clone()
template<class CloudType > virtual autoPtr< SurfaceFilmModel< CloudType > > clone () const inline virtual
Reimplemented from KinematicSurfaceFilm< CloudType >.
Definition at line 126 of file ThermoSurfaceFilm.H.
transferParcel()
template<class CloudType > bool transferParcel (parcelType & p, const polyPatch & pp, bool & keepParticle) virtual
Reimplemented from KinematicSurfaceFilm< CloudType >.
Definition at line 59 of file ThermoSurfaceFilm.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, mu, p, pp(), and GeometricField< Type, PatchField, GeoMesh >::T().
info()
template<class CloudType > void info () virtual
Reimplemented from KinematicSurfaceFilm< CloudType >.
Definition at line 271 of file ThermoSurfaceFilm.C.
References KinematicSurfaceFilm< CloudType >::info().
Member Data Documentation
thermo_
template<class CloudType > const SLGThermo& thermo_ protected
Definition at line 76 of file ThermoSurfaceFilm.H.
TFilmPatch_
template<class CloudType > scalarField TFilmPatch_ protected
Definition at line 82 of file ThermoSurfaceFilm.H.
CpFilmPatch_
template<class CloudType > scalarField CpFilmPatch_ protected
Definition at line 85 of file ThermoSurfaceFilm.H.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/Thermodynamic/SurfaceFilmModel/ThermoSurfaceFilm/ThermoSurfaceFilm.H
src/lagrangian/intermediate/submodels/Thermodynamic/SurfaceFilmModel/ThermoSurfaceFilm/ThermoSurfaceFilm.C