OpenFOAM: ConstantField< Type > Class Template Reference
ConstantField< Type > Class Template Reference
Templated function that returns a constant value.
#include <ConstantField.H>
Public Member Functions
TypeName ("constant")
ConstantField (const polyPatch &pp, const word &entryName, const Type &uniformValue, const dictionary &dict=dictionary::null, const bool faceValues=true)
ConstantField (const polyPatch &pp, const word &entryName, const bool isUniform, const Type &uniformValue, const Field< Type > &fieldValues, const dictionary &dict=dictionary::null, const bool faceValues=true)
ConstantField (const polyPatch &pp, const word &redirectType, const word &entryName, const dictionary &dict, const bool faceValues=true)
ConstantField (const polyPatch &pp, const entry *eptr, const word &entryName, const dictionary &dict, const bool faceValues=true)
ConstantField (const ConstantField< Type > &rhs)
ConstantField (const ConstantField< Type > &rhs, const polyPatch &pp)
virtual tmp< PatchFunction1< Type > > clone () const
virtual tmp< PatchFunction1< Type > > clone (const polyPatch &pp) const
virtual ~ConstantField ()=default
virtual bool constant () const
virtual bool uniform () const
virtual tmp< Field< Type > > value (const scalar x) const
virtual tmp< Field< Type > > integrate (const scalar x1, const scalar x2) const
virtual void autoMap (const FieldMapper &mapper)
virtual void rmap (const PatchFunction1< Type > &pf1, const labelList &addr)
virtual void writeData (Ostream &os) const
Public Member Functions inherited from PatchFunction1< Type >
TypeName ("PatchFunction1") declareRunTimeSelectionTable(autoPtr
PatchFunction1 (const polyPatch &pp, const word &entryName, const bool faceValues=true)
PatchFunction1 (const polyPatch &pp, const word &entryName, const dictionary &dict, const bool faceValues=true)
PatchFunction1 (const PatchFunction1< Type > &rhs)
PatchFunction1 (const PatchFunction1< Type > &rhs, const polyPatch &pp)
virtual ~PatchFunction1 ()=default
virtual bool good () const
virtual tmp< pointField > localPosition (const pointField &globalPos) const
virtual tmp< Field< Type > > transform (const Field< Type > &fld) const
virtual tmp< Field< Type > > transform (const tmp< Field< Type > > &tfld) const
Public Member Functions inherited from patchFunction1Base
patchFunction1Base (const polyPatch &pp, const word &entryName, const bool faceValues=true)
patchFunction1Base (const polyPatch &pp, const word &entryName, const dictionary &dict, const bool faceValues=true)
patchFunction1Base (const patchFunction1Base &rhs)
patchFunction1Base (const patchFunction1Base &rhs, const polyPatch &pp)
virtual ~patchFunction1Base ()=default
const word & name () const noexcept
const polyPatch & patch () const noexcept
bool faceValues () const noexcept
label size () const
const objectRegistry * whichDb () const
const objectRegistry & obr () const
const Time & time () const
virtual void userTimeToTime (const Time &t)
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Additional Inherited Members
Public Types inherited from PatchFunction1< Type >
typedef Field< Type > returnType
Static Public Member Functions inherited from PatchFunction1< Type >
static autoPtr< PatchFunction1< Type > > New (const polyPatch &pp, const word &entryName, const dictionary &dict, const bool faceValues=true, const bool mandatory=true)
static autoPtr< PatchFunction1< Type > > NewCompat (const polyPatch &pp, const word &entryName, std::initializer_list< std::pair< const char *, int > > compat, const dictionary &dict, const bool faceValues=true, const bool mandatory=true)
static autoPtr< PatchFunction1< Type > > NewIfPresent (const polyPatch &pp, const word &entryName, const dictionary &dict, const bool faceValues=true)
static refPtr< PatchFunction1< Type > > New (HashPtrTable< PatchFunction1< Type > > &cache, const polyPatch &pp, const word &entryName, const dictionary &dict, enum keyType::option matchOpt=keyType::LITERAL, const bool faceValues=true, const bool mandatory=true)
Public Attributes inherited from PatchFunction1< Type >
PatchFunction1
dictionary
const polyPatch & pp
const polyPatch const word & type
const polyPatch const word const word & entryName
const polyPatch const word const word const dictionary & dict
const polyPatch const word const word const dictionary const bool faceValues
const polyPatch const word const word const dictionary const bool pp
const polyPatch const word const word const dictionary const bool type
const polyPatch const word const word const dictionary const bool entryName
const polyPatch const word const word const dictionary const bool dict
Protected Member Functions inherited from PatchFunction1< Type >
void operator= (const PatchFunction1< Type > &)=delete
Protected Member Functions inherited from patchFunction1Base
void operator= (const patchFunction1Base &)=delete
Protected Attributes inherited from PatchFunction1< Type >
coordinateScaling< Type > coordSys_
Protected Attributes inherited from patchFunction1Base
const word name_
const polyPatch & patch_
const bool faceValues_
Detailed Description
template<class Type>
class Foam::PatchFunction1Types::ConstantField< Type >
Templated function that returns a constant value.
Usage - for entry <entryName> returning the value <value>:
    <entryName>    constant  <value>;
or
    <entryName>
    {
        type    constant;
        value   <value>;
    }
Source files
ConstantField.H
ConstantField.C
Definition at line 62 of file ConstantField.H.
Constructor & Destructor Documentation
ConstantField() [1/6]
template<class Type > ConstantField (const polyPatch & pp, const word & entryName, const Type & uniformValue, const dictionary & dict = dictionary::null, const bool faceValues = true)
Definition at line 26 of file ConstantField.C.
ConstantField() [2/6]
template<class Type > ConstantField (const polyPatch & pp, const word & entryName, const bool isUniform, const Type & uniformValue, const Field< Type > & fieldValues, const dictionary & dict = dictionary::null, const bool faceValues = true)
Definition at line 43 of file ConstantField.C.
References PatchFunction1< Type >::dict, Foam::exit(), PatchFunction1< Type >::faceValues, Foam::FatalIOError, FatalIOErrorInFunction, patchIdentifier::name(), Foam::nl, patchFunction1Base::size(), and UPtrList< T >::size().
ConstantField() [3/6]
template<class Type > ConstantField (const polyPatch & pp, const word & redirectType, const word & entryName, const dictionary & dict, const bool faceValues = true)
Definition at line 189 of file ConstantField.C.
ConstantField() [4/6]
template<class Type > ConstantField (const polyPatch & pp, const entry * eptr, const word & entryName, const dictionary & dict, const bool faceValues = true)
Definition at line 217 of file ConstantField.C.
ConstantField() [5/6]
template<class Type > ConstantField (const ConstantField< Type > & rhs) explicit
Definition at line 245 of file ConstantField.C.
ConstantField() [6/6]
template<class Type > ConstantField (const ConstantField< Type > & rhs, const polyPatch & pp) explicit
Definition at line 255 of file ConstantField.C.
References PtrList< T >::resize(), patchFunction1Base::size(), and Foam::Zero.
~ConstantField()
template<class Type > virtual ~ConstantField () virtual default
Member Function Documentation
TypeName()
template<class Type > TypeName ("constant")
clone() [1/2]
template<class Type > virtual tmp< PatchFunction1< Type > > clone () const inline virtual
Implements PatchFunction1< Type >.
Definition at line 156 of file ConstantField.H.
clone() [2/2]
template<class Type > virtual tmp< PatchFunction1< Type > > clone (const polyPatch & pp) const inline virtual
Implements PatchFunction1< Type >.
Definition at line 162 of file ConstantField.H.
References PatchFunction1< Type >::pp.
constant()
template<class Type > virtual bool constant () const inline virtual
Reimplemented from PatchFunction1< Type >.
Definition at line 178 of file ConstantField.H.
uniform()
template<class Type > virtual bool uniform () const inline virtual
Implements PatchFunction1< Type >.
Definition at line 184 of file ConstantField.H.
References PatchFunction1< Type >::uniform().
value()
template<class Type > Foam::tmp< Foam::Field< Type > > value (const scalar x) const inline virtual
Reimplemented from PatchFunction1< Type >.
Definition at line 27 of file ConstantFieldI.H.
References Foam::transform().
integrate()
template<class Type > Foam::tmp< Foam::Field< Type > > integrate (const scalar x1, const scalar x2) const inline virtual
Reimplemented from PatchFunction1< Type >.
Definition at line 43 of file ConstantFieldI.H.
References Foam::transform().
autoMap()
template<class Type > void autoMap (const FieldMapper & mapper) virtual
Reimplemented from PatchFunction1< Type >.
Definition at line 279 of file ConstantField.C.
rmap()
template<class Type > void rmap (const PatchFunction1< Type > & pf1, const labelList & addr) virtual
Reimplemented from PatchFunction1< Type >.
Definition at line 295 of file ConstantField.C.
writeData()
template<class Type > void writeData (Ostream & os) const virtual
Reimplemented from PatchFunction1< Type >.
Definition at line 307 of file ConstantField.C.
References Foam::name(), os(), token::SPACE, and PatchFunction1< Type >::writeData().
The documentation for this class was generated from the following files:
src/meshTools/PatchFunction1/ConstantField/ConstantField.H
src/meshTools/PatchFunction1/ConstantField/ConstantField.C
src/meshTools/PatchFunction1/ConstantField/ConstantFieldI.H