OpenFOAM: triangleFuncs Class Reference
triangleFuncs Class Reference
Contains various triangle static functions.
#include <triangleFuncs.H>
Static Public Member Functions
static bool intersectAxesBundle (const point &V0, const point &V10, const point &V20, const label i0, const pointField &origin, const scalar maxLength, point &pInter)
static bool intersectBb (const triPointRef &tri, const treeBoundBox &cubeBb)
static bool intersectBb (const point &p0, const point &p1, const point &p2, const treeBoundBox &cubeBb)
static bool intersect (const point &va0, const point &va10, const point &va20, const point &basePoint, const vector &normal, point &pInter0, point &pInter1)
static bool intersect (const point &va0, const point &va10, const point &va20, const point &vb0, const point &vb10, const point &vb20, point &pInter0, point &pInter1)
Detailed Description
Contains various triangle static functions.
Source files
triangleFuncs.H
triangleFuncs.C
Definition at line 51 of file triangleFuncs.H.
Member Function Documentation
intersectAxesBundle()
bool intersectAxesBundle (const point & V0, const point & V10, const point & V20, const label i0, const pointField & origin, const scalar maxLength, point & pInter) static
Definition at line 59 of file triangleFuncs.C.
References alpha, beta(), Foam::det(), forAll, Foam::mag(), s(), and u0.
intersectBb() [1/2]
bool intersectBb (const triPointRef & tri, const treeBoundBox & cubeBb) static
Definition at line 143 of file triangleFuncs.C.
References triangle< Point, PointRef >::a(), triangle< Point, PointRef >::b(), triangle< Point, PointRef >::c(), e, treeBoundBox::edges, intersection::HALF_RAY, triangle< Point, PointRef >::intersection(), and points.
intersectBb() [2/2]
bool intersectBb (const point & p0, const point & p1, const point & p2, const treeBoundBox & cubeBb) static
Definition at line 187 of file triangleFuncs.C.
References p0.
intersect() [1/2]
bool intersect (const point & va0, const point & va10, const point & va20, const point & basePoint, const vector & normal, point & pInter0, point & pInter1) static
Definition at line 201 of file triangleFuncs.C.
References Foam::mag(), and Foam::sqrt().
intersect() [2/2]
bool intersect (const point & va0, const point & va10, const point & va20, const point & vb0, const point & vb10, const point & vb20, point & pInter0, point & pInter1) static
Definition at line 319 of file triangleFuncs.C.
References Foam::mag(), and pts.
The documentation for this class was generated from the following files:
src/meshTools/triSurface/triangleFuncs/triangleFuncs.H
src/meshTools/triSurface/triangleFuncs/triangleFuncs.C