OpenFOAM: SmagorinskyZhang< BasicTurbulenceModel > Class Template Reference
SmagorinskyZhang< BasicTurbulenceModel > Class Template Reference
Turbulence models » LES turbulence
The Smagorinsky SGS model including bubble-generated turbulence.
#include <SmagorinskyZhang.H>
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from Smagorinsky< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from LESeddyViscosity< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from eddyViscosity< LESModel< BasicTurbulenceModel > >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from linearViscousStress< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("SmagorinskyZhang")
SmagorinskyZhang (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
virtual ~SmagorinskyZhang ()=default
virtual bool read ()
Public Member Functions inherited from Smagorinsky< BasicTurbulenceModel >
TypeName ("Smagorinsky")
Smagorinsky (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
virtual ~Smagorinsky ()=default
virtual tmp< volScalarField > k () const
virtual void correct ()
Public Member Functions inherited from LESeddyViscosity< BasicTurbulenceModel >
LESeddyViscosity (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
virtual ~LESeddyViscosity ()=default
Public Member Functions inherited from eddyViscosity< LESModel< BasicTurbulenceModel > >
eddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~eddyViscosity ()=default
virtual tmp< volScalarField > nut () const
virtual tmp< scalarField > nut (const label patchi) const
virtual tmp< volSymmTensorField > R () const
virtual void validate ()
Public Member Functions inherited from linearViscousStress< BasicTurbulenceModel >
linearViscousStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~linearViscousStress ()=default
virtual tmp< volSymmTensorField > devRhoReff () const
virtual tmp< volSymmTensorField > devRhoReff (const volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Protected Member Functions
virtual void correctNut ()
Protected Member Functions inherited from Smagorinsky< BasicTurbulenceModel >
tmp< volScalarField > k (const tmp< volTensorField > &gradU) const
Protected Attributes
dimensionedScalar Cmub_
Protected Attributes inherited from Smagorinsky< BasicTurbulenceModel >
dimensionedScalar Ck_
Protected Attributes inherited from eddyViscosity< LESModel< BasicTurbulenceModel > >
volScalarField nut_
Detailed Description
template<class BasicTurbulenceModel>
class Foam::LESModels::SmagorinskyZhang< BasicTurbulenceModel >
The Smagorinsky SGS model including bubble-generated turbulence.
Reference:
    Zhang, D., Deen, N. G., & Kuipers, J. A. M. (2006).
    Numerical simulation of the dynamic flow behavior in a bubble column:
    a study of closures for turbulence and interface forces.
    Chemical Engineering Science, 61(23), 7593-7608.
The default model coefficients are
    SmagorinskyZhangCoeffs
    {
        Ck              0.094;
        Ce              1.048;
        Cmub            0.6;
    }
Source files
SmagorinskyZhang.H
SmagorinskyZhang.C
Definition at line 71 of file SmagorinskyZhang.H.
Member Typedef Documentation
alphaField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 115 of file SmagorinskyZhang.H.
rhoField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 116 of file SmagorinskyZhang.H.
transportModel
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 117 of file SmagorinskyZhang.H.
Constructor & Destructor Documentation
SmagorinskyZhang()
template<class BasicTurbulenceModel > SmagorinskyZhang (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Definition at line 35 of file SmagorinskyZhang.C.
References Foam::type().
~SmagorinskyZhang()
template<class BasicTurbulenceModel > virtual ~SmagorinskyZhang () virtual default
Member Function Documentation
correctNut()
template<class BasicTurbulenceModel > void correctNut () protected virtual
Reimplemented from Smagorinsky< BasicTurbulenceModel >.
Definition at line 127 of file SmagorinskyZhang.C.
References delta, Foam::fvc::grad(), k, Foam::mag(), options::New(), and Foam::sqrt().
TypeName()
template<class BasicTurbulenceModel > TypeName ("SmagorinskyZhang< BasicTurbulenceModel >")
read()
template<class BasicTurbulenceModel > bool read () virtual
Reimplemented from Smagorinsky< BasicTurbulenceModel >.
Definition at line 81 of file SmagorinskyZhang.C.
Member Data Documentation
Cmub_
template<class BasicTurbulenceModel > dimensionedScalar Cmub_ protected
Definition at line 105 of file SmagorinskyZhang.H.
The documentation for this class was generated from the following files:
src/TurbulenceModels/phaseCompressible/LES/SmagorinskyZhang/SmagorinskyZhang.H
src/TurbulenceModels/phaseCompressible/LES/SmagorinskyZhang/SmagorinskyZhang.C