OpenFOAM: Stochastic< CloudType > Class Template Reference
Stochastic< CloudType > Class Template Reference
Lagrangian particle models » Submodels » MP-PIC » Isotropy
Stochastic return-to-isotropy model.
#include <Stochastic.H>
Public Member Functions
TypeName ("stochastic")
Stochastic (const dictionary &dict, CloudType &owner)
Stochastic (const Stochastic< CloudType > &cm)
virtual autoPtr< IsotropyModel< CloudType > > clone () const
virtual ~Stochastic ()
virtual void calculate ()
Public Member Functions inherited from IsotropyModel< CloudType >
TypeName ("isotropyModel")
declareRunTimeSelectionTable (autoPtr, IsotropyModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
IsotropyModel (CloudType &owner)
IsotropyModel (const dictionary &dict, CloudType &owner, const word &type)
IsotropyModel (const IsotropyModel< CloudType > &cm)
virtual ~IsotropyModel ()
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
virtual ~CloudSubModelBase ()=default
const CloudType & owner () const
virtual bool writeTime () const
virtual fileName localPath () const
CloudType & owner ()
virtual void info ()
virtual void write (Ostream &os) const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
subModelBase (const subModelBase &smb)
virtual ~subModelBase ()=default
const word & modelName () const
const dictionary & dict () const
const word & baseName () const
const word & modelType () const
const dictionary & coeffDict () const
const dictionary & properties () const
virtual bool defaultCoeffs (const bool printMsg) const
virtual bool active () const
virtual void cacheFields (const bool store)
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
bool getModelDict (const word &entryName, dictionary &dict) const
template<class Type >
bool getModelProperty (const word &entryName, Type &value) const
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Additional Inherited Members
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Static Public Member Functions inherited from IsotropyModel< CloudType >
static autoPtr< IsotropyModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Public Attributes inherited from subModelBase
bool log
Protected Member Functions inherited from subModelBase
bool inLine () const
Protected Attributes inherited from IsotropyModel< CloudType >
autoPtr< TimeScaleModel > timeScaleModel_
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Protected Attributes inherited from subModelBase
const word modelName_
dictionary & properties_
const dictionary dict_
const word baseName_
const word modelType_
const dictionary coeffDict_
Detailed Description
template<class CloudType>
class Foam::IsotropyModels::Stochastic< CloudType >
Stochastic return-to-isotropy model.
Particle velocities are modified by sampling a gaussian-plus-delta distribution, which depends on a time-scale. This randomises some particle velocities whilst leaving others unchanged. The lower the value of the time-scale, the greater the proportion of particle velocities affected.
A correction step is performed at the end to ensure that the model conserves both momentum and granular temperature.
Reference:
    "Inclusion of collisional return-to-isotropy in the MP-PIC method"
    P O'Rourke and D Snider
    Chemical Engineering Science
    Volume 80, Issue 0, Pages 39-54, December 2012
Source files
Stochastic.H
Stochastic.C
Definition at line 68 of file Stochastic.H.
Constructor & Destructor Documentation
Stochastic() [1/2]
template<class CloudType > Stochastic (const dictionary & dict, CloudType & owner)
Definition at line 27 of file Stochastic.C.
Stochastic() [2/2]
template<class CloudType > Stochastic (const Stochastic< CloudType > & cm)
Definition at line 38 of file Stochastic.C.
~Stochastic()
template<class CloudType > ~Stochastic () virtual
Definition at line 50 of file Stochastic.C.
Member Function Documentation
TypeName()
template<class CloudType > TypeName ("stochastic")
clone()
template<class CloudType > virtual autoPtr< IsotropyModel< CloudType > > clone () const inline virtual
Implements IsotropyModel< CloudType >.
Definition at line 94 of file Stochastic.H.
calculate()
template<class CloudType > void calculate () virtual
Implements IsotropyModel< CloudType >.
Definition at line 93 of file Stochastic.C.
References dict, Foam::exp(), Foam::magSqr(), Foam::max(), mesh, Foam::name(), p, rndGen, Foam::sqrt(), timeName, and x.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/MPPIC/IsotropyModels/Stochastic/Stochastic.H
src/lagrangian/intermediate/submodels/MPPIC/IsotropyModels/Stochastic/Stochastic.C