OpenFOAM: freeSurfacePressureFvPatchScalarField Class Reference
freeSurfacePressureFvPatchScalarField Class Reference
Boundary conditions » Generic
This boundary condition provides static pressure condition for p_rgh, calculated as:
#include <freeSurfacePressureFvPatchScalarField.H>
Public Member Functions
TypeName ("freeSurfacePressure")
freeSurfacePressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
freeSurfacePressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
freeSurfacePressureFvPatchScalarField (const freeSurfacePressureFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
freeSurfacePressureFvPatchScalarField (const freeSurfacePressureFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
freeSurfacePressureFvPatchScalarField (const freeSurfacePressureFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
const scalarField & pa () const
scalarField & pa ()
virtual void autoMap (const fvPatchFieldMapper &)
virtual void rmap (const fvPatchScalarField &, const labelList &)
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Protected Attributes
scalarField pa_
Detailed Description
This boundary condition provides static pressure condition for p_rgh, calculated as:
where
= Free surface modified pressure
= Free surface ambient pressure
= acceleration due to gravity [m/s^2]
Usage
Property Description Required Default value
pa static ambient pressure yes 0
Example of the boundary condition specification:
    <patchName>
    {
        type            freeSurfacePressure;
        pa              uniform 0;
        value           uniform 0; // optional initial value
    }
See also
Foam::fixedValueFvPatchScalarField
Source files
freeSurfacePressureFvPatchScalarField.H
freeSurfacePressureFvPatchScalarField.C
Definition at line 102 of file freeSurfacePressureFvPatchScalarField.H.
Constructor & Destructor Documentation
freeSurfacePressureFvPatchScalarField() [1/5]
freeSurfacePressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 32 of file freeSurfacePressureFvPatchScalarField.C.
freeSurfacePressureFvPatchScalarField() [2/5]
freeSurfacePressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 44 of file freeSurfacePressureFvPatchScalarField.C.
References dict, fvPatchField< Type >::operator=(), and freeSurfacePressureFvPatchScalarField::pa_.
freeSurfacePressureFvPatchScalarField() [3/5]
freeSurfacePressureFvPatchScalarField (const freeSurfacePressureFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 62 of file freeSurfacePressureFvPatchScalarField.C.
freeSurfacePressureFvPatchScalarField() [4/5]
freeSurfacePressureFvPatchScalarField (const freeSurfacePressureFvPatchScalarField & ptf)
Definition at line 76 of file freeSurfacePressureFvPatchScalarField.C.
freeSurfacePressureFvPatchScalarField() [5/5]
freeSurfacePressureFvPatchScalarField (const freeSurfacePressureFvPatchScalarField & ptf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 87 of file freeSurfacePressureFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("freeSurfacePressure")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 153 of file freeSurfacePressureFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 169 of file freeSurfacePressureFvPatchScalarField.H.
pa() [1/2]
const scalarField & pa () const inline
Definition at line 186 of file freeSurfacePressureFvPatchScalarField.H.
References freeSurfacePressureFvPatchScalarField::pa_.
pa() [2/2]
scalarField & pa () inline
Definition at line 192 of file freeSurfacePressureFvPatchScalarField.H.
References freeSurfacePressureFvPatchScalarField::pa_.
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Definition at line 101 of file freeSurfacePressureFvPatchScalarField.C.
rmap()
void rmap (const fvPatchScalarField & ptf, const labelList & addr) virtual
Definition at line 111 of file freeSurfacePressureFvPatchScalarField.C.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 126 of file freeSurfacePressureFvPatchScalarField.C.
References objectRegistry::lookupObject(), and mesh.
write()
void write (Ostream & os) const virtual
Definition at line 153 of file freeSurfacePressureFvPatchScalarField.C.
References os(), fvPatchField< Type >::write(), and fvPatchField< Type >::writeValueEntry().
Member Data Documentation
pa_
scalarField pa_ protected
Definition at line 111 of file freeSurfacePressureFvPatchScalarField.H.
Referenced by freeSurfacePressureFvPatchScalarField::freeSurfacePressureFvPatchScalarField(), freeSurfacePressureFvPatchScalarField::pa(), and freeSurfacePressureFvPatchScalarField::pa().
The documentation for this class was generated from the following files:
src/dynamicFaMesh/interfaceTrackingFvMesh/fvPatchFields/freeSurfacePressure/freeSurfacePressureFvPatchScalarField.H
src/dynamicFaMesh/interfaceTrackingFvMesh/fvPatchFields/freeSurfacePressure/freeSurfacePressureFvPatchScalarField.C