OpenFOAM: ShihQuadraticKE Class Reference
ShihQuadraticKE Class Reference
Shih's quadratic algebraic Reynolds stress k-epsilon turbulence model for incompressible flows.
#include <ShihQuadraticKE.H>
Public Member Functions
TypeName ("ShihQuadraticKE")
ShihQuadraticKE (const geometricOneField &alpha, const geometricOneField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
virtual ~ShihQuadraticKE ()=default
virtual bool read ()
tmp< volScalarField > DkEff () const
tmp< volScalarField > DepsilonEff () const
virtual tmp< volScalarField > k () const
virtual tmp< volScalarField > epsilon () const
virtual void correct ()
Public Member Functions inherited from nonlinearEddyViscosity< incompressible::RASModel >
nonlinearEddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~nonlinearEddyViscosity ()=default
virtual tmp< volSymmTensorField > R () const
virtual tmp< volSymmTensorField > devRhoReff () const
virtual tmp< volSymmTensorField > devRhoReff (const volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Public Member Functions inherited from eddyViscosity< BasicTurbulenceModel >
eddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~eddyViscosity ()=default
virtual tmp< volScalarField > nut () const
virtual tmp< scalarField > nut (const label patchi) const
virtual void validate ()
Public Member Functions inherited from linearViscousStress< BasicTurbulenceModel >
linearViscousStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~linearViscousStress ()=default
Protected Member Functions
virtual void correctNut ()
virtual void correctNonlinearStress (const volTensorField &gradU)
Protected Attributes
dimensionedScalar Ceps1_
dimensionedScalar Ceps2_
dimensionedScalar sigmak_
dimensionedScalar sigmaEps_
dimensionedScalar Cmu1_
dimensionedScalar Cmu2_
dimensionedScalar Cbeta_
dimensionedScalar Cbeta1_
dimensionedScalar Cbeta2_
dimensionedScalar Cbeta3_
volScalarField k_
volScalarField epsilon_
Protected Attributes inherited from nonlinearEddyViscosity< incompressible::RASModel >
volSymmTensorField nonlinearStress_
Protected Attributes inherited from eddyViscosity< BasicTurbulenceModel >
volScalarField nut_
Additional Inherited Members
Public Types inherited from nonlinearEddyViscosity< incompressible::RASModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from eddyViscosity< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from linearViscousStress< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Detailed Description
Shih's quadratic algebraic Reynolds stress k-epsilon turbulence model for incompressible flows.
This turbulence model is described in:
    Shih, T. H., Zhu, J., & Lumley, J. L. (1993).
    A realizable Reynolds stress algebraic equation model.
    NASA technical memorandum 105993.
Implemented according to the specification in: Apsley: Turbulence Models 2002
Source files
ShihQuadraticKE.H
ShihQuadraticKE.C
Definition at line 68 of file ShihQuadraticKE.H.
Constructor & Destructor Documentation
ShihQuadraticKE()
ShihQuadraticKE (const geometricOneField & alpha, const geometricOneField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Definition at line 74 of file ShihQuadraticKE.C.
References Foam::bound(), ShihQuadraticKE::epsilon_, ShihQuadraticKE::k_, and Foam::type().
~ShihQuadraticKE()
virtual ~ShihQuadraticKE () virtual default
Member Function Documentation
correctNut()
void correctNut () protected virtual
Implements eddyViscosity< BasicTurbulenceModel >.
Definition at line 43 of file ShihQuadraticKE.C.
References ShihQuadraticKE::correctNonlinearStress(), and Foam::fvc::grad().
correctNonlinearStress()
void correctNonlinearStress (const volTensorField & gradU) protected virtual
Implements nonlinearEddyViscosity< incompressible::RASModel >.
Definition at line 49 of file ShihQuadraticKE.C.
References ShihQuadraticKE::Cbeta1_, ShihQuadraticKE::Cbeta2_, ShihQuadraticKE::Cbeta3_, ShihQuadraticKE::Cbeta_, ShihQuadraticKE::Cmu1_, ShihQuadraticKE::Cmu2_, GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), Foam::dev(), Foam::devSymm(), ShihQuadraticKE::epsilon_, Foam::innerSqr(), ShihQuadraticKE::k_, Foam::mag(), nonlinearEddyViscosity< incompressible::RASModel >::nonlinearStress_, eddyViscosity< BasicTurbulenceModel >::nut_, Foam::pow3(), Foam::skew(), Foam::sqr(), Foam::sqrt(), Foam::symm(), and Foam::twoSymm().
Referenced by ShihQuadraticKE::correct(), and ShihQuadraticKE::correctNut().
TypeName()
TypeName ("ShihQuadraticKE")
read()
bool read () virtual
Implements eddyViscosity< BasicTurbulenceModel >.
Definition at line 227 of file ShihQuadraticKE.C.
References ShihQuadraticKE::Cbeta1_, ShihQuadraticKE::Cbeta2_, ShihQuadraticKE::Cbeta3_, ShihQuadraticKE::Cbeta_, ShihQuadraticKE::Ceps1_, ShihQuadraticKE::Ceps2_, ShihQuadraticKE::Cmu1_, ShihQuadraticKE::Cmu2_, dimensioned< Type >::readIfPresent(), ShihQuadraticKE::sigmaEps_, and ShihQuadraticKE::sigmak_.
DkEff()
tmp< volScalarField > DkEff () const inline
Definition at line 135 of file ShihQuadraticKE.H.
References nu, eddyViscosity< BasicTurbulenceModel >::nut_, and ShihQuadraticKE::sigmak_.
Referenced by ShihQuadraticKE::correct().
DepsilonEff()
tmp< volScalarField > DepsilonEff () const inline
Definition at line 144 of file ShihQuadraticKE.H.
References nu, eddyViscosity< BasicTurbulenceModel >::nut_, and ShihQuadraticKE::sigmaEps_.
Referenced by ShihQuadraticKE::correct().
k()
virtual tmp< volScalarField > k () const inline virtual
Implements eddyViscosity< BasicTurbulenceModel >.
Definition at line 153 of file ShihQuadraticKE.H.
References ShihQuadraticKE::k_.
epsilon()
virtual tmp< volScalarField > epsilon () const inline virtual
Definition at line 159 of file ShihQuadraticKE.H.
References ShihQuadraticKE::epsilon_.
correct()
void correct () virtual
Implements eddyViscosity< BasicTurbulenceModel >.
Definition at line 249 of file ShihQuadraticKE.C.
References Foam::bound(), GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), ShihQuadraticKE::Ceps1_, ShihQuadraticKE::Ceps2_, eddyViscosity< BasicTurbulenceModel >::correct(), ShihQuadraticKE::correctNonlinearStress(), Foam::fvm::ddt(), ShihQuadraticKE::DepsilonEff(), Foam::fvm::div(), ShihQuadraticKE::DkEff(), ShihQuadraticKE::epsilon_, GeometricBoundaryField< Type, PatchField, GeoMesh >::evaluateCoupled(), Foam::fvc::grad(), ShihQuadraticKE::k_, Foam::fvm::laplacian(), nonlinearEddyViscosity< incompressible::RASModel >::nonlinearStress_, eddyViscosity< BasicTurbulenceModel >::nut_, solve(), Foam::fvm::Sp(), Foam::twoSymm(), and GeometricBoundaryField< Type, PatchField, GeoMesh >::updateCoeffs().
Member Data Documentation
Ceps1_
dimensionedScalar Ceps1_ protected
Definition at line 79 of file ShihQuadraticKE.H.
Referenced by ShihQuadraticKE::correct(), and ShihQuadraticKE::read().
Ceps2_
dimensionedScalar Ceps2_ protected
Definition at line 80 of file ShihQuadraticKE.H.
Referenced by ShihQuadraticKE::correct(), and ShihQuadraticKE::read().
sigmak_
dimensionedScalar sigmak_ protected
Definition at line 81 of file ShihQuadraticKE.H.
Referenced by ShihQuadraticKE::DkEff(), and ShihQuadraticKE::read().
sigmaEps_
dimensionedScalar sigmaEps_ protected
Definition at line 82 of file ShihQuadraticKE.H.
Referenced by ShihQuadraticKE::DepsilonEff(), and ShihQuadraticKE::read().
Cmu1_
dimensionedScalar Cmu1_ protected
Definition at line 83 of file ShihQuadraticKE.H.
Referenced by ShihQuadraticKE::correctNonlinearStress(), and ShihQuadraticKE::read().
Cmu2_
dimensionedScalar Cmu2_ protected
Definition at line 84 of file ShihQuadraticKE.H.
Referenced by ShihQuadraticKE::correctNonlinearStress(), and ShihQuadraticKE::read().
Cbeta_
dimensionedScalar Cbeta_ protected
Definition at line 85 of file ShihQuadraticKE.H.
Referenced by ShihQuadraticKE::correctNonlinearStress(), and ShihQuadraticKE::read().
Cbeta1_
dimensionedScalar Cbeta1_ protected
Definition at line 86 of file ShihQuadraticKE.H.
Referenced by ShihQuadraticKE::correctNonlinearStress(), and ShihQuadraticKE::read().
Cbeta2_
dimensionedScalar Cbeta2_ protected
Definition at line 87 of file ShihQuadraticKE.H.
Referenced by ShihQuadraticKE::correctNonlinearStress(), and ShihQuadraticKE::read().
Cbeta3_
dimensionedScalar Cbeta3_ protected
Definition at line 88 of file ShihQuadraticKE.H.
Referenced by ShihQuadraticKE::correctNonlinearStress(), and ShihQuadraticKE::read().
k_
volScalarField k_ protected
Definition at line 93 of file ShihQuadraticKE.H.
Referenced by ShihQuadraticKE::correct(), ShihQuadraticKE::correctNonlinearStress(), ShihQuadraticKE::k(), and ShihQuadraticKE::ShihQuadraticKE().
epsilon_
volScalarField epsilon_ protected
Definition at line 94 of file ShihQuadraticKE.H.
Referenced by ShihQuadraticKE::correct(), ShihQuadraticKE::correctNonlinearStress(), ShihQuadraticKE::epsilon(), and ShihQuadraticKE::ShihQuadraticKE().
The documentation for this class was generated from the following files:
src/TurbulenceModels/incompressible/turbulentTransportModels/RAS/ShihQuadraticKE/ShihQuadraticKE.H
src/TurbulenceModels/incompressible/turbulentTransportModels/RAS/ShihQuadraticKE/ShihQuadraticKE.C