OpenFOAM: coordinateScaling< Type > Class Template Reference
coordinateScaling< Type > Class Template Reference
Helper class to wrap coordinate system and component-wise scaling.
#include <coordinateScaling.H>
Public Member Functions
coordinateScaling ()
coordinateScaling (const objectRegistry &obr, const dictionary &dict)
coordinateScaling (const coordinateScaling &rhs)
virtual ~coordinateScaling ()=default
bool active () const noexcept
const autoPtr< coordinateSystem > & coordSys () const
tmp< pointField > localPosition (const pointField &globalPos) const
virtual tmp< Field< Type > > transform (const pointField &pos, const Field< Type > &local) const
virtual void writeEntry (Ostream &os) const
tmp< Field< label > > transform (const pointField &pos, const Field< label > &local) const
Foam::tmp< Foam::Field< Foam::label > > transform (const pointField &pos, const Field< label > &local) const
Detailed Description
template<class Type>
class Foam::coordinateScaling< Type >
Helper class to wrap coordinate system and component-wise scaling.
See also
Foam::Function1Types
Source files
coordinateScaling.H
coordinateScaling.C
Definition at line 51 of file coordinateScaling.H.
Constructor & Destructor Documentation
coordinateScaling() [1/3]
template<class Type > coordinateScaling ()
Definition at line 24 of file coordinateScaling.C.
coordinateScaling() [2/3]
template<class Type > coordinateScaling (const objectRegistry & obr, const dictionary & dict)
Definition at line 33 of file coordinateScaling.C.
References dict, Foam::name(), VectorSpace< Form, Cmpt, Ncmpts >::nComponents, Function1< Type >::NewIfPresent(), and PtrList< T >::set().
coordinateScaling() [3/3]
template<class Type > coordinateScaling (const coordinateScaling< Type > & rhs)
Definition at line 59 of file coordinateScaling.C.
~coordinateScaling()
template<class Type > virtual ~coordinateScaling () virtual default
Member Function Documentation
active()
template<class Type > bool active () const inline noexcept
Definition at line 95 of file coordinateScaling.H.
coordSys()
template<class Type > const autoPtr< coordinateSystem > & coordSys () const inline
Definition at line 101 of file coordinateScaling.H.
localPosition()
template<class Type > Foam::tmp< Foam::pointField > localPosition (const pointField & globalPos) const
Definition at line 70 of file coordinateScaling.C.
transform() [1/3]
template<class Type > Foam::tmp< Foam::Field< Type > > transform (const pointField & pos, const Field< Type > & local) const virtual
Definition at line 85 of file coordinateScaling.C.
writeEntry()
template<class Type > void writeEntry (Ostream & os) const virtual
Definition at line 131 of file coordinateScaling.C.
References forAll, and os().
transform() [2/3]
tmp< Field< label > > transform (const pointField & pos, const Field< label > & local) const
transform() [3/3]
Foam::tmp< Foam::Field< Foam::label > > transform (const pointField & pos, const Field< label > & local) const
Definition at line 27 of file coordinateScalings.C.
References local.
The documentation for this class was generated from the following files:
src/meshTools/PatchFunction1/coordinateScaling/coordinateScaling.H
src/meshTools/PatchFunction1/coordinateScaling/coordinateScaling.C