OpenFOAM: Shirai Class Reference
Shirai Class Reference
Temperature of departure from nulceate boiling correlation.
#include <Shirai.H>
Public Member Functions
TypeName ("Shirai")
Shirai (const dictionary &dict)
virtual ~Shirai ()=default
virtual tmp< scalarField > TDNB (const phaseModel &liquid, const phaseModel &vapor, const label patchi, const scalarField &Tl, const scalarField &Tsatw, const scalarField &L) const
virtual void write (Ostream &os) const
Public Member Functions inherited from TDNBModel
TypeName ("TDNBModel")
declareRunTimeSelectionTable (autoPtr, TDNBModel, dictionary,(const dictionary &dict),(dict))
TDNBModel ()=default
virtual ~TDNBModel ()=default
Additional Inherited Members
Static Public Member Functions inherited from TDNBModel
static autoPtr< TDNBModel > New (const dictionary &dict)
Detailed Description
Temperature of departure from nulceate boiling correlation.
References:
    Shirai, Y., Tatsumoto, H., Shiotsu, M., Hata, K.,
    Kobayashi, H., Naruo, Y., & Inatani, Y. (2010).
    Boiling heat transfer from a horizontal flat
    plate in a pool of liquid hydrogen.
    Cryogenics, 50(6-7), 410-416.
    DOI:10.1016/j.cryogenics.2010.04.001
Usage
Example of the model specification:
TDNBModel
{
    // Mandatory entries
    type            Shirai;
    Tc              <scalar>;
    Pc              <scalar>;
}
where the entries mean:
Property Description Type Reqd Deflt
type Type name: Shirai word yes -
Tc Critical temperature scalar yes -
Pc Critical pressure scalar yes -
Note
Correlation based on fiting data from Fig 11 from above references.
Suitable for liquid Helium, Nitrogen, Oxygen and Hydrogen.
Source files
Shirai.H
Shirai.C
Definition at line 108 of file Shirai.H.
Constructor & Destructor Documentation
Shirai()
Shirai (const dictionary & dict)
Definition at line 45 of file Shirai.C.
~Shirai()
virtual ~Shirai () virtual default
Member Function Documentation
TypeName()
TypeName ("Shirai")
TDNB()
Foam::tmp< Foam::scalarField > TDNB (const phaseModel & liquid, const phaseModel & vapor, const label patchi, const scalarField & Tl, const scalarField & Tsatw, const scalarField & L) const virtual
Implements TDNBModel.
Definition at line 59 of file Shirai.C.
References Foam::clamp(), Foam::pow3(), and Foam::sqr().
write()
void write (Ostream & os) const virtual
Reimplemented from TDNBModel.
Definition at line 80 of file Shirai.C.
References os(), and TDNBModel::write().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/wallBoilingSubModels/TDNBModels/Shirai/Shirai.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/wallBoilingSubModels/TDNBModels/Shirai/Shirai.C