OpenFOAM: processorFaMeshes Class Reference
processorFaMeshes Class Reference
Container for finite-area processor mesh addressing.
#include <processorFaMeshes.H>
Public Member Functions
processorFaMeshes (const UPtrList< fvMesh > &procFvMeshes)
const PtrList< faMesh > & meshes () const noexcept
PtrList< faMesh > & meshes () noexcept
const PtrList< labelIOList > & pointProcAddressing () const noexcept
PtrList< labelIOList > & edgeProcAddressing () noexcept
const PtrList< labelIOList > & faceProcAddressing () const noexcept
const PtrList< labelIOList > & boundaryProcAddressing () const noexcept
Static Public Member Functions
static void removeFiles (const faMesh &mesh)
Detailed Description
Container for finite-area processor mesh addressing.
Author Zeljko Tukovic, FSB Zagreb
Source files
processorFaMeshes.H
processorFaMeshes.C
Definition at line 53 of file processorFaMeshes.H.
Constructor & Destructor Documentation
processorFaMeshes()
processorFaMeshes (const UPtrList< fvMesh > & procFvMeshes) explicit
Definition at line 74 of file processorFaMeshes.C.
Member Function Documentation
meshes() [1/2]
const PtrList< faMesh > & meshes () const inline noexcept
Definition at line 98 of file processorFaMeshes.H.
meshes() [2/2]
PtrList< faMesh > & meshes () inline noexcept
Definition at line 103 of file processorFaMeshes.H.
pointProcAddressing()
const PtrList< labelIOList > & pointProcAddressing () const inline noexcept
Definition at line 108 of file processorFaMeshes.H.
edgeProcAddressing()
PtrList< labelIOList > & edgeProcAddressing () inline noexcept
Definition at line 113 of file processorFaMeshes.H.
faceProcAddressing()
const PtrList< labelIOList > & faceProcAddressing () const inline noexcept
Definition at line 118 of file processorFaMeshes.H.
boundaryProcAddressing()
const PtrList< labelIOList > & boundaryProcAddressing () const inline noexcept
Definition at line 123 of file processorFaMeshes.H.
removeFiles()
void removeFiles (const faMesh & mesh) static
Definition at line 92 of file processorFaMeshes.C.
References polyMesh::facesInstance(), Foam::fileHandler, io(), mesh, faMesh::meshSubDir, IOobject::objectPath(), IOobject::rename(), and fvMesh::thisDb().
The documentation for this class was generated from the following files:
src/parallel/reconstruct/faReconstruct/processorFaMeshes.H
src/parallel/reconstruct/faReconstruct/processorFaMeshes.C