OpenFOAM: edgeFaceCirculator Class Reference
edgeFaceCirculator Class Reference
Walks from starting face around edge.
#include <edgeFaceCirculator.H>
Public Member Functions
edgeFaceCirculator (const primitiveMesh &mesh, const label faceLabel, const bool ownerSide, const label index, const bool isBoundaryEdge)
edgeFaceCirculator (const edgeFaceCirculator &circ)
label faceLabel () const
bool isInternalFace () const
bool ownerSide () const
label index () const
label cellLabel () const
bool sameOrder (const label v0, const label v1) const
void setCanonical ()
void operator= (const edgeFaceCirculator &iter)
bool operator== (const edgeFaceCirculator &iter) const
bool operator!= (const edgeFaceCirculator &iter) const
edgeFaceCirculator & operator++ ()
edgeFaceCirculator begin () const
edgeFaceCirculator cbegin () const
const edgeFaceCirculator end () const
const edgeFaceCirculator cend () const
Static Public Member Functions
static label getMinIndex (const face &f, const label v0, const label v1)
Detailed Description
Walks from starting face around edge.
Implicit description of edge:
face
index in face. edge is always between f[index] and f[index+1]
direction (cell to walk into)
Use in-place:
edgeFaceCirculator circ(..);
// Optionally rotate to beginning: circ.setCanonical();
// Walk
do
{
    Info<< "face:" << circ.face() << endl;
    ++circ;
}
while (circ != circ.end());
Use like STL iterator:
edgeFaceCirculator circ(..);
for
(
    edgeFaceCirculator iter = circ.begin();
    iter != circ.end();
    ++iter
)
{
    Info<< "face:" << iter.face() << endl;
}
Source files
edgeFaceCirculator.H
edgeFaceCirculator.C
Definition at line 84 of file edgeFaceCirculator.H.
Constructor & Destructor Documentation
edgeFaceCirculator() [1/2]
edgeFaceCirculator (const primitiveMesh & mesh, const label faceLabel, const bool ownerSide, const label index, const bool isBoundaryEdge) inline
Definition at line 104 of file edgeFaceCirculatorI.H.
edgeFaceCirculator() [2/2]
edgeFaceCirculator (const edgeFaceCirculator & circ) inline
Definition at line 122 of file edgeFaceCirculatorI.H.
Member Function Documentation
getMinIndex()
Foam::label getMinIndex (const face & f, const label v0, const label v1) inline static
Definition at line 135 of file edgeFaceCirculatorI.H.
References f(), UList< T >::fcIndex(), UList< T >::find(), and UList< T >::rcIndex().
faceLabel()
Foam::label faceLabel () const inline
Definition at line 166 of file edgeFaceCirculatorI.H.
isInternalFace()
bool isInternalFace () const inline
Definition at line 172 of file edgeFaceCirculatorI.H.
ownerSide()
bool ownerSide () const inline
Definition at line 183 of file edgeFaceCirculatorI.H.
index()
Foam::label index () const inline
Definition at line 189 of file edgeFaceCirculatorI.H.
cellLabel()
Foam::label cellLabel () const inline
Definition at line 195 of file edgeFaceCirculatorI.H.
References polyMesh::faceNeighbour(), polyMesh::faceOwner(), and mesh.
sameOrder()
bool sameOrder (const label v0, const label v1) const inline
Definition at line 210 of file edgeFaceCirculatorI.H.
References Foam::abort(), f(), polyMesh::faces(), Foam::FatalError, FatalErrorInFunction, and mesh.
setCanonical()
void setCanonical () inline
Definition at line 230 of file edgeFaceCirculatorI.H.
References Foam::abort(), Foam::endl(), f(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), polyMesh::faces(), Foam::FatalError, FatalErrorInFunction, mesh, and polyMesh::points().
Referenced by edgeFaceCirculator::cbegin().
operator=()
void operator= (const edgeFaceCirculator & iter) inline
Definition at line 334 of file edgeFaceCirculatorI.H.
operator==()
bool operator== (const edgeFaceCirculator & iter) const inline
Definition at line 344 of file edgeFaceCirculatorI.H.
operator!=()
bool operator!= (const edgeFaceCirculator & iter) const inline
Definition at line 364 of file edgeFaceCirculatorI.H.
operator++()
Foam::edgeFaceCirculator & operator++ () inline
Definition at line 374 of file edgeFaceCirculatorI.H.
References Foam::abort(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), Foam::FatalError, FatalErrorInFunction, and mesh.
begin()
Foam::edgeFaceCirculator begin () const inline
Definition at line 439 of file edgeFaceCirculatorI.H.
cbegin()
Foam::edgeFaceCirculator cbegin () const inline
Definition at line 420 of file edgeFaceCirculatorI.H.
References edgeFaceCirculator::setCanonical().
end()
const Foam::edgeFaceCirculator end () const inline
Definition at line 444 of file edgeFaceCirculatorI.H.
cend()
const Foam::edgeFaceCirculator cend () const inline
Definition at line 449 of file edgeFaceCirculatorI.H.
The documentation for this class was generated from the following files:
src/meshTools/edgeFaceCirculator/edgeFaceCirculator.H
src/meshTools/edgeFaceCirculator/edgeFaceCirculatorI.H