OpenFOAM: IOobjectOption Class Reference
IOobjectOption Class Reference
A simple container of IOobject preferences. Can also be used for general handling of read/no-read/read-if-present logic outside of an IOobject.
#include <IOobjectOption.H>
Public Types
enum readOption : unsigned char {
NO_READ = 0 , MUST_READ = 0x1 , READ_MODIFIED = 0x3 , MUST_READ_IF_MODIFIED = 0x3 ,
LAZY_READ = 0x4 , READ_IF_PRESENT = 0x4
}
enum writeOption : unsigned char { NO_WRITE = 0 , AUTO_WRITE = 0x10 }
enum registerOption : unsigned char { NO_REGISTER = 0 , REGISTER = 1 }
Public Member Functions
constexpr IOobjectOption (readOption rOpt=readOption::NO_READ, writeOption wOpt=writeOption::NO_WRITE, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (readOption rOpt, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (writeOption wOpt, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (registerOption registerObject, bool globalObject=false) noexcept
constexpr IOobjectOption (readOption rOpt, writeOption wOpt, bool registerObject, bool globalObject=false) noexcept
constexpr IOobjectOption (bool registerObject, bool globalObject=false) noexcept
readOption readOpt () const noexcept
readOption readOpt (readOption opt) noexcept
writeOption writeOpt () const noexcept
writeOption writeOpt (writeOption opt) noexcept
bool registerObject () const noexcept
bool registerObject (bool on) noexcept
bool globalObject () const noexcept
bool globalObject (bool on) noexcept
bool isAnyRead () const noexcept
bool isReadRequired () const noexcept
bool isReadOptional () const noexcept
readOption & readOpt () noexcept
writeOption & writeOpt () noexcept
bool & registerObject () noexcept
bool & globalObject () noexcept
Static Public Member Functions
static bool isAnyRead (readOption opt) noexcept
static bool isReadRequired (readOption opt) noexcept
static bool isReadOptional (readOption opt) noexcept
static readOption lazierRead (readOption opt) noexcept
Detailed Description
A simple container of IOobject preferences. Can also be used for general handling of read/no-read/read-if-present logic outside of an IOobject.
See also
Foam::IOobject
Definition at line 45 of file IOobjectOption.H.
Member Enumeration Documentation
readOption
enum readOption : unsigned char
Enumerator
NO_READ
Nothing to be read.
MUST_READ
Reading required.
READ_MODIFIED
Reading required, file watched for runTime modification [identical to MUST_READ_IF_MODIFIED]
MUST_READ_IF_MODIFIED
Reading required, file watched for runTime modification [identical to READ_MODIFIED]
LAZY_READ
Reading is optional [identical to READ_IF_PRESENT].
READ_IF_PRESENT
Reading is optional [identical to LAZY_READ].
Definition at line 54 of file IOobjectOption.H.
writeOption
enum writeOption : unsigned char
Enumerator
NO_WRITE
Ignore writing from objectRegistry::writeObject()
AUTO_WRITE
Automatically write from objectRegistry::writeObject()
Definition at line 78 of file IOobjectOption.H.
registerOption
enum registerOption : unsigned char
Enumerator
NO_REGISTER
Do not request registration (bool: false)
REGISTER
Request registration (bool: true)
Definition at line 89 of file IOobjectOption.H.
Constructor & Destructor Documentation
IOobjectOption() [1/6]
constexpr IOobjectOption (readOption rOpt = readOption::NO_READ, writeOption wOpt = writeOption::NO_WRITE, registerOption registerObject = registerOption::REGISTER, bool globalObject = false) inline constexpr noexcept
Definition at line 122 of file IOobjectOption.H.
IOobjectOption() [2/6]
constexpr IOobjectOption (readOption rOpt, registerOption registerObject = registerOption::REGISTER, bool globalObject = false) inline constexpr noexcept
Definition at line 137 of file IOobjectOption.H.
IOobjectOption() [3/6]
constexpr IOobjectOption (writeOption wOpt, registerOption registerObject = registerOption::REGISTER, bool globalObject = false) inline constexpr noexcept
Definition at line 151 of file IOobjectOption.H.
IOobjectOption() [4/6]
constexpr IOobjectOption (registerOption registerObject, bool globalObject = false) inline constexpr noexcept
Definition at line 165 of file IOobjectOption.H.
IOobjectOption() [5/6]
constexpr IOobjectOption (readOption rOpt, writeOption wOpt, bool registerObject, bool globalObject = false) inline constexpr noexcept
Definition at line 179 of file IOobjectOption.H.
IOobjectOption() [6/6]
constexpr IOobjectOption (bool registerObject, bool globalObject = false) inline explicit constexpr noexcept
Definition at line 195 of file IOobjectOption.H.
Member Function Documentation
readOpt() [1/3]
readOption readOpt () const inline noexcept
Definition at line 211 of file IOobjectOption.H.
Referenced by columnFvMesh::columnFvMesh(), decomposedBlockData::decomposedBlockData(), topoSet::findIOobject(), hexRef8::hexRef8(), dynamicMotionSolverListFvMesh::init(), IOobject::IOobject(), IOobject::operator=(), radiationModel::radiationModel(), codedPoints0MotionSolver::redirectMotionSolver(), schemesLookup::schemesLookup(), IOobject::selectIO(), SimplifiedDynamicFvMesh< DynamicMeshType >::SimplifiedDynamicFvMesh(), solution::solution(), Time::Time(), Time::Time(), and Time::Time().
readOpt() [2/3]
readOption readOpt (readOption opt) inline noexcept
Definition at line 214 of file IOobjectOption.H.
writeOpt() [1/3]
writeOption writeOpt () const inline noexcept
Definition at line 222 of file IOobjectOption.H.
Referenced by snappyLayerDriver::addLayers(), dynamicMotionSolverListFvMesh::init(), IOobject::IOobject(), objectRegistry::objectRegistry(), IOobject::operator=(), phaseSystem::phaseSystem(), IOobject::selectIO(), and polyMesh::setInstance().
writeOpt() [2/3]
writeOption writeOpt (writeOption opt) inline noexcept
Definition at line 225 of file IOobjectOption.H.
registerObject() [1/3]
bool registerObject () const inline noexcept
Definition at line 233 of file IOobjectOption.H.
Referenced by IOobject::IOobject(), Foam::loadPointField(), regIOobject::regIOobject(), regIOobject::regIOobject(), and IOobject::selectIO().
registerObject() [2/3]
bool registerObject (bool on) inline noexcept
Definition at line 236 of file IOobjectOption.H.
globalObject() [1/3]
bool globalObject () const inline noexcept
Definition at line 244 of file IOobjectOption.H.
Referenced by IOobject::operator=(), and IOobject::selectIO().
globalObject() [2/3]
bool globalObject (bool on) inline noexcept
Definition at line 247 of file IOobjectOption.H.
isAnyRead() [1/2]
static bool isAnyRead (readOption opt) inline static noexcept
Definition at line 258 of file IOobjectOption.H.
References IOobjectOption::NO_READ.
isAnyRead() [2/2]
bool isAnyRead () const inline noexcept
Definition at line 264 of file IOobjectOption.H.
References IOobjectOption::NO_READ.
Referenced by fixedGradientFaPatchField< Type >::readGradientEntry(), fixedGradientFvPatchField< Type >::readGradientEntry(), mixedFaPatchField< Type >::readMixedEntries(), mixedFvPatchField< Type >::readMixedEntries(), faePatchField< Type >::readValueEntry(), faPatchField< Type >::readValueEntry(), fvPatchField< Type >::readValueEntry(), fvsPatchField< Type >::readValueEntry(), and valuePointPatchField< Type >::readValueEntry().
isReadRequired() [1/2]
static bool isReadRequired (readOption opt) inline static noexcept
Definition at line 270 of file IOobjectOption.H.
References IOobjectOption::MUST_READ.
isReadRequired() [2/2]
bool isReadRequired () const inline noexcept
Definition at line 276 of file IOobjectOption.H.
References IOobjectOption::MUST_READ.
Referenced by coordinateSystem::assign(), cellZoneSet::cellZoneSet(), cyclicFaPatchField< Type >::cyclicFaPatchField(), decomposedBlockData::decomposedBlockData(), extendedFeatureEdgeMesh::extendedFeatureEdgeMesh(), faBoundaryMeshEntries::faBoundaryMeshEntries(), faceZoneSet::faceZoneSet(), featureEdgeMesh::featureEdgeMesh(), IOField< Type >::IOField(), IOPtrList< T >::IOPtrList(), IOPtrList< T >::IOPtrList(), lumpedPointIOMovement::lumpedPointIOMovement(), pointZoneSet::pointZoneSet(), polyBoundaryMeshEntries::polyBoundaryMeshEntries(), dictionary::readCheck(), dictionary::readCompat(), dimensionSet::readEntry(), dictionary::readEntry(), fixedGradientFaPatchField< Type >::readGradientEntry(), fixedGradientFvPatchField< Type >::readGradientEntry(), regIOobject::readHeaderOk(), faePatchField< Type >::readValueEntry(), faPatchField< Type >::readValueEntry(), fvPatchField< Type >::readValueEntry(), fvsPatchField< Type >::readValueEntry(), valuePointPatchField< Type >::readValueEntry(), regionProperties::regionProperties(), surfZoneIOList::surfZoneIOList(), topoSet::topoSet(), and topoSet::topoSet().
isReadOptional() [1/2]
static bool isReadOptional (readOption opt) inline static noexcept
Definition at line 282 of file IOobjectOption.H.
References IOobjectOption::LAZY_READ.
isReadOptional() [2/2]
bool isReadOptional () const inline noexcept
Definition at line 288 of file IOobjectOption.H.
References IOobjectOption::LAZY_READ.
Referenced by cellZoneSet::cellZoneSet(), decomposedBlockData::decomposedBlockData(), extendedFeatureEdgeMesh::extendedFeatureEdgeMesh(), faBoundaryMeshEntries::faBoundaryMeshEntries(), faceZoneSet::faceZoneSet(), featureEdgeMesh::featureEdgeMesh(), Field< T >::Field(), IOPtrList< T >::IOPtrList(), IOPtrList< T >::IOPtrList(), pointZoneSet::pointZoneSet(), polyBoundaryMeshEntries::polyBoundaryMeshEntries(), regIOobject::readHeaderOk(), mixedFaPatchField< Type >::readMixedEntries(), mixedFvPatchField< Type >::readMixedEntries(), schemesLookup::schemesLookup(), solution::solution(), topoSet::topoSet(), and topoSet::topoSet().
lazierRead()
static readOption lazierRead (readOption opt) inline static noexcept
Definition at line 294 of file IOobjectOption.H.
References IOobjectOption::LAZY_READ, and IOobjectOption::NO_READ.
Referenced by coordinateSystem::assign(), and coordinateSystem::coordinateSystem().
readOpt() [3/3]
readOption & readOpt () inline noexcept
Definition at line 304 of file IOobjectOption.H.
writeOpt() [3/3]
writeOption & writeOpt () inline noexcept
Definition at line 308 of file IOobjectOption.H.
registerObject() [3/3]
bool & registerObject () inline noexcept
Definition at line 312 of file IOobjectOption.H.
globalObject() [3/3]
bool & globalObject () inline noexcept
Definition at line 316 of file IOobjectOption.H.
The documentation for this class was generated from the following file:
src/OpenFOAM/db/options/IOobjectOption.H