OpenFOAM: seriesWriter Class Reference
seriesWriter Class Reference
Provides a means of accumulating and generating VTK file series.
#include <foamVtkSeriesWriter.H>
Public Member Functions
seriesWriter ()=default
seriesWriter (const seriesWriter &)=default
seriesWriter (seriesWriter &&)=default
seriesWriter & operator= (const seriesWriter &)=default
seriesWriter & operator= (seriesWriter &&)=default
~seriesWriter ()=default
bool empty () const noexcept
label size () const noexcept
void clear ()
bool append (const fileNameInstant &inst)
bool append (fileNameInstant &&inst)
bool append (scalar timeValue, const fileName &file)
bool append (scalar timeValue, fileName &&file)
label load (const fileName &seriesName, const bool checkFiles=false, const scalar restartTime=ROOTVGREAT)
label scan (const fileName &seriesName, const scalar restartTime=ROOTVGREAT)
bool removeNewer (const scalar timeValue)
void sort ()
void print (Ostream &os) const
void write (const fileName &seriesName) const
Static Public Member Functions
static fileName base (const fileName &outputName, char sep='_')
static word suffix (const fileName &file, char sep='_')
static Ostream & print (Ostream &os, const fileName &seriesName, const UList< instant > &series, const char sep='_')
static void write (const fileName &base, const UList< instant > &series, const char sep='_')
static Ostream & print (Ostream &os, const UList< fileNameInstant > &series)
static void write (const fileName &seriesName, const UList< fileNameInstant > &series)
Detailed Description
Provides a means of accumulating and generating VTK file series.
The VTK file series format is a simple JSON format with the following type of content:
{
  "file-series-version" : "1.0",
  "files": [
    { "name" : "file1.vtk", "time" : 10 },
    { "name" : "file2.vtk", "time" : 20 },
    { "name" : "file3.vtk", "time" : 30 },
  ]
}
The append() operations include various sanity checks. Entries with an empty name are ignored. If an entry with an identical name already exists, its place will be overwritten with the new time value.
Source files
foamVtkSeriesWriter.H
foamVtkSeriesWriter.C
Definition at line 71 of file foamVtkSeriesWriter.H.
Constructor & Destructor Documentation
seriesWriter() [1/3]
seriesWriter () default
seriesWriter() [2/3]
seriesWriter (const seriesWriter &) default
seriesWriter() [3/3]
seriesWriter (seriesWriter &&) default
~seriesWriter()
~seriesWriter () default
Member Function Documentation
operator=() [1/2]
seriesWriter & operator= (const seriesWriter &) default
operator=() [2/2]
seriesWriter & operator= (seriesWriter &&) default
base()
Foam::fileName base (const fileName & outputName, char sep = '_') static
Definition at line 83 of file foamVtkSeriesWriter.C.
References Foam::dot(), and outputName().
Referenced by vtkCloud::write(), and vtkWrite::write().
suffix()
Foam::word suffix (const fileName & file, char sep = '_') static
Definition at line 113 of file foamVtkSeriesWriter.C.
References Foam::dot().
print() [1/3]
Foam::Ostream & print (Ostream & os, const fileName & seriesName, const UList< instant > & series, const char sep = '_') static
Definition at line 143 of file foamVtkSeriesWriter.C.
References fileName::ext(), Foam::nl, os(), UPtrList< T >::size(), and fileName::stem().
Referenced by seriesWriter::print().
write() [1/3]
void write (const fileName & base, const UList< instant > & series, const char sep = '_') static
Definition at line 225 of file foamVtkSeriesWriter.C.
References Foam::mkDir(), and autoPtr< T >::New().
Referenced by seriesWriter::write().
print() [2/3]
Foam::Ostream & print (Ostream & os, const UList< fileNameInstant > & series) static
Definition at line 190 of file foamVtkSeriesWriter.C.
References Foam::nl, os(), and UPtrList< T >::size().
write() [2/3]
void write (const fileName & seriesName, const UList< fileNameInstant > & series) static
Definition at line 246 of file foamVtkSeriesWriter.C.
References Foam::mkDir(), and autoPtr< T >::New().
empty()
bool empty () const inline noexcept
Definition at line 23 of file foamVtkSeriesWriterI.H.
References UPtrList< T >::empty().
size()
Foam::label size () const inline noexcept
Definition at line 29 of file foamVtkSeriesWriterI.H.
References UPtrList< T >::size().
clear()
void clear () inline
Definition at line 35 of file foamVtkSeriesWriterI.H.
References PtrList< T >::clear().
append() [1/4]
bool append (const fileNameInstant & inst) inline
Definition at line 42 of file foamVtkSeriesWriterI.H.
append() [2/4]
bool append (fileNameInstant && inst) inline
Definition at line 49 of file foamVtkSeriesWriterI.H.
append() [3/4]
bool append (scalar timeValue, const fileName & file) inline
Definition at line 58 of file foamVtkSeriesWriterI.H.
References fileName::name().
append() [4/4]
bool append (scalar timeValue, fileName && file) inline
Definition at line 69 of file foamVtkSeriesWriterI.H.
load()
Foam::label load (const fileName & seriesName, const bool checkFiles = false, const scalar restartTime = ROOTVGREAT)
Definition at line 358 of file foamVtkSeriesWriter.C.
References token::BEGIN_BLOCK, token::BEGIN_SQR, clear(), token::COMMA, token::END_BLOCK, token::END_SQR, Foam::getToken(), Foam::getValueToken(), Foam::isFile(), Foam::lessThan(), and Foam::readDir().
scan()
Foam::label scan (const fileName & seriesName, const scalar restartTime = ROOTVGREAT)
Definition at line 576 of file foamVtkSeriesWriter.C.
References append(), clear(), Foam::Info, Foam::isDir(), Foam::lessThan(), Foam::nl, path(), Foam::readDir(), PtrList< T >::resize(), Foam::sort(), and Foam::subsetList().
removeNewer()
bool removeNewer (const scalar timeValue)
Definition at line 708 of file foamVtkSeriesWriter.C.
References PtrList< T >::clear(), UPtrList< T >::empty(), Foam::lessThan(), Instant< T >::name(), Foam::name(), PtrList< T >::resize(), UPtrList< T >::size(), and Instant< T >::value().
sort()
void sort ()
Definition at line 738 of file foamVtkSeriesWriter.C.
References Foam::sort().
print() [3/3]
void print (Ostream & os) const inline
Definition at line 82 of file foamVtkSeriesWriterI.H.
References os(), and seriesWriter::print().
write() [3/3]
void write (const fileName & seriesName) const inline
Definition at line 88 of file foamVtkSeriesWriterI.H.
References seriesWriter::write().
The documentation for this class was generated from the following files:
src/fileFormats/vtk/file/foamVtkSeriesWriter.H
src/fileFormats/vtk/file/foamVtkSeriesWriter.C
src/fileFormats/vtk/file/foamVtkSeriesWriterI.H