OpenFOAM: mapPatchChange Class Reference
mapPatchChange Class Reference
Class containing mesh-to-mesh mapping information after a patch change operation.
#include <mapPatchChange.H>
Public Member Functions
mapPatchChange (const label nOldPatches, const labelList &patchMap)
label nOldPatches () const
const labelList & patchMap () const
labelList addedPatches () const
labelList deletedPatches () const
Detailed Description
Class containing mesh-to-mesh mapping information after a patch change operation.
Source files
mapPatchChange.H
Definition at line 46 of file mapPatchChange.H.
Constructor & Destructor Documentation
mapPatchChange()
mapPatchChange (const label nOldPatches, const labelList & patchMap) inline
Definition at line 61 of file mapPatchChange.H.
Member Function Documentation
nOldPatches()
label nOldPatches () const inline
Definition at line 73 of file mapPatchChange.H.
patchMap()
const labelList & patchMap () const inline
Definition at line 82 of file mapPatchChange.H.
addedPatches()
labelList addedPatches () const inline
Definition at line 91 of file mapPatchChange.H.
References forAll, PtrList< T >::setSize(), and UList< T >::size().
deletedPatches()
labelList deletedPatches () const inline
Definition at line 109 of file mapPatchChange.H.
References forAll, and PtrList< T >::setSize().
The documentation for this class was generated from the following file:
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/mapPatchChange/mapPatchChange.H