OpenFOAM: UPtrList< T >::iterator Class Reference
UPtrList< T >::iterator Class Reference
#include <UPtrList.H>
Public Types
using pointer = T *
using reference = T &
Public Types inherited from UPtrList< T >::Iterator< Const >
using list_type = typename std::conditional< Const, const UPtrList< T >, UPtrList< T > >::type
Public Member Functions
constexpr iterator () noexcept=default
iterator (const Iterator< false > &iter)
pointer get () const
reference val () const
pointer operator-> () const
reference operator* () const
reference operator() () const
iterator & operator++ ()
iterator operator++ (int)
Public Member Functions inherited from UPtrList< T >::Iterator< Const >
bool good () const noexcept
label key () const noexcept
template<bool Any>
bool operator== (const Iterator< Any > &iter) const noexcept
template<bool Any>
bool operator!= (const Iterator< Any > &iter) const noexcept
Additional Inherited Members
Protected Member Functions inherited from UPtrList< T >::Iterator< Const >
constexpr Iterator () noexcept
Iterator (list_type *list)
void increment ()
template<bool Any>
operator const Iterator< Any > & () const
Protected Attributes inherited from UPtrList< T >::Iterator< Const >
list_type * list_
label pos_
Detailed Description
template<class T>
class Foam::UPtrList< T >::iterator
Definition at line 480 of file UPtrList.H.
Member Typedef Documentation
pointer
template<class T > using pointer = T*
Definition at line 485 of file UPtrList.H.
reference
template<class T > using reference = T&
Definition at line 486 of file UPtrList.H.
Constructor & Destructor Documentation
iterator() [1/2]
template<class T > constexpr iterator () constexpr default noexcept
iterator() [2/2]
template<class T > iterator (const Iterator< false > & iter) inline explicit
Definition at line 495 of file UPtrList.H.
Member Function Documentation
get()
template<class T > T * get () const inline
Definition at line 338 of file UPtrListI.H.
Referenced by UPtrList< T >::iterator::operator->().
val()
template<class T > T & val () const inline
Definition at line 345 of file UPtrListI.H.
References UPtrList< T >::at().
Referenced by UPtrList< T >::iterator::operator()(), UPtrList< T >::iterator::operator*(), and cuttingSurfaceBase::walkCellCuts().
operator->()
template<class T > pointer operator-> () const inline
Definition at line 510 of file UPtrList.H.
References UPtrList< T >::iterator::get().
operator*()
template<class T > reference operator* () const inline
Definition at line 513 of file UPtrList.H.
References UPtrList< T >::iterator::val().
operator()()
template<class T > reference operator() () const inline
Definition at line 516 of file UPtrList.H.
References UPtrList< T >::iterator::val().
operator++() [1/2]
template<class T > Foam::UPtrList< T >::iterator & operator++ () inline
Definition at line 353 of file UPtrListI.H.
operator++() [2/2]
template<class T > Foam::UPtrList< T >::iterator operator++ (int) inline
Definition at line 362 of file UPtrListI.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/PtrLists/UPtrList/UPtrList.H
src/OpenFOAM/containers/PtrLists/UPtrList/UPtrListI.H