OpenFOAM: rigidBodyInertia Class Reference
rigidBodyInertia Class Reference
#include <rigidBodyInertia.H>
Public Member Functions
rigidBodyInertia ()
rigidBodyInertia (const scalar m, const vector &c, const symmTensor &Ic)
rigidBodyInertia (const dictionary &dict)
rigidBodyInertia (const spatialTensor &st)
rigidBodyInertia (Istream &is)
scalar m () const
const vector & c () const
const symmTensor & Ic () const
symmTensor Ioc () const
symmTensor Icc (const vector &c) const
symmTensor Io () const
scalar kineticEnergy (const spatialVector &v)
operator spatialTensor () const
void operator+= (const rigidBodyInertia &)
Static Public Member Functions
static symmTensor Ioc (const scalar m, const vector &c)
Friends
Istream & operator>> (Istream &, rigidBodyInertia &)
Ostream & operator<< (Ostream &, const rigidBodyInertia &)
Detailed Description
Definition at line 68 of file rigidBodyInertia.H.
Constructor & Destructor Documentation
rigidBodyInertia() [1/5]
rigidBodyInertia () inline
Definition at line 40 of file rigidBodyInertiaI.H.
rigidBodyInertia() [2/5]
rigidBodyInertia (const scalar m, const vector & c, const symmTensor & Ic) inline
Definition at line 48 of file rigidBodyInertiaI.H.
rigidBodyInertia() [3/5]
rigidBodyInertia (const dictionary & dict) inline
Definition at line 61 of file rigidBodyInertiaI.H.
rigidBodyInertia() [4/5]
rigidBodyInertia (const spatialTensor & st) inline explicit
Definition at line 69 of file rigidBodyInertiaI.H.
rigidBodyInertia() [5/5]
rigidBodyInertia (Istream & is) inline explicit
Definition at line 77 of file rigidBodyInertiaI.H.
Member Function Documentation
Ioc() [1/2]
Foam::symmTensor Ioc (const scalar m, const vector & c) inline static
Definition at line 28 of file rigidBodyInertiaI.H.
References rigidBodyInertia::c(), Foam::I, rigidBodyInertia::m(), Foam::magSqr(), and Foam::sqr().
m()
Foam::scalar m () const inline
Definition at line 87 of file rigidBodyInertiaI.H.
Referenced by cuboid::cuboid(), rigidBodyInertia::Ioc(), sphere::sphere(), and Foam::RBD::transform().
c()
const Foam::vector & c () const inline
Definition at line 92 of file rigidBodyInertiaI.H.
Referenced by cuboid::cuboid(), rigidBodyInertia::Ioc(), sphere::sphere(), and Foam::RBD::transform().
Ic()
const Foam::symmTensor & Ic () const inline
Definition at line 97 of file rigidBodyInertiaI.H.
Referenced by Foam::RBD::transform().
Ioc() [2/2]
Foam::symmTensor Ioc () const inline
Definition at line 102 of file rigidBodyInertiaI.H.
Icc()
Foam::symmTensor Icc (const vector & c) const inline
Definition at line 107 of file rigidBodyInertiaI.H.
Io()
Foam::symmTensor Io () const inline
Definition at line 112 of file rigidBodyInertiaI.H.
kineticEnergy()
Foam::scalar kineticEnergy (const spatialVector & v) inline
Definition at line 234 of file rigidBodyInertiaI.H.
operator spatialTensor()
operator spatialTensor () const inline
Definition at line 120 of file rigidBodyInertiaI.H.
References Foam::I.
operator+=()
void operator+= (const rigidBodyInertia & rbi) inline
Definition at line 245 of file rigidBodyInertiaI.H.
Friends And Related Symbol Documentation
operator>>
Istream & operator>> (Istream & , rigidBodyInertia &) friend
operator<<
Ostream & operator<< (Ostream & , const rigidBodyInertia &) friend
The documentation for this class was generated from the following files:
src/rigidBodyDynamics/rigidBodyInertia/rigidBodyInertia.H
src/rigidBodyDynamics/rigidBodyInertia/rigidBodyInertiaI.H