OpenFOAM: advancingFrontAMI Class Reference
advancingFrontAMI Class Reference
Base class for Arbitrary Mesh Interface (AMI) methods.
#include <advancingFrontAMI.H>
Public Types
enum class areaNormalisationMode { project , mag }
Public Member Functions
TypeName ("advancingFrontAMI")
advancingFrontAMI (const dictionary &dict, const bool reverseTarget)
advancingFrontAMI (const bool requireMatch=true, const bool reverseTarget=false, const scalar lowWeightCorrection=-1, const faceAreaIntersect::triangulationMode triMode=faceAreaIntersect::tmMesh)
advancingFrontAMI (const advancingFrontAMI &ami)
virtual autoPtr< AMIInterpolation > clone () const
virtual ~advancingFrontAMI ()=default
const primitivePatch & srcPatch () const
const primitivePatch & tgtPatch () const
const labelList & srcNonOverlap () const
virtual void write (Ostream &os) const
Public Member Functions inherited from AMIInterpolation
TypeName ("AMIInterpolation")
declareRunTimeSelectionTable (autoPtr, AMIInterpolation, dict,(const dictionary &dict, const bool reverseTarget),(dict, reverseTarget))
declareRunTimeSelectionTable (autoPtr, AMIInterpolation, component,(const bool requireMatch, const bool reverseTarget, const scalar lowWeightCorrection),(requireMatch, reverseTarget, lowWeightCorrection))
AMIInterpolation (const dictionary &dict, const bool reverseTarget=false)
AMIInterpolation (const bool requireMatch=true, const bool reverseTarget=false, const scalar lowWeightCorrection=-1)
AMIInterpolation (const AMIInterpolation &fineAMI, const labelList &sourceRestrictAddressing, const labelList &neighbourRestrictAddressing)
AMIInterpolation (const AMIInterpolation &ami)
virtual ~AMIInterpolation ()=default
bool upToDate () const noexcept
bool upToDate (bool flag) noexcept
bool upToDate () noexcept
bool distributed () const
bool requireMatch () const
bool setRequireMatch (const bool flag)
bool mustMatchFaces () const
bool reverseTarget () const
scalar lowWeightCorrection () const
bool applyLowWeightCorrection () const
label singlePatchProc () const
const List< scalar > & srcMagSf () const
List< scalar > & srcMagSf ()
const labelListList & srcAddress () const
labelListList & srcAddress ()
const scalarListList & srcWeights () const
scalarListList & srcWeights ()
const scalarField & srcWeightsSum () const
scalarField & srcWeightsSum ()
const pointListList & srcCentroids () const
pointListList & srcCentroids ()
const mapDistribute & srcMap () const
const List< scalar > & tgtMagSf () const
List< scalar > & tgtMagSf ()
const labelListList & tgtAddress () const
labelListList & tgtAddress ()
const scalarListList & tgtWeights () const
scalarListList & tgtWeights ()
const scalarField & tgtWeightsSum () const
scalarField & tgtWeightsSum ()
const mapDistribute & tgtMap () const
void reset (autoPtr< mapDistribute > &&srcToTgtMap, autoPtr< mapDistribute > &&tgtToSrcMap, labelListList &&srcAddress, scalarListList &&srcWeights, labelListList &&tgtAddress, scalarListList &&tgtWeights)
void append (const primitivePatch &srcPatch, const primitivePatch &tgtPatch)
void normaliseWeights (const bool conformal, const bool output)
template<class Type , class CombineOp >
void interpolateToSource (const UList< Type > &fld, const CombineOp &cop, List< Type > &result, const UList< Type > &defaultValues=UList< Type >::null()) const
template<class Type , class CombineOp >
void interpolateToTarget (const UList< Type > &fld, const CombineOp &cop, List< Type > &result, const UList< Type > &defaultValues=UList< Type >::null()) const
template<class Type , class CombineOp >
tmp< Field< Type > > interpolateToSource (const Field< Type > &fld, const CombineOp &cop, const UList< Type > &defaultValues=UList< Type >::null()) const
template<class Type , class CombineOp >
tmp< Field< Type > > interpolateToSource (const tmp< Field< Type > > &tFld, const CombineOp &cop, const UList< Type > &defaultValues=UList< Type >::null()) const
template<class Type , class CombineOp >
tmp< Field< Type > > interpolateToTarget (const Field< Type > &fld, const CombineOp &cop, const UList< Type > &defaultValues=UList< Type >::null()) const
template<class Type , class CombineOp >
tmp< Field< Type > > interpolateToTarget (const tmp< Field< Type > > &tFld, const CombineOp &cop, const UList< Type > &defaultValues=UList< Type >::null()) const
template<class Type >
tmp< Field< Type > > interpolateToSource (const Field< Type > &fld, const UList< Type > &defaultValues=UList< Type >::null()) const
template<class Type >
tmp< Field< Type > > interpolateToSource (const tmp< Field< Type > > &tFld, const UList< Type > &defaultValues=UList< Type >::null()) const
template<class Type >
tmp< Field< Type > > interpolateToTarget (const Field< Type > &fld, const UList< Type > &defaultValues=UList< Type >::null()) const
template<class Type >
tmp< Field< Type > > interpolateToTarget (const tmp< Field< Type > > &tFld, const UList< Type > &defaultValues=UList< Type >::null()) const
label srcPointFace (const primitivePatch &srcPatch, const primitivePatch &tgtPatch, const vector &n, const label tgtFacei, point &tgtPoint) const
label tgtPointFace (const primitivePatch &srcPatch, const primitivePatch &tgtPatch, const vector &n, const label srcFacei, point &srcPoint) const
bool checkSymmetricWeights (const bool log) const
void writeFaceConnectivity (const primitivePatch &srcPatch, const primitivePatch &tgtPatch, const labelListList &srcAddress) const
template<class Type , class CombineOp >
Foam::tmp< Foam::Field< Type > > interpolateToSource (const Field< Type > &fld, const CombineOp &cop, const UList< Type > &defaultValues) const
template<class Type , class CombineOp >
Foam::tmp< Foam::Field< Type > > interpolateToSource (const tmp< Field< Type > > &tFld, const CombineOp &cop, const UList< Type > &defaultValues) const
template<class Type , class CombineOp >
Foam::tmp< Foam::Field< Type > > interpolateToTarget (const Field< Type > &fld, const CombineOp &cop, const UList< Type > &defaultValues) const
template<class Type , class CombineOp >
Foam::tmp< Foam::Field< Type > > interpolateToTarget (const tmp< Field< Type > > &tFld, const CombineOp &cop, const UList< Type > &defaultValues) const
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolateToSource (const Field< Type > &fld, const UList< Type > &defaultValues) const
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolateToSource (const tmp< Field< Type > > &tFld, const UList< Type > &defaultValues) const
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolateToTarget (const Field< Type > &fld, const UList< Type > &defaultValues) const
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolateToTarget (const tmp< Field< Type > > &tFld, const UList< Type > &defaultValues) const
Static Public Attributes
static const Enum< areaNormalisationMode > areaNormalisationModeNames_
Static Public Attributes inherited from AMIInterpolation
static bool cacheIntersections_ = false
Protected Member Functions
void createExtendedTgtPatch ()
void checkPatches () const
bool isCandidate (const label srcFacei, const label tgtFacei) const
virtual bool calculate (const primitivePatch &srcPatch, const primitivePatch &tgtPatch, const autoPtr< searchableSurface > &surfPtr=nullptr)
bool initialiseWalk (label &srcFacei, label &tgtFacei)
void writeIntersectionOBJ (const scalar area, const face &f1, const face &f2, const pointField &f1Points, const pointField &f2Points) const
label findTargetFace (const label srcFacei, const UList< label > &excludeFaces=UList< label >::null(), const label srcFacePti=-1) const
void appendNbrFaces (const label facei, const primitivePatch &patch, const DynamicList< label > &visitedFaces, DynamicList< label > &faceIDs) const
void triangulatePatch (const primitivePatch &patch, List< DynamicList< face > > &tris, List< scalar > &magSf) const
virtual void nonConformalCorrection ()
Protected Member Functions inherited from AMIInterpolation
void operator= (const AMIInterpolation &)=delete
autoPtr< indexedOctree< treeType > > createTree (const primitivePatch &patch) const
label calcDistribution (const primitivePatch &srcPatch, const primitivePatch &tgtPatch) const
void projectPointsToSurface (const searchableSurface &surf, pointField &pts) const
const primitivePatch & srcPatch0 () const
const primitivePatch & tgtPatch0 () const
Protected Attributes
const scalar maxDistance2_
const scalar minCosAngle_
List< DynamicList< face > > srcTris_
List< DynamicList< face > > tgtTris_
autoPtr< primitivePatch > extendedTgtPatchPtr_
faceList extendedTgtFaces_
pointField extendedTgtPoints_
labelList extendedTgtFaceIDs_
autoPtr< mapDistribute > extendedTgtMapPtr_
labelList srcNonOverlap_
autoPtr< indexedOctree< treeType > > treePtr_
const faceAreaIntersect::triangulationMode triMode_
areaNormalisationMode areaNormalisationMode_
Protected Attributes inherited from AMIInterpolation
bool requireMatch_
const bool reverseTarget_
const scalar lowWeightCorrection_
label singlePatchProc_
scalarList srcMagSf_
labelListList srcAddress_
scalarListList srcWeights_
scalarField srcWeightsSum_
pointListList srcCentroids_
pointField srcPatchPts_
refPtr< primitivePatch > tsrcPatch0_
autoPtr< mapDistribute > srcMapPtr_
scalarList tgtMagSf_
labelListList tgtAddress_
scalarListList tgtWeights_
scalarField tgtWeightsSum_
pointListList tgtCentroids_
pointField tgtPatchPts_
refPtr< primitivePatch > ttgtPatch0_
autoPtr< mapDistribute > tgtMapPtr_
bool upToDate_
Additional Inherited Members
Static Public Member Functions inherited from AMIInterpolation
static autoPtr< AMIInterpolation > New (const word &modelName, const dictionary &dict, const bool reverseTarget=false)
static autoPtr< AMIInterpolation > New (const word &modelName, const bool requireMatch=true, const bool reverseTarget=false, const scalar lowWeightCorrection=-1)
Protected Types inherited from AMIInterpolation
typedef treeDataPrimitivePatch< primitivePatch > treeType
Static Protected Member Functions inherited from AMIInterpolation
static void normaliseWeights (const scalarList &patchAreas, const word &patchName, const labelListList &addr, scalarListList &wght, scalarField &wghtSum, const bool conformal, const bool output, const scalar lowWeightTol)
static void agglomerate (const autoPtr< mapDistribute > &targetMap, const scalarList &fineSrcMagSf, const labelListList &fineSrcAddress, const scalarListList &fineSrcWeights, const labelList &sourceRestrictAddressing, const labelList &targetRestrictAddressing, scalarList &srcMagSf, labelListList &srcAddress, scalarListList &srcWeights, scalarField &srcWeightsSum, autoPtr< mapDistribute > &tgtMap)
Detailed Description
Base class for Arbitrary Mesh Interface (AMI) methods.
Source files
advancingFrontAMI.H
advancingFrontAMI.C
Definition at line 51 of file advancingFrontAMI.H.
Member Enumeration Documentation
areaNormalisationMode
enum class areaNormalisationMode strong
Enumerator
project
mag
Definition at line 58 of file advancingFrontAMI.H.
Constructor & Destructor Documentation
advancingFrontAMI() [1/3]
advancingFrontAMI (const dictionary & dict, const bool reverseTarget)
Definition at line 448 of file advancingFrontAMI.C.
References advancingFrontAMI::areaNormalisationMode_, advancingFrontAMI::areaNormalisationModeNames_, DebugInfo, Foam::endl(), advancingFrontAMI::maxDistance2_, advancingFrontAMI::minCosAngle_, faceAreaIntersect::triangulationModeNames_, and advancingFrontAMI::triMode_.
advancingFrontAMI() [2/3]
advancingFrontAMI (const bool requireMatch = true, const bool reverseTarget = false, const scalar lowWeightCorrection = -1, const faceAreaIntersect::triangulationMode triMode = faceAreaIntersect::tmMesh)
Definition at line 494 of file advancingFrontAMI.C.
advancingFrontAMI() [3/3]
advancingFrontAMI (const advancingFrontAMI & ami)
Definition at line 518 of file advancingFrontAMI.C.
~advancingFrontAMI()
virtual ~advancingFrontAMI () virtual default
Member Function Documentation
createExtendedTgtPatch()
void createExtendedTgtPatch () protected
Definition at line 136 of file advancingFrontAMI.C.
checkPatches()
void checkPatches () const protected
Definition at line 46 of file advancingFrontAMI.C.
References Foam::endl(), Foam::nl, Foam::Pout, AMIInterpolation::requireMatch_, advancingFrontAMI::srcPatch(), advancingFrontAMI::tgtPatch(), and WarningInFunction.
isCandidate()
bool isCandidate (const label srcFacei, const label tgtFacei) const protected
Definition at line 85 of file advancingFrontAMI.C.
References Foam::sqr().
calculate()
bool calculate (const primitivePatch & srcPatch, const primitivePatch & tgtPatch, const autoPtr< searchableSurface > & surfPtr = nullptr) protected virtual
Reimplemented from AMIInterpolation.
Reimplemented in faceAreaWeightAMI, and faceAreaWeightAMI2D.
Definition at line 538 of file advancingFrontAMI.C.
References AMIInterpolation::calculate().
Referenced by faceAreaWeightAMI::calculate(), and faceAreaWeightAMI2D::calculate().
initialiseWalk()
bool initialiseWalk (label & srcFacei, label & tgtFacei) protected
Definition at line 170 of file advancingFrontAMI.C.
References Foam::abort(), Foam::createTree(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::Pout, UPtrList< T >::size(), and WarningInFunction.
writeIntersectionOBJ()
void writeIntersectionOBJ (const scalar area, const face & f1, const face & f2, const pointField & f1Points, const pointField & f2Points) const protected
Definition at line 231 of file advancingFrontAMI.C.
References Foam::endl(), forAll, n, Foam::name(), Foam::nl, os(), face::points(), Foam::Pout, UPtrList< T >::size(), and Foam::meshTools::writeOBJ().
findTargetFace()
Foam::label findTargetFace (const label srcFacei, const UList< label > & excludeFaces = UList<label>::null(), const label srcFacePti = -1) const protected
Definition at line 282 of file advancingFrontAMI.C.
References boundBox::centre(), Foam::endl(), boundBox::magSqr(), and Foam::Pout.
appendNbrFaces()
void appendNbrFaces (const label facei, const primitivePatch & patch, const DynamicList< label > & visitedFaces, DynamicList< label > & faceIDs) const protected
Definition at line 322 of file advancingFrontAMI.C.
References PtrList< T >::append(), Foam::cos(), and Foam::degToRad().
triangulatePatch()
void triangulatePatch (const primitivePatch & patch, List< DynamicList< face > > & tris, List< scalar > & magSf) const protected
Definition at line 354 of file advancingFrontAMI.C.
References PtrList< T >::clear(), f(), forAll, points, PtrList< T >::setSize(), UPtrList< T >::size(), faceAreaIntersect::tmFan, faceAreaIntersect::tmMesh, and faceAreaIntersect::triangleFan().
nonConformalCorrection()
void nonConformalCorrection () protected virtual
Definition at line 425 of file advancingFrontAMI.C.
TypeName()
TypeName ("advancingFrontAMI")
clone()
virtual autoPtr< AMIInterpolation > clone () const inline virtual
Reimplemented from AMIInterpolation.
Reimplemented in faceAreaWeightAMI, and faceAreaWeightAMI2D.
Definition at line 253 of file advancingFrontAMI.H.
srcPatch()
const Foam::primitivePatch & srcPatch () const inline
Definition at line 21 of file advancingFrontAMII.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and AMIInterpolation::tsrcPatch0_.
Referenced by advancingFrontAMI::checkPatches(), and faceAreaWeightAMI2D::writeNoMatch().
tgtPatch()
const Foam::primitivePatch & tgtPatch () const inline
Definition at line 34 of file advancingFrontAMII.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Referenced by advancingFrontAMI::checkPatches(), and faceAreaWeightAMI2D::writeNoMatch().
srcNonOverlap()
const Foam::labelList & srcNonOverlap () const inline
Definition at line 52 of file advancingFrontAMII.H.
write()
void write (Ostream & os) const virtual
Reimplemented from AMIInterpolation.
Reimplemented in faceAreaWeightAMI, and faceAreaWeightAMI2D.
Definition at line 599 of file advancingFrontAMI.C.
References os(), faceAreaIntersect::tmMesh, faceAreaIntersect::triangulationModeNames_, AMIInterpolation::write(), and Ostream::writeEntryIfDifferent().
Referenced by faceAreaWeightAMI::write(), and faceAreaWeightAMI2D::write().
Member Data Documentation
areaNormalisationModeNames_
const Foam::Enum< Foam::advancingFrontAMI::areaNormalisationMode > areaNormalisationModeNames_ static
Initial value:
{
    { areaNormalisationMode::project, "project" },
    { areaNormalisationMode::mag, "mag" },
}
Definition at line 38 of file advancingFrontAMI.H.
Referenced by advancingFrontAMI::advancingFrontAMI().
maxDistance2_
const scalar maxDistance2_ protected
Definition at line 116 of file advancingFrontAMI.H.
Referenced by advancingFrontAMI::advancingFrontAMI().
minCosAngle_
const scalar minCosAngle_ protected
Definition at line 119 of file advancingFrontAMI.H.
Referenced by advancingFrontAMI::advancingFrontAMI().
srcTris_
List<DynamicList<face> > srcTris_ protected
Definition at line 122 of file advancingFrontAMI.H.
tgtTris_
List<DynamicList<face> > tgtTris_ protected
Definition at line 125 of file advancingFrontAMI.H.
extendedTgtPatchPtr_
autoPtr<primitivePatch> extendedTgtPatchPtr_ protected
Definition at line 128 of file advancingFrontAMI.H.
extendedTgtFaces_
faceList extendedTgtFaces_ protected
Definition at line 131 of file advancingFrontAMI.H.
extendedTgtPoints_
pointField extendedTgtPoints_ protected
Definition at line 134 of file advancingFrontAMI.H.
extendedTgtFaceIDs_
labelList extendedTgtFaceIDs_ protected
Definition at line 137 of file advancingFrontAMI.H.
extendedTgtMapPtr_
autoPtr<mapDistribute> extendedTgtMapPtr_ protected
Definition at line 140 of file advancingFrontAMI.H.
srcNonOverlap_
labelList srcNonOverlap_ protected
Definition at line 144 of file advancingFrontAMI.H.
Referenced by faceAreaWeightAMI::calcAddressing().
treePtr_
autoPtr<indexedOctree<treeType> > treePtr_ protected
Definition at line 147 of file advancingFrontAMI.H.
triMode_
const faceAreaIntersect::triangulationMode triMode_ protected
Definition at line 150 of file advancingFrontAMI.H.
Referenced by advancingFrontAMI::advancingFrontAMI().
areaNormalisationMode_
areaNormalisationMode areaNormalisationMode_ protected
Definition at line 153 of file advancingFrontAMI.H.
Referenced by advancingFrontAMI::advancingFrontAMI().
The documentation for this class was generated from the following files:
src/meshTools/AMIInterpolation/AMIInterpolation/advancingFrontAMI/advancingFrontAMI.H
src/meshTools/AMIInterpolation/AMIInterpolation/advancingFrontAMI/advancingFrontAMI.C
src/meshTools/AMIInterpolation/AMIInterpolation/advancingFrontAMI/advancingFrontAMII.H
src/meshTools/AMIInterpolation/AMIInterpolation/advancingFrontAMI/advancingFrontAMIParallelOps.C