OpenFOAM: Vector2D< Cmpt > Class Template Reference
Vector2D< Cmpt > Class Template Reference
Templated 2D Vector derived from VectorSpace adding construction from 2 components, element access using x() and y() member functions and the inner-product (dot-product).
#include <Vector2D.H>
Public Types
enum components { X , Y }
typedef Vector2D< label > labelType
Public Types inherited from VectorSpace< Vector2D< Cmpt >, Cmpt, 2 >
typedef VectorSpace< Vector2D< Cmpt >, Cmpt, Ncmpts > vsType
typedef Cmpt cmptType
typedef Cmpt magType
typedef Cmpt * iterator
typedef const Cmpt * const_iterator
Public Member Functions
Vector2D ()=default
Vector2D (const Vector2D &)=default
Vector2D & operator= (const Vector2D &)=default
Vector2D (const Foam::zero)
Vector2D (const VectorSpace< Vector2D< Cmpt >, Cmpt, 2 > &vs)
Vector2D (const Cmpt &vx, const Cmpt &vy)
Vector2D (Istream &is)
const Cmpt & x () const noexcept
const Cmpt & y () const noexcept
Cmpt & x () noexcept
Cmpt & y () noexcept
scalar mag () const
scalar magSqr () const
scalar dist (const Vector2D< Cmpt > &v2) const
scalar distSqr (const Vector2D< Cmpt > &v2) const
Vector2D< Cmpt > & normalise (const scalar tol=ROOTVSMALL)
Vector2D< Cmpt > & removeCollinear (const Vector2D< Cmpt > &unitVec)
scalar perp (const Vector2D< Cmpt > &b) const
bool isClose (const Vector2D< Cmpt > &b, const scalar tol=1e-10) const
Public Member Functions inherited from VectorSpace< Vector2D< Cmpt >, Cmpt, 2 >
VectorSpace ()=default
VectorSpace (const Foam::zero)
VectorSpace (const VectorSpace< Vector2D< Cmpt >, Cmpt, Ncmpts > &vs)
VectorSpace (const VectorSpace< Form2, Cmpt2, Ncmpts > &)
VectorSpace (Istream &is)
const Cmpt & component (const direction) const
Cmpt & component (const direction)
void component (Cmpt &, const direction) const
void replace (const direction, const Cmpt &)
const Cmpt * cdata () const noexcept
Cmpt * data () noexcept
const ConstBlock< SubVector, BStart > block () const
const Foam::VectorSpace< Vector2D< Cmpt >, Cmpt, Ncmpts >::template ConstBlock< SubVector, BStart > block () const
const Cmpt & operator[] (const direction) const
Cmpt & operator[] (const direction)
void operator= (const VectorSpace< Vector2D< Cmpt >, Cmpt, Ncmpts > &)
void operator= (const Foam::zero)
void operator+= (const VectorSpace< Vector2D< Cmpt >, Cmpt, Ncmpts > &)
void operator-= (const VectorSpace< Vector2D< Cmpt >, Cmpt, Ncmpts > &)
void operator*= (const scalar)
void operator/= (const scalar)
iterator begin () noexcept
const_iterator begin () const noexcept
iterator end () noexcept
const_iterator end () const noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
Static Public Member Functions
static bool less_xy (const Vector2D< Cmpt > &a, const Vector2D< Cmpt > &b)
static bool less_yx (const Vector2D< Cmpt > &a, const Vector2D< Cmpt > &b)
Static Public Member Functions inherited from VectorSpace< Vector2D< Cmpt >, Cmpt, 2 >
static constexpr direction size () noexcept
static Vector2D< Cmpt > uniform (const Cmpt &s)
Static Public Attributes
static constexpr direction rank = 1
Static Public Attributes inherited from VectorSpace< Vector2D< Cmpt >, Cmpt, 2 >
static constexpr direction dim
static constexpr direction nComponents
static constexpr direction mRows
static constexpr direction nCols
static const char *const typeName
static const char *const componentNames []
static const Vector2D< Cmpt > zero
static const Vector2D< Cmpt > one
static const Vector2D< Cmpt > max
static const Vector2D< Cmpt > min
static const Vector2D< Cmpt > rootMax
static const Vector2D< Cmpt > rootMin
Additional Inherited Members
Public Attributes inherited from VectorSpace< Vector2D< Cmpt >, Cmpt, 2 >
Cmpt v_ [Ncmpts]
Detailed Description
template<class Cmpt>
class Foam::Vector2D< Cmpt >
Templated 2D Vector derived from VectorSpace adding construction from 2 components, element access using x() and y() member functions and the inner-product (dot-product).
Source files
Vector2D.H
Vector2DI.H
Definition at line 51 of file Vector2D.H.
Member Typedef Documentation
labelType
template<class Cmpt > typedef Vector2D<label> labelType
Definition at line 60 of file Vector2D.H.
Member Enumeration Documentation
components
template<class Cmpt > enum components
Enumerator
X
Y
Definition at line 70 of file Vector2D.H.
Constructor & Destructor Documentation
Vector2D() [1/6]
template<class Cmpt > Vector2D () default
Vector2D() [2/6]
template<class Cmpt > Vector2D (const Vector2D< Cmpt > &) default
Vector2D() [3/6]
template<class Cmpt > Vector2D (const Foam::zero) inline
Definition at line 25 of file Vector2DI.H.
Vector2D() [4/6]
template<class Cmpt > Vector2D (const VectorSpace< Vector2D< Cmpt >, Cmpt, 2 > & vs) inline
Definition at line 32 of file Vector2DI.H.
Vector2D() [5/6]
template<class Cmpt > Vector2D (const Cmpt & vx, const Cmpt & vy) inline
Definition at line 42 of file Vector2DI.H.
References Y.
Vector2D() [6/6]
template<class Cmpt > Vector2D (Istream & is) inline explicit
Definition at line 50 of file Vector2DI.H.
Member Function Documentation
operator=()
template<class Cmpt > Vector2D & operator= (const Vector2D< Cmpt > &) default
x() [1/2]
template<class Cmpt > const Cmpt & x () const inline noexcept
Definition at line 105 of file Vector2D.H.
References VectorSpace< Vector2D< Cmpt >, Cmpt, 2 >::v_, and Vector2D< Cmpt >::X.
y() [1/2]
template<class Cmpt > const Cmpt & y () const inline noexcept
Definition at line 108 of file Vector2D.H.
References VectorSpace< Vector2D< Cmpt >, Cmpt, 2 >::v_, and Vector2D< Cmpt >::Y.
x() [2/2]
template<class Cmpt > Cmpt & x () inline noexcept
Definition at line 111 of file Vector2D.H.
References VectorSpace< Vector2D< Cmpt >, Cmpt, 2 >::v_, and Vector2D< Cmpt >::X.
y() [2/2]
template<class Cmpt > Cmpt & y () inline noexcept
Definition at line 114 of file Vector2D.H.
References VectorSpace< Vector2D< Cmpt >, Cmpt, 2 >::v_, and Vector2D< Cmpt >::Y.
mag()
template<class Cmpt > Foam::scalar mag () const inline
Definition at line 70 of file Vector2DI.H.
References Foam::magSqr().
magSqr()
template<class Cmpt > Foam::scalar magSqr () const inline
Definition at line 59 of file Vector2DI.H.
References Foam::magSqr(), x, and y.
dist()
template<class Cmpt > Foam::scalar dist (const Vector2D< Cmpt > & v2) const inline
Definition at line 89 of file Vector2DI.H.
distSqr()
template<class Cmpt > Foam::scalar distSqr (const Vector2D< Cmpt > & v2) const inline
Definition at line 78 of file Vector2DI.H.
References Foam::magSqr().
normalise()
template<class Cmpt > Foam::Vector2D< Cmpt > & normalise (const scalar tol = ROOTVSMALL) inline
Definition at line 96 of file Vector2DI.H.
removeCollinear()
template<class Cmpt > Foam::Vector2D< Cmpt > & removeCollinear (const Vector2D< Cmpt > & unitVec) inline
Definition at line 115 of file Vector2DI.H.
perp()
template<class Cmpt > scalar perp (const Vector2D< Cmpt > & b) const inline
Definition at line 163 of file Vector2DI.H.
Referenced by triangle2D::area(), triangle2D::lineSegmentIntersectionPoint(), and line< Point, PointRef >::nearestDist().
isClose()
template<class Cmpt > bool isClose (const Vector2D< Cmpt > & b, const scalar tol = 1e-10) const inline
Definition at line 170 of file Vector2DI.H.
References b, Foam::mag(), x, and y.
less_xy()
template<class Cmpt > bool less_xy (const Vector2D< Cmpt > & a, const Vector2D< Cmpt > & b) inline static
Definition at line 126 of file Vector2DI.H.
less_yx()
template<class Cmpt > bool less_yx (const Vector2D< Cmpt > & a, const Vector2D< Cmpt > & b) inline static
Definition at line 138 of file Vector2DI.H.
Member Data Documentation
rank
template<class Cmpt > constexpr direction rank = 1 static constexpr
Definition at line 66 of file Vector2D.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/Vector2D/Vector2D.H
src/OpenFOAM/primitives/Vector2D/Vector2DI.H