OpenFOAM: perfectGas< Specie > Class Template Reference
perfectGas< Specie > Class Template Reference
Thermophysical models » Specie » Equation of state
Perfect gas equation of state.
#include <perfectGas.H>
Public Member Functions
perfectGas (const Specie &sp)
perfectGas (const dictionary &dict)
perfectGas (const word &name, const perfectGas &)
autoPtr< perfectGas > clone () const
scalar rho (scalar p, scalar T) const
scalar H (const scalar p, const scalar T) const
scalar Cp (scalar p, scalar T) const
scalar E (const scalar p, const scalar T) const
scalar Cv (scalar p, scalar T) const
scalar S (const scalar p, const scalar T) const
scalar psi (scalar p, scalar T) const
scalar Z (scalar p, scalar T) const
scalar CpMCv (scalar p, scalar T) const
void write (Ostream &os) const
void operator+= (const perfectGas &)
void operator*= (const scalar)
Static Public Member Functions
static autoPtr< perfectGas > New (const dictionary &dict)
static word typeName ()
Static Public Attributes
static const bool incompressible = false
static const bool isochoric = false
Friends
perfectGas operator+ (const perfectGas &, const perfectGas &)
perfectGas operator* (const scalar s, const perfectGas &)
perfectGas operator== (const perfectGas &, const perfectGas &)
Ostream & operator<< (Ostream &, const perfectGas &)
Detailed Description
template<class Specie>
class Foam::perfectGas< Specie >
Perfect gas equation of state.
Source files
perfectGas.H
perfectGasI.H
perfectGas.C
Definition at line 84 of file perfectGas.H.
Constructor & Destructor Documentation
perfectGas() [1/3]
template<class Specie > perfectGas (const Specie & sp) inline
Definition at line 29 of file perfectGasI.H.
perfectGas() [2/3]
template<class Specie > perfectGas (const dictionary & dict)
Definition at line 27 of file perfectGas.C.
perfectGas() [3/3]
template<class Specie > perfectGas (const word & name, const perfectGas< Specie > &) inline
Member Function Documentation
clone()
template<class Specie > Foam::autoPtr< Foam::perfectGas< Specie > > clone () const inline
Definition at line 50 of file perfectGasI.H.
References Foam::New().
New()
template<class Specie > Foam::autoPtr< Foam::perfectGas< Specie > > New (const dictionary & dict) inline static
Definition at line 57 of file perfectGasI.H.
References dict, and Foam::New().
typeName()
template<class Specie > static word typeName () inline static
Definition at line 112 of file perfectGas.H.
rho()
template<class Specie > Foam::scalar rho (scalar p, scalar T) const inline
Definition at line 69 of file perfectGasI.H.
References p, R, and T.
H()
template<class Specie > Foam::scalar H (const scalar p, const scalar T) const inline
Definition at line 76 of file perfectGasI.H.
Cp()
template<class Specie > Foam::scalar Cp (scalar p, scalar T) const inline
Definition at line 83 of file perfectGasI.H.
E()
template<class Specie > Foam::scalar E (const scalar p, const scalar T) const inline
Definition at line 90 of file perfectGasI.H.
Cv()
template<class Specie > Foam::scalar Cv (scalar p, scalar T) const inline
Definition at line 97 of file perfectGasI.H.
S()
template<class Specie > Foam::scalar S (const scalar p, const scalar T) const inline
Definition at line 104 of file perfectGasI.H.
References Foam::log(), p, Foam::constant::thermodynamic::Pstd, and R.
psi()
template<class Specie > Foam::scalar psi (scalar p, scalar T) const inline
Definition at line 111 of file perfectGasI.H.
References R, and T.
Z()
template<class Specie > Foam::scalar Z (scalar p, scalar T) const inline
Definition at line 118 of file perfectGasI.H.
CpMCv()
template<class Specie > Foam::scalar CpMCv (scalar p, scalar T) const inline
Definition at line 125 of file perfectGasI.H.
References R.
write()
template<class Specie > void write (Ostream & os) const
Definition at line 36 of file perfectGas.C.
References os().
operator+=()
template<class Specie > void operator+= (const perfectGas< Specie > &) inline
Definition at line 134 of file perfectGasI.H.
operator*=()
template<class Specie > void operator*= (const scalar s) inline
Definition at line 141 of file perfectGasI.H.
References s().
Friends And Related Symbol Documentation
operator+
template<class Specie > perfectGas operator+ (const perfectGas< Specie > & , const perfectGas< Specie > &) friend
operator*
template<class Specie > perfectGas operator* (const scalar s, const perfectGas< Specie > &) friend
operator==
template<class Specie > perfectGas operator== (const perfectGas< Specie > & , const perfectGas< Specie > &) friend
operator<<
template<class Specie > Ostream & operator<< (Ostream & , const perfectGas< Specie > &) friend
Member Data Documentation
incompressible
template<class Specie > const bool incompressible = false static
Definition at line 121 of file perfectGas.H.
isochoric
template<class Specie > const bool isochoric = false static
Definition at line 124 of file perfectGas.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/equationOfState/perfectGas/perfectGas.H
src/thermophysicalModels/specie/equationOfState/perfectGas/perfectGas.C
src/thermophysicalModels/specie/equationOfState/perfectGas/perfectGasI.H