OpenFOAM: turbulentTemperatureRadCoupledMixedFvPatchScalarField Class Reference
turbulentTemperatureRadCoupledMixedFvPatchScalarField Class Reference
Mixed boundary condition for temperature and radiation heat transfer, suitable for multiregion cases. The optional specification of thin thermal layer resistances can be made using the entries thicknessLayers and kappaLayers.
#include <turbulentTemperatureRadCoupledMixedFvPatchScalarField.H>
Public Member Functions
TypeName ("compressible::turbulentTemperatureRadCoupledMixed")
turbulentTemperatureRadCoupledMixedFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
turbulentTemperatureRadCoupledMixedFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
turbulentTemperatureRadCoupledMixedFvPatchScalarField (const turbulentTemperatureRadCoupledMixedFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
turbulentTemperatureRadCoupledMixedFvPatchScalarField (const turbulentTemperatureRadCoupledMixedFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
turbulentTemperatureRadCoupledMixedFvPatchScalarField (const turbulentTemperatureRadCoupledMixedFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual void autoMap (const fvPatchFieldMapper &)
virtual void rmap (const fvPatchField< scalar > &, const labelList &)
virtual tmp< scalarField > kappa (const scalarField &Tp) const
virtual void updateCoeffs ()
virtual void manipulateMatrix (fvMatrix< scalar > &m, const label iMatrix, const direction cmpt)
virtual void write (Ostream &os) const
Public Member Functions inherited from temperatureCoupledBase
temperatureCoupledBase (const fvPatch &patch, const KMethodType method=KMethodType::mtFluidThermo)
temperatureCoupledBase (const fvPatch &patch, const KMethodType method, const word &kappaName, const word &alphaName, const word &alphaAniName)
temperatureCoupledBase (const fvPatch &patch, const dictionary &dict)
temperatureCoupledBase (const fvPatch &patch, const temperatureCoupledBase &base)
temperatureCoupledBase (const temperatureCoupledBase &base)
virtual ~temperatureCoupledBase ()=default
word KMethod () const
const word & kappaName () const noexcept
const word & alphaName () const noexcept
virtual tmp< scalarField > alpha (const scalarField &Tp) const
void write (Ostream &os) const
Public Member Functions inherited from mappedPatchFieldBase< scalar >
mappedPatchFieldBase (const mappedPatchBase &mapper, const fvPatchField< scalar > &patchField, const word &fieldName, const bool setAverage, const scalar average, const word &interpolationScheme)
mappedPatchFieldBase (const mappedPatchBase &mapper, const fvPatchField< scalar > &patchField, const dictionary &dict)
mappedPatchFieldBase (const mappedPatchBase &mapper, const fvPatchField< scalar > &patchField, const dictionary &dict, const Field< scalar > &fld)
mappedPatchFieldBase (const mappedPatchBase &mapper, const fvPatchField< scalar > &patchField)
mappedPatchFieldBase (const mappedPatchFieldBase< scalar > &mapper)
mappedPatchFieldBase (const mappedPatchBase &mapper, const fvPatchField< scalar > &patchField, const mappedPatchFieldBase< scalar > &base)
virtual ~mappedPatchFieldBase ()=default
const GeometricField< T, fvPatchField, volMesh > & sampleField (const word &fieldName) const
const GeometricField< scalar, fvPatchField, volMesh > & sampleField () const
const Foam::GeometricField< Type2, Foam::fvPatchField, Foam::volMesh > & sampleField (const word &fieldName) const
virtual tmp< Field< scalar > > mappedField () const
virtual tmp< Field< scalar > > mappedInternalField () const
virtual tmp< scalarField > mappedWeightField () const
virtual void mappedWeightField (const word &weightFieldName, tmp< scalarField > &thisWeights, tmp< scalarField > &nbrWeights) const
void distribute (const word &fieldName, Field< T > &newValues) const
Public Member Functions inherited from writeFile
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name="undefined", const bool writeToFile=true)
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name, const dictionary &dict, const bool writeToFile=true)
writeFile (const writeFile &wf)
virtual ~writeFile ()=default
virtual bool read (const dictionary &dict)
virtual OFstream & file ()
virtual bool writeToFile () const
virtual bool canWriteToFile () const
virtual bool canResetFile () const
virtual bool canWriteHeader () const
virtual label charWidth () const
virtual void writeCommented (Ostream &os, const string &str) const
virtual void writeTabbed (Ostream &os, const string &str) const
virtual void writeHeader (Ostream &os, const string &str) const
virtual void writeCurrentTime (Ostream &os) const
virtual void writeBreak (Ostream &os) const
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
template<class Type >
void writeValue (Ostream &os, const Type &val) const
Additional Inherited Members
Public Types inherited from temperatureCoupledBase
enum KMethodType {
mtFluidThermo , mtSolidThermo , mtDirectionalSolidThermo , mtLookup ,
mtFunction
}
Static Public Member Functions inherited from mappedPatchFieldBase< scalar >
static const mappedPatchBase & mapper (const fvPatch &p, const DimensionedField< scalar, volMesh > &iF)
Static Public Attributes inherited from writeFile
static label addChars = 8
Protected Member Functions inherited from mappedPatchFieldBase< scalar >
void initRetrieveField (const objectRegistry &obr, const word &region, const word &patch, const labelListList &map, const word &fieldName, const Field< T > &fld) const
void initRetrieveField (const word &fieldName, const Field< T > &fld) const
bool storeAndRetrieveField (const word &fieldName, const label myComm, const labelListList &subMap, const label constructSize, const labelListList &constructMap, const labelListList &address, const scalarListList &weights, Field< T > &fld) const
void storeField (const objectRegistry &obr, const word &region, const word &patch, const label myComm, const labelListList &procToMap, const word &fieldName, const Field< T > &fld) const
bool retrieveField (const bool allowUnset, const objectRegistry &obr, const word &region, const word &patch, const label myComm, const labelListList &procToMap, const word &fieldName, Field< T > &fld) const
Protected Member Functions inherited from writeFile
void initStream (Ostream &os) const
fileName baseFileDir () const
fileName baseTimeDir () const
fileName filePath (const fileName &fName) const
virtual autoPtr< OFstream > newFile (const fileName &fName) const
virtual autoPtr< OFstream > newFileAtTime (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > newFileAtStartTime (const word &name) const
virtual void resetFile (const word &name)
Omanip< int > valueWidth (const label offset=0) const
void operator= (const writeFile &)=delete
virtual autoPtr< OFstream > createFile (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > createFile (const word &name) const
Protected Attributes inherited from temperatureCoupledBase
const fvPatch & patch_
const KMethodType method_
const word kappaName_
const word alphaName_
const word alphaAniName_
autoPtr< PatchFunction1< scalar > > kappaFunction1_
autoPtr< PatchFunction1< scalar > > alphaFunction1_
Protected Attributes inherited from mappedPatchFieldBase< scalar >
const mappedPatchBase & mapper_
const fvPatchField< scalar > & patchField_
word fieldName_
const bool setAverage_
const scalar average_
word interpolationScheme_
Protected Attributes inherited from writeFile
const objectRegistry & fileObr_
const fileName prefix_
word fileName_
autoPtr< OFstream > filePtr_
label writePrecision_
bool writeToFile_
bool updateHeader_
bool writtenHeader_
bool useUserTime_
scalar startTime_
Static Protected Attributes inherited from temperatureCoupledBase
static const Enum< KMethodType > KMethodTypeNames_
Detailed Description
Mixed boundary condition for temperature and radiation heat transfer, suitable for multiregion cases. The optional specification of thin thermal layer resistances can be made using the entries thicknessLayers and kappaLayers.
The thermal conductivity kappa can be obtained from a variety of sources, as explained in the temperatureCoupledBase class.
Usage
Example of the boundary condition specification:
<patchName>
{
    // Mandatory entries
    type                compressible::turbulentTemperatureRadCoupledMixed;
    // Optional entries
    Tnbr                <word>;
    qrNbr               <word>;
    qr                  <word>;
    logInterval         <scalar>;
    thermalInertia      <bool>;
    verbose             <bool>;
    prefix              <word>;
    // Conditional entries
        // Option-1
        thicknessLayers <scalarList>;
        kappaLayers     <scalarList>;
        // Option-2
        thicknessLayer  <PatchFunction1<scalar>>;
        kappaLayer      <PatchFunction1<scalar>>;
    // Inherited entries
    kappaMethod         <word>;
    kappa               <word>;
    ...
}
For example:
<patchName>
{
    type            compressible::turbulentTemperatureRadCoupledMixed;
    Tnbr            T;
    qrNbr           qr; // or none. Name of qr field on neighbour region
    qr              qr; // or none. Name of qr field on this region
    thicknessLayers (0.1 0.2 0.3 0.4);
    kappaLayers     (1 2 3 4);
    thermalInertia  false/true;
    kappaMethod     lookup;
    kappa           kappa;
    value           uniform 300;
}
where the entries mean:
Property Description Type Reqd Deflt
type
Type name: compressible::turbulentTemperatureRadCoupledMixed
word yes -
Tnbr Name of the nbr temperature field word no T
qrNbr Name of the radiative flux in the nbr region word no none
qr Name of the radiative flux in this region word no none
logInterval Log-file output frequency [s] scalar no -1
thermalInertia Flag to add thermal inertia to wall node bool
no
false
verbose Flag to enable verbose output with extra fields bool
no
false
prefix
Name of output-field prefix (in verbose mode)
word no multiWorld
thicknessLayers List of thicknesses per layer [m]
scalarList
choice -
kappaLayers
List of thermal conductivites per layer [W/m/K]
scalarList choice -
thicknessLayer
Single thickness of layer [m]
PatchFunction1<scalar> choice -
kappaLayer
Corresponding thermal conductivity [W/m/K]
PatchFunction1<scalar> choice -
The inherited entries are elaborated in:
mixedFvPatchFields.H
temperatureCoupledBase.H
mappedPatchFieldBase.H
writeFile.H
Note
Needs to be on underlying mapped(Wall)FvPatch.
Source files
turbulentTemperatureRadCoupledMixedFvPatchScalarField.H
turbulentTemperatureRadCoupledMixedFvPatchScalarField.C
Definition at line 238 of file turbulentTemperatureRadCoupledMixedFvPatchScalarField.H.
Constructor & Destructor Documentation
turbulentTemperatureRadCoupledMixedFvPatchScalarField() [1/5]
turbulentTemperatureRadCoupledMixedFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 116 of file turbulentTemperatureRadCoupledMixedFvPatchScalarField.C.
References Foam::Zero.
turbulentTemperatureRadCoupledMixedFvPatchScalarField() [2/5]
turbulentTemperatureRadCoupledMixedFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 186 of file turbulentTemperatureRadCoupledMixedFvPatchScalarField.C.
References dict, Foam::exit(), Foam::FatalError, FatalErrorInFunction, IOobjectOption::MUST_READ, PatchFunction1< Type >::NewIfPresent(), p, and Foam::Zero.
turbulentTemperatureRadCoupledMixedFvPatchScalarField() [3/5]
turbulentTemperatureRadCoupledMixedFvPatchScalarField (const turbulentTemperatureRadCoupledMixedFvPatchScalarField & psf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 153 of file turbulentTemperatureRadCoupledMixedFvPatchScalarField.C.
turbulentTemperatureRadCoupledMixedFvPatchScalarField() [4/5]
turbulentTemperatureRadCoupledMixedFvPatchScalarField (const turbulentTemperatureRadCoupledMixedFvPatchScalarField & psf)
Definition at line 354 of file turbulentTemperatureRadCoupledMixedFvPatchScalarField.C.
turbulentTemperatureRadCoupledMixedFvPatchScalarField() [5/5]
turbulentTemperatureRadCoupledMixedFvPatchScalarField (const turbulentTemperatureRadCoupledMixedFvPatchScalarField & psf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 323 of file turbulentTemperatureRadCoupledMixedFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("compressible::turbulentTemperatureRadCoupledMixed")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Reimplemented in thermalBaffleFvPatchScalarField.
Definition at line 363 of file turbulentTemperatureRadCoupledMixedFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Reimplemented in thermalBaffleFvPatchScalarField.
Definition at line 382 of file turbulentTemperatureRadCoupledMixedFvPatchScalarField.H.
autoMap()
void autoMap (const fvPatchFieldMapper & mapper) virtual
Implements temperatureCoupledBase.
Definition at line 386 of file turbulentTemperatureRadCoupledMixedFvPatchScalarField.C.
References temperatureCoupledBase::autoMap(), and mappedPatchFieldBase< scalar >::mapper().
rmap()
void rmap (const fvPatchField< scalar > & ptf, const labelList & addr) virtual
Implements temperatureCoupledBase.
Definition at line 402 of file turbulentTemperatureRadCoupledMixedFvPatchScalarField.C.
References Foam::refCast(), and temperatureCoupledBase::rmap().
kappa()
tmp< Foam::scalarField > kappa (const scalarField & Tp) const virtual
Reimplemented from temperatureCoupledBase.
Definition at line 427 of file turbulentTemperatureRadCoupledMixedFvPatchScalarField.C.
References temperatureCoupledBase::kappa().
Referenced by turbulentTemperatureRadCoupledMixedFvPatchScalarField::updateCoeffs().
updateCoeffs()
void updateCoeffs () virtual
Reimplemented in thermalBaffleFvPatchScalarField.
Definition at line 439 of file turbulentTemperatureRadCoupledMixedFvPatchScalarField.C.
References alpha, writeFile::canResetFile(), writeFile::canWriteHeader(), writeFile::canWriteToFile(), basicThermo::dictName, mappedPatchFieldBase< scalar >::distribute(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, writeFile::file(), forAll, Foam::gAverage(), Foam::gMinMax(), Foam::gSum(), Foam::Info, turbulentTemperatureRadCoupledMixedFvPatchScalarField::kappa(), Foam::mag(), mappedPatchFieldBase< Type >::mapper(), Foam::max(), mesh, UPstream::msgType(), Foam::name(), Foam::nl, pp(), Foam::refCast(), writeFile::resetFile(), PtrList< T >::setSize(), UPtrList< T >::size(), UList< T >::size(), T, token::TAB, and Foam::Zero.
Referenced by thermalBaffleFvPatchScalarField::updateCoeffs().
manipulateMatrix()
void manipulateMatrix (fvMatrix< scalar > & m, const label iMatrix, const direction cmpt) virtual
Definition at line 773 of file turbulentTemperatureRadCoupledMixedFvPatchScalarField.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
write()
void write (Ostream & os) const virtual
Reimplemented from mappedPatchFieldBase< scalar >.
Reimplemented in thermalBaffleFvPatchScalarField.
Definition at line 951 of file turbulentTemperatureRadCoupledMixedFvPatchScalarField.C.
References os(), UList< T >::size(), writeFile::updateHeader_, writeFile::useUserTime_, mixedFvPatchField< Type >::write(), mappedPatchFieldBase< Type >::write(), temperatureCoupledBase::write(), UList< T >::writeEntry(), writeFile::writePrecision_, and writeFile::writeToFile_.
Referenced by thermalBaffleFvPatchScalarField::write().
The documentation for this class was generated from the following files:
src/thermoTools/derivedFvPatchFields/turbulentTemperatureRadCoupledMixed/turbulentTemperatureRadCoupledMixedFvPatchScalarField.H
src/thermoTools/derivedFvPatchFields/turbulentTemperatureRadCoupledMixed/turbulentTemperatureRadCoupledMixedFvPatchScalarField.C