OpenFOAM: dragModel Class Reference
dragModel Class Reference abstract
#include <dragModel.H>
Public Member Functions
TypeName ("dragModel")
declareRunTimeSelectionTable (autoPtr, dragModel, dictionary,(const dictionary &interfaceDict, const phaseModel &phase1, const phaseModel &phase2),(interfaceDict, phase1, phase2))
dragModel (const dictionary &dict, const phaseModel &phase1, const phaseModel &phase2)
virtual ~dragModel ()=default
const phaseModel & phase1 () const
const phaseModel & phase2 () const
const dimensionedScalar & residualPhaseFraction () const
const dimensionedScalar & residualSlip () const
virtual tmp< volScalarField > K (const volScalarField &Ur) const =0
Static Public Member Functions
static autoPtr< dragModel > New (const dictionary &dict, const phaseModel &phase1, const phaseModel &phase2)
Protected Attributes
const dictionary & interfaceDict_
const phaseModel & phase1_
const phaseModel & phase2_
dimensionedScalar residualPhaseFraction_
dimensionedScalar residualSlip_
Detailed Description
Source files
dragModel.H
dragModel.C
Definition at line 50 of file dragModel.H.
Constructor & Destructor Documentation
dragModel()
dragModel (const dictionary & dict, const phaseModel & phase1, const phaseModel & phase2)
Definition at line 38 of file dragModel.C.
References Foam::dimless, and Foam::dimVelocity.
~dragModel()
virtual ~dragModel () virtual default
Member Function Documentation
TypeName()
TypeName ("dragModel")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , dragModel , dictionary , (const dictionary &interfaceDict, const phaseModel &phase1, const phaseModel &phase2) , (interfaceDict, phase1, phase2))
New()
Foam::autoPtr< Foam::multiphaseEuler::dragModel > New (const dictionary & dict, const phaseModel & phase1, const phaseModel & phase2) static
Definition at line 56 of file dragModel.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, Foam::Info, phase1, and phase2.
Referenced by multiphaseSystem::multiphaseSystem().
phase1()
const phaseModel & phase1 () const inline
Definition at line 110 of file dragModel.H.
References dragModel::phase1_.
phase2()
const phaseModel & phase2 () const inline
Definition at line 115 of file dragModel.H.
References dragModel::phase2_.
residualPhaseFraction()
const dimensionedScalar & residualPhaseFraction () const inline
Definition at line 120 of file dragModel.H.
References dragModel::residualPhaseFraction_.
residualSlip()
const dimensionedScalar & residualSlip () const inline
Definition at line 125 of file dragModel.H.
References dragModel::residualSlip_.
K()
virtual tmp< volScalarField > K (const volScalarField & Ur) const pure virtual
Implemented in blended, Ergun, Gibilaro, GidaspowErgunWenYu, GidaspowSchillerNaumann, interface, SchillerNaumann, SyamlalOBrien, and WenYu.
Member Data Documentation
interfaceDict_
const dictionary& interfaceDict_ protected
Definition at line 56 of file dragModel.H.
phase1_
const phaseModel& phase1_ protected
Definition at line 57 of file dragModel.H.
Referenced by dragModel::phase1().
phase2_
const phaseModel& phase2_ protected
Definition at line 58 of file dragModel.H.
Referenced by dragModel::phase2().
residualPhaseFraction_
dimensionedScalar residualPhaseFraction_ protected
Definition at line 59 of file dragModel.H.
Referenced by dragModel::residualPhaseFraction().
residualSlip_
dimensionedScalar residualSlip_ protected
Definition at line 60 of file dragModel.H.
Referenced by dragModel::residualSlip().
The documentation for this class was generated from the following files:
src/phaseSystemModels/multiphaseEuler/multiphaseSystem/interfacialModels/dragModels/dragModel/dragModel.H
src/phaseSystemModels/multiphaseEuler/multiphaseSystem/interfacialModels/dragModels/dragModel/dragModel.C