OpenFOAM: tabulatedSolidTransport< Thermo > Class Template Reference
tabulatedSolidTransport< Thermo > Class Template Reference
Transport properties package using non-uniform tabulated data for thermal conductivity vs temperature.
#include <tabulatedSolidTransport.H>
Public Member Functions
tabulatedSolidTransport (const word &, const tabulatedSolidTransport &)
tabulatedSolidTransport (const dictionary &dict)
autoPtr< tabulatedSolidTransport > clone () const
scalar mu (const scalar p, const scalar T) const
scalar kappa (const scalar p, const scalar T) const
vector Kappa (const scalar p, const scalar T) const
scalar alphah (const scalar p, const scalar T) const
void write (Ostream &os) const
Static Public Member Functions
static autoPtr< tabulatedSolidTransport > New (const dictionary &dict)
static word typeName ()
Static Public Attributes
static const bool isotropic = true
Friends
Ostream & operator<< (Ostream &, const tabulatedSolidTransport &)
Detailed Description
template<class Thermo>
class Foam::tabulatedSolidTransport< Thermo >
Transport properties package using non-uniform tabulated data for thermal conductivity vs temperature.
Usage
Property Description
kappa Thermal conductivity vs temperature table
Example of the specification of the transport properties:
    transport
    {
        kappa
        (
            (200 2.56e-5)
            (350 3.33e-5)
            (400 4.72e-5)
        );
    }
Source files
tabulatedSolidTransport.H
tabulatedSolidTransportI.H
tabulatedSolidTransport.C
See also
Foam::thermophysicalFunctions::nonUniformTable
Definition at line 85 of file tabulatedSolidTransport.H.
Constructor & Destructor Documentation
tabulatedSolidTransport() [1/2]
template<class Thermo > tabulatedSolidTransport (const word & name, const tabulatedSolidTransport< Thermo > & pt) inline
Definition at line 38 of file tabulatedSolidTransportI.H.
References Foam::name().
tabulatedSolidTransport() [2/2]
template<class Thermo > tabulatedSolidTransport (const dictionary & dict) explicit
Definition at line 27 of file tabulatedSolidTransport.C.
Member Function Documentation
clone()
template<class Thermo > Foam::autoPtr< Foam::tabulatedSolidTransport< Thermo > > clone () const inline
Definition at line 51 of file tabulatedSolidTransportI.H.
References Foam::New().
New()
template<class Thermo > Foam::autoPtr< Foam::tabulatedSolidTransport< Thermo > > New (const dictionary & dict) inline static
Definition at line 59 of file tabulatedSolidTransportI.H.
References dict, and Foam::New().
typeName()
template<class Thermo > static word typeName () inline static
Definition at line 128 of file tabulatedSolidTransport.H.
mu()
template<class Thermo > Foam::scalar mu (const scalar p, const scalar T) const inline
Definition at line 68 of file tabulatedSolidTransportI.H.
References NotImplemented.
kappa()
template<class Thermo > Foam::scalar kappa (const scalar p, const scalar T) const inline
Definition at line 80 of file tabulatedSolidTransportI.H.
References p, and T.
Kappa()
template<class Thermo > Foam::vector Kappa (const scalar p, const scalar T) const inline
Definition at line 91 of file tabulatedSolidTransportI.H.
References p, and T.
alphah()
template<class Thermo > Foam::scalar alphah (const scalar p, const scalar T) const inline
Definition at line 103 of file tabulatedSolidTransportI.H.
References Cp, p, and T.
write()
template<class Thermo > void write (Ostream & os) const
Definition at line 40 of file tabulatedSolidTransport.C.
References Ostream::beginBlock(), Ostream::endBlock(), Foam::name(), os(), and Ostream::writeEntry().
Friends And Related Symbol Documentation
operator<<
template<class Thermo > Ostream & operator<< (Ostream & , const tabulatedSolidTransport< Thermo > &) friend
Member Data Documentation
isotropic
template<class Thermo > const bool isotropic = true static
Definition at line 134 of file tabulatedSolidTransport.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/solidSpecie/transport/tabulated/tabulatedSolidTransport.H
src/thermophysicalModels/solidSpecie/transport/tabulated/tabulatedSolidTransport.C
src/thermophysicalModels/solidSpecie/transport/tabulated/tabulatedSolidTransportI.H