OpenFOAM: timeInfo Class Reference
timeInfo Class Reference
Writes the run time (time-step), cpuTime and clockTime - optionally with cpuTime and clockTime change for each time step.
#include <timeInfo.H>
Public Member Functions
TypeName ("timeInfo")
timeInfo (const word &name, const Time &runTime, const dictionary &dict)
virtual ~timeInfo ()=default
virtual bool read (const dictionary &dict)
virtual bool execute ()
virtual bool write ()
Public Member Functions inherited from timeFunctionObject
timeFunctionObject (const word &name, const Time &runTime)
virtual ~timeFunctionObject ()=default
const Time & time () const
objectRegistry & storedObjects ()
const objectRegistry & storedObjects () const
Public Member Functions inherited from functionObject
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name, const bool withNamePrefix=defaultUseNamePrefix)
autoPtr< functionObject > clone () const
virtual ~functionObject ()=default
virtual const word & type () const =0
const word & name () const noexcept
bool useNamePrefix () const noexcept
bool useNamePrefix (bool on) noexcept
virtual bool execute (const label subIndex)
virtual bool end ()
virtual bool adjustTimeStep ()
virtual bool filesModified () const
virtual void updateMesh (const mapPolyMesh &mpm)
virtual void movePoints (const polyMesh &mesh)
Public Member Functions inherited from writeFile
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name="undefined", const bool writeToFile=true)
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name, const dictionary &dict, const bool writeToFile=true)
writeFile (const writeFile &wf)
virtual ~writeFile ()=default
virtual OFstream & file ()
virtual bool writeToFile () const
virtual bool canWriteToFile () const
virtual bool canResetFile () const
virtual bool canWriteHeader () const
virtual label charWidth () const
virtual void writeCommented (Ostream &os, const string &str) const
virtual void writeTabbed (Ostream &os, const string &str) const
virtual void writeHeader (Ostream &os, const string &str) const
virtual void writeCurrentTime (Ostream &os) const
virtual void writeBreak (Ostream &os) const
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
template<class Type >
void writeValue (Ostream &os, const Type &val) const
Protected Member Functions
virtual void writeFileHeader (Ostream &os)
timeInfo (const timeInfo &)=delete
void operator= (const timeInfo &)=delete
Protected Member Functions inherited from timeFunctionObject
void clearOutputObjects (const wordList &objNames)
timeFunctionObject (const timeFunctionObject &)=delete
void operator= (const timeFunctionObject &)=delete
Protected Member Functions inherited from functionObject
word scopedName (const word &name) const
Protected Member Functions inherited from writeFile
void initStream (Ostream &os) const
fileName baseFileDir () const
fileName baseTimeDir () const
fileName filePath (const fileName &fName) const
virtual autoPtr< OFstream > newFile (const fileName &fName) const
virtual autoPtr< OFstream > newFileAtTime (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > newFileAtStartTime (const word &name) const
virtual void resetFile (const word &name)
Omanip< int > valueWidth (const label offset=0) const
void operator= (const writeFile &)=delete
virtual autoPtr< OFstream > createFile (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > createFile (const word &name) const
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &runTime, const dictionary &dict)
Public Attributes inherited from functionObject
bool log
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
static bool defaultUseNamePrefix
static word outputPrefix
Static Public Attributes inherited from writeFile
static label addChars = 8
Protected Attributes inherited from timeFunctionObject
const Time & time_
Protected Attributes inherited from writeFile
const objectRegistry & fileObr_
const fileName prefix_
word fileName_
autoPtr< OFstream > filePtr_
label writePrecision_
bool writeToFile_
bool updateHeader_
bool writtenHeader_
bool useUserTime_
scalar startTime_
Detailed Description
Writes the run time (time-step), cpuTime and clockTime - optionally with cpuTime and clockTime change for each time step.
Example of function object specification:
time
{
    type            timeInfo;
    libs            (utilityFunctionObjects);
    writeControl    timeStep;
    writeInterval   1;
    perTimeStep     no;
}
Where the entries comprise:
Property Description Required Default
type Type name: timeInfo yes
writeToFile Write information to file no yes
perTimeStep Write value per interval/step no no
The initial per-step value is likely to be inaccurate and should mostly be ignored.
See also
Foam::functionObject Foam::timeFunctionObject Foam::functionObjects::writeFile
Source files
timeInfo.H
timeInfo.C
Definition at line 101 of file timeInfo.H.
Constructor & Destructor Documentation
timeInfo() [1/2]
timeInfo (const timeInfo &) protected delete
timeInfo() [2/2]
timeInfo (const word & name, const Time & runTime, const dictionary & dict)
Definition at line 59 of file timeInfo.C.
References dict, writeFile::file(), timeInfo::read(), and timeInfo::writeFileHeader().
~timeInfo()
virtual ~timeInfo () virtual default
Member Function Documentation
writeFileHeader()
void writeFileHeader (Ostream & os) protected virtual
Definition at line 41 of file timeInfo.C.
References Foam::nl, os(), writeFile::writeCommented(), and writeFile::writeTabbed().
Referenced by timeInfo::timeInfo().
operator=()
void operator= (const timeInfo &) protected delete
TypeName()
TypeName ("timeInfo")
read()
bool read (const dictionary & dict) virtual
Reimplemented from functionObject.
Definition at line 79 of file timeInfo.C.
References dict, functionObject::read(), and writeFile::read().
Referenced by timeInfo::timeInfo().
execute()
bool execute () virtual
Implements functionObject.
Definition at line 89 of file timeInfo.C.
write()
bool write () virtual
Implements functionObject.
Definition at line 95 of file timeInfo.C.
References UPstream::master(), Foam::nl, and Foam::tab.
The documentation for this class was generated from the following files:
src/functionObjects/utilities/timeInfo/timeInfo.H
src/functionObjects/utilities/timeInfo/timeInfo.C