OpenFOAM: addPatchCellLayer Class Reference
addPatchCellLayer Class Reference
Adds layers of cells to outside of polyPatch. Can optionally create stand-alone extruded mesh (addToMesh=false).
#include <addPatchCellLayer.H>
Public Member Functions
ClassName ("addPatchCellLayer")
addPatchCellLayer (const polyMesh &, const bool addToMesh=true)
const labelListList & addedPoints () const
const labelListList & layerFaces () const
labelListList addedCells () const
void setRefinement (const globalIndex &globalFaces, const labelListList &globalEdgeFaces, const scalarField &expansionRatio, const indirectPrimitivePatch &pp, const bitSet &flip, const labelList &sidePatchID, const labelList &sideZoneID, const boolList &sideFlip, const labelList &inflateFaceID, const labelList &exposedPatchID, const labelList &nFaceLayers, const labelList &nPointLayers, const vectorField &firstLayerDisp, polyTopoChange &meshMod)
void setRefinement (const globalIndex &globalFaces, const labelListList &globalEdgeFaces, const label nLayers, const indirectPrimitivePatch &pp, const labelList &sidePatchID, const vectorField &overallDisplacement, polyTopoChange &meshMod)
void updateMesh (const mapPolyMesh &, const labelList &faceMap, const labelList &pointMap)
Static Public Member Functions
static labelListList addedCells (const polyMesh &, const labelListList &layerFaces)
static labelListList globalEdgeFaces (const polyMesh &, const globalIndex &globalFaces, const indirectPrimitivePatch &pp)
static void calcExtrudeInfo (const bool zoneFromAnyFace, const polyMesh &, const globalIndex &globalFaces, const labelListList &globalEdgeFaces, const indirectPrimitivePatch &pp, labelList &edgePatchID, label &nPatches, Map< label > &nbrProcToPatch, Map< label > &patchToNbrProc, labelList &edgeZoneID, boolList &edgeFlip, labelList &inflateFaceID)
Detailed Description
Adds layers of cells to outside of polyPatch. Can optionally create stand-alone extruded mesh (addToMesh=false).
Call setRefinement with offset vector for every patch point and number of layers per patch face and number of layers per patch point.
offset vector should be zero for any non-manifold point and synchronised on coupled points before calling this.
offset vector of zero will not add any points.
gets supplied the number of extruded layers both per face and per point. Usually the point nlayers is the max of surrounding face nlayers.
point nlayers:
0 : no extrusion. Any surrounding face being extruded becomes 'prism'
>0 : should be max of surrounding face nlayers.
differing face nlayers: 'termination' : (e.g. from 2 to 4 layers) match at original patch face side.
E.g. 2 boundary faces on patches a,b. 2 layers for a, 3 for b.
    Was:
       a      b         <- patch of boundary face
    +------+------+
    |      |      |     <- original cells
    +------+------+
    Becomes:
       a      b         <- patch of boundary face
    +------+------+
    +      +------+
    +------+------+
    +------+------+
    |      |      |     <- original cells
    +------+------+
added faces get same patchID as face they are extruded from
'side' faces (i.e. on the edge of pp) get the patchID/zoneID of the other patch/zone they are connected to (hopefully only 1)
E.g. 3 boundary faces on patches a,b. b gets extruded, a doesn't.
       a      b      b        <- patch of boundary face
    +------+------+------+
    |      |      |      |    <- cells
    +------+------+------+
           ^      ^           <- wanted extrusion vector (none at far right)
       a   |  b   |  b        <- patch of boundary face
    +------+------+------+
    |      |      |      |    <- cells
    +------+------+------+
              b
           +------+\ b        1. prism cell added onto second b face since
       a  a|      | ----\          only one side gets extruded.
    +------+------+------+    2. side-face gets patch a, not b.
    |      |      |      |
    +------+------+------+
Source files
addPatchCellLayer.H
addPatchCellLayer.C
Definition at line 124 of file addPatchCellLayer.H.
Constructor & Destructor Documentation
addPatchCellLayer()
addPatchCellLayer (const polyMesh & mesh, const bool addToMesh = true) explicit
Definition at line 604 of file addPatchCellLayer.C.
Member Function Documentation
ClassName()
ClassName ("addPatchCellLayer")
addedPoints()
const labelListList & addedPoints () const inline
Definition at line 300 of file addPatchCellLayer.H.
layerFaces()
const labelListList & layerFaces () const inline
Definition at line 306 of file addPatchCellLayer.H.
addedCells() [1/2]
Foam::labelListList addedCells (const polyMesh & mesh, const labelListList & layerFaces) static
Definition at line 619 of file addPatchCellLayer.C.
References faceLabels(), polyMesh::faceNeighbour(), forAll, mesh, PtrList< T >::setSize(), and UList< T >::size().
addedCells() [2/2]
Foam::labelListList addedCells () const
Definition at line 646 of file addPatchCellLayer.C.
globalEdgeFaces()
Foam::labelListList globalEdgeFaces (const polyMesh & mesh, const globalIndex & globalFaces, const indirectPrimitivePatch & pp) static
Definition at line 652 of file addPatchCellLayer.C.
References PrimitivePatch< FaceList, PointField >::edgeFaces(), primitiveMesh::edges(), forAll, mesh, PrimitivePatch< FaceList, PointField >::meshEdges(), primitiveMesh::nEdges(), primitiveMesh::pointEdges(), pp(), PtrList< T >::setSize(), UPtrList< T >::size(), and syncTools::syncEdgeList().
Referenced by snappyLayerDriver::addLayers(), snappyLayerDriver::addLayersSinglePass(), and addPatchCellLayer::setRefinement().
calcExtrudeInfo()
void calcExtrudeInfo (const bool zoneFromAnyFace, const polyMesh & mesh, const globalIndex & globalFaces, const labelListList & globalEdgeFaces, const indirectPrimitivePatch & pp, labelList & edgePatchID, label & nPatches, Map< label > & nbrProcToPatch, Map< label > & patchToNbrProc, labelList & edgeZoneID, boolList & edgeFlip, labelList & inflateFaceID) static
Definition at line 1097 of file addPatchCellLayer.C.
References polyMesh::boundaryMesh(), e, primitiveMesh::edgeFaces(), PrimitivePatch< FaceList, PointField >::edgeFaces(), primitiveMesh::edges(), PrimitivePatch< FaceList, PointField >::edges(), Foam::endl(), forAll, polyMesh::globalData(), primitiveMesh::isInternalFace(), k, PatchTools::matchEdges(), mesh, PrimitivePatch< FaceList, PointField >::meshEdges(), PrimitivePatch< FaceList, PointField >::meshPoints(), PrimitivePatch< FaceList, PointField >::nEdges(), nPatches, UPstream::parRun(), patches, primitiveMesh::pointEdges(), PrimitivePatch< FaceList, PointField >::points(), pp(), PtrList< T >::setSize(), UPtrList< T >::size(), globalMeshData::syncData(), and WarningInFunction.
setRefinement() [1/2]
void setRefinement (const globalIndex & globalFaces, const labelListList & globalEdgeFaces, const scalarField & expansionRatio, const indirectPrimitivePatch & pp, const bitSet & flip, const labelList & sidePatchID, const labelList & sideZoneID, const boolList & sideFlip, const labelList & inflateFaceID, const labelList & exposedPatchID, const labelList & nFaceLayers, const labelList & nPointLayers, const vectorField & firstLayerDisp, polyTopoChange & meshMod)
Definition at line 1425 of file addPatchCellLayer.C.
References Foam::abort(), PtrList< T >::clear(), UPtrList< T >::count(), e, PrimitivePatch< FaceList, PointField >::edgeFaces(), PrimitivePatch< FaceList, PointField >::edges(), UPtrList< T >::empty(), Foam::endl(), Foam::exit(), f(), PrimitivePatch< FaceList, PointField >::faceEdges(), Foam::FatalError, FatalErrorInFunction, UList< T >::fcIndex(), forAll, forAllReverse, Foam::gMax(), Foam::labelMax, UPtrList< T >::last(), PrimitivePatch< FaceList, PointField >::localFaces(), PrimitivePatch< FaceList, PointField >::localPoints(), Foam::mag(), Foam::max(), VectorSpace< Form, Cmpt, Ncmpts >::max, PrimitivePatch< FaceList, PointField >::meshEdges(), PrimitivePatch< FaceList, PointField >::meshPointMap(), PrimitivePatch< FaceList, PointField >::meshPoints(), polyTopoChange::modifyFace(), n, PrimitivePatch< FaceList, PointField >::nEdges(), PrimitivePatch< FaceList, PointField >::nInternalEdges(), Foam::nl, PrimitivePatch< FaceList, PointField >::nPoints(), patches, patchID, polyTopoChange::points(), PrimitivePatch< FaceList, PointField >::points(), Foam::Pout, pp(), Foam::returnReduceOr(), face::reverseFace(), PtrList< T >::set(), polyTopoChange::setAction(), List< T >::setSize(), PtrList< T >::setSize(), UPtrList< T >::size(), UList< T >::size(), syncTools::swapBoundaryFaceList(), syncTools::syncBoundaryFaceList(), syncTools::syncEdgeList(), syncTools::syncPointList(), and Foam::Zero.
Referenced by addPatchCellLayer::setRefinement().
setRefinement() [2/2]
void setRefinement (const globalIndex & globalFaces, const labelListList & globalEdgeFaces, const label nLayers, const indirectPrimitivePatch & pp, const labelList & sidePatchID, const vectorField & overallDisplacement, polyTopoChange & meshMod) inline
Definition at line 410 of file addPatchCellLayer.H.
References addPatchCellLayer::globalEdgeFaces(), pp(), and addPatchCellLayer::setRefinement().
updateMesh()
void updateMesh (const mapPolyMesh & morphMap, const labelList & faceMap, const labelList & pointMap)
Definition at line 2880 of file addPatchCellLayer.C.
References Foam::faceMap(), forAll, newPointi, PtrList< T >::setSize(), UPtrList< T >::size(), UList< T >::size(), and PtrList< T >::transfer().
The documentation for this class was generated from the following files:
src/dynamicMesh/polyTopoChange/polyTopoChange/addPatchCellLayer.H
src/dynamicMesh/polyTopoChange/polyTopoChange/addPatchCellLayer.C