OpenFOAM: interfaceCompressionLimiter Class Reference
interfaceCompressionLimiter Class Reference
Interface compression scheme currently based on the generic limited scheme although it does not use the NVD/TVD functions.
#include <interfaceCompression.H>
Public Member Functions
interfaceCompressionLimiter (Istream &)
scalar limiter (const scalar cdWeight, const scalar faceFlux, const scalar phiP, const scalar phiN, const vector &, const scalar) const
Detailed Description
Interface compression scheme currently based on the generic limited scheme although it does not use the NVD/TVD functions.
Source files
interfaceCompression.H
interfaceCompression.C
Definition at line 47 of file interfaceCompression.H.
Constructor & Destructor Documentation
interfaceCompressionLimiter()
interfaceCompressionLimiter (Istream &) inline
Definition at line 52 of file interfaceCompression.H.
Member Function Documentation
limiter()
scalar limiter (const scalar cdWeight, const scalar faceFlux, const scalar phiP, const scalar phiN, const vector & , const scalar) const inline
Definition at line 55 of file interfaceCompression.H.
References Foam::clamp(), Foam::max(), and Foam::sqr().
The documentation for this class was generated from the following file:
src/transportModels/interfaceProperties/interfaceCompression/interfaceCompression.H