OpenFOAM: sweepData Class Reference
sweepData Class Reference
Helper class used by fvc::sweep function.
#include <sweepData.H>
Public Member Functions
sweepData (const sweepData &)=default
sweepData & operator= (const sweepData &)=default
sweepData ()
sweepData (const scalar value, const point &origin)
scalar value () const
scalar & value ()
const point & origin () const
template<class TrackingData >
bool valid (TrackingData &td) const
template<class TrackingData >
bool sameGeometry (const polyMesh &, const sweepData &, const scalar, TrackingData &td) const
template<class TrackingData >
void leaveDomain (const polyMesh &, const polyPatch &, const label patchFacei, const point &faceCentre, TrackingData &td)
template<class TrackingData >
void enterDomain (const polyMesh &, const polyPatch &, const label patchFacei, const point &faceCentre, TrackingData &td)
template<class TrackingData >
void transform (const polyMesh &, const tensor &, TrackingData &td)
template<class TrackingData >
bool updateCell (const polyMesh &, const label thisCelli, const label neighbourFacei, const sweepData &svf, const scalar tol, TrackingData &td)
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFacei, const label neighbourCelli, const sweepData &svf, const scalar tol, TrackingData &td)
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFacei, const sweepData &svf, const scalar tol, TrackingData &td)
template<class TrackingData >
bool equal (const sweepData &, TrackingData &td) const
void operator= (const scalar value)
bool operator== (const sweepData &) const
bool operator!= (const sweepData &) const
Friends
Ostream & operator<< (Ostream &os, const sweepData &rhs)
Istream & operator>> (Istream &is, sweepData &rhs)
Detailed Description
Helper class used by fvc::sweep function.
Source files
sweepData.H
sweepData.H
sweepDataI.H
Definition at line 52 of file sweepData.H.
Constructor & Destructor Documentation
sweepData() [1/3]
sweepData (const sweepData &) default
sweepData() [2/3]
sweepData () inline
Definition at line 69 of file sweepDataI.H.
sweepData() [3/3]
sweepData (const scalar value, const point & origin) inline
Definition at line 76 of file sweepDataI.H.
Member Function Documentation
operator=() [1/2]
sweepData & operator= (const sweepData &) default
value() [1/2]
scalar value () const inline
Definition at line 100 of file sweepData.H.
Referenced by sweepData::operator=().
value() [2/2]
scalar & value () inline
Definition at line 106 of file sweepData.H.
origin()
const point & origin () const inline
Definition at line 112 of file sweepData.H.
valid()
template<class TrackingData > bool valid (TrackingData & td) const inline
Definition at line 90 of file sweepDataI.H.
sameGeometry()
template<class TrackingData > bool sameGeometry (const polyMesh & , const sweepData & , const scalar , TrackingData & td) const inline
Definition at line 97 of file sweepDataI.H.
leaveDomain()
template<class TrackingData > void leaveDomain (const polyMesh & , const polyPatch & , const label patchFacei, const point & faceCentre, TrackingData & td) inline
Definition at line 110 of file sweepDataI.H.
enterDomain()
template<class TrackingData > void enterDomain (const polyMesh & , const polyPatch & , const label patchFacei, const point & faceCentre, TrackingData & td) inline
Definition at line 136 of file sweepDataI.H.
transform()
template<class TrackingData > void transform (const polyMesh & , const tensor & rotTensor, TrackingData & td) inline
Definition at line 124 of file sweepDataI.H.
References Foam::transform().
updateCell()
template<class TrackingData > bool updateCell (const polyMesh & mesh, const label thisCelli, const label neighbourFacei, const sweepData & svf, const scalar tol, TrackingData & td) inline
Definition at line 151 of file sweepDataI.H.
References primitiveMesh::cellCentres(), mesh, and update().
updateFace() [1/2]
template<class TrackingData > bool updateFace (const polyMesh & mesh, const label thisFacei, const label neighbourCelli, const sweepData & svf, const scalar tol, TrackingData & td) inline
Definition at line 166 of file sweepDataI.H.
References primitiveMesh::faceCentres(), mesh, and update().
updateFace() [2/2]
template<class TrackingData > bool updateFace (const polyMesh & mesh, const label thisFacei, const sweepData & svf, const scalar tol, TrackingData & td) inline
Definition at line 182 of file sweepDataI.H.
References primitiveMesh::faceCentres(), mesh, and update().
equal()
template<class TrackingData > bool equal (const sweepData & rhs, TrackingData & td) const inline
Definition at line 196 of file sweepDataI.H.
References Foam::operator==().
operator=() [2/2]
void operator= (const scalar value) inline
Definition at line 209 of file sweepData.H.
References sweepData::value().
operator==()
bool operator== (const sweepData & rhs) const inline
Definition at line 208 of file sweepDataI.H.
operator!=()
bool operator!= (const sweepData & rhs) const inline
Definition at line 217 of file sweepDataI.H.
Friends And Related Symbol Documentation
operator<<
Ostream & operator<< (Ostream & os, const sweepData & rhs) friend
Definition at line 223 of file sweepData.H.
operator>>
Istream & operator>> (Istream & is, sweepData & rhs) friend
Definition at line 228 of file sweepData.H.
The documentation for this class was generated from the following files:
src/finiteVolume/finiteVolume/fvc/fvcSmooth/sweepData.H
src/finiteVolume/finiteVolume/fvc/fvcSmooth/sweepDataI.H