OpenFOAM: WenYuDragForce< CloudType > Class Template Reference
WenYuDragForce< CloudType > Class Template Reference
Lagrangian particle models » Submodels » Kinematic » Forces
Particle-drag model wherein drag forces (per unit carrier-fluid velocity) are dynamically computed based on the Wen-Yu drag model.
#include <WenYuDragForce.H>
Public Member Functions
TypeName ("WenYuDrag")
WenYuDragForce (CloudType &owner, const fvMesh &mesh, const dictionary &dict)
WenYuDragForce (const WenYuDragForce< CloudType > &df)
virtual autoPtr< ParticleForce< CloudType > > clone () const
void operator= (const WenYuDragForce< CloudType > &)=delete
virtual ~WenYuDragForce ()=default
virtual forceSuSp calcCoupled (const typename CloudType::parcelType &p, const typename CloudType::parcelType::trackingData &td, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const
Public Member Functions inherited from ParticleForce< CloudType >
TypeName ("particleForce")
declareRunTimeSelectionTable (autoPtr, ParticleForce, dictionary,(CloudType &owner, const fvMesh &mesh, const dictionary &dict),(owner, mesh, dict))
ParticleForce (CloudType &owner, const fvMesh &mesh, const dictionary &dict, const word &forceType, const bool readCoeffs)
ParticleForce (const ParticleForce &pf)
virtual ~ParticleForce ()
const CloudType & owner () const
CloudType & owner ()
const fvMesh & mesh () const
const dictionary & coeffs () const
virtual void cacheFields (const bool store)
virtual forceSuSp calcNonCoupled (const typename CloudType::parcelType &p, const typename CloudType::parcelType::trackingData &td, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const
virtual scalar massAdd (const typename CloudType::parcelType &p, const typename CloudType::parcelType::trackingData &td, const scalar mass) const
Additional Inherited Members
Public Types inherited from ParticleForce< CloudType >
typedef VectorSpace< Vector< vector >, vector, 2 > returnType
Static Public Member Functions inherited from ParticleForce< CloudType >
static autoPtr< ParticleForce< CloudType > > New (CloudType &owner, const fvMesh &mesh, const dictionary &dict, const word &forceType)
Detailed Description
template<class CloudType>
class Foam::WenYuDragForce< CloudType >
Particle-drag model wherein drag forces (per unit carrier-fluid velocity) are dynamically computed based on the Wen-Yu drag model.
with
and
where
= Drag force per carrier-fluid velocity [kg/s]
= Particle drag coefficient
= Particle Reynolds number
= Dynamic viscosity of carrier at the cell occupying particle
= Particle diameter
= Density of carrier at the cell occupying particle
= Relative velocity between particle and carrier
= Volume fraction of the carrier fluid
References:
        Standard model:
            Wen, C. Y., & Yu, Y. H., (1966).
            Mechanics of fluidization.
            Chem. Eng. Prog. Symp. Ser. 62, 100-111.
        Drag-coefficient model:
            Schiller, L., & Naumann, A. (1935).
            Über die grundlegenden Berechnungen bei der Schwerkraftaufbereitung.
            Z. Ver. Dtsch. Ing., 77: 318–326.
        Expressions (tags:ZZB, GLSLR), (Eq.13-14, Table 3):
            Zhou, L., Zhang, L., Bai, L., Shi, W.,
            Li, W., Wang, C., & Agarwal, R. (2017).
            Experimental study and transient CFD/DEM simulation in
            a fluidized bed based on different drag models.
            RSC advances, 7(21), 12764-12774.
            DOI:10.1039/C6RA28615A
            Gao, X., Li, T., Sarkar, A., Lu, L., & Rogers, W. A. (2018).
            Development and validation of an enhanced filtered drag model
            for simulating gas-solid fluidization of Geldart A particles
            in all flow regimes.
            Chemical Engineering Science, 184, 33-51.
            DOI:10.1016/j.ces.2018.03.038
Usage
Minimal example by using constant/<CloudProperties>:
subModels
{
    particleForces
    {
        WenYuDrag
        {
            alphac    <alphacName>; // e.g. alpha.air
        }
    }
}
where the entries mean:
Property Description Type Reqd Deflt
type Type name: WenYuDrag word yes -
alphac Name of carrier fluid word yes -
Note
is weighted with the particle mass/density at the stage of a function return, so that it can later be normalised with the effective mass, if necessary (e.g. when using virtual-mass forces).
Source files
WenYuDragForce.H
WenYuDragForce.C
Definition at line 194 of file WenYuDragForce.H.
Constructor & Destructor Documentation
WenYuDragForce() [1/2]
template<class CloudType > WenYuDragForce (CloudType & owner, const fvMesh & mesh, const dictionary & dict)
Definition at line 42 of file WenYuDragForce.C.
WenYuDragForce() [2/2]
template<class CloudType > WenYuDragForce (const WenYuDragForce< CloudType > & df)
Definition at line 61 of file WenYuDragForce.C.
~WenYuDragForce()
template<class CloudType > virtual ~WenYuDragForce () virtual default
Member Function Documentation
TypeName()
template<class CloudType > TypeName ("WenYuDrag")
clone()
template<class CloudType > virtual autoPtr< ParticleForce< CloudType > > clone () const inline virtual
Reimplemented from ParticleForce< CloudType >.
Definition at line 230 of file WenYuDragForce.H.
operator=()
template<class CloudType > void operator= (const WenYuDragForce< CloudType > &) delete
calcCoupled()
template<class CloudType > Foam::forceSuSp calcCoupled (const typename CloudType::parcelType & p, const typename CloudType::parcelType::trackingData & td, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const virtual
Reimplemented from ParticleForce< CloudType >.
Definition at line 80 of file WenYuDragForce.C.
References p, Foam::pow(), Foam::Re(), Foam::sqr(), and Foam::Zero.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/Kinematic/ParticleForces/Drag/WenYuDrag/WenYuDragForce.H
src/lagrangian/intermediate/submodels/Kinematic/ParticleForces/Drag/WenYuDrag/WenYuDragForce.C