OpenFOAM: dynamicContactAngleForce Class Reference
dynamicContactAngleForce Class Reference
Film-speed or film-temperature dependent contact-angle force with a stochastic perturbation.
#include <dynamicContactAngleForce.H>
Public Member Functions
TypeName ("dynamicContactAngle")
dynamicContactAngleForce (liquidFilmBase &film, const dictionary &dict)
virtual ~dynamicContactAngleForce ()=default
Public Member Functions inherited from contactAngleForce
TypeName ("contactAngle")
contactAngleForce (const word &typeName, liquidFilmBase &film, const dictionary &dict)
virtual ~contactAngleForce ()=default
virtual tmp< faVectorMatrix > correct (areaVectorField &U)
Public Member Functions inherited from force
TypeName ("force")
declareRunTimeSelectionTable (autoPtr, force, dictionary,(liquidFilmBase &film, const dictionary &dict),(film, dict))
force (liquidFilmBase &film)
force (const word &modelType, liquidFilmBase &film, const dictionary &dict)
virtual ~force ()
Public Member Functions inherited from filmSubModelBase
filmSubModelBase (liquidFilmBase &film)
filmSubModelBase (liquidFilmBase &film, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
filmSubModelBase (const word &modelName, liquidFilmBase &film, const dictionary &dict, const word &baseName, const word &modelType)
virtual ~filmSubModelBase ()
virtual bool writeTime () const
const liquidFilmBase & film () const
liquidFilmBase & film ()
template<class FilmType >
const FilmType & filmType () const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
subModelBase (const subModelBase &smb)
virtual ~subModelBase ()=default
const word & modelName () const
const dictionary & dict () const
const word & baseName () const
const word & modelType () const
const dictionary & coeffDict () const
const dictionary & properties () const
virtual bool defaultCoeffs (const bool printMsg) const
virtual bool active () const
virtual void cacheFields (const bool store)
virtual fileName localPath () const
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
bool getModelDict (const word &entryName, dictionary &dict) const
template<class Type >
bool getModelProperty (const word &entryName, Type &value) const
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
virtual void write (Ostream &os) const
Protected Member Functions
virtual tmp< areaScalarField > theta () const
Protected Member Functions inherited from subModelBase
bool inLine () const
Additional Inherited Members
Static Public Member Functions inherited from force
static autoPtr< force > New (liquidFilmBase &film, const dictionary &dict, const word &modelType)
Public Attributes inherited from subModelBase
bool log
Protected Attributes inherited from filmSubModelBase
liquidFilmBase & filmModel_
Protected Attributes inherited from subModelBase
const word modelName_
dictionary & properties_
const dictionary dict_
const word baseName_
const word modelType_
const dictionary coeffDict_
Detailed Description
Film-speed or film-temperature dependent contact-angle force with a stochastic perturbation.
The contact angle in degrees is specified as a Foam::Function1 type, to enable the use of, e.g. constant, polynomial, table values and the stochastic perturbation obtained from a Foam::distributionModels::distributionModel.
Usage
Minimal example:
forces
(
    dynamicContactAngle
);
dynamicContactAngleForceCoeffs
{
    // Mandatory entries
    distribution    <subDict>;
    // Conditional entries
        // Option-1
        Utheta           <Function1<scalar>>;
        // Option-2
        Ttheta           <Function1<scalar>>;
    // Inherited entries
    ...
}
where the entries mean:
Property Description Type Reqd Deflt
dynamicContactAngle Type name word yes -
Utheta
Contact angle as a function of film speed
<Function1<scalar> choice -
Ttheta
Contact angle as a function of film temperature
<Function1<scalar> choice -
distribution Probability distribution model subDict yes -
The inherited entries are elaborated in:
contactAngleForce.H
Function1.H
distributionModel.H
Source files
dynamicContactAngleForce.H
dynamicContactAngleForce.C
Definition at line 135 of file dynamicContactAngleForce.H.
Constructor & Destructor Documentation
dynamicContactAngleForce()
dynamicContactAngleForce (liquidFilmBase & film, const dictionary & dict)
Definition at line 46 of file dynamicContactAngleForce.C.
References Foam::abort(), subModelBase::dict(), Foam::FatalIOError, and FatalIOErrorInFunction.
~dynamicContactAngleForce()
virtual ~dynamicContactAngleForce () virtual default
Member Function Documentation
theta()
tmp< areaScalarField > theta () const protected virtual
Implements contactAngleForce.
Definition at line 94 of file dynamicContactAngleForce.C.
References Foam::dimless, filmSubModelBase::film(), forAll, Foam::mag(), tmp< T >::New(), IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, IOobject::scopedName(), T, dynamicContactAngleForce::theta(), timeName, U, and Foam::Zero.
Referenced by dynamicContactAngleForce::theta().
TypeName()
TypeName ("dynamicContactAngle")
The documentation for this class was generated from the following files:
src/regionFaModels/liquidFilm/subModels/kinematic/force/contactAngleForces/dynamicContactAngleForce/dynamicContactAngleForce.H
src/regionFaModels/liquidFilm/subModels/kinematic/force/contactAngleForces/dynamicContactAngleForce/dynamicContactAngleForce.C