OpenFOAM: atmNutWallFunctionFvPatchScalarField Class Reference
atmNutWallFunctionFvPatchScalarField Class Reference
This boundary condition provides a wall constraint on the turbulent viscosity (i.e. nut) based on the turbulent kinetic energy (i.e. k) and velocity (i.e. U) for atmospheric boundary layer modelling.
#include <atmNutWallFunctionFvPatchScalarField.H>
Public Member Functions
TypeName ("atmNutWallFunction")
atmNutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
atmNutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
atmNutWallFunctionFvPatchScalarField (const atmNutWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
atmNutWallFunctionFvPatchScalarField (const atmNutWallFunctionFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
atmNutWallFunctionFvPatchScalarField (const atmNutWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual void autoMap (const fvPatchFieldMapper &)
virtual void rmap (const fvPatchScalarField &, const labelList &)
virtual void write (Ostream &) const
Public Member Functions inherited from nutkWallFunctionFvPatchScalarField
TypeName ("nutkWallFunction")
nutkWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
nutkWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
nutkWallFunctionFvPatchScalarField (const nutkWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
nutkWallFunctionFvPatchScalarField (const nutkWallFunctionFvPatchScalarField &)
nutkWallFunctionFvPatchScalarField (const nutkWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< scalarField > yPlus () const
Public Member Functions inherited from nutWallFunctionFvPatchScalarField
TypeName ("nutWallFunction")
nutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
nutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &)
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
const wallFunctionCoefficients & wallCoeffs () const noexcept
virtual void updateCoeffs ()
Protected Member Functions
virtual tmp< scalarField > calcNut () const
void writeLocalEntries (Ostream &) const
Protected Member Functions inherited from nutkWallFunctionFvPatchScalarField
void writeLocalEntries (Ostream &) const
Protected Member Functions inherited from nutWallFunctionFvPatchScalarField
virtual const volVectorField & U (const turbulenceModel &turb) const
virtual void checkType ()
void writeLocalEntries (Ostream &) const
Additional Inherited Members
Static Public Member Functions inherited from nutWallFunctionFvPatchScalarField
static const nutWallFunctionFvPatchScalarField & nutw (const turbulenceModel &turbModel, const label patchi)
Protected Attributes inherited from nutWallFunctionFvPatchScalarField
word UName_
wallFunctionCoefficients wallCoeffs_
Detailed Description
This boundary condition provides a wall constraint on the turbulent viscosity (i.e. nut) based on the turbulent kinetic energy (i.e. k) and velocity (i.e. U) for atmospheric boundary layer modelling.
The governing equation of the boundary condition:
with
where
= wall shear stress
= local friction velocity based on near-ground velocity
= local friction velocity based on near-ground k
= von Kármán constant
= near-ground velocity
= vertical coordinate
= surface roughness length [m]
= empirical model constant
= turbulent kinetic energy
References:
        Theoretical expressions (tags:RH, SBJM, SM):
            Richards, P. J., & Hoxey, R. P. (1993).
            Appropriate boundary conditions for computational wind
            engineering models using the k-ε turbulence model.
            In Computational Wind Engineering 1 (pp. 145-153).
            DOI:10.1016/B978-0-444-81688-7.50018-8
            Sørensen, N. N., Bechmann, A., Johansen, J., Myllerup, L.,
            Botha, P., Vinther, S., & Nielsen, B. S. (2007).
            Identification of severe wind conditions using
            a Reynolds Averaged Navier-Stokes solver.
            In Journal of Physics: Conference
            series (Vol. 75, No. 1, p. 012053).
            DOI:10.1088/1742-6596/75/1/012053
            Sumner, J., & Masson, C. (2012).
            k−ε simulations of the neutral atmospheric boundary layer:
            analysis and correction of discretization errors on practical grids.
            International journal for numerical
            methods in fluids, 70(6), 724-741.
            DOI:10.1002/fld.2709
Required fields:
      nut     | Turbulent viscosity      [m2/s]
      k       | Turbulent kinetic energy [m2/s2]
Usage
Example of the boundary condition specification:
<patchName>
{
    // Mandatory entries
    type            atmNutWallFunction;
    z0Min           <scalar>;
    z0              <PatchFunction1<scalar>>;
    // Inherited entries
    ...
}
where the entries mean:
Property Description Type Reqd Deflt
type Type name: nutAtmWallFunction word yes -
z0Min Minimum surface roughness length [m] scalar yes -
z0 Surface roughness length [m] PatchFunction1<scalar> yes -
The inherited entries are elaborated in:
nutkWallFunctionFvPatchScalarField.H
PatchFunction1.H
Source files
atmNutWallFunctionFvPatchScalarField.H
atmNutWallFunctionFvPatchScalarField.C
Definition at line 200 of file atmNutWallFunctionFvPatchScalarField.H.
Constructor & Destructor Documentation
atmNutWallFunctionFvPatchScalarField() [1/5]
atmNutWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 124 of file atmNutWallFunctionFvPatchScalarField.C.
atmNutWallFunctionFvPatchScalarField() [2/5]
atmNutWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 150 of file atmNutWallFunctionFvPatchScalarField.C.
atmNutWallFunctionFvPatchScalarField() [3/5]
atmNutWallFunctionFvPatchScalarField (const atmNutWallFunctionFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 136 of file atmNutWallFunctionFvPatchScalarField.C.
atmNutWallFunctionFvPatchScalarField() [4/5]
atmNutWallFunctionFvPatchScalarField (const atmNutWallFunctionFvPatchScalarField & rwfpsf)
Definition at line 171 of file atmNutWallFunctionFvPatchScalarField.C.
atmNutWallFunctionFvPatchScalarField() [5/5]
atmNutWallFunctionFvPatchScalarField (const atmNutWallFunctionFvPatchScalarField & rwfpsf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 182 of file atmNutWallFunctionFvPatchScalarField.C.
Member Function Documentation
calcNut()
tmp< scalarField > calcNut () const protected virtual
Reimplemented from nutkWallFunctionFvPatchScalarField.
Definition at line 36 of file atmNutWallFunctionFvPatchScalarField.C.
References wallFunctionCoefficients::Cmu(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, IOobject::groupName(), k, wallFunctionCoefficients::kappa(), Foam::log(), Foam::mag(), magUp, Foam::max(), tmp< T >::New(), nutWallFunctionFvPatchScalarField::nutw(), fvPatchField< Type >::patchInternalField(), Foam::pow025(), turbulenceModel::propertiesName, Foam::sqrt(), tauw, nutWallFunctionFvPatchScalarField::wallCoeffs_, and y.
writeLocalEntries()
void writeLocalEntries (Ostream & os) const protected
Definition at line 108 of file atmNutWallFunctionFvPatchScalarField.C.
References os(), and Ostream::writeEntryIfDifferent().
Referenced by atmNutWallFunctionFvPatchScalarField::write().
TypeName()
TypeName ("atmNutWallFunction")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Reimplemented from nutkWallFunctionFvPatchScalarField.
Definition at line 266 of file atmNutWallFunctionFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Reimplemented from nutkWallFunctionFvPatchScalarField.
Definition at line 282 of file atmNutWallFunctionFvPatchScalarField.H.
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Definition at line 196 of file atmNutWallFunctionFvPatchScalarField.C.
rmap()
void rmap (const fvPatchScalarField & ptf, const labelList & addr) virtual
Definition at line 210 of file atmNutWallFunctionFvPatchScalarField.C.
write()
void write (Ostream & os) const virtual
Reimplemented from nutkWallFunctionFvPatchScalarField.
Definition at line 228 of file atmNutWallFunctionFvPatchScalarField.C.
References os(), nutWallFunctionFvPatchScalarField::write(), atmNutWallFunctionFvPatchScalarField::writeLocalEntries(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/atmosphericModels/derivedFvPatchFields/wallFunctions/atmNutWallFunction/atmNutWallFunctionFvPatchScalarField.H
src/atmosphericModels/derivedFvPatchFields/wallFunctions/atmNutWallFunction/atmNutWallFunctionFvPatchScalarField.C