OpenFOAM: NSRDSfunc7 Class Reference
NSRDSfunc7 Class Reference
NSRDS-AICHE function number 107.
#include <NSRDSfunc7.H>
Public Member Functions
TypeName ("NSRDSfunc7")
NSRDSfunc7 (const scalar a, const scalar b, const scalar c, const scalar d, const scalar e)
NSRDSfunc7 (const dictionary &dict)
scalar f (scalar, scalar T) const
void writeData (Ostream &os) const
Public Member Functions inherited from thermophysicalFunction
TypeName ("thermophysicalFunction")
declareRunTimeSelectionTable (autoPtr, thermophysicalFunction, Istream,(Istream &is),(is))
declareRunTimeSelectionTable (autoPtr, thermophysicalFunction, dictionary,(const dictionary &dict),(dict))
thermophysicalFunction ()
virtual ~thermophysicalFunction ()=default
Friends
Ostream & operator<< (Ostream &os, const NSRDSfunc7 &f)
Additional Inherited Members
Static Public Member Functions inherited from thermophysicalFunction
static autoPtr< thermophysicalFunction > New (Istream &is)
static autoPtr< thermophysicalFunction > New (const dictionary &dict)
Detailed Description
NSRDS-AICHE function number 107.
Source:
                  NSRDS - AICHE
             Data Compilation Tables
                of Properties of
                 Pure Compounds
    Design Institute for Physical Property Data
      American Institute of Chemical Engineers
              345 East 47th Street
            New York, New York 10017
     National Standard Reference Data System
     American Institute of Chemical Engineers
      T.E. Daubert       -       R.P. Danner
        Department of Chemical Engineering
        The Pennsylvania State University
            University Park, PA 16802
Definition at line 63 of file NSRDSfunc7.H.
Constructor & Destructor Documentation
NSRDSfunc7() [1/2]
NSRDSfunc7 (const scalar a, const scalar b, const scalar c, const scalar d, const scalar e)
Definition at line 34 of file NSRDSfunc7.C.
NSRDSfunc7() [2/2]
NSRDSfunc7 (const dictionary & dict)
Definition at line 51 of file NSRDSfunc7.C.
Member Function Documentation
TypeName()
TypeName ("NSRDSfunc7")
f()
scalar f (scalar , scalar T) const inline virtual
Implements thermophysicalFunction.
Definition at line 98 of file NSRDSfunc7.H.
References Foam::cosh(), Foam::sinh(), Foam::sqr(), and T.
writeData()
void writeData (Ostream & os) const inline virtual
Implements thermophysicalFunction.
Definition at line 104 of file NSRDSfunc7.H.
References os(), and token::SPACE.
Friends And Related Symbol Documentation
operator<<
Ostream & operator<< (Ostream & os, const NSRDSfunc7 & f) friend
Definition at line 116 of file NSRDSfunc7.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/thermophysicalProperties/thermophysicalFunctions/NSRDSfunctions/NSRDSfunc7/NSRDSfunc7.H
src/thermophysicalModels/thermophysicalProperties/thermophysicalFunctions/NSRDSfunctions/NSRDSfunc7/NSRDSfunc7.C