OpenFOAM: LISAAtomization< CloudType > Class Template Reference
LISAAtomization< CloudType > Class Template Reference
Lagrangian particle models » Submodels » Reacting » Atomization
Primary Breakup Model for pressure swirl atomizers.
#include <LISAAtomization.H>
Public Types
enum SMDMethods { method1 , method2 }
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Public Member Functions
TypeName ("LISA")
LISAAtomization (const dictionary &, CloudType &)
LISAAtomization (const LISAAtomization< CloudType > &am)
virtual autoPtr< AtomizationModel< CloudType > > clone () const
virtual ~LISAAtomization ()
virtual scalar initLiquidCore () const
virtual bool calcChi () const
virtual void update (const scalar dt, scalar &d, scalar &liquidCore, scalar &tc, const scalar rho, const scalar mu, const scalar sigma, const scalar volFlowRate, const scalar rhoAv, const scalar Urel, const vector &pos, const vector &injectionPos, const scalar pAmbient, const scalar chi, Random &rndGen) const
Public Member Functions inherited from AtomizationModel< CloudType >
TypeName ("atomizationModel")
declareRunTimeSelectionTable (autoPtr, AtomizationModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
AtomizationModel (CloudType &owner)
AtomizationModel (const dictionary &dict, CloudType &owner, const word &type)
AtomizationModel (const AtomizationModel< CloudType > &am)
virtual ~AtomizationModel ()
scalar Taverage (const scalar &Tliq, const scalar &Tc) const
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
virtual ~CloudSubModelBase ()=default
const CloudType & owner () const
virtual bool writeTime () const
virtual fileName localPath () const
CloudType & owner ()
virtual void info ()
virtual void write (Ostream &os) const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
subModelBase (const subModelBase &smb)
virtual ~subModelBase ()=default
const word & modelName () const
const dictionary & dict () const
const word & baseName () const
const word & modelType () const
const dictionary & coeffDict () const
const dictionary & properties () const
virtual bool defaultCoeffs (const bool printMsg) const
virtual bool active () const
virtual void cacheFields (const bool store)
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
bool getModelDict (const word &entryName, dictionary &dict) const
template<class Type >
bool getModelProperty (const word &entryName, Type &value) const
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Additional Inherited Members
Static Public Member Functions inherited from AtomizationModel< CloudType >
static autoPtr< AtomizationModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Public Attributes inherited from subModelBase
bool log
Protected Member Functions inherited from subModelBase
bool inLine () const
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Protected Attributes inherited from subModelBase
const word modelName_
dictionary & properties_
const dictionary dict_
const word baseName_
const word modelType_
const dictionary coeffDict_
Detailed Description
template<class CloudType>
class Foam::LISAAtomization< CloudType >
Primary Breakup Model for pressure swirl atomizers.
Accurate description in
P.K. Senecal, D.P. Schmidt, I. Nouar, C.J. Rutland, R.D. Reitz, M. Corradini
"Modeling high-speed viscous liquid sheet atomization"
International Journal of Multiphase Flow 25 (1999) pags. 1073-1097
and
D.P. Schmidt, I. Nouar, P.K. Senecal, C.J. Rutland, J.K. Martin, R.D. Reitz
"Pressure-Swirl Atomization in the Near Field"
SAE Techical Paper Series 1999-01-0496
Definition at line 60 of file LISAAtomization.H.
Member Enumeration Documentation
SMDMethods
template<class CloudType > enum SMDMethods
Enumerator
method1
method2
Definition at line 68 of file LISAAtomization.H.
Constructor & Destructor Documentation
LISAAtomization() [1/2]
template<class CloudType > LISAAtomization (const dictionary & dict, CloudType & owner)
Definition at line 26 of file LISAAtomization.C.
References Foam::endl(), Foam::Info, LISAAtomization< CloudType >::method1, LISAAtomization< CloudType >::method2, and Vector< Cmpt >::normalise().
LISAAtomization() [2/2]
template<class CloudType > LISAAtomization (const LISAAtomization< CloudType > & am)
Definition at line 64 of file LISAAtomization.C.
~LISAAtomization()
template<class CloudType > ~LISAAtomization () virtual
Definition at line 82 of file LISAAtomization.C.
Member Function Documentation
TypeName()
template<class CloudType > TypeName ("LISA")
clone()
template<class CloudType > virtual autoPtr< AtomizationModel< CloudType > > clone () const inline virtual
Implements AtomizationModel< CloudType >.
Definition at line 104 of file LISAAtomization.H.
initLiquidCore()
template<class CloudType > Foam::scalar initLiquidCore () const virtual
Implements AtomizationModel< CloudType >.
Definition at line 89 of file LISAAtomization.C.
calcChi()
template<class CloudType > bool calcChi () const virtual
Implements AtomizationModel< CloudType >.
Definition at line 96 of file LISAAtomization.C.
update()
template<class CloudType > void update (const scalar dt, scalar & d, scalar & liquidCore, scalar & tc, const scalar rho, const scalar mu, const scalar sigma, const scalar volFlowRate, const scalar rhoAv, const scalar Urel, const vector & pos, const vector & injectionPos, const scalar pAmbient, const scalar chi, Random & rndGen) const virtual
Implements AtomizationModel< CloudType >.
Definition at line 103 of file LISAAtomization.C.
References Foam::cbrt(), delta, Foam::diff(), e, h, k, Foam::mag(), Foam::min(), mu, nu, Foam::constant::mathematical::pi(), Foam::pos(), Foam::pow(), Foam::pow3(), Foam::pow4(), rho, Foam::sqr(), Foam::sqrt(), Urel, and x.
The documentation for this class was generated from the following files:
src/lagrangian/spray/submodels/AtomizationModel/LISAAtomization/LISAAtomization.H
src/lagrangian/spray/submodels/AtomizationModel/LISAAtomization/LISAAtomization.C