OpenFOAM: scene Class Reference
scene Class Reference
Main class to assemble glTF components into a scene.
#include <foamGltfScene.H>
Public Member Functions
scene ()
template<class Type >
label addField (const Type &fld, const word &name, const label target=-1)
template<class Type >
label addMesh (const Type &fld, const word &name)
template<class Type >
label addFieldToMesh (const Type &fld, const word &name, const label meshId)
label addColourToMesh (const vectorField &fld, const word &name, const label meshId, const scalarField &alpha=scalarField::null())
label createAnimation (const word &name)
void addToAnimation (const label animationi, const label inputId, const label outputId, const label meshId, const string &interpolation="LINEAR")
void write (const fileName &outputFile)
void write (Ostream &os)
template<class Type >
Foam::label addField (const Type &fld, const word &name, const label target)
template<class Type >
Foam::label addMesh (const Type &fld, const word &name)
template<class Type >
Foam::label addFieldToMesh (const Type &fld, const word &name, const label meshi)
Detailed Description
Main class to assemble glTF components into a scene.
Note
Implements the glTF v2 specification
Source files
foamGltfScene.H
foamGltfScene.C
foamGltfSceneTemplates.C
Definition at line 64 of file foamGltfScene.H.
Constructor & Destructor Documentation
scene()
scene ()
Definition at line 27 of file foamGltfScene.C.
Member Function Documentation
addField() [1/2]
template<class Type > label addField (const Type & fld, const word & name, const label target = -1)
addMesh() [1/2]
template<class Type > label addMesh (const Type & fld, const word & name)
addFieldToMesh() [1/2]
template<class Type > label addFieldToMesh (const Type & fld, const word & name, const label meshId)
addColourToMesh()
Foam::label addColourToMesh (const vectorField & fld, const word & name, const label meshId, const scalarField & alpha = scalarField::null())
Parameters
fld RGB colour field
alpha Alpha channel
Definition at line 60 of file foamGltfScene.C.
References alpha, Foam::glTF::ARRAY_BUFFER, fld(), Foam::glTF::key(), Foam::name(), tmp< T >::New(), PtrList< T >::set(), and UPtrList< T >::size().
createAnimation()
Foam::label createAnimation (const word & name)
Definition at line 110 of file foamGltfScene.C.
References Foam::name(), and UPtrList< T >::size().
addToAnimation()
void addToAnimation (const label animationi, const label inputId, const label outputId, const label meshId, const string & interpolation = "LINEAR")
Definition at line 117 of file foamGltfScene.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and UPtrList< T >::size().
write() [1/2]
void write (const fileName & outputFile)
Definition at line 155 of file foamGltfScene.C.
References Foam::isDir(), Foam::mkDir(), os(), and write().
write() [2/2]
void write (Ostream & os)
Definition at line 172 of file foamGltfScene.C.
References IOstreamOption::BINARY, Foam::decrIndent(), Foam::endl(), forAll, Foam::incrIndent(), Foam::indent(), fileName::name(), Foam::nl, os(), UPtrList< T >::size(), OFstream::stdStream(), and Ostream::write().
addField() [2/2]
template<class Type > Foam::label addField (const Type & fld, const word & name, const label target)
Definition at line 22 of file foamGltfSceneTemplates.C.
References fld(), Foam::name(), PtrList< T >::set(), and UPtrList< T >::size().
addMesh() [2/2]
template<class Type > Foam::label addMesh (const Type & fld, const word & name)
Definition at line 52 of file foamGltfSceneTemplates.C.
References Foam::glTF::ARRAY_BUFFER, fld(), Foam::glTF::key(), Foam::name(), and UPtrList< T >::size().
addFieldToMesh() [2/2]
template<class Type > Foam::label addFieldToMesh (const Type & fld, const word & name, const label meshi)
Definition at line 65 of file foamGltfSceneTemplates.C.
References fld(), and Foam::name().
The documentation for this class was generated from the following files:
src/fileFormats/gltf/foamGltfScene.H
src/fileFormats/gltf/foamGltfScene.C
src/fileFormats/gltf/foamGltfSceneTemplates.C