OpenFOAM: PopeIndex Class Reference
PopeIndex Class Reference
Computes a single-mesh resolution index according to Pope's index, which is used as a LES/DES quality/post-verification metric that does not require any experimental or DNS data.
#include <PopeIndex.H>
Public Member Functions
TypeName ("PopeIndex")
PopeIndex (const word &name, const fvMesh &mesh, const dictionary &dict)
PopeIndex (const PopeIndex &)=delete
void operator= (const PopeIndex &)=delete
virtual ~PopeIndex ()=default
virtual bool read (const dictionary &dict)
virtual bool execute ()
virtual bool write ()
Public Member Functions inherited from resolutionIndexModel
TypeName ("resolutionIndexModel")
declareRunTimeSelectionTable (autoPtr, resolutionIndexModel, dictionary,(const word &name, const fvMesh &mesh, const dictionary &dict),(name, mesh, dict))
resolutionIndexModel (const word &name, const fvMesh &mesh, const dictionary &dict)
resolutionIndexModel (const resolutionIndexModel &)=delete
void operator= (const resolutionIndexModel &)=delete
virtual ~resolutionIndexModel ()=default
const fvMesh & mesh () const noexcept
const word & resultName () const noexcept
Additional Inherited Members
Static Public Member Functions inherited from resolutionIndexModel
static autoPtr< resolutionIndexModel > New (const word &name, const fvMesh &mesh, const dictionary &dict)
Protected Member Functions inherited from resolutionIndexModel
template<class GeoFieldType >
GeoFieldType & getOrReadField (const word &fieldName) const
tmp< volScalarField > V () const
Detailed Description
Computes a single-mesh resolution index according to Pope's index, which is used as a LES/DES quality/post-verification metric that does not require any experimental or DNS data.
with
where
= Pope's index [-]
= Total turbulent kinetic energy [m^2/s^2]
= Resolved turbulent kinetic energy [m^2/s^2]
= Subgrid-scale turbulent kinetic energy [m^2/s^2]
= Numerical turbulent kinetic energy [m^2/s^2]
Inclusion of is optional, and set as true by default:
where
= Empirical constant [-]
= Characteristic length scale with [m]
= Cell volume [m^3]
= Filter length scale [m]
Typical criterion for acceptable-quality resolution:
Required fields:
      U        | Velocity                                   [m/s]
      UMean    | Mean velocity                              [m/s]
      k        | Subgrid-scale turbulent kinetic energy     [m^2/s^2]
      delta    | Filter length                              [m]
References:
        Governing equation (tag:P):
            Pope, S. B. (2000).
            Turbulent flows.
            Cambridge, UK: Cambridge Univ. Press
            DOI:10.1017/CBO9780511840531
        Governing equations for the denominator kNum term (tag:CKJ):
            Celik, I., Klein, M., & Janicka, J. (2009).
            Assessment measures for engineering LES applications.
            Journal of fluids engineering, 131(3).
            DOI:10.1115/1.3059703
Usage
Minimal example by using system/controlDict.functions:
resolutionIndex1
{
    // Inherited entries
    ...
    model       PopeIndex;
    // Optional entries
    U           <word>;
    UMean       <word>;
    k           <word>;
    delta       <word>;
    includeKnum <bool>;
    // Conditional entries
    // when includeKnum = true
    Cn          <scalar>;
}
where the entries mean:
Property Description Type Reqd Deflt
model Model name: PopeIndex word yes -
U Name of velocity field word no U
UMean Name of mean velocity field word no UMean
k
Name of subgrid-scale turbulent kinetic energy field
word no k
delta Name of filter field word no delta
includeKnum Flag to include numerical k field bool no true
Cn Empirical constant choice no 1.0
Note
Some studies measured with comparisons between a LES and a corresponding filtered DNS. Nonphysical results may occur.
Source files
PopeIndex.H
PopeIndex.C
Definition at line 238 of file PopeIndex.H.
Constructor & Destructor Documentation
PopeIndex() [1/2]
PopeIndex (const word & name, const fvMesh & mesh, const dictionary & dict)
Definition at line 54 of file PopeIndex.C.
References dict, and PopeIndex::read().
PopeIndex() [2/2]
PopeIndex (const PopeIndex &) delete
~PopeIndex()
virtual ~PopeIndex () virtual default
Member Function Documentation
TypeName()
TypeName ("PopeIndex")
operator=()
void operator= (const PopeIndex &) delete
read()
bool read (const dictionary & dict) virtual
Reimplemented from resolutionIndexModel.
Definition at line 75 of file PopeIndex.C.
References dict, and resolutionIndexModel::read().
Referenced by PopeIndex::PopeIndex().
execute()
bool execute () virtual
Implements resolutionIndexModel.
Definition at line 96 of file PopeIndex.C.
References Foam::mag(), Foam::magSqr(), Foam::max(), U, and UMean().
write()
bool write () virtual
Implements resolutionIndexModel.
Definition at line 127 of file PopeIndex.C.
References Foam::endl(), Foam::Info, Foam::tab, and Ostream::write().
The documentation for this class was generated from the following files:
src/functionObjects/field/resolutionIndex/resolutionIndexModels/PopeIndex/PopeIndex.H
src/functionObjects/field/resolutionIndex/resolutionIndexModels/PopeIndex/PopeIndex.C