OpenFOAM: linearTsub Class Reference
linearTsub Class Reference
#include <linearTsubDiameter.H>
Public Member Functions
TypeName ("linearTsub")
linearTsub (const dictionary &diameterProperties, const phaseModel &phase)
virtual ~linearTsub ()
virtual tmp< volScalarField > d () const
virtual void correct ()
virtual bool read (const dictionary &phaseProperties)
Public Member Functions inherited from diameterModel
TypeName ("diameterModel")
declareRunTimeSelectionTable (autoPtr, diameterModel, dictionary,(const dictionary &dict, const phaseModel &phase),(dict, phase))
diameterModel (const dictionary &dict, const phaseModel &phase)
virtual ~diameterModel ()=default
const dictionary & diameterProperties () const
const phaseModel & phase () const
TypeName ("diameterModel")
declareRunTimeSelectionTable (autoPtr, diameterModel, dictionary,(const dictionary &dict, const phaseModel &phase),(dict, phase))
diameterModel (const dictionary &dict, const phaseModel &phase)
virtual ~diameterModel ()=default
const dictionary & diameterProperties () const
const phaseModel & phase () const
Additional Inherited Members
Static Public Member Functions inherited from diameterModel
static autoPtr< diameterModel > New (const dictionary &diameterProperties, const phaseModel &phase)
static autoPtr< diameterModel > New (const dictionary &dict, const phaseModel &phase)
Protected Attributes inherited from diameterModel
dictionary diameterProperties_
const phaseModel & phase_
Detailed Description
Definition at line 58 of file linearTsubDiameter.H.
Constructor & Destructor Documentation
linearTsub()
linearTsub (const dictionary & diameterProperties, const phaseModel & phase)
Definition at line 47 of file linearTsubDiameter.C.
References Foam::dimLength, Foam::dimTemperature, and Foam::name().
~linearTsub()
~linearTsub () virtual
Definition at line 92 of file linearTsubDiameter.C.
Member Function Documentation
TypeName()
TypeName ("linearTsub")
d()
Foam::tmp< Foam::volScalarField > d () const virtual
Implements diameterModel.
Definition at line 98 of file linearTsubDiameter.C.
correct()
void correct () virtual
Reimplemented from diameterModel.
Definition at line 104 of file linearTsubDiameter.C.
References fluid, Foam::max(), and Foam::min().
read()
bool read (const dictionary & phaseProperties) virtual
Implements diameterModel.
Definition at line 138 of file linearTsubDiameter.C.
References diameterModel::read().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/diameterModels/linearTsubDiameter/linearTsubDiameter.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/diameterModels/linearTsubDiameter/linearTsubDiameter.C