OpenFOAM: cellDistFuncs Class Reference
cellDistFuncs Class Reference
Collection of functions used in wall distance calculation.
#include <cellDistFuncs.H>
Public Member Functions
ClassName ("cellDistFuncs")
cellDistFuncs (const polyMesh &mesh)
const polyMesh & mesh () const
labelHashSet getPatchIDs (const UList< wordRe > &patchNames) const
template<class Type >
labelHashSet getPatchIDs () const
scalar smallestDist (const point &p, const polyPatch &patch, const labelUList &wallFaces, label &meshFacei) const
void getPointNeighbours (const primitivePatch &, const label patchFacei, DynamicList< label > &) const
label maxPatchSize (const labelHashSet &patchIDs) const
label sumPatchSize (const labelHashSet &patchIDs) const
void correctBoundaryFaceCells (const labelHashSet &patchIDs, scalarField &wallDistCorrected, Map< label > &nearestFace) const
void correctBoundaryPointCells (const labelHashSet &patchIDs, scalarField &wallDistCorrected, Map< label > &nearestFace) const
template<class Type >
Foam::labelHashSet getPatchIDs () const
Detailed Description
Collection of functions used in wall distance calculation.
Source files
cellDistFuncs.H
cellDistFuncs.C
cellDistFuncsTemplates.C
Definition at line 59 of file cellDistFuncs.H.
Constructor & Destructor Documentation
cellDistFuncs()
cellDistFuncs (const polyMesh & mesh)
Definition at line 35 of file cellDistFuncs.C.
Member Function Documentation
ClassName()
ClassName ("cellDistFuncs")
mesh()
const polyMesh & mesh () const inline
Definition at line 88 of file cellDistFuncs.H.
Referenced by wallDistData< TransferType >::correct(), and cellDistFuncs::getPatchIDs().
getPatchIDs() [1/3]
Foam::labelHashSet getPatchIDs (const UList< wordRe > & patchNames) const
Definition at line 43 of file cellDistFuncs.C.
References polyMesh::boundaryMesh(), mesh, and patchNames().
getPatchIDs() [2/3]
template<class Type > labelHashSet getPatchIDs () const
smallestDist()
Foam::scalar smallestDist (const point & p, const polyPatch & patch, const labelUList & wallFaces, label & meshFacei) const
Definition at line 55 of file cellDistFuncs.C.
References p, and points.
getPointNeighbours()
void getPointNeighbours (const primitivePatch & patch, const label patchFacei, DynamicList< label > & neighbours) const
Definition at line 86 of file cellDistFuncs.C.
References Foam::abort(), PtrList< T >::append(), PtrList< T >::clear(), Foam::endl(), f(), Foam::FatalError, FatalErrorInFunction, forAll, SeriousErrorInFunction, UPtrList< T >::size(), and UList< T >::size().
maxPatchSize()
Foam::label maxPatchSize (const labelHashSet & patchIDs) const
Definition at line 181 of file cellDistFuncs.C.
References polyMesh::boundaryMesh(), forAll, Foam::max(), mesh, patchIDs(), and UPtrList< T >::size().
sumPatchSize()
Foam::label sumPatchSize (const labelHashSet & patchIDs) const
Definition at line 202 of file cellDistFuncs.C.
References polyMesh::boundaryMesh(), forAll, mesh, patchIDs(), UPtrList< T >::size(), and Foam::sum().
correctBoundaryFaceCells()
void correctBoundaryFaceCells (const labelHashSet & patchIDs, scalarField & wallDistCorrected, Map< label > & nearestFace) const
Definition at line 224 of file cellDistFuncs.C.
References polyMesh::boundaryMesh(), primitiveMesh::cellCentres(), polyMesh::faceOwner(), forAll, mesh, and patchIDs().
correctBoundaryPointCells()
void correctBoundaryPointCells (const labelHashSet & patchIDs, scalarField & wallDistCorrected, Map< label > & nearestFace) const
Definition at line 270 of file cellDistFuncs.C.
References polyMesh::boundaryMesh(), primitiveMesh::cellCentres(), forAll, mesh, patchIDs(), and primitiveMesh::pointCells().
getPatchIDs() [3/3]
template<class Type > Foam::labelHashSet getPatchIDs () const
Definition at line 29 of file cellDistFuncsTemplates.C.
References forAll, cellDistFuncs::mesh(), patchIDs(), and UPtrList< T >::size().
The documentation for this class was generated from the following files:
src/meshTools/cellDist/cellDistFuncs.H
src/meshTools/cellDist/cellDistFuncs.C
src/meshTools/cellDist/cellDistFuncsTemplates.C