OpenFOAM: clock Class Reference
clock Class Reference
Read access to the system clock with formatting.
#include <clock.H>
Public Member Functions
clock ()
double elapsedClockTime () const
double clockTimeIncrement () const
Static Public Member Functions
static time_t getTime ()
static const struct tm rawDate ()
static std::string dateTime ()
static std::string date ()
static std::string clockTime ()
Detailed Description
Read access to the system clock with formatting.
Source files
clock.H
clock.C
Definition at line 48 of file clock.H.
Constructor & Destructor Documentation
clock()
clock ()
Definition at line 106 of file clock.C.
Member Function Documentation
getTime()
time_t getTime () static
Definition at line 39 of file clock.C.
rawDate()
const struct tm rawDate () static
Definition at line 45 of file clock.C.
References PtrList< T >::PtrList().
dateTime()
std::string dateTime () static
Definition at line 53 of file clock.C.
References os().
Referenced by edgeMeshFormat::write(), OBJedgeFormat::write(), profilingSysInfo::write(), STARCDedgeFormat::writeCase(), STARCDsurfaceFormatCore::writeCase(), VTKsurfaceFormatCore::writeHeader(), and VTPsurfaceFormatCore::writeHeader().
date()
std::string date () static
Definition at line 73 of file clock.C.
References monthNames, and os().
Referenced by argList::parse().
clockTime()
std::string clockTime () static
Definition at line 88 of file clock.C.
References os().
Referenced by argList::parse().
elapsedClockTime()
double elapsedClockTime () const
Definition at line 115 of file clock.C.
clockTimeIncrement()
double clockTimeIncrement () const
Definition at line 122 of file clock.C.
The documentation for this class was generated from the following files:
src/OpenFOAM/global/clock/clock.H
src/OpenFOAM/global/clock/clock.C