OpenFOAM: PatchFunction1< Type > Class Template Reference
PatchFunction1< Type > Class Template Reference abstract
Top level data entry class for use in dictionaries. Provides a mechanism to specify a variable as a certain type, e.g. constant or time varying, and provide functions to return the (interpolated) value, and integral between limits.
#include <PatchFunction1.H>
Public Types
typedef Field< Type > returnType
Public Member Functions
TypeName ("PatchFunction1") declareRunTimeSelectionTable(autoPtr
PatchFunction1 (const polyPatch &pp, const word &entryName, const bool faceValues=true)
PatchFunction1 (const polyPatch &pp, const word &entryName, const dictionary &dict, const bool faceValues=true)
PatchFunction1 (const PatchFunction1< Type > &rhs)
PatchFunction1 (const PatchFunction1< Type > &rhs, const polyPatch &pp)
virtual tmp< PatchFunction1< Type > > clone () const =0
virtual tmp< PatchFunction1< Type > > clone (const polyPatch &pp) const =0
virtual ~PatchFunction1 ()=default
virtual bool constant () const
virtual bool good () const
virtual bool uniform () const =0
virtual tmp< Field< Type > > value (const scalar x) const
virtual tmp< Field< Type > > integrate (const scalar x1, const scalar x2) const
virtual tmp< pointField > localPosition (const pointField &globalPos) const
virtual tmp< Field< Type > > transform (const Field< Type > &fld) const
virtual tmp< Field< Type > > transform (const tmp< Field< Type > > &tfld) const
virtual void autoMap (const FieldMapper &mapper)
virtual void rmap (const PatchFunction1< Type > &rhs, const labelList &addr)
virtual void writeData (Ostream &os) const
Public Member Functions inherited from patchFunction1Base
patchFunction1Base (const polyPatch &pp, const word &entryName, const bool faceValues=true)
patchFunction1Base (const polyPatch &pp, const word &entryName, const dictionary &dict, const bool faceValues=true)
patchFunction1Base (const patchFunction1Base &rhs)
patchFunction1Base (const patchFunction1Base &rhs, const polyPatch &pp)
virtual ~patchFunction1Base ()=default
const word & name () const noexcept
const polyPatch & patch () const noexcept
bool faceValues () const noexcept
label size () const
const objectRegistry * whichDb () const
const objectRegistry & obr () const
const Time & time () const
virtual void userTimeToTime (const Time &t)
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Static Public Member Functions
static autoPtr< PatchFunction1< Type > > New (const polyPatch &pp, const word &entryName, const dictionary &dict, const bool faceValues=true, const bool mandatory=true)
static autoPtr< PatchFunction1< Type > > NewCompat (const polyPatch &pp, const word &entryName, std::initializer_list< std::pair< const char *, int > > compat, const dictionary &dict, const bool faceValues=true, const bool mandatory=true)
static autoPtr< PatchFunction1< Type > > NewIfPresent (const polyPatch &pp, const word &entryName, const dictionary &dict, const bool faceValues=true)
static refPtr< PatchFunction1< Type > > New (HashPtrTable< PatchFunction1< Type > > &cache, const polyPatch &pp, const word &entryName, const dictionary &dict, enum keyType::option matchOpt=keyType::LITERAL, const bool faceValues=true, const bool mandatory=true)
Public Attributes
PatchFunction1
dictionary
const polyPatch & pp
const polyPatch const word & type
const polyPatch const word const word & entryName
const polyPatch const word const word const dictionary & dict
const polyPatch const word const word const dictionary const bool faceValues
const polyPatch const word const word const dictionary const bool pp
const polyPatch const word const word const dictionary const bool type
const polyPatch const word const word const dictionary const bool entryName
const polyPatch const word const word const dictionary const bool dict
Protected Member Functions
void operator= (const PatchFunction1< Type > &)=delete
Protected Member Functions inherited from patchFunction1Base
void operator= (const patchFunction1Base &)=delete
Protected Attributes
coordinateScaling< Type > coordSys_
Protected Attributes inherited from patchFunction1Base
const word name_
const polyPatch & patch_
const bool faceValues_
Friends
Ostream & operator<< (Ostream &os, const PatchFunction1< Type > &rhs)
Detailed Description
template<class Type>
class Foam::PatchFunction1< Type >
Top level data entry class for use in dictionaries. Provides a mechanism to specify a variable as a certain type, e.g. constant or time varying, and provide functions to return the (interpolated) value, and integral between limits.
Extends the Function1 class by adding autoMap and rMap functions
Source files
PatchFunction1.H
PatchFunction1.C
PatchFunction1New.C
See also
Foam::Function1
Definition at line 66 of file PatchFunction1.H.
Member Typedef Documentation
returnType
template<class Type > typedef Field<Type> returnType
Definition at line 103 of file PatchFunction1.H.
Constructor & Destructor Documentation
PatchFunction1() [1/4]
template<class Type > PatchFunction1 (const polyPatch & pp, const word & entryName, const bool faceValues = true)
PatchFunction1() [2/4]
template<class Type > PatchFunction1 (const polyPatch & pp, const word & entryName, const dictionary & dict, const bool faceValues = true)
PatchFunction1() [3/4]
template<class Type > PatchFunction1 (const PatchFunction1< Type > & rhs) explicit
PatchFunction1() [4/4]
template<class Type > PatchFunction1 (const PatchFunction1< Type > & rhs, const polyPatch & pp) explicit
~PatchFunction1()
template<class Type > virtual ~PatchFunction1 () virtual default
Member Function Documentation
operator=()
template<class Type > void operator= (const PatchFunction1< Type > &) protected delete
TypeName()
template<class Type > TypeName ("PatchFunction1< Type >")
clone() [1/2]
template<class Type > virtual tmp< PatchFunction1< Type > > clone () const pure virtual
Implemented in PatchExprField< Type >, Sampled< Type >, CodedField< Type >, ConstantField< Type >, MappedFile< Type >, MappedFile< scalar >, and UniformValueField< Type >.
clone() [2/2]
template<class Type > virtual tmp< PatchFunction1< Type > > clone (const polyPatch & pp) const pure virtual
Implemented in PatchExprField< Type >, Sampled< Type >, CodedField< Type >, ConstantField< Type >, MappedFile< Type >, MappedFile< scalar >, and UniformValueField< Type >.
New() [1/2]
template<class Type > Foam::autoPtr< Foam::PatchFunction1< Type > > New (const polyPatch & pp, const word & entryName, const dictionary & dict, const bool faceValues = true, const bool mandatory = true) static
Definition at line 160 of file PatchFunction1New.C.
NewCompat()
template<class Type > Foam::autoPtr< Foam::PatchFunction1< Type > > NewCompat (const polyPatch & pp, const word & entryName, std::initializer_list< std::pair< const char *, int > > compat, const dictionary & dict, const bool faceValues = true, const bool mandatory = true) static
Definition at line 183 of file PatchFunction1New.C.
NewIfPresent()
template<class Type > Foam::autoPtr< Foam::PatchFunction1< Type > > NewIfPresent (const polyPatch & pp, const word & entryName, const dictionary & dict, const bool faceValues = true) static
Definition at line 207 of file PatchFunction1New.C.
References dict, and pp().
Referenced by turbulentTemperatureCoupledBaffleMixedFvPatchScalarField::turbulentTemperatureCoupledBaffleMixedFvPatchScalarField(), and turbulentTemperatureRadCoupledMixedFvPatchScalarField::turbulentTemperatureRadCoupledMixedFvPatchScalarField().
New() [2/2]
template<class Type > Foam::refPtr< Foam::PatchFunction1< Type > > New (HashPtrTable< PatchFunction1< Type > > & cache, const polyPatch & pp, const word & entryName, const dictionary & dict, enum keyType::option matchOpt = keyType::LITERAL, const bool faceValues = true, const bool mandatory = true) static
Definition at line 222 of file PatchFunction1New.C.
References dict, Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, dictionary::findEntry(), UPtrList< T >::get(), Foam::nl, pp(), and PtrList< T >::set().
constant()
template<class Type > virtual bool constant () const inline virtual
Reimplemented in PatchExprField< Type >, Sampled< Type >, ConstantField< Type >, MappedFile< Type >, MappedFile< scalar >, and UniformValueField< Type >.
Definition at line 218 of file PatchFunction1.H.
good()
template<class Type > virtual bool good () const inline virtual
Reimplemented in UniformValueField< Type >.
Definition at line 221 of file PatchFunction1.H.
uniform()
template<class Type > bool uniform () const pure virtual
Implemented in PatchExprField< Type >, Sampled< Type >, CodedField< Type >, ConstantField< Type >, MappedFile< Type >, MappedFile< scalar >, and UniformValueField< Type >.
Definition at line 76 of file PatchFunction1.C.
Referenced by ConstantField< Type >::uniform(), MappedFile< Type >::uniform(), and UniformValueField< Type >::uniform().
value()
template<class Type > Foam::tmp< Foam::Field< Type > > value (const scalar x) const virtual
Reimplemented in PatchExprField< Type >, Sampled< Type >, CodedField< Type >, ConstantField< Type >, UniformValueField< Type >, MappedFile< Type >, and MappedFile< scalar >.
Definition at line 83 of file PatchFunction1.C.
References NotImplemented.
integrate()
template<class Type > Foam::tmp< Foam::Field< Type > > integrate (const scalar x1, const scalar x2) const virtual
Reimplemented in PatchExprField< Type >, Sampled< Type >, CodedField< Type >, ConstantField< Type >, MappedFile< Type >, MappedFile< scalar >, and UniformValueField< Type >.
Definition at line 94 of file PatchFunction1.C.
References NotImplemented.
localPosition()
template<class Type > Foam::tmp< Foam::pointField > localPosition (const pointField & globalPos) const virtual
Definition at line 107 of file PatchFunction1.C.
transform() [1/2]
template<class Type > Foam::tmp< Foam::Field< Type > > transform (const Field< Type > & fld) const virtual
Definition at line 137 of file PatchFunction1.C.
References fld().
transform() [2/2]
template<class Type > Foam::tmp< Foam::Field< Type > > transform (const tmp< Field< Type > > & tfld) const virtual
Definition at line 114 of file PatchFunction1.C.
References PtrList< T >::clear().
autoMap()
template<class Type > void autoMap (const FieldMapper & mapper) virtual
Reimplemented in PatchExprField< Type >, CodedField< Type >, ConstantField< Type >, MappedFile< Type >, MappedFile< scalar >, and UniformValueField< Type >.
Definition at line 159 of file PatchFunction1.C.
Referenced by PatchExprField< Type >::autoMap(), CodedField< Type >::autoMap(), and MappedFile< Type >::autoMap().
rmap()
template<class Type > void rmap (const PatchFunction1< Type > & rhs, const labelList & addr) virtual
Reimplemented in MappedFile< scalar >, PatchExprField< Type >, CodedField< Type >, ConstantField< Type >, MappedFile< Type >, and UniformValueField< Type >.
Definition at line 164 of file PatchFunction1.C.
Referenced by PatchExprField< Type >::rmap(), CodedField< Type >::rmap(), and MappedFile< Type >::rmap().
writeData()
template<class Type > void writeData (Ostream & os) const virtual
Reimplemented in PatchExprField< Type >, Sampled< Type >, CodedField< Type >, ConstantField< Type >, MappedFile< Type >, MappedFile< scalar >, and UniformValueField< Type >.
Definition at line 173 of file PatchFunction1.C.
References os().
Referenced by Sampled< Type >::writeData(), ConstantField< Type >::writeData(), MappedFile< Type >::writeData(), and UniformValueField< Type >::writeData().
Friends And Related Symbol Documentation
operator<<
template<class Type > Ostream & operator<< (Ostream & os, const PatchFunction1< Type > & rhs) friend
Member Data Documentation
coordSys_
template<class Type > coordinateScaling<Type> coordSys_ protected
Definition at line 89 of file PatchFunction1.H.
PatchFunction1
template<class Type > PatchFunction1
Definition at line 113 of file PatchFunction1.H.
dictionary
template<class Type > dictionary
Definition at line 114 of file PatchFunction1.H.
pp [1/2]
template<class Type > const polyPatch& pp
Definition at line 116 of file PatchFunction1.H.
Referenced by PatchExprField< Type >::clone(), Sampled< Type >::clone(), CodedField< Type >::clone(), ConstantField< Type >::clone(), MappedFile< Type >::clone(), and UniformValueField< Type >::clone().
type [1/2]
template<class Type > const polyPatch const word& type
Definition at line 117 of file PatchFunction1.H.
entryName [1/2]
template<class Type > const polyPatch const word const word& entryName
Definition at line 118 of file PatchFunction1.H.
dict [1/2]
template<class Type > const polyPatch const word const word const dictionary& dict
Definition at line 119 of file PatchFunction1.H.
Referenced by ConstantField< Type >::ConstantField(), and PatchExprField< Type >::PatchExprField().
faceValues
template<class Type > const polyPatch const word const word const dictionary const bool faceValues
Definition at line 120 of file PatchFunction1.H.
Referenced by ConstantField< Type >::ConstantField().
pp [2/2]
template<class Type > const polyPatch const word const word const dictionary const bool pp
Definition at line 122 of file PatchFunction1.H.
type [2/2]
template<class Type > const polyPatch const word const word const dictionary const bool type
Definition at line 122 of file PatchFunction1.H.
entryName [2/2]
template<class Type > const polyPatch const word const word const dictionary const bool entryName
Definition at line 122 of file PatchFunction1.H.
dict [2/2]
template<class Type > const polyPatch const word const word const dictionary const bool dict
Definition at line 122 of file PatchFunction1.H.
The documentation for this class was generated from the following files:
src/meshTools/PatchFunction1/PatchFunction1/PatchFunction1.H
src/meshTools/PatchFunction1/PatchFunction1/PatchFunction1.C
src/meshTools/PatchFunction1/PatchFunction1/PatchFunction1New.C