OpenFOAM: ReactingHeterogeneousParcel< ParcelType > Class Template Reference
ReactingHeterogeneousParcel< ParcelType > Class Template Reference
Lagrangian particle models » Parcels
Reacting heterogeneous Parcel.
#include <ReactingHeterogeneousParcel.H>
Classes
class constantProperties
class iNew
Public Types
typedef ParcelType::trackingData trackingData
Public Member Functions
TypeName ("ReactingHeterogeneousParcel")
AddToPropertyList (ParcelType,+" nReactions(F1..FN)")
ReactingHeterogeneousParcel (const polyMesh &mesh, const barycentric &coordinates, const label celli, const label tetFacei, const label tetPti)
ReactingHeterogeneousParcel (const polyMesh &mesh, const vector &position, const label celli)
ReactingHeterogeneousParcel (const polyMesh &mesh, const barycentric &coordinates, const label celli, const label tetFacei, const label tetPti, const label typeId, const scalar nParticle0, const scalar d0, const scalar dTarget0, const vector &U0, const vector &f0, const vector &angularMomentum0, const vector &torque0, const scalarField &Y, const scalarField &F, const constantProperties &constProps)
ReactingHeterogeneousParcel (const polyMesh &mesh, Istream &is, bool readFields=true, bool newFormat=true)
ReactingHeterogeneousParcel (const ReactingHeterogeneousParcel &p)
ReactingHeterogeneousParcel (const ReactingHeterogeneousParcel &p, const polyMesh &mesh)
virtual autoPtr< particle > clone () const
virtual autoPtr< particle > clone (const polyMesh &mesh) const
const scalarField & F () const
label canCombust () const
scalarField & F ()
label & canCombust ()
template<class TrackCloudType >
void calc (TrackCloudType &cloud, trackingData &td, const scalar dt)
void writeProperties (Ostream &os, const wordRes &filters, const word &delim, const bool namesOnly) const
template<class TrackCloudType >
Foam::scalar CpEff (TrackCloudType &cloud, trackingData &td, const scalar p, const scalar T, const label idS) const
template<class TrackCloudType >
Foam::scalar HsEff (TrackCloudType &cloud, trackingData &td, const scalar p, const scalar T, const label idS) const
template<class TrackCloudType >
Foam::scalar LEff (TrackCloudType &cloud, trackingData &td, const scalar p, const scalar T, const label idS) const
template<class TrackCloudType >
Foam::scalar updatedDeltaVolume (TrackCloudType &cloud, const scalarField &dMass, const scalar p, const scalar T)
Static Public Member Functions
template<class CloudType , class CompositionType >
static void readFields (CloudType &c, const CompositionType &compModel)
template<class CloudType >
static void readFields (CloudType &c)
template<class CloudType , class CompositionType >
static void writeFields (const CloudType &c, const CompositionType &compModel)
template<class CloudType >
static void writeFields (const CloudType &c)
template<class CloudType >
static void readObjects (CloudType &c, const objectRegistry &obr)
template<class CloudType , class CompositionType >
static void readObjects (CloudType &c, const CompositionType &compModel, const objectRegistry &obr)
template<class CloudType >
static void writeObjects (const CloudType &c, objectRegistry &obr)
template<class CloudType , class CompositionType >
static void writeObjects (const CloudType &c, const CompositionType &compModel, objectRegistry &obr)
Static Public Attributes
static const std::size_t sizeofFields
Protected Member Functions
template<class TrackCloudType >
scalar updatedDeltaVolume (TrackCloudType &cloud, const scalarField &dMass, const scalar p, const scalar T)
template<class TrackCloudType >
void calcHeterogeneousReactions (TrackCloudType &cloud, trackingData &td, const scalar dt, const scalar Res, const scalar nu, const scalar d, const scalar T, const scalar mass, const label canCombust, const scalar N, scalar &NCpW, const scalarField &YSolid, scalarField &F, scalarField &dMassSRSolid, scalarField &dMassSRCarrier, scalar &Sh, scalar &dhsTrans) const
Protected Attributes
scalarField F_
label canCombust_
Friends
Ostream & operator<< (Ostream &, const ReactingHeterogeneousParcel< ParcelType > &)
Detailed Description
template<class ParcelType>
class Foam::ReactingHeterogeneousParcel< ParcelType >
Reacting heterogeneous Parcel.
Source files
ReactingHeterogeneousParcel.H
ReactingHeterogeneousParcelI.H
ReactingHeterogeneousParcel.C
ReactingHeterogeneousParcelIO.C
Definition at line 62 of file ReactingHeterogeneousParcel.H.
Member Typedef Documentation
trackingData
template<class ParcelType > typedef ParcelType::trackingData trackingData
Definition at line 105 of file ReactingHeterogeneousParcel.H.
Constructor & Destructor Documentation
ReactingHeterogeneousParcel() [1/6]
template<class ParcelType > ReactingHeterogeneousParcel (const polyMesh & mesh, const barycentric & coordinates, const label celli, const label tetFacei, const label tetPti) inline
Definition at line 57 of file ReactingHeterogeneousParcelI.H.
ReactingHeterogeneousParcel() [2/6]
template<class ParcelType > ReactingHeterogeneousParcel (const polyMesh & mesh, const vector & position, const label celli) inline
Definition at line 73 of file ReactingHeterogeneousParcelI.H.
ReactingHeterogeneousParcel() [3/6]
template<class ParcelType > ReactingHeterogeneousParcel (const polyMesh & mesh, const barycentric & coordinates, const label celli, const label tetFacei, const label tetPti, const label typeId, const scalar nParticle0, const scalar d0, const scalar dTarget0, const vector & U0, const vector & f0, const vector & angularMomentum0, const vector & torque0, const scalarField & Y, const scalarField & F, const constantProperties & constProps) inline
Definition at line 87 of file ReactingHeterogeneousParcelI.H.
ReactingHeterogeneousParcel() [4/6]
template<class ParcelType > ReactingHeterogeneousParcel (const polyMesh & mesh, Istream & is, bool readFields = true, bool newFormat = true)
Definition at line 42 of file ReactingHeterogeneousParcelIO.C.
References ReactingHeterogeneousParcel< ParcelType >::F(), ReactingHeterogeneousParcel< ParcelType >::F_, FUNCTION_NAME, ReactingHeterogeneousParcel< ParcelType >::readFields(), Foam::readFields(), and List< T >::transfer().
ReactingHeterogeneousParcel() [5/6]
template<class ParcelType > ReactingHeterogeneousParcel (const ReactingHeterogeneousParcel< ParcelType > & p)
ReactingHeterogeneousParcel() [6/6]
template<class ParcelType > ReactingHeterogeneousParcel (const ReactingHeterogeneousParcel< ParcelType > & p, const polyMesh & mesh)
Member Function Documentation
updatedDeltaVolume() [1/2]
template<class ParcelType > template<class TrackCloudType > scalar updatedDeltaVolume (TrackCloudType & cloud, const scalarField & dMass, const scalar p, const scalar T) protected
calcHeterogeneousReactions()
template<class ParcelType > template<class TrackCloudType > void calcHeterogeneousReactions (TrackCloudType & cloud, trackingData & td, const scalar dt, const scalar Res, const scalar nu, const scalar d, const scalar T, const scalar mass, const label canCombust, const scalar N, scalar & NCpW, const scalarField & YSolid, scalarField & F, scalarField & dMassSRSolid, scalarField & dMassSRCarrier, scalar & Sh, scalar & dhsTrans) const protected
Definition at line 348 of file ReactingHeterogeneousParcel.C.
References F(), Foam::min(), nu, Foam::Re(), Foam::sum(), and T.
TypeName()
template<class ParcelType > TypeName ("ReactingHeterogeneousParcel< ParcelType >")
AddToPropertyList()
template<class ParcelType > AddToPropertyList (ParcelType , +" nReactions(F1..FN)")
clone() [1/2]
template<class ParcelType > virtual autoPtr< particle > clone () const inline virtual
Definition at line 279 of file ReactingHeterogeneousParcel.H.
clone() [2/2]
template<class ParcelType > virtual autoPtr< particle > clone (const polyMesh & mesh) const inline virtual
Definition at line 285 of file ReactingHeterogeneousParcel.H.
References mesh.
F() [1/2]
template<class ParcelType > const Foam::scalarField & F () const inline
Definition at line 154 of file ReactingHeterogeneousParcelI.H.
Referenced by ReactingHeterogeneousParcel< ParcelType >::ReactingHeterogeneousParcel().
canCombust() [1/2]
template<class ParcelType > Foam::label canCombust () const inline
Definition at line 171 of file ReactingHeterogeneousParcelI.H.
F() [2/2]
template<class ParcelType > Foam::scalarField & F () inline
Definition at line 162 of file ReactingHeterogeneousParcelI.H.
canCombust() [2/2]
template<class ParcelType > Foam::label & canCombust () inline
Definition at line 178 of file ReactingHeterogeneousParcelI.H.
calc()
template<class ParcelType > template<class TrackCloudType > void calc (TrackCloudType & cloud, trackingData & td, const scalar dt)
Definition at line 102 of file ReactingHeterogeneousParcel.C.
References Foam::cbrt(), composition, Cs, forAll, basicSpecieMixture::Hs(), Foam::constant::mathematical::pi(), Foam::pow4(), Foam::Re(), UPtrList< T >::size(), basicMultiComponentMixture::species(), Su, Foam::sum(), T0, and Foam::Zero.
readFields() [1/2]
template<class ParcelType > template<class CloudType , class CompositionType > void readFields (CloudType & c, const CompositionType & compModel) static
Definition at line 77 of file ReactingHeterogeneousParcelIO.C.
References F(), forAll, IOobjectOption::MUST_READ, Foam::name(), p, List< T >::setSize(), UPtrList< T >::size(), solidNames(), Y, and Foam::Zero.
Referenced by ReactingHeterogeneousParcel< ParcelType >::ReactingHeterogeneousParcel().
readFields() [2/2]
template<class ParcelType > template<class CloudType > void readFields (CloudType & c) static
Definition at line 69 of file ReactingHeterogeneousParcelIO.C.
writeFields() [1/2]
template<class ParcelType > template<class CloudType , class CompositionType > void writeFields (const CloudType & c, const CompositionType & compModel) static
Definition at line 171 of file ReactingHeterogeneousParcelIO.C.
References F(), forAll, Foam::name(), IOobjectOption::NO_READ, p, p0, UPtrList< T >::size(), UList< T >::size(), solidNames(), regIOobject::write(), Foam::writeFields(), and Y.
writeFields() [2/2]
template<class ParcelType > template<class CloudType > void writeFields (const CloudType & c) static
Definition at line 160 of file ReactingHeterogeneousParcelIO.C.
writeProperties()
template<class ParcelType > void writeProperties (Ostream & os, const wordRes & filters, const word & delim, const bool namesOnly) const
Definition at line 248 of file ReactingHeterogeneousParcelIO.C.
References os(), and writeProp.
readObjects() [1/2]
template<class ParcelType > template<class CloudType > void readObjects (CloudType & c, const objectRegistry & obr) static
Definition at line 271 of file ReactingHeterogeneousParcelIO.C.
readObjects() [2/2]
template<class ParcelType > template<class CloudType , class CompositionType > void readObjects (CloudType & c, const CompositionType & compModel, const objectRegistry & obr) static
Definition at line 295 of file ReactingHeterogeneousParcelIO.C.
References Foam::nl, and WarningInFunction.
writeObjects() [1/2]
template<class ParcelType > template<class CloudType > void writeObjects (const CloudType & c, objectRegistry & obr) static
Definition at line 283 of file ReactingHeterogeneousParcelIO.C.
writeObjects() [2/2]
template<class ParcelType > template<class CloudType , class CompositionType > void writeObjects (const CloudType & c, const CompositionType & compModel, objectRegistry & obr) static
Definition at line 316 of file ReactingHeterogeneousParcelIO.C.
References F(), forAll, Foam::name(), p0, UPtrList< T >::size(), solidNames(), and Y.
CpEff()
template<class ParcelType > template<class TrackCloudType > Foam::scalar CpEff (TrackCloudType & cloud, trackingData & td, const scalar p, const scalar T, const label idS) const
Definition at line 31 of file ReactingHeterogeneousParcel.C.
References p, and T.
HsEff()
template<class ParcelType > template<class TrackCloudType > Foam::scalar HsEff (TrackCloudType & cloud, trackingData & td, const scalar p, const scalar T, const label idS) const
Definition at line 46 of file ReactingHeterogeneousParcel.C.
References p, and T.
LEff()
template<class ParcelType > template<class TrackCloudType > Foam::scalar LEff (TrackCloudType & cloud, trackingData & td, const scalar p, const scalar T, const label idS) const
Definition at line 61 of file ReactingHeterogeneousParcel.C.
References p, and T.
updatedDeltaVolume() [2/2]
template<class ParcelType > template<class TrackCloudType > Foam::scalar updatedDeltaVolume (TrackCloudType & cloud, const scalarField & dMass, const scalar p, const scalar T)
Definition at line 79 of file ReactingHeterogeneousParcel.C.
References composition, forAll, basicSpecieMixture::rho(), UPtrList< T >::size(), Foam::sum(), and Foam::Zero.
Friends And Related Symbol Documentation
operator<<
template<class ParcelType > Ostream & operator<< (Ostream & , const ReactingHeterogeneousParcel< ParcelType > &) friend
Member Data Documentation
sizeofFields
template<class ParcelType > const std::size_t sizeofFields static
Definition at line 69 of file ReactingHeterogeneousParcel.H.
F_
template<class ParcelType > scalarField F_ protected
Definition at line 153 of file ReactingHeterogeneousParcel.H.
Referenced by ReactingHeterogeneousParcel< ParcelType >::ReactingHeterogeneousParcel().
canCombust_
template<class ParcelType > label canCombust_ protected
Definition at line 161 of file ReactingHeterogeneousParcel.H.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/parcels/Templates/ReactingHeterogeneousParcel/ReactingHeterogeneousParcel.H
src/lagrangian/intermediate/parcels/Templates/ReactingHeterogeneousParcel/ReactingHeterogeneousParcel.C
src/lagrangian/intermediate/parcels/Templates/ReactingHeterogeneousParcel/ReactingHeterogeneousParcelI.H
src/lagrangian/intermediate/parcels/Templates/ReactingHeterogeneousParcel/ReactingHeterogeneousParcelIO.C