OpenFOAM: surfaceDisplacementPointPatchVectorField Class Reference
surfaceDisplacementPointPatchVectorField Class Reference
Displacement fixed by projection onto triSurface. Use in a displacementMotionSolver as a bc on the pointDisplacement field.
#include <surfaceDisplacementPointPatchVectorField.H>
Public Types
enum projectMode { NEAREST , POINTNORMAL , FIXEDNORMAL }
Public Member Functions
TypeName ("surfaceDisplacement")
surfaceDisplacementPointPatchVectorField (const pointPatch &, const DimensionedField< vector, pointMesh > &)
surfaceDisplacementPointPatchVectorField (const pointPatch &, const DimensionedField< vector, pointMesh > &, const dictionary &)
surfaceDisplacementPointPatchVectorField (const surfaceDisplacementPointPatchVectorField &, const pointPatch &, const DimensionedField< vector, pointMesh > &, const pointPatchFieldMapper &)
surfaceDisplacementPointPatchVectorField (const surfaceDisplacementPointPatchVectorField &)
virtual autoPtr< pointPatchVectorField > clone () const
surfaceDisplacementPointPatchVectorField (const surfaceDisplacementPointPatchVectorField &, const DimensionedField< vector, pointMesh > &)
virtual autoPtr< pointPatchVectorField > clone (const DimensionedField< vector, pointMesh > &iF) const
const searchableSurfaces & surfaces () const
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
Displacement fixed by projection onto triSurface. Use in a displacementMotionSolver as a bc on the pointDisplacement field.
Calculates the projection onto the surface according to the projectMode
NEAREST : nearest
POINTNORMAL : intersection with point normal
FIXEDNORMAL : intersection with fixed vector
This displacement is then clipped with the specified velocity * deltaT.
Optionally (intersection only) removes a component ("wedgePlane") to stay in 2D.
Needs:
geometry : dictionary with searchableSurfaces. (usually triSurfaceMeshes in constant/triSurface)
projectMode : see above
projectDirection : if projectMode = fixedNormal
wedgePlane : -1 or component to knock out of intersection normal
frozenPointsZone : empty or name of pointZone containing points that do not move
Source files
surfaceDisplacementPointPatchVectorField.H
surfaceDisplacementPointPatchVectorField.C
Definition at line 72 of file surfaceDisplacementPointPatchVectorField.H.
Member Enumeration Documentation
projectMode
enum projectMode
Enumerator
NEAREST
POINTNORMAL
FIXEDNORMAL
Definition at line 81 of file surfaceDisplacementPointPatchVectorField.H.
Constructor & Destructor Documentation
surfaceDisplacementPointPatchVectorField() [1/5]
surfaceDisplacementPointPatchVectorField (const pointPatch & p, const DimensionedField< vector, pointMesh > & iF)
Definition at line 287 of file surfaceDisplacementPointPatchVectorField.C.
surfaceDisplacementPointPatchVectorField() [2/5]
surfaceDisplacementPointPatchVectorField (const pointPatch & p, const DimensionedField< vector, pointMesh > & iF, const dictionary & dict)
Definition at line 302 of file surfaceDisplacementPointPatchVectorField.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and Foam::nl.
surfaceDisplacementPointPatchVectorField() [3/5]
surfaceDisplacementPointPatchVectorField (const surfaceDisplacementPointPatchVectorField & ppf, const pointPatch & p, const DimensionedField< vector, pointMesh > & iF, const pointPatchFieldMapper & mapper)
Definition at line 329 of file surfaceDisplacementPointPatchVectorField.C.
surfaceDisplacementPointPatchVectorField() [4/5]
surfaceDisplacementPointPatchVectorField (const surfaceDisplacementPointPatchVectorField & ppf)
Definition at line 348 of file surfaceDisplacementPointPatchVectorField.C.
surfaceDisplacementPointPatchVectorField() [5/5]
surfaceDisplacementPointPatchVectorField (const surfaceDisplacementPointPatchVectorField & ppf, const DimensionedField< vector, pointMesh > & iF)
Definition at line 364 of file surfaceDisplacementPointPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("surfaceDisplacement")
clone() [1/2]
virtual autoPtr< pointPatchVectorField > clone () const inline virtual
Definition at line 168 of file surfaceDisplacementPointPatchVectorField.H.
clone() [2/2]
virtual autoPtr< pointPatchVectorField > clone (const DimensionedField< vector, pointMesh > & iF) const inline virtual
Definition at line 187 of file surfaceDisplacementPointPatchVectorField.H.
surfaces()
const Foam::searchableSurfaces & surfaces () const
Definition at line 384 of file surfaceDisplacementPointPatchVectorField.C.
References IOobjectOption::MUST_READ, and IOobjectOption::NO_WRITE.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 411 of file surfaceDisplacementPointPatchVectorField.C.
References forAll, Foam::max(), mesh, Foam::min(), VectorSpace< Form, Cmpt, Ncmpts >::nComponents, Foam::operator==(), and fvMesh::time().
write()
void write (Ostream & os) const virtual
Definition at line 457 of file surfaceDisplacementPointPatchVectorField.C.
References word::null, os(), valuePointPatchField< Type >::write(), Ostream::writeEntry(), and Ostream::writeEntryIfDifferent().
The documentation for this class was generated from the following files:
src/fvMotionSolver/pointPatchFields/derived/surfaceDisplacement/surfaceDisplacementPointPatchVectorField.H
src/fvMotionSolver/pointPatchFields/derived/surfaceDisplacement/surfaceDisplacementPointPatchVectorField.C