OpenFOAM: noDecomp Class Reference
noDecomp Class Reference
A dummy decomposition method, selected as none.
#include <noDecomp.H>
Public Member Functions
TypeNameNoDebug ("none")
noDecomp (const dictionary &decompDict, const word &regionName="")
virtual ~noDecomp ()=default
virtual bool parallelAware () const
virtual labelList decompose (const polyMesh &mesh, const pointField &cc, const scalarField &cWeights) const
virtual labelList decompose (const labelListList &globalCellCells, const pointField &cc, const scalarField &cWeights) const
Public Member Functions inherited from decompositionMethod
TypeName ("decompositionMethod")
declareRunTimeSelectionTable (autoPtr, decompositionMethod, dictionary,(const dictionary &decompDict, const word &regionName),(decompDict, regionName))
decompositionMethod (const dictionary &decompDict, const word &regionName="")
virtual ~decompositionMethod ()=default
label nDomains () const noexcept
virtual labelList decompose (const pointField &points, const scalarField &pointWeights) const
virtual labelList decompose (const pointField &points) const
virtual labelList decompose (const polyMesh &mesh, const pointField &points) const
virtual labelList decompose (const polyMesh &mesh, const labelList &cellToRegion, const pointField &regionPoints, const scalarField &regionWeights) const
virtual labelList decompose (const polyMesh &mesh, const labelList &cellToRegion, const pointField &regionPoints) const
virtual labelList decompose (const labelListList &globalCellCells, const pointField &cc) const
void setConstraints (const polyMesh &mesh, boolList &blockedFace, PtrList< labelList > &specifiedProcessorFaces, labelList &specifiedProcessor, List< labelPair > &explicitConnections) const
void applyConstraints (const polyMesh &mesh, const boolList &blockedFace, const PtrList< labelList > &specifiedProcessorFaces, const labelList &specifiedProcessor, const List< labelPair > &explicitConnections, labelList &finalDecomp) const
virtual labelList decompose (const polyMesh &mesh, const scalarField &cellWeights, const boolList &blockedFace, const PtrList< labelList > &specifiedProcessorFaces, const labelList &specifiedProcessor, const List< labelPair > &explicitConnections) const
labelList decompose (const polyMesh &mesh, const scalarField &cWeights) const
Additional Inherited Members
Static Public Member Functions inherited from decompositionMethod
static label nDomains (const dictionary &decompDict, const word &regionName="")
static const dictionary & optionalRegionDict (const dictionary &decompDict, const word &regionName)
static autoPtr< decompositionMethod > New (const dictionary &decompDict, const word &regionName="")
static void calcCellCells (const polyMesh &mesh, const labelList &agglom, const label nLocalCoarse, const bool global, CompactListList< label > &cellCells)
static void calcCellCells (const polyMesh &mesh, const labelList &agglom, const label nLocalCoarse, const bool parallel, CompactListList< label > &cellCells, CompactListList< scalar > &cellCellWeights)
Protected Types inherited from decompositionMethod
enum selectionType { DEFAULT = 0 , EXACT = 1 , MANDATORY = 2 , NULL_DICT = 4 }
Protected Member Functions inherited from decompositionMethod
const dictionary & findCoeffsDict (const word &coeffsName, int select=selectionType::DEFAULT) const
Static Protected Member Functions inherited from decompositionMethod
static const dictionary & findCoeffsDict (const dictionary &dict, const word &coeffsName, int select=selectionType::DEFAULT)
Protected Attributes inherited from decompositionMethod
const dictionary & decompDict_
const dictionary & decompRegionDict_
label nDomains_
PtrList< decompositionConstraint > constraints_
Detailed Description
A dummy decomposition method, selected as none.
Method coefficients: none
Source files
noDecomp.H
noDecomp.C
Definition at line 47 of file noDecomp.H.
Constructor & Destructor Documentation
noDecomp()
noDecomp (const dictionary & decompDict, const word & regionName = "") explicit
Definition at line 42 of file noDecomp.C.
~noDecomp()
virtual ~noDecomp () virtual default
Member Function Documentation
TypeNameNoDebug()
TypeNameNoDebug ("none")
parallelAware()
virtual bool parallelAware () const inline virtual
Implements decompositionMethod.
Definition at line 83 of file noDecomp.H.
decompose() [1/2]
virtual labelList decompose (const polyMesh & mesh, const pointField & cc, const scalarField & cWeights) const inline virtual
Implements decompositionMethod.
Definition at line 90 of file noDecomp.H.
References UPstream::myProcNo(), and UPtrList< T >::size().
decompose() [2/2]
virtual labelList decompose (const labelListList & globalCellCells, const pointField & cc, const scalarField & cWeights) const inline virtual
Implements decompositionMethod.
Definition at line 107 of file noDecomp.H.
References UPstream::myProcNo(), and UList< T >::size().
The documentation for this class was generated from the following files:
src/parallel/decompose/decompositionMethods/noDecomp/noDecomp.H
src/parallel/decompose/decompositionMethods/noDecomp/noDecomp.C