OpenFOAM: dimFieldDecomposer Class Reference
dimFieldDecomposer Class Reference
Dimensioned field decomposer.
#include <dimFieldDecomposer.H>
Public Member Functions
dimFieldDecomposer (const dimFieldDecomposer &)=delete
void operator= (const dimFieldDecomposer &)=delete
dimFieldDecomposer (const fvMesh &procMesh, const labelList &cellAddressing)
dimFieldDecomposer (const fvMesh &completeMesh, const fvMesh &procMesh, const labelList &faceAddressing, const labelList &cellAddressing)
~dimFieldDecomposer ()=default
template<class Type >
tmp< DimensionedField< Type, volMesh > > decomposeField (const DimensionedField< Type, volMesh > &field) const
template<class GeoField >
void decomposeFields (const PtrList< GeoField > &fields) const
template<class Type >
Foam::tmp< Foam::DimensionedField< Type, Foam::volMesh > > decomposeField (const DimensionedField< Type, volMesh > &field) const
Detailed Description
Dimensioned field decomposer.
Source files
dimFieldDecomposer.H
dimFieldDecomposer.C
dimFieldDecomposerTemplates.C
Definition at line 49 of file dimFieldDecomposer.H.
Constructor & Destructor Documentation
dimFieldDecomposer() [1/3]
dimFieldDecomposer (const dimFieldDecomposer &) delete
dimFieldDecomposer() [2/3]
dimFieldDecomposer (const fvMesh & procMesh, const labelList & cellAddressing)
Definition at line 26 of file dimFieldDecomposer.C.
dimFieldDecomposer() [3/3]
dimFieldDecomposer (const fvMesh & completeMesh, const fvMesh & procMesh, const labelList & faceAddressing, const labelList & cellAddressing)
Parameters
completeMesh unused
faceAddressing unused
Definition at line 37 of file dimFieldDecomposer.C.
~dimFieldDecomposer()
~dimFieldDecomposer () default
Member Function Documentation
operator=()
void operator= (const dimFieldDecomposer &) delete
decomposeField() [1/2]
template<class Type > tmp< DimensionedField< Type, volMesh > > decomposeField (const DimensionedField< Type, volMesh > & field) const
decomposeFields()
template<class GeoField > void decomposeFields (const PtrList< GeoField > & fields) const
Definition at line 57 of file dimFieldDecomposerTemplates.C.
References fields, fld(), and write().
decomposeField() [2/2]
template<class Type > Foam::tmp< Foam::DimensionedField< Type, Foam::volMesh > > decomposeField (const DimensionedField< Type, volMesh > & field) const
Definition at line 28 of file dimFieldDecomposerTemplates.C.
References field(), Foam::New(), IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, and IOobjectOption::NO_WRITE.
The documentation for this class was generated from the following files:
src/parallel/decompose/decompose/dimFieldDecomposer.H
src/parallel/decompose/decompose/dimFieldDecomposer.C
src/parallel/decompose/decompose/dimFieldDecomposerTemplates.C