OpenFOAM: outputOptions Class Reference
outputOptions Class Reference
Encapsulated combinations of output format options. This is primarily useful when defining the output type based on some command-line arguments or dictionary contents. However, it can also be a useful alternative to using the underlying enumeration directly, since this class provides additional methods not possible with an enum.
#include <foamVtkOutputOptions.H>
Public Member Functions
outputOptions ()
outputOptions (enum vtk::formatType fmtType)
outputOptions (enum vtk::formatType fmtType, unsigned prec)
autoPtr< formatter > newFormatter (std::ostream &os) const
vtk::formatType fmt () const noexcept
word ext (vtk::fileTag contentType) const
bool legacy () const noexcept
bool xml () const noexcept
bool append () const noexcept
bool insitu () const noexcept
bool ascii () const noexcept
unsigned precision () const noexcept
outputOptions & ascii (bool on)
outputOptions & append (bool on)
outputOptions & legacy (bool on)
outputOptions & precision (unsigned prec)
string description () const
Detailed Description
Encapsulated combinations of output format options. This is primarily useful when defining the output type based on some command-line arguments or dictionary contents. However, it can also be a useful alternative to using the underlying enumeration directly, since this class provides additional methods not possible with an enum.
Source files
foamVtkOutputOptions.H
foamVtkOutputOptions.C
foamVtkOutputOptionsI.H
Definition at line 55 of file foamVtkOutputOptions.H.
Constructor & Destructor Documentation
outputOptions() [1/3]
outputOptions () inline
Definition at line 23 of file foamVtkOutputOptionsI.H.
References Foam::vtk::INLINE_ASCII.
outputOptions() [2/3]
outputOptions (enum vtk::formatType fmtType) inline
Definition at line 30 of file foamVtkOutputOptionsI.H.
outputOptions() [3/3]
outputOptions (enum vtk::formatType fmtType, unsigned prec) inline
Definition at line 40 of file foamVtkOutputOptionsI.H.
Member Function Documentation
newFormatter()
Foam::autoPtr< Foam::vtk::formatter > newFormatter (std::ostream & os) const inline
Definition at line 54 of file foamVtkOutputOptionsI.H.
References Foam::vtk::newFormatter(), and os().
Referenced by VTKsurfaceFormat< Face >::write(), VTPsurfaceFormat< Face >::write(), VTKsurfaceFormat< Face >::write(), VTPsurfaceFormat< Face >::write(), and Foam::vtk::writePointSet().
fmt()
Foam::vtk::formatType fmt () const inline noexcept
Definition at line 62 of file foamVtkOutputOptionsI.H.
Referenced by vtkWriter::vtkWriter().
ext()
Foam::word ext (vtk::fileTag contentType) const inline
Definition at line 68 of file foamVtkOutputOptionsI.H.
References Foam::vtk::fileExtension, and Foam::vtk::legacy::fileExtension.
Referenced by polyWriter::ext(), internalMeshWriter::ext(), and patchMeshWriter::ext().
legacy() [1/2]
bool legacy () const inline noexcept
Definition at line 79 of file foamVtkOutputOptionsI.H.
References Foam::vtk::LEGACY_ASCII, and Foam::vtk::LEGACY_BINARY.
Referenced by VTPsurfaceFormatCore::formatOptions(), VTKsurfaceFormatCore::formatOptions(), lagrangianWriter::lagrangianWriter(), surfaceFieldWriter::surfaceFieldWriter(), vtkWriter::vtkWriter(), and Foam::vtk::writePointSet().
xml()
bool xml () const inline noexcept
Definition at line 89 of file foamVtkOutputOptionsI.H.
append() [1/2]
bool append () const inline noexcept
Definition at line 95 of file foamVtkOutputOptionsI.H.
References Foam::vtk::APPEND_BASE64, and Foam::vtk::APPEND_BINARY.
Referenced by fileWriter::fileWriter(), VTPsurfaceFormatCore::formatOptions(), VTKsurfaceFormatCore::formatOptions(), internalMeshWriter::internalMeshWriter(), lagrangianWriter::lagrangianWriter(), patchMeshWriter::patchMeshWriter(), polyWriter::polyWriter(), surfaceFieldWriter::surfaceFieldWriter(), and Foam::vtk::writePointSet().
insitu()
bool insitu () const inline noexcept
Definition at line 105 of file foamVtkOutputOptionsI.H.
References append().
ascii() [1/2]
bool ascii () const inline noexcept
Definition at line 111 of file foamVtkOutputOptionsI.H.
Referenced by VTPsurfaceFormatCore::formatOptions(), VTKsurfaceFormatCore::formatOptions(), and vtkWriter::vtkWriter().
precision() [1/2]
unsigned precision () const inline noexcept
Definition at line 117 of file foamVtkOutputOptionsI.H.
Referenced by VTPsurfaceFormatCore::formatOptions(), VTKsurfaceFormatCore::formatOptions(), and VTKedgeFormat::write().
ascii() [2/2]
Foam::vtk::outputOptions & ascii (bool on)
Definition at line 26 of file foamVtkOutputOptions.C.
References Foam::vtk::APPEND_BASE64, Foam::vtk::APPEND_BINARY, Foam::vtk::INLINE_ASCII, Foam::vtk::INLINE_BASE64, Foam::vtk::LEGACY_ASCII, and Foam::vtk::LEGACY_BINARY.
append() [2/2]
Foam::vtk::outputOptions & append (bool on)
Definition at line 74 of file foamVtkOutputOptions.C.
References Foam::vtk::APPEND_BASE64, Foam::vtk::APPEND_BINARY, Foam::vtk::INLINE_ASCII, Foam::vtk::INLINE_BASE64, Foam::vtk::LEGACY_ASCII, and Foam::vtk::LEGACY_BINARY.
legacy() [2/2]
Foam::vtk::outputOptions & legacy (bool on)
Definition at line 116 of file foamVtkOutputOptions.C.
References Foam::vtk::APPEND_BASE64, Foam::vtk::APPEND_BINARY, Foam::vtk::INLINE_ASCII, Foam::vtk::INLINE_BASE64, Foam::vtk::LEGACY_ASCII, and Foam::vtk::LEGACY_BINARY.
precision() [2/2]
Foam::vtk::outputOptions & precision (unsigned prec)
Definition at line 158 of file foamVtkOutputOptions.C.
description()
Foam::string description () const
Definition at line 165 of file foamVtkOutputOptions.C.
References Foam::vtk::APPEND_BASE64, Foam::vtk::APPEND_BINARY, Foam::vtk::INLINE_ASCII, Foam::vtk::INLINE_BASE64, Foam::vtk::LEGACY_ASCII, and Foam::vtk::LEGACY_BINARY.
The documentation for this class was generated from the following files:
src/fileFormats/vtk/output/foamVtkOutputOptions.H
src/fileFormats/vtk/output/foamVtkOutputOptions.C
src/fileFormats/vtk/output/foamVtkOutputOptionsI.H