OpenFOAM: singleCellFvMesh::agglomPatchFieldMapper Class Reference
singleCellFvMesh::agglomPatchFieldMapper Class Reference
#include <singleCellFvMesh.H>
Public Member Functions
agglomPatchFieldMapper (const labelListList &addressing, const scalarListList &weights)
virtual label size () const
virtual bool direct () const
bool hasUnmapped () const
virtual const labelListList & addressing () const
virtual const scalarListList & weights () const
Public Member Functions inherited from fvPatchFieldMapper
fvPatchFieldMapper ()=default
Public Member Functions inherited from FieldMapper
FieldMapper ()=default
virtual ~FieldMapper ()=default
virtual bool distributed () const
virtual const labelUList & directAddressing () const
virtual const mapDistributeBase & distributeMap () const
template<class Type >
tmp< Field< Type > > operator() (const Field< Type > &fld) const
Detailed Description
Definition at line 89 of file singleCellFvMesh.H.
Constructor & Destructor Documentation
agglomPatchFieldMapper()
agglomPatchFieldMapper (const labelListList & addressing, const scalarListList & weights) inline
Definition at line 102 of file singleCellFvMesh.H.
References singleCellFvMesh::agglomPatchFieldMapper::addressing(), and UPtrList< T >::empty().
Member Function Documentation
size()
virtual label size () const inline virtual
Implements FieldMapper.
Definition at line 122 of file singleCellFvMesh.H.
References UList< T >::size().
direct()
virtual bool direct () const inline virtual
Implements FieldMapper.
Definition at line 127 of file singleCellFvMesh.H.
hasUnmapped()
bool hasUnmapped () const inline virtual
Implements FieldMapper.
Definition at line 132 of file singleCellFvMesh.H.
addressing()
virtual const labelListList & addressing () const inline virtual
Reimplemented from FieldMapper.
Definition at line 137 of file singleCellFvMesh.H.
Referenced by singleCellFvMesh::agglomPatchFieldMapper::agglomPatchFieldMapper().
weights()
virtual const scalarListList & weights () const inline virtual
Reimplemented from FieldMapper.
Definition at line 142 of file singleCellFvMesh.H.
The documentation for this class was generated from the following file:
src/finiteVolume/fvMesh/singleCellFvMesh/singleCellFvMesh.H