OpenFOAM: thermalBaffle1DFvPatchScalarField< solidType > Class Template Reference
thermalBaffle1DFvPatchScalarField< solidType > Class Template Reference
Boundary conditions » Thermophysical
This BC solves a steady 1D thermal baffle.
#include <thermalBaffle1DFvPatchScalarField.H>
Public Member Functions
TypeName ("compressible::thermalBaffle1D")
thermalBaffle1DFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
thermalBaffle1DFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
thermalBaffle1DFvPatchScalarField (const thermalBaffle1DFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
thermalBaffle1DFvPatchScalarField (const thermalBaffle1DFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
thermalBaffle1DFvPatchScalarField (const thermalBaffle1DFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual void autoMap (const fvPatchFieldMapper &)
virtual void rmap (const fvPatchScalarField &, const labelList &)
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Public Member Functions inherited from mappedPatchBase
TypeName ("mappedPatchBase")
mappedPatchBase (const polyPatch &)
mappedPatchBase (const polyPatch &pp, const word &sampleRegion, const sampleMode sampleMode, const word &samplePatch, const vectorField &offsets)
mappedPatchBase (const polyPatch &pp, const word &sampleRegion, const sampleMode sampleMode, const word &samplePatch, const vector &uniformOffset)
mappedPatchBase (const polyPatch &pp, const word &sampleRegion, const sampleMode sampleMode, const word &samplePatch, const scalar normalDistance)
mappedPatchBase (const polyPatch &, const dictionary &)
mappedPatchBase (const polyPatch &, const sampleMode, const dictionary &)
mappedPatchBase (const polyPatch &, const mappedPatchBase &)
mappedPatchBase (const polyPatch &, const mappedPatchBase &, const labelUList &mapAddressing)
virtual ~mappedPatchBase ()
void clearOut ()
void setOffset (const scalar normalDist)
void setOffset (const vector &uniformOffset)
void setOffset (const vectorField &offsets)
sampleMode mode () const noexcept
const word & sampleWorld () const noexcept
const word & sampleRegion () const
const word & samplePatch () const
const word & coupleGroup () const
label sampleSize () const
const vector & offset () const noexcept
const vectorField & offsets () const noexcept
label getCommunicator () const
label comm () const
bool sameWorld () const
bool masterWorld () const
bool sameRegion () const noexcept
uniformDimensionedScalarField & updateSampleMeshTime () const
uniformDimensionedScalarField & updateMeshTime () const
bool upToDate () const
const mapDistribute & map () const
const AMIPatchToPatchInterpolation & AMI (const bool forceUpdate=false) const
bool owner () const
const autoPtr< Foam::searchableSurface > & surfPtr () const
const polyMesh & sampleMesh () const
const polyPatch & samplePolyPatch () const
tmp< pointField > samplePoints () const
const fileName & sampleDatabasePath () const
bool sampleDatabase () const
virtual fileName sendPath (const label proci) const
virtual fileName receivePath (const label proci) const
template<class Type >
void distribute (List< Type > &lst) const
template<class Type , class CombineOp >
void distribute (List< Type > &lst, const CombineOp &cop) const
template<class Type >
void reverseDistribute (List< Type > &lst) const
template<class Type , class CombineOp >
void reverseDistribute (List< Type > &lst, const CombineOp &cop) const
Additional Inherited Members
Public Types inherited from mappedPatchBase
enum sampleMode {
NEARESTCELL , NEARESTPATCHFACE , NEARESTPATCHFACEAMI , NEARESTPATCHPOINT ,
NEARESTFACE , NEARESTONLYCELL
}
enum offsetMode { UNIFORM , NONUNIFORM , NORMAL }
typedef Tuple2< pointIndexHit, Tuple2< scalar, label > > nearInfo
typedef Tuple2< nearInfo, label > nearInfoWorld
Static Public Member Functions inherited from mappedPatchBase
static pointIndexHit facePoint (const polyMesh &, const label facei, const polyMesh::cellDecomposition)
static fileName sendPath (const fileName &root, const label proci)
static fileName receivePath (const fileName &root, const label proci)
static const objectRegistry & subRegistry (const objectRegistry &obr, const fileName &path)
template<class Type >
static void storeField (objectRegistry &obr, const word &fieldName, const Field< Type > &values)
static void writeDict (const objectRegistry &obr, dictionary &dict)
static void readDict (const dictionary &d, objectRegistry &obr)
Static Public Attributes inherited from mappedPatchBase
static const Enum< sampleMode > sampleModeNames_
static const Enum< offsetMode > offsetModeNames_
Protected Member Functions inherited from mappedPatchBase
bool addWorldConnection ()
label getWorldCommunicator () const
const polyMesh & lookupMesh (const word &region) const
const polyPatch & lookupPatch (const word &sampleRegion, const word &samplePatch) const
tmp< pointField > facePoints (const polyPatch &) const
void collectSamples (const label mySampleWorld, const pointField &facePoints, pointField &samples, labelList &patchFaceWorlds, labelList &patchFaceProcs, labelList &patchFaces, pointField &patchFc) const
void findLocalSamples (const sampleMode mode, const label sampleWorld, const word &sampleRegion, const word &samplePatch, const pointField &samplePoints, List< nearInfoWorld > &nearest) const
void findSamples (const sampleMode mode, const label myWorldIndex, const pointField &, const labelList &wantedWorlds, const labelList &origProcs, labelList &sampleProcs, labelList &sampleIndices, pointField &sampleLocations) const
tmp< pointField > samplePoints (const pointField &) const
void calcMapping () const
void calcAMI () const
Static Protected Member Functions inherited from mappedPatchBase
static autoPtr< fileName > readDatabase (const dictionary &dict)
static const objectRegistry & subRegistry (const objectRegistry &obr, const wordList &names, const label index)
template<class Type >
static bool writeIOField (const regIOobject &obj, dictionary &dict)
template<class Type >
static bool constructIOField (const word &name, token &tok, Istream &is, objectRegistry &obr)
Protected Attributes inherited from mappedPatchBase
const polyPatch & patch_
word sampleWorld_
word sampleRegion_
const sampleMode mode_
word samplePatch_
const coupleGroupIdentifier coupleGroup_
const autoPtr< fileName > sampleDatabasePtr_
offsetMode offsetMode_
vector offset_
vectorField offsets_
scalar distance_
label communicator_
bool sameRegion_
autoPtr< mapDistribute > mapPtr_
const bool AMIReverse_
autoPtr< AMIPatchToPatchInterpolation > AMIPtr_
autoPtr< searchableSurface > surfPtr_
dictionary surfDict_
autoPtr< uniformDimensionedScalarField > updateMeshTimePtr_
autoPtr< uniformDimensionedScalarField > updateSampleMeshTimePtr_
Detailed Description
template<class solidType>
class Foam::compressible::thermalBaffle1DFvPatchScalarField< solidType >
This BC solves a steady 1D thermal baffle.
The solid properties are specify as dictionary. Optionally radiative heat flux (qr) can be incorporated into the balance. Some under-relaxation might be needed on qr. Baffle and solid properties need to be specified on the master side of the baffle.
Usage
Example of the boundary condition specification using constant solid thermo :
<masterPatchName>
{
    type   compressible::thermalBaffle1D<hConstSolidThermoPhysics>;
    samplePatch     <slavePatchName>;
    thickness       uniform 0.005;  // thickness [m]
    qs              uniform 100;    // heat flux [W/m2]
    qr              none;
    relaxation      1;
    // Solid thermo
    specie
    {
        molWeight       20;
    }
    transport
    {
        kappa           1;
    }
    thermodynamics
    {
        Hf              0;
        Cp              10;
    }
    equationOfState
    {
        rho             10;
    }
    value               uniform 300;
}
<slavePatchName>
{
    type   compressible::thermalBaffle1D<hConstSolidThermoPhysics>;
    samplePatch     <masterPatchName>;
    qr              none;
    relaxation      1;
}
Source files
thermalBaffle1DFvPatchScalarField.H
thermalBaffle1DFvPatchScalarField.C
Definition at line 107 of file thermalBaffle1DFvPatchScalarField.H.
Constructor & Destructor Documentation
thermalBaffle1DFvPatchScalarField() [1/5]
template<class solidType > thermalBaffle1DFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 37 of file thermalBaffle1DFvPatchScalarField.C.
thermalBaffle1DFvPatchScalarField() [2/5]
template<class solidType > thermalBaffle1DFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 83 of file thermalBaffle1DFvPatchScalarField.C.
thermalBaffle1DFvPatchScalarField() [3/5]
template<class solidType > thermalBaffle1DFvPatchScalarField (const thermalBaffle1DFvPatchScalarField< solidType > & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 59 of file thermalBaffle1DFvPatchScalarField.C.
thermalBaffle1DFvPatchScalarField() [4/5]
template<class solidType > thermalBaffle1DFvPatchScalarField (const thermalBaffle1DFvPatchScalarField< solidType > & ptf)
Definition at line 139 of file thermalBaffle1DFvPatchScalarField.C.
thermalBaffle1DFvPatchScalarField() [5/5]
template<class solidType > thermalBaffle1DFvPatchScalarField (const thermalBaffle1DFvPatchScalarField< solidType > & ptf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 160 of file thermalBaffle1DFvPatchScalarField.C.
Member Function Documentation
TypeName()
template<class solidType > TypeName ("compressible::thermalBaffle1D")
clone() [1/2]
template<class solidType > virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 197 of file thermalBaffle1DFvPatchScalarField.H.
clone() [2/2]
template<class solidType > virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 213 of file thermalBaffle1DFvPatchScalarField.H.
autoMap()
template<class solidType > void autoMap (const fvPatchFieldMapper & m) virtual
Definition at line 289 of file thermalBaffle1DFvPatchScalarField.C.
References mappedPatchBase::clearOut().
rmap()
template<class solidType > void rmap (const fvPatchScalarField & ptf, const labelList & addr) virtual
Definition at line 307 of file thermalBaffle1DFvPatchScalarField.C.
updateCoeffs()
template<class solidType > void updateCoeffs () virtual
Definition at line 327 of file thermalBaffle1DFvPatchScalarField.C.
References alpha, Foam::endl(), forAll, Foam::gAverage(), Foam::gMax(), Foam::gMin(), Foam::Info, mappedPatchBase::map(), UPstream::msgType(), turbulenceModel::propertiesName, UList< T >::size(), and Foam::Zero.
write()
template<class solidType > void write (Ostream & os) const virtual
Reimplemented from mappedPatchBase.
Definition at line 419 of file thermalBaffle1DFvPatchScalarField.C.
References os(), mixedFvPatchField< Type >::write(), and mappedPatchBase::write().
The documentation for this class was generated from the following files:
src/thermoTools/derivedFvPatchFields/thermalBaffle1D/thermalBaffle1DFvPatchScalarField.H
src/thermoTools/derivedFvPatchFields/thermalBaffle1D/thermalBaffle1DFvPatchScalarField.C