OpenFOAM: sampledDistanceSurface Class Reference
sampledDistanceSurface Class Reference
A sampledSurface defined by a distance to a surface - resolved using an iso-surface (algorithm: cell, point, topo)
#include <sampledDistanceSurface.H>
Public Member Functions
TypeName ("sampledDistanceSurface")
sampledDistanceSurface (const word &name, const polyMesh &mesh, const dictionary &dict)
sampledDistanceSurface (const word name, const polyMesh &mesh, const bool interpolate, autoPtr< searchableSurface > &&surface, const scalar distance, const bool useSignedDistance)
virtual ~sampledDistanceSurface ()=default
virtual bool needsUpdate () const
virtual bool expire ()
virtual bool update ()
virtual const pointField & points () const
virtual const faceList & faces () const
virtual const labelList & zoneIds () const
virtual const vectorField & Sf () const
virtual const scalarField & magSf () const
virtual const vectorField & Cf () const
virtual tmp< scalarField > sample (const interpolation< scalar > &sampler) const
virtual tmp< vectorField > sample (const interpolation< vector > &sampler) const
virtual tmp< sphericalTensorField > sample (const interpolation< sphericalTensor > &sampler) const
virtual tmp< symmTensorField > sample (const interpolation< symmTensor > &sampler) const
virtual tmp< tensorField > sample (const interpolation< tensor > &sampler) const
virtual tmp< scalarField > interpolate (const interpolation< scalar > &interpolator) const
virtual tmp< vectorField > interpolate (const interpolation< vector > &interpolator) const
virtual tmp< sphericalTensorField > interpolate (const interpolation< sphericalTensor > &interpolator) const
virtual tmp< symmTensorField > interpolate (const interpolation< symmTensor > &interpolator) const
virtual tmp< tensorField > interpolate (const interpolation< tensor > &interpolator) const
virtual void print (Ostream &os, int level=0) const
template<class Type >
Foam::tmp< Foam::Field< Type > > sampleOnFaces (const interpolation< Type > &sampler) const
template<class Type >
Foam::tmp< Foam::Field< Type > > sampleOnPoints (const interpolation< Type > &interpolator) const
template<class Type >
Foam::tmp< Foam::Field< Type > > sampleOnIsoSurfacePoints (const interpolation< Type > &interpolator) const
Public Member Functions inherited from sampledSurface
TypeName ("sampledSurface")
declareRunTimeSelectionTable (autoPtr, sampledSurface, word,(const word &name, const polyMesh &mesh, const dictionary &dict),(name, mesh, dict))
sampledSurface (const word &name, const polyMesh &mesh, const bool interpolateToPoints=false)
sampledSurface (const word &name, const polyMesh &mesh, const dictionary &dict)
autoPtr< sampledSurface > clone () const
virtual ~sampledSurface ()
const polyMesh & mesh () const noexcept
const word & name () const noexcept
bool enabled () const noexcept
bool invariant () const noexcept
bool isPointData () const noexcept
virtual bool isPointData (const bool on)
scalar area () const
virtual bool hasFaceIds () const
polySurface * getRegistrySurface (const objectRegistry &obr, word lookupName="") const
polySurface * storeRegistrySurface (objectRegistry &obr, word lookupName="") const
bool removeRegistrySurface (objectRegistry &obr, word lookupName="") const
template<class Type , class GeoMeshType >
bool storeRegistryField (const objectRegistry &obr, const word &fieldName, const dimensionSet &dims, const Field< Type > &values, word lookupName="") const
template<class Type , class GeoMeshType >
bool storeRegistryField (const objectRegistry &obr, const word &fieldName, const dimensionSet &dims, Field< Type > &&values, word lookupName="") const
virtual bool withSurfaceFields () const
virtual tmp< scalarField > sample (const surfaceScalarField &sField) const
virtual tmp< vectorField > sample (const surfaceVectorField &sField) const
virtual tmp< sphericalTensorField > sample (const surfaceSphericalTensorField &sField) const
virtual tmp< symmTensorField > sample (const surfaceSymmTensorField &sField) const
virtual tmp< tensorField > sample (const surfaceTensorField &sField) const
virtual void rename (const word &newName)
bool interpolate () const noexcept
template<class Type >
Foam::tmp< Foam::Field< Type > > sampleOnFaces (const interpolation< Type > &sampler, const labelUList &elements, const faceList &fcs, const pointField &pts, const Type &defaultValue)
template<class Type >
Foam::tmp< Foam::Field< Type > > sampleOnPoints (const interpolation< Type > &interpolator, const labelUList &elements, const faceList &fcs, const pointField &pts)
template<class Type >
Foam::tmp< Foam::VolumeField< Type > > pointAverage (const PointField< Type > &pfld)
Public Member Functions inherited from meshedSurf
constexpr meshedSurf () noexcept=default
virtual ~meshedSurf ()=default
virtual const labelList & faceIds () const
Public Member Functions inherited from distanceSurface
TypeName ("distanceSurface")
distanceSurface (const word &defaultSurfaceName, const polyMesh &mesh, const dictionary &dict)
distanceSurface (const polyMesh &mesh, const word &surfaceType, const word &surfaceName, const isoSurfaceParams &params=isoSurfaceParams(), const bool interpolate=false)
distanceSurface (const polyMesh &mesh, const bool interpolate, const word &surfaceType, const word &surfaceName, const scalar distance, const bool useSignedDistance, const isoSurfaceParams &params=isoSurfaceParams())
distanceSurface (const polyMesh &mesh, const bool interpolate, autoPtr< searchableSurface > &&surface, const scalar distance, const bool useSignedDistance, const isoSurfaceParams &params=isoSurfaceParams())
virtual ~distanceSurface ()=default
void createGeometry ()
const word & surfaceName () const
scalar distance () const noexcept
const meshedSurface & surface () const
meshedSurface & surface ()
const labelList & meshCells () const
labelList & meshCells ()
void print (Ostream &os, int level=0) const
Additional Inherited Members
Static Public Member Functions inherited from sampledSurface
static autoPtr< sampledSurface > New (const word &name, const polyMesh &mesh, const dictionary &dict)
Protected Member Functions inherited from sampledSurface
virtual void clearGeom () const
sampledSurface (const word &name, std::nullptr_t)
Protected Member Functions inherited from distanceSurface
bool hasIsoSurface () const
template<class Type >
tmp< Field< Type > > isoSurfaceInterpolate (const VolumeField< Type > &cellValues, const Field< Type > &pointValues) const
bool refineBlockedCells (bitSet &ignoreCells, const isoSurfaceBase &isoContext) const
bitSet filterPrepareRegionSplit (const bitSet &ignoreCells) const
void filterKeepLargestRegion (bitSet &ignoreCells) const
void filterKeepNearestRegions (bitSet &ignoreCells) const
void filterRegionProximity (bitSet &ignoreCells) const
void filterFaceProximity ()
Static Protected Member Functions inherited from sampledSurface
template<class Type >
static tmp< Field< Type > > sampleOnFaces (const interpolation< Type > &sampler, const labelUList &elements, const faceList &fcs, const pointField &pts, const Type &defaultValue=Type(Zero))
template<class Type >
static tmp< Field< Type > > sampleOnPoints (const interpolation< Type > &interpolator, const labelUList &elements, const faceList &fcs, const pointField &pts)
template<class Type >
static tmp< VolumeField< Type > > pointAverage (const PointField< Type > &pfld)
Detailed Description
A sampledSurface defined by a distance to a surface - resolved using an iso-surface (algorithm: cell, point, topo)
This is often embedded as part of a sampled surfaces function object.
Usage
Example of function object partial specification:
surfaces
{
    surface1
    {
        type        distanceSurface;
        surfaceType triSurfaceMesh;
        surfaceName something.obj;
        topology    proximity;
    }
}
Where the sub-entries comprise:
Property Description Required Default
type distanceSurface yes
distance distance from surface no 0
signed Use sign when distance is positive no true
isoMethod Iso-algorithm (cell/topo/point) no default
regularise Face simplification (enum or bool) no true
average Cell values from averaged point values no false
bounds Limit with bounding box no
surfaceType Type of surface yes
surfaceName Name of surface in triSurface/ no dict name
topology Topology filter name no none
nearestPoints Points for point-based segmentation no
maxDistance Max search distance for nearestPoints no GREAT
absProximity Max proximity of face centres no 1e-5
Source files
sampledDistanceSurface.H
sampledDistanceSurface.C
sampledDistanceSurfaceTemplates.C
Definition at line 154 of file sampledDistanceSurface.H.
Constructor & Destructor Documentation
sampledDistanceSurface() [1/2]
sampledDistanceSurface (const word & name, const polyMesh & mesh, const dictionary & dict)
Definition at line 46 of file sampledDistanceSurface.C.
References Foam::name().
sampledDistanceSurface() [2/2]
sampledDistanceSurface (const word name, const polyMesh & mesh, const bool interpolate, autoPtr< searchableSurface > && surface, const scalar distance, const bool useSignedDistance)
Definition at line 60 of file sampledDistanceSurface.C.
~sampledDistanceSurface()
virtual ~sampledDistanceSurface () virtual default
Member Function Documentation
TypeName()
TypeName ("sampledDistanceSurface")
needsUpdate()
bool needsUpdate () const virtual
Implements sampledSurface.
Definition at line 86 of file sampledDistanceSurface.C.
expire()
bool expire () virtual
Implements sampledSurface.
Definition at line 92 of file sampledDistanceSurface.C.
References Foam::endl(), and Foam::Pout.
update()
bool update () virtual
Implements sampledSurface.
Definition at line 114 of file sampledDistanceSurface.C.
References distanceSurface::createGeometry(), Foam::endl(), and Foam::Pout.
points()
virtual const pointField & points () const inline virtual
Implements sampledSurface.
Definition at line 240 of file sampledDistanceSurface.H.
References distanceSurface::surface().
Referenced by sampledDistanceSurface::sampleOnFaces().
faces()
virtual const faceList & faces () const inline virtual
Implements sampledSurface.
Definition at line 246 of file sampledDistanceSurface.H.
References distanceSurface::surface().
Referenced by sampledDistanceSurface::sampleOnFaces().
zoneIds()
virtual const labelList & zoneIds () const inline virtual
Reimplemented from meshedSurf.
Definition at line 252 of file sampledDistanceSurface.H.
References List< label >::null().
Sf()
virtual const vectorField & Sf () const inline virtual
Implements sampledSurface.
Definition at line 258 of file sampledDistanceSurface.H.
References distanceSurface::surface().
magSf()
virtual const scalarField & magSf () const inline virtual
Implements sampledSurface.
Definition at line 264 of file sampledDistanceSurface.H.
References distanceSurface::surface().
Cf()
virtual const vectorField & Cf () const inline virtual
Implements sampledSurface.
Definition at line 270 of file sampledDistanceSurface.H.
References distanceSurface::surface().
sample() [1/5]
Foam::tmp< Foam::scalarField > sample (const interpolation< scalar > & sampler) const virtual
Implements sampledSurface.
Definition at line 134 of file sampledDistanceSurface.C.
sample() [2/5]
Foam::tmp< Foam::vectorField > sample (const interpolation< vector > & sampler) const virtual
Implements sampledSurface.
Definition at line 143 of file sampledDistanceSurface.C.
sample() [3/5]
Foam::tmp< Foam::sphericalTensorField > sample (const interpolation< sphericalTensor > & sampler) const virtual
Implements sampledSurface.
Definition at line 152 of file sampledDistanceSurface.C.
sample() [4/5]
Foam::tmp< Foam::symmTensorField > sample (const interpolation< symmTensor > & sampler) const virtual
Implements sampledSurface.
Definition at line 161 of file sampledDistanceSurface.C.
sample() [5/5]
Foam::tmp< Foam::tensorField > sample (const interpolation< tensor > & sampler) const virtual
Implements sampledSurface.
Definition at line 170 of file sampledDistanceSurface.C.
interpolate() [1/5]
Foam::tmp< Foam::scalarField > interpolate (const interpolation< scalar > & interpolator) const virtual
Implements sampledSurface.
Definition at line 179 of file sampledDistanceSurface.C.
interpolate() [2/5]
Foam::tmp< Foam::vectorField > interpolate (const interpolation< vector > & interpolator) const virtual
Implements sampledSurface.
Definition at line 188 of file sampledDistanceSurface.C.
interpolate() [3/5]
Foam::tmp< Foam::sphericalTensorField > interpolate (const interpolation< sphericalTensor > & interpolator) const virtual
Implements sampledSurface.
Definition at line 196 of file sampledDistanceSurface.C.
interpolate() [4/5]
Foam::tmp< Foam::symmTensorField > interpolate (const interpolation< symmTensor > & interpolator) const virtual
Implements sampledSurface.
Definition at line 205 of file sampledDistanceSurface.C.
interpolate() [5/5]
Foam::tmp< Foam::tensorField > interpolate (const interpolation< tensor > & interpolator) const virtual
Implements sampledSurface.
Definition at line 214 of file sampledDistanceSurface.C.
print()
void print (Ostream & os, int level = 0) const virtual
Reimplemented from sampledSurface.
Definition at line 223 of file sampledDistanceSurface.C.
References Foam::name(), os(), and distanceSurface::print().
sampleOnFaces()
template<class Type > Foam::tmp< Foam::Field< Type > > sampleOnFaces (const interpolation< Type > & sampler) const
Definition at line 31 of file sampledDistanceSurfaceTemplates.C.
References sampledDistanceSurface::faces(), distanceSurface::meshCells(), sampledDistanceSurface::points(), and sampledSurface::sampleOnFaces().
sampleOnPoints()
template<class Type > Foam::tmp< Foam::Field< Type > > sampleOnPoints (const interpolation< Type > & interpolator) const
Definition at line 48 of file sampledDistanceSurfaceTemplates.C.
References points, and sampledSurface::sampleOnPoints().
sampleOnIsoSurfacePoints()
template<class Type > Foam::tmp< Foam::Field< Type > > sampleOnIsoSurfacePoints (const interpolation< Type > & interpolator) const
Definition at line 70 of file sampledDistanceSurfaceTemplates.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::interpolate(), mesh, MeshObject< fvMesh, UpdateableMeshObject, volPointInterpolation >::New(), and Foam::nl.
The documentation for this class was generated from the following files:
src/sampling/sampledSurface/distanceSurface/sampledDistanceSurface.H
src/sampling/sampledSurface/distanceSurface/sampledDistanceSurface.C
src/sampling/sampledSurface/distanceSurface/sampledDistanceSurfaceTemplates.C