OpenFOAM: dynamicLagrangian< BasicTurbulenceModel > Class Template Reference
dynamicLagrangian< BasicTurbulenceModel > Class Template Reference
Turbulence models » LES turbulence
Dynamic SGS model with Lagrangian averaging.
#include <dynamicLagrangian.H>
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from LESeddyViscosity< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from eddyViscosity< LESModel< BasicTurbulenceModel > >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from linearViscousStress< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("dynamicLagrangian")
dynamicLagrangian (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
virtual ~dynamicLagrangian ()=default
virtual bool read ()
tmp< volScalarField > k (const tmp< volTensorField > &gradU) const
virtual tmp< volScalarField > k () const
tmp< volScalarField > DkEff () const
virtual void correct ()
Public Member Functions inherited from LESeddyViscosity< BasicTurbulenceModel >
LESeddyViscosity (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
virtual ~LESeddyViscosity ()=default
Public Member Functions inherited from eddyViscosity< LESModel< BasicTurbulenceModel > >
eddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~eddyViscosity ()=default
virtual tmp< volScalarField > nut () const
virtual tmp< scalarField > nut (const label patchi) const
virtual tmp< volSymmTensorField > R () const
virtual void validate ()
Public Member Functions inherited from linearViscousStress< BasicTurbulenceModel >
linearViscousStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~linearViscousStress ()=default
virtual tmp< volSymmTensorField > devRhoReff () const
virtual tmp< volSymmTensorField > devRhoReff (const volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Protected Member Functions
void correctNut (const tmp< volTensorField > &gradU)
virtual void correctNut ()
Protected Attributes
volScalarField flm_
volScalarField fmm_
dimensionedScalar theta_
simpleFilter simpleFilter_
autoPtr< LESfilter > filterPtr_
LESfilter & filter_
dimensionedScalar flm0_
dimensionedScalar fmm0_
Protected Attributes inherited from eddyViscosity< LESModel< BasicTurbulenceModel > >
volScalarField nut_
Detailed Description
template<class BasicTurbulenceModel>
class Foam::LESModels::dynamicLagrangian< BasicTurbulenceModel >
Dynamic SGS model with Lagrangian averaging.
Reference:
    Meneveau, C., Lund, T. S., & Cabot, W. H. (1996).
    A Lagrangian dynamic subgrid-scale model of turbulence.
    Journal of Fluid Mechanics, 319, 353-385.
Source files
dynamicLagrangian.H
dynamicLagrangian.C
Definition at line 61 of file dynamicLagrangian.H.
Member Typedef Documentation
alphaField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 101 of file dynamicLagrangian.H.
rhoField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 102 of file dynamicLagrangian.H.
transportModel
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 103 of file dynamicLagrangian.H.
Constructor & Destructor Documentation
dynamicLagrangian()
template<class BasicTurbulenceModel > dynamicLagrangian (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Definition at line 58 of file dynamicLagrangian.C.
References Foam::type().
~dynamicLagrangian()
template<class BasicTurbulenceModel > virtual ~dynamicLagrangian () virtual default
Member Function Documentation
correctNut() [1/2]
template<class BasicTurbulenceModel > void correctNut (const tmp< volTensorField > & gradU) protected
Definition at line 35 of file dynamicLagrangian.C.
References delta, Foam::devSymm(), Foam::mag(), options::New(), and Foam::sqr().
correctNut() [2/2]
template<class BasicTurbulenceModel > void correctNut () protected virtual
Implements eddyViscosity< LESModel< BasicTurbulenceModel > >.
Definition at line 49 of file dynamicLagrangian.C.
References Foam::fvc::grad().
TypeName()
template<class BasicTurbulenceModel > TypeName ("dynamicLagrangian< BasicTurbulenceModel >")
read()
template<class BasicTurbulenceModel > bool read () virtual
Reimplemented from LESeddyViscosity< BasicTurbulenceModel >.
Definition at line 133 of file dynamicLagrangian.C.
k() [1/2]
template<class BasicTurbulenceModel > tmp< volScalarField > k (const tmp< volTensorField > & gradU) const inline
Definition at line 135 of file dynamicLagrangian.H.
References delta, Foam::dev(), dynamicLagrangian< BasicTurbulenceModel >::flm_, dynamicLagrangian< BasicTurbulenceModel >::fmm_, Foam::magSqr(), Foam::pow(), Foam::sqr(), and Foam::symm().
k() [2/2]
template<class BasicTurbulenceModel > virtual tmp< volScalarField > k () const inline virtual
Implements eddyViscosity< LESModel< BasicTurbulenceModel > >.
Definition at line 144 of file dynamicLagrangian.H.
References Foam::fvc::grad(), and dynamicLagrangian< BasicTurbulenceModel >::k().
Referenced by dynamicLagrangian< BasicTurbulenceModel >::k().
DkEff()
template<class BasicTurbulenceModel > tmp< volScalarField > DkEff () const inline
Definition at line 150 of file dynamicLagrangian.H.
References nu, and eddyViscosity< LESModel< BasicTurbulenceModel > >::nut_.
correct()
template<class BasicTurbulenceModel > void correct () virtual
Implements eddyViscosity< LESModel< BasicTurbulenceModel > >.
Definition at line 148 of file dynamicLagrangian.C.
References alpha, Foam::bound(), linearViscousStress< BasicTurbulenceModel >::correct(), Foam::fvm::ddt(), delta, Foam::dev(), Foam::devSymm(), Foam::fvm::div(), fvOptions, Foam::fvc::grad(), L, M, Foam::mag(), options::New(), Foam::pow(), rho, Foam::fvm::Sp(), Foam::sqr(), U, and Uf.
Member Data Documentation
flm_
template<class BasicTurbulenceModel > volScalarField flm_ protected
Definition at line 78 of file dynamicLagrangian.H.
Referenced by dynamicLagrangian< BasicTurbulenceModel >::k().
fmm_
template<class BasicTurbulenceModel > volScalarField fmm_ protected
Definition at line 79 of file dynamicLagrangian.H.
Referenced by dynamicLagrangian< BasicTurbulenceModel >::k().
theta_
template<class BasicTurbulenceModel > dimensionedScalar theta_ protected
Definition at line 81 of file dynamicLagrangian.H.
simpleFilter_
template<class BasicTurbulenceModel > simpleFilter simpleFilter_ protected
Definition at line 83 of file dynamicLagrangian.H.
filterPtr_
template<class BasicTurbulenceModel > autoPtr<LESfilter> filterPtr_ protected
Definition at line 84 of file dynamicLagrangian.H.
filter_
template<class BasicTurbulenceModel > LESfilter& filter_ protected
Definition at line 85 of file dynamicLagrangian.H.
flm0_
template<class BasicTurbulenceModel > dimensionedScalar flm0_ protected
Definition at line 87 of file dynamicLagrangian.H.
fmm0_
template<class BasicTurbulenceModel > dimensionedScalar fmm0_ protected
Definition at line 88 of file dynamicLagrangian.H.
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/LES/dynamicLagrangian/dynamicLagrangian.H
src/TurbulenceModels/turbulenceModels/LES/dynamicLagrangian/dynamicLagrangian.C