OpenFOAM: exprResultStack Class Reference
exprResultStack Class Reference
A stack of polymorphic fields. Can be used to build a list of results one at a time.
#include <exprResultStack.H>
Public Member Functions
TypeName ("exprResultStack")
exprResultStack ()
exprResultStack (const exprResultStack &rhs)
exprResultStack (const dictionary &dict)
virtual autoPtr< exprResult > clone () const
virtual ~exprResultStack ()=default
exprResult pop ()
void push (const exprResult &result)
void operator= (const exprResultStack &rhs)
void operator= (const exprResult &rhs)
Public Member Functions inherited from exprResult
TypeName ("exprResult")
declareRunTimeSelectionTable (autoPtr, exprResult, dictionary,(const dictionary &dict),(dict))
declareRunTimeSelectionTable (autoPtr, exprResult, empty,(),())
exprResult ()
exprResult (const exprResult &expr)
exprResult (exprResult &&expr)
exprResult (const dictionary &dict, const bool uniform=false, const bool needsValue=false)
exprResult (Istream &is)
template<class Type >
exprResult (const Field< Type > &fld)
template<class Type >
exprResult (Field< Type > &&fld)
template<class Type >
exprResult (autoPtr< Type > &&obj)
template<class Type >
exprResult (const dimensioned< Type > &dt)
exprResult (const bool &val)
Construct from single value of bool.
exprResult (const scalar &val)
Construct from single value of scalar.
exprResult (const vector &val)
Construct from single value of vector.
exprResult (const tensor &val)
Construct from single value of tensor.
exprResult (const symmTensor &val)
Construct from single value of symmTensor.
exprResult (const sphericalTensor &val)
Construct from single value of sphericalTensor.
virtual ~exprResult ()
bool hasValue () const
const word & valueType () const noexcept
bool isPointData (const bool wantPointData=true) const
bool isUniform () const
template<class Type >
bool isType () const
template<class Type >
Type getValue () const
bool is_bool () const
label size () const
const void * dataAddress () const
void clear ()
void noReset () noexcept
void allowReset () noexcept
void testIfSingleValue (const bool parRun=Pstream::parRun())
template<class Type >
void setResult (Field< Type > *, bool wantPointData=false)
template<class Type >
void setResult (const Field< Type > &, bool wantPointData=false)
template<class Type >
void setResult (Field< Type > &&, bool wantPointData=false)
template<class Type >
void setResult (const Type &val, const label size)
template<class Type >
void setSingleValue (const Type &val)
template<class Type >
const Field< Type > & cref () const
template<class Type >
Field< Type > & ref ()
template<class Type >
Field< Type > & constCast () const
template<class Type >
tmp< Field< Type > > getResult (bool cacheCopy=false)
exprResult getUniform (const label size, const bool noWarn, const bool parRun=Pstream::parRun()) const
template<template< class > class BinaryOp, class Type >
Type getReduced (const BinaryOp< Type > &bop, const Type &initial=pTraits< Type >::zero)
void writeEntry (const word &keyword, Ostream &os) const
void writeDict (Ostream &os, const bool subDict=true) const
void writeField (Ostream &os, const word &keyword="") const
void writeValue (Ostream &os) const
virtual void operator= (exprResult &&rhs)
exprResult & operator*= (const scalar &b)
exprResult & operator+= (const exprResult &b)
template<class Type >
Foam::tmp< Foam::Field< Type > > getResult (bool cacheCopy)
template<class Type >
const Foam::Field< Type > & cref () const
template<class Type >
Foam::Field< Type > & ref ()
template<class Type >
Foam::Field< Type > & constCast () const
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Additional Inherited Members
Static Public Member Functions inherited from exprResult
static autoPtr< exprResult > New (const dictionary &dict)
static autoPtr< exprResult > New (Istream &is)
Static Public Attributes inherited from exprResult
static const exprResult null
Protected Member Functions inherited from exprResult
virtual expressions::exprResult & target ()
virtual void resetImpl ()
bool reset (bool force=false)
void needsReset (bool val)
Detailed Description
A stack of polymorphic fields. Can be used to build a list of results one at a time.
Source files
exprResultStack.H
exprResultStack.C
exprResultStackTemplates.C
Definition at line 51 of file exprResultStack.H.
Constructor & Destructor Documentation
exprResultStack() [1/3]
exprResultStack ()
Definition at line 56 of file exprResultStack.C.
References exprResult::needsReset().
Referenced by exprResultStack::clone().
exprResultStack() [2/3]
exprResultStack (const exprResultStack & rhs)
Definition at line 64 of file exprResultStack.C.
References exprResult::needsReset().
exprResultStack() [3/3]
exprResultStack (const dictionary & dict) explicit
Definition at line 75 of file exprResultStack.C.
References exprResult::needsReset().
~exprResultStack()
virtual ~exprResultStack () virtual default
Member Function Documentation
TypeName()
TypeName ("exprResultStack")
clone()
virtual autoPtr< exprResult > clone () const inline virtual
Reimplemented from exprResult.
Reimplemented in exprResultStoredStack.
Definition at line 88 of file exprResultStack.H.
References exprResultStack::exprResultStack().
pop()
Foam::expressions::exprResult pop ()
Definition at line 89 of file exprResultStack.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, and Foam::nl.
push()
void push (const exprResult & result)
Definition at line 122 of file exprResultStack.C.
References Foam::abort(), DebugInFunction, Foam::FatalError, FatalErrorInFunction, Foam::nl, exprResult::operator=(), and exprResult::valueType().
operator=() [1/2]
void operator= (const exprResultStack & rhs)
Definition at line 164 of file exprResultStack.C.
Referenced by exprResultStoredStack::operator=().
operator=() [2/2]
void operator= (const exprResult & rhs) virtual
Reimplemented from exprResult.
Definition at line 178 of file exprResultStack.C.
References DebugInFunction, and Foam::nl.
The documentation for this class was generated from the following files:
src/OpenFOAM/expressions/exprResult/exprResultStack.H
src/OpenFOAM/expressions/exprResult/exprResultStack.C
src/OpenFOAM/expressions/exprResult/exprResultStackTemplates.C