OpenFOAM: inclinedFilmNusseltInletVelocityFvPatchVectorField Class Reference
inclinedFilmNusseltInletVelocityFvPatchVectorField Class Reference
Film velocity boundary condition for inclined films that imposes a sinusoidal perturbation on top of a mean flow rate, where the velocity is calculated using the Nusselt solution.
#include <inclinedFilmNusseltInletVelocityFvPatchVectorField.H>
Public Member Functions
TypeName ("inclinedFilmNusseltInletVelocity")
inclinedFilmNusseltInletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
inclinedFilmNusseltInletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
inclinedFilmNusseltInletVelocityFvPatchVectorField (const inclinedFilmNusseltInletVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
inclinedFilmNusseltInletVelocityFvPatchVectorField (const inclinedFilmNusseltInletVelocityFvPatchVectorField &)
virtual tmp< fvPatchVectorField > clone () const
inclinedFilmNusseltInletVelocityFvPatchVectorField (const inclinedFilmNusseltInletVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
Film velocity boundary condition for inclined films that imposes a sinusoidal perturbation on top of a mean flow rate, where the velocity is calculated using the Nusselt solution.
Source files
inclinedFilmNusseltInletVelocityFvPatchVectorField.H
inclinedFilmNusseltInletVelocityFvPatchVectorField.C
Definition at line 50 of file inclinedFilmNusseltInletVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
inclinedFilmNusseltInletVelocityFvPatchVectorField() [1/5]
inclinedFilmNusseltInletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Definition at line 29 of file inclinedFilmNusseltInletVelocityFvPatchVectorField.C.
inclinedFilmNusseltInletVelocityFvPatchVectorField() [2/5]
inclinedFilmNusseltInletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Definition at line 61 of file inclinedFilmNusseltInletVelocityFvPatchVectorField.C.
inclinedFilmNusseltInletVelocityFvPatchVectorField() [3/5]
inclinedFilmNusseltInletVelocityFvPatchVectorField (const inclinedFilmNusseltInletVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 44 of file inclinedFilmNusseltInletVelocityFvPatchVectorField.C.
inclinedFilmNusseltInletVelocityFvPatchVectorField() [4/5]
inclinedFilmNusseltInletVelocityFvPatchVectorField (const inclinedFilmNusseltInletVelocityFvPatchVectorField & fmfrpvf)
Definition at line 80 of file inclinedFilmNusseltInletVelocityFvPatchVectorField.C.
inclinedFilmNusseltInletVelocityFvPatchVectorField() [5/5]
inclinedFilmNusseltInletVelocityFvPatchVectorField (const inclinedFilmNusseltInletVelocityFvPatchVectorField & fmfrpvf, const DimensionedField< vector, volMesh > & iF)
Definition at line 94 of file inclinedFilmNusseltInletVelocityFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("inclinedFilmNusseltInletVelocity")
clone() [1/2]
virtual tmp< fvPatchVectorField > clone () const inline virtual
Definition at line 109 of file inclinedFilmNusseltInletVelocityFvPatchVectorField.H.
clone() [2/2]
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Definition at line 125 of file inclinedFilmNusseltInletVelocityFvPatchVectorField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 111 of file inclinedFilmNusseltInletVelocityFvPatchVectorField.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), Foam::cbrt(), Foam::endl(), Foam::mag(), Foam::max(), mu, n, Foam::operator==(), Foam::pow(), Foam::Re(), rho, Foam::sin(), regionModel::time(), Foam::constant::mathematical::twoPi(), and WarningInFunction.
write()
void write (Ostream & os) const virtual
Definition at line 184 of file inclinedFilmNusseltInletVelocityFvPatchVectorField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntryIfDifferent(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/regionModels/surfaceFilmModels/derivedFvPatchFields/inclinedFilmNusseltInletVelocity/inclinedFilmNusseltInletVelocityFvPatchVectorField.H
src/regionModels/surfaceFilmModels/derivedFvPatchFields/inclinedFilmNusseltInletVelocity/inclinedFilmNusseltInletVelocityFvPatchVectorField.C