OpenFOAM: processorMeshes Class Reference
processorMeshes Class Reference
Container for processor mesh addressing.
#include <processorMeshes.H>
Public Member Functions
ClassName ("processorMeshes")
processorMeshes (PtrList< Time > &databases, const word &meshName)
polyMesh::readUpdateState readUpdate ()
void reconstructPoints (fvMesh &)
const PtrList< fvMesh > & meshes () const noexcept
PtrList< fvMesh > & meshes () noexcept
const PtrList< labelIOList > & pointProcAddressing () const noexcept
PtrList< labelIOList > & faceProcAddressing () noexcept
const PtrList< labelIOList > & cellProcAddressing () const noexcept
const PtrList< labelIOList > & boundaryProcAddressing () const noexcept
Static Public Member Functions
static void removeFiles (const polyMesh &mesh)
Detailed Description
Container for processor mesh addressing.
Source files
processorMeshes.H
processorMeshes.C
Definition at line 50 of file processorMeshes.H.
Constructor & Destructor Documentation
processorMeshes()
processorMeshes (PtrList< Time > & databases, const word & meshName)
Definition at line 100 of file processorMeshes.C.
Member Function Documentation
ClassName()
ClassName ("processorMeshes")
readUpdate()
Foam::polyMesh::readUpdateState readUpdate ()
Definition at line 120 of file processorMeshes.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::nl, Foam::read(), polyMesh::TOPO_CHANGE, polyMesh::TOPO_PATCH_CHANGE, and polyMesh::UNCHANGED.
reconstructPoints()
void reconstructPoints (fvMesh & mesh)
Definition at line 171 of file processorMeshes.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, mesh, polyMesh::meshSubDir, fvMesh::movePoints(), IOobjectOption::MUST_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, primitiveMesh::nPoints(), PtrList< T >::set(), UPtrList< T >::size(), UList< T >::size(), timeName, and fvMesh::write().
meshes() [1/2]
const PtrList< fvMesh > & meshes () const inline noexcept
Definition at line 107 of file processorMeshes.H.
meshes() [2/2]
PtrList< fvMesh > & meshes () inline noexcept
Definition at line 112 of file processorMeshes.H.
pointProcAddressing()
const PtrList< labelIOList > & pointProcAddressing () const inline noexcept
Definition at line 117 of file processorMeshes.H.
faceProcAddressing()
PtrList< labelIOList > & faceProcAddressing () inline noexcept
Definition at line 122 of file processorMeshes.H.
cellProcAddressing()
const PtrList< labelIOList > & cellProcAddressing () const inline noexcept
Definition at line 127 of file processorMeshes.H.
boundaryProcAddressing()
const PtrList< labelIOList > & boundaryProcAddressing () const inline noexcept
Definition at line 132 of file processorMeshes.H.
removeFiles()
void removeFiles (const polyMesh & mesh) static
Definition at line 224 of file processorMeshes.C.
References polyMesh::facesInstance(), Foam::fileHandler, io(), mesh, polyMesh::meshSubDir, IOobject::objectPath(), IOobject::rename(), and fvMesh::thisDb().
The documentation for this class was generated from the following files:
src/parallel/reconstruct/reconstruct/processorMeshes.H
src/parallel/reconstruct/reconstruct/processorMeshes.C