OpenFOAM: nutLowReWallFunctionFvPatchScalarField Class Reference
nutLowReWallFunctionFvPatchScalarField Class Reference
Turbulence models » Boundary conditions » Wall functions
This boundary condition provides a simple wrapper around a zero fixed-value condition for the turbulent viscosity (i.e. nut) for low-Reynolds number applications. It sets nut to zero, and provides an access function to calculate y+.
#include <nutLowReWallFunctionFvPatchScalarField.H>
Public Member Functions
TypeName ("nutLowReWallFunction")
nutLowReWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
nutLowReWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
nutLowReWallFunctionFvPatchScalarField (const nutLowReWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
nutLowReWallFunctionFvPatchScalarField (const nutLowReWallFunctionFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
nutLowReWallFunctionFvPatchScalarField (const nutLowReWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual tmp< scalarField > yPlus () const
virtual void write (Ostream &) const
Public Member Functions inherited from nutWallFunctionFvPatchScalarField
TypeName ("nutWallFunction")
nutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
nutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &)
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
const wallFunctionCoefficients & wallCoeffs () const noexcept
virtual void updateCoeffs ()
Protected Member Functions
virtual tmp< scalarField > calcNut () const
Protected Member Functions inherited from nutWallFunctionFvPatchScalarField
virtual const volVectorField & U (const turbulenceModel &turb) const
virtual void checkType ()
void writeLocalEntries (Ostream &) const
Additional Inherited Members
Static Public Member Functions inherited from nutWallFunctionFvPatchScalarField
static const nutWallFunctionFvPatchScalarField & nutw (const turbulenceModel &turbModel, const label patchi)
Protected Attributes inherited from nutWallFunctionFvPatchScalarField
word UName_
wallFunctionCoefficients wallCoeffs_
Detailed Description
This boundary condition provides a simple wrapper around a zero fixed-value condition for the turbulent viscosity (i.e. nut) for low-Reynolds number applications. It sets nut to zero, and provides an access function to calculate y+.
Usage
Example of the boundary condition specification:
<patchName>
{
    // Mandatory entries
    type            nutLowReWallFunction;
    // Inherited entries
    ...
}
where the entries mean:
Property Description Type Reqd Deflt
type Type name: nutLowReWallFunction word yes -
The inherited entries are elaborated in:
nutWallFunctionFvPatchScalarField.H
Source files
nutLowReWallFunctionFvPatchScalarField.H
nutLowReWallFunctionFvPatchScalarField.C
Definition at line 87 of file nutLowReWallFunctionFvPatchScalarField.H.
Constructor & Destructor Documentation
nutLowReWallFunctionFvPatchScalarField() [1/5]
nutLowReWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 40 of file nutLowReWallFunctionFvPatchScalarField.C.
nutLowReWallFunctionFvPatchScalarField() [2/5]
nutLowReWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 64 of file nutLowReWallFunctionFvPatchScalarField.C.
nutLowReWallFunctionFvPatchScalarField() [3/5]
nutLowReWallFunctionFvPatchScalarField (const nutLowReWallFunctionFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 51 of file nutLowReWallFunctionFvPatchScalarField.C.
nutLowReWallFunctionFvPatchScalarField() [4/5]
nutLowReWallFunctionFvPatchScalarField (const nutLowReWallFunctionFvPatchScalarField & nlrwfpsf)
Definition at line 76 of file nutLowReWallFunctionFvPatchScalarField.C.
nutLowReWallFunctionFvPatchScalarField() [5/5]
nutLowReWallFunctionFvPatchScalarField (const nutLowReWallFunctionFvPatchScalarField & nlrwfpsf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 86 of file nutLowReWallFunctionFvPatchScalarField.C.
Member Function Documentation
calcNut()
Foam::tmp< Foam::scalarField > calcNut () const protected virtual
Implements nutWallFunctionFvPatchScalarField.
Definition at line 31 of file nutLowReWallFunctionFvPatchScalarField.C.
References tmp< T >::New(), and Foam::Zero.
TypeName()
TypeName ("nutLowReWallFunction")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 140 of file nutLowReWallFunctionFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 156 of file nutLowReWallFunctionFvPatchScalarField.H.
yPlus()
Foam::tmp< Foam::scalarField > yPlus () const virtual
Implements nutWallFunctionFvPatchScalarField.
Definition at line 99 of file nutLowReWallFunctionFvPatchScalarField.C.
References IOobject::groupName(), Foam::mag(), turbulenceModel::propertiesName, fvPatchField< Type >::snGrad(), Foam::sqrt(), U, and y.
write()
void write (Ostream & os) const virtual
Reimplemented from nutWallFunctionFvPatchScalarField.
Definition at line 127 of file nutLowReWallFunctionFvPatchScalarField.C.
References os(), nutWallFunctionFvPatchScalarField::write(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/derivedFvPatchFields/wallFunctions/nutWallFunctions/nutLowReWallFunction/nutLowReWallFunctionFvPatchScalarField.H
src/TurbulenceModels/turbulenceModels/derivedFvPatchFields/wallFunctions/nutWallFunctions/nutLowReWallFunction/nutLowReWallFunctionFvPatchScalarField.C