OpenFOAM: MultiComponentPhaseModel< BasePhaseModel, phaseThermo > Class Template Reference
MultiComponentPhaseModel< BasePhaseModel, phaseThermo > Class Template Reference
Class which represents a phase with multiple species. Returns the species' mass fractions, and their governing equations.
#include <MultiComponentPhaseModel.H>
Public Member Functions
MultiComponentPhaseModel (const multiphaseInterSystem &fluid, const word &phaseName)
virtual ~MultiComponentPhaseModel ()=default
const hashedWordList & species () const
virtual const phaseThermo & thermo () const
virtual phaseThermo & thermo ()
virtual void correct ()
virtual void solveYi (PtrList< volScalarField::Internal > &, PtrList< volScalarField::Internal > &)
virtual const PtrList< volScalarField > & Y () const
virtual PtrList< volScalarField > & Y ()
label inertIndex () const
MultiComponentPhaseModel (const phaseSystem &fluid, const word &phaseName, const label index)
virtual ~MultiComponentPhaseModel ()
virtual void correctThermo ()
virtual bool pure () const
virtual tmp< fvScalarMatrix > YiEqn (volScalarField &Yi)
virtual const PtrList< volScalarField > & Y () const
virtual const volScalarField & Y (const word &name) const
virtual PtrList< volScalarField > & YRef ()
virtual const UPtrList< volScalarField > & YActive () const
virtual UPtrList< volScalarField > & YActiveRef ()
Protected Member Functions
void calculateMassFractions ()
void calculateVolumeFractions ()
Protected Attributes
hashedWordList species_
label inertIndex_
autoPtr< phaseThermo > thermoPtr_
PtrList< volScalarField > X_
bool addDiffusion_
scalar Sct_
dimensionedScalar Sct_
dimensionedScalar residualAlpha_
UPtrList< volScalarField > YActive_
Detailed Description
template<class BasePhaseModel, class phaseThermo>
class Foam::MultiComponentPhaseModel< BasePhaseModel, phaseThermo >
Class which represents a phase with multiple species. Returns the species' mass fractions, and their governing equations.
Source files
MultiComponentPhaseModel.H
MultiComponentPhaseModel.C
Source files
MultiComponentPhaseModel.H
MultiComponentPhaseModel.C
Definition at line 51 of file MultiComponentPhaseModel.H.
Constructor & Destructor Documentation
MultiComponentPhaseModel() [1/2]
template<class BasePhaseModel , class phaseThermo > MultiComponentPhaseModel (const multiphaseInterSystem & fluid, const word & phaseName)
Definition at line 39 of file MultiComponentPhaseModel.C.
References MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::addDiffusion_, MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::calculateVolumeFractions(), basicThermo::dictName, UPtrList< T >::empty(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, hashedWordList::find(), fluid, forAll, IOobject::groupName(), MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::inertIndex_, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, basicThermo::phasePropertyName(), autoPtr< T >::reset(), MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::Sct_, PtrList< T >::set(), PtrList< T >::setSize(), UPtrList< T >::size(), MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::species_, MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::thermoPtr_, MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::X_, and MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::Y().
~MultiComponentPhaseModel() [1/2]
template<class BasePhaseModel > ~MultiComponentPhaseModel () virtual default
Definition at line 86 of file MultiComponentPhaseModel.C.
MultiComponentPhaseModel() [2/2]
template<class BasePhaseModel > MultiComponentPhaseModel (const phaseSystem & fluid, const word & phaseName, const label index)
Definition at line 37 of file MultiComponentPhaseModel.C.
References Foam::dimless, forAll, MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::inertIndex_, inertSpecie(), PtrList< T >::resize(), PtrList< T >::set(), UPtrList< T >::size(), MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::Y(), and MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::YActive_.
~MultiComponentPhaseModel() [2/2]
template<class BasePhaseModel , class phaseThermo > virtual ~MultiComponentPhaseModel () virtual
Member Function Documentation
calculateMassFractions()
template<class BasePhaseModel , class phaseThermo > void calculateMassFractions () protected
Definition at line 154 of file MultiComponentPhaseModel.C.
References composition, Foam::endl(), forAll, Foam::Info, Foam::max(), Foam::min(), UPtrList< T >::size(), and Y.
calculateVolumeFractions()
template<class BasePhaseModel , class phaseThermo > void calculateVolumeFractions () protected
Definition at line 110 of file MultiComponentPhaseModel.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), composition, Foam::dimMass, Foam::dimMoles, forAll, and Y.
Referenced by MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::MultiComponentPhaseModel().
species()
template<class BasePhaseModel , class phaseThermo > const hashedWordList & species () const inline
Definition at line 107 of file MultiComponentPhaseModel.H.
References MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::species_.
thermo() [1/2]
template<class BasePhaseModel , class phaseThermo > const phaseThermo & thermo () const virtual
Definition at line 177 of file MultiComponentPhaseModel.C.
thermo() [2/2]
template<class BasePhaseModel , class phaseThermo > phaseThermo & thermo () virtual
Definition at line 185 of file MultiComponentPhaseModel.C.
correct()
template<class BasePhaseModel , class phaseThermo > void correct () virtual
Definition at line 192 of file MultiComponentPhaseModel.C.
solveYi()
template<class BasePhaseModel , class phaseThermo > void solveYi (PtrList< volScalarField::Internal > & Su, PtrList< volScalarField::Internal > & Sp) virtual
Definition at line 199 of file MultiComponentPhaseModel.C.
References alpha, alpha1, alpha2, GeometricField< Type, PatchField, GeoMesh >::boundaryField(), GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), GeometricField< Type, PatchField, GeoMesh >::clamp_min(), Foam::fvc::ddt(), Foam::fvm::ddt(), Foam::MULES::explicitSolve(), fluid, fvMatrix< Type >::flux(), Foam::fvc::flux(), forAll, forAllConstIter, UPtrList< T >::get(), Foam::fvm::laplacian(), Foam::MULES::limit(), Foam::mag(), fvMesh::magSf(), Foam::max(), mesh, Foam::min(), nut, phases, phi, twoPhaseSystem::phi(), phic(), phir(), PtrList< T >::set(), fvMatrix< Type >::solve(), solution::solver(), solution::solverDict(), Sp, Foam::fvm::Sp(), Su, fvMesh::time(), turbulence, and Yt().
Y() [1/4]
template<class BasePhaseModel > const Foam::PtrList< Foam::volScalarField > & Y () const virtual
Definition at line 432 of file MultiComponentPhaseModel.C.
Referenced by MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::MultiComponentPhaseModel(), and MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::MultiComponentPhaseModel().
Y() [2/4]
template<class BasePhaseModel , class phaseThermo > Foam::PtrList< Foam::volScalarField > & Y () virtual
Definition at line 440 of file MultiComponentPhaseModel.C.
inertIndex()
template<class BasePhaseModel , class phaseThermo > Foam::label inertIndex () const
Definition at line 448 of file MultiComponentPhaseModel.C.
correctThermo()
template<class BasePhaseModel > void correctThermo () virtual
Definition at line 93 of file MultiComponentPhaseModel.C.
References Foam::dimless, fluid, forAll, IOobject::groupName(), mesh, Foam::name(), timeName, and Yt().
pure()
template<class BasePhaseModel > bool pure () const virtual
Definition at line 136 of file MultiComponentPhaseModel.C.
YiEqn()
template<class BasePhaseModel > Foam::tmp< Foam::fvScalarMatrix > YiEqn (volScalarField & Yi) virtual
Definition at line 144 of file MultiComponentPhaseModel.C.
References alpha, Foam::fvc::ddt(), Foam::fvm::ddt(), Foam::fvm::div(), Foam::fvc::interpolate(), Foam::fvm::laplacian(), IOobject::name(), and rho.
Y() [3/4]
template<class BasePhaseModel , class phaseThermo > virtual const PtrList< volScalarField > & Y () const virtual
Y() [4/4]
template<class BasePhaseModel > const Foam::volScalarField & Y (const word & name) const virtual
Definition at line 180 of file MultiComponentPhaseModel.C.
References Foam::name().
YRef()
template<class BasePhaseModel > Foam::PtrList< Foam::volScalarField > & YRef () virtual
Definition at line 188 of file MultiComponentPhaseModel.C.
YActive()
template<class BasePhaseModel > const Foam::UPtrList< Foam::volScalarField > & YActive () const virtual
Definition at line 196 of file MultiComponentPhaseModel.C.
YActiveRef()
template<class BasePhaseModel > Foam::UPtrList< Foam::volScalarField > & YActiveRef () virtual
Definition at line 204 of file MultiComponentPhaseModel.C.
Member Data Documentation
species_
template<class BasePhaseModel , class phaseThermo > hashedWordList species_ protected
Definition at line 60 of file MultiComponentPhaseModel.H.
Referenced by MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::MultiComponentPhaseModel(), and MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::species().
inertIndex_
template<class BasePhaseModel , class phaseThermo > label inertIndex_ protected
Definition at line 63 of file MultiComponentPhaseModel.H.
Referenced by MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::MultiComponentPhaseModel(), and MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::MultiComponentPhaseModel().
thermoPtr_
template<class BasePhaseModel , class phaseThermo > autoPtr<phaseThermo> thermoPtr_ protected
Definition at line 66 of file MultiComponentPhaseModel.H.
Referenced by MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::MultiComponentPhaseModel().
X_
template<class BasePhaseModel , class phaseThermo > PtrList<volScalarField> X_ protected
Definition at line 69 of file MultiComponentPhaseModel.H.
Referenced by MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::MultiComponentPhaseModel().
addDiffusion_
template<class BasePhaseModel , class phaseThermo > bool addDiffusion_ protected
Definition at line 72 of file MultiComponentPhaseModel.H.
Referenced by MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::MultiComponentPhaseModel().
Sct_ [1/2]
template<class BasePhaseModel , class phaseThermo > scalar Sct_ protected
Definition at line 75 of file MultiComponentPhaseModel.H.
Referenced by MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::MultiComponentPhaseModel().
Sct_ [2/2]
template<class BasePhaseModel , class phaseThermo > dimensionedScalar Sct_ protected
Definition at line 57 of file MultiComponentPhaseModel.H.
residualAlpha_
template<class BasePhaseModel , class phaseThermo > dimensionedScalar residualAlpha_ protected
Definition at line 60 of file MultiComponentPhaseModel.H.
YActive_
template<class BasePhaseModel , class phaseThermo > UPtrList<volScalarField> YActive_ protected
Definition at line 66 of file MultiComponentPhaseModel.H.
Referenced by MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::MultiComponentPhaseModel().
The documentation for this class was generated from the following files:
src/phaseSystemModels/multiphaseInter/phasesSystem/phaseModel/MultiComponentPhaseModel/MultiComponentPhaseModel.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/phaseModel/MultiComponentPhaseModel/MultiComponentPhaseModel.H
src/phaseSystemModels/multiphaseInter/phasesSystem/phaseModel/MultiComponentPhaseModel/MultiComponentPhaseModel.C
src/phaseSystemModels/reactingEuler/multiphaseSystem/phaseModel/MultiComponentPhaseModel/MultiComponentPhaseModel.C