OpenFOAM: relaxation Class Reference
relaxation Class Reference
Consumption rate per unit of flame area obtained from a relaxation equation.
#include <relaxation.H>
Public Member Functions
TypeName ("relaxation")
relaxation (const word modelType, const dictionary &dictCoeffs, const fvMesh &mesh, const combustionModel &combModel)
virtual ~relaxation ()
virtual void correct (const volScalarField &sigma)
virtual bool read (const dictionary &dictProperties)
Public Member Functions inherited from reactionRateFlameArea
TypeName ("reactionRateFlameArea")
declareRunTimeSelectionTable (autoPtr, reactionRateFlameArea, dictionary,(const word modelType, const dictionary &dict, const fvMesh &mesh, const combustionModel &combModel),(modelType, dict, mesh, combModel))
reactionRateFlameArea (const word &modelType, const dictionary &dict, const fvMesh &mesh, const combustionModel &combModel)
virtual ~reactionRateFlameArea ()
const volScalarField & omega () const
Additional Inherited Members
Static Public Member Functions inherited from reactionRateFlameArea
static autoPtr< reactionRateFlameArea > New (const dictionary &dict, const fvMesh &mesh, const combustionModel &combModel)
Protected Attributes inherited from reactionRateFlameArea
dictionary coeffDict_
const fvMesh & mesh_
const combustionModel & combModel_
word fuel_
volScalarField omega_
Detailed Description
Consumption rate per unit of flame area obtained from a relaxation equation.
Source files
relaxation.H
relaxation.C
Definition at line 49 of file relaxation.H.
Constructor & Destructor Documentation
relaxation()
relaxation (const word modelType, const dictionary & dictCoeffs, const fvMesh & mesh, const combustionModel & combModel)
Definition at line 45 of file relaxation.C.
~relaxation()
~relaxation () virtual
Definition at line 62 of file relaxation.C.
Member Function Documentation
TypeName()
TypeName ("relaxation")
correct()
void correct (const volScalarField & sigma) virtual
Implements reactionRateFlameArea.
Definition at line 68 of file relaxation.C.
References Foam::fvm::ddt(), dimensioned< Type >::dimensions(), Foam::dimVelocity, Foam::fvm::div(), e, Foam::mag(), phi, rho, solve(), Foam::sqr(), Foam::fvm::SuSp(), turbulence, and dimensioned< Type >::value().
read()
bool read (const dictionary & dictProperties) virtual
Reimplemented from reactionRateFlameArea.
Definition at line 136 of file relaxation.C.
References dict, and reactionRateFlameArea::read().
The documentation for this class was generated from the following files:
src/combustionModels/FSD/reactionRateFlameAreaModels/relaxation/relaxation.H
src/combustionModels/FSD/reactionRateFlameAreaModels/relaxation/relaxation.C