OpenFOAM: OFstreamCollator Class Reference
OFstreamCollator Class Reference
Threaded file writer.
#include <OFstreamCollator.H>
Public Member Functions
TypeName ("OFstreamCollator")
OFstreamCollator (const off_t maxBufferSize)
OFstreamCollator (const off_t maxBufferSize, const label comm)
virtual ~OFstreamCollator ()
bool write (const word &objectType, const fileName &, const string &data, IOstreamOption streamOpt, IOstreamOption::atomicType atomic, IOstreamOption::appendType append, const bool useThread=true, const dictionary &headerEntries=dictionary::null)
void waitAll ()
Detailed Description
Threaded file writer.
Collects all data from all processors and writes as single 'decomposedBlockData' file. The operation is determined by the buffer size (maxThreadFileBufferSize setting):
local size of data is larger than buffer: receive and write processor by processor (i.e. 'scheduled'). Does not use a thread, no file size limit.
total size of data is larger than buffer (but local is not): thread does all the collecting and writing of the processors. No file size limit.
total size of data is less than buffer: collecting is done locally; the thread only does the writing (since the data has already been collected)
Source files
OFstreamCollator.H
OFstreamCollator.C
Definition at line 66 of file OFstreamCollator.H.
Constructor & Destructor Documentation
OFstreamCollator() [1/2]
OFstreamCollator (const off_t maxBufferSize) explicit
Definition at line 281 of file OFstreamCollator.C.
OFstreamCollator() [2/2]
OFstreamCollator (const off_t maxBufferSize, const label comm)
Definition at line 297 of file OFstreamCollator.C.
~OFstreamCollator()
~OFstreamCollator () virtual
Definition at line 319 of file OFstreamCollator.C.
References Foam::endl(), UPstream::freeCommunicator(), and Foam::Pout.
Member Function Documentation
TypeName()
TypeName ("OFstreamCollator")
write()
bool write (const word & objectType, const fileName & fName, const string & data, IOstreamOption streamOpt, IOstreamOption::atomicType atomic, IOstreamOption::appendType append, const bool useThread = true, const dictionary & headerEntries = dictionary::null)
Definition at line 337 of file OFstreamCollator.C.
References Foam::abort(), append(), Pstream::broadcasts(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, decomposedBlockData::gather(), UPstream::haveThreads(), UPstream::master(), Foam::max(), UPstream::msgType(), UPstream::nonBlocking, UPstream::nRequests(), string::null, Foam::Pout, UIPstream::read(), PtrList< T >::set(), PtrList< T >::setSize(), UPtrList< T >::size(), UPstream::waitRequests(), UOPstream::write(), and Foam::writeData().
waitAll()
void waitAll ()
Definition at line 580 of file OFstreamCollator.C.
References Foam::endl(), UPstream::master(), and Foam::Pout.
The documentation for this class was generated from the following files:
src/OpenFOAM/global/fileOperations/collatedFileOperation/OFstreamCollator.H
src/OpenFOAM/global/fileOperations/collatedFileOperation/OFstreamCollator.C