OpenFOAM: procLduMatrix Class Reference
procLduMatrix Class Reference
I/O for lduMatrix and interface values.
#include <procLduMatrix.H>
Public Member Functions
procLduMatrix (const lduMatrix &ldum, const FieldField< Field, scalar > &interfaceCoeffs, const lduInterfaceFieldPtrsList &interfaces)
procLduMatrix (Istream &is)
label size () const
Friends
class LUscalarMatrix
Ostream & operator<< (Ostream &, const procLduMatrix &)
Detailed Description
I/O for lduMatrix and interface values.
Source files
procLduMatrix.H
procLduMatrix.C
Definition at line 59 of file procLduMatrix.H.
Constructor & Destructor Documentation
procLduMatrix() [1/2]
procLduMatrix (const lduMatrix & ldum, const FieldField< Field, scalar > & interfaceCoeffs, const lduInterfaceFieldPtrsList & interfaces)
Definition at line 27 of file procLduMatrix.C.
References Foam::diag(), forAll, PtrList< T >::set(), UPtrList< T >::set(), and PtrList< T >::setSize().
procLduMatrix() [2/2]
procLduMatrix (Istream & is)
Definition at line 73 of file procLduMatrix.C.
Member Function Documentation
size()
label size () const inline
Definition at line 96 of file procLduMatrix.H.
References UList< T >::size().
Friends And Related Symbol Documentation
LUscalarMatrix
friend class LUscalarMatrix friend
Definition at line 79 of file procLduMatrix.H.
operator<<
Ostream & operator<< (Ostream & , const procLduMatrix &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/LUscalarMatrix/procLduMatrix.H
src/OpenFOAM/matrices/LUscalarMatrix/procLduMatrix.C