OpenFOAM: axis Class Reference
axis Class Reference
This constraint imposes an orientation limitation where bodies are restricted to rotate only around a fixed axis, optionally with the inclusion of maximum and minimum rotation angle constraints.
#include <sixDoFRigidBodyMotionAxisConstraint.H>
Public Member Functions
TypeName ("axis")
axis (const word &name, const dictionary &sDoFRBMCDict, const sixDoFRigidBodyMotion &motion)
virtual autoPtr< sixDoFRigidBodyMotionConstraint > clone () const
void operator= (const sixDoFRigidBodyMotionConstraint &)=delete
virtual ~axis ()=default
virtual void constrainTranslation (pointConstraint &) const
virtual void constrainRotation (pointConstraint &) const
virtual bool read (const dictionary &sDoFRBMCCoeff)
virtual void write (Ostream &) const
Public Member Functions inherited from sixDoFRigidBodyMotionConstraint
TypeName ("sixDoFRigidBodyMotionConstraint")
declareRunTimeSelectionTable (autoPtr, sixDoFRigidBodyMotionConstraint, dictionary,(const word &name, const dictionary &sDoFRBMCDict, const sixDoFRigidBodyMotion &motion),(name, sDoFRBMCDict, motion))
sixDoFRigidBodyMotionConstraint (const word &name, const dictionary &sDoFRBMCDict, const sixDoFRigidBodyMotion &motion)
virtual ~sixDoFRigidBodyMotionConstraint ()
const word & name () const
virtual void setCentreOfRotation (point &) const
const dictionary & coeffDict () const
const sixDoFRigidBodyMotion & motion () const noexcept
Additional Inherited Members
Static Public Member Functions inherited from sixDoFRigidBodyMotionConstraint
static autoPtr< sixDoFRigidBodyMotionConstraint > New (const word &name, const dictionary &sDoFRBMCDict, const sixDoFRigidBodyMotion &motion)
Protected Attributes inherited from sixDoFRigidBodyMotionConstraint
word name_
dictionary sDoFRBMCCoeffs_
const sixDoFRigidBodyMotion & motion_
Detailed Description
This constraint imposes an orientation limitation where bodies are restricted to rotate only around a fixed axis, optionally with the inclusion of maximum and minimum rotation angle constraints.
Usage
Minimal example by constant/dynamicMeshDict.sixDoFRigidBodyMotionCoeffs:
constraints
{
    constrainRotation1
    {
        // Mandatory entries
        sixDoFRigidBodyMotionConstraint     axis;
        axis                                <vector>;
        // Optional entries
        maxClockwiseTheta                   <Function1<scalar>>;
        maxCounterclockwiseTheta            <Function1<scalar>>;
        thetaUnits                          <word>;
        referenceOrientation                <tensor>;
    }
}
where the entries mean:
Property Description Type Reqd Deflt
sixDoFRigidBodyMotionConstraint Type name: axis word yes -
axis
Reference rotation axis fixed in global space
vector yes -
maxClockwiseTheta
Maximum clockwise rotation angle about the
rotation axis
Function1<scalar> no -
maxCounterlockwiseTheta
Maximum counterclockwise rotation
angle about the rotation axis
Function1<scalar> no -
thetaUnits Units of theta angles word no radians
referenceOrientation
Reference orientation where there is no moment
tensor no I
The inherited entries are elaborated in:
Function1.H
Notes
The units for thetaUnits can be specified as either degrees or radians.
The maxClockwiseTheta and maxCounterlockwiseTheta are always non-negative.
Negative and positive theta correspond to clockwise and counterclockwise rotation sectors with respect to the reference orientation, respectively.
Source files
sixDoFRigidBodyMotionAxisConstraint.H
sixDoFRigidBodyMotionAxisConstraint.C
Definition at line 150 of file sixDoFRigidBodyMotionAxisConstraint.H.
Constructor & Destructor Documentation
axis()
axis (const word & name, const dictionary & sDoFRBMCDict, const sixDoFRigidBodyMotion & motion)
Definition at line 83 of file sixDoFRigidBodyMotionAxisConstraint.C.
References axis::read().
~axis()
virtual ~axis () virtual default
Member Function Documentation
TypeName()
TypeName ("axis")
clone()
virtual autoPtr< sixDoFRigidBodyMotionConstraint > clone () const inline virtual
Implements sixDoFRigidBodyMotionConstraint.
Definition at line 201 of file sixDoFRigidBodyMotionAxisConstraint.H.
operator=()
void operator= (const sixDoFRigidBodyMotionConstraint &) delete
constrainTranslation()
void constrainTranslation (pointConstraint & pc) const virtual
Implements sixDoFRigidBodyMotionConstraint.
Definition at line 103 of file sixDoFRigidBodyMotionAxisConstraint.C.
constrainRotation()
void constrainRotation (pointConstraint & pc) const virtual
Implements sixDoFRigidBodyMotionConstraint.
Definition at line 110 of file sixDoFRigidBodyMotionAxisConstraint.C.
References Foam::acos(), pointConstraint::combine(), Foam::degToRad(), Foam::endl(), Foam::equal(), Foam::Info, Foam::mag(), Foam::min(), Foam::nl, Foam::rotationTensor(), Foam::sign(), and Foam::Zero.
read()
bool read (const dictionary & sDoFRBMCCoeff) virtual
Reimplemented from sixDoFRigidBodyMotionConstraint.
Definition at line 227 of file sixDoFRigidBodyMotionAxisConstraint.C.
References Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, Foam::I, Foam::mag(), Foam::nl, sixDoFRigidBodyMotionConstraint::read(), and Foam::sqrt().
Referenced by axis::axis().
write()
void write (Ostream & os) const virtual
Reimplemented from sixDoFRigidBodyMotionConstraint.
Definition at line 308 of file sixDoFRigidBodyMotionAxisConstraint.C.
References os().
The documentation for this class was generated from the following files:
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/constraints/axis/sixDoFRigidBodyMotionAxisConstraint.H
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/constraints/axis/sixDoFRigidBodyMotionAxisConstraint.C