OpenFOAM: blockFace Class Reference
blockFace Class Reference abstract
Define a curved face.
#include <blockFace.H>
Classes
class iNew
Public Member Functions
TypeName ("blockFace")
declareRunTimeSelectionTable (autoPtr, blockFace, Istream,(const dictionary &dict, const label index, const searchableSurfaces &geometry, Istream &is),(dict, index, geometry, is))
blockFace (const face &vertices)
blockFace (const dictionary &dict, const label index, Istream &is)
virtual autoPtr< blockFace > clone () const
virtual ~blockFace ()=default
const face & vertices () const
bool compare (const blockFace &) const
bool compare (const face &vertices) const
virtual void project (const blockDescriptor &, const label blockFacei, pointField &points) const =0
void write (Ostream &, const dictionary &) const
Static Public Member Functions
static autoPtr< blockFace > New (const dictionary &dict, const label index, const searchableSurfaces &geometry, Istream &)
Protected Attributes
const face vertices_
Friends
Ostream & operator<< (Ostream &, const blockFace &)
Detailed Description
Define a curved face.
Source files
blockFace.H
blockFace.C
Definition at line 53 of file blockFace.H.
Constructor & Destructor Documentation
blockFace() [1/2]
blockFace (const face & vertices) explicit
Definition at line 37 of file blockFace.C.
References Foam::vertices().
blockFace() [2/2]
blockFace (const dictionary & dict, const label index, Istream & is)
Definition at line 43 of file blockFace.C.
~blockFace()
virtual ~blockFace () virtual default
Member Function Documentation
TypeName()
TypeName ("blockFace")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , blockFace , Istream , (const dictionary &dict, const label index, const searchableSurfaces &geometry, Istream &is) , (dict, index, geometry, is))
clone()
Foam::autoPtr< Foam::blockFace > clone () const virtual
Definition at line 61 of file blockFace.C.
References NotImplemented.
New()
Foam::autoPtr< Foam::blockFace > New (const dictionary & dict, const label index, const searchableSurfaces & geometry, Istream & is) static
Definition at line 68 of file blockFace.C.
References Foam::abort(), DebugInFunction, dict, Foam::endl(), Foam::FatalIOError, and FatalIOErrorInLookup.
Referenced by blockFace::iNew::operator()().
vertices()
const Foam::face & vertices () const inline
Definition at line 23 of file blockFaceI.H.
References blockFace::vertices_.
compare() [1/2]
bool compare (const blockFace & bf) const inline
Definition at line 29 of file blockFaceI.H.
compare() [2/2]
bool compare (const face & vertices) const inline
Definition at line 35 of file blockFaceI.H.
References face::sameVertices(), and Foam::vertices().
project()
virtual void project (const blockDescriptor & , const label blockFacei, pointField & points) const pure virtual
Implemented in projectFace.
write()
void write (Ostream & os, const dictionary & d) const
Definition at line 99 of file blockFace.C.
References token::BEGIN_LIST, token::END_LIST, forAll, os(), token::SPACE, and blockVertex::write().
Friends And Related Symbol Documentation
operator<<
Ostream & operator<< (Ostream & , const blockFace &) friend
Member Data Documentation
vertices_
const face vertices_ protected
Definition at line 60 of file blockFace.H.
Referenced by blockFace::vertices().
The documentation for this class was generated from the following files:
src/mesh/blockMesh/blockFaces/blockFace/blockFace.H
src/mesh/blockMesh/blockFaces/blockFace/blockFace.C
src/mesh/blockMesh/blockFaces/blockFace/blockFaceI.H