OpenFOAM: FieldMapper Class Reference
FieldMapper Class Reference abstract
Abstract base class to hold the Field mapping addressing and weights.
#include <FieldMapper.H>
Public Member Functions
FieldMapper ()=default
virtual ~FieldMapper ()=default
virtual label size () const =0
virtual bool direct () const =0
virtual bool distributed () const
virtual bool hasUnmapped () const =0
virtual const labelUList & directAddressing () const
virtual const mapDistributeBase & distributeMap () const
virtual const labelListList & addressing () const
virtual const scalarListList & weights () const
template<class Type >
tmp< Field< Type > > operator() (const Field< Type > &fld) const
Detailed Description
Abstract base class to hold the Field mapping addressing and weights.
Definition at line 43 of file FieldMapper.H.
Constructor & Destructor Documentation
FieldMapper()
FieldMapper () default
~FieldMapper()
virtual ~FieldMapper () virtual default
Member Function Documentation
size()
virtual label size () const pure virtual
Implemented in faAreaMapper, faEdgeMapper, faPatchMapper, fvPatchMapper, fvSurfaceMapper, singleCellFvMesh::agglomPatchFieldMapper, pointMapper, pointPatchMapper, cellMapper, faceMapper, fvFieldDecomposer::patchFieldDecomposer, fvFieldDecomposer::processorVolPatchFieldDecomposer, fvFieldDecomposer::processorSurfacePatchFieldDecomposer, pointFieldDecomposer::patchFieldDecomposer, faFieldDecomposer::patchFieldDecomposer, faFieldDecomposer::processorAreaPatchFieldDecomposer, faFieldDecomposer::processorEdgePatchFieldDecomposer, faFieldReconstructor::faPatchFieldReconstructor, fvFieldReconstructor::fvPatchFieldReconstructor, pointFieldReconstructor::pointPatchFieldReconstructor, distributedWeightedFvPatchFieldMapper, and meshToMesh0::patchFieldInterpolator.
Referenced by fvPatchField< Type >::autoMap(), and externalWallHeatFluxTemperatureFvPatchScalarField::externalWallHeatFluxTemperatureFvPatchScalarField().
direct()
virtual bool direct () const pure virtual
Implemented in faAreaMapper, faEdgeMapper, faPatchMapper, fvPatchMapper, fvSurfaceMapper, singleCellFvMesh::agglomPatchFieldMapper, pointMapper, pointPatchMapper, cellMapper, faceMapper, fvFieldDecomposer::patchFieldDecomposer, fvFieldDecomposer::processorVolPatchFieldDecomposer, fvFieldDecomposer::processorSurfacePatchFieldDecomposer, pointFieldDecomposer::patchFieldDecomposer, faFieldDecomposer::patchFieldDecomposer, faFieldDecomposer::processorAreaPatchFieldDecomposer, faFieldDecomposer::processorEdgePatchFieldDecomposer, faFieldReconstructor::faPatchFieldReconstructor, fvFieldReconstructor::fvPatchFieldReconstructor, pointFieldReconstructor::pointPatchFieldReconstructor, distributedWeightedFvPatchFieldMapper, and meshToMesh0::patchFieldInterpolator.
Referenced by fvPatchField< Type >::autoMap(), pointPatchMapper::direct(), outletMappedUniformInletFvPatchField< Type >::outletMappedUniformInletFvPatchField(), uniformFixedValueFaPatchField< Type >::uniformFixedValueFaPatchField(), uniformFixedValueFvPatchField< Type >::uniformFixedValueFvPatchField(), uniformFixedValuePointPatchField< Type >::uniformFixedValuePointPatchField(), and uniformNormalFixedValueFvPatchVectorField::uniformNormalFixedValueFvPatchVectorField().
distributed()
virtual bool distributed () const inline virtual
Reimplemented in distributedWeightedFvPatchFieldMapper.
Definition at line 66 of file FieldMapper.H.
Referenced by Field< Type >::autoMap(), fvPatchField< Type >::autoMap(), and Field< T >::rmap().
hasUnmapped()
virtual bool hasUnmapped () const pure virtual
Implemented in faAreaMapper, faEdgeMapper, faPatchMapper, fvPatchMapper, fvSurfaceMapper, singleCellFvMesh::agglomPatchFieldMapper, pointMapper, pointPatchMapper, cellMapper, faceMapper, fvFieldDecomposer::patchFieldDecomposer, fvFieldDecomposer::processorVolPatchFieldDecomposer, fvFieldDecomposer::processorSurfacePatchFieldDecomposer, pointFieldDecomposer::patchFieldDecomposer, faFieldDecomposer::patchFieldDecomposer, faFieldDecomposer::processorAreaPatchFieldDecomposer, faFieldDecomposer::processorEdgePatchFieldDecomposer, faFieldReconstructor::faPatchFieldReconstructor, fvFieldReconstructor::fvPatchFieldReconstructor, pointFieldReconstructor::pointPatchFieldReconstructor, distributedWeightedFvPatchFieldMapper, and meshToMesh0::patchFieldInterpolator.
Referenced by fvPatchField< Type >::autoMap(), directionMixedFvPatchField< Type >::directionMixedFvPatchField(), fixedGradientFvPatchField< Type >::fixedGradientFvPatchField(), fixedValueFvPatchField< Type >::fixedValueFvPatchField(), fvPatchField< Type >::fvPatchField(), outletMappedUniformInletFvPatchField< Type >::outletMappedUniformInletFvPatchField(), mixedFvPatchField< scalar >::readMixedEntries(), uniformFixedValueFaPatchField< Type >::uniformFixedValueFaPatchField(), uniformFixedValueFvPatchField< Type >::uniformFixedValueFvPatchField(), uniformFixedValuePointPatchField< Type >::uniformFixedValuePointPatchField(), and uniformNormalFixedValueFvPatchVectorField::uniformNormalFixedValueFvPatchVectorField().
directAddressing()
virtual const labelUList & directAddressing () const inline virtual
Reimplemented in faAreaMapper, faEdgeMapper, faPatchMapper, fvPatchMapper, fvSurfaceMapper, pointMapper, pointPatchMapper, cellMapper, faceMapper, fvFieldDecomposer::patchFieldDecomposer, fvFieldDecomposer::processorVolPatchFieldDecomposer, pointFieldDecomposer::patchFieldDecomposer, faFieldDecomposer::patchFieldDecomposer, faFieldReconstructor::faPatchFieldReconstructor, fvFieldReconstructor::fvPatchFieldReconstructor, pointFieldReconstructor::pointPatchFieldReconstructor, and meshToMesh0::patchFieldInterpolator.
Definition at line 76 of file FieldMapper.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and UList< label >::null().
Referenced by fvPatchField< Type >::autoMap(), Field< T >::clamp_max(), and Field< T >::negate().
distributeMap()
virtual const mapDistributeBase & distributeMap () const inline virtual
Reimplemented in distributedWeightedFvPatchFieldMapper.
Definition at line 86 of file FieldMapper.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Referenced by Field< Type >::autoMap(), and Field< T >::rmap().
addressing()
virtual const labelListList & addressing () const inline virtual
Reimplemented in faAreaMapper, faEdgeMapper, faPatchMapper, fvPatchMapper, fvSurfaceMapper, singleCellFvMesh::agglomPatchFieldMapper, pointMapper, pointPatchMapper, cellMapper, faceMapper, fvFieldDecomposer::processorSurfacePatchFieldDecomposer, faFieldDecomposer::processorAreaPatchFieldDecomposer, faFieldDecomposer::processorEdgePatchFieldDecomposer, and distributedWeightedFvPatchFieldMapper.
Definition at line 96 of file FieldMapper.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and List< labelList >::null().
Referenced by fvPatchField< Type >::autoMap(), and Field< T >::normalise().
weights()
virtual const scalarListList & weights () const inline virtual
Reimplemented in faAreaMapper, faEdgeMapper, faPatchMapper, fvPatchMapper, fvSurfaceMapper, singleCellFvMesh::agglomPatchFieldMapper, pointMapper, pointPatchMapper, cellMapper, faceMapper, fvFieldDecomposer::processorSurfacePatchFieldDecomposer, faFieldDecomposer::processorAreaPatchFieldDecomposer, faFieldDecomposer::processorEdgePatchFieldDecomposer, and distributedWeightedFvPatchFieldMapper.
Definition at line 106 of file FieldMapper.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and List< scalarList >::null().
Referenced by Field< T >::normalise().
operator()()
template<class Type > tmp< Field< Type > > operator() (const Field< Type > & fld) const inline
Definition at line 120 of file FieldMapper.H.
References fld(), and Foam::New().
The documentation for this class was generated from the following file:
src/OpenFOAM/fields/Fields/Field/FieldMapper.H