OpenFOAM: intersection Class Reference
intersection Class Reference
Foam::intersection.
#include <intersection.H>
Public Types
enum direction { VECTOR , CONTACT_SPHERE }
enum algorithm { FULL_RAY , HALF_RAY , VISIBLE }
Static Public Member Functions
static scalar planarTol ()
static scalar setPlanarTol (const scalar t)
Static Public Attributes
static const Enum< direction > directionNames_
static const Enum< algorithm > algorithmNames_
Detailed Description
Foam::intersection.
Source files
intersection.H
intersection.C
Definition at line 48 of file intersection.H.
Member Enumeration Documentation
direction
enum direction
Enumerator
VECTOR
CONTACT_SPHERE
Definition at line 62 of file intersection.H.
algorithm
enum algorithm
Enumerator
FULL_RAY
HALF_RAY
VISIBLE
Definition at line 68 of file intersection.H.
Member Function Documentation
planarTol()
static scalar planarTol () inline static
Definition at line 84 of file intersection.H.
Referenced by triangle< Point, PointRef >::ray().
setPlanarTol()
static scalar setPlanarTol (const scalar t) inline static
Definition at line 90 of file intersection.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Referenced by treeDataCell::findIntersectOp::operator()().
Member Data Documentation
directionNames_
const Foam::Enum< Foam::intersection::direction > directionNames_ static
Definition at line 78 of file intersection.H.
algorithmNames_
const Foam::Enum< Foam::intersection::algorithm > algorithmNames_ static
Definition at line 81 of file intersection.H.
Referenced by slidingInterface::writeDict().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/primitiveShapes/triangle/intersection.H
src/OpenFOAM/meshes/primitiveShapes/triangle/intersection.C