OpenFOAM: icoTabulated< Specie > Class Template Reference
icoTabulated< Specie > Class Template Reference
Incompressible of equation of state using non-uniform tabulated density vs temperature.
#include <icoTabulated.H>
Public Member Functions
icoTabulated (const Specie &sp, const nonUniformTable &rho)
icoTabulated (const dictionary &dict)
icoTabulated (const word &name, const icoTabulated &)
autoPtr< icoTabulated > clone () const
scalar rho (scalar p, scalar T) const
scalar H (const scalar p, const scalar T) const
scalar Cp (scalar p, scalar T) const
scalar E (const scalar p, const scalar T) const
scalar Cv (scalar p, scalar T) const
scalar S (const scalar p, const scalar T) const
scalar psi (scalar p, scalar T) const
scalar Z (scalar p, scalar T) const
scalar CpMCv (scalar p, scalar T) const
void write (Ostream &os) const
Static Public Member Functions
static autoPtr< icoTabulated > New (const dictionary &dict)
static word typeName ()
Static Public Attributes
static const bool incompressible = true
static const bool isochoric = false
Friends
Ostream & operator<< (Ostream &, const icoTabulated &)
Detailed Description
template<class Specie>
class Foam::icoTabulated< Specie >
Incompressible of equation of state using non-uniform tabulated density vs temperature.
Usage
Property Description
rho Density vs temperature table
Example of the specification of the equation of state:
    equationOfState
    {
        rho
        (
            (200 1010)
            (350 1000)
            (400 980)
        );
    }
Source files
icoTabulated.H
icoTabulatedI.H
icoTabulated.C
See also
Foam::thermophysicalFunctions::nonUniformTable
Definition at line 85 of file icoTabulated.H.
Constructor & Destructor Documentation
icoTabulated() [1/3]
template<class Specie > icoTabulated (const Specie & sp, const nonUniformTable & rho) inline
Definition at line 27 of file icoTabulatedI.H.
icoTabulated() [2/3]
template<class Specie > icoTabulated (const dictionary & dict) explicit
Definition at line 28 of file icoTabulated.C.
icoTabulated() [3/3]
template<class Specie > icoTabulated (const word & name, const icoTabulated< Specie > &) inline
Member Function Documentation
clone()
template<class Specie > Foam::autoPtr< Foam::icoTabulated< Specie > > clone () const inline
Definition at line 54 of file icoTabulatedI.H.
References Foam::New().
New()
template<class Specie > Foam::autoPtr< Foam::icoTabulated< Specie > > New (const dictionary & dict) inline static
Definition at line 62 of file icoTabulatedI.H.
References dict, and Foam::New().
typeName()
template<class Specie > static word typeName () inline static
Definition at line 122 of file icoTabulated.H.
rho()
template<class Specie > Foam::scalar rho (scalar p, scalar T) const inline
Definition at line 71 of file icoTabulatedI.H.
References p, and T.
H()
template<class Specie > Foam::scalar H (const scalar p, const scalar T) const inline
Definition at line 82 of file icoTabulatedI.H.
References p, rho, and T.
Cp()
template<class Specie > Foam::scalar Cp (scalar p, scalar T) const inline
Definition at line 93 of file icoTabulatedI.H.
E()
template<class Specie > Foam::scalar E (const scalar p, const scalar T) const inline
Definition at line 104 of file icoTabulatedI.H.
Cv()
template<class Specie > Foam::scalar Cv (scalar p, scalar T) const inline
Definition at line 115 of file icoTabulatedI.H.
S()
template<class Specie > Foam::scalar S (const scalar p, const scalar T) const inline
Definition at line 126 of file icoTabulatedI.H.
psi()
template<class Specie > Foam::scalar psi (scalar p, scalar T) const inline
Definition at line 137 of file icoTabulatedI.H.
Z()
template<class Specie > Foam::scalar Z (scalar p, scalar T) const inline
Definition at line 148 of file icoTabulatedI.H.
CpMCv()
template<class Specie > Foam::scalar CpMCv (scalar p, scalar T) const inline
Definition at line 159 of file icoTabulatedI.H.
write()
template<class Specie > void write (Ostream & os) const
Definition at line 38 of file icoTabulated.C.
References Ostream::beginBlock(), Ostream::endBlock(), os(), and Ostream::writeEntry().
Friends And Related Symbol Documentation
operator<<
template<class Specie > Ostream & operator<< (Ostream & , const icoTabulated< Specie > &) friend
Member Data Documentation
incompressible
template<class Specie > const bool incompressible = true static
Definition at line 131 of file icoTabulated.H.
isochoric
template<class Specie > const bool isochoric = false static
Definition at line 134 of file icoTabulated.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/equationOfState/icoTabulated/icoTabulated.H
src/thermophysicalModels/specie/equationOfState/icoTabulated/icoTabulated.C
src/thermophysicalModels/specie/equationOfState/icoTabulated/icoTabulatedI.H