OpenFOAM: IListStream Class Reference
IListStream Class Reference
An input stream that reads from a List and manages the List storage. Similar to IStringStream but with a List for its storage instead of as string to allow reuse of List contents without copying.
#include <IListStream.H>
Public Member Functions
IListStream (IOstreamOption streamOpt=IOstreamOption())
IListStream (::Foam::List< char > &&buffer, IOstreamOption streamOpt=IOstreamOption())
template<int SizeMin>
IListStream (DynamicList< char, SizeMin > &&buffer, IOstreamOption streamOpt=IOstreamOption())
std::streampos pos () const
virtual void rewind ()
virtual void print (Ostream &os) const
Istream & operator() () const
label size () const
Public Member Functions inherited from IListStreamAllocator
void clearStorage ()
void swap (List< char > &list)
label size () const
Public Member Functions inherited from UIListStreamAllocator
const UList< char > list () const
UList< char > list ()
label size () const
std::streampos tellg () const
void rewind ()
Public Member Functions inherited from ISstream
ISstream (std::istream &is, const string &streamName, IOstreamOption streamOpt=IOstreamOption())
ISstream (std::istream &is, const string &streamName, IOstreamOption::streamFormat fmt, IOstreamOption::compressionType cmp=IOstreamOption::UNCOMPRESSED)
ISstream (std::istream &is, const string &streamName, IOstreamOption::streamFormat fmt, IOstreamOption::versionNumber ver, IOstreamOption::compressionType cmp=IOstreamOption::UNCOMPRESSED)
virtual ~ISstream ()=default
virtual const fileName & name () const
virtual fileName & name ()
virtual const std::istream & stdStream () const
virtual std::istream & stdStream ()
virtual ios_base::fmtflags flags () const
virtual ios_base::fmtflags flags (const ios_base::fmtflags f)
void syncState ()
bool seekCommentEnd_Cstyle ()
bool continueReadUntilRightBrace (std::string &str, const bool stripComments=true)
ISstream & get (char &c)
int peek ()
ISstream & getLine (std::string &str, char delim='\n')
std::streamsize getLine (std::nullptr_t, char delim='\n')
ISstream & putback (const char c)
virtual Istream & read (token &t)
virtual Istream & read (char &c)
virtual Istream & read (word &str)
virtual Istream & read (string &str)
virtual Istream & read (label &val)
virtual Istream & read (float &val)
virtual Istream & read (double &val)
virtual Istream & read (char *data, std::streamsize count)
virtual Istream & readRaw (char *data, std::streamsize count)
virtual bool beginRawRead ()
virtual bool endRawRead ()
Public Member Functions inherited from Istream
Istream (const Istream &)=default
virtual ~Istream ()=default
Istream (IOstreamOption streamOpt=IOstreamOption())
Istream (IOstreamOption::streamFormat fmt, IOstreamOption::compressionType cmp=IOstreamOption::UNCOMPRESSED)
const token & peekBack () const noexcept
bool peekBack (token &tok)
void putBack (const token &tok)
bool getBack (token &tok)
bool readBegin (const char *funcName)
bool readEnd (const char *funcName)
char readBeginList (const char *funcName)
char readEndList (const char *funcName)
Istream & operator() () const
Public Member Functions inherited from IOstream
IOstream (const IOstream &)=default
virtual ~IOstream ()=default
IOstream (IOstreamOption streamOpt=IOstreamOption())
IOstream (IOstreamOption::streamFormat fmt, IOstreamOption::versionNumber ver, IOstreamOption::compressionType cmp=IOstreamOption::UNCOMPRESSED)
fileName relativeName () const
virtual bool check (const char *operation) const
bool fatalCheck (const char *operation) const
bool opened () const noexcept
bool closed () const noexcept
bool good () const noexcept
bool eof () const noexcept
bool fail () const noexcept
bool bad () const noexcept
operator bool () const noexcept
bool operator! () const noexcept
unsigned labelByteSize () const noexcept
unsigned scalarByteSize () const noexcept
void setLabelByteSize (unsigned nbytes) noexcept
void setScalarByteSize (unsigned nbytes) noexcept
template<class T = label>
std::enable_if< std::is_integral< T >::value, bool >::type checkLabelSize () const noexcept
template<class T = scalar>
std::enable_if< std::is_floating_point< T >::value, bool >::type checkScalarSize () const noexcept
label lineNumber () const noexcept
label & lineNumber () noexcept
label lineNumber (const label num) noexcept
void setEof () noexcept
void setFail () noexcept
void setBad ()
ios_base::fmtflags setf (const ios_base::fmtflags f)
ios_base::fmtflags setf (const ios_base::fmtflags f, const ios_base::fmtflags mask)
void unsetf (const ios_base::fmtflags f)
void print (Ostream &os, const int streamState) const
InfoProxy< IOstream > info () const noexcept
Public Member Functions inherited from IOstreamOption
constexpr IOstreamOption (streamFormat fmt=streamFormat::ASCII, compressionType comp=compressionType::UNCOMPRESSED) noexcept
constexpr IOstreamOption (streamFormat fmt, compressionType comp, versionNumber ver) noexcept
constexpr IOstreamOption (streamFormat fmt, versionNumber ver, compressionType comp=compressionType::UNCOMPRESSED) noexcept
IOstreamOption (const IOstreamOption &opt, streamFormat fmt) noexcept
streamFormat format () const noexcept
streamFormat format (const streamFormat fmt) noexcept
streamFormat format (const word &formatName)
compressionType compression () const noexcept
compressionType compression (const compressionType comp) noexcept
compressionType compression (const word &compName)
versionNumber version () const noexcept
versionNumber version (const versionNumber ver) noexcept
versionNumber version (const token &tok)
Additional Inherited Members
Public Types inherited from IOstream
enum streamAccess : char { CLOSED = 0 , OPENED }
Public Types inherited from IOstreamOption
enum streamFormat : char { ASCII = 0 , BINARY }
enum compressionType : char { UNCOMPRESSED = 0 , COMPRESSED }
enum appendType : char { NON_APPEND = 0 , APPEND }
enum atomicType : char { NON_ATOMIC = 0 , ATOMIC }
Static Public Member Functions inherited from IOstream
static unsigned int defaultPrecision () noexcept
static unsigned int defaultPrecision (unsigned int prec) noexcept
Static Public Member Functions inherited from IOstreamOption
static streamFormat formatEnum (const word &formatName, const streamFormat deflt=streamFormat::ASCII)
static streamFormat formatEnum (const word &key, const dictionary &dict, const streamFormat deflt=streamFormat::ASCII)
static compressionType compressionEnum (const word &compName, const compressionType deflt=compressionType::UNCOMPRESSED)
static compressionType compressionEnum (const word &key, const dictionary &dict, const compressionType deflt=compressionType::UNCOMPRESSED)
Static Public Attributes inherited from IOstream
static unsigned int precision_
Static Public Attributes inherited from IOstreamOption
static const Enum< streamFormat > formatNames
static const versionNumber currentVersion
Protected Types inherited from UIListStreamAllocator
typedef std::istream stream_type
Protected Member Functions inherited from IListStreamAllocator
IListStreamAllocator ()
IListStreamAllocator (List< char > &&buffer)
template<int SizeMin>
IListStreamAllocator (DynamicList< char, SizeMin > &&buffer)
void reset_gbuffer ()
Protected Member Functions inherited from UIListStreamAllocator
UIListStreamAllocator (char *buffer, size_t nbytes)
void reset (char *buffer, size_t nbytes)
void printBufInfo (Ostream &os) const
Protected Member Functions inherited from Istream
bool hasPutback () const noexcept
Protected Member Functions inherited from IOstream
void setOpened () noexcept
void setClosed () noexcept
void setState (std::ios_base::iostate state) noexcept
void setGood () noexcept
Protected Attributes inherited from UIListStreamAllocator
memorybuf::in buf_
stream_type stream_
Protected Attributes inherited from IOstream
std::ios_base::iostate ioState_
streamAccess openClosed_
unsigned char sizeofLabel_
unsigned char sizeofScalar_
label lineNumber_
Static Protected Attributes inherited from IOstream
static fileName staticName_
Detailed Description
An input stream that reads from a List and manages the List storage. Similar to IStringStream but with a List for its storage instead of as string to allow reuse of List contents without copying.
See also
Foam::OListStream Foam::UIListStream Foam::UOListStream
Definition at line 130 of file IListStream.H.
Constructor & Destructor Documentation
IListStream() [1/3]
IListStream (IOstreamOption streamOpt = IOstreamOption()) inline explicit
Definition at line 142 of file IListStream.H.
IListStream() [2/3]
IListStream (::Foam::List< char > && buffer, IOstreamOption streamOpt = IOstreamOption()) inline explicit
Definition at line 152 of file IListStream.H.
IListStream() [3/3]
template<int SizeMin> IListStream (DynamicList< char, SizeMin > && buffer, IOstreamOption streamOpt = IOstreamOption()) inline explicit
Definition at line 165 of file IListStream.H.
Member Function Documentation
pos()
std::streampos pos () const inline
Definition at line 183 of file IListStream.H.
References UIListStreamAllocator::tellg().
rewind()
virtual void rewind () inline virtual
Reimplemented from ISstream.
Definition at line 189 of file IListStream.H.
References UIListStreamAllocator::rewind(), and IOstream::setGood().
print()
void print (Ostream & os) const virtual
Reimplemented from ISstream.
Definition at line 27 of file ListStream.C.
References Foam::endl(), os(), and UIListStreamAllocator::printBufInfo().
operator()()
Istream & operator() () const inline
Definition at line 204 of file IListStream.H.
size()
label size () const inline
Definition at line 103 of file UIListStream.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOstreams/memory/IListStream.H
src/OpenFOAM/db/IOstreams/memory/ListStream.C