OpenFOAM: Kutadeladze Class Reference
Kutadeladze Class Reference
Nucleate flux sub-cooling correlation.
#include <Kutadeladze.H>
Public Member Functions
TypeName ("Kutadeladze")
Kutadeladze (const dictionary &dict)
virtual ~Kutadeladze ()=default
virtual tmp< scalarField > qNucleate (const phaseModel &liquid, const phaseModel &vapor, const label patchi, const scalarField &Tl, const scalarField &Tsatw, const scalarField &L) const
virtual void write (Ostream &os) const
Public Member Functions inherited from nucleateFluxModel
TypeName ("nucleateFluxModel")
declareRunTimeSelectionTable (autoPtr, nucleateFluxModel, dictionary,(const dictionary &dict),(dict))
nucleateFluxModel ()=default
virtual ~nucleateFluxModel ()=default
Additional Inherited Members
Static Public Member Functions inherited from nucleateFluxModel
static autoPtr< nucleateFluxModel > New (const dictionary &dict)
Detailed Description
Nucleate flux sub-cooling correlation.
References:
    Wang, L., Li, Y., Zhang, F., Xie, F., & Ma, Y. (2016).
    Correlations for calculating heat transfer of hydrogen pool boiling.
    International Journal of Hydrogen Energy, 41(38), 17118-17131.
Usage
Example of the model specification:
nucleateFluxModel
{
    // Mandatory entries
    type            Kutadeladze;
    // Optional entries
    Cn              <scalar>;
    an              <scalar>;
    bn              <scalar>;
    n               <scalar>;
}
where the entries mean:
Property Description Type Reqd Deflt
type Type name: Kutadeladze word yes -
Cn Model coefficient scalar no 5.66e-10
an Coefficient for deltaT sub-cooling scalar no 2.5
bn Exponent for n scalar no 1
n Nucleating boiling paramemeter scalar no 1
Source files
Kutadeladze.H
Kutadeladze.C
Definition at line 119 of file Kutadeladze.H.
Constructor & Destructor Documentation
Kutadeladze()
Kutadeladze (const dictionary & dict)
Definition at line 48 of file Kutadeladze.C.
~Kutadeladze()
virtual ~Kutadeladze () virtual default
Member Function Documentation
TypeName()
TypeName ("Kutadeladze")
qNucleate()
Foam::tmp< Foam::scalarField > qNucleate (const phaseModel & liquid, const phaseModel & vapor, const label patchi, const scalarField & Tl, const scalarField & Tsatw, const scalarField & L) const virtual
Implements nucleateFluxModel.
Definition at line 64 of file Kutadeladze.C.
References cells, liquid::Cp(), liquid::kappa(), L, Foam::max(), liquid::mu(), p, Foam::pow(), and liquid::sigma().
write()
void write (Ostream & os) const virtual
Reimplemented from nucleateFluxModel.
Definition at line 114 of file Kutadeladze.C.
References os(), and nucleateFluxModel::write().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/wallBoilingSubModels/nucleateFluxModels/Kutadeladze/Kutadeladze.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/wallBoilingSubModels/nucleateFluxModels/Kutadeladze/Kutadeladze.C