OpenFOAM: meshStructure Class Reference
meshStructure Class Reference
Detect extruded mesh structure given a set of faces (uindirectPrimitivePatch).
#include <meshStructure.H>
Public Member Functions
ClassName ("meshStructure")
meshStructure (const polyMesh &mesh, const uindirectPrimitivePatch &)
meshStructure (const polyMesh &mesh, const uindirectPrimitivePatch &, const globalIndex &globalFaces, const globalIndex &globalEdges, const globalIndex &globalPoints)
bool structured () const
const labelList & cellToPatchFaceAddressing () const
labelList & cellToPatchFaceAddressing ()
const labelList & cellLayer () const
labelList & cellLayer ()
const labelList & faceToPatchFaceAddressing () const
labelList & faceToPatchFaceAddressing ()
const labelList & faceToPatchEdgeAddressing () const
labelList & faceToPatchEdgeAddressing ()
const labelList & faceLayer () const
labelList & faceLayer ()
const labelList & pointToPatchPointAddressing () const
labelList & pointToPatchPointAddressing ()
const labelList & pointLayer () const
labelList & pointLayer ()
Detailed Description
Detect extruded mesh structure given a set of faces (uindirectPrimitivePatch).
All indices to originating set are in terms of global faces, global edges, global points.
Source files
meshStructure.H
meshStructure.C
Definition at line 57 of file meshStructure.H.
Constructor & Destructor Documentation
meshStructure() [1/2]
meshStructure (const polyMesh & mesh, const uindirectPrimitivePatch & pp)
Definition at line 393 of file meshStructure.C.
References correct(), mesh, PrimitivePatch< FaceList, PointField >::nEdges(), PrimitivePatch< FaceList, PointField >::nPoints(), and pp().
meshStructure() [2/2]
meshStructure (const polyMesh & mesh, const uindirectPrimitivePatch & pp, const globalIndex & globalFaces, const globalIndex & globalEdges, const globalIndex & globalPoints)
Definition at line 410 of file meshStructure.C.
References correct(), mesh, and pp().
Member Function Documentation
ClassName()
ClassName ("meshStructure")
structured()
bool structured () const inline
Definition at line 25 of file meshStructureI.H.
cellToPatchFaceAddressing() [1/2]
const Foam::labelList & cellToPatchFaceAddressing () const inline
Definition at line 31 of file meshStructureI.H.
cellToPatchFaceAddressing() [2/2]
Foam::labelList & cellToPatchFaceAddressing () inline
Definition at line 37 of file meshStructureI.H.
cellLayer() [1/2]
const Foam::labelList & cellLayer () const inline
Definition at line 43 of file meshStructureI.H.
cellLayer() [2/2]
Foam::labelList & cellLayer () inline
Definition at line 49 of file meshStructureI.H.
faceToPatchFaceAddressing() [1/2]
const Foam::labelList & faceToPatchFaceAddressing () const inline
Definition at line 55 of file meshStructureI.H.
faceToPatchFaceAddressing() [2/2]
Foam::labelList & faceToPatchFaceAddressing () inline
Definition at line 61 of file meshStructureI.H.
faceToPatchEdgeAddressing() [1/2]
const Foam::labelList & faceToPatchEdgeAddressing () const inline
Definition at line 67 of file meshStructureI.H.
faceToPatchEdgeAddressing() [2/2]
Foam::labelList & faceToPatchEdgeAddressing () inline
Definition at line 73 of file meshStructureI.H.
faceLayer() [1/2]
const Foam::labelList & faceLayer () const inline
Definition at line 79 of file meshStructureI.H.
faceLayer() [2/2]
Foam::labelList & faceLayer () inline
Definition at line 85 of file meshStructureI.H.
pointToPatchPointAddressing() [1/2]
const Foam::labelList & pointToPatchPointAddressing () const inline
Definition at line 91 of file meshStructureI.H.
pointToPatchPointAddressing() [2/2]
Foam::labelList & pointToPatchPointAddressing () inline
Definition at line 97 of file meshStructureI.H.
pointLayer() [1/2]
const Foam::labelList & pointLayer () const inline
Definition at line 103 of file meshStructureI.H.
pointLayer() [2/2]
Foam::labelList & pointLayer () inline
Definition at line 109 of file meshStructureI.H.
The documentation for this class was generated from the following files:
src/meshTools/meshStructure/meshStructure.H
src/meshTools/meshStructure/meshStructure.C
src/meshTools/meshStructure/meshStructureI.H