OpenFOAM: matchedFlowRateOutletVelocityFvPatchVectorField Class Reference
matchedFlowRateOutletVelocityFvPatchVectorField Class Reference
Boundary conditions » Outlet
Velocity outlet boundary condition which corrects the extrapolated velocity to match the flow rate of the specified corresponding inlet patch.
#include <matchedFlowRateOutletVelocityFvPatchVectorField.H>
Public Member Functions
TypeName ("matchedFlowRateOutletVelocity")
matchedFlowRateOutletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
matchedFlowRateOutletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
matchedFlowRateOutletVelocityFvPatchVectorField (const matchedFlowRateOutletVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
matchedFlowRateOutletVelocityFvPatchVectorField (const matchedFlowRateOutletVelocityFvPatchVectorField &)
virtual tmp< fvPatchVectorField > clone () const
matchedFlowRateOutletVelocityFvPatchVectorField (const matchedFlowRateOutletVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
Velocity outlet boundary condition which corrects the extrapolated velocity to match the flow rate of the specified corresponding inlet patch.
Usage
Property Description Required Default value
inletPatch Corresponding inlet patch name yes
volumetric Set volumetric or mass flow-rate no false
rho density field name no rho
Example of the boundary condition specification for a volumetric flow rate:
    <patchName>
    {
        type                matchedFlowRateOutletVelocity;
        inletPatch          inlet;
        value               uniform (0 0 0);
    }
See also
Foam::fixedValueFvPatchField
Source files
matchedFlowRateOutletVelocityFvPatchVectorField.H
matchedFlowRateOutletVelocityFvPatchVectorField.C
Definition at line 91 of file matchedFlowRateOutletVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
matchedFlowRateOutletVelocityFvPatchVectorField() [1/5]
matchedFlowRateOutletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Definition at line 29 of file matchedFlowRateOutletVelocityFvPatchVectorField.C.
matchedFlowRateOutletVelocityFvPatchVectorField() [2/5]
matchedFlowRateOutletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Definition at line 43 of file matchedFlowRateOutletVelocityFvPatchVectorField.C.
References UPstream::blocking, and dict.
matchedFlowRateOutletVelocityFvPatchVectorField() [3/5]
matchedFlowRateOutletVelocityFvPatchVectorField (const matchedFlowRateOutletVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 73 of file matchedFlowRateOutletVelocityFvPatchVectorField.C.
matchedFlowRateOutletVelocityFvPatchVectorField() [4/5]
matchedFlowRateOutletVelocityFvPatchVectorField (const matchedFlowRateOutletVelocityFvPatchVectorField & ptf)
Definition at line 89 of file matchedFlowRateOutletVelocityFvPatchVectorField.C.
matchedFlowRateOutletVelocityFvPatchVectorField() [5/5]
matchedFlowRateOutletVelocityFvPatchVectorField (const matchedFlowRateOutletVelocityFvPatchVectorField & ptf, const DimensionedField< vector, volMesh > & iF)
Definition at line 102 of file matchedFlowRateOutletVelocityFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("matchedFlowRateOutletVelocity")
clone() [1/2]
virtual tmp< fvPatchVectorField > clone () const inline virtual
Definition at line 160 of file matchedFlowRateOutletVelocityFvPatchVectorField.H.
clone() [2/2]
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Definition at line 176 of file matchedFlowRateOutletVelocityFvPatchVectorField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 181 of file matchedFlowRateOutletVelocityFvPatchVectorField.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and rho.
write()
void write (Ostream & os) const virtual
Definition at line 231 of file matchedFlowRateOutletVelocityFvPatchVectorField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntry(), Ostream::writeEntryIfDifferent(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/matchedFlowRateOutletVelocity/matchedFlowRateOutletVelocityFvPatchVectorField.H
src/finiteVolume/fields/fvPatchFields/derived/matchedFlowRateOutletVelocity/matchedFlowRateOutletVelocityFvPatchVectorField.C