OpenFOAM: IndirectList< T > Class Template Reference
IndirectList< T > Class Template Reference
A List with indirect addressing.
#include <IndirectList.H>
Public Member Functions
IndirectList (const UList< T > &values, const labelUList &addr)
IndirectList (const UList< T > &values, labelList &&addr)
IndirectList (const UList< T > &values, const Foam::zero)
IndirectList (const IndirectList< T > &list)
IndirectList (IndirectList< T > &&list)
IndirectList (const UIndirectList< T > &list)
void operator= (const IndirectList< T > &rhs)
template<class UnaryCondition >
Foam::IndirectList< T > subset (const UList< T > &values, const UnaryCondition &select, const bool invert)
template<class UnaryPredicate >
Foam::IndirectList< T > subset_if (const UList< T > &values, const UnaryPredicate &pred, const bool invert)
const Addr & addressing () const noexcept
Addr & addressing () noexcept
Public Member Functions inherited from UIndirectList< T >
UIndirectList (const UList< T > &values, const labelUList &addr)
UIndirectList (const UIndirectList< T > &list)
void operator= (const UIndirectList< T > &rhs)
Public Member Functions inherited from IndirectListBase< T, labelUList >
IndirectListBase ()=delete
IndirectListBase (const UList< T > &values, const labelUList &addr)
bool empty () const noexcept
label size () const noexcept
const UList< T > & values () const noexcept
UList< T > & values () noexcept
const labelUList & addressing () const noexcept
bool uniform () const
const T & front () const
T & front ()
const T & back () const
T & back ()
label fcIndex (const label i) const
label rcIndex (const label i) const
const T & fcValue (const label i) const
T & fcValue (const label i)
const T & rcValue (const label i) const
T & rcValue (const label i)
List< T > list () const
label find (const T &val, label pos=0) const
label rfind (const T &val, label pos=-1) const
bool contains (const T &val, label pos=0) const
List< T > operator() () const
T & operator[] (const label i)
const T & operator[] (const label i) const
void operator= (const T &val)
void operator= (const Foam::zero)
void operator= (const UList< T > &rhs)
void operator= (const IndirectListBase< T, labelUList > &rhs)
void operator= (const IndirectListBase< T, AnyAddr > &rhs)
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
const_iterator cbegin () const
const_iterator cend () const
Ostream & writeList (Ostream &os, const label shortLen=0) const
T & first ()
const T & first () const
T & last ()
const T & last () const
bool found (const T &val, label pos=0) const
Static Public Member Functions
template<class UnaryCondition >
static IndirectList< T > subset (const UList< T > &values, const UnaryCondition &select, const bool invert=false)
template<class UnaryPredicate >
static IndirectList< T > subset_if (const UList< T > &values, const UnaryPredicate &pred, const bool invert=false)
static IndirectList< T > uniq (const UList< T > &values, const bool sorted=false)
Additional Inherited Members
Public Types inherited from IndirectListBase< T, labelUList >
typedef T value_type
typedef T * pointer
typedef const T * const_pointer
typedef T & reference
typedef const T & const_reference
typedef label size_type
typedef label difference_type
typedef labelUList addressing_type
Protected Member Functions inherited from IndirectListBase< T, labelUList >
void copyList (const ListType &rhs)
Detailed Description
template<class T>
class Foam::IndirectList< T >
A List with indirect addressing.
See also
Foam::UIndirectList for a version without addressing allocation.
Definition at line 112 of file IndirectList.H.
Constructor & Destructor Documentation
IndirectList() [1/6]
template<class T > IndirectList (const UList< T > & values, const labelUList & addr) inline
Definition at line 25 of file IndirectListI.H.
IndirectList() [2/6]
template<class T > IndirectList (const UList< T > & values, labelList && addr) inline
Definition at line 41 of file IndirectListI.H.
IndirectList() [3/6]
template<class T > IndirectList (const UList< T > & values, const Foam::zero) inline
Definition at line 57 of file IndirectListI.H.
IndirectList() [4/6]
template<class T > IndirectList (const IndirectList< T > & list) inline
Definition at line 73 of file IndirectListI.H.
IndirectList() [5/6]
template<class T > IndirectList (IndirectList< T > && list) inline
Definition at line 86 of file IndirectListI.H.
IndirectList() [6/6]
template<class T > IndirectList (const UIndirectList< T > & list) inline explicit
Definition at line 99 of file IndirectListI.H.
Member Function Documentation
subset() [1/2]
template<class T > template<class UnaryCondition > static IndirectList< T > subset (const UList< T > & values, const UnaryCondition & select, const bool invert = false) static
subset_if() [1/2]
template<class T > template<class UnaryPredicate > static IndirectList< T > subset_if (const UList< T > & values, const UnaryPredicate & pred, const bool invert = false) static
uniq()
template<class T > Foam::IndirectList< T > uniq (const UList< T > & values, const bool sorted = false) static
Definition at line 178 of file IndirectListI.H.
References PtrList< T >::resize(), Foam::sort(), and Foam::sortedOrder().
operator=()
template<class T > void operator= (const IndirectList< T > & rhs) inline
Definition at line 199 of file IndirectList.H.
References IndirectListBase< T, labelUList >::copyList().
subset() [2/2]
template<class T > template<class UnaryCondition > Foam::IndirectList< T > subset (const UList< T > & values, const UnaryCondition & select, const bool invert)
Definition at line 115 of file IndirectListI.H.
References Foam::invert(), and PtrList< T >::resize().
subset_if() [2/2]
template<class T > template<class UnaryPredicate > Foam::IndirectList< T > subset_if (const UList< T > & values, const UnaryPredicate & pred, const bool invert)
Definition at line 147 of file IndirectListI.H.
References Foam::invert(), and PtrList< T >::resize().
addressing() [1/2]
template<class T > const Addr & addressing () const inline noexcept
Definition at line 72 of file IndirectListAddressing.H.
addressing() [2/2]
template<class T > Addr & addressing () inline noexcept
Definition at line 78 of file IndirectListAddressing.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/IndirectLists/IndirectList/IndirectList.H
src/OpenFOAM/containers/IndirectLists/IndirectList/IndirectListI.H