OpenFOAM: PrimitivePatchInterpolation< Patch > Class Template Reference
PrimitivePatchInterpolation< Patch > Class Template Reference
Interpolation class within a primitive patch. Allows interpolation from points to faces and vice versa.
#include <PrimitivePatchInterpolation.H>
Public Member Functions
PrimitivePatchInterpolation (const Patch &p)
~PrimitivePatchInterpolation ()=default
template<class Type >
tmp< Field< Type > > faceToPointInterpolate (const Field< Type > &ff) const
template<class Type >
tmp< Field< Type > > faceToPointInterpolate (const tmp< Field< Type > > &tff) const
template<class Type >
tmp< Field< Type > > pointToFaceInterpolate (const Field< Type > &pf) const
template<class Type >
tmp< Field< Type > > pointToFaceInterpolate (const tmp< Field< Type > > &tpf) const
template<class Type >
tmp< Field< Type > > faceToEdgeInterpolate (const Field< Type > &ff) const
template<class Type >
tmp< Field< Type > > faceToEdgeInterpolate (const tmp< Field< Type > > &tff) const
bool movePoints ()
template<class Type >
Foam::tmp< Foam::Field< Type > > faceToPointInterpolate (const Field< Type > &ff) const
template<class Type >
Foam::tmp< Foam::Field< Type > > faceToPointInterpolate (const tmp< Field< Type > > &tff) const
template<class Type >
Foam::tmp< Foam::Field< Type > > pointToFaceInterpolate (const Field< Type > &pf) const
template<class Type >
Foam::tmp< Foam::Field< Type > > pointToFaceInterpolate (const tmp< Field< Type > > &tpf) const
template<class Type >
Foam::tmp< Foam::Field< Type > > faceToEdgeInterpolate (const Field< Type > &pf) const
template<class Type >
Foam::tmp< Foam::Field< Type > > faceToEdgeInterpolate (const tmp< Field< Type > > &tpf) const
Detailed Description
template<class Patch>
class Foam::PrimitivePatchInterpolation< Patch >
Interpolation class within a primitive patch. Allows interpolation from points to faces and vice versa.
Source files
PrimitivePatchInterpolation.H
PrimitivePatchInterpolation.C
Definition at line 53 of file PrimitivePatchInterpolation.H.
Constructor & Destructor Documentation
PrimitivePatchInterpolation()
template<class Patch > PrimitivePatchInterpolation (const Patch & p)
Definition at line 141 of file PrimitivePatchInterpolation.C.
~PrimitivePatchInterpolation()
template<class Patch > ~PrimitivePatchInterpolation () default
Member Function Documentation
faceToPointInterpolate() [1/4]
template<class Patch > template<class Type > tmp< Field< Type > > faceToPointInterpolate (const Field< Type > & ff) const
faceToPointInterpolate() [2/4]
template<class Patch > template<class Type > tmp< Field< Type > > faceToPointInterpolate (const tmp< Field< Type > > & tff) const
pointToFaceInterpolate() [1/4]
template<class Patch > template<class Type > tmp< Field< Type > > pointToFaceInterpolate (const Field< Type > & pf) const
pointToFaceInterpolate() [2/4]
template<class Patch > template<class Type > tmp< Field< Type > > pointToFaceInterpolate (const tmp< Field< Type > > & tpf) const
faceToEdgeInterpolate() [1/4]
template<class Patch > template<class Type > tmp< Field< Type > > faceToEdgeInterpolate (const Field< Type > & ff) const
faceToEdgeInterpolate() [2/4]
template<class Patch > template<class Type > tmp< Field< Type > > faceToEdgeInterpolate (const tmp< Field< Type > > & tff) const
movePoints()
template<class Patch > bool movePoints ()
Definition at line 313 of file PrimitivePatchInterpolation.C.
faceToPointInterpolate() [3/4]
template<class Patch > template<class Type > Foam::tmp< Foam::Field< Type > > faceToPointInterpolate (const Field< Type > & ff) const
Definition at line 157 of file PrimitivePatchInterpolation.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::New(), UPtrList< T >::size(), and Foam::Zero.
faceToPointInterpolate() [4/4]
template<class Patch > template<class Type > Foam::tmp< Foam::Field< Type > > faceToPointInterpolate (const tmp< Field< Type > > & tff) const
Definition at line 195 of file PrimitivePatchInterpolation.C.
References PtrList< T >::clear().
pointToFaceInterpolate() [3/4]
template<class Patch > template<class Type > Foam::tmp< Foam::Field< Type > > pointToFaceInterpolate (const Field< Type > & pf) const
Definition at line 209 of file PrimitivePatchInterpolation.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::New(), UPtrList< T >::size(), UList< T >::size(), and Foam::Zero.
pointToFaceInterpolate() [4/4]
template<class Patch > template<class Type > Foam::tmp< Foam::Field< Type > > pointToFaceInterpolate (const tmp< Field< Type > > & tpf) const
Definition at line 246 of file PrimitivePatchInterpolation.C.
References PtrList< T >::clear().
faceToEdgeInterpolate() [3/4]
template<class Patch > template<class Type > Foam::tmp< Foam::Field< Type > > faceToEdgeInterpolate (const Field< Type > & pf) const
Definition at line 260 of file PrimitivePatchInterpolation.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, Foam::New(), UPtrList< T >::size(), UList< T >::size(), and Foam::Zero.
faceToEdgeInterpolate() [4/4]
template<class Patch > template<class Type > Foam::tmp< Foam::Field< Type > > faceToEdgeInterpolate (const tmp< Field< Type > > & tpf) const
Definition at line 301 of file PrimitivePatchInterpolation.C.
References PtrList< T >::clear().
The documentation for this class was generated from the following files:
src/OpenFOAM/interpolations/primitivePatchInterpolation/PrimitivePatchInterpolation.H
src/OpenFOAM/interpolations/primitivePatchInterpolation/PrimitivePatchInterpolation.C