OpenFOAM: heSolidThermo< BasicSolidThermo, MixtureType > Class Template Reference
heSolidThermo< BasicSolidThermo, MixtureType > Class Template Reference
Energy for a solid mixture.
#include <heSolidThermo.H>
Public Member Functions
TypeName ("heSolidThermo")
heSolidThermo (const fvMesh &, const word &phaseName)
heSolidThermo (const fvMesh &, const dictionary &, const word &phaseName)
heSolidThermo (const fvMesh &, const word &phaseName, const word &dictName)
virtual ~heSolidThermo ()
virtual void correct ()
virtual tmp< volVectorField > Kappa () const
virtual bool isotropic () const
virtual tmp< vectorField > Kappa (const label patchi) const
Public Member Functions inherited from heThermo< BasicSolidThermo, MixtureType >
heThermo (const fvMesh &, const word &phaseName)
heThermo (const fvMesh &, const dictionary &, const word &phaseName)
heThermo (const fvMesh &, const word &phaseName, const word &dictionaryName)
virtual ~heThermo ()
virtual MixtureType::basicMixtureType & composition ()
virtual const MixtureType::basicMixtureType & composition () const
virtual word thermoName () const
virtual bool incompressible () const
virtual bool isochoric () const
virtual volScalarField & he ()
virtual const volScalarField & he () const
virtual tmp< volScalarField > he (const volScalarField &p, const volScalarField &T) const
virtual tmp< scalarField > he (const scalarField &p, const scalarField &T, const labelList &cells) const
virtual tmp< scalarField > he (const scalarField &p, const scalarField &T, const label patchi) const
virtual tmp< volScalarField > hc () const
virtual tmp< scalarField > THE (const scalarField &he, const scalarField &p, const scalarField &T0, const labelList &cells) const
virtual tmp< scalarField > THE (const scalarField &he, const scalarField &p, const scalarField &T0, const label patchi) const
virtual tmp< scalarField > Cp (const scalarField &p, const scalarField &T, const label patchi) const
virtual tmp< scalarField > Cp (const scalarField &p, const scalarField &T, const labelList &cells) const
virtual tmp< volScalarField > Cp () const
virtual tmp< scalarField > Cv (const scalarField &p, const scalarField &T, const label patchi) const
virtual tmp< volScalarField > Cv () const
virtual tmp< scalarField > rhoEoS (const scalarField &p, const scalarField &T, const labelList &cells) const
virtual tmp< volScalarField > gamma () const
virtual tmp< scalarField > gamma (const scalarField &p, const scalarField &T, const label patchi) const
virtual tmp< scalarField > Cpv (const scalarField &p, const scalarField &T, const label patchi) const
virtual tmp< volScalarField > Cpv () const
virtual tmp< volScalarField > CpByCpv () const
virtual tmp< scalarField > CpByCpv (const scalarField &p, const scalarField &T, const label patchi) const
virtual tmp< volScalarField > W () const
virtual tmp< volScalarField > kappa () const
virtual tmp< scalarField > kappa (const label patchi) const
virtual tmp< volScalarField > alphahe () const
virtual tmp< scalarField > alphahe (const label patchi) const
virtual tmp< volScalarField > kappaEff (const volScalarField &) const
virtual tmp< scalarField > kappaEff (const scalarField &alphat, const label patchi) const
virtual tmp< volScalarField > alphaEff (const volScalarField &alphat) const
virtual tmp< scalarField > alphaEff (const scalarField &alphat, const label patchi) const
virtual bool read ()
Additional Inherited Members
Protected Member Functions inherited from heThermo< BasicSolidThermo, MixtureType >
void heBoundaryCorrection (volScalarField &he)
Protected Attributes inherited from heThermo< BasicSolidThermo, MixtureType >
volScalarField he_
Detailed Description
template<class BasicSolidThermo, class MixtureType>
class Foam::heSolidThermo< BasicSolidThermo, MixtureType >
Energy for a solid mixture.
Source files
heSolidThermo.H
heSolidThermo.C
Definition at line 48 of file heSolidThermo.H.
Constructor & Destructor Documentation
heSolidThermo() [1/3]
template<class BasicSolidThermo , class MixtureType > heSolidThermo (const fvMesh & mesh, const word & phaseName)
Definition at line 137 of file heSolidThermo.C.
References Foam::Zero.
heSolidThermo() [2/3]
template<class BasicSolidThermo , class MixtureType > heSolidThermo (const fvMesh & mesh, const dictionary & dict, const word & phaseName)
Definition at line 153 of file heSolidThermo.C.
References Foam::Zero.
heSolidThermo() [3/3]
template<class BasicSolidThermo , class MixtureType > heSolidThermo (const fvMesh & mesh, const word & phaseName, const word & dictName)
Definition at line 170 of file heSolidThermo.C.
References Foam::Zero.
~heSolidThermo()
template<class BasicSolidThermo , class MixtureType > ~heSolidThermo () virtual
Definition at line 192 of file heSolidThermo.C.
Member Function Documentation
TypeName()
template<class BasicSolidThermo , class MixtureType > TypeName ("heSolidThermo< BasicSolidThermo, MixtureType >")
correct()
template<class BasicSolidThermo , class MixtureType > void correct () virtual
Definition at line 199 of file heSolidThermo.C.
References DebugInfo, DebugInFunction, Foam::endl(), and Foam::nl.
Kappa() [1/2]
template<class BasicSolidThermo , class MixtureType > Foam::tmp< Foam::volVectorField > Kappa () const virtual
Definition at line 211 of file heSolidThermo.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), Foam::dimEnergy, Foam::dimLength, Foam::dimTemperature, Foam::dimTime, forAll, mesh, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, pp(), GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef(), and fvMesh::time().
isotropic()
template<class BasicSolidThermo , class MixtureType > virtual bool isotropic () const inline virtual
Definition at line 109 of file heSolidThermo.H.
Kappa() [2/2]
template<class BasicSolidThermo , class MixtureType > Foam::tmp< Foam::vectorField > Kappa (const label patchi) const virtual
Definition at line 275 of file heSolidThermo.C.
References forAll, and pp().
The documentation for this class was generated from the following files:
src/thermophysicalModels/solidThermo/solidThermo/heSolidThermo.H
src/thermophysicalModels/solidThermo/solidThermo/heSolidThermo.C