OpenFOAM: noPreconditioner Class Reference
noPreconditioner Class Reference
Numerics » Matrix manipulation and solvers » Preconditioners
Null preconditioner for both symmetric and asymmetric matrices.
#include <noPreconditioner.H>
Public Member Functions
TypeName ("none")
noPreconditioner (const lduMatrix::solver &, const dictionary &solverControlsUnused)
virtual ~noPreconditioner ()=default
virtual void precondition (solveScalarField &wA, const solveScalarField &rA, const direction cmpt=0) const
virtual void preconditionT (solveScalarField &wT, const solveScalarField &rT, const direction cmpt=0) const
Public Member Functions inherited from lduMatrix::preconditioner
virtual const word & type () const =0
declareRunTimeSelectionTable (autoPtr, preconditioner, symMatrix,(const solver &sol, const dictionary &solverControls),(sol, solverControls))
declareRunTimeSelectionTable (autoPtr, preconditioner, asymMatrix,(const solver &sol, const dictionary &solverControls),(sol, solverControls))
preconditioner (const solver &sol)
virtual ~preconditioner ()=default
virtual void read (const dictionary &)
virtual void setFinished (const solverPerformance &perf) const
Additional Inherited Members
Static Public Member Functions inherited from lduMatrix::preconditioner
static word getName (const dictionary &)
static autoPtr< preconditioner > New (const solver &sol, const dictionary &solverControls)
Protected Attributes inherited from lduMatrix::preconditioner
const solver & solver_
Detailed Description
Null preconditioner for both symmetric and asymmetric matrices.
Source files
noPreconditioner.H
noPreconditioner.C
Definition at line 50 of file noPreconditioner.H.
Constructor & Destructor Documentation
noPreconditioner()
noPreconditioner (const lduMatrix::solver & sol, const dictionary & solverControlsUnused)
Definition at line 42 of file noPreconditioner.C.
~noPreconditioner()
virtual ~noPreconditioner () virtual default
Member Function Documentation
TypeName()
TypeName ("none")
precondition()
void precondition (solveScalarField & wA, const solveScalarField & rA, const direction cmpt = 0) const virtual
Implements lduMatrix::preconditioner.
Definition at line 54 of file noPreconditioner.C.
References UPtrList< T >::begin(), and UPtrList< T >::size().
Referenced by noPreconditioner::preconditionT().
preconditionT()
virtual void preconditionT (solveScalarField & wT, const solveScalarField & rT, const direction cmpt = 0) const inline virtual
Reimplemented from lduMatrix::preconditioner.
Definition at line 94 of file noPreconditioner.H.
References noPreconditioner::precondition().
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/lduMatrix/preconditioners/noPreconditioner/noPreconditioner.H
src/OpenFOAM/matrices/lduMatrix/preconditioners/noPreconditioner/noPreconditioner.C