OpenFOAM: sine Class Reference
sine Class Reference
#include <sineWallDamping.H>
Public Member Functions
TypeName ("sine")
sine (const dictionary &dict, const phasePair &pair)
virtual ~sine ()
Public Member Functions inherited from interpolated
TypeName ("interpolated")
interpolated (const dictionary &dict, const phasePair &pair)
virtual ~interpolated ()
virtual tmp< volScalarField > damp (const tmp< volScalarField > &) const
virtual tmp< volVectorField > damp (const tmp< volVectorField > &) const
virtual tmp< surfaceScalarField > damp (const tmp< surfaceScalarField > &) const
Public Member Functions inherited from wallDampingModel
TypeName ("wallDampingModel")
declareRunTimeSelectionTable (autoPtr, wallDampingModel, dictionary,(const dictionary &dict, const phasePair &pair),(dict, pair))
wallDampingModel (const dictionary &dict, const phasePair &pair)
virtual ~wallDampingModel ()=default
Public Member Functions inherited from wallDependentModel
wallDependentModel (const fvMesh &mesh)
virtual ~wallDependentModel ()
const volScalarField & yWall () const
const volVectorField & nWall () const
wallDependentModel (const fvMesh &mesh)
virtual ~wallDependentModel ()
const volScalarField & yWall () const
const volVectorField & nWall () const
Protected Member Functions
virtual tmp< volScalarField > limiter () const
Additional Inherited Members
Static Public Member Functions inherited from wallDampingModel
static autoPtr< wallDampingModel > New (const dictionary &dict, const phasePair &pair)
Static Public Attributes inherited from wallDampingModel
static const dimensionSet dimF
Protected Attributes inherited from wallDampingModel
const phasePair & pair_
Detailed Description
Source files
sineWallDamping.H
sineWallDamping.C
Definition at line 50 of file sineWallDamping.H.
Constructor & Destructor Documentation
sine()
sine (const dictionary & dict, const phasePair & pair)
Definition at line 57 of file sineWallDamping.C.
~sine()
~sine () virtual
Definition at line 70 of file sineWallDamping.C.
Member Function Documentation
limiter()
Foam::tmp< Foam::volScalarField > limiter () const protected virtual
Implements interpolated.
Definition at line 45 of file sineWallDamping.C.
References Foam::min(), wallDampingModel::pair_, Foam::constant::mathematical::piByTwo(), Foam::sin(), and wallDependentModel::yWall().
TypeName()
TypeName ("sine")
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/interfacialModels/wallDampingModels/sine/sineWallDamping.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/interfacialModels/wallDampingModels/sine/sineWallDamping.C