OpenFOAM: wallNormalInfo Class Reference
wallNormalInfo Class Reference
Holds information regarding nearest wall point. Used in wall refinement.
#include <wallNormalInfo.H>
Public Member Functions
wallNormalInfo ()
wallNormalInfo (const vector &normal)
const vector & normal () const
vector & normal ()
template<class TrackingData >
bool valid (TrackingData &td) const
template<class TrackingData >
bool sameGeometry (const polyMesh &, const wallNormalInfo &, const scalar, TrackingData &td) const
template<class TrackingData >
void leaveDomain (const polyMesh &, const polyPatch &, const label patchFacei, const point &faceCentre, TrackingData &td)
template<class TrackingData >
void enterDomain (const polyMesh &, const polyPatch &, const label patchFacei, const point &faceCentre, TrackingData &td)
template<class TrackingData >
void transform (const polyMesh &, const tensor &, TrackingData &td)
template<class TrackingData >
bool updateCell (const polyMesh &, const label thisCelli, const label neighbourFacei, const wallNormalInfo &neighbourInfo, const scalar tol, TrackingData &td)
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFacei, const label neighbourCelli, const wallNormalInfo &neighbourInfo, const scalar tol, TrackingData &td)
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFacei, const wallNormalInfo &neighbourInfo, const scalar tol, TrackingData &td)
template<class TrackingData >
bool equal (const wallNormalInfo &, TrackingData &td) const
bool operator== (const wallNormalInfo &) const
bool operator!= (const wallNormalInfo &) const
Friends
Ostream & operator<< (Ostream &, const wallNormalInfo &)
Istream & operator>> (Istream &, wallNormalInfo &)
Detailed Description
Holds information regarding nearest wall point. Used in wall refinement.
Source files
wallNormalInfo.H
wallNormalInfoI.H
wallNormalInfo.C
Definition at line 60 of file wallNormalInfo.H.
Constructor & Destructor Documentation
wallNormalInfo() [1/2]
wallNormalInfo () inline
Definition at line 57 of file wallNormalInfoI.H.
wallNormalInfo() [2/2]
wallNormalInfo (const vector & normal) inline
Definition at line 63 of file wallNormalInfoI.H.
Member Function Documentation
normal() [1/2]
const vector & normal () const inline
Definition at line 91 of file wallNormalInfo.H.
Referenced by wallLayerCells::wallLayerCells().
normal() [2/2]
vector & normal () inline
Definition at line 95 of file wallNormalInfo.H.
valid()
template<class TrackingData > bool valid (TrackingData & td) const inline
Definition at line 72 of file wallNormalInfoI.H.
References VectorSpace< Form, Cmpt, Ncmpts >::max.
Referenced by wallLayerCells::wallLayerCells().
sameGeometry()
template<class TrackingData > bool sameGeometry (const polyMesh & , const wallNormalInfo & w2, const scalar tol, TrackingData & td) const inline
Definition at line 80 of file wallNormalInfoI.H.
leaveDomain()
template<class TrackingData > void leaveDomain (const polyMesh & , const polyPatch & patch, const label patchFacei, const point & faceCentre, TrackingData & td) inline
Definition at line 94 of file wallNormalInfoI.H.
enterDomain()
template<class TrackingData > void enterDomain (const polyMesh & , const polyPatch & patch, const label patchFacei, const point & faceCentre, TrackingData & td) inline
Definition at line 118 of file wallNormalInfoI.H.
transform()
template<class TrackingData > void transform (const polyMesh & , const tensor & rotTensor, TrackingData & td) inline
Definition at line 107 of file wallNormalInfoI.H.
updateCell()
template<class TrackingData > bool updateCell (const polyMesh & , const label thisCelli, const label neighbourFacei, const wallNormalInfo & neighbourInfo, const scalar tol, TrackingData & td) inline
Definition at line 131 of file wallNormalInfoI.H.
References update().
updateFace() [1/2]
template<class TrackingData > bool updateFace (const polyMesh & , const label thisFacei, const label neighbourCelli, const wallNormalInfo & neighbourInfo, const scalar tol, TrackingData & td) inline
Definition at line 147 of file wallNormalInfoI.H.
References update().
updateFace() [2/2]
template<class TrackingData > bool updateFace (const polyMesh & , const label thisFacei, const wallNormalInfo & neighbourInfo, const scalar tol, TrackingData & td) inline
Definition at line 163 of file wallNormalInfoI.H.
References update().
equal()
template<class TrackingData > bool equal (const wallNormalInfo & rhs, TrackingData & td) const inline
Definition at line 177 of file wallNormalInfoI.H.
References Foam::operator==().
operator==()
bool operator== (const wallNormalInfo & rhs) const inline
Definition at line 189 of file wallNormalInfoI.H.
operator!=()
bool operator!= (const wallNormalInfo & rhs) const inline
Definition at line 198 of file wallNormalInfoI.H.
Friends And Related Symbol Documentation
operator<<
Ostream & operator<< (Ostream & , const wallNormalInfo &) friend
operator>>
Istream & operator>> (Istream & , wallNormalInfo &) friend
The documentation for this class was generated from the following files:
src/dynamicMesh/meshCut/wallLayerCells/wallNormalInfo/wallNormalInfo.H
src/dynamicMesh/meshCut/wallLayerCells/wallNormalInfo/wallNormalInfoI.H