OpenFOAM: Gidaspow Class Reference
Gidaspow Class Reference
#include <GidaspowConductivity.H>
Public Member Functions
TypeName ("Gidaspow")
Gidaspow (const dictionary &dict)
virtual ~Gidaspow ()
tmp< volScalarField > kappa (const volScalarField &alpha1, const volScalarField &Theta, const volScalarField &g0, const volScalarField &rho1, const volScalarField &da, const dimensionedScalar &e) const
TypeName ("Gidaspow")
Gidaspow (const dictionary &dict)
virtual ~Gidaspow ()
tmp< volScalarField > kappa (const volScalarField &alpha1, const volScalarField &Theta, const volScalarField &g0, const volScalarField &rho1, const volScalarField &da, const dimensionedScalar &e) const
Public Member Functions inherited from conductivityModel
TypeName ("conductivityModel")
declareRunTimeSelectionTable (autoPtr, conductivityModel, dictionary,(const dictionary &dict),(dict))
conductivityModel (const dictionary &dict)
virtual ~conductivityModel ()=default
virtual bool read ()
TypeName ("conductivityModel")
declareRunTimeSelectionTable (autoPtr, conductivityModel, dictionary,(const dictionary &dict),(dict))
conductivityModel (const dictionary &dict)
virtual ~conductivityModel ()=default
virtual bool read ()
Additional Inherited Members
Static Public Member Functions inherited from conductivityModel
static autoPtr< conductivityModel > New (const dictionary &dict)
static autoPtr< conductivityModel > New (const dictionary &dict)
Protected Attributes inherited from conductivityModel
const dictionary & dict_
Detailed Description
Source files
GidaspowConductivity.H
Gidaspow.C
Source files
GidaspowConductivity.H
Gidaspow.C
Definition at line 49 of file GidaspowConductivity.H.
Constructor & Destructor Documentation
Gidaspow() [1/2]
Gidaspow (const dictionary & dict)
Definition at line 48 of file GidaspowConductivity.C.
~Gidaspow() [1/2]
~Gidaspow () virtual
Definition at line 59 of file GidaspowConductivity.C.
Gidaspow() [2/2]
Gidaspow (const dictionary & dict)
~Gidaspow() [2/2]
virtual ~Gidaspow () virtual
Member Function Documentation
TypeName() [1/2]
TypeName ("Gidaspow")
kappa() [1/2]
Foam::tmp< Foam::volScalarField > kappa (const volScalarField & alpha1, const volScalarField & Theta, const volScalarField & g0, const volScalarField & rho1, const volScalarField & da, const dimensionedScalar & e) const virtual
Implements conductivityModel.
Definition at line 66 of file GidaspowConductivity.C.
References alpha1, e, Foam::constant::mathematical::pi(), rho1, Foam::sqr(), and Foam::sqrt().
TypeName() [2/2]
TypeName ("Gidaspow")
kappa() [2/2]
tmp< volScalarField > kappa (const volScalarField & alpha1, const volScalarField & Theta, const volScalarField & g0, const volScalarField & rho1, const volScalarField & da, const dimensionedScalar & e) const virtual
Implements conductivityModel.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/twoPhaseCompressibleTurbulenceModels/kineticTheoryModels/conductivityModel/Gidaspow/GidaspowConductivity.H
src/phaseSystemModels/twoPhaseEuler/phaseCompressibleTurbulenceModels/kineticTheoryModels/conductivityModel/Gidaspow/GidaspowConductivity.H
src/phaseSystemModels/reactingEuler/twoPhaseCompressibleTurbulenceModels/kineticTheoryModels/conductivityModel/Gidaspow/GidaspowConductivity.C
src/phaseSystemModels/twoPhaseEuler/phaseCompressibleTurbulenceModels/kineticTheoryModels/conductivityModel/Gidaspow/GidaspowConductivity.C