OpenFOAM: coordinateSystem Class Reference
coordinateSystem Class Reference
Base class for coordinate system specification, the default coordinate system type is cartesian .
#include <coordinateSystem.H>
Classes
struct iNew
Public Member Functions
TypeName ("coordinateSystem")
coordinateSystem ()
coordinateSystem (const coordinateRotation &crot)
coordinateSystem (coordinateRotation &&crot)
coordinateSystem (const coordinateSystem &csys)
coordinateSystem (coordinateSystem &&csys)
coordinateSystem (autoPtr< coordinateSystem > &&csys)
coordinateSystem (const word &name, const coordinateSystem &csys)
coordinateSystem (const point &origin, const coordinateRotation &crot)
coordinateSystem (const point &origin, const vector &axis, const vector &dirn)
coordinateSystem (const word &name, const point &origin, const coordinateRotation &crot)
coordinateSystem (const word &name, const point &origin, const vector &axis, const vector &dirn)
coordinateSystem (const dictionary &dict, IOobjectOption::readOption readOrigin=IOobjectOption::MUST_READ)
coordinateSystem (const dictionary &dict, const word &dictName, IOobjectOption::readOption readOrigin=IOobjectOption::MUST_READ)
virtual autoPtr< coordinateSystem > clone () const
declareRunTimeSelectionTable (autoPtr, coordinateSystem, dictionary,(const dictionary &dict, IOobjectOption::readOption readOrigin),(dict, readOrigin))
declareRunTimeSelectionTable (autoPtr, coordinateSystem, registry,(const objectRegistry &obr, const dictionary &dict, IOobjectOption::readOption readOrigin),(obr, dict, readOrigin))
virtual ~coordinateSystem ()=default
virtual bool valid () const
virtual bool uniform () const
virtual const point & origin () const
virtual const coordinateRotation & rotation () const
virtual const word & name () const
virtual const string & note () const
virtual const tensor & R () const
virtual const vector e1 () const
virtual const vector e2 () const
virtual const vector e3 () const
virtual void rename (const word &newName)
virtual string & note ()
virtual point & origin ()
virtual void clear ()
virtual void rotation (autoPtr< coordinateRotation > &&crot)
virtual void write (Ostream &os) const
virtual void writeEntry (Ostream &os) const
virtual void writeEntry (const word &keyword, Ostream &os) const
void operator= (const coordinateSystem &csys)
void operator= (coordinateSystem &&csys)
void operator= (const autoPtr< coordinateSystem > &csys)
void operator= (autoPtr< coordinateSystem > &&csys)
virtual tensor R (const point &global) const
virtual tmp< tensorField > R (const UList< point > &global) const
virtual tmp< tensorField > R (const pointUIndList &global) const
point transformPoint (const point &localCart) const
tmp< pointField > transformPoint (const UList< point > &localCart) const
tmp< pointField > transformPoint (const pointUIndList &localCart) const
point invTransformPoint (const point &global) const
tmp< pointField > invTransformPoint (const UList< point > &global) const
tmp< pointField > invTransformPoint (const pointUIndList &global) const
point globalPosition (const point &local) const
tmp< pointField > globalPosition (const pointField &local) const
point localPosition (const point &global) const
tmp< pointField > localPosition (const pointField &global) const
vector globalVector (const vector &local) const
tmp< vectorField > globalVector (const vectorField &local) const
vector localVector (const vector &global) const
tmp< vectorField > localVector (const vectorField &global) const
virtual symmTensor transformPrincipal (const vector &input) const
With constant rotation tensor.
virtual tmp< Field< symmTensor > > transformPrincipal (const UList< vector > &input) const
With constant rotation tensor.
virtual symmTensor transformPrincipal (const point &global, const vector &input) const
With rotation tensor at given global position.
virtual tmp< Field< symmTensor > > transformPrincipal (const UList< point > &global, const vector &input) const
With rotation tensors at given global positions.
virtual tmp< Field< symmTensor > > transformPrincipal (const pointUIndList &global, const vector &input) const
With rotation tensors at given global positions.
virtual tmp< Field< symmTensor > > transformPrincipal (const UList< point > &global, const UList< vector > &input) const
With rotation tensors at given global positions.
virtual tmp< Field< symmTensor > > transformPrincipal (const pointUIndList &global, const UList< vector > &input) const
With rotation tensors at given global positions.
virtual scalar transform (const scalar &input) const
With constant rotation tensor.
virtual tmp< Field< scalar > > transform (const UList< scalar > &input) const
With constant rotation tensor.
virtual scalar transform (const point &global, const scalar &input) const
With rotation tensor at given global position.
virtual tmp< Field< scalar > > transform (const UList< point > &global, const scalar &input) const
With rotation tensors at given global positions.
virtual tmp< Field< scalar > > transform (const pointUIndList &global, const scalar &input) const
With rotation tensors at given global positions.
virtual tmp< Field< scalar > > transform (const UList< point > &global, const UList< scalar > &input) const
With rotation tensors at given global positions.
virtual tmp< Field< scalar > > transform (const pointUIndList &global, const UList< scalar > &input) const
With rotation tensors at given global positions.
virtual vector transform (const vector &input) const
With constant rotation tensor.
virtual tmp< Field< vector > > transform (const UList< vector > &input) const
With constant rotation tensor.
virtual vector transform (const point &global, const vector &input) const
With rotation tensor at given global position.
virtual tmp< Field< vector > > transform (const UList< point > &global, const vector &input) const
With rotation tensors at given global positions.
virtual tmp< Field< vector > > transform (const pointUIndList &global, const vector &input) const
With rotation tensors at given global positions.
virtual tmp< Field< vector > > transform (const UList< point > &global, const UList< vector > &input) const
With rotation tensors at given global positions.
virtual tmp< Field< vector > > transform (const pointUIndList &global, const UList< vector > &input) const
With rotation tensors at given global positions.
virtual sphericalTensor transform (const sphericalTensor &input) const
With constant rotation tensor.
virtual tmp< Field< sphericalTensor > > transform (const UList< sphericalTensor > &input) const
With constant rotation tensor.
virtual sphericalTensor transform (const point &global, const sphericalTensor &input) const
With rotation tensor at given global position.
virtual tmp< Field< sphericalTensor > > transform (const UList< point > &global, const sphericalTensor &input) const
With rotation tensors at given global positions.
virtual tmp< Field< sphericalTensor > > transform (const pointUIndList &global, const sphericalTensor &input) const
With rotation tensors at given global positions.
virtual tmp< Field< sphericalTensor > > transform (const UList< point > &global, const UList< sphericalTensor > &input) const
With rotation tensors at given global positions.
virtual tmp< Field< sphericalTensor > > transform (const pointUIndList &global, const UList< sphericalTensor > &input) const
With rotation tensors at given global positions.
virtual symmTensor transform (const symmTensor &input) const
With constant rotation tensor.
virtual tmp< Field< symmTensor > > transform (const UList< symmTensor > &input) const
With constant rotation tensor.
virtual symmTensor transform (const point &global, const symmTensor &input) const
With rotation tensor at given global position.
virtual tmp< Field< symmTensor > > transform (const UList< point > &global, const symmTensor &input) const
With rotation tensors at given global positions.
virtual tmp< Field< symmTensor > > transform (const pointUIndList &global, const symmTensor &input) const
With rotation tensors at given global positions.
virtual tmp< Field< symmTensor > > transform (const UList< point > &global, const UList< symmTensor > &input) const
With rotation tensors at given global positions.
virtual tmp< Field< symmTensor > > transform (const pointUIndList &global, const UList< symmTensor > &input) const
With rotation tensors at given global positions.
virtual tensor transform (const tensor &input) const
With constant rotation tensor.
virtual tmp< Field< tensor > > transform (const UList< tensor > &input) const
With constant rotation tensor.
virtual tensor transform (const point &global, const tensor &input) const
With rotation tensor at given global position.
virtual tmp< Field< tensor > > transform (const UList< point > &global, const tensor &input) const
With rotation tensors at given global positions.
virtual tmp< Field< tensor > > transform (const pointUIndList &global, const tensor &input) const
With rotation tensors at given global positions.
virtual tmp< Field< tensor > > transform (const UList< point > &global, const UList< tensor > &input) const
With rotation tensors at given global positions.
virtual tmp< Field< tensor > > transform (const pointUIndList &global, const UList< tensor > &input) const
With rotation tensors at given global positions.
virtual scalar invTransform (const scalar &input) const
With constant rotation tensor.
virtual tmp< Field< scalar > > invTransform (const UList< scalar > &input) const
With constant rotation tensor.
virtual scalar invTransform (const point &global, const scalar &input) const
With rotation tensor at given global position.
virtual tmp< Field< scalar > > invTransform (const UList< point > &global, const scalar &input) const
With rotation tensors at given global positions.
virtual tmp< Field< scalar > > invTransform (const pointUIndList &global, const scalar &input) const
With rotation tensors at given global positions.
virtual tmp< Field< scalar > > invTransform (const UList< point > &global, const UList< scalar > &input) const
With rotation tensors at given global positions.
virtual tmp< Field< scalar > > invTransform (const pointUIndList &global, const UList< scalar > &input) const
With rotation tensors at given global positions.
virtual vector invTransform (const vector &input) const
With constant rotation tensor.
virtual tmp< Field< vector > > invTransform (const UList< vector > &input) const
With constant rotation tensor.
virtual vector invTransform (const point &global, const vector &input) const
With rotation tensor at given global position.
virtual tmp< Field< vector > > invTransform (const UList< point > &global, const vector &input) const
With rotation tensors at given global positions.
virtual tmp< Field< vector > > invTransform (const pointUIndList &global, const vector &input) const
With rotation tensors at given global positions.
virtual tmp< Field< vector > > invTransform (const UList< point > &global, const UList< vector > &input) const
With rotation tensors at given global positions.
virtual tmp< Field< vector > > invTransform (const pointUIndList &global, const UList< vector > &input) const
With rotation tensors at given global positions.
virtual sphericalTensor invTransform (const sphericalTensor &input) const
With constant rotation tensor.
virtual tmp< Field< sphericalTensor > > invTransform (const UList< sphericalTensor > &input) const
With constant rotation tensor.
virtual sphericalTensor invTransform (const point &global, const sphericalTensor &input) const
With rotation tensor at given global position.
virtual tmp< Field< sphericalTensor > > invTransform (const UList< point > &global, const sphericalTensor &input) const
With rotation tensors at given global positions.
virtual tmp< Field< sphericalTensor > > invTransform (const pointUIndList &global, const sphericalTensor &input) const
With rotation tensors at given global positions.
virtual tmp< Field< sphericalTensor > > invTransform (const UList< point > &global, const UList< sphericalTensor > &input) const
With rotation tensors at given global positions.
virtual tmp< Field< sphericalTensor > > invTransform (const pointUIndList &global, const UList< sphericalTensor > &input) const
With rotation tensors at given global positions.
virtual symmTensor invTransform (const symmTensor &input) const
With constant rotation tensor.
virtual tmp< Field< symmTensor > > invTransform (const UList< symmTensor > &input) const
With constant rotation tensor.
virtual symmTensor invTransform (const point &global, const symmTensor &input) const
With rotation tensor at given global position.
virtual tmp< Field< symmTensor > > invTransform (const UList< point > &global, const symmTensor &input) const
With rotation tensors at given global positions.
virtual tmp< Field< symmTensor > > invTransform (const pointUIndList &global, const symmTensor &input) const
With rotation tensors at given global positions.
virtual tmp< Field< symmTensor > > invTransform (const UList< point > &global, const UList< symmTensor > &input) const
With rotation tensors at given global positions.
virtual tmp< Field< symmTensor > > invTransform (const pointUIndList &global, const UList< symmTensor > &input) const
With rotation tensors at given global positions.
virtual tensor invTransform (const tensor &input) const
With constant rotation tensor.
virtual tmp< Field< tensor > > invTransform (const UList< tensor > &input) const
With constant rotation tensor.
virtual tensor invTransform (const point &global, const tensor &input) const
With rotation tensor at given global position.
virtual tmp< Field< tensor > > invTransform (const UList< point > &global, const tensor &input) const
With rotation tensors at given global positions.
virtual tmp< Field< tensor > > invTransform (const pointUIndList &global, const tensor &input) const
With rotation tensors at given global positions.
virtual tmp< Field< tensor > > invTransform (const UList< point > &global, const UList< tensor > &input) const
With rotation tensors at given global positions.
virtual tmp< Field< tensor > > invTransform (const pointUIndList &global, const UList< tensor > &input) const
With rotation tensors at given global positions.
template<class PointField >
Foam::tmp< Foam::tensorField > rotationsImpl (const PointField &global) const
template<class PointField >
Foam::tmp< Foam::pointField > transformPointImpl (const PointField &localCart) const
template<class PointField >
Foam::tmp< Foam::pointField > invTransformPointImpl (const PointField &global) const
template<class RetType , class Type , class BinaryOp >
Foam::tmp< Foam::Field< RetType > > manyTimesImpl (const tensor &tt, const UList< Type > &input, const BinaryOp &bop)
template<class RetType , class PointField , class Type , class BinaryOp >
Foam::tmp< Foam::Field< RetType > > oneToOneImpl (const PointField &global, const UList< Type > &input, const BinaryOp &bop) const
template<class RetType , class PointField , class Type , class BinaryOp >
Foam::tmp< Foam::Field< RetType > > oneToManyImpl (const PointField &global, const Type &input, const BinaryOp &bop) const
Static Public Member Functions
static autoPtr< coordinateSystem > New (const word &modelType, const objectRegistry &obr, const dictionary &dict, IOobjectOption::readOption readOrigin=IOobjectOption::MUST_READ)
static autoPtr< coordinateSystem > New (const word &modelType, const dictionary &dict, IOobjectOption::readOption readOrigin=IOobjectOption::MUST_READ)
static autoPtr< coordinateSystem > New (const objectRegistry &obr, const dictionary &dict, const word &dictName=word::null, IOobjectOption::readOption readOrigin=IOobjectOption::MUST_READ)
static autoPtr< coordinateSystem > New (const dictionary &dict, const word &dictName=word::null, IOobjectOption::readOption readOrigin=IOobjectOption::MUST_READ)
static autoPtr< coordinateSystem > New (Istream &is, IOobjectOption::readOption readOrigin=IOobjectOption::MUST_READ)
static autoPtr< coordinateSystem > NewIfPresent (const objectRegistry &obr, const dictionary &dict, const word &dictName=coordinateSystem::typeName)
static autoPtr< coordinateSystem > NewIfPresent (const dictionary &dict, const word &dictName=coordinateSystem::typeName)
Protected Member Functions
template<class PointField >
tmp< tensorField > rotationsImpl (const PointField &global) const
template<class PointField >
tmp< pointField > transformPointImpl (const PointField &localCart) const
template<class PointField >
tmp< pointField > invTransformPointImpl (const PointField &global) const
template<class RetType , class PointField , class Type , class BinaryOp >
tmp< Field< RetType > > oneToOneImpl (const PointField &global, const UList< Type > &input, const BinaryOp &bop) const
template<class RetType , class PointField , class Type , class BinaryOp >
tmp< Field< RetType > > oneToManyImpl (const PointField &global, const Type &input, const BinaryOp &bop) const
virtual vector localToGlobal (const vector &local, bool translate) const
virtual tmp< vectorField > localToGlobal (const vectorField &local, bool translate) const
virtual vector globalToLocal (const vector &global, bool translate) const
virtual tmp< vectorField > globalToLocal (const vectorField &global, bool translate) const
void assign (const dictionary &dict, IOobjectOption::readOption readOrigin=IOobjectOption::MUST_READ)
coordinateSystem (std::nullptr_t)
Static Protected Member Functions
template<class RetType , class Type , class BinaryOp >
static tmp< Field< RetType > > manyTimesImpl (const tensor &tt, const UList< Type > &input, const BinaryOp &bop)
Protected Attributes
autoPtr< coordinateRotation > spec_
point origin_
tensor rot_
word name_
string note_
Static Protected Attributes
static coordinateSystem dummy_
Detailed Description
Base class for coordinate system specification, the default coordinate system type is cartesian .
All systems are defined by an origin point and a coordinate rotation By default, the axes specification can be used directly as part of the coordinate system specification. For example,
coordinateSystem
{
    origin  (0 0 0);
    e1      (0 1 0);
    e3      (1 0 0);
}
However, a more verbose format with rotation provided as a dictionary entry is possible:
coordinateSystem
{
    type    cartesian;
    origin  (0 0 0);
    rotation
    {
        type    axes;
        e1      (0 1 0);
        e3      (1 0 0);
    }
}
It also also possible to use the compact (single-dictionary) form and specific a different type of rotation:
coordinateSystem
{
    type        cartesian;
    origin      (0 0 0);
    rotation    euler;
    angles      (90 0 0);
}
This last form can be particularly readable for an identity rotation: coordinateSystem { type cartesian; origin (0 0 0); rotation none; }
Types of coordinateRotation:
none
axes
axisAngle
euler
starcd
Type of coordinateSystem:
cartesian
cylindrical
indirect (references an entry in coordinateSystems).
Source files
coordinateSystem.H
coordinateSystem.C
coordinateSystemNew.C
coordinateSystemTemplates.C
coordinateSystemTransform.C
Definition at line 142 of file coordinateSystem.H.
Constructor & Destructor Documentation
coordinateSystem() [1/14]
coordinateSystem (std::nullptr_t) protected
Definition at line 125 of file coordinateSystem.C.
coordinateSystem() [2/14]
coordinateSystem ()
Definition at line 135 of file coordinateSystem.C.
coordinateSystem() [3/14]
coordinateSystem (const coordinateRotation & crot) explicit
Definition at line 145 of file coordinateSystem.C.
coordinateSystem() [4/14]
coordinateSystem (coordinateRotation && crot) explicit
Definition at line 151 of file coordinateSystem.C.
coordinateSystem() [5/14]
coordinateSystem (const coordinateSystem & csys)
Definition at line 157 of file coordinateSystem.C.
coordinateSystem() [6/14]
coordinateSystem (coordinateSystem && csys)
Definition at line 167 of file coordinateSystem.C.
coordinateSystem() [7/14]
coordinateSystem (autoPtr< coordinateSystem > && csys) explicit
Definition at line 177 of file coordinateSystem.C.
References coordinateSystem::operator=(), and coordinateSystem::spec_.
coordinateSystem() [8/14]
coordinateSystem (const word & name, const coordinateSystem & csys)
Definition at line 195 of file coordinateSystem.C.
coordinateSystem() [9/14]
coordinateSystem (const point & origin, const coordinateRotation & crot)
Definition at line 209 of file coordinateSystem.C.
coordinateSystem() [10/14]
coordinateSystem (const point & origin, const vector & axis, const vector & dirn)
Definition at line 234 of file coordinateSystem.C.
coordinateSystem() [11/14]
coordinateSystem (const word & name, const point & origin, const coordinateRotation & crot)
Definition at line 219 of file coordinateSystem.C.
coordinateSystem() [12/14]
coordinateSystem (const word & name, const point & origin, const vector & axis, const vector & dirn)
Definition at line 245 of file coordinateSystem.C.
coordinateSystem() [13/14]
coordinateSystem (const dictionary & dict, IOobjectOption::readOption readOrigin = IOobjectOption::MUST_READ) explicit
Definition at line 261 of file coordinateSystem.C.
References coordinateSystem::assign(), and dict.
coordinateSystem() [14/14]
coordinateSystem (const dictionary & dict, const word & dictName, IOobjectOption::readOption readOrigin = IOobjectOption::MUST_READ)
Definition at line 273 of file coordinateSystem.C.
References coordinateSystem::assign(), dict, dictName(), and IOobjectOption::lazierRead().
~coordinateSystem()
virtual ~coordinateSystem () virtual default
Member Function Documentation
rotationsImpl() [1/2]
template<class PointField > tmp< tensorField > rotationsImpl (const PointField & global) const protected
transformPointImpl() [1/2]
template<class PointField > tmp< pointField > transformPointImpl (const PointField & localCart) const protected
Referenced by coordinateSystem::transformPoint().
invTransformPointImpl() [1/2]
template<class PointField > tmp< pointField > invTransformPointImpl (const PointField & global) const protected
manyTimesImpl() [1/2]
template<class RetType , class Type , class BinaryOp > static tmp< Field< RetType > > manyTimesImpl (const tensor & tt, const UList< Type > & input, const BinaryOp & bop) static protected
oneToOneImpl() [1/2]
template<class RetType , class PointField , class Type , class BinaryOp > tmp< Field< RetType > > oneToOneImpl (const PointField & global, const UList< Type > & input, const BinaryOp & bop) const protected
oneToManyImpl() [1/2]
template<class RetType , class PointField , class Type , class BinaryOp > tmp< Field< RetType > > oneToManyImpl (const PointField & global, const Type & input, const BinaryOp & bop) const protected
localToGlobal() [1/2]
Foam::vector localToGlobal (const vector & local, bool translate) const protected virtual
Reimplemented in cylindrical, and indirect.
Definition at line 349 of file coordinateSystem.C.
References Foam::transform().
Referenced by coordinateSystem::globalPosition(), coordinateSystem::globalPosition(), coordinateSystem::globalVector(), coordinateSystem::globalVector(), cylindrical::localToGlobal(), indirect::localToGlobal(), cylindrical::localToGlobal(), and indirect::localToGlobal().
localToGlobal() [2/2]
Foam::tmp< Foam::vectorField > localToGlobal (const vectorField & local, bool translate) const protected virtual
Reimplemented in cylindrical, and indirect.
Definition at line 364 of file coordinateSystem.C.
References Foam::transform().
globalToLocal() [1/2]
Foam::vector globalToLocal (const vector & global, bool translate) const protected virtual
Reimplemented in cylindrical, and indirect.
Definition at line 379 of file coordinateSystem.C.
References Foam::invTransform().
Referenced by cylindrical::globalToLocal(), indirect::globalToLocal(), cylindrical::globalToLocal(), indirect::globalToLocal(), coordinateSystem::localPosition(), coordinateSystem::localPosition(), coordinateSystem::localVector(), and coordinateSystem::localVector().
globalToLocal() [2/2]
Foam::tmp< Foam::vectorField > globalToLocal (const vectorField & global, bool translate) const protected virtual
Reimplemented in cylindrical, and indirect.
Definition at line 394 of file coordinateSystem.C.
References Foam::invTransform().
assign()
void assign (const dictionary & dict, IOobjectOption::readOption readOrigin = IOobjectOption::MUST_READ) protected
Definition at line 68 of file coordinateSystem.C.
References dict, UPtrList< T >::get(), IOobjectOption::isReadRequired(), IOobjectOption::lazierRead(), keyType::LITERAL, coordinateRotation::New(), coordinateSystem::note_, coordinateSystem::origin_, coordinateSystem::rot_, coordinateSystem::spec_, and Foam::Zero.
Referenced by coordinateSystem::coordinateSystem(), and coordinateSystem::coordinateSystem().
TypeName()
TypeName ("coordinateSystem")
clone()
virtual autoPtr< coordinateSystem > clone () const inline virtual
Reimplemented in cartesian, cylindrical, and indirect.
Definition at line 418 of file coordinateSystem.H.
References autoPtr< T >::New().
declareRunTimeSelectionTable() [1/2]
declareRunTimeSelectionTable (autoPtr , coordinateSystem , dictionary , (const dictionary &dict, IOobjectOption::readOption readOrigin) , (dict, readOrigin))
declareRunTimeSelectionTable() [2/2]
declareRunTimeSelectionTable (autoPtr , coordinateSystem , registry , (const objectRegistry &obr, const dictionary &dict, IOobjectOption::readOption readOrigin) , (obr, dict, readOrigin))
References Foam::New().
New() [1/5]
Foam::autoPtr< Foam::coordinateSystem > New (const word & modelType, const objectRegistry & obr, const dictionary & dict, IOobjectOption::readOption readOrigin = IOobjectOption::MUST_READ) static
Definition at line 233 of file coordinateSystemNew.C.
References dict, and Foam::New().
New() [2/5]
Foam::autoPtr< Foam::coordinateSystem > New (const word & modelType, const dictionary & dict, IOobjectOption::readOption readOrigin = IOobjectOption::MUST_READ) static
Definition at line 246 of file coordinateSystemNew.C.
References dict, and Foam::New().
New() [3/5]
Foam::autoPtr< Foam::coordinateSystem > New (const objectRegistry & obr, const dictionary & dict, const word & dictName = word::null, IOobjectOption::readOption readOrigin = IOobjectOption::MUST_READ) static
Definition at line 258 of file coordinateSystemNew.C.
References dict, dictName(), and Foam::New().
New() [4/5]
Foam::autoPtr< Foam::coordinateSystem > New (const dictionary & dict, const word & dictName = word::null, IOobjectOption::readOption readOrigin = IOobjectOption::MUST_READ) static
Definition at line 271 of file coordinateSystemNew.C.
References dict, dictName(), and Foam::New().
New() [5/5]
Foam::autoPtr< Foam::coordinateSystem > New (Istream & is, IOobjectOption::readOption readOrigin = IOobjectOption::MUST_READ) static
Definition at line 212 of file coordinateSystemNew.C.
References dict, keyType::LITERAL, and dictionary::readIfPresent().
NewIfPresent() [1/2]
Foam::autoPtr< Foam::coordinateSystem > NewIfPresent (const objectRegistry & obr, const dictionary & dict, const word & dictName = coordinateSystem::typeName) static
Definition at line 283 of file coordinateSystemNew.C.
References dict, and dictName().
NewIfPresent() [2/2]
Foam::autoPtr< Foam::coordinateSystem > NewIfPresent (const dictionary & dict, const word & dictName = coordinateSystem::typeName) static
Definition at line 295 of file coordinateSystemNew.C.
References dict, and dictName().
valid()
virtual bool valid () const inline virtual
Reimplemented in indirect.
Definition at line 558 of file coordinateSystem.H.
References coordinateSystem::spec_.
Referenced by indirect::valid().
uniform()
virtual bool uniform () const inline virtual
Reimplemented in cylindrical, and indirect.
Definition at line 564 of file coordinateSystem.H.
Referenced by indirect::uniform().
origin() [1/2]
virtual const point & origin () const inline virtual
Reimplemented in indirect.
Definition at line 573 of file coordinateSystem.H.
References coordinateSystem::origin_.
Referenced by arcEdge::arcEdge(), mixerFvMesh::mixerFvMesh(), Foam::operator!=(), indirect::origin(), and propellerInfo::setSampleDiskGeometry().
rotation() [1/2]
virtual const coordinateRotation & rotation () const inline virtual
Reimplemented in indirect.
Definition at line 579 of file coordinateSystem.H.
References coordinateSystem::spec_.
Referenced by arcEdge::arcEdge(), and indirect::rotation().
name()
virtual const word & name () const inline virtual
Reimplemented in indirect.
Definition at line 585 of file coordinateSystem.H.
References coordinateSystem::name_.
note() [1/2]
virtual const string & note () const inline virtual
Reimplemented in indirect.
Definition at line 591 of file coordinateSystem.H.
References coordinateSystem::note_.
Referenced by indirect::note().
R() [1/4]
virtual const tensor & R () const inline virtual
Reimplemented in cylindrical, and indirect.
Definition at line 597 of file coordinateSystem.H.
References coordinateSystem::rot_.
Referenced by Foam::operator!=(), indirect::R(), indirect::R(), indirect::R(), indirect::R(), and coordinateSystem::rotationsImpl().
e1()
virtual const vector e1 () const inline virtual
Reimplemented in indirect.
Definition at line 603 of file coordinateSystem.H.
References Tensor< Cmpt >::cx(), and coordinateSystem::rot_.
Referenced by indirect::e1().
e2()
virtual const vector e2 () const inline virtual
Reimplemented in indirect.
Definition at line 609 of file coordinateSystem.H.
References Tensor< Cmpt >::cy(), and coordinateSystem::rot_.
Referenced by indirect::e2().
e3()
virtual const vector e3 () const inline virtual
Reimplemented in indirect.
Definition at line 615 of file coordinateSystem.H.
References Tensor< Cmpt >::cz(), and coordinateSystem::rot_.
Referenced by rotorDiskSource::checkData(), indirect::e3(), and mixerFvMesh::mixerFvMesh().
rename()
virtual void rename (const word & newName) inline virtual
Reimplemented in indirect.
Definition at line 624 of file coordinateSystem.H.
References coordinateSystem::name_.
note() [2/2]
virtual string & note () inline virtual
Reimplemented in indirect.
Definition at line 630 of file coordinateSystem.H.
References coordinateSystem::note_.
origin() [2/2]
virtual point & origin () inline virtual
Reimplemented in indirect.
Definition at line 636 of file coordinateSystem.H.
References coordinateSystem::origin_.
clear()
void clear () virtual
Reimplemented in indirect.
Definition at line 298 of file coordinateSystem.C.
References PtrList< T >::clear(), SphericalTensor< scalar >::I, and Foam::Zero.
Referenced by surfaceWriter::surfaceWriter().
rotation() [2/2]
void rotation (autoPtr< coordinateRotation > && crot) virtual
Reimplemented in indirect.
Definition at line 409 of file coordinateSystem.C.
References SphericalTensor< scalar >::I.
write()
void write (Ostream & os) const virtual
Reimplemented in indirect.
Definition at line 423 of file coordinateSystem.C.
References os(), Foam::type(), and OBJstream::write().
Referenced by Foam::operator<<().
writeEntry() [1/2]
void writeEntry (Ostream & os) const virtual
Reimplemented in indirect.
Definition at line 441 of file coordinateSystem.C.
References os().
writeEntry() [2/2]
void writeEntry (const word & keyword, Ostream & os) const virtual
Reimplemented in indirect.
Definition at line 447 of file coordinateSystem.C.
References Ostream::beginBlock(), Ostream::endBlock(), os(), Foam::type(), and Ostream::writeEntry().
operator=() [1/4]
void operator= (const coordinateSystem & csys)
Definition at line 486 of file coordinateSystem.C.
References PtrList< T >::clone(), SphericalTensor< scalar >::I, coordinateSystem::name_, coordinateSystem::note_, coordinateSystem::origin_, and coordinateSystem::spec_.
Referenced by coordinateSystem::coordinateSystem(), coordinateSystem::operator=(), and coordinateSystem::operator=().
operator=() [2/4]
void operator= (coordinateSystem && csys)
Definition at line 505 of file coordinateSystem.C.
operator=() [3/4]
void operator= (const autoPtr< coordinateSystem > & csys)
Definition at line 515 of file coordinateSystem.C.
References coordinateSystem::operator=().
operator=() [4/4]
void operator= (autoPtr< coordinateSystem > && csys)
Definition at line 521 of file coordinateSystem.C.
References coordinateSystem::operator=().
R() [2/4]
Foam::tensor R (const point & global) const virtual
Reimplemented in cylindrical, cylindrical, and indirect.
Definition at line 307 of file coordinateSystem.C.
R() [3/4]
Foam::tmp< Foam::tensorField > R (const UList< point > & global) const virtual
Reimplemented in cylindrical, and indirect.
Definition at line 313 of file coordinateSystem.C.
R() [4/4]
Foam::tmp< Foam::tensorField > R (const pointUIndList & global) const virtual
Reimplemented in cylindrical, and indirect.
Definition at line 322 of file coordinateSystem.C.
transformPoint() [1/3]
Foam::point transformPoint (const point & localCart) const
Definition at line 331 of file coordinateSystem.C.
References Foam::transform().
transformPoint() [2/3]
Foam::tmp< Foam::pointField > transformPoint (const UList< point > & localCart) const
Definition at line 93 of file coordinateSystemTransform.C.
References coordinateSystem::transformPointImpl().
transformPoint() [3/3]
Foam::tmp< Foam::pointField > transformPoint (const pointUIndList & localCart) const
Definition at line 102 of file coordinateSystemTransform.C.
invTransformPoint() [1/3]
Foam::point invTransformPoint (const point & global) const
Definition at line 340 of file coordinateSystem.C.
References Foam::invTransform().
invTransformPoint() [2/3]
Foam::tmp< Foam::pointField > invTransformPoint (const UList< point > & global) const
Definition at line 111 of file coordinateSystemTransform.C.
invTransformPoint() [3/3]
Foam::tmp< Foam::pointField > invTransformPoint (const pointUIndList & global) const
Definition at line 120 of file coordinateSystemTransform.C.
globalPosition() [1/2]
point globalPosition (const point & local) const inline
Definition at line 720 of file coordinateSystem.H.
References local, and coordinateSystem::localToGlobal().
Referenced by searchableRotatedBox::searchableRotatedBox(), and propellerInfo::setSampleDiskGeometry().
globalPosition() [2/2]
tmp< pointField > globalPosition (const pointField & local) const inline
Definition at line 726 of file coordinateSystem.H.
References local, and coordinateSystem::localToGlobal().
localPosition() [1/2]
point localPosition (const point & global) const inline
Definition at line 732 of file coordinateSystem.H.
References coordinateSystem::globalToLocal().
localPosition() [2/2]
tmp< pointField > localPosition (const pointField & global) const inline
Definition at line 738 of file coordinateSystem.H.
References coordinateSystem::globalToLocal().
globalVector() [1/2]
vector globalVector (const vector & local) const inline
Definition at line 746 of file coordinateSystem.H.
References local, and coordinateSystem::localToGlobal().
globalVector() [2/2]
tmp< vectorField > globalVector (const vectorField & local) const inline
Definition at line 752 of file coordinateSystem.H.
References local, and coordinateSystem::localToGlobal().
localVector() [1/2]
vector localVector (const vector & global) const inline
Definition at line 758 of file coordinateSystem.H.
References coordinateSystem::globalToLocal().
localVector() [2/2]
tmp< vectorField > localVector (const vectorField & global) const inline
Definition at line 764 of file coordinateSystem.H.
References coordinateSystem::globalToLocal().
transformPrincipal() [1/7]
Foam::symmTensor transformPrincipal (const vector & input) const virtual
With constant rotation tensor.
Definition at line 195 of file coordinateSystemTransform.C.
transformPrincipal() [2/7]
Foam::tmp< Foam::Field< Foam::symmTensor > > transformPrincipal (const UList< vector > & input) const virtual
With constant rotation tensor.
Definition at line 195 of file coordinateSystemTransform.C.
transformPrincipal() [3/7]
Foam::symmTensor transformPrincipal (const point & global, const vector & input) const virtual
With rotation tensor at given global position.
Definition at line 195 of file coordinateSystemTransform.C.
transformPrincipal() [4/7]
Foam::tmp< Foam::Field< Foam::symmTensor > > transformPrincipal (const UList< point > & global, const vector & input) const virtual
With rotation tensors at given global positions.
Definition at line 195 of file coordinateSystemTransform.C.
transformPrincipal() [5/7]
Foam::tmp< Foam::Field< Foam::symmTensor > > transformPrincipal (const pointUIndList & global, const vector & input) const virtual
With rotation tensors at given global positions.
Definition at line 195 of file coordinateSystemTransform.C.
transformPrincipal() [6/7]
Foam::tmp< Foam::Field< Foam::symmTensor > > transformPrincipal (const UList< point > & global, const UList< vector > & input) const virtual
With rotation tensors at given global positions.
Definition at line 195 of file coordinateSystemTransform.C.
transformPrincipal() [7/7]
Foam::tmp< Foam::Field< Foam::symmTensor > > transformPrincipal (const pointUIndList & global, const UList< vector > & input) const virtual
With rotation tensors at given global positions.
Definition at line 195 of file coordinateSystemTransform.C.
transform() [1/35]
Foam::scalar transform (const scalar & input) const virtual
With constant rotation tensor.
Definition at line 197 of file coordinateSystemTransform.C.
transform() [2/35]
Foam::tmp< Foam::Field< Foam::scalar > > transform (const UList< scalar > & input) const virtual
With constant rotation tensor.
Definition at line 197 of file coordinateSystemTransform.C.
transform() [3/35]
Foam::scalar transform (const point & global, const scalar & input) const virtual
With rotation tensor at given global position.
Definition at line 197 of file coordinateSystemTransform.C.
transform() [4/35]
Foam::tmp< Foam::Field< Foam::scalar > > transform (const UList< point > & global, const scalar & input) const virtual
With rotation tensors at given global positions.
Definition at line 197 of file coordinateSystemTransform.C.
transform() [5/35]
Foam::tmp< Foam::Field< Foam::scalar > > transform (const pointUIndList & global, const scalar & input) const virtual
With rotation tensors at given global positions.
Definition at line 197 of file coordinateSystemTransform.C.
transform() [6/35]
Foam::tmp< Foam::Field< Foam::scalar > > transform (const UList< point > & global, const UList< scalar > & input) const virtual
With rotation tensors at given global positions.
Definition at line 197 of file coordinateSystemTransform.C.
transform() [7/35]
Foam::tmp< Foam::Field< Foam::scalar > > transform (const pointUIndList & global, const UList< scalar > & input) const virtual
With rotation tensors at given global positions.
Definition at line 197 of file coordinateSystemTransform.C.
transform() [8/35]
Foam::vector transform (const vector & input) const virtual
With constant rotation tensor.
Definition at line 198 of file coordinateSystemTransform.C.
transform() [9/35]
Foam::tmp< Foam::Field< Foam::vector > > transform (const UList< vector > & input) const virtual
With constant rotation tensor.
Definition at line 198 of file coordinateSystemTransform.C.
transform() [10/35]
Foam::vector transform (const point & global, const vector & input) const virtual
With rotation tensor at given global position.
Definition at line 198 of file coordinateSystemTransform.C.
transform() [11/35]
Foam::tmp< Foam::Field< Foam::vector > > transform (const UList< point > & global, const vector & input) const virtual
With rotation tensors at given global positions.
Definition at line 198 of file coordinateSystemTransform.C.
transform() [12/35]
Foam::tmp< Foam::Field< Foam::vector > > transform (const pointUIndList & global, const vector & input) const virtual
With rotation tensors at given global positions.
Definition at line 198 of file coordinateSystemTransform.C.
transform() [13/35]
Foam::tmp< Foam::Field< Foam::vector > > transform (const UList< point > & global, const UList< vector > & input) const virtual
With rotation tensors at given global positions.
Definition at line 198 of file coordinateSystemTransform.C.
transform() [14/35]
Foam::tmp< Foam::Field< Foam::vector > > transform (const pointUIndList & global, const UList< vector > & input) const virtual
With rotation tensors at given global positions.
Definition at line 198 of file coordinateSystemTransform.C.
transform() [15/35]
Foam::sphericalTensor transform (const sphericalTensor & input) const virtual
With constant rotation tensor.
Definition at line 199 of file coordinateSystemTransform.C.
transform() [16/35]
Foam::tmp< Foam::Field< Foam::sphericalTensor > > transform (const UList< sphericalTensor > & input) const virtual
With constant rotation tensor.
Definition at line 199 of file coordinateSystemTransform.C.
transform() [17/35]
Foam::sphericalTensor transform (const point & global, const sphericalTensor & input) const virtual
With rotation tensor at given global position.
Definition at line 199 of file coordinateSystemTransform.C.
transform() [18/35]
Foam::tmp< Foam::Field< Foam::sphericalTensor > > transform (const UList< point > & global, const sphericalTensor & input) const virtual
With rotation tensors at given global positions.
Definition at line 199 of file coordinateSystemTransform.C.
transform() [19/35]
Foam::tmp< Foam::Field< Foam::sphericalTensor > > transform (const pointUIndList & global, const sphericalTensor & input) const virtual
With rotation tensors at given global positions.
Definition at line 199 of file coordinateSystemTransform.C.
transform() [20/35]
Foam::tmp< Foam::Field< Foam::sphericalTensor > > transform (const UList< point > & global, const UList< sphericalTensor > & input) const virtual
With rotation tensors at given global positions.
Definition at line 199 of file coordinateSystemTransform.C.
transform() [21/35]
Foam::tmp< Foam::Field< Foam::sphericalTensor > > transform (const pointUIndList & global, const UList< sphericalTensor > & input) const virtual
With rotation tensors at given global positions.
Definition at line 199 of file coordinateSystemTransform.C.
transform() [22/35]
Foam::symmTensor transform (const symmTensor & input) const virtual
With constant rotation tensor.
Definition at line 200 of file coordinateSystemTransform.C.
transform() [23/35]
Foam::tmp< Foam::Field< Foam::symmTensor > > transform (const UList< symmTensor > & input) const virtual
With constant rotation tensor.
Definition at line 200 of file coordinateSystemTransform.C.
transform() [24/35]
Foam::symmTensor transform (const point & global, const symmTensor & input) const virtual
With rotation tensor at given global position.
Definition at line 200 of file coordinateSystemTransform.C.
transform() [25/35]
Foam::tmp< Foam::Field< Foam::symmTensor > > transform (const UList< point > & global, const symmTensor & input) const virtual
With rotation tensors at given global positions.
Definition at line 200 of file coordinateSystemTransform.C.
transform() [26/35]
Foam::tmp< Foam::Field< Foam::symmTensor > > transform (const pointUIndList & global, const symmTensor & input) const virtual
With rotation tensors at given global positions.
Definition at line 200 of file coordinateSystemTransform.C.
transform() [27/35]
Foam::tmp< Foam::Field< Foam::symmTensor > > transform (const UList< point > & global, const UList< symmTensor > & input) const virtual
With rotation tensors at given global positions.
Definition at line 200 of file coordinateSystemTransform.C.
transform() [28/35]
Foam::tmp< Foam::Field< Foam::symmTensor > > transform (const pointUIndList & global, const UList< symmTensor > & input) const virtual
With rotation tensors at given global positions.
Definition at line 200 of file coordinateSystemTransform.C.
transform() [29/35]
Foam::tensor transform (const tensor & input) const virtual
With constant rotation tensor.
Definition at line 201 of file coordinateSystemTransform.C.
transform() [30/35]
Foam::tmp< Foam::Field< Foam::tensor > > transform (const UList< tensor > & input) const virtual
With constant rotation tensor.
Definition at line 201 of file coordinateSystemTransform.C.
transform() [31/35]
Foam::tensor transform (const point & global, const tensor & input) const virtual
With rotation tensor at given global position.
Definition at line 201 of file coordinateSystemTransform.C.
transform() [32/35]
Foam::tmp< Foam::Field< Foam::tensor > > transform (const UList< point > & global, const tensor & input) const virtual
With rotation tensors at given global positions.
Definition at line 201 of file coordinateSystemTransform.C.
transform() [33/35]
Foam::tmp< Foam::Field< Foam::tensor > > transform (const pointUIndList & global, const tensor & input) const virtual
With rotation tensors at given global positions.
Definition at line 201 of file coordinateSystemTransform.C.
transform() [34/35]
Foam::tmp< Foam::Field< Foam::tensor > > transform (const UList< point > & global, const UList< tensor > & input) const virtual
With rotation tensors at given global positions.
Definition at line 201 of file coordinateSystemTransform.C.
transform() [35/35]
Foam::tmp< Foam::Field< Foam::tensor > > transform (const pointUIndList & global, const UList< tensor > & input) const virtual
With rotation tensors at given global positions.
Definition at line 201 of file coordinateSystemTransform.C.
invTransform() [1/35]
Foam::scalar invTransform (const scalar & input) const virtual
With constant rotation tensor.
Definition at line 203 of file coordinateSystemTransform.C.
invTransform() [2/35]
Foam::tmp< Foam::Field< Foam::scalar > > invTransform (const UList< scalar > & input) const virtual
With constant rotation tensor.
Definition at line 203 of file coordinateSystemTransform.C.
invTransform() [3/35]
Foam::scalar invTransform (const point & global, const scalar & input) const virtual
With rotation tensor at given global position.
Definition at line 203 of file coordinateSystemTransform.C.
invTransform() [4/35]
Foam::tmp< Foam::Field< Foam::scalar > > invTransform (const UList< point > & global, const scalar & input) const virtual
With rotation tensors at given global positions.
Definition at line 203 of file coordinateSystemTransform.C.
invTransform() [5/35]
Foam::tmp< Foam::Field< Foam::scalar > > invTransform (const pointUIndList & global, const scalar & input) const virtual
With rotation tensors at given global positions.
Definition at line 203 of file coordinateSystemTransform.C.
invTransform() [6/35]
Foam::tmp< Foam::Field< Foam::scalar > > invTransform (const UList< point > & global, const UList< scalar > & input) const virtual
With rotation tensors at given global positions.
Definition at line 203 of file coordinateSystemTransform.C.
invTransform() [7/35]
Foam::tmp< Foam::Field< Foam::scalar > > invTransform (const pointUIndList & global, const UList< scalar > & input) const virtual
With rotation tensors at given global positions.
Definition at line 203 of file coordinateSystemTransform.C.
invTransform() [8/35]
Foam::vector invTransform (const vector & input) const virtual
With constant rotation tensor.
Definition at line 204 of file coordinateSystemTransform.C.
invTransform() [9/35]
Foam::tmp< Foam::Field< Foam::vector > > invTransform (const UList< vector > & input) const virtual
With constant rotation tensor.
Definition at line 204 of file coordinateSystemTransform.C.
invTransform() [10/35]
Foam::vector invTransform (const point & global, const vector & input) const virtual
With rotation tensor at given global position.
Definition at line 204 of file coordinateSystemTransform.C.
invTransform() [11/35]
Foam::tmp< Foam::Field< Foam::vector > > invTransform (const UList< point > & global, const vector & input) const virtual
With rotation tensors at given global positions.
Definition at line 204 of file coordinateSystemTransform.C.
invTransform() [12/35]
Foam::tmp< Foam::Field< Foam::vector > > invTransform (const pointUIndList & global, const vector & input) const virtual
With rotation tensors at given global positions.
Definition at line 204 of file coordinateSystemTransform.C.
invTransform() [13/35]
Foam::tmp< Foam::Field< Foam::vector > > invTransform (const UList< point > & global, const UList< vector > & input) const virtual
With rotation tensors at given global positions.
Definition at line 204 of file coordinateSystemTransform.C.
invTransform() [14/35]
Foam::tmp< Foam::Field< Foam::vector > > invTransform (const pointUIndList & global, const UList< vector > & input) const virtual
With rotation tensors at given global positions.
Definition at line 204 of file coordinateSystemTransform.C.
invTransform() [15/35]
Foam::sphericalTensor invTransform (const sphericalTensor & input) const virtual
With constant rotation tensor.
Definition at line 205 of file coordinateSystemTransform.C.
invTransform() [16/35]
Foam::tmp< Foam::Field< Foam::sphericalTensor > > invTransform (const UList< sphericalTensor > & input) const virtual
With constant rotation tensor.
Definition at line 205 of file coordinateSystemTransform.C.
invTransform() [17/35]
Foam::sphericalTensor invTransform (const point & global, const sphericalTensor & input) const virtual
With rotation tensor at given global position.
Definition at line 205 of file coordinateSystemTransform.C.
invTransform() [18/35]
Foam::tmp< Foam::Field< Foam::sphericalTensor > > invTransform (const UList< point > & global, const sphericalTensor & input) const virtual
With rotation tensors at given global positions.
Definition at line 205 of file coordinateSystemTransform.C.
invTransform() [19/35]
Foam::tmp< Foam::Field< Foam::sphericalTensor > > invTransform (const pointUIndList & global, const sphericalTensor & input) const virtual
With rotation tensors at given global positions.
Definition at line 205 of file coordinateSystemTransform.C.
invTransform() [20/35]
Foam::tmp< Foam::Field< Foam::sphericalTensor > > invTransform (const UList< point > & global, const UList< sphericalTensor > & input) const virtual
With rotation tensors at given global positions.
Definition at line 205 of file coordinateSystemTransform.C.
invTransform() [21/35]
Foam::tmp< Foam::Field< Foam::sphericalTensor > > invTransform (const pointUIndList & global, const UList< sphericalTensor > & input) const virtual
With rotation tensors at given global positions.
Definition at line 205 of file coordinateSystemTransform.C.
invTransform() [22/35]
Foam::symmTensor invTransform (const symmTensor & input) const virtual
With constant rotation tensor.
Definition at line 206 of file coordinateSystemTransform.C.
invTransform() [23/35]
Foam::tmp< Foam::Field< Foam::symmTensor > > invTransform (const UList< symmTensor > & input) const virtual
With constant rotation tensor.
Definition at line 206 of file coordinateSystemTransform.C.
invTransform() [24/35]
Foam::symmTensor invTransform (const point & global, const symmTensor & input) const virtual
With rotation tensor at given global position.
Definition at line 206 of file coordinateSystemTransform.C.
invTransform() [25/35]
Foam::tmp< Foam::Field< Foam::symmTensor > > invTransform (const UList< point > & global, const symmTensor & input) const virtual
With rotation tensors at given global positions.
Definition at line 206 of file coordinateSystemTransform.C.
invTransform() [26/35]
Foam::tmp< Foam::Field< Foam::symmTensor > > invTransform (const pointUIndList & global, const symmTensor & input) const virtual
With rotation tensors at given global positions.
Definition at line 206 of file coordinateSystemTransform.C.
invTransform() [27/35]
Foam::tmp< Foam::Field< Foam::symmTensor > > invTransform (const UList< point > & global, const UList< symmTensor > & input) const virtual
With rotation tensors at given global positions.
Definition at line 206 of file coordinateSystemTransform.C.
invTransform() [28/35]
Foam::tmp< Foam::Field< Foam::symmTensor > > invTransform (const pointUIndList & global, const UList< symmTensor > & input) const virtual
With rotation tensors at given global positions.
Definition at line 206 of file coordinateSystemTransform.C.
invTransform() [29/35]
Foam::tensor invTransform (const tensor & input) const virtual
With constant rotation tensor.
Definition at line 207 of file coordinateSystemTransform.C.
invTransform() [30/35]
Foam::tmp< Foam::Field< Foam::tensor > > invTransform (const UList< tensor > & input) const virtual
With constant rotation tensor.
Definition at line 207 of file coordinateSystemTransform.C.
invTransform() [31/35]
Foam::tensor invTransform (const point & global, const tensor & input) const virtual
With rotation tensor at given global position.
Definition at line 207 of file coordinateSystemTransform.C.
invTransform() [32/35]
Foam::tmp< Foam::Field< Foam::tensor > > invTransform (const UList< point > & global, const tensor & input) const virtual
With rotation tensors at given global positions.
Definition at line 207 of file coordinateSystemTransform.C.
invTransform() [33/35]
Foam::tmp< Foam::Field< Foam::tensor > > invTransform (const pointUIndList & global, const tensor & input) const virtual
With rotation tensors at given global positions.
Definition at line 207 of file coordinateSystemTransform.C.
invTransform() [34/35]
Foam::tmp< Foam::Field< Foam::tensor > > invTransform (const UList< point > & global, const UList< tensor > & input) const virtual
With rotation tensors at given global positions.
Definition at line 207 of file coordinateSystemTransform.C.
invTransform() [35/35]
Foam::tmp< Foam::Field< Foam::tensor > > invTransform (const pointUIndList & global, const UList< tensor > & input) const virtual
With rotation tensors at given global positions.
Definition at line 207 of file coordinateSystemTransform.C.
rotationsImpl() [2/2]
template<class PointField > Foam::tmp< Foam::tensorField > rotationsImpl (const PointField & global) const
Definition at line 28 of file coordinateSystemTemplates.C.
References tmp< T >::New(), coordinateSystem::R(), and UList< T >::size().
transformPointImpl() [2/2]
template<class PointField > Foam::tmp< Foam::pointField > transformPointImpl (const PointField & localCart) const
Definition at line 46 of file coordinateSystemTemplates.C.
References tmp< T >::New(), UPtrList< T >::size(), and Foam::transform().
invTransformPointImpl() [2/2]
template<class PointField > Foam::tmp< Foam::pointField > invTransformPointImpl (const PointField & global) const
Definition at line 64 of file coordinateSystemTemplates.C.
References Foam::invTransform(), tmp< T >::New(), and UList< T >::size().
manyTimesImpl() [2/2]
template<class RetType , class Type , class BinaryOp > Foam::tmp< Foam::Field< RetType > > manyTimesImpl (const tensor & tt, const UList< Type > & input, const BinaryOp & bop)
Definition at line 82 of file coordinateSystemTemplates.C.
References Foam::input(), Foam::New(), and UPtrList< T >::size().
oneToOneImpl() [2/2]
template<class RetType , class PointField , class Type , class BinaryOp > Foam::tmp< Foam::Field< RetType > > oneToOneImpl (const PointField & global, const UList< Type > & input, const BinaryOp & bop) const
Definition at line 105 of file coordinateSystemTemplates.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, Foam::input(), Foam::New(), R, UPtrList< T >::size(), and UList< T >::size().
oneToManyImpl() [2/2]
template<class RetType , class PointField , class Type , class BinaryOp > Foam::tmp< Foam::Field< RetType > > oneToManyImpl (const PointField & global, const Type & input, const BinaryOp & bop) const
Definition at line 135 of file coordinateSystemTemplates.C.
References Foam::input(), Foam::New(), R, and UList< T >::size().
Member Data Documentation
spec_
autoPtr<coordinateRotation> spec_ protected
Definition at line 207 of file coordinateSystem.H.
Referenced by coordinateSystem::assign(), coordinateSystem::coordinateSystem(), coordinateSystem::operator=(), coordinateSystem::rotation(), and coordinateSystem::valid().
origin_
point origin_ protected
Definition at line 210 of file coordinateSystem.H.
Referenced by coordinateSystem::assign(), coordinateSystem::operator=(), coordinateSystem::origin(), and coordinateSystem::origin().
rot_
tensor rot_ protected
Definition at line 213 of file coordinateSystem.H.
Referenced by coordinateSystem::assign(), coordinateSystem::e1(), coordinateSystem::e2(), coordinateSystem::e3(), and coordinateSystem::R().
name_
word name_ protected
Definition at line 216 of file coordinateSystem.H.
Referenced by coordinateSystem::name(), indirect::name(), coordinateSystem::operator=(), and coordinateSystem::rename().
note_
string note_ protected
Definition at line 219 of file coordinateSystem.H.
Referenced by coordinateSystem::assign(), coordinateSystem::note(), coordinateSystem::note(), and coordinateSystem::operator=().
dummy_
Foam::coordinateSystem dummy_ static protected
Definition at line 222 of file coordinateSystem.H.
Referenced by indirect::note(), and indirect::origin().
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/coordinate/systems/coordinateSystem.H
src/OpenFOAM/primitives/coordinate/systems/coordinateSystem.C
src/OpenFOAM/primitives/coordinate/systems/coordinateSystemNew.C
src/OpenFOAM/primitives/coordinate/systems/coordinateSystemTemplates.C
src/OpenFOAM/primitives/coordinate/systems/coordinateSystemTransform.C