OpenFOAM: extendedCellToFaceStencil Class Reference
extendedCellToFaceStencil Class Reference
Calculates/constains the extended cell-to-face stencil.
#include <extendedCellToFaceStencil.H>
Public Member Functions
ClassName ("extendedCellToFaceStencil")
extendedCellToFaceStencil (const polyMesh &)
template<class Type >
void collectData (const mapDistribute &map, const labelListList &stencil, const GeometricField< Type, fvPatchField, volMesh > &fld, List< List< Type > > &stencilFld)
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > weightedSum (const mapDistribute &map, const labelListList &stencil, const GeometricField< Type, fvPatchField, volMesh > &fld, const List< List< scalar > > &stencilWeights)
Static Public Member Functions
template<class T >
static void collectData (const mapDistribute &map, const labelListList &stencil, const GeometricField< T, fvPatchField, volMesh > &fld, List< List< T > > &stencilFld)
template<class Type >
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > weightedSum (const mapDistribute &map, const labelListList &stencil, const GeometricField< Type, fvPatchField, volMesh > &fld, const List< List< scalar > > &stencilWeights)
Static Protected Member Functions
static void writeStencilStats (Ostream &os, const labelListList &stencil, const mapDistribute &map)
Protected Attributes
const polyMesh & mesh_
Detailed Description
Calculates/constains the extended cell-to-face stencil.
The stencil is a list of indices into either cells or boundary faces in a compact way. (element 0 is owner, 1 is neighbour). The index numbering is
cells first
then all (non-empty patch) boundary faces
When used in evaluation is a two stage process:
collect the data (cell data and non-empty boundaries) into a single field
(parallel) distribute the field
sum the weights*field.
Source files
extendedCellToFaceStencil.H
extendedCellToFaceStencil.C
extendedCellToFaceStencilTemplates.C
Definition at line 63 of file extendedCellToFaceStencil.H.
Constructor & Destructor Documentation
extendedCellToFaceStencil()
extendedCellToFaceStencil (const polyMesh & mesh) explicit
Definition at line 94 of file extendedCellToFaceStencil.C.
References coupled(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, mesh, and patches.
Member Function Documentation
writeStencilStats()
void writeStencilStats (Ostream & os, const labelListList & stencil, const mapDistribute & map) static protected
Definition at line 35 of file extendedCellToFaceStencil.C.
References Foam::endl(), forAll, Foam::labelMax, Foam::labelMin, Foam::max(), Foam::min(), UPstream::myProcNo(), Foam::nl, os(), Foam::reduce(), Foam::returnReduce(), UPtrList< T >::size(), and mapDistributeBase::subMap().
Referenced by centredCECCellToFaceStencilObject::centredCECCellToFaceStencilObject(), centredCFCCellToFaceStencilObject::centredCFCCellToFaceStencilObject(), centredCPCCellToFaceStencilObject::centredCPCCellToFaceStencilObject(), centredFECCellToFaceStencilObject::centredFECCellToFaceStencilObject(), pureUpwindCFCCellToFaceStencilObject::pureUpwindCFCCellToFaceStencilObject(), upwindCECCellToFaceStencilObject::upwindCECCellToFaceStencilObject(), upwindCFCCellToFaceStencilObject::upwindCFCCellToFaceStencilObject(), upwindCPCCellToFaceStencilObject::upwindCPCCellToFaceStencilObject(), and upwindFECCellToFaceStencilObject::upwindFECCellToFaceStencilObject().
ClassName()
ClassName ("extendedCellToFaceStencil")
collectData() [1/2]
template<class T > static void collectData (const mapDistribute & map, const labelListList & stencil, const GeometricField< T, fvPatchField, volMesh > & fld, List< List< T > > & stencilFld) static
Referenced by extendedCentredCellToFaceStencil::collectData(), extendedCentredCellToCellStencil::collectData(), extendedUpwindCellToFaceStencil::extendedUpwindCellToFaceStencil(), extendedUpwindCellToFaceStencil::extendedUpwindCellToFaceStencil(), extendedCellToCellStencil::weightedSum(), and extendedUpwindCellToFaceStencil::weightedSum().
weightedSum() [1/2]
template<class Type > static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > weightedSum (const mapDistribute & map, const labelListList & stencil, const GeometricField< Type, fvPatchField, volMesh > & fld, const List< List< scalar > > & stencilWeights) static
Referenced by extendedCentredCellToFaceStencil::weightedSum().
collectData() [2/2]
template<class Type > void collectData (const mapDistribute & map, const labelListList & stencil, const GeometricField< Type, fvPatchField, volMesh > & fld, List< List< Type > > & stencilFld)
Definition at line 26 of file extendedCellToFaceStencilTemplates.C.
References mapDistributeBase::constructSize(), mapDistribute::distribute(), fld(), forAll, PtrList< T >::setSize(), UPtrList< T >::size(), UList< T >::size(), and Foam::Zero.
weightedSum() [2/2]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > weightedSum (const mapDistribute & map, const labelListList & stencil, const GeometricField< Type, fvPatchField, volMesh > & fld, const List< List< scalar > > & stencilWeights)
Definition at line 80 of file extendedCellToFaceStencilTemplates.C.
References fld(), forAll, mesh, primitiveMesh::nInternalFaces(), IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, fvMesh::time(), and Foam::Zero.
Member Data Documentation
mesh_
const polyMesh& mesh_ protected
Definition at line 69 of file extendedCellToFaceStencil.H.
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/extendedStencil/cellToFace/extendedCellToFaceStencil.H
src/finiteVolume/fvMesh/extendedStencil/cellToFace/extendedCellToFaceStencil.C
src/finiteVolume/fvMesh/extendedStencil/cellToFace/extendedCellToFaceStencilTemplates.C