OpenFOAM: FaceInteraction< CloudType > Class Template Reference
FaceInteraction< CloudType > Class Template Reference
Lagrangian particle models » Submodels » Function objects
Face zone-based particle interactions.
#include <FaceInteraction.H>
Public Types
enum class interactionType { ESCAPE , STICK , REBOUND }
typedef CloudType::parcelType parcelType
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Public Member Functions
TypeName ("faceInteraction")
FaceInteraction (const dictionary &dict, CloudType &owner, const word &modelName)
FaceInteraction (const FaceInteraction< CloudType > &ppm)
virtual autoPtr< CloudFunctionObject< CloudType > > clone () const
virtual ~FaceInteraction ()=default
virtual void postFace (const parcelType &p, bool &keepParticle)
Public Member Functions inherited from CloudFunctionObject< CloudType >
TypeName ("cloudFunctionObject")
declareRunTimeSelectionTable (autoPtr, CloudFunctionObject, dictionary,(const dictionary &dict, CloudType &owner, const word &modelName),(dict, owner, modelName))
CloudFunctionObject (CloudType &owner)
CloudFunctionObject (const dictionary &dict, CloudType &owner, const word &objectType, const word &modelName)
CloudFunctionObject (const CloudFunctionObject< CloudType > &ppm)
virtual ~CloudFunctionObject ()=default
virtual void preEvolve (const typename parcelType::trackingData &td)
virtual void postEvolve (const typename parcelType::trackingData &td)
virtual void postMove (parcelType &p, const scalar dt, const point &position0, bool &keepParticle)
virtual void postPatch (const parcelType &p, const polyPatch &pp, bool &keepParticle)
virtual void postFace (const parcelType &p, bool &keepParticle)
const fileName & outputDir () const
fileName writeTimeDir () const
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
virtual ~CloudSubModelBase ()=default
const CloudType & owner () const
virtual bool writeTime () const
virtual fileName localPath () const
CloudType & owner ()
virtual void info ()
virtual void write (Ostream &os) const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
subModelBase (const subModelBase &smb)
virtual ~subModelBase ()=default
const word & modelName () const
const dictionary & dict () const
const word & baseName () const
const word & modelType () const
const dictionary & coeffDict () const
const dictionary & properties () const
virtual bool defaultCoeffs (const bool printMsg) const
virtual bool active () const
virtual void cacheFields (const bool store)
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
bool getModelDict (const word &entryName, dictionary &dict) const
template<class Type >
bool getModelProperty (const word &entryName, Type &value) const
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Public Member Functions inherited from writeFile
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name="undefined", const bool writeToFile=true)
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name, const dictionary &dict, const bool writeToFile=true)
writeFile (const writeFile &wf)
virtual ~writeFile ()=default
virtual bool read (const dictionary &dict)
virtual OFstream & file ()
virtual bool writeToFile () const
virtual bool canWriteToFile () const
virtual bool canResetFile () const
virtual bool canWriteHeader () const
virtual label charWidth () const
virtual void writeCommented (Ostream &os, const string &str) const
virtual void writeTabbed (Ostream &os, const string &str) const
virtual void writeHeader (Ostream &os, const string &str) const
virtual void writeCurrentTime (Ostream &os) const
virtual void writeBreak (Ostream &os) const
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
template<class Type >
void writeValue (Ostream &os, const Type &val) const
Static Public Attributes
static const Enum< interactionType > interactionTypeNames_
Static Public Attributes inherited from writeFile
static label addChars = 8
Protected Member Functions
bool processParticle (const parcelType &p, const label localZonei)
void write ()
Protected Member Functions inherited from subModelBase
bool inLine () const
Protected Member Functions inherited from writeFile
void initStream (Ostream &os) const
fileName baseFileDir () const
fileName baseTimeDir () const
fileName filePath (const fileName &fName) const
virtual autoPtr< OFstream > newFile (const fileName &fName) const
virtual autoPtr< OFstream > newFileAtTime (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > newFileAtStartTime (const word &name) const
virtual void resetFile (const word &name)
Omanip< int > valueWidth (const label offset=0) const
void operator= (const writeFile &)=delete
virtual autoPtr< OFstream > createFile (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > createFile (const word &name) const
Additional Inherited Members
Static Public Member Functions inherited from CloudFunctionObject< CloudType >
static autoPtr< CloudFunctionObject< CloudType > > New (const dictionary &dict, CloudType &owner, const word &objectType, const word &modelName)
Public Attributes inherited from subModelBase
bool log
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Protected Attributes inherited from subModelBase
const word modelName_
dictionary & properties_
const dictionary dict_
const word baseName_
const word modelType_
const dictionary coeffDict_
Protected Attributes inherited from writeFile
const objectRegistry & fileObr_
const fileName prefix_
word fileName_
autoPtr< OFstream > filePtr_
label writePrecision_
bool writeToFile_
bool updateHeader_
bool writtenHeader_
bool useUserTime_
scalar startTime_
Detailed Description
template<class CloudType>
class Foam::FaceInteraction< CloudType >
Face zone-based particle interactions.
faceInteraction1
{
    type            faceInteraction;
    // List of (faceZone interactionType)
    faceZones
    (
        (faceZone1      stick)
        (faceZone2      escape)
        (faceZone3      rebound)
    );
    // Optional limiting to diameter range
    dMin            0;
    dMax            1;
    writeToFile     yes; // default = yes
}
File written per faceZone as:
postProcessing/lagrangian/cloudName/modelName/time/modelName_faceZone.dat
Source files
FaceInteraction.H
FaceInteraction.C
Definition at line 77 of file FaceInteraction.H.
Member Typedef Documentation
parcelType
template<class CloudType > typedef CloudType::parcelType parcelType
Definition at line 87 of file FaceInteraction.H.
Member Enumeration Documentation
interactionType
template<class CloudType > enum class interactionType strong
Enumerator
ESCAPE
particles escape/are removed
STICK
particles stick to the faceZone faces
REBOUND
particles rebound from the faceZone faces
Definition at line 90 of file FaceInteraction.H.
Constructor & Destructor Documentation
FaceInteraction() [1/2]
template<class CloudType > FaceInteraction (const dictionary & dict, CloudType & owner, const word & modelName)
Definition at line 128 of file FaceInteraction.C.
References PtrList< T >::append(), subModelBase::coeffDict(), Foam::endl(), UPtrList< T >::first(), Foam::Info, FaceInteraction< CloudType >::interactionTypeNames_, writeFile::newFileAtStartTime(), Foam::nl, CloudSubModelBase< CloudType >::owner(), points, Foam::reduce(), Foam::returnReduce(), PtrList< T >::set(), List< T >::setSize(), PtrList< T >::setSize(), UPtrList< T >::size(), List< T >::transfer(), Foam::type(), WarningInFunction, writeFile::writeCommented(), writeFile::writeHeaderValue(), writeFile::writeTabbed(), writeFile::writeToFile(), Foam::Zero, and zoneIDs.
FaceInteraction() [2/2]
template<class CloudType > FaceInteraction (const FaceInteraction< CloudType > & ppm)
Definition at line 238 of file FaceInteraction.C.
~FaceInteraction()
template<class CloudType > virtual ~FaceInteraction () virtual default
Member Function Documentation
processParticle()
template<class CloudType > bool processParticle (const parcelType & p, const label localZonei) protected
Definition at line 39 of file FaceInteraction.C.
References p.
write()
template<class CloudType > void write () protected virtual
Reimplemented from CloudFunctionObject< CloudType >.
Definition at line 61 of file FaceInteraction.C.
References Foam::endl(), polyMesh::faceZones(), forAll, Log_, mesh, Foam::nl, os(), Foam::returnReduce(), UPtrList< T >::size(), Foam::tab, Foam::type(), and Foam::Zero.
TypeName()
template<class CloudType > TypeName ("faceInteraction")
clone()
template<class CloudType > virtual autoPtr< CloudFunctionObject< CloudType > > clone () const inline virtual
Reimplemented from CloudFunctionObject< CloudType >.
Definition at line 164 of file FaceInteraction.H.
postFace()
template<class CloudType > void postFace (const parcelType & p, bool & keepParticle) virtual
Definition at line 259 of file FaceInteraction.C.
References Foam::abort(), f(), Foam::FatalError, FatalErrorInFunction, forAll, mesh, n, p, points, and Foam::Zero.
Member Data Documentation
interactionTypeNames_
template<class CloudType > const Foam::Enum< typename Foam::FaceInteraction< CloudType >::interactionType > interactionTypeNames_ static
Definition at line 98 of file FaceInteraction.H.
Referenced by FaceInteraction< CloudType >::FaceInteraction().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/CloudFunctionObjects/FaceInteraction/FaceInteraction.H
src/lagrangian/intermediate/submodels/CloudFunctionObjects/FaceInteraction/FaceInteraction.C