OpenFOAM: sphericalHeatTransfer Class Reference
sphericalHeatTransfer Class Reference
Model which applies an analytical solution for heat transfer from the surface of a sphere to the fluid within the sphere.
#include <sphericalHeatTransfer.H>
Public Member Functions
TypeName ("spherical")
sphericalHeatTransfer (const dictionary &dict, const phasePair &pair)
virtual ~sphericalHeatTransfer ()
tmp< volScalarField > K (const scalar residualAlpha) const
TypeName ("spherical")
sphericalHeatTransfer (const dictionary &dict, const phasePair &pair)
virtual ~sphericalHeatTransfer ()
tmp< volScalarField > K () const
Public Member Functions inherited from heatTransferModel
TypeName ("heatTransferModel")
declareRunTimeSelectionTable (autoPtr, heatTransferModel, dictionary,(const dictionary &dict, const phasePair &pair),(dict, pair))
heatTransferModel (const dictionary &dict, const phasePair &pair)
virtual ~heatTransferModel ()=default
tmp< volScalarField > K () const
TypeName ("heatTransferModel")
declareRunTimeSelectionTable (autoPtr, heatTransferModel, dictionary,(const dictionary &dict, const phasePair &pair),(dict, pair))
heatTransferModel (const dictionary &dict, const phasePair &pair)
virtual ~heatTransferModel ()=default
Additional Inherited Members
Static Public Member Functions inherited from heatTransferModel
static autoPtr< heatTransferModel > New (const dictionary &dict, const phasePair &pair)
static autoPtr< heatTransferModel > New (const dictionary &dict, const phasePair &pair)
Static Public Attributes inherited from heatTransferModel
static const dimensionSet dimK
Protected Attributes inherited from heatTransferModel
const phasePair & pair_
const dimensionedScalar residualAlpha_
Detailed Description
Model which applies an analytical solution for heat transfer from the surface of a sphere to the fluid within the sphere.
Source files
sphericalHeatTransfer.H
sphericalHeatTransfer.C
Source files
sphericalHeatTransfer.H
sphericalHeatTransfer.C
Definition at line 52 of file sphericalHeatTransfer.H.
Constructor & Destructor Documentation
sphericalHeatTransfer() [1/2]
sphericalHeatTransfer (const dictionary & dict, const phasePair & pair)
Definition at line 44 of file sphericalHeatTransfer.C.
~sphericalHeatTransfer() [1/2]
~sphericalHeatTransfer () virtual
Definition at line 56 of file sphericalHeatTransfer.C.
sphericalHeatTransfer() [2/2]
sphericalHeatTransfer (const dictionary & dict, const phasePair & pair)
~sphericalHeatTransfer() [2/2]
virtual ~sphericalHeatTransfer () virtual
Member Function Documentation
TypeName() [1/2]
TypeName ("spherical")
K() [1/2]
Foam::tmp< Foam::volScalarField > K (const scalar residualAlpha) const virtual
Implements heatTransferModel.
Definition at line 63 of file sphericalHeatTransfer.C.
References Foam::max(), and Foam::sqr().
TypeName() [2/2]
TypeName ("spherical")
K() [2/2]
Foam::tmp< Foam::volScalarField > K () const virtual
Implements heatTransferModel.
Definition at line 63 of file sphericalHeatTransfer.C.
References Foam::max(), and Foam::sqr().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/interfacialModels/heatTransferModels/sphericalHeatTransfer/sphericalHeatTransfer.H
src/phaseSystemModels/twoPhaseEuler/twoPhaseSystem/interfacialModels/heatTransferModels/sphericalHeatTransfer/sphericalHeatTransfer.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/interfacialModels/heatTransferModels/sphericalHeatTransfer/sphericalHeatTransfer.C
src/phaseSystemModels/twoPhaseEuler/twoPhaseSystem/interfacialModels/heatTransferModels/sphericalHeatTransfer/sphericalHeatTransfer.C