OpenFOAM: Luo Class Reference
Luo Class Reference
Model of Luo (1993). The coalescence rate is calculated by.
#include <Luo.H>
Public Member Functions
TypeName ("Luo")
Luo (const populationBalanceModel &popBal, const dictionary &dict)
virtual ~Luo ()=default
virtual void addToCoalescenceRate (volScalarField &coalescenceRate, const label i, const label j)
Public Member Functions inherited from coalescenceModel
TypeName ("coalescenceModel")
declareRunTimeSelectionTable (autoPtr, coalescenceModel, dictionary,(const populationBalanceModel &popBal, const dictionary &dict),(popBal, dict))
coalescenceModel (const populationBalanceModel &popBal, const dictionary &dict)
autoPtr< coalescenceModel > clone () const
virtual ~coalescenceModel ()=default
virtual void correct ()
Additional Inherited Members
Static Public Member Functions inherited from coalescenceModel
static autoPtr< coalescenceModel > New (const word &type, const populationBalanceModel &popBal, const dictionary &dict)
Protected Attributes inherited from coalescenceModel
const populationBalanceModel & popBal_
Detailed Description
Model of Luo (1993). The coalescence rate is calculated by.
where
is the mean approach velocity of the bubbles and
their size ratio.
= Diameter of bubble i [m]
= Diameter of bubble j [m]
= Mean approach velocity [m/s]
= Bubble size ratio [-]
= Density of dispersed phase [kg/m3]
= Density of continuous phase [kg/m3]
= Surface tension [N/m]
= Virtual mass coefficient [-]
= Coefficient [-]
= Coefficient [-]
= Continuous phase turbulent dissipation rate [m2/s3]
Reference:
        Luo, H. (1993).
        Coalescence, breakup and liquid circulation in bubble column reactors.
        Dr. Ing (Doctoral dissertation, Thesis, Department of Chemical
        Engineering, The Norwegian Institute of Technology, Trondheim, Norway).
Usage
Property Description Required Default value
beta Coefficient beta no 2.0
C1 Coefficient C1 no 1.0
Source files
Luo.H
Luo.C
Definition at line 164 of file Luo.H.
Constructor & Destructor Documentation
Luo()
Luo (const populationBalanceModel & popBal, const dictionary & dict)
Definition at line 52 of file Luo.C.
References Foam::dimless.
~Luo()
virtual ~Luo () virtual default
Member Function Documentation
TypeName()
TypeName ("Luo")
addToCoalescenceRate()
void addToCoalescenceRate (volScalarField & coalescenceRate, const label i, const label j) virtual
Implements coalescenceModel.
Definition at line 67 of file Luo.C.
References Foam::cbrt(), Foam::exit(), Foam::exp(), Foam::FatalError, FatalErrorInFunction, Foam::pow(), Foam::pow3(), phaseModel::rho(), Foam::sqr(), and Foam::sqrt().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/populationBalanceModel/coalescenceModels/Luo/Luo.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/populationBalanceModel/coalescenceModels/Luo/Luo.C