OpenFOAM: PackedList< Width >::reference Class Reference
PackedList< Width >::reference Class Reference
#include <PackedList.H>
Public Member Functions
reference (const reference &)=default
reference (reference &&)=default
void operator= (const reference &other)
void operator= (const unsigned int val)
operator unsigned int () const
Protected Member Functions
void operator& ()=delete
reference (PackedList *parent, const label index)
unsigned int get () const
bool set (unsigned int val)
Protected Attributes
block_type & ref_
unsigned shift_
Friends
class PackedList
Detailed Description
template<unsigned Width>
class Foam::PackedList< Width >::reference
Definition at line 467 of file PackedList.H.
Constructor & Destructor Documentation
reference() [1/3]
template<unsigned Width> reference (PackedList * parent, const label index) inline protected
reference() [2/3]
template<unsigned Width> reference (const reference &) default
reference() [3/3]
template<unsigned Width> reference (reference &&) default
Member Function Documentation
operator&()
template<unsigned Width> void operator& () protected delete
get()
template<unsigned Width> unsigned int get () const inline protected
Definition at line 295 of file PackedListI.H.
Referenced by PackedList< Width >::get(), and PackedList< Width >::remove().
set()
template<unsigned Width> bool set (unsigned int val) inline protected
Definition at line 302 of file PackedListI.H.
Referenced by PackedList< Width >::push_back(), PackedList< Width >::set(), and PackedList< Width >::unset().
operator=() [1/2]
template<unsigned Width> void operator= (const reference & other) inline
Definition at line 322 of file PackedListI.H.
operator=() [2/2]
template<unsigned Width> void operator= (const unsigned int val) inline
Definition at line 333 of file PackedListI.H.
operator unsigned int()
template<unsigned Width> operator unsigned int () const inline
Definition at line 343 of file PackedListI.H.
Friends And Related Symbol Documentation
PackedList
template<unsigned Width> friend class PackedList friend
Definition at line 471 of file PackedList.H.
Member Data Documentation
ref_
template<unsigned Width> block_type& ref_ protected
Definition at line 475 of file PackedList.H.
shift_
template<unsigned Width> unsigned shift_ protected
Definition at line 478 of file PackedList.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/Bits/PackedList/PackedList.H
src/OpenFOAM/containers/Bits/PackedList/PackedListI.H