OpenFOAM: solidificationMeltingSource Class Reference
solidificationMeltingSource Class Reference
Numerics » Finite volume Options » Sources
This source is designed to model the effect of solidification and melting processes, e.g. windhield defrosting, within a specified region. The phase change occurs at the melting temperature, Tmelt.
#include <solidificationMeltingSource.H>
Public Types
enum thermoMode { mdThermo , mdLookup }
Public Types inherited from cellSetOption
enum selectionModeType {
smAll , smCellSet , smCellZone , smPoints ,
smGeometric , smCellType
}
Public Member Functions
TypeName ("solidificationMeltingSource")
solidificationMeltingSource (const word &sourceName, const word &modelType, const dictionary &dict, const fvMesh &mesh)
solidificationMeltingSource (const solidificationMeltingSource &)=delete
void operator= (const solidificationMeltingSource &)=delete
~solidificationMeltingSource ()=default
virtual void addSup (fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (fvMatrix< vector > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldi)
virtual bool read (const dictionary &dict)
Public Member Functions inherited from cellSetOption
TypeName ("cellSetOption")
cellSetOption (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
virtual ~cellSetOption ()=default
scalar timeStart () const noexcept
scalar duration () const noexcept
bool inTimeLimits (const scalar timeValue) const
bool useSubMesh () const noexcept
selectionModeType selectionMode () const noexcept
const wordRes & selectionNames () const noexcept
const wordRe & zoneName () const
scalar V () const noexcept
const labelList & cells () const noexcept
scalar timeStart (scalar val) noexcept
scalar duration (scalar val) noexcept
virtual bool isActive ()
const word & cellSetName () const
Public Member Functions inherited from option
TypeName ("option")
declareRunTimeSelectionTable (autoPtr, option, dictionary,(const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh),(name, modelType, dict, mesh))
option (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
autoPtr< option > clone () const
virtual ~option ()=default
const word & name () const noexcept
const fvMesh & mesh () const noexcept
const dictionary & coeffs () const noexcept
bool active () const noexcept
void setApplied (const label fieldi)
bool active (const bool on) noexcept
virtual label applyToField (const word &fieldName) const
virtual void checkApplied () const
virtual void addSup (fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (fvMatrix< tensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< scalar > &eqn, const label fieldi)
virtual void constrain (fvMatrix< vector > &eqn, const label fieldi)
virtual void constrain (fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< tensor > &eqn, const label fieldi)
virtual void correct (volScalarField &field)
virtual void correct (volVectorField &field)
virtual void correct (volSphericalTensorField &field)
virtual void correct (volSymmTensorField &field)
virtual void correct (volTensorField &field)
virtual void postProcessSens (scalarField &sensField, const word &fieldName=word::null, const word &designVariablesName=word::null)
virtual void postProcessSens (vectorField &sensField, const word &fieldName=word::null, const word &designVariablesName=word::null)
virtual void postProcessSens (tensorField &sensField, const word &fieldName=word::null, const word &designVariablesName=word::null)
virtual void writeHeader (Ostream &) const
virtual void writeFooter (Ostream &) const
virtual void writeData (Ostream &) const
Static Public Attributes
static const Enum< thermoMode > thermoModeTypeNames_
Static Public Attributes inherited from cellSetOption
static const Enum< selectionModeType > selectionModeTypeNames_
Additional Inherited Members
Static Public Member Functions inherited from option
static autoPtr< option > New (const word &name, const dictionary &dict, const fvMesh &mesh)
Public Attributes inherited from option
bool log
Protected Member Functions inherited from cellSetOption
void setSelection (const dictionary &dict)
void setCellSelection ()
void setVol ()
Protected Member Functions inherited from option
void resetApplied ()
Protected Attributes inherited from cellSetOption
scalar timeStart_
scalar duration_
selectionModeType selectionMode_
wordRes selectionNames_
List< point > points_
dictionary geometricSelection_
labelList cells_
scalar V_
Protected Attributes inherited from option
const word name_
const word modelType_
const fvMesh & mesh_
dictionary dict_
dictionary coeffs_
wordList fieldNames_
List< bool > applied_
bool active_
Detailed Description
This source is designed to model the effect of solidification and melting processes, e.g. windhield defrosting, within a specified region. The phase change occurs at the melting temperature, Tmelt.
The presence of the solid phase in the flow field is incorporated into the model as a momentum porosity contribution; the energy associated with the phase change is added as an enthalpy contribution.
References:
    Voller, V. R., & Prakash, C. (1987).
    A fixed grid numerical modelling methodology for
    convection-diffusion mushy region phase-change problems.
    International Journal of Heat and Mass Transfer, 30(8), 1709-1719.
    DOI:10.1016/0017-9310(87)90317-6
    Swaminathan, C. R., & Voller, V. R. (1992).
    A general enthalpy method for modeling solidification processes.
    Metallurgical transactions B, 23(5), 651-664.
    DOI:10.1007/BF02649725
The model generates a field <name>:alpha1 which can be visualised to to show the melt distribution as a fraction [0-1].
Usage
Minimal example by using constant/fvOptions:
solidificationMeltingSource1
{
    // Mandatory entries (unmodifiable)
    type           solidificationMeltingSource;
    // Mandatory entries (runtime modifiable)
    Tmelt          273;
    L              334000;
    thermoMode     <thermoModeName>;
    rhoRef         800;
    beta           5e-6;
    // Optional entries (runtime modifiable)
    relax          0.9;
    T              <Tname>;
    rho            <rhoName>;
    U              <Uname>;
    phi            <phiName>;
    Cu             1e5;
    q              1e-2;
    // Conditional optional entries (runtime modifiable)
        // when thermoMode=lookup
        Cp         Cp;
    // Conditional mandatory entries (runtime modifiable)
        // when Cp=CpRef
        CpRef  1000;
    // Mandatory/Optional (inherited) entries
    ...
}
where the entries mean:
Property Description Type Reqd Dflt
type Type name: solidificationMeltingSource word yes -
Tmelt Melting temperature [K] scalar yes -
L Latent heat of fusion [J/kg] scalar yes -
thermoMode Thermo mode word yes -
rhoRef Reference (solid) density scalar yes -
beta Thermal expansion coefficient [1/K] scalar yes -
relax Relaxation factor [0-1] scakar no 0.9
T Name of operand temperature field word no T
rho Name of operand density field word no rho
U Name of operand velocity field word no U
phi Name of operand flux field word no phi
Cu
Mushy region momentum sink coefficient [1/s]
scalar no 1e5
q Coefficient used in porosity calc scalar no 1e-2
Cp Name of specific heat capacity field word cndtnl Cp
CpRef Specific heat capacity value scalar cndtnl -
The inherited entries are elaborated in:
fvOption.H
cellSetOption.H
Options for the thermoMode entry:
      thermo    | Access Cp information from database
      lookup    | Access Cp information by looking up from dictionary
Source files
solidificationMeltingSource.H
solidificationMeltingSource.C
solidificationMeltingSourceTemplates.C
Definition at line 247 of file solidificationMeltingSource.H.
Member Enumeration Documentation
thermoMode
enum thermoMode
Enumerator
mdThermo
mdLookup
Definition at line 256 of file solidificationMeltingSource.H.
Constructor & Destructor Documentation
solidificationMeltingSource() [1/2]
solidificationMeltingSource (const word & sourceName, const word & modelType, const dictionary & dict, const fvMesh & mesh)
Definition at line 155 of file solidificationMeltingSource.C.
References Foam::abort(), basicThermo::dictName, Foam::FatalError, FatalErrorInFunction, option::fieldNames_, fv(), solidificationMeltingSource::mdLookup, solidificationMeltingSource::mdThermo, option::mesh_, option::resetApplied(), List< T >::resize(), and solidificationMeltingSource::thermoModeTypeNames_.
solidificationMeltingSource() [2/2]
solidificationMeltingSource (const solidificationMeltingSource &) delete
~solidificationMeltingSource()
~solidificationMeltingSource () default
Member Function Documentation
TypeName()
TypeName ("solidificationMeltingSource")
operator=()
void operator= (const solidificationMeltingSource &) delete
addSup() [1/4]
void addSup (fvMatrix< scalar > & eqn, const label fieldi) virtual
Reimplemented from option.
Definition at line 225 of file solidificationMeltingSource.C.
References Foam::apply().
addSup() [2/4]
void addSup (fvMatrix< vector > & eqn, const label fieldi) virtual
Reimplemented from option.
Definition at line 246 of file solidificationMeltingSource.C.
References Cp, Foam::endl(), forAll, g, Foam::Info, gravity::New(), Foam::pow3(), Sp, Foam::sqr(), Su, Foam::type(), and update().
addSup() [3/4]
void addSup (const volScalarField & rho, fvMatrix< scalar > & eqn, const label fieldi) virtual
Reimplemented from option.
Definition at line 235 of file solidificationMeltingSource.C.
References Foam::apply(), and rho.
addSup() [4/4]
void addSup (const volScalarField & rho, fvMatrix< vector > & eqn, const label fieldi) virtual
Reimplemented from option.
Definition at line 283 of file solidificationMeltingSource.C.
read()
bool read (const dictionary & dict) virtual
Reimplemented from cellSetOption.
Definition at line 295 of file solidificationMeltingSource.C.
References dict, and cellSetOption::read().
Member Data Documentation
thermoModeTypeNames_
const Foam::Enum< Foam::fv::solidificationMeltingSource::thermoMode > thermoModeTypeNames_ static
Definition at line 263 of file solidificationMeltingSource.H.
Referenced by solidificationMeltingSource::solidificationMeltingSource().
The documentation for this class was generated from the following files:
src/fvOptions/sources/derived/solidificationMeltingSource/solidificationMeltingSource.H
src/fvOptions/sources/derived/solidificationMeltingSource/solidificationMeltingSource.C
src/fvOptions/sources/derived/solidificationMeltingSource/solidificationMeltingSourceTemplates.C