OpenFOAM: correctedLnGrad< Type > Class Template Reference
correctedLnGrad< Type > Class Template Reference
Simple central-difference lnGrad scheme with non-orthogonal correction.
#include <correctedLnGrad.H>
Public Member Functions
TypeName ("corrected")
correctedLnGrad (const faMesh &mesh)
correctedLnGrad (const faMesh &mesh, Istream &)
virtual ~correctedLnGrad ()
virtual tmp< edgeScalarField > deltaCoeffs (const GeometricField< Type, faPatchField, areaMesh > &) const
virtual bool corrected () const
virtual tmp< GeometricField< Type, faePatchField, edgeMesh > > correction (const GeometricField< Type, faPatchField, areaMesh > &) const
Public Member Functions inherited from lnGradScheme< Type >
declareRunTimeSelectionTable (tmp, lnGradScheme, Mesh,(const faMesh &mesh, Istream &schemeData),(mesh, schemeData))
lnGradScheme (const faMesh &mesh)
virtual ~lnGradScheme ()
const faMesh & mesh () const
virtual tmp< GeometricField< Type, faePatchField, edgeMesh > > lnGrad (const GeometricField< Type, faPatchField, areaMesh > &) const
tmp< GeometricField< Type, faePatchField, edgeMesh > > lnGrad (const tmp< GeometricField< Type, faPatchField, areaMesh > > &) const
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Additional Inherited Members
Static Public Member Functions inherited from lnGradScheme< Type >
static tmp< lnGradScheme< Type > > New (const faMesh &mesh, Istream &schemeData)
static tmp< GeometricField< Type, faePatchField, edgeMesh > > lnGrad (const GeometricField< Type, faPatchField, areaMesh > &, const tmp< edgeScalarField > &, const word &snGradName="lnGrad")
Detailed Description
template<class Type>
class Foam::fa::correctedLnGrad< Type >
Simple central-difference lnGrad scheme with non-orthogonal correction.
Source files
correctedLnGrad.H
correctedLnGrad.C
Definition at line 52 of file correctedLnGrad.H.
Constructor & Destructor Documentation
correctedLnGrad() [1/2]
template<class Type > correctedLnGrad (const faMesh & mesh) inline
Definition at line 71 of file correctedLnGrad.H.
correctedLnGrad() [2/2]
template<class Type > correctedLnGrad (const faMesh & mesh, Istream &) inline
Definition at line 78 of file correctedLnGrad.H.
~correctedLnGrad()
template<class Type > ~correctedLnGrad () virtual
Definition at line 40 of file correctedLnGrad.C.
Member Function Documentation
TypeName()
template<class Type > TypeName ("corrected")
deltaCoeffs()
template<class Type > virtual tmp< edgeScalarField > deltaCoeffs (const GeometricField< Type, faPatchField, areaMesh > &) const inline virtual
Implements lnGradScheme< Type >.
Definition at line 91 of file correctedLnGrad.H.
References lnGradScheme< Type >::mesh().
corrected()
template<class Type > virtual bool corrected () const inline virtual
Reimplemented from lnGradScheme< Type >.
Definition at line 100 of file correctedLnGrad.H.
References lnGradScheme< Type >::mesh().
correction()
template<class Type > tmp< GeometricField< Type, faePatchField, edgeMesh > > correction (const GeometricField< Type, faPatchField, areaMesh > & vf) const virtual
Reimplemented from lnGradScheme< Type >.
Definition at line 48 of file correctedLnGrad.C.
References mesh, Foam::New(), and Foam::type().
The documentation for this class was generated from the following files:
src/finiteArea/finiteArea/lnGradSchemes/correctedLnGrad/correctedLnGrad.H
src/finiteArea/finiteArea/lnGradSchemes/correctedLnGrad/correctedLnGrad.C