OpenFOAM: triSurface Class Reference
triSurface Class Reference
Triangulated surface description with patch information.
#include <triSurface.H>
Public Types
typedef bool BoundaryMesh
typedef labelledTri face_type
typedef point point_type
Public Types inherited from PrimitivePatch<::Foam::List< labelledTri >, pointField >
enum surfaceTopo
typedef std::remove_reference< ::Foam::List< labelledTri > >::type::value_type face_type
typedef std::remove_reference< pointField >::type::value_type point_type
typedef ::Foam::List< labelledTri > FaceListType
typedef pointField PointFieldType
typedef face_type FaceType
Public Types inherited from List< labelledTri >
typedef SubList< labelledTri > subList
Public Types inherited from UList< T >
typedef T value_type
typedef T * pointer
typedef const T * const_pointer
typedef T & reference
typedef const T & const_reference
typedef T * iterator
typedef const T * const_iterator
typedef label size_type
typedef label difference_type
typedef std::reverse_iterator< iterator > reverse_iterator
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
Public Member Functions
ClassName ("triSurface")
triSurface ()
triSurface (const triSurface &surf)
triSurface (triSurface &&surf)
triSurface (const List< labelledTri > &triangles, const geometricSurfacePatchList &patches, const pointField &pts)
triSurface (List< labelledTri > &triangles, const geometricSurfacePatchList &patches, pointField &pts, const bool reuse)
triSurface (const List< labelledTri > &triangles, const pointField &pts)
triSurface (const triFaceList &triangles, const pointField &pts)
triSurface (const fileName &name, const scalar scaleFactor=-1)
triSurface (const fileName &name, const word &fileType, const scalar scaleFactor=-1)
triSurface (Istream &is)
triSurface (const Time &d)
triSurface (const IOobject &io, const dictionary &dict, const bool isGlobal=true)
virtual ~triSurface ()
void clearOut ()
void clearTopology ()
void clearPatchMeshAddr ()
void swap (triSurface &surf)
const geometricSurfacePatchList & patches () const noexcept
geometricSurfacePatchList & patches () noexcept
const List< labelledTri > & surfFaces () const noexcept
const labelListList & sortedEdgeFaces () const
const labelList & edgeOwner () const
const vectorField & Sf () const
const scalarField & magSf () const
const vectorField & Cf () const
List< surfZone > sortedZones (labelList &faceMap) const
void triFaceFaces (List< face > &plainFaceList) const
virtual void movePoints (const pointField &pts)
virtual void swapPoints (pointField &pts)
virtual void scalePoints (const scalar scaleFactor)
void checkTriangles (const bool verbose)
void checkEdges (const bool verbose)
void cleanup (const bool verbose)
void compactPoints (labelList &pointMap=const_cast< labelList & >(labelList::null()))
void markZone (const boolList &borderEdge, const label facei, const label currentZone, labelList &faceZone) const
label markZones (const boolList &borderEdge, labelList &faceZone) const
template<class BoolListType >
void subsetMeshMap (const BoolListType &include, labelList &pointMap, labelList &faceMap) const
triSurface subsetMesh (const UList< bool > &include, labelList &pointMap, labelList &faceMap) const
triSurface subsetMesh (const bitSet &include, labelList &pointMap, labelList &faceMap) const
triSurface subsetMesh (const UList< bool > &include) const
triSurface subsetMesh (const bitSet &include) const
triSurface subsetMesh (const wordRes &includeNames, const wordRes &excludeNames=wordRes()) const
void swapFaces (List< labelledTri > &faceLst)
void transfer (triSurface &surf)
void transfer (MeshedSurface< labelledTri > &surf)
void write (Ostream &os) const
void write (const fileName &, const bool sortByRegion=false) const
void write (const fileName &filename, const word &fileType, const bool sortByRegion=false) const
void write (const Time &d) const
void writeStats (Ostream &os) const
void operator= (const triSurface &surf)
void operator= (triSurface &&surf)
void operator= (MeshedSurface< labelledTri > &&surf)
Public Member Functions inherited from PrimitivePatch<::Foam::List< labelledTri >, pointField >
PrimitivePatch (const ::Foam::List< labelledTri > &faces, const pointField &points)
PrimitivePatch (::Foam::List< labelledTri > &&faces, const pointField &points)
PrimitivePatch (::Foam::List< labelledTri > &faces, pointField &points, const bool reuse)
PrimitivePatch (const PrimitivePatch< ::Foam::List< labelledTri >, pointField > &pp)
virtual ~PrimitivePatch ()
void clearOut ()
void clearGeom ()
void clearTopology ()
void clearPatchMeshAddr ()
void swap (PrimitivePatch &)=delete
const Field< point_type > & points () const noexcept
label nFaces () const noexcept
label nPoints () const
label nEdges () const
const edgeList & edges () const
const edgeList::subList internalEdges () const
const edgeList::subList boundaryEdges () const
label nInternalEdges () const
label nBoundaryEdges () const
bool isInternalEdge (const label edgei) const
const labelList & boundaryPoints () const
const labelListList & faceFaces () const
const labelListList & edgeFaces () const
const labelListList & faceEdges () const
const labelListList & pointEdges () const
const labelListList & pointFaces () const
const List< face_type > & localFaces () const
labelList boundaryFaces () const
labelList uniqBoundaryFaces () const
const labelList & meshPoints () const
const Map< label > & meshPointMap () const
const Field< point_type > & localPoints () const
const labelList & localPointOrder () const
label whichPoint (const label gp) const
edge meshEdge (const label edgei) const
edge meshEdge (const edge &e) const
label meshEdge (const label edgei, const edgeList &allEdges, const labelListList &pointEdges) const
label findEdge (const edge &e) const
labelList meshEdges (const edgeList &allEdges, const labelListList &cellEdges, const labelList &faceCells) const
labelList meshEdges (const edgeList &allEdges, const labelListList &pointEdges) const
labelList meshEdges (const labelUList &edgeLabels, const edgeList &allEdges, const labelListList &pointEdges) const
const Field< point_type > & faceCentres () const
const Field< point_type > & faceAreas () const
const Field< scalar > & magFaceAreas () const
const Field< point_type > & faceNormals () const
const Field< point_type > & pointNormals () const
Pair< point_type > box () const
scalar sphere (const label facei) const
bool hasFaceAreas () const
bool hasFaceCentres () const
bool hasFaceNormals () const
bool hasPointNormals () const
bool hasBoundaryPoints () const
bool hasEdges () const
bool hasFaceFaces () const
bool hasEdgeFaces () const
bool hasFaceEdges () const
bool hasPointEdges () const
bool hasPointFaces () const
bool hasMeshPoints () const
bool hasMeshPointMap () const
List< objectHit > projectPoints (const ToPatch &targetPatch, const Field< point_type > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Foam::List< Foam::objectHit > projectPoints (const ToPatch &targetPatch, const Field< typename Foam::PrimitivePatch< ::Foam::List< labelledTri >, pointField >::point_type > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
List< objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< point_type > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Foam::List< Foam::objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< typename Foam::PrimitivePatch< ::Foam::List< labelledTri >, pointField >::point_type > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
const labelListList & edgeLoops () const
surfaceTopo surfaceType (labelHashSet *badEdgesPtr=nullptr) const
bool checkTopology (const bool report=false, labelHashSet *pointSetPtr=nullptr) const
bool checkPointManifold (const bool report=false, labelHashSet *pointSetPtr=nullptr) const
virtual void movePoints (const Field< point_type > &)
void operator= (const PrimitivePatch< ::Foam::List< labelledTri >, pointField > &rhs)
void operator= (PrimitivePatch< ::Foam::List< labelledTri >, pointField > &&rhs)
label whichEdge (const edge &e) const
Public Member Functions inherited from PrimitivePatchBase
ClassName ("PrimitivePatch")
PrimitivePatchBase ()=default
Public Member Functions inherited from List< labelledTri >
constexpr List () noexcept
List (const label len)
List (const label len, const labelledTri &val)
List (const label len, const Foam::zero)
List (const Foam::one, const labelledTri &val)
List (const Foam::one, labelledTri &&val)
List (const Foam::one, const Foam::zero)
List (const List< labelledTri > &a)
List (const UList< labelledTri > &a)
List (List< labelledTri > &a, bool reuse)
List (const UList< labelledTri > &list, const labelUList &indices)
List (const UList< labelledTri > &list, const FixedList< label, N > &indices)
List (const FixedList< labelledTri, N > &list)
List (const PtrList< labelledTri > &list)
List (const SLList< labelledTri > &list)
List (const IndirectListBase< labelledTri, Addr > &list)
List (std::initializer_list< labelledTri > list)
List (List< labelledTri > &&list)
List (DynamicList< labelledTri, SizeMin > &&list)
List (SLList< labelledTri > &&list)
List (Istream &is)
autoPtr< List< labelledTri > > clone () const
~List ()
void clear ()
void resize (const label len)
void resize (const label len, const labelledTri &val)
void resize (const label newLen)
void resize_nocopy (const label len)
void setSize (const label n)
void setSize (const label n, const labelledTri &val)
void transfer (List< labelledTri > &list)
void transfer (DynamicList< labelledTri, SizeMin > &list)
labelledTri & newElmt (const label i)
labelledTri & emplace_back (Args &&... args)
void push_back (const labelledTri &val)
void push_back (labelledTri &&val)
void push_back (const UList< labelledTri > &list)
void push_back (const IndirectListBase< labelledTri, Addr > &list)
label push_uniq (const labelledTri &val)
void pop_back (label n=1)
void operator= (const UList< labelledTri > &a)
void operator= (const List< labelledTri > &list)
void operator= (const SLList< labelledTri > &list)
void operator= (const IndirectListBase< labelledTri, Addr > &list)
void operator= (const FixedList< labelledTri, N > &list)
void operator= (std::initializer_list< labelledTri > list)
void operator= (const labelledTri &val)
void operator= (const Foam::zero)
void operator= (List< labelledTri > &&list)
void operator= (DynamicList< labelledTri, SizeMin > &&list)
void operator= (SLList< labelledTri > &&list)
Istream & readList (Istream &is)
Istream & readList (Istream &is)
Istream & readList (Istream &is)
void shallowCopy (const UList< labelledTri > &)=delete
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type set (const label i, bool val=true)
void append (const labelledTri &val)
void append (labelledTri &&val)
void append (const UList< labelledTri > &list)
void append (const IndirectListBase< labelledTri, Addr > &list)
label appendUniq (const labelledTri &val)
Public Member Functions inherited from UList< T >
UList (const UList< T > &)=default
constexpr UList () noexcept
UList (T *__restrict__ v, const label len) noexcept
label fcIndex (const label i) const noexcept
label rcIndex (const label i) const noexcept
const T & fcValue (const label i) const
T & fcValue (const label i)
const T & rcValue (const label i) const
T & rcValue (const label i)
const T * cdata () const noexcept
T * data () noexcept
const char * cdata_bytes () const noexcept
char * data_bytes () noexcept
T & front ()
const T & front () const
T & back ()
const T & back () const
std::streamsize size_bytes () const noexcept
std::streamsize byteSize () const
void checkStart (const label start) const
void checkSize (const label size) const
void checkRange (const label start, const label len) const
void checkIndex (const label i) const
bool uniform () const
label find (const T &val, label pos=0) const
label rfind (const T &val, label pos=-1) const
bool contains (const T &val, label pos=0) const
void moveFirst (const label i)
void moveLast (const label i)
void swapFirst (const label i)
void swapLast (const label i)
void shallowCopy (const UList< T > &list)
void deepCopy (const UList< T > &list)
template<class Addr >
void deepCopy (const IndirectListBase< T, Addr > &list)
SubList< T > slice (const label pos, label len=-1)
const SubList< T > slice (const label pos, label len=-1) const
SubList< T > slice (const labelRange &range)
const SubList< T > slice (const labelRange &range) const
T & operator[] (const label i)
const T & operator[] (const label i) const
operator const Foam::List< T > & () const
void operator= (const T &val)
void operator= (const Foam::zero)
iterator begin () noexcept
iterator end () noexcept
iterator begin (const label i) noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
const_iterator begin () const noexcept
const_iterator end () const noexcept
const_iterator cbegin (const label i) const noexcept
const_iterator begin (const label i) const noexcept
reverse_iterator rbegin ()
reverse_iterator rend ()
const_reverse_iterator crbegin () const
const_reverse_iterator crend () const
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
bool empty () const noexcept
label size () const noexcept
void swap (UList< T > &list)
bool operator== (const UList< T > &a) const
bool operator!= (const UList< T > &a) const
bool operator< (const UList< T > &list) const
bool operator> (const UList< T > &a) const
bool operator<= (const UList< T > &a) const
bool operator>= (const UList< T > &a) const
Istream & readList (Istream &is)
void writeEntry (const word &keyword, Ostream &os) const
Ostream & writeList (Ostream &os, const label shortLen=0) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type test (const label i) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type get (const label i) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type unset (const label i)
T & first ()
const T & first () const
T & last ()
const T & last () const
bool found (const T &val, label pos=0) const
Istream & readList (Istream &is)
Ostream & writeList (Ostream &os, const label) const
const bool & operator[] (const label i) const
UPstream::commsStruct & operator[] (const label procID)
const UPstream::commsStruct & operator[] (const label procID) const
Foam::UPstream::commsStruct & operator[] (const label procID)
const Foam::UPstream::commsStruct & operator[] (const label procID) const
Ostream & writeList (Ostream &os, const label) const
Istream & readList (Istream &is)
Static Public Member Functions
static fileName triSurfInstance (const Time &)
static wordHashSet readTypes ()
static wordHashSet writeTypes ()
static bool canReadType (const word &fileType, bool verbose=false)
static bool canWriteType (const word &fileType, bool verbose=false)
static bool canRead (const fileName &name, bool verbose=false)
static fileName relativeFilePath (const IOobject &io, const fileName &f, const bool isGlobal=true)
static fileName checkFile (const IOobject &io, const bool isGlobal=true)
static fileName checkFile (const IOobject &io, const dictionary &dict, const bool isGlobal=true)
static fileName findFile (const IOobject &io, const bool isGlobal=true)
static fileName findFile (const IOobject &io, const dictionary &dict, const bool isGlobal=true)
static autoPtr< triSurface > New (const fileName &name, const word &fileType)
static autoPtr< triSurface > New (const fileName &name)
Static Public Member Functions inherited from List< labelledTri >
static const List< labelledTri > & null ()
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
static constexpr label max_size () noexcept
Protected Member Functions
pointField & storedPoints ()
List< labelledTri > & storedFaces ()
Protected Member Functions inherited from UList< T >
void setAddressableSize (const label n) noexcept
void size (const label n)
void writeEntry (Ostream &os) const
labelRange validateRange (const labelRange &requestedRange) const
UList< T > & operator= (const UList< T > &)=delete
void writeEntry (Ostream &os) const
void writeEntry (Ostream &os) const
Friends
Istream & operator>> (Istream &is, triSurface &s)
Ostream & operator<< (Ostream &os, const triSurface &s)
Detailed Description
Triangulated surface description with patch information.
Source files
triSurface.H
triSurface.C
triSurfaceAddressing.C
triSurfaceIO.C
triSurfaceStitch.C
Definition at line 71 of file triSurface.H.
Member Typedef Documentation
BoundaryMesh
typedef bool BoundaryMesh
Definition at line 201 of file triSurface.H.
face_type
typedef labelledTri face_type
Definition at line 204 of file triSurface.H.
point_type
typedef point point_type
Definition at line 207 of file triSurface.H.
Constructor & Destructor Documentation
triSurface() [1/12]
triSurface ()
Definition at line 425 of file triSurface.C.
Referenced by booleanSurface::booleanSurface(), and intersectedSurface::intersectedSurface().
triSurface() [2/12]
triSurface (const triSurface & surf)
Definition at line 434 of file triSurface.C.
triSurface() [3/12]
triSurface (triSurface && surf)
Definition at line 443 of file triSurface.C.
References triSurface::transfer().
triSurface() [4/12]
triSurface (const List< labelledTri > & triangles, const geometricSurfacePatchList & patches, const pointField & pts)
Definition at line 451 of file triSurface.C.
triSurface() [5/12]
triSurface (List< labelledTri > & triangles, const geometricSurfacePatchList & patches, pointField & pts, const bool reuse)
Definition at line 465 of file triSurface.C.
triSurface() [6/12]
triSurface (const List< labelledTri > & triangles, const pointField & pts)
Definition at line 480 of file triSurface.C.
triSurface() [7/12]
triSurface (const triFaceList & triangles, const pointField & pts)
Definition at line 495 of file triSurface.C.
triSurface() [8/12]
triSurface (const fileName & name, const scalar scaleFactor = -1) explicit
Definition at line 510 of file triSurface.C.
triSurface() [9/12]
triSurface (const fileName & name, const word & fileType, const scalar scaleFactor = -1)
Definition at line 520 of file triSurface.C.
References Foam::name(), and triSurface::scalePoints().
triSurface() [10/12]
triSurface (Istream & is) explicit
Definition at line 275 of file triSurfaceIO.C.
triSurface() [11/12]
triSurface (const Time & d) explicit
Definition at line 285 of file triSurfaceIO.C.
References Time::caseName(), Time::path(), and triSurface::triSurfInstance().
triSurface() [12/12]
triSurface (const IOobject & io, const dictionary & dict, const bool isGlobal = true)
Parameters
isGlobal resolve as a global file
Definition at line 300 of file triSurfaceIO.C.
References triSurface::checkFile(), dict, io(), word::null, and triSurface::scalePoints().
~triSurface()
~triSurface () virtual
Definition at line 537 of file triSurface.C.
Member Function Documentation
storedPoints()
pointField & storedPoints () inline protected
Definition at line 184 of file triSurface.H.
References PrimitivePatch<::Foam::List< labelledTri >, pointField >::points().
Referenced by triSurface::swap(), and triSurface::transfer().
storedFaces()
List< labelledTri > & storedFaces () inline protected
Definition at line 190 of file triSurface.H.
Referenced by triSurface::swap(), and triSurface::transfer().
ClassName()
ClassName ("triSurface")
triSurfInstance()
Foam::fileName triSurfInstance (const Time & d) static
Definition at line 66 of file triSurface.C.
References Time::caseName(), TimePaths::constant(), Foam::endl(), Foam::isFile(), Time::path(), Foam::Pout, UPtrList< T >::size(), TimeState::timeOutputValue(), and TimePaths::times().
Referenced by triSurface::triSurface().
readTypes()
Foam::wordHashSet readTypes () static
Definition at line 33 of file triSurfaceIO.C.
Referenced by triSurface::New().
writeTypes()
Foam::wordHashSet writeTypes () static
Definition at line 51 of file triSurfaceIO.C.
canReadType()
bool canReadType (const word & fileType, bool verbose = false) static
Definition at line 68 of file triSurfaceIO.C.
References surfaceFormatsCore::checkSupport().
canWriteType()
bool canWriteType (const word & fileType, bool verbose = false) static
Definition at line 80 of file triSurfaceIO.C.
References surfaceFormatsCore::checkSupport().
canRead()
bool canRead (const fileName & name, bool verbose = false) static
Definition at line 92 of file triSurfaceIO.C.
References word::ext(), word::has_ext(), and Foam::name().
Referenced by triSurfaceLoader::readDir().
relativeFilePath()
Foam::fileName relativeFilePath (const IOobject & io, const fileName & f, const bool isGlobal = true) static
Parameters
isGlobal resolve as a global file
Definition at line 105 of file triSurfaceIO.C.
References f(), io(), and surfaceFormatsCore::relativeFilePath().
Referenced by triSurfaceMesh::triSurfaceMesh(), and triSurfaceMesh::triSurfaceMesh().
checkFile() [1/2]
Foam::fileName checkFile (const IOobject & io, const bool isGlobal = true) static
Parameters
isGlobal resolve as a global file
Definition at line 116 of file triSurfaceIO.C.
References surfaceFormatsCore::checkFile(), and io().
Referenced by triSurface::triSurface().
checkFile() [2/2]
Foam::fileName checkFile (const IOobject & io, const dictionary & dict, const bool isGlobal = true) static
Parameters
isGlobal resolve as a global file
Definition at line 126 of file triSurfaceIO.C.
References surfaceFormatsCore::checkFile(), dict, and io().
findFile() [1/2]
Foam::fileName findFile (const IOobject & io, const bool isGlobal = true) static
Parameters
isGlobal resolve as a global file
Definition at line 137 of file triSurfaceIO.C.
References surfaceFormatsCore::findFile(), and io().
Referenced by distributedTriSurfaceMesh::distributedTriSurfaceMesh(), and distributedTriSurfaceMesh::distributedTriSurfaceMesh().
findFile() [2/2]
Foam::fileName findFile (const IOobject & io, const dictionary & dict, const bool isGlobal = true) static
Parameters
isGlobal resolve as a global file
Definition at line 147 of file triSurfaceIO.C.
References dict, surfaceFormatsCore::findFile(), and io().
New() [1/2]
Foam::autoPtr< Foam::triSurface > New (const fileName & name, const word & fileType) static
Definition at line 29 of file triSurfaceNew.C.
References UPtrList< T >::empty(), Foam::exit(), word::ext(), Foam::FatalError, FatalErrorInFunction, Foam::flatOutput(), found, word::lessExt(), Foam::name(), autoPtr< T >::New(), triSurface::New(), Foam::nl, and triSurface::readTypes().
Referenced by triSurface::New().
New() [2/2]
Foam::autoPtr< Foam::triSurface > New (const fileName & name) static
Definition at line 133 of file triSurfaceNew.C.
References word::ext(), word::has_ext(), word::lessExt(), Foam::name(), and Foam::New().
clearOut()
void clearOut ()
Definition at line 559 of file triSurface.C.
Referenced by triSurfaceMesh::clearOut(), triSurface::swap(), and triSurface::transfer().
clearTopology()
void clearTopology ()
Definition at line 545 of file triSurface.C.
clearPatchMeshAddr()
void clearPatchMeshAddr ()
Definition at line 553 of file triSurface.C.
swap()
void swap (triSurface & surf)
Definition at line 567 of file triSurface.C.
References triSurface::clearOut(), triSurface::patches(), triSurface::storedFaces(), triSurface::storedPoints(), and UPtrList< T >::swap().
patches() [1/2]
const geometricSurfacePatchList & patches () const inline noexcept
Definition at line 394 of file triSurface.H.
Referenced by triSurfaceTools::collapseEdges(), triSurfaceTools::greenRefine(), intersectedSurface::intersectedSurface(), triSurfaceLoader::load(), triSurfaceTools::mergePoints(), triSurface::operator=(), boundaryMesh::readTriSurface(), triSurface::swap(), triSurface::transfer(), triSurfaceMesh::triSurfaceMesh(), and triSurfaceMesh::triSurfaceMesh().
patches() [2/2]
geometricSurfacePatchList & patches () inline noexcept
Definition at line 399 of file triSurface.H.
surfFaces()
const List< labelledTri > & surfFaces () const inline noexcept
Definition at line 405 of file triSurface.H.
sortedEdgeFaces()
const Foam::labelListList & sortedEdgeFaces () const
Definition at line 583 of file triSurface.C.
edgeOwner()
const Foam::labelList & edgeOwner () const
Definition at line 594 of file triSurface.C.
Sf()
const vectorField & Sf () const inline
Definition at line 424 of file triSurface.H.
References PrimitivePatch<::Foam::List< labelledTri >, pointField >::faceAreas().
magSf()
const scalarField & magSf () const inline
Definition at line 430 of file triSurface.H.
References PrimitivePatch<::Foam::List< labelledTri >, pointField >::magFaceAreas().
Cf()
const vectorField & Cf () const inline
Definition at line 436 of file triSurface.H.
References PrimitivePatch<::Foam::List< labelledTri >, pointField >::faceCentres().
sortedZones()
Foam::List< Foam::surfZone > sortedZones (labelList & faceMap) const
Definition at line 702 of file triSurface.C.
References Foam::faceMap(), forAll, patches, and UPtrList< T >::size().
triFaceFaces()
void triFaceFaces (List< face > & plainFaceList) const
Definition at line 716 of file triSurface.C.
References forAll, and PtrList< T >::setSize().
movePoints()
void movePoints (const pointField & pts) virtual
Reimplemented in triSurfaceMesh.
Definition at line 605 of file triSurface.C.
References pts.
Referenced by triSurfaceMesh::movePoints().
swapPoints()
void swapPoints (pointField & pts) virtual
Definition at line 618 of file triSurface.C.
References pts.
scalePoints()
void scalePoints (const scalar scaleFactor) virtual
Definition at line 631 of file triSurface.C.
References Foam::equal().
Referenced by triSurface::triSurface(), and triSurface::triSurface().
checkTriangles()
void checkTriangles (const bool verbose)
Definition at line 175 of file triSurface.C.
References bitSet::all(), Foam::endl(), Foam::exit(), f(), Foam::FatalError, FatalErrorInFunction, forAll, n, points, Foam::printTriangle(), UPtrList< T >::size(), bitSet::unset(), Foam::Warning, and WarningInFunction.
checkEdges()
void checkEdges (const bool verbose)
Definition at line 294 of file triSurface.C.
References UPtrList< T >::empty(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, UPtrList< T >::size(), and WarningInFunction.
cleanup()
void cleanup (const bool verbose)
Definition at line 648 of file triSurface.C.
compactPoints()
void compactPoints (labelList & pointMap = const_cast<labelList&>(labelList::null()))
Definition at line 662 of file triSurface.C.
References PtrList< T >::append(), f(), Foam::notNull(), points, UPtrList< T >::size(), and List< T >::transfer().
markZone()
void markZone (const boolList & borderEdge, const label facei, const label currentZone, labelList & faceZone) const
Definition at line 729 of file triSurface.C.
References Foam::abort(), PtrList< T >::append(), UPtrList< T >::empty(), Foam::FatalError, FatalErrorInFunction, UPtrList< T >::size(), and PtrList< T >::transfer().
markZones()
Foam::label markZones (const boolList & borderEdge, labelList & faceZone) const
Definition at line 788 of file triSurface.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, List< T >::setSize(), and UPtrList< T >::size().
subsetMeshMap()
template<class BoolListType > void subsetMeshMap (const BoolListType & include, labelList & pointMap, labelList & faceMap) const inline
Definition at line 507 of file triSurface.H.
References Foam::faceMap(), and PatchTools::subsetMap().
subsetMesh() [1/5]
Foam::triSurface subsetMesh (const UList< bool > & include, labelList & pointMap, labelList & faceMap) const
Definition at line 871 of file triSurface.C.
References Foam::faceMap().
subsetMesh() [2/5]
Foam::triSurface subsetMesh (const bitSet & include, labelList & pointMap, labelList & faceMap) const
Definition at line 884 of file triSurface.C.
References Foam::faceMap().
subsetMesh() [3/5]
Foam::triSurface subsetMesh (const UList< bool > & include) const
Definition at line 897 of file triSurface.C.
References Foam::faceMap().
subsetMesh() [4/5]
Foam::triSurface subsetMesh (const bitSet & include) const
Definition at line 905 of file triSurface.C.
References Foam::faceMap().
subsetMesh() [5/5]
Foam::triSurface subsetMesh (const wordRes & includeNames, const wordRes & excludeNames = wordRes()) const
Definition at line 913 of file triSurface.C.
References Foam::stringListOps::findMatching(), forAll, bitSet::set(), and UPtrList< T >::test().
swapFaces()
void swapFaces (List< labelledTri > & faceLst)
Definition at line 946 of file triSurface.C.
transfer() [1/2]
void transfer (triSurface & surf)
Definition at line 954 of file triSurface.C.
References triSurface::clearOut(), triSurface::patches(), triSurface::storedFaces(), and triSurface::storedPoints().
Referenced by triSurface::triSurface(), triSurfaceMesh::triSurfaceMesh(), and triSurfaceMesh::triSurfaceMesh().
transfer() [2/2]
void transfer (MeshedSurface< labelledTri > & surf)
Definition at line 966 of file triSurface.C.
References PtrList< T >::clear(), patches, pts, and s().
write() [1/4]
void write (Ostream & os) const
Definition at line 331 of file triSurfaceIO.C.
References os().
Referenced by triSurfaceMesh::writeObject(), distributedTriSurfaceMesh::writeObject(), and boundaryMesh::writeTriSurface().
write() [2/4]
void write (const fileName & name, const bool sortByRegion = false) const
Definition at line 321 of file triSurfaceIO.C.
References word::ext(), Foam::name(), and write().
write() [3/4]
void write (const fileName & filename, const word & fileType, const bool sortByRegion = false) const
Definition at line 201 of file triSurfaceIO.C.
References UPtrList< T >::empty(), Foam::exit(), word::ext(), Foam::faceMap(), Foam::FatalError, FatalErrorInFunction, Foam::flatOutput(), Foam::name(), Foam::nl, os(), points, and write().
write() [4/4]
void write (const Time & d) const
Definition at line 337 of file triSurfaceIO.C.
References Time::caseName(), os(), and Time::path().
writeStats()
void writeStats (Ostream & os) const
Definition at line 348 of file triSurfaceIO.C.
References boundBox::add(), UPtrList< T >::count(), Foam::endl(), f(), Foam::nl, os(), points, PtrList< T >::set(), and UPtrList< T >::size().
operator=() [1/3]
void operator= (const triSurface & surf)
Definition at line 992 of file triSurface.C.
References triSurface::patches(), and PrimitivePatch< FaceList, PointField >::points().
Referenced by booleanSurface::booleanSurface(), distributedTriSurfaceMesh::distribute(), and intersectedSurface::intersectedSurface().
operator=() [2/3]
void operator= (triSurface && surf)
Definition at line 1002 of file triSurface.C.
operator=() [3/3]
void operator= (MeshedSurface< labelledTri > && surf)
Definition at line 1008 of file triSurface.C.
Friends And Related Symbol Documentation
operator>>
Istream & operator>> (Istream & is, triSurface & s) friend
operator<<
Ostream & operator<< (Ostream & os, const triSurface & s) friend
The documentation for this class was generated from the following files:
src/surfMesh/triSurface/triSurface.H
src/surfMesh/surfaceFormats/gts/triSurfaceGTSformat.C
src/surfMesh/surfaceFormats/stl/triSurfaceSTLformat.C
src/surfMesh/triSurface/triSurface.C
src/surfMesh/triSurface/triSurfaceAddressing.C
src/surfMesh/triSurface/triSurfaceIO.C
src/surfMesh/triSurface/triSurfaceNew.C
src/surfMesh/triSurface/triSurfaceStitch.C