OpenFOAM: vtkWrite Class Reference
vtkWrite Class Reference
FunctionObjects » Utility function objects
Writes fields in VTK (xml or legacy) format. Writes cell-values or point-interpolated values for volFields.
#include <vtkWrite.H>
Public Member Functions
TypeName ("vtkWrite")
vtkWrite (const word &name, const Time &runTime, const dictionary &dict)
virtual ~vtkWrite ()=default
virtual bool read (const dictionary &dict)
virtual bool execute ()
virtual bool write ()
virtual bool end ()
virtual void updateMesh (const mapPolyMesh &mpm)
virtual void movePoints (const polyMesh &mesh)
template<class GeoField >
Foam::label writeVolFieldsImpl (autoPtr< vtk::internalWriter > &internalWriter, UPtrList< vtk::patchWriter > &patchWriters, const fvMeshSubset &proxy, const wordHashSet &candidateNames) const
template<class GeoField >
Foam::label writeVolFieldsImpl (autoPtr< vtk::internalWriter > &internalWriter, const autoPtr< volPointInterpolation > &pInterp, UPtrList< vtk::patchWriter > &patchWriters, const UPtrList< PrimitivePatchInterpolation< primitivePatch > > &patchInterps, const fvMeshSubset &proxy, const wordHashSet &candidateNames) const
Public Member Functions inherited from timeFunctionObject
timeFunctionObject (const word &name, const Time &runTime)
virtual ~timeFunctionObject ()=default
const Time & time () const
objectRegistry & storedObjects ()
const objectRegistry & storedObjects () const
Public Member Functions inherited from functionObject
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name, const bool withNamePrefix=defaultUseNamePrefix)
autoPtr< functionObject > clone () const
virtual ~functionObject ()=default
virtual const word & type () const =0
const word & name () const noexcept
bool useNamePrefix () const noexcept
bool useNamePrefix (bool on) noexcept
virtual bool execute (const label subIndex)
virtual bool adjustTimeStep ()
virtual bool filesModified () const
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &runTime, const dictionary &dict)
Public Attributes inherited from functionObject
bool log
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
static bool defaultUseNamePrefix
static word outputPrefix
Protected Member Functions inherited from timeFunctionObject
void clearOutputObjects (const wordList &objNames)
timeFunctionObject (const timeFunctionObject &)=delete
void operator= (const timeFunctionObject &)=delete
Protected Member Functions inherited from functionObject
word scopedName (const word &name) const
Protected Attributes inherited from timeFunctionObject
const Time & time_
Detailed Description
Writes fields in VTK (xml or legacy) format. Writes cell-values or point-interpolated values for volFields.
Example of function object specification:
vtkWrite1
{
    type            vtkWrite;
    libs            (utilityFunctionObjects);
    writeControl    writeTime;
    writeInterval   1;
    format          binary;
    legacy          false;
    decompose       false;
    ...
    fields          (U p);
    // excludeFields  ("force.*");
    selection
    {
        box
        {
            action  use;
            source  box;
            box     (-0.1 -0.01 -0.1) (0.1 0.30 0.1);
        }
        dome
        {
            action  add;
            source  sphere;
            origin  (-0.1 -0.01 -0.1);
            radius  0.25;
        }
        centre
        {
            action  subtract;
            source  sphere;
            origin  (-0.1 -0.01 -0.1);
            radius  0.1;
        }
        blob
        {
            action  add;
            source  surface;
            surface triSurfaceMesh;
            name    blob.stl;
        }
    }
}
Basic Usage
Property Description Required Default
type Type name: vtkWrite yes
fields Select fields to output (wordRe list) yes
excludeFields Exclude fields from output (wordRe list) no
boundary Convert boundary fields no true
internal Convert internal fields no true
single Combine patches into a single boundary no false
interpolate Interpolate for point values no false
Output Options
Property Description Required Default
format ascii or binary format no binary
legacy Legacy VTK output no false
precision Write precision in ascii no same as IOstream
directory The output directory name no postProcessing/NAME
width Padding width for file name no 8
decompose Decompose polyhedral cells no false
writeIds Write cell,patch,proc id fields no false
Output Selection
Property Description Required Default
region Name for a single region no region0
regions List of regions (wordRe list) no
patches Limit to listed patches (wordRe list) no
excludePatches Exclude specified patches no
selection Cell selection (topoSet actions) no empty dict
Note
The region of interest is defined by the selection dictionary as a set of actions (use,add,subtract,subset,invert). Omitting the selection dictionary is the same as specifying the conversion of all cells (in the selected regions). Omitting the patches entry is the same as specifying the conversion of all patches.
See also
Foam::functionObjects::ensightWrite Foam::functionObjects::fvMeshFunctionObject Foam::functionObjects::timeControl Foam::cellBitSet::select
Source files
vtkWrite.H
vtkWrite.C
vtkWriteImpl.C
Definition at line 264 of file vtkWrite.H.
Constructor & Destructor Documentation
vtkWrite()
vtkWrite (const word & name, const Time & runTime, const dictionary & dict)
Definition at line 122 of file vtkWrite.C.
References dict, and vtkWrite::read().
~vtkWrite()
virtual ~vtkWrite () virtual default
Member Function Documentation
TypeName()
TypeName ("vtkWrite")
read()
bool read (const dictionary & dict) virtual
Reimplemented from functionObject.
Definition at line 168 of file vtkWrite.C.
References IOstreamOption::ASCII, IOstreamOption::BINARY, PtrList< T >::clear(), IOstream::defaultPrecision(), dict, IOstreamOption::formatEnum(), Foam::vtk::INLINE_BASE64, Foam::name(), functionObject::outputPrefix, and functionObject::read().
Referenced by vtkWrite::vtkWrite().
execute()
bool execute () virtual
Implements functionObject.
Definition at line 249 of file vtkWrite.C.
write()
bool write () virtual
Implements functionObject.
Definition at line 255 of file vtkWrite.C.
References PtrList< T >::append(), seriesWriter::base(), objectRegistry::count(), UPtrList< T >::empty(), Foam::endl(), Foam::vtk::legacy::fileExtension, forAll, Foam::Info, internalWriter, k, UPstream::master(), Foam::name(), objectRegistry::names(), nDimFields, autoPtr< T >::New(), Foam::nl, nPatchWriters, nVolFields, outputName(), UPstream::parRun(), patches, patchId(), patchIds, patchInterps, patchWriters, pInterp, pp(), word::printf(), regionDir, polyMesh::regionName(), regionName, PtrList< T >::resize(), PtrList< T >::set(), UPtrList< T >::size(), update(), Foam::fieldTypes::volume, vtmBoundaries, vtmOutputBase(), vtmWriter, WarningInFunction, Foam::writeAllVolFields(), and writer().
end()
bool end () virtual
Reimplemented from functionObject.
Definition at line 785 of file vtkWrite.C.
References PtrList< T >::clear().
updateMesh()
void updateMesh (const mapPolyMesh & mpm) virtual
Reimplemented from functionObject.
Definition at line 189 of file vtkWriteUpdate.C.
References polyMesh::TOPO_CHANGE.
movePoints()
void movePoints (const polyMesh & mesh) virtual
Reimplemented from functionObject.
Definition at line 195 of file vtkWriteUpdate.C.
References polyMesh::POINTS_MOVED, and polyMesh::UNCHANGED.
writeVolFieldsImpl() [1/2]
template<class GeoField > Foam::label writeVolFieldsImpl (autoPtr< vtk::internalWriter > & internalWriter, UPtrList< vtk::patchWriter > & patchWriters, const fvMeshSubset & proxy, const wordHashSet & candidateNames) const
Definition at line 24 of file vtkWriteImpl.C.
References Foam::endl(), field(), internalWriter, fvMeshSubsetProxy::interpolate(), Log, patchWriters, objectRegistry::sorted(), and writer().
writeVolFieldsImpl() [2/2]
template<class GeoField > Foam::label writeVolFieldsImpl (autoPtr< vtk::internalWriter > & internalWriter, const autoPtr< volPointInterpolation > & pInterp, UPtrList< vtk::patchWriter > & patchWriters, const UPtrList< PrimitivePatchInterpolation< primitivePatch > > & patchInterps, const fvMeshSubset & proxy, const wordHashSet & candidateNames) const
Definition at line 89 of file vtkWriteImpl.C.
References Foam::endl(), field(), internalWriter, fvMeshSubsetProxy::interpolate(), Log, patchInterps, patchWriters, pInterp, PtrList< T >::set(), UPtrList< T >::size(), objectRegistry::sorted(), and writer().
The documentation for this class was generated from the following files:
src/functionObjects/utilities/vtkWrite/vtkWrite.H
src/functionObjects/utilities/vtkWrite/vtkWrite.C
src/functionObjects/utilities/vtkWrite/vtkWriteImpl.C
src/functionObjects/utilities/vtkWrite/vtkWriteUpdate.C