OpenFOAM: ReactionList< ThermoType > Class Template Reference
ReactionList< ThermoType > Class Template Reference
List of templated reactions.
#include <ReactionList.H>
Public Member Functions
ReactionList (const speciesTable &species, const ReactionTable< ThermoType > &thermoDatabase)
ReactionList (const speciesTable &species, const ReactionTable< ThermoType > &thermoDatabase, const dictionary &dict)
ReactionList (const ReactionList< ThermoType > &reactions)
~ReactionList ()=default
bool readReactionDict ()
void write (Ostream &os) const
Public Member Functions inherited from LPtrList< LListBase, T >
LPtrList ()=default
LPtrList (T *item)
LPtrList (const LPtrList &lst)
LPtrList (LPtrList &&lst)
template<class INew >
LPtrList (Istream &is, const INew &inew)
LPtrList (Istream &is)
~LPtrList ()
T & front ()
const T & front () const
T & back ()
const T & back () const
void pop_front (label n=1)
void clear ()
void transfer (LPtrList< LListBase, T > &lst)
void operator= (const LPtrList< LListBase, T > &lst)
void operator= (LPtrList< LListBase, T > &&lst)
iterator begin ()
const_iterator cbegin () const
reverse_iterator rbegin ()
const_reverse_iterator crbegin () const
const_iterator begin () const
const_reverse_iterator rbegin () const
const iterator & end ()
const const_iterator & cend () const
const reverse_iterator & rend ()
const const_reverse_iterator & crend () const
const const_iterator & end () const
const const_reverse_iterator & rend () const
T & first ()
const T & first () const
T & last ()
const T & last () const
Public Member Functions inherited from LList< LListBase, T * >
LList ()=default
LList (const T * &elem)
LList (T * &&elem)
LList (Istream &is)
LList (const LList< LListBase, T * > &lst)
LList (LList< LListBase, T * > &&lst)
LList (std::initializer_list< T * > lst)
~LList ()
reference front ()
const_reference front () const
reference back ()
const_reference back () const
void push_front (const T * &elem)
void push_front (T * &&elem)
void push_back (const T * &elem)
void push_back (T * &&elem)
void clear ()
void pop_front (label n=1)
T * removeHead ()
T * remove (link *item)
T * remove (iterator &iter)
void transfer (LList< LListBase, T * > &lst)
void operator= (const LList< LListBase, T * > &lst)
void operator= (LList< LListBase, T * > &&lst)
void operator= (std::initializer_list< T * > lst)
Istream & readList (Istream &is)
Ostream & writeList (Ostream &os, const label shortLen=0) const
iterator begin ()
const_iterator begin () const
const_iterator cbegin () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
const_reverse_iterator crbegin () const
const iterator & end ()
const const_iterator & end () const
const const_iterator & cend () const
const reverse_iterator & rend ()
const const_reverse_iterator & rend () const
const const_reverse_iterator & crend () const
reference first ()
const_reference first () const
reference last ()
const_reference last () const
void prepend (const T * &elem)
void prepend (T * &&elem)
void append (const T * &elem)
void append (T * &&elem)
void insert (const T * &elem)
void insert (T * &&elem)
Additional Inherited Members
Public Types inherited from LPtrList< LListBase, T >
typedef T * pointer
typedef const T * const_pointer
typedef T & reference
typedef const T & const_reference
using base_iterator = typename LListBase::iterator
using const_base_iterator = typename LListBase::const_iterator
typedef LList< LListBase, T * > parent_type
Public Types inherited from LList< LListBase, T * >
typedef T * value_type
typedef T * * pointer
typedef const T * * const_pointer
typedef T * & reference
typedef const T * & const_reference
typedef label size_type
typedef label difference_type
using base_iterator = typename LListBase::iterator
using const_base_iterator = typename LListBase::const_iterator
Detailed Description
template<class ThermoType>
class Foam::ReactionList< ThermoType >
List of templated reactions.
Source files
ReactionList.H
ReactionList.C
Definition at line 52 of file ReactionList.H.
Constructor & Destructor Documentation
ReactionList() [1/3]
template<class ThermoType > ReactionList (const speciesTable & species, const ReactionTable< ThermoType > & thermoDatabase)
Definition at line 27 of file ReactionList.C.
ReactionList() [2/3]
template<class ThermoType > ReactionList (const speciesTable & species, const ReactionTable< ThermoType > & thermoDatabase, const dictionary & dict)
Definition at line 41 of file ReactionList.C.
References ReactionList< ThermoType >::readReactionDict().
ReactionList() [3/3]
template<class ThermoType > ReactionList (const ReactionList< ThermoType > & reactions)
~ReactionList()
template<class ThermoType > ~ReactionList () default
Member Function Documentation
readReactionDict()
template<class ThermoType > bool readReactionDict ()
Definition at line 70 of file ReactionList.C.
References append().
Referenced by ReactionList< ThermoType >::ReactionList().
write()
template<class ThermoType > void write (Ostream & os) const
Definition at line 90 of file ReactionList.C.
References Ostream::beginBlock(), Ostream::endBlock(), os(), Ostream::write(), and Ostream::writeEntry().
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/reaction/Reactions/ReactionList/ReactionList.H
src/thermophysicalModels/specie/reaction/Reactions/ReactionList/ReactionList.C