OpenFOAM: faPatchFieldBase Class Reference
faPatchFieldBase Class Reference
#include <faPatchField.H>
Public Member Functions
TypeName ("faPatchField")
faPatchFieldBase (const faPatch &p)
faPatchFieldBase (const faPatch &p, const word &patchType)
faPatchFieldBase (const faPatch &p, const dictionary &dict)
faPatchFieldBase (const faPatchFieldBase &rhs, const faPatch &p)
faPatchFieldBase (const faPatchFieldBase &rhs)
virtual ~faPatchFieldBase ()=default
virtual bool fixesValue () const
virtual bool coupled () const
const objectRegistry & db () const
const faPatch & patch () const noexcept
const word & patchType () const noexcept
word & patchType () noexcept
bool updated () const noexcept
bool manipulatedMatrix () const noexcept
void checkPatch (const faPatchFieldBase &rhs) const
Static Public Member Functions
static const word & emptyType () noexcept
static const word & calculatedType () noexcept
static const word & extrapolatedCalculatedType () noexcept
static const word & zeroGradientType () noexcept
Static Public Attributes
static int disallowGenericPatchField
Protected Member Functions
virtual void readDict (const dictionary &dict)
void setUpdated (bool state) noexcept
void setManipulated (bool state) noexcept
Detailed Description
Definition at line 77 of file faPatchField.H.
Constructor & Destructor Documentation
faPatchFieldBase() [1/5]
faPatchFieldBase (const faPatch & p) explicit
Definition at line 41 of file faPatchFieldBase.C.
faPatchFieldBase() [2/5]
faPatchFieldBase (const faPatch & p, const word & patchType) explicit
Definition at line 49 of file faPatchFieldBase.C.
References faPatchFieldBase::patchType().
faPatchFieldBase() [3/5]
faPatchFieldBase (const faPatch & p, const dictionary & dict)
Definition at line 61 of file faPatchFieldBase.C.
References dict, and faPatchFieldBase::readDict().
faPatchFieldBase() [4/5]
faPatchFieldBase (const faPatchFieldBase & rhs, const faPatch & p)
Definition at line 73 of file faPatchFieldBase.C.
faPatchFieldBase() [5/5]
faPatchFieldBase (const faPatchFieldBase & rhs)
Definition at line 85 of file faPatchFieldBase.C.
~faPatchFieldBase()
virtual ~faPatchFieldBase () virtual default
Member Function Documentation
readDict()
void readDict (const dictionary & dict) protected virtual
Definition at line 95 of file faPatchFieldBase.C.
References dict, keyType::LITERAL, and dictionary::readIfPresent().
Referenced by faPatchFieldBase::faPatchFieldBase(), outletInletFaPatchField< Type >::outletInletFaPatchField(), slicedFaPatchField< Type >::slicedFaPatchField(), and uniformMixedFaPatchField< Type >::uniformMixedFaPatchField().
setUpdated()
void setUpdated (bool state) inline protected noexcept
Definition at line 104 of file faPatchField.H.
Referenced by faPatchField< Type >::evaluate(), and faPatchField< Type >::updateCoeffs().
setManipulated()
void setManipulated (bool state) inline protected noexcept
Definition at line 110 of file faPatchField.H.
TypeName()
TypeName ("faPatchField")
emptyType()
static const word & emptyType () inline static noexcept
Definition at line 148 of file faPatchField.H.
References Foam::fieldTypes::emptyType.
calculatedType()
static const word & calculatedType () inline static noexcept
Definition at line 154 of file faPatchField.H.
References Foam::fieldTypes::calculatedType.
Referenced by EulerFaD2dt2Scheme< Type >::facD2dt2(), backwardFaDdtScheme< Type >::facDdt(), EulerFaDdtScheme< Type >::facDdt(), boundedBackwardFaDdtScheme::facDdt(), and faMeshSubset::interpolate().
extrapolatedCalculatedType()
static const word & extrapolatedCalculatedType () inline static noexcept
Definition at line 161 of file faPatchField.H.
References Foam::fieldTypes::extrapolatedCalculatedType.
Referenced by faMatrix< Type >::A(), and faMatrix< Type >::H().
zeroGradientType()
static const word & zeroGradientType () inline static noexcept
Definition at line 167 of file faPatchField.H.
References Foam::fieldTypes::zeroGradientType.
Referenced by leastSquaresFaGrad< Type >::calcGrad(), thermalShell::Cp(), Foam::fac::edgeIntegrate(), Foam::fac::edgeSum(), thermalShell::kappa(), KirchhoffShell::rho(), thermalShell::rho(), and sensitivitySurface::smoothSensitivities().
fixesValue()
virtual bool fixesValue () const inline virtual
Reimplemented in calculatedFaPatchField< Type >, fixedValueFaPatchField< Type >, mixedFaPatchField< Type >, slicedFaPatchField< Type >, and fixedValueOutflowFaPatchField< Type >.
Definition at line 180 of file faPatchField.H.
coupled()
virtual bool coupled () const inline virtual
Reimplemented in coupledFaPatchField< Type >, and processorFaPatchField< Type >.
Definition at line 186 of file faPatchField.H.
db()
const Foam::objectRegistry & db () const
Definition at line 101 of file faPatchFieldBase.C.
patch()
const faPatch & patch () const inline noexcept
Definition at line 198 of file faPatchField.H.
Referenced by cyclicFaPatchField< Type >::cyclicFaPatchField(), faPatchField< Type >::extrapolateInternal(), genericFaPatchField< Type >::genericFaPatchField(), genericFaPatchField< Type >::genericFaPatchField(), processorFaPatchField< Type >::processorFaPatchField(), fixedGradientFaPatchField< Type >::readGradientEntry(), mixedFaPatchField< Type >::readMixedEntries(), faPatchField< Type >::readValueEntry(), symmetryFaPatchField< Type >::symmetryFaPatchField(), uniformMixedFaPatchField< Type >::uniformMixedFaPatchField(), wedgeFaPatchField< Type >::wedgeFaPatchField(), and wedgeFaPatchField< Type >::wedgeFaPatchField().
patchType() [1/2]
const word & patchType () const inline noexcept
Definition at line 204 of file faPatchField.H.
Referenced by faPatchFieldBase::faPatchFieldBase().
patchType() [2/2]
word & patchType () inline noexcept
Definition at line 210 of file faPatchField.H.
updated()
bool updated () const inline noexcept
Definition at line 219 of file faPatchField.H.
manipulatedMatrix()
bool manipulatedMatrix () const inline noexcept
Definition at line 226 of file faPatchField.H.
checkPatch()
void checkPatch (const faPatchFieldBase & rhs) const
Definition at line 107 of file faPatchFieldBase.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Referenced by faPatchField< Type >::check(), faPatchField< Type >::operator*=(), faPatchField< Type >::operator+=(), faPatchField< Type >::operator-=(), faPatchField< Type >::operator/=(), and faPatchField< Type >::operator=().
Member Data Documentation
disallowGenericPatchField
int disallowGenericPatchField static
Definition at line 117 of file faPatchField.H.
Referenced by faPatchField< Type >::New().
The documentation for this class was generated from the following files:
src/finiteArea/fields/faPatchFields/faPatchField/faPatchField.H
src/finiteArea/fields/faPatchFields/faPatchField/faPatchFieldBase.C