OpenFOAM: linear Class Reference
linear Class Reference
linear compressibility model.
#include <linear.H>
Public Member Functions
TypeName ("linear")
linear (const dictionary &compressibilityProperties, const volScalarField &gamma, const word &psiName="psi")
~linear ()
void correct ()
bool read (const dictionary &compressibilityProperties)
Public Member Functions inherited from barotropicCompressibilityModel
TypeName ("barotropicCompressibilityModel")
declareRunTimeSelectionTable (autoPtr, barotropicCompressibilityModel, dictionary,(const dictionary &compressibilityProperties, const volScalarField &gamma, const word &psiName),(compressibilityProperties, gamma, psiName))
barotropicCompressibilityModel (const dictionary &compressibilityProperties, const volScalarField &gamma, const word &psiName="psi")
virtual ~barotropicCompressibilityModel ()=default
const dictionary & compressibilityProperties () const
const volScalarField & psi () const
Additional Inherited Members
Static Public Member Functions inherited from barotropicCompressibilityModel
static autoPtr< barotropicCompressibilityModel > New (const dictionary &compressibilityProperties, const volScalarField &gamma, const word &psiName="psi")
Protected Member Functions inherited from barotropicCompressibilityModel
barotropicCompressibilityModel (const barotropicCompressibilityModel &)=delete
void operator= (const barotropicCompressibilityModel &)=delete
Protected Attributes inherited from barotropicCompressibilityModel
dictionary compressibilityProperties_
volScalarField psi_
const volScalarField & gamma_
Detailed Description
linear compressibility model.
Source files
linear.H
linear.C
Definition at line 49 of file linear.H.
Constructor & Destructor Documentation
linear()
linear (const dictionary & compressibilityProperties, const volScalarField & gamma, const word & psiName = "psi")
Definition at line 42 of file linear.C.
References linear::correct(), Foam::dimCompressibility, GeometricField< Type, PatchField, GeoMesh >::oldTime(), and barotropicCompressibilityModel::psi_.
~linear()
~linear () inline
Definition at line 77 of file linear.H.
Member Function Documentation
TypeName()
TypeName ("linear")
correct()
void correct () virtual
Implements barotropicCompressibilityModel.
Definition at line 70 of file linear.C.
Referenced by linear::linear().
read()
bool read (const dictionary & compressibilityProperties) virtual
Implements barotropicCompressibilityModel.
Definition at line 76 of file linear.C.
References barotropicCompressibilityModel::read().
The documentation for this class was generated from the following files:
src/thermophysicalModels/barotropicCompressibilityModel/linear/linear.H
src/thermophysicalModels/barotropicCompressibilityModel/linear/linear.C