OpenFOAM: polyAddFace Class Reference
polyAddFace Class Reference
A face addition data class. A face can be inflated either from a point or from another face and can either be in internal or a boundary face.
#include <polyAddFace.H>
Public Member Functions
TypeName ("addFace")
polyAddFace ()
polyAddFace (const face &f, const label owner, const label neighbour, const label masterPointID, const label masterEdgeID, const label masterFaceID, const bool flipFaceFlux, const label patchID, const label zoneID, const bool zoneFlip)
virtual autoPtr< topoAction > clone () const
const face & newFace () const
label owner () const
label neighbour () const
bool isPointMaster () const
bool isEdgeMaster () const
bool isFaceMaster () const
bool appended () const
label masterPointID () const
label masterEdgeID () const
label masterFaceID () const
bool flipFaceFlux () const
bool isInPatch () const
label patchID () const
bool isInZone () const
bool onlyInZone () const
label zoneID () const
label zoneFlip () const
Public Member Functions inherited from topoAction
TypeName ("topoAction")
topoAction ()
virtual ~topoAction ()=default
Detailed Description
A face addition data class. A face can be inflated either from a point or from another face and can either be in internal or a boundary face.
Definition at line 47 of file polyAddFace.H.
Constructor & Destructor Documentation
polyAddFace() [1/2]
polyAddFace () inline
Definition at line 95 of file polyAddFace.H.
Referenced by polyAddFace::clone().
polyAddFace() [2/2]
polyAddFace (const face & f, const label owner, const label neighbour, const label masterPointID, const label masterEdgeID, const label masterFaceID, const bool flipFaceFlux, const label patchID, const label zoneID, const bool zoneFlip) inline
Definition at line 111 of file polyAddFace.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, Foam::min(), polyAddFace::patchID(), UList< T >::size(), polyAddFace::zoneFlip(), and polyAddFace::zoneID().
Member Function Documentation
TypeName()
TypeName ("addFace")
clone()
virtual autoPtr< topoAction > clone () const inline virtual
Implements topoAction.
Definition at line 223 of file polyAddFace.H.
References polyAddFace::polyAddFace().
newFace()
const face & newFace () const inline
Definition at line 234 of file polyAddFace.H.
owner()
label owner () const inline
Definition at line 240 of file polyAddFace.H.
neighbour()
label neighbour () const inline
Definition at line 246 of file polyAddFace.H.
isPointMaster()
bool isPointMaster () const inline
Definition at line 252 of file polyAddFace.H.
Referenced by polyAddFace::appended().
isEdgeMaster()
bool isEdgeMaster () const inline
Definition at line 258 of file polyAddFace.H.
Referenced by polyAddFace::appended().
isFaceMaster()
bool isFaceMaster () const inline
Definition at line 264 of file polyAddFace.H.
Referenced by polyAddFace::appended().
appended()
bool appended () const inline
Definition at line 270 of file polyAddFace.H.
References polyAddFace::isEdgeMaster(), polyAddFace::isFaceMaster(), and polyAddFace::isPointMaster().
masterPointID()
label masterPointID () const inline
Definition at line 276 of file polyAddFace.H.
masterEdgeID()
label masterEdgeID () const inline
Definition at line 282 of file polyAddFace.H.
masterFaceID()
label masterFaceID () const inline
Definition at line 288 of file polyAddFace.H.
flipFaceFlux()
bool flipFaceFlux () const inline
Definition at line 294 of file polyAddFace.H.
isInPatch()
bool isInPatch () const inline
Definition at line 300 of file polyAddFace.H.
patchID()
label patchID () const inline
Definition at line 306 of file polyAddFace.H.
Referenced by polyAddFace::polyAddFace().
isInZone()
bool isInZone () const inline
Definition at line 312 of file polyAddFace.H.
onlyInZone()
bool onlyInZone () const inline
Definition at line 318 of file polyAddFace.H.
zoneID()
label zoneID () const inline
Definition at line 324 of file polyAddFace.H.
Referenced by polyAddFace::polyAddFace().
zoneFlip()
label zoneFlip () const inline
Definition at line 330 of file polyAddFace.H.
Referenced by polyAddFace::polyAddFace().
The documentation for this class was generated from the following file:
src/meshTools/polyTopoChange/addObject/polyAddFace.H