OpenFOAM: blockVertex Class Reference
blockVertex Class Reference abstract
Define a block vertex.
#include <blockVertex.H>
Classes
class iNew
Public Member Functions
TypeName ("blockVertex")
declareRunTimeSelectionTable (autoPtr, blockVertex, Istream,(const dictionary &dict, const label index, const searchableSurfaces &geometry, Istream &is),(dict, index, geometry, is))
blockVertex () noexcept=default
virtual autoPtr< blockVertex > clone () const
virtual ~blockVertex ()=default
virtual operator point () const =0
Static Public Member Functions
static autoPtr< blockVertex > New (const dictionary &dict, const label index, const searchableSurfaces &geometry, Istream &)
static label read (Istream &, const dictionary &)
static void write (Ostream &, const label, const dictionary &)
Detailed Description
Define a block vertex.
Source files
blockVertex.H
blockVertex.C
Definition at line 47 of file blockVertex.H.
Constructor & Destructor Documentation
blockVertex()
blockVertex () default noexcept
~blockVertex()
virtual ~blockVertex () virtual default
Member Function Documentation
TypeName()
TypeName ("blockVertex")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , blockVertex , Istream , (const dictionary &dict, const label index, const searchableSurfaces &geometry, Istream &is) , (dict, index, geometry, is))
clone()
Foam::autoPtr< Foam::blockVertex > clone () const virtual
Definition at line 37 of file blockVertex.C.
References NotImplemented.
New()
Foam::autoPtr< Foam::blockVertex > New (const dictionary & dict, const label index, const searchableSurfaces & geometry, Istream & is) static
Definition at line 44 of file blockVertex.C.
References Foam::abort(), token::BEGIN_LIST, DebugInFunction, dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, FatalIOErrorInLookup, and Foam::nl.
Referenced by blockVertex::iNew::operator()().
operator point()
virtual operator point () const pure virtual
Implemented in namedVertex, pointVertex, and projectVertex.
read()
Foam::label read (Istream & is, const dictionary & dict) static
Definition at line 95 of file blockVertex.C.
References dict, dictionary::findDict(), Foam::blockMeshTools::read(), and Foam::readLabel().
write()
void write (Ostream & os, const label val, const dictionary & d) static
Definition at line 110 of file blockVertex.C.
References dictionary::findDict(), os(), and Foam::blockMeshTools::write().
Referenced by blockFace::write(), and blockEdge::write().
The documentation for this class was generated from the following files:
src/mesh/blockMesh/blockVertices/blockVertex/blockVertex.H
src/mesh/blockMesh/blockVertices/blockVertex/blockVertex.C