OpenFOAM: movingWallVelocityFvPatchVectorField Class Reference
movingWallVelocityFvPatchVectorField Class Reference
Boundary conditions » Wall
This boundary condition provides a velocity condition for cases with moving walls.
#include <movingWallVelocityFvPatchVectorField.H>
Public Member Functions
TypeName ("movingWallVelocity")
movingWallVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
movingWallVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
movingWallVelocityFvPatchVectorField (const movingWallVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
movingWallVelocityFvPatchVectorField (const movingWallVelocityFvPatchVectorField &)
virtual tmp< fvPatchVectorField > clone () const
movingWallVelocityFvPatchVectorField (const movingWallVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
tmp< vectorField > Uwall () const
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
This boundary condition provides a velocity condition for cases with moving walls.
Usage
Example of the boundary condition specification:
<patchName>
{
    type            movingWallVelocity;
    value           uniform (0 0 0);    // Initial value
}
See also
Foam::fixedValueFvPatchVectorField Foam::MRFZone
Source files
movingWallVelocityFvPatchVectorField.H
movingWallVelocityFvPatchVectorField.C
Definition at line 65 of file movingWallVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
movingWallVelocityFvPatchVectorField() [1/5]
movingWallVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Definition at line 30 of file movingWallVelocityFvPatchVectorField.C.
movingWallVelocityFvPatchVectorField() [2/5]
movingWallVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Definition at line 41 of file movingWallVelocityFvPatchVectorField.C.
movingWallVelocityFvPatchVectorField() [3/5]
movingWallVelocityFvPatchVectorField (const movingWallVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 53 of file movingWallVelocityFvPatchVectorField.C.
movingWallVelocityFvPatchVectorField() [4/5]
movingWallVelocityFvPatchVectorField (const movingWallVelocityFvPatchVectorField & mwvpvf)
Definition at line 66 of file movingWallVelocityFvPatchVectorField.C.
movingWallVelocityFvPatchVectorField() [5/5]
movingWallVelocityFvPatchVectorField (const movingWallVelocityFvPatchVectorField & mwvpvf, const DimensionedField< vector, volMesh > & iF)
Definition at line 76 of file movingWallVelocityFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("movingWallVelocity")
clone() [1/2]
virtual tmp< fvPatchVectorField > clone () const inline virtual
Definition at line 109 of file movingWallVelocityFvPatchVectorField.H.
clone() [2/2]
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Definition at line 125 of file movingWallVelocityFvPatchVectorField.H.
Uwall()
Foam::tmp< Foam::vectorField > Uwall () const
Definition at line 90 of file movingWallVelocityFvPatchVectorField.C.
References PrimitivePatch< FaceList, PointField >::faceCentres(), forAll, mesh, Foam::fvc::meshPhi(), n, polyMesh::oldPoints(), p, pp(), fvMesh::time(), and U.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 124 of file movingWallVelocityFvPatchVectorField.C.
References mesh, polyMesh::moving(), and Field< vector >::operator=().
write()
void write (Ostream & os) const virtual
Definition at line 143 of file movingWallVelocityFvPatchVectorField.C.
References os(), fvPatchField< Type >::write(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/movingWallVelocity/movingWallVelocityFvPatchVectorField.H
src/finiteVolume/fields/fvPatchFields/derived/movingWallVelocity/movingWallVelocityFvPatchVectorField.C