OpenFOAM: rigidBody Class Reference
rigidBody Class Reference
Mesh motion » Rigid body dynamics » Bodies
#include <rigidBody.H>
Public Member Functions
TypeName ("rigidBody")
declareRunTimeSelectionTable (autoPtr, rigidBody, dictionary,(const word &name, const dictionary &dict),(name, dict))
rigidBody (const word &name, const scalar &m, const vector &c, const symmTensor &Ic)
rigidBody (const word &name, const rigidBodyInertia &rbi)
rigidBody (const word &name, const dictionary &dict)
virtual autoPtr< rigidBody > clone () const
virtual ~rigidBody ()
const word & name () const
virtual bool massless () const
void merge (const subBody &)
virtual void write (Ostream &) const
Public Member Functions inherited from rigidBodyInertia
rigidBodyInertia ()
rigidBodyInertia (const scalar m, const vector &c, const symmTensor &Ic)
rigidBodyInertia (const dictionary &dict)
rigidBodyInertia (const spatialTensor &st)
rigidBodyInertia (Istream &is)
scalar m () const
const vector & c () const
const symmTensor & Ic () const
symmTensor Ioc () const
symmTensor Icc (const vector &c) const
symmTensor Io () const
scalar kineticEnergy (const spatialVector &v)
operator spatialTensor () const
void operator+= (const rigidBodyInertia &)
Static Public Member Functions
static autoPtr< rigidBody > New (const word &name, const scalar &m, const vector &c, const symmTensor &Ic)
static autoPtr< rigidBody > New (const word &name, const dictionary &dict)
Static Public Member Functions inherited from rigidBodyInertia
static symmTensor Ioc (const scalar m, const vector &c)
Friends
Ostream & operator<< (Ostream &, const rigidBody &)
Detailed Description
Source files
rigidBody.H
rigidBodyI.H
Definition at line 61 of file rigidBody.H.
Constructor & Destructor Documentation
rigidBody() [1/3]
rigidBody (const word & name, const scalar & m, const vector & c, const symmTensor & Ic) inline
Definition at line 23 of file rigidBodyI.H.
References Foam::name().
rigidBody() [2/3]
rigidBody (const word & name, const rigidBodyInertia & rbi) inline
Definition at line 36 of file rigidBodyI.H.
rigidBody() [3/3]
rigidBody (const word & name, const dictionary & dict) inline
Definition at line 47 of file rigidBodyI.H.
~rigidBody()
~rigidBody () virtual
Definition at line 94 of file rigidBody.C.
Member Function Documentation
TypeName()
TypeName ("rigidBody")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , rigidBody , dictionary , (const word &name, const dictionary &dict) , (name, dict))
clone()
Foam::autoPtr< Foam::RBD::rigidBody > clone () const virtual
Reimplemented in compositeBody, cuboid, jointBody, masslessBody, and sphere.
Definition at line 47 of file rigidBody.C.
References autoPtr< T >::New().
New() [1/2]
Foam::autoPtr< Foam::RBD::rigidBody > New (const word & name, const scalar & m, const vector & c, const symmTensor & Ic) static
Definition at line 55 of file rigidBody.C.
References Foam::name(), and autoPtr< T >::New().
Referenced by rigidBodyModel::rigidBodyModel().
New() [2/2]
Foam::autoPtr< Foam::RBD::rigidBody > New (const word & name, const dictionary & dict) static
Definition at line 67 of file rigidBody.C.
References dict, Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, and Foam::name().
name()
const Foam::word & name () const inline
Definition at line 60 of file rigidBodyI.H.
Referenced by rigidBodyModel::join_().
massless()
bool massless () const virtual
Reimplemented in masslessBody.
Definition at line 100 of file rigidBody.C.
merge()
void merge (const subBody & subBody)
Definition at line 106 of file rigidBody.C.
References subBody::body(), subBody::masterXT(), Foam::name(), and Foam::RBD::transform().
write()
void write (Ostream & os) const virtual
Reimplemented in compositeBody, cuboid, masslessBody, and sphere.
Definition at line 116 of file rigidBody.C.
References os(), and Foam::type().
Friends And Related Symbol Documentation
operator<<
Ostream & operator<< (Ostream & , const rigidBody &) friend
The documentation for this class was generated from the following files:
src/rigidBodyDynamics/bodies/rigidBody/rigidBody.H
src/rigidBodyDynamics/bodies/rigidBody/rigidBody.C
src/rigidBodyDynamics/bodies/rigidBody/rigidBodyI.H