OpenFOAM: interfaceOxideRate< Thermo, OtherThermo > Class Template Reference
interfaceOxideRate< Thermo, OtherThermo > Class Template Reference
The interfaceOxideRate is a simple model to calculate the formation rate of oxide inclusions (mDotOxide), which is a local function of the volume fraction of reducing agent (alpha), temperature (T) and oxide-inclusion density (chi).
#include <interfaceOxideRate.H>
Public Member Functions
TypeName ("interfaceOxideRate")
interfaceOxideRate (const dictionary &dict, const phasePair &pair)
virtual ~interfaceOxideRate ()=default
virtual tmp< volScalarField > Kexp (const volScalarField &field)
virtual tmp< volScalarField > KSp (label modelVariable, const volScalarField &field)
virtual tmp< volScalarField > KSu (label modelVariable, const volScalarField &field)
virtual const dimensionedScalar & Tactivate () const noexcept
virtual bool includeDivU () const noexcept
Public Member Functions inherited from InterfaceCompositionModel< Thermo, OtherThermo >
InterfaceCompositionModel (const dictionary &dict, const phasePair &pair)
virtual ~InterfaceCompositionModel ()=default
virtual tmp< volScalarField > dY (const word &speciesName, const volScalarField &Tf) const
virtual tmp< volScalarField > Yf (const word &speciesName, const volScalarField &Tf) const
virtual tmp< volScalarField > Dfrom (const word &speciesName) const
virtual tmp< volScalarField > Dto (const word &speciesName) const
virtual tmp< volScalarField > L (const word &speciesName, const volScalarField &Tf) const
InterfaceCompositionModel (const dictionary &dict, const phasePair &pair)
~InterfaceCompositionModel ()=default
virtual tmp< volScalarField > dY (const word &speciesName, const volScalarField &Tf) const
virtual tmp< volScalarField > D (const word &speciesName) const
virtual tmp< volScalarField > L (const word &speciesName, const volScalarField &Tf) const
virtual void addMDotL (const volScalarField &K, const volScalarField &Tf, volScalarField &mDotL, volScalarField &mDotLPrime) const
template<class ThermoType >
const Foam::multiComponentMixture< ThermoType >::thermoType & getLocalThermo (const word &speciesName, const multiComponentMixture< ThermoType > &globalThermo) const
template<class ThermoType >
const Foam::pureMixture< ThermoType >::thermoType & getLocalThermo (const word &speciesName, const pureMixture< ThermoType > &globalThermo) const
template<class ThermoType >
Foam::tmp< Foam::volScalarField > getSpecieMassFraction (const word &speciesName, const multiComponentMixture< ThermoType > &mixture) const
template<class ThermoType >
Foam::tmp< Foam::volScalarField > getSpecieMassFraction (const word &speciesName, const pureMixture< ThermoType > &mixture) const
template<class ThermoType >
Foam::tmp< Foam::volScalarField > MwMixture (const pureMixture< ThermoType > &mixture) const
template<class ThermoType >
Foam::tmp< Foam::volScalarField > MwMixture (const multiComponentMixture< ThermoType > &mixture) const
Public Member Functions inherited from interfaceCompositionModel
TypeName ("interfaceCompositionModel")
declareRunTimeSelectionTable (autoPtr, interfaceCompositionModel, dictionary,(const dictionary &dict, const phasePair &pair),(dict, pair))
interfaceCompositionModel (const dictionary &dict, const phasePair &pair)
virtual ~interfaceCompositionModel ()=default
const word transferSpecie () const
const phasePair & pair () const
const multiphaseInterSystem & fluid () const
bool includeVolChange ()
const word & variable () const
Additional Inherited Members
Public Types inherited from interfaceCompositionModel
enum modelVariable { T , P , Y , alpha }
Static Public Member Functions inherited from interfaceCompositionModel
static autoPtr< interfaceCompositionModel > New (const dictionary &dict, const phasePair &pair)
Protected Member Functions inherited from InterfaceCompositionModel< Thermo, OtherThermo >
template<class ThermoType >
const pureMixture< ThermoType >::thermoType & getLocalThermo (const word &speciesName, const pureMixture< ThermoType > &globalThermo) const
template<class ThermoType >
const multiComponentMixture< ThermoType >::thermoType & getLocalThermo (const word &speciesName, const multiComponentMixture< ThermoType > &globalThermo) const
template<class ThermoType >
tmp< volScalarField > getSpecieMassFraction (const word &speciesName, const pureMixture< ThermoType > &thermo) const
template<class ThermoType >
tmp< volScalarField > getSpecieMassFraction (const word &speciesName, const multiComponentMixture< ThermoType > &thermo) const
template<class ThermoType >
tmp< volScalarField > MwMixture (const pureMixture< ThermoType > &thermo) const
template<class ThermoType >
tmp< volScalarField > MwMixture (const multiComponentMixture< ThermoType > &) const
template<class ThermoType >
const pureMixture< ThermoType >::thermoType & getLocalThermo (const word &speciesName, const pureMixture< ThermoType > &globalThermo) const
template<class ThermoType >
const multiComponentMixture< ThermoType >::thermoType & getLocalThermo (const word &speciesName, const multiComponentMixture< ThermoType > &globalThermo) const
Protected Attributes inherited from InterfaceCompositionModel< Thermo, OtherThermo >
const Thermo & fromThermo_
const OtherThermo & toThermo_
const dimensionedScalar Le_
const Thermo & thermo_
const OtherThermo & otherThermo_
Protected Attributes inherited from interfaceCompositionModel
modelVariable modelVariable_
bool includeVolChange_
const phasePair & pair_
word speciesName_
const fvMesh & mesh_
Static Protected Attributes inherited from interfaceCompositionModel
static const Enum< modelVariable > modelVariableNames_
Detailed Description
template<class Thermo, class OtherThermo>
class Foam::meltingEvaporationModels::interfaceOxideRate< Thermo, OtherThermo >
The interfaceOxideRate is a simple model to calculate the formation rate of oxide inclusions (mDotOxide), which is a local function of the volume fraction of reducing agent (alpha), temperature (T) and oxide-inclusion density (chi).
The oxide-inclusion formation rate is modelled as follows:
with
where
= Oxide-inclusion formation rate [kg/(m^3 s)]
= Oxide-inclusion formation rate constant [kg/(m^3 s)]
= Formation factor due to volume fraction of reducing agent [-]
= Formation factor due to temperature [-]
= Formation factor due to oxide-inclusion density [-]
= Volume fraction of reducing agent [-]
= Local temperature [K]
= Solidus temperature of reducing agent [K]
= Liquidus temperature of reducing agent [K]
= Critical oxide-inclusion density [kg/m^3]
= Current oxide-inclusion density [kg/m^3]
References:
        Oxide-inclusion model (tag:CSC):
            Cao, L., Sun, F., Chen, T., Tang, Y., & Liao, D. (2018).
            Quantitative prediction of oxide inclusion defects inside
            the casting and on the walls during cast-filling processes.
            International Journal of Heat and Mass Transfer, 119, 614-623.
            DOI:10.1016/j.ijheatmasstransfer.2017.11.127
Usage
Minimal example by using constant/phaseProperties.massTransferModel:
massTransferModel
(
    (liquid to oxide)
    {
        type                interfaceOxideRate;
        C                   <scalar>;
        Tliquidus           <scalar>;
        Tsolidus            <scalar>;
        oxideCrit           <scalar>;
        isoAlpha            <scalar>;
    }
);
where the entries mean:
Property Description Type Reqd Deflt
type Type name: interfaceOxideRate word yes -
C Oxide-inclusion formation rate constant scalar yes -
Tliquidus Liquidus temperature of reducing agent scalar yes -
Tsolidus Solidus temperature of reducing agent scalar yes -
oxideCrit Critical oxide-inclusion density scalar yes -
isoAlpha Location of the source scalar no 0.5
Note
oxideCrit should be determined experimentally (CSC:p. 616).
C should be determined by practical production (CSC:p. 616).
Source files
interfaceOxideRate.H
interfaceOxideRate.C
Definition at line 223 of file interfaceOxideRate.H.
Constructor & Destructor Documentation
interfaceOxideRate()
template<class Thermo , class OtherThermo > interfaceOxideRate (const dictionary & dict, const phasePair & pair)
Definition at line 30 of file interfaceOxideRate.C.
References Foam::dimDensity, Foam::dimTemperature, and Foam::dimTime.
~interfaceOxideRate()
template<class Thermo , class OtherThermo > virtual ~interfaceOxideRate () virtual default
Member Function Documentation
TypeName()
template<class Thermo , class OtherThermo > TypeName ("interfaceOxideRate< Thermo, OtherThermo >")
Kexp()
template<class Thermo , class OtherThermo > Foam::tmp< Foam::volScalarField > Kexp (const volScalarField & field) virtual
Implements interfaceCompositionModel.
Definition at line 90 of file interfaceOxideRate.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), Foam::dimDensity, e, Foam::exp(), forAll, Foam::interpolate(), Foam::max(), mesh, tmp< T >::New(), MeshObject< fvMesh, UpdateableMeshObject, volPointInterpolation >::New(), pp(), T, and Foam::Zero.
KSp()
template<class Thermo , class OtherThermo > Foam::tmp< Foam::volScalarField > KSp (label modelVariable, const volScalarField & field) virtual
Implements interfaceCompositionModel.
Definition at line 178 of file interfaceOxideRate.C.
KSu()
template<class Thermo , class OtherThermo > Foam::tmp< Foam::volScalarField > KSu (label modelVariable, const volScalarField & field) virtual
Implements interfaceCompositionModel.
Definition at line 190 of file interfaceOxideRate.C.
Tactivate()
template<class Thermo , class OtherThermo > virtual const dimensionedScalar & Tactivate () const inline virtual noexcept
Implements interfaceCompositionModel.
Definition at line 291 of file interfaceOxideRate.H.
includeDivU()
template<class Thermo , class OtherThermo > virtual bool includeDivU () const inline virtual noexcept
Reimplemented from interfaceCompositionModel.
Definition at line 298 of file interfaceOxideRate.H.
The documentation for this class was generated from the following files:
src/phaseSystemModels/multiphaseInter/phasesSystem/massTransferModels/interfaceOxideRate/interfaceOxideRate.H
src/phaseSystemModels/multiphaseInter/phasesSystem/massTransferModels/interfaceOxideRate/interfaceOxideRate.C