OpenFOAM: fvMotionSolver Class Reference
fvMotionSolver Class Reference
Base class for fvMesh based motionSolvers.
#include <fvMotionSolver.H>
Public Member Functions
ClassName ("displacementMotionSolver")
fvMotionSolver (const polyMesh &)
const fvMesh & mesh () const
template<class Type >
Foam::wordList cellMotionBoundaryTypes (const typename GeometricField< Type, pointPatchField, pointMesh >::Boundary &pmUbf) const
Protected Member Functions
template<class Type >
wordList cellMotionBoundaryTypes (const typename GeometricField< Type, pointPatchField, pointMesh >::Boundary &pmUbf) const
Protected Attributes
const fvMesh & fvMesh_
Detailed Description
Base class for fvMesh based motionSolvers.
Source files
fvMotionSolver.H
fvMotionSolver.C
Definition at line 46 of file fvMotionSolver.H.
Constructor & Destructor Documentation
fvMotionSolver()
fvMotionSolver (const polyMesh & mesh)
Definition at line 33 of file fvMotionSolver.C.
References Foam::refCast().
Member Function Documentation
cellMotionBoundaryTypes() [1/2]
template<class Type > wordList cellMotionBoundaryTypes (const typename GeometricField< Type, pointPatchField, pointMesh >::Boundary & pmUbf) const protected
ClassName()
ClassName ("displacementMotionSolver")
mesh()
const fvMesh & mesh () const inline
Definition at line 82 of file fvMotionSolver.H.
References fvMotionSolver::fvMesh_.
Referenced by surfaceAlignedSBRStressFvMotionSolver::surfaceAlignedSBRStressFvMotionSolver().
cellMotionBoundaryTypes() [2/2]
template<class Type > Foam::wordList cellMotionBoundaryTypes (const typename GeometricField< Type, pointPatchField, pointMesh >::Boundary & pmUbf) const
Definition at line 28 of file fvMotionSolverTemplates.C.
References Foam::endl(), forAll, fvMotionSolver::fvMesh_, Foam::isA(), Foam::Pout, PtrList< T >::setSize(), and UPtrList< T >::size().
Member Data Documentation
fvMesh_
const fvMesh& fvMesh_ protected
Definition at line 54 of file fvMotionSolver.H.
Referenced by fvMotionSolver::cellMotionBoundaryTypes(), displacementComponentLaplacianFvMotionSolver::displacementComponentLaplacianFvMotionSolver(), displacementLaplacianFvMotionSolver::displacementLaplacianFvMotionSolver(), displacementLaplacianFvMotionSolver::displacementLaplacianFvMotionSolver(), fvMotionSolver::mesh(), laplacianMotionSolver::setBoundaryConditions(), solidBodyDisplacementLaplacianFvMotionSolver::solidBodyDisplacementLaplacianFvMotionSolver(), and solidBodyDisplacementLaplacianFvMotionSolver::solidBodyDisplacementLaplacianFvMotionSolver().
The documentation for this class was generated from the following files:
src/fvMotionSolver/fvMotionSolvers/fvMotionSolver/fvMotionSolver.H
src/fvMotionSolver/fvMotionSolvers/fvMotionSolver/fvMotionSolver.C
src/fvMotionSolver/fvMotionSolvers/fvMotionSolver/fvMotionSolverTemplates.C