OpenFOAM: dynamicFvMesh Class Reference
dynamicFvMesh Class Reference abstract
Abstract base class for geometry and/or topology changing fvMesh.
#include <dynamicFvMesh.H>
Public Member Functions
TypeName ("dynamicFvMesh")
declareRunTimeSelectionTable (autoPtr, dynamicFvMesh, IOobject,(const IOobject &io),(io))
declareRunTimeSelectionTable (autoPtr, dynamicFvMesh, doInit,(const IOobject &io, const bool doInit),(io, doInit))
dynamicFvMesh (const IOobject &io, const bool doInit=true)
dynamicFvMesh (const IOobject &io, const Foam::zero, bool syncPar=true)
dynamicFvMesh (const IOobject &io, pointField &&points, faceList &&faces, labelList &&allOwner, labelList &&allNeighbour, const bool syncPar=true)
dynamicFvMesh (const IOobject &io, pointField &&points, faceList &&faces, cellList &&cells, const bool syncPar=true)
virtual ~dynamicFvMesh ()=default
virtual bool init (const bool doInit)
virtual bool dynamic () const
virtual bool controlledUpdate ()
virtual bool update ()=0
Public Member Functions inherited from fvMesh
ClassName ("fvMesh")
fvMesh (const IOobject &io, const bool doInit=true)
fvMesh (const IOobject &io, const Foam::zero, bool syncPar=true)
fvMesh (const IOobject &io, const fvMesh &baseMesh, const Foam::zero, const bool syncPar=true)
fvMesh (const IOobject &io, pointField &&points, faceList &&faces, labelList &&allOwner, labelList &&allNeighbour, const bool syncPar=true)
fvMesh (const IOobject &io, pointField &&points, faceList &&faces, cellList &&cells, const bool syncPar=true)
fvMesh (const IOobject &io, const fvMesh &baseMesh, pointField &&points, faceList &&faces, labelList &&allOwner, labelList &&allNeighbour, const bool syncPar=true)
fvMesh (const IOobject &io, const fvMesh &baseMesh, pointField &&points, faceList &&faces, cellList &&cells, const bool syncPar=true)
virtual ~fvMesh ()
void addFvPatches (polyPatchList &plist, const bool validBoundary=true)
void addFvPatches (const List< polyPatch * > &p, const bool validBoundary=true)
virtual readUpdateState readUpdate ()
const Time & time () const
virtual bool hasDb () const
virtual const objectRegistry & thisDb () const
const word & name () const
const fvBoundaryMesh & boundary () const noexcept
virtual const lduAddressing & lduAddr () const
virtual lduInterfacePtrsList interfaces () const
virtual label comm () const
virtual void interpolate (volScalarField &) const
virtual void interpolate (volVectorField &) const
virtual void interpolate (volSphericalTensorField &) const
virtual void interpolate (volSymmTensorField &) const
virtual void interpolate (volTensorField &) const
virtual void interpolate (scalarField &) const
virtual void interpolate (vectorField &) const
virtual void interpolate (sphericalTensorField &) const
virtual void interpolate (symmTensorField &) const
virtual void interpolate (tensorField &) const
virtual SolverPerformance< scalar > solve (fvMatrix< scalar > &, const dictionary &) const
virtual SolverPerformance< vector > solve (fvMatrix< vector > &, const dictionary &) const
virtual SolverPerformance< sphericalTensor > solve (fvMatrix< sphericalTensor > &, const dictionary &) const
virtual SolverPerformance< symmTensor > solve (fvMatrix< symmTensor > &, const dictionary &) const
virtual SolverPerformance< tensor > solve (fvMatrix< tensor > &, const dictionary &) const
const labelUList & owner () const
const labelUList & neighbour () const
const DimensionedField< scalar, volMesh > & V () const
const DimensionedField< scalar, volMesh > & V0 () const
const DimensionedField< scalar, volMesh > & V00 () const
tmp< DimensionedField< scalar, volMesh > > Vsc () const
tmp< DimensionedField< scalar, volMesh > > Vsc0 () const
const surfaceVectorField & Sf () const
const surfaceScalarField & magSf () const
tmp< surfaceVectorField > unitSf () const
const surfaceScalarField & phi () const
const volVectorField & C () const
const surfaceVectorField & Cf () const
tmp< surfaceVectorField > delta () const
template<class Type >
pTraits< Type >::labelType validComponents () const
void clearOut ()
virtual void updateMesh (const mapPolyMesh &mpm)
virtual void movePoints (const pointField &)
virtual void updateGeom ()
virtual void mapFields (const mapPolyMesh &mpm)
void removeFvBoundary ()
refPtr< surfaceScalarField > setPhi ()
DimensionedField< scalar, volMesh > & setV0 ()
virtual bool writeObject (IOstreamOption streamOpt, const bool writeOnProc) const
virtual bool write (const bool writeOnProc=true) const
bool operator!= (const fvMesh &rhs) const
bool operator== (const fvMesh &rhs) const
template<>
pTraits< sphericalTensor >::labelType validComponents () const
template<class Type >
Foam::pTraits< Type >::labelType validComponents () const
virtual bool movePoints ()
Public Member Functions inherited from polyMesh
TypeName ("polyMesh")
polyMesh (const IOobject &io, const bool doInit=true)
polyMesh (const IOobject &io, const zero, const bool syncPar=true)
polyMesh (const IOobject &io, pointField &&points, faceList &&faces, labelList &&owner, labelList &&neighbour, const bool syncPar=true)
polyMesh (const IOobject &io, pointField &&points, faceList &&faces, cellList &&cells, const bool syncPar=true)
polyMesh (const IOobject &io, pointField &&points, const cellShapeList &shapes, const faceListList &boundaryFaces, const wordList &boundaryPatchNames, const wordList &boundaryPatchTypes, const word &defaultBoundaryPatchName, const word &defaultBoundaryPatchType, const wordList &boundaryPatchPhysicalTypes, const bool syncPar=true)
polyMesh (const IOobject &io, pointField &&points, const cellShapeList &shapes, const faceListList &boundaryFaces, const wordList &boundaryPatchNames, const PtrList< dictionary > &boundaryDicts, const word &defaultBoundaryPatchName, const word &defaultBoundaryPatchType, const bool syncPar=true)
virtual ~polyMesh ()
virtual const fileName & dbDir () const
fileName meshDir () const
const fileName & pointsInstance () const
const fileName & facesInstance () const
void setInstance (const fileName &instance, const IOobjectOption::writeOption wOpt=IOobject::AUTO_WRITE)
const word & regionName () const
virtual const pointField & points () const
virtual bool upToDatePoints (const regIOobject &io) const
virtual void setUpToDatePoints (regIOobject &io) const
virtual const faceList & faces () const
virtual const labelList & faceOwner () const
virtual const labelList & faceNeighbour () const
virtual const pointField & oldPoints () const
virtual const pointField & oldCellCentres () const
const polyBoundaryMesh & boundaryMesh () const noexcept
const boundBox & bounds () const noexcept
const Vector< label > & geometricD () const
label nGeometricD () const
const Vector< label > & solutionD () const
label nSolutionD () const
const labelIOList & tetBasePtIs () const
const indexedOctree< treeDataCell > & cellTree () const
const pointZoneMesh & pointZones () const noexcept
const faceZoneMesh & faceZones () const noexcept
const cellZoneMesh & cellZones () const noexcept
const globalMeshData & globalData () const
label comm () const noexcept
label & comm () noexcept
const objectRegistry & thisDb () const noexcept
bool moving () const noexcept
bool moving (const bool on) noexcept
bool topoChanging () const noexcept
bool topoChanging (const bool on) noexcept
bool changing () const noexcept
void resetMotion () const
pointZoneMesh & pointZones () noexcept
faceZoneMesh & faceZones () noexcept
cellZoneMesh & cellZones () noexcept
void addPatches (polyPatchList &plist, const bool validBoundary=true)
void addPatches (const List< polyPatch * > &p, const bool validBoundary=true)
void addZones (PtrList< pointZone > &&pz, PtrList< faceZone > &&fz, PtrList< cellZone > &&cz)
void addZones (const List< pointZone * > &pz, const List< faceZone * > &fz, const List< cellZone * > &cz)
void removeBoundary ()
void resetPrimitives (autoPtr< pointField > &&points, autoPtr< faceList > &&faces, autoPtr< labelList > &&owner, autoPtr< labelList > &&neighbour, const labelUList &patchSizes, const labelUList &patchStarts, const bool validBoundary=true)
void clearGeom ()
void updateGeomPoints (pointIOField &&newPoints, autoPtr< labelIOList > &newTetBasePtIsPtr)
void clearAddressing (const bool isMeshUpdate=false)
void clearOut ()
void clearPrimitives ()
void clearTetBasePtIs ()
void clearCellTree ()
void removeFiles (const fileName &instanceDir) const
void removeFiles () const
bool hasTetBasePtIs () const
virtual bool checkFaceOrthogonality (const bool report=false, labelHashSet *setPtr=nullptr) const
virtual bool checkFaceSkewness (const bool report=false, labelHashSet *setPtr=nullptr) const
virtual bool checkEdgeAlignment (const bool report, const Vector< label > &directions, labelHashSet *setPtr) const
virtual bool checkCellDeterminant (const bool report, labelHashSet *setPtr) const
virtual bool checkMeshMotion (const pointField &newPoints, const bool report=false, const bool detailedReport=false) const
virtual bool checkFaceWeight (const bool report, const scalar minWeight=0.05, labelHashSet *setPtr=nullptr) const
virtual bool checkVolRatio (const bool report, const scalar minRatio=0.01, labelHashSet *setPtr=nullptr) const
void findCellFacePt (const point &p, label &celli, label &tetFacei, label &tetPti) const
void findTetFacePt (const label celli, const point &p, label &tetFacei, label &tetPti) const
bool pointInCell (const point &p, label celli, const cellDecomposition=CELL_TETS) const
label findCell (const point &p, const cellDecomposition=CELL_TETS) const
Public Member Functions inherited from objectRegistry
TypeName ("objectRegistry")
objectRegistry (const Time &db, const label nObjects=128)
objectRegistry (const IOobject &io, const label nObjects=128)
virtual ~objectRegistry ()
const objectRegistry & thisDb () const noexcept
const objectRegistry & parent () const noexcept
const Time & time () const noexcept
bool isTimeDb () const noexcept
HashTable< wordHashSet > classes () const
template<class MatchPredicate >
HashTable< wordHashSet > classes (const MatchPredicate &matchName) const
UPtrList< const regIOobject > csorted () const
UPtrList< const regIOobject > sorted () const
UPtrList< regIOobject > sorted ()
template<class Type >
UPtrList< const Type > csorted () const
template<class Type >
UPtrList< const Type > sorted () const
template<class Type >
UPtrList< Type > sorted ()
template<class Type , class MatchPredicate >
UPtrList< const Type > csorted (const MatchPredicate &matchName) const
template<class Type , class MatchPredicate >
UPtrList< const Type > sorted (const MatchPredicate &matchName) const
template<class Type , class MatchPredicate >
UPtrList< Type > sorted (const MatchPredicate &matchName)
label count (const char *clsName) const
template<class MatchPredicate >
label count (const MatchPredicate &matchClass) const
template<class MatchPredicate1 , class MatchPredicate2 >
label count (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName) const
template<class Type >
label count (const bool strict=false) const
template<class Type , class MatchPredicate >
label count (const MatchPredicate &matchName) const
wordList names () const
wordList names (const char *clsName) const
template<class MatchPredicate >
wordList names (const MatchPredicate &matchClass) const
template<class MatchPredicate1 , class MatchPredicate2 >
wordList names (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName) const
template<class Type >
wordList names () const
template<class Type , class MatchPredicate >
wordList names (const MatchPredicate &matchName) const
wordList sortedNames () const
wordList sortedNames (const char *clsName) const
template<class MatchPredicate >
wordList sortedNames (const MatchPredicate &matchClass) const
template<class MatchPredicate1 , class MatchPredicate2 >
wordList sortedNames (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName) const
template<class Type >
wordList sortedNames () const
template<class Type , class MatchPredicate >
wordList sortedNames (const MatchPredicate &matchName) const
const objectRegistry & subRegistry (const word &name, const bool forceCreate=false, const bool recursive=false) const
template<class Type >
HashTable< const Type * > lookupClass (const bool strict=false) const
template<class Type >
HashTable< Type * > lookupClass (const bool strict=false)
const regIOobject * cfindIOobject (const word &name, const bool recursive=false) const
bool contains (const word &name, const bool recursive=false) const
template<class Type >
bool foundObject (const word &name, const bool recursive=false) const
template<class Type >
const Type * cfindObject (const word &name, const bool recursive=false) const
template<class Type >
const Type * findObject (const word &name, const bool recursive=false) const
template<class Type >
Type * findObject (const word &name, const bool recursive=false)
template<class Type >
Type * getObjectPtr (const word &name, const bool recursive=false) const
template<class Type >
const Type & lookupObject (const word &name, const bool recursive=false) const
template<class Type >
Type & lookupObjectRef (const word &name, const bool recursive=false) const
label getEvent () const
bool checkIn (regIOobject *io) const
bool checkIn (regIOobject &io) const
bool checkOut (regIOobject *io) const
bool checkOut (regIOobject &io) const
bool checkOut (const word &key) const
void clear ()
void clearStorage ()
bool erase (const iterator &iter)
bool erase (const word &key)
label erase (std::initializer_list< word > keys)
label erase (const UList< word > &keys)
virtual void rename (const word &newName)
bool cacheTemporaryObject (const word &name) const
template<class Type >
bool cacheTemporaryObject (Type &obj) const
void resetCacheTemporaryObject (const regIOobject *io) const
void resetCacheTemporaryObject (const regIOobject &io) const
bool checkCacheTemporaryObjects () const
virtual bool modified () const
void readModifiedObjects ()
virtual bool readIfModified ()
virtual bool writeData (Ostream &) const
bool found (const word &name, bool recursive=false) const
template<class Type >
const Type * lookupObjectPtr (const word &name, bool recursive=false) const
template<class Type >
Type * lookupObjectRefPtr (const word &name, bool recursive=false) const
template<class MatchPredicate >
Foam::HashTable< Foam::wordHashSet > classesImpl (const objectRegistry &list, const MatchPredicate &matchName)
template<class MatchPredicate1 , class MatchPredicate2 >
Foam::label countImpl (const objectRegistry &list, const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName)
template<class Type , class MatchPredicate >
Foam::label countTypeImpl (const objectRegistry &list, const MatchPredicate &matchName)
template<class MatchPredicate1 , class MatchPredicate2 >
Foam::wordList namesImpl (const objectRegistry &list, const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName, const bool doSort)
template<class Type , class MatchPredicate >
Foam::wordList namesTypeImpl (const objectRegistry &list, const MatchPredicate &matchName, const bool doSort)
template<class Type , class MatchPredicate >
Foam::UPtrList< Type > objectsTypeImpl (const objectRegistry &list, const MatchPredicate &matchName)
template<class MatchPredicate >
Foam::HashTable< Foam::wordHashSet > classes (const MatchPredicate &matchName) const
template<class MatchPredicate >
Foam::label count (const MatchPredicate &matchClass) const
template<class MatchPredicate1 , class MatchPredicate2 >
Foam::label count (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName) const
template<class Type , class MatchPredicate >
Foam::label count (const MatchPredicate &matchName) const
template<class Type >
Foam::label count (const bool strict) const
template<class Type >
Foam::UPtrList< const Type > csorted () const
template<class Type >
Foam::UPtrList< const Type > sorted () const
template<class Type >
Foam::UPtrList< Type > sorted ()
template<class Type , class MatchPredicate >
Foam::UPtrList< const Type > csorted (const MatchPredicate &matchName) const
template<class Type , class MatchPredicate >
Foam::UPtrList< const Type > sorted (const MatchPredicate &matchName) const
template<class Type , class MatchPredicate >
Foam::UPtrList< Type > sorted (const MatchPredicate &matchName)
template<class MatchPredicate >
Foam::wordList names (const MatchPredicate &matchClass) const
template<class MatchPredicate1 , class MatchPredicate2 >
Foam::wordList names (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName) const
template<class Type >
Foam::wordList names () const
template<class Type , class MatchPredicate >
Foam::wordList names (const MatchPredicate &matchName) const
template<class MatchPredicate >
Foam::wordList sortedNames (const MatchPredicate &matchClass) const
template<class MatchPredicate1 , class MatchPredicate2 >
Foam::wordList sortedNames (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName) const
template<class Type >
Foam::wordList sortedNames () const
template<class Type , class MatchPredicate >
Foam::wordList sortedNames (const MatchPredicate &matchName) const
template<class Type >
Foam::HashTable< const Type * > lookupClass (const bool strict) const
template<class Type >
Foam::HashTable< Type * > lookupClass (const bool strict)
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
regIOobject (const IOobject &io, const bool isTimeObject=false)
regIOobject (const regIOobject &rio)
regIOobject (const regIOobject &rio, bool registerCopy)
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
regIOobject (const IOobject &io, const regIOobject &rio)
virtual ~regIOobject ()
bool checkIn ()
bool checkOut ()
virtual void addWatch ()
bool registered () const noexcept
bool ownedByRegistry () const noexcept
bool store ()
void release (const bool unregister=false) noexcept
label eventNo () const noexcept
label & eventNo () noexcept
bool upToDate (const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
void setUpToDate ()
const dictionary * findMetaData () const noexcept
dictionary & getMetaData () noexcept
void removeMetaData ()
virtual void updateMetaData ()
bool headerOk ()
Istream & readStream (const word &, const bool readOnProc=true)
void close ()
virtual label addWatch (const fileName &)
const labelList & watchIndices () const noexcept
labelList & watchIndices () noexcept
void operator= (const IOobject &io)
virtual bool writeObject (IOstreamOption::streamFormat fmt, IOstreamOption::versionNumber ver, IOstreamOption::compressionType cmp, const bool writeOnProc) const
Public Member Functions inherited from IOobject
TypeName ("IOobject")
IOobject (const IOobject &)=default
virtual ~IOobject ()=default
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const fileName &path, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const fileName &path, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const IOobject &io, const objectRegistry &registry)
IOobject (const IOobject &io, const word &name)
IOobject (const IOobject &io, const word &name, const fileName &local)
IOobject (const IOobject &io, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt)
IOobject (const IOobject &io, IOobjectOption::registerOption regOpt)
autoPtr< IOobject > clone () const
autoPtr< IOobject > clone (const objectRegistry &registry) const
const objectRegistry & db () const noexcept
const Time & time () const noexcept
const word & name () const noexcept
const word & headerClassName () const noexcept
word & headerClassName () noexcept
const string & note () const noexcept
string & note () noexcept
unsigned labelByteSize () const noexcept
unsigned scalarByteSize () const noexcept
void resetHeader (const word &newName=word::null)
bool hasHeaderClass () const noexcept
template<class Type >
bool isHeaderClass () const
template<class Type >
bool isHeaderClassName () const
word group () const
word member () const
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const noexcept
fileName & instance () noexcept
const fileName & local () const noexcept
fileName path () const
fileName path (const word &instance, const fileName &local=fileName::null) const
fileName objectPath () const
fileName objectRelPath () const
fileName localFilePath (const word &typeName, const bool search=true) const
fileName globalFilePath (const word &typeName, const bool search=true) const
IOstreamOption parseHeader (const dictionary &headerDict)
bool readHeader (Istream &is)
bool readHeader (dictionary &headerDict, Istream &is)
template<class Type >
bool typeHeaderOk (const bool checkType=true, const bool search=true, const bool verbose=true)
template<class Type >
void warnNoRereading () const
bool writeHeader (Ostream &os) const
bool writeHeader (Ostream &os, const word &objectType) const
void writeHeader (dictionary &dict, IOstreamOption streamOpt) const
void writeHeader (dictionary &dict, const word &objectType, IOstreamOption streamOpt) const
bool good () const noexcept
bool bad () const noexcept
InfoProxy< IOobject > info () const noexcept
void operator= (const IOobject &io)
template<>
bool isHeaderClass () const
template<class StringType >
Foam::word groupName (StringType base, const word &group)
Public Member Functions inherited from IOobjectOption
constexpr IOobjectOption (readOption rOpt=readOption::NO_READ, writeOption wOpt=writeOption::NO_WRITE, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (readOption rOpt, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (writeOption wOpt, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (registerOption registerObject, bool globalObject=false) noexcept
constexpr IOobjectOption (readOption rOpt, writeOption wOpt, bool registerObject, bool globalObject=false) noexcept
constexpr IOobjectOption (bool registerObject, bool globalObject=false) noexcept
readOption readOpt () const noexcept
readOption readOpt (readOption opt) noexcept
writeOption writeOpt () const noexcept
writeOption writeOpt (writeOption opt) noexcept
bool registerObject () const noexcept
bool registerObject (bool on) noexcept
bool globalObject () const noexcept
bool globalObject (bool on) noexcept
bool isAnyRead () const noexcept
bool isReadRequired () const noexcept
bool isReadOptional () const noexcept
readOption & readOpt () noexcept
writeOption & writeOpt () noexcept
bool & registerObject () noexcept
bool & globalObject () noexcept
Public Member Functions inherited from HashTable< regIOobject * >
HashTable ()
HashTable (const label size)
HashTable (Istream &is, const label size=128)
HashTable (const this_type &ht)
HashTable (this_type &&rhs)
HashTable (std::initializer_list< std::pair< word, regIOobject * > > list)
~HashTable ()
bool empty () const noexcept
label size () const noexcept
label capacity () const noexcept
regIOobject * & at (const word &key)
const regIOobject * & at (const word &key) const
bool contains (const word &key) const
iterator find (const word &key)
const_iterator find (const word &key) const
const_iterator cfind (const word &key) const
const regIOobject * & lookup (const word &key, const regIOobject * &deflt) const
List< word > toc () const
List< word > sortedToc () const
List< word > sortedToc (const Compare &comp) const
Foam::List< word > sortedToc (const Compare &comp) const
List< word > tocKeys (const UnaryPredicate &pred, const bool invert=false) const
Foam::List< word > tocKeys (const UnaryPredicate &pred, const bool invert) const
List< word > tocValues (const UnaryPredicate &pred, const bool invert=false) const
Foam::List< word > tocValues (const UnaryPredicate &pred, const bool invert) const
List< word > tocEntries (const BinaryPredicate &pred, const bool invert=false) const
Foam::List< word > tocEntries (const BinaryPredicate &pred, const bool invert) const
UPtrList< const node_type > csorted () const
UPtrList< const node_type > sorted () const
UPtrList< node_type > sorted ()
label countKeys (const UnaryPredicate &pred, const bool invert=false) const
Foam::label countKeys (const UnaryPredicate &pred, const bool invert) const
label countValues (const UnaryPredicate &pred, const bool invert=false) const
Foam::label countValues (const UnaryPredicate &pred, const bool invert) const
label countEntries (const BinaryPredicate &pred, const bool invert=false) const
Foam::label countEntries (const BinaryPredicate &pred, const bool invert) const
bool emplace (const word &key, Args &&... args)
bool emplace_set (const word &key, Args &&... args)
bool insert (const word &key, const regIOobject * &obj)
bool insert (const word &key, regIOobject * &&obj)
bool set (const word &key, const regIOobject * &obj)
bool set (const word &key, regIOobject * &&obj)
bool erase (const iterator &iter)
bool erase (const word &key)
label erase (const HashTable< AnyType, word, AnyHash > &other)
label erase (std::initializer_list< word > keys)
label erase (InputIter first, InputIter last)
label erase (const FixedList< word, N > &keys)
label erase (const UList< word > &keys)
Foam::label erase (InputIter first, InputIter last)
Foam::label erase (const FixedList< word, N > &keys)
Foam::label erase (const HashTable< AnyType, word, AnyHash > &other)
label retain (const HashTable< AnyType, word, AnyHash > &other)
Foam::label retain (const HashTable< AnyType, word, AnyHash > &other)
label filterKeys (const UnaryPredicate &pred, const bool pruning=false)
Foam::label filterKeys (const UnaryPredicate &pred, const bool pruning)
label filterValues (const UnaryPredicate &pred, const bool pruning=false)
Foam::label filterValues (const UnaryPredicate &pred, const bool pruning)
label filterEntries (const BinaryPredicate &pred, const bool pruning=false)
Foam::label filterEntries (const BinaryPredicate &pred, const bool pruning)
void resize (const label sz)
void clear ()
void clearStorage ()
void swap (HashTable< regIOobject *, word, Foam::Hash< word > > &rhs)
void transfer (HashTable< regIOobject *, word, Foam::Hash< word > > &rhs)
void merge (HashTable< regIOobject *, word, Foam::Hash< word > > &source)
void merge (HashTable< regIOobject *, word, Foam::Hash< word > > &&source)
regIOobject * & operator[] (const word &key)
const regIOobject * & operator[] (const word &key) const
regIOobject * & operator() (const word &key)
regIOobject * & operator() (const word &key, const regIOobject * &deflt)
void operator= (const this_type &rhs)
void operator= (std::initializer_list< std::pair< word, regIOobject * > > rhs)
void operator= (this_type &&rhs)
bool operator== (const this_type &rhs) const
bool operator!= (const this_type &rhs) const
this_type & operator+= (const this_type &rhs)
const_iterator_pair< const_key_iterator, this_type > keys () const
iterator begin ()
const_iterator begin () const
const_iterator cbegin () const
iterator end () noexcept
const_iterator end () const noexcept
constexpr const_iterator cend () const noexcept
Ostream & printInfo (Ostream &os) const
Ostream & writeKeys (Ostream &os, const label shortLen=0) const
bool found (const word &key) const
Public Member Functions inherited from HashTableCore
ClassName ("HashTable")
HashTableCore () noexcept=default
Public Member Functions inherited from primitiveMesh
ClassName ("primitiveMesh")
primitiveMesh (const label nPoints, const label nInternalFaces, const label nFaces, const label nCells)
virtual ~primitiveMesh ()
void reset (const label nPoints, const label nInternalFaces, const label nFaces, const label nCells)
void reset (const label nPoints, const label nInternalFaces, const label nFaces, const label nCells, cellList &cells)
void resetGeometry (pointField &&faceCentres, pointField &&faceAreas, pointField &&cellCentres, scalarField &&cellVolumes)
label nPoints () const noexcept
label nEdges () const
label nFaces () const noexcept
label nCells () const noexcept
label nInternalFaces () const noexcept
label nBoundaryFaces () const noexcept
label nInternalPoints () const noexcept
label nInternal0Edges () const
label nInternal1Edges () const
label nInternalEdges () const
const cellShapeList & cellShapes () const
const edgeList & edges () const
const labelListList & cellCells () const
const labelListList & edgeCells () const
const labelListList & pointCells () const
const cellList & cells () const
const labelListList & edgeFaces () const
const labelListList & pointFaces () const
const labelListList & cellEdges () const
const labelListList & faceEdges () const
const labelListList & pointEdges () const
const labelListList & pointPoints () const
const labelListList & cellPoints () const
const vectorField & cellCentres () const
const vectorField & faceCentres () const
const scalarField & cellVolumes () const
const vectorField & faceAreas () const
void movePoints (const pointField &p, const pointField &oldP)
bool isInternalFace (const label faceIndex) const noexcept
virtual bool checkUpperTriangular (const bool report=false, labelHashSet *setPtr=nullptr) const
virtual bool checkCellsZipUp (const bool report=false, labelHashSet *setPtr=nullptr) const
virtual bool checkFaceVertices (const bool report=false, labelHashSet *setPtr=nullptr) const
virtual bool checkPoints (const bool report=false, labelHashSet *setPtr=nullptr) const
virtual bool checkFaceFaces (const bool report=false, labelHashSet *setPtr=nullptr) const
virtual bool checkClosedBoundary (const bool report=false) const
virtual bool checkClosedCells (const bool report=false, labelHashSet *setPtr=nullptr, labelHashSet *highAspectSetPtr=nullptr, const Vector< label > &solutionD=Vector< label >::one) const
virtual bool checkFaceAreas (const bool report=false, labelHashSet *setPtr=nullptr) const
virtual bool checkCellVolumes (const bool report=false, labelHashSet *setPtr=nullptr) const
virtual bool checkFacePyramids (const bool report=false, const scalar minPyrVol=-SMALL, labelHashSet *setPtr=nullptr) const
virtual bool checkFaceAngles (const bool report=false, const scalar maxSin=10, labelHashSet *setPtr=nullptr) const
virtual bool checkFaceFlatness (const bool report, const scalar warnFlatness, labelHashSet *setPtr) const
virtual bool checkPointNearness (const bool report, const scalar reportDistSqr, labelHashSet *setPtr=nullptr) const
virtual bool checkEdgeLength (const bool report, const scalar minLenSqr, labelHashSet *setPtr=nullptr) const
virtual bool checkConcaveCells (const bool report=false, labelHashSet *setPtr=nullptr) const
virtual bool checkTopology (const bool report=false) const
virtual bool checkGeometry (const bool report=false) const
virtual bool checkMesh (const bool report=false) const
boundBox cellBb (const label celli) const
bool pointInCellBB (const point &p, label celli, scalar inflationFraction=0) const
bool pointInCell (const point &p, label celli) const
label findNearestCell (const point &location) const
label findCell (const point &location) const
void printAllocated () const
bool hasCellShapes () const noexcept
bool hasEdges () const noexcept
bool hasCellCells () const noexcept
bool hasEdgeCells () const noexcept
bool hasPointCells () const noexcept
bool hasCells () const noexcept
bool hasEdgeFaces () const noexcept
bool hasPointFaces () const noexcept
bool hasCellEdges () const noexcept
bool hasFaceEdges () const noexcept
bool hasPointEdges () const noexcept
bool hasPointPoints () const noexcept
bool hasCellPoints () const noexcept
bool hasCellCentres () const noexcept
bool hasCellVolumes () const noexcept
bool hasFaceCentres () const noexcept
bool hasFaceAreas () const noexcept
const labelList & cellCells (const label celli, DynamicList< label > &) const
const labelList & cellCells (const label celli) const
const labelList & cellPoints (const label celli, labelHashSet &, DynamicList< label > &) const
const labelList & cellPoints (const label celli) const
const labelList & pointCells (const label pointi, DynamicList< label > &) const
const labelList & pointCells (const label pointi) const
const labelList & pointPoints (const label pointi, DynamicList< label > &) const
const labelList & pointPoints (const label pointi) const
const labelList & faceEdges (const label facei, DynamicList< label > &) const
const labelList & faceEdges (const label facei) const
const labelList & edgeFaces (const label edgeI, DynamicList< label > &) const
const labelList & edgeFaces (const label edgeI) const
const labelList & edgeCells (const label edgeI, DynamicList< label > &) const
const labelList & edgeCells (const label edgeI) const
const labelList & cellEdges (const label celli, labelHashSet &, DynamicList< label > &) const
const labelList & cellEdges (const label celli) const
void clearGeom ()
void clearCellGeom ()
void clearAddressing ()
void clearOut ()
Public Member Functions inherited from lduMesh
TypeName ("lduMesh")
virtual ~lduMesh ()=default
template<class T , class BinaryOp >
void reduce (T &Value, const BinaryOp &bop) const
InfoProxy< lduMesh > info () const noexcept
Public Member Functions inherited from fvSchemes
fvSchemes (const fvSchemes &)=delete
void operator= (const fvSchemes &)=delete
fvSchemes (const objectRegistry &obr, IOobjectOption::readOption rOpt, const word &dictName, const dictionary *fallback=nullptr)
fvSchemes (const objectRegistry &obr, const word &dictName, const dictionary *fallback=nullptr)
fvSchemes (const objectRegistry &obr, IOobjectOption::readOption rOpt, const dictionary *fallback=nullptr)
fvSchemes (const objectRegistry &obr, const dictionary *fallback=nullptr)
fvSchemes (const objectRegistry &obr, const dictionary &dict)
Public Member Functions inherited from schemesLookup
schemesLookup (const objectRegistry &obr, IOobjectOption::readOption rOpt, const word &dictName, const dictionary *fallback=nullptr)
schemesLookup (const objectRegistry &obr, const word &dictName, const dictionary *fallback=nullptr)
const dictionary & schemesDict () const
bool steady () const noexcept
bool transient () const noexcept
ITstream & ddtScheme (const word &name) const
ITstream & d2dt2Scheme (const word &name) const
ITstream & interpolationScheme (const word &name) const
ITstream & divScheme (const word &name) const
ITstream & gradScheme (const word &name) const
ITstream & lnGradScheme (const word &name) const
ITstream & snGradScheme (const word &name) const
ITstream & laplacianScheme (const word &name) const
void setFluxRequired (const word &name) const
bool fluxRequired (const word &name) const
const dictionary & ddtSchemes () const noexcept
const dictionary & d2dt2Schemes () const noexcept
const dictionary & interpolationSchemes () const noexcept
const dictionary & divSchemes () const noexcept
const dictionary & gradSchemes () const noexcept
const dictionary & lnGradSchemes () const noexcept
const dictionary & snGradSchemes () const noexcept
const dictionary & laplacianSchemes () const noexcept
const dictionary & fluxRequired () const noexcept
dictionary & ddtSchemes () noexcept
dictionary & d2dt2Schemes () noexcept
dictionary & interpolationSchemes () noexcept
dictionary & divSchemes () noexcept
dictionary & gradSchemes () noexcept
dictionary & lnGradSchemes () noexcept
dictionary & snGradSchemes () noexcept
dictionary & laplacianSchemes () noexcept
dictionary & fluxRequired () noexcept
bool read ()
void writeDicts (Ostream &os) const
Public Member Functions inherited from IOdictionary
IOdictionary (const IOobject &io, const dictionary *fallback=nullptr)
IOdictionary (const IOobject &io, const dictionary &dict)
IOdictionary (const IOobject &io, const word &wantedType, const dictionary *fallback=nullptr)
IOdictionary (const IOobject &io, Istream &is)
virtual ~IOdictionary ()=default
virtual bool global () const
virtual fileName filePath () const
Public Member Functions inherited from baseIOdictionary
TypeName ("dictionary")
baseIOdictionary (const baseIOdictionary &)=default
baseIOdictionary (baseIOdictionary &&)=default
virtual ~baseIOdictionary ()=default
baseIOdictionary (const IOobject &io, const dictionary *fallback=nullptr)
baseIOdictionary (const IOobject &io, const dictionary &dict)
baseIOdictionary (const IOobject &io, Istream &is)
const word & name () const
virtual bool readData (Istream &)
virtual bool writeData (Ostream &) const
void operator= (const baseIOdictionary &rhs)
void operator= (const dictionary &rhs)
Public Member Functions inherited from dictionary
ClassName ("dictionary")
dictionary ()
dictionary (const fileName &name)
dictionary (const fileName &name, const dictionary &parentDict, Istream &is, bool keepHeader=false)
dictionary (Istream &is)
dictionary (Istream &is, bool keepHeader)
dictionary (const dictionary &parentDict, const dictionary &dict)
dictionary (const dictionary &dict)
dictionary (const dictionary *dict)
dictionary (const dictionary &parentDict, dictionary &&dict)
dictionary (dictionary &&dict)
autoPtr< dictionary > clone () const
virtual ~dictionary ()
const fileName & name () const noexcept
fileName & name () noexcept
word dictName () const
fileName relativeName (const bool caseTag=false) const
bool isNullDict () const noexcept
const dictionary & parent () const noexcept
const dictionary & topDict () const
label startLineNumber () const
label endLineNumber () const
SHA1Digest digest () const
tokenList tokens () const
const entry * findEntry (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
entry * findEntry (const word &keyword, enum keyType::option matchOpt=keyType::REGEX)
bool found (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
const entry * findScoped (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
const dictionary * findDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
dictionary * findDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX)
bool isDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
const entry & lookupEntry (const word &keyword, enum keyType::option matchOpt) const
ITstream & lookup (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
template<class T >
T get (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
template<class T >
T getOrDefault (const word &keyword, const T &deflt, enum keyType::option matchOpt=keyType::REGEX) const
template<class T >
T getOrAdd (const word &keyword, const T &deflt, enum keyType::option matchOpt=keyType::REGEX)
template<class T >
bool readEntry (const word &keyword, T &val, enum keyType::option matchOpt=keyType::REGEX, IOobjectOption::readOption readOpt=IOobjectOption::MUST_READ) const
template<class T >
bool readIfPresent (const word &keyword, T &val, enum keyType::option matchOpt=keyType::REGEX) const
template<class T , class Predicate >
T getCheck (const word &keyword, const Predicate &pred, enum keyType::option matchOpt=keyType::REGEX) const
template<class T , class Predicate >
T getCheckOrDefault (const word &keyword, const T &deflt, const Predicate &pred, enum keyType::option matchOpt=keyType::REGEX) const
template<class T , class Predicate >
T getCheckOrAdd (const word &keyword, const T &deflt, const Predicate &pred, enum keyType::option matchOpt=keyType::REGEX)
template<class T , class Predicate >
bool readCheck (const word &keyword, T &val, const Predicate &pred, enum keyType::option matchOpt=keyType::REGEX, IOobjectOption::readOption readOpt=IOobjectOption::MUST_READ) const
template<class T , class Predicate >
bool readCheckIfPresent (const word &keyword, T &val, const Predicate &pred, enum keyType::option matchOpt=keyType::REGEX) const
const dictionary & subDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
dictionary & subDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX)
dictionary & subDictOrAdd (const word &keyword, enum keyType::option matchOpt=keyType::REGEX)
dictionary subOrEmptyDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX, const bool mandatory=false) const
const dictionary & optionalSubDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
wordList toc () const
wordList sortedToc () const
template<class Compare >
wordList sortedToc (const Compare &comp) const
List< keyType > keys (bool patterns=false) const
bool substituteKeyword (const word &keyword, bool mergeEntry=false)
bool substituteScopedKeyword (const word &keyword, bool mergeEntry=false)
entry * add (entry *entryPtr, bool mergeEntry=false)
entry * add (const entry &e, bool mergeEntry=false)
entry * add (const keyType &k, const word &v, bool overwrite=false)
entry * add (const keyType &k, const string &v, bool overwrite=false)
entry * add (const keyType &k, const label v, bool overwrite=false)
entry * add (const keyType &k, const scalar v, bool overwrite=false)
entry * add (const keyType &k, const dictionary &d, bool mergeEntry=false)
template<class T >
entry * add (const keyType &k, const T &v, bool overwrite=false)
entry * set (entry *entryPtr)
entry * set (const entry &e)
entry * set (const keyType &k, const dictionary &v)
template<class T >
entry * set (const keyType &k, const T &v)
bool remove (const word &keyword)
bool changeKeyword (const keyType &oldKeyword, const keyType &newKeyword, bool overwrite=false)
bool merge (const dictionary &dict)
void clear ()
void transfer (dictionary &dict)
void checkITstream (const ITstream &is, const word &keyword) const
bool read (Istream &is)
bool read (Istream &is, bool keepHeader)
void writeEntry (Ostream &os) const
void writeEntry (const keyType &keyword, Ostream &os) const
void writeEntries (Ostream &os, const bool extraNewLine=false) const
void write (Ostream &os, const bool subDict=true) const
const_searcher csearch (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
const_searcher search (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
searcher search (const word &keyword, enum keyType::option matchOpt=keyType::REGEX)
const_searcher csearchScoped (const word &keyword, enum keyType::option matchOpt) const
const_searcher searchScoped (const word &keyword, enum keyType::option matchOpt) const
searcher searchScoped (const word &keyword, enum keyType::option matchOpt)
const dictionary * cfindScopedDict (const fileName &dictPath) const
const dictionary * findScopedDict (const fileName &dictPath) const
dictionary * findScopedDict (const fileName &dictPath)
dictionary * makeScopedDict (const fileName &dictPath)
const_searcher csearchCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, enum keyType::option matchOpt=keyType::REGEX) const
const entry * findCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, enum keyType::option matchOpt) const
bool foundCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, enum keyType::option matchOpt=keyType::REGEX) const
const entry & lookupEntryCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, enum keyType::option matchOpt) const
ITstream & lookupCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, enum keyType::option matchOpt=keyType::REGEX) const
template<class T >
T getCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, enum keyType::option matchOpt=keyType::REGEX) const
template<class T >
T getOrDefaultCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, const T &deflt, enum keyType::option matchOpt=keyType::REGEX) const
template<class T >
bool readCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, T &val, enum keyType::option matchOpt=keyType::REGEX, IOobjectOption::readOption readOpt=IOobjectOption::MUST_READ) const
template<class T >
bool readIfPresentCompat (const word &keyword, std::initializer_list< std::pair< const char *, int > > compat, T &val, enum keyType::option matchOpt=keyType::REGEX) const
void operator= (const dictionary &rhs)
void operator+= (const dictionary &rhs)
void operator|= (const dictionary &rhs)
void operator<<= (const dictionary &rhs)
bool getBool (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Same as get< bool >(const word&, keyType::option)
label getLabel (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Same as get< label >(const word&, keyType::option)
scalar getScalar (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Same as get< scalar >(const word&, keyType::option)
string getString (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Same as get< string >(const word&, keyType::option)
word getWord (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Same as get< word >(const word&, keyType::option)
fileName getFileName (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Same as get< fileName >(const word&, keyType::option)
template<class T >
T lookupOrDefault (const word &keyword, const T &deflt, enum keyType::option matchOpt=keyType::REGEX) const
template<class T >
T lookupOrAddDefault (const word &keyword, const T &deflt, enum keyType::option matchOpt=keyType::REGEX)
ITstream & operator[] (const word &keyword) const
bool found (const word &keyword, bool recursive, bool patternMatch=true) const
entry * lookupEntryPtr (const word &keyword, bool recursive, bool patternMatch)
const entry * lookupEntryPtr (const word &keyword, bool recursive, bool patternMatch) const
const entry * lookupScopedEntryPtr (const word &keyword, bool recursive, bool patternMatch) const
const dictionary * subDictPtr (const word &keyword) const
dictionary * subDictPtr (const word &keyword)
const entry & lookupEntry (const word &keyword, bool recursive, bool patternMatch) const
ITstream & lookup (const word &keyword, bool recursive, bool patternMatch=true) const
template<class T >
T lookupOrDefault (const word &keyword, const T &deflt, bool recursive, bool patternMatch=true) const
template<class T >
T lookupOrAddDefault (const word &keyword, const T &deflt, bool recursive, bool patternMatch=true)
template<class T >
bool readIfPresent (const word &keyword, T &val, bool recursive, bool patternMatch=true) const
template<class T >
T lookupType (const word &keyword, bool recursive=false, bool patternMatch=true) const
template<class Compare >
Foam::wordList sortedToc (const Compare &comp) const
template<class T >
Foam::entry * add (const keyType &k, const T &v, bool overwrite)
template<class T >
Foam::entry * set (const keyType &k, const T &v)
Public Member Functions inherited from ILList< LListBase, T >
ILList ()=default
ILList (T *item)
ILList (Istream &is)
ILList (const ILList< LListBase, T > &lst)
ILList (ILList< LListBase, T > &&lst)
template<class CloneArg >
ILList (const ILList< LListBase, T > &lst, const CloneArg &cloneArg)
template<class INew >
ILList (Istream &is, const INew &inew)
~ILList ()
void clear ()
void pop_front (label n=1)
bool erase (T *item)
void transfer (ILList< LListBase, T > &lst)
void operator= (const ILList< LListBase, T > &lst)
void operator= (ILList< LListBase, T > &&lst)
Public Member Functions inherited from UILList< LListBase, T >
UILList ()=default
UILList (T *item)
UILList (const UILList< LListBase, T > &list)
T * front ()
const T * front () const
T * back ()
const T * back () const
T * removeHead ()
T * remove (T *item)
T * remove (iterator &iter)
void operator= (const UILList< LListBase, T > &lst)
bool operator== (const UILList< LListBase, T > &lst) const
bool operator!= (const UILList< LListBase, T > &lst) const
Ostream & writeList (Ostream &os, const label shortLen=0) const
iterator begin ()
const_iterator cbegin () const
reverse_iterator rbegin ()
const_reverse_iterator crbegin () const
const_iterator begin () const
const_reverse_iterator rbegin () const
const iterator & end ()
const const_iterator & cend () const
const reverse_iterator & rend ()
const const_reverse_iterator & crend () const
const const_iterator & end () const
const const_reverse_iterator & rend () const
T * first ()
const T * first () const
T * last ()
const T * last () const
Public Member Functions inherited from surfaceInterpolation
ClassName ("surfaceInterpolation")
surfaceInterpolation (const fvMesh &)
virtual ~surfaceInterpolation ()
virtual const fvGeometryScheme & geometry () const
void geometry (tmp< fvGeometryScheme > &)
virtual const surfaceScalarField & weights () const
virtual const surfaceScalarField & deltaCoeffs () const
virtual const surfaceScalarField & nonOrthDeltaCoeffs () const
virtual const surfaceVectorField & nonOrthCorrectionVectors () const
bool hasWeights () const noexcept
Public Member Functions inherited from fvSolution
fvSolution (const fvSolution &)=delete
void operator= (const fvSolution &)=delete
fvSolution (const objectRegistry &obr, IOobjectOption::readOption rOpt, const word &dictName, const dictionary *fallback=nullptr)
fvSolution (const objectRegistry &obr, const word &dictName, const dictionary *fallback=nullptr)
fvSolution (const objectRegistry &obr, IOobjectOption::readOption rOpt, const dictionary *fallback=nullptr)
fvSolution (const objectRegistry &obr, const dictionary *fallback=nullptr)
fvSolution (const objectRegistry &obr, const dictionary &dict)
Public Member Functions inherited from solution
solution (const objectRegistry &obr, IOobjectOption::readOption rOpt, const fileName &dictName, const dictionary *fallback=nullptr)
solution (const objectRegistry &obr, const fileName &dictName, const dictionary *fallback=nullptr)
virtual ~solution ()
bool cache (const word &name) const
bool relaxField (const word &name) const
bool relaxEquation (const word &name) const
scalar fieldRelaxationFactor (const word &name) const
scalar equationRelaxationFactor (const word &name) const
const dictionary & solutionDict () const
const dictionary & solverDict (const word &name) const
const dictionary & solver (const word &name) const
bool read ()
Public Member Functions inherited from data
data (const word &name, const objectRegistry &obr, const dictionary *content=nullptr)
data (const objectRegistry &obr)
data (const word &name, const objectRegistry &obr, const dictionary &dict)
data (const objectRegistry &obr, const dictionary &dict)
const dictionary & solverPerformanceDict () const
bool isFirstIteration () const
bool isFinalIteration () const
void isFirstIteration (bool on)
void isFinalIteration (bool on)
template<class Type >
void setSolverPerformance (const word &name, const SolverPerformance< Type > &sp) const
template<class Type >
void setSolverPerformance (const SolverPerformance< Type > &sp) const
Static Public Member Functions
static autoPtr< dynamicFvMesh > New (const IOobject &io)
static autoPtr< dynamicFvMesh > New (const argList &args, const Time &runTime)
Static Public Member Functions inherited from polyMesh
static const word & regionName (const word &region)
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *p)
template<class Type >
static Type & store (autoPtr< Type > &ptr)
template<class Type >
static Type & store (autoPtr< Type > &&ptr)
template<class Type >
static Type & store (refPtr< Type > &ptr)
template<class Type >
static Type & store (refPtr< Type > &&ptr)
template<class Type >
static Type & store (tmp< Type > &ptr)
template<class Type >
static Type & store (tmp< Type > &&ptr)
Static Public Member Functions inherited from IOobject
static bool bannerEnabled () noexcept
static bool bannerEnabled (bool on) noexcept
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
template<class StringType >
static word groupName (StringType base, const word &group)
static word group (const word &name)
static word member (const word &name)
static word scopedName (const std::string &scope, const word &name)
static IOobject selectIO (const IOobject &io, const fileName &altFile, const word &ioName="")
static Ostream & writeBanner (Ostream &os, const bool noSyntaxHint=false)
static Ostream & writeDivider (Ostream &os)
static Ostream & writeEndDivider (Ostream &os)
Static Public Member Functions inherited from IOobjectOption
static bool isAnyRead (readOption opt) noexcept
static bool isReadRequired (readOption opt) noexcept
static bool isReadOptional (readOption opt) noexcept
static readOption lazierRead (readOption opt) noexcept
Static Public Member Functions inherited from HashTableCore
static label canonicalSize (const label requested_size)
Static Public Member Functions inherited from primitiveMesh
static void calcCells (cellList &, const labelUList &own, const labelUList &nei, const label nCells=-1)
static bool calcPointOrder (label &nInternalPoints, labelList &pointMap, const faceList &, const label nInternalFaces, const label nPoints)
static scalar setClosedThreshold (const scalar)
static scalar setAspectThreshold (const scalar)
static scalar setNonOrthThreshold (const scalar)
static scalar setSkewThreshold (const scalar)
Static Public Member Functions inherited from IOdictionary
static dictionary readContents (const IOobject &io)
Static Public Member Functions inherited from dictionary
static int reportOptional () noexcept
static int reportOptional (const int level) noexcept
static autoPtr< dictionary > New (Istream &is)
Static Public Member Functions inherited from solution
static label upgradeSolverDict (dictionary &dict, const bool verbose=true)
template<class FieldType >
static void cachePrintMessage (const char *message, const word &name, const FieldType &vf)
Additional Inherited Members
Public Types inherited from fvMesh
typedef fvMesh Mesh
typedef fvBoundaryMesh BoundaryMesh
Public Types inherited from polyMesh
enum readUpdateState { UNCHANGED , POINTS_MOVED , TOPO_CHANGE , TOPO_PATCH_CHANGE }
enum cellDecomposition { FACE_PLANES , FACE_CENTRE_TRIS , FACE_DIAG_TRIS , CELL_TETS }
typedef polyMesh Mesh
typedef polyBoundaryMesh BoundaryMesh
Public Types inherited from IOobject
enum objectState : char { GOOD , BAD }
enum fileCheckTypes : char { timeStamp , timeStampMaster , inotify , inotifyMaster }
Public Types inherited from IOobjectOption
enum readOption : unsigned char {
NO_READ = 0 , MUST_READ = 0x1 , READ_MODIFIED = 0x3 , MUST_READ_IF_MODIFIED = 0x3 ,
LAZY_READ = 0x4 , READ_IF_PRESENT = 0x4
}
enum writeOption : unsigned char { NO_WRITE = 0 , AUTO_WRITE = 0x10 }
enum registerOption : unsigned char { NO_REGISTER = 0 , REGISTER = 1 }
Public Types inherited from HashTable< regIOobject * >
typedef HashTable< regIOobject *, word, Foam::Hash< word > > this_type
typedef std::conditional< std::is_same< Foam::zero, typenamestd::remove_cv< regIOobject * >::type >::value, Detail::HashTableSingle< word >, Detail::HashTablePair< word, regIOobject * > >::type node_type
typedef word key_type
typedef regIOobject * mapped_type
typedef regIOobject * value_type
typedef Foam::Hash< word > hasher
typedef regIOobject * * pointer
typedef regIOobject * & reference
typedef const regIOobject * * const_pointer
typedef const regIOobject * & const_reference
typedef label difference_type
typedef label size_type
using key_iterator = key_iterator_base< iterator >
using const_key_iterator = key_iterator_base< const_iterator >
Public Types inherited from dictionary
typedef Searcher< true > const_searcher
typedef Searcher< false > searcher
Public Types inherited from UILList< LListBase, T >
typedef T value_type
typedef T * pointer
typedef const T * const_pointer
typedef T & reference
typedef const T & const_reference
typedef label size_type
typedef label difference_type
using base_iterator = typename LListBase::iterator
using const_base_iterator = typename LListBase::const_iterator
Public Attributes inherited from dictionary
friend const_searcher
friend searcher
Static Public Attributes inherited from polyMesh
static word defaultRegion = "region0"
static word meshSubDir = "polyMesh"
Static Public Attributes inherited from IOobject
static const Enum< fileCheckTypes > fileCheckTypesNames
static char scopeSeparator
static fileCheckTypes fileModificationChecking
static float fileModificationSkew
static int maxFileModificationPolls
Static Public Attributes inherited from HashTableCore
static const label maxTableSize
Static Public Attributes inherited from primitiveMesh
static const unsigned cellsPerEdge_ = 4
static const unsigned cellsPerPoint_ = 8
static const unsigned facesPerCell_ = 6
static const unsigned facesPerEdge_ = 4
static const unsigned facesPerPoint_ = 12
static const unsigned edgesPerCell_ = 12
static const unsigned edgesPerFace_ = 4
static const unsigned edgesPerPoint_ = 6
static const unsigned pointsPerCell_ = 8
static const unsigned pointsPerFace_ = 4
Static Public Attributes inherited from schemesLookup
static int debug
Static Public Attributes inherited from dictionary
static int writeOptionalEntries
static const dictionary null
static refPtr< OSstream > reportingOutput
Static Public Attributes inherited from solution
static int debug
Protected Member Functions inherited from fvMesh
void clearGeomNotOldVol ()
void updateGeomNotOldVol ()
void clearGeom ()
void clearAddressing (const bool isMeshUpdate=false)
void clearOutLocal ()
void storeOldVol (const scalarField &)
void makeSf () const
void makeMagSf () const
void makeC () const
void makeCf () const
fvMesh (const fvMesh &)=delete
void operator= (const fvMesh &)=delete
Protected Member Functions inherited from regIOobject
bool readHeaderOk (const IOstreamOption::streamFormat fmt, const word &typeName)
Protected Member Functions inherited from IOobject
void setBad (const string &s)
Protected Member Functions inherited from primitiveMesh
void calcFaceCentresAndAreas () const
void calcCellCentresAndVols () const
void calcEdgeVectors () const
bool checkDuplicateFaces (const label, const Map< label > &, label &nBaffleFaces, labelHashSet *) const
bool checkCommonOrder (const label, const Map< label > &, labelHashSet *) const
bool checkClosedBoundary (const vectorField &areas, const bool report, const bitSet &internalOrCoupledFaces) const
bool checkClosedCells (const vectorField &faceAreas, const scalarField &cellVolumes, const bool report, labelHashSet *setPtr, labelHashSet *aspectSetPtr, const Vector< label > &meshD) const
bool checkFaceAreas (const vectorField &faceAreas, const bool report, const bool detailedReport, labelHashSet *setPtr) const
bool checkCellVolumes (const scalarField &vols, const bool report, const bool detailedReport, labelHashSet *setPtr) const
bool checkFaceOrthogonality (const vectorField &fAreas, const vectorField &cellCtrs, const bool report, labelHashSet *setPtr) const
bool checkFacePyramids (const pointField &points, const vectorField &ctrs, const bool report, const bool detailedReport, const scalar minPyrVol, labelHashSet *setPtr) const
bool checkFaceSkewness (const pointField &points, const vectorField &fCtrs, const vectorField &fAreas, const vectorField &cellCtrs, const bool report, labelHashSet *setPtr) const
bool checkFaceAngles (const pointField &points, const vectorField &faceAreas, const bool report, const scalar maxDeg, labelHashSet *setPtr) const
bool checkFaceFlatness (const pointField &points, const vectorField &faceCentres, const vectorField &faceAreas, const bool report, const scalar warnFlatness, labelHashSet *setPtr) const
bool checkConcaveCells (const vectorField &fAreas, const pointField &fCentres, const bool report, labelHashSet *setPtr) const
primitiveMesh ()
Protected Member Functions inherited from surfaceInterpolation
void clearOut ()
Static Protected Member Functions inherited from IOobject
static void writeHeaderContent (Ostream &os, const IOobject &io, const word &objectType, const dictionary *metaDataDict=nullptr)
static void writeHeaderContent (dictionary &dict, const IOobject &io, const word &objectType, IOstreamOption streamOpt, const dictionary *metaDataDict=nullptr)
Protected Attributes inherited from fvMesh
fvBoundaryMesh boundary_
fvMeshLduAddressing * lduPtr_
label curTimeIndex_
SlicedDimensionedField< scalar, volMesh > * VPtr_
DimensionedField< scalar, volMesh > * V0Ptr_
DimensionedField< scalar, volMesh > * V00Ptr_
slicedSurfaceVectorField * SfPtr_
surfaceScalarField * magSfPtr_
slicedVolVectorField * CPtr_
slicedSurfaceVectorField * CfPtr_
surfaceScalarField * phiPtr_
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
Static Protected Attributes inherited from primitiveMesh
static scalar closedThreshold_ = 1.0e-6
static scalar aspectThreshold_ = 1000
static scalar nonOrthThreshold_ = 70
static scalar skewThreshold_ = 4
static scalar planarCosAngle_ = 1.0e-6
Detailed Description
Abstract base class for geometry and/or topology changing fvMesh.
Supports optional update controls that may be used by custom solvers:
Property Description Required Default
updateControl See time controls below no timeStep
updateInterval Steps/time between update phases no 1
See also
Foam::timeControl
Source files
dynamicFvMesh.H
dynamicFvMesh.C
dynamicFvMeshNew.C
Definition at line 74 of file dynamicFvMesh.H.
Constructor & Destructor Documentation
dynamicFvMesh() [1/4]
dynamicFvMesh (const IOobject & io, const bool doInit = true) explicit
Definition at line 72 of file dynamicFvMesh.C.
References dynamicFvMesh::init().
dynamicFvMesh() [2/4]
dynamicFvMesh (const IOobject & io, const Foam::zero , bool syncPar = true)
Definition at line 98 of file dynamicFvMesh.C.
dynamicFvMesh() [3/4]
dynamicFvMesh (const IOobject & io, pointField && points, faceList && faces, labelList && allOwner, labelList && allNeighbour, const bool syncPar = true)
Definition at line 112 of file dynamicFvMesh.C.
dynamicFvMesh() [4/4]
dynamicFvMesh (const IOobject & io, pointField && points, faceList && faces, cellList && cells, const bool syncPar = true)
Definition at line 137 of file dynamicFvMesh.C.
~dynamicFvMesh()
virtual ~dynamicFvMesh () virtual default
Member Function Documentation
TypeName()
TypeName ("dynamicFvMesh")
declareRunTimeSelectionTable() [1/2]
declareRunTimeSelectionTable (autoPtr , dynamicFvMesh , IOobject , (const IOobject &io) , (io))
declareRunTimeSelectionTable() [2/2]
declareRunTimeSelectionTable (autoPtr , dynamicFvMesh , doInit , (const IOobject &io, const bool doInit) , (io, doInit))
New() [1/2]
Foam::autoPtr< Foam::dynamicFvMesh > New (const IOobject & io) static
Definition at line 28 of file dynamicFvMeshNew.C.
References DebugInfo, dict, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::FatalIOError, FatalIOErrorInLookup, Foam::Info, io(), meshPtr, IOobjectOption::MUST_READ_IF_MODIFIED, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, and polyMesh::regionName().
New() [2/2]
Foam::autoPtr< Foam::dynamicFvMesh > New (const argList & args, const Time & runTime) static
Definition at line 114 of file dynamicFvMeshNew.C.
References FieldBase::allowConstructFromLargerSize, args, polyMesh::defaultRegion, argList::dryRun(), Foam::endl(), argList::found(), Foam::Info, IOobjectOption::MUST_READ, simplifiedDynamicFvMeshBase::New(), Foam::New(), functionObject::outputPrefix, runTime, Time::saNoWriteNow, Time::saWriteNow, Time::stopAt(), and Time::timeName().
init()
bool init (const bool doInit) virtual
Reimplemented from fvMesh.
Reimplemented in interfaceTrackingFvMesh, dynamicMotionSolverFvMesh, dynamicMotionSolverFvMeshAMI, dynamicMotionSolverListFvMesh, dynamicMultiMotionSolverFvMesh, dynamicRefineFvMesh, dynamicMotionSolverTopoFvMesh, and movingConeTopoFvMesh.
Definition at line 84 of file dynamicFvMesh.C.
References fvMesh::init().
Referenced by dynamicFvMesh::dynamicFvMesh(), dynamicMotionSolverFvMesh::init(), dynamicMotionSolverFvMeshAMI::init(), dynamicMultiMotionSolverFvMesh::init(), dynamicMotionSolverTopoFvMesh::init(), movingConeTopoFvMesh::init(), dynamicMotionSolverListFvMesh::init(), and faMeshTools::newMesh().
dynamic()
virtual bool dynamic () const inline virtual
Reimplemented from polyMesh.
Reimplemented in staticFvMesh.
Definition at line 187 of file dynamicFvMesh.H.
controlledUpdate()
bool controlledUpdate () virtual
Definition at line 160 of file dynamicFvMesh.C.
References addProfiling, Foam::Info, mesh, Foam::nl, and update().
update()
virtual bool update () pure virtual
Implemented in interfaceTrackingFvMesh, dynamicInkJetFvMesh, dynamicMotionSolverFvMesh, dynamicMotionSolverFvMeshAMI, dynamicMotionSolverListFvMesh, dynamicMultiMotionSolverFvMesh, dynamicRefineFvMesh, staticFvMesh, dynamicOversetFvMesh, staticOversetFvMesh, dynamicMotionSolverTopoFvMesh, linearValveFvMesh, linearValveLayersFvMesh, mixerFvMesh, movingConeTopoFvMesh, rawTopoChangerFvMesh, and topoChangerFvMesh.
Referenced by attachDetach::updateMesh(), perfectInterface::updateMesh(), and slidingInterface::updateMesh().
The documentation for this class was generated from the following files:
src/dynamicFvMesh/dynamicFvMesh/dynamicFvMesh.H
src/dynamicFvMesh/dynamicFvMesh/dynamicFvMesh.C
src/dynamicFvMesh/dynamicFvMesh/dynamicFvMeshNew.C