OpenFOAM: swirlInletVelocityFvPatchVectorField Class Reference
swirlInletVelocityFvPatchVectorField Class Reference
Boundary conditions » Inlet
This boundary condition describes an inlet vector boundary condition in swirl coordinates given a central axis, central point, axial, radial and tangential velocity profiles.
#include <swirlInletVelocityFvPatchVectorField.H>
Public Member Functions
TypeName ("swirlInletVelocity")
swirlInletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
swirlInletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
swirlInletVelocityFvPatchVectorField (const swirlInletVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
swirlInletVelocityFvPatchVectorField (const swirlInletVelocityFvPatchVectorField &)
virtual tmp< fvPatchVectorField > clone () const
swirlInletVelocityFvPatchVectorField (const swirlInletVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
This boundary condition describes an inlet vector boundary condition in swirl coordinates given a central axis, central point, axial, radial and tangential velocity profiles.
Usage
Property Description Required Default value
axis Axis of rotation yes
origin Origin of rotation yes
axialVelocity Axial velocity profile [m/s] yes
radialVelocity Radial velocity profile [m/s] yes
tangentialVelocity tangential velocity profile [m/s] yes
Example of the boundary condition specification:
    <patchName>
    {
        type            swirlInletVelocity;
        axis            (0 0 1);
        origin          (0 0 0);
        axialVelocity   constant 30;
        radialVelocity  constant 10;
        tangentialVelocity  constant 100;
    }
Note
The axialVelocity, radialVelocity and tangentialVelocity entries are Function1 types, able to describe time varying functions. The example above gives the usage for supplying constant values.
See also
Foam::fixedValueFvPatchField Foam::Function1Types
Source files
swirlInletVelocityFvPatchVectorField.H
swirlInletVelocityFvPatchVectorField.C
Definition at line 113 of file swirlInletVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
swirlInletVelocityFvPatchVectorField() [1/5]
swirlInletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Definition at line 27 of file swirlInletVelocityFvPatchVectorField.C.
swirlInletVelocityFvPatchVectorField() [2/5]
swirlInletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Definition at line 61 of file swirlInletVelocityFvPatchVectorField.C.
swirlInletVelocityFvPatchVectorField() [3/5]
swirlInletVelocityFvPatchVectorField (const swirlInletVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 43 of file swirlInletVelocityFvPatchVectorField.C.
swirlInletVelocityFvPatchVectorField() [4/5]
swirlInletVelocityFvPatchVectorField (const swirlInletVelocityFvPatchVectorField & ptf)
Definition at line 84 of file swirlInletVelocityFvPatchVectorField.C.
swirlInletVelocityFvPatchVectorField() [5/5]
swirlInletVelocityFvPatchVectorField (const swirlInletVelocityFvPatchVectorField & ptf, const DimensionedField< vector, volMesh > & iF)
Definition at line 99 of file swirlInletVelocityFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("swirlInletVelocity")
clone() [1/2]
virtual tmp< fvPatchVectorField > clone () const inline virtual
Definition at line 176 of file swirlInletVelocityFvPatchVectorField.H.
clone() [2/2]
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Definition at line 192 of file swirlInletVelocityFvPatchVectorField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 117 of file swirlInletVelocityFvPatchVectorField.C.
References Foam::mag(), and fvPatchField< Type >::updateCoeffs().
write()
void write (Ostream & os) const virtual
Definition at line 147 of file swirlInletVelocityFvPatchVectorField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntry(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/swirlInletVelocity/swirlInletVelocityFvPatchVectorField.H
src/finiteVolume/fields/fvPatchFields/derived/swirlInletVelocity/swirlInletVelocityFvPatchVectorField.C