OpenFOAM: basicSpecieMixture Class Reference
basicSpecieMixture Class Reference abstract
Thermophysical models » Reaction thermophysical models » Mixtures
Specialization of basicMultiComponentMixture for a mixture consisting of a number for molecular species.
#include <basicSpecieMixture.H>
Public Types
typedef basicSpecieMixture basicMixtureType
Public Types inherited from basicMultiComponentMixture
typedef basicMultiComponentMixture basicMixtureType
Public Types inherited from basicMixture
typedef basicMixture basicMixtureType
Public Member Functions
TypeName ("basicSpecieMixture")
basicSpecieMixture (const dictionary &thermoDict, const wordList &specieNames, const fvMesh &mesh, const word &phaseName)
virtual ~basicSpecieMixture ()=default
virtual scalar W (const label speciei) const =0
virtual scalar Hc (const label speciei) const =0
virtual scalar Cp (const label speciei, const scalar p, const scalar T) const =0
virtual scalar Cv (const label speciei, const scalar p, const scalar T) const =0
virtual scalar HE (const label speciei, const scalar p, const scalar T) const =0
virtual scalar Ha (const label speciei, const scalar p, const scalar T) const =0
virtual scalar Hs (const label speciei, const scalar p, const scalar T) const =0
virtual scalar S (const label speciei, const scalar p, const scalar T) const =0
virtual scalar Es (const label speciei, const scalar p, const scalar T) const =0
virtual scalar G (const label speciei, const scalar p, const scalar T) const =0
virtual scalar A (const label speciei, const scalar p, const scalar T) const =0
virtual scalar mu (const label speciei, const scalar p, const scalar T) const =0
virtual scalar kappa (const label speciei, const scalar p, const scalar T) const =0
virtual scalar alphah (const label speciei, const scalar p, const scalar T) const =0
virtual scalar rho (const label speciei, const scalar p, const scalar T) const =0
virtual autoPtr< speciesCompositionTable > specieComposition () const
Public Member Functions inherited from basicMultiComponentMixture
TypeName ("basicMultiComponentMixture")
basicMultiComponentMixture (const dictionary &thermoDict, const wordList &specieNames, const fvMesh &mesh, const word &phaseName)
virtual ~basicMultiComponentMixture ()=default
const speciesTable & species () const
bool contains (const word &specieName) const
bool active (label speciei) const
const List< bool > & active () const
void setActive (label speciei)
void setInactive (label speciei)
PtrList< volScalarField > & Y ()
const PtrList< volScalarField > & Y () const
volScalarField & Y (const label i)
const volScalarField & Y (const label i) const
volScalarField & Y (const word &specieName)
const volScalarField & Y (const word &specieName) const
Public Member Functions inherited from basicMixture
basicMixture (const dictionary &, const fvMesh &, const word &)
Additional Inherited Members
Protected Attributes inherited from basicMultiComponentMixture
speciesTable species_
List< bool > active_
PtrList< volScalarField > Y_
Detailed Description
Specialization of basicMultiComponentMixture for a mixture consisting of a number for molecular species.
Source files
basicSpecieMixture.H
basicSpecieMixture.C
Definition at line 54 of file basicSpecieMixture.H.
Member Typedef Documentation
basicMixtureType
typedef basicSpecieMixture basicMixtureType
Definition at line 65 of file basicSpecieMixture.H.
Constructor & Destructor Documentation
basicSpecieMixture()
basicSpecieMixture (const dictionary & thermoDict, const wordList & specieNames, const fvMesh & mesh, const word & phaseName)
Definition at line 33 of file basicSpecieMixture.C.
~basicSpecieMixture()
virtual ~basicSpecieMixture () virtual default
Member Function Documentation
TypeName()
TypeName ("basicSpecieMixture")
W()
virtual scalar W (const label speciei) const pure virtual
Referenced by ReactingMultiphaseParcel< ParcelType >::calcDevolatilisation(), ReactingParcel< ParcelType >::calcPhaseChange(), and MUCSheterogeneousRate< CloudType >::calculate().
Hc()
virtual scalar Hc (const label speciei) const pure virtual
Cp()
virtual scalar Cp (const label speciei, const scalar p, const scalar T) const pure virtual
Referenced by ReactingParcel< ParcelType >::calc(), ReactingMultiphaseParcel< ParcelType >::calcDevolatilisation(), and ReactingParcel< ParcelType >::calcPhaseChange().
Cv()
virtual scalar Cv (const label speciei, const scalar p, const scalar T) const pure virtual
HE()
virtual scalar HE (const label speciei, const scalar p, const scalar T) const pure virtual
Ha()
virtual scalar Ha (const label speciei, const scalar p, const scalar T) const pure virtual
Hs()
virtual scalar Hs (const label speciei, const scalar p, const scalar T) const pure virtual
Referenced by ReactingHeterogeneousParcel< ParcelType >::calc(), ReactingMultiphaseParcel< ParcelType >::calc(), ReactingParcel< ParcelType >::calc(), and enthalpySorptionFvPatchScalarField::patchSource().
S()
virtual scalar S (const label speciei, const scalar p, const scalar T) const pure virtual
Es()
virtual scalar Es (const label speciei, const scalar p, const scalar T) const pure virtual
G()
virtual scalar G (const label speciei, const scalar p, const scalar T) const pure virtual
A()
virtual scalar A (const label speciei, const scalar p, const scalar T) const pure virtual
mu()
virtual scalar mu (const label speciei, const scalar p, const scalar T) const pure virtual
kappa()
virtual scalar kappa (const label speciei, const scalar p, const scalar T) const pure virtual
alphah()
virtual scalar alphah (const label speciei, const scalar p, const scalar T) const pure virtual
rho()
virtual scalar rho (const label speciei, const scalar p, const scalar T) const pure virtual
Referenced by MUCSheterogeneousRate< CloudType >::calculate(), ReactingMultiphaseCloud< Foam::DSMCCloud >::ReactingMultiphaseCloud(), and ReactingHeterogeneousParcel< ParcelType >::updatedDeltaVolume().
specieComposition()
virtual autoPtr< speciesCompositionTable > specieComposition () const inline virtual
Reimplemented in reactingMixture< ThermoType >.
Definition at line 206 of file basicSpecieMixture.H.
References autoPtr< T >::New().
The documentation for this class was generated from the following files:
src/thermophysicalModels/reactionThermo/mixtures/basicSpecieMixture/basicSpecieMixture.H
src/thermophysicalModels/reactionThermo/mixtures/basicSpecieMixture/basicSpecieMixture.C