OpenFOAM: profilingPstream Class Reference
profilingPstream Class Reference
Timers and values for simple (simplistic) mpi-profiling. The entire class behaves as a singleton.
#include <profilingPstream.H>
Public Types
enum timingType : unsigned {
ALL_TO_ALL = 0 , BROADCAST , PROBE , REDUCE ,
GATHER , SCATTER , REQUEST , WAIT ,
OTHER , nCategories
}
typedef FixedList< double, timingType::nCategories > timingList
typedef FixedList< uint64_t, timingType::nCategories > countList
Static Public Member Functions
static bool active () noexcept
static void enable ()
static void disable () noexcept
static void reset ()
static bool suspend () noexcept
static void resume () noexcept
static timingList & times () noexcept
static countList & counts () noexcept
static double times (const timingType idx)
static uint64_t counts (const timingType idx)
static double elapsedTime ()
static void beginTiming ()
static void addTime (const timingType idx)
static void addBroadcastTime ()
static void addReduceTime ()
static void addProbeTime ()
static void addRequestTime ()
static void addWaitTime ()
static void addGatherTime ()
static void addScatterTime ()
static void addAllToAllTime ()
static void addOtherTime ()
static void report (const int reportLevel=0)
Detailed Description
Timers and values for simple (simplistic) mpi-profiling. The entire class behaves as a singleton.
Source files
profilingPstream.H
profilingPstream.C
Definition at line 49 of file profilingPstream.H.
Member Typedef Documentation
timingList
typedef FixedList<double, timingType::nCategories> timingList
Definition at line 71 of file profilingPstream.H.
countList
typedef FixedList<uint64_t, timingType::nCategories> countList
Definition at line 74 of file profilingPstream.H.
Member Enumeration Documentation
timingType
enum timingType : unsigned
Enumerator
ALL_TO_ALL
BROADCAST
PROBE
REDUCE
GATHER
SCATTER
REQUEST
WAIT
OTHER
nCategories
Definition at line 56 of file profilingPstream.H.
Member Function Documentation
active()
static bool active () inline static noexcept
Definition at line 101 of file profilingPstream.H.
enable()
void enable () static
Definition at line 38 of file profilingPstream.C.
Referenced by parProfiling::parProfiling(), and parProfilingSolver::solve().
disable()
void disable () static noexcept
Definition at line 50 of file profilingPstream.C.
Referenced by parProfiling::end(), and parProfiling::~parProfiling().
reset()
void reset () static
Definition at line 57 of file profilingPstream.C.
Referenced by parProfilingSolver::parProfilingSolver().
suspend()
static bool suspend () inline static noexcept
Definition at line 114 of file profilingPstream.H.
Referenced by parProfilingSolver::parProfilingSolver(), and parProfilingSolver::solve().
resume()
static void resume () inline static noexcept
Definition at line 122 of file profilingPstream.H.
times() [1/2]
static timingList & times () inline static noexcept
Definition at line 131 of file profilingPstream.H.
counts() [1/2]
static countList & counts () inline static noexcept
Definition at line 134 of file profilingPstream.H.
times() [2/2]
static double times (const timingType idx) inline static
Definition at line 137 of file profilingPstream.H.
counts() [2/2]
static uint64_t counts (const timingType idx) inline static
Definition at line 143 of file profilingPstream.H.
elapsedTime()
double elapsedTime () static
Definition at line 64 of file profilingPstream.C.
beginTiming()
static void beginTiming () inline static
Definition at line 152 of file profilingPstream.H.
addTime()
static void addTime (const timingType idx) inline static
Definition at line 161 of file profilingPstream.H.
Referenced by profilingPstream::addAllToAllTime(), profilingPstream::addBroadcastTime(), profilingPstream::addGatherTime(), profilingPstream::addOtherTime(), profilingPstream::addProbeTime(), profilingPstream::addReduceTime(), profilingPstream::addRequestTime(), profilingPstream::addScatterTime(), and profilingPstream::addWaitTime().
addBroadcastTime()
static void addBroadcastTime () inline static
Definition at line 171 of file profilingPstream.H.
References profilingPstream::addTime(), and profilingPstream::BROADCAST.
addReduceTime()
static void addReduceTime () inline static
Definition at line 177 of file profilingPstream.H.
References profilingPstream::addTime(), and profilingPstream::REDUCE.
addProbeTime()
static void addProbeTime () inline static
Definition at line 183 of file profilingPstream.H.
References profilingPstream::addTime(), and profilingPstream::PROBE.
addRequestTime()
static void addRequestTime () inline static
Definition at line 189 of file profilingPstream.H.
References profilingPstream::addTime(), and profilingPstream::REQUEST.
addWaitTime()
static void addWaitTime () inline static
Definition at line 195 of file profilingPstream.H.
References profilingPstream::addTime(), and profilingPstream::WAIT.
addGatherTime()
static void addGatherTime () inline static
Definition at line 201 of file profilingPstream.H.
References profilingPstream::addTime(), and profilingPstream::GATHER.
addScatterTime()
static void addScatterTime () inline static
Definition at line 207 of file profilingPstream.H.
References profilingPstream::addTime(), and profilingPstream::SCATTER.
addAllToAllTime()
static void addAllToAllTime () inline static
Definition at line 213 of file profilingPstream.H.
References profilingPstream::addTime(), and profilingPstream::ALL_TO_ALL.
addOtherTime()
static void addOtherTime () inline static
Definition at line 219 of file profilingPstream.H.
References profilingPstream::addTime(), and profilingPstream::OTHER.
report()
void report (const int reportLevel = 0) static
Definition at line 191 of file profilingPstream.C.
References UPstream::commWorld(), Foam::decrIndent(), Foam::extractValues(), UPtrList< T >::first(), Foam::incrIndent(), Foam::indent(), Foam::Info, UPstream::master(), UPstream::mpiGather(), Foam::nl, UPstream::nProcs(), os(), UPstream::parRun(), Foam::printTimingDetail(), PtrList< T >::resize(), and UPtrList< T >::size().
Referenced by parProfiling::report().
The documentation for this class was generated from the following files:
src/OpenFOAM/global/profiling/profilingPstream.H
src/OpenFOAM/global/profiling/profilingPstream.C