OpenFOAM: ParRunControl Class Reference
ParRunControl Class Reference
Helper class for initializing parallel jobs from the command arguments, storing 'dry-run' state etc. Also handles cleanup of parallel (or serial) jobs.
#include <parRun.H>
Public Member Functions
ParRunControl () noexcept
~ParRunControl ()
int dryRun () const noexcept
void incrDryRun (int level=1) noexcept
int dryRun (const int level) noexcept
int verbose () const noexcept
void incrVerbose (int level=1) noexcept
int verbose (const int level) noexcept
bool parRun () const noexcept
bool parRun (const bool on) noexcept
bool distributed () const noexcept
void distributed (bool on) noexcept
bool threads () const noexcept
void threads (bool on) noexcept
void runPar (int &argc, char **&argv)
Detailed Description
Helper class for initializing parallel jobs from the command arguments, storing 'dry-run' state etc. Also handles cleanup of parallel (or serial) jobs.
Note
In the meantime the class name may be slightly misleading.
Definition at line 48 of file parRun.H.
Constructor & Destructor Documentation
ParRunControl()
ParRunControl () inline noexcept
Definition at line 73 of file parRun.H.
~ParRunControl()
~ParRunControl () inline
Definition at line 84 of file parRun.H.
References Foam::endl(), Foam::Info, and UPstream::shutdown().
Member Function Documentation
dryRun() [1/2]
int dryRun () const inline noexcept
Definition at line 97 of file parRun.H.
incrDryRun()
void incrDryRun (int level = 1) inline noexcept
Definition at line 100 of file parRun.H.
Referenced by argList::argList().
dryRun() [2/2]
int dryRun (const int level) inline noexcept
Definition at line 103 of file parRun.H.
verbose() [1/2]
int verbose () const inline noexcept
Definition at line 111 of file parRun.H.
incrVerbose()
void incrVerbose (int level = 1) inline noexcept
Definition at line 114 of file parRun.H.
Referenced by argList::argList().
verbose() [2/2]
int verbose (const int level) inline noexcept
Definition at line 117 of file parRun.H.
parRun() [1/2]
bool parRun () const inline noexcept
Definition at line 128 of file parRun.H.
Referenced by argList::argList().
parRun() [2/2]
bool parRun (const bool on) inline noexcept
Definition at line 136 of file parRun.H.
distributed() [1/2]
bool distributed () const inline noexcept
Definition at line 144 of file parRun.H.
distributed() [2/2]
void distributed (bool on) inline noexcept
Definition at line 150 of file parRun.H.
threads() [1/2]
bool threads () const inline noexcept
Definition at line 156 of file parRun.H.
Referenced by argList::argList().
threads() [2/2]
void threads (bool on) inline noexcept
Definition at line 162 of file parRun.H.
runPar()
void runPar (int & argc, char **& argv) inline
Definition at line 168 of file parRun.H.
References Foam::endl(), UPstream::exit(), Foam::Info, and UPstream::init().
Referenced by argList::argList().
The documentation for this class was generated from the following file:
src/OpenFOAM/global/argList/parRun.H