OpenFOAM: edgeVertex Class Reference
edgeVertex Class Reference
Combines edge or vertex in single label. Used to specify cuts across cell circumference.
#include <edgeVertex.H>
Public Member Functions
edgeVertex (const polyMesh &mesh)
const polyMesh & mesh () const
bool isEdge (const label eVert) const
label getEdge (const label eVert) const
label getVertex (const label eVert) const
label vertToEVert (const label vertI) const
label edgeToEVert (const label edgeI) const
point coord (const label cut, const scalar weight) const
label cutPairToEdge (const label cut0, const label cut1) const
Ostream & writeCut (Ostream &os, const label cut, const scalar) const
Ostream & writeCuts (Ostream &os, const labelList &, const scalarField &) const
Static Public Member Functions
static void updateLabels (const labelList &map, List< refineCell > &)
static void updateLabels (const labelList &map, Map< label > &)
static void updateLabels (const labelList &map, labelHashSet &)
static bool isEdge (const primitiveMesh &mesh, const label eVert)
static label getEdge (const primitiveMesh &mesh, const label eVert)
static label getVertex (const primitiveMesh &mesh, const label eVert)
static label vertToEVert (const primitiveMesh &mesh, const label vertI)
static label edgeToEVert (const primitiveMesh &mesh, const label edgeI)
static point coord (const primitiveMesh &, const label cut, const scalar weight)
static label cutPairToEdge (const primitiveMesh &, const label cut0, const label cut1)
Detailed Description
Combines edge or vertex in single label. Used to specify cuts across cell circumference.
Source files
edgeVertex.H
edgeVertex.C
Definition at line 51 of file edgeVertex.H.
Constructor & Destructor Documentation
edgeVertex()
edgeVertex (const polyMesh & mesh) inline explicit
Definition at line 89 of file edgeVertex.H.
Member Function Documentation
updateLabels() [1/3]
void updateLabels (const labelList & map, List< refineCell > & refCells) static
Definition at line 29 of file edgeVertex.C.
References refineCell::cellNo(), refineCell::direction(), forAll, and PtrList< T >::setSize().
updateLabels() [2/3]
void updateLabels (const labelList & map, Map< label > & cellPairs) static
Definition at line 56 of file edgeVertex.C.
References Foam::endl(), forAllConstIters, UPtrList< T >::size(), and WarningInFunction.
updateLabels() [3/3]
void updateLabels (const labelList & map, labelHashSet & cells) static
Definition at line 119 of file edgeVertex.C.
References cells, and UPtrList< T >::size().
mesh()
const polyMesh & mesh () const inline
Definition at line 97 of file edgeVertex.H.
Referenced by cellCuts::cellCuts(), edgeVertex::edgeToEVert(), edgeVertex::getEdge(), edgeVertex::getVertex(), edgeVertex::isEdge(), cellLooper::New(), edgeVertex::vertToEVert(), and wallLayerCells::wallLayerCells().
isEdge() [1/2]
static bool isEdge (const primitiveMesh & mesh, const label eVert) inline static
Definition at line 106 of file edgeVertex.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and edgeVertex::mesh().
Referenced by edgeVertex::getEdge(), edgeVertex::getVertex(), and edgeVertex::isEdge().
isEdge() [2/2]
bool isEdge (const label eVert) const inline
Definition at line 119 of file edgeVertex.H.
References edgeVertex::isEdge().
getEdge() [1/2]
static label getEdge (const primitiveMesh & mesh, const label eVert) inline static
Definition at line 125 of file edgeVertex.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, edgeVertex::isEdge(), and edgeVertex::mesh().
Referenced by edgeVertex::getEdge().
getEdge() [2/2]
label getEdge (const label eVert) const inline
Definition at line 135 of file edgeVertex.H.
References edgeVertex::getEdge().
getVertex() [1/2]
static label getVertex (const primitiveMesh & mesh, const label eVert) inline static
Definition at line 141 of file edgeVertex.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, edgeVertex::isEdge(), and edgeVertex::mesh().
Referenced by edgeVertex::getVertex().
getVertex() [2/2]
label getVertex (const label eVert) const inline
Definition at line 151 of file edgeVertex.H.
References edgeVertex::getVertex().
vertToEVert() [1/2]
static label vertToEVert (const primitiveMesh & mesh, const label vertI) inline static
Definition at line 157 of file edgeVertex.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and edgeVertex::mesh().
Referenced by edgeVertex::vertToEVert().
vertToEVert() [2/2]
label vertToEVert (const label vertI) const inline
Definition at line 167 of file edgeVertex.H.
References edgeVertex::vertToEVert().
edgeToEVert() [1/2]
static label edgeToEVert (const primitiveMesh & mesh, const label edgeI) inline static
Definition at line 173 of file edgeVertex.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and edgeVertex::mesh().
Referenced by edgeVertex::edgeToEVert().
edgeToEVert() [2/2]
label edgeToEVert (const label edgeI) const inline
Definition at line 183 of file edgeVertex.H.
References edgeVertex::edgeToEVert().
coord() [1/2]
Foam::point coord (const primitiveMesh & mesh, const label cut, const scalar weight) static
Definition at line 162 of file edgeVertex.C.
References e, primitiveMesh::edges(), UList< T >::end(), Foam::getEdge(), mesh, polyMesh::points(), and pts.
Referenced by edgeVertex::coord().
coord() [2/2]
point coord (const label cut, const scalar weight) const inline
Definition at line 195 of file edgeVertex.H.
References edgeVertex::coord().
cutPairToEdge() [1/2]
Foam::label cutPairToEdge (const primitiveMesh & mesh, const label cut0, const label cut1) static
Definition at line 184 of file edgeVertex.C.
References Foam::meshTools::findEdge(), and mesh.
Referenced by edgeVertex::cutPairToEdge().
cutPairToEdge() [2/2]
label cutPairToEdge (const label cut0, const label cut1) const inline
Definition at line 207 of file edgeVertex.H.
References edgeVertex::cutPairToEdge().
writeCut()
Foam::Ostream & writeCut (Ostream & os, const label cut, const scalar weight) const
Definition at line 207 of file edgeVertex.C.
References e, primitiveMesh::edges(), Foam::getEdge(), mesh, and os().
writeCuts()
Foam::Ostream & writeCuts (Ostream & os, const labelList & cuts, const scalarField & weights) const
Definition at line 232 of file edgeVertex.C.
References forAll, and os().
The documentation for this class was generated from the following files:
src/dynamicMesh/meshCut/edgeVertex/edgeVertex.H
src/dynamicMesh/meshCut/edgeVertex/edgeVertex.C