OpenFOAM: boundaryMesh Class Reference
boundaryMesh Class Reference
Addressing for all faces on surface of mesh. Can either be read from polyMesh or from triSurface. Used for repatching existing meshes.
#include <boundaryMesh.H>
Public Member Functions
ClassName ("boundaryMesh")
boundaryMesh ()
~boundaryMesh ()=default
void clearOut ()
const bMesh & mesh () const
const PtrList< boundaryPatch > & patches () const
const labelList & meshFace () const
const pointField & featurePoints () const
const edgeList & featureEdges () const
const labelList & featureToEdge () const
const labelList & edgeToFeature () const
const labelListList & featureSegments () const
const labelList & extraEdges () const
void read (const polyMesh &)
void readTriSurface (const fileName &)
void writeTriSurface (const fileName &) const
labelList getNearest (const primitiveMesh &pMesh, const vector &searchSpan) const
void patchify (const labelList &nearest, const polyBoundaryMesh &oldPatches, polyMesh &newMesh) const
label whichPatch (const label facei) const
label findPatchID (const word &patchName) const
wordList patchNames () const
void addPatch (const word &patchName)
void deletePatch (const word &patchName)
void changePatchType (const word &patchName, const word &type)
void changeFaces (const labelList &patchIDs, labelList &oldToNew)
void setFeatureEdges (const scalar minCos)
void setExtraEdges (const label edgeI)
label getNTris (const label facei) const
label getNTris (const label startFacei, const label nFaces, labelList &nTris) const
void triangulate (const label startFacei, const label nFaces, const label totalNTris, labelList &triVerts) const
label getNPoints (const label startFacei, const label nFaces) const
void triangulateLocal (const label startFacei, const label nFaces, const label totalNTris, labelList &triVerts, labelList &localToGlobal) const
void markFaces (const labelList &protectedEdges, const label facei, boolList &visited) const
Detailed Description
Addressing for all faces on surface of mesh. Can either be read from polyMesh or from triSurface. Used for repatching existing meshes.
Source files
boundaryMesh.H
boundaryMesh.C
Definition at line 58 of file boundaryMesh.H.
Constructor & Destructor Documentation
boundaryMesh()
boundaryMesh ()
Definition at line 433 of file boundaryMesh.C.
~boundaryMesh()
~boundaryMesh () default
Member Function Documentation
ClassName()
ClassName ("boundaryMesh")
clearOut()
void clearOut ()
Definition at line 449 of file boundaryMesh.C.
mesh()
const bMesh & mesh () const inline
Definition at line 202 of file boundaryMesh.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Referenced by cyclicAMIPolyPatch::addAMIFaces(), faPatch::boundaryConnections(), faPatch::boundaryProcs(), faPatch::boundaryProcSizes(), cyclicAMIPolyPatch::canResetAMI(), fvPatch::Cf(), processorFaPatch::comm(), processorPolyPatch::comm(), cyclicAMIFvPatch::coupled(), cyclicAMIPointPatch::coupled(), faPatch::deltaCoeffs(), fvPatch::deltaCoeffs(), faPatch::edgeCentres(), faPatch::edgeLengths(), faPatch::magEdgeLengths(), fvPatch::magSf(), processorFaPatch::makeNonGlobalPatchPoints(), cyclicACMIFvPatch::movePoints(), cyclicAMIFvPatch::movePoints(), faPatch::ngbPolyPatchFaceNormals(), cyclicACMIPolyPatch::resetAMI(), cyclicAMIPolyPatch::resetAMI(), cyclicACMIPolyPatch::scalePatchFaceAreas(), cyclicACMIPolyPatch::scalePatchFaceAreas(), fvPatch::Sf(), faPatch::start(), cyclicAMIPolyPatch::surfPtr(), cyclicACMIPolyPatch::updateAreas(), faPatch::weights(), and fvPatch::weights().
patches()
const PtrList< boundaryPatch > & patches () const inline
Definition at line 213 of file boundaryMesh.H.
meshFace()
const labelList & meshFace () const inline
Definition at line 220 of file boundaryMesh.H.
featurePoints()
const pointField & featurePoints () const inline
Definition at line 226 of file boundaryMesh.H.
featureEdges()
const edgeList & featureEdges () const inline
Definition at line 232 of file boundaryMesh.H.
featureToEdge()
const labelList & featureToEdge () const inline
Definition at line 238 of file boundaryMesh.H.
edgeToFeature()
const labelList & edgeToFeature () const inline
Definition at line 244 of file boundaryMesh.H.
featureSegments()
const labelListList & featureSegments () const inline
Definition at line 250 of file boundaryMesh.H.
extraEdges()
const labelList & extraEdges () const inline
Definition at line 256 of file boundaryMesh.H.
read()
void read (const polyMesh & mesh)
Definition at line 455 of file boundaryMesh.C.
References polyMesh::boundaryMesh(), PtrList< T >::clear(), Foam::endl(), f(), forAll, mesh, primitiveMesh::nBoundaryFaces(), polyMesh::points(), Foam::Pout, pp(), PtrList< T >::resize(), PtrList< T >::set(), UPtrList< T >::size(), UList< T >::size(), and Foam::Zero.
readTriSurface()
void readTriSurface (const fileName & fName)
Definition at line 581 of file boundaryMesh.C.
References PtrList< T >::clear(), geometricSurfacePatch::defaultName(), UList< T >::empty(), geometricSurfacePatch::emptyType, Foam::endl(), forAll, PrimitivePatch< FaceList, PointField >::localFaces(), PrimitivePatch< FaceList, PointField >::localPoints(), triSurface::patches(), Foam::Pout, labelledTri::region(), PtrList< T >::resize(), PtrList< T >::set(), UPtrList< T >::size(), and UList< T >::size().
writeTriSurface()
void writeTriSurface (const fileName & fName) const
Definition at line 749 of file boundaryMesh.C.
References forAll, mesh, points, and triSurface::write().
getNearest()
Foam::labelList getNearest (const primitiveMesh & pMesh, const vector & searchSpan) const
Definition at line 838 of file boundaryMesh.C.
References PtrList< T >::append(), e, Foam::endl(), f(), primitiveMesh::faceAreas(), primitiveMesh::faceCentres(), primitiveMesh::faces(), forAll, Foam::mag(), Foam::magSqr(), Foam::max(), mesh, n, primitiveMesh::nBoundaryFaces(), primitiveMesh::nInternalFaces(), points, primitiveMesh::points(), Foam::Pout, Foam::sign(), and UPtrList< T >::size().
patchify()
void patchify (const labelList & nearest, const polyBoundaryMesh & oldPatches, polyMesh & newMesh) const
Definition at line 1091 of file boundaryMesh.C.
References PtrList< T >::append(), polyMesh::boundaryMesh(), PtrList< T >::clone(), Foam::endl(), forAll, primitiveMesh::nBoundaryFaces(), polyPatch::New(), primitiveMesh::nInternalFaces(), pFaces, Foam::Pout, PtrList< T >::set(), and UPtrList< T >::size().
whichPatch()
Foam::label whichPatch (const label facei) const
Definition at line 1517 of file boundaryMesh.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, and UPtrList< T >::size().
findPatchID()
Foam::label findPatchID (const word & patchName) const
Definition at line 1538 of file boundaryMesh.C.
References forAll, and Foam::name().
patchNames()
Foam::wordList patchNames () const
Definition at line 268 of file boundaryMesh.C.
References forAll.
addPatch()
void addPatch (const word & patchName)
Definition at line 1552 of file boundaryMesh.C.
References Foam::endl(), forAll, mesh, Foam::Pout, PtrList< T >::setSize(), and UPtrList< T >::size().
deletePatch()
void deletePatch (const word & patchName)
Definition at line 1589 of file boundaryMesh.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::Pout, PtrList< T >::set(), and UPtrList< T >::size().
changePatchType()
void changePatchType (const word & patchName, const word & type)
Definition at line 1642 of file boundaryMesh.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, PtrList< T >::set(), and UPtrList< T >::size().
changeFaces()
void changeFaces (const labelList & patchIDs, labelList & oldToNew)
Definition at line 1693 of file boundaryMesh.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, mesh, patchID, patchIDs(), points, Foam::Pout, PtrList< T >::set(), PtrList< T >::setSize(), HashTable< T, Key, Hash >::size(), UPtrList< T >::size(), and Foam::Zero.
setFeatureEdges()
void setFeatureEdges (const scalar minCos)
Definition at line 1301 of file boundaryMesh.C.
References PtrList< T >::append(), e, primitiveMesh::edgeFaces(), primitiveMesh::edges(), UList< T >::end(), forAll, mesh, nPoints, polyMesh::points(), PtrList< T >::setSize(), and UPtrList< T >::size().
setExtraEdges()
void setExtraEdges (const label edgeI)
Definition at line 1502 of file boundaryMesh.C.
References mesh.
getNTris() [1/2]
Foam::label getNTris (const label facei) const
Definition at line 1813 of file boundaryMesh.C.
References f(), mesh, and points.
getNTris() [2/2]
Foam::label getNTris (const label startFacei, const label nFaces, labelList & nTris) const
Definition at line 1821 of file boundaryMesh.C.
References PtrList< T >::setSize().
triangulate()
void triangulate (const label startFacei, const label nFaces, const label totalNTris, labelList & triVerts) const
Definition at line 1846 of file boundaryMesh.C.
References f(), forAll, mesh, points, and PtrList< T >::setSize().
getNPoints()
Foam::label getNPoints (const label startFacei, const label nFaces) const
Definition at line 1887 of file boundaryMesh.C.
References mesh, and points.
triangulateLocal()
void triangulateLocal (const label startFacei, const label nFaces, const label totalNTris, labelList & triVerts, labelList & localToGlobal) const
Definition at line 1904 of file boundaryMesh.C.
References f(), forAll, mesh, points, and PtrList< T >::setSize().
markFaces()
void markFaces (const labelList & protectedEdges, const label facei, boolList & visited) const
Definition at line 1953 of file boundaryMesh.C.
References forAll, mesh, and PtrList< T >::setSize().
The documentation for this class was generated from the following files:
src/dynamicMesh/boundaryMesh/boundaryMesh.H
src/dynamicMesh/boundaryMesh/boundaryMesh.C