OpenFOAM: rotatingWallVelocityFvPatchVectorField Class Reference
rotatingWallVelocityFvPatchVectorField Class Reference
Boundary conditions » Wall | Boundary conditions » Generic
This boundary condition provides a rotational velocity condition.
#include <rotatingWallVelocityFvPatchVectorField.H>
Public Member Functions
TypeName ("rotatingWallVelocity")
rotatingWallVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
rotatingWallVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
rotatingWallVelocityFvPatchVectorField (const rotatingWallVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
rotatingWallVelocityFvPatchVectorField (const rotatingWallVelocityFvPatchVectorField &)
virtual tmp< fvPatchVectorField > clone () const
rotatingWallVelocityFvPatchVectorField (const rotatingWallVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
const vector & origin () const
const vector & axis () const
vector & origin ()
vector & axis ()
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
This boundary condition provides a rotational velocity condition.
Usage
Property Description Required Default value
origin origin of rotation in Cartesian coordinates yes
axis axis of rotation yes
omega angular velocty of the frame [rad/s] yes
Example of the boundary condition specification:
    <patchName>
    {
        type            rotatingWallVelocity;
        origin          (0 0 0);
        axis            (0 0 1);
        omega           100;
    }
The omega entry is a Function1 of time, see Foam::Function1Types.
See also
Foam::fixedValueFvPatchField Foam::Function1Types
Source files
rotatingWallVelocityFvPatchVectorField.H
rotatingWallVelocityFvPatchVectorField.C
Definition at line 95 of file rotatingWallVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
rotatingWallVelocityFvPatchVectorField() [1/5]
rotatingWallVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Definition at line 29 of file rotatingWallVelocityFvPatchVectorField.C.
rotatingWallVelocityFvPatchVectorField() [2/5]
rotatingWallVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Definition at line 43 of file rotatingWallVelocityFvPatchVectorField.C.
References dict, and rotatingWallVelocityFvPatchVectorField::updateCoeffs().
rotatingWallVelocityFvPatchVectorField() [3/5]
rotatingWallVelocityFvPatchVectorField (const rotatingWallVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 64 of file rotatingWallVelocityFvPatchVectorField.C.
rotatingWallVelocityFvPatchVectorField() [4/5]
rotatingWallVelocityFvPatchVectorField (const rotatingWallVelocityFvPatchVectorField & rwvpvf)
Definition at line 80 of file rotatingWallVelocityFvPatchVectorField.C.
rotatingWallVelocityFvPatchVectorField() [5/5]
rotatingWallVelocityFvPatchVectorField (const rotatingWallVelocityFvPatchVectorField & rwvpvf, const DimensionedField< vector, volMesh > & iF)
Definition at line 93 of file rotatingWallVelocityFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("rotatingWallVelocity")
clone() [1/2]
virtual tmp< fvPatchVectorField > clone () const inline virtual
Definition at line 151 of file rotatingWallVelocityFvPatchVectorField.H.
clone() [2/2]
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Definition at line 167 of file rotatingWallVelocityFvPatchVectorField.H.
origin() [1/2]
const vector & origin () const inline
Definition at line 185 of file rotatingWallVelocityFvPatchVectorField.H.
axis() [1/2]
const vector & axis () const inline
Definition at line 191 of file rotatingWallVelocityFvPatchVectorField.H.
origin() [2/2]
vector & origin () inline
Definition at line 197 of file rotatingWallVelocityFvPatchVectorField.H.
axis() [2/2]
vector & axis () inline
Definition at line 203 of file rotatingWallVelocityFvPatchVectorField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 109 of file rotatingWallVelocityFvPatchVectorField.C.
References Foam::mag(), n, om, and Field< vector >::operator=().
Referenced by rotatingWallVelocityFvPatchVectorField::rotatingWallVelocityFvPatchVectorField().
write()
void write (Ostream & os) const virtual
Definition at line 134 of file rotatingWallVelocityFvPatchVectorField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntry(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/rotatingWallVelocity/rotatingWallVelocityFvPatchVectorField.H
src/finiteVolume/fields/fvPatchFields/derived/rotatingWallVelocity/rotatingWallVelocityFvPatchVectorField.C