OpenFOAM: fvFieldDecomposer::fieldsCache::privateCache Class Reference
fvFieldDecomposer::fieldsCache::privateCache Class Reference
Public Member Functions
label size () const noexcept
bool empty () const noexcept
void readAll (const fvMesh &mesh, const IOobjectList &objects)
void decomposeAll (const fvFieldDecomposer &decomposer, bool report) const
Static Public Member Functions
template<class GeoField >
static void decompose (const fvFieldDecomposer &decomposer, const PtrList< GeoField > &fields, bool report)
Public Attributes
PtrList< DimensionedField< scalar, volMesh > > scalarDimFields_
PtrList< GeometricField< scalar, fvPatchField, volMesh > > scalarVolFields_
PtrList< GeometricField< scalar, fvsPatchField, surfaceMesh > > scalarSurfFields_
PtrList< DimensionedField< vector, volMesh > > vectorDimFields_
PtrList< GeometricField< vector, fvPatchField, volMesh > > vectorVolFields_
PtrList< GeometricField< vector, fvsPatchField, surfaceMesh > > vectorSurfFields_
PtrList< DimensionedField< sphericalTensor, volMesh > > sphericalTensorDimFields_
PtrList< GeometricField< sphericalTensor, fvPatchField, volMesh > > sphericalTensorVolFields_
PtrList< GeometricField< sphericalTensor, fvsPatchField, surfaceMesh > > sphericalTensorSurfFields_
PtrList< DimensionedField< symmTensor, volMesh > > symmTensorDimFields_
PtrList< GeometricField< symmTensor, fvPatchField, volMesh > > symmTensorVolFields_
PtrList< GeometricField< symmTensor, fvsPatchField, surfaceMesh > > symmTensorSurfFields_
PtrList< DimensionedField< tensor, volMesh > > tensorDimFields_
PtrList< GeometricField< tensor, fvPatchField, volMesh > > tensorVolFields_
PtrList< GeometricField< tensor, fvsPatchField, surfaceMesh > > tensorSurfFields_
Detailed Description
Definition at line 34 of file fvFieldDecomposerCache.C.
Member Function Documentation
size()
label size () const inline noexcept
Definition at line 51 of file fvFieldDecomposerCache.C.
References doLocalCode.
Referenced by fvFieldDecomposer::fieldsCache::privateCache::empty().
empty()
bool empty () const inline noexcept
Definition at line 73 of file fvFieldDecomposerCache.C.
References fvFieldDecomposer::fieldsCache::privateCache::size().
readAll()
void readAll (const fvMesh & mesh, const IOobjectList & objects) inline
Definition at line 75 of file fvFieldDecomposerCache.C.
References doLocalCode.
decompose()
template<class GeoField > static void decompose (const fvFieldDecomposer & decomposer, const PtrList< GeoField > & fields, bool report) inline static
Definition at line 112 of file fvFieldDecomposerCache.C.
References fvFieldDecomposer::decomposeFields(), fields, Foam::flatOutput(), Foam::Info, Foam::PtrListOps::names(), and Foam::nl.
decomposeAll()
void decomposeAll (const fvFieldDecomposer & decomposer, bool report) const inline
Definition at line 133 of file fvFieldDecomposerCache.C.
References doLocalCode.
Member Data Documentation
scalarDimFields_
PtrList<DimensionedField< scalar , volMesh> > scalarDimFields_
Definition at line 44 of file fvFieldDecomposerCache.C.
scalarVolFields_
PtrList<GeometricField< scalar , fvPatchField, volMesh> > scalarVolFields_
Definition at line 44 of file fvFieldDecomposerCache.C.
scalarSurfFields_
PtrList<GeometricField< scalar , fvsPatchField, surfaceMesh> > scalarSurfFields_
Definition at line 44 of file fvFieldDecomposerCache.C.
vectorDimFields_
PtrList<DimensionedField< vector , volMesh> > vectorDimFields_
Definition at line 45 of file fvFieldDecomposerCache.C.
vectorVolFields_
PtrList<GeometricField< vector , fvPatchField, volMesh> > vectorVolFields_
Definition at line 45 of file fvFieldDecomposerCache.C.
vectorSurfFields_
PtrList<GeometricField< vector , fvsPatchField, surfaceMesh> > vectorSurfFields_
Definition at line 45 of file fvFieldDecomposerCache.C.
sphericalTensorDimFields_
PtrList<DimensionedField< sphericalTensor , volMesh> > sphericalTensorDimFields_
Definition at line 46 of file fvFieldDecomposerCache.C.
sphericalTensorVolFields_
PtrList<GeometricField< sphericalTensor , fvPatchField, volMesh> > sphericalTensorVolFields_
Definition at line 46 of file fvFieldDecomposerCache.C.
sphericalTensorSurfFields_
PtrList<GeometricField< sphericalTensor , fvsPatchField, surfaceMesh> > sphericalTensorSurfFields_
Definition at line 46 of file fvFieldDecomposerCache.C.
symmTensorDimFields_
PtrList<DimensionedField< symmTensor , volMesh> > symmTensorDimFields_
Definition at line 47 of file fvFieldDecomposerCache.C.
symmTensorVolFields_
PtrList<GeometricField< symmTensor , fvPatchField, volMesh> > symmTensorVolFields_
Definition at line 47 of file fvFieldDecomposerCache.C.
symmTensorSurfFields_
PtrList<GeometricField< symmTensor , fvsPatchField, surfaceMesh> > symmTensorSurfFields_
Definition at line 47 of file fvFieldDecomposerCache.C.
tensorDimFields_
PtrList<DimensionedField< tensor , volMesh> > tensorDimFields_
Definition at line 48 of file fvFieldDecomposerCache.C.
tensorVolFields_
PtrList<GeometricField< tensor , fvPatchField, volMesh> > tensorVolFields_
Definition at line 48 of file fvFieldDecomposerCache.C.
tensorSurfFields_
PtrList<GeometricField< tensor , fvsPatchField, surfaceMesh> > tensorSurfFields_
Definition at line 48 of file fvFieldDecomposerCache.C.
The documentation for this class was generated from the following file:
src/parallel/decompose/decompose/fvFieldDecomposerCache.C