OpenFOAM: linearInterpolationWeights Class Reference
linearInterpolationWeights Class Reference
#include <linearInterpolationWeights.H>
Public Member Functions
TypeName ("linear")
linearInterpolationWeights (const scalarField &samples)
virtual ~linearInterpolationWeights ()=default
virtual bool valueWeights (const scalar t, labelList &indices, scalarField &weights) const
virtual bool integrationWeights (const scalar t1, const scalar t2, labelList &indices, scalarField &weights) const
Public Member Functions inherited from interpolationWeights
TypeName ("interpolationWeights")
declareRunTimeSelectionTable (autoPtr, interpolationWeights, word,(const scalarField &samples),(samples))
interpolationWeights (const scalarField &samples)
virtual ~interpolationWeights ()=default
template<class ListType1 , class ListType2 >
Foam::outerProduct< typenameListType1::value_type, typenameListType2::value_type >::type weightedSum (const ListType1 &f1, const ListType2 &f2)
Additional Inherited Members
Static Public Member Functions inherited from interpolationWeights
static autoPtr< interpolationWeights > New (const word &type, const scalarField &samples)
template<class ListType1 , class ListType2 >
static outerProduct< typenameListType1::value_type, typenameListType2::value_type >::type weightedSum (const ListType1 &f1, const ListType2 &f2)
Protected Member Functions inherited from interpolationWeights
interpolationWeights (const interpolationWeights &)=delete
void operator= (const interpolationWeights &)=delete
Protected Attributes inherited from interpolationWeights
const scalarField & samples_
Detailed Description
Source files
linearInterpolationWeights.H
linearInterpolationWeights.C
Definition at line 46 of file linearInterpolationWeights.H.
Constructor & Destructor Documentation
linearInterpolationWeights()
linearInterpolationWeights (const scalarField & samples) explicit
Definition at line 69 of file linearInterpolationWeights.C.
~linearInterpolationWeights()
virtual ~linearInterpolationWeights () virtual default
Member Function Documentation
TypeName()
TypeName ("linear")
valueWeights()
bool valueWeights (const scalar t, labelList & indices, scalarField & weights) const virtual
Implements interpolationWeights.
Definition at line 81 of file linearInterpolationWeights.C.
References Foam::findLower(), List< T >::setSize(), and UList< T >::size().
Referenced by searchableExtrudedCircle::findParametricNearest(), projectCurveEdge::position(), projectEdge::position(), projectFace::project(), and splineInterpolationWeights::valueWeights().
integrationWeights()
bool integrationWeights (const scalar t1, const scalar t2, labelList & indices, scalarField & weights) const virtual
Implements interpolationWeights.
Definition at line 148 of file linearInterpolationWeights.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::findLower(), UPtrList< T >::first(), forAll, UPtrList< T >::last(), List< T >::setSize(), UPtrList< T >::size(), and UList< T >::size().
The documentation for this class was generated from the following files:
src/OpenFOAM/interpolations/interpolationWeights/linearInterpolationWeights/linearInterpolationWeights.H
src/OpenFOAM/interpolations/interpolationWeights/linearInterpolationWeights/linearInterpolationWeights.C