OpenFOAM: LiquidEvapFuchsKnudsen< CloudType > Class Template Reference
LiquidEvapFuchsKnudsen< CloudType > Class Template Reference
Lagrangian particle models » Submodels » Reacting » Phase change
Liquid evaporation/condensation model for solution of liquid and solid.
#include <LiquidEvapFuchsKnudsen.H>
Public Types
enum activityCoeffMethodType { pUNIFAC , pHoff }
Public Types inherited from PhaseChangeModel< CloudType >
enum enthalpyTransferType { etLatentHeat , etEnthalpyDifference }
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Public Member Functions
TypeName ("liquidEvapFuchsKnudsen")
LiquidEvapFuchsKnudsen (const dictionary &dict, CloudType &cloud)
LiquidEvapFuchsKnudsen (const LiquidEvapFuchsKnudsen< CloudType > &pcm)
virtual autoPtr< PhaseChangeModel< CloudType > > clone () const
virtual ~LiquidEvapFuchsKnudsen ()=default
virtual void calculate (const scalar dt, const label celli, const scalar Re, const scalar Pr, const scalar d, const scalar nu, const scalar rho, const scalar T, const scalar Ts, const scalar pc, const scalar Tc, const scalarField &X, const scalarField &Xsol, const scalarField &liqMass, scalarField &dMassPC) const
virtual scalar dh (const label idc, const label idl, const scalar p, const scalar T) const
virtual scalar Tvap (const scalarField &X) const
virtual scalar TMax (const scalar p, const scalarField &X) const
Public Member Functions inherited from PhaseChangeModel< CloudType >
TypeName ("phaseChangeModel")
declareRunTimeSelectionTable (autoPtr, PhaseChangeModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
PhaseChangeModel (CloudType &owner)
PhaseChangeModel (const dictionary &dict, CloudType &owner, const word &type)
PhaseChangeModel (const PhaseChangeModel< CloudType > &pcm)
virtual ~PhaseChangeModel ()=default
const enthalpyTransferType & enthalpyTransfer () const
void addToPhaseChangeMass (const scalar dMass)
virtual void info ()
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
virtual ~CloudSubModelBase ()=default
const CloudType & owner () const
virtual bool writeTime () const
virtual fileName localPath () const
CloudType & owner ()
virtual void write (Ostream &os) const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
subModelBase (const subModelBase &smb)
virtual ~subModelBase ()=default
const word & modelName () const
const dictionary & dict () const
const word & baseName () const
const word & modelType () const
const dictionary & coeffDict () const
const dictionary & properties () const
virtual bool defaultCoeffs (const bool printMsg) const
virtual bool active () const
virtual void cacheFields (const bool store)
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
bool getModelDict (const word &entryName, dictionary &dict) const
template<class Type >
bool getModelProperty (const word &entryName, Type &value) const
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Protected Member Functions
scalar Sh (const scalar Re, const scalar Sc) const
tmp< scalarField > calcXc (const label celli) const
void calcXcSolution (const scalar massliq, const scalar masssol, scalar &Xliq, scalar &Xsol) const
scalar activityCoeff (const scalar Xliq, const scalar Ysol) const
Protected Member Functions inherited from PhaseChangeModel< CloudType >
enthalpyTransferType wordToEnthalpyTransfer (const word &etName) const
scalar Sh () const
Protected Member Functions inherited from subModelBase
bool inLine () const
Protected Attributes
activityCoeffMethodType method_
scalar gamma_
scalar alpha_
const liquidMixtureProperties & liquids_
List< word > solution_
label liqToCarrierMap_
label liqToLiqMap_
label solToSolMap_
Protected Attributes inherited from PhaseChangeModel< CloudType >
enthalpyTransferType enthalpyTransfer_
scalar dMass_
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Protected Attributes inherited from subModelBase
const word modelName_
dictionary & properties_
const dictionary dict_
const word baseName_
const word modelType_
const dictionary coeffDict_
Additional Inherited Members
Static Public Member Functions inherited from PhaseChangeModel< CloudType >
static autoPtr< PhaseChangeModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Public Attributes inherited from subModelBase
bool log
Static Public Attributes inherited from PhaseChangeModel< CloudType >
static const wordList enthalpyTransferTypeNames
Detailed Description
template<class CloudType>
class Foam::LiquidEvapFuchsKnudsen< CloudType >
Liquid evaporation/condensation model for solution of liquid and solid.
This model takes into account the Fuchs-Knudsen number correction, the modified Raoult's law is used to obtain the concenration of the evapora ble component on the surface and the activity coefficient is used. The correction Kelvin effect is used.
Reference:
    Xiaole Chen, Yu Feng, Wenqi Zhon, Clement Kleinstreuer.
    Numerical investigation of the interaction, transport and deposition
    of multicomponent droplets in a a simple mouth-throat model.
    Journal of Aerosol Science, 105(2017), 108-127.
    DOI:10.1016/j.jaerosci.2016.12.001
Definition at line 60 of file LiquidEvapFuchsKnudsen.H.
Member Enumeration Documentation
activityCoeffMethodType
template<class CloudType > enum activityCoeffMethodType
Enumerator
pUNIFAC
pHoff
Definition at line 69 of file LiquidEvapFuchsKnudsen.H.
Constructor & Destructor Documentation
LiquidEvapFuchsKnudsen() [1/2]
template<class CloudType > LiquidEvapFuchsKnudsen (const dictionary & dict, CloudType & cloud)
Definition at line 104 of file LiquidEvapFuchsKnudsen.C.
References subModelBase::coeffDict(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::Info, LiquidEvapFuchsKnudsen< CloudType >::liqToCarrierMap_, LiquidEvapFuchsKnudsen< CloudType >::liqToLiqMap_, LiquidEvapFuchsKnudsen< CloudType >::method_, Foam::nl, CloudSubModelBase< CloudType >::owner(), LiquidEvapFuchsKnudsen< CloudType >::pHoff, LiquidEvapFuchsKnudsen< CloudType >::pUNIFAC, UList< T >::size(), LiquidEvapFuchsKnudsen< CloudType >::solToSolMap_, and LiquidEvapFuchsKnudsen< CloudType >::solution_.
LiquidEvapFuchsKnudsen() [2/2]
template<class CloudType > LiquidEvapFuchsKnudsen (const LiquidEvapFuchsKnudsen< CloudType > & pcm)
Definition at line 169 of file LiquidEvapFuchsKnudsen.C.
~LiquidEvapFuchsKnudsen()
template<class CloudType > virtual ~LiquidEvapFuchsKnudsen () virtual default
Member Function Documentation
Sh()
template<class CloudType > Foam::scalar Sh (const scalar Re, const scalar Sc) const protected
Definition at line 64 of file LiquidEvapFuchsKnudsen.C.
References Foam::cbrt(), Foam::max(), Foam::pow(), and Foam::Re().
calcXc()
template<class CloudType > Foam::tmp< Foam::scalarField > calcXc (const label celli) const protected
Definition at line 45 of file LiquidEvapFuchsKnudsen.C.
References forAll, Foam::sum(), and Y.
calcXcSolution()
template<class CloudType > void calcXcSolution (const scalar massliq, const scalar masssol, scalar & Xliq, scalar & Xsol) const protected
Definition at line 27 of file LiquidEvapFuchsKnudsen.C.
References PtrList< T >::PtrList().
activityCoeff()
template<class CloudType > Foam::scalar activityCoeff (const scalar Xliq, const scalar Ysol) const protected
Definition at line 75 of file LiquidEvapFuchsKnudsen.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, Foam::inv(), and Foam::nl.
TypeName()
template<class CloudType > TypeName ("liquidEvapFuchsKnudsen")
clone()
template<class CloudType > virtual autoPtr< PhaseChangeModel< CloudType > > clone () const inline virtual
Implements PhaseChangeModel< CloudType >.
Definition at line 141 of file LiquidEvapFuchsKnudsen.H.
calculate()
template<class CloudType > void calculate (const scalar dt, const label celli, const scalar Re, const scalar Pr, const scalar d, const scalar nu, const scalar rho, const scalar T, const scalar Ts, const scalar pc, const scalar Tc, const scalarField & X, const scalarField & Xsol, const scalarField & liqMass, scalarField & dMassPC) const virtual
Implements PhaseChangeModel< CloudType >.
Definition at line 189 of file LiquidEvapFuchsKnudsen.C.
References Foam::exp(), gamma, Foam::log(), Foam::max(), nu, Foam::constant::mathematical::pi(), Foam::Re(), rho, rhog(), Foam::sqr(), and T.
dh()
template<class CloudType > Foam::scalar dh (const label idc, const label idl, const scalar p, const scalar T) const virtual
Reimplemented from PhaseChangeModel< CloudType >.
Definition at line 259 of file LiquidEvapFuchsKnudsen.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, p, and T.
Tvap()
template<class CloudType > Foam::scalar Tvap (const scalarField & X) const virtual
Reimplemented from PhaseChangeModel< CloudType >.
Definition at line 297 of file LiquidEvapFuchsKnudsen.C.
References Foam::Zero.
TMax()
template<class CloudType > Foam::scalar TMax (const scalar p, const scalarField & X) const virtual
Reimplemented from PhaseChangeModel< CloudType >.
Definition at line 307 of file LiquidEvapFuchsKnudsen.C.
References p, and Foam::sum().
Member Data Documentation
method_
template<class CloudType > activityCoeffMethodType method_ protected
Definition at line 81 of file LiquidEvapFuchsKnudsen.H.
Referenced by LiquidEvapFuchsKnudsen< CloudType >::LiquidEvapFuchsKnudsen().
gamma_
template<class CloudType > scalar gamma_ protected
Definition at line 84 of file LiquidEvapFuchsKnudsen.H.
alpha_
template<class CloudType > scalar alpha_ protected
Definition at line 87 of file LiquidEvapFuchsKnudsen.H.
liquids_
template<class CloudType > const liquidMixtureProperties& liquids_ protected
Definition at line 90 of file LiquidEvapFuchsKnudsen.H.
solution_
template<class CloudType > List<word> solution_ protected
Definition at line 93 of file LiquidEvapFuchsKnudsen.H.
Referenced by LiquidEvapFuchsKnudsen< CloudType >::LiquidEvapFuchsKnudsen().
liqToCarrierMap_
template<class CloudType > label liqToCarrierMap_ protected
Definition at line 96 of file LiquidEvapFuchsKnudsen.H.
Referenced by LiquidEvapFuchsKnudsen< CloudType >::LiquidEvapFuchsKnudsen().
liqToLiqMap_
template<class CloudType > label liqToLiqMap_ protected
Definition at line 99 of file LiquidEvapFuchsKnudsen.H.
Referenced by LiquidEvapFuchsKnudsen< CloudType >::LiquidEvapFuchsKnudsen().
solToSolMap_
template<class CloudType > label solToSolMap_ protected
Definition at line 102 of file LiquidEvapFuchsKnudsen.H.
Referenced by LiquidEvapFuchsKnudsen< CloudType >::LiquidEvapFuchsKnudsen().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/Reacting/PhaseChangeModel/LiquidEvapFuchsKnudsen/LiquidEvapFuchsKnudsen.H
src/lagrangian/intermediate/submodels/Reacting/PhaseChangeModel/LiquidEvapFuchsKnudsen/LiquidEvapFuchsKnudsen.C