OpenFOAM: structuredDecomp Class Reference
structuredDecomp Class Reference
Walk out decomposition of patch cells mesh - selectable as structured.
#include <structuredDecomp.H>
Public Member Functions
TypeName ("structured")
structuredDecomp (const dictionary &decompDict, const word &regionName="")
virtual ~structuredDecomp ()=default
virtual bool parallelAware () const
virtual labelList decompose (const polyMesh &mesh, const pointField &points, const scalarField &pointWeights) const
virtual labelList decompose (const labelListList &globalCellCells, const pointField &cc, const scalarField &cWeights) const
Public Member Functions inherited from decompositionMethod
TypeName ("decompositionMethod")
declareRunTimeSelectionTable (autoPtr, decompositionMethod, dictionary,(const dictionary &decompDict, const word &regionName),(decompDict, regionName))
decompositionMethod (const dictionary &decompDict, const word &regionName="")
virtual ~decompositionMethod ()=default
label nDomains () const noexcept
virtual labelList decompose (const pointField &points, const scalarField &pointWeights) const
virtual labelList decompose (const pointField &points) const
virtual labelList decompose (const polyMesh &mesh, const pointField &points) const
virtual labelList decompose (const polyMesh &mesh, const labelList &cellToRegion, const pointField &regionPoints, const scalarField &regionWeights) const
virtual labelList decompose (const polyMesh &mesh, const labelList &cellToRegion, const pointField &regionPoints) const
virtual labelList decompose (const labelListList &globalCellCells, const pointField &cc) const
void setConstraints (const polyMesh &mesh, boolList &blockedFace, PtrList< labelList > &specifiedProcessorFaces, labelList &specifiedProcessor, List< labelPair > &explicitConnections) const
void applyConstraints (const polyMesh &mesh, const boolList &blockedFace, const PtrList< labelList > &specifiedProcessorFaces, const labelList &specifiedProcessor, const List< labelPair > &explicitConnections, labelList &finalDecomp) const
virtual labelList decompose (const polyMesh &mesh, const scalarField &cellWeights, const boolList &blockedFace, const PtrList< labelList > &specifiedProcessorFaces, const labelList &specifiedProcessor, const List< labelPair > &explicitConnections) const
labelList decompose (const polyMesh &mesh, const scalarField &cWeights) const
Additional Inherited Members
Static Public Member Functions inherited from decompositionMethod
static label nDomains (const dictionary &decompDict, const word &regionName="")
static const dictionary & optionalRegionDict (const dictionary &decompDict, const word &regionName)
static autoPtr< decompositionMethod > New (const dictionary &decompDict, const word &regionName="")
static void calcCellCells (const polyMesh &mesh, const labelList &agglom, const label nLocalCoarse, const bool global, CompactListList< label > &cellCells)
static void calcCellCells (const polyMesh &mesh, const labelList &agglom, const label nLocalCoarse, const bool parallel, CompactListList< label > &cellCells, CompactListList< scalar > &cellCellWeights)
Protected Types inherited from decompositionMethod
enum selectionType { DEFAULT = 0 , EXACT = 1 , MANDATORY = 2 , NULL_DICT = 4 }
Protected Member Functions inherited from decompositionMethod
const dictionary & findCoeffsDict (const word &coeffsName, int select=selectionType::DEFAULT) const
Static Protected Member Functions inherited from decompositionMethod
static const dictionary & findCoeffsDict (const dictionary &dict, const word &coeffsName, int select=selectionType::DEFAULT)
Protected Attributes inherited from decompositionMethod
const dictionary & decompDict_
const dictionary & decompRegionDict_
label nDomains_
PtrList< decompositionConstraint > constraints_
Detailed Description
Walk out decomposition of patch cells mesh - selectable as structured.
Source files
structuredDecomp.H
structuredDecomp.C
Definition at line 46 of file structuredDecomp.H.
Constructor & Destructor Documentation
structuredDecomp()
structuredDecomp (const dictionary & decompDict, const word & regionName = "") explicit
Definition at line 44 of file structuredDecomp.C.
References decompositionMethod::nDomains(), decompositionMethod::New(), and dictionary::set().
~structuredDecomp()
virtual ~structuredDecomp () virtual default
Member Function Documentation
TypeName()
TypeName ("structured")
parallelAware()
bool parallelAware () const virtual
Implements decompositionMethod.
Definition at line 61 of file structuredDecomp.C.
decompose() [1/2]
Foam::labelList decompose (const polyMesh & mesh, const pointField & points, const scalarField & pointWeights) const virtual
Implements decompositionMethod.
Definition at line 67 of file structuredDecomp.C.
References polyMesh::boundaryMesh(), primitiveMesh::cellCentres(), fvMeshSubset::cellMap(), Foam::endl(), forAll, polyMesh::globalData(), mesh, primitiveMesh::nCells(), primitiveMesh::nFaces(), Foam::nl, patchIDs(), pbm, pp(), UPtrList< T >::size(), fvMeshSubset::subMesh(), and WarningInFunction.
decompose() [2/2]
virtual labelList decompose (const labelListList & globalCellCells, const pointField & cc, const scalarField & cWeights) const inline virtual
Implements decompositionMethod.
Definition at line 105 of file structuredDecomp.H.
References NotImplemented.
The documentation for this class was generated from the following files:
src/parallel/decompose/decompositionMethods/structuredDecomp/structuredDecomp.H
src/parallel/decompose/decompositionMethods/structuredDecomp/structuredDecomp.C