OpenFOAM: IOstreamOption::versionNumber Class Reference
IOstreamOption::versionNumber Class Reference
#include <IOstreamOption.H>
Public Member Functions
constexpr versionNumber () noexcept
constexpr versionNumber (int major, int minor) noexcept
constexpr versionNumber (const float ver) noexcept
versionNumber (const std::string &verNum)
versionNumber (const token &tok)
versionNumber (const word &keyword, const dictionary &dict)
std::string str () const
int canonical () const noexcept
int compare (const versionNumber &other) const noexcept
Static Public Member Functions
static versionNumber canonical (int verNum) noexcept
Detailed Description
Definition at line 97 of file IOstreamOption.H.
Constructor & Destructor Documentation
versionNumber() [1/6]
constexpr versionNumber () inline constexpr noexcept
Definition at line 108 of file IOstreamOption.H.
Referenced by IOstreamOption::versionNumber::canonical(), IOstreamOption::versionNumber::versionNumber(), and IOstreamOption::versionNumber::versionNumber().
versionNumber() [2/6]
constexpr versionNumber (int major, int minor) inline constexpr noexcept
Definition at line 114 of file IOstreamOption.H.
versionNumber() [3/6]
constexpr versionNumber (const float ver) inline explicit constexpr noexcept
Definition at line 120 of file IOstreamOption.H.
versionNumber() [4/6]
versionNumber (const std::string & verNum) explicit
Definition at line 137 of file IOstreamOption.C.
versionNumber() [5/6]
versionNumber (const token & tok) explicit
Definition at line 143 of file IOstreamOption.C.
References Foam::nl, IOstreamOption::versionNumber::versionNumber(), and WarningInFunction.
versionNumber() [6/6]
versionNumber (const word & keyword, const dictionary & dict)
Definition at line 166 of file IOstreamOption.C.
References dict, keyType::LITERAL, and IOstreamOption::versionNumber::versionNumber().
Member Function Documentation
str()
std::string str () const inline
Definition at line 138 of file IOstreamOption.H.
canonical() [1/2]
int canonical () const inline noexcept
Definition at line 149 of file IOstreamOption.H.
Referenced by decomposedBlockData::readBlocks(), and decomposedBlockData::writeData().
canonical() [2/2]
static versionNumber canonical (int verNum) inline static noexcept
Definition at line 155 of file IOstreamOption.H.
References IOstreamOption::versionNumber::versionNumber().
compare()
int compare (const versionNumber & other) const inline noexcept
Definition at line 164 of file IOstreamOption.H.
Referenced by Foam::operator!=(), Foam::operator<(), Foam::operator<=(), Foam::operator==(), Foam::operator>(), and Foam::operator>=().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/options/IOstreamOption.H
src/OpenFOAM/db/options/IOstreamOption.C