OpenFOAM: animation Class Reference
animation Class Reference
glTF animation
#include <foamGltfAnimation.H>
Classes
struct glTFChannel
struct glTFSampler
struct glTFTarget
Public Member Functions
animation ()
animation (const word &name)
~animation ()=default
void addTranslation (const label inputId, const label outputId, const label nodeId, const string &interpolation)
void write (Ostream &os) const
Public Member Functions inherited from base
base ()
base (const word &name)
~base ()=default
label & id () noexcept
const word & name () const noexcept
void write (Ostream &os) const
void operator= (const base &gltf)
Protected Attributes
DynamicList< glTFSampler > samplers_
DynamicList< glTFChannel > channels_
Protected Attributes inherited from base
word name_
label id_
Detailed Description
glTF animation
Note
Implements the glTF v2 specification
Source files
foamGltfAnimation.H
foamGltfAnimation.C
Definition at line 61 of file foamGltfAnimation.H.
Constructor & Destructor Documentation
animation() [1/2]
animation ()
Definition at line 25 of file foamGltfAnimation.C.
animation() [2/2]
animation (const word & name) explicit
Definition at line 33 of file foamGltfAnimation.C.
~animation()
~animation () default
Member Function Documentation
addTranslation()
void addTranslation (const label inputId, const label outputId, const label nodeId, const string & interpolation)
Definition at line 43 of file foamGltfAnimation.C.
References PtrList< T >::append(), and UPtrList< T >::size().
write()
void write (Ostream & os) const
Definition at line 65 of file foamGltfAnimation.C.
References Foam::decrIndent(), forAll, Foam::incrIndent(), Foam::indent(), Foam::nl, and os().
Referenced by Foam::operator<<().
Member Data Documentation
samplers_
DynamicList<glTFSampler> samplers_ protected
Definition at line 96 of file foamGltfAnimation.H.
channels_
DynamicList<glTFChannel> channels_ protected
Definition at line 99 of file foamGltfAnimation.H.
The documentation for this class was generated from the following files:
src/fileFormats/gltf/foamGltfAnimation.H
src/fileFormats/gltf/foamGltfAnimation.C