OpenFOAM: decomposedBlockData Class Reference
decomposedBlockData Class Reference
The decomposedBlockData comprise a List<char> for each output processor, typically with IO on the master processor only.
#include <decomposedBlockData.H>
Public Member Functions
TypeName ("decomposedBlockData")
decomposedBlockData (const label comm, const IOobject &io, const UPstream::commsTypes=UPstream::commsTypes::scheduled)
virtual ~decomposedBlockData ()=default
virtual bool read ()
virtual bool writeData (Ostream &os) const
virtual bool writeObject (IOstreamOption streamOpt, const bool writeOnProc) const
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
regIOobject (const IOobject &io, const bool isTimeObject=false)
regIOobject (const regIOobject &rio)
regIOobject (const regIOobject &rio, bool registerCopy)
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
regIOobject (const IOobject &io, const regIOobject &rio)
virtual ~regIOobject ()
bool checkIn ()
bool checkOut ()
virtual void addWatch ()
bool registered () const noexcept
bool ownedByRegistry () const noexcept
bool store ()
void release (const bool unregister=false) noexcept
label eventNo () const noexcept
label & eventNo () noexcept
bool upToDate (const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
void setUpToDate ()
virtual void rename (const word &newName)
const dictionary * findMetaData () const noexcept
dictionary & getMetaData () noexcept
void removeMetaData ()
virtual void updateMetaData ()
virtual fileName filePath () const
bool headerOk ()
Istream & readStream (const word &, const bool readOnProc=true)
void close ()
virtual bool readData (Istream &)
virtual label addWatch (const fileName &)
const labelList & watchIndices () const noexcept
labelList & watchIndices () noexcept
virtual bool modified () const
virtual bool readIfModified ()
virtual bool write (const bool writeOnProc=true) const
virtual bool global () const
void operator= (const IOobject &io)
virtual bool writeObject (IOstreamOption::streamFormat fmt, IOstreamOption::versionNumber ver, IOstreamOption::compressionType cmp, const bool writeOnProc) const
Public Member Functions inherited from IOobject
TypeName ("IOobject")
IOobject (const IOobject &)=default
virtual ~IOobject ()=default
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const fileName &path, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const fileName &path, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const IOobject &io, const objectRegistry &registry)
IOobject (const IOobject &io, const word &name)
IOobject (const IOobject &io, const word &name, const fileName &local)
IOobject (const IOobject &io, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt)
IOobject (const IOobject &io, IOobjectOption::registerOption regOpt)
autoPtr< IOobject > clone () const
autoPtr< IOobject > clone (const objectRegistry &registry) const
const objectRegistry & db () const noexcept
const Time & time () const noexcept
const word & name () const noexcept
const word & headerClassName () const noexcept
word & headerClassName () noexcept
const string & note () const noexcept
string & note () noexcept
unsigned labelByteSize () const noexcept
unsigned scalarByteSize () const noexcept
void resetHeader (const word &newName=word::null)
bool hasHeaderClass () const noexcept
template<class Type >
bool isHeaderClass () const
template<class Type >
bool isHeaderClassName () const
word group () const
word member () const
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const noexcept
fileName & instance () noexcept
const fileName & local () const noexcept
fileName path () const
fileName path (const word &instance, const fileName &local=fileName::null) const
fileName objectPath () const
fileName objectRelPath () const
fileName localFilePath (const word &typeName, const bool search=true) const
fileName globalFilePath (const word &typeName, const bool search=true) const
IOstreamOption parseHeader (const dictionary &headerDict)
bool readHeader (Istream &is)
bool readHeader (dictionary &headerDict, Istream &is)
template<class Type >
bool typeHeaderOk (const bool checkType=true, const bool search=true, const bool verbose=true)
template<class Type >
void warnNoRereading () const
bool writeHeader (Ostream &os) const
bool writeHeader (Ostream &os, const word &objectType) const
void writeHeader (dictionary &dict, IOstreamOption streamOpt) const
void writeHeader (dictionary &dict, const word &objectType, IOstreamOption streamOpt) const
bool good () const noexcept
bool bad () const noexcept
InfoProxy< IOobject > info () const noexcept
void operator= (const IOobject &io)
template<>
bool isHeaderClass () const
template<class StringType >
Foam::word groupName (StringType base, const word &group)
Public Member Functions inherited from IOobjectOption
constexpr IOobjectOption (readOption rOpt=readOption::NO_READ, writeOption wOpt=writeOption::NO_WRITE, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (readOption rOpt, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (writeOption wOpt, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (registerOption registerObject, bool globalObject=false) noexcept
constexpr IOobjectOption (readOption rOpt, writeOption wOpt, bool registerObject, bool globalObject=false) noexcept
constexpr IOobjectOption (bool registerObject, bool globalObject=false) noexcept
readOption readOpt () const noexcept
readOption readOpt (readOption opt) noexcept
writeOption writeOpt () const noexcept
writeOption writeOpt (writeOption opt) noexcept
bool registerObject () const noexcept
bool registerObject (bool on) noexcept
bool globalObject () const noexcept
bool globalObject (bool on) noexcept
bool isAnyRead () const noexcept
bool isReadRequired () const noexcept
bool isReadOptional () const noexcept
readOption & readOpt () noexcept
writeOption & writeOpt () noexcept
bool & registerObject () noexcept
bool & globalObject () noexcept
Static Public Member Functions
static bool isCollatedType (const word &objectType)
static bool isCollatedType (const IOobject &io)
static bool readHeader (IOobject &io, Istream &is)
static void writeHeader (Ostream &os, IOstreamOption streamOptContainer, const word &objectType, const string &note, const fileName &location, const word &objectName, const dictionary &extraEntries)
static void writeHeader (Ostream &os, IOstreamOption streamOptData, const IOobject &io)
static void writeExtraHeaderContent (dictionary &dict, IOstreamOption streamOptData, const IOobject &io)
static bool readBlockEntry (Istream &is, List< char > &charData)
static std::streamoff writeBlockEntry (OSstream &os, const label blocki, const UList< char > &charData)
static std::streamoff writeBlockEntry (OSstream &os, const label blocki, const std::string &content)
static std::streamoff writeBlockEntry (OSstream &os, IOstreamOption streamOptData, const regIOobject &io, const label blocki, const bool withLocalHeader)
static autoPtr< ISstream > readBlock (const label blocki, ISstream &is, IOobject &headerIO)
static autoPtr< ISstream > readBlocks (const label comm, const fileName &fName, autoPtr< ISstream > &isPtr, IOobject &headerIO, const UPstream::commsTypes commsType)
static void gather (const label comm, const label data, labelList &datas)
static void gatherSlaveData (const label comm, const UList< char > &data, const labelUList &recvSizes, const labelRange &fromProcs, List< int > &recvOffsets, DynamicList< char > &recvData)
static bool writeBlocks (const label comm, autoPtr< OSstream > &osPtr, List< std::streamoff > &blockOffset, const UList< char > &masterData, const labelUList &recvSizes, const UPtrList< SubList< char > > &slaveData, const UPstream::commsTypes commsType, const bool syncReturnState=true)
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *p)
template<class Type >
static Type & store (autoPtr< Type > &ptr)
template<class Type >
static Type & store (autoPtr< Type > &&ptr)
template<class Type >
static Type & store (refPtr< Type > &ptr)
template<class Type >
static Type & store (refPtr< Type > &&ptr)
template<class Type >
static Type & store (tmp< Type > &ptr)
template<class Type >
static Type & store (tmp< Type > &&ptr)
Static Public Member Functions inherited from IOobject
static bool bannerEnabled () noexcept
static bool bannerEnabled (bool on) noexcept
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
template<class StringType >
static word groupName (StringType base, const word &group)
static word group (const word &name)
static word member (const word &name)
static word scopedName (const std::string &scope, const word &name)
static IOobject selectIO (const IOobject &io, const fileName &altFile, const word &ioName="")
static Ostream & writeBanner (Ostream &os, const bool noSyntaxHint=false)
static Ostream & writeDivider (Ostream &os)
static Ostream & writeEndDivider (Ostream &os)
Static Public Member Functions inherited from IOobjectOption
static bool isAnyRead (readOption opt) noexcept
static bool isReadRequired (readOption opt) noexcept
static bool isReadOptional (readOption opt) noexcept
static readOption lazierRead (readOption opt) noexcept
Static Protected Member Functions
static label calcNumProcs (const label comm, const off_t maxBufferSize, const labelUList &recvSizes, const label startProci)
static bool readBlocks (const label comm, autoPtr< ISstream > &isPtr, List< char > &contentChars, const UPstream::commsTypes commsType)
static bool skipBlockEntry (Istream &is)
static label getNumBlocks (Istream &is, const bool readHeader)
Static Protected Member Functions inherited from IOobject
static void writeHeaderContent (Ostream &os, const IOobject &io, const word &objectType, const dictionary *metaDataDict=nullptr)
static void writeHeaderContent (dictionary &dict, const IOobject &io, const word &objectType, IOstreamOption streamOpt, const dictionary *metaDataDict=nullptr)
Protected Attributes
const UPstream::commsTypes commsType_
const label comm_
List< char > contentData_
Additional Inherited Members
Public Types inherited from IOobject
enum objectState : char { GOOD , BAD }
enum fileCheckTypes : char { timeStamp , timeStampMaster , inotify , inotifyMaster }
Public Types inherited from IOobjectOption
enum readOption : unsigned char {
NO_READ = 0 , MUST_READ = 0x1 , READ_MODIFIED = 0x3 , MUST_READ_IF_MODIFIED = 0x3 ,
LAZY_READ = 0x4 , READ_IF_PRESENT = 0x4
}
enum writeOption : unsigned char { NO_WRITE = 0 , AUTO_WRITE = 0x10 }
enum registerOption : unsigned char { NO_REGISTER = 0 , REGISTER = 1 }
Static Public Attributes inherited from IOobject
static const Enum< fileCheckTypes > fileCheckTypesNames
static char scopeSeparator
static fileCheckTypes fileModificationChecking
static float fileModificationSkew
static int maxFileModificationPolls
Protected Member Functions inherited from regIOobject
bool readHeaderOk (const IOstreamOption::streamFormat fmt, const word &typeName)
Protected Member Functions inherited from IOobject
void setBad (const string &s)
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
Detailed Description
The decomposedBlockData comprise a List<char> for each output processor, typically with IO on the master processor only.
For decomposedBlockData, we make a distinction between the container description and the individual block contents.
The FoamFile header specifies the container characteristics and thus has class = decomposedBlockData and normally format = binary. This description refers to the entire file container, not the individual blocks.
Each processor block is simply a binary chunk of characters and the first block also contains the header description for all of the blocks. For example,
FoamFile
{
    version     2.0;
    format      binary;
    arch        "LSB;label=32;scalar=64";
    class       decomposedBlockData;
    location    "constant/polyMesh";
    object      points;
}
// processor0
NCHARS
(FoamFile
{
    version     2.0;
    format      ascii;
    arch        "LSB;label=32;scalar=64";
    class       vectorField;
    location    "constant/polyMesh";
    object      points;
}
...content...
)
// processor1
NCHARS
(...content...)
...
Source files
decomposedBlockData.H
decomposedBlockData.C
decomposedBlockDataHeader.C
Definition at line 99 of file decomposedBlockData.H.
Constructor & Destructor Documentation
decomposedBlockData()
decomposedBlockData (const label comm, const IOobject & io, const UPstream::commsTypes commsType = UPstream::commsTypes::scheduled)
Definition at line 69 of file decomposedBlockData.C.
References Foam::endl(), regIOobject::headerOk(), IOobjectOption::isReadOptional(), IOobjectOption::isReadRequired(), IOobjectOption::MUST_READ_IF_MODIFIED, IOobject::name(), decomposedBlockData::read(), IOobjectOption::readOpt(), and WarningInFunction.
~decomposedBlockData()
virtual ~decomposedBlockData () virtual default
Member Function Documentation
calcNumProcs()
Foam::label calcNumProcs (const label comm, const off_t maxBufferSize, const labelUList & recvSizes, const label startProci) static protected
Definition at line 792 of file decomposedBlockData.C.
References Pstream::broadcast(), UPstream::master(), and UPstream::nProcs().
readBlocks() [1/2]
bool readBlocks (const label comm, autoPtr< ISstream > & isPtr, List< char > & contentChars, const UPstream::commsTypes commsType) static protected
Definition at line 427 of file decomposedBlockData.C.
References Pstream::broadcast(), UPstream::commsTypeNames, Foam::endl(), FUNCTION_NAME, UPstream::master(), UPstream::masterNo(), UPstream::msgType(), UPstream::nonBlocking, os(), Foam::Pout, decomposedBlockData::readBlockEntry(), UPstream::scheduled, and UPstream::subProcs().
Referenced by masterUncollatedFileOperation::readStream().
skipBlockEntry()
bool skipBlockEntry (Istream & is) static protected
Definition at line 142 of file decomposedBlockData.C.
References IOstreamOption::BINARY, token::END_STATEMENT, and FUNCTION_NAME.
getNumBlocks()
Foam::label getNumBlocks (Istream & is, const bool readHeader) static protected
Definition at line 219 of file decomposedBlockData.C.
References UPtrList< T >::get().
TypeName()
TypeName ("decomposedBlockData")
read()
bool read () virtual
Reimplemented from regIOobject.
Definition at line 1036 of file decomposedBlockData.C.
References Foam::fileHandler, UPstream::master(), word::null, and IOobject::readHeader().
Referenced by decomposedBlockData::decomposedBlockData().
writeData()
bool writeData (Ostream & os) const virtual
Implements regIOobject.
Definition at line 1050 of file decomposedBlockData.C.
References Pstream::broadcasts(), IOstreamOption::versionNumber::canonical(), IOstream::good(), IOobject::headerClassName(), io(), local, UPstream::master(), Foam::name(), IOobject::note(), os(), IOobject::readHeader(), IOobject::writeEndDivider(), decomposedBlockData::writeHeader(), OBJstream::writeQuoted(), and OSstream::writeRaw().
writeObject()
bool writeObject (IOstreamOption streamOpt, const bool writeOnProc) const virtual
Reimplemented from regIOobject.
Definition at line 1123 of file decomposedBlockData.C.
References IOstreamOption::BINARY, UPstream::master(), and decomposedBlockData::writeHeader().
isCollatedType() [1/2]
bool isCollatedType (const word & objectType) static
Definition at line 46 of file decomposedBlockData.C.
Referenced by decomposedBlockData::isCollatedType(), decomposedBlockData::readHeader(), masterUncollatedFileOperation::readStream(), and uncollatedFileOperation::readStream().
isCollatedType() [2/2]
bool isCollatedType (const IOobject & io) static
Definition at line 58 of file decomposedBlockData.C.
References IOobject::headerClassName(), io(), and decomposedBlockData::isCollatedType().
readHeader()
bool readHeader (IOobject & io, Istream & is) static
Definition at line 101 of file decomposedBlockDataHeader.C.
References IOobject::headerClassName(), io(), decomposedBlockData::isCollatedType(), decomposedBlockData::readBlockEntry(), and IOobject::readHeader().
Referenced by masterUncollatedFileOperation::readHeader(), and uncollatedFileOperation::readHeader().
writeHeader() [1/2]
void writeHeader (Ostream & os, IOstreamOption streamOptContainer, const word & objectType, const string & note, const fileName & location, const word & objectName, const dictionary & extraEntries) static
Definition at line 132 of file decomposedBlockDataHeader.C.
References IOobject::bannerEnabled(), Ostream::beginBlock(), UPtrList< T >::empty(), Ostream::endBlock(), Foam::nl, os(), IOobject::writeBanner(), and IOobject::writeDivider().
Referenced by collatedFileOperation::appendObject(), decomposedBlockData::writeData(), and decomposedBlockData::writeObject().
writeHeader() [2/2]
void writeHeader (Ostream & os, IOstreamOption streamOptData, const IOobject & io) static
Definition at line 193 of file decomposedBlockDataHeader.C.
References IOobject::bannerEnabled(), Ostream::beginBlock(), IOobject::db(), UPtrList< T >::empty(), Ostream::endBlock(), IOobject::findMetaData(), IOobject::instance(), io(), IOobject::local(), IOobject::name(), Foam::nl, IOobject::note(), os(), IOobject::writeBanner(), IOobject::writeDivider(), and Foam::writeHeaderEntry().
writeExtraHeaderContent()
void writeExtraHeaderContent (dictionary & dict, IOstreamOption streamOptData, const IOobject & io) static
Definition at line 174 of file decomposedBlockDataHeader.C.
References dictionary::add(), dict, UPtrList< T >::empty(), IOobject::findMetaData(), io(), and dictionary::set().
Referenced by collatedFileOperation::writeObject().
readBlockEntry()
bool readBlockEntry (Istream & is, List< char > & charData) static
Definition at line 99 of file decomposedBlockData.C.
References token::END_STATEMENT, and FUNCTION_NAME.
Referenced by decomposedBlockData::readBlock(), decomposedBlockData::readBlocks(), decomposedBlockData::readBlocks(), and decomposedBlockData::readHeader().
writeBlockEntry() [1/3]
std::streamoff writeBlockEntry (OSstream & os, const label blocki, const UList< char > & charData) static
Definition at line 261 of file decomposedBlockData.C.
References Foam::name(), Foam::nl, os(), and OFstream::stdStream().
Referenced by collatedFileOperation::appendObject(), decomposedBlockData::writeBlockEntry(), decomposedBlockData::writeBlockEntry(), and decomposedBlockData::writeBlocks().
writeBlockEntry() [2/3]
std::streamoff writeBlockEntry (OSstream & os, const label blocki, const std::string & content) static
Definition at line 290 of file decomposedBlockData.C.
References os(), and decomposedBlockData::writeBlockEntry().
writeBlockEntry() [3/3]
std::streamoff writeBlockEntry (OSstream & os, IOstreamOption streamOptData, const regIOobject & io, const label blocki, const bool withLocalHeader) static
Definition at line 307 of file decomposedBlockData.C.
References IOobject::bannerEnabled(), io(), os(), StringStreamAllocator< StreamType >::str(), decomposedBlockData::writeBlockEntry(), and IOobject::writeHeader().
readBlock()
Foam::autoPtr< Foam::ISstream > readBlock (const label blocki, ISstream & is, IOobject & headerIO) static
Definition at line 349 of file decomposedBlockData.C.
References Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, Foam::nl, Foam::Pout, and decomposedBlockData::readBlockEntry().
Referenced by masterUncollatedFileOperation::readStream(), and uncollatedFileOperation::readStream().
readBlocks() [2/2]
Foam::autoPtr< Foam::ISstream > readBlocks (const label comm, const fileName & fName, autoPtr< ISstream > & isPtr, IOobject & headerIO, const UPstream::commsTypes commsType) static
Definition at line 530 of file decomposedBlockData.C.
References Pstream::broadcast(), Pstream::broadcasts(), IOstreamOption::versionNumber::canonical(), UPstream::commsTypeNames, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, FUNCTION_NAME, UPstream::master(), UPstream::masterNo(), UPstream::msgType(), Foam::nl, UPstream::nonBlocking, os(), Foam::Pout, decomposedBlockData::readBlockEntry(), UPstream::scheduled, UPstream::subProcs(), and UPstream::worldComm.
gather()
void gather (const label comm, const label data, labelList & datas) static
Definition at line 695 of file decomposedBlockData.C.
References forAll, UPstream::gather(), UPstream::master(), UPstream::nProcs(), PtrList< T >::resize(), and PtrList< T >::setSize().
Referenced by OFstreamCollator::write().
gatherSlaveData()
void gatherSlaveData (const label comm, const UList< char > & data, const labelUList & recvSizes, const labelRange & fromProcs, List< int > & recvOffsets, DynamicList< char > & recvData) static
Definition at line 734 of file decomposedBlockData.C.
References PtrList< T >::clear(), UPstream::gather(), UPstream::master(), UPstream::myProcNo(), UPstream::nProcs(), and PtrList< T >::resize().
writeBlocks()
bool writeBlocks (const label comm, autoPtr< OSstream > & osPtr, List< std::streamoff > & blockOffset, const UList< char > & masterData, const labelUList & recvSizes, const UPtrList< SubList< char > > & slaveData, const UPstream::commsTypes commsType, const bool syncReturnState = true) static
Definition at line 822 of file decomposedBlockData.C.
References Pstream::broadcast(), UPstream::commsTypeNames, Foam::endl(), IOstream::good(), UPstream::master(), UPstream::masterNo(), Foam::max(), UPstream::msgType(), UPstream::nProcs(), os(), Foam::Pout, UIPstream::read(), PtrList< T >::resize(), UPstream::scheduled, UPtrList< T >::size(), UOPstream::write(), and decomposedBlockData::writeBlockEntry().
Member Data Documentation
commsType_
const UPstream::commsTypes commsType_ protected
Definition at line 122 of file decomposedBlockData.H.
comm_
const label comm_ protected
Definition at line 125 of file decomposedBlockData.H.
contentData_
List<char> contentData_ protected
Definition at line 128 of file decomposedBlockData.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOobjects/decomposedBlockData/decomposedBlockData.H
src/OpenFOAM/db/IOobjects/decomposedBlockData/decomposedBlockData.C
src/OpenFOAM/db/IOobjects/decomposedBlockData/decomposedBlockDataHeader.C