OpenFOAM: cyclicAMIGAMGInterfaceField Class Reference
cyclicAMIGAMGInterfaceField Class Reference
GAMG agglomerated cyclic interface field.
#include <cyclicAMIGAMGInterfaceField.H>
Public Member Functions
TypeName ("cyclicAMI")
cyclicAMIGAMGInterfaceField (const GAMGInterface &GAMGCp, const lduInterfaceField &fineInterfaceField)
cyclicAMIGAMGInterfaceField (const GAMGInterface &GAMGCp, const bool doTransform, const int rank)
virtual ~cyclicAMIGAMGInterfaceField ()
label size () const
virtual void updateInterfaceMatrix (solveScalarField &result, const bool add, const lduAddressing &lduAddr, const label patchId, const solveScalarField &psiInternal, const scalarField &coeffs, const direction cmpt, const Pstream::commsTypes commsType) const
virtual bool doTransform () const
virtual const tensorField & forwardT () const
virtual const tensorField & reverseT () const
virtual int rank () const
Public Member Functions inherited from GAMGInterfaceField
TypeName ("GAMGInterfaceField")
declareRunTimeSelectionTable (autoPtr, GAMGInterfaceField, lduInterfaceField,(const GAMGInterface &GAMGCp, const lduInterfaceField &fineInterface),(GAMGCp, fineInterface))
declareRunTimeSelectionTable (autoPtr, GAMGInterfaceField, lduInterface,(const GAMGInterface &GAMGCp, const bool doTransform, const int rank),(GAMGCp, doTransform, rank))
GAMGInterfaceField (const GAMGInterface &GAMGCp, const lduInterfaceField &)
GAMGInterfaceField (const GAMGInterface &GAMGCp, const bool doTransform, const int rank)
const GAMGInterface & interface () const
Public Member Functions inherited from lduInterfaceField
TypeName ("lduInterfaceField")
lduInterfaceField (const lduInterfaceField &)=delete
void operator= (const lduInterfaceField &)=delete
lduInterfaceField (const lduInterface &patch)
virtual ~lduInterfaceField ()=default
const lduInterface & interface () const noexcept
virtual const word & interfaceFieldType () const
virtual bool ready () const
bool updatedMatrix () const noexcept
bool updatedMatrix (bool flag) const noexcept
virtual void initInterfaceMatrixUpdate (solveScalarField &result, const bool add, const lduAddressing &, const label interfacei, const solveScalarField &psiInternal, const scalarField &coeffs, const direction cmpt, const Pstream::commsTypes commsType) const
template<class Type >
void addToInternalField (Field< Type > &result, const bool add, const labelUList &faceCells, const scalarField &coeffs, const Field< Type > &vals) const
bool & updatedMatrix () noexcept
Public Member Functions inherited from cyclicAMILduInterfaceField
TypeName ("cyclicAMILduInterfaceField")
cyclicAMILduInterfaceField ()
virtual ~cyclicAMILduInterfaceField ()
template<class Type >
void transformCoupleField (Field< Type > &f) const
void transformCoupleField (solveScalarField &psiInternal, const direction cmpt) const
Additional Inherited Members
Static Public Member Functions inherited from GAMGInterfaceField
static autoPtr< GAMGInterfaceField > New (const GAMGInterface &GAMGCp, const lduInterfaceField &fineInterface)
static autoPtr< GAMGInterfaceField > New (const GAMGInterface &GAMGCp, const bool doTransform, const int rank)
Detailed Description
GAMG agglomerated cyclic interface field.
Source files
cyclicAMIGAMGInterfaceField.H
cyclicAMIGAMGInterfaceField.C
Definition at line 49 of file cyclicAMIGAMGInterfaceField.H.
Constructor & Destructor Documentation
cyclicAMIGAMGInterfaceField() [1/2]
cyclicAMIGAMGInterfaceField (const GAMGInterface & GAMGCp, const lduInterfaceField & fineInterfaceField)
Definition at line 48 of file cyclicAMIGAMGInterfaceField.C.
References p, and Foam::refCast().
cyclicAMIGAMGInterfaceField() [2/2]
cyclicAMIGAMGInterfaceField (const GAMGInterface & GAMGCp, const bool doTransform, const int rank)
Definition at line 67 of file cyclicAMIGAMGInterfaceField.C.
~cyclicAMIGAMGInterfaceField()
~cyclicAMIGAMGInterfaceField () virtual
Definition at line 83 of file cyclicAMIGAMGInterfaceField.C.
Member Function Documentation
TypeName()
TypeName ("cyclicAMI")
size()
label size () const inline
Definition at line 111 of file cyclicAMIGAMGInterfaceField.H.
References GAMGInterface::size().
updateInterfaceMatrix()
void updateInterfaceMatrix (solveScalarField & result, const bool add, const lduAddressing & lduAddr, const label patchId, const solveScalarField & psiInternal, const scalarField & coeffs, const direction cmpt, const Pstream::commsTypes commsType) const virtual
Implements lduInterfaceField.
Definition at line 89 of file cyclicAMIGAMGInterfaceField.C.
References Foam::add(), lduAddressing::patchAddr(), and patchId().
doTransform()
virtual bool doTransform () const inline virtual
Implements cyclicAMILduInterfaceField.
Definition at line 136 of file cyclicAMIGAMGInterfaceField.H.
forwardT()
virtual const tensorField & forwardT () const inline virtual
Implements cyclicAMILduInterfaceField.
Definition at line 142 of file cyclicAMIGAMGInterfaceField.H.
References cyclicAMIGAMGInterface::forwardT().
reverseT()
virtual const tensorField & reverseT () const inline virtual
Implements cyclicAMILduInterfaceField.
Definition at line 148 of file cyclicAMIGAMGInterfaceField.H.
References cyclicAMIGAMGInterface::reverseT().
rank()
virtual int rank () const inline virtual
Implements cyclicAMILduInterfaceField.
Definition at line 154 of file cyclicAMIGAMGInterfaceField.H.
The documentation for this class was generated from the following files:
src/meshTools/AMIInterpolation/GAMG/interfaceFields/cyclicAMIGAMGInterfaceField/cyclicAMIGAMGInterfaceField.H
src/meshTools/AMIInterpolation/GAMG/interfaceFields/cyclicAMIGAMGInterfaceField/cyclicAMIGAMGInterfaceField.C