OpenFOAM: x3dWriter Class Reference
x3dWriter Class Reference
A surfaceWriter for X3D files.
#include <x3dSurfaceWriter.H>
Public Member Functions
TypeNameNoDebug ("x3d")
x3dWriter ()
x3dWriter (const dictionary &options)
x3dWriter (const meshedSurf &surf, const fileName &outputPath, bool parallel=Pstream::parRun(), const dictionary &options=dictionary())
x3dWriter (const pointField &points, const faceList &faces, const fileName &outputPath, bool parallel=Pstream::parRun(), const dictionary &options=dictionary())
virtual ~x3dWriter ()=default
virtual fileName write ()
declareSurfaceWriterWriteMethod (label)
declareSurfaceWriterWriteMethod (scalar)
declareSurfaceWriterWriteMethod (vector)
declareSurfaceWriterWriteMethod (sphericalTensor)
declareSurfaceWriterWriteMethod (symmTensor)
declareSurfaceWriterWriteMethod (tensor)
template<class Type >
Foam::fileName writeTemplate (const word &fieldName, const Field< Type > &localValues)
Public Member Functions inherited from surfaceWriter
TypeName ("surfaceWriter")
declareRunTimeSelectionTable (autoPtr, surfaceWriter, word,(),())
declareRunTimeSelectionTable (autoPtr, surfaceWriter, wordDict,(const dictionary &writeOpts),(writeOpts))
surfaceWriter ()
surfaceWriter (const dictionary &options)
virtual ~surfaceWriter ()
virtual bool enabled () const
virtual bool separateGeometry () const
virtual bool usesFaceIds () const
virtual bool needsUpdate () const
virtual bool wroteData () const
virtual bool expire ()
virtual void clear ()
virtual void setSurface (const meshedSurf &surf, bool parallel)
virtual void setSurface (const pointField &points, const faceList &faces, bool parallel)
virtual void setSurface (const meshedSurf &surf)
virtual void setSurface (const pointField &points, const faceList &faces)
bool is_open () const noexcept
bool hasSurface () const
bool empty () const
label size () const
label nFields () const noexcept
label nFields (const label n) noexcept
bool isPointData () const noexcept
bool isPointData (const bool on) noexcept
bool useTimeDir () const noexcept
bool useTimeDir (const bool on) noexcept
bool verbose () const noexcept
bool verbose (const bool on) noexcept
scalar mergeDim () const noexcept
scalar mergeDim (const scalar dist) noexcept
scalar scale () const noexcept
scalar scale (const scalar factor) noexcept
const coordSystem::cartesian & transform () const noexcept
bool hasTime () const
const word & timeName () const
scalar timeValue () const
void setTime (const instant &inst)
void setTime (scalar timeValue)
void setTime (scalar timeValue, const word &timeName)
void unsetTime ()
virtual void beginTime (const Time &t)
virtual void beginTime (const instant &inst)
virtual void endTime ()
virtual void open (const fileName &outputPath)
virtual void open (const pointField &points, const faceList &faces, const fileName &outputPath, bool parallel)
virtual void open (const meshedSurf &surf, const fileName &outputPath, bool parallel)
virtual void open (const pointField &points, const faceList &faces, const fileName &outputPath)
virtual void open (const meshedSurf &surf, const fileName &outputPath)
virtual void close ()
virtual fileName write (const word &fieldName, const Field< label > &values)=0
Write field of label (per face or vertex)
virtual fileName write (const word &fieldName, const Field< scalar > &values)=0
Write field of scalar (per face or vertex)
virtual fileName write (const word &fieldName, const Field< vector > &values)=0
Write field of vector (per face or vertex)
virtual fileName write (const word &fieldName, const Field< sphericalTensor > &values)=0
Write field of sphericalTensor (per face or vertex)
virtual fileName write (const word &fieldName, const Field< symmTensor > &values)=0
Write field of symmTensor (per face or vertex)
virtual fileName write (const word &fieldName, const Field< tensor > &values)=0
Write field of tensor (per face or vertex)
virtual InfoProxy< surfaceWriter > info () const noexcept
template<class Type >
Foam::tmp< Foam::Field< Type > > mergeFieldTemplate (const Field< Type > &fld) const
template<class Type >
Foam::tmp< Foam::Field< Type > > adjustFieldTemplate (const word &fieldName, const tmp< Field< Type > > &tfield) const
Additional Inherited Members
Static Public Member Functions inherited from surfaceWriter
static dictionary formatOptions (const dictionary &dict, const word &formatName, const word &entryName="formatOptions")
static dictionary formatOptions (const dictionary &dict, const dictionary &surfDict, const word &formatName, const word &entryName="formatOptions")
static bool supportedType (const word &writeType)
static autoPtr< surfaceWriter > New (const word &writeType)
static autoPtr< surfaceWriter > New (const word &writeType, const dictionary &writeOptions)
Static Public Attributes inherited from surfaceWriter
static scalar defaultMergeDim = 1e-8
Protected Member Functions inherited from surfaceWriter
void checkOpen () const
virtual bool merge () const
const meshedSurf & surface () const
const meshedSurfRef & adjustSurface () const
template<class Type >
tmp< Field< Type > > mergeFieldTemplate (const Field< Type > &fld) const
template<class Type >
tmp< Field< Type > > adjustFieldTemplate (const word &fieldName, const tmp< Field< Type > > &tfield) const
tmp< Field< label > > mergeField (const Field< label > &fld) const
tmp< Field< label > > adjustField (const word &fieldName, const tmp< Field< label > > &tfield) const
tmp< Field< scalar > > mergeField (const Field< scalar > &fld) const
tmp< Field< scalar > > adjustField (const word &fieldName, const tmp< Field< scalar > > &tfield) const
tmp< Field< vector > > mergeField (const Field< vector > &fld) const
tmp< Field< vector > > adjustField (const word &fieldName, const tmp< Field< vector > > &tfield) const
tmp< Field< sphericalTensor > > mergeField (const Field< sphericalTensor > &fld) const
tmp< Field< sphericalTensor > > adjustField (const word &fieldName, const tmp< Field< sphericalTensor > > &tfield) const
tmp< Field< symmTensor > > mergeField (const Field< symmTensor > &fld) const
tmp< Field< symmTensor > > adjustField (const word &fieldName, const tmp< Field< symmTensor > > &tfield) const
tmp< Field< tensor > > mergeField (const Field< tensor > &fld) const
tmp< Field< tensor > > adjustField (const word &fieldName, const tmp< Field< tensor > > &tfield) const
template<class Type >
fileName writeTemplate (const word &fieldName, const Field< Type > &localValues)
Static Protected Member Functions inherited from X3DsurfaceFormatCore
static void writeHeader (Ostream &os)
static void writeFooter (Ostream &os)
static void beginGroup (Ostream &os)
static void endGroup (Ostream &os)
static void writeAppearance (Ostream &os)
static void writePoints (Ostream &os, const UList< point > &pts)
Protected Attributes inherited from surfaceWriter
meshedSurfRef surf_
mergedSurf mergedSurf_
meshedSurfRef adjustedSurf_
scalar mergeDim_
scalar geometryScale_
point geometryCentre_
coordSystem::cartesian geometryTransform_
bool upToDate_
bool wroteGeom_
bool parallel_
bool useTimeDir_
bool isPointData_
bool verbose_
UPstream::commsTypes commType_
label nFields_
instant currTime_
fileName outputPath_
dictionary fieldLevel_
dictionary fieldScale_
Detailed Description
A surfaceWriter for X3D files.
The formatOptions for x3d:
Property Description Required Default
range The min/max range for colour table no automatic
colourMap The colour map for rendering no coolToWarm
compression Use file compression no false
scale Output geometry scaling no 1
transform Output coordinate transform no
fieldLevel Subtract field level before scaling no empty dict
fieldScale Output field scaling no empty dict
file locations
The rootdir normally corresponds to something like postProcessing/<name>
Geometry
    rootdir
    `-- timeName
        `-- surfaceName.x3d
Fields
    rootdir
    `-- timeName
        |-- <field0>_surfaceName.x3d
        `-- <field1>_surfaceName.x3d
Note
The range is applied after any field scaling.
Source files
x3dSurfaceWriter.H
x3dSurfaceWriter.C
Definition at line 126 of file x3dSurfaceWriter.H.
Constructor & Destructor Documentation
x3dWriter() [1/4]
x3dWriter ()
Definition at line 107 of file x3dSurfaceWriter.C.
x3dWriter() [2/4]
x3dWriter (const dictionary & options) explicit
Definition at line 116 of file x3dSurfaceWriter.C.
References colourTable::COOL_WARM, Foam::Info, Foam::nl, colourTable::predefinedNames, colourTable::ptr(), dictionary::readIfPresent(), MinMax< T >::valid(), surfaceWriter::verbose_, and WarningInFunction.
x3dWriter() [3/4]
x3dWriter (const meshedSurf & surf, const fileName & outputPath, bool parallel = Pstream::parRun(), const dictionary & options = dictionary())
Definition at line 168 of file x3dSurfaceWriter.C.
References surfaceWriter::open().
x3dWriter() [4/4]
x3dWriter (const pointField & points, const faceList & faces, const fileName & outputPath, bool parallel = Pstream::parRun(), const dictionary & options = dictionary())
Definition at line 182 of file x3dSurfaceWriter.C.
References surfaceWriter::open(), and points.
~x3dWriter()
virtual ~x3dWriter () virtual default
Member Function Documentation
TypeNameNoDebug()
TypeNameNoDebug ("x3d")
write()
Foam::fileName write () virtual
Implements surfaceWriter.
Definition at line 199 of file x3dSurfaceWriter.C.
References Foam::endl(), meshedSurfRef::faces(), Foam::Info, Foam::isDir(), UPstream::master(), Foam::mkDir(), meshedSurfRef::points(), and timeName.
declareSurfaceWriterWriteMethod() [1/6]
declareSurfaceWriterWriteMethod (label)
declareSurfaceWriterWriteMethod() [2/6]
declareSurfaceWriterWriteMethod (scalar)
declareSurfaceWriterWriteMethod() [3/6]
declareSurfaceWriterWriteMethod (vector)
declareSurfaceWriterWriteMethod() [4/6]
declareSurfaceWriterWriteMethod (sphericalTensor)
declareSurfaceWriterWriteMethod() [5/6]
declareSurfaceWriterWriteMethod (symmTensor)
declareSurfaceWriterWriteMethod() [6/6]
declareSurfaceWriterWriteMethod (tensor)
writeTemplate()
template<class Type > Foam::fileName writeTemplate (const word & fieldName, const Field< Type > & localValues)
Definition at line 244 of file x3dSurfaceWriter.C.
References Foam::endl(), Foam::equal(), f(), meshedSurfRef::faces(), Foam::Info, Foam::isDir(), UPstream::master(), Foam::minMaxMag(), Foam::mkDir(), Foam::nl, os(), meshedSurfRef::points(), Foam::printColour(), range, Foam::rangex(), UPtrList< T >::size(), timeName, WarningInFunction, write(), Foam::writeHeader(), and x.
The documentation for this class was generated from the following files:
src/surfMesh/writers/x3d/x3dSurfaceWriter.H
src/surfMesh/writers/x3d/x3dSurfaceWriter.C