OpenFOAM: faceCoupleInfo Class Reference
faceCoupleInfo Class Reference
Container for information needed to couple to meshes. When constructed from two meshes and a geometric tolerance finds the corresponding boundary faces.
#include <faceCoupleInfo.H>
Public Member Functions
ClassName ("faceCoupleInfo")
faceCoupleInfo (const polyMesh &mesh0, const polyMesh &mesh1, const scalar absTol, const bool perfectMatch)
faceCoupleInfo (const polyMesh &masterMesh, const labelList &masterAddressing, const polyMesh &slaveMesh, const labelList &slaveAddressing, const scalar absTol, const bool perfectMatch, const bool orderedFaces, const bool patchDivision)
~faceCoupleInfo ()=default
const indirectPrimitivePatch & masterPatch () const
const indirectPrimitivePatch & slavePatch () const
const primitiveFacePatch & cutFaces () const
const pointField & cutPoints () const
const labelList & cutToMasterFaces () const
const labelList & masterToCutPoints () const
const labelList & cutToSlaveFaces () const
const labelList & slaveToCutPoints () const
const EdgeMap< labelList > & cutEdgeToPoints () const noexcept
template<template< class > class FaceList>
Foam::pointField calcFaceCentres (const FaceList< face > &faces, const pointField &points, const label start, const label size)
template<template< class > class FaceList>
Foam::pointField calcFacePointAverages (const FaceList< face > &faces, const pointField &points, const label start, const label size)
Static Public Member Functions
static labelList faceLabels (const polyPatch &)
static Map< label > makeMap (const labelList &)
static Map< labelList > makeMap (const labelListList &)
Detailed Description
Container for information needed to couple to meshes. When constructed from two meshes and a geometric tolerance finds the corresponding boundary faces.
The information it keeps is the set of faces&points (cutFaces, cutPoints) that should replace a set of faces on the master (masterPatch) and a set of faces on the slave (slavePatch)
Uses same tolerance to match faces and points on matched faces since they both originate from the same points and the tolerance usually comes from writing these points with limited precision (6 by default)
Perfect match:
one-to-one match for faces and points.
the cut is always the 'most connected' of the master and slave so multiple master or slave points might point to the same cut point.
e.g. master:
    +--+
    |  |
    |  |
    +--+
        +--+
        |  |
        |  |
        +--+
slave:
        +--+
        |  |
        |  |
        +--+
    +--+
    |  |
    |  |
    +--+
adding both together creates a singly connected 2x2 cavity so suddenly the duplicate master points and the duplicate slave points all become a single cut point.
Subdivision match:
Can be constructed from slave being subdivision of master with the polyPatch constructor.
Does not include above shared-point detection!
Notes on multiple slave faces per master:
As long as
all master edges are present in slave
slave can have extra edges/points/faces BUT all subfaces have to have at least one point on a maste face.
So master:
+-------+
|       |
|       |
|       |
|       |
|       |
|       |
|       |
+-------+
slave:
+---+---+
|\  |  /|
| \ | / |
|  \|/  |
+---+---+
|  /|\  |
| / | \ |
|/  |  \|
+---+---+
is ok.
For this kind of matching the order is:
match cutpoint to masterpoint
find those cutEdges that align with a master edge. This gives two sets of cut edges: those that have a master equivalent ('border edges') and those that don't ('internal edges'). The border edges now divide the cutFaces into regions with the same masterFace correspondence.
find cutFaces that are fully determined by the border edges they use.
all cutFaces that are connected through an internal edge have the same master face.
Note: matching refined faces onto master is a bit dodgy and will probably only work for unwarped faces. Also it will fail if e.g. face is split into 3x3 since then middle face has no point/edge in common with master. (problem is in face matching (findSlavesCoveringMaster), probably point/edge matching might just work)
Source files
faceCoupleInfo.H
faceCoupleInfo.C
Definition at line 152 of file faceCoupleInfo.H.
Constructor & Destructor Documentation
faceCoupleInfo() [1/2]
faceCoupleInfo (const polyMesh & mesh0, const polyMesh & mesh1, const scalar absTol, const bool perfectMatch)
Definition at line 1906 of file faceCoupleInfo.C.
faceCoupleInfo() [2/2]
faceCoupleInfo (const polyMesh & masterMesh, const labelList & masterAddressing, const polyMesh & slaveMesh, const labelList & slaveAddressing, const scalar absTol, const bool perfectMatch, const bool orderedFaces, const bool patchDivision)
Definition at line 1994 of file faceCoupleInfo.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, Foam::min(), Foam::nl, and UPtrList< T >::size().
~faceCoupleInfo()
~faceCoupleInfo () default
Member Function Documentation
ClassName()
ClassName ("faceCoupleInfo")
faceLabels()
Foam::labelList faceLabels (const polyPatch & pp) static
Definition at line 2083 of file faceCoupleInfo.C.
References forAll, and pp().
makeMap() [1/2]
Foam::Map< Foam::label > makeMap (const labelList & lst) static
Definition at line 2097 of file faceCoupleInfo.C.
References forAll, and UPtrList< T >::size().
makeMap() [2/2]
Foam::Map< Foam::labelList > makeMap (const labelListList & lst) static
Definition at line 2112 of file faceCoupleInfo.C.
References forAll, and UPtrList< T >::size().
masterPatch()
const indirectPrimitivePatch & masterPatch () const inline
Definition at line 447 of file faceCoupleInfo.H.
slavePatch()
const indirectPrimitivePatch & slavePatch () const inline
Definition at line 453 of file faceCoupleInfo.H.
cutFaces()
const primitiveFacePatch & cutFaces () const inline
Definition at line 459 of file faceCoupleInfo.H.
cutPoints()
const pointField & cutPoints () const inline
Definition at line 465 of file faceCoupleInfo.H.
cutToMasterFaces()
const labelList & cutToMasterFaces () const inline
Definition at line 476 of file faceCoupleInfo.H.
masterToCutPoints()
const labelList & masterToCutPoints () const inline
Definition at line 480 of file faceCoupleInfo.H.
cutToSlaveFaces()
const labelList & cutToSlaveFaces () const inline
Definition at line 485 of file faceCoupleInfo.H.
slaveToCutPoints()
const labelList & slaveToCutPoints () const inline
Definition at line 489 of file faceCoupleInfo.H.
cutEdgeToPoints()
const EdgeMap< labelList > & cutEdgeToPoints () const inline noexcept
Definition at line 495 of file faceCoupleInfo.H.
calcFaceCentres()
template<template< class > class FaceList> Foam::pointField calcFaceCentres (const FaceList< face > & faces, const pointField & points, const label start, const label size)
Definition at line 27 of file faceCoupleInfoTemplates.C.
References forAll, and points.
calcFacePointAverages()
template<template< class > class FaceList> Foam::pointField calcFacePointAverages (const FaceList< face > & faces, const pointField & points, const label start, const label size)
Definition at line 48 of file faceCoupleInfoTemplates.C.
References forAll, points, UPtrList< T >::size(), and Foam::Zero.
The documentation for this class was generated from the following files:
src/dynamicMesh/polyMeshAdder/faceCoupleInfo.H
src/dynamicMesh/polyMeshAdder/faceCoupleInfo.C
src/dynamicMesh/polyMeshAdder/faceCoupleInfoTemplates.C