OpenFOAM: edge Class Reference
edge Class Reference
An edge is a list of two vertex labels. This can correspond to a directed graph edge or an edge on a mesh.
#include <edge.H>
Classes
struct Hash
struct hasher
Public Member Functions
edge ()
edge (const label from, const label to)
edge (const labelPair &pair)
edge (const FixedList< label, 2 > &list)
edge (const label from, const label to, const bool doSort)
edge (const FixedList< label, 2 > &list, const bool doSort)
edge (const UList< label > &list, const FixedList< label, 2 > &indices)
edge (Istream &is)
label a () const noexcept
label b () const noexcept
label & a () noexcept
label & b () noexcept
label start () const noexcept
label end () const noexcept
label & start () noexcept
label & end () noexcept
edge reverseEdge () const
label minVertex () const noexcept
label maxVertex () const noexcept
bool good () const noexcept
bool contains (const label vertex) const noexcept
label which (const label vertex) const
bool connected (const edge &other) const
label commonVertex (const edge &other) const
label otherVertex (const label vertex) const
bool connects (const edge &other) const
label collapse ()
label count () const
bool empty () const noexcept
void clear ()
bool insert (const label vertex)
template<class InputIterator >
label insert (InputIterator begIter, InputIterator endIter)
label insert (std::initializer_list< label > list)
template<unsigned N>
label insert (const FixedList< label, N > &list)
label insert (const labelUList &list)
label erase (const label vertex)
template<class InputIterator >
label erase (InputIterator begIter, InputIterator endIter)
label erase (std::initializer_list< label > list)
template<unsigned N>
label erase (const FixedList< label, N > &list)
label erase (const labelUList &list)
point centre (const UList< point > &pts) const
vector vec (const UList< point > &pts) const
vector unitVec (const UList< point > &pts) const
scalar mag (const UList< point > &pts) const
scalar magSqr (const UList< point > &pts) const
Pair< point > box (const UList< point > &pts) const
linePointRef line (const UList< point > &pts) const
label & operator[] (const label i)
const label & operator[] (const label i) const
unsigned hash_code (unsigned seed=0) const
bool found (label vertex) const
bool valid () const noexcept
template<class InputIterator >
Foam::label insert (InputIterator begIter, InputIterator endIter)
template<unsigned N>
Foam::label insert (const FixedList< label, N > &list)
template<class InputIterator >
Foam::label erase (InputIterator begIter, InputIterator endIter)
template<unsigned N>
Foam::label erase (const FixedList< label, N > &list)
Public Member Functions inherited from Pair< label >
Pair ()=default
Pair (const label &f, const label &s)
Pair (label &&f, label &&s)
Pair (const std::pair< label, label > &vals)
Pair (std::pair< label, label > &&vals)
Pair (const FixedList< label, 2 > &list)
Pair (const label &f, const label &s, const bool doSort)
Pair (const FixedList< label, 2 > &list, const bool doSort)
Pair (Istream &is)
void front ()=delete
void back ()=delete
const label & first () const noexcept
label & first () noexcept
const label & second () const noexcept
label & second () noexcept
const label & other (const label &a) const
bool sorted () const
void flip ()
void sort ()
Public Member Functions inherited from FixedList< T, N >
FixedList ()=default
FixedList (const T &val)
FixedList (const Foam::zero)
FixedList (const T list[N])
FixedList (const FixedList< T, N > &list)
FixedList (FixedList< T, N > &&list)
FixedList (std::initializer_list< T > list)
FixedList (const UList< T > &list)
template<unsigned AnyNum>
FixedList (const FixedList< T, AnyNum > &list, const FixedList< label, N > &indices)
FixedList (const UList< T > &list, const FixedList< label, N > &indices)
FixedList (const SLList< T > &list)
FixedList (Istream &is)
autoPtr< FixedList< T, N > > clone () const
const T * cdata () const noexcept
T * data () noexcept
const char * cdata_bytes () const noexcept
char * data_bytes () noexcept
template<unsigned Index>
T & get () noexcept
template<unsigned Index>
const T & get () const noexcept
T & front () noexcept
const T & front () const noexcept
T & back () noexcept
const T & back () const noexcept
label fcIndex (const label i) const
const T & fcValue (const label i) const
T & fcValue (const label i)
label rcIndex (const label i) const
const T & rcValue (const label i) const
T & rcValue (const label i)
void checkStart (const label start) const
void checkSize (const label size) const
void checkIndex (const label i) const
bool uniform () const
label find (const T &val, label pos=0) const
label rfind (const T &val, label pos=-1) const
bool contains (const T &val, label pos=0) const
void resize (const label n)
void resize_nocopy (const label n)
void setSize (const label n)
void fill (const T &val)
void fill (const Foam::zero)
void moveFirst (const label i)
void moveLast (const label i)
void swapFirst (const label i)
void swapLast (const label i)
void transfer (FixedList< T, N > &list)
T & operator[] (const label i)
const T & operator[] (const label i) const
void operator= (const T list[N])
void operator= (const UList< T > &list)
void operator= (const SLList< T > &list)
void operator= (std::initializer_list< T > list)
void operator= (const T &val)
void operator= (const Foam::zero)
void operator= (const FixedList< T, N > &list)
void operator= (FixedList< T, N > &&list)
iterator begin () noexcept
iterator end () noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
const_iterator begin () const noexcept
const_iterator end () const noexcept
reverse_iterator rbegin ()
reverse_iterator rend ()
const_reverse_iterator crbegin () const
const_reverse_iterator crend () const
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
void swap (FixedList< T, N > &other)
bool operator== (const FixedList< T, N > &list) const
bool operator!= (const FixedList< T, N > &list) const
bool operator< (const FixedList< T, N > &list) const
bool operator> (const FixedList< T, N > &list) const
bool operator<= (const FixedList< T, N > &list) const
bool operator>= (const FixedList< T, N > &list) const
Istream & readList (Istream &is)
void writeEntry (const word &keyword, Ostream &os) const
Ostream & writeList (Ostream &os, const label shortLen=0) const
T & first () noexcept
const T & first () const noexcept
T & last () noexcept
const T & last () const noexcept
bool found (const T &val, label pos=0) const
Static Public Member Functions
static int compare (const edge &a, const edge &b)
Static Public Member Functions inherited from Pair< label >
static int compare (const Pair< label > &a, const Pair< label > &b)
Static Public Member Functions inherited from FixedList< T, N >
static const FixedList< T, N > & null ()
static std::streamsize size_bytes () noexcept
static std::streamsize byteSize ()
static constexpr bool empty () noexcept
static constexpr label size () noexcept
static constexpr unsigned max_size () noexcept
Static Public Attributes
static const char *const typeName = "edge"
Additional Inherited Members
Public Types inherited from FixedList< T, N >
typedef T value_type
typedef T * pointer
typedef const T * const_pointer
typedef T & reference
typedef const T & const_reference
typedef T * iterator
typedef const T * const_iterator
typedef label size_type
typedef label difference_type
typedef std::reverse_iterator< iterator > reverse_iterator
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
Protected Member Functions inherited from FixedList< T, N >
void writeEntry (Ostream &os) const
Detailed Description
An edge is a list of two vertex labels. This can correspond to a directed graph edge or an edge on a mesh.
The edge is implemented as a Pair/FixedList of labels. As well as geometrically relevant methods, it also provides methods similar to HashSet for additional convenience. Valid vertex labels are always non-negative (eg, since they correspond to addressing within the mesh). The value '-1' is used to tag invalid point labels that correspond conceptually to open 'slots', which can be filled with a HashSet-like functionality.
Source files
edge.H
edge.C
edgeI.H
Definition at line 59 of file edge.H.
Constructor & Destructor Documentation
edge() [1/8]
edge () inline
Definition at line 34 of file edgeI.H.
Referenced by cellShape::edge(), and Foam::levelSetFraction().
edge() [2/8]
edge (const label from, const label to) inline
Definition at line 40 of file edgeI.H.
edge() [3/8]
edge (const labelPair & pair) inline
Definition at line 46 of file edgeI.H.
edge() [4/8]
edge (const FixedList< label, 2 > & list) inline
Definition at line 52 of file edgeI.H.
edge() [5/8]
edge (const label from, const label to, const bool doSort) inline
Definition at line 58 of file edgeI.H.
edge() [6/8]
edge (const FixedList< label, 2 > & list, const bool doSort) inline
Definition at line 64 of file edgeI.H.
edge() [7/8]
edge (const UList< label > & list, const FixedList< label, 2 > & indices) inline
Definition at line 70 of file edgeI.H.
edge() [8/8]
edge (Istream & is) inline
Definition at line 80 of file edgeI.H.
Member Function Documentation
a() [1/2]
label a () const inline noexcept
Definition at line 107 of file edge.H.
References Pair< label >::first().
Referenced by edge::compare().
b() [1/2]
label b () const inline noexcept
Definition at line 110 of file edge.H.
References Pair< label >::second().
Referenced by edge::compare().
a() [2/2]
label & a () inline noexcept
Definition at line 113 of file edge.H.
References Pair< label >::first().
b() [2/2]
label & b () inline noexcept
Definition at line 116 of file edge.H.
References Pair< label >::second().
start() [1/2]
label start () const inline noexcept
Definition at line 119 of file edge.H.
References Pair< label >::first().
Referenced by directionInfo::edgeToFaceIndex(), cellFeatures::isFeaturePoint(), line< Point, PointRef >::nearestDist(), and PatchTools::sortedPointEdges().
end() [1/2]
label end () const inline noexcept
Definition at line 122 of file edge.H.
References Pair< label >::second().
Referenced by directionInfo::edgeToFaceIndex(), cellFeatures::isFeaturePoint(), line< Point, PointRef >::nearestDist(), and PatchTools::sortedPointEdges().
start() [2/2]
label & start () inline noexcept
Definition at line 125 of file edge.H.
References Pair< label >::first().
end() [2/2]
label & end () inline noexcept
Definition at line 128 of file edge.H.
References Pair< label >::second().
reverseEdge()
Foam::edge reverseEdge () const inline
Definition at line 195 of file edgeI.H.
Referenced by hexCell::reverseEdge(), and tetCell::reverseEdge().
minVertex()
Foam::label minVertex () const inline noexcept
Definition at line 88 of file edgeI.H.
maxVertex()
Foam::label maxVertex () const inline noexcept
Definition at line 94 of file edgeI.H.
good()
bool good () const inline noexcept
Definition at line 100 of file edgeI.H.
Referenced by edge::valid().
contains()
bool contains (const label vertex) const inline noexcept
Definition at line 106 of file edgeI.H.
Referenced by edge::commonVertex(), edge::connected(), and edge::found().
which()
Foam::label which (const label vertex) const inline
Definition at line 117 of file edgeI.H.
connected()
bool connected (const edge & other) const inline
Definition at line 136 of file edgeI.H.
References edge::contains().
Referenced by Foam::calcProximityOfFeatureEdges(), and edge::connects().
commonVertex()
Foam::label commonVertex (const edge & other) const inline
Definition at line 142 of file edgeI.H.
References edge::contains().
Referenced by GTSsurfaceFormat< Face >::read().
otherVertex()
Foam::label otherVertex (const label vertex) const inline
Definition at line 158 of file edgeI.H.
Referenced by removePoints::countPointUsage(), and GTSsurfaceFormat< Face >::read().
connects()
bool connects (const edge & other) const inline
Definition at line 170 of file edge.H.
References edge::connected(), and Pair< label >::other().
collapse()
Foam::label collapse () inline
Definition at line 174 of file edgeI.H.
References n.
count()
Foam::label count () const inline
Definition at line 208 of file edgeI.H.
References n.
empty()
bool empty () const inline noexcept
Definition at line 224 of file edgeI.H.
clear()
void clear () inline
Definition at line 201 of file edgeI.H.
insert() [1/7]
bool insert (const label vertex) inline
Definition at line 230 of file edgeI.H.
insert() [2/7]
template<class InputIterator > label insert (InputIterator begIter, InputIterator endIter) inline
insert() [3/7]
Foam::label insert (std::initializer_list< label > list) inline
Definition at line 285 of file edgeI.H.
References insert().
insert() [4/7]
template<unsigned N> label insert (const FixedList< label, N > & list) inline
insert() [5/7]
Foam::label insert (const labelUList & list) inline
Definition at line 298 of file edgeI.H.
References UList< T >::begin(), UList< T >::end(), and insert().
erase() [1/7]
Foam::label erase (const label vertex) inline
Definition at line 304 of file edgeI.H.
References n.
erase() [2/7]
template<class InputIterator > label erase (InputIterator begIter, InputIterator endIter) inline
erase() [3/7]
Foam::label erase (std::initializer_list< label > list) inline
Definition at line 351 of file edgeI.H.
References erase().
erase() [4/7]
template<unsigned N> label erase (const FixedList< label, N > & list) inline
erase() [5/7]
Foam::label erase (const labelUList & list) inline
Definition at line 364 of file edgeI.H.
References UList< T >::begin(), UList< T >::end(), and erase().
centre()
Foam::point centre (const UList< point > & pts) const inline
Definition at line 372 of file edgeI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and pts.
vec()
Foam::vector vec (const UList< point > & pts) const inline
Definition at line 387 of file edgeI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and pts.
unitVec()
Foam::vector unitVec (const UList< point > & pts) const inline
Definition at line 402 of file edgeI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, Foam::mag(), pts, s(), and Foam::Zero.
Referenced by cellFeatures::isFeaturePoint().
mag()
Foam::scalar mag (const UList< point > & pts) const inline
Definition at line 420 of file edgeI.H.
References pts.
magSqr()
Foam::scalar magSqr (const UList< point > & pts) const inline
Definition at line 426 of file edgeI.H.
References pts.
box()
Foam::Pair< Foam::point > box (const UList< point > & pts) const inline
Definition at line 433 of file edgeI.H.
References Foam::abort(), line< Point, PointRef >::box(), Foam::FatalError, FatalErrorInFunction, and pts.
line()
Foam::linePointRef line (const UList< point > & pts) const inline
Definition at line 448 of file edgeI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and pts.
compare()
int compare (const edge & a, const edge & b) inline static
Definition at line 26 of file edgeI.H.
References edge::a(), edge::b(), and Pair< label >::compare().
Referenced by triSurfaceMesh::addFaceToEdge(), Foam::operator!=(), Foam::operator==(), syncTools::syncEdgeList(), and syncTools::syncEdgeList().
operator[]() [1/2]
Foam::label & operator[] (const label i) inline
Definition at line 465 of file edgeI.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
operator[]() [2/2]
const Foam::label & operator[] (const label i) const inline
Definition at line 478 of file edgeI.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
hash_code()
unsigned hash_code (unsigned seed = 0) const inline
Definition at line 300 of file edge.H.
References Pair< label >::first(), and Pair< label >::second().
found()
bool found (label vertex) const inline
Definition at line 327 of file edge.H.
References edge::contains().
valid()
bool valid () const inline noexcept
Definition at line 330 of file edge.H.
References edge::good().
insert() [6/7]
template<class InputIterator > Foam::label insert (InputIterator begIter, InputIterator endIter) inline
Definition at line 262 of file edgeI.H.
References insert().
insert() [7/7]
template<unsigned N> Foam::label insert (const FixedList< label, N > & list) inline
Definition at line 292 of file edgeI.H.
References UPtrList< T >::begin(), UPtrList< T >::end(), and insert().
erase() [6/7]
template<class InputIterator > Foam::label erase (InputIterator begIter, InputIterator endIter) inline
Definition at line 331 of file edgeI.H.
References erase().
erase() [7/7]
template<unsigned N> Foam::label erase (const FixedList< label, N > & list) inline
Definition at line 358 of file edgeI.H.
References UPtrList< T >::begin(), UPtrList< T >::end(), and erase().
Member Data Documentation
typeName
const char *const typeName = "edge" static
Definition at line 68 of file edge.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/meshShapes/edge/edge.H
src/OpenFOAM/meshes/meshShapes/edge/edge.C
src/OpenFOAM/meshes/meshShapes/edge/edgeI.H