OpenFOAM: topoSetSource Class Reference
topoSetSource Class Reference abstract
Base class of a source for a topoSet.
#include <topoSetSource.H>
Classes
class addToUsageTable
class iNew
Public Types
enum sourceType {
UNKNOWN_SOURCE = 0 , CELL_TYPE = 0x1 , FACE_TYPE = 0x2 , POINT_TYPE = 0x4 ,
SET_SOURCE = 0x10 , CELLSET_SOURCE = (CELL_TYPE | SET_SOURCE) , FACESET_SOURCE = (FACE_TYPE | SET_SOURCE) , POINTSET_SOURCE = (POINT_TYPE | SET_SOURCE) ,
ZONE_SOURCE = 0x20 , CELLZONE_SOURCE = (CELL_TYPE | ZONE_SOURCE) , FACEZONE_SOURCE = (FACE_TYPE | ZONE_SOURCE) , POINTZONE_SOURCE = (POINT_TYPE | ZONE_SOURCE) ,
CELLSETSOURCE = CELLSET_SOURCE , FACESETSOURCE = FACESET_SOURCE , POINTSETSOURCE = POINTSET_SOURCE , CELLZONESOURCE = CELLZONE_SOURCE ,
FACEZONESOURCE = FACEZONE_SOURCE , POINTZONESOURCE = POINTZONE_SOURCE
}
enum setAction {
ADD , SUBTRACT , NEW , SUBSET ,
INVERT , CLEAR , REMOVE , LIST ,
IGNORE , DELETE = SUBTRACT
}
Public Member Functions
TypeName ("topoSetSource")
declareRunTimeSelectionTable (autoPtr, topoSetSource, word,(const polyMesh &mesh, const dictionary &dict),(mesh, dict))
declareRunTimeSelectionTable (autoPtr, topoSetSource, istream,(const polyMesh &mesh, Istream &is),(mesh, is))
topoSetSource (const polyMesh &mesh, bool verbose=true)
topoSetSource (const polyMesh &mesh, const dictionary &dict)
autoPtr< topoSetSource > clone () const
virtual ~topoSetSource ()=default
const polyMesh & mesh () const noexcept
bool verbose () const noexcept
bool verbose (bool on) noexcept
void verbose (const dictionary &dict)
virtual sourceType setType () const =0
virtual void applyToSet (const topoSetSource::setAction action, topoSet &set) const =0
Static Public Member Functions
static Istream & checkIs (Istream &is)
static bool isSetSource (const sourceType t) noexcept
static bool isZoneSource (const sourceType t) noexcept
static bool isCell (const sourceType t) noexcept
static bool isFace (const sourceType t) noexcept
static bool isPoint (const sourceType t) noexcept
static const string & usage (const word &name)
static autoPtr< topoSetSource > New (const word &topoSetSourceType, const polyMesh &mesh, const dictionary &dict)
static autoPtr< topoSetSource > New (const word &topoSetSourceType, const polyMesh &mesh, Istream &is)
static setAction toAction (const word &actionName)
Static Public Attributes
static const Enum< setAction > actionNames
static const Enum< setAction > combineNames
Protected Member Functions
void addOrDelete (topoSet &set, const label id, const bool add) const
void addOrDelete (topoSet &set, const labelUList &labels, const bool add) const
void addOrDelete (topoSet &set, const bitSet &labels, const bool add) const
topoSetSource (const topoSetSource &)=delete
void operator= (const topoSetSource &)=delete
Static Protected Member Functions
static bool check (labelList &list, const label maxLabel)
Protected Attributes
const polyMesh & mesh_
bool verbose_
Static Protected Attributes
static const string illegalSource_
static HashTable< string > * usageTablePtr_ = nullptr
Detailed Description
Base class of a source for a topoSet.
Implementer must modify the given set (see applyToSet) according to its function and the setAction (one of ADD/SUBTRACT/NEW).
Source files
topoSetSource.H
topoSetSource.C
Definition at line 63 of file topoSetSource.H.
Member Enumeration Documentation
sourceType
enum sourceType
Enumerator
UNKNOWN_SOURCE
Placeholder.
CELL_TYPE
Geometric type is "cell".
FACE_TYPE
Geometric type is "face".
POINT_TYPE
Geometric type is "point".
SET_SOURCE
A source based on topoSet.
CELLSET_SOURCE
Cells as set.
FACESET_SOURCE
Faces as set.
POINTSET_SOURCE
Points as set.
ZONE_SOURCE
A source based on mesh zone.
CELLZONE_SOURCE
Cells as zone.
FACEZONE_SOURCE
Faces as zone.
POINTZONE_SOURCE
Points as zone.
CELLSETSOURCE
FACESETSOURCE
POINTSETSOURCE
CELLZONESOURCE
FACEZONESOURCE
POINTZONESOURCE
Definition at line 70 of file topoSetSource.H.
setAction
enum setAction
Enumerator
ADD
Add elements to current set.
SUBTRACT
Subtract elements from current set.
NEW
Create a new set and ADD elements to it.
SUBSET
Union of elements with current set.
INVERT
Invert the elements in the current set.
CLEAR
Clear the set, possibly creating it.
REMOVE
Remove the set (from the file system)
LIST
Print contents of the set.
IGNORE
"ignore" no-op action
DELETE
Deprecated:
(2018-10) Alias for SUBTRACT
Definition at line 96 of file topoSetSource.H.
Constructor & Destructor Documentation
topoSetSource() [1/3]
topoSetSource (const topoSetSource &) protected delete
topoSetSource() [2/3]
topoSetSource (const polyMesh & mesh, bool verbose = true) explicit
Definition at line 241 of file topoSetSource.C.
topoSetSource() [3/3]
topoSetSource (const polyMesh & mesh, const dictionary & dict)
Definition at line 252 of file topoSetSource.C.
References dict, and topoSetSource::verbose().
~topoSetSource()
virtual ~topoSetSource () virtual default
Member Function Documentation
check()
bool check (labelList & list, const label maxLabel) static protected
Definition at line 83 of file topoSetSource.C.
References List< T >::resize(), and UList< T >::size().
Referenced by labelToCell::labelToCell(), labelToFace::labelToFace(), and labelToPoint::labelToPoint().
addOrDelete() [1/3]
void addOrDelete (topoSet & set, const label id, const bool add) const protected
Definition at line 179 of file topoSetSource.C.
References Foam::add(), and PtrList< T >::set().
addOrDelete() [2/3]
void addOrDelete (topoSet & set, const labelUList & labels, const bool add) const protected
Definition at line 197 of file topoSetSource.C.
References Foam::add(), and PtrList< T >::set().
addOrDelete() [3/3]
void addOrDelete (topoSet & set, const bitSet & labels, const bool add) const protected
Definition at line 215 of file topoSetSource.C.
References Foam::add(), and PtrList< T >::set().
operator=()
void operator= (const topoSetSource &) protected delete
TypeName()
TypeName ("topoSetSource")
checkIs()
Foam::Istream & checkIs (Istream & is) static
Definition at line 165 of file topoSetSource.C.
References Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
Referenced by cylinderToCell::cylinderToCell(), cylinderToFace::cylinderToFace(), and cylinderToPoint::cylinderToPoint().
isSetSource()
static bool isSetSource (const sourceType t) inline static noexcept
Definition at line 212 of file topoSetSource.H.
References topoSetSource::SET_SOURCE.
isZoneSource()
static bool isZoneSource (const sourceType t) inline static noexcept
Definition at line 218 of file topoSetSource.H.
References topoSetSource::ZONE_SOURCE.
isCell()
static bool isCell (const sourceType t) inline static noexcept
Definition at line 224 of file topoSetSource.H.
References topoSetSource::CELL_TYPE.
isFace()
static bool isFace (const sourceType t) inline static noexcept
Definition at line 230 of file topoSetSource.H.
References topoSetSource::FACE_TYPE.
isPoint()
static bool isPoint (const sourceType t) inline static noexcept
Definition at line 236 of file topoSetSource.H.
References topoSetSource::POINT_TYPE.
declareRunTimeSelectionTable() [1/2]
declareRunTimeSelectionTable (autoPtr , topoSetSource , word , (const polyMesh &mesh, const dictionary &dict) , (mesh, dict))
declareRunTimeSelectionTable() [2/2]
declareRunTimeSelectionTable (autoPtr , topoSetSource , istream , (const polyMesh &mesh, Istream &is) , (mesh, is))
usage()
static const string & usage (const word & name) inline static
Definition at line 293 of file topoSetSource.H.
References topoSetSource::illegalSource_, Foam::name(), and topoSetSource::usageTablePtr_.
clone()
autoPtr< topoSetSource > clone () const inline
Definition at line 314 of file topoSetSource.H.
References NotImplemented.
New() [1/2]
Foam::autoPtr< Foam::topoSetSource > New (const word & topoSetSourceType, const polyMesh & mesh, const dictionary & dict) static
Definition at line 118 of file topoSetSource.C.
References dict, Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, and mesh.
Referenced by topoSetSource::iNew::operator()().
New() [2/2]
Foam::autoPtr< Foam::topoSetSource > New (const word & topoSetSourceType, const polyMesh & mesh, Istream & is) static
Definition at line 142 of file topoSetSource.C.
References Foam::exit(), Foam::FatalError, FatalErrorInLookup, and mesh.
mesh()
const polyMesh & mesh () const inline noexcept
Definition at line 347 of file topoSetSource.H.
References topoSetSource::mesh_.
Referenced by labelToCell::labelToCell(), labelToFace::labelToFace(), and labelToPoint::labelToPoint().
verbose() [1/3]
bool verbose () const inline noexcept
Definition at line 353 of file topoSetSource.H.
References topoSetSource::verbose_.
Referenced by topoSetSource::topoSetSource().
verbose() [2/3]
bool verbose (bool on) inline noexcept
Definition at line 360 of file topoSetSource.H.
References topoSetSource::verbose_.
verbose() [3/3]
void verbose (const dictionary & dict)
Definition at line 266 of file topoSetSource.C.
References dict, and dictionary::readIfPresent().
setType()
virtual sourceType setType () const pure virtual
Implemented in topoSetCellSource, topoSetCellZoneSource, topoSetFaceSource, topoSetFaceZoneSource, topoSetPointSource, and topoSetPointZoneSource.
applyToSet()
virtual void applyToSet (const topoSetSource::setAction action, topoSet & set) const pure virtual
Implemented in surfaceToCell, holeToFace, regionToFace, planeToFaceZone, badQualityToCell, badQualityToFace, boundaryToCell, boxToCell, cellToCell, clipPlaneToCell, cylinderToCell, faceToCell, faceZoneToCell, fieldToCell, haloToCell, labelToCell, nbrToCell, nearestToCell, patchToCell, pointToCell, regionToCell, rotatedBoxToCell, searchableSurfaceToCell, shapeToCell, sphereToCell, targetVolumeToCell, zoneToCell, setToCellZone, boundaryToFace, boxToFace, cellToFace, clipPlaneToFace, cylinderToFace, faceToFace, labelToFace, normalToFace, patchToFace, pointToFace, searchableSurfaceToFace, sphereToFace, zoneToFace, cellToFaceZone, faceZoneToFaceZone, searchableSurfaceToFaceZone, setAndNormalToFaceZone, setsToFaceZone, setToFaceZone, boxToPoint, cellToPoint, clipPlaneToPoint, cylinderToPoint, faceToPoint, labelToPoint, nearestToPoint, pointToPoint, searchableSurfaceToPoint, sphereToPoint, surfaceToPoint, zoneToPoint, setToPointZone, and regionsToCell.
toAction()
static setAction toAction (const word & actionName) inline static
Definition at line 388 of file topoSetSource.H.
References topoSetSource::actionNames.
Member Data Documentation
actionNames
const Foam::Enum< Foam::topoSetSource::setAction > actionNames static
Definition at line 117 of file topoSetSource.H.
Referenced by topoSetSource::toAction().
combineNames
const Foam::Enum< Foam::topoSetSource::setAction > combineNames static
Definition at line 123 of file topoSetSource.H.
Referenced by cellBitSet::select().
illegalSource_
const Foam::string illegalSource_ static protected
Definition at line 128 of file topoSetSource.H.
Referenced by topoSetSource::usage().
usageTablePtr_
Foam::HashTable< Foam::string > * usageTablePtr_ = nullptr static protected
Definition at line 131 of file topoSetSource.H.
Referenced by topoSetSource::addToUsageTable::addToUsageTable(), topoSetSource::usage(), and topoSetSource::addToUsageTable::~addToUsageTable().
mesh_
const polyMesh& mesh_ protected
Definition at line 161 of file topoSetSource.H.
Referenced by topoSetSource::mesh().
verbose_
bool verbose_ protected
Definition at line 164 of file topoSetSource.H.
Referenced by topoSetSource::verbose(), and topoSetSource::verbose().
The documentation for this class was generated from the following files:
src/meshTools/topoSet/topoSetSource/topoSetSource.H
src/meshTools/topoSet/topoSetSource/topoSetSource.C