OpenFOAM: globalMeshData Class Reference
globalMeshData Class Reference
Various mesh related information for a parallel run. Upon construction, constructs all info using parallel communication.
#include <globalMeshData.H>
Classes
struct ListPlusEqOp
Public Member Functions
ClassName ("globalMeshData")
globalMeshData (const polyMesh &mesh)
~globalMeshData ()
void clearOut ()
const polyMesh & mesh () const noexcept
bool parallel () const noexcept
label nTotalPoints () const noexcept
label nTotalFaces () const noexcept
label nTotalCells () const noexcept
const processorTopology & topology () const noexcept
const lduSchedule & patchSchedule () const noexcept
const labelList & processorPatches () const noexcept
const labelList & processorPatchIndices () const noexcept
const labelList & processorPatchNeighbours () const noexcept
label nGlobalPoints () const
const labelList & sharedPointLabels () const
const labelList & sharedPointAddr () const
const labelList & sharedPointGlobalLabels () const
pointField sharedPoints () const
pointField geometricSharedPoints () const
label nGlobalEdges () const
const labelList & sharedEdgeLabels () const
const labelList & sharedEdgeAddr () const
const indirectPrimitivePatch & coupledPatch () const
const labelList & coupledPatchMeshEdges () const
const Map< label > & coupledPatchMeshEdgeMap () const
const globalIndexAndTransform & globalTransforms () const
const globalIndex & globalPointNumbering () const
const labelListList & globalPointSlaves () const
const labelListList & globalPointTransformedSlaves () const
const mapDistribute & globalPointSlavesMap () const
template<class Type , class CombineOp , class TransformOp >
void syncPointData (List< Type > &pointData, const CombineOp &cop, const TransformOp &top) const
const globalIndex & globalEdgeNumbering () const
const labelListList & globalEdgeSlaves () const
const labelListList & globalEdgeTransformedSlaves () const
const mapDistribute & globalEdgeSlavesMap () const
const bitSet & globalEdgeOrientation () const
const labelListList & globalCoPointSlaves () const
const mapDistribute & globalCoPointSlavesMap () const
const globalIndex & globalBoundaryFaceNumbering () const
const labelListList & globalPointBoundaryFaces () const
const labelListList & globalPointTransformedBoundaryFaces () const
const mapDistribute & globalPointBoundaryFacesMap () const
const labelList & boundaryCells () const
const globalIndex & globalBoundaryCellNumbering () const
const labelListList & globalPointBoundaryCells () const
const labelListList & globalPointTransformedBoundaryCells () const
const mapDistribute & globalPointBoundaryCellsMap () const
autoPtr< globalIndex > mergePoints (labelList &pointToGlobal, labelList &uniquePoints) const
autoPtr< globalIndex > mergePoints (const labelUList &meshPoints, const Map< label > &meshPointMap, labelList &pointToGlobal, labelList &uniqueMeshPoints) const
void movePoints (const pointField &newPoints)
void updateMesh ()
Static Public Member Functions
template<class Type , class CombineOp , class TransformOp >
static void syncData (List< Type > &elems, const labelListList &slaves, const labelListList &transformedSlaves, const mapDistribute &slavesMap, const globalIndexAndTransform &, const CombineOp &cop, const TransformOp &top)
template<class Type , class CombineOp >
static void syncData (List< Type > &elems, const labelListList &slaves, const labelListList &transformedSlaves, const mapDistribute &slavesMap, const CombineOp &cop)
Static Public Attributes
static const Foam::scalar matchTol_ = 1e-8
Detailed Description
Various mesh related information for a parallel run. Upon construction, constructs all info using parallel communication.
Requires:
all processor patches to have correct ordering.
all processorPatches to have their transforms set.
The shared point and edge addressing calculates addressing for points and edges on coupled patches. In the 'old' way a distinction was made between points/edges that are only on two processors and those that are on multiple processors. The problem is that those on multiple processors do not allow any transformations and require a global reduction on the master processor.
The alternative is to have an exchange schedule (through a 'mapDistribute') which sends all point/edge data (no distinction is made between those on two and those on more than two coupled patches) to the local 'master'. This master then does any calculation and sends the result back to the 'slave' points/edges. This only needs to be done on points on coupled faces. Any transformation is done using a predetermined set of transformations - since transformations have to be space filling only a certain number of transformation is supported.
The exchange needs
a field of data
a mapDistribute which does all parallel exchange and transformations This appends remote data to the end of the field.
a set of indices which indicate where to get untransformed data in the field
a set of indices which indicate where to get transformed data in the field
Note
compared to 17x nTotalFaces, nTotalPoints do not compensate for shared points since this would trigger full connectivity analysis
most calculation is demand driven and uses parallel communication so make sure to invoke on all processors at the same time
old sharedEdge calculation: currently an edge is considered shared if it uses two shared points and is used more than once. This is not correct on processor patches but it only slightly overestimates the number of shared edges. Doing full analysis of how many patches use the edge would be too complicated
See also
mapDistribute globalIndexAndTransform
Source files
globalMeshData.H
globalMeshData.C
globalMeshDataTemplates.C
Definition at line 103 of file globalMeshData.H.
Constructor & Destructor Documentation
globalMeshData()
globalMeshData (const polyMesh & mesh)
Definition at line 1723 of file globalMeshData.C.
References globalMeshData::updateMesh().
~globalMeshData()
~globalMeshData ()
Definition at line 1755 of file globalMeshData.C.
Member Function Documentation
ClassName()
ClassName ("globalMeshData")
clearOut()
void clearOut ()
Definition at line 1759 of file globalMeshData.C.
References PtrList< T >::clear().
mesh()
const polyMesh & mesh () const inline noexcept
Definition at line 341 of file globalMeshData.H.
parallel()
bool parallel () const inline noexcept
Definition at line 348 of file globalMeshData.H.
References UList< T >::empty().
nTotalPoints()
label nTotalPoints () const inline noexcept
Definition at line 355 of file globalMeshData.H.
nTotalFaces()
label nTotalFaces () const inline noexcept
Definition at line 362 of file globalMeshData.H.
nTotalCells()
label nTotalCells () const inline noexcept
Definition at line 368 of file globalMeshData.H.
topology()
const processorTopology & topology () const inline noexcept
Definition at line 377 of file globalMeshData.H.
patchSchedule()
const lduSchedule & patchSchedule () const inline noexcept
Definition at line 384 of file globalMeshData.H.
References processorTopology::patchSchedule().
processorPatches()
const labelList & processorPatches () const inline noexcept
Definition at line 391 of file globalMeshData.H.
processorPatchIndices()
const labelList & processorPatchIndices () const inline noexcept
Definition at line 399 of file globalMeshData.H.
processorPatchNeighbours()
const labelList & processorPatchNeighbours () const inline noexcept
Definition at line 406 of file globalMeshData.H.
nGlobalPoints()
Foam::label nGlobalPoints () const
Definition at line 1948 of file globalMeshData.C.
sharedPointLabels()
const Foam::labelList & sharedPointLabels () const
Definition at line 1958 of file globalMeshData.C.
sharedPointAddr()
const Foam::labelList & sharedPointAddr () const
Definition at line 1968 of file globalMeshData.C.
sharedPointGlobalLabels()
const Foam::labelList & sharedPointGlobalLabels () const
Definition at line 1812 of file globalMeshData.C.
References Foam::endl(), forAll, IOobjectOption::MUST_READ, pointLabels(), and Foam::Pout.
sharedPoints()
Foam::pointField sharedPoints () const
Definition at line 1863 of file globalMeshData.C.
References UPstream::blocking, Pstream::broadcast(), forAll, UPstream::master(), UPstream::masterNo(), UPstream::parRun(), pointLabels(), and UPstream::subProcs().
geometricSharedPoints()
Foam::pointField geometricSharedPoints () const
Definition at line 1924 of file globalMeshData.C.
References Pstream::combineReduce(), and Foam::inplaceMergePoints().
nGlobalEdges()
Foam::label nGlobalEdges () const
Definition at line 1978 of file globalMeshData.C.
sharedEdgeLabels()
const Foam::labelList & sharedEdgeLabels () const
Definition at line 1988 of file globalMeshData.C.
sharedEdgeAddr()
const Foam::labelList & sharedEdgeAddr () const
Definition at line 1998 of file globalMeshData.C.
coupledPatch()
const Foam::indirectPrimitivePatch & coupledPatch () const
Definition at line 2008 of file globalMeshData.C.
References Foam::endl(), forAll, Foam::Pout, and pp().
Referenced by createShellMesh::calcPointRegions(), meshRefinement::countEdgeFaces(), syncTools::getMasterPoints(), and PatchTools::pointNormals().
coupledPatchMeshEdges()
const Foam::labelList & coupledPatchMeshEdges () const
Definition at line 2069 of file globalMeshData.C.
Referenced by syncTools::getMasterEdges().
coupledPatchMeshEdgeMap()
const Foam::Map< Foam::label > & coupledPatchMeshEdgeMap () const
Definition at line 2089 of file globalMeshData.C.
References forAll, and UPtrList< T >::size().
globalTransforms()
const Foam::globalIndexAndTransform & globalTransforms () const
Definition at line 2122 of file globalMeshData.C.
Referenced by PatchTools::edgeNormals(), and PatchTools::pointNormals().
syncData() [1/2]
template<class Type , class CombineOp , class TransformOp > void syncData (List< Type > & elems, const labelListList & slaves, const labelListList & transformedSlaves, const mapDistribute & slavesMap, const globalIndexAndTransform & transforms, const CombineOp & cop, const TransformOp & top) static
Definition at line 29 of file globalMeshDataTemplates.C.
References UPtrList< T >::empty(), forAll, List< label >::null(), and UPtrList< T >::size().
Referenced by addPatchCellLayer::calcExtrudeInfo(), meshRefinement::countEdgeFaces(), PatchTools::edgeNormals(), syncTools::syncEdgeList(), syncTools::syncEdgeList(), syncTools::syncEdgeList(), syncTools::syncPointList(), and syncTools::syncPointList().
syncData() [2/2]
template<class Type , class CombineOp > void syncData (List< Type > & elems, const labelListList & slaves, const labelListList & transformedSlaves, const mapDistribute & slavesMap, const CombineOp & cop) static
Definition at line 94 of file globalMeshDataTemplates.C.
References UPtrList< T >::empty(), forAll, List< label >::null(), and UPtrList< T >::size().
globalPointNumbering()
const Foam::globalIndex & globalPointNumbering () const
Definition at line 2108 of file globalMeshData.C.
References nPoints.
globalPointSlaves()
const Foam::labelListList & globalPointSlaves () const
Definition at line 2132 of file globalMeshData.C.
Referenced by syncTools::getMasterPoints(), and PatchTools::pointNormals().
globalPointTransformedSlaves()
const Foam::labelListList & globalPointTransformedSlaves () const
Definition at line 2142 of file globalMeshData.C.
Referenced by syncTools::getMasterPoints(), and PatchTools::pointNormals().
globalPointSlavesMap()
const Foam::mapDistribute & globalPointSlavesMap () const
Definition at line 2153 of file globalMeshData.C.
Referenced by PatchTools::pointNormals().
syncPointData()
template<class Type , class CombineOp , class TransformOp > void syncPointData (List< Type > & pointData, const CombineOp & cop, const TransformOp & top) const
Definition at line 151 of file globalMeshDataTemplates.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, and UPtrList< T >::size().
globalEdgeNumbering()
const Foam::globalIndex & globalEdgeNumbering () const
Definition at line 2163 of file globalMeshData.C.
globalEdgeSlaves()
const Foam::labelListList & globalEdgeSlaves () const
Definition at line 2176 of file globalMeshData.C.
Referenced by meshRefinement::countEdgeFaces(), PatchTools::edgeNormals(), and syncTools::getMasterEdges().
globalEdgeTransformedSlaves()
const Foam::labelListList & globalEdgeTransformedSlaves () const
Definition at line 2186 of file globalMeshData.C.
Referenced by meshRefinement::countEdgeFaces(), PatchTools::edgeNormals(), and syncTools::getMasterEdges().
globalEdgeSlavesMap()
const Foam::mapDistribute & globalEdgeSlavesMap () const
Definition at line 2207 of file globalMeshData.C.
Referenced by meshRefinement::countEdgeFaces(), and PatchTools::edgeNormals().
globalEdgeOrientation()
const Foam::bitSet & globalEdgeOrientation () const
Definition at line 2197 of file globalMeshData.C.
globalCoPointSlaves()
const Foam::labelListList & globalCoPointSlaves () const
Definition at line 2315 of file globalMeshData.C.
globalCoPointSlavesMap()
const Foam::mapDistribute & globalCoPointSlavesMap () const
Definition at line 2325 of file globalMeshData.C.
globalBoundaryFaceNumbering()
const Foam::globalIndex & globalBoundaryFaceNumbering () const
Definition at line 2217 of file globalMeshData.C.
globalPointBoundaryFaces()
const Foam::labelListList & globalPointBoundaryFaces () const
Definition at line 2228 of file globalMeshData.C.
globalPointTransformedBoundaryFaces()
const Foam::labelListList & globalPointTransformedBoundaryFaces () const
Definition at line 2240 of file globalMeshData.C.
globalPointBoundaryFacesMap()
const Foam::mapDistribute & globalPointBoundaryFacesMap () const
Definition at line 2250 of file globalMeshData.C.
boundaryCells()
const Foam::labelList & boundaryCells () const
Definition at line 2261 of file globalMeshData.C.
globalBoundaryCellNumbering()
const Foam::globalIndex & globalBoundaryCellNumbering () const
Definition at line 2271 of file globalMeshData.C.
globalPointBoundaryCells()
const Foam::labelListList & globalPointBoundaryCells () const
Definition at line 2282 of file globalMeshData.C.
globalPointTransformedBoundaryCells()
const Foam::labelListList & globalPointTransformedBoundaryCells () const
Definition at line 2294 of file globalMeshData.C.
globalPointBoundaryCellsMap()
const Foam::mapDistribute & globalPointBoundaryCellsMap () const
Definition at line 2304 of file globalMeshData.C.
mergePoints() [1/2]
Foam::autoPtr< Foam::globalIndex > mergePoints (labelList & pointToGlobal, labelList & uniquePoints) const
Definition at line 2335 of file globalMeshData.C.
References forAll, PtrList< T >::setSize(), UPtrList< T >::size(), and bitSet::unset().
mergePoints() [2/2]
Foam::autoPtr< Foam::globalIndex > mergePoints (const labelUList & meshPoints, const Map< label > & meshPointMap, labelList & pointToGlobal, labelList & uniqueMeshPoints) const
Parameters
meshPointMap currently unused
Definition at line 2469 of file globalMeshData.C.
References forAll, Foam::labelMax, List< T >::setSize(), PtrList< T >::setSize(), UPtrList< T >::size(), and UList< T >::size().
movePoints()
void movePoints (const pointField & newPoints)
Definition at line 2684 of file globalMeshData.C.
updateMesh()
void updateMesh ()
Definition at line 2693 of file globalMeshData.C.
References UPstream::commWarn(), Foam::endl(), Foam::Info, UPstream::msgType(), UPstream::nProcs(), Foam::Pout, Foam::reduce(), and UPstream::worldComm.
Referenced by globalMeshData::globalMeshData().
Member Data Documentation
matchTol_
const scalar matchTol_ = 1e-8 static
Definition at line 320 of file globalMeshData.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/globalMeshData/globalMeshData.H
src/OpenFOAM/meshes/polyMesh/globalMeshData/globalMeshData.C
src/OpenFOAM/meshes/polyMesh/globalMeshData/globalMeshDataTemplates.C