OpenFOAM: pureZoneMixture< ThermoType > Class Template Reference
pureZoneMixture< ThermoType > Class Template Reference
Version of pureMixture that uses different mixtures for different cellZones. Every cellZone has to provide an entry for its mixture. A reserved entry 'none' is for all unzoned cells.
#include <pureZoneMixture.H>
Public Types
typedef ThermoType thermoType
Public Types inherited from basicMixture
typedef basicMixture basicMixtureType
Public Member Functions
pureZoneMixture (const dictionary &thermoDict, const fvMesh &mesh, const word &phaseName)
virtual ~pureZoneMixture ()=default
const ThermoType & cellMixture (const label celli) const
const ThermoType & patchFaceMixture (const label patchi, const label facei) const
const ThermoType & cellVolMixture (const scalar p, const scalar T, const label celli) const
const ThermoType & patchFaceVolMixture (const scalar p, const scalar T, const label patchi, const label facei) const
void read (const dictionary &)
Public Member Functions inherited from basicMixture
basicMixture (const dictionary &, const fvMesh &, const word &)
Static Public Member Functions
static word typeName ()
Detailed Description
template<class ThermoType>
class Foam::pureZoneMixture< ThermoType >
Version of pureMixture that uses different mixtures for different cellZones. Every cellZone has to provide an entry for its mixture. A reserved entry 'none' is for all unzoned cells.
Example of the zone based mixture specification:
mixture
{
    solid1
    {
        specie
        {
            molWeight   50;
        }
        transport
        {
            kappa   80;
        }
        thermodynamics
        {
            Hf      0;
            Cp      450;
        }
        equationOfState
        {
            rho     8000;
        }
    }
    solid2
    {
        //- Start off from 'solid1' properties
        ${solid1}
        //- Selectively overwrite properties
        transport
        {
            kappa   8;
        }
    }
}
Source files
pureZoneMixture.H
pureZoneMixture.C
Definition at line 92 of file pureZoneMixture.H.
Member Typedef Documentation
thermoType
template<class ThermoType > typedef ThermoType thermoType
Definition at line 123 of file pureZoneMixture.H.
Constructor & Destructor Documentation
pureZoneMixture()
template<class ThermoType > pureZoneMixture (const dictionary & thermoDict, const fvMesh & mesh, const word & phaseName)
Definition at line 58 of file pureZoneMixture.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, UList< T >::find(), List< T >::setSize(), and UPtrList< T >::size().
~pureZoneMixture()
template<class ThermoType > virtual ~pureZoneMixture () virtual default
Member Function Documentation
typeName()
template<class ThermoType > static word typeName () inline static
Definition at line 144 of file pureZoneMixture.H.
cellMixture()
template<class ThermoType > const ThermoType & cellMixture (const label celli) const
Definition at line 97 of file pureZoneMixture.C.
patchFaceMixture()
template<class ThermoType > const ThermoType & patchFaceMixture (const label patchi, const label facei) const
Definition at line 108 of file pureZoneMixture.C.
cellVolMixture()
template<class ThermoType > const ThermoType & cellVolMixture (const scalar p, const scalar T, const label celli) const
Definition at line 121 of file pureZoneMixture.C.
patchFaceVolMixture()
template<class ThermoType > const ThermoType & patchFaceVolMixture (const scalar p, const scalar T, const label patchi, const label facei) const
Definition at line 134 of file pureZoneMixture.C.
read()
template<class ThermoType > void read (const dictionary & thermoDict)
Definition at line 148 of file pureZoneMixture.C.
References thermoDict.
The documentation for this class was generated from the following files:
src/thermophysicalModels/basic/mixtures/pureZoneMixture/pureZoneMixture.H
src/thermophysicalModels/basic/mixtures/pureZoneMixture/pureZoneMixture.C