OpenFOAM: attachDetach Class Reference
attachDetach Class Reference
Attach/detach boundary mesh modifier. This modifier takes a set of internal faces and converts them into boundary faces and vice versa based on the given activation switch.
#include <attachDetach.H>
Public Member Functions
TypeName ("attachDetach")
attachDetach (const word &name, const label index, const polyTopoChanger &mme, const word &faceZoneName, const word &masterPatchName, const word &slavePatchName, const scalarField &triggerTimes, const bool manualTrigger=false)
attachDetach (const word &name, const dictionary &dict, const label index, const polyTopoChanger &mesh)
virtual ~attachDetach ()=default
const polyPatchID & masterPatchID () const
const polyPatchID & slavePatchID () const
bool attached () const
bool manualTrigger () const
bool setAttach () const
bool setDetach () const
virtual bool changeTopology () const
virtual void setRefinement (polyTopoChange &) const
virtual void modifyMotionPoints (pointField &motionPoints) const
virtual void updateMesh (const mapPolyMesh &)
const scalarField & triggerTimes () const
virtual void write (Ostream &) const
virtual void writeDict (Ostream &) const
Public Member Functions inherited from polyMeshModifier
TypeName ("meshModifier")
declareRunTimeSelectionTable (autoPtr, polyMeshModifier, dictionary,(const word &name, const dictionary &dict, const label index, const polyTopoChanger &mme),(name, dict, index, mme))
polyMeshModifier (const word &name, const label index, const polyTopoChanger &mme, const bool act)
virtual ~polyMeshModifier ()=default
const word & name () const
label index () const
const polyTopoChanger & topoChanger () const
Switch active () const
void enable () const
void disable () const
Additional Inherited Members
Static Public Member Functions inherited from polyMeshModifier
static autoPtr< polyMeshModifier > New (const word &name, const dictionary &dict, const label index, const polyTopoChanger &mme)
Detailed Description
Attach/detach boundary mesh modifier. This modifier takes a set of internal faces and converts them into boundary faces and vice versa based on the given activation switch.
The patch is oriented using the flip map in the face zone. The oriented faces are put into the master patch and their mirror images into the slave.
Source files
attachDetach.H
attachDetach.C
attachInterface.C
detachInterface.C
attachDetachPointMatchMap.C
Definition at line 58 of file attachDetach.H.
Constructor & Destructor Documentation
attachDetach() [1/2]
attachDetach (const word & name, const label index, const polyTopoChanger & mme, const word & faceZoneName, const word & masterPatchName, const word & slavePatchName, const scalarField & triggerTimes, const bool manualTrigger = false)
Definition at line 223 of file attachDetach.C.
attachDetach() [2/2]
attachDetach (const word & name, const dictionary & dict, const label index, const polyTopoChanger & mesh)
Definition at line 250 of file attachDetach.C.
~attachDetach()
virtual ~attachDetach () virtual default
Member Function Documentation
TypeName()
TypeName ("attachDetach")
masterPatchID()
const polyPatchID & masterPatchID () const inline
Definition at line 179 of file attachDetach.H.
slavePatchID()
const polyPatchID & slavePatchID () const inline
Definition at line 185 of file attachDetach.H.
attached()
bool attached () const inline
Definition at line 191 of file attachDetach.H.
manualTrigger()
bool manualTrigger () const inline
Definition at line 197 of file attachDetach.H.
setAttach()
bool setAttach () const
Definition at line 287 of file attachDetach.C.
setDetach()
bool setDetach () const
Definition at line 295 of file attachDetach.C.
changeTopology()
bool changeTopology () const virtual
Implements polyMeshModifier.
Definition at line 303 of file attachDetach.C.
References Foam::endl(), mesh, Foam::name(), Foam::nl, and Foam::Pout.
setRefinement()
void setRefinement (polyTopoChange & ref) const virtual
Implements polyMeshModifier.
Definition at line 371 of file attachDetach.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and ref().
modifyMotionPoints()
void modifyMotionPoints (pointField & motionPoints) const virtual
Implements polyMeshModifier.
Definition at line 269 of file attachInterface.C.
References Foam::endl(), forAll, Foam::mag(), Foam::name(), Foam::Pout, and UPtrList< T >::size().
updateMesh()
void updateMesh (const mapPolyMesh &) virtual
Implements polyMeshModifier.
Definition at line 406 of file attachDetach.C.
References polyMesh::boundaryMesh(), polyMesh::faceZones(), mesh, and dynamicFvMesh::update().
triggerTimes()
const scalarField & triggerTimes () const inline
Definition at line 222 of file attachDetach.H.
write()
void write (Ostream & os) const virtual
Implements polyMeshModifier.
Definition at line 419 of file attachDetach.C.
References Foam::endl(), Foam::name(), Foam::nl, os(), and Foam::type().
writeDict()
void writeDict (Ostream & os) const virtual
Implements polyMeshModifier.
Definition at line 430 of file attachDetach.C.
References Ostream::beginBlock(), Ostream::endBlock(), Switch::name(), Foam::name(), Foam::nl, os(), Foam::type(), and Ostream::writeEntry().
The documentation for this class was generated from the following files:
src/dynamicMesh/attachDetach/attachDetach.H
src/dynamicMesh/attachDetach/attachDetach.C
src/dynamicMesh/attachDetach/attachDetachPointMatchMap.C
src/dynamicMesh/attachDetach/attachInterface.C
src/dynamicMesh/attachDetach/detachInterface.C