OpenFOAM: simpleFilter Class Reference
simpleFilter Class Reference
Simple top-hat filter used in dynamic LES models.
#include <simpleFilter.H>
Public Member Functions
TypeName ("simple")
simpleFilter (const fvMesh &mesh)
simpleFilter (const fvMesh &mesh, const dictionary &)
virtual ~simpleFilter ()=default
virtual void read (const dictionary &)
virtual tmp< volScalarField > operator() (const tmp< volScalarField > &) const
virtual tmp< volVectorField > operator() (const tmp< volVectorField > &) const
virtual tmp< volSymmTensorField > operator() (const tmp< volSymmTensorField > &) const
virtual tmp< volTensorField > operator() (const tmp< volTensorField > &) const
Public Member Functions inherited from LESfilter
TypeName ("LESfilter")
declareRunTimeSelectionTable (autoPtr, LESfilter, dictionary,(const fvMesh &mesh, const dictionary &LESfilterDict),(mesh, LESfilterDict))
LESfilter (const fvMesh &mesh)
virtual ~LESfilter ()=default
const fvMesh & mesh () const
Additional Inherited Members
Static Public Member Functions inherited from LESfilter
static autoPtr< LESfilter > New (const fvMesh &, const dictionary &, const word &filterDictName="filter")
Protected Member Functions inherited from LESfilter
template<class GeoFieldType >
void correctBoundaryConditions (const tmp< GeoFieldType > &tgf) const
Detailed Description
Simple top-hat filter used in dynamic LES models.
Implemented as a surface integral of the face interpolate of the field.
Source files
simpleFilter.H
simpleFilter.C
Definition at line 48 of file simpleFilter.H.
Constructor & Destructor Documentation
simpleFilter() [1/2]
simpleFilter (const fvMesh & mesh)
Definition at line 36 of file simpleFilter.C.
simpleFilter() [2/2]
simpleFilter (const fvMesh & mesh, const dictionary &)
Definition at line 45 of file simpleFilter.C.
~simpleFilter()
virtual ~simpleFilter () virtual default
Member Function Documentation
TypeName()
TypeName ("simple")
read()
void read (const dictionary &) virtual
Implements LESfilter.
Definition at line 53 of file simpleFilter.C.
operator()() [1/4]
Foam::tmp< Foam::volScalarField > operator() (const tmp< volScalarField > & unFilteredField) const virtual
Implements LESfilter.
Definition at line 59 of file simpleFilter.C.
References PtrList< T >::clear(), correctBoundaryConditions(), Foam::fvc::interpolate(), mesh, and Foam::fvc::surfaceSum().
operator()() [2/4]
Foam::tmp< Foam::volVectorField > operator() (const tmp< volVectorField > & unFilteredField) const virtual
Implements LESfilter.
Definition at line 77 of file simpleFilter.C.
References PtrList< T >::clear(), correctBoundaryConditions(), Foam::fvc::interpolate(), mesh, and Foam::fvc::surfaceSum().
operator()() [3/4]
Foam::tmp< Foam::volSymmTensorField > operator() (const tmp< volSymmTensorField > & unFilteredField) const virtual
Implements LESfilter.
Definition at line 95 of file simpleFilter.C.
References PtrList< T >::clear(), correctBoundaryConditions(), Foam::fvc::interpolate(), mesh, and Foam::fvc::surfaceSum().
operator()() [4/4]
Foam::tmp< Foam::volTensorField > operator() (const tmp< volTensorField > & unFilteredField) const virtual
Implements LESfilter.
Definition at line 113 of file simpleFilter.C.
References PtrList< T >::clear(), correctBoundaryConditions(), Foam::fvc::interpolate(), mesh, and Foam::fvc::surfaceSum().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/LES/LESfilters/simpleFilter/simpleFilter.H
src/TurbulenceModels/turbulenceModels/LES/LESfilters/simpleFilter/simpleFilter.C