OpenFOAM: interfaceCompressionFvPatchScalarField Class Reference
interfaceCompressionFvPatchScalarField Class Reference
Boundary conditions » Generic
Applies interface-compression to the phase-fraction distribution at the patch by setting the phase-fraction to 0 if it is below 0.5, otherwise to 1.
#include <interfaceCompressionFvPatchScalarField.H>
Public Member Functions
TypeName ("interfaceCompression")
interfaceCompressionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
interfaceCompressionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
interfaceCompressionFvPatchScalarField (const interfaceCompressionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
interfaceCompressionFvPatchScalarField (const interfaceCompressionFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
interfaceCompressionFvPatchScalarField (const interfaceCompressionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
Applies interface-compression to the phase-fraction distribution at the patch by setting the phase-fraction to 0 if it is below 0.5, otherwise to 1.
This approach is useful to avoid unphysical "bleed" of the lighter phase along the surface in regions of high shear adjacent to the surface which is at a shallow angle to the interface.
See also
Foam::fixedValueFvPatchScalarField
Source files
interfaceCompressionFvPatchScalarField.H
interfaceCompressionFvPatchScalarField.C
Definition at line 58 of file interfaceCompressionFvPatchScalarField.H.
Constructor & Destructor Documentation
interfaceCompressionFvPatchScalarField() [1/5]
interfaceCompressionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 27 of file interfaceCompressionFvPatchScalarField.C.
interfaceCompressionFvPatchScalarField() [2/5]
interfaceCompressionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 38 of file interfaceCompressionFvPatchScalarField.C.
interfaceCompressionFvPatchScalarField() [3/5]
interfaceCompressionFvPatchScalarField (const interfaceCompressionFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 52 of file interfaceCompressionFvPatchScalarField.C.
interfaceCompressionFvPatchScalarField() [4/5]
interfaceCompressionFvPatchScalarField (const interfaceCompressionFvPatchScalarField & ptf)
Definition at line 65 of file interfaceCompressionFvPatchScalarField.C.
interfaceCompressionFvPatchScalarField() [5/5]
interfaceCompressionFvPatchScalarField (const interfaceCompressionFvPatchScalarField & ptf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 75 of file interfaceCompressionFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("interfaceCompression")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 103 of file interfaceCompressionFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 119 of file interfaceCompressionFvPatchScalarField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 88 of file interfaceCompressionFvPatchScalarField.C.
References Foam::operator==(), and Foam::pos0().
write()
void write (Ostream & os) const virtual
Definition at line 101 of file interfaceCompressionFvPatchScalarField.C.
References os(), fvPatchField< Type >::write(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/interfaceCompression/interfaceCompressionFvPatchScalarField.H
src/finiteVolume/fields/fvPatchFields/derived/interfaceCompression/interfaceCompressionFvPatchScalarField.C