OpenFOAM: pointFieldDecomposer::fieldsCache::privateCache Class Reference
pointFieldDecomposer::fieldsCache::privateCache Class Reference
Public Member Functions
label size () const noexcept
bool empty () const noexcept
void readAll (const pointMesh &mesh, const IOobjectList &objects)
void decomposeAll (const pointFieldDecomposer &decomposer, bool report) const
Static Public Member Functions
template<class GeoField >
static void decompose (const pointFieldDecomposer &decomposer, const PtrList< GeoField > &fields, bool report)
Public Attributes
PtrList< GeometricField< scalar, pointPatchField, pointMesh > > scalarFields_
PtrList< GeometricField< vector, pointPatchField, pointMesh > > vectorFields_
PtrList< GeometricField< sphericalTensor, pointPatchField, pointMesh > > sphericalTensorFields_
PtrList< GeometricField< symmTensor, pointPatchField, pointMesh > > symmTensorFields_
PtrList< GeometricField< tensor, pointPatchField, pointMesh > > tensorFields_
Detailed Description
Definition at line 33 of file pointFieldDecomposerCache.C.
Member Function Documentation
size()
label size () const inline noexcept
Definition at line 48 of file pointFieldDecomposerCache.C.
References doLocalCode.
Referenced by pointFieldDecomposer::fieldsCache::privateCache::empty().
empty()
bool empty () const inline noexcept
Definition at line 68 of file pointFieldDecomposerCache.C.
References pointFieldDecomposer::fieldsCache::privateCache::size().
readAll()
void readAll (const pointMesh & mesh, const IOobjectList & objects) inline
Definition at line 70 of file pointFieldDecomposerCache.C.
References doLocalCode.
decompose()
template<class GeoField > static void decompose (const pointFieldDecomposer & decomposer, const PtrList< GeoField > & fields, bool report) inline static
Definition at line 94 of file pointFieldDecomposerCache.C.
References pointFieldDecomposer::decomposeFields(), fields, Foam::flatOutput(), Foam::Info, Foam::PtrListOps::names(), and Foam::nl.
decomposeAll()
void decomposeAll (const pointFieldDecomposer & decomposer, bool report) const inline
Definition at line 115 of file pointFieldDecomposerCache.C.
References doLocalCode.
Member Data Documentation
scalarFields_
PtrList<GeometricField< scalar , pointPatchField, pointMesh> > scalarFields_
Definition at line 41 of file pointFieldDecomposerCache.C.
vectorFields_
PtrList<GeometricField< vector , pointPatchField, pointMesh> > vectorFields_
Definition at line 42 of file pointFieldDecomposerCache.C.
sphericalTensorFields_
PtrList<GeometricField< sphericalTensor , pointPatchField, pointMesh> > sphericalTensorFields_
Definition at line 43 of file pointFieldDecomposerCache.C.
symmTensorFields_
PtrList<GeometricField< symmTensor , pointPatchField, pointMesh> > symmTensorFields_
Definition at line 44 of file pointFieldDecomposerCache.C.
tensorFields_
PtrList<GeometricField< tensor , pointPatchField, pointMesh> > tensorFields_
Definition at line 45 of file pointFieldDecomposerCache.C.
The documentation for this class was generated from the following file:
src/parallel/decompose/decompose/pointFieldDecomposerCache.C