OpenFOAM: cyclicAMIPolyPatch Class Reference
cyclicAMIPolyPatch Class Reference
Cyclic patch for Arbitrary Mesh Interface (AMI)
#include <cyclicAMIPolyPatch.H>
Public Member Functions
TypeName ("cyclicAMI")
cyclicAMIPolyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType, const transformType transform=UNKNOWN, const word &defaultAMIMethod=faceAreaWeightAMI::typeName)
cyclicAMIPolyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType, const word &defaultAMIMethod=faceAreaWeightAMI::typeName)
cyclicAMIPolyPatch (const cyclicAMIPolyPatch &, const polyBoundaryMesh &)
cyclicAMIPolyPatch (const cyclicAMIPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart, const word &nbrPatchName)
cyclicAMIPolyPatch (const cyclicAMIPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm) const
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart) const
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart) const
virtual ~cyclicAMIPolyPatch ()=default
virtual void newInternalProcFaces (label &, label &) const
virtual const labelUList & nbrCells () const
virtual label neighbPolyPatchID () const
virtual refPtr< labelListList > mapCollocatedFaces () const
virtual bool masterImplicit () const
bool canResetAMI () const
bool createAMIFaces () const
bool updatingAMI () const
virtual bool changeTopology () const
virtual bool setTopology (polyTopoChange &topoChange)
virtual bool coupled () const
const word & neighbPatchName () const
virtual label neighbPatchID () const
scalar fraction () const
virtual bool owner () const
virtual const cyclicAMIPolyPatch & neighbPatch () const
label periodicPatchID () const
const AMIPatchToPatchInterpolation & AMI () const
const scalarListList & weights () const
const scalarField & weightsSum () const
bool applyLowWeightCorrection () const
vectorField & faceAreas0 () const
vectorField & faceCentres0 () const
const vector & rotationAxis () const
const point & rotationCentre () const
const vector & separationVector () const
virtual void transformPosition (pointField &) const
virtual void transformPosition (point &l, const label facei) const
virtual void reverseTransformPosition (point &l, const label facei) const
virtual void reverseTransformDirection (vector &d, const label facei) const
template<class Type >
tmp< Field< Type > > interpolate (const Field< Type > &fld, const UList< Type > &defaultValues=UList< Type >()) const
template<class Type >
tmp< Field< Type > > interpolate (const tmp< Field< Type > > &tFld, const UList< Type > &defaultValues=UList< Type >()) const
template<class Type >
tmp< Field< Type > > interpolateUntransformed (const Field< Type > &fld, const UList< Type > &defaultValues) const
template<class Type , class CombineOp >
void interpolate (const UList< Type > &fld, const CombineOp &cop, List< Type > &result, const UList< Type > &defaultValues=UList< Type >()) const
virtual void calcGeometry (const primitivePatch &referPatch, const pointField &thisCtrs, const vectorField &thisAreas, const pointField &thisCc, const pointField &nbrCtrs, const vectorField &nbrAreas, const pointField &nbrCc)
virtual void initOrder (PstreamBuffers &, const primitivePatch &) const
virtual bool order (PstreamBuffers &, const primitivePatch &, labelList &faceMap, labelList &rotation) const
label pointFace (const label facei, const vector &n, point &p) const
virtual void write (Ostream &) const
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolateUntransformed (const Field< Type > &fld, const UList< Type > &defaultValues) const
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolate (const Field< Type > &fld, const UList< Type > &defaultValues) const
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolate (const tmp< Field< Type > > &tFld, const UList< Type > &defaultValues) const
Public Member Functions inherited from coupledPolyPatch
TypeName ("coupled")
coupledPolyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType, const transformType transform)
coupledPolyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType)
coupledPolyPatch (const coupledPolyPatch &, const polyBoundaryMesh &bm)
coupledPolyPatch (const coupledPolyPatch &, const labelList &faceCells)
coupledPolyPatch (const coupledPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart)
coupledPolyPatch (const coupledPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
virtual ~coupledPolyPatch ()
virtual bool neighbour () const
virtual transformType transform () const
virtual transformType & transform ()
virtual bool separated () const
virtual const vectorField & separation () const
virtual bool parallel () const
virtual const tensorField & forwardT () const
virtual const tensorField & reverseT () const
virtual const boolList & collocated () const
scalar matchTolerance () const
Public Member Functions inherited from polyPatch
TypeName ("patch")
declareRunTimeSelectionTable (autoPtr, polyPatch, word,(const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType),(name, size, start, index, bm, patchType))
declareRunTimeSelectionTable (autoPtr, polyPatch, dictionary,(const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType),(name, dict, index, bm, patchType))
polyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType)
polyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &physicalType, const wordList &inGroups)
polyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType)
polyPatch (const polyPatch &, const polyBoundaryMesh &)
polyPatch (const polyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart)
polyPatch (const polyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
polyPatch (const polyPatch &p)
polyPatch (const polyPatch &p, const labelList &faceCells)
virtual autoPtr< polyPatch > clone (const labelList &faceCells) const
virtual ~polyPatch ()
virtual word neighbRegionID () const
label offset () const noexcept
label start () const noexcept
labelRange range () const
const polyBoundaryMesh & boundaryMesh () const noexcept
template<class T >
const UIndirectList< T > patchInternalList (const UList< T > &internalValues) const
template<class T >
const List< T >::subList patchSlice (const UList< T > &values) const
template<class T >
const List< T >::subList boundarySlice (const List< T > &values) const
template<class T >
const Field< T >::subField patchSlice (const Field< T > &values) const
const vectorField::subField faceCentres () const
const vectorField::subField faceAreas () const
tmp< vectorField > faceCellCentres () const
tmp< scalarField > areaFraction () const
const labelUList & faceCells () const
const labelList & meshEdges () const
virtual void clearAddressing ()
label whichFace (const label facei) const noexcept
void operator= (const polyPatch &)
Public Member Functions inherited from patchIdentifier
patchIdentifier (const patchIdentifier &)=default
patchIdentifier & operator= (const patchIdentifier &)=default
virtual ~patchIdentifier ()=default
patchIdentifier ()
patchIdentifier (const word &name, const label index)
patchIdentifier (const word &name, const label index, const word &physicalType, const wordList &inGroups=wordList())
patchIdentifier (const word &name, const dictionary &dict, const label index)
patchIdentifier (const patchIdentifier &ident, const label index)
const word & name () const noexcept
word & name () noexcept
label index () const noexcept
label & index () noexcept
const word & physicalType () const noexcept
word & physicalType () noexcept
const wordList & inGroups () const noexcept
wordList & inGroups () noexcept
bool inGroup (const word &name) const
void write (Ostream &os) const
Public Member Functions inherited from PrimitivePatch< FaceList, PointField >
PrimitivePatch (const FaceList &faces, const PointField &points)
PrimitivePatch (FaceList &&faces, const PointField &points)
PrimitivePatch (FaceList &faces, PointField &points, const bool reuse)
PrimitivePatch (const PrimitivePatch< FaceList, PointField > &pp)
virtual ~PrimitivePatch ()
void clearOut ()
void clearGeom ()
void clearTopology ()
void clearPatchMeshAddr ()
void swap (PrimitivePatch &)=delete
const Field< point_type > & points () const noexcept
label nFaces () const noexcept
label nPoints () const
label nEdges () const
const edgeList & edges () const
const edgeList::subList internalEdges () const
const edgeList::subList boundaryEdges () const
label nInternalEdges () const
label nBoundaryEdges () const
bool isInternalEdge (const label edgei) const
const labelList & boundaryPoints () const
const labelListList & faceFaces () const
const labelListList & edgeFaces () const
const labelListList & faceEdges () const
const labelListList & pointEdges () const
const labelListList & pointFaces () const
const List< face_type > & localFaces () const
labelList boundaryFaces () const
labelList uniqBoundaryFaces () const
const labelList & meshPoints () const
const Map< label > & meshPointMap () const
const Field< point_type > & localPoints () const
const labelList & localPointOrder () const
label whichPoint (const label gp) const
edge meshEdge (const label edgei) const
edge meshEdge (const edge &e) const
label findEdge (const edge &e) const
labelList meshEdges (const edgeList &allEdges, const labelListList &cellEdges, const labelList &faceCells) const
labelList meshEdges (const edgeList &allEdges, const labelListList &pointEdges) const
label meshEdge (const label edgei, const edgeList &allEdges, const labelListList &pointEdges) const
labelList meshEdges (const labelUList &edgeLabels, const edgeList &allEdges, const labelListList &pointEdges) const
const Field< point_type > & faceCentres () const
const Field< point_type > & faceAreas () const
const Field< scalar > & magFaceAreas () const
const Field< point_type > & faceNormals () const
const Field< point_type > & pointNormals () const
Pair< point_type > box () const
scalar sphere (const label facei) const
bool hasFaceAreas () const
bool hasFaceCentres () const
bool hasFaceNormals () const
bool hasPointNormals () const
bool hasBoundaryPoints () const
bool hasEdges () const
bool hasFaceFaces () const
bool hasEdgeFaces () const
bool hasFaceEdges () const
bool hasPointEdges () const
bool hasPointFaces () const
bool hasMeshPoints () const
bool hasMeshPointMap () const
template<class ToPatch >
List< objectHit > projectPoints (const ToPatch &targetPatch, const Field< point_type > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
template<class ToPatch >
List< objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< point_type > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
const labelListList & edgeLoops () const
surfaceTopo surfaceType (labelHashSet *badEdgesPtr=nullptr) const
bool checkTopology (const bool report=false, labelHashSet *pointSetPtr=nullptr) const
bool checkPointManifold (const bool report=false, labelHashSet *pointSetPtr=nullptr) const
void operator= (const PrimitivePatch< FaceList, PointField > &rhs)
void operator= (PrimitivePatch< FaceList, PointField > &&rhs)
label whichEdge (const edge &e) const
template<class ToPatch >
Foam::List< Foam::objectHit > projectPoints (const ToPatch &targetPatch, const Field< typename Foam::PrimitivePatch< FaceList, PointField >::point_type > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
template<class ToPatch >
Foam::List< Foam::objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< typename Foam::PrimitivePatch< FaceList, PointField >::point_type > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
Public Member Functions inherited from PrimitivePatchBase
ClassName ("PrimitivePatch")
PrimitivePatchBase ()=default
Static Public Attributes
static const scalar tolerance_ = 1e-10
Static Public Attributes inherited from coupledPolyPatch
static const Enum< transformType > transformTypeNames
Static Public Attributes inherited from polyPatch
static int disallowGenericPolyPatch
Protected Member Functions
virtual bool removeAMIFaces (polyTopoChange &topoChange)
virtual bool addAMIFaces (polyTopoChange &topoChange)
virtual void setAMIFaces ()
virtual void restoreScaledGeometry ()
const autoPtr< searchableSurface > & surfPtr () const
autoPtr< coordSystem::cylindrical > cylindricalCS () const
virtual void resetAMI (const UList< point > &points) const
virtual void resetAMI () const
virtual void calcTransforms ()
virtual void initGeometry (PstreamBuffers &)
virtual void calcGeometry (PstreamBuffers &)
virtual void initMovePoints (PstreamBuffers &pBufs, const pointField &)
virtual void movePoints (PstreamBuffers &pBufs, const pointField &)
virtual void initUpdateMesh (PstreamBuffers &)
virtual void updateMesh (PstreamBuffers &)
virtual void clearGeom ()
Protected Member Functions inherited from coupledPolyPatch
void calcTransformTensors (const vectorField &Cf, const vectorField &Cr, const vectorField &nf, const vectorField &nr, const scalarField &smallDist, const scalar absTol, const transformType=UNKNOWN) const
Protected Member Functions inherited from polyPatch
virtual void movePoints (const Field< point_type > &)
Protected Attributes
word nbrPatchName_
const coupleGroupIdentifier coupleGroup_
label nbrPatchID_
const scalar fraction_
vector rotationAxis_
point rotationCentre_
bool rotationAngleDefined_
scalar rotationAngle_
vector separationVector_
word periodicPatchName_
label periodicPatchID_
autoPtr< AMIPatchToPatchInterpolation > AMIPtr_
const dictionary surfDict_
autoPtr< searchableSurface > surfPtr_
bool createAMIFaces_
bool moveFaceCentres_
bool updatingAMI_
labelListList srcFaceIDs_
labelListList tgtFaceIDs_
vectorField faceAreas0_
vectorField faceCentres0_
Additional Inherited Members
Public Types inherited from coupledPolyPatch
enum transformType {
UNKNOWN , ROTATIONAL , TRANSLATIONAL , COINCIDENTFULLMATCH ,
NOORDERING
}
Public Types inherited from PrimitivePatch< FaceList, PointField >
enum surfaceTopo { MANIFOLD , OPEN , ILLEGAL }
typedef std::remove_reference< FaceList >::type::value_type face_type
typedef std::remove_reference< PointField >::type::value_type point_type
typedef FaceList FaceListType
typedef PointField PointFieldType
typedef face_type FaceType
Static Public Member Functions inherited from coupledPolyPatch
static scalarField calcFaceTol (const UList< face > &faces, const pointField &points, const pointField &faceCentres)
Static Public Member Functions inherited from polyPatch
static autoPtr< polyPatch > New (const word &patchType, const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm)
static autoPtr< polyPatch > New (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm)
static autoPtr< polyPatch > New (const word &patchType, const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm)
static bool constraintType (const word &patchType)
static wordList constraintTypes ()
Static Public Member Functions inherited from patchIdentifier
static word defaultName (const label n=-1)
Static Protected Member Functions inherited from coupledPolyPatch
static void writeOBJ (Ostream &os, const point &pt)
static void writeOBJ (Ostream &, const pointField &, const labelList &)
static void writeOBJ (const fileName &, const UList< face > &, const pointField &)
static void writeOBJ (Ostream &os, const point &p0, const point &p1, label &vertI)
static pointField getAnchorPoints (const UList< face > &, const pointField &, const transformType)
static label getRotation (const pointField &points, const face &f, const point &anchor, const scalar tol)
Detailed Description
Cyclic patch for Arbitrary Mesh Interface (AMI)
Includes provision for updating the patch topology to enforce a 1-to-1 face match across the interface, based on the createAMIFaces flag.
The manipulations are based on the reference:
H.J. Aguerre, S. Mrquez Damin, J.M. Gimenez, N.M.Nigro, Conservative
handling of arbitrary non-conformal interfaces using an efficient
supermesh, Journal of Computational Physics 335(15) 21-49. 2017.
https://doi.org/10.1016/j.jcp.2017.01.018.
Source files
cyclicAMIPolyPatch.H
cyclicAMIPolyPatch.C
Definition at line 64 of file cyclicAMIPolyPatch.H.
Constructor & Destructor Documentation
cyclicAMIPolyPatch() [1/5]
cyclicAMIPolyPatch (const word & name, const label size, const label start, const label index, const polyBoundaryMesh & bm, const word & patchType, const transformType transform = UNKNOWN, const word & defaultAMIMethod = faceAreaWeightAMI::typeName)
Definition at line 599 of file cyclicAMIPolyPatch.C.
cyclicAMIPolyPatch() [2/5]
cyclicAMIPolyPatch (const word & name, const dictionary & dict, const label index, const polyBoundaryMesh & bm, const word & patchType, const word & defaultAMIMethod = faceAreaWeightAMI::typeName)
Definition at line 638 of file cyclicAMIPolyPatch.C.
References cyclicAMIPolyPatch::coupleGroup_, cyclicAMIPolyPatch::createAMIFaces_, Foam::degToRad(), dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, Foam::Info, Foam::mag(), cyclicAMIPolyPatch::moveFaceCentres_, patchIdentifier::name(), cyclicAMIPolyPatch::nbrPatchName_, word::null, coupledPolyPatch::ROTATIONAL, cyclicAMIPolyPatch::rotationAngle_, cyclicAMIPolyPatch::rotationAngleDefined_, cyclicAMIPolyPatch::rotationAxis_, cyclicAMIPolyPatch::rotationCentre_, cyclicAMIPolyPatch::separationVector_, List< T >::setSize(), cyclicAMIPolyPatch::srcFaceIDs_, cyclicAMIPolyPatch::tgtFaceIDs_, coupledPolyPatch::transform(), and coupledPolyPatch::TRANSLATIONAL.
cyclicAMIPolyPatch() [3/5]
cyclicAMIPolyPatch (const cyclicAMIPolyPatch & pp, const polyBoundaryMesh & bm)
Definition at line 749 of file cyclicAMIPolyPatch.C.
cyclicAMIPolyPatch() [4/5]
cyclicAMIPolyPatch (const cyclicAMIPolyPatch & pp, const polyBoundaryMesh & bm, const label index, const label newSize, const label newStart, const word & nbrPatchName)
Definition at line 783 of file cyclicAMIPolyPatch.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, patchIdentifier::name(), and cyclicAMIPolyPatch::nbrPatchName_.
cyclicAMIPolyPatch() [5/5]
cyclicAMIPolyPatch (const cyclicAMIPolyPatch & pp, const polyBoundaryMesh & bm, const label index, const labelUList & mapAddressing, const label newStart)
Definition at line 829 of file cyclicAMIPolyPatch.C.
~cyclicAMIPolyPatch()
virtual ~cyclicAMIPolyPatch () virtual default
Member Function Documentation
removeAMIFaces()
bool removeAMIFaces (polyTopoChange & topoChange) protected virtual
Definition at line 75 of file cyclicAMIPolyPatchTopologyChange.C.
References Foam::abort(), PtrList< T >::clear(), DebugInFunction, Foam::endl(), Foam::FatalError, FatalErrorInFunction, and UPtrList< T >::size().
addAMIFaces()
bool addAMIFaces (polyTopoChange & topoChange) protected virtual
Definition at line 130 of file cyclicAMIPolyPatchTopologyChange.C.
References Foam::abort(), DebugInFunction, UPtrList< T >::empty(), Foam::endl(), polyMesh::faceOwner(), polyMesh::faces(), polyMesh::faceZones(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::Info, mesh, boundaryMesh::mesh(), Foam::name(), Foam::nl, Foam::Pout, Foam::returnReduce(), Foam::returnReduceOr(), PtrList< T >::setSize(), UPtrList< T >::size(), and ZoneMesh< ZoneType, MeshType >::whichZone().
setAMIFaces()
void setAMIFaces () protected virtual
Definition at line 254 of file cyclicAMIPolyPatchTopologyChange.C.
References Foam::abort(), DebugInFunction, Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::identity(), Foam::mag(), Foam::name(), Foam::nl, Foam::Pout, and UPtrList< T >::size().
restoreScaledGeometry()
void restoreScaledGeometry () protected virtual
Definition at line 28 of file cyclicAMIPolyPatchTopologyChange.C.
References Foam::abort(), List< T >::clear(), cyclicAMIPolyPatch::createAMIFaces_, DebugInfo, DebugInFunction, Foam::endl(), polyPatch::faceAreas(), cyclicAMIPolyPatch::faceAreas0_, polyPatch::faceCentres(), cyclicAMIPolyPatch::faceCentres0_, Foam::FatalError, FatalErrorInFunction, Foam::gSum(), Foam::mag(), mesh, cyclicAMIPolyPatch::moveFaceCentres_, patchIdentifier::name(), Foam::nl, and WarningInFunction.
surfPtr()
const Foam::autoPtr< Foam::searchableSurface > & surfPtr () const protected
Definition at line 332 of file cyclicAMIPolyPatch.C.
References mesh, boundaryMesh::mesh(), IOobjectOption::MUST_READ, Foam::name(), searchableSurface::New(), IOobjectOption::NO_WRITE, and fvMesh::time().
cylindricalCS()
Foam::autoPtr< Foam::coordSystem::cylindrical > cylindricalCS () const protected
Definition at line 284 of file cyclicAMIPolyPatch.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::name(), autoPtr< T >::New(), and Foam::Zero.
resetAMI() [1/2]
void resetAMI (const UList< point > & points) const protected virtual
Reimplemented in cyclicACMIPolyPatch.
Definition at line 369 of file cyclicAMIPolyPatch.C.
References DebugInFunction, Foam::endl(), Foam::Info, boundaryMesh::mesh(), Foam::name(), os(), Time::path(), UPtrList< T >::size(), and Foam::meshTools::writeOBJ().
resetAMI() [2/2]
void resetAMI () const protected virtual
Reimplemented in cyclicACMIPolyPatch.
Definition at line 363 of file cyclicAMIPolyPatch.C.
References mesh, and points.
Referenced by cyclicACMIPolyPatch::resetAMI().
calcTransforms()
void calcTransforms () protected virtual
Definition at line 443 of file cyclicAMIPolyPatch.C.
References DebugInFunction, DebugPout, Foam::endl(), forAll, Foam::name(), Foam::nl, and UPtrList< T >::size().
initGeometry()
void initGeometry (PstreamBuffers & pBufs) protected virtual
Implements coupledPolyPatch.
Reimplemented in cyclicACMIPolyPatch.
Definition at line 479 of file cyclicAMIPolyPatch.C.
References DebugInFunction, Foam::endl(), and polyPatch::initGeometry().
Referenced by cyclicACMIPolyPatch::initGeometry().
calcGeometry() [1/2]
void calcGeometry (PstreamBuffers & pBufs) protected virtual
Implements coupledPolyPatch.
Reimplemented in cyclicACMIPolyPatch.
Definition at line 496 of file cyclicAMIPolyPatch.C.
References DebugInFunction, and Foam::endl().
Referenced by cyclicACMIPolyPatch::calcGeometry().
initMovePoints()
void initMovePoints (PstreamBuffers & pBufs, const pointField & p) protected virtual
Implements coupledPolyPatch.
Reimplemented in cyclicACMIPolyPatch.
Definition at line 502 of file cyclicAMIPolyPatch.C.
References DebugInFunction, Foam::endl(), PrimitivePatch< FaceList, PointField >::movePoints(), and p.
Referenced by cyclicACMIPolyPatch::initMovePoints().
movePoints()
void movePoints (PstreamBuffers & pBufs, const pointField & p) protected virtual
Implements coupledPolyPatch.
Reimplemented in cyclicACMIPolyPatch.
Definition at line 538 of file cyclicAMIPolyPatch.C.
References DebugInFunction, and Foam::endl().
Referenced by cyclicACMIPolyPatch::movePoints().
initUpdateMesh()
void initUpdateMesh (PstreamBuffers & pBufs) protected virtual
Implements coupledPolyPatch.
Reimplemented in cyclicACMIPolyPatch.
Definition at line 562 of file cyclicAMIPolyPatch.C.
References DebugInFunction, Foam::endl(), polyPatch::initUpdateMesh(), and mesh.
Referenced by cyclicACMIPolyPatch::initUpdateMesh().
updateMesh()
void updateMesh (PstreamBuffers & pBufs) protected virtual
Implements coupledPolyPatch.
Reimplemented in cyclicACMIPolyPatch.
Definition at line 575 of file cyclicAMIPolyPatch.C.
References DebugInFunction, Foam::endl(), and polyPatch::updateMesh().
Referenced by cyclicACMIPolyPatch::updateMesh().
clearGeom()
void clearGeom () protected virtual
Reimplemented from polyPatch.
Reimplemented in cyclicACMIPolyPatch.
Definition at line 584 of file cyclicAMIPolyPatch.C.
References polyPatch::clearGeom(), DebugInFunction, and Foam::endl().
Referenced by cyclicACMIPolyPatch::clearGeom().
TypeName()
TypeName ("cyclicAMI")
clone() [1/3]
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh & bm) const inline virtual
Reimplemented from polyPatch.
Reimplemented in cyclicACMIPolyPatch, and cyclicPeriodicAMIPolyPatch.
Definition at line 278 of file cyclicAMIPolyPatch.H.
clone() [2/3]
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh & bm, const label index, const label newSize, const label newStart) const inline virtual
Reimplemented from polyPatch.
Reimplemented in cyclicACMIPolyPatch, and cyclicPeriodicAMIPolyPatch.
Definition at line 285 of file cyclicAMIPolyPatch.H.
References patchIdentifier::index(), and cyclicAMIPolyPatch::nbrPatchName_.
clone() [3/3]
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh & bm, const label index, const labelUList & mapAddressing, const label newStart) const inline virtual
Reimplemented from polyPatch.
Reimplemented in cyclicACMIPolyPatch, and cyclicPeriodicAMIPolyPatch.
Definition at line 309 of file cyclicAMIPolyPatch.H.
References patchIdentifier::index().
newInternalProcFaces()
void newInternalProcFaces (label & newFaces, label & newProcFaces) const virtual
Reimplemented from polyPatch.
Reimplemented in cyclicACMIPolyPatch.
Definition at line 864 of file cyclicAMIPolyPatch.C.
References forAll.
nbrCells()
virtual const labelUList & nbrCells () const inline virtual
Reimplemented from polyPatch.
Definition at line 344 of file cyclicAMIPolyPatch.H.
References cyclicAMIPolyPatch::neighbPatch().
neighbPolyPatchID()
virtual label neighbPolyPatchID () const inline virtual
Reimplemented from polyPatch.
Definition at line 350 of file cyclicAMIPolyPatch.H.
References cyclicAMIPolyPatch::neighbPatch().
mapCollocatedFaces()
virtual refPtr< labelListList > mapCollocatedFaces () const inline virtual
Reimplemented from polyPatch.
Reimplemented in cyclicACMIPolyPatch.
Definition at line 356 of file cyclicAMIPolyPatch.H.
References cyclicAMIPolyPatch::AMI().
masterImplicit()
virtual bool masterImplicit () const inline virtual
Reimplemented from polyPatch.
Definition at line 363 of file cyclicAMIPolyPatch.H.
References cyclicAMIPolyPatch::owner().
canResetAMI()
bool canResetAMI () const inline
Definition at line 24 of file cyclicAMIPolyPatchI.H.
References boundaryMesh::mesh(), and UPstream::parRun().
createAMIFaces()
bool createAMIFaces () const inline
Definition at line 30 of file cyclicAMIPolyPatchI.H.
updatingAMI()
bool updatingAMI () const inline
Definition at line 36 of file cyclicAMIPolyPatchI.H.
changeTopology()
bool changeTopology () const virtual
Reimplemented from polyPatch.
Definition at line 640 of file cyclicAMIPolyPatchTopologyChange.C.
References DebugInFunction, and Foam::endl().
setTopology()
bool setTopology (polyTopoChange & topoChange) virtual
Reimplemented from polyPatch.
Definition at line 650 of file cyclicAMIPolyPatchTopologyChange.C.
References DebugInFunction, and Foam::endl().
coupled()
virtual bool coupled () const inline virtual
Reimplemented from coupledPolyPatch.
Definition at line 392 of file cyclicAMIPolyPatch.H.
neighbPatchName()
const Foam::word & neighbPatchName () const inline
Definition at line 42 of file cyclicAMIPolyPatchI.H.
References patchID.
Referenced by cyclicACMIPolyPatch::clone().
neighbPatchID()
Foam::label neighbPatchID () const virtual
Definition at line 896 of file cyclicAMIPolyPatch.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::name(), Foam::nl, and WarningInFunction.
Referenced by cyclicACMIFvPatch::neighbFvPatch(), cyclicAMIFvPatch::neighbFvPatch(), cyclicACMIFvPatch::neighbPatch(), cyclicAMIFvPatch::neighbPatch(), cyclicACMIPointPatch::neighbPatch(), cyclicAMIPointPatch::neighbPatch(), cyclicACMIFvPatch::neighbPatchID(), and cyclicAMIFvPatch::neighbPatchID().
fraction()
Foam::scalar fraction () const inline
Definition at line 55 of file cyclicAMIPolyPatchI.H.
owner()
bool owner () const virtual
Implements coupledPolyPatch.
Definition at line 958 of file cyclicAMIPolyPatch.C.
Referenced by cyclicAMIPolyPatch::interpolateUntransformed(), cyclicAMIPolyPatch::masterImplicit(), combine< Type, TrackingData >::operator()(), cyclicACMIFvPatch::owner(), cyclicAMIFvPatch::owner(), and cyclicACMIPolyPatch::updateAreas().
neighbPatch()
const Foam::cyclicAMIPolyPatch & neighbPatch () const virtual
Reimplemented in cyclicACMIPolyPatch.
Definition at line 964 of file cyclicAMIPolyPatch.C.
References pp().
Referenced by cyclicAMIPolyPatch::interpolateUntransformed(), cyclicAMIPolyPatch::nbrCells(), cyclicAMIPolyPatch::neighbPolyPatchID(), and combine< Type, TrackingData >::operator()().
periodicPatchID()
Foam::label periodicPatchID () const
Definition at line 932 of file cyclicAMIPolyPatch.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::nl, and word::null.
AMI()
const Foam::AMIPatchToPatchInterpolation & AMI () const
Definition at line 971 of file cyclicAMIPolyPatch.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Referenced by cyclicACMIFvPatch::AMI(), cyclicAMIFvPatch::AMI(), cyclicAMIPolyPatch::interpolateUntransformed(), and cyclicAMIPolyPatch::mapCollocatedFaces().
weights()
const Foam::scalarListList & weights () const inline
Definition at line 61 of file cyclicAMIPolyPatchI.H.
weightsSum()
const Foam::scalarField & weightsSum () const inline
Definition at line 72 of file cyclicAMIPolyPatchI.H.
applyLowWeightCorrection()
bool applyLowWeightCorrection () const
Definition at line 989 of file cyclicAMIPolyPatch.C.
Referenced by cyclicAMIFvPatch::applyLowWeightCorrection().
faceAreas0()
Foam::vectorField & faceAreas0 () const inline
Definition at line 83 of file cyclicAMIPolyPatchI.H.
faceCentres0()
Foam::vectorField & faceCentres0 () const inline
Definition at line 89 of file cyclicAMIPolyPatchI.H.
rotationAxis()
const Foam::vector & rotationAxis () const inline
Definition at line 94 of file cyclicAMIPolyPatchI.H.
rotationCentre()
const Foam::point & rotationCentre () const inline
Definition at line 100 of file cyclicAMIPolyPatchI.H.
separationVector()
const Foam::vector & separationVector () const inline
Definition at line 106 of file cyclicAMIPolyPatchI.H.
transformPosition() [1/2]
void transformPosition (pointField & l) const virtual
Implements coupledPolyPatch.
Definition at line 1002 of file cyclicAMIPolyPatch.C.
References forAll, s(), UPtrList< T >::size(), and Foam::transform().
transformPosition() [2/2]
void transformPosition (point & l, const label facei) const virtual
Implements coupledPolyPatch.
Definition at line 1037 of file cyclicAMIPolyPatch.C.
References s(), T, and Foam::transform().
reverseTransformPosition()
void reverseTransformPosition (point & l, const label facei) const virtual
Definition at line 1075 of file cyclicAMIPolyPatch.C.
References s(), T, and Foam::transform().
reverseTransformDirection()
void reverseTransformDirection (vector & d, const label facei) const virtual
Definition at line 1113 of file cyclicAMIPolyPatch.C.
References T, and Foam::transform().
interpolate() [1/5]
template<class Type > tmp< Field< Type > > interpolate (const Field< Type > & fld, const UList< Type > & defaultValues = UList< Type >()) const
Referenced by cyclicAMIFvPatch::interpolate(), and cyclicAMIFvPatch::interpolate().
interpolate() [2/5]
template<class Type > tmp< Field< Type > > interpolate (const tmp< Field< Type > > & tFld, const UList< Type > & defaultValues = UList< Type >()) const
interpolateUntransformed() [1/2]
template<class Type > tmp< Field< Type > > interpolateUntransformed (const Field< Type > & fld, const UList< Type > & defaultValues) const
interpolate() [3/5]
template<class Type , class CombineOp > void interpolate (const UList< Type > & fld, const CombineOp & cop, List< Type > & result, const UList< Type > & defaultValues = UList<Type>()) const
Definition at line 155 of file cyclicAMIPolyPatchTemplates.C.
References fld().
calcGeometry() [2/2]
void calcGeometry (const primitivePatch & referPatch, const pointField & thisCtrs, const vectorField & thisAreas, const pointField & thisCc, const pointField & nbrCtrs, const vectorField & nbrAreas, const pointField & nbrCc) virtual
Implements coupledPolyPatch.
Definition at line 1133 of file cyclicAMIPolyPatch.C.
initOrder()
void initOrder (PstreamBuffers & pBufs, const primitivePatch & pp) const virtual
Implements coupledPolyPatch.
Reimplemented in cyclicACMIPolyPatch.
Definition at line 1146 of file cyclicAMIPolyPatch.C.
Referenced by cyclicACMIPolyPatch::initOrder().
order()
bool order (PstreamBuffers & pBufs, const primitivePatch & pp, labelList & faceMap, labelList & rotation) const virtual
Implements coupledPolyPatch.
Reimplemented in cyclicACMIPolyPatch.
Definition at line 1154 of file cyclicAMIPolyPatch.C.
References Foam::faceMap(), pp(), List< T >::setSize(), and PtrList< T >::setSize().
Referenced by cyclicACMIPolyPatch::order().
pointFace()
Foam::label pointFace (const label facei, const vector & n, point & p) const
Definition at line 1172 of file cyclicAMIPolyPatch.C.
References n, and p.
write()
void write (Ostream & os) const virtual
Reimplemented from coupledPolyPatch.
Reimplemented in cyclicACMIPolyPatch, and cyclicPeriodicAMIPolyPatch.
Definition at line 1219 of file cyclicAMIPolyPatch.C.
References word::null, os(), Foam::radToDeg(), Foam::transform(), Ostream::write(), coupledPolyPatch::write(), Ostream::writeEntry(), Ostream::writeEntryIfDifferent(), and Foam::Zero.
Referenced by cyclicACMIPolyPatch::write(), and cyclicPeriodicAMIPolyPatch::write().
interpolateUntransformed() [2/2]
template<class Type > Foam::tmp< Foam::Field< Type > > interpolateUntransformed (const Field< Type > & fld, const UList< Type > & defaultValues) const
Definition at line 25 of file cyclicAMIPolyPatchTemplates.C.
References cyclicAMIPolyPatch::AMI(), fld(), cyclicAMIPolyPatch::neighbPatch(), and cyclicAMIPolyPatch::owner().
interpolate() [4/5]
template<class Type > Foam::tmp< Foam::Field< Type > > interpolate (const Field< Type > & fld, const UList< Type > & defaultValues) const
Definition at line 43 of file cyclicAMIPolyPatchTemplates.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, fld(), forAll, Foam::gAverage(), Foam::invTransform(), Foam::name(), Foam::New(), Foam::nl, Foam::Pout, R, UPtrList< T >::size(), T, and Foam::transform().
interpolate() [5/5]
template<class Type > Foam::tmp< Foam::Field< Type > > interpolate (const tmp< Field< Type > > & tFld, const UList< Type > & defaultValues) const
Definition at line 144 of file cyclicAMIPolyPatchTemplates.C.
References Foam::interpolate().
Member Data Documentation
nbrPatchName_
word nbrPatchName_ mutable protected
Definition at line 88 of file cyclicAMIPolyPatch.H.
Referenced by cyclicAMIPolyPatch::clone(), cyclicPeriodicAMIPolyPatch::clone(), cyclicAMIPolyPatch::cyclicAMIPolyPatch(), and cyclicAMIPolyPatch::cyclicAMIPolyPatch().
coupleGroup_
const coupleGroupIdentifier coupleGroup_ protected
Definition at line 91 of file cyclicAMIPolyPatch.H.
Referenced by cyclicAMIPolyPatch::cyclicAMIPolyPatch().
nbrPatchID_
label nbrPatchID_ mutable protected
Definition at line 94 of file cyclicAMIPolyPatch.H.
fraction_
const scalar fraction_ protected
Definition at line 97 of file cyclicAMIPolyPatch.H.
rotationAxis_
vector rotationAxis_ protected
Definition at line 105 of file cyclicAMIPolyPatch.H.
Referenced by cyclicAMIPolyPatch::cyclicAMIPolyPatch().
rotationCentre_
point rotationCentre_ protected
Definition at line 108 of file cyclicAMIPolyPatch.H.
Referenced by cyclicAMIPolyPatch::cyclicAMIPolyPatch().
rotationAngleDefined_
bool rotationAngleDefined_ protected
Definition at line 111 of file cyclicAMIPolyPatch.H.
Referenced by cyclicAMIPolyPatch::cyclicAMIPolyPatch().
rotationAngle_
scalar rotationAngle_ protected
Definition at line 114 of file cyclicAMIPolyPatch.H.
Referenced by cyclicAMIPolyPatch::cyclicAMIPolyPatch().
separationVector_
vector separationVector_ protected
Definition at line 120 of file cyclicAMIPolyPatch.H.
Referenced by cyclicAMIPolyPatch::cyclicAMIPolyPatch().
periodicPatchName_
word periodicPatchName_ protected
Definition at line 126 of file cyclicAMIPolyPatch.H.
periodicPatchID_
label periodicPatchID_ mutable protected
Definition at line 129 of file cyclicAMIPolyPatch.H.
AMIPtr_
autoPtr<AMIPatchToPatchInterpolation> AMIPtr_ mutable protected
Definition at line 133 of file cyclicAMIPolyPatch.H.
Referenced by cyclicACMIPolyPatch::cyclicACMIPolyPatch(), cyclicACMIPolyPatch::cyclicACMIPolyPatch(), cyclicACMIPolyPatch::cyclicACMIPolyPatch(), cyclicACMIPolyPatch::cyclicACMIPolyPatch(), cyclicACMIPolyPatch::cyclicACMIPolyPatch(), cyclicPeriodicAMIPolyPatch::cyclicPeriodicAMIPolyPatch(), cyclicPeriodicAMIPolyPatch::cyclicPeriodicAMIPolyPatch(), cyclicPeriodicAMIPolyPatch::cyclicPeriodicAMIPolyPatch(), cyclicPeriodicAMIPolyPatch::cyclicPeriodicAMIPolyPatch(), and cyclicPeriodicAMIPolyPatch::cyclicPeriodicAMIPolyPatch().
surfDict_
const dictionary surfDict_ protected
Definition at line 136 of file cyclicAMIPolyPatch.H.
surfPtr_
autoPtr<searchableSurface> surfPtr_ mutable protected
Definition at line 139 of file cyclicAMIPolyPatch.H.
createAMIFaces_
bool createAMIFaces_ mutable protected
Definition at line 146 of file cyclicAMIPolyPatch.H.
Referenced by cyclicAMIPolyPatch::cyclicAMIPolyPatch(), cyclicAMIPolyPatch::restoreScaledGeometry(), and cyclicACMIPolyPatch::updateAreas().
moveFaceCentres_
bool moveFaceCentres_ protected
Definition at line 149 of file cyclicAMIPolyPatch.H.
Referenced by cyclicAMIPolyPatch::cyclicAMIPolyPatch(), and cyclicAMIPolyPatch::restoreScaledGeometry().
updatingAMI_
bool updatingAMI_ mutable protected
Definition at line 151 of file cyclicAMIPolyPatch.H.
srcFaceIDs_
labelListList srcFaceIDs_ protected
Definition at line 153 of file cyclicAMIPolyPatch.H.
Referenced by cyclicAMIPolyPatch::cyclicAMIPolyPatch().
tgtFaceIDs_
labelListList tgtFaceIDs_ protected
Definition at line 155 of file cyclicAMIPolyPatch.H.
Referenced by cyclicAMIPolyPatch::cyclicAMIPolyPatch().
faceAreas0_
vectorField faceAreas0_ mutable protected
Definition at line 158 of file cyclicAMIPolyPatch.H.
Referenced by cyclicAMIPolyPatch::restoreScaledGeometry().
faceCentres0_
vectorField faceCentres0_ mutable protected
Definition at line 161 of file cyclicAMIPolyPatch.H.
Referenced by cyclicAMIPolyPatch::restoreScaledGeometry().
tolerance_
const Foam::scalar tolerance_ = 1e-10 static
Definition at line 372 of file cyclicAMIPolyPatch.H.
Referenced by cyclicACMIPolyPatch::updateAreas().
The documentation for this class was generated from the following files:
src/meshTools/AMIInterpolation/patches/cyclicAMI/cyclicAMIPolyPatch/cyclicAMIPolyPatch.H
src/meshTools/AMIInterpolation/patches/cyclicAMI/cyclicAMIPolyPatch/cyclicAMIPolyPatch.C
src/meshTools/AMIInterpolation/patches/cyclicAMI/cyclicAMIPolyPatch/cyclicAMIPolyPatchI.H
src/meshTools/AMIInterpolation/patches/cyclicAMI/cyclicAMIPolyPatch/cyclicAMIPolyPatchTemplates.C
src/meshTools/AMIInterpolation/patches/cyclicAMI/cyclicAMIPolyPatch/cyclicAMIPolyPatchTopologyChange.C