OpenFOAM: PatchEdgeFaceWave< PrimitivePatchType, Type, TrackingData > Class Template Reference
PatchEdgeFaceWave< PrimitivePatchType, Type, TrackingData > Class Template Reference
Wave propagation of information along patch. Every iteration information goes through one layer of faces. Templated on information that is transferred.
#include <PatchEdgeFaceWave.H>
Public Member Functions
PatchEdgeFaceWave (const polyMesh &mesh, const PrimitivePatchType &patch, const labelList &initialEdges, const List< Type > &initialEdgesInfo, UList< Type > &allEdgeInfo, UList< Type > &allFaceInfo, const label maxIter, TrackingData &td=PatchEdgeFaceWaveBase::dummyTrackData_)
PatchEdgeFaceWave (const polyMesh &mesh, const PrimitivePatchType &patch, UList< Type > &allEdgeInfo, UList< Type > &allFaceInfo, TrackingData &td=PatchEdgeFaceWaveBase::dummyTrackData_)
UList< Type > & allEdgeInfo () const noexcept
UList< Type > & allFaceInfo () const noexcept
const TrackingData & data () const noexcept
void setEdgeInfo (const labelList &changedEdges, const List< Type > &changedEdgesInfo)
label edgeToFace ()
label faceToEdge ()
label iterate (const label maxIter)
Public Member Functions inherited from PatchEdgeFaceWaveBase
ClassName ("PatchEdgeFaceWave")
PatchEdgeFaceWaveBase (const polyMesh &mesh, const label nEdges, const label nFaces)
const polyMesh & mesh () const noexcept
label nChangedEdges () const noexcept
label nChangedFaces () const noexcept
label nUnvisitedFaces () const noexcept
label nUnvisitedEdges () const noexcept
Additional Inherited Members
Static Public Member Functions inherited from PatchEdgeFaceWaveBase
static scalar propagationTol () noexcept
static scalar setPropagationTol (const scalar tol) noexcept
Static Public Attributes inherited from PatchEdgeFaceWaveBase
static label dummyTrackData_ = 12345
Protected Attributes inherited from PatchEdgeFaceWaveBase
const polyMesh & mesh_
bitSet changedEdge_
bitSet changedFace_
DynamicList< label > changedEdges_
DynamicList< label > changedFaces_
label nUnvisitedEdges_
label nUnvisitedFaces_
Static Protected Attributes inherited from PatchEdgeFaceWaveBase
static scalar propagationTol_ = 0.01
Detailed Description
template<class PrimitivePatchType, class Type, class TrackingData = label>
class Foam::PatchEdgeFaceWave< PrimitivePatchType, Type, TrackingData >
Wave propagation of information along patch. Every iteration information goes through one layer of faces. Templated on information that is transferred.
Source files
PatchEdgeFaceWave.H
PatchEdgeFaceWave.C
Definition at line 163 of file PatchEdgeFaceWave.H.
Constructor & Destructor Documentation
PatchEdgeFaceWave() [1/2]
template<class PrimitivePatchType , class Type , class TrackingData > PatchEdgeFaceWave (const polyMesh & mesh, const PrimitivePatchType & patch, const labelList & initialEdges, const List< Type > & initialEdgesInfo, UList< Type > & allEdgeInfo, UList< Type > & allFaceInfo, const label maxIter, TrackingData & td = PatchEdgeFaceWaveBase::dummyTrackData_)
Definition at line 259 of file PatchEdgeFaceWave.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, PatchEdgeFaceWave< PrimitivePatchType, Type, TrackingData >::iterate(), PatchTools::matchEdges(), PatchEdgeFaceWaveBase::mesh_, PatchEdgeFaceWaveBase::nChangedEdges(), PatchEdgeFaceWaveBase::nChangedFaces(), Foam::nl, Foam::Pout, PatchEdgeFaceWave< PrimitivePatchType, Type, TrackingData >::setEdgeInfo(), UPtrList< T >::size(), and UList< T >::size().
PatchEdgeFaceWave() [2/2]
template<class PrimitivePatchType , class Type , class TrackingData > PatchEdgeFaceWave (const polyMesh & mesh, const PrimitivePatchType & patch, UList< Type > & allEdgeInfo, UList< Type > & allFaceInfo, TrackingData & td = PatchEdgeFaceWaveBase::dummyTrackData_)
Definition at line 343 of file PatchEdgeFaceWave.C.
References PatchTools::matchEdges(), and PatchEdgeFaceWaveBase::mesh_.
Member Function Documentation
allEdgeInfo()
template<class PrimitivePatchType , class Type , class TrackingData = label> UList< Type > & allEdgeInfo () const inline noexcept
Definition at line 259 of file PatchEdgeFaceWave.H.
allFaceInfo()
template<class PrimitivePatchType , class Type , class TrackingData = label> UList< Type > & allFaceInfo () const inline noexcept
Definition at line 265 of file PatchEdgeFaceWave.H.
data()
template<class PrimitivePatchType , class Type , class TrackingData = label> const TrackingData & data () const inline noexcept
Definition at line 271 of file PatchEdgeFaceWave.H.
setEdgeInfo()
template<class PrimitivePatchType , class Type , class TrackingData > void setEdgeInfo (const labelList & changedEdges, const List< Type > & changedEdgesInfo)
Definition at line 383 of file PatchEdgeFaceWave.C.
References forAll, and PtrList< T >::push_back().
Referenced by PatchEdgeFaceWave< PrimitivePatchType, Type, TrackingData >::PatchEdgeFaceWave().
edgeToFace()
template<class PrimitivePatchType , class Type , class TrackingData > Foam::label edgeToFace ()
Definition at line 483 of file PatchEdgeFaceWave.C.
References Foam::abort(), PtrList< T >::clear(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, Foam::nl, Foam::Pout, and Foam::returnReduce().
faceToEdge()
template<class PrimitivePatchType , class Type , class TrackingData > Foam::label faceToEdge ()
Definition at line 422 of file PatchEdgeFaceWave.C.
References Foam::abort(), PtrList< T >::clear(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::nl, Foam::Pout, and Foam::returnReduce().
iterate()
template<class PrimitivePatchType , class Type , class TrackingData > Foam::label iterate (const label maxIter)
Definition at line 539 of file PatchEdgeFaceWave.C.
References Foam::endl(), Foam::nl, and Foam::Pout.
Referenced by PatchEdgeFaceWave< PrimitivePatchType, Type, TrackingData >::PatchEdgeFaceWave().
The documentation for this class was generated from the following files:
src/meshTools/algorithms/PatchEdgeFaceWave/PatchEdgeFaceWave.H
src/meshTools/algorithms/PatchEdgeFaceWave/PatchEdgeFaceWave.C