OpenFOAM: faPatch Class Reference
faPatch Class Reference
Finite area patch class. Used for 2-D non-Euclidian finite area method.
#include <faPatch.H>
Public Types
typedef faBoundaryMesh BoundaryMesh
Public Types inherited from List< label >
typedef SubList< label > subList
Public Types inherited from UList< T >
typedef T value_type
typedef T * pointer
typedef const T * const_pointer
typedef T & reference
typedef const T & const_reference
typedef T * iterator
typedef const T * const_iterator
typedef label size_type
typedef label difference_type
typedef std::reverse_iterator< iterator > reverse_iterator
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
Public Member Functions
TypeName ("patch")
declareRunTimeSelectionTable (autoPtr, faPatch, dictionary,(const word &name, const dictionary &dict, const label index, const faBoundaryMesh &bm, const word &patchType),(name, dict, index, bm, patchType))
faPatch (const word &name, const labelUList &edgeLabels, const label index, const faBoundaryMesh &bm, const label nbrPolyPatchi, const word &patchType)
faPatch (const word &name, const dictionary &dict, const label index, const faBoundaryMesh &bm, const word &patchType)
faPatch (const faPatch &p, const faBoundaryMesh &bm)
faPatch (const faPatch &p, const faBoundaryMesh &bm, const label index, const labelUList &edgeLabels, const label nbrPolyPatchi)
virtual autoPtr< faPatch > clone (const faBoundaryMesh &bm) const
virtual autoPtr< faPatch > clone (const faBoundaryMesh &bm, const labelUList &edgeLabels, const label index, const label nbrPolyPatchi) const
virtual ~faPatch ()
const labelList & edgeLabels () const noexcept
label nPoints () const
label nEdges () const noexcept
label ngbPolyPatchIndex () const noexcept
const faBoundaryMesh & boundaryMesh () const noexcept
virtual bool coupled () const
label offset () const
label start () const
virtual label size () const
label whichEdge (const label edgei) const
template<class T >
const List< T >::subList patchSlice (const List< T > &values) const
template<class T >
const List< T >::subList boundarySlice (const List< T > &values) const
virtual void write (Ostream &) const
List< labelPair > boundaryConnections () const
labelList boundaryProcs () const
List< labelPair > boundaryProcSizes () const
const labelList & pointLabels () const
const labelListList & pointEdges () const
tmp< vectorField > ngbPolyPatchFaceNormals () const
tmp< vectorField > ngbPolyPatchPointNormals () const
const labelUList & edgeFaces () const
const vectorField & edgeCentres () const
const vectorField & edgeLengths () const
const scalarField & magEdgeLengths () const
tmp< vectorField > edgeNormals () const
tmp< vectorField > edgeFaceCentres () const
virtual tmp< vectorField > delta () const
virtual void makeWeights (scalarField &) const
const scalarField & weights () const
virtual void makeDeltaCoeffs (scalarField &) const
void makeCorrectionVectors (vectorField &) const
const scalarField & deltaCoeffs () const
void resetEdges (const labelUList &newEdges)
void resetEdges (labelList &&newEdges)
template<class Type >
void patchInternalField (const UList< Type > &internalData, const labelUList &addressing, Field< Type > &pfld) const
template<class Type >
void patchInternalField (const UList< Type > &internalData, Field< Type > &pfld) const
template<class Type >
tmp< Field< Type > > patchInternalField (const UList< Type > &internalData) const
template<class GeometricField , class AnyType = bool>
const GeometricField::Patch & patchField (const GeometricField &gf) const
template<class GeometricField , class AnyType = bool>
const GeometricField::Patch & lookupPatchField (const word &name, const GeometricField *=nullptr, const AnyType *=nullptr) const
template<class Type >
Foam::tmp< Foam::Field< Type > > patchInternalField (const UList< Type > &internalData) const
Public Member Functions inherited from patchIdentifier
patchIdentifier (const patchIdentifier &)=default
patchIdentifier & operator= (const patchIdentifier &)=default
virtual ~patchIdentifier ()=default
patchIdentifier ()
patchIdentifier (const word &name, const label index)
patchIdentifier (const word &name, const label index, const word &physicalType, const wordList &inGroups=wordList())
patchIdentifier (const word &name, const dictionary &dict, const label index)
patchIdentifier (const patchIdentifier &ident, const label index)
const word & name () const noexcept
word & name () noexcept
label index () const noexcept
label & index () noexcept
const word & physicalType () const noexcept
word & physicalType () noexcept
const wordList & inGroups () const noexcept
wordList & inGroups () noexcept
bool inGroup (const word &name) const
void write (Ostream &os) const
Public Member Functions inherited from List< label >
constexpr List () noexcept
List (const label len)
List (const label len, const label &val)
List (const label len, const Foam::zero)
List (const Foam::one, const label &val)
List (const Foam::one, label &&val)
List (const Foam::one, const Foam::zero)
List (const List< label > &a)
List (const UList< label > &a)
List (List< label > &a, bool reuse)
List (const UList< label > &list, const labelUList &indices)
List (const UList< label > &list, const FixedList< label, N > &indices)
List (const FixedList< label, N > &list)
List (const PtrList< label > &list)
List (const SLList< label > &list)
List (const IndirectListBase< label, Addr > &list)
List (std::initializer_list< label > list)
List (List< label > &&list)
List (DynamicList< label, SizeMin > &&list)
List (SLList< label > &&list)
List (Istream &is)
autoPtr< List< label > > clone () const
~List ()
void clear ()
void resize (const label len)
void resize (const label len, const label &val)
void resize (const label newLen)
void resize_nocopy (const label len)
void setSize (const label n)
void setSize (const label n, const label &val)
void transfer (List< label > &list)
void transfer (DynamicList< label, SizeMin > &list)
label & newElmt (const label i)
label & emplace_back (Args &&... args)
void push_back (const label &val)
void push_back (label &&val)
void push_back (const UList< label > &list)
void push_back (const IndirectListBase< label, Addr > &list)
label push_uniq (const label &val)
void pop_back (label n=1)
void operator= (const UList< label > &a)
void operator= (const List< label > &list)
void operator= (const SLList< label > &list)
void operator= (const IndirectListBase< label, Addr > &list)
void operator= (const FixedList< label, N > &list)
void operator= (std::initializer_list< label > list)
void operator= (const label &val)
void operator= (const Foam::zero)
void operator= (List< label > &&list)
void operator= (DynamicList< label, SizeMin > &&list)
void operator= (SLList< label > &&list)
Istream & readList (Istream &is)
Istream & readList (Istream &is)
Istream & readList (Istream &is)
void shallowCopy (const UList< label > &)=delete
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type set (const label i, bool val=true)
void append (const label &val)
void append (label &&val)
void append (const UList< label > &list)
void append (const IndirectListBase< label, Addr > &list)
label appendUniq (const label &val)
Public Member Functions inherited from UList< T >
UList (const UList< T > &)=default
constexpr UList () noexcept
UList (T *__restrict__ v, const label len) noexcept
label fcIndex (const label i) const noexcept
label rcIndex (const label i) const noexcept
const T & fcValue (const label i) const
T & fcValue (const label i)
const T & rcValue (const label i) const
T & rcValue (const label i)
const T * cdata () const noexcept
T * data () noexcept
const char * cdata_bytes () const noexcept
char * data_bytes () noexcept
T & front ()
const T & front () const
T & back ()
const T & back () const
std::streamsize size_bytes () const noexcept
std::streamsize byteSize () const
void checkStart (const label start) const
void checkSize (const label size) const
void checkRange (const label start, const label len) const
void checkIndex (const label i) const
bool uniform () const
label find (const T &val, label pos=0) const
label rfind (const T &val, label pos=-1) const
bool contains (const T &val, label pos=0) const
void moveFirst (const label i)
void moveLast (const label i)
void swapFirst (const label i)
void swapLast (const label i)
void shallowCopy (const UList< T > &list)
void deepCopy (const UList< T > &list)
template<class Addr >
void deepCopy (const IndirectListBase< T, Addr > &list)
SubList< T > slice (const label pos, label len=-1)
const SubList< T > slice (const label pos, label len=-1) const
SubList< T > slice (const labelRange &range)
const SubList< T > slice (const labelRange &range) const
T & operator[] (const label i)
const T & operator[] (const label i) const
operator const Foam::List< T > & () const
void operator= (const T &val)
void operator= (const Foam::zero)
iterator begin () noexcept
iterator end () noexcept
iterator begin (const label i) noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
const_iterator begin () const noexcept
const_iterator end () const noexcept
const_iterator cbegin (const label i) const noexcept
const_iterator begin (const label i) const noexcept
reverse_iterator rbegin ()
reverse_iterator rend ()
const_reverse_iterator crbegin () const
const_reverse_iterator crend () const
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
bool empty () const noexcept
label size () const noexcept
void swap (UList< T > &list)
bool operator== (const UList< T > &a) const
bool operator!= (const UList< T > &a) const
bool operator< (const UList< T > &list) const
bool operator> (const UList< T > &a) const
bool operator<= (const UList< T > &a) const
bool operator>= (const UList< T > &a) const
Istream & readList (Istream &is)
void writeEntry (const word &keyword, Ostream &os) const
Ostream & writeList (Ostream &os, const label shortLen=0) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type test (const label i) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type get (const label i) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type unset (const label i)
T & first ()
const T & first () const
T & last ()
const T & last () const
bool found (const T &val, label pos=0) const
Istream & readList (Istream &is)
Ostream & writeList (Ostream &os, const label) const
const bool & operator[] (const label i) const
UPstream::commsStruct & operator[] (const label procID)
const UPstream::commsStruct & operator[] (const label procID) const
Foam::UPstream::commsStruct & operator[] (const label procID)
const Foam::UPstream::commsStruct & operator[] (const label procID) const
Ostream & writeList (Ostream &os, const label) const
Istream & readList (Istream &is)
Static Public Member Functions
static autoPtr< faPatch > New (const word &name, const dictionary &dict, const label index, const faBoundaryMesh &bm)
static autoPtr< faPatch > New (const word &patchType, const word &name, const dictionary &dict, const label index, const faBoundaryMesh &bm)
static bool constraintType (const word &patchType)
static wordList constraintTypes ()
Static Public Member Functions inherited from patchIdentifier
static word defaultName (const label n=-1)
Static Public Member Functions inherited from List< label >
static const List< label > & null ()
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
static constexpr label max_size () noexcept
Protected Member Functions
void calcPointLabels () const
void calcPointEdges () const
virtual void initGeometry (PstreamBuffers &)
virtual void calcGeometry (PstreamBuffers &)
virtual void initMovePoints (PstreamBuffers &, const pointField &)
virtual void movePoints (PstreamBuffers &, const pointField &)
virtual void initUpdateMesh (PstreamBuffers &)
virtual void updateMesh (PstreamBuffers &)
Protected Member Functions inherited from UList< T >
void setAddressableSize (const label n) noexcept
void size (const label n)
void writeEntry (Ostream &os) const
labelRange validateRange (const labelRange &requestedRange) const
UList< T > & operator= (const UList< T > &)=delete
void writeEntry (Ostream &os) const
void writeEntry (Ostream &os) const
Friends
class faBoundaryMesh
Ostream & operator<< (Ostream &, const faPatch &)
Detailed Description
Finite area patch class. Used for 2-D non-Euclidian finite area method.
Author Zeljko Tukovic, FMENA Hrvoje Jasak, Wikki Ltd.
Source files
faPatch.H
faPatch.C
faPatchNew.C
faPatchTemplates.C
faPatchFaMeshTemplates.C
Definition at line 72 of file faPatch.H.
Member Typedef Documentation
BoundaryMesh
typedef faBoundaryMesh BoundaryMesh
Definition at line 147 of file faPatch.H.
Constructor & Destructor Documentation
faPatch() [1/4]
faPatch (const word & name, const labelUList & edgeLabels, const label index, const faBoundaryMesh & bm, const label nbrPolyPatchi, const word & patchType)
Definition at line 89 of file faPatch.C.
References faPatch::constraintType(), and patchIdentifier::inGroups().
faPatch() [2/4]
faPatch (const word & name, const dictionary & dict, const label index, const faBoundaryMesh & bm, const word & patchType)
Definition at line 114 of file faPatch.C.
References faPatch::constraintType(), and patchIdentifier::inGroups().
faPatch() [3/4]
faPatch (const faPatch & p, const faBoundaryMesh & bm)
Definition at line 157 of file faPatch.C.
faPatch() [4/4]
faPatch (const faPatch & p, const faBoundaryMesh & bm, const label index, const labelUList & edgeLabels, const label nbrPolyPatchi)
Definition at line 138 of file faPatch.C.
~faPatch()
~faPatch () virtual
Definition at line 176 of file faPatch.C.
Member Function Documentation
calcPointLabels()
void calcPointLabels () const protected
const labelList& edgePoints = *pointLabelsPtr_;
// Cannot use invertManyToMany - we have non-local edge numbering
// Intermediate storage for pointEdges. // Points on the boundary will normally connect 1 or 2 edges only. List<DynamicList<label,2>> dynPointEdges(edgePoints.size());
forAll(edges, edgei) { const edge& e = edges[edgei];
dynPointEdges[markedPoints[e.first()]].append(edgei); dynPointEdges[markedPoints[e.second()]].append(edgei); }
// Flatten to regular list pointEdgesPtr_ = new labelListList(edgePoints.size()); auto& pEdges = *pointEdgesPtr_;
forAll(pEdges, pointi) { pEdges[pointi] = std::move(dynPointEdges[pointi]); }
Definition at line 299 of file faPatch.C.
References PtrList< T >::append(), e, UList< T >::first(), mesh, and UPtrList< T >::size().
calcPointEdges()
void calcPointEdges () const protected
Definition at line 356 of file faPatch.C.
References PtrList< T >::append(), e, UList< T >::first(), forAll, mesh, pointLabels(), and UPtrList< T >::size().
initGeometry()
virtual void initGeometry (PstreamBuffers &) inline protected virtual
Reimplemented in cyclicFaPatch, processorFaPatch, and coupledFaPatch.
Definition at line 121 of file faPatch.H.
Referenced by cyclicFaPatch::initGeometry().
calcGeometry()
virtual void calcGeometry (PstreamBuffers &) inline protected virtual
Reimplemented in cyclicFaPatch, processorFaPatch, and coupledFaPatch.
Definition at line 125 of file faPatch.H.
Referenced by cyclicFaPatch::calcGeometry().
initMovePoints()
virtual void initMovePoints (PstreamBuffers & , const pointField &) inline protected virtual
Reimplemented in cyclicFaPatch, processorFaPatch, and coupledFaPatch.
Definition at line 129 of file faPatch.H.
Referenced by cyclicFaPatch::initMovePoints().
movePoints()
void movePoints (PstreamBuffers & , const pointField &) protected virtual
Reimplemented in cyclicFaPatch, processorFaPatch, and coupledFaPatch.
Definition at line 539 of file faPatch.C.
Referenced by processorFaPatch::initMovePoints(), and cyclicFaPatch::movePoints().
initUpdateMesh()
virtual void initUpdateMesh (PstreamBuffers &) inline protected virtual
Reimplemented in processorFaPatch.
Definition at line 136 of file faPatch.H.
Referenced by processorFaPatch::initUpdateMesh().
updateMesh()
virtual void updateMesh (PstreamBuffers &) inline protected virtual
Reimplemented in processorFaPatch.
Definition at line 140 of file faPatch.H.
Referenced by processorFaPatch::updateMesh().
TypeName()
TypeName ("patch")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , faPatch , dictionary , (const word &name, const dictionary &dict, const label index, const faBoundaryMesh &bm, const word &patchType) , (name, dict, index, bm, patchType))
clone() [1/2]
virtual autoPtr< faPatch > clone (const faBoundaryMesh & bm) const inline virtual
Reimplemented in emptyFaPatch, symmetryFaPatch, and ignoreFaPatch.
Definition at line 209 of file faPatch.H.
References autoPtr< T >::New().
clone() [2/2]
virtual autoPtr< faPatch > clone (const faBoundaryMesh & bm, const labelUList & edgeLabels, const label index, const label nbrPolyPatchi) const inline virtual
Reimplemented in symmetryFaPatch, emptyFaPatch, and ignoreFaPatch.
Definition at line 216 of file faPatch.H.
References faPatch::edgeLabels(), patchIdentifier::index(), and autoPtr< T >::New().
New() [1/2]
Foam::autoPtr< Foam::faPatch > New (const word & name, const dictionary & dict, const label index, const faBoundaryMesh & bm) static
Definition at line 27 of file faPatchNew.C.
References dict, patchIdentifier::index(), patchIdentifier::name(), and faPatch::New().
Referenced by faPatch::New(), and faMeshTools::newMesh().
New() [2/2]
Foam::autoPtr< Foam::faPatch > New (const word & patchType, const word & name, const dictionary & dict, const label index, const faBoundaryMesh & bm) static
Definition at line 42 of file faPatchNew.C.
References DebugInFunction, dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, and Foam::name().
constraintType()
bool constraintType (const word & patchType) static
Definition at line 46 of file faPatch.C.
References polyPatch::constraintType().
Referenced by faPatch::faPatch(), and faPatch::faPatch().
constraintTypes()
Foam::wordList constraintTypes () static
Definition at line 55 of file faPatch.C.
References forAllConstIters, PtrList< T >::resize(), and UPtrList< T >::size().
edgeLabels()
const labelList & edgeLabels () const inline noexcept
Definition at line 273 of file faPatch.H.
Referenced by symmetryFaPatch::clone(), faPatch::clone(), emptyFaPatch::clone(), and ignoreFaPatch::clone().
nPoints()
label nPoints () const inline
Definition at line 279 of file faPatch.H.
References faPatch::pointLabels(), and UPtrList< T >::size().
nEdges()
label nEdges () const inline noexcept
Definition at line 285 of file faPatch.H.
References UList< T >::size().
ngbPolyPatchIndex()
label ngbPolyPatchIndex () const inline noexcept
Definition at line 291 of file faPatch.H.
Referenced by symmetryFaPatch::symmetryFaPatch(), and wedgeFaPatch::wedgeFaPatch().
boundaryMesh()
const Foam::faBoundaryMesh & boundaryMesh () const noexcept
Definition at line 184 of file faPatch.C.
Referenced by faPatch::lookupPatchField().
coupled()
virtual bool coupled () const inline virtual
Reimplemented in coupledFaPatch, and processorFaPatch.
Definition at line 300 of file faPatch.H.
offset()
Foam::label offset () const
Definition at line 190 of file faPatch.C.
References Foam::max(), and mesh.
Referenced by faPatch::boundarySlice().
start()
Foam::label start () const
Definition at line 201 of file faPatch.C.
References boundaryMesh::mesh().
Referenced by faPatch::patchSlice(), and faPatch::whichEdge().
size()
virtual label size () const inline virtual
Reimplemented in emptyFaPatch.
Definition at line 313 of file faPatch.H.
References UList< T >::size().
Referenced by faPatch::boundarySlice(), processorFaPatch::interfaceSize(), faPatch::patchInternalField(), faPatch::patchSlice(), faPatchMapper::size(), and emptyFaPatchField< Type >::updateCoeffs().
whichEdge()
label whichEdge (const label edgei) const inline
Definition at line 319 of file faPatch.H.
References faPatch::start().
patchSlice()
template<class T > const List< T >::subList patchSlice (const List< T > & values) const inline
Definition at line 327 of file faPatch.H.
References faPatch::size(), and faPatch::start().
boundarySlice()
template<class T > const List< T >::subList boundarySlice (const List< T > & values) const inline
Definition at line 336 of file faPatch.H.
References faPatch::offset(), and faPatch::size().
write()
void write (Ostream & os) const virtual
Reimplemented in processorFaPatch.
Definition at line 557 of file faPatch.C.
References os(), Foam::type(), patchIdentifier::write(), Ostream::writeEntry(), and UList< T >::writeEntry().
Referenced by processorFaPatch::write().
boundaryConnections()
Foam::List< Foam::labelPair > boundaryConnections () const
Definition at line 207 of file faPatch.C.
References boundaryMesh::mesh(), and Foam::output().
boundaryProcs()
Foam::labelList boundaryProcs () const
Definition at line 227 of file faPatch.C.
References UPtrList< T >::first(), boundaryMesh::mesh(), UPstream::myProcNo(), and UPstream::nProcs().
boundaryProcSizes()
Foam::List< Foam::labelPair > boundaryProcSizes () const
Definition at line 247 of file faPatch.C.
References UPtrList< T >::first(), boundaryMesh::mesh(), UPstream::myProcNo(), UPstream::nProcs(), Foam::output(), and UPtrList< T >::size().
pointLabels()
const Foam::labelList & pointLabels () const
Definition at line 277 of file faPatch.C.
Referenced by faPatch::nPoints().
pointEdges()
const Foam::labelListList & pointEdges () const
Definition at line 288 of file faPatch.C.
ngbPolyPatchFaceNormals()
Foam::tmp< Foam::vectorField > ngbPolyPatchFaceNormals () const
Definition at line 387 of file faPatch.C.
References boundaryMesh::mesh(), and tmp< T >::New().
ngbPolyPatchPointNormals()
Foam::tmp< Foam::vectorField > ngbPolyPatchPointNormals () const
Definition at line 398 of file faPatch.C.
References forAll, mesh, n, tmp< T >::New(), UPtrList< T >::size(), and Foam::Zero.
edgeFaces()
const Foam::labelUList & edgeFaces () const
Definition at line 433 of file faPatch.C.
References mesh.
Referenced by coupledFaPatch::faceCells().
edgeCentres()
const Foam::vectorField & edgeCentres () const
Definition at line 447 of file faPatch.C.
References boundaryMesh::mesh().
edgeLengths()
const Foam::vectorField & edgeLengths () const
Definition at line 453 of file faPatch.C.
References boundaryMesh::mesh().
magEdgeLengths()
const Foam::scalarField & magEdgeLengths () const
Definition at line 459 of file faPatch.C.
References boundaryMesh::mesh().
edgeNormals()
Foam::tmp< Foam::vectorField > edgeNormals () const
Definition at line 465 of file faPatch.C.
References tmp< T >::New().
edgeFaceCentres()
Foam::tmp< Foam::vectorField > edgeFaceCentres () const
Definition at line 475 of file faPatch.C.
References mesh.
delta()
Foam::tmp< Foam::vectorField > delta () const virtual
Reimplemented in cyclicFaPatch, processorFaPatch, and coupledFaPatch.
Definition at line 481 of file faPatch.C.
References e, edgeCentres(), and VectorSpace< Form, Cmpt, Ncmpts >::uniform().
makeWeights()
void makeWeights (scalarField & w) const virtual
Reimplemented in cyclicFaPatch, processorFaPatch, and coupledFaPatch.
Definition at line 527 of file faPatch.C.
weights()
const Foam::scalarField & weights () const
Definition at line 533 of file faPatch.C.
References boundaryMesh::mesh().
makeDeltaCoeffs()
void makeDeltaCoeffs (scalarField & dc) const virtual
Reimplemented in cyclicFaPatch, processorFaPatch, and coupledFaPatch.
Definition at line 505 of file faPatch.C.
References delta.
makeCorrectionVectors()
void makeCorrectionVectors (vectorField & k) const
Definition at line 511 of file faPatch.C.
References delta, k, and Foam::mag().
deltaCoeffs()
const Foam::scalarField & deltaCoeffs () const
Definition at line 521 of file faPatch.C.
References boundaryMesh::mesh().
resetEdges() [1/2]
void resetEdges (const labelUList & newEdges)
Definition at line 543 of file faPatch.C.
resetEdges() [2/2]
void resetEdges (labelList && newEdges)
Definition at line 550 of file faPatch.C.
patchInternalField() [1/4]
template<class Type > void patchInternalField (const UList< Type > & internalData, const labelUList & addressing, Field< Type > & pfld) const inline
Definition at line 27 of file faPatchTemplates.C.
References faPatch::size().
patchInternalField() [2/4]
template<class Type > void patchInternalField (const UList< Type > & internalData, Field< Type > & pfld) const
Definition at line 46 of file faPatchTemplates.C.
patchInternalField() [3/4]
template<class Type > tmp< Field< Type > > patchInternalField (const UList< Type > & internalData) const
patchField()
template<class GeometricField , class AnyType > const GeometricField::Patch & patchField (const GeometricField & gf) const
Definition at line 69 of file faPatchTemplates.C.
lookupPatchField()
template<class GeometricField , class AnyType > const GeometricField::Patch & lookupPatchField (const word & name, const GeometricField * = nullptr, const AnyType * = nullptr) const
Definition at line 27 of file faPatchFaMeshTemplates.C.
References faPatch::boundaryMesh(), patchIdentifier::index(), and patchIdentifier::name().
patchInternalField() [4/4]
template<class Type > Foam::tmp< Foam::Field< Type > > patchInternalField (const UList< Type > & internalData) const
Definition at line 57 of file faPatchTemplates.C.
References Foam::New().
Friends And Related Symbol Documentation
faBoundaryMesh
friend class faBoundaryMesh friend
Definition at line 112 of file faPatch.H.
operator<<
Ostream & operator<< (Ostream & , const faPatch &) friend
The documentation for this class was generated from the following files:
src/finiteArea/faMesh/faPatches/faPatch/faPatch.H
src/finiteArea/faMesh/faPatches/faPatch/faPatch.C
src/finiteArea/faMesh/faPatches/faPatch/faPatchFaMeshTemplates.C
src/finiteArea/faMesh/faPatches/faPatch/faPatchNew.C
src/finiteArea/faMesh/faPatches/faPatch/faPatchTemplates.C