OpenFOAM: valueAverageBase Class Reference
valueAverageBase Class Reference
Base class that computes the ensemble- or time-based singular-value average values, with optional windowing, from the output of function objects that generate non-field type values, e.g. Cd of forceCoeffs or momentum_x in momentum function objects.
#include <valueAverageBase.H>
Public Types
enum class windowType : uint8_t { NONE , APPROXIMATE , EXACT }
Public Member Functions
valueAverageBase (const word &name, const objectRegistry &obr, const dictionary &dict, stateFunctionObject &state, const bool writeToFile=true)
valueAverageBase (const valueAverageBase &)=delete
void operator= (const valueAverageBase &)=delete
virtual ~valueAverageBase ()=default
virtual bool read (const dictionary &dict)
virtual bool calculate (dictionary &dict)
Public Member Functions inherited from writeFile
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name="undefined", const bool writeToFile=true)
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name, const dictionary &dict, const bool writeToFile=true)
writeFile (const writeFile &wf)
virtual ~writeFile ()=default
virtual OFstream & file ()
virtual bool writeToFile () const
virtual bool canWriteToFile () const
virtual bool canResetFile () const
virtual bool canWriteHeader () const
virtual label charWidth () const
virtual void writeCommented (Ostream &os, const string &str) const
virtual void writeTabbed (Ostream &os, const string &str) const
virtual void writeHeader (Ostream &os, const string &str) const
virtual void writeCurrentTime (Ostream &os) const
virtual void writeBreak (Ostream &os) const
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
template<class Type >
void writeValue (Ostream &os, const Type &val) const
Static Public Attributes
static const Enum< windowType > windowTypeNames
Static Public Attributes inherited from writeFile
static label addChars = 8
Protected Member Functions
template<class Type , class Type2 = Type>
bool calc (const label fieldi, bool &converged, dictionary &dict)
virtual void writeFileHeader (Ostream &os) const
virtual void readState (dictionary &dict)
virtual void writeState (dictionary &dict)
virtual void resetState (dictionary &dict)
Protected Member Functions inherited from writeFile
void initStream (Ostream &os) const
fileName baseFileDir () const
fileName baseTimeDir () const
fileName filePath (const fileName &fName) const
virtual autoPtr< OFstream > newFile (const fileName &fName) const
virtual autoPtr< OFstream > newFileAtTime (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > newFileAtStartTime (const word &name) const
virtual void resetFile (const word &name)
Omanip< int > valueWidth (const label offset=0) const
void operator= (const writeFile &)=delete
virtual autoPtr< OFstream > createFile (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > createFile (const word &name) const
Protected Attributes
bool resetOnRestart_
windowType windowType_
stateFunctionObject & state_
word functionObjectName_
wordList fieldNames_
scalar tolerance_
scalar window_
List< scalar > totalTime_
Protected Attributes inherited from writeFile
const objectRegistry & fileObr_
const fileName prefix_
word fileName_
autoPtr< OFstream > filePtr_
label writePrecision_
bool writeToFile_
bool updateHeader_
bool writtenHeader_
bool useUserTime_
scalar startTime_
Detailed Description
Base class that computes the ensemble- or time-based singular-value average values, with optional windowing, from the output of function objects that generate non-field type values, e.g. Cd of forceCoeffs or momentum_x in momentum function objects.
See also
Foam::functionObjects::writeFile
Source files
valueAverageBase.H
valueAverageBase.C
valueAverageBaseTemplates.C
Definition at line 58 of file valueAverageBase.H.
Member Enumeration Documentation
windowType
enum class windowType : uint8_t strong
Enumerator
NONE
"none"
APPROXIMATE
"approximate"
EXACT
"exact"
Definition at line 67 of file valueAverageBase.H.
Constructor & Destructor Documentation
valueAverageBase() [1/2]
valueAverageBase (const word & name, const objectRegistry & obr, const dictionary & dict, stateFunctionObject & state, const bool writeToFile = true)
Definition at line 112 of file valueAverageBase.C.
References dict, writeFile::file(), valueAverageBase::read(), and valueAverageBase::writeFileHeader().
valueAverageBase() [2/2]
valueAverageBase (const valueAverageBase &) delete
~valueAverageBase()
virtual ~valueAverageBase () virtual default
Member Function Documentation
calc()
template<class Type , class Type2 > bool calc (const label fieldi, bool & converged, dictionary & dict) protected
Definition at line 25 of file valueAverageBaseTemplates.C.
References valueAverageBase::APPROXIMATE, beta(), UPtrList< T >::cbegin(), delta, dict, valueAverageBase::EXACT, valueAverageBase::fieldNames_, writeFile::file(), UPtrList< T >::first(), valueAverageBase::functionObjectName_, stateFunctionObject::getObjectResult(), stateFunctionObject::getResult(), Foam::indent(), Log, Foam::nl, valueAverageBase::NONE, stateFunctionObject::objectResultType(), dictionary::readIfPresent(), dictionary::set(), stateFunctionObject::setResult(), UPtrList< T >::size(), valueAverageBase::state_, dictionary::subDict(), Foam::tab, timeFunctionObject::time(), valueAverageBase::tolerance_, valueAverageBase::totalTime_, valueAverageBase::window_, valueAverageBase::windowType_, and Foam::Zero.
writeFileHeader()
void writeFileHeader (Ostream & os) const protected virtual
Definition at line 41 of file valueAverageBase.C.
References Foam::endl(), valueAverageBase::fieldNames_, forAll, os(), writeFile::writeCommented(), writeFile::writeHeader(), and writeFile::writeTabbed().
Referenced by valueAverageBase::valueAverageBase().
readState()
void readState (dictionary & dict) protected virtual
Definition at line 53 of file valueAverageBase.C.
References dict, forAll, and PtrList< T >::set().
Referenced by averageCondition::averageCondition(), and valueAverage::valueAverage().
writeState()
void writeState (dictionary & dict) protected virtual
Definition at line 79 of file valueAverageBase.C.
References dict, and forAll.
Referenced by valueAverage::write(), and averageCondition::write().
resetState()
void resetState (dictionary & dict) protected virtual
Definition at line 100 of file valueAverageBase.C.
References dict, forAll, and PtrList< T >::set().
Referenced by averageCondition::reset().
operator=()
void operator= (const valueAverageBase &) delete
read()
bool read (const dictionary & dict) virtual
Reimplemented from writeFile.
Reimplemented in valueAverage.
Definition at line 140 of file valueAverageBase.C.
References dict, UPtrList< T >::get(), writeFile::read(), PtrList< T >::resize(), and Foam::Zero.
Referenced by valueAverage::read(), and valueAverageBase::valueAverageBase().
calculate()
bool calculate (dictionary & dict) virtual
Definition at line 172 of file valueAverageBase.C.
References PtrList< T >::append(), dict, Foam::endl(), forAll, Foam::indent(), Log, Foam::nl, UPtrList< T >::size(), Foam::tab, and WarningInFunction.
Referenced by averageCondition::apply(), and valueAverage::execute().
Member Data Documentation
windowTypeNames
const Foam::Enum< Foam::functionObjects::valueAverageBase::windowType > windowTypeNames static
Definition at line 75 of file valueAverageBase.H.
resetOnRestart_
bool resetOnRestart_ protected
Definition at line 90 of file valueAverageBase.H.
windowType_
windowType windowType_ protected
Definition at line 93 of file valueAverageBase.H.
Referenced by valueAverageBase::calc().
state_
stateFunctionObject& state_ protected
Definition at line 96 of file valueAverageBase.H.
Referenced by valueAverageBase::calc().
functionObjectName_
word functionObjectName_ protected
Definition at line 99 of file valueAverageBase.H.
Referenced by valueAverageBase::calc().
fieldNames_
wordList fieldNames_ protected
Definition at line 102 of file valueAverageBase.H.
Referenced by valueAverageBase::calc(), and valueAverageBase::writeFileHeader().
tolerance_
scalar tolerance_ protected
Definition at line 105 of file valueAverageBase.H.
Referenced by valueAverageBase::calc().
window_
scalar window_ protected
Definition at line 108 of file valueAverageBase.H.
Referenced by valueAverageBase::calc().
totalTime_
List<scalar> totalTime_ protected
Definition at line 111 of file valueAverageBase.H.
Referenced by valueAverageBase::calc().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/functionObjects/valueAverageBase/valueAverageBase.H
src/OpenFOAM/db/functionObjects/valueAverageBase/valueAverageBase.C
src/OpenFOAM/db/functionObjects/valueAverageBase/valueAverageBaseTemplates.C