OpenFOAM: sigWriteNow Class Reference
sigWriteNow Class Reference
Signal handler to write once and continue. The interrupt is defined by OptimisationSwitches::writeNowSignal.
#include <sigWriteNow.H>
Public Member Functions
sigWriteNow ()
sigWriteNow (Time &runTime, bool verbose=false)
~sigWriteNow ()
Static Public Member Functions
static bool active ()
static int signalNumber ()
static void set (bool verbose=false)
Friends
class addwriteNowSignalToOpt
Detailed Description
Signal handler to write once and continue. The interrupt is defined by OptimisationSwitches::writeNowSignal.
Source files
sigWriteNow.H
sigWriteNow.C
Definition at line 49 of file sigWriteNow.H.
Constructor & Destructor Documentation
sigWriteNow() [1/2]
sigWriteNow ()
Definition at line 99 of file sigWriteNow.C.
sigWriteNow() [2/2]
sigWriteNow (Time & runTime, bool verbose = false)
Definition at line 103 of file sigWriteNow.C.
References runTime, and runTimePtr_.
~sigWriteNow()
~sigWriteNow ()
Definition at line 112 of file sigWriteNow.C.
References Foam::resetHandler().
Member Function Documentation
active()
bool active () static
Definition at line 125 of file sigWriteNow.C.
signalNumber()
int signalNumber () static
Definition at line 131 of file sigWriteNow.C.
Referenced by sigStopAtWriteNow::set().
set()
void set (bool verbose = false) static
Definition at line 137 of file sigWriteNow.C.
References Foam::Info, Foam::nl, and Foam::setHandler().
Referenced by addwriteNowSignalToOpt::readData().
Friends And Related Symbol Documentation
addwriteNowSignalToOpt
friend class addwriteNowSignalToOpt friend
Definition at line 66 of file sigWriteNow.H.
The documentation for this class was generated from the following files:
src/OSspecific/POSIX/signals/sigWriteNow.H
src/OSspecific/POSIX/signals/sigWriteNow.C