OpenFOAM: OCountStreamAllocator Class Reference
OCountStreamAllocator Class Reference
#include <OCountStream.H>
Public Member Functions
std::streamsize size () const
void rewind ()
Protected Types
typedef std::ostream stream_type
Protected Member Functions
OCountStreamAllocator (std::streamsize precount=0)
void printBufInfo (Ostream &os) const
Protected Attributes
countstreambuf buf_
stream_type stream_
Detailed Description
Definition at line 191 of file OCountStream.H.
Member Typedef Documentation
stream_type
typedef std::ostream stream_type protected
Definition at line 197 of file OCountStream.H.
Constructor & Destructor Documentation
OCountStreamAllocator()
OCountStreamAllocator (std::streamsize precount = 0) inline protected
Definition at line 209 of file OCountStream.H.
Member Function Documentation
printBufInfo()
void printBufInfo (Ostream & os) const inline protected
Definition at line 218 of file OCountStream.H.
References OCountStreamAllocator::buf_, os(), and countstreambuf::printBufInfo().
size()
std::streamsize size () const inline
Definition at line 228 of file OCountStream.H.
References OCountStreamAllocator::buf_, and countstreambuf::tellp().
rewind()
void rewind () inline
Definition at line 234 of file OCountStream.H.
References OCountStreamAllocator::buf_, and OCountStreamAllocator::stream_.
Referenced by OCountStream::rewind().
Member Data Documentation
buf_
countstreambuf buf_ protected
Definition at line 200 of file OCountStream.H.
Referenced by OCountStreamAllocator::printBufInfo(), OCountStreamAllocator::rewind(), and OCountStreamAllocator::size().
stream_
stream_type stream_ protected
Definition at line 203 of file OCountStream.H.
Referenced by OCountStreamAllocator::rewind().
The documentation for this class was generated from the following file:
src/OpenFOAM/db/IOstreams/memory/OCountStream.H