OpenFOAM: solidReaction< ReactionThermo > Class Template Reference
solidReaction< ReactionThermo > Class Template Reference
Read solid reactions of the type S1 = S2 + G1.
#include <solidReaction.H>
Public Member Functions
TypeName ("SolidReaction")
solidReaction (const Reaction< ReactionThermo > &reaction, const speciesTable &pyrolisisGases, const List< specieCoeffs > &glhs, const List< specieCoeffs > &grhs)
solidReaction (const solidReaction< ReactionThermo > &, const speciesTable &pyrolisisGases)
solidReaction (const speciesTable &species, const ReactionTable< ReactionThermo > &thermoDatabase, const dictionary &dict)
virtual autoPtr< Reaction< ReactionThermo > > clone () const
virtual autoPtr< Reaction< ReactionThermo > > clone (const speciesTable &species) const
virtual ~solidReaction ()=default
virtual const List< specieCoeffs > & grhs () const
virtual const List< specieCoeffs > & glhs () const
virtual const speciesTable & gasSpecies () const
virtual void write (Ostream &os) const
Public Member Functions inherited from Reaction< ReactionThermo >
TypeName ("Reaction")
declareRunTimeSelectionTable (autoPtr, Reaction, dictionary,(const speciesTable &species, const ReactionTable< ReactionThermo > &thermoDatabase, const dictionary &dict),(species, thermoDatabase, dict))
Reaction (const speciesTable &species, const List< specieCoeffs > &lhs, const List< specieCoeffs > &rhs, const ReactionTable< ReactionThermo > &thermoDatabase, bool initReactionThermo=true)
Reaction (const Reaction< ReactionThermo > &, const speciesTable &species)
Reaction (const speciesTable &species, const ReactionTable< ReactionThermo > &thermoDatabase, const dictionary &dict, bool initReactionThermo=true, bool failUnknownSpecie=true)
virtual ~Reaction ()=default
const word & name () const noexcept
const speciesTable & species () const noexcept
const List< specieCoeffs > & lhs () const noexcept
const List< specieCoeffs > & rhs () const noexcept
void setLRhs (Istream &, const speciesTable &, List< specieCoeffs > &lhs, List< specieCoeffs > &rhs, bool failUnknownSpecie=true)
virtual scalar kf (const scalar p, const scalar T, const scalarField &c) const
virtual scalar kr (const scalar kfwd, const scalar p, const scalar T, const scalarField &c) const
virtual scalar kr (const scalar p, const scalar T, const scalarField &c) const
Friends
Ostream & operator<< (Ostream &, const solidReaction< ReactionThermo > &)
Additional Inherited Members
Static Public Member Functions inherited from Reaction< ReactionThermo >
static autoPtr< Reaction< ReactionThermo > > New (const speciesTable &species, const ReactionTable< ReactionThermo > &thermoDatabase, const dictionary &dict)
Static Public Attributes inherited from Reaction< ReactionThermo >
static label nUnNamedReactions = 0
Protected Member Functions inherited from Reaction< ReactionThermo >
void reactionStrLeft (OStringStream &reaction) const
void reactionStrRight (OStringStream &reaction) const
Static Protected Member Functions inherited from Reaction< ReactionThermo >
static void reactionStr (OStringStream &reaction, const speciesTable &species, const List< specieCoeffs > &reactCoeffs)
Detailed Description
template<class ReactionThermo>
class Foam::solidReaction< ReactionThermo >
Read solid reactions of the type S1 = S2 + G1.
Source files
solidReaction.H
solidReactionI.H
solidReaction.C
Definition at line 57 of file solidReaction.H.
Constructor & Destructor Documentation
solidReaction() [1/3]
template<class ReactionThermo > solidReaction (const Reaction< ReactionThermo > & reaction, const speciesTable & pyrolisisGases, const List< specieCoeffs > & glhs, const List< specieCoeffs > & grhs)
Definition at line 28 of file solidReaction.C.
solidReaction() [2/3]
template<class ReactionThermo > solidReaction (const solidReaction< ReactionThermo > & r, const speciesTable & pyrolisisGases)
Definition at line 44 of file solidReaction.C.
solidReaction() [3/3]
template<class ReactionThermo > solidReaction (const speciesTable & species, const ReactionTable< ReactionThermo > & thermoDatabase, const dictionary & dict)
Definition at line 58 of file solidReaction.C.
References dict, Reaction< ReactionThermo >::setLRhs(), and Reaction< ReactionThermo >::species().
~solidReaction()
template<class ReactionThermo > virtual ~solidReaction () virtual default
Member Function Documentation
TypeName()
template<class ReactionThermo > TypeName ("SolidReaction")
clone() [1/2]
template<class ReactionThermo > virtual autoPtr< Reaction< ReactionThermo > > clone () const inline virtual
Reimplemented from Reaction< ReactionThermo >.
Definition at line 126 of file solidReaction.H.
clone() [2/2]
template<class ReactionThermo > virtual autoPtr< Reaction< ReactionThermo > > clone (const speciesTable & species) const inline virtual
Reimplemented from Reaction< ReactionThermo >.
Definition at line 135 of file solidReaction.H.
References Reaction< ReactionThermo >::species().
grhs()
template<class ReactionThermo > const Foam::List< typename Foam::Reaction< ReactionThermo >::specieCoeffs > & grhs () const virtual
Reimplemented from Reaction< ReactionThermo >.
Definition at line 118 of file solidReaction.C.
glhs()
template<class ReactionThermo > const Foam::List< typename Foam::solidReaction< ReactionThermo >::specieCoeffs > & glhs () const virtual
Reimplemented from Reaction< ReactionThermo >.
Definition at line 110 of file solidReaction.C.
gasSpecies()
template<class ReactionThermo > const Foam::speciesTable & gasSpecies () const virtual
Reimplemented from Reaction< ReactionThermo >.
Definition at line 125 of file solidReaction.C.
write()
template<class ReactionThermo > void write (Ostream & os) const virtual
Reimplemented from Reaction< ReactionThermo >.
Definition at line 133 of file solidReaction.C.
References os(), reaction, and Ostream::writeEntry().
Friends And Related Symbol Documentation
operator<<
template<class ReactionThermo > Ostream & operator<< (Ostream & os, const solidReaction< ReactionThermo > & r) friend
Definition at line 31 of file solidReactionI.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/solidSpecie/reaction/Reactions/solidReaction/solidReaction.H
src/thermophysicalModels/solidSpecie/reaction/Reactions/solidReaction/solidReaction.C