OpenFOAM: exprResultDelayed Class Reference
exprResultDelayed Class Reference
An exprResult with an additional delay before evaluation.
#include <exprResultDelayed.H>
Public Member Functions
TypeNameNoDebug ("exprResultDelayed")
exprResultDelayed ()
exprResultDelayed (const exprResultDelayed &)
exprResultDelayed (const dictionary &dict)
virtual autoPtr< exprResult > clone () const
virtual ~exprResultDelayed ()=default
const word & name () const
const expressions::exprString & startupValueExpression () const
bool updateReadValue (const scalar &timeVal)
void setReadValue (const exprResult &val)
void storeValue (const scalar &timeVal)
void writeDict (Ostream &os) const
void operator= (const exprResultDelayed &rhs)
void operator= (const exprResult &rhs)
void operator= (exprResult &&rhs)
Public Member Functions inherited from exprResult
TypeName ("exprResult")
declareRunTimeSelectionTable (autoPtr, exprResult, dictionary,(const dictionary &dict),(dict))
declareRunTimeSelectionTable (autoPtr, exprResult, empty,(),())
exprResult ()
exprResult (const exprResult &expr)
exprResult (exprResult &&expr)
exprResult (const dictionary &dict, const bool uniform=false, const bool needsValue=false)
exprResult (Istream &is)
template<class Type >
exprResult (const Field< Type > &fld)
template<class Type >
exprResult (Field< Type > &&fld)
template<class Type >
exprResult (autoPtr< Type > &&obj)
template<class Type >
exprResult (const dimensioned< Type > &dt)
exprResult (const bool &val)
Construct from single value of bool.
exprResult (const scalar &val)
Construct from single value of scalar.
exprResult (const vector &val)
Construct from single value of vector.
exprResult (const tensor &val)
Construct from single value of tensor.
exprResult (const symmTensor &val)
Construct from single value of symmTensor.
exprResult (const sphericalTensor &val)
Construct from single value of sphericalTensor.
virtual ~exprResult ()
bool hasValue () const
const word & valueType () const noexcept
bool isPointData (const bool wantPointData=true) const
bool isUniform () const
template<class Type >
bool isType () const
template<class Type >
Type getValue () const
bool is_bool () const
label size () const
const void * dataAddress () const
void clear ()
void noReset () noexcept
void allowReset () noexcept
void testIfSingleValue (const bool parRun=Pstream::parRun())
template<class Type >
void setResult (Field< Type > *, bool wantPointData=false)
template<class Type >
void setResult (const Field< Type > &, bool wantPointData=false)
template<class Type >
void setResult (Field< Type > &&, bool wantPointData=false)
template<class Type >
void setResult (const Type &val, const label size)
template<class Type >
void setSingleValue (const Type &val)
template<class Type >
const Field< Type > & cref () const
template<class Type >
Field< Type > & ref ()
template<class Type >
Field< Type > & constCast () const
template<class Type >
tmp< Field< Type > > getResult (bool cacheCopy=false)
exprResult getUniform (const label size, const bool noWarn, const bool parRun=Pstream::parRun()) const
template<template< class > class BinaryOp, class Type >
Type getReduced (const BinaryOp< Type > &bop, const Type &initial=pTraits< Type >::zero)
void writeEntry (const word &keyword, Ostream &os) const
void writeDict (Ostream &os, const bool subDict=true) const
void writeField (Ostream &os, const word &keyword="") const
void writeValue (Ostream &os) const
exprResult & operator*= (const scalar &b)
exprResult & operator+= (const exprResult &b)
template<class Type >
Foam::tmp< Foam::Field< Type > > getResult (bool cacheCopy)
template<class Type >
const Foam::Field< Type > & cref () const
template<class Type >
Foam::Field< Type > & ref ()
template<class Type >
Foam::Field< Type > & constCast () const
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Protected Member Functions
expressions::exprResult & target ()
Protected Member Functions inherited from exprResult
virtual void resetImpl ()
bool reset (bool force=false)
void needsReset (bool val)
Additional Inherited Members
Static Public Member Functions inherited from exprResult
static autoPtr< exprResult > New (const dictionary &dict)
static autoPtr< exprResult > New (Istream &is)
Static Public Attributes inherited from exprResult
static const exprResult null
Detailed Description
An exprResult with an additional delay before evaluation.
Dictionary parameters
Property Description Required Default
name The result name yes
delay The delay before starting yes
storeInterval The storage interval (time) yes
startupValue The initial startup value yes
value The expression result (dictionary) no
storedValues The list of stored values yes
Source files
exprResultDelayed.H
exprResultDelayed.C
Definition at line 97 of file exprResultDelayed.H.
Constructor & Destructor Documentation
exprResultDelayed() [1/3]
exprResultDelayed ()
Definition at line 58 of file exprResultDelayed.C.
Referenced by exprResultDelayed::clone().
exprResultDelayed() [2/3]
exprResultDelayed (const exprResultDelayed & rhs)
Definition at line 69 of file exprResultDelayed.C.
exprResultDelayed() [3/3]
exprResultDelayed (const dictionary & dict)
Definition at line 84 of file exprResultDelayed.C.
References dict, and keyType::LITERAL.
~exprResultDelayed()
virtual ~exprResultDelayed () virtual default
Member Function Documentation
target()
expressions::exprResult & target () inline protected virtual
Reimplemented from exprResult.
Definition at line 133 of file exprResultDelayed.H.
TypeNameNoDebug()
TypeNameNoDebug ("exprResultDelayed")
clone()
virtual autoPtr< exprResult > clone () const inline virtual
Reimplemented from exprResult.
Definition at line 154 of file exprResultDelayed.H.
References exprResultDelayed::exprResultDelayed().
name()
const word & name () const inline
Definition at line 170 of file exprResultDelayed.H.
startupValueExpression()
const expressions::exprString & startupValueExpression () const inline
Definition at line 176 of file exprResultDelayed.H.
updateReadValue()
bool updateReadValue (const scalar & timeVal)
Definition at line 106 of file exprResultDelayed.C.
References UPtrList< T >::cbegin(), Foam::endl(), Foam::exit(), f(), Foam::FatalError, FatalErrorInFunction, UPtrList< T >::first(), Foam::name(), and Foam::nl.
setReadValue()
void setReadValue (const exprResult & val)
Definition at line 165 of file exprResultDelayed.C.
References exprResult::operator=().
storeValue()
void storeValue (const scalar & timeVal)
Definition at line 174 of file exprResultDelayed.C.
References append(), UPtrList< T >::back(), UPtrList< T >::empty(), UPtrList< T >::front(), UPtrList< T >::last(), and PtrList< T >::push_back().
writeDict()
void writeDict (Ostream & os) const
Definition at line 232 of file exprResultDelayed.C.
References os().
operator=() [1/3]
void operator= (const exprResultDelayed & rhs)
Definition at line 258 of file exprResultDelayed.C.
References exprResult::operator=().
operator=() [2/3]
void operator= (const exprResult & rhs) virtual
Reimplemented from exprResult.
Definition at line 279 of file exprResultDelayed.C.
operator=() [3/3]
void operator= (exprResult && rhs) virtual
Reimplemented from exprResult.
Definition at line 288 of file exprResultDelayed.C.
The documentation for this class was generated from the following files:
src/OpenFOAM/expressions/exprResult/exprResultDelayed.H
src/OpenFOAM/expressions/exprResult/exprResultDelayed.C