OpenFOAM: wallPoint Class Reference
wallPoint Class Reference
Holds information regarding nearest wall point. Used in wall distance calculation.
#include <wallPoint.H>
Public Member Functions
wallPoint ()
wallPoint (const point &origin, const scalar distSqr)
const point & origin () const
point & origin ()
scalar distSqr () const
scalar & distSqr ()
template<class TrackingData >
bool valid (TrackingData &td) const
template<class TrackingData >
bool sameGeometry (const polyMesh &, const wallPoint &, const scalar, TrackingData &td) const
template<class TrackingData >
void leaveDomain (const polyMesh &, const polyPatch &, const label patchFacei, const point &faceCentre, TrackingData &td)
template<class TrackingData >
void enterDomain (const polyMesh &, const polyPatch &, const label patchFacei, const point &faceCentre, TrackingData &td)
template<class TrackingData >
void transform (const polyMesh &, const tensor &, TrackingData &td)
template<class TrackingData >
bool updateCell (const polyMesh &, const label thisCelli, const label neighbourFacei, const wallPoint &neighbourInfo, const scalar tol, TrackingData &td)
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFacei, const label neighbourCelli, const wallPoint &neighbourInfo, const scalar tol, TrackingData &td)
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFacei, const wallPoint &neighbourInfo, const scalar tol, TrackingData &td)
template<class TrackingData >
bool equal (const wallPoint &, TrackingData &td) const
bool operator== (const wallPoint &) const
bool operator!= (const wallPoint &) const
Friends
Ostream & operator<< (Ostream &, const wallPoint &)
Istream & operator>> (Istream &, wallPoint &)
Detailed Description
Holds information regarding nearest wall point. Used in wall distance calculation.
Source files
wallPoint.H
wallPointI.H
wallPoint.C
Definition at line 61 of file wallPoint.H.
Constructor & Destructor Documentation
wallPoint() [1/2]
wallPoint () inline
Definition at line 81 of file wallPointI.H.
wallPoint() [2/2]
wallPoint (const point & origin, const scalar distSqr) inline
Definition at line 88 of file wallPointI.H.
Member Function Documentation
origin() [1/2]
const point & origin () const inline
Definition at line 102 of file wallPoint.H.
origin() [2/2]
point & origin () inline
Definition at line 106 of file wallPoint.H.
distSqr() [1/2]
scalar distSqr () const inline
Definition at line 111 of file wallPoint.H.
distSqr() [2/2]
scalar & distSqr () inline
Definition at line 115 of file wallPoint.H.
valid()
template<class TrackingData > bool valid (TrackingData & td) const inline
Definition at line 98 of file wallPointI.H.
sameGeometry()
template<class TrackingData > bool sameGeometry (const polyMesh & , const wallPoint & w2, const scalar tol, TrackingData & td) const inline
Definition at line 106 of file wallPointI.H.
References Foam::diff(), Foam::mag(), and w2.
leaveDomain()
template<class TrackingData > void leaveDomain (const polyMesh & , const polyPatch & , const label patchFacei, const point & faceCentre, TrackingData & td) inline
Definition at line 135 of file wallPointI.H.
Referenced by wallPointAddressing::leaveDomain().
enterDomain()
template<class TrackingData > void enterDomain (const polyMesh & , const polyPatch & , const label patchFacei, const point & faceCentre, TrackingData & td) inline
Definition at line 163 of file wallPointI.H.
transform()
template<class TrackingData > void transform (const polyMesh & , const tensor & rotTensor, TrackingData & td) inline
Definition at line 149 of file wallPointI.H.
References Foam::transform().
updateCell()
template<class TrackingData > bool updateCell (const polyMesh & mesh, const label thisCelli, const label neighbourFacei, const wallPoint & neighbourInfo, const scalar tol, TrackingData & td) inline
Definition at line 179 of file wallPointI.H.
References primitiveMesh::cellCentres(), mesh, and update().
updateFace() [1/2]
template<class TrackingData > bool updateFace (const polyMesh & mesh, const label thisFacei, const label neighbourCelli, const wallPoint & neighbourInfo, const scalar tol, TrackingData & td) inline
Definition at line 202 of file wallPointI.H.
References primitiveMesh::faceCentres(), mesh, and update().
updateFace() [2/2]
template<class TrackingData > bool updateFace (const polyMesh & mesh, const label thisFacei, const wallPoint & neighbourInfo, const scalar tol, TrackingData & td) inline
Definition at line 225 of file wallPointI.H.
References primitiveMesh::faceCentres(), mesh, and update().
equal()
template<class TrackingData > bool equal (const wallPoint & rhs, TrackingData & td) const inline
Definition at line 246 of file wallPointI.H.
References Foam::operator==().
operator==()
bool operator== (const wallPoint & rhs) const inline
Definition at line 258 of file wallPointI.H.
operator!=()
bool operator!= (const wallPoint & rhs) const inline
Definition at line 267 of file wallPointI.H.
Friends And Related Symbol Documentation
operator<<
Ostream & operator<< (Ostream & , const wallPoint &) friend
operator>>
Istream & operator>> (Istream & , wallPoint &) friend
The documentation for this class was generated from the following files:
src/meshTools/cellDist/wallPoint/wallPoint.H
src/meshTools/cellDist/wallPoint/wallPointI.H