OpenFOAM: faceAreaWeightAMI Class Reference
faceAreaWeightAMI Class Reference
Face area weighted Arbitrary Mesh Interface (AMI) method.
#include <faceAreaWeightAMI.H>
Public Member Functions
TypeName ("faceAreaWeightAMI")
faceAreaWeightAMI (const dictionary &dict, const bool reverseTarget=false)
faceAreaWeightAMI (const bool requireMatch, const bool reverseTarget=false, const scalar lowWeightCorrection=-1, const faceAreaIntersect::triangulationMode triMode=faceAreaIntersect::tmMesh, const bool restartUncoveredSourceFace=true)
faceAreaWeightAMI (const faceAreaWeightAMI &ami)
virtual autoPtr< AMIInterpolation > clone () const
virtual ~faceAreaWeightAMI ()=default
virtual bool calculate (const primitivePatch &srcPatch, const primitivePatch &tgtPatch, const autoPtr< searchableSurface > &surfPtr=nullptr)
virtual void write (Ostream &os) const
Public Member Functions inherited from advancingFrontAMI
TypeName ("advancingFrontAMI")
advancingFrontAMI (const dictionary &dict, const bool reverseTarget)
advancingFrontAMI (const bool requireMatch=true, const bool reverseTarget=false, const scalar lowWeightCorrection=-1, const faceAreaIntersect::triangulationMode triMode=faceAreaIntersect::tmMesh)
advancingFrontAMI (const advancingFrontAMI &ami)
virtual ~advancingFrontAMI ()=default
const primitivePatch & srcPatch () const
const primitivePatch & tgtPatch () const
const labelList & srcNonOverlap () const
Public Member Functions inherited from AMIInterpolation
TypeName ("AMIInterpolation")
declareRunTimeSelectionTable (autoPtr, AMIInterpolation, dict,(const dictionary &dict, const bool reverseTarget),(dict, reverseTarget))
declareRunTimeSelectionTable (autoPtr, AMIInterpolation, component,(const bool requireMatch, const bool reverseTarget, const scalar lowWeightCorrection),(requireMatch, reverseTarget, lowWeightCorrection))
AMIInterpolation (const dictionary &dict, const bool reverseTarget=false)
AMIInterpolation (const bool requireMatch=true, const bool reverseTarget=false, const scalar lowWeightCorrection=-1)
AMIInterpolation (const AMIInterpolation &fineAMI, const labelList &sourceRestrictAddressing, const labelList &neighbourRestrictAddressing)
AMIInterpolation (const AMIInterpolation &ami)
virtual ~AMIInterpolation ()=default
bool upToDate () const noexcept
bool upToDate (bool flag) noexcept
bool upToDate () noexcept
bool distributed () const
bool requireMatch () const
bool setRequireMatch (const bool flag)
bool mustMatchFaces () const
bool reverseTarget () const
scalar lowWeightCorrection () const
bool applyLowWeightCorrection () const
label singlePatchProc () const
const List< scalar > & srcMagSf () const
List< scalar > & srcMagSf ()
const labelListList & srcAddress () const
labelListList & srcAddress ()
const scalarListList & srcWeights () const
scalarListList & srcWeights ()
const scalarField & srcWeightsSum () const
scalarField & srcWeightsSum ()
const pointListList & srcCentroids () const
pointListList & srcCentroids ()
const mapDistribute & srcMap () const
const List< scalar > & tgtMagSf () const
List< scalar > & tgtMagSf ()
const labelListList & tgtAddress () const
labelListList & tgtAddress ()
const scalarListList & tgtWeights () const
scalarListList & tgtWeights ()
const scalarField & tgtWeightsSum () const
scalarField & tgtWeightsSum ()
const mapDistribute & tgtMap () const
void reset (autoPtr< mapDistribute > &&srcToTgtMap, autoPtr< mapDistribute > &&tgtToSrcMap, labelListList &&srcAddress, scalarListList &&srcWeights, labelListList &&tgtAddress, scalarListList &&tgtWeights)
void append (const primitivePatch &srcPatch, const primitivePatch &tgtPatch)
void normaliseWeights (const bool conformal, const bool output)
template<class Type , class CombineOp >
void interpolateToSource (const UList< Type > &fld, const CombineOp &cop, List< Type > &result, const UList< Type > &defaultValues=UList< Type >::null()) const
template<class Type , class CombineOp >
void interpolateToTarget (const UList< Type > &fld, const CombineOp &cop, List< Type > &result, const UList< Type > &defaultValues=UList< Type >::null()) const
template<class Type , class CombineOp >
tmp< Field< Type > > interpolateToSource (const Field< Type > &fld, const CombineOp &cop, const UList< Type > &defaultValues=UList< Type >::null()) const
template<class Type , class CombineOp >
tmp< Field< Type > > interpolateToSource (const tmp< Field< Type > > &tFld, const CombineOp &cop, const UList< Type > &defaultValues=UList< Type >::null()) const
template<class Type , class CombineOp >
tmp< Field< Type > > interpolateToTarget (const Field< Type > &fld, const CombineOp &cop, const UList< Type > &defaultValues=UList< Type >::null()) const
template<class Type , class CombineOp >
tmp< Field< Type > > interpolateToTarget (const tmp< Field< Type > > &tFld, const CombineOp &cop, const UList< Type > &defaultValues=UList< Type >::null()) const
template<class Type >
tmp< Field< Type > > interpolateToSource (const Field< Type > &fld, const UList< Type > &defaultValues=UList< Type >::null()) const
template<class Type >
tmp< Field< Type > > interpolateToSource (const tmp< Field< Type > > &tFld, const UList< Type > &defaultValues=UList< Type >::null()) const
template<class Type >
tmp< Field< Type > > interpolateToTarget (const Field< Type > &fld, const UList< Type > &defaultValues=UList< Type >::null()) const
template<class Type >
tmp< Field< Type > > interpolateToTarget (const tmp< Field< Type > > &tFld, const UList< Type > &defaultValues=UList< Type >::null()) const
label srcPointFace (const primitivePatch &srcPatch, const primitivePatch &tgtPatch, const vector &n, const label tgtFacei, point &tgtPoint) const
label tgtPointFace (const primitivePatch &srcPatch, const primitivePatch &tgtPatch, const vector &n, const label srcFacei, point &srcPoint) const
bool checkSymmetricWeights (const bool log) const
void writeFaceConnectivity (const primitivePatch &srcPatch, const primitivePatch &tgtPatch, const labelListList &srcAddress) const
template<class Type , class CombineOp >
Foam::tmp< Foam::Field< Type > > interpolateToSource (const Field< Type > &fld, const CombineOp &cop, const UList< Type > &defaultValues) const
template<class Type , class CombineOp >
Foam::tmp< Foam::Field< Type > > interpolateToSource (const tmp< Field< Type > > &tFld, const CombineOp &cop, const UList< Type > &defaultValues) const
template<class Type , class CombineOp >
Foam::tmp< Foam::Field< Type > > interpolateToTarget (const Field< Type > &fld, const CombineOp &cop, const UList< Type > &defaultValues) const
template<class Type , class CombineOp >
Foam::tmp< Foam::Field< Type > > interpolateToTarget (const tmp< Field< Type > > &tFld, const CombineOp &cop, const UList< Type > &defaultValues) const
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolateToSource (const Field< Type > &fld, const UList< Type > &defaultValues) const
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolateToSource (const tmp< Field< Type > > &tFld, const UList< Type > &defaultValues) const
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolateToTarget (const Field< Type > &fld, const UList< Type > &defaultValues) const
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolateToTarget (const tmp< Field< Type > > &tFld, const UList< Type > &defaultValues) const
Protected Member Functions
void operator= (const faceAreaWeightAMI &)=delete
virtual void calcAddressing (List< DynamicList< label > > &srcAddress, List< DynamicList< scalar > > &srcWeights, List< DynamicList< point > > &srcCentroids, List< DynamicList< label > > &tgtAddress, List< DynamicList< scalar > > &tgtWeights, label srcFacei, label tgtFacei)
virtual bool processSourceFace (const label srcFacei, const label tgtStartFacei, DynamicList< label > &nbrFaces, DynamicList< label > &visitedFaces, List< DynamicList< label > > &srcAddr, List< DynamicList< scalar > > &srcWght, List< DynamicList< point > > &srcCtr, List< DynamicList< label > > &tgtAddr, List< DynamicList< scalar > > &tgtWght)
virtual void restartUncoveredSourceFace (List< DynamicList< label > > &srcAddr, List< DynamicList< scalar > > &srcWght, List< DynamicList< point > > &srcCtr, List< DynamicList< label > > &tgtAddr, List< DynamicList< scalar > > &tgtWght)
virtual bool setNextFaces (label &startSeedi, label &srcFacei, label &tgtFacei, const bitSet &mapFlag, labelList &seedFaces, const DynamicList< label > &visitedFaces, const bool errorOnNotFound=true) const
virtual void calcInterArea (const label srcFacei, const label tgtFacei, scalar &area, vector &centroid) const
virtual bool overlaps (const label srcFacei, const label tgtFacei, const scalar threshold) const
Protected Member Functions inherited from advancingFrontAMI
void createExtendedTgtPatch ()
void checkPatches () const
bool isCandidate (const label srcFacei, const label tgtFacei) const
bool initialiseWalk (label &srcFacei, label &tgtFacei)
void writeIntersectionOBJ (const scalar area, const face &f1, const face &f2, const pointField &f1Points, const pointField &f2Points) const
label findTargetFace (const label srcFacei, const UList< label > &excludeFaces=UList< label >::null(), const label srcFacePti=-1) const
void appendNbrFaces (const label facei, const primitivePatch &patch, const DynamicList< label > &visitedFaces, DynamicList< label > &faceIDs) const
void triangulatePatch (const primitivePatch &patch, List< DynamicList< face > > &tris, List< scalar > &magSf) const
virtual void nonConformalCorrection ()
Protected Member Functions inherited from AMIInterpolation
void operator= (const AMIInterpolation &)=delete
autoPtr< indexedOctree< treeType > > createTree (const primitivePatch &patch) const
label calcDistribution (const primitivePatch &srcPatch, const primitivePatch &tgtPatch) const
void projectPointsToSurface (const searchableSurface &surf, pointField &pts) const
const primitivePatch & srcPatch0 () const
const primitivePatch & tgtPatch0 () const
Additional Inherited Members
Public Types inherited from advancingFrontAMI
enum class areaNormalisationMode { project , mag }
Static Public Member Functions inherited from AMIInterpolation
static autoPtr< AMIInterpolation > New (const word &modelName, const dictionary &dict, const bool reverseTarget=false)
static autoPtr< AMIInterpolation > New (const word &modelName, const bool requireMatch=true, const bool reverseTarget=false, const scalar lowWeightCorrection=-1)
Static Public Attributes inherited from advancingFrontAMI
static const Enum< areaNormalisationMode > areaNormalisationModeNames_
Static Public Attributes inherited from AMIInterpolation
static bool cacheIntersections_ = false
Protected Types inherited from AMIInterpolation
typedef treeDataPrimitivePatch< primitivePatch > treeType
Static Protected Member Functions inherited from AMIInterpolation
static void normaliseWeights (const scalarList &patchAreas, const word &patchName, const labelListList &addr, scalarListList &wght, scalarField &wghtSum, const bool conformal, const bool output, const scalar lowWeightTol)
static void agglomerate (const autoPtr< mapDistribute > &targetMap, const scalarList &fineSrcMagSf, const labelListList &fineSrcAddress, const scalarListList &fineSrcWeights, const labelList &sourceRestrictAddressing, const labelList &targetRestrictAddressing, scalarList &srcMagSf, labelListList &srcAddress, scalarListList &srcWeights, scalarField &srcWeightsSum, autoPtr< mapDistribute > &tgtMap)
Protected Attributes inherited from advancingFrontAMI
const scalar maxDistance2_
const scalar minCosAngle_
List< DynamicList< face > > srcTris_
List< DynamicList< face > > tgtTris_
autoPtr< primitivePatch > extendedTgtPatchPtr_
faceList extendedTgtFaces_
pointField extendedTgtPoints_
labelList extendedTgtFaceIDs_
autoPtr< mapDistribute > extendedTgtMapPtr_
labelList srcNonOverlap_
autoPtr< indexedOctree< treeType > > treePtr_
const faceAreaIntersect::triangulationMode triMode_
areaNormalisationMode areaNormalisationMode_
Protected Attributes inherited from AMIInterpolation
bool requireMatch_
const bool reverseTarget_
const scalar lowWeightCorrection_
label singlePatchProc_
scalarList srcMagSf_
labelListList srcAddress_
scalarListList srcWeights_
scalarField srcWeightsSum_
pointListList srcCentroids_
pointField srcPatchPts_
refPtr< primitivePatch > tsrcPatch0_
autoPtr< mapDistribute > srcMapPtr_
scalarList tgtMagSf_
labelListList tgtAddress_
scalarListList tgtWeights_
scalarField tgtWeightsSum_
pointListList tgtCentroids_
pointField tgtPatchPts_
refPtr< primitivePatch > ttgtPatch0_
autoPtr< mapDistribute > tgtMapPtr_
bool upToDate_
Detailed Description
Face area weighted Arbitrary Mesh Interface (AMI) method.
Searching is performed using an advancing front.
Source files
faceAreaWeightAMI.H
faceAreaWeightAMI.C
Definition at line 49 of file faceAreaWeightAMI.H.
Constructor & Destructor Documentation
faceAreaWeightAMI() [1/3]
faceAreaWeightAMI (const dictionary & dict, const bool reverseTarget = false)
Definition at line 583 of file faceAreaWeightAMI.C.
faceAreaWeightAMI() [2/3]
faceAreaWeightAMI (const bool requireMatch, const bool reverseTarget = false, const scalar lowWeightCorrection = -1, const faceAreaIntersect::triangulationMode triMode = faceAreaIntersect::tmMesh, const bool restartUncoveredSourceFace = true)
Definition at line 597 of file faceAreaWeightAMI.C.
faceAreaWeightAMI() [3/3]
faceAreaWeightAMI (const faceAreaWeightAMI & ami)
Definition at line 617 of file faceAreaWeightAMI.C.
~faceAreaWeightAMI()
virtual ~faceAreaWeightAMI () virtual default
Member Function Documentation
operator=()
void operator= (const faceAreaWeightAMI &) protected delete
calcAddressing()
void calcAddressing (List< DynamicList< label > > & srcAddress, List< DynamicList< scalar > > & srcWeights, List< DynamicList< point > > & srcCentroids, List< DynamicList< label > > & tgtAddress, List< DynamicList< scalar > > & tgtWeights, label srcFacei, label tgtFacei) protected virtual
Definition at line 88 of file faceAreaWeightAMI.C.
References addProfiling, PtrList< T >::append(), PtrList< T >::clear(), AMIInterpolation::mustMatchFaces(), faceAreaWeightAMI::processSourceFace(), faceAreaWeightAMI::setNextFaces(), UPtrList< T >::size(), advancingFrontAMI::srcNonOverlap_, and List< T >::transfer().
processSourceFace()
bool processSourceFace (const label srcFacei, const label tgtStartFacei, DynamicList< label > & nbrFaces, DynamicList< label > & visitedFaces, List< DynamicList< label > > & srcAddr, List< DynamicList< scalar > > & srcWght, List< DynamicList< point > > & srcCtr, List< DynamicList< label > > & tgtAddr, List< DynamicList< scalar > > & tgtWght) protected virtual
Definition at line 174 of file faceAreaWeightAMI.C.
References addProfiling, PtrList< T >::append(), UPtrList< T >::back(), DebugVar, UPtrList< T >::empty(), Foam::max(), PtrList< T >::push_back(), UPtrList< T >::size(), faceAreaIntersect::tolerance(), and Foam::Zero.
Referenced by faceAreaWeightAMI::calcAddressing().
restartUncoveredSourceFace()
void restartUncoveredSourceFace (List< DynamicList< label > > & srcAddr, List< DynamicList< scalar > > & srcWght, List< DynamicList< point > > & srcCtr, List< DynamicList< label > > & tgtAddr, List< DynamicList< scalar > > & tgtWght) protected virtual
Definition at line 507 of file faceAreaWeightAMI.C.
References addProfiling, PtrList< T >::clear(), Foam::endl(), f(), forAll, s(), Foam::sum(), and WarningInFunction.
setNextFaces()
bool setNextFaces (label & startSeedi, label & srcFacei, label & tgtFacei, const bitSet & mapFlag, labelList & seedFaces, const DynamicList< label > & visitedFaces, const bool errorOnNotFound = true) const protected virtual
Definition at line 247 of file faceAreaWeightAMI.C.
References Foam::abort(), addProfiling, UPtrList< T >::count(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, UPtrList< T >::find_next(), Foam::Pout, UPtrList< T >::test(), and faceAreaIntersect::tolerance().
Referenced by faceAreaWeightAMI::calcAddressing().
calcInterArea()
void calcInterArea (const label srcFacei, const label tgtFacei, scalar & area, vector & centroid) const protected virtual
Definition at line 366 of file faceAreaWeightAMI.C.
References addProfiling, AMIInterpolation::cacheIntersections_, Foam::endl(), Foam::mag(), n, and WarningInFunction.
overlaps()
bool overlaps (const label srcFacei, const label tgtFacei, const scalar threshold) const protected virtual
Definition at line 445 of file faceAreaWeightAMI.C.
References AMIInterpolation::cacheIntersections_, Foam::endl(), Foam::mag(), n, and WarningInFunction.
TypeName()
TypeName ("faceAreaWeightAMI")
clone()
virtual autoPtr< AMIInterpolation > clone () const inline virtual
Reimplemented from advancingFrontAMI.
Definition at line 171 of file faceAreaWeightAMI.H.
calculate()
bool calculate (const primitivePatch & srcPatch, const primitivePatch & tgtPatch, const autoPtr< searchableSurface > & surfPtr = nullptr) virtual
Reimplemented from advancingFrontAMI.
Definition at line 626 of file faceAreaWeightAMI.C.
References addProfiling, advancingFrontAMI::calculate(), mapDistributeBase::distribute(), UPtrList< T >::empty(), Foam::endl(), forAll, UPstream::nonBlocking, Foam::Pout, UPtrList< T >::size(), and PtrList< T >::transfer().
write()
void write (Ostream & os) const virtual
Reimplemented from advancingFrontAMI.
Definition at line 790 of file faceAreaWeightAMI.C.
References os(), advancingFrontAMI::write(), and Ostream::writeEntry().
The documentation for this class was generated from the following files:
src/meshTools/AMIInterpolation/AMIInterpolation/faceAreaWeightAMI/faceAreaWeightAMI.H
src/meshTools/AMIInterpolation/AMIInterpolation/faceAreaWeightAMI/faceAreaWeightAMI.C