OpenFOAM: lookupProfile Class Reference
lookupProfile Class Reference
Profile model where polar lift and drag coefficients are linearly interpolated from a polar table by using an input angle of attack.
#include <lookupProfile.H>
Public Member Functions
TypeName ("lookup")
lookupProfile (const dictionary &dict, const word &modelName)
lookupProfile (const lookupProfile &)=delete
void operator= (const lookupProfile &)=delete
~lookupProfile ()=default
virtual void Cdl (const scalar alpha, scalar &Cd, scalar &Cl) const
Public Member Functions inherited from profileModel
TypeName ("profileModel")
declareRunTimeSelectionTable (autoPtr, profileModel, dictionary,(const dictionary &dict, const word &modelName),(dict, modelName))
profileModel (const dictionary &dict, const word &modelName)
virtual ~profileModel ()=default
const word & name () const
Protected Member Functions
void interpolateWeights (const scalar &xIn, const List< scalar > &values, label &i1, label &i2, scalar &ddx) const
Protected Member Functions inherited from profileModel
bool readFromFile () const
Protected Attributes
List< scalar > AOA_
List< scalar > Cd_
List< scalar > Cl_
Protected Attributes inherited from profileModel
const dictionary dict_
const word name_
fileName fName_
Additional Inherited Members
Static Public Member Functions inherited from profileModel
static autoPtr< profileModel > New (const dictionary &dict)
Detailed Description
Profile model where polar lift and drag coefficients are linearly interpolated from a polar table by using an input angle of attack.
Usage
Minimal example by using constant/fvOptions: rotorDiskSource1 { Mandatory/Optional (inherited) entries ...
Mandatory entries (runtime modifiable) profiles { Mandatory entries (runtime modifiable) <profile1> { Mandatory entries (runtime modifiable) type lookup; data ((AOA1 Cd1 Cl2) (AOA2 Cd2 Cl2) ([0] [1] [2]) ... (AOAN CdN CdN)); }
Mandatory/Optional (inherited) entries ... } }
where the entries mean:
Property Description Type Reqd Dflt
[0] AOA Angle of attack scalar yes -
[1] Cd
Drag coefficient corresponding to the angle attack
scalar yes -
[2] Cl
Lift coefficient corresponding to the angle attack
scalar yes -
Note
Angle of attack is internally converted from [deg] to [rad].
See also
Foam::fv::rotorDiskSource
Foam::profileModel
Foam::seriesProfile
Source files
lookupProfile.H
lookupProfile.C
Definition at line 125 of file lookupProfile.H.
Constructor & Destructor Documentation
lookupProfile() [1/2]
lookupProfile (const dictionary & dict, const word & modelName)
Definition at line 88 of file lookupProfile.C.
References lookupProfile::AOA_, lookupProfile::Cd_, lookupProfile::Cl_, Foam::degToRad(), dict, Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, profileModel::fName_, forAll, dictionary::readEntry(), profileModel::readFromFile(), and List< T >::setSize().
lookupProfile() [2/2]
lookupProfile (const lookupProfile &) delete
~lookupProfile()
~lookupProfile () default
Member Function Documentation
interpolateWeights()
void interpolateWeights (const scalar & xIn, const List< scalar > & values, label & i1, label & i2, scalar & ddx) const protected
Definition at line 39 of file lookupProfile.C.
TypeName()
TypeName ("lookup")
operator=()
void operator= (const lookupProfile &) delete
Cdl()
void Cdl (const scalar alpha, scalar & Cd, scalar & Cl) const virtual
Implements profileModel.
Definition at line 134 of file lookupProfile.C.
References alpha.
Member Data Documentation
AOA_
List<scalar> AOA_ protected
Definition at line 134 of file lookupProfile.H.
Referenced by lookupProfile::lookupProfile().
Cd_
List<scalar> Cd_ protected
Definition at line 137 of file lookupProfile.H.
Referenced by lookupProfile::lookupProfile().
Cl_
List<scalar> Cl_ protected
Definition at line 140 of file lookupProfile.H.
Referenced by lookupProfile::lookupProfile().
The documentation for this class was generated from the following files:
src/fvOptions/sources/derived/rotorDiskSource/profileModel/lookup/lookupProfile.H
src/fvOptions/sources/derived/rotorDiskSource/profileModel/lookup/lookupProfile.C