OpenFOAM: error Class Reference
error Class Reference
Class to handle errors and exceptions in a simple, consistent stream-based manner.
#include <error.H>
Public Member Functions
error (const string &title)
error (const dictionary &errDict)
error (const error &err)
virtual ~error () noexcept
string message () const
void clear () const
const string & functionName () const noexcept
const string & sourceFileName () const noexcept
label sourceFileLineNumber () const noexcept
bool throwing () const noexcept
bool throwing (const bool on) noexcept
OSstream & stream ()
operator OSstream & ()
OSstream & operator() ()
OSstream & operator() (const string &functionName)
OSstream & operator() (const char *functionName, const char *sourceFileName, const int sourceFileLineNumber=0)
OSstream & operator() (const string &functionName, const char *sourceFileName, const int sourceFileLineNumber=0)
operator dictionary () const
void exit (const int errNo=1)
void abort ()
virtual void write (Ostream &os, const bool withTitle=true) const
bool throwExceptions (const bool on=true) noexcept
bool dontThrowExceptions () noexcept
Public Member Functions inherited from messageStream
messageStream (const string &title, const errorSeverity severity, const int maxErrors=0)
messageStream (const dictionary &dict)
const string & title () const noexcept
int maxErrors () const noexcept
int maxErrors (int nErrors) noexcept
OSstream & stream (OSstream *alternative=nullptr)
OSstream & masterStream (const label communicator)
std::ostream & stdStream ()
OSstream & deprecated (const int afterVersion, const char *functionName, const char *sourceFileName, const int sourceFileLineNumber=0)
operator OSstream & ()
OSstream & operator() ()
OSstream & operator() (const std::string &functionName)
OSstream & operator() (const char *functionName, const char *sourceFileName, const int sourceFileLineNumber=0)
OSstream & operator() (const std::string &functionName, const char *sourceFileName, const int sourceFileLineNumber=0)
OSstream & operator() (const char *functionName, const char *sourceFileName, const int sourceFileLineNumber, const std::string &ioFileName, const label ioStartLineNumber=-1, const label ioEndLineNumber=-1)
OSstream & operator() (const char *functionName, const char *sourceFileName, const int sourceFileLineNumber, const IOstream &)
OSstream & operator() (const char *functionName, const char *sourceFileName, const int sourceFileLineNumber, const dictionary &)
Static Public Member Functions
static bool master (const label communicator=-1)
static bool warnAboutAge (const int version) noexcept
static bool warnAboutAge (const char *what, const int version)
static void safePrintStack (std::ostream &os, int size=-1)
static void printStack (Ostream &os, int size=-1)
static bool useAbort ()
Protected Member Functions
void simpleExit (const int errNo, const bool isAbort)
Protected Attributes
string functionName_
string sourceFileName_
label sourceFileLineNumber_
bool throwing_
std::unique_ptr< OStringStream > messageStreamPtr_
Protected Attributes inherited from messageStream
string title_
errorSeverity severity_
int maxErrors_
int errorCount_
Additional Inherited Members
Public Types inherited from messageStream
enum errorSeverity {
INFO = 1 , INFO_STDERR , WARNING , SERIOUS ,
FATAL
}
Static Public Attributes inherited from messageStream
static int level
static int redirect
Detailed Description
Class to handle errors and exceptions in a simple, consistent stream-based manner.
The error class is globally instantiated with a title string. Errors, messages and other data are piped to the messageStream class in the standard manner. Manipulators are supplied for exit and abort that may terminate the program or throw an exception depending on whether the exception handling has been switched on (off by default).
Usage
error << "message1" << "message2" << FoamDataType << exit(errNo);
error << "message1" << "message2" << FoamDataType << abort();
Source files
error.H
error.C
IOerror.C
See also
Foam::errorManip Foam::errorManipArg
Definition at line 69 of file error.H.
Constructor & Destructor Documentation
error() [1/3]
error (const string & title) explicit
Definition at line 103 of file error.C.
error() [2/3]
error (const dictionary & errDict) explicit
Definition at line 115 of file error.C.
error() [3/3]
error (const error & err)
Definition at line 127 of file error.C.
~error()
~error () virtual noexcept
Definition at line 141 of file error.C.
Member Function Documentation
simpleExit()
void simpleExit (const int errNo, const bool isAbort) protected
Definition at line 249 of file error.C.
References UPstream::abort(), Foam::endl(), UPstream::exit(), Foam::nl, UPstream::parRun(), Foam::Perr, error::printStack(), and error::useAbort().
master()
bool master (const label communicator = -1) static
Definition at line 37 of file error.C.
References UPstream::master(), and UPstream::parRun().
Referenced by dictionary::csearchCompat(), Foam::expandLeadingTilde(), and Foam::warnCompatDegrees().
warnAboutAge() [1/2]
bool warnAboutAge (const int version) static noexcept
Definition at line 51 of file error.C.
References Foam::foamVersion::api.
Referenced by dictionary::csearchCompat(), Foam::expandLeadingTilde(), and timeControl::read().
warnAboutAge() [2/2]
bool warnAboutAge (const char * what, const int version) static
Definition at line 58 of file error.C.
References Foam::foamVersion::api.
message()
Foam::string message () const
Definition at line 315 of file error.C.
Referenced by motionSmootherAlgo::checkMesh(), and motionSmootherAlgo::checkMesh().
clear()
void clear () const
Definition at line 321 of file error.C.
Referenced by motionSmootherAlgo::checkMesh(), and motionSmootherAlgo::checkMesh().
functionName()
const string & functionName () const inline noexcept
Definition at line 147 of file error.H.
References error::functionName_.
sourceFileName()
const string & sourceFileName () const inline noexcept
Definition at line 153 of file error.H.
References error::sourceFileName_.
sourceFileLineNumber()
label sourceFileLineNumber () const inline noexcept
Definition at line 159 of file error.H.
References error::sourceFileLineNumber_.
throwing() [1/2]
bool throwing () const inline noexcept
Definition at line 165 of file error.H.
References error::throwing_.
Referenced by functionObjectList::end(), functionObjectList::execute(), if(), IOobjectList::IOobjectList(), functionObjectList::read(), and error::throwExceptions().
throwing() [2/2]
bool throwing (const bool on) inline noexcept
Definition at line 172 of file error.H.
References error::throwing_.
stream()
Foam::OSstream & stream ()
Definition at line 300 of file error.C.
References Foam::abort(), Foam::endl(), Foam::nl, and Foam::Perr.
Referenced by error::operator OSstream &(), error::operator()(), and Time::readDict().
operator OSstream &()
operator OSstream & () inline
Definition at line 186 of file error.H.
References error::stream().
operator()() [1/4]
OSstream & operator() () inline
Definition at line 192 of file error.H.
References error::stream().
operator()() [2/4]
Foam::OSstream & operator() (const string & functionName)
Definition at line 147 of file error.C.
operator()() [3/4]
Foam::OSstream & operator() (const char * functionName, const char * sourceFileName, const int sourceFileLineNumber = 0)
Definition at line 160 of file error.C.
operator()() [4/4]
Foam::OSstream & operator() (const string & functionName, const char * sourceFileName, const int sourceFileLineNumber = 0)
Definition at line 186 of file error.C.
operator dictionary()
operator dictionary () const
safePrintStack()
void safePrintStack (std::ostream & os, int size = -1) static
Definition at line 26 of file dummyPrintStack.C.
printStack()
void printStack (Ostream & os, int size = -1) static
Definition at line 30 of file dummyPrintStack.C.
Referenced by Foam::exitNow(), messageStream::masterStream(), GeometricField< Type, PatchField, GeoMesh >::oldTime(), Foam::reduce(), and error::simpleExit().
useAbort()
bool useAbort () static
Definition at line 94 of file error.C.
References Switch::find(), and Foam::getEnv().
Referenced by Foam::exitNow(), and error::simpleExit().
exit()
void exit (const int errNo = 1)
Definition at line 327 of file error.C.
Referenced by Foam::exit(), and if().
abort()
void abort ()
Definition at line 333 of file error.C.
Referenced by Foam::abort().
write()
void write (Ostream & os, const bool withTitle = true) const virtual
Reimplemented in IOerror.
Definition at line 339 of file error.C.
References Foam::foamVersion::api, IOstream::bad(), messageStream::level, Foam::nl, os(), Foam::foamVersion::patch, and Foam::foamVersion::patched().
Referenced by argList::parse().
throwExceptions()
bool throwExceptions (const bool on = true) inline noexcept
Definition at line 256 of file error.H.
References error::throwing().
Referenced by error::dontThrowExceptions().
dontThrowExceptions()
bool dontThrowExceptions () inline noexcept
Definition at line 263 of file error.H.
References error::throwExceptions().
Member Data Documentation
functionName_
string functionName_ protected
Definition at line 84 of file error.H.
Referenced by error::functionName().
sourceFileName_
string sourceFileName_ protected
Definition at line 85 of file error.H.
Referenced by error::sourceFileName().
sourceFileLineNumber_
label sourceFileLineNumber_ protected
Definition at line 86 of file error.H.
Referenced by error::sourceFileLineNumber().
throwing_
bool throwing_ protected
Definition at line 87 of file error.H.
Referenced by error::throwing(), and error::throwing().
messageStreamPtr_
std::unique_ptr<OStringStream> messageStreamPtr_ protected
Definition at line 88 of file error.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/db/error/error.H
src/OpenFOAM/db/error/error.C
src/OSspecific/POSIX/printStack/dummyPrintStack.C
src/OSspecific/POSIX/printStack/printStack.C