OpenFOAM: CollisionRecordList< PairType, WallType > Class Template Reference
CollisionRecordList< PairType, WallType > Class Template Reference
#include <CollisionRecordList.H>
Public Member Functions
CollisionRecordList ()=default
CollisionRecordList (Istream &is)
CollisionRecordList (const labelField &pairAccessed, const labelField &pairOrigProcOfOther, const labelField &pairOrigIdOfOther, const Field< PairType > &pairData, const labelField &wallAccessed, const vectorField &wallPRel, const Field< WallType > &wallData)
const DynamicList< PairCollisionRecord< PairType > > & pairRecords () const
const DynamicList< WallCollisionRecord< WallType > > & wallRecords () const
labelField pairAccessed () const
labelField pairOrigProcOfOther () const
labelField pairOrigIdOfOther () const
Field< PairType > pairData () const
labelField wallAccessed () const
vectorField wallPRel () const
Field< WallType > wallData () const
PairCollisionRecord< PairType > & matchPairRecord (label origProcOfOther, label origIdOfOther)
bool checkPairRecord (label origProcOfOther, label origIdOfOther)
WallCollisionRecord< WallType > & matchWallRecord (const vector &pRel, scalar radius)
bool checkWallRecord (const vector &pRel, scalar radius)
void update ()
Friends
bool operator== (const CollisionRecordList< PairType, WallType > &, const CollisionRecordList< PairType, WallType > &)
bool operator!= (const CollisionRecordList< PairType, WallType > &, const CollisionRecordList< PairType, WallType > &)
Istream & operator>> (Istream &, CollisionRecordList< PairType, WallType > &)
Ostream & operator (Ostream &, const CollisionRecordList< PairType, WallType > &)
Detailed Description
template<class PairType, class WallType>
class Foam::CollisionRecordList< PairType, WallType >
Source files
CollisionRecordList.H
CollisionRecordListI.H
CollisionRecordList.C
CollisionRecordListIO.C
Definition at line 76 of file CollisionRecordList.H.
Constructor & Destructor Documentation
CollisionRecordList() [1/3]
template<class PairType , class WallType > CollisionRecordList () default
CollisionRecordList() [2/3]
template<class PairType , class WallType > CollisionRecordList (Istream & is) explicit
Definition at line 28 of file CollisionRecordList.C.
References FUNCTION_NAME.
CollisionRecordList() [3/3]
template<class PairType , class WallType > CollisionRecordList (const labelField & pairAccessed, const labelField & pairOrigProcOfOther, const labelField & pairOrigIdOfOther, const Field< PairType > & pairData, const labelField & wallAccessed, const vectorField & wallPRel, const Field< WallType > & wallData)
Definition at line 38 of file CollisionRecordList.C.
References Foam::abort(), PtrList< T >::append(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::nl, CollisionRecordList< PairType, WallType >::pairAccessed(), CollisionRecordList< PairType, WallType >::pairData(), CollisionRecordList< PairType, WallType >::pairOrigIdOfOther(), CollisionRecordList< PairType, WallType >::pairOrigProcOfOther(), UPtrList< T >::size(), UList< T >::size(), CollisionRecordList< PairType, WallType >::wallAccessed(), CollisionRecordList< PairType, WallType >::wallData(), and CollisionRecordList< PairType, WallType >::wallPRel().
Member Function Documentation
pairRecords()
template<class PairType , class WallType > const Foam::DynamicList< Foam::PairCollisionRecord< PairType > > & pairRecords () const inline
Definition at line 25 of file CollisionRecordListI.H.
wallRecords()
template<class PairType , class WallType > const Foam::DynamicList< Foam::WallCollisionRecord< WallType > > & wallRecords () const inline
Definition at line 33 of file CollisionRecordListI.H.
pairAccessed()
template<class PairType , class WallType > Foam::labelField pairAccessed () const
Definition at line 115 of file CollisionRecordList.C.
References f(), and forAll.
Referenced by CollisionRecordList< PairType, WallType >::CollisionRecordList().
pairOrigProcOfOther()
template<class PairType , class WallType > Foam::labelField pairOrigProcOfOther () const
Definition at line 130 of file CollisionRecordList.C.
References f(), and forAll.
Referenced by CollisionRecordList< PairType, WallType >::CollisionRecordList().
pairOrigIdOfOther()
template<class PairType , class WallType > Foam::labelField pairOrigIdOfOther () const
Definition at line 145 of file CollisionRecordList.C.
References f().
Referenced by CollisionRecordList< PairType, WallType >::CollisionRecordList().
pairData()
template<class PairType , class WallType > Foam::Field< PairType > pairData () const
Definition at line 160 of file CollisionRecordList.C.
References f().
Referenced by CollisionRecordList< PairType, WallType >::CollisionRecordList().
wallAccessed()
template<class PairType , class WallType > Foam::labelField wallAccessed () const
Definition at line 175 of file CollisionRecordList.C.
References f().
Referenced by CollisionRecordList< PairType, WallType >::CollisionRecordList().
wallPRel()
template<class PairType , class WallType > Foam::vectorField wallPRel () const
Definition at line 190 of file CollisionRecordList.C.
Referenced by CollisionRecordList< PairType, WallType >::CollisionRecordList().
wallData()
template<class PairType , class WallType > Foam::Field< WallType > wallData () const
Definition at line 205 of file CollisionRecordList.C.
References f(), and forAll.
Referenced by CollisionRecordList< PairType, WallType >::CollisionRecordList().
matchPairRecord()
template<class PairType , class WallType > Foam::PairCollisionRecord< PairType > & matchPairRecord (label origProcOfOther, label origIdOfOther)
Definition at line 220 of file CollisionRecordList.C.
References PtrList< T >::append(), forAll, and UPtrList< T >::last().
checkPairRecord()
template<class PairType , class WallType > bool checkPairRecord (label origProcOfOther, label origIdOfOther)
Definition at line 256 of file CollisionRecordList.C.
References forAll.
matchWallRecord()
template<class PairType , class WallType > Foam::WallCollisionRecord< WallType > & matchWallRecord (const vector & pRel, scalar radius)
Definition at line 278 of file CollisionRecordList.C.
References PtrList< T >::append(), forAll, and UPtrList< T >::last().
checkWallRecord()
template<class PairType , class WallType > bool checkWallRecord (const vector & pRel, scalar radius)
Definition at line 310 of file CollisionRecordList.C.
References forAll.
update()
template<class PairType , class WallType > void update ()
Definition at line 331 of file CollisionRecordList.C.
References PtrList< T >::append(), and forAll.
Friends And Related Symbol Documentation
operator==
template<class PairType , class WallType > bool operator== (const CollisionRecordList< PairType, WallType > & , const CollisionRecordList< PairType, WallType > &) friend
operator!=
template<class PairType , class WallType > bool operator!= (const CollisionRecordList< PairType, WallType > & , const CollisionRecordList< PairType, WallType > &) friend
operator>>
template<class PairType , class WallType > Istream & operator>> (Istream & , CollisionRecordList< PairType, WallType > &) friend
operator
template<class PairType , class WallType > Ostream & operator (Ostream & , const CollisionRecordList< PairType, WallType > &) friend
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/parcels/Templates/CollidingParcel/CollisionRecordList/CollisionRecordList.H
src/lagrangian/intermediate/parcels/Templates/CollidingParcel/CollisionRecordList/CollisionRecordList.C
src/lagrangian/intermediate/parcels/Templates/CollidingParcel/CollisionRecordList/CollisionRecordListI.H