OpenFOAM: heatTransferCoeffModel Class Reference
heatTransferCoeffModel Class Reference abstract
A base class for heat transfer coefficient models.
#include <heatTransferCoeffModel.H>
Public Member Functions
TypeName ("heatTransferCoeffModel")
declareRunTimeSelectionTable (autoPtr, heatTransferCoeffModel, dictionary,(const dictionary &dict, const fvMesh &mesh, const word &TName),(dict, mesh, TName))
heatTransferCoeffModel (const dictionary &dict, const fvMesh &mesh, const word &TName)
heatTransferCoeffModel (const heatTransferCoeffModel &)=delete
void operator= (const heatTransferCoeffModel &)=delete
virtual ~heatTransferCoeffModel ()=default
const fvMesh & mesh () const noexcept
const labelHashSet & patchSet () const noexcept
const word & TName () const noexcept
const word & qrName () const noexcept
tmp< FieldField< Field, scalar > > q () const
virtual bool calc (volScalarField &result, const FieldField< Field, scalar > &q)
virtual bool read (const dictionary &dict)
Static Public Member Functions
static autoPtr< heatTransferCoeffModel > New (const dictionary &dict, const fvMesh &mesh, const word &TName)
Protected Member Functions
virtual void htc (volScalarField &htc, const FieldField< Field, scalar > &q)=0
Protected Attributes
const fvMesh & mesh_
labelHashSet patchSet_
const word TName_
word qrName_
Detailed Description
A base class for heat transfer coefficient models.
Source files
heatTransferCoeffModel.H
heatTransferCoeffModel.C
heatTransferCoeffModelNew.C
Definition at line 57 of file heatTransferCoeffModel.H.
Constructor & Destructor Documentation
heatTransferCoeffModel() [1/2]
heatTransferCoeffModel (const dictionary & dict, const fvMesh & mesh, const word & TName)
Definition at line 38 of file heatTransferCoeffModel.C.
heatTransferCoeffModel() [2/2]
heatTransferCoeffModel (const heatTransferCoeffModel &) delete
~heatTransferCoeffModel()
virtual ~heatTransferCoeffModel () virtual default
Member Function Documentation
htc()
virtual void htc (volScalarField & htc, const FieldField< Field, scalar > & q) protected pure virtual
Implemented in fixedReferenceTemperature, localReferenceTemperature, and ReynoldsAnalogy.
TypeName()
TypeName ("heatTransferCoeffModel")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , heatTransferCoeffModel , dictionary , (const dictionary &dict, const fvMesh &mesh, const word &TName) , (dict, mesh, TName))
New()
Foam::autoPtr< Foam::heatTransferCoeffModel > New (const dictionary & dict, const fvMesh & mesh, const word & TName) static
Definition at line 27 of file heatTransferCoeffModelNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, Foam::Info, heatTransferCoeffModel::mesh(), and heatTransferCoeffModel::TName().
operator=()
void operator= (const heatTransferCoeffModel &) delete
mesh()
const fvMesh & mesh () const inline noexcept
Definition at line 145 of file heatTransferCoeffModel.H.
References heatTransferCoeffModel::mesh_.
Referenced by heatTransferCoeffModel::New().
patchSet()
const labelHashSet & patchSet () const inline noexcept
Definition at line 151 of file heatTransferCoeffModel.H.
References heatTransferCoeffModel::patchSet_.
TName()
const word & TName () const inline noexcept
Definition at line 157 of file heatTransferCoeffModel.H.
References heatTransferCoeffModel::TName_.
Referenced by heatTransferCoeffModel::New().
qrName()
const word & qrName () const inline noexcept
Definition at line 163 of file heatTransferCoeffModel.H.
References heatTransferCoeffModel::qrName_.
q()
Foam::tmp< Foam::FieldField< Foam::Field, Foam::scalar > > q () const
Definition at line 55 of file heatTransferCoeffModel.C.
References alpha, alphaEff(), ThermalDiffusivity< BasicTurbulenceModel >::alphaEff(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), basicThermo::dictName, Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, he, Foam::New(), Foam::nl, PtrList< T >::set(), UPtrList< T >::size(), T, turb, and Foam::Zero.
Referenced by fixedReferenceTemperature::htc(), and localReferenceTemperature::htc().
calc()
bool calc (volScalarField & result, const FieldField< Field, scalar > & q) virtual
Definition at line 130 of file heatTransferCoeffModel.C.
read()
bool read (const dictionary & dict) virtual
Reimplemented in faceZoneReferenceTemperature, fixedReferenceTemperature, localReferenceTemperature, and ReynoldsAnalogy.
Definition at line 142 of file heatTransferCoeffModel.C.
References dict, dictionary::get(), and dictionary::readIfPresent().
Referenced by faceZoneReferenceTemperature::read(), fixedReferenceTemperature::read(), localReferenceTemperature::read(), and ReynoldsAnalogy::read().
Member Data Documentation
mesh_
const fvMesh& mesh_ protected
Definition at line 64 of file heatTransferCoeffModel.H.
Referenced by fixedReferenceTemperature::htc(), localReferenceTemperature::htc(), heatTransferCoeffModel::mesh(), and ReynoldsAnalogy::rho().
patchSet_
labelHashSet patchSet_ protected
Definition at line 67 of file heatTransferCoeffModel.H.
Referenced by fixedReferenceTemperature::htc(), localReferenceTemperature::htc(), and heatTransferCoeffModel::patchSet().
TName_
const word TName_ protected
Definition at line 70 of file heatTransferCoeffModel.H.
Referenced by fixedReferenceTemperature::htc(), localReferenceTemperature::htc(), and heatTransferCoeffModel::TName().
qrName_
word qrName_ protected
Definition at line 73 of file heatTransferCoeffModel.H.
Referenced by heatTransferCoeffModel::qrName().
The documentation for this class was generated from the following files:
src/functionObjects/field/heatTransferCoeff/heatTransferCoeffModels/heatTransferCoeffModel/heatTransferCoeffModel.H
src/functionObjects/field/heatTransferCoeff/heatTransferCoeffModels/heatTransferCoeffModel/heatTransferCoeffModel.C
src/functionObjects/field/heatTransferCoeff/heatTransferCoeffModels/heatTransferCoeffModel/heatTransferCoeffModelNew.C