OpenFOAM: exprString Class Reference
exprString Class Reference
#include <exprString.H>
Public Member Functions
exprString ()=default
exprString (const exprString &rhs)=default
exprString (exprString &&rhs)=default
exprString (const std::string &s, bool doCheck=true)
exprString (std::string &&s, bool doCheck=true)
exprString (const char *s, bool doCheck=true)
exprString (const word &entryName, const dictionary &dict, const bool mandatory=true)
exprString (Istream &is, const dictionary &dict, const bool stripComments=true)
~exprString ()=default
bool valid () const
void expand (const dictionary &dict, const bool stripComments=true)
void trim ()
bool readEntry (const word &keyword, const dictionary &dict, IOobjectOption::readOption readOpt=IOobjectOption::MUST_READ)
bool readIfPresent (const word &keyword, const dictionary &dict)
exprString & operator= (const exprString &str)=default
exprString & operator= (exprString &&str)=default
exprString & operator= (const char *str)
exprString & operator= (const std::string &str)
exprString & operator= (std::string &&str)
bool writeEntry (const word &keyword, Ostream &os, bool writeEmpty=false) const
Public Member Functions inherited from string
string ()=default
string (const std::string &str)
string (std::string &&str)
string (const char *str)
string (const char *str, const size_type len)
string (const char c)
string (const size_type len, const char c)
string (Istream &is)
bool match (const std::string &text) const
string & replace (const std::string &s1, const std::string &s2, size_type pos=0)
string & replaceAll (const std::string &s1, const std::string &s2, size_type pos=0)
string & replaceAny (const std::string &s1, const char c2, size_type pos=0)
string & expand (const bool allowEmpty=false)
bool removeRepeated (const char character)
bool removeStart (const std::string &text)
bool removeStart (const char c)
bool removeEnd (const std::string &text)
bool removeEnd (const char c)
void swap (std::string &str)
bool operator() (const std::string &text) const
bool contains (char c) const noexcept
bool contains (const std::string &s) const noexcept
bool contains (const char *s) const
bool starts_with (char c) const
bool starts_with (const std::string &s) const
bool starts_with (const char *s) const
bool ends_with (char c) const
bool ends_with (const std::string &s) const
bool ends_with (const char *s) const
size_type count (const char c) const
bool startsWith (const std::string &s) const
bool endsWith (const std::string &s) const
bool removeTrailing (const char c)
Static Public Member Functions
static exprString toExpr (const std::string &str)
static exprString toExpr (std::string &&str)
static exprString toExpr (const std::string &str, const dictionary &dict, const bool stripComments=true)
static exprString toExpr (std::string &&str, const dictionary &dict, const bool stripComments=true)
static void inplaceExpand (std::string &str, const dictionary &dict, const bool stripComments=true)
Static Public Member Functions inherited from string
template<class StringType >
static bool valid (const std::string &str)
template<class StringType >
static bool stripInvalid (std::string &str)
template<class StringType >
static StringType validate (const std::string &str)
Additional Inherited Members
Static Public Attributes inherited from string
static const char *const typeName = "string"
static int debug
static const string null
Protected Member Functions inherited from string
std::string::size_type find_ext () const
word ext () const
bool ext (const word &ending)
bool has_ext () const
bool has_ext (const char *ending) const
bool has_ext (const std::string &ending) const
bool has_ext (const wordRe &ending) const
bool remove_path ()
bool remove_ext ()
Static Protected Member Functions inherited from string
static std::string::size_type find_ext (const std::string &str)
template<class PrimitiveType >
static std::string::size_type string_printf (std::string &output, const char *fmt, const PrimitiveType &val)
template<class PrimitiveType >
static std::string::size_type string_printf (std::string &output, const std::string &fmt, const PrimitiveType &val)
Detailed Description
Definition at line 56 of file exprString.H.
Constructor & Destructor Documentation
exprString() [1/8]
exprString () default
Referenced by exprString::exprString(), exprString::exprString(), exprString::exprString(), exprString::exprString(), and exprString::exprString().
exprString() [2/8]
exprString (const exprString & rhs) default
exprString() [3/8]
exprString (exprString && rhs) default
exprString() [4/8]
exprString (const std::string & s, bool doCheck = true) inline explicit
Definition at line 26 of file exprStringI.H.
References exprString::exprString(), and exprString::valid().
exprString() [5/8]
exprString (std::string && s, bool doCheck = true) inline explicit
Definition at line 43 of file exprStringI.H.
References exprString::exprString(), and exprString::valid().
exprString() [6/8]
exprString (const char * s, bool doCheck = true) inline explicit
Definition at line 60 of file exprStringI.H.
References exprString::exprString(), and exprString::valid().
exprString() [7/8]
exprString (const word & entryName, const dictionary & dict, const bool mandatory = true) inline
Parameters
entryName Lookup key. LITERAL (not REGEX)
Definition at line 77 of file exprStringI.H.
References dict, exprString::exprString(), and readIfPresent().
exprString() [8/8]
exprString (Istream & is, const dictionary & dict, const bool stripComments = true) inline
Definition at line 95 of file exprStringI.H.
References dict, exprString::expand(), and exprString::exprString().
~exprString()
~exprString () default
References exprString::expand(), exprString::inplaceExpand(), exprString::readEntry(), exprString::toExpr(), exprString::trim(), and exprString::valid().
Member Function Documentation
toExpr() [1/4]
Foam::expressions::exprString toExpr (const std::string & str) inline static
Definition at line 111 of file exprStringI.H.
References exprString::toExpr().
Referenced by exprString::toExpr(), exprString::toExpr(), exprString::toExpr(), exprString::toExpr(), and exprString::~exprString().
toExpr() [2/4]
Foam::expressions::exprString toExpr (std::string && str) inline static
Definition at line 122 of file exprStringI.H.
References exprString::toExpr().
toExpr() [3/4]
Foam::expressions::exprString toExpr (const std::string & str, const dictionary & dict, const bool stripComments = true) inline static
Definition at line 133 of file exprStringI.H.
References dict, and exprString::toExpr().
toExpr() [4/4]
Foam::expressions::exprString toExpr (std::string && str, const dictionary & dict, const bool stripComments = true) inline static
Definition at line 150 of file exprStringI.H.
References dict, and exprString::toExpr().
inplaceExpand()
void inplaceExpand (std::string & str, const dictionary & dict, const bool stripComments = true) static
Definition at line 28 of file exprString.C.
References dict, expressionEntry::inplaceExpand(), exprString::inplaceExpand(), and Foam::stringOps::inplaceRemoveComments().
Referenced by exprString::inplaceExpand(), and exprString::~exprString().
valid()
bool valid () const inline
Definition at line 168 of file exprStringI.H.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::nl, and exprString::valid().
Referenced by exprString::exprString(), exprString::exprString(), exprString::exprString(), exprString::valid(), and exprString::~exprString().
expand()
void expand (const dictionary & dict, const bool stripComments = true)
Definition at line 46 of file exprString.C.
References dict, and exprString::expand().
Referenced by exprString::expand(), exprString::exprString(), and exprString::~exprString().
trim()
void trim ()
Definition at line 60 of file exprString.C.
References Foam::stringOps::inplaceTrim(), and exprString::trim().
Referenced by exprString::trim(), and exprString::~exprString().
readEntry()
bool readEntry (const word & keyword, const dictionary & dict, IOobjectOption::readOption readOpt = IOobjectOption::MUST_READ)
Parameters
keyword Lookup key. Uses LITERAL (not REGEX)
Definition at line 66 of file exprString.C.
References clear(), dict, keyType::LITERAL, and exprString::readEntry().
Referenced by exprString::readEntry(), and exprString::~exprString().
readIfPresent()
bool readIfPresent (const word & keyword, const dictionary & dict) inline
Parameters
keyword Lookup key. Uses LITERAL (not REGEX)
Definition at line 185 of file exprStringI.H.
References dict, IOobjectOption::READ_IF_PRESENT, and exprString::readIfPresent().
Referenced by exprString::readIfPresent().
operator=() [1/5]
exprString & operator= (const exprString & str) default
Referenced by exprString::operator=(), exprString::operator=(), exprString::operator=(), and exprString::operator=().
operator=() [2/5]
exprString & operator= (exprString && str) default
References exprString::operator=(), and exprString::writeEntry().
operator=() [3/5]
Foam::expressions::exprString & operator= (const char * str) inline
Definition at line 198 of file exprStringI.H.
References exprString::operator=().
operator=() [4/5]
Foam::expressions::exprString & operator= (const std::string & str) inline
Definition at line 211 of file exprStringI.H.
References exprString::operator=().
operator=() [5/5]
Foam::expressions::exprString & operator= (std::string && str) inline
Definition at line 224 of file exprStringI.H.
References exprString::operator=().
writeEntry()
bool writeEntry (const word & keyword, Ostream & os, bool writeEmpty = false) const
Definition at line 88 of file exprString.C.
References os(), token::VERBATIM, and exprString::writeEntry().
Referenced by exprString::operator=(), and exprString::writeEntry().
The documentation for this class was generated from the following files:
src/OpenFOAM/expressions/exprString/exprString.H
src/OpenFOAM/expressions/exprString/exprString.C
src/OpenFOAM/expressions/exprString/exprStringI.H