OpenFOAM: dictionaryContent Class Reference
dictionaryContent Class Reference
A wrapper for dictionary content, without operators that could affect inheritance patterns.
#include <dictionaryContent.H>
Public Member Functions
dictionaryContent ()=default
dictionaryContent (const dictionaryContent &)=default
dictionaryContent (dictionaryContent &&)=default
dictionaryContent (const dictionary &dict)
dictionaryContent (dictionary &&dict)
virtual ~dictionaryContent ()=default
const dictionary & dict () const noexcept
void dict (const dictionary &dict)
void dict (dictionary &&dict)
void operator= (const dictionaryContent &)=delete
void operator= (dictionaryContent &&)=delete
Static Public Member Functions
static dictionary copyDict (const dictionary &input, const wordList &allow=wordList(), const wordList &deny=wordList())
static dictionary copyDict (const dictionary &input, const wordRes &allow, const wordRes &deny=wordRes())
Detailed Description
A wrapper for dictionary content, without operators that could affect inheritance patterns.
Definition at line 44 of file dictionaryContent.H.
Constructor & Destructor Documentation
dictionaryContent() [1/5]
dictionaryContent () default
dictionaryContent() [2/5]
dictionaryContent (const dictionaryContent &) default
dictionaryContent() [3/5]
dictionaryContent (dictionaryContent &&) default
dictionaryContent() [4/5]
dictionaryContent (const dictionary & dict) inline explicit
Definition at line 65 of file dictionaryContent.H.
dictionaryContent() [5/5]
dictionaryContent (dictionary && dict) inline explicit
Definition at line 71 of file dictionaryContent.H.
~dictionaryContent()
virtual ~dictionaryContent () virtual default
Member Function Documentation
copyDict() [1/2]
Foam::dictionary copyDict (const dictionary & input, const wordList & allow = wordList(), const wordList & deny = wordList()) static
Definition at line 70 of file dictionaryContent.C.
References Foam::copyFilteredDict(), UPtrList< T >::empty(), and Foam::input().
copyDict() [2/2]
Foam::dictionary copyDict (const dictionary & input, const wordRes & allow, const wordRes & deny = wordRes()) static
Definition at line 105 of file dictionaryContent.C.
References Foam::copyFilteredDict(), UPtrList< T >::empty(), Foam::input(), wordRe::LITERAL, and wordRe::REGEX.
dict() [1/3]
const dictionary & dict () const inline noexcept
Definition at line 120 of file dictionaryContent.H.
Referenced by dictionaryContent::dict(), and dictionaryContent::dict().
dict() [2/3]
void dict (const dictionary & dict) inline
Definition at line 126 of file dictionaryContent.H.
References dictionaryContent::dict().
dict() [3/3]
void dict (dictionary && dict) inline
Definition at line 132 of file dictionaryContent.H.
References dictionaryContent::dict().
operator=() [1/2]
void operator= (const dictionaryContent &) delete
operator=() [2/2]
void operator= (dictionaryContent &&) delete
The documentation for this class was generated from the following files:
src/OpenFOAM/db/dictionary/dictionaryContent/dictionaryContent.H
src/OpenFOAM/db/dictionary/dictionaryContent/dictionaryContent.C