OpenFOAM: pairPatchAgglomeration Class Reference
pairPatchAgglomeration Class Reference
Primitive patch pair agglomerate method.
#include <pairPatchAgglomeration.H>
Public Member Functions
TypeName ("pairPatch")
pairPatchAgglomeration (const faceList &faces, const pointField &points, const dictionary &controlDict)
pairPatchAgglomeration (const faceList &faces, const pointField &points, const label mergeLevels, const label maxLevels, const label nFacesInCoarsestLevel, const label nGlobalFacesInCoarsestLevel, const scalar featureAngle=0)
virtual ~pairPatchAgglomeration ()
void agglomerate ()
label size () const
const labelList & restrictTopBottomAddressing () const
const bPatch & patchLevel (const label leveli) const
const labelField & restrictAddressing (const label leveli) const
template<class Type >
void restrictField (Field< Type > &cf, const Field< Type > &ff, const label fineLevelIndex) const
template<class Type >
void prolongField (Field< Type > &ff, const Field< Type > &cf, const label coarseLevelIndex) const
Protected Types
typedef PrimitivePatch< List< face >, const pointField > bPatch
Protected Attributes
label mergeLevels_
label maxLevels_
label nFacesInCoarsestLevel_
label nGlobalFacesInCoarsestLevel_
scalar featureAngle_
labelList nFaces_
PtrList< labelField > restrictAddressing_
labelList restrictTopBottomAddressing_
PtrList< bPatch > patchLevels_
EdgeMap< scalar > facePairWeight_
Detailed Description
Primitive patch pair agglomerate method.
Source files
pairPatchAgglomeration.H
pairPatchAgglomeration.C
Definition at line 50 of file pairPatchAgglomeration.H.
Member Typedef Documentation
bPatch
typedef PrimitivePatch<List<face>, const pointField> bPatch protected
Definition at line 54 of file pairPatchAgglomeration.H.
Constructor & Destructor Documentation
pairPatchAgglomeration() [1/2]
pairPatchAgglomeration (const faceList & faces, const pointField & points, const dictionary & controlDict)
Definition at line 336 of file pairPatchAgglomeration.C.
References pairPatchAgglomeration::nFaces_, pairPatchAgglomeration::patchLevels_, points, PtrList< T >::set(), and UList< T >::size().
pairPatchAgglomeration() [2/2]
pairPatchAgglomeration (const faceList & faces, const pointField & points, const label mergeLevels, const label maxLevels, const label nFacesInCoarsestLevel, const label nGlobalFacesInCoarsestLevel, const scalar featureAngle = 0)
Definition at line 377 of file pairPatchAgglomeration.C.
References pairPatchAgglomeration::nFaces_, pairPatchAgglomeration::patchLevels_, points, PtrList< T >::set(), and UList< T >::size().
~pairPatchAgglomeration()
~pairPatchAgglomeration () virtual
Definition at line 412 of file pairPatchAgglomeration.C.
Member Function Documentation
TypeName()
TypeName ("pairPatch")
agglomerate()
void agglomerate ()
Definition at line 565 of file pairPatchAgglomeration.C.
References Foam::endl(), OFstream::name(), Foam::name(), os(), Foam::Pout, PtrList< T >::set(), and OBJstream::write().
size()
label size () const inline
Definition at line 202 of file pairPatchAgglomeration.H.
References pairPatchAgglomeration::patchLevels_, and UPtrList< T >::size().
restrictTopBottomAddressing()
const labelList & restrictTopBottomAddressing () const inline
Definition at line 208 of file pairPatchAgglomeration.H.
References pairPatchAgglomeration::restrictTopBottomAddressing_.
patchLevel()
const Foam::pairPatchAgglomeration::bPatch & patchLevel (const label leveli) const
Definition at line 419 of file pairPatchAgglomeration.C.
restrictAddressing()
const labelField & restrictAddressing (const label leveli) const inline
Definition at line 217 of file pairPatchAgglomeration.H.
References pairPatchAgglomeration::restrictAddressing_.
restrictField()
template<class Type > void restrictField (Field< Type > & cf, const Field< Type > & ff, const label fineLevelIndex) const
Definition at line 26 of file pairPatchAgglomerationTemplates.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, pairPatchAgglomeration::restrictAddressing_, and UPtrList< T >::size().
prolongField()
template<class Type > void prolongField (Field< Type > & ff, const Field< Type > & cf, const label coarseLevelIndex) const
Definition at line 54 of file pairPatchAgglomerationTemplates.C.
References forAll.
Member Data Documentation
mergeLevels_
label mergeLevels_ protected
Definition at line 59 of file pairPatchAgglomeration.H.
maxLevels_
label maxLevels_ protected
Definition at line 62 of file pairPatchAgglomeration.H.
nFacesInCoarsestLevel_
label nFacesInCoarsestLevel_ protected
Definition at line 65 of file pairPatchAgglomeration.H.
nGlobalFacesInCoarsestLevel_
label nGlobalFacesInCoarsestLevel_ protected
Definition at line 68 of file pairPatchAgglomeration.H.
featureAngle_
scalar featureAngle_ protected
Definition at line 71 of file pairPatchAgglomeration.H.
nFaces_
labelList nFaces_ protected
Definition at line 74 of file pairPatchAgglomeration.H.
Referenced by pairPatchAgglomeration::pairPatchAgglomeration(), and pairPatchAgglomeration::pairPatchAgglomeration().
restrictAddressing_
PtrList<labelField> restrictAddressing_ protected
Definition at line 78 of file pairPatchAgglomeration.H.
Referenced by pairPatchAgglomeration::restrictAddressing(), and pairPatchAgglomeration::restrictField().
restrictTopBottomAddressing_
labelList restrictTopBottomAddressing_ protected
Definition at line 81 of file pairPatchAgglomeration.H.
Referenced by pairPatchAgglomeration::restrictTopBottomAddressing().
patchLevels_
PtrList<bPatch> patchLevels_ protected
Definition at line 84 of file pairPatchAgglomeration.H.
Referenced by pairPatchAgglomeration::pairPatchAgglomeration(), pairPatchAgglomeration::pairPatchAgglomeration(), and pairPatchAgglomeration::size().
facePairWeight_
EdgeMap<scalar> facePairWeight_ protected
Definition at line 87 of file pairPatchAgglomeration.H.
The documentation for this class was generated from the following files:
src/fvAgglomerationMethods/pairPatchAgglomeration/pairPatchAgglomeration.H
src/fvAgglomerationMethods/pairPatchAgglomeration/pairPatchAgglomeration.C
src/fvAgglomerationMethods/pairPatchAgglomeration/pairPatchAgglomerationTemplates.C