OpenFOAM: edgeMeshFormatsCore Class Reference
edgeMeshFormatsCore Class Reference
A collection of helper functions for reading/writing edge formats.
#include <edgeMeshFormatsCore.H>
Public Member Functions
edgeMeshFormatsCore ()=default
virtual ~edgeMeshFormatsCore ()=default
Static Public Member Functions
static bool checkSupport (const wordHashSet &available, const word &fileType, const bool verbose=false, const char *functionName=nullptr)
Static Public Attributes
static word nativeExt
Static Protected Member Functions
static string getLineNoComment (ISstream &is, const char comment='#')
Detailed Description
A collection of helper functions for reading/writing edge formats.
Source files
edgeMeshFormatsCore.H
edgeMeshFormatsCore.C
Definition at line 56 of file edgeMeshFormatsCore.H.
Constructor & Destructor Documentation
edgeMeshFormatsCore()
edgeMeshFormatsCore () default
~edgeMeshFormatsCore()
virtual ~edgeMeshFormatsCore () virtual default
Member Function Documentation
getLineNoComment()
Foam::string getLineNoComment (ISstream & is, const char comment = '#') static protected
Definition at line 34 of file edgeMeshFormatsCore.C.
checkSupport()
bool checkSupport (const wordHashSet & available, const word & fileType, const bool verbose = false, const char * functionName = nullptr) static
Definition at line 151 of file edgeMeshFormatsCore.C.
References Foam::flatOutput(), HashTable< T, Key, Hash >::found(), Foam::Info, Foam::nl, and HashTable< T, Key, Hash >::sortedToc().
Member Data Documentation
nativeExt
Foam::word nativeExt static
Definition at line 71 of file edgeMeshFormatsCore.H.
The documentation for this class was generated from the following files:
src/meshTools/edgeMesh/edgeFormats/edgeMeshFormatsCore.H
src/meshTools/edgeMesh/edgeFormats/edgeMeshFormatsCore.C