OpenFOAM: pointFieldReconstructor Class Reference
pointFieldReconstructor Class Reference
Point field reconstructor.
#include <pointFieldReconstructor.H>
Classes
class pointPatchFieldReconstructor
Public Member Functions
pointFieldReconstructor (const pointMesh &mesh, const PtrList< pointMesh > &procMeshes, const PtrList< labelIOList > &pointProcAddressing, const PtrList< labelIOList > &boundaryProcAddressing)
label nReconstructed () const noexcept
template<class Type >
tmp< GeometricField< Type, pointPatchField, pointMesh > > reconstructField (const IOobject &fieldObject, const PtrList< GeometricField< Type, pointPatchField, pointMesh > > &) const
template<class Type >
tmp< GeometricField< Type, pointPatchField, pointMesh > > reconstructPointField (const IOobject &fieldObject)
template<class Type >
label reconstructPointFields (const UPtrList< const IOobject > &fieldObjects)
template<class Type >
label reconstructPointFields (const IOobjectList &objects, const wordRes &selectedFields=wordRes())
label reconstructAllFields (const IOobjectList &objects, const wordRes &selectedFields=wordRes())
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::pointPatchField, Foam::pointMesh > > reconstructField (const IOobject &fieldObject, const PtrList< GeometricField< Type, pointPatchField, pointMesh > > &procFields) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::pointPatchField, Foam::pointMesh > > reconstructPointField (const IOobject &fieldObject)
template<class Type >
Foam::label reconstructPointFields (const UPtrList< const IOobject > &fieldObjects)
template<class Type >
Foam::label reconstructPointFields (const IOobjectList &objects, const wordRes &selectedFields)
Static Public Attributes
static int verbose_ = 1
Detailed Description
Point field reconstructor.
Source files
pointFieldReconstructor.H
pointFieldReconstructor.C
pointFieldReconstructorTemplates.C
Definition at line 51 of file pointFieldReconstructor.H.
Constructor & Destructor Documentation
pointFieldReconstructor()
pointFieldReconstructor (const pointMesh & mesh, const PtrList< pointMesh > & procMeshes, const PtrList< labelIOList > & pointProcAddressing, const PtrList< labelIOList > & boundaryProcAddressing)
Definition at line 32 of file pointFieldReconstructor.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::min(), List< T >::setSize(), PtrList< T >::setSize(), and UPtrList< T >::size().
Member Function Documentation
nReconstructed()
label nReconstructed () const inline noexcept
Definition at line 149 of file pointFieldReconstructor.H.
reconstructField() [1/2]
template<class Type > tmp< GeometricField< Type, pointPatchField, pointMesh > > reconstructField (const IOobject & fieldObject, const PtrList< GeometricField< Type, pointPatchField, pointMesh > > &) const
reconstructPointField() [1/2]
template<class Type > tmp< GeometricField< Type, pointPatchField, pointMesh > > reconstructPointField (const IOobject & fieldObject)
reconstructPointFields() [1/4]
template<class Type > label reconstructPointFields (const UPtrList< const IOobject > & fieldObjects)
reconstructPointFields() [2/4]
template<class Type > label reconstructPointFields (const IOobjectList & objects, const wordRes & selectedFields = wordRes())
reconstructAllFields()
Foam::label reconstructAllFields (const IOobjectList & objects, const wordRes & selectedFields = wordRes())
Definition at line 100 of file pointFieldReconstructor.C.
reconstructField() [2/2]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::pointPatchField, Foam::pointMesh > > reconstructField (const IOobject & fieldObject, const PtrList< GeometricField< Type, pointPatchField, pointMesh > > & procFields) const
Definition at line 28 of file pointFieldReconstructorTemplates.C.
References forAll, tmp< T >::New(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, PtrList< T >::set(), and UPtrList< T >::size().
reconstructPointField() [2/2]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::pointPatchField, Foam::pointMesh > > reconstructPointField (const IOobject & fieldObject)
Definition at line 115 of file pointFieldReconstructorTemplates.C.
References forAll, IOobjectOption::MUST_READ, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, and PtrList< T >::set().
reconstructPointFields() [3/4]
template<class Type > Foam::label reconstructPointFields (const UPtrList< const IOobject > & fieldObjects)
Definition at line 161 of file pointFieldReconstructorTemplates.C.
References Foam::endl(), Foam::Info, io(), IOobject::isHeaderClass(), IOobject::name(), Foam::nl, and write().
reconstructPointFields() [4/4]
template<class Type > Foam::label reconstructPointFields (const IOobjectList & objects, const wordRes & selectedFields)
Definition at line 196 of file pointFieldReconstructorTemplates.C.
References UPtrList< T >::empty().
Member Data Documentation
verbose_
int verbose_ = 1 static
Definition at line 131 of file pointFieldReconstructor.H.
The documentation for this class was generated from the following files:
src/parallel/reconstruct/reconstruct/pointFieldReconstructor.H
src/parallel/reconstruct/reconstruct/pointFieldReconstructor.C
src/parallel/reconstruct/reconstruct/pointFieldReconstructorTemplates.C