OpenFOAM: solidBodyMotionDisplacementPointPatchVectorField Class Reference
solidBodyMotionDisplacementPointPatchVectorField Class Reference
Enables the specification of a fixed value boundary condition using the solid body motion functions.
#include <solidBodyMotionDisplacementPointPatchVectorField.H>
Public Member Functions
TypeName ("solidBodyMotionDisplacement")
solidBodyMotionDisplacementPointPatchVectorField (const pointPatch &, const DimensionedField< vector, pointMesh > &)
solidBodyMotionDisplacementPointPatchVectorField (const pointPatch &, const DimensionedField< vector, pointMesh > &, const dictionary &)
solidBodyMotionDisplacementPointPatchVectorField (const solidBodyMotionDisplacementPointPatchVectorField &, const pointPatch &, const DimensionedField< vector, pointMesh > &, const pointPatchFieldMapper &)
solidBodyMotionDisplacementPointPatchVectorField (const solidBodyMotionDisplacementPointPatchVectorField &)
virtual autoPtr< pointPatchField< vector > > clone () const
solidBodyMotionDisplacementPointPatchVectorField (const solidBodyMotionDisplacementPointPatchVectorField &, const DimensionedField< vector, pointMesh > &)
virtual autoPtr< pointPatchField< vector > > clone (const DimensionedField< vector, pointMesh > &iF) const
const solidBodyMotionFunction & motion () const
const pointField & localPoints0 () const
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
Enables the specification of a fixed value boundary condition using the solid body motion functions.
Source files
solidBodyMotionDisplacementPointPatchVectorField.H
solidBodyMotionDisplacementPointPatchVectorField.C
Definition at line 49 of file solidBodyMotionDisplacementPointPatchVectorField.H.
Constructor & Destructor Documentation
solidBodyMotionDisplacementPointPatchVectorField() [1/5]
solidBodyMotionDisplacementPointPatchVectorField (const pointPatch & p, const DimensionedField< vector, pointMesh > & iF)
Definition at line 34 of file solidBodyMotionDisplacementPointPatchVectorField.C.
solidBodyMotionDisplacementPointPatchVectorField() [2/5]
solidBodyMotionDisplacementPointPatchVectorField (const pointPatch & p, const DimensionedField< vector, pointMesh > & iF, const dictionary & dict)
Definition at line 47 of file solidBodyMotionDisplacementPointPatchVectorField.C.
References dict, solidBodyMotionDisplacementPointPatchVectorField::localPoints0(), and Foam::transformPoints().
solidBodyMotionDisplacementPointPatchVectorField() [3/5]
solidBodyMotionDisplacementPointPatchVectorField (const solidBodyMotionDisplacementPointPatchVectorField & ptf, const pointPatch & p, const DimensionedField< vector, pointMesh > & iF, const pointPatchFieldMapper & mapper)
Definition at line 71 of file solidBodyMotionDisplacementPointPatchVectorField.C.
References solidBodyMotionDisplacementPointPatchVectorField::localPoints0(), and Foam::transformPoints().
solidBodyMotionDisplacementPointPatchVectorField() [4/5]
solidBodyMotionDisplacementPointPatchVectorField (const solidBodyMotionDisplacementPointPatchVectorField & ptf)
Definition at line 94 of file solidBodyMotionDisplacementPointPatchVectorField.C.
solidBodyMotionDisplacementPointPatchVectorField() [5/5]
solidBodyMotionDisplacementPointPatchVectorField (const solidBodyMotionDisplacementPointPatchVectorField & ptf, const DimensionedField< vector, pointMesh > & iF)
Definition at line 106 of file solidBodyMotionDisplacementPointPatchVectorField.C.
References solidBodyMotionDisplacementPointPatchVectorField::localPoints0(), and Foam::transformPoints().
Member Function Documentation
TypeName()
TypeName ("solidBodyMotionDisplacement")
clone() [1/2]
virtual autoPtr< pointPatchField< vector > > clone () const inline virtual
Definition at line 100 of file solidBodyMotionDisplacementPointPatchVectorField.H.
clone() [2/2]
virtual autoPtr< pointPatchField< vector > > clone (const DimensionedField< vector, pointMesh > & iF) const inline virtual
Definition at line 120 of file solidBodyMotionDisplacementPointPatchVectorField.H.
motion()
const solidBodyMotionFunction & motion () const inline
Definition at line 141 of file solidBodyMotionDisplacementPointPatchVectorField.H.
localPoints0()
const pointField & localPoints0 () const
Definition at line 130 of file solidBodyMotionDisplacementPointPatchVectorField.C.
References polyMesh::meshSubDir, IOobjectOption::MUST_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, and points0().
Referenced by solidBodyMotionDisplacementPointPatchVectorField::solidBodyMotionDisplacementPointPatchVectorField(), solidBodyMotionDisplacementPointPatchVectorField::solidBodyMotionDisplacementPointPatchVectorField(), solidBodyMotionDisplacementPointPatchVectorField::solidBodyMotionDisplacementPointPatchVectorField(), and solidBodyMotionDisplacementPointPatchVectorField::updateCoeffs().
updateCoeffs()
void updateCoeffs () virtual
Definition at line 155 of file solidBodyMotionDisplacementPointPatchVectorField.C.
References solidBodyMotionDisplacementPointPatchVectorField::localPoints0(), and Foam::transformPoints().
write()
void write (Ostream & os) const virtual
Definition at line 173 of file solidBodyMotionDisplacementPointPatchVectorField.C.
References Foam::indent(), os(), and valuePointPatchField< Type >::write().
The documentation for this class was generated from the following files:
src/dynamicMesh/motionSolvers/displacement/solidBody/pointPatchFields/derived/solidBodyMotionDisplacement/solidBodyMotionDisplacementPointPatchVectorField.H
src/dynamicMesh/motionSolvers/displacement/solidBody/pointPatchFields/derived/solidBodyMotionDisplacement/solidBodyMotionDisplacementPointPatchVectorField.C