OpenFOAM: turbGen Class Reference
turbGen Class Reference
Generate a turbulent velocity field conforming to a given energy spectrum and being divergence free.
#include <turbGen.H>
Public Member Functions
turbGen (const Kmesh &k, const scalar EA, const scalar K0)
vectorField U ()
Detailed Description
Generate a turbulent velocity field conforming to a given energy spectrum and being divergence free.
Source files
turbGen.H
turbGen.C
turbGenIO.C
Definition at line 51 of file turbGen.H.
Constructor & Destructor Documentation
turbGen()
turbGen (const Kmesh & k, const scalar EA, const scalar K0)
Definition at line 32 of file turbGen.C.
Member Function Documentation
U()
Foam::vectorField U ()
Definition at line 43 of file turbGen.C.
References Foam::ComplexField(), Foam::cos(), Ea(), Foam::Ek(), forAll, Foam::mag(), Foam::ReImSum(), fft::reverseTransform(), s(), Foam::sin(), Foam::sqrt(), and Foam::constant::mathematical::twoPi().
The documentation for this class was generated from the following files:
src/randomProcesses/turbulence/turbGen.H
src/randomProcesses/turbulence/turbGen.C