OpenFOAM: codedFunctionObject Class Reference
codedFunctionObject Class Reference
FunctionObjects » Utility function objects
Provides a general interface to enable dynamic code compilation.
#include <codedFunctionObject.H>
Public Member Functions
TypeName ("coded")
codedFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
virtual ~codedFunctionObject ()=default
functionObject & redirectFunctionObject () const
virtual bool execute ()
virtual bool write ()
virtual bool end ()
virtual bool read (const dictionary &)
Public Member Functions inherited from timeFunctionObject
timeFunctionObject (const word &name, const Time &runTime)
virtual ~timeFunctionObject ()=default
const Time & time () const
objectRegistry & storedObjects ()
const objectRegistry & storedObjects () const
Public Member Functions inherited from functionObject
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name, const bool withNamePrefix=defaultUseNamePrefix)
autoPtr< functionObject > clone () const
virtual ~functionObject ()=default
virtual const word & type () const =0
const word & name () const noexcept
bool useNamePrefix () const noexcept
bool useNamePrefix (bool on) noexcept
virtual bool execute (const label subIndex)
virtual bool adjustTimeStep ()
virtual bool filesModified () const
virtual void updateMesh (const mapPolyMesh &mpm)
virtual void movePoints (const polyMesh &mesh)
Public Member Functions inherited from codedBase
ClassName ("codedBase")
codedBase (const codedBase &)=delete
void operator= (const codedBase &)=delete
codedBase ()=default
virtual ~codedBase ()=default
Static Public Attributes
static constexpr const char *const codeTemplateC = "functionObjectTemplate.C"
static constexpr const char *const codeTemplateH = "functionObjectTemplate.H"
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
static bool defaultUseNamePrefix
static word outputPrefix
Protected Member Functions
virtual dlLibraryTable & libs () const
virtual string description () const
virtual void clearRedirect () const
virtual const dictionary & codeContext () const
virtual const dictionary & codeDict () const
virtual void prepare (dynamicCode &, const dynamicCodeContext &) const
codedFunctionObject (const codedFunctionObject &)=delete
void operator= (const codedFunctionObject &)=delete
Protected Member Functions inherited from timeFunctionObject
void clearOutputObjects (const wordList &objNames)
timeFunctionObject (const timeFunctionObject &)=delete
void operator= (const timeFunctionObject &)=delete
Protected Member Functions inherited from functionObject
word scopedName (const word &name) const
Protected Member Functions inherited from codedBase
dynamicCodeContext & codeContext ()
void setCodeContext (const dictionary &dict)
void append (const std::string &str)
void updateLibrary (const word &name, const dynamicCodeContext &context) const
void updateLibrary (const word &name, const dictionary &dict) const
void updateLibrary (const word &name) const
Protected Attributes
dictionary dict_
word name_
string codeData_
string codeRead_
string codeExecute_
string codeWrite_
string codeEnd_
autoPtr< functionObject > redirectFunctionObjectPtr_
Protected Attributes inherited from timeFunctionObject
const Time & time_
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &runTime, const dictionary &dict)
Public Attributes inherited from functionObject
bool log
Static Protected Member Functions inherited from codedBase
static void writeCodeDict (Ostream &os, const dictionary &dict)
static const dictionary & codeDict (const objectRegistry &obr, const word &dictName="codeDict")
Detailed Description
Provides a general interface to enable dynamic code compilation.
The entries are:
codeInclude : include files
codeOptions : compiler line: added to EXE_INC (Make/options)
codeLibs : linker line: added to LIB_LIBS (Make/options)
codeData : c++; local member data (default constructed)
localCode : c++; local static functions
codeRead : c++; upon functionObject::read()
codeExecute : c++; upon functionObject::execute()
codeWrite : c++; upon functionObject::write()
codeEnd : c++; upon functionObject::end()
codeContext : additional dictionary context for the code
Usage
Example of function object specification:
difference
{
    type coded;
    libs (utilityFunctionObjects);
    // Name of on-the-fly generated functionObject
    name writeMagU;
    codeWrite
    #{
        // Lookup U
        const volVectorField& U = mesh().lookupObject<volVectorField>("U");
        // Write
        mag(U)().write();
    #};
}
Note
The code context dictionary can be supplied separately as the codeContext entry.
See also
Foam::functionObject Foam::codedBase
Source files
codedFunctionObject.H
codedFunctionObject.C
Definition at line 136 of file codedFunctionObject.H.
Constructor & Destructor Documentation
codedFunctionObject() [1/2]
codedFunctionObject (const codedFunctionObject &) protected delete
codedFunctionObject() [2/2]
codedFunctionObject (const word & name, const Time & runTime, const dictionary & dict)
Definition at line 127 of file codedFunctionObject.C.
References codedFunctionObject::dict_, codedFunctionObject::name_, codedFunctionObject::read(), codedFunctionObject::redirectFunctionObject(), and codedBase::updateLibrary().
~codedFunctionObject()
virtual ~codedFunctionObject () virtual default
Member Function Documentation
libs()
Foam::dlLibraryTable & libs () const protected virtual
Implements codedBase.
Definition at line 50 of file codedFunctionObject.C.
References timeFunctionObject::time_.
description()
Foam::string description () const protected virtual
Implements codedBase.
Definition at line 56 of file codedFunctionObject.C.
References Foam::name().
clearRedirect()
void clearRedirect () const protected virtual
Implements codedBase.
Definition at line 62 of file codedFunctionObject.C.
codeContext()
const Foam::dictionary & codeContext () const protected virtual
Definition at line 69 of file codedFunctionObject.C.
References dictionary::findDict(), keyType::LITERAL, and dictionary::null.
codeDict()
const Foam::dictionary & codeDict () const protected virtual
Implements codedBase.
Definition at line 77 of file codedFunctionObject.C.
prepare()
void prepare (dynamicCode & dynCode, const dynamicCodeContext & context) const protected virtual
Implements codedBase.
Definition at line 83 of file codedFunctionObject.C.
References DetailInfo, Foam::endl(), dynamicCodeContext::libs(), dynamicCodeContext::options(), and dynamicCodeContext::sha1().
operator=()
void operator= (const codedFunctionObject &) protected delete
TypeName()
TypeName ("coded")
redirectFunctionObject()
Foam::functionObject & redirectFunctionObject () const
Definition at line 148 of file codedFunctionObject.C.
References functionObject::New(), Foam::nl, PtrList< T >::set(), and WarningInFunction.
Referenced by codedFunctionObject::codedFunctionObject().
execute()
bool execute () virtual
Implements functionObject.
Definition at line 182 of file codedFunctionObject.C.
write()
bool write () virtual
Implements functionObject.
Definition at line 189 of file codedFunctionObject.C.
end()
bool end () virtual
Reimplemented from functionObject.
Definition at line 196 of file codedFunctionObject.C.
read()
bool read (const dictionary & dict) virtual
Reimplemented from functionObject.
Definition at line 203 of file codedFunctionObject.C.
References codedBase::codeContext(), dict, Foam::endl(), IOWarningInFunction, Foam::nl, functionObject::read(), and codedBase::setCodeContext().
Referenced by codedFunctionObject::codedFunctionObject().
Member Data Documentation
dict_
dictionary dict_ protected
Definition at line 146 of file codedFunctionObject.H.
Referenced by codedFunctionObject::codedFunctionObject().
name_
word name_ protected
Definition at line 148 of file codedFunctionObject.H.
Referenced by codedFunctionObject::codedFunctionObject().
codeData_
string codeData_ protected
Definition at line 150 of file codedFunctionObject.H.
codeRead_
string codeRead_ protected
Definition at line 151 of file codedFunctionObject.H.
codeExecute_
string codeExecute_ protected
Definition at line 152 of file codedFunctionObject.H.
codeWrite_
string codeWrite_ protected
Definition at line 153 of file codedFunctionObject.H.
codeEnd_
string codeEnd_ protected
Definition at line 154 of file codedFunctionObject.H.
redirectFunctionObjectPtr_
autoPtr<functionObject> redirectFunctionObjectPtr_ mutable protected
Definition at line 157 of file codedFunctionObject.H.
codeTemplateC
constexpr const char* const codeTemplateC = "functionObjectTemplate.C" static constexpr
Definition at line 193 of file codedFunctionObject.H.
codeTemplateH
constexpr const char* const codeTemplateH = "functionObjectTemplate.H" static constexpr
Definition at line 197 of file codedFunctionObject.H.
The documentation for this class was generated from the following files:
src/functionObjects/utilities/codedFunctionObject/codedFunctionObject.H
src/functionObjects/utilities/codedFunctionObject/codedFunctionObject.C