OpenFOAM: enrichedPatch Class Reference
enrichedPatch Class Reference
The enriched patch contains a double set of faces from the two sides of the sliding interface before the cutting.
#include <enrichedPatch.H>
Public Member Functions
ClassName ("enrichedPatch")
enrichedPatch (const primitiveFacePatch &masterPatch, const primitiveFacePatch &slavePatch, const labelUList &slavePointPointHits, const labelUList &slavePointEdgeHits, const UList< objectHit > &slavePointFaceHits)
~enrichedPatch ()=default
const Map< point > & pointMap () const
Map< point > & pointMap ()
const Map< label > & pointMergeMap () const
Map< label > & pointMergeMap ()
void calcEnrichedFaces (const labelListList &pointsIntoMasterEdges, const labelListList &pointsIntoSlaveEdges, const pointField &projectedSlavePoints)
const faceList & enrichedFaces () const
const labelList & meshPoints () const
const faceList & localFaces () const
const pointField & localPoints () const
const labelListList & pointPoints () const
const Map< labelList > & masterPointFaces () const
const faceList & cutFaces () const
const labelList & cutFaceMaster () const
const labelList & cutFaceSlave () const
bool checkSupport () const
void writeOBJ (const fileName &fName) const
Detailed Description
The enriched patch contains a double set of faces from the two sides of the sliding interface before the cutting.
The patch basically consists of two over-lapping sets of faces sitting on a common point support, where every edge may be shared by more than 2 faces. The patch points are collected in a map. Additional information needed for cutting is the point insertion into every edge of master and slave.
Note: If new points are created during master-slave edge cutting, they should be registered with the pointMap.
Source files
enrichedPatch.H
enrichedPatch.C
enrichedPatchCutFaces.C
enrichedPatchFaces.C
enrichedPatchPointMap.C
enrichedPatchPointMergeMap.C
enrichedPatchPointPoints.C
Definition at line 64 of file enrichedPatch.H.
Constructor & Destructor Documentation
enrichedPatch()
enrichedPatch (const primitiveFacePatch & masterPatch, const primitiveFacePatch & slavePatch, const labelUList & slavePointPointHits, const labelUList & slavePointEdgeHits, const UList< objectHit > & slavePointFaceHits)
Definition at line 123 of file enrichedPatch.C.
~enrichedPatch()
~enrichedPatch () default
Member Function Documentation
ClassName()
ClassName ("enrichedPatch")
pointMap() [1/2]
const Foam::Map< Foam::point > & pointMap () const inline
Definition at line 23 of file enrichedPatchI.H.
Referenced by enrichedPatch::calcEnrichedFaces().
pointMap() [2/2]
Foam::Map< Foam::point > & pointMap () inline
Definition at line 34 of file enrichedPatchI.H.
pointMergeMap() [1/2]
const Foam::Map< Foam::label > & pointMergeMap () const inline
Definition at line 45 of file enrichedPatchI.H.
Referenced by enrichedPatch::calcEnrichedFaces().
pointMergeMap() [2/2]
Foam::Map< Foam::label > & pointMergeMap () inline
Definition at line 51 of file enrichedPatchI.H.
calcEnrichedFaces()
void calcEnrichedFaces (const labelListList & pointsIntoMasterEdges, const labelListList & pointsIntoSlaveEdges, const pointField & projectedSlavePoints)
Definition at line 32 of file enrichedPatchFaces.C.
References Foam::abort(), PtrList< T >::append(), enrichedPatch::checkSupport(), e, Foam::endl(), enrichedPatch::enrichedFaces(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::Info, Foam::magSqr(), Foam::max(), Foam::min(), Foam::nl, enrichedPatch::pointMap(), enrichedPatch::pointMergeMap(), UPtrList< T >::size(), and PtrList< T >::transfer().
enrichedFaces()
const Foam::faceList & enrichedFaces () const
Definition at line 380 of file enrichedPatchFaces.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Referenced by enrichedPatch::calcEnrichedFaces().
meshPoints()
const Foam::labelList & meshPoints () const
Definition at line 158 of file enrichedPatch.C.
localFaces()
const Foam::faceList & localFaces () const
Definition at line 169 of file enrichedPatch.C.
localPoints()
const Foam::pointField & localPoints () const
Definition at line 180 of file enrichedPatch.C.
pointPoints()
const Foam::labelListList & pointPoints () const
Definition at line 191 of file enrichedPatch.C.
masterPointFaces()
const Foam::Map< Foam::labelList > & masterPointFaces () const
Definition at line 96 of file enrichedPatchMasterPoints.C.
cutFaces()
const Foam::faceList & cutFaces () const
Definition at line 648 of file enrichedPatchCutFaces.C.
cutFaceMaster()
const Foam::labelList & cutFaceMaster () const
Definition at line 659 of file enrichedPatchCutFaces.C.
cutFaceSlave()
const Foam::labelList & cutFaceSlave () const
Definition at line 670 of file enrichedPatchCutFaces.C.
checkSupport()
bool checkSupport () const
Definition at line 202 of file enrichedPatch.C.
References Foam::endl(), forAll, and WarningInFunction.
Referenced by enrichedPatch::calcEnrichedFaces().
writeOBJ()
void writeOBJ (const fileName & fName) const
Definition at line 229 of file enrichedPatch.C.
References f(), Foam::nl, and Foam::meshTools::writeOBJ().
The documentation for this class was generated from the following files:
src/dynamicMesh/slidingInterface/enrichedPatch/enrichedPatch.H
src/dynamicMesh/slidingInterface/enrichedPatch/enrichedPatch.C
src/dynamicMesh/slidingInterface/enrichedPatch/enrichedPatchCutFaces.C
src/dynamicMesh/slidingInterface/enrichedPatch/enrichedPatchFaces.C
src/dynamicMesh/slidingInterface/enrichedPatch/enrichedPatchI.H
src/dynamicMesh/slidingInterface/enrichedPatch/enrichedPatchMasterPoints.C
src/dynamicMesh/slidingInterface/enrichedPatch/enrichedPatchPointMap.C
src/dynamicMesh/slidingInterface/enrichedPatch/enrichedPatchPointPoints.C